### ISSUE TITLE
the _exit_tree signal emitted before its children's.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#28633]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

In 3.0 and before, the _exit_tree of a node is called after all of its children have left the tree.
However in 3.1 the order is inverted.Please check the scene file, the output should be:
Child2	exit tree
Child1	exit tree
root exit tree

But in 3.1 its output is:
root exit tree
Child1	exit tree
Child2	exit tree

**Steps to reproduce:**

**Minimal reproduction project:**
[Archive.zip](https://github.com/godotengine/godot/files/3140599/Archive.zip)

**Comment by avencherus** [comment]
Confirmed in c50ab02 as well.

**Comment by hilfazer** [comment]
Possibly intended.

_exit_tree() callback corresponds to _tree_exit**ing** signal. There's another signal - _tree_exit**ed** that is called after Node left the tree.

Child's _exit_tree() is called before parent's. But in your example you're connecting not to _tree_exiting, but to _tree_exited of a child.

Still, it can be a bug because docs say this:

> If the node has children, its _exit_tree callback will be called last, after all its **children have left the tree**.

It suggests that parent's _exit_tree()/tree_exiting gets called after children's tree_exited.

**Comment by Hubber116sx** [comment]
If that is true I have to wonder why you would need a tree_exiting signal _and_ a tree_exited signal. tree_exiting would be much more useful if it was called from top to bottom while tree exited was called from bottom to top, but that's just my opinion.

**Comment by tom-jk** [comment]
Testing on linux mint 18.3.
Can reproduce observed behaviour.

It seems to me that maybe the `_exit_tree()` function should be renamed `_exiting_tree()` to avoid confusion? Considering there are `exited` and `exiting` signals, and the function corresponds to exiting, not exited - the name is somewhat ambiguous.

@blaze-the-star Both signals have merit. `exiting` is for any destructor behaviour the node needs; `exited` is for when it's actually gone (the docs - [3.0](https://docs.godotengine.org/en/3.0/classes/class_node.html#signals) / [3.1](https://docs.godotengine.org/en/3.1/classes/class_node.html#signals) / [3.2](https://docs.godotengine.org/en/3.2/classes/class_node.html#signals) - also say this). For example, if say there was some thing that there must always be one of and never two, you might clean up the outgoing one in `exiting` and make a new one in `exited`.

----

**a more complete test**

Replace Root.gd script with this:

```gdscript
extends Node2D

func _ready():
	connect("tree_exited", self, "_on_Root_tree_exited")
	connect("tree_exiting", self, "_on_Root_tree_exiting")
	for child in get_children():
		child.connect("tree_exited", self, "on_child_tree_exited", [child])
		child.connect("tree_exiting", self, "on_child_tree_exiting", [child])
	yield(get_tree().create_timer(1),"timeout")
	queue_free()

func _exit_tree():
	prints("root   _exit_tree()")

func _on_Root_tree_exited():
	prints("root   exit tree signal")

func _on_Root_tree_exiting():
	prints("root   exiting tree signal")

func on_child_tree_exited(child):
	prints(child.name, "exit tree signal")

func on_child_tree_exiting(child):
	prints(child.name, "exiting tree signal")
```

And add this script to both children as Child.gd:

```gdscript
extends Node2D

func _exit_tree():
	prints(self.name, "_exit_tree()")
```

Produces this output in 3.0:

```
Child2 _exit_tree()
Child2 exiting tree signal
Child2 exit tree signal
Child1 _exit_tree()
Child1 exiting tree signal
Child1 exit tree signal
root   _exit_tree()
root   exiting tree signal
root   exit tree signal
```

And produces this output in 3.1 and 3.2.3.rc3:

```
Child2 _exit_tree()
Child2 exiting tree signal
Child1 _exit_tree()
Child1 exiting tree signal
root   _exit_tree()
root   exiting tree signal
Child1 exit tree signal
Child2 exit tree signal
root   exit tree signal
```

Neither way is strictly right or wrong, just different. I guess the 3.1+ way allows siblings to communicate during destructor-ing, which they couldn't do prior (except in a specific order, which might work for you by luck sometimes then fail seemingly at random) - in that sense it's an improvement?

**Comment by KoBeWi** [comment]
Here's a result that also includes `NOTIFICATION_EXIT_TREE`:
```
_exit_tree Child3
tree_exiting Child3
NOTIFICATION_EXIT_TREE Child3
_exit_tree Child2
tree_exiting Child2
NOTIFICATION_EXIT_TREE Child2
_exit_tree Child1
tree_exiting Child1
NOTIFICATION_EXIT_TREE Child1
_exit_tree Root
tree_exiting Root
NOTIFICATION_EXIT_TREE Root
tree_exited Child1
tree_exited Child2
tree_exited Child3
tree_exited Root
```
