### ISSUE TITLE
Cannot build master branch

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#28634]
**Godot version:**
Master

**OS/device including version:**
Ubuntu 16.04 

**Issue description:**
When building master, I get errors while compiling editor/plugins/visual_shader_editor_plugin.cpp
On all the lines with ``Shader::Mode`` I get the error: `'Shader::Mode' is not a class or namespace`

It looks like travis-ci is building fine. But im consistently getting errors. 

@Chaosus Do you have any idea what might cause this? Could it be caused by https://github.com/godotengine/godot/pull/28571?

**Comment by avencherus** [comment]
If it helps.  As of c50ab02 on Windows 10 with a 64-bit VS2017 build, I didn't encounter it.

**Comment by clayjohn** [comment]
Thanks! I was just able to successfully build on my windows machine too. I can't figure out why I would be having problems.

**Comment by Chaosus** [comment]
That's strange, it's still happens on Ubuntu ?

**Comment by Chaosus** [comment]
Ah.. probably it's not okay to call a full "Shader::Mode::" - need to call just a "Shader::" - will fix it now

**Comment by clayjohn** [comment]
That PR worked. Thanks!
