### ISSUE TITLE
Text in scrollbars.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#28637]
**Godot version:**

c50ab02e4ceb1517f3a87a7bac82967ba1e6e2a9

**OS/device including version:**

Win10 64bit

**Issue description:**

Noticed in the script editor that the text can intersect with the scrollbars.  Not sure if this is the intention, as these things typically don't bleed content into each other.

![image](https://user-images.githubusercontent.com/13004169/57123717-6e4e0780-6d8b-11e9-96eb-ab56c7e6e114.png)

**Comment by groud** [comment]
I think this expected. Here is a screenshot of a small Firefox window:
![2019-05-03-111651_823x308_scrot](https://user-images.githubusercontent.com/6093119/57128880-14523f80-6d95-11e9-9f4c-d377ad689329.png)
INCEPTIOOOOOON ! :p

**Comment by avencherus** [comment]
Yeah, not sure what the norm is per platform/setup.

Here's mine.

Chrome Windows
![image](https://user-images.githubusercontent.com/13004169/57147301-ef2ef280-6dcf-11e9-872f-fc6e241e3309.png)

Firefox Windows
![image](https://user-images.githubusercontent.com/13004169/57147361-1259a200-6dd0-11e9-86b1-0effe0a1d257.png)
