### ISSUE TITLE
Method hint in IDE does not work when wrapped in 'str'

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#28630]
**Godot version:**
3.1

**OS/device including version:**
Any, but in this last instance I was on Linux Mint 19.1

**Issue description:**
In the Godot IDE the 'Intellisense' feature fails when you use classes inside built in functions.

In the code editor when I type this: Engine.g

I get all Engine methods as expected drop down (in my case I wanted 'get_frames_per_second')

If I type: str(Engine.

I get no offers of help. So every time I want to use the intellisense help I have to type my commands on a brand new line to find the methods I want, then move it back to where I want it.

**Comment by clayjohn** [comment]
Are you using Godot's text editor or Visual Studio? I'm guessing you are talking about Godot, but it is unclear because intellisense is the name of Visual Studios code completion software. Please clarify.

**Comment by neilw1** [comment]
Sorry, yes it's the main Godot IDE. I didn't know a better word than 'intellisense'.

**Comment by ThakeeNathees** [comment]
this issue has been fixed and should be closed

**Comment by Calinou** [comment]
Closing per @ThakeeNathees's comment.
