### ISSUE TITLE
TCP_Server send "1" and client receives "��1"

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2863]
When I send a string("1") the receiver(client) gets 1 what are these strange symbols?

I used 
https://github.com/Kermer/Godot/wiki/tut_data-transfer
https://github.com/Kermer/Godot/wiki/tut_connection

Is it a bug? Am I doing something wrong?

Tested with socat and browser both the same.

**Comment by bojidar-bg** [comment]
@AlexHolly I guess you are sending the data through PacketPeerStream and receiving it directly through StreamPeerTCP (or even directly through some other program), right?

Because PacketPeerStream is able to send things other than strings (like numbers, dictionaries, etc.), it adds some information disambiguating between them, as explained [in the wiki](http://www.godotengine.org/projects/godot-engine/wiki/Binary_serialization_API).

If you want to, say, host an HTTP or TCP server in Godot for consumption from other programs, you should use StreamPeer::put_data() instead of PacketPeer::put_var()

**Comment by AlexHolly** [comment]
Thanks pointing this out.

I'm still not able to get it running. How can I bind the client to a StreamPeer?

PacketPeerStream
```peerstream[ index ].set_stream_peer( client )```

There is no StreamPeerStream class... and StreamPeer has no set_stream_peer function.

In the wiki I can only see how to use PacketPeerStream but not StreamPeer(Stream)
Maybe some more doku on this topic would help others too.

**Comment by reduz** [comment]
I think StreamPeer has not many functions to get and send raw data, those
should be added eventually. If you are writing your own server on the other
hand, you can use PacketPeer and use the format documented for it in the
wiki:

https://github.com/godotengine/godot/wiki/binary_Serialization

**Comment by est31** [comment]
@AlexHolly you have to chose whether to communicate low level or high level. If you send high level and you receive low level, you get the behaviour described in the bug report.

* Classes representing low level communication are: StreamPeer, StreamPeerTCP, 

* Classes representing high level communication are: PacketPeer, PacketPeerStream

If you have a low level class, you can use a PacketPeerStream to use it for high level communication.
If you have a high level class, you can't make it low level.
Yes, in the docs of PacketPeer it mentions the word "udp", so people might think this is low level. But it isn't. You can solely use it for high level communication (aka using the godot serialisation format).

> I'm still not able to send a string I get "cannot convert argument 1 from string to rawArray"

To convert a string to a rawArray, you'll have to use the to_utf8() method of the String class. If you are getting that error, you most likely want to use the `put_data` function of StreamPeer, so the low level protocol. I don't think you want to do this. There are multiple problems connected to it. The largest one is that you have to know the size of the transmitted message at the receiving side. If you use the high level protocol, godot takes care of that for you by sending the size of every packet at the start of each packet.

So you should tunnel everything through PacketPeerStream. Just use its  set_stream_peer method to bind it to the StreamPeer on both sides.

**Comment by AlexHolly** [comment]
I need a websocket in godot so that I can give the client(maybe a browser) a pure http text response without any godot overhead.
I made a function(put_text) for it.

The next step would be to implement the parsing of the incoming http requests, most of the parsing is already implemented inside http_client. Maybe someone could make the parsing more abstract to make it more easy implementing a websocket.

I will try to implement a quick solution in .gd to get things running I don't need a clean solution right now.

Maybe I miss something and there is already a solution for it.

**Comment by est31** [comment]
Just use `put_data("text".to_utf8())` then. put_text isn't needed.

**Comment by AlexHolly** [comment]
That is what I was looking for, thanks!
I think there is no documentation for it.
 - I can't see to_utf8() in the string class. 
 -An example to to send non serialized data would be nice.

**Comment by est31** [comment]
The method is very young, and the online docs only update every stable version or so. The docs from inside the editor are recent though (script tab then click "Classes" or "Search Help").

**Comment by est31** [comment]
And #2898 has improved the docs for to_utf8() (from mention to additional text).

**Comment by akien-mga** [comment]
Actually the online API reference was never updated I believe, it's still from pre-open source Godot code.

**Comment by akien-mga** [comment]
So if I understand correctly, the initial issue has a solution already, but it is not well documented enough on the online wiki. The API reference being outdated is a more global issue so we probably don't need to keep this issue open for it, on the other hand is there a need to improve/write a doc wiki page to mention this to_utf8() method?

**Comment by AlexHolly** [comment]
Yes I would like to see a documenation on how to communicate with another non godot system. It is basically a documentation of this issue.

**Comment by reduz** [comment]
need to add a low level API to streampeer
will work on this now

**Comment by AlexHolly** [comment]
Nice, will it also support #3057?
