### ISSUE TITLE
Issues with the tiles.

### ISSUE THREAD

**Issue by DegradedMind** [godotengine/godot#28647]
**Godot version:**
3.1.1

**Issue description:**
I don't seem to find and get an answer on Godot Q&A so I came here. Sorry.

In the editor: https://youtu.be/kwuRHCPe6Yg

Same. but zoomed in: https://youtu.be/fmDZ1dY3MN4

The issue is also present while playing the scene:
https://youtu.be/-MhwhRdwlUw

https://i.ibb.co/x7TtfGm/blinder.jpg

I am using a tileset. 
My tiles are 32x32.
Pixel Snap is disabled.
Camera2D: https://youtu.be/EFwz7x5NZyU

**Comment by Zylann** [comment]
Isn't that moire because the renderer is using nearest filter (i.e no smoothing, a.k.a pixel-arty) to display your tiles at lower size on screen?

**Comment by DegradedMind** [comment]
@Zylann, on the third video there is something happening with the tiles while moving. I don't know how this is called. They are kinda blinking. The screenshot shows a frame from the video.

**Comment by bojidar-bg** [comment]
Potentially related to #1682 (haven't watched the videos)

**Comment by DegradedMind** [comment]
@bojidar-bgm, it seems that enabling pixel snap solves the issue.

**Comment by Zylann** [comment]
@DegradedMind I think it's "Moire", you can see this effect if you try to render a texture with sharp vertical or horizontal shapes at a different scale on your screen, because depending on your camera floating position (which could be "between pixels") some of the shapes would end up be drawn with one less row or column of pixels.

**Comment by DegradedMind** [comment]
@Zylann, oh, now I get it. Thank you for explaining.

**Comment by DegradedMind** [comment]
@Zylann, just noticed that it still happens even with pixel snap on if the game is on full screen.

**Comment by DegradedMind** [comment]
@Nevermind. It happens if the window is maximized, not if the game is fullscreen.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/46681 and related issues.
