### ISSUE TITLE
Complete tscn and tres parser

### ISSUE THREAD

**Issue by Gfurst** [godotengine/godot#2864]
Hey folks, just creating the issue for the task: http://www.godotengine.org/work_packages/5
So we can keep track and communicate on whatever development happens.

**Comment by reduz** [comment]
alright, I'm working o that atm

**Comment by akien-mga** [comment]
Fixed in #7aa39b7. There are still a couple issues with the new parser, but they have their own tickets so there's no real need for a tracker bug.
