### ISSUE TITLE
video stream gdnative crashes when num audio channels is 0

### ISSUE THREAD

**Issue by underdoeg** [godotengine/godot#28644]
**Godot version:**
3.1

**OS/device including version:**
probably any OS

**Issue description:**
if the gdnative video stream implementation return 0 from get_channels. No mixer_callback is set and the application segfaults.

Probably the implementation is missing this 
https://github.com/godotengine/godot/blob/12cc760538fbec37199dcc24098d942ac1d623b8/modules/theora/video_stream_theora.cpp#L430

at this location
https://github.com/godotengine/godot/blob/a342131eba2834240289112a1b8d5d0c68a265c9/modules/gdnative/videodecoder/video_stream_gdnative.cpp#L149

I might be able to put together a PR but not at the moment. So I just add this as a reminder / invitation.

**Comment by akien-mga** [comment]
CC @KidRigger
