### ISSUE TITLE
MacOS: Screen turns red when moving editor window from Retina Display to different monitor.

### ISSUE THREAD

**Issue by MattRCole** [godotengine/godot#28651]
**Godot version:**

v3.1.stable.mono.official

**OS/device including version:**

macOS Mojave 10.14.4 (18E226) . 

    Intel UHD Graphics 630:

      Chipset Model: Intel UHD Graphics 630
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x3e9b
      Revision ID: 0x0000
      Automatic Graphics Switching: Supported
      gMux Version: 5.0.0
      Metal: Supported, feature set macOS GPUFamily2 v1

    Radeon Pro 560X:

      Chipset Model: Radeon Pro 560X
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x8
      VRAM (Total): 4 GB
      Vendor: AMD (0x1002)
      Device ID: 0x67ef
      Revision ID: 0x00c2
      ROM Revision: 113-C980AL-075
      VBIOS Version: 113-C97501U-005
      EFI Driver Version: 01.01.075
      Automatic Graphics Switching: Supported
      gMux Version: 5.0.0
      Metal: Supported, feature set macOS GPUFamily2 v1
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2880 x 1800 Retina
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No

**Issue description:**

When moving editor from Retina display to non-retina display:
 - What happened: The editor window appears to be overlaid in red.
 - What was expected: The editor window to not turn red.

**Steps to reproduce:**
 1. Start Godot on Retina Display
 2. Start Project and open Editor on Retina Display
 3. Move Editor from Retina Display to non-Retina Display

**Minimal reproduction project:**

This shouldn't matter. Any project should work.

**Comment by bheesham** [comment]
This issue went away for me when I upgraded to Godot v3.2.1.

Note: I'm running MacOS Catalina (10.15.3).

**Comment by Calinou** [comment]
@bheesham Thanks for testing whether this bug is still present :slightly_smiling_face: 

I'll consider it resolved then. If anyone else can reproduce this issue on Godot 3.2.1 or later, please comment and I'll reopen it.
