### ISSUE TITLE
TabContainer's "set_tab_icon" don't change the icon immediately

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#28655]
**Godot version:**
Godot_v3.1.1-stable_win64

**OS/device including version:**
Windows 10

**Issue description:**
The method `set_tab_icon` of the `TabContainer` control does not update the icon immediately, you need to interact with the tab to change the icon.

**Steps to reproduce:**
Call `set_tab_icon` in a `TabContainer` and note that nothing happens, then interact with the tab and see that the icon suddenly changes.

**Minimal reproduction project:**
[TabContainer_set_tab_icon.zip](https://github.com/godotengine/godot/files/3142935/TabContainer_set_tab_icon.zip)

___

In the **Minimal reproduction project** I have called `set_tab_disabled(child_index, false)` after setting the icon to make it change.

**Comment by YeldhamDev** [comment]
Just checked, it doesn't call `update()` after being set, same with `set_tab_title()`, should be a easy fix.

**Comment by felaugmar** [comment]
😊👌
