### ISSUE TITLE
CSGMesh messing up normals

### ISSUE THREAD

**Issue by TheSHEEEP** [godotengine/godot#28661]
**Godot version:**
3.1.1

**OS/device including version:**
Ubuntu 18.04
GeForce GTX 1070, NVIDIA 418.56

**Issue description:**
I am using [gdprocmesh](https://github.com/BastiaanOlij/gdprocmesh) to create a MeshArray consisting of two surfaces (each with a different material). I assign a SpatialShader to both surfaces and enable triplanar mapping. This works and renders just fine.

However, when I copy and paste the MeshArray into a CSGMesh, it seems to mess up the UVs somehow, probably best explained with an image (the CSGMesh with a hole cut out by a CSGCylinder is on the left side):
![Screenshot from 2019-05-03 14-04-12](https://user-images.githubusercontent.com/1766205/57165400-a8f18780-6dff-11e9-84d2-d782858512bf.png)
As you can see, where the CSGMesh becomes cut out by a CSGCylinder, the wall actually looks better. At first I thought this was a problem with the display of the CSGMesh in the editor (as that tends to show a blue wireframe on top of the actual mesh), but it is just the same when viewed in the final scene.

Also note that only the walls seem to show this problem, the ground box is fine.
I'm not sure what causes this problem, but I assume it is related to UVs (certainly looks like it, anyway). All I do know is that I expected the CSGMesh to look exactly like the original MeshArray, but it doesn't.

I also created an issue for this on the gdprocmesh repo, but I assume (and Bastiaan seems to agree) that gdprocmesh isn't to blame here.
Given that the original MeshArray renders fine, but the same mesh "used" in a CSGMesh doesn't, this seems to be a logical assumption?

**Steps to reproduce:**
See above. But it is probably best reproduced using the project below.

**Minimal reproduction project:**
Here is the project (only tested on linux so far, but it probably makes no difference):
[procmeshtest.zip](https://github.com/godotengine/godot/files/3143556/procmeshtest.zip)

**Comment by TheSHEEEP** [comment]
If any more input to this is needed from my side, feel free to ask. I am very interested in getting this fixed ASAP, as it is an important part of my own project.

**Comment by TheSHEEEP** [comment]
I played around a bit more with the SpatialMaterial assigned to the mesh.
To my surprise, when disabling triplanar mapping, both meshes now look identical (as far as I can tell anyway):
![Screenshot from 2019-05-08 10-46-31](https://user-images.githubusercontent.com/1766205/57358658-96b87600-717e-11e9-9802-684e596520b6.png)

Now this got me thinking. My initial assumption that CSGMesh messes with UVs is likely wrong. After all, triplanar mapping typically ignores an object's UV coordinates entirely, as its entire point is to be applied to geometry that isn't possible to UV-map properly (like procedurally generated geometry).
And since both meshes look identical with triplanar mapping disabled, the UVs are most likely identical, too.

However, what is it that makes the triplanar mapping mess up when applied to the source of a CSGMesh, but not with the actual mesh itself? I still think there is a bug here, but I don't know any more what kind of bug that could be.

**Comment by TheSHEEEP** [comment]
A new theory has come up in the Godot Discord:
gdprocmesh produces normals that are somehow broken - this might explain why the top/bottom/start/end of the walls on the mesh generated are broken (the right mesh on the original image). But the rest of the mesh looks fine.
However, when used as a source for CSGMesh, these broken normals somehow mess up with the CSG builder, resulting in the different look. After all, for triplanar mapping, the normals, instead of the UVs, are used for the texturing - so it would make sense that the difference between both meshes are the normals.

Could this be the issue?

**Comment by TheSHEEEP** [comment]
This "normals are the problem"-theory has got me thinking and at least I found a workaround:
I added more vertices to the shape that gets extruded to form the walls (this is gdprocmesh stuff). These new vertices seem to have made sure that all the faces get proper normals both in the original mesh and that mesh used as source for CSGMesh.
![Screenshot from 2019-05-08 14-07-28](https://user-images.githubusercontent.com/1766205/57371615-d9d51200-719b-11e9-81e4-815304d2106d.png)
You can still see a small rendering error on the leftmost side (where the wall "starts"), but this workaround is "good enough" to continue with my project until the underlying bug is fixed.

I still think there is a bug here, either in gdprocmesh not generating proper normals or CSGMesh messing up normals under certain conditions.

**Comment by hoontee** [comment]
`gdprocmesh` was creating normals with custom vectors (right):
![image](https://user-images.githubusercontent.com/5272529/89136951-ba8e7700-d4fb-11ea-8dd9-c5dd18aa9f13.png)
It may look good, but it's totally incompatible with CSG (left). All normal vectors get discarded in favor of `smooth` or `flat` faces, so this issue would probably do better as a feature proposal.

**Comment by Calinou** [comment]
Closing per @hoontee's comment.
