### ISSUE TITLE
collisions  when staticbdy2d is a child of parallaxlayer

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2866]
seems that it is not possible to collide with one staticbody that it is a child of an parallaxlayer.
looks my sample project: http://www.filedropper.com/tappyplane
as you can see the airplane goes through the ground.

**Comment by akien-mga** [comment]
I can confirm the bug using the above sample project; when changing the ParallaxLayer nodes to Node2D, the collisions do happen properly, so there's a problem with ParallaxLayer.

**Comment by reduz** [comment]
yes, this will not work and can't be fixed, parallax layer is drawn this way using mirroring, and this won't extend to the physics. You should probably look for an alternate way of doing this
