### ISSUE TITLE
NativeScript static functions and constants

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#28668]
**Godot version:**
Godot_v3.1.1-stable_win64

**Issue description:**
The current status of **GDNative** does not allow you to register **static functions** or **constants** in GDNative classes and use **NativeScript** to access them.

The equivalent in GDScript would be:
<details>
<summary>GDScript </summary>
<p>

> Static functions

``` gdscript
static func hello_world() -> void:
    print('Hello World!')
```

> Constants

``` gdscript
const HELLO_WORLD_STR := 'Hello World!'
```

</p>
</details>

**Comment by Calinou** [comment]
GDNative has been removed in favor of GDExtension in 4.0, closing.

Besides, the Godot API does not allow binding static functions in 3.x, so this can't be implemented there.
