### ISSUE TITLE
GDScript (int-float arithmetic?) behaves differently in release mode

### ISSUE THREAD

**Issue by gdelazzari** [godotengine/godot#28663]
**Godot version:** v3.1.stable.official and v3.1.1.stable.official
**OS/device including version:** Arch Linux 64bit, but shouldn't care (see issue description)

**Issue description:**
I should have narrowed down the problem enough... may not be the full story, but this is what's happening to me:

if a script has a variable (as a member, declared in its "global" space - i.e. not inside a function) of type int and I try to subtract a float value from it, the value doesn't get updated **only** when the project is exported in Release mode. I tested this on Linux and Android exports, so this shouldn't tied to my system. I also tried setting the script export mode to "Text" instead of "Compiled" without any luck.

This doesn't happen with a variable local to the function or with an int-int subtraction (i.e. if I subtract an int value from the script variable, it also works in Release mode)

**Steps to reproduce:**
I'll attach a minimal project where this happens, but without having you download and open it, this is the script I used:
```GDScript
extends Control

var own_value : int = 100

func console_print(text):
	print(text)
	$Label.text += text + "\n"

func myfunc(amount : float):
	self.own_value -= amount

func _on_Button_pressed():
	self.console_print("")

	var value : int = 100
	var amount : float = 5.0

	self.console_print("value=" + str(value))
	self.console_print("amount=" + str(amount))
	self.console_print("doing value -= amount")
	value -= amount
	self.console_print("value=" + str(value))

	self.console_print("own_value=" + str(own_value))
	self.console_print("doing own_value -= amount")
	self.own_value -= amount
	self.console_print("own_value=" + str(own_value))

	self.console_print("calling myfunc(amount : float)")
	self.myfunc(amount)
	self.console_print("own_value=" + str(own_value))

	var int_amount : int = 10
	self.console_print("int_amount=" + str(int_amount))
	self.console_print("calling myfunc(int_amount : int)")
	self.myfunc(int_amount)
	self.console_print("own_value=" + str(own_value))

	self.console_print("doing own_value -= int_amount")
	self.own_value -= int_amount
	self.console_print("own_value=" + str(own_value))

	self.console_print("setting own_value to 200")
	self.own_value = 200
	self.console_print("own_value=" + str(own_value))
```

The output in debug mode:
```
value=100
amount=5
doing value -= amount
value=95
own_value=100
doing own_value -= amount
own_value=95
calling myfunc(amount : float)
own_value=90
int_amount=10
calling myfunc(int_amount : int)
own_value=80
doing own_value -= int_amount
own_value=70
setting own_value to 200
own_value=200
```

And the output in release mode:
```
value=100
amount=5
doing value -= amount
value=95
own_value=100
doing own_value -= amount
own_value=100
calling myfunc(amount : float)
own_value=100
int_amount=10
calling myfunc(int_amount : int)
own_value=100
doing own_value -= int_amount
own_value=90
setting own_value to 200
own_value=200
```

You can clearly see it's behaving differently and wrongly in release mode, the value is not updated.

To reproduce with the project... run with F5 for Debug mode or add an export profile for whatever platform, ensure "Export with Debug" is off and run... I mean I don't think I should be telling you guys this, but just in case... :smile: 

**Minimal reproduction project:**
[GDScriptReleaseIssue.zip](https://github.com/godotengine/godot/files/3143759/GDScriptReleaseIssue.zip)

**Comment by avencherus** [comment]
Was able to reproduce for Win10 64-bit Editor/Release builds of 84401e8

**Comment by johngirvin** [comment]
I think I have the same issue with int/float in Release mode.
Posting this for further clarification.

**Godot version:**
v3.1.1.stable.official

**OS/device:**
macOS 64-bit 10.13 and 10.14

**Issue description:**
In a Release export the label displays "99" instead of the expected "100" (the constant values are not relevant).
```
extends Node2D

class V:
	var x : int = 99

var _v1 : V = V.new()

func _ready():
	_v1.x = 100

	find_node('Label').text = str(_v1.x)
	return
```

Any of the following work around the issue to display "100" in both Debug and Release exports:
- change constant `100` to `100.0`
- change type of `V.x` to `int`
- use a `float` for `_v1` instead of a class type

**Minimal reproduction project:**
[28663_repro.zip](https://github.com/godotengine/godot/files/3531753/28663_repro.zip)
