### ISSUE TITLE
Proposal: Signal connected to method with incorrect number of arguments should break application

### ISSUE THREAD

**Issue by pgoral** [godotengine/godot#28671]
**Godot version:**  84401e8cdf4f41fc0e804bf5410622e75a08c0f5

**Issue description:**
Currently there is only message thrown in Godot's console "ERROR: Object::emit_signal: Error calling method from signal 'completed': 'Sprite(GameBoard.gd)::_on_quest_compleated': Method expected 0 arguments, but called with 1.
   At: core\object.cpp:1242"
  
but it can be unnoticed. Maybe application should break to debbuger instead.
This issue should be considered also: #21844

**Comment by groud** [comment]
No, in general we do everything so that Godot does not crash. Because in a game, you don't want the game to crash if there is a little bug somewhere forgotten in the  code.

It's up to the developper to fix those issue when they appear.
