### ISSUE TITLE
Cannot connect to external debugging tool

### ISSUE THREAD

**Issue by lexwhitfield** [godotengine/godot#28678]
**Godot version:** Godot_v3.1.1-stable_mono_win64

**OS/device including version:** Windows 10 (10.0.17134)

**Issue description:** 

Changed to using Visual Studio Code as external coding and debugging tool. Set the 'Wait for Debugger' option in Project Settings > Mono -> Debugger Agent. Setup the standard launch.json file in VSCode entered the port from the settings tab. Then any attempt to start the game from Godot returns the error 

>drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054

looking into the command line i get:

>Mono: Logfile is: C:\Users\Lex\AppData\Roaming/Godot/mono/mono_logs/2019_05_04 13.48.38 (11832).txt
>debugger-agent: Timed out waiting to connect.
>ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:190

trying to debug directly from the command line with the verbose setting active gives no more information and the log file is empty apart from the standard "Config attempting to parse:" line.

Have googled everything I can think of and can't find anyone else with this problem.

**Steps to reproduce:**
check the 'Wait for Debugger' to true and the problem always occurs

**Minimal reproduction project:**

Tried creating an empty project with just a single scene containing an empty Node2D, set it to  wait for external debugger and the error occurs.

**Comment by Teashrock** [comment]
Same with me.

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer and no reproduction project to test, so closing.
