### ISSUE TITLE
Godot v3.1.stable build script for F-Droid

### ISSUE THREAD

**Issue by HassanHeydariNasab** [godotengine/godot#28676]
**Godot version:** v3.1.stable

**Issue description:**
I already submitted some Godot v2.1.x games on [F-Droid]( https://f-droid.org/).
The script doesn't work anymore for Godot 3.1.stable.
It's the MR on gitlab:
https://gitlab.com/fdroid/fdroiddata/merge_requests/3827
And the new MR:
https://gitlab.com/fdroid/fdroiddata/merge_requests/4851
_The MR opened 6 months ago, since Godot v3.0.x_

**Comment by clayjohn** [comment]
Can you be more specific about what your issue is? For example, what script are you talking about? Is something failing in Godot that should otherwise work?

**Comment by HassanHeydariNasab** [comment]
> Can you be more specific about what your issue is? For example, what script are you talking about? Is something failing in Godot that should otherwise work?

You could see the MR [here](https://gitlab.com/fdroid/fdroiddata/merge_requests/3827).

https://gitlab.com/fdroid/fdroiddata/blob/cea7458a59df076781f01e512a1658639941a1b7/metadata/ir.hsn6.turo3.txt

**Comment by groud** [comment]
Sorry, but it's really not up to us to maintain distribution of the binaries.

**Comment by HassanHeydariNasab** [comment]
> Sorry, but it's really not up to us to maintain distribution of the binaries.

It's about something like compiling.

**Comment by clayjohn** [comment]
> You could see the MR here.

This doesn't contain nearly enough information for someone to help you. Please follow the template provided when you opened the Issue and answer the questions I posed above. 

> Can you be more specific about what your issue is? For example, what script are you talking about? Is something failing in Godot that should otherwise work?

In addition: 
- What are you trying to do that isnt working?
- What part of Godot does this relate to?
- A Minimal Reproduction Project so other users can reproduce the error on their machines

People can only help if you give them information. Sending a link to a third-party repo where you are having trouble building an android APK is not enough, especially since this doesn't seem to be a Godot issue in the first place.

**Comment by HassanHeydariNasab** [comment]
The same issue here: https://github.com/godotengine/godot/issues/16949

Log:
```
DEBUG: buildserver > export: begin: Exporting for Android steps: 105
DEBUG: buildserver > export: end
DEBUG: buildserver > ERROR: _fs_changed: Project export failed with error code 7.
DEBUG: buildserver >    At: editor/editor_node.cpp:494.
DEBUG: buildserver > reimport: end
DEBUG: buildserver > ERROR: ~List: Condition ' _first != __null ' is true.
DEBUG: buildserver >    At: ./core/self_list.h:111.
DEBUG: buildserver > ERROR: cleanup: There are still MemoryPool allocs in use at exit!
DEBUG: buildserver >    At: core/pool_vector.cpp:70.
DEBUG: buildserver > INFO: Successfully built version 3.1.1 of ir.hsn6.turo3
DEBUG: buildserver > ERROR: Could not build app ir.hsn6.turo3: No apks match build/ir.hsn6.turo3/turo3.apk
DEBUG: buildserver > DEBUG: Error encoutered, stopping by user request.
```

here is the build script:
```
commit=v3.1.1-fdroid
	    sudo=apt-get install -y g++
	    output=turo3.apk
	    srclibs=Godot@3.1-stable
	    prebuild=mkdir turo3 && \
	        bash -O extglob -c "mv !(turo3) turo3" && \
	        cp -R $$Godot$$ godot && \
	        rm godot/misc/dist/ios_xcode/libgodot.iphone.release.fat.a && \
	        rm godot/misc/dist/ios_xcode/libgodot.iphone.debug.fat.a
	    target=android-19
	    build=cd godot && \
	        scons -j `nproc` platform=server unix_global_settings_path=".." && \
	        export ANDROID_NDK_ROOT=$$NDK$$ && \
	        scons -j `nproc` platform=android target=release && \
	        pushd platform/android/java/ && \
	        gradle assembleRelease && \
	        popd && \
	        export HOME=$PWD && \
	        mkdir -p ../templates/ && \
	        cp bin/android_release.apk ../templates && \
	        cd ../turo3 && \
	        ../godot/bin/godot_server.x11.tools.* --export Android ../turo3.apk
	    ndk=r18b
```

**Comment by HassanHeydariNasab** [comment]
Here is the working script: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/ir.hsn6.tpb.yml
I hope that it's going to help someone.
