### ISSUE TITLE
Script Editor Non-English Characters Problem

### ISSUE THREAD

**Issue by lacriment** [godotengine/godot#2867]
I'm using a Turkish keyboard and Turkish keymap. When I press the Turkish characters on my keyboard it doesn't shows Turkish characters on script editor but it cause syntax error, "unknown character". So everytime I press turkish characters by mistake or by forgetting GDScript doesn't support utf-8 I have to open script file with another text editor and delete the unknown(turkish) characters.

**Comment by lacriment** [comment]
ÜĞİŞÇÖüğşçöı these are the Turkish characters.

**Comment by akien-mga** [comment]
Duplicate of #871.
