### ISSUE TITLE
Using 'as' in function argument causes game crash once exported for release

### ISSUE THREAD

**Issue by ClementRivaille** [godotengine/godot#28680]
**Godot version:**
v3.1 stable

**OS/device including version:**
Linux Mint 18.3 Cinnamon 64-bit

**Issue description:**
Typing a variable with `as` inside a function arguments (like `myFunc(something as SomeClass)`) will run in the editor and debug export. However, it will crash in a release export. Giving this error:
```
SCRIPT ERROR: GDScript::load_byte_code: Compile Error: Parser bug: unresolved data type.
```
The error will happen on Linux exports as well as Windows ones.
Might be related to #25124

**Steps to reproduce:**
* Make a scene with a parent node and a child node
* Create a script for the child, and declare a class using `class_name`
```gdscript
extends Sprite
class_name MyClass
```
* Declare somewhere a function taking this class as parameter
```gdscript
func myFunc(value: MyClass):
  print('hello world')
```
* In the parent node's script, call this function by using `as` directly inside the arguments
```gdscript
# Will crash once exported
myFunc($icon as MyClass)
```

An easy workaround is to store the node in a variable, and use `as` before calling the function.
```gdscript
# Will run
var icon := $icon as MyClass
myFunc(icon)
```

**Minimal reproduction project:**

[AsCrashTest.zip](https://github.com/godotengine/godot/files/3144488/AsCrashTest.zip)

**Comment by Lisapple** [comment]
Tested on 3.1.1-release-official (with matching 3.1.1.stable export template)

I confirm it crashes on macOS 10.12 too.

Also, calling a method on `MyClass` would not work either:

```
($icon as MyClass).show() # Crash on release
```

But still, the workaround fixes the problem:
```
var icon := $icon as MyClass
icon.show() # Ok
```

**Comment by akien-mga** [comment]
Confirmed in the current master branch on Linux (b374a9f). To be clear, this is not a "crash" per se, but since the .gdc file fails compiling, the .tscn file which references it can't be loaded so the application stops:
```
ERROR: _gdtype_from_datatype: Parser bug: converting unresolved type.
   At: modules/gdscript/gdscript_compiler.cpp:166.
SCRIPT ERROR: GDScript::load_byte_code: Compile Error: Parser bug: unresolved data type.
   At: res://Main.gdc:6.
ERROR: load_byte_code: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules/gdscript/gdscript.cpp:794.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2195.
ERROR: _load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:285.
ERROR: poll: res://Main.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Main.gd
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:285.
ERROR: start: Condition ' !scene ' is true. returned: false
   At: main/main.cpp:1757.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2111.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:445.
```

The initial compilation error also happens when running directly from source, but then it does not prevent running the main scene as it does find the .gd file in the source folder:
```
SCRIPT ERROR: GDScript::reload: Compile Error: Parser bug: unresolved data type.
   At: res://Main.gd:5.
ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules/gdscript/gdscript.cpp:595.
```
