### ISSUE TITLE
GradientTexture spams error to console related with height

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#28688]
**Godot version:**

7018de8425e8c2781071595fdcf565acdfde2be4

**OS/device including version:**

Win7 64

**Issue description:**

Saving to tres file a GradientTexture spams an error to console every time the project is opened.
Error:
![GradientError](https://user-images.githubusercontent.com/11712737/57186019-dad61d00-6ed7-11e9-9322-c16f2470c516.png)

Project:
[Godot3_1_bug_Catch.zip](https://github.com/godotengine/godot/files/3144969/Godot3_1_bug_Catch.zip)

**Steps to reproduce:**
Create a Sprite, add an GradientTexture and save as tres file.

**Comment by KoBeWi** [comment]
Fixed in 3.2
