### ISSUE TITLE
Allow dragging and dropping directories into the code editor

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28682]
**Godot version:**
3.1.1

**Issue description:**
Dragging resources into the script editor works, but why doesn't it function the same way with directories?

**Steps to reproduce:**
* Create a directory and a script.
* Drag the directory into the script.

**Comment by akien-mga** [comment]
I assume that you expect to then get the path to that directory?

**Comment by Jummit** [comment]
> I assume that you expect to then get the path to that directory?

Yep, exactly what dragging in a resource does, just with folders.
