### ISSUE TITLE
Why PVRTC textures not exported to iOS build? (GLES2)

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#28683]
**Godot version:**

Godot 3.1.2-devel (bc577dc0c)

**OS/device including version:**

MacOSX 10.13.6
iOS 12.1.2

**Issue description:**

I setup project for GLES2. I added one vram compressed texture. I enabled pvrtc format in project settings. When I start project on iOS simulator I have this:
```
*********** main.m
running app main
Path: /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Bundle/Application/2A84127D-C6ED-438E-848C-C95385954509/test-particles-ios.app
godot_iphone /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Bundle/Application/2A84127D-C6ED-438E-848C-C95385954509/test-particles-ios.app/test-particles-ios
cwd /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Bundle/Application/2A84127D-C6ED-438E-848C-C95385954509/test-particles-ios.app
os created
setting data dir to /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Data/Application/454B8ABE-A404-4F82-89B0-6F14BE142C85/Documents from /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Data/Application/454B8ABE-A404-4F82-89B0-6F14BE142C85/Documents
setup 0
after init super 0x7fae23d03020
2019-05-04 19:53:07.790 test-particles-ios[52284:59232871] Setting up an OpenGL ES 2 context. Based on Project Settings "rendering/quality/driver/driver_name"
******** screen size 750, 1334
after init gles 0x7fae23d03020
******** adding observer for sound routing changes
******** adding observer for keyboard show/hide
cadisaplylink: 1start animation!
******** screen size 750, 1334
******** screen size 750, 1334
OpenGL ES 2.0 Renderer: Apple Software Renderer
2019-05-04 19:53:08.316532+0300 test-particles-ios[52284:59232871] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-05-04 19:53:08.334097+0300 test-particles-ios[52284:59232871] [MC] Reading from private effective user settings.
2019-05-04 19:53:08.400950+0300 test-particles-ios[52284:59233665] [aqme] 254: AQDefaultDevice (1): skipping input stream 0 0 0x0
**ERROR**: Failed loading resource: res://scene/menu-background.png
   At: core/io/resource_loader.cpp:285:_load() - Method/Function Failed, returning: RES()
**ERROR**: res://scene/Control.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scene/menu-background.png
   At: scene/resources/resource_format_text.cpp:440:poll() - res://scene/Control.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scene/menu-background.png
**ERROR**: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208:load() - Condition ' err != OK ' is true. returned: RES()
**ERROR**: Failed loading resource: res://scene/Control.tscn
   At: core/io/resource_loader.cpp:285:_load() - Method/Function Failed, returning: RES()
**ERROR**: Failed loading scene: res://scene/Control.tscn
   At: main/main.cpp:1739:start() - Condition ' !scene ' is true. returned: false
```
As far as I know GLES2 on iPhones supports Pvrtc compressed textures.

**Steps to reproduce:**

**Minimal reproduction project:**

[test-particles.zip](https://github.com/godotengine/godot/files/3144601/test-particles.zip)

**Comment by DrMoriarty** [comment]
I have discovered that `etc2` feature automatically added to features list only when current video driver is GLES3. If I add manually `etc2` it export all pvrtc textures to iOS project.
If I add `pvrtc` feature the strange things happens. The .pck file is larger then case without etc2 and pvrtc. But it is lesser then case when etc2 is present. What textures did it pack with this feature?
With `pvrtc` and without `etc2` the project is crashed on start because resources not found.
Maybe it will be more straightforward  to use `pvrtc` feature in order to control iOS packed textures?

**Comment by DrMoriarty** [comment]
I'm checking export options and it was a surprise for me. 
When I enable etc2 and pvrtc compression in  project settings, and etc2 feature enabled in iOS exporting, godot copied both types of files in application bundle. Every vram compressed texture exists in two etc2 and pvrtc files!
When I disabled pvrtc compression and reimport all vram textures I have a smaller IPA file!

I think that `pvrtc` feature  for control copying pvrtc files will be a good solution.

**Comment by DrMoriarty** [comment]
So, the result of investigation:
- Now I can make iOS build with etc2 files (enable etc2 compression and disable pvrtc)
- Or I can make iOS build with both types of files (larger IPA, enable etc2 and pvrtc)
- Or godot doesn't allow me to make any export (disable etc2)

**Comment by ealataur** [comment]
when I switch on the pvrtc and restart the editor, I have this error
Assertion failed: (bitmap.GetBitmapWidth() == bitmap.GetBitmapHeight()), function EncodeRgba4Bpp, file thirdparty/pvrtccompressor/PvrTcEncoder.cpp, line 388.

And then editor will crash..

v3.1.1.stable.custom_build.66baa3b
Mac OS 10.14.5

**Comment by DrMoriarty** [comment]
@ealataur it fixed in https://github.com/godotengine/godot/issues/28534
