### ISSUE TITLE
"godot -e" in a project folder opens the project but not the main scene

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2869]
Same with ```godot -e -path /path/to/project```.

**Comment by akien-mga** [comment]
Apparently it was already the case in 1.1, so it's likely not a regression like #2611 was.

**Comment by akien-mga** [comment]
To actually load the main scene, the project editor somehow retrieves the path to the resource and adds it to the command line: https://github.com/godotengine/godot/blob/33aa019e4f00b3ac9809c7974c1d660b2f65455f/tools/editor/project_manager.cpp#L627-L630

I'll see if this behaviour could be added directly to the ```-e | -editor``` switch.

**Comment by vnen** [comment]
If the path to the scene is provided in the command line, such scene is opened. Be careful to not override this behavior.

**Comment by vnen** [comment]
(Sorry, pressed the wrong button).

**Comment by akien-mga** [comment]
Ah you're right, I had indeed overlooked that. I'll check my WIP fix :)
