### ISSUE TITLE
There is no way for a tilemap sprite list to add/remove sprites and it not delete the levels you have already created with it

### ISSUE THREAD

**Issue by JoshuaCoffman** [godotengine/godot#28703]
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
There is no way for a tilemap sprite list to add/remove sprites and it not delete the levels you have already created with it

- If you turn merge on, your levels stay in place. Though with it on your sprite list gets messy with old sprites that you have edited or sprites that you removed but stick on the list.

- If you turn merge off your levels get destroyed each time you update your tile set, but your sprite list gets updated correctly.

**Steps to reproduce:**
1. Make changes to a tile set. Change a name of a tile and remove a tile.
2. Update a tile set by clicking Scene in the top left corner and then convert to... TileSet
3. a.) When updating with merge ON, you can see your sprite list with the tile map still has the older tiles you changed. Your levels you created with this tile map stay the how they were with no changes.
 b.) When updating with merge OFF, your sprite list with the tile map gets updated properly and removes the older tiles. The levels created with this tilemap before you updated it are now no longer there. 

You can see here the sprite list could get super messy if you were making a lot of changes or even when you're just testing things out.
![image](https://user-images.githubusercontent.com/9705020/57195439-1bee2180-6f18-11e9-8120-ded368f700ed.png)

**Comment by bojidar-bg** [comment]
There is an option in the Editor Settings to sort tiles by name, and not by id.
With it, you can have your tiles sorted normally (no dirt tiles in the middle of your grass tiles), while at the same time not having broken levels from changing tile indices.

![image](https://user-images.githubusercontent.com/5276727/57527393-353c0700-7338-11e9-93e3-f7fa84ce956e.png)

**Comment by Zylann** [comment]
That would be an enhancement, but it seems in Godot 4 the scene conversion workflow will be gone, so that problem might no longer exist. We'd have to test if removing/adding tiles still have the same problem, but if it does then that would be a bug, perhaps another issue.

**Comment by akien-mga** [comment]
This is fixed in 4.0 indeed, AFAIK the new tiles editor doesn't automatically change/remove tiles when tile IDs are changed in the tileset. It provides options to fix tiles that no longer match their ID in a changed tileset.
