### ISSUE TITLE
class_name added via external editor is only registered after restarting the editor

### ISSUE THREAD

**Issue by JMS55** [godotengine/godot#28706]
**Godot version:**
3.1.1

**Comment by akien-mga** [comment]
Please be more specific, the issue template asked for details for a reason.

What doesn't work? External editors don't compile GDScript, so what *could* even work?

**Comment by JMS55** [comment]
Anything related to the editor recognizing class_name. Scripts importing that class will crash, complaining they can't find the class. When trying to create a new node, the class won't come up. It only gets fixed if you open the script with godot, delete the class_name line, and retype it.

**Comment by akien-mga** [comment]
So you mean that if you add a `class_name` in a script using an external editor, and then you run the game, it errors out because it doesn't know the defined class name, right?

**Comment by JMS55** [comment]
Yes

**Comment by KoBeWi** [comment]
Seems like the class is also recognized correctly when you reload the project.

**Comment by rcorre** [comment]
@JMS55 you might consider renaming the topic to "class_name added via external editor only registered after restart" or something like that. This issue drives me crazy, but "Doesn't work" isn't quite accurate

**Comment by Calinou** [comment]
Duplicate of #24633.
