### ISSUE TITLE
Prevent editing a container child's position and size in the inspector

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#28718]
**Godot version:** 3.1.1 stable

**OS/device including version:** Linux, Xubuntu 18.04 64-bit

**Issue description:** When you click on a child node of a Container in the editor, a small warning shows up for a few seconds that says the position and size are determined only by the parent. This warning is easily missed, and so it would be better to prevent the properties such as Anchor, Margin, Position, and Size from being editable. 

https://github.com/godotengine/godot/issues/20750 made it so that you can't visually click on the child and move/rotate/resize it, but the values in the inspector are still editable. They should also be locked.

Currently, when you try to edit the values, for some of them the number changes but nothing visually happens, and for others there is a visual change... which is reverted when the scene is run. This is not ideal and is probably very confusing to new users.

**Comment by extrasyrup** [comment]
This has thrown me off before too.

**Comment by KoBeWi** [comment]
Related: #26403

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2202, as feature proposals are now tracked on the Godot proposals repository.

**Comment by pycbouh** [comment]
I'm not entirely sure that proposal talks about the same thing.
