### ISSUE TITLE
Trimming and normalizing audio as default during wave import is a mistake.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#28728]
**Godot version and OS**:
Godot 3.1.1-stable  64-bit,  Manjaro Linux v18.0.4-stable
**Issue** :
It seams that Godot, when importing waveform audio file format trims and normalizes the sound in the process. That should not be default behavior. Sounds should be imported as they are, unless normalize and trim options are checked in, but in Godot 3.1.1 there is no such option.
I remember in Godot 1.0/2.0 import audio dialog let users to check in/out the trim and normalize.

**Comment by Calinou** [comment]
I think this is a good idea too, but wouldn't it be considered as compatibility-breaking as it will change the volume of all sounds in existing projects? Therefore, if the defaults are changed, this should be done in 4.0.

**Comment by freemanfromgodotengine** [comment]
@Calinou Some things could already change since I filed this bug, but I would assume, that in existing projects the sounds were already imported - and trimmed, and normalized - so those files would not be untrimmed and un-normalized. All new sounds imported into existing or new projects would just have an option to check trim/normalize if needed.

"Less aggressive" auto-trimming by automatic fade outs is not a solution and in some cases might be even a problem. 
Sound/audio guys do not buy and work with all that pro-audio software and hardware to let the game engines mess up with some unwanted auto-editing during loading/importing of their already carefully prepared audio work.

My idea was to let import/loading mean "import/loading" and not "import/loading + some additional operations you did not ask for".  :)

**Comment by Keetz** [comment]
I totally agree that trim and normalize should be disabled as default.
I find myself re-importing all .wav files in every project I do because of this.
