### ISSUE TITLE
GDScript Enum doesn't check value integrity

### ISSUE THREAD

**Issue by Lisapple** [godotengine/godot#28727]
**Godot version:**

3.1.1

**Issue description:**

Mal-formatted enum values will be ignored instead of throwing a parse error:
```
enum { X = 123abc }

X == 123
```

It can lead to silent bug like: 
```
enum { MASK = 0b1111 }

MASK == 0
```

**Comment by bojidar-bg** [comment]
Uh, my bad.
This actually parses as `enum { X = 123, abc }`, which is then converted to `X = 123, abc = 124`..
