### ISSUE TITLE
Assigning a value to a getter's variable results in calling its setter function 

### ISSUE THREAD

**Issue by lukas-durica** [godotengine/godot#28720]
**Godot version:**

3.1.1

**OS/device including version:**

Windows 10/Nvidia GeForce GTX 1070

**Issue description:**

What happened:
Assigning setter's variable results in calling getter and setter function 
What was expected:
To not to call the setter function.

**Steps to reproduce:**

Just assign value to a variable, declared inside the class that is used as setter/getter (or download minimal reproduction project), e.g.:
```
# engine is a setter/getter in Car script
# engine's getter will be called, that is OK, 
# engine's setter will be callled, that is NOT OK
$Car.engine.speed = 60 
```
**Minimal reproduction project:**
[MinimalReproductionProject.zip](https://github.com/godotengine/godot/files/3147374/MinimalReproductionProject.zip)

**Comment by akien-mga** [comment]
Still reproducible in latest `3.x` and `master` branches.
Here's a MRP for `master` using the new GDScript property syntax: [TestProjectGH28720.zip](https://github.com/godotengine/godot/files/8356042/TestProjectGH28720.zip)
