### ISSUE TITLE
Error loading resources with exported exe/pck files

### ISSUE THREAD

**Issue by andrekim93** [godotengine/godot#28732]
**Godot version:**
3.1.1

**OS/device including version:**
windows 10

**Issue description:**
It's the same issue as this, but I don't think people can see archived posts that got reopened? https://github.com/godotengine/godot/issues/26379
So basically the exe file only runs as it should if the exe and pck files are inside the main project folder, whereas if theyre both outside that folder, a bunch of loading resource errors pop up. I assume the pck should be all the assets in the main project folder, but it just won't run unless inside the project folder. All the resources are autoload scenes minus the map files, but i assume it won't work only because the autoloads aren't loaded. The game still runs, its just nonfunctional because of the specific resources not being loaded.

These are the debug print statements
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
ERROR: No loader found for resource: res://assets/info_icon.png
   At: core/io/resource_loader.cpp:285
ERROR: poll: res://globals/hud.tscn:5 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/info_icon.png
   At: scene/resources/resource_format_text.cpp:440
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208
ERROR: Failed loading resource: res://globals/hud.tscn
   At: core/io/resource_loader.cpp:285
ERROR: Can't autoload: res://globals/hud.tscn
   At: main/main.cpp:1549
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:813
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2172
ERROR: Failed loading resource: res://dialogue/progress.gd
   At: core/io/resource_loader.cpp:285
ERROR: Can't autoload: res://dialogue/progress.gd
   At: main/main.cpp:1549
ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: scene/resources/resource_format_text.cpp:1226
ERROR: Failed loading resource: res://dialogue/dialogue.tscn
   At: core/io/resource_loader.cpp:285
ERROR: Can't autoload: res://dialogue/dialogue.tscn
   At: main/main.cpp:1549
ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: scene/resources/resource_format_text.cpp:1226
ERROR: Failed loading resource: res://dialogue/dialogue.tscn
   At: core/io/resource_loader.cpp:285
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Can't preload resource at path: res://dialogue/dialogue.tscn
          At: res://scripts/map.gdc:7
ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:785
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2168
ERROR: Failed loading resource: res://scripts/map.gdc
   At: core/io/resource_loader.cpp:285
ERROR: poll: res://scenes/map.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scripts/map.gd
   At: scene/resources/resource_format_text.cpp:440
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208
ERROR: Failed loading resource: res://scenes/map.tscn
   At: core/io/resource_loader.cpp:285

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by andrekim93** [comment]
Bit of an update, but still hasn't fixed the main issue. The map scene had a bunch of onready var preloaded scenes and removing all of them and loading them when needed seems to have solved the map failing to load. The autoloaded scenes still fail to load though.

**Comment by andrekim93** [comment]
Ok, I figured out almost all of it. I had an issue prior to this where the file system wouldn't show a specific folder, none of the scenes and assets inside were searchable through it. If I went to Scene -> Open Scene, then the folder would show up in that popup. Opening the scene, then saving it, would get the FileSystem to display the folder that was hidden, but it would only show that one scene. If I wanted all the scenes there, I'd have to open all manually and save it. The issue was fixed going off by this https://godotengine.org/qa/43323/how-do-i-import-a-folder-of-many-assets-resources . 
There's one problem left though, it won't read any json files. I do have the path as res://, not user:// so I don't think the path is the issue as the game does find and read the json files correctly in the editor. The exported exe file all works correctly now, it just can't find json files?

**Comment by LinuxUserGD** [comment]
People can see archived posts even if they are closed.

**Comment by ShrewdSpirit** [comment]
I have the same issue on Linux with exported .pck files with only the following error:
```OpenGL ES 3.0 Renderer: GeForce GTX 1050/PCIe/SSE2
WARNING: _update_root_rect: Font oversampling does not work in 'Viewport' stretch mode, only '2D'.
   At: scene/main/scene_tree.cpp:1241.
ERROR: _load: No loader found for resource: res://scripts/commands/Eval.gd.remap
   At: core/io/resource_loader.cpp:285.
SCRIPT ERROR: _load_commands: Attempt to call function 'new' in base 'null instance' on a null instance.
   At: res://autoload/Console.gdc:55.```

**Comment by fossegutten** [comment]
My exported game won't load json files either. Works fine when running debug build from editor.

![image](https://user-images.githubusercontent.com/15088582/66702585-6f576d80-ed09-11e9-8ff7-e74b0f126c24.png)

Windows 10
Godot 3.2 alpha 1 and 2

**Comment by Calinou** [comment]
@andrekim93 Have you been able to reproduce this issue recently?

**Comment by Calinou** [comment]
Closing due to lack of response.
