### ISSUE TITLE
_unhandled_input doesn't work with InputEventMouseMotion

### ISSUE THREAD

**Issue by rmullin7286** [godotengine/godot#28731]
**Godot version:**
Godot 3.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
I've tried moving some of my inputs to _unhandled_input for better control with other UI nodes, and _unhandled_input never catches any mouse motion events like what would regularly be caught in _input

**Steps to reproduce:**
I created a minimal scene with a root node and a script:

`func unhandled_input(event):
    print(event)`

when the code is run, Key events will be printed, but not MouseMotion events.

**Comment by Vultraz** [comment]
Seems to work fine in our project.. 🤔 We have this (trimmed out the unnecessary bits):
```swift
func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("mouse_left"):

	elif event.is_action_pressed("mouse_right"):

	elif event is InputEventMouseMotion:
```

and the last clause works.

**Comment by Daw11** [comment]
_unhandled_input will not work if there's a Control node covering your screen with the wrong mouse filter option.

**Comment by rmullin7286** [comment]
Looks like that was it. problem was on my side. Thanks!
