### ISSUE TITLE
Confusing workflow for new custom Android builds / source template

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#28736]
**Godot version:**
Godot 3.2.dev commit id:0239d8bd9fa03965439aac2482d18746f807bd00

**OS/device including version:**
Linux Manjaro

**Issue description:**
I don't know if this is an issue or not, simply I don't know how to test the new android export. I follow the documentation instruction, but Godot doesn't create the android project template. I attach some screenshot to better understand.
![Schermata del 2019-05-07 13-27-46](https://user-images.githubusercontent.com/16955149/57296708-ef7c0600-70cd-11e9-996e-917f8b520712.png)
![Schermata del 2019-05-07 13-28-34](https://user-images.githubusercontent.com/16955149/57296718-f6a31400-70cd-11e9-8791-2bd3ba959ae6.png)
Tell me the template is missing but I have installed all templates.
![Schermata del 2019-05-07 13-29-04](https://user-images.githubusercontent.com/16955149/57296750-07538a00-70ce-11e9-9459-1b84e678c9a4.png)
It's a bug or is intended to do this for now? How can I test the new android export for some feedback?

**Steps to reproduce:**
Look the screenshot

**Minimal reproduction project:**

**Comment by freemanfromgodotengine** [comment]
The templates have to be exactly match for your version of Godot, so if you compiled from master yourself, you also need to compile the templates. And I think there might be something wrong with creation of android templates right now. I was not able to compile it myself few days ago. Everything looked like it's going all right, but there was no templates in the folder after all. Looks like #28498 has something to do with this.

**Comment by LinuxUserGD** [comment]
@freemanfromgodotengine They are now in another folder (not copied to /bin anymore).

**Comment by erammos** [comment]
You can find the generated apk in godot/platform/android/java/build/outputs/apk

**Comment by HugeGameArtGD** [comment]
@erammos I can't find the .apk there on /android/java although the folder should be correct. Don't know what I'm doing wrong.

**Comment by LinuxUserGD** [comment]
I can't find the .apk there on /android/java although the folder should be correct. Don't know what I'm doing wrong.

**Comment by erammos** [comment]
Btw, i can't export the gradle project from "Install Android Build Template", I get the same error "Android build template is missing", although i have installed the template

**Comment by erammos** [comment]
Well I have managed to solve that issue. You have to take everything in godot/platform/android/java/  (except the Build folder), zip them in a file named as "android_source.zip" and  last copy-paste it in your templates folder 3.2.dev

**Comment by gamergamesz** [comment]
There is no android_source.zip on godot server so it won't work. Apk file won't going to work. Zipping java  folder works but it does not work on android phone, i.e crashes( might be some other bug).

**Comment by erammos** [comment]
> There is no android_source.zip on godot server so it won't work. Apk files won't going to work. Zipping java folder works but it does not work on android phone, i.e crashes( might be some other bug).

Maybe the engine libs are missing in java folder... you have to compile the engine first (scons platform = android )

**Comment by gamergamesz** [comment]
I did copy pasted lib folder in android_source.

**Comment by neikeq** [comment]
If it crashes, your best option is to run adb logcat and open an issue with the log.

**Comment by creikey** [comment]
I do not have the `android_source.zip` file in my templates folder and I can still build for android perfectly fine, for oculus quest and a normal android device @erammos
