### ISSUE TITLE
Error `look_at() failed` when look from top to the scene

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28737]
**Godot version:**
3.2.dev.custom_build. df18c8c

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I look to the scene from top, then this error appear:
```
ERROR: look_at: Up vector and direction between node origin and target are aligned, look_at() failed
   At: scene/3d/spatial.cpp:687.
```

**Steps to reproduce:**
https://streamable.com/zr5t1

**Comment by CptPotato** [comment]
The error is correct, there are many possibilities when the vectors are aligned.
I think you can just add a check for this special case and skip look_at() when it occurs.

**Comment by mojoyup** [comment]
I get this error now when trying to view an object from the bottom while its falling straight down, but I need to do this, so instead of checking to pass look at, how can I make sure it doesnt pass but doesnt fail either?
