### ISSUE TITLE
A second Godot client on the same PC won't connect to a websocket server

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#28749]
I  can connect a Godot client to a websocket server, but if you're trying to connect two clients on the same PC, it would not work.

I thought I did something wrong, until someone on Facebook pointed out that this is an issue with Godot.

**Comment by 2shady4u** [comment]
Could you give me a little more information to work with? 
Did you change the port for each client? or are they trying to access the server using the same port?

Some steps to reproduce the error would be nice. 😄

**Comment by elieobeid7** [comment]
They're trying to access the server on the same port.

Here you can test this


```
extends Node

var ws = null

func _ready():
    ws = WebSocketClient.new()
    ws.connect("connection_established", self, "_connection_established")
    ws.connect("connection_closed", self, "_connection_closed")
    ws.connect("connection_error", self, "_connection_error")

    var url = "wss://echo.websocket.org"
    print("Connecting to " + url)
    ws.connect_to_url(url)

func _connection_established(protocol):
    print("Connection established with protocol: ", protocol)

func _connection_closed():
    print("Connection closed")

func _connection_error():
    print("Connection error")

func _process(delta):
    if ws.get_connection_status() == ws.CONNECTION_CONNECTING || ws.get_connection_status() == ws.CONNECTION_CONNECTED:
        ws.poll()
    if ws.get_peer(1).is_connected_to_host():
        ws.get_peer(1).put_var("HI")
        if ws.get_peer(1).get_available_packet_count() > 0 :
            var test = ws.get_peer(1).get_var()
            print('recieve %s' % test)
```

Open two clients, the first will connect, the second won't.

**Comment by 2shady4u** [comment]
I couldn't really replicate your error because I don't really know what kind of server you are using?
There's also an error in that code because` _connection_closed()` requires a boolean input:

```
func _connection_closed(clean : bool):
    print("Connection closed")
```

Have you checked out this demo? 
https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo
I was able to run that demo without any problems with 3 clients connecting to the same server (at the same port).

Maybe the issue is at the side of your server?
It's a bit difficult from my side because I can't replicate the error of course. Apologies for that.

**Comment by elieobeid7** [comment]
The server is a demo server

**Comment by elieobeid7** [comment]
The server is a fake server

https://www.websocket.org/echo.html

but even on localhost, I have the same problem

And the code is not mine either, it's the code that everyone is using

https://github.com/gd-com/examples

in the websockets folder you'll find the basic and the advanced example, neither work with multiple clients.

I will run the demo you provided, if the issue is solved, I'll close the issue in this repo and reopen the issue in the other repo. Thanks for letting me know.

**Comment by 2shady4u** [comment]
![clients](https://user-images.githubusercontent.com/42484461/57543792-a4742400-7355-11e9-9876-aad3ae31a512.png)

I used the basic websocket example from that repository (https://github.com/gd-com/examples) and
added two clients that used the same script except for the message that they are sending to the server.
Client1 sends: I AM NUMBER ONE
Client2 sends: ALWAYS SECOND PLACE

As you can see in the screenshot, this works without any problem.

I am using the server supplied with this repository (the nodejs one found in the /websocket/basic/server) one and ran it with "npm start" (after installing the prerequisite @gd-com/utils and ws)

What version of Godot are you using? (I'm using 3.1.1 stable)
What version of nodejs? (I'm using 10.15.3 -lts)

**Comment by elieobeid7** [comment]
![screenshot](https://user-images.githubusercontent.com/660142/57545024-ba87e180-7361-11e9-9470-c0ddbec32db6.png)

What version of Godot are you using? (I'm using 3.1.1 stable)
What version of nodejs? (I'm using v8.16.0 (Thank you for letting check my node version to see how old it is :) )) 

What is your OS? (Ubuntu 16.04 LTS)

From the screenshot, I think this error only happens on Linux, since it seems a unix thing, correct me if I'm wrong. Maybe on mac too since it uses unix?

**Comment by 2shady4u** [comment]
![Capture](https://user-images.githubusercontent.com/42484461/57546064-41d25680-735c-11e9-88b9-460803a41485.PNG)

Could you try updating your nodejs? 

If the problem persists after this upgrade, I can also check it on my linux machine (Arch Linux)
to see if the problem is unique to Linux machines.

**Comment by elieobeid7** [comment]
ok will let you know tomorrow for sure.

**Comment by 2shady4u** [comment]
When running Godot in two editor it is also important to change the debugger port for one of the editors.
Currently both editors are trying to listen to port 6007 to find out any errors from the running game instance and this gives an error in one of the editors.

Change you debugger port by going to:
`Editor Settings -> Network -> Debug `
and change the remote port there to 6008 (or anything else than 6007)

**Comment by elieobeid7** [comment]
The error is still there after upgrading to node 10 lts.

There's nothing in `Editor Settings -> Network -> Debug`

![screenshot](https://user-images.githubusercontent.com/660142/57562310-3e5dc000-739a-11e9-8608-c4df06bd9949.png)

**Comment by 2shady4u** [comment]
![Untitled](https://user-images.githubusercontent.com/42484461/57568132-86ed9b80-73e3-11e9-96a5-fb7e89cf7599.png)

Be sure to remove the "net" search term! Otherwise the debug port options won't show! 😄

**Comment by elieobeid7** [comment]
Wow! That's worthy of a second issue just to fix the search :)
 
Regarding the websockets, it's fixed, thanks a lot seriously, no one could fix it but you, I posted it on reddit Godot group twice where hundreds of users are online always, on facebook and here, you were the only one who solved it :)

I hope you are paid very very well in your job because you deserve it, you are very helpful and just provided premium support, you deserve the very best this life has to give.
