### ISSUE TITLE
Visual Scripting Proposal

### ISSUE THREAD

**Issue by turtletooth** [godotengine/godot#28741]
I'd like to add some nodes to the Visual Script system but I want feedback before I start implementing it. 

I'd like to add some nodes that abstract away some of the complication of visual scripting to make it more accessible and bring the difficulty of visual scripting closer to that of GameMaker.

Some possibilities include a two way input node that returns a float based off of input.  Also, a four way input that returns a Vector 2.  

The idea is just to simplify some of the common actions and reduce the number of nodes required to do some of the basic tasks.

I'd like to see this included in Godot and not as an addon to make Visual Scripting as accessible as possible for folks.  

Thoughts?

**Comment by bruvzg** [comment]
One of accepted GSoC projects is on [Visual Scripting Improvement](https://summerofcode.withgoogle.com/projects/?sp-page=2#6258227275104256) and main discussion on the topic is in the separate repo - https://github.com/godotengine/godot-proposals/issues/3.

**Comment by turtletooth** [comment]
Thanks.  I'll move this over there.
