### ISSUE TITLE
Node.replace_by() has strange behavior with instanced scenes

### ISSUE THREAD

**Issue by Jeto143** [godotengine/godot#28746]
**Godot version:**

3.1

**Issue description:**

Using [`Node.replace_by`](https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-replace-by) to replace an instanced scene with another one created from script appears to merge the two subscenes instead of actually replacing.

**Steps to reproduce:**

- Create three scenes: `main`, `other`, `yetanother`, each with a simple `Node2D` as base node. Then add different sprites to `other` and `yetanother` to distinguish between them.
- In the `main` scene, instantiate the `other` scene (say, as `Other`) as a child with the editor.
- Using script attached to `main` scene's base node, instantiate a `yetanother` scene with `load('res://yetanother.scn')` and call `.instance()` on it (call the resulting variable `yetanother`).
- Add `$Other.replace_by(yetanother)` to the following line.

Instead of replacing the initially instanced scene node with the new one, this results in merging the two scenes together (which can be confirmed by looking at the Remote tab's scene tree during execution).

As an additional note, `print($Other)` will print `[Object:null]` then (because the node also took the new node's name), which imho is a bit counter-intuitive, though this is easily fixable with `yetanother.name = 'Other'`. I believe the replaced node should take the initial node's name by default, but that may be intended for reasons I'm missing.

**Minimal reproduction project:**

[replace_by_bug.zip](https://github.com/godotengine/godot/files/3154742/replace_by_bug.zip)

**Comment by bojidar-bg** [comment]
`Node.replace_by` is used by the editor when changing the type of a node in the scene dock. As such, it makes little sense to lose children nodes.

The part of it which you want is just:
```
var parent = get_parent()
var pos_in_parent = get_position_in_parent()
parent.remove_child(self)
parent.add_child(other)
parent.move_child(other, pos_in_parent)
```

That being said, the documentation is quite lacking. Retagging.

**Comment by Jeto143** [comment]
Yes, that's what I've been doing, and it's working fine, I was just curious why that method wouldn't do the same, considering what I thought it should do. 

So I was wrong about that--still, `replace_by` seems a bit misleading as a term to describe a method that doesn't, technically, seem to replace the node it's called on with another :)

(In any case, documentation could at least make that more obvious indeed!)

**Comment by starry-abyss** [comment]
If it's used by editor and works weirdly for games, maybe it should be made hidden/private from the user?
