### ISSUE TITLE
ID in id_pressed( int ID ) and id_focused( int ID ) should be lower case.

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28767]
**Godot version:**
3.1.1

**Issue description:**
ID in id_pressed( int ID ) and id_focused( int ID ) should be lower case, as full upper case should be reserved for constants.

**Comment by 2shady4u** [comment]
Seems like this was an deliberate choice as ID is always written in capitals in the code:



	void add_item(const String &p_label, int p_ID = -1, uint32_t p_accel = 0);
	void add_icon_check_item(const Ref<Texture> &p_icon, const String &p_label, int p_ID = -1, uint32_t p_accel = 0);
	void add_check_item(const String &p_label, int p_ID = -1, uint32_t p_accel = 0);
	void add_radio_check_item(const String &p_label, int p_ID = -1, uint32_t p_accel = 0);
	void add_icon_radio_check_item(const Ref<Texture> &p_icon, const String &p_label, int p_ID = -1, uint32_t p_accel = 0);

(from _blob/master/scene/gui/popup_menu.h_)

So don't worry about it too much. As long as it is used consistently in upper case everywhere.

**Comment by bojidar-bg** [comment]
> So don't worry about it too much. As long as it is used consistently in upper case everywhere.

Things is, the ID parameters are the only inconsistent ones. `p_rid`, `p_ip`, `p_json`, are all written lowercase.
