### ISSUE TITLE
Crash'n'Burn  when imported a multi-skinned gltf file

### ISSUE THREAD

**Issue by vpenades** [godotengine/godot#28764]
**Godot version:**
Godot_v3.1.1-stable_mono_win64

**OS/device including version:**
Windows10, nVidia

**Issue description:**
When importing a certain GLB asset, godot editor crashes

**Steps to reproduce:**
1- Download **InfiniteSkinnedTentacle.glb** from [here](https://github.com/vpenades/SharpGLTF/tree/master/examples)
2- Create a new project and drag the asset to import it.

Notice that this gltf model is valid, but it's been created to stress various engines skinning support.

At the time of reporting this issue, only BabylonJS is able to display this model correctly, all other viewers around, either crash or display it incorrectly.

**Comment by marstaik** [comment]
Fixed by #32213 (although the clicking on the animation player takes forever to load 🐢 )

![tentacles](https://user-images.githubusercontent.com/5601015/65482746-e27a6c00-de4e-11e9-96a4-98d480df354b.gif)
