### ISSUE TITLE
Godot Mono uses wrong path separator and extension when looking for mscorlib

### ISSUE THREAD

**Issue by ShyRed** [godotengine/godot#28769]
**Godot version:**
b96cd57

**OS/device including version:**
Windows 10, 64 Bit

**Issue description:**
The mono logfile shows Godot having trouble finding mscorlib as it is using a wrong directory separator (uses `/` instead of `\` ) and also attaches ".dll" twice to mscorlib. Also notice the `\/`:

> Config attempting to parse: 'C:\Program Files\Mono\etc\mono\config'. (in domain Mono, info)
> Image addref mscorlib[0000017110CC35F0] (asmctx DEFAULT) -> C:\Program Files\Mono\lib\\/mono/4.5/mscorlib.dll[0000017110DC2050]: 3 (in domain Mono, info)
> Prepared to set up assembly 'mscorlib' (C:\Program Files\Mono\lib\\/mono/4.5/mscorlib.dll) (in domain Mono, info)
> AOT: image 'C:\Program Files\Mono\lib\\/mono/4.5/mscorlib.dll.dll' not found: The system cannot find the file specified.
>  (in domain Mono, info)
> AOT: image 'C:\Program Files\Mono\lib\\/mono/aot-cache/amd64/mscorlib.dll.dll' not found: The system cannot find the path specified.
>  (in domain Mono, info)
> Assembly mscorlib[0000017110CC35F0] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
> Assembly mscorlib[0000017110CC35F0] added to domain GodotEngine.ToolsDomain, ref_count=2 (in domain Mono, info)
> Image addref GodotSharpTools[0000017110CC2240] (asmctx DEFAULT) -> c:\Work\Godot\bin/GodotSharp/Tools/GodotSharpTools.dll[0000017110E50BB0]: 2 (in domain Mono, info)
> Prepared to set up assembly 'GodotSharpTools' (c:\Work\Godot\bin/GodotSharp/Tools/GodotSharpTools.dll) (in domain Mono, info)

**Steps to reproduce:**
1. Build Godot from source on Windows 10 from within x64 Native Tools Command Prompt for VS 2017: `scons platform=windows target=debug vsproj=yes module_mono_enabled=yes mono_static=yes -j5`
2. Start Godot and close Godot once the project manager shows up
3. Open the generated mono logfile

**Minimal reproduction project:**
Opening the project manager is enough to reproduce the problem.

**Comment by neikeq** [comment]
The log shows it found mscorlib just fine in `C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll`. Yes, the path is not using backward slashes as it should on Windows, and it's also adding an extra slash, but it's still a valid one.

The `.dll` being attached twice is for the path to the AOT compiled image. The first one is to match the assembly extension, which is `.dll` on all platforms. The second one is the dynamic linked library extension, which would be `.so` and `.dylib` on Linux and macOS.
