### ISSUE TITLE
Add gdnative binding for parsing JSON for ease of use & code completeness 

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot#28775]
Currently, the GDNative bindings for Dictionaries only contain export functionalities to JSON. In the following form (as can be found in _\modules\gdnative\gdnative\dictionary.cpp_):

```
godot_string GDAPI godot_dictionary_to_json(const godot_dictionary *p_self) {
	godot_string raw_dest;
	String *dest = (String *)&raw_dest;
	const Dictionary *self = (const Dictionary *)p_self;
	memnew_placement(dest, String(JSON::print(Variant(*self))));
	return raw_dest;
}
```
The reverse functionality is however not implemented and thus there's no easy way to parse a String (read from some file) to a Dictionary. According to me this is a missing functionality that would have huge benefits when properly implemented. The JSON parsing functionalities are already part of the engine (as found in _core\io\json.h_) and would require no heavy lifting at all.

I propose to add something similar to this (!!! I haven't tested this!!!):

```
godot_dictionary GDAPI godot_dictionary_from_json(const godot_string *p_self) {
	godot_dictionary raw_dest;
	Dictionary *dest = (Dictionary *)&raw_dest;
	const String *self = (const String *)p_self;
	memnew_placement(dest, Dictionary(JSON::parse(Variant(*self))));
	return raw_dest;
} 
```
According to me this would be a good idea to add to the engine's functionalities. 
What is the community's opinion on this?

**Comment by karroffel** [comment]
The `to_json` is only there for compatibility reasons. The proper way to deal with JSON data is to use the JSON singleton directly in whatever bindings are used.

**Comment by 2shady4u** [comment]
Okay, then I'll close this issue.
Is there any plan on removing this .to_json() in the future? It confuses me (and others) that this might be the proper way to interact with JSON through a Dictionary. 

Might a commented line in the spirit of 
`//For compatibility reasons only. Using the JSON singleton for interaction with JSON is recommended`
be useful for making this clear to the junior user?

**Comment by 2shady4u** [comment]
I'm just going to leave this here for any future stranded travellers:

 ```
   Dictionary json_dictionary = JSON::get_singleton()->parse(String("{\"id\":1,\"name\":\"TheDuriel\"}"))->get_result();
    String json_string = JSON::get_singleton()->print(json_dictionary);
    Godot::print("id: " + (const String &)json_dictionary["id"]);
    Godot::print("name: " + (const String &)json_dictionary["name"]);
    Godot::print("full json_string: " + json_string);
```

And naturally don't forget to add the includes at the top!!!
```
#include "JSON.hpp"
#include "JSONParseResult.hpp"
```
