### ISSUE TITLE
Error is displayed in editor when trying to infer type from RandomNumberGenerator methods

### ISSUE THREAD

**Issue by scurvycapn** [godotengine/godot#28777]
**Godot version:** 3.1.1.stable.official

**OS/device including version:** Windows 10 x64

**Issue description:** When using statically typed GDScript, the methods under RandomNumberGenerator will display the following error message in the editor if trying to infer the type of the variable: **Assigned value does not have a set type, variable type cannot be inferred**

Seeing as these methods have defined return types (float or int depending on the method), I wouldn't think this should be the case. If the type is explicitly defined, no error is displayed and the code works as expected.

```gdscript
func test_random():
	var r = RandomNumberGenerator.new()
	r.randomize()
	# The following display the above mentioned error in the editor
	var x := r.randf()
	var y := r.randf_range(1.0, 2.0)
	var z := r.randfn(1.0, 1.0)
	var a := r.randi()
	var b := r.randi_range(1, 10)
	# The following do not display the error
	var c : float = r.randf()
	var d : float = r.randf_range(1.0, 2.0)
	var e : float = r.randfn(1.0, 1.0)
	var f : int = r.randi()
	var g : int = r.randi_range(1, 10)
```

**Steps to reproduce:** Attempt to infer a variable using one of the above methods.

**Minimal reproduction project:** [RandomInferTest.zip](https://github.com/godotengine/godot/files/3160416/RandomInferTest.zip)

**Comment by YeldhamDev** [comment]
The creation of the variable `r` is not typed, writing it like this makes the error go away:
`var r := RandomNumberGenerator.new()`

**Comment by scurvycapn** [comment]
> The creation of the variable `r` is not typed, writing it like this makes the error go away:
> `var r := RandomNumberGenerator.new()`

Oh man, I can't believe I missed that. Yeah, all is fine.
