### ISSUE TITLE
Merge H and V BoxContainer functionality into ListContainer

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#28779]
Currently we have two nodes providing identical functionality for sorting control nodes in a list. H and Y BoxContainer respectively. Both extend BoxContainer.

The idea would be to take the opportunity for breaking changes in 4.0, and merge both of these nodes into one: ListContainer. With a simple bool to flip between H and Y.

This would also allow for swapping the behavior on the fly, which could be pretty cool.

**Comment by Jummit** [comment]
Is it just me, or are HBoxContainer and VBoxContainer extremely easy to mix up? I always end up adding for the wrong node. This would add another step to making a HBoxContainer, but that isn't that bad.

**Comment by volzhs** [comment]
yeah, current HBox and VBox are easily distinguishable in scene tree dock by its node icon.

**Comment by KoBeWi** [comment]
IMO there's no need to change the name. BoxContainer is fine, as that's how it's called in other GUIs (or at least in Java).

**Comment by Calinou** [comment]
Merging both classes together would make https://github.com/godotengine/godot/pull/36040 easier to implement, but reduz was against it last time I asked.

**Comment by KoBeWi** [comment]
Closing the issue in favor of this proposal, which covers it: https://github.com/godotengine/godot-proposals/issues/3558
