### ISSUE TITLE
Scale doesn't applied to MeshInstance when is dragged directly to Viewport

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28788]
**Godot version:**
3.2 df18c8c

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I drag scene with MeshInstance with scale 0.3 to viewport, then sometimes scale is reset to 1.
When I drag same scene to Scene Tree, then everything works fine.

**Steps to reproduce:**
https://streamable.com/oi1ay

**Comment by mbrlabs** [comment]
I have a similar issue, that i think is connected to this one. If you drag a rotated scene into the viewport it's getting reset as well. 

I'm looking into this!
