### ISSUE TITLE
Allow 3D viewports to be independant of each other.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#28795]
![Captura de pantalla de 2019-05-09 23-33-15](https://user-images.githubusercontent.com/19626687/57502817-0fb8ea00-72b3-11e9-83e6-9b0bb51be90d.png)

As you can see in my picture I've tried to separate the level from the player layer, and I though I could set it up as a 2D game by using viewports, as I wanted to set up a 2D background parallax layer behind the 3D scene.
So I set up two viewports in diferent 2D scenes that render each one a diferent 3D scene so I could code it like a 2D game.
However even by doing this, it sort of render both scenes but also render the other 3D scene twice, using each diferent camera.

I think this could be a neat feature as will allow to make 3D games but code them like if they were 2D games.

**Comment by bojidar-bg** [comment]
Have you tried checking the "Own World" property?

**Comment by ca3games** [comment]
> Have you tried checking the "Own World" property?

Thanks.
