### ISSUE TITLE
Deprecate .pcz and use plain .zip instead

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2879]
Cloned from #2788:

@reduz:
> How about just deprecating the .pcz extension and use zip? We can make the exporter also write zips as an option to pck.

@punto-:
> Writing zips would be great, I've needed to create and debug my own pcks
many times.

> For the extension I don't mind either way, zips have many names nowadays,
starting from the first Quake packages (that's actually where I found out
about minizip, the library we use to read zips, the original Quake source),
but also IPA, APK, etc. I suspect their reasoning is just to stop the
operating system (and random users on some cases) from handling them, and
to possibly associate the extension with their own program, which I'm not
sure it's worth it for us.. We did have to rename the templates package for
similar reasons a while ago..

**Comment by DriNeo** [comment]
And why not .7z ?

**Comment by bojidar-bg** [comment]
@DriNeo As it is LGPL?

**Comment by akien-mga** [comment]
I think the idea is to use zip with minizip as it's very lightweight. And basically .tpz is already a zip file IIUC, so it's mostly a matter of changing the extension.
