### ISSUE TITLE
CPU Particles 2D left over from previous instance

### ISSUE THREAD

**Issue by marooncarl** [godotengine/godot#28790]
**Godot version:**

3.1.1.stable.official

**OS/device including version:**

Windows 7 (64-bit)
CPU: AMD Phenom II X4 945
GPU: Nvidia GeForce GTX 960
Driver version: 430.39

**Issue description:**

When creating multiple instances of a scene with CPU particles, if the scene is freed before the particle system completes, then the next scene will show the particles from the previous scene for one frame.  The particle system is one shot.  Happens in both GLES2 and GLES3.
Expected: No left over particles when creating a new scene, even if the previous one was cut off early.

**Steps to reproduce:**
1. Create a scene containing CPUParticles2D.  Turn on one shot.
2. Add a timer to the particles scene that frees the instance before the particle system is finished.
3. Create a scene that creates a new instance of the particle scene repeatedly.

**Minimal reproduction project:**

[CPU Particles Left Over.zip](https://github.com/godotengine/godot/files/3163949/CPU.Particles.Left.Over.zip)

**Comment by clayjohn** [comment]
Started looking into fixing this, but it is already fixed in current master!! :)
