### ISSUE TITLE
Comparisons fail with nested arrays retrieved from JSON.parse

### ISSUE THREAD

**Issue by Jeto143** [godotengine/godot#28797]
**Godot version:**
3.1 / 3.1.1

**Issue description:**
After retrieving an array of arrays from `JSON.parse`, inner arrays are not comparable with normal arrays in any way. Any comparison will return false.

**Steps to reproduce:**
```
var not_from_json = [[0, 2]]
var from_json = JSON.parse('[[0, 2]]').result

print(not_from_json)				# [[0, 2]]
print(from_json)				# [[0, 2]]

print(typeof(not_from_json) == TYPE_ARRAY)	# True
print([0, 2] in not_from_json)			# True
print(not_from_json.has([0, 2]))		# True
print(not_from_json[0] == [0, 2])		# True
	
print(typeof(from_json) == TYPE_ARRAY)		# True
print([0, 2] in from_json)			# False
print(from_json.has([0, 2]))			# False
print(from_json[0] == [0, 2])			# False
```

**Comment by bojidar-bg** [comment]
This is likely related to mismatched types, since JSON parses all numbers as floats/reals.
Doing this works:
```
print(from_json[0] == [0.0, 2.0])		# True
```

**Comment by Jeto143** [comment]
Oh, right. In JS, `2 === 2.0` though (because there's only one `number` type so they're exactly the same). 

Would parsing numbers without a floating point into integers be possible? That's what other languages (PHP, for instance) do. Can be very counter-intuitive otherwise.

I can create another more specific issue or rename this one if need be, but I think that'd be a decent improvement.

**Comment by 2shady4u** [comment]
I would argue the opposite actually.

```
extends Node

var example_dict = [{"value":3.2},{"value":3.0}]

func _ready():
	var printed_json = JSON.print(example_dict)
	print(printed_json)
```

Godot output:
`[{"value":3.2},{"value":3}]`

so after parsing this JSON again the first value would be an float while the second one would be an integer. 

Certainty that the output will always be a float is a good thing and you can always easily parse it to an integer if you so require.

**Comment by Jeto143** [comment]
> so after parsing this JSON again the first value would be an float while the second one would be an integer which could mess things up.

Why? That `JSON.print` line would accordingly need to return `"[{"value": 3.2}, {"value": 3.0}]"` then.

Here's how it works in Python for instance: 
https://onlinegdb.com/ByQ0IBXh4

I really don't see a good reason not to go this way.

**Comment by 2shady4u** [comment]
Previous discussion regarding the same thing:
https://github.com/godotengine/godot/issues/9499

**Comment by Jeto143** [comment]
Thanks, exactly the same topic indeed. After reading it though, I still fail to understand the reasoning behind not wanting to handle it more "naturally", as @punto- also mentioned there.

Again, pretty much all languages seem to do it (or at least, be able to do it) that way.

Guess moderators/devs can decide whether this deserves rediscussing or not (despite @reduz sharing his view on the other issue).

**Comment by KoBeWi** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/8830
Also #47502 might clear up the confusion.
