### ISSUE TITLE
Dictionary.hash() does not return equal values for equal data

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#2880]
```
var ev1={"id":1,"ash":2,"ssh":3}
var ev2={"id":1,"ash":2,"ssh":3}
print(ev1.hash()," ",ev2.hash())
```
This code shows different hash values for two equal objects. Is this an appropriate behavior, or the object's pointer is to be taken into account?

**Comment by vnen** [comment]
For the documentations, it should be based on the Dictionary's content. So this might be a bug (most likely never properly implemented).

**Comment by est31** [comment]
Right now the hash function bases solely on the pointer address.

Just taking the pointer address is fast and so on.

I think it should be kept, perhaps with protection from the problem that you might get the same hash if you create an object, hash it, it gets garbage collected, and you create a second object, and it gets the memory address of the first one. And one could add a second function that hashes solely on content.

**Comment by est31** [comment]
So it is definitely a bug with the documentation, but otherwise I'd keep it, or provide a memory address based hash function under another name.

**Comment by StraToN** [comment]
Should we just modify the documentation of Dictionary.hash() function to state that it is not based on the dictionary's content, but on its memory representation instead, and thus 2 instances containing the same value may not have same hashes ?

**Comment by akien-mga** [comment]
Yes I think that would do the trick. Regarding comparison of the memory *contents* and not addresses, I wonder if ```ev1 == ev``` returns true?

**Comment by StraToN** [comment]
ev1 != ev2 which seems legit as those are 2 different instances. One would have to redefine operator== (or design a new method) to determine whether 2 dictionaries have the same content.

**Comment by akien-mga** [comment]
Fair enough; but what's the point of the .hash() function then? Or maybe its purpose is not to compare instances but to just get the raw hash for whatever reason?

**Comment by vnen** [comment]
Variant also has a hash function. I don't see the usefulness of
Dictionary.hash(). I guess it's a matter of documentation then(?)
Em 24/11/2015 10:59, "Rémi Verschelde" <notifications@github.com> escreveu:

**Comment by Ovnuniarchos** [comment]
In the example above, the built-in GDScript hash() function gives equal results for the two dictionaries. I'll dig a bit later, but it leads me to think that the built-in really does deep inspection.

**Comment by akien-mga** [comment]
> In the example above, the built-in GDScript hash() function gives equal results for the two dictionaries. I'll dig a bit later, but it leads me to think that the built-in really does deep inspection.

I can't reproduce this. For me dict.hash() and hash(dict) give exactly the same results, i.e.:
```
	var ev1={"id":1,"ash":2,"ssh":3}
	var ev2={"id":1,"ash":2,"ssh":3}
	print(ev1.hash()," ",ev2.hash())
	print(hash(ev1)," ",hash(ev2))
```
Returns:
```
67703701 64469317
67703701 64469317
```

**Comment by reduz** [comment]
hmm maybe hash() should actually hash the internal values and not the pointer?
