### ISSUE TITLE
Area2D collision only reported when moving

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#28803]
**Godot version:**
3.1.1(stable)

**OS/device including version:**
Win7 64bit

**Issue description:**
Collision2D is there was no expected collision.when it is included and other collision2D actived is disable.

![collision2d_bug](https://user-images.githubusercontent.com/14953625/57521474-f6677a80-7352-11e9-8513-14205612871a.gif)

**Minimal reproduction project:**
[TestCollision.zip](https://github.com/godotengine/godot/files/3166079/TestCollision.zip)

**Comment by bojidar-bg** [comment]
Just to explain, the bug is that the change of an Area2D's collision shape from inactive to active is detected only if that Area2D is moving.

**Comment by CodeLazier** [comment]
I want to find an alternative, and find that even if it's not disable, I can't trigger collision events by creating code dynamically. I think this bug is more serious, which directly affects collision detection in games such as combat, action, etc.
ps:only when the game starts successfully triggers once

![bug2](https://user-images.githubusercontent.com/14953625/57703074-e53fa600-7691-11e9-81ed-6d836b18193f.gif)

[TestCollision2.zip](https://github.com/godotengine/godot/files/3178042/TestCollision2.zip)

====================================
craete collision2d key code:
func _createCollsion(create:bool):
	if !create:
	 $Area2D.call_deferred("remove_child",$Area2D/CollisionShape2D)
	else:
		var c=CollisionShape2D.new()
		c.name="CollisionShape2D"
		var r=RectangleShape2D.new()
		r.extents=Vector2(60,13)
		c.shape=r
		$Area2D.call_deferred("add_child",c)
