### ISSUE TITLE
Control node (TextureRect) scale not smooth with pivot offset

### ISSUE THREAD

**Issue by georgwacker** [godotengine/godot#28804]
**Godot version:**
3.1.1-stable

**OS/device including version:**
Windows 10 - 64bit

**Issue description:**
With a pivot offset on a Control node (TextureRect) other than the default (e.g. in the center of the rect), the scale transformation will wiggle the control around. This is most apparent, if one tries to slowly annimate the scale property.

**Problem source:**
https://github.com/godotengine/godot/blob/ecceabea7e74b56080c8deacc4323ac18b4b47c9/scene/gui/control.cpp#L453 
In the function _update_canvas_item_transform() there is a workaround to avoid flickering when moving the pivot offset. What ends up happening is that the pivot point gets rounded on every transform, resulting in a choppy animation. Regardless if pixel snap is enabled or not.

I compiled Godot without this workaround and the problem was fixed. I did not find a regression doing so, I was able to move the pivot around without flickering. 

**Steps to reproduce:**
- add TextureRect
- set pivot offset to the center
- scale the rect on x or y axis

**Minimal reproduction project:**
[ScalePivotBug.zip](https://github.com/godotengine/godot/files/3166020/ScalePivotBug.zip)

**Comment by jgodfrey** [comment]
I'm noticing this same issue on a TextureButton object in the official 3.2 stable Windows build. It's unclear to me what the state of this bug or the mentioned fix is.

Should I still be seeing this in 3.2?
