### ISSUE TITLE
Cursor position in editor problem

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#28805]
**Godot version:**
godot 3.1.1(stable)

**OS/device including version:**
win7 64bit

**Issue description:**
When AnimationPlayer playing, the cursor entered into control is automatically reset in editor

![editor_bug](https://user-images.githubusercontent.com/14953625/57527260-d25f6580-7361-11e9-95f2-12b8b929de6c.gif)

Minimal reproduction project:
same #28803

**Comment by KoBeWi** [comment]
Still valid in 3.2.3 rc3

**Comment by Zylann** [comment]
I could not figure out how to reproduce with the old project so I made a new one in Godot 3.4 rc1:
[CursorPositionDuringAnimation.zip](https://github.com/godotengine/godot/files/7446788/CursorPositionDuringAnimation.zip)
I could not reproduce the issue.

**Comment by Calinou** [comment]
Closing per @Zylann's comment.
