### ISSUE TITLE
HBoxContainer doesn't shrink after child controls shrink

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28818]
**Godot version:**
3.1

**OS/device including version:**
macOS 10.14.4

**Issue description:**
<img width="228" alt="Screen Shot 2019-05-10 at 10 46 31 PM" src="https://user-images.githubusercontent.com/6002340/57555868-bbc30980-7375-11e9-9198-5a4d089aff89.png">

Setting rect_min_size.x on a button that's in a HBoxContainer to a value larger than the container (and its parent, a PopupPanel) will result in the HBoxContainer keeping that width even after the button is shrunk later on:

```
extends PopupPanel

func _ready():
    connect("minimum_size_changed", self, "_minimum_size_changed")
    connect("resized", self, "_resized")
    
    $HBoxContainer.connect("minimum_size_changed", self, "_box_minimum_size_changed")
    $HBoxContainer.connect("resized", self, "_box_resized")
    
    call_later(self, "_grow", 1)
    call_later(self, "_shrink", 2)
    call_later(self, "_print_sizes", 2.5)

    show()
    
func _grow():
    log_message("growing")
    $HBoxContainer/Button.rect_min_size.x = 800
    
func _shrink():
    log_message("shrinking")
    $HBoxContainer/Button.rect_min_size.x = 200
    
func _minimum_size_changed():
    log_message("PopupPanel.rect_min_size: " + str(rect_min_size))
    
func _resized():
    log_message("PopupPanel.rect_size: " + str(rect_size))
    
func _box_minimum_size_changed():
    log_message("HBoxContainer.rect_min_size: " + str($HBoxContainer.rect_min_size))
    
func _box_resized():
    log_message("HBoxContainer.rect_size: " + str($HBoxContainer.rect_size))
        
func _print_sizes():
    log_message("final sizes:")
    _minimum_size_changed()
    _resized()
    _box_minimum_size_changed()
    _box_resized()
    
func log_message(message):
    print(str(OS.get_ticks_msec() / 1000.0) + "s - " + message)
    
func call_later(call_target, function_name, seconds_as_float):
    var timer = Timer.new()
    timer.connect("timeout", call_target, function_name)
    timer.set_wait_time(seconds_as_float)
    timer.one_shot = true
    timer.start()
    call_target.add_child(timer)
```

The example is contrived in order to be minimal, but having such a larger size can be possible in intermediate states before coming to a final size, especially when there are other child controls in the HBoxContainer and you don't know their size.

**Steps to reproduce:**
Run the attached project and wait for it to finish. The expected behaviour is that the HBoxContainer shrinks eventually.

**Minimal reproduction project:**
[size.zip](https://github.com/godotengine/godot/files/3168083/size.zip)

**Comment by swarnimarun** [comment]
I think that this pretty much is the "The Expected Behaviour" let me break it down,
- The `rect_size `is increased because of increasing `minimum_size `obviously(min_size has been less or equal).
- Then on decreasing the `minimum_size`, you don't see a change as the min_size relation is still true. It's still less than the `rect_size`.

I don't think this is something that devs would intend to add.

**Comment by swarnimarun** [comment]
Also @clayjohn this would be entirely part of the GUI which is part of the scene and not related to the core is the core tag acceptable/appropriate??

**Comment by mitchcurtis** [comment]
> I think that this pretty much is the "The Expected Behaviour" let me break it down,
> 
> * The `rect_size `is increased because of increasing `minimum_size `obviously(min_size has been less or equal).
> * Then on decreasing the `minimum_size`, you don't see a change as the min_size relation is still true. It's still less than the `rect_size`.
> 
> I don't think this is something that devs would intend to add.

So is there a recommended way of doing this in that case? Are controls not responsible for managing their size based on their children? Is the user really expected to have to shrink a control after its children change size? :/

For what it's worth, I ended up ditching HBoxContainer altogether and manually positioning items.

**Comment by swarnimarun** [comment]
@mitchcurtis I would say change the rect_size not the rect_min_size.... :/

**Comment by clayjohn** [comment]
@swarnimarun the topic tags don't correspond to those folders in the top level of the repo. In this context 'core' does not mean stuff in the core folder. Also, there is no tag for 'GUI' or 'Scene'.

**Comment by mitchcurtis** [comment]
> @mitchcurtis I would say change the rect_size not the rect_min_size.... :/

That goes against the point of having an item manage the size of its children. It's the same in other UI toolkits like Qt: you can't set the width and height of items because the layout engine stores the calculated values in those properties.

https://docs.godotengine.org/en/latest/tutorials/gui/gui_containers.html#container-layout says:

> When a Container-derived node is used, all children Control nodes give up their own positioning ability. This means the Container will control their positioning and any attempt to manually alter these nodes will be either ignored or invalidated the next time their parent is resized.

**Comment by mitchcurtis** [comment]
That quote was actually about positioning, but I imagine it's the same for size - after all, what happens if you set the size flags to expand + fill? The size that you specify will be overwritten when the container resizes that item.

https://godotengine.org/qa/23362/buttons-in-vboxcontainer-containers-not-resizable?show=23370#a23370 also mentions it.

**Comment by swarnimarun** [comment]
Ah. It would make sense for Container nodes. So probably it should be specific to Container Nodes, and it's children. Will look into it, and PR a fix today.

**Comment by robbertzzz** [comment]
Found this page after I had a similar issue, and can confirm that appropriately setting the size flags does solve it. Shouldn't this bug be closed?

**Comment by KoBeWi** [comment]
I actually encountered a bug that sounds like this issue.
![gbw8bvXVaX](https://user-images.githubusercontent.com/2223172/87720933-fd3f1800-c7b5-11ea-9734-e7fa2c6496f4.gif)
I add text to label that will expand the container, then undo. The container doesn't return to the original size, but when I save the scene and reload it, the container magically shrinks. I've seen it many times where container has some "internal size" not matching its current size and it fixes itself on scene reload.

**Comment by MaaaxiKing** [comment]
What if there was a property on the Container itself for shrinking its size in this case?

**Comment by Avantir-Chaosfire** [comment]
A bit late to the party, for future reference for anyone who finds this thread, setting a container's (e.g. HBox or VBox) RectSize to a zero vector will shrink it to the size of the child controls. So the easiest way to achieve this constant shrinking is to just put `RectSize = new Vector()` into the physics process method of the container.
