### ISSUE TITLE
Android 4.3 export to GLESv2; fails 'dlopen' for libGLES3.dll

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#28813]
**Godot version:**

Godot Engine v3.1.1.stable.official
Also have the newest nightly Godot as maintained by Calinou (thanks!), but I don't necessarily want to test in that due to a bug that's causing my inherited scenes to wipe back to base repeatedly (not the topic of this bug report!). inb4 the fifth time I setup all 10+ scenes...

**OS/device including version:**

Fedora 30 (XFCE) Linux
Intel Core i7 920, AMD Radeon RX590

Samsung Galaxy S4 (Android 4.3, kernel 3.4.0)
Exynos 5410 Octa (4x1.6 GHz Cortex-A15 & 4x1.2 GHz Cortex-A7)
PowerVR SGX544MP3 (I noticed there's some performance issues reported for this device, but this doesn't seem anywhere near performance related)

**Issue description:**

The application crashes immediately upon launch on the device, whether I launch it manually, or adb launches it. `adb logcat godot:V DEBUG:V AndroidRuntime:V ValidateServiceOp:V \*:S` returns
```
--------- beginning of /dev/log/system
E/AndroidRuntime(26694): FATAL EXCEPTION: main
E/AndroidRuntime(26694): java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libGLESv3.so" needed by "libgodot_android.so"; caused by empty/missing DT_HASH in "libGLESv3.so" (built with --hash-style=gnu?)
E/AndroidRuntime(26694): 	at java.lang.Runtime.loadLibrary(Runtime.java:362)
E/AndroidRuntime(26694): 	at java.lang.System.loadLibrary(System.java:525)
E/AndroidRuntime(26694): 	at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:40)
E/AndroidRuntime(26694): 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:434)
E/AndroidRuntime(26694): 	at org.godotengine.godot.Godot.onCreate(Godot.java:598)
E/AndroidRuntime(26694): 	at android.app.Activity.performCreate(Activity.java:5372)
E/AndroidRuntime(26694): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
E/AndroidRuntime(26694): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
E/AndroidRuntime(26694): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
E/AndroidRuntime(26694): 	at android.app.ActivityThread.access$700(ActivityThread.java:159)
E/AndroidRuntime(26694): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
E/AndroidRuntime(26694): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26694): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(26694): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
E/AndroidRuntime(26694): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26694): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(26694): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
E/AndroidRuntime(26694): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(26694): 	at dalvik.system.NativeStart.main(Native Method)
```

This error obviously shows that despite my best efforts (i.e., setting everything I can find to GLES2.. also tried restarting in GLES3 mode and then returning to GLES2.. also tried changing texture compression settings... also tried changing the 32 bit framebuffer option...) the error must not be my doing. I assume some settings aren't getting modified in the already built Android export template?

**Steps to reproduce:**
I'm not sure? Obviously, building for GLESv2 on Android is possible... but maybe the export templates are bugged in that they don't allow choice between them? I don't know the engine like the back of my hand yet, so I'm not even sure where to look in the source code for the export-parameter-passing-place

**Comment by clayjohn** [comment]
I think this may be caused in part because the android platform does not link against GLESv2 here.

https://github.com/godotengine/godot/blob/ecceabea7e74b56080c8deacc4323ac18b4b47c9/platform/android/detect.py#L304

I added it in my PR https://github.com/godotengine/godot/pull/28518

**Comment by akien-mga** [comment]
I think we might need to attempt `dlopen()`-ing `libGLESv3.so` manually instead of linking it at compile time (which requires it to be present on the system).

I don't get this issue on a Samsung Galaxy S4 which is GLES2 only but running LineageOS 14.1 (Android 7.1.2). I guess recent Android versions might have a `libGLESv3.so` stub even when their drivers don't support it, but apparently it's not the case for Android 4.3.

**Comment by akien-mga** [comment]
I think this is specific to Android 4.3, which was the first release to support OpenGL ES 3.0 but maybe did not mandate the library to be included for GPUs that don't support it.

IMO we're unlikely to fix this, as we'll likely soon drop support for Android 4.3 (API level 18).

For anyone who really wants to support Android 4.3 and runs into this issue, you can this:
```diff
diff --git a/platform/android/detect.py b/platform/android/detect.py
index 8b62360888..b8b1bee0d8 100644
--- a/platform/android/detect.py
+++ b/platform/android/detect.py
@@ -282,7 +282,7 @@ def configure(env):
 
     env.Prepend(CPPPATH=['#platform/android'])
     env.Append(CPPDEFINES=['ANDROID_ENABLED', 'UNIX_ENABLED', 'NO_FCNTL'])
-    env.Append(LIBS=['OpenSLES', 'EGL', 'GLESv3', 'GLESv2', 'android', 'log', 'z', 'dl'])
+    env.Append(LIBS=['OpenSLES', 'EGL', 'GLESv2', 'android', 'log', 'z', 'dl'])
 
 
 # Return NDK version string in source.properties (adapted from the Chromium project).
```
