### ISSUE TITLE
Facing linker error when using custom template for export in iOS

### ISSUE THREAD

**Issue by atologist-pratik** [godotengine/godot#28822]
**Godot version:**
Godot 3.1 Stable

**OS/device including version:**
MacOS High Sierra 10.13.6

**Issue description:**
Facing linker error when using custom template for export in ios.

**Steps to reproduce:**
NOTE: i'm using MacOS, Xcode 10.1 with developer account and iPhone device(iPhone8).

1. I get Godot source for 3.1 from this [Link](https://github.com/godotengine/godot/tree/3.1).
2. After i compile for iOS using below command.
```
scons p=iphone tools=no target=debug arch=arm

scons p=iphone tools=no target=debug arch=arm64
```
as result i get two ***.a** files in **godot/bin** folder.

**libgodot.iphone.debug.arm.a** and **libgodot.iphone.debug.arm64.a**

3. use below command to generate **fat.a** 
```
lipo -create bin/libgodot.iphone.debug.arm64.a bin/libgodot.iphone.debug.arm.a  -output bin/libgodot.iphone.debug.fat.a
```
as result i get **libgodot.iphone.debug.fat.a** in godot/bin folder.

4. i copied above **libgodot.iphone.debug.fat.a** from **godot/bin** to **godot/misc/dist/ios_xcode** folder (replaced).

5. i copied **ios_xcode** folder in documents, rename **ios_xcode** to **iphone**, then zip it. i get result **iphone.zip** in Document folder.

6. Then i replace iphone.zip with `/Library/Application\ Support/Godot/templates/3.1.stable`

7. Then i export project then try to run in device. i get issue as below.

```
Undefined symbols for architecture arm64:
  "_z_error", referenced from:
      _inflate_codes in FBLogin.a(ftgzip.iphone.debug.arm64.o)
  "_z_verbose", referenced from:
      _inflateInit2_ in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflate in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflateEnd in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflateReset in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflate_blocks_reset in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflate_codes_free in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflate_blocks_new in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Is i'm doing anything wrong in compile? How do i resolve this one?

If i repeat above process for Godot 3.1.1 stable version my machine freeze, can't do anything after. had to restart using power switch.

**Comment by vini-guerrero** [comment]
Does it work the export for you with the default official ios template tpz files?

**Comment by pratikprajapati30** [comment]
yes, if i used official `ios template tpz` [Link for 3.1](https://downloads.tuxfamily.org/godotengine/3.1/) then its working just fine. problem comes when i use custom compiled binary for export.

**Comment by atologist-pratik** [comment]
yes, if i used official ios template tpz [Link for 3.1](https://downloads.tuxfamily.org/godotengine/3.1/) then its working just fine. problem comes when i use custom compiled binary for export.

**Comment by akien-mga** [comment]
You can't mix versions like this. If you build custom templates from the `3.1` branch, you should also build your editor binary from the same branch. Your export templates and editor binary have to be built from the exact same commit.

**Comment by atologist-pratik** [comment]
@akien-mga  Thanks for your comment, finally i'm able to compile custom template for iOS.
@vini-guerrero 
I create step-by-step process to generate custom template for iOS and i also create share module compiled binary for iOS.

Those who are also confused please check below link.

[Create custom build for iOS](https://github.com/atologist-pratik/CustomBuildForGodot)

if i get time i'll make video for this.

And i'm closing this issue.

Happy coding.

**Comment by vini-guerrero** [comment]
@atologist-pratik That's awesome! I haven’t tried that module on iOS yet. However, most of my issues are happening when using a custom modules that has any settings coming from a third party lib, such as this one ( https://github.com/DrMoriarty/godot-facebook/tree/master/GodotFacebook/ios ) what would be the Manifest.xml in Android... Aparently any linker flags are working for me and even when XCode says it found the frameworks and the warning signs goes away, the project crashes after compiled. ( Same happens to firebase and admob )

**Comment by atologist-pratik** [comment]
@vini-guerrero for (https://github.com/DrMoriarty/godot-facebook/tree/master/GodotFacebook/ios) i successfully manage to compile and run in iOS device. For me Facebook login is working perfectly in iOS. For Android work is in progress. 
i'll let you know once its complete

**Comment by vini-guerrero** [comment]
@atologist-pratik do you have the compiled .a file (debug/release) with facebook uploaded somewhere?

**Comment by atologist-pratik** [comment]
@vini-guerrero  you can find compiled .a file for debug in below link. 

[FBLoginGodot](https://github.com/atologist-pratik/FBLoginGodot)

If you still confuse of facing above issue, wait till this weekend i'm making full video on this.

**Comment by vini-guerrero** [comment]
Awesome! Thanks @atologist-pratik

**Comment by atologist-pratik** [comment]
hey @vini-guerrero , i need you help if you can?
Please have a look at this 

[https://github.com/godotengine/godot/issues/28955](https://github.com/godotengine/godot/issues/28955)
