### ISSUE TITLE
Make .import files hidden

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28826]
**Godot version:**
3.1.1

**Issue description:**
There were complains about .import files, that they clutter the directories and should be moved elsewhere or removed etc. etc. I agree that they are problematic, because e.g. it's harder to browse files. By default they are sorted by name and it results in png/import/png grid in directory view. Ofc you can change sorting to per type and it makes things a lot easier, but you need to do it for each folder (at least on Windows), which is not a perfect solution.

So how about just making the .import files hidden? On Windows it's a file flag, for Linux I guess all import files would need to start with a dot in name. Hiding these files would make the asset directory much more friendly to browse. It of course introduces problems, like since you can't see .import files, you might not be aware that they are here, which might create problems with moving or deleting files from system explorer. However, Godot should handle .imports for files moved/deleted externally and that's another issue. I guess when it's solved, making .import files hidden shouldn't have more downsides.

I've seen this request mentioned in comments, like [here](https://github.com/godotengine/godot/issues/10583#issuecomment-328334146) or [here](https://github.com/godotengine/godot/issues/9291#issuecomment-320751177), but it never got its own issue, so here is one.

**Comment by slapin** [comment]
If you hide something which exists it is not normal. It might be fine to have option, but that should not be default. This is developer tool. Also the files are in completely separate directory, why do you go in there if you don't want to?

**Comment by slapin** [comment]
Or you ask about files which are created for import parameters? These should not be hidden.

1. They are part of your project because your settings are kept there. They should be added to your version control too, if you do not want to lose import options.
2. Thay are not clutter, they are functional files. And you should be aware of their presence and why they are needed. Pretending they do not exist will do you nothing good, they are project data, the same as your asset files.

**Comment by KoBeWi** [comment]
> Or you ask about files which are created for import parameters?

Yes, these ones. My point is, you are not supposed to edit them manually. You edit all the import settings inside Godot, so these files are totally irrelevant for you. Or that's how it should be. Cool, they exist and are important, but I don't see any reason why it shouldn't be done behind the scenes, so you don't worry how it works. And if you do care to do anything with them (dunno what would you), you can enable visibility for hidden files on your OS if they were hidden.

**Comment by Calinou** [comment]
I think it's fine to leave them visible too. They contain important metadata which should be checked into version control, and making their name begin with a dot could mislead people into adding them into their `.gitignore`.

**Comment by NathanWarden** [comment]
These files are very important and should be in a place where it's obvious to the developer that they should be checked into version control or backed up. Hidden files typically start with a `.` and in Godot are automatically generated. It would completely break a project if the developer didn't back up the import meta files and had to recover it on another machine or in another folder.

**Comment by KoBeWi** [comment]
It could be at least optional. Although Unix systems with their .naming would be a problem here.

**Comment by Calinou** [comment]
> It could be at least optional.

This poses the issue of making documentation and tutorials more confusing, since the `.import` files could now have two potential names. Moreover, if both `file.import` and `.file.import` exist, which one would have priority?

**Comment by vnen** [comment]
Related: #24177

**Comment by KoBeWi** [comment]
Closing in favor of the proposal (see mention above).
