### ISSUE TITLE
Holding down single quote key, makes right arrow key pressed infinitely.

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#28825]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 8.1 with keyboard set to United States-International.

**Issue description:**
When I hold down the single quote key, with event 222, for half a second on my keyboard Godot thinks that right arrow key, with event 39, is being pressed infinitely and IsActionPressed is true because of it. Only way to stop the loop is to actually use right arrow key once on my keyboard.

**Steps to reproduce:**
Open a project, hold single quote key for half a second, see that right arrow is now showing up as IsActionPressed until you actually use right arrow key once.

**Minimal reproduction project:**
Setup a project with a input map on right arrow key so you can see the behaviour.

**Comment by KoBeWi** [comment]
@ScepticDope Can you still reproduce this in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3)? If yes, please attach a minimal reproduction project.

**Comment by ScepticDope** [comment]
@KoBeWi I tested it on Windows 10 1909 with both Godot_v3.2.3-rc4_win64 and Godot_v3.2.3-rc4_mono_win64.exe and I can't reproduce it anymore.

However I don't have the capacity to test it on Windows 8.1 anymore, it might have been a Windows 8.1- OS specific bug.

**Comment by KoBeWi** [comment]
So should be fine to close.

**Comment by ScepticDope** [comment]
In case anyone ever comes across this bug on Windows 8.1 or lower again in the future here is how to debug it with a minimal reproduction project:

Start a new project add a Node2D with a new script with the following code:

GDScript
```
func _process(_delta):
	if Input.is_action_pressed("ui_right"):
		print("right is pressed!")
```

C#
```
public override void _Process(float delta)
{
	if (Input.IsActionPressed("ui_right"))
	{
		Console.WriteLine("right is pressed C#!");
	}
}
```
