### ISSUE TITLE
Use Physics2DServer created rigidbody2d and KinematicBody2D not collision with StaticBody2D or Arae2d

### ISSUE THREAD

**Issue by myhalibobo** [godotengine/godot#28835]
Godot version:Godot_v3.1-stable_win64
Steps to reproduce:Run A and B separately for the demo
![temp](https://user-images.githubusercontent.com/8662169/57577441-6851d800-74a9-11e9-9c9d-04ace1e1252a.png)
![QQ截图20190512112742](https://user-images.githubusercontent.com/8662169/57577442-6ab43200-74a9-11e9-8024-f8d4b54a431e.png)

Minimal reproduction project:
[Physics2DServer.zip](https://github.com/godotengine/godot/files/3169694/Physics2DServer.zip)

**Comment by myhalibobo** [comment]
I've found the problem

**Comment by nthrack** [comment]
> I've found the problem
I'm in the same situation.
Can you explain the solution to the problem?

**Comment by nthrack** [comment]
> I've found the problem

@myhalibobo 
Can you explain the solution to the problem?
