### ISSUE TITLE
Modulate/Self Modulate Not Working On Sprite

### ISSUE THREAD

**Issue by zacharytyhacz** [godotengine/godot#28834]
**Godot version:** 3.2 beta + GLES2

**OS/device including version:** Mac OS High Sierra 10.13

**Issue description:** Transparent Sprite ( .png ) Self Modulate / Moduate not changing sprite VIA INSPECTOR

**Steps to reproduce:**
1. Import Image 
2. Create 2D scene / project ( GLES2 enabled )
3. Add TouchScreenButton or Sprite 2D node and apply the imported image to it.
4. Attempt to change self-modulate or modulate value in the Inspector ( NOT SCRIPT/CODE )
- Nothing effects the sprite image.

**Very Minimal reproduction project:**
[godot_bug_ssue.zip](https://github.com/godotengine/godot/files/3169657/godot_bug_ssue.zip)

I have other *.png files that work just fine ( in minimal project to show )  but this one imported .png image does not work with the modulate values in the inspector.

What is causing this? Is the png file import some how 'corrupted'? Is it there a certain import flag i need to check that was automatically set upon import? I've tried fiddling with many inspector values to get this sprite to change colors, but no luck.

**Comment by dankan1890** [comment]
I don't think it's a bug, the "modulate" and "self-modulate" functions simply apply a tint adding it to the existing one, so starting from black there's no difference.
Maybe you could expand the possibilities by adding a "colorize" function.

**Comment by zacharytyhacz** [comment]
> I don't think it's a bug, the "modulate" and "self-modulate" functions simply apply a tint adding it to the existing one, so starting from black there's no difference.
> Maybe you could expand the possibilities by adding a "colorize" function.

Hmm ok I didn't think that would the issue. Though, yes a colorize function is what I technically truely want, which is what I thought the modulate values would achieve. 

I'm going to close this issue as I thought it was a bug, but I was just mis-using the (self-)modulate values.

**Comment by Drachenbauer** [comment]
If you want to use modulate to color in stuff, the best option is to start with a white or light greyscaled graphic file.
For sample i made a character with a colorable hat.
For this i placed the areas of the hat as extra frames and made them white in the graphic-file.
so i can load them into separate Sprites2D-nodes and color them with modulate.
