### ISSUE TITLE
Viewport not clip control node input

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#28833]
**Godot version:**
<3.1>

[#5172](https://github.com/godotengine/godot/issues/5172)report the control not clip input, but I found viewport no work either.
I cannot find a simple way to let the control node not get gui_input when it's out of it's parent control node(with clip content) or a viewport. I dont understand why a node outside of a viewport
can still catch input, it makes no sense. 
What I can do now is check if the the parent get the input too.
![image](https://user-images.githubusercontent.com/9168814/57575774-c2d83d80-7483-11e9-97f9-3e1cde068416.png)
And I cannot use mouse_enter exit to check if the mouse is in parent box, because the final mouse enter/exit area is the blue area in the pic above, not only the parent block.

**Comment by Zylann** [comment]
Can reproduce in Godot 3.4 rc1
[ViewportControlClipInput.zip](https://github.com/godotengine/godot/files/7446878/ViewportControlClipInput.zip)

**Comment by Nukiloco** [comment]
This is still happening in Godot 3.5.
