### ISSUE TITLE
CSGMesh inspector lacks a material entry

### ISSUE THREAD

**Issue by eetson** [godotengine/godot#28844]
**Godot version:**
3.1.1

**OS/device including version:**
Win10

**Issue description:**
As of 3.1.1, CSGMesh has no material property in the inspector, unlike all other CSGPrimitives
![csgmesh-nomat](https://user-images.githubusercontent.com/43553709/57586882-56ccf800-74ca-11e9-9f11-c0d22dc1f372.jpg)

**Expected behavior:**
To be able to change the material of the CSGMesh just like any other CSGPrimitive
![expected](https://user-images.githubusercontent.com/43553709/57586930-1d48bc80-74cb-11e9-8df6-6508be46dbd6.jpg)

**Steps to reproduce:**
Add a CSGMesh node and look at it in the inspector

**Comment by clayjohn** [comment]
With a Mesh you can change the material on the Mesh resource itself! The CSG primitives don't have a mesh resource so the Material is exposed directly.

**Comment by akien-mga** [comment]
This has already been fixed by #27940 in the master branch.
