### ISSUE TITLE
Unable to set HBoxContainer/VBoxContainer Separation Custom Constant to 0 without changing first

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#28852]
**Godot version:**
3.1.1 (Mono)

**Issue description:**
When creating a new HBoxContainer/VBoxContainer (and maybe GridContainer but I haven't confirmed), there is a default Separation value that is not shown in the editor, and instead the value 0 is shown. There is an outstanding issue already to display the correct value #27947. In addition to this, if you actually want to set the Separation value to 0 you can't unless you set it to another value and then set it back. This likely applies to all Custom Constants that don't have a value, and where the editor shows an unassigned default value.

**Steps to reproduce:**

1. Add an HBoxContainer or VBoxContainer
2. Set the Separation value under Custom Constants to 0. **Nothing will happen. The container will still be using the default Separation value.**
3. Set the Separation to 1
4. Set the Separation value back to 0. The container will now have 0 Separation.

**Comment by volzhs** [comment]
related to #27947

**Comment by Megalomaniak** [comment]
Yep, fighting with this in GDScript right now, supposedly the separation is a theme property/constant, but the documentation is not at all useful for figuring out how to set it.

**Comment by KoBeWi** [comment]
Seems to be working correctly in 3.2.1
![m8MBg5VReM](https://user-images.githubusercontent.com/2223172/82616337-32bbf080-9bcd-11ea-917e-094ab9496d0d.gif)
Or is the issue about something else?

**Comment by andy-noisyduck** [comment]
@KoBeWi Yes, the checkbox setting fixes the issue I originally opened. I will close.

Not sure how long this has been fixed for. I haven't needed to use that setting since I opened the issue.
