### ISSUE TITLE
Going over words with CTRL and arrow doesn't work with non ascii characters

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28850]
**Godot version:**
3.2.dev.custom_build. ecceabe

**OS/device including version:**
Ubuntu 19

**Issue description:**
When I trying to go over words with CTRL and left or right arrow, then it stop before  end of word

Try to do this with this text
```
Dodawanie numeru właściciela
```

**Steps to reproduce:**
![output](https://user-images.githubusercontent.com/41945903/57618839-bb4c8d80-7584-11e9-910a-0a2c8f80bbb9.gif)

**Comment by raymoo** [comment]
If this is changed then IMO it should be based on unicode character class, so that punctuation doesn't count as part of words.
