### ISSUE TITLE
Scheduled PR review meetings

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#28853]
This issue is to notify contributors whenever we plan to review PRs together with @reduz and any available contributor on IRC.

PR review meetings always happen on **#godotengine-meeting** on Freenode IRC. Feel free to join and get involved in the review and discussion of pull requests with the rest of the team.

Commenting on this issue is restricted to core contributors who will post the time and date of upcoming PR review meetings. Subscribe to notifications on this issue to be notified of upcoming meetings.

Times will be given in UTC, you can use [timeanddate.com](https://www.timeanddate.com/worldclock/timezone/utc) or [timebie.com](http://www.timebie.com/std/utc.php) to convert to your local time.

Currently we don't have fixed times for those meetings, but this might change in the future if we find time slots which are convenient for the majority of core developers.

**Comment by akien-mga** [comment]
Meeting on Monday 13 May 2019 at 14:20 UTC (5 min from now).

**Comment by akien-mga** [comment]
Meeting on Monday 20 May 2019 at 13:00 UTC (now).

**Comment by akien-mga** [comment]
Meeting on Friday 24 May at 12:30 UTC (10 min from now).

**Comment by akien-mga** [comment]
Meeting on Tuesday 28 May at 13:00 UTC (2 hours from now).

**Comment by akien-mga** [comment]
Meeting on Friday 31 May at 12:00 UTC (1 hour from now).

**Comment by akien-mga** [comment]
Meeting on Wednesday 12 June at 12:00 UTC (3 hours from now).

**Comment by akien-mga** [comment]
Meeting on Thursday 18 July at 12:00 UTC (3.5 hours from now).

**Comment by akien-mga** [comment]
Meeting on Friday 19 July at 12:00 UTC (3.5 hours from now).

**Comment by akien-mga** [comment]
Meeting on Tuesday 23 July at 12:00 UTC (2 hours from now).

**Comment by akien-mga** [comment]
Meeting on Tuesday 6 August at 12:00 UTC (3.5 hours from now).

**Comment by akien-mga** [comment]
Meeting on Monday 26 August at 12:00 UTC (2 hours from now).

**Comment by akien-mga** [comment]
Meeting on Wednesday 28 August at 12:00 UTC (now).

**Comment by akien-mga** [comment]
Meeting on Monday 2 September at 13:00 UTC (24 hours from now), with focusing on GDScript PRs.

**Comment by akien-mga** [comment]
Meeting on Wednesday 25 September at 12:00 UTC (3 hours from now).

**Comment by akien-mga** [comment]
Meeting on Monday 28 October at 12:00 UTC (4 hour from now).

**Comment by akien-mga** [comment]
After some hiatus while stabilizing Godot 3.2 and then breaking everything in the `master` branch for 4.0, it's time to restart regular PR review meetings to hack away at the huge backlog that we accumulated.

We will start tomorrow with a PR review meeting focusing on PRs with label [`bug`](https://github.com/godotengine/godot/pulls?q=is%3Aopen+is%3Apr+label%3Abug) and authored by contributors who are present at the meeting, so that we can discuss them live with the author and progress quickly.

The meeting will be on #godotengine-meeting at this time:

**Tuesday 28 April at 18:00 UTC**.

**Comment by fire** [comment]
Here's a timezone list for those who don't use UTC time.

https://www.timeanddate.com/worldclock/fixedtime.html?p1=1440&iso=20200428T18&msg=Scheduled%20PR%20review%20meetings%20%28%2328853%29&sort=0

**Comment by mhilbrunner** [comment]
Closing, as this issue seems to have outlived its usefulness for now :)
