### ISSUE TITLE
I failed to install apk in my android phone

### ISSUE THREAD

**Issue by niu2x** [godotengine/godot#2885]
I can export project targeted to android. 
but the apk file can't be installed in my android device.
What's the common mistakes for a newer

**Comment by akien-mga** [comment]
Did you use an export template that matches the version of your engine? (i.e. 1.1 templates for Godot 1.1, or templates that were built from the same commit as your editor if you use a nightly build)

What is the error? What version of Android are you using? What device model?

**Comment by niu2x** [comment]
I made a wrong config about jar sign,
now it work,
thanks
