### ISSUE TITLE
InputEventMouse.global_position not correctly accounting for transformations

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#28855]
**Godot version:**
3.1.1 (Mono)

**Issue description:**
When adding Controls with manually specified positions, there are a number of scenarios where `global_position` gives incorrect results when handling `InputEventMouse` events through `_gui_input`.

I have not tested to see if the same happens with Node2D and the `_input_event` callback.

**Steps to reproduce:**
Create a wrapping control with a `_gui_input` handler to test events and print the `global_position`

1.  Negative Offset
Add a child control with Position (set in code or editor) to (-200, 0).
Click the _top left_ of the visible portion of the control (i.e. the very top left corner of the window). Expected global position is (0, 0) but `global_position` returns (**-200**, 0).

2. Positive Offset
Add a ColorRect child control with Position (set in code or editor) to (0, 500), with MinSize of (500, 500).
Click the _bottom right_ of the visible portion of the control. Expected global position is (500, 1000) but `global_position` returns (500, **1500**).

**Minimal reproduction project:**
[Testing-MouseGlobal.zip](https://github.com/godotengine/godot/files/3173722/Testing-MouseGlobal.zip)

**Comment by swarnimarun** [comment]
I can't seem to be able to reproduce it in the master branch of the Engine(Non-Mono). 
Have you tried this in the master or can someone else test and verify this problem?

I am using Windows 10 64bit, Master with commit at 89c37da

**Comment by silkentrance** [comment]
I experience the same behaviour with 3.3.1.stable.official (Non Mono)

However, if I add the same input handling code to the color rects, then the reported position and global_position will be just fine. It seems as if Godot applies the position of the control that is directly under the mouse as an offset to both the position and the global_position of the event.

**Comment by KoBeWi** [comment]
Fixed by #31915
