### ISSUE TITLE
Built-in methods/keywords highlighted when they shouldn't

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28866]
**Godot version:**
3.1.1

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/57664159-5a11d200-75f7-11e9-8eb7-b54a3617b7ad.png)
Method calls from other objects might use some words that are normally highlighted red. This shouldn't happen IMO (I mean, this should appear as normal member method call, i.e. blue).

**Comment by YeldhamDev** [comment]
CC @vnen

**Comment by vnen** [comment]
CC @Paulb23

**Comment by KoBeWi** [comment]
Still valid in 6831da6

**Comment by KoBeWi** [comment]
Fixed by #45479
