### ISSUE TITLE
Onion Skinning button should turn blue when enabled

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28868]
**Godot version:**
3.1.1

**Issue description:**
See title. Pretty much every other button in AnimationPlayer does this.

**Comment by YeldhamDev** [comment]
The thing is, the onion button is a menu, not a toggle. What could be done is make it work like the snap section in canvas editor, where there's a button dedicated to toggling it, and another to configure it:
![Screenshot_20190513_224544](https://user-images.githubusercontent.com/30739239/57665075-e9f05580-75d0-11e9-947e-e3e5b420c10e.png)
