### ISSUE TITLE
Swap "Edit" and "Search" in script editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28869]
**Godot version:**
3.1.1

**Issue description:**
This is rather debatable, but most script/text editors have "Edit" directly next to "File". While in Godot we have File|Search|Edit. It never bothered me, because I never used the menu, but recently I had to do some work there and well, for whatever reason this layout feels counter-intuitive.

Normally search falls under edit, but since Godot has them in separate menus, it should be enough if they just swapped places. So it would be File|Edit|Search (if you look at it, it's actually consistent with other editors, because Search is "next" after Edit).

Any thoughts?

**Comment by MaaaxiKing** [comment]
I think search should be under edit.
