### ISSUE TITLE
Borderless windows get border back

### ISSUE THREAD

**Issue by Project-Magenta** [godotengine/godot#28865]
**Godot version:**
Godot version 3.1.1 stable

**OS/device including version:**
Linux, Desktop Computer
Ubuntu 19.04
NVIDIA GTX 1050

**Issue description:**
I switch to fullscreen, switch back, and my borderless window has borders again.
Calling `OS.set_borderless_window(true)` doesn't help.
Similar to #7186 but for Godot 3.

**Steps to reproduce:**
Create a borderless project,
Call `OS.window_fullscreen = true` somewhere,
call `OS.window_fullscreen = false` after,
and see a bordered window. Attempt to
switch it back, and fail.

**Minimal reproduction project:**

[Reproduce.zip](https://github.com/godotengine/godot/files/3175424/Reproduce.zip)

**Comment by duckinator** [comment]
Confirmed: this results in a bordered window:

```
func _ready():
	OS.window_fullscreen = false
	OS.set_borderless_window(true)
```

I suspect &mdash; but have not confirmed &mdash; that Godot is assuming the borderless property of the window is persistent if you toggle fullscreen, and window managers are breaking this assumption.

----

**Workaround** until a proper fix is in place: You can make your own `set_borderless_window` function like this:

```
func set_borderless_window(val):
	OS.set_borderless_window(!val)
	OS.set_borderless_window(val)
```

If you add that function, then remove the `OS.` from your original `OS.set_borderless_window(true)` call, it works as expected.

**Comment by Project-Magenta** [comment]
Thanks for the confirmation! I've been waiting for a reply about half a month already. I suspected that setting it backwards would reset it, but I never tried it yet. I will study the window manager.

**Comment by Project-Magenta** [comment]
Thanks!
