### ISSUE TITLE
Inconsistency in "return" vs "returns" in documentation

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28867]
**Godot version:**
3.1.1

**Issue description:**
In class reference, when doc mentions return value, it sometimes says "return" and sometimes "returns". Like, half of the times for each. IMO it should always be the latter.

**Comment by akien-mga** [comment]
It's mentioned in the docs but could likely be made more explicit: http://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html#mention-what-methods-return-if-it-s-useful

CC @godotengine/documentation

**Comment by bojidar-bg** [comment]
I think it might be nice to put the `Returns XXX` inside the return tag.
To give an example from `Sprite.xml`.
Current:
```xml
<method name="get_rect" qualifiers="const">
	<return type="Rect2">
	</return>
	<description>
		Returns a Rect2 representing the Sprite's boundary relative to its local coordinates.
	</description>
</method>
```
New:
```xml
<method name="get_rect" qualifiers="const">
	<return type="Rect2">
		A Rect2 representing the Sprite's boundary relative to its local coordinates.
	</return>
	<description>
	</description>
</method>
```
To render as:
> void get_rect()
> *Returns:* A Rect2 representing the Sprite's boundary relative to its local coordinates.

**Comment by akien-mga** [comment]
@bojidar-bg I think that would be confusing for documentation contributors that you have both `<return>` and `<description>` tags that you can fill, especially since for most methods the only description you need is what it gives you (`<return>`).
