### ISSUE TITLE
Broken shadows when using SpotLight with Orthogonal Camera

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28878]
**Godot version:**
3.2.dev.custom_build. ecceabe

**OS/device including version:**
Ubuntu 19.04 Nvidia 970

![Zrzut ekranu z 2019-05-14 10-55-35](https://user-images.githubusercontent.com/41945903/57685191-a7ae2f00-7637-11e9-9bf3-0b7af37205d8.png)

**Minimal reproduction project:**
[FF.zip](https://github.com/godotengine/godot/files/3176735/FF.zip)

**Comment by YeldhamDev** [comment]
Maybe related to #21462.

**Comment by akien-mga** [comment]
Let's track both types of light in #21462, looks like the same issue indeed.
