### ISSUE TITLE
It's possible to unclick a button from ButtonGroup using shortcut

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28872]
**Godot version:**
3.1.1

**Issue description:**
Normally in ButtonGroup you have one button that is pressed and when you click that button, it stays pressed. There's no way to unpress it. HOWEVER, when you add a shortcut to the button, it can be unpressed using the shortcut.

Somewhat related to #9789
Either it should be possible to legitimately unpress a button or not possible in any way (and excluding shortcut, you can just create a group without any button set to pressed).

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/3175504/ReproductionProject.zip)
Press up.

**Comment by dominiks** [comment]
I cannot reproduce this on 3.2.1. When the button is pressed and you hit the key for the shortcut it shows the same behaviour as clicking it: it is rendered in its normal state while the shortcut (or mouse button) is pressed down and goes back to the released state when released.

It is not possible to unpress the button in the ButtonGroup with a shortcut. I think this can be closed.

**Comment by KoBeWi** [comment]
Indeed, there were some changes in buttons that probably fixed this.
