### ISSUE TITLE
NinePatchRect editor is useless

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28871]
**Godot version:**
3.1.1

**Issue description:**
This is what you see when you set right/bottom margin to some value:
![image](https://user-images.githubusercontent.com/2223172/57665038-ae6a8100-75fa-11e9-9072-dee7c7259d11.png)
You can move the lines with mouse, cool, but why right margin doesn't move from right border? Right now it start from the left and you move it outside the texture. That's not helpful at all.

**Comment by randibit** [comment]
I've noticed NinePatchRect has issues in 3.1.1 when going through a Godot course.  
I've seen this issue and also ran into a scale issue when attempting to go through a tutorial.
I'd report my issue here, but often get trolled.

**Comment by KoBeWi** [comment]
I just found out that there's a similar editor for StyleBoxTexture and it does lines correctly, but doesn't sync correctly with the inspector.
![image](https://user-images.githubusercontent.com/2223172/64995303-244d6480-d8db-11e9-8ab4-0b180ce2a04a.png)
So yeah, this is a bug.
