### ISSUE TITLE
Export for ios,  "App Store Team ID" cann't use real ID.

### ISSUE THREAD

**Issue by weihu120** [godotengine/godot#28876]
**Godot version:3.0.6~3.1.1**

**OS/device including version:Macos 10.12 xcode 9**

**Issue description:**

when export for ios, "App Store Team ID"use my real ID(email address),xcode cann't open the exported project, but i input "12345678"or"abcdefg" in "App Store Team ID",xcode open the project success.
**Steps to reproduce:**

**Minimal reproduction project:**

Sorry for my bad English!

**Comment by DrMoriarty** [comment]
@weihu120 The AppStore Team ID is not your email (apple id). You could find it in Membership tab in your developer account.
![Снимок экрана 2019-05-14 в 14 31 44](https://user-images.githubusercontent.com/1177068/57694774-4a28db00-7655-11e9-9034-218624639bef.png)

**Comment by weihu120** [comment]
@DrMoriarty Thank you very much.

**Comment by LinuxUserGD** [comment]
@weihu
You can find the personal id in the keyrings section of your mac if you don't have a paid developer account.

**Comment by LinuxUserGD** [comment]
https://stackoverflow.com/questions/18727894/how-can-i-find-my-apple-developer-team-id-and-team-agent-apple-id#18727947

**Comment by weihu120** [comment]
@LinuxUserGD Great! Thank you so much!
