### ISSUE TITLE
Viewport Lag [Issue]

### ISSUE THREAD

**Issue by Tiberion000** [godotengine/godot#28877]
Release:
Godot 3.1.1 stable

System:
5.0.13-arch1-1-ARCH x86_64 GNU/Linux
[Simple project
#1 SMP PREEMPT
HP 8440p, Intel i5 2.4GHz, Integrated Graphics (Up to GLES 2.0)

Issue:
Viewport gradual (or after clicking) lag 

Procedure:
Open Godot via terminal (I used QTerminal)
Open a project and switch to 2D viewport
Click on the player on the viewport.
Lag should be constantly present until you restart Godot Editor

Note:
A small annoyance, and it's not that bad. But I think this should be addressed. If this is just the case of outdated hardware, or Arch being Arch, then I guess I'll have to live with this until I get a better unit.

[Simple project.zip](https://github.com/godotengine/godot/files/3176413/Simple.project.zip)

**Comment by Zireael07** [comment]
Hmm, if your integrated graphics are Intel HD, it might be a driver bug that was reported several times already?

**Comment by Calinou** [comment]
@Zireael07 To my knowledge, that particular bug affects only Windows (https://github.com/godotengine/godot/issues/23069).

@Tiberion000 What do you mean by lag exactly? Is it low framerate or something different such as stuttering?

**Comment by Tiberion000** [comment]
@Calinou It is low framerate. I've tried replicating the issue again and it seems that after I open the Scripts tab, the framerate drops. This could be a hardware problem and not the problem of the editor itself.

**Comment by yusdacra** [comment]
I have the same problem too. I am using both Unity for Linux, and Godot. Unity runs fine with my small test scene, no viewport lag and FPS is around 200. While in Godot, in a newly created empty scene, viewport lags when i rotate / move viewport camera. It drops to around 30 FPS.

Void Linux, Kernel 5.1.4_1 SMP PREEMPT x86_64
Intel Pentium N3540 2.66GHZ, Intel Bay Trail iGPU (happens both with GLES 2.0 and GLES 3.0)

**Comment by Calinou** [comment]
@yusdacra Does it run smoother if you click the spinner in the top-right corner and set the update mode to **Update Always**?

**Comment by Calinou** [comment]
Closing, as there's not much that can be done on our end. In 3D, you can enable **Half Resolution** in the **Perspective** menu at the top-left corner of the 3D viewport to speed up rendering while in the editor.
