### ISSUE TITLE
Exported project looks different than in editor

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28879]
**Godot version:**
3.2.dev.custom_build. ecceabe
Linux and Windows Export, Release and Debug

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I try to export game, I got different image than in the editor
![Zrzut ekranu z 2019-05-14 12-26-22](https://user-images.githubusercontent.com/41945903/57691374-4fc9f500-7644-11e9-85d0-5c3dfc327548.png)
![Zrzut ekranu z 2019-05-14 12-27-10](https://user-images.githubusercontent.com/41945903/57691382-5193b880-7644-11e9-9aef-91d26441142a.png)

**Minimal reproduction project:**
[AA.zip](https://github.com/godotengine/godot/files/3177137/AA.zip)

**Comment by akien-mga** [comment]
Can't reproduce with dc7a40f0 on Mageia 7 with those two GPUs:
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
OpenGL ES 3.0 Renderer: AMD VEGAM (DRM 3.30.0, 5.1.1-desktop-1.mga7, LLVM 8.0.0)

**Comment by qarmin** [comment]
I cleared cache and config, but still I have same problem
My PC specs
Ubuntu 19.04 Linux 5.0.0-13
GTX 970  Proprietary drivers 430.09

**Comment by qarmin** [comment]
I can't reproduce this anymore with master.
I think there may have been something wrong with my drivers.
