### ISSUE TITLE
Curve saved in scene can have '#INF' as decimal causing the scene to break

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#28883]
**Godot version:**
Godot 3.1.1-stable

**Issue description:**
Somehow a Curve saved in a scene can have decimal values of '#INF' causing the scene to be incompatible and fail loading.

```
[sub_resource type="Curve" id=3]
max_value = 1024.0
_data = [ Vector2( 0, 0 ), 0.0, 0.0, 0, 0, Vector2( 0.619738, 0 ), 0.0, 1.#INF, 1, 1, Vector2( 0.619738, 1022.26 ), 1.#INF, 0.0, 1, 0 ]
```

**Steps to reproduce:**
Not 100% reproduceable, but adding a curve with its max value set to the maximum possible value is what caused this.

**Comment by Keetz** [comment]
Update on reproduceable project:

The problem occurs when playing around with the angles on a curve (The little blue points you can rotate on any point on the curve).

![Selection_003](https://user-images.githubusercontent.com/6707330/59037209-1cf4d480-8871-11e9-9c5f-8f67ae595f8b.png)

I can't 100% figure out a combination that can make it happen, but it happened a few times for me now trying to make a reproduceable project.

The problem is that it will hit a number way too large and replace it by #INF instead, so an easy way to make it happen is to open the scene file in a text editor, and edit one of the values to a very large number, for example: 2000000000000000000000000000000000000000000000000000000000 (you get the point :smile:)

1. Create some node that can have a Curve, I used CPUParticles2D
2. Add a curve, set some random values and save the scene.
3. Close Godot and open the scene file in your favorite Text Editor.
4. Change the curve to something like:
 ```[sub_resource type="Curve" id=3]
max_value = 1024.0
_data = [ Vector2( 0, 0 ), 0.0, 0.0, 0, 0, Vector2( 0.619738, 0 ), 0.0, 1.0, 1, 1, Vector2( 0.619738, 1022.26 ), 2000000000000000000000000000000000000000000000000000000000, 0.0, 1, 0 ]
```
5. Open Godot and the scene again, everything is ok because Godot just opened it without really looking at anything in the scene file.
6. Do some random change in the scene so you can trigger a scene save. For example just hiding/unhiding a node, doesn't matter as long as  you can save the scene.
7. Now if you open the scene file  you will see that the long number we added has changed to 1.#INF and you can no longer open that scene after closing it.

**Comment by creikey** [comment]
Maybe on loading godot can just replace `#INF` with say `999999999999` for all values to let it load the scene correctly?

**Comment by akien-mga** [comment]
It seems to be better handled in the current master branch. With the above steps to reproduce, I get:
```
ERROR: to_int: Cannot represent 2000000000000000000000000000000000000000000000000000000000 as integer, provided value is too big.
   At: core/ustring.cpp:2170.
```

And then in the scene file:
```
[sub_resource type="Curve" id=3]
_data = [ Vector2( 0, 0 ), 0.0, 0.0, 0, 0, Vector2( 0.619738, 0 ), 0.0, 1.0, 1, 1, Vector2( 0.619738, 1022.26 ), 9.22337e+18, 0.0, 1, 0 ]
```
Modifying the scene and saving doesn't seem to alter that.

So I'll consider it "fixed", though there might still be ways to trigger this kind of edge case. If you can still find ways to reproduce it, please comment and we'll reopen it.

**Comment by samdze** [comment]
The scene breaks for me in v3.3.3

![immagine](https://user-images.githubusercontent.com/19392104/134368902-d6cdf942-9e6e-46f0-ac18-11aa85b46063.png)
