### ISSUE TITLE
Make Godot gITF import/export compatible to Microsoft's SceneLoader

### ISSUE THREAD

**Issue by GeorgeS2019** [godotengine/godot#28881]
This is related to the [discussion ](https://github.com/godotengine/godot/issues/28830)BUT focusing on concrete steps how Godot could contribute to Microsoft 3D desktop experience 

I see the potential how Godot could make Windows 3D desktop development more friendly and appeal to open source community.

I would like to appeal to developers (especially those who are C#)  here who have more experience with Godot gITF to **test, evaluate and feedback** to the Microsoft team working on [SceneLoader  ](https://github.com/windows-toolkit/SceneLoader/blob/master/TestViewer/MainPage.xaml.cs)

> [SceneLoader](https://github.com/windows-toolkit/SceneLoader) is a library for generating [Windows.UI.Composition.Scenes ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.scenes)scene graphs from 3D file formats such as glTF. This project aims to simplify the design-to-code workflow for rendering 3D assets in your Windows applications.

>SceneLoader currently produces a SceneNode, allowing you to programmatically construct your own Visual tree. [A proposed companion Microsoft.UI.Xaml control](https://github.com/microsoft/microsoft-ui-xaml/issues/686) is expected to enable 3D assets to be loaded from markup without requiring explicit management of the Visual tree.

Please help shape the [Microsoft.UI.Xaml 3D Control](https://github.com/microsoft/microsoft-ui-xaml/issues/686#issuecomment-492011461) the way you see BEST serve the open source community!

**Comment by slapin** [comment]
But what is use case with Godot? I don't see any.

**Comment by GeorgeS2019** [comment]
Imagine this ... as 3D content becoming more common with 1 billion users of  Windows desktop/laptop UWP apps. There is need to hire someone who is able to deliver highly engaging 3D content as control into these desktop apps.

**Comment by slapin** [comment]
Still I fail to see how Godot is related to this.

**Comment by GeorgeS2019** [comment]
Not everyone has the imagination to see a great opportunity :-)

**Comment by slapin** [comment]
Maybe if you elaborate and explain thing properly, I'd be enlightened, but
from what you said that was kind of idea
I wake up with and totally forget abut next minute.

**Comment by GeorgeS2019** [comment]
@slapin I closes this issue as the blender to godot glTF export and subsequent godot glTF import is in my view "the state of art".  I believe this perhaps surpasses what can be supported by the SceneLoader ([Microsoft WinUI 3D control](https://github.com/godotengine/godot/issues/20271#issuecomment-580256419)).
