### ISSUE TITLE
Adding the control + C shortkey in FileSystem

### ISSUE THREAD

**Issue by Anthys** [godotengine/godot#28887]
It seems kind of inconsistent: In the "Scene" tab, there is a shortkey to copy quickly a node path, but this shortkey doesn't exist in the FileSystem tab. Is there a good reason for it not being available in the current build?
![aaaa](https://user-images.githubusercontent.com/47481790/57717999-a9e6ac80-767c-11e9-9291-14b7e803c57d.PNG)
![aazz](https://user-images.githubusercontent.com/47481790/57718047-c1259a00-767c-11e9-9c10-c430d04207d9.PNG)

**Comment by Calinou** [comment]
As you can see, none of the other context menu options in FileSystem have shortcuts or icons assigned to them. I'm not sure how difficult it would be to add those.

**Comment by KoBeWi** [comment]
Sooo, there ARE shortcuts for Filesystem Doc, but they are defined in a way that doesn't show them in the context menu.
https://github.com/godotengine/godot/blob/0b6b49a897b35bec53765e1288c32d57afa1a293/editor/filesystem_dock.cpp#L2450-L2453

Also, the "Copy Path" is bugged - if you try to use it while the Script Editor is focused, it will trigger in Script Editor instead. You need to be in 2D or 3D editor to make it work.

**Comment by KoBeWi** [comment]
The shortcuts are now properly available:
![image](https://user-images.githubusercontent.com/2223172/146544307-143c725b-409e-4079-8d23-eb967f5fa6f1.png)
And in 4.0 you can use them without any problem, so closing.
