### ISSUE TITLE
y-sorting not enough on tilemaps

### ISSUE THREAD

**Issue by paulmyers-0** [godotengine/godot#28893]
Heya, I've been developing a tactical RPG with the godot engine but working with the TileMap object, while great for the design step, is subpar for rendering the objects in the correct order. When I design the map, it is made of a series of TileMaps for each height value. But, to render the objects correctly, the higher the y value of the cell in a TileMap, I need that cell's sprite to render in front of a cell with a lower y value in any height's TileMap. Unless I'm mistaken, Y-sorting only accounts for cells within the same tilemap?

Being able to set the z_index for each cell of a map would be a solution which could work. I began programming a solution which would read through each height's TileMaps and generate sprite nodes and place them in the correct position and correct z_index, but now I'm running into a problem with CANVAS_ITEM_Z_MAX being reached? And this is only a 3D grid 30 heights * 20 y rows with each row at 10 possible z values, so 6000 z_index max...

Does anyone have a good solution for this? Is there something I'm missing? Are there new TileMap features in the works?

**Comment by Ranoller** [comment]
Well... i´m a bit tired today for fully understand english and your problem, but it sounds me to the problem that i have from long time ago. I push a commit: https://github.com/godotengine/godot/pull/28896 . With origin point -> BOTTOM LEFT if topdown or CENTER if isometric and this commit it should work, maybe, or maybe not, you have to test. I refer in the commit your issue to track.

**Comment by akien-mga** [comment]
Is this fixed in the master branch now that #28896 is merged?

**Comment by groud** [comment]
Closing as all of this mess is fixed on master today.
