### ISSUE TITLE
Godot game on iPad Pro 12.9 3rd can't get window safe area

### ISSUE THREAD

**Issue by kruglinski** [godotengine/godot#28899]
**Godot version:**

3.1.1

**OS/device including version:**

XCode 10.2, iOS 12.2, iPad Pro 12.9 3rd gen simulator

**Issue description:**

Godot game can't fill full screen of iPad Pro 12.9 3rd Simulator device, leave black edges in all 4 direction.

the return value of get_viewport_rect() and OS.get_window_safe_area() always the same

in iPhone X simulator, they are different and works fine!

**Steps to reproduce:**

**Minimal reproduction project:**

[demo.zip](https://github.com/godotengine/godot/files/3181416/demo.zip)

iPhone X
![iPhoneX](https://user-images.githubusercontent.com/2869425/57771803-5b9de000-7746-11e9-9785-7b42cc7d03dd.png)

iPad Pro 3rd demo project
![iPadPro12 9 3rd_godot](https://user-images.githubusercontent.com/2869425/57771811-622c5780-7746-11e9-9d12-2e18fee370c7.png)

iPad Pro 3rd message app
![iPadPro12 9 3rd_message](https://user-images.githubusercontent.com/2869425/57771833-73756400-7746-11e9-8368-69f21ac67430.png)

demo project compare with message in background preview
![iPadPro12 9 3rd_background](https://user-images.githubusercontent.com/2869425/57771837-7a03db80-7746-11e9-9f87-482c9148fb3b.png)

**Comment by akien-mga** [comment]
CC @godotengine/ios

**Comment by kruglinski** [comment]
If the demo project work fine with iPhone X simulator, I think there must be something wrong with the iOS template project not the engine.

Probably cause by LaunchImage, LaunchStoryboard or something, have no idea how to fix it

**Comment by kruglinski** [comment]
Sorry! my bad, I'm mistakenly link against older SDK(11.4) not the latest(12.2), that cause the app running in "compatibility mode" which iOS keep app running in the safe area and telling it that it already running in native mode, in "compatibility mode" get_viewport_rect() and OS.get_window_safe_area() always the same

Sorry for my stupid, and thank you all!

![iPadPro 3rd](https://user-images.githubusercontent.com/2869425/57795573-e5ff3780-7778-11e9-9689-d08bed9366bd.png)

**Comment by kruglinski** [comment]
Problem solved I'm close this one
