### ISSUE TITLE
Nested custom items

### ISSUE THREAD

**Issue by ismslv** [godotengine/godot#28890]
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
When I create custom nodes or resources, they are immediately parented to the root (Node or Resource respectively) in all interfaces (node selection dialog, resource creation panel and so on), even if it is not the case.   

```class Character : Node {}``` and ```class ThirdPersonChar : Character {}```
are both just Nodes, because second parameter in
```add_custom_type("ThirdPersonChar", "Node", script, icon)```
defines only the main type of item, and what logically seems correct like
```add_custom_type("ThirdPersonChar", "Character", script, icon)```
will not work.

It is even more evident with resources. Consider the following:
```csharp
//CustomMap.cs
public CustomMap : Resource { ... }

//CustomMapIndoors.cs
public CustomMapIndoors  : CustomMap { ... }

//MapLoaderIndoors.cs
[Export]
public CustomMapIndoors housePlan;
```
In this case in the inspector we will see a dropdown of all possible resource types, instead of just maps - which is not the case with any other resources.

Is there a way to define a correct inheritance or a "group"? Also, in the mentioned interfaces there are tooltips at the bottom with description of the item, which also seems not included in "add_custom_type".

**Comment by ismslv** [comment]
An addition: found out that gd script nodes (but not cs!) that have ```class_name```   
appear automatically in the list of nodes and stack as they must,   
though only with a strange syntax like this: ```extends 'res://NodeParent.gd'```    

Now we have a mess: cs nodes do not appear automatically even after build,   
but gd can appear doubled: automatically and imported as plugin ```add_custom_type```,   
but only automatic ones stack in tree structure, and cs do not stack at all.   

As so, I get that cs support is far from complete,  but gdscript - which seems   
to be rather solid - also has a strange behaviour in this situation.

**Comment by aaronfranke** [comment]
@ismslv Please test if this issue still exists with Godot 3.2.3 and/or the master branch.

If this issue does still exist for you, then you will need to include a minimal reproduction project.

**Comment by Calinou** [comment]
Closing due to lack of response (see the above comment).
