### ISSUE TITLE
Attempt to connect nonexistent signal 'open' error when opening project

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28903]
**Godot version:**
3.2.dev.custom_build. dc7a40f

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I opened editor I had this error:
```
ERROR: connect: In Object of type 'FileSystemDock': Attempt to connect nonexistent signal 'open' to method 'EditorNode.open_request'
   At: core/object.cpp:1467.
```

**Comment by YeldhamDev** [comment]
Oops, that would be my fault. I thought that this signal was unused, but this proves me wrong.
