### ISSUE TITLE
Remember selected VisualScript function when changing scripts with alt+right

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28910]
**Godot version:**
3.1.1

**Issue description:**
When selecting a previously edited VisualScript with alt+right the last edited function doesn't reopen. This isn't the case when clicking it manually.

**Steps to reproduce:**
Create a VisualScript with a function and select it, open another script/documentation and switch back to the VisualScript with alt+right.

**Comment by swarnimarun** [comment]
Oh just saw why this is a issue(while sifting through the code) will submit a PR. ASAP.
