### ISSUE TITLE
3D import collisions (-colonly) with Instanced Sub-Scenes

### ISSUE THREAD

**Issue by zEh-** [godotengine/godot#28918]
I was happy to find two ways to import multiple meshes from a single 3d model (.glb in my case) into multiple files. Because I want to include collision in my models I chose "Instanced Sub-Scenes" instead of *.mesh-files.

I expected to be able to use the collision conventions specified in the "Importing 3D scenes" documentation. For example an empty node of type Cube named "MeshName-colonly" to add a basic BoxShape collision.

**Instead of adding a StaticBody to the actual mesh, <del>the import creates its own scene file for a "-colonly" object (which results in just a translated spatial).</del> it produces a translated Spatial**

Just tested a bit further:
"-col" works fine but creates a ConcavePolygonShape as expected ("-convcol" would be nice to have)

**Comment by zEh-** [comment]
I thought I had the "-colonly"-object as a child. I didn't. After fixing that it doesn't create a separate scene file anymore. But instead of a StaticBody I just get a Spatial as a child on import.

I don't see the reason behind the "enhancement" label. It's clearly described [here](https://docs.godotengine.org/en/3.1/getting_started/workflow/assets/importing_scenes.html#create-collisions-col-colonly-convcolonly).

**Comment by Calinou** [comment]
The 3D import system was revamped in the `master` branch. It no longer relies on import hints in object names (although the option remains for custom importers).

> "-col" works fine but creates a ConcavePolygonShape as expected ("-convcol" would be nice to have)

`-convcol` and `-convcolonly` are available since Godot 3.2.
