### ISSUE TITLE
Get the list of global classes in scripting language

### ISSUE THREAD

**Issue by RameshRavone** [godotengine/godot#28929]
**Godot version:**
master branch

**OS/device including version:**
Ubuntu 19.04

Just wanted to know how to get the list of global classes registered by `class_name`, My guess is you can only get the list from `ScriptServer` which is not exposed for scripting, Is there a way to expose methods related to global classes,

**Comment by RameshRavone** [comment]
My proposal is to add `get_global_class_list`, `global_class_exists` to the `_ClassDB` and expose that to the scripting, and isn't ClassDB suppose to have all the class info, why global_classes are inside `ScriptServer` in the first place,

**Comment by RameshRavone** [comment]
Ok, It seems we can get global_class_list from ProjectSettings, but doing so looks kinda ugly.

**Comment by RameshRavone** [comment]
Maybe I should just create a PR and hope it gets accepted

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5444, as feature proposals are now tracked on the Godot proposals repository.
