### ISSUE TITLE
anisotropy doesn't render right on custom meshes

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#28927]
**Godot version:** 3.1.1
 

**OS/device including version:** Ubuntu 18.10

**Issue description:** 
Made a sphere in blender, imported and added a spatial material and set anisotropy to 1. Doesn't render the way it does for a default godot sphere (shown on right)
![Screenshot from 2019-05-15 22-23-55](https://user-images.githubusercontent.com/7292421/57822141-091ded00-7761-11e9-9201-5a4d0b51e1c6.png)

I've attached the mesh used:

[sphere.zip](https://github.com/godotengine/godot/files/3185157/sphere.zip)

**Comment by CptPotato** [comment]
Does your mesh have UV maps? Anisotropy probably requires them.

**Comment by clayjohn** [comment]
You need tangents in order to use anisotropy. Without them the sphere fails to render correctly, I will update the docs to explain that.
