### ISSUE TITLE
ERROR: get_path: Condition ' !is_inside_tree() ' is true - when closing the editor

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2893]
When closing an open project to return to the project manager, the following messages are shown:
```
ERROR: get_path: Condition ' !is_inside_tree() ' is true. returned: NodePath()
   At: scene/main/node.cpp:1153.
ERROR: get_path: Condition ' !is_inside_tree() ' is true. returned: NodePath()
   At: scene/main/node.cpp:1153.
ERROR: get_path: Condition ' !is_inside_tree() ' is true. returned: NodePath()
   At: scene/main/node.cpp:1153.
ERROR: get_path: Condition ' !is_inside_tree() ' is true. returned: NodePath()
   At: scene/main/node.cpp:1153.
```
There are repeats several times, but it varies based on the project.

**Comment by swenner** [comment]
I can confirm this bug with current master.

**Comment by bojidar-bg** [comment]
I can confirm this even if not returning to Project Manager, but just closing the editor. (on 19a8f9b74d9ef7a4e2e9f5b1d1333995e2384943 )

**Comment by akien-mga** [comment]
This error comes from here: https://github.com/godotengine/godot/blob/8adc4ef65b76ee0e8a5fdf6c773d47716fa8511f/scene/main/node.cpp#L1153
So whatever calls Node::get_path() after the editor has been closed needs to be made aware that it's not a good idea :)
