### ISSUE TITLE
VisualScript gets modified when it shouldn't

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28937]
**Godot version:**
3.1.1

**Issue description:**
There are some instances where VisualScripts are modified (A star appears next to the file name and you have to save it again), even though they shouldn't.
* Selecting functions
* Canceling the base type selection
* More stuff I will add soon

**Steps to reproduce:**
Create a VisualScript with two functions, save it and select a function.
Create a VisualScript and cancel the change the base type dialog

**Comment by swarnimarun** [comment]
Also, Undo doesn't revert back the Visual Script to un-edited state.

**Comment by KoBeWi** [comment]
The two cases mentioned seem fixed in 4.0, so closing.
