### ISSUE TITLE
Proposal: "Time Correction" option in PitchShift audio effect

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#28932]
PitchShift audio effect should have an option to not time-correct the audio. Right now it automatically compensates the speed of playback, trying to preserve the speed/tempo of the sound/music. Sometimes it could be required to play the pitch shifted audio without correction of speed, so for example Pitch Scale value of 0.5 would result in not only music playing octave lower from original pitch, but also at half the speed of the original (2x slower).
The option could be called "Time Correction" or "Speed Preservation".

**Comment by kawa-yoiko** [comment]
Hi ^ ^

You are looking for audio resampling. As you have already seen, this changes the length of the audio and thus cannot be implemented as a real-time effect. Instead, use an `AudioStreamPlayer` and set `pitch_scale` to the desired value.

**Comment by freemanfromgodotengine** [comment]
Yes, I am talking about audio resampling. More or less like it was working before audio engine rewrite. You were able to use audio engine to play 44100 Hz files as 22050 Hz, hearing it pitched octave lower and played twice slower.

**Comment by kawa-yoiko** [comment]
`AudioStreamPlayer`, `AudioStreamPlayer2D` and `AudioStreamPlayer3D` all have the "pitch scale" parameter which achieves resampling. Is there any use case not covered by this?

(I don't know about the situation before the rewrite, perhaps it allowed for non-real-time effects but the current system does not seem to...)

**Comment by Calinou** [comment]
@freemanfromgodotengine Bump :slightly_smiling_face: 

See the comment above: https://github.com/godotengine/godot/issues/28932#issuecomment-514036741

**Comment by freemanfromgodotengine** [comment]
Thanks @Calinou for the bump.
@kawa-yoiko is right. "Pitch scale" does exactly what I described.
I am closing this proposal.
