### ISSUE TITLE
Godot server fails to load gdnative libraries in C ++

### ISSUE THREAD

**Issue by cotmat** [godotengine/godot#28938]
**Godot version:**
3.1.1

**OS/device including version:**
x11.64 Debian 9

**Issue description:**
When I try to run the project with godot server I get the following error:

![Istantanea_2019-05-16_20-18-35](https://user-images.githubusercontent.com/49816824/57877304-c79c4900-7817-11e9-9d3a-4908bbd3b491.png)
Fails to load the libtest.so (gdnative C++) library.
Using godot with gui instead, the project runs correctly and the libtest.so library is loaded.

**Steps to reproduce:**
Add any library (gdnative c ++) to the project and run one of these console commands
1. ./server --path project.godot
2. ./server --main-pack server.pck

**Comment by bruvzg** [comment]
For server build you should use additional "Server" platform line in the `.gdnlib` file:
```
X11.x86_64="res://bin/linux.x86_64/libtest.so" <-- for X11
Server.x86_64="res://bin/linux.x86_64/libtest.so" <-- for Server
```

**Comment by cotmat** [comment]
> For server build you should use additional "Server" platform line in the `.gdnlib` file:
> 
> ```
> X11.x86_64="res://bin/linux.x86_64/libtest.so" <-- for X11
> Server.x86_64="res://bin/linux.x86_64/libtest.so" <-- for Server
> ```

ok, it worked and I thank you and I hope it can serve others.

Running it on Centos he pointed out the error:
ERROR: open_dynamic_library: Method / Function Failed, returning: ERR_CANT_OPEN

1. I tried to add the text below but it didn't work:
env.Append (LINKFLAGS = [
     '-Wl, -rpath \' $$ ORIGIN \ '/ lib'
])

2. I tried to add LD_LIBRARY_PATH but it didn't work:
export LD_LIBRARY_PATH = $ (pwd) /: $ (pwd) / lib /

3. I tried to compile the library in the same path as the executable but it didn't work.

4. Finally I tried to replace:
         env.Append (CCFLAGS = ['-fPIC', '-g', '- O3', '-std = c ++ 17'])
     IN
        env.Append (CCFLAGS = ['-fPIC', '-g', '- O3', '-std = c ++ 11'])
and the latter solved the problem.

In practice with the transition to C ++ 11, it allowed the executable to find the right path to the library.
Are there performance differences using C ++ 11 instead of C ++ 17?

Excuse me for not perfect English.

**Comment by Calinou** [comment]
> Are there performance differences using C ++ 11 instead of C ++ 17?

With the same compiler version and the same code as input, it's unlikely to show any performance differences. However, recent compilers often perform better than older compilers.

Still, if you wish to distribute portable binaries/libraries, these should be built on the oldest distribution you wish to support, which naturally limits the compiler (and C++ language) versions you can use.

**Comment by cotmat** [comment]
Thanks for the info.

**Comment by mintyleaf** [comment]
How about documenting this case and making it accessible through Editor UI?
I spent like 2 hours of my life trying to realize why godot-headless didn't work with my .so lib!

**Comment by Calinou** [comment]
@mintyleaf I think the Server platform should just attempt to load the library defined for X11 or macOS (Server can run on macOS too since 3.2). This way, users don't need to define the library path twice.

**Comment by follower** [comment]
FYI here is the PR related to the Server / Headless GDNative library issue: https://github.com/godotengine/godot/pull/38898
