### ISSUE TITLE
Reviewing editor/plugins/script_editor_plugin.cpp#L3307 ff.

### ISSUE THREAD

**Issue by silkentrance** [godotengine/godot#28943]
**Godot version:**
current master

**Issue description:**
https://github.com/godotengine/godot/blob/master/editor/plugins/script_editor_plugin.cpp#L3294

the two ifs need separate returns or an else if at least

**Comment by erammos** [comment]
What's the issue with that? I will add that "else" ,if someone don't want to bother ofc, just to check that part of the code as well :)

**Comment by akien-mga** [comment]
I don't really see the need to change anything here, as it adds to the git history (new entry in `git blame`, etc.) without making a functional change.

But now that there's a PR for it already, I guess we can just as well merge it and get one issue closed :)
