### ISSUE TITLE
Waiting for timer in coroutine skipped on resume() 

### ISSUE THREAD

**Issue by GreenBeakCrow** [godotengine/godot#28942]
**Godot version:**

3.1 stable and 3.2.dev @aa3c5f59f27055245004ef19622e895e7b99a297

**OS/device including version:**

Arch linux

**Issue description:**

When waiting for a timer in a coroutine with `yield(timer, "timeout")` and calling `resume` on the returned state the coroutine immediately resumes without waiting for the timer. I don't know if this is intended behaviour, but it allows an outside function to break the coroutine's functionality.

This does not occur if the caller directly yields to the coroutine via `yield(someFunc(), "completed")`.

**Steps to reproduce:**
Run the following example script:
```
extends Node2D


func _ready() -> void:
    print(str(OS.get_ticks_msec()) + ": Starting coroutine")
    var state = someCoroutine()
    print(str(OS.get_ticks_msec()) + ": Resuming coroutine")
    state.resume()
    print(str(OS.get_ticks_msec()) + ": Done")

    print("------")
    print(str(OS.get_ticks_msec()) + ": Waiting for completed signal of coroutine")
    yield(someCoroutine(), "completed")
    print(str(OS.get_ticks_msec()) + ": Done")


func someCoroutine() -> void:
    print(str(OS.get_ticks_msec()) + ": Waiting for timer")
    yield(get_tree().create_timer(0.5), "timeout")
    print(str(OS.get_ticks_msec()) + ": Resuming")

```
This produces output similar to this:
```

562: Starting coroutine
562: Waiting for timer
562: Resuming coroutine
562: Resuming
562: Done
------
562: Waiting for completed signal of coroutine
562: Waiting for timer
1042: Resuming
1042: Done
```
I would expect a similar delay between `562: Resuming coroutine` and `562: Resuming`.

Maybe this is related:
https://github.com/godotengine/godot/issues/17280

**Minimal reproduction project:**

[WaitForTimerIssue.zip](https://github.com/godotengine/godot/files/3188621/WaitForTimerIssue.zip)

**Comment by vnen** [comment]
This is not a bug. If you call a coroutine you get a state back. It doesn't matter if this state is connected to a signal, you can always call `resume()` to make it keep going. So if you call `resume()` the functions resumes, this should be expected.

If you don't call `resume()` then when the timer finishes it will emit a signal which will resume the function for you.

Bottom line is: if you want it to wait the timer, don't call `resume()`. If you need it to resume immediately, without waiting, call `resume()`.

In Godot 4.0 you won't have access to the state, so this kind of confusion won't happen.
