### ISSUE TITLE
Facing _CTFontManagerRegisterGraphicsFont error when implement google login in iOS

### ISSUE THREAD

**Issue by atologist-pratik** [godotengine/godot#28955]
I'm trying to add google login in game, i add `GoogleLogin` in module folder, create `register_types.cpp`, `config.py` and  `*.h , *.m`in ios folder, also add google SDK framework and bundle in ios folder.

**Godot version:**
Godot version 3.1 and Godot Source version 3.1
Using Xcode with developer account and testing in Device. 
[Source code 3.1](https://github.com/godotengine/godot/releases/tag/3.1-stable)
[Engine 3.1](https://downloads.tuxfamily.org/godotengine/3.1/)

**Module Code:**
You can check my module code [Link](https://github.com/atologist-pratik/GodotGoogleLoginDemo/tree/master)

**Issue description:**
```
Undefined symbols for architecture arm64:
  "_CTFontManagerRegisterGraphicsFont", referenced from:
      ___45+[NSBundle(GID3PAdditions) gid_registerFonts]_block_invoke in GoogleSignIn(NSBundle+GID3PAdditions_6d6613bc1cea93bb9b465ce92c46bfbb.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Steps to reproduce:**
Using Mac OS 10.13.6
1. I generate binary using below command and create `iphone.zip` file from `misc/dist/ios_xcode`
2. Copy `iphone.zip` file to `Library/Application\ Support/Godot/templates/3.1.stable` 
3. Export project from Godot Engine 3.1
4. Open project in xcode, copy google SDK/framweork in project, add `credentials.plist` in project.
5. In Project add SafarServices, LocalAuthentication and SystemConfugration framework in `Target>Buil Phases>Link Binary with Libraries`
6. add `Other Linker Flags`  to `-ObjC`
7. add `URLTypes` my google `REVERSED_CLIENT_ID`
8. When i Hit run i face above linker error.

If i implement google login in native iOS application using GoogleSDK then working fine for ios native apps.

So i think problem is not in iOS SDK, may be im missing something while implementing googleLogin in module folder or any path.

Can someone point me out what i'm doing wrong or how do i resolve above issue?

Thanks

**Comment by vini-guerrero** [comment]
Hey @atologist-pratik , if you use XCode's legacy build system does the issue still persist?

**Comment by atologist-pratik** [comment]
@vini-guerrero i haven't checked this one, but i'll will test it n let you know.

**Comment by atologist-pratik** [comment]
@vini-guerrero  yes,  if i use XCode's legacy build system still same issue i'm facing.

**Comment by akien-mga** [comment]
No answer and this is a fairly old issue, so closing. Please open a new issue with a MRP if you can still reproduce a similar error.
