### ISSUE TITLE
'AudioStreamPlayer's are unaffected by 'time_scale'

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#28953]
**Godot version:**
2809d86

**Issue description:**
I would imagine that `Engine.time_scale` would also affect the speed of which `AudioStreamPlayer`s play their streams, but they're completely unaffected by it.

**Comment by avencherus** [comment]
Would be nice to optionally be able to time scale sound effects and such, but wouldn't want to arbitrarily do this for everything, as I wouldn't the UI SFX or game music to be affected by a slow motion effect.
