### ISSUE TITLE
When using close tabs to the right, the save dialog won't save.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#28963]
**Godot version:**

15cda53d802f5

**OS/device including version:**

Win10 64bit

**Issue description:**

When having multiple edited scenes, and doing a close tabs to the right, the save button will not carry out saving.

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/13004169/57938006-dc3c1800-78cf-11e9-9967-dcdd9b4a4200.gif)

@KoBeWi

**Steps to reproduce:**

1. Edit multiple scenes.
2. Don't save them.
3. Right-click a far left tab and select close all to the right option.
4. Try to save.

**Comment by KoBeWi** [comment]
When I added these options, I never tested saving the scene - I always discarded changes XD
All of them are broken in any combination if you try to save something and it went unnoticed for almost a month. Working on fix right now.

**Comment by avencherus** [comment]
Yeah, I save in a paranoid way, so it was some rare occasion when I was editing like 30 scenes that I had forgot to save something when I did this.  X)

Though generally it doesn't seem as though many people are actively making any large projects in the most recent builds.  My impression at least is quite a few issues here and there that are noticeably impinging on user experience that have gone unnoticed or unreported.

Thanks for taking a look into it so quickly.  I'll check out your PR soon, and fiddle with the conditions.
