### ISSUE TITLE
Scene tree not updating on tab change in some conditions

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#2896]
This is a weird bug I found by accident. The scene tree panel is not updating if you change the tab, but this does not seem to happen every time. I found a reliable way to reproduce this though:

* Create a new project (or open an existing one and close every scene).
* Add a new Node2D to the empty scene (this bug does not happen with a Control, only with Node2D and maybe with its descendants).
* Add a built-in script (just so you don't have to save the scene or type a path).
* Create a new scene.
* Go back to the first scene tab. Then the scene tree panel will remain empty.

The panel remains empty even if you switch back to the 2D view.

**Comment by akien-mga** [comment]
With a quick test I couldn't reproduce the bug with your exact procedure, however I've seen similar behaviours when playing around over the last few days. I'll keep an eye open.

**Comment by StraToN** [comment]
I could reproduce. The first scene containing a Node2D must not be saved before creating the second scene. If it is, the bug doesn't occur.
