### ISSUE TITLE
Spatial.get_global_transform() does not work with autocomplete.

### ISSUE THREAD

**Issue by OIronPigO** [godotengine/godot#28961]
**Godot version:** Godot v3.1.stable.flathub

**OS/device including version:**Kubuntu 18.10

**Issue description:**get_global_transform() does not show up in the autocomplete menu.

**Steps to reproduce:**
- Create a Spatial node.
- Attach a script to it
- Open the script
- Type 'get_global' and press Ctrl+Space
- get_global_transform() does not show up in the autocompletion menu

**Minimal reproduction project:**

**Comment by TheDuriel** [comment]
All virtual setters and getters are excluded from autocomplete. Once you define an override for the function it will show up.

Instead of using the setget functions, use the property directly. `Spatial.global_transform`

**Comment by volzhs** [comment]
![Screenshot_20190518_000936](https://user-images.githubusercontent.com/8281454/57937619-3f926e00-7901-11e9-8b82-10e072f14bb7.png)

I guess this is what you need.

**Comment by akien-mga** [comment]
Indeed, getters and setters are excluded from autocomplete when their property is directly accessible, like `global_transform`. The setting shown by @volzhs can re-enable their autocompletion if you need so.
