### ISSUE TITLE
Sprites larger than 4k resolution do not render when built for Android.

### ISSUE THREAD

**Issue by garrettmason** [godotengine/godot#28960]
**Godot version: 3.1.1 Stable**

**OS/device including version: Windows 10, Android API Level 22 and 23**

**Issue description: Sprites 4k and larger do not render on Android and only display as a black box. These sprites display fine when build for Windows or HTML5**

**Steps to reproduce: Add a sprite to the scene, apply a texture 4k or higher, build for android.**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
The maximum texture size is limited by hardware. Recent desktop GPUs are limited to 16384² textures, whereas mobile devices are often limited to 4096².
