### ISSUE TITLE
suport arcore for android ?

### ISSUE THREAD

**Issue by jaccen** [godotengine/godot#28973]
**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Reneator** [comment]
If you have questions, try to use the forum or the godot subreddit.

**Comment by Chaosus** [comment]
No need to create so bad-formed issue, especially if there is already a PR for this opened https://github.com/godotengine/godot/pull/26221
