### ISSUE TITLE
Dead links for variant and Error types

### ISSUE THREAD

**Issue by est31** [godotengine/godot#2897]
Example:
* [PacketPeer](https://github.com/godotengine/godot/wiki/class_packetpeer) , method `put_var`, param is typed `var`. (can be found in Dictionary class as well).
* [PacketPeerUDP](https://github.com/godotengine/godot/wiki/class_packetpeerudp) , method `wait` , return value is typed `Error`.

Both are shown as clickable in the help browser. Both lead to empty pages. Ideally, they should point to documentation pages of the types.

**Comment by reduz** [comment]
var is an any type value, weird that it wants to use a page

**Comment by akien-mga** [comment]
> var is an any type value, weird that it wants to use a page

Shouldn't it be ```Variant```?

**Comment by reduz** [comment]
hmm yes i guess
