### ISSUE TITLE
Area2D: Expected identifier as member (body)

### ISSUE THREAD

**Issue by jimmyjonezz** [godotengine/godot#28979]
Body Expected identifier as member

**Godot version:**
Godot 3.1.1

**OS/device including version:**
Windows 7, Intel G45, GLES2

**Issue description:**

**Minimal reproduction project:**
![gif1](https://user-images.githubusercontent.com/3973191/57966046-67abbc80-7955-11e9-89ea-509ecca50595.gif)

**Comment by Reneator** [comment]
That error tells you, that you have to put an identifier after the "."
So that it knows, what attribute/method you want to call.

You can test this by putting the . behind another variable somewhere else.

**Comment by jimmyjonezz** [comment]
> That error tells you, that you have to put an identifier after the "."
> So that it knows, what attribute/method you want to call.
> 
> You can test this by putting the . behind another variable somewhere else.

give me sample, please...

**Comment by Reneator** [comment]
> > That error tells you, that you have to put an identifier after the "."
> > So that it knows, what attribute/method you want to call.
> > You can test this by putting the . behind another variable somewhere else.
> 
> give me sample, please...

Please specify what you mean. With the given explanation its not really possible to help you properly. And besides, these kinds of issues are better suited for godot-forums or the godot-subreddit.
