### ISSUE TITLE
Should godot_variant_evaluate deref arguments a and b?

### ISSUE THREAD

**Issue by pchasco** [godotengine/godot#28984]
**Godot version:**

3.1

**OS/device including version:**

**Issue description:**

godot_variant_evaluate always returns incorrect results or sets the error flag when I use it. I noticed that the call to Variant::evaluate in godot_variant_evaluate doesn't deref the a and b arguments. I believe it should dereference these. Am I doing it wrong, or is there an issue in how GDNative calls Variant::evaluate?

https://github.com/godotengine/godot/blob/ee5ba3e0974caba3e3589d2a53405ef7328dc1b1/modules/gdnative/gdnative/variant.cpp#L521

**Steps to reproduce:**
```
  godot_variant a;
  godot_variant b;
  godot_bool r;
  api10->godot_variant_new_int(&a, 0);
  api10->godot_variant_new_int(&b, 0);
  godot_variant ret;
  api10->godot_variant_new_bool(&ret, r);
  api11->godot_variant_evaluate(0 /* add */, &a, &b, &ret, &r);
```

**Minimal reproduction project:**

**Comment by karroffel** [comment]
Indeed, it seems like the arguments should be dereferenced in the call.

I will make a PR this evening! (unless somebody beats me to it, the only change would be to change `a` to `*a` and `b` to `*b`)
