### ISSUE TITLE
PoolByteArray resize  cannot truncate the array to the new size

### ISSUE THREAD

**Issue by zhangshiqian1214** [godotengine/godot#28989]
I use PoolByteArray in gdnative,  and I found PoolByteArray resize cannot truncate the array to the new size.

```c++
PoolByteArray buffer;
buffer.resize(512);

buffer.resize(24);
int sz = buffer.size();
printf("sz=%d\n", sz); //and the result is 24
```

**Comment by clayjohn** [comment]
Isn't 24 the expected output because you resized the buffer to 24?

I'm having trouble understanding your problem.

**Comment by zhangshiqian1214** [comment]
sorry, I expected the result is 24, and the result is 512

**Comment by zhangshiqian1214** [comment]
Oh, I see a error:
ERROR: resize: Condition ' alloc->lock > 0 ' is true. returned: ERR_LOCKED
   At: ./core/pool_vector.h:541

![image](https://user-images.githubusercontent.com/9353330/57976916-6befdc80-7a1e-11e9-9ce0-f5b04a33e9d6.png)


![image](https://user-images.githubusercontent.com/9353330/57976901-27fcd780-7a1e-11e9-8414-5eafb885c6f4.png)

**Comment by zhangshiqian1214** [comment]
I think i was wrong, PoolByteArray is right, because i don't free the w. 
![image](https://user-images.githubusercontent.com/9353330/57980650-8e0a4e80-7a60-11e9-8bf9-893cdcae285a.png)
