### ISSUE TITLE
Custom editor themes don't work anymore

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28981]
**Godot version:**
34ad33d9e

**Issue description:**
Custom themes sometimes don't work or the setting is reset.

**Steps to reproduce:**
* create a new editor theme
* set it in the project settings
* reopen the project

**Comment by mbrlabs** [comment]
Has this been fixed?
I can't reproduce it with the latest master branch on Manjaro Linux.

**Comment by Tazshelby2016** [comment]
What is the current status of this issue?

**Comment by akien-mga** [comment]
No answer, assuming that it's working as expected now. Please comment if you can still reproduce this issue, and attach a project that triggers it.

**Comment by Jummit** [comment]
> No answer, assuming that it's working as expected now.

Sorry, I didn't get around to testing it. I still can't get custom themes to work.

> ... attach a project that triggers it.

That's kinda the problem; since it is a problem with an editor setting, it can't be shared as a project file. But it doesn't take that long to do what I put as the steps to reproduce in the OP.

**Comment by Jummit** [comment]
I just found out that it works if you don't create the theme through `Create from current editor theme`, but a clean theme works.

**Comment by Jummit** [comment]
Ok, this is the most confusing issues I've ever encountered. It seems to be a mix of the settings just being reset and the theme not working / only working in the project selection. I can't get it to work reliably, but since it works most of the time I think the problem must be investigated further. Closing for now.
