### ISSUE TITLE
Improve Particles Damping/Drag Behavior

### ISSUE THREAD

**Issue by rajin-s** [godotengine/godot#28994]
**Godot version:** 3.1.1

Currently, it is very difficult to create _good_ one-shot 'burst' particle effects such as explosions, dust poofs, etc. that rely on some sort of drag (simulated or approximated) to look compelling. A negative `Linear Acceleration` and `Damp` do essentially the same thing: decreasing a particle's speed each update independent of its current velocity. This results in a hard stop as particles go from positive to zero speed, rather than a smooth dropoff.
![godot_particles_issue1](https://user-images.githubusercontent.com/21044526/57976279-3c9f8800-79aa-11e9-8dc2-ac866822ae35.gif)

Unity and other tools allow more artistic control through direct speed manipulation via a parameter curve (speed over lifetime), non-physical damping (exponential decrease over lifetime), or simulated air resistance (based on particle size and speed). It would be great if Godot could incorporate at least one of these options.

Experimenting with different tweaks (to `CPUParticles`), the simplest solution seems to be replacing the damping calculation with something along the lines of `speed = lerp(speed, damp_target, clamp(delta * damp_amount, 0, 1))` where `damp_target` is a configurable 'speed limit' and `damp_amount` is a non-physical value controlling how quickly particles should adhere to that limit. This results in nice, smooth asymptotic motion
![godot_particles_issue2](https://user-images.githubusercontent.com/21044526/57976283-49bc7700-79aa-11e9-8221-3637176acbe6.gif)

**Comment by avencherus** [comment]
I'm also a bit envious of other particle systems.  I share your difficulty in creating desired effects, and most the time I have to write my own particles, unless it is a very simple effect.

**Comment by jesperkondrup** [comment]
Exactly it's very hard if not impossible to get the desired effect.

**Comment by Calinou** [comment]
Can this be achieved using the Damping Curve property (which is available in both Particles and CPUParticles)?

PS: I noticed the Damping property in the Inspector is limited to 100 in 2D, this should probably be changed. The Damping Curve property allows to circumvent this, as there's no limit for the curve's maximum value.

**Comment by QbieShay** [comment]
Accelerations are good for more realistic and chaotic particles, but for when artistic control needs more fine tuning, we should have a velocity over life property. Related to this proposal https://github.com/godotengine/godot-proposals/issues/5574

Pushing to 4.1 as it needs to implement a new feature (velocity over life) which is not possible to add in RC phase.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5574.
