### ISSUE TITLE
C# WorldToMap/world_to_map doesn't work

### ISSUE THREAD

**Issue by 0IJon0** [godotengine/godot#28992]
Godot_v3.1.1-stable_mono_win64

When I'm using WorldToMap istead of world_to_map, because I'm using C# the game always crashes with the Error:  drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054

Code:
`
Vector2 lastMousePos;
public override void _Ready()
    {
		lastMousePos = topMap.WorldToMap(GetGlobalMousePosition());
    }
`

**Comment by neikeq** [comment]
Why was this closed? Is this still a valid issue?

**Comment by 0IJon0** [comment]
I solved the issue with a workaround, but I can still not use it in the Ready() function...

**Comment by akien-mga** [comment]
Please don't close the issue if it's still a valid bug report. This issue tracker is for bug reports against the engine that need to be fixed for everyone.

**Comment by giulianob** [comment]
@0IJon0 can you post a project to reproduce it? I'm using tilemap and calling both WorldToMap and MapToWorld without any issues.

**Comment by akien-mga** [comment]
No answer, and it's not clear what the issue was about originally, so closing again.
