### ISSUE TITLE
Animation Reverse is not executed properly - Notifier not fired

### ISSUE THREAD

**Issue by Archina** [godotengine/godot#28991]
**Godot version:** 3.1.1

**OS/device including version:** Windows 10

**Issue description:**
New AnimatedSprite is created.
New Sprite FrameSet is created.
A 'default' Animation is created. Loop is set to off.

When the animation is then played in reverse then the notifier  'animation_finished' is only triggered once.

**Steps to reproduce:**
```python
extends AnimatedSprite

var count = 0

func callback():
	count = count + 1
	print("I am printed only once: %s" % count)

func _ready():
	pass
	
func _input(event):
	if event is InputEventKey:
		connect("animation_finished",self,"callback")
		play('default', true)
		print("KeyEvent is printed")
```

**Comment by KoBeWi** [comment]
Seems fixed in 3.2
