### ISSUE TITLE
IME support for non-latin Unicode characters (CJK, Arabic, etc.)

### ISSUE THREAD

**Issue by greggman** [godotengine/godot#29]
Trying to type Chinese, Japanese or Korean in OSX fails in the editor fails. 

In other words, make a Button, click on the text field, try to type ロード. It doesn't work. Copying from somewhere else and trying to paste it in doesn't work either.

**Comment by Calinou** [comment]
What about Noto Sans? http://www.google.com/get/noto/

We could even use it as default Godot font, it's great.

**Comment by michaeldesu** [comment]
Thanks Calinou - it's a nice font. As an experiment, I just tried one Japanese font at random (NotoSansJP-Medium), and found it to be a nice editor font.
![image](https://cloud.githubusercontent.com/assets/11791450/7064033/198c8638-deef-11e4-9412-cc432f2f1ebe.png)

**Comment by trollworkout** [comment]
i'd go for GNU unifont  as it has about 60k glyphs is monospaced and is bitmap pixel font

**Comment by reduz** [comment]
Definitely want to add proper internationalization for 1.2, as the new site
will support it too

**Comment by trollworkout** [comment]
At least add Korean and Japanese support  as those 2 countries are the biggest consumers of games. If you guys could somehow even add Korean and Japanese input to engine (Godot interface and Godot games) would open up the engine and games to a huge market. I mean just saying. The interface can easily be internationalized and translated with the help of volunteers. Even a last step the ability to support unicode variables in GDScript like Python does would be nice too.

**Comment by reduz** [comment]
To avoid mistakes, Godot already supports displaying text in CJK, it's just
the editor that can't be internationalized

**Comment by akien-mga** [comment]
@reduz mentioned wanting to fix this in 1.2 (now 2.0), but I'm not sure it's still in the planned roadmap for 2.0 as we're nearing to beta stage, so setting to "Later" for now.

> To avoid mistakes, Godot already supports displaying text in CJK, it's just
the editor that can't be internationalized

Is it only about internationalizing the editor? From what I gathered it seems to be more about missing IME support, which prevents inputing CJK characters (regardless of whether the editor itself is in English or internationlized).

**Comment by nunodonato** [comment]
isn't this solved by the recent commits of new fonts and internationalization?

the issue mentions OSX specifically so I can't test...

**Comment by reduz** [comment]
I'm not sure if IME is working properly for those languages

**Comment by nunodonato** [comment]
ah you're right, I just tested now in Linux and the problem persists with those characters in the editor

**Comment by yixiaoqingyuz** [comment]
**+1**
>Trying to type Chinese, Japanese or Korean in OSX fails in the editor fails.

**Comment by trollworkout** [comment]
@yixiaoqingyuz  try to copy chinese and paste in labels/strings. it wont be displayed in the script editor but works in the editor and in the game i u have the right font

**Comment by yixiaoqingyuz** [comment]
@trollworkout yes, the Japanese can be pasted in labels,but can't be typed

**Comment by trollworkout** [comment]
@yixiaoqingyuz  I know. I thought you didn't know. The editor does not support CJK input that's why you can't type. It only supports CJK characters. The script editor, however, only supports latin.

**Comment by akien-mga** [comment]
Actually the script editor supports CJK too now.

**Comment by trollworkout** [comment]
@akien-mga  really? let's try this 
Yep correct. It does work 👍

**Comment by raymoo** [comment]
Any update on this?
