### ISSUE TITLE
Strange light colours in TPS Demo with GLES 3

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29008]
**Godot version:**
3.2.dev.custom_build. e20fb10

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
TPS Demo looks really strange in GLES 3
![Zrzut ekranu z 2019-05-19 18-38-29](https://user-images.githubusercontent.com/41945903/57985292-07f10680-7a66-11e9-998e-b264fb34ae95.png)

With GLES 2 it looks good but a little too dark 
![Zrzut ekranu z 2019-05-19 18-39-55](https://user-images.githubusercontent.com/41945903/57985293-0a536080-7a66-11e9-9c18-f75ccc499ec9.png)

**Minimal reproduction project:**
TPS Demo

**Comment by Calinou** [comment]
I can confirm this in the Sponza demo on commit https://github.com/godotengine/godot/commit/580b0c651df86675145a696b1e961b224bf3ad8c.

![sponza_broken_rendering](https://user-images.githubusercontent.com/180032/57987329-35e34480-7a80-11e9-9c6b-15d8b99729fc.jpg)

**Comment by clayjohn** [comment]
Could be the result of https://github.com/godotengine/godot/pull/27898 as well. Reduz was worried about the interaction with light probes... 

I didn't notice any ill effects in my test scene, but these demos are significantly more complex...
