### ISSUE TITLE
add_font_override("font", null) does nothing

### ISSUE THREAD

**Issue by RicardRC** [godotengine/godot#29004]
**Godot version:**
master branch (3.1+?)

**OS/device including version:**
Windows 10, compiled with MSVS2019

**Issue description:**
add_font_override("font", null) does nothing, and should clear the previously set override

**Steps to reproduce:**
use the function mentioned with a valid override, then try to clear it using the same function with an empty font (as the documentation says)

**Comment by KoBeWi** [comment]
Null font is explicitly treated as error. The method does some stuff with the font, but I guess a special handler for null wouldn't hurt.

Although it's the same for `add_icon_override`, `add_shader_override` and `add_style_override`. These could be changed too.

**Comment by swarnimarun** [comment]
Yeah makes sense. Made a PR. We can probably discuss more there.
