### ISSUE TITLE
Having a resource that holds a reference to itself (in the inspector) breaks the editor

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#29007]
**Godot version:**
Lastest master version #d111d59

**OS/device including version:**
MacOSX

**Issue description:**
Creating a `*.tres` that exposes a resource in the inspector and dragging a self reference onto it, break the editor when you open the sub resource. Well it kinda of makes sense, it is a cyclic reference, but sometimes you need it to be like that. (From a data point of view) imagine a graph node (represented by a resource) that has a connection to itself.

I think I should give a cyclic reference warning when trying to expand the sub-resource and don't allow it.

**Comment by LikeLakers2** [comment]
While I'm not opposed to this being made a warning instead of breaking the editor, I do have to wonder: What *are* the use cases for cyclic references?

**Comment by xDGameStudios** [comment]
like I said...

#vertex.gd
```
extends Resource
class_name Vertex

export(String) var name;
export(Array, Resource) var connections;
```

create two vertices `one.tres` and `two.tres`

Now lets go to the inspector:

on vertex one add to entries to the connections array drag `two.tres` to the first entry (makes sense vertex one is connected to vertex two)... now draw `one.tres` to the second entry (also makes sense vertex). Trying to expand `one.tres` break editor. This should not happen imagine you are trying to create something similar to a state machine it's normal for a state to allow transitions to itself.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue, and make sure that there is an up-to-date reproduction project.
