### ISSUE TITLE
Cannot override animations in inherited scene

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#2901]
In inherited scenes, when modifying animations in an AnimationPlayer node inherited from the base scene, those modifications are lost when saving and reopening the inherited scene.

Would be amazing if you could add tracks to animations from base scenes and add keys to tracks from base scenes.
But at least it should be possible to override animations.

**Comment by reduz** [comment]
Adding animations should work, but not modifying them. The reason is that
animations are resources, which are unique and shared between instances.
You can somehow achieve this by editing the animation in the property
editor and using the "make unique" property, though this will create a
local copy

**Comment by eska014** [comment]
"Make Sub-Resources Unique" on the inherited AnimationPlayer is perfect for this, thanks reduz!
AnimationPlayer is still new to me, but I'm loving scene inheritance.
