### ISSUE TITLE
GDNative dll locked when editor is running

### ISSUE THREAD

**Issue by valentinAlkan** [godotengine/godot#29017]
**Godot version:**
Godot_v3.1.1-stable_win64

**OS/device including version:**
Win 10

**Issue description:**
Godot locks nativescript libraries when editor is running. This makes it extremely difficult to write and test native script code since you need to close the editor every time you recompile.

**Steps to reproduce:**
Import test project
Open godot editor.
Attempt to delete nativescript library (bin/win64/libnativescript.dll)
Access denied
![image](https://user-images.githubusercontent.com/19651331/57989354-8e5a1800-7a67-11e9-8425-2ecb3434716a.png)

[accessdenied.zip](https://github.com/godotengine/godot/files/3195722/accessdenied.zip)

**Comment by valentinAlkan** [comment]
closing my own issue, something was up with my OS. Restarted PC and issue is gone.

**Comment by niavok** [comment]
The setting reloadable=true in the .gdnlib file fix this problem for me :

https://github.com/godotengine/godot/issues/38371#issuecomment-622299647
