### ISSUE TITLE
tool: Scrollcontainer inside scrollcontainer ignores layout

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#29012]
**Godot version:**
3.1.1 official

**OS/device including version:**
Windows 10

**Issue description:**
This is specific for my plugin-layout in main-dock:
You have a scene with a scroll-container. If you add another scroll_container somewhere along the children of that scroll_container, the second scroll_container ignores the layout and drops behind all the other elements and gets pushed all the way up inside the contailner its currently in.

Expectation: Being able to put a scroll-container inside another scroll-container to be able to have multiple levels of scrolling inside each other.

**Steps to reproduce:**
Add a scroll-container with content as a child of another scroll_container

**Minimal reproduction project:**
[reproduction_project_scroll_container.zip](https://github.com/godotengine/godot/files/3195380/reproduction_project_scroll_container.zip)

The error is already visible in the 2D dock.

**Comment by KoBeWi** [comment]
Seems like a problem with ScrollContainer, as it doesn't increase the inner size until you really push it, which results in child nodes being very crammed. Containers might not function correctly at all unless you give them a minimal size.

**Comment by KoBeWi** [comment]
After looking at it again, this is not really a bug. ScrollContainer has no minimal size, so you need to specify it if you want to use it inside another ScrollContainer.
