### ISSUE TITLE
Game with `.` (dot) at the end of the name creates undeletable dir in `\Godot\app_userdata\` on Windows

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#29025]
**Godot version:**
3.1.1 Mono Stable

**OS/device including version:**
Windows

**Issue description:**
If your game has a name with a `.` in it at the end the auto generated folder for it in `C:\Users\*username*\AppData\Roaming\Godot\app_userdata\` can't be deleted without renaming it in CMD as admin first.

**Steps to reproduce:**
Create project with a dot in the name at the end like `name.`, run project on Windows, try to delete the generated app_userdata folder.

**Suggestion:**
I suggest not allowing a dot in the project name at the end or at least warning the user when attempting this. I found this bug when I tried to delete the folder of a Game Jam game I tested.

**Comment by aaronfranke** [comment]
> I suggest not allowing a dot in the project name at the end

It seems to already not allow this:

![Screenshot from 2019-05-20 06-53-47](https://user-images.githubusercontent.com/1646875/58016637-24278e80-7acc-11e9-864e-7536792925d6.png)

**Comment by ScepticDope** [comment]
@aaronfranke You can rename it just fine in the project manager, that might be how people go around that check?

**Comment by aaronfranke** [comment]
Yes, that's the problem then. The title should probably be "Rename project dialog does not check if the new project name is valid".

**Comment by ScepticDope** [comment]
You can also still manually change it. One could argue that it would then be outside the scope of the engine but regardless a un-removable dir will be created in `AppData\Roaming\Godot\` which makes Godot look bad if some dev goes around both checks.

Maybe a simple check removing the last char if it is a dot, where that dir gets created on engine level would fix the bug once and for all?

**Comment by ScepticDope** [comment]
*On a side note renaming everything manually happens a lot with Mono projects because as of now that is the only way to rename a project without breaking it. See: https://github.com/godotengine/godot/issues/27030

**Comment by K0bin** [comment]
You can also create invalid folders (trailing space in my case) using Godots file dialog.
![grafik](https://user-images.githubusercontent.com/1131720/73853331-f9838e80-4830-11ea-9f94-0b879cc29d39.png)

**Comment by KoBeWi** [comment]
Seems fixed in 3.2.4 beta4
Even if you rename project with dot at the end, the data directory won't contain it.
