### ISSUE TITLE
Find in Files/Replace does not accept empty input

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#29026]
**Godot version:**
3.1.1 official

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
You cannot use Find/Replace to mass-erase text. The "Replace All" button is simply grayed out if no replacement text is provided. Likewise if only space characters are given.

**Comment by aaronfranke** [comment]
Unable to reproduce the issue on 3.1.1 on Linux. Before:

![1](https://user-images.githubusercontent.com/1646875/58020233-92bd1a00-7ad5-11e9-9ee0-ed41efc4a44f.png)

After:

![2](https://user-images.githubusercontent.com/1646875/58020240-981a6480-7ad5-11e9-9ccb-bf5b998311b3.png)

**Comment by Vultraz** [comment]
Uhhh... what I'm seeing looks different.
![image](https://user-images.githubusercontent.com/3558659/58021346-61386300-7b56-11e9-86b2-ce3716a945bf.png)

**Comment by aaronfranke** [comment]
I simply pressed `Ctrl+R` to open the Find/Replace bar in the editor.

It seems that you're using the "Find in files" menu, but I don't see a way to replace in there...

**Comment by Calinou** [comment]
@aaronfranke Use the **Replace** button in the Find in Files dialog :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/180032/58021942-9d46d600-7b0c-11e9-9fde-74108c9fc157.png)

**Comment by Vultraz** [comment]
I didn't realize `Ctrl+R` was a thing! 😬 But can confirm the problem doesn't happen there.
