### ISSUE TITLE
File class always returns ERR_FILE_CANT_OPEN error instead of actual error

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#29039]
**Godot version:**
3.1.1 (Mono)

**OS/device including version:**
Windows 10

**Issue description:**
When attempt to open a file using the `File.open(...)` method, if an error occurs (such as a missing file) the return error will always be `ERR_FILE_CANT_OPEN`. It is not possible to determine the more specific error. The expected errors `ERR_FILE_NOT_FOUND` for a missing file, or `ERR_FILE_ALREADY_IN_USE` for an exclusively locked file are never returned.

**Steps to reproduce:**
Open a "valid" but missing file path using `File.open`. Check the return error value. It will always be 12 (the error code for the generic `ERR_FILE_CANT_OPEN` error).

**Minimal reproduction project:**
[Testing-FileOpen.zip](https://github.com/godotengine/godot/files/3198996/Testing-FileOpen.zip)

**Comment by mhilbrunner** [comment]
Yup. I'm currently working on a fix for this :)

**Comment by KoBeWi** [comment]
In 3.2 beta1, `ERR_FILE_NOT_FOUND` is returned correctly, but `ERR_FILE_ALREADY_IN_USE` is still not.

**Comment by timothyqiu** [comment]
`ERR_FILE_ALREADY_IN_USE` does not seem to be about "can't open an exclusively locked file". It's more like "there is already something in use", some examples:

https://github.com/godotengine/godot/blob/6e8eb0d98dea1f77a8ec199fe04ba5a44e88faee/modules/mono/mono_gd/gd_mono_assembly.cpp#L306-L308

https://github.com/godotengine/godot/blob/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac/drivers/mpc/audio_stream_mpc.cpp#L216-L218

**Comment by akien-mga** [comment]
Closing as "good enough" for now, but better error reporting for core APIs can be looked at for 4.0.
