### ISSUE TITLE
Light2D shadows slipping away from objects in GLES3

### ISSUE THREAD

**Issue by Samuel-Clarke123** [godotengine/godot#29030]
**Godot version:**
3.2 or, commit
8b0ea337771a2ec04f8c731601c6a0518187b328

**OS/device including version:**
Ubuntu 18.04, ZOTAC GTX 1050 Mini, Kernel 4.16.18

**Issue description:**
Light2D's shadows slip away from what they're casting on (light occluder 2d's, to be specific); especially with far Light2D->object distances.
GLES2 shadows don't do this. This only happens in GLES3. I've also tested this on Windows 10, and had the same issue, but I can't double check that.

**Steps to reproduce:**
Make a Light2D, move it far away, then make a light occluder 2d.

**Minimal reproduction project:**
[LightsTest.zip](https://github.com/godotengine/godot/files/3198066/LightsTest.zip)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/89c37da (Fedora 30, Intel HD 620).

## GLES3 (bad)

![image](https://user-images.githubusercontent.com/180032/58031522-dee17c00-7b20-11e9-950d-513e0423db7a.png)

## GLES2 (good)

![image](https://user-images.githubusercontent.com/180032/58031550-ed2f9800-7b20-11e9-8ba8-45642ac79a43.png)
