### ISSUE TITLE
File handles are not closed if an exception occurs (Mono)

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#29043]
**Godot version:**
3.1.1 (Mono)

**OS/device including version:**
Windows 10

**Issue description:**
Files opened with the `File` class are not closed if an exception occurs and the editor remains open. If you open a file in an exclusive mode (e.g. `WriteRead`), and an exception occurs later on in your Godot program, the program will exit, but the file will remain locked. It will continue to be locked until the editor is restarted. I think this is Mono only due to it requiring an exception to be thrown. Behaviour may be different on other OS's too.

The issue is exacerbated by #29039, as the failure message when open the file on the next run is generic.

**Steps to reproduce:**
1. Open a file using the `File` in exclusive mode (i.e. `File.ModeFlags.WriteRead`)
2. Throw an unhandled exception
3. Try to open the file externally - it will be locked.

**Minimal reproduction project:**
[Testing-FileExceptionLocking.zip](https://github.com/godotengine/godot/files/3199181/Testing-FileExceptionLocking.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by andy-noisyduck** [comment]
@KoBeWi This no longer happens for me in 3.2.3. Closing.
