### ISSUE TITLE
Profiler sometimes properly count time but sometimes not

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29049]
**Godot version:**
3.2.dev.custom_build. af731f8

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I check profiler, I got sometimes not properly time(Look at the Script Functions)
![Zrzut ekranu z 2019-05-20 22-53-30](https://user-images.githubusercontent.com/41945903/58051686-284abf00-7b53-11e9-93ef-d143afb8dfb3.png)
or this
![Zrzut ekranu z 2019-05-20 22-52-56](https://user-images.githubusercontent.com/41945903/58051727-42849d00-7b53-11e9-909d-6125b1a4aaee.png)

this happens not all the time, here are correct time
![Zrzut ekranu z 2019-05-20 22-52-48](https://user-images.githubusercontent.com/41945903/58051783-65af4c80-7b53-11e9-9468-241051fbbc81.png)

**Comment by mbrlabs** [comment]
Same here:

![ProfilerBug](https://user-images.githubusercontent.com/8750135/84570016-c75bdd80-ad8a-11ea-92e0-5ea96adff73a.PNG)

`BaseTile._ready` takes `9.62ms` while the total time for executing script functions only takes `5.19ms`. 
I'm not sure if this is a bug or me just not understanding how i should interpret the data, but i'm pretty sure that no single function sould take longer than the time shown for `Script Functions`.

**Comment by Calinou** [comment]
Related to #23715.
