### ISSUE TITLE
tool and dictionary saving in itself with ambiguous parameters in method crashes editor

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#29048]
**Godot version:**
3.1.1 official

**OS/device including version:**
windows 10

**Issue description:**
I know the basic premise is not optimal, but i think the editor shouldnt behave the way it did:
![image](https://user-images.githubusercontent.com/24807557/58051052-765ec300-7b51-11e9-8cc3-403f24f20d9d.png)

I accidentally tried to save a method parameter in a dictonary, that had the same var-name as the dictionary. When i now access this method, the whole editor just dies (closes itself, without any error-message or anything)

I fixed it by changing the parameter-name:
![image](https://user-images.githubusercontent.com/24807557/58051090-8c6c8380-7b51-11e9-84cd-7f7e44123853.png)

So here i dont know exactly, if its because of:
- the parameter having the same name and therefore the saving in the dictionary gets weird and loops or something
- Saving a dictionary in itself
- if its because of tool and/or the above

But im not sure why it crashes here, because when i try to build a reproduction project, its working just fine. Maybe it is in connection with the "tool" in the scripts. Im running this as part of a editor-plugin

The interesting thing here is also: If i start up the plugin (that uses that script) directly after the crash, it cant find any method in the script ("cannot find x method"). Then i have to change a line (add or remove free line) in the code (in the script that called the method that crashed) and save. Only then the script can be executed again. Restarting the editor doesnt change anything. I have to change the script.

If needed, i can try to provide a simple reproduction-Project, that behaves exactly as i described.

My expectation here would be:
- dont let me name method-parameters the same as vars (fields) in the scripts
- crash with an understandable error-message "There was some looping occuring" or something like that.
- Not having to "fake"-change a script to somehow get it to build the scripts again or something.

**Steps to reproduce:**

**Minimal reproduction project:**
Will add if needed, if this is not a duplicate.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Reneator** [comment]
This was a long time ago and i cant reproduce the premise. So im closing the ticket.

**Comment by Reneator** [comment]
Ah, i could reproduce it now:
[Tool and dictionary saving reproduction.zip](https://github.com/godotengine/godot/files/5035733/Tool.and.dictionary.saving.reproduction.zip)


Tested it in 3.2.3 rc3:
But now only when i start the scene, only the scene/game is crashing, but the editor keeps working, stays alive and no weird compilation-errors (like described in the original post) pertain.

Very nice! 👍

**Comment by akien-mga** [comment]
This seems fixed in the `master` branch:

- When running the scene, it depends the infinite recursion and errors out:

```
E 0:00:00:0653   _ready: Max recursion reached
  <C++ Source>   core/variant/variant.cpp:1674 @ stringify()
  <Stack Trace>  Control.gd:8 @ update_list()
                 Control.gd:13 @ _ready()
```

- When adding a breakpoint, it recurses for 400 steps (printing 400 errors) before bailing out:

```
E 0:00:00:0872   _ready: Potential inifite recursion detected. Bailing.
  <C++ Error>    Condition "p_depth > Variant::MAX_RECURSION_DEPTH" is true. Returning: ERR_OUT_OF_MEMORY
  <C++ Source>   core/io/marshalls.cpp:1033 @ encode_variant()
  <Stack Trace>  Control.gd:8 @ update_list()
                 Control.gd:13 @ _ready()
```
