### ISSUE TITLE
Godot in self-contained mode will generate thumbnails of it's own thumbnails.

### ISSUE THREAD

**Issue by API-Beast** [godotengine/godot#29058]
**Godot version:**
3.2.dev / ee5ba3e097

**OS/device including version:**
Windows

**Issue description:**
Godot will try to generate thumbnails of it's own thumbnails when it is in self-contained mode. The reason for this is that the cache folder in which the thumbnails are stored are inside the project path, and it will generate thumbnails for anything within the cache.

**Steps to reproduce:**
- Copy the Godot executable into a project folder.
- Create a empty file called `_sc_`
- Launch the Godot executable as editor. (-e command line)
- Click on the editor_data/cache entry in the FileSystem tab.

**Comment by akien-mga** [comment]
That's not really a bug, Godot's self-contained mode is not meant to be used *within* the project folder. Everything which is in a project folder is considered part of the project and will thus be imported.

It's up to you to have a project structure that matches this design decision, either by having your self-contained Godot outside the project folder, or by putting a `.gdignore` file in the folder where you put Godot (which would have to be a child folder of the project root, if you put `.gdignore` in your project root you'll prevent import of any resource).

**Comment by API-Beast** [comment]
Yes, using a .gdignore file seems like a easy enough solution.
