### ISSUE TITLE
Theme Editor doesn't open properly leading to several bugs

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#29056]
**Godot version:**
master 5cc1c7d

**OS/device including version:**
Arch, Manjaro, Windows 10 (all 64bit)

**Issue description:**

![image](https://user-images.githubusercontent.com/19930870/58074133-12281780-7bc2-11e9-84f7-5ecbb65fe3e8.png)

The handle that should be here to drag and make the Bottom Editor bigger doesn't appear on opening Theme creating using the Inspector. It shows up if we change to some other tab (like Output) and then back.

**EDIT:** This is one of the symptoms of the problem. Rest are down below.

**Comment by YeldhamDev** [comment]
This happens because it's not opening correctly when opening automatically, if you can see it clearly if you have any other tab opened:
![Screenshot_20190521_051619](https://user-images.githubusercontent.com/30739239/58079542-c749d800-7ba0-11e9-87f9-f59054cd7a5b.png)

**Comment by swarnimarun** [comment]
Yeah figured that out later let me update the issue.
