### ISSUE TITLE
Theme Editor Improvement Suggestions

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#29063]
As mentioned by a lot of people in various places(IRC, Discord). The Theme Editor needs some serious bit of work to be a proper tool for creating Themes and editing them.

I will list some of my ideas here to do the same,
- Fix the usability bugs like #29059, #29056, #29038, #29034
- Preview and Editing options in the Add Dialog too, currently the process of adding new Theme Options is convoluted, add a new Item, go to the settings section, adjust its settings, preview. This could be simplified if we do a quick preview and editing tool inside of the Add Dialog itself.
- More templates for the Editor to help quickly generate various types of GUIs. Such as creating something that uses Texture StyleBoxes, which is ridiculously painful to do at the moment.
- Make editing sub-resources like Stylebox much easier. 

* This is just some of my ideas feel free to push forward more suggestions.

-> Also made some PRs to fix a few of the issue will probably use some suggesttions to fix more issues and do some feature requests when I have time.

**Comment by Vultraz** [comment]
See also #29035

**Comment by williamd1k0** [comment]
See also #20123
This is not related to Theme Editor itself but is also related to Theme feature.

**Comment by swarnimarun** [comment]
@williamd1k0 Aah that's pretty annoying will look into it.

**Comment by pycbouh** [comment]
Closing this as feature proposals and enhancements are now tracked in the proposals repository. https://github.com/godotengine/godot-proposals/issues/1438 can be used for further discussions.
