### ISSUE TITLE
Setting GridMap meshes by name

### ISSUE THREAD

**Issue by MandL27** [godotengine/godot#29068]
GridMaps are great. They make 3D tile-based level design a breeze. But as #13920 highlights, they have some room for improvement. Another such improvement, that I only thought up as I attempted to do it, is **assigning cell meshes by their name rather than ID**.

As someone who's dealing with hundreds of meshes in GridMaps, with procedural names determined by their orientation and connecting directions, it'd be far, far easier to have code to determine the appropriate mesh name, then pass that into a `SetCellItem()` call to assign the mesh. With the current implementation, that'd also require a conversion table from name to ID (and back, if I need to check what nearby cells look like first). That conversion table could just written into the GridMap itself, possibly as a `Dictionary<int, string>` (assuming C#), letting game devs just use mesh names instead of having to memorize IDs.

**Comment by Zylann** [comment]
IDs are just the way they are ultimately stored into the node, I guess there are ways to add wrappers which take by name and translate it to IDs.

**Comment by MandL27** [comment]
That's...pretty much exactly what I wanted to do. Thanks for showing me that!
