### ISSUE TITLE
Editor crash if Resource is Tool

### ISSUE THREAD

**Issue by ismslv** [godotengine/godot#29064]
**Godot version:**
3.1 Mono

**OS/device including version:**
Windows 10

**Issue description:**
Resource script that is marked as [Tool].   
If it is opened in inspector as a standalone resource file (.tres), everything runs as expected.   
If it is inside of another node (in export field), as a sub-resource, editor crashes immediately when trying to unfold this resource.

**Example project:**
[IssueTools.zip](https://github.com/godotengine/godot/files/3203469/IssueTools.zip)

**Comment by bojidar-bg** [comment]
A backtrace or an example project which is easy to reproduce with would be welcome.

**Comment by ismslv** [comment]
Uploaded example project.

- Map and MapCS resource types - respectively in GDScript and CS
- Inspector plugin and a Get_Map_Size method in both scripts to demonstrate the usage of Tool
- Two autonomous resource files of these types
- Scene with two nodes, each have export field of type Resource.
- First has Map attached, second has MapCS.
- Autonomous files work fine.
- Export field with GDScript resource works fine.
- Export field with CS script crashes editor.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.

Please comment if you can still reproduce it, and this issue can be reopened. Or open a new issue with a MRP if this would be better suited.
