### ISSUE TITLE
ERROR: All memory pool allocations are in use, can't COW.

### ISSUE THREAD

**Issue by zhangshiqian1214** [godotengine/godot#29069]
**Godot version: Godot 3.1.1.stable.official  windows7
### I use GDNative to bind a library [sproto](https://github.com/cloudwu/sproto) and I found when I call function sproto.decode, even the sproto.decode is a empty function, the result is:
[main.gd](https://github.com/zhangshiqian1214/sproto_gdnative/blob/016f12127bf4c67ad38b69db79e67f1b81535e38/demo/Main.gd#L54)
```gdscript
#main.gd
func _on_Button3_pressed():
    var unixdt = OS.get_unix_time()
    for i in range(1000000):
	var bytes = sproto.encode("auth.Player", player)
	var result = sproto.decode("auth.Player", bytes)
```
```
ERROR: All memory pool allocations are in use, can't COW.
```
![image](https://user-images.githubusercontent.com/9353330/58100902-27786280-7c11-11e9-8152-d2491250022c.png)

### But if I commented out the sproto.decode like this, There is no Error:
```gdscript
#main.gd
func _on_Button3_pressed():
    var unixdt = OS.get_unix_time()
    for i in range(1000000):
	var bytes = sproto.encode("auth.Player", player)
	#var result = sproto.decode("auth.Player", bytes)
```

**Comment by akien-mga** [comment]
Did you find a solution to this issue?
