### ISSUE TITLE
Add the ability to build Mono API assemblies in Debug mode

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#29077]
Currently, the Mono API assemblies are always built in Release mode, even with `target=debug` passed to SCons. Not having Debug available can [hide problems](https://github.com/godotengine/godot/pull/29079).

@neikeq said that he wants to improve this in the future, so I'm opening this issue to track progress on that. It will be easier after he makes SCons build the API assemblies.

**Comment by aaronfranke** [comment]
Probably not going to be done for 3.2, I suggest bumping to 4.0.

**Comment by neikeq** [comment]
This is already being done since 270af6fa089ccfb93ace68ada8d476bd902b10fa:

>Make the editor, editor player and debug export templates use Api assemblies built with debug symbols.
