### ISSUE TITLE
AnimationTree Sub-StateMachines reset to start node

### ISSUE THREAD

**Issue by Grandro** [godotengine/godot#29086]
**Godot version:**

3.1

**OS/device including version:**

Windows

**Issue description:**

I don't think my problem is a bug, it's just an issue that I find no way to solve and where I am not able to get help with.
Im trying to animate my player with an AnimationTree:
The state machine of the animation player looks like this:
![image](https://user-images.githubusercontent.com/48568096/58127662-24cc3c00-7c16-11e9-815d-e042f38dcda8.png) and each of the sub-state machines look like this:
![image](https://user-images.githubusercontent.com/48568096/58127725-4fb69000-7c16-11e9-9bbf-13968c35944f.png) 
and this is the script on the player which controls the state machines:

```
extends KinematicBody2D

export (int) var walk_speed = 200
export (int) var run_speed = 300
export (float) var secs_till_idle = 5.0

onready var Idle_Timer = get_node("Idle_Checker")

var state_machines = {}
var curr_speed = 0
var move_state = "stop"
var direction = "down"
var velocity = Vector2()

func _ready():
	state_machines["main"] = get_node("AnimationTree").get("parameters/playback")
	state_machines["idle"] = get_node("AnimationTree").get("parameters/idle/playback")
	state_machines["stop"] = get_node("AnimationTree").get("parameters/stop/playback")
	state_machines["walk"] = get_node("AnimationTree").get("parameters/walk/playback")
	state_machines["run"] = get_node("AnimationTree").get("parameters/run/playback")
	
	Idle_Timer.set_wait_time(secs_till_idle)

func _physics_process(delta):
	_check_movement()
	_check_idle()
	move_and_slide(velocity)

func _check_movement():
	
	velocity = Vector2()
	if Input.is_action_pressed("move_down"):
		set_direction("down")
		velocity.y += 1
	
	if Input.is_action_pressed("move_up"):
		set_direction("up")
		velocity.y -= 1
	
	if Input.is_action_pressed("move_right"):
		set_direction("right")
		velocity.x += 1
		
	if Input.is_action_pressed("move_left"):
		set_direction("left")
		velocity.x -= 1
	
	if velocity.length() > 0:
		if Input.is_action_pressed("move_run"):
			set_move_state("run")
		else:
			set_move_state("walk")
		
	elif move_state != "idle":
		set_move_state("stop")
	
	if state_machines["main"].is_playing():
		state_machines["main"].travel(move_state)
	
	_change_all_sub_state_machines(direction) # Doesn't fix anything
	#if state_machines[move_state].is_playing():
	#	state_machines[move_state].travel(move_state + "_" + direction)
	
	velocity = velocity.normalized() * curr_speed

func _change_all_sub_state_machines(direction):
	if state_machines["idle"].is_playing():
		state_machines["idle"].travel("idle_" + direction)
	
	if state_machines["stop"].is_playing():
		state_machines["stop"].travel("stop_" + direction)
	
	if state_machines["walk"].is_playing():
		state_machines["walk"].travel("walk_" + direction)
	
	if state_machines["run"].is_playing():
		state_machines["run"].travel("run_" + direction)

func _check_idle():
	if move_state == "stop":
		if Idle_Timer.is_stopped():
			Idle_Timer.start()
	else:
		Idle_Timer.stop()

func _on_Idle_Checker_timeout():
	set_move_state("idle")

func set_move_state(new_move_state):
	match new_move_state:
		"stop": set_speed(0)
		"idle": set_speed(0)
		"walk": set_speed(walk_speed)
		"run": set_speed(run_speed)
	
	move_state = new_move_state

func set_speed(new_speed):
	curr_speed = new_speed

func set_direction(new_direction):
	direction = new_direction
```

Now the problem is, that if I change from state "stop" in the main state machine to state "walk" for example and from the sub-state machine "stop_left" to sub-state machine "walk_left", the animation with the start marker shows off for one frame in the sub_state machine im traveling in ("walk_down" in this example).
I tried to fix this by traveling every sub-state machine to "[state]_[direction]", but that doesnt fix anything, the animation still gets reset. I have made a video showing it:
https://www.youtube.com/watch?v=i-eziuBjpOU&feature=youtu.be
(This is me mashing the arrow keys in one direction at a time triggering the start node)

So I am questioning the usage of sub-state machines right now. I don't how you would use them without encountering this problem... Maybe I am missing something.

**Minimal reproduction project:**
[Sub-state machine debug.zip](https://github.com/godotengine/godot/files/3204404/Sub-state.machine.debug.zip)
This is the actual project im working on, but its not very advanced so you should see the issue right away.

**Comment by yanorax** [comment]
Here is your project with an update that makes the state machine dance in the right way.

[Sub-state machine debug revised.zip](https://github.com/godotengine/godot/files/3318011/Sub-state.machine.debug.revised.zip)

I disabled the autoplay on all the states and added else statements to start the states if they are not running.

```
	if state_machines["main"].is_playing():
		state_machines["main"].travel(move_state)
	else:
		state_machines["main"].start(move_state)
	
	_change_all_sub_state_machines(direction) # Doesn't fix anything
	#if state_machines[move_state].is_playing():
	#	state_machines[move_state].travel(move_state + "_" + direction)
	
	velocity = velocity.normalized() * curr_speed

func _change_all_sub_state_machines(direction):
	if state_machines["idle"].is_playing():
		state_machines["idle"].travel("idle_" + direction)
	else:
		state_machines["idle"].start("idle_" + direction)
	
	if state_machines["stop"].is_playing():
		state_machines["stop"].travel("stop_" + direction)
	else:
		state_machines["stop"].start("stop_" + direction)
	
	if state_machines["walk"].is_playing():
		state_machines["walk"].travel("walk_" + direction)
	else:
		state_machines["walk"].start("walk_" + direction)
	
	if state_machines["run"].is_playing():
		state_machines["run"].travel("run_" + direction)
	else:
		state_machines["run"].start("run_" + direction)
```

**Comment by Grandro** [comment]
Hmm okay.. thanks for taking a look. Seems a little inconvinient, but it closes the issue.
