### ISSUE TITLE
Unable to copy and paste visual shader nodes

### ISSUE THREAD

**Issue by fire** [godotengine/godot#29089]
**Godot version:**
e2375f487c2b6857ba7300ed1d460f43cef8cc59

**OS/device including version:**
* osx
* amd

**Issue description:**

Unable to copy and paste visual shader nodes.

**Steps to reproduce:**

Box select a series of visual shader nodes. Hit [copy key sequence] and [paste key sequence]. Nodes are not copied.

**Comment by Chaosus** [comment]
Not a recent regression - also exist on 3.1.1.
