### ISSUE TITLE
Editor crashes a few moments after opening project

### ISSUE THREAD

**Issue by squished-01** [godotengine/godot#29080]
**Godot version:**

3.1.1

**OS/device including version:**

Win 10 64-bit

**Issue description:**

I just upgraded my project from 3.0.6 to 3.1.1.  Now whenever I open the project, the editor crashes after a few minutes.

Using GLES3 video driver
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms
CORE API HASH: -7323055289690356460
EDITOR API HASH: 4311324559216891413
Loading resource: C:\Users/Admin/AppData/Roaming/Godot/editor_settings-3.tres
EditorSettings: Load OK!
EditorSettings: Save OK!
Loaded builtin certs
Editing project: C:/Godot/Quasar4x (C:::Godot::Quasar4x)
EditorSettings: Save OK!

$ OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2

No further output that isn't printed by me.  No output from the crash

I do use https://github.com/khairul169/gdsqlite-native/releases/tag/1.2 but I don't have the time to see whether it's the source of the problem.  I don't see why it would crash the editor when the game isn't running though.

**Steps to reproduce:**

Open my project, run it from editor, close the game, make updates to my script, click another window

The editor crashes with no output as soon as I click a non-godot window

**Minimal reproduction project:**

I have no idea how to minimalize the issue. Sorry.

**Comment by akien-mga** [comment]
There's no crash shown in your log. Before editing your issue, you had logs about cyclic references which are now forbidden in Godot 3.1, as per https://github.com/godotengine/godot/blob/master/CHANGELOG.md#changed:

> - Cyclic references to other scripts with preload() are no longer allowed.
>   * load() should be used in at least one of the scripts instead.

**Comment by squished-01** [comment]
The editor itself closes immediately, as soon as I switch focus to any other window on my OS.

**Comment by squished-01** [comment]
installing https://github.com/TGRCdev/gdsqlite-native/releases/tag/1.4-beta fixes it.
