### ISSUE TITLE
RigidBody center of gravity issue

### ISSUE THREAD

**Issue by martys71** [godotengine/godot#29099]
**Godot version:** 3.1.1

**OS/device including version:** Windows 10 x64

**Issue description:**

In the following scene the collision shape of the corner desk was auto-generated via Mesh->Create Trimesh Collision sibling.
![obraz](https://user-images.githubusercontent.com/46401158/58159256-62fc4680-7c7c-11e9-89af-1c809596b622.png)

As the RigidBody origin is located outside on the side of the Collision shape Im' expecting the desk to behave like a pendelum. It doesn't. It behaves as if its center of gravity was located somwhere inside the mesh:

![obraz](https://user-images.githubusercontent.com/46401158/58159696-5b896d00-7c7d-11e9-9849-9109ac36797f.png)

But... After I add a simple CollisionShape, and disble it (!) I'm getting the proper result:

![obraz](https://user-images.githubusercontent.com/46401158/58159845-9b505480-7c7d-11e9-842d-70f210682d55.png)

The result:
![obraz](https://user-images.githubusercontent.com/46401158/58159860-a30ff900-7c7d-11e9-9f0f-47c98e8d1e5a.png)

[EDIT] Other things that work:

- duplicate the collision shape instead of adding a new one.
- use convex sibling instead of trimesh

**Steps to reproduce:**
See above

**Minimal reproduction project:**

[Phys.zip](https://github.com/godotengine/godot/files/3206448/Phys.zip)

**Comment by eon-s** [comment]
Convex shape decomposition got some updates recently, can you try on a master build to see if still affects it? (I do not know if there are new options for it too)

**Comment by raphael10241024** [comment]
A Concave Collider is treated as a box actually and center of gravity will be recalculated, not the origin position.

**Comment by KoBeWi** [comment]
Still valid in 3.2.3 rc3

**Comment by AndreaCatania** [comment]
The rigid body can only have convex collisions. A trimesh (concave) shape, which is made of triangles, is too complex to be simulated.
So the physics engine can't simulate properly the dynamics of the RigidBody that has a trimesh shape.

**Comment by pouleyKetchoupp** [comment]
Happens only with ConcavePolygonShape, and there's a warning in the editor:
`ConcavePolygonShape doesn't support RigidBody in another mode than static.`

This is a documented limitation, closing.
