### ISSUE TITLE
Tooltips don't appear when `Engine.time_scale` is 0

### ISSUE THREAD

**Issue by StUNt71** [godotengine/godot#29101]
**Godot version:**
v3.1.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
If i change the parameter timescale to 0 (ex. Engine.SetTimeScale(0f) ). After this, the interface hints are not displayed during the game.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta2

**Comment by Calinou** [comment]
We should scale the tooltip delay according to the current engine time scale.
