### ISSUE TITLE
Objects with "No Depth Test" gets drawn behind the Sky. GLES3

### ISSUE THREAD

**Issue by jejay** [godotengine/godot#29108]
**Godot version:**

3.1.1 stable

**OS/device including version:**

Ubuntu 18.04. RTX Quadro 5000, Driver Version: 418.67

**Issue description:**

Objects with "No Depth Test" gets drawn behind the sky. Can be avoided by either checking "Transparent" or setting the environment to a color.

https://youtu.be/YnBT_Qykjzk

**Steps to reproduce:**
1. Open a fresh project
2. Make two MeshInstances occluding each other.
2. Create SpatialMaterial, check "No Depth Test" flag
3. Set the appropriate render priority (1 for the object with the material).

**Comment by Jummit** [comment]
This was annoying when I made a gun that should always render on top of everything.
