### ISSUE TITLE
GodotSharp C# solution fails to build due to duplicated Object.ToString method

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#29116]
**Godot version:**
`master` / fa5cc1da7a

**OS/device including version:**
Manjaro KDE 18.0.4

**Issue description:**
When I launched the editor first time after upgdading it to the latest master, it tries to rebuild _GodotSharp_ solution but fails with a message says that `ObjectType/Object.cs` contains a duplicated method `ToString()`.

I was able to build the solution after deleting the offending method definition from the generated source.

**Comment by lukaszbulzacki** [comment]
Same problem is on windows.
