### ISSUE TITLE
Spinner doesn't stop with some control elements

### ISSUE THREAD

**Issue by alvaromunoz** [godotengine/godot#29114]
**Godot version:** 3.1.1

**OS/device including version:** MacOS Mojave

**Issue description:** The spinner doesn't stop rotating whenever I select some control elements (like a button), consuming a lot of cpu and battery even when it shouldn't update in the editor.

**Steps to reproduce:** Here's a gif:
![Kapture 2019-05-22 at 17 45 03](https://user-images.githubusercontent.com/2722773/58211427-e425fe80-7cb9-11e9-8eb7-6e045a2ca5ba.gif)

**Minimal reproduction project:**

**Comment by Jummit** [comment]
This is also the case when opening the code editor, even if the cursor isn't visible (at least in 3.1.1).

**Comment by KoBeWi** [comment]
Fixed in 3.2
