### ISSUE TITLE
image loading 16bit internally only working with 8bit

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#2911]
loading 16bit grayscale internally strips down to 8bit
this strips down the resolution ( for example: a heightmap for terrain) from 16bit  to 8bit
with 2 simple hacks i managed to load it 16bit...so that shouldnt be a big problem.

trackhelp:
gray16 is a static fake var from me :)
faking color itself didnt work (loc2)

loc1:

```
    if (!gray16)
    {
        if (depth > 8) {
            png_set_strip_16(png);
            png_read_update_info(png, info);
        }
    }
```

loc2:

```
    switch(color) {
        ....
        case PNG_COLOR_TYPE_GRAY: {

            fmt=Image::FORMAT_GRAYSCALE;
            components=1;
            if (gray16)
            {
                fmt = Image::FORMAT_GRAYSCALE_ALPHA;
                components = 2;
            }
        } break;
         ....
```

**Comment by reduz** [comment]
godot textures are 8 bits only, this will change in 3.0

**Comment by bojidar-bg** [comment]
Bumping just in case... (and hoping @reduz did it in the recent Image remake)

**Comment by reduz** [comment]
PNG will remain at 8 bit, use exr or hdr for higher dynamic ranges which are now supported. closing this one!
