### ISSUE TITLE
"ERROR: get_class_info: GetTypeInfo fallback. Bug!" when running the project

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#29117]
**Godot version:**
`master` / fa5cc1da7a

**OS/device including version:**
Manjaro KDE 18.0.4

**Issue description:**
After I updated the engine to the latest master, I'm getting the following message when I run my game:
```
ERROR: get_class_info: GetTypeInfo fallback. Bug!
   At: ./core/type_info.h:91.
ERROR: get_language: Index p_idx=2 out of size (_language_count=0)
   At: core/script_language.cpp:84.
```
There seems to be no apparent problem to the functionalities of the project, however. It may be related to Mono but I'm not entirely certain.

**Comment by neikeq** [comment]
I cannot reproduce this on latest master (a46b8e1ebfa0ef97c1fba046c6f2d975973c9401), Ubuntu 18.04 64-bit.

**Comment by qarmin** [comment]
I got today this error:
```
ERROR: get_class_info: GetTypeInfo fallback. Bug!
   At: ./core/type_info.h:91.
```
But I'm not using mono, just GDScript.

**Comment by neikeq** [comment]
What parameters are those who can reproduce this passing to SCons? Are you building with a custom module of some sort?

**Comment by qarmin** [comment]
I compiled basic Godot with simplest parameters without any modules:
```
scons p=x11 -j6
```

**Comment by neikeq** [comment]
As I cannot reproduce this, can you share a small project where you can reproduce this issue?

**Comment by qarmin** [comment]
I tried to get error but now my projects doesn't show this error

**Comment by neikeq** [comment]
Do you mean you can't reproduce it in a new project or the one you could reproduce it on before?

**Comment by qarmin** [comment]
I can't reproduce the error in all my projects, both in which this error was visible, and those that I haven't checked before

**Comment by volzhs** [comment]
```
~$ godot3
OpenGL ES 3.0 Renderer: GeForce GTX 1070 Ti/PCIe/SSE2
ERROR: get_class_info: GetTypeInfo fallback. Bug!
   At: ./core/type_info.h:91.
```
I got this too when just launching project manager.
compiled 86f9d1bf5 with gcc 8.3.0 on Kubuntu 19.04

**Comment by neikeq** [comment]
I was able to reproduce it in `release_debug` instead of `debug`.

**Comment by mysticfall** [comment]
I can confirm that my build script (which was appropriated from an old AUR package) contains `release_debug` flag like this:
```
scons platform=x11 target=release_debug CXX=clang++ -j$(nproc) tools=yes module_mono_enabled=yes mono_glue=no
```

**Comment by neikeq** [comment]
The problem is with the method `VisualShaderNodeGroupBase::set_control(Control *, int)` which was introduced in 5648924eefdcaecd62d67b854147635c84206c7b. For some reason it `GetTypeInfo<Control *>` is not using the correct template specialization.

**Comment by akien-mga** [comment]
CC @Chaosus

**Comment by Chaosus** [comment]
Will fix it now..
