### ISSUE TITLE
Make possible to navigate overflowed 'PopupMenu's without a scroll wheel

### ISSUE THREAD

**Issue by isnt-alice** [godotengine/godot#29111]
**Godot version:**

15cda53

**OS/device including version:**

Linux

**Issue description:**
And therefore I cannot select a bone.

**Steps to reproduce:**
Use a BoneAttachment node in a skeleton with hundreds of bones

**Minimal reproduction project:**

[TooManyBones.zip](https://github.com/godotengine/godot/files/3209067/TooManyBones.zip)
https://user-images.githubusercontent.com/48971470/58204044-508c0800-7c90-11e9-8d11-c4642424b9ee.png

**Comment by YeldhamDev** [comment]
You can navigate overflowed menus with the scroll wheel.

**Comment by isnt-alice** [comment]
I don't have a scroll wheel.

**Comment by Zylann** [comment]
We should be able to add optional arrows on top and bottom of the menu, which when hovered or clicked scroll the menu up and down.
But when I see such list of bones I think it should open a better suited popup with a listview and search bar.

**Comment by KoBeWi** [comment]
While we are at it, it would be cool if the menu also scrolled to whatever item was selected. If you use arrows on overflown popup, you can select item out of view and there's no way to tell what did you select. (this is also a problem for my PR #28841 which implements searching for OptionButton)
