### ISSUE TITLE
Will Godot use GitHub Sponsors?

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#29126]
Is using [GitHub Sponsors](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/) alongside Patreon a possibility? What are the upsides / downsides?

**Comment by akien-mga** [comment]
It's only for individuals for now so we can't participate with @godotengine.

We're discussing with GitHub nevertheless to see what could be future options. But this doesn't need to be discussed in a GitHub issue, that's a matter for the Godot Project Leadership Committee to discuss and decide.

**Comment by thejustinwalsh** [comment]
Github Sponsors is open to teams now. [Defold ](https://github.com/defold) is using it. I want that Godot badge!! ;)

**Comment by gstavrinos** [comment]
Just throwing here that I am eagerly waiting for godot to join the github sponsors program to chime in! :)

**Comment by Jummit** [comment]
This issue was originally opened as a question. If this is still under discussion, maybe a proposal at godotengine/godot-proposals can be opened.
