### ISSUE TITLE
The memory  will not be collected  in gdnative

### ISSUE THREAD

**Issue by zhangshiqian1214** [godotengine/godot#29128]
I test the gdnative, try use pass argument to c++, Then I found no matter how many time I wait,
The memory used in the application won't be collected.

```c++
//test_bind.cpp

Test::Test()
{
}

Test::~Test()
{
}
void Test::_init()
{
}
void Test::_register_methods() {
    register_method("test", &Test::test);
}
Variant godot::Test::test(const String name, const Array buffer)
{
   return Variant();
}
```

```gdscript
# Main.gd
const Test = preload("res://bin/test.gdns")
onready var test= Test.new()

# Called when the node enters the scene tree for the first time.
func _ready():		
    pass # Replace with function body.

# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
func _on_Button_pressed():
    for i in range(10000):
        var buffer = Array()
	buffer.resize(1024)
	test.test("hello world", buffer)
```

[gdnative_test.zip](https://github.com/godotengine/godot/files/3826808/gdnative_test.zip)

**Comment by TheDuriel** [comment]
`var buffer = Array()`

if written as

`var buffer = []`

it should work as expected

**Comment by zhangshiqian1214** [comment]
> `var buffer = Array()`
> 
> if written as
> 
> `var buffer = []`
> 
> it should work as expected


### 1. I use the code you give, but still not collect the memory

```gdscript
# Main.gd
const Test = preload("res://bin/test.gdns")
onready var test= Test.new()

# Called when the node enters the scene tree for the first time.
func _ready():		
    pass # Replace with function body.

# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
func _on_Button_pressed():
    for i in range(10000):
        var buffer = []
	buffer.resize(1024)
	test.test("hello world", buffer)
```
#### Then I click the test button some times
![image](https://user-images.githubusercontent.com/9353330/58299027-41cc5f00-7e10-11e9-892b-99577ef26d1f.png)

#### This is before I click
![image](https://user-images.githubusercontent.com/9353330/58298977-0b8edf80-7e10-11e9-9208-bc6a36162008.png)

#### This is after I click
![image](https://user-images.githubusercontent.com/9353330/58299003-295c4480-7e10-11e9-8184-f712ef983f08.png)

### 2. Actually, I want to pass buffer(PoolByteArray instead of Array), because I read binary from file, and pass the binary to gdnative, but i try use PoolByteArray, the result is A lot of Error("All memory pool allocations are in use, can't COW.")

```gdscript
# Main.gd
const Test = preload("res://bin/test.gdns")
onready var test= Test.new()

# Called when the node enters the scene tree for the first time.
func _ready():		
    pass # Replace with function body.

# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
func _on_Button_pressed():
    for i in range(10000):
        var f = File.new()
	if (f.open("res://test.binary", File.READ)) == OK:
		var buffer = f.get_buffer(f.get_len())
	        test.test("hello world", buffer)
                f.close()
```

**Comment by zhangshiqian1214** [comment]
@akien-mga can you fix this bug

**Comment by zhangshiqian1214** [comment]
I found a commit(GodotNativeTools/godot-cpp@95feb48) in godot-cpp can fix this bug, The cast implicitly calls the C++ type's copy constructor. (You can find it in the gdb disassembly.) This increases the ref-count twice instead of just once through godot_variant_as_*. For PoolArrays, it caused an error message on exiting Godot
