### ISSUE TITLE
Godot 3.1/3.1.1 crashes randomly

### ISSUE THREAD

**Issue by Galaxy613** [godotengine/godot#29135]
**Godot version:**
3.1 - 3.1.1

**OS/device including version:**
Windows 10 Home, 64-bit
Intel Core i7 4710HQ
16GB RAM
GeForce GTX 850M - Driver version 425.31

**Issue description:**
Godot just every once in awhile freezes for a second, and then kills itself. It also causes Chrome that I have open in the other window to go black. But when that happens I can click and drag a tab out of the chrome window, and then chrome will redraw. However Godot is still dead.

**Steps to reproduce:**
Run Godot on my computer, 5 minutes to 5 hours later it'll crash.

**Minimal reproduction project:**
There has not been a single project I've worked on since I started using Godot on this machine that hasn't had this happen. However it seemed to got worse with 3.1.1

**Comment by Galaxy613** [comment]
![image](https://user-images.githubusercontent.com/411932/58281287-c36cb000-7d70-11e9-95b9-e359a26b0f49.png)

**Comment by aaronfranke** [comment]
Does this happen with any other program? Have you tried upgrading and downgrading graphics drivers? Is your GPU at good temperatures? Have you only tested Windows 10?

**Comment by Galaxy613** [comment]
I upgraded my graphics driver this afternoon after collecting these logs - I also did `Win-Shift-Ctrl-B` to manually restart my driver.

Ever since this afternoon Godot 3.1.1 has been running flawlessly. We'll see if that continues into tomorrow and the day after,,, I'll close this by Sunday if I don't have another crash.

I wouldn't have created this issue if updating my drivers helped the first time I encountered this. :\ But when I first started using Godot 3.1 that's exactly what I did and it didn't solve it. So I'm not sure yet if it has been solved, but hopefully it was just old drivers...

**Comment by eon-s** [comment]
That kind of error is usually a system failure and nothing related to Godot (which crashes because the GPU crashed), do some OS and hardware tests (file integrities, GPU temperature, memory, etc.) if that error appears again.

**Comment by LinuxUserGD** [comment]
@Galaxy613 So you will close it?

**Comment by Galaxy613** [comment]
Yeah, Godot is still running strong - must've been my driver.
