### ISSUE TITLE
Using a variable in a tenary if still gives unused class variable warning

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#29131]
**Godot version:**
3.1.1

**Issue description:**
When using a variable in a tenary if Godot still gives me an unused class variable warning.

**Steps to reproduce:**
Create a variable and use it in a tenary if.

**Comment by AMS21** [comment]
Interestingly it doesn't happen when declaring a local variable, only for global ones

**Comment by YeldhamDev** [comment]
CC @vnen

**Comment by ThakeeNathees** [comment]
seems like fixed already

**Comment by Jummit** [comment]
I couldn't reproduce this either. Closing for now.
