### ISSUE TITLE
Cannot inherit subclass of name class

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#29144]
**Godot version:**

Godot 3.1.1

**OS/device including version:**

**Issue description:**

Cannot inherit subclass of name class (defined with `class_name` keyword)
GDScript parser complains with `Could not determine inheritance`

**Steps to reproduce:**

Item.gd
```gdscript
class_name Item

class Bullet:
	func _init():
		print('new bullete')
```

GunBullet.gd
```gdscript
extends Item.Bullet
```

**Comment by paulhocker** [comment]
if you want a Bullet to be an Item, does it not make sense to have two different class files? 

one for Item, and then one for Bullet that extends Item?

Then all you have to do is extend the Bullet class on the GunBullet.
