### ISSUE TITLE
TCP put_string adds string length representing byte to the actual string

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#29153]
**Godot version:**
Godot 3.1 Stable

**OS/device including version:**
Arch Linux 5.1.2

**Issue description:**
When setting up a TCP server on godot, `StreamPeer.put_string()` does not work as expected.

For some reason it adds a byte representing the string size to the actual string.

For example, if I try to send a string "Hello world! This is sent from Godot.", the client will receive "%Hello world! This is sent from Godot.", because the string is 37 bytes, and 37 is `%` in ASCII.

**Steps to reproduce:**
Create a TCP server in Godot and try to send strings with `StreamPeer.put_string()`

**Minimal reproduction project:**
[mini-demo.tar.gz](https://github.com/godotengine/godot/files/3217260/mini-demo.tar.gz)

**Comment by akien-mga** [comment]
That's the documented behaviour: http://docs.godotengine.org/en/latest/classes/class_streampeer.html#class-streampeer-method-put-string

You can use `put_data(string.to_ascii())` if you don't want the length of the string.

@Faless That's the second issue about this today with #29150, I'll let you see if anything needs to be improved.

**Comment by PonasKovas** [comment]
In what situation would you possibly want to use this function?

The name is misleading, and I suggest you do something about it

**Comment by Faless** [comment]
> In what situation would you possibly want to use this function?

Whenever you want to write a string and its size in the stream.

For example, if you send 2 consecutive strings you need a way to separate them on receive.
If you don't put the size or a terminator, the retrieving end will concatenate the two original strings thinking it was one.

**Comment by PonasKovas** [comment]
That makes sense.

I think providing an example on the docs of the use of this function would save a lot of time for most people

**Comment by zaksnet** [comment]
> > In what situation would you possibly want to use this function?
> 
> Whenever you want to write a string and its size in the stream.
> 
> For example, if you send 2 consecutive strings you need a way to separate them on receive.
> If you don't put the size or a terminator, the retrieving end will concatenate the two original strings thinking it was one.

You could read from the stream until some kind of "endTag", or custom terminator. It could be newLine or anything custom like "{end}". That way you know when you reach "{end}" its the end of the first string.
