### ISSUE TITLE
The documentation for assert() doesn't state that it's only run in debug mode

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#29154]
I got an unused variable warning for `indoors_area` in this code:

```
extends Node2D

onready var indoors_area = NodeUtils.node_or_null(self, "IndoorsArea")

func _ready():
    assert(indoors_area.connect("body_entered", self, "_on_body_entered") == OK)

func _on_body_entered(body):
    if (!body.has_method("set_indoors")):
        return
        
    # ...
```

According to [this comment](https://godotengine.org/qa/270/what-does-the-assert-function-do?show=282#c282), the code within an assert is only run in a debug build, which I guess is what the warning is trying to point out. However, the [documentation](https://docs.godotengine.org/en/3.1/classes/class_@gdscript.html#class-gdscript-method-assert) doesn't clearly state this:

> Assert that the condition is true. If the condition is false a fatal error is generated and the program is halted. **Useful for debugging** to make sure a value is always true.

It just says "useful for debugging", not "the code within the assert is only run in a debug build". There is quite a big difference between the two, as it is possible to get hard-to-find bugs from code that suddenly stops being executed in a release build, especially if you:

- Disregard the warning ("I'm using the variable in the connect call, so I'll just ignore that warning"), or
- Don't have "Treat Warnings As Errors" enabled.

**Comment by PetePete1984** [comment]
It's mentioned in the list of keywords on the GDScript basics page: https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#keywords

But I agree, it would be better to have that on the other page, too.

**Comment by mitchcurtis** [comment]
> https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#assert-keyword

Ah, cool. Pity I didn't see it.
