### ISSUE TITLE
StreamPeer: Send a socket message without the "32 bits unsigned integer".

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#29150]
**Godot version:**

v3.1_Stable

Hello,
```
void put_string( String value )
Put a zero-terminated ascii string into the stream prepended by a 32 bits unsigned integer representing its size.
```
As the docs state, when using put_string("some data") it also sends a 32 bits unsigned integer along with "some data". I would like to know if it is possible to overide that or maybe be added in a future version of godot.
Thank you.

**Comment by akien-mga** [comment]
`put_data("some data".to_ascii())` might do the trick.

**Comment by zaksnet** [comment]
Great, that worked, thank you!

**Comment by zaksnet** [comment]
Great, that worked, thank you!
