### ISSUE TITLE
Port Rooms and portals from 2.1

### ISSUE THREAD

**Issue by HeadClot** [godotengine/godot#29160]
In Godot 2.1 there was a feature for rooms and portals. It would be great it was ported to Godot 3.2.

Details here on what they do.
https://docs.godotengine.org/en/2.1/classes/class_room.html
https://docs.godotengine.org/en/2.1/classes/class_portal.html

The Code is found here in the 2.1 branch.
https://github.com/godotengine/godot/blob/2.1/scene/resources/room.cpp
https://github.com/godotengine/godot/blob/2.1/scene/audio/sound_room_params.cpp
https://github.com/godotengine/godot/blob/2.1/scene/3d/portal.cpp

Why do I need it?
So that I am not drawing an entire 3D level per frame. This would greatly improve performance for 3D games and large 2D games.

**Comment by eon-s** [comment]
It is on the roadmap https://github.com/godotengine/godot-roadmap/blob/master/ROADMAP.md#3d-rendering-features

**Comment by HeadClot** [comment]
OK, I am getting to the point where I REALLY need this. I have a fairly dense master scene with a bunch of sub-scenes consisting of grid maps. If some one were to work on this is would be greatly appreciated.

**Comment by Calinou** [comment]
Closing in favor of #22048, which has more information on the subject.
