### ISSUE TITLE
ViewportSprite with Material set to Lights Only affects other pixels at the same screen position

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#2916]
A ViewportSprite with Material set to Lights Only affects pixels at the same screen position even when the visibility of the ViewportSprite is turned off. It also affects other ViewportSprites with material set to Lights Only, the light masks affecting the ViewportSprites adding to each other. 

In this example a ordinary 2D sprite has a 'shadow' (red dotted circle) where the light affecting the ViewportSprite with Material set to Lights Only is positioned but the visibility turned off. 
![texture_mask04](https://cloud.githubusercontent.com/assets/15687516/11422835/80933236-943f-11e5-99c0-aec78b1bb7c4.png)

The ViewportSprites in the next image examples each has a 2D light with a texture mask added to them to create the desired masking effect.

In this image the two faces are ViewportSprites  with Material set to Lights Only.
![texture_mask01](https://cloud.githubusercontent.com/assets/15687516/11422419/1ab07026-943c-11e5-8fde-500100f655cf.png)

In this image a third ViewportSprite with Material set to Lights Only is also affected by the masked area of the two faces.
![texture_mask02](https://cloud.githubusercontent.com/assets/15687516/11422455/4bfda612-943c-11e5-8f91-dbd61af60aa1.png)

In this image the visibility of the third ViewportSprite has been turned off but its mask still affects the two faces adding to the mask 
![texture_mask03](https://cloud.githubusercontent.com/assets/15687516/11422549/120c8990-943d-11e5-8c4b-7cf33f177b83.png)

**Comment by reduz** [comment]
I think i fixed an issue related to this some days ago.  Lights now have an explicit "Mask" option so you can use them as mask without having to resort to the lights only mode

**Comment by akien-mga** [comment]
Assuming fixed as per reduz's comment above + a lot of time has passed since then. Please comment if there is still more work needed to fully resolve this issue.
