### ISSUE TITLE
Make tutorial links in the documentation more appealing

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#29169]
**Godot version:**
3.1.1

**Issue description:**
Tutorial links look quite ugly at the moment, in my oppionion. Maybe they could have the title as text instead?
![image](https://user-images.githubusercontent.com/28286961/58368343-f6877e80-7eeb-11e9-8521-c2a4bde8369f.png)

**Steps to reproduce:**
Go to a documentation link that has an online tutorial, for example the KinematicBody.

If this is an issue that should go elsewhere, let me know.

**Comment by Calinou** [comment]
Sounds good to me, although we'll need a way to consistently communicate the website origin in the link name. (Some tutorials may be hosted by third parties, this needs to be made obvious.)

**Comment by SaviHex** [comment]
Websites usually show a dialogue telling they are about to leave that website, perhaps this should be done here as well...? If that's too much maybe we could just indicate it next to the title like this:

[**Importing 3d Objects** (from KidsCanCode)](http://kidscancode.org/godot_recipes/g101/3d/101_3d_02/)

I've also found out that there's an ["external link icon"](https://ux.stackexchange.com/a/2502) that could be used as well. Unfortunately, the one in the link is not included in unicode (there's this one 🔗 though...).

I'm trying to contribute for the first time and this looks like an easy first issue but I'm not sure if I'm doing this right so feel free to correct me!

**Comment by Jummit** [comment]
This is fixed in Godot 4.

**Comment by lostptr** [comment]
THIS HAS NOT BEEN CLOSED? Sorry, did I do something wrong in my PR for this not to have been closed until now? 😅 Just wanna know for future contributions
