### ISSUE TITLE
Godot crashes when i try to hide something in this window

### ISSUE THREAD

**Issue by ShRyDeR** [godotengine/godot#29175]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Nothing special but Godot crashed so I thought of mentioning it.
What happened: Godot crashed
What was expected: Hide object from scene

**Steps to reproduce:**
Create new MeshInstance node (3D), select that MeshInstance and go to Inspector... Double click Skeleton and when you see list of nodes: Try to hide one of the nodes using the eye icon on the right and Godot crashes for me.

**Comment by KoBeWi** [comment]
This is fixed in 3.1.1. Just update your Godot version.
