### ISSUE TITLE
Error message 'the code execution cannot proceed because mono-2.0-sgen.dll was not found.' on trying to run compiled binary

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#29170]
After compiling Godot I always get this error when I try to open the compiled Godot binary.

![2019-05-24_19-02-01](https://user-images.githubusercontent.com/5526342/58369468-ae1f8f00-7ef2-11e9-98a6-097bf355d3c3.png)

I've tried several different options in my scons command but it always results in the same thing.

I'm using the latest version of Mono (mono-5.20.1.19-x64)

If I copy "C:\Program Files\Mono\bin\mono-2.0-sgen.dll" into the bin folder then the program opens without issue.

**Comment by ShyRed** [comment]
Another workaround is statically compiling mono using `mono_static=yes`. For example:

```C#
scons platform=windows target=debug vsproj=yes module_mono_enabled=yes mono_static=yes -j5
```

**Comment by neikeq** [comment]
SCons should copy `mono-2.0-sgen.dll` to the output directory automatically. Can you check if it's inside a `bin` folder in `modules/mono` or `modules/mono/build_scripts`? I moved some build system code recently and I think relative paths got messed up.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by neikeq** [comment]
Assuming this is fixed. It can be re-opened otherwise.
