### ISSUE TITLE
Performance drop from 3.0.6 to 3.1?

### ISSUE THREAD

**Issue by masmartyg** [godotengine/godot#29178]
**Godot version:**

v3.0.6.stable.official.8314054 VS v3.1.stable.official

**OS/device including version:**

Windows 10 Pro 1803 build 17134.765
Dell Inspirion 15 5000 series Intel Core i7-6500U 2.50GHz
GPU Intel HD Graphics 520
(tested on bigger desktop workstation with NVidia gpu with same results!)

**Issue description:**

In the creation and runtime positioning of objects the total time used is much longer and the translation of the objects is jerky and not very fluid.

**Steps to reproduce:**
I include an example created with version 3.0.6 and another with version 3.1. In both cases the configuration of the project parameters is the default one.
[TestSpeed3.0.zip](https://github.com/godotengine/godot/files/3219675/TestSpeed3.0.zip)
[TestSpeed3.1.zip](https://github.com/godotengine/godot/files/3219676/TestSpeed3.1.zip)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Tested it on GTX 1060. The time difference is negligible (I get ~100 more ms in 3.1 with GLES2, GLES 3 seems to be the same as 3.0). What do you mean by "much longer"?

**Comment by Ranoller** [comment]
Can´t reproduce in i5 win7 GTX660.
Cubes generate equally.
And without VSYNC:
3.0 project runs at 2095 fps
3.1 project in GLES2 runs at 2714.
You should make a video to illustrate the problem.

**Comment by masmartyg** [comment]
In 3.0 the execution time is 2250 ~ 2350, in 3.1 it is 3730 ~ 3760 (I changed the movement of the cubes to a fixed value), nothing chance when exporting (Windows desktop).
The profiler shows a longer idle time in 3.1.
At the end of the video you see that moving the 3.0 window is more fluid than the 3.1 window.

![3 0](https://user-images.githubusercontent.com/41666170/58378959-d4016e00-7f9c-11e9-9a15-6e7213b8135b.png)
![3 1](https://user-images.githubusercontent.com/41666170/58378960-dd8ad600-7f9c-11e9-9b93-4d22bd39957a.png)

[VideoComparison3.0-3.1.mp4.zip](https://github.com/godotengine/godot/files/3220088/VideoComparison3.0-3.1.mp4.zip)

**Comment by masmartyg** [comment]
With 3.1.1 it's even worse! the execution time changes to 3800 ~ 4200 ...

![3 1 1](https://user-images.githubusercontent.com/41666170/58379063-9ef61b00-7f9e-11e9-9946-47235cb0ffb6.png)

**Comment by groud** [comment]
If I am not mistaking, the Idle time corresponds to the time the engine is doing nothing, waiting for the the next frame.
So what you see here is maybe instead a performance increase.

Have you disabled vsync?

**Comment by masmartyg** [comment]
I need vsync...

I found that in the Debugger -> Monitor tab, the FPS are at 30 in 3.1 and 60 in 3.0 ...?
In Project Settings-> Debug-> Settings I put FPS at 60 on both of them and StdOut-> Print FPS at on and on 3.0 reach 60 frames while on 3.1 they stop at 30 ... I can't find other settings in Godot for set the frame rate. In the settings of the video card I have set the same configuration for both Godot version.

**Comment by masmartyg** [comment]
Tested with AMD Radeon HD 5700 Series: Both versions run at 30 FPS.
Tested with GeForce GTX 1080: Both versions run at 60 FPS.

At this point it seems clear to me that the problem is my lack of knowledge of the subject and configuration of the video cards. I believe the issue should be closed.
I thank all those who participated by trying the tests and giving me advice and I hope I didn't make you lose too much time.

Ciao
masmart
