### ISSUE TITLE
Project Manager - add ability to move projects up & down in list

### ISSUE THREAD

**Issue by randibit** [godotengine/godot#29183]
[Feature Request] Project Manager - add ability to move projects up & down in list

**Godot version:**
3.1.1 but this is not related to a specific version

**OS/device including version:**
Win7

**Issue description:**
Minor suggestion to allow the user to move a project up and down in priority / order in the project manager.

**Steps to reproduce:**
Open the Godot Engine - Project Manager
Would be nice to have buttons on the menu to reorder the projects.

The idea is to have current projects bubbled up to the top or whatever the user wishes to reorder for.

Thank you

I drafted the idea over a screenshot to show what I'm asking for:
![Suggestion - Project Manager - Move Project up-down in list](https://user-images.githubusercontent.com/50721970/58377740-07f87700-7f3c-11e9-8a95-9256bb7f5e3e.png)

**Comment by randibit** [comment]
More specifically, like this:
Increment / decrement position and TOP to send to priority spot #1.
![image](https://user-images.githubusercontent.com/50721970/63980503-ada60f80-ca70-11e9-8c23-e6d9c34a6070.png)
My wishlist improvement design sent to Amazon and used for years and Valve which is now using it too.
Thanks

**Comment by Calinou** [comment]
There is one issue I can see given the current project manager organization. Since projects are always sorted by a criterion (name, path, last modification), reordering projects would imply the list is no longer ordered by the selected criterion.

**Comment by randibit** [comment]
> There is one issue I can see given the current project manager organization. Since projects are always sorted by a criterion (name, path, last modification), reordering projects would mean the list is no longer ordered by the selected criterion.

That's a good point I thought of but did not comment on.  Can the sorting be changed to custom upon manually reordering it?  Then perhaps put a toggle nearby which says "Criterion / Custom" or something to that effect.

**Comment by randibit** [comment]
> There is one issue I can see given the current project manager organization. Since projects are always sorted by a criterion (name, path, last modification), reordering projects would mean the list is no longer ordered by the selected criterion.
New rendering... (I know someone beat me to the clone project, but I just threw that in too for placement)
![Godot Project list suggestions](https://user-images.githubusercontent.com/50721970/63982370-0f697800-ca77-11e9-9e16-b44cdc236f44.png)

**Comment by aaronfranke** [comment]
@randibit Is this feature still desired? This is very low priority, and is not something I would personally use. This is something that I would suggest we close unless many users have a strong desire for this feature.

**Comment by randibit** [comment]
IDC, I moved on to another game engine.
