### ISSUE TITLE
Autocomplete dialog not popping up when calling a custom class's function from outside the file

### ISSUE THREAD

**Issue by Imvoo** [godotengine/godot#29195]
**Godot version:**
3.1.1 (no C#)

**OS/device including version:**
Windows 10 1809

**Issue description:**
The autocomplete dialog pops up when calling a function in the same class it is defined. It does not popup when an instance of that custom class is made, and the function is called on that instance.

e.g. I have two classes/nodes, Main and Outputter. Outputter has a function called `output(text: String)`. If I write `output(` in class Outputter's `_ready`, I can see the autocomplete pop up that says `null output ( String text )`.

![](https://i.imgur.com/EXOaqVb.png)

However, if I make an instance of class Outputter in Main and call `outputter.output(`, it just completes the braces and doesn't show me the autocomplete dialog/popup.

![](https://i.imgur.com/oCFrb1E.png)

**Steps to reproduce:**
Make two nodes, Main and Outputter and attach the following scripts:

```
# Attach me to Outputter node
class_name Outputter
extends Node2D

func _ready() -> void:
    pass
    # writing line below shows me autocomplete dialog
    # output(

func output(text: String) -> void:
    print(text)
```

```
# Attach me to Main node
extends Node2D

func _ready() -> void:
    var outputter := preload("res://outputter.tscn").instance() as Outputter
    # line below does not popup autocomplete dialog 
    # outputter.output()
```

In `_ready()` in Outputter, type in `output(` and notice that the autocomplete dialog pops up.

In `_ready()` in Main, type in `outputter.output(` and notice that there is no autocomplete dialog.

**Minimal reproduction project:**
[autocomplete-dialog-bug.zip](https://github.com/godotengine/godot/files/3220393/autocomplete-dialog-bug.zip)

**Comment by KoBeWi** [comment]
Still valid in 3.2.3 rc3

**Comment by luislodosm** [comment]
Still valid in 3.2.3. Any news?

**Comment by HolonProduction** [comment]
Doesn't apply to 4.x
