### ISSUE TITLE
How to detect if a sprite is touched/clicked?

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#29190]
If you go [here](https://www.reddit.com/r/godot/comments/7xwr22/guide_how_to_click_a_sprite/), Someone proposed this code, and his code was [merged](https://github.com/godotengine/godot/pull/16756)  

```
extends Sprite

func _unhandled_input(event):
    if event is InputEventMouseButton and event.pressed and not event.is_echo() and event.button_index == BUTTON_LEFT:
        if get_rect().has_point(event.position):
            print('test')
            get_tree().set_input_as_handled() # if you don't want subsequent input callbacks to respond to this input
```

When I try that, it doesn't work, what's the correct way of doing that? What was merged? Isn't that feature available in Godot 3.1?

**Comment by KoBeWi** [comment]
Rect2 returned by `get_rect()` is in local coordinates. You need to change your condition to
`if get_rect().has_point(to_local(event.position)):`

I guess that could be clarified in the docs.

**Comment by elieobeid7** [comment]
That works perfectly thank you! Should I close this issue or leave it open until documentation is added? As far as I can tell, this entire feature is nowhere to be found in the docs, it still says that one needs area2d and so forth.

**Comment by groud** [comment]
In any case that's not the place to ask questions about how to use the engine, but to report bugs and ask features /enhancement to the engine.

**Comment by njt1982** [comment]
I've had issues getting this to work if the camera is moved/zoomed in? the to_local() doesn't seem to take the viewpoint into account?

**Comment by njt1982** [comment]
This worked, though...
```
extends Sprite

func _unhandled_input(event):
    if event is InputEventMouseButton and event.pressed and not event.is_echo() and event.button_index == BUTTON_LEFT:
        if get_rect().has_point(get_local_mouse_position()):
            print('test')
            get_tree().set_input_as_handled() # if you don't want subsequent input callbacks to respond to this input
```

**Comment by Nutriz** [comment]
I've had also issue with this. When the sprint is scaled, this technique don't work. I found a workaround but it's still not too easy and clear to do a clickable sprint IMO.

Workaround:
```gdscript
func isMouseOverPiece(position):
	var rect_end = $Sprite.get_rect().end*$Sprite.scale
	var real_rect = Rect2($Sprite.position.x, $Sprite.position.y, rect_end.x, rect_end.y)
	return real_rect.has_point(to_local(position))
```
