### ISSUE TITLE
Spatial lock status not saved

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#29196]
**Godot version:**
3.1.1

**OS/device including version:**
N/A

**Issue description:**
I tried to make a MeshInstance "locked" so that I could not move it accidentally. When I reopen the scene, the node is again unlocked. Git doesn't show any changes related to locking.

Might be important: the mesh instance is inherited from a base scene (the whole .tscn was created as 'make new inherited' from an imported .dae file)

**Steps to reproduce:**
Attempt to mark a mesh instance as locked.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Related to #12990 and #12838

**Comment by KoBeWi** [comment]
This is basically the same as #12838, so closing.
