### ISSUE TITLE
Playing a project while having an AnimationPlayer selected makes the animation tab override the output tab

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#29209]
**Godot version:**
 252c841

**Issue description:**
Pretty much what the title says, if you have an `AnimationPlayer` node selected and play your project, it will attempt to open the output tab, only to go back to the animation tab.

**Comment by avencherus** [comment]
I have trouble reproducing this.  If you're able reliably recreate it, I wanted to ask if it is also causing the resize handle to stop working too?

On some rare occasions we've had the AnimationPlayer panel pop open, and it couldn't be resized, until toggling it on and off using the bottom tabs.

![image](https://user-images.githubusercontent.com/13004169/58397568-3b312800-805a-11e9-9f0e-4e1ff2e3110f.png)
**This thing disappears sometimes.**
