### ISSUE TITLE
Clean search help results at script tab

### ISSUE THREAD

**Issue by danilojr** [godotengine/godot#2920]
Could you give a option to clean search help results or disable it?  My script tab get flooded with these history results together with scripts.

![script-tab-help-search](https://cloud.githubusercontent.com/assets/13174433/11429118/41d77a9e-9452-11e5-8c53-1a2b80c1083b.jpeg)

**Comment by volzhs** [comment]
There is option for it if you use latest commit.
Settings -> Editor Settings -> Text Editor -> Group Help Pages

**Comment by akien-mga** [comment]
You can close both scripts and help pages with File > Close (Ctrl+W).

**Comment by danilojr** [comment]
Wow..  I didn't know it!  

Thank you!
