### ISSUE TITLE
interpolate_callback not work when input arg is null

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#29204]
godot 3.1
May be is a same problem with [#9187](https://github.com/godotengine/godot/issues/9187)

```
var b = camera_tween.interpolate_callback(self, _duration, "camera_fin", false, null)
camera_tween.start()

func camera_fin(delete_prev, new_scene):
	set_process(false)
	emit_signal("camera_stop")
```
var b return true so the tween is called, but when input arg is null, the camera_fin function never call, even the null param not used in the callback func, I think that's a big problem

**Comment by KoBeWi** [comment]
Did you call `camera_tween.start()`?

**Comment by firecloud888** [comment]
Yes, Of course.

**Comment by KoBeWi** [comment]
Nevermind, I changed the null to false when testing and forgot to change it back. The bug might have something to do with the fact that null is a default argument. Well, the method signature looks hacky anyways.

**Comment by firecloud888** [comment]
Yes, finally I pass the arg to outside to avoid it appear in the input param.

**Comment by KoBeWi** [comment]
Still valid in 9adf6d344

**Comment by KoBeWi** [comment]
No longer a problem with new Tweens in 4.0
