### ISSUE TITLE
LightOccluder2D doesn't work with Godot 3.1.1 on Huawai H60-L04 (GPU Mali-T624)

### ISSUE THREAD

**Issue by MaurizioMacri** [godotengine/godot#29208]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
OS: Android 6
Device: Huawai H60-L04
GPU:  Mali-T624

**Issue description:**
I have a scene with some lights and one 2d occluder. It works well on my computer but the occluder doesn't work on my Android device (Huawai H60-L04, GPU Mali-T624). I'm using godot 3.1.1 and I'm sure everything worked fine till version 3.0.0. Also i have a lot of these errors (just with the smartphone):
```
E 0:00:00:0281   Condition ' status != 0x8CD5 ' is true. Continuing..:
  <C Source>     drivers/gles3/rasterizer_scene_gles3.cpp:5124 @ initialize()
```

If i run it with GLES2 i got just one of these:

```
E 0:00:01:0238   Condition ' status != 0x8CD5 ' is true. returned: RID()
  <C Source>     drivers/gles2/rasterizer_storage_gles2.cpp:4841 @ canvas_light_shadow_buffer_create()

```

**Steps to reproduce:**
Just create a scene with a sprite, a 2d light and a 2d occluder. 
Run the scene on the device.
Everthing works fine except there is no occluder

**Minimal reproduction project:**
[shadow_test.zip](https://github.com/godotengine/godot/files/3221388/shadow_test.zip)

**Comment by clayjohn** [comment]
Buffer creation has changed substantially between 3.1 and 3.2. I am confident that this bug has been fixed. If you are still experiencing this bug with version 3.2, let me know and I will reopen
