### ISSUE TITLE
Dragging functions in script editor move a script name

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29216]
**Godot version:**
3.2 b9ee3f3

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
![file](https://user-images.githubusercontent.com/41945903/58416109-d63cf880-8080-11e9-979a-0b3382c1847e.gif)

**Comment by Jummit** [comment]
Should this be fixed by not making the methods draggable or not changing the order of the scripts?

**Comment by bojidar-bg** [comment]
I think this should be fixed by not allowing methods to be dragged around, as they are sorted alphabetically anyway (AFAIK/S).
