### ISSUE TITLE
ProximityGroup poorly documented

### ISSUE THREAD

**Issue by io12** [godotengine/godot#29211]
**Godot version:**

v3.1.1.stable.official

**Issue description:**

The documentation for [ProximityGroup](https://docs.godotengine.org/en/3.1/classes/class_proximitygroup.html) describes it as a "general purpose proximity-detection node." This sounds a lot like an `Area`. I couldn't find any information online on how to use it, or what it does different from `Area`.

**Comment by MJacred** [comment]
I'll try to flesh it out in the coming days (provided I understand the code, my C++ is rusty...)

**Comment by KoBeWi** [comment]
ProximityGroup was removed in 4.0, so now this is only relevant for 3.x branch.

**Comment by MJacred** [comment]
@KoBeWi: fixed in #60636
