### ISSUE TITLE
When switching scenes Animation panel sometimes loses ability to resize.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#29213]
**Godot version:**

**OS/device including version:**

Win10 64-bit

**Issue description:**

When switching to a scene with an AnimationPlayers and the panel is re-opened, it can lose its resizing handle until the tab button is pushed to close it and reopen it.

This is the result of the missing resize handle.
![image](https://user-images.githubusercontent.com/13004169/58397983-e8587000-805b-11e9-9efc-7ccbe51367eb.png)

This is what is expected.
![image](https://user-images.githubusercontent.com/13004169/58397994-f4443200-805b-11e9-9051-a071d126e7b8.png)

**Steps to reproduce:**
1. Create two scenes, at least one with an AnimationPlayer.
2. Have the AnimationPlayer panel open in one scene.
3. Switch to another scene, and make sure to close the panel.
4. Then switch back to the scene with the AnimationPlayer selected.

**Comment by YeldhamDev** [comment]
Guess did not fix this correctly then.
