### ISSUE TITLE
AnimationPlayer lacks a way to re-arrange track groups.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#29212]
**Godot version:**

252c841d7ff5d770e8d2819e4f7955363410744b

**Issue description:**

As far as I can tell, there is no way to re-arrange track groups.  At least not with dragging.  It is very difficult to work in this mode when doing larger animations, as the track groups can't be organized for workflow.

![image](https://user-images.githubusercontent.com/13004169/58397423-91ea3200-8059-11e9-8303-380924cdc241.png)

**Comment by elvisish** [comment]
Is it still not possible to rearrange animation tracks?

**Comment by Calinou** [comment]
> Is it still not possible to rearrange animation tracks?

I don't think it is, but this should be reopened as a feature proposal on the Godot proposals repository. This is because this repository is now used for bug reports only.
