### ISSUE TITLE
Dictionary values in instanced scene are not updated from parent

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#29221]
**Godot version:**
Master dev 25d2ee677ffd460d90059f0c94e0b068bd09c3b3

**OS/device including version:**
Windows 10

**Issue description:**
When using a dictionary export variable in an instanced scene, values are always saved in the scene as if they were overridden for the instance.

This causes dictionary values not to be updated in the instance when the parent scene is modified.

Expected behavior:
- When saving scene: Save dictionary values only when they are modified in the instance
- In the inspector: Update dictionary values in the instance when the parent scene is modified

Note 1: It's possible to work around the issue by resetting the dictionary in the inspector for each instance and save the scene again, but that's not a viable solution for large projects.

Note 2: This problem is specific to dictionaries, arrays are working fine.

**Steps to reproduce:**

Prepare parent scene:
- Create a new scene with just one node (scene A)
- Add a script to this node with a Dictionary export variable
`export(Dictionary) var _dictionary = {}`
- Add one entry to the dictionary
- Save scene A

Prepare scene with instance:
- Create a new scene (scene B)
- Add an instance of scene A in scene B
- Save scene B

Update parent scene:
- Open scene A again
- Add another entry to the dictionary

Observe the issue:
- Open scene B again
- The dictionary in the instance contains only one entry

**Minimal reproduction project:**
[test-dict-save.zip](https://github.com/godotengine/godot/files/3223847/test-dict-save.zip)

**Comment by RandomShaper** [comment]
This should be fixed by #35816.

**Comment by akien-mga** [comment]
Tested in current `master`, confirmed fixed.
