### ISSUE TITLE
Triplanar Texturing Node In Visual Shader Editor

### ISSUE THREAD

**Issue by mindinsomnia** [godotengine/godot#29220]
Hello there,

I was advised by Calinou to create an issue to request this feature.

Triplanar texture mapping  is incredibly useful for a number of reason, and I can see it's an option when using the editor for SpatialMaterial. But it would be really super useful to have the option to use triplanar texture filtering in the visual shader editor too, and as far as I know that currently isn't possible in the current visual shader editor and I believe (correct me if I'm wrong) it isn't possible in the new updated visual shader editor as well?

It would be especially useful to have triplanar texture mapping for procedural materials that use seamless repeating textures on objects of any shape or size. Would it be possible to implement this in 3.2 along with the other new nodes in the new visual shader editor?

Side note: How would triplanar texture mapping effect normal maps in this regard and would it be possible for those to work as expected using the visual shader editor?

Thanks!

**Comment by clayjohn** [comment]
I'm not sure this makes sense as a "feature" because you can just implement it yourself using the current nodes. 

Alternatively, in 3.2, you can make a SpatialMaterial, select "Convert to ShaderMaterial", then copy the relevant code into an expression node in your VisualShader.

**Comment by mindinsomnia** [comment]
I'm sure you could can implement yourself but you could also implement yourself in Blender's shader editor, but they still added it as a feature. Implementing it yourself with nodes or copy pasting shader code would kinda defeat the purpose of having an easy to use shader node editor, especially if you use it for lots of materials?

**Comment by clayjohn** [comment]
The visual shader editor is not the same as blenders material node system. Its meant as a way to let users write shader code using nodes, rather than an all out material system that replaces shaders completely. If you need triplanar texturing it is provided out of the box in the SpatialMaterial.

**Comment by mindinsomnia** [comment]
Well if anyone does feel like implementing this feature it would be super appreciated. It would save a huge amount of time for artists and be easier to use than having to create a bunch of nodes to replicate the functionality or copypaste shader code from a spatial material, and make it easier to create materials that mix 2 or more triplanar textures.

**Comment by clayjohn** [comment]
@Chaosus What do you think?

**Comment by Chaosus** [comment]
Well I think such function may be implemented..

**Comment by mindinsomnia** [comment]
@Chaosus Amazing work, fantastic! That's just perfect, that little node will be so useful!

**Comment by Nodragem** [comment]
I am not sure how to use this node. Let’s say we want to have a texture for the top plane and another texture for the side plane. Is it possible to combine the 2 textures with this node? Or do I need to use the node twice?
