### ISSUE TITLE
Ability to export data.pck only

### ISSUE THREAD

**Issue by est31** [godotengine/godot#2923]
Some people used the -export command line param without a destination binary in the past to create the data.pck file only. This however doesn't work anymore, see #2921 and #2843. Workaround right now is to specify the destination binary, and then pick the data.pck from the same directory as the target binary.

**Comment by vnen** [comment]
One interesting thing would be to have command line options for modifying the export. Doesn't need to have all the options from the Export dialog, but at least some such as:

* Enable/disable debug.
* Choose between 32/64.
* Pack mode (single exec, exec + pack, pack only).

This would allow the creation of scripts for batch export without having to modify nor rely on the `export.cfg` file.

**Comment by est31** [comment]
Debug is possible already now: there is -export and -export_debug.

**Comment by vnen** [comment]
> Debug is possible already now: there is -export and -export_debug.

This is missing from `godot -h` help then.

**Comment by bojidar-bg** [comment]
Was this fixed with the new export system?

**Comment by kosz78** [comment]
This PR https://github.com/godotengine/godot/pull/12555 add this behavior
