### ISSUE TITLE
Error when closing godot with camera preview open

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29230]
**Godot version:**
3.2.dev.custom_build.ec5be4e

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When preview in Camera(3D) is enabled, and Godot is closing, then this error occurs:
```
ERROR: _toggle_camera_preview: Condition ' !p_activate && !previewing ' is true.
   At: editor/plugins/spatial_editor_plugin.cpp:2828.
```

**Comment by KoBeWi** [comment]
Doesn't happen in 3.1.1 stable.

**Comment by akien-mga** [comment]
From #33050:

>  Bisect show that this is first bad commit [5e80177](https://github.com/godotengine/godot/commit/5e8017721a8a552c26f6ad2abe3e4b438727214b)

**Comment by akien-mga** [comment]
CC @volzhs as the bisected commit is yours, even though the relationship between it and this bug is not immediately obvious.

**Comment by pouleyKetchoupp** [comment]
From what I saw for #33050: it looks like calling `BaseButton::set_pressed()` immediately emits `toggled` signal, which causes `_toggle_camera_preview` to be called twice in some cases.

**Comment by volzhs** [comment]
I can see error messages when opening and closing a scene with 3d camera preview on.
```
 editor/plugins/spatial_editor_plugin.cpp:2822 - Condition ' p_activate && !preview ' is true.
 editor/plugins/spatial_editor_plugin.cpp:2823 - Condition ' !p_activate && !previewing ' is true.
```
but this does not close the editor.

**Comment by volzhs** [comment]
what I understood is that `set_pressed()` is used only for updating the checkbox looks before.
but after refactoring `BaseButton`, it raised `toggled` event.
