### ISSUE TITLE
is_instance_valid reads events from emulated mouse

### ISSUE THREAD

**Issue by scottluker** [godotengine/godot#29237]
**Godot version:** v3.1.1

**OS/device including version:** Windows 10, PC

**Issue description:** is_instance_valid is broken when using emulate mouse from touch as when mouse moves it makes the instance valid again. Turning off this option fixes the issue.

**Steps to reproduce:**
- Enable emulate mouse from touch
- Play the project
- Hover over game window.

**Minimal reproduction project:**
[godot-3-pong-develop.zip](https://github.com/godotengine/godot/files/3224805/godot-3-pong-develop.zip)

**Comment by KoBeWi** [comment]
Should be resolved in #36189
(although I couldn't reproduce it in 3.2.1 too)
