### ISSUE TITLE
"A Godot Engine build callback failed"

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#29232]
**Godot version:**
51d7026

**OS/device including version:**

Manjaro

**Issue description:**

Mono build fails using MSBuild with the message (mono 5.20):

```
MSBUILD : error MSB1005: Specify a property and its value.
Switch: /p:GodotDefineConstants=GODOT_X11;GODOT_64;

For switch syntax, type "MSBuild /help"
ERROR: call_build: A Godot Engine build callback failed.
```

I removed mono folders, but it's still happening.

Could be related to #28786.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by LinuxUserGD** [comment]
More related to #29210

**Comment by neikeq** [comment]
For whatever reason `ProcessStartInfo` treats `/p:GodotDefineConstants="GODOT_X11;GODOT_64;"` as `/p:GodotDefineConstants=GODOT_X11;GODOT_64;`. Amazing. It looks like `/p:GodotDefineConstants=\"GODOT_X11;GODOT_64;\"` (`\\\"` in code) works on linux. I assume this bug is not reproducible on Windows, @ShyRed can you check if such a change works on Windows as well? I don't want to break it by accident.

**Comment by neikeq** [comment]
or perhaps this is a thing with msbuild and not ProcessStartInfo ¯\_(ツ)_/¯

**Comment by ShyRed** [comment]
Just tried `/p:GodotDefineConstants=\"GODOT_WINDOWS;GODOT_64;\"` and it fails on Windows :(

**Comment by neikeq** [comment]
Did you try on the command line or in Godot like this?:

```diff
@@ -369,7 +369,7 @@ bool GodotSharpBuilds::build_project_blocking(const String &p_config, const Vect
	MonoBuildInfo build_info(GodotSharpDirs::get_project_sln_path(), p_config);

	// Add Godot defines
-	String constants = "GodotDefineConstants=\"";
+	String constants = "GodotDefineConstants=\\\"";

	for (int i = 0; i < p_godot_defines.size(); i++) {
		constants += "GODOT_" + p_godot_defines[i].to_upper().replace("-", "_").replace(" ", "_").replace(";", "_") + ";";
@@ -379,7 +379,7 @@ bool GodotSharpBuilds::build_project_blocking(const String &p_config, const Vect
	constants += "GODOT_REAL_T_IS_DOUBLE;";
#endif

-	constants += "\"";
+	constants += "\\\"";
	build_info.custom_props.push_back(constants);

	if (!GodotSharpBuilds::get_singleton()->build(build_info)) {
```

**Comment by ShyRed** [comment]
Tried in Godot.

Also Google is full of results when searching for `ProcessStartInfo` and quoting. Seems to be quite a mess and I wouldn't be surprised if the whole issue was OS dependent with Windows requiring simple quotes while Linux etc. wants escaped quotes.
Microsoft actually added a [ProcessStartInfo.ArgumentList Property](https://docs.microsoft.com/de-de/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=netstandard-2.1) which might solve the problem in an OS independent way, but it's not available for .Net Framework yet...

**Comment by neikeq** [comment]
Welp, this sucks but we can always add some ifdefs.
