### ISSUE TITLE
Scene tabs do not persist opened script state

### ISSUE THREAD

**Issue by RoboYorkie** [godotengine/godot#29245]
**Godot version:**

v3.1.stable.official

**OS/device including version:**

N/A

**Issue description:**

Script editor does not persist display state of scene tabs when moving between scene tabs. Expectation: Scene tabs should preserve state of which script is displayed.

**Steps to reproduce:**
Video: https://youtu.be/xNoNWc4YGyI

1. Create two scenes: SceneA, SceneB
2. Add child node "Subnode" to SceneB
3. Attach scripts to SceneA, SceneB, and Subnode [ SceneA.gd, SceneB.gd, Subnode.gd]
4. Click SceneB tab in editor
5. Click Subnode script icon in editor [Subnode.gd should display]
6. Click SceneA tab in editor
7. Click SceneB tab in editor

Expected: Subnode.gd displayed in editor
Actual: SceneB.gd displayed in editor

**Minimal reproduction project:**

[Godot Bug Example.zip](https://github.com/godotengine/godot/files/3227041/Godot.Bug.Example.zip)

**Comment by KoBeWi** [comment]
By default, Godot opens "dominant script" on changing scenes, which is a script attached to that scene. Does toggling it in Editor Settings help somehow? (under Text Editor -> Files)

**Comment by RoboYorkie** [comment]
Thanks for the follow-up.

Disabling "Open Dominant Script on Scene Change" did have an effect, but not quite the behavior I would expect. [Video: https://youtu.be/hxxBLNL5NBM]

I think maybe I can now restate the problem a bit better: The Godot editor has Scene tabs but doesn't have functionality for script tabs, e.g. in the same way as other editors like vim or visual studio.

**Comment by KoBeWi** [comment]
This looks like feature request, so open a [proposal](https://github.com/godotengine/godot-proposals) instead.
There are already a few proposals about scene/script tabs, so maybe it's already covered.
