### ISSUE TITLE
Make local reparenting discoverable

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#29249]
**Godot version:**
b71254a86134233949ee9ebe5855fa509f34824c

**Issue description:**
With #28392 merged, it needs to be more discoverable (as discussed in the PR).

The feature is that when you hold Shift and move nodes in scene tree dock, instead of staying in place like now, they will keep their local position. It should be indicated somewhere that it's possible.

**Steps to reproduce:**
1. Forget that this feature exists
2. Try to figure out how to use it

**Comment by akien-mga** [comment]
The same applies to many other editor options which are enabled by undocumented hotkeys, i.e. they're not triggered by an `ED_SHORTCUT` which gives a configurable in the Editor Settings, but their hotkeys are hardcoded and usually context-based.

For example freelook options (right click to start it, Ctrl, Shift, WASD, Q and E, etc.).

**Comment by KoBeWi** [comment]
Maybe we could make tracker for such features?

**Comment by akien-mga** [comment]
Good idea yes.

**Comment by KoBeWi** [comment]
I think this counts as a tracker: https://github.com/godotengine/godot-docs/issues/4377
