### ISSUE TITLE
String::simplify_path() is not exposed to scripting

### ISSUE THREAD

**Issue by NilsIrl** [godotengine/godot#29243]
**Godot version:**

6305030ee5ff7576772fb2d7bbb91db7eef455c0

**Issue description:**

There is no documentation for the `String::simplify_path()` function.
https://github.com/godotengine/godot/blob/556ee712772b992c8d734dfeb478e0ef8363aa8b/core/ustring.h#L322
https://github.com/godotengine/godot/blob/252c841d7ff5d770e8d2819e4f7955363410744b/core/ustring.cpp#L3125

**Comment by NilsIrl** [comment]
Is this intended or should I (or someone else) do a PR?

**Comment by bruvzg** [comment]
> Is this intended or should I (or someone else) do a PR?

`.xml` doc files are generated automatically form the GDScript API, if `simplify_path` is not in the documentation it is not exposed to GDScript at all and should be registered in `core/variant_call.cpp` first.

**Comment by NilsIrl** [comment]
> `.xml` doc files are generated automatically form the GDScript API, if `simplify_path` is not in the documentation it is not exposed to GDScript at all and should be registered in `core/variant_call.cpp` first.

Where is the GDScript API defined?

**Comment by akien-mga** [comment]
In `core/variant_call.cpp`, as mentioned :)

**Comment by NilsIrl** [comment]
Ok closing
