### ISSUE TITLE
Exported projects are quite large

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#29241]
**Godot version:** 3.0.6, 3.1

Exported Godot projects are quite large; a GDscript project is around 30MB. A Godot/C# project is around 42MB. A GDscript Android project is around 33MB; I imagine when Android/C# is a thing, the binaries will be larger.

These project sizes are quite large. Is there any way to shrink them at all?

For Windows, I tend to zip the `.exe` and `pck` file, which usually compress well.

**Comment by KoBeWi** [comment]
You can shrink the export size, by compiling your own export templates optimized for size: https://docs.godotengine.org/en/latest/development/compiling/optimizing_for_size.html

For Android, the new template builder probably helps.

**Comment by Zylann** [comment]
Are APKs compressed on Android?
This size comes down to the engine itself and all the features it has.

**Comment by Garrom** [comment]
Compared to Unity I'd say that exported projects are rather small

**Comment by nightblade9** [comment]
> You can shrink the export size, by compiling your own export templates optimized for size: https://docs.godotengine.org/en/latest/development/compiling/optimizing_for_size.html
> 
> For Android, the new template builder probably helps.

Very useful, thanks for sharing the link. Can you post a link for the new template builder? This is the first I've heard of it.

**Comment by Calinou** [comment]
@Zylann APKs are just ZIP archives, so they're compressed.

**Comment by freemanfromgodotengine** [comment]
In previous versions of Godot, or at least with version 1.0 it was possible to compile the engine without some "components", like 3D part of the engine, gamepad support (ex. gamepad=no option), or some audio or gfx formats. 
By eliminating things I did not need, I remember I was able to get as low as 7.8 Mb taken by the engine in 2D android app.

Is it possible to build stripped version of the engine with Godot 3.1 and up?

**Comment by Calinou** [comment]
@freemanfromgodotengine This is still possible, as described in [Optimizing for size](https://docs.godotengine.org/en/latest/development/compiling/optimizing_for_size.html) in the documentation :slightly_smiling_face:

**Comment by nightblade9** [comment]
It sounds like this is a known problem with a known solution that is well-documented. Since that's the case, I'm going to go ahead and close this. If anyone has any serious issues with this, please let me know and I can re-open it.

Thanks for the good discussion, I learned a lot.

**Comment by jahd2602** [comment]
I had a project that was around 120 mb when exported for android.

I enabled the setting to import all the images with *Lossy* compression. The quality of the images in the game wasn't reduced at all.

When compiled for Android, the app was 25 mb.
