### ISSUE TITLE
Wrong operator used in Vector3::operator<=

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#2924]
in operator <=:
<= instead of <

```
bool Vector3::operator<(const Vector3& p_v) const {

	if (x==p_v.x) {
		if (y==p_v.y)
			return z<p_v.z;
		else
			return y<p_v.y;
	} else
		return x<p_v.x;

}

bool Vector3::operator<=(const Vector3& p_v) const {

	if (x==p_v.x) {
		if (y==p_v.y)
			return z<=p_v.z;
		else
``` 		
return y**<**p_v.y;
```
	} else
```
return x**<**p_v.x;
```

}
```

**Comment by akien-mga** [comment]
Nice catch.

**Comment by akien-mga** [comment]
Feel free to make a pull request to fix it (also check the >= operator to be sure).

**Comment by CharlesWoodhill** [comment]
stumbled over it when making my intvector3 :)
sorry cant pull and push atm, have too much changed in enginefiles including vector3.h (conversion support),
if not done later, i will do,
but only if IntVector3 becomes coretype :)

**Comment by akien-mga** [comment]
I'll handle it then. I've had a quick look and it looks like the logic in min_axis and max_axis is broken too :)

**Comment by CharlesWoodhill** [comment]
whoever understands that line... :)
return x < y ? (x < z ? 0 : 2) : (y < z ? 1 : 2);

**Comment by akien-mga** [comment]
Well actually I had a closer look and the min_axis and max_axis seem right. The syntax is not easy to read yeah, but it's not much worse than if everything was written with ifs and elses :D

**Comment by akien-mga** [comment]
Actually I checked again and there is no bug: the case of equality is already taken care of in the ifs, so the elses only need to do a strict comparison.

```Vector3(1,2,3) <= Vector3(1,2,3)``` does return true properly, no bug.
