### ISSUE TITLE
Visible collision shapes: Incorrect display.

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#2925]
If the software to re-create "sheyps" on the screen in debug mode will not be shown correctly (old version)

an example can be seen that the bullet had to face the asteroids but it does not happen because the size of the figure is less than he had seen on the screen
![godot 2015-11-27 13-16-48-78](https://cloud.githubusercontent.com/assets/233268/11440872/51dda34e-9517-11e5-8bf1-c23113b5b7ab.jpg)

**Comment by bojidar-bg** [comment]
Is there any chance that you are *scaling* collision shapes? They should generally be left with 1,1,1 scale IMO...

**Comment by ret80** [comment]
I do not scaling shapes. I re-create them. Here is an example:

<code>
func config(info):

       var s = get_rand_val(cfg, "scale", 1.0)
       clear_shapes()
       var shape = CircleShape2D.new()
       shape.set_radius(cfg.radius*s)
       add_shape(shape)
</code>

**Comment by reduz** [comment]
ah yeah that won't work, the debug information is provided by the
CollisionShape node

**Comment by reduz** [comment]
this will only be fixed in 3.0, when collision is actually moved to the nodes

**Comment by ret80** [comment]
then you need to either closed or change the issue status to feature

**Comment by reduz** [comment]
this should now work, as the collision is finally in the node
