### ISSUE TITLE
KinematicBody does not collide properly with RigidBody

### ISSUE THREAD

**Issue by io12** [godotengine/godot#29256]
**Godot version:**
3.1.1.stable.official

**Issue description:**

Whenever I make a `KinematicBody` press a `RigidBody` against a `StaticBody` (`PhysicsBody` sandwich) using `move_and_slide()`, the `RigidBody` jitters. Sometimes, it clips through the `StaticBody`. Looking through the documentation for `move_and_slide()`, it has an `infinite_inertia` option, which needs to be enabled to move `RigidBody` nodes. I couldn't find any option to move a `KinematicBody` with *some* inertia, such that there is resistance when pushing a `RigidBody`. I think this is the cause of the jitter and wall clipping.

**Steps to reproduce:**
Place a `StaticBody` to use as the ground. Put a `RigidBody` above it. Finally, place a `KinematicBody` on top. Push the `KinematicBody` down into the `RigidBody` with `move_and_slide()`. The `RigidBody` will jitter and potentially clip through the ground.

**Minimal reproduction project:**

[godot-kinematic-bug.zip](https://github.com/godotengine/godot/files/3229209/godot-kinematic-bug.zip)

**Comment by KoBeWi** [comment]
AFAIK, that's how it's supposed to work. My workaround was attaching a StaticBody2D inside the RigidBody2D, to prevent too much clipping, although that's rather awkward (and didn't work perfectly too).

**Comment by eon-s** [comment]
Yes, this is how it is supposed to work, the infinite inertia parameter is there to get the other behavior where a body is unable to push, the user must control what behavior wants.

**Comment by io12** [comment]
I realize that infinite inertia implies that `KinematicBody` can move without being impeded by `RigidBody`, but it would be useful for `KinematicBody` to be able to interact with `RigidBody` without having infinite inertia. Many people use `KinematicBody` as a player hitbox, and this would cause issues if the player jumps on a `RigidBody`.

I'm unsure if there's a way to accomplish this.

**Comment by eon-s** [comment]
For hit detection is better to use Area nodes, that and making the use of the multiple layers and masks.
If the player jumps on a rigid, the player is able to "ask" the rigid if it can be pushed before moving more.

**Comment by io12** [comment]
That works for simple cases, but is it reliable with (rotational movement / slopes) for example?

What I'm looking to implement is a 3D environment where the player can move around and interact with (push, jump on) `RigidBody` nodes without clipping issues or jittering.

**Comment by eon-s** [comment]
As realiable as you manage to make it, check better if your interactive objects will be really rigid or kinematics with special physics, also if the player character is kinematic or rigid with a custom integrator.

**Comment by io12** [comment]
Probably I should make my player a `RigidBody` then. I'll close this issue since it seems that realistic collisions are outside the scope of `KinematicBody` and better suited to `RigidBody`.
