### ISSUE TITLE
Android device is not listed

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#29258]
**Godot version:**

3.2.dev 80f7a1956

**OS/device including version:**

Kubuntu 19.04

**Issue description:**

Android device is reconized but not display in list.
when click Android icon, it shows an empty box, so can't run on device.

**Steps to reproduce:**
![android_1](https://user-images.githubusercontent.com/8281454/58508664-81f45e80-81cf-11e9-9238-13cca52785a5.png)
![android_2](https://user-images.githubusercontent.com/8281454/58508665-81f45e80-81cf-11e9-81b9-d37a33db0395.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
It shouldn't display a dropdown when you click it when there's only one device connected, so there's something wrong there.

Just to make sure, what's the output of `adb devices` on your system?

**Comment by volzhs** [comment]
```
$ adb devices
List of devices attached
ce0617163d50b61a01      device

$ adb install game.apk
Success
```
nothing wrong with `adb`

**Comment by volzhs** [comment]
I think I found the problem. will make a PR.
