### ISSUE TITLE
Can't undo conversion to CPUParticles

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#29250]
**Godot version:**
3.1.1

**Issue description:**
Particles and Particles2D have an option to convert to CPU particles. However, you can't undo this action and the only way to go back is to revert scene.

**Hint for junior contributors:**
#28349 introduced changes to editor's `replace_node()` that make this easy to fix. Just see how `_convert_to_mesh_2d_node()` got undo support in that PR and do similar thing for particles.

**Comment by hbina** [comment]
I would like to work on this.

It seems like I have 4 options where to implement this:

1. As a helper function in cpu_particles_2d_editor_plugin.cpp
2. As a helper function in particles_2d_editor_plugin.cpp
3. As a member function in particles_2d.cpp 
4. As a member function in cpu_particles_2d.cpp

Which one is most suitable?

**Comment by KoBeWi** [comment]
You don't need to create any new function. Just add `UndoRedo` calls to the existing one.
