### ISSUE TITLE
Game FPS drops when manipulating editor camera

### ISSUE THREAD

**Issue by SeleckyErik** [godotengine/godot#29260]
**Godot version:**
Godot master, commit bbb1af91

**OS/device including version:**
OS: Windows 10
GPU: NVIDIA GeForce GTX 960M
GPU Driver version: 430.86

**Issue description:**
When launching game from the editor, the game FPS drops drastically when editor viewport camera is manipulated while the game is running.

**Steps to reproduce:**
1. Add a label that gets updated with the current FPS (e.g. `Engine.get_frames_per_second()` function. Don't use `print(...)` in `_process(delta)`, because that also prints to stdout in case you have a console running which alone makes FPS drop drastically if printing each frame and makes the effects less visible.
2. Disable VSync
3. Launch the game
4. In editor, go to either 2D or 3D viewport and start moving the camera
5. Watch the FPS plummet

**Minimal reproduction project:**
[CameraTest.zip](https://github.com/godotengine/godot/files/3229757/CameraTest.zip)

**Comment by Calinou** [comment]
This is kind of expected, as the editor and running game will "compete" in re-rendering their respective viewports.

**Comment by SeleckyErik** [comment]
Yes, it is indeed expected. I just thoought that the FPS drop is rather extreme. As an example, on my machine this causes a completely empty scene with just a label in it to drop from 500 FPS to 100 FPS. Maybe the complexity of a scene in this case doesn't play a role and the main reason of the FPS drop is all the OpenGL state changes that have to take place to serve both applications running? I wasn't sure, that's why I opened this issue after all.
