### ISSUE TITLE
Add an option to open scenes fully folded or unfolded by default

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#29264]
**Godot version:** 3.2 252c841

**Issue description:** I cleaned my project's config data and now all scenes are fully unfolded because the folding state is no longer saved in the .tscn itself. This would also happen when opening a project downloaded from somewhere as you're not receiving the folding state. I know it's possible to fold all nodes with Alt+left/right, but...

**Suggestion:** It would be pretty convenient if there were an editor setting for opening scenes fully expanded or collapsed when no prior folding state is known.

**Comment by Xrayez** [comment]
> I know it's possible to fold all nodes with Alt+left/right, but...

Oh I didn't know about this, but seems like it doesn't work recursively... I made a PR at #19936 which works recursively by doing Shift+RMB to fold/unfold nodes. 🤔

In any case, I confirm that it's quite an issue for me, having nodes to be fully folded by default would make nodes easier to navigate. 

I'm also having an issue that breaks saved folding whenever scenes are being instanced apparently, see #29975.

**Comment by KoBeWi** [comment]
As noted above, you can Shift+Click to fold everything at once.
If that's not sufficient, open a [proposal](https://github.com/godotengine/godot-proposals) instead.
