### ISSUE TITLE
Godot fails to load valid GLTF glb file

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#29265]
Godot 3.1.1 currently fails to load a .vrm file from the vrm format (https://vrm.dev/en/) VRM format files are valid glb files but with extra data, however all other software i've tried to load the file with simply ignores the extra data, godot however just crashes, this shouldn't happen.

Attached is a test file so the bug can be reproduced.

I am not sure if thsi bug is the same as #28764 , so it would be nice if someone could verify this is the case.

Log:

```
C:\Users\EIREXE\AppData\Local\Godot
λ  .\Godot_v3.1.1-stable_win64.exe
OpenGL ES 3.0 Renderer: Radeon RX 580 Series
Editing project: C:/Users/EIREXE/Documents/FontBugTest (C:::Users::EIREXE::Documents::FontBugTest)
C:\Users\EIREXE\AppData\Local\Godot
λ  OpenGL ES 3.0 Renderer: Radeon RX 580 Series
ERROR: set_name: Condition ' name == "" ' is true.
   At: scene/main/node.cpp:930
ERROR: get: FATAL: Index p_index=-1 out of size (size()=161)
   At: ./core/cowdata.h:151
```

[star.zip](https://github.com/godotengine/godot/files/3230174/star.zip)

**Comment by fire** [comment]
I have a Godot branch that imports this correctly (Although set -90 on the x axis).

![godot windows tools 64_fURMy9oXM6](https://user-images.githubusercontent.com/32321/58531373-e941ec80-8196-11e9-9f77-2c4c8448277b.png)

**Comment by fire** [comment]
Here's the corrected material settings.

![godot windows tools 64_G9rXI505QC](https://user-images.githubusercontent.com/32321/58533145-894e4480-819c-11e9-9b38-0365a62b1970.png)

**Comment by fire** [comment]
See https://github.com/godotengine/godot/pull/29273

**Comment by EIREXE** [comment]
@fire that's great, the model should be SFW btw, it's simply part of the vroid studio application, which is SFW

**Comment by marstaik** [comment]
I believe this has been by #32213

Sorry, I had fun with a bunch of the morph targets:
![star](https://user-images.githubusercontent.com/5601015/65482221-28363500-de4d-11e9-8a40-3de166c7b765.png)
