### ISSUE TITLE
Instancing breaks when exporting with debug off

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#29274]
**Godot version:**

v3.1 stable

**OS/device including version:**

Windows 7

**Issue description:**

I am scared as hell guys. This is the build with debug on
![rec](https://user-images.githubusercontent.com/47214394/58536344-e33b2280-820d-11e9-9683-a2ed801477a1.gif)

It plays the same in editor

This is the build with debug off
![rec](https://user-images.githubusercontent.com/47214394/58536424-1f6e8300-820e-11e9-80f7-61912b9f20dc.gif)

The instancing of my corridor scene breaks. I haven't changed a single thing in the project. I am literally scared by this, it seems as if my week of development is in danger.

Here is the project:
[Dungeon.zip](https://github.com/godotengine/godot/files/3231143/Dungeon.zip)

(please don't use it elsewhere)

The release build(windows)
[Release_build.zip](https://github.com/godotengine/godot/files/3231156/Release_build.zip)

Linux release build[I dont have Linux please check this one]:
[linuxBuild.zip](https://github.com/godotengine/godot/files/3231165/linuxBuild.zip)

**Steps to reproduce:**
Can't say.First time encounter

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
There are many errors in the debugger when you run the project in the editor. Errors in debug mode can usually mean crash or broken behaviour in release mode (release mode is optimized for performance, so it doesn't do everything it can to make sure things don't crash).

**Comment by akien-mga** [comment]
All errors are here:
```
func spawn():
...
		for y in range(iterator):
			c=corScene.instance()
                        # global_position does not make sense if the node is not in the scene tree,
                        # as "global" is relevant to the scene root.
			c.global_position.y=corPos-y*tileSize*3
			c.global_position.x=curRoom.get_node("pos/enter").global_position.x
			$Corridors.add_child(c)
```

Just call `add_child` before setting `global_position` and it should work.

**Comment by nikhilCad** [comment]
Thank you! It is fixed. I didnt expected such a quiick reply. So I should change values after adding the instance. Lesson learnt.

**Comment by nikhilCad** [comment]
Thank you! Fixed. I didnt expected a reply this quick
