### ISSUE TITLE
BBCode [center] tag doesn't center over multiple lines

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#29278]
**Godot version:**

3.1.1

**Issue description:**

```
[center]Text text text text text text text text text text text text text text text text text text text[/center]
```

![image](https://user-images.githubusercontent.com/28724859/58544647-50779500-81c7-11e9-9485-30521977ed9a.png)

Expected the 2nd line to be centered

**Comment by KoBeWi** [comment]
Looks like duplicate of #6982
