### ISSUE TITLE
Gradient/Color of CPUParticles not working

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#29276]
**Godot version:**
3.1.1 stable

**OS/device including version:**
Windows 10 / Android

**Issue description:**
I am using GLES 2 and so I have to use CPUParticles.

I tried to make a simple particle effect where the particles change their color over time.
I tried setting the color and the color gradient in the properties, but it doesn't have any effect.

My particle effect still looks like this:
![particleEffect](https://user-images.githubusercontent.com/25849067/58543591-07900280-8200-11e9-8797-d34410466138.PNG)

**Steps to reproduce:**
- Create a CPUParticle-Node
- Assign a mesh, e.g. a MeshInstance Quad
- Set the color / color ramp property

**Minimal reproduction project:**

[CpuParticleGradient.zip](https://github.com/godotengine/godot/files/3231576/CpuParticleGradient.zip)

**Comment by mrcdk** [comment]
You need to enable `Vertex Color/Use as Albedo` in your model's material.

**Comment by Tobi-La** [comment]
Ah I didn't know this, thanks!
