### ISSUE TITLE
Inspector contents goes over its size

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#29289]
**Godot version:**

3.2.dev 62c9af407

**OS/device including version:**

Kubuntu 19.04

**Issue description:**

Inspector contents goes over its panel size.
and resize panel won't help to fit in again.

**Steps to reproduce:**
1. make Inspector and Scene dock side by side
2. select node

**Minimal reproduction project:**

![inspector](https://user-images.githubusercontent.com/8281454/58576139-8a57a280-827e-11e9-93be-f15cb9cef760.gif)

**Comment by akien-mga** [comment]
Is this also a regression from #28952?
