### ISSUE TITLE
Feature Request: "close all scenes" and "close other scenes" options in editor

### ISSUE THREAD

**Issue by CngKO** [godotengine/godot#29282]
This is a feature request...

Can we have "close all scenes" and "close other scenes" options in the context menu of Godot Engine's scene editor?  

It would make life easier when working with many scenes.

Currently, there is only an X (close) button and a "Close Tab" menu item in the context menu which closes only the scene that was clicked on.

**Comment by KoBeWi** [comment]
This is already a thing in 3.2-dev version. You can get a nightly build to try it out.
