### ISSUE TITLE
Popup visible not set in mono

### ISSUE THREAD

**Issue by TheBlue-1** [godotengine/godot#29281]
**Godot version:** 3.1.1 Mono (using C#)

**OS/device including version:** Windowsn10 Edu

**Issue description:**
When I call PopupCentered in the Script of my Popup it pops up, but IsVisible returns false.
If I call Show, IsVisible stays false.

I expect it to be true because I can see it.  

**Steps to reproduce:**

- Call PopupCentered or Show in a Popups script
- Call IsVisible on the same script

**Comment by KoBeWi** [comment]
Reproduction project? Works fine for me.

**Comment by TheBlue-1** [comment]
[project.zip](https://github.com/godotengine/godot/files/3234494/project.zip)

You can find the popup by clicking on the start button and then [esc]
The Code is in  Scripts/Popup.cs

(My Popup gets Closed by pressing escape without my code if i tab out before pressing it, maybe that's an other issue, so i debugged with GD.Print)

**Comment by TheBlue-1** [comment]
Everything is working just fine. I just didnt know that a popup gets closed by pressing [esc]
