### ISSUE TITLE
Can see Remote and Local scene tree at the same time

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#29288]
**Godot version:**

3.2.dev 62c9af407

**OS/device including version:**

Kubuntu 19.04

**Issue description:**

I can see Remote and Local scene tree at the same time.
I guess it's not desired.

**Steps to reproduce:**
1. run project
2. click Remote tab
3. make a new scene
4. back to previous scene

**Minimal reproduction project:**

![remote_local](https://user-images.githubusercontent.com/8281454/58575484-1ff23280-827d-11e9-9834-713464dafd5c.gif)

**Comment by XR4Y-TEDDY** [comment]
Guys, I don't know why but for the "remote" and "local" tabs aren't showing up at all. I have an auto load script set up on Node2D, but I can't get anything to work while trying to reference a global variable.

public class GameManager : Node2D     // [ Global Variable ]
{
 	public int currentDir = 1;
)
---------------------------------------------------------------------------------------
public class Player : KinematicBody2D    // [ Player Node ] 
{
	var gameManager = GetNode<GameManager>("/root/GameManager");
	gameManager.currentDir = 1; 
}
---------------------------------------------------------------------------------------
There's more code for the player but it's not relevant
I also get this error message for trying to use the global variable -

Invalid token '=' in class, record, struct, or interface member declaration

![game error](https://user-images.githubusercontent.com/32947815/155862310-a322116a-69bb-4b6f-91f5-e7ce9a5be69f.PNG)

**Comment by Calinou** [comment]
> [](https://github.com/godotengine/godot/issues/29288#issuecomment-1052795839)Guys, I don't know why but for the "remote" and "local" tabs aren't showing up at all.

The Remote and Local tabs only display while the project is running, after the editor debugger was started and successfully connected to the debuggee (i.e. the running project).
