### ISSUE TITLE
Animation class missing track_set_key_time() method

### ISSUE THREAD

**Issue by regakakobigman** [godotengine/godot#29295]
**Godot version:** 

3.1.1

**OS/device including version:** 

Windows 8.1 64-bit

**Issue description:**

The Animation class has a track_get_key_time method, but not a track_set_key_time method. Without this method, moving keys in place through code is impossible and requires deleting and recreating the entire animation, which is both inflexible and inefficient. Moving keys is still possible through the editor interface.

Other issues exist about track_set_key_time (#20858, #28482), but they're marked as discussions or feature requests when this appears to be a bug. #28482 shows that there is no setter function at all in animation.cpp. https://github.com/godotengine/godot/blob/c11bf884e0a127fb714a575f40fdc0b73fe54f2d/scene/resources/animation.cpp#L1248

### Because the key time can be set in the editor, but not through code, this appears to be an oversight.

**Steps to reproduce:**

1. Create an AnimationPlayer
2. Create an Animation in the AnimationPlayer
3. Add keys
4. The keys can be set in the editor, but not through code

**Comment by avencherus** [comment]
If I recall correctly, the keys in a track are sorted by time, so changing a key's time might mean rebuilding the entire list (track) again anyway, depending on the approach.

If the key's time becomes greater than the any ahead of it or less than any behind it, the key needs to be deleted and reinserted into the proper index position to maintain the time ordering.  There are a variety of ways of doing it, but key counts in tracks are low, so I can't imagining choosing an algorithm to re-insert or re-sort would ever be a performance concern.

I at least do this extra work in GDScript when it comes to this for tool code, so I definitely agree it would be nice to have a method exposed in API that does this.  It does feel like a missing function.
