### ISSUE TITLE
Skeleton pose values not saved or read by editor

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#29292]
**Godot version:**
a4b250d

**Issue description:**
I have an escn that contains a skeleton, no animation, no animation player node, but the skeleton has set pose transforms. However when I open it in Godot, the skeleton appears to be in its rest position. I check the pose transforms in the inspector and they are all identitied, they do not equal the values set in the serialized escn.

I tried changing the pose values in the editor and saving it as a tscn.
The pose values reset again, this time the identitied pose transforms were serialized into the tscn.
I then tried altering the pose transforms in the editor again and saving.
Now the serialized tscn has no pose values, each bone's pose property has been deleted from the tscn.

I don't understand this behaviour, if there's not an animation player targeting a skeleton, the editor should serialize and write the pose transforms to file.

**Steps to reproduce:**
Import test.escn into a project and perform all the steps I mentioned above:
[test.zip](https://github.com/godotengine/godot/files/3233742/test.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.

Please comment if you can still reproduce it, and this issue can be reopened. Or open a new issue with a MRP if this would be better suited.
