### ISSUE TITLE
Label text disappearing inside a viewport node

### ISSUE THREAD

**Issue by soloparatolos** [godotengine/godot#2929]
When Label autowrap is enabled, the label text dissapears inside the Viewport.

Can be easily tested with  the "GUI in 3D" demo. 

![captura de pantalla de 2015-11-27 08-57-28](https://cloud.githubusercontent.com/assets/11409821/11448376/39d42274-9557-11e5-9226-4a225d5068b7.png)
![captura de pantalla de 2015-11-27 08-58-23](https://cloud.githubusercontent.com/assets/11409821/11448378/426421e6-9557-11e5-8c2f-e1c872808849.png)

**Comment by akien-mga** [comment]
Nice catch, it happens with the "clip text" option too.

**Comment by soloparatolos** [comment]
Issue fixed with this commit https://github.com/godotengine/godot/pull/2719
