### ISSUE TITLE
Can't send 2d array over network

### ISSUE THREAD

**Issue by Derzo** [godotengine/godot#29293]
**Godot version:**

3.1

**OS/device including version:**

Windows 10 64-Bit

**Issue description:**

When sending a 2d array with an rpc call, the receiving function seems to interpret it as a 1d 
array.

**Example Code:**
```
func _ready():
	var networkArray = [ [1,2], [3,4], [5,6] ]
	rpc("doSomething", networkArray)

remote func doSomething(networkArray):
	var localArray = [ [1,2], [3,4], [5,6] ]
	print(localArray[2][0]) #prints 5
	print(networkArray[2][0]) #prints "Invalid get index '[]' (on base: 'Array')"
```

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by Faless** [comment]
@derderder77 I'm unable to reproduce, and the error seems like what you get if you do: `networkArray[[]]`.
Are you sure that is the exact code that gives you that error? Can you provide a minimum reproduction project?

**Comment by Derzo** [comment]
It seems that it was some bug on my side, now that I implemented it again it works
