### ISSUE TITLE
Not working android build because of .fscache bug related to game assets update

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#293]
Hey there..
If I add new resources to my project and then try to export the project to my android device the game does not start. Logcat shows that the newely added resources are not found.
Checking the .fscache file showed me, that the new resources were not added. Fix for that is deleting the .fscache and then restarting the project which creates a new .fscache.
This seems to be a write permission issue?

**Comment by kubecz3k** [comment]
I believe it's fixed by now, if not please let me know I will reopen.
