### ISSUE TITLE
I would like to develop Kotlin language export templates plugin for Android

### ISSUE THREAD

**Issue by JunShiozawa** [godotengine/godot#29302]
I would like to develop Kotlin language export templates plugin for Android.

https://godotengine.org/article/godot-3-2-will-get-new-android-plugin-system

This plugin system bring only Java language.

However Google said "Android development will become increasingly Kotlin-first".

https://techcrunch.com/2019/05/07/kotlin-is-now-googles-preferred-language-for-android-app-development/

Could you let me develop an export templates plugin for Godot for Android in Kotlin language?

**Comment by FeralBytes** [comment]
@JunShiozawa Please do! You just need to make a PR once you have your code complete and tested.

**Comment by m4gr3d** [comment]
Using kotlin for development is already supported.

**Comment by FeralBytes** [comment]
@m4gr3d Yes it is, I have been doing this for months. Thank you for all of your work on the Android build system for Godot.
