### ISSUE TITLE
Select/Copy/Paste Tilemap area reverts tiles to the first index of an atlas

### ISSUE THREAD

**Issue by tfcat** [godotengine/godot#29307]
**Godot version:** 3.1.1
**OS/device including version:** Windows 10 LTSB
**Issue description:**
On selecting a range of tiles and copying, the paste (and preview) contains the first subimage of an atlas rather than the specific tile it actually copied.

*Similar* past issues: 
[#22756](https://github.com/godotengine/godot/issues/22756)
[#24440](https://github.com/godotengine/godot/issues/24440)

[**Video demonstrating issue**](https://cdn.niu.moe/media_attachments/files/005/321/709/original/3810af974db02417.mp4)

**To recreate the issue:**
- Create a textured TileMap
- Create a new Atlas containing a range of those tiles
- Draw a Tilemap in a scene using a variety of tiles in the atlas
- Control+B -> Select an area of tiles
- Control+C -> Copy that area of tiles

You'll then likely see an incorrect preview, and pastes will be incorrect, replacing all copied tiles with the first tile in an atlas. Similar issues were reported as fixed in 2018. Let me know if it's me doing something wrong, cheers!

**Comment by SolarLune** [comment]
I think I might be also seeing the same kinds of issues with atlas tiles, #29444 and #29445.
