### ISSUE TITLE
Adding and moving a label can set its position and size to infinity and corrupt a scene.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#29305]
**Godot version:**

8c923fc

**OS/device including version:**

Win10 64bit

**Issue description:**

I was adding a label without a container to label a bug report scene, and when holding ALT to move the label everything vanished.  

The rect position and size of the label became infinities, and the viewport also stopped working.  I tried recentering on other nodes, but it wouldn't return anything to view.

If the scene is saved afterwards, it won't re-open, because it fails to parse.

This video shows the process and results: https://streamable.com/fcl5t

This is a look at the scene file data regarding the label.

![sublime_text_2019-05-30_09-45-18](https://user-images.githubusercontent.com/13004169/58620369-961f8500-82cf-11e9-92f9-dd7ca153cfe4.png)

**Steps to reproduce:**
1. Add a Label to a new scene.
2. Use ALT and drag to move it.  It may need to be done twice and deselected and selected in the tree.
3. Observe the rectangle position and size properties.
4. Save and close the scene.
5. Try re-opening the scene.

**Comment by groud** [comment]
Sorry, I cannot reproduce the bug. This might be a windows only bug, but I could not explain why (maybe an wrong mouse event sent ?).

**Comment by avencherus** [comment]
I'll take a glance at a Linux build first chance I get tomorrow.

**Comment by avencherus** [comment]
@groud Just reproduced it in Ubuntu 19.04, shouldn't be OS related.  In a new scene, I made a new label, and used ALT drag to try to move it, and again, everything is trapped and the values for the rect and anchor went to nan and infinity.

![Screenshot from 2019-05-31 06-43-01](https://user-images.githubusercontent.com/13004169/58680194-5d36ed00-836f-11e9-9053-b98b48457ac4.png)

**Comment by bojidar-bg** [comment]
Can confirm, it happens when moving the anchors, either via the anchor lock or via the anchor handles, if the parent is a Node2D. Does not happen if the player is a plain Node or a Sprite with a texture.

**Comment by avencherus** [comment]
@groud I think it was when this was introduced:  79cc95c6a78bf4949cfb2

It happens when clicking on the green anchor.  I'm not clear yet on what it is supposed to do, or if there was a way to invoke it prior.  In the current situation the legs of it start disappearing on click and adding some inf/nan values to the control properties.

![Screenshot from 2019-06-01 14-49-52](https://user-images.githubusercontent.com/13004169/58748139-ea1b9c80-847c-11e9-9ccd-d94752839dd2.png)

After looking at it again, the issue with the viewport is that I may of recentered on the label while it was at infinities, and that is what seems to trap it.
