### ISSUE TITLE
Rigid bodies using inertia become unstable.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#29303]
**Godot version:**

8c923fc

**OS/device including version:**

Win10 64-bit

**Issue description:**

Decided to revisit these to see if they're usable, and when trying to change the inertia in script, I got rather bad results.  This video shows some pairs of shapes, with and without custom inertia.  

The one of the left is without, and is the expected result, the copy on the right is with some inertia set.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13004169/58613458-73d13b80-82be-11e9-8af3-0dbe23ffaafe.gif)

**Steps to reproduce:**
Make some RigidBody2Ds, and in script set their inertia property.  Values closer to 1 seem to be the most unstable.

**Minimal reproduction project:**

[RigidBody Bug.zip](https://github.com/godotengine/godot/files/3235733/RigidBody.Bug.zip)

**Comment by OBKF** [comment]
This is looking weirdly similar to this #25468 issue when applying torque to a RigidBody

**Comment by KoBeWi** [comment]
Still valid in a3110e838 xd
![oYKliIC2o0](https://user-images.githubusercontent.com/2223172/89354325-d12dfd00-d6b8-11ea-9729-e06185c5125d.gif)

**Comment by avencherus** [comment]
Some how your result looks worse...  🤔

**Comment by avencherus** [comment]
@pouleyKetchoupp
