### ISSUE TITLE
Make the script editor's syntax error message selectable or copiable

### ISSUE THREAD

**Issue by KurtBliss** [godotengine/godot#29321]
**Godot version:**
Godot Engine v3.1.1.stable.official 

**Issue description:**
Can't copy and paste syntax error message have to copy it manually.  

![image](https://user-images.githubusercontent.com/7538857/58648960-ee0eb980-82d8-11e9-86c2-55407d4c94e7.png)

I do like how clicking it brings you directly to the syntax error... Maybe not make it selectable but add a right click context menu option with copy, search google, or search documentation. 

**Steps to reproduce:**
`func get_path(start, end):
	pass`

**Comment by mindinsomnia** [comment]
Brilliant idea!

**Comment by dankan1890** [comment]
For now, a simple workaround is to save the script with the error and copy it from the console (or from the output in version 3.2.dev).
However, with a contextmenu it would certainly be easier.

**Comment by Calinou** [comment]
Label can't be made selectable, only RichTextLabel can. We could switch to RichTextLabel to allow using the code font dynamically (only using it to reference variables), but this requires a full rework of the GDScript error reporting system.

**Comment by KurtBliss** [comment]
Not sure where or when this happened but looks like it's been added with the errors button

![image](https://github.com/godotengine/godot/assets/7538857/930a0c06-1703-420b-8f3f-53bb5c3ac3ac)

**Comment by akien-mga** [comment]
Seems like this was added in 4.1.
