### ISSUE TITLE
Mesh.get_faces() method crashes on android

### ISSUE THREAD

**Issue by Toshiwoz** [godotengine/godot#29330]
I'm not seeing something similar, will look around for related issues, as it may be others have experienced the same issue but not nailed down to the exact problem.

**Godot version:**
Official 3.1.1

**OS/device including version:**
Huawei MYA-L11
Should have:
CPU: ARM Cortex-A53, 1400 MHz
GPU: : ARM Mali-T720 MP2, 600 MHz

**Issue description:**
I have experienced crashes on my Android GLES2.0 3D project. It works fine in Windows 10.
the issue occours when you want to get vertices of the ArrayMesh in order to generate programmatically a collision shape.

**Steps to reproduce:**
You can create a simple project with a MeshInstance and arraymesh as it's mesh, doesn't matter if it's empty.
Then use the following code.

```
func _ready():
	var fcs = self.mesh.get_faces() #this one crashes on android
	print(fcs)
```
It will crash on an android export.

**Minimal reproduction project:**
[Get_Faces gles2.0.zip](https://github.com/godotengine/godot/files/3238921/Get_Faces.gles2.0.zip)
I have added an apk, just in case.. but you may want to configure your own in order to place a breakpoint right before the get_faces() method.

**Comment by Toshiwoz** [comment]
Please don't bully me because I have a Huawei...

**Comment by clayjohn** [comment]
Have you tried this with GLES3 as well?

**Comment by Toshiwoz** [comment]
> 
> 
> Have you tried this with GLES3 as well?

Nope, at least not on mobile, for performance reasons, too slow on my 2 mobile devices.
Neither on OSX as I do not have a macOS to compile for it.

My guess is that it works, may try later for the sake of solving the issue.

**Comment by clayjohn** [comment]
It would help narrow down the problem as I dont have an android build system set up right now.

**Comment by Toshiwoz** [comment]
> 
> 
> It would help narrow down the problem as I dont have an android build system set up right now.

That's definitely a problem.

Anyhow, I tried and on my device it crashes right after splash screen:
 platform/windows/os_windows.cpp:2532 - Condition ' !process_map->has(p_pid) ' is true. returned: FAILED

But it seems to be my device not working with gles3.0 (even if it states it's compatible), I re created an empty project, added a meshinstance node and a camera, and it crashes, no scripts at all.
I am trying right now with just a node2d this time.

**Comment by Toshiwoz** [comment]
Weird,
I tried with node2d as root, without any other node, it worked, then I changed the root node again to spatial, ad worked.
I added again a mesh and a camera, and it worked again.

**Comment by Toshiwoz** [comment]
Now that I had the GLES3.0 version working I added again the script, and it crashed again.
So I guess I should change the title.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/34794
