### ISSUE TITLE
Cannot use `class_name` before `extends`

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#29345]
**Godot version:**
c07b49280aee24b07e0da7fd42dee4cba187cf13, "regression" from #27987

Related issues: #24364.

**OS/device including version:**
Windows 10

**Issue description:**
Impossible to write `class_name` before `extends`
```
SCRIPT ERROR: GDScript::reload: Parse Error: 'extends' must be used before anything else.
```

**Steps to reproduce:**
Write this kind of script:
```gdscript
class_name Foo
extends Node
```
---

If this is the wrong way from now on, then close the issue, but I feel like some people would find it more logical to write `class_name` before `extends`, ~~it even used to work as one-liner~~ should work like this but there's a bug as described in https://github.com/godotengine/godot/issues/31056#issuecomment-518163829:
```gdscript
class_name Foo extends Node
```
which otherwise wouldn't make it easier to comprehend:
```gdscript
extends Node class_name Foo
```

**Comment by akien-mga** [comment]
CC @vnen @bojidar-bg @lupoDharkael 

As I mentioned on https://github.com/godotengine/godot/issues/24364#issuecomment-447641113, it would be better if it worked the same way regardless of the order, but if that's not possible, then we'll have to confirm and document this compat breakage.

**Comment by Zylann** [comment]
I hit this today when testing 3.2, I confirm it's quite confusing that it doesn't work regardless of order, and breaks my plugin.
