### ISSUE TITLE
WASM cant export on Google Chrome or Internet explorer

### ISSUE THREAD

**Issue by andrew-njoroge** [godotengine/godot#29342]
**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
When testing locally using Chrome, you need to run a local Web server to comply with its security policies; see the beginning of [Exporting for the Web](https://docs.godotengine.org/en/latest/getting_started/workflow/export/exporting_for_web.html) for details.

As for Internet Explorer, [it doesn't support WebAssembly](https://caniuse.com/#feat=wasm), so it's expected not to work.

**Comment by KoBeWi** [comment]
Is the problem maybe the same as in this issue #28103?

**Comment by Zireael07** [comment]
Firefox 68.0.1. also blocks file// requests, so this issue now makes the 'run in browser' editor button completely useless, since IE doesn't do WASM and the other two browsers now block due to cors policies.

**Comment by Calinou** [comment]
@Zireael07 Running a local web server for development is being tracked in #16245. There's also a workaround described in https://github.com/godotengine/godot/issues/16245#issuecomment-405003096.

**Comment by andrew-njoroge** [comment]
@KoBeWi 
Yes it is the same problem as that one

**Comment by Calinou** [comment]
@andrew-njoroge I'll close this issue in favor of #28103 then :slightly_smiling_face:
