### ISSUE TITLE
Type information for `Node.Connect` in Mono

### ISSUE THREAD

**Issue by Radbuglet** [godotengine/godot#29346]
**Godot version:**
Godot `v3.1.1.stable.mono.official`

**OS/device including version:**
MacOS v10.12.6

**Issue description:**
One of the major benefits of using C# over GDScript is its robust typing system. However, with default Godot Signals, there is absolutely no type checking when it comes to ensuring that a handler is valid for a specific event. Currently, a run time error is displayed if the signal doesn't exist, if the handler method couldn't be found or if none of the found methods have adequate parameter counts and typings however I believe that, if possible in C#, these things should be displayed at compile time.

**Steps to reproduce:**
n.a.

**Minimal reproduction project:**
Here is some example code of what could happen: (Doesn't and probably can't act exactly like this if the feature is added, this is just an example of functionality:
```cs
class MyPublisherNode : Node
{
	[Signal]
	public delegate void MySignal(int signalArg1);
}

class MySubscriberNode : Node
{
	public override void _Ready()
	{
		var myPublisherNode = ...;
		myPublisherNode.Connect(MyPublisherNode.MySignal, this, this.MyHandler1); // Shouldn't compile
		myPublisherNode.Connect(MyPublisherNode.MySignal, this, this.MyHandler2); // Should compile
		myPublisherNode.Connect(MyPublisherNode.MySignal, this, this.MyHandler3); // Shouldn't compile
		myPublisherNode.Connect(MyPublisherNode.MySignal, this, this.MyHandler3, new Array{ 21 }); // Should compile
	}

	public void MyHandler1() {}
	public void MyHandler2(int signalArg1) {}
	public void MyHandler3(int signalArg1, int bindArg1) {}
}
```

The 1st one **shouldn't** compile because the handler doesn't have enough arguments to support `MySignal`.
The 2nd one **should (and does)** compile because the handler and event signatures match.
The 3rd one **shouldn't** compile because the handler doesn't have enough arguments to support `MySignal` plus the extra binds.
The 4th one **should (and does)** compile because the handler has enough arguments to support arguments from the event plus the extra binds.

**Comment by Radbuglet** [comment]
**Disclaimer:** I only started working with C# a month ago when I started using Godot Mono so I probably don't know what I'm talking about.

Looking around [Microsoft C# documentation](https://docs.microsoft.com/en-us/dotnet/api/system.eventhandler-1?view=netframework-4.8#examples), the example code tends to use argument objects (eg `ThresholdReachedEventArgs`, `EntityKilledEventArgs`). I feel like this, in conjunction with bind argument objects (eg `KillContextBindArgs`) would make adding typing to the event system a lot easier. I mean, there's probably a reason why .NET recommends to do events this way instead of the current "GDScript way".

If it is done this way, implementing this isn't too hard:
```cs
[System.Serializable]
public delegate void GdEvent<in TEventArgs>(TEventArgs eventArgs);

[System.Serializable]
public delegate void GdEventHandler<in TEventArgs, in TEventBind>(TEventArgs eventArgs, TEventBind bindArgs);

public class Object
{
    // ...

    public void MonoConnect<TEventArgs, TBinds>(GdEvent<TEventArgs> @event, Object @object, GdEventHandler<TEventArgs, TBinds> handler, TBinds binds)
    {
        // ...
    }
    
    public void MonoConnect<TEventArgs>(GdEvent<TEventArgs> @event, Object @object, GdEvent<TEventArgs> handler)
    {
        // ...
    }

    public void MonoFire<TEventArgs>(GdEvent<TEventArgs> @event, TEventArgs eventArgs)
    {
        // ...
    }

    // ...
}
```

Example usage:
```cs
public class Entity : Node
{
    // ...

    class EntityDeathEvent
    {
        public Entity Killer;
        public bool WasSuicide;
        // ...
    }

    [Signal]
    public event GdEvent<EntityDeathEvent> OnDeath;

    private void Suicide() {
        // ...
        MonoFire(OnDeath, new EntityDeathEvent{Killer=null, WasSuicide=true});
    }

    // ...
}

public class DeathChatAnouncer : Node
{
    class EntityDeathBinds
    {
        public bool WasFriendly;
        // ...
    }

    private void HandleEntityDeath(Entity.EntityDeathEvent event, EntityDeathBinds binds)
    {
        // ...
    }

    public void RegisterFriendlyEntity(Entity entity)
    {
        entity.MonoConnect(Entity.OnDeath, this, HandleEntityDeath, new EntityDeathBinds{WasFriendly=true});
    }

    public void RegisterFoeEntity(Entity entity)
    {
        entity.MonoConnect(Entity.OnDeath, this, HandleEntityDeath, new EntityDeathBinds{WasFriendly=false});
    }
}
```

The biggest downside to this is that there would be two separate `Connect` methods which could confuse beginners so I guess `Connect` would have to be deprecated and the difference between "GDScript style events" and "Mono style events" would have to be pointed out in the docs.

**Comment by Radbuglet** [comment]
Hello,

I just finished writing a proposal on how we could implement type-checking for signals in Godot and generally make them less of a pain point.

Here's a [Gist](https://gist.github.com/Radbuglet/39955c397067c7cbc240db695aa70bc6) of my prototype (**not yet tested in a real Godot environment**).

Here are my proposed changes (**but please, read the Gist as well**):
- Modify `Godot.Object`:
  - Remove or deprecate (or don't, I don't know how Godot handles legacy features):
    - `AddUserSignal`
    - `EmitSignal`
    - `Connect`
    - `Disconnect`
    - `IsConnected`
  - Change `GetIncomingConnections` to reflect new abilities of `Godot.Signal.Connect`.
  - Add `GetSignal` method to `Godot.Object` with [this method signature](https://gist.github.com/Radbuglet/39955c397067c7cbc240db695aa70bc6#file-godot-signals-idea-proto-v2-cs-L78).
- Add `Godot.Signal` class (detailed [here on the aforementioned Gist](https://gist.github.com/Radbuglet/39955c397067c7cbc240db695aa70bc6))
- Add `Godot.SignalConnection` class (detailed [here on the aforementioned Gist](https://gist.github.com/Radbuglet/39955c397067c7cbc240db695aa70bc6#file-godot-signals-idea-proto-v2-cs-L49))
- Signal connections shouldn't just support class method members. They should support anything that conforms to the signal delegate (ie methods, anonymous methods, lambdas, etc)

**Please be aware, I am not a very experienced C# developer and I am still learning about new features in C# that may allow for an even better solution.**

Thanks,
Rad

**Comment by Radbuglet** [comment]
Hello,

After a lot of research, I've decided to not add support for anonymous delegates/lambdas in the `Object.Connect` method. However, the syntax of using lambdas to relay signal connections to methods was good as it provided type checking to the `Connect` method's handler. As a compromise, I decided to use a `Linq Expression` to specify the handler and wrote some parsing logic to convert the lambda into a validated handler and binds.

So far, I've completed a functional extension class for the feature which can be found in [this Gist](https://gist.github.com/Radbuglet/af39726e773e32f843a111556f070393).

As to the proposed changes, forget everything I previously said! My new proposed changes only modify the Mono glue. There aren't any needed deprecations or new features to be written in C++. To add this, the `Signal` class should be imported and my extension method should be implemented as an actual method for `Godot.Object`. That should be it.

Thanks,
Rad

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
