### ISSUE TITLE
Allow plugins to not have init scripts

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#29356]
**Godot version:** 3.1.1 and master

**Issue description:** With [Godot plugins](https://docs.godotengine.org/en/3.1/tutorials/plugins/editor/making_plugins.html), you are normally expected to define a script to initialize the plugin, and have this line in `plugin.cfg` to call it:

    script="mycoolthing_plugin.gd"

Yet sometimes, you don't need to do anything in the script to initialize the plugin. 

* If you remove the line, Godot gives you a warning about the plugin not containing a script. 
* If you change the line to `script=""`, Godot fails to load the plugin with an error that it can't find the script at the plugin's path.

Proposal: `script=""` should be interpreted as having no script, and show no warning.

**Comment by akien-mga** [comment]
Do you have an example of a plugin with no script?

**Comment by aaronfranke** [comment]
Yes, [this one](https://github.com/aaronfranke/GodotExtraMath) I just submitted today. I gave it [an empty script](https://github.com/aaronfranke/GodotExtraMath/blob/master/extramath_plugin.gd) for now.
