### ISSUE TITLE
File picker uses 2.1 theme.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#29351]
The File picker from 3.1.1 uses the old 2.1 theme.

**Comment by KoBeWi** [comment]
Every Control node uses the old theme in-game. They were only updated in editor. Or you mean something else?

**Comment by ca3games** [comment]
> Every Control node uses the old theme in-game. They were only updated in editor. Or you mean something else?

Yes, I mean when playing the game.

**Comment by KoBeWi** [comment]
Well, it has all the functionality of editor's FileDialog, despite the old theme. So as I said, it's supposed to be like that, same with other GUI nodes.
