### ISSUE TITLE
OS.has_touchscreen_ui_hint() returns 'False' on Surface Go

### ISSUE THREAD

**Issue by tree786** [godotengine/godot#29350]
**Please search existing issues for potential duplicates before filing yours:**
Similar issue #90 has been before, but it seems as the problem has been solved for a different Surface device (so will open this new thread).

**Godot version:**
 3.1.1 stable (godotengine.org)

**OS/device including version:**
Device: Surface Go
OS: Windows 10 Home v1803

**Issue description:**
Using `OS.has_touchscreen_ui_hint()` on the Surface Go (a touchscreen device) returns False. This function works well on my phone (returns True for the Galaxy S6), so I suspect it's something related to the Surface Go.

**Steps to reproduce:**
`print(OS.has_touchscreen_ui_hint())`

**Minimal reproduction project:**
`print(OS.has_touchscreen_ui_hint())`

**Comment by KoBeWi** [comment]
Are you using Windows or UWP export?

**Comment by tree786** [comment]
> Are you using Windows or UWP export?

Hi, thanks for the reply
Sorry, I didn't understand the question. Do you mean 'UWP export' as in Windows Universal? I'm running  the engine via the editor (F5) and not the exported app (please excuse me for I know next to nothing about what UWP is)

**Comment by KoBeWi** [comment]
> Do you mean 'UWP export' as in Windows Universal?

Yeah, I just thought it's about exported game, not running from editor (Surface Go part implied it).

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc2](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-2) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue, and make sure that there is an up-to-date reproduction project.
