### ISSUE TITLE
The default thumbnail size should be bigger

### ISSUE THREAD

**Issue by Daw11** [godotengine/godot#29352]
**Godot version:**
3.2.dev

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
The default thumbnail size right now is 64 pixels.
![1](https://user-images.githubusercontent.com/3595817/58721822-234d0180-83d6-11e9-8f71-146963512ac7.png)

I think that it's a little too small, especially if you have a large monitor.
96 pixels seems to be a good compromise, it doesn't waste too much space and the images are more readable.
![2](https://user-images.githubusercontent.com/3595817/58722028-af5f2900-83d6-11e9-92ce-e03e750d0aa9.png)

It's already possible to change this value within the editor, my proposal is just to make the default a bit larger.
![3](https://user-images.githubusercontent.com/3595817/58722187-17ae0a80-83d7-11e9-9a67-fca49d6b3863.png)

**Comment by Calinou** [comment]
Is there a significant performance difference with larger values? This should be tested on a slow PC (such as an ultrabook with no dedicated graphics card).

**Comment by groud** [comment]
One of the strength of the Godot editor is to look nice directly on both small screen and big screens too. IMHO, increasing the default size would significantly worsen the UX on small screens, so it is not a good idea.
Small are still really important for people working on laptops, which happens a lot in game jams, for example.

**Comment by Althar93** [comment]
What about adding a slider directly in the filesystem dock (probably in the top/right, just under the set of icons/button)?

Something like this : https://s3.amazonaws.com/ssi-article-images/adobe/pse/pse10/media-browser-5.jpg

The slider scale could be applied on top of the specified thumbnail size, and give additional x0.5, x1, x2, x4 scaling modes for the duration of the operation ; or alternatively, it could simply map directly to the 'Thumbnail Size' value saved in the editor allowing the user to change this setting in two different places.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
