### ISSUE TITLE
Expose Control closest focus neighbour selection to GDScript

### ISSUE THREAD

**Issue by Rriik** [godotengine/godot#29357]
**Godot version:** 3.1.1 stable

**Issue description:**
This issue is relevant for making keyboard/controller-friendly UI navigation. Godot by default can determine the closest focus neighbours when the user tries to navigate the interface using default input actions. If the `focus_neighbour_*` properties are not explicitly set, quoting, "Godot will give focus to the closest Control to the [direction] of this one."

The problem comes when it is desired to call for this "best guess" on demand through script. To my understanding, there is currently no way to to obtain the closest neighbouring control node to give focus to. This functionality isn't exposed in the GDScript API, which makes it difficult to implement certain types of interfaces or for ease of use when navigating them with keyboard/controller.

I am asking for a function possibly called `get_closest_focus_neighbour` which would need a direction parameter and would return the closest node to give focus to, using the same algorithm Godot does when searching for them. This could also be extended to `focus_previous/next` best guess algorithms.

**Comment by linkpy** [comment]
For my project i use the default tabing algorithm of godot, and for some cases i want to change the focus from GDScript using that algorithm, but it's not exposed.
