### ISSUE TITLE
Tooltips are not shown when the scene tree is paused.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#29362]
**Godot version:** master (e9be875)

**OS/device including version:** Arch Linux

**Issue description:** Tooltips are not shown when the scene tree is paused.

This is possibly caused by `tooltip_timer`s being managed in the root viewport's `NOTIFICATION_INTERNAL_PROCESS`. The root viewport likely has a `PAUSE_MODE_INHERIT` by default, so the notification in question won't be sent when the tree is paused.

**Steps to reproduce:**

* Add a control with a tooltip.
* Hover it while unpaused. The tooltip will show up normally.
* Pause the scene tree.
* Hover the control while paused. The tooltip won't show up, regardless of the control's own `pause_mode`.

**Minimal reproduction project:** [pause-tooltip.zip](https://github.com/godotengine/godot/files/3243394/pause-tooltip.zip)

**Comment by KoBeWi** [comment]
Likely related: #29101

**Comment by ktosox** [comment]
Any hope of this ever getting resolved? Just wondering as it's not an obvious behavior and it's not noted in the documentation. Took me over an hour of flipping my project upside down to figure out that it was the pause state of the tree that caused hints to sometimes not show up.

**Comment by KoBeWi** [comment]
> Just wondering as it's not an obvious behavior and it's not noted in the documentation.

Maybe this should just be mentioned in the docs...

**Comment by chucklepie** [comment]
@KoBeWi 
A typical use-case is in almost every game the options/config window is made visible and the game behind paused. But doing this means tooltips won't work and a custom solution recreating all of tooltips is required by.

So I would imagine this could affect a lot of people and is more of a bug than an enhancement.
