### ISSUE TITLE
Error when launching Godot

### ISSUE THREAD

**Issue by HeyTheories** [godotengine/godot#29361]
**Godot version:**
v3.1.1

**OS/device including version:**
Windows 10, 1607

**Issue description:**
I just installed the engine and am getting errors when I open it and when I click things on Godot it doesnt show untill I go full screen then minimize and so on. Hopefully this made sense.

Errors: https://gyazo.com/867375f269a6aee6fae6e8a71cbed3bf

**Steps to reproduce:**
Launching Godot

**Comment by Calinou** [comment]
Try updating your graphics driver to the latest version *provided by Intel* as described in https://github.com/godotengine/godot/issues/23069#issuecomment-471168356.

**Comment by HeyTheories** [comment]
> Try updating your graphics driver to the latest version _provided by Intel_ as described in [#23069 (comment)](https://github.com/godotengine/godot/issues/23069#issuecomment-471168356).

My drivers are up to date

**Comment by KoBeWi** [comment]
@HeyTheories Does it still happen in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1)?

**Comment by akien-mga** [comment]
No answer, so closing.
