### ISSUE TITLE
[MacOS] Godot crashes when trying to create a GDScript

### ISSUE THREAD

**Issue by MattSays** [godotengine/godot#29370]
**Godot version:**
3.1.1 (Standard edition)

**OS/device including version:**
Mac Os Macbook pro 13 2017 base model

**Issue description:**
When i try to create/open a gd script an exception is thrown.

For more infos: https://pastebin.com/BdbAnxta

**Comment by bruvzg** [comment]
Are you trying to use external text editor? In you are it's probably duplicate of the #17615, check your external editor path is set correctly.

**Comment by MattSays** [comment]
No I just want to use the built-in editor

**Comment by MattSays** [comment]
I solve it. For an unknown reason the external editor option was enabled.
