### ISSUE TITLE
HTTPRequest returns RESULT_CANT_RESOLVE on Android even with Internet permission

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#29387]
**Godot version:** 3.1.1

**OS/device including version:** Android - Xiaomi Redmi 4A

My app uses `HTTPRequest` to load a JSON file hosted on `github.com`. Everything works fine in Windows (debugging or Export), and worked fine on Android until recently.

Now, irrespective of whatever URL I specify, the response I get back in the `request_completed` event handler has a result code of 3 (`RESULT_CANT_RESOLVE`). I made sure that the Android export settings include the `Internet` permission; strangely enough, with or without that permission, I get the same error.

Again, this used to work on Android a couple of days ago, and now it doesn't.

**Minimal reproduction project:** https://github.com/nightblade9/lecture-library (latest commit)

**Sample code**
```
const _INDEX_FILE_URL = "https://raw.githubusercontent.com/nightblade9/lecture-library/master/metadata.json"

func _ready():
	var request = HTTPRequest.new()
	add_child(request)
	request.connect("request_completed", self, "_on_download_completed")
	request.request(_INDEX_FILE_URL)

func _on_download_completed(result, response_code, headers, body):
	if result != 0: # RESULT_SUCCESS
		print("Something went wrong when getting the list of lectures from the server.  Please try again later.\nResult: " + str(result) + ". Response Code: " + str(response_code))
	else:
		print("success")
```

**Comment by Calinou** [comment]
I remember seeing something about Android permission names being confusing. Don't you need to enable a second permission to actually access network resources?

**Comment by nightblade9** [comment]
> I remember seeing something about Android permission names being confusing. Don't you need to enable a second permission to actually access network resources? (I don't remember its name, sorry.)

Interesting thought. I couldn't find the permission you're referring to, so I added every single permission. I still get the same error.

This makes sense - the app worked a few days ago when it just had the `Internet` permission.

**Comment by Faless** [comment]
@nightblade9 can you post the ADB log portion related to godot? Does it makes any difference between using a mobile connection (3g/4g/etc) or a WiFi connection instead? Might it be another bogus dual-ip network like in #27864 ?

**Comment by NoodleSushi** [comment]
I really need a workaround/solution for this 😭

**Comment by nightblade9** [comment]
@Faless I stopped working on my app back in May because of this. I will try to get you the ADB logs. I don't use mobile data, just WiFi (my app was for downloading/streaming large audio files).

**Comment by Faless** [comment]
This issue seems stale, is it still valid? @nightblade9 can you still reproduce it in`3.2`?

**Comment by nightblade9** [comment]
I don't use Godot any more and I dumped this project back in June after getting stuck on this bug. I suspect the problem was something phone-specific, but I can't prove it.

@Faless my initial post has a link to the complete project. If you have a working Godot environment, you can quickly test it out and see if it works for you or not.

Based on my assumptions about it being environment/phone specific, I'm going to go ahead and close it. Feel free to reopen it if it actually *is* a real bug though.
