### ISSUE TITLE
Godot 3.0 editor woes

### ISSUE THREAD

**Issue by ahalfmontynun** [godotengine/godot#29386]
Godot version: 3.0

OS/device including version:
Windows 7 64 bit

Issue description:
Upon starting Godot, the 2D editor window is entirely missing and the top toolbar is stretched downward across the screen, project files do not appear in the expected window (bottom left),  text language changes randomly but only in certain parts of the inspector, and the tools along the bottom bar (Animation, Audio, etc) open downward off the screen. I have tried different versions of Godot, all with the same result. Yesterday, i restored my computer to an restore point from about a week ago, and it seemed to fix the issue. It worked fine for the rest of the day, but today the problem is back.

![godot](https://user-images.githubusercontent.com/51270221/58751448-6305fe80-8453-11e9-92fc-011d8e76f1aa.PNG)

**Comment by Calinou** [comment]
@ahalfmontynun What graphics card do you have? Make sure you're using the latest version of the graphics driver, as provided by the GPU manufacturer.

**Comment by ahalfmontynun** [comment]
It is a GT430 so an older card for sure, but i checked the drivers and they are up to date. I have not yet tried 3.1.1, as the other members of my team are nhesitant to make the switch, with all of the fixes and rebuilding it will entail

**Comment by Anutrix** [comment]
Check what driver changes happen during system restore.

**Comment by dreamsComeTrue** [comment]
@ahalfmontynun is the bug still relevant for 3.2 ?

**Comment by Anutrix** [comment]
It could also be editor config file issue. Try deleting the config files.

**Comment by Calinou** [comment]
Closing, as nobody has been able to reproduce this recently. Please comment if you can still reproduce this issue (make sure to state your hardware and OS version).
