### ISSUE TITLE
using nordic layout in godot editor makes certain symbols not register such as [] or {} 

### ISSUE THREAD

**Issue by gnurn** [godotengine/godot#29399]
**Godot version:**

**OS/device including version:**
< Windows 10 Home-->

**Issue description:**
<Godot doesn't register typing symbols such as { , [  or \ which requires ctrl+alt+"button" on nordic layout. Other symbols which only requires shift+"button" works tho like "!" or ( . I could  copy paste the ctrl+alt+"button symbols into the Godot editor from google .

  -->

**Steps to reproduce:**
use a nordic layout, try typing symbols such as [ or {  inside the Godot editor.

**Minimal reproduction project:**

**Comment by olejr** [comment]
It's working if you use the **Alt Gr** key instead of Ctrl+Alt.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc2](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-2) or any later release?

**Comment by Calinou** [comment]
@KoBeWi Judging by @olejr's comment, this should be resolved by https://github.com/godotengine/godot/pull/37769 once it's merged.
