### ISSUE TITLE
[Bullet] move_and_slide_with_snap causes erroneous movement near edges

### ISSUE THREAD

**Issue by jackwilsdon** [godotengine/godot#29392]
**Godot version:** v3.1.stable.official

**OS/device including version:** Windows 10

**Issue description:** `move_and_slide_with_snap` causes a `KinematicBody` to slide of it's own accord if it's near an edge.

**Dropped directly on the seam**
![Dropped on seam](https://user-images.githubusercontent.com/1843197/58755062-dc453600-84d3-11e9-9928-ad78b7e086fd.gif)

**Dropped near the seam**
![Dropped near seam](https://user-images.githubusercontent.com/1843197/58755102-e74c9600-84d4-11e9-98c4-85ef47a26d24.gif)

Note that this doesn't happen when dropped near the seam if the static body on the left is not present.

**Steps to reproduce:** Create two static bodies with box collision shapes that are touching and drop a KinematicBody using `move_and_slide_with_snap` near the seam (doesn't happen with `move_and_slide` at all).

**Minimal reproduction project:** [seam_bug.zip](https://github.com/godotengine/godot/files/3244327/seam_bug.zip)

**Comment by klhrt** [comment]
happens with move_and_slide() and move_and_collide() in 3.1.1

**Comment by madmiraal** [comment]
Related to #28438?

**Comment by jackwilsdon** [comment]
@madmiraal #28438 doesn't seem to be using `move_and_slide_with_snap`, although I guess that doesn't eliminate the possibility of them being caused by the same root issue.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by pouleyKetchoupp** [comment]
Can be still reproduced in 3.2.4 beta 5, but occurs only when using Bullet Physics (default settings). Switching to Godot Physics 3D fixes the issue.

**Comment by David-Ochoa** [comment]
Well, it doesn't fix the issue because I can't switch from bullet to godot Physics, it's more accurate to say it's not present on Godot Physics

**Comment by pseidemann** [comment]
I confirm this issue still exists with `move_and_slide`, v3.4.4.stable.official [419e713a2], macOS 12.3.1 (21E258) with the Bullet engine.
In my case I just walk over the seams which causes my player to make little jitter jumps which disrupt the experience.

**Comment by akien-mga** [comment]
Fixed by #56801.
