### ISSUE TITLE
Clarify documentation: Overriding Class Functions vs Setters and Getters

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#29390]
**Godot version:**

3.1.1

**OS/device including version:**

Any

**Issue description:**

```
func set_default_color(new_value: Color) -> void:
	print("hey")
	default_color.a = 0.0
```
In a tool script on a Line2D Node results in nothing. No printing, no color change.

**Steps to reproduce:**
^

**Minimal reproduction project:**

**Comment by TheDuriel** [comment]
So, after some further discussion in discord. This is not a bug, no setters and getters are overridable if the property is not declared by the user. However, this begs the question of poor documentation. Class functions _are_ overridable in all cases. and the original can be called in .<name>. Setters and Getters are documented in the same manner, but are also entirely pointless since they are _not_ overridable. There _may_ be some hacky way to do it by overriding set and get, but thats a really bad solution if it even works.

**Comment by TheDuriel** [comment]
@KoBeWi Since you're around. Can you redo the tags please?

**Comment by henriiquecampos** [comment]
Is there anyway to at least add a warning to the Editor's warnings to communicate this in any manner? Like when we use `set_*` it will automatically warn that `Built-in setter and getter functions are not overridable`, then the person can decide if they want to create their own.

**Comment by bojidar-bg** [comment]
Even better: warn when a script overrides a function present in the base class which isn't marked "virtual". That way people overriding e.g. `CanvasItem.update` would be warned.

**Comment by KoBeWi** [comment]
Trying to override built-in setters now results in an error, so this is resolved.
