### ISSUE TITLE
Unable to connect nodes in GraphEdit when using a custom theme

### ISSUE THREAD

**Issue by mrzapp** [godotengine/godot#29404]
**Godot version:**
v3.1.1

**OS/device including version:**
Fedora 30

**Issue description:**
When using an AnimationTree with AnimationNodeBlendTree while a custom theme is selected, the inputs/outputs are unresponsive. Only removing the theme restores the functionality.

_bugsquad edit: Affecting all GraphEdit nodes (Visual shaders/Visual scripts)_

**Steps to reproduce:**
- Create a new derived theme
- Set it as a custom theme in the project GUI settings

**Minimal reproduction project:**
[here](http://ge.tt/1RKiEPw2)

Holy crap, this was hard to track down :sweat_smile:

**Comment by bojidar-bg** [comment]
Just tested, the VisualScript editor is broken as well.

**Comment by zaksnet** [comment]
@akien-mga , @bojidar-bg , I think something fixed this ( or broke it even more ) Autocomplete and node connections seem to work now but some theme properties are being ignored like `WindowPopup` `Title Font`.

**Comment by bojidar-bg** [comment]
There might have been some effects from #30351.

**Comment by rrei** [comment]
This is still affecting 3.2. I was trying out the visual shader editor and I can't connect anything (drag behavior takes over).

**Comment by snougo** [comment]
well, it's weird because I didn't use any custom theme but I still got this issue few days ago, but I can't reproduce it again after rebooting Godot Editor

**Comment by KoBeWi** [comment]
The MRP is dead.
Can someone still reproduce this in Godot 4.0 and provide a new minimal project?

**Comment by rluders** [comment]
I'm having a similar issue at `v4.0.alpha16.official [86dd3f312]`, but no custom theme (?).

I'm creating an `AnimationNodeStateMachine` and trying to connect the nodes, but as you can see in the video it isn't creating the connections at all.

![godot_bug](https://user-images.githubusercontent.com/191027/189358891-a1803ca2-9b32-4a92-b3eb-2734d9aa9d9c.gif)

**Comment by YuriSizov** [comment]
I think the original issue was due to the fact that the custom theme missed some properties. Previously, the custom theme had to be a complete replacement for the editor theme. Nowadays you can have partial custom themes, and they'd merge together, so no property would be amiss.

The latest reported issue in this ticket seems to be unrelated (and it's worth reporting it again, separately, @rluders, if you can still reproduce it in the latest beta).
