### ISSUE TITLE
Godot sharp freezes when there are csv files present and I update a script

### ISSUE THREAD

**Issue by blukatdevelopment** [godotengine/godot#29402]
**Godot version:**
V3.1.1.stable.mono.official

**OS/device including version:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
**CPU**
AMD FX(tm)-8350 Eight-Core Processor
**GPU**
  *-display                 
       description: VGA compatible controller
       product: Cayman PRO [Radeon HD 6950]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:07:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:35 memory:d0000000-dfffffff memory:fe9c0000-fe9dffff ioport:e000(size=256) memory:c0000-dffff

**Issue description:**
I had csv files used to store data in a project while using 3.0.6. When I upgraded to 3.1, I found that the editor was freezing almost every time I updated a script.

**Steps to reproduce:**
1. Play the scene in the attached project
2. Edit the DebugScript.cs slightly (Repea)
3. Play the scene again
4. Attempt to click the play button again and notice it is frozen.

You might have to repeat steps 2 and 3 once or twice to get the desired effect.

**Minimal reproduction project:**
[freezing_bug.zip](https://github.com/godotengine/godot/files/3244950/freezing_bug.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by akien-mga** [comment]
Tested in 3.2.4 beta 3 and couldn't reproduce the freeze.

There are however import errors for the CSV as they are being imported as CSVTranslation but they're not valid translation catalogs:
```
ERROR: import: Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
   At: editor/import/resource_importer_csv_translation.cpp:96.
ERROR: _reimport_file: Error importing 'res://cool.csv'.
   At: editor/editor_file_system.cpp:1801.
ERROR: import: Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
   At: editor/import/resource_importer_csv_translation.cpp:96.
ERROR: _reimport_file: Error importing 'res://lame.csv'.
   At: editor/editor_file_system.cpp:1801.
```
But that's a different issue, see #38245.
