### ISSUE TITLE
stex file's size is about 8 times bigger than the original jpg file's size after import.

### ISSUE THREAD

**Issue by lefay1982** [godotengine/godot#29415]
**Godot version:**
3.1.1

**OS/device including version:**
ALL

**Issue description:**
I have a jpg texture's size is 6.5m, when I use it in godot, after import, this file in .import folder stex file is 52.5m.
why it is so bigger than original file?

how can I reduce the file size for it?
![TIM图片20190603110950](https://user-images.githubusercontent.com/5716884/58773704-af3a7580-85f0-11e9-9ea2-b54dbe4a5fdc.png)
![TIM图片20190603111024](https://user-images.githubusercontent.com/5716884/58773708-b3ff2980-85f0-11e9-8ebd-7ae3f0e73851.png)

**Comment by lefay1982** [comment]
I found convert jpg to png RGB8888, the size also is 55m.
It is godot's StreamTexture convert jpg to RGB8888 format. so the jpg's size become bigger?

**Comment by lefay1982** [comment]
I use reimport the jpg to lossy, can reduce the stex size.
![TIM图片20190603202855](https://user-images.githubusercontent.com/5716884/58801841-44b02680-863e-11e9-9cdf-85fc60d38911.png)
![TIM图片20190603202944](https://user-images.githubusercontent.com/5716884/58801866-572a6000-863e-11e9-95fd-7c84f5ee2c72.png)

**Comment by fire** [comment]
Is there something we should do? Like default to compressed vram?

**Comment by Calinou** [comment]
> Is there something we should do? Like default to compressed vram?

This is already the case for assets used in 3D. VRAM compression shouldn't be used in 2D as its artifacts are too noticeable.

**Comment by fire** [comment]
Closed due to analysis by Calinou since we're optimizing for other advantages we can't get everything.
