### ISSUE TITLE
build error: platform=isim

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#2942]
msg: no souch file or directory
xcode v7.1.1

**Comment by vnen** [comment]
The `detect.py` from isim platform is very buggy indeed. You may try to tweak it to make it work (by comparing with the `detect.py` from iphone platform).

You should also provide more of the output from the command, since you're not even saying which file is missing.

**Comment by ret80** [comment]
I do not understand anything.And I expect that all the same, you eliminate it, not me.
Why do you need to know which file is missing. Just try to build "isim" at home. If you have no errors, then discuss what files I do not have. If errors occur simply eliminate them.

**Comment by akien-mga** [comment]
Please mind your tone. We are not working for you.
And yes, if you want this issue to be fixed, you need to provide more info. Many of us don't have Xcode or any means to try to build the isim platform, so some pointers to know what is not working might help us redirect the issue towards who can fix it.

The other option is that nobody cares, and hopefully in a few months someone tries to build it and provides better info.

**Comment by ret80** [comment]
I have a normal tone. all questions to the Google translator :)

**Comment by ret80** [comment]
He made changes in the "isim/detect.py". It was possible to collect the "godot.isim.tools". It runs successfully. Please fill in the changes to the repository
file:
https://yadi.sk/d/TmQxphVNkuqvn

**Comment by akien-mga** [comment]
Thanks @ret80! @punto- could you review the changes and push them if they're good?

**Comment by ret80** [comment]
It was:
<code>
def get_opts():
	return [
              ('ISIMPATH', 'the path to iphone toolchain', '/Applications/Xcode.app/Contents/Developer/Platforms/${ISIMPLATFORM}.platform'),
             ('ISIMSDK', 'path to the iphone SDK', '$ISIMPATH/Developer/SDKs/${ISIMPLATFORM}.sdk'),

def configure(env):
   ...
   env['CC'] = '$ISIMPATH/Developer/usr/bin/gcc'
   env['CXX'] = '$ISIMPATH/Developer/usr/bin/g++'
   env['AR'] = 'ar'
</code>

It became:
<code>
def get_opts():
	return [
               ('ISIMPATH', 'the path to iphone toolchain', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain'),
               ('ISIMSDK', 'path to the iphone SDK', '/Applications/Xcode.app/Contents/Developer/Platforms/${ISIMPLATFORM}.platform/Developer/SDKs/${ISIMPLATFORM}.sdk'),

def configure(env):
   ...
   env['CC'] = '$ISIMPATH/usr/bin/${ios_triple}clang'
   env['CXX'] = '$ISIMPATH/usr/bin/${ios_triple}clang++'
   env['AR'] = '$ISIMPATH/usr/bin/${ios_triple}ar'
   env['RANLIB'] = '$ISIMPATH/usr/bin/${ios_triple}ranlib'
</code>

**Comment by ret80** [comment]
tag "code" all as the spoils

**Comment by ret80** [comment]
how to push the changes?

**Comment by punto-** [comment]
is there an "ios_triple" somewhere? or is it just supposed to be empty?

**Comment by punto-** [comment]
ok, just pushed with these changes

**Comment by ret80** [comment]
everything is working. can be closed.
