### ISSUE TITLE
String.rsplit and String.split are the same

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#29429]
Maybe i am just misunderstanding but this is what i expected and what i'v got instead:
var updates : String = "path/morePath/file.exe"
Both print(updates.rsplit("/")) and print(updates.split("/")) returns ["path","morePath","file.exe"] while i would expect print(updates.rsplit("/")) to return ["file.exe","morePath","path"]. Even in the documentation it states that the result is the same. If so, then whats the difference between them?

> PoolStringArray split ( String divisor, bool allow_empty=True, int maxsplit=0 )
> Splits the string by a divisor string and returns an array of the substrings.
> 
> Example: "One,Two,Three" will return ["One","Two","Three"] if split by ",".
> 
> If maxsplit is given, at most maxsplit number of splits occur, and the remainder of the string is returned as the final element of the list (thus, the list will have at most maxsplit+1 elements)

> PoolStringArray rsplit ( String divisor, bool allow_empty=True, int maxsplit=0 )
> Splits the string by a divisor string and returns an array of the substrings, starting from right.
> 
> Example: "One,Two,Three" will return ["One","Two","Three"] if split by ",".
> 
> If maxsplit is specified, then it is number of splits to do, default is 0 which splits all the items.

**Comment by KoBeWi** [comment]
The last argument makes difference. If you specify max splits, you will end up with n strings either starting from left or from right.

**Comment by zaksnet** [comment]
Well since i opened this, 
"Splits the string by a divisor string and returns an array of the substrings."
That's partly wrong, it returns a PoolStringArray, not an Array.

**Comment by akien-mga** [comment]
`PoolStringArray` is a type of *array* (lowercase, common noun designing a list container), but not an `Array` indeed (capitalized, formatted as code, builtin class name). So it's fine to refer to it as "an array" and the `PoolStringArray` return type specified in the signature tells you what kind of array exactly.

**Comment by akien-mga** [comment]
The documentation could be improved to make things clearer though. If the only difference comes from the maxsplits argument, the code example should make use of it to show this difference. It should also be clearer that the string is split from the right up to maxsplits, but that the returned split strings are still ordered from left (maxsplits-th split) to right (0).

**Comment by zaksnet** [comment]
> `PoolStringArray` is a type of _array_ (lowercase, common noun designing a list container), but not an `Array` indeed (capitalized, formatted as code, builtin class name). So it's fine to refer to it as "an array" and the `PoolStringArray` return type specified in the signature tells you what kind of array exactly.

I see, inside godot i can see the return type :
![godot-string-rsplit](https://user-images.githubusercontent.com/1850856/58801206-8aef9080-8612-11e9-9b1a-37ecf267188d.png)

But at godot website:
![godot-help-page](https://user-images.githubusercontent.com/1850856/58801167-6f848580-8612-11e9-9769-9897271d6e62.png)

**Comment by zaksnet** [comment]
Also i made the changes of the documentation as you can see but i have no idia how to make a pull request :/

**Comment by KoBeWi** [comment]
> i have no idia how to make a pull request 

https://docs.godotengine.org/en/3.1/community/contributing/pr_workflow.html

**Comment by zaksnet** [comment]
Also! why is there a [code][/code] tag inside the xml, it adds no styling to the text from what i understand. It would be could if it was styled with the same colors as in the editor

**Comment by KoBeWi** [comment]
The built-in documentation lacks formatting (there's already an issue created for that #27456), but it's visible in the online version.

**Comment by akien-mga** [comment]
Fixed by #29467.
