### ISSUE TITLE
Texture rotation in radians use same function as texture rotation degrees in Polygon2D

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29425]
**Godot version:**
3.2.dev.custom_build. a69436a

**Issue description:**  
![Zrzut ekranu z 2019-06-03 12-00-52](https://user-images.githubusercontent.com/41945903/58794241-0728aa80-85f8-11e9-8326-1fbcede4bdde.png)

**Comment by akien-mga** [comment]
That's weird as the bindings are correct, the bug might be in the documentation generator.

https://github.com/godotengine/godot/blob/7da9f28035c5caa94ba52da1807dfd95c74bf8c1/scene/2d/polygon_2d.cpp#L845-L846

Maybe the `PROPERTY_HINT_NONE, "", 0` messes things up.

**Comment by bojidar-bg** [comment]
This is probably caused by `DocData.merge_from` copying setters and getters, in addition to description.

https://github.com/godotengine/godot/blob/7da9f28035c5caa94ba52da1807dfd95c74bf8c1/editor/doc/doc_data.cpp#L138-L140

**Comment by akien-mga** [comment]
Oh so you mean it's the XML which is bogus and DocData doesn't properly fix it?

**Comment by akien-mga** [comment]
Just found that I had actually reported this a couple of years ago: #12476. :D
