### ISSUE TITLE
NotificationWmQuitRequest with alt+f4 gets invoked twice if mouse is made visible in handler

### ISSUE THREAD

**Issue by TheBlue-1** [godotengine/godot#29423]
**Godot version:**
3.1.1 Mono
using c#

**OS/device including version:**
Win 10 Edu
GTX 1060 max (notebook)

**Issue description:**
My cursor is captured normally,
When I recieve a NotificationWmQuitRequest, i open a popup and set cursor to visible and confined. It should just open and be usable with cursor.

But the NotificationWmQuitRequest gets called twice (one time the normal windows event, one time godots because mouse is captured) . So the popups "about to show" gets called twice and than the "about to hide" gets called (dont know why). In the "about to hide" the curser should be captured again so it does.

So the popup is opened but the cursor captured becouse the NotificationWmQuitRequest-handler gets called twice.

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/3246974/project.zip)

**Comment by neikeq** [comment]
Is this C#-only issue? If not, we should remove the `topic:mono` label.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, GDScript version of MRP would be useful.

**Comment by akien-mga** [comment]
No answer, so closing.
