### ISSUE TITLE
Request - Add docs for EditorInspectorPlugin

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#29438]
Missing docs:

- Methods
    - can_handle
    - parse_begin
    - parse_category
    - parse_end
    - parse_property
    - add_custom_control
    - add_property_editor
    - add_property_editor_for_multiple_properties

**Comment by williamd1k0** [comment]
This seems fixed since 325f6c6581ab4a22665ca59cd9859b6605a58841
