### ISSUE TITLE
String "[*]" is recognized as Array

### ISSUE THREAD

**Issue by Mandscharo** [godotengine/godot#29435]
**Godot version:** 3.1

**OS/device including version:** Windows 10

**Issue description:**
I wrote a method that loads multiple .json-files and puts them in a single dictionary.
In order to achieve this I´ve added a "[" at the beginng and a "]" at the end of the String to build an (JSON-)Array.
Now I get the following error-message:
"Trying to assign value of type 'Array' to a variable of type 'Dictionary'."

The following code results in the error:
`temp_res = ("[" + temp_res.substr(0, temp_res.length() - 1) + "]")
result = parse_json(temp_res)`

So does this:
`result = parse_json("[" + temp_res.substr(0, temp_res.length() - 1) + "]")`

And this:
`result = parse_json(temp_res.insert(0, "[") + (temp_res.substr(0, temp_res.length() - 1) + "]")`

**Steps to reproduce:**
1. Create a String
2. Add the brackets to it (your_string = "[" + your_string + "]"
3. Create a Dictionary (var dic = parse_json(your_string)

**Minimal reproduction project:**
Currently N/A

I checked the String-Documentation and couldn´t find a fix
This is my first submission, please correct me if I made a mistake.

The JSON-String built by my method:

> [{
	"id": "coal",
	"name": "Coal",
	"tags": ["R"]
},{
	"id": "cooked_meat",
	"name": "Cooked Meat",
	"tags": ["R", "H"]
},{
	"id": "iron",
	"name": "Iron",
	"tags": ["R"]
},{
	"id": "iron_ingot",
	"name": "Iron Ingot",
	"tags": ["R"]
},{
	"id": "leather",
	"name": "Leather",
	"tags": ["R"]
},{
	"id": "raw_meat",
	"name": "Raw Meat",
	"tags": ["R"]
},{
	"id": "stone",
	"name": "Stone",
	"tags": ["R", "C"]
},{
	"id": "stone_sword",
	"name": "Stone Sword",
	"tags": ["W"]
},{
	"id": "wood",
	"name": "Wood",
	"tags": ["R"]
},{
	"id": "wooden_shield",
	"name": "Wooden Shield",
	"tags": ["S"]
},{
	"id": "coal",
	"name": "Coal",
	"tags": ["R"]
},{
	"id": "cooked_meat",
	"name": "Cooked Meat",
	"tags": ["R", "H"]
},{
	"id": "iron",
	"name": "Iron",
	"tags": ["R"]
},{
	"id": "iron_ingot",
	"name": "Iron Ingot",
	"tags": ["R"]
},{
	"id": "leather",
	"name": "Leather",
	"tags": ["R"]
},{
	"id": "raw_meat",
	"name": "Raw Meat",
	"tags": ["R"]
},{
	"id": "stone",
	"name": "Stone",
	"tags": ["R", "C"]
},{
	"id": "stone_sword",
	"name": "Stone Sword",
	"tags": ["W"]
},{
	"id": "wood",
	"name": "Wood",
	"tags": ["R"]
},{
	"id": "wooden_shield",
	"name": "Wooden Shield",
	"tags": ["S"]
}]<

**Comment by bojidar-bg** [comment]
`parse_json` does not result in a Dictionary always, as you saw, but can also result in an Array. Ensure that there the type of your `result` variable is not `: Dictionary`, but either `: Array` or untyped.

**Comment by Mandscharo** [comment]
> 
> 
> `parse_json` does not result in a Dictionary always, as you saw, but can also result in an Array. Ensure that the type of your `result` variable is not `: Dictionary`, but either `: Array` or untyped.

Yeah I just realized.
What's weird about that, is that my method returns a Dictionary and returning the parse_json(string) doesnt result in an error... I´m kinda lost here...

**Comment by bojidar-bg** [comment]
Well, `parse_json` is marked as returning "Variant", or, in other words, anything. That's why you are allowed to return it, because it could be a Dictionary, and GDScript has no (simple) way of making sure it is one at compile time. Then, when it gets an Array at runtime, it just errors out, instead of silently returning the Array to the caller.

**Comment by Mandscharo** [comment]
> 
> 
> Well, `parse_json` is marked as returning "Variant", or, in other words, anything. That's why you are allowed to return it, because it could be a Dictionary, and GDScript has no (simple) way of making sure it is one at compile time. Then, when it gets an Array at runtime, it just errors out, instead of silently returning the Array to the caller.

Ok, got it.
I changed the JSON-Files to keyed-json and rewrote the method a little bit and now it works with dictionary, thanks for the help and sorry for the issue
