### ISSUE TITLE
AnimationTree TimeScale node shows incorrect previously set value

### ISSUE THREAD

**Issue by fogine** [godotengine/godot#29436]
**Godot version:**

`v3.1.1`

**OS/device including version:**

> Linux 5.1.6-arch1-1-ARCH

**Issue description:**

![img-2019-06-03-194902](https://user-images.githubusercontent.com/7884288/58823184-63f88500-8639-11e9-8653-0592186a98fb.png)

When you create `TimeScale` node as child of `BlendTree` node and set a value and then restart godot editor. The value is reset back to default `0` and can not be changed anymore at all. Workaround is to set the value in the `Inspector` tab which also shows correct value being currently set.

**Comment by asheraryam** [comment]
Another workaround is to rename the Timescale node to something else, since that forces a refresh somehow and allows you to change the values, but this needs to be done every time you traverse the node tree :b

**Comment by asheraryam** [comment]
This bug also happens with Blend2 and might happen with other nodes as well. i.e. I can't edit the blend integer value until I rename the blend2 node. I guess it might be something to do with the number not being refreshed in the UI properly and nothing more.
