### ISSUE TITLE
Draw Order: Lifetime is reversed on CPUParticles2D

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#29440]
**Godot version:**
3.1.1

**Issue description:**
Setting `draw_order` to "Lifetime" on Particles2D results in oldest particles drawn first, while the same setting on CPUParticles2D results in newest particles being drawn first.

See attached gif - both particle systems are configured identically, with `draw_order == DRAW_ORDER_LIFETIME`:
![particles_draw](https://user-images.githubusercontent.com/3812514/58826976-caa87f00-85f6-11e9-9843-44322b15b919.gif)

**Comment by clayjohn** [comment]
Should be as easy as reversing the sort here:

https://github.com/godotengine/godot/blob/197b65f32ac811f79bc5599fbfe8cf83914b6873/scene/2d/cpu_particles_2d.h#L119
