### ISSUE TITLE
Text undoing selects text

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#29450]
**Godot version:**
 774a9fd

**Issue description:**
When undoing typing operation in a `TextEdit`  and there's text after it, it will select said text:
![Peek 2019-06-03 20-19](https://user-images.githubusercontent.com/30739239/58840693-2bb36f80-8656-11e9-9095-11e258716f2c.gif)

**Comment by YeldhamDev** [comment]
CC @Paulb23

**Comment by akien-mga** [comment]
It also happens when undoing a paste btw.
