### ISSUE TITLE
Add RPC send_to_peers parameter

### ISSUE THREAD

**Issue by menip** [godotengine/godot#29457]
Would be nice to have syntactic sugar for 

    for id in send_list:
        rpc_id(id, "method", args ...)

For example, `rpc("method", args ..., peers=send_list)`. One question would be: for `sync` methods and properties, would they be called/updated locally when peer list is specified, or would you have to including the sending peers id in list? I would think it should still be called/updated locally. 

One (of multiple) use case: In attempt to reduce rpc/scenetree sync error, I've replaced all my rpc calls with above, including separate call locally. Would of been much nicer to just specify a third optional parameter.

**Comment by Faless** [comment]
I don't think there's much to be gained from this. If the use case is state syncing it would probably be better to work on Zoned RPCs and some kind of NetworkSync node.

For the remaining RPCs doing:
`for id in send_list: rpc_id(id, "method", args ...)`
doesn't change much in terms of coding I guess.

**Comment by mhilbrunner** [comment]
Closing as per Faless' comment above.
