### ISSUE TITLE
c# error can not create a cast from Node to spatial.

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#29456]
**Godot version:**
![Screenshot_6](https://user-images.githubusercontent.com/12847027/58844130-323ce980-864c-11e9-897b-f396e1c176ac.png)

**OS/device including version:**
windows 7 64 bits

**Issue description:**
**MiniVideo**
https://www.youtube.com/watch?v=hlwCk7yS3yU&feature=youtu.be
**proyect this video.**
[probandoGOdotC#.zip](https://github.com/godotengine/godot/files/3252523/probandoGOdotC.zip)
![Screenshot_6](https://user-images.githubusercontent.com/12847027/58846167-9fed1380-8654-11e9-92a9-c7ea67fef528.png)

English:
c # error can not create a cast from Node to spatial.
I was seeing that to access the properties of a node you have to access that node and do a casting to be able to change the properties, since apart from finding the node by name, we have access to the properties and how c # needs the type data in my case what I wanted to access is to rotate it.
The nodes "DO NOT have the rotation data type", that is, that property is part of SPATIAL.
However NO CASTING CAN BE MADE TO SPATIAL.
I was talking to the community boys in Spanish and they told me what can be done, it's more in the documentation they show that you can do casting to access the properties ...
HOWEVER YOU CAN NOT DO THE CASTING BETWEEN NODE TO SPATIAL ... Nothing is going to be a BUG or there is something I am doing wrong ..
I leave the images with ways of doing the casting.

Español:
c# error no se puede crear un casting de Node a spatial.
Estuve viendo que para acceder a las propiedades de un nodo hay que acceder a ese nodo y hacer un casting para poder cambiar las propiedades,ya que a parte de encontrar el nodo por el nombre,tenemos acceder a las propiedades y como c# necesita el tipo dato en mi caso lo que quise acceder es rotarlo.
Los nodos "NO tienen el tipo de dato rotación",osea esa propiedad es parte de SPATIAL.
Sin embargo NO SE PUEDE HACER EL CASTING DE NODO A SPATIAL.
Estuve hablando con los muchachos de la comunidad en español y me dijeron que se puede hacer,es más en la documentación muestran que se puede hacer casting para acceder a las propiedades...
Sin embargo NO SE PUEDE HACER EL CASTING ENTRE NODO A SPATIAL..Nose si sera un BUG o hay algo que estoy haciendo mal..
Dejo imágenes con formas de hacer el casting.

**Steps to reproduce:**
V1:
![Screenshot_7](https://user-images.githubusercontent.com/12847027/58844657-92cd2600-864e-11e9-9952-0aa49fbd22b2.png)
![Screenshot_9](https://user-images.githubusercontent.com/12847027/58844719-daec4880-864e-11e9-8474-faf3e9ef1fb9.png)

V2:
![Screenshot_8](https://user-images.githubusercontent.com/12847027/58844662-9791da00-864e-11e9-9f8a-00557762f7c9.png)
![Screenshot_9](https://user-images.githubusercontent.com/12847027/58844664-9b256100-864e-11e9-9c0c-22aaa0f56f7d.png)

![Screenshot_5](https://user-images.githubusercontent.com/12847027/58844668-a11b4200-864e-11e9-843f-98af950f1fb2.png)

**Minimal reproduction project:**
NOTE:
Almost all nodes have the type Spatial

**proyect old**
[probandoGOdotC#.zip](https://github.com/godotengine/godot/files/3250113/probandoGOdotC.zip)
**Video old**
https://www.youtube.com/watch?v=1AYAvk1ocgE&feature=youtu.be

**Comment by neikeq** [comment]
What is the type of the Node `cubo`? Can you upload an example project?

**Comment by kone9** [comment]
> What is the type of the Node `cubo`? Can you upload an example project?

If I upload it now it's a cube created with a node .

**Comment by kone9** [comment]
> What is the type of the Node `cubo`? Can you upload an example project?

I already uploaded a simple project with the example where I can not access the rotation by doing the casting, see above

**Comment by kone9** [comment]
> What is the type of the Node `cubo`? Can you upload an example project?

The node type is meshInstance and like most nodes it has the Spatial / Transform / rotation
![Screenshot_1](https://user-images.githubusercontent.com/12847027/58845531-ff95ef80-8651-11e9-96bb-039f663034b8.png)
![Screenshot_2](https://user-images.githubusercontent.com/12847027/58845532-ff95ef80-8651-11e9-9edf-69e28d339328.png)
![Screenshot_3](https://user-images.githubusercontent.com/12847027/58845533-002e8600-8652-11e9-9a65-64069cc23b0c.png)

**Comment by kone9** [comment]
**English:**
I found the solution boys ..
the problem was that I was confused since I thought that this worked as unity and that the spatial type was a component of all the objects, therefore if I wanted to convert any node into a spatial type it could not ... For some reason .. It would be nice to be able to implement it .. However when I put the type of object that really MESHINSTANCE since that is the type of node, I could access the spatial properties and rotate the cube .. If you want you can close the ISSUE, however it would be good to implement that casting from NODE to SPATIAL.
I leave a reference image.
and a mini video on YouTube showing how it works.

**Spanish:**
Encontre la solución muchachos..
el problema era que yo estaba confundido ya que pense que esto funcionaba como unity y que el tipo spatial era un componente de todos los objetos,por lo tanto si queria convertir cualquier nodo en un tipo spatial no se podia..Por alguna razón...Estaria bueno poder implementarlo..Sin embargo cuando puse el tipo de objeto que realmente MESHINSTANCE ya que asi es el tipo de nodo,pude acceder a las propiedades spatial y hacer rotar el cubo..Si quieren pueden cerrar el ISSUE,sin embargo estaria bueno implementar ese casting de NODE a SPATIAL.
Dejo una imagen de referencia.
y un mini video en youtube mostrando el funcionamiento.

![Screenshot_8](https://user-images.githubusercontent.com/12847027/58847631-15a7ae00-865a-11e9-815a-b4f313092883.png)
https://www.youtube.com/watch?v=ZJ7Z9hlTo84

**Comment by kone9** [comment]
English:
Mini video 3 ways to access a child node with c #
I show that if it is of type SPATIAL it does not work.

Spanish:
Mini video 3 formas de acceder a un nodo hijo con c#
muestro que si es de tipo SPATIAL no funciona.

https://www.youtube.com/watch?v=sYhXg0zsFNo&feature=youtu.be

![Screenshot_1](https://user-images.githubusercontent.com/12847027/58872542-a1412f00-869a-11e9-8459-a324a166a703.png)

**Comment by kone9** [comment]
English:
confirmed the BUG is when you want to access the NODOS of TYPE "SPATIAL" and create that casting
I also did the same with groups, but still giving error.
Mini video showing with groups and accessing a spatial object.

Spanish:
confirmado el BUG esta cuando queres acceder a los NODOS de TIPO "SPATIAL" y crear ese casting
tambien hice los mismo con grupos,pero sigue dando error.
Mini video mostrando con grupos y accediendo a un objeto de tipo spatial.

https://www.youtube.com/watch?v=hlwCk7yS3yU&feature=youtu.be

**Comment by neikeq** [comment]
Your class is named `Spatial` and you're doing the cast from within this class:

``` C#
using Godot;
using System;

public class Spatial : Godot.Spatial
{
  public override void _Process(float delta)
  {
      var player = (Spatial)GetNode("cubo");
      player.SetRotation(new Vector3(0,10 *delta ,0));
  }
```

Therefore it's picking your `Spatial` class instead of `Godot.Spatial`. To fix this, either rename your class (and the file name, remember it must match the class name), or use `Godot.Spatial for the cast:

``` C#
GetNode<Godot.Spatial>("cubo");
(Godot.Spatial)GetNode("cubo");
```

**Comment by kone9** [comment]
> Therefore it's picking your `Spatial` class instead of `Godot.Spatial`. To fix this, either rename your class (and the file name, remember it must match the class name), or use `Godot.Spatial for the cast:

Ok, ahora entiendo por que no funcionaba, muchas gracias.
