### ISSUE TITLE
tscn/tres: Inconsistencies in the extension filters of the save/open file dialogs

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2946]
In the current master branch (46c5fda), there are some inconsistencies in the listing of formats in the save and open file dialogs of the editor + project settings:

- In the project settings, the .tscn format is missing. *Fixed*

- In the "Open Scene" and "New Inherited Scene" dialogs, the filters are listed as:
![filter-open](https://cloud.githubusercontent.com/assets/4701338/11456556/fa690d2a-968c-11e5-92ed-5db612d8a45d.png)
  - TRES ( *.tres ) is missing (if RES is supported, I guess TRES would be too)
  - Since the new T-formats are meant to replace the XML-formats, they should probably be moved up in the list

- In the "Save Scene As.." dialog, the filters are:
![filter-save](https://cloud.githubusercontent.com/assets/4701338/11456569/4fc2be4c-968d-11e5-8c5c-de9911f4d6fd.png)
  - Here all formats are shown, but "*.tscn" is missing from the "All recognized" list while "*.tres" is there, which looks a bit weird.
  - Just like above, the T-formats should be moved up.
  - The order is different from the "Open Scene" dialogs where it was more natural: first the scene-specific format, then the general format. So it should be: SCN, RES, TSCN, TRES, XSCN, XML.

- For both dialogs, if we want users to start using T-formats preferentially over XML formats, maybe the XML formats could be removed altogether from the "All recognized" shortlist (but kept as available filters of course).

**Comment by reduz** [comment]
for scenes, tres is purposedly removed from the dialog, as that would just
save a compressed scene like xml instead of a descriptive one

**Comment by akien-mga** [comment]
> for scenes, tres is purposedly removed from the dialog, as that would just save a compressed scene like xml instead of a descriptive one

But actually tres is removed in the "open scene" dialog but present (and with a higher priority than tscn) in the "save scene" dialog.

**Comment by alketii** [comment]
Also when choosing the main scene which is a .tscn, it isn't recognized as a file extension.

**Comment by akien-mga** [comment]
I've had a quick look at this one but I get easily lost in the ```get_recognized_extensions``` logic, especially since the new text scene format is defined within scene/, while the binary and XML formats are in core/, so it's hard to define their ordering, etc.

**Comment by cochise** [comment]
In the dialog to select the `main_scene`, `*.tscn` is not available at all.

**Comment by akien-mga** [comment]
Non critical, but would be quite nice to fixed for 2.0 @reduz as we do want to push users towards using tscn over xscn (or to a lesser extent scn).

**Comment by djrm** [comment]
not junior job, seems impossible without ugly hacks or code restructuring

**Comment by akien-mga** [comment]
Would likely be fixed by #5467.

**Comment by akien-mga** [comment]
This has been fixed by #5467, later reverted but finally fixed for good :)
