### ISSUE TITLE
Autocomplete only works if not in a custom class

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#29466]
**Godot version:**
3.2 dev #33bcd9770

**OS/device including version:**
MacOSX but I'm sure this also happens in Windows

**Issue description:**
when you have a class that is a custom class the autocomplete stops working, for example:

```
extends Reference
class_name CustomClass

var a
var b
var c

func test(p_a, p_b, p_c):
    a = p_a # doesn't autocomplete
    b = p_b # doesn't autocomplete
    c = p_c # doesn't autocomplete

    var t: Array = []
    var t.push_back(a) # doesn't autocomplete (doesn't recognize array methods)
```

if I remove the `class_name CustomClass` everything works again.

**Comment by lupoDharkael** [comment]
https://github.com/godotengine/godot/pull/28099 is in master so I guess it should be fixed.

**Comment by akien-mga** [comment]
> #28099 is in master so I guess it should be fixed.

That's why a commit hash would be more useful than "last master", if that "last master" is indeed older than the merge of #28099 one day ago.

**Comment by xDGameStudios** [comment]
> > #28099 is in master so I guess it should be fixed.
> 
> That's why a commit hash would be more useful than "last master", if that "last master" is indeed older than the merge of #28099 one day ago.

sorry for that... I was not on my working PC
will update!
