### ISSUE TITLE
tscn format is missing from the filesystem panel

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2947]
Scenes saved in the tscn format do not appear in the filesystem panel. A potentially related issue is that they do not appear either in the "Quick Open Scene" (Ctrl + Shift + O) dialog. On the other hand they appear fine in the "Open Scene" dialog (Ctrl + O).

If the main scene is a tscn file, it seems however to appear fine in the filesystem.
*Edit:* Actually no, tscn files appear in the filesystem if they have been saved once during the session.

![tscn-fs](https://cloud.githubusercontent.com/assets/4701338/11456596/6e762832-968e-11e5-9d47-686cafb57587.png)
![tscn-fs1](https://cloud.githubusercontent.com/assets/4701338/11456601/849c5aaa-968e-11e5-9da5-3b010291a049.png)
![tscn-fs2](https://cloud.githubusercontent.com/assets/4701338/11456602/86ac64d4-968e-11e5-9a0d-e4f1ea8197c3.png)

**Comment by kubecz3k** [comment]
The same behaviour here on 68d3438a9351498909ffa0bfe79f51b74004e906 build
