### ISSUE TITLE
Double popup bug

### ISSUE THREAD

**Issue by vaporlain** [godotengine/godot#29478]
**Godot version:**
(EDIT) 3.1.1 stable

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
I had to force quit Godot because of a bug. This is why and how it happened.

I made an Area node (Spatial), I clicked to change its name, deleted the text, but I couldn't think of a good name. So I clicked on the warning, the one that says that you have to add a collision shape. This resulted in getting 2 popup notices at the same time, bugging the engine and forcing me to shut it down without saving my progress. 

**Steps to reproduce:**
Make Area 2D and delete the name, then click on the warning button (the one that says that there is no collision shape)

_This isn't a big issue, or something that should be prioritized. I am aware of that, but as they say in my country, every little bit helps._

**Comment by KoBeWi** [comment]
> 3.2 stable

An issue from the future ( ͠° ͟ʖ ͡°)

Happens in 3.1.1 stable too and results in editor freezing.

**Comment by NilsIrl** [comment]
I tried it and for some reason, Godot starts to have 100% CPU usage during the crash.

**Comment by NilsIrl** [comment]
But this high CPU usage only starts after you click on the UI (anywhere) after confirming (clicking on OK) the first Warning box "No name provided."

**Comment by NilsIrl** [comment]
So to crash the editor you have to:
1. Create an Area2D node
2. Double click on the name (to rename)
3. Backspace to remove all the name
4. Click on the warning sign "This node has no shape"
5. Click anywhere apart from the Warning box (You can click on the warning box, including moving it, but it won't crash yet)
6. 100% CPU usage glhf
