### ISSUE TITLE
All materials are extremely reflective on android

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#29475]
**Godot version:**
3.2.dev.calinou.a25e52fb7

**OS/device including version:**

Android, Tested on Samsung Galaxy J5 duos + Oukitel K6000 pro GLES2

**Issue description:**
It seems all materials are extremely reflections on the current master build on Android.

Herre is how a basic scene looks on 3.1.1 stable:

![](https://i.imgur.com/cS61Rau.png)

And here on the master build 3.2.dev.calinou.a25e52fb7

![](https://i.imgur.com/oewToK7.png)

**Steps to reproduce:**
- Create a basic scene with a few meshes and a directional light source and run in on android

**Minimal reproduction project:**
[ReflectiveMaterials.zip](https://github.com/godotengine/godot/files/3252975/ReflectiveMaterials.zip)

**Comment by mbrlabs** [comment]
Same here with Galaxy S8, Android 9 and GLES2 Backend. 
I tracked the issue down to commit 5c252092e17a563b54b9c9bcb88127af102926e2 (#27898).
@clayjohn could you have a look?

**Comment by lawnjelly** [comment]
I may have had this issue too, so far I have been fixing by turning off the checkbox 'Force Vertex Shading.mobile', which may be a workaround until it gets fixed (albeit more expensive shaders).

**Comment by mbrlabs** [comment]
That workaround produces the expected result. I just noticed that you can reproduce this issue on desktop as well if you check "Force Vertex shading"

**Comment by clayjohn** [comment]
@mbrlabs I'll take a look!
