### ISSUE TITLE
Project exported to HTML5 doesn't run due to Emscripten requiring `dlopen()` support

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#29480]
**Godot version:** Git https://github.com/godotengine/godot/commit/e22dde1b18657158510cead4fd3c202045640935

**OS/device including version:** Fedora 30, Emscripten 1.38.34

**Issue description:**

When running a project exported with a self-compiled HTML5 release template, I get the following message:

```
abort("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking"). Build with -s ASSERTIONS=1 for more info.
```

Full console log:

```
Godot Engine v3.2.dev.custom_build.e22dde1b1 - https://godotengine.org Low-Resolution Rendering.js:7:38838
OpenGL ES 2.0 Renderer: Mozilla Low-Resolution Rendering.js:7:38838
To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking Low-Resolution Rendering.js:7:329614
To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking Low-Resolution Rendering.js:7:329624
exception thrown: abort("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking"). Build with -s ASSERTIONS=1 for more info. Low-Resolution Rendering.js:7:328618
abort("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking"). Build with -s ASSERTIONS=1 for more info. Low-Resolution Rendering:241:13
**ERROR**: Condition ' !_start_success ' is true. returned: false Low-Resolution Rendering.js:7:39107
   At: main/main.cpp:1296:start() - Condition ' !_start_success ' is true. returned: false Low-Resolution Rendering.js:7:39107
81 Low-Resolution Rendering.js:7:329614
81 Low-Resolution Rendering.js:7:329624
uncaught exception: abort(81). Build with -s ASSERTIONS=1 for more info.
```

The project uses GLES2 and is run with a local Web server in Firefox 67.0. I get the same error with an export template compiled in debug mode.

**Steps to reproduce:** Build an HTML5 export template.

**Minimal reproduction project:**

- Project files: [godot-viewport-upscaling-demo.zip](https://github.com/godotengine/godot/files/3253538/godot-viewport-upscaling-demo.zip)
- HTML5 debug: [low-res-rendering_debug.zip](https://github.com/godotengine/godot/files/3253528/low-res-rendering_debug.zip)
- HTML5 release: [low-res-rendering_release.zip](https://github.com/godotengine/godot/files/3253515/low-res-rendering_release.zip)

**Comment by Faless** [comment]
Seems related to GLES2 only. Why do we need dlopen for GLES2?
https://github.com/godotengine/godot/blob/65c211d30325b4d4573cb049508d3d59ecff6214/drivers/gles2/rasterizer_storage_gles2.cpp#L5611

**Comment by akien-mga** [comment]
That code assumes that `!GLES_OVER_GL && !IPHONE_ENABLED` is Android, but it forgets that HTML5 is also `!GLES_OVER_GL`.

`libGLESv2.so` used indeed not to be linked directly on Android but `dlopen`'ed. It was added to the linker command in a3d5aec68d so this should no longer be needed I assume.

But I think it was backwards in the first place. It doesn't really make sense to hardlink `libGLESv3.so` and `dlopen` `libGLESv2.so`, as almost all devices have the latter but some might lack the former (so it seems like currently you couldn't ship a GLES2 game on a phone that doesn't include `libGLESv3.so`?). We should probably hardlink `libGLESv2.so` and `dlopen` `libGLESv3.so` instead.

**Comment by akien-mga** [comment]
Ah I misread, this code was actually *added* in a3d5aec, CC @clayjohn. It's `dlopen`'ed to extract the relevant symbols from it.

**Comment by clayjohn** [comment]
Should be enough to just wrap it in a ``#ifndef JAVASCRIPT_ENABLED``. Will make a PR.
