### ISSUE TITLE
tscn/tres: Can't open tileset source scene nor use exported tileset resource in tscn/tres formats

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2948]
I can't say for sure that this is related to tilesets, or if it's just that my tileset scene happens to use a feature that the tscn/tres parser does not handle properly.

To reproduce the issue, you can clone: https://github.com/akien-mga/dynadungeons

There is already a scenes/tileset.tscn file there that Godot is not able to open. Alternatively, you can open scenes/tileset.xscn and save it as .tscn, it should produce the exact same non-usable file.

Regarding the resources, sprites/tileset.xml was saved as sprites/tileset.tres, and the latter does not work when trying to load it in-game (change the resource path in scenes/level.tscn to test).
Reexporting the tileset from scenes/tileset.xscn to a new sprites/tileset.tres produces the exact same result, so at least the conversions seem to work fine, but the format is not OK for the engine.

**Comment by kubecz3k** [comment]
I can confirm this issue on 68d3438a9351498909ffa0bfe79f51b74004e906 build
It's enought to use empty tilemap node as a scene root, after saving it to tscn it's impossible to reopen this scene in editor.
Quick proof video: https://youtu.be/cxNNHz5bu4o
(the editor crash in vid is not related with tscn format)

**Comment by akien-mga** [comment]
Awesome! Will give it a try.

**Comment by blurymind** [comment]
this bug is still present in 2.0.1 which is supposed to be stable

**Comment by akien-mga** [comment]
Please open a new issue, this bug has clearly been fixed, so if you have an issue with tscn/tres and tilemaps, it's likely due to a different cause. Also not sure how to interpret your *supposed to be stable*... Feel free to fix bugs and make pull requests if it's not stable enough for you.
