### ISSUE TITLE
Godot c # variables export with between classes does not work

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#29486]
**Godot version:**
![Screenshot_2](https://user-images.githubusercontent.com/12847027/58900530-b4bdbb80-86d5-11e9-8567-cf6363696a2a.png)

**OS/device including version:**
windows 7 64 bits.
![Screenshot_3](https://user-images.githubusercontent.com/12847027/58900601-dcad1f00-86d5-11e9-887f-5f553ee68c7c.png)

**Issue description:**
I want to use a global variable from the editor.
I have that variable in 2 different classes, since one is like a singleton to use from any class and the other class is the one that accesses that variable
![Screenshot_4](https://user-images.githubusercontent.com/12847027/58900788-34e42100-86d6-11e9-80ae-267ab9a2d094.png)
The issue is that if I change the value of the variable in the editor it does not work, the value is not changed. I do not understand why this happens, if with GDscript it can work in this way.
![Screenshot_5](https://user-images.githubusercontent.com/12847027/58900890-6826b000-86d6-11e9-8af0-f6efa5b46f1c.png)
![Screenshot_6](https://user-images.githubusercontent.com/12847027/58900917-770d6280-86d6-11e9-8ce2-48a59cc8f5be.png)
I also want to report that it works quite badly when clicking on the variable in the editor and that when running the application the remote works quite badly.

**Spanish:**
Quiero usar una varible global desde el editor.
esa variable la tengo en 2 clases difentes,ya que una es como un singleton para usar desde cualquier clase y la otra clase es la que accede a esa variable
El tema es que si cambio el valor de la variable en el editor no funciona,no se cambia el valor.No entiendo porque pasa esto,si con GDscript puede funcionar de esta forma.
Tambien quiero reportar que funciona bastante mal a la hora de hacer click arriba de la variable en el editor y que  al ejecutar la aplicación el remote funciona bastante mal.

**Steps to reproduce:**
Video
https://www.youtube.com/watch?v=oRVRl6K6NG4&feature=youtu.be
https://www.youtube.com/watch?v=ll4ftN9Y6S0&feature=youtu.be

**Minimal reproduction project:**
https://drive.google.com/open?id=127cqqOOXDCwVKsnwuDnCgz32Ek3nY9uJ

**Comment by kone9** [comment]
con gdscript podia hacer GetParent y buscar la variable de la clase superior.
![Screenshot_2](https://user-images.githubusercontent.com/12847027/58954107-9b1c8280-876e-11e9-83f6-b2241f60aa8b.png)

but with c # it does not work and it is extremely useful.
in this way with GDscript it worked with the export variables
![Screenshot_4](https://user-images.githubusercontent.com/12847027/58954213-e46cd200-876e-11e9-9266-e5e5b5e951f8.png)

**Comment by kone9** [comment]
Well I found the solution and I'm going to do a tutorial the problem was that I had to put the type of data, so if we put the getparent like that.
![Screenshot_6](https://user-images.githubusercontent.com/12847027/58954889-cacc8a00-8770-11e9-9382-9cc6267da1d0.png)

Now I check in the other class that I have the reference to that variable
![Screenshot_7](https://user-images.githubusercontent.com/12847027/58954956-01a2a000-8771-11e9-8e2b-7475c55e8fc1.png)


And so I could use higher class variables working the export ..
An important issue is that this can only be called from within a function; therefore, if we want to use it in a variable, we must declare it within the function where we use it.
![Screenshot_8](https://user-images.githubusercontent.com/12847027/58955088-59410b80-8771-11e9-83a1-2cce5770262f.png)

**Comment by kone9** [comment]
SOLUTIONFINAL:
https://www.youtube.com/watch?v=F3UBoa0pm9I&feature=youtu.be

**Comment by Far-offmui-x-data-grid** [comment]
> SOLUTION FINAL: https://www.youtube.com/watch?v=F3UBoa0pm9I&feature=youtu.be





https://elevatedsherlock674.github.io/IOReqsGO5wQIffE8O5lLkUS-rGkQVmwjVabTxeEd/
