### ISSUE TITLE
KinematicBody (3D) moves wrong when its parent's translation is not (0,0,0)

### ISSUE THREAD

**Issue by gokudomatic** [godotengine/godot#2949]
Let say we have:
- a spatial as the world
- a static body as the map 
- a kinematic body as the player

The player collides with the map with the method move(motion), so it doesn't get through walls and the ground. If the root node, the world, has a translation = (0,0,0), everything is fine. But if it has a translation (x,y,z), everytime the player enters in collision with the map, for instance at the landing of a jump, the player suddenly moves with the translation of its parent, the world. So, if the world has a translation (1,0,0), the move method from the kinematic body will add this (1,0,0) to the kinematic body, but only when it detects a new collision with something else. This bug doesn't happens when there was already a collision (like standing on the ground because of gravity) or when there's no collision (falling or flying).

Also if the kinematic body has multiple parents, the sum of the parents' translation is the distance the body will move. Therefore it moves according to the absolute translation of the immediat parent of the kinematic body. Adding an intermediate spatial node with translation=(0,0,0) is useless. And setting the root node's translation to (0,0,0) doesn't matter either if one parent of the kinematic body has a translation not (0,0,0).

The obvious workaround is to insure that every parent of kinematic nodes has a translation = (0,0,0). But it can be quite inconvenient, especially for mobs.

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
