### ISSUE TITLE
Some shortcuts are hard-coded in TextEdit

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#29490]
**Godot version:**
3.1.1

**Issue description:**
I remember seeing similar issue (maybe), but can't find it now. Anyways, I was looking how #27164 could be implemented and thought that it would make sense if MenuButton shortcuts allowed for echo events. Not all of course, but for stuff like moving or duplicating lines that would be useful.

Then I noticed that some actions, like undo or paste, already support that. Tracking down the code, these actions are hard-coded in TextEdit. There are few problems with that. We can already remap actions like paste to another shortcut and it changes in script editor menu (but not the right-click menu of TextEdit, which is part of script editor). But doing this, we end up with 2 shortcuts for the same action, with one of them working as intended and the new one not supporting continuous actions.

So these actions should somehow be changed to proper shortcuts and also shortcuts should support optional echo events, so everything works the same, but is cleaner and allows improving other actions with continuous activation.

**Comment by Paulb23** [comment]
I think you're looking for #12164?

**Comment by KoBeWi** [comment]
No, I think it was a different one. Still, it didn't had the echo part, so even if similar issue exists, it's not exact duplicate.
