### ISSUE TITLE
 Script inherits from native type 'Position3D', so it can't be instanced in object of type: 'ScriptEditorDebuggerInspectedObject'

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#29506]
**Godot version:**
3.1.1.

**OS/device including version:**
Ubuntu 18.04 LTS

**Issue description:**
Getting the above error when inspecting things in remote scene tree.

**Steps to reproduce:**
Remote scene tree, click on certain nodes (e.g. root/Node2D/Node2D or any of the Road .../ Road_instance0 nodes)

**Minimal reproduction project:**
https://github.com/Zireael07/2DFreeRoamRacerRoguelike (doesn't suffer from the other issue)

**Comment by Zireael07** [comment]
ETA: I am seeing it in quite a lot of scenes, in fact - but not all of them.
Might be relevant: the project has been upgraded several times (3.0.3 to 3.1 alpha to 3.1 official to 3.1.1)

**Comment by Zireael07** [comment]
Also, this is not specific to any one type - I have seen it with Spatial and Position3D so far.

**Comment by Zireael07** [comment]
Not limited to 3D either, I just saw it with 2D nodes too in a separate project that I don't believe went through as many upgrades.

Aha! I think I see the common pattern: I believe ALL the nodes I'm seeing the error on are using 'tool' scripts!

**Comment by samdze** [comment]
Can confirm, the error appears when I select a node with a C# script using [Tool] in the remote tree.
And no script exported property is being shown in the inspector, even if the script is not [Tool].
