### ISSUE TITLE
It's not possible to determine the rect_size of children in GridContainer

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#29505]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

Since there is a margin between each child in the GridContainer, and the size of margin is unknown, it's impossible to calculate the size of the child to fill the Grid with a fixed size.
For example, the width of my GridContainer is 640, its columns is 4, and I want the children fill the grid, I set the rect_min_size.x of the child to 160, the final size of the Grid will bigger than 640.
Suggestion:
The margin between the children can be set to a determined value. 

**Steps to reproduce:**

**Minimal reproduction project:**
<img width="1013" alt="Screen Shot 2019-06-05 at 7 05 34 PM" src="https://user-images.githubusercontent.com/1130047/58956866-03e91680-87d2-11e9-8a1b-1338fc34c952.png">

**Comment by KoBeWi** [comment]
You can customize the "margin" via separation variables in theme constants.
![image](https://user-images.githubusercontent.com/2223172/58979218-d00bf200-87cd-11e9-8e08-674c6279f888.png)

**Comment by groud** [comment]
As pointed out by @KoBeWi , there is a default margin with grid containers which you can override using custom constants.

**Comment by alexzheng** [comment]
I have not changed this value ,its value is 0, but there is still a 4 pixel margin between children.

**Comment by groud** [comment]
> it's OK.

Did it ticking the boxes solve the problem?
I see from my emails you, edited the message saying it wasn't working. If so that's a big.

**Comment by alexzheng** [comment]
after check that option on, it works.
The default value is 0 and it is not checked on, but it leaves a 4 pixels margin, it's a little confusion without your reminder.
