### ISSUE TITLE
Add description of custom signal with params to documentation

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot#29501]
**Documentation URL: [Custom Signals]**(https://docs.godotengine.org/en/latest/getting_started/step_by_step/signals.html#custom-signals) 

**Problem:** 
Current documentation does not include sufficient description of custom signals, i.e. there are no mentions of the ability to create signals with parameters.  

**Solution:**
Add `signal my_signal_with_arguments(x, y)` to documentation. 

**BONUS:**
Clarify the explanation of the emit_signal("signal", ...) function by explaining where the varargs parameters originate from and how they are connected to a custom signal with parameters.

_extra rant
I've had to scour the internet to get a decent explanation about Godot signals functionality and to be honest, it's just ridiculous how bad the documentation in general is. If you got to direct your funds anywhere, please start by improving the documentation._

**Comment by ShraddhaDevaiya** [comment]
Hello, this issue is resolved , it is already added. @aspenforest and @bruvzg , can you please close this issue?

**Comment by Calinou** [comment]
Closing per https://github.com/godotengine/godot-docs/pull/2883#issuecomment-558079941.
