### ISSUE TITLE
json file don't display on res manager

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29507]
file don't display in Godot, but can read
> var file = File.new()
file.open("res://assets/data/stage.json",file.READ)
var json = parse_json(file.get_as_text())
print(json)

![](https://user-images.githubusercontent.com/1890538/58963429-b4a9e280-87df-11e9-8a5e-d3ce3696d65a.png)

**Comment by mrcdk** [comment]
The filesystem dock only shows imported resources (files that are recognized by godot as a resource) JSON, txt, xml,... Aren't recognized resources for godot and it won't show them in the filesystem dock.

You are able to read them with the File API but take into account that you'll need to add those files manually when exporting or they won't be added to the pck file

**Comment by zszen** [comment]
> The filesystem dock only shows imported resources (files that are recognized by godot as a resource) JSON, txt, xml,... Aren't recognized resources for godot and it won't show them in the filesystem dock.
> 
> You are able to read them with the File API but take into account that you'll need to add those files manually when exporting or they won't be added to the pck file

Thank you. Important notice.
