### ISSUE TITLE
[OSX] Curly brackets { } and @ symbol not working in the inspector

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#29509]
**Godot version:**
3.2 build #197b65f32

**OS/device including version:**
MacOSX Mojave

**Issue description:**
Upon exporting a String to the inspector if you try to enter a `{`  `}` or a `@` you can't, my guess is that it happens due to keyboard layout. I'm from Portugal and to input those symbols I need to press `option + shift + 8` `option + shift + 9` and `option + shift + 2` respectively so the key combination must be being considered as a short-cut instead.

**Comment by bruvzg** [comment]
Should be fixed by #29498 (LineEdit was ignoring all symbols entered with Alt/⌥).
