### ISSUE TITLE
Error getting image from URL - can this be omitted ?

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#29502]
**Godot version:**
3.1.x / 3.2

**Issue description:**

![image](https://user-images.githubusercontent.com/3036176/58897330-b781d600-8700-11e9-9eb2-b02876c8a010.png)

I think this warning can be safely removed, to not confuse the users ?

**Comment by Faless** [comment]
I humbly disagree, it helps both the user reporting problems with the assets lib and us keeping track of which assets are at least partially broken. See #27050 and #27117 .

**Comment by Chaosus** [comment]
Yeah, its not neccessary, I just thinked this warning absolutly have not dependents on user actions and that is not a correct behavior.

**Comment by Faless** [comment]
It's still a relevant information though. because something *is* wrong, and keeping the user in the dark does not seem to be the right thing to do either.
Maybe we can add a note to broken asset in the list, or some kind of `!` button with a popup showing the warning.

**Comment by Calinou** [comment]
I agree the current icon display needs some improvements too. We should display a "loading" icon while an icon is loading, and a "warning" icon if an asset icon failed to load (this doesn't mean the asset is broken, though).

**Comment by Calinou** [comment]
Closing, as the current behavior is expected. We want to be aware of broken icon paths so they can be fixed :slightly_smiling_face:
