### ISSUE TITLE
GDScript can't be singleton 

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29510]
**Godot version:**
3.1

**OS/device including version:**
macOS, runing inside of Godot

**Issue description:**
Singleton class don't be instance/create when run app.
But It create a Node with script, binding the node file with singleton. It works.
Here is the tip: https://docs.godotengine.org/en/3.1/getting_started/step_by_step/singletons_autoload.html?highlight=singleton

**Steps to reproduce:**
1. create a gdscript file, extends Node
2. add the class to "AutoLoad"
3. run game
4. stright typing the class name or get_node all don't get the object.

![Snip20190605_58](https://user-images.githubusercontent.com/1890538/58971487-25f09200-87ee-11e9-846a-6c4f9e1807ce.png)

**Minimal reproduction project:**

**Comment by MuffinManKen** [comment]
What are your settings on the Autoload tab?

**Comment by zszen** [comment]
@MuffinManKen  here the snap
![image](https://user-images.githubusercontent.com/1890538/58977780-f8f7ab80-87fc-11e9-84b9-645a47196277.png)

**Comment by KoBeWi** [comment]
Are you maybe using it in a tool script? Does it also happen in 3.1.1?

**Comment by zszen** [comment]
@KoBeWi What's mean "tool script" ? I use whitch version from official website statble ver3.1

**Comment by KoBeWi** [comment]
Well, if you don't know what is a tool script, then I doubt that's the problem xd
Another possibility is that your script has some error, so it can't compile, so it can't be recognized as singleton.

A reproduction project would be helpful, because it works for me (I even tested with the same name/path).

**Comment by zszen** [comment]
@KoBeWi 
Originally I will create a simple project for this bug. But I found that all is works well either new project or my game.

Maybe it cause by app some where crashed. Sometimes I run my code with strange error. But I can't found wrong code. Then I restart the app and it works well.

**Comment by zszen** [comment]
Now I know that the Singleton gdscript forbid add "class_name" keyword

**Comment by KoBeWi** [comment]
Ok, first thing: it doesn't make much sense to make a singleton with `class_name`. Well, it's practical if you want to make more instances of the singleton (then it's not singleton) or use it as argument somewhere and need a type name (you don't do that with singletons).
Second, if for whatever reason you want it, it should be possible, but make sure the singleton name is different than class name.

On Godot's side, this should probably result in some warning or error. (btw, I still can't reproduce your exact problem)

**Comment by zszen** [comment]
@KoBeWi Thanks
