### ISSUE TITLE
Array find and has api don't work when data from json

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29513]
**Godot version:**
3.1

**OS/device including version:**
MacOS, internal runing test

**Issue description:**
I save config to local with json and load it back next time. I found that the array object can't check unit with "find" or "has" api

**Steps to reproduce:**
1. read json file from user:// path and parse success.
2. get an array from dic which from jsondata.result
3. check if the array contain some data
4. result is always false or return -1
...
5. I then do manual loop check, the value can compare and can check it exist

**Minimal reproduction project:**
right code:
```
 if not dic.has(key):
	dic[key] = []
var arr:Array = dic[key] as Array
var isContain:=false
for k in arr:
	if k==value:
		isContain = true
		break
if not isContain:
	arr.append(value)
	saveData()
```
wrong code : (always save the same data)
```
 if not dic.has(key):
	dic[key] = []
var arr:Array = dic[key] as Array
var isContain:= arr.find(value)>=0 # arr.has(value)
if not isContain:
	arr.append(value)
	saveData()
```
dic defined:
```
var dic:Dictionary = {}

func _ready():
	saver.open("user://savegame.save", File.READ)
	var data = JSON.parse(saver.get_as_text())
	saver.close()
	if data!=null && data.result!=null:
		dic = data.result
```

**Comment by zszen** [comment]
maybe I save the number , it read back to string ?

**Comment by zszen** [comment]
I wrote a custom 'has' api:
```
func arrContain(arr:Array, value)->bool:
	var type = typeof(value)
	for k in arr:
		if typeof(k) == type:
			if k==value:
				return true
	return false
```

**Comment by Calinou** [comment]
> I save config to local with json and load it back next time.

You should use the [ConfigFile](https://docs.godotengine.org/en/latest/classes/class_configfile.html) class to store user configuration, it's specifically intended for that purpose. JSON can do it, but it's simpler with ConfigFile :smiley:

**Comment by zszen** [comment]
@Calinou  thank you very much  <3

**Comment by KoBeWi** [comment]
The problem was probably that any number parsed from JSON is a float and you used find/has with integer.

**Comment by zszen** [comment]
@KoBeWi 
After restart the app. the Array api is works well. Maybe cause by app memory leak.
