### ISSUE TITLE
OS window title does not support non-ascii characters

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2952]
Trying to setup a new project with e.g. "Rémi" as project name, the window title appears as "RÃ©mi", typical encoding issue.

The corresponding project name appears however fine in the project settings or engine.cfg.

Seen on Linux X11.

**Comment by akien-mga** [comment]
Found a potential fix based on this code: http://mupdf.com/doc/browse/platform/x11/x11_main.c
I just blindly copied what is does and did not try to do some checks to see if UTF-8 is allowed or not, so I'm not making a PR out of it, I'd prefer an X11 expert (@reduz, I know you love the X11 API) to have a look at it :) It does work for me.
```
diff --git a/platform/x11/os_x11.cpp b/platform/x11/os_x11.cpp
index 74ebad7..95da3b7 100644
--- a/platform/x11/os_x11.cpp
+++ b/platform/x11/os_x11.cpp
@@ -577,6 +577,7 @@ Point2 OS_X11::get_mouse_pos() const {
 
 void OS_X11::set_window_title(const String& p_title) {
        XStoreName(x11_display,x11_window,p_title.utf8().get_data());
+       Xutf8SetWMProperties(x11_display, x11_window, p_title.utf8().get_data(), p_title.utf8().get_data(), NULL, 0, NULL, NULL, NULL);
 }
 
 void OS_X11::set_video_mode(const VideoMode& p_video_mode,int p_screen) {
```

**Comment by akien-mga** [comment]
Looks like the change above is a bit overkill, though it works. Another possibility would be to set _NET_WM_NAME as specified in the FreeDesktop spec: http://standards.freedesktop.org/wm-spec/wm-spec-1.4.html#idm139915845226624

**Comment by akien-mga** [comment]
On the other hand the above change works well, and apparently all parameters that are NULL are just ignored (so their current values are not changed), so basically this long command only sets the new window title in UTF-8. I'll make a small pull request with it for the time being.

**Comment by akien-mga** [comment]
Closed my PR as I sync setting _NET_WM_NAME is really the way to go.
Here is the code that SDL2 uses, we could use it as a reference: http://code.metager.de/source/xref/SDL/2.0/src/video/x11/SDL_x11window.c#667

**Comment by reduz** [comment]
i can' t believe so much code needs to be done to change the window title

**Comment by reduz** [comment]
PR welcome, i don' t understand how to get NET_WM_NAME :|
