### ISSUE TITLE
Crash caused when calling `remove_collision_exception_with` on body queued for deletion with `queue_free`

### ISSUE THREAD

**Issue by Razzlegames** [godotengine/godot#29524]
**Godot version:**
Godot_v3.1.1-stable_win64

**OS/device including version:**
Windows 10 Pro
Version: 1803

**Issue description:**
Apologies, if this is a duplicate, but I couldn't find any issues that matched exactly.  This issue doesn't occur in Godot 3.0, only 3.1 so far.

Calling `queue_free` on a physics body that is held in another object (as a reference) causes a crash on calling `remove_collision_exception_with`

> Invalid type in function `remove_collision_exception_with` in base 'RigidBody2D (QueueFreeCrashTest.gd)'. Cannot convert argument  1 from Object to Object

- I was also able to reproduce by just iterating through objects in a list where one was in `queue_free` state, likely a few frames later, after being queued.  It appeared to crash before ever getting to any operation on the queued objects, but I am unable to reproduce as a small project as the moment.  

The use case here is:
- Player is hit by enemy
- Put all colliding enemies in list and add a collision exception with them (so you can pass through them)
- After a timer expires, we remove the collision exception and remove from the list
- Sometimes, during this timer's lifecycle, the enemy might be killed by something else. Thus the `enemy.queue_free` is called

Of course there are many work arounds, e.g. currently I just trap with a timer in the enemy with 
```gdscript
yield(get_tree().create_timer(4, true), "timeout")
```

This is fine for now, and avoids the race condition.  But I think `queue_free` should be safe, at the trade-off of the app programmer introducing memory leaks?

**Expectation**
Calling an operation on a node scheduled for deletion would be a no-op, or would run on the object if it makes sense etc.

**Steps to reproduce:**
Run this project: https://github.com/Razzlegames/GodotQueueFreeCrashOn3.1
Just main scene is fine (which is automatic, but `QueueFreeCrashTest.tscn`).

**Minimal reproduction project:**
 https://github.com/Razzlegames/GodotQueueFreeCrashOn3.1

**Comment by avencherus** [comment]
Glancing at the code, I would say it looks very likely to be a bug with how `yield` is being used, and expected within the current design.  It would be nice though if they had more meaningful crashes, which looks to be what this PR is aiming to address:  https://github.com/godotengine/godot/pull/28884

I could be wrong, I wouldn't have time to step through it, but if is, the following is what may be happening in your example.

1. The processing will happen before the object is finished freeing, and yields are made into the SceneTree with timers.
2. The object goes free in the following frame.  (1/60th of a second).
3. Those timers end a half second later and fire signals to resume the yield on those functions.
4. The object doesn't exist anymore.
5. With nothing to return to the function callback can't be done on a null object, and you get a crash.

**Comment by Razzlegames** [comment]
That seems logical.  Perhaps the fix is not to pend the final object `delete` until after all coroutines have exited.

**Comment by Razzlegames** [comment]
I not as familiar with this, but perhaps in this section a check for pending state can take place: 
https://github.com/godotengine/godot/blob/master/scene/main/scene_tree.cpp#L1113-L1125

Assuming it is what you mentioned, of course.

**Comment by KoBeWi** [comment]
In 3.2.3 rc1 the error says that parameter is null, which is correct, because the node was removed (and you can easily track the error source). Coroutines and freed objects is another problem which is not the topic of this issue, so closing as resolved.

**Comment by Razzlegames** [comment]
Does it crash though?  Also, is the parameter really `null`?  I'd think it was just queued for delete and not `null`, as the reference is never changed.  

I'll have to try on `3.2.3 rc1`.  If it does crash I still don't think that's correct behavior.  If it logs an error and continues (typical `release` type behavior) I think it's acceptable.

**Comment by KoBeWi** [comment]
> Also, is the parameter really null? I'd think it was just queued for delete and not null, as the reference is never changed.

The method call happens *after* the object is freed, at which point the reference points to a freed object (null).

**Comment by Razzlegames** [comment]
> the reference points to a freed object (null).
This isn't typically how languages (where you manage memory yourself) work, though.  That's my confusion . Typically this means the reference/pointer/etc points to garbage at that point.

**Comment by KoBeWi** [comment]
> Typically this means the reference/pointer/etc points to garbage at that point.

Well, this would cause a legit crash. GDScript has some safe-guards against invalid references. I think it used to be reported as [deleted object], but now it's just null.

**Comment by Razzlegames** [comment]
Thanks.  OK that's good, so that makes me think there's still some state that exists about the object at that point (meta data wrapper etc, I'd have to study code to know). 

So it sounds like it's expected for anyone that holds a `Node` reference, that we should be trapping any kind of `signal`s related to `free` for that node, to purge these references.  The best place I can find for knowing when a `Node` is `queue_free`ed is using `Node` `signal tree_exiting`.

Is there a better place for this?

**Comment by KoBeWi** [comment]
> The best place I can find for knowing when a Node is queue_freeed is using Node signal tree_exiting.
Is there a better place for this?

There's also NOTIFICATION_PREDELETE, but you can use it only in the node that is going to be deleted (unless you emit a custom signal when this happens).
