### ISSUE TITLE
Editor freeze when selecting context menu item with LMB while holding RMB

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#29521]
**Godot version:**

3.1.1.stable.official

**OS/device including version:**

Debian Testing GNU/Linux

**Issue description:**

When I delete a node through its context menu by left clicking while holding the right mouse button, and then confirm in the popup dialog, the main editor never regains focus and has practically frozen. I can't save either except by trying to close the window so that it prompts me to save. Under some conditions the editor will freeze completely after breaking the UI, but I haven't been able to reproduce it reliably.

This happens with other popups activated through context menus too, such as adding a child to a node through the parent node's context menu.

The expected behavior is that after the popup is closed, the editor UI regains focus and responds to input.

**Steps to reproduce:** 

1. Create a blank project
2. Create a 2D scene by clicking the 2D scene button in the Scene dock.
3. Right click the root node and hold the right mouse button
4. Left click the "Delete Node(s)" context menu item, without letting go of the right mouse button
5. Click either "Cancel" or "Ok", it doesn't matter which

At this point, the main UI is darkened and does not respond to keyboard or mouse inputs.

**Minimal reproduction project:**

It's probably faster to create a blank project than to download and open an existing project. You can even use one of your own existing projects - just don't use one with unsaved changes.

**Comment by capnm** [comment]
Can confirm this in current master 8fb7481fd53313c5b7a7cece27af0de84c404853
In an attached gdb it seems to loop somewhere around `while (!gui.modal_stack.empty())`
```
(gdb) list *$pc
0x37db54e is in _gui_input_event() (scene/main/viewport.cpp:1844).
1839	
1840					_gui_sort_modal_stack();
1841					while (!gui.modal_stack.empty()) {
1842	
1843						Control *top = gui.modal_stack.back()->get();
1844						Vector2 pos2 = top->get_global_transform_with_canvas().affine_inverse().xform(mpos);
1845						if (!top->has_point(pos2)) {
1846	
1847							if (top->data.modal_exclusive || top->data.modal_frame == Engine::get_singleton()->get_frames_drawn()) {
1848								//cancel event, sorry, modal exclusive EATS UP ALL
```

```
(gdb) bt
#0  _gui_input_event () at scene/main/viewport.cpp:1861
#1  0x00000000037d930d in input () at scene/main/viewport.cpp:2789
#2  0x00000000037d9118 in _vp_input () at scene/main/viewport.cpp:1411
#3  0x00000000037fcb91 in call () at ./core/method_bind.gen.inc:867
#4  0x0000000004886ab2 in call () at core/object.cpp:921
#5  0x00000000048868cb in Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) () at core/object.cpp:847
#6  0x00000000037a4391 in call_group_flags () at scene/main/scene_tree.cpp:275
#7  0x00000000037a5eae in input_event () at scene/main/scene_tree.cpp:430
#8  0x0000000002035444 in _parse_input_event_impl () at main/input_default.cpp:442
#9  0x0000000002036a89 in flush_accumulated_events () at main/input_default.cpp:678
#10 0x0000000002022d30 in process_xevents () at platform/x11/os_x11.cpp:2692
#11 0x00000000020272a1 in OS_X11::run() () at platform/x11/os_x11.cpp:3256
#12 0x000000000201917b in main () at platform/x11/godot_x11.cpp:56
```
