### ISSUE TITLE
Godot as an Editor is not ready yet for complex projects

### ISSUE THREAD

**Issue by owstetra** [godotengine/godot#29529]
**Godot version:**
Godot Engine 3.1.1

**OS/device including version:**
Windows 7 x64bit
8 GB Ram
GTX 980

**Issue description:**
Godot as an Editor not as an Engine is not ready yet for big / complex Games / Projects
as you can see in this video :
https://youtu.be/gWLli5CBhCQ

Here is a small level for our Game , almost everything in this level is a scripted scene , Trees are scenes , Rocks are scenes , Floor are scenes ... etc , this will give is the full control of everything for example making the Trees Destroyable or Light poles turn the lights off if they get Hit .. etc
____
1- Running the game when i'm in 3D mode in the Editor in the same level that contain many instances you will see that the FPS is about 160 FPS
2- Running the game when i'm in Script mode in the Editor in the same level that contain many instances you will see that the FPS is about 193 FPS
3- Running the game when i create an Empty scene that contain nothing and switch to Script mode in the Editor you will see that the FPS is about 243 FPS

and Godot Engine will get Laggy after running the game several times.. make the FPS Drop more and more ... in this case i need to Export the game , Close Godot and Run the Game to get the Full FPS 

____
and when Opening many scripts in Godot , Close Godot and Run it again , Godot Editor will get messy like this 
![GodotProblem](https://user-images.githubusercontent.com/51128638/59013445-40e8f380-883a-11e9-9f3f-1acd9b914635.png)

and the way i fix it is by going to :
C:\Users\UserName\AppData\Roaming\Godot\projects and search for the project folder and Delete it ..

**Comment by qarmin** [comment]
Can you next time when Editor will break all layouts put here files "editor_layout.cfg" and "project_metadata.cfg"?
They should be in /Appdata/Roaming/Godot/projects/%ProjectName%/

**Comment by groud** [comment]
I see several issue here, please split your problem into several dedicated issues, they are unrelated.

**Comment by Ranoller** [comment]
What kind of issue name is this?

Issue name should be a resume of the problem, not a rant.

**Comment by owstetra** [comment]
@qarmin yes here is the files :
[Uploading Godot.zip…]()

**Comment by owstetra** [comment]
@qarmin yes here is the files
[Godot.zip](https://github.com/godotengine/godot/files/3260598/Godot.zip)

@Ranoller you should see the issue not the name

**Comment by Ranoller** [comment]
> @Ranoller you should see the issue not the name

It´s not mandatory, sorry....
