### ISSUE TITLE
 First Project Works With C#, All Further Projects Do Not

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot#29523]
Version 3.1.1 Stable

Windows 10
NVidia Optimus GPU

I can't compile any C# project after the first one I created. I've tried all using both Visual Studio and Mono. But the first one remains compilable, which is baffling.

 modules/mono/editor/csharp_project.cpp:183 - Parse error: Unexpected token: Symbol
 Failed to determine namespace and class for script: res://Scripts/XWing.cs
 modules/mono/editor/godotsharp_builds.cpp:383 - Condition ' metadata_err != OK ' is true. returned: false
 editor/editor_node.cpp:4666 - A Godot Engine build callback failed.

Set build_tool

 modules/mono/editor/csharp_project.cpp:183 - Parse error: Unexpected token: Symbol
 Failed to determine namespace and class for script: res://Scripts/XWing.cs
 modules/mono/editor/godotsharp_builds.cpp:383 - Condition ' metadata_err != OK ' is true. returned: false
 editor/editor_node.cpp:4666 - A Godot Engine build callback failed.

**Comment by steinm6** [comment]
Hi,

I have a similar problem:
``` 
modules/mono/editor/csharp_project.cpp:183 - Parse error: Unexpected token: ,
 Failed to determine namespace and class for script: res://Core/Scripts/Player/PlayerStateMachine.cs
 modules/mono/editor/godotsharp_builds.cpp:383 - Condition ' metadata_err != OK ' is true. returned: false
 editor/editor_node.cpp:4666 - A Godot Engine build callback failed.
```

The problem comes from the following C#-Code:
```
private class PlayerStateProvider : StateProvider<State<PlayerStates, PlayerEvents, PlayerData>, PlayerStates,
            PlayerEvents, PlayerData>
        {
            protected override State<PlayerStates, PlayerEvents, PlayerData>[] GetStates(
                IStateTransitioner<PlayerEvents, PlayerData> stateTransitioner)
            {
                return new State<PlayerStates, PlayerEvents, PlayerData>[]
                {
                    new Idle(stateTransitioner),
                    new Running(stateTransitioner)
                };
            }
        }
```

I work around this by creating a class that extends State<PlayerStates, PlayerEvents, PlayerData>. This way the error is gone, so I think it might also be related to: #23515

Project to reproduce this error:
[CSharp.zip](https://github.com/godotengine/godot/files/3878921/CSharp.zip)

This bug occures in 3.1.1.stable and 3.2-beta1.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 builds?

**Comment by neikeq** [comment]
Actually I don't know if the PR above fixes this issue. It fixes the one from @steinm6's example project. Can OP upload an example project?
