### ISSUE TITLE
Inconsistent using MAX in enums

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29530]
**Godot version:**
3.1.1

**Issue description:**
Sometimes enums have last value enum_MAX but sometimes not, probably i will be better to add MAX value to (almost) all enums

![Zrzut ekranu z 2019-06-06 09-58-21](https://user-images.githubusercontent.com/41945903/59016846-7f82ac00-8842-11e9-9bed-a5c045fcfe2c.png)

![Zrzut ekranu z 2019-06-06 09-57-52](https://user-images.githubusercontent.com/41945903/59016850-827d9c80-8842-11e9-92cc-d18214410701.png)

**Comment by akien-mga** [comment]
I'm not sure it's necessary to add `_MAX` values to all enums, those are only meant for enums where you would typically iterate over their values (e.g. `for (int i = 0: i < ALIGN_MAX; i++)`).

For many enums (especially those which are a list of constants to use individually, like `KeyList`, this doesn't really make sense.
