### ISSUE TITLE
Add space before commit in godot --version 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29535]
**Godot version:**
3.2.dev.custom_build.197b65f32
3.2.dev.custom_build. 197b65f32

**Issue description:**
When I paste to github godot version - 3.2.dev.custom_build.197b65f32 copied from `godot --version` or lastly added `godot` from terminal, then github just ignore commit and will display this as normal text.

But when a space between build. and commit number is putted, then it looks better, because github automatically show link to commit -  3.2.dev.custom_build. 197b65f32

**Comment by KoBeWi** [comment]
I just copy the commit hash when reporting something, so not sure how would that be useful (you need to select it anyways and the "custom build" part is rather irrelevant). If anything, the last dot could be replaced by space, because it would look weird otherwise.

**Comment by akien-mga** [comment]
I'd prefer not to change the format of the version string used since early Godot days just for the sake of easier parsing of the commit by GitHub.
