### ISSUE TITLE
Remote scene tree needs better error handling

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#29533]
**Godot version:**
3.1.1.

**OS/device including version:**
Ubuntu 18.04 LTS

**Issue description:**
I have an issue where clicking on a certain kind of node in the remote scene tree crashes the running game (but not the editor). It's not 100% reproducible - that means that once or twice I will get to inspect the affected node in inspector, but most of the time it ends in a game crash.
NOTE: There is NO crash at all if I don't use the remote scene tree and/or inspect some other nodes, e.g. the affected node's children/parent. In other words, the game plays perfectly, there are no errors reported or props being misaligned.
If I run the affected scene by itself, I am able to inspect it in the remote scene tree (every time so far, knock on wood, but I see #29506 then [which is not limited to this crash-inducing scene]) 
Usually - but not always, sometimes the crash is completely silent - the crash is accompanied by an error message (unix_socket line: 199: socket error 104). 104, as far as I can tell, is "connection ended by peer". Note, it's not the more common 10054. Yes, it's pointing to line 199, which as far as I can tell, is just an else? 
I am unable to get a better stacktrace because the release build doesn't have debug symbols.

(I spent half of yesterday and the best part of today ensuring there are no variables left unassigned, arrays that could've been assigned to themselves, etc. etc. and I am currently reasonably sure this is not an issue with the affected scene's script, as it's possible to remote inspect it if run by itself and it's possible to inspect it roughly 5% of the time...)

**Steps to reproduce:**
Run main scene, click on a certain kind of a scene in remote scene tree (Navigation/map/Road 12-3/Spatial0/Road instance0 is the one I tried when trying to see if it's reproducible). This is not limited to this one scene, you could run e.g. intersections.tscn and click Road 0-1/Spatial0/Road instance0 with the same sort of effects)

**Minimal reproduction project:**
Unfortunately it's a large project - I could give a link to its repo if you wish?

ETA: https://github.com/Zireael07/FreeRoamRoguelikeRacerPrototype/commit/7b64f365fb9ef013b046fa13849fa4b073386ee4

Proof that it works (but very very rarely):
![Screenshot 2019-06-06 15:04:35](https://user-images.githubusercontent.com/4525388/59034966-950ccb80-886c-11e9-8a53-1e5a8b3693a5.png)

**Comment by Zireael07** [comment]
Wishlist item point 1, the game absolutely should not crash because of the sockets interface not being able to handle some data (corrupted? too big?)
Wishlist item point 2, in such a case the inspector should simply stop trying to inspect the affected node (or the affected variable). An error message would be nice but not required.
Wishlist item point 3, tell us why the sockets interface crashed (corrupted variable? which one? too much data - again, which one?)

**Comment by Zireael07** [comment]
What does 'needs testing' label mean? Is it for me to test more or what?

**Comment by Zireael07** [comment]
So, I was thinking the materials/props were to blame. I split off the materials/props to a separate child node (https://github.com/Zireael07/FreeRoamRoguelikeRacerPrototype/commit/7cbcae200af00672f2f5529f86dd719e1fa5f157), and guess what, the child node doesn't cause the debugger to crash.

Since the actual code for straight and curved roads is practically the same, I am starting to suspect something similar to https://github.com/godotengine/godot/issues/27444#issuecomment-489466790 (the main difference between curved and straight roads at this point is, there is much more amount of commented out code in the latter).

**Comment by Zireael07** [comment]
Good news, I finally stumbled on a fix. I pitched in a tangentially related issue #4192 and saw a screenshot of debugger project settings. Doubling the websockets server/client values (all of them) seems to have fixed the issue completely.

Note that the scene causing the crash does suffer from #29506, being a tool script.
Quite possibly the node data itself was bringing websockets over the original limits, or possibly the added error from #29506, being quite long.

Either way, this should absolutely NOT crash and PLEASE, PLEASE add a user-visible message about the limits being exceeded.

**Comment by Zireael07** [comment]
Pinging @Faless since he seems to be the go-to person for websockets.

**Comment by Zireael07** [comment]
Shouldn't this get a topic:network tag?

**Comment by Faless** [comment]
@Zireael07 I'm not sure how websocket is related. It's not even used by the debugger. I suspect the problem lies in the editor/debugger.

**Comment by Zireael07** [comment]
It's not? So how do you explain this picture:
https://user-images.githubusercontent.com/6002340/56150199-9fb68d00-5fae-11e9-904b-1b87a86d310f.png

The settings I changed are clearly marked as 'websockets'

**Comment by Faless** [comment]
@Zireael07 no, the changed one (with the rotating arrow), are `Debugger Stdout`

**Comment by Zireael07** [comment]
The picture is *not* mine - I am just using it as a reference so that you know what to look for in settings. The person who posted the pic changed debugger settings, what *I* changed was the ones marked 'websocket client' and 'websocket server' (I doubled them to 128 and 2048)

**Comment by Faless** [comment]
@Zireael07 I see, well, again, websocket is not used by debugger, so if any of its code gets executed is kind of magic, which probably means the real problem lays somewhere else.

**Comment by Zireael07** [comment]
I tried doing some sleuthing on this. AFAICT editor debugger uses a "server" (eg. https://github.com/godotengine/godot/blob/7fa941bfd8a1d81fc5c27c21635e60846efc52f4/editor/script_editor_debugger.cpp#L1297) which I guess is tcp_server.cpp, which in turn uses "_sock" (https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/core/io/tcp_server.cpp#L54), and that is probably why so many debugger crashes involve unix_socket.cpp.

Since line 2004 of the editor debugger sets the packet size to 8 MB (I guess for the client, as there is nothing setting anything similar for server), I assume changing the server setting would have been enough.

So while it might not be "WEBsockets", something of networking is being used definitely @Faless

**Comment by Faless** [comment]
> So while it might not be "WEBsockets",

indeed. So it makes no sense that the "WEBSocket" setting matters at all.

> something of networking is being used definitely.

Of course it is, I never said the contrary.

**Comment by Zireael07** [comment]
Unfortunately I have zero idea how to follow those breadcrumbs I found, and my c++ is very poor :(

**Comment by Faless** [comment]
@Zireael07 honestly, the debugger needs an overhaul to do better buffering and packet dropping and never use blocking IO. It's going to take a while, but it might fix it (unless it's a bug in the remote scene inspector itself).
In the meantime try raising `Max buffer po` to something like `24` **restart the editor** and try to see if it works.

**Comment by Zireael07** [comment]
Raising max buffer po in 3.2 to anything higher than the default results in  core/io/packet_peer.cpp:272 - Condition "p_buffer_size + 4 > output_buffer.size()" is true. Returned: ERR_INVALID_PARAMETER

on start and on every tick and the remote tree is unusable (empty)

Oh, and in 3.2 it seems something changed - for the worse - no matter what my websocket settings are, I can't navigate to the affected nodes in remote scene tree. It just silently crashes.

**Comment by Faless** [comment]
> no matter what my websocket settings are

As I explained more then once in this thread, no matter what your websockets settings are, because the debugger does not use websocket.

**Comment by Zireael07** [comment]
The issue no longer happens in 3.2.1 rc1, I <3 Godot again! <3

The debugger/remote tree does feel a bit slower in 3.2 vs 3.1, in this 3D project (2D is fine), but I guess that'll go away with the upcoming refactor and threading.
