### ISSUE TITLE
Weird behaviour with load() inside a loop

### ISSUE THREAD

**Issue by teedoubleuu** [godotengine/godot#29545]
**Godot version: 3.1**

**OS/device including version:**
Windows 10

**Issue description:**
Large nested for() loop is executed 10 times faster after adding a random load() instruction inside the loop.

```
for y in range(512):
	for x in range(512):
		var some_string= some_array_pretending_to_be_a_grid[512*y+x]
			
                #without this line loop takes 10 times longer
		var o = load(some_random_path_to_a_script)

		some code operating on some_string
```

I'm losing my sanity here because it seems that adding that random load() instructions is making the loop take 10 times less time. Is there some kind of a hidden effect of using load()? Does it affect the memory used by the loop?

**Comment by volzhs** [comment]
can you provide a sample project?

**Comment by teedoubleuu** [comment]
Not really. I can't reproduce this in a new project. All I know is that load() should not affect how a loop is executed and if it is somehow affecting the loop it should be fixed or documented.

**Comment by santouits** [comment]
Maybe the load method errors and the loop breaks somehow? Can you check if the loop reaches to the end when using the load by incrementing a variable or something?

**Comment by teedoubleuu** [comment]
The loop completes and everything works fine. The only difference I can see is the time the loop takes.

**Comment by MGilleronFJ** [comment]
Is the code you posted the only code there is between the moment you start measuring time and the moment you stop measuring time? (assuming you measure time in code with OS.get_ticks_usec. If you don't, you probably should)

**Comment by KoBeWi** [comment]
This is impossible to investigate without a project. Also GDScript was rewritten in Godot 4, so likely no longer relevant. Closing.
Comment if you can still reproduce and have a MRP.
