### ISSUE TITLE
Problem with GDScript line breaking

### ISSUE THREAD

**Issue by Gabriel-Diaz** [godotengine/godot#29549]
**Godot version:**
Godot v3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
Godot detects a misplaced linebreak. I can't seem to detect it so I cannot solve it.

![parsing error3](https://user-images.githubusercontent.com/39809625/59045899-e60dc700-884e-11e9-9991-1b8ceba66e11.PNG)

	if Input.is_action_pressed("hum"):
			get_node("AudioStreamPlayer").play()
			counter++
		if counter == 2:
			counter = 0
			get_node("AudioStreamPlayer").stop()

**Comment by clayjohn** [comment]
The error is occurring because Godot doesn't support the ``++`` operator on line 35. Use ``counter += 1`` instead.

**Comment by Gabriel-Diaz** [comment]
Thank you so much!

**Comment by Calinou** [comment]
Would it be feasible to detect usage of `++`/`--`  and display a more user-friendly error message in this case?

**Comment by akien-mga** [comment]
That error message is a bit bogus, but since it's related to #19128 I mentioned it there.
