### ISSUE TITLE
Add Script Name to Script Icon tooltip in Scene Tree

### ISSUE THREAD

**Issue by lordoverflowgit** [godotengine/godot#29541]
**Godot version:**
3,1.1 stable

**Issue description:**
It would be useful to see the script name in script icon tooltip when mouse is over the script icon in scene tree.

See the image.

![image](https://user-images.githubusercontent.com/11921431/59031953-c9cd5280-886d-11e9-9291-bd5866135f4b.png)

**Comment by sparkart** [comment]
I've added a PR regarding this issue here: https://github.com/godotengine/godot/pull/29708
