### ISSUE TITLE
How to get colorful particle2d ?

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29551]
I create mutiple color config file. The partcles get the same color. Is there any config can let one particle2d create different colors ?

```
for i in range(4):
		var pt:Particles2D = PtCls.instance()
		add_child(pt)
		pt.position = Vector2()
		pool.append(pt)
		pt.process_material.color_ramp = load("res://game/pts/ptc_%s.tres"%poolCr[i])
		pt.restart()
```

I want this effect. I think there also have problem if upon code runing well. Because the different color set two different layer, not with together.
![](https://user-images.githubusercontent.com/1890538/59050580-40de0780-88bd-11e9-8f55-fe9c0eddb390.png)

**Comment by bojidar-bg** [comment]
Are you looking for "Hue shift" (+ "Hue shift random")?

**Comment by zszen** [comment]
@bojidar-bg thanks, it work

![image](https://user-images.githubusercontent.com/1890538/59056811-9ae5c980-88cb-11e9-8c00-aed690db58cf.png)
