### ISSUE TITLE
Using mouse wheel with MOUSE_MODE_CAPTURED is changing mouse position

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#29559]
Godot 3.1.1
Windows 10 64 bits

I use `get_viewport().get_mouse_position()` in order to get a ray to the 3D world from within `_physics_update`. However, I found that if I use `MOUSE_MODE_CAPTURED`, scrolling the mouse wheel will make the function return bad coordinates, until you move the mouse again. I expect this should not happen, mouse wheel is not supposed to move the mouse in any way.

Project:
[MousePositionWheel.zip](https://github.com/godotengine/godot/files/3263507/MousePositionWheel.zip)
Run the main scene, notice the mouse position is correctly reported (most often near the center). Then use mouse wheel, you'll see it changes by a lot, until you move the mouse again.

**Comment by EmeraldSlash** [comment]
I encountered this issue with the _input method, as it's being called with the InputEventMouseMotion event every time the wheel is scrolled.
