### ISSUE TITLE
Godot stuck

### ISSUE THREAD

**Issue by sman026** [godotengine/godot#29556]
**Godot version:**

3.1.1

**OS/device including version:**

I5 windows 8.1

**Issue description:**

Window is stuck

Picture
![1559847233493276587937877774750](https://user-images.githubusercontent.com/51458748/59058571-9c040000-88a5-11e9-920a-091e6e382f5d.jpg)

. Reproduce
Idk I just click and it gets stuck

**Comment by clayjohn** [comment]
Please include steps to reproduce. 

Also try again using the latest release, which is version 3.1.1.

**Comment by sman026** [comment]
Still stuck

في الخميس، ٦ يونيو ٢٠١٩ ١٠:١٤ م Clay John <notifications@github.com> كتب:

**Comment by clayjohn** [comment]
Please include steps to reproduce so someone can try to figure out what is going wrong.

**Comment by sunnystormy** [comment]
I'm having a similar issue where I run the godot binary on my Linux machine and nothing happens. When I open "top" it shows the process consuming 100 percent of the cpu. I did not have this issue prior to the current stable release (3.1.1). I switched to different desktop environments (between KDE and LXDE) but the problem persists. Any ideas?

**Comment by Calinou** [comment]
@sunnystormy Please open a new issue about this, as your hardware/software configuration is quite different to OP's.

**Comment by groud** [comment]
Sorry, but without more information on how to reproduce the problem, this issue is pointless. Please provide more information on how to reproduce the problem, or we will have to close the issue.

**Comment by Ovnuniarchos** [comment]
Try opening godot from a terminal, and copy the text that appears. It could provide us with more info.

**Comment by KoBeWi** [comment]
This issue was inactive for a year despite multiple information requests, so closing. Comment if this still happens in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1).
