### ISSUE TITLE
Renaming a file that no longer exists on the computer causes warnings on screen update

### ISSUE THREAD

**Issue by imnphil** [godotengine/godot#29566]
**Godot version:**

Godot 3.1.1 x64

**OS/device including version:**

AMD RX 480

**Issue description:**

The command line prints out the following errors whenever the screen updates after selecting rename on a project deleted from the computer:

WARNING: _get: Property not found: rendering/limits/time/time_rollover_secs
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/shadows/filter_mode
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/follow_surface
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/weight_samples
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/quality
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/scale
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/voxel_cone_tracing/high_quality
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/limits/time/time_rollover_secs
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/shadows/filter_mode
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/follow_surface
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/weight_samples
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/quality
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/scale
     At: core/project_settings.cpp:193
WARNING: _get: Property not found: rendering/quality/voxel_cone_tracing/high_quality
     At: core/project_settings.cpp:193

Trying to rename a deleted project should not cause warnings that continue until Godot is restarted. 

**Steps to reproduce:**

After deleting a project from the computer by going into my documents and deleting the file, the Godot interface creates an un-named, grayed out, empty project in the project list.

Selecting this box and attempting to rename the project causes the command line to create many warnings whenever any update to the interface happens.

**Minimal reproduction project:**

This issue works for all projects that no longer exist on the computer, but have not been deleted in the project list.

**Comment by qarmin** [comment]
Probably duplicate #25661

**Comment by KoBeWi** [comment]
It's no longer possible to rename a missing project, so this is resolved.
