### ISSUE TITLE
Allow node to have visibility toggle (eye icon) in editor tree view

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#29561]
**Godot version:**
3.1

**OS/device including version:**
linux

**Issue description:**
The node object does not have the option to hide in the editor. It is useful to hide nodes so that the children are hidden when working in the editor with large scenes. If using a regular spatial for this, its often to easy to move accidentally.

Or as an alternative, have another icon which allows nodes to be hidden in the editor, and does not affect the visibility in game. For example, I may have a details node which gets in the way in the editor, so i can leave it off. Then when the user jumps in game, that node is visible in game.

**Comment by Calinou** [comment]
Unlike Spatial, Control and Node2D, Node doesn't have a `visible` property, so I don't know if this can be implemented without too much trouble.

That said, I like the idea of having a global "Editor Only" property (as we already have for lights). This can be done by scripting, but it's a relatively common need, so it makes sense to have something like that built-in. I remember seeing an issue about this, but I can't find it.

**Comment by bojidar-bg** [comment]
You mean #12453?

**Comment by Calinou** [comment]
@bojidar-bg Yes, thanks :slightly_smiling_face:

**Comment by Gibbz** [comment]
Yeah basically I want to be able to use a node like a 'folder' in a file system. 
Currently using a Spatial for this is a bit annoying as we cannot lock the node from moving accidentally...

**Comment by Calinou** [comment]
@Gibbz 3D nodes can be locked since #12359 (merged before 3.0's release), is this feature still needed?

**Comment by Gibbz** [comment]
I'll have to check that out! Locking nodes would certainly be a solution. 
However I think using a node instead of a spatial, as a root\folder item still would be the more logical method.

**Comment by mhilbrunner** [comment]
Closing as per the above. If you checked the above and still need something else, please open a proposal in the proposals repo. :)
