### ISSUE TITLE
Exported executable shows "Godot Engine editor" in task manger.

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#29569]
**Godot version:**
3.1.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
Exported projects show up as "Godot engine editor" in task manager.

**Steps to reproduce:**
- Export a project with "Release" export mode.
- Run the executable and check task manager. There is a main process called "Godot engine editor" and a child process with the name of the project.
- Also if you right click the executable and go to properties > details, the details are about the egine.
![Godot-Task-Manager](https://user-images.githubusercontent.com/1850856/59089222-3a2daf80-8912-11e9-85e1-fbe2ffe4fb61.png)
![godot-properties](https://user-images.githubusercontent.com/1850856/59089220-3a2daf80-8912-11e9-92fc-8b33d332172b.png)

Seems to be the same as #3686 which might have been fixed with 2.0.1 build system but then got broken again with 3.0?

**Comment by Calinou** [comment]
Try following the instructions in [Changing application icon for Windows](https://docs.godotengine.org/en/latest/getting_started/workflow/export/changing_application_icon_for_windows.html), as `rcedit` is also used to set other executable metadata such as the file description.

**Comment by zaksnet** [comment]
I might be misunderstanding but i expected these:
![Screenshot_10](https://user-images.githubusercontent.com/1850856/59311488-60f13a80-8cb2-11e9-8111-e9615f54add7.png)
To be in here:
![Screenshot_11](https://user-images.githubusercontent.com/1850856/59311496-664e8500-8cb2-11e9-8146-6202f7b7508e.png)
I have set rcedit path as @Calinou pointed out but the exported executable still has godot's details.

**Comment by Calinou** [comment]
@zaksnet Do you see anything in the console output after exporting? Maybe rcedit isn't running correctly.

**Comment by zaksnet** [comment]
> @zaksnet Do you see anything in the command prompt after exporting? Maybe rcedit isn't running correctly.

@Calinou "Fatal error: Unable to parse version string for FileVersion". I have tried both rcedit-x86 and x64 if that helps.

**Comment by akien-mga** [comment]
Seems like rcedit doesn't like your invalid FileVersion "zak". Try with real values and see if it works.

**Comment by zaksnet** [comment]
@Calinou Using rcedit from cmd seems to work fine.

`rcedit-x64 "someFile" --set-version-string "FileDescription" "Some Description"`

successfully changed the file description.

**Comment by zaksnet** [comment]
> Seems like rcedit doesn't like your invalid FileVersion "zak". Try with real values and see if it works.

You'r right @akien-mga ! after changing "File version" and "Product version" it looks good, thank you! I will try to implement a check at the error dialog before closing this.
