### ISSUE TITLE
Created node has always at first place small letter

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29577]
**Godot version:**
3.2.dev.custom_build. 197b65f32

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I try to add node "Spatial", Godot change it name to "spatial"
![file](https://user-images.githubusercontent.com/41945903/59112234-e4bdc680-8942-11e9-94f3-e9c0f70fe8ec.gif)

**Comment by mrcdk** [comment]
Did you change the project settings Node section to `Name Casing = camelCase`?

**Comment by qarmin** [comment]
I'm idiot, I changed in Project settings accidentally Name Casting to camelCase instead PascalCase
