### ISSUE TITLE
Mouse signals still getting triggered when mouse is in UI

### ISSUE THREAD

**Issue by that-richard** [godotengine/godot#29575]
**Godot version: 3.1.1**

**Issue description:**
Mouse entered / exited signals get triggered from the last mouse position received by _unhandled_input even though the mouse is currently in a Control node and the signals shouldn't be triggering.

Possible solution:
Disable the signals when a mouse is over a node with the mouse filter set to "Stop"?

**Steps to reproduce:**
- Create an Area2D with entered/exited signals and somehow visualize it
- Save their state if their currently hovered
- Create a Control node with the MouseFilter set to "Stop" or "Pass"
- Make a way to move with a Camera
- Run the game
- Put your mouse on the selected Area2D and check that it selects normally with the mouse position
- Put your mouse into the Control node and then move around and if you remember the last position that the mouse wasnt in UI, put that place over the Area2D
- You got it

**Minimal reproduction project:**
[MouseIssue.zip](https://github.com/godotengine/godot/files/3266230/MouseIssue.zip)
^ Left / Right arrow keys to move the camera ^

**Comment by Jalu1** [comment]
Checking it out...

**Comment by KoBeWi** [comment]
This is weird. It looks like the mouse is permanently reported on the position it was before entering the Control, until it leaves. So e.g. when you trigger the entered signal, you can move cursor over whole Control and exit is triggered as soon as you leave the Control.

**Comment by that-richard** [comment]
> This is weird. It looks like the mouse is permanently reported on the position it was before entering the Control, until it leaves. So e.g. when you trigger the entered signal, you can move cursor over whole Control and exit is triggered as soon as you leave the Control.

Probably getting the mouse position that is being saved in _unhandled_input, which stops updating once the mouse goes over the Control.

**Comment by mrcdk** [comment]
Probably caused by this https://github.com/godotengine/godot/blob/197b65f32ac811f79bc5599fbfe8cf83914b6873/scene/main/viewport.cpp#L402-L427

It was added in https://github.com/godotengine/godot/commit/80a90ca824b3dd82ced0b047877949bb2f076a3e

**Comment by noname1477** [comment]
Sorry, I'm a bit late, but that issue seems to be bigger. For ColorRect the mouse doesn't stop where it enters, but also triggers signals inside (as long as you don't move the mouse).
