### ISSUE TITLE
Inherited Scenes that also inherit from the same .gd class can't hold default values in exported variables

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#2958]
The bug was reproduced in 222d112f496a5193b837854a72e4025a45a28ef2 build, but with manually reversed fix from: https://github.com/godotengine/godot/commit/884d5a0f41032a9c5c793577b82998998b3f87a0 since with this fix it's not possible to use Inherited Scenes feature at all.

1. You have BaseScene.xscn that has a script "BaseScript.gd".
2. You have a scene "ExtendedScene.xscn" that inherit from BaseScene.xscn and have a "ExtendedScript.gd" script that inherit from BaseScript.gd.
3. If in BaseScript.gd you will have any exported variable you wont be able to hold in "ExtendedScene.xscn" default value of this variable.

Video for quick judge:
https://youtu.be/JgwUxxqv7KE
Sample project: 
https://dl.dropboxusercontent.com/u/168251/godot/InheritedSceneAndPropertyLost.7z

**Comment by reduz** [comment]
I can't seem to reproduce, or maybe i'm doing something wrong?

**Comment by kubecz3k** [comment]
I can confirm it's fixed now, thanks!
