### ISSUE TITLE
Missing enum in GeometryInstance

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29582]
**Godot version:**
3.2 master

![Zrzut ekranu z 2019-06-07 18-03-50](https://user-images.githubusercontent.com/41945903/59117759-de354c00-894e-11e9-8ab4-f3b250a4467d.png)

**Comment by bojidar-bg** [comment]
The missing flag is `INSTANCE_FLAG_DRAW_NEXT_FRAME_IF_VISIBLE`:

https://github.com/godotengine/godot/blob/197b65f32ac811f79bc5599fbfe8cf83914b6873/servers/visual_server.h#L841-L845
https://github.com/godotengine/godot/blob/197b65f32ac811f79bc5599fbfe8cf83914b6873/scene/3d/visual_instance.h#L90-L93

**Comment by kbajno** [comment]
I would like to take on this issue!
