### ISSUE TITLE
Missing FLAG_DISABLE_Z enum value in CPU Particles(2D)

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29580]
**Godot version:**
3.2.dev.custom_build.197b65f32

**Issue description:**
Similar issue as #29419, but this time in CPU Particles( maybe also CPU Particles 2D, but I'm not sure)
![Zrzut ekranu z 2019-06-07 17-41-34](https://user-images.githubusercontent.com/41945903/59116533-0cfdf300-894c-11e9-9f45-69f180a4f3b5.png)
![Zrzut ekranu z 2019-06-07 17-41-38](https://user-images.githubusercontent.com/41945903/59116534-0cfdf300-894c-11e9-9d59-74ec4f413fba.png)

also in CPU Particles 3D can be missing PARAM_ORBIT_VELOCITY which is present in CPU Particles 2D(Not sure, but in code is commented)

**Comment by akien-mga** [comment]
This one is a bit more involved than #29419, as it seems `FLAG_DISABLE_Z` and `orbit_velocity` code is commented out and not exposed in both `CPUParticles` and `CPUParticles2D`, seemingly since their first implementation.
