### ISSUE TITLE
Inherited class does not load properly if used with `tool`

### ISSUE THREAD

**Issue by JohnMeadow1** [godotengine/godot#29586]
I see multiple issues related to class_name, but nothing obviously related to this one.

Godot 3.1.1 Stable
Windows 10

**Issue description:**
Adding `tool` before `extends` works if you use it like this:
 `extends "res://BaseClass.gd"`
but not like this:
`extends BaseClass`
![obraz](https://user-images.githubusercontent.com/23294139/59129990-89093280-896e-11e9-8269-7ca5438ffe18.png)

**Steps to reproduce:**

```
#base class at res://BaseClass.gd
extends Node2D
class_name BaseClass

enum GameResourceType{ GRAIN, WOOD, STONE }
```
![obraz](https://user-images.githubusercontent.com/23294139/59130527-fb2e4700-896f-11e9-825e-c9aabd7be539.png)
 (the base class is properly registered in Godot)

**This does not work:**
```
tool
extends BaseClass

export(GameResourceType) var resource_type:int = 0 setget _set_resource_type

func _set_resource_type(value):
	resource_type = value

```
**And this works:**
```
tool
extends "res://BaseClass.gd"

export(GameResourceType) var resource_type:int = 0 setget _set_resource_type

func _set_resource_type(value):
	resource_type = value
```

**Minimal project**
[class_name_and_tool.zip](https://github.com/godotengine/godot/files/3267377/class_name_and_tool.zip)

**Comment by Geequlim** [comment]
The `BaseClass` should be defined with `tool`.

**Comment by JohnMeadow1** [comment]
Sure. That make sense.
But there is inconsistence in behavior if you extend base class like:
`extends "res://BaseClass.gd"`
or 
`extends BaseClass`
Shouldn't both ways behave in the same way?
