### ISSUE TITLE
Physics2DServer.body_set_state doesn't cause changes until the next physics step

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#29591]
PhysicsServer2D.body_set_state doesn't cause immediate changes, yet changing the transform of a shape causes immediate changes and this method seems to be the only one able to change the transform of a body, I also tried changing the body's direct state but that did the same thing.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment]
Fixed by #41423
