### ISSUE TITLE
Import dae file failed with skeleton and mesh skin, Also failed with skeleton animation

### ISSUE THREAD

**Issue by rssqian** [godotengine/godot#2959]
Hi,

Currently, I want to use fbx(mesh with skeleton animation, created by Maya) in godot。
But import failed with dae file exported by OpenCollada plugin with Maya--2011.
 https://github.com/KhronosGroup/OpenCOLLADA/wiki/OpenCOLLADA-Tools

I create some samples:
https://drive.google.com/folderview?id=0B4YTkPLUt69iZ2RsZjlLblhhLU0&usp=sharing

The sample list as follows:
    1) onlymesh.dae-----Sphere
    Result:  both works in godot and unity with import 3d scene 
    2)onemesh onjoint.dae-- one mesh with two joints, so one skeleton
    Result: both works in godot and unity.
   3)onemesh onjoint skin.dae -- one mesh, two joints, with skin
   Result: godot import error
  4)onemesh onjoint animation.dae -- one mesh, two joints, with skin and skeleton animation
   Result: godot import error, unity import , but can not play skeleton animation

  Also, as I saw the notes somewhere:
        make sure that
        -meshes are child of skeleton
       -mesh transform (offset, rotation, scale) in regards to skeleton is zero
     
I create samples with skeleton as mesh's parent:
    1)onemesh onjoint parent.dae-- make skeleton as mesh's parent in Maya 2011
       Result: both works in godot and unity
   2)onemesh onjoint parent skin.dae-- one mesh, two joints, with skin, make skeleton as mesh parent
       Result:godot can import,but no mesh,only skeleton Nodes. Unity works well
   3)onemesh onjoint parent animation.dae
      Result: not works.

Many thanks if you could help.

Best Wishes,
Fengwei.

**Comment by reduz** [comment]
i think the only situation where this might fail is when you have one mesh
affected by more than one skeleton. Maya is pretty "free" on how data is
linked and might mess up the importer

**Comment by rssqian** [comment]
Hi，reduz
You mean 
1) one mesh can only affected by one skeleton

I asked our designer, It is normal when one mesh affected by more than one skeleton. 

For example, A leg be driven by more than two skeleton.
Also in Maya,  Maybe a horse is one mesh,while it has many skeleton.

Best Wishes,
Fengwei.

**Comment by rssqian** [comment]
Sorry, My misunderstanding about this issue's description.

This case in Maya, two joints with one mesh.
That is one skeleton. As follow png show.

![skeleton](https://cloud.githubusercontent.com/assets/475049/11493013/2abdbff4-982f-11e5-8152-7dcc797ebf38.png)

**Comment by rssqian** [comment]
Also @reduz ,
    I want to use godot as 3D engine, and at present, to show follow things:
    1) import fbx --mainly mesh and skeleton animation made by Maya, 
    or 2) 3D things like prefabs(Unity)

We use unity before, I found godot is wonderful 3D engine. So could you tell me its 3D ability and usabilily. As i import 3d mesh+skeleton animation failed in this case.

We mainly care about 3D mesh + skeleton animation + physical engine + Particle system + audio system +Shader + gltf support + gesture + network.

Many thanks for your guide...

Best Wishes,
Fengwei.

**Comment by reduz** [comment]
The collada in your examples was invalid, it was missing the sid=<> field in the joints. I just hacked it so it works anyway

**Comment by rssqian** [comment]
@reduz, thanks,it works now.
