### ISSUE TITLE
Add CLion project to codebase

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot#29596]
Hello,

Like many other developers, I am most familiar with IntelliJ IDE's, and in this case would like to use CLion. Now, as I understand it there is no need to support multiple IDE project types in tandem (VS is already the 'default' option) so I understand this is likely a low-priority issue.

However, I feel like this is worth looking into as it would be beneficial to have all CLion developers on the same page - using the same .clang-format for the project, having the source indexed properly, or even finding a way to introduce the SCons build system into the IDE directly (or if the build system moves away from SCons, support CMake or whatever). There are a lot of different features, and many different setups, and I'd like to ensure that there isn't too much divergence for the components that matter the most.

I'm using CLion myself but am missing many of the features - I'm more comfortable in this IDE and having a more streamlined setup process would help introduce more developers into contributing to the codebase. I know personally it took many hours and several failed attempts to get Godot to build once, and I still have to manually run SCons in the terminal window. I'm also unable to figure out debug but that could be due to my being out of practice with C++.

SCons already has the option to produce a VSCode project. I'm curious why we rely on SCons to produce this instead of including it directly in the VCS (with appropriate .gitignore of course). However, I'm still naive as far as the technical details of SCons so I won't worry about that too much. Adding a CLion option doesn't seem like too much of a stretch if it was deemed a priority.

Thanks,
-Devin

**Comment by Calinou** [comment]
> SCons already has the option to produce a VSCode project.

It can produce a Visual Studio project, not a Visual Studio Code project :wink:

**Comment by DevinPentecost** [comment]
> [This PR featuring an IntelliJ project file](https://github.com/godotengine/godot/pull/27657) has recently been merged, how well does it work with CLion? (It's said to be working according to the pull request author.)
> 
> > SCons already has the option to produce a VSCode project.
> 
> It can produce a Visual Studio project, not a Visual Studio Code project 😉

See? Just goes to show how oblivious I really am when it comes to SCons 🥇 
Either way I think we should encourage as much development as possible and a huge part of that (For me at least) is using tools that I'm more familiar with.

I'll try out the PR when I can get around to it and see how it compares. As far as I know most IntelliJ tools are compatible in one form or another so it should work somewhat with CLion.

Thanks!
-Devin

**Comment by Calinou** [comment]
@DevinPentecost Did you give it a try? It was merged recently :slightly_smiling_face:

**Comment by DDL-Blue** [comment]
@DevinPentecost You can find the file at platform/android/java/lib/CMakeLists.txt

**Comment by m4gr3d** [comment]
Seems like once @DDL-Blue [updates the documentation](https://github.com/godotengine/godot/pull/27657#issuecomment-569718932), this issue can be closed.

**Comment by sebastian-heinz** [comment]
A minor update is that the file has moved:
`godot/platform/android/java/nativeSrcsConfigs/CMakeLists.txt`

Apart from that everything from the tutorial still works.

An additional step that can be done is:

1) create a `Custom Build Target` for scons like so:
<img width="1796" alt="Screenshot 2021-03-01 at 2 22 07 PM" src="https://user-images.githubusercontent.com/7891178/109459396-a9a9e200-7a99-11eb-9e9d-dfaafe828516.png">

2) create a `Run Configuration` like so:
<img width="1059" alt="Screenshot 2021-03-01 at 2 22 39 PM" src="https://user-images.githubusercontent.com/7891178/109459400-aadb0f00-7a99-11eb-8ba2-c0061d172a2d.png">

This allows you to select the `Debug` icon from the CLion menu and it will compile the project and run the resulting binary with the debugger attached.

In case this might reduce some manual steps of attaching.
If there is already a better way, it would be great to share that in the tutorial as well.

Thanks!

**Comment by Calinou** [comment]
@sebastian-heinz Feel free to open a pull request for this :slightly_smiling_face:
