### ISSUE TITLE
Issue with inherited _input_event()

### ISSUE THREAD

**Issue by quantumnoctus** [godotengine/godot#29594]
**Godot version:**

3.1 from Steam

**OS/device including version:**

Windows 10 fully up to date, doesn't seem graphics-related.
Not sure if relevant but I have a Ryzen 5 1600, a GTX 1080, 16GB of ram.

**Issue description:**

I have a (brown) Door scene that I can click on to open. I created a (silver) LockedDoor class that inherited from the Door scene, but with additional functionality. The idea is to use a keypad and once you enter the correct combination, the door should open. 

Once setting everything up, I placed a LockedDoor into my scene to test it out. I used a few print statements to try to troubleshoot and while it did recognize when I was in the area2d, it never once recognized my clicks on it. If i changed my code from _input_event(): to _input(): it did start to work but obviously it wasn't usable because everytime I clicked anywhere it would pull up the keypad, which isn't what I was going for. 

What clued me in to this bug is that I follow an online tutorial and have copied the instructors code word for word all the way through. When he tested it, his worked fine, but mine did not. Granted, the course is in Godot 3.0, and I am running Godot 3.1, so maybe this isn't a bug and I just don't know how it works now... Unsure. 

HOWEVER - I was able to get it to work how I wanted it to by completely deleting my LockedDoor.tres and LockedDoor.gd and restarting the client. I then build the LockedDoor.tres from scratch (and the .gd) and did it without the inheritance. THAT version did work. (I did not attach it because I am not sure if you'd want 2 projects, haha.)

This leads me to believe that there may be some issue with inheritance although I don't know what it is. 

**Steps to reproduce:**
If you open the attached project, once you hit play, hit the space bar so you can actually see. I placed two easy access doors you should be able to just click on the brown door and see it open and then click on the silver door and it won't open or register the click.

**Minimal reproduction project:**

[For_Godot.zip](https://github.com/godotengine/godot/files/3268039/For_Godot.zip)

**Comment by mrcdk** [comment]
For some reason your instanced locked door in the level don't have any collision layer bits enabled and that's why it doesn't work.

**Comment by quantumnoctus** [comment]
Thanks so much for this response. Sorry for putting this as a bug. I don't know why it did that since it did have the collision enabled in the LockedDoor scene.
