### ISSUE TITLE
C# Multiple KinematicBody2D's on the same tile move_and_slide issue

### ISSUE THREAD

**Issue by CrustyRob** [godotengine/godot#29597]
**Godot version:**
Godot_v3.1.1-stable_mono_win64

**OS/device including version:**
Windows 10

**Issue description:**
When moving multiple KinematicBody2D's from the same tile with the same speed and direction (I made all the enemies start on the same tile) and using RayCast2D to detect when the NPC reaches the edge of the tile, it negates the RayCast2D and acts as if all of the NPC's are sharing the same script, forcing them to fly off. This only happens when they are basically 1:1 pixels stacked on top of each other. (You can re-create it easily by placing them on top of each other and starting the scene). I also increased the speed for debugging purposes so it would collide more often, the actual speed of the enemy is in the bottom GIF. Although, this bug happens at any speed.

Starting the scene with 4 NPC's ontop of eachother.
[https://i.imgur.com/4tmUBex.gifv](https://i.imgur.com/4tmUBex.gifv)

Debugging the scene further, under the (!rayCast.IsColliding()) check, I added a print line to check the class name being called. It keeps getting stuck on the first enemy.

** Debug Process Started **
OpenGL ES 2.0 Renderer: GeForce GTX 950/PCIe/SSE2
Snake2
Snake
Snake
Snake
Snake
Snake
Snake
Snake
Snake
Snake
Snake
Snake
Snake

When they are not stacked on top of each other, the script and movement work perfectly fine. Which looks something like this. This scene was started where enemies were not stacked and spread out better. The issue still persists just very rarely, only on the chance that two or more NPC's are walking in the same direction near an edge at the same time.
[https://i.imgur.com/sn0m4x6.gifv](https://i.imgur.com/sn0m4x6.gifv)

**Class file:**
https://pastebin.com/czWS3c4X
https://i.imgur.com/lGN7Ll0.png

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
