### ISSUE TITLE
iOS 9 runtime failure

### ISSUE THREAD

**Issue by Tassim** [godotengine/godot#2960]
When compiling & running godot on iOS9, you get this error : 

http://oi65.tinypic.com/348km4o.jpg

Everything works fine for older iOS versions.

**Comment by punto-** [comment]
It looks like your game didn't load, since the help text is on the
console.. How are you adding your data to the project?

**Comment by Tassim** [comment]
by a data.pck. The same process works nicely on iphone 4, with a lower iOS. Sadly, it runs at 10 fps... Knowing that on android it runs smoothly at 50 fps.

**Comment by Tassim** [comment]
It was a data.pck problem; not from godot.
