### ISSUE TITLE
Sub-Meshes are merged into a single node in Godot

### ISSUE THREAD

**Issue by MartinHaeusler** [godotengine/godot#29608]
**Godot version:**
v3.1.1, Mono Edition

**OS/device including version:**
Windows

**Issue description:**
- I have a blender model which contains several independent objects.
- After exporting this model to *.obj format and importing it in Godot, Godot will treat the entire *.obj file as one atomic node in the scene hierarchy.

This causes several problems:
- It is not possible to manipulate (move, show/hide, scale...) sub-objects independently of each other.
- The sub-objects all share the 8 materials which can be attached to the root object, introducing an unnecessary limitation.

**What should have happened instead:**
Godot should have realized that the *.obj contains several independent objects, and should have created one node in the hierarchy for each of them, under a common root node which represents the file.

This *may* be a limitation of the *.obj format though: I'm not sure if *.obj files can convey information such as sub-objects.

**Comment by Zylann** [comment]
Does obj actually supports multi-submesh models?

**Comment by MartinHaeusler** [comment]
To be honest I don't really care about the *.obj format, it was just the only way to make blender 2.8 and Godot 3.1.1 play nicely together. I wouldn't use it in a real project (Collada and FBX are much better in many aspects).

I just wanted to let the devs know that this is an issue. If things behave differently for other formats, then that's fine. Using Blender 2.8 with Godot 3.1.1. at this point in time turned out to be quite the frustrating experience.

**Comment by Zireael07** [comment]
@MartinHaeusler: Can't you use the Blender - Godot exporter plugin?

https://github.com/godotengine/godot-blender-exporter

**Comment by MartinHaeusler** [comment]
@Zireael07 unfortunately, no. Neither the "Better collada exporter" plugin nor the Scene Exporter plugin work with Blender 2.8 at the time of writing this comment. Blender 2.8 is techically still in Beta, but the public API has been declared as final already, so this might be a good time to update the exporters...

**Comment by Megalomaniak** [comment]
> @Zylann said:
> I thought OBJ didn't support multi-objects, but according to [this post](https://blender.stackexchange.com/questions/51785/how-do-i-export-multiple-separate-objects-in-an-obj-file) it looks like it does?

To be more specific, Wavefront OBJ only supports a single basis. How a thirdparty application chooses to import the OBJ groups is up to that application. We could have an option added to import each group in the OBJ file as a separate meshinstance/object, but all their origin points(basis) would be identical.

Basically think in terms of having multiple vertex groups in a blender 3d mesh object separated out into different objects, if that makes sense.

**Comment by eon-s** [comment]
@MartinHaeusler about collada, it seems that the fix for 2.8 was broken recently due to changes on Blender so I do not think it will be upgraded until Blender enters a stable version, you can check try the fix yourself from the PRs
https://github.com/godotengine/collada-exporter/pulls

**Comment by fracteed** [comment]
You need to reimport the obj as a scene, and it will then import as a flat scene hierarchy. By default it will come in merged as one mesh.
Obj format will not retain the individual origins of each object are any hierarchical info, so you will need dae or gltf if you need those.

**Comment by Megalomaniak** [comment]
> We could have an option added to import each group in the OBJ file as a separate meshinstance/object, but all their origin points(basis) would be identical.

Actually thinking more about it another way of handling the import I've seen in the past is to calculate each AABB and then use the center of that to define each objects origin.

**Comment by MartinHaeusler** [comment]
> You need to reimport the obj as a scene, and it will then import as a flat scene hierarchy. By default it will come in merged as one mesh.
> Obj format will not retain the individual origins of each object are any hierarchical info, so you will need dae or gltf if you need those.

So... if I used DAE/GLTF files instead, the sub-objects will be preserved? I can't really test that at the moment (GLTF exporter in Blender 2.8 is broken right now, and Better Collada Exporter doesn't like 2.8). 

If it is an *obj thing, then this issue is really not all that important - (hopefully) nobody will use *.obj files when the standard formats (dae, fbx) are working on both the blender side and the godot side.

**Comment by fracteed** [comment]
I use obj almost exclusively for static objects as I always find them trouble free and very robust. Unless I need vertex colors or a full hierarchy I would use dae. Gltf is the future, see eventually that would be all that you need. 

Currently if you import an obj into Godot it will import as a single mesh by default, so if you had multiple meshes in Blender it will merge them. However if you select the obj in Godot's file browser and then go to the import tab, you can change this to be imported as a scene and then reimport it. Then all separate meshes from Blender will each be a separate node in Godot as a flat hierarchy. Though all pivot points will be at world center.

**Comment by fire** [comment]
Since @fracteed gave a workflow. This issue should be solved.

Thanks for contributing.
