### ISSUE TITLE
ShortCut doesn't call Button _pressed virtual function

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#29604]
**Godot version:** Godot 3.1.1

**OS/device including version:** Windows 10

**Issue description:**

When the ShortCut key combination is pressed, the `_pressed` function is not call but the signal `pressed` is emitted.

```
extends TextureButton

func _ready():
#	connect('pressed', self, 'toggle') # works if uncommented
	pass

func _pressed():
	toggle()

func toggle():
	OS.window_fullscreen = not OS.window_fullscreen
```

**Steps to reproduce:**
1. Extract zip and put scene in any project
2. Run the scene with F6
3. Press `Alt + Enter`

**Minimal reproduction project:**

[FullscreenButton.zip](https://github.com/godotengine/godot/files/3268607/FullscreenButton.zip)

**Comment by akien-mga** [comment]
I can confirm that it doesn't seem to behave as one would expect. If you set it the button to Toggle Mode, then the shortcut works fine for the toggle, but not in the normal non-toggle mode.

Here's an updated MRP with the broken dependency resolved and a texture for the pressed state:
[FullscreenButton.zip](https://github.com/godotengine/godot/files/3281591/FullscreenButton.zip)
