### ISSUE TITLE
Godot engine corrutines in c#

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#29609]
**Godot version:**

![Screenshot_5](https://user-images.githubusercontent.com/12847027/59150875-90791c00-8a00-11e9-8e1e-8fc255dd816a.png)

**OS/device including version:**
windows 7 64 bits.
![Screenshot_4](https://user-images.githubusercontent.com/12847027/59150866-7e977900-8a00-11e9-88ef-8aab37797901.png)

**Issue description:**
someone knows how to create a corrutina with c # in godot engine ... With Gdscript it was simple, but with c # I can not find the form ... "It tells me that yield does not exist in the context"
![Screenshot_1](https://user-images.githubusercontent.com/12847027/59150846-409a5500-8a00-11e9-84a9-a37bce18cc98.png)
I could create the function to stop the flow for a while
![Screenshot_2](https://user-images.githubusercontent.com/12847027/59150848-4b54ea00-8a00-11e9-8e07-bd1bf0f3af6f.png)
but if I call it for example in a function type bodyenter it seems that it does not work.
![Screenshot_3](https://user-images.githubusercontent.com/12847027/59150857-5f98e700-8a00-11e9-873e-6e8c82daf353.png)

Could you create this function for the next versions of godot engine c #?

**Comment by neikeq** [comment]
That line should be `await tiempoEspera(5.0f);`.

**Comment by kone9** [comment]
> That line should be `await tiempoEspera(5.0f);`

![Screenshot_6](https://user-images.githubusercontent.com/12847027/59151041-fe264780-8a02-11e9-9a30-909a0733faba.png)

**Comment by kone9** [comment]
> That line should be `await tiempoEspera(5.0f);`.

It only works in this way, I can not run it with a function, so I asked them if they can create this function to make things easier and what function is more similar to GDscript
![Screenshot_7](https://user-images.githubusercontent.com/12847027/59151064-742aae80-8a03-11e9-9879-be6857a5c96e.png)

**Comment by kone9** [comment]
**solution final:**Thanks for help
![Screenshot_8](https://user-images.githubusercontent.com/12847027/59151173-e780f000-8a04-11e9-800b-894969530600.png)
![Screenshot_9](https://user-images.githubusercontent.com/12847027/59151174-eb147700-8a04-11e9-9110-8900440520c4.png)

**Comment by neikeq** [comment]
`tiempoEspera` must return `Task` instead of `void` in order to be awaitable.

**Comment by kone9** [comment]
> `tiempoEspera` must return `Task` instead of `void` in order to be awaitable.

Ok,thanks....Video solutión.
https://www.youtube.com/watch?v=P0n_HvOJjx4&t=25s
https://www.youtube.com/watch?v=ACVJ2qNj1AU
