### ISSUE TITLE
Error using static method

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#2961]
It fails to create a object :(

    class Grass_LoDStrategy extends Node:
    	# singleton initializer
    	static func initialize():
    		var o = Globals.has('iGrass_LoDStrategy')
    		if not Globals.has('iGrass_LoDStrategy'):
    			o = Grass_LoDStrategy.new()
    			Globals.set('iGrass_LoDStrategy',o)
    		return o
    	
    	func _init():
    		pass

**Comment by akien-mga** [comment]
Could you give more details about what you're trying to do? It looks like you are make a class which should instanciate itself when calling initialize(), but to do what, I have no clue.

Also you don't say what the error is, and since we don't have your Globals we can't really test it either.

**Comment by kubecz3k** [comment]
@marcosbitetti from looking at your code it looks there is an error.  ``var o = Globals.has('iGrass_LoDStrategy')`` o will have boolean value instead of your object. I believe you should write it more like: 
```python
if Globals.has("iGrass_LoDStrategy"): 
         o = get_singleton("iGrass_LoDStrategy")
else:
         o = Grass_LoDStrategy.new()
         Globals.set('iGrass_LoDStrategy',o)
return o
```
it's also possible you might need to use ``has_singleton`` instead of ``has``, I'm not sure I never used Globals

**Comment by marcosbitetti** [comment]
The error is on Grass_LoDStrategy.new()
Static method not reconize it as a class!

Sorry, I reorganize it

    class Grass_LoDStrategy extends Node:
    	# singleton initializer
    	static func initialize():
    		var o
    		if not Globals.has('iGrass_LoDStrategy'):
    			o = Grass_LoDStrategy.new() # this not work
    			Globals.set('iGrass_LoDStrategy',o)
    		else:
    			o = Globals.get('iGrass_LoDStrategy')
    		return o
    	
    	func _init():
    		pass

**Comment by bojidar-bg** [comment]
@marcosbitetti I usually do it like this (as new is a static function too :wink:  ):
````
class Connection:
	#....
	static func create(stream):
		var new_self = new()
		new_self.stream = stream
	#....
````

**Comment by marcosbitetti** [comment]
uhmm. Make sense, but capacity to view itself is desirable.
