### ISSUE TITLE
Godot Headless Export Path Inconsistent

### ISSUE THREAD

**Issue by greenfox1505** [godotengine/godot#29618]
**Godot version:**
3.1.1 Headless

**OS/device including version:**
Linux, version shouldn't matter

**Issue description:**
Godot headless export path is confusing.

**Steps to reproduce:**
`./bin/Godot_v3.1.1-stable_linux_headless.64 -v "./${projectDir}/project.godot" --export HTML5 "./${exportDir}/index.html"`

I expect this to export to export to the relative path of my current directory, `"./${exportDir}/testProject.html"`, but instead it tries to export to the relative path of the `project.godot` file, so `./${projectDir}/${exportDir}/testProject.html`

This can be bypassed with the absolute path `${realpath "./${exportDir}/testProject.html"}`, but it is not oblivious that is the problem from the error messages.

This is not technically a bug, but it is very confusing and can cause headless builds to fail and give no useful error message if you don't realize Godot is using the project file's relative path.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1) or any later release?

**Comment by Calinou** [comment]
@KoBeWi There's already an issue about this, but I can't find it right now. I discussed this problem with Akien recently and he said he'd prefer the current behavior to be kept as-is to avoid breaking automateed scripts.

**Comment by Calinou** [comment]
The command line help was improved to mention that the output path is relative to the project root:

```
  --export <preset> <path>  Export the project using the given preset and matching release template.
                            The preset name should match one defined in export_presets.cfg.
                            <path> should be absolute or relative to the project directory,
                            and include the filename for the binary (e.g. 'builds/game.exe').
                            The target directory should exist.
```

Therefore, I'll close this in favor of https://github.com/godotengine/godot-proposals/issues/4951.
