### ISSUE TITLE
Android: Error when exporting random functions - **SCRIPT ERROR**: Parse Error: Too few arguments for 'inverse_lerp' intrinsic function.

### ISSUE THREAD

**Issue by nadorkb** [godotengine/godot#29617]
Godot version: last stable version 3.1

OS/device including version: Linux debianHP 4.9.0-9-amd64, Android: version 9, Phones: OnePlus 6, Oneplus 3T, Samsung 5, HTC.

Issue description:

I cloned the last git godot repository, recompiled with an ecryption AES key. No new module, nothing added. Just trying to test the encryption.

I created a simple project where I have only one scene with a simple panel in Node, and one script which is attached to the node.

Inside the code also simple:

```
extends Node

func _ready():
	randomize();
	pass

```
Export: Script -> Mode: (Compile or Encryption with my AES key)

When I exported this simple project (android) to my phones (all of them),  the project is installed without error, but when launching, I'm getting:

> 06-08 21:47:55.582 17057 17097 E godot   : **SCRIPT ERROR**: Parse Error: Too few arguments for 'inverse_lerp' intrinsic function.
> 06-08 21:47:55.582 17057 17097 E godot   :    At: res://test.gde:5:GDScript::load_byte_code() - Parse Error: Too few arguments for 'inverse_lerp' intrinsic function.
> 06-08 21:47:55.582 17057 17097 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 06-08 21:47:55.582 17057 17097 E godot   :    At: modules/gdscript/gdscript.cpp:786:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 06-08 21:47:55.582 17057 17097 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 06-08 21:47:55.582 17057 17097 E godot   :    At: modules/gdscript/gdscript.cpp:2195:load() - Condition ' err != OK ' is true. returned: RES()
> 06-08 21:47:55.582 17057 17097 E godot   : **ERROR**: Failed loading resource: res://test.gde
> 06-08 21:47:55.582 17057 17097 E godot   :    At: core/io/resource_loader.cpp:285:_load() - Method/Function Failed, returning: RES()
> 06-08 21:47:55.582 17057 17097 E godot   : **ERROR**: res://Node2D.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://test.gd
> 06-08 21:47:55.582 17057 17097 E godot   :    At: scene/resources/resource_format_text.cpp:440:poll() - res://Node2D.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://test.gd
> 06-08 21:47:55.582 17057 17097 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 06-08 21:47:55.583 17057 17097 E godot   :    At: core/io/resource_loader.cpp:208:load() - Condition ' err != OK ' is true. returned: RES()
> 06-08 21:47:55.583 17057 17097 E godot   : **ERROR**: Failed loading resource: res://Node2D.tscn
> 06-08 21:47:55.583 17057 17097 E godot   :    At: core/io/resource_loader.cpp:285:_load() - Method/Function Failed, returning: RES()
> 06-08 21:47:55.583 17057 17097 E godot   : **ERROR**: Failed loading scene: res://Node2D.tscn
> 06-08 21:47:55.583 17057 17097 E godot   :    At: main/main.cpp:1757:start() - Condition ' !scene ' is true. returned: false
......

With the same code, without randomize(), the export works normally.
I have the same errors if I replace this function with max(), random functions.

Export: Mode -> Text, no problem with randomize, max and others.

Tryed also with Window 10, the same issues.

I tried different proposition found in gitgub issues, godot forum and by googling, nothing fixes my issue.

Am i doing something wrong ?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
