### ISSUE TITLE
Some node configuration warnings aren't displayed immediately after changing properties

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#29619]
**Godot version:** Git https://github.com/godotengine/godot/commit/abbbde87e28982150d30e748b89c5303384909ca

**OS/device including version:** Fedora 30, Clang 8.0.0

**Issue description:** When changing properties that *should* cause a node to display a configuration warning, the warning isn't displayed immediately. Instead, the warning is only displayed after reloading the scene. The opposite is also true: in some cases, fixing a warning will require the user to reload the scene to make the warning icon go away.

**Steps to reproduce:** Create a CPUParticles node and assign a mesh to it. Notice how it still has a warning icon, but clicking it doesn't display any popup. Reload the scene (using Revert Scene or by closing and reopening the editor) and notice the warning icon disappearing.

**Comment by KoBeWi** [comment]
Still valid in 819ef12

**Comment by ExquisiterEmil** [comment]
I think this still happens in Godot4 beta10, at least when overriding `_GetConfigurationWarnings` and calling `UpdateConfigurationWarnings` in a custom script.

**Comment by KoBeWi** [comment]
Fixed.
