### ISSUE TITLE
build error for android x86 in drivers/opus/silk (no such instruction: `smulbb %eax,%eax,%ebp')

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#2962]
```
scons -j 4 p=android target=release android_arch=x86
```
```
#!/bin/sh
cd godot

export ANDROID_NDK_ROOT=/home/alexey/Android/android-ndk-r10d/
export ANDROID_HOME=/home/alexey/Android/Sdk/

# git does not allow empty dirs, so create those
mkdir -p platform/android/java/libs/armeabi
mkdir -p platform/android/java/libs/x86
mkdir -p ../templates

#Android Release

#scons -j 4 p=android target=release
scons -j 4 p=android target=release android_arch=x86

cp bin/libgodot.android.opt.armv7.neon.so platform/android/java/libs/armeabi/libgodot_android.so
cp bin/libgodot.android.opt.x86.so platform/android/java/libs/x86/libgodot_android.so

ant -s platform/android/java/build.xml release

cp platform/android/java/bin/Godot-release-unsigned.apk ../templates/android_release.apk
```

![builr_e_and_x86](https://cloud.githubusercontent.com/assets/233268/11485753/105a53ac-97c6-11e5-8738-ab16d6b80762.jpg)

ndk : android-ndk-r10d

**Comment by akien-mga** [comment]
Looking at the log it seems to be related to the opus driver. Any idea @vnen?

@ret80 Could you try to build with ```opus=no``` to confirm that it works better?

**Comment by punto-** [comment]
Probably it assumes that ANDROID_ENABLED means it can turn on the ARM
optimization, that's why it's complaining about that arm assembler.

**Comment by akien-mga** [comment]
Thanks for the hint @punto-, I think the devil lies here: https://github.com/godotengine/godot/blob/master/platform/android/detect.py#L213-L215

```
	if(env["opus"]=="yes"):
		env.Append(CFLAGS=["-DOPUS_ARM_OPT"])
		env.opus_fixed_point="yes"
```

**Comment by akien-mga** [comment]
I guess it could be changed to:
```
    if(env["opus"]=="yes"):
        if (env["android_arch"]=="armv6" or env["android_arch"]=="armv7"):
            env.Append(CFLAGS=["-DOPUS_ARM_OPT"])
        env.opus_fixed_point="yes"
```

**Comment by ret80** [comment]
proposed changes to resolve the issue. thank

**Comment by akien-mga** [comment]
Thanks for the confirmation @ret80, I'll merge it then.

**Comment by punto-** [comment]
Also maybe there's a flag to turn on x86 optimization? I don't know how bad
opus is on x86..

**Comment by akien-mga** [comment]
Maybe it's optimised for x86 by default and only needs specific parameters for arm I guess? https://github.com/godotengine/godot/blob/9827c3cd26e4df8d382b1d41322eed6548a6453f/drivers/opus/opus_config.h

**Comment by vnen** [comment]
@punto- The optimizations for x86 are the same for mobile and for desktop and enabled by default (assuming both have SSE). I don't have any x86 device to test though.

**Comment by ret80** [comment]
x86 You can check on the emulator
