### ISSUE TITLE
GDScript - validate conditions when comparing non-nullable types to nulls

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot#29631]
Consider following code:

```
var integer := 1

func test() -> void:
    if(integer == null):
        pass
```

semantic analyzer does not complain - and it probably should, even checking `1 == null` is possible. I don't see how this behavior is useful - in my mind it can only lead to bugs and developer's mistakes. I think that semantic analysis should prevent comparing non-nullable types to nulls and raise error if such think occurs. What do you guys think?

**Comment by Zylann** [comment]
Slightly related: https://github.com/godotengine/godot/issues/26375

**Comment by iwek7** [comment]
I just realized that null is used to check if variable is uninitialized, as described in https://github.com/godotengine/godot/pull/11437. Seems hacky but well... Closing this since this subject was discussed already.
