### ISSUE TITLE
Latest Godot GNative Bindings doesn't compile

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#29630]
**Godot version:**
3.1.1

**OS/device including version:**
OSX 10.12.6

**Issue description:**
I was following the instructions on setting up GDNative on the latest documentation and I get an error when compiling generating and compiling the bindings. It has to do with the (I think, new) `AudioEffectSpectrumAnalyzer`.

I generated the bindings using Godot 3.1.1 and want to use them for GDNative.

Here's the error:
```
In file included from src/AudioEffectSpectrumAnalyzer.cpp:1:
include/AudioEffectSpectrumAnalyzer.hpp:34:31: error: no type named 'FFT_Size' in 'godot::AudioEffectSpectrumAnalyzer'
        AudioEffectSpectrumAnalyzer::FFT_Size get_fft_size() const;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
src/AudioEffectSpectrumAnalyzer.cpp:65:30: error: no type named 'FFT_Size' in 'godot::AudioEffectSpectrumAnalyzer'
AudioEffectSpectrumAnalyzer::FFT_Size AudioEffectSpectrumAnalyzer::get_fft_size() const {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
src/AudioEffectSpectrumAnalyzer.cpp:70:39: error: no member named 'FFT_Size' in 'godot::AudioEffectSpectrumAnalyzer'
        return (AudioEffectSpectrumAnalyzer::FFT_Size) ___godot_icall_int(mb, (godot_object *) this);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
3 errors generated.
scons: *** [src/AudioEffectSpectrumAnalyzer.o] Error 1
```

**Edit**: Actually, even when GDNative uses its own api.json, there are still tons of errors when trying to compile. I tried compiling with 3.0 and 3.1, both don't compile following the latest Godot documentation on GDNative.

In the 3.1.1 bindings, the `ResourceFormatLoader.hpp` on line 30 has a method defined like
```
bool handles_type(const String typename);
```

which results in this error:
`error: expected a qualified name after 'typename'`

It's easily fixable by changing the `typename` to `type_name` in the generated api.json, but should probably be fixed so godot generates the proper api.json.

**Steps to reproduce:**
Follow the steps to setup the C++ bindings for GDNative from the documentation using Godot 3.1.1.

**Comment by Faless** [comment]
See #28084 , this is already fixed in `3.1` branch, and will be included in `3.1.2`.
