### ISSUE TITLE
Node._unhandled_input() doesn't catch events that are not handled by GUI controls

### ISSUE THREAD

**Issue by Jeto143** [godotengine/godot#29637]
**Godot version:**

3.1.1

**Issue description:**

It is my understanding (though I may be mistaken) that [`Node._unhandled_input`](http://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-unhandled-input) should catch any event that isn't handled by the GUI. Instead, it appears to never catch events that occur over a GUI control, whether they were handled or not.

**Steps to reproduce:**

- Add a node to an empty scene, such as a Sprite.
- Add a control to the scene, such as a Panel, and place it partly over the sprite.
- Set the control's `mouse_input` property to `MOUSE_FILTER_PASS` so that all unhandled mouse events get propagated.
- Override `Node._unhandled_input` in Sprite.
- Notice that none of the mouse events over the panel (move or click) are caught by it.

So... what entity consumed the event, exactly?

**Minimal reproduction project:**

[unhandled_input.zip](https://github.com/godotengine/godot/files/3269948/unhandled_input.zip)

Click on the sprite to see a message in the console. Click on the panel over the sprite and notice that no message gets displayed.

**Comment by Zylann** [comment]
It should work if you set the mouse mode to `MOUSE_FILTER_IGNORE`. Though I don't know what would be the difference with `MOUSE_FILTER_PASS` then... maybe it catches it by default and it makes sense only with some controls?

**Comment by Jeto143** [comment]
@Zylann You're right--it does produce the expected result with `MOUSE_FILTER_IGNORE` on the control, which I should've mentioned in the OP. Thanks for pointing it out.

However, I feel like things should behave the exact same with `MOUSE_FILTER_PASS` unless an event is marked as handled by consuming it through `Control.accept_event()` (within `_gui_input`). That would seem more logical and consistent, unless I'm missing something.

**Comment by nezvers** [comment]
I also encountered the same problem - mouse -> pass blocks event to go further to _unhandled_input.
"Pass" should mean - process and allow go to unhandled input.
"Ignore" should mean - don't process and allow to go to unhandled input.

**Comment by dluke** [comment]
Just mentioning that, after some pain trying to figure this out, I found clearly stated in the documentation for `MouseFilter.MOUSE_FILTER_PASS` that

> Even if no control handled it at all, the event will still be handled automatically, so unhandled input will not be fired.

In fact, I suspect that a wise developer had a good reason for this design and I'm just starting to appreciate it.

**Comment by KoBeWi** [comment]
As stated above, this is not a bug.
