### ISSUE TITLE
AStar possible bug ?

### ISSUE THREAD

**Issue by PoirotovBrk** [godotengine/godot#29649]
Godot 3.1.1
Windows 10 64 bits

So, I'm making a simple hex grid based 2D game and I am heavily using the built-in AStar. Normally it works ok.

However I have stumbled upon on something which I percieve as bug. Basically the problem is, when I have neighbouring nodes, sometimes the built-in _get_id_path()_ function doesn't work as expected.

For example, lets say we have 3 interconnected nodes like a triangle, with the third node having a weight of 3.

One would expect that for _get_id(1,3)_ the function would return _[1, 3]_ as this is the quickest (shortest) path.

However in the small example I have it returns _[1, 2 , 3]_ .  Is this a bug ? 

Minimal Example; here is my Scene Structure;

```
Node2D
-- TileMap

```
And this is the GDScript code which I use in TileMap;

```
extends TileMap

var myStar = AStar.new()

func _ready() -> void:

    cell_half_offset = TileMap.HALF_OFFSET_X
    cell_tile_origin = TileMap.TILE_ORIGIN_TOP_LEFT
    
    #create 3 static bodies as children of TileMap
    var aStarIndex:int = 1
    var myStaticBody1 = StaticBody2D.new()
    var pos1 = Vector2(1,1)
    myStaticBody1.position = pos1
    add_child(myStaticBody1)
    
    var myStaticBody2 = StaticBody2D.new()
    var pos2 = Vector2(2,1)
    myStaticBody1.position = pos2
    add_child(myStaticBody2)
    
    var myStaticBody3 = StaticBody2D.new()
    var pos3 = Vector2(1,2)
    myStaticBody1.position = pos3
    add_child(myStaticBody3)   
    
    var myKids = get_children()
    
    var c = 1
    
    #add the positions of the static bodies to the AStar object
    for aKid in myKids:

        if c == 3:
            #point number 3 has some higher weight than the rest
            myStar.add_point(c, Vector3(aKid.position.x, aKid.position.y, 0), 3)     
        else:
            myStar.add_point(c, Vector3(aKid.position.x, aKid.position.y, 0))
        c += 1
        
    #connect the 3 points with each other
    myStar.connect_points(1,2)    
    myStar.connect_points(2,3)  
    myStar.connect_points(1,3)   
        
        
    var myPoints = myStar.get_points()
    for aPoint in myPoints:
        print("point_", aPoint, " is connected with: ", myStar.get_point_connections(aPoint))
        
    #this should return me the quickest path between points 1 and 3 right ?
    var myArray = myStar.get_id_path(1,3)
    
    print("myPath : ", myArray)
```

**Comment by bojidar-bg** [comment]
I think this is correct behavior from AStar. The weight scale is applied to the cost of getting to the node. Here is a table with the costs you are getting:

| `` | A | B | C |
| `` | A | B | C |
| `` | A | B | C |
| `` | A | B | C |

**Comment by bojidar-bg** [comment]
I cannot reproduce with this code:
```gdscript
func _ready():
	var a = AStar.new()
	a.add_point(1, Vector3(1, 1, 0))
	a.add_point(2, Vector3(2, 1, 0))
	a.add_point(3, Vector3(1, 2, 0), 3)
	a.connect_points(1, 2)
	a.connect_points(2, 3)
	a.connect_points(1, 3)
	print(a.get_id_path(1, 3)) # [1,3]
```

**Comment by raphael10241024** [comment]
can't reproduce it too

**Comment by PoirotovBrk** [comment]
It seems its not a bug but an error in my code.  (i assign the false position in each static body:

    #create 3 static bodies as children of TileMap
```
    var aStarIndex:int = 1
    var myStaticBody1 = StaticBody2D.new()
    var pos1 = Vector2(1,1)
    **myStaticBody1.position = pos1**
    add_child(myStaticBody1)
    
    var myStaticBody2 = StaticBody2D.new()
    var pos2 = Vector2(2,1)
    myStaticBody**1**.position = **pos2**
    add_child(myStaticBody2)
    
    var myStaticBody3 = StaticBody2D.new()
    var pos3 = Vector2(1,2)
    myStaticBody**1**.position = **pos3**
    add_child(myStaticBody3) 
```
False Alarm, but thanx for help everyone.

**Comment by PoirotovBrk** [comment]
Not a bug but an error in my own code.

**Comment by PoirotovBrk** [comment]
Well, I did had an error in code, but the possible bug actually still exists (or so I think).

bojidar-bg made a simple example so I will just reuse his code with one difference being point positions;

```
func _ready():
    var a = AStar.new()
    a.add_point(1, Vector3(1, 3, 0))
    a.add_point(2, Vector3(1, 4, 0))
    a.add_point(3, Vector3(2, 4, 0), 3)
    a.connect_points(1, 2)
    a.connect_points(2, 3)
    a.connect_points(1, 3)
    print(a.get_id_path(1, 3))  # [1, 2, 3]
```

So the thing is if one uses Points:

1 = (1,3)
2 = (1,4)
3 = (2,4)

The result is not [1,2] as expected but rather [1,2,3]

**Comment by raphael10241024** [comment]
1-3 cost is 1.4*3=4.2
1-2-3 cost is 1+1*3=4
the answer was actually right

**Comment by PoirotovBrk** [comment]
The way I see it, the bug comes from weighing factor; 

This returns the expected result;
```
func _ready():
    var a = AStar.new()
    a.add_point(1, Vector3(1, 3, 0))
    a.add_point(2, Vector3(1, 4, 0))
    a.add_point(3, Vector3(2, 4, 0))
    a.connect_points(1, 2)
    a.connect_points(2, 3)
    a.connect_points(1, 3)
    print(a.get_id_path(1, 3)) # [1,3]
```


This return the bugged result;
```
func _ready():
    var a = AStar.new()
    a.add_point(1, Vector3(1, 3, 0))
    a.add_point(2, Vector3(1, 4, 0))
    a.add_point(3, Vector3(2, 4, 0), 3)  # weight factor of 3 added 
    a.connect_points(1, 2)
    a.connect_points(2, 3)
    a.connect_points(1, 3)
    print(a.get_id_path(1, 3)) # [1, 2, 3]
```

**Comment by raphael10241024** [comment]
If you set weight for point 3 as 3, the shortest way changes too, It's correct.

**Comment by akien-mga** [comment]
I didn't do the math but as per the docs it seems consistent: https://docs.godotengine.org/en/3.1/classes/class_astar.html#class-astar-method-add-point

> The algorithm prefers points with **lower** weight_scale to form a path.

So the path from 1 to 3 (`3 * sqrt(2) = 4.243`) is heavier than the path from 1 to 2 to 3 (`1 * 1 + 3 * 1 = 4`).
