### ISSUE TITLE
Change PhysicsBody programatically 

### ISSUE THREAD

**Issue by SilverFoxA** [godotengine/godot#2964]
Out of curiosity I was wondering is it possible to change the PhysicsBody 2d? Looked into the methods but the static body doesn't have the gravity parameter nor the PhysicsBody class has any method to change the same.

Please let me know if there's any alternative 
Thank you

**Comment by bojidar-bg** [comment]
@SilverFoxA ~ I don't really understand this issue... You want to tweak the global gravity parameter, or the `gravity_scale` of a RigidBody2D? Or maybe you want to change the gravity for only one RigidBody2D?

**Comment by WeAthFoLD** [comment]
Static body doesn't have gravity at all, as is described in the wiki:

> A static body is a simple body that is not intended to move. They don't consume any CPU resources in  contrast to a RigidBody2D so they are great for scenaro collision.

And so should be its base node PhysicsBody. KinematicBody is intended to be user-controlled so it doesn't have gravity either. But you can use `set_gravity_scale` for RigidBody2D.
