### ISSUE TITLE
Resize Control Node based on anchors.

### ISSUE THREAD

**Issue by Gfurst** [godotengine/godot#2965]
The issue is that whenever nodes have their size changed, either by calling the function or a container that have changed children, the node always expands to the right and bottom.

Instead it should be depended on the anchor points, for example, in the horizontal dimension:
- if anchor are both "begin" then it should expand to right;
- if anchor are both "end" then it should expand to the left instead, respecting the right or end margin;
- if anchor are both "center" or mixed, they expand equally the same to both sizes, respecting central position on the parent.

**Comment by kubecz3k** [comment]
I think it would be quite bad to make this dependent on anchoring, it would be difficult to do anything with UI from code if you would need to always check where is pivot point for your computations (right edge, left edge, 4 corners etc). Anchoring and origin point are two different concepts in my opinion... In this issue I have proposed to simply add 'centered' ability of Sprite2D to Control nodes: https://github.com/godotengine/godot/issues/5245

**Comment by Gfurst** [comment]
@kubecz3k I kinda disagree, the anchoring provides just that, a anchor for it to be relative to...
For example, if you want something sitting on the right edge at a certain padding, is relative to that edge. The way it currently works, if the node grows for whatever reason it grows to the opposite side. Thus requiring calculation for it to be place with the right padding again.

In that same manner anchoring a object on the center, should mean make the center its relative origin. If the object grows for whatever reason, again its always to the bottom and the right, thus not being centered anymore...

**Comment by kubecz3k** [comment]
@Gfurst but then it would be impossible to have nice ui scaling animations for controls which anchoring is set to something other than centered. Further more in this case even centered anchored controls by design should have bad scaling animations since 'origin' point for the scale should be at anchor center, not on the center of the control itself.

**Comment by kubecz3k** [comment]
Or maybe I'm recognizing this issue wrongly and I should not confuse control scale and it's size?

**Comment by Gfurst** [comment]
The issue at hand is that Godot will always grow 2d nodes to the to the bottom and right (and shrink in the opposite way), so it always grows shrinks from the origin point (upper-left corner)(might need confirmation on this). 

Therefor, we both might be correct on this, however, just having a centered origin does not solve it completely. Anchor points should mean their relative origin with their parent. This does work well for animation: if you have a scaling window coming from the right, its anchored in the right border, it grows from the right.... If you have a spinning object in the the center, it grows and spins from the center.

At first I thought your suggestion was to have all origin on the center on the viewport, is it actually having a relative origin within each node2d? If that is the case it could be done by having a relative node to house the rotating node, the rotating node being anchored to the center, and the housing node being positioned wherever on the screen. That is, assuming the anchoring worked as assumed in this issue.

**Comment by reduz** [comment]
This was finally implemented, sorry it took so long. Figuring out how to do it had to click.

**Comment by Gfurst** [comment]
Beautiful, thanks mate!
