### ISSUE TITLE
Does not play video after export

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#29652]
**Godot version 3.1.1** 
**Linux**

Does not play video after export.

I've created this error message before. It was combined with a duplicate and closed. Now I tested the export per Godot 3.1.1 - it does not work. I added the file type *.ogv to the list of exported - but it's still not working.

**Comment by groud** [comment]
Could you elaborate a little bit more than "It does not work" ?
Also, please provide a sample project.

**Comment by DimitriyPS** [comment]
> Could you elaborate a little bit more than "It does not work" ?
Just didn't play the video and the program hung.

I still don't know the root cause... but I found something that interfered. Along with the video files were files *.import created by previous version of Godot. After I deleted them - everything worked!
