### ISSUE TITLE
HIDPI HTML in browser not working

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#29661]
**Godot version:**

3.1.1-stable

**OS/device including version:**

GTX1050

**Issue description:**

playing godot in HTML export on 4k screen looks crappy (aliasing issue)
for now zooming out manually works to make it look good
I tried multiplying the canvas size with window.devicePixelRatio and scaling the body with 1/window.devicePixelRatio in the HTML template. It looks good but now godot does not register mouse click events on buttons

**Steps to reproduce:**
template line 164
```
function adjustCanvasDimensions() {
	canvas.width = innerWidth * window.devicePixelRatio;
	canvas.height = innerHeight * window.devicePixelRatio;
}
animationCallbacks.push(adjustCanvasDimensions);
adjustCanvasDimensions();
document.getElementsByTagName("BODY")[0].style.scale = 1/window.devicePixelRatio
```

**Minimal reproduction project:**

any project with above changes to the html template on a 4k or similar screen

**Comment by Phoenix1747** [comment]
Same issue here, can confirm HIDPI works for stand-alone executables (at least in windows) but not in a browser.

**Comment by akien-mga** [comment]
MRP from #29725:

> [godot-hidpi-bug.zip](https://github.com/godotengine/godot/files/3282533/godot-hidpi-bug.zip)
>
> I've made a simple script that draws dots where a mouse click is detected. Simply open a build with both shells, open it in a browser and click around the game screen.

**Comment by scottkunkel** [comment]
Short term hack, until proper, clean implementation:
HTML template:
```
			function adjustCanvasDimensions() {
				let ctx = canvas.getContext('webgl');
				let ratio = window.devicePixelRatio || 1;
				canvas.width = innerWidth * ratio;
				canvas.height = innerHeight * ratio;
				canvas.style.width = (canvas.width / ratio) + 'px';
  				canvas.style.height = (canvas.height / ratio) + 'px';
			}
			animationCallbacks.push(adjustCanvasDimensions);
			adjustCanvasDimensions();```

os_javascript.cpp:
mouse_button_callback and mousemove_callback:
change line to 
```ev->set_position(Point2(p_event->canvasX * emscripten_get_device_pixel_ratio(), p_event->canvasY * emscripten_get_device_pixel_ratio()));```

**Comment by kroltan** [comment]
I have got permission from the company I work for to contribute code on this.

I think it's better to correct for differing canvas pixel size and actual visible size, since not only will this fix the highdpi case, but wherever there is a discrepancy between canvas pixels and screen pixels.

Soon I'll set a PR up, just reading the guidelines first.

**Comment by Guang1234567** [comment]
Hello @akien-mga 

> Fix pointer position in hidpi-corrected resolutions on web #29786


> @akien-mga akien-mga added this to the 3.2 milestone on 16 Jun 2019

still not working on `godot v3.2.3`, thanks.

Below screen recording shows the problem:


https://user-images.githubusercontent.com/8240718/105017454-bee52700-5a7e-11eb-99ad-ff9c3e292c33.mp4

**Comment by akien-mga** [comment]
Please open a new issue with a minimal reproduction project (project zip) so that we can see if it's an engine bug or a project configuration issue.

**Comment by Guang1234567** [comment]
- macOS  10.15.7

- browser for macOS (version 87.0.4280.141) ,  newest at this moment.

- export template


![Uploading 1611050174827.jpg…]()


[godot_hidpi_html5_chrome_macOS.repo](https://github.com/Guang1234567/Godot_MyFirstGame.git)

**Comment by Guang1234567** [comment]
- macOS  10.15.7

- browser for macOS (version 87.0.4280.141) ,  newest at this moment.

- export template


![1611050174827](https://user-images.githubusercontent.com/8240718/105019094-ae35b080-5a80-11eb-9ae6-72683c25a560.jpg)


[godot_hidpi_html5_chrome_macOS.repo](https://github.com/Guang1234567/Godot_MyFirstGame.git)

**Comment by Guang1234567** [comment]
> Please open a new issue with a minimal reproduction project (project zip) so that we can see if it's an engine bug or a project configuration issue.

project zip 👆👆👆

**Comment by Phoenix1747** [comment]
> Please open a **new** issue [...]
@Guang1234567

**Comment by Guang1234567** [comment]
> > Please open a **new** issue [...]
> 
> @Guang1234567

👌, thanks remind.

[new issue](https://github.com/godotengine/godot/issues/45323)
