### ISSUE TITLE
FileDialog current_* values should not be saved to scene files

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#29674]
**Godot version:** 3.1.1

**Issue description:**

The `FileDialog` node has a few string properties called `current_dir`, `current_file`, and `current_path`. These are fine to generate on the fly and use while the game is running, but they should not be saved to `.tscn` or similar files. Every system that this project is opened on will change this path to be something else. If we really need to save it, then save it inside the `.godot` folder.

**Minimal reproduction project:**

The problem is visible here: https://github.com/godotengine/godot-demo-projects/pull/89#discussion_r292378795

**Comment by MatteoPiovanelli-Laser** [comment]
Hello. I think this is still an issue now in Godot 3.2.3
See this other issue I opened on a Godot project before finding this thread: https://github.com/godotengine/godot/issues/29674

Having those properties automatically save in the .tscn file is troublesome for VCS.

**Comment by Calinou** [comment]
> This is a security/privacy concerning bug. Someone please delete the "enhancement" tag and put e.g. "high priority".

If you consider your real name to be sensitive information, don't use your real name as your PC username. I know it requires a fair amount of work to move everything, but it's worth it in the long run :slightly_smiling_face:

**Comment by Zireael07** [comment]
@Calinou: Counterargument: it's fairly easy to edit screenshots and logs when posting. On the other hand, you can't edit these fields without breaking stuff.

Also, many companies require user name to be your real name, end of story - they won't let you change.

**Comment by AndreaCalligaris** [comment]
> If you consider your real name to be sensitive information, don't use your real name as your PC username. I know it requires a fair amount of work to move everything, but it's worth it in the long run slightly_smiling_face

As you can see I have my real name in this GitHub account, so it's not about me: it's about the fact that the bug described in this issue saves an entire path in the scene file. It's not about the name of the PC account, it's about any other folder, any other content that you can browse on your computer. Let's say that for whatever reason, for testing your game you traverse a path on your PC named `/home/JohnSmith/Documents/MyVerySecretProjectAboutSomething/secret_information_about_XYZ.txt`, that path will be saved in the scene file. That, as I pointed out, is a security/privacy concerning bug.
