### ISSUE TITLE
Area2D and Area use same functions, but with different names

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29670]
**Godot version:**
3.2 master

**Issue description:**
Function to set/get audio_bus_name property use 
in Area function set_audio_bus
and in Area2D function set_audio_bus_name

![Zrzut ekranu z 2019-06-11 10-54-51](https://user-images.githubusercontent.com/41945903/59258259-e71c6b00-8c37-11e9-92c1-b59f8a47a61c.png)

**Comment by akien-mga** [comment]
The `Area` methods should be renamed to include `_name`, so that they match the property. Moving this to #16863 as it's compat breaking.
