### ISSUE TITLE
Error calling method from signal 'animation_finished': 'AnimationPlayer::_on_AnimationPlayer_animation_finished': Method not found.

### ISSUE THREAD

**Issue by Josh012422** [godotengine/godot#29689]
**Godot version:**

Godot Mono Stable 3.1.1

**OS/device including version:**

Intel HD Graphics 4000 1536 VRAM
MacOS 10.14 Mojave

**Issue description:**

6 Errors after building the project, look:
![Captura de Pantalla 2019-06-11 a la(s) 1 26 43 p  m](https://user-images.githubusercontent.com/38227521/59296881-9a8f5a80-8c4c-11e9-8eea-c6a3af0d4bc2.png)

The expected was: when finishing this animation:
https://media.giphy.com/media/Vg4zz8fkSZEfFRHryS/source.mov 

Do a blur in animation then change scene then a blur out animation, nothing of that happens
and put me an error saying:   Error calling method from signal 'animation_finished': 'AnimationPlayer::_on_AnimationPlayer_animation_finished': Method not found.
  
See this:
https://youtu.be/LtVO03F3_48 

 

**Steps to reproduce:**
Open the project and build it

**Minimal reproduction project:**

[Mah Geim TresDe.zip](https://github.com/godotengine/godot/files/3278085/Mah.Geim.TresDe.zip)(Dont judge the name)

**Comment by qarmin** [comment]
Project contains only project.godot file

**Comment by KoBeWi** [comment]
There's probably a typo somewhere.

**Comment by Josh012422** [comment]
where

**Comment by Josh012422** [comment]
[Mah Geim TresDe.zip](https://github.com/godotengine/godot/files/3278406/Mah.Geim.TresDe.zip)
The zip with all files

**Comment by KoBeWi** [comment]
> where

In the signal connection. It's connected to AnimationPlayer, which doesn't have a script.

**Comment by Josh012422** [comment]
and what should I put in the script

**Comment by KoBeWi** [comment]
I guess you should read this: https://docs.godotengine.org/en/3.1/getting_started/step_by_step/signals.html

You need a proper method in the script.

**Comment by Josh012422** [comment]
thanks i will read it

ps: im starting with godot, i dont now much of godot

**Comment by KoBeWi** [comment]
Well, if you have a problem with your project and you are not sure why, try asking on [community channels](https://godotengine.org/community) first before creating issue on GitHub, to make sure it's actually a bug.

**Comment by Josh012422** [comment]
ok  I'm going to keep that in mind
