### ISSUE TITLE
Editor Settings tooltips

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#29694]
**Godot version:**
3.1.1

**Issue description:**
Apparently, Editor Settings don't support setting descriptions, unlike Project Settings. It would be useful to have them in case of settings that can't really have a descriptive name (like this probably https://github.com/godotengine/godot/pull/29517#issuecomment-500774118).

**Comment by rcorre** [comment]
It seems that the `EditorInspector` used for the `ProjectSettings` and `EditorSettings` dialog pulls its tooltips from the docs. For some reason `ProjectSettings` has docs for all its members and `EditorSettings` does not, in spite of both being generated on-the-fly (using `GLOBAL_DEF` and `EDITOR_DEF`, respectively). Does anyone know how the doc xml for `ProjectSettings` gets populated with all these dynamic members?

**Comment by Calinou** [comment]
@rcorre This is done here: https://github.com/godotengine/godot/blob/fafb0ba06df9417a22bd8deb31a61feeb24de794/editor/doc_data.cpp#L236-L237

Unfortunately, you can't do the same with EditorSettings as the editor (or doctool) will crash on startup.

**Comment by rcorre** [comment]
ah crap, I just tried that :(

**Comment by KoBeWi** [comment]
The proposals are banned on main repo, so I just removed the "feature proposal" label. Hope it's ok in this case XD

**Comment by akien-mga** [comment]
I think it would be good to have in a formal GIP simply for visibility, as it's not a "simple" enhancement but requires significant work to make it happen. I don't have a strong opinion either way though, it's on the line :)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1339, as feature proposals are now tracked on the Godot proposals repository.
