### ISSUE TITLE
NetworkedMultiplayerENet.create_server() listening on UDP6

### ISSUE THREAD

**Issue by Inseighn** [godotengine/godot#29693]
**Godot version:**
3.1.1

**OS/device including version:**
Fedora 30

**Issue description:**
When creating a high level network server using NetworkedMultiplayerENet.create_server() Godot listens on only the UDP6 port. 

**Steps to reproduce:**
Create a new Spatial node, attach a script: 
```
extends Spatial

var game_server : NetworkedMultiplayerENet
func _ready():
	game_server = NetworkedMultiplayerENet.new()
	game_server.create_server(52380, 200)
	get_tree().set_network_peer(game_server)
	pass 
```
![Screenshot from 2019-06-11 16-02-31](https://user-images.githubusercontent.com/7285156/59306653-5c9d3100-8c62-11e9-8216-09d0f4c78595.png)

**Minimal reproduction project:**
[Godot_Network_Issues.zip](https://github.com/godotengine/godot/files/3278544/Godot_Network_Issues.zip)

Edit:
I think the issue is due to the following line:
https://github.com/godotengine/godot/blob/30e8b53c380a7bc88fbea768e31bc6b64f27f0ef/modules/enet/networked_multiplayer_enet.cpp#L127-L140

It looks like when GODOT_ENET is defined it only connects on IPv6? Does that mean the build I'm using was compiled to only use IPv6 in this case?

**Comment by singerbj** [comment]
I'm running into this same thing. @Inseighn How did you get around this issue?

**Comment by Calinou** [comment]
I wonder if this is related to https://github.com/godotengine/godot/issues/36418.
