### ISSUE TITLE
How to purchase on iOS ?

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29691]
my code:

//purchase for id 'getpro'
```
InAppStore = Engine.get_singleton("InAppStore")
var result = InAppStore.purchase( { "product_id": "getpro" } )
```
//restore 
```
InAppStore = Engine.get_singleton("InAppStore")
var result =  InAppStore.restore_purchases()
```

Restore button click don't show the ipa board. Purchase button press with a board input password. But it warning me that I can't test the ipa right now. 

![image](https://user-images.githubusercontent.com/1890538/59304574-18924680-8ccb-11e9-975d-b83a22e84f95.png)

Can you supply a simple code with this. The docs tech less infomation. I don't know what is the return result.

**Comment by ArdaE** [comment]
You might wanna post your question at https://godotengine.org/qa/questions. The issue database is for issues that Godot has, not issues you have with Godot (or Apple for that matter, as your problem seems to be a more of an Apple sandbox account setup issue).

**Comment by zszen** [comment]
Fixed with upload app to testflight
