### ISSUE TITLE
"$" parse error for paths with math operands

### ISSUE THREAD

**Issue by tastesliketriangle** [godotengine/godot#29705]
The get_node short hand $ has a bug where a valid node path that contains a math operand will try to perform math on the path and fail.

for instance:
`$GUI/Panel/VSplitContainer/Label-2`

produces the error:
`Parse Error: Invalid operand types ('Node' and 'int') to operator '-'.`

**Comment by akien-mga** [comment]
I don't think it's a bug, you should use `$"GUI/Panel/VSplitContainer/Label-2"`.

**Comment by KoBeWi** [comment]
Yeah, in the same way you can't use spaces. This is just a limitation of $ without quotes.
