### ISSUE TITLE
default_linear_damp ignored in 3D

### ISSUE THREAD

**Issue by io12** [godotengine/godot#29707]
**Godot version:**

3.1.1.stable.official

**Issue description:**

The `default_linear_damp` property under `Project->Project Settings->Physics->3d->Default Linear Damp` does not affect anything.

**Steps to reproduce:**

Create a RigidBody with `linear_damp = -1`, set the property as described above from `0.1` to `1`. The RigidBody will fall at a normal rate. If you set the RigidBody's `linear_damp` to `1`, it will have a noticeable effect, even though it should be the same (since the project's default should already be 1).

**Minimal reproduction project:**

[default_linear_damp_bug.zip](https://github.com/godotengine/godot/files/3279601/default_linear_damp_bug.zip)

**Comment by io12** [comment]
Incidentally, this problem doesn't exist in 2D.

**Comment by KoBeWi** [comment]
Fixed in 3.2.3
