### ISSUE TITLE
Need to be able to add *.ini as resources

### ISSUE THREAD

**Issue by Malkierian** [godotengine/godot#29709]
Version 3.1.1
Windows 10

So I think it's rather silly to have support for .ini files for config purposes, and not be able to load a .ini file into the resources as a default config.  I request that the editor be able to recognize and package .ini files in the project folder for use with `load("res://")`

**Comment by sparkart** [comment]
.ini file is not loadable via `load("res://")`?

**Comment by dalexeev** [comment]
#29655

**Comment by Malkierian** [comment]
No, it's not.  I have it in the project folder, and when debugging via the play button in the top right of the editor, it can still locate it, but exporting the project to either Android or Windows, the ini file is not included in the packaging.

Looking at that other issue, it seems like a lot of "supported" formats are not packable resources according to the engine.

**Comment by akien-mga** [comment]
You should add a filter to export `*.ini` files: http://docs.godotengine.org/en/latest/getting_started/workflow/export/exporting_projects.html#export-mode

**Comment by Malkierian** [comment]
Why should I have to do that myself for something that the engine has helper functions for?  It should be built-in.

**Comment by akien-mga** [comment]
What helper functions are you referring to? The engine does not know what custom files you may want to access at runtime if they are not registered as resources. This filter lets you register them as resources to ensure that they are exported.

**Comment by Malkierian** [comment]
I'm talking about `Config`.  It was made to load and save INI format.  So why aren't .ini files automatically included in non-resource exports?

**Comment by akien-mga** [comment]
There is no INI format per se, and `.ini` is not a standard extension. The `ConfigFile` API is made to load and write INI-style (i.e. `[section]` and `key=value` entries) config files, but those don't have to come with a `.ini` extension.

It's actually more common in Godot projects (and for the editor itself) to use the `.cfg` extension for those files. But even then, it's just a matter of convention, you could also use `.my_config_format`.
