### ISSUE TITLE
Vector2.clamped doesn't handle INFs

### ISSUE THREAD

**Issue by razcore-rad** [godotengine/godot#29714]
**Godot version:**
3.1.1.stable.official

`Vector2.clamped` returns `nan`s (Not a Number) when operating on vectors with `INF` components while `clamp` global function seems to work just fine, I'd expect `Vector2.clamped` to be able to handle `INF`s as well.

**Comment by razcore-art** [comment]
I think this is a more general problem with `INF` `Vector` math as `Vector2(INF, 0) * Vector2.ZERO` also gives `Vector2(-nan, 0)` say. I haven't tried `Vector3` yet

**Comment by KoBeWi** [comment]
Still valid in 173ebe487

Although if it's impossible to fix it without math hacks (affecting performance), it should just be documented.
