### ISSUE TITLE
Bring selected script file's name into view

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#29721]
**Godot version:**
3.1.1

**OS/device including version:**
mac OS 10.14.5

**Issue description:**
When .gd script files get selected automatically in the script editor for whatever reason (e.g. breakpoint/error during debugging, changing scene tabs, etc.), the displayed script file's name gets selected in the "Scripts Panel" (left pane of the script editor), but the selection isn't brought into view. So when a larger number of scripts are open than fits onscreen, which is a common occurrence on laptop screens, there's no visible indication of what script you're looking at in the script editor, without scrolling the file list to see what's highlighted every time.

**Steps to reproduce:**
Open a number scenes with scripts attached to them. Either open a large number of them or reduce Godot's window size so there's a larger number of open scripts than fits the screen.  Then change scene tabs, which will automatically display the scene's script but won't bring the selection in left pane into view if it's outside of the view.

**Solution:**
1. Please bring the selected script file's name into view (i.e. scroll the list as needed)
2. In addition to 1 above, consider adding the script file's name somewhere else. For example, the selected scene's name is displayed in two locations right now: the tabs above the script editor, and Godot's window title. Consider doing the same for script file names, i.e. append the open script's name to the window title: e.g. "Godot Engine - MyProject - MyScene.tscn - MyScript.gd"

**Comment by sparkart** [comment]
It's actually right above the "methods" list. But yeah, I agree.... I feel like the scripting editor is kinda clunky.

**Comment by ArdaE** [comment]
> It's actually right above the "methods" list.

Yes, that's where the list is. And **it doesn't bring into view the focused entry, when the focused entry changes**. Hence my proposal 1 above. My second proposal is simply an easy to implement, nice-to-have feature, so the script's name is always readily available (like the scene name). The first proposal is a must have, and is standard behaviour in every software that automatically selects any entry on any list.

**Comment by ArdaE** [comment]
Thanks @sparkart, I see that now; that's helpful. Any auto-selected entry on the list should be brought into view regardless, which is standard behaviour in any software that automatically selects an entry on any list (i.e. my request 1 above). What you've pointed out diminishes the need for my second proposal, but considering how easy it would be to implement the second proposal too, it wouldn't hurt to have the script name on the title bar of the window along with the scene name. Anyway, now I know where to look; thanks.
