### ISSUE TITLE
get_tree().quit() and window decoration quit buttons not working

### ISSUE THREAD

**Issue by mitchwagner** [godotengine/godot#29729]
**Godot version:**
3.1.1

**OS/device including version:**
Mac Mojave, MacBook Pro and Windows (custom PC)

**Issue description:**

- get_tree().quit() does not close the game (either when running from Godot or standalone executable)
- Window Decoration quit buttons (e.g., red circle on mac, X on windows) do not close:
    - Godot itself
    - A standalone executable
    - Scenes run from within Godot

Basically, the only way for me to stop Godot scenes run from within the editor is to use the square stop button. The only way for me to quit Godot itself is to kill the command line process that starts up alongside it.

When I start a brand-new project, I have none of these issues.

**Steps to reproduce:**
I have no clue how the project wound up like this. When I start a brand-new project, I have none of these issues. Somehow, the six files in the repository below are somehow corrupted such that they cause all of this behavior?

**Minimal reproduction project:**
https://github.com/mitchwagner/godot-broken-quit

Cloning and running the above project's scene exhibits the behavior for me.

**Comment by KoBeWi** [comment]
This is caused by physics FPS set to 0. I guess it shouldn't behave like that.

**Comment by KoBeWi** [comment]
Well, in 3.2 you can't legitimately set physics FPS to 0, so this is resolved.
