### ISSUE TITLE
Can't extend both built-in classes and custom scripts

### ISSUE THREAD

**Issue by rdmtt** [godotengine/godot#29726]
**Godot version:** 3.1

**Issue description:**
When I extend a KinematicBody2D with a script, its functions don't work:

How the file is extended:
![bug](https://user-images.githubusercontent.com/49587900/59376391-440b4480-8d50-11e9-81fc-359a63f3f7ac.PNG)

The error:
![bug2](https://user-images.githubusercontent.com/49587900/59376388-440b4480-8d50-11e9-8ca0-aaf97190e960.PNG)

It worked in 3.0. Not sure if it's supposed to be like this, if yes, then please tell me what to do.

[Extends_Problem.zip](https://github.com/godotengine/godot/files/3282803/Extends_Problem.zip)

**Comment by KoBeWi** [comment]
Any reproduction project?

**Comment by rdmtt** [comment]
Simple project:
[Extends_Problem.zip](https://github.com/godotengine/godot/files/3282801/Extends_Problem.zip)

**Comment by sparkart** [comment]
Your Characters.gd script extends Node, not KinematicBody2D or whatever other class has "move_and_slide"

**Comment by KoBeWi** [comment]
^
This. Just change your extents in Characters.gd.

The script will extend whatever you write with the `extends` keyword, not the node you attach it to.
