### ISSUE TITLE
label material _notification causes segfault on exit

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2972]
To reproduce:
Add a label to a scene.  Add a material to the label, and add a script to the material.  If you run right now, it's fine.  If you add:

func _notification(what):
    pass

to the script, it'll segfault when you exit the window.  I test with 
/path/to/godot.x11.tools.64 -path /path/to/project

**Comment by eska014** [comment]
Confirming on Windows

**Comment by bojidar-bg** [comment]
Does this happen with sprites (or other Node2D based nodes) too?

**Comment by reduz** [comment]
i can't reproduce though i'm on linux..

**Comment by vnen** [comment]
I can't reproduce this. Is it still valid?

**Comment by akien-mga** [comment]
Can't reproduce either on Linux x64, so I'll assume it's fixed.
