### ISSUE TITLE
Godot accessibility features with screen readers 

### ISSUE THREAD

**Issue by ahmedSamy31** [godotengine/godot#29736]
I am a blind programmer I tried  to use Godot game engin mono version64  with NVDA  screen reader but it doesn't support screen readers completely 
there is any way to use it for some  like me?
if the company can make it half exesable I mean readable by mouse hovering that's will be good move

**Comment by akien-mga** [comment]
See the related discussion in #14011.

It's sadly quite difficult to make Godot usable with screen readers, as it uses its own toolkit (the Godot Control nodes) for the editor, and thus does not benefit from accessibility features implemented in existing general purpose toolkits like Qt or GTK.

**Comment by ahmedSamy31** [comment]
There is no hope for that and not even simple?
You can do this in the future or look for an alternative solution eg the Unity game engine does not support screen readers but there are some possible native  menus of browsing
