### ISSUE TITLE
const declarations fail when constructing other consts with built-ins

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#29738]
**Godot version:**
3.1.1.stable.official

Something like:

```gdscript
const V: = 20
const C: = Color(V) # fail point

const G: = 900.0
const V2: = Vector2(0.0, G) # fail point
```

Where `# fail point` gives `Expected constant expression` error. This doesn't make sense as `Color(20)` doesn't fail so it's not related to the fact that we're using built-in types.

related: #391

**Comment by qarmin** [comment]
Duplicate #8006
