### ISSUE TITLE
Setting World and/or World2 to Viewport cause errors

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29747]
**Godot version:**
3.2.dev.custom_build. 15425b450

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I set world in viewport
```
set_world(World.new())
set_world_2d(World2D.new())
```
Then after a while, this error shows in debugger
```
Attempt to call function 'is_size_override_enabled' in base 'previusly freed instance' on a null instance
```
This is strange, because in remote scene Viewport still is shown, and after continuing execution of project, project works for a while until shows same error(functions names are different).

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit e09f44201df5158e3c09f361907e5c6536b99864
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/e09f44201df5158e3c09f361907e5c6536b99864.zip

**Comment by Anutrix** [comment]
I couldn't reproduce the bug in https://github.com/qarmin/The-worst-Godot-test-project/archive/e09f44201df5158e3c09f361907e5c6536b99864.zip (just Parse Error: Error parsing expression, misplaced: ')' in BASE_SCRIPT.gd). Running on Godot Engine v3.2.dev.custom_build.5e3ef9b89 .

**Comment by qarmin** [comment]
Can't reproduce with 3.2.2, maybe it was only linux related or maybe latest Variant changes fixed it.
