### ISSUE TITLE
Connect signal with a after function not suggest it

### ISSUE THREAD

**Issue by jjmontes** [godotengine/godot#29759]
**Godot version:**
3.1.0 stable and 3.1.1 stable

**OS/device including version:**
Ubuntu 18.04.2 LTS 

**Issue description:**
English (not native): 
I connect a signal from code with a after function and into the suggest list not show it the exist function. Must show it

NOTE: The code works, not work to suggest. Its a UI BUG

Español (nativo):
Conecto una señal desde código con una función declarada luego de dicha línea y no me sugiere la función que quiero conectar. Debería mostrarla.

NOTA: El código funciona, lo que no funciona es el autocomplete. Es algo de la UI

**Steps to reproduce:**
Here not work
![imagen](https://user-images.githubusercontent.com/576414/59450840-811f1780-8de0-11e9-9531-303183a86a56.png)

Here works
![imagen](https://user-images.githubusercontent.com/576414/59450914-ad3a9880-8de0-11e9-896a-7ce8f80c5001.png)

**Minimal reproduction project:**
Project. Player.gd line 24, col 68
[RunnerPrototype.zip](https://github.com/godotengine/godot/files/3287191/RunnerPrototype.zip)

**Comment by KoBeWi** [comment]
Might be related to #20393

**Comment by KoBeWi** [comment]
Still valid in 3.2.3 rc1

There's a similar issue #23264, but in this case it fails regardless if it's in `if` block/loop.

**Comment by KoBeWi** [comment]
Fixed in 4
