### ISSUE TITLE
Pixel Rendering Problem

### ISSUE THREAD

**Issue by samdaiya** [godotengine/godot#29761]
**Godot version:** 3.1.1

**OS/device including version:** Manjaro

**Issue description:** When I try to resize Window pixels gets messy as shown in Screenshots.

Desired Output:
![desired_output](https://user-images.githubusercontent.com/17422674/59453837-6a9fad00-8e2e-11e9-9505-e8e8b02fb7c5.png)

Output in 480x320 WIndow:
![480x320_window](https://user-images.githubusercontent.com/17422674/59453403-6c1ca580-8e2d-11e9-9767-07f84d9d7828.png)

Output After Maximizing Window:
![maximized_output](https://user-images.githubusercontent.com/17422674/59453407-6f179600-8e2d-11e9-9da4-c22ecf844c10.png)

**Steps to reproduce:** Run given project and try to resize Window or Maximize it and you will see the problem.

**Minimal reproduction project:**  [PixelProblem.zip](https://github.com/godotengine/godot/files/3287319/PixelProblem.zip)

**Comment by Calinou** [comment]
Pixel art can only look crisp if you resize it by an integer factor. See https://github.com/godotengine/godot/issues/6506.

**Comment by samdaiya** [comment]
* I found workaround for this problem.
* If I use 4 pixels border instead 1 pixel border Pixels looks good.

![IMG_20190615_081624](https://user-images.githubusercontent.com/17422674/59546190-03295080-8f47-11e9-9c49-0ad1faf39f20.jpg)

**Comment by Phoenix1747** [comment]
Glad you found a workaround, pretty much identical to https://github.com/godotengine/godot/issues/6506, though.
