### ISSUE TITLE
Color picker layer render wrong size.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29770]
**Godot version:**
3.1.1

**OS/device including version:**
macos 10.14.4

**Issue description:**
I can't select difference color on right of panel.

**Steps to reproduce:**
It always occur at VisualShader/Color clicked.
It also occur when sometimes select color in node properties.

**Minimal reproduction project:**
![image](https://user-images.githubusercontent.com/1890538/59487703-07eef580-8eb0-11e9-9a38-1d5ac521bf9e.png)

**Comment by groud** [comment]
Duplicate of #27312
