### ISSUE TITLE
Help font extremely small

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#29774]
**Godot version:**
3.1.1 release OK
3.2 df17cf0  OK
3.2 23a9ba6 (around the end of May) and all future builds have the issue

**OS/device including version:**
Win10/64
Nvidia 1060
1920x1080 display, no hidpi enabled

**Issue description:**
Only properties and methods display tiny. The links still work.

![current](https://user-images.githubusercontent.com/632766/59498361-3f6d9a00-8ed0-11e9-9c24-6d8c6c494ea2.png)
![more](https://user-images.githubusercontent.com/632766/59498536-95424200-8ed0-11e9-9f03-162fd1be01fb.png)

**Steps to reproduce:**
Open a recent build of godot and look for anything in help.

I tried turning on and off hdpi, messing with editor settings font sizes and scaling. All of that changes the editor fonts, but doesn't touch the help.

Maybe related to #8730.

**Comment by akien-mga** [comment]
Might be due to #28107. What value do you have for the `"text_editor/help/help_source_font_size"` property?

**Comment by tinmanjuggernaut** [comment]
Help Title Font size 23
Help Font size 15
Help source font size 14

I increased the latter two and that affected the font. I then reverted the change and they look normal.

Next, I deleted %appdata%\godot\editor_settings-3.tres
Opening Godot, I found the super tiny font size returned. 
Also now there is no setting for help_source_font_size neither in the generated .tres file, nor in the editor. 

Adding the line back into the .tres file with size 14 has fixed it for me, but it appears there is a bug in the default generated settings.

**Comment by tinmanjuggernaut** [comment]
Thanks for your help getting the docs usable again for me.

**Comment by andit001** [comment]
Hello,

I've got the same problem. However, changing the value in the editor didn't work. It even isn't in the options where the other font size settings for help are. I could find it by searching for it in the search bar. However, changing it this way didn't help.

In %appdata%\godot\editor_settings-3.tres the option was missing completely (even after trying to change it in the editor settings). After adding the option in the file by hand it works.

I'm on bd937ea39 and Windows 10.

**Comment by akien-mga** [comment]
I think it might be because the setting has not been assigned its default value yet in `editor/editor_fonts.cpp` for some reason (if this code runs earlier than the `editor_settings.cpp` code).

**Comment by akien-mga** [comment]
Ah no, it's a typo...

**Comment by akien-mga** [comment]
Could you confirm that #29779 fixes it?

**Comment by andit001** [comment]
> Could you confirm that #29779 fixes it?

It fixed it on my end.

**Comment by tinmanjuggernaut** [comment]
Looks good here. Thanks for the help.
