### ISSUE TITLE
Normals not scaled when instance has non uniform scale

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#2978]
hello,

ive a problem when creating a meshInstance from a mesh (using visual server directly)
if i provide a transform that has a scale not (x/x/x) then it seems the normals arent updated/scaled.
is this on purpose? or just not supported yet? or do i make a missasumption?

maybe its because of my splatmapshader, im using a shader only with fragment code,
and there i only set DIFFUSE, and uniform in some textures and params.

i dont have a project i could add here (yet), because im developing a module in c++

as an example:
when i have a terrain in size 500/20/500, and a heightmap 100/100
then i create a terrain mesh 0..100/0..1/0..100 (where 0..1 is the height from heightmap)
when creating the the meshinstance for it, ive to scale it from 100/1/100 to 500/20/500

but when doin this, the light is the same all over the terrain, 
because the normals are all very steep 
thats because of height is only 0..1, 
so deltaheights (y) for a triangle are very small, compared to tris x/z => steep normal)
when i fake the normals to reflect the scale all is ok... 
but what if the user changes the scale or size of the terrain...then i have to update the mesh...i dont think it should work this way...
i also could generate the mesh in the "correct" size or "aspect ratio" i may need to do it as a workaround, but still not very cool...

greets and tnx in advance

**Comment by ZuBsPaCe** [comment]
If I'm not mistaken, generally, you need to recalculate normals yourself as soon as there is non-uniform scaling.

The idea is, that transformations are render-time modifiers. The transformation matrix changes the final output *without* adjusting the underlying mesh. The other option would be, that the engine would recalculate the normals after each change of the transformation matrix. And that would be incredibly inefficient.

So generating the terrain mesh and its normals in the right size without the need for scaling would be the correct way. Maybe you could also try to calcuate the correct normal in the vertex shader like this: http://stackoverflow.com/q/29008847/998987

**Comment by CharlesWoodhill** [comment]
i hope ur wrong :)
i know that the render process dont changes the mesh ;)
but i still think the shader should get the correct normal...like in other engines.
imagine a game, using diffrent scales on their models, then uve to write your own shader or import models twice if needed in 2 diffrent scales.
otherwise lightning & more is not correct.

**Comment by CharlesWoodhill** [comment]
ok ive tracked it down abit:
if i use following line in the frag shader code
" vec3 someUnusedVar = NORMAL; "
then the normal gets calculated correctly

**Comment by CharlesWoodhill** [comment]
but maybe its intended to do this on your own.
then i think it is a feature request :)

**Comment by bojidar-bg** [comment]
Bump, is this worth considering for the new 3.0 renderer?

**Comment by Chaosus** [comment]
I think this has been fixed by #19786 by implemented ensure_correct_normal flag
