### ISSUE TITLE
[SOLVED] partial mesh update?

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#2979]
ahoi,

ive a question about meshmanipulation:

if u edit a mesh, for example a changeable terrain,
where u can change the height for the building site,
only 1 -4 vertices change, afaik at the moment uve to remove and reAdd the whole surface to achieve this.

will it ever be possible to "change" partial surface data?
i know unity doesnt support it, so i think there may be a reason, on the other hand there are things like:
glBufferSubData and glMapBufferRange (seems to be slower)

or should a "changeable mesh" be composed of multiple smaller meshChunks (surfaces) to achieve
less vertex data streaming, if so, whats the performance hit, doing so?

greets cw

**Comment by CharlesWoodhill** [comment]
for others with that question:

short:
not doable :blush:

longer:
seems to produce, problems with meshs AABB, and meshCompression, and maybe more... :blush:

**Comment by kubecz3k** [comment]
Well since it's 'solved' I will move it to archive.

**Comment by reduz** [comment]
it should be possible to update indices in real time, which is useful for
some techniques like clipmapping

**Comment by kubecz3k** [comment]
@reduz therefore should I reopen the issue? Should it be threaded as feature request for runtime indices update?
