### ISSUE TITLE
Change the color of a panel with add_color_override?

### ISSUE THREAD

**Issue by Drillur** [godotengine/godot#29792]
Godot version: 3.1
windows 10

var color = some color

Through searching, I've been able to get my labels to change to a color I want by using $Label.add_color_override("font_color", color), but for panels, "font_color" obviously doesn't work.

I've tried "modulate", "visibility", "bg_color", "bgcolor", and just "color". I cannot for the heck of me find anywhere online where a list of strings like this would be listed. Why are they hidden :'(

Does anyone know how to use this exact function to change the color of the panel? I don't want to mess with styles because I need to change the color of it often.

**Comment by groud** [comment]
Sorry, but this is not the place to ask general questions about how to use the engine, but to ask for new features and report bugs. Please use the [other community channels](https://godotengine.org/community) for this purpose.

> I don't want to mess with styles because I need to change the color of it often.

I think there is no real problem in doing so.
