### ISSUE TITLE
Emscripten warning: cannot represent a NaN literal '0xebe1140' with custom bit pattern in NaN-canonicalizing JS engines without erasing bits (in RasterizerStorageGLES3::multimesh_allocate)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#29796]
**Godot version:**
3.2 master (0a3c21d99)

**OS/device including version:**
Linux, building for HTML5 with Emscripten 1.38.30.

**Issue description:**
When compiling `scons p=javascript`, the following warnings are raised when linking:
```
emcc: warning: cannot represent a NaN literal '0xebe1140' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   store float 0xFFFFFFFFE0000000, float* %94, align 4, !tbaa !30 in _ZN22RasterizerStorageGLES318multimesh_allocateE3RIDiN12VisualServer24MultimeshTransformFormatENS1_20MultimeshColorFormatENS1_25MultimeshCustomDataFormatE() 
emcc: warning: cannot represent a NaN literal '0xebe1140' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   store float 0xFFFFFFFFE0000000, float* %93, align 4, !tbaa !31 in _ZN22RasterizerStorageGLES218multimesh_allocateE3RIDiN12VisualServer24MultimeshTransformFormatENS1_20MultimeshColorFormatENS1_25MultimeshCustomDataFormatE()
```

I guess this is the part that Emscripten doesn't like? Note that the same code is in GLES2 and GLES3:
https://github.com/godotengine/godot/blob/0a3c21d999559617cc9cdfe261d631e6d1267374/drivers/gles3/rasterizer_storage_gles3.cpp#L4369-L4379

**Steps to reproduce:**
`scons p=javascript dev=yes`

**Comment by akien-mga** [comment]
I'm not sure why `0xFFFFFFFF` would end up as a `0x0ebe1140` NaN literal, the latter is way smaller than the max value of `uint32_t`. Or is it the union `float` that overflows? A single float should be able to hold that value just fine, but does JS default to `half` or something?

**Comment by akien-mga** [comment]
The literal value is just some random stuff, on another build I got:
```
emcc: warning: cannot represent a NaN literal '0xd962da0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   store float 0xFFFFFFFFE0000000, float* %104, align 4, !tbaa !30 in _ZN22RasterizerStorageGLES318multimesh_allocateE3RIDiN12VisualServer24MultimeshTransformFormatENS1_20MultimeshColorFormatENS1_25MultimeshCustomDataFormatE() 
emcc: warning: cannot represent a NaN literal '0xd962da0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   store float 0xFFFFFFFFE0000000, float* %270, align 4, !tbaa !33 in _ZN22RasterizerStorageGLES218multimesh_allocateE3RIDiN12VisualServer24MultimeshTransformFormatENS1_20MultimeshColorFormatENS1_25MultimeshCustomDataFormatE()
```

**Comment by Faless** [comment]
If understand the correctly [WASM](https://www.w3.org/TR/wasm-core-1/#floating-point) specifies a canonical `NaN` format (and `0xFFFFFFFF` is a non-canonical NaN).
Some JS engines (e.g. Firefox, Safari) canonicalize NaNs automatically, so `0xFFFFFFFF` cannot be represented there.

**Comment by Faless** [comment]
@akien-mga I'm wondering, do we need that union at all? Can't we just assign the literal `0xFFFFFFFF` to `dataptr[i + color_from + 0]`? It seems to work without even needing a cast here.

**Comment by Faless** [comment]
>  It seems to work without even needing a cast here.

No, of course it doen't give the expected result without casting, it seems that `0xFFFFFFFF` simply cannot be represented in javascript. If I cast it to `(float *)` and back it still gives the warning.

**Comment by bruvzg** [comment]
Not sure how WASM is handling this union, but AFAIK JS engines (at least [SpiderMonkey](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Internals#JavaScript_values)) use double precision floats as the only fundamental data type and special NaN patterns to store 32-bit ints and 48-bit pointers and type tags inside doubles (aka. "NaN-Boxing").

**Comment by Calinou** [comment]
I can still reproduce this on commit https://github.com/godotengine/godot/commit/24e1039eb6fe32115e8d1a62a84965e9be19a2ed.

**Comment by Faless** [comment]
This also seems fixed with latest upstream emscripten. Can anyone still reproduce?

**Comment by Faless** [comment]
Closing, as this issue seems fixed in the upstream toolchain. (I haven't seen this warning in recent emscripten versions).
