### ISSUE TITLE
Could Capsule CollisionShape Height be renamed to match Capsule MeshInstance?

### ISSUE THREAD

**Issue by fakedeltatime** [godotengine/godot#29807]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Linux

**Description:**
The height of Capsule CollisionShape is called "Height", while the height of Capsule MeshInstance is called "Mid Height". I believe both of these should be called "Mid Height", as the unit presented is not the overall height of the capsule, which caused me a lot of problems with the scale of my capsule ColllisionShape. Mid Height is actually representative of the property that is affected. A unit called Height that affects the actual height by manipulating the scale would also be nice, but I think Mid Height would suffice as an easier fix.

**Comment by KoBeWi** [comment]
Probably a candidate for #16863

**Comment by Calinou** [comment]
CapsuleMesh's height property is now called just `height`, closing.

https://github.com/godotengine/godot/blob/52b7d5fa347fb88aa016e1e30414abd01e800381/scene/resources/primitive_meshes.cpp#L422
