### ISSUE TITLE
[SOLVED] Left Hand Coord System

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#2980]
Question 1: will godot ever change to LeftHand?
**Question 2: will the below codechanges create problems** (more important question) :)

i wondered why u dont expose the Left Hand coord system to the user,
knowing openGl is using right hand, but this only because the proj matrix does so.

i hope i dont stamp me to a noob, non geek, tipex user, ...
but isnt LH not much more intuitive? (to normal humans, not 3d geeks) ;)

since i actually porting/rewriting code from my old directX and unity projects, i dont want to convert,
so i tried abit with godot, and changed
camera_matrix.cpp
```c
void CameraMatrix::set_perspective(float p_fovy_degrees, float p_aspect, float p_z_near, float p_z_far,bool p_flip_fov) {
...
 	//matrix[2][2] = -(p_z_far + p_z_near) / deltaZ;
	//matrix[2][3] = -1;
	matrix[2][2] = (p_z_far + p_z_near) / deltaZ;
	matrix[2][3] = 1;
...
```
to make all LH. ( i know this hack only working for perspective )
but this need some thinking about it, do i run into future problems?
i know TriangleCulling changes ( to the one i actually use in dx and unity)
mesh culling and lightning still seem to work (as expected)
is there anything else ive to think about, when doing this?
for example math (LookAt, vector.cross, rotations, quaternion, ....) 
or the physics server (not worked with it yet) or anything else?

greets & thanks in advance 
and remember going forward with RH is going back! :)  or left instead of right... :P
what if i need my mousehand and have to imagine some 3d sh...err things :)

**Comment by akien-mga** [comment]
I don't have much experience with low level stuff, but right hand is the common convention in math. Why would left hand be more intuitive to humans? As soon as you reach middle school, you start learning about the Cartesian system (first 2D, then 3D) which follows the right hand rule: https://en.wikipedia.org/wiki/Cartesian_coordinate_system

**Comment by CharlesWoodhill** [comment]
why a rotation matrix in the direction of my eyes is not identity?

**Comment by reduz** [comment]
no, i don't think it will ever support left hand. Too much code expects
right hand.

**Comment by manokara** [comment]
This is just a matter of personal preference. I mean, [even the lead dev from DirectX chose LH arbitrarily](http://www.alexstjohn.com/WP/2013/07/22/the-evolution-of-direct3d/) (somewhere around 10th paragraph). In every discussion on the web you can find, there's no ultimate technical reason to use one or another.

LH also makes more sense to me, but I wouldn't mind using RH at all. Godot has much more important aspects to deal with than handedness. Like reduz said, it would require lots of rewrite.

**Comment by CharlesWoodhill** [comment]
so i will run into prolems using this hack...

**Comment by ali-rahbar-17** [comment]
why there aren't any options to customize it?

**Comment by Zireael07** [comment]
@alirahhbar Because customizing it means rewriting half of the engine for little gain
