### ISSUE TITLE
Non-updating handles of SegmentShape2D instances

### ISSUE THREAD

**Issue by tree786** [godotengine/godot#29819]
**Godot version:**
v3.1.1 (from godotengine.org)

**Issue description:**
When multiple instances of a SegmentShape2D is spawned from another scene (using a for loop), the handle `shape` values `a` and `b` do not get updated, even when they are explicitly assigned values. They only get updated to reflect the value assigned at the end of the for loop. E.g. if I was to run this code:

    for i in 2:
        var segment_shape2d=segment_shape2d_preload.instance() # instance
        add_child(segment_shape2d) # add it to the current scene
        segment_shape2d.get_child(0).shape.a=Vector2(i,0) # set handle 'a' value
        segment_shape2d.get_child(0).shape.b=Vector2(i,i) # set handle 'b' value

The code should instance (and add to the current scene) two `SegmentShape2D`'s, with the first having a `shape.a` value of (0,0) and the second having a  a `shape.a` value of (1,0). But this doesn't happen, and instead ALL `shape.a` values are incorrectly set to (1,0), including the first instance of `SegmentShape2D`. Hopefully I explained this somewhat clearly.

**Steps to reproduce:**
1. Instance and add a `SegmentShape2D` to the current scene using a for loop (make sure its parent is a `StaticBody2D`)

2. Set the handle values of `shape.a` and `shape.b` to vary based on the current position in the for loop (i.e. use the iterator value to set them)

3. Print  `shape.a` and  `shape.b` and check the values

**Minimal reproduction project:**
Here it is...(make sure you run 'Node2D.tscn')
[segmentshape2d_issue.zip](https://github.com/godotengine/godot/files/3293751/segmentshape2d_issue.zip)

**Comment by KoBeWi** [comment]
This is probably caused by Shape being a resource, so it's shared between colliders (even though you instance them from scene). If you enable `local_to_scene` for the shape, it should fix it.
![image](https://user-images.githubusercontent.com/2223172/59564053-4fa58680-9042-11e9-9692-ae42ba4be5fa.png)

**Comment by tree786** [comment]
Thank you, it works now! I will be closing this issue then.
