### ISSUE TITLE
Editor help no longer displays correctly

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#29810]
**Godot version:** Git https://github.com/godotengine/godot/commit/89ce9a6f4694711e383c3d3e42141d176a12529e

**OS/device including version:** Fedora 30, Clang 8.0.0

**Issue description:** The editor help no longer displays correctly. This is likely a regression from https://github.com/godotengine/godot/pull/29785. Maybe the editor help generation needs to be modified to take the above PR into account?

## 3.1.1 stable (good)

![doc_3 1 1_1_good](https://user-images.githubusercontent.com/180032/59553910-4feb4680-8f9c-11e9-9891-755097b7b091.png)
![doc_3 1 1_2_good](https://user-images.githubusercontent.com/180032/59553911-4feb4680-8f9c-11e9-8bf8-b8471ec6dbe0.png)

## Master (bad)

![doc_master_1_bad](https://user-images.githubusercontent.com/180032/59553913-52e63700-8f9c-11e9-9574-05cb2cea2168.png)
![doc_master_2_bad](https://user-images.githubusercontent.com/180032/59553914-55e12780-8f9c-11e9-88b2-4aab5eb75977.png)

**Steps to reproduce:** Open any class in the editor help.

**Comment by akien-mga** [comment]
I confirm that reverting #29785 fixes the regression, CC @eligt.

**Comment by eligt** [comment]
I'll have a look at this shorty.
