### ISSUE TITLE
LineEdit in mode: editable = false, - translucent text

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#29814]
**Godot version: 3.1.1**

I need not editable LineEdit:

`MyLineEdit.editable = false`

And I see that the text in LineEdit is translucent in this mode. This is not what was expected. But most importantly, I didn’t find a parameter to change it.

**Comment by Calinou** [comment]
This is currently hardcoded here:

https://github.com/godotengine/godot/blob/ce8e5413390b48542b98ffafe5fc8b0b8032efa2/scene/gui/line_edit.cpp#L678-L684

It probably should be turned into a custom color, like for other text colors.
