### ISSUE TITLE
GDScript debugger incorrectly warns about unused exported variables.

### ISSUE THREAD

**Issue by hbina** [godotengine/godot#29829]
**Godot version:**

master [ 9d33425](https://github.com/godotengine/godot/commit/9c7cce3c9b8062817e976676ff0f4772971895cb)

**OS/device including version:**

Ubuntu 18.04 Linux 5.1

**Issue description:**

GDScript incorrectly complains that an exported variable is unused despite it being used by another file.

**Steps to reproduce:**
1. Declare any exported variable.
2. Use it in another file.
3. GDScript debugger will complain.

**Minimal reproduction project:**

Any project really, I was using the Dodge the Creeps project from Godot's demo projects.

**Comment by TheDuriel** [comment]
Not _really_ a bug. Variable usage is only tracked within the Class Scope. It can't know you are using it elsewhere. That would require a _lot_ of effort.

**Comment by BraindeadBZH** [comment]
Would it not be sufficient to just ignore exported variables when checking for unused?
I mean I can make the warning disappear by just adding a getter, but it would be redundant as an exported variable is already public in a sense.

**Comment by TheDuriel** [comment]
Just add the comments.

Click the warning triangle in the script editor.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
