### ISSUE TITLE
Add h and v_flip to TextureRect

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#29837]
No idea why https://github.com/godotengine/godot/issues/21729 was closed. 

Being able to correctly flip a TextureRect without changing its scale is a good feature in my eyes.

Right now the only way to do this is via shader, or by scaling the node. The latter pretty much defeats the anchors, margins, and containers work flow...

**Comment by KoBeWi** [comment]
The issue was closed by PR, which was merged for 3.2. You can use the feature with nightly build or compiled master branch. Or just wait for 3.2 release.
