### ISSUE TITLE
Error at the openning of godot

### ISSUE THREAD

**Issue by AdrienDML** [godotengine/godot#29836]
I have the following error showing in the terminal when i open my Godot 3.1 with C#:

OpenGL ES 3.0 Renderer: GeForce GTX 1050/PCIe/SSE2
ERROR: initialize: Condition ' !_load_editor_tools_assembly() ' is true.
   At: modules/mono/mono_gd/gd_mono.cpp:340.

It doesn't seems to affect the software general operation. I can open projects and build them without any problem.

**Comment by KoBeWi** [comment]
@AdrienDML Can you still reproduce it in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1)?

**Comment by akien-mga** [comment]
No answer and no steps to reproduce the issue, so closing.
