### ISSUE TITLE
Strange scroll behaviour when opening a script

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#29858]
**Godot version:**
3.2-dev 0ac3687d6

**OS/device including version:**
Windows 10 Build 18362

**Issue description:**
It seems that, since 3.1.0, some new script editor scrolling behaviour when opening a script was added. It's pretty wonky. I haven't found any issues about this so sorry if this is a duplicate.

In 3.1.0, I think it would just put the cursor at line 0 and leave the scroll offset at 0. In master, it puts the cursor at the end of a file. I've seen the cursor start on different lines before, which I think was the intended behaviour (remembering the last cursor position in a script) but I cannot for the life of me manage to replicate it.

It tries to scroll the window so that the highlighted line is near the top of the script window, which is weird since I'd expect it to be around the center. Even then, when the cursor isn't placed at the last line, it tends to scroll *past* the highlighted line.

With the "Scroll Past End Of File" editor setting enabled, most of the script is scrolled out of view, since it's trying to put the highlighted line around the top of the window. This is what opening a new script usually looks like for me:

![image](https://user-images.githubusercontent.com/27100585/59641888-5947ff00-91a6-11e9-8a3f-47a546db9a42.png)

I'd personally expect it to 1) scroll the window so that the highlighted line is in the middle of the window rather than the top, and 2) make sure it doesn't scroll past the end of the file, regardless of whether the setting is enabled or not.

**Steps to reproduce:**
1. Enable "Scroll Past End Of File" editor setting (under Text Editor > Cursor)
2. Open a script (the longer the better)
3. Position the cursor somewhere within the script
4. Save the script, then close it
5. Re-open the script and take note of the highlighted line and scroll offset

**Comment by KoBeWi** [comment]
I also had the script editor open at awkward position, but after quick testing now, it doesn't seem to happen.

**Comment by homer666** [comment]
Still happens as of 3.2-dev 72dfa67dd, but I can't reproduce it consistently (and never really could).

**Comment by Calinou** [comment]
Can anyone else still reproduce this bug in [Godot 3.3.3](https://godotengine.org/article/maintenance-release-godot-3-3-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No reply, and this was a fairly old issue and the OP deleted their account, so closing. If you can still reproduce this issue, please open a new issue following the current template.
