### ISSUE TITLE
Isometric tiles drawn over collision shapes

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#2985]
You can quickly check this by enabling "Visible Collision Shapes" in the isometric 2d demo:

![example](https://camo.githubusercontent.com/90a29b8d9f4e0403280307871f69a6bfd56cabd4/687474703a2f2f692e696d6775722e636f6d2f393659487a30542e706e67)

Collision shapes should be visible over the tiles.

**Comment by reduz** [comment]
ah must change the layer for this..  thanks for reporting

On Fri, Dec 4, 2015 at 8:21 AM, Ignacio Etcheverry <notifications@github.com
