### ISSUE TITLE
Resizing Control in CanvasLayer will change control's anchor, not margin.

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#29864]
**Godot version:**

Master: 0ac3687

**OS/device including version:**
Windows 7

**Issue description:**

![圖片](https://user-images.githubusercontent.com/2070604/59657007-f3716c80-91d1-11e9-92ac-2b60a1fa3c75.png)

Resizing Control in CanvasLayer will change control's anchor, not margin.

**Steps to reproduce:**
* create a new scene
* use CanvasLayer as root
* create a Control under CanvasLayer
* resize Control

**Comment by groud** [comment]
You have the anchor mode activated (top right of the toolbar), that's an expected behaviour.

The problem is that the mode activate itself for no reason, but I have a pending PR to fix that.
