### ISSUE TITLE
Inconsistent slash behavior in New Project dialog on Windows

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#29875]
**Godot version:** 3.1.1

**OS/device including version:** Windows 10

**Issue description:** On Windows, in the project manager, when creating a new project, it auto-fills the project path with backslashes (traditional Windows style), but any of the buttons on the top-right will change this to forward slashes (cross-platform style). 

I think it's fine to use forward slashes everywhere. Windows has supported this for quite awhile. EDIT: Supported since MS-DOS.

I believe [here](https://github.com/godotengine/godot/blob/master/editor/project_manager.cpp#L722) and [here](https://github.com/godotengine/godot/blob/master/editor/editor_settings.cpp#L386) is where the default value comes from.

**Steps to reproduce:**

Click "New Project" in the project manager. Notice the path starts filled with backslashes, and clicking Browse and browsing for a path, or clicking "Create folder", will change this to forward slashes.

**Comment by KoBeWi** [comment]
Still valid in 3c6f5226f

**Comment by aaronfranke** [comment]
Fixed by #50136.
