### ISSUE TITLE
Can GDScript's syntax be changed to be more C++ like?

### ISSUE THREAD

**Issue by Bluecoreg** [godotengine/godot#29887]
For those who want to be able to code inside of Godot, out of the box, no extra set up required; however, prefer to code with curly braces, rather than tabs and colons.

I'd like to help work on an alternative GDScript. Everything is the same, except just switching out all of the Python-esque syntax. This would give people the option of choosing which one they wanted to use.

If anyone could point me in the right direction on where in the codebase a project like this should start, I would appreciate it.

**Comment by Calinou** [comment]
I don't think having two syntaxes is worth the trouble. You lose a lot on standardization (people will be writing code in two syntaxes instead of just one), for very little benefit.

Besides, when evaluating a programming language, its features and community come first. Syntax is usually a very secondary point when you're an established programmer :slightly_smiling_face:

**Comment by Bluecoreg** [comment]
It shouldn't be confusing to newcomers, just like the addition of C# support shouldn't be confusing to newcomers.

Both versions should be independent of each other. It would aid newcomers to Godot who are used to C++, or other programs that share C's syntax like Game Maker Studio.

**Comment by groud** [comment]
This is not going to happen. Maintaining two syntaxes of a language is a pain, and will, as Calinou has pointed out, be very confusing for all people learning the language. 

It is a lot easier to learn a python-like language even when you come from a C++ or C background than having to learn a language with several syntax. Examples over the net would need to be translated in your favorite syntax, which is more difficult than just get use to the new syntax.
