### ISSUE TITLE
2D Normal map and 2d light 

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#29880]
**Godot version:**
Godot Engine v3.2.dev.calinou.0ac3687d6
0ac3687d6

So when i have a normal map on a sprite, and the light 2d is set at hight 1, i assume that whuld lit up only one side of the sphere, but this behaves funky..? when i set the height of the 2d light to 100 or so that weird effect is gone and the light effect is much worse and has a black outline at the edge of the sphere.  is this a bug or is it supposed to be like this?

![e26588b9073816fa6aea1f399ec19c79](https://user-images.githubusercontent.com/13393087/59723003-8091e100-9225-11e9-8e31-6827557ecc45.gif)
![1513176e2bc33f9834c7ac6b25c40c7e](https://user-images.githubusercontent.com/13393087/59723012-84256800-9225-11e9-887c-9f5c8f3a70e5.gif)

[bugnm.zip](https://github.com/godotengine/godot/files/3303589/bugnm.zip)

**Comment by TheDuriel** [comment]
You typically want to use heights of 64 or more. Depending on the depth of your normal map. There was a PR some time ago that fixes the height property to allow values from -1024 to +1024.

**Comment by clayjohn** [comment]
Adding to what @TheDuriel has already said above. The weird outlines in the second gif appear to be from your normal map rather than an issue with Godot. Outside the planet, the normal map defaults to a flat plane. So at the edges of your planet the light is interacting with a flat plane and not a sphere so you are getting a weird dark-then-bright outline.

**Comment by Norrox** [comment]
If i set the height of the light to 64, I still get the same strange thing as the first gif shows, isn't it supposed to light the side that facing the light source, now some "sides" of the sphere are completely black and if I put the light directly on top of the sphere the light appear as an egg shape not perfect circular 🤔

**Comment by Norrox** [comment]
I don't think this bug exist anymore or if it even existed when I did this, I think I just didn't invert the y on the normal map.

**Comment by clayjohn** [comment]
Thanks for the update. :)
