### ISSUE TITLE
Vertex shaders color broken ? 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [godotengine/godot#29896]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
If you assign COLOR  inside Vertex shader it is just ignored.

**Steps to reproduce:**
1) create emty scene
2) Create direct light , camera 
3) create meshinstance assign New spheremesh
4) New shader material

```
shader_type spatial;

void vertex()
{
	vec4 iamred = vec4(1.0,0.0,0.0,1.0);
	COLOR = iamred;
}

void fragment()
{
	// do nothing
}
```

5) Press Play. You see sphere which quite far from red. Even more it colored with default colors which it get from nowhere. 

**Minimal reproduction project:**

**Comment by sdfgeoff** [comment]
I think the default fragment function doesn't use  vertex colors.
In the fragment() function you can probably do:
```
void fragment(){
    ALBEDO = COLOR.rgb;
}
```

**Comment by jpVm5jYYRE1VIKL** [comment]
Yes but in this case i forced to use fragment shader. And COLOR only used just as a transport for ALBEDO from vertex shader.

**Comment by clayjohn** [comment]
This is not a bug. As explained above. You have to assign ALBEDO in the fragment shader. COLOR and ALBEDO do different things. COLOR is used only for passing vertex colors to the fragment shader.

For more information on shaders, please see the docs.  http://docs.godotengine.org/en/latest/tutorials/shading/index.html
