### ISSUE TITLE
obj.free() cannot free the dictionary member of a object (not work as that described in manual)

### ISSUE THREAD

**Issue by JustusPan** [godotengine/godot#29891]
**Godot version:**

Godot v3.1 stable

**OS/device including version:**

Dell xps13
Win64
iris640

**Issue description:**

[Here](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/resources.html) described a example for 'pass by reference' behavior of Dictionary, while Godot v3.1 does not work as this way.
```  
extends Node

class MyObject:
    extends Object
    var dict = {}

func _ready():
    var obj1 = MyObject.new()
    var obj2 = MyObject.new()
    obj1.dict.greeting = "hello"
    obj2.dict = obj1.dict             # 'obj2.dict' now references 'obj1's Dictionary.
    obj1.free()                       # 'obj1' is freed and the Dictionary too!
    print(obj2.dict.greeting)         # Error! 'greeting' index accessed on null instance!

    # To avoid this, we must manually duplicate the Dictionary.
    obj1 = MyObject.new()
    obj1.dict.greeting = "hello"
    obj2.dict = obj1.dict.duplicate() # Now we are passing a copy, not a reference.
    obj1.free()                       # obj2's Dictionary still exists.
    print(obj2.dict.greeting)         # Prints 'hello'.
```  

In the first half part of this example, `obj2.dict.greeting` still contains valid value "hello" and has been printed out.

Could you please clarify the behavior of dictionary copy in this condition? Or Should the manual be refined?

**Steps to reproduce:**
Copy the code above to a new script attached to a root node of a new scene. Then press f6.

**Minimal reproduction project:**

unzipped. open it by Godot v3.1. Press F5
[dictionary_issue.zip](https://github.com/godotengine/godot/files/3304919/dictionary_issue.zip)

**Comment by KoBeWi** [comment]
This should be actually on godot-docs repo, but it's fixed anyways in 3.2.
