### ISSUE TITLE
Rim not visible on unshaded materials

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#29898]
**Godot version:**
3.1.1.

**OS/device including version:**
Ubuntu 18.04 LTS
Intel HD Kaby Lake

**Issue description:**
![Screenshot 2019-06-19 12:31:56](https://user-images.githubusercontent.com/4525388/59759427-545f7a00-9290-11e9-9c54-070dec0f5451.png)

This scene has a light, yet I can't see the rim effect (on the yellow round mesh) at all. It's not a matter of view angle/mesh, as I consistently cannot see the rim. Note that the material preview at the top of inspector does show the rim, as does the running game, so we can exclude an issue with my GFX card, too.

**Steps to reproduce:**
Tick rim on spatial material, wonder why the mesh doesn't seem to change at all. Move some sliders, still no change.

**Minimal reproduction project:**

**Comment by slapin** [comment]
yeah, same here

**Comment by clayjohn** [comment]
Can you upload an MRP? I can't reproduce on my system. Rim appears fine in editor for me.

**Comment by slapin** [comment]
I use nvidia GTX660 on Linux.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Is rim lighting even supposed to work on unshaded materials? (The material appears to be unshaded on the screenshot.)

**Comment by Zireael07** [comment]
Not in front of the computer, but iirc yes it's unshaded. In that case, something for the docs? Mobile so can't tag 👎

**Comment by akien-mga** [comment]
Not sure where that should be documented? I guess it's not just rim shading, all kind of shading will by definition not be applied when unshaded...

**Comment by Zireael07** [comment]
It's not obvious to users that rim is/implies shading... I honestly thought it just tints the texture...
