### ISSUE TITLE
Add predelete signal to Object

### ISSUE THREAD

**Issue by josh18** [godotengine/godot#29890]
Using the Mono version I have an extension method that needs to perform some cleanup steps when an Object is freed. However there doesn't seem to be any way to know when an Object has been freed from outside of the Object.

If we think this is useful I believe I could follow this to create a PR: https://github.com/godotengine/godot/pull/15911

Note: I tried using a Reference for this but as far as I can tell References in the Mono version aren't freed by Godot but instead are disposed by the garbage collector? Which means the predelete notification on the Reference isn't sent.

**Comment by akien-mga** [comment]
There is `NOTIFICATION_PREDELETE` in Object which you can receive in the `_notification` callback: http://docs.godotengine.org/en/latest/classes/class_object.html#constants (might be `_Notification` in C# I guess).

So you could listen to this notification, and emit a signal to notify your cleanup scene of the Object's incoming deletion.

**Comment by josh18** [comment]
Yeah it just means I would have to add that to every Node that uses the extension method. Not too difficult but it might be useful having a signal similar to the `ready` signal

**Comment by Zylann** [comment]
I think a virtual method should just be enough, feels strange to be a signal to me, because this notificationis essentially a destructor.

**Comment by josh18** [comment]
> There is `NOTIFICATION_PREDELETE` in Object which you can receive in the `_notification` callback: http://docs.godotengine.org/en/latest/classes/class_object.html#constants (might be `_Notification` in C# I guess).
> 
> So you could listen to this notification, and emit a signal to notify your cleanup scene of the Object's incoming deletion.

Hmm I tried this but it doesn't actually look like it works. I think the user signals must be cleaned up by the time it reaches this point?

**Comment by mrcdk** [comment]
A predelete signal isn't possible because by the time you get to receive the signal the object has been already deleted. If you want to still use a signal you'll need to use another object as an intermediary or something.
