### ISSUE TITLE
Collision body_enter signal and Collisions in general

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#299]
Already talked in irc about this topic.
Rigidbody that is set to "rigid" is the only type which can perform a body_enter signal.
When set to "static" or "kinematic" no body_enter signal is triggered which is unfortunate.

Here is an example project which demonstrates the behavior.

Also I would like to suggest a new type for collision shapes. It would be nice if we could set them to ghost. This will only trigger a collision signal but lets the objects intersect. I know collision shapes have a Trigger boolean. This lets objects intersect but does not trigger a body_enter signal.
In general it would be nice if area2d nodes can detect other area2d nodes. This is not possible either. 

https://www.dropbox.com/s/v92amwfy0ohw0bx/collisions.zip

**Comment by kubecz3k** [comment]
I'm not sure but it looks to me like it's solved by now.. @ndee85 can you confirm?

**Comment by ndee85** [comment]
Yes.. this is solved. Closing this issue.
