### ISSUE TITLE
Godot giving errors that methods from the base node don't exist.

### ISSUE THREAD

**Issue by lincolnpepper** [godotengine/godot#29908]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 build 17763.557

**Issue description:**
i'm getting errors for methods from the base node not existing, such as is_in_group() and queue_free(). I'm not sure why or steps to reproduce this. I got an error one time that i tried to run the game after running the game using these methods several times in the same session. Resetting Godot doesn't help. Not sure yet if reinstalling Godot helps, but i'm trying it later. Problem only occurs on the project i got it on. Since i don't know when or why it happens, i can't reproduce it in a minimal reproduction project, so here's the project i'm getting the problem on:
[Badaboom.zip](https://github.com/godotengine/godot/files/3307471/Badaboom.zip)

**Comment by KoBeWi** [comment]
`get_slide_collision(i)` doesn't return the colliding object, but a `KinematicCollision2D` object, which doesn't have `is_in_group()` or `queue_free()` methods. If you want to get the actual collided object, use the `collider` property of said collision:
```
for i in range(get_slide_count()):
	var collision_object = get_slide_collision(i).collider
```
