### ISSUE TITLE
Console error at startup: Invalid Function for Setter: ColorPicker::set_pick_color

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#29900]
Seems like a regression from bb0aeb48741033f80f7576bd138189931ffbaa62

![image](https://user-images.githubusercontent.com/3036176/59764153-dc02b400-92a3-11e9-85ec-1e25e2a7fe2e.png)

**Comment by Chaosus** [comment]
CC @KoBeWi

**Comment by KoBeWi** [comment]
Uh, I didn't notice that it's a setter and ClassDB complains about additional argument.

**Comment by akien-mga** [comment]
You can add
```
void ColorPicker::_set_pick_color(const Color &p_color) {
	set_pick_color(const Color &p_color, true);
}
```
as new binding.
