### ISSUE TITLE
2D Screen space shader demo blur effect not working on GLES2

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#29907]
**Godot version:**
3.1.1 official

**OS/device including version:**
Windows 10

**Issue description:**
I tried the 2D screen space shader demo and noticed that the blur effect is working on GLES3, but isn't showing anything on GLES2 without giving an error.

**Steps to reproduce:**
- Download the 2D screen space shader demo
- Run the project and select the blur effect

**Minimal reproduction project:**

https://godotengine.org/asset-library/asset/122

**Comment by clayjohn** [comment]
This is not a bug. GLES2 does not compute mipmaps for SCREEN_TEXTURE. 

It is documented here http://docs.godotengine.org/en/latest/tutorials/misc/gles2_gles3_differences.html#screen-texture-mip-maps

**Comment by Tobi-La** [comment]
Oh, that's bad. :( How can I achieve a blur effect in GLES2 then?

**Comment by clayjohn** [comment]
Render to a viewport and blur. Here is a simple example http://docs.godotengine.org/en/latest/tutorials/viewports/custom_postprocessing.html

**Comment by ChildLearningClub** [comment]
Another simple option is to use the the "WorldEnvironment" Node [https://www.youtube.com/watch?v=j5v8OVgnlzA](https://www.youtube.com/watch?v=j5v8OVgnlzA) Enable the "DOF Near Blur" and put your UI inside a CnavasLayer if not already in one. Adjust level of the CanvasLayer's and WorldEnviroment's Background Canvas Max Layer to fit your needs.

As [Rungeon](https://www.youtube.com/@rungeon83) Mentions in the video and [Bot.13](https://godotengine.org/qa/user/Bot.13) says here [https://godotengine.org/qa/28122/how-to-use-worldenvironment-node-in-2d](https://godotengine.org/qa/28122/how-to-use-worldenvironment-node-in-2d) Be sure to set the WorldEnvironment Background Mode to "Canvas".
