### ISSUE TITLE
Sometimes unable to enter text to Godot, when opened two instances of Editor

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29917]
**Godot version:**
3.2.dev.custom_build. c6507933a

**OS/device including version:**
Ubuntu 19.04 GNOME Shell 3.32.1 GTX 970  430.26

**Issue description:**
Sometimes when I open two instances of Godot(documentation page and script editor), then after some time of copying from documentation to script editor this error is shown in console
`No Target 'GTK_TEXT_BUFFER_CONTENTS'`
since that error I'm unable to use a keyboard in Godot(write to script editor and also use keyboard shortcuts like CTRL + S) in script editor window.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by qarmin** [comment]
Now I can't reproduce.
