### ISSUE TITLE
collisions does not works afther replacing static2d node

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2992]
test case:
1 -create a scene with a rigidbody2d (and relative collisionshape2d)
2 -add a staticbody2d with relative collisionshape2d
3 -collisions works great!
4 - replace staticbody2d with Node2d
5 - save
6 - replace again Node2d in staticbody2d
7 - save
8 - collisions does not works now

**Comment by GrandFunkR** [comment]
I do not know if I can be useful.
But I compared the files generated after saving in step 5 with the one after step 7.
I noticed that the last file lack these:
shapes/0/shape = SubResource( 1 )
shapes/0/transform = Matrix32( 1, 0, 0, 1, 0, 0 )
shapes/0/trigger = false

The scenes were saved tscn

**Comment by akien-mga** [comment]
I guess the collision shape resource is lost when switching from StaticBody2D to Node2D. I don't know if it's normal or a bug (it would be a bug if one would expect it to stay attached to the existing CollisionShape2D, even though it would not be working without a *Body2D parent of course).

**Comment by GrandFunkR** [comment]
I even think it's not a bug that switching from state to StaticBody2D Node2D resource shape is lost.
But I think it's a bug that switching from state to Node2S StaticBody2D resource shape is not restored.
In other words, switching from state StaticBody2D to Node2D and immediately afterwards do the reverse passage I expect to obtain the situation that had before. 
If this does not happen, to me it is a bug.

**Comment by reduz** [comment]
collision information is stored in CollisionObject, while CollisionShape is mostly an editor helper. Creating it or using in real-time does not work well.

This will change in 3.0 so CollisionShape is the one who actually holds collision information, but it won't be done now as it means breaking compatibility with saved scenes
