### ISSUE TITLE
Sometimes replace all not working

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29922]
**Godot version:**
3.2.dev.custom_build. c6507933a

**Issue description:**
Sometimes when I try to replace all words, a word which is after : (class name) doesn't replace. 
![file](https://user-images.githubusercontent.com/41945903/59849406-ce166700-9367-11e9-81f4-a8933f0ac30a.gif)

**Comment by Calinou** [comment]
Does this occur because the word that is being replaced is currently selected?

**Comment by qarmin** [comment]
No, it also happens when I select other words.

**Comment by Anutrix** [comment]
https://github.com/godotengine/godot/blob/e4193743306c1b2685eebf24f1c321fa0ff447ea/editor/code_editor.cpp#L194
Seeing this. I think might be related to https://github.com/godotengine/godot/issues/29916.

**Comment by Anutrix** [comment]
Also, found out that it skips one instance of string alternatively in each line.
e.g,
```
	q = Callassa Callassa
	q 
	q Callassa Callassa Callassa Callassa Callassa Callassa
	q = 
	q
```
When replaced all Callassa with 2 becomes:
```
	q = 2 Callassa
	q 
	q 2 Callassa 2 Callassa 2 Callassa
	q = 
	q
```
i.e, in each line, only oddth(1st, 3rd, 5th, etc) result is replaced.

**Comment by Anutrix** [comment]
Replacing https://github.com/godotengine/godot/blob/e4193743306c1b2685eebf24f1c321fa0ff447ea/editor/code_editor.cpp#L342 with `String text = get_replace_text();` fixes this issue but might have unexpected results due to this change in search_next() function.
