### ISSUE TITLE
Vehicle wheels not gaining traction

### ISSUE THREAD

**Issue by jonri** [godotengine/godot#29939]
When the Roll Influence of a tire is set very low (ex. 0.01), the tire will not maintain grip even at rest.  If you set the Roll Influence to surrounding values such as 0.0 or 0.1, the tire grip works as expected.  This can be verified using the value returned from get_skidinfo().

In the block of code starting here: https://github.com/godotengine/godot/blob/master/scene/3d/vehicle_body.cpp#L583 the intent appears to be to have contactDamping maximized at 0.2 when p_rollInfluence is 0.0, and the value decreases as p_rollInfluence increases.  When you have a roll influence of 0.1, 0.2, etc, the result of the division works out along these lines.  0.1 gives you contactDamping of 0.16, 0.2 gives you 0.08, etc.

If you decrease the divisor p_rollInfluence below 0.1, though, the contactDamping increases unbounded as you approach zero.  This results in values of contactDamping over 1.0, which appear to cause the tire to always lose grip.

@BastiaanOlij can you confirm the intent here?

Timofffee's Advanced Vehicle branch (#28733) fixed this for me because he removed the code in question entirely.  I propose clamping the contactDamping value to the intended maximum 0.2 in cases where it would go above that value.  This will keep the contactDamping the same for most vehicles where the Roll Influence is set to a more typical value.  PR to follow.

**Comment by akien-mga** [comment]
Fixed by #29940.
