### ISSUE TITLE
Math::is_nan(v.x) occures on ARVRCamera

### ISSUE THREAD

**Issue by AkatDeen** [godotengine/godot#29944]
**Godot 3.1.1 Stable**
**Windows 10**

**Issue: Math::is_nan(v.x) thrown when playing around with the transformation for ARVRCamera**

**Steps to reproduce:**
1. Just setup a normal VR Application
2. Create ARVRCamera as per normal VR Application:
 -- it works just fine when no calculation has been involved ARVRCamera.
 -- try attach one node to ARVRCamera as a child and do some transformation on the child node. the error will be catched as 'Math::is_nan(v.x) etc etc. (but still it is works just fine)
 -- or else: without any node attached, try to call ARVRCamera and play with the transformation through the script somewhere anywhere, it will throw the same error again. (yes still, the scripts just works as expected)
 -- for all these errors above, the codes or the nodes working great as expected, only that it throws an error... which the real matter is:-
 -- this error will prevent me from 'exporting' as 'released' application

**Comment by BenjaminNavarro** [comment]
I wanted to give this issue a try for my first contribution to Godot but I can't reproduce the issue (on Linux). 

Could you provide a sample scene where this error appears please?

**Comment by toddmedema** [comment]
Should we close this? Seems inactive, unreproduced, and like https://github.com/godotengine/godot/issues/32611 might have fixed it
