### ISSUE TITLE
Parent directory "../" in File Chooser should not be shown at the root of "res://"

### ISSUE THREAD

**Issue by TierraDelFuego** [godotengine/godot#2994]
I am running on linux using current git.
Steps to reproduce:
1. Create a Sprite
2. Inspector->Sprite->Texture->Load
3. Try going up the directory tree and nothing happens

Clicking the Up Arrow or the double-dot folder does not work.

If I use the Import feature, the File Chooser works correctly.

**Comment by akien-mga** [comment]
Well I don't think that's a bug. When you load a resource like a texture, it's expected to be in your project folder (the "res://" filesystem). It's this filesystem which will be exported as your game's data.

So if you want to use say a PNG file as texture, you need to copy it first in your project directory.

**Comment by akien-mga** [comment]
Actually I'm sure it's not a bug. "Load" expects the file to be in res://, i.e. your project folder. If you want to move an external file inside the filesystem, you need to either copy it using your system's file manager/cp, or import it within Godot (but the file will then likely be converted to an internal binary format).

**Comment by TierraDelFuego** [comment]
Okay, I was watching a tutorial and the author was on windows and was able to do this. But maybe this is a new feature as the tutorial was from Jan. 2015

Also it is confusing to have directory traversal options appear but not work, so at least the options should not be visible.

**Comment by akien-mga** [comment]
I'll have a look. What tutorial was it?

**Comment by TierraDelFuego** [comment]
@akien-mga the tutorial was a gamefromscratch and I re-watched the video and I was wrong. He switched between the windows too fast so I confused the import steps he showed with the Inspector stuff he showed.

Since I am new to Godot I will tell you that I would be okay if the File Chooser let me look outside the root of res://.  But if I load something that way I would not mind if it copied that under my root res://.  But maybe this is a confusing and untraditional approach that might create more problems than it solves.
