### ISSUE TITLE
Custom Drawing and Particles2D show performance problems on MacOS

### ISSUE THREAD

**Issue by JustAntoRS** [godotengine/godot#29945]
**Godot version:** 3.1.1

**OS/device including version:** MacOS 10.14.5

**Issue description:**
When adding Particles2D to the scene the performance slows a lot, [video showing it](https://imgur.com/a/EfxaIQv)

I have tested the same project on other OS like Windows and Linux on computers with similars components to my MacBook and this problem disappear and it works flawlessly.

**Minimal reproduction project:**
[Download Link of the project ](https://we.tl/t-K54vx0eWpZ)

**Comment by Zireael07** [comment]
Is the Mac monitor a retina?

**Comment by JustAntoRS** [comment]
Retina, the exact model is MacBook Pro 13 inch,2017 [the 1500$ one](https://www.apple.com/shop/buy-mac/macbook-pro)

**Comment by Calinou** [comment]
I guess you may need to render the project at a lower resolution on hiDPI displays (by default, at least). This can be achieved by setting **Display -> Window -> Stretch -> Shrink** to 2 in the Project Settings, provided the stretch mode is currently `viewport`.

**Comment by Zireael07** [comment]
@Calinou wouldn't that take effect always? Can he tell from GDScript whether the display is hiDPI? So that he can then set shrink from code only if needed?

**Comment by JustAntoRS** [comment]
> I guess you may need to render the project at a lower resolution on hiDPI displays (by default, at least). This can be achieved by setting **Display -> Window -> Stretch -> Shrink** to 2 in the Project Settings, provided the stretch mode is currently `viewport`.

Doing that makes the game unlplayable by just showing a quarter of the area :S 
![](https://i.imgur.com/fFoGbY5.png)

**Comment by Zireael07** [comment]
Hm, weird - the shrink setting should just decrease the resolution of your viewport (not affecting anything else). Are you sure your stretch mode is "viewport"?

**Comment by JustAntoRS** [comment]
Yes, stretch mode is viewport and stretch aspect is keep although changing it didn't produce any change in the shrink

**Comment by Calinou** [comment]
> Can he tell from GDScript whether the display is hiDPI?

From what I've seen, there's no built-in method that returns the OS scaling factor, but you can perform a check manually like this:

```gdscript
if OS.get_screen_dpi() >= 192 and OS::get_singleton()->get_screen_size().x > 2000:
    # Screen is HiDPI
else:
    # Screen is LoDPI
```

This is the check used by the Godot editor (which automatically sets the editor scale to 2.0 if applicable).

**Comment by JustAntoRS** [comment]
I've been searching and I've found the problem! 

Id you download the project from the link in the first post on this issue you will see I have a node called Net that is just a Node2D with a script that does:

```
func _draw() -> void:
	var y : float = 16
	var x : float = get_viewport_rect().size.x/2
	var color : Color  = Color(1,1,1,0.1)
	var from : Vector2 = Vector2(x,y)
	var to : Vector2 = Vector2(x,y+50)
	var counter : int = 0

	
	while counter < 16:
		draw_line(from,to,color,10,true)
		y += 66
		from = Vector2(x,y)
		to = Vector2(x,y+50)
		counter+=1
```
Basically it uses Custom Drawing to draw 16 lines in the middle of the screen, I thought this was a nice method to draw a simple net and more optimised than creating 16 Sprites.

If you add this node to scene with the Particles2D nodes you get the performance problems already show, but if you delete this node the problem disappear :O 

So in MacOS I can't have Custom Drawing and Particles2D at the same time I guess :S

Hope this help, and thanks to everyone for the help, you're amazing!

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(the attached project doesn't seem to be downloadable anymore)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/17584.

**Comment by akien-mga** [comment]
No answer to https://github.com/godotengine/godot/issues/29945#issuecomment-664028716, so closing.
