### ISSUE TITLE
Errant particles when instancing Particles2D with global particles and after SceneTreeTimer's timeout

### ISSUE THREAD

**Issue by possatti** [godotengine/godot#29952]
**Godot version:** 3.1.1 Stable

**OS/device including version:** Ubuntu 18.04.2 LTS x86_64
**GPU:** GeForce GTX 1060 6GB
**Nvidia Driver Version:** 418.56

**Issue description:**
When instancing a Particles2D with `local_coords = false` after some delay using `get_tree().create_timer()`, the first few particles will be emitted from global origin (0,0), even though the node is being instanced somewhere else on the scene.

The problem does not happen when using a regular `Timer` instead of a `SceneTreeTimer`. However, using a regular `Timer` requires writing significant more boilerplate code.

**Steps to reproduce:**
1. Wait `get_tree().create_timer()` timeout.
2. Instance a Particles2D node with `local_coords = false`.
3. Immediately position the Particles2D away from origin, and add it as a child.
4. The first few particles will be emitted on origin.

**Minimal reproduction project:** [particles_bug.zip](https://github.com/godotengine/godot/files/3314266/particles_bug.zip)

Run the "World" scene to see the problem. The function `_on_Timer_timeout()` will instance a new Particles2D node every half second. In there I've prepared 5 different functions that could help narrow down the problem. Uncomment the one you want to test, and comment the other ones. The 5 functions are:
 - `this_works()`: Instance Particles2D with no delay at all.
 - `doesnt_work_1()`: Instance Particles2D immediately, but only add it as a child after some delay with `get_tree().create_timer()`.
 - `doesnt_work_2()`: Wait some delay with `get_tree().create_timer()` and only then instance the Particles2D and add it as a child.
 - `works_with_timer_1()`: Same as `doesnt_work_1()` but use a regular `Timer`.
 - `works_with_timer_2()`: Same as `doesnt_work_2()` but use a regular `Timer`.

I also recorded my screen showing the problem. I don't know how to embed it here, so I just zipped it and here it is: [godot_particles_bug_screencast.zip](https://github.com/godotengine/godot/files/3314272/godot_particles_bug_screencast.zip)

**Comment by clayjohn** [comment]
Note: This only applies to gpu Particles and not to CPUParticles.
