### ISSUE TITLE
When changing the theme SpinBox icon shifts

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#29956]
**Godot version: 3.1.1**

![0000](https://user-images.githubusercontent.com/11189223/59924939-90850d00-943f-11e9-88ab-60e9bdc95b87.png)

[Demo.zip](https://github.com/godotengine/godot/files/3314599/Demo.zip)

**Comment by guilhermefelipecgs** [comment]
Replace this code:
```
get_node("SpinBox").get_line_edit().minimum_size_changed()
get_node("SpinBox").set_size(get_node("SpinBox").get_minimum_size())
```
with this:
```
get_node("SpinBox").set_size(get_node("SpinBox").get_minimum_size())
get_node("SpinBox").minimum_size_changed()
get_node("SpinBox").get_line_edit().minimum_size_changed()
```

**Comment by guilhermefelipecgs** [comment]
Related issue #29816

**Comment by DimitriyPS** [comment]
In 3.0.6 it was enough:

`get_node ("SpinBox").set_size (get_node ("SpinBox").get_minimum_size())`

**Comment by guilhermefelipecgs** [comment]
Marking as regression then.

**Comment by DimitriyPS** [comment]
So same in 3.0.6 not was this:

https://github.com/godotengine/godot/issues/29816

Probably by analogy mark as regression.

**Comment by DimitriyPS** [comment]
So same in 3.0.6 not was this:

#29816

Probably by analogy mark as regression.
