### ISSUE TITLE
The first update of tween should happens as soon as start() is called

### ISSUE THREAD

**Issue by hatemsh** [godotengine/godot#29966]
**Godot version:** 5c66771e3ebccdfec55bb94ea521d2f24cb6200a

**Issue description:**

The first update of tween property/method/callback should happens as soon as start() is called

Right now the first property change applies on the next frame and not when start is called.
This is a problem in my case because I'm trying to create a queue of tweens that are run one after the other. this causes a flicker in the animation if my tweens have a duration of 0. 
I have to wait a frame before I can remove them and call start on the next tween.

**Steps to reproduce:** 
This code doesn't work because the tween is freed before the interpolation happens. If I remove the last if statement I get a flicker where each tween change happens on a different frame even if their duration is 0
```
func start_next_if_exists():
	if current && !current.is_active():
		current.queue_free()
		current = null

	if !current && !array.empty():
		current = array.pop_front()
		current.start()
                
		if current.get_runtime() == 0:
			current.queue_free()
			current = null
			start_next_if_exists()
```

**Comment by KoBeWi** [comment]
The new Tween system in 4.0 allows for very easy chaining, so this is no longer necessary.
