### ISSUE TITLE
collisionshape and images deform

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2996]
it would be nice if you could deform collisionshape and images. 
Take a look at this game many years ago: https://www.youtube.com/watch?v=437Ld_rKM2s 
The barrier is deformed when a bullet hits.

**Comment by akien-mga** [comment]
Well to make space invaders you would likely give each invader its own collision shape... but the feature you're asking from might still be interesting in other cases I guess.

**Comment by GrandFunkR** [comment]
I do not understand.
The barrier deform depends on bullet impact point.
In any case, sure maybe space invaders is not the best example.
but it is only one example

**Comment by reduz** [comment]
yeah this will be possible when we add local image manipulation in 2.1

**Comment by vnen** [comment]
"Image deforming" is the same request as #2914, though that doesn't mention collision shape deform.

**Comment by akien-mga** [comment]
I think these things are now planned more for 3.0.

**Comment by bojidar-bg** [comment]
Image deform is planned for 3.0 (and is duplicate in #2914), but softbody deformations are likely going to be for 3.1 or even later (even if they are fakeable with joints even now).

Bugsquad: I can't find another issue about softbodies, so as to mark this as a duplicate... Do you remember if we had one?

**Comment by reduz** [comment]
-bad news, no deforming images yetm kicking to 3.1
-good news, deforming collision shapes now works

**Comment by reduz** [comment]
oh but since this is a duplicate now, just closing
