### ISSUE TITLE
TileSet error spam when opening a scene with (old) TileMap

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#29962]
**Godot version:**
3.2 master (34224d5)

**OS/device including version:**
Any

**Issue description:**
When I opened the `Node2D.tscn` scene in the attached project, I get this errors repeatedly:
```
ERROR: tile_get_shape_transform: Index p_shape_id=0 out of size (tile_map[p_id].shapes_data.size()=0)
   At: scene/resources/tile_set.cpp:753.
ERROR: tile_get_shape_transform: Index p_shape_id=0 out of size (tile_map[p_id].shapes_data.size()=0)
   At: scene/resources/tile_set.cpp:753.
ERROR: tile_get_shape: Index p_shape_id=0 out of size (tile_map[p_id].shapes_data.size()=0)
   At: scene/resources/tile_set.cpp:734.
ERROR: tile_get_shape_one_way: Index p_shape_id=0 out of size (tile_map[p_id].shapes_data.size()=0)
   At: scene/resources/tile_set.cpp:782.
ERROR: tile_get_shape_one_way_margin: Index p_shape_id=0 out of size (tile_map[p_id].shapes_data.size()=0)
   At: scene/resources/tile_set.cpp:801.
```

The TileSet was generated from a scene in Godot 3.1, and it does not produce errors there.

**Steps to reproduce:**
See above.

**Minimal reproduction project:**
[jetpaca-tilemap.zip](https://github.com/godotengine/godot/files/3315320/jetpaca-tilemap.zip)

**Comment by qarmin** [comment]
This is caused by this commit - https://github.com/godotengine/godot/commit/02319dceb2e17184eb765c67719a306f56dafc1b.
Before this commit, errors were simply silenced.

**Comment by akien-mga** [comment]
Had a quick look, I think some of those changes should likely be undone. The whole class seems to be written with the assumption that you can call things like `tile_get_shape_transform(int p_id, int p_shape_id)` and get `Transform2D()` back if the `p_id` or `p_shape_id` is invalid.

So either we keep allowing this (that's bad design, but the whole class seems designed around it), or we would have to add stuff like this in many places:
```diff
diff --git a/scene/resources/tile_set.cpp b/scene/resources/tile_set.cpp
index f577a2e14..4d20413b2 100644
--- a/scene/resources/tile_set.cpp
+++ b/scene/resources/tile_set.cpp
@@ -756,7 +756,11 @@ Transform2D TileSet::tile_get_shape_transform(int p_id, int p_shape_id) const {
 }
 
 void TileSet::tile_set_shape_offset(int p_id, int p_shape_id, const Vector2 &p_offset) {
-	Transform2D transform = tile_get_shape_transform(p_id, p_shape_id);
+
+	Transform2D transform;
+	if (tile_map.has(p_id) && p_shape_id < tile_map[p_id].shapes_data.size()) {
+		transform = tile_get_shape_transform(p_id, p_shape_id);
+	}
 	transform.set_origin(p_offset);
 	tile_set_shape_transform(p_id, p_shape_id, transform);
 }
```

**Comment by akien-mga** [comment]
Above snippet can be a bit prettier using the proper methods for that though:
```
if (has_tile(p_id) && p_shape_id < tile_get_shape_count(p_id))
```
