### ISSUE TITLE
Can't get latest master to compile, libpng, linux mint 18.2

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#29967]
**Godot version:**

Godot master 10cf5ac (21/6/2019)

**OS/device including version:**

Linux Mint 18.2 Cinnamon 64 bit

**Issue description:**

Pull latest master, can't compile:

```
scons: Reading SConscript files ...
Package libpng16 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpng16.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpng16' found
OSError: 'pkg-config libpng16 --cflags --libs' exited 1:
  File "/home/baron/Apps/Fork/godot/SConstruct", line 312:
    detect.configure(env)
  File "./platform/x11/detect.py", line 219:
    env.ParseConfig('pkg-config libpng16 --cflags --libs')
  File "/usr/lib/scons/SCons/Environment.py", line 1576:
    return function(self, self.backtick(command))
  File "/usr/lib/scons/SCons/Environment.py", line 594:
    raise OSError("'%s' exited %d" % (command, status))
20:21:24: The process "/usr/bin/scons" exited with code 2.
Error while building/deploying project GodotFork (kit: Desktop)
When executing step "Custom Process Step"
```
Apologies as I'm very new to linux and the whole handling of dependencies, so it is probably due to me being a linux newbie. I tried installing libpng16-dev in synaptic package manager, and it says this:

```
To be removed:
libfreetype6-dev
libpng12-dev
```

Once installed the compile no longer complains about libpng16 but instead complains that libfreetype is not found. It seems to be a circular dependency problem - the source needs libpng16 but that removes libpng12, but freetype2 requires libpng12?

Is this a problem at my end that I can resolve? I'm guessing this is related to PR #29874
In this PR they mention using builtin_libpng (presumably the source in thirdparty folder). Should it be using this on mine?

**Comment by Calinou** [comment]
> In this PR they mention using builtin_libpng (presumably the source in thirdparty folder). Should it be using this on mine?

Yes; we should probably set `builtin_libpng` to `yes` by default.

**Comment by lawnjelly** [comment]
Fantastic! :smile: That sorted it.
I don't feel so stupid for asking now, maybe it will help someone else with the same problem.
