### ISSUE TITLE
[Compatibility] template glibc version check too strict

### ISSUE THREAD

**Issue by Houkime** [godotengine/godot#29976]
**Godot version:**

3.2.dev.custom_build.ce8e54133

**OS/device including version:**

* Arch Linux - compiling machine
  * glibc 2.29
  * Scons 3.0.4
  * clang 8.0.0
* Ubuntu 18.04 - playing machine
  * glibc 2.27

**Issue description:**

Export templates compiled against glibc 2.29 won't run with glibc 2.27

Screenshot from ubuntu VM (replicating original issue):  
![bs](https://user-images.githubusercontent.com/32805122/59962293-ed7dd300-94d2-11e9-9ba0-80ab4cef60a4.jpg)

#### Expected:

glibc check not that strict and considering actual ABI-breaking glibc changes and not just version numbers.

**Steps to reproduce:**

* compile Godot master on a machine with glibc 2.29 along with an x11 template.
(probably 2.28 will also suffice)
* export any project using your compiled template
* try to run it on Ubuntu 18.04 (VM suffices) or probably any other system with glibc that differs from compile-time glibc.

**Minimal reproduction project:**
blank project should be enough (I used GLES3 3D scene)

**Comment by Houkime** [comment]
oops, actually used llvm this all time. Should check gcc as well.

**Comment by Houkime** [comment]
gcc-produced builds also demonstare this behavoir (gcc 9.1)

**Comment by Calinou** [comment]
If you want export templates to be portable across distributions, you should build them on the oldest distribution you wish to target. Using an Ubuntu 16.04 VM/container works wlel for this purpose.

**Comment by Houkime** [comment]
I tried `use_static_cpp=yes` now but it doesn't really help. 

Although it should and there is no point in it whatsoever if it doesn't since it means that linking was still dynamic despite this flag. Note that godot does not employ only C++, but C files also.

**Comment by Calinou** [comment]
> Although it should and there is no point in it whatsoever if it doesn't since it means that linking was still dynamic despite this flag. Note that godot does not employ only C++, but C files also.

`use_static_cpp=yes` is *only* helpful if you use an old distribution but a recent compiler version. It won't help if you still build on a recent distribution.

**Comment by Houkime** [comment]
I ended up setting up a Debian 8 VM, building an x11 release template there and extracting built binary via SFTP (which was as easy as forwarding an SSH port in virtualbox network settings).
Success.

**Comment by Calinou** [comment]
You could likely speed up the process a lot by setting up a [Docker](https://www.docker.com/) container:

```bash
docker run -it debian:8
# Starts an interactive session in the container
# (paste commands to build Godot here…)
```

To get the binary back on the local system:

```bash
# Get the container name for use in `docker cp`
docker ps

# Copy the compiled binary to local filesystem
docker cp <name>:/root/godot/bin/godot.x11.opt.64 .
```

You can reuse the container by starting it using `docker start --attach <name>`.

**Comment by akien-mga** [comment]
I thought we were building official Linux binaries on a recent Fedora, but @hpvb actually confirmed that we build them on an old Ubuntu release:

> Official binaries are actually built on an ancient Ubuntu. There's no way at all to do this without that. The only option would be to start bundling a c library and libstdc++ with Godot...

So this issue effectively can't be solved. Documentation was improved in godotengine/godot-docs#2556 so this can be considered fixed. I might have a go at further improving the docs to document the use of `use_static_cpp=yes`, LTO and how to install a modern compiler on an ancient distro for best compatibility and performance.
