### ISSUE TITLE
Ability to create a new Image from GDScript

### ISSUE THREAD

**Issue by ratsdiov** [godotengine/godot#2998]
Usage scenario - I want to create a height map at run time and then set that image as the texture for a sprite (in this case just for debugging purposes so I can see the height map).  The Image built in type does not seem to allow creation from GDScript with control over the format, size, etc.  Creating an empty image and then using resized() on it crashes godot.

There are a couple create methods in image.cpp that look to do what I would like but I don't think they are exposed.

**Comment by bluenote10** [comment]
As a complete newcomer to GDScript I'm surprised why `Image.create` and `Image.create_from_data` aren't static functions. I assume the work-around is to use `Image.new().create(...)`?
