### ISSUE TITLE
Trouble with a Large Model

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot#29990]
**Godot version:**
3.1.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
I have a large city of about 500k triangles that I can't seem to manipulate in Godot. I finally exported it in two OBJs (having tried all other formats as well as exporting in a single OBJ) and I was able to put both into a scene. The first half is for some reason gray, the other fully textured. When I try to manipulate either half, the editor stops responding (but doesn't crash).

**Comment by KoBeWi** [comment]
Would be helpful if you provided the model here.

**Comment by KoBeWi** [comment]
@OriginalAGP Can you still reproduce this in 3.2.2?

**Comment by fire** [comment]
Closing due to lack of reproduction project.

Can reopen if posted.
