### ISSUE TITLE
Should we be able to use get_packet_port() before get_packet()?

### ISSUE THREAD

**Issue by Sphynxinator** [godotengine/godot#29999]
**Godot version:**
3.1

**OS/device including version:**
Windows 8.1

**Issue description:**
Hi. As you know, UDP is not like TCP. I mean, when you use TCP with the server, you can handshake with the server and server knows that it is you and you know that is the server. But in UDP, for example the server(my server is node.js) gives the client a port number and server knows which client is sending message to the server. But the client, Godot Engine, doesn't  know if the message is sent for itself. I mean, there may be another client in same IP and server may send its message to the other client. Godot have to take packet first and it can control the port then. But if the packet is not for the client, the packet loss happen. Is there any change that we can use the get_packet_port() before the get_packet() function?

**Comment by Faless** [comment]
> But if the packet is not for the client, the packet loss happen.

I'm not sure I follow.
If you receive a packet on a socket, you must consume it before you can receive more.
I'm not sure what you mean by packet loss happen when you actually received the packet.
Simply, if you receive a packet from an unacceptable source you should drop it (i.e. not process it).

**Comment by Sphynxinator** [comment]
Clients take packet for processing, right? What if the server sent the packet for the other client on the same IP? If the wrong client takes and drops it before the real client takes it, the real client couldn't process it? Am I wrong? Sorry if I am wrong.

**Comment by Faless** [comment]
> What if the server sent the packet for the other client on the same IP

The socket to which the packet will be passed by the OS is decided by the IP/port pair, You can have only one socket listening on that IP/port, so, another client on the same IP will have a different port.

(to be complete there's a bit more to that on UDP, since most OSes support "connecting" a UDP socket, and in that case you can bind two sockets to the same IP/port pair because the "connected" one will only receive packets from one source address/port)

**Comment by Sphynxinator** [comment]
So I don't have to do something to take the correct packet? The server will automatically send the correct packet to the client?

**Comment by Faless** [comment]
> So I don't have to do something to take the correct packet? The server will automatically send the correct packet to the client?

You set the destination address and port of the client. Send the packet. (Assuming network works). Client receive the packet.

**Comment by Sphynxinator** [comment]
Sorry, that's the point that I am missing. I set the destination address and port of the server, but where exactly I set the port of my client and how I set the port of the client of uniquely? For example, what if I set the port that already exists? And also the server sets a port for the client, and what if my client port is different from the server's attached port of client? And I don't see any port setting function in PacketPeerUDP. `set_dest_address()` sets the destination server address, right? And `listen()` is for UDP server, right? Sorry if it's confusing.

**Comment by Faless** [comment]
If you don't call `listen` a random free port will be assigned by the OS.
If you call `listen` on a port on which another socket is listening you will get an error.
The server will know the right IP/address by reading the source packet information (`get_packet_port` and `get_packet_ip` in case of a godot server)

**Comment by Sphynxinator** [comment]
Okay then I should do more test. Thank you.
