### ISSUE TITLE
animationplayer bessel animate curve can't be edited exactly.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29997]
**Godot version:**
3.1.1

**OS/device including version:**
macos 10.14.4

**Issue description:**
Make alpha or scale aniamte bessel curve need value around 0 or 1. But curve editor give large number with little change.
If edit the curve with input number. The curve will display like a stright line.(useless)

![](https://user-images.githubusercontent.com/1890538/59972681-2054c380-95c6-11e9-93bc-8ee44f72e8d6.png)

**Comment by KoBeWi** [comment]
Seems like the curve editor can't scale the value range/step (unless I'm missing some obscure button).
