### ISSUE TITLE
class_name icon not scaled in Inspector tab

### ISSUE THREAD

**Issue by epuscasu** [godotengine/godot#30003]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Pro 64-bit (10.0, Build 17134)

**Issue description:**
Custom class/node icons are not scaled and may overlap elements in the Inspector tab. Icon is also not used until project reload (standard Node icon is used instead). 

![image](https://user-images.githubusercontent.com/11788042/59974867-ac142300-95b9-11e9-9385-dda0373cf0cf.png)

**Steps to reproduce:**
1) Create new project
2) Create a script with minimal class registering code (standalone or attached to a node) then save

```
extends Node
class_name test, "res://icon.png"
```

3) Creating a new test node now leads to it having a Node icon in the Inspector tab (this may be intended behavior?)

![image](https://user-images.githubusercontent.com/11788042/59975247-cac8e880-95be-11e9-8c86-f7f3b446fd22.png)

4) Close and open project again. Creating a test node now leads to it having the icon assigned using class_name instead of the icon shown prior to reloading. Also, the icon doesn't scale and overlaps elements in the Inspector tab.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/3317753/test.zip)

**Comment by epuscasu** [comment]
Might be related to #23849 ?

**Comment by creikey** [comment]
When I followed the reproduction steps, the icon was not clipped, however it did only reappear on relaunching of the editor.
