### ISSUE TITLE
Appease the OCD of all repository watchers eagerly waiting for issue 3000

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3000]
Here you are.

**Comment by bojidar-bg** [comment]
:+1:

**Comment by volzhs** [comment]
waiting for 2.1 stable :+1:

**Comment by Calinou** [comment]
I can reproduce this on my brain.

Steps to reproduce:
- Watch the issue title.
- Watch it harder.
- Quietly weep.

**Comment by akien-mga** [comment]
Fixed by #3000.

Ugh.

**ERROR:** Division by 0. Call a theoretical physicist.
