### ISSUE TITLE
Webtorrent support

### ISSUE THREAD

**Issue by unicomp21** [godotengine/godot#30008]
Feature request

Browser support, webassembly

**Issue description:**
In addition to the existing webrtc support, which is AMAZING!  Could we also get webtorrent support?  The intention being to bring down, or possibly eliminate, the bandwidth bill for games requiring large amounts of geometry, like in the gigabyte-terabyte range.

**Steps to reproduce:**
feature request

**Minimal reproduction project:**
feature request

Please assign to Fabio Alessandrelli

**Comment by Faless** [comment]
Well, I don't think it's something we should implement in the engine.
Use cases are limited so it should be implemented as a plugin for the asset-lib in case.
Additionally, the implementation is in Javascript (Node.js) so including it is really not doable. But then again, I don't think this is something we need in core at all.

**Comment by KoBeWi** [comment]
Seeing as it's another feature that "should be implemented as a plugin", maybe we should have a label for these? (unless topic:plugin would work)

**Comment by Anutrix** [comment]
Maybe a topic called plugin proposal 
> 
> 
> Seeing as it's another feature that "should be implemented as a plugin", maybe we should have a label for these? (unless topic:plugin would work)

**Comment by Faless** [comment]
> maybe we should have a label for these?

I would argue these issues should be closed after a while, unless someone brings new reason for their inclusion in core. I think having plugin requests in godot repo is going to just clutter the issue tab.

**Comment by Faless** [comment]
Closing, this could be done via plugin, even directly in GDScript (or easier by using an external library via GDNative/Javascript singleton), and there is no real need to have it in core.
