### ISSUE TITLE
godot error initializing : directional shadow framebuffer status invalid and other

### ISSUE THREAD

**Issue by MrPeace03** [godotengine/godot#30013]
![Capture](https://user-images.githubusercontent.com/52131799/59981042-a3920b80-95fe-11e9-9194-a661640f18fe.PNG)

**Comment by KoBeWi** [comment]
First error is a duplicate of #28894

**Comment by akien-mga** [comment]
Duplicate of #28894 indeed. Not enough details to know if there's anything else here.
