### ISSUE TITLE
Replace md5/sha256/aes misc library with mbedTLS ones?

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#30025]
While playing around with external libraries I noticed that we are using 3 external libraries for md5 and sha256 hasing, and aes encryption in core. (`thirdparty/misc/`)

I propose we use the mbedtls ones (which we would ship anyway).
It's pretty easy to have `core` include only the needed file (so builds will work with mbedtls module disabled, and only bringing along those files). AES instead, requires a couple of functions from platform.c and platform_util.c. They are really minimal dependencies (zeroize function, 2 macros) so it can be hacked/proposed upstream with a flag in a way that's embeddable without them. Otherwise we'll have to ship those 2 files too.

What do you think?

**Comment by Faless** [comment]
To wrap around those functions (so if we change library we won't have to change a lot of code), we could use always available functions (i.e. even when `module_mbedtls_enabled=no`) in the new crypto header #29871

**Comment by akien-mga** [comment]
Sounds good, as long as I'm still able to build against system mbedtls (including with the mbedtls module disabled, even though it would be an unlikely scenario), i.e. `rm -rf thirdparty/mbedtls && scons p=x11 builtin_mbedtls=no module_mbedtls_enabled=no`.

**Comment by Faless** [comment]
Well, the idea is to work with `scons p=x11 builtin_mbedtls=no module_mbedtls_enabled=no` not sure with the `rm -rf thirdparty/mbedtls`.
I was thinking to always bundle builtin library for those 3 files (and *only* those 3 files).
But I guess it could be done working the other way too, as long as the mbedtls is compatible (which should be the case for mbedtls 2.7+, we are using 2.16 but those functions should be retro-compatible)

**Comment by akien-mga** [comment]
> Well, the idea is to work with scons p=x11 builtin_mbedtls=no module_mbedtls_enabled=no not sure with the rm -rf thirdparty/mbedtls.
I was thinking to always bundle builtin library for those 3 files (and only those 3 files).

The thing is that if the user chooses `builtin_mbedtls=no`, we should not use any builtin mbedTLS code without telling them. As long as the core code uses system include paths without hardcoded `thirdparty/mbedtls` prefix, and that `platform/x11/detect.py` enforces linking system mbedtls even with the module disabled, it should work.

**Comment by akien-mga** [comment]
> The thing is that if the user chooses builtin_mbedtls=no, we should not use any builtin mbedTLS code without telling them. As long as the core code uses system include paths without hardcoded thirdparty/mbedtls prefix, and that platform/x11/detect.py enforces linking system mbedtls even with the module disabled, it should work.

Though thinking about it some more, linking the full mbedtls just for the sake of some crypto methods that used to be provided via small headers is a bit overkill. So I guess core should use system mbedtls code if the module is enabled, and enforce using builtin code if the module is disabled.

- `builtin_mbedtls=yes`: use builtin code for core
- `builtin_mbedtls=no module_mbedtls_enabled=yes`: use system code for core
- `builtin_mbedtls=no module_mbedtls_enabled=no`: use builtin code for core (so it will fail building if the user removes `thirdparty/mbedtls`, but at this point we can say that we don't support this scenario)

**Comment by Faless** [comment]
Fixed after #30239 , I forgot to reference it.
