### ISSUE TITLE
FPS Tutorial Sticky Grenades Performance Issue

### ISSUE THREAD

**Issue by afable** [godotengine/godot#30037]
**Godot version:**

Godot_v3.1.1-stable_win64

**OS/device including version:**

NVIDIA GeForce GTX 1050 Ti
AMD Phenom II X6 1100T Processor, 3.30 GHz
16GB RAM

**Issue description:**

Following the **Adding grenades** part of the FPS tutorial (https://docs.godotengine.org/en/3.1/tutorials/3d/fps_tutorial/part_five.html):
- When firing sticky grenades, FPS performance decreases significantly.
- Normal grenades are fine.
- Issue occurs on both Ruins & Space level but not in the Testing Area.
- Disabling the Sticky_Area/Collision_Shape node in Sticky_Grenade.tscn allows firing sticky grenades without FPS performance decrease.
- Issue also occurs from the completed project download link at the bottom of the tutorial page.
- Recording of issue can be found here: https://youtu.be/4XLGV4T3H8Q

**Steps to reproduce:**

**Minimal reproduction project:**

[Godot_FPS_Starter.zip](https://github.com/godotengine/godot/files/3321369/Godot_FPS_Starter.zip)

**Comment by KoBeWi** [comment]
Sooo I tried the demo in 3.2.3 rc1 and FPS drop is noticeable, but not sure if it's really physics problem or demo problem or what. I'd just close it and only reopen with an actual engine issue.

**Comment by akien-mga** [comment]
Closing as per the above, it's not clear whether there's any engine bug or just a project-specific bug.
