### ISSUE TITLE
Properties from scripts do not update in the inspector when they are changed in an external editor

### ISSUE THREAD

**Issue by mcanders** [godotengine/godot#3003]
If I add/edit a property in a script (ex: add "export var new_property = 1") from an external editor, the change will not be reflected in the inspector unless I restart godot.  Closing and reopening the scene does not help, nor does selecting some other node and re-selecting the node with the changed property (which often works for the internal editor). 

Note: I have the external editor setting enabled.

**Comment by vnen** [comment]
Question: are you using 1.1 or a recent alpha version?

**Comment by mcanders** [comment]
recent alpha built from source less than two weeks ago on linux

**Comment by vnen** [comment]
Just tested and there is an issue indeed. However, for me it does update the inspector if I just close and reopen the scene.

**Comment by mcanders** [comment]
Maybe that issue was fixed with recent changes?  Right now Im blocked by #2995

**Comment by mcanders** [comment]
#2995 was fixed so I was able to build.  My experience is now the same as @vnen.  The changes are not shown when I reselect a node, but they are when I reopen its scene.

**Comment by reduz** [comment]
yeah external editor has some issues, i will work on it
