### ISSUE TITLE
Incline/Shear in Basic Node same as Sprite (Move, Rotate, Scale)

### ISSUE THREAD

**Issue by tonypuglieso** [godotengine/godot#30046]
Godot version:
3.1 stable

Inclination to basic nodes objects as in inkscape? It would be very beneficial for 2D isometric 2D cut / exit animation inside godot. That is, in the same category as move, rotate, scale.

It is true that I could use a polygon2D and move the nodes, but when you have characters composed of many objects, it has lower performance than a basic sprite.

**Comment by bojidar-bg** [comment]
Skew was implemented in efb1f7d76b63d56fc0c097d13b4b6d7b91250611 for master/4.0. Closing for now, please comment if this issue is not about skew.
