### ISSUE TITLE
Area2D `body_entered` signal has a problematic type hint.

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#30040]
**Godot version:**
3.1.1-stable

**Issue description:**
Area2Ds signal `body_entered` type hints the body as `PhysicsBody2D`.
Problem is that TileMap, while being considered a body, doesn't inherit `PhysicsBody2D` and thus results in `null` on conversion. The easiest would probably type hinting bodies as `Node2D` (as that is the closest common ascendant) but it that would include a lot more than just bodies.

**Comment by KoBeWi** [comment]
Duplicate of #27076 and #24739

**Comment by akien-mga** [comment]
Beat me to it, I was looking for those issue numbers :D

**Comment by akien-mga** [comment]
I'll change the type hint as suggested though, it's not a perfect solution but it does fix a bug in the current bindings.

**Comment by Byteron** [comment]
Oh I missed those. Apologies!
