### ISSUE TITLE
Allow getting control focus owner from the scene tree

### ISSUE THREAD

**Issue by Nukiloco** [godotengine/godot#30042]
**Godot version:**

Godot v3.1

**OS/device including version:**

Windows 10

We should be able to get the focus owner from the scene tree because right now the only way to get the focus owner of any control node is to create or find a control node in the scene and then call the get_focus_owner function.

**Comment by Zylann** [comment]
The focus owner is actually referenced in `Viewport`, yet not exposed.

**Comment by KoBeWi** [comment]
#34269 adds a signal emitted when focus changes, providing the focused Control, so I assume that would be sufficient if it gets merged.

**Comment by KoBeWi** [comment]
Aaand it got merged.

@Flairieve Is `gui_focus_changed(control)` signal enough to close this? You can connect to it to receive the focused control, but the downside is that you can't poll for the focus owner at any time.

**Comment by akien-mga** [comment]
I think we could just expose `Viewport`'s `_gui_get_focus_owner` as a public method (without `_` prefix).

**Comment by fossegutten** [comment]
Would be nice @akien-mga, to expose that method! 
Also a "gui_focus_lost" signal could be useful in Viewport, since the gui_focus_changed(Control) does not emit NULL when focus is lost. 
I am making a node that needs to know the focus owner, but doesn't have access to Control nodes.

**Comment by markdibarry** [comment]
It looks like this was implemented in
https://github.com/godotengine/godot/pull/57517
and
https://github.com/godotengine/godot/pull/92573.
So feel free to close.
