### ISSUE TITLE
Theora libs VideoPlayer, serious speed issues

### ISSUE THREAD

**Issue by GovanifY** [godotengine/godot#3004]
Theora library for loading ogv and ogm on custom builds with theora activated have freaking serious speed issues, which you can see right here:
https://youtu.be/PFc3J457CjY

VLC isn't really fast on this computer because of SimpleScreenRecorder, but video playing on godot without SimpleScreenRecorder is really odd: at first the video plays fine then begins to have some issues to keep up the rythm at the end, tried out with 2 videos manually converted from wmv to ogv which runs just fine with VLC.

Just thougt it'd be cool to write out at least an issue on it, since video playing is, for in-game cinematics, something you can't, most of the time, avoid, and so a big feature that should come up with Godot 2.0 at release time.

**Comment by Calinou** [comment]
Better implement VP8/VP9 playback, Theora is considered mostly obsolete by now. The CPU usage is low enough to do it, at least on desktop platforms.

**Comment by GovanifY** [comment]
Yeah, should be better while consuming as much thougt it'd require a complete rewrite I bet so better for now fix Theora and then talk about VP8/9 on another issue

**Comment by reduz** [comment]
have any reference game engine that is under MIT license that implements
VP8/VP9? there is not even an example muxer for other people to use

**Comment by reduz** [comment]
i think it's fixed please give it a test

**Comment by GovanifY** [comment]
Yup, works flawlessly, thanks!
