### ISSUE TITLE
GDScript indention syntax mixed in the C# script as I indent

### ISSUE THREAD

**Issue by Kramchay-Dig** [godotengine/godot#30054]
**Godot version: Godot_v3.1.1-stable_mono_win64**

**OS/device including version: ALL**

**I'm not sure if the indention symbol is part of the version of Godot mono C# but C# never used an indention syntax and it's not very used for someone to see that symbol so I ask I want to know if this is normal
![Untitled](https://user-images.githubusercontent.com/27763628/60062322-5495c480-972b-11e9-89f8-43454ed0b14c.png)
**
I want that indention symbol syntax that is mixed with the C# code to disappear if it shouldn't be there because this is a C# code and not a GDScript code. If it's mixed, I want to know why is that because I don't know yet.

**Comment by Faless** [comment]
That is not a GDScript related symbol, is just a symbol used to differentiate between tabs and space.
You can disable it in `Editor -> Editor Settings -> Text Editor -> Draw Tabs`
