### ISSUE TITLE
Make the animationPlayer have groups for the animations.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#30051]
Hi, I wanna say today that it would be nice if the animationPlayer had a way to group their animations, maybe in groups like Movements, attacks, magics, or other labels.

Maybe You could even add a button to add a certain frame properties to all the other animations on the same group.
Maybe also a way to copy paste the same propertie frame to all the other animations inside the animationPlayer.

Thanks for reading me.

**Comment by golddotasksquestions** [comment]
I have about 80 animations so far and it gets really hard to find what I need to work with in this endless vertical list that goes beyond my screen.

**Comment by Calinou** [comment]
I suppose you could name your animations to have common prefixes, like `move_right`, `move_left`, `attack_melee` and so on.

**Comment by golddotasksquestions** [comment]
> Since the list of animations is sorted by name, I suppose you could name your animations to have common prefixes, like move_right, move_left, attack_melee and so on.

Yes, this is exactly what I do. It's still an enormous long vertical list in a single column. Depending on my screen resolution and UI size, a lot of it is hidden. Moving between animations is cumbersome. If you are making more than a jam game, this list can get very long very quickly. 
I suppose one way to solve this would be to have multible AnimationPlayer nodes for different groups of animations, but I feel like this might open up another can of worms.

**Comment by Calinou** [comment]
@golddotasksquestions Maybe you could design a mockup for an animation menu that handles small and large numbers of animations well :slightly_smiling_face:

**Comment by jo-onis** [comment]
Is anyone working on this or any similar feature?
Or does someone know another good way to handle a large amount of animations?

I ran into the same problem, the list of animations for the player character is getting very long. 
It's a 2D top-down game, so I need to have a separate animation for each direction the player can move towards. And several different attack and movement type animations on top of that ^^;

It would be great as suggested to simply be able to put a group/label on each animation and then choose which group to display,

**Comment by Calinou** [comment]
> Is anyone working on this or any similar feature?

As far as I know, nobody has started working on this feature yet.

Anyway, I'll close this issue in favor of https://github.com/godotengine/godot-proposals/issues/51, as feature proposals are now tracked on the Godot proposals repository.
