### ISSUE TITLE
Camera2D Anchor Mode; allow changing anchor to different positions.

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#30057]
Right now there are only two anchor option, Fixed topleft and DragCenter.  I was hoping to be able to change the anchor to a custom position, in this case the bottom center, so I could rotate the camera around a circle.

Is it possible to do this at the moment? If not, is it possible for it to be implemented?

**Comment by KoBeWi** [comment]
Current anchor modes are enough for all cases. If you want more control, you can make the camera a child of Node2D and change its position to give it any pivot or behavior you want.

If you feel like it's not enough, fill a proposal at the [official Godot proposals repository](https://github.com/godotengine/godot-proposals). All feature proposals are now moved there.
