### ISSUE TITLE
Can't load scene after saving shader code with infinite loop

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30066]
**Godot version:**
3.1.1

**OS/device including version:**
mac10.14.4

**Issue description:**
write some shader code and save. the godot software stack ~

[crash when save](https://github.com/godotengine/godot/files/3324963/log.txt)

I restart my mbp. Then test_galaxy.tscn can't be open again (stack when open)

[crash when open scene](https://github.com/godotengine/godot/files/3324972/crash2.txt)

[test_galaxy.tscn.txt](https://github.com/godotengine/godot/files/3324983/test_galaxy.tscn.txt)

I saw the code write wrong loop. But it can't be open when do that.

**Comment by Anutrix** [comment]
Exception backtrace?

**Comment by KoBeWi** [comment]
Opening the scene crashes the whole editor without any error. Normally when scene is invalid, it should say that it can't be parsed.

**Comment by Faless** [comment]
I think the **infinite loop** in the shader code might be responsible.
```
        for(int i=3;i>=0;i++){

        }
```

In fact, it does not crash for me, but freezes completely. I guess it depends on OS/drivers.

**Comment by zszen** [comment]
> I think the **infinite loop** in the shader code might be responsible.
> 
> ```
>         for(int i=3;i>=0;i++){
> 
>         }
> ```
> 
> In fact, it does not crash for me, but freezes completely. I guess it depends on OS/drivers.

Yes. It happened there. It should forbid occur

**Comment by akien-mga** [comment]
Related to #1587. Detecting infinite loops is not trivial, and probably even harder in shader code.

**Comment by KoBeWi** [comment]
The scene loads and saves fine in 3.2.3
