### ISSUE TITLE
Add Esperanto to the list of available languages for the documentation?

### ISSUE THREAD

**Issue by AlexHoratio** [godotengine/godot#30070]
Sorry if this isn't the right place for this^^, I was wondering if anybody here had considered adding Esperanto as a [supported language for translation](https://hosted.weblate.org/projects/godot-engine/godot-docs/). I'll admit it isn't a very popular language, but I feel there's *some* overlap with Esperanto speakers and the FOSS community- maybe enough to justify it?

Any discussion appreciated :D

**Comment by akien-mga** [comment]
Sure, you can add the translation yourself if you intend to contribute to it:
![Screenshot_20190625_145909](https://user-images.githubusercontent.com/4701338/60100333-d1d82e00-9759-11e9-9eb2-6eb01901c8c2.png)

But I'd focus on contributing to the editor translations first maybe: https://hosted.weblate.org/projects/godot-engine/godot/eo/
Translating the docs is a tremendous amount of work.

**Comment by akien-mga** [comment]
(BTW issues about the documentation website should go to https://github.com/godotengine/godot-docs :))

**Comment by AlexHoratio** [comment]
Ooh, right. I'll take a look at the editor translations, I didn't even realize that existed. Thanks so much :D
