### ISSUE TITLE
VisualServer.shader_get_code() returns nothing

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#30073]
**Godot version:**
v3.1.1 stable
v3.2.dev.custom_build.c93bea312

**OS/device including version:**
Win10/64
Linux
GLES3

**Issue description:**

I want to dump the shader code for a material but get nothing back from shader_get_code(). Is my gdscript wrong?

GDScript:
```
    sphere = get_node("Sphere-spatial")
    print ("Node: ", sphere.name)
    mat = sphere.get_surface_material(0)
    print ("Resource name: ", mat.resource_name)
    print ("RID: ", mat.get_rid().get_id())
    print ("VS shader_get_param_list: ", VisualServer.shader_get_param_list( mat.get_rid() ) )
    print ("VS shader_get_code: ", VisualServer.shader_get_code( mat.get_rid() ) )
```
Output:
```
Node: Sphere-spatial
Resource name: red_noise
RID: 153
ERROR: RID_Owner<struct RasterizerStorageGLES3::Shader>::get: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: C:\Dev\GD\godot\core/rid.h:154
ERROR: RasterizerStorageGLES3::shader_get_param_list: Condition ' !shader ' is true.
   At: drivers\gles3\rasterizer_storage_gles3.cpp:2202
VS shader_get_param_list: []
ERROR: RID_Owner<struct RasterizerStorageGLES3::Shader>::get: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: C:\Dev\GD\godot\core/rid.h:154
ERROR: RasterizerStorageGLES3::shader_get_code: Condition ' !shader ' is true. returned: String()
   At: drivers\gles3\rasterizer_storage_gles3.cpp:2050
VS shader_get_code:
```

I get the same thing regardless of if I use a SpatialMaterial or ShaderMaterial. When I debug in MSVC I can see `scene/resources/material.cpp SpatialMaterial::_update_shader() ` pass the shader with RID 153 to the VisualServer without error. But a few calls later, requesting RID 153 from the VS results in this failing:
```
const Shader *shader = shader_owner.get(p_shader);
ERR_FAIL_COND_V(!shader, String());
```

**Sample project**
[get-shader.zip](https://github.com/godotengine/godot/files/3325562/get-shader.zip)

(edit: Cut out feature request as it already exists.)

**Comment by Anutrix** [comment]
I advice you to make a separate issue for the side request. Do check if there's already a related issue before creating the new issue though.

**Comment by tinmanjuggernaut** [comment]
Ah, looks like the feature already exists to convert a material to shader code. With that, this issue is kind of moot. The provided VisualServer function still doesn't work right (or I'm using it wrong), but there exists an easier work around to provide what I wanted.

Reference #10242

**Comment by clayjohn** [comment]
Two mistakes here:

1. ``VisualServer.get_code()`` takes a shader RID, not a material RID So your code should be ``VisualServer.shader_get_code( mat.shader.get_rid() )``

2. You shouldn't mix ``VisualServer`` functions with nodes. If you want to retrieve a shader's code you should use ``get_code()`` e.g. ``mat.shader.get_code()``
