### ISSUE TITLE
My second game project offen stack when quit

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30075]
**Godot version:**
3.1.1

**OS/device including version:**
macos 10.14.4

**Issue description:**
almost quit freezing with stack. I need force quit twice it always.

**Steps to reproduce:**
edit game a while and quit it.

**Minimal reproduction project:**
[stack_when_quit.log](https://github.com/godotengine/godot/files/3327076/crash_when_quit.log)

[stack_when_quit2.log](https://github.com/godotengine/godot/files/3329710/crash_when_quit2.log)

[stack_when_quit3.log](https://github.com/godotengine/godot/files/3336650/stack_when_quit3.log)

**Comment by KoBeWi** [comment]
@zszen Does it still happen in 3.2.2?

**Comment by akien-mga** [comment]
No answer and no reproduction project, so closing.
