### ISSUE TITLE
Help Search uses case sensitive filter without showing the related icon as toggled

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30071]
I'm not sure if you are aware but there seems to be an issue with the latest master. Help search doesn't seem to be working properly, at least not for variable types. 
Screenshot of Godot Engine v3.2.dev.custom_build.4b0bdb4c7:
![godot-search-issue-dev](https://user-images.githubusercontent.com/1850856/60100260-094ad880-9762-11e9-8dd5-8d980c5be569.png)
Screenshot of 3.1:
![godot-search-issue](https://user-images.githubusercontent.com/1850856/60100273-136cd700-9762-11e9-9b26-39a1aab7d2b6.png)

The search help of the dev build won't even display the string variable type in the list (even when i scroll down its not there).

**Comment by akien-mga** [comment]
It's working fine for me on Linux, debug build of 93a67dba:
![Screenshot_20190625_150323](https://user-images.githubusercontent.com/4701338/60100616-66429080-975a-11e9-957a-0d45f1e6fe5a.png)

Your results look like the "case sensitive" mode ("Aa" icon) is enabled, though the icon doesn't show it. Maybe the bool is uninitialized and happens to be true in your case.

**Comment by akien-mga** [comment]
The `search_flags` bool in `EditorHelpSearch::Runner` seems properly initialized, so I'm not sure why it would mistakenly enable case sensitive checks.

**Comment by zaksnet** [comment]
Nope, if i enable case sensitive there are not results at all when i write String for example:
![Screenshot_1](https://user-images.githubusercontent.com/1850856/60101873-351b8d80-9765-11e9-8dd8-124ba7f73609.png)
I even did a clean rebuild of the master to make sure its not something i messed up with.

**Comment by zaksnet** [comment]
I think its related to the editor feature profiles:
![Screenshot_2](https://user-images.githubusercontent.com/1850856/60102053-a1968c80-9765-11e9-9144-55722933f95c.png)
But i have everything enabled in there.

**Comment by zaksnet** [comment]
Yeah thats it. After unsetting the profile it works.

**Comment by YeldhamDev** [comment]
Appears to be a regression from my commit related to that (#29565). I will see how to fix it later today.
