### ISSUE TITLE
Javascript, Android, IPhone, OSX, etc... not present in platform

### ISSUE THREAD

**Issue by GovanifY** [godotengine/godot#3008]
I don't know is this is a regression or a temporary bug but when launching scons on the latest fork of godot nor of the Javascript, Android, IPhone or OSX platforms are present in the platform option(only windows, server, x11 and haiku).
I don't know if I misreaded something on the doc or anything else but it kinda seems weird that those doesn't show up b\c imo OSX and Android are kind of a big deal, so I just opened up the issue.

**Comment by romulox-x** [comment]
What platform are you on?  Did they show up before, and a recent commit broke things?

**Comment by GovanifY** [comment]
I'm on x11, Ubuntu-based distro. I actually just forked up and it didn't showed up, didn't checked older commits.

**Comment by akien-mga** [comment]
It's normal that they don't show up, they only do if you can actually build them. But you likely have no build environment setup for javascript, android, iphone or OSX, so they're not listed. It's not a regression, it has always been like that :)

**Comment by GovanifY** [comment]
Well the environnement for osx was setted up(using osx cross)before relaunching scons when I actually made this issue so...

**Comment by akien-mga** [comment]
Then probably not setup properly for the buildsystem. Check: https://github.com/godotengine/godot/blob/master/platform/osx/detect.py#L12
For osxcross you need to define a specific environment variable it seems.

**Comment by GovanifY** [comment]
Forget that, it was setted up correctly, just had to relaunch the terminal ^^"
