### ISSUE TITLE
About launch the app.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30083]
**Godot version:**
3.1.1

**OS/device including version:**
mac10.14.4

**Issue description:**
1. almost the app launch with create a new app in the dock.
![](https://user-images.githubusercontent.com/1890538/60351497-7bd4e600-99f8-11e9-9ad4-03e3bb8077ea.png)
2. sometimes the app icon will be change with game icon.(rarely, but I saw yesterday. I restart the Godot. It can't be change any more.)
![](https://user-images.githubusercontent.com/1890538/60351440-6364cb80-99f8-11e9-9f24-372c80cfc7f5.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
@zszen Does it still happen in 3.2.2?

**Comment by KoBeWi** [comment]
Closing. Please comment if you can still reproduce in 4.4+
