### ISSUE TITLE
how to set target path  of other scene for interpolatedcamera?

### ISSUE THREAD

**Issue by twegg** [godotengine/godot#30080]
**Godot version:3.11**

**OS/device including version:windows10**

Other scenes have no choice as targets.
How can you do this?

I attached a script to interpolatedcamera

```
extends InterpolatedCamera

var scene = load("res://0_practice_folder/singleton/ins.tscn")
var ins
var path
# Called when the node enters the scene tree for the first time.
func _ready():
	ins = scene.instance()
	path  = ins.get_node("p3d")
	self.set_target_path(path)
```
But is this not correct?
How do you target other scenes?

**Comment by groud** [comment]
Sorry but this is not the place to ask about how to use the engine, but to report bugs and ask for new engine features. Please use the [other community channels](https://godotengine.org/community) for this purpose .

**Comment by twegg** [comment]
I was misunderstood. I'm sorry.
