### ISSUE TITLE
Godot freezes randomly

### ISSUE THREAD

**Issue by MarkuBu** [godotengine/godot#30093]
**Godot version:**
Godot v3.1.1 64 Bit Mono for Linux

**OS/device including version:**
Ubuntu 18.04 64 Bit, Nvidia GTX750, nvidia-driver-390

**Issue description:**
Godot editor freezes randomly for a few minutes. First time I was just reading a script, then I just edit a material. After a few minutes I can continue

**Steps to reproduce:**
Can't reproduce this. Happens randomly

**Minimal reproduction project:**
It doesn't seem to be project related, because it happens in different projects, but I get some error messages at the console

```
Failed method: LineEdit:_update_callback target ID: 221444
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: ToolButton:_update_callback target ID: 8204
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: ToolButton:_update_minimum_size target ID: 8204
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorPropertyVector3:_update_callback target ID: 221428
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorSpinSlider:_update_callback target ID: 221442
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: LineEdit:show_modal target ID: 221444
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: LineEdit:grab_focus target ID: 221444
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: LineEdit:select_all target ID: 221444
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
```

**Comment by Zireael07** [comment]
Did you try doing what it suggests?

**Comment by KoBeWi** [comment]
Is it maybe the same issue as this? #17693

**Comment by MarkuBu** [comment]
> Did you try doing what it suggests?
I didn't compile from source. I just downloaded it from https://godotengine.org/download/linux

I don't expect any memory issues in a more or less empty project with just one plane and one material

**Comment by Zireael07** [comment]
It tells you to change a value in project settings. Unless it freezes immediately upon opening the editor, you can edit them easily, no need to compile ;)

**Comment by MarkuBu** [comment]
Ah, sorry. Too hot to think today (currently about 40°C). Will try it later

**Comment by MarkuBu** [comment]
I set the value to 2048kb. Was 1024kb

But even if it is working now it shouldn't be necessary to increase this value for such a simple project. 

either the default value is too low or there is a memory leak

**Comment by StraToN** [comment]
I encounter some freezes as well, usually when entering values. When this happens, I usually hit the Control key to wake Godot up. Is this the same behaviour?

**Comment by MarkuBu** [comment]
My freezes are random and I can't reproduce them. But I haven't used Godot in the last week and reinstalled my operating system, so I don't know if anything has changed since the reinstall. My last installation was a bit older and was updated from earlier versions. So probably a bit messy.

**Comment by MarkuBu** [comment]
> Is it maybe the same issue as this? #17693

The difference between this issue and my problem is, that it also happens in projects without any script and a single primitive mesh.

Godot freezes randomly, even with one spacial node, one meshinstance with a cube as mesh primitive and one texture.

I can only wait for several minutes (and really minutes) or kill the process

**Comment by akien-mga** [comment]
Superseded by #35653.

If this still happens, you can work it around by increasing the value of the MessageQueue's max size in the project settings.

**Comment by linuxsocke** [comment]
> I encounter some freezes as well, usually when entering values. When this happens, I usually hit the Control key to wake Godot up. Is this the same behaviour?

Have the same issue and pressing Control did help
