### ISSUE TITLE
improvements to enum hint.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30098]
in 3.1.1 have Inconvenient place.
1. enum can't define variable or param. 
2. enum value can't list in hint when write code.

**Comment by williamd1k0** [comment]
>2. enum value can't list in hint when write code.

I think you're talking about autocomplete. If so, this has been fixed in #29185 and was already marked as cherry-pickable for Godot 3.1.x.

**Comment by zszen** [comment]
@williamd1k0 ;p
