### ISSUE TITLE
AutoLoad auto set NodeName after selecting a script

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3010]
Is it possible to set the Node Name to the selected name of the script?

It is most of the time the same name as the script and the previous Node Name is not removed anyway so there is nothing to lose.

**Comment by reduz** [comment]
ah, i might not have been done what you requested now that i think about it. In the case of scripts there is no node, so I guess current behavior works for both

**Comment by AlexHolly** [comment]
It works, thanks.
