### ISSUE TITLE
EditorSpinSlider for custom inspectors don't work

### ISSUE THREAD

**Issue by theboyboy** [godotengine/godot#30108]
**Godot version:** 3.1.1 Stable

**OS/device including version:** Manjaro 18.0.4 Illyria, Kernel x86_64 Linux 4.19.49-1-MANJARO

**Issue description:** When following the [inspector plugin](https://docs.godotengine.org/en/3.1/tutorials/plugins/editor/inspector_plugins.html) tutorial and trying to implement the EditorSpinSlider there are issues. It has no autocomplete, when left clicking on it while holding control it just opens a black page instead of proper documentation, and it causes a cyclic reference error when trying to preload the EditorInspectorPlugin script from the EditorPlugin. Though it has no autocomplete, when you manually write out the functions it does seem to recognize them as seen below. Additionally, when trying to use the `add_focusable()` and `set_bottom_editor()` methods, Godot does not recognize them, though this should have nothing to do with the EditorSpinSlider and I can open a separate issue for it if desired.

![image](https://user-images.githubusercontent.com/32691832/60219375-2e157d80-9840-11e9-85af-02f286ae2264.png)

**Comment by YeldhamDev** [comment]
Those docs appear incorrect, none of the `EditorProperty` pieces are exposed and I don't think this is the right way to do this. I will open an issue report in the docs repo.
