### ISSUE TITLE
Better Multiline code support for GDScript

### ISSUE THREAD

**Issue by navaronbracke** [godotengine/godot#30107]
Description:
I opened this issue to address my concerns about the current way of doing multiline code in GDScript. Sometimes you will end up with either a long chained function call(think Fluent API) or a long $ prefixed NodePath from a very big Scene. Then you want to put this on multiple lines for readability. As it stands you can tell the parser to see the following lines of code by inserting a '/' . In my opinion this reduces code readability.
Obviously the parser needs some way of knowing what is valid code and what isn't. Therefore I'd suggest expanding the parser's cababilities slightly in terms of how it reads code.

Example situations that might occur in a current codebase(forgive me if I forget anything)
- during func declaration
- inside a func body
- during (onready) var declaration

For each of these situations we could make the parser look for specific things(as it probably does now?), but over multiple lines.
1)For the func name: look for valid text between the whitespace after 'func' and the opening bracket, over multiple lines
For the parameter list we could look for either
- emty string(no arg func)
- (whitespace) argument name (whitespace) (colon + optional whitespace + argument type + optional whithespace)
- list of the item above, separated by the comma separator 
2) if parsing fails on a line, try to concat the next line and see if that is valid, but stay within the func body, when looking for a new line of code. Repeat until no lines can be concatenated anymore
3) look for (whitespace) (onready) (whitespace) var (whitespace) argument name(concat valid arg name text from multiple lines if needed) (whitespace) = (whitespace) valid assignment value (concatenated over multiple lines)

Concrete Examples of the above ('\r' signals carriage return, or new line, for clarity):
func my_very_long_name\r
_that_doesnt_fit_function(): 

func my_function( with_a_very_\r
long_argument: MyVeryLong\r
ScriptClassName ):

func do_some_chain_function():
   obj.do().some().crazy()\r
.long().function().chain().with(argument)

func why_do_i_have_long_node_paths():
 var node : Node = $Very/Long/Node/Path\r
/From/Some/GridContainer/Node

Mind you that the above is a very raw conceptual approach by myself.

This issue for now is probably just a discussion but maybe it could turn into a feature request someday

PS: I do come from static-typed languages, hence the irritated programmer :p

**Comment by girng** [comment]
that imo makes the code even less readable

**Comment by girng** [comment]
collapsible lines might help with this

**Comment by 4lph4-Ph4un** [comment]
I agree. Coming from Python, I find reading the second or third of these to be more readable:

```
# 1.
print(get_tree() \
      .get_root() \
      .get_node("Root") \
      .name)

# 2.
print(get_tree()
      .get_root()
      .get_node("Root")
      .name)

# 3.
print(get_tree().get_root()
                .get_node("Root")
                .name)
```

Currently only the first seems to work which I find funny, since otherwise encapsulating statements into brackets allows automatically breaking multilines).

**Comment by andrewvaughan** [comment]
+1

This is a jumbled, unreadable mess:

```
var cell_to_pixel = Transform2D(Vector2(tilemap.cell_size.x * tilemap.scale.x, 0), Vector2(0, tilemap.cell_size.y * tilemap.scale.y), Vector2())
```

Would prefer to see a Python style:

```
var cell_to_pixel = Transform2D(
	Vector2(tilemap.cell_size.x * tilemap.scale.x, 0),
	Vector2(0, tilemap.cell_size.y * tilemap.scale.y),
	Vector2()
)
```

I can't imagine this would be a ridiculous change to the tokenizer...

**Comment by Calinou** [comment]
@andrewvaughan The second style you mentioned should work fine already :slightly_smiling_face:

**Comment by aaronfranke** [comment]
Parts of this issue are not actually issues (such as @andrewvaughan's code example), and other parts are things that aren't going to be changed (such as most of the OP and @4lph4-Ph4un's code example, the `\` characters stay). Therefore, I'm closing this.
