### ISSUE TITLE
Bug with AnimatedSprite & AnimationPlayer.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30100]
**Godot version:**
3.1.1

**OS/device including version:**
mac 10.14

**Issue description:**
can't make curve animation for animated sprite. here has two bug.

1. Select animationplayer first, then select animatedsprite. The keyframe button don't display any more. After that always don't show key frame button with other nodes. (AnimatedSprite it self can't be set animation. And it stop other nodes do that.)

2. AnimatedSprite is not never be animation. It can to it only with manual keyframe control.

**Comment by kubecz3k** [comment]
About point 1. 
I was unable to reproduce with Godot 3.1.1 on Ubuntu 18.04:
![AnimationOnAnimatedSprite](https://user-images.githubusercontent.com/6129594/60258072-ae85be00-98d4-11e9-97e8-67f26e939f24.gif)
Did I misunderstood the reproduction steps?

About point 2.
When you define an animation you should be able to play it in runtime with `play("animation name")` method of `AnimatedSprite`

**Comment by zszen** [comment]
> About point 1.
> I was unable to reproduce with Godot 3.1.1 on Ubuntu 18.04:
> ![AnimationOnAnimatedSprite](https://user-images.githubusercontent.com/6129594/60258072-ae85be00-98d4-11e9-97e8-67f26e939f24.gif)
> Did I misunderstood the reproduction steps?
> 
> About point 2.
> When you define an animation you should be able to play it in runtime with `play("animation name")` method of `AnimatedSprite`

Your animatedSpirte's frames is empty. You can try with not empty frames for this.

**Comment by dankan1890** [comment]
When you select AnimatedSprite the SpriteFrames panel is opened by default, that's why the key icons no longer appear, you need to select the Animation panel at the bottom.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment]
I guess not.
