### ISSUE TITLE
Needlessly repeated texts in VisualShader translations

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#30111]
**Godot version:**
3.1.1

**Issue description:**
While translating on Weblate, I encountered a streak of same-looking texts, which differed only in an untranslatable string. The texts are e.g.:
`'uv' input parameter for all shader modes.`

My point is, in above text the "uv" will probably stay the same in all languages, as I assume it's a constant name. There are 10 texts like this and they could be simply:
`'%s' input parameter for all shader modes.`

Later there's also
`'%s' input parameter for vertex and fragment shader modes.`
`'%s' input parameter for fragment and light shader modes.`
and few more similar groups. Using a format instead would result in much less texts to translate, because it's pointless to keep them as separate strings.

**Comment by akien-mga** [comment]
This can be fixed by using:
`vformat(TTR("'%s' input parameter for all shader modes."), "uv");` and so on for all other occurrences.

**Comment by Chaosus** [comment]
Yeah, good idea, at that time I'm maked them I didnt knew about that method (otherwise they already been correct)

**Comment by hbina** [comment]
I would like to work on this, as a way to learn how it works.
So if I understood this correctly, i have to remove texts like this (leaving only one of them?)

https://github.com/godotengine/godot/blob/6e03236574467d6a0c3aca1b0375da59423b0083/editor/translations/af.po#L8231-L8233

from the translation files.
Then replace something like `TTR("'camera' input parameter for all shader modes.")` with what @akien-mga said above?

**Comment by akien-mga** [comment]
You don't need to change translation files, only the `TTR` statements. The .pot and .po files are updated by a script.

**Comment by hbina** [comment]
Which script is it?

**Comment by akien-mga** [comment]
> Edit: is it extract.py in the same folder they are located?

Yes, but you don't need to run it, I do that when syncing docs.

**Comment by KoBeWi** [comment]
Actually syncing would be useful for this particular PR.
