### ISSUE TITLE
define BACK_TO_TABLES in aes256.cpp?

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#3012]
Is there a reason the line
#define BACK_TO_TABLES
is commented out at the top of core/io/aes256.cpp?  From what I can gather, the current code skips the use of lookup tables, and instead calculates the needed data on the fly.  In my roughly measured experiments where I enabled encryption of my scripts, this gives me load times 3-4 times longer than the unencrypted scripts.  If I uncomment this line, so that it uses the lookup tables, I can no longer distinguish between the encrypted and unencrypted load times, which is great.  But I wonder if this is too good to be true, and using the lookup tables is a bad choice for some reason.  I was able to export my scripts encrypted using a slow, non-lookup table built binary, then load that data using the fast lookup table version, so it seems they both work correctly.

Shall I make a PR for this, enabling the lookup tables?  Does anyone know enough about this to comment on whether this is a good idea?  I should be able to do this through scons build scripts myself, but if this is an acceptable change, I see no reason to keep doing it the slow way by default.

**Comment by akien-mga** [comment]
It seems it was imported like that: 162d2ebe
So it might be worth checking upstream if there are some explanations about this.

**Comment by romulox-x** [comment]
I just checked on the site provided in the source file:
http://www.literatecode.com/aes256
He posted a new version of the file.  Maybe we should update to that?  He says the decryption is faster.  He mentions that the updated code provides a way to choose between dynamic or precomputed tables, which seems to be done in this code with the BACK_TO_TABLES flag as well.  I'm a bit confused by the timeline of file changes he's talking about (since this new file supposedly introduced this flag), but the bottom line I'm getting from this is that the BACK_TO_TABLES flag is indeed intended for exactly this.  He even says on that page that the dynamic version is slower, but it was what he needed.  So even if we don't upgrade the whole file, using this flag looks pretty safe to me.

**Comment by akien-mga** [comment]
I'd say feel free to make a PR using the new upstream code (just try maybe to see first if the file we are using is a clean copy of the upstream code, or if @reduz had modified it prior to committing).

**Comment by reduz** [comment]
if it's faster feel free to do a PR and merge it

**Comment by eska014** [comment]
Resolved by #3022
