### ISSUE TITLE
A few of source files still don't use the FALLTHROUGH macro

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#30122]
**Godot version:**

Latest master https://github.com/godotengine/godot/commit/2df8b5606b9de9d11873c27f0a297127bbbfc255.

**OS/device including version:**

All.

**Issue description:**

A few of the source codes still don't use  FALLTHROUGH macro. Some were left in #27677.
Not sure if this is duplicate of #29801. It would be nice if some made a list of it so it could be fixed at once. Some data:

These needs changes to use the macro:

- core/packed_data_container.cpp:227: }; //fallthrough
- core/ustring.cpp:2134: // let it fallthrough
- editor/plugins/sprite_frames_editor_plugin.cpp:235:             } // Fallthrough.
- editor/plugins/tile_map_editor_plugin.cpp:65: } // fallthrough
- modules/gdscript/gdscript_editor.cpp:2501:              } // fallthrough
- modules/gdscript/gdscript_editor.cpp:2540:              } // fallthrough
- modules/gdscript/gdscript_editor.cpp:3237:              } // fallthrough
- modules/gdscript/gdscript_editor.cpp:3368:              } // fallthrough
- platform/windows/os_windows.cpp:847: } //fallthrough
- scene/resources/particles_material.cpp:187: } //fallthrough
- thirdparty/libpng/pngerror.c:166:            /* FALLTHROUGH */
- thirdparty/libpng/pngerror.c:176:            /* FALLTHROUGH */
- thirdparty/libpng/pngread.c:1983:               /* FALLTHROUGH */
- thirdparty/libpng/pngread.c:2005:               /* FALLTHROUGH */
- thirdparty/libpng/pngread.c:2034:               /* FALLTHROUGH */
- thirdparty/libpng/pngread.c:2043:               /* FALLTHROUGH */
- thirdparty/libpng/pngread.c:2963:         /* FALLTHROUGH */
- thirdparty/libpng/pngrtran.c:63:         /* FALLTHROUGH */
- thirdparty/misc/stb_truetype.h:2093:         // fallthrough

These comments seem wierd because the switch cases there have both continue; and break; statements:

- modules/gdscript/gdscript_parser.cpp:4523:                              //may be fallthrough from export, ignore if so
- modules/gdscript/gdscript_parser.cpp:4534:                              //may be fallthrough from export, ignore if so
- modules/gdscript/gdscript_parser.cpp:4554:                              //may be fallthrough from export, ignore if so
- modules/gdscript/gdscript_parser.cpp:4579:                              //may be fallthrough from export, ignore if so
- modules/gdscript/gdscript_parser.cpp:4600:                              //may be fallthrough from export, ignore if so
- modules/gdscript/gdscript_parser.cpp:4615:                              //may be fallthrough from export, ignore if so
- modules/gdscript/gdscript_parser.cpp:4630:                              //may be fallthrough from export, ignore if so

These don't need changes because they are empty cases:

- modules/gridmap/grid_map_editor_plugin.cpp:238:         case MENU_OPTION_SELECTION_DUPLICATE: // fallthrough
- scene/gui/slider.cpp:159:               case NOTIFICATION_VISIBILITY_CHANGED: // fallthrough
- thirdparty/libpng/pngrtran.c:1270:               /* FALLTHROUGH */ /*  (Already 8 bits) */

Not sure because there doesn't seem to be switch here:

- thirdparty/libwebp/src/dsp/lossless_enc_neon.c:124:  // fallthrough and finish off with plain-C
- thirdparty/libwebp/src/dsp/lossless_enc_neon.c:68:  // fallthrough and finish off with plain-C
- thirdparty/libwebp/src/dsp/lossless_enc_sse2.c:40:  // fallthrough and finish off with plain-C
- thirdparty/libwebp/src/dsp/lossless_enc_sse2.c:74:  // fallthrough and finish off with plain-C
- thirdparty/libwebp/src/dsp/lossless_enc_sse41.c:38:  // fallthrough and finish off with plain-C
- thirdparty/libwebp/src/dsp/lossless_neon.c:537:  // fallthrough and finish off with plain-C
- thirdparty/libwebp/src/dsp/lossless_sse2.c:442:  // fallthrough and finish off with plain-C

I got these from greping those 3 patterns below. There might be more.
I manually checked each of the lines and grouped them above.
greping without -i reduces false-positives sometimes.

**Steps to reproduce:**
Search for fallthrough in all source files. Recursive grep should work.
`grep -rni "//fallthrough"`
`grep -rn "/* fallthrough"`
`grep -rni "/* fallthrough"`

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Fixed by #30177.

Code in `thirdparty/` should not be changed.
