### ISSUE TITLE
Improments to Scene Labels

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30139]
godot 3.1.1 mac 10.14

Here need add function "close all scene" and "close others scene" function.

![image](https://user-images.githubusercontent.com/1890538/60297655-46c68600-995b-11e9-9b3a-fae21bd8ba89.png)

**Comment by qarmin** [comment]
This options are added in 3.2 master
![Zrzut ekranu z 2019-06-27 23-07-16](https://user-images.githubusercontent.com/41945903/60300940-6d22fc00-9930-11e9-8379-17622ba42214.png)

**Comment by zszen** [comment]
great!
