### ISSUE TITLE
transparent light occluder

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#3013]
Is it possible, to set up kind of transparent light occluder?
Like every occluder consumes a given percentage of light and maybe changes the color.

With this I'd like to realise things like transparent objects (leaves, glass...) or in a tilemap make the light gone after 4 tiles or something to reduce the vision.

I think, that would feel a natural way to achieve those effects.

**Comment by reduz** [comment]
most likely for 3.0 with the new renderer

**Comment by reduz** [comment]
i thought this was about softshadows, which work now for 3D.. but it's impossible to do per occluder, as occluders store depth only... so closing this, sorry :(
