### ISSUE TITLE
Helper for controlling anchors of Control node can't be off

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#30132]
**Godot version:**

3.2.dev 755b58938

**OS/device including version:**

Kubuntu 19.04

**Issue description:**

Helper for controlling anger of Control node can't be off

**Steps to reproduce:**
try to off helper
![helper](https://user-images.githubusercontent.com/8281454/60292859-0e25ad00-9959-11e9-947c-5f3d5c4c3d4f.gif)

**Minimal reproduction project:**

**Comment by groud** [comment]
Yeah I changed that on purpose as it was confusing for users. 
Do you think it deserves a dedicated checkbox ? I mean, for me anchors are as important as drag handles for control nodes, so I am not sure it should be allowed to disable their display.

**Comment by akien-mga** [comment]
![anger control](https://media.giphy.com/media/3otPoHUNSFWviCyboQ/giphy.gif)

Sorry, had to :P

**Comment by volzhs** [comment]
@groud it was coming from this.
I was trying to resize the control but the anchor is grabbed...
![anchor](https://user-images.githubusercontent.com/8281454/60305297-1096ff80-9977-11e9-85a9-1a4cd350e6b3.gif)

**Comment by groud** [comment]
@volzhs ah indeed this is more annoying. But it could be solved by charging the anchor input priority

**Comment by volzhs** [comment]
that is enough for me i think
