### ISSUE TITLE
UNUSED_CLASS_VARIABLE warning - except it's used and removing it crashes everything

### ISSUE THREAD

**Issue by PabloNeirotti** [godotengine/godot#30143]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
iMac (Retina 5K, 27-inch, 2017)
macOS Mojave (10.14.5)

**Issue description:**
So I import a file that defines "mods" via `class` definitions. Via this line of code:
```
onready var Mods = load("res://Services/Mods.gd")
```

This line gets the warning `UNUSED_CLASS_VARIABLE: The class variable 'Mods' is declared but never used in the script.`

Except that it's used below in the same file:

```
onready var all_sentry_mods = [
	Mods.ModOption.new("Capacitor", Mods.CapacitorMod, 6, 'Damage +++   Fire rate --'),
	# ...
]
```

But if I was to remove the variable, the game would crash before it can start, stating:

```
Parse Error: Identifier not found: Mods
```

... pointing at that `Mods.ModOption.new(...)` line.

Can someone clarify what's going on, or if it's an actual issue?

Thank you!

**Comment by bojidar-bg** [comment]
Sounds potentially related to #29406, though that was fixed. Can you retest on a recent nightly version?

**Comment by PabloNeirotti** [comment]
> Sounds potentially related to #29406, though that was fixed. Can you retest on a recent nightly version?

Sure thing. I looked around in the GitHub Releases tab but I couldn't find any nightly release. Where could I get it?

**Comment by bojidar-bg** [comment]
You could try [Calinou's builds](https://hugo.pro/projects/godot-builds/).

**Comment by PabloNeirotti** [comment]
Just tried and it would seem the warning is gone in the nightly build. Thanks!
