### ISSUE TITLE
Editor console suggestion.

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30150]
From what i understand the editor is running on top of the engine itself. Therefore it would be nice if there was a console (pretty much like cmd) where you can invoke commands from the loaded Singletons. For example:
`OS.get_real_window_size()` (Or any other OS method in this case)
It would be timesaving if we could invoke this method and get back the result without the need to run the game itself and print the results to the console.

PS: I'm probably going to build this myself but just in case there is something out there already.

**Comment by bojidar-bg** [comment]
I'm pretty sure there was an issue about that in the past, but I cannot find it.

Anyway, I think this is doable using an EditorPlugin.

**Comment by akien-mga** [comment]
This can be done as a plugin in GDScript.

But note that the value you'd get would be for the editor window, not the game window (since it's not running).
