### ISSUE TITLE
PinJoint2D: Problem with collision of connected bodies

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#3015]
When I connect a RigidBody to a static one by a PinJoint2D, they won't collide.
Further Rigidbodies added to that chain will collide with the static as expected.

![pinjoint2d_error_demo](https://cloud.githubusercontent.com/assets/16130334/11649904/445f329e-9d84-11e5-851d-9c60dd274d7f.png)

**Comment by reduz** [comment]
i think this is on purpose, but it should be optional

**Comment by nopeson** [comment]
Had that thought too, that directly connected bodies will not collide per default. But yes, it would be very nice, if it would be optional.

**Comment by nopeson** [comment]
Wow, that fast :O! thank you so much! :)
