### ISSUE TITLE
Add ability for Font Drop Shadow to account for Outline thickness

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30165]
Feature request:

Right now the drop shadow of a font does not account for any outline properties set. This makes using both at the same time jarring, as the drop shadow will be a different shape from the font itself. Especially noticeable with thick or cursive fonts where the outline drastically warps the silhouette.

Perhaps it could be added as a toggle?

**Comment by Calinou** [comment]
> Perhaps it could be added as a toggle?

I'm not sure if there are any real use cases to have a drop shadow that doesn't match the "visible" font shape (which includes the outline), so we might as well always do it whenever a font outline is used.
