### ISSUE TITLE
Large shaders difficult to edit because of live recompile interruptions

### ISSUE THREAD

**Issue by loganjk** [godotengine/godot#30164]
**Godot version:**
3.1.1 win64 (Classical)

**OS/device including version:**
Windows 10 Pro, Intel i7-4790K, integrated GPU only (Intel HD Graphics 4600), driver igdkmd64.sys version 20.19.15.5058

**Issue description:**

With a GLES2 fragment shader of about 2,000 lines, I find the interruptions due to live recompile (and parsing?) to be annoying.  I would prefer to have an option to turn off this behavior so I can recompile/parse only when desired and otherwise have the editor window behave like a simple text editor.  I looked in the editor and project settings, but could not find a way to do this or at least greatly increase the delay before recompile/parsing to permit longer pauses in typing.

The problem is not only that there the editor window freezes, but that sometimes keystrokes I made after the freeze began, before I noticed the freeze, are not remembered by the editor and are lost, leading to typos if I am not careful.

I realize that most shaders are probably small enough that this is not a problem, but it would be a great "quality of life" improvement for me.  An alternative is to use a separate editor and copy/paste when I want into Godot's editor window, but I'd prefer to do everything in Godot if possible.

Thanks for considering.

**Comment by Zireael07** [comment]
With a large shader, even moving around in shader editor (by arrow keys or mouse) gets laggy.

**Comment by Calinou** [comment]
> I looked in the editor and project settings, but could not find a way to do this or at least greatly increase the delay before recompile/parsing to permit longer pauses in typing.

You can increase **Text Editor → Completion → Idle Parse Delay** in the Editor Settings. Note that this affects both the script editor and shader editor, and will cause error reporting to take longer to appear.

**Comment by loganjk** [comment]
I changed Idle Parse Delay before and it had no effect, but it seems that's because I did not restart the editor afterwards!  Thanks very much, problem solved.
