### ISSUE TITLE
AREA_SPACE_OVERRIDE_COMBINE only combines gravity

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#3016]
When areas overlap, and the top one uses AREA_SPACE_OVERRIDE_COMBINE, only the gravity gets combined. The linear/angular dampenings are replaced.

Is this correct behavior?

**Comment by reduz** [comment]
not sure, probably should be combined too i guess

**Comment by reduz** [comment]
you did a PR and i merged it, so i'm closing this

**Comment by Ovnuniarchos** [comment]
Nice. Now I can write the docs accordingly.
