### ISSUE TITLE
Custom Resource.changed not emitted when properties changed

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#30179]
**Godot version:** 3.1

**OS/device including version:** Windows 10

**Issue description:**

The signal is not documented at all in the [docs](https://docs.godotengine.org/en/3.1/classes/class_resource.html) so:

_Originally posted by @vnen in https://github.com/godotengine/godot/issues/16365#issuecomment-362851447_:

> The `Resource` class has a `changed` signal when any of its properties change (via Inspector or not).

Built-in `Resource`s do emit `changed` when changing properties: [GDScript Playground](https://gd.tumeo.space/KYDwLsB2AmDOAEA5A9tYAodAzArpAxvAPoBOwAhtAJ4AUAlAFzoCQAbuSfJMgJazDwAvPADyABygBlHgFsxAG1Ao+wAHSRgAd3otuK1fmSQN+MDQDk+ABblIAc2DRzAGnj95WV+aJGi12w5OdLq8-KrIpuSswAgA1MIAjJi4BMS+-vaO9EzMYiQ8kGbmyvzwAFY4sGDwGYEAhOZ0QA).

But not user-created `Resource` unless you setup a setter and emit the signal in there: [GDScript Playground](https://gd.tumeo.space/KYDwLsB2AmDOAEA5A9tYAodBjANgQ1gQGUw8xYAudASFAhgQCVhZkBXAJyw2poDc8HeNDwBbPAHNg8ALzwAjAAZ4sYGClh4AfVVgtI8VMzUAZm0hZtu-WMnAAFAJxtgASirVqBu7PhOXNNQAxMCiAJZ6sGESkHg49gDkWAAWeJBS0AmuNOhmFtocwHjQAJ727vyCKqTkviRksAB0kMAA7uU0sDVNWMiQLVhgiSlpGQkANCrAOCaTCVp9WiPpwJnZ1F0Njd5S8ABUcgBMmHmWC5BLqSvQ5R4ADhxhkEMJ9bUAVmxd8MsZAIRZIA).

**Comment by Xrayez** [comment]
Thanks, yeah this is also relevant in 3.2 master, also asked in [Q&A](https://godotengine.org/qa/47386/resource-changed-signal-default-whenever-properties-modified).

**Comment by willnationsdev** [comment]
Should this be something that is handled on the ScriptInstance level in core, or maybe on the GDScriptInstance/etc. Level in each module?

**Comment by Xrayez** [comment]
I don't see why this should be specific to GDScript since the behavior is present in core by default.

**Comment by willnationsdev** [comment]
@Xrayez

> in each module

I meant I wasn't sure if this was supposed to be handled in the setter for each language, so that the language can check if it extends Resource, or if it should be handled in the core in object.cpp's master set method. Probably the latter

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3

**Comment by Xrayez** [comment]
@KoBeWi I wonder whether it emits the signal automatically if you do `resource->set("property_name", value)` in C++, if yes then that would be still a bug.

Otherwise yeah I think I was so sure that resources *should* emit the "changed" signal, I'm just really surprised that this is not the default behavior, hence bug...

**Comment by KoBeWi** [comment]
> I wonder whether it emits the signal automatically if you do resource->set("property_name", value) in C++, if yes then that would be still a bug.

Using `set` will call the setter normally.
