### ISSUE TITLE
Converted Tileset using ViewportTexture shows up black

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#30199]
**Godot version:** 3.1

**OS/device including version:** Windows 10

**Issue description:**

I'm using `ViewportTexture` to show a 3D model as a 2D tile. When I exported it, the tile displays as a black viewport. Is it a limitation/expected behavior?

**Comment by TheDuriel** [comment]
This is expected. ViewportTexture is the live render of the viewport. No viewport. No texture. Not to mention that tilemaps are batched, so this would not work anyways.

**Comment by DleanJeans** [comment]
I just wrote this script to save the viewport's texture to a folder of choice and load it easily:

```
tool
extends Sprite

export(String, DIR) var texture_folder = 'res://' setget _set_texture_folder
export(bool) var save_texture = false setget _save_texture
export(bool) var load_texture = false setget _load_texture

var _image_path:String

func _set_texture_folder(value):
	texture_folder = value
	_image_path = texture_folder.plus_file('%s.png' % name)

func _save_texture(value):
	var image = $Viewport.get_texture().get_data()
	image.save_png(_image_path)

func _load_texture(value):
	texture = load(_image_path)
```
