### ISSUE TITLE
When the game crashes it still exits with code 0

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#30207]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Arch Linux

**Issue description:**
When a game crashes due to some error, it exits with status code 0, and there's no way to tell if it crashed or closed on purpose.

**Steps to reproduce:**
1. Create a simple script with a syntax error
2. Attach that script to an empty scene
3. Export that scene
4. Launch the exported scene

**Minimal reproduction project:**
[crashing.zip](https://github.com/godotengine/godot/files/3343128/crashing.zip)

**Comment by touilleMan** [comment]
I have a similar trouble we using Godot in a CI role: https://dev.azure.com/godot-python/godot-python/_build/results?buildId=168&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=4f7f0e14-4767-5646-3512-f2409f98e2bf&l=1157

Basically the main scene failed to load so Godot exists, but exit status is a misleading 0 :(

I think a simple solution to implement a fix on this would be to set non-zero default value for `OS.exit_code` (hence if Godot ends up with an unexpected exit we will always have a non-zero status) and only overwrite this value if `SceneTree.quit` is called (hence only a user-commanded exist is considered as a valid one). And of course `OS.set_exit_code()` should still be able to manually overwrite the exit code.
