### ISSUE TITLE
Searching for `ed` in inspector with open editor theme causes infinite loop

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30217]
**Godot version:**

3.1

**Issue description:**

When searching for `ed`tor in the inspector it causes an infinite "object was deleted while awaiting callback" loop. Effectively freezing the editor forever.

**Steps to reproduce:**
Create a theme. Copy the editor theme into it. Search for `ed`itor in the inspector.

**Comment by KoBeWi** [comment]
@TheDuriel I can't reproduce it even in 3.1.
Does it still happen in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4)?

**Comment by TheDuriel** [comment]
I've since undergone a significant hardware upgrade. But even on my i9 searching for e then d will cause significant hiccups and take a noticeable amount of time.

**Comment by KoBeWi** [comment]
That doesn't sound like infinite loop though. What about the "object was deleted while awaiting callback" error? Does it still happen? If no, this can be closed.

**Comment by TheDuriel** [comment]
It does not.

Issue can be closed until someone else with low end hardware does this test., a more optimized search
