### ISSUE TITLE
Segfault last build

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#3021]
When I try to start godot it segfault..
![segfault](https://cloud.githubusercontent.com/assets/7677575/11669956/5b621a24-9e10-11e5-8a67-510d4defd710.png)

**Comment by AlexHolly** [comment]
+1 Ubuntu

ERROR: get_driver: Index p_driver out of size (driver_count).
   At: servers/audio/audio_server_sw.cpp:1022.
ERROR: get_audio_driver_name: Condition ' !driver ' is true. returned: ""
   At: platform/x11/os_x11.cpp:95.

**Comment by ealataur** [comment]
builded with no pulseaudio but alsa

**Comment by vnen** [comment]
It runs fine when compiled PulseAudio, but does segfault when it's not enabled.

**Comment by vnen** [comment]
Fixed by 78b5404434eefce497ef9d49e25645afcda93710.
