### ISSUE TITLE
GraphEditFilter visible in code completion even though its not bound

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30216]
**Godot version:**

3.1

**Issue description:**

When declaring a variable in GDScript, you can define the type to be `GraphEditFilter` and will get code completion for it. However the class is not actually exposed to GDScript, making this rather pointless.

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/44248915/60414203-bf397b00-9bd7-11e9-99a6-6555c2d1d235.png)

**Comment by KoBeWi** [comment]
Still valid in 3.2.3, but fixed in 4.0 8016521
