### ISSUE TITLE
Abillity to open multiple animations at once

### ISSUE THREAD

**Issue by joleeee** [godotengine/godot#30227]
**Godot version:** v3.1.1.stable.official

**OS/device including version:** Linux Mint 19.1

**Issue description:**

It would be nice if you could select multiple animation files when opening animations on an AnimationPlayer using Animation -> Load.

**Comment by TheDuriel** [comment]
Bit missleading title (it suggests editing multiple at once). Yes mass loading of animations would be nice.

**Comment by joleeee** [comment]
I agree though i can't come up with a better one.

While on the topic it would be nice if you could drag and drop animation files into the animation tab as a way to import them.

**Comment by ArchangelZeero** [comment]
+1, really needed, I'm currently with 64 animation files per character (and there's 100+ characters) and needed to do an script to edit .tscn file as text to load them '-'

**Comment by golddotasksquestions** [comment]
> +1, really needed, I'm currently with 64 animation files per character (and there's 100+ characters) and needed to do an script to edit .tscn file as text to load them

I'm in the same boat. It's easy to miss something or get lost in larger .tscn files if you try to copy and paste animations via text. But currently there is no other practical option (https://github.com/godotengine/godot/issues/30197, https://github.com/godotengine/godot/issues/27280). There is also always this unsure feeling of "Did I paste them at the correct place? Did I copy all?"
It's currently a lot of back and forth and prone to error to copy and paste or transport animations from AnimationPlayer to AnimationPlayer.
