### ISSUE TITLE
Tree (Control node): Add support for more fine-grained column expansion behaviour (like stretch ratios)

### ISSUE THREAD

**Issue by Meriipu** [godotengine/godot#30233]
Trees (the Control node) currently (3.1) allow making particular columns expand when the Tree is resized. There does however not seem to be any support for setting a stretch_ratio on the individual columns, e.g. making one expanding column always be twice the width of another. 

Is this something that it makes sense adding support for, or is it easy enough to achieve through other means, that it is less useful?

Other means:
* Manually setting min-sizes and hoping stuff does not exceed them too much?
* The Tree catching resize/transform signals, dynamically updating the minwidths of columns with respect to the whole width ?
* There is actually support for stretch_ratios, it is just not documented well?

**Comment by akien-mga** [comment]
Closed by #30233.

**Comment by groud** [comment]
> Closed by #30233.

@akien-mga you self-referenced the issue here

**Comment by akien-mga** [comment]
Thanks, fixed.
