### ISSUE TITLE
Discrepancy between editor, in-game, and viewport lighting

### ISSUE THREAD

**Issue by hbgdo** [godotengine/godot#30235]
**Godot version:**
v3.1.1

**OS/device including version:**
Windows 10/GTX970

Also in Ubuntu 16.04/Intel® HD Graphics 520 (Skylake GT2) 

**Issue description:**

Firstly I noticed that in editor lighting was different (light energy seems to be lower) than in game.

editor: http://oi67.tinypic.com/11t24ax.jpg

in-game: http://oi66.tinypic.com/2vczzpc.jpg

Also in Linux:
http://oi66.tinypic.com/e8r2f7.jpg

After checking out the lighting tutorial again, I noticed that changing project settings -> Intended Usage -> Framebuffer Allocation to 3D instead of 2D returned in-game lighting to the same as the editor.

However, when implementing rendering to a viewport/2D quad on screen, this issue cannot be resolved by changing intended purpose of the viewport. In any case, the rendered quad resembles the in-game dimmer case shown above. This is fairly easy to reproduce in new projects etc, with simple lighting and sprites, although it does seem more noticeable with lights with higher energy/brightness. 

**Steps to reproduce:**

See attached simple project. 
[bug.zip](https://github.com/godotengine/godot/files/3347576/bug.zip)

**Comment by TheDuriel** [comment]
You need to correctly configure, and use the same World Environment in the editor and game viewports. This will make them match.

**Comment by hbgdo** [comment]
Thank you for taking the time to reply. Utilizing a world environment as you say does allow the viewport to match the intended scene.

However, the problem persists when not using viewports at all and launching from scene. I found that changing Framebuffer Allocation to 2D has the same effect as disabling HDR, which seems to be what is happening. I appreciate it notes that it supports less features but I have had a difficult time finding documentation on the features that are and are not supported by this setting. If this is intended behaviour, and if HDR is not supported by this setting, shouldn't we receive some kind of warning?

Secondly, it seems that, no matter the rendering settings, the editor renders with HDR. I had assumed incorrectly that the editor would match the render settings of the game relatively closely but it does not appear to. Is this intended behaviour? Is there any way to get the editor to render with the same settings?

Cheers

**Comment by KoBeWi** [comment]
Seems fixed in 4.0
![image](https://user-images.githubusercontent.com/2223172/94376209-58c44500-0119-11eb-95b1-e569b663bc7a.png)
(I mean both look the same, soo...)

**Comment by filsd** [comment]
Will this be fixed on 3.x series?
I'm having this problem on 3.2.3 Stable. :/
