### ISSUE TITLE
Large images are not importing. 

### ISSUE THREAD

**Issue by Ubiw** [godotengine/godot#30238]
**Godot version:**
Godot 3.1.1 (Steam Version)

**OS/device including version:**
**OpenGL ES 2.0 Renderer**: GeForce GTX 1060/PCIe/SSE2

**Issue description:**
Large images are registered as corrupted in godot when forcefully imported,
and just wont import at all when drag and dropped.

[log](https://pastebin.com/raw/tJV0Vefq)

**Steps to reproduce:**
1. make image size 30000x1920 (what i used)
2. try to import to godot

**Comment by eon-s** [comment]
Your textures are too big:
`core/image.cpp:1460 - Index p_width - 1=29999 out of size (MAX_WIDTH=16384)`
See https://docs.godotengine.org/en/3.1/classes/class_image.html#constants

And unlikely to run on any GLES2/WebGL1 (only) capable device since most of these do not support more than 2048x2048 (some mobile can go up to 4096).

You can try changing this
https://github.com/godotengine/godot/blob/eaaff9da3178fa515a0f051fda932c1dd04d53db/core/image.h#L59
And see if something breaks for your game if going too far from the default hardcoded limitations.

**Comment by TheDuriel** [comment]
OpenGL does not support textures beyond 16,384. Even on the best desktop hardware.

**Comment by eon-s** [comment]
Thanks @TheDuriel, I could not find the numbers anywhere, I guess that it should be clarified on the documentation entry so it does not look like an arbitrary limit.

**Comment by KoBeWi** [comment]
This might be fixed with Vulkan. It probably doesn't have the limitations of OpenGL.

**Comment by TheDuriel** [comment]
Technically the limit is several times higher in vulkan yes. But it will probably still refuse to work.

Practically you will find that very few consumer GPUs are even capable of handling textures 16k or higher for real time usage purposes. We're talking about images that easily take up 3 gigs on disk. And close to half that in vram. Just for 16k.

**Comment by Xrayez** [comment]
Rendering is not a problem as long as I can import (or rather load) the image, chop it down into chunks, and work with those as individual `ImageTexture`s that are rendered based on visibility or whatever. Besides the use cases shouldn't be limited to rendering.

**Comment by eon-s** [comment]
LargeTexture may be able to solve this (like in 2.x) but it does not have an importer that splits image data into small chunks.

**Comment by Xrayez** [comment]
As I said in the linked PR, it does fail to render the preview of a texture larger than 16384 pixels in size.

Though I've found some places where this limit is inconsistent but not sure if it's related to specific image format:
https://github.com/godotengine/godot/blob/4e4697b1c481094949165fa9edbe6aeebcfcf3b4/core/image.cpp#L1675-L1676

So yeah I'd basically would like to increase image max size to at least 32768 which should cover most use cases I believe, and just show a warning that the imported image won't render past render limit which seems to be 16384.

**Comment by Xrayez** [comment]
Something like this:

![image_too_large_but_ok](https://user-images.githubusercontent.com/17108460/61299378-a096cf00-a7e8-11e9-961c-92d759d18778.png)
