### ISSUE TITLE
GraphNode does not grab focus when clicked

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30243]
**Godot version:**

3.1

**Issue description:**

GraphNode implements a selected state, but does not aquire focus when clicked even with focus acquisition set to "click". This means that _gui_input does not receive key input events unless you do the following after enabling click focus:

```
func _gui_input(event):
	if event is InputEventMouseButton:
		grab_focus()
```

Imho clicking a GraphNode should grab focus by default.

[GraphNode.zip](https://github.com/godotengine/godot/files/3348253/GraphNode.zip)

**Comment by sparkart** [comment]
The GraphNode does grab focus when clicked, which is demonstrated when you connect a "focus_entered"  signal to it. It immediately loses focus for some reason.
