### ISSUE TITLE
graphedit delete_nodes_request should pass origin node

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30240]
**Godot version:**

3.1

**Issue description:**

GraphEdit's `delete_node_request` does not pass any information about the node wanting to be deleted... making it entirely useless. Since it makes it impossible to use the signal to delete the node and correctly remove its connections.

The current way to delete a node seems to be: Let the node call queue_free on itself. Catch the deletion_request signal to force an update of the graphedit node, which will then clean up connection and redraw the node.

**Comment by Zylann** [comment]
Editors of the engine using `GraphEdit` do it all in this way, which I also did in GDScript:
```gdscript
func _on_GraphEdit_delete_nodes_request():
	var to_delete = []
	
	for i in _graph_edit.get_child_count():
		var node = _graph_edit.get_child(i)
		if node is GraphNode:
			if node.selected:
				to_delete.append(node)
	
	for node in to_delete:
		node.free() # queue_free also works
```

However it raises a bug that I'm about to post.

**Comment by asheraryam** [comment]
I'm currently using this inside the GraphNodes themselves

```
func _on_Node_close_request():
	# any cleanup
	queue_free()
	print('removing node')
```

The GraphEdit not sending node information with the signal definitely needs fixing since it's useless otherwise, but I guess it can be worked around by manually emitting a signal from the nodes themselves when they get this callbacl

**Comment by FaerDerr** [comment]
Since Godot 4 is around the corner, It would be cool if someone could take some time to implement that !
That way, people just learning more advanced tools (like me) wouldn't waste time looking around on how to do that correctly ! :)
