### ISSUE TITLE
change shadow resolution without restart

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#30241]
**Godot version:**
3.1

**OS/device including version:**
rx580

**Issue description:**
Im working on a project where we are currently incorporation some graphics options. It would be nice to be able to apply the settings without needing the user to quit and relaunch the game. We have this issue mainly with shadow resolution.

**Comment by Gibbz** [comment]
Ive had a further look into the viewports. It would be great to get the following settings added to the viewports so the user doesnt need a restart:

- target frame rate/frame cap
- shadow sizes (directional especially)
- anisotropic filter level

**Comment by Calinou** [comment]
> target frame rate/frame cap

Just set `Engine.target_fps` at any time :slightly_smiling_face:

**Comment by Gibbz** [comment]
Nice, that may be helpful! 
It would be nice to have independent frame rates for render viewports for performance and style purposes :)

**Comment by Calinou** [comment]
> It would be nice to have independent frame rates for render viewports for performance and style purposes :)

To render specific viewports at a lower frequency, you could render them manually by setting their **Update Mode** to **Once** repeatedly using a timer.

**Comment by Calinou** [comment]
I'll close this issue in favor of #18621. Please open another issue related to changing the anisotropic filtering level at runtime :slightly_smiling_face:
