### ISSUE TITLE
LightOccluder in Tilemaps loosing their lightmask

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#3025]
When using LightOccluders on different light masks in a tileset scene, the light masks will be reset to 1 after convert to TileSet.
After a quick view in the generated tileset.xml it seems to me, that the light mask info isn't stored there.
Converting it to a .res file instead of .xml has the same issue.

**Comment by reduz** [comment]
tilemap draws everything as a batch, including occluders so any per-tile information except material is lost by design. Maybe what we could do is add a property so we can set the occluder mask for the entire tilemap?

**Comment by reduz** [comment]
an alternative for what you desire may be using more than one tilemap with different occluder masks

**Comment by nopeson** [comment]
In my case, there was only one occluder in the tilemap. It was on mask 2, but then reset to mask 1. Sorry, my description was a bit unclear in that point.

**Comment by reduz** [comment]
oh ok, now you can change occluder mask in tilemap settings

**Comment by nopeson** [comment]
great, thx! i'll check it with the next build :)
