### ISSUE TITLE
Gamepad vibration doesn't work on windows.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#30256]
Hi, I made a game that uses gamepad vibration and where the gamepad vibration is fundamental to the game, since there's not visual or audio output.

I use the gamepad vibration to convey information to the player.

The game works fine under lubuntu, but there's not vibration output on windows 7 x64.
I installed the drivers and could get some rumble vibration from the USB gamepad setup panel, but not vibration output on my windows exported game.

**Comment by KoBeWi** [comment]
According to #5013, vibration isn't implemented yet for Windows.

**Comment by Calinou** [comment]
@KoBeWi It should be implemented now as https://github.com/godotengine/godot/pull/5225 was merged.

**Comment by Ranoller** [comment]
Last time i test in my control singleton it works, i will test other time...

**Comment by eon-s** [comment]
Which gamepad? Godot version? drivers, etc.?

**Comment by ca3games** [comment]
> Which gamepad? Godot version? drivers, etc.?

Nanicastation (generid bootleg gamepad)
Godot 3.1.1
Generic gamepad drivers

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/14634.
