### ISSUE TITLE
Re-organize Script Editor's Edit menu

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#30265]
**Godot version:**
ae65c610e

**Issue description:**
This is the edit menu right now:
![image](https://user-images.githubusercontent.com/2223172/60536213-0d4c9c80-9d06-11e9-9cfb-fc41b4ec3ca8.png)

It's... long. Especially compared to other menus. Many of the positions can be moved to sub-menus, like Convert Case, to make it shorter and probably more accessible.

My proposals are:

- ~~Rename "Bookmarks" to "Go to" (as discussed in #29071), and move Breakpoint-related actions there.~~
- Fold/Unfold Line/All Lines -> Folding sub-menu
- Convert/Auto Indent (also maybe Indent Left/Right) -> Indent sub-menu
- _Optionally:_ Move Up/Down, Delete Line, Toggle Comment -> Line (or Line Operations) sub-menu

This would make the menu 8 (or 10) positions shorter. (actually, similar thing could be done with File menu...)

Any other propositions? Or the menu should stay as now?

**Comment by akien-mga** [comment]
> Rename "Bookmarks" to "Go to" (as discussed in #29071), and move Breakpoint-related actions there.

This is implemented in #30228.
