### ISSUE TITLE
OS.get_user_data_dir() has incorrect/unclear documentation

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot#30260]
> **String get_user_data_dir() const**
> Returns the absolute directory path where user data is written (user://).
> / - - - /
> On Windows, this is %APPDATA%/Godot/app_userdata/[project_name], or 
> %APPDATA%/[custom_name] if use_custom_user_dir is set.

When OS.get_user_data_dir() is executed in a project and the result is printed to console, the result is:  
C:/Users/[accountname]/AppData/**Roaming**/Godot/app_userdata/[projectname]

Also, the Custom User Dir Name setting is not documented well enough to understand
what one is supposed to write into the field and how it affects the [projectname] save dir.

**Comment by Calinou** [comment]
> Also, the Custom User Dir Name setting is not documented well enough to understand what one is supposed to write into the field and how it affects the [projectname] save dir.

@aspenforest What could be added to the [current description](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-application-config-custom-user-dir-name) to make it clearer?

**Comment by aspenforest** [comment]
For example, is it supposed to be an absolute path ("C:/folder"), or is it
relative to where the game executable is running ("res://folder") ?

**Comment by akien-mga** [comment]
The `OS.get_user_data_dir()` docs were clarified with #30449. IMO it's clear enough what they refer to, and they do specify that the user data dir is *absolute* (and the examples given are too).

The only thing that might still be unclear is for Windows users who may not be familiar with `%APPDATA%` nor with `%USERPROFILE%`. Explaining it further would force us to give an example with a made up username though, e.g. `C:\Users\JohnDoe`.

As for the custom user dir name property, it does state (emphasis mine):

> If a custom directory name is defined, this name will be used instead and **appended** to the system-specific user data directory (same parent folder as the Godot configuration folder documented in [method OS.get_user_data_dir]).

And clicking the link would confirm what exact path that is on the user's system.

So as far as I can see, all relevant information is already included in both descriptions. The language could maybe be improved though, if the included information is not crystal clear when reading it.

**Comment by aspenforest** [comment]
Thank you for the clarifications and the improved documentation. :)

**Comment by akien-mga** [comment]
I'll close assuming that things are clear enough after the recent changes. If something is still unclear, please comment, ideally with a suggestion on how to make it clearer.

**Comment by hiulit** [comment]
In the docs for v3.1 https://docs.godotengine.org/en/3.1/tutorials/io/data_paths.html it says that the `user://` path for macOS is `~/.local/share/godot/app_userdata/Name` (same in Linux), but I'm using **Godot v3.1.1-stable** on macOS and the path is `/Users/[USER]/Library/Application Support/Godot/app_userdata/`.
That's the path you get from `OS.get_user_data_dir()`.

I don't know if the Linux path is still the same that it is stated in the docs, but the macOS one should be updated.

Thanks!

**Comment by Calinou** [comment]
@hiulit This was corrected in the `latest` branch already: https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html

Everything written in the `latest` branch also applies to `3.1`, it should be cherry-picked. cc @akien-mga

**Comment by hiulit** [comment]
Thanks! I have to say, it is my fault for not checking the latest docs. But
thanks to my mistake we now know that the the 3.1 docs have to be updated :)

El dv., 15 de nov. 2019, 14:11, Hugo Locurcio <notifications@github.com> va
escriure:
