### ISSUE TITLE
On the posibility to make a third party tool for console homebrew export (discussion).

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#30266]
Hi, I know console export is not possible for license issues.
My question is that what are the legalities of having a third party tool to export a godot project into a homebrew executable ready to be played on consoles, mainly retro ones.

**Comment by piratesephiroth** [comment]
I think people can fork the repository and make their own exporters, like https://www.youtube.com/watch?v=7EYiev3PARc

But I don't think something like that will ever be added to the main project because it will require constant maintenance.

**Comment by Calinou** [comment]
I'll close this, as this will not be officially supported as @piratesephiroth said. However, nothing prevents third parties from creating homebrew console ports (at their own risk).
