### ISSUE TITLE
Hints show up under other controls if controls are in a canvas layer

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#30273]
**Godot version:** 3.0.6 and 3.1.1 stable official (from Steam)
**OS/device including version:** Windows 8

**Issue description:** When buttons with hints are placed in a `CanvasLayer`, the hints for some buttons render other buttons.

Removing them from the canvas layer causes the hints to render correctly (always on top).

**Steps to reproduce:**
- Create a new project with a new scene with a new canvas layer
- Add a `Button` with a reasonable size and a hint, inside the canvas layer
- Duplicate it twice and place them adjacent to each other
- Run the app and hover over the middle button; the tooltip appears under the controls.

**Minimal reproduction project:** 3.1.1 project provided. 

[HintBugTest.zip](https://github.com/godotengine/godot/files/3353172/HintBugTest.zip)

![image](https://user-images.githubusercontent.com/31222662/60562143-47c53200-9d24-11e9-8d39-ff7039b4a496.png)

**Other:** Please provide a work-around. For my 3.0.6 project (can't upgrade, release is imminent) I need four buttons in a canvas layer because my map is bigger than my view - I don't know how else to always keep them on-screen.

![image](https://user-images.githubusercontent.com/31222662/60562172-7216ef80-9d24-11e9-8188-fff714c467e1.png)

**Comment by sparkart** [comment]
A work around is if you make all of the buttons children of a "Control" node. Then, make that "Control" node a child of your "CanvasLayer" node.

**Comment by nightblade9** [comment]
That seems to work, thanks @sparkart

**Comment by KoBeWi** [comment]
Fixed in 4.0
![image](https://user-images.githubusercontent.com/2223172/94351896-fa3a9080-005e-11eb-973c-62bfc9881d5c.png)

Impossible to fix in 3.2 without hacks, so it's not worth it. Just make sure all your controls are on one layer.
