### ISSUE TITLE
TextEdit font color affects materials with 'Use As Albedo' option

### ISSUE THREAD

**Issue by tastesliketriangle** [godotengine/godot#30275]
**Godot version:**
0b555fc70af3c717665934c95070aa6aa481679f
also works with the Godot_v3.1-stable_win64

**OS/device including version:**
Windows 7 x64

**Issue description:**
 A TextEdit node being rendered to a texture from a Viewport will affect the colour of ALL materials in the scene that have enabled 'Use as Albedo' option.
![ezgif](https://user-images.githubusercontent.com/5613717/60564468-beb2f880-9d2d-11e9-9e77-9dccef0fda2c.gif)

**Steps to reproduce:**
Add a TextEdit node, then render to a texture.
Add another object with a material that has 'Use As Albedo' enabled.
Change font colour for more pronounced effect.

**Minimal reproduction project:**
[materrortest.zip](https://github.com/godotengine/godot/files/3353340/materrortest.zip)

**Comment by Llcoolsouder** [comment]
Another small but relevant observation:

The color of the cube in this example is always the color of the last character rendered in the TextEdit. 

For example in the current example with text
```
Foo = 0
Bar = 1
```
the numbers are rendered in orange. However, when I change the text to 
```
Foo = 0
Bar = "test"
```
the string is rendered in gray and the cube is likewise rendered in gray.

**Comment by tastesliketriangle** [comment]
the bug seems to actually happen based on the font colour. setting 'Font Colour' under 'Custom Colors' seems to be what it's tied to.

the bug always happens. it's just that by default the text is a grey that subtley affects the materials. gah!
