### ISSUE TITLE
Game always crash the window session on Android P simulator when Corner Display Cutout is turn on

### ISSUE THREAD

**Issue by kruglinski** [godotengine/godot#30274]
**Godot version:**

3.1.1 stable
2.1.6 rc

**OS/device including version:**

The Simulator in the latest Android SDK with Android P system

**Issue description:**

When turn on Corner Display Cutout on android simulator,  game always crash the window session.
06-29 03:55:43.403 2005 2710 E WindowManager: Window Session Crash
06-29 03:55:43.403 2005 2710 E WindowManager: java.lang.NullPointerException: Attempt to read from field 'android.view.SurfaceControl com.android.server.wm.WindowSurfaceController.mSurfaceControl' on a null object reference
06-29 03:55:43.403 2005 2710 E WindowManager: at com.android.server.wm.ForcedSeamlessRotator.finish(ForcedSeamlessRotator.java:78)
06-29 03:55:43.403 2005 2710 E WindowManager: at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:1888)
06-29 03:55:43.403 2005 2710 E WindowManager: at com.android.server.wm.Session.relayout(Session.java:244)
06-29 03:55:43.403 2005 2710 E WindowManager: at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:309)
06-29 03:55:43.403 2005 2710 E WindowManager: at com.android.server.wm.Session.onTransact(Session.java:164)
06-29 03:55:43.403 2005 2710 E WindowManager: at android.os.Binder.execTransact(Binder.java:731)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: FATAL EXCEPTION: main
06-29 03:55:43.406 6439 6439 E AndroidRuntime: Process: com.android.systemui, PID: 6439
06-29 03:55:43.406 6439 6439 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.view.SurfaceControl com.android.server.wm.WindowSurfaceController.mSurfaceControl' on a null object reference
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.os.Parcel.createException(Parcel.java:1948)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:1910)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:1860)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.IWindowSession$Stub$Proxy.relayout(IWindowSession.java:957)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.ViewRootImpl.relayoutWindow(ViewRootImpl.java:6546)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1995)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.Choreographer.doCallbacks(Choreographer.java:761)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.Choreographer.doFrame(Choreographer.java:696)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:873)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6669)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at com.android.server.wm.ForcedSeamlessRotator.finish(ForcedSeamlessRotator.java:78)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:1888)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at com.android.server.wm.Session.relayout(Session.java:244)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:309)
06-29 03:55:43.406 6439 6439 E AndroidRuntime: at com.android.server.wm.Session.onTransact(Session.java:164)
06-29 03:55:43.406 6439 6439 E AndroidRuntime:

**Steps to reproduce:**
![0](https://user-images.githubusercontent.com/2869425/60562187-1af73600-9d89-11e9-8dce-5c810375c622.png)
![1](https://user-images.githubusercontent.com/2869425/60562195-2185ad80-9d89-11e9-94a3-03aa281a6893.png)
![2](https://user-images.githubusercontent.com/2869425/60562199-264a6180-9d89-11e9-971d-83db2ba7239f.png)
![3](https://user-images.githubusercontent.com/2869425/60562201-29dde880-9d89-11e9-8b48-3e87af54be1a.png)

**Minimal reproduction project:**

2.1.6: 
[safe.zip](https://github.com/godotengine/godot/files/3353213/safe.zip)

3.1.1:
[projects.zip](https://github.com/godotengine/godot/files/3353214/projects.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.
