### ISSUE TITLE
HTTPRequest request timeout cannot be configured

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30276]
**Godot version:**
v.3.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Connection never times out when connecting with a host that does not exist. I think it only happens when trying to connect with ip hosts, status is indefinitely `STATUS_CONNECTING` (3). I'm not sure if that is expected behavior so for now i'v created a `Timer` `Node` and i cancel the request on timeout of the timer.
What i was expecting is the request to timeout at some point and call the `request_complete` signal. Also i was expecting to find out some `timeout` property or parameter in case we need to timeout the connection manualy.

**Steps to reproduce:**
Request anything from an unrelovable ip, example:
```
request("http://10.10.10.10:1234"
request("http://127.0.0.1:1234"
request("http://1.1.1.1:1234"
```
Any of these should be able to reproduce it as long as there is no server running on these ips/ports.

**Comment by Faless** [comment]
If really the server is not responding, it should time out, but the timeout is 5 minutes.

Are you sure it doesn't timeout after 5 minutes? I tested it, and for me it times out after 5 minutes as it should.

`request("http://127.0.0.1:1234")` should btw fail immediately, because unless you have a firewall active on localhost you will get a connection refused.

You don't get it for external server servers because most of them have firewall set on [`DROP` and not `REJECT`](https://serverfault.com/questions/157375/reject-vs-drop-when-using-iptables).

If the IP does not exists (which for IPv4 is very unlikely now, unless it's a private address) you'll probably get disconnected very soon too, since routers will send back to your machine a "destination unreachable" packet.

That said, I agree, we should add an option to specify a TCP timeout different from the default `300` seconds.

**Comment by zaksnet** [comment]
> If really the server is not responding, it should time out, but the timeout is 5 minutes.
> 
> Are you sure it doesn't timeout after 5 minutes? I tested it, and for me it times out after 5 minutes as it should.
> 
> `request("http://127.0.0.1:1234")` should btw fail immediately, because unless you have a firewall active on localhost you will get a connection refused.
> 
> You don't get it for external server servers because most of them have firewall set on [`DROP` and not `REJECT`](https://serverfault.com/questions/157375/reject-vs-drop-when-using-iptables).
> 
> If the IP does not exists (which for IPv4 is very unlikely now, unless it's a private address) you'll probably get disconnected very soon too, since routers will send back to your machine a "destination unreachable" packet.
> 
> That said, I agree, we should add an option to specify a TCP timeout different from the default `300` seconds.

Sorry @Faless i forgot to update. Yes, it times out at 5 minutes (with a nonsense net_socket.h error message currently). I'm already trying to add the timeout parameter for the timeout if that is ok.

**Comment by zaksnet** [comment]
@Faless , as i suspected, the 5-minute timeout doesn't seem to be consistent. In fact, It rarely occurs to me:
![socketTimeoutCode](https://user-images.githubusercontent.com/1850856/60656874-f8345280-9e58-11e9-8fc6-b42059247a6e.png)
![Screenshot_2](https://user-images.githubusercontent.com/1850856/60656599-6593b380-9e58-11e9-82b6-ed1e2b1c8d1f.png)
It might have timed out some time and showed the net_socket.h error, but I wasn't sure if it was after 5 minutes so i did some debugging. Turns out that it goes way beyond 300 sec. I will do some more debugging and let you know.

> request("http://127.0.0.1:1234") should btw fail immediately because unless you have a firewall active on localhost you will get a connection refused.

Indeed that is what i expected also. There is no firewall running in my computer:
![firewall](https://user-images.githubusercontent.com/1850856/60656782-c4592d00-9e58-11e9-885f-739ca169c1d7.png)
Also no software firewall.

I'm am connecting through the 4G network of my phone so i assume the router is located at the transmit tower(?). Not sure if that makes any difference.

**Comment by Faless** [comment]
On Thu, Jul 4, 2019, 11:46 Zak Stam <notifications@github.com> wrote:

> @Faless <https://github.com/Faless> , as i suspected, the 5-minute
> timeout doesn't seem to be consistent.
>

Well, it should be more or less consistent, but it might indeed be
different than 5 minutes on different OS.
I'm pretty sure there's a socket option for that, so we should at least
normalize it.

> Also no software firewall.
>
Did you disable the windows firewall completely?

**Comment by Faless** [comment]
Trying to connect with disconnected internet (i.e. disconnect before
launching the project) still gives you no error on 1.1.1.1:1234 ? Or only
on localhost?

**Comment by Faless** [comment]
BTW, if you type http://1.1.1.1:1234 in your browser it will likely not say
can't connect right away, it will have to timeout. At least that's what
happens for me with Firefox and chrome. Isn't that the case for you?

It's an intrinsic feature of the internet, that you can't really know a
port/IP is not available unless a router or the host machine sends you an
icmp packet saying destination not reachable or connection refused.
The only thing you can do is to set a timeout.

**Comment by zaksnet** [comment]
>BTW, if you type http://1.1.1.1:1234 in your browser it will likely not say
can't connect right away, it will have to timeout. At least that's what
happens for me with Firefox and chrome. Isn't that the case for you?

Indeed that is what's happening with firefox and chrome. i get `ERR_CONNECTION_TIMED_OUT`.
>Trying to connect with disconnected internet (i.e. disconnect before
launching the project) still gives you no error on 1.1.1.1:1234 ? Or only
on localhost?

After further testing, it seems that this is happening with any host as long as you add a custom port to them. Example:
`http://www.google.com:1234`
`http://127.0.0.1:1234`
`http://1.1.1.1:1234`

None of these ever timed out for me. It does not matter if i am connected or not, the result is the same (never times out).

> Did you disable the windows firewall completely?

That's right, the windows firewall is completely disabled and i have no software firewall running.

**Comment by Faless** [comment]
> None of these ever timed out for me.

Didn't you say that one of them timed out before? And only localhost didn't time out?

**Comment by zaksnet** [comment]
>Didn't you say that one of them timed out before? And only localhost didn't time out?

As stated in my initial post:
>Request anything from an unrelovable ip, example:

>request("http://10.10.10.10:1234"
request("http://127.0.0.1:1234"
request("http://1.1.1.1:1234"
Any of these should be able to reproduce it as long as there is no server running on these ips/ports.

I though that any ip host would give you the error.

And as stated in my last post:
>After further testing, it seems that this is happening with any host as long as you add a custom port to them. Example:
http://www.google.com:1234
http://127.0.0.1:1234
http://1.1.1.1:1234

>None of these ever timed out for me. It does not matter if i am connected to the internet or not, the result is the same (never times out).

After further testing, this only occurs when you use a custom port.
As for the timeout:
>It might have timed out some time and showed the net_socket.h error, but I wasn't sure if it was after 5 minutes so i did some debugging. Turns out that it goes way beyond 300 sec. I will do some more debugging and let you know.

You can also check the screenshots i attached to verify.

**Comment by Faless** [comment]
> After further testing, this only occurs when you use a custom port.

because connections to that port is blocked by the server. If you connect to a custom port that is open no problem, if you connect to a standard port on a server that has connection dropped to that port it would be the same.



> It might have timed out some time and showed the net_socket.h error, but I wasn't sure if it was after 5 minutes so i did some debugging. Turns out that it goes way beyond 300 sec.

As I said, the 5 minutes is OS dependant. But you DID get a socket error and a disconnect after some time then.

**Comment by zaksnet** [comment]
> > After further testing, this only occurs when you use a custom port.
> 
> because connections to that port is blocked by the server. If you connect to a custom port that is open no problem, if you connect to a standard port on a server that has connection dropped to that port it would be the same.
> 
> > It might have timed out some time and showed the net_socket.h error, but I wasn't sure if it was after 5 minutes so i did some debugging. Turns out that it goes way beyond 300 sec.
> 
> As I said, the 5 minutes is OS dependant. But you DID get a socket error and a disconnect after some time then.

I am sorry, i did get an error at some point and as i said in the following posts after that, i tried to reproduce it but i could not. The timeout does not seem to ever happen for me as demonstrated in the screenshots. By "Ever happening", i mean that i left it running for about 10 min. Although i am willing to leave for more, it seems pointless.

**Comment by Faless** [comment]
@zaksnet well, It did work on linux, with a 5 min timeout, I'll reboot on windows 10 and give it a try myself.

**Comment by mkadirtan** [comment]
I think this should also go as a feature request. A timeout property on HTTPRequest node would be very useful.

**Comment by Faless** [comment]
@zaksnet sorry for not getting back to you earlier, I've been away from my computer this weekend.
I confirm on Windows connect never times out.
As said in your PR I think this specific issue should be handled in StreamPeerTCP.
See #30422
