### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by hpn33** [godotengine/godot#30285]
**Godot version:**
3.1

**OS/device including version:**
win 10 64

**Issue description:**
microsoft visual studio 2019 community
python 3.7.3
scons 3.0.1

```
scons platform=windows
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
 Found MSVC version 14.1, arch amd64, bits=64
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
run(["core\method_bind.gen.inc", "core\method_bind_ext.gen.inc"], ["core\make_binders.py"])
Executing builder function in subprocess: module_path='H:\\workspace\\godot-3.1\\core\\make_binders.py', parameter_file='C:\\Users\\HEERRA~1\\AppData\\Local\\Temp\\3fa02edaa4914c8986114a3634a123d6.json', parameter_file_size=15957, target=['H:\\workspace\\godot-3.1\\core\\method_bind.gen.inc', 'H:\\workspace\\godot-3.1\\core\\method_bind_ext.gen.inc'], source=['H:\\workspace\\godot-3.1\\core\\make_binders.py']
Compiling ==> platform\windows\godot_windows.cpp
godot_windows.cpp
H:\workspace\godot-3.1\core/typedefs.h(34): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
scons: *** [platform\windows\godot_windows.windows.tools.64.obj] Error 2
scons: building terminated because of errors.

```

**Comment by qarmin** [comment]
Which exactly commit?
Appveyor doesn't show any problems - https://ci.appveyor.com/project/akien-mga/godot/builds/25711457

**Comment by hpn33** [comment]
The only part that is different is python version
my version is 3.7.3
and you 2.7.16
I have to check it out

**Comment by akien-mga** [comment]
You likely have an incomplete installation of Visual Studio, probably lacking the Windows 10 SDK. Google " Cannot open include file: 'stddef.h' ", you should find lots of posts about this which is not a Godot issue.

**Comment by hpn33** [comment]
ok now i have
Godot version:
3.1

OS/device including version:
win 10 64

Issue description:
microsoft visual studio 2019
python 2.7.16
scons 3.0.1

```
I:\workspace\godot-3.1>scons platform=windows
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
Found MSVC compiler: x86_amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] scons: *** [AUTHORS.md] ValueError : unsupported pickle protocol: 4
scons: building terminated because of errors.
```

what now?

**Comment by Calinou** [comment]
If you switched Python versions, you should clean all generated files before running SCons again using `git clean -dfx` (this will remove all untracked and ignored files, beware).

(pickle is a serialization format that's popular in Python programs, and its format isn't compatible across major versions.)

**Comment by hpn33** [comment]
I changed the python version to 3.7.3 with the previous settings,
and now everything is working.
Thank you for your guides.

**Comment by gamepad-coder** [comment]
Definitely a Visual Studio installation issue, 

but posting what worked for me in case it helps anyone searching + troubleshooting this problem.

<hr>

**Using:**
- Windows 10
- Python 3 
- Scons 4
- Visual Studio Community 2019
  - "Workload" called "Desktop Development with C++" installed<br>_(however if this is incomplete/ incorrectly installed, it will not notify you on the modify screen)_.
  - No other workloads nor modules installed in VS 2019.

Compiling Godot master branch for Windows from Powershell using SCons, using MSVC default and not MinGW.

**Issue:**

Visual Studio 2019 inaccurately displayed that "Desktop development with C++" was fully installed. It was only partially installed.

Upon typing `scons platform=windows -j6` I got the error : 

`C:\GitHub\_ _ Repository\Godot\core/typedefs.h(34): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory`


**Fix:**

Reinstalling "Desktop development with C++" resolved this error, and (for me) I was immediately able to compile Godot. 

**Steps / More Details:**

To modify or install more "Components" or "Workloads" for Visual Studio 2019 :
- Press the Windows Key (or Start in the Windows Taskbar).
- Type "Visual Studio Installer" without quotes
- A shortcut with this name should display, open it.
- It will start with a tab focused called "Installed". You should see Visual Studio Community 2019. 
- Click "Modify" to pull up a configuration screen.

Ensure "Desktop development with C++" is fully installed : 
- From the Modify menu, stay on the first tab titled "Workloads".
- Find the section "Desktop & Mobile".
- If "Desktop development with C++" is already checked, click it once and it will be unchecked.
- Click it again to re-enable the checkbox. 
- If it was incomplete, you will now see a nonzero number in the bottom-right corner labeled "Total space required".
- Click "Modify" below this, and VS will download and install the missing parts of this Workload.

![2020-11-16 16_51_50-Visual Studio Installer](https://user-images.githubusercontent.com/65138515/99323169-402dfc80-2837-11eb-81b2-a129a39ab1ec.png)
![2020-11-16 16_52_07-Visual Studio Installer](https://user-images.githubusercontent.com/65138515/99323170-415f2980-2837-11eb-88b6-b239fdecd737.png)
![2020-11-16 16_52_24-Visual Studio Installer](https://user-images.githubusercontent.com/65138515/99323172-415f2980-2837-11eb-88b9-3de514908ee4.png)



Once this finished, I was immediately able to compile Godot from the same Powershell instance, without restarting Windows 10. Your mileage may vary.

Good luck!
