### ISSUE TITLE
Document Texture2DArray, Texture3D, and array shader functionality

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30298]
**Documentation details:**
The following classes require documentation: (They don't even have a page right now.)

TextureLayered, Texture2DArray, Texture3D

sampler2dArray must be added to the shading language data types

The following functions must be added to the shading docs:
texture(sampler2DArray, vec3(u, v, layer))
textureLod(sampler2DArray, vec3(u, v, layer))

**Original issue. This has been implemented already. It is there for reference for the above documentation needs:**
GL_TEXTURE_2D_ARRAY implementation request:

Texture arrays are useful for creating FlipBook shaders. Like motion vector fire, fog, and water.
It allows sampling multiple layers from the same Uniform, allowing Shaders to play back sprite sheet animations and interpolate between frames. (Interpolation must be done by the user and is not part of this request) Some examples of Fire and Smoke effects using this technique: https://www.gdcvault.com/play/1024630/Visual-Effects-Bootcamp-The-Rise

To do this tree things are necessary:

A Texture2DArray (or similar) resource type. Which takes one image file. The number of vertical and horizontal frames to split it by. And the range of frames to use. (So you can have empty frames, or re-purpose the same texture for multiple sheets.)

A sampler2D uniform that takes a Texture2DArray resource.

Extend texture() to take a vec3 UV where the third component is the layer.

Example usage code that interpolates through the textures over time:
```
uniform sampler2DArray my_flipbook;

void frag() {
	int frame = int(TIME);
	COLOR = texture(my_flipbook, vec3(UV, frame)); 
}
```

Additionally there needs to be a means for the shader to get the number of layers within a sampler2DArray using the textureSize() function.

**Comment by TheDuriel** [comment]
And just before anyone gets any wrong ideas: AnimatedTextures are not this.

You can _kind of_ use them in a hacky way, if you employ some varying trickery. But the inability to access multiple layers during the same frame makes this incredibly poor practice.

**Comment by TheDuriel** [comment]
Relevant discussion investigating implementation details: https://www.gamedev.net/forums/topic/607286-glsl-texture-array/?tab=comments#comment-4841635

**Comment by Zylann** [comment]
Wasn't this feature added to the engine a while ago? https://github.com/godotengine/godot/pull/20597

**Comment by TheDuriel** [comment]
@Zylann  From what i can see there is no way of actually using that in a project. Just engine internals. So perhaps it needs exposing with the resource type?

**Comment by Zylann** [comment]
![image](https://user-images.githubusercontent.com/1311555/60620137-4fdbab00-9dd2-11e9-9b98-08ba5ea4492e.png)

Everything looks exposed. I haven't tested these much though.

**Comment by TheDuriel** [comment]
Just tried it. You can change the type of an image to TextureArray through the import dialogue. But you can not define a sampler2DArray to actually place the texture in.

sampler2D and samplerCube do not take a Texture2DArray resource. And texture() can not take a vec3 UV. (But textureLod can if you give it a samplerCube)

Looks like it was never fully implemented for Godots shader lang.

**Comment by Zylann** [comment]
> Just tried it. You can change the type of an image to TextureArray through the import dialogue. But you can not define a sampler2DArray to actually place the texture in.

You must use a shader with `uniform sampler2DArray my_texture` in it, and then a material using that shader in order to assign to that uniform.

> sampler2D and samplerCube do not take a Texture2DArray resource

Because that's not the correct uniform types.

> And texture() can not take a vec3 UV. 

It can:
![image](https://user-images.githubusercontent.com/1311555/60620821-1dcb4880-9dd4-11e9-9c82-256c28dfcaa1.png)

To me it looks like the feature is essentially missing from docs ¯\\\_(ツ)_/¯

**Comment by TheDuriel** [comment]
Whew. Ok typing it out does work. Yup, needs documentation. Maybe i close the issue and make a new one for documentation? It's fairly simple stuff.

```
shader_type canvas_item;

uniform sampler2DArray my_flipbook;

void fragment() {
    COLOR = texture(my_flipbook, vec3(UV, TIME)); 
}
```

Makes me wonder what is happening to TIME here though. Is it floor() or ceil()?

**Comment by Zylann** [comment]
I think `sampler2DArray` does not interpolate between frames, so it's probably floored or rounded. If you need full interpolation in all 3 coordinates (with `filter` is enabled as well), you could probably use a `sampler3D` with a `Texture3D` instead.

**Comment by TheDuriel** [comment]
Ok documentation details:

The following classes require documentation: (They don't even have a page right now.)

TextureLayered, Texture2DArray, Texture3D

sampler2dArray must be added to the shading language data types

The following functions must be added to the shading docs:
texture(sampler2DArray, vec3(u, v, layer))
textureLod(sampler2DArray, vec3(u, v, layer))

**Comment by TheDuriel** [comment]
@Zylann Interpolation should be done manually by the user. But its important to know what happens when you give it a float. Since directly passing an int is not possible.

**Comment by Zylann** [comment]
Interpolation does happen if you use a `Texture3D`, and it does not if you use a `TextureArray`. At least, that's how I understood them so far, given results other people got when testing them.

`texture(sampler3D, vec3)` also seems to be missing from autocompletion for some reason.

**Comment by akien-mga** [comment]
> The following classes require documentation: (They don't even have a page right now.)
> 
> TextureLayered, Texture2DArray, Texture3D

They do have pages in the classref, but their API is not documented yet:
```
$ python3 doc/tools/doc_status.py -bio doc/classes/ modules/*/doc_classes/ | grep Texture
| CameraTexture                          |     OK      | MISSING |    3/3    |   57%   |
| NoiseTexture                           |     OK      |   OK    |    5/6    |   96%   |
| ProxyTexture                           |   MISSING   | MISSING |    0/1    |    0%   |
| StyleBoxTexture                        |     OK      |   OK    |   12/21   |   78%   |
| Texture                                |     OK      |   OK    |   12/17   |   86%   |
| Texture3D                              |   MISSING   | MISSING |    0/0    |    0%   |
| TextureArray                           |   MISSING   | MISSING |    0/0    |    0%   |
| TextureLayered                         |   MISSING   | MISSING |    0/14   |    0%   |
| VisualShaderNodeTexture                |   MISSING   | MISSING |    0/10   |    0%   |
| VisualShaderNodeTextureUniform         |   MISSING   | MISSING |    0/8    |    0%   |
```

And then yeah, specific tutorials in http://docs.godotengine.org/en/latest/tutorials/shading/index.html would likely make sense.

**Comment by InfernalWAVE** [comment]
I'm deep in this now, is there something best to contribute toward here?

**Comment by clayjohn** [comment]
It looks like everything mentioned in this report has actually been completed, so I'll go ahead and close it.

@InfernalWAVE It looks like we have some work to do around documenting the 4.x style of setting filter/repeat mode (like in https://github.com/godotengine/godot/issues/62472) if you are interested.
