### ISSUE TITLE
Add position and scale properties to GUI nodes for animation

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#30303]
As of right now, there is no way to animate a GUI node's position and size, for example making a `Label` Node grow bigger when the mouse hovers over, when the GUI node is a child of a Container node. The solution for accomplishing this typically is to add it as a child of a `Node2D` and animate the `Node2D`'s properties, however, this does not function correctly when using a layout GUI node such as a `VBoxContainer`. If there were the rotation degrees and scale properties in each control node that functioned on the rasterized GUI, while ignoring layout nodes, then animation would be possible.

**Comment by creikey** [comment]
This is already implemented

**Comment by viroidgames** [comment]
Implemented how? I'm trying to animate dynamically created child elements in a vboxcontainer with no luck. I believe as soon as the items are added through add_child, the position of the new elements reset to (0,0) but I'd like them to start off the list so they can slide in from the left. As it is, they first appear, then after a blink, they slide in from the left. 

I'm using Tween node but using AnimationPlayer posed a different kind of problem. Only the first added child's animation runs. The other ones occupy space in the vbox but their animation doesn't play.

**Comment by creikey** [comment]
@viroidgames I was referring to the `rect_scale` property for that kind of animation, but a proposal in https://github.com/godotengine/godot-proposals to add a separate `visual_offset`, rotation, and scale is definitely in order for animations like these, as the current workaround is to set them as toplevel, which is usually cumbersome and causes visual glitches

**Comment by viroidgames** [comment]
I'll peruse the proposals and see what's in the works. Thank you for pointing that out.
