### ISSUE TITLE
DynamicFont outline does not draw using draw_char

### ISSUE THREAD

**Issue by DomsterKB** [godotengine/godot#30309]
**Godot version:**
v 3.1.1.stable.official

**OS/device including version:**
Windows 10 x64

**Issue description:**
Dynamic font outline does not show using draw_char() of CanvasItem.  An outline is expected to appear.  Outlines are working for draw_string().

**Steps to reproduce:**
1. Create a root node with Node.
2. Create a child node with Control or Node2D node and attach a GDScript to it.
3. Instantiate a new DynamicFont and initialize with a outline_size and color.
```
func _ready():
	dynamic_font = DynamicFont.new()
	dynamic_font.font_data = load("res://KGMissKindergarten.ttf")
	dynamic_font.size = 120
	dynamic_font.outline_size = 5
	dynamic_font.outline_color = Color( 0, 0, 0, 1 )
	dynamic_font.use_filter = true
```
4. Override the _draw() method and draw some characters with draw_char()
```
func _draw():
	for i in string.length():
		var c = string[i]
		var next_char = string[i + 1] if i + 1 < string.length() else ''
		var advance = draw_char(dynamic_font, pos, c, next_char, Color.red)
		pos.x += advance
```

**Minimal reproduction project:**
[DrawCharTest.zip](https://github.com/godotengine/godot/files/3357867/DrawCharTest.zip)

**Comment by joleeee** [comment]
You could do Font.draw_char() as long as you set the last parameter (outline) to true, it should draw the outline. Could work as a temporary workaround?
