### ISSUE TITLE
Detected that the app is using an old version of the Google Play Developer API.

### ISSUE THREAD

**Issue by phaitonican** [godotengine/godot#30323]
**Godot version:**
3.1.1

**OS/device including version:**
Linux 64bit

**Issue description:**
after Google Play APK upload:
![api](https://user-images.githubusercontent.com/25594670/60683089-3c921380-9e96-11e9-96ce-527434e90e51.png)

**Steps to reproduce:**
Export for android and upload to Play Console

**Comment by akien-mga** [comment]
Is this not relevant anymore?

**Comment by phaitonican** [comment]
No the issue doesnt show anymore on Play Console and I dont know which API godot uses, but I think it was rather a Play Console Bug... not sure though
