### ISSUE TITLE
APK should include custom drawables assets for common tablet screen densities

### ISSUE THREAD

**Issue by phaitonican** [godotengine/godot#30322]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Linux 64bit

**Issue description:**
![13](https://user-images.githubusercontent.com/25594670/60681012-da351500-9e8d-11e9-92ee-4dd32676afed.png)

**Steps to reproduce:**
Check this boxes in the export window of Android
![12](https://user-images.githubusercontent.com/25594670/60681014-de613280-9e8d-11e9-963e-c5fb3130b472.png)

**Minimal reproduction project:**
Export default project with this settings and upload to Play Store

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1003, as feature proposals are now tracked in the Godot proposals repository.
