### ISSUE TITLE
New node duplication behavior has wrong ordering

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#30339]
**Godot version:**
a9ad1e6692af85fbe8aab36361c304b81ed376f4

**Issue description:**
The new duplication behavior introduced in #30321 isn't perfect - it doesn't retain order of selected nodes.
![Dup1](https://user-images.githubusercontent.com/2223172/60679702-e5397680-9e88-11e9-97b0-644943c1bb5b.gif)

This is caused by the selection from editor being sorted weirdly. Well, it's still better than what we had before (see #28549), but I guess some people might be bothered by the ordering, so I'm just creating the issue hoping maybe someone will figure it out and fix it.
(also see the linked PR for more details on the selection problem)

**Minimal reproduction project:**
[DuplicationPlayground.zip](https://github.com/godotengine/godot/files/3363947/DuplicationPlayground.zip)

**Comment by Zylann** [comment]
Would it be possible to rely on the `index` property of the copied nodes, and sort them before adding to the tree?
