### ISSUE TITLE
Function to calculate a ColorRamp's color at a given value

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#3034]
I'd like to ask for a method in ColorRamp to return a color according to a value between 0 and 1. Such as having 0,0,0,0 and 255,255,255,255 as colors in the ramp, and this function would return Color(128,128,128,128) with 0.5 as input.
While the ColorRamp class has methods to get the values to interpolate manually, it'd be really convenient to have that built-in.

**Comment by bojidar-bg** [comment]
:+1:
