### ISSUE TITLE
Editor 2D view scroll limits not working properly

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#30348]
**Godot version:**
3.1.1

**OS/device including version:**
Manjaro Linux

**Issue description:**
When I create a tilemap I have scrolling problem in -y direction. If the map is bigger in x and -x direction I can scroll accordingly more to cover the tilemap cell, but in -y direction the viewport is locked and I can't scroll over some limit.

**Steps to reproduce:**
Create a tilemap and draw in -y direction.

**Comment by bojidar-bg** [comment]
Note the the bug depends on the Quadrant Size of the TileMap. On master, I can reproduce with quadrant size of 16, but not with quadrant size of 1.

Likely related to how the TileMap computes its boundary size.
