### ISSUE TITLE
Swapped Axes in OpenSimplexNoise Images

### ISSUE THREAD

**Issue by poberlohr** [godotengine/godot#30356]
**Godot version:**
v3.1.stable.official

**Issue description:**

In a small expirement I created a NoiseTexture using OpenSimplexNoise and added it to the scene as background image. Then I tried to query the noise value at a specific position, but it didn't match with what was shown on the screen.

It took me a while to figure out, that OpenSimplexNoise.get_image() swaps the x- and y-axis:

```cpp
for (int i = 0; i < p_height; i++) {
    for (int j = 0; j < p_width; j++) {
        float v = get_noise_2d(i, j); // this should be get_noise_2d(j, i);
// or maybe use x and y instead of j and i
```

See [open_simplex_noise.cpp](https://github.com/godotengine/godot/blob/87ee2a9239928e2811ce1711bc381f601edd278a/modules/opensimplex/open_simplex_noise.cpp)

**Steps to reproduce:**
```GDScript
var noise = OpenSimplexNoise()
var image = noise.get_image(1024, 1024)
image.lock()

var x = 700
var y = 400
var valueFromNoise = noise.get_noise_2d(x, y)
var pixelColor = image.get_pixel(x, y)
var valueFromNoiseImage = pixelColor.r * 2 - 1 # maps [0,1] to [-1,1]

if abs(valueFromNoise - valueFromNoiseImage) > 0.01:
    print("Reproduced issue: ", valueFromNoise, " vs ", valueFromNoiseImage)
```

**Minimal reproduction project:**

[NoiseImageFlippedAxesDemo.zip](https://github.com/godotengine/godot/files/3364122/NoiseImageFlippedAxesDemo.zip)

**Remarks:**
It is of course easy to work around this issue by just calling `noise.get_noise_2d(y, x)` instead, but that's something one has to figure out first.
What I don't know is, if fixing the order in open_simplex_noise.cpp would cause some side-effects for other projects. Alternatively the docs should just mention this issue, that would be helping too.

**Comment by Anutrix** [comment]
I think you are right but wouldn't it break compatibility?

**Comment by poberlohr** [comment]
It definitely could, especially if someone already calls `noise.get_noise_2d(y, x)` because it works that way.

The safest solution I can think of is introducing a fixed version of the function using a different name (or signature) and marking the existing one as deprecated.

What about passing a `Vector2` instead of separate x- and y-values? That should work in c++, but how does this translate to GDScript?

**Comment by Anutrix** [comment]
Maybe add a breaks-compatibility tag?
