### ISSUE TITLE
Json file read and save doesnt work on android

### ISSUE THREAD

**Issue by jacoby34** [godotengine/godot#30353]
**Godot version:** 3.1.1

**OS/device including version:** Android 9.0

**Issue description:**

I want to save and read from a json file on android. But the app just crashes. Ive tried both "user://" and "res:// with .json as non resource files". And both crashes. res:// when saving and user:// when reading the file. 

**Code:**
`var PATH = "user://settings.json"

func _ready():
	load_settings()
	
func save_settings():
	var save_dict = {}
	save_dict["test"] = 0
	var save_file = File.new()
	save_file.open(PATH, File.WRITE)
	save_file.store_line(to_json(save_dict))
	save_file.close()
	
func load_settings():
	var save_file = File.new()
	if not save_file.file_exists(PATH):
		return
	save_file.open(PATH, File.READ)
	var loaded_data = parse_json(save_file.get_line())
	save_file.close()
`

**Comment by KoBeWi** [comment]
If it crashes when saving/reading, it might be a file permission issue, not JSON problem. Check if you have proper permissions enabled.

**Comment by clayjohn** [comment]
@jacoby34 Did you try KoBeWi's advice yet? If so I would like to close this issue as solved.
