### ISSUE TITLE
Camera2D offset is blocked by limit

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#30358]
**Godot version:**
3.1

**OS/device:**
Windows 8.1, Toshiba Satellite

**Issue description:**
The `offset` of a `Camera2D` is blocked by the camera's limit.

If a camera is up against one of its limits and you adjust the camera's `offset` in the direction of the limit, nothing happens. Because altering offset is primarily used for camera effects like screen shake, it should ignore the camera's limits. Otherwise, you won't be able to do these effects when the camera is at the limit.

**Steps to reproduce:**
1. Create a 2D scene with a `Camera2D` and a `Sprite`.
2. Set the limits of the camera to the limits of the window.
3. Change the camera's offset while running the scene and observe that the camera does not change.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/3364238/TestProject.zip)

**Comment by securas** [comment]
The shaking problem could be solved simply by a temporary readjustment of the camera limits. This solution over-complicates use cases where the camera is not the child of a character node.
