### ISSUE TITLE
Shaders auto-completion has been broken

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#30350]
**Godot version:**
550f436f8

**Issue description:**

![bug](https://user-images.githubusercontent.com/3036176/60741633-e941c300-9f72-11e9-9663-8ffb1ae1305e.gif)

Expected:

![expect](https://user-images.githubusercontent.com/3036176/60741717-332aa900-9f73-11e9-9f9a-427892ee6ef7.gif)

**Comment by akien-mga** [comment]
Possibly related to @Geequlim's changes?

**Comment by Anutrix** [comment]
Broken by this commit https://github.com/godotengine/godot/commit/2293c612e6c0913b6999080c9f2fa77227348818 .

**Comment by Geequlim** [comment]
I'll check it.
