### ISSUE TITLE
Editor tooltips not working for me Windows 64-bit, v3.1.1

### ISSUE THREAD

**Issue by jgodfrey** [godotengine/godot#30360]
**Godot version:**
3.1.1 (stable, official, Windows 64-bit standard) 

**OS/device including version:**
Windows 10, 64-bit

**Issue description:**
I don't have *any* tooltips in the Godot editor. Research indicates this *used* to be a problem, but was fixed in 3.1.1. Unfortunately, that's not the case for me. I have a fresh install (no upgrades) and a new project, but don't see *any* tooltips in Godot.

I also filed a question here:

https://godotengine.org/qa/47869/godot-3-1-1-windows-tooltips-not-working-in-editor

**Steps to reproduce:**
None really. Run Godot. No tooltips.

**Minimal reproduction project:**
Is this important in this case? I don't have access to my project ATM, but can add it if necessary.

**Comment by clayjohn** [comment]
I am also on Windows 10 64-bit and I am having no problem with tooltips in editor.

**Comment by ticnew** [comment]
Same Issue here with me i have Windows 10 64 bit godot v3.1.1  no tooltip is shown

**Comment by jgodfrey** [comment]
Good to know it's not just happening to me... The lack of tooltips really steepens the curve for learning to use the editor.

I have noticed (on a few *very* rare) occasions, a random tooltip pop-up in the editor at a location not associated with the mouse cursor. The few times it's happened, I've tried to reproduce it by painstakingly moving the mouse to various controls and waiting for unusually long periods of time. Unfortunately, other than this handful of seemingly random sightings, tooltips just don't work here.

**Comment by jgodfrey** [comment]
Wait... I just found a semi-reliable way to see a single-tooltip...

I feel like this could be multi-monitor or display scaling related...

In my case, my setup is as follows:

- Two monitor setup 
   - Right-hand monitor
     - 1920x1080 laptop at 125% scaling
   -  Left-hand monitor
      - 1920x1200 DELL U2415 at 100% scaling

Using the above (at least ATM) I can get the "Add Child Node (Control+A)" tooltip associated with the "+" icon in the toolbar of the "Scene" panel to display as follows:

- Run Godot editor on right-hand monitor (HD laptop) in full-screen mode
- With the Godot editor having focus, move over the mouse over the mentioned "+" icon in the Scene panel (no tooltip seen)
- Quickly move mouse a bit left, placing the pointer on the left-hand monitor
- The tooltip opens after the mouse moves to the other screeen (and stays open until I move the pointer back into the Godot editor window

Does my setup resemble that of others with the same problem?

Can anyone else here reproduce the above?

**Comment by jgodfrey** [comment]
Changing the main HD laptop monitor back to 100% scaling doesn't seem to change anything. It still works exactly as outlined above...

**Comment by clayjohn** [comment]
Interesting! Could definitely be the result of the multi-monitor setup. I'm on a single 1920x1080 monitor and I have no issues. 

@Calinou Any ideas?

**Comment by jgodfrey** [comment]
One other data point. I was using reassigned editor fonts and font sizes. Thinking that could be related I reset the 3 fonts and the 2 font size properties and restarted the editor. However, that changed nothing. The above outline still works as described.

**Comment by jgodfrey** [comment]
I just tried disabled my 2nd monitor (via Display Settings |  Multiple displays |  Show only on 1). However, restarting Godot on the single, laptop HD display still shows no tooltips.

Also, in case the issue could be GPU related (doubtful since I can see tooltips on occasion as oultined above), I'm using the following:

- Lenovo Y500 laptop
- NVIDIA GeForce GT 750M

**Comment by Calinou** [comment]
@clayjohn I don't know what could be causing this, sorry :slightly_frowning_face:

**Comment by clayjohn** [comment]
@Calinou I thought it may be the result of multi-monitor / high DPI scaling. And you seem to be the expert in that regard. :)

**Comment by jgodfrey** [comment]
If I can find the time, I may try to build Godot locally and poke around a bit... If I find anything interesting, I'll report back here.

**Comment by jgodfrey** [comment]
I've found a little simpler way to show the tooltip issue than I outlined above. It's still related to hovering, and then moving the mouse quickly outside the Godot window. Here's a small video showing the situation...

https://drive.google.com/file/d/1Lu52IWVfZGHNFCCwmejTWH26D4O9wEC0/view?usp=sharing

**Comment by Calinou** [comment]
@clayjohn @jgodfrey mentioned that they tried to set the laptop's display scale to 100%, yet the issue still occured, so that doesn't appear to be related.

**Comment by ticnew** [comment]
is not about hiDPI i just have regular laptop with small screen and tooltip only shown when you run the mouse away from the entire editor after over it on a specific property like in @jgodfrey video

**Comment by jgodfrey** [comment]
Ok - weird... I just built a local version of Godot from source and the tooltips work correctly in debug  mode...

**Comment by ticnew** [comment]
it works great when you first time have godot on your machine (it was working great for me first), apparently some modification on editor run the tooltip and the only thing i've changed is the theme but it seems i found the solution from project setting  > Display > Mouse Cursor > Tooltip position offsite play with values of x and y and and save then reset them again back and reopen godot and that should bring the tooltip back, that works for me

**Comment by jgodfrey** [comment]
To be more specific...

I cloned the `master` branch and built the `debug` and `release_debug` targets for both 32 and 64-bit platforms. All of resulting exe's have functional tooltips. So, I guess whatever is causing the issue in the official 3.1.1 build has been fixed in `master`. While it might be interesting to know exactly *what* fixed the issue here, I probably won't dig into it any further.

**Comment by Calinou** [comment]
Closing, as this issue was apparently resolved between 3.1.1 and 3.2.

**Comment by TsFreddie** [comment]
is it possible to re-open this? Tooltip randomly stops working on my windows machine. If it stopped working, then all versions I have (3.2.5, 4.1.1, 4.1.2) will stop showing tooltips across reboot. If it started working, all versions will be fine until someday it just decided to stop working.

for me it really seems like a randomly occuring bug rather than a fixed one. Mine also started working after I built a dev build which makes this really hard to debug as well.

**Comment by pjmavcom** [comment]
I am having this problem as well. I have tried both GDScript and Mono versions, 4.2.2 and 4.2-dev6 and neither are working.
I am using Windows 10 with dual monitors with a RTX 3080 if that helps.
