### ISSUE TITLE
Editor may stay dimmed after a modal dialog is closed in some cases.

### ISSUE THREAD

**Issue by toasteater** [godotengine/godot#30368]
**Godot version:** Confirmed on 3.1.1 stable and `master` (d897131)

**OS/device including version:** Not related

**Issue description:** Editor may stay dimmed after a modal dialog is closed in some cases.

**Steps to reproduce:**
1. Open Editor Settings
2. In Interface/Theme, select a preset from the dropdown, then quickly click the "open" button for Custom Theme, before the color scheme change is actually applied.
3. Observe that a file dialog will pop up, and then be closed as the new color scheme is applied.
4. Close Editor Settings. Observe that the editor is still dimmed.

**Minimal reproduction project:** N/A

**Comment by lefay1982** [comment]
Also crashed in Android after a modal dialog is closing.
