### ISSUE TITLE
Code completion is highlighted incorrectly because of new icons

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#30365]
**Godot version:**
d897131

**Issue description:**
The new icons introduced in #29744 makes so that the highlighting while typing is incorrect, due to it not taking into account the size of the icons:
![Screenshot_20190706_002542](https://user-images.githubusercontent.com/30739239/60750842-cd074b80-9f9d-11e9-86ff-00ec75f12493.png)

CC @Geequlim

**Comment by Geequlim** [comment]
Not really understand the problem you met.

**Comment by YeldhamDev** [comment]
You see how there is a lighter area the ends between the 'n' and 'i' in the code completion? It should end after the 'a', because that's where it ends in the text.

**Comment by Geequlim** [comment]
Oh never noticed that before :laughing:
