### ISSUE TITLE
Using shortcuts in the EditorFileDialog freezes the editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#30366]
**Godot version:**
d897131

**Issue description:**
Trying to do any shortcut in the `EditorFileDialog` will result in the editor completely freezing.

**Comment by creikey** [comment]
I'm able to reproduce on arch linux with the same commit. Attatched is an example project. Steps to reproduce:

1. open example project in editor
2. click on sprite node in scene tree
3. click on the `[empty]` dropdown button next to the `Texture` property in the inspector
4. click on `Load`
5. press CTRL + H ( keyboard shortcut to toggle hidden files )

Godot will then become unresponsive
[godot-issue-30366.zip](https://github.com/godotengine/godot/files/3364385/godot-issue-30366.zip)

**Comment by creikey** [comment]
The behavior is not the same if a file is selected by clicking on its icon in the `EditorFileDialog` before pressing CTRL + H. Rather than becoming responsive, Godot will successfully hide shown hidden files, then on the next input event, the file dialog will disappear, but the editor will still remained blacked out as if it was there. Everything else functions as normal besides that.

**Comment by creikey** [comment]
When debugging the hang, send a continue signal to the `gdb` command by doing `kill -CONT [pid of godot gdb process]` to print the stacktrace

**Comment by creikey** [comment]
The freeze is the while loop on line 1402 in `core/ucaps.h` never exiting

**Comment by creikey** [comment]
The function `findn` in `core/ustring.cpp` is infinitely hanging

**Comment by creikey** [comment]
> The behavior is not the same if a file is selected by clicking on its icon in the `EditorFileDialog` before pressing CTRL + H. Rather than becoming responsive, Godot will successfully hide shown hidden files, then on the next input event, the file dialog will disappear, but the editor will still remained blacked out as if it was there. Everything else functions as normal besides that.

This is a separate bug, I will open a new issue on it. I believe I have found a possible fix for this issue and will open a PR
