### ISSUE TITLE
Using range() in for loop throwing error on android

### ISSUE THREAD

**Issue by emreozkartal** [godotengine/godot#30364]
**Godot version:**
3.1.1 via Steam

**OS/device including version:**
Compiled on Ubuntu 16.04
Test device: Samsung j4+ android 9

**Issue description:**
For loop with range() causes error on android. Working on linux without error.

code: 
```
for i in range(1,9):
 print(i)
```

or try 
`for i in range(9):
 print(i)`

Error:
`
07-06 04:52:48.757 14648 14778 E godot   : **SCRIPT ERROR**: Parse Error: Too many arguments for 'load()' call. Expected at most 1.

07-06 04:52:48.757 14648 14778 E godot   :    At: res://scripts/game.gdc:12:GDScript::load_byte_code() - Parse Error: Too many arguments for 'load()' call. Expected at most 1.

07-06 04:52:48.757 14648 14778 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR

07-06 04:52:48.757 14648 14778 E godot   :    At: modules/gdscript/gdscript.cpp:785:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR

07-06 04:52:48.758 14648 14778 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()

07-06 04:52:48.758 14648 14778 E godot   :    At: modules/gdscript/gdscript.cpp:2168:load() - Condition ' err != OK ' is true. returned: RES()

07-06 04:52:48.758 14648 14778 E godot   : **ERROR**: Failed loading resource: res://scripts/game.gdc

`

**Comment by akien-mga** [comment]
Did you make sure that the Android export template you use matches your editor version? If you're using the default settings via Steam it should, but if you compiled your own and use it as custom template, there could be a mismatch explaining such bytecode issues.

**Comment by emreozkartal** [comment]
I finally realized i'm using an old version or (non-released) version of godot source code.
Thank you.
