### ISSUE TITLE
Cannot fold code if numbers are not showing. 

### ISSUE THREAD

**Issue by urusuru** [godotengine/godot#30389]
**Godot version:**
3.1.1
**OS/device including version:**
Windows

**Issue description:**
In the General Settings > Text Editor > Line Numbers. If you disable "**Show Line Numbers**" then to fold the code you require almost too much precision, almost "pixel perfect precision" and you can't fold the code.

**Comment by sparkart** [comment]
Confirmed bug on 3.1.1 but it appears to be fixed with the latest version: Godot Engine v3.2.dev.custom_build.44db85d6f
