### ISSUE TITLE
Duplicate/inheritance does not make all resources unique

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#30385]
**Godot version:**
3.1

**OS/device including version:**
Windows

**Issue description:**
Sorry if this is not a bug and a feature request, but the documentation just does not make things clear regarding duplication and inheritance and the expected behaviour (to me) does not match the outcome.

Basically,
If I create a simple texture or almost any node, e.g.

    [ext_resource path="res://icon.png" type="Texture" id=1]
    [node name="TextureRect" type="TextureRect" parent="."]
    texture = ExtResource( 1 )

If I then duplicate it (CTRL+D) and change the texture it adds a new texture resource to the file and updates the reference:

    [ext_resource path="res://icon.png" type="Texture" id=**2**]
    [node name="TextureRect2" type="TextureRect" parent="."]
    texture = ExtResource( **2** )

However, if I do the same for a label and adjust the font, then duplicate, the two labels become linked to the same font resource and I have to select to 'make sub-resource unique' in the (hard to find and not exactly intuitive!)  object properties to unlink the font from the duplicate.

It seems to me that this is because font is a possibly special case being it's own resource, whereas the others are just plain properties, but if you duplicate an item you expect the system to be consistent across all properties, i.e. how many more properties of items need to be unlinked like this when you duplicate?

When you add on top inheriting scenes, it makes things even more confusing when you do things.

If not a bug, can this be a suggestion that when you duplicate all items automatically become unique, or at least rename 'duplicate' to be something more sensible (e.g. 'shallow duplicate' and have a secondary 'deep duplicate' that really does make everything unique.)

If you extend that to inherited nodes, it becomes even worse with changes to far down children affecting upstream parent scenes.

Thanks.

**Comment by KoBeWi** [comment]
When you duplicate a node with a texture, both nodes still share the same texture, but it's less obvious, because you normally don't edit its resource directly. If you have two font resources in separate files, when you change one font to the other, you should observe the same behavior as with textures.

**Comment by chucklepie** [comment]
I have a scene. I use inheritance to create 5 children. For these children I create another set of children via inheritance.

On the very bottom child I modify the texture and the font.

All siblings, all parents and the root parent get the font change.

How is this logical? This is exactly the same issue as duplicate. You have absolutely no idea whether changing a downstream item will affect an upstream item unless you know the specifics of each and every property.

**Comment by mrcdk** [comment]
How are you modifying those properties? Resources are shared by default and if you modify (aka open the resource and modify any of its properties) the changes will happen to any node that uses the same resource.

So if you modify the size of a font resource for example, every node that uses that resource will be updated because the resource is shared between all of them.

Changing a texture isn't modifying the Texture resource itself but swapping one resource for another. If you then modify the new texture externally the changes will be reflected once you go back to Godot in any node that uses that texture.

Duplicating or instancing does not make resources unique unless that resource has `Local To Scene` enabled.

**Comment by KoBeWi** [comment]
> To answer your question, that's not true. If you duplicate an item then change the texture, the texture changes just for that item. If you duplicate the item and change the font size, it changes all of them. That is not logical.

It IS logical. You just misunderstand what these both actions do. Changing a font size is like drawing a pixel on a texture - if you were able to do that via inspector, all Sprites using this texture would get that pixel.

And if you did my font example correctly, it does behave the same as textures. You need separate font resources - separate files. You don't keep all textures in one file, right?

**Comment by chucklepie** [comment]
So I take it other 'resources' like materials are the same?

I guess the problem is knowing when you duplicate/inherit you need to understand the difference between when a property is changed and when a resource is changed and knowing that resources are shared across duplication/inheritance. The documentation (and the gui tutorial in the docs does not make this clear. Especially for 'duplicate' which by the word makes you assume it is a full copy of all items, not a copy with shared references.

So, I do get what you're saying, it just needs to sink in because I wasn't expecting changing a font to upstream modify a parent. Perhaps the gui/inheritance documentation could be better improved, unless this failing is just me :)

Thanks.

**Comment by RantingBob** [comment]
So...there currently is a bool that allows you to duplicate and make a unique copy by setting subresources to true, but I think that only goes one level deep.

That is to say in the following tree:

Reference -> Resource -> Resource -> Resource

duplicate makes a new reference pointing to Resource
duplicate(true) makes a new reference pointing to a copy of the first resource, but the second and third resource are still the same.

Would you consider adding a second flag, defaulting to false, that is recursive, so duplicate(true, true) would duplicate all the resources right down to the bottom, without breaking the current contract?

**Comment by Calinou** [comment]
@RantingBob At this point, I think it'd be better to break compatibility (we can do it for 4.0) and use an enum to specify the duplication mode instead.

**Comment by RantingBob** [comment]
Is there anyway I can help?

**Comment by Calinou** [comment]
@RantingBob Right now, it might be better to focus on improving the documentation. You could [contribute to the class reference](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html) or [edit one of the documentation pages](https://github.com/godotengine/godot-docs) where it would make sense to clarify this.

**Comment by RantingBob** [comment]
I've added a note to the documentation, but it turns out thats not an easy sentence to write.

**Comment by RantingBob** [comment]
@Calinou I added  two pull requests.  One to update the RST file, one the XML.  I'm not sure which needed changing, but figured one was probably generated from the other.  Let me know which one to kill.

**Comment by RantingBob** [comment]
...and another attempt. https://github.com/godotengine/godot/pull/40210

**Comment by akien-mga** [comment]
Fixed by #40210.

**Comment by Mietzsche81** [comment]
Tacking onto this thread since I've been very confused by this very same issue in `v3.2.2.stable.official`. I would very much like to be able to duplicate the whole resource tree for some resources.

@Calinou what do you propose for an enum? A single option flag `{THIS, CHILDREN, ALL_SUBS}`? A packed bitset of combinable options?

**Comment by Calinou** [comment]
@Mietzsche81 I think an enum is a better way to go about it, as it's easier to reason about (especially for people less knowledgeable with bitmasks).

**Comment by lukostello** [comment]
this only allows duplicating the sub resources during the resource.duplicate() not the node.duplicate() right?
