### ISSUE TITLE
Sometimes when Collision2D is disabled/enabled, the collision appears to act the opposite of its state

### ISSUE THREAD

**Issue by SbNanduri** [godotengine/godot#30383]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 64bit

**Issue description:**

In my game, I disable and enable collisionshapes to open and close doors. Sometimes, when I enable a collisionshape it still acts disabled even though it appears enabled when viewing collisionshapes. In this gif, the player character's hitbox is the capsule shape at the bottom of his sprite and he just passes right through the wall. 
Currently I've fixed the issue by yielding 1 frame when updating the hitboxes.

![CollisionBug](https://user-images.githubusercontent.com/39013190/60758791-542de100-9fe9-11e9-92f5-ba29abe73699.gif)

**Steps to reproduce:**
When trying to reproduce this bug, I found the opposite problem where the collisionshape looks disabled but it is still enabled. This was caused by disabling the collisionshape using a signal from an area2d

**Minimal reproduction project:**
When I this kinematicbody2d passes through this area2d, the area2d sends a signal that's supposed to disable the collisionshape. It looks disabled but it still collides with the kinematicbody2d.

![CollisionBug2](https://user-images.githubusercontent.com/39013190/60758871-59d7f680-9fea-11e9-80e2-f19441f5b38c.gif)

Here's a zip file with the project
[Test.zip](https://github.com/godotengine/godot/files/3364854/Test.zip)

**Comment by avencherus** [comment]
I think as it is, when disabling shapes from code it has to be done with a `call_deferred`.

**Comment by SbNanduri** [comment]
> I think as it is, when disabling shapes from code it has to be done with a `call_deferred`.

Oh, so I'd just use the set_disabled() method with call_deferred. That makes a lot of sense, thank you!

**Comment by KoBeWi** [comment]
Godot already warns about disabling shapes in some cases. Maybe it should check more cases where it might lead to unexpected results.

**Comment by ondesic** [comment]
Why is disabled even allowed in shape code.  I see that an error is in the error list, but it doesn't crash the game to bring your attention to it.  In the documentation it simply says "a disabled shape has no effect in the world."  
If you turn on Debug | Visible Collision Shapes, you can see the shapes.  Godot will will turn the shape gray if by code you disable it, the same as if you disable it in the inspector.

Intuitively coding `myShape.disabled = true` should do the same as the inspector IMO

**Comment by KoBeWi** [comment]
The reason why you have to use `set_deferred` is that the change needs to be synchronized with the PhysicsServer. Otherwise you might e.g. try to change the state when physics state is locked and it fails. The error is clear and even documentation mentions this now, so closing. If you think the behavior should be changed, [open a proposal](https://github.com/godotengine/godot-proposals).
