### ISSUE TITLE
Incorrect unused_class_variable error.

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30393]
**Godot version:**

3.1

**Issue description:**

```
onready var _LEFT_TOP: MarginContainer = $"Left/Top"
onready var _LEFT_MID: MarginContainer = $"Left/Middle"
onready var _LEFT_BOT: MarginContainer = $"Left/Bottom"
onready var _MIDDLE_TOP: MarginContainer = $"Middle/Top"
onready var _MIDDLE_MID: MarginContainer = $"Middle/Middle"
onready var _MIDDLE_BOT: MarginContainer = $"Middle/Bottom"
onready var _RIGHT_TOP: MarginContainer = $"Right/Top"
onready var _RIGHT_MID: MarginContainer = $"Right/Middle"
onready var _RIGHT_BOT: MarginContainer = $"Right/Bottom"
onready var _slots: Array = [
		[_LEFT_TOP, _LEFT_MID, _LEFT_BOT],
		[_MIDDLE_TOP, _MIDDLE_MID, _MIDDLE_BOT],
		[_RIGHT_TOP, _RIGHT_MID, _RIGHT_BOT]
		]
```
Creates 9 unused-class_variable warnings. Using a variable in the declaration of another should count as using it. I could circumvent this by fetching the nodes in the array itself, but that would be more of a hassle to work with, and does not allow type validation.

**Comment by Anutrix** [comment]
Can't reproduce in latest master https://github.com/godotengine/godot/commit/44db85d6f61e410c35a91db580166d9296fda77a. Can someone confirm.

**Comment by KoBeWi** [comment]
Yeah, the warnings appear in 3.1, but not in master. Thanks for testing.
