### ISSUE TITLE
http_unescape() in GDScript can't unescape a string escaped by http_escape

### ISSUE THREAD

**Issue by Larpon** [godotengine/godot#30409]
**Godot version:**
v3.2.dev.custom_build.e6a0076f0

**OS/device including version:**
Linux Kubuntu 18.04

**Issue description:**
While updating the docs for `http_unescape` I found that `String.http_unescape` is broken in the following snippets of code.

**Steps to reproduce:**
```gdscript
var escaped = "https://example.org/?e="+"Godot Engine:'docs'".http_escape()
	print( escaped ) # Correctly encodes https://example.org/?e=Godot%20Engine%3A%27docs%27 
	print( escaped.http_unescape() ) # Wrongly cuts output at 'Godot' ...
	print( "https://example.org/?e=Godot_Engine%3A%27docs%27".http_unescape() ) # Prints 'Unicode error: invalid skip'
```

**Minimal reproduction project:**
[bug_http_unescape.zip](https://github.com/godotengine/godot/files/3365788/bug_http_unescape.zip)

**Comment by Anutrix** [comment]
Couldn't reproduce the issue on latest master https://github.com/godotengine/godot/commit/1fa26b969c296ca62462debf01c22e2cc0aa059e on Windows 10 1903.
![Capture51](https://user-images.githubusercontent.com/11459028/60770629-b88c9580-a0fa-11e9-931a-6f9bada0fcc8.PNG)
Isn't this how it should look?

**Comment by Larpon** [comment]
@Anutrix yup that's indeed how it should look - here's output from a fresh build from 1fa26b9 on my Linux host:
![image](https://user-images.githubusercontent.com/768942/60770688-38f0cd80-a0de-11e9-8655-50c430c86d7d.png)
So might be a Linux specific thing

**Comment by Anutrix** [comment]
Related to #30396.

**Comment by Faless** [comment]
@Anutrix I really don't think it's related

**Comment by Faless** [comment]
I can't reproduce this in current master with Ubuntu 18.04.

Output seems fine:
```
https://example.org/?e=Godot%20Engine%3A%27docs%27
https://example.org/?e=Godot Engine:'docs'
https://example.org/?e=Godot_Engine:'docs'
```

**Comment by Larpon** [comment]
Strangely in 3bfffcc (things are moving fast! :sweat_smile: ) the output now has changed to giving the `Invalid skip` error on both unescapes:
![image](https://user-images.githubusercontent.com/768942/60803208-00530180-a17b-11e9-8d64-21aa96de7fdf.png)

Additional info:
* It's not only in Godot's console output - but also in the terminal running the process.
* I'm building using `llvm`/`clang` (command: `scons platform=x11 use_llvm=yes -j5 platform=x11 tools=yes`)

**Comment by Anutrix** [comment]
Test on gcc once.

**Comment by bojidar-bg** [comment]
I built 3bfffcc568d87342e867f95c35a4a19e09072189 with clang, but could not reproduce. Arch Linux, x86_64.

**Comment by Faless** [comment]
I can reproduce when building with clang:
```
clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
but not with GCC. Weird...

**Comment by Anutrix** [comment]
I kinda had a hunch it was compiler related when I saw https://github.com/godotengine/godot/blob/56269e2db835e50a4cf2681bb73c44ae41fcca10/core/ustring.cpp#L3321-L3325.

**Comment by Anutrix** [comment]
I kinda had a hunch that it's compiler-related when I saw https://github.com/godotengine/godot/blob/56269e2db835e50a4cf2681bb73c44ae41fcca10/core/ustring.cpp#L3321-L3325

**Comment by Faless** [comment]
This was actually caused by passing a bogus argument to `strtol` (which apparently at least GCC fixed automatically knowing the array length)

**Comment by Larpon** [comment]
Thanks for looking into it and fixing it!
