### ISSUE TITLE
Improvements add 3d objects on 2d scene 

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30400]
Could the engine add a feature about 3d objects add to 2d scene. like some simbols like stars, crystles and so on. It can rotation, move and scale look like in 3d space. But the most things created based on Node2d.

**Comment by KoBeWi** [comment]
You can already achieve this with viewports.

**Comment by clayjohn** [comment]
As KoBeWi pointed out, this is already possible. There is an example of how to do it in the demo repository here https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_in_2d

**Comment by zszen** [comment]
> As KoBeWi pointed out, this is already possible. There is an example of how to do it in the demo repository here https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_in_2d

thank you
