### ISSUE TITLE
HSlider misbehaving with analog input

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#30402]
**Godot version:**
3.1.1-stable

**OS/device including version:**
Windows 10

**Issue description:**
When mapping analog gamepad input to `ui_left` and `ui_right`, HSlider interprets all movements as "to the left". Other controls seem to respect it.

**Steps to reproduce:**
Run MRP, connect gamepad, move left stick to the right.

**Minimal reproduction project:**
https://github.com/lekoder/godot-issue-hslider-analog

**Comment by KoBeWi** [comment]
VSlider seems to have this problem too.

**Comment by Anutrix** [comment]
Couldn't reproduce on MAXJoypad emulator. It's working fine on it.

**Comment by lekoder** [comment]
Original report made using XBox360 physical controller.
