### ISSUE TITLE
Crash on rigidbody enter_shape with a set_contact_monitor(false) call

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#3041]
I'm trying to disable collision for the player on enemy hit with this code on enter body
```
func _on_body_enter_shape( body_id, body, body_shape, local_shape ):
	self.set_contact_monitor(false)
```
This causes a crash for some reason, looking for debug dump on godot source code, the method who crash called by the player is:
```
void RigidBody2D::_body_inout(int p_status, ObjectID p_instance, int p_body_shape,int p_local_shape) 
```
It seems to be a problem with enter collision, disable on enter contact monitor and for some reason godot call exit collision and crash, maybe add a check for contact monitor bool here?.

video from the issue:
https://gfycat.com/LegitimateThunderousBorderterrier

Here is the simple demo from video which reproduce the problem and you could trace with debug:
https://dl.dropboxusercontent.com/s/ktv2ltlufr9v19c/bug_collision.zip?dl=0

Tested with the last compiled godot from git today Dec 10, 2015 (https://github.com/godotengine/godot/commit/3b68f0d051ac33a95e78025622c5f93219591da9)

So, I don't know if this is a bug or is the intended behaviour and if I should use another simple alternative for disable/enable ALL rigidbody collisions on player respawn/death animation?

**Comment by reduz** [comment]
if it's from a singal it should at least throw an error before crashing
(though i think it was not supposed to crash)
you can always do

call_deferred("set_contact_monitor",false)

and it will work

**Comment by HeartoLazor** [comment]
Thanks for your reply, with deferred works, but always crash if I close the window after the collision with deferred call, so leaves the game unstable, tested with the demo. Also for what I understand from deferred methods, those are asynchronous, so the object could collide with another objects on the window of true > false?
On the console doesn't print anything weird or errors, also I tried disconnect signals on enter before the set_contact_monitor and the bug persist.
Screenshot from the console: http://vgy.me/zYU8GP.png
The complete code on the demo uploaded to reproduce the bug is so simple:

```
extends RigidBody2D

func _ready():
	pass

func _on_bug_body_enter_shape( body_id, body, body_shape, local_shape ):
	self.set_contact_monitor(false)
```
And with the godot source code is easy to track where the error is.
