### ISSUE TITLE
GoDot crashes after building and then the project wont open again

### ISSUE THREAD

**Issue by xXrandomryzeXx** [godotengine/godot#30420]
Okay, for the past few days i've been searching for an answer for my problem but none of which i find have the same problem like me. The issue is that when i make a project, add my player and add code to him, when i compile it asks me to select the main scene, but right after i selec it, GoDot crashes. After i open GoDot and then open my project, it opens, BUT right after that windows says that GoDot is not responding and there isnt an option to wait and i can only close the app. Well if i make a new project it doesn't have this problem. Now okay, right now i am on a holiday and im using an old laptop but i managed to update the drivers and when making a project i select the opengl 2.0 instead of 3.0 because only that seemed to load in the first place.
Also i get an error in the console which might be a bit of the cause:

`ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
At: drivars/gles3/rasterizer_scene_gles3.cpp:5037`

And that error is shown in the console for like 20- 30 times i can say.

When loading the scene i get 2 more errors:
![image](https://user-images.githubusercontent.com/29554645/60788086-84e65580-a164-11e9-91ce-8f084bbcbcdb.png)

i have no problems with the editor until i compile. Finaly when the project loads and i get the warning that Godot Engine editor stopped working i get this message in the console:
![image](https://user-images.githubusercontent.com/29554645/60788233-df7fb180-a164-11e9-9612-a9a923a90c3d.png)

i read it, but i hav no idea where to look for the fix.

OKAY I still havent posted this but it might be because i dont have the Mono SDK or the visual studio build tools.

[EDIT]: Okay this seems to doesnt work or i will have to run something with the Mono? Tought i found that Godot wont crash if the code cant compile but right after that it does. I will try out the other option.

Godot version: Latest  of this date 08.07.2019 mono 32bit

OS : Windows 7

**Comment by Anutrix** [comment]
@xXrandomryzeXx Mention the version number too when creating issues and preferably follow the github issue template. By latest, do you mean stable 3.1.1 Mono or master(self-built)?

**Comment by Anutrix** [comment]
Directional shadow framebuffer status invalid bug has been reported before. Might be similar to one of these https://github.com/godotengine/godot/search?q=directional+shadow+framebuffer&type=Issues, not sure.

**Comment by xXrandomryzeXx** [comment]
> @xXrandomryzeXx Mention the version number too when creating issues and preferably follow the github issue template. By latest, do you mean stable 3.1.1 Mono or master(self-built)?

Yeah its 3.1.1 Mono, sorry i didnt write it first time

**Comment by KoBeWi** [comment]
Maybe there's a problem with the scene you set? Sounds like it might corrupt project.godot for whatever reason.

**Comment by xXrandomryzeXx** [comment]
> Maybe there's a problem with the scene you set? Sounds like it might corrupt project.godot for whatever reason.

Well im not sure because inmy home computer i do everything the same way and i dont get the same problem.

**Comment by xXrandomryzeXx** [comment]
> Directional shadow framebuffer status invalid bug has been reported before. Might be similar to one of these https://github.com/godotengine/godot/search?q=directional+shadow+framebuffer&type=Issues, not sure.

Yeah, but if the problem is in shadows then its not something that can crash the app , running the build, right?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing.
