### ISSUE TITLE
String.insert() not working correctly

### ISSUE THREAD

**Issue by Phoenix1747** [godotengine/godot#30429]
**Godot version:**

3.1.1-stable

**OS/device including version:**

Windows 10, latest

**Issue description:**

Inserting in a string only seems to be working with a string directly instead of declaring a var first and then inserting in this var.

For example this is working:
```GDScript
var a = "12345".insert(2,"x")
print(a)
```

However, the piece of code below does not work.

**Steps to reproduce:**
This should be enough to reproduce the issue:
```GDScript
var a = "12345"
a.insert(2,"x")
print(a)
```

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
This is probably intended, but documentation doesn't clarify it properly. The method returns the resulting String, so the original one doesn't get modified.

**Comment by StraToN** [comment]
More than just a documentation question, I think this issue raises a more global programming design question.

The design choice for `String` is: all methods that modify the input string return a new `String` and do not actually modify the input. If you want to replace the input with output value, you'll need to do `a = a.insert(2, "x")`.

On the contrary, `Spatial.rotate()` does modify the input object and returns nothing.

IMHO, all methods should comply the "setter/modifier methods do modify the input and return nothing".
In terms of memory, this means 1 less variable allocation.
The "return new value" policy is sometimes considered as bad practice, or more likely a old-fashioned way. But it is really subject to personal tastes.

However, such design change will bring backwards incompatibility, so it may not happen (soon).

**Comment by Phoenix1747** [comment]
Thanks @KoBeWi, looks like I missed the return type here. Like @StraToN and you mentioned, the documentation is quite confusing IMHO.

On one hand you have functions like `String insert` that return a new string, on the other there is e.g. `void erase` that just returns nothing while doing it's job.

Anyways, I'm going to close this issue as it's only been a misunderstanding on my part, thanks!

**Comment by KoBeWi** [comment]
I'd say that documentation could be improved here. Now that I look at String docs, some methods say that they return a value and some just say about modifying string. It should be more consistent. But that's another issue probably.
