### ISSUE TITLE
Editor doesn't accept class name with dots in create script popup

### ISSUE THREAD

**Issue by Ev1lbl0w** [godotengine/godot#30427]
**Godot version:** v3.1.stable.official

**OS/device including version:** Arch Linux *(kernel 5.1.12)*

**Issue description:**
When creating a GDNative script, the editor doesn't allow me to input some characters in the *Class Name* field, like dots. But this only happens in the popup: after I input a random name and then modify the class name from the Inspector, Godot saves the field without problems and successfully runs the script.

![image](https://user-images.githubusercontent.com/6501975/60806793-dd751d00-a17b-11e9-8b45-20eb3a491d38.png)

**Steps to reproduce:**
Create a GDNative script and try to specifiy a class name with dots *(`example.text`)*. Godot won't allow to create the script, but when the script is created, it's possible to save the same class name from the Inspector

**Comment by Anutrix** [comment]
What is the intended behavior? Are dots supposed to be allowed or not?
I hope someone will answer it here.
As far as I know, most languages don't allow dots in class name. So, I think Godot follows the same.

**Comment by Ev1lbl0w** [comment]
In my case it is supposed to allow the dots, because I'm doing GDNative on the D language and using modules.

The class itself has no dots, but I need to refer to it by the full package name.
