### ISSUE TITLE
AREA_SPACE_OVERRIDE_REPLACE does not replace gravity/friction

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#3042]
As seen in Body*SW::integrate_forces, areas marked as _REPLACE do not replace current gravity/friction with their own values. Instead, they add them to the total, and stop calculating.

If this is not a desirable behavior, I propose to split _REPLACE into two constants: One that *does* replace values (and stops calculating), and other the combines values and stops (like it does now). Aditionally, a new constant could be made to replace values, but do not stop calculating.

**Comment by reduz** [comment]
what do you believe would be most useful?

**Comment by Ovnuniarchos** [comment]
I think a *true* replace is needed (how else would you do an antigravity field that overrides any other fields?). COMBINE_REPLACE would be kept to maintain compatibility.

I'm a bit more open about REPLACE_PASSTHRU (provisional name), though, but I'm always a sucker for giving options ;)

**Comment by reduz** [comment]
oh ok, feel free to do a PR then as you best think it should work :)

**Comment by Ovnuniarchos** [comment]
I'll get on it.

**Comment by Ovnuniarchos** [comment]
This issue has been resolved by #3071.
