### ISSUE TITLE
Visualshader Not Opening New Image Resource In The Inspector

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot#30430]
**Godot version:**

410cb13abdf5699bdcd6e73728c947e1e75b4cad

**OS/device including version:**

Linux mint 19.1

**Issue description:**

![Screenshot from 2019-07-08 20-47-37](https://user-images.githubusercontent.com/19777767/60815359-a7f32280-a1c1-11e9-8799-288841cc70b2.png)
Clicking the image resource (in this case the  noise texture) won't open the inspector.

**Steps to reproduce:**
- Create A texture node
- `New Noise Texture`
- Click it

**Comment by KoBeWi** [comment]
Selecting "Edit" from context menu doesn't do anything either.

**Comment by Chaosus** [comment]
Seems like one of the commit broke the preview.. I will search and fix this bug

**Comment by Chaosus** [comment]
Ah.. I confuse this with another bug  :( nvm, sorry

**Comment by fire** [comment]
Is this bug still valid?

**Comment by TritiatedWater** [comment]
It still happens to me
