### ISSUE TITLE
Renaming any file in the project reloads the current scene, loosing all modifications made to it

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#30436]
Godot 3.1.1
Windows 10 64 bits

In a scene I had saved already, I removed a script from a node by using the "Clear Script" contextual menu. The script icon disappeared, then I renamed the script from the File Explorer dock. As soon as I did that, the script icon came back on the node, with the new name.

Also I got this in the console:
```
ERROR: Another resource is loaded from path: res://chip_editor2.gd (possible cyclic resource inclusion)
   At: core/resource.cpp:79
```

Also the script editor looks like this after a few attempts:
![image](https://user-images.githubusercontent.com/1311555/60832978-2a291a00-a1b5-11e9-868f-88f1a76c8e57.png)

Edit: it's a broader issue https://github.com/godotengine/godot/issues/30436#issuecomment-511199428

**Comment by sparkart** [comment]
Seems to be related to the scene's dependencies. If you save the scene immediately after you clear the script it works fine. If you do not save the scene and then do some modifications to the files like rename, or move... it causes problems.

A solution would be to auto-save the scene after clearing/adding a script, although that might not be ideal.

**Comment by Zylann** [comment]
I renamed the issue because it's a lot worse than I thought.
If you didnt save your scene yet and rename any asset in the project, you will loose ALL changes you made to it :(

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987.

Clearing a script then renaming it in the FileSystem dock will cause the script to display with the new name in the script editor. This will also likely cause "ghost scripts" to appear in the script editor (icons with no name).
