### ISSUE TITLE
Collision between CSGPolygon and ConcavePolygonShape not working

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#30442]
**Godot version:**
3.1.1.stable

**OS/device including version:**
Windows 10. Geforce 970M

**Issue description:**
I have a RigidBody with ConcavePolygonShape for collision. I also have a CSGPolygon extruded along a path with collision activated. The RigidBody is able to collide with another StaticBody with a CubeShape but not with the CSGPolygon. Another RigidBody with a CapsuleShape is able to collide with the CSGPolygon.

**Steps to reproduce:**
1. Create a CSGPolygonextruded along a path
2. Create a RigidBody with a ConcavePolygonShape
3. The RigidBody goes through the CSGPolygon

[CSGCollisionTest.zip](https://github.com/godotengine/godot/files/3372685/CSGCollisionTest.zip)

**Comment by rhossack** [comment]
I ran into this problem with a SphereShape. I have a RigidBody with a ConcavePolygonShape that collides with RayCasts and ConvexPolygonShapes, but not SphereShapes.

The workaround was to create a convex collision sibling instead of a Trimesh collision sibling.

**Comment by pete3000a** [comment]
STILL HAPPENS IN 3.2

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by Calinou** [comment]
I believe this is expected, as RigidBodies can't use trimesh collision shapes (when using Bullet at least): https://github.com/godotengine/godot/blob/0c7c6401128a61bc2d805c4c7b400df39ffdb657/modules/bullet/rigid_body_bullet.cpp#L255

**Comment by rhossack** [comment]
> RigidBodies can't use trimesh collision shapes

Then the button that creates trimesh collision shapes should be disabled if there are RigidBodies in the current selection.

At least, that's vaguely how I remember running into the issue 2 years ago
