### ISSUE TITLE
InputEventKey echo property exported as wrong type inspector

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30446]
**Godot version:**

3.1

**Issue description:**

When editing an InputEventKey in the inspector, the `echo` property is exported with a SpinBox, even though it is a bool and should be a checkbox.

**Steps to reproduce:**
In my case: Make a Button, Add a ShortCut, add an InputEventKey. But making an InputEventKey resource directly displays the same behavior.

**Comment by KoBeWi** [comment]
Fixed in 3.2
