### ISSUE TITLE
Godot mono not log file.

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30456]
**Godot version:**
3.1 mono stable

**OS/device including version:**
Windows 10

**Issue description:**
![Screenshot_6](https://user-images.githubusercontent.com/1850856/60885116-73ca4100-a257-11e9-98a3-b54e54029965.png)
The above error happens when I try to build the project.
Although I'm pretty sure the problem is with my C# script, that is not what i am reporting. My problem is that the error log file `C:\Users\Zak\AppData\Roaming/Godot/mono/build_logs/745f45ce67d8ac69195fa551fb436f59_Tools/msbuild_log.txt` does not exist. Maybe because it uses backslash instead of slash after the %appdata% path? Strangely though, at some point, that file was created but i could not reproduce this (even tried creating the folder and the file myself).

**Comment by neikeq** [comment]
If the file does not exist, it could be some different error with MSBuild. Go to `Editor Settings > Builds` and enable `Print Build Output`, then try building again and check the command line output.

**Comment by zaksnet** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/1850856/60886053-a5dca280-a259-11e9-935f-d77c2c4e70a9.png)
Same thing. Also, checked for the log file and it still doesn't exist.

**Comment by zaksnet** [comment]
@neikeq , Changed from MSBuild (Mono) to MSBuild (VS Build tools) and the log file is being created now.

**Comment by neikeq** [comment]
I was about to recommend that. We encourage using `MSBuild (VS Build Tools)` and that's what we have defaulted to for some time (we will change to `dotnet build` once we migrate to .NET Standard).
Is there something else wrong or can this be closed now?

**Comment by zaksnet** [comment]
I think that's all, when i was using MSBuild (Mono) i couldn't see the errors also. Thank you.
