### ISSUE TITLE
Faulty "Unreachable code" warning on match statement containing a return

### ISSUE THREAD

**Issue by aburg** [godotengine/godot#30458]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Ubuntu 18.04.2 LTS

**Issue description:**
The editor throws a "Unreachable code" warning after a "match" statement that contains a single unused return. 

_I am aware that this behavior is probably not really new, but the other issues on that are closed while this type of warning still occurs._ (see #25955, #26097, #28360)

**Steps to reproduce:**
Run the following script:

```
extends Node2D

func _ready():
	var selector = 0
	match selector:
		1:
			return
	
	print("we reached the unreachable")
```

The output says:
```
** Debug Process Started **
OpenGL ES 3.0 Renderer: GeForce GTS 450/PCIe/SSE2
we reached the unreachable
```
But the editor still receives a warning:
```
W 0:00:00:0765   Unreachable code (statement after return) in function '_ready()'.
  <Source>       test.gd:9
```

**Comment by aburg** [comment]
as a workaround you can add the default case with a "pass" statement
```
_:
  pass
```

(still we should consider the warning a bug!)

**Comment by Anutrix** [comment]
Something similar to all_have_return flag logic used for if-else can be done for match too I guess.
