### ISSUE TITLE
Do not focus script editor if using external editor

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#3046]
I configured settings to use an external editor. But if I open a script, the editor still switches to the Script tab (it does not open the script there though). This can be quite annoying.

**Comment by akien-mga** [comment]
Fixed in master, but the fix needs to be backported to 2.1.

**Comment by RayKoopa** [comment]
Is this still current?

**Comment by akien-mga** [comment]
Nope, fixed in master by #6962 and in 2.1 by #12021.
