### ISSUE TITLE
Cannot debug godot with gdb/lldb

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#30464]
**Godot version:**

3.2-dev master compiled with 7f80c1dca8892cab4f4fe7a2daf6699755024f09

**OS/device including version:**

Arch Linux x64

gcc (GCC) 9.1.0
GNU gdb (GDB) 8.3

clang version 8.0.0 (tags/RELEASE_800/final)
lldb version 8.0.0

**Issue description:**

GDB and LLDB didn't work to debug godot editor any more. The program can be paused with breakpoints but got lost when step into or step over randomly.

Tested with a Qt GUI project don't have such problem.

**Steps to reproduce:**

I can't step over from L1866 to L1876 as below

* In VSCode
![Peek 2019-07-09 21-58](https://user-images.githubusercontent.com/6964556/60899590-4ef8bc80-a29d-11e9-8f49-7ee43c521d77.gif)

* In QtCreator
![Peek 2019-07-09 22-46](https://user-images.githubusercontent.com/6964556/60899604-55873400-a29d-11e9-8c58-6814e5cfc80b.gif)

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
I have exactly same behaviour with VSCode on macOS, but on completely different parts of code.

Stepping the `Main::iteration` function works ok but, for example VSCode fails to step beyond this line [main.cpp#L356](https://github.com/godotengine/godot/blob/master/main/main.cpp#L356) in `Main::setup` and falls from the function instantly.

I do not have any these problems with Qt Creator or lldb CLI.

**Comment by KoBeWi** [comment]
>GDB and LLDB didn't work to debug godot editor any more.

You mean it worked before?

**Comment by Geequlim** [comment]
@KoBeWi  Yes. They work fine two weeks ago when I debug the LSP server #29780

**Comment by Calinou** [comment]
@Geequlim Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Geequlim** [comment]
I can still reproduce this with latest gcc/gdb but clang/llvm works fine.
Just debug the editor without any project.

**Comment by akien-mga** [comment]
Is this specific to VSCode? Maybe it's a VSCode bug?

Command line `gdb` works fine for me on Linux.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this issue.
