### ISSUE TITLE
TextEdit: Typing ^- changes the write mode to "Insert"

### ISSUE THREAD

**Issue by SuzukaDev** [godotengine/godot#30477]
**Godot version:**
3.1 stable

**OS**:
Windows 7 64bit

**Issue description:**
On a **TextEdit node**, when you type **^-**  the caret changes to "insert mode" (basically, like pressing the insert key)
I made a little .gif to show the issue:
https://imgur.com/Kro75v3
(I also tried to reproduce the issue on a LineEdit node, but in LineEdit it works as expected)

**Steps to reproduce:**
- On any scene, add a TextEdit node
- Play the scene
- On a spanish keyboard, type ^- 
- (see how the write mode changed)

Note: the "^" is typed by pressing Shift+` on a Spanish Keyboard
I couldn't reproduce the error on an English keyboard, but maybe it could be reproducible in other keyboards where you need to press shift to write ^

**Comment by SuzukaDev** [comment]
It also happening when typing:
` (and) -
(without the need of pressing shift)

**Comment by SuzukaDev** [comment]
I changed the title because is not only related to a specific keyboards/language

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by SuzukaDev** [comment]
@KoBeWi Seems solved in 3.2.3.stable.official (Windows) for me!

**Comment by KoBeWi** [comment]
Closing then.
