### ISSUE TITLE
Clean up GraphEdit ports and slots

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30475]
**Godot version:**

3.1

**Issue description:**

GraphEdit and GraphNode use "slots" and "ports" interchangeably, including in the exposed API. Can we unify that to just ports? Should be a simple across the board replacement job.

**Comment by KoBeWi** [comment]
Actually, they are two different things. "Slots" are the nodes you need to add to GraphNode, while "ports" are the actual points on either side that you can connect to. Maybe this could be better clarified, but the term isn't really interchangeable.
