### ISSUE TITLE
Control get_drag_data incorrect return type

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30478]
**Godot version:**

3.1

**Issue description:**

Documentation, and in editor auto completion, suggest that `get_drag_data` of `Control` returns `Object`. This is wrong, it can return anything at all, and is typically used for variants. (Dictionary)

I'm guessing this is because there is no `-> Any` or `-> Variant` syntax. But even then, they would not allow `void`.

https://github.com/godotengine/godot/blob/master/scene/gui/control.cpp#L714 Funnily enough here it returns variant.

So this is pretty awkward? Is there even a good solution to this?

**Comment by TheDuriel** [comment]
Ridicules solution:

Add `-> Any`. Add `can_get_drag_data`, like we have `can_drop_data`. This would mean `get_drag_data` no longer needs to be able to return void. And could return `Any`.

**Comment by Calinou** [comment]
> Add `-> Any`.

See also https://github.com/godotengine/godot/issues/26228.

**Comment by KoBeWi** [comment]
Doc is fixed in 3.2, but autocompletion still doesn't add `-> Variant`.

**Comment by KoBeWi** [comment]
Fixed.
