### ISSUE TITLE
Godot hides the error text after the crashed game is closed

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#30471]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
ArchLinux

**Issue description:**
When my game crashes, Godot displays the error in the debugger, but when I close the crashed game to reduce the lag a bit, the error suddenly disappears.. This is really irritating, and was bothering me for a long time.

![godot-bug-not-showing-errors](https://user-images.githubusercontent.com/25486263/60918180-574ff800-a29b-11e9-91d3-302884e157fb.gif)

P.S. don't mind that Godot doesn't take focus after the error, something's wrong with my desktop environment

**Comment by KoBeWi** [comment]
Still valid in fea72f2

**Comment by KoBeWi** [comment]
The stack trace is cleared now and the error is replaced with a message.
![Image](https://github.com/user-attachments/assets/dce38e48-0e67-4a85-b121-710ab7f2046f)
It does not look like a bug anymore.
