### ISSUE TITLE
LineEdit and SpinBox drag data handling

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30480]
**Godot version:**

3.1

**Issue description:**

LineEdit:

It is impossible to implement can_drop_data and get_drop_data. Since LineEdit already does this.
If your drop data is a string, it will "correctly" insert it into the current text.
However if it is any other type, nothing at all happens and none of the drag_data functions are called.

Furthermore, since SpinBox, instances a LineEdit node. It is possible to insert strings into the field. (Which later gets validated and removed.)

https://github.com/godotengine/godot/commit/2d84ec5468ea0f88b2df5e5f8ae257f72288aa9d

This commit is meant to forward mouse events from the SpinBoxs LineEdit node, to the spinbox. However, this does not include Drag data. Making it impossible to implement drag and drop into SpinBox nodes. (You _can_ drag the data into the SpinBox buttons.)

I imagine this (not the commit, but the general behavior) is also partially responsible for https://github.com/godotengine/godot/issues/30479 .

**Comment by TheDuriel** [comment]
![image](https://user-images.githubusercontent.com/44248915/60936586-dcec9b80-a2cd-11e9-91e5-240a17e5e2a6.png)

Windows handles this quite gracefully? We should probably reject text input for SpinBox nodes.

**Comment by KoBeWi** [comment]
> Making it impossible to implement drag and drop into SpinBox nodes.

Well, it is possible actually. The LineEdit of SpinBox is available using `get_child()` method. You can use `set_script()` on the LineEdit to attach a script that will forward the drag methods to SpinBox. It's a bit tricky, but solving this on C++ side would be a bit tricky too. Not sure it this issue can be considered a bug.

**Comment by akien-mga** [comment]
Partly fixed by #44349.
