### ISSUE TITLE
AnimationPlayer cannot insert key for Node2D property

### ISSUE THREAD

**Issue by dantofei** [godotengine/godot#30495]
**Godot version:**
3.2.dev.custom_build. 5e495750a37e3314a8cd85cb3f7be9a676420c44

**OS/device including version:**
Xubuntu 19.04

**Issue description:**
Cannot insert key for `Node2D:position` property for a Sprite Node using right-click on the timeline.
Trying to insert key throws error: 
```
 core/undo_redo.cpp:296 - Error calling method from signal 'track_insert_key': 'Animation::track_insert_key': Method expected 3 arguments, but called with 2.
```

With `Auto Insert Keys`  enabled I was able to add animation keys to the timeline by moving the sprite node.

**Steps to reproduce:**

1. Create Sprite Node
2. Add AnimationPlayer Node to Sprite Node
3. Create new animation
4. Add `Node2D:position` property track from Sprite Node/Node2D
5. Right-click on timeline and insert key

**Minimal reproduction project:**
[MinimalTestProject.zip](https://github.com/godotengine/godot/files/3378535/MinimalTestProject.zip)

**Comment by KoBeWi** [comment]
Works correctly in stable.
