### ISSUE TITLE
Engine singletons portability issues

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#30496]
This issue lists the current problems regarding Engine singletons and the ClassDB API portability. The purpose of this issue is to try to find a solution for these problems.

Before starting, I will describe the rules for registering Engine singletons while respecting API portability. Any Engine singleton that breaks any of these rules will at best cause an API hash mismatch, which is already bad enough for the mono module.

1. The class **must** be exposed to the scripting API (`ClassDB::register_class`). _(Otherwise only GDScript would be able to use it, and that is only because right now GDScript doesn't check whether a class is exposed or not)._
2. Exposed classes **must** be exposed on ALL platforms. _This applies to Engine singletons as they must be exposed. The class can be replaced with a dummy one on unsupported platforms._
3. The class **must not** be exposed only on builds with **tools disabled**.
4. The class **may** be exposed only on builds with **tools enabled** if it's exposed as part of the Editor API (`ClassDB::current_api` at the time it is registered).

However, there's currently a problem that prevents the last rule (`4`) from working properly. The class `VisualScriptEngineSingleton` [has a property](https://github.com/godotengine/godot/blob/1abe12f5bb869605646797e043db88bb3d428e62/modules/visual_script/visual_script_nodes.cpp#L1953-L1966) to select between the list of Engine singletons. This doesn't differentiate between singletons exposed as part of the Core and Editor APIs, so the hint string will variate between builds with tools enabled and disabled. This is important because hint strings [are considered when calculating the API hash](https://github.com/godotengine/godot/blob/1abe12f5bb869605646797e043db88bb3d428e62/core/class_db.cpp#L496).
I'm not sure how to properly solve this problem. We could simply check if the class is part of the Editor API before adding it to the hint string, but that would mean Editor-only singletons like `NavigationMeshGenerator` will not be selectable and that may be a problem.

Having made all that clear, I'm listing the current singletons that are causing API portability issues:

- `JavaClassWrapper` is added as a Engine singleton only on Android; this breaks rule `2`. The class `JavaClassWrapper` is not even exposed to the scripting API via `register_class`, breaking rule `1`.

- `NavigationMeshGenerator` is added as an Engine singleton only on builds with tools enabled. This is actually fine as `NavigationMeshGenerator` is exposed to the Editor scripting API, adhering to rule `4`. However, as described above, rule `4` is not working right now because of the `VisualScriptEngineSingleton` problem.

The `JavaClassWrapper` issue can be fixed easily. Just make sure to expose the class to the scripting API (`register_class`) and add it as an Engine singleton, both on all platforms. On non-Android platforms, a dummy class would be used. The reason I haven't done this is because it would need to be moved from its current location at `platforms/android/` to somewhere else, and I'm uncertain where the new location should be.

I don't know what to do about the `VisualScriptEngineSingleton` issue.

**Comment by neikeq** [comment]
cc @reduz Maybe you have a suggestion.

**Comment by neikeq** [comment]
Here's an example of how the `VisualScriptEngineSingleton`'s property hint string differs between builds. The first is from a desktop tools build, the second is from an android non-tools build (export template).

```diff
-"hint_string": "Performance,ProjectSettings,IP,Geometry,ResourceLoader,ResourceSaver,OS,Engine,ClassDB,Marshalls,TranslationServer,Input,InputMap,JSON,JavaScript,GodotSharp,NavigationMeshGenerator",
+"hint_string": "Performance,JavaClassWrapper,ProjectSettings,IP,Geometry,ResourceLoader,ResourceSaver,OS,Engine,ClassDB,Marshalls,TranslationServer,Input,InputMap,JSON,JavaScript,GodotSharp",
```

Notice how the desktop tools build includes `NavigationMeshGenerator` while the android non-tools build doesn't, and how the android build includes `JavaClassWrapper` while the desktop build doesn't.

**Comment by bojidar-bg** [comment]
I think it might be possible to write `VisualScriptEngineSingleton`'s property hint in `_validate_property`. Maybe the one that is registered in `_bind_methods` could then include only non-editor singletons.

**Comment by neikeq** [comment]
@bojidar-bg Interesting, doing it in `_validate_property` may actually work.
