### ISSUE TITLE
Engine freezes very often

### ISSUE THREAD

**Issue by Altair1234** [godotengine/godot#30523]
Version 3.1
Issue present in both GLES 2 and 3.

8gb DDR3 RAM, i5 6200u, AMD Radeon m430

Regular freezes. While opening Godot, opening a project, loading a scene, saving, writing new code, and playing the scene.

Hard to tell minimum steps to reproduce. Noticed freezes after importing a gltf file. [Was following this tutorial](https://www.youtube.com/watch?v=XMfiojwtuKo)

This was the second gltf I imported. My specs being a problem is improbable as it ran Unity and Unreal fine.

**Comment by creikey** [comment]
I was unable to reproduce this issue with 16gb DDR4 RAM, a Ryzen 5, and a gtx 1060 ti, and an SSD. I was able to use two of the GLTF assets provided in the tutorial to create a simple scene that is attached with no freezes whatsoever. Do you have a mechanical hard drive or a solid state drive?

[download my example project](https://gofile.io/?c=NXlcEm)

**Comment by Altair1234** [comment]
Here's [my project](https://gofile.io/?c=sRF7tS)
I have an HDD but that shouldn't be a problem, right?

**Comment by creikey** [comment]
@Altair1234 I was unable to download your project, it said that the upload didn't exist. HDDs are significantly slower than solid state drives in terms of random file read performance, and I remember godot and most applications having lag spikes when reading from a file when I had one. Because the gtlf files provided by the tutorial are up to 37 megabytes in size, you can expect some freezing whenever Godot has to poll that file.

**Comment by Altair1234** [comment]
Wait, I can't download either project. And as I said, it happens when I edit other stuff (like scripts) as well.

**Comment by creikey** [comment]
Seems like gofile is just broken. Here is a new link that has my project zip: [link](https://filebin.net/sgozx6rymzrmh913)

**Comment by Altair1234** [comment]
[Here's my project.](https://filebin.net/sgozx6rymzrmh913) Please take a look and tell me if I screwed up somewhere.

**Comment by KoBeWi** [comment]
The file is gone again xd

Check again if it happens in the newest 3.2 beta and if it does, upload the project directly to GitHub (drag and drop into text box) to make sure it doesn't disappear anymore.

**Comment by akien-mga** [comment]
It's impossible to debug as is sadly, there's not even information on the user's operating system.

**Comment by Altair1234** [comment]
Windows 10. Sorry I couldn't reply sooner. I'll try again tomorrow morning with the latest build, although some people mention it being super slow at the point so maybe I just didn't wait long enough. However, 2+ hours for a single task, even on my potato, shouldn't be normal behaviour.
