### ISSUE TITLE
Lines smoothing has been broken in GLES2

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#30535]
**Godot version:**
https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987

**OS/device including version:**
Win10

**Issue description:**

![image](https://user-images.githubusercontent.com/3036176/61126010-0404c200-a4b4-11e9-9b59-ea99847f0d44.png)

**Comment by akien-mga** [comment]
Possibly a regression from #30521.

**Comment by Calinou** [comment]
It's working on commit https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987 here:

![image](https://user-images.githubusercontent.com/180032/61129206-2f87ac80-a4b4-11e9-846b-0a7508eb4d99.png)

Note that line antialiasing has only been implemented in the GLES3 renderer. Therefore, if you use the GLES2 renderer in a project, line antialiasing will also be disabled in the editor.

**Comment by Chaosus** [comment]
Aww.. it is true, sorry , false alarm

**Comment by Calinou** [comment]
Here's a [pull request](https://github.com/godotengine/godot/pull/30540) implementing line antialiasing in GLES2 :slightly_smiling_face:

**Comment by Chaosus** [comment]
Lol ) then it will be fixed
