### ISSUE TITLE
Splash screen show gray-black colour in ios

### ISSUE THREAD

**Issue by ATOshailesh** [godotengine/godot#30533]
**Godot version:**
Godot 3.1

**OS/device including version:**
IOS iPhone 6s 11.4

**Issue description:**

When open app then show gray-black colour in splash screen.
first display white screen image it's added in xcode LaunchImage assets,
after display grey-black colour,
then display godot boot splash  image.

So, how can i remove grey-black colour?
 
**Steps to reproduce:**
In godot editor:
- set image : project/project settings/ : Application/boot splash/image
- export project for ios.

**Comment by ATOshailesh** [comment]
Any update for this issues?

**Comment by Calinou** [comment]
@ATOshailesh Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
