### ISSUE TITLE
Incorrect dynamic value for exported NodePath after reparenting in Editor

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#30534]
I believe this is a bug in the implementation of #9801

**Godot version:**

3.1.1.stable.custom_build

**OS/device including version:**

Linux

**Issue description:**

When reparenting an object that exports a `NodePath` in the editor, the `NodePath` updates dynamically, but can end up pointing to a nonexistent path.

**Steps to reproduce:**

`Parent.tscn`:

```
Parent (path : NodePath = './Child')
|
| - Child
```

--- 

`World.tscn`:
```
World
|
| - SubWorld1
| | - Parent (path : NodePath = './Child')
| - SubWorld2
| |
```

Drag Parent to SubWorld2:

```
World
|
| - SubWorld1
| |
| - SubWorld2
| | -  Parent (path : NodePath = './Child')
```

Drag Parent back to SubWorld1:

```
World
|
| - SubWorld1
| | -  Parent (path : NodePath = '../../SubWorld2/Parent/Child')
| - SubWorld2
| |
```

Note that the path now incorrect.

![out](https://user-images.githubusercontent.com/2496231/61124469-f7ad4480-a474-11e9-8baf-5898deb4139d.gif)

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/3386197/example.zip)

**Comment by akien-mga** [comment]
> I believe this is a bug in the implementation of #23989

I guess you meant to link another PR? That one doesn't seem related.

**Comment by rcorre** [comment]
> I guess you meant to link another PR?

#9801, sorry. Autocomplete was being really stubborn :grin:

**Comment by Gastronok** [comment]
I'm not sure if it's the same root bug, but I'm experiencing similar undesirable behavior. If I've got the following scene tree:

| Level
| + Ball (Scene)
|    + Sprite
|    + CustomScript (NodePath: "../Sprite"

then I load another instance of the Ball Scene, I end up with:

| Level
| + Ball (Scene)
|    + Sprite
|    + CustomScript (NodePath: "../Sprite"
| + Ball 2
|    + Sprite
|    + CustomScript (NodePath: "../../Ball/Sprite")

I'm not sure if it's intended behavior or not but it does seem to make it impossible to have a scene with a relative exported NodePath point to that scene's nodes when loading more copies at runtime.
