### ISSUE TITLE
Export headless/server projects

### ISSUE THREAD

**Issue by MarkuBu** [godotengine/godot#30531]
I want to develop a client/server application and I miss the feature to export a headless project to a single executable. If I export a simple project with just a node an as script that just prints a message to the CLI there is still a viewport window that opens automatically

I know that I can run a server from the project files, but to distribute the game it would be better to have a stand alone executable.

I suggest to add an option to export a server project without graphic dependencies.

**Comment by Calinou** [comment]
As a workaround, you can export a project for Linux/X11 then run it using a server binary:

```text
./godot_server --main-pack my_project.pck
```

Note that the PCK file will still include textures and sounds. Adding a specific Server export preset that strips textures and sounds from the PCK is planned.

**Comment by MarkuBu** [comment]
Ok, I missed the --main-pack option. I already tried to run the pck file with the server, but just get error messages.

But there is still one downside. It might happen that the pck file is incompatible with the Godot version. The best way will be an all inclusive package.

Thanks for the workaround

**Comment by Calinou** [comment]
> I already tried to run the pck file with the server, but just get error messages.

Can you paste the error messages here, please?

**Comment by MarkuBu** [comment]
If I run the same package with the --main-pack option everything works fine

```
godot_server test.pck 
ERROR: _load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:285.
ERROR: start: Condition ' !scene ' is true. returned: false
   At: main/main.cpp:1739.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2095.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425.
ERROR: cleanup: Condition ' allocs_used > 0 ' is true.
   At: core/pool_vector.cpp:70.

```

**Comment by Calinou** [comment]
@MarkuBu The positional command-line argument (i.e. argument without a flag) should refer to a scene file, which is meant to run scenes directly. This is mainly used for debugging.

We could make it accept PCK/ZIP files as well (based on the file extension or something like that).

**Comment by MarkuBu** [comment]
Sounds good to me as workaround

**Comment by chiguireitor** [comment]
Have you tried using a linux export with a custom "template" using the server binary? that should work

**Comment by shintiger** [comment]
I had a simular issue about server export template, unlike other export target, I don't have example export presets or exported binary location should place on
