### ISSUE TITLE
Default values != null show broken in editor docs

### ISSUE THREAD

**Issue by DavidSichma** [godotengine/godot#30537]
**Godot version:**

Master, built from 0b69be91d56e8983877ec5a48c219cf28a741903

**OS/device including version:**
Windows

**Issue description:**
Some default values will occupy an area way too large and overlap with other text.
This appears to only happen if the default value is not null ~and has many sub-properties~(There is an empty Dictionary in RegexMatch that is broken as well). Most of these properties are of type Dictionary, but I have also seen some Objects.

![packed_scene_text_overlap](https://user-images.githubusercontent.com/25692790/61129766-6a3e1480-a4b5-11e9-964c-b46015c39c56.png)

**Where this issue occurs:**

- Image/data
- PackedScene/_bundled
- Path/curve
- Path2D/curve
- Many properties in ProjectSettings. It's the worst here.
- Some other places

**Additional info:**
I remember reading that every newline in the xml-files used to generate the editor docs will result in a new paragraph. Every instance of this bug I investigated so far spans multiple lines.

**Comment by akien-mga** [comment]
CC @bojidar-bg
