### ISSUE TITLE
Scaling down texture cause artifact

### ISSUE THREAD

**Issue by Mugiwara00** [godotengine/godot#30545]
Godot Version 3.1

I have a 4096x4096 texture, I change its size file to 512. When I use the tilable texture (for a wall) there is a line. So there seems to be an issue when scaling texture.

**Steps to reproduce:**
Create a 4096 tilable asset, change its size file to 512 in import. use it on a wall/floor, and see a line where the tile ends. the smaller to put the size file the bigger the line.

**Minimal reproduction project:**
Dont have one atm. But a screenshot to show the line, its the vertical line in the center.
![image](https://user-images.githubusercontent.com/22804788/61153199-898a7100-a4b8-11e9-9928-eee919a7d6b6.png)

**Comment by Calinou** [comment]
Can you reproduce this if you set the texture compression mode to **Lossless** instead of **Video RAM**? To do so, select the texture in the **FileSystem** dock, then go to the **Import** dock, change the texture compression mode then click **Reimport**.

**Comment by Mugiwara00** [comment]
yes, I've tried lots of those settings, mipmaps, premute alpha, lossless, and it kept happening, only way I was able to fix it, was to change my texture to a 512 (cause then it didnt scale)

**Comment by Calinou** [comment]
@Mugiwara00 Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

We absolutely need a minimal reproduction project here.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
