### ISSUE TITLE
Change mouse cursor when moving guide lines

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30550]
**Godot version:**

3.1

**OS/device including version:**

Windows 7

**Issue description:**

When adding or removing GuideLines in the scene editor the cursor currently retains its default appearance. This makes it unclear as to when you are grabbing a guide, and under which circumstances they are movable.

The cursor should change to a up/down left/right slider to indicate that a guideline is grab and movable.

Removing a guideline currently requires you to hold ctrl, and drag the guideline from the _rulers_ in the editor. But i only found out by randomly holding modifier keys and grabbing at random places.

![image](https://user-images.githubusercontent.com/44248915/61163566-0b0cee00-a50f-11e9-85c1-6b67e26baad8.png)
Example of me holding ctrl at the correct spot.
Turns out for some reason my cursor is not in the screenshot xD Imagine it being on top of the purple line and the ruler.

**Comment by Calinou** [comment]
> Removing a guideline currently requires you to hold ctrl,

I don't need to hold Ctrl to remove a guideline on https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987. I can just drag it to the "square" at the top-left of the 2D viewport.

I agree with the rest of the suggestsions though.
