### ISSUE TITLE
FPS drop on Empty project  when clicking mouse button

### ISSUE THREAD

**Issue by miblooming** [godotengine/godot#30553]
**Godot version:**

Godot Engine 3.1.1

**OS/device including version:**

Microsoft Windows 10.0.17763.379
OpenGL ES 3.0
GeForce GTX 1050/PCIe/SSE2

**Issue description:**

FPS drop

**Steps to reproduce:**
1.Create a new project
2.Create a new tscn
3.Run the empty project
4.Open the tab on the middle bottom of editor: Debugger-> Monitors
5.Click on the game window by Mouse Button(left or right)
6.FPS drop to about 50  frequently
![fps_drop_on_click_mouse_button](https://user-images.githubusercontent.com/2108904/61170032-69c97a80-a596-11e9-8c2d-0a96ac7819c2.png)

This problem occur on my desktop PC:
Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
12.0 GB DDR3 1600 MHz
GeForce GTX 1050/PCIe/SSE2

But NOT occur on my laptop PC:
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
8.0 GB 2133 MHz
NVIDIA GeForce MX150

**Minimal reproduction project:**

**Comment by miblooming** [comment]
It's not an issue about that demo. 
In my game project, I meet with the FPS Drop problem.
And I test the Demo of Godot. The same problem appeares.

**Comment by Calinou** [comment]
@miblooming Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

Also, make sure your graphics drivers are up-to-date.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
