### ISSUE TITLE
Crash when reimporting a different sound file with same name

### ISSUE THREAD

**Issue by urusuru** [godotengine/godot#30559]
**Godot version:**
3.1.1

**OS/device including version:**
Windows.

**Issue description:**
When you import the same sound again (update sound) and you try to play it crashes engine.

**Steps to reproduce:**
Import sound with a specific name.
Play it in engine.
Reimport, same name, different sound.
Play again.

**Minimal reproduction project:**

**Comment by SonerSound** [comment]
I'll take it! Hopefully I can have this in less than a month, if all goes right.

**Comment by creikey** [comment]
@SonerSound Are you still working on this issue?

**Comment by SonerSound** [comment]
@creikey Yes, however I've not pushed anything to my fork unfortunately. Work hasn't helped in the slightest as well.

**Comment by Anutrix** [comment]
I tried it. Godot crashed even before trying to play it.

**Comment by volzhs** [comment]
can't reproduce it with a0ce88f953
editor does not crash.

**Comment by Anutrix** [comment]
Wish we knew which commit fixed.

**Comment by KoBeWi** [comment]
I can confirm this in 3.2 beta6.

You need to use the built-in audio player (the one in the bottom of the inspector when you double-click audio asset). Play it, change the file and the resource will reimport, but the player will not refresh. Trying to double-click the asset again to refresh the player will freeze the editor.

Seems to happen only with OGG files.

**Comment by akien-mga** [comment]
Duplicate of #26964.
