### ISSUE TITLE
Node paths and signals.

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30555]
Unless there is a better way to do this that i don't know of, using Node paths is messy because usually when the path changes, you have to change the whole code to correspond to the changes. I could store the node within an `onready var` and only change this `var` when i change the tree (which is what i'm doing for non-important nodes), but still, i would prefer if i didn't have to make any changes when i move nodes around.  Currently, i am overcoming this by connecting the `ready()` signal of the node to its owner and also sending the node id along with the signal.
 Example: 
`connect("ready", self.owner, "_home_button_ready", [self])`
and then saving the returned value:
```
var home_button
func _home_button_ready(p_which):
    home_button = p_which
```
That way i know my script will never break because of a wrong path. But that involves adding a script at the `home_button` which makes it inefficient so i am only doing it for nodes that i change all the time. My suggestions are the following on the subject:

- Add more types in the "Add extra call argument" dialog, it currently only supports static types.
![Screenshot_12](https://user-images.githubusercontent.com/1850856/61168355-b50f6900-a555-11e9-98c7-d0424ca45b37.png)

- Currently "Node" signals don't send any data along with them. Maybe add the node path as a parameter to them? I'm not sure if that would break compatibility though.

- Maybe there could be another connection mechanism (not a signal) that will create a variable with the node path instead of a function.

- Simply being able to trace which node called a signal would also solve this.

I will be looking to see if i can do this myself, in the meantime let me know if i have missed something.

EDIT: This seemed insignificant at first but as the project grows the need for something like that becomes more obvious.

**Comment by KoBeWi** [comment]
> adding a script at the home_button which makes it inefficient

If your script has literally one method called from a signal, it doesn't have much impact. Even less if you make it built-in.

**Comment by zaksnet** [comment]
I feel stupid, but believe it or not, i had not noticed the `Build-in` option so far :flushed:! This will probably ease my workflow a lot, thank you @KoBeWi ! As far as this issue is concerned, i still think it would be nice if this was integrated in some way. I'll leave it open until i figure out if there is something i can do (or feel free to close it yourself).

**Comment by zaksnet** [comment]
Although `Build-in` scrips are nice to keep the project folders clean, i already had to create more than 50 of them just to address the above issue so it became frustrating fast. I'm not advanced enough yet to address this myself, for now I'll just work around it.
