### ISSUE TITLE
Auto-open screenshot option does not working (on Windows)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#30554]
**Godot version:**
https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987

**OS/device including version:**
Win10

**Issue description:**
Screenshots are saved but does not open if that option is enabled

![image](https://user-images.githubusercontent.com/3036176/61167909-e2581900-a54d-11e9-9eaa-b0c0487c9307.png)

I dont know whether its also doesnt work on other platforms..

**Comment by qarmin** [comment]
It works on Ubuntu, but it is strange that it save screenshots in project data instead pictures folder

**Comment by TheDuriel** [comment]
I'd rather not have images put in my documents folders. I told iFire they should go into Godots app data dir, which is save to write to anyways, instead of the project. But eh.

Note that this option lets the OS decide what to open the image with. Do you have a default .png application set?

Calling out @fire you wrote this stuff.

**Comment by Chaosus** [comment]
> Do you have a default .png application set?

Paint.Net.. However it doesn't matter - even if the user does not have a default app - the dialog with options should appear. Its purely a path bug.

**Comment by Chaosus** [comment]
This option also increases the option bar menu which makes it ugly : /

**Comment by fire** [comment]
What happens if you go to the png and open it directly from the file explorer?

If nothing happens, then it is opening in the default image editor. Which is nothing.. We're using the operating system's open, since there is no way to know where the Paint.Net executable is.

**Comment by Chaosus** [comment]
> If nothing happens, then it is opening in the default image editor.

Its opens in the Paint.Net

**Comment by fire** [comment]
What happens when you type `explorer C:\Users\fire\Desktop\path_to_png.png`? Change the path to png file.

**Comment by Chaosus** [comment]
Correctly opens in Paint.Net

**Comment by Calinou** [comment]
> This option also increases the option bar menu which makes it ugly : /

The option should probably be moved to the Editor Settings.

**Comment by fire** [comment]
Weird, when I tested this screenshots goes to "C:\Users\fire\AppData\Roaming\Godot\app_userdata\VRM compatibility"

but sometimes the screenshot is saved to "C:\Users\fire\Documents\VRM compatibility".

**Comment by Calinou** [comment]
@Chaosus Is this issue still relevant in the current `master` branch?

**Comment by Chaosus** [comment]
Yeah, its still not opening even if the checkbox is toggled

**Comment by sparkart** [comment]
This is working for me.
Version: 3.2.alpha.custom_build.aa06f515e
Windows 10

**Comment by Chaosus** [comment]
Ah, it's really working for embedded photo viewer in Windows 10 - but not Paint.NET, but I think its that app problem and not Godot. Closed.
