### ISSUE TITLE
Add a built-in function for lerping angle

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#30564]
Similar to Unity's [Mathf.LerpAngle](https://docs.unity3d.com/ScriptReference/Mathf.LerpAngle.html).
This is my implementation in GDScript:

```
static func lerp_angle(from, to, weight):
    return from + _short_angle_dist(from, to) * weight

static func _short_angle_dist(from, to):
    var max_angle = PI * 2
    var difference = fmod(to - from, max_angle)
    return fmod(2 * difference, max_angle) - difference
```

**Comment by Xrayez** [comment]
This would be really useful to have indeed. Here's some simplified/optimized version:
```gdscript
static func lerp_angle(from, to, weight):
	var difference = fmod(to - from, TAU)
	var short_angle_dist = fmod(2 * difference, TAU) - difference
	return from + short_angle_dist * weight
```

**Comment by Chaosus** [comment]
@Xrayez Are you sure that its correct algorithm ? In Unity 

`Mathf.LerpAngle(0.0, 90.0, 1.0) // == 90`

while in your proposal

`lerp_angle(0.0, 90.0, 1.0) // == 116`

**Comment by DleanJeans** [comment]
It's the same with my implementation. The function expects angles in radians not in degrees.

**Comment by Xrayez** [comment]
Ninja'd by @DleanJeans so writing an example now. 🙂 

```gdscript
var angle_rad = deg2rad(90.0) # PI / 2
var interpolated = lerp_angle(0.0, angle_rad, 1.0)
print(rad2deg(interpolated)) # 90
```

**Comment by Chaosus** [comment]
And why you change it to radians when in Unity its in degrees ?

**Comment by Xrayez** [comment]
It makes sense to me to work in radians because many (Godot) math functions expect angles to be in radians already:
```gdscript
Vector2.rotated(radians)
var radians = Vector2.angle_to_point(Vector2)
var radians = sin(radians)
```
Those functions that expect degrees are often exposed directly in the engine's editor to make it easier to work with from user side and are converted to radians to be used internally anyway:
```c++

void Node2D::set_rotation_degrees(float p_degrees) {

	set_rotation(Math::deg2rad(p_degrees));
}
```
So built-in GDScript functions should work in radians.

**Comment by DleanJeans** [comment]
@Chaosus:
> And why you change it to radians when in Unity its in degrees ?

I based it off a gist I found on GitHub. The link to Unity docs is just to simply explain it and to show that Unity has it then we should have it builted in too (though the real reason is that I saw on many occasions people asking about lerping angles in Godot).

**Comment by Chaosus** [comment]
@Xrayez for some reason it produce a negative values eg. 

`print(str(rad2deg(lerp_angle2(deg2rad(0), deg2rad(180), 1.0)))) # produces -180`

while in Unity 

`print(Mathf.LerpAngle(0.0f, 180.0f, 1.0f)); // produces 180`

If you fix or explain why this happens, I can create PR with your changes and add you as co-author

**Comment by DleanJeans** [comment]
`180` and `-180` are the same thing. I think it doesn't make any difference.

**Comment by Chaosus** [comment]
Alright then..

**Comment by Xrayez** [comment]
Ideally even if the shortest angles are "equal" as in [0, 180], [0 -180] (minus would take counter-clockwise rotation), the rotation should take the route of the same sign, but lerping angle is mostly done for smoothing so this difference is not as important I think. Might be related to how `fmod` works internally there.

`print(str(rad2deg(Utils.lerp_angle(deg2rad(0), deg2rad(-180), 1.0))))` also gives -180, so lets say it yields consistent results at least. The unit circle takes angles [counter-clockwise](https://en.wikipedia.org/wiki/Unit_circle#/media/File:Unitycircle-complex.gif) according to my trigonometry knowledge.

**Comment by Xrayez** [comment]
@Chaosus I translated this initially to C++ but then stopped, feel free to add this if you haven't already:
```cpp
	static _ALWAYS_INLINE_ double lerp_angle(double p_from, double p_to, double p_weight) {
		double diff = fmod(to - from, Math_TAU);
		double shortest = fmod(2.0 * diff, Math_TAU) - diff;
		return from + shortest * weight;
	}
	static _ALWAYS_INLINE_ float lerp_angle(float p_from, float p_to, float p_weight) {
		float difference = fmod(to - from, Math_TAU);
		float shortest = fmod(2.0f * difference, Math_TAU) - difference;
		return from + shortest * weight;
	}
```

**Comment by Chaosus** [comment]
`wrapf `can be used instead fmod then, its supports negative wrapping..

**Comment by Lisoveliy** [comment]
I think i am blinded but i can't found it on C#. Can you add it please?

**Comment by Chaosus** [comment]
> I think i am blinded but i can't found it on C#. Can you add it please?

`Mathf.LerpAngle`

**Comment by Lisoveliy** [comment]
> > I think i am blinded but i can't found it on C#. Can you add it please?
> 
> `Mathf.LerpAngle`

Thanks, Dude!
