### ISSUE TITLE
"Simulated motion mode" in StaticBody docs doesn't exist.

### ISSUE THREAD

**Issue by asheraryam** [godotengine/godot#30560]
**Godot version:**
Latest master branch.

**OS/device including version:**
Windows 10.

**Issue description:**
The "simulated motion" referred to in the docs doesn't seem to actually exist.
https://docs.godotengine.org/en/latest/classes/class_staticbody.html#description
https://imgur.com/yBK5BAx

 I also looked in the C++ code and couldn't find anything either.

I also found this other mention of simulated motion in KinematicBody but I haven't looked into it further.
https://docs.godotengine.org/ko/latest/classes/class_kinematicbody.html#description

**Comment by asheraryam** [comment]
Is this a duplicate of https://github.com/godotengine/godot/issues/17531

**Comment by eiszfuchs** [comment]
Yeah, is it a duplicate? Would like to know, too.

**Comment by Calinou** [comment]
@eiszfuchs No, #17531 is about the constant velocity properties not working when using Bullet physics.

**Comment by eiszfuchs** [comment]
I see. Was wondering because both issues stumble over the same now-gone documentation fragment.
Thanks!
