### ISSUE TITLE
No audio output latency option in project settings when using WASAPI

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#30562]
3.1.1 and 3.2

Although noted here: https://docs.godotengine.org/en/3.1/classes/class_projectsettings.html?highlight=latency#class-projectsettings-property-audio-output-latency
There is no option in the project settings to change the audio latency. 
Also, placing the option manually into the project.godot file allows the option to show up, but changing it does not change the audio output latency.

Here, the documentation talks about changing the size of audio buffers with the audio latency option in project settings : https://docs.godotengine.org/en/latest/tutorials/audio/sync_with_audio.html
"Audio is mixed in chunks (not continuously), depending on the size of audio buffers used (check latency in project settings)."

-I know that this sync_with_audio documentation is specifically for 3.2, but even in 3.2 there is no audio latency option in project settings, and also does not effect latency. In fact, 3.2 does not output latency correctly at the moment; neither in debug monitor nor Performance.get_monitor(Performance.AUDIO_OUTPUT_LATENCY); it shows 0 constantly.

Is there actually way to change the buffer size/audio output latency?

**Comment by Calinou** [comment]
On a newly-created project using 584ca0f156cec64c259382895e105cf27566a987, I see an **Audio -> Output Latency** setting in the Project Settings:

![image](https://user-images.githubusercontent.com/180032/61174907-190e4d80-a5a7-11e9-99e8-a737fd50ed39.png)

**Comment by JustYourAverageJosh** [comment]
Hmmm, I am still not able to see that with a new project using 584ca0f15, downloaded from here: https://hugo.pro/projects/godot-builds/

**Comment by Calinou** [comment]
It seems audio latency isn't configurable on all audio drivers. Due to how the setting is implemented, the project setting will only be visible if you're currently using an audio driver which supports tweaking the output latency:

![image](https://user-images.githubusercontent.com/180032/61175309-52e25280-a5ad-11e9-88a3-6743a3f1949f.png)

Most importantly, `drivers/wasapi` (the default audio driver on Windows) is missing from this list.

**Comment by JustYourAverageJosh** [comment]
Oh ok thanks for clearing that up! I will look into changing my audio driver, but hopefully in the future it will be clear either in documentation or in the audio setting itself (maybe a greyed out option that explains why you can't change it). Do you know what drivers are able to change latency? Possibly is there a documented list for all operating systems? as I would like to change it for Android as well.

**Comment by Calinou** [comment]
@JustYourAverageJosh See the screenshot I posted for the list of audio drivers that support adjusting the output latency.

There's only one audio driver available on Android. On Windows, only WASAPI is available by default, but XAudio2 can be enabled by recompiling Godot with `xaudio2=yes` on the SCons command line. (I don't know if it's still working though.)

**Comment by akien-mga** [comment]
Looking at the WASAPI audio driver, it looks like we have no control on the size of the audio buffer/latency, which is likely why the setting isn't exposed.

Still, this should be changed to ensure that the setting is always defined, even if unused on WASAPI. Right now it makes it difficult to change audio latency from Windows for non-Windows exports, and the setting is removed from the docs when running `doctool` on Windows.

**Comment by akien-mga** [comment]
CC @marcelofg55

**Comment by joseloc300** [comment]
i might be wrong here but isn't the buffer size related to latency? if so it says it should be possible to adjust it (adjust buffer size)

https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/low-latency-audio#windows_audio_session_api_wasapi

**Comment by Calinou** [comment]
@joseloc300 According to that page, adjusting the buffer latency is only supported on Windows 10, so we'd need to conditionally check whether the user is running Windows 10 or not.

**Comment by joseloc300** [comment]
@Calinou is checking for that bad? is just that seems that for WASAPI would be preferable to have the option on Win10 rather than never having it
