### ISSUE TITLE
sampleplayer controls cover help buttons

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#3056]
Go into the script tab, where you can see the "Tutorials", "Classes", and "Search Help" buttons.  Select a SamplePlayer in the scene tree, and its play, stop, and sample library controls will be on top of the help buttons.

**Comment by reduz** [comment]
fixing in 2.1, need to remake those windows

**Comment by TheHX** [comment]
This issue still valid? Since this editor was [disabled](https://github.com/godotengine/godot/blob/master/tools/editor/editor_node.cpp#L6456):

**Comment by vnen** [comment]
Indeed, the SampleLibrary controls are used to play/stop in editor now, so this not valid anymore.
