### ISSUE TITLE
get_available_packet_count on PacketPeerStream

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3057]
Why is "get_available_packet_count()" always 0 when I send data from java to godot?

Reading data without "get_available_packet_count()" slows godot down.

Example client and java server
https://github.com/AlexHolly/godot-tcp-issue

**Comment by reduz** [comment]
because if you use the packetpeer api, you have to send data to Godot in a
format it understands. Here's how to send variant packets to godot:
https://github.com/godotengine/godot/wiki/binary_Serialization

**Comment by AlexHolly** [comment]
Okay now it works thanks, it feels a bit slow but the reason could be my implementation.
