### ISSUE TITLE
After dragging something in the 2D editor, the cursor shape doesn't change until the cursor is moved

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#30582]
**Godot version:** Git https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987

**OS/device including version:** Fedora 30, NVIDIA 430.26

**Issue description:** After finishing a dragging operation in the 2D editor, the mouse cursor shape will only change once the cursor is moved again.

**Steps to reproduce:** Drag a node in the 2D editor, release the left mouse button but don't move the move. The cursor will still use the "dragging" shape until you move it.

**Minimal reproduction project:** N/A (can be reproduced in any project)

**Comment by sparkart** [comment]
I wasn't able to reproduce the issue.
**Godot version:** [584ca0f](https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987)

**OS/device including version:** Windows 10/Razerblade Pro 2014

**Comment by Calinou** [comment]
@sparkart I tested this on Windows and couldn't reproduce it there as well, so I'll assume this is issue Linux-specific.

**Comment by Calinou** [comment]
I can still reproduce this on commit https://github.com/godotengine/godot/commit/7a62b94bcae4da685144ce11aa6f1c8ad19b7c71.

**Comment by akien-mga** [comment]
#58913 is being reverted temporarily, but let's keep this one closed and treat it as a duplicate of #45936 (same root cause).
