### ISSUE TITLE
Add support of non-breaking spaces in Label nodes

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#30580]
**Godot version:**
Godot 3.1.1

**Issue description:**
In my current project I need to use [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) in my `Label` nodes, but as I understand, Godot doesn't support them?
The spaces appear, but the line still breaks on them.

**Steps to reproduce:**
1. Create a Label node.
2. Enable `autowrap`
3. Type a sentence with a lot of words, but instead of normal spaces use non-breaking spaces.
4. Line still breaks on the spaces

**Comment by Calinou** [comment]
I can't reproduce this on commit https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987.

**Demo project:** [test_nbsp.zip](https://github.com/godotengine/godot/files/3389932/test_nbsp.zip)

In order of appearance, normal spaces, non-breaking space, thin non-breaking space, [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space):

![image](https://user-images.githubusercontent.com/180032/61184470-83c69400-a64e-11e9-833e-21e8ed485eab.png)

Note that thin non-breaking spaces won't display with the default project font, but it will work with most custom fonts.

**Comment by PonasKovas** [comment]
Oh... I don't know why, but when I copied the non-breaking space from the wikipedia, it didn't work, but when I copied it from your project it now works...

Sorry for bothering...
