### ISSUE TITLE
LineEdit's clear_button_enabled makes the cursor work not as expected when alignment is not to the left

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#30599]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Arch Linux

**Issue description:**
When I enable LineEdit's property `clear_button_enabled`, the cursor starts functioning not properly. When I click on the text, the caret moves not where I clicked, but a bit to the left from there. This only happens when `clear_button_enabled` is enabled.

![ezgif-1-3c97369fef3d](https://user-images.githubusercontent.com/25486263/61239353-5ad5fa00-a747-11e9-8ce4-3136e98a27db.gif)

**Steps to reproduce:**
1. Create a LineEdit node
2. Enable `clear_button_enabled`
3. Try clicking on the text written in it

**Comment by BeLuckyDaf** [comment]
Could not reproduce this bug on Windows 10 (Godot 3.1.1), so I guess this is a Linux only problem. Although, I think there is a tiny offset issue, that is, one or two pixels to the right, it is perhaps not related to `clear_button_enabled`.

**Comment by YeldhamDev** [comment]
This only happens when the alignment is centered, and still happens in master efd5563.
