### ISSUE TITLE
Add Half Offset for hexgonal GridMap

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#30593]
**Godot version:** 3.1

Half Offset is missing from `GridMap` whereas `TileMap` supports this.

**Comment by Ramshell** [comment]
It would be excellent to have this!

**Comment by Calinou** [comment]
@Ramshell Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by Tolkinder** [comment]
You can set GridMap size.x/z to .5 and size.z/x to .866 [sin(pi/3)]. This will allow you to place tiles that align, but does make double the grid positions actually needed.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4386, as feature proposals are now tracked on the Godot proposals repository.
