### ISSUE TITLE
Editor doc properties misaligned

### ISSUE THREAD

**Issue by DavidSichma** [godotengine/godot#30592]
**Godot version:**

Master built from 7e27da54d8ac3cacd7ecdcb8cdf009d76702ed69
Does not appear in official 3.1.1 stable

**OS/device including version:**
Windows 10

**Issue description:**
The property type is placed two pixels below the property name.
![cant_unsee](https://user-images.githubusercontent.com/25692790/61211613-4fabab80-a700-11e9-85a0-96fbfd4486e9.PNG)
I can't unsee this.

Only happens in the "Properties:" section. Everything else (even "Property Descriptions:") looks aligned.

**Comment by akien-mga** [comment]
CC @bojidar-bg
