### ISSUE TITLE
Cull limit is set to 65556 - is this intentional?

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#30597]
Hello

I'm experiencing an issue detailed in this video with instancing a member of your community pointed out that this code is hard limited by the engine and I was wondering if it could be raised in the engine or if there is a reason it is so low?

Video: https://www.youtube.com/watch?v=nFtq_ANakWg

The limitation appears to be here:
https://github.com/godotengine/godot/blob/803544052a6d0aca73e7b3c4b7c3a9c5ee9707d8/servers/visual/visual_server_scene.h#L47

Godot engine: 3.1.1.

**Comment by Calinou** [comment]
For the record, this limit can't be lifted until 4.0. The documentation for 3.2.x was updated in https://github.com/godotengine/godot/pull/44435.
