### ISSUE TITLE
Allow configuration of buffer size for WebRTC

### ISSUE THREAD

**Issue by TheDevelo** [godotengine/godot#30605]
**Godot version:**
v3.2.dev.custom_build.2c6daf73f

While trying to receive payloads of over 64 KiBs in size over WebRTC, the following error is printed in console:
```
ERROR: Buffer full! Dropping data
   At: modules/webrtc/webrtc_data_channel_js.cpp:73
```

To fix this issue, I resized the in_buffer to 2 MiBs by recompiling the engine, but that's not ideal.
A similar issue was encountered with Websockets (#22496), and that was fixed by allowing configuration of the buffer size in Project Settings. A similar solution would be nice for WebRTC.

**Comment by akien-mga** [comment]
CC @Faless
