### ISSUE TITLE
32 bit GDScript memory performance is 15-20x slower than 64 bit

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#30606]
**Godot version:**
3.1.1-stable

**OS/device including version:**
Windows 10 1903

**Issue description:**
GDScript memory performance is heavily affected by whether or not it's running in 64 bits.
Slowdown occurs both in the 32 bit editor and in exported builds.
![image](https://user-images.githubusercontent.com/5272529/61259117-6bce3d80-a73e-11e9-8f1f-c8f37ad47b44.png)
Left to right: 64 bit, 32 bit

**Steps to reproduce:**
Run this line in both 32 and 64 bit versions of Godot and compare the time it takes:
`range(10000000)`

**Minimal reproduction project:**
[32-64 Performance Test.zip](https://github.com/godotengine/godot/files/3395368/32-64.Performance.Test.zip)

**Comment by kruglinski** [comment]
use valgrind to analysis which function cost the most of time

**Comment by toasteater** [comment]
In case you didn't know, there're no iterators in GDScript and `range` returns an actual array. I'd be curious how much of the runtime was allocating and filling those `10000000` numbers. The speed difference may be due to auto-vectorization.

**Comment by hunte922** [comment]
> 
> 
> In case you didn't know, there're no iterators in GDScript and `range` returns an actual array. I'd be curious how much of the runtime was allocating and filling those `10000000` numbers. The speed difference may be due to auto-vectorization.

Oh. That's helpful. I'll update the issue.

**Comment by aaronfranke** [comment]
GDScript ints and floats are both 64-bit data types, which can be slow on 32-bit CPUs. Additionally, 64-bit CPUs have more instruction sets than 32-bit ones. There is probably a bug with this high amount of performance degradation, but do note that you shouldn't expect parity.

**Comment by hoontee** [comment]
Fixed by #40598. 32-bit and 64-bit timings are now 0.5 and 0.6 seconds, respectively.

Though, it's an overall increase over the original 64-bit timings. Oh well.
