### ISSUE TITLE
Metadata in tscn format

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3060]
The tscn format is already way VCS-friendlier than the XML format, so that's a big improvements.
The two remaining issues IMO are:
 - random reordering of external resources upon save (#2495)
 - editor-specific metadata that are saved to the tscn and change very often (whether on 2D or script screen, camera offset, etc.). This issue is about this point.

Here's what I get in a simple 2D tscn scene (as a one-liner, but I split it for readability):
```
__meta__ = {
	"__editor_plugin_screen__":"2D",
	"__editor_plugin_states__":{ 
		"2D":{ 
			"ofs":Vector2( -166.143, -66.5586 ),
			"snap_grid":true, 
			"snap_offset":Vector2( 0, 0 ), 
			"snap_pixel":false, 
			"snap_relative":false, 
			"snap_rotation":false, 
			"snap_rotation_offset":0, 
			"snap_rotation_step":0.261799, 
			"snap_show_grid":false, 
			"snap_step":Vector2( 16, 16 ), 
			"zoom":0.814506 }, 
		"3D":{ 
			"ambient_light_color":Color( 0.15, 0.15, 0.15, 1 ), 
			"default_light":true, 
			"default_srgb":false, 
			"deflight_rot_x":0.942478, 
			"deflight_rot_y":0.628319, 
			"fov":45, 
			"show_grid":true, 
			"show_origin":true, 
			"viewport_mode":1, 
			"viewports":[ 
				{ "distance":4, "listener":true, "pos":Vector3( 0, 0, 0 ), "use_environment":false, "use_orthogonal":false, "x_rot":0, "y_rot":0 },
				{ "distance":4, "listener":false, "pos":Vector3( 0, 0, 0 ), "use_environment":false, "use_orthogonal":false, "x_rot":0, "y_rot":0 },
				{ "distance":4, "listener":false, "pos":Vector3( 0, 0, 0 ), "use_environment":false, "use_orthogonal":false, "x_rot":0, "y_rot":0 },
				{ "distance":4, "listener":false, "pos":Vector3( 0, 0, 0 ), "use_environment":false, "use_orthogonal":false, "x_rot":0, "y_rot":0 } ],
			"zfar":500,
			"znear":0.1 },
		"Anim":{
			"visible":false } },
	"__editor_run_settings__":{
		"custom_args":"-l $scene",
		"run_mode":0 } }
```
I'll put some thoughts in a later comment on how these metadata could be made more VCS friendly.

**Comment by akien-mga** [comment]
To make things better VCS-wise, the main idea is that the diffs between two commits should be as little as possible.

1. Currently with everything as a oneliner, the metadata are changed at basically every diff, so splitting them e.g. as shown above would make things better (if "__editor_plugin_states__/3D/fov" is changed, only this line would be changed, and it would also be easy to understand in the diff).

2. If the oneliner is split as shown above, it starts to be a bit long, which was probably the motivation to make it a oneliner. This could be improved by not saving all the metadata that have default values.  My scene is 2D only, and I never used the 3D screen, so I don't need any of the 3D metadata which basically all have default values. The metadata should be written only when different from the default values.

3. Some metadata should not be saved in the scene, as they change basically all the time and are not so relevant to have under version control:
  - ```__editor_plugin_screen__```: we don't need to save if the last screen viewed was 2D or script. Of course there's the question of how to know if the default scene to open should be 2D or 3D... An alternative could be to keep this parameter, but just handle 2D and 3D and ignore Script.
  - ```__editor_plugin_states__/2D```: ```ofs``` and ```zoom``` should not be saved in the scene file, they also change all the time. Snapping parameters on the other hand should not change often, so it's meaningful to save them IMO.
  - ```__editor_plugin_states__/3D```: don't have much experience here, maybe someone used to the 3D edition could comment?
  - ```__editor_plugin_states__/Anim```: if it's only about the ```visible``` state, it should be dropped too IMO. It's easy enough to bring up the animation panel by clicking the animation node, it doesn't have to be saved (I tend to close it each time I open a scene and it shows up by default personally...)
  - ```__editor_run_settings__```: Not sure what those do?

**Comment by reduz** [comment]
ah yeah.. editor metadata must be moved outside the project

**Comment by akien-mga** [comment]
That's an alternative yes :)

**Comment by reduz** [comment]
this is done, metadata should all be gone

**Comment by akien-mga** [comment]
There seems to still be one piece of metadata saved: https://github.com/KOBUGE-Games/project-kumquat/blob/fccc7a622e65cbc7a5592a07fbb0c33b5ca8e85c/levels/level.tscn#L11
```__meta__ = { "__editor_plugin_screen__":"2D" }```
This one is IMO the most important to get rid of version control-wise, as it changes basically all the time, it just depends whether you pressed Ctrl+S while looking at the script of the 2D screen.

IMO it might be useful to keep the distinction 2D vs 3D using a meta argument (i.e. whether the scene should open by default the 2D plugin screen or the 3D one?), but maybe we could simply ignore the Script screen?
Then when saving the scene on the 2D screen, it would define ```"__editor_plugin_screen__":"2D"```, on the 3D screen it would define ```"__editor_plugin_screen__":"3D"``` (just like it does now), but on the Script screen it would keep the previous definition (2D or 3D). WDYT?

**Comment by eska014** [comment]
Agree, this `__meta__ = { "__editor_plugin_screen__":"2D" }` is annoying

Maybe just use the scene root node type to determine initial view?
I don't really care for this in the first place, I'd rather do an extra click than make version control more complicated

**Comment by akien-mga** [comment]
Let's open a new issue for that, it will be clearer.
