### ISSUE TITLE
Tilemap edge artifacts in Editor

### ISSUE THREAD

**Issue by paulmasri** [godotengine/godot#30619]
**Godot version:** 3.1.1
**OS/device including version:** MacOS 10.14.4 (Graphics Intel HD Graphics 6000 1536MB)

**Issue description:**
In the Tilemap Editor, there are sometimes horizontal or vertical artifacts at the boundary between some tiles. Like many others reporting similar issues, I had initially imported my tileset image with Filter on. However the issue remains (intermittently) even after reimporting with Filter off.

Examples below. Github doesn't accept .mov so these are converted to gif but the interlacing makes them less clear - sorry.

**Example 1: import filter on; there are artifacts when scrolling or zooming, but no artifacts when immediately after clicking (1) (zoom 100%) button**

![screencast-edge-artifacts-in-editor](https://user-images.githubusercontent.com/496858/61294406-a3d09180-a7cd-11e9-8af5-4dceb8f74046.gif)

**Example 2: import filter off, but there are artifacts when zooming**

![screencast-edge-artifacts-in-editor-reimport-filter-off](https://user-images.githubusercontent.com/496858/61294611-1e011600-a7ce-11e9-8a05-3970c907fd85.gif)

**Comment by clayjohn** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
