### ISSUE TITLE
Add custom properties to controls

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30614]
I would like to add a custom font color for `button` class when they are in `Focused` state but i can't find any obvious way on how to do this.
![Screenshot_13](https://user-images.githubusercontent.com/1850856/61283395-ba72ea80-a7c5-11e9-8a7c-a6aa8cb9c23e.png)

I have also searched the source code of `base_button`, `button`, `control`, `object` classes but i can't find where these properties are being added. I'm guessing they are part of the default theme but i can't seem to be able to figure out where this is located.

**Comment by Calinou** [comment]
Custom theme properties are not script properties per se, but they are added using the following methods:

- `add_color_override()` (Color)
- `add_constant_override()` (int)
- `add_font_override()` (Font)
- `add_icon_override()` (Texture)
- `add_shader_override()` (Shader)
- `add_stylebox_override()` (StyleBox)

See the [Control class documentation](https://docs.godotengine.org/en/latest/classes/class_control.html) for more information.

**Comment by zaksnet** [comment]
> Custom theme properties are not script properties per se, but they are added using the following methods:
> 
> * `add_color_override()` (Color)
> * `add_constant_override()` (int)
> * `add_font_override()` (Font)
> * `add_icon_override()` (Texture)
> * `add_shader_override()` (Shader)
> * `add_stylebox_override()` (StyleBox)
> 
> To remove a constant, set its value to `null` (or `0` for integer constants).
> 
> See the [Control class documentation](https://docs.godotengine.org/en/latest/classes/class_control.html) for more information.

@Calinou Cool! But I'm talking about the predefined custom properties themselves, not their values. Turns out they re being set inside default_theme.cpp.
