### ISSUE TITLE
Trackpad usability in Windows/Linux and spacebar panning issues.

### ISSUE THREAD

**Issue by MissKraya** [godotengine/godot#30615]
Godot Version: 3.1.1.stable
Device: Dell XPS15 9570
OS: Windows 10

Horizontal scrolling doesn't work in-editor and in-application it is not pleasant. 

In macOS on my old Macbook Air in the 2d and 3d viewport we can pan/orbit using two fingers on the trackpad and pinch to zoom. This is perfect for using the editor on the go and I never feel the need for a mouse however I recently switched my daily driver to windows for more power.

My windows trackpad (windows precision) supports this behavior as tested by zooming in and panning in a web browser. However inside the Godot editor vertical scrolling zooms into the 2d viewport instead of panning up (pinch zooming also works so why have the same thing mapped twice?) and horizontal scrolling is not being used at all, it does however work in the GraphEdit node in the standalone but the sensitivity is insanely high.

As I don't have a scroll button on my trackpad my only options are to use spacebar to pan around or using the mouse to drag the scrollbars which feels clunky. Unfortunately the spacebar panning isn't a valid option because most trackpad drivers disable the trackpad when typing as a sort of "palm rejection". On top of this mouse wrapping doesn't work when using space bar panning, as tested on my desktop also. I can make a separate issue for this if requested.

I have been informed that this is an issue on Ubuntu too but I cant confirm. I really think that windows should use use the same behavior as the macOS editor, I understand that there are a lot of poor windows trackpads but almost all of them support horizontal scrolling and pinch zooming, possibly we could make it an editor option to disable it?

**Comment by MissKraya** [comment]
If horizontal panning in this way isn't supported I'd be happy with a right click panning option in the 2d viewport as that currently isn't used and is more comfortable on desktop and easy to make use of on a touchpad.

**Comment by MissKraya** [comment]
It's worth mentioning that windows precision trackpad drivers actually do support scrolling on both axises at once like a macbook.

**Comment by Calinou** [comment]
Since we don't use the right mouse button for anything yet, why not make panning work with both middle and right mouse buttons?

**Comment by akien-mga** [comment]
@MissKraya What do you think of proposed changes in #30713?

**Comment by MissKraya** [comment]
Sounds perfect and solves my issue! Thanks to bojidar-bg!
