### ISSUE TITLE
Crash when opening inherited scenes in tscn format

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3062]
Creating an inherited scene based on my scenes/towers/tower1.tscn scene in https://github.com/KOBUGE-Games/project-kumquat works fine, but then Godot crashes when trying to load the saved inherited scene (checkout this commit to reproduce: 239764d).

I get this error:
```
ERROR: get_dependencies: res://scenes/towers/tower2.tscn:5 - Parse Error: Unexpected end of file
   At: scene/resources/scene_format_text.cpp:606.
```

With this content saved in the inherited scene:
```
[gd_scene load_steps=2 format=1]

[ext_resource path="res://scenes/towers/tower1.tscn" type="PackedScene" id=1]

[node name="tower" instance=ExtResource( 1 )]

linear_damp = 0.1
damage = 5

[node name="attack_timer" parent="."]

wait_time = 0.2
```

Saving the base scene in XML to then create an XML-formatted inherited scene works fine, so it's a tscn parsing issue.

To reproduce:
- Clone https://github.com/KOBUGE-Games/project-kumquat
- Run ```git checkout 239764d```
- Open the project and click "New Inherited Scene"
- Select "scenes/towers/tower1.tscn"
- Save it as "scenes/towers/tower2.tscn", and close it.
- Try to reopen the inherited scene, and see the crash.

**Comment by akien-mga** [comment]
Note that the linear_damp, damage and wait_time variables above were _not modified_ before saving the inherited scene. If I remove them from the text file, the inherited scene actually opens fine, i.e. this works:

```
[gd_scene load_steps=2 format=1]

[ext_resource path="res://scenes/towers/tower1.tscn" type="PackedScene" id=1]

[node name="tower" instance=ExtResource( 1 )]
```

**Comment by akien-mga** [comment]
Note that I reverted my tower scene to xscn format for the time being to be able to use scene inheritance, so to reproduce the bug it would be necessary to checkout this commit: https://github.com/KOBUGE-Games/project-kumquat/commit/239764d0566e3be41f279afe232dc77adcee2b40

**Comment by akien-mga** [comment]
\o/ I'll try the fix asap.

**Comment by reduz** [comment]
tscn is desgiend to save the minimum information necessary, so the parser has to do some guesswork. In this case guesswork was broken
