### ISSUE TITLE
BMP loader fails to import images

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#30629]
**Godot version:** Git https://github.com/godotengine/godot/commit/22c843b0c451a0c3d79a3b3e6af900b841c51c12

**OS/device including version:** Fedora 30, GIMP 2.10.12, ImageMagick 6.9.10 (used for BMP conversion)

**Issue description:** The BMP loader fails to load images saved from GIMP and ImageMagick:

![image](https://user-images.githubusercontent.com/180032/61325683-8b846500-a815-11e9-8511-991ca486dea1.png)

```
Unsupported bmp file: res://icon_from_gimp_16bit.bmp
core/io/image_loader.cpp:69 - Error loading image: res://icon_from_gimp_16bit.bmp
editor/editor_file_system.cpp:1786 - Error importing: res://icon_from_gimp_16bit.bmp
modules/bmp/image_loader_bmp.cpp:261 - Condition ' color_table_size == 0 ' is true. returned: ERR_BUG
core/io/image_loader.cpp:69 - Error loading image: res://icon_from_gimp_24bit.bmp
editor/editor_file_system.cpp:1786 - Error importing: res://icon_from_gimp_24bit.bmp
Unsupported bmp file: res://icon_from_gimp_32bit.bmp
core/io/image_loader.cpp:69 - Error loading image: res://icon_from_gimp_32bit.bmp
editor/editor_file_system.cpp:1786 - Error importing: res://icon_from_gimp_32bit.bmp
Unsupported bmp file: res://icon_from_imagemagick.bmp
core/io/image_loader.cpp:69 - Error loading image: res://icon_from_imagemagick.bmp
editor/editor_file_system.cpp:1786 - Error importing: res://icon_from_imagemagick.bmp
```

The exact file formats as described by the `file` command are:

```
icon_from_gimp_16bit.bmp:  PC bitmap, Windows 98/2000 and newer format, 64 x 64 x 16
icon_from_gimp_24bit.bmp:  PC bitmap, Windows 95/NT4 and newer format, 64 x 64 x 24
icon_from_gimp_32bit.bmp:  PC bitmap, Windows 98/2000 and newer format, 64 x 64 x 32
icon_from_imagemagick.bmp: PC bitmap, Windows 98/2000 and newer format, 64 x 64 x 32
```

**Steps to reproduce:** Load a BMP file and try to use it as a Sprite texture.

**Minimal reproduction project:** [test_image_formats.zip](https://github.com/godotengine/godot/files/3398927/test_image_formats.zip)

**Comment by Xrayez** [comment]
Managed to fix importing `icon_from_gimp_24bit.bmp` in linked PR, for other types it seems like the loader is complaining about not supported compression type:

https://github.com/godotengine/godot/blob/4e5310cc60dc17e5ef09e57115ca8236544679e4/modules/bmp/image_loader_bmp.cpp#L241-L246
