### ISSUE TITLE
triplanar ignores depth map

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#30621]
**Godot version:**
3.1 and 3.2 nightly 20190715

**OS/device including version:**
Windows 10, Nvidia GTX 1060 current drivers

**Issue description:**
in a Quad, Plane, Godot-primitive, activating triplanar makes the spatialmaterial ignore the Depth map, as soon as you deactivate triplanar and set the UV scale by hand, the Depth maps works again, this was supposed to be solved last year with: https://github.com/godotengine/godot/issues/19301

but at least depth map is still broken when triplanar is activated, further testing with other maps needs to be done.

**Steps to reproduce:**
Create a Quad, plane, primitive, set the maps (albedo, normal, etc), set the depth map, it should work... now activate triplanar in UV, the depth stopts working, it gets ignored and only normal, albedo, etc are used

**Comment by clayjohn** [comment]
Looks like it is not supported. 
https://github.com/godotengine/godot/blob/22c843b0c451a0c3d79a3b3e6af900b841c51c12/scene/resources/material.cpp#L742

**Comment by rubenjavier** [comment]
interesting, its weird that it was marked as resolved in last year issue
¿is there a math issue when the triplanar is calculated or something like that? I mean, normal maps are working and using the same calculations
thanks @clayjohn hope this gets added, its a lot easier to use triplanar than to manually set UVs for every plane

**Comment by clayjohn** [comment]
In that issue all additional maps broke, so the depth map issue was just grouped in with the rest. 

> is there a math issue when the triplanar is calculated or something like that?

I am not sure. But I would guess it is very difficult to implement if not impossible. As depth mapping is significantly more complex than normal mapping. Normal mapping only effects the light calculations while depth mapping affects the visibility of sections of the texture.

**Comment by mhilbrunner** [comment]
Closing as per the comment above.
