### ISSUE TITLE
Automatic line break stops bbcode text centering in RichTextLabel

### ISSUE THREAD

**Issue by OmnipotentPotato** [godotengine/godot#30632]
With RichTextLabels the text will automatically line break in order to not go over its set width if your message is too long and you did not put in a line break yourself. If you do this it will always automatically make the line break be left aligned instead of center aligned even if you have the text set to be center aligned using bbcode.

For example I have the following line:
description_text.set_bbcode("[center]-\nmemorize the grid and find the color that changes\n-[/center]")

Which should make the text look something like..

```
         -
 Memorize the grid
and find the color
   that changes
        -
```

where the text is centered obviously.

But what I actually get is this:

```
           -
memorize the grid
and find the color
that changes
           -
```
where any line break that was not manually entered breaks into being left aligned and not center aligned. The "-" characters remain fine since i had the /n but the lines "and find the color" and "that changes" are left aligned instead of center aligned

Let me know if this post made no sense and I can post my code and some pictures.

**Comment by KoBeWi** [comment]
> Let me know if this post made no sense and I can post my code and some pictures.

Godot version and some reproduction project would be sufficient.

**Comment by Calinou** [comment]
Closing in favor of #34308, which has more information about the issue at hand.
