### ISSUE TITLE
PopupDialog has no theme properties

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#30637]
**Godot version:**
3.1.1

**Issue description:**
`PopupDialog` doesn't have an apparent purpose, as most dialogs inherit from `WindowDialog` instead.  It appears to be a generic panel, with no way to access its StyleBox.  If the only distinction between PopupDialog and its parent class is aesthetic, perhaps its purpose could be clarified in the docs.  Otherwise, it appears to behave similarly to `PopupPanel`, but without theme properties exposed.

**Comment by akien-mga** [comment]
See also godotengine/godot-docs#2495.

**Comment by YeldhamDev** [comment]
I think #33120 closes this.

**Comment by akien-mga** [comment]
Fixed by #33120.
