### ISSUE TITLE
"Non-static function 'func name' can only be called from an instance" when AutoLoading a script

### ISSUE THREAD

**Issue by georgikoemdzhiev** [godotengine/godot#30649]
**Godot version:**
Godot 3.1.1.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
I created a script called "network.gd", I added a function called "create_server()" in it. Then I added it as a AutoLoaded script and tried to use it in another script. When I tried to run the project it showed me that error - "_Non-static function 'create_server' can only be called from an instance._" when AutoLoading a script"

**Steps to reproduce:**
1. Create a script, name it "networking.gd"
2. add a method "create_server()":
```
func create_server():
	# Initialize the networking system
	var net = NetworkedMultiplayerENet.new()
	
	# Try to create the server
	if (net.create_server(server_info.used_port, server_info.max_players) != OK):
		print("Failed to create server")
		return
		
	# Assign it into the tree
	get_tree().set_network_peer(net)
```
3. Add the script to **AutoLoad**
4. Try calling `network.create_server()` from another script

**Minimal reproduction project:**
[SimpleNetworkingPractice.zip](https://github.com/godotengine/godot/files/3401596/SimpleNetworkingPractice.zip)

**Comment by KoBeWi** [comment]
This is because you used `class_name` with the same name as Autoload. It's the same as #28187

**Comment by georgikoemdzhiev** [comment]
Yes, that was the case. Thanks :)
