### ISSUE TITLE
Write a documentation exporter to reStructuredText format

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3064]
As we're considering using readthedocs.org / Sphinx to generate Godot's online documentation based on a git repo instead of a conventional wiki CMS, we need to add support for yet another markup language to export the classes list to: reStructuredText (readthedocs.org also supports Markdown, but apparently provided many more features when using reST).

Pinging @shackra who already worked on the exporter for the Textile format, if you're willing to give a go at another markup language :)

I've already put an example of a class documented in reST: https://raw.githubusercontent.com/akien-mga/godot-test-wiki/master/classes/class_dictionary.rst
And the corresponding documentation entry: http://godot-wiki.readthedocs.org/en/latest/classes/class_dictionary.html

This reST was automatically converted from Markdown using Pandoc, so it's not necessarily the best output we can achieve, we can discuss first how it should look like before implementing it.

**Comment by akien-mga** [comment]
BTW I moved the documentation tools from tools/docdump to doc/tools (the former now only contains the C++ code used for Godot's ```-doctool``` function).

**Comment by bojidar-bg** [comment]
If we can use something like `ejs`/`handlebars` for python, it might be much easier to implement new markup languages.

**Comment by shackra** [comment]
Sure! I'll be happy to make more useful contributions to Godot Engine :D

I'll take a look at ejs and handlebars. I was thinking anyway in using a design pattern to write
more exports when the time of adding more exporters comes.

El domingo 13 de diciembre del 2015 a las 0940 horas, Bojidar Marinov escribió:

> If we can use something like `ejs`/`handlebars` for python, it might be much easier to implement new markup languages.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/godotengine/godot/issues/3064#issuecomment-164269145

-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by shackra** [comment]
Man, can you assign this task to me? or is it limited to people part of Godot engine team?

**Comment by akien-mga** [comment]
@shackra Looks like I can't assign the issue to you, it seems indeed to be limited to godotengine organization members. But I guess now it's clear from the comments on this issue that you're currently working on it, so potential other contributors will be aware too :)

**Comment by akien-mga** [comment]
I've now imported the OP project wiki in my test project on readthedocs.org: http://godot-wiki.readthedocs.org/en/latest/
It still needs some work, but now the biggest missing part is the API doc ;)

(I could have a go at it by exporting to MarkDown or Textile and then using pandoc as a start, though we'll need to reST exporter in the long run to avoid having too much manual sync work)

**Comment by akien-mga** [comment]
@shackra Actually @reduz just went and wrote an exporter (he's finishing it right now), so no need for you to start working on it now. The refactoring work you were planning within  `makedocs.py` might still be interesting though :)

**Comment by shackra** [comment]
Uh, there was some work already done (check my fork) but it's OK I guess... 


Enviado desde mi dispositivo Samsung

-------- Mensaje original --------
De: Rémi Verschelde <notifications@github.com> 
Fecha: 06/02/2016  14:13  (GMT-06:00) 
Para: godotengine/godot <godot@noreply.github.com> 
Cc: Jorge Araya Navarro <shackra@riseup.net> 
Asunto: Re: [godot] Write a documentation exporter to reStructuredText format
  (#3064) 

@shackra Actually @reduz just went and wrote an exporter (he's finishing it right now), so no need for you to start working on it now. The refactoring work you were planning within  makedocs.py might still be interesting though :)
