### ISSUE TITLE
DynamicFont should enable filter by default

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30643]
**Godot version:**

3.1

**Issue description:**

Currently the filter and mipmap properties default to false. This means that it is very easy to run into a situation where font quality is negatively affected. (For example when the viewport resolution, and the window resolution do not match. Aka. any debug environment.)

Imho filtering should default to being on. It simply looks better in all cases.

**Comment by Calinou** [comment]
Filter isn't enabled by default because it sometimes causes the font to become blurry even if you aren't zooming in at all.

**Comment by IAmActuallyCthulhu** [comment]
@Calinou By that logic should images import **not** have filter `ON` by default?

**Comment by Calinou** [comment]
@IAmActuallyCthulhu I think this is a different situation, as images are often expected to be scaled at run-time. By contrast, this is usually not the case for fonts. If you use the `2d` stretch mode, Godot will automatically oversample DynamicFonts by default, which means they will still be rendered at a pixel-perfect scale, just rendered at an higher resolution.

**Comment by TheDuriel** [comment]
>If you use the 2d stretch mode, Godot will automatically oversample DynamicFonts by default

Filtering off:
https://cdn.discordapp.com/attachments/540803169374961664/601000131222962176/unknown.png
viewport 1080p, window 900p, stretch 2D, aspect expand

Filtering on:
https://cdn.discordapp.com/attachments/540803169374961664/600999817300279296/unknown.png
viewport 1080p, window 900p, stretch 2D, aspect expand

**Comment by Calinou** [comment]
@TheDuriel Double-check that **Rendering > Quality > Dynamic Fonts > Use Oversampling** is enabled in the Project Settings (it should be enabled by default since 3.1). Also, note that it will only work within the default viewport; it won't work with custom viewports.

**Comment by TheDuriel** [comment]
![image](https://user-images.githubusercontent.com/44248915/61403962-b387cd00-a8d6-11e9-85ac-ce49bcadcb5d.png)

Default viewport.

Funnily enough, with it disabled and having filtering off as well is __almost__ ok. Still terrible, but at least the letters line up.
![image](https://user-images.githubusercontent.com/44248915/61404080-ef229700-a8d6-11e9-8c91-dbd100d38ffe.png)

**Comment by girng** [comment]
wats up with that font @TheDuriel  lol

**Comment by TheDuriel** [comment]
Happens to be inconsolata. Meant to look like this. Hence the thread.
![image](https://user-images.githubusercontent.com/44248915/61482504-13e04280-a99b-11e9-859c-3c0dd241ef9c.png)

**Comment by girng** [comment]
something ain't right, even if filter is enabled it looks way out of character (pun intended)

**Comment by Calinou** [comment]
Fonts are now filtered by default in the `master` branch as part of the Vulkan renderer rewrite, closing.
