### ISSUE TITLE
Error flood using VisualServers to create sprite

### ISSUE THREAD

**Issue by salvob41** [godotengine/godot#30650]
**Godot version:**
Godot3.1.

**OS/device including version:**

**Issue description:**
Creating a scene, in order to use VisualServer to add a sprite using the code in the documentation: 
https://docs.godotengine.org/en/latest/tutorials/optimization/using_servers.html

```
func _ready():
        # Create a canvas item, child of this node.
	var ci_rid = VisualServer.canvas_item_create()
	# Make this node the parent.
	VisualServer.canvas_item_set_parent(ci_rid, get_canvas_item())
	# Draw a sprite on it.
	# Remember, keep this reference.
	var sprite = load("res://icon.png")
	# Add it, centered.
	VisualServer.canvas_item_add_texture_rect(ci_rid, Rect2(sprite.get_size() / 2, sprite.get_size()), sprite)
	# Add the item, rotated 45 degrees and translated.
	var xform = Transform2D().rotated(deg2rad(45)).translated(Vector2(20, 30))
	VisualServer.canvas_item_set_transform(ci_rid, xform)
```

flood the debugger with the following errors:
```

E 0:00:01:0474   Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
  <C Source>     ./core/rid.h:164 @ getornull()

```

**Comment by salvob41** [comment]
if you load the sprite texture before the _ready, the error stop flooding

**Comment by bojidar-bg** [comment]
Is this an issue with Godot, or with the documentation?

**Comment by salvob41** [comment]
I thought it was a Godot issue (that's why I put it here), but since this worked
> if you load the sprite texture before the _ready, the error stop flooding

I guess we could update the docs and close this issue. What do you think?

**Comment by bojidar-bg** [comment]
Given the `# Remember, keep this reference.` comment, I think it is a problem with the specific example in the documentation (the reference dies by the end of `_ready` as the example is currently written).

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/3213
