### ISSUE TITLE
Less Tedious SoftBody Attachments

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#30664]
Hello,

I have an idea/feature proposal that would make pinning cloth less tedious.

I've been trying to edit the `SoftBodyGizmo` (or make a `SoftBodyEditorPlugin`), to no avail, so that when pinning a point it would be created and already be attached to a node. For example I see this working like the context specific Mesh Menu that pops up when selecting a `MeshInstance` where one option would open a dialog to select a node from the scene to pin to.

I've already started this feature and am just having some trouble getting my `SoftBodyEditorPlugin` to show when clicking on a `SoftBody`.

I also can't seem to find where the Attachments are created when pinning a point.

Hopefully @AndreaCatania could chime in about how this is done so I could modify things to fit and I could submit a pull request for review. 

Let me know if this is good/bad and if I should spend time on it or not. I think it would speed up usage of the softbody node to make pinning less tedious.

**Comment by AndreaCatania** [comment]
I think that this is really nice addition.

The Pin Points are created and synchronized with the physics inside the SoftBody here: https://github.com/godotengine/godot/blob/master/scene/3d/soft_body.cpp#L677
But the gizmo that show the handles is here:  https://github.com/godotengine/godot/blob/2293c612e6c0913b6999080c9f2fa77227348818/editor/spatial_editor_gizmos.cpp#L2182-L2256

The function `commit_handle` is the function responsible for the toggling of the Pinned Point.

You have to work on the `redraw` function to implement what you want to do.

Hope that it's helpful!
