### ISSUE TITLE
Theora Streams not played entirely

### ISSUE THREAD

**Issue by GovanifY** [godotengine/godot#3066]
This is kind of a weird behaviour as some Theora Streams on a VideoPlayer node seems just to be shrinked down by just not showing the last frames(approx 1sec)

I've done the test on 4 different ogv streams, and this is reproduced each time.

**Comment by GovanifY** [comment]
It seems this issue doesn't appear on windows, so I'm running an X11 server for anyone who wants to try it out.

**Comment by GovanifY** [comment]
I fetched the project, compiled, launched my test godot project, didn't worked.
I deleted the folder, re-cloned and re-compiled in case, still didn't worked.
Could you @akien-mga or @reduz re-open this issue as this is not fixed? Thanks for the hard work!

**Comment by akien-mga** [comment]
Could you provide a minimal test project that reproduces the issue, or some steps on how to reproduce it with a given ogv stream?

**Comment by GovanifY** [comment]
ofc, will do it in a sec. Btw I'm working on an x11 server so this you might have to test on a linux platform to operate this issue.

**Comment by GovanifY** [comment]
Here is the test project: http://www.govanify.com/_files/TEST_VIDEO.7z

**Comment by akien-mga** [comment]
Most of us run Linux with X11 too actually ;)
I'll test it asap.

**Comment by reduz** [comment]
don't mind testing on linux

**Comment by akien-mga** [comment]
I tried it and it seems indeed not to show the very last frames. When played on VLC, the stream stops just after finishing the "3" loop and as soon as the "2" shows up. When played in Godot, it stops half-way through the "3", so half a second is missing or so.

**Comment by GovanifY** [comment]
Does that on all theora streams I know, the length seems also to be variable from the length, but that might just be me tbh.

**Comment by GovanifY** [comment]
Ok I actually tried on a windows machine, it's not a platform:linux issue, you can delete this label.

**Comment by reduz** [comment]
This seems to work perfectly for me, please try again. The audio is a tiny bit delayed in Godot, but you can adjust that.

**Comment by GovanifY** [comment]
Compiling the latest version right now, will test just after

**Comment by GovanifY** [comment]
Nope, still not working

**Comment by reduz** [comment]
Tried your test project on both linux and windows and it seems to work.. unless i'm missing something. What are you expecting to see and what are you not seeing?

**Comment by akien-mga** [comment]
@reduz See https://github.com/godotengine/godot/issues/3066#issuecomment-165197536, the "issue" is not that easy to see, at least not with this example. If you compare the video in VLC and Godot, VLC plays it about half a second further or so.

**Comment by reduz** [comment]
will check again
