### ISSUE TITLE
Unable to generate an independent node instance

### ISSUE THREAD

**Issue by davehayes** [godotengine/godot#30669]
**Godot version:** 3.1.1-stable (FreeBSD ports build)

**OS/device including version:** FreeBSD 11.3-STABLE r349638

**Issue description:**

Consider the following two scripts, Simple.gd and Driver.gd

``` gdscript
extends Node
var a = 17
func _ready():
	pass 
func get_a():
	return self.a
func set_a(value : int) :
	self.a = value
```

```gdscript
extends Node
var oldd
onready var d = load("res://Simple.gd").new()
func _ready():
 	pass
func _on_Button_pressed():
	print("#### PRESSED")
	if (oldd != null) :
		print("Old A is " + str(oldd.get_a()))
	var newd = d.duplicate(DUPLICATE_USE_INSTANCING|DUPLICATE_SCRIPTS)
	print("New 'instance' attempt, a is " + str(newd.get_a()))
	newd.set_a(22)
	print("Set a to 22: " + str(newd.get_a()))
	if (oldd != null) :
		print("Old a still should be 17: " + str(oldd.get_a()))
	print(oldd)
	print(newd)
	oldd = newd
```

The output from the 2nd and subsequent button presses indicates that the old node (oldd) is getting changed along with the new node:

```
#### PRESSED
Old A is 22
New 'instance' attempt, a is 17
Set a to 22: 22
Old a still should be 17: 22
[Node:1780]
[Node:1991]
```

I would expect that `newd` would be a fresh instance and `set_a` to only change the fresh instance's copy of a. Instead, it changes all of them (tested this in a much more complex project). I do not understand. Is this my naivete, a bug in Godot, or a combination of both? 

Note that I have tried `new()`, `duplicate()`, and `instance()` to get a fresh instance. All three, while returning slightly different semantics when printed, produce the same result.

**Comment by Zylann** [comment]
> Old a still should be 17

On second button pressed, this statement can't be true because you set `a` to 22 and assign the node to `oldd` during the previous button press. So on the next button press, `oldd` is still 22.

**Comment by davehayes** [comment]
Yep, this test case is whacked. :) Closing.
