### ISSUE TITLE
Quote completion for selected string

### ISSUE THREAD

**Issue by greenfox1505** [godotengine/godot#30662]
**Godot version:**
3.1

**OS/device including version:**
Editor/All

**Issue description:**
In the text editor, if you have something selected, pressing `"` should not replace the text. Instead it should place a `"` on the left and right side of the selected text.

This should also be the behaviour of: `{}`, `[]`, `()`, `'`, `<>`. Selected text and pressing a left member of a bracketing pair should insert the correct bracket to both sides.

**Comment by BeayemX** [comment]
You can enable this behavior in `Editor Settings / Auto Brace Complete`
It just does not work for `<`

**Comment by greenfox1505** [comment]
Awesome, I didn't know that. IMHO, that should definitely be an "on by default" feature. It is in VSCode.

`<` is very much a low priority, but also should be extremely trivial to add if the rest is there. Might not be a good idea regardless. Mostly useful for editing XML, which might be useful if your GDSCript is calling JS which is modifying the DOM. However, that type of DOM editing is usually rare.

**Comment by greenfox1505** [comment]
I just tried this feature out. It is almost perfect. However, it unselects the text. If I want to place a `dictionary.key` with `dictionary["key"]`, I have to highlight `key` twice. Other text editors I've used that have this feature do not unselect the text, so you can keep adding layers of `()` without having to re-highlight.
