### ISSUE TITLE
Errors at game close when using static factory methods

### ISSUE THREAD

**Issue by cheesegreater** [godotengine/godot#30668]
**Godot version:** v3.1.1.stable.official

**OS/device including version:** Windows 10, 64-bit, version 1809

**Issue description:** I have a class in one of my scripts named `PlayerInfo`. I created a `serialize() -> String` method that converts all of its data to a single string, and a `deserialize(input: String) -> PlayerInfo` static method that returns a new instance of `PlayerInfo`.

The class and its methods work perfectly. The problem that I'm having occurs when I add static typing to the `deserialize()` method. If I set the type to `PlayerInfo`, the name of the class, the engine throws a few errors when the game closes:

```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2095
```

These errors do not occur when using dynamic typing, or when the return type is specified as `Reference` (which is technically true, but not as specific as I'd prefer). The code will work fully with or without the errors; it only causes issues when the game is closed.

From my perspective, it seems like this is causing a cyclic dependency issue, but it's valid syntax in other languages (e.g. [Java](https://www.baeldung.com/java-constructors-vs-static-factory-methods)).

**Steps to reproduce:**

1. Create a new project and add a Node2D with any name. Save the scene with any name.

2. Attach a new script to the Node2D with these contents:

```
extends Node2D

class causes_error:
	var val: int

	static func from_string(input: String) -> Reference:
		var output: causes_error = causes_error.new()
		output.val = int(input)
		return output
```

3. Run the scene and close the game window. Errors will be added to the terminal window opened by the editor. If the game is run from a terminal instead (e.g. `godot.exe --path /path/to/project`), then the errors will be output to that terminal.

**Minimal reproduction project:** [ResourceBug.zip](https://github.com/godotengine/godot/files/3404272/ResourceBug.zip)

**Comment by cheesegreater** [comment]
I ran it with the -v flag and got about the same as you did (different line numbers in the "Leaked instance" lines):

```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2095
Leaked instance: GDScript:1127 - Resource name:  Path:
Leaked instance: GDScriptNativeClass:530
Orphan StringName: Reference
Orphan StringName: causes_error
Orphan StringName: new
Orphan StringName: GDScriptNativeClass
Orphan StringName: val
Orphan StringName: res://main_scene.gd
Orphan StringName: from_string
Orphan StringName: input
Orphan StringName: _init
Orphan StringName: GDScript
StringName: 10 unclaimed string names at exit.
```

**Comment by ShawnMcCool** [comment]
This is one of my biggest frustrations when working with Godot. 

I believe that optional typing is going to be big for Godot. Its promise compels me.

Cyclical references breaking the compiler is problematic. But I get it, the features are new and Godot is changing rapidly.

In the short-term it'd go a long way to be able to reference a class' own name within its static functions. Static factory methods are an important part of my expressive code style.

Thanks for your work.

**Comment by qarmin** [comment]
Still happens in master(3.2 beta 5) and I find this leaks in many projects
```
extends Reference
class_name PaletteColor

func fromDict(input_dict : Dictionary) -> PaletteColor:
	var result = get_script().new()
	return result
```

**Comment by qarmin** [comment]
The worst thing about it, is that the memory leak is present even if we open project in editor(we don't need to run it)

**Comment by qarmin** [comment]
There is also another one example of leak which shows when we use just typed variable:
```
extends Reference
class_name PaletteColor

var player : PaletteColor = null
```

**Comment by NathanLovato** [comment]
It seems it happens every time a class has a member of its own type. Happens the same here:

```gdscript
extends Node
class_name State

var _parent: State = null
```

This causes a memory leak upon quitting the engine.

**Comment by NathanLovato** [comment]
This also happens with casting, the leak is the same:

```
class_name State

var _parent = null

func _ready():
    _parent = get_parent() as State
```

**Comment by cgbeutler** [comment]
I am seeing a regression for this in 3.3.2

**Comment by akien-mga** [comment]
That's possible, but it would be clearer to open a new issue to see what the current problem is, which may differ from what it was in 2019 (especially since there were fixes in the meantime aiming to solve it, some of which may have been partially undone due to bugs).
