### ISSUE TITLE
Calling function repeatedly in fragment shader causes Godot Engine to crash during shader compilation

### ISSUE THREAD

**Issue by loganjk** [godotengine/godot#30666]
**Godot version:**
3.1.1 win64 (Classical)

**OS/device including version:**
Windows 10 Pro, Intel i7-4790K, integrated GPU only (Intel HD Graphics 4600), driver igdkmd64.sys version 20.19.15.5058

**Issue description:**
Working on a large fragment shader (GLES2), I found that inserting a clearly bug-free line inside a certain function and then trying to save or play would cause Godot Engine to crash, I assume during shader compilation (at least, before anything was displayed).  Any extra line would cause a crash, such as adding 0.0 to an already-defined float.  What distinguished this function from others is that it was called frequently, about 150 times throughout the shader.  I have distilled this problem to its essence in the attached minimal reproduction project.  The shader for the ColorRect in the project defines a simple (if somewhat silly) function and then that function is called repeatedly in fragment().  There are 3,000 calls and another 1,000 commented out.  With 3,000 calls, save/play work as expected.  When uncommenting the additional 1,000 calls, making 4,000 total, save/play cause Godot Engine to crash.  The calls are all written explicitly, rather than in a loop, since a loop that repeatedly calls the function once does not seem to cause a crash. 

Windows Task Manager does not show any difference in activity between the 3,000 and 4,000 cases -- no memory or GPU memory spike for 4,000, for example.  Godot does not show any errors in the console before crashing and does not leave any log.  I do not know how to do a stack trace to try to figure out what is going on, but it seems that some limit is being reached during shader compilation.  The critical number of function calls -- the smallest number causing the crash -- seems to depend on the complexity of the function.  When I add more arithmetic operations inside the function, for example, the critical number decreases.  In my real shader, the critical number is much lower because the function is more complex than in the minimal reproduction project.

_Any help would be greatly appreciated since I have not found a way to avoid calling my desired function more than its critical number of times or to put the calls in a loop. In other words, at present, I cannot use my desired function in Godot because of these crashes._

**Steps to reproduce:**
Open the attached minimal reproduction project.  There is a ColorRect with a shader material -- open the editor for the shader.  In fragment(), scroll down until you see the commented-out 1,000 function calls, uncomment them and save or play.  When I do this, Godot Engine crashes.  In case the critical number is machine-dependent, and 4,000 works on your machine when testing, try increasing the number of calls by copying and pasting until you get a crash.

**Minimal reproduction project:**
[Godot Bug Report 3.zip](https://github.com/godotengine/godot/files/3404068/Godot.Bug.Report.3.zip)

**Comment by clayjohn** [comment]
This sounds like you are hitting the maximum instruction count on your hardware. This is a hardware dependent limit and has nothing to do with Godot. For example, I am able to run your test case fine on my Celeron N2840. 

Using for loops is a much better approach than copying the same function 3000 times. I'll bet your hardware will be able to run that function in a loop 3000 times with no problem. In general loops like that are slower (the compiler will manually unroll the loop for you if small enough) but in this case its necessary.

**Comment by loganjk** [comment]
Thanks very much for your reply.  This seems like a plausible explanation.  Obviously in my real code I did not copy the same function when it could have simply been in a loop -- instead, the function is called in many separate places in the code.  Anyway, regarding Godot, is there a way to see how many instructions are used in the shader when it compiles?  That would be helpful as a guide to know how effective my attempts are at reducing instruction count.  Also, if Godot crashes because a shader exceeded the instruction count limit, is that recorded in a log anywhere?  Knowing the reason for the crash would save some debugging time.

**Comment by clayjohn** [comment]
Unfortunately, no. It would be very helpful to count instructions, i think Unreal engine does that in its shader editor. And due to the nature of the crash its difficult for godot to do anything at all. We can't tell what your instruction limit will be in advance. And the crash is on your graphics driver, not in Godot anywhere. So Godot doesnt really even know why things are crashing.

**Comment by loganjk** [comment]
Thanks again.  I will open a separate issue suggesting a visible instruction count.  It seems Unity does that, not sure about Unreal.
