### ISSUE TITLE
Shadow Contact Property Affects Objects With Shadows Disabled

### ISSUE THREAD

**Issue by matthew1006** [godotengine/godot#30673]
Godot 3.1.1
GLES 3
Windows 7 64-bit
Nvidia GeForce GTX 750 Ti

The `shadow_contact` property of 3D light nodes still affects GeometryInstance nodes that have had their `cast_shadow` property set to `SHADOW_CASTING_SETTING_OFF`

Directional Light
![contact_no_shadow_1](https://user-images.githubusercontent.com/7364976/61446476-1ca72900-a947-11e9-92b6-6977296a1a5b.PNG)

Omni Light
![contact_no_shadow_2](https://user-images.githubusercontent.com/7364976/61446501-2597fa80-a947-11e9-82ce-3a941f69c050.PNG)

Spot Light
![contact_no_shadow_3](https://user-images.githubusercontent.com/7364976/61446517-2a5cae80-a947-11e9-9399-67740f24e1be.PNG)

Steps to reproduce:

1. Add a MeshInstance and set its `cast_shadow` property to `SHADOW_CASTING_SETTING_OFF`
2. Add any light and set its `shadow_enabled` property to `true`
3. Set the light's `shadow_contact` property to any value >0

Minimal reproduction project:
[Shadow Contact Issue.zip](https://github.com/godotengine/godot/files/3405837/Shadow.Contact.Issue.zip)

**Comment by akien-mga** [comment]
CC @clayjohn
