### ISSUE TITLE
CollisionPolygon2D doesn't display colors per generated quadrangle

### ISSUE THREAD

**Issue by vichug** [godotengine/godot#3069]
Not sure of the "quadrangle" here. But look at this example : using Godot 1.1
![allthecolors](https://cloud.githubusercontent.com/assets/4671710/11768914/8347527e-a1db-11e5-8ee9-6e9e6887e1a5.png)
and now, with latest 2.x :
![onlybluecolor](https://cloud.githubusercontent.com/assets/4671710/11768944/7771c96a-a1dc-11e5-9975-71d2d38ad0bf.png)

This is the same scene, in which there is a sprite for the background, with a CollisionPolygon2D drawn on top of it, for having "solid" walls for interaction wiht the player. I suppose this is not a totally 100% correct workflow, but it works.
The colors were very useful, because the CollisionPolygon2D generates all those "quadrangles", i think this is the same be it in 1.x and 2.x ? Anyway there are some rare cases where one quadrangle is not drawn correctly and the collisions are ignored for that buggy area, which can be corrected by moving/adding some points in order to generate the missing quadrangle.

**Comment by Ovnuniarchos** [comment]
It is controlled by a compile-time flag, but it's still there. Should this flag be exposed run-time?

**Comment by akien-mga** [comment]
What flag?

**Comment by Ovnuniarchos** [comment]
DEBUG_DECOMPOSE. Line 149 of /scene/2d/collision_polygon_2d.cpp

**Comment by akien-mga** [comment]
Indeed: https://github.com/godotengine/godot/blob/9251298/scene/2d/collision_polygon_2d.cpp#L155

It was commented out by @reduz in https://github.com/godotengine/godot/commit/83d9a692be648668b5b363f2424c619e15639843#diff-90d27e5985a7771fb7e81ed5d76ae317R149
Should it be reactivated? Or exposed at an editor setting?

**Comment by vichug** [comment]
the commit comment reads `-Customizable colors in project settings`
maybe it is already exposed as an editor settings then......

**Comment by vichug** [comment]
anyway i can't find this setitng, if it's there.
