### ISSUE TITLE
Examples in AStar documentation page uses `as` keyword as variable name

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#30699]
**Godot version:**

Latest Docs

**OS/device including version:**

All

**Issue description:**

Examples in AStar documentation page uses `as` keyword as variable name.

**Steps to reproduce:**
Visit https://docs.godotengine.org/en/latest/classes/class_astar.html .
Try any example code snippets like:
```
var as = AStar.new()
as.add_point(1, Vector3(0, 0, 0))
as.add_point(2, Vector3(0, 1, 0), 1) # Default weight is 1
as.add_point(3, Vector3(1, 1, 0))
as.add_point(4, Vector3(2, 0, 0))

as.connect_points(1, 2, false)
as.connect_points(2, 3, false)
as.connect_points(4, 3, false)
as.connect_points(1, 4, false)
as.connect_points(5, 4, false)

var res = as.get_id_path(1, 3) # Returns [1, 2, 3]
```

Kinda unrelated but related note: Running the code also gave me
 ```
ERROR: AStar::connect_points: Condition ' !points.has(p_id) ' is true.
   At: core\math\a_star.cpp:126 
```
in console. It's a separate issue.

**Minimal reproduction project:**
Try the code in ready function of any script in any project to test it.

**Comment by Anutrix** [comment]
I was gonna a make a PR myself but wasn't sure what the variable name should be so that it's still explanatory. Maybe astr.

**Comment by akien-mga** [comment]
> I was gonna a make a PR myself but wasn't sure what the variable name should be so that it's still explanatory. Maybe astr.

`astar`

**Comment by Anutrix** [comment]
Ok
