### ISSUE TITLE
Feature Proposal - Easier custom resource management in inspector

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#30694]
**Godot version:**

nighhtly: v3.2.dev.calinou.2c6daf73f

**OS/device including version:**

Windows 10

**Issue description:**

Feature Proposal:

Currently it is possible to define Resource-Scripts `extends Resource`
and when defining `class_name MyResource` the custom resource will show up in the list of resources that show up, when you click on an empty `export (Resource) var resource` field in the inspector. Here i have the problem, that its bothersome to search for the right Resource in the big List of resources.

So my proposal would be, to make it possible to define an export as:
`export (MyResource) var resource` and when you now click on the empty export in the inspector, it will either show the `MyResource` alone or including all of its children.

This way it would be easier (and more intuitive) to managing custom resources, speeding up the process.

**Comment by Zoomulator** [comment]
Optionally, one could add a hint for filtering the resource list.
Something like `export (Resource, "<filter string>") var resource`

It could allow matching multiple type names, or just a straight up string equality match.
Perhaps it's even a bit easier to implement than `export (MyResource) var resource`, but I don't really have a clue.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/18, as feature proposals are now handled on the Godot Proposals repository.
