### ISSUE TITLE
Rearrange items on MenuButton

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot#30705]
**Godot version:**

Godot v3.1

**OS/device including version:**

Windows 10

**Issue description:**

For some reason you can't rearrange the order of the items on the MenuButton when using the item list editor so instead you have to remove all the items and add them all back in just to rearrange the item list.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/368, https://github.com/godotengine/godot-proposals/issues/1975, https://github.com/godotengine/godot-proposals/issues/2355 and https://github.com/godotengine/godot-proposals/issues/2356, as feature proposals are now tracked on the Godot proposals repository.
