### ISSUE TITLE
Height-based fog is inverted

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#30709]
Godot 3.1.1

The parameters of the height-based fog seem to be inverted.
The defaults are: `Height Min: 0` and `Height Max: 100` but the result is fog that is most dense at height 100 and least dense at height 0 - which is usually the opposite of what you want.

Here's some secreenshots:

`Height Min: 0`, `Height Max: 1`:
![grafik](https://user-images.githubusercontent.com/3957610/61577378-da1c5280-aae6-11e9-8862-6eb87059968d.png)

`Height Min: 1`, `Height Max: 0`:
![grafik](https://user-images.githubusercontent.com/3957610/61577386-e6081480-aae6-11e9-8a7d-c8235ab12aa2.png)

**Comment by Calinou** [comment]
I suppose it was worded in the way that "Height Min" is where there's the *least* fog, and "Height Max" is where there's the *most* fog.

We could invert the order if that's more logical, but that will break compatibility.

**Comment by CptPotato** [comment]
Yes, this makes sense. Though, the default values should be changed in my opinion.
