### ISSUE TITLE
Implement support for Android App Bundles (.aab)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#30711]
Google recently introduced a new "App Bundle" format (`.aab`) to upload Android applications to the Google Play store, which lifts various restrictions. Google Play then handles the signing and generation of the final `.apk` file.

I haven't looked into details myself yet, but inevitably some users will want to make use of those features, and we can also expect that eventually Google Play will mandate the use of App Bundles and reject self-compiled APKs, so we should be prepared for that (which also means that App Bundle support should be backported to old stable branches once implemented). Note: I searched and did not find any announced date for this hypothetical restrictions, if you are aware of anything, please notify us.

Google's documentation:
- https://developer.android.com/guide/app-bundle
- https://developer.android.com/studio/publish/upload-bundle

**Comment by Anutrix** [comment]
Isn't it as simple as https://developer.android.com/studio/build/building-cmdline#bundle_build_gradle ?

**Comment by creikey** [comment]
After modifying gradle like that, depending on if the android manifest is still compiled to bytecode, the exporter may need to be heavily modified.

**Comment by fede-Raider** [comment]
A flag like in unity to create or not the android bundle would be very useful!

**Comment by akien-mga** [comment]
CC @godotengine/android

**Comment by alexzheng** [comment]
will 3.2 have this feature?

**Comment by Calinou** [comment]
@alexzheng As Godot 3.2 is currently in the feature freeze period, it likely won't be available in 3.2.

**Comment by alexzheng** [comment]
As 3.2 support custom build, will the app bundle support come soon?

**Comment by Calinou** [comment]
I'll close this in favor of https://github.com/godotengine/godot-proposals/issues/342, as feature proposals are now tracked on the Godot Proposals repository.
