### ISSUE TITLE
Bad font quality when downscalling

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30729]
**Godot version:**
3.2 Dev

**OS/device including version:**
Windows 10

**Issue description:**
Scale= 1:
![Screenshot_21](https://user-images.githubusercontent.com/1850856/61588931-e1596400-abab-11e9-9d0a-5729c2243e2f.png)
Scale = 0.7:
![Screenshot_19](https://user-images.githubusercontent.com/1850856/61588832-74919a00-abaa-11e9-96f7-2a4f64b11195.png)
As seen in the picture, fonts look bad when downscalling.

Also strech mode doesn't seem to make any diffrence:
![Screenshot_20](https://user-images.githubusercontent.com/1850856/61588941-0e0d7b80-abac-11e9-8fa8-87c9c075362f.png)

- Oversampling is enabled.
- The font is a dynamic .otf font (also tried ttf).

EDIT: Use Mipmaps and use Filter does seem to improve it but i think it looks little blurry.
![Screenshot_23](https://user-images.githubusercontent.com/1850856/61589032-419cd580-abad-11e9-8e70-5072ac9ad185.png)

**Comment by Calinou** [comment]
This is expected when downscaling an image that doesn't use mipmaps. You can enable mipmaps to improve the interpolation quality, but it will then look blurry. There's no way to solve this when downscaling by a non-integer factor – you will run into the same issue when downscaling an image in GIMP, for instance.

As a workaround, create a separate font resource with a smaller size, and avoid scaling the Control. (Scaling a control for animation purposes is fine, just make sure to enable Filter on the font then.)

**Comment by zaksnet** [comment]
Thank you @Calinou . Can you please tell me if there is a way to prevent just the font from being scaled? Images seem to be scaled fine.

**Comment by Calinou** [comment]
>  I'm trying to create a UI for multiple resolutions without having to recreate the graphics and so far only fonts don't render nice when downscaled.

Just set up GUI anchors correctly, and use the `2d` stretch mode and `expand` stretch aspect as you did. You don't need to scale controls manually; Godot will do it for you as the window size changes. See [Multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) documentation for details.

Scaling control nodes is mainly useful for animation purposes, you should avoid doing it otherwise.

**Comment by TheDuriel** [comment]
See https://github.com/godotengine/godot/issues/30643

Note that i've not seen a case in which mipmapping a font resource did anything.

**Comment by zaksnet** [comment]
> Note that i've not seen a case in which mipmapping a font resource did anything.

Although my knowledge about mipmap goes as far as what @Calinou explained, i also haven't seen any difference when enabling mipmap.

> Just set up GUI anchors correctly, and use the 2d stretch mode and expand stretch aspect as you did. You don't need to scale controls manually; Godot will do it for you as the window size changes. See Multiple resolutions in the documentation for details.

Scaling control nodes is mainly useful for animation purposes; you should avoid doing it otherwise.

Well, Godot does `resize` the controls, it does not `scale` them. Although this is all you need is most cases, what i want is to give users the option to `shrink` or `enlarge` the UI interface (much like HiDPi but customizable) which seemed to work out of the box by just scaling the parent control of the UI, except the font. Also, i would like this scaling to happen depending on the resolution (which i failed to explain in my previous comment). I concluded that

**Comment by naturally-intelligent** [comment]
I'm also running into this issue with Godot 3.5

Specifically running a 1920x1080 game at 1366x768
The fonts are barely readable even with filter + mipmap on.

Ironically images with text downscale better, than a TTF font! 
May post an image if anyone is interested...

**Comment by Calinou** [comment]
> I'm also running into this issue with Godot 3.5

In 4.0, this is fixed when using MSDF fonts, although very small text will remain hard to read as MSDF doesn't use hinting.

Can you take screenshots of the text in 1920×1080 and 1366×768 respectively? Also, please uploada minimal reproduction project.

**Comment by xahon** [comment]
Here is my case. On the left is rendered text in Godot (10px size) and on the right default Windows 10 font viewer

![image](https://user-images.githubusercontent.com/18731681/226298541-ffe7b25f-fe18-4fd1-ad38-6940b85d4443.png)

The difference is obvious. I've tried different import options. I use these options now because it looks the best possible in that case  
![image](https://user-images.githubusercontent.com/18731681/226298938-af269053-7a12-4573-b5c3-cac9756fbb75.png)

**Comment by xahon** [comment]
Here is an SDF approach. On the left is how it looks like in the editor, on the right how it looks in the game

![image](https://user-images.githubusercontent.com/18731681/226306129-183d2b72-6920-4f52-b20a-c6bb8d820d93.png)

**Comment by Zireael07** [comment]
@xahon: You said the control is NOT scaled, therefore this is a different issue. I think you're seeing a duplicate of https://github.com/godotengine/godot/issues/74694

**Comment by xahon** [comment]
@Zireael07 thanks, moved my comments there
