### ISSUE TITLE
Import > Sub-Scene is confusingly named

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3072]
The "sub-scene" term is used in several places but can be quite confusing to newcomers und especially developers new to Godot's scene system, see e.g. this Facebook post: https://www.facebook.com/groups/godotengine/permalink/703042476499016/

The PR #2928 based on @Fiona's proposal already moves the "Export -> Sub-Scene" menu entry to an icon in the scene tree panel ("Create new scene from node(s)"), but the "Import -> Sub-Scene" entry could also use some love.

As this import function actually seems to *copy* the selected nodes of a scene to the current scene, a name like "Import nodes from scene" would be more explicit.

**Comment by vnen** [comment]
> As this import function actually seems to *copy* the selected nodes of a scene to the current scene

That's what I'd guess it does anyway, as I am already familiar to Godot system. If it were a reference, wouldn't be different of instancing another scene.

But I agree with the name change, "Import nodes from scene" seems to be much more clear.
