### ISSUE TITLE
The last Input.is_action_just_released() fires a 2nd time when app focus lost

### ISSUE THREAD

**Issue by Prime-Eight** [godotengine/godot#30722]
the last Input.is_action_just_released() fires a 2nd time when app focuses lost.
Ie  say the last call was checking if F10 was pressed :

	if Input.is_action_just_released("input_key_F10"): #  /set to F10  
		print("is_action_just_released."   )

you will see the print 1 time to console in the editor, or in the exported apps debug.
now alt-tab, or simply click on another app, any other app and you will see it fire again and a 2nd line will appear as the print() is reached a second time.

for my use, I was able to use Input.is_action_just_pressed(). It works as expected in the case that helps anyone else who needs a quick fix.

**Godot version:**
Nightly 3.2, Dev as of today 

**OS/device including version:**
W10, Ryzen 3 1200, 16GB ram, Zotac GTX1050ti, standard keyboard layout 

**Issue description:**
the last Input.is_action_just_released() is true a 2nd time on app loss of focus, the moment you click in/on another app.

**Comment by aaronfranke** [comment]
I see you tested master, but also, does the problem occur on 3.1.1 stable?

**Comment by allkhor** [comment]
Maybe is related c709dfdf06f6b09b61c1?

**Comment by Prime-Eight** [comment]
It could be related. Its sister function works fine. ( Input.is_action_just_pressed().  )

> I see you tested master, but also, does the problem occur on 3.1.1 stable?
No, it works correctly & as expected in stable 3.1.1

**Comment by KoBeWi** [comment]
Probably the problem is that all input is released, but it doesn't actually check if what it's releasing is pressed. That could even qualify as Junior Job maybe.
