### ISSUE TITLE
GIProbe very low FPS with some materials, example

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#30727]
**Godot version:**
3.1

**OS/device including version:**
Linux and web(Chrome/Firefoxlatest)

**Issue description:**
using GIProbe on *some materials* with high reflection (because of Metallic or/and Roughness) make FPS drop very hard.

**Steps to reproduce:**
 I have FPS drop from 60 to 2-3 FPS, changing *bad* material to other fix problem
example project has 2 cubes with material, first material has *metalic and roughness* texture, second same material without textures
disabling cube with texture or set roughness to 1 fix FPS

**Minimal reproduction project:**
source zip: https://danilw.github.io/godot-utils-and-other/GI_test_material_bug/material_GI_bug.zip

web version :
https://danilw.github.io/godot-utils-and-other/GI_test_material_bug/material_GI_bug.html (fps drop in all builds, web only as example)

![1](https://user-images.githubusercontent.com/24825887/61587642-96812180-ab96-11e9-9ed4-45e93e889b5a.png)

maybe this is not bug, sorry if so

**Comment by clayjohn** [comment]
For me, FPS is very low all the time, regardless of which cube is visible and how metallic is set. Without the GIProbe, I get a full 60 FPS, but with it I get 7 FPS consistently. The roughness/metallic of the materials has no effect.

**Comment by danilw** [comment]
on that example change Roughness to 1 make ~40FPS for me when I look on Flooron that scene
Roughness <0.5 make FPS<8
if you add any *emission* objects they will bake correctly and do not hit performance(FPS stay at 60 with other material or at 40 with Roughness=1)

I have Nvidia 750 video card(latest drivers)

**Comment by Calinou** [comment]
Try disabling **Rendering > Quality > Voxel Cone Tracing > Quality** in the Project Settings.

**Comment by danilw** [comment]
disabling this help, thanks!
