### ISSUE TITLE
QA forum vote abuse

### ISSUE THREAD

**Issue by e-e** [godotengine/godot#30733]
Not sure who to reach out to about this - I've already submitted feedback on the forum, but have received no response. For some reason, it seems someone has downvoted every answer I've ever posted, sometimes up to 4 times. Is there any way to get this removed? All downvotes happened at the same time.

https://godotengine.org/qa/user/Eric+Ellingson/answers

**Comment by akien-mga** [comment]
Sorry that you're experiencing that, it seems to be a coordinated effort from 3 accounts (likely same person) to downvote everything you post.

This is not the place to discuss it though, please reach out privately to webmaster at godotengine · org.

**Comment by akien-mga** [comment]
I also fixed the feedback email which previously went only the contributor who set up the Q2A platform, now it will also go to the webmaster email.
