### ISSUE TITLE
Feature request: websockets:  Put_var() once

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#30739]
`ws.get_peer(1).put_var()`

is always inside (or most often)

`func _process(delta)` which is a loop

if we want to `get_var()` we do

    if ws.get_peer(1).get_available_packet_count() > 0: 			
    var test = ws.get_peer(1).get_var()

which only gets the variable once, inside the loop the same loop.

Using `put_var()` we have to create our own if statements with counters and it gets messy in big projects. It would be nice to have a condition created by Godot to ensure that `put_var()` gets sent once just like

`if ws.get_peer(1).get_available_packet_count() > 0: ` for `get_var()`	that way put_var doesn't get executed more than once unless we remove the condition.	

I'm not sure I could do it since I've never worked on this project, but I'm willing to try and work on it if this feature is approved

**Comment by aspenforest** [comment]
```
extends Node

var peer_id : int = 1
var send_states : Dictionary= {}
var my_var : Array = ["Hello", "World"]

**func _process(delta):
    send_once(peer_id, my_var, "Greeting")**

**func _on_Button_pressed():
    set_send_once("Greeting", true)**

func send_once(id:int, my_var, key:String) -> void:
    if send_states.has(key) == false:
        send_states[key] = true
    if send_states[key] == true:
        send_states[key] = false
        ws.get_peer(id).put_var()

func set_send_once(key:String, b:bool) -> void:
    send_states[key] = b
```

**Comment by elieobeid7** [comment]
Wow! that's really awesome thank you!

**Comment by aspenforest** [comment]
np :)

**Comment by Faless** [comment]
> `ws.get_peer(1).put_var()`
> 
> is always inside (or most often)
>
> `func _process(delta)` which is a loop

Why? I mean, it's there, if you need to send something on every frame, otherwise you would just put it in a function, in a signal, and so on.

I'm sorry, but I really do not understand what the feature would be here.
Could you elaborate further?

**Comment by elieobeid7** [comment]
@aspenforest Thank you so much for the tips!

@Faless 

I can't retest now, but last time I tried, `putvar()` would only send messages to the server, if it's inside a 
`func _process(delta)`, in order to test, download this simple [websocket basic example](https://github.com/gd-com/examples/tree/master/websocket/basic) and run it, run the server too.

You'll notice an infinite loop sending "HI", now remove `func _process(delta)`, and place the code either in a button `_on_Button_pressed()` or in a ready function, you'll notice nothing gets to the server.

Therefore, at least when dealing with WebSockets (haven't tried anything else), `putvar()` won't send anything unless it's a loop, or perhaps the server won't receive the message unless `putvar()` is in a loop, either way, `func _process(delta)` is vital for `putvar()` to send data to WebSockets server

**Comment by Faless** [comment]
> Therefore, at least when dealing with WebSockets (haven't tried anything else), `putvar()` won't send anything unless it's a loop, or perhaps the server won't receive the message unless `putvar()` is in a loop, either way, `func _process(delta)` is vital for `putvar()` to send data to WebSockets server

Well, you want `poll` and `get_var` in `process` so data can be received, but if you only want to send once only move `put_var` out of the loop.

**Comment by elieobeid7** [comment]
```
if Global.ws.get_connection_status() == Global.ws.CONNECTION_CONNECTING || Global.ws.get_connection_status() == Global.ws.CONNECTION_CONNECTED:
    Global.ws.poll()
```

Retested again, you're right, that's the code that should be in the loop and `get_var` of course. Thanks!

**Comment by Faless** [comment]
I'm glad it's working now.
I've been working on a long overdue official tutorial, which has been
delayed due to some personal issues, I hope to publish it this week, so
stay tuned ;-) .

**Comment by elieobeid7** [comment]
Of course please notify me as soon as the tutorial comes out as my entire game depends on WebSockets :)
