### ISSUE TITLE
Attach scripts to nodes by drag and drop from script panel

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot#30746]
Godot v3.1.1.stable.official

Linux Mint 19.1

Enable drag and drop from the script panel (script editor) onto a node, to attach a script to the node.

Attaching a script to a node works fine, if dragged from the file system panel onto the node.
Dragging a script from the script panel would be faster and very useful.
You wouldn't have to search the script in the file system panel first.

**Comment by aspenforest** [comment]
I can see how this can be helpful, but keep in mind that the scripts are listed in the script editor only by their name, not their full path, and we can have scripts with the same name as long as they have different paths. I just created two scripts with the same name into different folders, but when opened, they have identical names in the script editor list. How do you propose to get around the danger of mixing up scripts with identical names?

**Comment by bojidar-bg** [comment]
Since this will not be the only way to assign scripts, users who regularly have to deal with same-named scripts will soon learn to assign scripts through the Add Script button, the Script property, or by dragging from the filesystem dock instead of the script editor.

**Comment by TrickMe** [comment]
> How do you propose to get around the danger of mixing up scripts with identical names?

If you have scripts with identical names, you can still use the file system panel to not nix them up.
I generally try to avoid scripts with identical names though.

When testing a lot and making scripts for testing purposes only (in order not to compromise the functional state of the original script), switching from the original script to a test script and back, would be much quicker from the script editor.
By appending "_test" to the test-script name, you can avoid mixing them up in the script editor panel.
