### ISSUE TITLE
ColorPicker doesn't always remember its HSV mode status in the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#30754]
**Godot version:** Git https://github.com/godotengine/godot/commit/017b224a87064a3d333ba63809a0f12cfe2c4412

**OS/device including version:** Fedora 30

**Issue description:** In the editor, when using a ColorPicker in HSV mode, it will sometimes go back to RGB mode after closing it. This can be pretty confusing when editing colors, especially if you're editing the same property a second time.

This seems to always occur when editing a color in the Project Settings (such as the default clear color) then closing the Project Settings dialog. All color pickers' HSV mode states (including the ones in the inspector) will be reverted back to RGB mode.

**Steps to reproduce:** Go to the Project Settings, change the default clear color while in HSV mode, then close the Project Settings.

**Comment by akien-mga** [comment]
Fixed by #31782.
