### ISSUE TITLE
Editor maximum view distance is to small

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#30766]
**Godot version:**
3.2 build 72b5a9e47

**OS/device including version:**
linux

**Issue description:**
Trying to increase the view range past 10000 is not possible in the editor. Im working on a large terrain and currently its being clipped from the camera so I cannot work on it very well.

**Steps to reproduce:**
In the editor, open the viewport settings, and type in a number larger than 10000. It wont save the value.

**Comment by chaojian-zhang** [comment]
I am working on a planet sized map and Camera3D can allow larger far Z but editor is limited to only 1000000.0 which is not big enough.
