### ISSUE TITLE
Value changes made in keys from 'Method' tracks can't be undone in the AnimationPlayer.

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#30762]
**Godot version:**
bcfbd25

**Issue description:**
Attempting to undo a change a value in a key from a Method type track will result in nothing happening, even if in the output it states that it was undone.

Here is the location of code that is related to that:
https://github.com/godotengine/godot/blob/bcfbd25eefe4d1c0b8ac54ef7eb4abcc51cf68d4/editor/animation_track_editor.cpp#L208

**Comment by bojidar-bg** [comment]
Maybe it just needs a `.duplicate()` call when copying the dictionary?
https://github.com/godotengine/godot/blob/bcfbd25eefe4d1c0b8ac54ef7eb4abcc51cf68d4/editor/animation_track_editor.cpp#L211

**Comment by YeldhamDev** [comment]
> Maybe it just needs a `.duplicate()` call when copying the dictionary?

Would you like at that, that was exactly the problem. Making a pull right now.
