### ISSUE TITLE
please add style for all containers

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#30769]
please add a style for all containers
currently things like hbox and vbox cannot render anything forcing the user to place something behind it
![image](https://user-images.githubusercontent.com/2453707/61678644-5023e380-acb8-11e9-81d5-7cdc36b13945.png)

**Comment by groud** [comment]
No, I don't think it makes sense. Containers are for rearranging their children, they do not need a style.
If you need a style to be applied, simply put your container inside a PanelContainer.

**Comment by LikeLakers2** [comment]
With all due respect, if we were to allow styling these containers, what would you even use that styling for? What might you expect to be able to style about a container?

**Comment by bojidar-bg** [comment]
Having styling on containers would allow for not using PanelContainer so often, which would lead to somewhat cleaner hierarchies.

**Comment by groud** [comment]
> Having styling on containers would allow for not using PanelContainer so often, which would lead to somewhat cleaner hierarchies.

The thing is that I am not sure it makes sense for most containers. It has also a maintenance cost, unless we add it as a generic property in all containers. Also, this would make the PanelContainer useless.

All of this could be modified, but it should be a global rework, not just adding style to all containers.

**Comment by Zylann** [comment]
Containers are all `CanvasItems` still, which means then *can* draw. For now you could use a script which draws your stylebox in `_draw()`.

**Comment by Shadowblitz16** [comment]
the purpose of styling these would be so that the user doesn't have to place a panel underneath the container.   

if containers shouldn't be stylized then there should be some sort of panel alternative to all the containers in which can be styled.

**Comment by MuffinManKen** [comment]
This doesn't seem like something that should be implemented in Godot. Since there are a number of ways to get this effect with what Godot provides, this would just add bloat.

**Comment by girng** [comment]
can't this be done with a theme?

**Comment by Shadowblitz16** [comment]
@girng no it can't that's the issue

**Comment by Zylann** [comment]
I mean... you can pick the StyleBox you want and assign it to all container items in a custom `Theme` resource, and define that as your global theme. That will make all of these container have that stylebox by default, a bit like in CSS.

**Comment by Shadowblitz16** [comment]
@Zylann wait what?
your example image doesn't have a option to assign a StyleBox.

**Comment by Zylann** [comment]
@Shadowblitz16 yeah I just realized.

**Comment by pycbouh** [comment]
This should be [a proposal](https://github.com/godotengine/godot-proposals/issues) instead, even though this is unlikely to happen as there are `Panel` and `PanelContainer` specifically for this purpose.
