### ISSUE TITLE
Exported game crashes on OSX, works on Windows/Linux

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#30775]
**Godot version:** 3.0.6
**OS/device including version:** Mac OS X 10.14.5 (18F203)

**Issue description:** I exported my game on OSX and gave it to two people. Both reported that the game crashed, at different stages.

The same game works fine when exported for Windows and Linux.

First case, which crashed just after the splash screen: [emanquest.txt](https://github.com/godotengine/godot/files/3422097/emanquest.txt)
Second case, which crashes unpredictably - maybe a race condition: [emen.log](https://github.com/godotengine/godot/files/3438250/emen.log)
Third case, no crash/dump file, but it just closed while the player was walking around.

Initially, I suspected it's something to do with OSX; but the game clearly works for the second/third user for some period of time.

Second user's specs:
![image](https://user-images.githubusercontent.com/31222662/61995255-c5463e80-b053-11e9-9885-f685a6b7655d.png)

Third user is on 10.14.4.

**Comment by Zireael07** [comment]
Windows is a non-case sensitive filesystem, while MacOS and Unix both are. Are you sure your casing is correct?

**Comment by nightblade9** [comment]
> Windows is a non-case sensitive filesystem, while MacOS and Unix both are. Are you sure your casing is correct?

I initially suspected the same, but I am 99% sure my casing is correct. My experience developing on Windows, is that the Godot editor itself is case-insensitive (it will happily run if you preload `some_file.tscn` which is `SOME_FILE.tscn` on disk), but the export - even the Windows export - is case-sensitive.

**Comment by qarmin** [comment]
Can you provide minimal project which cause crash?
It seems that something is wrong with add_child function
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6a9112c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6a9ccbf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff6a87b6a6 abort + 127
3   com.deengames.emanquest       	0x000000010e9d0fdc handle_crash(int) + 1740
4   libsystem_platform.dylib      	0x00007fff6a9c1b5d _sigtramp + 29
5   ???                           	0x00007ffee122dc10 0 + 140732675578896
6   com.deengames.emanquest       	0x000000010eb5ea27 GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) + 215
7   com.deengames.emanquest       	0x000000010f5752c6 Node2D::_notificationv(int, bool) + 102
8   com.deengames.emanquest       	0x000000010fe33996 Object::notification(int, bool) + 22
9   com.deengames.emanquest       	0x000000010f0996bf Node::_set_tree(SceneTree*) + 95
10  com.deengames.emanquest       	0x000000010f09954a Node::_add_child_nocheck(Node*, StringName const&) + 122
11  com.deengames.emanquest       	0x000000010f099c7a Node::add_child(Node*, bool) + 1402
12  com.deengames.emanquest       	0x000000010f0b6263 MethodBind1<Node*>::call(Object*, Variant const**, int, Variant::CallError&) + 307
13  com.deengames.emanquest       	0x000000010fe373fb Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 411
14  com.deengames.emanquest       	0x000000010fe2929a MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) + 266
15  com.deengames.emanquest       	0x000000010fe2951b MessageQueue::flush() + 219
16  com.deengames.emanquest       	0x000000010e9fd053 Main::iteration() + 867
17  com.deengames.emanquest       	0x000000010e9da1c2 OS_OSX::run() + 402
18  com.deengames.emanquest       	0x000000010e9dd060 main + 832
19  libdyld.dylib                 	0x00007fff6a7d63d5 start + 1
```

Do you use exactly 3.0.6 version of export templates?

**Comment by nightblade9** [comment]
I don't have a minimal project. I can't distill one because I don't have access to a Mac. My project is open on GitHub - this is the specific commit I built the OSX template from (although I don't think that's significant): https://github.com/deengames/eman-quest/tree/32c670421628f16ea420f39e3d47c30a194a9340

I used exactly the 3.0.6 version of the export templates, the official ones.

**Comment by nightblade9** [comment]
I got a second data point. A second user on Twitter graciously agreed to try out my game. For them, it works beyond the splash screen - they are able to run the game. I updated my initial post with a screenshot of their specs, which they shared with me.

**Comment by nightblade9** [comment]
Third data point - third user, same version of OSX (10.14), same behaviour - it crashes sooner or later. No log file, unfortunately.

**Comment by nightblade9** [comment]
@akien-mga mentioned that crash dump files aren't enough information to make traction. I can (sometimes) see a crash in the Windows export, too. Since I'm not going to pursue this further, I'll close this issue.

Anecdotal data suggests that updating the project to Godot 3.1.1 or running it from the editor seem to fix the crashes.
