### ISSUE TITLE
Add return type hint popup when mouse hover on expression

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot#30773]
What currently slows down my development progress is having to constantly consult the docs for the return type of functions.  
Considering the amount of callable functions, remembering even a fraction of them is a task.  
Therefore, I propose a usability improvement, which would make a small tooltip pop up above or below the mouse cursor displaying the return type of the function or expression over which the mouse is currently hovering. Naturally, this would work for user-defined functions only if they use the "->" operator to explicitly indicate a return type.
If this feature would exist, it would be SO much easier to design and also debug programs.  

Examples:
![example_1](https://user-images.githubusercontent.com/6948036/61702475-8315b800-ad48-11e9-9892-10a93c629f8b.png)
![example_2](https://user-images.githubusercontent.com/6948036/61702484-86a93f00-ad48-11e9-925f-8f10eea6433c.png)

EDIT: The tooltips in the examples are a bit faulty and the info they provide was thought of in a rush.  
They should only give you a general idea how this would work, not what info they should provide.

**Comment by KoBeWi** [comment]
Closing because we are moving proposals out of this repository. There's already a GIP covering this feature: https://github.com/godotengine/godot-proposals/issues/765
