### ISSUE TITLE
Potential bugs found by PVS Studio and Coverity Scan

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#30779]
**Godot version:**
3.2.dev.custom_build. 4c943cca2

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
Possibly bugs found by PVS Studio are collected from previous issues - #27649, #27668 and #28085

- [x] 1. /home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1009: ostrzeżenie: V519 The 'r_ret' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 1004, 1009.
![14Z](https://user-images.githubusercontent.com/41945903/55502684-6e080280-564d-11e9-8f9d-cb157dd1150d.png)
- [ ] 2. godot/core/pool_allocator.cpp:396: ostrzeżenie: V547 Expression '(next_pos - e->pos) > alloc_size' is always false.
![36Z](https://user-images.githubusercontent.com/41945903/55543387-3f2f7200-56c9-11e9-9c85-c0898ba94830.png)
- [ ] 3. core/os/os.cpp:747: ostrzeżenie: V506 Pointer to local variable 'stack_bottom' is stored outside the scope of this variable. Such a pointer will become invalid.
![4](https://user-images.githubusercontent.com/41945903/56227101-fab2b780-6074-11e9-915f-baf41c945f33.png)
- [ ] 4. core/image.cpp:1608: błąd: V621 Consider inspecting the 'for' operator. It's possible that the loop will be executed incorrectly or won't be executed at all.
![2](https://user-images.githubusercontent.com/41945903/56227085-f1c1e600-6074-11e9-99ff-1b7662122ba9.png)
- [x] 5. servers/physics/joints/slider_joint_sw.cpp atan2fast
The copied code will not have its intended effect.
In atan2fast(float, float): A copied piece of code is inconsistent with the original 
![Zrzut ekranu z 2019-07-23 19-25-45](https://user-images.githubusercontent.com/41945903/61733314-cf301f00-ad7f-11e9-9863-9d0e09a13c31.png)
- [x] 6. /editor/plugins/spatial_editor_plugin.cpp
The function call will not have its intended effect.
In SpatialEditorViewport::​_sinput(Ref<InputEvent> const &): The arguments to a function call are provided in the wrong order. 
![Zrzut ekranu z 2019-07-23 19-25-50](https://user-images.githubusercontent.com/41945903/61733489-38b02d80-ad80-11e9-8ff5-087090c61bcc.png)
- [x] 7. modules/assimp/editor_scene_importer_assimp.cpp
The function call will not have its intended effect.
In EditorSceneImporterAssimp::​_generate_node(EditorSceneImporterAssimp::​ImportState &, aiNode const *, Node *): The arguments to a function call are provided in the wrong order. 
![Zrzut ekranu z 2019-07-23 19-25-53](https://user-images.githubusercontent.com/41945903/61733607-7745e800-ad80-11e9-9a79-712daf537197.png)
- [x] 8. editor/plugins/animation_player_editor_plugin.cpp
Either the check against null is unnecessary, or there may be a null pointer dereference.
In AnimationPlayerEditor::​ensure_visibility(): Pointer is checked against null but then dereferenced anyway
![Zrzut ekranu z 2019-07-23 19-43-27](https://user-images.githubusercontent.com/41945903/61734444-38189680-ad82-11e9-8b0d-ece5b5dc2268.png)
- [x] 9. editor/editor_inspector.cpp
 Either the check against null is unnecessary, or there may be a null pointer dereference.
In AnimationPlayerEditor::​ensure_visibility(): Pointer is checked against null but then dereferenced anyway 
![Zrzut ekranu z 2019-07-23 19-34-54](https://user-images.githubusercontent.com/41945903/61734221-cccec480-ad81-11e9-8a8f-19222d839346.png)
- [x] 10. modules/visual_script_/property_selection.cpp
Dereference before null check
There may be a null pointer dereference, or else the comparison against null is unnecessary.
In VisualScriptPropertySelector::​_update_search(): All paths that lead to this null pointer comparison already dereference the pointer earlier (
![Zrzut ekranu z 2019-07-23 19-46-04](https://user-images.githubusercontent.com/41945903/61734632-9180c580-ad82-11e9-87cc-3d1be8cf53d9.png)
- [x] 11. void AudioStreamPlayer::_mix_internal(bool p_fadeout) {
Division or modulo by float zero
This could cause an immediate crash or incorrect computation.
In AudioStreamPlayer::​_mix_internal(bool): An expression which may be zero is used as a divisor in floating-point arithmetic.
![Zrzut](https://user-images.githubusercontent.com/41945903/61888836-8f467480-af04-11e9-84df-09836ad7cc56.png)
- [ ] 12.  AudioStreamPlayer::set_stream(Ref<AudioStream> p_stream)
Division or modulo by float zero
This could cause an immediate crash or incorrect computation.
In AudioStreamPlayer::​set_stream(Ref<AudioStream>): An expression which may be zero is used as a divisor in floating-point arithmetic.
![RRR](https://user-images.githubusercontent.com/41945903/61888895-ae450680-af04-11e9-8c86-c4241671f07b.png)
- [x] 13. EditorProfiler::_graph_tex_draw()
Division or modulo by float zero
This could cause an immediate crash or incorrect computation.
In EditorProfiler::​_graph_tex_draw(): An expression which may be zero is used as a divisor in floating-point arithmetic.
![FF](https://user-images.githubusercontent.com/41945903/61888974-e64c4980-af04-11e9-8adc-066dc82ad71d.png)
- [x] 14. GDScriptParser::_parse_block(BlockNode *p_block, bool p_static)
This is very strange part of code, @vnen @bojidar-bg 
Logically dead code
The indicated dead code may have performed some action; that action will never occur.
In GDScriptParser::​_parse_block(GDScriptParser::​BlockNode *, bool): Code can never be reached because of a logical contradiction 
![QWWE](https://user-images.githubusercontent.com/41945903/61889227-565acf80-af05-11e9-8cea-fc28b17fc05c.png)
- [x] 15. Negative array index read
A memory location at a negative offset from the beginning of the array will be read, resulting in incorrect values.
In EditorInspector::​remove_inspector_plugin(Ref<EditorInspectorPlugin> const &): Negative value used to index an array in a read operation 
![Screenshot_20190725_175919](https://user-images.githubusercontent.com/41945903/61889679-23fda200-af06-11e9-9534-f7f1e817036c.png)
- [x] 16. Negative array index read
A memory location at a negative offset from the beginning of the array will be read, resulting in incorrect values.
In AnimationNodeBlendSpace2D::​process(float, bool): Negative value used to index an array in a read operation 
![Screenshot_20190725_180212](https://user-images.githubusercontent.com/41945903/61889773-57d8c780-af06-11e9-85ee-0dadc92a5ca7.png)
![Screenshot_20190725_180155](https://user-images.githubusercontent.com/41945903/61889783-5a3b2180-af06-11e9-86d5-17e367941578.png)
- [x] 17. Negative array index write
A memory location at a negative offset from the beginning of the array will be written, likely causing a crash later.
In AnimationNodeBlendSpace1D::​process(float, bool): Negative value used to index an array in a write operation 
![Screenshot_20190725_180316](https://user-images.githubusercontent.com/41945903/61889869-848cdf00-af06-11e9-847b-d62e1b9d9faa.png)
![Screenshot_20190725_180301](https://user-images.githubusercontent.com/41945903/61889870-85be0c00-af06-11e9-9a29-9ed3b5536ffe.png)
- [ ] 18. String not null terminated
The function may iterate past the end of the buffer looking for a null terminator.
In detect_prime(): A character buffer that has not been null terminated is passed to a function expecting a null terminated string
![Screenshot_20190725_180428](https://user-images.githubusercontent.com/41945903/61889940-b2722380-af06-11e9-8b22-4927db861007.png)
- [x] 19. Useless call
A function call that seems to have an intended effect has no actual effect on the logic of the program.
In Control::​_compute_child_rect(float const *, float const *): A function is called that is only useful for its return value, and this value is ignored.
Probably there should be
`result = result.grow_margin((Margin)i, p_anchors[i] * anchorable.get_size()[i % 2] + p_margins[i]);`
![Screenshot_20190725_180552](https://user-images.githubusercontent.com/41945903/61890029-e6e5df80-af06-11e9-93ea-d6de7b9a2053.png)
- [x] 20. Arguments in wrong order
The function call will not have its intended effect.
In EditorSceneImporterAssimp::​create_light(AssimpImporter::​ImportState &, AssimpImporter::​RecursiveState &): The arguments to a function call are provided in the wrong order. 
![Screenshot_20190909_075523](https://user-images.githubusercontent.com/41945903/64506356-9fa98780-d2d7-11e9-8e5b-7a96bb55a5fa.png)
- [x] 21. Arguments in wrong order
The function call will not have its intended effect.
In EditorSceneImporterAssimp::​create_light(AssimpImporter::​ImportState &, AssimpImporter::​RecursiveState &): The arguments to a function call are provided in the wrong order. 
![Screenshot_20190909_075944](https://user-images.githubusercontent.com/41945903/64506458-f7e08980-d2d7-11e9-8925-9f0ba1a37e9f.png)

**Comment by MaciejKucia** [comment]
How about using sonarcloud.io in travis-ci?

**Comment by qarmin** [comment]
I already setup sonarcloud with Gitlab CI, because Travis doesn't allow me to compile and scan project due to too small time limits.

Sonarcloud project(I try to update all projects weekly) - https://sonarcloud.io/project/issues?id=qarmin_godot&resolved=false&types=BUG

**Comment by qarmin** [comment]
Suppressed by https://github.com/godotengine/godot/issues/44172
