### ISSUE TITLE
Godot 3.1 - Android 6\7 Invalid Class

### ISSUE THREAD

**Issue by nemesis567** [godotengine/godot#30770]
**Godot version:**
3.1-stable

**OS/device including version:**
Android 6, 7
Compiled on Windows 10

**Issue description:**
`ATAL EXCEPTION: GLThread 557
Process: com.murderintheshadows.aelia, PID: 9604
java.lang.ClassNotFoundException: Didn't find class "org/godotengine/godot/GodotShare" on path: DexPathList[[zip file "/data/app/com.murderintheshadows.aelia-1/base.apk"],nativeLibraryDirectories=[/data/app/com.murderintheshadows.aelia-1/lib/arm64, /data/app/com.murderintheshadows.aelia-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at org.godotengine.godot.GodotLib.setup(Native Method)
	at org.godotengine.godot.Godot$2.run(Godot.java:311)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1481)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "org/godotengine/godot/GodotFacebook" on path: DexPathList[[zip file "/data/app/com.murderintheshadows.aelia-1/base.apk"],nativeLibraryDirectories=[/data/app/com.murderintheshadows.aelia-1/lib/arm64, /data/app/com.murderintheshadows.aelia-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
		... 7 more`

**Steps to reproduce:**
You can download the project bellow, compile, export and try to run on android 6, app crashes with error above.
This runs fine on Android 8+

**Minimal reproduction project:**
https://github.com/Shin-NiL/Godot-Share

**Comment by akien-mga** [comment]
Please report the issue at https://github.com/Shin-NiL/Godot-Share, from the description it's not clear that there is any issue with Godot itself, but more with the distribution of that module.
