### ISSUE TITLE
Ability to convert scenes to full fledged "Node Plugins"

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3077]
Since we have ability to save scenes to file, and attach them to the scene like almost any ordinary
predefined node, the next natural step would be to to allow people to convert these scenes into some kind of "node plugin" that could be shared even more easly between projects in more easily and 'standardized' way than currently. 
Basically when we put 'Node Plugin' folder somewhere inside the project folder, editor should automatically detect it (or allow to add it from settings) and add proper entry in "Create new node" window.  (Additionally  there could be a folder inside ~/.godot/ that would collect all the 'node plugins' for use in all our projects without the need to define them in each project separately)

Couple observations:
* There is need for some kind of 'public/protected' modifier for gdscript, to disallow users changing internal state of 'plugin node' in not planned way.
* Scripts that are added to root node of plugin should not be visible in inspector, and user should be able to define it's own script for this node if he need (just like it's with build in nodes) (I assume this script should by default extend after the script from 'plugin node').
* There should be possibility to contain more than one 'Node definition' inside single plugin. Some plugins might require to operate on higher amount of node types in order to work (i.e. StateMachine node might need to operate on 'State' nodes). Guess the easiest way to achieve this might be to simply allow to define main folder that contain more than one 'root node plugin' at the same level (referencing to other plugins(node types) would be easy thanks to relative paths).  
* In "Create new node" window there should be some kind of separator to separate build in nodes, from those that comes from the plugins folder.
* Other things that need to be considered is to allow plugin creator to define an icon for 'plugin node'
* Godot help system should be able to display descriptions written by plugin creators for public functions, members, signals and the plugin itself. 
* I know that there are currently available "editor plugins", which allows developers to write widgets that are used by Godot editor itself. It might be good idea to allow distribute 'scene plugins' together with these editor ones in a transparent - not noticeable for user - way, since I can imagine someone might want to write 'node plugin' that might be editable only via editor plugin.
* Creating a plugin should not be very complicated process and should allow developers to gain better reusability of some parts of the project (even if they want these plugins only for internal use like "Enemy" node, and thanks to help system developers could easily document those plugins for their less technical co-workers).
* Node plugins should not be allowed to be created, if they are using any resource that is located  outside of the main folder for given plugin. Thus all paths should be relative, and all inner scenes should be located inside plugin folder.
* As an exception from above,  there should be possibility to define plugin that is depended on another plugin (one or more).
* It also seems that nodes that are part of the editor plugin should not be visible from the outside world (someone who is using plugin node as a root node for it's scene could be very surprised by what  get_children() is returning). Some random idea: As alternative provide some global way to set node visibility as ?public/protected/private? In this case I don't have clear idea how this exactly should work, and be represented in editor right now, guess some feedback from main devs is needed. 
* Idea on how creation of such plugin could look: Scene -> convert to plugin option. After selecting, some kind of simple wizard/guide could be launched that would validate scene and look for not relative paths in .gd (?or resources that are outside the folder?) and show validation alerts. There also could be some short "howto" in this place, as well as other necessary steps (depending on idea implementation: i.e file icon chose, pointing out which folder is a main folder for the plugin as a whole, etc).
* Sounds like implementation of some of these things would require some additions to gdscipt. I know that in 2.1 there are plans to add new scripting language with static typing, maybe creation of 'node plugins' should be possible when using this new language? 
* Also this would be some start point for developers to create more generic, **encapsulated** scenes that could be more easily shared on the upcoming asset store. 

These ideas in their core are currently generally achievable by using some rules when creating scenes. This feature request is opened more in hope to standardize some things and make them more automatic, native and pleasant to use. 

**Edit: Further (maybe little crazy) ideas:**
* It's totally possible currently to write 'subscene', that in order to work need some other node that is delivered by the user from editor depending on the situation (currently we can just add a node to the scene loaded from file, or click 'edit' button and add node to any child of subscene). But there are some problems with this approach: 
 - first of all, the user need to know internal structure of the node-plugin, it need to know where to add given node and how to name it.
 - Node-plugins by it's nature should hide it's internal implementation from the outside world
This problem might be partially solved by exported variables, but this is not always straightforward (for example plugin could want from user to provide Position3D nodes to point some concrete transform).
 - Because of all this it would be cool if there could be an ability to define plugin-placeholder nodes, that would be visible as a childrens of a plugin-node when it's added to the editor (All other children are hidden). Thanks to these nodes user will be able to 'inject' some concrete nodes  inside the plugin by replacing those placeholders. 
 - Another approach to this problem would be to just give ability for selected nodes to be visible in scene tree editor as a child of node-plugin. (Not involving any kind of placeholder concept), this would allow users to modify these concrete internal nodes ([move]/[scale]/[add new child] - exactly the same way how it's possible currently with any child when SubScene is editable).

**Comment by reduz** [comment]
fantastic. Will work on this in 2.1 so all this feedback is amazing

**Comment by toger5** [comment]
Finally I found that issue. 
I was sure someone had this idea too. (I almost started a similar issue, which would have been less detailed and structured ;) but about the same topic) good I found this one.

I really love the idea to make give the user the ability tk create assets in a form of "plugin nodes" I believe that is one of the biggest strength of the whole scene system.

- I can imagine that it is much faster simpler to import a 3D mesh as an node (for example from the asset sture) than creating the node connecting it to the right mesh recource, and than to the right shader an texture. (texture assets become sprite nodes, character assets become spatial nodes with a proper rig setup and mesh and animations as children...)
 - There also should be the option in the project luncher to start a "asset/plugin scene" without creating a project.This would be great for little tests (you dont need to create a project folder an delete if afterwards) And also for creating assets (obviously)
 - In addition this feature is great to use in combination with the tool mode of gd script. nodes can be extreamly difficult with a lot of setup (export) variables, so you can use them extreamly flexible. (ndee recently uploaded a video about the use of the tool mode and showed some giod ideas)
 - Combined with the idea of creating placeholder nodes this is even more powerful. btw placeholder nodes arn't even necessary if you use export variables for the nodes ( packed scenes) you need so you can attach what you need. (if this is supported if not that would be a nice feature, maybe a feature could be added ti create unattached (not attached to the root node) in the same scene. So you can store nodes which can be added to the scene during runtime without using packedScenes. those nodes ghan also could be used to pass to export variables)

I'm extreamly exited abouthe possibility this featureset would offer (especially with the asset store.) Imagine you can use a map uploaded in the asset store which would be created of a lot of spatial nodes (from the asset store created by other users), which is fully animated and has features like traps which are than activated by a node which is specified through an export variable or a placeholder node. for this node you use a downloaded FPS character controller which has a exported var for a cool spacial node (a fully animated gun from the asset store, of corse). so you attach that character to your map_asset and have your first game. This is sounds very convinient especially for beginners.
which would maybe lead to a much bigger community.

all in all i can see a huge amount of potential in such a system (basicly its the the node system itself which makes all that possible. so I should put it in other words, what i mean is the "community integration" of the node system which increases the popularity and the feature set of the engine)
so if I could i would give that thread +23 but thats not commenly used so:
+1

**Comment by DenisComtesse** [comment]
A big fat +1
I'd love to see this in Godot. It would not only become easier to exchange assets, this would also add a whole new level of flexibility in organising projects.

**Comment by akien-mga** [comment]
What's the status on this after the work on the EditorPlugin API?

**Comment by kubecz3k** [comment]
@akien-mga Well I guess this issue can be closed, since it was more a hint for @reduz on how I would see this. In the end plugins are implemented in different way, some of those ideas are addressed others are not, guess the api will improve in time due to feedback from community and there is no longer need for this  issue which at current moment is quite detached from reality.
