### ISSUE TITLE
User set boot_splash gone on Android when checking Compress to RAM

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3079]
In Godot 1.1(stable) when using 'Compress to RAM (BC/PVRTC/ETC)' option in 'Project Export Settings' and exporting to android device (by pressing android button above help tab) my own splash (boot_splash set in 'Project Settings') was gone. At start the default Godot logo was displayed. 
When exporting to Linux boot_splash is displayed correctly.

**Comment by akien-mga** [comment]
Is this issue also valid in the current master branch / a recent build? (you can try one of the unofficial builds from fixnum.org/godot as the official nightly builds seem outdated)

**Comment by reduz** [comment]
This is fixed on master

**Comment by akien-mga** [comment]
Closing then as we have no plan to release a bugfix for 1.1 as 2.0 is just around the corner.
