### ISSUE TITLE
Document test_move in KinematicBody2D's move_and_collide function

### ISSUE THREAD

**Issue by 2DemiGods** [godotengine/godot#30808]
As we've already seen, the kinematic body does have some slight bugs and misbehaviors.
* This feature would allow the user to code their own collision handling logic in a physics system.
* This will not break existing code as _something_ is regarded as true and _nothing_ is regarded as false
* I assume this would be a simple change as this is test for collision so returning the results should not present a major change in logic

**Comment by Xrayez** [comment]
What Godot version do you use? I see there's `test_only` parameter in `move_and_collide` in master branch:

`KinematicCollision2D move_and_collide( Vector2 rel_vec, bool infinite_inertia = true, bool exclude_raycast_shapes = true, bool test_only = false )`

So you'd have to call it like this to test whether the body would collide without moving it and returning useful information as well:
```gdscript
var collision = move_and_collide(velocity, true, true, true)
if collision:
    move_and_collide(velocity) # for real
```

**Comment by Xrayez** [comment]
Also note that the `test_only` parameter is documented in `KinematicBody` but not in `KinematicBody2D` which is a separate issue.

> If test_only is true, the body does not move but the would-be collision information is given.

**Comment by 2DemiGods** [comment]
> 
> 
> What Godot version do you use? I see there's `test_only` parameter in `move_and_collide` in master branch:
> 
> `KinematicCollision2D move_and_collide( Vector2 rel_vec, bool infinite_inertia = true, bool exclude_raycast_shapes = true, bool test_only = false )`
> 
> So you'd have to call it like this to test whether the body would collide without moving it and returning useful information as well:
> 
> ```gdscript
> var collision = move_and_collide(velocity, true, true, true)
> if collision:
>     move_and_collide(velocity) # for real
> ```

I am using godot 3.1.1

> 
> 
> Also note that the `test_only` parameter is documented in `KinematicBody` but not in `KinematicBody2D` which is a separate issue.
> 
> > If test_only is true, the body does not move but the would-be collision information is given.

This seems to my problem, as I was using KinematicBody2D.

I guess this should move over to docs then. please close the issue if you think that's the case.
