### ISSUE TITLE
Option to Remove delete node confirmation

### ISSUE THREAD

**Issue by keenfoong** [godotengine/godot#30805]
I have a feature request to have an option to remove the "Delete Node(s)?" confirmation when deleting a node the the scene:
![2c9256b6023d920aaf90da9c7027fc9c](https://user-images.githubusercontent.com/31301148/61845063-17b51d00-aee5-11e9-97c7-7d5168a3862d.png)

**Godot version:** 3.1.1 Standard 64bit
**OS/device including version:** Windows 10

It is a bit redundant to have it there, the delete key is pretty far from everything else so it's a bit hard to fat finger it and you can always undo it pretty easily. It can be a bit obstructing for people who like to work by starting rough and by prototyping. Then polishing afterwards.

**Comment by Anutrix** [comment]
We could add a editor setting to toggle it but removing is bad idea. New users will have trouble.

**Comment by keenfoong** [comment]
Yeah definitely as an option. Even as a new user though, I would think they can undo if they accidentally delete.

Just a note that other software with object hierarchies also deletes without confirmation as well (Unity, Blender, Maya)

**Comment by TheSHEEEP** [comment]
Maybe both can be combined.
What I have also seen in other software (and games) is that the window asking for confirmation has a little checkbox "don't show this anymore". When ticked, the window won't show anymore after that.
Combined with the option to bring it back or hide it from the get-go, this would seem optimal.

**Comment by KoBeWi** [comment]
Looks like there's a `delete_no_confirm` shortcut already (Shift + Delete). I guess it should get removed if there was an option to delete without confirming. Or maybe the shortcut is enough?

**Comment by Calinou** [comment]
I think it makes sense to remove the node confirmation too, as long as undo support works reliably.

**Comment by girng** [comment]
I can't believe this is an issue, lol

**Comment by KoBeWi** [comment]
Closing this as per https://github.com/godotengine/godot/pull/30816#issuecomment-533882845
Just rebind "Delete No Confirm" to Delete key.

The only benefit of removing this confirmation is that it wouldn't appear from context menu (and if someone wants to remove confirmation, I doubt they use the context menu).
