### ISSUE TITLE
Godot does not respect cull mode in the occluder

### ISSUE THREAD

**Issue by fopeczek** [godotengine/godot#30818]
Godot version: 3.1.stable.official
Ubuntu 18.04
Intel vga driver

Steps to reproduce:
See the time-lapsed movie https://www.youtube.com/watch?v=ipEIrlmbKbw&feature=youtu.be and the attached game project.

[New Game Project.tar.gz](https://github.com/godotengine/godot/files/3432249/New.Game.Project.tar.gz)

**Comment by raphael10241024** [comment]
You have set `closed` to true, so the occluder begin and end points was connected. Uncheck it and you will see the differences.

**Comment by adamryczkowski** [comment]
I didn't know that, thank you for the answer!

**Comment by clayjohn** [comment]
Question is answered correctly, I would add the documentation label, but it is already documented here http://docs.godotengine.org/en/latest/tutorials/2d/2d_lights_and_shadows.html

Closing accordingly.
