### ISSUE TITLE
Custom mouse pointer hotspot not working

### ISSUE THREAD

**Issue by soloparatolos** [godotengine/godot#3082]
Custom mouse pointer hotspot is not working as far as I tested. The value keeps pointing coords 0,0 no matter what.

After closing and opening the project again the hotspot option is unchecked and weirdly, in different position in the list of preferences.

**Comment by kubecz3k** [comment]
Can confirm on 69c79c0d4a6107313c24fa1202d9709551d95c03

**Comment by reduz** [comment]
this code will be rewritten in 2.1, for now won't touch it

**Comment by reduz** [comment]
code will be rewritten for 3.0, we didn't make it in time, sorry :( we'll be expecting to lose binary compatibility so it should make more sense for 3.0

**Comment by akien-mga** [comment]
Fixed by #6250.
