### ISSUE TITLE
Handle clicking on AudioStream change in AudioStreamPlayer2D/3D

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#30827]
**Godot version:**
3.2 master (3a68b241)

**OS/device including version:**
All

**Issue description:**
#25974 aimed at fixing a clicking noise when changing AudioStreams as reported in #25087, but it introduced bugs and was reverted by #28469.

Then @reduz implemented a proper fix for `AudioStreamPlayer` in 040b59c, but did not do it for `AudioStreamPlayer2D` and `AudioStreamPlayer3D`. The code from this commit should be ported over to those two classes.

**Comment by fahlmant** [comment]
I'd be interested in giving this a try

**Comment by alokranjan1234** [comment]
is this issue still open? I would like to work on it.

**Comment by Calinou** [comment]
@alokranjan1234 It seems like it's still available for grabs, go ahead :slightly_smiling_face:

**Comment by fahlmant** [comment]
Haven't had time yet, so go ahead

**Comment by SamSindt** [comment]
Anyone still working on this?

**Comment by Calinou** [comment]
@SamSindt It doesn't seem like anyone is working on it currently, so you could give it a try.

**Comment by hbina** [comment]
@SamSindt are you working on this still?

I was reading the code and have a few questions, why are certain variables `volatile`? I don't think the usage (the only one --- where you are dealing with specialised hardware that writes to memory) applies here.

**Comment by SamSindt** [comment]
@hbina I am still working on it but am having trouble replicating the bug on MacOS. Feel free to give it a try.

**Comment by hbina** [comment]
Kewl, I don't quite understand how to apply the changes from reduz's patch because there are lots of different functions from there and here...

**Comment by Calinou** [comment]
Removing the **`junior job`** label, as it doesn't seem easy to implement.

**Comment by gdesecrate** [comment]
I am having this issue in my game. But reading your comments ... gave me and idea. Spawn new StreamPlayer3D node every time new sound is played. And delete it when sound ends. I love you guys!

**Comment by SoapSpangledGames** [comment]
I am having this problem (and other audio problems which don't belong with this issue) on 3.2 stable with AudioStreamPlayer on Linux. It doesn't matter if the audio is wav or ogg. The audio is flawless if played with automatic looping, but has painfully obvious clicks/static when played by changing streams. (AudioStreamPlayer.stream=x).

**Comment by Calinou** [comment]
@SoapSpangledGames As a workaround, try creating a new AudioStreamPlayer after freeing the previous one.

**Comment by SoapSpangledGames** [comment]
The problem persists when I change my code to create a new AudioStreamPlayer after freeing the previous one. 

Initially, I created the AudioStreamPlayer as part of the scene design, and just changed the stream as each sound finished playing. 

After your suggestion, I removed it from the scene design in the IDE, and created it in code, queue_free()'ing it and recreating it in my finished() event handler. Either way, the clicking is still present.

**Comment by Calinou** [comment]
How long is the sound? This is likely a different problem then (#22016).

**Comment by SoapSpangledGames** [comment]
The sounds are 0.1 seconds to 0.7 seconds (the 0.7 second sound is silence), played in rapid succession.

**Comment by ellenhp** [comment]
This should be fixed in 4.0. @akien-mga Do we want to keep this issue open for 3.x?

**Comment by akien-mga** [comment]
Let's closed as fixed in 4.0 then. If anyone wants to work on a non-intrusive fix for this issue in 3.x though, feel free to.
