### ISSUE TITLE
set_inertia on RigidBody2D to greater than zero prevents set_mode from working correctly

### ISSUE THREAD

**Issue by mcardellg** [godotengine/godot#30838]
**Godot version:**
3.1.1 stable official

**OS/device including version:**
Windows 10 Home

**Issue description:**
When using set_inertia on a RigidBody2D setting anything greater than zero prevents set_mode from working correctly.
Specifically: if in MODE_CHARACTER and set_mode(RigidBody2D.MODE_RIGID) is used the MODE flag changes to MODE_RIGID but the body continues to act as MODE_CHARACTER.
Note that by removing the first set_inertia instruction from the script (the one that sets inertia to a very small value >0) all then works fine.

**Steps to reproduce:**
Run the NODE2D scene in the attached project, press "down arrow" which should switch the RigidBody2D from Character to Rigid. The mode flag changes but the body`s behaviour does not. The body should start to rotate as torque is being applied.
You can check the current mode and inertia by pressing "Enter". Press 'Up Arrow" to switch back to rigid mode.

**Minimal reproduction project:**
[rigidbodybug.zip](https://github.com/godotengine/godot/files/3435819/rigidbodybug.zip)

**Comment by mcardellg** [comment]
After two weeks, not even a confirmation? 
Has anyone even noticed this bug report?

**Comment by raphael10241024** [comment]
Changing mode to MODE_RIGID_CHARACTER, MODE_STATIC and MODE_KINEMATIC will clear custom inertia value, so resetting inertia after you switch to MODE_RIGID is a temporarily solution, I'm solving this.

**Comment by mcardellg** [comment]
Thanks  Raphael, sadly the work around does not seem to work for me. 
Possibly I am doing something wrong, do you have a working example by any chance?

Incidentally is there a reason why get_inertia can return zero but set_inertia(0) returns an error?

**Comment by raphael10241024** [comment]
Write it like that :
`set_mode(Rigidbody2D.MODE_RIGID)
set_inertia(1)`
Seems the code forget that inertia can be a value <= 0, so `set_inertia(0)` cause errors,  I'll delete the checking.

**Comment by mcardellg** [comment]
Sorry Raphael but it still seems to do the same, the code in my example now looks like this:
`extends RigidBody2D

func _ready():
	set_inertia(1)
#	set_inertia(0)

func _process(delta):
	if Input.is_action_pressed("ui_up") and get_mode() != RigidBody2D.MODE_CHARACTER: 
		print("MODE BEFORE: ", get_mode())
		set_mode(RigidBody2D.MODE_CHARACTER)
		set_inertia(1)
		set_angular_velocity(0)
		set_rotation(0)
		print("MODE AFTER: ", get_mode())
	if Input.is_action_pressed("ui_down") and get_mode() != RigidBody2D.MODE_RIGID: 
		print("MODE BEFORE: ", get_mode())
		set_mode(RigidBody2D.MODE_RIGID)
		set_inertia(1)
		set_angular_velocity(0)
		set_rotation(0)
		print("MODE AFTER: ", get_mode())
	if Input.is_action_pressed("ui_accept"):
		print("MODE NOW: " , get_mode(), " Inertia: ", inertia, " angular_velocity: ", angular_velocity, " rotation: ", rotation) 

func _integrate_forces(state):
	set_applied_torque(10)`

Still seems to go into RIGID and never go back to CHARACTER.
Perhaps I can work around by manually simulating character mode, any tips on what settings I would have to manually fix? (very high inertia perhaps, zero rotational velocity?)

Thanks for the help, 
Giles

**Comment by raphael10241024** [comment]
Write it like this :
`extends RigidBody2D


func _process(delta):
	if Input.is_action_pressed("ui_up") and get_mode() != RigidBody2D.MODE_CHARACTER: 
		print("MODE BEFORE: ", get_mode())
		set_mode(RigidBody2D.MODE_CHARACTER)
		applied_torque = 0
		angular_velocity = 0
		print(get_inertia())
		print("MODE AFTER: ", get_mode())
	if Input.is_action_pressed("ui_down") and get_mode() != RigidBody2D.MODE_RIGID: 
		print("MODE BEFORE: ", get_mode())
		set_mode(RigidBody2D.MODE_RIGID)
		set_applied_torque(1000)
		set_inertia(10)
		print("MODE AFTER: ", get_mode())
	if Input.is_action_pressed("ui_accept"):
		print("MODE NOW: " , get_mode(), " Inertia: ", get_inertia())`
