### ISSUE TITLE
accessing var.instance() issue

### ISSUE THREAD

**Issue by dijam8** [godotengine/godot#30836]
**Godot version:**

3.1

**OS/device including version:**

ubuntu 18.04.2/intel

**Issue description:**

i did :
var derictions
var hit=preload("res://Area2D.tscn")
var hit2=hit.instance()
hit2.direction = derictions
and hit2.direction did not change 
**Steps to reproduce:**

**Minimal reproduction project:**

[platformer 2.zip](https://github.com/godotengine/godot/files/3435806/platformer.2.zip)

**Comment by dijam8** [comment]
blev me gays this is a bug in godot 3.1

**Comment by akien-mga** [comment]
Well your `derictions` variable has no value, so assuming that `Area2D.tscn`'s `direction` member variable also is uninitialized, then yeah this code won't change it. You assign `null` to the member variable.

This is not a bug in the engine, and you should use other community platforms for support when learning how to use the engine, for example the Q&A, Discord or Forums: https://godotengine.org/community

**Comment by dijam8** [comment]
i am sorry i jest forget to writ var derictions = 1
