### ISSUE TITLE
Label's 'Autowrap' is broken for words bigger than its width

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#30832]
**Godot version:**
 d483a85

**Issue description:**
While having `Autowrap` enabled in a `Label`, if a word inside of it is bigger than its width, it will not wrap it:
![Screenshot_20190725_235349](https://user-images.githubusercontent.com/30739239/61922619-a317c800-af50-11e9-85f8-d84f11acc0f3.png)

**Comment by girng** [comment]
this used to work
