### ISSUE TITLE
enemy killing issue

### ISSUE THREAD

**Issue by dijam8** [godotengine/godot#30835]
**Godot version:**

3.1

**OS/device including version:**

ubuntu 18.04.2/intel
**Issue description:**

when enter attack is true is when they enter an erea2d called attack ;and it is so close from the player it is as far as its weapon .
what hapend is wen i attack a random enemey it get into attack area2d and it call signal _on_attack_body_shape_entered then when i pres the attack botton it call the signal _on_player_hit then it reduces health until it hit 0 then an if methud call queue_free() .
i think if i hit a player the health reduces on all enemy code and thats why they all die .
what i want from you is how can i attack spesifec enemy and only he die
**Steps to reproduce:**

**Minimal reproduction project:**

[platformer 2.zip](https://github.com/godotengine/godot/files/3435768/platformer.2.zip)

**Comment by sparkart** [comment]
This is for reporting bug issues regarding the actual Godot Engine and not bugs regarding your particular project. For help, you can go to: https://godotengine.org/qa/ or Discord: https://discordapp.com/invite/zH7NUgz

**Comment by groud** [comment]
As @sparkart stated, this is not the place to ask about how to use the engine, but to report bugs or ask for new features. Please use the [other community channels](https://godotengine.org/community) for that.
