### ISSUE TITLE
GDNativeLibrary editor should let you filter platforms with checkable entries

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#30841]
**Godot version:**
3.1.1 and 3.2 master (d483a85)

**OS/device including version:**
 Mageia 7 x86_64

**Issue description:**
When you create a `GDNativeLibrary` resource, a specific editor is shown. It has a drop-down list to select platforms which should be visible, but it's all or nothing as it uses exclusive radio buttons:
![Screenshot_20190726_163808](https://user-images.githubusercontent.com/4701338/61959487-cb8cda00-afc3-11e9-9235-ffda89152017.png)

This popup menu should use checkboxes so that you can select the platforms you want to see.

**Steps to reproduce:**

- Open project
- On Inspector, click "Create new resource"
- Select GDNativeLibrary
- Uses drop-down list to filter platforms, see that you can only filter "All" or any single platform

**Comment by NilsIrl** [comment]
Working on it
