### ISSUE TITLE
GDNativeLibrary editor can't be expanded initially

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#30840]
**Godot version:**
3.1.1 and 3.2 master (d483a85a)

**OS/device including version:**
Mageia 7 x86_64

**Issue description:**
When you add a new resource of type `GDNativeLibrary`, a specific editor plugin is shown. However, it cannot be expanded as the grabber button doesn't appear on hover, and the "Expand Bottom Panel" button is also missing:

![Screenshot_20190726_163309](https://user-images.githubusercontent.com/4701338/61959260-515c5580-afc3-11e9-908e-4b5505a103a7.png)

Once you switch to another bottom dock (e.g. `Animation`) and back, the panel can be expanded with both grabber and "Expand Bottom Panel" button.

**Steps to reproduce:**

- Open project
- On Inspector, click "Create new resource"
- Select GDNativeLibrary
- See that you can't resize the bottom dock
- Switch to another dock and back
- Now it's fine

**Comment by NilsIrl** [comment]
Can confirm on e4ec59b6a.

**Comment by NilsIrl** [comment]
Working on it

**Comment by NilsIrl** [comment]
![image](https://user-images.githubusercontent.com/26231126/61996139-36f0ad80-b091-11e9-948c-e4d5245998d2.png)

It would probably be better if it never disappeared. Even when the panel is hidden.

**Comment by NilsIrl** [comment]
Actually this is not possible because the editor will not be able know which tab to expand.
