### ISSUE TITLE
Invalid operands 'int' and 'Nil' in operator '+' when running ANY project on Linux in Godot Editor (64bit version) in 64bit system

### ISSUE THREAD

**Issue by MasterPolska123** [godotengine/godot#30848]
**Godot version:**

**OS/device including version:**

**Issue description:**
Invalid operands 'int' and 'Nil' in operator '+'. It occurs when you run any project in godot 3.2.dev, 3.1.1 and 3.1 on Linux Ubuntu (18.10 amd64). Tested even on a project containing an empty stage, without any script.

**Steps to reproduce:**
Just build Godot for x11-64 and run any project
**Minimal reproduction project:**
All projects.

**Comment by akien-mga** [comment]
I can't reproduce that, nor can thousands of Linux users on 64-bit systems. So we'll need more information to debug. This error is unlikely to happen without having any script, as it's a GDScript error.

**Comment by MasterPolska123** [comment]
Download any project (for examle my godot project - Pixel Zone - https://github.com/MasterPolska123/Pixel-Zone-master) and run it in Godot compilation from the current source code.
I've already given you everything about that error, I could.

I will know about this error.


I should not ask abuot it here, but I have no choice...

You can tell me why I got banned at https://www.facebook.com/groups/godotengine

My profile on facebook is:https://www.facebook.com/KarolTomaszewski123

I would be grateful if you removed the ban from my account. This group is important to me (it's a pity you do not know how much). If you look at our conversation, read the last 15 messages. One of them is important and even if you continue to ignore me, it's very important that you read it.

I'm sorry, but it was the only option to get in touch with you in any way.

**Comment by akien-mga** [comment]
> Download any project (for examle my godot project - Pixel Zone - https://github.com/MasterPolska123/Pixel-Zone-master) and run it in Godot compilation from the current source code.

So a 300 MB project using various addons and which generates a huge number of errors when you run it -- that's hardly "any project".

The issue you have is due to bugs in your project and/or the addons you're using.

Check the debugger and the terminal output:
```
Running: /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64 --path /home/akien/tmp/godot/bug/Pixel-Zone-master --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 27689 --position 448,240
Godot Engine v3.2.dev.custom_build.e4ec59b6a - https://godotengine.org
ERROR: put_packet: Condition ' p_buffer_size + 4 > output_buffer.size() ' is true. returned: ERR_INVALID_PARAMETER
   At: core/io/packet_peer.cpp:249.
OpenGL ES 2.0 Renderer: AMD VEGAM (DRM 3.30.0, 5.1.18-desktop-1.mga7, LLVM 8.0.0)
 
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://sounds/cutscenes/rendered/0001-0183.ogg
   At: editor/editor_file_system.cpp:1784.
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://sounds/cutscenes/rendered/Chooseoutput00000230.ogg
   At: editor/editor_file_system.cpp:1784.
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://sounds/cutscenes/rendered/0001-0183.ogg
   At: editor/editor_file_system.cpp:1784.
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://sounds/cutscenes/rendered/Chooseoutput00000230.ogg
   At: editor/editor_file_system.cpp:1784.
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:814.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2199.
ERROR: _load: Failed loading resource: res://addons/HTTPSSEClient/HTTPSSEClient.gd
   At: core/io/resource_loader.cpp:283.
ERROR: poll: res://addons/GDFirebase/HTTPSSEClient/HTTPSSEClient.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://addons/HTTPSSEClient/HTTPSSEClient.gd
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://addons/GDFirebase/HTTPSSEClient/HTTPSSEClient.tscn
   At: core/io/resource_loader.cpp:283.
ERROR: start: Can't autoload: res://addons/GDFirebase/HTTPSSEClient/HTTPSSEClient.tscn
   At: main/main.cpp:1577.
ERROR: get_file_as_array: Can't open file from path: res://3d/brightness.shader
   At: core/os/file_access.cpp:603.
ERROR: _get_modified_time: Failed to get modified time for: res://3d/brightness.shader
   At: drivers/unix/file_access_unix.cpp:292.
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://sounds/cutscenes/rendered/0001-0183.ogg
   At: editor/editor_file_system.cpp:1784.
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://sounds/cutscenes/rendered/Chooseoutput00000230.ogg
   At: editor/editor_file_system.cpp:1784.
ERROR: get_line: Condition ' !f ' is true. returned: String()
   At: core/bind/core_bind.cpp:1983.
ERROR: put_packet: Condition ' p_buffer_size + 4 > output_buffer.size() ' is true. returned: ERR_INVALID_PARAMETER
   At: core/io/packet_peer.cpp:249.
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://sounds/cutscenes/rendered/0001-0183.ogg
   At: editor/editor_file_system.cpp:1784.
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://sounds/cutscenes/rendered/Chooseoutput00000230.ogg
   At: editor/editor_file_system.cpp:1784.
```
![Screenshot_20190726_225508](https://user-images.githubusercontent.com/4701338/61980924-6c958800-aff8-11e9-88e8-219edd724e7b.png)

Those are not engine bugs.

**Comment by akien-mga** [comment]
And the specific error you get in the debugger is due to the last one:
```
	var loaded_coins = parse_json(load_.get_line())
	points += loaded_coins
```
in `game_state.gd`.

If `parse_json` fails (which it does here apparently), `loaded_coins` is `null` and can't be added to an `int` variable.

Please use other community platforms to get help debug your project next time, GitHub is for engine bugs. We don't have bandwidth to help all Godot users fix their project issues.

**Comment by MasterPolska123** [comment]
In windows, there are no errors from the ones you provided. Everything works PERFECTLY.
And there was no error on windows. That's why I thought the script worked well. And I am honoring you because you were right. Thank you very much :)

> 'Please use other community platforms...' - Then why do you give me a ban on the biggest one?
Tell me at least what I got the ban for?
I will cling to it until I get the information. You have no idea how this group was important to me!

**Comment by MasterPolska123** [comment]
@akien-mga Yes, that was my mistake, so I'm sorry I was bothering you.
It is interesting to see why the windows version of godot did not indicate this serious error in the game code, the Linux version did.

I think you know that you are forced to use a google interpreter, which ... well, it does not always translate everything as it should.

And ... where did you get these errors in the Pixel Zone code (applies only to the GDFirebase addon, because at the time of writing this comment I just deleted other errors)? I only have this after starting the game in the debugger. [pictures]


![Zrzut ekranu z 2019-07-27 20-07-58](https://user-images.githubusercontent.com/45912895/61998112-54327580-b0ab-11e9-8d3a-646c87e31afd.png)


![Zrzut ekranu z 2019-07-27 20-09-08](https://user-images.githubusercontent.com/45912895/61998106-3533e380-b0ab-11e9-8aee-552241d449a3.png)

I would like to reward you for this invaluable help, but I think this is not the right place. Contact me, for example, via email and talk about it. I am also sorry for spam on the conversation.
