### ISSUE TITLE
"Script" property from "Editor settings" should be erased/hidden

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3084]
I was messing today with "script" property from Godot editor settings. Don't know what it does but I was able accidentally  erase all my editor settings :)
From what Reduz said on irc, this property "probably should not be there"  and ask me to open an issue as a reminder. 
So hide this from gui or document it :)
Will label this as a bug since touching this property can be quite harmful.
![script_in_editor_settings](https://cloud.githubusercontent.com/assets/6129594/11819012/e6ecb73c-a35d-11e5-8447-f3f6258c8d41.png)

**Comment by reduz** [comment]
it's gone
