### ISSUE TITLE
Exported oculus quest games treated as go games

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#30854]
**Godot version:**

e4ec59b6ae7ba4da8a57d35a4763192fd84fa358

**OS/device including version:**

 Arch Linux

**Issue description:**

Exported android game is missing extra android feature line in the manifest needed for the oculus quest to give the game 6dof tracking on the controllers: https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/

**Steps to reproduce:**
1. Follow steps on the [oculus mobile github](https://github.com/GodotVR/godot_oculus_mobile) to export for oculus quest
2. Modify the demo to include controllers with a simple meshinstance as children for visualization
3. Controller tracking does not work due to the missing line in the manifest. 

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
CC @BastiaanOlij @m4gr3d

**Comment by creikey** [comment]
After adding the line `<uses-feature android:name="android.hardware.vr.headtracking" android:required="true" android:version="1"/>` as discussed in the reddit thread to the manifest the issue still "manifests". I've attatched the modified demo project with controller tracking so the issue can be reproduced. 
[demo.zip](https://github.com/godotengine/godot/files/3438041/demo.zip)

**Comment by m4gr3d** [comment]
@creikey Thanks for the update, I'll take a look.
Before the Quest firmware update, were the controller tracking correctly for you?

@akien-mga Feel free to assign the issue to me.

**Comment by creikey** [comment]
@m4gr3d yes, the controller tracking was working correctly. I'll look into it as well and let you know if I find anything.

**Comment by creikey** [comment]
@m4gr3d It was a combination of two issues, godot not exporing the game with the correct manifest and oculus changing what result was a correct error in the vrapi input library. I'm opening a pull request for both of these issues right now.

**Comment by creikey** [comment]
It turns out that the controller tracking will work correctly if the line is added to the manifest, I was testing with a modified version of the godot oculus mobile plugin that had a bug in it. Apologies.

**Comment by m4gr3d** [comment]
No problems, and thanks for the update!
Are you still working on a PR for the manifest fix, or should I handle it?

**Comment by creikey** [comment]
@m4gr3d I've created a pr for it at #30902  that just adds the line to the manifest with android required being false. If it's required to have it be an optional setting by the godot devs, then I can sort through the strange binary android manifest parser in the android platform's `export.cpp`
