### ISSUE TITLE
Button only works when you hit test scene, not work properly when testing game.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#30858]
[Game.zip](https://github.com/godotengine/godot/files/3437805/Game.zip)

Attached a .zip containing a minimal project error (Godot 3.1.1 official / GLES 2)

Issue is that the button on the Scenes/Menues/GAMEOVER.tscn doesn't work, not even produces the signal is connected to.
The real issue is that buttons on other parts of the game work properly (TITLE.tscn)

The reason why I made this issue is that the button doesn't work only when you play and lose normally by letting yourself be killed by the monsters, but it works fine when you hit test scene button and start the game from that scene.
Letting yourself wait until the timer is over also let the button work properly.

I dunno what I am doing wrong, not sure if this is a mistake from my part.

**Comment by Anutrix** [comment]
Please provide the minimal project that can reproduce this issue.
In your case, GAMEOVER.tscn and dependencies might be enough.

**Comment by ca3games** [comment]
I changed my code to work with keyboard and for some reason It also didn't worked.
Changed my code to also unpause the scene at the _ready function and it worked.
