### ISSUE TITLE
Ability to define template for empty class

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3085]
It would be nice to have ability to define template file for empty class. 
From irc Reduz would like to have this in 2.1

**Comment by akien-mga** [comment]
When implemented, these templates could be shared in the asset sharing platform.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by bojidar-bg** [comment]
Not a duplicate of #4132?

**Comment by kubecz3k** [comment]
@bojidar-bg true :)
