### ISSUE TITLE
Why android export so slow

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#30850]
**Godot version:**

Godot 3.1.2-devel (e766b16e9)

**OS/device including version:**

MacOSX 10.14.5

**Issue description:**

When I export my game it takes:
- 5 min 8 sec for android
- 1 min 45 sec for iOS
- 10 seconds for HTML5

All release builds. I think the most of time it just copying files from one folder to another. Building APK (in the end of process) takes less time then building IPA as far as I could notice.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Is it faster if you create one APK per architecture (by checking only one architecture in the Android export preset)?

**Comment by DrMoriarty** [comment]
@Calinou Selected only one architecture - armv7. Exporting time = 5 min 11 sec.

**Comment by creikey** [comment]
Building an APK requires zipping everything, so that's very likely the issue.

**Comment by DrMoriarty** [comment]
I unpacked the content of APK file and do `time zip -r -9 ga-apk.zip ga-apk/`:
```
real	0m31.531s
user	0m29.432s
sys	0m0.890s
```
If my computer can pack all files in 31 seconds, why it takes 5 minutes?

**Comment by DrMoriarty** [comment]
Ok, I have found function `_should_compress_asset` in file `godot3/platform/android/export/export.cpp` and changed it that it always returs `false`.

The original APK was 104 Mb, the new one is 108 Mb. The export time for non-packed APK is 5 min 13 secs. So packing costs nothing!

Also I saw that most types of files `_should_compress_asset` already consider as packed and not pack it twice.

So, the question is - what process takes that all time?

**Comment by DrMoriarty** [comment]
In my previous experiment I didn't consider non-resource files. Now I totally disabled all types of compression in `export.cpp`. 

The APK became 208 Mb, export time = 5 min 01 sec.

**Comment by DrMoriarty** [comment]
In my next experiment I used Z_BEST_COMPRESSION for all files. The APK file became 83 Mb. Export time = 5 min 30 sec.
Really compression costs only this 30 seconds. Other 5 minutes - I don't know what it takes.

**Comment by DrMoriarty** [comment]
more than 4 minutes takes this string:
```
 621|        ed->ep->step("File: " + p_path, 3 + p_file * 100 / p_total);
```
I commented out only this one string and get release APK in 43 seconds! I even can enable Z_BEST_COMPRESSION for all files and I will get APK in 5 times faster then before!
Why it so slow?

**Comment by DrMoriarty** [comment]
The secret of other platforms exporters is - do not call this `step` function. iOS exporter calls it only 5 times. HTML5 exporters doesn't call it at all.

**Comment by Calinou** [comment]
When running the editor on Linux, I couldn't notice a difference when exporting the Platformer 2D demo to Android with the `step()` function commented. Maybe it's only noticeable when having a lot of assets in the project?

**Comment by DrMoriarty** [comment]
@Calinou I have 4140 files in `.import` folder. When the project was small I also didn't see the difference when exported on iOS and on Android.

**Comment by MightyPrinny** [comment]
Maybe those `step()` calls should be removed for 3.2.1, android exports take considerably longer than desktop exports.
