### ISSUE TITLE
Mouse cursor visibility does not work with custom mouse cursor

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#3086]
If you add a custom mouse cursor, then the mouse mode is set to `hidden`, even though the custom cursor is visible (my guess is that this hides the OS cursor). But that also means there's no way to hide the custom cursor.

If you try to show the mouse cursor (via `Input.set_mouse_mode()`), it will then show the OS mouse cursor on top of the custom one.

This can be quickly checked by setting a custom cursor in the Window Management demo and pressing `<Esc>` to grab and release the mouse. The custom cursor will still be visible after the grab and the OS cursor will be visible after releasing the mouse.

(This may be Linux only, as I have not tested in other platforms).

**Comment by reduz** [comment]
this needs to be rewritten properly for 2.1, using hardware cursors..
right now it's kind of a hack

**Comment by akien-mga** [comment]
This will likely get worked on for 3.0 together with #4187.

**Comment by SuperUserNameMan** [comment]
this also happen under Windows.

**Comment by zaps166** [comment]
Related to: #6633 ?

**Comment by reduz** [comment]
no one ventured to fix custom mouse cursors, so kicking it for 3.1

**Comment by guilhermefelipecgs** [comment]
This was fixed, right?

**Comment by vnen** [comment]
@guilhermefelipecgs it does hide the mouse now but when it's made visible again the custom cursor is gone, the system cursor is shown instead.
