### ISSUE TITLE
[Proposal] Animate a single axis, and or Animate relative to position

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#30867]
Hello,
Is animating a single property in translation possible?
Like if i only want to animate the "y" position of an object or the "z" rotation.
I guess that whuld be animating relative to the current position?

**Comment by KoBeWi** [comment]
It is possible, but you need to enter the track manually and then insert keys via right click on the timeline.
![image](https://user-images.githubusercontent.com/2223172/61994893-5da6e800-b081-11e9-862a-41b93f8a8983.png)

Not sure if this is documented anywhere or couldn't be more accessible.

**Comment by Norrox** [comment]
Thank you, will check this out!

**Comment by Norrox** [comment]
@KoBeWi i get this error when im trying to insert a key
![error2](https://user-images.githubusercontent.com/13393087/62006890-1edb6580-b147-11e9-8a60-7b8c4b53e20f.PNG)

but if i change the property from Sprite:position.y to just Sprite:position it works

**Comment by KoBeWi** [comment]
It should be `Sprite:position:y` not `Sprite:position.y` (colon not period).

**Comment by Norrox** [comment]
ops :D thanks that works !
