### ISSUE TITLE
While editing tilemap: pressing right mouse button scroll the screen

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#30875]
**Godot version:**
Working normal in commit: 31eb116d49a8648a560354c7caa895cc7a8661c5
Broken in commit: 017b224a87064a3d333ba63809a0f12cfe2c4412

**OS/device including version:**
Lubuntu 19.04

**Issue description:**
When editing tilemap you're expected to use LMB to place tiles and RMB to erase them. They are supposed to work the same way: if you hold mouse button and move the cursor you can "brush" tiles with LMB and erase with RMB.
RMB is broken (on my Lubuntu 19.04 at least, didn't try other one) here:
https://github.com/godotengine/godot/commit/017b224a87064a3d333ba63809a0f12cfe2c4412
With RMB continue to scroll the background, making the "eraser" impossible to operate

Attached animated PNG (hope Github don't mess with it)

![sample](https://user-images.githubusercontent.com/42388967/61998230-572e6580-b0ad-11e9-9c0d-6430e8d7d11b.png)

**Comment by YeldhamDev** [comment]
CC @bojidar-bg

**Comment by bojidar-bg** [comment]
Oups! Will look into it now :smiley:
