### ISSUE TITLE
Godot crashing after converting project to 3.1

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#30871]
I recently opened a 3.06 version of a game into 3.1 stable. It asked to convert the project, to which I allowed it. Now Godot crashes every time I load the project. Here is the log file. I noticed a few FATAL errors at the bottom. Any ideas?

OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
ERROR: Error opening file: res://icon.png
At: core/io/imageloader.cpp:56:loadimage() - Error opening file: res://icon.png
ERROR: Non-existing or invalid boot splash at: res://icon.png. Loading default splash.
At: main/main.cpp:1155:setup2() - Non-existing or invalid boot splash at: res://icon.png. Loading default splash.
WARNING: The method setfriction has been deprecated and will be removed in the future, use physics material instead.
At: scene/2d/physicsbody2d.cpp:207:setfriction() - This method has been deprecated and will be removed in the future
ERROR: Condition ' psize < 0 ' is true. returned: ERRINVALIDPARAMETER
At: ./core/cowdata.h:252:resize() - Condition ' psize < 0 ' is true. returned: ERRINVALIDPARAMETER
ERROR: FATAL: Index pindex=-2147483648 out of size (size()=0)
At: ./core/cowdata.h:151:get() - FATAL: Index pindex=-2147483648 out of size (size()=0)

**Comment by qarmin** [comment]
Can you provide a minimal project? 
Without it, it can be hard to reproduce crash.

**Comment by ondesic** [comment]
I would love to create a minimal project, but I can't load the above project to begin with.  When trying to open the project, godot crashes.  All I have is the log I provided above.  I was hoping someone to figure it out with the errors I was receiving.

**Comment by akien-mga** [comment]
The first error is relatively clear, there's no `icon.png` file, or it's not valid.

The warning can be ignored for now, that shouldn't prevent running the project.

The last error looks like a variable is overflowing 32bit ints but it's not clear what it refers to.

**Comment by qarmin** [comment]
You can delete several files each time until Godot starts running.
You will then be able to narrow down the number of scripts/scenes to check and create with it minimal project

**Comment by ondesic** [comment]
I'll try that.  Thank you

**Comment by ondesic** [comment]
Ok.  I did try deleting files and see if it would run, but had no luck.  I ended up creating a new 3.1 project, imported all the scenes, sprites and scripts.  I only had to reconnect 2 signals and everything is working fine.  I didn't need to change any code.

Unfortunately, this does not help solve the bug for others who run into this same problem trying to convert..

**Comment by akien-mga** [comment]
If you still have the original non-working project, it would be good to compare its engine metadata with that of the new working version.

You should be able to find it in `~/.config/godot/projects/`

**Comment by ondesic** [comment]
**Metadata for 3.06**
"[editor_options]

update_always=false

[script_setup]

last_selected_template=""
last_selected_language="GDScript"

[export_options]

default_filename="Test Game"

[debug_options]

run_file_server=true
run_deploy_remote_debug=true

[recent_files]

scripts=[ "Node2D", "Input", "res://Superman.gd", "res://StartButton.gd", "res://Martian.gd", "res://Main.gd", "res://HUD.gd", "res://global.gd", "res://Food.gd" ]
scenes=[ "res://Main.tscn" ]

[script_text_editor]

syntax_highlighter=0


**Metadata at 3.1**

[editor_options]

update_always=false

[recent_files]

scenes=[ "res://Superman.tscn", "res://Main.tscn", "res://Martian.tscn", "res://Level.tscn", "res://HUD.tscn", "res://HUD - Copy.tscn", "res://HUD2.tscn", "res://Food.tscn" ]
scripts=[ "res://Superman.gd", "res://StartButton.gd", "res://Martian.gd", "res://Main.gd", "res://lblScore.gd", "res://HUD.gd", "res://global.gd", "res://Food.gd" ]

[script_text_editor]

syntax_highlighter=0

[dialog_bounds]

project_settings=Rect2( 945, 500, 1350, 1050 )
editor_settings=Rect2( 945, 500, 1350, 1050 )

**Comment by akien-mga** [comment]
I meant comparing the metadata for the working 3.1 remake and the non-working 3.1 port. But I'm not sure it would tell us much.

If you still have the 3.0.6 or non-working 3.1 version of the project and can share it (possibly privately) I could have a closer look at what might cause the crash, otherwise I think it's unlikely we can debug further. Thankfully I don't recall many similar reports, so it was likely a one-off issue.

**Comment by Calinou** [comment]
@ondesic Can you (or anyone else) still reproduce this bug in Godot 3.2.2 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
