### ISSUE TITLE
'FileDialog' always has the first driver selected no matter what

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#30872]
**Godot version:**
 6c9ccf1

**OS/device including version:**
GNU/Linux at least.

**Issue description:**
In the `FileDialog`, when selecting one of the drivers (which in here are the folders in "Places"), while correctly going to the location, it will still have the first one selected:
![Screenshot_20190727_124525](https://user-images.githubusercontent.com/30739239/61996633-c728f580-b085-11e9-82d6-61ab13420c57.png)

From the little digging I did, this is because `DirAccess::get_current_drive()` only checks if the beginning of the paths is equal to get its results. And since all of them start with "/home/[user]", it just always returns the first one.

Also, shouldn't "/home/[user]" be hidden to begin with? As otherwise it would lead to the dialog expanding drastically from drivers with big names.

**Comment by follower** [comment]
By "driver" I'm guessing you mean "drive" a.k.a "mount point"?

Mentioning the term here so it's findable via search, you may wish to update the title. :)

**Comment by Calinou** [comment]
> Also, shouldn't "/home/[user]" be hidden to begin with? As otherwise it would lead to the dialog expanding drastically from drivers with big names.

I'm not sure about this, as you can have multiple drives (from multiple mount points) in your Places list.

**Comment by Calinou** [comment]
@follower Sorry, I accidentally removed your comment instead of removing mine...

**Comment by YeldhamDev** [comment]
This appears to be fixed in `master`.
