### ISSUE TITLE
Redundant "Theme" button shown during edition of TileSet property of Tilemap node

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3087]
Just edit "Tile set" property of Tilemap node. Reproduced in 69c79c0d4a6107313c24fa1202d9709551d95c03 build

***Other places where this happens:***
* Same steps to reproduce on **MeshLibrary** editor in GridMap node (thanks TheHX)

Short vid to clarify on how to reproduce: https://youtu.be/IBNAwJMCrc0
As well as screenshot:
![rect4162](https://cloud.githubusercontent.com/assets/6129594/11820641/c90b5b62-a365-11e5-9138-f2b5d1010016.png)

**Comment by neikeq** [comment]
After a quick check in the source and testing the menu options, that seems to be the right plugin to edit a TileSet (same goes for MeshLibrary I guess).
You can add and remove tiles, and generate (or generate but merging) the tiles from the scene (same as what _Scene->Convert To->TileSet.._ dies).
I guess the menu title is just wrong. Also that black panel background looks weird...
BTW, I had no idea these plugins existed :astonished:

**Comment by kubecz3k** [comment]
So it looks it's a functionality and not an issue after all :dancer: 
Only one thing... are you able to use "remove selected item" button from this "theme" @neikeq ?

**Comment by akien-mga** [comment]
Well the theme should probably be adjusted to the overall 2.0 theme.
