### ISSUE TITLE
Navigation2D Using Tileset With Corners

### ISSUE THREAD

**Issue by Bloodyaugust** [godotengine/godot#30883]
**Godot version:**
3.1.1

**OS/device including version:**
Win 10/AMD Radeon R9 200 Series

**Issue description:**
After having created a tileset, and placing navigation polygons that only partially take up those tiles, it seems that corners are causing `get_simple_path` to return no solution. I've verified that the tiles line up exactly in the tileset and editor, and also that the nav polygons do as well.
When enabling navigation debug drawing, I've noticed an odd artifact that I believe may be responsible for causing the undesired behavior, but am unsure as to what is causing this artifact.

Successful case
![tilemap-pathfinding-bug-3](https://user-images.githubusercontent.com/215218/62000964-3f051900-b0a2-11e9-88fb-9d00f874368f.png)

Artifact in-game
![tilemap-pathfinding-bug-4](https://user-images.githubusercontent.com/215218/62000965-3f051900-b0a2-11e9-8fb6-5a6ab6741510.png)

Configured tilemap
![tilemap-pathfinding-bug-1](https://user-images.githubusercontent.com/215218/62000966-3f051900-b0a2-11e9-8406-87055463e947.png)

Failing case
![tilemap-pathfinding-bug-2](https://user-images.githubusercontent.com/215218/62000967-3f9daf80-b0a2-11e9-8c32-efc5ec152298.png)

**Steps to reproduce:**
- Configure tilemap with corners
- Draw navigation polys
- Attempt to use `get_simple_path` across corner tile

**Minimal reproduction project:**
[bug-repro.zip](https://github.com/godotengine/godot/files/3438754/bug-repro.zip)

**Comment by raphael10241024** [comment]
There are some error when i try to open the repro project .

**Comment by novhack** [comment]
I have encountered the same bug. When I try to create navigation polygons in the tileset editor they become messed up when running the game.
![bug](https://user-images.githubusercontent.com/42614907/72211143-658b0500-34c6-11ea-9bf0-824cebeac61d.png)

**Comment by DanielKinsman** [comment]
I get similar problems in 3.2.2 on linux.

This is my tileset with navigation polygons highlighted

![tilemap_navigation](https://user-images.githubusercontent.com/15639/89095330-2bf0fb80-d410-11ea-8a08-0215263a8625.png)

And this is in game with Debug->Visible Navigation on.

![game_navigation_debug](https://user-images.githubusercontent.com/15639/89095334-33b0a000-d410-11ea-9bce-682ac3d0de3e.png)

The white line shows a path returned from `Navigation2D.get_simple_path()`

**Comment by DanielKinsman** [comment]
Here is a sample project which should highlight the lack of a solution from `get_simple_path` when mixing tiles with different navigation polys.

![navigation](https://user-images.githubusercontent.com/15639/89148823-38a35a00-d59e-11ea-9454-f6788ed26db4.gif)

[tilenavtest2.zip](https://github.com/godotengine/godot/files/5014089/tilenavtest2.zip)

**Comment by smix8** [comment]
Same as in #41349 the TileSet Editor stores the polygon data in wrong order in the TileSet resource compared to other Editor tools that edit NavigationPolygon resources.

**Comment by akien-mga** [comment]
Fixed by #61266.
