### ISSUE TITLE
Input.is_action_pressed() inconsistent for multiple key bindings

### ISSUE THREAD

**Issue by Yoshi72** [godotengine/godot#30888]
**Godot version:**
3.1.1

**Issue description:**
If assigning multiple keys to the same action, then pressing both keys at the same time and only releasing one (while still holding the second key bound to the same action) will return false for that action in Input.is_action_pressed().
It appears that Input does not check if another key is still being pressed when a key assigned to the same action is released.

**Steps to reproduce:**
-Create a new action in the Project Settings (e.g. "move_up")
-Assign two different keys to that action ("W" and "Up")
-Create a script that checks for Input.is_action_pressed("move_up")
-Press both assigned keys at the same time ("W" and "Up")
-Release only one while still holding the other
-Input.is_action_pressed("move_up") will now return _false_ 

**Minimal reproduction project:**
[Input.is_action_pressed Bugreport.zip](https://github.com/godotengine/godot/files/3438967/Input.is_action_pressed.Bugreport.zip)
The color of the Icon will change based on Input detected for the action "do_stuff". Please press W or Space to trigger the action.

**Comment by groud** [comment]
Might be a regression from #30792 if you are using the master branch.

**Comment by Yoshi72** [comment]
Nah, this behaviour is on both, the current stable release on steam, as well as the current master branch on github (3.2.dev).
So it's safe to say that it's unrelated to the merge you mentioned.

**Comment by KoBeWi** [comment]
#30792 didn't affect this particular case, but holds related discussion. Basically, that's how the input system works. You can detect multiple key presses on single action, but the action itself is either pressed or not. There's no "button count action strength" that would count number of pressed buttons for that action and that's probably by design.

**Comment by Yoshi72** [comment]
If that is by design, then so be it. I don't mind. But I would reocmmend, to update the docs to make this clear.
https://docs.godotengine.org/en/3.1/classes/class_input.html#class-input-method-is-action-pressed

> bool is_action_pressed ( String action ) const
_Returns true if you are pressing the action event._

There is no mentioning of how it should behave with multiple keybinding.
