### ISSUE TITLE
Default environment slows down godot

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#30881]
I'm using Godot 3.1.1 stable 64 bits in GLES2 mode. 

This happens in any project, empty or not. The symptom is that Godot takes a while to load up, and then also to launch my apps. 

Removing the default environment in `Project Settings->Environment` "fixes" it (and that's how I found what was slowing it down). I've been working without any problems since I removed it... though I don't have a nice blue sky in the editor. :)

---

Windows 7
ATI Radeon HD 4800 Series (up to date)
Dual core 2.13Ghz (Intel Core Duo, iirc)

**Comment by clayjohn** [comment]
I wonder if this is related to generating the radiance map for the procedural sky. I ended up reducing the size of it and it substantially increases load times for scenes with panorama or procedural skies.

**Comment by Calinou** [comment]
@clayjohn That reminds me, perhaps we could disable radiance map generation if the framebuffer allocation is configured to "2D" or "2D Without Effects" in the Project Settings. This still requires the user to edit a project setting to benefit from faster loading times in 2D-only projects, but it won't require tweaking/removing the default environment anymore.

**Comment by clayjohn** [comment]
@Calinou Something like that is a good idea. However, the radiance map isn't tied to the Viewport, it is tied to the sky resource. So it gets created and updated separately from any Viewport. 

Also, just realized the post is talking about GLES2. I only notice a hiccup from radiance generation in GLES3. In GLES2 there isn't as noticeable difference when using a lower radiance size.

**Comment by Skaruts** [comment]
Noticed a few days ago that my apps take longer to launch when using an environment with a procedural sky. So it's the sky that makes it slow.

**Comment by Calinou** [comment]
The default environment has been removed in Godot 4.0 (in favor of the Preview Sun & Sky system), closing.
