### ISSUE TITLE
TileSet editor plugin: Remove Selected Item won't work

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#3088]
When editing a TileSet resource on the editor, there is a "Theme" menu with some options. Among them, there is an option called _Remove Selected Item_, which doesn't work (it won't pass [this condition](https://github.com/godotengine/godot/blob/master/tools/editor/plugins/tile_set_editor_plugin.cpp#L180)).
It makes sense, since there is no way to select a specific tile in the inspector.

**Comment by kubecz3k** [comment]
I can confirm this on https://github.com/godotengine/godot/commit/69c79c0d4a6107313c24fa1202d9709551d95c03 commit
