### ISSUE TITLE
Mac OS - Editor HiDPI doesn't work for external monitors

### ISSUE THREAD

**Issue by robgraeber** [godotengine/godot#30880]
**Godot version:** v3.1.1.stable.official

**OS/device including version:** Mac OS X 10.14.5

**Issue description:**
Editor HiDPI mode works when opening on Macbook Air's retina monitor. But when opening Godot on a 4k external monitor with retina mode enabled, the editor scales like it's a 4k monitor instead of respecting the retina mode.
<img width="1920" alt="Screen Shot 2019-07-27 at 4 35 35 PM" src="https://user-images.githubusercontent.com/2387719/62000525-fd6a7300-b08d-11e9-815d-783a232bc472.png">

The workaround I've been doing is setting Godot to open on my laptop monitor, then dragging the window over to the external 4k monitor.

**Steps to reproduce:**
Open any project on an external monitor with retina scaling on Mac.

**Comment by Calinou** [comment]
As a workaround, you could likely force the editor scale to 200% in the Editor Settings.

**Comment by robgraeber** [comment]
@Calinou Thanks I was looking for that setting, that works too.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment]
No answer, so closing. It was possibly fixed in 3.2.3 as there were fixes to HiDPI support on Retina displays.
