### ISSUE TITLE
GodotPhysics not working in nightly build

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#30886]
**Godot version:**
6c9ccf18f (3.2.dev.calinou.6c9ccf18f)

**OS/device including version:**
GNU/Linux x65

**Issue description:**
I tried a project on a nightly build just for curiosity and a kinematic body using move_and_collide doesn't collide with anything 

**Steps to reproduce:**
Change physics engine to GodotPhysics and try moving a KinematicBody with move_and_collide

**Minimal reproduction project:**
[SimpleKinematicTest.zip](https://github.com/godotengine/godot/files/3438931/SimpleKinematicTest.zip)

**Comment by lawnjelly** [comment]
A little more information, I just tried it on latest master and it is spamming the debug log with

`Condition ' p_point_count_A != 2 ' is true.`

A find in files suggests this might be occurring here in collision_solver_sat.cpp:
```
static void _generate_contacts_edge_edge(const Vector3 *p_points_A, int p_point_count_A, const Vector3 *p_points_B, int p_point_count_B, _CollectorCallback *p_callback) {

#ifdef DEBUG_ENABLED
	ERR_FAIL_COND(p_point_count_A != 2);
	ERR_FAIL_COND(p_point_count_B != 2); // circle is actually a 4x3 matrix
#endif
```
It does seem to be detecting the collision ok with Bullet physics.
