### ISSUE TITLE
3D viewport issue, zooming

### ISSUE THREAD

**Issue by kacmak7** [godotengine/godot#30897]
**Godot version:**
v3.1.1-stable

**OS/device including version:**
Ubuntu 18.04.2 LTS, GTX 1050 Ti

**Issue description:**
If you zoom out too much and move using 'shift' and 'middle button of the mouse' you can get lost, pivot position will change and you won't be able to zoom in to see closer or even find your main plate. I'm new to Godot, if it should work like that, is there any option to reset the viewport?

**Steps to reproduce:**
1. Create a new project
2. Zoom out to maximum
3. Move the view using Shift+Middle Mouse Button

**Comment by clayjohn** [comment]
Yes, press "o" or click on the "Viewport" menu in the top left corner and select the option "Focus Origin"

**Comment by kacmak7** [comment]
that's great, thank you !
