### ISSUE TITLE
EditorSpinSlider's grabber goes outside while scrolling

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#30900]
**Godot version:**
 becbb7b

**Issue description:**
While hovering an `EditorSpinSlider` with a grabber enabled, scrolling will make it go outside if the mouse isn't moved:
![Peek 2019-07-28 18-28](https://user-images.githubusercontent.com/30739239/62013190-bb6d2a00-b17e-11e9-8e38-168002c21d08.gif)

**Comment by Calinou** [comment]
Duplicate of #27258.
