### ISSUE TITLE
Atlas textures force FLAG_FILTER

### ISSUE THREAD

**Issue by Myriachan** [godotengine/godot#30904]
**Godot version:**

3.2.dev.calinou.437939589

**OS/device including version:**

Windows NT 10.0 build 18362

**Issue description:**

If you use a texture that is inside an atlas texture, `FLAG_FILTER` will be assumed.

**Steps to reproduce:**
1. Make a texture atlas out of a texture.
2. draw_texture_rect_region with a destination rectangle that is exactly twice the width and height of the source rectangle.
3. The texture will be drawn with filtering.
4. Manually change the filter flag in the atlas texture's .import file.
5. The texture will be drawn with filtering.
6. Manually remove `FLAG_FILTER` at runtime from each subtexture.
7. It works.

**Minimal reproduction project:**

**Comment by raphael10241024** [comment]
When you reset flags , you need to click reimport button to reimport it.
I can't reproduce it, do you have a demo project?

**Comment by clayjohn** [comment]
Wasn't reproduced and no response in almost a year, so closing.
