### ISSUE TITLE
Particles stop emitting if set a initial velocity [macOS]

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#30906]
**Godot version:**
Master (6c9ccf1)

**OS/device including version:**
macOS 10.14.5
RX 580

**Issue description:**

Particles stop emitting if set a initial velocity
(it works before)

**Steps to reproduce:**

- create a Particles node
- assign a Mesh and ParticleMaterial
- it start emitting
- set Velocity in Initial Velocity to any value
- it stop emitting

**Comment by clayjohn** [comment]
I can't reproduce in current master becbb7b525e1cc9bf1520a0ac94b9e9f799f6169

When you set ``initial_velocity`` does the emitting checkbox get unchecked?

Also what value are you setting ``initial_velocity`` to? When I set it above 600 the particles move so fast I don't see them.

**Comment by ippan** [comment]
![particle_velocity](https://user-images.githubusercontent.com/2070604/62019527-e17fe200-b1f1-11e9-89f5-04365201113c.gif)

I set it to 1 only~

I will try it at current master later (becbb7b)

**Comment by ippan** [comment]
Tested in current master (becbb7b)

have same issue in Mac.

but I test in Windows PC. It work fine.

maybe a Mac only issue.

Machine Detail:
MacBook Air
1.6 GHz intel Core i5-8210Y
16GB Ram
RX 580 External GPU

**Comment by creikey** [comment]
I was unable to reproduce on linux. Try with CPUParticles to see if it's an error with the graphics?

**Comment by ippan** [comment]
CPUParticles work fine.
no error message in console

**Comment by creikey** [comment]
Almost definitely a platform issue with OSX then.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 builds?

**Comment by ippan** [comment]
yes, it's still reproducible in latest 3.2 master build (adb6734)

**Comment by akien-mga** [comment]
CC @bruzvg @timothyqiu

**Comment by timothyqiu** [comment]
I can't reproduce this in the current master (7e76a67d1):

![demo](https://user-images.githubusercontent.com/372476/72878468-f28b5500-3d35-11ea-911d-340366fa4335.gif)

I also tried rc2, rc1, beta6, and beta5, can't reproduce either.

**Comment by bruvzg** [comment]
I can confirm this (macOS 10.15.2, AMD FirePro D300), emitting stops if `initial_velocity` is set to non-zero value, and restarts if it's set back to 0, no errors displayed.

**Comment by ViktorEvil** [comment]
works fine on MacBook Air (macOS 10.15.2) Godot 3.2 rc2

set initial_velocity to 1 or above and particles emit

**Comment by akien-mga** [comment]
Could you test if #36031 fixes it for you?

**Comment by ippan** [comment]
yes, it's fixed after apply that commit, thanks👍🏻
