### ISSUE TITLE
Compiling for x11: ld final link failed

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#30916]
**Godot version:**
master (https://github.com/godotengine/godot/commit/8547a351eb53e95c10525dcd3fb6a1fd58f746fd)

**OS/device including version:**
Arch Linux (Antergos Deepin)

**Issue description:**
```Swift
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 96%] Linking Program        ==> bin/godot.x11.opt.tools.64
[ 99%] progress_finish(["progress_finish"], [])
[100%] /usr/bin/ld: final link failed: Value too large for defined data type
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.opt.tools.64] Error 1
scons: building terminated because of errors.
```

**Steps to reproduce:**
```Swift
scons p=x11 bits=64 target=release_debug tools=yes -j 8
```

**Comment by qarmin** [comment]
I had similar errors two or three days ago and simple `git clean -x -q -f` fixed this(this back Godot to clean git repo)

**Comment by LinuxUserGD** [comment]
I tried it and it fixed it temporary but today the error showed up again when compiling with lto=yes.

**Comment by akien-mga** [comment]
If you switch between `use_lto=yes` and `use_lto=no`, you should clean the build objects. LTO implies doing different operations for each build object, so you do need to rebuild from scratch. I'm not sure that SCons picks it up properly though, which could lead to linking errors.

**Comment by LinuxUserGD** [comment]
Cloning godot again and using either lto=yes or lto=no fixes this problem (even if I run out of RAM and have to restart the computer it will still compile without errors).
