### ISSUE TITLE
Slider/SpinBox values.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#3091]
When using sliders (HSlider and VSlider. And applies to SpinBox as well.), I noticed two small quirks that could be subject to discussion. Specifically in the case of using integers/ "Rounded values".

The second thing is that the limits for the sliders seem reasonable for floats, but 65535 seems like a very low number for integers. While multiplication tricks could be used to get around this limit, it could become cumbersome when the numbers could get large like money or experience points. Seems the only way to get exact integers over 65535 is using a LineEdit, but that'd require accounting for possible non-numeric characters the user may accidentally input.

Is there something that could be done for this?

**Comment by vnen** [comment]
A random thought just to take note: maybe the integer cap is related to some less-powerful platform? Though I believe everything has 32-bit integers nowadays.

**Comment by hetdegon** [comment]
Whoops, the notification for your reply kinda got lost into the void. Sorry about that.

I believe every device capable of running Godot has at least 32-bit integers as well (unless there's some obscure mobile platform out there), although in this specific case, so says the documentation, all Range subclasses use a float regardless of the user setting "rounded values" or not. That might be why the low limit, as the rounded values seem to be merely discarding the fractional component.

This is not as much as a problem with sliders, as you can kind of play with the numbers and update a label with the processed values, making it seamless to the user, but spinboxes show its own value, which remains limited to 65535, which is a bit of a bummer since they are ideal for making tools quickly.

**Comment by vnen** [comment]
It makes sense. I guess the rounding is what causes a "-0", which might be -0.00001 (or something like this) and the engine just ignores the decimals, but not the sign. This could be considered a bug (if you want to report this case as a separate issue, I'll label that as a bug).

And the value cap should be much higher, I agree with that.

**Comment by hetdegon** [comment]
I'll file a separate issue for -0 then.

**Comment by bojidar-bg** [comment]
Would be nice if those classes are made to support non-float values indeed.

**Comment by bojidar-bg** [comment]
Based on [a stackoverflow question about the Number type in JavaScript](http://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin), `double` values should be able to store integers up to 9007199254740991 without losing precision. Which means that the real problem should be in the artificial limit imposed on Variant::REAL and Variant::INT by the editor....

**Comment by bojidar-bg** [comment]
Ok, according to another [stackoverflow answer](http://stackoverflow.com/questions/589575/what-does-the-c-standard-state-the-size-of-int-long-type-to-be), it seems like the `signed int` type cannot be assumed to contain numbers higher than `32767`, and as such can't be trusted with larger volumes of information. Given that we already allow "unsafe" values from `-65535` to `65535`, which are more of the `signed long` range, I guess I can directly switch to `-2147483647` to `2147483647` (which is what `signed long int` must be able to support no matter what)

**Comment by bojidar-bg** [comment]
If you have complaints about the current solution, please, tell us :smile:

**Comment by hetdegon** [comment]
Tested it out and seems perfect as far as I can tell. Thanks a lot bojidar!
