### ISSUE TITLE
override.cfg gets pulled into project.godot

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#30912]
**Godot version:**
Master branch (3.2)

**Issue description:**
I add values to override.cfg - such things as video/render settings or what not when the user changes some options and hits apply.
These values will eventually get pulled into the project.godot settings during development.

I would expect there a separation to be maintained between whats in the override.cfg and whats in the project.godot settings.

**Steps to reproduce:**
Create an override.cfg, add in a value. Run the editor and make a change to something in your project. Quit the editor.

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/5d172d5d9aaf05a247a517612def8fc719efa69f. I could reproduce this while developing [godot-settings-manager](https://github.com/Calinou/godot-settings-manager) which recommends defining a project settings override.

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by jitspoe** [comment]
Yeah, this has been a bit of a struggle for me, as my fullscreen setting keeps getting unset, and I couldn't figure out why at first.

My case:
Project settings (project.godot) has fullscreen enabled, as I want this to be the default behavior when the game first launches.

I have an options menu that can enable/disable fullscreen and writes to a "Project Settings Override" config file.  I turn fullscreen off in the game, which modifies the config file.

Launching the editor while this config file exists disables the fullscreen value in the project.godot file.

What I'd like:
Fullscreen setting stays set how I set it in the project and determines the first-launch behavior of the game.  Override config file only applies to the game (either standalone or when launched from the editor).

**Comment by Calinou** [comment]
@jitspoe As a workaround, you can configure the project settings override to be used only in exported projects by defining its value for the `standalone` [feature tag](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html)./

**Comment by jitspoe** [comment]
> 
> 
> @jitspoe As a workaround, you can configure the project settings override to be used only in exported projects by defining its value for the `standalone` [feature tag](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html) and leaving it unset otherwise.

That would mean it would always launch in fullscreen while developing, right?  That's not what I want, either.  Or are you saying I override the setting to enable fullscreen for standalone, and when the override config file gets loaded, it only applies to general setting and not the standalone one?

**Comment by Calinou** [comment]
> That would mean it would always launch in fullscreen while developing, right?

Yes, although you can override this in the Editor Settings (Game Window Placement).

**Comment by jitspoe** [comment]
This doesn't seem like it would be a viable approach.  If I have the override config set what should be in the shipping version of the game, the project config would still have that set on project load, right?  So when I went to export it, it would use what was in project file as the default setting when the game first launches.

**Comment by 2shady4u** [comment]
Some additional information/issue that is related, when using a custom `override.cfg` or `user://custom_settings.cfg` on exported projects, Godot attempts to modify the `project.godot` file on game launch but this results in following error:

![image](https://user-images.githubusercontent.com/42484461/127650243-af92c724-3e83-4c35-9c47-f9f706310f61.png)

I would expect some kind of feature tag check that properly checks if the Godot instance is an exported build or not?

**Comment by Calinou** [comment]
> Some additional information/issue that is related, when using a custom `override.cfg` or `user://custom_settings.cfg` on exported projects, Godot attempts to modify the `project.godot` file on game launch but this results in following error:
> 
> ![image](https://user-images.githubusercontent.com/42484461/127650243-af92c724-3e83-4c35-9c47-f9f706310f61.png)
> 
> I would expect some kind of feature tag check that properly checks if the Godot instance is an exported build or not?

Please open a new issue with a minimal reproduction project attached, as this is an unrelated bug.

**Comment by jitspoe** [comment]
I've just noticed another issue with this: I decided to consolidate the settings all in one file for one of my projects, and it brought completely unrelated settings (like settings I added specifically to my game) into the project.godot file.

**Comment by KoBeWi** [comment]
Would it be ok if `override.cfg` was functional only at runtime and not in editor? That would fix the issue.

**Comment by Calinou** [comment]
> Would it be ok if `override.cfg` was functional only at runtime and not in editor? That would fix the issue.

That sounds good to me; I don't see any reason to have it effective within the editor.

**Comment by jitspoe** [comment]
Depends on what you mean by "only at runtime".  I'd like to be able to test my game when running from the editor and have the settings work so I can test/debug things without having to export a build every time.  I just don't want them loading when the editor launches (not running the game).

**Comment by KoBeWi** [comment]
>  I'd like to be able to test my game when running from the editor and have the settings work so I can test/debug things without having to export a build every time.

This is still possible.

**Comment by dreadpon** [comment]
I cannot describe just how utterly frustrating it was to deal with `project.godot` that constantly reverted itself.
Is this still supposed to happen when launching an editor? Because it does.

However, my `override.cfg` has a different name (defined in ProjectSettings as `user://project_settings_override.cfg`), and it totally overrides `project.godot` whenever I launch my project.

It kind of makes sense, but still I expected this file to be used for runtime-only, *not* while in editor.
The workaround I used is to not save it via `ProjectSettings.save_custom()`, but write it to a separate `ConfigFile`. That way only a small subset of settings gets overriden in `project.godot` file.

It's manageable now for graphics settings, but might not be sufficient if I'd like to write something more substantial in the override file.

**Comment by juliohq** [comment]
Still happening in 4.0.3 stable.

**Comment by KoBeWi** [comment]
Try in 4.1 rc.

**Comment by AlfishSoftware** [comment]
> > Would it be ok if `override.cfg` was functional only at runtime and not in editor? That would fix the issue.
> 
> That sounds good to me. I don't see any reason to have `override.cfg` be effective within the editor.

So, it's not possible to have an editor plugin/addon that I don't want checked into git?
I thought I could have a file separate from `project.godot` for project settings that I can exclude from git, and I hoped this `override.cfg` would be the feature for this, so I could set `editor_plugins/enabled` and `autoload/MyEditorOnlyTool` outside of version control.

**Comment by KoBeWi** [comment]
You can use `get_editor_interface().get_editor_settings()` and use `set()`/`get()` to modify custom settings (or `set_meta()`/`get_meta()` if it doesn't work).

**Comment by AlfishSoftware** [comment]
But will that be excluded from `project.godot` even after I save?

**Comment by AlfishSoftware** [comment]
Wait, `editor_plugins` and `autoload` are project settings. Is there a way to set them or their equivalent as editor settings?

**Comment by KoBeWi** [comment]
No, currently they are stored in project settings.
Maybe I misunderstood your comment. EditorSettings can be used for plugin settings that you don't want in project, but not the plugin list itself. I think what you want is global addons, which are not implemented yet: https://github.com/godotengine/godot-proposals/issues/831

**Comment by AlfishSoftware** [comment]
Yes, this is exactly what I want.
I thought I could use this workaround while it's not yet implemented, but I guess not.

**Comment by ace24713** [comment]
I'm still getting this issue in 3.5, specifically when project.godot is reloaded i.e. if external modifications were detected... usually happens when I leave godot open and do a git pull on my project

**Comment by Calinou** [comment]
@ace24713 Please open a new issue with a minimal reproduction project attached.

**Comment by dyvoker** [comment]
The idea itself with`override.cfg` file is bad. When the game saves `ProjectSettings` it saves every property to the file, fully blocking updates from `project.godot`. So when you change, for example, the version of the game - it doesn't update. It is a global BUG for EACH Godot project and the `ProjectSettings.SaveConfig` only exists to create such bugs for now. The good solution is only to save properties that have different values with `project.godot`

So the solution I see for now is to use a custom config file and apply all settings to ProjectSettings at the start, and just don't save `ProjectSettings` to a file at all. Anyway, it is a workaround around the bug and you'll have to manage two sources of truth (it is messy).
