### ISSUE TITLE
Cannot collapse remote tree

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30921]
**Godot version:**
3.2 Dev

**OS/device including version:**
Windows 10

**Issue description:**
Remote tree can not be collapsed in the latest Godot Dev build. In 3.1 stable it is fine.
![Tree bug](https://user-images.githubusercontent.com/1850856/62049596-3d5d6180-b218-11e9-8c18-f60965287c62.gif)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by sparkart** [comment]
Possible regression from: #23270

**Comment by akien-mga** [comment]
CC @silvanocerza

**Comment by silvanocerza** [comment]
Sorry, I broke it. The PR fixes it. :)
