### ISSUE TITLE
Android export GodotPaymentV3: random game crashes

### ISSUE THREAD

**Issue by etalot** [godotengine/godot#30922]
I upload my game to Google Play and google Stability test randomly shows(actually while testing by myself I randomly(1 in 10-20 runs) gets it too:

**Issue: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getSkuDetails(int, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference**

FATAL EXCEPTION: Thread-8
Process: com.qudop.moneytree, PID: 12418
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getSkuDetails(int, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
	at org.godotengine.godot.payments.PaymentsManager$7.run(PaymentsManager.java:390)
	at java.lang.Thread.run(Thread.java:764)

**Godot version:**
3.1 branch, custom build, 1-2 month fresh, (GodotPaymentV3.java/PaymentsManager.java for now last modify: 9 april)

**OS/device including version:**
Random android devices

In 2 days(from 1 aug) google will stop loads 32bit apk, please help and give solution just to stop crushes game(full fixing issue is not necessary now, just prevent game crushes).

**Comment by idkaryan** [comment]
Please fix this. I gave 3 seconds in the beginning of the game to make sure GodotPayments module is loaded. This happens only when getSkuDetails() is called when payment module isn't initialized. If there was a way to initiate a callback exactly when GodotPayments get initialize, it'd work.

**Comment by MyNameIsDabin** [comment]
Please fix this. : (
My Android game already has more than 20,000 installations, and 20 to 30 Payments Crush happens every day.

**Comment by akien-mga** [comment]
Might be fixed in 3.2.2 by @m4gr3d's refactoring work.

**Comment by MyNameIsDabin** [comment]
> Might be fixed in 3.2.2 by @m4gr3d's refactoring work.
Wow, I will be rich with godot engine.

**Comment by myood** [comment]
I had the same issue. In 3.2 I extended the IAP.gd from the example in the repo with callback to "iap_connected" and "iap_disconnected". Not sure, but I think PaymentManger.java callbacks GodotPayments.java, which in turn callbacks the IAP.gd. On "iap_connected" I emit the signal "service_connected" and on "iap_disconnected" the signal "service_disconnected". From that point I act accordingly in a client code.

Well, I didn't spend much time on this, but this should work, right? Sadly the "service_connected" signal is never emitted, at least not on my AVD. I'll test it later on the real phone, but there should be no difference.

Anyway I leave the diff here in case it may point somebody to the right solution:

```python
diff --git a/scenes/IAP.gd b/scenes/IAP.gd
index 9bfbd18e..17132fb8 100644
--- a/scenes/IAP.gd
+++ b/scenes/IAP.gd
@@ -14,6 +14,9 @@ signal consume_not_required
 signal sku_details_complete
 signal sku_details_error

+signal service_connected
+signal service_disconnected
+
 var payment

 func _ready():
@@ -72,6 +75,14 @@ func purchase_cancel():
 func purchase_owned(sku):
     print("purchase_owned : ", sku)
     emit_signal("purchase_owned", sku)
+
+func iap_connected():
+    print("iap_connected")
+    emit_signal("service_connected")
+
+func iap_disconnected():
+    print("iap_disconnected")
+    emit_signal("service_disconnected")


 # Consume purchased item.
diff --git a/scenes/UI/ShopButton.gd b/scenes/UI/ShopButton.gd
index 4d1de15c..895402cf 100644
--- a/scenes/UI/ShopButton.gd
+++ b/scenes/UI/ShopButton.gd
@@ -2,14 +2,21 @@ extends Button

 func _ready():
     # get_tree().create_timer(3.0).connect("timeout", self, "query_iap")
+
+    IAP.connect("sku_details_complete", self, "sku_details_complete")
+    IAP.connect("service_connected", self, "on_service_connect")
+    IAP.connect("service_disconnected", self, "on_service_dc")
+
+func on_service_connect():
+    disabled = false
+    query_iap()
+
+func on_service_dc():
+    disabled = true
:
```

**Comment by m4gr3d** [comment]
As mentioned, the issue should be resolved and the module has been moved into its [own repo](https://github.com/godotengine/godot-google-play-billing).
