### ISSUE TITLE
BakedLightmap shadows looks highly pixelated when using ConeTrace and simply incorrect when using RayTrace

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#30929]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
I've had troubles when trying to implement baked light for our game.
Shadows looks highly pixelated when using ConeTrace and simply incorrect when using RayTrace.

**Steps to reproduce:**
1) Get the demo project from here: https://github.com/Antokolos/palladium3d-demo/archive/v0.0.1.zip
2) Open BakedLightmap node in res://floor_demo_full.tscn
3) Click Bake Lightmaps and wait for completion (Caution, this will require some time to be finished)
4) Run the game, press Esc, set the Optimal quality in the settings, now the Godot's OmniLights will be hidden and you'll see only baked light
5) Take a look at the shadows, they are looking very pixelated.

![image](https://user-images.githubusercontent.com/7196697/62059841-d060c080-b245-11e9-9421-2424ed59dddf.png)

![image](https://user-images.githubusercontent.com/7196697/62059873-e40c2700-b245-11e9-8e07-4dc6efe14e18.png)

6) Press Esc, set the High quality in the settings, now you can see Godot's OmniLights with shadows enabled. This is what I'm trying to achieve when using baked light

![image](https://user-images.githubusercontent.com/7196697/62061215-8a592c00-b248-11e9-9020-bdc7cf1a4969.png)

7) Press ALT+F4, exit the game.
8) Open BakedLightmap node in res://floor_demo_full.tscn, set bake mode to RayTrace
9) Click Bake Lightmaps and wait for completion (Caution, this will require some time to be finished)
10) Run the game, set the Optimal graphics quality
10) Take a look at the shadows, they are incorrect

![image](https://user-images.githubusercontent.com/7196697/62060362-ce4b3180-b246-11e9-92a1-ea6316b35786.png)

![image](https://user-images.githubusercontent.com/7196697/62060384-dacf8a00-b246-11e9-99f5-db252e6421f4.png)

**Minimal reproduction project:**
https://github.com/Antokolos/palladium3d-demo/archive/v0.0.1.zip

**Comment by Calinou** [comment]
Cone tracing is less accurate than raytracing, which means most small fixtures won't cast shadows if you rely on lightmaps only (i.e. no real-time lighting).

There is an [ongoing GSOC project](https://godotengine.org/article/gsoc-2019-progress-report-1-part-2#lightmapper) on rewriting the lightmapper. It seems the cone tracing approach will be removed in favor of raytracing.

**Comment by Antokolos** [comment]
Wow, GSOC project looks very promising! I hope that it will be included in Godot 3.2
And I hope that Godot 3.2 will be released relatively soon... ;)

**Comment by Antokolos** [comment]
By the way, I intended to do this because I thought that baked lightmaps is more "lightweight" than the shadows from the Godot's OmniLight sources, but it seems that baked lightmaps consumes resources too, so I'm uncertain that this is the case...
For example, let's compare the stats for the Good quality settings (which means no baked lightmap & enables Godot's OmniLight sources without the shadows)
![image](https://user-images.githubusercontent.com/7196697/62119687-ecb23b00-b2e1-11e9-83e8-f79ab245b73f.png)
And the Optimal quality settings (which means hide the Godot's OmniLight sources and enable baked lightmap)
![image](https://user-images.githubusercontent.com/7196697/62119781-21be8d80-b2e2-11e9-9001-4ff49615ca52.png)
Take a look at the Material changes stat, it is actually increased in case of baked lightmap.
Drawcalls were decreased, but still overall performance is not significantly better in this case

**Comment by Antokolos** [comment]
Also, please take a look at the normal maps at the torch, they seems to be missing when using baked lightmaps. Is this really the case? Baked light means no normal maps? Or maybe I should post another issue regarding this problem?

**Comment by Antokolos** [comment]
Please note: in the current version of the demo available on the GitHub I reworked the approach for lighting (baked lightmaps are not used anymore), so you'll need to download release 0.0.1 via https://github.com/Antokolos/palladium3d-demo/archive/v0.0.1.zip if you want to explore this issue

**Comment by Calinou** [comment]
This was resolved by https://github.com/godotengine/godot/pull/44628 (ConeTrace was removed), closing.
