### ISSUE TITLE
Add a global function to get the type of variant.

### ISSUE THREAD

**Issue by dbsGen** [godotengine/godot#3093]
So we can check the variant type and do something.

        if typeof(obj) == TYPE_OBJECT:
            print(obj.get_type())

**Comment by akien-mga** [comment]
There is Object::get_type() exposed to GDScript already: https://github.com/godotengine/godot/blob/3ecc9e07b7650725c8786d6af7c5f77ab6d94cc2/core/object.cpp#L1543
Isn't it what you're looking for?

**Comment by akien-mga** [comment]
Ah sorry I misread, you meant to add a ```typeof``` function.

**Comment by akien-mga** [comment]
> There is Object::get_type() exposed to GDScript already

On the other hand I'm not sure there is an equivalent for Variants exposed to GDScript, though Variant does have ```Variant::get_type_name()```.

**Comment by dbsGen** [comment]
Variant::get_type is OK.because TYPE_* is already  added.

**Comment by kubecz3k** [comment]
There is already typeof() function that returns values from TYPE consts.
However there is no mention about it in help system...

**Comment by dbsGen** [comment]
Oh,I see. it's just added.
