### ISSUE TITLE
Mixed tabs and spaces no longer supported for multiline declarations

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#30937]
**Godot version:**
6c9ccf18f

**Issue description:**
GDScript files which contain mixed tabs and spaces in multiline definitions (for example, to align dictionaries or arrays) are now considered a hard error when before they were ignored.  This can (for example) break plugins when migrating.

**Comment by akien-mga** [comment]
Can you give examples of such multiline definitions?

**Comment by nobuyukinyuu** [comment]
can-do.

![image](https://user-images.githubusercontent.com/1023003/62078744-ed2fd080-b212-11e9-8f99-402de79fcfd7.png)

I had to replace 3 spaces on lines 21 and 22 to a tab for the script to pass the current parser, but it now looks ugly.  This is just a simple example;  more complicated ones would obviously have more instances of this necessary to alignment if nesting becomes involved (such as with dictionaries) and the declaration far exceeded 80 characters (or whatever the canonical convention is supposed to be now).

Another few examples flagged in my current codebase:
![image](https://user-images.githubusercontent.com/1023003/62079011-6d563600-b213-11e9-8133-ad32ef13aad0.png)
![image](https://user-images.githubusercontent.com/1023003/62079060-8ced5e80-b213-11e9-9a98-eba10c39c923.png)
![image](https://user-images.githubusercontent.com/1023003/62079131-af7f7780-b213-11e9-96b8-efe4df652321.png)

**Comment by TheDuriel** [comment]
Mixing tabs and spaces _should_ error. The convention commonly seen for continuing lines is two tabs anyways.

**Comment by akien-mga** [comment]
It should only error when the indentation has syntactic meaning, like in a code block. So that last screenshot is a valid error for example, the comment is badly indented in its scope.

But for array/soft declarations and statements wrapped over multiple lines, freestyle should be allowed (even if mix tabs and spaces is ewww, but still not a reason for a syntax error if it can't be a source of bugs).

**Comment by Xrayez** [comment]
The same could happen in plugins for which a user might not have much control and have to come up with custom indentation fixes in order to continue using them, see bitwes/Gut#126 for instance. Also noticed this in [godot-logger](https://github.com/KOBUGE-Games/godot-logger).

**Comment by Xrayez** [comment]
Talking about plugins, consider making an ability to ignore indentation inconsistencies for "third-party" stuff or custom folders, as proposed in #28232 to ignore warnings in GDScript. Alternatively, one could make indentation inconsistency error to be treated as a warning optionally (per project or folder). Warnings can be turned on to be treated as errors anytime, though you can't make a *single* warning to be treated as an error unfortunately.

**Comment by Skaruts** [comment]
@akien-mga Also for long function calls that one may want to break the parentheses into several lines.

**Comment by Calinou** [comment]
@Skaruts This can already be done using only tabs (or spaces):

```gdscript
some_function_call(
        123,
        "hello",
        456
)
```

The [GDScript style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) advises using two tabs to separate line continuation indents from "semantic" indentation

**Comment by Skaruts** [comment]
@Calinou Yea, sometimes I do them like that (the 2nd one), but usually with the `)` indented one more.

But there are cases where doing them like the example below helps me visualize things better. The code looks clearer to my eyes this way. 
```
igm.draw_linestrip( 
                    [   
                        Vector3(0 , 0,  0), 
                        Vector3(core.grid_size, 0,  0),
                        Vector3(core.grid_size, 0, core.grid_size), 
                        Vector3(0 , 0, core.grid_size),
                        Vector3(0 , 0,  0)
                    ], 
                    "ig_grid_bounds"     # <-- second function parameter
                  )
```
(Had to use spaces there just to align things properly, because github. The original uses tabs.)

**Comment by michelmontenegro** [comment]
Who program in other languages knows that "Tab" is used and always was to identify code, now in cases of use of matrix or similar even to think, but still, what is the justification?

What is the justification? Just say it's like that and that's it, no real advantage?

**Comment by michelmontenegro** [comment]
Why don't you come back and release the TAB?
Removing Godot's TAB usage is very wrong, all programming languages coexist well, why did Godot decide to change that?

**Comment by akien-mga** [comment]
> What is the justification for a BUG?

It's a bug.

**Comment by nobuyukinyuu** [comment]
This bug has returned as of v4.0.dev.custom_build.364ea7f28.  example:
![image](https://user-images.githubusercontent.com/1023003/119928199-b925b380-bf40-11eb-9a80-3717355480ef.png)

Please consider re-opening the issue if the cause is similar.

**Comment by fcole90** [comment]
See my workaround at https://github.com/godotengine/godot/issues/49171#issuecomment-850998695
