### ISSUE TITLE
vec3 uniform bug, next uniform does not change

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#30930]
look like old bug, still exist https://github.com/godotengine/godot/issues/14962

**Godot version:**
3.1.1 stable

**OS/device including version:**
Linux/Web

**Issue description and Steps to reproduce:**

Create shader material, make uniform vec3... and next other uniform int/float/bool

Changing that uniform after vec3 will be lost.

**Editing that vec3 value** (any of its number) in GUI Godot editor (set any value to it press Enter and edit again return previous, like edit from 0 to 1 and back to 0) fix this, and next Uniform will work.

_look like bug exist only in unedited vec3._ 

**Minimal reproduction project:**

web version: https://danilw.github.io/godot-utils-and-other/bug_vec3/web/BUG_shader_vec3.html

source project: https://danilw.github.io/godot-utils-and-other/bug_vec3/BUG_shader_vec3.zip

(in that example, changing state of button change uniform value, and this should change color in shader (by if rule) from red to blue)

**Comment by clayjohn** [comment]
Note to whoever works on this. It only happens in GLES3, so you can use the code from GLES2 to help you find the proper solution. 

Additionally, the bug is only present while the vec3 is uninitialized. That should help you narrow down where the bug is coming from.
