### ISSUE TITLE
Change Default TileMap Custom Transform to match default Square mode Cell Size

### ISSUE THREAD

**Issue by StStep** [godotengine/godot#30948]
I think it's unintuitive that the TileMap node default value for the  Custom Transform property is Transform2D( 1, 0, 0, 1, 0, 0 ), and that it should match the Size default of Vector2(64,64) by having the default value of Transform2D( 64, 0, 0, 64, 0, 0 ).

Usage Reasons:
* It is a large performance hit if you switch from mode Square to Custom without changing the default Custom Transform if you have a tileset loaded
    * This crashed godot the first time I tried using the custom transform due to this
    * I've seen multiple posts about performance with TileMap that can be attributed to this
* A 1px by 1px TileMap doesn't make sense for most users

Aesthetic Reasons:
* It helps new users understand how the transforms works by associating values with similar usage

**Comment by aole** [comment]
There are the changes you are expecting as default?

![image](https://user-images.githubusercontent.com/4707543/63973322-894e3100-ca78-11e9-98fe-48a5f717dc6e.png)

**Comment by StStep** [comment]
Yep
