### ISSUE TITLE
Performance improvement for PoolVector<T> when T is a core type (+35% in my tests)

### ISSUE THREAD

**Issue by eligt** [godotengine/godot#30946]
The `PoolVector<T>` template class calls constructor (placement_new) and destructor on objects that are pooled, which makes sense for most classes. 

The issue is that `PoolVector` is used extensively as a `ByteArray` (`PoolVector<u8>`) to read and write data for resources. I think the assumption here is that the compiler should collapse constructors and destructors for core types and therefore collapse the whole construction/destruction loop but this does not happen.

I initially thought that the debug info required for profiling somehow disables these optimizations but then I created my own export templates and even the exported version seems faster to me, although I need to make more measurements to be sure.

You can test this yourself by pulling in this commit: https://github.com/eligt/godot/commit/d33343f0525c145002296a69eef8ba1c4f29c110

As you can see, the commit is fairly simple and lean but unfortunately it is C++11 only and Godot does not allow C++11 code so having this as an actual fix in upstream will require more work, which is why I didn't make a pull request.

**Comment by mafiesto4** [comment]
Who needs performance? :trollface:

**Comment by akien-mga** [comment]
> As you can see, the commit is fairly simple and lean but unfortunately it is C++11 only and Godot does not allow C++11 code so having this as an actual fix in upstream will require more work, which is why I didn't make a pull request.

We'll use C++11 in 4.0, so this change could likely be included then (as soon as 3.2 is released and branched off).

**Comment by nem0** [comment]
I tested with custom container in VS 2019, the constructors/destructors are optimized out in release build.

**Comment by eligt** [comment]
@nem0 This could be a difference in compilers then - I compared the GCC-generated disassembly of `PoolVector<unsigned char>::resize()` and `PoolVector<unsigned char, true>::resize()` (the latter using my modifications) and, while I still have to identify the part of the construction/destruction loop, just the fact that the first disassembly is 1280 lines long while the second is 570 makes me think that a lot of that unnecessary logic is kept even with a release build.

**Comment by Calinou** [comment]
@eligt Do you have the commit still available somewhere? The `3.x` branch can now use C++14.

**Comment by akien-mga** [comment]
Closing as the commit is no longer available, and these classes have been greatly modernized in 4.0.

**Comment by Calinou** [comment]
> Closing as the commit is no longer available, and these classes have been greatly modernized in 4.0.

It seems to be available as https://github.com/eligt/godot/commit/ba21d02e6b2f78299ab427668798a6a2a79447e5 now (part of https://github.com/eligt/godot/commits/poolvector-speedup).
