### ISSUE TITLE
Porting GLES3 built-in functions to GLES2

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#30940]
**The Problem**
GLES3 supports more built in functions than GLES2 does (like ``round()``, ``isnan()``, ``sinh()``, etc.) . Godot's shading language follows the GLES3 spec so when these functions are used in GLES2, they result in a compile error (see #24850). Our current solution is to track these differences in the [Differences between GLES2 and GLES3 tutorial](http://docs.godotengine.org/en/latest/tutorials/misc/gles2_gles3_differences.html#shading-language), however, that hasn't been enough. 

**The Solution**
Some of these functions can be implemented in glsl. For example ``round()`` can be implemented as:

```
float round(float x) {
    return floor(x + 0.5);
}
```

Accordingly, someone (maybe YOU!) needs to go through and determine which, if any, other functions can be implemented easily in glsl and then implement them. 

In implementing them, you can just follow how it was implemented for ``round()`` in 
https://github.com/godotengine/godot/pull/30895

**Comment by Chaosus** [comment]
I can be that hero..

**Comment by coderguy1777** [comment]
I can also help with this

**Comment by clayjohn** [comment]
@coderguy1777 Thanks! But Chaosus has already made a PR https://github.com/godotengine/godot/pull/30993
