### ISSUE TITLE
godot android compile error

### ISSUE THREAD

**Issue by jacoby34** [godotengine/godot#30941]
Im trying to compile android templates with custom apks. one of them being the admob module. And I get this error:

```
scons: Reading SConscript files ...
Building for Android (armv7) (with NEON)
Using NDK unified headers
Warning: module 'admob' uses a deprecated `can_build` signature in its config.py file, it should be `can_build(env, platform)`.
AttributeError: 'SConsEnvironment' object has no attribute 'android_add_dependency':
  File "C:\Users\Jacob\Downloads\godot\SConstruct", line 427:
    config.configure(env)
  File "./modules/admob\config.py", line 6:
    env.android_add_dependency("compile ('com.google.android.gms:play-services-ads:16.0.0') { exclude group: 'com.android.support' }")
```

this is the config.py for admob:

```
def can_build(plat):
    return plat=="android" or plat=="iphone"

def configure(env):
    if (env['platform'] == 'android'):
        env.android_add_dependency("compile ('com.google.android.gms:play-services-ads:16.0.0') { exclude group: 'com.android.support' }")
        env.android_add_java_dir("android")
        env.android_add_to_manifest("android/AndroidManifestChunk.xml")
        env.disable_module() 
```

**Comment by volzhs** [comment]
Android build has been changed to support new plugin system for android.
https://godotengine.org/article/godot-3-2-will-get-new-android-plugin-system

if you want to use admob module with master(3.2), you need to follow the document.
if you want it in old way, you need to checkout 3.1 branch not master.

**Comment by jacoby34** [comment]
> Android build has been changed to support new plugin system for android.
> https://godotengine.org/article/godot-3-2-will-get-new-android-plugin-system
> 
> if you want to use admob module with master(3.2), you need to follow the document.
> if you want it in old way, you need to checkout 3.1 branch not master.

Thank you for the response! I tried again but with the 3.1 source instead of master. and I get the same exact error.

**Comment by jacoby34** [comment]
Thank you

**Comment by MohammadKhashashneh** [comment]
Does this include the (2.1) as well? I'm having similar issues building an old module on 2.1_master.

**Comment by MohammadKhashashneh** [comment]
never mind, had to git clean after building and switching branches.
