### ISSUE TITLE
3 featrure propose for godot

### ISSUE THREAD

**Issue by fish2091852127** [godotengine/godot#30951]
1.keyword replace for all of script in the project 
2.add notes for scripts custom variable/function, (user can make a note for a self variable in scirpt,when cursor at the variable can be show the note)
3. Godot buld-in simple painting tool( at now,if i need to make a draft role/ui in project, i need open any outside drawing software and import some draft in my project, is some troubles, if Godot have buld-in simple drawing tool (likes GameMakerStudio) is should be convenient

**Comment by groud** [comment]
Please open an issue for each feature, those are completely unrelated and do not fit into a single issue.
