### ISSUE TITLE
 Feature request - Editing Multiple Keyframes in the Animation Timeline at once

### ISSUE THREAD

**Issue by chrisphyffer** [godotengine/godot#30956]
Possible Duplicate:
https://github.com/godotengine/godot/issues/28477

**Godot version:**
Godot 3.1.1

**OS/device including version:**
Windows / Gtx 1080

**Feature description:**
Would it be possible to select multiple keyframes to edit at the same time?
For example, I have a simple animation for rocks assembling to a position, and need to scale them all up.

![edit_multiple-keyframes](https://user-images.githubusercontent.com/17959437/62121100-c8217900-b277-11e9-8b2a-35170eec6bcf.jpg)

If this is not feasible, I can definitely animate them in Blender and just go with that.

Thanks!

**Comment by akien-mga** [comment]
@YeldhamDev Did #30778 fix that?

**Comment by YeldhamDev** [comment]
@akien-mga Pretty much.
