### ISSUE TITLE
Custom variable/function can make notes for it

### ISSUE THREAD

**Issue by fish2091852127** [godotengine/godot#30955]
new featrue propose:
user can add notes for scripts custom variable/function, (user can make a note for a self variable in scirpt,when cursor at the variable can be show the note)

**Comment by KoBeWi** [comment]
I think there was already similar proposal, but I can't find it now >_>

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/27607 and https://github.com/godotengine/godot/issues/4370.
