### ISSUE TITLE
WindowDialog theme options missing titlebar

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3095]
Right now the only options to theme the windows ui are the ones that appear in the image
![window-ui](https://cloud.githubusercontent.com/assets/6296184/11880777/7c708e58-a4e1-11e5-9ec7-70e1b10f48ba.png)

Just a couple of missing features / bugs
1º There are no options to change the style of the titlebar. When you style the window with a custom theme the titlebar just disappears. 
2º The option titlebar_height does not increase the titlebar height.
3º The close button textures can be changed, but the button mask is still very very small and it can not be changed (it can be moved using offsets tough).

**Comment by reduz** [comment]
will remake this dialog in 2.1

**Comment by akien-mga** [comment]
The theme editor was reworked recently, is this issue still valid in 2.1-beta?

**Comment by reduz** [comment]
Actually, looking at it again this was never a bug:

1) the titlebar is part of the stylebox
2) titlebar_height is meant to be changed by yourself to adjust it as you like
3) the close button should respond to the texture, it's a simple texturebutton

**Comment by FEDE0D** [comment]
@reduz I'll try to test this when I have the time to be sure it's working now.

**Comment by cromorg** [comment]
We have the same problem ! With the update, the title bar still disappear !
Did you find a way to fix it ?

**Comment by BitTim** [comment]
Problem still exists in 3.1

**Comment by redapple91** [comment]
expand the top:
- add a theme
- add window dialog class item
- in styles/panel, add new styleboxflat
- in expand margin property, increase the top value to 23 for ex.

**Comment by ondesic** [comment]
There needs to be a way to change the "X" button size in the corner.  If you change the default font to something bigger, the "x" remains small, almost impossible to click.
