### ISSUE TITLE
Godot built-in drawing tool

### ISSUE THREAD

**Issue by fish2091852127** [godotengine/godot#30954]
Godot buld-in simple painting tool( at now,if i need to make a draft role/ui in project, i need open any outside drawing software and import some draft in my project, is some troubles, if Godot have buld-in simple drawing tool (likes GameMakerStudio) is should be convenient

**Comment by Faless** [comment]
Isn't this a duplicate of #6477 ?

**Comment by akien-mga** [comment]
Yes, duplicate of #6477. Sprite editing is outside the scope of Godot's features, at least for the time being.
