### ISSUE TITLE
Visual detail: Scripts name highlighting

### ISSUE THREAD

**Issue by GovanifY** [godotengine/godot#3096]
As the title says it's just a really little visual detail I'm talking about
In the script opened window the scripts are highlighted w/ a red like surface, but if the name is
too long to be completely contained the red surface doesn't highlight the complete name:

http://gyazo.govanify.com/grab/8ca4b6.png

For this reason I think the surface should be a little bit bigger, covering the whole area of the name, maybe by using a more rectagular shpaed transparent  selector

**Comment by akien-mga** [comment]
I'll give it a go, it should not be too hard to fix :)
