### ISSUE TITLE
Bug: When duplicating a node using GUI, the rotation of the duplicate changes

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#30973]
I'm using the latest version of godot 3.1 on ubuntu 16.04 64 bit.

I'm creating a cards game, there's no need to create instances of cards in my case, perhaps instancing is the best practice but duplicating worked just fine from a game end goal perspective

When duplicating a node using Gui, it's rotation changes and weird things happen:

- Some cards have 0 degrees in rotation
- Some cards have 180
- Some of the cards that have 180 degrees rotation look upside down 
- Some of the cards that have 0 degrees rotation look upside down  

I can't find an explanation for why this is happening nor how it's possible

**Comment by Calinou** [comment]
Please upload a minimal reproduction project so we can try to reproduce the issue. You could also share a video recording or a GIF of the issue happening.

**Comment by elieobeid7** [comment]
Of course, I'll do that ASAP

**Comment by codecustard** [comment]
I can't reproduce the issue. An example project would be great, as far as I can tell this could be some underlying issue specific to the way that your project is set up.
