### ISSUE TITLE
Godot C# there is no AABB.size

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot#30976]
**Godot version:**
3.1.1 Mono

**OS/device including version:**
Windows 10

**Issue description:**
The following code produces, "AABB does not contain definition for GetSize." Same thing if I do boundingBox.size.

`		city = GetParent().GetNode("City_1") as MeshInstance;
		AABB boundingBox = city.GetTransformedAabb();
		Vector3 size = boundingBox.GetSize();`

**Steps to reproduce:**
Run that code.

**Comment by neikeq** [comment]
Use the property `Size` instead:

``` C#
Vector3 size = boundingBox.Size;
```

**Comment by OriginalAGP** [comment]
Thank you. I wish that I could have found this in the docs. Still, I'm only getting (0, 0, 0).
