### ISSUE TITLE
Png transparency converted to black

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3097]
Some times when using images that contains an alpha channel, the alpha is discarded and rendered as black in the editor. 
What's confusing is that after launching the application the image with the black alpha is written to disk overwritten the original texture, what makes it very annoying.

[This is the original image](https://dl.dropboxusercontent.com/u/274954519/godot-issues/button_focus.png)
![button_focus](https://cloud.githubusercontent.com/assets/6296184/11882961/784a16a2-a4ee-11e5-8a29-18ecbb8e9cc7.png)

[And this what godot overwrites after using it in-editor](https://dl.dropboxusercontent.com/u/274954519/godot-issues/button_focus_after.png)
![button_focus_after](https://cloud.githubusercontent.com/assets/6296184/11882977/8b6ca4c0-a4ee-11e5-81be-f74575454732.png)

This is a very annoying issue as it appears to be random, and even after reimporting the issue can be retriggered.
Even using the import feature does not fix the black background.

Is this related to #1178 ?

**Comment by reduz** [comment]
I have never seen this. Please make an example project with an example file that fails

**Comment by FEDE0D** [comment]
Ok. Here's an example project: https://dl.dropboxusercontent.com/u/274954519/godot-issues/PngBlack.zip

This is how the image looks on my filesystem:
![1](https://cloud.githubusercontent.com/assets/6296184/12225804/f77a42d4-b7f0-11e5-8b65-ba519e16cb27.png)

Now I'm editing the project and this is how it looks in the preview:
![2](https://cloud.githubusercontent.com/assets/6296184/12225808/081a2898-b7f1-11e5-874c-28c6d2daae2d.png)

And in editor:
![3](https://cloud.githubusercontent.com/assets/6296184/12225809/0d425eee-b7f1-11e5-85fe-a1bf71fe6388.png)

Sometimes the file on the project folder gets overwritten by Godot and makes the alpha channel to go black like in editor.
Here's the original texture: https://dl.dropboxusercontent.com/u/274954519/godot-issues/original.png

**Comment by reduz** [comment]
Which tool did you use to create this png?

**Comment by FEDE0D** [comment]
ImageMagick convert command on Linux.

**Comment by reduz** [comment]
what did you convert the image from then?

**Comment by FEDE0D** [comment]
I exported an svg vector from Inkscape. Then I scaled a bunch of images using this command:
``convert $i -scale 50% -alpha on "PNG24:"$i;``

I know it has something to do with the way the alpha is stored on the file. I've tried every combination to make it work with no luck so far. Other programs opens the file just fine.

**Comment by FEDE0D** [comment]
I export from Inkscape to png files. Then I scaled them using that command.
The files exported right from Inkscape works fine on Godot.

**Comment by reduz** [comment]
Why are you using PNG24 isntead of PNG32 ?

**Comment by FEDE0D** [comment]
I used PNG32 to begin with, but was not working.

**Comment by FEDE0D** [comment]
That's was it. It fails only with PNG24.

**Comment by FEDE0D** [comment]
I've just tested it. I thought I had tried it. I guess I didn't try the -alpha PNG32 combination.

**Comment by reduz** [comment]
you are a machine of finding weird bugs, keep at it :D

**Comment by reduz** [comment]
well, still fixed the bug though

**Comment by FEDE0D** [comment]
And you're a machine fixing them!
Thanks for all your work :+1:
