### ISSUE TITLE
Feature request: Easy way to share scenes

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#30974]
My brother isn't a programmer, I gave him an exact copy of my project and told him to edit the scene, fixing some UI stuff. When he's done there's no way for me to copy the `.tsn` files back into the project, I have to copy the entire project.

my scripts are stored in `/scripts`, my scenes are stored in `/scenes`, he has an exact copy, just has to edit the scenes and give them back to me.I know and use git, he's not a programmer, he doesn't know it and won't tell him to learn it.
 
In fact next month I'm hiring a graphic designer to help me with the intro scene, she might need to work in godot, because it's so easy for me to teach her, as long as she's sticking to the GUI, that way I won't waste my time adding whatever she does in godot, she can add it herself.  I don't want to teach her git too.

**Comment by KoBeWi** [comment]
>  When he's done there's no way for me to copy the .tsn files back into the project, I have to copy the entire project.

Why would that be? Do you get some error on broken dependencies or something? It should work perfectly fine as long as your project's copy has all the resources used on scene, in the same paths.

**Comment by elieobeid7** [comment]
I'm not sure, he gives me the `.tsn` back, I rerun the game, I see the old game, before he did his edits. Am I missing something?

**Comment by KoBeWi** [comment]
If you have the scene open, you need to reload it when you replace the file (the easiest way is to use Scene -> Revert Scene). Godot doesn't do this automatically.

**Comment by elieobeid7** [comment]
Oh thanks I'll try your answer soon, and reopen this issue if it did not work, I'll close it for now to reduce the number of open issues by one :) Thanks so much!
