### ISSUE TITLE
Bug: warning about never used value of connect function

### ISSUE THREAD

**Issue by NieznanywInternetach** [godotengine/godot#30980]
**Godot version:** 
3.1.1, stable official

**OS/device including version:** 
Windows 8.1

**Issue description:**
![obraz](https://user-images.githubusercontent.com/51792746/62166184-62d59280-b320-11e9-8642-6dbe60e8201a.png)
I think it's self-explaining: This warning shouldn't appear in such circumstances

**Steps to reproduce:**
I had saved it as:

func _ready():
	connect("pointed", self, "coord_maker", [second_ID, second_coord])
	pass

At the moment this warning was correctly because those variables weren't used. But after some coding i realised i don't need to return it via connect(). So i had:

func _ready():
	connect("pointed", self, "coord_maker")
	pass

I saved it and worked on. After a while i spotted it still remains.
I had asked about it on Godot's Discord but they were suprised as well. I shared the code but this warning didn't show up to them. 

**Minimal reproduction project:**
[Punkt1.zip](https://github.com/godotengine/godot/files/3448947/Punkt1.zip)

**Comment by KoBeWi** [comment]
It's about return value of `connect`, not arguments. See this comment: https://github.com/godotengine/godot/issues/27576#issuecomment-478683871

Is there anything more to the topic than already discussed in linked issue?

> I shared the code but this warning didn't show up to them.

If they didn't try it on clean project, they most likely disabled this warning.

**Comment by NieznanywInternetach** [comment]
I wasn't sure if i'm not missing something and that's it
> Is there anything more to the topic than already discussed in linked issue?
I don't think so, thank you for help
