### ISSUE TITLE
SSR Looses Color Upon Higher Roughness Values

### ISSUE THREAD

**Issue by adriansnetlis** [godotengine/godot#30989]
**Godot version:**
3.1

**OS/device including version:**
Arch Linux (5.2.4-arch1-1-ARCH)
NVIDIA GeForce GTX 1060 6GB (430.34-4)

**Issue description:**
When having SSR enabled and increasing roughness, the reflections loose colors. There appears a gray tint that seems to be more pronounced in grazing angles and closer to the reflected object. Below images with roughness 0.01 in first and 0.3 in second.
![ssr-glossy-color](https://user-images.githubusercontent.com/6423934/62194971-7c033100-b36a-11e9-8303-350032e4f341.png)
![ssr-rough-nocolor](https://user-images.githubusercontent.com/6423934/62194973-7c033100-b36a-11e9-9d5d-36aa4349f5fc.png)

**Steps to reproduce:**

- Create a Spatial scene
- Add world environment and enable SSR
- Add 2 objects - one to reflect and one to be reflected
- Add colorful material to the reflected object
- Adjust the roughness of the material for the reflecting object and observe how reflection color changes in strange behavior

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing.
