### ISSUE TITLE
Joint have linear latency even with the strongest connection

### ISSUE THREAD

**Issue by Wapit1** [godotengine/godot#30984]
**Godot version:**

 3.1.1

**Issue description:**

 even with small impulses and the strongest setting on the joint, there is still a space and a bit of latency in the movement between the two rigidbody, instead of working like in unreal and unity were joint are allows to combine rigidbody 

**Steps to reproduce:**
joint two rigidbody in Rigid mode with a generic joint have one of the two get an impulse and see the space being created between the two rigidbody

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing.
