### ISSUE TITLE
Negative spotlight not working in GLES 2

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#30983]
**Godot version:**
3.1.1 stable

**OS/device including version:**
GNU/Linux x64

**Issue description:**
Negative spotlights don't seem to be implemented for the GLES2 renderer

**Minimal reproduction project:**
[SpotlightTest.zip](https://github.com/godotengine/godot/files/3449164/SpotlightTest.zip)

**Comment by clayjohn** [comment]
Same issue for OmniLights
