### ISSUE TITLE
Parsing error when attaching a script to a derived node type

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#30985]
**Godot version:** #331a703

**Issue description:** A script extending a given node type will fail to parse when attached to an inherited node type.

**Steps to reproduce:** Attach the following script to an Area2D node:
```
extends Node2D
func _ready():
    set_collision_mask_bit(0, true)    #Fails
    call("set_collision_mask_bit", 0, true)    #Works
```

The first line fails on parsing (in editor and in game) and outputs "Parser error "Method 'set_collision_mask_bit' is not declared in the current class". The second line works as expected in game. If this is not intended to work at all, then the editor should prevent attaching "bad scripts" to nodes.

This also happens with variables, for example `set("hframes", 10)` would work for a Sprite node.

**Comment by akien-mga** [comment]
Seems to behave as expected to me.

If your script inherits Node2D, you can only use Node2D APIs, that's normal. If you want to use Area2D APIs, you should extend Area2D.

There is a use case for under-extending though, which is that you can use the same scripts for nodes of different types, provided you only use APIs of their common ancestor in the script (or `call` statements as you showed when the node type is right).

**Comment by isaacremnant** [comment]
Closing this as the answer above makes sense.
