### ISSUE TITLE
Low gradient texture quality on Android in GLES 2

### ISSUE THREAD

**Issue by ICatRegister** [godotengine/godot#30990]
**Godot version:**
3.1.1 stable

**OS/device including version:**
Android / Windows 10
Xiaomi Redmi 5, Samsung Galaxy S8

**Issue description:**
On Android textures look like this.
No matter which flags are chosen, it does not affect the quality.
In version 2.1 everything looks the same as on the PC, so the problem only appeared in 3.1.
The problem is most noticeable with white or gray shades
![texture](https://user-images.githubusercontent.com/30937277/62193214-01dda700-b380-11e9-8f5d-7230c54f4aba.jpg)

**Steps to reproduce:**
Export to Android any texture that has gradient with transparency

**Minimal reproduction project:**
[GradientTest.zip](https://github.com/godotengine/godot/files/3450855/GradientTest.zip)

**Comment by lawnjelly** [comment]
A minimal reproduction project would still be useful imo, as it is not clear what we are looking at in the pics in terms of transparency etc. Is this occurring with an uncompressed texture?

**Comment by ICatRegister** [comment]
All textures are lossless compressed, but their quality as if they are vram compressed

**Comment by ICatRegister** [comment]
It's not a bug. Enabling the 32_bits_framebuffer option solved the problem. It's strange, the same option in 2.1 did not affect anything
