### ISSUE TITLE
Shape offset (collision) misplaced

### ISSUE THREAD

**Issue by NedAlex94** [godotengine/godot#30994]
**Godot version:**
v3.2.dev.calinou.9da24f7e3 AND Godot 3.1 Stable

**OS/device including version:**
Windoes 10, issue persists on different computers

**Issue description:**
The collision shape is mislplaced when using texture offset, even when piared with shape offset to account for it. Not all of the texture's collision shapes are misplaced, just some, for whatever reason.

**Steps to reproduce:**

Here's a screenshot explaining the problem. As you see, the collision shapes are correctly placed, paired with the shape offset

![Capture](https://user-images.githubusercontent.com/17100058/62214315-1718fc80-b3a5-11e9-943f-6936f2784c1d.PNG)

**Comment by Ranoller** [comment]
Please upload a simple test case.

**Comment by NedAlex94** [comment]
> 
> 
> Please upload a simple test case.

I placed it in this zip file
[Collision Test Case.zip](https://github.com/godotengine/godot/files/3455655/Collision.Test.Case.zip)

![image](https://user-images.githubusercontent.com/17100058/62278030-97903980-b447-11e9-8947-60f300353290.png)

**Comment by Ranoller** [comment]
Related:
Atlas_tile tex_offset:
https://github.com/godotengine/godot/issues/30781
Autotile ATLAS_TILE shape offset only applies to first tile:
https://github.com/godotengine/godot/issues/25610

For now you should do that map only with "single tile", this seems not as a bug, is not implemented functionality, it´s not easy to fix. Atlas tile has only one shape, it works like an unique tile, so it seems not possible to do a working "colliding" map with that. Main confusion is that **tileset editor** is offering a functionality that **tileset** and **tilemap** doesn´t have.

**Comment by Ranoller** [comment]
OK... this issue is not to complex. But ATLAS_TILE is broken in other ways.
Until is fixed... you can change manually the offset of the other shapes in the tres files:
[Collision Test Case.zip](https://github.com/godotengine/godot/files/3456325/Collision.Test.Case.zip)
![ManuallyFixOffsets](https://user-images.githubusercontent.com/11712737/62288809-7c302900-b45d-11e9-8bab-5a5635a26cf8.png)

**Comment by NedAlex94** [comment]
> 
> 
> OK... this issue is not to complex. But ATLAS_TILE is broken in other ways.
> Until is fixed... you can change manually the offset of the other shapes in the tres files:
> [Collision Test Case.zip](https://github.com/godotengine/godot/files/3456325/Collision.Test.Case.zip)
> ![ManuallyFixOffsets](https://user-images.githubusercontent.com/11712737/62288809-7c302900-b45d-11e9-8bab-5a5635a26cf8.png)

Thank you for the help! That is great news! it solves so many issues we had because of it
