### ISSUE TITLE
pthread build error on ios/osx

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#3099]
It seems the function pthread_setname_np has to be called differently on different platforms:

http://stackoverflow.com/questions/2369738/can-i-set-the-name-of-a-thread-in-pthreads-linux/7989973#7989973

On OSX and (presumably) iOS, you have to call it with just the name, from within the running thread.

**Comment by punto-** [comment]
Fixed, although now some platforms (like osx and iphone) won't accept calls
to rename the thread unless it's called from the thread itself (or from
gdscript if you call set_thread_name() before start())
