### ISSUE TITLE
SCRIPT ERROR: _process: Invalid get index 'foo' (on base: 'int').

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#31006]
This is a bug potentially, no one could solve it on reddit. 

Using a node js websockets server I'm sending this object, which becomes a dictionary in gdscript

`{1:{level:10, name:foo, player_index:1}, action:0, score:500}`

```
var result = Global.ws.get_peer(1).get_var() // getting the json
print (result) // this works fine and outputs the object above

for key in result:
print(result[key].name)
```
`Foo` gets printed correctly, followed by the error

`SCRIPT ERROR: _process: Invalid get index 'foo' (on base: 'int').`

I've been told [on Reddit](https://www.reddit.com/r/godot/comments/cjkwdu/script_error_process_invalid_call_nonexistent/) that there's no way to do type checking on dictionaries 

Is this a bug? And how to fix it?

**Comment by KoBeWi** [comment]
Some minimal project would be helpful.

What is `get_var()` supposed to return? Parsed JSON or raw string? There's a chance you are trying to iterate a string by characters.

Maybe try
```
for key in parse_json(result):
    print(result[key].name)
```

**Comment by elieobeid7** [comment]
the `parse_json` doesn't work, I get

`SCRIPT ERROR: _process: Invalid type in built-in function 'parse_json'. Cannot convert argument 1 from Dictionary to String`

if you want a basic example just download the basic example from here

https://github.com/gd-com/examples/tree/master/websocket/basic,

I'm using it as is, instead of sending a string, send the object I tried sending above.

I believe it returns parsed Json.

**Comment by KoBeWi** [comment]
Ok, looks like bug is in your code. When instead you do
```
for key in result:
    print(result[key])
```
You will get this output:
```
{level:10, name:foo, player_index:1}
0
500
```
See, only first value in your received dictionary is a dictionary (javascript object). You have two numbers there and you are trying to access their "name" too.

**Comment by elieobeid7** [comment]
Thank you so much.
