### ISSUE TITLE
Cannot compile via CLI (atleast not with docker)

### ISSUE THREAD

**Issue by logo4poop** [godotengine/godot#31017]
**Godot version:**
3.1.1

**OS/device including version:**
RX 570
Ryzen 2200g
KDE Neon (Docker running with alpine)

**Issue description:**
When exporting via CLI I get 
`ERROR:` _load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:285.
ERROR: start: Condition ' !scene ' is true. returned: false
   At: main/main.cpp:1739.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2095.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425.
ERROR: cleanup: Condition ' allocs_used > 0 ' is true.
   At: core/pool_vector.cpp:70.```
I am attempting to get travis ci working with my godot project so I am trying to update `
https://github.com/GameDrivenDesign/docker-godot-export to 3.1.1  my fork is at https://github.com/waitstudios/docker-godot-export/blob/master/Dockerfile

**Steps to reproduce:**
Dependencies: Docker and git
1. Clone my repo ``git clone https://github.com/waitstudios/docker-godot-export``
2. Change directory ``cd docker-godot-export``
3. Compile ``docker build -t docker-godot-export:3.1.1 .``
4. Go to the minimal project below 
5. Run this command ``` 
 sudo docker run \
       -e EXPORT_NAME="HTML5" \
       -e OUTPUT_FILENAME="index.html" \
       -v $(pwd):/build/src -v /tmp/output:/build/output docker-godot-export:3.1.1```
**Minimal reproduction project:**
[godotprojecttest.zip](https://github.com/godotengine/godot/files/3457095/godotprojecttest.zip)

**Comment by groud** [comment]
Sorry but this this problem is not up to to us, it is the maintainer or this docker plugin's one's.
Please contact him first and check what might be wrong with this setup.
If you manage to isolate the godot-only part that might be failing please open an issue without the docker-specific part (basically the command line that is not working).

**Comment by logo4poop** [comment]
> Sorry but this this problem is not up to to us, it is the maintainer of this docker plugin's one's.
> Please contact him first and check what might be wrong with this setup.
> If you manage to isolate the godot-only part that might be failing please open an issue without the docker-specific part (basically the command line that is not working).

I have figured this is a godot issue i believe

**Comment by groud** [comment]
Then please isolate the Godot command like that is not working, with which sources and all. 
Most of your reproduction steps are docker-specific commands, we are not going to spend time figuring out if there is a problem with the Dockerfile.
