### ISSUE TITLE
GLES2 3D editor and game: meshes and viewports are rendered black (no light?)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#31019]
**Godot version:**
master (https://github.com/godotengine/godot/commit/77e894768798c6d6b02759edf5774fb0cd09ac04 )

**OS/device including version:**
Arch Linux (Antergos Deepin)

**Issue description:**
<img width="377" alt="screenshot" src="https://user-images.githubusercontent.com/34406967/62316608-2b89f180-b498-11e9-9cee-5d40813db741.png">

**Minimal reproduction project:**
Any 3D game

**Comment by qarmin** [comment]
Can't reproduce on Ubuntu.
Are you sure, that you don't change default_env.tres file?

**Comment by LinuxUserGD** [comment]
It also happens on old games I made and with new projects with default cubes so it should be a bug in Godot or some missing driver. GLES3 displays everything correctly.

**Comment by qarmin** [comment]
Did you updated your graphics drivers recently?

**Comment by LinuxUserGD** [comment]
I installed dxvk today for playing games on wine, not sure if it could cause something like this.

**Comment by LinuxUserGD** [comment]
Strange thing is that this also happens for me on Windows wine

**Comment by clayjohn** [comment]
I can't reproduce either. Ubuntu 16.04 with Intel integrated drivers

**Comment by MightyPrinny** [comment]
it might be a problem with your project this doesn't happen to me either

**Comment by MightyPrinny** [comment]
this seems to happen when the sky contribution is 0 and you don't have any lights

**Comment by Skaruts** [comment]
I tried a build a few hours ago and this happened to me as well. Another build from a few days ago didn't.

**Comment by Relintai** [comment]
This happens to me too, on both windows and linux across 3 different machines.

I haven't had the time to look into it yet. I'll do a regression test later when I'll have some time on my hands, because it only started happening with my most recent build.

**Comment by Skaruts** [comment]
Also, my viewport to a 3D scene was fullly black (the scene contains an Environment with background set (through code) to custom color black).

**Comment by akien-mga** [comment]
Any errors in the terminal?

@clayjohn Sounds like redefining `round()` and co. might be problematic on some hardware in the end.

**Comment by Relintai** [comment]
No errors for me.

**Comment by Relintai** [comment]
Found it, it is caused by https://github.com/godotengine/godot/commit/47df673d737f10dcc7dbcc32a574a3589bddc3f7

**Comment by akien-mga** [comment]
CC @raphael10241024

**Comment by clayjohn** [comment]
@Relintai Are you sure? None of the code changed in 47df673 should run on a desktop.

**Comment by raphael10241024** [comment]
Unable to see it both in my mac and windows pc, I'm still trying to fingure out how this happens, it looks confusing.

**Comment by homer666** [comment]
Yeah, this has also been happening to me. All the 3D meshes in my old GLES2 projects are rendered solid black.

**Godot version:** 3.2-dev 77e894768
**OS:** Windows 10 version 1903 x64
**Graphics card:** NVIDIA GeForce 980 Ti
**Graphics driver:**  NVIDIA driver 430.64

![image](https://user-images.githubusercontent.com/27100585/62390336-5ca41800-b5a5-11e9-9d45-2468143ce76a.png)

Everything seems to work in 47df673d7... Not sure that's the culprit. I'll try bisecting in a moment.

**Comment by Relintai** [comment]
I just figured it out, that this only happens in release_debug, in debug it is not an issue, even on the current master.

On my linux machine reverting to one before the commit I linked fixed the issue, building on that commit, the issue appeared.  I'll clean rebuild everything, to double check in a few minutes.

**Comment by homer666** [comment]
Finished bisecting. 8b4c538ab is the culprit!

During my bisecting I discovered that 507e41e69 renders only ImmediateGeometry lines as black:
![image](https://user-images.githubusercontent.com/27100585/62394781-8f540d80-b5b1-11e9-8189-71e71ef9a029.png)
It's probably not the commit that broke it, but it's probably worth pointing out regardless.

**Comment by Relintai** [comment]
Yeah, I ran into errors with https://github.com/godotengine/godot/commit/8b4c538ab2d6330e0d65dc2947d05d42c7678315 too, I got a few shader errrors, but I didn't yet had the time to properly sit down and check if it's just something with my project (like I have to reimport everything). But that is definitely a different issue.

**Comment by clayjohn** [comment]
@Relintai @homer666 Doing a clean build may fix the problem! ``gles_builder.py`` doesn't rebuild shaders when only ``stdlib.glsl`` has changed. So if you did a partial build after 8b4c538 it may not have triggered a recompile and maybe thats what is causing this. 

@LinuxUserGD Can you try a full recompile and see if that solves the issue?

**Comment by LinuxUserGD** [comment]
@clayjohn What commit should I choose for the full recompile? I would do ```git reset --hard```, ```git clean``` and then ```scons p=x11 target=release_debug```

**Comment by clayjohn** [comment]
@LinuxUserGD Build from master. Instead of doing a full recompile just force gles_builder to rebuild shaders. You can do that by adding a comment to ``drivers/gles2/shaders/scene.glsl`` and ``drivers/gles2/shaders/canvas.glsl``

**Comment by LinuxUserGD** [comment]
Got some error because I was compiling with lto. Will try a full compile tomorrow (sorry!).

**Comment by homer666** [comment]
@clayjohn I tried building after using `git clean`, and also tried building from a freshly-downloaded master repo. Both don't result in any change, with either my old projects or a new one.

They were `release_debug` builds, mind you; `debug` builds have been working fine.

**Comment by Relintai** [comment]
The black immediate geometry stuff will require more testing. I'll continue tomorrow, with git cleans and scons cache cleans to find the proper culprit. It was https://github.com/godotengine/godot/commit/47df673d737f10dcc7dbcc32a574a3589bddc3f7 for me on linux, but without clearing caches, so this might not be the right one. If I find it, I'll open an another issue for that (or pr if I can fix it).

However for the black spatial meshes https://github.com/godotengine/godot/commit/8743da90d964f7b9110f6e3578fba30ac810f6ac seems to be the culprit consistently, on both windows and linux.

A few more screenshots, because the original one really doesn't do this justice, it even confused me first.

Both are windows, release_debug, 64bit builds. The same project.

This is at 3256fbfd:
![3256fbfd_01](https://user-images.githubusercontent.com/16229538/62404974-5e67de80-b599-11e9-9676-fc860f719efd.png)

![3256fbfd_04](https://user-images.githubusercontent.com/16229538/62404975-6031a200-b599-11e9-9d0c-1434e989f5e5.png)


This is at 8743da90:
![8743da90_01](https://user-images.githubusercontent.com/16229538/62404965-527c1c80-b599-11e9-9461-07a0e7b2701f.png)

![8743da90_02](https://user-images.githubusercontent.com/16229538/62404972-5a3bc100-b599-11e9-9d16-d4f998f5019d.png)

The same happens on linux,

I've also tried adding lights, and textures, I get the same black box.

And on GLES3 it works perfectly.

**Comment by clayjohn** [comment]
Okay, I can now confirm 3f25dde6b4c46bec1fd25a3dd8f65c774b0fef94 breaks rendering initially, but only for the lines and grid and then 8743da9 breaks everything else. However, debug builds are fine. 

I do not understand why these commits have broken rendering in that way. There are no errors, so the shaders must be compiling fine. @akien-mga  We may need to just revert for now and figure something else out...]

**Comment by Relintai** [comment]
I managed to figure out how to get shader compile errors.

The key to it is having a WorldEnvironment in the Scene with fog enabled.

Minimal example project:
[Test_bl.zip](https://github.com/godotengine/godot/files/3463525/Test_bl.zip)

Open the project, click on the MeshInstance Node in the scene, and in the mesh property create a new mesh, something that's not an empty ArrayMesh.

I've tried it with multiple builds, it errors every time.

Also, these are the errors I get:

[shader_error.txt](https://github.com/godotengine/godot/files/3463530/shader_error.txt)

**Comment by LinuxUserGD** [comment]
@Relintai I get some more errors when trying your minimal example project:
```Swift
 drivers/gles2/shader_gles2.cpp:129 - SceneShaderGLES2: Fragment shader compilation failed:
0:1831(120): error: `light_direction' undeclared
0:1831(102): error: no matching function for call to `dot(vec3, error)'; candidates are:
0:1831(102): error:    float dot(float, float)
0:1831(102): error:    float dot(vec2, vec2)
0:1831(102): error:    float dot(vec3, vec3)
0:1831(102): error:    float dot(vec4, vec4)
0:1831(98): error: no matching function for call to `max(error, float)'; candidates are:
0:1831(98): error:    float max(float, float)
0:1831(98): error:    vec2 max(vec2, float)
0:1831(98): error:    vec3 max(vec3, float)
0:1831(98): error:    vec4 max(vec4, float)
0:1831(98): error:    vec2 max(vec2, vec2)
0:1831(98): error:    vec3 max(vec3, vec3)
0:1831(98): error:    vec4 max(vec4, vec4)
0:1831(98): error:    int max(int, int)
0:1831(98): error:    ivec2 max(ivec2, int)
0:1831(98): error:    ivec3 max(ivec3, int)
0:1831(98): error:    ivec4 max(ivec4, int)
0:1831(98): error:    ivec2 max(ivec2, ivec2)
0:1831(98): error:    ivec3 max(ivec3, ivec3)
0:1831(98): error:    ivec4 max(ivec4, ivec4)
0:1831(94): error: no matching function for call to `pow(error, float)'; candidates are:
0:1831(94): error:    float pow(float, float)
0:1831(94): error:    vec2 pow(vec2, vec2)
0:1831(94): error:    vec3 pow(vec3, vec3)
0:1831(94): error:    vec4 pow(vec4, vec4)
0:1831(69): error: operands to arithmetic operators must be numeric
0:1831(19): error: no matching function for call to `mix(vec3, vec3, error)'; candidates are:
0:1831(19): error:    float mix(float, float, float)
0:1831(19): error:    vec2 mix(vec2, vec2, float)
0:1831(19): error:    vec3 mix(vec3, vec3, float)
0:1831(19): error:    vec4 mix(vec4, vec4, float)
0:1831(19): error:    vec2 mix(vec2, vec2, vec2)
0:1831(19): error:    vec3 mix(vec3, vec3, vec3)
0:1831(19): error:    vec4 mix(vec4, vec4, vec4)
0:1847(35): warning: `fog_color' used uninitialized
0:1847(47): warning: `fog_color' used uninitialized

 drivers/gles2/shader_gles2.cpp:360 - Method/Function Failed, returning: __null
 drivers/gles2/shader_gles2.cpp:88 - Condition ' !version ' is true. returned: false
 drivers/gles2/shader_gles2.h:254 - Condition ' !version ' is true. returned: -1
```

**Comment by Relintai** [comment]
After seeing @LinuxUserGD 's error, out of curiosity I put a "#define USE_LIGHTING" into scene.glsl both under the [vertex], and under the [fragment] shader mark, and now it seems to work. Even without a WorldEnvironment,

![define_01](https://user-images.githubusercontent.com/16229538/62411423-bd0d7680-b5f2-11e9-987b-22327d1d6050.png)

![define_02](https://user-images.githubusercontent.com/16229538/62411425-bf6fd080-b5f2-11e9-9e24-4831941a685c.png)

**Comment by Relintai** [comment]
I think I found it, in shader_gles2.h the conditionals like USE_LIGHTNING is stored in conditional_version.version as bits.

Before those 2 commits the Conditionals array for the scene shader contained exactly 32 entries.

conditional_version.version is an uint32_t.

And now USE_LIGHTNING's index is 33 in the array, so it just won't gets set anymore.

**Comment by clayjohn** [comment]
@Relintai Great work! Keep us updated!

**Comment by clayjohn** [comment]
@Relintai I asked Reduz what to do, he explained that we can avoid creating extra code_versions if we use ``#if defined()`` instead of ``#ifdef``. Accordingly, we can avoid that 32 conditions limit. Chaosus is making a PR now to fix this.

**Comment by Relintai** [comment]
Really cool! This solution is soo much simpler and better! Thanks!

**Comment by LinuxUserGD** [comment]
Thanks! After deleting all the *glsl.gen.h files, everything is working again :+1:
