### ISSUE TITLE
Crash on newly cloned git version of Godot

### ISSUE THREAD

**Issue by Smilex** [godotengine/godot#3103]
To test out Godot for the first time, I created a new project, placed some 2D nodes, and wrote a player script.
Having one Node2D, with a player script and the default texture for the sprite worked fine, I could run around.
When I set the scene up so that there was a root node, with two child nodes, one being the previous player and the new one being a copy, without the player script (I did this to test raycasting), it crashes every time.
I'm on Ubuntu 15 64bit

This is my script

```
extends Node2D

var velocity
var acceleration
var top_speed
var mass
var g_acc
var friction_co

func _ready():
    set_process(true)
    velocity = Vector2(0,0)
    acceleration = 1000
    top_speed = 560
    mass = 80
    g_acc = 9.82
func _process(dt):
    var horizontal = 0
    if (Input.is_action_pressed("move_right")):
        horizontal += 1
    if (Input.is_action_pressed("move_left")):
        horizontal -= 1
    if (horizontal == 0):
        friction_co = 1.2
    else:
        friction_co = 0.18
    var current_position = get_pos()
    var new_position = current_position
    var prev_velocity = velocity
    velocity.x += horizontal * acceleration * dt
    var vel_mag = velocity.length()
    if (vel_mag > top_speed):
        velocity = prev_velocity
    var direction = velocity.normalized()
    var surf_norm = Vector2(0, -1)
    var gravity_dir = Vector2(0, 1)
    var gravity = gravity_dir * mass * g_acc * dt
    var space_state = get_world_2d().get_direct_space_state()
    var ray_result = space_state.intersect_ray(current_position, new_position)
    if (not ray_result.empty()):
        velocity = Vector2(0,0)
    else:
        var friction = -direction * friction_co * gravity.y
        velocity += friction
        new_position += velocity * dt
        set_pos(new_position)
```

This was the terminal output

```
OPENING: /home/ian/workspace/godot_test (::home::ian::workspace::godot_test)
freed code id 1
ian@tux-station:~/source/godot/bin$ VBoxContainer: 136,100
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:598.
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:598.
ERROR: add_child: Can't add child, already has a parent
   At: scene/main/node.cpp:740.
ERROR: add_child: Can't add child, already has a parent
   At: scene/main/node.cpp:740.
bind toptions
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:598.
ERROR: grab_focus: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:2218.
ERROR: grab_focus: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:2218.
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:625.
settings changed
ERROR IN: /icon.png
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/unix/file_access_unix.cpp:236.
ERROR IN: /new_scene.scn
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/unix/file_access_unix.cpp:236.
ERROR IN: /player_gd.res
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/unix/file_access_unix.cpp:236.
ERROR IN: /player_script.res
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/unix/file_access_unix.cpp:236.
ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core/math/octree.h:827.
ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core/math/octree.h:827.
ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core/math/octree.h:827.
ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core/math/octree.h:827.
ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core/math/octree.h:827.
ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core/math/octree.h:827.
freed code id 3
freed code id 5
freed code id 4
freed code id 6
freed code id 2
ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:246.
freed code id 1
```

**Comment by vnen** [comment]
This is a very broad description and may be a lot of things. Could you try to narrow the bug and/or provide a sample project (as a zip file or as a GitHub repository)?

**Comment by reduz** [comment]
Please make an example project

**Comment by vnen** [comment]
@Smilex ping

**Comment by Smilex** [comment]
Sorry. Forgot all about this.
I tried to recreate this, and I got it to happen the first time. But since it crashed, I wanted to do it a second time to save it, and that's when I noticed that I had loaded script from other files that were actually projects or something.
There was no crash when I didn't do that.

**Comment by techtonik** [comment]
@Smilex so, this can be closed?

**Comment by Smilex** [comment]
@techtonik I don't know. I don't know how you want Godot to work, all I can say is that I didn't like it working that way. I couldn't figure out which files to open, and Godot crashes if you do it incorrectly

**Comment by reduz** [comment]
if you can post a project that crashes We´ll be glad to take a look at it
and fix it

**Comment by Smilex** [comment]
Just create two projects, and in one of the projects reference a project file as a script for any object, and run.

**Comment by akien-mga** [comment]
Could you be more specific? What is the second project used for? Do you create a scene in the first project, do you save it, what node do you use as root node, what node do you attach the script to, etc.? 

The steps you gave are very broad and are what Godot users do all the time when using Godot, so if that was triggering reproducible crashes every time, we'd know about it and it would have been fixed by now :) So it's likely that you are doing something much more specific than what you just described.

**Comment by Smilex** [comment]
But I can't give you the specific project, because it crashes without saving, so I have to set it up again everytime. And everytime It's the same thing. One root node (Node type), two child nodes (Node type), each with a sprite and collision box.
I try to add the above script as the script for one of them, but when I get the file browser window, it shows me scenes or projects or something, where I was expecting scripts. I pick one of them.
I run the thing, it crashes. I've tried this several times now. I can't do it again for sometime, because I've installed Windows and haven't fixed Grub yet

**Comment by techtonik** [comment]
@Smilex the most obvious way is to not forget all steps being made in the specific order is to record a screencast with something like https://github.com/cessen/recordscreen

**Comment by bojidar-bg** [comment]
If there is no way to reliably reproduce this issue (doesn't matter the version), I think it should be closed.

**Comment by techtonik** [comment]
@Smilex close it?
