### ISSUE TITLE
The cursor icon moves slower then the mouse.

### ISSUE THREAD

**Issue by miblooming** [godotengine/godot#31038]
**Godot version:**
3.1.1

**OS/device including version:**
Windows10.0.17763.379

**Issue description:**
The cursor icon moves slower then the mouse.
I expect the icon following the mouse immediately.

```
onready var cursor_icon = $cursor_icon
func _process(delta):
	sync_cursor_icon()
	
func sync_cursor_icon():
	cursor_icon.position = get_viewport().get_mouse_position() + Vector2(24,24)
```

**Comment by Zylann** [comment]
See my answer on Q&A: https://godotengine.org/qa/49505/how-to-make-sprite-be-perfectly-next-to-the-mouse-at-all-times

**Comment by Calinou** [comment]
As @Zylann pointed out, this is a limitation of using a software cursor. Consider defining a custom mouse cursor in the Project Settings (or setting it using `Input.set_custom_mouse_cursor()`) to benefit from an hardware cursor, which will follow the mouse immediately.

**Comment by Calinou** [comment]
As @Zylann pointed out, this is a limitation of using a software cursor. Consider defining a custom mouse cursor in the Project Settings (or setting it using [`Input.set_custom_mouse_cursor()`](https://docs.godotengine.org/en/latest/classes/class_input.html#class-input-method-set-custom-mouse-cursor)) to benefit from an hardware cursor, which will follow the mouse immediately.

**Comment by miblooming** [comment]
@Calinou My requirement: 
There are hundreds of prop in my game. 
After player selected a prop, I expect  that an icon follow the cursor.
If using hardware cursor, I need to create hundreds of cursor.
I have made a demo in Unity last month, soft cursor works.
So i think this is not an insurmountable difficulty for Game Engine.

**Comment by miblooming** [comment]
@Calinou I check my code in Unity. 
I find that I have hide the system cursor. 
The delay almost can not be perceived.
It's really an insurmountable difficulty of the delay technically.

At last I find a trick.
1)Hide the system cursor
Input.set_mouse_mode(Input.MOUSE_MODE_HIDDEN)
2)create a cursor node, with two child node:
a) a cursor image like the system cursor
b) a sprite which is changeful

Without the reference substance(system cursor), the cursor and sprite moves  at the same time. And players almost can not perceive the delay.
