### ISSUE TITLE
TileSet editor creates redundant navigation polygons

### ISSUE THREAD

**Issue by guycook** [godotengine/godot#31049]
**Godot version:** v3.1.1.stable.official

**OS/device including version:** Windows 10 17763

**Issue description:**

When modifying the vertices of a polygon in the Navigation pane of the TileSet editor, duplicate polygons are saved out to the .tres file, 1 per modification. i.e.

```
[sub_resource type="NavigationPolygon" id=2]
vertices = PoolVector2Array( 0, 16, 32, 0, 64, 16, 32, 32 )
polygons = [ PoolIntArray( 0, 1, 2, 3 ) ]
```
after one modification becomes
```
[sub_resource type="NavigationPolygon" id=2]
vertices = PoolVector2Array( 1, 16, 32, 0, 64, 16, 32, 32 )
polygons = [ PoolIntArray( 0, 1, 2, 3 ), PoolIntArray( 0, 1, 2, 3 ) ]
```
and if you play around a while you'll end up with
`polygons = [ PoolIntArray( 0, 1, 2, 3 ), PoolIntArray( 0, 1, 2, 3 ), PoolIntArray( 0, 1, 2, 3 ), PoolIntArray( 0, 1, 2, 3 ), ...`

Besides the obvious of untidy diffs, larger tres files and a perf hit when the navmesh is being collected, this actually breaks navigation in the affected tiles (is this a seperate bug? I wouldn't expect two overlapping polys to prevent navigation). My player couldn't move in or out until I went into a text editor to remove all but the first `PoolIntArray`

**Steps to reproduce:**

1. Create a TileSet resource and at least one tile
2. On the Navigation pane, "Create a new polygon" and finalise it by closing
3. Modify one of the points then save

Example
![2019-08-03_15-47-54](https://user-images.githubusercontent.com/3148046/62407450-cc012280-b60c-11e9-84b7-bb301987c9cb.gif)

**Comment by sparkart** [comment]
It's a weird bug... could you provide a sample project? I tested with version 3.2.dev and it doesn't add extra polygons after each save, although there are two instead of one.

I tested with version 3.1 but it only adds another polygon once. It starts off with two, then on the next save it adds another one resulting to three total. But modifying and saving afterwards doesn't add extra polygons like your example.

**Comment by guycook** [comment]
Here's the minimal repro, the Tileset.tres isn't modified by me but exactly as it came out of the editor. I just made the nav polygon on the red tile correctly on the first try, whereas the green had 3 points out of place which I then corrected (hence now 4 polygons). If I keep playing around with it, more get added.

[navtiles.zip](https://github.com/godotengine/godot/files/3463727/navtiles.zip)

**Comment by Xrayez** [comment]
I've had this effect when developing my own custom editor plugin in GDScript, happened while I was manually saving the resource instead of delegating the task to editor itself or so.

Also likely something doesn't clear the polygons on editing.
