### ISSUE TITLE
Pool*Array.resize(x) causes old data from memory to leak into the array

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot#31040]
When resizing Pool\*Array types, the Godot Engine reserves a continuous memory space and does not clear the old values from the memory cells when allocating memory to the Pool\*Array type. 

I was working with PoolIntArrays by printing their contents to the console after resizing them and
each time the result was different. Mostly the array was filled with zeroes, but occasionally I would encounter some total gibberish values in the array which I had not assigned to them. 
I tried to replicate the issue with the regular Array type and all uninitialized values were of type null. 

I expected the PoolIntArray to be initialized to all zeroes when resizing, instead it was occasionally filled with gibberish, which was different every time the code was run. 
I think the Pool\*Array types should be initialized automatically to zero by the Godot Engine when they are resized and this should not be left in the hands of game developers, who are not expected to understand these kind of issues. 

P.S. @reduz

**Comment by xcrdev** [comment]
I would suggest that the documentation on Pool*Array be updated to state that resize does not clear the memory allocated.

**Comment by aspenforest** [comment]
That's also a possibility, but which solution prevents bugs better?

**Comment by xcrdev** [comment]
My preference is for the data to be cleared on resize.  But if that’s not reasonable at this time then I would like to have the documentation updated to reflect that data is not cleared on a resize.

**Comment by KoBeWi** [comment]
This was fixed when Pool*Arrays were changed into Packed*Arrays.

**Comment by Shatur95** [comment]
Can reproduce on 3.2.3:

```gdscript
var slots: PoolIntArray = [1]
slots.resize(slots_count)
_create_team(slots)
```

But can be workarounded:

```gdscript
var slots: Array = [1]
slots.resize(slots_count)
_create_team(PoolIntArray(slots))
```

Will the problem be fixed in this version?

**Comment by Shatur95** [comment]
Can reproduce in 3.3 too. There is [a similar issue](https://github.com/godotengine/godot/pull/44827).
