### ISSUE TITLE
inst2dict and dict2inst fail in compiled version of game

### ISSUE THREAD

**Issue by CJCarns** [godotengine/godot#31045]
**Godot version:**

v3.1.1.stable.official

**OS/device including version:**

Windows 10

**Issue description:**

Attempting to use inst2dict and dict2inst to serialize an object works perfectly in editor but fails in the compiled version of the game. Game does not crash, but the behaviour fails and the console logs this error: [console.png](https://i.imgur.com/Zrr7TPv.png)
It appears to be confused about .gd files vs .gdc files.

**Steps to reproduce:**
Will try later, had to leave but wanted to post in case I'm crazy.
Create a new project. Create a basic object with some simple fields, floats, arrays, ints, etc.
Use inst2dict and/or dict2inst.
Run in editor.
Run compiled as an .exe windows application.
Look at console in compiled version.

**Minimal reproduction project:**

Will make one later, just wanted to post ASAP.

**Comment by Xrayez** [comment]
Likely related to the fact that certain methods are only present in debug mode, also (de)serializing objects/scripts could be a culprit. Also could fail if serializing at `res://` path?

**Comment by CJCarns** [comment]
@Xrayez It does seem to be using paths to serialize and deserialize the object. My objective is simply to efficiently send all the data of an object to other players in a network without having to constantly go back and modifiy the data sending every time I add to this object in the future. I.e. if and when I add another field to the object I don't want to have to edit the serialization and deserialization each time. Is there a better way to do this? Perhaps somehow iterating over the fields in an object and deconstructing and reconstructing them in an array? I also want to ensure it's quick especially being sent over a network.

**Comment by Xrayez** [comment]
I think you and me want to achieve this: #16793.

My previous approach was indeed using `inst2dict` and `dict2inst` to do this, and I've also encountered some inconveniences with it:  #6533, https://github.com/Xrayez/godot/commit/74ffc1a3c9c54534145460e5f53e357ec0a608a8

What I've come up is essentially gathering those properties I'm interested in synchronizing over the network. So I define `get_properties` for each node type to return a dictionary defining how and when those should be replicated.

Also see cautions tale described in #27485 about object serialization (pertains to encoding).

**Comment by CJCarns** [comment]
That would be awesome to implement. If I wasn't new at networking and I had more time I might be tempted to collaborate on it. Unfortunately I'll probably have to do it more by hand. Thank you for the references!

**Comment by Xrayez** [comment]
I couldn't reproduce, inst2dict/dict2inst doesn't fail on their own, but the `@path` dict property is not cross-compatible between editor/exported project as seen in #26188.
