### ISSUE TITLE
GUI support for multilinguar texts in RichTextLabel (new property for translation keys)

### ISSUE THREAD

**Issue by GovanifY** [godotengine/godot#3105]
As the title says, when you want to add keys that are put in a translation file in a richtextlabel, you have to do it through code, since the UI just prints the text. The code looks like this:

extends RichTextLabel
func _ready():
        #set_text doesn't exists for richtext, so let's use add_text
	get_node(".").add_text(tr("EXPZ_DESC_00"))
	pass

But when rendered on screen it acts like this: http://www.gyazo.govanify.com/grab/0246fb.png
It can be seen clearly that BBCode isn't parsed, while enabled in the projects and font setted up.

On a side note you also have to set up the size of the text in a richtext label, unlike a normal label, which you don't specially know when translating stuff,

**Comment by GovanifY** [comment]
Nevermind, set_bbcode does the job. Though letting this issue still since the key support should be added in main GUI imo

**Comment by GovanifY** [comment]
As another comment \n or real line returns aren't parsed correctly in a CSV file. It should also be worked on.

**Comment by akien-mga** [comment]
> Though letting this issue still since the key support should be added in main GUI imo

What do you mean with "key support"?
