### ISSUE TITLE
`class_name` and `extends` should be re-ordered

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#31056]
Godot 3.2

The fix for https://github.com/godotengine/godot/issues/24364 made it so `class_name` would be expected after `extends`, not before, so that it gets registered with the correct base.
However, like it was mentionned in the PR https://github.com/godotengine/godot/issues/29345, I think it's not a good fix, for mainly two reasons:
- It breaks compatibility. My code no longer works with this change, as I have to re-order all uses of `class_name`.
- It is confusing. Reading the name of a class after the one it extends is unusual.

So I think it should be made to work either order-independent, or make it so `class_name` actually works when written before `extends`.

**Comment by arkology** [comment]
+1 for order-independent

**Comment by Calinou** [comment]
> +1 for order-independent

We should still have a recommended order in the [GDScript style guide](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) though.

**Comment by Sslaxx** [comment]
Having support for the syntax `class_name foo extends bar` could be a good way of handling this?

**Comment by Xrayez** [comment]
For some time I thought this was possible and one of the reasons why this might be difficult to solve:
![class_name_inner](https://user-images.githubusercontent.com/17108460/62453246-9ed28280-b77a-11e9-9f9a-5bc641b68ffa.png)

But this makes sense, which would make the independent order easier to implement?

> Having support for the syntax class_name foo extends bar could be a good way of handling this?

Figured that it doesn't work correctly either, it works but it forces to extend `Reference` that way. 👀
Likely it just parses the `class_name` part and skips over the `extends` part, and the script extends `Reference` by default if `extends` keyword is omitted. The bug is hidden on master because of this very issue regarding order.

**Comment by Xrayez** [comment]
Also, it would be really nice to be able to use `class` keyword to be registered as a `class_name` if it appears before `extends`, that way we could avoid having to use somewhat ugly `class_name` keyword. Users would still be able to write `class_name` after `extends`.

**Comment by Sslaxx** [comment]
> For some time I thought this was possible and one of the reasons why this might be difficult to solve:
> ![class_name_inner](https://user-images.githubusercontent.com/17108460/62453246-9ed28280-b77a-11e9-9f9a-5bc641b68ffa.png)
> 
> But this makes sense, which would make the independent order easier to implement?
> 
> > Having support for the syntax class_name foo extends bar could be a good way of handling this?
> 
> Figured that it doesn't work correctly either, it works but it forces to extend `Reference` that way. eyes
> Likely it just parses the `class_name` part and skips over the `extends` part, and the script extends `Reference` by default if `extends` keyword is omitted. The bug is hidden on master because of this very issue regarding order.

If it's a bug, is it reported on the tracker?

**Comment by Xrayez** [comment]
> If it's a bug, is it reported on the tracker?

Seems like not, I could open an issue once it's reproducible in master.
