### ISSUE TITLE
Suggestion about code highlighting

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#31054]
Keywords could be separated into a few categories and use different colors. Currently they're all the same color. This is not a big deal, but I think it would be an improvement.

Personally, I wouldn't even mind it if they were still kept all the same color by default. Just the option to change the colors would be a nice thing to have for highly visual people like me.

Something like:

**declaration keywords:** 
```func, var, enum, extends, onready, export, setget, etc.```

**built-in functions:**
```seed(), randomize(), hash(), print() [and its variations], randi(), push_error(), str(), int(), float(), etc.```

**common**
```if, elif, else, match, for, while, and, or, is, as, return, etc.```

**values/types**
```false, true, null, int, float, void, etc.``` 

---

On a related thought, what if return type syntax (`-> Node2D`, `-> void`) also used its own color for all types?

**Comment by Calinou** [comment]
Visual Studio Code's default *Dark+* theme distinguishes control flow keywords from other keywords such as `func` and `var`:

![image](https://user-images.githubusercontent.com/180032/62411350-ca763100-b5f1-11e9-9b78-f592b5097a27.png)

I think this would be a good start :slightly_smiling_face:

**Comment by Calinou** [comment]
This was addressed by https://github.com/godotengine/godot/pull/33577 and https://github.com/godotengine/godot/pull/47751, closing.
