### ISSUE TITLE
Bug: All Global variables (singletons) show in the debugger errors' tab

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#31052]
Godot 3.1, if you declare a global variable in autoload (maybe you call it singleton)

`var foo = 0`

And then you call it in another file

`Global.foo = 5`

The debugger error tab will still show

`The class variable 'foo' is declared but never used in the script.`

 Godot has to understand that Globals are not meant to be used in the same file anyhow.

So if you declare foo as global, you can't do `foo+=1` inside the global file. 

I have like 15 global variables and dictionaries, it's so annoying to the extent that I don't check the debugger errors anymore. I only check the red errors, reading what the debugger has to say is a waste of time.

**Comment by KoBeWi** [comment]
Related to #23207 and #29829

**Comment by elieobeid7** [comment]
@KoBeWi  Should I close it then or leave it open? What's the policy of handling duplicates?

**Comment by KoBeWi** [comment]
I'd close it if it's duplicate, but while it's similar problem than the issues I linked, they don't cover singletons. So it's fine if this one stays too.

**Comment by KoBeWi** [comment]
Fixed in 3.2, probably together with #23207
