### ISSUE TITLE
Ctrl+Click on a constant opens doc but doesn't scroll to definition (2)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#31067]
Godot 3.1.1

Similar to https://github.com/godotengine/godot/issues/17396
In the following script, Ctrl+clicking `UPDATE_ONCE` opens `Viewport` docs, but doesn't scroll to the enum value.

```gdscript
extends Viewport

func update():
	render_target_update_mode = Viewport.UPDATE_ONCE
```

**Comment by aole** [comment]
Seems to be fixed in the master. Cannot reproduce this (CTRL+Click goes to exact doc definition).

**Comment by Calinou** [comment]
I can't reproduce this either on https://github.com/godotengine/godot/commit/3db1d400458853bfa33c4605c819d368c11e4a57, so I'll close this.
