### ISSUE TITLE
Are empty lines and comments removed automatically when building the project?

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#31060]
Sorry for having to ask here, no one is sure on Reddit, and I don't use facebook, please close the issue after answering it. Seems like the only ones who can answer this are the core dev who spend time here.

When building a project, to the various platforms, does Godot remove new lines, empty spaces, and comments or should I write my own bash script that does that?

**Comment by LinuxUserGD** [comment]
Export to .zip, unpack and view the .gdc files

**Comment by clayjohn** [comment]
@elieobeid7 This is not the proper place to ask questions. This is for bug reports only. 

Please see the docs page on community channels where you can ask questions. 
http://docs.godotengine.org/en/latest/community/channels.html

In particular there is a site dedicated to asking questions: https://godotengine.org/qa/

**Comment by elieobeid7** [comment]
@clayjohn  couldn't you just answered me while closing my issue man? you're a core developer? if so you know the answer. Anyhow, I'll ask there, but that's not the point.

My question is a yes and no question, doesn't require explanation nor it takes time to answer it, and the only people who can answer it are the core developers.

**Comment by LinuxUserGD** [comment]
@elieobeid7 I'm not a developer, just a one commit contributor, bit I think I already answered your question.

**Comment by elieobeid7** [comment]
@LinuxUserGD I'm searching for a binary viewer to read the files, no text editors can open .gdc file on my pc, it's not a thing I do, after opening it, let's pray that I understand what I see. Have you ever done that? If so what are your results?

**Comment by clayjohn** [comment]
@elieobeid7 Im not a core developer, I'm on the bugsquad. My job is to flag issues and to direct people to the proper channels. Again, this is not the place to ask quesitons, use the QA (question and answer) site for that.

> My question is a yes and no question, doesn't require explanation nor it takes time to answer it, and the only people who can answer it are the core developers.

I don't know the answer. Even though it is a yes or no question, it takes a lot of knowledge to answer. Further, even if I was a core developer I might not know the answer. Godot has a huge codebase and no single person understands all of it.

**Comment by elieobeid7** [comment]
@clayjohn But what I asked should be common knowledge, how can a studio release a game using it while leaving all the comments and garbage in it? Anyone using Godot for anything real should know the answer, otherwise, his code is rubbish.

My very first job I didn't know angular, the CTO had a maven file that runs webpack, we ran builds on a Jenkins server, he had to go through webpack and create custom stuff just to remove code that can't make it into production.

**Comment by LikeLakers2** [comment]
@elieobeid7 The answer to your question is yes, they are removed automatically (at least as far as I'm aware).

That said, please be aware of how you're treating others in the future. Regardless of how much you might want to believe something is "common knowledge," (even to a group like the core contributors) you'd be surprised at the things that aren't. Give people the benefit of the doubt in the future.

Also, as clayjohn said, this sort of question should go on the Q&A site, not on this bugtracker. If nobody there knows, you have about [many other community forums](https://godotengine.org/community) that you could try.

**Comment by elieobeid7** [comment]
@LinuxUserGD Opening the GDC doesn't help, I opened it in VSCODE, it's binary so obviously, I didn't understand anything, and probably the file got opened in the wrong encoding, but there are 5 # in the main.gdc and 1 # in main.gd

plus the signals name are written in ASCII in .gdc and there are spaces and empty lines.

This is not decisive, I should've seen only 1 # but saw 5, so can't draw any correlation between what I saw and the reality

**Comment by elieobeid7** [comment]
@LinuxUserGD 

- I asked everywhere, please check Godot Q&A site, Reddit and facebook page

- How did I "treat" others wrong? By saying that if Godot doesn't clean your code, it's rubbish? Since when is reality harsh? plus I did not attack anyone, I'm stating facts, my code is full of shit if Godot doesn't clean it that's why I'm here asking.  Everyone is sensitive these days for the silliest of reasons and goes into defensive mode. 

I'm saying anyone who do godot for production must know the answer. It's like writing c without knowing if it does garbage collection or not....

**Comment by LikeLakers2** [comment]
@elieobeid7 
>I asked everywhere, please check Godot Q&A site, Reddit and facebook page

You've still got the IRC chat, the Discord chat, the Twitter, Godot's forums, and the Steam Community to try out. I wouldn't really call that everywhere. Like I said, even if the Q&A site (and in your case, reddit and facebook as well) doesn't work, you've still got many other places you could ask -> https://godotengine.org/community

**Comment by elieobeid7** [comment]
@LikeLakers2 okay then I'll just write some bashscript to clean the code, seems that's faster than asking the developers.

**Comment by LikeLakers2** [comment]
With all due respect, I *did* answer your question above:

>The answer to your question is yes, they are removed automatically (at least as far as I'm aware).

**Comment by elieobeid7** [comment]
I got my answer on facebook

> # comments get removed
> """ comments don't get removed according to documentation
> gdcript is a wrapped language it optimize the native langue (c++) and building release take care of everything is not necessarily

https://www.facebook.com/groups/godotengine/1618120818324506/?comment_id=1618142058322382&notif_id=1564859497098091&notif_t=group_comment&ref=notif

Do you agree or disagree with that statement?

**Comment by Calinou** [comment]
@elieobeid7 `"""` is used for multiline strings, not comments. When you write a `"""` statement on its own line, it's a standalone string which won't have any effect on the resulting code, but it will still be present in the script.

Only `#` can be used to write actual comments in GDScript.

**Comment by elieobeid7** [comment]
@Calinou thank you, I'll follow @LikeLakers2 advice because I don't use `"""` because the editor doesn't understand it anyway.

**Comment by LikeLakers2** [comment]
@elieobeid7 My apologies for the misunderstanding. It never occurred to me that you might be confused about the difference between `# comments` and `"""comments"""`, up until you posted that comment from facebook. (In fact, I admit I had forgotten about `"""comments"""` because I so rarely see `"""this"""` used as comments that I often forget the syntax even exists. Sorry.)

Also, sorry for the whole "please be kinder in the future" when it wasn't actually needed! I realize that may have come off as rude.

**Comment by elieobeid7** [comment]
@LikeLakers2 I am sorry too, now that I read what I said, I guess could've been nicer :) Thank you for everything, have an awesome weekend.

**Comment by elieobeid7** [comment]
@LikeLakers2 I am sorry too, now that I read what I said, I guess could've been nicer :) Thank you for everything, have an awesome weekend.

**Comment by LinuxUserGD** [comment]
<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/34406967/62417185-f91ff600-b649-11e9-8e6d-6e2a601a5bb2.png">
Maybe it depends on the platform and on the export settings but here comments are still in the .pck as you can see when you type in this code in https://gdscript-online.github.io/

**Comment by Calinou** [comment]
@LinuxUserGD See https://github.com/godotengine/godot/issues/24716.
