### ISSUE TITLE
Opening the context menu of a SpinBox node sets it to its max value

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#31069]
**Godot version:**
e14e08c

**Issue description:**
When right-clicking a `SpinBox` node to open its context menu, the value will be set to max value defined for it (100 by default). After a quick analysis, I found that the commit where the bug appeared was this one: #29067 

CC @KoBeWi

**Comment by Anutrix** [comment]
Issue probably caused by https://github.com/godotengine/godot/blob/7126654eafc5a50a782bfbcdcfcb243807662eab/scene/gui/spin_box.cpp#L119
I don't get the reason for this line to be present there. Seems to be there since Godot was open-sourced. Could it be part of some old logic/design?
