### ISSUE TITLE
Please move breakpoint related commands from Edit to Debug menu

### ISSUE THREAD

**Issue by thatcashcow** [godotengine/godot#31071]
Commands like Toggle Breakpoint, Remove all breakpoints could be in Debug menu. Thanks!

**Comment by KoBeWi** [comment]
They are already moved to a dedicated menu in 3.2-dev.
![image](https://user-images.githubusercontent.com/2223172/62423738-9a4b9280-b6c4-11e9-888d-1b235842c553.png)
