### ISSUE TITLE
Spawned SceneTree's network_peer never accepts RPCs. Unclear error message "Mode is 0"

### ISSUE THREAD

**Issue by droqen** [godotengine/godot#31074]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Client will connect to server, but received "Mode is 0" error upon attempt to call any RPC.
![image](https://user-images.githubusercontent.com/5104632/62423337-aec06880-b68d-11e9-8139-cbbbf28607af.png)

`remote func` is supposed to set Mode to 2 or some other value, but Mode is 0 even if I call rpc_config to manually set Mode. (I think somewhere in the multiplayer code it must be reading from the base scenetree, even though it allows me to set network peer of a non-base scenetree.)

I would expect either:

1. A warning message or error upon calling a non-base scenetree's set_network_peer function (since it does not appear to function properly anyway),

2. Or for a non-base scenetree's set_network_peer function to work fully.

**Steps to reproduce:**
1. Spawn two SceneTrees.
2. Use `spawnedSceneTree1.set_network_peer(clientHost)` and `spawnedSceneTree2.set_network_peer(serverHost)` to set up two NetworkedMultiplayerENets in the same project: one client and one server.
3. They will connect successfully, but all rpcs will fail with the error citing "Mode is 0" as the reason for failure.

**Minimal reproduction project:**
[server+client mode 0 minimal.zip](https://github.com/godotengine/godot/files/3464871/server%2Bclient.mode.0.minimal.zip)

**Comment by Faless** [comment]
For what I can see the server script is never added to the other tree, i.e both client and server are part of the same tree.
Additionally you are calling the RPC on the tree root (which is a Viewport with no script attached).

If you want to use both client and server in the same instance, have a look at: https://github.com/LudiDorici/gd-custom-multiplayer .
It provide an example to do just that, without the need of having 2 different trees.

**Comment by Faless** [comment]
Closing, this appears to be a logical error in the game, not the engine.
