### ISSUE TITLE
Add render completed signal to Viewport

### ISSUE THREAD

**Issue by wlodeqp** [godotengine/godot#31083]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Ubuntu 18.04.2 LTS

**Issue description:**
Is it possible to add signal "render_completed" or something similar to Viewport? It could be emitted only when we set update mode to UPDATE_ONCE.

For now I use something like this:

```
viewport.set_clear_mode(Viewport.CLEAR_MODE_ONLY_NEXT_FRAME)
viewport.set_update_mode(Viewport.UPDATE_ONCE)

yield(get_tree(), "idle_frame")
yield(get_tree(), "idle_frame")

viewport.get_texture()
```

but the texture is not always up to date and we can't really check if render is completed. `viewport.get_texture().get_data().is_empty()` and `viewport.get_texture().get_data().is_invisible()` only works when we use this viewport for the first time. For the next render, this methods indicate to previous texture.

**Comment by clayjohn** [comment]
Have you tried using the signal ``frame_post_draw()`` in the [VisualServer](http://docs.godotengine.org/en/latest/classes/class_visualserver.html#signals)?

I think it may do exactly what you want. I'm not sure, but it would be worth testing out.
```
VisualServer.connect("frame_post_draw", self, "_update_my_texture_please")
```

**Comment by wlodeqp** [comment]
Hello, thank you for your reply. I didn't use this signal. I will try it as soon as possible.

**Comment by wlodeqp** [comment]
I tested it and it works, but if I want reuse my viewports I still need wait after `viewport.get_texture()` (I have a viewport pool)

So my current code look like this:

```
func render() -> void:
	viewport.set_clear_mode(Viewport.CLEAR_MODE_ONLY_NEXT_FRAME)
	viewport.set_update_mode(Viewport.UPDATE_ONCE)

	yield(VisualServer, "frame_post_draw")
	yield(get_tree(), "idle_frame") #we need wait to emit signal 'on_ready', app freeze without this

	emit_signal("on_ready") #in this place I get texture

	#this two yields are required to proper reuse viewport
	yield(VisualServer, "frame_post_draw")
	yield(get_tree(), "idle_frame")
```

**Comment by clayjohn** [comment]
I'm procrastinating working on something else. So here is a working example of using Servers to set up a custom viewport to generate textures without having to render a full frame and wait.
https://gist.github.com/clayjohn/80d9b1e52e1b9a23445504e85a8d7890

**Comment by wlodeqp** [comment]
Thank you, this is very helpful. I did some tests and it works with my shaders. To set a shaders I use something like this:

```
#var sprite = load("res://icon.png")
#VisualServer.canvas_item_add_texture_rect(ci_rid, Rect2(Vector2(0, 0), sprite.get_size()), sprite)

var material = ShaderMaterial.new()
VisualServer.canvas_item_set_material(ci_rid, material.get_rid())
VisualServer.canvas_item_add_rect(ci_rid, Rect2(Vector2(0,0), viewport_size), Color.white)

material.set_shader(my_shader)
material.set_shader_param(...)
```
but this solution have some disadvantages, I didn't notice any performance improvements and it lag my main loop. I will test it more, but for my purposes I probably prefer previous solution.

**Comment by clayjohn** [comment]
@wlodeqp Its just an option, not a general purpose solution. Its a better option if you are generating the textures at load time, but it locks up your main loop, so its not a good idea to use for real-time generation. 

For generating textures on the fly, your previous method is going to avoid stalling the main thread, but you unfortunately are stuck having to wait a few idle frames to ensure that your texture has been generated before grabbing the data.

**Comment by wlodeqp** [comment]
This two solutions have some cons and pros, for my current project I prefer first one, but in a other project the second could be better.
You are right, using "frame_post_draw" is the same as my propose so I think we can close this issue. Or someone could add this to documentatio.
[https://docs.godotengine.org/en/3.1/tutorials/viewports/viewports.html#capture](url)

**Comment by clayjohn** [comment]
@wlodeqp I made an issue in the Godot docs rep a few days ago already to do just that :) https://github.com/godotengine/godot-docs/issues/2685

I am also going to make a tutorial on using viewports in the VisualServer. 

Thanks for the good suggetsion though! And good luck on your project!

**Comment by wlodeqp** [comment]
@clayjohn Thank you for your help

**Comment by Xrayez** [comment]
It would be nice if this could work per viewport. Indeed both methods seem to have pros and cons. The method which doesn't use signals has a major disadvantage in cases where you need to interact with an existing scene with nodes in them. Here's how I do it currently (similar to what @wlodeqp does):

```gdscript
func render():
	assert(is_inside_tree())

	$viewport.render_target_v_flip = true
	$viewport.render_target_update_mode = Viewport.UPDATE_ONCE

	var image

	var viewport_texture = $viewport.get_texture()
	yield(VisualServer, "frame_post_draw")
	image = viewport_texture.get_data()

	$viewport.render_target_v_flip = false

	emit_signal("rendered", image)
```
