### ISSUE TITLE
Building x11 tools fails on current master

### ISSUE THREAD

**Issue by est31** [godotengine/godot#3108]
As of current master (commit 020700af1d664c7b6e3b8b8d50a23e86286ef3dd) I get an error when trying to build godot. scons p=x11 gives the error:
```
platform/x11/joystick_linux.cpp:36:44: fatal error: libevdev-1.0/libevdev/libevdev.h: No such file or directory
compilation terminated.
```
git blame points to commit af633c794179d29a4bf0c01983c8b08d14553596 so most probably that's the faulty commit.

Note that I couldn't find version 1 of the evdev headers for my distro (kubuntu 15.10), only version 2.

**Comment by punto-** [comment]
Oh yeah the gamepad stuff adds a dependency to libevdev-dev. I tested it on
a pretty old Ubuntu (12.4) but the package seems to still be around (
http://packages.ubuntu.com/wily/i386/libevdev-dev/filelist), isn't it?
There was a second dependency, I don't remember it. We should note them and
update the building wiki page.

**Comment by est31** [comment]
Installing the libevdev-dev package did it.

**Comment by reduz** [comment]
Yes, but this code is wrong:

#include <libevdev-1.0/libevdev/libevdev.h>

we must do this correctly using pkg-config

**Comment by reduz** [comment]
fixed it. Next time please use pkg-config to add libraries, which is there
for a reason :)

**Comment by est31** [comment]
46dee92c8eb2eed4ed72e0b79670889eca5e1896 thanks

**Comment by reduz** [comment]
also as far as I know, there is libevdev for freebsd, so this should be
fine without checking linux platform

**Comment by Hinsbart** [comment]
Sorry for not doing this properly :/
And thanks for the hint on evdev being available on freebsd, I'll set up a VM and check it out.
It won't have hotplugging, as that depends on udev, but I think that's still better than no gamepad input at all.

Also, I _may_ have an opportunity to borrow a macbook, so I might be able to check out joystick support on osx. But I can't promise anything at this point.
