### ISSUE TITLE
init_library:  does not have a library for the current platform

### ISSUE THREAD

**Issue by HarryVolek** [godotengine/godot#31088]
**Godot version:**
Godot Engine v3.2.dev.custom_build.77e894768

**OS/device including version:**
Ubuntu 18.10 PC
Nvidia 2070

**Issue description:**
Trying to use nativescript gives error:
```
ERROR: init_library:  does not have a library for the current platform
   At: modules/gdnative/nativescript/nativescript.cpp:1503.
```

**Steps to reproduce:**
Following the guide here: https://github.com/GodotNativeTools/godot-cpp#compiling-the-cpp-bindings-library
I built the cpp bindings library with this command:
`scons platform=linux generate_bindings=yes use_llvm=yes`
I compiled the cpp file with the following two commands:
```
clang -fPIC -o src/start.os -c src/start.cpp -g -O3 -std=c++14 -Igodot-cpp/include -Igodot-cpp/include/core -Igodot-cpp/include/gen -Igodot-cpp/godot_headers
clang -o bin/libtest.so -shared src/start.os -Lgodot-cpp/bin -lgodot-cpp.linux.debug.64
```

Trying to load the nativescript file upon a button press in the example project posted below triggers the init_library error:
```
func _on_start_pressed():
	var startbutton = load("res://start.gdns").new()
	startbutton.test_void_method()
```

**Minimal reproduction project:**
[example.zip](https://github.com/godotengine/godot/files/3465509/example.zip)
Is there something I am missing? First time using Godot.

**Comment by akien-mga** [comment]
You `.gdns` NativeScript resource uses an empty GDNativeLibrary resource, not your `.gdnlib` file:
![Screenshot_20190805_094845](https://user-images.githubusercontent.com/4701338/62447715-47c2b280-b766-11e9-825d-5ea35b785e95.png)

See http://docs.godotengine.org/fr/latest/tutorials/plugins/gdnative/gdnative-c-example.html for up to date instructions on NativeScript usage.

**Comment by ryanpeach** [comment]
Hey I've got a very similar problem on my end but I don't quite understand this answer. This is my first gdnative script. Any advice?

https://godotengine.org/qa/85249/gdnative-script-not-doing-anything-when-attached-path2d-node

**Comment by akien-mga** [comment]
Updated the link for a stable one, and answered your question on the Q&A.

**Comment by ryanpeach** [comment]
Ok so it was just a master branch problem. Thanks.

I'm making ongoing PRs to the master branch that affect my game. I'll probably be done with them no sooner than 4.0 is released lol. So I'm probably just stuck there.
