### ISSUE TITLE
2D KinematicBody slides down slope with move_and_slide_with_snap

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot#31097]
**Godot version:** 3.1.1 Stable

**OS/device including version:** Manjaro Arch Linux (Linux 4.19.62-1 Kernel)

**Issue description:** When using the snapping feature of move_and_slide_with_snap it seems that there's some kind of artifact movement on slopes that occurs as a result of snapping. It does not happen when snapping is not used. Its not caused by the velocity of my 2D kinematic body directly, however it appears higher velocities of the body coming towards the slope (like gravity) does greatly effect the possibility of it happening. (beyond sliding) If stop_on_slope is false it appears to move faster but does not otherwise change the effect.

https://gfycat.com/klutzycorruptdeermouse

**Steps to reproduce:**
In a 2D platformer setup, while using move_and_slide_with_snap for movement, have the body snapped to a slope after falling.

**Minimal reproduction project:**
[snapping_testing.zip](https://github.com/godotengine/godot/files/3466446/snapping_testing.zip)

**Comment by Spartan322** [comment]
It's definitely caused by the application of the collider's `travel` variable eventually getting applied to the global transform starting [here](https://github.com/godotengine/godot/blob/8743da90d964f7b9110f6e3578fba30ac810f6ac/scene/2d/physics_body_2d.cpp#L1337), the best I could do to remove any visible aspect of it was rounding `travel` or steppifying it. I am still unaware of what the root cause is specifically.

**Comment by akien-mga** [comment]
CC @madmiraal

**Comment by madmiraal** [comment]
This is actually a problem with `move_and_collide()` that is used by `move_and_slide_with_snap()`; so it's the 2D version of #18433, which was identified by @xphere ([comment](https://github.com/godotengine/godot/issues/18433#issuecomment-396372868)), but unfortunately, unlike the 3D version, it is not solved with #35945.
