### ISSUE TITLE
Option Button Popup is displaced

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31098]
**Godot version:**

3.1

**Issue description:**

Moving an Options Button displaced the Popup that appears once you click it. The displacement becomes more severe the further the button is moved from _an arbitrary, yet fixed_ point.

**Steps to reproduce:**
Create an Option Button, implement the ability to move it by dragging. Observe how the popup begins appearing in increasingly wrong locations.

In my case the button is contained within a panel container which implements the drag movement.

```
func _gui_input(event: InputEvent) -> void:
	if event is InputEventMouseMotion:
		if Input.is_mouse_button_pressed(BUTTON_LEFT):
			rect_position += event.relative
```

**Comment by sparkart** [comment]
It intentionally displaces the dropdown menu to keep it inscreen.

**Comment by TheDuriel** [comment]
![image](https://user-images.githubusercontent.com/44248915/62788252-d026b780-bac6-11e9-9318-f07a45b407db.png)

![image](https://user-images.githubusercontent.com/44248915/62788272-d9178900-bac6-11e9-9d3b-0f3cc82493c4.png)

![image](https://user-images.githubusercontent.com/44248915/62788306-e92f6880-bac6-11e9-8cb6-952573245ff2.png)

(Bottom left coord is the camera position, aka the white rectangle.)

**Comment by sparkart** [comment]
Where's your viewport?

**Comment by TheDuriel** [comment]
Its filling the entire screen for testing.
