### ISSUE TITLE
changing node type wipes its connections

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#311]
If you change a node type in a scene, any connections it has (set with the connections editor tool) are erased. I think it should retain the connections.

Example: Connect a button's pressed event to a parent EmptyControl (or whatever) node, then change the parent's type to Control (or whatever), and the connection is now gone.

**Comment by kubecz3k** [comment]
From my tests it looks like the connections are now saved if it's possible (new type needs to have this signal). If I misunderstood something then please open new one.
