### ISSUE TITLE
LineEdit command history

### ISSUE THREAD

**Issue by rxlecky** [godotengine/godot#31101]
I am currently working on expression evaluator for Godot debugger and I implemented a command history feature that is present pretty much in any console type of application. For those who aren't sure what I have in mind, when you enter the command in the console, I store it in history that I can browse later, in my case pressing up and down arrow keys, user can get back to previously entered commands.

I implemented this as a custom Control for the tool only. However, I wanted to ask whether this would be feature that other users would find useful too. If yes, I could move this to LineEdit.

**Comment by SeleckyErik** [comment]
![2019-08-05_11-21-00](https://user-images.githubusercontent.com/35656626/62453720-30d68d00-b773-11e9-9cee-ef87388f3f89.gif)
_Illustration of current usage_

**Comment by KoBeWi** [comment]
If you coded an already working feature, it would be probably better to create a PR, not an issue. Whether we need it also depends on how complex code it introduces. (feature-alone, looks useful to me, e.g. for chats)

**Comment by groud** [comment]
I don't think this will be merged, the use case is too specific and is not needed in the editor.

**Comment by SeleckyErik** [comment]
@KoBeWi I implemented the feature as a custom `Control` node, not in the `LineEdit`. Moreover, I implemented it specifivally for my usecase, so I did not implement full generic API for it, only what I needed. Talking to Juan, he suggested opening an issue for this.

**Comment by SeleckyErik** [comment]
@groud Well, it is used in the editor now - it will be, better said. 😀 But I agree that the use case is quite specific. That's why I opened this issue, to see opinion of other users and contributors.

**Comment by girng** [comment]
this is why gdscript exists! the power of gdscript interweaves with ui nodes at full force in this thread! great work!
