### ISSUE TITLE
Tuxfamily download link for Godot is not working

### ISSUE THREAD

**Issue by mrmoon117** [godotengine/godot#31104]
Hey, I have been trying to download Godot from Godot website, it the server on which Godot engine is hosted seems to be broken. Also, down below there is also a link for itch.io, but I am wandering is that one an official download link? Should I use that one?

**Comment by akien-mga** [comment]
The links on https://godotengine.org/download seem to work fine for me, could you be more specific on what link is not working?

**Comment by mrmoon117** [comment]
> 
> 
> The links on https://godotengine.org/download seem to work fine for me, could you be more specific on what link is not working?

Actually, there is no problem with godotengine link. Tuxfamily link seems to be download.

**Comment by akien-mga** [comment]
This link has buttons to download files from TuxFamily. Those buttons work fine.

I still need to know what URL does not work for you.

**Comment by mrmoon117** [comment]
https://downloads.tuxfamily.org/godotengine/3.1.1/mono/Godot_v3.1.1-stable_mono_win64.zip
https://downloads.tuxfamily.org/godotengine/3.1.1/mono/Godot_v3.1.1-stable_mono_win32.zip
https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_win64.exe.zip
https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_win32.exe.zip

Non of the links above are working for me.

**Comment by akien-mga** [comment]
Thanks. I can't reproduce the issue myself but I'm trying to see with our server admins what the problem could be.

Could you send my your IP address by email? At: remi at godotengine · org
You can find it e.g. by visiting https://whatismyipaddress.com/

> Also, down below there is also a link for itch.io, but I am wandering is that one an official download link? Should I use that one?

In the meantime you can use itch.io to install Godot yes, it's the same version. But I'd also like to debug further to find out what the issue is, and ideally solve it.

**Comment by Zireael07** [comment]
Hmm, I had issues once on a very very shitty connection (think modem speeds). Alternately, could be some sort of a country block? Where are you in, @mrmoon117, and what is your connection?

**Comment by mrmoon117** [comment]
> 
> 
> Hmm, I had issues once on a very very shitty connection (think modem speeds). Alternately, could be some sort of a country block? Where are you in, @mrmoon117, and what is your connection?

I am from Bangladesh. I don't know whether tux family is blocked Bangladesh or not

**Comment by mrmoon117** [comment]
Sorry for bothering. The links are fine. I tried to download Godot from a different computer using the same network. Everything was fine. I think something is wrong on my side.

Sorry once again.

**Comment by eNzr** [comment]
the link to http://downloads.tuxfamily.org does work for me neither
server not reachable
but a can reach http://download.tuxfamily.org (without a s at download
is it safe ?Iis it the new one ?

**Comment by Calinou** [comment]
@eNzr The HTTPS link works for me here. In any case, feel free to use this mirror hosted by yours truly: https://archive.hugo.pro/godot-tuxfamily/
