### ISSUE TITLE
Android Animation Texture Abnormality

### ISSUE THREAD

**Issue by 316902108** [godotengine/godot#31110]
Dear Godot creator, I hope I can get your help.

I am a Chinese. I like the Godot engine very much. It's very good.
These questions puzzled me for a long time

Why does animation texture abnormal on Android?
It's normal on the window desktop.

My project is over 10M and cannot be uploaded. Please provide your mail and I will send you the project file.

![Abnormal1](https://user-images.githubusercontent.com/48303560/62476169-fd592a00-b795-11e9-985e-da916c950153.jpg)
![Abnormal2](https://user-images.githubusercontent.com/48303560/62476172-fdf1c080-b795-11e9-801e-e82721eba8f2.jpg)
![Natural1](https://user-images.githubusercontent.com/48303560/62476175-ff22ed80-b795-11e9-9d26-69e7fc959e4a.png)
![Natural2](https://user-images.githubusercontent.com/48303560/62476182-01854780-b796-11e9-8ccd-be95c9f9d3b0.png)

**Comment by Calinou** [comment]
What's the size (in pixels) of the animated textures? Most Android devices don't support displaying textures larger than 4096×4096.

**Comment by akien-mga** [comment]
Are you using GLES2 or GLES3?

If you use GLES2 and ETC (ETC1) compression for Android, I think it doesn't support transparency. So you might need to use lossless compression for transparent textures.

**Comment by 316902108** [comment]
I have tried all kinds of compression modes, 
I will send you my project, hope to get your help, 
thank you very much for answering my question!
  	
 	 		  			从QQ邮箱发来的超大附件 		 	
 	 		  	 	 		 			 		
 		 			 Project.zip (71.52M, 2019年9月5日 08:05 到期) 			 			 				进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=233663329eafb3cbbdbc80201532061f54545604500b00564c055a50061f0004540e4e53000b041d5402510b0b07510759015206333934601359095750461a4a0846630f4765&t=exs_ftn_download&code=a6c23240 			
 		
 	
 
  	 	 		 			 		
 		 			 APK.zip (54.91M, 2019年9月5日 08:05 到期) 			 			 				进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0b6432647f1ca1cfe9eed1764463021c5105530101575302185d5701554e040351051f065005091e575102055050050554070a0762643072652f1c1e0b13300e4133&t=exs_ftn_download&code=5d2dbc03

**Comment by volzhs** [comment]
`res://ZiYuan/Role/Man/CLJ/Q_Stand.png`
this file dimension(7440x263) is too big for mobile.
try to make it under 4096x4096

**Comment by 316902108** [comment]
But this animation is normal(Q_Stand).

I don't think it's because of pixel size.



 
---Original---

**Comment by volzhs** [comment]
what do you mean **normal**?

**Comment by volzhs** [comment]
pixel size is matter.
https://www.google.com/search?q=android+exture+size+limit

**Comment by volzhs** [comment]
@akien-mga is it bettter to show warning message when exporting android if texture dimension is over 4096x4096?

**Comment by akien-mga** [comment]
> is it bettter to show warning message when exporting android if texture dimension is over 4096x4096?

Probably yes, or even a blocking error.

**Comment by 316902108** [comment]
> @akien-mga is it bettter to show warning message when exporting android if texture dimension is over 4096x4096?



> > is it bettter to show warning message when exporting android if texture dimension is over 4096x4096?
> 
> Probably yes, or even a blocking error.

Probably yes
Texture greater than 4096x4096 export, no error

**Comment by Zireael07** [comment]
@316902108 Yes, your problem is because the texture is too big. They are discussing adding an error in the future if the textures are so big

**Comment by 316902108** [comment]
> @316902108 Yes, your problem is because the texture is too big. They are discussing adding an error in the future if the textures are so big



> > is it bettter to show warning message when exporting android if texture dimension is over 4096x4096?
> 
> Probably yes, or even a blocking error.



> @akien-mga is it bettter to show warning message when exporting android if texture dimension is over 4096x4096?



> What's the size (in pixels) of the animated textures? Most Android devices don't support displaying textures larger than 4096×4096.
> 
> > My project is over 10M and cannot be uploaded. Please provide your mail and I will send you the project file.
> 
> You could upload it on [Transfer.sh](https://transfer.sh/). The link will only be valid for 14 days, but it might be sufficient to troubleshoot the issue 🙂
> 
> Also, I think GitHub allows uploading files up to 50 MB, but that may have changed recently.

Thank you all very much.
Thank you for your dedication to Godot

When I narrowed one of the textures, the problem was solved.
I'm sorry to have caused you trouble.
In the future, I will control the texture in (4096X4096)

I often broadcasted on large live platforms in China (similar to YouToBe)
Doing Godot Teaching and Publicity

If my project makes any profit, I will donate at least 10% or more to Godot.
Godot enthusiasts are increasing in China
I hope Godot can support Chinese language better.

**Comment by volzhs** [comment]
I made a new issue about checking texture dimension when exporting for mobile. #31414
@akien-mga @316902108 can this be closed now?
