### ISSUE TITLE
Animated 3D Mesh’s arm looks weird in GLES2 on my old laptop.

### ISSUE THREAD

**Issue by sdhy** [godotengine/godot#31126]
Screenshots (read below for details):

What it looks like when I import a Better-Collada animated mesh from Blender:
![Anim test BAD - Godot 3 1 1 GLES2 Windows 7](https://user-images.githubusercontent.com/21011280/62712591-21508180-b9c9-11e9-9072-230cdbe31afd.png)
^i.e. Bad.
.
.

What it's supposed to look like:
![Anim test GOOD - Godot 3 1 1 GLES2 iMac](https://user-images.githubusercontent.com/21011280/62712631-34635180-b9c9-11e9-9636-26eed5ee2175.png)
.
.
.

If you need any more information, please don’t hesitate to ask.

P.S. Will updating to Windows 10 or using the newly released Blender 2.80 help???
P.P.S. How do I add tags to this post?

**Godot version:**
Godot 3.1.1 Stable.
Blender 2.79b
Better Collada (downloaded on July 12, 2019 from Godot website).

**OS/device including version:**
Laptop specs:
TOSHIBA Satellite C670
Microsoft Windows 7 Home Premium (64-bit)
Intel® Core™ i3 CPU M 370 @ 2.40GHz
 Intel® HD Graphics
EDIT: Everything is up to date according to Windows Update and Intel Driver & Support Assistant. 
More details on computer specs are in the zip file.

**Issue description:**
I animated a 3D character-mesh in Blender 2.79 (using a better iMac). 
I exported using Better Collada.

I imported it into Godot (on an older Windows 7 laptop).
But the character's arm stretches in a weird way. Both arms should look the same in a t-pose.

This only happens on my old windows 7 laptop, and not on my not-as-old iMac.

Un-parenting the mesh from the rig makes the mesh look normal, but then it's no longer animated.

_P.S. my windows laptop this error message whenever I turn it on, but it seems irrelevant (i.e. LAN). But just in case, here it is:_

_Realtek PCIe FE Family Controller Series v1.24 (10/07/10)_
_PXE-E61: Media test failure, check cable_

_PXE-M0F:  Exiting PXE ROM._

	
_Otherwise, my computer works fine, albeit it can be very slow, especially with Godot._

**Steps to reproduce:**
Rig and animate a mesh in Blender 2.79
Export using Better Collada with the “All Animations” and “Actions” checkboxes checked.

Then do one of two things:
1) Using a laptop with similar specs(?), import the .dae file into any Godot project with GLES2. Test run any game scene with the mesh.

Or:

2) EDIT: Use a better-end computer to export a windows game and run it on an old laptop like my old Windows laptop.

**Minimal reproduction project:**
[3DGodot3.1.1GLES2 Windows7forGithub.zip](https://github.com/godotengine/godot/files/3469779/3DGodot3.1.1GLES2.Windows7forGithub.zip)

**Comment by MightyPrinny** [comment]
I can confirm that mesh deformations might look wrong on old laptops, I encountered a similar problem on an old laptop with an i5 m540 with an integrated iron lake gpu, but graphic acceleration on that laptop was terrible so I thought it was the driver's fault.

**Comment by sdhy** [comment]
@MightyPrinny for me, only DirectionalLight seems to work in Godot on my old laptop. The other lights don't do anything afaik.

**Comment by sdhy** [comment]
Using Lubuntu OS fixes the problem! I burned Lubuntu to a USB drive and ran it from the USB drive. The arm looks normal, now! :)

Here's the link to Lubuntu:
https://lubuntu.net/downloads/

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.
