### ISSUE TITLE
Suggestion on adding a "back to top" link to in-editor docs.

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#31139]
(Just to avoid potential confusion: this pertains to documentation inside the editor, only.)

When I click a method name in a doc page, it takes me down to where the method is documented, but then I have to scroll all the way back to the top, click another method, repeat. Usually I go back to the top mostly because it's easier to find methods there. So it tends to get a bit unwieldy...

So my suggestion is to add a little link to the top, right next to each method's documentation. 

In the case of properties, constants, etc, I suppose it would be overkill to have that next to each and every one of them, but perhaps they could have it next to the section headers.

---

EDIT: well, pressing Home works. But still...

**Comment by KoBeWi** [comment]
> So my suggestion is to add a little link to the top, right next to each method's documentation.

A dedicated button somewhere at the edge would be better IMO. Some methods have really short descriptions and "back to top" everywhere would create a lot of clutter.

#16554 for docs would work too.

**Comment by Skaruts** [comment]
I should've specified what I was thinking, but I was a little divided. One of the things I was thinking was a little up-arrow button kind of thing. That wouldn't add much clutter. I do agree a link saying `back to top` would be a bit too much.

But I'm ok with whatever you guys think is more appropriate.

**Comment by Calinou** [comment]
Since we already have a scrollbar and the <kbd>Home</kbd> button, is there much point in adding a "back to top" button? Such buttons are generally considered to be antipatterns nowadays.

**Comment by Skaruts** [comment]
@Calinou 
Sorry for late reply. 

What do you mean by `Home` button? You mean the `Home` key on the keyboard, or some button that's been added in godot? (I don't see that in 3.2.1.) 

Anyway, I just realized the buttons in the method list on the left side actually solve my problem, and pretty much do what I was suggesting in my first post. :) So I think this issue can be closed.
