### ISSUE TITLE
AnimationTreeStateMachine priority is broken

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#31132]
When running a state machine with two paths of different priority, it will always pick the same path regardless of the value:

![imagen](https://user-images.githubusercontent.com/3101690/62514138-83b94e80-b81e-11e9-9a86-ecbdc3120a65.png)

What this means is, regardless of what priority I set, it will always go through jump 2 in the above example.

Tested on 7126654ea

**Comment by pouleyKetchoupp** [comment]
Are you by any chance trying to set a higher priority value on the jump transition? Priority works the other way around, you need to set a lower value for the transition to be made instead of the other one.

Otherwise, can you share a project to reproduce the issue?

**Comment by ElGatoNinja** [comment]
I had this bug, and yesterday I looked at the implementation in the engine because I couldn't understand how this thing works.
First the engine seems to use not only the priority but the length of the transition arrow for some reason.

When I tried to jump, from run, it first turned to left -> idle ->start_run -> jump (instead of just, jump) I solved it deleting jump, and creating an exactly equal node connected in the same way.

I've also tried to disable some of the transitions, but It doesn't work neither. Looking in the engine it is not even implemented yet, It is in the AnimatedNodeStateMachineTransition but it is not used in the AnimatedNodeStateMachinePlayback::_travel() function

**Comment by EIREXE** [comment]
> 
> 
> Are you by any chance trying to set a higher priority value on the jump transition? Priority works the other way around, you need to set a lower value for the transition to be made instead of the other one.
> 
> Otherwise, can you share a project to reproduce the issue?

I tried both ways, I will provide a test project, give me a minute, I'm on a very slow connection so i'll have to strip most data out of it to make it minimal.

**Comment by EIREXE** [comment]
https://files.catbox.moe/coax8q.7z

open up characters -> player.tscn

**Comment by pouleyKetchoupp** [comment]
@EIREXE Thanks for the test project!

Can you share some details about your repro? I've tested on my end by setting both transitions to "auto-advance" and I've added a transition with "auto-advance" from idle-loop to idle. When I play idle, it does transition to the priority 0 state.

I'm not sure if it's the way you trigger the transition that's different from me, or possibly a different issue, but it would be a good start to make sure we're testing the exact same things step by step :)

**Comment by pouleyKetchoupp** [comment]
@ElGatoNinja After fixing priorities I can confirm the actual distance between nodes is taken into account to prioritize the path. I'm not sure why it has been implemented this way. If it's causing problems for you, I would suggest to open a separate issue about that specifically, so maybe you can at least get an option to disable it.
Same thing with disabling transitions, creating a separate issue would be nice.

**Comment by EIREXE** [comment]
> 
> 
> @EIREXE Thanks for the test project!
> 
> Can you share some details about your repro? I've tested on my end by setting both transitions to "auto-advance" and I've added a transition with "auto-advance" from idle-loop to idle. When I play idle, it does transition to the priority 0 state.
> 
> I'm not sure if it's the way you trigger the transition that's different from me, or possibly a different issue, but it would be a good start to make sure we're testing the exact same things step by step :)
> 
> **edit**: ok, I've tested with travel instead and I've found the bug. I'm going to make a PR soon.

Yes I clicked the play buttons, which Iassume is the same as travel.
