### ISSUE TITLE
Godot acts weird when scale of a mesh is near 0.

### ISSUE THREAD

**Issue by Skipperro** [godotengine/godot#31134]
**Godot version:**
3.1.1

**OS/device including version:**
Tested on Linux Mint 19.1 but should apply to all.

**Issue description:**
When a MeshInstance have a scale of 0 or near it, like 0.0001, one of two things can happen:
- Console will spam weird errors about `something() == 0`.
- If Mesh is part of the AnimationPlayer, performance of the game will slowly drop to about 5% of the FPS count at start, after about 1 minute.

**Steps to reproduce:**
Create a mesh and force it scale to 0. Preferably by AnimationPlayer.
You could also download this model and play it's "Idle" animation, as unused weapons are scaled to 0 here:
https://sketchfab.com/3d-models/low-poly-character-rpg-kit-animation-904c06fc53574534a3aace8dba79f796

**Comment by Zireael07** [comment]
Mesh scale of 0 is a bad idea, generally. Console errors are because the physics engine cannot handle that.

**Comment by Skipperro** [comment]
Yes, it is a bad idea, but it happens and some models, like the one I've linked are setting it in their animations. Unity and UE4 handles such a scenario without errors, so there should be some check in Godot too, like if scale is 0, then don't even bother calculating the rest.

**Comment by gdesecrate** [comment]
Sorry, why it is about physics when it is about rendering?

**Comment by Calinou** [comment]
Closing in favor of #40059, as that issue has more information about the problem at hand.
