### ISSUE TITLE
Camera2D margins don't consider calculations for rotated or zoomed camera

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3114]
This is related to #1912 
The camera2D does not consider the rotation when checking the margins.

Here's a test project: https://dl.dropboxusercontent.com/u/274954519/godot-issues/camera-bug.zip
Move the camera using the arrow keys and the R key for rotation.
When the scale is not 1, 1 the margins dont work. The same happens when the rotation is different than 0.

**Comment by reduz** [comment]
I have no idea how to consider the margins when rotating, but here is the camera code in case anyone wants to give it a try or propose a way this should work, it's a single function that does the margin checks: 

https://github.com/godotengine/godot/blob/master/scene/2d/camera_2d.cpp#L71

**Comment by kubecz3k** [comment]
Since reduz showed what code is responsible for this -> in perfect world this bug would be solved by contribution. Will add 'junior job' tag to give a hint for contributors.

**Comment by reduz** [comment]
I still have my doubt whether this is a bug, I can' t think of a "right" behavior when using rotation+margins

**Comment by FEDE0D** [comment]
I thought about this for a while. The zoom could be changed to fit the margins inside the screen.
Thats what I made for my game. But it was a bit annoying (specially on margins with an aspect other than 1:1) so I always keep the zoom the same. Maybe an option for turning that on/off would work fine.

**Comment by reduz** [comment]
yes that's what I mean, I think margin is not really meant to be used together with rotation, it' s better to just code your own limiting code yourself at this point

**Comment by reduz** [comment]
after some dicussion i'm closing this, it's not clear there is an obvious way to make this work in a way that everyone is satisfied, or that is standard.
