### ISSUE TITLE
Transpose in TileMap doesn't have a button

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31149]
**Godot version:**
3.1.1

**Issue description:**
If you look at the editor shortcuts, you might notice a mysterious one called "Transpose". It's fully functional and even has a dedicated variable in tiles, but if the shortcut was hard-coded, there would be no way of knowing it even exists, because it doesn't appear in any menu. It should probably have a button, like the rotation and mirroring.

**Comment by akien-mga** [comment]
IIRC the button was removed on purpose? CC @groud

**Comment by groud** [comment]
Yes, that's an expected change. Rotating and flipping tiles is modifying a combination of the three booleans transpose, flip H, flip H. They are now internal and should not be exposed.

So the shortcut should be remoced too, and maybe be replaced by the rotate left/right and flip h/v. Though I am surprised this one still exist, maybe it's is still in your configuration file but not in the code anymore (that happens).
To be verified.

**Comment by erictuvesson** [comment]
The `transpose` shortcut doesn't do anything noticeable on `master`. (It does still exist)

I notice that the flag is referenced a lot in the code, I am not sure if it does something in the background. It's not the easiest code to follow along. 😅

**Comment by KoBeWi** [comment]
The shortcut still works on master, but rotating tiles is bugged, so the effect is not clearly visible.

**Comment by groud** [comment]
> The shortcut still works on master, but rotating tiles is bugged, so the effect is not clearly visible.

I have just realized that, internally, the transposition does not work anymore. Likely due to an update in the rendering code I suppose.

**Comment by groud** [comment]
Closing as this is an enhancement request not needed anymore on master. The bug we talked about is still to be fixed though.
