### ISSUE TITLE
Error -127 is outside the range of representable values of type 'unsigned char' in visual_server.cpp

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#31140]
**Godot version:**
3.2.dev.custom_build 7126654ea

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
logs
```
servers/visual_server.cpp:514:17: runtime error: -127 is outside the range of representable values of type 'unsigned char'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior servers/visual_server.cpp:514:17 in 
servers/visual_server.cpp:515:17: runtime error: -12.4482 is outside the range of representable values of type 'unsigned char'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior servers/visual_server.cpp:515:17 in 
servers/visual_server.cpp:513:17: runtime error: -2.42852 is outside the range of representable values of type 'unsigned char'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior servers/visual_server.cpp:513:17 in 
```
This code
https://github.com/godotengine/godot/blob/4188b0c139dc71b425528db97afdc1e54c2fb5b4/servers/visual_server.cpp#L512-L517
should probably look like a little above(uint_8 -> int_8)
https://github.com/godotengine/godot/blob/4188b0c139dc71b425528db97afdc1e54c2fb5b4/servers/visual_server.cpp#L477-L482
or clamp should have this values CLAMP(value,0,255)

**Comment by sparkart** [comment]
I think it should be signed int. Line 512 was most likely a typo and then the following casts in lines 513-516 were added afterwards https://github.com/sparkart/godot/commit/e2b50e1abbc6cab58410a2ef4155bdcadf73efcf#diff-23cec7725ea48162a903e4160145a2ceR482

That's my guess.
