### ISSUE TITLE
Shift + F3 doesn't work in the built-in docs

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31147]
**Godot version:**
3.1.1

**Issue description:**
When you search something in the documentation, you can use F3, but Shift + F3 (search previous) doesn't work.

**Steps to reproduce:**
1. Open some doc in the editor
2. Search something
3. Press F3
4. Press Shift + F3
5. Press Shift + F3 again, just to be sure

**Comment by sparkart** [comment]
The Docs seem to be opened by a "ScriptEditor", which doesn't appear to have a shortcut key for  Find Previous. GDScripts, seem to be opened by "ScriptTextEditor", which has a shortcut key for both Find Next and Find Previous. I'm not sure if this is true as I haven't looked at the source, just came to the conclusion by looking at the shortcuts in Editor Settings.

Is there a reason for Script Editor and Script Text Editor? I feel like Script Editor is old as even the file menu is different between the editor for docs and scripts. Also, when you press CTR + F to search, the search bar in the docs looks more primitive then the search bar for scripts.
