### ISSUE TITLE
Replace in files have no shortcut

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31146]
**Godot version:**
3.1.1

**Issue description:**
We already have Ctrl + Shift + F to find in files, but replace in files is missing a shortcut. Usually in editors Ctrl + H is for replace and Ctrl + Shift + H is for replace in files, as equivalent for F stuff.

**Comment by Calinou** [comment]
We currently use <kbd>Ctrl + R</kbd> to replace in the script editor, so replacing files would be triggered by pressing <kbd>Ctrl + Shift + R</kbd>.

**Comment by zayngdev** [comment]
Now, Ctrl + Alt + F is the shortcut.

**Comment by dreamsComeTrue** [comment]
> 
> 
> Now, Ctrl + Alt + F is the shortcut.

That is 'Go To Function' shortcut actually

**Comment by Calinou** [comment]
Since we don't have a dedicated "Replace in Files" dialog (just a Find in Files menu that can do both finding and replacing), should we just make <kbd>Ctrl + Shift + R</kbd> bring up the Find in Files dialog?

**Comment by dreamsComeTrue** [comment]
I am already working on that PR, stay put :)

**Comment by KoBeWi** [comment]
> Since we don't have a dedicated "Replace in Files" dialog (just a Find in Files menu that can do both finding and replacing)

Eh, I actually didn't consider that when creating this issue. It makes no sense to make a double shortcut.

**Comment by akien-mga** [comment]
Fixed by #36044.
