### ISSUE TITLE
Add FuncRef.callv( Array arg_array ) method

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#31143]
**Godot version:**
3.1.1.stable.official

**Issue description:**
To call a function using `FuncRef.call_func( ... )`, you need to know in advance how many arguments it takes.

Although the `Object` class has two separate methods (`Object.call` and `Object.callv`).

`Object.call( String method, ... )`
`Object.callv( String method, Array arg_array )`

**Comment by bojidar-bg** [comment]
Note that you can already do `func_ref.callv("call_func", [...])`, since `func_ref` inherits `Object`.

**Comment by dalexeev** [comment]
@bojidar-bg
> you can already do `func_ref.callv("call_func", [...])`

This makes no sense because it will call a method of `func_ref` itself.

So far, I replaced in my code `funcref(obj, 'my_func')` with `[obj, 'my_func']`.
Used as follows: `ref[0].callv(ref[1], args_arr)`.

Thank you for your PR.

**Comment by bojidar-bg** [comment]
> This makes no sense because it will call a method of func_ref itself.

Which method is a vararg method.

Seriously, try it! All of the following lines do the same thing:
```gdscript
var f = funcref(obj, "method")

obj.method(1, 2, 3)
obj.call("method", 1, 2, 3)
obj.callv("method", [1, 2, 3])
obj.callv("call", ["method", 1, 2, 3])

f.call_func(1, 2, 3)
f.call("call_func", 1, 2, 3)
f.callv("call_func", [1, 2, 3])
f.callv("call", ["call_func", 1, 2, 3])
# With the PR:
f.call_funcv([1, 2, 3])
```

**Comment by dalexeev** [comment]
```gdscript
f.callv("call_func", [1, 2, 3]) # okay, basically fine
f.callv("call", ["call_func", 1, 2, 3]) # WHAT A NIGHTMARE
```

P.S. JavaScript is the best:
```javascript
f.call_func(...[1, 2, 3])
```

**Comment by akien-mga** [comment]
Reopening, the issue is not fixed yet.
