### ISSUE TITLE
KinematicCollision.get_local_shape() always returns the KinematicBody's first CollisionShape

### ISSUE THREAD

**Issue by idi0tf0wl** [godotengine/godot#31144]
**Godot version:**
3.1.1

**OS/device including version:**
macOS 10.14.5

**Issue description:**
KinematicCollisions returned by KinematicBody.move_and_collide or get_slide_collision will always return the acting KinematicBody's first CollisionShape as the local_shape, even if that CollisionShape is disabled, sizeless, or otherwise incapable of colliding with anything.

**Steps to reproduce:**
Create a KinematicBody with two CollisionShapes, disabling the one which is first in the child node hierarchy or, alternatively, arranging them such that only one could collide with your chosen target.

Move the KinematicBody to collide with the target via a method of your choice.

Get the local_shape of the KinematicCollision. It will invariably be the first CollisionShape in the KinematicBody's child node hierarchy.

**Comment by Tegu** [comment]
I was able to reproduce the issue with Godot 3.1.1 on 64-bit Windows 10 (version 1903). The attachment has a small test project that demonstrates the problem.

[KinematicCollisionLocalShape.zip](https://github.com/godotengine/godot/files/3474261/KinematicCollisionLocalShape.zip)

**Comment by raphael10241024** [comment]
GodotPhysic is fine, happens only in bullet physics.

**Comment by bojidar-bg** [comment]
CC @AndreaCatania

**Comment by r0401** [comment]
This exact issue Appears again in Godot 4, I Tested in Godot 4.0.1.stable and 4.1.stable and both got the same issue
