### ISSUE TITLE
Constants in the inspector no longer work

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31155]
**Godot version:**
3.1.1

**Issue description:**
This worked in 3.0, but doesn't work since 3.1. Basically, you could e.g. write `KEY_ENTER` in a field in the inspector and it would be properly replaced as 16777221. It was very useful for creating shortcuts. Doing this in 3.1 has no effect at all.

**Comment by akien-mga** [comment]
Some constants like `PI` or `INF` work though, they're handled specifically in `core/math/expression.cpp`.

The pre-3.1 "evaluator" system was actually [generating and running GDScript](https://github.com/godotengine/godot/blob/3.0/editor/property_editor.cpp#L4659-L4690) to do this, while the new `Expression` class has its own parser for basic math and property access.

**Comment by KoBeWi** [comment]
Still valid in 2d9b409

**Comment by KoBeWi** [comment]
Setting shortcuts was overhauled, so this is no longer important.
