### ISSUE TITLE
CPUParticles don't have a gizmo icon

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31152]
**Godot version:**
3.1.1

**Issue description:**
Particles have a nice icon in 3D that show where they are
![image](https://user-images.githubusercontent.com/2223172/62563756-f872a400-b883-11e9-823b-20ad06f68f5b.png)
But CPUParticles don't have one. It's not really important, but it bothered me when I converted to CPUParticles and the icon disappeared.

**Comment by clayjohn** [comment]
Also mentioned in https://github.com/godotengine/godot/issues/29692

Maybe we should start a tracker for 3D Particles and CPUParticles.

**Comment by KoBeWi** [comment]
That's just one issue so far, so not worth of making a tracker yet.

**Comment by akien-mga** [comment]
@clayjohn #29692 is meant for all four nodes.

**Comment by creikey** [comment]
In my PR I use the same icon for CPUParticles as normal particles, I could change it to the custom cpuparticles icon if needed.

**Comment by creikey** [comment]
I've added a new custom icon approved by Calinou
