### ISSUE TITLE
Editor closing after running project (but project runs after that - editor closed)

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#31158]
**Godot version:**
Godot_v3.1.1-stable_mono_win64.exe

**OS/device including version:**
Windows 7

**Issue description:**
On running application the editor is closing automaticly, and the project is starting.

![crashGodotCSharp5](https://user-images.githubusercontent.com/2394124/62571516-d7b14b00-b891-11e9-9259-a7680d19bf23.png)

**Steps to reproduce:**
1) Make a change in one script (new line or something - dont change code!).
2) Run the project
3*) Maybe you have to do this twice or more times
-> Crash

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/3473879/project.zip)

--------------------------------

I think it has todo something with the Label-Node. The accessing. Without delegating it doesn't crash i think.

And with 
`CustomClass customClass = GetNode(path) as CustomClass ;`
instead of
`CustomClass customClass = GetNode<CustomClass>(path);`

I think its not crashing at all.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.
