### ISSUE TITLE
Inconsistency with _ in virtual methods

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31151]
**Godot version:**
3.1.1

**Issue description:**
Virtual methods are (probably) supposed to start with _, like `_process()`, `_draw()` etc. However, I recently noticed that some virtual methods don't start with _, e.g. `has_point()` in Control class, which already caused some confusion (#18540).

Are all virtual methods supposed to start with _? If so, some existing ones should be renamed.

**Comment by neikeq** [comment]
Looks like a duplicate of #19209

**Comment by KoBeWi** [comment]
The other issue is about whether the underscores should exist at all. Yeah, it touched the consistency in the end, but it's not exactly the same.

**Comment by neikeq** [comment]
No, the other issue was about inconsistency in the first play. Whether underscore should be used at all was mentioned later.

**Comment by KoBeWi** [comment]
Eh, ok :/
