### ISSUE TITLE
Project Manager doesn't remember sorting option

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31150]
**Godot version:**
52cfb5f

**Issue description:**
Not sure if it wasn't always like this, but when you change the sorting option in the manager and exit the editor, it will be reverted back to "Name" on another launch. Moreover, when you manually change the sorting in Editor Settings, it will be ok when running Project Manager, but will revert again when running editor.

This actually seems to be similar to #24303, except it was fixed and now it isn't again.

**Comment by akien-mga** [comment]
Might have broken in the #30735 refactoring? CC @Zylann

**Comment by Zylann** [comment]
Yup that would be me. Need to initialize it properly (but without triggering a re-save).
