### ISSUE TITLE
Keyboard repeat lag on GNOME

### ISSUE THREAD

**Issue by kkga** [godotengine/godot#31177]
**Godot version:**
3.1.1 stable, also happens on 3.2 dev

**OS/device including version:**
OS: Linux, Fedora 30, GNOME 3.32.2
GPU: Intel UHD 620

**Issue description:**
When using the script editor on GNOME desktop, the response to keyboard repeat is “lagging”.
It’s difficult to illustrate with a GIF, but simply put: if you hold a key (e.g. arrow down to scroll) and then release it, the release triggers not immediately but after a certain lag.
Response to initial keystroke is immediate, so the lag only happens on keyboard repeat, i.e. when holding a key.

This happens only on GNOME, both when running on Wayland and Xorg.
I’ve tested on i3 and Sway: the problem disappears.

Adjusting keyboard repeat rate in GNOME also affects this issue but doesn’t solve it: higher repeat rate makes the lag in Godot longer. So if I have a very high repeat rate, Godot might keep “firing” the repeated keystroke for over ~2sec after I release the key.

To exclude the possibility that it's specific to my machine and OS setup, I’ve also tested and confirmed the issue on a spare laptop with a clean install of Fedora 29.

**Comment by kkga** [comment]
After some more experimenting found that the lag is directly tied to my screen resolution, as I'm using a 4k display: if I switch the resolution to 1440p or 1080p -- the lag disappears.

**Comment by Calinou** [comment]
@kkga What framerate do you get in the editor? You can start the Godot binary with `--print-fps` command-line argument to print the FPS continuously to standard output. Note that this setting isn't passed to the editor when starting the project manager, so you will have to edit a project directly by specifying a path to a `project.godot` file:

```text
path/to/godot.binary ~/Documents/Godot/some_project/project.godot --print-fps
```

**Comment by kkga** [comment]
The framerate is really bad :/

This is with V-sync turned off.

Here's what it's like when navigating the script editor in fullscreen:
![Peek 2019-08-08 12-14](https://user-images.githubusercontent.com/1460122/62691003-6e872000-b9d6-11e9-9bbd-ca9d75991233.gif)

The only way to get a usable framerate is to resize the window to something like this:
![Peek 2019-08-08 12-16](https://user-images.githubusercontent.com/1460122/62691043-82cb1d00-b9d6-11e9-92f3-be864ca3be78.gif)

---

As I mentioned before, I'm only experiencing such performance drop on GNOME.

**Comment by Calinou** [comment]
> As I mentioned before, I'm only experiencing such performance drop on GNOME.

GNOME's compositing likely doesn't help with rendering performance… This is why you get better performance in a window manager with compositing disabled :wink:

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by kkga** [comment]
I have a discrete GPU now, so I can't really test under the same conditions.
