### ISSUE TITLE
Navigation2D get_simple_path not resolving a path on a flat tilemap

### ISSUE THREAD

**Issue by agmcleod** [godotengine/godot#31170]
**Godot version:**
3.1

**OS/device including version:**
MacOS 10.14.5 Mojave

**Issue description:**
I setup a tileset with some offset & padding. Each tile is 32x32, with 1px margin around to avoid lines drawing between each tile. I have pixel snap on as well. So the tileset image is 68x68, giving 34x34 of space for each tile.

The game map is 1024x576. The path coordinates don't seem to give me a higher X value than 512. So when i go behind the enemy, whos on the right side of the map won't move towards me. At the start of the gif i move the larger character on the right hand side touching the circle area2d, and the enemy moves away from me instead of towards.

![runaway](https://user-images.githubusercontent.com/113275/62590150-6ecdd100-b899-11e9-8e9c-d9b511c8b78f.gif)

The debug navigation UI seems to show all the tiles aligning correctly as well.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/113275/62590241-ab99c800-b899-11e9-89c5-946d4b3a3be7.png">

**Minimal reproduction project:**
I've included my working project as it's still somewhat small. Have a look at how the tileset is configured, and the enemy scene to see how im using the area2d detection & navigation2d node to use the path.
[ld43.zip](https://github.com/godotengine/godot/files/3474944/ld43.zip)

The most relevant script would be RangedGoblin.gd

**Comment by sparkart** [comment]
get_simple_path() uses local space. That means it's relative to the navigation node.

The origin of your Navigation2D node is offset, so it's messing up your coordinates. If you want to offset the Navigation node, make sure everything is in the same coordinate space by childrening everything to it. Or you can remove your navigation node's offset and positioning it to zero.

**Comment by agmcleod** [comment]
@sparkart corrected it, and yep looks like pathing is working properly now. Thanks a bunch!
