### ISSUE TITLE
Mono: Intermittent hang on game shutdown "Domain finalization timeout"

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#31184]
**Godot version:**
Reproducible (intermittent) on both Godot Mono 3.1.1 Stable and Godot Mono `master` (52cfb5f5799af38e4aa543417a76999b732c3a54)

**OS/device including version:**
Manjaro Linux x64 and Windows 10 (x64?)

**Issue description:**
Very very rarely the game will hang on shutdown with the error
```
ERROR: finalize_and_unload_domain: Mono: Domain finalization timeout
   At: modules/mono/mono_gd/gd_mono.cpp:940.
```
![image](https://user-images.githubusercontent.com/30666851/62648451-cfecb780-b920-11e9-93f9-c43b0d3d6f16.png)
(`-connect` is a custom flag parsed by a game script)

**Steps to reproduce:**
It seems to be related to the networking loosing connection to the server it is connected to (Godot high level multiplayer). Beyond that I haven't been able to reproduce it reliably enough to know anything further which is rather frustrating to be unable to provide more information.

**Minimal reproduction project:**
I can't even reliably reproduce it let alone create a minimal project reproducing it. If anyone *really* wants to test this in my game project its over under [SkyOfSteel](https://github.com/ForLoveOfCats/SkyOfSteel)

**Corresponding bug on our tracker:**  https://github.com/ForLoveOfCats/SkyOfSteel/issues/70

**Comment by ForLoveOfCats** [comment]
Mono logfile here: [log.txt](https://github.com/godotengine/godot/files/3478454/log.txt)

**Comment by ForLoveOfCats** [comment]
Still reproducible on latest master (ba854bbc7bb0eae230299de4da8dfcb7caf74b69)

![image](https://user-images.githubusercontent.com/30666851/64048148-e57b8880-cb3e-11e9-8144-d6727e4c78ad.png)

[Logfile](https://github.com/godotengine/godot/files/3561324/2019_08_30.15.54.11.24114.txt)

**Comment by ForLoveOfCats** [comment]
In the event that the cause of this cannot be determined could a reasonable workaround be implemented such that when this occurs during engine shutdown that the engine will still finish closing?

**Comment by ForLoveOfCats** [comment]
This is still reproducible in Godot Mono 3.2 Beta 2 on GNU/Linux x64

**Comment by ForLoveOfCats** [comment]
As of "recent" (I'm not quite sure what build of 3.2 this changed in) this has changed into a predictable early finalization segfault.

![image](https://user-images.githubusercontent.com/30666851/73029362-634d7280-3e05-11ea-9bb8-74ef4ca419d8.png)

As requested on Discord here is the mono logfile (with `--verbose`)
[EarlyFinalizationMonoLogfileVerbose.txt](https://github.com/godotengine/godot/files/4105870/EarlyFinalizationMonoLogfileVerbose.txt)
And here is the log of all that was spat into the shell (with `--verbose`)
[EarlyFinalizationShellOutputVerbose.txt](https://github.com/godotengine/godot/files/4105878/EarlyFinalizationShellOutputVerbose.txt)

**Comment by neikeq** [comment]
The issue doesn't seem to happen anymore. If you start experiencing it again in the future, we will re-open.
Regarding the last crash. Please open a new issue. There seems to be something wrong with `ProceduralSky`'s worker thread. It's trying to access the `MessageQueue` (via `call_deferred`) after it was already cleaned at exit.
