### ISSUE TITLE
Shader graph editor: "Add node" button is gone

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3118]
In 02d6669a3849c55e415f37b23b36b49f23319957 build there is no "Add node" button. Tested by creating CanvasItemShaderGraphMaterial inside empty Sprite 2d:
![noaddnodesatnodeshader](https://cloud.githubusercontent.com/assets/6129594/11959249/92d38b2a-a8cc-11e5-929f-3389306ea103.png)

**Comment by Ace-Dragon** [comment]
Right-click on the node-editor space and you'll get the add-node menu.

Though I do agree, it would be nice for the button to come back for new users even though the new right-click method is faster and more convenient (or at least a text saying "right click to add node").

**Comment by kubecz3k** [comment]
@Ace-Dragon Thanks for the info, didn't know. Visual button should be somewhere for sure... for each other functionalities there is visual representation and user is expecting this... especially that this is the first place where right mouse button actually is doing something. :)

**Comment by MarianoGnu** [comment]
This was done to allow user to chose where to add the new node, maybe when drag and drop is ready to use we can make a toolbox

**Comment by kubecz3k** [comment]
@MarianoGnu So it was intentional? In that case I will close the issue.
