### ISSUE TITLE
Object.get_method_list() 

### ISSUE THREAD

**Issue by PaulZibert** [godotengine/godot#31181]
Godot version: 3.1.1
Issue description:
function Object.get_method_list() does not return the names and types of arguments  in user-defined functions

**Comment by Wolfcrux** [comment]
I noticed this today while writing a plugin.

**Comment by KoBeWi** [comment]
Still valid in 377c3bb25

This code:
```
func test(mah_strin: String):
	pass

func _ready() -> void:
	var list = get_method_list()
	for m in list:
		if m.name == "test":
			print(m)
```
outputs
```
{args:[{class_name:, hint:0, hint_string:, name:arg0, type:0, usage:7}], default_args:[], flags:65, id:0, name:test, return:{class_name:, hint:0, hint_string:, name:, type:0, usage:7}}
```
The argument has always `name:arg#` and `hint/type:0`.
