### ISSUE TITLE
Add a script-configurable, centralized editor API for executing editor operations.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#31190]
**Issue description:**
The Godot Editor does not have a centralized, user-configurable collection of editor operations that can be executed on command.

If I wanted to build a tool that manipulated the Godot Editor, and also enabled content added by users to also be controlled via this same tool, then I would not have an adequate tool with which to do this. Examples of systems that could take advantage of this are...

- Vim emulation support for the Godot Editor.

- Controlling the Godot Editor's state through an external program, similar to how the GDScript Language Server would give GDScript information to an external program.

Instead, Godot currently has two other systems, each accompanied with issues of their own:

- EditorInterface:

    - Pro: Collects a number of operations for manipulating the editor from the scripting API.

    - Con: User plugins do not have the ability to add to its functionality.

    - Con: Many of the operations it supports are embedded within nested data structures. The full scope of what it can do is not clearly accessible from the top-level of the API.

- KeyboardShortcuts:

    - Pro: Defines a large collection of operations supported by the editor in a list.

    - Pro: Any statically-defined triggers for operations are tracked and can be updated easily.

    - Pro: Users can define their own shortcuts.

    - Con: Operations can only be triggered by using input events.

    - Con: If one were to try and trigger these behaviors manually, one would have to simulate the input events as if they were applied directly to the editor. This does not work for key remapping systems such as vim bindings or emacs bindings, which necessarily need to override shortcuts with custom functionality.

**Proposal**:

What I would prefer is having something like a mix between these two systems where other objects can register their methods to a third-party system, map them to keyboard shortcuts if they want to, and it would all be exposed to the scripting API so that users could also register their own methods to the same centralized system and access everything.

For keyboard shortcuts, which entail a LOT of the editors' functionality, operations are all executed within an input callback belonging to a class when it checks if the current input event matches that of a certain-named shortcut in the editor. This means they are not guaranteed to execute from a dedicated method. If the logic is instead inlined directly into the input callback, it would need to be moved to a method for an on-command solution to be possible.

**Comment by EricEzaM** [comment]
I think this should be moved to the proposals repo.

**Comment by Calinou** [comment]
@EricEzaM This was already done in https://github.com/godotengine/godot-proposals/issues/70 :slightly_smiling_face:
