### ISSUE TITLE
RichTextLabel meta_hover_start and meta_hover_end don’t work along the margins.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#31199]
**Godot version:**

ef05306ca250cc29346e89aedd3e327860f56502

**OS/device including version:**

Win10 64bit 

**Issue description:**

@willnationsdev Found this feature https://github.com/godotengine/godot/pull/12984, and it is exactly what I need, but I am having issues with it not signaling when the hover exits from the edges when the text is right along a margin.

![issue](https://user-images.githubusercontent.com/13004169/62686877-48f61880-b9ce-11e9-8648-51078146290b.gif)

**Steps to reproduce:**

1. Create a RichTextLabel with a URL BBCode tag around text that is along an edge or corner.
2. Connect meta_hover_start and meta_hover_end signals.
3. Move control away from the corner of the window.
4. Run the project and move cursor in and out of the URL tagged text along an edge.

**Minimal reproduction project:**

[3.1 RichTextLabel Meta Hover Issue.zip](https://github.com/godotengine/godot/files/3480564/3.1.RichTextLabel.Meta.Hover.Issue.zip)

**Comment by girng** [comment]
workaround is connecting a mouse_exited signal. but yeah. it's technically a bug within rtl

**Comment by avencherus** [comment]
@girng Yeah, luckily that can be done.  Also need to connect a mouse_enter, and use a flag to track the last meta signals.  The state is frozen where it last was when going in or out.

My use case is for creating a tooltip inside of RTLs.

![image](https://user-images.githubusercontent.com/13004169/62789609-f9991080-bad1-11e9-95ee-e5b57a548495.png)
