### ISSUE TITLE
Godot CLI: Run a project + run a specific scene

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#31218]
Hi,

I would like to use Godot as a CLI. Let's say I have a `project.godot` file which defaults to `MainScene.tscn` when run through the editor, and I have an additional `RunAllTestsScene.tscn`.

I would like to be able to invoke Godot to:

1) Run the project from the CLI, without opening the editor (something like `godot --run <project.godot>`, which is like hitting F5 in the editor.
2) Run `RunAllTestsScene.tscn` from the CLI, eg. `godot --run Scenes/RunAllTestsScene.tscn`

I couldn't find a way to do this. Is it possible? If not, can you add support for this?  The latter allows me to integrate with Travis and friends to get proper CI (eg. failure notification when I break tests which break the build).

**Comment by KoBeWi** [comment]
It is possible: https://docs.godotengine.org/en/3.1/getting_started/editor/command_line_tutorial.html

**Comment by nightblade9** [comment]
Thanks, don't know how I missed that page.
