### ISSUE TITLE
Exported C#/Mono Project Crashes

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#31219]
**Godot version:** 3.1.1 + Mono
**OS/device including version:** Manjaro
**Issue description:** When I export a C#/Mono project to `/tmp` for Linux/x64, it crashes on startup. The console shows this:

```
OpenGL ES 2.0 Renderer: Mesa DRI Intel(R) Sandybridge Desktop 
Mono: Logfile is: /home/nightblade/.local/share/godot/app_userdata/Roguelike/mono/mono_logs/2019_08_08 18.34.18 (29924).txt
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/tmp/data_Godot/Mono/lib/mono/4.5/mscorlib.dll' directory.
```
I checked, and there is no `data_Godot` directory in `/tmp` where I exported my project. Am I doing something wrong? I thought exporting would bundle everything I needed.

**Steps to reproduce:** Unsure. These don't seem to be enough.
- Create a new Godot/Mono project
- Create a scene with a C# file backing it
- Add something simple like `Console.WriteLine("hello from C#!")
- Open the `.proj` file and change the .NET Framework to 4.6.2
- Export it to `/tmp` for Linux/x64
- Run the exported app from the CLI

**Comment by LinuxUserGD** [comment]
Maybe the project is bigger than 4GB. /tmp dir should have half of the size of RAM

**Comment by nightblade9** [comment]
The project is quite small. The pck file is a few kb but the executable is around 68MB. Not unreasonable for a Mono project.

**Comment by neikeq** [comment]
Do you see any error in the terminal when exporting your game? (Right now, the export plugin system we use doesn't allow us to abort when an error occurs while exporting)

**Comment by nightblade9** [comment]
```
 Cannot load assembly (refonly): MonoGame.Framework
 modules/mono/editor/godotsharp_export.cpp:129 - Condition ' depend_error != OK ' is true.
```

I think I figured out the problem. Because my code relies on .NET Standard 2.0 libraries (via NuGet), I changed the .NET Framework version to 4.6.2.

Any ideas how I can make this work?

**Comment by nightblade9** [comment]
I figured it out.

Adding a NuGet reference to `GoRogue` somehow implicitly depends on `MonoGame.Framework`. If I add a NuGet reference to `MonoGame.Framework.DesktopGL`, everything works.

Sorry for the confusion.

**Comment by nightblade9** [comment]
I figured it out.

Adding a NuGet reference to `GoRogue` somehow implicitly depends on `MonoGame.Framework`. If I add a NuGet reference to `MonoGame.Framework.DesktopGL`, everything works.

Sorry for the confusion.
