### ISSUE TITLE
CPUParticles2D crash on iOS with GLES2

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#31231]
**Godot version:**

Godot Engine v3.1.1.stable.official

**OS/device including version:**

iOS / iphoneSE + iPad, project using GLES2, Export with Debug

**Issue description:**

CPUParticles2D crashes the application with an invalid thread access (main thread, gleRunVertexSubmitARM) as soon as the emission Point enters the screen (Particles drawing is activated).

The code works without problems on macOS, Windows/64 and Android with GLES2.
On iOS, simply switching the project to GLES3 "solves" the problem.
This implies a bug for iOS for GLES2

**Steps to reproduce:**
I have a Player (KinematicBody2D) with 2 CPUParticles2D underneath which is frozen by the crash when half of the sprite enters the screen, i.e. the emission point of the Particles is visible.

Export with GLES2 => crash
Export with GLES3 => OK

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Are you able to test if this is fixed in the master branch? (You'd have to compile the editor and iOS template from Git.)

**Comment by oeleo1** [comment]
Yes I am, but it'll take the time it takes when I manage to make for it.

**Comment by oeleo1** [comment]
Finally managed to give it a try with the lastest master branch.
Well, I thought I could do it but it appears move involved than anticipated.
Made my way through compiling the iOS templates in a iphone.zip including arm/arm64/x86_64 images in release+debug, but I am stuck with the build/export chain.
Exporting the project suggests:
a) unresolved ARKit symbols
b) build chain inconsistencies

My config: macOS Mojave 10.14.6, Xcode 10.3
Any help?
Since the whole thing didn't go smoothly I am not sure I'm the best person to test this...
`
ld: warning: object file (/Users/oeleo/Games/export/TestProj.a(btPolyhedralContactClipping.iphone.debug.arm64.o)) was built for newer iOS version (10.0) than being linked (9.0)
ld: warning: object file (/Users/oeleo/Games/export/TestProj.a(asn1write.iphone.debug.arm64.o)) was built for newer iOS version (10.0) than being linked (9.0)
ld: warning: object file (/Users/oeleo/Games/export/TestProj.a(hmac_drbg.iphone.debug.arm64.o)) was built for newer iOS version (10.0) than being linked (9.0)
ld: warning: object file (/Users/oeleo/Games/export/TestProj.a(btMiniSDF.iphone.debug.arm64.o)) was built for newer iOS version (10.0) than being linked (9.0)
Undefined symbols for architecture arm64:
  "_z_error", referenced from:
      _inflate_codes in TestProj.a(ftgzip.iphone.debug.arm64.o)
  "_OBJC_CLASS_$_ARSession", referenced from:
      objc-class-ref in TestProj.a(arkit_interface.iphone.debug.arm64.o)
  "_z_verbose", referenced from:
      _inflateInit2_ in TestProj.a(ftgzip.iphone.debug.arm64.o)
      _inflate in TestProj.a(ftgzip.iphone.debug.arm64.o)
      _inflateEnd in TestProj.a(ftgzip.iphone.debug.arm64.o)
      _inflateReset in TestProj.a(ftgzip.iphone.debug.arm64.o)
      _inflate_blocks_reset in TestProj.a(ftgzip.iphone.debug.arm64.o)
      _inflate_codes_free in TestProj.a(ftgzip.iphone.debug.arm64.o)
      _inflate_blocks_new in TestProj.a(ftgzip.iphone.debug.arm64.o)
      ...
  "_OBJC_CLASS_$_ARWorldTrackingConfiguration", referenced from:
      objc-class-ref in TestProj.a(arkit_interface.iphone.debug.arm64.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/oeleo/Library/Developer/Xcode/DerivedData/TestProj-eolncyplhlpttdegqigbryhgpekl/Build/Intermediates.noindex/ArchiveIntermediates/TestProj/IntermediateBuildFilesPath/TestProj.build/Debug-iphoneos/TestProj.build/Objects-normal/arm64/TestProj normal arm64
(1 failure)
error: archive not found at path '/Users/oeleo/Games/export/TestProj.xcarchive'
** EXPORT FAILED **
`

**Comment by oeleo1** [comment]
Good news -- this can be closed. Tested on the latest 3.2.beta master branch and it doesn't crash.

**Comment by clayjohn** [comment]
Great! Thanks for following up. :)
