### ISSUE TITLE
GDScript error when using `get_tree().root.foo = bar` (setter called on property with read-only property)

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#31245]
**Godot version:**
Tested on nightly build and 3.1.1

**OS/device including version:**
GNU/Linux x64

**Issue description:**
The engine seems to only throw an error when using get_tree().root.foo = bar, I tried with another object and the script ran fine.
![image](https://user-images.githubusercontent.com/18746022/62800495-8a132900-bab1-11e9-89b8-41ccb180477e.png)

**Steps to reproduce:**
use get_tree().root.foo = bar in a script

**Minimal reproduction project:**
[GDScriptBug.zip](https://github.com/godotengine/godot/files/3487608/GDScriptBug.zip)

**Comment by TheDuriel** [comment]
Possibly because you are trying to access a parent node in _ready within the games main scene. The scenetrees root viewport may not have readied by then.

**Comment by MightyPrinny** [comment]
> Possibly because you are trying to access a parent node in _ready within the games main scene. The scenetrees root viewport may not have readied by then.

Probably not since storing the in a variable and using it works as shown in the code and doing the same in _process also causes an error.

**Comment by Xrayez** [comment]
Calling `get_root()` method directly works:
```gdscript
get_tree().get_root().render_target_v_flip = true
```
When attempted with property, strangely the following hack works: :eyes:
```gdscript
((get_tree().root) as Viewport).render_target_v_flip = true
```
(this casts the `root` to viewport before accessing)

 The following prints `true`, though:
```gdscript
print(get_tree().root is Viewport) # true
```

**Comment by DavidSichma** [comment]
I think I commented this on another issue.

If you set the last value "property chain" like this
```gdscript
a.b.c.d = new_val_d
```
Godot will update each property in reverse. Once the `d` value is set for `c` the updated value for `c` will be set for `b` and then `b` for `a`. Like the code gets transformed to this:
```gdscript
var b = a.b
var c = b.c
c.d = new_val_d
b.c = c
a.b = b
```
So in your code Godot sets a property for `root` and tries to call `get_tree().root = root` but the latter is an invalid operation (only read access).

It's been a while though and I don't remember exactly where this behavior applies in GDScript. I think this covers the C++ code that is just exposed.

Calling a get-method will break the chain and is a valid workaround.

**Comment by akien-mga** [comment]
This is still reproducible in the current `master` branch.
