### ISSUE TITLE
Inspector doesn't show the real property values

### ISSUE THREAD

**Issue by athal24** [godotengine/godot#31246]
Godot 3.1.1 Stable Win64

Windows 10 Pro 10.0.17763 compilación 17763

**Issue description:**
Inspector not updating the values of the instances that were changed on its original scene.

**Steps to reproduce:**
Import the example proyect I provided, that is the same used as example in the Step by Step tutorial on the Godot docs: http://docs.godotengine.org/en/latest/getting_started/step_by_step/instancing.html
Add one instance of the "ball.tscn" as a child of the "Main" node.
Now open the ball scene editor and change the "Scale Gravity" value on the inspector from 4 to -4. 
Go back to the Main.tscn to see that the inspector still shows the original value (4) and not the new one. F5 to reproduce and see that the changes are affecting the ball instance, because it goes up instead of down, but inspector still shows "4" on "Gravity Scale".
Sorry if I am missing something because I have so much to learn but this wasn't the behaviour I expected. 

[instancing.zip](https://github.com/godotengine/godot/files/3487635/instancing.zip)

**Comment by qarmin** [comment]
Everything seems work with 3.1.1 and 3.2
![file](https://user-images.githubusercontent.com/41945903/62801689-92d22200-bae6-11e9-97d8-6632d0812e47.gif)

Maybe you changed value in instanced scene?
If yes, then this value become local and changing base value doesn't change it.

**Comment by athal24** [comment]
> Everything seems work with 3.1.1 and 3.2
> ![file](https://user-images.githubusercontent.com/41945903/62801689-92d22200-bae6-11e9-97d8-6632d0812e47.gif)
> 
> Maybe you changed value in instanced scene?
> If yes, then this value become local and changing base value doesn't change it.

Thank you for your answer. It's strange, I think that I am doing exactly the same but the result is different. 
![Godot inspector bug](https://user-images.githubusercontent.com/42813957/62804967-f82a1100-baee-11e9-805f-204032eff63c.gif)

**Comment by qarmin** [comment]
It not works because you don't save Ball scene.

**Comment by athal24** [comment]
Ohh I see, thank you very much. I thought I was doing the same but I guess you used a shortcut to save the ball scene. I close the issue.
