### ISSUE TITLE
Blank screen after opening a project on Arch Linux

### ISSUE THREAD

**Issue by glatteis** [godotengine/godot#31240]
I know this is not enough info. I would be very thankful if someone could guide me into the direction of how to fix this.

**Godot version:**
3.1.stable.official

**OS/device including version:**
Clean Arch Linux 64bit install on an Intel video card

**Issue description:**
Opened a project. Expected: Something shows up. Happened: Nothing showed up.
A window does open, but without anything rendering (not black or white, just showing what was last on screen)
On htop, godot is still open and uses up a lot of cpu.

**Steps to reproduce:**
Open project

**Comment by Calinou** [comment]
Which exact graphics card model do you have? Also, can you see something if you resize the window?

**Comment by LinuxUserGD** [comment]
You could print neofetch which shows hardware and driver

**Comment by glatteis** [comment]
Output of lspci:
```
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Haswell-ULT Integrated Graphics Controller
	Flags: bus master, fast devsel, latency 0, IRQ 50
	Memory at f0000000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915
```
glxinfo:
```

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.1.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 19.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by glatteis** [comment]
I have identified the culprit.
This is apparently a problem that appears only when using the window manager wingo (https://github.com/BurntSushi/wingo).
I never had a problem with wingo before. Very weird.

**Comment by glatteis** [comment]
Also works with bspwm. I'm inducting this is a problem with wingo. Closing this.
