### ISSUE TITLE
Changing text of label which is child of a viewport, changes colour of all cpu particle systems

### ISSUE THREAD

**Issue by slasktotten** [godotengine/godot#31250]
**Godot version:**
3.1.1

**OS/device including version:**
Tested on variety of apple laptops and iphones. Bug only appears using GLES3, both in builds and while running project from editors

**Issue description:**
When using label as a child of a viewport. Setting it's text makes all cpu particle systems the same color as the font color. Setting update mode to disabled on the viewport makes it display correctly. This is only an issue on GLES3. Everything looks as it should with GLES2.

**Steps to reproduce:**
I have a label as a child of a viewport. When I try to set text with set_text() it will tint color of all cpu particle systems the same color as the font color of the label. This is only an issue on GLES3 and works perfectly on GLES2. It also specifically triggers when writing the text so just setting the font color itself doesn’t work.

Create a viewport
Set x, y to more then 2
Set Update mode to Always

Create a label
Make label child of viewport

Add a cpu particle system
Give it a mesh and spatial material
Under material/Vertex Color, set Use As Albedo to true

Programatically change font color add_color_override(“font_color”, Color.red) and set text of label with set_text()

[godot_bug.zip](https://github.com/godotengine/godot/files/3487954/godot_bug.zip)

**Comment by Calinou** [comment]
This bug sounds very similar to https://github.com/godotengine/godot/issues/30275.
