### ISSUE TITLE
Ability to rename root node of inherited scene

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3125]
It would be really nice if there could be ability to rename the most root node in inherited scene. 
Reasoning:
Currently when we are inheriting a scene, the base name for this scene is taken from it's ancestor and there is no possibility to change it in the scene itself. So for example when we are creating concrete enemies, we have a lot of "BaseEnemy"  names and we need to remember to rename them manually each time after instancing this concrete scene somewhere, which is inconvenient and error prone.

**Comment by kubecz3k** [comment]
After a reflection I decided to set milestone to 2.0 since SceneInheritance is introduced in 2.0 and it might be good idea to have this from the beginning. It's up to @reduz  to decide if this is needed and if yes when to add it (change milestone, close or discuss :))

**Comment by kubecz3k** [comment]
just a ping

**Comment by bojidar-bg** [comment]
:+1:

**Comment by kubecz3k** [comment]
Solved by Reduz in this commit: https://github.com/godotengine/godot/commit/595de75641e0fae1f4e6924530da7a3308371a07 
Seems to work fine so I'm closing it :+1: :)
