### ISSUE TITLE
Moving ALL files from a folder deletes the folder

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31264]
**Godot version:**

3.1

**OS/device including version:**

Win7

**Issue description:**

When using the editor file dock to move _all_ files from a folder, it will subsequently delete the folder. This can mess with project management quite a bit.

**Comment by creikey** [comment]
Unable to reproduce on linux

**Comment by TheDuriel** [comment]
before moving
![image](https://user-images.githubusercontent.com/44248915/62821343-9364ca00-bb73-11e9-911d-0a8c627eaeac.png)

after moving, tabbing out, and tabbing back in
![image](https://user-images.githubusercontent.com/44248915/62821345-a8415d80-bb73-11e9-8a32-147b0ca55a45.png)

**Comment by TheDuriel** [comment]
It's sourcetrees fault lawl.
