### ISSUE TITLE
ReImport Causes Crash

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot#31273]
**Godot version:**
3.1.1 Mono x64

**OS/device including version:**
NVidia Optimus, Windows 10 x64

**Issue description:**
Reimporting DAE frequently crashes. I'm not quite sure if it's limited to that, but I think that it usually happens when I turn off importing animations for meshes without any. When I re-open Godot, all is well and the model has no AnimationPlayer.

**Comment by Calinou** [comment]
Could you upload a minimal reproduction project with the model(s) included, please?

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
