### ISSUE TITLE
AudioEffectRecord::get_recording() is always returning null

### ISSUE THREAD

**Issue by DomsterKB** [godotengine/godot#31282]
**Godot version:**
v3.2.dev.custom_build.3418f76a9

**OS/device including version:**
Windows 10 Pro x64

**Issue description:**

The mic_record project in godot-demo-projects fails after audio recording.  the variable recording is expected to contain AudioStreamSample after calling get_recording(), but instead a null is returned from get_recording().

This is not an issue on v3.1.1-stable.official and works perfectly fine.

**Steps to reproduce:**
1. Play the mic_record project.
2. Press Record.
3. Press Stop.
4. Press Play. The program breaks at _on_PlayButton_pressed() as variable recording is null because get_recording() returned a null.

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record

**Comment by akien-mga** [comment]
CC @SaracenOne

**Comment by SaracenOne** [comment]
Hmm, I don't it was my changes which broke this, but I had quick look at the code and I think I fixed it anyway.

**Comment by SaracenOne** [comment]
PR fix here (https://github.com/godotengine/godot/pull/31310)

**Comment by akien-mga** [comment]
You're right, this was actually a regression from #29980. Thanks for fixing it nevertheless :)
