### ISSUE TITLE
Full-window flashing glitch when previewing sample project

### ISSUE THREAD

**Issue by thoughton** [godotengine/godot#31280]
**Godot version:**
Godot Engine v3.2.dev.custom_build.ab7ee63e3
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 

**OS/device including version:**
Host: XPS 13 9370 
OS: Ubuntu 19.04 x86_64 
Kernel: 5.0.0-23-generic 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
GPU Driver: i915 
Resolution: 1920x1080 
Memory: 3995MiB / 15754MiB 

**Issue description:**
Some time over the past couple of months I've noticed that when testing the "Dynamic Character Control-Based Platformer" sample it occasionally flashes a bright full-window glitch.

Here's a video of it occurring: https://www.youtube.com/watch?v=OWviruuA3AQ

Unfortunately I don't know exactly when this started happening, but I do happen to have an older clone of the engine on the same system which still works fine. The version of that working clone is: v3.2.dev.custom_build.4e361c4

Please let me know if there's any extra debugging info I could provide.

Thanks!

**Comment by KoBeWi** [comment]
@thoughton Can you still reproduce this issue in 3.2.3?

**Comment by akien-mga** [comment]
No answer, so closing.
