### ISSUE TITLE
Undefined behaviour while quitting with custom export template

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#31281]
**Godot version:**
3.1.1 stable

**OS/device including version:**
Windows 10 (1803)

**Issue description:**
When quitting via SceneTree.quit() or pressing the X button to close with a custom export template made with the command below the application seems to crash

**Steps to reproduce:**
Compile the **3.1** branch with the following command:

---

`scons C=gcc CXX=g++ platform=windows tools=no disable_3d=yes disable_advanced_gui=yes module_bmp_enabled=no module_bullet_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etc_enabled=no module_gdnative_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_mbedtls_enabled=no module_mobile_vr_enabled=no module_opus_enabled=no module_pvr_enabled=no module_recast_enabled=no module_regex_enabled=no module_squish_enabled=no module_tga_enabled=no module_thekla_unwrap_enabled=no module_tinyexr_enabled=no module_webm_enabled=no module_websocket_enabled=no target=release debug_symbols=no bits=64 use_mingw=yes use_lto=yes`

**and**

`strip bin/godot.windows.opt.64.exe`
---

Then copy the executable and replace the `%USERPROFILE%\AppData\Roaming\Godot\templates\3.1.1.stable\windows_64_release.exe` by this new one (also remember to change the executable's name)

Then create an empty project and export it with `Export with Debug` unchecked.

Open the game and close it

**Minimal reproduction project:**
Any project

---

EDIT: I recompiled removing all "disable" s and the game closed correctly.
`scons C=gcc CXX=g++ platform=windows tools=no target=release debug_symbols=no bits=64 use_mingw=yes use_lto=yes`

**Comment by akien-mga** [comment]
You can't mix different versions like that.

The current `3.1` branch is not the 3.1.1 release, it has many more commits for what will become the 3.1.2 release eventually.

If you want to use a custom built template from the `3.1` branch, you should also use a custom built editor from the same commit. Or you can compile the `3.1.1-stable` tag instead.

**Comment by Muller-Castro** [comment]
@akien-mga Omg sorry I didn't notice that :/

But I repeated the same steps following your [suggestion](https://github.com/godotengine/godot/releases/tag/3.1.1-stable) and it keeps crashing when quitting :/

**Comment by Muller-Castro** [comment]
@akien-mga It's something related to `disable_3d=yes`, this flag is causing the crash... I tested without it and the game closed correctly.

I'll see if I can fix it
