### ISSUE TITLE
Internal script error! - opcode #9 (report please).

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#31287]
**Godot version:**
3.1 Stable

**OS/device including version:**
Windows

![Screenshot_1](https://user-images.githubusercontent.com/1850856/62832457-05521780-bc37-11e9-978b-9733be1457a8.png)
![Screenshot_2](https://user-images.githubusercontent.com/1850856/62832458-05eaae00-bc37-11e9-9a78-8893c6d325e8.png)
![Screenshot_31](https://user-images.githubusercontent.com/1850856/62832459-06834480-bc37-11e9-9ac2-f8f636f7ad42.png)

**Comment by akien-mga** [comment]
Could you provide a minimal reproduction project? It's a bit hard to assess the error just based on three small screenshots.

**Comment by zaksnet** [comment]
Sorry I can't replicate this. It happens randomly and I only reported it because it was kindly asked in the message ! The screenshots where all the info I had at the moment, if they are not much of use, you can close this ( or wait couple of days in case this happends again). Also if you can give me some info on what this error means I might be able to replicate it.

**Comment by bojidar-bg** [comment]
For whenever this happens again: You should have another error in addition to the opcode 9 error, make sure to include it in the bug report.

<details>
    <summary>Reasoning (looking at `gdscript_function.cpp`)</summary>

Opcode 9 is `OPCODE_ASSIGN`. In order for this message to print, `err_text` shouldn't have been set. Only way to get out of the opcode dispatching loop is with `OPCODE_BREAK`.
`OPCODE_ASSIGN` does not use `OPCODE_BREAK` directly, but uses `CHECK_SPACE` and `GET_VARIANT_PTR`, both of which do.
`CHECK_SPACE` will set `err_text` unconditionally before hitting `OPCODE_BREAK` (via `GD_ERR_BREAK`).
`GET_VARIANT_PTR` calls `_get_variant`, passing `err_text` as the `r_error` parameter, and hits `OPCODE_BREAK` if that function returns `NULL`. Inspecting that function reveals that in order for it to return `NULL`, it would have to exit via one of the `ERR_` macros inside it.

</details>

**Comment by zaksnet** [comment]
Seems to be related to hot script reloading, at-least in my case and happens on rare occasions (mostly misuse so it can be ignored).
