### ISSUE TITLE
Linkage error when crosscompiling for Windows with mono

### ISSUE THREAD

**Issue by crym0nster** [godotengine/godot#31288]
**Godot version:**

3418f76a9eab9f496e5b26310bd3bc1125b8119b

**OS/device including version:**

Arch Linux

**Issue description:**

When crosscompiling for Windows with mono enabled I got this linkage error at the end of compilation 

[100%] /usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lo
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ln
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lo
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -l-
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -l2
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -l.
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -l0
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -l-
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ls
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lg
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -le
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ln
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.tools.64.mono.exe] Error 1
scons: building terminated because of errors.

The problem appears to be in this line:
https://github.com/godotengine/godot/blob/3418f76a9eab9f496e5b26310bd3bc1125b8119b/modules/mono/build_scripts/mono_configure.py#L127
When changed the line above to `env.Append(LIBS=[mono_lib_name])` compilation completes successfully

**Steps to reproduce:**
Build from source with
 `scons -j8 p=windows target=release_debug tools=yes module_mono_enabled=yes mono_prefix=/path/to/windows/mono bits=64`
The mono directory i have copied from windows installation

**Comment by santouits** [comment]
What does the mono_lib_name variable prints?

**Comment by crym0nster** [comment]
> What does the mono_lib_name variable prints?
It prints mono-2.0-sgen. But if I print env.Dump(), then in LIBS section will be the following: 

`'LIBS': [<SCons.Node.FS.File object at 0x563ae45fa5d0>, [<SCons.Node.FS.File object at 0x563ae45da630>], [<SCons.Node.FS.File object at 0x563ae4596970>], [<SCons.Node.FS.File object at 0x563ae440f4f0>], [<SCons.Node.FS.File object at 0x563ae439aa90>], [<SCons.Node.FS.File object at 0x563ae4370050>], [<SCons.Node.FS.File object at 0x563ae479bf90>], 'mingw32', 'opengl32', 'dsound', 'ole32', 'd3d9', 'winmm', 'gdi32', 'iphlpapi', 'shlwapi', 'wsock32', 'ws2_32', 'kernel32', 'oleaut32', 'dinput8', 'dxguid', 'ksuser', 'imm32', 'bcrypt', 'avrt', 'uuid', 'm', 'o', 'n', 'o', '-', '2', '.', '0', '-', 's', 'g', 'e', 'n'],`

I think that env.Append() treats mono_lib_name as a list and adds every individual character from that string to LIBS.

**Comment by neikeq** [comment]
>`'LIBS': [<SCons.Node.FS.File object at 0x563ae45fa5d0>, [<SCons.Node.FS.File object at 0x563ae45da630>], [<SCons.Node.FS.File object at 0x563ae4596970>], [<SCons.Node.FS.File object at 0x563ae440f4f0>], [<SCons.Node.FS.File object at 0x563ae439aa90>], [<SCons.Node.FS.File object at 0x563ae4370050>], [<SCons.Node.FS.File object at 0x563ae479bf90>], 'mingw32', 'opengl32', 'dsound', 'ole32', 'd3d9', 'winmm', 'gdi32', 'iphlpapi', 'shlwapi', 'wsock32', 'ws2_32', 'kernel32', 'oleaut32', 'dinput8', 'dxguid', 'ksuser', 'imm32', 'bcrypt', 'avrt', 'uuid', 'm', 'o', 'n', 'o', '-', '2', '.', '0', '-', 's', 'g', 'e', 'n'],`
>
>I think that env.Append() treats mono_lib_name as a list and adds every individual character from that string to LIBS.

Thanks, I didn't understand what was actually happening until I read this. Saved me some time.
