### ISSUE TITLE
PopupPanel _ready() not called, "error calling method from signal" upon opening

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#31296]
**Godot version:**

3.1

**OS/device including version:**

macOS 10.14.6
MacBook Pro

**Issue description:**

1. _ready() is not called at all. From the tests I did with a super minimal example, it should be called after _init() -- without having to open the popup.
2. When opening the popup, I get this error message:
```
E 0:00:01:0485   Error calling method from signal 'about_to_show': 'PopupPanel::on_about_to_show': Method not found.
  <C Source>     core/object.cpp:1238 @ emit_signal()
  <Stack Trace>  MainScene.gd:9 @ _unhandled_input()

```

I was not able to reproduce either of these issues starting from scratch with a minimal example, only when reducing my existing project down to the attached version.

**Steps to reproduce:**
Run the attached project and press T to open the popup.

**Minimal reproduction project:**
[popup-test.zip](https://github.com/godotengine/godot/files/3490179/popup-test.zip)

**Comment by mitchcurtis** [comment]
OK, I figured out a workaround for #1: attach the SavePopup.gd script to the _instance_ of SavePopup. This shouldn't be necessary, since SavePopup.tscn already has a script attached to its root node.

**Comment by akien-mga** [comment]
Your instance had script removed, which does not happen when creating new instances (either via drag and drop or by pressing the "Instance" button):
![Screenshot_20190812_092004](https://user-images.githubusercontent.com/4701338/62850218-78fd2e80-bce2-11e9-8eb6-a87adca04871.png)

So most likely you reset the script yourself somehow, e.g. by pressing the "Clear Script" button on the instance.

If you can reproduce a scenario where the script is lost without you removing it, then please file a dedicated bug report.
