### ISSUE TITLE
Allow SurfaceTool to add data to INSTANCE_CUSTOM for shader

### ISSUE THREAD

**Issue by orosmatthew** [godotengine/godot#31299]
I am trying to write a shader and need to send just 3 more values to the shader for each vertex (which would massively simplify the whole process). The docs say that this value is mostly used for particles but since I am not using particles, it would be great if I could use those values instead for a different purpose. It would be optimal if I could set these values using the SurfaceTool

**Comment by clayjohn** [comment]
I am assuming you figured out the correct answer yourself. But as a note for others who may struggle with the same problem. ``INSTANCE_CUSTOM`` is only used by Particles and MultiMeshes. To set it yourself, you can use the MultiMesh function [set_instance_custom_data](http://docs.godotengine.org/en/latest/classes/class_multimesh.html#class-multimesh-method-set-instance-custom-data). The reason it can't be accessed through the surfacetool is that the surfacetool sets per-vertex parameters on the surface, while ``INSTANCE_CUSTOM`` is a per-instance variable that can only be set on MultiMeshes. 

Hope that helps :)
