### ISSUE TITLE
HTML5: this.rtenv.callMain is not a function when using latest-upstream backend

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#31297]
**Godot version:**
master (https://github.com/godotengine/godot/commit/3418f76a9eab9f496e5b26310bd3bc1125b8119b)

**OS/device including version:**
Arch Linux

**Issue description:**
This error shows when loading the .pck with Chromium
console log:
```Swift
test.html:246 this.rtenv.callMain is not a function
displayFailureNotice @ test.html:246
```

**Steps to reproduce:**
```Swift
scons p=x11 bits=64 target=release_debug tools=yes use_llvm=yes use_lld=yes use_thinlto=yes -j 8
./emsdk install latest       OR:      ./emsdk install latest-upstream
./emsdk activate latest               ./emsdk activate latest-upstream
source ./emsdk_env.sh
scons p=javascript target=release_debug tools=no -j 8
python3 -m http.server
http://localhost:8000/test.html
```

Tested projects: Solus Sphere (https://github.com/HugeGameArtGD/Solus-Sphere) and material demo (both GLES2)

**Comment by Mellondill** [comment]
Same with me, but I've tried omg macOS.
As I've understood new versions of Emscripten doesn't export `callMain` function in `Module["callMain"]` and this is the main problem.
Maybe someone knows how to resolve this problem?

**Comment by Mellondill** [comment]
I've found the problem. Due to Emscriptens [changlog](https://github.com/emscripten-core/emscripten/blob/incoming/ChangeLog.md#v13841-08072019) :

> `callMain` is no longer exported by default on Module, to allow better JS minification. You must add it to `EXTRA_EXPORTED_RUNTIME_METHODS` if you want to call it on Module. (In assertions builds, an error with an explanation is shown.)

**Comment by kripken** [comment]
Correct, yes, as the error says we no longer export it by default. You can add the flag to export it.

Sorry for this annoyance, but we sometimes need to make a breaking change like this in order to make progress. We do try to always document it in the changelog, and to make builds with assertions show a clear error, to minimize the annoyance.

**Comment by Mellondill** [comment]
@akien-mga , think this issue could be closed

**Comment by LinuxUserGD** [comment]
@Mellondill I think there should be a PR to make the flag the default option.

**Comment by Mellondill** [comment]
@LinuxUserGD ah, sorry forgot about PR

**Comment by Mellondill** [comment]
@LinuxUserGD created PR with needed changes

**Comment by Calinou** [comment]
@kripken Do you know which changes would be required for Godot to work without `callMain`? This way, we could benefit from better JavaScript minification as stated by the changelog.

**Comment by kripken** [comment]
@Calinou in general you shouldn't need callMain - main will be called automatically by the emscripten runtime, when everything is ready. But if godot has special logic for when to start, then using callMain is reasonable (and the downside isn't big, it's just a few JS strings of "callMain" in the final JS file).

**Comment by Mellondill** [comment]
@Calinou As I understand, initial resource package must be synced in internal filesystem before main function could be called in Godot, so that's why we need such changes
