### ISSUE TITLE
libXcursor.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by YugoCode** [godotengine/godot#3129]
I use the latest build from http://fixnum.org/godot/ [December 22, 2015 at 20:33]
and the according export template from the site.

I exported for 32bit Linux, and if I run it, I get:

./my_game: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory

PS:
I have Ubuntu 15.10 on 64bit machine.

**Comment by Calinou** [comment]
Did you install the 32-bit version of the requested library? You can do so using this syntax:

`sudo apt-get install libxcursor-dev:i386`

**Comment by YugoCode** [comment]
Thank you Calinou!!
The next error then is:
error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

I tried  sudo apt-get install libssl:i386
But it cannot find libssl.

**Comment by Hinsbart** [comment]
I think it's called [libssl1.0.0](http://packages.ubuntu.com/wily/libssl1.0.0)

**Comment by akien-mga** [comment]
Closing as it's not a Godot issue but more a general topic about how to run 32-bit binaries on a 64-bit system. (Now that it's started, feel free to continue debugging your issues in this topic, but I close the "issue" as it's not something that Godot devs need to work on specifically).
