### ISSUE TITLE
Not easy to get logical screen resolution with stretch mode 2D

### ISSUE THREAD

**Issue by robgraeber** [godotengine/godot#31308]
**Godot version:** 3.1

**Issue description:**
When using stretch mode 2D and one of the stretch aspects e.g. keep_height, AFAIK it's not easy to find what's the logical dimensions of the screen without calculating it yourself. E.g. you're able to get the project settings window size and the viewport size which is the *actual* window size in pixels, but you're not able to get the project settings window size adjusted for the aspect ratio out of the box.

For example:
Given a project window size of 1000 x 1000. With stretch mode 2D and keep_height, if the aspect ratio is 1.7 I want a way to be able to get the logical window size of 1700 x 1000 as this is the dimension all the game coordinates are based on.

Apologies if this is already available but I couldn't find it after researching for a couple of hours.

**Comment by pouleyKetchoupp** [comment]
You can use `OS.window_size` to get the adjusted size:
https://docs.godotengine.org/en/3.1/classes/class_os.html#class-os-property-window-size

**Comment by robgraeber** [comment]
@pouleyKetchoupp `OS.window_size` returns the same thing as `get_viewport().size`, which is the actual size of the window in pixels. 

Here's a demo of the issue:
[ScreenSizeDemo.zip](https://github.com/godotengine/godot/files/3491397/ScreenSizeDemo.zip)

For a 1000x1000 project window, set to a 500x300 test window with 2D stretch and keep_height, it will log:

```
1000 1000 # project size
(500, 300) # os window size
(500, 300) # get_viewport().size
```
But what I want is (1666.67, 1000)

**Comment by pouleyKetchoupp** [comment]
Ok, I don't know why `get_viewport().size` doesn't return the right thing, but it seems what you're looking for is `get_viewport_rect().size`.

**Comment by Calinou** [comment]
What about `get_viewport().get_size_override()`?

**Comment by robgraeber** [comment]
Thanks all `get_viewport_rect().size` is what I was looking for. `get_viewport().get_size_override()` works too for 2D stretch, but would be less versatile as it returns (0, 0) for viewport stretch modes.

**Comment by Zireael07** [comment]
I guess this should get a documentation label?
