### ISSUE TITLE
NavigationMesh dynamic obstacle detection

### ISSUE THREAD

**Issue by soloparatolos** [godotengine/godot#3130]
NavMesh is working great right now but lacks the ability to detect Bodies and Areas in real time to calculate paths when something changes in the scene. Implementing something like this seem really relevant.

**Comment by reduz** [comment]
I've been thinking about how to do this, it should hopefully not be that
difficult

**Comment by soloparatolos** [comment]
I never tried Urho 3d but I've seen they have something like this. Dont know if their approach can be acceptable for Godot.

**Comment by reduz** [comment]
They use recast, but I prefer something more customizable

**Comment by soloparatolos** [comment]
Perfect, more options are always better.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
What's the status on this in the current master branch?

**Comment by reduz** [comment]
i was thinking about leaving it for 3.1. There are libraries like
Recast/Detour that can handle this, but they are limited to agents all the
same size, so I would like to research if it's possible to do it better

**Comment by akien-mga** [comment]
We've planned to work on navigation issues for 3.2, so moving to that milestone.

**Comment by Byteron** [comment]
Is this being worked on now?
Certainly would be useful to have.

**Comment by regakakobigman** [comment]
Will this be making it into 3.2?

**Comment by Calinou** [comment]
This was implemented by #34776, closing.
