### ISSUE TITLE
Game on android 4.4 does not work

### ISSUE THREAD

**Issue by Schweini07** [godotengine/godot#31316]
**Godot version:**
3.1

**OS/device including version:** 
Samsung Galaxy S4 mini with android 4.4.4

**Issue description:**
This issue is related to this question: https://godotengine.org/qa/50091/game-app-not-working-when-i-change-display-settings
I have the same problem when I try to play my game: https://schweini007.itch.io/fish-catching, where the display settings are 2D and keep.

**Comment by Calinou** [comment]
Your project seems to use the GLES3 renderer (at least when running the Linux binary). Try switching to the GLES2 renderer in the project settings.

**Comment by Schweini07** [comment]
If I would like to export my game to the Google Play Store and would like to support all android version, what should I do then?

**Comment by akien-mga** [comment]
Switch to the OpenGL ES 2.0 renderer as mentioned. Old devices don't support OpenGL ES 3.0.

**Comment by Schweini07** [comment]
Ok it works now. I understood now how to handle that with the Play Store. Thanks
