### ISSUE TITLE
Consider removing *.sln from .gitignore

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#31318]
Our `.gitignore` is configured to ignore solution files:

https://github.com/godotengine/godot/blob/5441aaf768d6dd4c3d8465e6b340ae38ddc7db1d/.gitignore#L86

This is bad as such files are not meant to be ignored. It's specially annoying for me as I use solutions for C# projects in the mono module. It already happened twice that I didn't commit a solution file because of this; the first one made it into master resulting in build errors.

As far as I understand, this was done to ignore generated solution files (via the `vsproj=yes` SCons option) for working with the Godot source code in Visual Studio.
Is this option guaranteed to always generate the solution at the same location? If that's the case, would it be possible to replace that line in our `.gitignore` with `actual/path/to/generated/solution.sln`?

**Note:**

We are also ignoring Visual Studio C++ project files:

https://github.com/godotengine/godot/blob/5441aaf768d6dd4c3d8465e6b340ae38ddc7db1d/.gitignore#L87

This is also wrong and it would be better to ignore a specific path instead. That being said, I don't use Visual Studio C++ projects so it's not a problem for me.

**Comment by akien-mga** [comment]
You can simply add an override for the Mono module:
```
diff --git a/modules/mono/.gitignore b/modules/mono/.gitignore
new file mode 100644
index 000000000..f47f98b34
--- /dev/null
+++ b/modules/mono/.gitignore
@@ -0,0 +1 @@
+!*.sln
```

**Comment by akien-mga** [comment]
> As far as I understand, this was done to ignore generated solution files (via the vsproj=yes SCons option) for working with the Godot source code in Visual Studio.

That one likely gives you a specific path, but you can also create your own custom solution without using this option if you want, just like I can create any `SomeNameIPicked.creator` QtCreator project definition.

So it's better IMO to have a wildcard ignore for all IDE-specific files which are not required for our buildsystem, and then have specific overrides for the files which do matter to our buildsystem, and which in this case are limited to the `modules/mono/` folder (and in the future possibly `misc/ide/` if we decide to add more helpers like that).

**Comment by neikeq** [comment]
Thanks, I didn't realize it was possible to override it in a sub-directory. I will make a PR.
