### ISSUE TITLE
Better export pipeline

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [godotengine/godot#31311]
I am currently using a Cmake instead of Godot's internal "Export" in order to build my project due to the fact that there are multiple DLL's that needs to be built on top of the engine itself, and I ran into some limitations on my part. It seems that there is really no other way to build .pck / .zip (It is somewhat easy, but there is no out of the box way of doing that) then doing this manually every single time. 

My point is: It would be great to see some godot.packing.%version%.%os_executable% supplied with current toolchain in order to automate such a process. My current self-proclaimed solution is to strip out the code for the export from the editor to a separate executable and supply it with the export template.

**Comment by akien-mga** [comment]
You can export a .pck or .zip just fine from the command line with a headless binary (or non-headless, but then you'll see the editor pop up while it exports).
```
godot-headless --export "Linux/X11" game.pck
```

The string after `--export` should match one of the platform names defined in your `export_presets.cfg`.

**Comment by IlyaStuurFedorov** [comment]
Thanks,[ it seems like I missed that part of this part of the documentation.](https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_projects.html?highlight=Export#exporting-from-the-command-line)
