### ISSUE TITLE
CollisionShape2D.set_disabled is not called when using Collision2D.disabled

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#31325]
**Godot version:** 3.1.1

**OS/device including version:** Solus Gnome 4.0

**Issue description:**

When mutating `CollisionShape2D.disabled` the setter method `CollisionShape2D.set_disabled(disable)` is not called

**Steps to reproduce:**
1. Create a CollisionShape2D
2. Add a script
3. Override the `set_disabled` method to 
```
func set_disabled(disable):
    .set_disabled(disable)
    print(disable)
```
4. Try to mutate the variable (try `self.disabled = !disabled` on the `_ready` callback or mutate it from an outer class

**Comment by KoBeWi** [comment]
It is called, you just can't override the setter. See #29390
