### ISSUE TITLE
Editor freeze on search previous

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31328]
**Godot version:**
3.1.1

**Issue description:**
I encountered an editor freeze that might happen when using search previous (Shift + F3) in the code editor. No idea what exactly causes it, but it results in this loop running infinitely:
https://github.com/godotengine/godot/blob/3c78837218bafed0324d67f4f721fed8887a4369/scene/gui/text_edit.cpp#L5039-L5045
It only happens if the search bar is invisible.

**Steps to reproduce:**
1. Copy this code into script editor:
```
func update_extents() -> void:
    pass
```
2. Double click `update_extents` and press Ctrl + F, so the search for `update_extents` will start.
3. Press Escape to close search and make sure the text is unselected.
4. Place the cursor between `n` and `t`
5. Press Shift + F3

**Comment by alexey-makarenko** [comment]
6a842fb commit adds another reproduction steps (which are not valid before the fix), but infinite loop stays the same.
1) Create or open a script file with content:
```
123
123
```
2) Ctrl+F and type _23_
3) Press Shift + F3 or use buttons on search toolbar to search_prev

Not sure, should I create another Issue, or we can just reopen this one?
