### ISSUE TITLE
Missing Libraries while compiling android templete from mac

### ISSUE THREAD

**Issue by mani144** [godotengine/godot#31320]
**Godot version:**

3.1.1

**OS/device including version:**

Macbook pro

**Issue description:**

I usually compile using Linux or Windows but when i tried to use mac to compile android i faced a problem. there is many missing libraries that i need to install to make it compile, however, i found out that there is a missing library that i cant install no matter what. the library is on
 thirdparty/libsimplewebm/OpusVorbisDecoder.cpp:27:10: fatal error: 
      'vorbis/codec.h' file not found
#include <vorbis/codec.h>

i tried to install vorbis by so many ways , none of them worked . i even used brew vorbis-tools ...etc

is there a way to get vorbis for mac os ?

**Comment by mani144** [comment]
it seems the problem is related to module building, with the right option this problem is not there... for future ref: if you faced this problem check the modules that u r compiling it with

**Comment by Calinou** [comment]
@mani144 Is this bug caused by a third-party module? If so, please report it on the module's repository :slightly_smiling_face:

You could also post the solution here, so that other people can learn from it.

**Comment by mani144** [comment]
> @mani144 Is this bug caused by a third-party module? If so, please report it on the module's repository 🙂
> 
> You could also post the solution here, so that other people can learn from it.

i would if i knew the purpose of each module i just removed a couple of them till it worked, it seems there is some dependences and some modules does not work with android ... and i know that you can learn the default modules for android by using `scons android --help` , but  there is no current way to know what modules your game is using.

**Comment by akien-mga** [comment]
You don't need to install vorbis, you just need not to disable it...

The webm module needs the vorbis module,so if you want to disable the latter (i.e. no music), the also disable the former (no video).
