### ISSUE TITLE
normalmap texture compressed "VideoRam" different than the other compression modes

### ISSUE THREAD

**Issue by puthre** [godotengine/godot#31324]
**Godot version:**
3.1.1
**OS/device including version:**
Linux Ubuntu 18.04

**Issue description:**
Texture imported as normalmap with compression mode "VideoRAM" seem to have inverted channels (green and blue?)
Here is my original PNG.

![3x4_normals](https://user-images.githubusercontent.com/38382/62873226-efb41f00-bd16-11e9-8d82-375dee73b76e.png)
Here is the geometry rendered with a shader that outputs the normal texture in the color channel .
![lossless](https://user-images.githubusercontent.com/38382/62873299-0e1a1a80-bd17-11e9-96e6-8da5a830307c.png)
Here is the same but with the normal map texture imported as VideoRam Compressed (nromal map -> enable)
![Screenshot_2019-08-12_15-23-36](https://user-images.githubusercontent.com/38382/62873305-12463800-bd17-11e9-8bc4-3d00d691d3c2.png)

The shader I'm using:

shader_type canvas_item;
render_mode unshaded;

uniform sampler2D normal : hint_normal;
void fragment() {
COLOR =  vec4(texture(normal,UV).x,texture(normal,UV).y,texture(normal,UV).z,1.0);

}

**Comment by Calinou** [comment]
When using video RAM compression, Godot converts normal maps to the more efficient RGTC format (Red-Green Texture Compression).

**Comment by puthre** [comment]
> When using video RAM compression, Godot converts normal maps to the RGTC format (Red-Green Texture Compression). It's more efficient as it only contains 2 color channels instead of 3. The rendering engine handles it in a transparent manner by "reconstructing" the 3rd channel or something along those lines.

Well, if that's the issue then it should at least warn you that the results of the compression are not even close to what you input.

But after some more investigations I don't think that is the issue but the fact that Z is reversed when Video Compresssed. 
if I show the color as:

COLOR =  vec4(texture(normal,UV).x,texture(normal,UV).y,1.0 - texture(normal,UV).z,1.0);

it looks fine

**Comment by puthre** [comment]
... but only on desktop, on android is NOT reversed.

**Comment by CptPotato** [comment]
> But after some more investigations I don't think that is the issue but the fact that Z is reversed when Video Compresssed.

It might seem like that because the z channel of normalmaps is close to 1.0 but Calinou is right: The z channel of normalmaps can be omitted and calculated in the shader as `sqrt(1.0f - x * x - y * y)` since normalmaps usually store unit vectors.

**Comment by puthre** [comment]
> > But after some more investigations I don't think that is the issue but the fact that Z is reversed when Video Compresssed.
> 
> It might seem like that because the z channel of normalmaps is close to 1.0 but Calinou is right: The z channel of normalmaps can be omitted and calculated in the shader as `sqrt(1.0f - x * x - y * y)` since normalmaps usually store unit vectors.

Probably this is how is already computed from the other components, but negative on desktop and positive on android.

**Comment by CptPotato** [comment]
What I meant is that nothing is inverted. You're simply getting 0 as z component since it is not stored in the normalmap with this compression setting.

**Comment by puthre** [comment]
> What I meant is that nothing is inverted. You're simply getting 0 as z component since it is not stored in the normalmap with this compression setting.
> 
> The difference in android is probably because it doesn't support the compression format and falls back to another one.

Ok, it makes sense. This should be documented somewhere as there is no way you could guess that when you compress with "Video RAM" it will zero out the z component.

**Comment by Calinou** [comment]
This was documented in https://github.com/godotengine/godot-docs/pull/2705, closing.
