### ISSUE TITLE
Add safe comparison operator (===)

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#31331]
**Godot version:**
3.1.1.stable.official

**Issue description:**
At this point, the `==` operator can only compare values of the same type:
```gdscript
var x = 2
print(x == true) # Error: Invalid operands 'int' and 'bool' in operator '=='
```

This is absolutely the right decision, but sometimes it can be inconvenient. For example, if a function returns a value of an arbitrary type, you have to check both the type and the value.
```gdscript
var res = my_func()
if res is bool and res == false:
    do_something()
```

I propose to add the operator `===`, which allows you to compare the value of any type with the value of any type. Herewith:
1. If `A` and `B` are values of different types, then `A === B` is always `false`.
2. If `A` and `B` are of the same type, then `A === B` is always equal to `A == B`.

Then the condition in the example will be a little easier:
```gdscript
var res = my_func()
if res === false:
    do_something()
```

P. S. And still need the opposite operator, of course.
P. P. S. You can think about the syntax of the operator.

**UPD.** `my_func()` can return a value of any type (e.g. a string or a boolean). And in this case, I need to check that the function returned false, not `""` or `0`, for example.
**UPD 2.** Although now I think it's better to change the behavior of the `==` operator. (#26375)

**Comment by dalexeev** [comment]
```gdscript
var x = 2
print(x == "2") # Error: Invalid operands 'int' and 'String' in operator '=='
```


In Python:
```
>>> 2 == '2'
False
```
However, no errors.

**Comment by KoBeWi** [comment]
Related: #26375

**Comment by dalexeev** [comment]
Although now I think it's better to change the behavior of the `==` operator.
I think the issue should be seen as a potential duplicate.

**Comment by aaronfranke** [comment]
> ```
> var res = my_func()
> if res is bool and res == false:
>     do_something()
> ``` 

Alternatively:

```
var res: bool = my_func()
if !res:
    do_something()
```

**Comment by dalexeev** [comment]
1. This does not always work as expected:
```gdscript
var x = "abc"
var res: bool = x
print(res) # prints 'abc'
print(res == true) # Error: Invalid operands 'String' and 'bool' in operator '=='
```

```gdscript
var x = null
var res: String = x
print(res) # prints 'Null'
print(res.length()) # Error: Invalid call. Nonexistent function 'length' in base 'Nil'
```

2. `my_func()` can return a value of any type (e.g. a string or a boolean). And in this case, I need to check that the function returned `false`, not `""` or `0`, for example.

**Comment by aaronfranke** [comment]
@dalexeev That's really weird, I can confirm this behavior, but that's definitely a bug. @vnen You should check this out, it seems that typed GDScript is not working at all here.

**Comment by dalexeev** [comment]
```gdsript
static func eq(a, b) -> bool: # a === b # a ?= b # a =?= b
    return typeof(a) == typeof(b) and a == b
```

**Comment by dalexeev** [comment]
```gdscript
static func eq(a, b) -> bool: # a === b # a ?= b # a =?= b
    return typeof(a) == typeof(b) and a == b
```

**Comment by zkmark** [comment]
It's 2023, couldn't they add that very important functionality in godot 4?

**Comment by dalexeev** [comment]
* See also godotengine/godot-proposals#6092.

There is [`is_same()`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-is-same) global function.
