### ISSUE TITLE
Crash: on open project

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#3133]
He worked with the project. All was good. After a while began to fall. He gathered the latest version of the editor of the repository and found that the project began to fall steadily at the start. This happens not for the first time.
For experimentation rolled his project to the latest version from the repository. And the project has ceased to fall.

godot Latest commit dfd7bdb
OS: win 10

prj: https://yadi.sk/d/rseVn2semU87H

**Comment by kubecz3k** [comment]
I compiled dfd7bdb00528eb9a45e21a5c99d0e76bd642e74c and downloaded your project, unfortunately everything works fine... I can't reproduce this behaviour on linux...  
When exactly it is crashing? Is it the game crashing or the editor itself? What message is in the console?
Maybe it's os related bug, or eventually related somehow to Godot configuration? Have no idea.

**Comment by ret80** [comment]
I can not check under linux. But under windose played 100%.
It occurs when you open the project. If you open the project in the editor, then after a couple of seconds after the project opens the editor falls.
Build the project using "visual studio 2015" and "minGW" under Linux. The result is the same. Log do not know where to look.

**Comment by ret80** [comment]
Upgrade to c4f0c3d and it worked.
