### ISSUE TITLE
2D viewport is not fully cleaned up when closing scenes

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#31332]
**Godot version and OS:**
v3.1.1.stable.official x64, Ubuntu
Radeon RX 470/480/570/570X/580/580X
Kernel driver in use: amdgpu
Kernel modules: amdgpu
No additional drivers installed (clean install of Ubuntu)

**Issue description:**
When closing a 2D scene in the editor, some visual elements stay visible until zooming or scrolling the 2D Viewport.

Looks like this was fixed [here](../commit/0120f0473f6e5e6e5dc08e8134691a3b051ae554) (see related issue #5977) but it's somehow still here in v3.1.1:

![bug](https://user-images.githubusercontent.com/10872697/62891216-741d9680-bd45-11e9-8c32-f7beac14a948.png)

**Comment by sparkart** [comment]
Could you upload an example project? I didn't find any problems in both 3.1 and current master branch.

**Comment by char0xff** [comment]
Sure, but it's really easy to reproduce:
Create a scene, add a Sprite or anything, move it a bit, save the scene, close it. If the bug does not appear, reopen the scene and close it.
If you can't reproduce, maybe it's about OS / GPU?
It happens to me with both GLES2 and GLES3.

Example project:
[example.zip](https://github.com/godotengine/godot/files/3495548/example.zip)
Steps:
* Simply close the scene
You will see the Position2D symbol stays there until refreshing the viewport.

**Comment by sparkart** [comment]
Still can't reproduce the problem. It could be because you have a clean install and don't have the correct/updated drivers for your graphics card.

**Comment by akien-mga** [comment]
Can't reproduce either on Mageia 7 x86_64, tested various 3.0.x, 3.1, 3.1.1 and master.

**Comment by char0xff** [comment]
I had indeed some problems with VLC too, so I guess it's on my end.
