### ISSUE TITLE
Retina iOS. Screen(Viewport) is croped

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#3134]
On my ipod5 with retina display with resolution 1136x640 the viewport is only 960x640. I'am not ios developer but I try this method http://www.david-amador.com/2010/09/setting-opengl-view-for-iphone-4-retina-hi-resolution/
but it not help..

**Comment by ealataur** [comment]
![img_20151225_142838](https://cloud.githubusercontent.com/assets/7677575/12002641/6e8ba5b4-ab14-11e5-980e-df1d51d9f6f6.jpg)

**Comment by punto-** [comment]
you need to add a splash screen to your xcode project for that resolution
(and all the resolutions you want to support). We ahould do this for the
template xcode project we use, with placeholders so people can replace them
(also al, the icons). Also if I'm not mistaken the latest xcode has a way
to make a generic splash screen that supports all resolutions, using a
different thing for the entry point (I don't remember what they're called)

**Comment by ealataur** [comment]
Thank you! It works
