### ISSUE TITLE
[Docs] accessing object properties by Autoload singleton

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot#31344]
Godot 3.1.1.stable.official

Linux Mint 19.2

If a Autoload-singleton is called on an object,
how can a property of the object be accessed (set/get) by the function of the Autoload script?

e.g.:
in object script:
`self.AutoloadScript.move(vector2(x, y))`
in AutoloadScript:
`func move(movement):`
 `Object.position += movement`
What do I have to use instead of "Object", if I want to get/set the position property of the Object?

Or, if I use return:
in object script:
`self.AutoloadScript.move(position, vector2(x, y))`
in AutoloadScript:
`func move(pos, movement):`
`pos += movement`
`return pos`
How can I set the position of the object to the return?

I'm pretty new to programming, like probably a lot of godot users, so although there might be a simple way, which every programmer knows about, I didn't find any explanation on this matter in the documentation.
If there is a simple way of doing this, could it be added or made more visible in the docs?

**Comment by dioptryk** [comment]
To be honest, I'm at loss at what you're trying to do here. Are you creating a singleton as some kind of object controller? What do you mean that "Autoload-singleton is called on an object"?

If you want a script to control another object, just pass the object reference as function argument, like so:

```
func move_obj(obj, destination):
  obj.position = destination
```

But, unless you want to have some kind of centralized logic for all objects/nodes, why not program the movement in the object script itself?

**Comment by TrickMe** [comment]
> Are you creating a singleton as some kind of object controller?

Yes.
Actually I'm trying to call the same function (singleton) on multiple objects simultaneously.
I want to be able to call that function on the object from any third-party script, which is not attached to the object and nether is autoloaded.

> What do you mean that "Autoload-singleton is called on an object"?

It should work like e.g. look_at ( Vector2 ), move_local_x ( float  ), or rotate ( float ).
`Node2D.rotate( float )` can be called from anywhere "on the object". I don't know the correct term.


> But, unless you want to have some kind of centralized logic for all objects/nodes, why not program the movement in the object script itself?

Because, it would increase memory usage.
Instead I'm trying to attach a script with vars to the objects and modify the vars via autoload singletons.

Sorry if i use unfamiliar terms.
I'm just trying not to use more familiar terms in a possibly wrong way, until I really understood their exact meanings.
If you use a more correct terminology, I'm sure I will understand.

**Comment by TrickMe** [comment]
If, e.g. look_at ( Vector2 ), move_local_x ( float ), or rotate ( float ), are declared in Node2D, then this is not the functionality that I want.

Thinking about it, this is maybe not as simple as I thought, even with object-oriented languages.
I'm closing this now and make a feature request, once I find a way to better express the desired functionality.
