### ISSUE TITLE
Better support for 2D (HUD elements) in 3D environment

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot#31352]
If I'm being stupid (it happens) or this is a duplicate, please let me know and I'll close this. This comes up in Redit and Q&A from time to time. 

As best I can tell, there are two approaches when one wants text or other 2D content to follow 3D nodes in 3D space:

1. Put your 2D content under a Viewport, make a viewport texture, apply that texture to a "native 3D" object. [I may have details slightly wrong, but I think that is the idea.]
2. Use Camera.unproject_position() to convert 3D target node to 2D viewport coordinates, then update 2D content position every frame to follow 3D node.

Both of these are excessively complicated to program and (I suspect) not sufficiently performant for my needs. I have a solar system simulator with 1000s of Spatial nodes. Having each text label calculate its own 2D position every frame via GDScript (method 2) seems like it will be a frame-killer. I don't have much hope either that my computer can handle 1000s of individual viewports (method 1). To be fair, I haven't tested these yet, but my sim is already at the bleeding edge of what Godot can do so I am looking for more optimal solutions.

Well, for my own specific needs I have dodged both methods above. Instead, I convert text items to images (outside of Godot) so that I can apply them directly to a quad mesh. This is not a good general solution.

From a user point of view, the simplest and most intuitive approach would be this: **If I add a 2D node as child of a 3D node, it will follow that item in 3D space**. I can't think of any backward compatibility problems with this approach (why else would one put a 2D node under a 3D node?) but I might not have thought of something.

**Comment by Zireael07** [comment]
If your viewports are very small, you can probably go with method 1.
I am using method 1 in my race game, twice for every car (once for a UI label above the car, once for the nameplate on the back), and I have yet to see problems. Granted, I don't have many cars yet, but 4*2 is already 8 viewports plus one more for the player's rear view mirror...

**Comment by Calinou** [comment]
> Both of these are excessively complicated to program and (I suspect) not sufficiently performant for my needs. I have a solar system simulator with 1000s of Spatial nodes. Having each text label calculate its own 2D position every frame via GDScript (method 2) seems like it will be a frame-killer. I don't have much hope either that my computer can handle 1000s of individual viewports (method 1; to be fair, I haven't tested this yet).

As for this particular use case, you could optimize it by hiding 2D elements that would be too small to be readable (while not calculating their position). This is the case for 3D elements that are outside of the viewport or too far away.

**Comment by dioptryk** [comment]
There are more approaches available... For example, render all names to textures _once_ (using Viewports or whatever), get the image data, then attach the newly created textures to 3D sprites, that are set as _fixed size_ in material properties. You don't have to have 1000s Viewports this way, but just one, a kind of "label renderer" - should work nicely for your case. If you need to change the label, then you simply recreate the specific texture. The only problem is that you'll have many small textures, but you can go around it by using one big texture with all the names. Then it's just a matter of calculating UVs for each sprite.

**Comment by Zireael07** [comment]
@dioptryk: That's kinda what I do, render a name to texture once and attach the texture to a 3D quad. But from my experience, for rendering a name for a texture, I need a viewport even if I only render once and never redraw. I wonder if it's possible to drop that one-use viewport somehow?

**Comment by dioptryk** [comment]
@Zireael07 The Viewport will be small, so the resources usage should be minimal, I think there's no problem with having it around (you can check profiler for specifics) - or you can free() it after it renders all the labels (but then if you need to redraw a label you'll have to create it again). You can also prepare an empty image and draw directly to it, creating the texture afterwards, so no viewport, but then it's just pure text, no fancy labels ;)

**Comment by dioptryk** [comment]
@charliewhitfield I don't think that connecting 2D to 3D nodes should work just like that, simply because 2D and 3D coordinate systems are different and you don't necessarily want label of width=100 to be size 100 in the 3D scene... These are different worlds and should be connected "graphically" through render textures and viewports, imo. The solutions presented in this thread should deal with your performance problems.

**Comment by raymoo** [comment]
There doesn't have to be a fixed correspondence between 2D and 3D coordinates. Just have the spatial node be some size, and have it specify (as a property) the corresponding 2D size.

Having one Viewport for rendering is sufficient for static textures, but not if you have multiple interactive elements.

**Comment by charliewhitfield** [comment]
@dioptryk, Thanks! It's a workaround that will solve my needs. It certainly addresses my performance concerns.

However, I don't think this is a good general solution due to programming complexity. It's even more obscure. If this is really an edge-case game design need, then so be it. We can close the thread.

If folks think it is a more general need, then surely we should have some solution easier than writing our own "gdscript label renderer". I'm not particularly attached to my suggested solution above (about 2D nodes under 3D nodes). Just thought I'd throw out an idea.

**Comment by dioptryk** [comment]
@charliewhitfield you're welcome, though I don't think, that calling such a simple and common technique "obscure" is justified ;-)

**Comment by mhilbrunner** [comment]
Closing as per the above, and lack of consensus on this. If you still feel there is enough demand for this, consider opening a proposal on the proposals repository. :)

**Comment by msbritton** [comment]
# This code block is part of a script that inherits from Spatial.
# `control` is a reference to a node inheriting from Control.
control.visible = not get_viewport().get_camera().is_position_behind(global_transform.origin)
control.rect_position = get_viewport().get_camera().unproject_position(global_transform.origin)

**Comment by Calinou** [comment]
For reference, there's now a proposal tracking this: https://github.com/godotengine/godot-proposals/issues/3219
