### ISSUE TITLE
Change Path to Name and set script name for Built-in Script directly

### ISSUE THREAD

**Issue by 2dvision** [godotengine/godot#31364]
Is it possible to change Path to Name in Attach Node Script window, when Built-in Script toggle is on? User could rename Built-in Script directly.

![bult-in script name](https://user-images.githubusercontent.com/16509592/62975156-0b124d80-be2f-11e9-803e-9f6c0c0b695e.jpg)

**Comment by TheDuriel** [comment]
Do add on to this, for non built in scripts: Seperating the file name, from the path, might come in handy as well. _typically_ the preset path is fine, (for example when creating a script in a scene, it will be the path of the scene) but the filename might need adjusting. This can be quite a hassle to do with the tiny filepath box, and pulling up the filebrowser seems a bit excessive.
