### ISSUE TITLE
Make separate export templates available for download

### ISSUE THREAD

**Issue by 2dvision** [godotengine/godot#31363]
Is it possible separate export templates for download? For example, I just use the android template and I don't need others. I must download 430 MB for android template. What do you think?

Something like this in Godot engine:

![export templates 01](https://user-images.githubusercontent.com/16509592/62974339-427ffa80-be2d-11e9-9c21-9e2b976833a0.jpg)

on website:

![export templates 02](https://user-images.githubusercontent.com/16509592/62974364-4dd32600-be2d-11e9-86ab-089ce07f9363.png)

**Comment by Calinou** [comment]
This is technically possible, but we would have to build and provide separate `.tpz` archives on the website. Also, we'd need to adapt the current "Installed" detection to work on a per-platform basis.

**Comment by Siberian-Cat** [comment]
This would be cool. Maybe this can be a good thing

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/647, as feature proposals are now tracked on the Godot proposals repository.
