### ISSUE TITLE
PanoramaSky automatically applies filter to texture after reloading the scene or changing radiance size

### ISSUE THREAD

**Issue by grusad** [godotengine/godot#31372]
**Godot version:**

Godot 3.1 -stable

**OS/device including version:**

Linux Mint 19.*something*

**Issue description:**

I import a texture without the filter flag enabled and its all fine. Once applied to the Worldenviroments panoramaSky the texture gets filtered anyway. At first glance it looks like it is working because in the editor it gets filtered. But once I close the scene in the editor and reopen OR just start the game the texture is filtered.

So apparently the WorldEnviroment or the PanoramaSky automatically enables the filter flag anyways.

**Steps to reproduce:**

1. Import a texture with filter flag off.
2. Create a scene with a worldEnviroment and give it a PanoramaSky resource.
3. Give the PanoramaSky the imported texture.
4. Close and reopen the scene OR play the game.
5. A filtered skybox, not pixelated as I wanted it to be :(

**Minimal reproduction project:**

**Comment by EzraT** [comment]
Can confirm, this issue is still present in 3.2.1.

![image](https://user-images.githubusercontent.com/781121/79054074-53923d00-7c42-11ea-95b6-3ddcf8982516.png)

This effectively makes PanoramaSky useless for 3D Pixel art games.

**Comment by clayjohn** [comment]
@Ezrat GLES2 or GLES3?

**Comment by EzraT** [comment]
@clayjohn Both.

**Comment by clayjohn** [comment]
@Calinou Were you able to reproduce? I just tested it out and both GLES2 and GLES3 are working fine. 

Zoom in to see the difference.
![Screenshot (160)](https://user-images.githubusercontent.com/16521339/79056434-78b78900-7c0b-11ea-9ab4-746514706568.png)

![Screenshot (161)](https://user-images.githubusercontent.com/16521339/79056437-7a814c80-7c0b-11ea-9c82-590cdc312a19.png)

**Comment by EzraT** [comment]
@clayjohn Either re-open or run your scene to reproduce the issue.
Changing radiance size also works.

**Comment by clayjohn** [comment]
@EzraT Oh! That's very helpful then. I bet the filter just isnt getting reset after creating radiance maps.

**Comment by clayjohn** [comment]
@EzraT Thanks for the extra info. It turned out to be an easy fix. I have submitted a PR :)

**Comment by EzraT** [comment]
@clayjohn Many thanks for the fix! Happy to help. :]

**Comment by akien-mga** [comment]
Fixed by #37815.

**Comment by EzraT** [comment]
@clayjohn @Calinou 
Could this issue be re-opened?
I think this problem has re-surfaced in one of the later versions, I'm getting this same incorrect behavior again in 3.2.3.

**Comment by clayjohn** [comment]
I can reproduce. Fortunately, this issue only affects GLES3 right now which should make the issue easier to track down.

**Comment by clayjohn** [comment]
@EzraT PR made :)

**Comment by EzraT** [comment]
Thanks! @clayjohn

**Comment by akien-mga** [comment]
Further fixed by #43264.
