### ISSUE TITLE
Buttons needs to be updated after deleting project in Project Manager

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#31377]
**Godot version:**
3.2.dev.custom_build. 3ea33c0e4
Happens probably since d3652887df0bbe5876dd7b64e741b3c5b14e0cad

**Issue description:**
When user delete a project, then buttons should be updated.
![file](https://user-images.githubusercontent.com/41945903/63043436-87a73980-becc-11e9-887e-4666b028f945.gif)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/6fedb2bf28d613b781d38a1b374ee1917bca0047.
