### ISSUE TITLE
Can godot support a large dynamic world with a lot of moving lights?

### ISSUE THREAD

**Issue by blockspacer** [godotengine/godot#31388]
[**question**] Can we support a lot of moving lights in large dynamic world (like lights from torches, vehicles e.t.c.)? ( Think about dynamic world like godot-voxel, where players can change everything https://github.com/Zylann/godot_voxel )

Godot uses forward renderer, so it can`t handle a lot of dynamic lights?https://godotengine.org/article/godot-3-renderer-design-explained

Also can godot handle fully dynamic scene without lights passing through dynamic objects? ( issue like in godotengine/godot#26838 , but lights can`t be baked )

[**alternative question**] Is is possible to overcome forward renderer & voxel cone tracing (VCT) issues? (For example, can we handle doors/windows in other ways? Like have two versions of lightprobes near doors/windows with one for open and one for closed, etc. https://dev.gamedev.net/forums/topic/702924-what-gi-is-usable-right-now/)

[**alternative question**] Is is possible to change renderer pipepline in godot to deferred shading?

> [Quote] The reason we chose deferred shading instead of deferred lighting or forward rendering was mainly due to the large number of dynamic lights we had to support in-game and also because the amount of geometry rendered which prohibited us from rendering it more than once. From https://interplayoflight.wordpress.com/2015/04/08/the-rendering-technology-of-skysaga-infinite-isles/

[**alternative question**] Is is possible to add Scalable Realtime Global Illumination?
https://github.com/godotengine/godot/issues/31289

[**alternative question**] Is is possible to add DDGI support (realtime global illumination without precompute)?
https://github.com/godotengine/godot/issues/31405

**Comment by clayjohn** [comment]
Closing as it is a bunch of questions that are out of date. 

For future reference, it is best to ask these questions on a community channel (discord, reddit, Facebook, Q&A) if you want an answer. This space is for bug reports only. 

To answer your man question: Godot 3.2 doesn't support open worlds with many dynamic lights well. Meshes have a limit of 8 lights.

In Godot 4.0, we hope we can support larger, more dynamic worlds as we use clustered lighting and reduz is currently working on a dynamic global illumination system, similar to DDGI.
