### ISSUE TITLE
High framerate on idle in editor

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#31384]
version: v3.2.dev.calinou.82a86e807 (nightly build from a few days ago)

I'm not sure if this is intended but when I don't interact with godot the reported framerate in the 3D viewport jumps to 140 fps:
![grafik](https://user-images.githubusercontent.com/3957610/63082678-283a3f80-bf47-11e9-8e65-b3f77ab2e417.png)

When moving over some of the buttons the framerate decreases a bit. If I move the camera in the 3D viewport the fps stay somewhere between 30 and 50. Overall the reported framerate seems very unstable.

**Comment by Calinou** [comment]
The FPS counter can only really be accurate if **Interface > Editor > Update Continuously** is enabled. Otherwise, the window will only update when something changes in the viewport.

**Comment by CptPotato** [comment]
I see. With it enabled it stays at a constant 60 fps.
Still a bit strange that it reports such a high framerate on idle (without update continously).

**Comment by Calinou** [comment]
@CptPotato It likely reports a value around 144 because that's the default editor FPS cap when V-Sync is disabled :slightly_smiling_face:

It can be changed in the Editor Settings by tweaking **Interface > Editor > Low Processor Mode Sleep Usec**. This defines how many in microseconds

**Comment by CptPotato** [comment]
> It can be changed in the Editor Settings by tweaking **Interface > Editor > Low Processor Mode Sleep Usec**. This defines how many microseconds the editor has to sleep between frames. The default value (6900) is roughly equivalent to 144 FPS.

Apparently you have to reopen the editor for that setting to take effect but you're right. Thanks for the hint.

**Comment by Calinou** [comment]
This is now fixed with the new FPS indicator in the `master` branch (which is more accurate and displays CPU/GPU time separately), closing.
