### ISSUE TITLE
Optional automatic re-import of resources

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#3139]
Some engines like Unreal Engine 4 offer an option to automatically re-import any resources that are modified. Currently, Godot will notify you when some of your assets are modified, but won't automatically re-import them.

I guess an option to re-import them automatically would make sense.

**Comment by reduz** [comment]
Yeah, now that we can probably do away with the 3D import/merge options it
could be easier

**Comment by Ace-Dragon** [comment]
Sounds good to me so long as we can be sure nothing in the scene breaks during the update process (ie. making sure all outstanding import/re-import issues are fixed), it will make iterating that much quicker.

**Comment by bojidar-bg** [comment]
Hm, has the situation changed since 2015? :smile:

**Comment by reduz** [comment]
This was implemented in 2.1

**Comment by vnen** [comment]
AIUI now it's automatic but not optional.

**Comment by akien-mga** [comment]
I'd propose to close it as fixed, since the current situation is now different to the one that prompted asking for an *optional* auto-reimport.
If some users have a need for disabling auto-reimport, they'll open a new issue against 2.1 or 2.2-dev.
