### ISSUE TITLE
PackedScene example should check return value of ResourceSaver.save

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#31393]
```
# create the objects
var node = Node2D.new()
var rigid = RigidBody2D.new()
var collision = CollisionShape2D.new()

# create the object hierarchy
rigid.add_child(collision)
node.add_child(rigid)

# change owner of rigid, but not of collision
rigid.owner = node

var scene = PackedScene.new()
# only node and rigid are now packed
var result = scene.pack(node)
if result == OK:
    ResourceSaver.save("res://path/name.scn", scene) # <=== should check return value

```

https://docs.godotengine.org/en/3.1/classes/class_packedscene.html#description

https://docs.godotengine.org/en/3.1/classes/class_resourcesaver.html#class-resourcesaver-method-save

**Comment by Calinou** [comment]
For the purposes of the example, would it be sufficient to print an error message if the result of `ResourceSaver.save()` is not `OK`?

**Comment by mitchcurtis** [comment]
> For the purposes of the example, would it be sufficient to print an error message if the result of `ResourceSaver.save()` is not `OK`?

That's what I was hoping for. :)
