### ISSUE TITLE
Custom drawing not updating

### ISSUE THREAD

**Issue by Migar4** [godotengine/godot#31403]
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
I am trying to change the radius of a half circle custom drawing depending on the mouse position so whenever I try to move my mouse the half circle should change it's radius by updating but it never happens the half circle only takes the initial radius although the value of the radius actually change when I move the mouse I tried having `tool` at the beginning as well to no avail

**Steps to reproduce:**
here's the code
```
extends Node2D

var rotation_angle = 50
var nb_points : int = 32
var points_arc : PoolVector2Array = PoolVector2Array()
var angle_point : float

var center : Vector2
var radius : float
var angle_from : float = 90
var angle_to : float = 0
var color : Color

func _ready():
    set_process(true)

func _draw():
    center.y = 0
    radius = abs(get_global_mouse_position().y)
    print(radius)
    center.x = radius
    angle_to = 90
    angle_from = 270
    color = Color(1,0,0)
    _draw_arc(center, radius, angle_from, angle_to, color)


func _process(delta):
    update()

func _draw_arc(center, radius, angle_from, angle_to, color):
    for i in range(nb_points + 1):
        angle_point = deg2rad(angle_from + i * (angle_to - angle_from) / nb_points - 90)
        points_arc.push_back(center + Vector2(cos(angle_point), sin(angle_point)) * radius)
    for index_point in range(nb_points):
        draw_line(points_arc[index_point], points_arc[index_point + 1], color)
```

**Comment by KoBeWi** [comment]
If you want it to redraw in editor, you need the `tool` keyword. However, you need to reload the scene before the script starts running (also it can't be built-in).

**Comment by Migar4** [comment]
> If you want it to redraw in editor, you need the `tool` keyword. However, you need to reload the scene before the script starts running (also it can't be built-in).

Thanks for the answer but
how do I reload only that scene? when I use `get_tree().reload_current_scene()` the root gets reloaded when I am running only the half circle scene it is fine but when the game is running when the half circle scene is a child everything from the top is getting reloaded.
thanks

**Comment by KoBeWi** [comment]
From editor menu. Scene -> Reload Scene (or something like that).

**Comment by Calinou** [comment]
Closing, as this is likely resolved by following the advice above.
