### ISSUE TITLE
alias for rset and rpc to be more clear

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#31404]
rset and rpc are confusingly named I suggest a better name for them

net_call()
net_set()
mayber a net_get() as well?

**Comment by bojidar-bg** [comment]
Linking to tracker: #16863

Keep in mind that multiplayer does not need to be over a network. For example, you might have multiplayer over bluetooth. Should the functions be called `blue_call` and `blue_set` then?

`net_get` is probably a bad idea, as it would have a high latency before the response is received, while being mostly useless in both server-authoritative and peer-to-peer games.

**Comment by Zylann** [comment]
`remote_call()` / `remote_set`?

**Comment by Shadowblitz16** [comment]
I like Zylann's idea
whatever to make them more clear.

**Comment by Calinou** [comment]
Closing in favor of #16863.
