### ISSUE TITLE
calling grab_focus() during mouse_entered signal causes !is_inside_tree() error

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31409]
**Godot version:**

3.1

**Issue description:**

![image](https://user-images.githubusercontent.com/44248915/63166691-762a7280-c02f-11e9-915b-609d08123f59.png)

All focus methods are affected in this example, grab, grab_click, and release_focus.

**Steps to reproduce:**
Run the provided project. Mouse over the panels.
Relevant code is on lines 140 and beyond.
The goal is to detect the mouse entering/existing, grab focus, then play an animation.

**Minimal reproduction project:**

[buttonlist.zip](https://github.com/godotengine/godot/files/3509487/buttonlist.zip)

**Comment by KoBeWi** [comment]
This looks like a problem with your scene. Not sure how you set object bindings via editor, but they don't seem to be working. The node you get as method's argument isn't the one you think. Try `print(child.name)` and you'll see its name is empty.

**Comment by TheDuriel** [comment]
node.connect(signal, self, func, [node])

i dont see how `node` could not be correct in this case.

**Comment by TheDuriel** [comment]
<.< Unless of course due to the fact that these connections are saved, it cant save the reference. Which is _weird_, that it would even be able to return a node in the first place.

I guess ill have to reconstruct the signals during _ready.

**Comment by KoBeWi** [comment]
I mean, the nodes on scene are already connected and doesn't seem like the connecting code is being called. (that might be because `add_child` and `add_child_below_node` aren't virtual, so you can't override them)

**Comment by TheDuriel** [comment]
The connections _stem_ from those calls. Add a new node to the scene and see for yourself.

**Comment by KoBeWi** [comment]
Right .-.

So in the end, assuming that you manage to save the node reference, isn't it basically the same as exporting a Node? AFAIK it's not possible. I guess you should pass a NodePath, not sure how to do this correctly though.

Anyways, the problem is not with the `grab_focus` in `mouse_entered`.

**Comment by sparkart** [comment]
> node.connect(signal, self, func, [node])
> 
> i dont see how `node` could not be correct in this case.

`add_child(_t)`

Tween is not a Control. Also, that seems to be the only place that code is being called, unless the example is incomplete. Inspecting the signals in the inspector, the extra call argument is empty.

**Comment by TheDuriel** [comment]
It looks like an issue with serialization of the signals.

I'll close this issue, and make a new one. Signals that have bindings which can not be saved, should print a warning when you do so.
