### ISSUE TITLE
move_and_slide() generates an error when KinematicBody2D moved from one scene to another

### ISSUE THREAD

**Issue by SoulForMachine** [godotengine/godot#31416]
**Godot version:**
v3.2.dev.custom_build.de8ce3e625e7

**OS/device including version:**

**Issue description:**
I use a scene with base node KinematicBody2D for the player. When changing scenes, I remove the player from the old scene and add it to the new scene, but I do not delete the instance of the first scene because I want to keep it around for later. After that, the first call to move_and_slide() in player script's _physics_process() causes an error to be displayed in the debugger:

> E 0:00:04:0903   Condition ' !body->get_space() ' is true. returned: 0
>   <C Source>     servers\physics_2d\physics_2d_server_sw.cpp:1078 @ Physics2DServerSW::body_get_direct_state()
>   <Stack Trace>  Player.gd:24 @ _physics_process()

After investigating, I found out that this happens because KinematicBody2D keeps a RID of the floor body on_floor_body, and when kinematic body is removed from a tree this keeps pointing to whatever floor body it was colliding with in an old scene. When the kinematic body enters the new scene, the first call to move_and_slide() will try to use that object and get it's Physics2DDirectBodyState since it is still valid, but since it has no space, it will print the above error.

This would have caused a crash as specified in issue  #23722, but this has been solved with pull request #24629 by adding the line that produces the above error:

`ERR_FAIL_COND_V(!body->get_space(), NULL);`

As mentioned in comments of the issue and PR, this prevents the crash but does not solve the issue and the error message is displayed.

I suggest that this should be solved by setting on_floor_body to empty RID in response to NOTIFICATION_ENTER_TREE:

```
void KinematicBody2D::_notification(int p_what) {
	if (p_what == NOTIFICATION_ENTER_TREE) {
		last_valid_transform = get_global_transform();
		on_floor = false;
		on_floor_body = RID();
	}
```

Please advise if this is a good solution. If it is, I'll create a pull request.

**Steps to reproduce:**
As described in the first passage of the issue description. I also attached a reproduction project.

**Minimal reproduction project:**
[MoveAndSlideTest.zip](https://github.com/godotengine/godot/files/3510244/MoveAndSlideTest.zip)

Just move left or right until you enter an area. This will trigger scene switch. After the scene is switched, there will be an error displayed in the debugger.

**Comment by sparkart** [comment]
Makes sense to me.

**Comment by gunwhalegames** [comment]
I'm not sure if I'm somehow violating github etiquette by posting on an older/closed thread but this issue still seems to exist for move_and_slide_with_snap()

**Comment by Calinou** [comment]
@gunwhalegames Please open a new issue with a minimal reproduction project attached.
