### ISSUE TITLE
Leak of VRAM and RAM when freeing a rigged 3d Model (GLES2)

### ISSUE THREAD

**Issue by Tugsav** [godotengine/godot#31412]
Godot version: 3.1.1.stable
Ubuntu 18.04.3 LTS

We noticed that our framerate were dropping slowly when running our game for a long time. The issue were tracked to a leak when freeing a 3D node with a mesh that is rigged with a skeleton.

Reproduction:
We have created a small project that reproduces the issue. Clone the project and open it up in Godot
https://github.com/Tugsav/GodotRiggedFreeingLeak.git
Next run it while monitoring your VRAM using a tool such as nvidia-smi. You should notice the VRAM usage going up. You should also be able to notice your regular RAM usage increasing.

The test scene will continiously instantiate a simple scene containing a skeleton, a mesh, and an animation. when a certain number of instances is reached it will start freeing the first ones so that a constant amount of instances are maintained.

Note that changing the instanced scene from the provided rigged_scene to a version without a skeleton rig (simply change the script to use the provided animated_scene instead) does not seem to cause the leak.
Also the leak does not occur on GLES3. only on GLES2

**Comment by akien-mga** [comment]
CC @clayjohn

**Comment by clayjohn** [comment]
I am able to reproduce in 3.1.1 and in current master. Also on my desktop with an NVidia GPU and my laptop with an integrated GPU, so it doesn't appear to be a driver issue. We are likely forgetting to free some GPU memory somewhere. I'll find out where.
