### ISSUE TITLE
Shape duplicating when set as a node and then accessed in scripts

### ISSUE THREAD

**Issue by Ijatsu** [godotengine/godot#3141]
Context:
StaticBody2D
--- CollisionShape2D

StaticBody2D is draggable
CollisionShape2D is on trigger

In script, if the shape is accessed by one way or another (StaticBody2D.get_shape(0).set_extents(...) or get_node("CollisionShape2D").get_shape().set_extents(...) in my case), all events produced on this collision shape (mouse enter, mouse event and mouse exit) will be duplicated with different shape_idx.

I don't know if this bug is caused by set_extents function specifically. I'll get as much duplicated event as I have called set_extents.

**Comment by reduz** [comment]
if you duplicate a node, the sub-resources are duplicated by default

**Comment by reduz** [comment]
er sorry, are shared by default

**Comment by Ijatsu** [comment]
I'm not duplicating anything

**Comment by reduz** [comment]
I'm not sure if I understand the problem.. can you make an example project?

**Comment by Ijatsu** [comment]
Sorry for the late, I'll provide sample code and outputs ASAP.

**Comment by Ijatsu** [comment]
My godot version is the latest at the time I write this comment. Compiled with the command "scons platform=windows bits=64"
Link of the project: 
https://mega.nz/#!sABCgbaR!YCAakMA4Qrya9mCo_toi19J4DKK1KwlDJdqEcB1ttQc


The scene's tree is:
Node2D
   Area2D 
      CollisionShape2D (trigger : true)
         shape: CircleShape2D of radius 5000

A script is given to the root Node2D, input_event of Area2D is connected to this script.
```gdscript
extends Node2D

func _ready():
	print(get_node("Area2D").get_shape_count()) # prints 0
	print(get_node("Area2D").get_shape(0)) # prints circle [CircleShape2D...]
	get_node("Area2D").get_shape(0).set_radius(5000) # mandatory to produce the bug
	print(get_node("Area2D").get_shape_count()) # still prints 0
	# print(get_node("Area2D").get_shape(1)) # optional, prints null object

func _on_Area2D_input_event( viewport, event, shape_idx ):
	if( event.type == 3 && event.button_mask == 1): # left click only to avoid being flooded by mouse move events
		print("mouse click event ", shape_idx) # will be called twice with shape idx = 1 and 0
```

Output with this code with one left click:
```
1
[CircleShape2D:XXX]
1
mouse click event 0
mouse click event 1
```

Output with the set_radius commented:
```
1
[CircleShape2D:XXX]
1
mouse click event 0
```

**Comment by Ijatsu** [comment]
Note: Instantiating this object 10 times will make this project crash.

**Comment by DualMatrix** [comment]
Tested in master, almost all of the functions in that script changed name since then so had to change the script a bit.

It worked properly now and printed only once.

**Comment by akien-mga** [comment]
Thanks, closing as fixed.
