### ISSUE TITLE
Autocompletion problems with the new list

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31425]
**Godot version:**
afecc0b

**Issue description:**
I can't believe no one reported it yet, but the autocompletion has a severe issue since the changes from #29626. Check this
![image](https://user-images.githubusercontent.com/2223172/63202955-af450000-c08c-11e9-998a-9d9c5c201b6d.png)
It's a very nice list without quotes and with icons looks cool and stuff. But how do I search that list? I mean, when I start typing something to filter options, the list disappears. Previously, all options started with ", so you had to write " and then whatever you wanted to search, otherwise you ran into #24077, which seems to still be true. Now when you write ", the list disappears too, so it's entirely impossible to filter it.

**Comment by akien-mga** [comment]
CC @Geequlim

**Comment by Calinou** [comment]
I think it makes more sense to display quotes for strings that can be completed, as it will be what you get after pressing <kbd>Tab</kbd>.

**Comment by KoBeWi** [comment]
I actually think it's better without the quotes. If only the filtering worked properly, it would be a nice fix for #24077.

**Comment by Geequlim** [comment]
The filter it does work in fact. But a new completion request is queryed when input new charactors so the  options are replaced by new completions.

I can restore the quotes in the options to make it as same as what 3.1 does (We have to manually input a quote to filter options as before).

But I'd like to avoid new completions request in this kind of situations (for NodePath files and signals)
