### ISSUE TITLE
OS test demo request

### ISSUE THREAD

**Issue by Max-Might** [godotengine/godot#3142]
Hello.

The OS class provides an abstraction layer over the platform-dependent code.
The engine now has code for something like 13 platforms.
It would be nice to have a demo that tests all (or most) of the OS class methods.
This way it would be much more easier to test and compare different platform implementations.
And also find bugs in the platform-dependent code.
It will also be very helpful when adding support for a new platform.

**Comment by bojidar-bg** [comment]
:+1:, esp. when considering some of them are unimplemented in all platforms.

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-demo-projects/issues/8
