### ISSUE TITLE
OS.get_system_time_msec() returns wrong value or different type of time

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3143]
test code
```
print("OS.get_system_time_msec() = ", OS.get_system_time_msec())
```

On android ``OS.get_system_time_msec() = -472413797`` > negative int
On windows ``OS.get_system_time_msec() = 324`` > only 0~999 int (only milliseconds of time)

and as far as I know, ``Variant`` does not have 64 bit int.
but some of function returns ``uint64_t`` in ``OS``.
doesn't it make bugs?

**Comment by reduz** [comment]
yeah this function was contributed and the way it was done wasnt as I
suggested, it should have been divided in 2 functions,

get_system_time_secs() # system time in seconds
get_system_time_msecs() # system time in milliseconds

due to the values returned being larger than 32 bits in milliseconds

**Comment by volzhs** [comment]
I found ``OS.get_unix_time()``.

> get_system_time_secs() # system time in seconds

this seems the same with ``get_unix_time()``
