### ISSUE TITLE
Tip of the day

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31430]
**Godot version:**
40640a0

**Issue description:**
There are some useful features in Godot that are well-hidden and it's not obvious how to make them more visible, like #29249 or #31415 (especially if done with shortcut). It would be cool to have a perfect UX, so every feature is accessible and obvious, but for some stuff it's just overthinking.

So I though, maybe a "Tip of the Day" window would help with some of these problems? It wouldn't probably hurt. A window that appears on startup and says random useful stuff about the editor and you can disable it if you know it all or want to keep the mystery and discover it yourself. Here's some random example:
![image](https://user-images.githubusercontent.com/2223172/63210465-eb10b180-c0ee-11e9-9134-67832547c927.png)

The tips could include some hidden shortcuts (like the mentioned reparenting thing), places where you can drag and drop stuff or useful editor settings (e.g. removing 2D limits).

**Comment by Jummit** [comment]
Could be made as a plugin.

**Comment by KoBeWi** [comment]
> Could be made as a plugin.

Why tho? It'd be useful to have this built-in.

**Comment by Zireael07** [comment]
I don't understand why telling the users how to use the core engine should be shipped out as a plugin?

**Comment by Jummit** [comment]
When I first saw this I just didn't really feel like it was Godot-ish enough to be built-in. Just my opinion though.

**Comment by nikhilCad** [comment]
This should be added with an option to turn it off,, things like this can piss off experienced guys.

**Comment by Calinou** [comment]
I think it's fine to have as something you explicitly reach for (e.g. **Editor > Tip of the Day...**), instead of something that pops up when you open the editor. It's much less annoying when you set up Godot on a new machine or similar :slightly_smiling_face:

**Comment by sparkart** [comment]
You could have a checkbox that disables it on startup.

**Comment by piratesephiroth** [comment]
tbh it's useless.
I have this in other software and after a few days it becomes just a fancy nag dialog that eveyone disables permanently.

**Comment by KoBeWi** [comment]
> This should be added with an option to turn it off,, things like this can piss off experienced guys.

> You could have a checkbox that disables it on startup.

That's on the example screenshot I gave and literally every example screenshot you can find in Google. Only GIMP seems to have done this differently.

> a fancy nag dialog that everyone disables permanently

The idea is that you just read all the tips once. You can go to next tip, so you can read all of them and never see the dialog again. Also if you disable it without reading, you have no right to complain that some feature is hard to notice, if it was in the tips :v

> Tips like that would only be viable if they were done like in BotW, showing up in unavoidable loading screens. Maybe you could show the tips while building big projects or importing many files?

It makes sense in games, but would be weird in a regular software. Also, you don't see these often enough. Maaaybe if code errors caused a game over screen... (XD)

I know that such dialog might be out of place in Godot or be an annoyance, but it is really hard to make some features visible (at least without redesigning everything). Alternatively, we could have this in the docs, called "1001 useful Godot features you don't know about" or something. But there are lots of awesome docs that most users don't read, because most users don't read the docs. That would be just another of them (and I can already imagine a post on Reddit saying "look at this pearl I found in Godot docs").

**Comment by piratesephiroth** [comment]
Be careful though. 
"for when you gaze long into the abyss. The abyss gazes also into you.”

![oh no](https://i.imgur.com/zOp9mxP.png)

**Comment by Calinou** [comment]
I'll close this issue due to lack of support (as seen in https://github.com/godotengine/godot-proposals/issues/15).
