### ISSUE TITLE
Documentation macros

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31433]
**Godot version:**
de4aabe

**Issue description:**
Soo, not sure how much is it possible, but #31119 inspired me to create this issue. I mean, look at this
https://github.com/godotengine/godot/blob/de4aabe89b7b68677f145f21c956183bbc92f686/doc/classes/Control.xml#L228
and this
https://github.com/godotengine/godot/blob/de4aabe89b7b68677f145f21c956183bbc92f686/doc/classes/Control.xml#L250
and also this
https://github.com/godotengine/godot/blob/de4aabe89b7b68677f145f21c956183bbc92f686/doc/classes/Control.xml#L309
oh, and don't forget this either
https://github.com/godotengine/godot/blob/de4aabe89b7b68677f145f21c956183bbc92f686/doc/classes/Control.xml#L327

See? It's basically the same text, repeated few times with single different word. It could be done with a format-supporting macro, like
```
<macro=get_stuff>Returns %s from assigned [Theme] with given [code]name[/code] and associated with [Control] of given [code]type[/code].</macro>
```
And then
```
<description>
    [get_stuff]an icon[/get_stuff]
</description>
```
The way it could work, upon reaching macro definition (which usually would be on the top), the parser could go through all of the text and replace all occurrences of this macro.

It would make the documentation more compact and easier to translate (cuz less text).

**Comment by HectorCastelli** [comment]
This does sound useful. Thanks for bringing this up.

I have created a copy of this on [godot-docs/#3235](https://github.com/godotengine/godot-docs/issues/3235) so it's on the correct repository.

**Comment by Calinou** [comment]
@HectorCastelli I think this issue should stay on the main repository as this is about adding additional syntax to the class reference XML. it has to be handled by the engine's C++ code.

**Comment by HectorCastelli** [comment]
@Calinou Thanks for pointing this out! I misunderstood the request at first. You are right.

**Comment by KoBeWi** [comment]
In the end, this can't stay on this repository, heh.

I opened a separate proposal: https://github.com/godotengine/godot-proposals/issues/890
Although I don't recall the macros being useful outside the examples I gave :I
