### ISSUE TITLE
Panel not rendered unless window is resized

### ISSUE THREAD

**Issue by ShrewdSpirit** [godotengine/godot#31446]
**Godot version:**

3.1.1

**OS/device including version:**

Archlinux kernel 4.19.62 Nvidia GTX 1050 v430 drivers

**Issue description:**

Whenever I instantiate a scene that contains a panel control, the panel doesn't render. I have custom resize handling script that only changes the root node's rect to match the new size and when I resize, the panel gets rendered fine.
Running the scene by F6 is ok.

**Steps to reproduce:**
Make a scene with panel control as root or as a child of control. Instantiate the scene inside another scene and add it to the current scene as child instead of replacing it. Running the project won't render the panel. I have tested it in two different projects.

[Here's a video describing how it looks](https://www.reddit.com/r/godot/comments/crpcys/panel_doesnt_render_on_first_load_but_renders/)

**Reproduction project:**
[Here](https://github.com/ShrewdSpirit/godot_issue)

Edit: I have added a CenterContainer as a child of such buggy panel and whenever it doesn't render, the center container doesn't align its children to center

**Comment by KoBeWi** [comment]
Reproduction project?

**Comment by ShrewdSpirit** [comment]
@KoBeWi edited.
Among all solutions people suggested on reddit only resizing the panel to viewport size in `_ready` worked

**Comment by KoBeWi** [comment]
Sooo, the Main control should be set to full size too. Then it works.

**Comment by ShrewdSpirit** [comment]
Oh I didn't notice that! Thanks for clearfying
