### ISSUE TITLE
New errors checks on ConfigFile::load() generate unnecessary error prints when file doesn't exist yet

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#31444]
**Godot version:**
3.2 master (86371b7), regression from #31077 (@qarmin)

**OS/device including version:**
Any

**Issue description:**
PR #31077 added missing return value checks for `ConfigFile::load()`, but missed the fact that this API can be used successfully even if `err != OK`, as it will return `ERR_CANT_OPEN` if the file can't be opened, which also occurs if the file doesn't exist.

Code that uses `ConfigFile` typically attempts to load files even if not present, so that they can be either edited or created and then re-saved. So in this case no error should be raised.

Current code raises errors all the time when you e.g. save a scene, as the project metadata for the scene doesn't exist yet. And the metadata is not created at all due to this early exit.

The `ConfigFile` API could maybe be changed to use a more specific error when the file can't be loaded because it doesn't exist, so that it can be treated as a harmless error (e.g. `ERR_FILE_NOT_FOUND`).

**Steps to reproduce:**
- Create a new project
- Create new scene, save it
- Check terminal

**Comment by Xrayez** [comment]
Stumbled upon this while testing #31111, project metadata was used for saving last language and template used, so new projects would emit this error but only once, which got me confused.
