### ISSUE TITLE
Stack Underflow (Engine Bug) when using yield completed

### ISSUE THREAD

**Issue by muchitto** [godotengine/godot#31455]
**Godot version:**
3.2-dev (https://github.com/godotengine/godot/commit/fb5e8b509b859f9e81d7b7c63086fb7e8dae5dd2)

**OS/device including version:**
Windows 10 x64

**Issue description:**
I was implementing a kind of state machine and ran into the `Stack Underflow (Engine Bug)` problem, which has been mentioned in issue #30269. It seems to occur at specific times when using the `yield(gdfunctionstate, "completed")` kind of code.

**Steps to reproduce:**
Open the project, run and press `space` (or any of the default "ui_accept" action keys).
All the code in the minimal reproduction project is in the `Main.gd` file:

```
extends Node2D

class Runner:
	signal ContinueExecution()
	
	func continue_excution ():
		emit_signal("ContinueExecution")
	
	func run_data ():
		var run_state = run_branch()
		
		if run_state is GDScriptFunctionState:
			yield(run_state, "completed")
			
		return run_state
	
	func run_branch ():
		yield(self, "ContinueExecution")
	
var data_intpr := Runner.new()

func _ready():
	data_intpr.run_data()

func _process(delta):
	if Input.is_action_just_pressed("ui_accept"):
		data_intpr.continue_excution()
```

**Minimal reproduction project:**
[Stack Underflow Yield problem.zip](https://github.com/godotengine/godot/files/3512945/Stack.Underflow.Yield.problem.zip)

**Comment by muchitto** [comment]
Ok, if you comment out the `return` line from the `run_data()` function, it doesn't throw the underflow error...

**Comment by bojidar-bg** [comment]
Probably related to this comment on the PR which change `yield`: https://github.com/godotengine/godot/pull/28884/files/9df1a2442b480f9ed8a8d4ec8992ea5046b98719#r284189443
