### ISSUE TITLE
Custom android build looks for the sdk in the wrong directory

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#31451]
**Godot version:**

cc9f2a2d8

**OS/device including version:**
GNU/Linux x64

**Issue description:**
The path to the SDK set in editor settings is relative to the engine executable, but when a project is exported for android using a custom build Godot tries to find the SDK in a path relative to the android/build folder within the project folder. As a temporary solution a I created a symlink to the SDK in the folder Godot was trying to use.

**Comment by akien-mga** [comment]
Fixed by #31586.
