### ISSUE TITLE
Node2D edit_*_pivot unimplemented

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3145]
While checking the Node2D code for an upcoming documentation update, I noticed that the edit_*_pivot part seems unimplemented:

```
void Node2D::edit_set_pivot(const Point2& p_pivot) {


}

Point2 Node2D::edit_get_pivot() const {

	return Point2();
}
bool Node2D::edit_has_pivot() const {

	return false;
}
```

https://github.com/godotengine/godot/blob/d3eb9e8/scene/2d/node_2d.cpp#L37-L49

It should either get implemented or remove I guess.

**Comment by reduz** [comment]
oh it's a virtual function, it's reimplemented in objects that use it such
as Sprite, AnimatedSprite, and a few others. It has default functions to
avoid overriding them in every single inheritance

**Comment by akien-mga** [comment]
Ah right, my bad :)
