### ISSUE TITLE
TileMap world_to_map unexpected result with half offset

### ISSUE THREAD

**Issue by zer0problem** [godotengine/godot#31468]
**Godot version:**
bcd2f24

**OS/device including version:**
Windows 10

**Issue description:**
For a TileMap node, using world_to_map, with a negative position on the border between 2 tile rows while half offset is active, it returns the wrong position by 1 depending on the other axis.

**Steps to reproduce:**
calling
world_to_map(Vector2(-49,-64))
on a TileMap with cell size 64,64, and half offset x
Should be -2,-1 or -1,-2 as those are the 2 tiles it's on the border of, but returns -1,-1

Minimal project
[minproject.zip](https://github.com/godotengine/godot/files/3513637/minproject.zip)

**Comment by bojidar-bg** [comment]
Does the same occur to points further away from the X/Y axes?

**Comment by zer0problem** [comment]
> Does the same occur to points further away from the X/Y axes?

Tried -64000000 units away, still happens while the non offset axis is a rather low number
with X offset,
-36, -64000000 turns out wrong
-64000036, -64000000 turns out correct
-64000036, -36 turns out wrong

**Comment by bojidar-bg** [comment]
Potentially similar to the bug in #30425 -- likely rounding up due to truncation instead of rounding down.
<sup>(won't have time to have a look at it now, other contributors welcome :) )</sup>

**Comment by zer0problem** [comment]
I don't think rounding would be the issue, if it just rounded the odd axis the same way when calculating the offset as when returning the value, I'll check if I can fix this quickly
