### ISSUE TITLE
Flicering when using scale in animation tree

### ISSUE THREAD

**Issue by IllusiveS** [godotengine/godot#31467]
**Godot version:**
bcd2f248ec04681c731ad0f90ad9869ac1745183

**OS/device including version:**
ubuntu 18.04.3 LTS

**Issue description:**
I am trying to use some animation trees for practice, since im going to talk about godot on a local open source event and figured animations and 2d bones are good idea for that.
I have a tree with two blend trees, one responsible for triggering walking animation, one responsible on animating scale, depending on the direction, then i simply blend those two, filtering only x scale to get a papermario-like effect when character changes direction

For some reason the flickering happens.

![scaling_anim_problem](https://user-images.githubusercontent.com/7921065/63230455-23a6ad00-c20d-11e9-8a6e-e43a88a0b430.gif)

**Steps to reproduce:**
Not sure what are the repro steps, there is a link to the project, its a small demo

**Minimal reproduction project:**

https://github.com/IllusiveS/godot_2d_animation

EDIT:
Forgot to mention that in editor everything seems to be fine

**Comment by qarmin** [comment]
Add `tool` keyword at the begging of script. to see this in editor.
I don't know if this is a Godot bug or just logic error in script.

**Comment by KoBeWi** [comment]
Seems to still happen in 3.2.3 rc6, but as qarmin said, someone needs to check if it's a valid bug or user error.

**Comment by Calinou** [comment]
This is not a bug, and is the nature of floating-point computations. To prevent this kind of chatter from ocurring, you need to have some kind of "epsilon" value in your character script. If the player's horizontal movement speed is located within this epsilon value range (typically below 1%-2% of maximum walk speed), the character's flip state should not be changed.
