### ISSUE TITLE
GLSL if/else bug only in Godot

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#31469]
**Godot version:**
3.1.1 stable

**OS/device including version:**
linux/web

**Issue description:**
this line `((uv.x>0.5)?((uv.x<0.75)?vec3(0.1):vec3(0.2)):vec3(0.3))*(3.+3.*sin(iTime));`
bugged in Godot when `(uv.x>0.5)` is true, when it true then this part `*(3.+3.*sin(iTime))` does not work.
example images display how it look like in Godot(first) and how it should look like(second)

This bug exist only in Godot GLSL, I have test it in real OpenGL application and Vulkan(glsllang), no error there.

**Steps to reproduce:**
create shader:
```
shader_type canvas_item;

void fragment() {
	vec2 uv=UV;
	COLOR.rgb= ((uv.x>0.5)?((uv.x<0.75)?vec3(0.1):vec3(0.2)):vec3(0.3))*(3.+3.*sin(TIME));
	COLOR.a=1.;
}
```

**Minimal reproduction project:**
shadertoy https://www.shadertoy.com/view/wt2XWm (work correct)
Godot web https://danilw.github.io/godot-utils-and-other/glsl_bug_ifelse/web/GLSL_bug_ifelse.html
Godot source https://danilw.github.io/godot-utils-and-other/glsl_bug_ifelse/OpenGL_bug_ifelse.zip

![Godot](https://user-images.githubusercontent.com/24825887/63231406-fa454b80-c223-11e9-840e-581f1af06592.png)
![Correct](https://user-images.githubusercontent.com/24825887/63231407-fa454b80-c223-11e9-9f95-6d3f70f148dc.png)

**Comment by clayjohn** [comment]
@Chaosus You have a lot of experience in the shader compiler. Any idea what could cause this?

@danilw To be perfectly honest, unless this is an easy fix, I cannot see it being a high priority. It is such an extreme edge case and everything is being rewritten for 4.0 anyway. That being said, if its an easy fix than we should fix it.

**Comment by Chaosus** [comment]
I've just awakening, will look at this :)

**Comment by Chaosus** [comment]
Yeah, it's a parser bug. This code will works as expected:

```
	if(uv.x > 0.5) {
		if(uv.x < 0.75) {
			COLOR.rgb = vec3(0.1);
		} else {
			COLOR.rgb = vec3(0.2);
		}
	}
	else {
		COLOR.rgb = vec3(0.3);
	}
	COLOR.rgb *= (3. + 3. * sin(TIME));
```

**Comment by clayjohn** [comment]
Realistically, users should be using that code rather than the single liner. I know when working on GDScript they try to enforce good coding style. There is never a good reason to use multiple nested ``?``s on the same line.

**Comment by Chaosus** [comment]
Well, a lot of peoples copy/paste shader from different sources such as ShaderToy where a lot of peoples uses complex expressions of ternary operators, so fixing it is necessary.

**Comment by clayjohn** [comment]
Good point!
