### ISSUE TITLE
godot 3.1.1 html5 export freeze and crash

### ISSUE THREAD

**Issue by canvasbushi** [godotengine/godot#31472]
**Godot version:**
3.1.1

**OS/device including version:**
exported on windows 10
chrome/firefox/pretty much every browser

**Issue description:**
exported my project to html, uploaded it to a live server, tried to load it up. browser freeze followed by browser crash(followed by browser burning)

**Steps to reproduce:**
seems to happen with even new empty projects, so i'm thinking its easy to reproduce.

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Again, you'll have to provide more information. 

It's not easy to reproduce as other users aren't experiencing this same issue. Without more information it will be impossible to reproduce and so no one can help you.

**Comment by canvasbushi** [comment]
No error messages in console, console won't open because the entire tab freezes on trying to load.
wait long enough and the browser will recommend killing the tab.

![image](https://user-images.githubusercontent.com/49125185/63389133-63d27080-c370-11e9-9505-eccbcbb3833a.png)

reloading doesnt work, nothing works since everything is frozen, but after awhile this shows up OpenGL ES 2.0 Renderer: WebKit WebGL, but still frozen. i can't even close the tab.

**Comment by jusroberts** [comment]
Hi there, I'm seeing similar issues with windows 10 3.1.1. Chrome will crash when trying to load, but firefox manages to stay alive. I've gotten different errors, depending on the game I've tried to export:

``` index.js:7:32435
uncaught exception: abort(101). Build with -s ASSERTIONS=1 for more info. index.js:7:321101
    abort file:///C:/Users/justi/godot/exports/nineTenths/index.js:7
    b101 file:///C:/Users/justi/godot/exports/nineTenths/index.js line 96 > WebAssembly.instantiate:181195
    __ZN6Object12notificationEib file:///C:/Users/justi/godot/exports/nineTenths/index.js line 96 > WebAssembly.instantiate:272470
    _send_notification file:///C:/Users/justi/godot/exports/nineTenths/index.js line 96 > WebAssembly.instantiate:3896247
    _send_notification file:///C:/Users/justi/godot/exports/nineTenths/index.js:7
    <anonymous> self-hosted:1047
```

is an example error, along with:

```**ERROR**: Condition ' !f ' is true. returned: String() Backromancy.js:7:32704
   At: core/bind/core_bind.cpp:1755:get_as_text() - Condition ' !f ' is true. returned: String() Backromancy.js:7:32704
**SCRIPT ERROR**: Unable to iterate on object of type  Nil'. Backromancy.js:7:32704
   At: res://scripts/ItemManager.gd:19:parse() - Unable to iterate on object of type  Nil'. Backromancy.js:7:32704
**ERROR**: Condition ' !f ' is true. returned: String() Backromancy.js:7:32704
   At: core/bind/core_bind.cpp:1755:get_as_text() - Condition ' !f ' is true. returned: String() Backromancy.js:7:32704
**SCRIPT ERROR**: Unable to iterate on object of type  Nil'. Backromancy.js:7:32704
   At: res://scripts/ItemManager.gd:19:parse() - Unable to iterate on object of type  Nil'.```

I am able to successfully export to Windows (.exe) and Android. I am using the latest stable 3.1.1 export templates.

**Comment by NetroScript** [comment]
I also had the problem that the HTML5 export didn't work for me, for me this was due to the Physics Thread Model being set to Multi-Threaded (which I probably changed by accident when testing stuff) - so if your HTML export is not working you could also try checking that. (My situation also was that the console didn't log anything besides which Renderer was used)

**Comment by jusroberts** [comment]
Looks like my Physics threads and rendering threads are both set to single-safe. Thanks for chiming in!

**Comment by jusroberts** [comment]
Hey, ignore my errors. It turns out I wasn't including *.json in my HTML5 export (but of course was for android and windows). Everything seems to be working swimmingly. Sorry for highjacking this thread.

**Comment by canvasbushi** [comment]
@NetroScript 
This was exactly my issue, thank you for the fix!

**Comment by Faless** [comment]
Moving discussion to #29641 then , I'll work on a fix for it, shouldn't be too hard.
