### ISSUE TITLE
drag and drop within Godot fails when screen sharing to Mac

### ISSUE THREAD

**Issue by ty-newton** [godotengine/godot#31479]
**Godot version:**

version 3.1.1.stable.official

**OS/device including version:**

remote desktop client and server are both MacOS Mojave 10.14.6

**Issue description:**

When using the in-built MacOS remote desktop capability Godot does not seem to respond to a mouse left click plus drag.  This stops functionality like dragging an image asset from the FileSystem onto the 2D canvas.

**Steps to reproduce:**
1. configure 2 MacOS computers so that one (the server) can share its screen with the other (the client) re: https://support.apple.com/en-au/guide/mac-help/mh11848/mac
2. install Godot 3.1.1.stable.official on the server
3. use the client to connect to the server so the server screen is being accessed from the client re: https://support.apple.com/en-au/guide/mac-help/mh14066/10.14/mac/10.14
4. start Godot and create a new project
5. select 2D
6. attempt to drag icon.png from the FileSystem onto the 2D canvas
The icon is not dragged.

Note: when dragging a file from Finder to the desktop the drag and drop functionality works.
Note 2: when running Godot on Windows 10 and using Microsoft Remote Desktop for Mac on the client; it is possible to drag the icon onto the canvas.

**Minimal reproduction project:**

No need, just use the default project that Godot generates when creating a new project.

**Comment by ty-newton** [comment]
Additionally, I tested running Godot on MacOS and used RealVNC on a Windows 10 client.  The icon failed to drag in this configuration.  This leads me to think the problem is within the MacOS implementation.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by ty-newton** [comment]
> Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

I can confirm that the bug seems to be fixed in v3.2.3.

**Comment by akien-mga** [comment]
Thanks, closing then.
