### ISSUE TITLE
I can't start godot. Got an error

### ISSUE THREAD

**Issue by abelard-l** [godotengine/godot#31475]
Hello!
I can't start godot.
I got this error in console

http://joxi.ru/82QEzEaIwz60o2

**Comment by akien-mga** [comment]
There was an issue template, please fill it. We can't help without information on your system, GPU, Godot version, etc.

**Comment by LinuxUserGD** [comment]
I think you are using a newer project (e. g. from master) on an old Godot build (Godot 3.1.1) because of the `condition !version is true`.

**Comment by akien-mga** [comment]
> I think you are using a newer project (e. g. from master) on an old Godot build (Godot 3.1.1) because of the condition !version is true.

No this message originates in the shader compiler, it's not related to the engine version.

In any case, we can't solve this issue with so little detail, so closing.

**Comment by bojidar-bg** [comment]
As per https://community.khronos.org/t/opengl-does-not-allow-mediump-after-inout/67417

Your drivers are probably old, and support a non-standard version of OpenGL (on in which inout and precision modifiers are swapped around). Try updating them.
