### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#3148]
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o drivers/unix/thread_posix.iphone.debug.o -c -fno-objc-arc -arch armv7 -fmessage-length=0 -fno-strict-aliasing -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -Wno-trigraphs -fpascal-strings -Wmissing-prototypes -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk -gdwarf-2 -fvisibility=hidden -Wno-sign-conversion -mthumb "-DIBOutlet=__attribute__((iboutlet))" "-DIBOutletCollection(ClassName)=__attribute__((iboutletcollection(ClassName)))" "-DIBAction=void)__attribute__((ibaction)" -miphoneos-version-min=5.1.1 -MMD -MT dependencies -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/ -D_DEBUG -DDEBUG=1 -gdwarf-2 -Wall -O0 -DDEBUG_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -fblocks -DPLATFORM_SERVICES -fblocks -DGAME_CENTER_ENABLED -DSTOREKIT_ENABLED -DICLOUD_ENABLED -DDEBUG_MEMORY_ENABLED -DIPHONE_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DMPC_FIXED_POINT -fexceptions -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DPNG_ARM_NEON_OPT=0 -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/iphone -Iplatform/iphone/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AudioUnit.framework/Headers -Idrivers/builtin_openssl2 -Idrivers/builtin_zlib/zlib -Idrivers/unix/vorbis -Idrivers/builtin_openssl2/crypto -Idrivers/builtin_openssl2/openssl -Idrivers/builtin_openssl2/crypto/evp -Idrivers/builtin_openssl2/crypto/asn1 -Idrivers/builtin_openssl2/crypto/modes drivers/unix/thread_posix.cpp
drivers/unix/thread_posix.cpp:103:12:{103:12-103:30}: error: no matching function for call to 'pthread_setname_np' [2]
        int err = pthread_setname_np(pthread, p_name.utf8().get_data());
                   ^~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/pthread.h:474:5: note: candidate function not viable: requires 1 argument, but 2 were provided [2]
 int    pthread_setname_np(const char*);
         ^
1 error generated.
scons: *** [drivers/unix/thread_posix.iphone.debug.o] Error 1
scons: building terminated because of errors.
```

This error with named threads..

**Comment by akien-mga** [comment]
Which commit are you trying to compile?

**Comment by ealataur** [comment]
Latest from master

**Comment by punto-** [comment]
Did we fix this last week?

**Comment by akien-mga** [comment]
That's what I supposed, but I assume that by "Latest from master" @ealataur meant today's HEAD.

**Comment by akien-mga** [comment]
Do you still have this issue @ealataur?

**Comment by ealataur** [comment]
I will check tomorrow..

**Comment by ealataur** [comment]
bash-3.2$ scons platform=iphone b=32 -j5

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: servers/libservers.iphone.debug.a(voice_rb_sw.iphone.debug.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o core/globals.iphone.debug.o -c -fno-objc-arc -arch armv7 -fmessage-length=0 -fno-strict-aliasing -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -Wno-trigraphs -fpascal-strings -Wmissing-prototypes -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk -fvisibility=hidden -Wno-sign-conversion -mthumb "-DIBOutlet=__attribute__((iboutlet))" "-DIBOutletCollection(ClassName)=__attribute__((iboutletcollection(ClassName)))" "-DIBAction=void)__attribute__((ibaction)" -miphoneos-version-min=5.1.1 -MMD -MT dependencies -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/ -D_DEBUG -DDEBUG=1 -gdwarf-2 -Wall -O0 -DDEBUG_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -fblocks -DPLATFORM_SERVICES -fblocks -DGAME_CENTER_ENABLED -DSTOREKIT_ENABLED -DICLOUD_ENABLED -DDEBUG_MEMORY_ENABLED -DIPHONE_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DMPC_FIXED_POINT -fexceptions -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DPNG_ARM_NEON_OPT=0 -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/iphone -Iplatform/iphone/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AudioUnit.framework/Headers -Idrivers/builtin_openssl2 -Idrivers/builtin_zlib/zlib -Icore/vorbis -Idrivers/builtin_openssl2/crypto -Idrivers/builtin_openssl2/openssl -Idrivers/builtin_openssl2/crypto/evp -Idrivers/builtin_openssl2/crypto/asn1 -Idrivers/builtin_openssl2/crypto/modes core/globals.cpp
core/global_defaults.cpp:8:2: error: use of undeclared identifier 'register_iphone___global_defaults'; did you mean 'register_iphone_global_defaults'? [2]
        register_iphone___global_defaults();
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         register_iphone_global_defaults
fix-it:"core/global_defaults.cpp":{8:2-8:35}:"register_iphone_global_defaults"
./platform/iphone__/globals/global_defaults.h:3:6: note: 'register_iphone_global_defaults' declared here [2]
 void register_iphone_global_defaults();
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o core/image.iphone.debug.o -c -fno-objc-arc -arch armv7 -fmessage-length=0 -fno-strict-aliasing -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -Wno-trigraphs -fpascal-strings -Wmissing-prototypes -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk -fvisibility=hidden -Wno-sign-conversion -mthumb "-DIBOutlet=__attribute__((iboutlet))" "-DIBOutletCollection(ClassName)=__attribute__((iboutletcollection(ClassName)))" "-DIBAction=void)__attribute__((ibaction)" -miphoneos-version-min=5.1.1 -MMD -MT dependencies -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/ -D_DEBUG -DDEBUG=1 -gdwarf-2 -Wall -O0 -DDEBUG_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -fblocks -DPLATFORM_SERVICES -fblocks -DGAME_CENTER_ENABLED -DSTOREKIT_ENABLED -DICLOUD_ENABLED -DDEBUG_MEMORY_ENABLED -DIPHONE_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DMPC_FIXED_POINT -fexceptions -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DPNG_ARM_NEON_OPT=0 -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/iphone -Iplatform/iphone/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AudioUnit.framework/Headers -Idrivers/builtin_openssl2 -Idrivers/builtin_zlib/zlib -Icore/vorbis -Idrivers/builtin_openssl2/crypto -Idrivers/builtin_openssl2/openssl -Idrivers/builtin_openssl2/crypto/evp -Idrivers/builtin_openssl2/crypto/asn1 -Idrivers/builtin_openssl2/crypto/modes core/image.cpp
1 error generated.
scons: *** [core/global_defaults.iphone.debug.o] Error 1
core/image.cpp:1655:10: warning: 21 enumeration values not handled in switch: 'FORMAT_GRAYSCALE', 'FORMAT_INTENSITY', 'FORMAT_GRAYSCALE_ALPHA'... [-Wswitch,2]
                switch(format) {
                        ^
1 warning generated.
scons: building terminated because of errors.

**Comment by akien-mga** [comment]
Did you rename ```platform/iphone``` to ```platform/iphone__``` yourself?

**Comment by ealataur** [comment]
Not rename.. It is duplicate of folder with my own fixes

**Comment by akien-mga** [comment]
You need to fix this line then: https://github.com/godotengine/godot/blob/0c3386b2ed7c3791127e2b12a2227deddad96ae5/core/SCsub#L12

**Comment by akien-mga** [comment]
But please try to build the main ```platform/iphone``` from git to confirm if the bug reported initially is fixed. It's harder to debug your own copy of the code ;) (and out of the scope of this issue tracker)

**Comment by ealataur** [comment]
Ok. Without my duplicate folder all compiles done. Sorry..

I have some features for iphone platform. And i want commit it in main tree. How I can do it? I tested this features on device and all ok

**Comment by akien-mga** [comment]
> Ok. Without my duplicate folder all compiles done. Sorry..

Thanks, closing the issue then as it was likely fixed by what @punto- mentioned earlier.

> I have some features for iphone platform. And i want commit it in main tree. How I can do it? I tested this features on device and all ok

To do this you would have to make a "pull request".
- You need first to fork the main Godot repository by clicking the "Fork" button in the GitHub interface.
- Then you can clone your own fork locally with ```git clone https://github.com/ealataur/godot``` (or alternatively add a custom "remote" to your existing clone of the godotengine/godot repo - but if you are not experienced with git I would advise you to do the first suggestion)
- In your freshly forked and cloned repository, you can then copy you changes on top of the upstream files. By running ```git diff```, it should show you all the changes that you made in the form of diffs/patches. If it looks good, you can commit the changes.
- To commit, add all your changes with ```git add```, for example if you only changed files in platform/iphone, you can do ```git add platform/iphone```. ```git status``` should show you what files are currently "added".
- Once all relevant files are "added", you can make a commit with ```git commit```. It should open a text editor where you will write the commit log which should explain what your changes bring. Don't hesitate to write a complete paragraph if need be (just make the first line short like a "title", and then add more details in the following lines).
- After saving and closing the editor, it should have committed your changes *locally*. You can check with ```git log``` and ```git show```. Then you can push your changes to your remote fork with ```git push``` - on the GitHub interface for your online repo, it should now show that you are one commit (or more, if you made several commits) ahead of godotengine/master (and maybe some commits behind if new stuff was pushed to the main repo in the meantime, but that's usually not an issue). You can then click the "Pull request" button to make a request to automatically merge your changes in the main repo.

**Comment by ealataur** [comment]
Ok. Thank you
