### ISSUE TITLE
glitch in resolution

### ISSUE THREAD

**Issue by Vulganot** [godotengine/godot#31491]
![godot](https://user-images.githubusercontent.com/54265939/63298705-ba0ac980-c306-11e9-9c39-565e491c687e.png)

this started happening yesterday and its stuck like this and i cant really do anything. every now and then like once a minute it randomly will fix itself for like 10 seconds then stretches out again like this. Its really weird. I tried reinstalling a few times already and tried running the client i got from both steam and godots site. I was having fun with the engine all day yesterday and then this started happening after i clicked import and tried to change something about how the texture is imported or something.

**Godot version:**

3.1.1

**OS/device including version:**

Intel(R) HD Graphics 4000

**Issue description:**

screen resolution and size messing up

**Steps to reproduce:**
mess with how textures import

**Minimal reproduction project:**

**Comment by qarmin** [comment]
Please fill template about Godot version, OS version, your graphics driver etc.
Do you have installed the latest graphics drivers?

**Comment by Vulganot** [comment]
> Please fill template about Godot version, OS version, your graphics driver etc.
> Do you have installed the latest graphics drivers?

when i go to update graphics drivers it says i have the best up to date installed.

**Comment by KoBeWi** [comment]
@Vulganot Can you still reproduce this issue in 3.2.3?

**Comment by akien-mga** [comment]
No answer, so closing.
