### ISSUE TITLE
Child physic body 2d can not be collide by another child physic body 2d

### ISSUE THREAD

**Issue by narunsa** [godotengine/godot#31497]
**Godot version:**
3.1.1

**Issue description:**
I create a kinematic body 2d and set it collision layer to nothing and collision mask to nothing. In this kinematic body 2d, I create a static body 2d as a child of it then i set it collision layer to layer 1 and  collision mask to layer 1. 

I add 2 kinematic bodies to my scene and it not collide with themself.

If I create new kinematic body 2d and set it mask layer to 1, it collide with first kinematic body 2d.

**Comment by KoBeWi** [comment]
Reproduction project?

**Comment by bojidar-bg** [comment]
Static bodies do not collide with other static bodies. (Also, consider: even if they did, why would they make their respective kinematic body parents collide? They would more likely just move out of collision without affecting the kinematic body.)

**Comment by narunsa** [comment]
Here is a [simple project](https://drive.google.com/file/d/1JGDYTQ7dQBXaaSygUDt33K6azIWGSRli/view)

My purpose is i want to make a kinematic body have many shape of collision eg. shape A can collide with player or wall and shape b can collide only enemy.

I wonder have a another way to do it?

Thanks.

**Comment by KoBeWi** [comment]
Sorry for a late answer, but your StaticBodies aren't supposed to have any interaction. They do collide with themselves, but it doesn't affect KinematicBody, because the KinematicBody is affected only by its own collider and whatever it collides with (and StaticBodies are both on different layer).

Why exactly do you need these StaticBodies? If you want to detect collisions, you should use Areas.

**Comment by narunsa** [comment]
Thank for explain me about this.

If i want a KinematicBody collide with wall and enemy but it have different shape of each other. eg. shape that collide with Enemy is circle (small circle, player avoid enemy easier) and shape that collide with Wall is capsule. I can do something like this or not.

Thanks.

**Comment by KoBeWi** [comment]
Well, if you mean physical collisions, you can't do anything like that. However, if you want your character to be stopped by walls, you can add the collider you want for walls directly to your KinematicBody. Then if you want another collider for enemies, you can add a child Area2D for your character. However, it is impossible to get physical contact with enemies this way - you can at most detect the collision.

**Comment by narunsa** [comment]
Thanks for answer and explain me about this.
