### ISSUE TITLE
Subpixel Label rendering issues when Label within Node2D

### ISSUE THREAD

**Issue by NetroScript** [godotengine/godot#31495]
**Godot version:**
3.1.1 stable, but also tested on https://github.com/godotengine/godot/commit/e802da4e81e8262e968e09da4b9690f6c9a19a56

**OS/device including version:**
Windows 10 | RTX 2070 Super, 431.68

**Issue description:**
When a Control Node using a Dynamic Font is contained withing a Node2D, which is in a subpixel position (in this case 0.5 pixels), each letter will be rendered on a different height.
![1wy0WS4RDq](https://user-images.githubusercontent.com/18115780/63310065-86757280-c2f9-11e9-8607-39872176b151.png)
(Open in a new tab to see it more easily)

Meaning the issue title is similar to https://github.com/godotengine/godot/issues/15124 but it is a different problem

**Steps to reproduce:**
1. Create a Node2D, set it's position to Y = 0.5
2. Add a Label, add any text, set a dynamic font as custom font (easier to see on small font sizes)

**Minimal reproduction project:**
[Bug Demo Wrong Text Rendering.zip](https://github.com/godotengine/godot/files/3518239/Bug.Demo.Wrong.Text.Rendering.zip)

I want to mention that the reproduction project I provided shows the problem, but in my project I am working on, the offset letters are even more visible.

**Comment by TheDuriel** [comment]
Related: https://github.com/godotengine/godot/issues/30643

**Comment by KoBeWi** [comment]
Seems solved in 6ac7b90
(Although valid in 3.2.3 rc6)
