### ISSUE TITLE
TileSet editor enhancement

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31500]
**Godot version:**

3.1

**Issue description:**

When you have no texture selected in the TileSet editor, it should say so. This avoids scenarios where the user opens up the editor and wonders where all their tiles have gone.

![image](https://user-images.githubusercontent.com/44248915/63353675-5f538b00-c363-11e9-9eb5-6c9f5451d9a1.png)

**Comment by sndels** [comment]
This seemed pretty straightforward. Any comments on the implementation?
![empty](https://user-images.githubusercontent.com/16364388/63369765-507fcf00-c389-11e9-9c36-87fdadd7f4ae.PNG)

```c++
--- a/editor/plugins/tile_map_editor_plugin.cpp
+++ b/editor/plugins/tile_map_editor_plugin.cpp
@@ -405,8 +405,13 @@ void TileMapEditor::_update_palette() {
        manual_palette->hide();

        Ref<TileSet> tileset = node->get_tileset();
-       if (tileset.is_null())
+       if (tileset.is_null()) {
+               real_t width = palette->get_size().x - palette->get_margin(Margin::MARGIN_LEFT) - palette->get_margin(Margin::MARGIN_RIGHT);
+               palette->set_fixed_column_width(width);
+               palette->add_item(String("No TileSet selected"));
+               palette->set_item_custom_fg_color(0, Color(1, 0, 0));
                return;
+       }

        List<int> tiles;
        tileset->get_tile_list(&tiles);
```

**Comment by TheDuriel** [comment]
That looks good for the TileMap editor yes, just needs the TileSet editor now as well ;P You might want to grab the correct font color from the theme, if there is one.

**Comment by Calinou** [comment]
The default font color should be fine to use, which means you can likely remove `palette->set_item_custom_fg_color(0, Color(1, 0, 0));`.

**Comment by sndels** [comment]
Good point on the color. I figured having the labeled TileSet dropdown right next to the text would suffice for the TileMap panel but adding context there might be a good idea. Doing the message through a palette item seems a bit hacky but it takes care of potential wrapping pretty nicely.

Here's what I conjured for TileSet editor
![empty](https://user-images.githubusercontent.com/16364388/63378798-a9586300-c39b-11e9-91a5-1264ba4d1392.PNG)
```c++
--- a/editor/plugins/tile_set_editor_plugin.cpp
+++ b/editor/plugins/tile_set_editor_plugin.cpp
@@ -1033,9 +1033,17 @@ void TileSetEditor::_on_workspace_process() {

 void TileSetEditor::_on_workspace_overlay_draw() {

-       if (!tileset.is_valid() || !get_current_texture().is_valid())
+       if (!tileset.is_valid())
                return;

+       if (!get_current_texture().is_valid()) {
+               Ref<Font> font = get_font("font", "Label");
+               Color color = get_color("font_color", "Editor");
+               Point2i offset(workspace_overlay->get_margin(Margin::MARGIN_LEFT), WORKSPACE_MARGIN.y);
+               workspace_overlay->draw_string(font, offset, String("Select texture to edit from the left"), color);
+               return;
+       }
+
```
The margins are a bit odd but using the workspace_overlay's top margin rendered the text halfway under the frame.
