### ISSUE TITLE
Suggestion: Make get_stack() available in exported exe (release mode) too

### ISSUE THREAD

**Issue by rslepon** [godotengine/godot#31501]
**Godot version:**
Godot_v3.1.1-stable_win64

**Issue description:**
Currently get_stack() seems to work only in the editor, as far as I can see. I believe it may be even more useful in the exported exe (in release mode), so I suggest making it work there too.

Here is a function I was planning to use in my game as a replacement for assert():
```
# replacement for assert, aborting in debug mode, logging in debug and release modes
func ass (cond :  bool, # if conditional is not true, pretty fatal
          msg  := ""    # message to print to log
         ) -> void:
   var fh  := File.new() # file handle
   var err := OK         # error code

   # if failed
   if not cond:

      # open new file
      err = fh.open(D.LOG_FILE_PATH_FULL, File.READ_WRITE)
      assert(err == OK)

      # write to log
      fh.store_line("%d: %s" % [OS.get_ticks_msec(), msg])
      fh.store_line(str(get_stack()))

      # close file
      fh.close()

      # abort in debug mode
      assert(cond)
```

It works just fine, except that get_stack() returns an empty array in the exported exe (regardless of whether "Export With Debug" is checked or not), where it is most needed, since in the editor the information is already available in the debugger.

P.S. I expect the same could be said for print_stack() too.

P.P.S. I am suggesting to add this as an optional project (or export) setting (off by default). If one wished to pay the performance penalty for the added debug capability (I expect I would), then one would enable that setting.

**Comment by KoBeWi** [comment]
Wouldn't that mean the release build should keep the stack trace? I think it's not supported there at all for performance reasons.

**Comment by rslepon** [comment]
Yes. It would mean that.

I forgot to mention that I am suggesting to add this as an optional project setting (off by default). If one wished to pay the performance penalty for the added debug capability (I expect I would), then one would enable that setting.

**Comment by alex-evelyn** [comment]
I second wanting get_stack() to work in release executables. I am currently implementing a logger gdscript so users can submit logs to me when my game breaks and being able to get a stracktrace would be very useful.

**Comment by rslepon** [comment]
Moved here:
https://github.com/godotengine/godot-proposals/issues/105
