### ISSUE TITLE
Touch events stolen by iOS

### ISSUE THREAD

**Issue by fogine** [godotengine/godot#31503]
**Godot version:**

`v3.1.1.stable.official`

**OS/device including version:**

all `iOS` devices

**Issue description:**

OS is stealing touch events on top and bottom sides (at least inch in height).
What happens is that all "InputEventTouch" events (when pressed) are delayed for one second.  
This makes games using bottom space for button placement unusable.  

**SOLUTION**
As described in the detail here:
https://useyourloaf.com/blog/avoiding-conflicts-with-system-gestures-at-screen-edges/

The solution is to tell the OS that the app should take precedence when handling events in those areas.

**Minimal reproduction project:**
Don't think its needed, but can provide if it was to help fix the issue.

 The issue is not reproductible on emulated `iOS` devices and in my opinion can be only seen  when testing on real `iOS` device.  

Its really an unfortunate that I stumbled upon this issue at a time of preparing for `iOS` release. As I'm not a `mac` user, I'd be really grateful for any help with a workaround script or some way to temporary fix the issue when exporting from `godot 3.1.1`.
Recently I got `iOS 12` device for app testing so I can test changes around the issue if needed.

**Comment by fogine** [comment]
As I see `ViewController` implementation for iphone already overrides `prefersStatusBarHidden` and returns explicitly `true`.  
So this issue should apply only for `iOS>=11` where implementation of `preferredScreenEdgesDeferringSystemGestures` is required.  

This should be minor fix in the code in the case of keeping current behavior - that is all apps have currently explicitly disabled status bar and system overlays...  

What comes to my mind though is that it would be better to make it configurable in the editor.
Or even make the functionality dynamic and allow to change the configuration on the fly from script if possible - which, for most cases would be overkill.

Some type of apps would rather have the `iOS` overlays enabled, games will have it mostly disabled.

Any thoughts?

**Comment by akien-mga** [comment]
CC @godotengine/ios
