### ISSUE TITLE
Deprecate the ToolButton node

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#31518]
`ToolButton` is a `Button` that has `flat` enabled by default. **That's it.**

I don't think such a thing needs a node of its own, and would probably be for the better if it was marked as deprecated and then removed in 4.0.

**But wait! It's heavily used in the editor itself!**
Indeed, and it saves a total of one single line. Sure, the editor has lots of buttons, so those single lines pile up, but here's a better solution, making `Button` take a argument when created, like `Label` does:
`Label *new_label = memnew(Label("Placing text here avoids needing a extra line."));`

**Comment by KoBeWi** [comment]
I love how single copyright header is longer than whole declaration and implementation of this class XD

Constructor argument makes sense, but is `flat` really that important option to be there? (I mean outside editor ofc)

**Comment by groud** [comment]
Making ToolButton an editor-only feature makes even more sense IMHO.

**Comment by akien-mga** [comment]
Should we simply make the editor theme have flat by default for all buttons, and drop ToolButton + the manual `set_flat()`s? Or are there good use cases for both flat and non-flat buttons in the editor?

**Comment by groud** [comment]
> Should we simply make the editor theme have flat by default for all buttons

That would make sense, but for now the "flat" button property is not overridable in the theme. It should be made an overridable constant.

**Comment by YeldhamDev** [comment]
There are a lot of non-flat buttons (mainly the "Cancel" and "OK" in dialogs) that would look odd if flat, so I don't think setting all buttons to one option would work.

**Comment by groud** [comment]
Indeed, if we move that to a theme constant, it can also be overriden later on for specific nodes.

**Comment by Calinou** [comment]
For the record, the [editor theme redesign](https://github.com/Calinou/godot/tree/improve-editor-theme) I'm currently working on doesn't need ToolButton, so I already removed it there.

**Comment by YeldhamDev** [comment]
Closed by #39690.
