### ISSUE TITLE
Collection-based Godot API calls

### ISSUE THREAD

**Issue by Trayani** [godotengine/godot#31512]
Communication with Godot's C++ code is expensive. When you have 600 moving objects, you are updating their position every frame.

Instead of calling the same function 600 times, why not make it possible to call a "batch" method accepting an array of moving objects and their new positions?
This is not relevant to position update only, but set_position is definitely one of the most frequent calls 

If it can be optimized, I believe it could benefit all Godoters that do not use C++, to some degree (mostly us, users of C#, though).

Now, I lack the expertise to implement it by myself (and provide some numbers) hence I'm making this issue, more as topic for discussion. I'm interested in your opinions.
If it is a silly suggestion, feel free to close it. No hard feelings ;).

**Comment by KoBeWi** [comment]
Have you seen [propagate_call()](https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-propagate-call)?

**Comment by Trayani** [comment]
@KoBeWi, it is certainly interesting, but not exactly what I have in mind. 

Let's say we have 500 move-able Nodes. All are children of the same parent. Only 40 Nodes moved. 
AFAIK, propagate_call applies the same arguments over and over. So setting the position of all 500 Nodes is all I can do with it.

What I imaged was a method like this:

```
set_positions ( int count , Node nodes[], Vector2 positions[]) {
    for (int i = 0; i < count ; ++i) {
                nodes[i].position = positions[i];
        }
}
```
(this is merely my attempt at c++ code)

**Comment by KoBeWi** [comment]
That might require having a separate method for each of these operations. Or a single method only for position, which is too specific. Sounds like something for GDNative plugin.

Alternatively, we could have an `Array.each` method, which calls a method for each Object in an array (something like not-mutative `map`). It might be slower than pure C++ code, as it could call an arbitrary method, but probably still faster than a `for` in GDScript.

**Comment by Trayani** [comment]
I'm not sure if GDNative bindings currently have enough control over godot's own core classes. So I assumed that only an addition to the core could allow it.

Personally, I think a few of the most frequently used methods could receive their specific collection-based counter-part (e.g. scale, position, angle, color, scene instantiation / node duplication....). That is just my preference though.
More scarcely used methods could be batched according to your suggestion.

**Comment by Zylann** [comment]
Where do you think the bottleneck really is?

If it is in the call doing transition from C# managed world to C++, sure that might be relevant (need to measure to prove it).

If the bottleneck isn't there, adding such a feature may run down to the core of servers where position gets propagated. But servers themselves take inputs for single objects, so for such optimization to make sense it would have to map well to the memory layout of these objects... which might be a bit too far fetched.

Also, what are you moving? If you move a node with children, some with physics, some with graphics, doing an array-update for speed will be less relevant (depends again where the bottleneck is).

Note that using servers directly might make more sense if you want speed, or use particles, batching etc.

**Comment by Trayani** [comment]
Okay, I performed a test using C++ dynamic library where I set positions of 15 000 Sprite objects. I ran it 5 times to account for warm-up and randomness.
The time for preparation of parameter array for the batch call was not accounted in any way (making the result a bit biased in favor of batch calls).
The C++ method looked like this (it was the best version I could come up with. I'm open to a further optimizations though):

```
void BatchCalls::set_positions(Array args) {
	int count = int(args[0]);      // count is due to potential array recycling
	Node2D* nodes = (Node2D*) &(Array(args[1])[0]);
	Vector2* pos = (Vector2*) &Array(args[2])[0];
	for (int i = 0; i < count; ++i) {
			nodes++->set_position(*pos++);
	}
}
```
Results for the batch call and simple position update were as follows, 
```
Attempt 1, batch call,           TIME: 00:00:00.0146841
Attempt 1, position update,      TIME: 00:00:00.0052034
Attempt 2, batch call,           TIME: 00:00:00.0063530
Attempt 2, position update,      TIME: 00:00:00.0054188
Attempt 3, batch call,           TIME: 00:00:00.0068978
Attempt 3, position update,      TIME: 00:00:00.0051130
Attempt 4, batch call,           TIME: 00:00:00.0063171
Attempt 4, position update,      TIME: 00:00:00.0050269
Attempt 5, batch call,           TIME: 00:00:00.0062056
Attempt 5, position update,      TIME: 00:00:00.0047558
```

Position update is always the winner. This makes this issue obsolete (unless there is a room for a significant optimization, that I do not know of).

The reason I wanted to suggest this "optimization" is because I encountered claims that C# users should avoid Godot API calls and thus considered it general consensus. Honestly, I do not have links to such posts and since I did the test, I dont think they need to be cited.
I'm not saying that Godot API is universally light-weight. For example, C#-ers should always watch out for use of reflection is it is in signals and animation tracks.

Anyway, if I find a room for optimization, I will return with more compelling evidence :).

**Comment by Trayani** [comment]
```void BatchCalls::set_positions(Array args) {	int count = int(args[0]);	Node2D* nodes = (Node2D*) &(Array(args[1])[0]);	Vector2* pos = (Vector2*) &Array(args[2])[0];	for (int i = 0; i < count; ++i) {			nodes++->set_position(*pos++);	}}```
