### ISSUE TITLE
Vulkan build does not start.

### ISSUE THREAD

**Issue by LordEvilthe666** [godotengine/godot#31514]
**Godot version:**

92a1606 (Vulkan branch)

**OS/device including version:**

Visual Studio 2019 Community
Windows 10 r1903
Intel Core i7-7700HQ
Dual Intel HD 630/NVidia GeForce GTX 1050 Ti (drv. v.431.60)

**Issue description:**

_What happened:_
Engine does not launch. Exceptions and trace log follow:

> Vulkan physical device creation success o_O
> ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> ERROR: ERROR: ERROR:    At: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR: ERROR:    At: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
>    At: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> drivers\vulkan\rendering_device_vulkan.cpp:3774
>    At:    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
>    At: ERROR:    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR:    At: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> drivers\vulkan\rendering_device_vulkan.cpp:3774
>    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
>    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR: ERROR: ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
>    At: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
>    At:    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
>    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: ERROR: ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
>    At:    At: ERROR: ERROR:    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> drivers\vulkan\rendering_device_vulkan.cpp:3774
>    At: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
>    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
>    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> ERROR:    At: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> drivers\vulkan\rendering_device_vulkan.cpp:3774
>    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> ERROR:    At: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> drivers\vulkan\rendering_device_vulkan.cpp:3774
>    At: ERROR: ERROR: drivers\vulkan\rendering_device_vulkan.cpp:3774
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
> Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
>    At:    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: RenderPipelineVertexFormatCacheRD::setup: Condition ' p_shader.is_null() ' is true.
>    At: servers\visual\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:65
> ERROR: Reflection of SPIR-V shader stage 'Vertex' failed obtaining input variables.
>    At: drivers\vulkan\rendering_device_vulkan.cpp:3774
> ERROR: RenderingDeviceVulkan::render_pipeline_create: Condition ' !shader ' is true. returned: RID()
>    At: drivers\vulkan\rendering_device_vulkan.cpp:4754
> ERROR: RenderingDeviceVulkan::render_pipeline_create: Condition ' !shader ' is true. returned: RID()
>    At: drivers\vulkan\rendering_device_vulkan.cpp:4754
> ERROR: RenderingDeviceVulkan::render_pipeline_create: Condition ' !shader ' is true. returned: RID()
>    At: drivers\vulkan\rendering_device_vulkan.cpp:4754
> ERROR: RenderingDeviceVulkan::uniform_set_create: Condition ' !shader ' is true. returned: RID()
>    At: drivers\vulkan\rendering_device_vulkan.cpp:4224
> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] Map<enum VisualServer::ShaderMode,ShaderTypes::Type,Comparator<enum VisualServer::ShaderMode>,DefaultAllocator>::operator[] (D:\temp\godot\core\map.h:605)
> [1] Map<enum VisualServer::ShaderMode,ShaderTypes::Type,Comparator<enum VisualServer::ShaderMode>,DefaultAllocator>::operator[] (D:\temp\godot\core\map.h:605)
> [2] ShaderTypes::get_modes (D:\temp\godot\servers\visual\shader_types.cpp:40)
> [3] ShaderCompilerRD::compile (D:\temp\godot\servers\visual\rasterizer_rd\shader_compiler_rd.cpp:803)
> [4] RasterizerSceneForwardRD::ShaderData::set_code (D:\temp\godot\servers\visual\rasterizer_rd\rasterizer_scene_forward_rd.cpp:164)
> [5] RasterizerStorageRD::shader_set_code (D:\temp\godot\servers\visual\rasterizer_rd\rasterizer_storage_rd.cpp:881)
> [6] RasterizerSceneForwardRD::RasterizerSceneForwardRD (D:\temp\godot\servers\visual\rasterizer_rd\rasterizer_scene_forward_rd.cpp:1961)
> [7] RasterizerRD::RasterizerRD (D:\temp\godot\servers\visual\rasterizer_rd\rasterizer_rd.cpp:180)
> [8] RasterizerRD::_create_current (D:\temp\godot\servers\visual\rasterizer_rd\rasterizer_rd.h:81)
> [9] Rasterizer::create (D:\temp\godot\servers\visual\rasterizer.cpp:66)
> [10] VisualServerRaster::VisualServerRaster (D:\temp\godot\servers\visual\visual_server_raster.cpp:203)
> [11] OS_Windows::initialize (D:\temp\godot\platform\windows\os_windows.cpp:1357)
> [12] Main::setup2 (D:\temp\godot\main\main.cpp:1107)
> [13] Main::setup (D:\temp\godot\main\main.cpp:1050)
> [14] widechar_main (D:\temp\godot\platform\windows\godot_windows.cpp:150)
> [15] _main (D:\temp\godot\platform\windows\godot_windows.cpp:184)
> [16] main (D:\temp\godot\platform\windows\godot_windows.cpp:196)
> [17] __scrt_common_main_seh (d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
> [18] BaseThreadInitThunk
> -- END OF BACKTRACE --

Started the binary with debugger attached, got SPV_REFLECT_RESULT_ERROR_COUNT_MISMATCH in **result** and null pointer in **input_vars** at vulkan_rendering_device.cpp:3773
_Expected result:_
Something close to the one I have got, I think. 
(Unfortunately, I am unable to help with anything but the debug info at the moment)

**Steps to reproduce:**
1. Build current Vulkan version
2. Try to launch binary

**Minimal reproduction project:**

None.

**Comment by KoBeWi** [comment]
It's expected that the Vulcan branch might not run. It's heavily WIP, so not sure if it makes sense to report bugs right now.

**Comment by clayjohn** [comment]
Indeed. The Vulkan branch is more for people to follow along with development. Reduz is the only person actively developing it right now. We should not start tracking bugs until the core functionality is in place.

**Comment by LordEvilthe666** [comment]
It is indeed not a bug. As stated in the description, this was expected. More of a reference to what surely needs more attention in case it will be needed.
