### ISSUE TITLE
Platformer 3D - Player doesn't Show any Animation when Played

### ISSUE THREAD

**Issue by ScotFlux** [godotengine/godot#3151]
Player (GodotBot, a Cute blue Robot) doesn't Show / Act any animations. I means, when walking the GodotBot doesn't show a walk animation. And whenever shooting, it doesn't show a shooting animation.

Using Godot v2.0.alpha-r2575 (2015-12-26) compiled by Kelinci Senja (on Facebook).
But, with Godot v1.1-stable, this problem is not present.

![platform_3d_bug_-_animation_for_player_not_working](https://cloud.githubusercontent.com/assets/10663548/12024816/0ecbb0f2-ade3-11e5-9eaa-3712f3c59297.png)

**Comment by akien-mga** [comment]
I think I've seen something similar too when converting all demos scn files to the 2.0 format (but the regression was already there before I converted them), but forgot to create an issue, so thanks :)

**Comment by akien-mga** [comment]
I think there's a similar issue in the 2D + 3D viewport demo.
