### ISSUE TITLE
Explore performance improvements to core hash map implementation

### ISSUE THREAD

**Issue by savorywatt** [godotengine/godot#3152]
@reduz I was poking around looking for something to get started in this code base (more interested in the networking/game server side but that is more complicated) and I saw this issue and thought I might take a crack at it.

Make HashMap more efficient
http://www.godotengine.org/work_packages/13
- research using prime numbers for hashtable sizes and do benchmarks

I've done a bunch of reading around the prime numbers and started looking at other implementations and how godot's hashmap current implementation works. I'll try to summarize findings into a blog post or something and maybe throw up a PR with some proposed changes/benchmarks if I can. Just playing around with Godot in general trying to flex some C++ muscle (been a while).

**Comment by bojidar-bg** [comment]
Um... any updates?

**Comment by mhilbrunner** [comment]
@akien-mga Close this?

**Comment by akien-mga** [comment]
This has been partly done via new structures like OrderedHashMap.
