### ISSUE TITLE
Custom shape cursor with fullscreen hidden

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#31524]
**Godot version:**

Godot 2.1.6, Godot  3.1.1.stable.official

**OS/device including version:**

Windows 7 x64, Windows 10 x64

**Issue description:**

When used custom shape cursor bigger then 32x32px and fullscreen enabled, cursor hidden.
Only can see cursor when alt-tab pressed. Bug not reproduced on Linux machine maybe only windows specific.

**Steps to reproduce:**
Open attached project and run.

**Minimal reproduction project:**

For Godot 3.1.1: [CursorOnFullScreen.zip](https://github.com/godotengine/godot/files/3524057/CursorOnFullScreen.zip)

**Comment by KoBeWi** [comment]
Looks fixed in 3.2.3 rc6
Tested on Windows 10
