### ISSUE TITLE
Built Godot and had missing .pck file

### ISSUE THREAD

**Issue by jshlw** [godotengine/godot#31537]
**Godot version: 3.2**

**OS/device including version:**
Windows 10

**Issue description:**
I built Godot from source and when I tried opening the executable, it says that .pck file is missing.

`scons p=windows target=release -j2 tools=no optimize=size disable_3d=yes module_bmp_enabled=no module_bullet_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etc_enabled=no module_gdnative_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_mbedtls_enabled=no module_mobile_vr_enabled=no module_opus_enabled=no module_pvr_enabled=no module_recast_enabled=no module_regex_enabled=no module_squish_enabled=no module_tga_enabled=no module_thekla_unwrap_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_webm_enabled=no module_websocket_enabled=no disable`

**Steps to reproduce:**
Build from source and open executable.

**Comment by Calinou** [comment]
If you build an export template, you cannot run it directly. You need to export a project using it, or specify the path to a project directory using the `--path` command-line argument (for testing purposes).

To edit projects, compile a binary with `tools=yes`. Note that some modules can't be disabled when building an editor binary.

**Comment by jshlw** [comment]
So, I made the mistake of disabling `tools`. I'm going to build it again. Closing the issue.
