### ISSUE TITLE
Tilemap: sprite offset is not considered when rotating tiles

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3153]
The sprite offset on the tile is not considered when the tile is rotated/mirrored.
This makes the tile not snap to the grid entirely.

Here's an image showing the problem
![tile-offset](https://cloud.githubusercontent.com/assets/6296184/12025365/e28534b0-ad8c-11e5-89b8-ae98a2783bb1.png)

the tile on the left is properly snapped to the grid, but the second is not although it's the same tile just rotated.

**Comment by neikeq** [comment]
Can you check if the above PR fixes this issue?

**Comment by FEDE0D** [comment]
Nope, it's still in the wrong position.
![issue-tiles](https://cloud.githubusercontent.com/assets/6296184/12082622/565f95c4-b274-11e5-90eb-0dd36462d685.png)

0º and 270º rotation looks good, but the others are still in a bad position.

This is the tile I'm using: it's 128x148 (20 extra pixels on the top)
![test](https://cloud.githubusercontent.com/assets/6296184/12082629/8f48df26-b274-11e5-8c22-2ae13d578b68.png)

**Comment by neikeq** [comment]
Hmm, the problem seems to be caused because the tile region size is not 1:1.

**Comment by neikeq** [comment]
Now it should properly rotate tiles whose region size is not 1:1. Please, confirm :)

**Comment by akien-mga** [comment]
Does it work now @FEDE0D with the new commit in #3204?

**Comment by FEDE0D** [comment]
Yes! Now it's working as expected.

![tiles-working](https://cloud.githubusercontent.com/assets/6296184/12144386/096b98aa-b466-11e5-83c0-54878ce6c35f.png)

**Comment by FEDE0D** [comment]
I'm gonna leave this issue opened until the pr is merged.
Nice work!
