### ISSUE TITLE
Editor Settings absolute file paths are saved and shown as relative paths

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#31533]
**Godot version:**
3.2 master (48eaf14), regression from #28701 (CC @SonerSound)

**OS/device including version:**
Mageia 7 x86_64

**Issue description:**
Various editor settings are now saved as relative paths when they are meant to be absolute. See e.g. Android settings:
![Screenshot_20190821_142252](https://user-images.githubusercontent.com/4701338/63431563-66d86a00-c41f-11e9-848b-02a102ad507d.png)

Or custom template paths:
![Screenshot_20190821_142530](https://user-images.githubusercontent.com/4701338/63431688-b1f27d00-c41f-11e9-91b7-aba704d6b3fe.png)

These changes should likely be partially reverted, and a dedicated `PROPERTY_USAGE_*` flag should be used/added for paths that are meant to be saved as relative to the project root.

**Steps to reproduce:**
- Open Editor Settings > Export > Android
- Set path to adb or jarsigner

**Comment by SonerSound** [comment]
@akien-mga I'll work on a fix asap.
