### ISSUE TITLE
Godot doctool misses return/argument type for Variant and the various Resource types

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#3154]
KinematicBody2D.get_collider_metadata returns Variant, but after running doctool, the classes.xml says it returns void.

**Comment by akien-mga** [comment]
To fix it, it looks like we need to use:
```
diff --git a/scene/2d/physics_body_2d.cpp b/scene/2d/physics_body_2d.cpp
index c30921e..1dd1a39 100644
--- a/scene/2d/physics_body_2d.cpp
+++ b/scene/2d/physics_body_2d.cpp
@@ -1250,7 +1250,7 @@ void KinematicBody2D::_bind_methods() {
        ObjectTypeDB::bind_method(_MD("get_collider_velocity"),&KinematicBody2D::get_collider_velocity);
        ObjectTypeDB::bind_method(_MD("get_collider:Object"),&KinematicBody2D::_get_collider);
        ObjectTypeDB::bind_method(_MD("get_collider_shape"),&KinematicBody2D::get_collider_shape);
-       ObjectTypeDB::bind_method(_MD("get_collider_metadata"),&KinematicBody2D::get_collider_metadata);
+       ObjectTypeDB::bind_method(_MD("get_collider_metadata:Variant"),&KinematicBody2D::get_collider_metadata);
 
        ObjectTypeDB::bind_method(_MD("set_collision_margin","pixels"),&KinematicBody2D::set_collision_margin);
        ObjectTypeDB::bind_method(_MD("get_collision_margin","pixels"),&KinematicBody2D::get_collision_margin);
```
That could be done, but it likely means that all functions that return Variant would need a similar trick.

@reduz Would there be a way to enhance doctool so that it recognizes custom types out of the box?

**Comment by Ovnuniarchos** [comment]
This "fix" is already used by FileDialog.get_vbox() (and many others for sure). Not the best solution, indeed, but the best available as of now.

**Comment by reduz** [comment]
nothing to do, no way to detect that it's a variant return type.. might change all templates by 3.0 but for now it's the only way

**Comment by akien-mga** [comment]
> nothing to do, no way to detect that it's a variant return type.. might change all templates by 3.0 but for now it's the only way

Quoting @reduz from IRC, the issue is maybe not fully blocked:

> \<reduz> Akien, maybe it's possible, the binding system will be eventually have to be fixed to add languages such as .net so..
> \<reduz\> Maybe someone with more C++ experience can figure out a way to automatically detect that
> \<reduz\> it also may be possible in C++11

**Comment by akien-mga** [comment]
Also related, ConfigFile currently reports the return type for two of its methods as ``Error`` (like the enum): https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/core/io/config_file.cpp#L218-L219
But the online docs don't understand it, and I'm not sure if the editor knows what to do of it either. I guess such return types should be kept default (i.e. ``int``), and described in the methods descriptions.

**Comment by neikeq** [comment]
This madness is no more.
