### ISSUE TITLE
get_surface_material

### ISSUE THREAD

**Issue by roiteee** [godotengine/godot#31558]
**Godot version:**
Version 3.1.1 official

**OS/device including version:**
windows 10

**Issue description:**
**Steps to reproduce:**
I create a cube, uvw map it, create texture, import it to godot.
I create a new inherited scene from the exported dae file, The texture is applied correctly and shows up in the material. The problem is with accessing it from code.
I put a script in MeshInstance like this
extends MeshInstance

export(Texture) var box_texture

func _ready():
	print(get_surface_material_count())
	print(get_surface_material(0))
	var new_material = SpatialMaterial.new()
	new_material.albedo_texture = box_texture
	set_surface_material(0, new_material)
	print(get_surface_material_count())
	print(get_surface_material(0))

The result is like this:
** Debug Process Started **
OpenGL ES 3.0 Renderer: GeForce GTX 970M/PCIe/SSE2
1
[Object:null]
1
[SpatialMaterial:1146]

As you can see, even if the get_surface_material_count() sees the material, while getting the material using get_surface_material returns null object. On the other hand if I create a material on code and run the same print statements again, it shows correct SpatialMaterial.

**Minimal reproduction project:**
https://github.com/roiteee/godot_issue_surface_material

**Comment by clayjohn** [comment]
I think this reflects an issue with how the editor assigns materials.

**Comment by shafy** [comment]
If you do `surface_get_material(0)` on the Mesh, it should work. E.g.

```
$MeshInstance.mesh.`surface_get_material(0)
```

**Comment by Lexpartizan** [comment]
script on MeshInstance
var mat = mesh.surface_get_material(0) #Этот глюк есть на гитхабе!
print (mat)

Null
Still not working in 3.2 stable

**Comment by clayjohn** [comment]
Do you have your material assigned to the ``MeshInstance`` or to the ``Mesh``?

``Mesh.surface_get_material()`` returns the material assigned to a particular surface, while ``MeshInstance.get_surface_material()`` returns the surface material override.

**Comment by Zireael07** [comment]
Can't this be unified somehow (potentially with a new function) so that it gets the override or mesh material, whichever exists?

**Comment by clayjohn** [comment]
@Zireael07 Thats a good idea. Something like ``MeshInstance.get_active_material()``

**Comment by Lexpartizan** [comment]
Big Thanks!
The fact is that these methods are called very similar, but they are written a little differently.
MeshInstance.get_surface_material(0)
mesh.surface_get_material(0)
In the first case, the "get" is at the beginning, in the second in the middle.

I didn't notice this difference. And when you just caused Meshinstance this method, I thought that it does not exist.

**Comment by clayjohn** [comment]
@Lexpartizan I agree the naming is confusing. For 4.0 I would like to rename ``$MeshInstance.get_surface_material()`` to ``$MeshInstance.get_surface_override_material()``

**Comment by lukostello** [comment]
that would still have get at the beginning of 1 and the middle of the other. Instead of calling it get_active_material(), why not call it get_material()? Surely it isn't a stretch to infer that one wants the active one.

**Comment by colorworlds** [comment]
> @Lexpartizan I agree the naming is confusing. For 4.0 I would like to rename `$MeshInstance.get_surface_material()` to `$MeshInstance.get_surface_override_material()`

It may be out of date, but the `GeometryInstance` that the parent class of `MeshInstance`,  also provides a property called `material override`
