### ISSUE TITLE
Retrieve Port Number Assigned By System for NetworkedMultiplayerENET.

### ISSUE THREAD

**Issue by alexis-evelyn** [godotengine/godot#31557]
**Godot version:**
3.2-dev

**OS/device including version:**
All Systems

**Issue description:**
Feature Request:
I would like to be able to request the port number assigned by the system for NetworkedMultiplayerENET. When setting the port number to 0, the system automatically assigns a port to be used so I don't have to keep checking ports until I find a free one available.

I have started work on implementing this idea in [my copy of Godot](https://github.com/alex-evelyn/Godot-3.2-Sweet-Tea/commit/c9e87330223d396619fd3d12edb316177aa80db4). However, I am stuck at finding how to get ENET to give me the port number assigned by the system. I can get the user set port number by returning `host -> address.port;`. If I do figure this out before anyone else does, I will be sending in a pull request.

**Steps to reproduce:**
Look for get_port() function.

**Minimal reproduction project:**
None Needed

Note: I have tested using port 0 to make sure it works. I used netstat to find the port and connected to it from my client with no problem.

**Comment by alex-evelyn** [comment]
This is an example of what the GDScript code would look like after this feature is implemented.

```
...
if (net.create_server(server_info.used_port, server_info.max_players) != OK):
	...
print("Port: ", net.get_port())
```

**Comment by alex-evelyn** [comment]
I believe I almost got the feature working. I am just having trouble getting the file descriptor from NetSocket (I know almost nothing about c++, so this is a new challenge for me).

```
int enet_socket_get_port(ENetHost * host) {
	// getsockname(...) - https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxbd00/getsn.htm
	// Example of getsockname(...) - https://stackoverflow.com/a/6660056/6828099

	NetSocket *sock = (NetSocket *) host -> socket;

	struct sockaddr_in sin;
	int addrlen = sizeof(sin);
	if(getsockname(sock -> qfd, (struct sockaddr *) &sin, &addrlen) == 0 &&
	   sin.sin_family == AF_INET &&
	   addrlen == sizeof(sin))
	{
	    return ntohs(sin.sin_port);
	}
	else
	    return -1; // handle error
}
```

**Comment by Faless** [comment]
@alex-evelyn you should implement `getsockname` in a wrapping function in the NetSocket class, and then call that wrapper function from the ENet code. (2 functions maybe? `get_socket_address` and `get_socket_port`?)
Relevant files:
https://github.com/godotengine/godot/blob/master/core/io/net_socket.h (interface)
https://github.com/godotengine/godot/blob/master/drivers/unix/net_socket_posix.h (implementation header)
https://github.com/godotengine/godot/blob/master/drivers/unix/net_socket_posix.cpp (implementation)

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/48235, closing.
