### ISSUE TITLE
Possible bug with importing .tres file with HTerrain plugin

### ISSUE THREAD

**Issue by Altair1234** [godotengine/godot#31559]
3.1

Minimum steps to reproduce:

Download and enable Zylann's Terrain plugin. Create node "HTerrain", make new resource with HTerrainData as a .tres file. Then go to HTerrain's data field and try to load HTerrainData file. Clicking on the saved .tres file makes the Open button unclickable.

The workaround is to type the path to the file: res://HTerrainData.tres

**Comment by Zylann** [comment]
Does this reproduce with regular .tres?
Would be interesting to try with a minimap addon registering a custom resource loader

**Comment by Altair1234** [comment]
In your vid from last year isn't that how you did it? You opened a new resource, loaded HTerrainData into the Data field and saved it as test.tres. I'm new so it's possible I'm making a silly mistake but I don't see where. You then went to the HTerrain node and loaded test.tres from there.

**Comment by Zylann** [comment]
It was a video for the 0.8 version of the plugin. This part has changed since.

**Comment by Altair1234** [comment]
If you don't mind, could you tell me how to do it now? It's a really important plugin.

**Comment by Zylann** [comment]
@Altair1234 now you don't even need to create the data resource. You just create the terrain node and choose a folder, the data will be written inside automatically.

**Comment by KoBeWi** [comment]
Is this a bug in Godot or it's only related to the plugin? If the latter, I guess it could be closed.

**Comment by Altair1234** [comment]
@KoBeWi I thought it was a bug in Godot but that doesn't seem to be the case so closing the issue.
