### ISSUE TITLE
ScrollContainer cannot be scrolled by dragging inside it using a mouse input

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#31553]
3.1.1 on Windows 10, HTML5 on chrome browser and firefox browser

The ScrollContainer can be scrolled only if you drag a *touch input* inside it, as far as I know.
On HTML5, on android, ScrollContainer is able to be dragged from inside as it detects touch input.
However, I have found that on HTML5, on Windows (not sure about LINUX/MAC), the ScrollContainer is NOT able to be dragged from inside. EVEN WHEN Emulate Touch From Mouse is turned on in project settings/input devices/pointing
-I hypothesize that when HTML5 is on windows(or non mobileOS), it will change any touch input to a mouse input? and a scrollcontainer will only drag from inside if it is a touch input.

Is there a way to get this to work  on PC HTML5?

If not, I propose that Dragging from the inside be allowed with mouse input as well, and an option to allow dragging from the inside can be turned on/off in the inspector.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
