### ISSUE TITLE
Autoload singleton not recognized as a valid identifier

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3156]
I've pushed changes in my game to use the new autoload singleton and onready features (as of latest HEAD), but it does not seem to work properly: https://github.com/akien-mga/dynadungeons/tree/autoload-singleton

The "global" autoload is enabled for use as a singleton, but running the game gives:
```Parse Error: Identifier not found: global```

I could not reproduce the issue easily in a minimal project, so for now I propose the above mentioned branch as a way to reproduce. I'll have to investigate further.

**Comment by akien-mga** [comment]
When editing my scripts in the editor, the auto-completion seems to work fine for the global autoload - but it still gives the same "Identifier not found" error on launch.

**Comment by akien-mga** [comment]
The parsing issue happens even if the script is not used, e.g. if I try to run my ```scenes/level.tscn``` scene, it will raise an error in ```scripts/menu.gd``` even though the latter is not used by the scene I wanted to load.

**Comment by Calinou** [comment]
In Veraball, I need to manually declare it in two scripts:
https://github.com/Veraball/veraball/blob/master/data/scripts/autoload/game.gd#L23-L25
https://github.com/Veraball/veraball/blob/master/data/scripts/hud/main.gd#L3-L4

**Comment by volzhs** [comment]
I made a simple project to reproduce this. [Here is the project zip file.](https://drive.google.com/file/d/0ByuhCIzeus36VzRkYUs5MGE1WG8/view?usp=sharing)

What I did with this project is...

after import and open project,
you can see these logs. (seems like some another bug... anyway)

```
no access to /global.gd
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/windows/file_access_windows.cpp:249
no access to /icon.png
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/windows/file_access_windows.cpp:249
no access to /new_scene.scn
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/windows/file_access_windows.cpp:249
no access to /test.gd
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/windows/file_access_windows.cpp:249
no access to /unused_scene.gd
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/windows/file_access_windows.cpp:249
no access to /unused_scene.scn
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/windows/file_access_windows.cpp:249
no access to /unused_script.gd
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/windows/file_access_windows.cpp:249
```

after open ``res://unused_scene.scn`` from **FileSystem panel** or **Open Scene panel**(Ctrl+O).
then you can see these logs.

```
ERROR: GDScript::reload: Compile Error: Identifier not found: global
   At: res://unused_script.gd:3
ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules/gdscript/gd_script.cpp:1872
```

now **Quit to Project List** and open this project again.
then you can see there logs again at launch editor.

```
ERROR: GDScript::reload: Compile Error: Identifier not found: global
   At: res://unused_script.gd:3
ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules/gdscript/gd_script.cpp:1872
```

**Comment by kubecz3k** [comment]
The bug is valid for me also, I reproduced it in 79c1392d17156aeb8d6a2abca16db59b1f8312cc build

**Comment by reduz** [comment]
cool, i' ve been waiting to fix this one for a bit and focused on simpler
bugs first, as soon as I have a little more time I'll close the few
remaining ones and work on a beta release

**Comment by reduz** [comment]
well, it seems this is fixed and closed

**Comment by zatherz** [comment]
Happens with `tool` scripts on latest master.

**Comment by akien-mga** [comment]
Please open a specific bug report, this one was fixed.

**Comment by kubecz3k** [comment]
@zatherz yes, tool autoloads are simply not supported :(
