### ISSUE TITLE
Scene Editor add option to clear all guides

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31576]
**Godot version:**

3.1

**Issue description:**

Right now there is no option to clear all user made canvas guides, requiring you to manually remove each individual guide. An option to clear all could be added under the view menu.

**Comment by 2shady4u** [comment]
Heyo I'm working on this one 😄 

![Untitled](https://user-images.githubusercontent.com/42484461/63546026-0c2b3500-c529-11e9-94c4-98e41b7f8edd.png)

Any preferences on the shortcut and placement in the View menu???

**Comment by 2shady4u** [comment]
Added this functionality in #31585

**Comment by netpoetica** [comment]
Is there any way to clear the guides at all, or are they just permanently in once you put them? The googles are short on answers to this question. I'm not seeing anything in the editor for removing guides?
