### ISSUE TITLE
Questions and ideas for improvement

### ISSUE THREAD

**Issue by bodamat** [godotengine/godot#31574]
**Godot version:** 3.1

**Issue description:** advice

Good day. Your game engine is the best. Thank you very much.

I start worry about your work, so I had a question: "Why did you choose a MIT license rather than a GNU license?" I am afraid that no one will steal or sell your work under self name. Instead of closing the code and selling it, they want to help you develop who is really interested.

P.S. I plan to join the development of the best game engine in the near future.

**Comment by TheDuriel** [comment]
Ok.

**Comment by Calinou** [comment]
The MIT license was chosen for Godot because of its simplicity. It's very easy to comply with, including on mobile platforms and consoles (where using GPL-licensed code is difficult, if not impossible).

So far, many people are contributing to Godot's source code even if it's permissively licensed, so I don't think we need to change the license to get people to contribute :slightly_smiling_face:

See [Complying with licenses](https://docs.godotengine.org/en/latest/tutorials/legal/complying_with_licenses.html) in the documentation for more information.

**Comment by KoBeWi** [comment]
> (including on mobile platforms and consoles where using GPL-licensed code is difficult, if not impossible).

Yeah, GPL is generally incompatible with this stuff. However, if software creators decide so, they can breach their own license and still release their app/game on proprietary platform. It happened in an open-source game I'm following (they ported to iOS) and cause one user to write a very very **very** long rant how it was a bad practice and it hurts FOSS and how the devs are evil and shady doing this XD

**Comment by akien-mga** [comment]
A copyleft license can't work for a general purpose game engine where people ship games that are derivatives of the software. If Godot was GPL, no serious developer would touch it with a ten foot pole, as they would believe that it would not allow them to release proprietary games (whether that's true could be debated by lawyers, but the simple fact that people would not be sure would be detrimental to Godot's use).

Permissive licensing works fine for a project like Godot with hundreds of contributors every month. We really don't need to force people to contribute back to get the base engine growing and getting better for everyone :)

**Comment by akien-mga** [comment]
As a side note, please refrain from opening issues to ask questions, or with a generic title like this one. This is an issue tracker for engine bugs or actionable feature requests, i.e. issues that can be debugged, implemented and closed. We do have discussions from time to time but only on technical engine-related topics, not general musings about licensing.

For such questions, it's best to use one of the other community platforms: https://godotengine.org/community

**Comment by bodamat** [comment]
Ok. Thank you!
