### ISSUE TITLE
OS_Unix::execute - Could not create child process

### ISSUE THREAD

**Issue by IronicallySerious** [godotengine/godot#31577]
**Godot version:**
3.2

**OS/device including version:**
Linux Ubuntu 18.04

**Issue description:**
Double clicking any file in the filesystem dock doesn't do anything, expect opening the file in the Inspector. Expected behaviour is to open the file in the script editor.

Not errors pop up in the Output tab but I see this string output in the program output:
```shell
**ERROR** OS_Unix::execute - Could not create child process while executing: 
```

Tried changing executable permissions to 755 and running with `sudo`, with no success.

**Steps to reproduce:**
1. Open the demo project
1. Double click `new_script.gd` in the filesystem dock  

**Minimal reproduction project:**
[demo.tar.gz](https://github.com/godotengine/godot/files/3531451/demo.tar.gz)

**Comment by akien-mga** [comment]
Sounds like you configured an external editor and it's not in PATH?

**Comment by IronicallySerious** [comment]
Yes, that was the issue. Turned off the external editor from the editor settings.
