### ISSUE TITLE
Minimap region color is hard to see

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#31584]
Godot 3.2 ccf294b92f02af6e60206e220dcf4a8474f73f0a

Maybe that's related to my syntax theme, but I can hardly see it:

![image](https://user-images.githubusercontent.com/1311555/63549620-afc81580-c528-11e9-8fe3-4e220cd511cf.png)

It uses the color of the current line, but I believe it should have its own?

**Comment by Calinou** [comment]
It would make sense to reuse a translucent variant of the accent color, so that it can be visible even if the user uses a syntax theme where the current line color is barely visible:

```cpp
// Accent color with 40% opacity
Color selection_color = get_color("accent_color", "Editor") * Color(1, 1, 1, 0.4);
```
