### ISSUE TITLE
[Mono] Windows export template - Core API hash mismatch

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#31581]
**Godot version:**
v32.dev.mono 4ab4d4a59

**OS/device including version:**
Windows 10 x64

**Issue description:**
Mono Windows export templates crash at start, outputting "Core API hash mismatch" on the console.
![image](https://user-images.githubusercontent.com/10672233/63654101-3872cb80-c74c-11e9-8445-4d88018fdaa5.png)

if I decide to give it the mscorlib I suppose it wants (the same the editor is using), I get this
![image](https://user-images.githubusercontent.com/10672233/63654183-4e34c080-c74d-11e9-9827-441578998a72.png)

Glue is current, generated for the build. The editor works as expected.

**Steps to reproduce:**
Build mono editor and export templates, export any project and run it.

**Minimal reproduction project:**
\-

**Comment by Anutrix** [comment]
Can you provide the mono_logs file?

**Comment by piratesephiroth** [comment]
The log file has only 3 lines:

```The 'log' profiler wasn't found in the main executable nor could it be loaded from 'mono-profiler-log'. (in domain Mono, critical)```
```Config attempting to parse: 'C:\Users\ADMIN\Documents\Godot\export/data_PlatformerTest-proto/Mono/etc\mono\config'. (in domain Mono, info)```
```Assembly Loader probing location: 'C:\Users\ADMIN\Documents\Godot\export/data_PlatformerTest-proto/Mono/lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)```

**Comment by Anutrix** [comment]
Maybe related to https://github.com/godotengine/godot/issues/29005?

**Comment by piratesephiroth** [comment]
> 
> 
> Maybe related to #29005?

Most certainly. Funny how the exported game demands that in order to work and the editor doesn't.

**Comment by piratesephiroth** [comment]
Well, actually it's not that either. I went to the project settings and disabled the profiler.

Now the console complains about mscorlib and the log has only the other 2 lines

```Config attempting to parse: 'C:\Users\ADMIN\Documents\Godot\export/data_PlatformerTest-proto/Mono/etc\mono\config'. (in domain Mono, info)```

```Assembly Loader probing location: 'C:\Users\ADMIN\Documents\Godot\export/data_PlatformerTest-proto/Mono/lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)```

I've updated the issue

**Comment by piratesephiroth** [comment]
#32022 fixed the debug template but the release one now crashes on start without displaying any error message. It also creates empty log files.

**Comment by neikeq** [comment]
I cannot reproduce this. Do you see any error in the terminal during export?

**Comment by piratesephiroth** [comment]
Nope, no errors at all. It says the usual "Build succeeded, 0 warnings, 0 errors"
Still on the same Windows 10 x64, Visual Studio 2019. Mono v5.18 if it's anything relevant.
Latest commit (24e1039eb).
Just closes abruptly without displaying any error message even if I launch it via command line.
Creates a log file but writes nothing to it..

Also the debug template seems to run fine but the console still disaplys the message:
ERROR: GDMono::_initialize_and_check_api_hashes: Mono: Core API hash mismatch.

**Comment by neikeq** [comment]
The API hash mismatch is a known issue that will be fixed soon. Nevertheless it's not critical and should not have any negative effect.

Even though it doesn't crash for me, I cannot get any terminal output when running the release export templates on Windows somehow.... Is this normal or does it only happen with builds that use the mono module?

**Comment by piratesephiroth** [comment]
>Even though it doesn't crash for me, I cannot get any terminal output when running the release export templates on Windows somehow.... Is this normal or does it only happen with builds that use the mono module?

It seems to be the case, at least for v3.2
