### ISSUE TITLE
Display all compatible resources when creating one in the resource slot

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#31591]
This is just a minor usability thing:

I created a custom resource inheriting `ShaderMaterial` using a GDScript plugin:
![grafik](https://user-images.githubusercontent.com/3957610/63575970-92786300-c58b-11e9-8d35-595ce3a576e5.png)

I can assign it into any material slot without problems but creating it in memory is still a bit cumbersome as it isn't listed in the material slots:
![grafik](https://user-images.githubusercontent.com/3957610/63576303-2813f280-c58c-11e9-92d7-7e6d622be106.png)

It would be nice if all compatible resource types would be displayed there. Currently I'm creating the resource in the inspector and I copy it into the target slot using the copy/paste functionality.

I understand that this is a very minor thing that probably requires a complex fix but I thought it was worth mentioning.

**Comment by Phischermen** [comment]
Hello @CptPotato.
Could you upload your project? I was thinking about taking a look at this issue.

**Comment by Phischermen** [comment]
Actually never mind, I was able to set something up myself. I also just got it fixed! I'll set up a pull request shortly.

**Comment by TechnoPorg** [comment]
I believe this was fixed by #62413.

**Comment by Calinou** [comment]
Closing per @TechnoPorg's comment.
