### ISSUE TITLE
Static body ignores collision when used with conclave collision shape

### ISSUE THREAD

**Issue by Garrom** [godotengine/godot#31603]
**Godot version:**
3.1.1 Official Stable

**OS/device including version:**
Lenovo Laptop B50-80. Intel dual core 1.9 Ghz ICPU. Mesa DRI Intel(R) Broadwell GT1 IGPU. Linux Mint Debian Edition

**Issue description:**
(In 3D) When I add concave collision shape to static body or to rigid body in static mode, collision stop working. Everything can pass through object and area ignores it too. But it still can be picked by raycast node. This include any collision shape that was imported into Godot from blender using `-colonly` suffix because Godot will import it as conclave no matter if it is conclave or convex shape. Everything works if I use on of Godot's primitive mesh colliders like cylinder or box

**Comment by Zylann** [comment]
Which physics engine are you using? Bullet or GodotPhysics? Does that happen if you create a concave collision shape *from the editor*?

**Comment by Garrom** [comment]
> Which physics engine are you using? Bullet or GodotPhysics? Does that happen if you create a concave collision shape _from the editor_?

I have no idea what physics engine I'm using. I never set it up so I guess default one. I navigated to my mesh instance node and created "trymesh" collision, unfortunately observed same result so we can exclude my crappy 3d modeling ability from list of possible causes of problem.

**Comment by Garrom** [comment]
Apparently, two conclave shapes just can't collide with each other. I'm closing issue as I understand now why it is like this and it is excepted behavior not issue
