### ISSUE TITLE
horrific performance on android (3D)

### ISSUE THREAD

**Issue by grusad** [godotengine/godot#31601]
**Godot version:**

Godot 3.1.1

**OS/device including version:**

PC: RTX 2080 ti, i7... a monster
Android: Galaxy s10

**Issue description:**

Well im having a simple 3D scene containing a small gridmap (something like 15x15), a player, 3 mobs running around, and some sprite3D laying around in the gridmap. On my PC a get over 1,5k FPS in fullscreen mode, and on my android phone its unplayable.. maybe around 10fps? 

So what is going on here? Should i exclude 3d in android dev using Godot?

**Comment by Calinou** [comment]
By default, Godot will render in the device's native resolution. This resolution is very high on high-end smartphones; it makes sense to lower it. To do so, go to the **Project Settings** and set the window width and height to 1280 and 720 (or 720 and 1080 for a game in portrait mode). Then set the stretch mode to `viewport` and the stretch aspect to `keep`.

See [Multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) in the documentation for more information.

**Comment by grusad** [comment]
@Calinou I tried GLES2, and adjusted the settings that u mentioned, and the fps didnt increase that much.. And i lost depth test on all objects :'D Ill have to stick to desktop version with the game, unfortunately. I dont even  know if this should be issued on github or not...

**Comment by Calinou** [comment]
@grusad Some features like real-time shadows are very taxing on mobile GPUs, so you will likely have to live without them if you're targeting mobile devices (use baked lightmaps instead).

**Comment by lawnjelly** [comment]
> So what is going on here? Should i exclude 3d in android dev using Godot?

This might not be a godot issue, just a guess are you new to developing for mobile / non-desktop platforms?

Mobile in particular is a lot more limited in terms of horsepower than desktop, particularly with graphics. If you are aiming for mobile release it is a good idea to do performance testing early and throughout development so you can get an idea of what is and isn't feasible.

Fill rate in particular is often very low, and mobiles often use tile rendering so the bottlenecks can be different than on desktop. Overdraw, transparency, and things like shadows can kill performance, and simpler shaders are likely to work better.

**Comment by grusad** [comment]
@lawnjelly I am pretty novice at mobile dev. The thing is that my scene that i tried to render on my galaxy s10 should not be a problem to run, i cant imagine that anyways. Havnt had the time to try to replace my sprite3D to a quadmesh to see if that fixes the problem yet..

**Comment by Jayanth-L** [comment]
> @lawnjelly I am pretty novice at mobile dev. The thing is that my scene that i tried to render on my galaxy s10 should not be a problem to run, i cant imagine that anyways. Havnt had the time to try to replace my sprite3D to a quadmesh to see if that fixes the problem yet..

Hello grusad i would recommend you to remove the Procedural sky and set it to Clear Color and also adjust the Ambient Light, You will see FPS Shooting up in GLES3

The main Bottleneck here is actually the Sky and its prperties like light and shadows, according to my experience with GLES3

**Comment by kruglinski** [comment]
I think the weakest chain of Godot is 3D assets pipeline not the renderer.

I backport godot-sponza(from @Calinou ) to Godot 2.1, fix some core engine bugs including one in material.glsl(Godot 2 BakedLightmap is broken in iOS). and use BakedLightmap I'm able to running this scene in 60 FPS for both vivo z3(Qualcomm Snapdragon 710) and iPhone 6SP(A9)

![psb](https://user-images.githubusercontent.com/2869425/65208838-cb432380-dac8-11e9-961b-537b5c4b45ac.png)

generally In mobile platform you use realtime shadow as less as possible, if you must have shadow you use only one DirectionalLight

**Comment by shivmsit** [comment]
> godot-sponza

I tried godot-sponza with godot 3.1.1, performance is very poor it's struggling to achieve 6-7 fps for machine with
2.8 GHz Quad-Core Intel Core i7
NVIDIA GeForce GT 750M 2 GB
macOS

**Comment by clayjohn** [comment]
@shivmsit this issue is about Android performance, not macOS. Please search for an issue relating to macOS or open a new issue.

**Comment by mahdisml** [comment]
this video show Godot have poor performance in android :
[Youtube Video : Godot vs Unity Performance Android/Windows ](https://www.youtube.com/watch?v=mZy3H0XK51U)

**Comment by Calinou** [comment]
@mahdisml Please don't derail the discussion with off-topic comments.
