### ISSUE TITLE
Improve image loading performance in the asset library

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#31614]
**Godot version:** Git https://github.com/godotengine/godot/commit/791d7f78b52f5b828aa5541897e12c6a1861ef6f

**OS/device including version:** Fedora 30

**Issue description:** Currently, icons in the editor asset library load quite slowly, despite their small size. In comparison, they load much faster on the [web interface](https://godotengine.org/asset-library/asset) (on the same PC and connection, that is). Maybe this is due to suboptimal use of HTTPClient?

**Steps to reproduce:** Open the asset library in the project manager or editor.

**Comment by Daw11** [comment]
One problem is that only two images can be downloaded at the same time.

https://github.com/godotengine/godot/blob/57589a767dcb52063bd891eb8cb8544829278bbf/editor/plugins/asset_library_editor_plugin.cpp#L848

Browsers nowadays allow to download around 10 images simultaneously from the same domain and even more if they are from different sources.

Another problem is that the every request opens and closes the connection to the server, even if it's the same. There should be a way to group all the requests together and tell them to keep alive the connections till the whole page is loaded.
