### ISSUE TITLE
Particle billboards do not work on all computers

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot#31612]
**Godot version:**
3.1.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
Particle billboarding works on most computers, but not all. The computer in which this failed uses AMD Radeon(TM) HD8490.

**Steps to reproduce:**
Test on various different GPUs.

**Comment by clayjohn** [comment]
Does this happen in both GLES2 and GLES3? Also what about latest master?

**Comment by kakoeimon** [comment]
Are you sure you are using quads in the pass? Other types (I haven't tested all of them) give different results of unknown usability yo me.

**Comment by QbieShay** [comment]
@clayjohn can confirm on my Radeon 590, version 3.2-a03af876d1a8c30723021bc60ce10d38d2a8d534.
Broken for both CPU and GPU particles, both in gles3 and 2

**Comment by Calinou** [comment]
@OriginalAGP @QbieShay Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

(Also, can you describe what happens by "not working"? Is there nothing appearing on screen, and do you get error messages?)

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
