### ISSUE TITLE
`OS.execute()` on Windows shows a command window, but only when run from a release export template

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#31623]
**Godot version:**
Latest 3.2 Dev

**OS/device including version:**
Windows 10

**Issue description:**
This should have been resolved by #26674 but it seems that if a project is exported without the debug tools the console windows still apear. With the debug tools enabled the consoles are not visible.

![Screenshot_3](https://user-images.githubusercontent.com/1850856/63634602-7515c880-c661-11e9-9bb4-530d5875728b.png)

**Sample Project**
[Execute test.zip](https://github.com/godotengine/godot/files/3537005/Execute.test.zip)
* You will have to export the sample project without debug tools in order to replicate the issue.

**Comment by zaksnet** [comment]
I have been downloading externals from https://hugo.pro/projects/godot-builds/. Turns out that after rebuilding externals myself it started working as expected.

**Comment by williamd1k0** [comment]
I don't know why, but I'm still having this issue.
I'm using Godot 3.2.1-stable. I also tried recompiling the template with both mingw (manjaro) and msvc (win10).

I made a minimal reproduction project with OS.execute() being called on the main thread and on another thread.
[windows-console-bug.zip](https://github.com/godotengine/godot/files/4697589/windows-console-bug.zip)

**Comment by zaksnet** [comment]
> 
> 
> I don't know why, but I'm still having this issue.
> I'm using Godot 3.2.1-stable. I also tried recompiling the template with both mingw (manjaro) and msvc (win10).
> 
> I made a minimal reproduction project with OS.execute() being called on the main thread and on another thread.
> [windows-console-bug.zip](https://github.com/godotengine/godot/files/4697589/windows-console-bug.zip)

Indeed i can confirm this is the case. @williamd1k0 i have ended up using C# [Process class](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=netcore-3.1)

**Comment by Onusai** [comment]
I'm also having this issue.
Windows 10
Godot Engine v3.2.3.stable.official

**Comment by Calinou** [comment]
>  Cant release project until this is fixed because no one is going to trust a program that keeps opening a bunch of console windows lol.

You could export your project with debugging enabled to prevent the focus from being stolen. I suppose this happens in release mode only because the application is compiled in GUI mode, which means running the base application won't spawn a command window.

**Comment by bruvzg** [comment]
What command is causing the issue? If it's something like `OS.execute("CMD", ["/c dir"], false)` (from the MRP in the first post), `CMD` itself probably will open a new console window. If it is try running target app directly.

Also, blocking mode with redirection (e.g. `OS.execute("CMD", ["/c", "dir"], true, output)`), probably won't work at all:
```
If used in a Windows program, the _popen function returns an invalid file pointer that causes the program to stop responding indefinitely. _popen works properly in a console application.
```

**Comment by Onusai** [comment]
From what I've tested, OS.execute opens a new console window regardless of what the target is.

examples:
OS.execute("start", ["c:"])
OS.execute("program.exe", ["arg"])
OS.execute("notepad", [])

**Comment by mrjustaguy** [comment]
Also opened with a full path to what it's opening, however I've noticed that in the Godot Editor when I run the project and run the command, it doesn't open a window, probably because it's using the Godot Editor console that is hidden so it doesn't unhide that..
Possible fix would be to just extend the execute function with "hide system console" in a way that the editor does it's hiding.

**Comment by ztc0611** [comment]
Any chance this gets fixed in 3.5, or will I just have to wait for 4.0?

**Comment by bruvzg** [comment]
It should be already fixed in 3.x - https://github.com/godotengine/godot/pull/55987

**Comment by ztc0611** [comment]
> It should be already fixed in 3.x - #55987

Still happening to me on 3.4.3.stable, unforunately.
