### ISSUE TITLE
Adding project heirarchichal view mode to related scenes

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#3162]
Add a viewer to Project's root node hierarchical relationship to all referenced nodes in the project. When the project grows, finding the relationship between scenes becomes awkward and hard to maintain. By adding a Project mode, "Scene" like tab to show heirarchy of the object (a ListTree would suffice). It would make working with Godot more robust than ever.

In the Instancing wiki tutorial: see the following image.
https://github.com/godotengine/godot/wiki/images/shooter_instancing.png

If Godot can show this kind of relationship between scenes it would be awesome.

I am coming from Game Maker Studio Pro, and I really hate to compare it with Godot since both
are excellent, and both have different ways of doing the management. But at least Game Maker Studio
does have excellent project viewer. It even creates logical filter "Folders" for resources or Rooms (Scenes) in the Project's ListTree.

Please consider adding this feature.

**Comment by reduz** [comment]
I'm not sure how neat this would look, as most of this happens via code...
sounds like the job for a plugin, when plugins are finally made to work in
2.1

**Comment by KoBeWi** [comment]
There's this plugin: https://godotengine.org/asset-library/asset/108

**Comment by akien-mga** [comment]
Closing as solved by https://godotengine.org/asset-library/asset/108 then.
