### ISSUE TITLE
Large scene size on making material unique

### ISSUE THREAD

**Issue by epuscasu** [godotengine/godot#31632]
**Godot version:**
3.1.1

**Issue description:**
Loading a .gltf file (exported by blender) and saving it as a scene after making its material unique results in huge file size (~200MB compared to .gltf's 7MB size). Scene saved without unique material is under 200KB. This leads to huge load time increase.

Not sure if this is intended behavior, the size increase just seems odd.

**Steps to reproduce:**
Load gltf file, make material unique, save scene.

**Minimal reproduction project:**
Not project, but the blender file to be loaded/exported as gltf and saved as scene (part of this tutorial - https://www.youtube.com/watch?v=XMfiojwtuKo):

http://bit.ly/godot3-5blend

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by capnm** [comment]
> Can anyone still reproduce this bug in Godot 3.2.3 rc6 or any later release?

No, although the linked Blender-Project state is not suitable for export for a game, the size of the Godot's material file is around 27 MB. I think you can close the issue.
