### ISSUE TITLE
Changing the size of a CubeMesh doesn't change its selectable area

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#31633]
Godot 3.1.1
Windows 10 64 bits

Repro:
1) Create a MeshInstance with a CubeMesh in it
2) Change the CubeMesh size from (2,2,2) to (16,16,16)
3) Notice you can't select the cube from the viewport anymore, unless you click near its origin
4) Select another node: notice now you can select your cube mesh

**Comment by KoBeWi** [comment]
Still valid in 1777211

**Comment by capnm** [comment]
> Notice you can't select the cube from the viewport anymore, unless you click near its origin

The algorithm seems to select by hitting the wires, not a BB or faces. Therefore, you cannot select an almost empty cube mesh.
Try  in the wireframe view selecting the cube wire near the corner (or a cylinder between the wires)  ...

(3.2 branch tip)
![grafik](https://user-images.githubusercontent.com/4047289/93383220-9b596800-f863-11ea-942e-3eaaf204682c.png)

**Comment by KoBeWi** [comment]
Ok, somehow this is fixed in 64d3827. It's not critical to fix this in 3.2.x, so closing.

**Comment by capnm** [comment]
@KoBeWi nothing changed on the 3.2 tip for me ...

**Comment by KoBeWi** [comment]
Yeah, but it has an easy workaround. The biggest problem with backporting the fix is that someone has to find out which commit fixed this.
