### ISSUE TITLE
Why raycasts are disabled by default?

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31637]
**Godot version:**
89bcfa4

**Steps to reproduce:**
1. Create a RayCast(2D) node
2. Add some code and stuff
3. Try it
4. Oh, it doesn't work. You forgot that the Raycast you just wanted to use isn't enabled by default

**Issue description:**
Why tho? If I add a Raycast, I most likely want to use it. And raycast is supposed to be working all the time to, you know, actually detect something. Couldn't the `enabled` property be ON by default? Is really no one else bothered by this? >_>

**Comment by slapin** [comment]
Well, if you're not careful raycasts can hog your CPU and having them disabled by default is more newbie friendly. And ticking one checkbox as you go (or adding one line of code) is not really a big deal. Also for more complex games you want to control when your raycasts happen, so it is better to keep them disabled at all times and enable when needed.

**Comment by KoBeWi** [comment]
Newbies don't make complex games. They just need this one raycast. I can't see how it's newbie-friendly, when it might cause confusion. And even if you are experienced, raycasts might catch you off-guard when you don't use them too often and you waste a minute or two.

**Comment by TheDuriel** [comment]
Agreed, Raycasts should be on by default. Performance is really not a factor here. You can have thousands of them before you will even notice.

If anything the performance argument should be made for collision shapes. Which are drastically more expensive, but on by default. (And it would still be silly to have them off by default.)

**Comment by slapin** [comment]
@TheDuriel well, maybe for 2D  you cah have thousands of them, but not for 3D, people have to implement raycast schedulers for well under 1000 raycasts per frame on much more mature engines, because they cost time and doing something you don't need to do at short precious frame time is a bad thing. I'd vote for status quo as it is not really big deal discussed here. I prefer my beard under blanked and you don't need to change anything. Bingo!

**Comment by Janders1800** [comment]
Yeah, they should be on by default, It's pretty annoying to have to manually activate then every time I create a new one. As TheDuriel said collision shapes are on by default, and they're more expensive than Raycasts even for 3D.

**Comment by Calinou** [comment]
I agree RayCasts should be enabled by default as well, but this will have to wait for 4.0 as to not break existing projects.

**Comment by SolarLune** [comment]
Yes, it's probably best to enable as default. 

I feel that it is more confusing for devs to add a raycast only for it not to work intentionally than it is to add 1000 raycasts and then wonder why their game is running slowly.

**Comment by hazarek** [comment]
I found myself here trying to figure out what's wrong with Raycast2d. I was almost crazy. 
v3.5.beta1.official [b9b23d222]

**Comment by Calinou** [comment]
For future reference, RayCast nodes are now enabled by default in 4.0: https://github.com/godotengine/godot/issues/31637

This change can't be backported to `3.x` to preserve compatibility with existing projects.
