### ISSUE TITLE
How to create a module class ?

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#31634]
I know how to create singleton with gdscript
```
Engine::get_singleton()->add_singleton(Engine::Singleton("Summator", memnew(Summator)));
```
use right way:
```
if Engine.has_singleton("Summator"):
	var s = Engine.get_singleton("Summator")
}
```

I don't know how to creat a module. the module class don't work with godot software. It only build '*.a' file for xcode.
if write like tech code : https://docs.godotengine.org/en/3.1/development/cpp/custom_modules_in_cpp.html
it show class don't defined.

create module code
```
ClassDB::register_class<Summator>();
```
use module code: (error with class not found)
```
var s = Summator.new()
```

**Comment by Dimev** [comment]
Make sure to build the entire engine, with your module under godot\module\your_module_name

**Comment by zszen** [comment]
@Dimev "build the entire engine" online offical teach link ? thanks

**Comment by Dimev** [comment]
I'm assuming for mac, because you are using XCode.
Here's the documentation: https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_osx.html

**Comment by zszen** [comment]
@Dimev Yes, I use macos. 
Is this doc mean I can use "scons" command re-create a new godot.app file ?

**Comment by Dimev** [comment]
Yes.
download the godot source, add your module under the modules directory and build using scons

**Comment by zszen** [comment]
@Dimev very thanks. I will try it.
