### ISSUE TITLE
is_between() method

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31639]
**Godot version:**
89bcfa4

**Issue description:**
There are many useful built-in methods that do different kinds of things. One time, when writing a condition inside `_process()`, I thought that we could have something like `is_between(a, min, max)`, which would be just short for `if a >= min and a <= max`. This might be useful when you want to put an expression for `a`, so you don't need a new variable and don't need to write the expression twice.

**Comment by Garrom** [comment]
I agree, that sounds very usefull

**Comment by akien-mga** [comment]
I don't see much point, `is_between(a, min, max)` is not much shorter than `a >= min and a <= max`, and the latter is more explicit, especially regarding whether the bounds are considered in the interval or not. If we add this, some users will want `is_strictly_between` for `a > min and a < max` or `is_between_min_and_strict_max` for `a >= min and a < max`.

> This might be useful when you want to put an expression for `a`, so you don't need a new variable and don't need to write the expression twice.

I don't understand that, why do you need a variable? The proposed `is_between(a, min, max)` would be the same as `a >= min and a <= max`, no variables are needed.

**Comment by KoBeWi** [comment]
> I don't understand that, why do you need a variable?

If `a` is a result of some complex calculations, like `some_non_trivial_function()`

then you either repeat it twice
`if some_non_trivial_function() >= -10 && some_non_trivial_function() <= 20`
or "cache" the result
```
var a = some_non_trivial_function()
if a >= -10 && a <= 20
```
With `is_between()` this becomes just `is_between(some_non_trivial_function(), -10, 20)`. That's literally why I thought about this function.

**Comment by groud** [comment]
I agree with @akien-mga on this one, the inclusion of the boundaries is not clear (or would need other arguments) and the gain isn't that significant.

**Comment by dalexeev** [comment]
Maybe `min <= a <= max`, like Python?

**Comment by KoBeWi** [comment]
Closing in favor https://github.com/godotengine/godot-proposals/issues/889
