### ISSUE TITLE
Rename the editor setting for the minimap

### ISSUE THREAD

**Issue by merumelu** [godotengine/godot#31631]
**Godot version:**
3.2.dev f2777c0

**Issue description:**
The setting for the new code editor minimap is "*Draw* Minimap" while other settings use "*Show* \<thing>".
And maybe it's just me but "Line Numbers" doesn't seem like the most adequate category for it either.

**Comment by Cykyrios** [comment]
I agree "Show Minimap" would be more consistent with other settings.
Would "Open Scripts" be a more appropriate category for the minimap?

I can make the change if no one has already.

**Comment by Cykyrios** [comment]
So it looks like I messed up rebasing my commit several times, sorry about that. Anyway, further discussion about where the minimap setting should be can go to #31656.
