### ISSUE TITLE
C# on Android on Oculus Quest

### ISSUE THREAD

**Issue by BenMcLean** [godotengine/godot#31635]
I've read on the blog that 3.2 will have C# on Android support.

And I've read on the blog that 3.2 will have Oculus Quest support.

The Oculus Quest is an Android device.

Does this mean that 3.2 will have C# on Oculus Quest support?

**Comment by clayjohn** [comment]
Sorry to respond so late. I don't know the answer to your question. But this is not the place to ask it. Github issues should only be used for reporting bugs, all questions should go to one of the various [community channels](https://docs.godotengine.org/en/stable/community/channels.html) (reddit, discord, Q and A, etc.)
