### ISSUE TITLE
Set BakedLightmap data to be stored in a separate file and as a binary file by default. And add a custom file extension to BakedLightmap data binary.

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#31644]
**Godot version:**
3.1.1 Stable

**Issue description:**
Wen you bake a lightmap in Godot it gets stored as text in the file scene, this is a problem wen handling complex scenes, saving the whole scene can take up to minutes, even if you do something so simple as to move a single cube.

Also if you manually save the BakedLightmap data in a separate file as a text file the same problem occurs the first time you save the lightmap. Saving the lightmap as a binary speeds this up but you have to manually do it every time you re-bake a scene.

My proposal is to have BakedLightmap data to be saved in a separate file as a binary by default, also to have a custom file extension to BakedLightmap data binary, something like *.lm.

**Comment by akien-mga** [comment]
It makes sense indeed to avoid writing binary data to text-based scene files.

CC @JFonS

**Comment by Calinou** [comment]
Note that this issue also occurs with GIProbe (last time I checked). See also #16783.

**Comment by JFonS** [comment]
This makes sense, I will make sure to include these changes in the new light mapper.

**Comment by Calinou** [comment]
This should be checked again with the upcoming [new lightmapper in Godot 4.0](https://godotengine.org/article/godot-40-will-get-new-modernized-lightmapper).

**Comment by Calinou** [comment]
This was implemented in the new CPU lightmapper for 3.2.4 and the new GPU lightmapper for 4.0, closing.
