### ISSUE TITLE
Add more image file formats

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#3164]
There is an awesome library called "stb_image" https://github.com/nothings/stb
It is a single header library, no license at all, can be used without any creditation.
Basically they are Public Domain, it has great number of file formats.

There are other header files too in that project to open OggVorbis, TrueType fonts...etc
also public domain.

Please consider adding more image formats, a vectorized SWF file would be awesome.
To avoid pixelated images while zooming. although it is not part of `stb_image` library.

**Comment by reduz** [comment]
Adding more image formats would mean making the game binary more fatty for
the extra libraries required. At this point, png, webp and jpg provide more
than enough for all use cases

SWF is rasterized via software, which is not possible to do in 3D
accelerated game engines such as Godot.

**Comment by RebelliousX** [comment]
If you use stb_image library (1 header file only to include in the project), and replace all
image libraries in Godot, it will make the binary smaller.

**Comment by reduz** [comment]
no, because
1) Godot uses more functionality from PNG than currently supported by
stb_image
2) stb_image does not support WebP, which is currently the best format to
compress lossy+alpha
