### ISSUE TITLE
Improve the manual re-import UX of multiple files

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#31645]
**Godot version:**
3.1 stable

**Issue description:**
I was trying to reimport all my images with midmaps turned on.
At first I tried selecting the files I want and changing the settings and then just hitting "reimport".

This did not work, so I check the "Midmaps" checkbox, go to "Preset..." -> set as default for Texture, select all my images in the filebrowser and hit reimport.
It will reimport, but it won't reimport with midmaps turned on. Reimporting single images works.

It took me a few days an a lot of persistence to finally realize that there are some grey boxes showing up on the left if I select more than one file and that I had to check these to make sure midmaps are on on all files. This is currently [explained nowhere](https://docs.godotengine.org/en/3.1/getting_started/workflow/assets/import_process.html) and yet it's anything but intuitive or self-explanatory that setting a preset is not enough to set the reimport options. 

**Proposed UX improvement:**
All currently clicked checkboxes and other settings should apply to all (reimportable) files the user has selected when they hit the "reimport" button. No need for to double click any grey checkboxes.
If the purpose (?) of these grey checkboxes is to be able to differentiate between just reimporting a bunch of files with their previous setting _OR_ reimporting them with the current settings, make two buttons instead: 

- Reimport with orig settings
- Reimport with these settings

Right now it is not explained what those grey checkbox actually do https://github.com/godotengine/godot-docs/issues/2723,and even if they were, I would have troubles to intuitively understand why I would have to check an option twice, provided I pay enough attention to see them at all.

**Comment by Calinou** [comment]
I suppose the checkboxes at the left could be checked automatically as soon as you tweak the associated setitng.

**Comment by golddotasksquestions** [comment]
> it could be difficult to explain what those two buttons do in a single sentence

Why would it be difficult? 
"Reimport with original settings" or "Reimport with setting from previous import"
and
"Reimport with these settings" or "Reimport with above settings"

Anything is better than having to doublecheck these grey no-name boxes.

> Also, what if you want to change a single property but leave all other properties unaffected?
Not sure I understand what you mean.
I don't know how reimport works under the hood. But from a UX perspective: Just select the files, change the property in the settings and hit "Reimport"

**Comment by Calinou** [comment]
@golddotasksquestions The Import dock currently allows you to change only some properties when reimporting several resources at once. However, you may want to apply a setting that's identical to the resource you selected last. If we add a "Reimport with original" settings button, this may not be possible as you would never have changed the setting in question in the first place.

**Comment by golddotasksquestions** [comment]
Well, how about a third (checkbox then, probably):
"Reimport with settings of first selected file"

If we have or want this feature, it should be made visually clear which file we are talking about once a bunch are selected. Right now the highlighting selector looks exactly the same for all files selected.

**Comment by golddotasksquestions** [comment]
In general I'm skeptic about these rather hard to understand features,

> "Reimport all files with settings of first selected file"
> "Reimport with individual files original settings" 
> "Reimport files with individual settings from previous import" 

 as the importer does not have that many settings and the time it takes to comprehend what these "one-button-solutions" do, the user has already selected all checkboxes, dropdowns and reimported a thousand times.

**Comment by KoBeWi** [comment]
Closing for the same reason as #28403
