### ISSUE TITLE
Enhance debugging, new type of breakpoints

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#3165]
I know I am stretching it, but it would be great if the users would be able to create a
breakpoint by clicking the area left to line numbers by making it a few pixels wider
(similar to Visual Studio), also adding a context menu to create custom breakpoint
that occurs when a condition is true, for example (only do a breakpoint if x value > 30)
Also, toggling the breakpoint should be easy as clicking..

**Comment by reduz** [comment]
you have assert for that:

assert(value <=30 )

**Comment by RebelliousX** [comment]
Hmm, no, it is not like assert. It is like it hit the breakpoint when the condition is met, so I can
step over and see what is going on. AFAIK assert will cause execution to halt, at least from C++
perspective.

It is fair point, but what about a simple visual indicator to toggle the breakpoints?

**Comment by reduz** [comment]
improving that is very low on list of priorities. Maybe what could be added
easily is a breakpoint insruction, so you can write code such as

if (somecondition):
      breakpoint

**Comment by reduz** [comment]
clicking on a number may set a breakpoint too, I guess that should be asy

**Comment by RebelliousX** [comment]
That would be great for both of your ideas :+1:
