### ISSUE TITLE
Favorite directories don't show content

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31668]
**Godot version:**
0985d5f

**Issue description:**
I have a somewhat complex directory structure. There's a particular directory I'll use more frequently for some time, so I thought that I'd make if favorite. However there's a problem.
The folder
![image](https://user-images.githubusercontent.com/2223172/63657179-b3fd6880-c79e-11e9-9de9-4f88f556cb13.png)

Same folder in favorites
![image](https://user-images.githubusercontent.com/2223172/63657190-df805300-c79e-11e9-98e3-ee1a90b46fe3.png)

I can't access contents of favorite directories (at least in the tree view), which makes the option... not very useful.

**Comment by akien-mga** [comment]
Favorites are meant as shortcuts to go into the directory in the main tree, not as pinned subtrees. It's similar to the favorites/places/saved locations you have in most file managers.

**Comment by KoBeWi** [comment]
Double-clicking favorite folder jumps to that folder, so I think it's enough.

**Comment by nathanfranke** [comment]
Note that it is actually more helpful in the split view mode.

![image](https://user-images.githubusercontent.com/14253836/179269548-d3b7cacb-0ee2-404a-9bc2-095d917f1810.png)
