### ISSUE TITLE
map_to_world in tilemap gives invalid coordiantes with scale

### ISSUE THREAD

**Issue by leoxs22** [godotengine/godot#31663]
**Godot version:**
3.1

If the tilemap has a scale, like x2 in its Node2D transform, the coordinates of map_to_world are ignoring that. The Vector2 has to be manually multiplied by 2 to solve the issue.

Multiplying the result by scale.x and scale.y in the respective axis should solve the issue

**Comment by Zylann** [comment]
I believe this is the same as https://github.com/godotengine/godot/issues/37394. 
`world_to_map` and `map_to_world` are converting from ant to *tilemap's local pixel space*, not *world space*.

**Comment by zzz-assault** [comment]
Based on the PR #38551 to fix this potential bug, it was decided, that the local transform is correct and the documentation needs to be changed (to clearly state local transform / coords).

If you need global data simply use the node2d functions "to_global" for output of map_to_world and "to_local" for input of world_to_map.

From my point of view, this issue can be closed, after the official API documentation was corrected.
