### ISSUE TITLE
Low-alpha transparent objects don't cast shadows even with opaque pre-pass

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#31661]
**Godot version:**
3.2.dev 6d6d437

**OS/device including version:**
Linux Mint 19.2 x86_64

**Issue description:**
Shadows of objects with a transparent material and Opaque Pre-pass enabled disappear when alpha drops below 0.1. In the picture below, on the left, alpha is 0.099 (down to 0), on the right it is 0.1 (up to 1).
![editor](https://user-images.githubusercontent.com/53737317/63653810-07a58d00-c772-11e9-99da-0f1cca92293b.png)

**Steps to reproduce:**
* Add a directional light to the scene and enable shadows.
* Create a spatial material with the transparent flag and depth draw set to opaque pre-pass.
* Play with the albedo alpha, any value below 26 (or 0.1 when normalized) will cause the shadow to disappear.

**Minimal reproduction project:**
[TransparentShadow.zip](https://github.com/godotengine/godot/files/3538436/TransparentShadow.zip)

This project contains a propeller which can spin at high speeds. A MultiMeshInstance is used to instance several duplicates with reduced opacity to create a "volumetric motion blur" effect.
Opacity of each instance depends on the number of instances, a single instance is fully opaque, and 100 instances results in an alpha value of 0.1. Any number of instances above that will cause the shadows to disappear.
While in the editor, the original mesh is visible, setting the PropMat material's alpha to values lower than 0.1 will also exhibit the issue while in the editor.

Unrelated to this specific issue but still about transparency, the picture below shows discrepancies to the rendering of transparent objects when depth draw is set to opaque only (left) or opaque pre-pass (right), should I open a new issue for this or is it expected behavior?
![ingame](https://user-images.githubusercontent.com/53737317/63653856-bea20880-c772-11e9-965e-d1ffa24855c0.png)

**Comment by clayjohn** [comment]
The threshold for alpha when using opaque prepass is indeed 0.1, it is found here:
https://github.com/godotengine/godot/blob/0985d5fa991d14f5393ced5783b69b967a69f4f5/drivers/gles3/rasterizer_scene_gles3.cpp#L4893

Opaque prepass is only supposed to capture the opaque parts of a partially transparent mesh, hence the cutoff of 0.1. I am not sure why 0.1 was chosen. Maybe it could be made configurable in the material?

**Comment by Cykyrios** [comment]
It does make sense not to render shadows of almost invisible objects, but it would be nice if it was documented or configurable.
Would you be aware of another way to render such shadows (preferably with low alpha as well)? Or is it a current limitation of transparency rendering?

**Comment by clayjohn** [comment]
Right now I don't think there is any way to render transparent shadows below an alpha of 0.1. 

But it should be possible to add a way to configure this threshold.

**Comment by Calinou** [comment]
Should the alpha scissor threshold stored in the material be reused as the shadow alpha threshold for opaque prepass?

**Comment by clayjohn** [comment]
This was implemented in https://github.com/godotengine/godot/pull/45372

Now you can use a lower threshold by overriding it with alpha scissor
