### ISSUE TITLE
draw_texture_rect third argument (bool tile) not applied

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#3167]
This was reported by someone else on IRC, but I can confirm it's misbehaving.
If you use something like draw_texture_rect(mytexture, myrect, true) with a texture loaded from (at least in my test) a non-converted png file, it will stretch the texture as if it was false.

**Comment by akien-mga** [comment]
Had a quick look at the source, the tile argument is passed down all the way to VisualServer in https://github.com/godotengine/godot/blob/428984e/servers/visual/visual_server_raster.cpp#L3573-L3574 where the ```Rasterizer::CANVAS_RECT_TILE``` flag is set.

But this set does not seem to be used indeed at a first glance:
```
$ ack CANVAS_RECT_TILE
drivers/gles2/rasterizer_gles2.cpp
9077:                                   flags|=Rasterizer::CANVAS_RECT_TILE;

servers/visual/rasterizer.h
568:            CANVAS_RECT_TILE=2,

servers/visual/visual_server_raster.cpp
3574:           rect->flags|=Rasterizer::CANVAS_RECT_TILE;
```
In rasterizer_gles2.cpp it's in an ```#if 0```'ed block.
