### ISSUE TITLE
Blank Project Manager

### ISSUE THREAD

**Issue by SyntaxPartnership** [godotengine/godot#31671]
**Godot version:**
3.1.1 Stable

**OS/device including version:**
WIndows 10 Home 64 Bit 16GB RAM
Intel Core i7-7700HQ 2.80 GHz
nVidia 1050 Ti (Driver Version: 436.02)

**Issue description:**
Project Manager window was completely blank. It functions as it should, but you can't see what you're clicking.

**Steps to reproduce:**
Open Godot

**Minimal reproduction project:**
![oops](https://user-images.githubusercontent.com/23580375/63658604-95cd4380-c771-11e9-95dc-497f103e3542.png)

**Comment by 9BitStrider** [comment]
Attempting to run my game give the same result. A blank window.
![oops2](https://user-images.githubusercontent.com/23580375/63658916-007f7e80-c774-11e9-892f-5c736e61bf31.png)

**Comment by 9BitStrider** [comment]
It's something to do with my video card. When I run the app using my integrated Intel HD 630 it works fine.

**Comment by aaronfranke** [comment]
I would ask if they can still reproduce this in 3.2 beta 6, but considering this user deleted their account, it may be best just to close this (and if someone happens to have the same problem we can re-open).

**Comment by Calinou** [comment]
I'll close this per @aaronfranke's comment.
