### ISSUE TITLE
RAW mode in ColorPicker

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31679]
**Godot version:**
4b53fdb

**Issue description:**
Right now, the ColorPicker supports 3 modes: RGB, HSV and RAW. The latter two are "exclusive CheckButtons"
![image](https://user-images.githubusercontent.com/2223172/63695836-c9fc3f00-c819-11e9-9dbe-187d4ac91d98.png)
which makes it hard to add more modes. So the idea is that there should be a dropdown for modes. HOWEVER, should RAW mode be another mode? See, "RAW mode" is just RGB mode with values from 0 to 1 and beyond. Which brought me an idea that RAW would be just a checkubutton separate to mode dropdown, which changes behavior of currently selected mode to use "raw" values. But this means that each new mode we might add (like HSY' or CMYK) would also need to handle the raw values, which makes things _slightly_ more complex.

So, should RAW be separate option or just one of modes? Does it make sense outside RGB and HSV?

**Comment by TheDuriel** [comment]
RAW makes little sense outside of RGB. It's could work for HSV, but its highly unintuitive to add it to a format that is specifically meant to represent colors as humans see and describe them.

Taking a look at blenders color picker might be a good idea.

![image](https://user-images.githubusercontent.com/44248915/63700746-d2597780-c823-11e9-8d40-2024d2db9c19.png)

It has three tabs. (Though i would prefer Hex to always be visible.)

Alpha is constant, and not linked to a specific tab.

By default all sliders go from 0 to 1. If you manually input a higher value, the sliders will go from 0 to 1 or your manual value, whichever is higher.

_Maybe_ the RGB tab could have a toggle for switching between integer and float representations.

**Comment by KoBeWi** [comment]
Tabs won't work, because they limit space. And the "RGB-only" switch would be awkward without tabs (like, should it hide and appear or get disabled on "incompatible" modes?)

**Comment by TheDuriel** [comment]
> Tabs won't work, because they limit space.

Not sure I understand.

**Comment by KoBeWi** [comment]
> Not sure I understand.

![image](https://user-images.githubusercontent.com/2223172/63724047-35183680-c857-11e9-87fe-a0b8707ca460.png)
If it were to be this design or similar, we'd have a lot of buttons if new color modes were added. It just doesn't fit the current ColorPicker. Unless it gets replaced by something completely new.

**Comment by Calinou** [comment]
@KoBeWi Will we get new color modes in the near future though? I think it'd be fine to use a tab-based design for now, as it'd be an upgrade over the two CheckButtons we currently have.

**Comment by KoBeWi** [comment]
Well, if the ColorPicker is going to be refactored (mostly to make stuff less hard-coded), it would be nice if it won't be needed again. At least not in a way that will require scrapping the previous work. And using tabs with different contents and then dropdown doesn't sound compatible.

**Comment by KoBeWi** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/4353
