### ISSUE TITLE
BitMap `opaque_to_polygons()` polygon generation problem

### ISSUE THREAD

**Issue by nthrack-zz** [godotengine/godot#31675]
**Godot version:**
Godot_v3.1.1-stable_win64

**OS/device including version:**
Windows10

**Issue description:**

In my project I'm using a lot of BitMaps to generate polygons through GDScript.

Sometimes the polygon generated by opaque_to_polygon has unexpected behavior.

I did some troubleshooting and it seems that if there is a single true pixel near a larger true area, the opaque_to_polygon function only generates a "single pixle" polygon and the larger area is ignored.

**Steps to reproduce:**

See the example project.

In the attached image, the first png used for BitMap Generation has an angular pixel near a larger area and generates a polygon around the single pixel by skipping the larger area, in the second png it works as it should.

![BitMap_Polygon_Bug](https://user-images.githubusercontent.com/45178200/63688636-3a01c980-c808-11e9-8be8-d5eef40f6069.png)

**Minimal reproduction project:**
[BitMap_Bug_Example.zip](https://github.com/godotengine/godot/files/3540946/BitMap_Bug_Example.zip)

**Comment by KoBeWi** [comment]
Still valid in 6f4384f20

**Comment by filipex2000** [comment]
I'm currently having very similar issues with opaque_to_polygon function, DId someone find any workarounds for this?

**Comment by DTFlip** [comment]
I'm also having this problem with the below sprite, I'm assuming because of the long skinny antenna next to the large square body. Is there anyway to fix this without modifying the sprite?
![stoat1](https://user-images.githubusercontent.com/10538166/126573150-2e9a6669-debb-4720-8823-5cc2d28ec5e4.png)

**Comment by Calinou** [comment]
> Is there anyway to fix this without modifying the sprite?

I don't think so, but you can use a second sprite dedicated to polygon generation.

**Comment by RabbitB** [comment]
I've decided to continue development of a raster image to svg conversion tool I was previously working on, and decided to refactor the svg conversion algorithms because my implementations in GDScript were way too slow, which is why I originally stopped developing it (too lazy to write native plugins in 3.x; will hold off until 4.x is out.)

At initial glance, BitMap is exactly what I needed, but I saw this open issue and decided to test it myself in 3.4 stable. I can verify that the bug is still present. I went and modified the example to display the output polygons, and you can see here that the large area is still being incorrectly skipped.

![bitmap_bug_w_poly_example](https://user-images.githubusercontent.com/6007524/145911504-05ff0ea6-3386-45dd-b9ad-7c3169bca49e.png)

**Comment by SteveSmith16384** [comment]
My "solution" was to go through the bitmap first and remove all pixels that don't have any adjacent pixels.  This is a lot faster than I expected and seems to work.

**Comment by Calinou** [comment]
> My "solution" was to go through the bitmap first and remove all pixels that don't have any adjacent pixels. This is a lot faster than I expected and seems to work.

Do you have a code sample you can share for doing this? Thanks in advance 🙂

**Comment by SteveSmith16384** [comment]
Sure.  It can be improved, but my quick hack was as follows:-

$Sprite is where the bitmap came from,

`	levelBM.create_from_image_alpha($Sprite.texture.get_data(), 0.1)
	for y in range(1, $Sprite.texture.get_height()-1):
		for x in range(1, $Sprite.texture.get_width()-1):
			var vec = Vector2(x, y)
			if levelBM.get_bit(vec):
				var vec1 = Vector2(x+1, y)
				if levelBM.get_bit(vec1) == false:
					var vec2 = Vector2(x-1, y)
					if levelBM.get_bit(vec2) == false:
						var vec3 = Vector2(x, y+1)
						if levelBM.get_bit(vec3) == false:
							var vec4 = Vector2(x, y-1)
							if levelBM.get_bit(vec4) == false:
								levelBM.set_bit(vec, false)

	arr = levelBM.opaque_to_polygons(...)

`

**Comment by SteveSmith16384** [comment]
Unfortunately it seems I've come across designs that still don't generate the correct polygons even after my hack.  I've still yet to determine what the specific layout of the bitmap is that causes this though.

**Comment by RabbitB** [comment]
[Here's](https://github.com/godotengine/godot/blob/90a35dac489bcbe39de35af661367519b411cb98/scene/resources/bit_map.cpp#L163) the relevant code for finding the vertices of the polygons.

I haven't looked that hard at it, but the comments say it's using marching square, but it doesn't look like standard marching square to me. It seems like they're using a modified lookup table, and without actually debugging, I would make an educated guess and say there's probably some short-circuiting code to bail-out early when you can safely do so, that's malformed and short-circuiting at inappropriate times.

**Comment by SteveSmith16384** [comment]
It seems that a problem occurs when two pixels are touching only by their corners (i.e. with no other pixels adjacent to them on that side, if you see what I mean).  FWIW, this is my new hack that seems to fix it:-

`	levelBM.create_from_image_alpha($Sprite.texture.get_data(), 0.1)
	for y in range(1, $Sprite.texture.get_height()-1):
		for x in range(1, $Sprite.texture.get_width()-1):
			var vec = Vector2(x, y)

			# Check for single pixels
			if levelBM.get_bit(vec):
				var vec1 = Vector2(x+1, y)
				var vec2 = Vector2(x-1, y)
				var vec3 = Vector2(x, y+1)
				var vec4 = Vector2(x, y-1)
				if levelBM.get_bit(vec1) == false and \
					levelBM.get_bit(vec2) == false and \
					levelBM.get_bit(vec3) == false and \
					levelBM.get_bit(vec4) == false:
						levelBM.set_bit(vec, false)

			# Check for diagonals
			var vec2 = Vector2(x+1, y)
			var vec3 = Vector2(x, y+1)
			var vec4 = Vector2(x+1, y+1)
			if levelBM.get_bit(vec) and levelBM.get_bit(vec2) == false and \
				levelBM.get_bit(vec3) == false and levelBM.get_bit(vec4): 
				levelBM.set_bit(vec, false)
			elif levelBM.get_bit(vec) == false and levelBM.get_bit(vec2) and \
				levelBM.get_bit(vec3) and levelBM.get_bit(vec4) == false: 
				levelBM.set_bit(vec, false)
	
	var arr = levelBM.opaque_to_polygons(...)
`
Apologies for the names of my vars.

**Comment by NykolaR** [comment]
I've written a (not particularly efficient) little project made for testing this bug, where you can draw on a bitmap representation and immediately compare it to the polygon output that's produced side by side (can also press space to randomly fill the bitmap). From this tool I think I've found out that the opaque to polygon fails if on any bit either of it's diagonal neighbor bits are set to true, while the bit above/below is set to false and the bit to the respective diagonals side is also false. With this knowledge it should be possible to write a loop that fixes all cases by setting these diagonal bits to false, but I won't know until I try it out tomorrow or later this week. I think the pixel chunk that gets successfully created is always read from top left to bottom right. Screenshot below that I think shows most or all of the breaking cases, where the red areas on the right is the polygon output

![break_cases](https://user-images.githubusercontent.com/15218653/167728328-0ae4f6ed-3a58-4ac4-9323-98227fd7d2c5.png)

I don't think I'll be able to actually fix the marching squares algo, but perhaps with this information and the tool below somebody smarter than I can figure it out and do a real fix:

[BitmapToPolygonsTester.zip](https://github.com/godotengine/godot/files/8665246/BitmapToPolygonsTester.zip)

**Comment by AThousandShips** [comment]
Opened a PR that should fix this:
#68732

**Comment by markusneg** [comment]
I tested opaque_to_polygons() under different circumstances and it seems to work nicely except that holes are discarded. Is there a distinct reason the function does not return "inner" polygons? I.e., is the implementation difficult or is it a design decision?

**Comment by AThousandShips** [comment]
It's not intended, and would make things a lot more convoluted, you can open a [proposal](https://github.com/godotengine/godot-proposals) to add this functionality though
