### ISSUE TITLE
File path autocomplete conflicts with regular autocomplete

### ISSUE THREAD

**Issue by regakakobigman** [godotengine/godot#31672]
**Godot version:**

v3.1.1.stable.official

**OS/device including version:**

Windows 8.1 64-bit

**Issue description:**

![L9EtssIg51](https://user-images.githubusercontent.com/42157525/63666037-ee193b00-c79b-11e9-9635-3c6502c834bc.gif)

When typing somewhere with file path autocomplete (like `load()` or `preload()`), an autocomplete dialog will show up with different options (such as `"res://icon.png"` or `"res://assets/my_scene.tscn"`).

If the user is inside quotes, such as after typing `preload("`, the autocomplete works correctly.

If the user is **not** in quotes, such as after typing `preload(`, the autocomplete will appear for a second but then be replaced by a generic autocomplete dialog. This is confusing because the autocomplete you see is swapped out with something else, and when you select it, you may end up inserting something you didn't mean to.

**Steps to reproduce:**

1. Begin typing something that looks like `const my_var = preload`
2. Type `(`. The file path autocomplete opens up and works correctly.
3. Begin typing the name of a file (in the .gif above, I typed 'ic' and then pressed enter). The file path autocomplete will stay open for about half a second, then it'll be replaced by another autocomplete menu.

The autocomplete works correctly if you add an apostrophe `"` after the opening parenthesis `(`. When there's no apostrophe, it works for a moment but then gets replaced by another autocomplete menu.

**Comment by nathanwfranke** [comment]
I can still reproduce this in the latest master. I am having the same issue with signal completions, or string arguments. For example, if I type `Input.is_action_just_pressed(ui` after a second it will show the property autocomplete

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by Jummit** [comment]
No longer the case in 4.0, now autocomplete stops completely inside preload and load.
