### ISSUE TITLE
Fog property of environment has incorrect default value

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#31686]
3.2 dev

The default fog start depth is 10 while **fog end depth is 0**, which is probably an oversight.
The end depth should be something around 100 for example.

**Comment by IlyaStuurFedorov** [comment]
What about fog height? It seems to have the same issue.

**Comment by CptPotato** [comment]
That commit was purely about **height fog** and is correct - this one is about **depth** fog.

**Comment by akien-mga** [comment]
CC @Calinou

**Comment by Calinou** [comment]
According to the [fog shader](https://github.com/godotengine/godot/blob/b7c46ed9298b6be4d61574979f686f59b8313be0/drivers/gles3/shaders/scene.glsl#L2131), a `fog_depth_end` value of 0 will set it to the Camera's `far` value (which is 100 by default, both in the editor and in the Camera node).

However, this behavior may be confusing, so I think it makes sense to change `fog_depth_end` to 100 by default. This way, people changing the Camera's `far` value won't be surprised by the fog becoming more/less intense.

**Comment by CptPotato** [comment]
Oh, I totally didn't know this. I guess my test scene was so small that I couldn't see the effect at all and assumed the fog wasn't working in that case.

That being said, I think having a conditional in the shader just for this is not very optimal. It could be done on the c++ side without problems. Though, it's probably not worth it since a lot of the code will probably change anyway when vulkan comes along.

**Comment by Calinou** [comment]
> That being said, I think having a conditional in the shader just for this is not very optimal. It could be done on the c++ side without problems. Though, it's probably not worth it since a lot of the code will probably change anyway when vulkan comes along.

Indeed, I don't see a whole lot of use cases for it either. In games where the view distance can be changed by the player, changing the fog distance can be done just as easily with a single line of code.

**Comment by npip99** [comment]
I'm using Godot v3.2.alpha0.official, and the fog_depth_end is indeed set to 100 as discussed in this thread. However, the fog doesn't work at all. When I change fog_depth_end to 99, or if I change it to 101, it works just fine. But leaving it the default 100 causes the fog to not work. Not sure if that's just me or if others are having the same issue?

**Comment by Calinou** [comment]
@CptPotato I tried removing the variable assignment and conditional here (making it always use `z_far` for testing purposes), but it had no performance impact in the demo project linked below:

https://github.com/godotengine/godot/blob/aa0fa6b14f62c6aeab04345151cf7c2a9f6df79f/drivers/gles3/shaders/scene.glsl#L2122

I get 1820 FPS in both cases (the project uses a fog depth of 0, which means it uses the Camera's Zfar value).

[test_fog.zip](https://github.com/godotengine/godot/files/3775008/test_fog.zip)

**Comment by CptPotato** [comment]
The difference is possibly just too small. So probably it's not even worth changing?

From what I know branching in shaders on modern GPUs is pretty fast, especially if large areas or all pixels are using the same branch.
