### ISSUE TITLE
AssetLib doesn't handle broken thumbnails properly

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#31683]
**Godot version:**
be99e7b

**Issue description:**
The AssetLib doesn't really know how to handle broken thumbnails:
- If the thumbnail of a video is broken, the "Play" icon is cutout:
![Screenshot_20190826_133024](https://user-images.githubusercontent.com/30739239/63706479-08e0c380-c81f-11e9-864c-ab54fcde6258.png)
_(Mixing Desk)_

- ~~It's not capable of showing GIFs.~~ The engine as a whole is not capable.
- ~~Switching from and to a broken thumbnail makes the dialog contents change size:~~ Addressed by #31733.
![Peek 2019-08-26 13-35](https://user-images.githubusercontent.com/30739239/63706686-9d4b2600-c81f-11e9-9f78-37de63815cee.gif)
_(Godot Map Loader)_

~~And of course, the fact that it uses the Godot logo instead of a proper specific icon as a placeholder.~~ Addressed by #31719.

**Comment by Calinou** [comment]
> It's not capable of showing GIFs.

Godot currently doesn't support GIFs, so the asset library shouldn't allow users to link to GIFs. We should write this down in the asset uploading guidelines :slightly_smiling_face:

**Comment by Calinou** [comment]
Note that I've fixed the Mixing Desk video thumbnails by fetching them from the [Streamable API](https://streamable.com/documentation) manually then editing the asset in question.

**Comment by KoBeWi** [comment]
Looks fixed in 3.2
![image](https://user-images.githubusercontent.com/2223172/92315029-684fe280-efe0-11ea-8a71-4203a783592c.png)
