### ISSUE TITLE
Code helper tooltip misses base functions on script extending

### ISSUE THREAD

**Issue by MrModez** [godotengine/godot#3168]
If you extend script file, code helper won't show you inherited functions/variables
![issue](https://i.imgur.com/4UVLdOm.png)

**Comment by MrModez** [comment]
Well that's more a bug, than an enhancement offer

**Comment by vnen** [comment]
This is related to (if not the same as) #1039.

**Comment by akien-mga** [comment]
Closing as duplicate of #1039 indeed.
