### ISSUE TITLE
Repeated bezier tracks when using insert key

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#31697]
**Godot version:**
2f63811 Goodot 3.2 from Calinou's dailies.

**OS/device including version:**
Windows 10 64

**Issue description:**
There is no way to edit position/scale/rotation graphically using bezier tracks since pressing insert results in creating a separate set of bezier tracks for the same properties. 
Only workaround is manually adding keys.
Some animation software is really smart or configurable regarding how it sets up the handles when adding new keyframes to bezier tracks. I personally don't care if the handles are always flat as long as I can add keyframes by moving, rotating, scaling visually and pressing insert. 

There are a series of bugs related to inserting bezier tracks. Here are the issue numbers:
#28429
#31695
#31696
#31697
#31698

**Steps to reproduce:**
- make sure the "loc" animation mask is set
- press insert and choose to add bezier tracks
- move somewhere else in the timeline
- press insert again

Expected: 
 - keys are added based on animation masks for existing tracks and the track creation popup shows up only if necessary

Actual:
 - the track creation poup appears again and a second set of position.x, position.y tracks is created

**Minimal reproduction project:**
[broken_beziers.zip](https://github.com/godotengine/godot/files/3544338/broken_beziers.zip)

Video demonstration: https://streamable.com/5ury3

**Comment by golddotasksquestions** [comment]
Animating with Bezier curves feels totally broken right now. This issue is the first thing I encountered when I was trying to use Bezier curves for the first time. Then I was trying to go into the Bezier edit to place a key at the end, but it would not snap to the snap settings https://github.com/godotengine/godot/issues/19468
