### ISSUE TITLE
Particle sprite animations sometimes show the wrong frame

### ISSUE THREAD

**Issue by Lucresis** [godotengine/godot#31699]
**Godot version:**

3.1.1

**OS/device including version:**

Windows 7 64-bit
AMD Radeon E8860

**Issue description:**

When using Particles2D with Particles Animation set to On, and both Particles Anim H Frames and Particles Anim V Frames are set to 3 (eg. 3x3 spritesheet = total 9 frames), the particles sometimes show the wrong frame. 

This issue also occurs for other combinations such as 7x7 spritesheets, etc.

**Steps to reproduce:**
As above.

**Minimal reproduction project:**

[Bug Repro.zip](https://github.com/godotengine/godot/files/3544606/Bug.Repro.zip)

In the reproduction project, the particle animation is supposed to show the numbers 1,2,3,4,5,6,7,8,9. But instead, it shows 1,2,3,1,5,6,4,8,9.

**Comment by Lucresis** [comment]
Hi, I think it may be GPU or driver specific. I tested it on another PC with NVIDIA GeForce GT 620 and did not see the issue for 3x3 sprites. However, I was able to reproduce the issue with a 7x7 spritesheet. 

[Bug Repro.zip](https://github.com/godotengine/godot/files/3550578/Bug.Repro.zip)

In this project, its supposed to show the numbers 1-49. But the numbers 8, 15, 22, 29, 36, 43 show blank white squares instead. Could you give this one a try and see if the same occurs?

**Comment by Lucresis** [comment]
Could it be related to floating point precision issues in older graphics card or drivers? https://github.com/godotengine/godot/blob/65d1b0b427cdccc5b2463cbc703b922d95075895/scene/2d/canvas_item.cpp#L134-L142 I noticed in the above code, particle_total_frames and particle_frame are float instead of int. This could cause some precision/rounding issues when doing mod or division operations.

Anyway, here is the detailed information on my system:

OS: Microsoft Windows 7 Professional (6.1.7601 Service Pack 1 Build 7601)
System Type: x64-based PC, 64-bit Operating System
Processor: Intel Pentium CPU G3420 @ 3.20GHz
Installed Physical Memory: 8.00GB

Graphics Chipset: AMD Radeon E8860
Device ID: 6822
Vendor ID: 1002
Subsystem ID: 031E
Subsystem Vendor ID: 1002
Revision ID: 00

Driver Packaging Version: 14.502.1001.1001-150113a-179456C-AES
Catalyst Version: 08.4
2D Driver Version: 8.01.01.1443
Direct3D Version: 9.14.10.01080
OpenGL Version: 6.14.10.13285
Mantle Driver Version: 9.1.10.0045
Mantle API Version: 98304
AMD Catalyst Control Center Version: 2015.0113.1141.20974

**Comment by KoBeWi** [comment]
@Lucresis Can you still reproduce this in [Godot 3.2.3 rc5](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-5)?
(I can't)

**Comment by Lucresis** [comment]
@KoBeWi Hi, the hardware I originally encountered the issue on belongs to my previous workplace, so I no longer have access to it.  I tried it on my personal laptop (Geforce 1060), wasn't able to reproduce it.

**Comment by KoBeWi** [comment]
This is rare issue and the particles are being reworked in 4.0, so should be fine to close this.
