### ISSUE TITLE
Why the get_area() function of AABB class is named get_area, instead of being get_volume()?

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#31692]
The shows that it is return the volume of the AABB, yet the function is named get_area(). Can anyone tell me why it named that.

https://github.com/godotengine/godot/blob/2f63811c9aa1d1710dc045e01b1391493243ddde/core/math/aabb.cpp#L35

**Comment by Zylann** [comment]
Candidate for https://github.com/godotengine/godot/issues/16863 ?
