### ISSUE TITLE
Disable internal command line usage in release

### ISSUE THREAD

**Issue by WiggleWizard** [godotengine/godot#31704]
I'm currently working on an application that requires command line input. I am struggling a little because Godot will actually error out if you pass an argument to it that doesn't start with a `-` and is not a valid path to a `PackedScene` in `res://` that it can start up with. I also see this being a small issue with some developers who don't want to give the player the ability to start random scenes up.

It would be nice to remove this from `release`. For reference you can see this line [main/main.cpp#L1339](https://github.com/godotengine/godot/blob/4b53fdb25d545b0a2fc73f6a46775ced586994b7/main/main.cpp#L1339) which does what I mentioned above.

**Comment by Calinou** [comment]
This is related to #8721, which would make it possible for applications to handle file paths gracefully without disabling other CLI arguments.

**Comment by WiggleWizard** [comment]
It seems I didn't look properly before making a new ticket. You can mark as duplicate as the latter ticket's latest discussion is what I'm after.
