### ISSUE TITLE
Keyboard navigation in the Project List ignores the first item

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#31707]
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/63766121-c96fb100-c8ca-11e9-8a9d-3c7a92e39c20.png)

**OS/device including version:**
Windows 10 64

**Issue description:**
Keyboard navigation in the Project List ignores the first item

**Steps to reproduce:**
Have a populated Project List, start navigating with up/down keys - it's impossible to select the first item this way.

**Comment by KoBeWi** [comment]
Works fine for me, except I can't select the first favorite project.

**Comment by PLyczkowski** [comment]
@KoBeWi Oops, correct. I updated the issue description.

**Comment by PLyczkowski** [comment]
Actually, it's just the first item in the list, doesn't have to be pinned
