### ISSUE TITLE
AudioEffectRecord returns all zero samples on Android

### ISSUE THREAD

**Issue by DomsterKB** [godotengine/godot#31708]
**Godot version:**
Tested on
v3.1.1.stable.official
and
v3.2.dev.custom_build.e23f5e641

**OS/device including version:**
Tested on
Android 9.0
and
Android 8.0
(Exported on Windows 10 Pro with Oracle JDK 8u221)

**Issue description:**
The data returned from AudioEffectRecord::get_recording() contains all zero values.  The size of the data sample appears to correlate with the length of the recording.  While the recorded data plays properly on Windows, it does not play at all on Android due to all samples being zero.

**Steps to reproduce:**
Export the sample project from the minimal reproduction project below to Android.
Look at the data returned from recording.get_data() in the sample project and it will contain all zeros.

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record

**Related issues/pull requests:**
[#30308](https://github.com/godotengine/godot/issues/30308)

**Comment by lawnjelly** [comment]
Permissions issue maybe?

**Comment by lawnjelly** [comment]
Can confirm, this seems to be a simple permissions issue. I tried the mic record project, ran on my android tablet, recording was blank. Then I added the record from microphone permission in the export dialog, and viola, it was working. :smile: 

It turns out there is a warning message already in logcat (although whether mere mortals will see this I don't know):

```
08-28 12:54:36.280 4381-4418/com.example.micrecord W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
08-28 12:54:36.280 125-2622/? W/ServiceManager: Permission failure: android.permission.RECORD_AUDIO from uid=10190 pid=4381
08-28 12:54:36.280 125-2622/? E/AudioFlinger: openRecord() permission denied: recording not allowed
08-28 12:54:36.280 4381-4418/com.example.micrecord E/AudioRecord: AudioFlinger could not create record track, status: -1
08-28 12:54:36.280 4381-4418/com.example.micrecord E/libOpenSLES: android_audioRecorder_realize(0x690c9210) error creating AudioRecord object
08-28 12:54:36.280 4381-4418/com.example.micrecord W/libOpenSLES: Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
08-28 12:54:36.280 4381-4418/com.example.micrecord E/godot: **ERROR**: Condition ' res != ((SLuint32) 0x00000000) ' is true. returned: ERR_CANT_OPEN
08-28 12:54:36.280 4381-4418/com.example.micrecord E/godot:    At: platform/android/audio_driver_opensl.cpp:265:capture_init_device() - Condition ' res != ((SLuint32) 0x00000000) ' is true. returned: ERR_CANT_OPEN
08-28 12:54:38.310 4381-4381/com.example.micrecord D/dalvikvm: GC_FOR_ALLOC freed 371K, 5% free 7785K/8192K, paused 19ms, total 19ms
08-28 12:54:43.760 4381-4381/com.example.micrecord D/dalvikvm: GC_FOR_ALLOC freed 520K, 7% free 7773K/8332K, paused 26ms, total 26ms
08-28 12:54:49.420 4381-4381/com.example.micrecord D/dalvikvm: GC_FOR_ALLOC freed 512K, 7% free 7773K/8332K, paused 25ms, total 25ms
```

**Comment by DomsterKB** [comment]
Enabling record audio in the export dialog indeed fixes this issue.  Thanks for confirming @lawnjelly
