### ISSUE TITLE
Timer doesn't start until present in scene

### ISSUE THREAD

**Issue by Vrzasq** [godotengine/godot#31710]
**Godot version:**
official 3.1.1

**OS/device including version:**
- GPU gtx1080 drivers GeForce Game Ready Driver v431.36
- CPU i5-750
- Windows 10

**Issue description:**
Timer doesn't start until present inside scene
```
var destroy_timer = Timer.new()
destroy_timer.connect("timeout", self, "on_destroy_timer_timeout")
destroy_timer.start(15.0)
```
This code doesn't start timer until it's added to the scene. Is it expected behavior ?

**Steps to reproduce:**
- create timer with Timer.new()
- don't add timer to scene tree
 - start timer

**Comment by volzhs** [comment]
yes. expected. it is a node so does not do anything until added to a scene.

**Comment by Vrzasq** [comment]
Thanks
