### ISSUE TITLE
Godot crashes on recent build

### ISSUE THREAD

**Issue by mcanders** [godotengine/godot#3171]
I've been experiencing some serious weirdness since rebuilding godot.  I last built it a week ago and everything was fine.  I am on arch linux if that matters.

Godot starts with these errors but does not crash.  I don't know if they are related or not:
```
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:598.
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:598.
ERROR: add_child: Can't add child, already has a parent
   At: scene/main/node.cpp:740.
ERROR: add_child: Can't add child, already has a parent
   At: scene/main/node.cpp:740.
bind toptions
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:598.
ERROR: grab_focus: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:2223.
ERROR: grab_focus: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:2223.
```

When I try to open my main scene (which is pretty big and has many references to other scenes) godot crashes with the following error:
```
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:625.
```

But it gets weirder.  When I opened my scripts folder in the filesystem tab, godot crashed (with the same "Index p_current out of size" error).  Opening other folders worked fine, but it crashed without fail when I opened the scripts folder.  However, I removed the contents of the scripts folder, then slowly added them back in (refreshing the filesystem tab as I went).  Throughout the process godot never crashed.  And it no longer crashed when I open the scripts folder.  This "fix" persisted even when I reopened godot.

Weird right?

**Comment by mcanders** [comment]
I should mention that only my "main" scene crashes the editor.  I can open every other scene without errors.

**Comment by akien-mga** [comment]
The set_current_tab issue is unrelated, is there no other error log when it crashes? No segmentation fault or similar? If you had a script with subclasses, could you try the latest master branch again? I just merged a fix for that.

**Comment by reduz** [comment]
may be related to the onready error

**Comment by mcanders** [comment]
It works now.  It was definitely one (or both) of @leezh's two commits.  For future reference, where should I look for more informative logs?  I got the errors above by running godot in a terminal.

**Comment by vnen** [comment]
@mcanders those command line logs can give a hint, though sometimes they're not related to the error. The best is to provide debug backtraces if you're able to use a debugging tool.
