### ISSUE TITLE
PinJoint2D unpins when parent node moved

### ISSUE THREAD

**Issue by mcardellg** [godotengine/godot#31711]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
When moving a node using remove_child + add_child any pin joints that are children of the node get unpinned. The joint copies correctly but detaches from it`s pinned nodes.

**Steps to reproduce:**
Run the attached minimal project, press enter to move the node in the tree, note that the previously pinned sub-node becomes detached but that the tree looks as expected.

**Minimal reproduction project:**
[unpinbug.zip](https://github.com/godotengine/godot/files/3546135/unpinbug.zip)

**Comment by KoBeWi** [comment]
Still valid in 6f4384f20
