### ISSUE TITLE
CSGBox hides coordinate system lines (GLES3 render)

### ISSUE THREAD

**Issue by softwaredev101** [godotengine/godot#31715]
**Godot version:**
Godot 3.1 Stable Mono

**OS/device including version:**
Windows 10 Home Edition 64-Bit

**Issue description:**
Whenever I'm adding a CSGBox while using the GLES3 render, the lines which indicate the coordinate system disappear.

**Steps to reproduce:**
Add a CSGBox inside the NodeTree while using the GLES3 render.

**Minimal reproduction project:**
[RPG.zip](https://github.com/godotengine/godot/files/3546739/RPG.zip)

**Comment by bojidar-bg** [comment]
Cannot confirm on master non-mono build.
Mind if you share a screenshot?

**Comment by Calinou** [comment]
@softwaredev101 Which graphics card model are you using?

**Comment by softwaredev101** [comment]
> @softwaredev101 To add to bojidar-bg's question, which graphics card model are you using?

I'm using an Intel HD 620 Integrated Graphics Card

**Comment by softwaredev101** [comment]
> 
> 
> @softwaredev101 To add to bojidar-bg's question, which graphics card model are you using?



> 
> 
> Cannot confirm on master non-mono build.
> Mind if you share a screenshot?

![Unbenannt](https://user-images.githubusercontent.com/26762235/64048841-33aa7f00-cb73-11e9-9e7f-420ae920b39a.PNG)

Sorry for the late reply. Due to work I couldn't send the screenshot earlier

**Comment by akien-mga** [comment]
Is this no longer relevant?
