### ISSUE TITLE
Ability to view 3D RayCasts while running the game

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#3172]
The ability to view 3D RayCasts while running the game would be helpful for debugging.

**Comment by Marqin** [comment]
:+1:

**Comment by kubecz3k** [comment]
Actually I need something like this right now so I made temporary workaround. 
Just add this scene to your most root scene and rays will be visualised: 
https://dl.dropboxusercontent.com/u/168251/godot/RayDebugVisualiser.7z
screen: https://dl.dropboxusercontent.com/u/168251/godot/debugrays.png

**Comment by neikeq** [comment]
This may be better in the 3.0 milestone. WDYT?

**Comment by Marqin** [comment]
Why is everything moved to 3.0?

2016-06-03 18:39 GMT+02:00 Ignacio Etcheverry <notifications@github.com>:

**Comment by neikeq** [comment]
@Marqin There will be a renderer improvement in 3.0, so we will probably take that chance to improve the 3D tools then.

**Comment by Marqin** [comment]
So there is hope we will get 3.0 from Santa?

**Comment by reduz** [comment]
No idea, I hope we can put it out before next year

**Comment by bd339** [comment]
New godot contributor here, and I would like to take a stab at this :slightly_smiling_face:

**Comment by bd339** [comment]
I have something working now. Check out my branch in #8102 if you want to try it.

**Comment by reduz** [comment]
fixed by #8102
