### ISSUE TITLE
Go to definition sometimes selects text

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31725]
**Godot version:**
f2777c04c

**Steps to reproduce:**
1. Write some code, like
```
func whatever():
	print("whatevs")

func _ready() -> void:
	whatever()

	print("place cursor here")
```
2. Put the cursor where the text says
3. Ctrl + Click the `whatever()` above `print()`. Sometimes the cursor will select text between the `print` and `whatever`.
![image](https://user-images.githubusercontent.com/2223172/63803181-905c2e80-c914-11e9-9bc7-3d2c671f35af.png)

**Comment by bojidar-bg** [comment]
This occurs when you drag on the function call instead of just tapping the mouse button.
