### ISSUE TITLE
Renaming and adding groups in the group editor doesn't work

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#31721]
**Godot version:**
3.1.1 Stable

**OS/device including version:**
Zorin OS 12 Core (Ubuntu 16.04 LTS)

**Issue description:**
Renaming groups in the group editor doesn't work, it looks like it worked but wen you press OK nothing happens.
![group-manager](https://user-images.githubusercontent.com/27329423/63794125-8a108700-c901-11e9-9a57-66d32f4cb17c.jpg)

**Steps to reproduce:**
- Create a group
- Open the group manager
- Try to rename it

EDIT: Seems adding groups in the group editor is also broken

**Comment by YeldhamDev** [comment]
If a group has no nodes, it will be "deleted" because it doesn't exist in the first place.
And renaming worked completely fine here.
