### ISSUE TITLE
Feature Request: Change order of elements in export (Array)

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#31723]
I am using Godot Engine v3.2.dev.calinou.0985d5fa9 on Windows 10

Export arrays in the inspector are great! 
But it can be a pain when you add a lot of elements, then realize you need to insert another element at a certain index. Right now the only way to do that is to erase every element until you reach that index, insert the new element, then re-add every element.

There are a few ways to add this, for example: 
-arrows next to the element index number to move it up or down the array
-Being able to drag the elements to sort them (however would not work with more than 1 page)
-Editable index number that will re-arrange elements according to the number you change it to
-"Insert at index #" option at top of the array

If there are any better ways then I'm all for it!

**Comment by KoBeWi** [comment]
Closing in favor of the proposal: https://github.com/godotengine/godot-proposals/issues/23
