### ISSUE TITLE
call group: Autoload singleton with object reference

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot#31726]
Godot v3.1.1.stable.official

Linux Mint 19.2

I want to call a Autoload singleton on all objects of a group.
One way to do that is to call the singleton with a function in the script attached to the objects.
That's what I did in the attached reproduction project.

[singleton object rep.zip](https://github.com/godotengine/godot/files/3547800/singleton.object.rep.zip)

In order to avoid an additional function call and to keep the script size of the objects minimal, I would like to pass the object references with the call_group() function.
The way this could be done is (about) shown in the node2D_better.gd scripts of the project.

The sprites_better.gd script of the project shows the object-script without the function that calls the Autoload singleton.

**Comment by bojidar-bg** [comment]
You can use `get_nodes_in_group`, no?
```gdscript
for node in get_tree().get_nodes_in_group():
    AutoLoad.drag(node, get_global_mouse_position())
```
Also, you should probably set the offsets in the scene directly using an `export var`, instead of using the `match` statement. Also, you should probably handle `_input` events in the sprite script, as it is clearer that way.

**Comment by TrickMe** [comment]
```
for node in get_tree().get_nodes_in_group():
    AutoLoad.drag(node, get_global_mouse_position())
```

works as intended.
Thank you sooo much!
