### ISSUE TITLE
Physics2D / default_gravity displaying value when unchecked

### ISSUE THREAD

**Issue by CodeTortoise** [godotengine/godot#3173]
When left unchecked, the value of 98.000000 is displayed in the debug console (the one that lives in its own window in OS Windows).

This is the setting found in Project Settings -> Physics2D -> default_gravity

**Comment by eska014** [comment]
Can confirm, both on Windows and web export.
It's unrelated to being checked or unchecked, if I set it to a non-default value it's still displayed.

**Comment by eska014** [comment]
Only happens with 2D kinematic bodies (both kinematic body and rigid body in kinematic mode), which will print the value once; and rigid bodies in rigid or character mode, which will print the value repeatedly.

**Comment by eska014** [comment]
I think this is fixed
If anyone still experiences this on builds after 8fb7014, please comment
