### ISSUE TITLE
Freeze on ubuntu 18

### ISSUE THREAD

**Issue by ejamshidiasl** [godotengine/godot#31734]
**Godot version:**
v3.1.1 (Latest Release)

**OS/device including version:**
OS: Ubuntu v18 (Latest Update)
CPU: intel core i7
RAM: 16GB
Graphic: Nvidia 940MX

**Issue description:**
Editor freezes every 30-60 seconds.

**Steps to reproduce:**
when i want to add node or change settings or write script , IDE freezes.
(i found solution to break freeze [press "Alt" key] but it freezes again after 30-60 seconds)

**Minimal reproduction project:**
every project (i tested on new project)

**Comment by Zireael07** [comment]
I have Ubuntu 18.04. which is the latest version of Ubuntu 18 IIRC, and I have seen no such freezes.

**Comment by aroldanju** [comment]
Same here with Ubuntu 18.04 LTS. I press the LCTRL key to unfreeze.

**Comment by Zireael07** [comment]
What is your graphics card @aroldanju? Mine is Intel HD Kaby Lake (I have an NVidia card but I usually don't have it switched on since the Intel does work well enough)

**Comment by aroldanju** [comment]
Gigabyte GT 630

**Comment by danilw** [comment]
im not on Ubuntu, Godot editor work without any problems (OpenSuse)

**Comment by ejamshidiasl** [comment]
i found solution
install **compizconfig** then go to opengl part and disable v-sync
