### ISSUE TITLE
Very common and wildly spread functionality in editing software require to write shaders

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#31742]
**Godot version:**
3.1

I suppose for people coming into Godot who already have a coding background, this is less of a problem. 
For me, having to learn another language in order to do things like overlaying with a color, shear a Node, adding an outline or a blurred shadow is a huge problem.
These things are literally a one or two click operations in editors of all kind, be it text editors, image editors, video or animation or presentation editors.
I really wish Godot would offer a these with the same intuitive simplicity as it does with Modulate/Visibility.

If adding a shadow was just a checkbox (with slider for the blur, and float for the angle),
if adding an outline was just a checkbox (with slider for the thickness),
if adding a solid color overlay was just a checkbox (in the modulate popup for instance),
if shearing was part of the transformations,

prototyping would be so much faster and Godot as a whole so much more accessible.

Is it not possible to have a couple shaders build into the engine? 

![common_shader_fx](https://user-images.githubusercontent.com/47016402/63856953-17f07e80-c9a3-11e9-96ac-3ef79a9d8979.png)
Edit: yes, 2D, but also for things like control nodes like buttons, labels, texturerect ect.

**Comment by Zylann** [comment]
Maybe we could add some features to `CanvasItemMaterial`? Just like `SpatialMaterial` has many of them.

**Comment by golddotasksquestions** [comment]
> Note 2: I know people might not like when I say this, but all of these things can be provided through extensions such as plugins.


Yes, I don't like that indeed. :) 
Mesh deformations, 2D skeletons and bones, pseudo 3D, CSG Mesh ... these could all be provided as plugins and have vastly narrower use cases than those simple shader effects above.

**Comment by bojidar-bg** [comment]
Note that you can already do shear transformations, but not directly from the editor. They are affine transformations and thus can be handled by `Transform2D`.

**Comment by bojidar-bg** [comment]
Another note: most of the requested features can be implemented with something similar to CSS's `box-shadow`, which is basically an underlay with replaced color, offset, and blur. It can be used for outlines of certain (simple) shapes, shadows, and blurred shadows.

**Comment by golddotasksquestions** [comment]
> Note that you can already do shear transformations, but not directly from the editor. They are affine transformations and thus can be handled by Transform2D
Is this explained anywhere? I looked through documentation and performed online searches and asked on Discord and Duriel meant I need to have a shader for that.

**Comment by avencherus** [comment]
> Is this explained anywhere? I looked through documentation and performed online searches and asked on Discord and Duriel meant I need to have a shader for that.

@golddotasksquestions 

No I don't think it is, but what he was meaning was to manipulate the matrix directly.  As you say though, one has to have some experience with matrix transforms to know how these effects are achieved.  The documentation assumes pre-requisite knowledge, which isn't unreasonable, but it could benefit from pointing out which elements deal with scaling and which handle skewing.

It is possible in script at least to manipulate the components on the Transform2D's x and y properties.  The x.y and y.x will add shearing, the others should be related to XY scaling.  Here's an example:

```
extends Node2D

export var shear_x = 1.0
export var shear_y = 2.0


func _ready():


	var s = Sprite.new()
	add_child(s)

	s.texture  = preload("res://icon.png")
	s.position = Vector2(100, 100)

	s.transform.y.x = shear_x
	s.transform.x.y = shear_y
```

That said, I quite agree, it would be nice if the transformation handles in the editor allowed more interesting kinds of manipulations.

Shearing is useful for faking perspective, and would be a lot easier to animate if it could be handled visually with drag handles.  It isn't so easy to get desired results attempting this blindly with code, but the above script could probably provide a less ideal work-around to problem.

You also might have better luck attracting attention to some of these features by breaking them up into individual discussions.

**Comment by golddotasksquestions** [comment]
$Sprite.transform.y.x = 2.0

Holy Crap! One line? That easy?!? I really can't believe this isn't mentioned anywhere I looked. Thank you so much! 
I still wish this was already build into the Inspector. .... along with the other features witch require shaders.

> You also might have better luck attracting attention to some of these features by breaking them up into individual discussions.

Probably, but these are like the five fingers on the designers hand not necessarily to make things pretty, but to visually communicate simple but important things:

Drop Shadow: 

- Is this shape picked-up and moveable, or is it "on the table"?
- Are these shapes touching each other?
- How many layers are there and which relation are they to each other?
- Do these shapes belong in the hierarchy of importance?
- Are these HUD elements or game elements?
- Can I move one shape behind another, or do I have to make another action before (like pickup or drop)?
- ...

Outline:

- "This is your current selection"
- "This thing is more relevant that that thing right now" (thicker vs thinner outline)
- "You can't see this thing, but it is still there"
- "This thing is foreground"
- ...

Solid Color (Coloring something in a solid color you need basically everywhere for everything):

- Take any graphic and make it a specific color (tinting aka modulate does not work as well as you cannot modulate any texture to a solid color)
- Unmistakably inform my users about gamestates like this thing bad, this thing good, this thing heathy, this thing hit, these things belong together ....
- Fade texture without making the graphic transparent 

...

I feel like they belong together, because as a game designer I need all of them daily to quickly and directly communicate an endless amount of things to my players.

**Comment by avencherus** [comment]
> Holy Crap! One line? That easy?!? I really can't believe this isn't mentioned anywhere I looked. Thank you so much!

No problem.  X)

> I feel like they belong together.

Those ones yeah, I think you can bundle them as "style options", but adding Shearing editor functionality seems like a different category.

**Comment by Calinou** [comment]
Someone published an outline shader to the Asset Library :slightly_smiling_face:

https://godotengine.org/asset-library/asset/394

**Comment by golddotasksquestions** [comment]
The point of this issue is that users (especially new users) need to hassle with shaders for these simple effects in the first place. See [this comment](https://github.com/godotengine/godot-proposals/issues/96#issuecomment-534933423).

**Comment by rcorre** [comment]
FWIW there are also visual shaders, which are [getting an overhaul](https://godotengine.org/article/major-update-for-visual-shader-in-godot-3-2) in 3.2. Sure, it isn't as easy as a checkbox, but it might be more intuitive than writing shader code.

I came to godot with 0 shader experience, and found the visual editor to be a nice starting point (in my case mainly the blender node tree, but same idea).

**Comment by golddotasksquestions** [comment]
I tried my luck with visual shaders multiple times without any success. To use them you need to know syntax and meaning of every component just as much as if you are writing the shader in shader language. Which I find looks a lot cleaner and more concise than visual shaders.
I read the article and surely will try again sometime with 3.2, but this has very little to do with the issue here.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
