### ISSUE TITLE
Link Node (similar to Linux soft/hard links)

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3174]
I found that in many situations I could have benefit from having some kind of link node, similar to 'link' concept on Unix systems. There could be 2 kind of links soft and hard one (or some checkbox). 
Basically after adding link node to the scene you could define node to which they are linked to.
From this moment you could thread link as this linked target node (exactly just like it would be added instead of the link in this place, so you could call functions, add new nodes, remove child etc).

Difference between hard and soft links:
**Hard Link:** If you will use hard link and you will remove original node from the game it would still be accessible via hard link (probably should simply replace one of hard links)
**Soft Link:** If you remove original node from the game it's no longer accessible via soft links (not sure what exactly should happen, remove all soft links as well? Should be some way to change 'target' node for soft link in this situation instead (probably with signal)). 

In this comment I'm telling about use case where this can be helpful: https://github.com/godotengine/godot/issues/3174#issuecomment-170865934

**Comment by bojidar-bg** [comment]
BTW, currently the best "workaround" is to export a `NodePath` variable:
````
export(NodePath) var target
var target_node
func _ready():
  target_node = get_node(target)
````

**Comment by neikeq** [comment]
You can make that a 2 liner thanks to the `onready` keyword:
``` GDScript
export(NodePath) var target
onready var target_node = get_node(target)
```

**Comment by kubecz3k** [comment]
@bojidar-bg @neikeq well it was not an use case I had in my mind, the situations I personally would find this helpful would be for example, when I have an asset scene imported from blender with an armature and boneAttachment node added to this armature. Usually I'm creating scenes (enemies/npc/hero/etc) with all main modules on equal scene level: [model/weapon/ai/backpack/etc] all on the same lvl in the same level of entity. Currently I need to do some strange things like push AI module to reside inside modelAsset.scn in some BoneAttachment node, just because this AI module have some visual representation...

**Comment by StraToN** [comment]
Once this feature exists, a drag&drop of a Node from the scene tree to the according target in the inspector could quickly set the NodePath. This is a similar behaviour as Unity3D.

**Comment by bojidar-bg** [comment]
@kubecz3k ~ I was just giving a quick workaround. I would like to support the soft-link idea.
(:+1:)

@StraToN ~ Not really the right issue for this...

**Comment by Calinou** [comment]
I'll close this issue as much has changed since Godot 2.0's release when it comes to scene organization. If you still have ideas for improvements in mind, please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository.
