### ISSUE TITLE
Creating/Adding project in Project Manager don't work

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3175]
In the latest b60a3e72028349493effe26811725d420c7e125b commit it's impossible to create or add new project. In case of creating project the files are created on the hard drive (engine.cfg is there) but it's impossible to import this project so as to it is visible on the project list. 
It's still possible to open projects created in this commit with older Godot.

**Comment by kubecz3k** [comment]
The bug was originally reported by Mrezai on the irc channel, I'm just confirming it.

**Comment by reduz** [comment]
I was expecting something to break because that was a large change, but
forgot about the project manager. I think the problem is that the new
parser does not handle comments. Fixing that..
