### ISSUE TITLE
Pressing enter in the Replace field doesn't run the Replace command

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#31762]
Pressing enter in the Replace field doesn't run the Replace command.
Optionally alt-enter or ctrl-alt-enter could run Replace All.

**Comment by zayngdev** [comment]
Will look into it.

**Comment by dreamsComeTrue** [comment]
Currently, Enter key worked for a case:

`if (selection_only->is_pressed() && text_edit->is_selection_active()) {
		_replace_all();
		_hide_bar();
	}`

My PR fixes that, so Enter works properly (and Shift-Enter replaces and moves backward)
