### ISSUE TITLE
Project is gone at project manager

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3176]
I tested with 586e482a98702055ed7323a3e81c14392233b650 commit.

steps to reproduce.
1. open project manager
2. create new project
3. check ``Render > default_clear_color`` at Project Settings.
4. Quit to Project List

then it's gone. and can't import either.

**Comment by reduz** [comment]
i think this has been fixed, give it a check to head

**Comment by volzhs** [comment]
- remove error print in area collision, should be a valid situation, closes #2463  1e65c3c  
- Fixed focus for shader editor when switching tab, closes #2551  8dad641  
- Fix parsing of comments in VariantParser, fixes #3175  586e482 < I checked with this commit.

I guess those 2 other commits are not related with this issue.
But I will do it again with head now.

**Comment by volzhs** [comment]
It still happen with head 1e65c3c

**Comment by volzhs** [comment]
key point is some error occurred if engine.cfg have ``default_clear_color``.

```
[application]

name="NewProjTest"
icon="res://icon.png"

[render]

default_clear_color=#ff4c4c4c
```

**Comment by reduz** [comment]
aaah.... that makes a ton of sense, fixing it.
