### ISSUE TITLE
Add method remove_children(free_children: bool = true) to Node class

### ISSUE THREAD

**Issue by likea-boss** [godotengine/godot#31772]
Adding method `remove_children()` to `Node` class. It would be useful for Nodes with a large number of children that generated procedurally. Also, it looks like a small simple change in code

**Comment by likea-boss** [comment]
It reduces the amount of boilerplate code and increases performance. Right now, if you want to delete all children you should iterate over children array that you get from the get_children method and manually delete each child. If you go from first to the last child, you will fire event NOTIFICATION_MOVED_IN_PARENT for all next children. It can be omitted by method remove_children which will remove children in order from last to first

**Comment by TheDuriel** [comment]
remove_child() does _not_ delete children. They will instead become memory leaks.

What you should be asking for is queue_free_children() and free_children(), which has doubtful application. Deleting everything is not that common, so when you need it a loop tends to be fine.

**Comment by volzhs** [comment]
I second for `queue_free_children()` and `free_children()`

**Comment by likea-boss** [comment]
@TheDuriel What for `free_children()`?

**Comment by likea-boss** [comment]
By the way, it can be kept as `remove_children`, but with an additional boolean argument `free_children` which is by default `true`. While it's `true` on each children node would be called `queue_free()`, if it's `false` `queue_free()` wouldn't be called.

**Comment by akien-mga** [comment]
> By the way, it can be kept as `remove_children`, but with an additional boolean argument `free_children` which is by default `true`. While it's `true` on each children node would be called `queue_free()`, if it's `false` `queue_free()` wouldn't be called.

There's no use case for `remove_children` without freeing the nodes, it's just asking for memory leaks.

**Comment by likea-boss** [comment]
@akien-mga Yes, you're right, but it would be noticed in the documentation. Also, it provides more flexibility for Godot user, because if you have links to all children and you want to do something with them you would have the ability to do this with `remove_children(false)`

**Comment by akien-mga** [comment]
Yes, but that's not a real life use case, so there's no point adding a feature for it which users might use by mistake, thinking it will free children (many users won't read documentation thoroughly).

If you really want to remove children for the scene for which you already saved references to them, you can use a for loop, it's really a corner case.

**Comment by likea-boss** [comment]
@akien-mga Ok, I agree with you. Maybe add to docs dedicated section where explains about memory management. I know about [this page](https://docs.godotengine.org/en/3.1/development/cpp/core_types.html?highlight=memory#memory-model), but it doesn't where I should call `free()` method and where shouldn't. Also, this page targeted for cpp devs.

**Comment by KoBeWi** [comment]
Closing this in favor of proposal: https://github.com/godotengine/godot-proposals/issues/764
