### ISSUE TITLE
gltf file import bug with skinned mesh

### ISSUE THREAD

**Issue by julienduroure** [godotengine/godot#31774]
**Godot version:**
3.1.1

**OS/device including version:**
Mint 19

**Issue description:**
This is a followup discussion based on this : https://github.com/KhronosGroup/glTF-Blender-IO/issues/566

2 different cases:

# Non animated skin mesh with non default transform on joints
Seems Godot does not apply the transform of joints.

* https://gltf-viewer.donmccurdy.com/ (tree.js) : Seems OK
* https://sandbox.babylonjs.com/ : Seems OK
* godot 3.1.1 : Not OK
* Blender importer : Not OK

![skin](https://user-images.githubusercontent.com/1696020/63646597-7a344f80-c715-11e9-9c24-b3d583392485.png)

# Animated skin mesh
* https://gltf-viewer.donmccurdy.com/ (tree.js) : Seems OK
* https://sandbox.babylonjs.com/ : Seems OK
* godot 3.1.1 : Not OK
* Blender importer : Seems OK

![image](https://user-images.githubusercontent.com/1696020/63961246-a7279000-ca90-11e9-9151-b328aca55be4.png)

![image](https://user-images.githubusercontent.com/1696020/63961300-c58d8b80-ca90-11e9-80d7-462f36703b82.png)

**Steps to reproduce:**
Import gltf file

**Minimal reproduction project:**
Here are files:
- non animated skin mesh:
[test_skin.zip](https://github.com/godotengine/godot/files/3556688/test_skin.zip)

- animated skin mesh:
[animated.zip](https://github.com/godotengine/godot/files/3556684/animated.zip)

Note: As said in glTF-Blender-IO issue, this are test files generated by a WIP branch.

**Comment by marstaik** [comment]
@julienduroure Ive been working to rewrite most of the importer for skins/animation and I am very close to being complete. Could you provide me with the animated glb's as gltf+glb's also? It is very helpful for me to manually debug some cases.

**Comment by marstaik** [comment]
Success:
![1iVyCJZAnb](https://user-images.githubusercontent.com/5601015/64482089-91f0e680-d19f-11e9-95d5-48e63a823c16.gif)

**Comment by fire** [comment]
Want me to test your branch?

**Comment by marstaik** [comment]
I'll push it up tomorrow, I want to clean up the code a bit. I would love some more testers. I've fixed a whole lot of issues though, not just this one.

**Comment by julienduroure** [comment]
@marstaik Here are the files!
[gltf.zip](https://github.com/godotengine/godot/files/3587321/gltf.zip)

**Comment by julienduroure** [comment]
@marstaik Hello Marios,
I know there is lots of discussion about skin glTF specification , but can I have a status about this ticket and files I sent you. Do you have any issue? Does it fit with what you expected?

**Comment by julienduroure** [comment]
@marstaik Ok, so issue is on your side. If you don't detect problems on glb file I provided, I can merge the PR changes on blender exporter.

**Comment by marstaik** [comment]
@julienduroure Would you mind holding off for one more day? There is something I would like to test, and I should know the result by the end of tomorrow. Alas, today I am too busy, but I will try to find time.

**Comment by julienduroure** [comment]
@marstaik Yes, no problem. Let me know when ready.

**Comment by marstaik** [comment]
Hey @julienduroure , this has been fixed earlier today by https://github.com/godotengine/godot/pull/32213
