### ISSUE TITLE
godot rejects keyboard input

### ISSUE THREAD

**Issue by grenzionky** [godotengine/godot#31778]
**Godot version:**

3.1.1 and 3.2

**OS/device including version:**

 OS: Manjaro Linux x86_64 
 Kernel: 5.2.8-1-MANJARO 
 WM: bspwm 

**Issue description:**

why does godot keep on not accepting keyboard input?
one minute im tying up a script, and the next it just doesnt let me type in anything (not ever keyboard shortcuts) unless if i restart godot, and thats annoying to have to keep on doing.
i know its godot cuz my keyboard still works perfectly fine everywhere else on my computer.
 
**Steps to reproduce:**
copy something from outside of godot, then paste it into godot using `xdotool key ctrl+v`

**Comment by felaugmar** [comment]
I've experienced the same behavior on Manjaro too.

**Comment by santouits** [comment]
Can you both try a different window manager. Also @felaugmar what wm you use?

**Comment by felaugmar** [comment]
@santouits xfwm

**Comment by grenzionky** [comment]
i figured out the cause. i updated the main post

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
