### ISSUE TITLE
Pressing delete key while having animation selected in AnimatedSprite should delete animation not a node

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#31779]
**Godot version:**
3.1

**OS/device including version:**
Win 10

**Issue description:**

In AnimatedSprite when you add some animation and want to remove them you can select animation and press delete key this will then delete a AnimatedSprite node where as user is likely wanting to delete animation itself or a frame. 

I believe this is because node is still selected in a scene tree and editor thinks key presses are related to a node not anything else. Solution to this problem would be the moment user clicks on any resource to unselct node and treat last thing user clicked on as main focus. 

Expected behaviour from this would be I crate AnimatedSprite Create animation "idle" with 3 different frames. If I click on a individual frame and press delete I should delete this frame only. If I click on animation "idle" and click delete I should delete whole animation and if I click on AnimatedSprite and press delete I should delete node. 

**Steps to reproduce:**

Just add any animation to a AnimatedSprite and press delete.

**Minimal reproduction project:**

**Comment by AtomaFajrovulpo** [comment]
Present in _3.2 beta 1_.

**Comment by Feniks-Gaming** [comment]
Great news thanks for letting me know.
