### ISSUE TITLE
Tween.start() should return error if not in tree

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31785]
**Godot version:**

3.1

**Issue description:**

Currently Tween.start() will not return false (error) if the Tween node is not contained within the scene tree. It's a common mistake to forget to add Tween (and Timer) nodes to the tree, and there is little you can do to notice it if the supposed error value returns a success.

**Comment by 2shady4u** [comment]
Heyo,

I'm working on this! Should be quite easy..
![Capture](https://user-images.githubusercontent.com/42484461/64069558-46dd4d80-cc4c-11e9-85f6-0a95e3badfc1.PNG)

Also going to implement this for Timer.

Cheerios,

**Comment by 2shady4u** [comment]
Implemented this in #31844 
Please define the wanted behavior in this PR as it is a bit unclear 🤔

**Comment by akien-mga** [comment]
Fixed by #31844.
