### ISSUE TITLE
Project Setting : Render : default_clear_color

### ISSUE THREAD

**Issue by anatagawa** [godotengine/godot#3179]
hello,

i have trying the last build "December 31, 2015 at 14:37"

I have changed the Project Setting : Render : default_clear_color
and now, godot don't show my project in the project list .

It hate the default_clear_color value in the engine.cfg of my project.

i have this error: "engine.cfg:22 error: Expected value, got ERROR."
At core/io/config_file.cpp:180

```
[render]

default_clear_color=#FF000000
```

**Comment by volzhs** [comment]
this is duplicating issue with #3176

**Comment by vnen** [comment]
Closing as duplicate.
