### ISSUE TITLE
rect_scale of child in ScrollContainer will revert to 1 when scroll

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#31804]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

When set the rect_scale of a child in ScrollContainer to Vector(2,2), the child will scale to 2, but ,when start to scroll the ScrollContainer, the rect_scale will change to Vector(1,1) automatically, it's not as expected.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by TheDuriel** [comment]
Works as expected to me. The scrolling triggers a sorting of the container, which correctly does its job and takes complete control over the transforms of its children. This includes setting the scale.

**Comment by alexzheng** [comment]
For situation, if an image is inside a ScrollContainer, and zoom in the image and pan the image to scroll and see the details of the image.

**Comment by TheDuriel** [comment]
that is better achieved by updating the min_size of the texturerect node

**Comment by bojidar-bg** [comment]
Note that you can put a plain Control node without scale and with minsize in the ScollContainer, then put the TextureRect inside it.

**Comment by alexzheng** [comment]
the min size can zoom in the image, but it cannot zoom out, for example, to 50%.

**Comment by bojidar-bg** [comment]
@alexzheng change the stretch mode if you want to support zooming out.

**Comment by alexzheng** [comment]
which stretch mode support zoom out?

**Comment by bojidar-bg** [comment]
I guess you should experiment before asking, but `STRETCH_KEEP_ASPECT` seems like a good fit.

**Comment by alexzheng** [comment]
it seems my problem has been resolved, Thanks.
