### ISSUE TITLE
Physics objects don't detect the mouse if inside a sub-viewport

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#31802]
**Godot version:**
ba854bb

**Issue description:**
Physics objects (like `Area2D`, for example) inside sub-viewports aren't detecting any mouse inputs.

This was supposedly fixed in 26d33d1, but it's still reproducible as of now.

**EDIT:** `_unhandle_input`s are also not being detected at all.

**Comment by lukaskotik** [comment]
Was it really fixed? In 3.2.1 I still have to use 
```
func _input(event):
    $viewport.unhandled_input(event)
```
and if the scaling or size of viewport is different than is the project setting, event position have to first transformed.
