### ISSUE TITLE
Mono: FindScancodeFromString returns int while InputEventKey.Scancode expects uint

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#31809]
**Godot version:**
ba854bbc7bb0eae230299de4da8dfcb7caf74b69

**OS/device including version:**
Manjaro Linux x64

**Issue description:**
The C# method `OS.FindScancodeFromString(string)` returns an `int` whereas the `Scancode` member of `InputEventKey` expects a `uint`

The change to have `InputEventKey.Scancode` be a `uint` seems to have been made between 3.1.1->master (ba854bbc7bb0eae230299de4da8dfcb7caf74b69). Is this mismatch intentional or not?

**Comment by akien-mga** [comment]
CC @bruvzg. In `master` it's now `Key OS::find_keycode_from_string(const String &p_code) const` and `Key keycode`, I guess that means the issue is fixed?

**Comment by bruvzg** [comment]
In `4.0` it's using `Key` enum class everywhere (underlying type is `int`).
In `3.x` it's `uint32_t` in some places and `int` in another, but it should not cause any issues, only 31 bits are used.
