### ISSUE TITLE
No way of getting a disabled point in AStar

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#31814]
**Godot version:**
v3.2.dev.calinou.a5e0aa32d

**Issue description:**
I disable a point in AStar when i mouseclick near a point, but when i use astar.get_closest_point(mouse_position) on a disabled point, it just returns the closest enabled point, so I have no way of finding the disabled one.

I suggest to add a boolean parameter to get_closest_point method, something like this:

`AStar::get_closest_point(const Vector3 &p_point, bool ignore_disabled = true)`

Maybe I will need to learn some C++ soon, so I can start contribute for some simple stuff like this =)

**Comment by KoBeWi** [comment]
Actually disabled points are skipped since #30112, so to implement this one would just need to change what that PR did to be optional.

**Comment by fossegutten** [comment]
Yes, that is what I meant, sorry if it wasn't clear. Without the option to find the disabled points, there is not much use from disabling them :) But it should probably ignore disabled points by default, as this is what probably is the intended behaviour when moving characters around!

**Comment by KoBeWi** [comment]
> Yes, that is what I meant, sorry if it wasn't clear.

Ah, no, you were clear :) I just accidentally found that PR and realized the problem you describe should be easy to fix.

**Comment by akien-mga** [comment]
CC @bojidar-bg @AgentEnder @profan

**Comment by profan** [comment]
Sounds like a pretty reasonable addition, moreover it's easy to add too :)

If someone else wants to pick this one up I'll leave it to them as it seems like a good first PR.

**Comment by AgentEnder** [comment]
This seems like a good change, but I'm not sure what would need to be changed to enable this from the gdscript/c# side.

**Comment by profan** [comment]
@AgentEnder as long as you can figure out the change in the C++, the only other thing to make sure it works on the gdscript/C# side is changing this bit here:
https://github.com/godotengine/godot/blob/6cd00432c39d97f6fc1e23fff59be58c8764c115/core/math/a_star.cpp#L543-L544

So it matches the new extra argument, and then marking the argument with its given default value with `DEFVAL` as for the `set_point_disabled` for example, then just some testing and you're there 👍 
(probably run the existing astar tests too)

**Comment by hbina** [comment]
Any minimum test project for this behavior?

**Comment by profan** [comment]
@hbina Make a small project for it and probably also add a small regression test to the existing astar tests in https://github.com/godotengine/godot/blob/master/main/tests/test_astar.cpp, one or two cases you know should fail if this functionality doesn't do what's expected.

Can just be something like create an AStar instance + add two points, disable one, get the closest point for one where you know it should fetch the disabled one (and also not fetch the disabled one for the other case probably).
