### ISSUE TITLE
please add max size for controls

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#31811]
Please add a max size for controls. 
this will allow people to stop things like containers from expanding when children items are too big

**Comment by TheDuriel** [comment]
Enabling the clip_contents flag practically achieves this in most cases.

**Comment by Zireael07** [comment]
... except for the little thing where clipped controls do react to input outside the clip (the clip is ONLY visual)

**Comment by TheDuriel** [comment]
That can be solved with the _clip_input virtual function. Simply declare it and return true.

**Comment by Shadowblitz16** [comment]
clip contents flag clips the contents if children go outside of it.
it doesn't limit the size of your control of children try to make it bigger

**Comment by girng** [comment]
the container's size is based on their children

**Comment by TheDuriel** [comment]
Which is why you enable both.

Granted, it will stop the control from growing alltogether, but often this is ok.

**Comment by Shadowblitz16** [comment]
that was the whole point though so the control doesn't grow past its max size.
many gui libraries have this property and I think godot should have it too

**Comment by nathanwfranke** [comment]
Can we get discussion label?

Personally I support this. I think eventually this could work with stuff like scroll container, where items that are added expand the container until it reaches the maximum size. This is not possible with clip content without a custom script.

**Comment by akien-mga** [comment]
This should actually be moved to https://github.com/godotengine/godot-proposals for further discussion with the community. The proposal would need to be fleshed out some more to explain the use cases (ideally showing how they have to be handled now - if possible - and what the proposal would allow to simplify the workflow).

**Comment by MattUV** [comment]
For information I just opened an issue in the godot proposal repository that looks like your proposal ;)
https://github.com/godotengine/godot-proposals/issues/1802
