### ISSUE TITLE
Explicit types break contextual autocompletion

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31818]
**Godot version:**
4f6eb36

**Issue description:**
...at least for AnimationPlayer. Here's a typed AnimationPlayer node variable:
![image](https://user-images.githubusercontent.com/2223172/64057712-b564d180-cba0-11e9-8bb5-b8bf8ea27093.png)
Works as expected. But when we enforce the type to make sure it's AnimationPlayer:
![image](https://user-images.githubusercontent.com/2223172/64057713-c01f6680-cba0-11e9-8b2d-86c926ac2b8a.png)
The animations don't show.

**Comment by akien-mga** [comment]
Does it work with `onready var anim : AnimationPlayer = $AnimationPlayer`?

**Comment by KoBeWi** [comment]
Huh, it actually works. So only using `as` causes problems in this case.

**Comment by KoBeWi** [comment]
This is actually closely related to https://github.com/godotengine/godot/issues/33434#issuecomment-559147462. When you use `as`, the variable loses the original context, even if it's converted to the same type.

**Comment by KoBeWi** [comment]
@bojidar-bg Um, looks like #34286 didn't fix this.

**Comment by bojidar-bg** [comment]
@KoBeWi Oh yeah? Mind if you give a reproduction example or project? :)

**Comment by KoBeWi** [comment]
Weird, it actually works in a minimal project. I'll look into it if it happens again.

**Comment by KoBeWi** [comment]
Aaand I found a reproducting case.

works
![image](https://user-images.githubusercontent.com/2223172/72671691-51a74c00-3a4e-11ea-8644-8c927aad3aae.png)

worksn't
![image](https://user-images.githubusercontent.com/2223172/72671697-579d2d00-3a4e-11ea-9a52-af4b8ddb3e40.png)

Although this might be slightly different issue, because `connect` is not strictly tied to Tweens.
@bojidar-bg

**Comment by bojidar-bg** [comment]
![image](https://user-images.githubusercontent.com/5276727/72678885-bf855f00-3ab2-11ea-9d88-36e2e106ebce.png)

This is a weird case: it work when autocompleting directly from `tween.con<tab>`, but not from `tween.connect(<tab`

**Comment by ThakeeNathees** [comment]
is this still reproducible? seems like fixed to me!

**Comment by KoBeWi** [comment]
Seems like my new example is fixed in master.

This has cherrypick 3.2 label, so it would be nice if someone could find which commit fixed the issue, but otherwise it can be closed.

**Comment by akien-mga** [comment]
Seems fixed in the 3.2 branch too (b929f561d), the fix was likely cherry-picked.
