### ISSUE TITLE
Signal not emitted for ScrollContainer

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#31819]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

When the scrolling is triggered by dragging on the scroll bar or by the InputEventPanGesture, no scroll_started or scroll_started is emitted.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by tom-jk** [comment]
Can reproduce in 3.1 thru 3.2.3.rc3.

Can get the scrollbars and use their `scrolling` signal, but nothing from the container itself.

MRP: [31819.zip](https://github.com/godotengine/godot/files/5011132/31819.zip)

**Comment by KoBeWi** [comment]
Closing as duplicate of #22936
