### ISSUE TITLE
please disallow controls to overflow out of container controls

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#31812]
please disallow controls to expand past the container controls they are in, or make flag that does this for all containers.

Godot version: 3.1.1

**Comment by groud** [comment]
That does not make any sense. Container are made to **contain** things. If you need overflowing controls, use the anchors and margins workflow.

**Comment by Shadowblitz16** [comment]
that's the thing though if a child has a min size that is bigger than the container it goes outside of it.
which also doesn't make sense.

why would someone need a container if there controls exceed the bound of it?

**Comment by girng** [comment]
please post an example code @Shadowblitz16  there is a bit of ambiguity with the issues I don't really understand what exactly you are trying to do, and what you expect to happen.

**Comment by Shadowblitz16** [comment]
hmm going back to my project to test rect_clip_content I can't reproduce the issue.
all controls rect_clip_content is false but its not going outside of the bounds
