### ISSUE TITLE
angle_to() differs when source vector is transform.y

### ISSUE THREAD

**Issue by trommlbomml** [godotengine/godot#31823]
**Godot version:**
Godot 3.1.1 stable

**OS/device including version:**
macOS Mojave 10.14.5

**Issue description:**
I have some problems with Vector2.angle_to in combination with transform2D.y. It seems like I get a wrong angle for the correct values. If I send the same values hard-codes to angle_to(), the result of the operation is correct, with transform.y() not. This is confusing as I am trying to implement a animated, rotated tank and I use this function to check if I have reached my target rotation angle.

**Steps to reproduce:**
1. Create a scene with a Node2D as a root.
2. Attach a script, only _ready() is needed.
3. Insert the following code:

`extends Node2D

var target_angle = Vector2(0,-1)

func _ready():
	print("target_angle = ", target_angle)
	print("-transform.y = ", -transform.y)
	print("-transform.y.angle_to(target_angle) = ", -transform.y.angle_to(target_angle))
	print("Vector2(-0,-1).angle_to(Vector2(0,-1))) = ", Vector2(0,-1).angle_to(Vector2(0,-1)))
`

4. The result should be - if am not overseeing something really stupid - the same for statement 3 and 4, but they are different by PI. Here is my output:

> target_angle = (0, -1)
-transform.y = (-0, -1)
-transform.y.angle_to(target_angle) = 3.141593
Vector2(-0,-1).angle_to(Vector2(0,-1))) = 0

**Minimal reproduction project:**
Not included, above steps are sufficient.

**Comment by akien-mga** [comment]
That's not a bug, it's a misunderstanding of operator precedence. `-transform.y.angle_to(target_angle)` calls `angle_to` on `transform.y`, then negates it. So it's the angle between `(0, 1)` and `(0, -1)`, which is -PI (since Y points downwards), then negated, so PI.

The 0 angle you're trying to get would be `(-transform.y).angle_to(target_angle)`.
