### ISSUE TITLE
not all the InputEventScreenTouch events is triggered in _gui_input

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#31822]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

Touch two or more fingers on the screen, two InputEventScreenTouch events is triggered with event.pressed = true, However, when release the fingers, only the last finger triggered a event with event.index =0 , event.pressed = false, all other InputEventScreenTouch events is lost.

In _input function, all these events can get.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by PonasKovas** [comment]
Can reproduce.

**Comment by PonasKovas** [comment]
minimal reproducible example:
[inputeventscreentouch.zip](https://github.com/godotengine/godot/files/4885383/inputeventscreentouch.zip)

**Comment by madmiraal** [comment]
Closing as it's a duplicate of #29525.
