### ISSUE TITLE
Kinematicbody not colliding with staticbody

### ISSUE THREAD

**Issue by oxrock** [godotengine/godot#3182]
I'm working on a camera raycasting demo for 3d found here: https://github.com/oxrock/Godot-camera-raycasting-demo and ran into the problem of collision not behaving as expected. I can simply change the staticbody node type to rigidbody and collision with the player(kinematicbody) starts working. If I change it back to staticbody, collisions stop again.

**Comment by eska014** [comment]
Use `move()` instead of `translate()` to move KinematicBody nodes. Make sure to call from `_fixed_process()`
(No need for `self` by the way, you can just write `move` rather than `self.move`)
