### ISSUE TITLE
magnetometer has a bug with iphone device ?

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#31830]
**Godot version:**
3.1

**OS/device including version:**
macos 10.14.4

**Issue description:**
when I test the magnetometer info with xcode runing it give me x,z change when I turn around. But after I disconect wire link mac and run the demo solo. It change to y,z change info when I turn around. 

**Steps to reproduce:**

**Minimal reproduction project:**
here is my code :
```
func _process(delta):
    var acce = Input.get_accelerometer()
    var mag = Input.get_magnetometer()
    mag = mag.normalized()
    acce = acce.normalized()
    rotation = Vector3(acce.z*.4*PI,atan2(mag.z,mag.x),0)
```

I want a camera rotation with iphone direction angle.(code is poor ~~ sorry)

![](https://user-images.githubusercontent.com/1890538/64067193-3ed6db00-cc57-11e9-9090-3bfd4edce939.png)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc5](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-5) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
