### ISSUE TITLE
Tilemap editor gui don't stay in place in Animation tab

### ISSUE THREAD

**Issue by ElefanteNoi** [godotengine/godot#31836]
**Godot version:**
3.1.1 stable

**OS/device including version:**
Windows 7

**Issue description:**
~~https://im2.ezgif.com/tmp/ezgif-2-2744b0f33c16.gif~~
https://i.imgur.com/lJ6tDaY.gif

**Steps to reproduce:**
Select Animation tab in Tilemap Editor

**Comment by myhalibobo** [comment]
Self-compiled 3.1.1 doesn't have this problem

**Comment by bojidar-bg** [comment]
What is the size of the editor window, in pixels (or, if maximised, the size of your screen)?

**Comment by myhalibobo** [comment]
@bojidar-bg I found this error, need to reduce the window, the full screen will not be a problem

**Comment by akien-mga** [comment]
Duplicate of #28135, fixed by #33829.
