### ISSUE TITLE
Custom Theme hides Autocomplete

### ISSUE THREAD

**Issue by orestiskon** [godotengine/godot#31834]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
While following Heartbeast's theming tutorial, I realized using a custom theme hides the auto-complete in the script editor.
Tutorial link: https://youtu.be/V6Zsg27n__Y

**Steps to reproduce:**
1. Right click on a resource -> Add New Resource
2. Select "Theme", click save
3. Double click on the theme file, on the Theme Editor click "Edit Etheme" and select "Create from current Editor Theme"
4. On the Inspector click Save
5. Go to Project Settings, select Theme under GUI
6. Assign the created theme file to the "Custom" parameter
7. Save, Quit to Project List and Reopen the project

If you now try to write a script, you will see the auto-complete is not visible, greatly hindering the scripting process.

You will find a project file attached with the autocomplete already broken.

**Minimal reproduction project:**

[ThemeTest.zip](https://github.com/godotengine/godot/files/3562720/ThemeTest.zip)

**Comment by Jean-Low** [comment]
Following the same tutorial, I got the exact same issue.
I was going to open an issue but thankfully you already did.
So I will just post comment this here to help to raise attention to this problem.

**Comment by AlexeyGrishin** [comment]
Met same issue on Mac.
Godot v3.1.2.stable.official.

**Comment by KoBeWi** [comment]
Fixed in 3.2
