### ISSUE TITLE
Some errors  do not lead to application stop in editor

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#31842]
In current master branch some error are now labelled "SCRIPT ERROR:" and do not lead to stop in editor.
This leads to portions of scripts being silently skipped if user does not pay attention to console output.
Example:
```
SCRIPT ERROR: DNATool.create_common: Invalid call. Nonexistent 'Array' constructor.
   At: res://characters/dna_tool.gd:323.
```

**Comment by Calinou** [comment]
Can you still reproduce this in 3.2.1?

**Comment by akien-mga** [comment]
I can't reproduce it in 3.2.3 RC 1:
```gdscript
func _ready():
	var badarr = Array(7)
```

Triggers:
```
SCRIPT ERROR: GDScript::reload: Parse Error: Invalid arguments for 'Array' constructor.
   At: res://Node2D3.gd:4.
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:599.
```
and interruption of the game execution.
