### ISSUE TITLE
Provide error message for every single ERR_FAIL, ERR_FAIL_COND etc.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#31849]
**Issue description:**
There is a lot of errors, that shows when using Godot. Some of this errors are not really clear:
```
core/node_path.cpp:215 - Condition ' !data ' is true. returned: StringName()

ERROR: affine_invert: Condition ' det == 0 ' is true.

At: ./core/cowdata.h:252:resize() - Condition ' psize < 0 ' is true. returned: ERRINVALIDPARAMETER

ERROR: ~List: Condition ' _first != __null ' is true.

Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null

editor/plugins/asset_library_editor_plugin.cpp:1206 - Condition 'category_map.has(r["category_id"]) ' is true.

core/class_db.h:186:register_virtual_class() - Condition ' !t ' is true.
```
So I think, that every ERR_* macro (maybe except ERR_CRASH, ERR_FAIL_INDEX), should provide clear error message.

*

A lot of ERR_FAIL can be easy to describe, like
https://github.com/godotengine/godot/blob/00aabec8bb598592b8a8702797b51fc9f6ca6169/core/image.cpp#L2058
```ERR_FAIL_COND_MSG(p_src.is_null(), "It isn't valid Image resource."); ```
https://github.com/godotengine/godot/blob/de4aabe89b7b68677f145f21c956183bbc92f686/core/pool_vector.h#L539
```ERR_FAIL_COND_V_MSG(alloc->lock > 0, ERR_LOCKED," Can't resize Pool Vector if locked!");```
 
*

People creating PR should always use ERR_*_MSG because, they should know best what the message should be.
 
*

Current number of macros without error message (Godot 3.2 00aabec8b)
```
rg "ERR_FAIL[_V]{0,2}\(" | wc -l
228

rg "ERR_FAIL_COND[_V]{0,2}\(" | wc -l
5091

rg "ERR_CONTINUE\(" | wc -l
274

rg "ERR_BREAK\(" | wc -l
50

rg "ERR_FAIL_NULL[_V]{0,2}\(" | wc -l
162

rg "CRASH_COND\(" | wc -l
124

```

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/42719, which should *hopefully* get more discussion going.
