### ISSUE TITLE
Vector2.INF != Vector2.INF

### ISSUE THREAD

**Issue by th1z** [godotengine/godot#31859]
**Godot version:**
Godot 3.2.dev: 5dd51a5b3b3da516c0e8bb2855d2772def037203

**OS/device including version:**
Win x64

**Issue description:**
In the latest Godot version (5dd51a5b3b3da516c0e8bb2855d2772def037203):
print(Vector2.INF == Vector2.INF) // => False

In Version 3.1.1:
print(Vector2.INF == Vector2.INF) // => True

**Steps to reproduce:**
```
print(Vector2.INF == Vector2.INF)
```

**Comment by akien-mga** [comment]
CC @aaronfranke

**Comment by Anutrix** [comment]
Not sure but I think infinity != infinity makes sense but weird.

**Comment by th1z** [comment]
It should be noted that:
`print(INF == INF) // => True` even in Godot 3.2.dev.

**Comment by akien-mga** [comment]
I'm pretty sure it's due to #18992.

**Comment by aaronfranke** [comment]
#31871 fixes this. Infinity values should be the only problematic values with the current code.
