### ISSUE TITLE
Quit to Project List is not triggered when press Alt > Shift > Q on Windows

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3185]
I guess both case should work.

<kbd>Shift</kbd> > <kbd>Alt</kbd> > <kbd>Q</kbd> => fine
<kbd>Alt</kbd> > <kbd>Shift</kbd> > <kbd>Q</kbd> => doesn't work

**Comment by vnen** [comment]
Wait, isn't the shortcut actually <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Q</kbd>? That's what's shown to me and works in any order.

**Comment by volzhs** [comment]
it was changed at 9c38ad00936f89c4c6ddacfdbf0332e9f1623bca

**Comment by vnen** [comment]
Oh, my bad. However, I just recompiled and am not able to reproduce this. For me it works in any order.

**Comment by volzhs** [comment]
I will try it again with current head.

**Comment by volzhs** [comment]
I compiled and tested with current head 0ed864d876347841d60797773a37c0b2f235c85c
On Ubuntu 14.04 it works fine.
On Windows 7 it does not. <kbd>Alt</kbd> > <kbd>Shift</kbd> > <kbd>Q</kbd> doesn't do anything.
