### ISSUE TITLE
Adding non-default inherited properties to documentation

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#31855]
PR #29380 added support for showing the default values of class properties in the documentation, which is a huge boost in usability and completeness for the docs.

Reading discussions about `ViewportContainer`'s default value for `mouse_filter` that differs from that of the parent class (#31825), I thought we could maybe try to show such overridden default values for inherited properties in the documentation too.

It could likely be an extra table below "Properties" (see e.g. http://docs.godotengine.org/en/latest/classes/class_viewportcontainer.html) listing inherited properties with init values different from the ancestor class that defines the property.

Other inherited properties with the same default value as the base class should likely not be listed -- though that may be up for discussion given that some users have difficulty understanding that a node's available properties are its own + those of its base classes.

According to @bojidar-bg, `ClassDB` might already have the necessary support for getting this information, so it would just need to be implemented in the docs generator and properly displayed.

**Comment by bojidar-bg** [comment]
> It could likely be an extra table below "Properties" [...]

How would that table be named? "Inherited Properties" is good if all inherited properties are listed, but this is likely not going to be the case. Maybe "Overridden Properties"?

**Comment by akien-mga** [comment]
> Maybe "Overridden Properties"?

:+1:
