### ISSUE TITLE
Add keywords to labels whose content is inherited from their owner.

### ISSUE THREAD

**Issue by carllacan** [godotengine/godot#31868]
I apologize for wasting your time if there is already a way to do what I'm going to describe.

Very often we need to update the _text_ on a Label object to indicate changes in health, money or similar information. My usual method for doing this is using code on a script attached to a node that sits somewhere above the Label, usually the node that represents the whole HUD or UI. This code regularly looks for the relevant information and updates the Labels, which often sit at the end of the nodetree. 

This means I usually have to find the node before updating it, with something like this: 

var label = $HBoxContainer/VBoxContainer/PanelContainer/HBoxContainer/Label
label.text = newtext

That node sequence is not a real-world example, I made it up, but my point is that you need to type out the whole structure. Most of the time this is only mildly annoying, but if later on you rearrange the node structure the code breaks. Multiply this by all the labels you might need to have in a complex strategy game and modifying the UI becomes a real problem.

### My proposal:

Add the possibility to use keywords on the _text_ fields of Label objects, which are filled out with information taken from their parents/owners. For instance:

Image we have a complex UI with many nested containers. A leaf of this nodetree is a Label node that indicates, say, the health of the player, like this: "Health: 100 HP". Instead of having to find the node and write code that depends on a specific UI structure we could, in my proposal, simply use the editor's GUI to set the _text_ field of the label to "Health: {health} HP". 

When rendering this Label the engine would parse that string, realize there is a keyword and look at the attributes of the Label node. If it didn't find a .health attribute there it would try to find it on the Label's owner or parent (I'm not sure which would be better, but I would say the owner). Failing to find it there it would look on the owner's owner, or the parent's owner, all the way up to the root. In case it didn't find it would throw an exception or, perhaps, just print "Health: null HP". 

This way we would only need to update an attribute on the owner or parent and all changes would be propagated downwards, without the need to add a single line of code. 

There is also another minor benefit. The text we write on the _text_ fields on Label objects (using the GUI I mean) is very often just a placeholder, since we will later overwrite it with code. In my proposal this field would actually be useful beyond being a placeholder :-)

Of course there are ways you can implement something like this already, by attaching a short script to the Label nodes themselves, but then you'd still need to call that code, which means you'd still need to find that node with code that depends on the structure of the UI in order to update the label. Also you end up scattering your code among many files, which I personally dislike.

I've also considered (haven't tried it yet) creating a KeywordLabel class that extends Label and use groups to update all their _text_ fields. While I think this might work I think it would be an interesting feature for the editor itself to have. Also, a similar behaviour could be extended to other kinds of nodes, like ProgressBars, so that they automatically update their values when their owners' attributes change.

Thank you for your attention.

**Comment by KoBeWi** [comment]
The problem you are describing affects not only labels. The usual approach is to use an `onready` variable that keeps the node and using the node only through this variable. Then if the path changes, you need to update it only in one place. There are multiple ways to do this without needing to type it manually (from using autocompletion to dragging the node from scene tree into script editor), so I'd consider it a minor annoyance.

If you however want the path to be autoupdating, you can export a NodePath variable, which will point to the correct node even if you move it around.

**Comment by carllacan** [comment]
> The problem you are describing affects not only labels. The usual approach is to use an `onready` variable that keeps the node and using the node only through this variable. Then if the path changes, you need to update it only in one place. There are multiple ways to do this without needing to type it manually (from using autocompletion to dragging the node from scene tree into script editor), so I'd consider it a minor annoyance.
> 
> If you however want the path to be autoupdating, you can export a NodePath variable, which will point to the correct node even if you move it around.

I agree it's a very minor annoyance, but since most projects will have to update labels I think this feature would, at the end of the day, save a non-negligible amount of time and bugs.

**Comment by mrcdk** [comment]
You don't really need the full path, name the label something unique like `HealthLabel` and then you can get it with `onready var HealthLabel = find_node("HealthLabel")` 

This way it doesn't matter if you move it afterwards as long as you don't change the name of it

**Comment by carllacan** [comment]
> You don't really need the full path, name the label something unique like `HealthLabel` and then you can get it with `onready var HealthLabel = find_node("HealthLabel")`
> 
> This way it doesn't matter if you move it afterwards as long as you don't change the name of it
> 
> It's slower than giving it the full path so don't use it inside a process function or something that gets called a lot.

Oh, wow, that's cool. I thought find_node was pretty much the same as get_node. I guess my proposal doesn't actually save all that much work, then.

Thank you all.

**Comment by MohammadKhashashneh** [comment]
Isn't a refactoring editor feature more useful/convenient, especially for complex scenes?

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
