### ISSUE TITLE
Atomic operations in SefRefCount are not properly cross-platform

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#31860]
**Godot version:**
3.2 master (adb85fc8)

**OS/device including version:**
All, but known problems on OpenBSD/macppc so far, or Android/x86 if `__atomic*` methods are used.

**Issue description:**
#31321 by @julianaito aimed to address a portability issue for `SefRefCount`'s atomic operations on OpenBSD/macppc, but caused an issue with Android/x86 (#31407).
It was thus reverted for the time being, but a better solution needs to be looked into and merged again.

See discussion in #31407, and the possibility to simply drop `SafeRefCount` in 4.0 to use atomic types from the standard library instead.

CC @RandomShaper @hpvb @reduz

**Comment by KoBeWi** [comment]
Is this still valid on master?

**Comment by RandomShaper** [comment]
In the upcoming days I'll be working on these areas of bringing C++ implementations of multi-threading stuff. Stay tuned.
