### ISSUE TITLE
Improvements to ruler tool

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31888]
**Godot version:**
220ff5baf29673ebdce4aeef4ddd19b629b44e9f

**Issue description:**
#31829 was merged, adding a very cool ruler tool for 2D editor:
![gTFD3aWqhD](https://user-images.githubusercontent.com/2223172/64065778-68214800-cc12-11e9-8158-2128d703ee66.gif)

There are some things that could be added to make it _even more cool_:
- [x] a dedicated icon (right now it uses icon from LineEdit, which is ok, but... green)
- [ ] support for smart snapping (right now it only snaps to grid, but could snap to nodes, to make measuring distance between them easier)
- [x] angle measuring

**Comment by YeldhamDev** [comment]
A few minutes in Inkscape and I came up with this. Is this presentable? (The color is to facilitate viewing it here):
![Screenshot_20190902_102841](https://user-images.githubusercontent.com/30739239/64117909-e5b99500-cd85-11e9-9350-92d9342cc42b.png)

**Comment by YeldhamDev** [comment]
Here's how it looks in the editor. Sadly, the lines are too small for it to look good for its size. Maybe it just being a triangle with a hole in the middle is enough to express its purpose?
![Screenshot_20190902_105652](https://user-images.githubusercontent.com/30739239/64119579-b2790500-cd89-11e9-98fe-4ba63b4ee5f3.png)

**Comment by isaacremnant** [comment]
What happens when you drag the line outside of the view (or if you zoom)? Maybe the strings then need to display aound the mouse corner?

**Comment by KoBeWi** [comment]
The strings are always visible. If they end up outside screen, they are clamped to the edges.
![image](https://user-images.githubusercontent.com/2223172/64122500-190a1d00-cda2-11e9-8fd6-fb0d672495a4.png)

**Comment by isaacremnant** [comment]
Ah ok sorry! didn't have time to test the commit.

**Comment by KoBeWi** [comment]
Closing as it's mostly resolved. I use this tool a lot, but never actually though "I wish it smart-snapped too". Of course it depends on usage, but if someone wants smart-snapping support, they could open a proposal.
