### ISSUE TITLE
iOS crash when using SphereMesh with GLES2

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#31905]
**Godot version:**
3.1.1

**OS/device including version:**
iPhone Xr with iOS 12.4
iPad mini 2 with iOS 12.2

**Issue description:**
Game crashes when a scene with a SphereMesh is loaded and GLES2 is used on an iOS device.

iPad mini 2 crashes with the "EXC_BAD_ACCESS" error:
<img width="1143" alt="Screenshot 2019-09-02 at 19 21 29" src="https://user-images.githubusercontent.com/39428930/64128603-a60ba100-cdb7-11e9-96b2-9cb442425f1e.png">

iPhone Xr with iOS 12.4 with iOS 12.2 segfaults:
<img width="1143" alt="Screenshot 2019-09-02 at 19 20 21" src="https://user-images.githubusercontent.com/39428930/64128629-bde32500-cdb7-11e9-857a-a9ef2dde4161.png">

**Steps to reproduce:**
1. Create a new project.
2. Enable GLES2.
3. Set default environment to use clear color.
4. Add a SphereMesh to the scene and assign a SpatialMaterial to it.
5. Run project on an iOS device.

**Workaround:**
Decreasing the "RadialSegments" and "Rings" properties of the mesh to a lower number (e.g. 12) solves the problem, but causes less detailed mesh.

**Minimal reproduction project:**
[3dtest.zip](https://github.com/godotengine/godot/files/3566816/3dtest.zip)
(edit: updated the minimal reproduction project, the previous one had "RadialSegments" and "Rings" set to 12, so it did not crash)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
