### ISSUE TITLE
Triggers on X-box controller no longer work

### ISSUE THREAD

**Issue by TheoXD** [godotengine/godot#3190]
I remember there was a PR with a proper controller mappings but probably since then analogue triggers stopped working on Windows. Making sure - analogue input can't be gathered, currently works only as a normal button. It's no longer on any axis 0-7 , used to be 3.
This is the commit #3101

**Comment by adolson** [comment]
This type of thing has been discussed in issue #49

**Comment by Hinsbart** [comment]
Well, having triggers as button events is considered the proper mapping. Take a look at the constants in [InputEvent](https://github.com/godotengine/godot/blob/master/core/os/input_event.h). `JOY_L2` and `JOY_R2` are defined as buttons `6` and `7` ;)

So this is not really a bug but more of a feature request. Also I already have the code for analog triggers on my machine, just didn't find the time to make a PR yet.. holidays and such ^^

**Comment by Hinsbart** [comment]
fixed by #3192

**Comment by kubecz3k** [comment]
@TheHX @Hinsbart
Ok as far as I understand this issue is now fixed  :+1:  so closing it :)

**Comment by TheoXD** [comment]
@kubecz3k, not TheHX, TheoXD

**Comment by kubecz3k** [comment]
@TheoXD @TheHX Sorry guys! It's fault of auto-completion I assume
