### ISSUE TITLE
Acute / Quoteleft / Circumflex/ Accent mark problem in TextEdit and LineEdit

### ISSUE THREAD

**Issue by SuzukaDev** [godotengine/godot#31914]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7 64bit

**Issue description:**
On a TextEdit and LineEdit, when writing the acute, quoteleft or circumflex  `` ´ ^ ` ``  following by a consonant, it triggers different F's.
Basically is like pressing and holding different F's (**forever**, until you press manually the specific Fx that was magically triggered) .

**Special mention to `w, wich, I don't know why, quits the running scene.**

For example (the text typed and the Key triggered):

```
`p = F1
`q = F2
`r = F3
`s = F4
`t = F5
`v = F7
`w = F8 (thanks Calinou). In the editor, quits the scene, and in build, freezes the TextEdit/LineEdit, and it wont "accept" new input until you press manually the key F8)
`x = F9
`y = F10
`z = F11
```

Note:
```
` is: KEY_QUOTELEFT = 96 — ` key.
´ is: KEY_ACUTE = 180 — ´ key
```
Acording to
https://docs.godotengine.org/en/3.1/classes/class_@globalscope.html

I tested and reproduced it in different keyboards/languages (spanish, german, etc).

**Possible Related issues:**
https://github.com/godotengine/godot/issues/30477
https://github.com/godotengine/godot/issues/16858

**Steps to reproduce:**
- Open sample project.
- Type ´ or ` (KEY_QUOTELEFT  & KEY_ACUTE) following a consonant on the TextEdit or the LineEdit.
- See how in console, triggers different F's

**Minimal reproduction project:**
[AcuteFsIssue.zip](https://github.com/godotengine/godot/files/3567159/AcuteFsIssue.zip)

**Comment by SuzukaDev** [comment]
I think this issue needs some love. Its pretty weird and shady.

I first thought that adding an accent plus a consonant, could be doing something weird, like adding unicodes or something, and triggering different keys. But I don't know.

Also, the problem is not only it triggers random keys, but it keeps them triggered forever. You need to press manually the key "magically triggered" (with an accent) to stop it.

I don't know how godot handles the input, but seems very weird.

**Comment by SuzukaDev** [comment]
Also, LineEdit and TextEdit is very common node. A simple error from an user typing an accent `` ` ´ ^`` following a consonant instead a vocal, could lead to a lot of errors in games/apps, and is very hard to "track" for an user that is not aware of this issue.

**Comment by Calinou** [comment]
> ```text
> `w = Following the parttern, it should be F8. 
> But I don't know. Quits the scene.
> ```

This is because pressing <kbd>F8</kbd> always stops the running project (while running a project from the editor).

**Comment by bojidar-bg** [comment]
Cannot confirm on Linux with QWERTY non-international English keyboard.
Make sure to test with the non-international keyboards.

**Comment by SuzukaDev** [comment]
I paste here what an user from the Godot Discord discovered, it case its useful>

> typing ^p sends two WM_CHAR events (^ followed by p) and that the code for p is the same code as VK_F1
> so Godot thinks the second input isn't a "char" for some reason and this is why it interprets it as a KEYDOWN event of the F1 key
> 

Im going to do some tests with different keyboards

**Comment by SuzukaDev** [comment]
Ι made some random tests on different keyboards (using Windows 7 64 bits):
Spanish (Spain) - Reproduced
Spanish (Chile) - Reproduced
English (Canada (French Canadian)) - Reproduced
Portuguese (Portugal) - Reproduced
Portuguese (Brazil) - Reproduced
German (Germany) - Reproduced
French (France) - Reproduced

I tried English (US) but, even googling, I don't know how to put accent marks like ó á ô

**Comment by SuzukaDev** [comment]
I've found a workaround to "solve" the bug ingame:


```
func _simulate_key_release(keyScancode):
	yield(get_tree(), "idle_frame")

	var ev = InputEventKey.new()	
	ev.pressed = false
	ev.scancode = keyScancode
	Input.parse_input_event(ev)
```

Whenever a Fx is triggered, I call _simulate_key_release() to ensure that is released.
The `yield(get_tree(), "idle_frame")` is optional, but I like the event to "stay alive" one frame just in case other scripts are "listening" to that key to be triggered.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta2

**Comment by SuzukaDev** [comment]
Issue stills on v3.3.2estable.official

**Comment by noidexe** [comment]
Just encountered this on 3.5.1-rc2 (Win 10, US-intl)
