### ISSUE TITLE
Stadia Support

### ISSUE THREAD

**Issue by adrian-goe** [godotengine/godot#31912]
**Feature Request:**
Google Stadia is coming later this year. Unity is full supported. So I would love to see a godot support for Stadia too. 

I cant do this by my self, so i create this Featue Request.

**Comment by TheFlamyy** [comment]
I'm not sure as to whether a public API exists or not - I briefly searched the web but couldn't find anything in particular (Could you link some resources?).

It seems they will be using [Vulkan as their graphics API](https://en.wikipedia.org/wiki/Google_Stadia#Software). Doesn't it mean that after 4.0 is released that it should be compatible?

**Comment by Flashnos** [comment]
I'm not sure volcan support is all that's needed.
There is a stadia SDK for which you have to apply. Unity and Unreal are both integrated. Currently hidden behind the stadia-dev account.

To get this account you have to apply via https://stadia.dev/

Maybe it is easier to contact the stadia team directly and find out how to integrate the support of stadia.

https://www.unrealengine.com/en-US/blog/unreal-engine-support-for-google-stadia-now-available

**Comment by nobuyukinyuu** [comment]
Unless the SDK is compatible with the MIT license Godot uses, it's unlikely to ever be supported officially.  This is why most other console targets aren't currently available..

**Comment by Calinou** [comment]
I'll close this due to apparent lack of support (see the above comments). If you still feel there's a need for this, please [open a proposal](https://github.com/godotengine/godot-proposals) on the Godot proposals repository. Still, expect this to be an uphill battle as Stadia doesn't seem to be much of an open platform.
