### ISSUE TITLE
file.get_csv_line() does not get line without CR

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#31910]
**Godot version:**
3.1.1

**OS/device including version:**
Windows

**Issue description:**
file.get_csv_line() doesnt read the last line when last char is not a CR/LF

**Steps to reproduce:**
MPR attached
[MRP csv_line.zip](https://github.com/godotengine/godot/files/3567053/MRP.csv_line.zip)

**Comment by sparkart** [comment]
The following reads your csv file fine.
```
while !csv.eof_reached():
    riga=csv.get_csv_line(";")
    prints(riga)
```

**Comment by burstina** [comment]
that's not what I meant.

from documentation:

 
>  bool eof_reached ( ) const
> 
> Returns true if the file cursor has read past the end of the file.
> 
> Note: This function will still return false while at the end of the file and o**nly activates when reading past it**. This can be confusing but it conforms to how low-level file access works in all operating systems. There is always get_len and get_position to implement a custom logic.

That means the while loop in MRP has to work as is.

**Comment by sparkart** [comment]
This could be a documentation issue, or change the way get_csv_line() works, because it already calls eof_reached() and breaks out of its process if it returns true.

**Comment by burstina** [comment]
@KoBeWi 
Considering the code example proposed by SparkArt works correctly, should be the case to change the issue title in "eof_reached() triggered when file.get_csv_line() fetches last data row"?

**Comment by burstina** [comment]
@sparkart 
After reading your reply, I did some research about file treatment on some languages and I found interesting that EOF behaviour is not the same: some works like Godot, some others not.
Speaking more clearly:  Godot's file.open() can trigger EOF on empty files, some other languages don't, instead they trigger EOF on file.read().

So yes, you are right, Godot works fine, it is not a bug.
