### ISSUE TITLE
Custom project font overrides Container warning text

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31917]
**Godot version:**
037237f

**Steps to reproduce:**
1. Create a valid DynamicFont resource
2. Set it under Project Settings -> GUI -> Theme -> Custom Font
3. Restart the project
4. Create a Container node and a child
5. Try to move the child
6. 
![image](https://user-images.githubusercontent.com/2223172/64136563-bdb44b00-cdf2-11e9-88f3-1c09ff054d44.png)

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/3567316/ReproductionProject.zip)

**Comment by Chinmaygoyal** [comment]
Can I work on this issue?

**Comment by bojidar-bg** [comment]
@Chinmaygoyal No need to "claim" it -- just make a PR :smiley:
