### ISSUE TITLE
Slider component don't work well when together label within hboxcontainer.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#31923]
**Godot version:**
3.1.1

**OS/device including version:**
mac 10.14.4

**Issue description:**
I want add a label instruction before label. But when I put them in HBoxContainer. It size very small.

**Steps to reproduce:**
create a HBoxContainer
add a Label
add a Slider
resize the Slider component.
preview those.

![Snip20190903_66](https://user-images.githubusercontent.com/1890538/64156352-2e954a80-ce67-11e9-87c1-7a67b6f385a3.png)

![Snip20190903_67](https://user-images.githubusercontent.com/1890538/64156364-3359fe80-ce67-11e9-9d77-2586592effb6.png)

**Comment by volzhs** [comment]
set min width of slider

**Comment by groud** [comment]
Did you put the horizontal expand flag to true in the slider ? If not, that's an expected behavior.

**Comment by zszen** [comment]
@volzhs It works. Thanks
