### ISSUE TITLE
Feature Request: Bounties

### ISSUE THREAD

**Issue by RUSshy** [godotengine/godot#31928]
Hi

I just had this idea, many open source projects offers the ability to pay people for fixing bugs or implementing user requested features

How it could work:

User  post issue X

He has choice:

- Do nothing, and hope someone fix/solve it
- Create a bounty for N$, more people can add to the bounty, then if someone come with a valid PR, he can claim the bounty

**Comment by Calinou** [comment]
Duplicate of #3792.
