### ISSUE TITLE
Regression: The Remote view no longer navigates to the inspected Node

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#31929]
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/64179408-6a2e1580-ce63-11e9-959c-067234b5914f.png)

**OS/device including version:**
Windows 10 64

**Issue description:**
The Remote view stopped navigating to and highlighting the inspected Node during game runtime, for instance when clicking on a variable containing a reference to said node

**Steps to reproduce:**
Create a scene. Add two child nodes. Store nodes in variables using
```
onready var one = $Node1
onready var two = $Node2
```
Run. Select scene's top node in the Remote scene tree view. Click on one of the ID fields:
![image](https://user-images.githubusercontent.com/7307968/64180610-5b486280-ce65-11e9-8c48-78609d98bfee.png)
The inspector shows the referenced node, but the scene tree dock no longer navigates to it and highlights it (I think it did in Godot version 2.x).

**Comment by sparkart** [comment]
It's a regression from #23270
Tested by reverting the code and it resolves the issue. Not sure why.
