### ISSUE TITLE
GLES2: 3d renders all objects black

### ISSUE THREAD

**Issue by NeoSpark314** [godotengine/godot#31922]
**Godot version:**

Current master: 4c169352a61fc97eff65867017910c94a6dbfde3

**OS/device including version:**
Windows 10 / Nvidia

**Issue description:**

Using GLES2 renderer in 3d all objects are rendered black (including the grid and handles)
![image](https://user-images.githubusercontent.com/1610621/64153271-cb87c180-ce2e-11e9-9186-e2d39e05e806.png)

**Steps to reproduce:**
Create an empty gles2 project.

**Minimal reproduction project:**

[gles2_black_issue.zip](https://github.com/godotengine/godot/files/3568331/gles2_black_issue.zip)

**Comment by akien-mga** [comment]
Can you enable the system console (Editor menu) and paste any error reported?

**Comment by NeoSpark314** [comment]
Yes; but I think there is no error reported:

![image](https://user-images.githubusercontent.com/1610621/64155747-b6616180-ce33-11e9-9414-1d86c48af7bb.png)

**Comment by clayjohn** [comment]
Looks to be related to https://github.com/godotengine/godot/issues/31019

Delete the *.glsl.gen files in drivers/gles2/shaders and then rebuild. This is likely caused by shaders not rebuilding when you rebuilt from master.

**Comment by NeoSpark314** [comment]
yes; this was the issue here; Thx a lot and sorry for not seeing this.

**Comment by clayjohn** [comment]
No problem! It would be hard for you to know about that specific issue. :)

**Comment by BaielComAcentoAgudo** [comment]
How i find these files?

**Comment by Calinou** [comment]
@BaielComAcentoAgudo clayjohn's advice targeted to people compiling Godot from source. If you've downloaded a Godot binary, then you're not compiling Godot from source.

There's already a bug report about meshes turning black on old AMD/Intel graphics cards: https://github.com/godotengine/godot/issues/30330
