### ISSUE TITLE
Timer error spam in editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31936]
**Godot version:**
750f8d4

**Issue description:**
After #31844 was merged, this spams in the console on editor startup and when running scene:
```
ERROR: Timer was not added to the SceneTree!
   At: scene\main\timer.cpp:111
```
Look like editor used Timers that were started outside tree.

**Comment by 2shady4u** [comment]
Hello!
It's a meh! The author of the PR that causes this!
No idea why though 🤔 

I'll look into it

**Comment by 2shady4u** [comment]
![Capture](https://user-images.githubusercontent.com/42484461/64213049-cc126d80-ceab-11e9-8111-27c686382d25.PNG)

Tried to add these wayward Timers to the tree, but this crashes the editor... Seems that the tree doesn't exist yet unfortunately

**Comment by KoBeWi** [comment]
@2shady4u If the node is not inside tree, you obviously can't use `get_tree()`. This method doesn't access some global SceneTree singleton.

btw, you can use `print_line` instead of `cout`.

**Comment by sparkart** [comment]
It's probably a hidden bug which is revealed with the PR. 

> ![Capture](https://user-images.githubusercontent.com/42484461/64213049-cc126d80-ceab-11e9-8111-27c686382d25.PNG)
> 
> Tried to add these wayward Timers to the tree, but this crashes the editor... Seems that the tree doesn't exist yet unfortunately (or something equally problematic)

Easiest thing to do is set a breakpoint at Timer::start() and run the editor in debug mode. Then trace the call stack to see what called it.

**Comment by qarmin** [comment]
This happens only in TextEdit::cursor_set_blink_enabled
![Screenshot_20190904_103035](https://user-images.githubusercontent.com/41945903/64238972-a4e58b80-ceff-11e9-9f23-e06f7011686e.png)
![Screenshot_20190904_102942](https://user-images.githubusercontent.com/41945903/64238976-a747e580-ceff-11e9-9b6d-94a1c689c07c.png)

**Comment by 2shady4u** [comment]
@qarmin but both these caret_blink_timers are added to the tree? So how can they be the cause of this?

![Capture](https://user-images.githubusercontent.com/42484461/64243716-1b868700-cf08-11e9-8fa7-81f08212a7be.PNG)

**Comment by volzhs** [comment]
actually `add_child()` does not mean `added to scene tree`, it just adds it to a another node.
maybe, its parent is not added to tree yet.

**Comment by pouleyKetchoupp** [comment]
`TextEdit` and `LineEdit` start the blinking timer before entering the scene tree. Also, these timers are running even when the controls are not in focus, which is hundreds of them in the editor.
I'm working on a fix to make them run only when needed.
