### ISSUE TITLE
Add PackedScene.Instance<T>() for C#

### ISSUE THREAD

**Issue by DagobertDev** [godotengine/godot#31933]
Having a generic Instance<T>() (and maybe InstanceOrNull<T>()) function similar to the generic GetNode<T>() functions would be super helpful.

**Comment by KellyThomas** [comment]
Last time this was suggested there was some concern that it would encourage code that left orphan nodes behind as a memory leak.

The conversation was over at  #20600

**Comment by neikeq** [comment]
That's right. `Instance()` returns a node that could be leaked if not managed properly, either by manually freeing it or by adding it as a child of another node and letting the parent take care of it.
Adding a generic version of this method encourages code like `var mesh = scene.Instance<MeshInstance>("...").Mesh`, which would leak the `MeshInstance` node.
Maybe we should have a `Node.InstanceChild(PackedScene) -> Node` method (and a generic version) as a safer way for the cases where you want to add it as a child right after instancing.

**Comment by DagobertDev** [comment]
I was actually going to use it in a way that leaks memory, so thanks for having that discussion.
I still believe that a generic Instance() would be good, even if only for consistency with GetNode, but i understand the concern.
Node.InstanceAsChild would be very helpful.

Should i close this and reopen at [proposals](https://github.com/godotengine/godot-proposals)? Maybe even two proposals, one for Instance and one for InstanceAsChild, the second one probably doesnt need much discussion and could be used for GDScript too.

**Comment by neikeq** [comment]
I haven't catched yet with this new way of opening proposals. I think that's the right path, but just in case I'll ping @akien-mga

**Comment by akien-mga** [comment]
Haven't caught up yet either as people started using it when I was in holidays ;)
But yeah, it would make sense to move to godot-proposals for further discussion.

**Comment by mhilbrunner** [comment]
Yeah, this should move to proposals. Closing :)
