### ISSUE TITLE
Autocomplete for change_scene() uses wrong icon

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#31941]
**Godot version:**

750f8d4926edb14269d9f6a117c5a9fd4765373

**OS/device including version:**

ArcoLinux

**Issue description:**

![image](https://user-images.githubusercontent.com/28724859/64208970-fe4cac80-ce64-11e9-9926-d40630cfde52.png)

Shows a function icon, should be a path icon I assume

**Comment by HolonProduction** [comment]
Does not apply to v4.3.stable.flathub [77dcf97d8]
So this should either be closed or moved to the 3.x milestone
