### ISSUE TITLE
Inspector shows sub-resources from unselected objects

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#31945]
**Godot version:**
75cbcb5

**Issue description:**
The inspector will show sub-resources for objects that are not selected anymore if switching scenes:
![Screenshot_20190904_000410](https://user-images.githubusercontent.com/30739239/64223172-5b2a8000-cec2-11e9-8e2a-e6b5f66129c6.png)

It will also still show objects as being selected even if it's not the case. Like when clicking in a empty space in the scene dock:
![Screenshot_20190904_000251](https://user-images.githubusercontent.com/30739239/64223177-5e257080-cec2-11e9-8be0-1cf8b113c9f3.png)

**Steps to reproduce:**
Select a node that has a sub-resource (e.g. a script), then create another scene. If you check for sub-resources, you will see that the script will still be listed

**Comment by YeldhamDev** [comment]
Sub-resources are still being shown while unselected.

**Comment by sparkart** [comment]
What do you mean by sub-resources?

**Comment by sparkart** [comment]
Sorry, I didn't know that it could be clicked on.... I guess your first picture makes more sense to me.
