### ISSUE TITLE
Physics process can't be disabled with set_physics_process(false) before _ready().

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#31946]
**Godot version:**

75cbcb596

**OS/device including version:**

Win10 64-bit

**Issue description:**

Physics processing is turned on by default when the function is defined in GDScript, and it has to be manually disabled.  This works fine, only during and after `_ready()`, it can't be set earlier than that.

It's unclear if this is a bug or undocumented behavior.

https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-physics-process

Note - Same is true of `_process()`.

**Steps to reproduce:**

The following code provides an example of the failure to flag processing off.

```
extends Node2D

func _init():
	set_physics_process(false)

func _enter_tree():
	set_physics_process(false)
	
func _physics_process(delta):
	print(get_tree().get_frame())

```

**Minimal reproduction project:**

**Comment by TheFlamyy** [comment]
I wouldn't necessarily say it's a bug. But you should be able to change the processing behaviour anytime - in my opinion.

The code affecting this behaviour should be the following:
https://github.com/godotengine/godot/blob/b679f622d8e66dbba8e15ec0a222cc6ad1827e80/scene/main/node.cpp#L141-L147

One concern arises and it's "how does the engine know if you manually set the processing to be false". Currently all nodes default to disabled processing unless they are "ready".

**Comment by ArdaE** [comment]
The documentation of `set_physics_process` (and `set_process`) already states "_Any calls to this before_ __ready will be ignored_". The version you've linked and even older versions of the documentation all have this warning.

So this looks like the intended behaviour. I wouldn't treat it as a bug.

**Comment by avencherus** [comment]
@TheFlamyy Yes, hard to consider it a bug.  Just an odd implementation restriction.
@ArdaE A good point.  I'm moving it to a proposal.  https://github.com/godotengine/godot-proposals/issues/1008

Though the issue is that documentation doesn't really alleviate the awkwardness of this one.  I don't think most have the habit of checking and rechecking the docs on every minor setter/getter on the off chance it has very specific limitations like this.  I had found it from inspecting the code, and until you mentioned it, had completely missed it was documented since this behavior was last changed.
