### ISSUE TITLE
Custom draw function only updates when scene is re-opened

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#3194]
I have a custom draw function on a node to draw a circle but it doesn't show in the editor properly unless I reopen the scene.

Here is my script which is attached to a `Node2D`. As you can see its nothing special. However I think this may be a bug I can't find anything on it.
```
tool
extends Node2D

export(float) var radius
export(Color) var color

func _process(delta):
    update()

func _ready():
    set_process(true)

func _draw():
	draw_circle(Vector2(), radius, color)
```

Possibly I am missing a line of code telling it to update in the editor? I'm at a loss at the moment and would appreciate any help. Thank you so much.

**Comment by kubecz3k** [comment]
It should update automatically if you click on this node in the "Scene" tab.

**Comment by reduz** [comment]
_draw function is only available on CanvaItem and inheritance, you should
have got an error that the update() method does not exist..

**Comment by volzhs** [comment]
Node2D inherits CanvasItem AFAIK.

**Comment by reduz** [comment]
oh right, it's Node2D

**Comment by kubecz3k** [comment]
I'm able to confirm the bug, also observed other strange behaviour: when deleting script from the node the exported variables are still there, even after scene reopen, this probably deserves to get it's own issue so I will open one.
quick vid for now: https://youtu.be/vPn6rJRO9rk

**Comment by kubecz3k** [comment]
Another thing: Right after attaching script to the node there is no visible exported vars in the editor. 
Reopening the scene doesn't help, only restarting the editor helps:
![exportvalandtools](https://cloud.githubusercontent.com/assets/6129594/12074418/0632e80c-b153-11e5-9a71-562fc62f71e4.gif)
Observed in df5fa62ab955437f05bfd7acdf6ed61d6d9c827e commit

**Comment by volzhs** [comment]
I did restart editor all the time for @kubecz3k issue.

**Comment by jedStevens** [comment]
After playing around a bit more, it turns out the scene doesn't need to be reopened but toggling the visibility of the desired object also updates the draw. I find this quite helpful if anyone else is having this issue.

Toggling the visibility of the root node also updates to the current draw function of each object in the scene.

**Comment by hetdegon** [comment]
I have this issue as well. I used what @jedStevens does to work around it, but it'd be nice if it updated automatically. Changing tabs also updates the draw, by the way.

**Comment by reduz** [comment]
This is expected with tool nodes and it can't be fixed. What it needs to be added is simply an option to reload the script.

**Comment by vnen** [comment]
If it's possible to reload the script with an option, isn't it also possible to reload it automatically on certain conditions?

**Comment by reduz** [comment]
The problem is that reloading it will make the internal state of the script
disappear. Exported variables will likely to be kept, but instance
variables will be lost.

**Comment by neikeq** [comment]
Reloading of `tool` scripts may be implemented soon. That may fix this issue.

**Comment by akien-mga** [comment]
What's the status on this issue now that tool script reloading was implemented?

**Comment by reduz** [comment]
tool reloading was still not doing it right for this case, just fixed it.
