### ISSUE TITLE
debian the problem run game version GLIBC_2.29 not found

### ISSUE THREAD

**Issue by ilyafuu** [godotengine/godot#31950]
**Godot version:**
youtube godot engine 3.1

**OS/device including version:**
debian 10

**Issue description:**
users probably uses ubuntu 19.04 godot engine Linux export through debian launch impossible due to version GLIBC_2.29

download via youtube file link after Linux it is impossible to start because of `libc6` debian, I believe 2.28-10 you need version GLIBC_2.29 there is a problem

https://www.youtube.com/watch?time_continue=42&v=jTmppCifnYE

Terminal
```
XXXXXX:~/Downloads/bw_game_lin64$ ./afg.x86_64 
./afg.x86_64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./afg.x86_64)
XXXXXX:~/Downloads/bw_game_lin64$ sudo apt install -t testing libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.28-10).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
https://packages.debian.org/en/bullseye/libc6 (debian 10)
https://packages.ubuntu.com/disco/libc6 (ubuntu 19.04)

**Steps to reproduce:**

**Minimal reproduction project:**
https://danilw.itch.io/particle-game-demo (Linux x64 zip)

**Comment by akien-mga** [comment]
That's not a Godot issue, the same would happen with any self compiled Linux binary from a too recent distro.

You should report this to the Dev of that demo. Official Godot binaries are built on Ubuntu 14.04 and don't have this compat issue.
