### ISSUE TITLE
Error exporting on android in 2.0 Alpha

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#3198]
I get this error and then it force close the app, it runs on pc just fine.
error opening cache file /data/data/org.godotengine.game/cache/com.android.opengl.shaders_cache: Permission denied (13)

**Comment by akien-mga** [comment]
Do you have templates that match your godot version (commit)?

**Comment by mohaalak** [comment]
yes I have the correct template version , android export is unstable , it force close sometimes, in some scene it just show a blank screen with camera( in 3d). 
for finding out that what's a problem I remove nodes from scenes and export step by step.one problem is that I preload some scenes in my script but I have that scene instanced in editor too, when I remove the instanced scene in editor, export was good to go.
another problem was I have a 3d scene with a spaital a camera and the robotrigged.xml from 3dplatformer it force closes on android. but if I remove the robotrigged instance it export, if I set the main scene the robotrigged it export. 

,
1-02 14:12:17.488 31143-31143/? I/DEBUG:     #00 pc 00aa64b4  /data/app/com.ratagames.tirandaz-1/lib/arm/libgodot_android.so (StringName::StringName(StringName const&)+64)
01-02 14:12:17.488 31143-31143/? I/DEBUG:     #01 pc 006dd050  /data/app/com.ratagames.tirandaz-1/lib/arm/libgodot_android.so (PackedScene::instance(bool) const+356)
01-02 14:12:17.488 31143-31143/? I/DEBUG:     #02 pc 00089ebc  /data/app/com.ratagames.tirandaz-1/lib/arm/libgodot_android.so (Main::start()+2040)
01-02 14:12:17.488 31143-31143/? I/DEBUG:     #03 pc 00068da0  /data/app/com.ratagames.tirandaz-1/lib/arm/libgodot_android.so (Java_com_android_godot_GodotLib_step+2496)
01-02 14:12:18.083 2998-8757/? W/ActivityManager:   Force finishing activity com.ratagames.tirandaz/com.android.godot.Godot
,

**Comment by mohaalak** [comment]
just open the platform 3d from demo and then mess with enviroment and gridmap a little then save export to android it will give you  force close:(:(

**Comment by mohaalak** [comment]
ok I got what's wrong you cannot instance another scene in 2.0 alpha android. I did not check the current repository but that's wrong . @akien-mga can you confirm this?

**Comment by mohaalak** [comment]
this is correct in head repo , I close it now
