### ISSUE TITLE
Node2D look_at expects global coordinates

### ISSUE THREAD

**Issue by Lakorta** [godotengine/godot#31982]
**Godot version:**
3.1.1

**OS/device including version:**
Linux

**Issue description:**
look_at(Vector2 point) expects global coordinates. The function converts the supplied Vector to local coordinates. If the coordinates are already local (e.g. due to being from the same parent) this will cause an offset (if the parent has an offset, see sample below). look_at should either expect the user to make the conversion or note in the docs that it expects global coordinates.

**Steps to reproduce:**
Create a new project with a Control as it's root node and add the following script:

`
extends Control

var goal = Sprite.new()
var player = Sprite.new()

var reached = false

func _ready():
	set_anchor_and_margin(MARGIN_TOP, 0, 50)
	
	add_child(goal)
	goal.texture = load("res://icon.png")
	goal.position = Vector2(200, 200)
	
	add_child(player)
	player.texture = load("res://icon.png")

func _process(delta):
	if(!reached):
		player.look_at(goal.position)
		
		if(player.position.distance_to(goal.position) > delta * 100):
			player.move_local_x(delta * 100)
		else:
			reached = true
			print("yay")
`
The player Sprite will miss the goal Sprite. If the anchor and margin line is removed the player will be able to reach the goal.

**Comment by LikeLakers2** [comment]
Throwing my opinion into the ring, I feel that noting it takes global coordinates is the better option here, as I expect `look_at()` will be used in reference to another (likely non-sibling) node such as the player. That way, users don't have to go to the effort of converting another sprite's global position using `Node2D.to_local()` every time.

Alternatively, perhaps we could have a `local_coordinates` parameter to skip converting the coordinates to local and assume the passed coordinates are already local.
