### ISSUE TITLE
We now have two separate code thumbnails

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#31991]
**Godot version:**
e205cbb
**Issue description:**
Is there any reason to not use one unified renderer for both the FileSystem tab and the code minimap?
![image](https://user-images.githubusercontent.com/28286961/64363866-e8c8b580-d011-11e9-8203-88a8c4f6fe6e.png)

**Comment by Zylann** [comment]
This is not the same thing at all. The minimap is rendered to screen on the fly using `VisualServer` drawing commands. The thumbnail in the filesystem dock is generated on the CPU to obtain an image file. 
I eventually agree the minimap could be improved to look the same as the thumbnail, but there is no point trying to make these two systems as one.

**Comment by Jummit** [comment]
Gotcha. That's what I wanted to know. In my opinion the FileSystem one could use a little more colorful syntax highlighting.
