### ISSUE TITLE
Code completion not working on specific project after setting a custom GUI theme in "Project settings"

### ISSUE THREAD

**Issue by Scemenzo** [godotengine/godot#31992]
**Godot version:**
3.1.1 stable

**OS/device including version:**
Windows 10, Arch Linux

**Issue description:**
Code completion has faulty behavior after setting the custom theme in `Project settings -> Gui -> Theme -> Custom`.
While writing a variable or a function name, a tiny segment appears on the bottom-left side of the text cursor, meaning that the graphical box that should contain the list of suggestions for the completion should be populated instead of being empty.
I've seen this on any .gd script of the specific project for which the setting has been changed (don't know the behavior for other languages).

**Steps to reproduce:**
1. Start a new project
2. Create theme resource
3. Assign the custom theme on `Project settings -> Gui -> Theme -> Custom`
4. Save and restart the program
5. From now on, code completion fails in populating the suggestion list

Thanks to @fuha18 on the issue #16257 for finding out the cause

**Comment by bojidar-bg** [comment]
Potentially fixed by #30351?

**Comment by Scemenzo** [comment]
@bojidar-bg it seems the exact same issue.
I've just noticed that another consequence of this issue was a broken layout for the color selector menu, so this leads more to the "broken view" scenario, instead of the non-populated list.

Thanks a lot for everything you do.
