### ISSUE TITLE
Projects got lost in Projectlist.

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#3199]
Projects are not displayed in the project list anymore. Seems to be related with icon set in the engine.cfg

**Comment by kubecz3k** [comment]
@ndee85 on which commit did you observed this? I have tested couple of things on almost newest df5fa62ab955437f05bfd7acdf6ed61d6d9c827e commit and I can see the projects...

**Comment by ndee85** [comment]
For me it was since 0ed864d876347841d60797773a37c0b2f235c85c
But I don't know if it was before already. I talked to reduz already and he asked me to create that issue. He seems to know what this is all about.

**Comment by ndee85** [comment]
One thing I would like to add. There seems to be some conflicts between the engine.cfg and the project settings in general. I got my project running by deleting a few lines in the editor.cfg. But after I reset a few project information in the project settings they still don't get showed. For Example the project name always stays "unamed project" and the icon is also always the default one. Even if I set it in the project settings.

**Comment by vnen** [comment]
@ndee85 Only the projects are gone or you lost the whole editor settings? If it's everything, then this is related to the problem that you lose the settings when updating the editor in some cases: #1689. If you can't import projects anymore, then it's a different issue.

The "Unamed project" issue was already reported in #3178.

**Comment by ndee85** [comment]
Nono.. I didn't lose the editor settings. Just the projects are gone. Some are shown. It is somehow related to the engine.cfg and the new projects settings that reduz reworked. I think he will know what to do. If needed, I can send you my project Juan.

**Comment by reduz** [comment]
This should be fixed now too
