### ISSUE TITLE
how can i build an aar for android studio?

### ISSUE THREAD

**Issue by jaccen** [godotengine/godot#32005]
i flow this step：
1、scons platform=android target=release android_arch=armv7
got “platform/android/java/libs/release/armeabi-v7a/libc++_shared.so"
"platform/android/java/libs/release/armeabi-v7a/libgodot_android.so",
2、then  ./gradlew build
and got nothing  in  platform/android/java/

how can i get an aar about godot engine。
i want to use this in another android project。3ks

**Comment by groud** [comment]
This is not supported yet, see #26469. But anyway, this is not the place to ask questions about how to use the engine, but to report bugs. Please use the other [community channels](https://godotengine.org/community) to ask questions.
