### ISSUE TITLE
Better export for HTML5

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#32006]
I put this request in the request Github page but it was rejected, so I put here because I don't know where else I have to ask this. I hope this could be the right place.
I'm a game developer and I'm developing HTML5 games, but the Godot HTML5 export template is not the best... We have no compatibility with Safari browser and there are thousands of problems, particles don't work properly, you can't use audio in loop and the performance of the exported game is really worst.
The result for me is simply moving to another game engine for HTML5 games, but there aren't engine so flexible and with fast development as Godot, so I'm wondering if could be better integrated the HTML5 export.
I have investigated a lot on HTML5 game engine and there is no one that is at least decent, the only way to create a game is using frameworks like Pixi.js or similar, but the development time increases a lot using that.

So after that, I guess that the games exported with HTML5 are full of bugs and incompatibility, there is a way to fix this?

P.S: if I want to have a look to create this template export what I have to do? There is some documentation about creating an export for Godot?

**Comment by Zireael07** [comment]
Same here as over on the other repo, there is a issue template you're expected to fill out!

And yes, I suppose this is the correct place for the request since it sounds more like a bug fix than an engine proposal.

**Comment by groud** [comment]
Sorry, but once again here the issue your are providing is pointless. Just saying "there are bugs, what should I do" is not helping anyone.
For each bug you should first check if there is already an issue opened about it, and if not, open a specific and precise issue describing the bug. Otherwise your issue is going to be closed.
