### ISSUE TITLE
3D Rigidbody never sleeps if bounce >= 0.39

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3200]
When you create 3d RigidBody with bounce >= 0.39 then it will never sleep (below it sleeps correctly, default mass, sphere collider, with radius set to 0.2). I tested this in df5fa62ab955437f05bfd7acdf6ed61d6d9c827e commit but I have feeling that this bug is a lot more old.

**Comment by reduz** [comment]
I wonder how other physics engines fix this.. While Godot 2D physics engine is really good and modern, Godot 3D physics engine is really old and the techniques it uses are a little obsolete (most 3d physics engines now use jacobi constraints and an unified LCP solver..).

**Comment by reduz** [comment]
moving to 3.1.. unless bullet branch really works

**Comment by icnikerazah** [comment]
same issue in 2d
![untitled](https://user-images.githubusercontent.com/33985414/35200712-c434b64e-ff23-11e7-88eb-8211dace5907.gif)

**Comment by kubecz3k** [comment]
Tested in ff59c562f745de957e8395fc02af1e5d7377a302, it's fixed (with bullet).

**Comment by kubecz3k** [comment]
@icnikerazah would be the best if you could open new issue for 2D

**Comment by icnikerazah** [comment]
@kubecz3k I'm sick of opening a title, 2 year problems still going on.

**Comment by kubecz3k** [comment]
@icnikerazah what do you mean? You have this problem for 2 years in 2d? No one tested this in 2D as far as I remember, you are the first one (12h ago) and this deserves it's own issue (2D and 3D physics are distinct engines)

**Comment by icnikerazah** [comment]
ok sorry.
