### ISSUE TITLE
Lower level Subscenes are not refreshed automatically in parent scenes

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3201]
This issue is fresh continuation of https://github.com/godotengine/godot/issues/2307 topic. 

Current status:
 * Issue it's partially addressed since changes on the first level seems to be refreshed in parent scenes automatically. 
 * For lower level changes we still need to close and reopen parent scenes. 

_(I'm not 100% sure what milestone should be, for now setting 2.0 since this is milestone of original issue.)_

**Comment by reduz** [comment]
Is this the only issue left regarding automatically refreshing changed scenes?

**Comment by kubecz3k** [comment]
@reduz Somewhat related bug would be this one: https://github.com/godotengine/godot/issues/3127

**Comment by reduz** [comment]
could I get a test project for this? like 3 scenes with different inheritance and what do I have to change for it to work

**Comment by kubecz3k** [comment]
@reduz sure, here is a sample: https://dl.dropboxusercontent.com/u/168251/godot/bugsquad/AutorefreshScenesSample.7z
here is a vid that demonstrates how to use this sample to get the bug: https://youtu.be/sARtaENFTl4
This sample is also valid for https://github.com/godotengine/godot/issues/3127 but more on this inside https://github.com/godotengine/godot/issues/3127

**Comment by akien-mga** [comment]
I can confirm that the behaviour shown in the video is exactly what I saw and mentioned in https://github.com/godotengine/godot/issues/2307#issuecomment-165066022 back then.
(i.e. Scenes A -> B -> C, change in C is properly shown in B but not in A)
