### ISSUE TITLE
Scene resource importer animation filter/optimizer only works with root-level nodes named AnimationPlayer

### ISSUE THREAD

**Issue by Klowner** [godotengine/godot#32014]
**Godot version:** 3.1.1 (also present in `master@4ee8ecd3ef`)

**OS/device including version:** Arch Linux (kernel 5.2.9)

**Issue description:** I was trying to understand how the Scene importer's animation track filtering works and realized that the `.escn` exported from Blender using the Godot Blender Exporter (https://github.com/godotengine/godot-blender-exporter) places the `AnimationPlayer` as a child of the animated node, rather than the root node of the imported scene.

The issue is that the scene importer only looks for a node named `AnimationPlayer` in the root of the scene, this leads to optimization and filtering silently not taking place.

**Steps to reproduce:**
 1. Throw a `print_line()` or set a breakpoint in `_filter_tracks()` in `editor/import/resource_importer_scene.cpp` after the `has_node(String("AnimationPlayer"))` check.
 2. export a scene with animations from Blender using the godot-blender-exporter
 3. import the scene
 4. observe that the breakpoint/print_line is never reached

**Minimal reproduction project:** :man_shrugging:

**Comment by Klowner** [comment]
I'm a bit new to Godot's architecture, but I'd be happy to try to fix this. My immediate thought was to recursively scan the imported Scene for AnimationPlayer nodes. I was hopeful there was a recursive `Node.find_by_type()`, but it appears one can only search for names?

Any input is appreciated! :wave:

**Comment by akien-mga** [comment]
CC @Jason0214 

@reduz commented:

> AnimationPlayer should go in the scene root, no idea why it is in the child of the animated node

**Comment by Jason0214** [comment]
Thanks @akien-mga ,  

In escn-exporter, each AnimationPlayer put in the subtree contains only animation of nodes in that subtree, so that each they can be played independently. So I suppose the exporter should create only one AnimationPlayer in root and make each independent animation as different AnimationResources, right?

**Comment by reduz** [comment]
Yes, there should be one AnimationPlayer node in the root with all the actions, it should work the same as in better collada exporter.

**Comment by akien-mga** [comment]
Moved to godotengine/godot-blender-exporter#281.
