### ISSUE TITLE
GLES3 renderer not handling transparency in some edge cases

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#32016]
**Godot version:**
3.2 alpha
**OS/device including version:**
Fedora and others are effected too
Hardware: R9 390X
**Issue description:**
GLES 3 Result - Transparency not working / is black biased when it overlaps another object:
![image](https://user-images.githubusercontent.com/748770/64443424-be3a3380-d0c9-11e9-9562-a85abe5c8963.png)

GLES 2 Result - Transparency working as expected
![image](https://user-images.githubusercontent.com/748770/64443963-f8580500-d0ca-11e9-9ca4-2de8648b7221.png)

**Steps to reproduce:**
1. Best way to get the same results is to load master godot.
2. download fbx from here: https://developer.nvidia.com/orca/amazon-lumberyard-bistro
3. open Bistro_Exterior.fbx

Please note: FBX Importer currently sets the following properties on the transparent materials:
```cpp
// anything transparent must be culled
if (image_data.raw_image->detect_alpha() != Image::ALPHA_NONE) {
    mat->set_feature(SpatialMaterial::FEATURE_TRANSPARENT, true);
    mat->set_depth_draw_mode(SpatialMaterial::DepthDrawMode::DEPTH_DRAW_ALPHA_OPAQUE_PREPASS);
    mat->set_cull_mode(SpatialMaterial::CULL_DISABLED); // since you can see both sides in transparent mode
}
```

**Minimal reproduction project:**
as described above, this is the only way I can reproduce the issue currently have tried creating the same setting in a new scene with same materials but no luck.

**Comment by RevoluPowered** [comment]
Updated with more information to help identify the problem.

**Comment by RevoluPowered** [comment]
Also black background only appears when at certain angles relative to the transparency.

**Comment by fire** [comment]
Could this be related to http://the-witness.net/news/2010/09/computing-alpha-mipmaps/ ?

**Comment by RevoluPowered** [comment]
I don't know to be honest, right now I believe the problem is just in the glBlend related code, but need to look a bit deeper into the problem as the GLES2 renderer does this really well, and I want to know what the differences are

**Comment by akien-mga** [comment]
Took me a while to notice what the issue is on the screenshot, a quick description would have been good :)

For anyone with bad eyes like me, there are blending issues around the foliage and balcony fence.

**Comment by clayjohn** [comment]
@RevoluPowered Are those particular elements (balcony fence and foliage) using alpha scissor as well? I think it may be a matter of alpha scissor conflicting with the opaque pre-pass.

**Comment by RevoluPowered** [comment]
@akien-mga Apologies, for clarification yeah it's the window panes, and foliage.

@clayjohn The only options enabled on the materials is transparency but alpha scissor is off currently, but I am having this with normal transparent textures and only in GLES3 not in GLES2.

I did testing with alpha scissor but it's not functional for glass so really need the GLES3 issue fixed.

When I get a chance I'll record a quick video of this to show settings and various setup so that you can clearly see the issue with all the information.

Thanks both

**Comment by RevoluPowered** [comment]
Sorry just realized above the code includes an example of what options are set on the material.

The minimum reproduction project should work fine in godot master by just dragging in the fbx

**Comment by MilosLukic** [comment]
**Godot version:**
3.2 alpha 1
**OS/device including version:**
Win 10
**Hardware**: Nvidia GTX 1050M

I have a similar issue, overlapping transparent images have black areas. It works perfectly well in 3.1.1 and it becomes black in 3.2. Here is an image and a sample project.

![tree_ugly](https://user-images.githubusercontent.com/8350874/66342043-cd223900-e948-11e9-9ffe-d854f5184f5a.png)

[sample_project.zip](https://github.com/godotengine/godot/files/3699094/sample_project.zip)
