### ISSUE TITLE
variable resets itself to 0 after being set [GDNative] [c++]

### ISSUE THREAD

**Issue by LuigiVanacore** [godotengine/godot#32026]
**Godot version:**
3.1.1
**OS/device including version:**
windows/windows x64
**Issue description:**
I have a variable Vector2 screenSize in the Player class. It is used to clamp the position of the player so the player can not go outside the borders of the game screen. The variable is inizialized from the class Main, who get a pointer of the child node Player and use the method setScreenSize to set the screenSize to the size of the game screen. The HUD node has a button StartGame. When the player clicks the button HUD send a signal to Main _on_HUD_start_game. When the function _on_HUD_start_game is called, it calls the function start_game in which Main call the funcion setScreenSize of Player class. After that the variable screenSize of Player is correctly setted, but when the program arrives to the _process function of the Player class the screenSize is now setted to 0,0.
 I don't know why it is happening and where it is the problem. 
When I close the debug game screen, the application crash and doesn't close correctly.
**Steps to reproduce:**
Start the editor and start the debug application for the Main Node, then press the start_game button and the Player will not move from its position because the screensize it is setted not correctly to 0,0 and so the clamp function set the position to 0,0. 
**Minimal reproduction project:**
https://github.com/LuigiVanacore/GodotGames

**Comment by LuigiVanacore** [comment]
the editor give me the error:  drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054
when I close the game window

**Comment by LuigiVanacore** [comment]
I tried to add this
 `	register_property<Player, Vector2>("screenSize", &Player::setScreenSize, &Player::getScreenSize, Vector2(400,700));`
to void Player::_register_methods() 
but when I play the game the variable screenSize in the _process method of Player is always 0,0

**Comment by karroffel** [comment]
I just want to note that registering a property does not automatically call the setter. You need to initialize the variables in the constructor or in the `_init` function.

The "default value" is a hint to the editor, it does not actually **set** the default value.

**Comment by rarsp** [comment]
Its not the bug in GDNative but in your code.

you are casting: player = (Player*) this->get_node("Player"); wrongly
It should be:  Object::cast_to<Player>get_node("Player");

**Comment by LuigiVanacore** [comment]
I resolved like this:
	player = Object::cast_to<Player>(this->get_node("Player"));
