### ISSUE TITLE
GridMap error spam everytime I load a specific scene.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#32028]
**Godot version:** 3.1.1 and recent master build.

**OS/device including version:** Linux Mint 19.2 Cinnamon 4.2.4

**Issue description:**
Godot keeps spamming me with an error message related to GridMaps every time I load or run a specific scene in my project, I tried changing my GridMap settings and recreating my MeshLibs, but no matter what I do it does not go away.
![Untitled](https://user-images.githubusercontent.com/781121/64476005-f143fc00-d189-11e9-84bf-3c807281f81a.jpg)

**Steps to reproduce:**
I have no idea, I've not been able to reproduce this with any other GridMap since.

**Minimal reproduction project:**
[gridmap_errors.zip](https://github.com/godotengine/godot/files/3586676/gridmap_errors.zip)

**Comment by nathanwfranke** [comment]
Ubuntu 18.04, Godot 3.1.1 Mono
I am also getting these errors on the Reproduction Project (Although Only in stdout)
![image](https://user-images.githubusercontent.com/14253836/64482123-fec0ac80-d1b0-11e9-9178-50d68576d042.png)
![image](https://user-images.githubusercontent.com/14253836/64482125-02ecca00-d1b1-11e9-97b7-318c020eba21.png)

**Comment by EzraT** [comment]
It looks like this issue has resurfaced, here's a screenshot of the MRP in 3.3.2.
![image](https://user-images.githubusercontent.com/781121/121690120-ba6ce980-cac5-11eb-9154-3a600367eaee.png)
