### ISSUE TITLE
|| acting as an inclusive "through" instead of "OR"

### ISSUE THREAD

**Issue by downhillGames** [godotengine/godot#32024]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Pro
i5 @3.10 Ghz 12 GB RAM
**Issue description:**
|| is acting as an inclusive "through" when working with integer numbers 
**Steps to reproduce:**

Start a new project and just add a node2D and a script attached

    var num
    func _ready():
	    randomize()
	    num = randi()% 10 + 0
	    print (num)
	
	    if (num == 1 || num==10):
		   print("WEIRD RIGHT")
	   pass # Replace with function body.

Output:

** Debug Process Started **
OpenGL 3.0 Renderer: GeForrce GT 740/PCIe/SSE2
4
WEIRD RIGHT

**Comment by downhillGames** [comment]
Sorry, this was my own misunderstanding.

    if (num == 1 || num==10):

will mean 1 OR 10

    if (num == 1 || 10):
 
will mean 1 THROUGH 10

**Comment by Calinou** [comment]
> ```
> if (num == 1 || 10):
> ```
>
> will mean 1 THROUGH 10

If I'm reading it right, it will always evaluate to `true` since `10` is a truthy value.

**Comment by volzhs** [comment]
```gdscript
if num in range(1,10):
```
