### ISSUE TITLE
non working nods

### ISSUE THREAD

**Issue by dijam8** [godotengine/godot#32042]
[platformer 3.zip](https://github.com/godotengine/godot/files/3587677/platformer.3.zip)

**Godot version:**
3.1
**OS/device including version:**
ubuntu 18
**Issue description:**
my area2d in player scene is working but in scene1 when i select it its propritis in the inspector becams red and it no longer working

**Steps to reproduce:**
![Screenshot from 2019-09-07 19-39-38](https://user-images.githubusercontent.com/50689412/64489659-9ecc1380-d24d-11e9-8f1a-bcc98f33708d.png)
![Screenshot from 2019-09-07 19-39-51](https://user-images.githubusercontent.com/50689412/64489661-a25f9a80-d24d-11e9-913a-d326a02bc0b4.png)

**Minimal reproduction project:**

**Comment by star-tek-mb** [comment]
you need to make node editable. or edit scene itself, by not linking it in another scene.

**Comment by dijam8** [comment]
thanks

**Comment by dijam8** [comment]
i make it local

**Comment by groud** [comment]
In any case, that's likely not an engine bugs. Closing.
