### ISSUE TITLE
Can't start godot in archlinux

### ISSUE THREAD

**Issue by swordhorn** [godotengine/godot#32046]
**Godot version:** 

3.1.1-1

**OS/device including version:** 

archlinux

**Issue description:** 

I  ran `yay -S godot` to install godot in archlinux, and the installation seemed no error occured, but I can't open it at all.

After installation, I can create a launch button on my panal, but If I click it, nothing will happen. If I click it one more time, the whole desktop will stuck and I can't move my mouse.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Can you post the output log that you get when starting Godot from a terminal?

**Comment by nealith** [comment]
The 3.1.1 downloaded from the website work well on archlinux.

**Comment by swordhorn** [comment]
> Can you post the output log that you get when starting Godot from a terminal?

I don't know how to start Godot from terminal.

I tried  `godot %f` and `godot -e` , and terminal shows `nvc0_screen_create:1093 - Error allocating PGRAPH context for M2MF: -16` and a blinking cursor.

And this command:  `godot` -> `(just a blinking cursor)` .

**Comment by Zireael07** [comment]
@swordhorn: Does ArchLinux have a graphical file explorer such as Ubuntu's Nautilus? You should have an option in it to open folder in terminal, and there you type 
` ./[yourGodotexecutable's` full name]

**Comment by groud** [comment]
> I don't know how to start Godot from terminal.

You use Archlinux and you don't know how to launch Godot from a terminal O_o ?

I any case, this is likely not a bug with Godot, it runs fine on my own Archlinux installation. 
As it can happen easily on Archlinux, I suspect a badly installed driver, or incompatible hardware, but that out of the scope of Godot's issues. If you need more help, you should instead reach the Archlinux Godot package maintainer, or eventually search on the other community channels if someone had a similar bug.

**Comment by santouits** [comment]
Try running these too in the terminal
``godot -v``
and
``DRI_PRIME=0 godot -v``

**Comment by swordhorn** [comment]
> > I don't know how to start Godot from terminal.
> 
> You use Archlinux and you don't know how to launch Godot from a terminal O_o ?
> 
> I any case, this is likely not a bug with Godot, it runs fine on my own Archlinux installation.
> As it can happen easily on Archlinux, I suspect a badly installed driver, or incompatible hardware, but that out of the scope of Godot's issues. If you need more help, you should instead reach the Archlinux Godot package maintainer, or eventually search on the other community channels if someone had a similar bug.

Thanks for your advice, the problem is about my nvidia driver and I solved it now.

I add `blacklist nouveau ` in `/etc/modprobe.d/blacklist.conf`, as [this page](https://bbs.archlinuxcn.org/viewtopic.php?id=5941) said , then godot run well.

And thanks everyone replying this thread.

I am a newbie in using linux, and this is my first month using arch. Yours reply teach me a lot.

**Comment by groud** [comment]
Happy to know this solved the problem :)

> I am a newbie in using linux, and this is my first month using arch. Yours reply teach me a lot.

Wow, starting learning linux with arch is not the easiest solution, I wish you good luck for that. :)
