### ISSUE TITLE
KinematicBody2D get_floor_velocity() wrong behavior when the moving platform beneath the player has synch_to_physics enabled

### ISSUE THREAD

**Issue by Scemenzo** [godotengine/godot#32059]
**Godot version:**
3.1.1 Stable

**OS/device including version:**
Windows 10, Arch Linux

**Issue description:**
The call to the method get_floor_velocity() of a KinematicBody2D, while standing on a moving KinematicBody2D animated with the AnimationPlayer class and with synch_to_physics enabled, gives inconsistent values.

Here is a print of the values returned by get_floor_velocity() on the kinematic body upon the moving platform every draw() callback with synch_to_physics turn off:
```
(84.001457, -11.999816)
(83.999626, -12.000274)
(83.999626, -11.999816)
(83.999626, -11.999816)
(83.999626, -12.000274)
(84.001457, -11.999816)
```
Here is the same with synch_to_physics turn on:
```
(0, 0)
(168.001083, -24.00009)
(0, 0)
(167.999252, -24.00009)
(0, 0)
(167.999252, -24.00009)
(0, 0)
(168.001083, -24.00009)
```

Now I don't know what changes beneath GDScript and if it is the desired behaviour with the synch_with_physics feature, but it surely seems it postpones one frame velocity calculation to sum it up to the next frame to maintain coherence with the character movement.

This, however, produces an incoherent physics result on the player (the kinematic body that calls get_floor_velocity()).
When the velocity of the moving platform is beneath a certain value, the player on top will slide (like it'd not consider the values returned by the moving platform:
(I'm pushing the right button to stay on the platform)
![slow](https://user-images.githubusercontent.com/12174888/64538285-a60e2280-d31c-11e9-9555-cd981ecc6cc5.gif)

If the velocity is high enough, there is no problem with the overall behaviour of the character:
(I'm pushing no buttons)
![fast](https://user-images.githubusercontent.com/12174888/64538438-e9689100-d31c-11e9-90be-8b229e46c85d.gif)

Without the synch_to_physics enabled, everything is fine at any speed, but there is the well-known problem of the one-frame delay between platform movement and the player's one that I'd like to avoid.

**Steps to reproduce:**
You must have a KinematicBody2D that adds gravitational force,  then adds the value returned by get_floor_velocity() multiplied by the delta factor and then calls move_and_slide (or move_and_slide_with_snap)

**Comment by Scemenzo** [comment]
Searching the Internet I've found a "trick" to get rid of this problem.
The appears that deactivating the "stop_on_slope" boolean value in any move_and_collide method inside the player script will result in a correct behavior on any moving platform.

I still want the possibility to stop the character from sliding down, so I made a variable that changes based on the surface the character is posing on.
Now everything is fine but it's still a "dirty trick". Hope this gets fixed.

**Comment by raphael10241024** [comment]
similar to https://github.com/godotengine/godot/issues/28181

**Comment by Scemenzo** [comment]
> similar to #28181

Thanks but no, it isn't.
I have no problem at all with the behavior of the animated kinematic body for wich sync_to_physics is enabled. It works fine, even in the specific case of magnified view described in the issue you reported.
This problem is related to the kinematic body (sync_to_physics disabled) that interact with the animated one (sync_to_physics enabled).

**Comment by raphael10241024** [comment]
Can you provide a simple test project? it could help to find the reason quickly.

**Comment by Scemenzo** [comment]
> Can you provide a simple test project? it could help to find the reason quickly.

I've put up a minimal set, but now I'm more confused than before. Maybe I'm just totally wrong. I cannot understand and the documentation is not on my side.
[simple test project](https://github.com/godotengine/godot/files/3642461/get_floor_velocity.zip)

Here is what happens:
1. synch_to_physics seems to be fine in both cases (on-off)
2. stop_on_slope = false: the characters stays on top of platform (except when the platform moves upward?!)
    stop_on_slope = true: makes the character slide off the platform (any velocity). The kinematic body will still percieve the floor_velocity if explicitly calling the method, but the character will move at double the speed.

I guess there is something in my more complex project that deal with this mechanic and give me the behavior described originally (so that this bug is turning into that behavior), but now I'm just mentally melted and can't think of anything more about. 
This is the fourth "physics-breaking" bug I find in the engine and the more i go forward on my development process, between lack of documentation and milestones of rewriting the 2d physics in version 4.0, the more I'm thinking about waiting for another release or maybe drop out the engine.

I love all the effort the developers are putting on this awesome engine, but I'm loosing time and my mind on those things.

**Comment by KoBeWi** [comment]
Seems like you are not supposed to use `sync_to_physics` with `move_and_slide`. Tested in 3.2.3 rc6, there's an error saying to read the documentation xd

Closing this, as the described behavior can't be observed anymore.

**Comment by MooSoup** [comment]
> Seems like you are not supposed to use `sync_to_physics` with `move_and_slide`. Tested in 3.2.3 rc6, there's an error saying to read the documentation xd
> 
> Closing this, as the described behavior can't be observed anymore.

but according to documentation, `sync_to_physics` doesn't work with `move_and_slide ` or `move_and_collide` but in my project it doesn't work with `move_and_slide_with_snap`. I don't know if I should report a bug or if it got forgotten to add.
