### ISSUE TITLE
Suggestion: Multiple Scripts

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#3205]
I'm unsure if this has been discussed and dismissed, but I think this engine would benefit from allowing objects to run multiple scripts. As far as I am aware there is no feature for this but correct me if I am wrong.

I feel like this would be a very good way to separate functionality and keep devs from having to create scripts that might combine behaviour they have already written. Like for example, if you want an enemy that has the same AI as the basic enemy but needs some special functionality like enhanced AI for given scenarios, it might help to just add a smaller script containing the extended AI features rather than a longer script containing the basic AI mixed with the enhanced AI. This is not currently my issue and I do realize this problem can be solved by using Godot's current scripting solution, however I feel like this feature would help modulate scripts for better project management.

Let me know what you think,
thanks for reading.

**Comment by reduz** [comment]
just add children nodes and with scripts that have extra behaviors

**Comment by jedStevens** [comment]
Very true.

I apologize I am quite new to this engine and didn't know that would work.

Thank you.

**Comment by reduz** [comment]
No worries! we should make some sort of guide for developers coming from
other engines too, to make this easier

**Comment by kubecz3k** [comment]
@jedStevens Will archive this issue if you don't mind, the discussion can still go on :)
