### ISSUE TITLE
Can't use timer created and held in dictionary

### ISSUE THREAD

**Issue by maksimp04** [godotengine/godot#32060]
functions like: set_wait_time() or set_one_shot() works like they should, but start() don't do anything. Tried set_paused(false) after start() but nothing changed.

**Comment by Calinou** [comment]
Can you upload a minimal reproduction project, please?

**Comment by KoBeWi** [comment]
You need the Timer to be added to the scene tree to work. Simply keeping it in Dictionary is not enough.

**Comment by Calinou** [comment]
See also #31844, which adds an error message if the Timer is started without being added to the tree.

**Comment by groud** [comment]
Please provide an example project.

**Comment by maksimp04** [comment]
KoBeWi says the right things, I should add timer to scene.
