### ISSUE TITLE
Tilemap reduces to about half the number of tiles when it is instantiated in another scene and the program crashes when you open the tilemap.

### ISSUE THREAD

**Issue by GabrielPaes** [godotengine/godot#32069]
**Godot version:**
Godot_v3.1.1-stable_win64
**OS/device including version:**
Windows 10 version 1809 build 17763.678

**Issue description:**
When a Tilemap node is instantiated in another scene, the organization of the map created through the autotile feature is disrupted due to the reduction of the number of tiles, apparently by half.
Also when you close Godot and reopen it, if you click on the tilemap scene the program crashes, you need to first click on the scene the instantiated the tilemap and then on the tilemap scene for it to work. 

**Steps to reproduce:**
1-Create a new Tilemap scene, set cell size to 16x16;
2-Add a new tileset, add image with the tiles, click on "New Autotile";
3-Click and drag on the image, then set the Snap Options step to 16x16;
4-Set the subtitle size to 16x16;
5-Draw the region, the bitmask and add a square collision for each tile;
6-Draw a simple map using the recently created autotile and save the scene;
7-Create a new scene (Node 2D), select it, click on "Instance a scene file as a node" and select the created tilemap scene;
8-See the error.

For the program to crash just close it, reopen it and double click on the tilemap scene
![Error_Tilemap](https://user-images.githubusercontent.com/5392885/64581876-1d19da00-d362-11e9-9a32-112c31d883d8.gif)

**Minimal reproduction project:**
[New_Test.zip](https://github.com/godotengine/godot/files/3593542/New_Test.zip)

**Comment by guilhermefelipecgs** [comment]
Tested on linux with latest build and it's seems this was fixed.

@GabrielPaes Can you test again with the latest build: https://hugo.pro/projects/godot-builds/

**Comment by KoBeWi** [comment]
Yep, it's fixed.
