### ISSUE TITLE
Calling string.StartsWith in C# causes crash on Android

### ISSUE THREAD

**Issue by gattila** [godotengine/godot#32075]
**Godot version:** v3.2.alpha

**OS/device including version:** Android 6.0 Xiaomi Redmi Note 3

**Issue description:** Whenever I tried to use a function from mscorlib, the app crashed on Android.

**Steps to reproduce:**
Here's the script that causes the error:

using Godot;
using System;

public class icon : Sprite
{
  
    public override void _Ready()
    {
        
    }

  public override void _Process(float delta)
    {
    **_var s = "Test";
    if (s.StartsWith("T"))_**
       this.Position = new Vector2(this.Position.x+delta*30, this.Position.y);     
    }
}

_Without the first two lines in the Process function, it works fine._

With this two lines, the application crashed and I found the following line in the logcat:

09-10 14:41:21.669 14154 14171 E mono    :
09-10 14:41:21.669 14154 14171 E mono    : Your mono runtime and class libraries are out of sync.
09-10 14:41:21.669 14154 14171 E mono    : The out of sync library is: .mono/assemblies/Debug/mscorlib.dll
09-10 14:41:21.669 14154 14171 E mono    :
09-10 14:41:21.669 14154 14171 E mono    : When you update one from git you need to update, compile and install
09-10 14:41:21.669 14154 14171 E mono    : the other too.
09-10 14:41:21.669 14154 14171 E mono    : Do not report this as a bug unless you're sure you have updated correctly:
09-10 14:41:21.669 14154 14171 E mono    : you probably have a broken mono install.
09-10 14:41:21.669 14154 14171 E mono    : If you see other errors or faults after this message they are probably related
09-10 14:41:21.669 14154 14171 E mono    : and you need to fix your mono install first.
09-10 14:41:21.670 14154 14171 E mono    :
09-10 14:41:21.670 14154 14171 E mono    : Your mono runtime and class libraries are out of sync.
09-10 14:41:21.670 14154 14171 E mono    : The out of sync library is: .mono/assemblies/Debug/mscorlib.dll
09-10 14:41:21.670 14154 14171 E mono    :
09-10 14:41:21.670 14154 14171 E mono    : When you update one from git you need to update, compile and install

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/3595727/test.zip)

**Comment by Anutrix** [comment]
Seems to be same issue as link below. Something to do with linking.

> This fixed it for me following Xamarin Studio updates on OS X - your mileage may vary!
1. In Xamarin Studio - Clean solution
2. In emulator - Settings -> Apps -> Uninstall "Mono Shared Runtime", "Xamarin.Android API-* Support", "Xamarin.*.SmokeTests",
3. Reboot entire machine (old Windows habit following new software install)
4. Start Xamarin Studio
5. Start emulator
6. Rebuild
7. Debug to emulator

If I had to guess, it was step 2 that got rid of a prior version of the Mono Shared Runtime and resolved the "Your mono runtime and class libraries are out of sync" error.

Src:  https://forums.xamarin.com/discussion/4731/problem-with-release

**Comment by gattila** [comment]
As I see the android apk must run without mono shared runtime, and the real problem is not that the dll was not loaded, but later:

Unhandled Exception:
Nested exception detected.
Original Exception: at System.Globalization.CompareInfo.get_UseManagedCollation () [0x0001d] in <b0dd258eb94b44a48f94659a34d3da02>:0
at System.Globalization.CompareInfo.StartsWith (string,string,System.Globalization.CompareOptions) [0x00000] in <b0dd258eb94b44a48f94659a34d3da02>:0
at System.Globalization.CompareInfo.IsPrefix (string,string,System.Globalization.CompareOptions) [0x00089] in <b0dd258eb94b44a48f94659a34d3da02>:0
at string.StartsWith (string,System.StringComparison) [0x0005a] in <b0dd258eb94b44a48f94659a34d3da02>:0
at string.StartsWith (string) [0x00011] in <b0dd258eb94b44a48f94659a34d3da02>:0

**Comment by gattila** [comment]
Ugly workaround: If I use s.StartsWith("T", **_StringComparison.Ordinal_**), it is Ok. I also tried to set the current culture of the thread manually, but it was not helped.

**Comment by akien-mga** [comment]
I'm pretty sure that this was fixed when we started shipping the `monodroid` BCL with the export templates, so I'll close.

Please comment if you can still reproduce it in 3.2 RC 1 or later and we'll reopen.
