### ISSUE TITLE
HSplitContainer's Margin Right changes itself

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#32076]
**Godot version:**
3.1 stable official x64

**OS/device including version:**
Linux Mint 19.1

**Issue description:**
Second element in HSplitContainer changes it's margin_right value to parent's margin_right against what set in the scene file. If try swap places second element with any other, then new element in second position glitches like this too.

**Steps to reproduce:**
1. Open project.
2. Select a scene in 2D grid.
3. Select an "UndoButton", change it's Margin Right to whatever value.
4. Save scene.
5. Reload project.
6. Select Undo Button again and see the bug.

**Minimal reproduction project:**
http://www.mediafire.com/file/31c1ad4if39zfhq/Margin_Right_Bug_Test.zip/file

**Comment by groud** [comment]
That's expected behavior. Containers override their children margin and anchor values.
I am working on an update that should disable editing margins & anchors when you have a child of a container, to make that more obvious.

**Comment by Teashrock** [comment]
@groud 
Then why it happens only with second element and not all others?

**Comment by groud** [comment]
@Teashrock it depends on the container. I don't know why only one is modified, but generally, you cannot rely on the margins and anchors values of a child of a container.

**Comment by Teashrock** [comment]
@groud 
So, there actually IS a bug, even not exactly which I submitted. Must I make another bug report?

**Comment by groud** [comment]
If the problem is about the children of a container not updating right away, I think that bug was already submitted.

**Comment by Teashrock** [comment]
@groud 
Must be here: https://github.com/godotengine/godot/issues/31813
