### ISSUE TITLE
Error parsing engine.cfg with "." or ":" in a tag

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#3207]
ConfgFile::load - /path/to/engine.cfg:30 error: Expected Identifier

This is caused by trying to load a config file with a '.' in a tag, like 'display.iOS'.  I have verified that removing the tag with a period in it does fix the error.

**Comment by romulox-x** [comment]
This also applies to export.cfg.  [platform:Android] and the like also don't parse correctly, presumably due to the ':'

**Comment by ndee85** [comment]
I think this is also related to my issue #3199
