### ISSUE TITLE
Control anchors are not loaded from the scene file

### ISSUE THREAD

**Issue by puthre** [godotengine/godot#32073]
3.1.2.devel
Ubuntu 18.04

I have the following scene file:
```
[gd_scene format=2]

[node name="Node2D" type="Node2D"]

[node name="CanvasLayer" type="CanvasLayer" parent="."]

[node name="MarginContainer" type="MarginContainer" parent="CanvasLayer"]
anchor_left = 1.0
anchor_right = 1.0
margin_bottom = 100.0
grow_horizontal = 0
rect_min_size = Vector2( 500, 100 )
size_flags_horizontal = 5
size_flags_vertical = 5

[node name="Control" type="Control" parent="CanvasLayer/MarginContainer"]
anchor_left = 1.0
anchor_right = 1.0
margin_bottom = 100.0
grow_horizontal = 0
rect_min_size = Vector2( 100, 50 )

[node name="Node2D" type="Node2D" parent="CanvasLayer/MarginContainer/Control"]

[node name="Label" type="Label" parent="CanvasLayer/MarginContainer/Control/Node2D"]
margin_right = 40.0
margin_bottom = 14.0
text = "something"
```

Load the scene, select "Control", set anchor left 1, anchor right 1, modify margin left to 1 so the control position updates, save the scene. When you load the scene again the anchors are set to 0, the text has a different position.
Just before save:
![Screenshot_2019-09-10_13-32-05](https://user-images.githubusercontent.com/38382/64614924-63f2e880-d3d1-11e9-8d35-1f178bd37526.png)
Just after loading.
![Screenshot_2019-09-10_13-47-17](https://user-images.githubusercontent.com/38382/64614986-86850180-d3d1-11e9-9267-8986166fa98c.png)

**Comment by puthre** [comment]
Also if you change the control rotation after you change the anchors to 1, and save  , when you load, it will not be rotated (or if you run it)
![Screenshot_2019-09-10_14-00-33](https://user-images.githubusercontent.com/38382/64616025-8ede3c00-d3d3-11e9-922c-82bfea006251.png)

**Comment by groud** [comment]
That's expected behavior, children of containers get their anchors and margins overridden by their parent. I am currently working on making this more obvious in the inspector by disabling their edition.
