### ISSUE TITLE
Runtime error: load of value 8199, which is not a valid value for type 'PropertyHint'

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#32089]
**Godot version:**
3.2.alpha.custom_build.24e1039eb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
This is caused by this line
https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/scene/gui/rich_text_label.cpp#L2634

@Eoin-ONeill-Yokai 

**Steps to reproduce**
Just run Godot, to see this errors compile Godot with sanitizers support.

**Comment by Eoin-ONeill-Yokai** [comment]
Thanks for tagging me. Could you try my latest pull request? I have resolved the issue on my end and want to make sure it is working well for you as well.

**Comment by Eoin-ONeill-Yokai** [comment]
This should be closed now since the fix has been merged. @KoBeWi or anyone else who can do that for me.
