### ISSUE TITLE
is_key_pressed event lost on shader compile and execute

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#32084]
**Godot version:**
3.1.1 stable

**OS/device including version:**
Linux Editor and game

**Issue description:**
*Maybe this only Linux bug*. I did not test it on other platform.
(it same like pressed key does not update state on windows focus lost)
launching shader compile(example on game load) for shaders that have long compile time, or long render time, pressing(click) Key during this lag, Key will update stay to pressed, and do not back, key pressed forever(untill user click it again) 
Godot events is_key_pressed is_action_pressed return true

(my real-game project has ~10 sec preloading to compile shaders, if user press any keys during this time, they all keep pressed-state on launch)

**Steps to reproduce:**
*simply* - press key, dont release, change OS Windows focus to other windows, release key, focus Godot windows again, Godot still show that Key pressed.

*shaders*(my example has shader that lag on render(loop 199 times in shader))
launch my example to see (it launch lag on 1 frame only)
in my example you need press key(W) when it show lag text line, click once, and it kepp pressed after lag gone

*shader compile lag*...I can not make small example for it, in my big project with lots of big shaders(long compile, they fast in running) it give me this key-bug

**Minimal reproduction project:**
https://danilw.github.io/godot-utils-and-other/BUG_key_pressed/BUG_key_pressed.zip

**Comment by KoBeWi** [comment]
I can't reproduce this.
@danilw Does it still happen to you in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6)?

**Comment by danilw** [comment]
yes look like it fixed now, I checked on 3.2.2 Stable

in 3.1 all Keys that pressed during compiling was ignored, so **if you Hold key during compiling and keep holding it after compiling-Godot ignore it** that what this bug about, now its works, **not bug anymore**

**Comment by danilw** [comment]
@KoBeWi 
it fixed in 3.2.2 stable
I compare to 3.1.1
Bug was - **pressing Key once** during shader compiling will return true(key pressed) after shader compiling when key no longer presed.
I confirm **in 3.2.2 this bug does not work**
