### ISSUE TITLE
Assert script errors hidden

### ISSUE THREAD

**Issue by MunWolf** [godotengine/godot#32085]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Home, 10.0.17134

**Issue description:**
Script errors inside an assert clause don't show up in the script editor

**Steps to reproduce:**
1. Make a script defining a classname and have an assert clause with gibberish in it.
2. Make a second script defining a function taking in a parameter of the previous scripts type.

Observe that no error is shown in the first script but the second fails with 'cyclic dependency or script error' because the first one has a script error

**Minimal reproduction project:**
[simple_test.zip](https://github.com/godotengine/godot/files/3598323/simple_test.zip)

**Comment by akien-mga** [comment]
Fixed by #38279.
