### ISSUE TITLE
is_instance_valid returns true for a valiable that should have no value

### ISSUE THREAD

**Issue by jaykyburz** [godotengine/godot#32083]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 (1803)

**Issue description:**
The following script prints False then True which I found unexpected. Not sure if bug or not. 

```
var obj_a:Spatial = null
var obj_b := Spatial

func _ready():
	print (is_instance_valid(obj_a))
	print (is_instance_valid(obj_b))
```

obj_b returns true for is_instance_valid but I never gave it a value so I would expect it would be false. 

I have a few places in my code where I set up a variable, then I test is_instance_valid() and if not I go find the nearest object I want to track. 

Its easy to fix, I just need to use the first form where I explicitly set the variable to null, but as I said, it was unexpected.

**Comment by KoBeWi** [comment]
AFAIK, `is_instance_valid()` is only for checking if the object is not freed. It doesn't care about nulls.

**Comment by jaykyburz** [comment]
Null value returns False which is what I would expect.

**Comment by KoBeWi** [comment]
Aaaah, ok. I misunderstood something.

**Comment by jaykyburz** [comment]
Oh, you know what I did! I instantiated a new Spatial in obj_b!

My Bug!
