### ISSUE TITLE
The 'line' variable is assigned values twice sucessively 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#32090]
**Godot version:**
3.2.alpha.custom_build. 24e1039eb

**Issue description:**
The 'line' variable is assigned values twice sucessively (Line 347 and 348, line 354 and 355)
https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/modules/gdscript/language_server/gdscript_extend_parser.cpp#L347-L355

@Geequlim

**Comment by Geequlim** [comment]
I think the second one should be `line += "\n"`

**Comment by akien-mga** [comment]
> I think the second one should be `line += "\n"`

Should be an easy fix. Who makes the PR? :)
