### ISSUE TITLE
AnimationPlayer Bug, animation wrong angles  in some cases (example in)

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#32097]
*(maybe this is .gltf import bug)*

**Godot version:**
3.1.1 stable

**OS/device including version:**
Linux

**Issue description:**
Look screenshot, loading non-first animation make animation play in wrong angles
Loading first animation for just one single frame, make everything work.
*I dont thing this is "as expected", maybe bug I think.*

This bug happened in other *big* animations, not just this.

**Steps to reproduce:**
download [this (sketchfab link)](https://sketchfab.com/3d-models/sphere-bot-6c3a32958c2d43cdbf12a7109616bdbe)
(or my example project include this model)
launch its animation by script 
`get_node("AnimationPlayer").play("05_Sphere_bot_WalkCycle")`
it will be broken, but launching 
`get_node("AnimationPlayer").play("01_Sphere_bot_Roll")`
for 1 frame, fix it

**Minimal reproduction project:**
https://danilw.github.io/godot-utils-and-other/BUG_animation_player/BUG_animation_player.zip

![Bug](https://user-images.githubusercontent.com/24825887/64746683-3616bc80-d515-11e9-9e71-7f384dc4d3cc.png)
![No bug](https://user-images.githubusercontent.com/24825887/64746684-3616bc80-d515-11e9-9d72-db018df1fdd6.png)

**Comment by KoBeWi** [comment]
Looks fine in 3.2.3 rc5
