### ISSUE TITLE
cannot move viewport container with tilemap

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#32093]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

Hello,
If you have a tilemap inside a viewport container you cannot move the container. It just moves everything. I have to take the map out, move the container, then put it back. As per screenshot below. To recreate, simply do as the picture and try to move the container.

To be honest, it might be that it's because the tilemap is inside the viewport container as per the screenshot and I shouldn't be doing that. I've been at this a week now simply trying to make my tilemap only display in a portion of the screen (with another viewport above it showing score, etc) and went round and round in circles trying to figure it out. There are no examples or templates, no valid samples on youtube now things have changed, no details on how containers/viewports/cameras are meant to be set up (e.g. I found out just yesterday that a viewport will only display to the screen when inside a viewport container and that is not documented). When you look at the documentation there really is nothing: This is the entire sum of the documentation for viewportcontainer: "A Container node that holds a Viewport, automatically setting its size.", nothing else!

I tried reddit, then facebook then the internet and literally nobody had an answer on how to use viewports in 3.1.

As an aside, please do something with the documentation on viewports, viewport containers and creating multiple viewports...

![image](https://user-images.githubusercontent.com/12863685/64722578-a9451200-d4c6-11e9-9537-cd4a7ca02ec5.png)

**Comment by Calinou** [comment]
Does it work if you create a TextureRect node and assign a ViewportTexture to it?

**Comment by chucklepie** [comment]
I have no idea, I'm just struggling to figure out having multiple viewports and individually sized viewports. Every single sample, every demo, every game I see all people do is create a single viewport taking up the whole screen.

The only sample I found was on 'kids can code', but all that code does not work now as it's out of date.

**Comment by clayjohn** [comment]
I think this is an issue of understanding what a Viewport is and how it works rather than being a bug.

I have started a draft on using multiple Viewports. The draft has been sitting on my computer for a few weeks now, but I plan to have it finished before the release of 3.2.

**Comment by chucklepie** [comment]
Thanks. This will be appreciated by many :)

The main issue I had is it's very particular in that I had to create a vertical/horizontal container, inside those put a viewport container, then put in that a viewport, then in that a tilemap and a camera, then set up for every level the right anchor and sizing. Then repeat for my second viewport. Missing a single thing or doing it slightly wrong results in completely nothing, or in my case a giant grey rectangle on the screen you cannot get rid of and is very difficult to diagnose.

Apart from making this simpler (after all that is what Godot tries to excel at, e.g. higher level viewport nodes) and I expect this has been suggested before, what is needed is a 'scene generator'. I'm not talking about prefabs, and not a 'godot template', but more a way inside the IDE (e.g. an extra tab beside Scene tab) to select from a list of curated scene templates that produce and insert into the current project a scene complete with nodes, e.g. 'fire shader', '2d platform controller'.

Imagine that :)

**Comment by KoBeWi** [comment]
In terms of documentation, this shows correct usage of sub-viewports: https://docs.godotengine.org/en/stable/tutorials/rendering/viewports.html#viewport-container
Closing.
