### ISSUE TITLE
Smart snapping guides sometimes don't disappear

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32105]
**Godot version:**
4ee8ecd3e

**Issue description:**
Sometimes the smart snapping guides don't disappear and just stay there until you snap something again.

**Steps to reproduce:**
1. Enable smart snapping
2. Move something
3. Repeat from point 2 if the line(s) disappear
4. Unselect the object and enjoy your permanent line(s)
![image](https://user-images.githubusercontent.com/2223172/64818903-5c883680-d5ad-11e9-8efd-940f1386e682.png)

EDIT:
Worth to mention that the guides are still there when you switch to other scenes.

**Comment by CptPotato** [comment]
I had the same issue. I used snapping in 2d and the guides (red) didn't disappear.
