### ISSUE TITLE
2D axes are both red

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#32104]
Godot 3.2 24e1039eb6fe32115e8d1a62a84965e9be19a2ed
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

When I open an empty scene in 2D, both axes are red:
![image](https://user-images.githubusercontent.com/1311555/64816991-b7fff780-d5a0-11e9-987f-a05285e0c440.png)

It doesn't happen in 3.1.1. They are supposed to look like this:
![image](https://user-images.githubusercontent.com/1311555/64817034-d5cd5c80-d5a0-11e9-8319-ea4f8ee54ccd.png)

If you drag one of the guides to make a margin appear, or drag a control node in the scene, axes change back to their normal color.

**Comment by groud** [comment]
> @KoBeWi This could be related to #32105, since these lines are of the same color.

That's pretty sure. The snapping guides might be initialized and displayed at 0,0 by default. 
So if they are not hidden in some situation, it make sense they are display on top of the axes.
Also, then are drawn on top of the rulers, so it's sure those are the guides.

**Comment by Xrayez** [comment]
> It happened to me few times, but seems to be random

I bet some `bool` value isn't initialized in a constructor, enabling/disabling axes would be determined by garbage value in this case.
