### ISSUE TITLE
Image Based Lighting has firefly artifact

### ISSUE THREAD

**Issue by fire** [godotengine/godot#32125]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
OSX

**Issue description:**
Image based lighting on .hdr files causes fireflies while this environment sky panorama does not on .exr.

![Screen Shot 2019-09-13 at 9 18 54 AM](https://user-images.githubusercontent.com/32321/64878251-f086ec00-d607-11e9-85af-a75eef4454e1.png)

Inspect the .hdr to see that there is a very bright light on the Image Based Lighting.

**Steps to reproduce:**

Open the project to see the fireflies.

**Minimal reproduction project:**
[IBL.fireflies.Test.zip](https://github.com/godotengine/godot/files/3610854/IBL.fireflies.Test.zip)

**Comment by Calinou** [comment]
I remember seeing an issue about this, but I can't find it anymore.

**Comment by clayjohn** [comment]
I have fixed this as much as can be done for 3.2 in https://github.com/godotengine/godot/pull/29182

Reduz has plans to switch to a new method in 4.0 for radiance map generation to minimize fireflies.
