### ISSUE TITLE
Godot 3.1.1 - Renaming/Moving C# Scripts break CSharpProj.csproj

### ISSUE THREAD

**Issue by JustKato** [godotengine/godot#32128]
**Godot version:** 3.1.1

**OS/device including version:** Windows 10

**Issue description:** Once a script is moved/renamed the `...CSharpProj.csproj` doesn't update

**Steps to reproduce:** Create a `.cs` script, use an external editor to edit it, rename the file, try and build the project

**Comment by KoBeWi** [comment]
Duplicate of #12917
