### ISSUE TITLE
List scene file responsible for loading resource error.

### ISSUE THREAD

**Issue by alexis-evelyn** [godotengine/godot#32133]
**Godot version:**
3.2-dev

**OS/device including version:**
Tested on OSX - I believe this is on all devices.

**Issue description:**
Occasionally my scene files manage to have a missing resource it tries to load. This is just a reference to a resource that no longer exists. The last time this happened, my project used to be much smaller, so I was able to track down the reference and delete it from the scene file in a text editor. However, now I cannot find it because my project is big and the error message does not tell me what it is trying to load.

The error message is `No loader found for resource: res://.` What should be done is the scene file causing the error should be listed in the error message.

**Steps to reproduce:**
Corrupt a scene file so it looks for a resource that no longer exists.
Get this error message every time you run the game from the editor.

**Minimal reproduction project:**
None Provided.

**Comment by KoBeWi** [comment]
AFAIK it should show what resource it can't load. Even the error message you quoted is obviously supposed to contain a path (the `res://` part), but not sure why it doesn't. Any reproduction project?

**Comment by KoBeWi** [comment]
So as I said, the resource path does appear when loading fails. Comment if you can still reproduce in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) and please provide some minimal reproduction project.
