### ISSUE TITLE
VCS selection menu dropdown uses dummy option as placeholder

### ISSUE THREAD

**Issue by IronicallySerious** [godotengine/godot#32135]
**Godot version:**
3.2 alpha

**Issue description:**
![image](https://user-images.githubusercontent.com/31801364/64910637-1e6a4e80-d736-11e9-9e8a-fea38d294161.png)

The dropdown default value/placeholder is an option itself. Should be shown as a placeholder or not at all.

**Steps to reproduce:**
1. Select Project > Version Control > Set Up Version Control.
2. Expand the dropdown container to see the default value listed in too.

**Minimal reproduction project:**
Fresh Godot Project

**Comment by IronicallySerious** [comment]
I introduced this bug originally :P 
I am creating an issue so I remember to fix this as soon as I get free, or if anyone is willing, they can probably have a go at it.

Looks like a simple UI bug

**Comment by Calinou** [comment]
It would probably make sense to remove the placeholder option if at least one VCS is available. Just select the one that was first added to the list :slightly_smiling_face:

If no VCSes are found, an error dialog can be displayed instead.

**Comment by follower** [comment]
FWIW I think the "If no VCSes are found, an error dialog can be displayed instead." approach leads to a pretty unfriendly first experience--particularly with the current level of documentation as mentioned in https://github.com/godotengine/godot-docs/issues/2838.

My thinking is it would be nice if the "Set Up Version Control" displayed the error message (perhaps also stating "No VCS plugin available" in the disabled pop-up control) and then documented or linked to documentation on how to add an addon.
