### ISSUE TITLE
TilesetEditorContext will only focus on the first tile ID with a given Texture when modifying other IDs which share them in the TileSet editor

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#32136]
**Version:**  3.1.1

**Issue Description:**
This is a bit difficult to describe bug, since I don't quite understand how the underlying implementation works and how a TilesetEditorContext is generated.  But basically, the "Next Coordinate" buttons needed to change the Tile/Subtile/Shape are extremely confusing in what context is needed for the given functionality and this has probably contributed to this bug in some fashion.

Basically, it's impossible to bring up a TilesetEditorContext which is appropriate to alter the collision shapes of a specific tile ID which shares a Texture resource with another unless it's the first instance of that ID which utilizes the resource in the TileSet's tile collection.  Attempting to do so on an "empty" subtile when the TilesetEditorContext is "focused" on a subsequent instance "pops" its focus back to the first instance.  This makes it impossible to create a collision mask for more than one tile sharing a texture resource unless the shape already exists for a given subtile.  

The only way to add a shape to a subtile is to copy it over from `TileSet/#/shape` in the `TileSet` inspector context, and this only appears to apply to a single shape and a single subtile -- this field may be broken or it may be a side effect of how the field is exposed, but I'm not sure it's a bug, so I've filed a feature request to fix this at https://github.com/godotengine/godot-proposals/issues/66 .  If it's a bug I can file a seperate issue here.  Regardless, once this shape is created, it's possible to alter it with the appropriate TilesetEditorContext, but the moment the tileset editor clicks a subtile without an associated shape resource, it reverts back to the original problem behavior.

**Steps to reproduce:**
Create a new tileset.  Add a few textures (3 for example).  Select the last texture in the list, hit edit and make a new autotile.  You should have a couple tile IDs in the `TileSet` context.  The inspector will be in the `TileSetEditorContext` for the first instance using this texture.  Give it a name like "Instance 1".  Make a collision mask on the first ID on the texture you selected (In this case, "Instance 1".  Now, make another new autotile called "Instance 2".  

Select a node to clear the TileSet context.  

Re-open the TileSet editor for your TileSet resource (I hope you saved it somewhere!).  Pressing the Next Coordinate button with the previous texture we added stuff to in the TileSet editor selected should bring up Instance 1.  Press the Region subtab so "Next Coordinate" changes the tile context.  Press Next Coordinate again.  We should be on Instance 2.  Press the Collision subtab and select an empty subtile.  The `TilesetEditorContext` should change (incorrectly) back to the first instance utilizing the Texture.

-----
Edit 1:  I've noticed this bug also seems to occur when trying to copy/paste and modify the bitmask of  a selected tile.  The context might change under more circumstances than just collision and bitmask editing...

Edit 2: It seems apparent when enabling tile names that something's not right when changing Tile contexts, as it displays the *last* tile ID sharing the texture resource as the name, and lets you flip through the contexts when on the region subtab, but only lets you edit the `first` tile ID because it'll "pop" back when you start attempting to edit within that ID's context!  The name never changes from the *last* ID.  The below screenshot should *not* be possible, as the context is for ID 2 (called "door0" in the screenshot) when the name displayed is clearly ID 3 ("door1").  Editing 'door1' outside of the inspector itself (ie:  in the TileSet editor) is not possible unless the texture is changed to a unique one and the tileset editor is reloaded.
![image](https://user-images.githubusercontent.com/1023003/64912599-4edec800-d6f7-11e9-8741-6cadd7a3fa5a.png)

Functionality is restored when inside the `TileSet` inspector context, the `#/texture` property of a given ID is changed to a unique value.

**Comment by nobuyukinyuu** [comment]
An update.  This behavior appears to occur whenever clicking on a shared texture resource whose region is not occupied by the current context, but instead a *different* context.  This may be intended behavior, but it's extremely obtuse and most users would have no idea what was going on.  

When clicking on the texture preview in the main part of the tileset panel, if the region is occupied only by one ID, the TilesetEditorContext will switch to it.  However, if the region is occupied by multiple IDs, it seems to retain the proper ID.  This is more apparent when the "Display Tile Names" option is enabled.  This behavior seems to occur regardless of the editing type selected.  Perhaps this default behavior can be changed to ctrl+click (to mimic "go to definition" behavior), and a warning issued if attempting to edit a subtile outside of the current tile's region otherwise....?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
