### ISSUE TITLE
[2.1 branch] Nonexistent function 'canvas_item_set_material' in base 'VisualServer'

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#32131]
**Godot version:** 2.1.6

I just noticed the function `VisualServer.canvas_item_set_material()` isn't exposed to GDScript in the 2.1 branch. 

Also, would there be a workaround for this? I'm trying to create some sprites directly using the visual server, and I need to use a shader on them.

**Comment by Chaosus** [comment]
Unfortunately, core devs are no longer support 2.1 branch (other than critical bug fixes) - but if someone wants to fix this - you welcome!

**Comment by Skaruts** [comment]
Personally I don't know how. I suppose it involves the bindings code in VisualServer.cpp, but that's about all I suppose I know.

**Comment by aaronfranke** [comment]
Are you trying to get this exposed, or is there some kind of bug caused by this not being exposed? Exposing this would be a feature change and those typically aren't done in maintenance releases, especially on old legacy branches.

**Comment by Skaruts** [comment]
I don't know if it classifies as a bug, but I certainly wouldn't classify it as a feature change: I am assuming that function was neglected in the gdscript bindings, leaving the VisualServer's interface incomplete. I'm assuming it wasn't intended to stay as it is. 

And the problem is that if you want to use the VisualServer directly you'll have no way to add a material (and shader) to a canvas item. The only work around I know of is falling back to using Sprites as usual, but then that's probably what you were trying to avoid in the first place by using the VisualServer.

**Comment by akien-mga** [comment]
There's a lot of VisualServer API which was not exposed in 2.1 and got exposed in 3.0, see #12241. It would be a significant amount of work to cherry-pick that, ensure that everything works and does not create issues (especially as this PR had to change the binding system a bit). So unless there's a strong need for it and someone interested in doing the work (ideally someone who'd need it and be able to test it), it's unlikely to happen for the 2.1 branch.
