### ISSUE TITLE
AnimatedTexture doesn't animate when loaded as custom mouse cursor

### ISSUE THREAD

**Issue by sprite-1** [godotengine/godot#32148]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
When I made an AnimatedTexture resource and used that to programmatically alter the mouse cursor, it doesn't animate.
https://i.imgur.com/JmRPO1k.gifv
The Sprite node on the left side has the AnimatedTexture loaded into it and it works but using that same resource as mouse cursor doesn't animate it.

**Steps to reproduce:**
1. Create an AnimatedTexture resource and propagate it with your images.
2. Set it as the mouse cursor by adding `Input.set_custom_mouse_cursor(load("res://your_animatedtexture.tres"),Input.CURSOR_POINTING_HAND,Vector2(0,0))` to the startup script

(You might get a better idea by checking the minimal repro project below)

**Minimal reproduction project:**
[AnimatedTexture Bug.zip](https://github.com/godotengine/godot/files/3614081/AnimatedTexture.Bug.zip)

**Comment by Calinou** [comment]
I think this is more of a feature request than a bug :slightly_smiling_face:

In the meantime, we should update the documentation to note that AnimatedTextures aren't supported as custom mouse cursors.

**Comment by sprite-1** [comment]
Oh, I didn't know that. What should I do from here? Do I open another request at [godot-proposals](https://github.com/godotengine/godot-proposals/)?

**Comment by Calinou** [comment]
@sprite-1 Yes, I think it makes sense as it may not be so easy to implement (hardware cursors call into OS-specific APIs).

**Comment by sprite-1** [comment]
Alright, writing a proposal might have to wait for a bit though since it seems to be an involved process.

**Comment by sprite-1** [comment]
Well I added the proposal [here](https://github.com/godotengine/godot-proposals/issues/74)

**Comment by Chaosus** [comment]
Ok, then this may be closed. ^^
