### ISSUE TITLE
Error spam when using compressed image as custom cursor

### ISSUE THREAD

**Issue by sprite-1** [godotengine/godot#32147]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
The game hangs and Godot's console gets spammed with error when I use compressed image as the cursor
![image](https://user-images.githubusercontent.com/33685433/64924858-9494b100-d81b-11e9-8b71-d5ea50aef8c2.png)

**Steps to reproduce:**
1. Import an image and set its compression to Video RAM
2. On the startup script, add `Input.set_custom_mouse_cursor(load("res://yourimage.png"),Input.CURSOR_POINTING_HAND,Vector2(0,0))`
3. Run the game in the editor

I currently worked around it by re-importing the image with compression set to "Uncompressed"

**Comment by Calinou** [comment]
The error message seems to be inaccurate. From my testing on commit https://github.com/godotengine/godot/commit/24e1039eb6fe32115e8d1a62a84965e9be19a2ed on Linux, the Uncompressed, Lossless and Lossy modes can all be used for custom mouse cursors. Only Video RAM can't be used.

**Comment by sprite-1** [comment]
> The error message seems to be inaccurate. From my testing on commit [24e1039](https://github.com/godotengine/godot/commit/24e1039eb6fe32115e8d1a62a84965e9be19a2ed) on Linux, the Uncompressed, Lossless and Lossy modes can all be used for custom mouse cursors. Only Video RAM can't be used.

So this is intended behavior then?

**Comment by Calinou** [comment]
@sprite-1 I guess it is – VRAM-compressed textures go through a different pipeline for efficiency. Either way, cursor images are small (256×256 at most), so VRAM compression isn't needed for those.

**Comment by sprite-1** [comment]
Yeah, I just have VRAM as the default for the project as a whole. If that's the case then I should just close this instead of clogging up other more important issues.

**Comment by Calinou** [comment]
I think this issue is still relevant – the project shouldn't hang and the error message shouldn't be spammed.

**Comment by sprite-1** [comment]
Oh alright gotcha

**Comment by KoBeWi** [comment]
Still valid in 3.2.3 rc4 (hangs the game)

In 23ce1db the cursor simply appears as black rectangle. This is already mentioned in the docs, so should be fine to the issue probably?
