### ISSUE TITLE
UPNP discovery blocks the main thread

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#32160]
**Godot version:**
3.1.1 stable
**OS/device including version:**
arch linux
**Issue description:**
When calling `upnp.discover()` on a newly created UPNP object with `UPNP.new()`, it will block the main thread until all gateway devices have been pinged for up to 5 seconds per device, significantly harming the user experience.

It is possible to move the discovery into a new thread in GDScript, but the discovery and the thread can never be force stopped for when the program is closed. The discovery should take place inside of another thread managed by this reference counted object with `upnp.discovery_start()`, `upnp.discovery_status()`, and `upnp.discovery_stop()` imo.
**Steps to reproduce:**
1. create upnp object with `UPNP.new()`
2. discover gateway devices with `upnp.discover`
**Minimal reproduction project:**

**Comment by tavurth** [comment]
Thanks for posting this, I've even tried running this in a separate thread and it still seems to block the main:

```gdscript
func _upnp_setup(server_port):
	Logger.log("[Network]: Setting up UPNP")

	# UPNP queries seem to take some time
	var upnp = UPNP.new()
	var err = upnp.discover()

	if err:
		return self.connection_failure(err)

	if upnp.get_gateway() and upnp.get_gateway().is_valid_gateway():
		upnp.add_port_mapping(server_port, server_port, "Godot", "UDP")
		upnp.add_port_mapping(server_port, server_port, "Godot", "TCP")

		self.UPNP_ROUTES = upnp

#
# Node setup
#
func _ready():
	var thread = Thread.new()
	thread.start(self, "_upnp_setup", DEFAULT_PORT)
	thread.wait_to_finish()
```

**Comment by Faless** [comment]
> ```gdscript
> 	thread.wait_to_finish()
> ```

You are also waiting for it to finish, so you are blocking the main thread on purpose.

This would do:
```gdscript
func _upnp_setup(server_port):
	# UPNP queries seem to take some time
	var upnp = UPNP.new()
	var err = upnp.discover()

	if err:
		return push_error(err)

	if upnp.get_gateway() and upnp.get_gateway().is_valid_gateway():
		upnp.add_port_mapping(server_port, server_port, "Godot", "UDP")
		upnp.add_port_mapping(server_port, server_port, "Godot", "TCP")

#
# Node setup
#
var thread = null
func _ready():
	var thread = Thread.new()
	thread.start(self, "_upnp_setup", 3928)

func _exit_tree():
	# Wait for thread finish here, to handle game exit while thread is running.
	thread.wait_to_finish()
```

I don't think we need to handle this in a dedicated UPNP node, it can be done with few lines of GDScript.

**Comment by tavurth** [comment]
Sorry perhaps I should have been more clear. 
The code above blocks the main thread **while it is running in the second thread**

Please see the ammended code:

```gdscript
extends Control


func _upnp_setup(server_port):
	# UPNP queries seem to take some time
	var upnp = UPNP.new()
	var err = upnp.discover()

	if err:
		return push_error(err)

	if upnp.get_gateway() and upnp.get_gateway().is_valid_gateway():
		upnp.add_port_mapping(server_port, server_port, "Godot", "UDP")
		upnp.add_port_mapping(server_port, server_port, "Godot", "TCP")

#
# Node setup
#
func _ready():
	yield(get_tree().create_timer(2), "timeout")
	var thread = Thread.new()
	print("Before thread")
	yield(get_tree().create_timer(0.5), "timeout")
	thread.start(self, "_upnp_setup", 3928)
	print("After thread")
	thread.wait_to_finish()
```

Can you please re-open this? It's still present in Godot 3.2

**Comment by Faless** [comment]
@tavurth as said above, **you must not call `wait_to_finish` in `_ready`**

**Comment by tavurth** [comment]
Hmm, something weird is going on with the print calls above then, I tried your code and it seems to work ok.

Maybe the print buffer is not being flushed in time and so the "After thread" text only shows after `thread.wait_to_finish()`.
