### ISSUE TITLE
The reserved `tool` keyword can be used as a variable identifier but it's still highlighted

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#32164]
**Godot version:**
3.2-alpha, 24e1039

**Issue description:**
According to [documentation](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#keywords):
> Since keywords are reserved words (tokens), they can’t be used as identifiers.

The question is whether it's a bug or should be a feature, because I couldn't accept the fact that I can't use `tool` identifier for my gameplay needs, or should I pick other keyword for that.

Since we're into breaking stuff in 4.0, perhaps this should be also renamed, something like in #17592.

**Steps to reproduce:**
This runs fine:

```gdscript
tool
extends Node2D

func _ready():
	var tool = "I'm just a tool"
	print(tool)
```

The second `tool` in `_ready` is also highlighted.

**Minimal reproduction project:**
[tool-can-use.zip](https://github.com/godotengine/godot/files/3615914/tool-can-use.zip)

**Comment by bojidar-bg** [comment]
Some keywords can be used as identifiers, though the support for this is patchy at times. This is only in contexts where they cannot be used as keywords.
For example, you can use `if` as a function name, but you cannot use it as a variable name.

The main issue before was that certain annotation-style keywords, such as `sync`, `master`, `puppet`, and even `tool` could not be used to index objects.

IMO, the syntax should continue to be supported in the future, or at least until annotations land (at which point, support for `func if` might be dropped).

**Comment by Xrayez** [comment]
Yeah, the main concern is not removing support for this, but whether it's going to be supported in the future or would I have to go through compatibility breakage.

> The second tool in _ready is also highlighted.

This creates usability issue then, the `var` and `tool` meld into each other making them more difficult to distinguish visually. I guess it's not as trivial to enable/disable highlight in different places though.

**Comment by KoBeWi** [comment]
Related to #28866

**Comment by Xrayez** [comment]
Superseded by #36878 and #28866, the current use case is covered there, so closing.
