### ISSUE TITLE
Failure to import bmp files and very poor error details

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#32166]
**Godot version:**
3.1.1

1. Godot does not support bmp files very well
2. Error handling of the import pipeline is poor and non-descript
3. Documentation on supported formats are not available, or easily found in the docs website

Specifically:
The Godot bitmap importer pipeline cannot read 8 bit bitmap files. Searching elsewhere it appears it may not even work with 16 or 24 bit bitmaps, which do not store separate palettes so there is no real-reason to not support them. Seems a bit poor that a load and convert cannot manage this and instead you have to resort to loading every image in an application, resave as 32bit then try again.

Also of note, is the error messages prodcued are distinctly lacking in any detail or clarity as to the probem:
" editor/editor_file_system.cpp:1618 - Error importing: res://assets/sprites/xman_walk2l.bmp"

is all you get. I could not find anywhere to add enhanced error messages.

Additionally, there doesn't seem to be any documentation stating file formats supported and not supported.

**Comment by Calinou** [comment]
I did some testing with BMP importing (some importing failures have been fixed after 3.1.1's release), see #30629.

**Comment by chucklepie** [comment]
Thanks, I'll try when the next stable comes out. I guess there'll be no 8 bit with palette index 0 transparency support ;-)

I guess error messages or documentation is not improved?

**Comment by Calinou** [comment]
Error messages have been partially improved. For instance, importing a compressed BMP will print an error message, stating that compressed BMPs aren't supported.

We still need to add an error message when importing a 16-bit BMP (which isn't supported yet), and mention BMP importing caveats in the class reference.

**Comment by Xrayez** [comment]
The `Image.load` method itself could be better documented to list officially supported image file formats, including BMP and other limitations (as in GIF probably #31831, if ever supported).

**Comment by chucklepie** [comment]
Thanks, these improvements sound great :)

Keep up the good work.

**Comment by DiegoRibeiro** [comment]
I have the same problem. I have a sprite sheet(32 bits rgba - without compression) from an old game and im trying to import  and can't import it on a tileset.

error:
 Failed loading resource: res://assets/sprite2.bmp
 'res://assets/sprite2.bmp' is not a valid texture.
 editor/editor_file_system.cpp:1618 - Error importing: res://assets/sprite2.bmp

the image is attached as a zip file. 

ps: it works on unity, maybe i am doing something wrong here i dont know.

thanks for this great engine.
[sprite2.zip](https://github.com/godotengine/godot/files/3786727/sprite2.zip)
