### ISSUE TITLE
Improve Android runtime permissions handling

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot#32162]
As discussed in PR#31598

> I'm not against about adding signal but now we seems to have to deal with all kinds of permission.
> there should be a way to simply handle this.

The list of permissions in the manifest can be retrieved at runtime via the [PackageInfo#requestedPermissions](https://developer.android.com/reference/android/content/pm/PackageInfo.html#requestedPermissions) field. So a better way to deal with arbitrary permissions would be to query the manifest at runtime, and request to the user the permissions declared there.

In addition, we should include an api to allow GDScript to request arbitrary runtime permissions, and be notified of the result via notifications. I'll create an issue to track it. It may be relatively short to implement (~1 week), so we may want to hold off on this PR if time's not an issue.

_Originally posted by @m4gr3d in https://github.com/godotengine/godot/pull/31598#issuecomment-531668507_

**Comment by cagdasc** [comment]
I can implement this feature. I will fetch permissions which defined in Android Manifest and compare with user requested permission's. If there is match/not match, I will give success/fail message with signal. We can give defined permission status like GRANTED/NOT GRANTED. But I have some questions about implementation. 
Q1: I can create new singleton for permission operations like `PermissionManager`. What do you think? or continue on `OS`.
Q2: Maybe we need to define available permissions constants for Godot which for abstract from operation system?

**Comment by cagdasc** [comment]
@m4gr3d @volzhs 
I implemented `PermissionManager` to native code. Can you review commit which below link? After everything is okay, I will map permission to given index on Java side and check permission exist in manifest and permission status(granted/not granted) after send signal to native side.

https://github.com/cagdasc/godot/commit/1ee3fd3abcbfec1f3bd26b5678aaa4d2dde6e19f

**Comment by cagdasc** [comment]
@m4gr3d there is no reviewer assigned my last pr #32246 is this normal?

**Comment by akien-mga** [comment]
Can we consider this fixed by #32600?

**Comment by m4gr3d** [comment]
Yep!
