### ISSUE TITLE
Viewport drag experience is worst

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#32163]
Godot 3.1.1

Linux Manjaro

I think that the viewport drag have to be free, I don't know what criteria it uses to lock the drag area but most of the time is limiting me. The image below is an example, when developing mobile portrait game i can't put the viewport in center of the screen because the drag is locked. Or with some big tilemap, I can't draw because the drag doesn't let me have a look at the next empty area [30348](https://github.com/godotengine/godot/issues/30348) (i haven't tested it yet).
![viewport wrong position](https://user-images.githubusercontent.com/16955149/64952017-7f516e00-d87f-11e9-9326-53f5cb50751f.png)

Reproduce by creating a simple empty scene with viewport of 720x1280, zoom out to view all area and you cant drag to center.

**Comment by Zireael07** [comment]
I believe that's a bug already fixed in master?

**Comment by KoBeWi** [comment]
Could you try with a nightly build if it's any better? Also in 3.1.2 you will be able to remove the viewport limits altogether.

**Comment by grevius5** [comment]
> Could you try with a nightly build if it's any better? Also in 3.1.2 you will be able to remove the viewport limits altogether.

This would be great to disable the limits! Now I'm pretty busy, but I'll try to compile and try the nightly build.

**Comment by KoBeWi** [comment]
You don't need to compile, you can get one from here: https://hugo.pro/projects/godot-builds/

**Comment by grevius5** [comment]
ok, It seam to work with daily version! But I haven't found where to disable the limit for the viewport. I think this is a must-have option for better usability.

**Comment by Calinou** [comment]
@grevius5 Try unchecking **Editors > 2d > Constrain Editor View**.

**Comment by grevius5** [comment]
ok, it's all working as aspected. I can close this issue as it's already fixed. But I think the setting is a bit hard to find.

**Comment by Macksaur** [comment]
I fixed this in https://github.com/godotengine/godot/pull/73223 but constraining might be being entirely removed.
