### ISSUE TITLE
DynamicFont fails to load FontData: ERR_CANT_OPEN

### ISSUE THREAD

**Issue by DavidJVitale** [godotengine/godot#32184]
**Godot version:** 

`3.1.stable.mono.official`

**OS/device including version:**

`Ubuntu 19.04`

**Issue description:**

I have a few `.otf` and `.ttf` fonts from [Google noto fonts](https://www.google.com/get/noto/). Attempting to create a `DynamicFont` with some `.otf`/`.ttf` files in the `FontData` section yields this error in the `Output` window:

`scene/resources/dynamic_font.cpp:149 - Condition ' !f ' is true. returned: ERR_CANT_OPEN`

**Steps to reproduce:**

- Download some font files, like https://www.google.com/get/noto/#sans-deva or https://www.google.com/get/noto/#sans-jpan
- Extract one of the `.otf`/`.ttf` files from the zip and copy it to your project via the nautilus file explorer
- In the `Create New Resource` window, create a new `DynamicFont`
- In the `Inspector` window of the new `DynamicFont`, set the `Font Data` to the `.otf`/`.ttf` file
- Notice the `ERR_CANT_OPEN` error in the output window. 
- Save the font as a `.tres`, and then try to use it on a `Label` node. No text output.

![nonlatinfonterror](https://user-images.githubusercontent.com/18691334/65112589-06443a80-d995-11e9-81c7-e9b7c79db74a.gif)

**Minimal reproduction project:**

[fonts_repro.zip](https://github.com/godotengine/godot/files/3624571/fonts_repro.zip)

-----

I believe this has something to do with file permissions or file ownership. **A workaround  I have discovered is running `sudo chmod +rw /path/to/fonts.ttf`.** I am not sure why this works. Another workaround is moving the `.otf`/`.ttf` file via the bash shell instead of the nautilus gui file explorer. 

It is possible this is an environment issue with my machine. But it also might be a bug on Godot's side, and the above project (should) be reproducible.

**Comment by qarmin** [comment]
I can't reproduce this on Godot 3.1 and 059a53ee1

**Comment by akien-mga** [comment]
If the font file lacked read permission `r`, it's normal that Godot couldn't access it. I'm not sure how you ended up with a font without read permission, but that would have happened outside Godot, we don't modify file permissions.

The error message is also slightly more explicit now, pointing you to the file that could not be open.
