### ISSUE TITLE
Cannot create new project when folder's name have blank space

### ISSUE THREAD

**Issue by juanfrangarro** [godotengine/godot#32187]
**Godot version:** 
Godot Engine v3.2.alpha.calinou.24e1039eb  

**OS/device including version:**
Windows 10 x64 
Intel i7 7700K 4.20 GHz, 64 GB RAM, nVidia GeForce GTX 1080

**Issue description:**
I am having an issue when I try to create a new project with a blank space inside the project's root folder.
Godot allows me to create both folder and project, but after that, Godot can't find it.

This problem is solved when I create the same folder without a blank space in the name.

I think Godot might not allow to create folders with blank spaces.

**Steps to reproduce:**
Go to Godot Project's Manager and create a new project. Create it in a folder with a blank space in its name. After that, try to find the project with the Project Manager.

**Comment by Calinou** [comment]
I can't reproduce this on commit https://github.com/godotengine/godot/commit/3e782c78ae46dd3452e7a61a52c65a69f09b8413. By "blank space", do you mean a standard space character or a special character such as a non-breaking space?

**Comment by akien-mga** [comment]
Ping. We need more information to debug, otherwise this can't be solved.

**Comment by juanfrangarro** [comment]
Hi everybody! 
I tested again and the issue didnt reproduce, tested with latest Calinou compilation.
Project folders create normally.
