### ISSUE TITLE
Windows build error C2065: 'XUSER_MAX_COUNT': undeclared identifier

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#3218]
this is the error:
```
\platform\windows\joystick.h(116) : error C2065: 'XUSER_MAX_COUNT' : undeclared identifier

```
I get

**Comment by akien-mga** [comment]
Ping @punto- and @Hinsbart.

**Comment by Hinsbart** [comment]
But it didn't complain about missing xinput.h? Strange.
Then I guess not all versions of the header have that constant, in this case a simple #ifndef and #define will do it. Will look into it later today

Thank you M$ for making gamepad code so joyfull to work on for your platform... not

**Comment by Hinsbart** [comment]
Can you try  [this branch](https://github.com/Hinsbart/godot/tree/xinput_define) please? Or add the following two lines to `platform/windows/joystick.h` yourself:
```c++
#ifndef XUSER_MAX_COUNT
#define XUSER_MAX_COUNT 4
```
As I'd like to know if there are any other constants we need for your version before I make a PR
