### ISSUE TITLE
Console reporting (and spamming) "non errors" on runtime

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#32188]
**Godot version:**
3.1.1
**OS/device including version:**
Windows 10

**Issue description:**
Console reports various kinds of error, but they are not really errors, neither warnings, they are only situations usually handled by scripts themselves.

**Steps to reproduce:**
execute the project and look at console output
[MRPerrors.zip](https://github.com/godotengine/godot/files/3626814/MRPerrors.zip)

**Minimal reproduction project:**

**Comment by girng** [comment]
> E 0:00:00:0643   Condition ' !metadata.has(p_name) ' is true. returned: Variant()
  <C Source>     core/object.cpp:1061 @ get_meta()
  <Stack Trace>  Node2D.gd:11 @ _ready()

You need to call `has_meta` before `get_meta` **if the meta key** does not exist :)

> E 0:00:00:0645   Node not found: test
  <C Source>     scene/main/node.cpp:1396 @ get_node()
  <Stack Trace>  Node2D.gd:14 @ _ready()

 You can use `has_node` if you are not sure if that node exists, but this is the correct error cause I'm looking in the scene tree, and the node `test` is not there.

**Comment by burstina** [comment]
I know about "has_something", but those functions return values already consistent.

for example

```
var some_node=null
if x.has_node(y):
    some_node=x.get_node(y)
```

and
```

var some_node=null
some_node=x.get_node(y)

```
are the same, except the second example report error in console



> 
> 
> > E 0:00:00:0643   Condition ' !metadata.has(p_name) ' is true. returned: Variant()
> >      core/object.cpp:1061 @ get_meta()
> >   Node2D.gd:11 @ _ready()
> 
> You need to call `has_meta` before `get_meta` **if the meta key** does not exist :). Or, make sure to set the meta by using `set_meta`.
> 
> > E 0:00:00:0645   Node not found: test
> >      scene/main/node.cpp:1396 @ get_node()
> >   Node2D.gd:14 @ _ready()
> 
> You can use `has_node` if you are not sure if that node exists, but this is the correct error cause I'm looking at the scene tree, and the node `test` is not there.
> 
> > they are only situations usually handled by scripts themselves.
> 
> Scripts can generate errors though, I'm confused :S

**Comment by Calinou** [comment]
> Think about using "has_node" each time you use "get_node": it is cumbersome.

`get_node()` will print an error message if the node doesn't exist. To avoid this, use `get_node_or_null()` (but do understand the implications of failing silently first).

**Comment by girng** [comment]
### `get_node()`:
> Fetches a node. The NodePath can be either a relative path (from the current node) or an absolute path (in the scene tree) to a node. If the path does not exist, a null instance is returned and attempts to access it will result in an "Attempt to call <method> on a null instance." error.

### `get_node_or_null()`
> Similar to get_node(), but does not raise an error if path does not point to a valid Node.

@burstina, you might be looking for `get_node_or_null` (as Calinou stated)

**Comment by burstina** [comment]
> `get_node_or_null()`

I didn't know that kind of function, this function was just too specific to remember for me, but I'll do.

>failing silently makes debugging more difficult. 

absolutely right, and not failing makes developing more time spending, but I hope it'd be good for stability and porting.

Usually you tend to stick to things and logics striving toward what you are already used to: only other peole can help to see better path!
ty

**Comment by Calinou** [comment]
Closing, as the original issue appears to be resolved.

If you really need to silence errors and warnings temporarily, you can use [`Engine.print_error_messages = false`](https://github.com/godotengine/godot/pull/48359) before running problematic code then use `Engine.print_error_messages = true` after running problematic code. Please do not report issues with errors silenced, as this use case is entirely unsupported :slightly_smiling_face:
