### ISSUE TITLE
Need to confirm app installation each time on native run

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32183]
**Godot version:**
3.1.1

**OS/device including version:**
Android 7 on Xiaomi Redmi Note 4

**Issue description:**
When you run Android app on the device (the "native run" option), Android will prompt you to confirm the installation. Even if I click to remember my choice, it still asks again. This does not happen when installing app directly via adb.

This is annoying, because when I run on device, I want to click and forget, because the exporting process takes time. However I have to remember to confirm the app, which makes the option pretty useless, because I could as well install it manually >_>

**Comment by akien-mga** [comment]
I have a same issue on a Xiaomi device (Pocophone F1). Is it really a Godot issue though? I got the feeling that it was MIUI being overly annoying on this process, as it used to work frictionless on my previous LineageOS phone.

But if that's on the Godot side and we can fix it, that would really be awesome, because my phone aborts installation after 10 s if I'm not fast enough to approve it... (Even though I enabled Developer mode and ticked on everything I could to prevent it from being a paranoid box).

**Comment by KoBeWi** [comment]
I mean, if it doesn't happen when using adb directly (`adb install -r`), then Godot might get some improvement. The fact that you need to "Remember my choice" each time suggests that the app is installed from different "source id" or whatever. I'm not Android expert, so not sure what it is exactly and if it's doable >_>

**Comment by akien-mga** [comment]
Does it work better if you turn off `one_click_deploy/clear_previous_install`?

**Comment by akien-mga** [comment]
Relevant code: https://github.com/godotengine/godot/blob/master/platform/android/export/export.cpp#L1437-L1472

**Comment by KoBeWi** [comment]
> Does it work better if you turn off one_click_deploy/clear_previous_install?

Actually it does... Any reason this is on by default? The app is overwritten anyways.

**Comment by akien-mga** [comment]
I guess it's cleaner to uninstall before install to be in the same conditions as a new user. Especially if your app requires specific permissions and you need to check that they're properly requested, you don't want the previous test to impact that.

Still, it's also quite annoying to have to babysit your phone when exporting a big project, so maybe it should be off by default. Pros and cons :)

**Comment by KoBeWi** [comment]
Yeah, you don't need to test permissions and "clean user state" each time, so having it off by default makes sense.
