### ISSUE TITLE
Project Export Crashes with Mono Support

### ISSUE THREAD

**Issue by Catchawink** [godotengine/godot#32185]
**Godot version:**
3.2.alpha
mono 6.0.0

**OS/device including version:**
Windows 10 x64

**Issue description:**
I'm compiling Godot with Mono (statically linked). The engine and export templates seem to build fine, but running an exported project (.exe) results in the following error:

```
ERROR: GDMono::_initialize_and_check_api_hashes: Mono: Core API hash mismatch.
   At: modules\mono\mono_gd\gd_mono.cpp:433
Mono: Logfile is: C:/Users/.../AppData/Roaming/Godot/app_userdata/Test/mono/mono_logs/2019_09_18 01.18.42 (19508).txt
ERROR: mono_log_callback: Mono: FATAL ERROR, ABORTING! Logfile: 'C:/Users/.../AppData/Roaming/Godot/app_userdata/Test/mono/mono_logs/2019_09_18 01.18.42 (19508).txt'.
   At: modules\mono\mono_gd\gd_mono_log.cpp:75
```

Here are the contents of the logfile:

```
Config attempting to parse: 'C:/Users/.../Desktop/Test/Build/Test/data_Test/Mono/etc/mono/config'. (in domain Mono, info)
..\mono\eglib\ghashtable.c:326: assertion 'hash != NULL' failed (in domain , critical)
Thread 0000000000004020 may have been prematurely finalized (in domain , warning)
* Assertion at ..\mono\utils\mono-threads.c:634, condition `info' not met
 (in domain , error)
```

**Steps to reproduce:**
- Compile Godot with Mono support (statically linked).
- Build export templates.
- Create a project.
- Export using a template (debug).
- Run export.

**Minimal reproduction project:**
A new project with an empty main scene.

**Comment by Catchawink** [comment]
When compiling and running without statically linking and using the latest version of Mono (6.4.0), exports still crash (both debug and release). Here's the output from the console:

> ERROR: GDMono::_initialize_and_check_api_hashes: Mono: Core API hash mismatch.
>    At: modules\mono\mono_gd\gd_mono.cpp:433
> Mono: Logfile is: C:/Users/.../AppData/Roaming/Godot/app_userdata/Test/mono/mono_logs/2019_09_25 14.34.01 (14192).txt
> ERROR: mono_log_callback: Mono: FATAL ERROR, ABORTING! Logfile: 'C:/Users/.../AppData/Roaming/Godot/app_userdata/Test/mono/mono_logs/2019_09_25 14.34.01 (14192).txt'.
>    At: modules\mono\mono_gd\gd_mono_log.cpp:75

And the logfile:

> Config attempting to parse: 'C:\Users\...\Desktop\Test\Build/Test/data_Test/Mono/etc\mono\config'. (in domain Mono, info)
> ..\mono\eglib\ghashtable.c:326: assertion 'hash != NULL' failed (in domain , critical)
> Thread 0000000000004BAC may have been prematurely finalized (in domain , warning)
> * Assertion at ..\mono\utils\mono-threads.c:638, condition `info' not met
>  (in domain , error)

I tried Mono v5.18.1 based on a comment in #32300 (again, not statically linked). Still receiving errors, albeit new ones:

> ERROR: GDMono::_initialize_and_check_api_hashes: Mono: Core API hash mismatch.
>    At: modules\mono\mono_gd\gd_mono.cpp:433
> Mono: Logfile is: C:/Users/.../AppData/Roaming/Godot/app_userdata/Test/mono/mono_logs/2019_09_25 14.07.05 (4580).txt
> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] RtlEnterCriticalSection
> [1] RtlEnterCriticalSection
> [2] mono_gchandle_new_weakref
> [3] mono_gchandle_new_weakref
> [4] mono_gchandle_new_weakref
> [5] mono_gchandle_new_weakref
> [6] mono_gchandle_new_weakref
> [7] mono_gchandle_new_weakref
> [8] mono_gchandle_new_weakref
> [9] GDMono::load_assembly (c:\users\...\desktop\godot\modules\mono\mono_gd\gd_mono.cpp:475)
> [10] GDMono::load_assembly (c:\users\...\desktop\godot\modules\mono\mono_gd\gd_mono.cpp:461)
> [11] GDMono::_load_core_api_assembly (c:\users\...\desktop\godot\modules\mono\mono_gd\gd_mono.cpp:683)
> [12] GDMono::_try_load_api_assemblies (c:\users\...\desktop\godot\modules\mono\mono_gd\gd_mono.cpp:736)
> [13] GDMono::_load_api_assemblies (c:\users\...\desktop\godot\modules\mono\mono_gd\gd_mono.cpp:764)
> [14] GDMono::initialize_load_assemblies (c:\users\...\desktop\godot\modules\mono\mono_gd\gd_mono.cpp:375)
> [15] CSharpLanguage::init (c:\users\...\desktop\godot\modules\mono\csharp_script.cpp:136)
> [16] ScriptServer::init_languages (c:\users\...\desktop\godot\core\script_language.cpp:178)
> [17] Main::setup2 (c:\users\...\desktop\godot\main\main.cpp:1282)
> [18] Main::setup (c:\users\...\desktop\godot\main\main.cpp:1062)
> [19] widechar_main (c:\users\...\desktop\godot\platform\windows\godot_windows.cpp:150)
> [20] _main (c:\users\...\desktop\godot\platform\windows\godot_windows.cpp:184)
> [21] main (c:\users\...\desktop\godot\platform\windows\godot_windows.cpp:196)
> [22] __scrt_common_main_seh (d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
> [23] BaseThreadInitThunk
> -- END OF BACKTRACE --

And the logfile:

> Config attempting to parse: 'C:\Users\...\Desktop\Test\Build/Test/data_Test/Mono/etc\mono\config'. (in domain Mono, info)
> ..\mono\eglib\ghashtable.c:324: assertion 'hash != NULL' failed (in domain , critical)
> ..\mono\eglib\ghashtable.c:324: assertion 'hash != NULL' failed (in domain , critical)

**Comment by neikeq** [comment]
Can you still reproduce this with alpha0? https://downloads.tuxfamily.org/godotengine/3.2/alpha0-unofficial/mono/

**Comment by Catchawink** [comment]
@neikeq I'm still receiving errors with alpha0. They're somewhat different:

```
ERROR: _initialize_and_check_api_hashes: Mono: Core API hash mismatch.
   At: modules/mono/mono_gd/gd_mono.cpp:433
Mono: Logfile is: C:/Users/.../AppData/Roaming/Godot/app_userdata/Test/mono/mono_logs/2019_09_27 17.04.50 (8880).txt
```

And here's the logfile:

```
Config attempting to parse: 'C:\Users\...\Desktop\Test\Build\Test/data_Test/Mono/etc\mono\config'. (in domain Mono, info)
ghashtable.c:324: assertion 'hash != NULL' failed (in domain , critical)
ghashtable.c:324: assertion 'hash != NULL' failed (in domain , critical)
```

**Comment by neikeq** [comment]
I will test this in a few days. I tested recently on Windows without this issue, so it may have something to do with the project. Can you upload an example project where you can reproduce it?

**Comment by akien-mga** [comment]
Can you test if it still crashes with https://downloads.tuxfamily.org/godotengine/3.2/dev.bf1c81adf/mono/ ?

**Comment by Catchawink** [comment]
@neikeq I uploaded an example project [here](https://github.com/Catchawink/godot-project-test).

@akien-mga I'm still receiving errors with this build. The errors are the same as the ones in my previous comment.

**Comment by BenMcLean** [comment]
I am also having this same problem when trying to run the oculus mobile plugin demo project on Windows 10.

**Comment by akien-mga** [comment]
The core API mismatch error on debug builds is still valid (see #35290), but it shouldn't make projects crash.

Can you still reproduce this issue in 3.2 RC 1 or later?

**Comment by akien-mga** [comment]
Tested the project in https://github.com/godotengine/godot/issues/32185#issuecomment-538701139 with 3.2 RC 2, it exports and works fine.
