### ISSUE TITLE
rotation_degrees range is from -1080 do 1080

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#32204]
**Godot version:**
a1fcac640
**Issue description:**
The edit range from rotation_degrees in the inspector is from -1080 do 1080, but should be -360 to 360 for better usability (dragging the value just makes the node spin like crazy).

**Comment by TheWhiteLlama** [comment]
Nah, -180 to 180 is absolutely normal. The "spin like crazy" is resulting from a mathematical problem called "gimbal lock". You should probably use quaternions for the issue you're facing.

**Comment by Calinou** [comment]
What @Jummit meant is that the `rotation_degrees` range should be reduced, so that it's easier to drag it with the mouse. I think -360..360 would make for a good default range. However, larger/smaller values should still be enterable by adding `or_greater,or_lesser` to the property hint string.

**Comment by TheWhiteLlama** [comment]
ah, sorry I missunderstood it then

**Comment by AbnerSantos** [comment]
May I take this issue? I'm new to the repository and this seems simple enough to start contributing

**Comment by Calinou** [comment]
@AbnerSantos Sure :slightly_smiling_face:

Note that there are quite a lot of `rotation_degrees` properties out there. Make sure to change the hints everywhere for consistency.

**Comment by aaronfranke** [comment]
I asked @akien-mga about this a few months ago, here was the response:

![Untitled](https://user-images.githubusercontent.com/1646875/65377638-ddfe5980-dc7c-11e9-99e2-45228023c04a.png)

**Comment by Calinou** [comment]
@aaronfranke This is what the `or_greater,or_greater` links would allow (by manually entering the value) :slightly_smiling_face:
