### ISSUE TITLE
VideoStreamPlaybackGDNative audio buffer and video seek

### ISSUE THREAD

**Issue by starryalley** [godotengine/godot#32200]
**Godot version:**
3.1.1

**OS/device including version:**
mac osx/windows 10

**Issue description:**
I implemented the video seek function based on the great work of gdnative video decoder here: https://github.com/kidrigger/godot-videodecoder. See my fork at: 
https://github.com/starryalley/godot-videodecoder

I have to also fix the audio buffer and video seek in VideoStreamPlaybackGDNative class in order for that to work. 

I think there are mainly 2 issues:
1. when seeking video, we have to also update the time to the targeted seek time. Also we have to reset audio buffers when seeking. 

There is a special case where we want to seek to earlier playback time. In this case, update() has to do update_texture() in order for the native decoder (ffmpeg in this case) to update playback time, so that in the last while() loop in update() we will actually get to the correct video frame.

PR: https://github.com/godotengine/godot/pull/32199

2. The audio buffer sent to mix_callback() has a small bug when there are previous remains. The offset should be added for the mix_callback() to get the correct data.

PR: https://github.com/godotengine/godot/pull/32198

**Steps to reproduce:**
Compile and install https://github.com/starryalley/godot-videodecoder , create a project with VideoPlayer, use VideoStreamGDNative to play any video, and try video seeking.

**Minimal reproduction project:**
Sorry I don't have a small project here. Just create a VideoPlayer and use VideoStreamGDNative, and in _ready() try to play a video and then seek the video. Seek won't work.

**Comment by starryalley** [comment]
Both PRs got merged. I assume I can close this. Thanks!

**Comment by paneda1998** [comment]
thank you
I build ffmpeg and video-decoder and now every thing is good!
My os is ubuntu20.04

now i have mp4 support and also seek suppot
its great!
