### ISSUE TITLE
Inconsistent file sizes in binary .scn during import

### ISSUE THREAD

**Issue by shinyclaw** [godotengine/godot#32219]
I have found a strange issue when importing scene from .dae file using "Instanced Sub-Scenes" option. This option creates a separate scene (binary .scn) for each object in the imported .dae file. After the initial import, I have a .scn file with size, for example, 3411 bytes. Now, if I open this scene and save it again (using Save Scene As and .scn format) it has only 1437 bytes. Is it intended behavior? Below you can find the bigger version of the file, right after the import from .dae - try to save it manually.

[Cube.zip](https://github.com/godotengine/godot/files/3635655/Cube.zip)

**Comment by shinyclaw** [comment]
Another tip - if you convert it to a text format (.tscn), both versions, the smaller and the bigger, have identical size and content.

**Comment by KoBeWi** [comment]
@shinyclaw Can you still reproduce this in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or at least provide the original model? It's impossible to test importer with the imported model.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
