### ISSUE TITLE
HeightMapShape error with disabled Bullet module on project startup

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#32217]
**Godot version:**
3.2-alpha, 2add51d08

**OS/device including version:**
Windows 10

**Issue description:**
Opening a project without Bullet module compiled leads to these errors (I'm working on a 2D project).

```
ERROR: HeightMapShapeSW::set_data: Condition ' !d.has("cell_size") ' is true.
   At: servers\physics\shape_sw.cpp:1640
```
Doesn't seem to be related to above:
```
ERROR: RID_Owner<class BodySW>::get: Condition ' !p_rid.is_valid() ' is true. returned: 0
   At: .\core/rid.h:149
ERROR: PhysicsServerSW::body_attach_object_instance_id: Condition ' !body ' is true.
   At: servers\physics\physics_server_sw.cpp:671
ERROR: Invalid ID.
   At: servers\physics\physics_server_sw.cpp:1400
```

Also present along with #32216.

**Steps to reproduce:**
1. Compile with `scons platform=windows tools=yes target=debug bits=64 module_bullet_enabled=no`
2. Start up any project.

**Expected behavior:**
No errors on project startup when Bullet-related physics are not used in the project.

**Comment by Zylann** [comment]
`HeightMapShape` is only implemented in Bullet. `GodotPhysics` does not have it.

**Comment by Xrayez** [comment]
If Bullet module is disabled, ideally the `HeightMapShape` shouldn't even be included in the build, or should silently ignore it. I disabled Bullet module because it's only used for 3D stuff and I want to reduce binary size as well (`GodotPhysics` is the only option for 2D). These errors could possibly ruin export templates but not sure.

**Comment by Zylann** [comment]
If that error occurs without using the shape then yeah that's problematic

**Comment by Xrayez** [comment]
Figured this error:
```
ERROR: RID_Owner<class BodySW>::get: Condition ' !p_rid.is_valid() ' is true. returned: 0
   At: .\core/rid.h:149
ERROR: PhysicsServerSW::body_attach_object_instance_id: Condition ' !body ' is true.
   At: servers\physics\physics_server_sw.cpp:671
ERROR: Invalid ID.
   At: servers\physics\physics_server_sw.cpp:1400
```
is actually caused by `SoftBody` attempted to be created without Bullet module compiled.

**Comment by akien-mga** [comment]
Same reason as #32216 for another Bullet-only shape, so consolidating them in the same issue.
