### ISSUE TITLE
Light2D doesn't affect Polygon2D when attached to Bone2D

### ISSUE THREAD

**Issue by mikeant42** [godotengine/godot#32212]
**Godot version:** 3.1.1 stable

**OS/device including version:** Windows 10

**Issue description:** light stops casting on a polygon when it's attached to a bone on a skeleton

**Steps to reproduce:** Create a polygon, map the uv points, create a skeleton and bone, attach the polygon to the bone. When they are connected, the light stops casting on the polygon. I followed this guide: https://docs.godotengine.org/en/3.1/tutorials/animation/2d_skeletons.html

**Minimal reproduction project:**
[bugdemoproject.zip](https://github.com/godotengine/godot/files/3633927/bugdemoproject.zip)

**Comment by oiblank** [comment]
Has there been any progress on this?

**Comment by Sektor13** [comment]
Hi,

This is not completely fixed. Light2d work mostly, but in some angles and positions it stops.
I have attached sample TSCN file.
If player is rotated by 90 degrees, light only shows in the middle. 

Open corespoding TSCN and move LIGHT2d left or right.


[light2d_b13.zip](https://github.com/godotengine/godot/files/4568446/light2d_b13.zip)
