### ISSUE TITLE
Range subclasses (Slider, Spinbox...) can return -0

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#3221]
As mentioned in #3091, apparently due to a rounding error, nodes like ?Slider and SpinBox can return -0 if the min value is negative and rounded values is enabled.
This is a minor issue, since Godot recognizes (0 == -0) as true, but when converting to string, the sign will be preserved, which can lead to some minor awkwardness that would have to be addressed manually.

**Comment by reduz** [comment]
I'm not sure if I understand the problem, but may a solution be here:

https://github.com/godotengine/godot/blob/master/scene/gui/range.cpp#L83

adding something like if (p_val==0) p_val=0;

might fix it?

**Comment by hetdegon** [comment]
I have updated, but I still get -0 with spinboxes as seen in the "Active Defense" spinbox here:
![snapshot7](https://cloud.githubusercontent.com/assets/323651/12218768/3e77486c-b729-11e5-83f3-b000592246b4.png)

**Comment by hetdegon** [comment]
I just updated but I still get a -0 from a spinbox. At first I thought I made a mistake when building, but it's all up-to-date. This spinbox only has a min of -90 and max of 200 with no special attached code to it. 
Also it seems it will return -0 when going from 1 to 0, as well. (I am not sure, I think before it'd only return -0 when going from -1 to 0).
![snapshot7](https://cloud.githubusercontent.com/assets/323651/12218852/f4fb53c4-b72b-11e5-9eb8-d1f868eaa2c5.png)

**Comment by akien-mga** [comment]
> Also it seems it will return -0 when going from 1 to 0, as well. (I am not sure, I think before it'd only return -0 when going from -1 to 0).

See my comment in https://github.com/godotengine/godot/commit/b123bc4a2a9c07fcfd27a84109960bda158b3b9d#commitcomment-15342666, Math::round(0) actually returns -0, so a "positive zero" will always be translated to a "negative zero".

Reopen the issue though, as you still get the behaviour commit b123bc4 was supposed to fix.

**Comment by hetdegon** [comment]
Ah I see. I can't reopen the issue myself though.

**Comment by akien-mga** [comment]
Right, I meant to write "I'll reopen the issue" and do it, but somehow that's not what I did :D
