### ISSUE TITLE
WindowDialog constants not working.

### ISSUE THREAD

**Issue by MunWolf** [godotengine/godot#32211]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Home 10.0.17134

**Issue description:**
Window dialog constants don't update the look of the node.
The only constant that seems to work is the stylebox.

**Steps to reproduce:**
Create a WindowDialog node, and try and modify any of its custom properties other then "custom style". See that nothing changes.

**Minimal reproduction project:**
[simple_test.zip](https://github.com/godotengine/godot/files/3633916/simple_test.zip)

**Comment by bojidar-bg** [comment]
Can confirm on 037237f5183c4b8752f8a08d610bb9395ad294ea (master-ish).
Can't see why it would happen though.
