### ISSUE TITLE
Multiline textbox clips content with a lot of text

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#32229]
**Godot version:**
3.2
**OS/device including version:**
ArcoLinux
**Issue description:**
Multiline text boxes no longer allow you to scroll through its contents if you have more text than what can be displayed at once.

![image](https://user-images.githubusercontent.com/28724859/65367759-24f83a80-dbfc-11e9-9562-f33d2ceddb2a.png)

![image](https://user-images.githubusercontent.com/28724859/65367761-2d507580-dbfc-11e9-9cdf-a5279f63240c.png)

Neither scrolling nor arrow keys can get the rest of the text to display again.

**Comment by Chepee73** [comment]
Expanding a bit. It seems to be a problem with test wrap, when the number of lines of the wrapped text exceeds the numbers of visible lines they disappear, if you then hit enter and use the scrollbar the text appear again.


![test-edit-bug-2019-09-21_15 50 19](https://user-images.githubusercontent.com/13109127/65377938-18b9bf00-dc88-11e9-9729-1d69a34e79eb.gif)
