### ISSUE TITLE
(C#) Exceptions thrown in a signal handler are lost, the stack trace is a lie

### ISSUE THREAD

**Issue by mwerezak** [godotengine/godot#32227]
**Godot version:**
v3.1.1.stable.mono.offical

**OS/device including version:**
Ubuntu 18.04.3 LTS

**Issue description:**
When a C# script receives a signal and handles it in it's own (C#) method, if an exception is thrown you will never get to see it. Instead you get to see this stack trace (see below), which looks IDENTICAL to the stack trace you see when a signal is improperly connected (i.e. wrong node passed to Connect(), misspelled method name). It even references the same line, `Object.cs:329 System.Object Godot.Object.EmitSignal(System.String , System.Object[] )()`

![](https://i.imgur.com/SujxM9W.png)

I cannot express how much frustration this caused me. I went on a wild goose chase trying all kinds of things to figure out what was wrong, searched through the .cs files here on the godot repo, on and on...

Eventually I gave up and decided to just throw in an ugly kludge reference to the node that would be receiving the signal and just call the handler directly, so I can at least get on with my work. That's when I discovered that the stack trace was a LIE. Now I was able to see the real stack trace:

![](https://i.imgur.com/wqMHatC.png)

It turns out the exception was actually caused several stack frames inside the signal handler, being thrown by my code. But the error handling by Godot is terrible, which is what this issue is about. The stack trace, even the VS Code debugger gave me no indication that my code was even being executed, let alone where the error was coming from.

**Steps to reproduce:**
1. Create a mono/C# project.
2. Create a C# node to emit a signal, and a C# node to receive the signal.
3. Somewhere inside the signal handler, throw an exception.

**Minimal reproduction project:**
[Here](https://www.dropbox.com/s/os296yi02ykrxlc/GodotBug.zip?dl=0)

**Comment by WizzardMaker** [comment]
Probably related to #30208, where the stacktrace also gets cut off. I seems like it always cuts the stacktrace off, when we leave the C# space but the called Native Godot code later calls C# again. So any transition from C# -> Godot -> C# will only show you the first C# stack.

The only solution I currently have to debug is to debug with Visual Studio Code and let it break when an exception occurs.

**Comment by mwerezak** [comment]
@WizzardMaker I am using Visual Studio Code as well, but I haven't yet found a successful workaround. I'm fairly new to the VS Code tho. How do you set up your debugger.

Also yes, it seems to happen any time you come back to mono/C# from inside the engine. I just ran into this problem again with SceneTree.CallGroup()

**Comment by WizzardMaker** [comment]
To enable exception breakpoints in VS Code, you need to edit some settings in the Mono Debug Extension. Go to the Extension Menu, then click the gear icon of the Mono Debug entry. Go to the Configure Extension Settings entry. There you can edit the `settings.json`. You have to add the following code to enable the exception breaking for the most common exceptions:
```
    "mono-debug.exceptionOptions": {
        "System.Exception": "unhandled",
        "System.SystemException": "unhandled",
        "System.ArithmeticException": "unhandled",
        "System.ArrayTypeMismatchException": "unhandled",
        "System.DivideByZeroException": "unhandled",
        "System.IndexOutOfRangeException": "unhandled",
        "System.InvalidCastException": "unhandled",
        "System.NullReferenceException": "always",
        "System.OutOfMemoryException": "unhandled",
        "System.OverflowException": "unhandled",
        "System.StackOverflowException": "unhandled",
        "System.TypeInitializationException": "unhandled"
    },
```
This will let the debugger know that you want to break for every unhandled (not handled by a try-catch block) exception. You can add other exception types, but I think the most common will be the NullReferenceException, which will always break here. The possible values a key can have are: "always", "unhandled" and "never".

A full `settings.json` would look like this:
```
{
    "mono-debug.exceptionOptions": {
        "System.Exception": "unhandled",
        "System.SystemException": "unhandled",
        "System.ArithmeticException": "unhandled",
        "System.ArrayTypeMismatchException": "unhandled",
        "System.DivideByZeroException": "unhandled",
        "System.IndexOutOfRangeException": "unhandled",
        "System.InvalidCastException": "unhandled",
        "System.NullReferenceException": "always",
        "System.OutOfMemoryException": "unhandled",
        "System.OverflowException": "unhandled",
        "System.StackOverflowException": "unhandled",
        "System.TypeInitializationException": "unhandled"
    },
    "editor.formatOnSave": true,
    "window.zoomLevel": 0,
}
```

This still needs you to be attached to the process you want to debug, but I think you already know that :)
I hope this helps you in your exception hunting process!

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc5](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-5) or any later release?

**Comment by Duehok** [comment]
It's definitely there in 3.2.2. Exceptions are raised where the signal is emitted instead of in the method that the signal called and from where the exception comes. I usually add a bunch of stop points in the problematic signal handler to narrow down to the actual cause.

 Later than 3.2.2, I don't know and I won't check.

**Comment by akien-mga** [comment]
The example project in the OP seems to work fine in 3.2.4 beta 2 as far as I understand, it throws this exception:
```
E 0:00:02.431   void Rx.Kablamo(): System.Exception: Exception of type 'System.Exception' was thrown.
  <C++ Error>   Unhandled exception
  <C++ Source>  /home/akien/tmp/godot/bug/GodotBug/Rx.cs:31 @ void Rx.Kablamo()()
  <Stack Trace> Rx.cs:31 @ void Rx.Kablamo()()
                Rx.cs:27 @ void Rx.Three()()
                Rx.cs:23 @ void Rx.Two()()
                Rx.cs:19 @ void Rx.One()()
                Rx.cs:15 @ void Rx.HandleSignal()()
                :0 @ ()
                Object.cs:359 @ void Godot.Object.EmitSignal(System.String , System.Object[] )()
                Tx.cs:14 @ void Tx.Xmit()()
```

So this appears to be fixed.
