### ISSUE TITLE
Add "Make Resource Unique" flag (allow unique Materials on instanced nodes)

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3222]
_bugsquad edit:  The orginal title of this issue was "Shader material not unique on instanced nodes"_
_Changed title to reflect "feature proposal" status in reaction to reduz comment: https://github.com/godotengine/godot/issues/3222#issuecomment-168666945_

---

Related to #2162

When using shader on sprites (haven tested on other nodes), the shader is the same for every instanced sprite.
I have a setup where the sprites are instanced in the editor inside another scene. If the shader changes one of it's parameters it changes on every sprite instance.

RootNode
===> Instanced1
=====> Sprite(shader)
===> Instanced2
======> Sprite(shader)

This happens even if I use the "Make sub-resources unique" on the instanced node. The only way to achive this is going node by node and set the "Editable Children" flag to true. Then navigating to the sprite child node and setting "Make sub-resources unique" flag.

Is there a reason why the shader resources are not duplicated when duplicating nodes that are using them?

PS: here's a test project https://dl.dropboxusercontent.com/u/274954519/godot-issues/test_shaders.zip

**Comment by puppetmaster-** [comment]
I have had the same problem with LightOccluder2D and the sub-resources OccluderPolygon2D https://github.com/godotengine/godot/issues/2557

I would be cool if we can have a flag/settings to duplicate the sub-resources automatically.

**Comment by reduz** [comment]
Sub-resources are always shared automatically between instances, Will
eventually at some point add a flag so the resources are unique to the
scene, but the default behavior will not change.
For duplicated objects, you can use the property editor options to make
sub-resources unique

**Comment by kubecz3k** [comment]
@FEDE0D You were asking if there are reasons for this behaviour, well generally it's about performance and how GPU works... I will convert this issue into feature request to support an option with the "unique for scene flag". 
Workaround for now is to duplicate() material in ready  and set it instead of the original one.

**Comment by reduz** [comment]
Yeah, Unique for scene flag is doable, could try adding it in 2.1

**Comment by RandomShaper** [comment]
No workaround for 3D materials at the moment, right?

**Comment by RandomShaper** [comment]
I wasn't aware it's a `Resource` method. Perfect!

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
What's the status on this in the current master branch?

**Comment by mhilbrunner** [comment]
The work left to do seems to be in #10147 and #9037.

Close this, @akien-mga?

**Comment by RockyMadio** [comment]
duplicating the mesh will solve the problem

**Comment by sairam4123** [comment]
It doesn't solve the issue, I'm still having the same problem, shader materials are not being duplicated.

**Comment by sszigeti** [comment]
I have several instances of a TextureRect scene with a desaturation (grayscale) shader on it. Unless I have `set_material(get_material().duplicate())` in its `_ready` function all the instances are affected when the shader's uniform is used in an animation, despite having checked "Make Unique" for both the shader _and_ the material.

**Comment by sszigeti** [comment]
I have only discovered it with `v3.5.1.stable.official [6fed1ffa3]` that why [my hack above](https://github.com/godotengine/godot/issues/3222#issuecomment-912975389) makes the materials unique to the instance, I see the following errors in verbose mode:

    ERROR: GL ERROR: Source: OpenGL Type: Error     ID: 1280        Severity: High  Message: GL_INVALID_ENUM error generated. Invalid target.
       at: _gl_debug_print (drivers/gles2/rasterizer_gles2.cpp:137)
