### ISSUE TITLE
Editor crash when passing a C# object to AddImportPlugin()

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#32231]
**Godot version:** v3.1.1.stable.mono.official

**OS/device including version:** Windows 10 Pro

**Issue description:**
Doing this crash the editor on enabling the plugin. There is no error displayed (even with `--verbose`) and no error is logged in the `mono_logs/` file.
```csharp
#if TOOLS
using Godot;
using System;

[Tool]
public class MyImportPlugin : EditorImportPlugin
{
    ...
}

[Tool]
public class MyEditorPlugin : EditorPlugin
{
    private EditorImportPlugin importPlugin;

    public override void _EnterTree()
    {
        importPlugin = new MyImportPlugin();
        AddImportPlugin(importPlugin); // This line crash the editor
    }
}
#endif
```

Defining the import plugin in a `.gd` file and loading it like this works fine.
```csharp
[Tool]
public class MyEditorPlugin : EditorPlugin
{
    private EditorImportPlugin importPlugin;

    public override void _EnterTree()
    {
        GDScript script = ResourceLoader.Load($"{addonBasePath}/my_import_plugin.gd") as GDScript;
        importPlugin = script.New() as EditorImportPlugin;
        AddImportPlugin(importPlugin);
    }
}
```

**Comment by neikeq** [comment]
Looks like it's trying to call into C# (for `GetImporterName`) from the editor file system thread, which is not attached to the Mono runtime. I have to think what should be done about this. At worst we could attach the thread temporarily for such calls, but I would prefer a better solution. Once I'm done with this month's tasks I'll ask the people at Mono for some advice.
