### ISSUE TITLE
Uniformly scaling nodes with aspect != 1:1

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3224]
Scaling nodes using the SHIFT key to scale uniformly (keeping aspect) works right only when the node has an aspect of 1:1

When scaling with another aspect the node stretches in a non uniform way.
This issue is an oldie but I guess nobody reported it yet.

**Comment by akien-mga** [comment]
Had a quick look via the GH interface, and I wonder if removing this line might not be sufficient: https://github.com/godotengine/godot/blob/5be9ff7/tools/editor/plugins/canvas_item_editor_plugin.cpp#L1595

**Comment by akien-mga** [comment]
Reading the code a bit more, I think this chunk needs to be reactivated:
https://github.com/godotengine/godot/blob/5be9ff7/tools/editor/plugins/canvas_item_editor_plugin.cpp#L1554-L1565
(it's currently ```if(false && ...)``` so it never runs, but we want if for ```if(m.mod.shift)``` instead, and the other ```if(uniform)``` chunks could be dropped.

Currently SHIFT/uniform is interpreted as "apply the same delta on X and on Y" (using X as reference, so the Y drag is discarded), but that's not really what people expect when dragging IMO.

**Comment by akien-mga** [comment]
Er... actually I can't reproduce the issue :D What kind of nodes are you trying to scale?
I tried both a KinematicBody2D and an AnimatedSprite and it works just fine with Shift, even if the aspect is not 1:1.

**Comment by FEDE0D** [comment]
I tried with Sprite2d and its not working.

**Comment by akien-mga** [comment]
Ok I could reproduce with both Sprite and AnimatedSprite, it's just important to load a texture with aspect != 1:1 (previously I was tested with a 1:1 texture that I had scale). I should be able to find a fix.

**Comment by akien-mga** [comment]
It's harder than I thought to get the signs right in this stuff, as there are often sign changes during the drag but we don't want big jumps and funky behaviours. I'm starting to understand why the code chunk was disabled :D But I'll find a good solution.

**Comment by akien-mga** [comment]
@FEDE0D Could you try the above PR?

**Comment by FEDE0D** [comment]
Sure. When I get home I'll give it a try. :D

2016-01-05 20:18 GMT-03:00 Rémi Verschelde <notifications@github.com>:

**Comment by reduz** [comment]
feel free to merge if you like how it works
