### ISSUE TITLE
NinePatchSprite 2D Node [Feature Request]

### ISSUE THREAD

**Issue by topy72** [godotengine/godot#32240]
It would be cool to have a NinePatchSprite node which inherits from Node2D.
NinePatchRect already exists but it's a Control node and so it behaves differently from a Node2D.

NinePatchSprite would scale according to the parent. If it's child of a KinematicBody2D for example, it would not deform, but tile as expected.

I think it could be an improvement to create varying size platforms or obstacles easily in a game. You create the main obstacle class and then you instance it in your levels, and you can resize each instance without deforming the sprite.

**Comment by clayjohn** [comment]
This repository is for posting bug reports only. If you have a proposal please open it in the [godot-proposals](https://github.com/godotengine/godot-proposals) repo and fill out the proposal template there.

**Comment by KoBeWi** [comment]
> I think it could be an improvement to create varying size platforms or obstacles easily in a game.

In my case I used a tool script with export variable, which updated the underlying NinePatchRect to desired size. It just takes few lines, so new node type isn't really necessary.
