### ISSUE TITLE
Window title changes freezes gnome

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#32254]
I am unsure if this is a gnome bug, or a bug in Godot itself, but this is the code that causes it:

Putting this code in an autoload causes gnome to freeze when opening the activities overview:
```
func _process(delta):
	OS.set_window_title("Project Heartbeat - %.2f" % Engine.get_frames_per_second())
```

**Comment by dankan1890** [comment]
Why do you set the title for each frame ?

**Comment by Calinou** [comment]
It's generally not advised to set the window title every frame, as it will cause substantial performance decreases under certain window managers.

**Comment by EIREXE** [comment]
Yes that is what I am doing now.
