### ISSUE TITLE
Closing input dialog undims editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32264]
**Godot version:**
72d87cfbce137b8012e86f678c27f0f19a9771cf

**Steps to reproduce:**
1. Open Project Settings
2. Go to input map
3. Edit some action (by pressing the pencil icon)
4. Either accept or cancel the dialog
5. Let there be light!

**Comment by akien-mga** [comment]
Possibly related to #32197, cc @YeldhamDev.

**Comment by YeldhamDev** [comment]
I'm not able to reproduce this. Actually, this was the behaviour that I fixed in that commit.

**Comment by KoBeWi** [comment]
;___;
I encountered it in custom build and forgot to test in latest master. Sorry.

**Comment by avencherus** [comment]
@KoBeWi Had the same issue, for me it was a custom build between 3.1 and master.  Editor will freeze in a dimmed state while moving a file, if I create a New Folder in the Move dialog window, then move the file into that new folder.

Some other commit(s) along the way must be needed, but couldn't narrow anything down in the time I had to mess about with it.

No issues with that PR when following the master branch commits going forward.
