### ISSUE TITLE
I18N.West.dll File Missing On Exported Mono Project

### ISSUE THREAD

**Issue by WizzardMaker** [godotengine/godot#32260]
**Godot version:** 3.1.1 C# Mono

**OS/device including version:** Windows 10

**Issue description:**
We are working on an open source re implementation of an old game. That game uses the ANIS (1252) encoding for its text. This encoding is handled by I18N.West.dll. The project works fine inside the editor, but the exported project reports the error: `Encoding 1252 data could not be found. Make sure you have correct international codeset assembly installed and enabled.`. The error disappears, when you put the I18N.West.dll inside the game folder.

**Steps to reproduce:**
1. Create Empty Project
2. Add the following C# code:
```
Encoding.GetEncoding(1252);
```
3. Export and run the project
4. `Encoding 1252 data could not be found. Make sure you have correct international codeset assembly installed and enabled.` appears

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 builds?

**Comment by WizzardMaker** [comment]
With Godot 3.2 RC 1
Yes, the error `Unhandled Exception:
System.NotSupportedException: Encoding 1252 data could not be found. Make sure you have correct international codeset assembly installed and enabled.` still occurs.

I attached a sample project. It also contains an exported sample exe in the `.export` folder
[LocalTest.zip](https://github.com/godotengine/godot/files/4097976/LocalTest.zip)

**Comment by neikeq** [comment]
Looks like these I18N assemblies are loaded dynamically. We need to add an option to include them in the exported game.
