### ISSUE TITLE
using POSITION in frag shader causes GLSL compiler error

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#3226]
In a 3D fragment shader, when trying to use the POSITION variable, I get this error:

<pre><code>
ERROR: get_current_version: MaterialShaderGLES2: Program LINK FAILED:
Fragment info
-------------
0(846) : error C5052: gl_Position is not accessible in this profile
</code></pre>

I believe this is because gl_Position is only meant to be used as the output of the vertex shader, not the input to the fragment shader.  In the fragment shader, the position is available in gl_FragCoord.

**Comment by reduz** [comment]
will be rewritting most of this for 3.0, so for now not doing much 3D work

**Comment by x1212** [comment]
replacing the line
`	mode_replace_table[ShaderLanguage::SHADER_MATERIAL_FRAGMENT]["POSITION"]="gl_Position";`
with
`	mode_replace_table[ShaderLanguage::SHADER_MATERIAL_FRAGMENT]["POSITION"]="gl_FragCoord";`

in drivers/gles2/shader_compiler_gles2.cpp seems to solve that for me

**Comment by reduz** [comment]
this was rewritten in 3.0 and seems to work, closing
