### ISSUE TITLE
Text input nodes ignore shift

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#32268]
**Godot version:**
Commit 72d87cf

**OS/device including version:**
Debian sid

**Issue description:**
Text input nodes ignore shift (and, possibly, other modifier keys), making it impossible to enter shifted characters.

**Steps to reproduce:**
Enter text in the editor. Especially, shifted characters from the upper row like parentheses.

**Minimal reproduction project:**

**Comment by Ovnuniarchos** [comment]
**Additional notes:**
Seems to be IME-related, as the last system update deactivated my IME. Reactivating it solved the issue.
Even then, it seems that Godot needs an IME to detect shifted characters. Is that an acceptable behavior?

**Comment by akien-mga** [comment]
What is your IME?

**Comment by qarmin** [comment]
Commit which cause this issue - https://github.com/godotengine/godot/pull/31740

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
I can't reproduce any input issues with or without IME.

Please specify what's the exact configuration that doesn't work. Also, could you try inputting non-working keys into the attached project and provide the output.

[test_proj.zip](https://github.com/godotengine/godot/files/3652855/test_proj.zip)

**Comment by qarmin** [comment]
I use Kubuntu 19.04 without any bigger modifications
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     pl
```
CTRL, ALT and others seems to work, but only shift not working good(Shift - 1000015)
```
K:      41 U:      61 P: True == a 
K:      41 U:      61 P:False == a 
K: 1000015 U:       0 P: True ==  
K: 1000015 U:       0 P:False ==  
K: 1000015 U:       0 P: True ==  
K:      41 U:      61 P: True == a 
K:      41 U:      61 P:False == a 
K: 1000015 U:       0 P:False ==  
K: 1000016 U:       0 P: True ==  
K:      41 U:      61 P: True == a 
K:      41 U:      61 P:False == a 
K: 1000016 U:       0 P:False ==  
K: 1000018 U:       0 P: True ==  
K:      41 U:      61 P: True == a 
K:      41 U:      61 P:False == a 
K: 1000018 U:       0 P:False ==  
K:       0 U:     105 P: True == ą 
K:       0 U:     105 P: True == ą 
```

**Comment by bruvzg** [comment]
Tried few other distros including fresh install of Kubuntu 19.04 and still can't reproduce it. I have no clue what's wrong. Just as an educated guess, please try following patch:

```diff
diff --git a/platform/x11/os_x11.cpp b/platform/x11/os_x11.cpp
index 687981f32..7fa60d960 100644
--- a/platform/x11/os_x11.cpp
+++ b/platform/x11/os_x11.cpp
@@ -1767,6 +1767,7 @@ void OS_X11::handle_key_event(XKeyEvent *p_event, bool p_echo) {
 	XKeyEvent xkeyevent_no_mod = *xkeyevent;
 	xkeyevent_no_mod.state &= ~ShiftMask;
 	xkeyevent_no_mod.state &= ~ControlMask;
+	XLookupString(xkeyevent, str, 256, &keysym_unicode, NULL);
 	XLookupString(&xkeyevent_no_mod, str, 256, &keysym_keycode, NULL);
 
 	// Meanwhile, XLookupString returns keysyms useful for unicode.
@@ -1777,8 +1778,6 @@ void OS_X11::handle_key_event(XKeyEvent *p_event, bool p_echo) {
 		xmblen = 8;
 	}
 
-	keysym_unicode = keysym_keycode;
-
 	if (xkeyevent->type == KeyPress && xic) {
 
 		Status status;
```

If it won't help, #31740 should be reverted.

**Comment by qarmin** [comment]
With this path Shift works, but compilation show this wartning:
```
[ 34%] platform/x11/os_x11.cpp: In member function 'void OS_X11::handle_key_event(XKeyEvent*, bool)':
platform/x11/os_x11.cpp:1770:1: warning: value computed is not used [-Wunused-value]
 + XLookupString(xkeyevent, str, 256, &keysym_unicode, NULL);
```

**Comment by GammaGames** [comment]
Using Elementary OS (based on Ubuntu 18.04) and have the same issue. Thought I was crazy at first!

**Comment by dsnopek** [comment]
I'm also experiencing this issue. I tried the patch above (in https://github.com/godotengine/godot/issues/32268#issuecomment-535343289) and it fixed it for me! Thanks :-)
