### ISSUE TITLE
Build android template on windows fail due to problem with starting scons

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#32270]
**Godot version:**
master branch

**OS/device including version:**
Windows10 x64

**Issue description:**
building templates for android on Windows with [gradlew.bat](https://github.com/godotengine/godot/blob/master/platform/android/java/gradlew.bat) will fail with following errors
```
> Task :Godot:lib:compileGodotNativeLibsDebugArmv7 FAILED
> Task :lib:compileGodotNativeLibsDebug FAILED
> Task :Godot:lib:compileGodotNativeLibsReleaseArmv7 FAILED
> Task :lib:compileGodotNativeLibsRelease FAILED
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
* What went wrong:
Execution failed for task ':Godot:lib:compileGodotNativeLibsDebugArmv7'.
> A problem occurred starting process 'command 'scons''
```

**seems like it failing to run scons on windows when invoked without `.bat` extension in** [build.gradle](https://github.com/godotengine/godot/blob/master/platform/android/java/lib/build.gradle)
if you add `.bat` extension to `scons` then it finishes without errors.

how about testing if its windows and appending `.bat` extension.
```
	def winExt = ""
	if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
		winExt = ".bat"
	}

        def abiTaskNames = []
        // Creating gradle tasks to generate the native libraries for the supported abis.
        supportedAbis.each { abi ->
            def abiTaskName = taskName + abi.capitalize()
            abiTaskNames += abiTaskName
            tasks.create(name: abiTaskName, type: Exec) {
                executable "scons" + winExt
                args "--directory=${pathToRootDir}", "platform=android", "target=${releaseTarget}", "android_arch=${abi}", "-j4"
            }
        }
```

**Steps to reproduce:**
attempt to build android templates on windows

i believe @m4gr3d might be interested

**Comment by gamergamesz** [comment]
Same error

**Comment by m4gr3d** [comment]
@avril-gh Thanks for the tip. I've added the logic to PR #32269.

**Comment by avril-gh** [comment]
> Can you patch in PR #32269 and test the fix.

sure, will try out.

**Comment by avril-gh** [comment]
@m4gr3d
thanks, this has been resolved by https://github.com/godotengine/godot/pull/32269
