### ISSUE TITLE
tileset overwriting doesn't refresh the spritelist.

### ISSUE THREAD

**Issue by xaagaar** [godotengine/godot#3227]
If you save a tileset overwriting the old one, tilemap editor doesn't reflect changes until you exit and enter godot.

Overwriting the tileset without merging should refresh on the fly too. It's better than "Merge with existing" to keep the tilemap updated and organized.

**Comment by bojidar-bg** [comment]
:+1:

**Comment by reduz** [comment]
May not be that easy of a job, but let's see.. these are the tools to work with. Here is the code that generates the tileset from he scene: 

https://github.com/godotengine/godot/blob/master/tools/editor/plugins/tile_set_editor_plugin.cpp#L37

I think it's called from here:

https://github.com/godotengine/godot/blob/master/tools/editor/editor_node.cpp#L1321

If the tileset is already in use, the line that does ResourceLoader::load should just open the one used by the tilemap (Remember that in Godot all resources from disk are always loaded unique and once)

The Resource class, base of all resources, has a signal that is usually emitted when something in the resource changes. Not all resources emit this, but i think TileSet does or should do..   this should refresh the tile list, but seems it's not happening
