### ISSUE TITLE
Missing pixel when using draw_rect

### ISSUE THREAD

**Issue by muchitto** [godotengine/godot#32279]
**Godot version:**
3.2-dev (https://github.com/godotengine/godot/commit/5ffae0d299aa799c7787e01f3cfe5e377b78a411)

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
A small issue, but an issue nevertheless. When drawing with the `draw_rect` function, there is a missing pixel in the lower left corner. If using fill, the bug doesn't introduce itself. This happens on both GLES3 and GLES2.

![missing_pixel](https://user-images.githubusercontent.com/359786/65432751-6f5c0000-de24-11e9-9105-b997f64bdd6a.png)

**Steps to reproduce:**
Just put this script to a Node2D: 
```
extends Node2D

func _draw():
	draw_rect(Rect2(1, 1, 100, 100), Color(0.5, 0.8, 0.5), false)
```

**Minimal reproduction project:**
[DrawRectBug.zip](https://github.com/godotengine/godot/files/3642497/DrawRectBug.zip)

**Comment by Zylann** [comment]
Is it always missing if you draw that rectangle at different positions, and with decimal coordinates?

**Comment by Calinou** [comment]
I can reproduce this on commit https://github.com/godotengine/godot/commit/a226d63f6815836284f947ccc56b688448381f84. Note that the missing pixel will not always be in the bottom-left corner; it depends on the rectangle's position (see demo project below).

**Demo project:** [DrawRectBug_with_anim.zip](https://github.com/godotengine/godot/files/3642727/DrawRectBug_with_anim.zip)

**Comment by CptPotato** [comment]
A half pixel offser is required to make this work: `draw_rect(Rect2(0.5, 0.5, 100.5, 100.5), Color(0.5, 0.8, 0.5), false)`
(though, pixel snap has to be disabled)

Note that this only applies to unfilled rectangles, as mentioned in the original post.

**Comment by muchitto** [comment]
> Is it always missing if you draw that rectangle at different positions, and with decimal coordinates?

If I'm using integer coordinates, then it's always in the bottom left corner. If I'm using decimal coordinates, then it shifts between the bottom left and bottom right corner.
Tested with this script (and tried changing the `increment` to `0.5`, when testing the decimal coordinates):
```
extends Node2D

var pos_x := 0.0
var pos_y := 0.0
var increment := 1

func _draw():
	draw_rect(Rect2(pos_x, pos_y, 100, 100), Color(0.5, 0.8, 0.5), false)

func _process(delta):
	if Input.is_action_pressed("ui_up"):
		pos_y -= increment
	elif Input.is_action_pressed("ui_down"):
		pos_y += increment
		
	if Input.is_action_pressed("ui_left"):
		pos_x -= increment
	elif Input.is_action_pressed("ui_right"):
		pos_x += increment
		
	update()
```

**Comment by Xrayez** [comment]
Anti-aliased version:

`draw_rect(Rect2(1, 1, 100, 100), Color(0.5, 0.8, 0.5), false, 1.0, true)`

![antialiased-rect](https://user-images.githubusercontent.com/17108460/65445020-f5367600-de39-11e9-8283-505731e2d804.png)

**Comment by Calinou** [comment]
For the record, the `width` and `antialiased` `draw_rect()` parameters were added in #30461.
