### ISSUE TITLE
Cannot compile Godot with Mono: Windows certificate authentication issues.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#32284]
**Godot version:**
I've tried the 3.1 tag and e205cbb, both with and without my own custom changes for a C# feature I'm working on.

**OS/device including version:**
Windows 10

**Issue description:**
When attempting to make a Mono build of Godot, following the procedure in the docs, I encounter certificate authentication issues that I do not know how to fix.

**Steps to reproduce:**
1. Clone the godot repository.
1. Follow the instructions on building Godot with Mono support.
     1. Get prerequisite libraries and programs
     1. Run `mozroots --import --sync`. Downloads 155 root certificates. But it also states that it is deprecated and that you should use `cert-sync` instead, which expects an argument in a "PEM" format.
     1. No documentation mentions anything about this. There is no indication of anything following the PEM format, so I don't know what I would plug into `cert-sync` anyway.
1. Attempt to build godot with `scons platform=windows module_mono_enabled=yes mono_glue=no tools=yes` (I used `-j6` too).

Observe the following error:

    [100%] MSBuild auto-detection: using msbuild version '15.0' from 'C:\Program Files\Mono\lib\mono\msbuild\15.0\bin'.
    WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
    Restoring NuGet package DotNet.Glob.2.1.1.
    WARNING: Unable to find version '2.1.1' of package 'DotNet.Glob'.
      C:\Users\Will_Nations\.nuget\packages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Users\Will_Nations\.nuget\packages\'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
      An error occurred while sending the request
      Error: TrustFailure (Authentication failed, see inner exception.)
      Authentication failed, see inner exception.
      Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
        at D:\j\workspace\build-package-win-mono\2019-02\external\boringssl\ssl\handshake_client.c:1132

    WARNING: Unable to find version '2.1.1' of package 'DotNet.Glob'.
      C:\Users\Will_Nations\.nuget\packages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Users\Will_Nations\.nuget\packages\'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
      An error occurred while sending the request
      Error: TrustFailure (Authentication failed, see inner exception.)
      Authentication failed, see inner exception.
      Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
        at D:\j\workspace\build-package-win-mono\2019-02\external\boringssl\ssl\handshake_client.c:1132

    Errors in packages.config projects
        Unable to find version '2.1.1' of package 'DotNet.Glob'.
          C:\Users\Will_Nations\.nuget\packages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Users\Will_Nations\.nuget\packages\'.
          C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
          https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
          An error occurred while sending the request
          Error: TrustFailure (Authentication failed, see inner exception.)
          Authentication failed, see inner exception.
          Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
            at D:\j\workspace\build-package-win-mono\2019-02\external\boringssl\ssl\handshake_client.c:1132

    NuGet Config files used:
        C:\Users\Will_Nations\AppData\Roaming\NuGet\NuGet.Config
        C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

    Feeds used:
        C:\Users\Will_Nations\.nuget\packages\
        https://api.nuget.org/v3/index.json
        C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    scons: *** [bin\GodotSharp\Tools\GodotSharpTools.dll] RuntimeError : GodotSharpTools: NuGet restore failed
    Traceback (most recent call last):
      File "C:\Users\Will_Nations\Documents\GitHub\godot\modules\mono\SCsub", line 312, in mono_build_solution
        subprocess.check_call([nuget_path, 'restore', sln_path])
      File "C:\Users\Will_Nations\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 328, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Program Files\\Mono\\bin\\nuget.bat', 'restore', 'C:\\Users\\Will_Nations\\Documents\\GitHub\\godot\\modules\\mono\\editor\\GodotSharpTools\\GodotSharpTools.sln']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\will_nations\appdata\local\programs\python\python37\lib\site-packages\scons-3.0.1\SCons\Action.py", line 1197, in execute
        result = self.execfunction(target=target, source=rsources, env=env)
      File "C:\Users\Will_Nations\Documents\GitHub\godot\modules\mono\SCsub", line 314, in mono_build_solution
        raise RuntimeError('GodotSharpTools: NuGet restore failed')
    RuntimeError: GodotSharpTools: NuGet restore failed
    scons: building terminated because of errors.

**Comment by willnationsdev** [comment]
Nevermind. Thanks to @aaronfranke . Seems this was a duplicate of #25811. Docs definitely need to be updated.

**Comment by willnationsdev** [comment]
@neikeq Well, I'd thought it was a duplicate, but this seems like a different error message. However, @aaronfranke's suggestion of adding the nuget dependency did fix the problem. You wanted to know if people still have the issue though, so ^ here is what I was dealing with.

Here is the information you requested in #25811:

I am on Windows 10.
"Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework"
"NuGet Version: 5.1.0.6013"
"I've tried the 3.1 tag and e205cbb \[a recent master\], both with and without my own custom changes for a C# feature I'm working on."

I cloned the Godot repo.
`scons platform=windows -j6`
`scons platform=windows vsproj=yes`
^ I usually do development in Visual Studio 2017/2019. Will build and debug through the GUI.

For the mono build, I went through the documentation explicitly.
`mozroots --import --sync`
"warning, deprecated. Supposed to use cert-sync. 155 root certificates added."
`scons platform=windows module_mono_enabled=yes mono_glue=no -j6`
^ Triggers the error message above.

**Comment by piratesephiroth** [comment]
mozroots is giving this deprecation warning for years now but it still works fine.

but anyway:
>You can just download curl's list of certificates from https://curl.haxx.se/ca/cacert.pem and then import the list via "cert-sync --user cacert.pem".

from https://mono.github.io/mail-archives/mono-list/2017-April/052431.html

**Comment by willnationsdev** [comment]
@piratesephiroth I'll try that out and get back to you guys later tonight. If that fixes it, then it'd just be a docs fix.

**Comment by piratesephiroth** [comment]
By the way, I'm on Windows 10 as well, with Visual Studio 2019. Both installed a few weeks ago.
The mozroots command was enough to get the mono version of Godot to compile.

**Comment by willnationsdev** [comment]
Looks like that didn't work. 139 new root certificates were added to the trust store. Then I built on master and got this:

    [ 96%] build_godot_tools_project_editor(["bin\GodotSharp\Tools\GodotTools.ProjectEditor.dll", "bin\GodotSharp\Tools\DotNet.Glob.dll", "bin\GodotSharp\Tools\GodotTools.Core.dll", "bin\GodotSharp\Tools\GodotTools.ProjectEditor.pdb", "bin\GodotSharp\Tools\GodotTools.Core.pdb"], [])
    [ 97%] NuGet path: C:\Program Files\Mono\bin\nuget.bat
    [100%] progress_finish(["progress_finish"], [])
    [100%] Restoring NuGet package DotNet.Glob.2.1.1.
    WARNING: Unable to find version '2.1.1' of package 'DotNet.Glob'.
    C:\Users\Will\.nuget\packages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Users\Will\.nuget\packages\'.
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
    An error occurred while sending the request
    Error: TrustFailure (Authentication failed, see inner exception.)
    Authentication failed, see inner exception.
    Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
        at D:\j\workspace\build-package-win-mono\2019-02\external\boringssl\ssl\handshake_client.c:1132

    WARNING: Unable to find version '2.1.1' of package 'DotNet.Glob'.
    C:\Users\Will\.nuget\packages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Users\Will\.nuget\packages\'.
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
    An error occurred while sending the request
    Error: TrustFailure (Authentication failed, see inner exception.)
    Authentication failed, see inner exception.
    Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
        at D:\j\workspace\build-package-win-mono\2019-02\external\boringssl\ssl\handshake_client.c:1132


    Errors in packages.config projects
        Unable to find version '2.1.1' of package 'DotNet.Glob'.
        C:\Users\Will\.nuget\packages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Users\Will\.nuget\packages\'.
        C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'DotNet.Glob.2.1.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
        https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
        An error occurred while sending the request
        Error: TrustFailure (Authentication failed, see inner exception.)
        Authentication failed, see inner exception.
        Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
            at D:\j\workspace\build-package-win-mono\2019-02\external\boringssl\ssl\handshake_client.c:1132

    NuGet Config files used:
        C:\Users\Will\AppData\Roaming\NuGet\NuGet.Config
        C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

    Feeds used:
        C:\Users\Will\.nuget\packages\
        https://api.nuget.org/v3/index.json
        C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    scons: *** [bin\GodotSharp\Tools\GodotTools.ProjectEditor.dll] RuntimeError : 'nuget restore' exited with error code: 1
    Traceback (most recent call last):
    File "D:\Source\GitHub\godot\modules\mono\build_scripts\solution_builder.py", line 148, in run_command
        subprocess.check_call(args)
    File "C:\Users\Will\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Program Files\\Mono\\bin\\nuget.bat', 'restore', 'D:\\Source\\GitHub\\godot\\modules\\mono\\editor/GodotTools\\GodotTools.ProjectEditor\\packages.config', '-PackagesDirectory', 'D:\\Source\\GitHub\\godot\\modules\\mono\\editor/GodotTools\\GodotTools.ProjectEditor\\packages']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "c:\users\will\appdata\local\programs\python\python37\lib\site-packages\scons\SCons\Action.py", line 1202, in execute
        result = self.execfunction(target=target, source=rsources, env=env)
    File "D:\Source\GitHub\godot\modules\mono\build_scripts\godot_tools_build.py", line 55, in build_godot_tools_project_editor
        os.path.join(csproj_dir, 'packages'))
    File "D:\Source\GitHub\godot\modules\mono\build_scripts\solution_builder.py", line 167, in nuget_restore
        run_command(nuget_path, ['restore'] + list(args), name='nuget restore')
    File "D:\Source\GitHub\godot\modules\mono\build_scripts\solution_builder.py", line 152, in run_command
        raise RuntimeError("'%s' exited with error code: %s" % (name, e.returncode))
    RuntimeError: 'nuget restore' exited with error code: 1
    Creating library bin\godot.windows.tools.64.mono.lib and object bin\godot.windows.tools.64.mono.exp
    scons: building terminated because of errors.

**Comment by piratesephiroth** [comment]
OK, I just wiped all the certificates from `%appdata%\.mono\certs\Trust` (and also from `%programdata%\.mono\certs\Trust`, I guess they get copied there at some point).
I've imported curl's certificates with cert-sync from and I'm gonna try compiling the latest commit of mono Godot right now.

**Comment by piratesephiroth** [comment]
Yep, nuget download the package just fine and compilation went as expected.

![image](https://user-images.githubusercontent.com/10672233/65742453-96396100-e0c6-11e9-80f2-f89637bf0979.png)

So I don't know what's going on with your machine...

**Comment by willnationsdev** [comment]
Well, if I manually call nuget myself, then it works. It only DOESN'T work when using scons. As I mentioned, I was able to resolve the problem by following aaronfranke's suggestion in the other Issue, but neikeq said that we shouldn't have to do that, so I re-opened this Issue to help debug this use case of it failing without the user manually calling nuget.

**Comment by piratesephiroth** [comment]
I'm suire this is something unrelated. Maybe you have more than one nuget installed?
The certificates aren't the issue as mozroots and cert-sync do what they should.

**Comment by neikeq** [comment]
@willnationsdev Which nuget are you running? The one that comes with Mono or another?

**Comment by willnationsdev** [comment]
@neikeq I'm not really sure. I am running it from the VS x64 native command prompt, but I also added Mono\bin to my PATH. I would assume that the nuget I call from there would be the one that comes with Visual Studio whereas scons would be trying to run the one that came with Mono (my guess?). Is there a command on windows that spits out the path of an executable you provide to it?

**Comment by willnationsdev** [comment]
Well, never mind. Apparently, I had it working at one point or another when I tried nuget directly, but now that isn't working.

I tried what @piratesephiroth suggested. Cleared the Trusts in those directories, re-ran mozroots and cert-sync with the curl pem, and cleared the local nuget cache. I then tried going to the `\modules\mono\editor\GodotTools\` directory and ran `nuget restore GodotTools.sln` as well as `nuget install DotNet.Glob -Version 2.1.1`. Both errored with `CERTIFICATE_VERIFY_FAILED`.

I am really at a loss as to how to fix this problem now. Not sure why it worked that one time.

**Comment by neikeq** [comment]
Perhaps it worked the first because you ran it from the Visual Studio Command Prompt?

**Comment by willnationsdev** [comment]
@neikeq No, I have always been doing that at every stage.

**Comment by piratesephiroth** [comment]
Also you don't need to run scons from the visual studio command prompt anymore

**Comment by willnationsdev** [comment]
Oh, ok. Good to know.

**Comment by piratesephiroth** [comment]
Try uninstalling mono and then installing again. MAYBE it helps... 😜

**Comment by piratesephiroth** [comment]
Uh, I think it works now. Try using `cert-sync` again,
It creates an additional folder that I wasn't seeing before (and that mozroots doesn't create), called new-certs.
After that, nuget begins to work agaain.

**Comment by akien-mga** [comment]
I can confirm that this issue is reproducible on Windows 10, with VS 2017, Mono 6.6.0.158 and Godot's current master branch.

I tried the document `mozroots` method, and as described here it doesn't seem sufficient. Whether I'm in the Mono command prompt or Git Bash, it fails the same way.

I'll try the updated instructions in godotengine/godot-docs#2821 now.

**Comment by KoukouStudios** [comment]
Having the same issue here. Unable to build Godot v3.2.1 with mono

**Comment by willnationsdev** [comment]
@KoukouStudios Just to be sure, can you walk people through exactly what you did? Were you looking at the `latest`, `stable`, or `3.2` version of the documentation or an earlier version? Did you use `mozroots` or `cert-sync`?

**Comment by KoukouStudios** [comment]
> @KoukouStudios Just to be sure, can you walk people through exactly what you did? Were you looking at the `latest`, `stable`, or `3.2` version of the documentation or an earlier version? Did you use `mozroots` or `cert-sync`?

I used scons on windows. Managed to build it last night by running cmd with admin rights but then exe would crash. I can't recall the error I'm afraid but I couldn't spare any more time so I ended up quiting the idea of c# and started working with c++ and gdscript. Not a big fan of gdscript but it gets the job done well :)
