### ISSUE TITLE
MeshLibrary get_item_preview not working on Android

### ISSUE THREAD

**Issue by Icaro-Lima** [godotengine/godot#32287]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Android 9 / moto g(6) play XT1922-5

**Issue description:**
On Windows when using the `MeshLibrary.get_item_preview(x)` function everything works perfectly. On Android only a black image is returned.

I am using GLES 3.

**Steps to reproduce:**
1. Create a MeshLibrary with some items.
2. Create a script inside a Button with `export(MeshLibrary) var meshlib`
3. Inside `_ready`, call `icon = meshlib.get_item_preview(i)`

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc5](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-5) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
