### ISSUE TITLE
NinePatchRect don't work with round corner

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#32292]
**Godot version:**
3.1.1

**OS/device including version:**
macos10.14.4

**Issue description:**
I can't modify the 9patchrect with editor easily. And It also don't show the corner. I take a capture video of operation.

**Steps to reproduce:**
create and modify the component

[9patch.mov.zip](https://github.com/godotengine/godot/files/3644357/9patch.mov.zip)

**Comment by avencherus** [comment]
@KoBeWi has made recent fixes with https://github.com/godotengine/godot/pull/32180.

You might want to check out a recent master build.

**Comment by zszen** [comment]
Offical please publish a release version instead of custom build. ;p
