### ISSUE TITLE
Default Angular Damp in Project Settings Disallows Fractional Input

### ISSUE THREAD

**Issue by amisner2k** [godotengine/godot#32294]
**Godot version:**
3.1.1.stable.official

**OS/device including version:**
Windows 10
Version	10.0.18362 Build 18362

**Issue description:**
In Project Settings under Physics > 2d, the "Default Angular Damp" text input disallows entering fractional input. Entering any fractional value such as 0.3 or 0.5 will cause the input to be rounded to the nearest whole number.

**Steps to reproduce:**
1. In any project, go to Project Settings > Physics > 2d
2. Type 0.3 in box and tab out...value gets rounded down to 0
3. Type 0.5 in box and tab out...value gets rounded up to 1

**Minimal reproduction project:**
Should occur in any project.

![image](https://user-images.githubusercontent.com/55228705/65476383-953ed000-de37-11e9-9033-05343c6ce2b2.png)

**Comment by cbolgiano** [comment]
I can look into this one.

**Comment by cbolgiano** [comment]
Pull request is out.
