### ISSUE TITLE
GDScript type error when Tween.interpolate_property takes Engine as argument

### ISSUE THREAD

**Issue by anissen** [godotengine/godot#32302]
**Godot version:**
72d87cfbce137b8012e86f678c27f0f19a9771cf

**OS/device including version:**
macOS 10.14.6

**Issue description:**
In GDScript, the following will cause a type error ("Engine is not of type Object"):
```gdscript
Tween.new().interpolate_property(Engine, "time_scale", ...
```

However, the following code works fine:
```gdscript
var tween = Tween.new()
tween.interpolate_property(Engine, "time_scale", ...
```
```gdscript
var engine = Engine
tween.interpolate_property(engine, "time_scale", ...
```

See comments in https://github.com/godotengine/godot/issues/27131 for more discussion.

**Steps to reproduce:**
See above.

**Minimal reproduction project:**
N/A

**Comment by bojidar-bg** [comment]
Would be solved by #26990 / side effect of #14872.
