### ISSUE TITLE
Compiling for iphone arch=x86_64 causes errors

### ISSUE THREAD

**Issue by mani144** [godotengine/godot#32301]
**Godot version:**
3.1.1
**OS/device including version:**
iOS MAC
**Issue description:**
I'm trying to build a custom modules for iOS, and i have successfully built arm and arm64 without any errors using the following commands
$ scons p=iphone tools=no target=release arch=arm
$ scons p=iphone tools=no target=release arch=arm64
however when i try to build a x86_64 version, i got this error :

scons: Building targets ...
[ 26%] Compiling ==> modules/bullet/area_bullet.cpp
In file included from modules/bullet/area_bullet.cpp:31:
In file included from modules/bullet/area_bullet.h:34:
In file included from modules/bullet/collision_object_bullet.h:40:
In file included from thirdparty/bullet/LinearMath/btTransform.h:18:
In file included from thirdparty/bullet/LinearMath/btMatrix3x3.h:18:
thirdparty/bullet/LinearMath/btVector3.h:335:7: error: argument value 10880 is outside the valid range [0, 255] [-Wargument-outside-range]
                y = bt_splat_ps(y, 0x80);
                    ^~~~~~~~~~~~~~~~~~~~
thirdparty/bullet/LinearMath/btVector3.h:43:29: note: expanded from macro 'bt_splat_ps'
#define bt_splat_ps(_a, _i) bt_pshufd_ps((_a), BT_SHUFFLE(_i, _i, _i, _i))
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/bullet/LinearMath/btVector3.h:41:33: note: expanded from macro 'bt_pshufd_ps'
#define bt_pshufd_ps(_a, _mask) _mm_shuffle_ps((_a), (_a), (_mask))
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/xmmintrin.h:2608:11: note: expanded from macro '_mm_shuffle_ps'
  (__m128)__builtin_ia32_shufps((__v4sf)(__m128)(a), (__v4sf)(__m128)(b), \
          ^
In file included from modules/bullet/area_bullet.cpp:31:
In file included from modules/bullet/area_bullet.h:34:
In file included from modules/bullet/collision_object_bullet.h:40:
In file included from thirdparty/bullet/LinearMath/btTransform.h:18:
thirdparty/bullet/LinearMath/btMatrix3x3.h:910:14: error: argument value 10880 is outside the valid range [0, 255] [-Wargument-outside-range]
        __m128 vk = bt_splat_ps(_mm_load_ss((float*)&k), 0x80);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/bullet/LinearMath/btVector3.h:43:29: note: expanded from macro 'bt_splat_ps'
#define bt_splat_ps(_a, _i) bt_pshufd_ps((_a), BT_SHUFFLE(_i, _i, _i, _i))
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/bullet/LinearMath/btVector3.h:41:33: note: expanded from macro 'bt_pshufd_ps'
#define bt_pshufd_ps(_a, _mask) _mm_shuffle_ps((_a), (_a), (_mask))
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/xmmintrin.h:2608:11: note: expanded from macro '_mm_shuffle_ps'
  (__m128)__builtin_ia32_shufps((__v4sf)(__m128)(a), (__v4sf)(__m128)(b), \
          ^
2 errors generated.
scons: *** [modules/bullet/area_bullet.iphone.opt.x86_64.o] Error 1
scons: building terminated because of errors.

this error only occurred when i try to compile x86_64 version

**Comment by akien-mga** [comment]
What Xcode version are you using?

**Comment by santouits** [comment]
https://github.com/godotengine/godot/issues/29503
It was fixed in master? Don't know if new bullet versions are cherrypicked for 3.1
If not, apply the patch in your code https://github.com/bulletphysics/bullet3/pull/2232

**Comment by akien-mga** [comment]
> #29503
It was fixed in master? Don't know if new bullet versions are cherrypicked for 3.1
If not, apply the patch in your code bulletphysics/bullet3#2232

Thanks, that's indeed the same issue. I don't plan to update Bullet in the 3.1 branch, as it tracks the latest stable version there (2.88). So I'll backport the patch.

**Comment by mani144** [comment]
@akien-mga @santouits  Thank you , i will close the issue
