### ISSUE TITLE
Android crash when purchasing 'android.test.canceled' test IAP product

### ISSUE THREAD

**Issue by johngirvin** [godotengine/godot#32304]
**Godot version:**
3.1.1.stable.official

**OS/device including version:**
Archos Alba 7"
Android 5.1

**Issue description:**
Attempting IAP with 'android.test.canceled' product ID results in an application crash.
This does not happen with a valid product ID when the IAP flow is cancelled by the user.

**Steps to reproduce:**
Edit the android_iap demo project to change product id to 'android.test.canceled'.
```
func button_purchase():
	iap.purchase("android.test.canceled")
```
Run the project on an Android device with billing permissions enabled.
Click "Purchase In App".
Proceed through the standard IAP process.
Application will stop after purchase is complete.

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/tree/master/misc/android_iap
Change product id to 'android.test.canceled'

**Comment by volzhs** [comment]
for reference, https://developer.android.com/google/play/billing/billing_testing#billing-testing-static

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.
