### ISSUE TITLE
Error when trying to compile Godot with c#

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#32311]
**Godot version:**
Latest dev

**OS/device including version:**
Windows 10
compile with: `scons p=windows tools=yes module_mono_enabled=yes mono_glue=no`
![image](https://user-images.githubusercontent.com/1850856/65528809-bd910200-defd-11e9-91b1-7cee71620029.png)

**Issue description:**
I get the error demonstrated in the picture when trying to compile Godot with mono module enabled:
![image](https://user-images.githubusercontent.com/1850856/65528465-1ad88380-defd-11e9-95bc-10342bdd6c7b.png)

**Comment by piratesephiroth** [comment]
have you imported the certificates with
`mozroots --import --sync`

**Comment by Calinou** [comment]
@zaksnet Bump :slightly_smiling_face: See @piratesephiroth's reply.

**Comment by zaksnet** [comment]
Sorry for the late reply @Calinou , @piratesephiroth . Yes i did run `mozroots --import --sync` from mono command line and it seemed to run without an issue so i though its done. When i tried running mozroots.exe from its installed location though i get the following error:
![Screenshot_1](https://user-images.githubusercontent.com/1850856/65863629-27376300-e379-11e9-95d8-239de599f3f7.png)

**Comment by piratesephiroth** [comment]
Do not run the executables directly.
Add mono to the system path (like `C:\Program Files\Mono\bin`) so you run the bat scripts from anywhere.
They'll then run using the mono runtime as intended.

**Comment by zaksnet** [comment]
> Do not run the executables directly.
> Add mono to the system path (like `C:\Program Files\Mono\bin`) so you can run the bat scripts from anywhere.
> They'll then run using the mono runtime as intended.

@piratesephiroth I understand. As i said above, i did run `mozroots --import --sync` from the `Mono command prompt` where the mono path is prepended:
![Screenshot_5](https://user-images.githubusercontent.com/1850856/65872078-7638c480-e388-11e9-853d-db7ddf957c61.png)

But besides that, mono path is added at the system path already:
![Screenshot_4](https://user-images.githubusercontent.com/1850856/65871990-42f63580-e388-11e9-8ae3-7dba61dc62c8.png)
So assuming that `mozroots --import --sync` this command is working properly, i guess thats not my issue.

**Comment by zaksnet** [comment]
> what happens if you run mozroots from a regular command prompt?
> 
> This is what it looks like when it's working
> ![image](https://user-images.githubusercontent.com/10672233/65873008-5b4e5c00-e358-11e9-9f09-f3321eb0c670.png)

It is empty, no error or success message:
![Screenshot_6](https://user-images.githubusercontent.com/1850856/65954339-769b9300-e44e-11e9-923b-64cee1ae4907.png)
That is the case when i run the command from Mono cmd or a normal cmd.
I tried reinstalling Mono, reinstalling .NET but nothing helped.

**Comment by piratesephiroth** [comment]
Try uninstalling mono, also verify if their installation directory is completely gone.
Maybe reinstalling it then will fix the problem.

**Comment by piratesephiroth** [comment]
Upgrade to the latest stable mono (v6.4.0) if you're using something older.

Then download this certificate collection:
https://curl.haxx.se/ca/cacert.pem

Then run cert-sync to install them
`cert-sync --user cacert.pem`

**Comment by zaksnet** [comment]
This was a folder permission issue (i think). Anyway, the steps i took to fix it was:
- Reset folder permissions with `icacls /t /reset` (Although just removing the folder after uninstall should be enough?).
- Deleted `%appData%/.mono` folder which contained the saved certificates.

Thank you @piratesephiroth for the help.
