### ISSUE TITLE
GLTF2 Crash on values index access

### ISSUE THREAD

**Issue by fire** [godotengine/godot#32316]
**Godot version:**
0c3335d 

**OS/device including version:**
Windows 10

**Issue description:**
Crash bug.

https://github.com/godotengine/godot/blob/master/editor/import/editor_scene_importer_gltf.cpp#L2833

`times.size() != values.size()`

**Steps to reproduce:**

Some models can have invalid data. Can't distribute model.

**Minimal reproduction project:**

**Comment by fire** [comment]
May be related to https://github.com/godotengine/godot/pull/32306

**Comment by marstaik** [comment]
Have you verified if that fixes the issue?

**Comment by fire** [comment]
I can't reproduce this bug anymore.
