### ISSUE TITLE
"Orphan Resource Manager" should be converted into "Resource Manager" with "show orphans only" option

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3231]
I'm not sure why there is no 'Resource Manager' tool, it should work very similar to how Orphan Resource Manager works but should also allow to check dependencies for scenes that are not orphans. I mean, it's currently impossible to quickly check where given scene is used. 
Also in this case I would suggest to change name from "Resources Manager" to **Dependencies Manager**.

**Comment by reduz** [comment]
did you try the filesystem dock? you can check there who is using a given
resource

**Comment by kubecz3k** [comment]
@reduz Thanks a lot! And sorry for struggle. Seen this when it was added, but forgot about it in need :)
