### ISSUE TITLE
GLTF2 Failure to import

### ISSUE THREAD

**Issue by fire** [godotengine/godot#32314]
**Godot version:**

0c3335d / Custom branch

**OS/device including version:**

Windows 10

**Issue description:**

"Make sure all parents of a multi-rooted skin are the SAME" failure to import.

**Steps to reproduce:**

Export via Maya2GLTF. Ping me if you need to create it.

**Minimal reproduction project:**

Causes "Make sure all parents of a multi-rooted skin are the SAME".

[aquarius-astellia-maya2gltf.zip](https://github.com/godotengine/godot/files/3648955/aquarius-astellia-maya2gltf.zip)

https://sketchfab.com/3d-models/aquarius-astellia-622bde32272d4545b89cc09113ca7439

**Comment by marstaik** [comment]
Should be fixed with that PR ^

**Comment by fire** [comment]
Worked, can close after pr is merged.
