### ISSUE TITLE
Implement center snapping

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32324]
**Godot version:**
dd3e175

**Issue description:**
![gZRZvnjv03](https://user-images.githubusercontent.com/2223172/65555187-23947e00-df2c-11e9-9606-2539ca59df64.gif)

Seems to be snapping only to upper-left corner. Or was it always like that?

**Comment by groud** [comment]
> Or was it always like that?

Yes, I never implemented center snapping.

**Comment by KoBeWi** [comment]
For some reason I thought it was there 🤔

**Comment by groud** [comment]
I guess the visible snapping guides now help to see where the nodes snap. :)

**Comment by groud** [comment]
@Calinou if someone wants to work on it, I guess.

**Comment by KoBeWi** [comment]
I'm using Containers almost everywhere nowadays, so I don't need this anymore. It should be moved to proposals in either case.
