### ISSUE TITLE
Better collada exporter support for multiple armatures

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#3232]
An animated asset with more than one armature is not supported. So this is a request that a future version will support multiple armatures.
The following image is an example of an animated character where only one animation will be exported to the collada file. The red box indicates the animation that wont be exported.
![colladaexporter-02](https://cloud.githubusercontent.com/assets/15687516/12088680/b8a705fa-b2dd-11e5-94d7-e67d46399b2c.png)
Exporting using the Better Collada plugin results in this warning message. 
The second warning is not relevant so just ignore it.
![colladaexporter-01](https://cloud.githubusercontent.com/assets/15687516/12087806/46285580-b2d6-11e5-9c77-6584a5eb3e8e.png)
I did not make the asset myself by the way, it was purchased.

**Comment by reduz** [comment]
You can have as many armatures as you want, the restriction is just one per
object, and this won't go away.

**Comment by akien-mga** [comment]
Closing then as it seems this feature request can't be addressed. I did fix the ugly typo shown in the error log though ;) https://github.com/godotengine/godot/pull/3239
