### ISSUE TITLE
Crash reporting difficult to read "<couldn't map PC to fn name>"

### ISSUE THREAD

**Issue by johnoneil** [godotengine/godot#32322]
**Godot version:**
3.1.1 stable official

**OS/device including version:**
Windows 10 Enterprise 1803

**Issue description:**
Upon native (c++) exception, C# crash reporting does not give descriptive names, defaulting to <couldn't map PC to fn name>"

**Steps to reproduce:**
I'm reproducing by generating a C++ exception via C#:
```
[DllImport("kernel32.dll")]
static extern void RaiseException(uint dwExceptionCode, uint dwExceptionFlags,  uint nNumberOfArguments, IntPtr lpArguments);

// Raise a native exception
RaiseException(13, 0, 0, new IntPtr(1));
```

**Minimal reproduction project:**
This type of call stack seems very common in previous bug reports, but people are usually concerned more about the crash than the lack of call stack info.
I offhand don't see a reason why the C# callstack could not be correctly dumped here, though I have not looked very deeply. Thought it worthwhile asking first before I dig deeper.

**Comment by akien-mga** [comment]
That's because official binaries don't include debug symbols, which would make the binaries several times bigger.

If you compile from source with a debug binary, you should be able to have the native backtrace.

**Comment by johnoneil** [comment]
That's very helpful Akien-mga. I'll try this.
I am also interested in getting corresponding C# call stacks (say from where the manged code entered into unmanaged code) but I don't see any support in the crash_handler_windows.cpp method ```CrashHandlerException```. Do you think this would be impossible? I might try to put together a PR to provide this functionality.

**Comment by akien-mga** [comment]
C# call stacks should already be working normally, even in release builds with C++ debug symbols. CC @neikeq

**Comment by neikeq** [comment]
Do you mean making the native crash handler print the C# stack trace as well?

**Comment by johnoneil** [comment]
@neikeq Yes, exactly. I'm struggling a bit to correct the missing C++ debug symbols (my project is a bit complex), but in theory I can see it can be done, however the C# stacktrace at that point would be much more helpful to me. Both would be ideal.
If you guys think it's not impossible I could try to provide a PR. But if it's not worthwhile.
Still appreciate your help on this. I'll just close it tonight pending feedback.
