### ISSUE TITLE
Snap options icon disappeared

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32323]
**Godot version:**
dd3e175

**Issue description:**
What happened here?
![image](https://user-images.githubusercontent.com/2223172/65554868-1cb93b80-df2b-11e9-9080-10758c104f02.png)

Same with onion skinning in Animation, which used that icon too.

**Comment by akien-mga** [comment]
Regression from #32267.

Your grep-fu failed you @YeldhamDev :)
```
$ rg GuiMiniTabMenu
editor/editor_audio_buses.cpp
91:                     bus_options->set_icon(get_icon("GuiMiniTabMenu", "EditorIcons"));
183:                    bus_options->set_icon(get_icon("GuiMiniTabMenu", "EditorIcons"));

editor/plugins/animation_player_editor_plugin.cpp
125:                    onion_skinning->set_icon(get_icon("GuiMiniTabMenu", "EditorIcons"));

editor/plugins/spatial_editor_plugin.cpp
2307:           view_menu->set_icon(get_icon("GuiMiniTabMenu", "EditorIcons"));

editor/plugins/canvas_item_editor_plugin.cpp
3670:           snap_config_menu->set_icon(get_icon("GuiMiniTabMenu", "EditorIcons"));
```

(Arguably those icons should likely be renamed to use lowercase `gui` in the filename to avoid this confusion, I guess you might have search for `GUIMiniTabMenu`.)

**Comment by akien-mga** [comment]
When readding the icon, it would be worth optimizing it with `svgcleaner` as done in #32318.
