### ISSUE TITLE
3D Collision Polygon Snapping Enabled on the 2D UI Screen. 

### ISSUE THREAD

**Issue by jaykyburz** [godotengine/godot#32328]
**Godot version:**
Godot 311

**OS/device including version:**
Windows 10.

**Issue description:**
When moving points on a collision polygon in a 3D Viewport, they will snap to the 2d grid settings. You have to change to the 2D Viewport to turn on and off snapping.  See Youtube example linked below. 

https://youtu.be/aGGAr3arxo0

**Comment by aure2006** [comment]
It works with the 2019/09/20 nightly build.

**Comment by Calinou** [comment]
Closing as resolved per the above comment.
