### ISSUE TITLE
Error: The apk for your currently selected variant (android_debug.apk) is not signed. Please specify a signing configuration for this variant (debug)

### ISSUE THREAD

**Issue by jaccen** [godotengine/godot#32331]
android studio--->open  platform/android/java  

GodotAPP.java
public class GodotApp extends Godot.SingletonBase {

    protected Activity appActivity;
    protected Context appContext;
    private int instanceId = 0;

    public int myFunction(String p_str) {
        // A function to bind.
        return 1;
    }

    public void getInstanceId(int pInstanceId) {
        // You will need to call this method from Godot and pass in the get_instance_id().
        instanceId = pInstanceId;
    }

    static public GodotApp initialize(Activity p_activity) {
        return new GodotApp(p_activity);
    }

    public GodotApp(Activity p_activity) {
        // Register class name and functions to bind.

        registerClass("MySingleton", new String[]
                {
                        "myFunction",
                        "getInstanceId"
                });
        this.appActivity = p_activity;
        this.appContext = appActivity.getApplicationContext();
        // You might want to try initializing your singleton here, but android
        // threads are weird and this runs in another thread, so to interact with Godot you usually have to do.
        //   activity.runOnUiThread(new Runnable() {
        //      public void run() {
        // Useful way to get config info from "project.godot".
        //           String key = GodotLib.getGlobal("plugin/api_key");
        //           // SDK.initializeHere();
        //      }
        //    }
        //    );

    }

    // Forwarded callbacks you can reimplement, as SDKs often need them.

    protected void onMainActivityResult(int requestCode, int resultCode, Intent data) {}
    protected void onMainRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {}

    protected void onMainPause() {}
    protected void onMainResume() {}
    protected void onMainDestroy() {}

    protected void onGLDrawFrame(GL10 gl) {}
    protected void onGLSurfaceChanged(GL10 gl, int width, int height) {} // Singletons will always miss first 'onGLSurfaceChanged' call.

}

get errors:
Error: The apk for your currently selected variant (android_debug.apk) is not signed. Please specify a signing configuration for this variant (debug)

i want compile godot an simple app  from android studio,.
how can i resolve this problem

3ks

**Comment by akien-mga** [comment]
CC @m4gr3d

**Comment by m4gr3d** [comment]
@jaccen Android Studio is only to be used for development of the Godot engine.
You need to use the Godot editor to compile and use a simple app as you mention. The behavior you're seeing is expected behavior since the apks generated by Android Studio for the Godot engine are only meant to be unsigned templates to be used and signed by the Godot editor when exporting the game apk.

**Comment by m4gr3d** [comment]
If you're trying to learn Godot development, I'd recommend the [Getting started documentation](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/index.html) and the super helpful [community channels](https://docs.godotengine.org/en/3.1/community/channels.html).

**Comment by jaccen** [comment]
i want to use godot as e render engine  for my project, for exaple add camera for AR
,an so on 

so  i like to use native engine ,not editor

**Comment by jaccen** [comment]
@m4gr3d 
i want to comple godot as a lib, as my project's nativ thirdparty
through JNI  with my project in andriod studio.

**Comment by m4gr3d** [comment]
What you're trying to do is possible through Godot custom Android build templates which will be available in 3.2, so I'd recommend going that route.
That said, while that's possible it still requires knowledge of how the Godot editor interacts with Android apks so you'd still need to familiarize yourself with the Godot editor or you'll quickly run into issues like this one.

**Comment by jaccen** [comment]
i have some knowledge about 3dEngine, i have writtern an cross-patform play engine several years ago, and recently work in BaiDu (china)  writtern an  AR Engine.
so i get godot and found this an perfect engine ,so i want to learn ,an use it!

**Comment by jaccen** [comment]
@m4gr3d  when will the 3.2 come out?  that version support AAR  for android ?
I expect it so much！
