### ISSUE TITLE
Can´t add child 'pelota' to 'barra',already as a parent 'barra'

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#32338]
**Godot version:**
<img width="487" alt="Screenshot_1" src="https://user-images.githubusercontent.com/12847027/65598939-f7e8b680-df72-11e9-9e0e-0d743d2915cb.png">

**OS/device including version:**
<img width="798" alt="Screenshot_2" src="https://user-images.githubusercontent.com/12847027/65598965-0a62f000-df73-11e9-95c8-4c09196a2f7d.png">

**Issue description:**
I am in a practice with a block type game, the issue is that there seems to be something weird with the hierarchy when repairing the bar sphere. Although the program works well, the debugger throws this error:
<img width="520" alt="Screenshot_3" src="https://user-images.githubusercontent.com/12847027/65599137-88bf9200-df73-11e9-9893-9e6f67bc3978.png">
<img width="512" alt="Screenshot_5" src="https://user-images.githubusercontent.com/12847027/65599146-8c531900-df73-11e9-92f9-578354f2f476.png">
<img width="673" alt="Screenshot_6" src="https://user-images.githubusercontent.com/12847027/65599192-a260d980-df73-11e9-9b69-55b9887eeb04.png">
[https://youtu.be/5YqmraON52c](url)

**Steps to reproduce:**
Create 3 nodes and name them 1,2,3
Node 2 is a child of node 1 and node 3 is a child of node 2
Change the code hierarchy by making node 3 the daughter of node 1 and after a while node 3 becomes the son of node 2 again

For the project that I send them.
Activate play and every time the ball touches the ground
they will see that the change of the hierarchy works well,
however the debugger marks the error
Can´t add child 'ball' to 'bar', already as a parent 'bar'
the error is in the "Escena_principal script"
which is in the first node of the scene

**Minimal reproduction project:**
[Bloques_tu_primer_juego_con_Godot_y_Blender3D.zip](https://github.com/godotengine/godot/files/3652341/Bloques_tu_primer_juego_con_Godot_y_Blender3D.zip)

**Comment by akien-mga** [comment]
The problem is with your code, you're adding `pelota` to `barra` while it is *already* a child of `barra`.

Which means that your code doesn't do what you expect:
![Screenshot_20190925_142403](https://user-images.githubusercontent.com/4701338/65600285-23ce6100-dfa0-11e9-8ada-25b34e9418fd.png)

```
		get_child(0).remove_child(body_pelota)#esto hace que la pelota deje de ser hijo de este nodo
		barra.add_child(body_pelota)#hago que la pelota vuelva a ser hijo de la barra para que se muevan juentos
```

See your scene tree, `get_child(0)` in `Escena_principal` is `barra_pelota_pared`, which does not have the `pelota` child. So it's not removed from `barra`, and thus can't be readded.

Please post such questions on other community platforms in the future, GitHub is for engine bugs, and until you're confident that your code is correct, an error does not mean an engine bug, but most of the time a bug in your own code.

**Comment by KoBeWi** [comment]
The actual problem is that the method `_on_area_para_eventos_body_entered` is called twice. When ball initially enters area and then when `add_child` is called (it technically enters the area for the second time).

**Comment by kone9** [comment]
> The actual problem is that the method `_on_area_para_eventos_body_entered` is called twice. When ball initially enters area and then when `add_child` is called (it technically enters the area for the second time).

If that is the odd thing, because it only shows one message per console ... It works fine too ... I will also try what akien-mga told me

**Comment by kone9** [comment]
> The problem is with your code, you're adding `pelota` to `barra` while it is _already_ a child of `barra`.
> 
> Which means that your code doesn't do what you expect:
> ![Screenshot_20190925_142403](https://user-images.githubusercontent.com/4701338/65600285-23ce6100-dfa0-11e9-8ada-25b34e9418fd.png)
> 
> ```
> 		get_child(0).remove_child(body_pelota)#esto hace que la pelota deje de ser hijo de este nodo
> 		barra.add_child(body_pelota)#hago que la pelota vuelva a ser hijo de la barra para que se muevan juentos
> ```
> 
> See your scene tree, `get_child(0)` in `Escena_principal` is `barra_pelota_pared`, which does not have the `pelota` child. So it's not removed from `barra`, and thus can't be readded.
> 
> Please post such questions on other community platforms in the future, GitHub is for engine bugs, and until you're confident that your code is correct, an error does not mean an engine bug, but most of the time a bug in your own code.

ok,thanks

**Comment by kone9** [comment]
> The problem is with your code, you're adding `pelota` to `barra` while it is _already_ a child of `barra`.
> 
> Which means that your code doesn't do what you expect:
> ![Screenshot_20190925_142403](https://user-images.githubusercontent.com/4701338/65600285-23ce6100-dfa0-11e9-8ada-25b34e9418fd.png)
> 
> ```
> 		get_child(0).remove_child(body_pelota)#esto hace que la pelota deje de ser hijo de este nodo
> 		barra.add_child(body_pelota)#hago que la pelota vuelva a ser hijo de la barra para que se muevan juentos
> ```
> 
> See your scene tree, `get_child(0)` in `Escena_principal` is `barra_pelota_pared`, which does not have the `pelota` child. So it's not removed from `barra`, and thus can't be readded.
> 
> Please post such questions on other community platforms in the future, GitHub is for engine bugs, and until you're confident that your code is correct, an error does not mean an engine bug, but most of the time a bug in your own code.

To solve this problem, I created a condition by checking when the ball node is as a child, however I cannot understand why it comes in twice. It is very rare ... I also leave the code example here for the doubts ... Thank you very much for your time.

<img width="624" alt="Screenshot_7" src="https://user-images.githubusercontent.com/12847027/65606933-16a27980-df82-11e9-856d-c0979a93bafc.png">

**Comment by KoBeWi** [comment]
> I cannot understand why it comes in twice.

I explained it in my post. When you remove child, it exits Area2D. Then when you do `add_child`, the node is added to scene tree and the Area2D detects it again immediately.

**Comment by kone9** [comment]
> > I cannot understand why it comes in twice.
> 
> I explained it in my post. When you remove child, it exits Area2D. Then when you do `add_child`, the node is added to scene tree and the Area2D detects it again immediately.

OK, Thank you very much. In the end I solved it as I show in the code.
