### ISSUE TITLE
Strange behaviour in tilemap's tile selector, when rotating/flipping single tiles (with gles2_use_nvidia_rect_flicker_workaround ON)

### ISSUE THREAD

**Issue by muchitto** [godotengine/godot#32346]
**Godot version:**
3.2-dev (https://github.com/godotengine/godot/commit/e426169e4ce8cbb0a8c0fb04f75e60976058177e)

**OS/device including version:**
Window 10 64-bit

**Issue description:**
When I try rotating/flipping the tiles in the tilemap's tile selector panel, something strange happens. It seems that it changes/rotates the areas/rects of the atlas texture that the individual tiles have been assigned to. The areas go back to normal when you click the Clear Transform button, but start again if you try to flip them again. 

![tilemapproblem](https://user-images.githubusercontent.com/359786/65622669-d0bfd280-dfce-11e9-9f69-fa43a3239822.gif)

**Steps to reproduce:**
Open the minimal reproduction project and select the Level tilemap and then try to use the tile rotation and flipping commands.

**Minimal reproduction project:**
[TilemapRotationBug.zip](https://github.com/godotengine/godot/files/3653785/TilemapRotationBug.zip)

**Comment by akien-mga** [comment]
CC @groud @YeldhamDev @MarianoGnu

**Comment by muchitto** [comment]
I forgot to mention, that if you flip/rotate a tile in the tilemap's tile selector and it looks all weird in there and then place it in the actual map, it looks totally right. It is flipped/rotated correctly in the actual map, but not in the tile selector.

**Comment by groud** [comment]
That's kind of weird though, I don't remember this bug when I changed the TileMap editor buttons.
Maybe this bug was likely introduced recently.

**Comment by muchitto** [comment]
Ok, I found the issue. Somehow I have enabled (maybe by accident, because I had enabled the "pixel snap" option) the "Gles 2 Use Nvidia Rect Flicker Workaround" in the Rendering -> Quality -> 2D section of the project settings. When I disable it and restart the editor, the tileselector works.
