### ISSUE TITLE
Allow to use constants in preload/load

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3234]
Currently it's impossible to write code like that:
```
const PATH_2_SCENE = "ScenePath.xscn";
var scene = preload(PATH_2_SCENE);
```
In editor validation (before starting the program) It says ```"error(9,22): Expected string constant as 'preload' argument"```
It would be nice to allow developers to use static const variables in case together with preloads and loads since it would ease changes if there would be ability to define paths in one place for the whole project.

**Comment by akien-mga** [comment]
Sounds like a good idea. Once implemented, we should make sure that it works too with constants from autoload singletons, e.g. ```preload(global.PATH_2_SCENE)``` as it's likely the main usage of what you're asking for.

**Comment by reduz** [comment]
Could try using the reduce constant expression code for this, should not be too difficult

**Comment by reduz** [comment]
let's see if anyone can do this, it shouldn' t be too difficult :)
https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_parser.cpp#L277

**Comment by reduz** [comment]
just call parse_and_reduce_constant_expression instead of parsing a constant string

**Comment by reduz** [comment]
closed by 3441

**Comment by cgbeutler** [comment]
Does this still work in 2020? I'm getting a "expected string constant as 'preload' argument."

**Comment by cgbeutler** [comment]
Ohhh, never mind. This apparently isn't for the case I'm doing, which was never added:
```
const __root := "../../../"
const err_ext := preload(__root + "err_ext.gd")
...
```
