### ISSUE TITLE
iOS error log fills with "500 error" [GLES2]

### ISSUE THREAD

**Issue by johngirvin** [godotengine/godot#32359]
**Godot version:**
3.1.1-stable-official

**OS/device including version:**
iOS (any)
Tested on iOS 11.x iPhone 8

**Issue description:**
Error log fills up with "500 error"

**Steps to reproduce:**
Run any iOS project with GLES2 renderer.
Switching to GLES3 renderer solves the issue.
Seems to be identical to GLES3 issue [#25324](https://github.com/godotengine/godot/issues/25324)

**Comment by clayjohn** [comment]
Duplicate of https://github.com/godotengine/godot/issues/31907
