### ISSUE TITLE
Inspector values cannot be modified after "Play" window is closed

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot#32355]
**Godot version:** 3.1.1 (Mono)

**OS version:** Ubuntu 19.04

**Issue description:** After "Playing" and closing the window, fields cannot be modified until another node is selected first.

**Steps to reproduce:**
1. Select a node (I think it must have a script attached)
2. Press Run (F5)
3. Close the running game
4. Attempt to edit a text field

**Comment by clayjohn** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
