### ISSUE TITLE
Light2D Shadow Smoothing produces weird artifacts

### ISSUE THREAD

**Issue by Chrisstar56** [godotengine/godot#32368]
**Godot version:** 3.1

**OS/device including version:** Windows 10
![grafik](https://user-images.githubusercontent.com/18631757/65700857-a3336180-e080-11e9-8601-9f6febcd4017.png)
Setting high level of smoothing on a Light2D shadow produces weird artifacts (see picture). It's less noticeable with smaller levels, but if you know what you are looking for you can still see it

**Comment by clayjohn** [comment]
Is it those hard lines below the player and in the upper-left corner?

**Comment by Chrisstar56** [comment]
Without smoothing
![grafik](https://user-images.githubusercontent.com/18631757/65709294-c5cd7680-e090-11e9-9280-682dc328a347.png)
With Max smoothing
![grafik](https://user-images.githubusercontent.com/18631757/65709338-de3d9100-e090-11e9-9a4d-1c57571b6f89.png)
With light smoothing (barely noticeable, but still there)
![grafik](https://user-images.githubusercontent.com/18631757/65709382-fb725f80-e090-11e9-98d7-a1d6194b9b70.png)
Here's a zoomed in version of the last screenshot
![grafik](https://user-images.githubusercontent.com/18631757/65709410-06c58b00-e091-11e9-83b5-5672f665b85c.png)

**Comment by Chrisstar56** [comment]
Here's a version of the last screenshot with increased contrast so you can more easily see where it happens
![grafik](https://user-images.githubusercontent.com/18631757/65713179-eac5e780-e098-11e9-899c-5a2f45b39e1f.png)

**Comment by girng** [comment]
Might be fixed with vulkan?

**Comment by clayjohn** [comment]
Indeed. The 2D rendering system was overhauled in the move to Vulkan. This issue should be fixed in 4.0. If it is not, we can reopen. 

Sorry I can't point to a specific PR, the 2D stuff was added during the period where reduz maintained a separate branch.
