### ISSUE TITLE
Viewport image capture not working on iPhone

### ISSUE THREAD

**Issue by danielkotzer** [godotengine/godot#32361]
**Godot version:**
3.1.1

**OS/device including version:**
iPhone 5S ios 12.1.4

**Issue description:**
Viewport image capture not working on iPhone device

**Steps to reproduce:**
var img = Image.new()
var itex = ImageTexture.new()
img = viewport.get_texture().get_data()
itex.create_from_image(img)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

**Comment by KoBeWi** [comment]
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.
