### ISSUE TITLE
The error when redeclaring type is unclear

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32370]
**Godot version:**
02ca4c4

**Issue description:**
So, sometimes happens that I have a typed variable and mistakenly try to assign the type again.
![image](https://user-images.githubusercontent.com/2223172/65708267-74bc8300-e08e-11e9-9b38-a050fa8b1544.png)
The error that shows in this situation is totally misleading. It should say something like "can't assign type to already declared variable" or "use = not :=, fool".

**Comment by akien-mga** [comment]
CC @vnen @bojidar-bg

**Comment by bojidar-bg** [comment]
Would it be good enough if the error message is changed to `Expected end of statement after expression, got ':'`?

**Comment by KoBeWi** [comment]
It would be better, but not sure if good enough. The error is still weird. Why would it expect end of statement after lone identifier?

**Comment by bojidar-bg** [comment]
Because `:` is not a valid part of an expression.
