### ISSUE TITLE
OS.get_system_time_msec() has wrong value if OS is HTML5

### ISSUE THREAD

**Issue by davehayes** [godotengine/godot#32376]
**Godot version:**

3.1

**OS/device including version:**

FreeBSD 11.3 + Chromium Version 75.0.3770.142

**Issue description:**

`OS.get_system_time_msec()` produces incorrect output when running in a browser.

**Steps to reproduce:**

Here's the GDscript that I am running:

```
	var now = OS.get_system_time_msecs()
	print_debug("MSEC: " + str(now))
	print_debug("SEC: " + str(OS.get_system_time_secs()))
	print_debug("UNIX: " + str(OS.get_unix_time()))
	JavaScript.eval("console.log('T:' + (new Date).getTime());");
```

This produces the following output in the browser console:

```
MSEC: 1866397845
SEC: 1569529460
UNIX: 1569529460
T:1569529460886
```
Quite unexpected that the MSEC value produces a date somewhere in 2029. The T value is what I would have expected.

**Comment by akien-mga** [comment]
Relevant code: https://github.com/godotengine/godot/blob/b2569d5fa8e45173bbd8c03d9887e7635c7986b0/drivers/unix/os_unix.cpp#L181-L191

It's the same for Javascript and other Unixes, so not sure why it's giving a wrong result. I assume it must be some overflow issue, possibly `timeval`'s `time_t` might be 32-bit on Emscripten, so `tv_now.tv_sec * 1000` overflows and wraps around?

BTW, not directly related as it's about performance, but might be worth looking into: https://github.com/urho3d/Urho3D/issues/916

CC @Faless

**Comment by Kanabenki** [comment]
It seems indeed to be case that `time_t` is 32-bit on Emscripten since it's defined as `long ` and those seems to be 4 bytes wide when I compile with emcc.

https://github.com/emscripten-core/emscripten/blob/cfa4819b501d351bdaf99942da9f2f9b6f456553/system/lib/libc/musl/arch/emscripten/bits/alltypes.h#L74-L77
