### ISSUE TITLE
Transform matrix elements can become -0

### ISSUE THREAD

**Issue by AngelOnFira** [godotengine/godot#32371]
Godot Engine v3.2.alpha.custom_build.02ca4c49f

Ubuntu 18.04.3 LTS

When rotating with `$SpatialObject.rotate_y(deg2rad(90))`, the decimal points of radians will leave some artifacts. Even though the rotation is a clean right angle, it can show up in the matrix as -0 instead of 0.

![image](https://user-images.githubusercontent.com/14791619/65709770-9eaa8100-e05f-11e9-8b8b-2e38955e4b80.png)

Therefore, when trying to compare transforms to see if objects are oriented the same way, they will not show as equal to one another. This is not the best way to achieve this while rotating by angles that are not 90 degrees, but for beginners who don't understand why they are not equal, it would be difficult to debug.

Not sure what the best solution would be, but the way I'm fixing it is as such:

```
func _clean_transform(transform_in):
	transform_in.basis.x = Vector3(
		int(transform_in.basis.x.x),
		int(transform_in.basis.x.y),
		int(transform_in.basis.x.z))
		
	transform_in.basis.y = Vector3(
		int(transform_in.basis.y.x),
		int(transform_in.basis.y.y),
		int(transform_in.basis.y.z))
		
	transform_in.basis.z = Vector3(
		int(transform_in.basis.z.x),
		int(transform_in.basis.z.y),
		int(transform_in.basis.z.z))
		
	return transform_in
```

I apologize if there is a better solution to this entire problem that I'm overlooking.

**Comment by AngelOnFira** [comment]
I seem to have found a better solution by comparing `basis.get_euler()` of each transform. I'll leave this open in case there are other applications for the issue. Otherwise, it's probably worth closing.

**Comment by clayjohn** [comment]
This looks more like a floating point precision error than an error with the transform class itself.

**Comment by AngelOnFira** [comment]
I agree. A way to cast all entries to int would be helpful to fix this, unless there is a different way.

**Comment by AngelOnFira** [comment]
I've done some more reading into this subject and I think there are other issues that better encompass more fundamental issues.
