### ISSUE TITLE
(C#) GetNodeOrNull() prints errors to the errors tab when the node is not found

### ISSUE THREAD

**Issue by mwerezak** [godotengine/godot#32375]
**Godot version:**
v3.1.1.stable.mono.official

**OS/device including version:**
Ubuntu 18.04.3 LTS

**Issue description:**
Contrary to its documentation, when GetNodeOrNull<T>() is called on a node path to a nonexistant node, it produces "Node not found" errors in the Godot console.

**Steps to reproduce:**
1. Call GetNodeOrNull() with a nonexistent path as the argument.

**Comment by neikeq** [comment]
Could be a conflict with the helper method we added before `get_node_or_null` was added to the engine:

https://github.com/godotengine/godot/blob/b2569d5fa8e45173bbd8c03d9887e7635c7986b0/modules/mono/glue/Managed/Files/Extensions/NodeExtensions.cs#L10-L13

**Comment by mwerezak** [comment]
@neikeq it seems so, looks like both `GetNode()` and `GetNodeOrNull()` are being funneled into the same underlying method.

**Comment by Phischermen** [comment]
This issue seems to have been fixed by #35708.

**Comment by akien-mga** [comment]
Thanks, closing.
