### ISSUE TITLE
Basis Universal and mingw compiler errors on Vulkan

### ISSUE THREAD

**Issue by fire** [godotengine/godot#32384]
**Godot version:**
8275e43

**OS/device including version:**
OSX 

**Issue description:**
> &2|02:19:59.516 thirdparty/basis_universal/basisu_enc.h:748:26: error: 'dirname' was not declared in this scope

> &2|02:19:59.537 thirdparty/basis_universal/basisu_enc.h:749:27: error: 'basename' was not declared in this scope

There's more.

[compile.txt](https://github.com/godotengine/godot/files/3661067/compile.txt)

**Comment by akien-mga** [comment]
Fixed by #32385.

Patch submitted upstream.

**Comment by akien-mga** [comment]
The patch was merged upstream.
