### ISSUE TITLE
List of functions inside a GDScript file and fast access by click

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#3238]
I think it would be a nice feature to add to the script editor.
It basically consists on a panel (that can be hidden/shown) aside the editor, listing all the functions by their name. A click on the function focuses the editor on this function.
An icon just before each function name could give a quick information, such as:
- is an inherited function
- is a standard GDScript redefined function (_ready, _process, _draw...)
- is a user function (others)
- is a function called by connect()
- ...

**Comment by kubecz3k** [comment]
Good idea, I probably would not use the panel itself since there already is ctrl+shift+f, but would be great if this additional info (inherited function, user function, etc) will be also implemented into ctrl+shift+f window +1

**Comment by StraToN** [comment]
@kubecz3k Doesn't ctrl+shift+f assume that you already know the name of the function you are looking for? The panel I propose gives a more global view of functions contained in the script. 
Also, I personally appreciate to know the order of the functions in the file, as I often move them so functions who are related to each other can be placed close together if they are not.

**Comment by Calinou** [comment]
:+1:

A list of methods would make the script editor more like an IDE, which is very helpful when working on large games.

**Comment by kubecz3k** [comment]
@StraToN well there are all the functions in the list, you don't need to know the name, order also is taken from the order of these function in the file..

**Comment by StraToN** [comment]
I'll need to have a look at this functionality, I never used it yet. Maybe the panel displayed by ctrl+shift+f can be made accessible through a button (keeping the shortcut useable), and the list be improved with the icons I previously quoted. 
I'll have a look this evening.

**Comment by kubecz3k** [comment]
Generally currently the windows is quite rough: 
![functionswindow](https://cloud.githubusercontent.com/assets/6129594/12118834/e0c867c2-b3c8-11e5-90aa-1f9cacbcf017.gif)
Improvements that you proposed would be very nice for sure.

**Comment by StraToN** [comment]
@kubecz3k Thanks for that GIF.

Ok, so as I understand, ctrl+shift+f opens a popup that already lists the functions contained in the current GDScript. So, basically the job is already done.
So, this is what I propose for modifying this feature:
- turn the ctrl+shift+f popup to a toggable panel attached to a button (propositions on its position?)
- sort the functions in this order and add corresponding icons at their left: 
 * standard GDScript redefined function (_ready, _process, _draw...) -  Red dot
 * inherited functions - Yellow dot
 * user function (others) - Green dot
 * connected function - Grey dot

**Comment by akien-mga** [comment]
If some work is done on this function, there could also be an option to see non-used but overridable virtuals as asked for in #3237.

**Comment by StraToN** [comment]
@akien-mga I like the idea. Clicking one of these non-used but overridable virtuals functions could directly add the corresponding function at the end of the GDScript. However they need to be displayed different from existing (overriden) functions in that panel. Maybe with just no icon at all? Or with a statement like this:
```
# _ready() : line 32 [Help]
# _process() : line 50 [Help]
O my_user_function() : line 75
O my_user_function2() : line 80
___________________
   _draw() : (create)  [Help]
   _paused() : (create) [Help]
   _unpaused() : (create) [Help]
....
```

**Comment by StraToN** [comment]
Adding a reference to #2982

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.
