### ISSUE TITLE
Playing game in html5 crashes 99% of time time either instantly, or after a few seconds

### ISSUE THREAD

**Issue by dali99** [godotengine/godot#32391]
**Godot version:**
3.1.1.stable.custom_build
Docker barichello/godot-ci:3.1.1

**OS/device including version:**
NixOS 19.03
Firefox 68.0.1

**Issue description:**
Unable to play a html5 compiled version of the game.
When opening the game it usually just has a black screen with audio playing.
Few times it will play for a second
One time it played for a whole game, until the scene got respawned, crashing it again.

with the error code:
```
OpenGL ES 2.0 Renderer: Mozilla index.js:7:32213
Error: WebGL warning: framebufferRenderbuffer: bindRenderbuffer must be called before attachment to 8d00 2 index.js:7:260673
uncaught exception: abort(27). Build with -s ASSERTIONS=1 for more info. index.js:7:320859
**ERROR**: Method/Function Failed, returning: RES() index.js:7:32482
   At: core/io/resource_loader.cpp:285:_load() - Method/Function Failed, returning: RES() index.js:7:32482
27 index.js:7:320776
27 index.js:7:320786
```

https://matrix.to/#/!hiFyysvSNAREQyJdCG:matrix.org/$156957004523477lNtks:dodsorf.as?via=matrix.org&via=amorgan.xyz&via=dodsorf.as

I can confirm GLES2 is on, and Physics mode is set to single-safe

**Steps to reproduce:**
Unsure
https://dandellion.pages.dodsorf.as/fossekleiva-ks-hackathon-demo/

**Minimal reproduction project:**
https://git.dodsorf.as/Dandellion/fossekleiva-ks-hackathon-demo

**Comment by Relintai** [comment]
The issue is that the stuff you load from code won't get exported with the `Export selected scenes (and dependencies)`  option.

By the way I've also tested it on master, it doesn't hang there.

**Comment by dali99** [comment]
That does make sense, thank you.

I see now that the only other platform I tested was _not_ set to load only the dependencies.

I assume export resources and then selecting all those  would work.

Thank you very much it works now

**Comment by dali99** [comment]
Sorry for the noise
