### ISSUE TITLE
Clicking on the rename function in visual script gives an invalid input

### ISSUE THREAD

**Issue by fire** [godotengine/godot#32396]
**Godot version:**
ba8b2a1

**OS/device including version:**
OSX 10.14

**Issue description:**

Clicking on the rename function in visual script gives an invalid input.

![Screen Shot 2019-09-27 at 12 25 36 PM](https://user-images.githubusercontent.com/32321/65796614-ef82ae00-e121-11e9-9c74-b1af3d289333.png)

**Minimal reproduction project:**
Any visual script project.

**Comment by akien-mga** [comment]
CC @swarnimarun

**Comment by fire** [comment]
Still occurs.

https://cdn.discordapp.com/attachments/575034574510227491/627497522650152970/Screen_Recording_2019-09-28_at_6.30.47_AM.mov

**Comment by swarnimarun** [comment]
@fire it is valid you can type in it and it will change the name.

**Comment by swarnimarun** [comment]
I guess I should add the text into the boxes by default... :P
Seems like a Bad UX problem now. Done with most of the Decompose and Compose nodes will add it in there...

**Comment by swarnimarun** [comment]
![rename](https://user-images.githubusercontent.com/19930870/65840012-ddc32580-e330-11e9-9c42-f12f9cd91c43.gif)
The UX was fixed in the deconstruct node PR.
