### ISSUE TITLE
Android: GLES2 project crash if WorldEnvironment has Background in Sky mode ( Fatal signal 7 (SIGBUS))

### ISSUE THREAD

**Issue by legendiguess** [godotengine/godot#32394]
**Godot version:** 3.1.1.stable

**OS/device including version:** Xiaomi Redmi 4 Android 6.0.1

**Issue description:** Game on android crash after bootsplash logo if scene have WorldEnvironment with sky setup(only in GLES2, on GLES3 game works fine).

**Steps to reproduce:** 

1. Create empty project
2. Delete default_env.tres (it's causes same crash after bootsplash(i think it's cause it's have sky setup))
3. Make simple scene with Spatial and WorldEnvironment inside.
4. Set up WorldEnvironment node with procedural sky.
5. Turn on GLES2 mode.
6. Export and lanuch game on android.

**Minimal reproduction project:**

[minimal reproduction project.zip](https://github.com/godotengine/godot/files/3663632/minimal.reproduction.project.zip)

Also here some cut from adb logcat log:
[logcat.txt](https://github.com/godotengine/godot/files/3663646/logcat.txt)

In log you can see Fatal signal 7 (SIGBUS) error that appears only if scene have WorldEnvironment with sky and if project is in GLES2

**Comment by lawnjelly** [comment]
Could be a data alignment issue, does it occur in an x86 emulator?

**Comment by legendiguess** [comment]
> Could be a data alignment issue, does it occur in an x86 emulator?

need to be tested

**Comment by lawnjelly** [comment]
Also I would try it with the latest 3.2:
https://hugo.pro/projects/godot-builds/

You are unlikely to get interest in investigating unless it occurs in latest master, it may be a bug that was previously fixed.

**Comment by avril-gh** [comment]
given minimal reproduction project does not crash for me
tested on master b0f0e0e2fc95743adccf76ce82696be5b9553536 on real gles2 android device with mali450
[crash.apk.zip](https://github.com/godotengine/godot/files/3665339/crash.apk.zip)

**Comment by Relintai** [comment]
Try setting the procedural sky's texture size to lower than 1024, and please test that way as well, maybe that phone doesn't like big textures.

I'm at the moment not sure if I read about issues like this, or had a phone in the past that didn't like 1024x1024-ish textures, but looking at the crash log my first guess is that this might be a driver issue. (More that half of it is in the opengl driver, manipulating textures).

I'll simbolify the crashlog later, I only have the downloaded templates for 3.1.1 at the moment.

**Comment by legendiguess** [comment]
Just checked Godot 3.1.2 - bug still here. 
Also as @lawnjelly suggested - tryed it on last Godot 3.2(Godot 3.2 beta 2) - bug still exist.

**Comment by clayjohn** [comment]
@legendiguess did you try lowering your radiance map size as Relintai suggested? On lower-end hardware sizes of 1024 and above can cause crashes.

**Comment by legendiguess** [comment]
@clayjohn just checked with those settings on Godot 3.2(Godot 3.2 beta 2) still crash with `Fatal signal 7 (SIGBUS), code 1, fault addr 0x2751 in tid 4012 (GLThread 6084)` error.
![image](https://user-images.githubusercontent.com/40376451/69894494-4c792b00-1342-11ea-93b7-6f8da638ae27.png)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by legendiguess** [comment]
> 
> 
> Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

I no longer have access to the phone on which I encountered this bug, so i can't try to reproduce it.

**Comment by KoBeWi** [comment]
Doesn't look like anyone else had this issue, so closing.
