### ISSUE TITLE
Allow selecting multiple scenes or scripts in "Quick Open ..." for opening

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#3240]
The ability to select multiple scenes or scripts in "Quick Open Scene" and "Quick Open Script" would help increase productivity.

Use cases:
- Open all your scripts at once
- Open all the scripts in a folder (since the scripts are sorted by name, this is easy)
- Open just 2-3 scripts, without using the menu 2-3 times

**Comment by reduz** [comment]
Anyone wants to give it a spin?
https://github.com/godotengine/godot/blob/master/tools/editor/quick_open.cpp
