### ISSUE TITLE
set_meta overrides array values

### ISSUE THREAD

**Issue by zero334** [godotengine/godot#32415]
**Godot version:**
3.1.1 & b0f0e0e2fc95743adccf76ce82696be5b9553536
**OS/device including version:**
Windows 10 & Ubuntu 19.04
**Issue description:**

I try to add instances of a TextureRect element to an array. Before adding them, I set metadata information with the method .set_meta("id", "some_name"). After adding x elements to the array, the first x elments have the meta information of the last element I pushed to the array.

![demo](https://user-images.githubusercontent.com/1432845/65817958-31d4e980-e20d-11e9-8aa4-718165ffaf07.PNG)
Note the output. I was expecting cat cow dog cat cow dog but I got cat cow dog dog dog dog.
I also did talk about that issue with some guys on the godot discord. Some were able to reproduce it, some were not. If someone wants to work on that, and is not able to reproduce it, I am more than happy to help.

**Steps to reproduce:**
1) Create a new project
2) Add a new Node (I did use the "Other Node" button)
3) Attatch a new GDScript to the created node
4) Add following code to the script

```
extends Node

var items = []
const tex = preload("res://TextureRect.tscn")

func _ready():
	createItem("cat")
	createItem("cow")
	createItem("dog")
	read_meta()

func read_meta():
	for i in items:
		print(i.get_meta("id"))

func createItem(item_name):
	var item := tex.instance()
	item.set_meta("id", item_name)
	print(item.get_meta("id"))
	add_child(item)
	items.append(item)
```
5) Create a new scene
6) Add a single TextureRect node using the "Other Node" button
7) Run the project and check the debug output.

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/3665585/project.zip)

**Comment by girng** [comment]
Wow, nice find

**Comment by girng** [comment]
..wait

Arn't you supposed to use `duplicate()` here?

**Comment by girng** [comment]
Hmm, here is something that I find interesting:
```
	var tex = load("res://TextureRect.tscn")
	var item = tex.instance()
```

If you use a **local variable** that instances the scene (**not a referenced** instance variable), the output is correct. This might be why I've never ran into this problem because I've always done it like this.

However, I could totally see how this is a bug because when the developer uses `instance()`, it's implied   it's a *new* instance being created? Thus, the meta values should be unique.

**Comment by bojidar-bg** [comment]
@girng I assume, that if you replace `load` with `preload`, you will again get the wrong output. The reason it works with `load` might be that it loses reference to the packed scene object, which in turn loses reference to the problematic metadata dictionary.

**Comment by girng** [comment]
@bojidar-bg Just tested, yep you are right
