### ISSUE TITLE
iOS 13.1 - Audio is not working

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#32413]
**Godot version:**
3.2 - master branch

**OS/device including version:**
iPhone Xr, iOS 13.1

**Issue description:**
There is no audio playing when running a game on an iOS 13.1 device. The same game works on an iOS 12 device.

**Steps to reproduce:**

- Import a WAV file to a project
- Insert AudioStreamPlayer and either set it to auto-play or start it from the code (it makes no difference)
- Run the game on an iOS 13.1 device -- there will be no audio

**Minimal reproduction project:**
[audioproblem.zip](https://github.com/godotengine/godot/files/3665476/audioproblem.zip)

**Comment by AlexRixhardson** [comment]
Sorry, I am closing this event. The devices I tested on were in the silent mode. Somehow YouTube and other music streaming apps still emitted sound, so I did not notice that.

**Comment by DanWilkerson** [comment]
Had the same thing happen to me!

**Comment by garthhumphreys** [comment]
Same here :)
