### ISSUE TITLE
Shadows on tiles with transparency

### ISSUE THREAD

**Issue by cobreen** [godotengine/godot#32419]
On Godot 3.1.1

On windows 10 pro

![example](https://i.imgur.com/UVatLv8.png)
![example](https://user-images.githubusercontent.com/22748041/65819742-c26cf300-e228-11e9-8c68-86e312825415.png)
Any tiles with transparency, and occlusion looks weird

https://gitlab.com/mr.cobreen/godot-projects (too big labyrynth "initial commit")
(It's not minimal, but it's really small)

**Comment by Calinou** [comment]
> On Godot 3.2

Could you mention the commit hash of the build you used?

**Comment by cobreen** [comment]
It's 3.1.1 downloaded from oficial site (27.04.2019)

**Comment by clayjohn** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
