### ISSUE TITLE
[Android] Using latest custom template throws error.

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#32414]
3.2 master
win10

Custom build throw me this error.I have compiled android_source.zip from the master.

No build apk generated at: 
./android/build/build/outputs/apk/debug/build-debug-unsigned.apk

WARNING: _update_custom_build_project: No adding of application tags because could not find last tag for <application: android:icon="@drawable/icon"
     At: platform/android/export/export.cpp:1897
ERROR: _export_project_to_path: Failed to export the project for platform 'Android'.
   At: editor/project_export.cpp:973

**Comment by gamergamesz** [comment]
@m4gr3d

**Comment by akien-mga** [comment]
Confirmed on this pre-alpha1 test build: https://downloads.tuxfamily.org/godotengine/3.2/dev.bf1c81adf
This would be a blocker for 3.2 alpha 1 as custom Android exports are one of the most anticipated features.
