### ISSUE TITLE
GIProbe compression setting has no benefit and slightly reduces performance.

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot#32427]
**Godot version:** 
3.1

**OS/device including version:** 
Windows 10

**Issue description:**
The compression setting of the GIProbe node has no benefits. The file size of the bake data isn't smaller compared to when it's uncompressed. The size of an exported project with compressed data is exactly the same as a project without compression. I also compared the framerate of a scene with and without compression(V-sync was turned off so I could have a unlimited framerate). They're almost the same however the compressed scene actually has a lower average framerate.

**Comment by Calinou** [comment]
I think we would be better off removing compression support in GIProbe entirely, as it always looked broken in my experience.

**Comment by akien-mga** [comment]
Fixed by #41471.
