### ISSUE TITLE
Cannot decompose or compose basic types in Visual Script

### ISSUE THREAD

**Issue by fire** [godotengine/godot#32420]
**Godot version:**
b0f0e0e2fc95743adccf76ce82696be5b9553536

**OS/device including version:**
Windows 10

**Issue description:**

Unable to compose or decompose basic types to scalar values in visual script.

Example:

> It's impossible to go from vector3 to a float input.

This is from visual shaders.

![unknown](https://user-images.githubusercontent.com/32321/65820638-86ae3b00-e1e0-11e9-8053-55977740312f.png)

We can't do this in Visual Script.

These are the basic types. Will get a list of compose and compose special vs nodes in the next post.

![unknown](https://user-images.githubusercontent.com/32321/65820670-bfe6ab00-e1e0-11e9-96f0-2d01270a3821.png)

**Comment by fire** [comment]
* Vector2 Compose
* Vector2 Decompose
* Rect2 Compose
* Rect3 Decompose
* Vector3 Compose
* Vector3 Decompose
* Transform 2D Compose
* Transform 2D Decompose
* Plane Compose
* Plane Decopose
* Quat Compose
* Quat Decompose
* AABB Compose
* AABB Decompose
* Basis Compose
* Basis Decompose
* Transform Compose
* Transform Decompose

**Comment by willnationsdev** [comment]
Shouldn't this go in Proposals, technically? It sounds like an enhancement.

**Comment by fire** [comment]
I mean it is a bug.. that we cannot represent certain things in vs.

![image](https://user-images.githubusercontent.com/32321/65820899-7b104380-e1e3-11e9-8a19-3485dff2bdce.png)

However, I can rewrite the report if you want.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/65820899-7b104380-e1e3-11e9-8a19-3485dff2bdce.png)

This is not discoverable and has bad ux for the compose functionality.

**Comment by willnationsdev** [comment]
Yeah, I agree with you that the discoverability is an issue. But since it is possible to edit the fields, just with bad usability, the change is about improving the workflow (an enhancement), not fixing an erroneous state or something (a bug).

I mean, personally I don't care where it is, but I think for consistency it would be better to put it where other things like it go.

**Comment by fire** [comment]
It's impossible to go from vector3 to a float input. That's the bug. I suggested compose and decompose to fix it.

The other stuff is ux and doesn't matter.

How does this work, I do I move the issue?

**Comment by willnationsdev** [comment]
Oh, if it's impossible then I guess it is a bug. Either way then.

As for how to move it, I think there is a way to transfer issues. Or you would just create a new one and close this one.

**Comment by swarnimarun** [comment]
Exposed the functionality properly. :+1:

**Comment by swarnimarun** [comment]
The functions are named Construct and Deconstruct as what their specific classes are named as.
