### ISSUE TITLE
Confusing Array typecasting creates duplicates

### ISSUE THREAD

**Issue by mcardellg** [godotengine/godot#32423]
**Godot version:**
3.1.1 Mono

**OS/device including version:**
Windows 10 PC

**Issue description:**
Creating variables typecase as Array without instancing the array produces duplicate/same array.
Not sure if this is by design but it`s rather counter intuitive if it is.

**Steps to reproduce:**
Add the bit of code below to a node and run the node, the result looks like this:
[Test a, Test b] : [Test a, Test b]. a == b : True
{Test_c:Test c} : {Test_d:Test d}. c == d : False
The dictionaries are working as expected but I would have expected the Arrays to have also created unique objects. 
Expected result:
[Test a] : [Test b]. a == b : False
{Test_c:Test c} : {Test_d:Test d}. c == d : False

**Minimal reproduction project:**
```
extends Node

var a : Array
var b : Array
var c : Dictionary
var d : Dictionary

func _ready():
	a.append("Test a")
	b.append("Test b")
	print(a, " : ", b, ". a == b : ", a==b)
	
	c.Test_c = "Test c"
	d.Test_d = "Test d"
	print(c, " : ", d, ". c == d : ", c==d)

```

**Comment by hungrymonkey** [comment]
```
extends SceneTree

var a : Array
var b : Array
var c : Dictionary
var d : Dictionary

func _init():
	a.append("Test a")
	b.append("Test b")
	print(a, " : ", b, ". a == b : ", a==b)
	
	c.Test_c = "Test c"
	d.Test_d = "Test d"
	print(c, " : ", d, ". c == d : ", c==d)
	quit()
```

```
[Test a] : [Test b]. a == b : False
{Test_c:Test c} : {Test_d:Test d}. c == d : False
```
I cant replicate your issue.

```
 [Test a, Test b] : [Test a, Test b]. a == b : True
```
Why does array look different from your code?

**Comment by mcardellg** [comment]
Thanks for the swift response (and sorry for my slightly slow one).
Only difference I see here is "extends SceneTree" rather than "extends Node" - I attached my script to a Node (just one node as the only one in the scene). Literally just a node with this script attached.
I don`t know how to run a script with "extends SceneTree" so cannot try it your way. Let me know how to and I`ll try it.

**Comment by hungrymonkey** [comment]
@mcardellg  it should not really matter. I change to SceneTree because I did not want to create the entire project. Your bug is probably not in the code you presented.

**Comment by mcardellg** [comment]
@hungrymonkey - As mentioned this bit of code constitutes the entirety of the code in the minimal project I created to demonstrate the bug. I felt in unnecessary to actually post a zip of the project because of it's simplicity. However to try and get some momentum here is the entire project, such as it is: [ArrayBug](https://1drv.ms/u/s!Aup_NDH7UAIvg589B4FPPDyJ2TELgw?e=cRgVaa)

It is not actually holding me up as I have found replacing "var a : Array" with "var a := []" fixes the issue, but it seems like something quite fundamental.
Did you test with mono? Could something specific to my local Godot environment (preferences etc) affect it do you think?

**Comment by hilfazer** [comment]
That's a known issue and fixed on master:
https://github.com/godotengine/godot/issues/24134

**Comment by mcardellg** [comment]
Ah, sorry, I failed to find that issue when I looked before.
Thanks for the info.
