### ISSUE TITLE
Editor and Executable scale popups differently

### ISSUE THREAD

**Issue by Pixdigit** [godotengine/godot#32443]
**Godot version:**
3.1.1 stable 

**OS/device including version:**
xUbuntu 18.08

**Issue description:**
In my project I have a popup that is opened upon button click. The popup along with other menu items are beneath a Node2D with scale `Vector2(0.5, 0.5)`. In the editor, when made visible, the popup scales according to the Node2D parent. However when the project is executed and the popup is opened via `PopupPanel.popup()` it retains it original scaling and is thus twice as large.

**Steps to reproduce:**
Create a new 2D scene and a menu with a popuppanel in it that is opened via code. Then make the popuppanel visible in the editor and set the scale on the Node2D to something other than `Vector2(1, 1)`. The size of the popup should not be different within the editor and the project when run.

**Minimal reproduction project:**
See https://gitlab.com/Pixdigit/sodoko/tree/godot_issue
I know it's not really minimal but it should be minimal enough. For the effect open the multiplayer lobby.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(the provided project is not minimal enough)

**Comment by akien-mga** [comment]
No answer, so closing.
