### ISSUE TITLE
Unchecking nodes when merging from scene doesn't work

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#32445]
**Godot version:** 3.1.1.stable

**OS/device including version:** Windows 10 18362

**Issue description:** When unchecking a node in **Merge From Scene** panel the node is still considered even if not selected

**Steps to reproduce:**

![MergeFromScene](https://user-images.githubusercontent.com/37383316/65893501-6b793200-e37e-11e9-9a35-eafa04bafcb0.gif)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
This just adds the node with all its children. Unchecking doesn't matter here, same happens if you select only A from the beginning.

**Comment by Muller-Castro** [comment]
> This just adds the node with all its children. Unchecking doesn't matter here, same happens if you select only A from the beginning.

The problem also happens with siblings nodes
