### ISSUE TITLE
Custom Viewport children of 2D/3D type can't be locked

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#32446]
**Godot version:** 3.1.1.stable

**OS/device including version:** Windows 10 18362

**Issue description:** If you add a Viewport node and add 2D or 3D child nodes the lock & lock children buttons won't work for those nodes

**Steps to reproduce:**

![LockBug](https://user-images.githubusercontent.com/37383316/65895141-56ea6900-e381-11e9-8369-433ae0cf07ae.gif)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Might be related to #20619

**Comment by codecustard** [comment]
Duplicate of : #30910

It was deliberately disabled by @reduz to fix some other https://github.com/godotengine/godot/issues/1383

**Comment by akien-mga** [comment]
Closing as duplicate of #30910.
