### ISSUE TITLE
"Save Paths as Relative" should be ON by default

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3244]
I think this option should be turned on by default. Are there any issues with it? 
I don't see any downsides, and as a plus it would allow to little more easily share some scenes that were designed in mind to be small and independent parts of the main project.
Also I'm wondering is it save to turn this option on in the middle of the works on the project?
_Will mark this as 2.1 milestone since there will be some works to polish plugin system in this relase_

**Comment by reduz** [comment]
It used to be on, but it just was less intuitive to find why stuff broke
when it did. Now you can rename/move stuff from UI so this is less important

**Comment by reduz** [comment]
I think the option also at this point, given we can now move around files and keep dependencies fixed, should be removed. Instead, I was thinking of adding an option kind of similar to what Unity has to export a "package" from a directory, with all files saved as relative.

**Comment by kubecz3k** [comment]
@reduz my thoughts on such feature are collected in this issue: https://github.com/godotengine/godot/issues/3077 Hope it might give some good amount of things to consider before actual implementation.

**Comment by akien-mga** [comment]
This issue has been obsoleted since the option was removed in 3aeafca.
