### ISSUE TITLE
orgin and grid get disapper's

### ISSUE THREAD

**Issue by selvabharathis** [godotengine/godot#32451]
When ever i add a mesh(meshInstance), the orgin and grid get disapper's.
i am using godot3.1.1,
win 10 pro x64,
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 620.

**Comment by Anutrix** [comment]
@selvabharathis Please provide more information and/or a minimum project with this bug.

**Comment by selvabharathis** [comment]
ya sure, i added the minimum project with this bug.


[test.zip](https://github.com/godotengine/godot/files/3687909/test.zip)

**Comment by clayjohn** [comment]
Can't reproduce with the provided MRP. Ubuntu 16.04, intel graphics.

**Comment by Anutrix** [comment]
Reproducible using provided MRP on Windows 10 x64, Intel Graphics 620.

**Comment by saljic** [comment]
5/17/2020 still reproducible using Godot 3.2.1 Mono version.
Intel(R) UHD Graphics 620

Steps to reproduce:

1. Create new project using GLES3
2. Create 3D Scene
3. Add Kinematic Body
4. Add MeshInstance
5. Add new CubeMesh trough inspector

Gridlines and Axis dissapears.

If i click on View i see the view origin and view grid both are checked. Unchecking and checking them does not solve anything.

**Comment by Calinou** [comment]
So far, it seems people have only managed to reproduce this on Intel graphics on Windows. This is likely to be a driver-specific issue. Someone could try contacting Intel about it.

**Comment by Calinou** [comment]
Duplicate of #3033.
