### ISSUE TITLE
Environment's Background Mode "Canvas" does not work on GLES2

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#32458]
**Godot version:**
3.2 master (1f40117)

**OS/device including version:**
Mageia 7 x86_64 Linux
Intel HD Graphics 630 + AMD Radeon RX Vega M, Mesa 19.1.7, kernel 5.2.x

**Issue description:**
When WorldEnvironment's `Background Mode` is set to `Canvas`, the screen turns black when using GLES2 for a 2D scene. It works fine in GLES3.

Comments from @clayjohn and @reduz:
```
15:25 <Akien> reduz: clayjohn: I'm trying to fix Environment's bg_mode Canvas being broken on GLES2 (renders black screen). I've noticed that it doesn't seem to be implemented at all in GLES2 contrarily to GLES3, so I tried to copy the GLES3 code and adapt to GLES2, but not working so far: https://hastebin.com/raheyorino.diff
15:26 <Akien> I guess copying the screen is not as simple as calling `storage->_copy_screen()` :P
15:28 <Akien> Any idea on how it should be done properly in GLES2?
15:29 <reduz> Akien: i think you basically have to do nothing on GLES2, it should just work
15:29 <reduz> Akien: maybe it needs some manual code for MSAA
15:32 <Akien> reduz: Oh you seem to have a good intuition. Enabling MSAA fixes it
15:32 <Akien> So it's only broken if MSAA is disabled
15:33 <reduz> that is weird, i was expecting that enabling msaa may break it
15:33 <reduz> but i guess clayjohn will have to take a look at it :P
15:35 <Akien> Actually it needs MSAA on + my diff, then it works
21:29 <clayjohn> Akien: regarding the canvas bg not working on GLES2, I can fix that when I am implementing ``SCREEN_TEXTURE`` mipmaps in GLES2. The reason it doesn't work is that both 3D and 2D render directly to ``current_rt->fbo`` in GLES2, canvas bg requires sampling from the screen_texture.
21:31 <clayjohn> If you want to fix it for testing purposes, you can do that by using ``screen_copy_effect`` instead of ``mip_maps[0].color``
21:31 <clayjohn> Akien: after my current PR is merged I will do another one that uses ``mip_maps[0].color`` instead of the hardcoded ``screen_copy_effect``
```

**Steps to reproduce:**
- Create a 2D scene (e.g. with `icon.png` as a Sprite)
- Add WorldEnvironment, set Environment's Background Mode to "Canvas"
- Enjoy the clear color

**Minimal reproduction project:**
- Minimal: [bg_mode_canvas.zip](https://github.com/godotengine/godot/files/3674996/bg_mode_canvas.zip)
- Real use case: https://github.com/quendera/TheSpinnerGame/pull/64 (use this PR to fix tabs/spaces compilation error) - this game uses Canvas bg mode to add Glow post-processing to UI elements. I PR'ed this in the past to work around the issue, but now that Glow is implemented in GLES2, a proper fix would be good: https://github.com/quendera/TheSpinnerGame/pull/63

**Comment by quendera** [comment]
Thank you @akien-mga
