### ISSUE TITLE
Tween was not added to the SceneTree!

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#32464]
**Godot version:**
![Screenshot_9](https://user-images.githubusercontent.com/1850856/65956018-16a6eb80-e452-11e9-9f2c-e489dd60195c.png)

**OS/device including version:**
![image](https://user-images.githubusercontent.com/1850856/65956055-24f50780-e452-11e9-8584-c56d3d566d75.png)

**Issue description:**
![Screenshot_7](https://user-images.githubusercontent.com/1850856/65956314-bfede180-e452-11e9-85ff-3c070e563c63.png)
![Screenshot_8](https://user-images.githubusercontent.com/1850856/65956315-bfede180-e452-11e9-8926-1fa559ce1e82.png)

I'm getting `Tween was not added to the SceneTree!` error while as you can see in the screenshot the tween and the timer nodes have been added to the scene tree before running the project.
That only happens with the alpha version of Godot. In the stable 3.1 version, it is working properly.

**Comment by KoBeWi** [comment]
Reproduction project? The fact that we can see the tree on the screenshot doesn't mean it looks like that when starting Tween.

**Comment by zaksnet** [comment]
> Reproduction project? The fact that we can see the tree on the screenshot doesn't mean it looks like that when starting Tween.

I thought this would be easily identifiable as regression of something as it has been working for the few latest alphas and the stable. If not, i will take some time to create a sample project.

**Comment by KoBeWi** [comment]
I mean, I added a Tween to the scene and started it without a problem, so it's not as simple as that. Probably requires more steps/code and that makes room for user error.

btw, new alpha builds print their version hash to the console, so you don't need to paste the version screenshot (and that text is automatically parsed by GitHub, so it's easy to find the commit).

**Comment by zaksnet** [comment]
> I mean, I added a Tween to the scene and started it without a problem, so it's not as simple as that. Probably requires more steps/code and that makes room for user error.

I see, I will try to recreate a minimum reproduction project.

> btw, new alpha builds print their version hash to the console, so you don't need to paste the version screenshot (and that text is automatically parsed by GitHub, so it's easy to find the commit).

Thank you!

**Comment by zaksnet** [comment]
Used call_deffered("start") to start the tween and all is good. As for the error, something else was broken in this version of Godot and caused the issue. I will investigate and create a new issue.

**Comment by rp181135198** [comment]
I am also facing similar problem in Godot v3.2.3 stable (custom_build).
`start: Tween was not added to the SceneTree!`
`<C++ Error> Condition "!is_inside_tree()" is true. Returned: false`
`<C++ Source> scene/animation/tween.cpp:849 @ start()`

Can anyone explain how can I solve this issue? My code was working fine in Godot v3.1.2 stable (official)

**Comment by KoBeWi** [comment]
Check if there aren't any other errors in your debugger and make sure the Tween is inside tree when using the start() method. You can for example do
```
print(tween.is_inside_tree()
tween.start()
```
If it prints false, it means there's something wrong in your code. If you are absolutely sure that it's not your error, try to make a minimal reproduction project or at least provide some exact steps to reproduce the issue. Otherwise there's not much that can be done about this.

**Comment by rp181135198** [comment]
@KoBeWi 
Thank you!! It worked..

Actually in my case, I was creating new instance of a scene in one of my script and depending upon some conditions, calling some methods of that instance (which was calling `tween.start()`). And this was happening before adding that instance object inside tree which was creating this issue.

To solve this, I simply added that instance to tree first and then called methods of that instance and it worked for me.. :smile:

**Comment by rp181135198** [comment]
@KoBeWi 
Thank you!! It worked..

Actually in my case, I was creating new instance of a scene in one of my script and depending upon some conditions, calling some methods of that instance (which was calling `tween.start()`). And this was happening before adding that instance object inside tree which was creating this issue.

To solve this, I simply added that instance to tree first and then called methods of that instance and it worked for me.. :smile:

**Comment by nightblade9** [comment]
I ran into this for a different but also interesting case. I had something calling `queue_free` on an instance, and inside that instance I had a reference to an `onready var _tween = $Tween` (same problem also happened if I called `Tween.new()`). I didn't realize that the instance was already queue_free'd or actually freed by the time it reached the tween's start method.
