### ISSUE TITLE
GraphNode port location doesn't respect Separation

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#32474]
**Godot version:**
3.2
**OS/device including version:**
ArcoLinux
**Issue description:**
GraphNode's ports don't seem to align correctly when Custom Constants/Separation is set to anything.  In this example, Separation is set to 40, but the same thing happens with other values:

![image](https://user-images.githubusercontent.com/28724859/65984373-400d4a80-e445-11e9-9b08-825775a56721.png)
(Port 2)

At first, I thought separation simply broke everything except the first port (which is positioned correctly); when attempting to drag off from a port, it would instead grab the node and move it around.  Some experimentation later, it turned out that the actual port location was just in the wrong place, and the port graphic is rendered in the right place.  There is some method to this, however: real port locations aren't where they would be without separation, but are consistently in the same, invisible spot for all but the first port.  So it seems whatever is being used to calculate that position is consistently putting it on the wrong place.

![image](https://user-images.githubusercontent.com/28724859/65985069-b65e7c80-e446-11e9-8b33-eef8bf74e7d4.png)
(Port 4)

**Comment by KoBeWi** [comment]
Any minimal project for easier testing?

**Comment by somnivore** [comment]
[graph_node_proj.zip](https://github.com/godotengine/godot/files/3684436/graph_node_proj.zip)

**Comment by KoBeWi** [comment]
Tested this in 77b1214a9

The separation works fine, but I can click only the first port. The others are unclickable :I
Works correctly in 3.1.1, but has some problem with separation between first two ports.

@somnivore Which "3.2" version did you use? Could you try a [nightly build](https://hugo.pro/projects/godot-builds/)?

**Comment by somnivore** [comment]
@KoBeWi 00417675fa186103ddfcaa37807d4c2819f709e2

What you're describing is the behavior shown in the issue; there's an invisible spot above all ports except the 1st one which lets you drag off a connection.  The little white dot graphic which represents the port is in the correct place, but the spot that lets you interact with it is higher up and thus misplaced.  Attempting to use the white dot graphic as the port's location results in dragging the node, since the interaction spot for the port is somewhere else.

Try clicking and dragging a small distance below Port 0, and you'll start dragging off a connection as shown in the image below; that connection represents Port 1, several pixels (perhaps even the number of pixels for separation?) above where Port 1 is supposed to be.

![image](https://user-images.githubusercontent.com/28724859/66173425-c5dff000-e615-11e9-8bbd-cdd227ec0710.png)

**Comment by KoBeWi** [comment]
Ah, makes sense now. Looks like the drag point uses default `separation` value, relative to previous port.

**Comment by lrgilbert** [comment]
Fixed this with pull request #37218
