### ISSUE TITLE
Control: Enter and Exit is not called when mouse is pressed

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#32472]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 7

**Issue description:**
On Controls:
Enter and Exit is not called when **mouse is pressed** (on holding mouse key) when you go over or out of the control with the mouse.

> public override void _Notification(int what)
> {
>   if (what == Control.NotificationMouseEnter)
>   {
>       Console.WriteLine("ENTER");
>   }
>   else if (what == Control.NotificationMouseExit)
>   {
>       Console.WriteLine("EXIT");
>   }
> }

**Comment by groud** [comment]
This is expected behavior. 
When you press a button, you don't want it to "unpress" while the mouse is pressed just because you got out of the boundaries of the button. It stays pressed until you release the mouse button.

**Comment by WizzardMaker** [comment]
Why don't you use the signals mouse_entered and mouse_exited?
I assume you use C#, so that should do the trick:

```
public override void _Ready() {
	Connect("mouse_entered", this, nameof(MouseEntered));
	Connect("mouse_exited", this, nameof(MouseExited));
}

public void MouseEntered() {

}
public void MouseExited() {

}
```

**Comment by TypeOverride** [comment]
> Why don't you use the signals mouse_entered and mouse_exited?
> I assume you use C#, so that should do the trick:
> 
> ```
> public override void _Ready() {
> 	Connect("mouse_entered", this, nameof(MouseEntered));
> 	Connect("mouse_exited", this, nameof(MouseExited));
> }
> 
> public void MouseEntered() {
> 
> }
> public void MouseExited() {
> 
> }
> ```

because it has the same behaviour!

**Comment by TypeOverride** [comment]
> This is expected behavior.
> When you press a button, you don't want it to "unpress" while the mouse is pressed just because you got out of the boundaries of the button. It stays pressed until you release the mouse button.

Its a problem!

Because i cant write logic with this behaviour.

**Comment by groud** [comment]
Anyway that's a duplicate of #20881

**Comment by TypeOverride** [comment]
> Anyway that's a duplicate of #20881

And here:
https://github.com/godotengine/godot/issues/23296

Well known problem. ... but old one.

**Comment by Xebeth** [comment]
I'm having issues with that one as well.

**Comment by sian2005** [comment]
Yeah same, I ended up just writing a custom mouse enter and exit signal using (`Control.get_global_rect().has_point(get_global_mouse_position())`)
