### ISSUE TITLE
Screen turns completly black if shader changed on GLES2

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#32479]
**Godot version:**
bf1c81adf4b1584470318d25fa2ef67e261874cf

**OS/device including version:**
Win10/GTX1060

**Issue description:**
![bug](https://user-images.githubusercontent.com/3036176/66022906-15c89500-e4f8-11e9-894a-359d74d5867c.gif)

**Steps to reproduce:**
Create a MeshInstance, add a shader to it and try to change...

Note: its different from #32458 - this issue happens every time the shader changed, and the screen turns completely black, not only background...

**Comment by akien-mga** [comment]
No error in the terminal?

**Comment by Chaosus** [comment]
Nope. Its also broke the change modes - so you unable to set a wireframe or overdraw modes
 
![image](https://user-images.githubusercontent.com/3036176/66023576-46113300-e4fa-11e9-8459-d32f304e9f5b.png)

**Comment by akien-mga** [comment]
I guess it's likely caused by #31845.

**Comment by Chaosus** [comment]
You right it's from that PR, I've checked

**Comment by akien-mga** [comment]
I did a quick test on Linux, AMD Radeon RX Vega M, I don''t seem to reproduce the issue:
![Screenshot_20191002_091128](https://user-images.githubusercontent.com/4701338/66024638-a8ffcb80-e4f4-11e9-99ce-023d65770b03.png)

**Comment by Chaosus** [comment]
Thats strange - Im unable to reproduce it on new project but it will on -

[AShaderTest.zip](https://github.com/godotengine/godot/files/3679881/AShaderTest.zip)

**Comment by akien-mga** [comment]
> Its also broke the render modes - so you unable to change it to wireframe or overdraw

I can confirm that render modes don't seem to change anything, but did they ever work on GLES2? Maybe they're only implemented in GLES3.

> Thats strange - Im unable to reproduce it on new project but it will on -
> 
> [AShaderTest.zip](https://github.com/godotengine/godot/files/3679881/AShaderTest.zip)

This project also seems to work fine for me, weird.

**Comment by Zireael07** [comment]
IIRC render modes are GLES3 only?

**Comment by Calinou** [comment]
@Zireael07 That's correct, see #27018.

**Comment by Chaosus** [comment]
Hmm..  probably some environment bug, in the scene

**Comment by Chaosus** [comment]
Anyways, after cleanup the *.gen shader files again Its no longer happens ( which is weird cuz deleting it several times before but it have no effect)

**Comment by avril-gh** [comment]
I can confirm that render modes don't seem to change anything, but did they ever work on GLES2?

they did'nt worked on GLES2 for a long time, i remember i had to use GLES3 mode when i been working on vertex shader's to see wireframe preview.
