### ISSUE TITLE
draw_polygon() function is MUCH slower in master than in 3.1.1

### ISSUE THREAD

**Issue by PostPollux** [godotengine/godot#32476]
**Godot version:**
Current Master (bf1c81adf4b1584470318d25fa2ef67e261874cf) -> slow
Official 3.1.1 -> fast

**OS/device including version:**
 Linux Manjaro, i7-8850U, Intel UHD 620

**Issue description:**
There seems to be a massive performance drop compared to Godot 3.1.1 when drawing a polygon in the _draw() Function.

Using my reproduction project on my machine has the following results:

With 2000 points (number_of_points = 1000):
Master: 4 fps
3.1.1 : 38 fps

With 200 points (number_of_points = 100)
Master: 300 fps
3.1.1: 810 fps

With 20 points (number_of_points = 10)
Master: 810 fps
3.1.1: 840 fps

**Steps to reproduce:**
Start the included project both in 3.1.1 and in current master. Compare the framerate!

**Minimal reproduction project:**
[draw_performance_regression_test.zip](https://github.com/godotengine/godot/files/3678682/draw_performance_regression_test.zip)

**Comment by KoBeWi** [comment]
Did you compile with `target=release_debug`?

**Comment by PostPollux** [comment]
I have no idea. I just ran "scons -j8 platform=x11" in the main directory. So I guess not.

**Comment by volzhs** [comment]
I compiled 3.1 and 3.2 `release_debug` with current head.

`var number_of_points : int = 1000`

Godot 3.1.2 8f3fea205 - fps 75\~77
Godot 3.2.alpha bf1c81adf - fps 66\~77

it seems there is a slight slower but not noticible.

**Comment by KoBeWi** [comment]
Sooo this is another "regression" issue about speed, caused by wrong compiler flags. FYI, with default flags you end up with a build that compiles faster, but runs _a lot_ slower.

Maybe the compiling docs could be updated to mention this? Something more emphatic than a note about production use.

**Comment by PostPollux** [comment]
Oh, sorry, I missed that. Ok I'll compile it with the correct compiler flags and try again. Thanks for letting me know! If the problem is gone I'll close the issue.

**Comment by PostPollux** [comment]
Ok, everything fine with `target=release_debug`. Thanks again for your quick help. Next time I won't make that mistake again :)
