### ISSUE TITLE
Log creation fails first time when Enable File Logging is on

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#32488]
**Godot version:**
09bf1b35c

**OS/device including version:**
Win10 64-bit

**Issue description:**
Godot fails to create a log when enabling logging in the Project Settings and using it along with a custom user directory name.

![GwgJbsMumH](https://user-images.githubusercontent.com/13004169/66032519-33085e00-e50e-11e9-8698-c8b369f0d38f.png)

This is related to debug builds, and only happens the first time its run.  It appears code executed later creates the directory, so the next run it will locate the folder and create a log.

**Steps to reproduce:**
1. Create a new project and change the following project settings.

2. Set a custom directory name.
![godot windows opt tools 64_fTRXvlJY9G](https://user-images.githubusercontent.com/13004169/66031939-14559780-e50d-11e9-9978-244d1631a0cb.png)

3. Enable logging.
![godot windows opt tools 64_pJ9bE2MgMj](https://user-images.githubusercontent.com/13004169/66031943-161f5b00-e50d-11e9-9b57-7c705921fa4d.png)

4. Export a debugging version of the project.  (Without running it, or delete the custom directory if it was created at some point.)

5. Run the built project and examine the console and the app data folder.

**Minimal reproduction project:**

Build this with a debugging template: [Log Creation Fails First Time.zip](https://github.com/godotengine/godot/files/3680305/Log.Creation.Fails.First.Time.zip)

The relevant project settings are:
```
[application]

config/name="Log Creation Fails First Time"
run/main_scene="res://Node2D.tscn"
config/use_custom_user_dir=true
config/custom_user_dir_name="Log Test"
config/icon="res://icon.png"

[logging]

file_logging/enable_file_logging=true
```

**Comment by akien-mga** [comment]
Confirmed in the current master branch. It's also reproducible without setting a custom user directory name, activating file logging is sufficient to trigger it in a project whose `user://` directory hasn't been created yet.
