### ISSUE TITLE
Some of the functions in the document header are not sorted alphabetically, but in the description they are.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#32501]
**Godot version:**
3.2.alpha.custom_build. 71d6990e1

**Issue description:**
In description of Control node `can_drop_data` function is below `accept_event`

![Screenshot_20191002_211308](https://user-images.githubusercontent.com/41945903/66075105-252cfa00-e55b-11e9-8ea1-82c83a6836bf.png)

**Comment by akien-mga** [comment]
As seen on the screenshot, the first part art `virtual` functions, which are also listed alphabetically in their own section (with `_` being before `a` in the alphanumeric sorting).

But yeah, the description section should likely use the same ordering.

**Comment by hbina** [comment]
Which file should I be looking at here?
