### ISSUE TITLE
Linux export with embedded PCK fails with ERR_FILE_CORRUPT

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#32513]
**Godot version:**
3.2 master (bf1c81af), test build: https://downloads.tuxfamily.org/godotengine/3.2/dev.bf1c81adf/

**OS/device including version:**
Mageia 7 x86_64

**Issue description:**
When exporting https://github.com/KOBUGE-Games/jetpaca for Linux with the embedded PCK option enabled, the export fails with `ERR_FILE_CORRUPT` (so `fixup_embedded_pck()` is not satisfied).

This is with export templates built on the official buildsystem. Notable build options that could influence this are `debug_symbols=no use_static_cpp=yes use_lto=yes`. Building with GCC 8.

Even though the export fails and editor raises an error, the binary is still properly exported, and the PCK seems included, as it runs the game fine.

Note: contrarily to #32310, the Linux binaries are not signed. They are also not `strip`-ed beyond `debug_symbols=no`.

**Steps to reproduce:**
- Download https://downloads.tuxfamily.org/godotengine/3.2/dev.bf1c81adf
- Export a project to Linux with embedded PCK (tested both 32-bit and 64-bit, release and debug)

**Comment by akien-mga** [comment]
The issue doesn't seem to happen with *signed* Windows templates.

**Comment by RandomShaper** [comment]
I'll have a look ASAP.

**Comment by akien-mga** [comment]
BTW, I had a hunch that it could be that it uses the wrong `gcc-ar` and `gcc-ranlib` as we use Ubuntu 14.04 and `gcc-8` is an extra package that we install, not the default GCC 4.8 version Ubuntu shipped with.

And while the logs mention calling `gcc-ranlib` and `gcc-ar`, they seem to be properly set as symlinks to their versions from the GCC 8 distribution:
```
ls /usr/bin/gcc* -l
lrwxrwxrwx. 1 root root     14 Aug 31 18:32 /usr/bin/gcc -> /usr/bin/gcc-8
-rwxr-xr-x. 1 root root 775888 Apr 25  2018 /usr/bin/gcc-4.8
lrwxrwxrwx. 1 root root     22 Jul  5 14:10 /usr/bin/gcc-8 -> x86_64-linux-gnu-gcc-8
lrwxrwxrwx. 1 root root     17 Aug 31 18:32 /usr/bin/gcc-ar -> /usr/bin/gcc-ar-8
-rwxr-xr-x. 1 root root  26968 Apr 25  2018 /usr/bin/gcc-ar-4.8
lrwxrwxrwx. 1 root root     25 Jul  5 14:10 /usr/bin/gcc-ar-8 -> x86_64-linux-gnu-gcc-ar-8
lrwxrwxrwx. 1 root root     10 Apr  7  2014 /usr/bin/gcc-nm -> gcc-nm-4.8
-rwxr-xr-x. 1 root root  26968 Apr 25  2018 /usr/bin/gcc-nm-4.8
lrwxrwxrwx. 1 root root     25 Jul  5 14:10 /usr/bin/gcc-nm-8 -> x86_64-linux-gnu-gcc-nm-8
lrwxrwxrwx. 1 root root     21 Aug 31 18:32 /usr/bin/gcc-ranlib -> /usr/bin/gcc-ranlib-8
-rwxr-xr-x. 1 root root  26968 Apr 25  2018 /usr/bin/gcc-ranlib-4.8
lrwxrwxrwx. 1 root root     29 Jul  5 14:10 /usr/bin/gcc-ranlib-8 -> x86_64-linux-gnu-gcc-ranlib-8
```

So that shouldn't be the culprit.

It's worth nothing that they're from Ubuntu 14.04's old binutils though:
```
gcc-ranlib-8 --version
GNU ranlib (GNU Binutils for Ubuntu) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by samvila** [comment]
Hi @RandomShaper , any chance to have this fix for 3.2 Final? We are about to get the full 3.2 release and this is still not working.

**Comment by RandomShaper** [comment]
The problem is due to the _pck_ section missing from the template binaries.

When I developed this, I added a comment about maybe adding an CI check to check its presence (https://github.com/godotengine/godot/pull/24086#issuecomment-446373891).

Now, regarding why it's absent, I think it's up to the linker. Which version of `ld` is being used?

**Comment by akien-mga** [comment]
> Now, regarding why it's absent, I think it's up to the linker. Which version of `ld` is being used?

GNU binutils 2.24, same as in https://github.com/godotengine/godot/issues/32513#issuecomment-537868093
We also build with `use_lto=yes use_static_cpp=yes`.

**Comment by RandomShaper** [comment]
Works for me with 2.30 (with and without LTO). I've not been able to find a proper changelog to try to explain what's the relevant difference.

**Comment by akien-mga** [comment]
You can build the container we use for the official buildsystem with https://github.com/godotengine/build-containers/blob/master/Dockerfile.ubuntu-64
(see `build.sh` for usage instructions).

Then the in-container build script amounts to:
```
export BUILD_NAME=official
export SCONS="scons -j${NUM_CORES} verbose=yes warnings=no progress=no"
export OPTIONS="debug_symbols=no use_static_cpp=yes use_lto=yes"
export CC="gcc-8"
export CXX="g++-8"

$SCONS platform=x11 CC=$CC CXX=$CXX $OPTIONS tools=yes target=release_debug
mkdir -p /root/out/tools
cp -rvp bin/* /root/out/tools
rm -rf bin

$SCONS platform=x11 CC=$CC CXX=$CXX $OPTIONS tools=no target=release_debug
$SCONS platform=x11 CC=$CC CXX=$CXX $OPTIONS tools=no target=release
mkdir -p /root/out/templates
cp -rvp bin/* /root/out/templates
rm -rf bin
```

With `/root/out` being mounted to copy the binaries outsides of the container.
