### ISSUE TITLE
Two buttons are missing their mapping on Sony DS4 Controller.

### ISSUE THREAD

**Issue by alex-evelyn** [godotengine/godot#32537]
**Godot version:**
3.2-dev

**OS/device including version:**
Tested on MacOS Mojave 10.14.6

Should Effect All Versions.

Edit: Forgot to put Controller Model Number: CUH-ZCT2U

*Turns out my controller has id 030000004c050000cc09000000010000 which falls under Generic PS4 Controller in the mappings file. There are currently only mappings for Linux and OSX, but they appear to be the same exact string other than that. Does this controller work natively on Windows?

**Issue description:**
The PS4 Logo button has button id 16 (which is equal to JOY_BUTTON_MAX). This is because it is registered with Godot, but not added to the enum. This is made apparent by using `Input. get_joy_button_string(ButtonID)`.

The share button just straight up does not show up when using `_input(...)`. ~Godot believes the share button to be the rectangle pad in the middle of the controller. It is not.~ (I was wrong, it is mapped as the select button). ~This button once added should be marked as the 17th button in the enum with the JOY_BUTTON_MAX set to 18.~ (The share button shows up as Button 8 when the unmapped button return is turned on during compile time).

**The Enum**
https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/main/input_default.cpp#L1128-L1145

**Steps to reproduce:**
Test buttons against `get_joy_button_string(...)`. Find one does not show up at all and the other just triggers the JOY_BUTTON_MAX error.

**Minimal reproduction project:**
None Provided

Edit:

Found enum with JoyButton ints:

https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/core/os/input_event.h#L62-L154

**Comment by alex-evelyn** [comment]
I recompiled my copy of Godot with https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/main/input_default.cpp#L763-L767 re-enabled (although with a modified return line). The share button shows up as Button 8.

The new return line is `return _button_event(p_device, p_button, p_pressed);` which just has p_last_id removed.

**Comment by alex-evelyn** [comment]
I added the two missing buttons to the mapping and once Godot finished compiling (and I tested the mapping works), I'll send in a pull request.

**Comment by alex-evelyn** [comment]
I got the logo button working perfectly. I just need to make sure the share button is mapped properly. Apparently I can use Steam to help me generate the mappings for the [SDL Mappings](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/README.md).

**Comment by bruvzg** [comment]
> Apparently I can use Steam to help me generate the mappings for the SDL Mappings.

Godot doesn't support 2.0.6+ style (with half axis and inversion modifiers (+,-,~)) SDL mapping (see related issues #8368, #26544), mapping for newer controller might be already in the included database, but is not loaded correctly.

**Comment by alex-evelyn** [comment]
I noticed. I started using Gamepad Tool to find the button mappings. It appears that the share button is b8, the select is b13, and guide is b12.

My Controller id (same thing is generated by Steam and Gamepad Tool) is 030000004c050000cc09000000010000.

I had to add a button called share to the sdl mapping and I increased the max supported buttons to 18. One for Guide (Logo Button) and one for Share. I am currently compiling Godot to make sure the share button works. If it does, I will do further testing tomorrow to make sure this doesn't break other controllers (I believe I can test with a Wiimote).

**Comment by alex-evelyn** [comment]
It's the guid. I just had my game print the GUID.

Godot thinks my GUID is 4c05000000000000cc09000000000000.
Steam and Gamepad Tool thinks my GUID is 030000004c050000cc09000000010000.

**Comment by alex-evelyn** [comment]
Both the share button and the guide button work now. **I'll do further testing tomorrow to make sure I didn't break something else and I will create a pull request***.

The problem with the share button was not using the correct GUID. Looking at the SDL Configs, it appears my GUID only exists for OSX and I don't have Windows or Linux outside of a VM to test with (I don't know if a VM will interfere with the controller GUID). So, someone else will have to create the correct mapping for the share button.

Anyway, the other changes I made involve adding the GUIDE button to the button enum and editor inputmap list. I also made sure to give it a string to lookup by `get_joy_button_string(...)`. I did all of this for share too, but I added the sdl button map "share" as "share:b8" and I added it to the buttons list in input_default.cpp (the line under the comment `// string names of the SDL buttons in the same order as input_event.h godot buttons`).

* I wrote this commit into my custom copy of Godot with modules, so I will have to create a patch file to write it into an otherwise unmodified copy of 3.2-dev.

**Comment by akien-mga** [comment]
I don't think you should be adding new buttons to the enum, hundreds of joypads are properly described as is, including many DS4s. The "share" button is like "select" on earlier models AFAIK.

**Comment by alex-evelyn** [comment]
How should we add the share button then? The select button is already taken up by the middle rectangle on the controller.

**Comment by alex-evelyn** [comment]
Last night, I must have been on a programming high last night. Do what you want with the fix to the button detection issue. I'm going to reopen this issue so people can see this and discuss what they want out of controller input support. I'm otherwise finished with this as I already fixed the issue for myself and I already use a customized version of Godot for my game. 😊

**Comment by agameraaron** [comment]
I think you should close the issue. We should be able to still post & discuss despite you closing the issue. Godot has a milestone for of 3.2 to meet and this is issue is marked for that release.

**Comment by capnm** [comment]
@alex-evelyn we had the same issue, thanks for your patch!

Personally, I think you could try to make a pull request. I think your patch is fine - in any case all the standard PS4 buttons should be somehow predictably accessible in gdscript.

**Comment by akien-mga** [comment]
Is this fixed..?

**Comment by capnm** [comment]
> Is this fixed..?

I don't think so. 

> Edit: Though it's true that "guide" seems missing from the enum, even though it's in the SDL bindings. So that one might need to be added.

Agree, AFAICT the SDL db entry isn't accessible in Godot.
git grep ',guide:' | wc -l
746

   746	main/godotcontrollerdb.txt:16:030000005e040000ea02000001030000,Xbox One Wireless Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,**guide**:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,
