### ISSUE TITLE
Polygon face disappears upon changed position in the inspector

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#3253]
_bugsquad edit:_
- _In presented sample the dissapering polygon is imported from obj. But the bug is still valid when using ordinary Sprite3D node._
- _It's worth to mention that those objects are not be visible in the editor even after restarting Godot._ 
- _However they are still normally visible during runtime._

---

I made face polygon from Blender and export to .obj and import into Godot
There is a test scene:
https://www.dropbox.com/s/n6vpix05xfmb9py/testMoveFace.zip?dl=0

I set some postion of face in Inspector, and then face is disappear.
For example, I set translation to (0, 0, -2) and set to (0, 0, -1), now face is gone.

**Comment by kubecz3k** [comment]
I was able to reproduce this bug using 02d6669a3849c55e415f37b23b36b49f23319957 build:
![disaperingpolygon](https://cloud.githubusercontent.com/assets/6129594/12139409/aa32b47c-b460-11e5-8da2-de8361802d83.gif)
It's worth to say that the polygon is still visible in runtime.

**Comment by bojidar-bg** [comment]
Fixed by above commit, but github didn't close it....
