### ISSUE TITLE
Exporting doesn't work on Android 4.4

### ISSUE THREAD

**Issue by danielkotzer** [godotengine/godot#32542]
**Godot version:**
3.1.1

**OS/device including version:**
GT-193011 Android 4.4.2

**Issue description:**
Exporting doesn't work, even though Android 4.4 is in the range of minimum system target. 
if I use GLES 2 it works better but then no scene is loaded

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
What do you mean by "doesn't work"? If you export a GLES3 project, it's normal, this phone doesn't support OpenGL ES 3.0.

>  if I use GLES 2 it works better but then no scene is loaded

What does "it works better" mean?

There really isn't enough information to help you here. I have a GT-9300 (Samsung Galaxy S3) and it runs fine with GLES2 projects (running LineageOS 14.1 I think - Android 7.1.2).

**Comment by danielkotzer** [comment]
On OpenGL ES 2 the only thing not working so far is loading a scene:

`	current_scene = load("model/"+file_name+".scn").instance()
	$World_Geometry.add_child(current_scene)
`

All I see is a background color, non of the content of the scene is there, even though it works fine on the editor and on exporting to Windows exe file.

**Comment by akien-mga** [comment]
Can you share the project?

If not, are you using `WorldEnvironment` with Background mode "Canvas"?

**Comment by danielkotzer** [comment]
here is a link to my project:
[https://drive.google.com/file/d/1Lqs6ugF3eQq6dWaCqikvFKp5Z4BFE13C/view?usp=sharing](https://drive.google.com/file/d/1Lqs6ugF3eQq6dWaCqikvFKp5Z4BFE13C/view?usp=sharing)

this project is using color to detect which object the mouse has clicked on, at the moment of clicking, the viewport is covered with a texture of the last frame, and all the materials of the objects are changed to a flat color, each color is the ID of the object kept in a Dicrionary. then after the click is over and the object was identified, the objects are getting their original materials back, the cover texture is hidden again and the rendering continues as usual (Would be a good idea to add this feature as build in into the Godot engine), anyway, in iOS if I use OpenGL ES 3 it works but the captutre of the viewport imange is not working, OpenGl ES 2 on iOS gives me the same problem as with Android, the scene is not loading: this code is not working:
`current_scene = load("model/"+file_name+".scn").instance() $World_Geometry.add_child(current_scene)`

**Comment by volzhs** [comment]
first of all, in your project.zip, I could not find actual texture files `model/630-v6.jpg` and `model/630-v6_nml.jpg`

and according to `.import` content,
```
[remap]

importer="texture"
type="StreamTexture"
path.s3tc="res://.import/630-v6.jpg-3caf254588937136cb1543d91b12f436.s3tc.stex"
path.etc2="res://.import/630-v6.jpg-3caf254588937136cb1543d91b12f436.etc2.stex"
metadata={
"imported_formats": [ "s3tc", "etc2" ],
"vram_texture": true
}
```
you imported texture with `s3tc` and `etc2` format.
and I confirmed you enabled `etc` format at project setting.

now I guess you didn't **reimport** those texture files.
try **reimport** on `Import` panel.

**Comment by danielkotzer** [comment]
OK this worked, I imported the textures again and now it has loaded the
scene.

**Comment by aurodev** [comment]
I guess this issue can then be closed.

**Comment by danielkotzer** [comment]
Yes

בתאריך 23:10 ש' 5.10.2019, מאת Aurodev <notifications@github.com>:

**Comment by danielkotzer** [comment]
Thank you

בתאריך 23:10 ש' 5.10.2019, מאת Aurodev <notifications@github.com>:
