### ISSUE TITLE
Automatic indent doesn't work if there's a comment

### ISSUE THREAD

**Issue by carllacan** [godotengine/godot#32561]
**Godot version:**
Godot 3.1.1 stable official

**OS/device including version:**
Debian 9

**Issue description:**
Automatic indent after a line ending with a colon doesn't work if there is a comment after a semicolon.

**Steps to reproduce:**
1) In the code editor write a line ending in a colon followed by a comment, like this:

``if condition: # comment about the condition

2) Press intro. The editor normally autoindents the new line to the next level, but if there is a comment after the colon the new line is indented at the level of the previous line.

**Minimal reproduction project:**
Unnecessary.

**Comment by Tabas32** [comment]
Hello, can I take this?

**Comment by Calinou** [comment]
@Tabas32 It seems nobody is currently working on this issue, so yes :slightly_smiling_face:

**Comment by Tabas32** [comment]
Hello,
I am new to this. I have tried to fix this issue. Here is my commit  https://github.com/Tabas32/godot/commit/616f02e90576c899e34e9810d2dcbfa606abd4b6
What now.

**Comment by Calinou** [comment]
@Tabas32 Thanks! Please open a pull request based on your fork's branch, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for details.

**Comment by akien-mga** [comment]
Fixed by #33066.
