### ISSUE TITLE
Array.sort() always returns null

### ISSUE THREAD

**Issue by flight714** [godotengine/godot#32576]
**Godot version:** 3.1.1

**OS/device including version:** Windows 10

**Issue description:** Array.sort() always returns null

**Steps to reproduce:** Create new project, create new array variable with ints or floats in random order. call 'print(array_name.sort()' to see outcome.

**Minimal reproduction project:** https://github.com/flight714/ArrayTest

**Comment by clayjohn** [comment]
Array.sort is supposed to return null. See the docs http://docs.godotengine.org/en/latest/classes/class_array.html#class-array-method-sort

What you need to do is:

array.sort()
print(array)

**Comment by flight714** [comment]
That’s embarrassing, I didn’t notice void return in the docs...Thanks for the quick response!
