### ISSUE TITLE
A way to better organize child nodes of YSort nodes

### ISSUE THREAD

**Issue by gusthe** [godotengine/godot#3258]
Currently, if I understand correctly YSort nodes only sort direct child nodes. This can be a nightmare if you have hundreds of nodes within a single YSort node and no way to organize them. Would it be possible to add a new node that would only serve as a container within YSort nodes where their contents would be YSorted as if they were direct children of the YSort node for better organization. 

Here's what I'm thinking
>>YSort
>> >> sprite1    <---- YSorted because it is a direct child node of the YSort node
>> >> sprite2 
>> >> (New container node)
>> >> >> sprite3
>> >> >> sprite4      <---- Direct children of the new node (sprite3 and 4) would also be YSorted as if they were direct children of the YSort node like sprites 1-2

**Comment by akien-mga** [comment]
Did you try with another YSort as "(New container node)"? Or does it produce bad results?

**Comment by gusthe** [comment]
I get bad results when I try that. Sprites under it don't get YSorted.

**Comment by volzhs** [comment]
I thought this also before, but I found some problem if YSort does sort all nodes under YSort node.

* YSort
    * Node (for each unit)
        * Label (for name)
        * Sprite (for image)
        * Node (for something another)
    * Node (for each unit)
        * Label (for name)
        * Sprite (for image)
        * Node (for something another)

I don't want YSort for children of **Node (for each unit)**.
I just described my case.

**Comment by volzhs** [comment]
I tested YSort has another YSort case.

* Node2D
    * YSort 1
        * Sprite 1
        * Sprite 2
        * YSort 2
            * Sprite 3
            * Sprite 4

**YSort 2** is not sorted.
I guess YSort needs to sort YSort node too.

**Comment by gusthe** [comment]
volzhs I'm not asking for YSort to sort the children of all child nodes. I'm asking if it would be possible to add a new node for the purpose of better organization. Your first example would still work the same way it does now.

YSort 2 is actually sorted by YSort 1 in your second example, and Sprites 3 & 4, are sorted under YSort 2, but that's still no good because you need Sprite3 & 4 to be sorted under YSort 1. To see what I mean move sprites 3 or 4 to pos0,0 and run the test again you'll see that YSort 2 is being sorted by YSort 1.

**Comment by volzhs** [comment]
Oh. I tested it wrong.
Yes, you are right. YSort does sort YSort node also. I'm sorry for that.

**Comment by kubecz3k** [comment]
Sounds like this feature request is related: https://github.com/godotengine/godot/issues/3174

**Comment by reduz** [comment]
YSort just sorts children, but not children of children. The way it is
implemented is pretty much the only way it can be implemented due to
performance constraints.

**Comment by reduz** [comment]
It is also more useful the way it is currently implemented, as you really don't want to sort the sub-children. This allows to instance entire scenes which get sorted, or use intermediate nodes to change the root point that will be sorted.

**Comment by gusthe** [comment]
Again, I'm not asking for YSort to sort all children. I don't want it to do that. I'm asking if it would be possible to add a new specialized node for the purpose of organizing the contents of a YSort Node.

**Comment by volzhs** [comment]
@gusthe I think I seems so a little bit.
Anyway, in my case, I just put all necessary nodes under a single YSort node though.
