### ISSUE TITLE
Scenes instanced by a GDNative tool class cannot be deleted within the editor

### ISSUE THREAD

**Issue by Kwu564** [godotengine/godot#32583]
Godot 3.1.2

Windows 10 64 bit

I encountered an issue where I'm unable to delete scenes in the editor that I instanced using a tool class written in C++. I get a "Can't operate on nodes from a foreign scene!" dialogue if I try to select and delete an instanced scene. I believe this is related to a past issue: https://github.com/godotengine/godot/issues/12487

**Steps to reproduce:**
1. Under the main scene in the below attached project select the spatial root node and activate the toggle spawn variable once to create an instance of a test scene containing a cube.

2. Select the cube in the editor and hit delete. The above mentioned dialogue should appear.

**Link to minimal example project**
[InstanceBug.zip](https://github.com/godotengine/godot/files/3694187/InstanceBug.zip)

**Comment by 2shady4u** [comment]
Hello @Kwu564 !

This is not a bug!
To have the new instance show up in the SceneTree you will have to set the correct owner, in following manner:

`String GD_Test::spawn_scene(String scene_path) {
   ResourceLoader* reLo = ResourceLoader::get_singleton();
   Ref<PackedScene> scene = reLo->load(scene_path);

   Node* CurrentScene = scene->instance();

   add_child(CurrentScene);
   CurrentScene->set_owner(this);

   Spatial* spatial = Node::cast_to<Spatial>(CurrentScene);
   spatial->set_translation(Vector3(10,0,0));

   return "Scene spawned!";
}`
After compiling this I can properly delete the instance without running into the foreign scene issue.

More reading material regarding the owner property:
https://docs.godotengine.org/en/latest/classes/class_node.html
![Capture](https://user-images.githubusercontent.com/42484461/66834687-69a69580-ef5e-11e9-9a8b-e3c2e328d45b.PNG)

Cheers!

**Comment by Kwu564** [comment]
Ah I see, that explains it thanks!
