### ISSUE TITLE
Failure to run android app natively from editor

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#32581]
**Godot version:**
3.2.alpha
**OS/device including version:**
Arch Linux, reproduces on Android 9 and Oculus Quest
**Issue description:**
When pressing the android icon in the upper right corner to run, it fails to run on the device stating that the Intent `com.godot.GodotApp` could not be found.
**Steps to reproduce:**
1. Plug in android device, and enable USB debugging
2. Attempt to run on android device
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
I can't reproduce it. Did you build Android templates matching your editor commit?

**Comment by m4gr3d** [comment]
@creikey As @akien-mga mentioned, I've also deployed the Android app from the editor and it's working as expected.
You most likely have properly generated the Android build templates.

**Comment by creikey** [comment]
It turns out that I had an error in my build system, causing the android build templates to be about three months behind the current master. Apologies for the faulty issue.
