### ISSUE TITLE
Position marker shown out of the script editor after scrolling when on the first column

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#3259]
When writing in the script editor the little line that tells you where you are typing moves out of the script editor when at the end of the line. But when it is in the beginning of the line it stays in the script editor.
![bug](https://cloud.githubusercontent.com/assets/4701338/12163728/492bf23c-b510-11e5-9083-8f56a35a1f56.png)
https://lut.im/ZHt5f7O1sN/UMiCefso2rE93sk1.PNG

**Comment by akien-mga** [comment]
OK I've managed to reproduce the issue, but I'll phrase it somewhat differently:
- When the position marker is within a line (any position but the first one), *scrolling* horizontally on long lines (i.e. with a mouse click, not with arrow keys) will work just fine, the position marker disappears correctly when reaching the left or right end of the script editor.
- If the position marker is before the first character/first column, it will stay visible when scrolling to the right on long lines, as shown in the above screenshot.
