### ISSUE TITLE
Missing quotation for $ autocompletion if used with quoted NodePath.

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#32593]
**Godot version:**
Godot_v3.2-alpha1_win64
**OS/device including version:**
Windows 7 SP1
**Issue description:**
I typed `$` followed by `'`. Choosen a completion candidate, for example `'Control'`.
Pressed Enter. What i got was this:
`$Control'`
Expected this:
`$'Control'`
Same thing with `"`.
**Steps to reproduce:**
Place cursor after dollar, type `'` or `"`, choose a completion candidate.

**Minimal reproduction project:**
https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/EngineIssues/WrongDollarQuotedAutocomplete

**Comment by hilfazer** [comment]
It used to work properly after my changes got merged https://github.com/godotengine/godot/pull/26224

I know where it can be fixed but don't know how.
File: gdscript_editor.cpp
Function: GDScriptLanguage::complete_code
code:
```
for (List<String>::Element *E = opts.front(); E; E = E->next()) {

					String opt = E->get().strip_edges();
					if (opt.is_quoted()) {
						r_forced = true;
						String idopt = opt.unquote();
						if (idopt.replace("/", "_").is_valid_identifier()) {
							ScriptCodeCompletionOption option(idopt, ScriptCodeCompletionOption::KIND_NODE_PATH);
							options.insert(option.display, option);
						} else {
							ScriptCodeCompletionOption option(opt, ScriptCodeCompletionOption::KIND_NODE_PATH);
							options.insert(option.display, option);
						}
					}
				}
```
This line
`String idopt = opt.unquote();`
removes quotes from completion candidates regardless of `'` or `"` being between `$` and cursor.
But i don't know how to check if there's quotation after dollar in that function.

**Comment by creikey** [comment]
The issue is also present in the `get_node` code, manifesting on line 2645 of `node.cpp`, where the `quote_style` gotten from the editor definitions is not always equal to what the user types:

```C++
#ifdef TOOLS_ENABLED
	const String quote_style = EDITOR_DEF("text_editor/completion/use_single_quotes", 0) ? "'" : "\"";
#else
	const String quote_style = "\"";
#endif

	if (p_node != p_base && !p_node->get_owner())
		return;
	String n = p_base->get_path_to(p_node);
	r_options->push_back(quote_style + n + quote_style); // line 2645
	for (int i = 0; i < p_node->get_child_count(); i++) {
		_add_nodes_to_options(p_base, p_node->get_child(i), r_options);
	}
```

**Comment by creikey** [comment]
That fix would work for fixing `$` but that code is not the code that runs for when `get_node` is called

**Comment by hilfazer** [comment]
Is there a problem with `get_node` as well?

**Comment by creikey** [comment]
Yes @hilfazer it is reported here: #32688
