### ISSUE TITLE
Parse error: Spaces used for indentation in tab-indented file! 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#32612]
**Godot version:3.2 alpha 1

**OS/device including version:**
Mac OS 10.14.6

**Issue description:**
When open 3.1 projects in 3.2 alpha 1, the output this error.
Another similar error is: 
Tabs used for indentation in space-indented file!

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by qarmin** [comment]
From Godot 3.2, each file must have indentations created with spaces or tabs, but you cannot mix them together.

**Comment by AlexHolly** [comment]
I expected 'Convert Indent On Save' to fix all indent errors but it doesn't help in this case, is it a bug?

**Comment by qarmin** [comment]
Already exists easy way to convert indents to spaces or tabs(but not automatically)
![Screenshot_20191007_182441](https://user-images.githubusercontent.com/41945903/66330102-09956b00-e930-11e9-87b1-beadb09671bc.png)

**Comment by AlexHolly** [comment]
In 3.1.1 it shows no error but in Godot version:3.2 alpha 1 it does.

It catches empty lines with spaces as invalid indent which is new, it should convert them, 
Using 'Convert Indent to Spaces' is doing nothing in this case.
```
func _ready():
	print("")
   
	print("")
```

**Comment by qarmin** [comment]
By default Godot convert 4 spaces to tabulator.
I see here only 3 spaces

**Comment by girng** [comment]
whelp, i've got about 20k lines of gds to go through, disgonnabegood.jpg
edit: actually, holy crap this error is actually making my code look way nicer. i have tons of indents n stuff all over the place lmao

**Comment by Calinou** [comment]
PS: One can set up [pre-commit](https://pre-commit.com/) with a bunch of [predefined hooks](https://github.com/Calinou/escape-space/blob/master/.pre-commit-config.yaml) to clean up files automatically on every commit :slightly_smiling_face:
