### ISSUE TITLE
Curve add point between two existing points

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3261]
Is there a way to add a point between two points?
It always adds to the last point

![auswahl_027](https://cloud.githubusercontent.com/assets/4741886/12162116/5e292040-b4fe-11e5-9d4e-9afd6271c426.png)

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/commit/aa63b86febad156d148a5268534ce3012573d4b8
Still not fixed.

**Comment by KoBeWi** [comment]
Is it about this?
![image](https://user-images.githubusercontent.com/2223172/57988358-9462ef80-7a8d-11e9-93f7-1a188de9b5b6.png)
Seems to be possible now with the Select Point tool.

**Comment by Zireael07** [comment]
I think this is about scripting (adding points in between in editor has been possible for quite some time)

**Comment by AlexHolly** [comment]
It is a bit confusing that selecting a point is also there to add a point I always tried the "Add Point" button.
