### ISSUE TITLE
[Mono] Plane intersect methods returning Vector3(0, 0, 0)

### ISSUE THREAD

**Issue by wfowler1** [godotengine/godot#32614]
**Godot version:**
3.1.1
**OS/device including version:**
Windows 10
**Issue description:**
Per the documentation at [https://docs.godotengine.org/en/3.1/classes/class_plane.html](https://docs.godotengine.org/en/3.1/classes/class_plane.html) Plane.intersect_3, Plane.intersect_ray and Plane.intersect_segment will return null if no intersection is found. However, in C#/Mono, value types cannot be null, so instead these methods return Vector3(0, 0, 0). This isn't good, since (0, 0, 0) could be a valid intersection point but we have no way to know if it was the actual intersection or an invalid result. A better result might be to return Vector3(float.NaN, float.NaN, float.NaN).
**Steps to reproduce:**
Try to use any of these three methods from C# using data which won't actually intersect. You can use Intersect3 with planes:
(0, 0, 1), 0
(0, 0, 1), 1
[any other plane]

**Comment by Zylann** [comment]
Could we make it return `Nullable<Vector3>`?

**Comment by wfowler1** [comment]
`Nullable<Vector3>` would probably work as well.
As far as returning a `bool` with an `out` parameter, this is the approach Unity3D took for its raycasts and it works fairly well, though I'm not sure it's the cleanest implementation.
Really the main issue is knowing whether there actually was an intersection or not. However this is done, it shouldn't yield a result which could potentially be valid.

**Comment by aaronfranke** [comment]
Another option, if we want to use purely value types, is to return `new Vector3(Mathf.Inf, Mathf.Inf, Mathf.Inf)` since infinity is easier to compare than `NaN` (`NaN == NaN` is always false).

**Comment by NathanWarden** [comment]
I agree with Zylann about either for Nullable<Vector3> or returning bool with an out parameter since these seem to be basically self documenting. Nullable<Vector3> seems a little better since it's essentially a 1 to 1 equivalent with GDScript.

**Comment by neikeq** [comment]
I would prefer the bool and out way too.

**Comment by mwerezak** [comment]
Nullable or bool/out are the most idiosyncratic ways to do this in C# so it should probably be one of these two.

I can't think of any real pro/cons between the two so it seems like a purely stylistic difference. Returning a Vector3? (i.e. the nullable type) would more closely match the gdscript API.

The other ideas involving INF or NaN just seem awkward and weird as a longtime C# dev.

**Comment by aaronfranke** [comment]
@mwerezak Agreed, the PR I opened uses `Vector3?`, the suggestion of `INF` was just an idea. I prefer `Vector3?` over bool with out parameters personally.
