### ISSUE TITLE
instance_set_transform: Condition ' Math::is_nan(v.x) ' is true

### ISSUE THREAD

**Issue by owstetra** [godotengine/godot#32611]
**Godot version:**
Godot 3.2 Alpha1 official

**OS/device including version:**
Windows 7 x64bit

**Issue description:**
In Godot 3.1 stable this code runs fine without any problem

`get_parent().CannonYRotator.global_transform = get_parent().CannonYRotator.global_transform.interpolate_with(
get_parent().CannonYRotator.global_transform.looking_at(Vector(100,15,214),Vector3(0,1,0)),
state.get_step() * 5)`

but after running the game in the 3.2 Alpha 1 .. this code sometimes cause an Error and make the game very very laggy ( the game will not crash but it will spam the debugger )
this does not happen always .. it happen only sometimes and it happen at the beginning

and this is the Error :

```
E 0:00:14:0752   get_quat: Basis must be normalized in order to be casted to a Quaternion. Use get_rotation_quat() or call orthonormalized() instead.
  <C++ Error>    Condition ' !is_rotation() ' is true. returned: Quat()
  <C++ Source>   core/math/basis.cpp:621 @ get_quat()
  <Stack Trace>  PlayerBody.gd:47 @ _integrate_forces()
```

![Error](https://user-images.githubusercontent.com/51128638/66280574-a831b580-e8b7-11e9-8068-b75e1feb6cf0.jpg)

Edit : i really don't know how to get this error , i press F5 to run the game , it runs fine , i close the game and run it again .. this error happen .
even if i make the transform orthonomalized .. it still happen

Edit 2 : using this code rise the error : 
`self.global_transform = self.global_transform.looking_at(tar.global_transform.origin,Vector3(0,1,0))`

Error : 

```
E 0:00:02:0289   instance_set_transform: Condition ' Math::is_nan(v.x) ' is true.
  <C++ Source>   servers/visual/visual_server_scene.cpp:599 @ instance_set_transform()
```

I'm sorry if the Title does not represent the Problem
Thank you guys

**Comment by owstetra** [comment]
i think the problem is related to :
https://github.com/godotengine/godot/issues/29944

because i removed the camera transformation code from the player ... and the error is gone

**Comment by soham0243** [comment]
> i think the problem is related to :
> #29944
> 
> because i removed the camera transformation code from the player ... and the error is gone

Hello I am getting the same error in a simple car controller. What do you mean by 'camera transformation code from the player' ?
The camera only contains car(player) transformation code. But the car(player) does not contain camera transformation code.
Full source for my car controller [GODOT_3.2_simple_car_controller](https://github.com/soham0243/GODOT_3.2_simple_car_controller/tree/problem_vehicleWheel)
And I can't understand the source of error 
![Image](https://pasteboard.co/JiPiR9q.png)

**Comment by zappedfish** [comment]
I have the same error, it appears randomly and is 2x as frequent if multithreading is enabled.

Could this be reopened?

**Comment by akien-mga** [comment]
Please open a new issue, this was closed 2 years ago and the original post didn't include enough information to debug. Be sure to include a minimal reproduction project so that the error can be reproduced by contributors.
