### ISSUE TITLE
Add a "Delete content" checkbox option when removing a project

### ISSUE THREAD

**Issue by Gamepreie** [godotengine/godot#32627]
title

**Comment by mgd** [comment]
What operating system are you using?

**Comment by Calinou** [comment]
@mgd I don't think this is OS-specific. The file manipulation classes are OS-independent, we don't need to do anything specific to cater to a specific OS.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/47200, closing. (See also the [proposal](https://github.com/godotengine/godot-proposals/issues/2421).)
