### ISSUE TITLE
Cmd + R on macOS has conflict: Run Scene and Toggle Ruler

### ISSUE THREAD

**Issue by yigitozdemir** [godotengine/godot#32639]
Hello everyone.

I think there is a bug related to run scene shortcut on MacOs Mojave

Godot Version:
3.2 Alpha 1 

OS Version:
Mojave (10.14.6)

Issue Description:
On MacOs CMR + R combination hides / shows ruler. Run Scene shortcut was working perfectly on Godot 3.1 and 3.1.1. Even it still runs scene also effects to editor too.

To reproduce issue:
Create a scene and press CMD + R to run scene.

Minimal Project to Reproduce:
Empty project will be enough.

Thank for everyone's support in advance.

**Comment by akien-mga** [comment]
CC @KoBeWi

**Comment by KoBeWi** [comment]
It's about rulers, not the ruler tool.

**Comment by groud** [comment]
Any opinion about how to solve it ?
I think the shortcut is good on PC (ctrl + R) for ruler with F5/F6 for launch game/scene, I think we should keep them. 
Should we replace the run shortcut or the ruler one ? Any suggestion ?

**Comment by KoBeWi** [comment]
tbh, I don't remember the last time when I wanted to toggle the rulers (probably never). They would be fine without shortcut or with Ctrl + Shift + R.

**Comment by jabcross** [comment]
It's not really that frequent, and just two mouseclicks away.

CTRL + SHIFT + R conflicts with Soft Reload Script.

I find that shortcuts are most useful when your hands are already on the keyboard, anyways.
