### ISSUE TITLE
UNDOing a label with text doesn't updates the size preview until you click on it

### ISSUE THREAD

**Issue by Gamepreie** [godotengine/godot#32635]
**Godot version:** Godot 3.2 alpha 1

**OS/device including version:** Windows 10

**Issue description:** title

**Steps to reproduce:** Create a label, add a text to it and then hit CTRL+Z
![gletch](https://user-images.githubusercontent.com/28575885/66360968-5d657b80-e953-11e9-9ae9-460722042ff2.gif)

**Comment by KoBeWi** [comment]
Duplicate of #21803
