### ISSUE TITLE
Autocomplete for custom singletons not working

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#32644]
**Godot version:**
Tested with both 3.1 Stable and 1d9233c38

**OS/device including version:**
Windows 10

**Issue description:**
Autocomplete for the parameters of custom singletons is not working. For example:
If i have a singleton named `Global` and i try to call a function from it in another script called `execute_app` that has a parameter called `p_app`, then i will get autocomplete as far as `Global.execute_app()`. It does not show me the parameters i can pass and their types.

**Steps to reproduce:**
I'm not sure if this is expected behavior. If not, i will try to recreate it and attach a project.

**Comment by Calinou** [comment]
Closing in favor of #40537, which has more information about the issue at hand.
