### ISSUE TITLE
3d gizmos not rendering

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#32648]
**Godot version:**
31600f07d

**OS/device:**
Linux/Thinkpad

**Issue description:**
All 3d gizmos only render when hovered over

**Steps to reproduce:**
Add a spacial and hover over it

**Comment by Calinou** [comment]
Can you take a screenshot or record a GIF to demonstrate the issue?

Also, which graphics card/driver are you using?

**Comment by Jummit** [comment]
![demo](https://user-images.githubusercontent.com/28286961/66410181-f945c480-e9f1-11e9-834f-6e524e1aefcb.gif)
Driver: Mesa DRI Intel Sandybrigde Mobile
Integrated Graphics: Intel 2nd Generation Core Processor
Correct me if these values seem off, I looked it up for the first time.

**Comment by KoBeWi** [comment]
Can't reproduce in bb41f0b0c on Windows 10 x64 with NVidia GTX 1060
![image](https://user-images.githubusercontent.com/2223172/66438542-41360d00-ea2d-11e9-9832-9ee4c752d621.png)


Do you have any specific settings enabled in the project/editor that could affect it?

**Comment by clayjohn** [comment]
Also mention if GLES2 or GLES3 are used.

**Comment by Jummit** [comment]
Somehow the Manipulator Gizmo Opacity setting was set to 0. I didn't change any project settings, and it changed to that when updating to the latest build. Closing now, because this is probably hard to reproduce.
