### ISSUE TITLE
Incorrect control tooltip's placement

### ISSUE THREAD

**Issue by mrawlingst** [godotengine/godot#3264]
I'm aware that there is similar issue - Issue #1445 but this is separate from scrollbar.

Essentially, if you parent a control (such as a button) underneath a node then changed the parent's position, the tooltip for button would remain the same regardless of button's or parent's position.

I was able to reproduce this in a clean project.
This is default position when creating the parent and the button (adjusting size of both nodes for clarity -- 200, 50).
![editor_normal](https://cloud.githubusercontent.com/assets/5606120/12172694/6ba87028-b520-11e5-8525-aee11567c80d.png)

The result: 
![game_normal](https://cloud.githubusercontent.com/assets/5606120/12172715/8f26fe3e-b520-11e5-8b48-4626d52f5932.png)

However, if you decide to move the parent:
![ss 2016-01-07 at 09 18 24](https://cloud.githubusercontent.com/assets/5606120/12172735/af4a3e24-b520-11e5-9996-770029c5661d.png)

You can see that the tooltip has not moved along with the parent or the button:
![ss 2016-01-07 at 09 18 30](https://cloud.githubusercontent.com/assets/5606120/12172743/bfd4437a-b520-11e5-8ebb-c494f51bd5b0.png)

Thing to note: I built Godot from source using commit 1fe9f626e116d0ff2d373f54c8265f5b8c2ca833

**Comment by mrawlingst** [comment]
If someone can point me in the right direction to where tooltip reside in the source code, I can attempt to make a fix. I just started using Godot 2 days ago so I haven't had enough time to learn the source code.

**Comment by reduz** [comment]
I will be changing some of this code around before 2.0 so will give it a test by then

**Comment by bojidar-bg** [comment]
Given that 2.0 was released... was this actually fixed?

**Comment by vnen** [comment]
I can't reproduce, I guess it was fixed.
