### ISSUE TITLE
Visualscript float variables are not precise

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#32650]
**Godot version:**
31600f07d2

**Issue description:**
![image](https://user-images.githubusercontent.com/28286961/66401634-c4327580-e9e3-11e9-870c-2dbe710e8e06.png)

**Steps to reproduce:**
Create a new Visualscript with float variable and set it to a whole number.

**Comment by fire** [comment]
Should the variable value round for display purposes? 

I think they're showing the number as is.

**Comment by hbina** [comment]
Could be a global setting, and append `f` at the end to show that these are floats.

**Comment by aaronfranke** [comment]
Whole-number floats can be represented exactly and shouldn't be imprecise when setting directly. This issue doesn't occur on Godot 3.1, it's a regression.

**Comment by aaronfranke** [comment]
I've narrowed it down to #30776. Reverting only the changes in `editor/editor_properties.cpp` fixes this. However, there shouldn't be any precision loss in the first place.

https://www.h-schmidt.net/FloatConverter/IEEE754.html

If you insert `100`, then check the last box, you can see that the next value up in a 32-bit float is `100.00000762939453125`, so it doesn't make sense that it would ever be `100.000005`.

**Comment by akien-mga** [comment]
> I've narrowed it down to #30776. Reverting only the changes in `editor/editor_properties.cpp` fixes this. However, there shouldn't be any precision loss in the first place.

That's pretty weird as the default float step is `0.001`, so the changes in `editor/editor_properties.cpp` shouldn't impact anything. Or do you have a different default float step configured, like `0.000005`, which could explain your results?

**Comment by aaronfranke** [comment]
@akien-mga No, it's the default `0.001`. It's really weird. Here's another thing to try, if you type in `100.1234` it shows up as `100.123005`, so it's truncating to 3 digits but printing false digits at the end.

**Comment by DavidSichma** [comment]
Note: This issue affects most if not all float properties. Variables in VisualScript just don't round the numbers for display unlike other properties. You can hover over other properties to see the unrounded value.
