### ISSUE TITLE
AnimatedTexture not working with TextureAtlas

### ISSUE THREAD

**Issue by MasterGordon** [godotengine/godot#32653]
**Godot version:**
v3.2.alpha.1
**OS/device including version:**
Windows 10
**Issue description:**
If you are trying to use a TextureAtlas inside of an AnimatedTexture it doesn't play the Animation. This makes it really annoying to use AnimatedTextures with TileMaps.
**Steps to reproduce:**
https://imgur.com/a/76RF7hB
**Minimal reproduction project:**
https://github.com/MasterGordon/animatedtexturetest

**Comment by Byteron** [comment]
that's a duplicate of #30295 I guess?

**Comment by akien-mga** [comment]
Indeed. I'll link the reproduction project there.
