### ISSUE TITLE
Visual Script Variable issue

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#32656]
**Godot version:**
Godot 3.2 Alpha official release

**OS/device including version:**
Windows 10

**Issue description:**
Some nodes when created pick "Any" as their type, instead of the types they should be (vector3 for translations, rotations etc) which limit the options when dragging the output to make new nodes in case of getter nodes, and in case of setter nodes force the use of variables even if you want to set a fixed value for that node

**Steps to reproduce:**
1. Create a Visual Script
2. Create a Getter or a Setter node (Some recognize type just fine, some don't, like most under spatial don't)
The result:
![Godot VS variable bug](https://user-images.githubusercontent.com/50302479/66425118-35d3e900-ea0f-11e9-8b8b-c5a754960277.png)
(The Deconstruction node was made via standard node creation, not via output creator for the get rotation node)

**Minimal reproduction project:**
[Project.zip](https://github.com/godotengine/godot/files/3704106/Project.zip)

**Comment by aaronfranke** [comment]
This happens whenever the method originates from a parent class.

If you add "Get rotation_degrees" on a Spatial, the type is set as Vector3. If you add "Get rotation_degrees" on a MeshInstance, the type is set as Any.

I just opened #32673 which will make VisualScript check inheritance when getting type info.
