### ISSUE TITLE
Godot master have broken reimport (for scenes at least)

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#32666]
On master branch when one presses reimport button on scene, if it is in cache it is instanced instead of being loaded directly which makes unintentional behavior and breaks import scripts (i.e. filename is not set among other things). There should be some mechanism implemented, otherwise reimport now requires removing .import directory and restarting Godot which is not nice.

**Comment by fire** [comment]
Please check if https://github.com/godotengine/godot/issues/32766 fixes your issue?

**Comment by slapin** [comment]
No

**Comment by akien-mga** [comment]
Can you provide an example project that reproduces the issue?

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.

**Comment by slapin** [comment]
Great! As expected from Godot team.
