### ISSUE TITLE
Invisible icons in the SpriteFrame editor (Godot 3.2 alpha 1)

### ISSUE THREAD

**Issue by Gamepreie** [godotengine/godot#32668]
**Godot version:** 3.2 alpha 1

**OS/device including version:** Windows 10

**Issue description:** No icons in the AnimatedSprite editor, still works if you click on it.

**Steps to reproduce:** Add an AnimatedSprite > Create a SpriteFrame > Edit it

**Godot 3.2 alpha 1** (Not Working)
![image](https://user-images.githubusercontent.com/28575885/66446463-075f0980-ea21-11e9-834e-ecc7f2c1e549.png)

**Godot 3.1** (Working)
![image](https://user-images.githubusercontent.com/28575885/66446458-00d09200-ea21-11e9-81fd-43d15d5e9849.png)

**Comment by Duroxxigar** [comment]
![image](https://user-images.githubusercontent.com/16636969/66452212-a38f0d80-ea2d-11e9-895e-722d9ba40d18.png)

Cannot repro on Alpha 1 or Master. Can you upload a test project or provide more information?

**Comment by Gamepreie** [comment]
Just found out why that happened, it was because of the theme with the empty template that I added, when you remove the custom theme, you need to restart Godot (so the icons show properly).
