### ISSUE TITLE
Animation import behavior is not consistent between formats (loop/cycle, flags and optimization)

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#32678]
**Godot version:** 3.1.1

**OS/device including version:** Windows 8.1

**Issue description:** Animation import behavior is not consistent between formats.  Importing collada (dae) files flags animations ending in "loop" or "cycle" to be looping.  Other formats, such as GLTF and escn do not do this.  Also, it seems impossible to loop these animations in data if they're imported.

The animation optimizer/compression behavior also seems to behave differently between formats.  Escn files seem like they have no optimization (all frames are saved).  GLTF exporter behaves differently, so I can't confirm if the optimization is different or not, since the frames are different.

It would be nice if all the formats had a consistent behavior.  Currently, looking at the code, the importers appear to be all silo'd.  Perhaps it would make sense to have a generic post-import process to flag animations and apply optimization so the behavior is consistent.

**Steps to reproduce:**  Export an animated mesh that has an animation named something like "run-loop" with the better collada exporter and the again with the gltf exporter.  Notice that the gltf version is not looped.

**Comment by fire** [comment]
See gltf2 bug on "special names" https://github.com/godotengine/godot/issues/32363

**Comment by thirite2** [comment]
I can confirm this happens in 3.2b1. It's really irritating to keep switching "loop" back on for every animation (and that only makes them actually loop if they are imported as seperate anim .files...)

**Comment by fire** [comment]
Using this issue as a tracker

* https://github.com/godotengine/godot/issues/5823
* https://github.com/godotengine/godot/issues/32363

**Comment by fire** [comment]
https://docs.godotengine.org/en/latest/getting_started/workflow/assets/importing_scenes.html#animation-loop-loop-cycle

Current list of flags to be tracked.

**Comment by fire** [comment]
For 3.2, the various importers should be patched so they support the code needed for the flags listed at https://github.com/godotengine/godot/issues/32678#issuecomment-572749468.

Not sure how to define a standard for animation optimizer/compression behavior. So that is not part of the work.

**Comment by fire** [comment]
I've created a sample that has the import hints.

[32678-respect-import-hints.zip](https://github.com/godotengine/godot/files/4046283/32678-respect-import-hints.zip)

![image](https://user-images.githubusercontent.com/32321/72163600-fb187e80-3378-11ea-9c4d-83782b4ca105.png)

**Comment by fire** [comment]
Made a test project.

[34841 Respect Import Hints Project.zip](https://github.com/godotengine/godot/files/4046340/34841.Respect.Import.Hints.Project.zip)

**Comment by fire** [comment]
Considering this done, because in the test project both scenes from collada and gltf2 look similar and Godot now has the animation loop / cycle patches.

Will not make obj import match gltf or collada since the default import of obj is as a mesh and not as a scene. The second reason is the import obj as a scene's names are scrambled.

**Comment by jitspoe** [comment]
Awesome!  Thanks for your hard work!

**Comment by A-Lamia** [comment]
**Godot Version:** _v4.0._

**OS Version: Windows** _10._

I have used the same test blender file shared here and added a empty cube with -colonly as the doc said.

**Steps:**
Export blender file as single GLFL2 (.glb) file Add to local Godot project folder to auto import.

**Problem:**
Empty Cube being imported as a node3D

**Desired Effect:**
Empty Cube should be converted to a StaticBody with a collision node child set to BoxShape as the docs have said.

![godot windows tools 64_FxlPJjH1b](https://user-images.githubusercontent.com/6450181/88482627-d4810480-cfa5-11ea-8fcb-be2d97402ad9.png)

[32678-respect-import-hints-with-empty.zip](https://github.com/godotengine/godot/files/4977830/32678-respect-import-hints-with-empty.zip)
