### ISSUE TITLE
F5 should continue from a breakpoint instead of restarting

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#32681]
This is just a small quality of life thing, not specific to any type of project.  I'm very used to Visual Studio, where F5 both starts debugging and continues if you're at a breakpoint.  There have been a number of times where I'm stepping through a difficult to repro bug then hit F5 and end up completely restarting the game.  It would be nice if Godot behaved the same way as VS.

**Comment by Calinou** [comment]
Should we distinguish breakpoints from script errors causing the project to pause? If not, pressing <kbd>F5</kbd> will cause the project to resume after a script error, which is usually not what you want.

**Comment by mattiascibien** [comment]
I second this. When developing my LD45 entry I stumbled a lot on this as I am used to Visual Studio as my main IDE. Not sure about other people used to other IDEs, though.

**Comment by Zireael07** [comment]
F5 doing double duty as Run/Continue is extremely common across IDEs.

**Comment by Chaosus** [comment]
By default, Continue Debug is currently binded to F12, but yeah, F5 binding is more common

**Comment by jitspoe** [comment]
> 
> 
> Should we distinguish breakpoints from script errors causing the project to pause? If not, pressing F5 will cause the project to resume after a script error, which is usually not what you want (as it may be in an inconsistent state).

You can fix script errors and continue, though, right?  I know you can edit scripts while the game is running and they'll update without a restart.  I haven't actually tried doing this when there's an error.  Seems you'd always want F5 to continue.  That's how it behaves in Visual Studio.

**Comment by Calinou** [comment]
> Is this still up for consideration? 

Yes, but I suggest opening a [proposal](https://github.com/godotengine/godot-proposals/issues) as feature proposals are now tracked there (this is an historical issue).

**Comment by jitspoe** [comment]
I've opened the feature proposal here: https://github.com/godotengine/godot-proposals/issues/8068

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/8068.
