### ISSUE TITLE
GD script debugger jumping around weird places

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#32689]
Godot version: 3.1.1
OS: Windows 7 Ultimate 64bit

I am having a issue where the godot debugger is reading code inside a condition before actually checking the condition.

I don't know if it actually executes it, but currently this makes debugging really hard.

1. download this project: https://drive.google.com/open?id=1fo3fr8KEY3eLLqnh1DI_n5TZexbnZeg9

2. make sure breakpoint is in Player.gd line 31.

3. debug Player scene and press up.

4. note debugger position

5. use debugger to step into code

6. note its now at the if statement instead of the next line where it sets the animation.

7. use debugger to step into code (again)

8. note its now at where it sets its animation.

**Comment by KoBeWi** [comment]
Seems to be working correctly in 3.2.3
