### ISSUE TITLE
Search previous unexpected behaviour in built-in docs

### ISSUE THREAD

**Issue by MarqusJonsson** [godotengine/godot#32687]
**Godot version:**
3.1

**Issue description:**
When you search something in the documentation of Godot's built-in docs, you can use "Enter" key to search for next occurrence and "Shift + Enter" to search for the previous occourence(you can also use the GUI arrow buttons). When searching for previous a unexpected behaviour occours, rather than shoing the previous result of the search, it shows the first result in previous "segment" of the text(see GIF below).

![2019-10-09_17-53-46](https://user-images.githubusercontent.com/30708674/66498101-d4b71e80-eabd-11e9-84e6-9dc35175a284.gif)

**Steps to reproduce:**

1. Open some doc in the editor
2. Search something which occours multiple times within each segment of the opened doc
3. Click the search next arrow until you pass a segment where your search term occoured more than once
4. Click the search previous arrow and step back through the segment where your search term occoured more than once

**Comment by KoBeWi** [comment]
Still valid in 825ab3b
