### ISSUE TITLE
Text/LineEdit not taking input on mobile browsers

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#32680]
**Godot version:**
3.1.1 (but also previous)

**OS/device including version:**
Ubuntu 18.04 LTS / any Android phone (Android Chrome/FF tested)

**Issue description:**
TextEdit/LineEdit in mobile browser don't pop up keyboard or don't have any other way of interacting.

Nb. I'm aware of workarounds involving use of HTML input boxes and passing their content to Godot side, but that requires the creator to edit the main site (and supposedly we're not able to reuse the HTML site, so I'd have to edit it every time???)

**Steps to reproduce:**
Open https://zireael07.github.io/Veins-of-the-Earth-Godot in a mobile browser, attempt to enter player name.

**Minimal reproduction project:**
See above.

**Comment by codecustard** [comment]
You could use a prompt box to pass input into the textfield as the prompt should trigger displaying the keyboard.

**Comment by Zireael07** [comment]
As I said, I'm aware of workarounds. However, those aren't very tenable with the requirement to not reuse the HTML site, as stated in https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_for_web.html

**Comment by codecustard** [comment]
That's just basically saying not to use the exported file as some sort of template for other games. You can customize the file: https://docs.godotengine.org/en/3.1/tutorials/platform/customizing_html5_shell.html#doc-customizing-html5-shell

**Comment by SamToorchi** [comment]
Is there any solution to solve this problem?

**Comment by kalbfled** [comment]
I might be encountering this bug with Godot 3.2.1.  I use a LineEdit instance to allow the user to input his or her initials next to a high score (like an old arcade game).  This works fine on my desktop, but the LineEdit instance isn't displayed at all on Android.

My desktop: Ubuntu 18.04, Godot 3.2.1
My Android device (phone): LineageOS 16.0 (based on Android 9)

**Comment by Zireael07** [comment]
People are still running into this issue. I have limited my projects to desktop only because of this, too.
