### ISSUE TITLE
get_node() autocompletion malfunctions when single quotes are used.

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#32688]
**Godot version:**
Godot_v3.2-alpha1_win64
**OS/device including version:**
Windows 7 SP1
**Issue description:**
I've triggered autocomplete for this code
`get_node('')`
and got 
`get_node("."')`
Works fine with double quotes.
If you trigger autocomplete for this code:
`get_node(' )`
you'll get 
`get_node("." )`
not as bad as previously but i expected single quotes to be used.

**Steps to reproduce:**

**Minimal reproduction project:**
Any with at least the root node.

Related to https://github.com/godotengine/godot/issues/32593

**Comment by creikey** [comment]
I was unable to reproduce in `3.1.1 stable`, possible regression?

**Comment by dalexeev** [comment]
It seems that this is the same for all types of autocompletion.

![demo](https://user-images.githubusercontent.com/47700418/67622672-1a494a80-f825-11e9-8826-af9a727c58f6.gif)

**Godot version:** 3.2.alpha3.official
**text_editor/completion/use_single_quotes:** disabled

**Comment by creikey** [comment]
@dalexeev yes, the two things that are broken currently are
 - autocompletion with `$`
 - autocompletion with functions ( which `get_node()` is )

**Comment by creikey** [comment]
The actual bug is located around line 6500 in `text_edit.cpp`, in the function `_update_completion_candidates`, where it is supposed to add the suggestion with single quotes to the `completion_current` variable but instead ( somehow ) pushes the suggestion with double quotes while the visual box uses single quotes.
