### ISSUE TITLE
The editor remains dim (darkened) after saving a scene

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#32690]
Godot 3.2 alpha1

When I save a scene, sometimes the editor dims itself (probably because a popup opens, which is probably expected), however it remains darkened after that.
I haven't found a way to reproduce it reliably, so far it just happened 2 times after I save a scene.
The editor still works normally, it just remains much darker than usual, until another window is opened and closed.

Edit: happens almost always actually, I have it 70% of the time when saving a terrain demo I'm making.

**Comment by akien-mga** [comment]
I've also seen this happen after exporting to Android. Seems like multiple superimposed modals are not properly handled, even though there were a couple PRs trying to fix exactly that.

**Comment by burstina** [comment]
confirmed on 3.2 alpha 2

![image](https://user-images.githubusercontent.com/47447512/66707275-35548e80-ed3e-11e9-8b5d-201ffb0ac53e.png)

**Comment by Zylann** [comment]
@burstina that looks like a *brightening*... did you change the dim color? Or maybe you are on Windows, the editor is hanging and so the OS brighten the entire window including the popup? (if so you are hitting a different issue).

**Comment by burstina** [comment]
@Zylann the 2nd you wrote: "the editor is not responding and so the OS brighten the entire window including the popup".

**Comment by Shin-NiL** [comment]
I've noticed this exporting and running on Android using custom template.

![Peek](https://user-images.githubusercontent.com/4077589/67117809-ef724d00-f1b9-11e9-89b9-fc998153c01f.gif)
