### ISSUE TITLE
Cannot build Windows export template from MacOS

### ISSUE THREAD

**Issue by rafaelgdp** [godotengine/godot#32695]
**Godot version:** Master Branch, Commit 781e4f8673857b2b318e919ecb780bfad972a5a6

**OS/device including version:** MacOS Mojave 10.14.6. Macbook Pro 15" 2018.

**Issue description:** I can build for MacOS normally. However, when I try to build an export template for Windows, there are some function calls that are not recognised. Searching the internet for the solution, some people argued that sprintf_s and wcspy_s are not functions from the standard C++ Library. Maybe other functions should be used instead.

**Steps to reproduce:** Install everything you need to compile Godot from source (i.e. Python, scons, etc). Additionally, I installed mingw with brew, as recommended by the docs (brew install mingw).

**Minimal reproduction project:** I do not have a project to share, as I'm simply trying to build Godot itself for Windows from a Mac machine.

<img width="1680" alt="Screen Shot 2019-10-09 at 15 38 39" src="https://user-images.githubusercontent.com/9672536/66531444-2ec9db00-eae2-11e9-840a-277e6f2fcaf6.png">
<img width="1680" alt="Screen Shot 2019-10-09 at 15 38 48" src="https://user-images.githubusercontent.com/9672536/66531452-32f5f880-eae2-11e9-8fa7-b6483d0141ec.png">
<img width="243" alt="Screen Shot 2019-10-09 at 15 43 09" src="https://user-images.githubusercontent.com/9672536/66531461-3b4e3380-eae2-11e9-8c02-717e17f5522b.png">
<img width="995" alt="Screen Shot 2019-10-09 at 15 47 51" src="https://user-images.githubusercontent.com/9672536/66531465-3ee1ba80-eae2-11e9-9387-650e79b0f99b.png">

**Comment by bruvzg** [comment]
Try adding ` CXXFLAGS="-DMINGW_HAS_SECURE_API" ` to the scons command, it's missing from the default configuration of some MinGW distribution.

**Comment by rafaelgdp** [comment]
> Try adding `CXXFLAGS="-DMINGW_HAS_SECURE_API"` to the scons command, it's missing from the default configuration of some MinGW distribution.

Adding this flag actually solved my problem!! I have no idea what it stands for, but it made the build work! Thank you so much! By the way, I wonder if this notice should be present in the official documentation. It was really frustrating not being able to compile the engine because of silly "undefined-token" errors.

**Comment by yeonghoey** [comment]
This is just for posterity who ran into this issue,

As per https://github.com/godotengine/godot/issues/33062,
We embeded `-DMINGW_HAS_SECURE_API=1` into the build script,

which means that people don't need to specify this flag manually. 
We expect people not to see this error anymore.
