### ISSUE TITLE
Android virtual keyboard doesn't respect max length of LineEdit

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32709]
**Godot version:**
3.2 alpha

**OS/device including version:**
Android 7 on Xiaomi Redmi Note 4

**Issue description:**
When you set a maximum length for LineEdit, it works alright on desktop, but on Android you can write past the limit. It won't appear in the LineEdit, but the extra letters will show on virtual keyboard.
![image](https://user-images.githubusercontent.com/2223172/66568689-4056c580-eb6a-11e9-834a-db31187025f7.png)
What's worse, doing "Backspace" has no effect in LineEdit until you remove all the extra letters.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/3712495/ReproductionProject.zip)

**Comment by MadEqua** [comment]
Is iOS behaving differently?

I can fix this on Android this by adding a `max_input_length` parameter to `OS::show_virtual_keyboard()`
https://github.com/godotengine/godot/blob/4b3123104cb766a11a9cb93afb08af118712f012/core/os/os.h#L383
passing it into Java land to an [InputFilter](https://developer.android.com/reference/android/text/InputFilter) used when requesting a keyboard. This should stop the soft keyboard apps to accept any number of characters.

Other implementations of `OS::show_virtual_keyboard()` will just ignore the new parameter.
