### ISSUE TITLE
Navmesh not imported using glTF2 format in Godot 3.2 (regression from #30877)

### ISSUE THREAD

**Issue by Nehluxhes** [godotengine/godot#32712]
**Godot version:**
Godot 3.2alpha1

**Issue description:**
Navmeshes are not correctly imported using the gltf2 format (from Blender 2.8 if it changes anything).
A NavigationMeshInstance is correctly created but the navmesh itself is not (ie blue polygons in the editor)
Using Godot 3.1 they are correctly imported so this is a regression bug. They seems to be correctly imported too using dae files.

**Steps to reproduce:**

Create a mesh in blender, add mesh with the -navmesh suffix, export to godot with gltf2 format.

![](https://cdn.discordapp.com/attachments/477544613511692358/631556110830010378/unknown.png)

![](https://cdn.discordapp.com/attachments/477544613511692358/631556202891051011/unknown.png)

**Minimal reproduction project**

[TestNavmesh3.2.zip](https://github.com/godotengine/godot/files/3712763/TestNavmesh3.2.zip)

**Comment by Nehluxhes** [comment]
After lots of recompiling (god that's slow...) I was able to pinpoint the bug appearing in https://github.com/godotengine/godot/pull/30877
CC @JosephCatrambone 

Really not sure what would be the fix since I know next to nothing about 3D (I am just starting)

**Comment by thirite2** [comment]
I can confirm this affects 3.2b1. It works properly in 3.1.1 though. I've been using 3.1.1 solely to import my gridmap tiles.

**Comment by akien-mga** [comment]
CC @JosephCatrambone @fire @RevoluPowered @marstaik

**Comment by JosephCatrambone** [comment]
@Nehluxhes The bug in 30877 is reappearing?  Or it is now reproduced?

**Comment by Nehluxhes** [comment]
@JosephCatrambone No the bug with the blend shapes is still fixed by your pull request but as a side effect it introduced the navmesh bug I explained

**Comment by marstaik** [comment]
This issue seems more related to the import hints bug, if I am not mistaken:
https://github.com/godotengine/godot/pull/32343#issuecomment-535522158

**Comment by Nehluxhes** [comment]
@marstaik Not sure I follow you correctly since the pull request you linked was merged?
But anyways yeah when I tested Godot builds after each commit I thought at first too that this navmesh import bug was because of your changes since no import hints were working after them, but then #32343 fixed that.
They were then correctly working (well at least -col and -noimp, that's the only other ones I use and you can see them in the pictures of my original post working correctly) EXCEPT for -navmesh.
And -navmesh was already not working before your changes so I keep on trying builds with older commits and that's how I found -navmesh was working before #30877 and not after it.

You can easily test it even on the latest master, you just have to remove one exclamation mark to revert #30877 and the navmeshes are correctly imported again. Of course that would reintroduce the blend shapes bug so it's not a proper fix (even though that bug was cool looking, it should almost be a feature ^^ )
Now I believe #30877 actually just exposed a bug that went unnoticed before but as I said all that 3D stuff is over my head. It should be a good starting point to try to fix it though.

**Comment by akien-mga** [comment]
I can confirm that a local revert of #30877 fixes this issue.

#30877 obviously fixed another valid issue itself, so I guess the `if` condition needs to be made a bit more specific to handle navmesh properly?

**Comment by fire** [comment]
Can someone confirm this is fixed?

**Comment by Nehluxhes** [comment]
@fire On latest master, it is NOT fixed.
