### ISSUE TITLE
Single-axis scaling + look_at changes scale on all components [regression]

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#32711]
Godot 3.2 alpha1

I launched one of my projects with 3.2 recently and found out many 3D models I scale at runtime were much larger than usual.

I made a small project showing that:
[ScaleBroken.zip](https://github.com/godotengine/godot/files/3712669/ScaleBroken.zip)

In Godot 3.1.1, this project shows a long cube increase and decrease in Z-length while it changes orientation using `look_at`. This is expected because only the Z scale is modified.

In Godot 3.2, the cube now scales uniformly, which makes it look too thick or too thin, which is not expected.

**Comment by akien-mga** [comment]
Likely due to #26897 (and fixup #29125), CC @rodolforg.
