### ISSUE TITLE
export var(int) doesn't allow for a series of odd numbers

### ISSUE THREAD

**Issue by AzureDVBB** [godotengine/godot#32715]
**Godot version:**
3.1.1 (also in 3.2 alpha 1 release)

**OS/device including version:**
Windows 10 /PC

**Issue description:**
Trying to use an exported variable (integer) to only allow for odd numbers between 3 and 11 to be settable in the editor window.
using `export(int, 3, 11, 2) var grid_height = 3` does not work since it turns it into a list of only even numbers and 11 at the end. (grid width uses the exact same method)
![image](https://user-images.githubusercontent.com/24957704/66578841-1b6b4e00-eb7c-11e9-8d45-dc7b0f0ee24c.png)

**Example Godot Project:**
https://github.com/AzureDVBB/Issue-report-for-godot-01-

**Comment by AzureDVBB** [comment]
I agree and the fix is easy, but it did give me quite the headscratch for a while as the docs on exporting didn't delve into this gotcha. Perhaps add a small note on it?

**Comment by Calinou** [comment]
I think we should close this, as changing the snap behavior may not be desired (see https://github.com/godotengine/godot/issues/32715#issuecomment-540629288).
