### ISSUE TITLE
VS Vector3 index

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#32718]
**Godot version:**
Godot 3.2 Alpha Official Release

**OS/device including version:**
Windows 10

**Issue description:**
In Visual Script when setting Vector3 (and other such composed ones like Vector2, transform etc) fail to show index option in inspector untill "assign op" is changed from assign to some other, works fine in assign after it was changed and put back to assign

**Steps to reproduce:**
1.Create any Setter that sets composed variables such as Vectors
2.Click on them - Inspector shows no index
3.Change "Assign Op" in the inspector to any other option
4.Index Appears
5.Set "Assign Op" to what it was
6.Index is still there

**Minimal reproduction project:**
[Project.zip](https://github.com/godotengine/godot/files/3713464/Project.zip)

**Comment by bojidar-bg** [comment]
Why was this closed?

**Comment by mrjustaguy** [comment]
Sorry must have hit the close button when i was here 4 hours ago and didn't notice.. my mistake.
