### ISSUE TITLE
Ability to create 3d NavigationMesh from set of points that are defined via code

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3271]
**I might be wrong** but it looks like there is no way to define 3d navigation from the code with set of connected points. If I'm correct in 2d equivalent this can by achieved with "NavigationPolygon" node functions:

```
void add_outline( Vector2Array outline )
void add_outline_at_index( Vector2Array outline, int index )
int get_outline_count() const
void set_outline( int idx, Vector2Array outline )
Vector2Array get_outline( int idx ) const
void remove_outline( int idx )
void clear_outlines()
void make_polygons_from_outlines()
```

However I never used Godot navigation system and I might be wrong. Provided sample generate navigation data from lvl mesh, while I'm exploring a possibility to create navigation data manually based on Grid informations as well as on 'helper' nodes placed in various locations from the editor. 
It also would be good it there could be an **ability to edit generated meshes programatically** (lets say some parts of my map are in gridmap and others are made in blender, it would be good if I would be able to merge their navigations into one from the code).
_Will label it to be considered in 2.1_

**Comment by reduz** [comment]
right, nothing for this in 3D I think, will check it out in 2.1

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by HummusSamurai** [comment]
Bump?

**Comment by kubecz3k** [comment]
@HummusSamurai well why not, I will add this task to my todo :+1:

**Comment by kubecz3k** [comment]
@HummusSamurai well why not, I will add this task to my todo list :+1:
edit: But it's quite massive amount of work (I usually try to investigate those issues to some degree), so it will take me some time (probably a task for the weekend).

**Comment by Zireael07** [comment]
As far as I can tell navmeshes can be defined from vertices the same way that normal meshes can (the only difference is that you use NavMeshInstance and not SurfaceTool). 

Should probably be closed?
