### ISSUE TITLE
TextEdit created from code doesn't have correct default background

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#32724]
Godot 3.2 alpha1

When I create a `TextEdit` from code in 3.2, its background is black, while it is supposed to be dark purple like the default theme.

3.1.1:
![image](https://user-images.githubusercontent.com/1311555/66599507-4e710a00-eb9b-11e9-8117-43a412873050.png)

3.2a1:
![image](https://user-images.githubusercontent.com/1311555/66599542-5e88e980-eb9b-11e9-898c-2025fea2433a.png)

Curiously, `TextEdit` nodes that were already placed in the editor show up fine.

Project:
[TextEditCreatedFromCode.zip](https://github.com/godotengine/godot/files/3714244/TextEditCreatedFromCode.zip)

**Comment by qarmin** [comment]
Bisect shows this commit as first bad - 28d3a6051ce197579817fb56521f539f2951d7e1

**Comment by Calinou** [comment]
@qarmin Indeed, it seems like I botched the TextEdit's `background_color` in the process. I'll fix it :slightly_smiling_face:
