### ISSUE TITLE
The bookmark circle isn't drawn correctly.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#32735]
**Godot version:**
3.2 alpha 1

**OS/device including version:**
Windows 10 64bit

**Issue description:**
The bookmark circle's pixels are not correct, the right and left sides are not even. I guess this is an issue with the `draw_circle` function. It might be better if this circle is replaced with a texture so that it can be drawn nicely and have anti-aliasing. Here is a scaled up screenshot for reference.

![bookmark](https://user-images.githubusercontent.com/11450875/66619566-58026e00-ebab-11e9-925a-5959ee7181b3.png)

**Comment by akien-mga** [comment]
CC @Calinou @Paulb23

**Comment by Calinou** [comment]
It probably makes sense to use an icon for this instead, so that it can be antialiased.

**Comment by KoBeWi** [comment]
I proposed this icon at the original PR: https://github.com/alefragnani/vscode-bookmarks/blob/master/images/bookmark.svg

It's free to use AFAIK.

**Comment by Paulb23** [comment]
Yeah, breakpoints should become a large circle icon, with a banner icon similar to the one that @KoBeWi linked for bookmarks.

**Comment by CowThing** [comment]
I do like that bookmark icon. And making breakpoints large circles would help them stand out more.
