### ISSUE TITLE
VariantParser issue with "[platform:BlackBerry 10]" in export.cfg

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3274]
when open project, console says.

```
ERROR: load: ConfgFile::load - res://export.cfg:215 error: Expected Identifier
   At: core/io/config_file.cpp:184
```

**export.cfg**
```
213 : version/code=1
214 : version/name="1.0"
215 : 
216 : [platform:BlackBerry 10]
217 : 
218 : package/category="core.games"
219 : package/custom_template=""
```

All settings are gone, when open **Project Export Settings**
tested with latest commit 79c1392d17156aeb8d6a2abca16db59b1f8312cc

**Comment by akien-mga** [comment]
Support for colon was added a few commits before: b6388e6
But it could be that the issue is now the space between "BlackBerry" and "10"?

**Comment by volzhs** [comment]
@akien-mga I guess so.

**Comment by akien-mga** [comment]
Yes I had a quick look at VariantParser::get_token and I think it doesn't handle spaces properly when they are not part of a string (and a string should be delimited by double quotes, so I suppose ```[platform:"BlackBerry 10"]``` could be parsed fine - which doesn't mean that it would work afterwards as a tag though). But I guess @reduz will find the fix in a matter of seconds :)

**Comment by reduz** [comment]
damn it, i didn't expect that.. guess will have to change the code to just
behave different for these kind of files :(
