### ISSUE TITLE
Translate C# WebSocket script to WebSocketClient

### ISSUE THREAD

**Issue by Grandro** [godotengine/godot#32745]
Im trying to translate the code below into Godot but im failing to understand how to achieve that.
```
public static class Program {
    private static WebSocket Connection = null;

    static void Main(string[] args) {
        Connection = new WebSocket("wss://127.0.0.1:" + PORT+ "/", "wamp");
        Connection.SetCredentials("riot", "PASSWORD", true);
        Connection.SslConfiguration.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12;

        Connection.OnMessage += OnWebsocketMessage;

        Connection.Connect();
        Connection.Send("[5,\"OnJsonApiEvent_lol-champ-select_v1_session\"]");
        Console.ReadKey(true);
    }

    private static void OnWebsocketMessage(object sender, MessageEventArgs e) {
        var Messages = JArray.Parse(e.Data);
        Console.WriteLine(Messages);
    }
}
```
(It uses following implementation: https://github.com/sta/websocket-sharp)

My current code uses the `WebSocketClient` and the function `connect_to_url` and it connects to the url `wss://127.0.0.1:PORT`. It emits the signal `connection_error` afterwards.

How do I pass the credentials within the `WebSocketClient` in Godot?
What do I do with the used Tls12 protocol? Do i need a SSL-Certificate? How would the certificate look like?
Im finding no answer to my questions and the emission of that signal with no further information doesn't help me in any way sadly.

Any help is very much appreciated :)

**Comment by Chaosus** [comment]
The issue tracker is not a place for questions or guidance. It's used for bug tracking. Try asking on Godot Q/A (https://godotengine.org/qa), Forum (https://godotforums.org/) or Discord(https://discord.gg/zH7NUgz) channel. Sorry, but closing.

**Comment by Grandro** [comment]
Alright... maybe that should be more clarifyed then.
I was asking myself it this was the right place to ask the question and I answered that question with yes because:

- They are called issues after all and not bugs on github
- There is a bug label which seems senseless now in this case

Have a nice day

**Comment by akien-mga** [comment]
The "bug" label is because issues can also be "enhancement" or "feature request", but in all cases they related to something that should be changed in the engine. That already covers a lot of ground and we can't use the issue tracker for support requests too - for those, we have many other community platform: https://godotengine.org/community
