### ISSUE TITLE
Freeing an autoloaded Node may cause a crash later

### ISSUE THREAD

**Issue by mewin** [godotengine/godot#32749]
**Godot version:**
3.2 Alpha 3cc94b2c0b90ec1136937e2c02b9d7901d3d28b8

**OS/device including version:**
Windows 10

**Issue description:**
Calliing `queue_free()` on an autoloaded Node does not remove its reference from `GDScriptLanguage::global_array`. This may cause a crash later. In my case the crash occurred in `GDScriptLanguage::debug_get_globals()` when debugging another script.

(from [gdscript_editor.cpp:344](https://github.com/godotengine/godot/blob/617797c47cac39830282b7ea85fc38eb2d242e19/modules/gdscript/gdscript_editor.cpp#L344))
```C++
void GDScriptLanguage::debug_get_globals(List<String> *p_globals, List<Variant> *p_values, int p_max_subitems, int p_max_depth) {

	const Map<StringName, int> &name_idx = GDScriptLanguage::get_singleton()->get_global_map();
	const Variant *globals = GDScriptLanguage::get_singleton()->get_global_array();
[...]
	for (const Map<StringName, int>::Element *E = name_idx.front(); E; E = E->next()) {
[...]
		const Variant &var = globals[E->value()]; // <-- var references the deleted object
		if (Object *obj = var) {
			if (Object::cast_to<GDScriptNativeClass>(obj)) // this might crash (see backtrace.txt)
				continue;
		}
[...]
	}
}
```

Full backtrace: [backtrace.txt](https://github.com/godotengine/godot/files/3718254/backtrace.txt)

**Steps to reproduce:**
1. Create an autoload script.
2. Call `queue_free()` in `_ready()`
3. Create a scene with a button.
4. Place a breakpoint in the buttons `_pressed()` function.
5. Run the scene and click the button multiple times.

**Minimal reproduction project:**
[free_autoload.zip](https://github.com/godotengine/godot/files/3718283/free_autoload.zip) (You'll have to place the breakpoint in Button.gd:4 manually.)

**Comment by KoBeWi** [comment]
Doesn't crash in 3.2.3
