### ISSUE TITLE
Blend Shapes imported through glTF are broken

### ISSUE THREAD

**Issue by YannKervran** [godotengine/godot#32757]
**Godot version:** 3.1.1.stable.official

**OS/device including version:** 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 Sid

**Issue description:**

I have made a small grass blades pack with Shape Keys in Blender. I have exported the result in glTF and everything is fine. I can check that the values are registered in the glTF file, as I can tweak and change the values in another glTF viewer, like https://gltf-viewer.donmccurdy.com/
On that website, I have for each blade my two Shape Keys, called Morph targets.

![Capture d’écran_2019-10-11_22-44-59](https://user-images.githubusercontent.com/24250679/66684024-4f786900-ec79-11e9-92be-7788b16752a1.png)

When I import the glTF file in Godot, the resulting mesh is broken. (I show you there just one of the grass blades, for simplicity)

![Capture d’écran_2019-10-11_22-46-47](https://user-images.githubusercontent.com/24250679/66684043-60c17580-ec79-11e9-96c4-2c033a0d7528.png)

The Blend Shapes are imported but it seems that it has doubled the vertices and forget to adress the Blend Shapes correctly to some of them. If I put the Blend Shapes values to 0, eveything is fine, but if I try to rise them above 0, the mesh is broken, all faces become deconnected.

![Capture d’écran_2019-10-11_22-47-06](https://user-images.githubusercontent.com/24250679/66684067-70d95500-ec79-11e9-805a-6463bcf54489.png)

**Steps to reproduce:**
- import a glTF with Shape Keys from Blender / Morph targets
- change the values of Blend Shapes above 0

**Minimal reproduction project:** I enclose my small glTF file here for testing purpose : 
[grass_pack.zip](https://github.com/godotengine/godot/files/3719582/grass_pack.zip)

**Comment by fire** [comment]
Please try 3.2 alpha 2. It should be better there. I'll post a few exports in a few moments.

**Comment by fire** [comment]
![Blend Grass](https://media.giphy.com/media/WTX89QYDk5oQR3ETAm/giphy.gif)

**Comment by StraToN** [comment]
@fire I am not able to get the same result as yours, neither on alpha 2 nor on current master. 
![Capture d’écran de 2019-10-12 18-25-30](https://user-images.githubusercontent.com/1289207/66704607-ba7b7b80-ed1d-11e9-9cff-d945d6c46105.png)

Did you do something special in order to achieve this result?

**Comment by fire** [comment]
I spun the camera around.

To make the material show for any angle, you can also turn "culling" to be disabled. Aka double sided materials.

I haven't checked if this is as specified in the glb file. Will reply in the next post.

**Comment by fire** [comment]
I opened the glb in blender and export as gltf.

There is no materials array so:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#double-sided is not active. Therefore, the correct behaviour of one side-ness is correct.

**Comment by StraToN** [comment]
> I spun the camera around.
> 
> To make the material show for any angle, you can also turn "culling" to be disabled. Aka double sided materials.

The mesh displayed in Godot appears weird on my side (see my screenshot), even with a Material set to all MeshInstances with Culling disabled, and turning the camera around does not change anything about that.

**Comment by fire** [comment]
Do you know if it’s related to https://github.com/godotengine/godot/issues/32766 ?

> On Oct 12, 2019, at 1:33 PM, Julian Murgia <notifications@github.com> wrote:
> 

﻿
I spun the camera around.

To make the material show for any angle, you can also turn "culling" to be disabled. Aka double sided materials.

The mesh displayed in Godot appears weird on my side (see my screenshot), even with a Material set to all MeshInstances with Culling disabled, and turning the camera around does not change anything about that.

**Comment by StraToN** [comment]
@fire It seems related to #32766 yes. I effectively deleted the import file, then Godot reimported the gltf file and now it's appearing fine. Let's wait for OP to confirm, and eventually mark this one as duplicate?

**Comment by fire** [comment]
Due to no reply in 2 weeks and we believe https://github.com/godotengine/godot/issues/32766 fixes the issue. Closing.

Thanks for your report!
