### ISSUE TITLE
Websocket client doesn't work!

### ISSUE THREAD

**Issue by mthnzbk** [godotengine/godot#32755]
When I try to connect with websocket client, it is disconnected in 1-2 seconds. The websocket examples I found from Goodle are also disconnected. What is the problem?

When I test the example with the python websocket server application, I can send data once during the connection. Then the connection is terminated before the server responds.

[Godot Code](https://paste.ubuntu.com/p/sBMCqYKX5s/)

**Comment by Faless** [comment]
Can you please provide the server code too so that we can test it?

**Comment by Faless** [comment]
Also, can you please provide OS, platform, versiob, etc too?

**Comment by mthnzbk** [comment]
https://www.websocket.org/echo.html I couldn't connect to that.

https://paste.ubuntu.com/p/y3zMcPGVjg/ This local server code

https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo 
I opened the project with godot and tried it. I had the same connection problem.

The example application returns the same result with the server godot.

**Comment by mthnzbk** [comment]
Windows 10 64bit, Godot 3.1.1 and 3.2alpha2

**Comment by Faless** [comment]
@mthnzbk The only problem I was able to reproduce was with `3.1` and the remote echo server (`3.2` works fine).
All other tests I did succeeded both in `3.1` and `3.2`.
Make sure you use the correct sub-protocol if any or the server will close the connection.

With this simple this script `3.2` works in every case, `3.1` seems to have an issues with that specific server (but not the python one, nor the built-in one):
```gdscript
extends Control

var client = WebSocketClient.new()
var url = "ws://localhost:8000"
#var url = "wss://echo.websocket.org"

func _ready():
	client.connect("connection_established", self, "connected")
	client.connect("connection_error", self, "failed")
	client.connect("connection_closed", self, "failed")
	print(client.connect_to_url(url))

func _process(delta):
	if client.get_connection_status() == WebSocketClient.CONNECTION_DISCONNECTED:
		print(client.get_connection_status())
		return
	client.poll()

func connected(proto):
	print("connected")

func failed(code=1000, clean=false):
	print("closed")
```

![s1](https://user-images.githubusercontent.com/1687918/66747291-7787e800-ee84-11e9-9d12-bd94bc47f3b6.png)
![s2](https://user-images.githubusercontent.com/1687918/66747292-7787e800-ee84-11e9-9278-d163c97d6d00.png)

**Comment by mthnzbk** [comment]
Yeah. Looks like it works this way. I can't just cancel serializing when I send data like this.
`client.get_peer(1).put_var(to_json(dict).to_utf8())`

**Comment by mthnzbk** [comment]
Sorry. put_packet() run. Problem resolved.
