### ISSUE TITLE
Interface screw when any language with long name selected in script creating dialog

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#32768]
**Godot version:**
3cc94b2c0

**OS/device including version:**
Windows 10 x64

**Issue description:**
![image](https://i.imgur.com/ptxxRr4.png)

**Steps to reproduce:**
1. Open script creating window.
2. Select VisualScript.
3. See the bug.

**Minimal reproduction project:**
Not needed.

**Comment by Teashrock** [comment]
@akien-mga @groud @YeldhamDev 
UPDETO! Looks like it's not with only "VisualScript", but all aside "C#".  I suspect that interface self-adjusting to contained string's length is to blame.

**Comment by YeldhamDev** [comment]
I'm unable to reproduce this.

**Comment by Teashrock** [comment]
@YeldhamDev 
Not appeared for me too in random second attempt. Don't know, what's this.

**Comment by YeldhamDev** [comment]
Did you change the editor's scale when this happened?

**Comment by Teashrock** [comment]
@YeldhamDev
No, not at all. Fullscreen and that's it.

**Comment by fire** [comment]
It looks somewhat similiar to https://github.com/godotengine/godot/issues/32790

**Comment by YeldhamDev** [comment]
@Teashrock Can you still reproduce this?

**Comment by Teashrock** [comment]
@YeldhamDev 
Not tried intentionally, but didn't see it either.

**Comment by YeldhamDev** [comment]
I will close this for now, give me a heads-up if you see it again.
