### ISSUE TITLE
Underline in u and url tags in RichTextLabel don´t cover extra spacing while fill tag is enabled

### ISSUE THREAD

**Issue by Bethleem** [godotengine/godot#32779]
**Godot version:** 3.1.1-stable_win32

**OS/device including version:** Windows 7/PC

**Issue description:** In RichTextLabel, when you have text between [fill] [/fill] tags, it sometimes adds extra spacing for the line to match the right edge. Well, this extra spacing is unkwon for [u] and [url] tags, that not put the underline under it and creates a ugly gap.

**Steps to reproduce:**
-Create a Rich text label.
-Add some text like "[Fill]Enough text to fill [u]the line and reach the [/u]right limit, so extra spacing may be added and NO UNDERLINED[/fill]" 
-Enjoy the bug!

**Minimal reproduction project:**
Bbcode text in the example is: [fill]\t Se cree que [u]los primeros pobladores[/u][/fill]" and the output (see the not underlined gap between words "los" and "primeros"
![bug](https://user-images.githubusercontent.com/17690275/66704858-4bebed00-ed20-11e9-9c85-c6dd671880cf.png)

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by bruvzg** [comment]
For the reference, it's fixed in `master`:
<img width="257" alt="Screenshot 2021-01-25 at 09 56 05" src="https://user-images.githubusercontent.com/7645683/105676754-a1d3ac80-5ef3-11eb-90a8-c02a2c47f03b.png">

**Comment by akien-mga** [comment]
Fixed by #54296.
