### ISSUE TITLE
Open Scene with Missing dependencies is too small

### ISSUE THREAD

**Issue by trommlbomml** [godotengine/godot#32770]
**Godot version:**
Godot 3.2 Alpha 2

**OS/device including version:**
Operating System: Mac OS Mojave 10.14.6
Screen Resolution: Retina (2880x1800), HIDPI
Graphics Card: AMD Radeon R9 M370X 2GB

**Issue description:**

The missing dependecies dialog is too small to see the missing dependencies and cannot be resized:

<img width="316" alt="Bildschirmfoto 2019-10-12 um 12 21 38" src="https://user-images.githubusercontent.com/1698003/66699891-1d075400-eceb-11e9-9004-eba37369c98b.png">

**Steps to reproduce:**

The node type does not matter, simply the scenes are important.

1) Create a Scene A
2) Create Scene B
3) Instanciate Scene B as a child of A
4) Close Scene B and A
4) Delete Scene B
5) Open Scene A

**Minimal reproduction project:**
I can provide my project, but I think the steps to reproduce are easy.

**Comment by Zireael07** [comment]
What is your monitor resolution/gfx card? Is the screen retina?

**Comment by akien-mga** [comment]
CC @Calinou

**Comment by trommlbomml** [comment]
@Zireael07 I have updated the issue description according your requested information, sorry I missed that!
