### ISSUE TITLE
Large indent in docs

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#32780]
Godot 3.2 alpha2

I noticed a large indent in doc files of the editor:

![image](https://user-images.githubusercontent.com/1311555/66704911-4f7b7600-ed18-11e9-8135-1df08d990fa0.png)

Is this intended?

**Comment by Calinou** [comment]
The documentation pane is now limited to a maximum width for better readability, see https://github.com/godotengine/godot/pull/31588.

Lines of text between 45 and 80 characters are considered to be more readable than longer or shorter lines.

**Comment by Zylann** [comment]
Hmm looks like the indent is not always present... I looked again at the doc and it didn't have the indent Oo

**Comment by Zylann** [comment]
Nevermind, subtle resolution change...
