### ISSUE TITLE
Debugger pointing wrong part of an `if`

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#32782]
Godot 3.2 alpha2
Godot 3.1.1

I just had an error occur within an `elif` in my code, but the debugger confusingly pointed me at the `if` instead:

![image](https://user-images.githubusercontent.com/1311555/66705404-1ba34f00-ed1e-11e9-8f58-d1a27b39557c.png)

It reproduces fairly simply:
[DebuggerIfElse.zip](https://github.com/godotengine/godot/files/3720974/DebuggerIfElse.zip)

It might be related to https://github.com/godotengine/godot/issues/32689

**Comment by ondesic** [comment]
I was just about to report this same problem.  It is really making it hard to debug if you have a long IF/ELIF/ELSE statement
