### ISSUE TITLE
TouchScreenButton crashes with no texture defined

### ISSUE THREAD

**Issue by jonyrock** [godotengine/godot#328]
I made a simple project with a button and it crushes when I "touch" it in android emulator.
I am not sure is it a bug or I did something wrong.

https://dl.dropboxusercontent.com/u/34699053/godot_touch_test.zip

**Comment by kubecz3k** [comment]
Can someone confirm if this bug is still valid?

**Comment by akien-mga** [comment]
Ping :)

**Comment by akien-mga** [comment]
No answer, assuming this is not reproducible anymore. Please comment if you can still reproduce it.
