### ISSUE TITLE
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project 

### ISSUE THREAD

**Issue by victorbstan** [godotengine/godot#32806]
**Godot version:**
3.1.1
**OS/device including version:**
Windows 10
**Issue description:**
Failed method: LineEdit:_update_callback target ID: 1174274
Failed method: RichTextLabel:_update_callback target ID: 8215
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL grab_focus: 1
CALL show_modal: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: ToolButton:_update_callback target ID: 8217
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL grab_focus: 1
CALL show_modal: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: ToolButton:_update_minimum_size target ID: 8217
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL grab_focus: 1
CALL show_modal: 1
CALL select_all: 1
**Steps to reproduce:**
Edit configuration in display, tab between field, should see blocking in UI. And these messages in log.
**Minimal reproduction project:**

**Comment by slapin** [comment]
Need code. My Astral Probe tells me you might be doing too much stuff in single frame. Either increase message_queue_size_kb in project settings or don't do what you're doing.

**Comment by jwatte** [comment]
This happens quite frequently in very simple projects, especially when using tab to move through size fields in GUI container widgets.
See also: #34592

**Comment by akien-mga** [comment]
Superseded by #35653.
