### ISSUE TITLE
Node not found

### ISSUE THREAD

**Issue by mrdev023** [godotengine/godot#32802]
**Godot version:**
3.2 Alpha2

**OS/device including version:**
Windows 10 1903 18362.239

**Issue description:**
When i add Set or Get Node from a variable i get this error 

 modules/visual_script/visual_script.cpp:320 - Condition ' !functions.has(p_func) ' is true.
 modules/visual_script/visual_script.cpp:231 - Condition ' !functions.has(p_name) ' is true. returned: Vector2()
Ajouter un nœud
 Node not found: 2

**Steps to reproduce:**

- Create a visual script
- Add a variable
- Try to add a Setter or Getter from this variable

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/3722077/Test.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

The reproduction project is definitely broken, but creating a new script fixes it and then it can't be reproduced. Some details on how this happened would be useful, otherwise the issue could be closed.
