### ISSUE TITLE
Game is scaled to 1/4th of the screen on macOS Catalina

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#32805]
**Godot version:**
3.2 Alpha 2 -- this bug can only be reproduced when running executable built from GIT. It seems to work correctly when running binary available at https://downloads.tuxfamily.org/godotengine/3.2/alpha2/

**OS/device including version:**
MacBook Pro (Retina, Mid 2012), macOS Catalina, version 10.15

**Issue description:**
Game is rendered in the bottom left quarter of the window only, as shown in the image below. It seems that game is not properly scaled to fit the whole window in macOS Catalina. The same project works fine in Mojave.

<img width="1136" alt="Screenshot 2019-10-13 at 21 13 34" src="https://user-images.githubusercontent.com/39428930/66720607-37caed00-edff-11e9-8d2a-cd7d5ebbc244.png">

**Steps to reproduce:**
- Create a new project with Godot 3.2 Alpha 2;
- Run it in macOS Catalina;

**Minimal reproduction project:**
[CatalinaTest.zip](https://github.com/godotengine/godot/files/3722174/CatalinaTest.zip)

**Additional info**
This bug only occurs when running binary that is built from sources using "scons platform=osx". When running binary available at "https://downloads.tuxfamily.org/godotengine/3.2/alpha2/Godot_v3.2-alpha2_osx.64.zip", things seem to work properly.

What could be causing binary built from sources to behave like this?

Problematic sources were built using the latest SDK -- with Xcode Version 11.1 (11A1027)

**Comment by rafaelgdp** [comment]
I was about to report this bug too. I am also on MacOS Catalina. I just compiled the master branch, commit d0628180aef4987d24f91329e4c3378b5a037a34.

**Comment by Calinou** [comment]
See discussion in https://github.com/ioquake/ioq3/issues/418. Maybe the issue stems from official builds using an different Xcode/macOS SDK version?

**Comment by bruvzg** [comment]
I can confirm this, I guess new SDK expect all apps to support HiDPI mode, you can fix it by setting `Project Setting`->`Allow HiDPI` setting to ` true.

**Comment by bruvzg** [comment]
And setting `<key>NSHighResolutionCapable</key><false/>` is NOT a correct solution it's gonna prevent us from using HiDPI mode at all.

**Comment by rafaelgdp** [comment]
Yes, I discovered that the mouse clicks are mapped in the entire screen, but the rendering only takes place in the third quadrant.
Here's a demo video: https://youtu.be/UzGHa_7gkz8

**Comment by bruvzg** [comment]
@rafaelgdp check #32809, I do not have any mac with real retina display, but it works with simulated HiDPI mode on a normal display.

**Comment by rafaelgdp** [comment]
@bruvzg I enabled Hidpi option in the Godot Project Settings as you advised and the game worked normally. Thanks! I am on a Macbook Pro 15" 2018, MacOS Catalina 10.15.
Here's a screenshot of the same project I demoed in the video above:
<img width="1680" alt="Screen Shot 2019-10-13 at 17 24 26" src="https://user-images.githubusercontent.com/9672536/66721939-58cf1600-edde-11e9-8fc3-a16f72eab423.png">

**Comment by AlexRixhardson** [comment]
@bruvzg I tested your patch https://github.com/godotengine/godot/pull/32809 on MacBook Pro (Retina, Mid 2012) and it works perfectly. Thanks! That was a quick fix!!

**Comment by rafaelgdp** [comment]
@bruvzg I just tested the fix you coded in your branch and I confirm that it also corrected this bug for me out of the box. Even if I disable Hidpi on the project settings it also works (with a lower resolution). Thanks for the ninja contribution!
