### ISSUE TITLE
Redundand #ifdef TOOLS_ENABLED in VisualScriptEditor.cpp

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#32817]
**Godot version:**
3.2 master

In VisualScriptEditor.cpp
https://github.com/godotengine/godot/blob/680bcb1ef45c67da1b58ff3be84ca5e4fd1e40cf/modules/visual_script/visual_script_editor.cpp#L46
and 
https://github.com/godotengine/godot/blob/680bcb1ef45c67da1b58ff3be84ca5e4fd1e40cf/modules/visual_script/visual_script_editor.cpp#L1919
and https://github.com/godotengine/godot/blob/680bcb1ef45c67da1b58ff3be84ca5e4fd1e40cf/modules/visual_script/visual_script_editor.cpp#L2459

**Comment by timoschwarzer** [comment]
I don't think https://github.com/godotengine/godot/blob/680bcb1ef45c67da1b58ff3be84ca5e4fd1e40cf/modules/visual_script/visual_script_editor.cpp#L46 is redundant. (Also, removing that makes the build fail with `tools=no`)

I made a PR removing the inner ones.

**Comment by Zylann** [comment]
I would like to point out that this is an editor-specific class, and in such circumstances it should not even be added to compilation. I think the SCons file for that module needs to be changed.

**Comment by timoschwarzer** [comment]
@Zylann Thanks for pointing out! I don't know why `TOOLS_ENABLED` was added then in https://github.com/godotengine/godot/issues/6022
