### ISSUE TITLE
Compiler warning when building Godot for the `server` platform

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#32810]
**Godot version:** Git https://github.com/godotengine/godot/commit/1fed266bf5452b30376db62495f4985f6975f2c1

**OS/device including version:** Fedora 30, Clang 8.0.0

**Issue description:** Clang reports a warning when compiling Godot for the `server` platform:

```text
In file included from platform/server/os_server.cpp:31:
platform/server/os_server.h:61:11: warning: private field 'ip_unix' is not used [-Wunused-private-field]
        IP_Unix *ip_unix;
```

I'm not sure if removing it entails anything, so I prefer making an issue first just to be sure.

**Steps to reproduce:** Build Godot for the `server` platform using `scons platform=server`.

**Comment by Faless** [comment]
Yeah, that's just a very old leftover.
