### ISSUE TITLE
Evalute Selection does not insert the correct type for evaluated values.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#32811]
**Godot version:**
3.2 alpha 2

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When using evaluate selection on anything other than a number it does not insert the type into the resulting evaluated value. For example `Vector2(1, 1) + Vector2(2, 2)` becomes `(3, 3)` when it should be `Vector2(3, 3)`. This happens to everything that isn't a plain number. Sometimes it doesn't even include parentheses, which is the case with Color types.

Is this an issue with the Expression class since it is being used to evaluate lines?

**Steps to reproduce:**
Type in any expression into the script editor that uses types other than numbers, then evaluate that line. Here are a few examples:

```GDScript
Vector2(1, 1) + Vector2(2, 2) # becomes (3, 3)
Vector3(1, 1, 1).normalized() # becomes (0.57735, 0.57735, 0.57735)
Color(1, 1, 1, 1).darkened(0.5) # becomes 0.5,0.5,0.5,1
````

**Comment by akien-mga** [comment]
CC @KoBeWi

**Comment by DavidSichma** [comment]
Expression works fine, the returned Variant just isn't parsed correctly. Making a PR soon...
