### ISSUE TITLE
Alpha build with tools off will not run, missing .pck file.

### ISSUE THREAD

**Issue by SnailBones** [godotengine/godot#32816]
**Godot version:**
3.2
**OS/device including version:**
Windows 10
**Issue description:**
Compiling Godot from source with: `scons platform=windows tools=no target=release` creates a dev build that works as expected.
However, changing the command to: `scons platform=windows tools=no target=release` creates an executable `godot.windows.opt.64.exe` that, upon running, returns the error message:  "Error: Could not load game data at path '.'. Is the .pck file missing?"

I've also been unable to find build tools for the dev version, I'm currently unable to export games. (I know I shouldn't be using an Alpha version for that purpose, but it would be nice to have the option)

**Comment by akien-mga** [comment]
You pasted the same command twice. I assume the first is with `tools=yes`?

What you describe is expected behaviour, `tools=no` are the export templates, so they need to be used together with a .pck file. They don't contain the Godot editor to run (which is what `tools=yes` enables).

**Comment by akien-mga** [comment]
If you are trying to build your own export templates, see https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_windows.html#creating-windows-export-templates

You can also pick `godot.windows.opt.64.exe` as custom release package in your Windows export preset.

**Comment by SnailBones** [comment]
Thank you! You are correct about my typo. I now see that I've been misunderstanding what the tools flag does.
