### ISSUE TITLE
There's no public Android FrameLayout anymore

### ISSUE THREAD

**Issue by Shin-NiL** [godotengine/godot#32827]
**Godot version:**
3.2 alpha 2

**OS/device including version:**
Android 7

**Issue description:**
I see there were some changes on the Android platform code lately. One of them just broke my [Admob plugin](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin) (and will break my module too). 
Now I'm unable to access the ```FrameLayout layout``` property from the _Godot.java_ class, it was public before and was removed now. It was used to show the banner ads.

Is there any other way I can get the current layout?

**Comment by m4gr3d** [comment]
@Shin-NiL can you describe what you plugin is trying to do. 

Having public fields as an external api is an anti-pattern, so as the `Godot` class was cleaned up, a lot of these were removed. If there's a functionality that you require, then we should have clear explicit methods for that usecase, that don't expose the underlying class architecture.

**Comment by m4gr3d** [comment]
Looking at your plugin implementation, it seems that adding a `View SingletonBase#onMainCreateView()` method to the `SingletonBase` should cover your usecase. 
At start time, the `Godot` class would iterate through the list of registered `SingletonBase` singletons, gather the views they return from the newly added method, and add it to its layout.

**Comment by Shin-NiL** [comment]
@m4gr3d thanks for your explanations.
I just need a way to add and remove my ```AdView``` from the app layout. Before the current changes I was able to just access the reference for the layout itself. But as you said it was not a good practice.

**Comment by m4gr3d** [comment]
With the proposed `View SingletonBase#onMainCreateView()` api, you can create and return a `FrameLayout` view from that method that will be the root view for your plugin. You can then add/remove the `AdView` to/from that root layout.

On its side, the `Godot` class will ensure the root layout you returned is properly added to the its view hierarchy.

**Comment by m4gr3d** [comment]
@Shin-NiL I've added PR #32858 to add the api discussed above. Can you give it a try and see if it solves your issue.

**Comment by Shin-NiL** [comment]
@m4gr3d how am I supposed to add the AdView at anytime?

**Comment by m4gr3d** [comment]
You have [a reference to `layout`](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/066fa662f50fd2dc736135fe3761e84ce27269a3/admob-plugin/src/GodotAdMob.java#L41) in your class. Just initialize that `layout` in the new `onMainCreateView`, and it should be all that's needed.
Example:
```
@Override
public View onMainCreateView(Activity activity) {
   layout = new FrameLayout(activity);
   return layout;
}
```

**Comment by Shin-NiL** [comment]
Thanks @m4gr3d!

I did the changes as you suggested. However the ```onMainCreateView``` overridden method is not being called. After some debugging I found that in this part of the code (Godot.java):

```
		for (int i = 0; i < singleton_count; i++) {
			View view = singletons[i].onMainCreateView(this);
			
			if (view != null) {
				layout.addView(view);
			}
		}
```
the ```singleton_count``` is 0, so the ```onMainCreateView``` method is never called.

**Comment by m4gr3d** [comment]
@Shin-NiL I pushed an update that should fix the issue for calling the `onMainCreateView` method.

**Comment by Shin-NiL** [comment]
Thanks @m4gr3d, now it's working fine! I'm able to add an remove the banner view as before.
