### ISSUE TITLE
Compiling a shader with an error causes shader tab of editor to disappear in Godot 3.2.alpha2 but not in 3.1.1.stable

### ISSUE THREAD

**Issue by loganjk** [godotengine/godot#32832]
**Godot version:** 3.2.alpha2.official win64 (Classical)

**OS/device including version:** Windows 10 Pro, Intel i7-4790K, integrated GPU only (Intel HD Graphics 4600), driver igdkmd64.sys version 20.19.15.5058

**Issue description:** When the shader editor is open and the shader is compiled with an error, the Shader tab of the editor disappears. This did not happen in 3.1.1.stable, so it appears to be a regression.

**Steps to reproduce:**

In a new project, create a Node2D with a ColorRect child node with a ShaderMaterial with the following shader:

```
shader_type canvas_item;
render_mode unshaded;

void fragment() {float a=0.0;}
```

Play the project, nothing exciting, no problem.

Now, in the shader editor, change `float a=0.0` to `float a=0` and play the project again. As expected, this has caused an error. However, what is unexpected is that the Shader tab at the bottom of the editor has disappeared. Before the error, there were tabs for Output, Debugger, Audio, Animation, and Shader, but, after the error, there is no Shader tab.  The Shader tab also sometimes (but not always?) disappears after fixing a shader error and recompiling.

**Minimal reproduction project:**
[Godot Bug Report 5.zip](https://github.com/godotengine/godot/files/3725052/Godot.Bug.Report.5.zip)

**Comment by KoBeWi** [comment]
Seems like the Shader resource gets folded in the inspector, which closes the Shader Editor. It is possible to keep it open when the error appears, but the behavior seems somewhat confusing.

**Comment by akien-mga** [comment]
CC @Chaosus @bojidar-bg

**Comment by Chaosus** [comment]
It seems like the problem somewhere in CanvasItemEditorPlugin cuz spatial doesn't close if the shader error occurred.

**Comment by Chaosus** [comment]
I currently debugging this problem in VS. Found a regression commit: 3f174c86d0c688bba6900b90bb5fda1316eae04f
Because _node_renamed is emitted the selected node for some reason is set to the underlying node instead of the shader resource applied to that node, which removes the shader editor.

**Comment by akien-mga** [comment]
CC @pouleyKetchoupp

**Comment by Chaosus** [comment]
The problem is node_renamed should not be called for in-editor labels. In that case, node_renamed is called in that line https://github.com/godotengine/godot/blob/1c6d1fcf956b882fc8a14fa595b7f1e9b15e1574/editor/script_editor_debugger.cpp#L1285

**Comment by pouleyKetchoupp** [comment]
Thanks @Chaosus for investigating. I'm not sure PR #35506 would be the proper fix because it seems very specific, but it's probably a good hotfix for the time being.

I'm investigating the use case. For some reason, as @KoBeWi mentioned, the edited resource gets reset as if it was unfolded when `node_renamed` causes the tree to update. That happens only when the game is being started, and I don't think it should do that at all.

**Comment by pouleyKetchoupp** [comment]
@Chaosus @akien-mga I've just made PR #35526 to fix this case. Does it look safe enough for 3.2? It's a more generic solution so it might interfere with more systems.

**Comment by Chaosus** [comment]
Yeah, it seems to be a more correct solution than mine. Also interesting that the spatial editor does not emit shader error in the debugger but canvas_item does. But this is another issue of course.
