### ISSUE TITLE
AnimationPlayer resource list doesn't show animations

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#32839]
**Godot version:** 3.1.1.stable

**OS/device including version:** Windows 10

**Issue description:** The animations added to AnimationPlayer doesn't appear in resource list, even though resources are assigned to AnimationPlayer's variables

![image](https://user-images.githubusercontent.com/37383316/66780706-e6c30380-eea7-11e9-8a90-8bcd4da761da.png)

**Steps to reproduce:**

![AnimationPlayerRes](https://user-images.githubusercontent.com/37383316/66780718-f04c6b80-eea7-11e9-93e6-f68a4669c4e1.gif)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
This is actually not a bug, animations are excluded from the inspector on purpose because their dedicated editor is the AnimationPlayerEditorPlugin (bottom dock), not the Inspector.
