### ISSUE TITLE
help layout is messy

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#32834]
**Godot version:**
3.2 alpha 2

**OS/device including version:**
Windows 10

**Issue description:**
Help layout is messy, need a wider column layout
In this image, desktop size is 2540x1440

![image](https://user-images.githubusercontent.com/47447512/66773673-d74fb480-eebf-11e9-9804-127c78eac37c.png)
![image](https://user-images.githubusercontent.com/47447512/66773752-0a924380-eec0-11e9-9325-3cfd9d34da3f.png)

**Comment by guilhermefelipecgs** [comment]
CC @Calinou

**Comment by Calinou** [comment]
To solve this, I guess the margins should be calculated based on the help font sizes (whichever is larger, excluding the title font size).

**Comment by burstina** [comment]
> To solve this, I guess the margins should be calculated based on the help font sizes (whichever is larger, excluding the title font size).

perhaps visible area too... 2540x1440 shows a lot of wasted eomty space

> I didn't think about people using particularly large fonts for documentation when implementing #31588 🙂

aging causes vision loss... and fonts growing :P
