### ISSUE TITLE
Collision section of GridMap is outdated when compared to TileMap

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3284]
There is no way to set friction for GridMap, or set physic layer/mask. The missing properties are in the  'Collision' section of TileMap: 
![gridmapcollision](https://cloud.githubusercontent.com/assets/6129594/12211105/324048ca-b65f-11e5-84c0-3d90d1b26ea0.png)

**Comment by neikeq** [comment]
We should probably postpone this to 3.0 :)

**Comment by eon-s** [comment]
GridMap improvements will be added to 3.0 or moved to 3.1?

Another feature that needs is the possibility to have a non uniform cell size, on Y in particular.
And to be able to move the origin (it tends to center itself on [0,0,0]).

**Comment by reduz** [comment]
probably moved to 3.1

**Comment by reduz** [comment]
unless someone wants to contribute them, of course

**Comment by akien-mga** [comment]
Still relevant in the current master branch. It should now be ported to benefit from `PhysicsMaterial`.
Not critical for 3.1 though, so moving to next milestone.
