### ISSUE TITLE
Godot V3.2.alpha2 does not honor Scene Instancing with Edit Children for CollisionShape2D

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#32844]
**Godot version:**
Godot V3.2.alpha2
**OS/device including version:**
Mac OS X, Mojave
Linux Mint 19.1

**Issue description:**
If you have a scene that is **instanced**, and you select and checkoff Editable Children for that instanced scene, then changing the size of the subnode CollisionShape2D, changes it for all other scene instances.

![image](https://user-images.githubusercontent.com/930478/66795528-e724c400-eed2-11e9-9654-aaf6b7f6cc6a.png)

Expected behavior should only change the selected subnode of an instanced scene, in this case CollisionShape2D. Workaround would be to manually create each node/subnode instead of using an instanced scene, which would defeat the purpose of instancing.

**Steps to reproduce:**

1. Install _Scene Instancing Demo_ from Godot Project Templates tab.
2. Right Click on any `ball` node and checkmark `Editable Children`.
3. Select and Resize `sprite` node. Notice only the that sprite is changed.
4. Select and Resize '`collision`'  node. Notice that it resizes all on-screen collisions.

**Comment by girng** [comment]
shape needs to be made unique

right click your shape property in the inspector, select "make unique"

**Comment by KoBeWi** [comment]
Or enable "Local To Scene" option.

**Comment by wyattbiker** [comment]
Where is Local To Scene option?

**Comment by KoBeWi** [comment]
Under Resource section, when you click the CircleShape2D in the inspector. The thing is that your circle is a Resource, so it can be shared by multiple nodes.

**Comment by girng** [comment]
> Why do I have to make it Unique? 

Here is some more info
> Even if you save a built-in resource, when you instance a scene multiple times, the engine will only load one copy of it.

https://docs.godotengine.org/en/latest/getting_started/step_by_step/resources.html

**Comment by wyattbiker** [comment]
Ok thank you.
