### ISSUE TITLE
Array variables use a common array instance in the editor

### ISSUE THREAD

**Issue by AntonSalazar** [godotengine/godot#32850]
**Godot version:**
v3.1.1.stable.official, downloaded from the Godot main page as Godot_v3.1.1-stable_x11.64.zip

**OS/device including version:**
OS: KDE neon 5.16 Kernel: x86_64 Linux 5.0.0-31-generic CPU: Intel Core i5-4670K @ 4x 3.8GHz GPU: AMD/ATI Ellesmere [Radeon RX 470/480/570/570X/580/580X], AMD/ATI Ellesmere [Radeon RX 470/480/570/570X/580/580X]

**Issue description:**
Filling arrays in editor mode (tools script) does not work correctly.
In the attached example project, when you click on the `start_test` variable, two arrays are automatically filled. It was expected that it would work on only one node, and not on all.

**Steps to reproduce:**
- Open Godot.
- Open the attached `array_bug` project.
- Open `Main.tscn`.
- Choose any node.
- Set any value from 1 and above for the `array_size` variable.
- Click on `start_test` variable.
- Click on any node and you will see that its arrays have changed.

**Minimal reproduction project:**
[array_bug.zip](https://github.com/godotengine/godot/files/3728805/array_bug.zip)

**Other observations:**
If you try to delete the nodes except the very first one, reset the parameters, duplicate the nodes and perform the operation of filling the arrays again, you will notice that only one node is filled. However, if you exit the project and follow all the steps that were written above, you will get the same result - filling occurs in all nodes, except what you completed the last time.

**Comment by AntonSalazar** [comment]
I think the problem is somehow related to export(Array, ...) var ...
Is it possible that the engine allocates a common memory area for such variables?

**Comment by KoBeWi** [comment]
Already fixed in 3.2. It's broken in some other cases, but there are already issues for these.
