### ISSUE TITLE
android template compile error with module

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3285]
I tried to compile with android module (https://github.com/punto-/godot_modules/tree/master/admob)

error logs
```
Godot Android!!!!! (armv7) (with neon)
AttributeError: 'SConsEnvironment' object has no attribute 'android_module_file':
  File "/media/volzh/Dev/godot/SConstruct", line 291:
    config.configure(env)
  File "./modules/Admob/config.py", line 6:
    env.android_module_file("android/GodotAdmob.java")
```

tested with latest commit 292e8bf0ab02cf37b6ee1759a3942a57a6a69062

**Comment by reduz** [comment]
ah yeah, ant build system was removed.. module should be adapted to use
Gradle

**Comment by reduz** [comment]
I think you should try replacing:

env.android_module_library("android/GoogleAdMobAdsSdk-6.4.1.jar")

by

env.android_add_dependency("compile
'com.google.android.gms:play-services-ads:8.3.0'")

and then put the java file in a proper java dir like

android/src/org/godotengine/godot/GodotAdMob.java

and add the following line:

env.android_add_java_dir("android/src")

**Comment by volzhs** [comment]
@reduz I tried it and now different error occurred.
when ``./gradlew build``,

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > You must specify a URL for a Maven repository.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by volzhs** [comment]
I think this problem is solved now.

**Comment by reduz** [comment]
awesome, please close then :D

**Comment by reduz** [comment]
feel free to do a PR to the admob module so punto can merge it and fix it
