### ISSUE TITLE
Top/Bottom content margin does not affects TextEdits 

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#32867]
**Godot version:**
a1033aea51515cd5f831cedf9834ea376200356a

**OS/device including version:**
Win10

**Issue description:**

![content_margin_bug](https://user-images.githubusercontent.com/3036176/66917396-f8cab080-f025-11e9-85d4-04fbba69aed1.gif)

I think its incorrect ^^ in comparison, LineEdits handles it correctly

**Comment by JohnMeadow1** [comment]
Can confirm. 
Win 10, Godot 3.2.1. stable

Just wanted to report an issue on that.

**Comment by regbennyhold** [comment]
Yes, this is still in 3.2.3

**Comment by ondesic** [comment]
I can confirm this is still a bug in 3.2.4 beta 3.  It is probably a simple fix.

**Comment by dominiks** [comment]
Also confirmed for master:

* Top&bottom content margins only apply when read only - except for the scrollbars, they respect the margins
* Expand margins are ignored for all styles
