### ISSUE TITLE
Add Point2i type for integer coordinates (like in TileMap)

### ISSUE THREAD

**Issue by sheepandshepherd** [godotengine/godot#3286]
GDScript only has float vector structs (Vector2/Vector3), no integer versions, so functions like `TileMap::get_used_cells` convert their integer cell coordinates to `Vector2`s. If they're left as `Vector2`s when we do calculations on them, like adding/subtracting to get adjacent cells, the floating-point math [could introduce small error](https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems), and using the `Vector2` variable in certain ways will create bugs:
- As keys in a Dictionary, since the hashes will be different and `==` will return false
- Cast back to `int`s for the other TileMap functions, since the fractional part gets truncated, not rounded (example in GDScript: `int(1.9999999)` returns 1, not 2.)

I'm avoiding the issue by converting the coordinates to Arrays `[int(vector.x), int(vector.y)]` before using them in my pathfinding/line-of-sight functions or the Dictionary where I keep extra map info. But it'd be more convenient and efficient to have an integer vector struct that works like `Vector2`, so I made a branch implementing the existing `Point2i` type from [math_2d.h](https://github.com/godotengine/godot/blob/master/core/math/math_2d.h#L369) into GDScript, Variant, the resource formats, and those TileMap functions: https://github.com/sheepandshepherd/godot/tree/point2i
And a scene testing that the new type, operators, saving/loading, etc all work correctly: https://github.com/sheepandshepherd/godot-point2i-test

Are these integer vector types something we'd want to add to Godot? If so, I can finish adding Point2iArray and Point3i types, then make a pull request. Or otherwise, I don't mind just sticking with IntArrays, which are a simpler solution to the problem; might not warrant adding new types to GDScript.

**Comment by trollworkout** [comment]
@sheepandshepherd  While unrelated to the matter at hand it was a very interesting read that link you provided.

**Comment by Zylann** [comment]
I would like to see integer vector types too, especially when it comes to make dictionaries indexed by positions. Having a hasher for Point2i and Point3i would be good.

Not so important, but as part of https://github.com/godotengine/godot/issues/6523, why is Point2i not named Vector2i instead?

**Comment by Zylann** [comment]
I ran into a nasty bug today that reminded me of this issue. Any status to add integer vectors?

**Comment by sheepandshepherd** [comment]
I'm not sure adding new types to Variant is a good idea at this point. Is there any use case for integer vectors where you can't use just two integers or a custom class? If you need the performance of a value type, it's probably best to use GDNative instead of GDScript.

**Comment by Zylann** [comment]
Well, grid indexing is used a lot in 2D games, as well as pixel operations. It can be used in 3D too for gridmap-based games. At the moment I'm forced to review all my code and add explicit casts everywhere I used Vector2 in places integers are actually needed, because it was breaking things without being noticed.

**Comment by akien-mga** [comment]
> However, I believe that Point3 and Point2 are better names. We are already creating a new name, Point instead of Vector, so why include i? While it could be useful to have other variants, such as long, short, and byte, it would make the most since to start with int and make it the default.

All Godot vector types are float by default, and in the C++ backend there is already `Point2` (float) and `Point2i` (int). Having a new GDScript/C# `Point2` that is int would be quite inconsistent.

**Comment by aaronfranke** [comment]
Why are there both Vector2 and Point2 that both use `float`? *That* seems inconsistent to me. Why have two types to do the same thing and store the same values? Is there a good reason?

My vote would be to replace existing mentions of Point2 with Vector2 if they're so similar.

**Comment by aaronfranke** [comment]
From `math_2d.h`

    typedef Vector2 Size2;
    typedef Vector2 Point2;

This just seems to needlessly add confusion, no?

**Comment by groud** [comment]
No it's pretty useful. Once you know there are the same thing it helps understanding what a vector is about. It's used a lot in the backend code

**Comment by aaronfranke** [comment]
Is the name of a vector variable not descriptive enough? 

Isn't `Size2 size;` just as descriptive as `Vector2 size;`? Are you not only referencing `size.something()`?

**Comment by groud** [comment]
Well sometimes it helpful, sometime less. When the name is not descriptive enough, it might worth checking it type.
But anyway that's not very harmful, both three naming are quite explicit so I think it's better to keep things how they are.

**Comment by aaronfranke** [comment]
@groud If you like descriptive type names, why not change the `Point2` typedef to `Position2`? This would be more descriptive in most cases and would open up the name `Point2` for proposed `int` stuff.

**Comment by aaronfranke** [comment]
Ok... so please let me know your opinions on this. @BBric [suggested](https://github.com/godotengine/godot/issues/18324) the name Cell.

The more I think about it, the more I like the idea of calling these integer classes "Cell2" and "Cell3". I like having unique names, and I suggested "Point", but @groud considers this too vague, and he's mostly right. The name "Cell" is a unique name that fits many of the use cases.

* TileMap and GridMap have cells on a grid, as do other grid implementations.

* Dictionaries having "integer vector" keys can be thought of storing values in "Cells"

* It's already used internally (such as `TileMap::get_used_cells`) and I find myself using the word Cell in my own code to describe many "integer point/vector" things.

What do you think of the name "Cell"? Descriptive? Unique? Simple?

My main concern with such a name is discoverability, however, it would be pretty obvious what it is once you found it, and you could find it just from looking around the methods for related classes (TileMap/GridMap would use it, and there'd probably be conversions to/from Vectors, for example).

**Comment by akien-mga** [comment]
I still think names like `Point2i` or `Vector2i` are as descriptive as they should be. Trying to find another less explicit name for what *is* a integer point/position/vector is not a good idea IMO.

For example `Cell` might sound like a good idea (it does work well for TileMap and GridMap), but it bears a lot more implied meaning than what an integer coordinate would be. Cell means that you're accessing content from a table/matrix, with rows and columns. That works on TileMap and GridMap which are rectangular/parallelepipedic by nature, but does it make sense in the unrestricted 2D canvas or 3D space? In a table, all row/cell numbers within table extents are valid and may contain information. In the unrestricted canvas/space, you might have information at `(12, 31)` while `(5, 18)` may be outside your game's level and not something you want to access. But if I see a Cell with coordinates `(12, 31)`, I'd visualize a rectangular table spanning *at least* 13 rows and 32 columns, starting from `(0, 0)`.

**Comment by aaronfranke** [comment]
It will always be restricted to the nearest integer values, therefore each area has a corresponding point. The "cell" (1, 1) could be thought of as (0.5, 0.5) to (1.5, 1.5), or (1, 1) to (2, 2). For representing points in unrestricted space, you can just use vectors, correct?

**Comment by akien-mga** [comment]
That's not the point of what I wrote though...

Or actually that's exactly my point. An integer point should not be a representation of a 1x1 or 1x1x1 px bounding box centered on its location (which Cell would imply). That's *one* use case for using integer coordinates, but not the only one and should therefore not define the name of such a mathematical construct.

**Comment by reduz** [comment]
I want to get rid of Point2i and Rect2i in the next compatibility breakage. There is no practical reason to NOT use floats, they work for all practical use cases, even as cell indices. Floats can contain an integer up to 2^24, which is way more than enough for practical cases.

**Comment by Zireael07** [comment]
Practical reason to use integers instead of floats is ease of comparing (no need to use epsilon).

**Comment by groud** [comment]
Definitely, integer comparison seems very necessary to me. Point2i/Vector2i would be a great addition to gdscript.

**Comment by aaronfranke** [comment]
> as well as bit operations without requiring casts

For example, you can perform power-of-two "fposmod" operations using bitwise `&`.

I _will_ be using integer vectors in my code. I would hope to have it as a built-in Godot type so that it gets first-class support with things like conversions to/from float vectors and the ability to use them with many classes such as TileMap. If not, I'll just have to implement my own types.

**Comment by KoBeWi** [comment]
`Vector2i` was added in #36436

**Comment by aaronfranke** [comment]
Note that `Vector2i` still needs to be added to TileMap/etc, but that's tracked in #18324
