### ISSUE TITLE
Unable to Save scripts

### ISSUE THREAD

**Issue by verbalshadow** [godotengine/godot#3287]
When working with GD scripts in the git build from earlier today. The scripts do not saves or show as saved in the UI. When checking the files on disk no changes have been made. Does not respond to keyboard commands or the save in Menu.
VIDEO: [2016-01-08 20-48-27.mp4.zip](https://github.com/godotengine/godot/files/83514/2016-01-08.20-48-27.mp4.zip)

**Comment by verbalshadow** [comment]
Oh i'm on Archlinux 64 bit. Built from AUR godot-git PKGBUILD.

**Comment by sheepandshepherd** [comment]
I have the same issue on OpenSUSE. It's been like this for a while for me, actually. Do your scripts get saved if you save the scene or run the scene from the editor?

**Comment by kubecz3k** [comment]
Sounds serious, but I was not able to reproduce it in 292e8bf0ab02cf37b6ee1759a3942a57a6a69062 build.

**Comment by bojidar-bg** [comment]
I'm on arch too, but I have builded godot myself. Can't reproduce on 292e8bf0ab02cf37b6ee1759a3942a57a6a69062.

@verbalshadow ~ BTW, are you sure that the game is not running at the time you try to save? On my machine, while the game is running I can't interact with the editor in any way, except by pressing the stop button.

Also, are you using built-in (e.g. in-scene) scripts? If you are, this might part of the issue.

**Comment by sheepandshepherd** [comment]
How about the Save As button, does that work for you? I'm able to save just fine using "Save As", but not "Save".

This *might* be related to #3295 (an error in FileAccessUnix::_get_modified_time). Note the code for the Save and Save As buttons:
```C++
case FILE_SAVE: {
	if (!_test_script_times_on_disk())
		return;
	editor->save_resource( current->get_edited_script() );

} break;
case FILE_SAVE_AS: {

	editor->save_resource_as( current->get_edited_script() );

} break;
```
Only "Save" calls `_test_script_times_on_disk()`, which itself calls `FileAccess::get_modified_time`. That's the same function giving me an error message in #3295.

Further info: I'm not using any built-in scripts, only scripts that get saved to files. On 662ed9c built with GCC.

**Comment by verbalshadow** [comment]
updated to https://github.com/godotengine/godot/commit/c9852501a4e1c92dafb35f81f337cb653f8bf501  there is no change in the behavior. ie it is still not saving properly.
@bojidar-bg I do not have the game running and i'm not using built in scripts or scenes.
@sheepandshepherd if i run the scene (it's currently empty) it does save the files successfully.

**Comment by reduz** [comment]
out of curiosity, do other kind of files save to that directory?

**Comment by sheepandshepherd** [comment]
@reduz  Yes, other resources and scenes save successfully to the same directories.

Also, when viewing the script's resource in the Inspector, the Inspector's "Save" and "Save As..." buttons both work, and do write the changes to the .gd file.
The script editor's "Close" button does *not* work though. It prompts to save the modified script, but does not write to the .gd file, even though it marks the script as unmodified.

**Comment by verbalshadow** [comment]
Sorry, been doing other things but yes i can save other files (scenes) to the directory. It is owned by my user and i have full permissions. All files and folders have 755 for their unix permissions.

**Comment by trollworkout** [comment]
@reduz  @verbalshadow  I have gotten a similar issue.

Sometimes when I save a script it assigns .scn instead of .gd to the script although it works fine regardless. 

But sometimes it actually saves the scene instead of the script. This is from the Text Editor! Like make a new GDScript write some stuff then click save or save as in the Text Editor and saved the scene instead of the script with .scn appended. I had to manually copy a script with a different name and open it in Godot then edit it out into a new script cause I couldn't save any script .

I am using latest version now so I will keep everyone posted if this happens again.

**Comment by verbalshadow** [comment]
Working correctly now. Thanks.

**Comment by spada-hk** [comment]
fix dependencies ( you might have changed the folder name so the path of some sub-folders have changed) 

(for general fix)
