### ISSUE TITLE
Editor Array subhints bug

### ISSUE THREAD

**Issue by lonegamedev** [godotengine/godot#32872]
**Godot version:**

v3.2alpha for sure, probably other versions as well.

**OS/device including version:**

Windows 10

**Issue description:**

hint_string for restricting array sub-type and sub-hint in editor UI is not parsing properly, resulting in default array editor.

This feature is possible when adding NodePath property, and looking at the source,
for array editor it should be possible there as well - but it seems parsing is failing.

**Steps to reproduce:**

Create export property like this:

`ADD_PROPERTY(PropertyInfo(Variant::ARRAY, 
  "hints_array", PROPERTY_HINT_NONE, itos(Variant::NODE_PATH)+":"+itos((int)PROPERTY_HINT_NODE_PATH_VALID_TYPES)+"/RigidBody"), "set_hints", "get_hints");`

This should allow to enter only NodePath elements, pointing at RigidBodies.
Default array editor is rendered instead.

**Minimal reproduction project:**

Test node type with property as described above.

[array_subhint_example.zip](https://github.com/godotengine/godot/files/3734705/array_subhint_example.zip)

**Comment by lonegamedev** [comment]
Fix proposal: https://github.com/godotengine/godot/pull/32871

**Comment by KoBeWi** [comment]
Likely no longer valid after export hints rewrite in GDScript 2.0. Not sure if similar bug still exists in the new system, but there's a missing feature here, see https://github.com/godotengine/godot-proposals/issues/1048
