### ISSUE TITLE
(Mono) Godot crash as soon as i run the project.

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#32888]
**Godot version:**
Godot Engine v3.2.alpha2.mono.official

**OS/device including version:**
Windows 10 Version 1903

**Issue description:**
Godot crashes as soon as i run the project. Below is the backtrace:
```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.70
Running: C:\Users\Zak\Desktop\Game_Development\Game_engines\Godot\Standard\Godot_v3.2-alpha2_mono_win64\Godot_v3.2-alpha2_mono_win64.exe --path C:/Users/Zak/Documents/C#%20Process%20list --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 16872 --position 448,240
Godot Engine v3.2.alpha2.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 620
ERROR: get_class: Condition ' !loaded ' is true. returned: __null
   At: modules/mono/mono_gd/gd_mono_assembly.cpp:380
ERROR: Mono Cache: Member GDMonoUtils::mono_cache.class_Vector2 is null.
   At: modules/mono/mono_gd/gd_mono_utils.cpp:226

Mono: Logfile is: C:\Users\Zak\AppData\Roaming/Godot/mono/mono_logs/2019_10_17 12.05.16 (10860).txt
ERROR: get_class: Condition ' !loaded ' is true. returned: __null
   At: modules/mono/mono_gd/gd_mono_assembly.cpp:380
ERROR: Mono Cache: Member GDMonoUtils::mono_cache.class_Vector2 is null.
   At: modules/mono/mono_gd/gd_mono_utils.cpp:226
ERROR: _load_api_assemblies: The loaded assembly 'GodotSharp' is in sync, but the cache update failed.
   At: modules/mono/mono_gd/gd_mono.cpp:888
ERROR: _load_api_assemblies: FATAL: Method/Function Failed.
   At: modules/mono/mono_gd/gd_mono.cpp:897

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGILL while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Managed Stacktrace:
=================================================================
=================================================================

Unhandled Exception:
System.InvalidOperationException: Process has exited or is inaccessible, so the requested information is not available.
  at System.Diagnostics.Process.get_ProcessName () [0x0002d] in <748af814b14a45f7803e4fe5c9300d51>:0
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.get_ProcessName()
  at Main._Ready () [0x00013] in C:\Users\Zak\Documents\C# Process list\Main.cs:19
```
EDIT: After looking inside the mono log it seems that a file `advapi32.dll` was missing from `mono/lib/mono/4.5` folder. After finding that file in my computer and putting it inside that folder, here is the mono log: 
[2019_10_17 12.25.50 (19780).txt](https://github.com/godotengine/godot/files/3738466/2019_10_17.12.25.50.19780.txt)

**Steps to reproduce:**
Run the attached project.

**Minimal reproduction project:**
[C# Process list.zip](https://github.com/godotengine/godot/files/3738381/C.Process.list.zip)

**Comment by qarmin** [comment]
I have on Ubuntu 19.04 Mono 6.4 this backtrace

```
=================================================================
	Native stacktrace:
=================================================================
	0xd084d5 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : (null)
	0xcfbe69 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : (null)
	0xd10e08 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : (null)
	0x7ffaea315f40 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
	0x3119d7c - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN6GDMono20_load_api_assembliesEv
	0x311a0d1 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN6GDMono21reload_scripts_domainEv
	0x2e59107 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN14CSharpLanguage17reload_assembliesEb
	0x30a830e - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : (null)
	0x121a213 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE
	0x136dead - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN12MessageQueue14_call_functionEP6ObjectRK10StringNamePK7Variantib
	0x136e210 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN12MessageQueue5flushEv
	0x1f428a8 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN9SceneTree4idleEf
	0x31ea9a0 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN4Main9iterationEv
	0x32c53d9 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : _ZN6OS_X113runEv
	0xc38f20 - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : main
	0x7ffae9fdeb6b - /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main
	0xc391fe - /home/rafal/Pobrane/Godot_v3.2-alpha2_mono_x11_64/Godot_v3.2-alpha2_mono_x11.64 : (null)
```

**Comment by zaksnet** [comment]
Tested with 119bf2372 also and the editor on this version does not crash, just the game. The debugger gives me this error:
```
E 0:00:04:0290   System.String System.Diagnostics.Process.get_ProcessName(): System.InvalidOperationException: Process has exited or is inaccessible, so the requested information is not available.

  <C++ Error>    Unhandled exception
  <C++ Source>   :0 @ System.String System.Diagnostics.Process.get_ProcessName()()
  <Stack Trace>  :0 @ System.String System.Diagnostics.Process.get_ProcessName()()
                 :0 @ ()
                 Main.cs:19 @ void Main._Ready()()
```
Running the same code in a C# console application seems to be working as expected so its not a syntax error.
@qarmin is it working for you or it crashes?

**Comment by piratesephiroth** [comment]
It runs fine on v3.2 mono alpha1 but crashes the editor on alpha2 (but then every project seems to crash the editor in mono alpha2 with that infamous socket error)

**Comment by qarmin** [comment]
Probably this is duplicate #32762. Wait for alpha 3 to check if this works

**Comment by piratesephiroth** [comment]
It works fine in 119bf23, on Windows

**Comment by Duroxxigar** [comment]
This is happening in my project as well. Editor crashes and then collision doesn't work in my game afterwards. This is alpha 2 (mono)]

**Comment by piratesephiroth** [comment]
yeah, mono is very broken on alpha 2

**Comment by zaksnet** [comment]
> It works completely fine in [119bf23](https://github.com/godotengine/godot/commit/119bf237209414a49879fba40459f22315ab1467), on Windows.
> No errors, warnings or editor crashes.

I just tested in 1e0fb0dc144ce8b7daaa783a67b17c85bba5d57d and it still crashes the game.

**Comment by piratesephiroth** [comment]
> 
> 
> > It works completely fine in [119bf23](https://github.com/godotengine/godot/commit/119bf237209414a49879fba40459f22315ab1467), on Windows.
> > No errors, warnings or editor crashes.
> 
> I just tested in [1e0fb0d](https://github.com/godotengine/godot/commit/1e0fb0dc144ce8b7daaa783a67b17c85bba5d57d) and it still crashes the game.

try deleting the `.mono` folder of your project

**Comment by zaksnet** [comment]
@piratesephiroth i tried deleting `.mono` from game folder, `mono` from `%appdata%/Godot`, still the same. I noticed today that i get a `Mono: Core API mismatch.` error in console:
![image](https://user-images.githubusercontent.com/1850856/67380912-b4925f80-f593-11e9-86b1-e01fb05729cc.png)

**Comment by neikeq** [comment]
@zaksnet The exception you're getting is thrown somewhere from your `Main._Ready()` method. Probably something you're doing with the Process class: `Process has exited or is inaccessible` is being thrown from the `ProcessName` property you're calling.

**Comment by zaksnet** [comment]
Thank you @neikeq , you can ignore the crash part then on this post. If you check #32888 you can see more info on the crash (you probably already have judging from the info you provided). The code is working well in visual studio, plus if it was an error with the code shouldn't it just give me an error instead of a crash? Should I be trying to solve this by changing the code or you feel it is something else?

**Comment by neikeq** [comment]
The exception is unhandled, so the exception is printed and the app terminates. If you run it from the editor, it will show in the list of errors.
I don't know why it would work fine in visual studio but not here. If you find out it's actually an issue with Godot and not the code, please open an issue?

**Comment by zaksnet** [comment]
> The exception is unhandled, so the exception is printed and the app terminates. If you run it from the editor, it will show in the list of errors.
> I don't know why it would work fine in visual studio but not here. If you find out it's actually an issue with Godot and not the code, please open an issue?

Thank you @neikeq , it seems you were right, the problem was that the exception was unhandled. For future reference, i just added `try {} catch {}` to handle the exception and everything works normally now.
