### ISSUE TITLE
2.1.6 build error

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#32883]
**Godot version:**
2.1.6

**OS/device including version:**
Mac OS 10.14.6
**Issue description:**
error: cannot find -lc++
**Steps to reproduce:**
build use the command:
scons platform=android target=release
**Minimal reproduction project:**

**Comment by alexzheng** [comment]
also 2.1.5 has the same error.
However, I can build 2.1.5 successfully on the same device months ago.
Maybe Some updates on my device broke the build.

**Comment by alexzheng** [comment]
the 3.1.1 source code can build on my MacBook Pro.
What's the problem of the 2.1.6 source code?

**Comment by alexzheng** [comment]
the code on the GitHub can build.
only the 2.1.6 has error.

**Comment by akien-mga** [comment]
Duplicate of #30688.
