### ISSUE TITLE
Dictionary braces insert tabs but Array brackets don't

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#32897]
**Godot version:** 3.1.1.stable

**OS/device including version:** Windows 10

**Issue description:** When you create two braces and press enter the new lines insert tabs automatically, but it doesn't happen when they are brackets

**Steps to reproduce:**

![Tabs](https://user-images.githubusercontent.com/37383316/67042631-a0b3ad00-f0fe-11e9-995f-3b5946f18182.gif)

**Minimal reproduction project:**

---------------------------------------

EDIT: As pointed out by @CowThing , the same goes for parentheses of function calls

![FuncTab](https://user-images.githubusercontent.com/37383316/67054956-a5875980-f11c-11e9-9af5-18bbe6b63059.gif)

**Comment by CowThing** [comment]
This should also happen with parentheses for function calls, currently it acts the same way as array square brackets do.
