### ISSUE TITLE
MOUSE_MODE_CAPTURED doesn't work properly!

### ISSUE THREAD

**Issue by vesko24** [godotengine/godot#32891]
**Godot version:**
3.1.1 win64

**OS/device including version:**
Windows 10

**Issue description:**
I have an object that is following the mouse around. When setting the mouse mode to captured in the _ready() function the mouse cursor does disappear, but the mouse gets stuck in the middle of the screen and isn't able to move anymore. When you get out of captured mode everything works perfectly again and the object continues following the mouse as it should.

**Steps to reproduce:**
Window Width: 450
Window Height: 800

You need an Area2D, a Sprite for it and also a Script attached to it. Enter the following code in the script:

-------------------------------------------------------------------------------------------------------------

extends Area2D

onready var viewport = get_viewport()

export(float) var speed = 5

var velocity = Vector2()

func _ready():
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

func _process(delta):
	var motion_x = (get_global_mouse_position().x - self.position.x) * speed
	var motion_y = (get_global_mouse_position().y - self.position.y) * speed
	
	velocity.x = motion_x
	velocity.y = motion_y
	
	velocity *= delta
	
	self.position.x = clamp(self.position.x, 50, viewport.size.x - 50)
	self.position.y = clamp(self.position.y, 38, viewport.size.y - 38)
	
	if Input.is_action_just_pressed("ui_cancel"):
		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
	
	translate(velocity)

-------------------------------------------------------------------------------------------------------------

As soon as you run the game the mouse cursor should disappear and you shouldn't be able to move the Area2D with the mouse. But if you press Escape the mouse cursor should appear and the object will start following the mouse.

**Minimal reproduction project:**
https://gofile.io/?c=v5eqzK

**Comment by Calinou** [comment]
> When setting the mouse mode to captured in the _ready() function the mouse cursor does disappear, but the mouse gets stuck in the middle of the screen and isn't able to move anymore.

This is expected. If the cursor was able to move, it would eventually reach the screen's borders, which would make first-person aiming invisible.

**Comment by vesko24** [comment]
Oh, I see. That makes sense. Thank you for the explanation!
