### ISSUE TITLE
Type casting when declaring a variable does not work

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#32905]
**Godot version:**
3.1.1.stable.official
3.2.alpha2.official

**OS/device including version:**
5.2.20-1-MANJARO

**Issue description:**

See examples:

```gdscript
var x = "abc"
var res: bool = x
print(res) # prints 'abc'
print(res == true) # Error: Invalid operands 'String' and 'bool' in operator '=='
```
```gdscript
var x = null
var res: String = x
print(res) # prints 'Null'
print(res.length()) # Error: Invalid call. Nonexistent function 'length' in base 'Nil'
```
![1](https://user-images.githubusercontent.com/47700418/67102121-9b706400-f1cb-11e9-9ce4-63991ab5e0f9.png)

It works (but the icon is wrong, by the way):

![2](https://user-images.githubusercontent.com/47700418/67102167-aaefad00-f1cb-11e9-8af2-22e95484d5d4.png)

**Comment by fsy98** [comment]
If the code still have problem.I think it may the program didn't do the  type casting, so try another way to do the type casting. For example convert boolen into string: .toString()

**Comment by dalexeev** [comment]
Probably, it's a bug. See https://github.com/godotengine/godot/issues/31331#issuecomment-520632367
