### ISSUE TITLE
Change node's script via another script

### ISSUE THREAD

**Issue by FrancyP** [godotengine/godot#32917]
In my FPS game I created a general Weapon class and for each weapon I create a new script. How I can the weapon script depending on which weapon I'm holding via code?

**Comment by Byteron** [comment]
The issue board is not the place to ask for help, mate.
The discord server as well as the forums are all about helping each other, but this is only to track bugs.

Forum: https://godotforums.org/
Discord: https://discordapp.com/invite/zH7NUgz
QA: https://godotengine.org/qa/
