### ISSUE TITLE
Default font does not match Editor font

### ISSUE THREAD

**Issue by codecustard** [godotengine/godot#32916]
**Godot version:**
3.2.master

**OS/device including version:**
Windows 10

**Issue description:**
The default font does not match the editor's default font. When you type text in a lineedit/textedit node in the editor, you are able to use unicode characters (e.g. ♂). You can also try to create a theme based on the editor by selecting the theme > edit theme > create from current editor theme

**Steps to reproduce:**
-Type unicode text in any textedit/lineedit element within the editor. Notice the font support for unicode.
-Run the project with no theme setup or a theme derived from the editor's theme. Type in the textedit/lineedit and notice the lack of support for special characters.

**Minimal reproduction project:**
[Default Font Issue.zip](https://github.com/godotengine/godot/files/3746031/Default.Font.Issue.zip)

**Comment by dalexeev** [comment]
Also, the default font does not support some alphabets, such as Russian.
![1](https://user-images.githubusercontent.com/47700418/67145736-8ad3f280-f28c-11e9-85a9-fd9378c96edf.png)

**Comment by Calinou** [comment]
This could be solved by replacing the default BitmapFont with a DynamicFont, but it will likely increase the binary size of export templates (even if you never use the default font in your project).

**Comment by dalexeev** [comment]
>but it will likely increase the binary size of export templates even if you never use the default font in your project

When creating a new project, the default font should be automatically added to the `res://` folder. Then those who do not need it will be able to remove it.


.import/
default_env.tres
**default_font.tres**
**default_font.ttf**
icon.png
icon.png.import
project.godot

```
; project.godot
[gui]
theme/custom_font="res://default_font.tres"
```

**Comment by volzhs** [comment]
related to #8998.
can be fixed together.
