### ISSUE TITLE
Ability for the game window to "request attention"

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#3292]
The ability for the game window to "request attention" (blink the tray icon on Windows and GNU/Linux, bounce the dock icon in OS X) would be useful for many things, especially when the game is minimized or unfocused.

Use cases:
- Chat message has arrived
- A player joined/left the game (for multiplayer games)
- …

Just like in LOVE: https://love2d.org/wiki/love.window.requestAttention

----

**Implemented for the following platforms:**
- [x] Windows (#5560)
- [x] OSX (#5662)
- [x] Linux (#5842)
- [ ] Haiku

**Comment by hetdegon** [comment]
I can see many uses for such a function, maybe it can even be used in the editor itself for error popups and prompts and such, too. +1

**Comment by vnen** [comment]
Love don't have this on Linux, it seems, so I wonder how difficult it'd be to do that. For Windows and OSX this seems trivial (I managed easily on Windows, don't have a Mac to try though).

**Comment by akien-mga** [comment]
It's now implemented for our three major desktop platforms (Linux, OSX, Windows), so closing. If a Haiku user wants to contribute the equivalent, it would be welcome :)
