### ISSUE TITLE
I cannot playtest my godot projects

### ISSUE THREAD

**Issue by 5H4D0WILA** [godotengine/godot#32936]
**Godot version:**
3.1.1

**OS/device including version:**
Manjaro, also tested on Windows
both have the same problem

**Issue description:**
i am working on a game and want to playtest it
My laptop can load the project, export, and everything else
except for playtesting
It gives me an error that my video card drivers are outdated and do not support gles 2, but they do

**Steps to reproduce:**
It seems to be just on my laptop

**Minimal reproduction project:**
any project is the same

**Comment by Calinou** [comment]
This may be caused by the renderer selection dropdown not persisting the change to the `project.godot` file correctly.

Try changing **Rendering > Quality > Driver > Driver Name** to GLES2 in the Project Settings.

**Comment by 5H4D0WILA** [comment]
i'll try that

**Comment by 5H4D0WILA** [comment]
That worked
OMG
Thank you
