### ISSUE TITLE
ItemList contains [Object:null] and False after add_item-calls

### ISSUE THREAD

**Issue by LeonFretter** [godotengine/godot#32952]
3.2 alpha

Ubuntu 18.04

In a gdscript that extends ItemList, calling add_item("some string") in a for-loop does not result in only those strings being added to the list. Those strings are indeed added, but they are interspersed with two objects that appear as "[Object:null]" and "False" when printed to the debugger. This problem did only appear after i moved and re-opened my project.

As i said, this only appeared after i moved and re-opened my project. I cannot guarantee that it is reproducable. However, i also don't see how moving and re-opening the project should be able to affect the node's behaviour in such a way. I strongly suspect a problem within the add_item-method. These are the steps, which created the problem for me:
* create ItemList-Node
* create Script extending ItemList-Node
* create for-loop
* inside for-loop make call to add_item("some string")
* print items -> the items should now contain the strange intruders

**Comment by KoBeWi** [comment]
I'm not sure if you are supposed to use `items` directly. They are not listed in the documentation. The `add_item` methods takes also a Texture and a bool whether the item should be selectable, so your intruders come from this additional data.

**Comment by LeonFretter** [comment]
> I'm not sure if you are supposed to use `items` directly. They are not listed in the documentation. The `add_item` methods takes also a Texture and a bool whether the item should be selectable, so your intruders come from this additional data.

Thanks for pointing that out! Not a bug then, but a misunderstanding on my side.
For people in the future, who might stumble upon this: 
`get_item_text` would be the ItemList-method to use for accessing the text of an item specified by an index.
Closing.
