### ISSUE TITLE
[Mono] Crash when adding a custom Resource 

### ISSUE THREAD

**Issue by bigmonte** [godotengine/godot#32953]
**Godot version:**
3.1.1 Mono 
**OS/device including version:**
Windows 10

**Issue description:**
Editor crashes when trying to access the exported Resource. 

**Steps to reproduce:**
1. Create a plugin.
2. Create a class that inherits from `Resource`.
3. In the plugin script, load the script and add a custom type Resource. 
` AddCustomType("DialogueTreeRes", "Resource", DialogueTreeRes, (Texture) GD.Load("res://addons/dialogue_tree/assets/ResIcon.png")); `
4. Create a script with that resource exported.

5. Try to fill the empty exported Resource with your newly created Resource Type

![1](https://user-images.githubusercontent.com/34067397/67166756-28611c00-f38a-11e9-8f40-4484523e42b8.png)

6. Crash when clicking on it. 

![2](https://user-images.githubusercontent.com/34067397/67166757-2b5c0c80-f38a-11e9-947b-b8bcbd6f17df.png)

**Minimal reproduction project:**
https://github.com/bigmonte/MyTest

**Comment by bigmonte** [comment]
This issue recieved no feedback in last 2 weeks. Is the problem invalid?

**Comment by bigmonte** [comment]
Thanks for you comment. Ok less bad. I wish I could help more on this one. When I have time I’ll try to find a way to get some error messages or to debug properly the editor. (Despite my lack of c++ knowledge)

**Comment by CathodeRayBlues** [comment]
I am shamelessly bumping this thread. Having the same issue, and while I understand this is one of many many problems that need fixing, it would be nice to have it brought further into the light.

**Comment by Simiopsis** [comment]
I think this is a problem of the Export attribute, when generating the custom resource since the godot code does not close, it is also related to [#29064](https://github.com/godotengine/godot/issues/29064)

Possible temporary solutions are:

- Generate the resource from the code, but you cannot change the fields from the inspector

- Load the resource through a path without using export for the resource, but you will have to configure the fields outside the node.

**Comment by bigmonte** [comment]
I tested this working example, using Godot 3.2 stable, everything working as expected.

**Comment by Calinou** [comment]
I'll close this as resolved then. Thanks for letting us know :slightly_smiling_face:
