### ISSUE TITLE
When saving an Autoload Script, the file will vanish

### ISSUE THREAD

**Issue by girng** [godotengine/godot#32955]
**Godot version:** 3.2.alpha1

**OS/device including version:** Windows 10, 64-bit

**Issue description:** When saving an Autoload script with **new data**, it will vanish.

**Steps to reproduce:** 
 - Create a script named: GameFunctions.gd
 - Setup an Autoload, set path to `GameFunctions.gd`, set name to `GF2`.
 - File -> Open.. select `GameFunctions.gd`, and enter: 
```
extends Node
func _ready():
	print("hey")
```

 - Now do `CTRL+S`. 
 - All seems good, **however, add a new line** `print("muffin")`. Now do `CTRL+S`
 - The script will vanish from the left side, and an error occurs: 
 - >  Another resource is loaded from path 'res://GameFunctions.gd' (possible cyclic resource inclusion)

Any continued edits to this file will seem like they work, but they are now in the void (doesn't exist).

![](https://i.gyazo.com/966f4aaf1369e6a11896da328d26e8b2.gif)

**Example Project:** 
[EditingGDScriptDirectlyBug.zip](https://github.com/godotengine/godot/files/3750586/EditingGDScriptDirectlyBug.zip)

**Comment by girng** [comment]
Not sure if this helps, but this cannot be reproduced on `3.1.1` stable

**Comment by KoBeWi** [comment]
Doesn't seem to happen in 3.2.3. Please comment if you can still reproduce.
