### ISSUE TITLE
SkeletonIK seems to only work in-editor

### ISSUE THREAD

**Issue by DeleteSystem32** [godotengine/godot#32962]
**EDIT:**
This is not a bug, but to clarify for anyone else having this issue:
To get it to work in the animation, the process mode needs to be set to *Physics*.
Also, manually calling start() *does* work after all, I made a mistake in the setup.

**Godot version:**
3.2 Alpha (commit d33af87b61288fa960f0b1dc5fc5bd76800814d8)

**OS/device including version:**
OpenSUSE Tumbleweed 64bit / Windows 10
CPU: Intel Xeon E3 1231 v3
GPU: AMD Radeon 380 4GB

**Issue description:**
SkeletonIK works in-editor (with the "Play IK" button), but neither through the AnimationPlayer, ~~nor through manual calling of start() in-game.~~

Quick vids to illustrate:
[With "Play IK" button (works)](https://imgur.com/a/TntmnEh)
[In the AnimationPlayer (does nothing)](https://imgur.com/d1ANT00)
[In-game.](https://imgur.com/o5MdbP7) Note how the left hand doesn't move on weapon switch.

**Steps to reproduce:**
Add a SkeletonIK node to a rigged Skeleton, set root, tip, and target nodes. Add the "start" and "stop" function calls to an animation at the start and end, respectively. Compare result to the one of the "Play IK" button.

**Minimal reproduction project:**
Use the [demo project](https://godotengine.org/article/skeleton-inverse-kinematic). Simply running it will illustrate the problem in that the hand will remain in place instead of moving to the weapon body.

**Comment by nazgulsenpai** [comment]
If it helps you narrow it down any, I just tested on commit d33af87 and it works fine on my hardware.  

Windows 10 Pro 64 v1903 (18362.418) 
AMD Ryzen 5 1600 Six-Core Processor 3.20 GHz
NVIDIA Geforce GTX 1050 2GB v436.48

**Comment by DeleteSystem32** [comment]
I've tested on Windows (w/ MSVC compiler) as well just now - same issue, still. I've added some videos to the original post to illustrate the problem.

**Comment by DeleteSystem32** [comment]
Okay, so after a day of trying to find what caused it: the AnimationPlayer's process mode needs to be set to "physics", it won't work in idle mode. As for why it didn't work in code, it only works if the target node comes *before* the SkeletonIK node in the hierarchy, otherwise you'll get a "Condition ' !is_inside_tree()" error. Just in case someone else is encountering issues with this.

Sorry for wasting your time, closing this issue.
