### ISSUE TITLE
Cursor can scroll out of text area when on end of line

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#3296]
Just a minor thing that doesn't affect usability:

just place the cursor on the end of line and scroll to the right

![optimised](https://cloud.githubusercontent.com/assets/8281916/12218708/fca719cc-b727-11e5-82a5-7be7983d3f98.gif)

**Comment by neikeq** [comment]
Looks like a duplicate of #3259, which should be fixed after 02d1ef8
