### ISSUE TITLE
Android Exporting: INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by ElContreh** [godotengine/godot#32974]
Okay, first of all, English isn't my first language, and it's my first time asking ANYTHING on the Internet, so... Sorry in advance!

**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
When I try to one-click deploy, nothing happens. I know it's because of the INSTALL_PARSE_FAILED_NO_CERTIFICATES error in the console, but I don't know why it's happening, I have the adb (From Android Studio), the debug.keystore and the jarsigner all in the Android Export Settings

**Things I tried**
- I tried using the jarsigner from OpenJDK versions 1.8 and 11
- I tried using the default debug.keystore from the .android folder and the one you can create using the command line from the Export documentation (I think they are the same, but whatever)
- I tried exporting the apk and sending it to my phone, but it fails saying "Analisis Error"
- I tried exporting an empty project, but it gives me the same error.
- I tried signing myself the apk with jarsigner

### Console Screenshot
![image](https://user-images.githubusercontent.com/41845000/67256374-0a182080-f45d-11e9-8b90-34086348867c.png)

**Comment by ElContreh** [comment]
It appears that some of my files have "ñ" in them, and that's what causing the issue. Guess I'll go and change all the filenames with that letter, it'll be tedious.
Sorry for the inconvenience, closing this now.

**Comment by Burchard36** [comment]
> 
> 
> It appears that some of my files have "ñ" in them, and that's what causing the issue. Guess I'll go and change all the filenames with that letter, it'll be tedious.
> Sorry for the inconvenience, closing this now.

This is not the issue, its an issue with your keystore, hence why you get NO_CERTIFICATES, double check your have your keystore location right, username and password as well when jarsigning! (Also, dont edit those "ñ" it will break things further ;) )

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/18222.
