### ISSUE TITLE
RichTextEffect doesn't update shadow

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#32981]
**Godot version:**
3564547208030264a28cc55232992aab3cbdad94

**OS/device including version:**
ArcoLinux

**Issue description:**
RichTextEffects do not work with the text's shadow.  I expected the shadow to move with the letters.

![image](https://user-images.githubusercontent.com/28724859/67285564-6bf87a80-f49d-11e9-92ff-ca7777ccbb30.png)

**Comment by YeldhamDev** [comment]
CC @Eoin-ONeill-Yokai

**Comment by Eoin-ONeill-Yokai** [comment]
Thank you for reporting this bug @somnivore , A fix is up now if you'd like to test it out for your specific project.
