### ISSUE TITLE
Ruler Tool breaks when zooming

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32983]
**Godot version:**
3.2 alpha2

**Issue description:**
I noticed that when you measure something but use zoom while doing it, the origin point of ruler gets shifted. I'm not yet sure how to properly fix this, so I'm just leaving this issue in case someone wants to fix it before me.
![image](https://i.imgur.com/HgHljmj.gif)

**Steps to reproduce:**
1. Select Ruler tool
2. Click to start measuring
3. Zoom

**Comment by codecustard** [comment]
I can't reproduce the issue when testing with 3.2.master.72dfa67dd3508f20592959d306e8f2ef159eea5f

Running on Windows 10. Razerblade Pro 2014

**Comment by volzhs** [comment]
i can reproduce it with 982774e639
the **origin** is moving while zooming.
