### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by fsy98** [godotengine/godot#32984]
**Godot version:**
3.11
**OS/device including version:**
windows 10
**Issue description:**
cmake problem
**Steps to reproduce:**
just follow the steps to compile the code, but the last step make this problem
**Minimal reproduction project:**
![image](https://user-images.githubusercontent.com/30133945/67287148-8e43c580-f4a8-11e9-8f73-b297ec1da3a9.png)

**Comment by dreamsComeTrue** [comment]
Are you able to build any simple project with your CMAKE & compiler environment?
Are you sure - this is Godot-specific-related?

**Comment by KoBeWi** [comment]
AFAIK, Godot's buildsystem doesn't support CMake. Not sure what steps you are mentioning.
Also, no response for almost 2 weeks. Closing.
