### ISSUE TITLE
export.cfg can't be saved

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3299]
1. Open any project.
2. Open **Project Export Settings**
3. change value of ``Android > Package > Unique Name``
    * ``org.godotengine.$genname`` to ``org.godotengine.test``
4. restart editor and open it again
5. Try to change any property.

then console says
```
ERROR: close: Condition ' rename_error ' is true.
   At: drivers/windows/file_access_windows.cpp:133
```

And all changes are gone when reopen project.(restart editor)
tested with latest commit 3a3ce982b0157c21b4976a347d4c1c254093970f

edit : added more specific steps to reproduce.

**Comment by reduz** [comment]
windows xp?

**Comment by volzhs** [comment]
@reduz windows 7

**Comment by reduz** [comment]
sounds like something is wrong with your filesystem or the permissions of
the file

**Comment by volzhs** [comment]
I can not delete ``export.cfg`` file when this happen.
And I can delete this file after quit editor.
I hope this gives you a clue.

**Comment by reduz** [comment]
maybe you are editing the file with an external program? Godot only
opens/closes the file briefly, it doen't keep a reference to it

**Comment by volzhs** [comment]
No, I didn't open ``export.cfg`` with any other program.
when I tried to delete ``export.cfg``,
Explorer says, **This file is opend by "Godot Engine Editor (alpha), so task can not be completed**
(actually this message is korean, just translating what it says like)

**Comment by reduz** [comment]
nevermind, found the bug, thanks :D

**Comment by reduz** [comment]
I guess this only was visible on Windows because on Linux, you can keep
references to old files open even if the file is released

**Comment by volzhs** [comment]
Thank you. I will test this right a way. :)

**Comment by volzhs** [comment]
Ah. I tested this on linux also. It looks fine on linux.

**Comment by volzhs** [comment]
It's done! :)
