### ISSUE TITLE
Project Settings search brings weird results

### ISSUE THREAD

**Issue by rezgi** [godotengine/godot#33005]
**Godot version:**
3.2 alpha-2

**OS/device including version:**
OSX Sierra

**Issue description:**
When searching in the project settings to filter elements, the displaying results behave strangely. For example if I search for 'window', when I type 'wi' it appears, and then if I type 'win' it doesn't appear anymore. I've tried this for other settings and I don't really understand the results, seems to behave randomly to me.

**Steps to reproduce:**
In any project, open Project Settings and search for a setting by typing the first letter, then the second then the third and so on, and see how search results behave.

**Minimal reproduction project:**
Empty new project.

**Comment by bruvzg** [comment]
It's searching for property name only (not the category), `window` is showing for `wi` because there's `width` and `test_width` properties within this category.

**Comment by Calinou** [comment]
It'd probably make sense to search in category names as well. This always throws me off when searching for "stretch mode" or "stretch aspect" :slightly_smiling_face:

**Comment by bruvzg** [comment]
It was change in #30516, previously (in 3.1.1) it was searching by full property name.

**Comment by silvanocerza** [comment]
What would be the expected behaviour here? If I search `Application` should I see just the category and its subcategories? Or should I also see all its subcategories' properties?

**Comment by akien-mga** [comment]
> It was change in #30516, previously (in 3.1.1) it was searching by full property name.

Ah right, I had missed that change. The previous behaviour should be brought back.

> What would be the expected behaviour here? If I search `Application` should I see just the category and its subcategories? Or should I also see all its subcategories' properties?

IMO it should list all properties which contain the filter, whether it's in the property name itself or further up its path (i.e. a category/sub-category). So yeah if you search `Application` it should show all subcategories and properties in that category.

**Comment by rezgi** [comment]
Ok seems better to me, the actual state is quite confusing.

**Comment by xelivous** [comment]
can someone add a "regression" label to this issue thanks
