### ISSUE TITLE
Executing an exported build that uses encrypted scripts fails loading them at runtime

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#33002]
**Godot version:**
v3.1.1.stable.oficial

**OS/device including version:**
Windows 10 x64 1903 build 18362.418

**Issue description:**
When you export using encrypted scripts using a valid 64 characters hex key the runtime engine cannot load them properly. This was tested both with windows desktop and android builds using the attached project. Builds exported with plain scripts, compiled scripts or with scripts encrypted with and empty encryption key work just fine, only builds with encryption and valid encryption keys fail to run after export. The console errors uppon running are the ones bellow:
```
ERROR: open_and_parse: Condition ' String::md5(md5.digest) != String::md5(md5d) ' is true. returned: ERR_FILE_CORRUPT
   At: core/io/file_access_encrypted.cpp:103
ERROR: load_byte_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:756
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2168
ERROR: Failed loading resource: res://Node2D.gde
   At: core/io/resource_loader.cpp:285
ERROR: poll: res://Node2D.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Node2D.gd
   At: scene/resources/resource_format_text.cpp:440
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208
ERROR: Failed loading resource: res://Node2D.tscn
   At: core/io/resource_loader.cpp:285
ERROR: Failed loading scene: res://Node2D.tscn
   At: main/main.cpp:1739
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2095
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425
```

**Steps to reproduce:**
* open the attached project
* export a build for any platform. Eg.: Project > Export > Presets > Windows Desktop > Export Project > Save
* run the exported build. The game window will apper brieffly before closing along with the terminal.
* run the build on a pre-existing terminal. The behavior will be the same but the terminal wont close and you'll be able to see the log messages

**Minimal reproduction project:**
[NewGameProject.zip](https://github.com/godotengine/godot/files/3761681/NewGameProject.zip)

**Other Info:**
The encryption key was generated using this site:
[https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx](https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx)

**Comment by akien-mga** [comment]
Did you build your custom export templates with the encryption key? https://docs.godotengine.org/en/3.1/development/compiling/compiling_with_script_encryption_key.html

**Comment by Gnumaru** [comment]
I did not used a custom export template, just the default export templates. I didn't know a custom export template was needed when providing an encryption key. Shame on me for not reading the docs properly =(.
