### ISSUE TITLE
Animation Player with Opacity

### ISSUE THREAD

**Issue by mrawlingst** [godotengine/godot#3301]
As of build 3a3ce982b0157c21b4976a347d4c1c254093970f - the animation player involving with opacity does not behave correctly. When you key opacity at 0, 1, then 0 - when you play the animation player in the editor, it does show the intended behavior. However, when you run the scene or play the game, it does not fades in (from 0 to 1) then fades out (from 1 to 0), instead it just pops in and out as if the code show() and hide() are being executed.

I've attached a project showcasing this issue since it's difficult to show it through screenshot:
[AnimationPlayer-Opacity.zip](https://github.com/godotengine/godot/files/84103/AnimationPlayer-Opacity.zip)

**Comment by akien-mga** [comment]
I can confirm the bug using the above project (and I checked, the play mode is of course "continuous", not "discrete"). Actually for me the fade in/out does not work even in the editor; on the other hand if I create a new animation with the same parameters, it fades in/out properly in the editor, but again not in the running game.

**Comment by mrawlingst** [comment]
I thought I would check couple of other properties to see if it also affects them. Please note I only checked three properties. Position and Scaling works as intended however, Self-Opacity doesn't work either. Just though I should report my findings since it seems it only affects most (if not all) properties relating to opacity.

**Comment by reduz** [comment]
this is not a bug, the second and third keys added are of type int..  how
did you manage to add them? :)


On Sun, Jan 10, 2016 at 10:58 AM, Michael Rawlings <notifications@github.com

**Comment by reduz** [comment]
just use the key button right to the property to add keys, i'm still no
sure how did you manage to do that :P

**Comment by mrawlingst** [comment]
Wha... I added em by clicking on the key button next to the opacity property. Maybe it didn't get typecasted properly?

**Comment by reduz** [comment]
maybe there was a bug leading to that? can you try to reproduce it?

On Sun, Jan 10, 2016 at 11:18 AM, Michael Rawlings <notifications@github.com

**Comment by mrawlingst** [comment]
Well, I was able to convert it to float and ran it. Still the same behavior. I think it's reading it as int, not float. That's what appears to be the case. I've attached the screenshot of the tooltip indicating it's a float.

![ss 2016-01-10 at 09 22 24](https://cloud.githubusercontent.com/assets/5606120/12221986/e02b0480-b77b-11e5-96dd-faa222d4bbc3.png)

**Comment by mrawlingst** [comment]
Yup. I got the behavior to work. It does appear to be typecast issue. I set the opacity keyframes (0.01, 0.99, 0.01) and it worked flawless in running game. It looks like the engine read 0 and 1 as int resulting unintended behavior. It should be a quick fix by typecasting the values for opacity to float.

**Comment by reduz** [comment]
that's seriously weird.. I can' t reproduce it at all. Could you create a
scene that resulted in this configuration from scratch and write the steps
on the way?

On Sun, Jan 10, 2016 at 11:26 AM, Michael Rawlings <notifications@github.com

**Comment by mrawlingst** [comment]
Sure, give me 5 minutes. Do you also want the project in a zip file as well (the one I'm reproducing as you requested)?

**Comment by reduz** [comment]
no.. steps should be ok


On Sun, Jan 10, 2016 at 11:32 AM, Michael Rawlings <notifications@github.com

**Comment by akien-mga** [comment]
> It does appear to be typecast issue. I set the opacity keyframes (0.01, 0.99, 0.01) and it worked flawless in running game. It looks like the engine read 0 and 1 as int resulting unintended behavior. It should be a quick fix by typecasting the values for opacity to float.

I can confirm this, in the project linked above if I change the key at t=2 to a value of 0.999 instead of 1, the bug disappears. On the other hand the value is shown as "1" in the property editor of the animation player.

**Comment by reduz** [comment]
yeah doing this is expected to fix it, the real question is how did he end
up with integers in there on the first place

**Comment by mrawlingst** [comment]
As requested by reduz, here's what I did that resulted this bug:

1. Create a new project
2. Add a Node2D
3. Add Sprite node to parent Node2D, set a texture
4. Add AnimationPlayer to parent Sprite
5. Create a new animation, name it opacity
6. Set length to 4 seconds
7. Click on Sprite
8. Set Sprite's opacity to 0
9. Press the key button next to the opacity's property to create first keyframe
10. In track, go to 2 seconds
11. Set Sprite's opacity to 1, press key button again to create second keyframe
12. In track, go to 4 seconds
13. Set Sprite's opacity to 0, press key button again to create third keyframe

**Comment by akien-mga** [comment]
Note that after doing these steps the animation should play fine in the editor. To actually reproduce the issue, I'd add:

14. Set the animation to autoplay
15. Start the scene and see the result

**Comment by mrawlingst** [comment]
My apologize, I forgot those two steps.

And I just noticed something that reduz is trying to figure out. It does appear that when you do those steps, it does show as float. However, when you save and close the project and open it again, it shows as int. Maybe the engine is reading the numbers as int since scene.tscn shows it as 0 and 1, not 0.0 or 1.0

**Comment by reduz** [comment]
oh I see, this is related to the tscn saver. Fixing asap

On Sun, Jan 10, 2016 at 11:43 AM, Michael Rawlings <notifications@github.com

**Comment by mrawlingst** [comment]
This is animation using (0, 1, 0), specifically looking at "values":[].
`tracks/0/keys = { "cont":true, "times":FloatArray( 0, 2, 4 ), "transitions":FloatArray( 1, 1, 1 ), "values":[ 0, 1, 0 ] }`

This is animation using (0.01, 0.99, 0.01), specifically looking at "values":[]
`tracks/0/keys = { "cont":true, "times":FloatArray( 0, 2, 4 ), "transitions":FloatArray( 1, 1, 1 ), "values":[ 0.01, 1, 0.01 ] }`

**Comment by reduz** [comment]
yeah, it seems the tscn saver should add .0 to floats

On Sun, Jan 10, 2016 at 11:46 AM, Michael Rawlings <notifications@github.com

**Comment by mrawlingst** [comment]
Looks like it. :)
