### ISSUE TITLE
Xamarin C# Support

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#33040]
I wanted to open an issue specific to tracking the status of using Xamarin with Godot. Because I have no idea how to do it, or if it is even possible yet?
I imagine this already works for Windows users, but given that many of us are Linux  users; to include many Godot core developers; I wanted to know how we use it too.

Things needed to close this issue:

- [ ] Working example project of a Linux user compiling a C# project for Godot with Xamarin support for Android.
- [ ] Document the process for Linux users to create a C# Godot Xamarin project on Android.
- [ ] Working example project of a Linux user compiling a C# project for Godot with Xamarin support for iOS.
- [ ] Document the process for Linux users to create a C# Godot Xamarin project on Android.
- [ ] Document the process for Windows users to create a C# Godot Xamarin project on Android.
- [ ] Document the process for Windows users to create a C# Godot Xamarin project on iOS.
- [ ] Document the process for OSX users to create a C# Godot Xamarin project on Android.
- [ ] Document the process for OSX users to create a C# Godot Xamarin project on iOS.

Applies to Godot current master, and 3.2a2.

Thank you to all of the developers for your time and for making Godot such an awesome engine. I do realize that solving these issues is non-trivial, but if they are solved I wanted to know how? If they are not solved, I would like to know what are the possibilities for ways to solve it, and how can the community help?

**Comment by aaronfranke** [comment]
See https://github.com/godotengine/godot/issues/20267#issuecomment-461164960 for a response from the founder of Mono and Xamarin.

Any development tools we implement have to be multiplatform, since Godot is multiplatform, and it's Microsoft's business decision to not release Xamarin development tools for Linux. [Stated indirectly](https://github.com/mono/monodevelop/issues/5228):

> I've been trying to write a reply here which won't get me fired for an hour so far. I don't want to be seen as making company policy, or revealing company secrets.
> 
> This is all a discussion of high-level management policy. There's no insurmountable technical barriers to any of the feasible ways to close this issue.

But anyway, thanks for opening this issue, we had nothing to track it before, even if it's looking quite hopeless to do in the near future.

**Comment by FeralBytes** [comment]
@aaronfranke Thank you for the research, now that I think about it, I remember following you down this same rabbit hole (Only to learn that Evil Empires rarely change their minds about their enemies). Well now I am going to look for a workaround. I tried wine, but failed to get visual studio to install, now trying to get a virtual machine to install everything, but seems godot may not run in a virtual machine. So may be a dead end for Linux Developers?

**Comment by ricardoalcantara** [comment]
@FeralBytes I don't understand what you're tying to achieve, Why do you want Xamarin support and why do you need Visual Studio on linux? I've been working with .NET and Godot for a while on linux and I don't have those problems. VSCode works like a charm on Linux for .NET and Godot uses mono for C#.

**Comment by FeralBytes** [comment]
@ricardoalcantara I want to develop Android apps on Linux using C# which requires Xamarin for Android support.
```C#
using Android;
```
But I can not because Microsoft has purposefully blocked the use of Xamarin on Linux, you have to use it on Windows.

**Comment by ricardoalcantara** [comment]
@FeralBytes You don't need Xamarin to make an Android App on Linux with Godot, have you read the documentation? Godot's C# implementation for Android uses Mono. https://github.com/godotengine/godot/pull/29359

**Comment by FeralBytes** [comment]
@ricardoalcantara How can I use android specific features, for instance I want to turn wifi on and off, not event considering Android 10 which has a special requirement for such operations. Or Say I want to create a service on Android? Or utilize Bluetooth? Can I do these without Xamarin? If we can thoose should be published somewheres for the community to use. It is definitely possible to code around and basicly re-implement Xamarain's features but we really should not have too.

**Comment by ricardoalcantara** [comment]
You can do it but you have to do it natively with java, you have to create an android module and setup an interface using Godot APIs and after that you can call it with C#, you can even use android specific dependencies like admob or firebase, actually this is how we do that. http://docs.godotengine.org/en/latest/tutorials/plugins/android/android_plugin.html

**Comment by FeralBytes** [comment]
@ricardoalcantara Yes I know I could write Java, as that is what I did when I wrote the new permissions for Godot, but I want something easier. That required a large amount of setup, and maintanence. C# is integrated, having access to Xamarin would complete the package with out the need of recompiling the entire engine every time.

**Comment by ricardoalcantara** [comment]
@FeralBytes They choose not to use Xamarin, there is no Xamarin available to be used.

**Comment by FeralBytes** [comment]
Actually [Xamarin is still a part of the C# ecosystem](https://dotnet.microsoft.com/apps/xamarin). But as stated by the microsoft emplyees, they could get it working for Linux, but they are not going to. So yes there is no Xamarin for Mono, but their is Xamarin for [Visual Studio](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16). Not to be confused with [Code](https://code.visualstudio.com/docs/?dv=linux64_deb) (Visual Studio Code). You can see the difference between [thoose products here](https://visualstudio.microsoft.com/).

**Comment by ricardoalcantara** [comment]
I know those products, I know Xamarin since before Microsoft purchased it, I know Visual studio since the first one and VSCode too, I know the difference, I know .NET Core (with runs on linux natively), .NET framework and .NET Standards, Maybe you don't know Godot enough... and I also know that there is no Xamarin for Godot. What else do you need?

**Comment by FeralBytes** [comment]
> What else do you need?
Xamarin for Godot. Not trying to be rude, but that is the title.
> I don't have doubts I am trying to solve yours,
This is a confusing statement.
> maybe you don't know Godot enough...
It seems like you are just trying to insult me now. So I think I will stop having this conversation with you.

**Comment by ricardoalcantara** [comment]
> Xamarin for Godot

Now I understand, you want to request a feature. This what I asked at the first place. For me your issue is not clear, you opened it as Xamarin was implemented and requiring sample projects. For this issue you better open it here https://github.com/godotengine/godot-proposals

https://github.com/godotengine/godot/issues/33040#issuecomment-546736042
> @FeralBytes I don't understand what you're tying to achieve, 

> It seems like you are just trying to insult me now. So I think I will stop having this conversation with you.

Not at all.

**Comment by aaronfranke** [comment]
In case there is still any confusion, let me just copy paste this bit from Miguel de Icaza:

> But most importantly, because then your C# users could call and consume any native APIs from Android without having to use some sort of module, they can access the entire Android API from C# when they so desire.

**Comment by FeralBytes** [comment]
For me until C# has Xamarin, [this new Java plug-in system](https://godotengine.org/article/godot-3-2-will-get-new-android-plugin-system) is the way forward for me. It makes Java plug-ins  much faster to create and modify then ever before.

**Comment by BenMcLean** [comment]
To work around not having Xarmarin, would it be possible to make a generic Java plugin that does everything that's needed?

I absolutely need to read and write external storage for my project to remake Wolfenstein 3-D for the Oculus Quest. And I really do mean external storage, not the app's private storage and not resources bundled into the APK.

**Comment by BenMcLean** [comment]
> **Any development tools we implement have to be multiplatform, since Godot is multiplatform**, and it's Microsoft's business decision to not release Xamarin development tools for Linux.

Godot's Android build templates already won't build on Windows, only on Linux. So Godot isn't really multi-platform: it's really Linux-first.

**Comment by ricardoalcantara** [comment]
@BenMcLean 

> To work around not having Xarmarin, would it be possible to make a generic Java plugin that does everything that's needed?

Yes, you can do it in Java and interface with Godot using C# or GDScript (there's other ways too).

> Godot's Android build templates already won't build on Windows, only on Linux. So Godot isn't really multi-platform: it's really Linux-first.

I achieve to build Android template on windows and Linux. It just not straightforward, but obliviously it's easier on Linux, windows has many issues that you have to workaround =/. But I agree it's Linux first, because they use Linux and they love FOSS, but the community maintain the other OS compatible as well. Even the Vulkan branch that's been developed on Linux Ubuntu, has other contributors committing to adjust for Windows and MacOS. 

Anyway tell us more about your issue building on windows and if it is a bug you can even open an issue for that, providing more information about Version, OS, Logs and soon on. Saying it doesn't build isn't very helpful.

**Comment by BenMcLean** [comment]
> Anyway tell us more about your issue building on windows and if it is a bug you can even open an issue for that, providing more information about Version, OS, Logs and soon on. Saying it doesn't build isn't very helpful.

Oh, I'm sorry, I forgot to mention that the problem there is with Mono. AFAIK, Mono doesn't build on Windows, only on Linux. You can build the regular Android build templates without C# support on Windows, but not the Godot Mono Android build templates.

I know C#, Java and a little C++. But I'm completely lost on how to make this Java plugin. I know how to ask for the permission to read external storage I need in a Java Android app, but not how to make it into a plugin for Godot and make that accessible from C#. I'm not sure how to even start researching that.

**Comment by BenMcLean** [comment]
However ... isn't being able to make calls to the Android API inherently part of what "Android support" means? I mean Godot couldn't even run on Android without being able to make Android API calls. However it is doing that should be exposed by default. I'm really confused as to why this would need a plugin when all the plugin's going to do is expose the API that should already be exposed.

**Comment by FeralBytes** [comment]
@BenMcLean because in short Godot is really a Native C & C++ application, it has just enough Java integrated into it, to talk to Android for only exactly what it needs, this is done as a API between the Native C++ Godot Engine and a Java Program that supports that API, carrying out the required functions for the Engine. The same thing would have to be created in C# for Android... but my argument is that it already exists, it is called Xamarin and to use that in C# you just call `using Android` but that is not supported for Godot or Linux thanks to Microsoft blocking. We could re-implement the solution in C# and that may be the way forward since Microsoft refuses to lift the ban. But I don't have time for that so I will just use Java as a stop gap.

**Comment by BenMcLean** [comment]
After reading [this](https://docs.godotengine.org/en/latest/tutorials/plugins/android/android_plugin.html), it looks like I would need some major hand-holding from someone who's done it before to make and debug this if it was ever going to happen, and I don't think anyone's going to want to take the time for that.

I think that, if I'm on my own, then I can get my app running in Unity faster than I could figure this out.

**Comment by BenMcLean** [comment]
If anyone else comes along and wants to know how to get access to external files on Android, [here's how it's done on the Java side](https://github.com/BenMcLean/QuakeQuestSwitcher/blob/29d75a37f3f82b7b23b43de136592d7637ce0f87/app/src/main/java/net/benmclean/quakequestswitcher/MainActivity.java#L54-L89).

**Comment by neikeq** [comment]
I can't say for certain what will be of this, but just a clarification: The reason this is not done right now is not because of any block by Microsoft. Xamarin Android, albeit not officially supported, can be made to work on Linux and, as Miguel [commented](https://github.com/godotengine/godot/issues/20267#issuecomment-461164960), they can produce packages for Godot to use.

**Comment by neikeq** [comment]
I'm not experienced with Xamarin Android, but I would be happy to make this happen. The reason it hasn't happened yet is simply because I have several higher priority tasks.
If anyone with enough knowledge of Godot and Xamarin Android wants to move this forward, I would recommend opening a [GIP](https://github.com/godotengine/godot-proposals) with detailed information. That would certainly help because, as I said, I'm not experienced with it.

**Comment by BenMcLean** [comment]
All I actually needed for my project was to request external file permissions, and "SomeBody3D" on Discord pointed out that [this got merged 20 days ago](https://github.com/godotengine/godot/pull/32600). That exposes what I needed!

Having Xamarin would be nice for other people trying to achieve other things, but to be able to access external file storage, you just need to:

1. Mark READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE in the Godot export options so that it will be in the manifest and...

2. Run the Godot.OS.RequestPermisisons() method to get the user's permission before actually accessing the external file storage.

I still need to figure out how to query that the permission was granted so that my program won't try to dig into the files too early, before it actually has permission, but this is definitely progress and shows I probably won't need to make a Java plugin for this after all.

Trying to make a plugin just for that would have been crazy!

**Comment by knuxbbs** [comment]
Recently I could build a Xamarin.Android application in my Linux machine, as described is [this issue](https://github.com/0xFireball/xamarin-android-linux/issues/10).

**Comment by FeralBytes** [comment]
@knuxbbs I will have to try this out soon. Thanks!

**Comment by timothyparez** [comment]
Wondering if this could help: https://dev.azure.com/xamarin/public/_build/results?buildId=31493&view=results
The artifacts contain `.deb` packages to install Xamarin.Android on Ubuntu.

**Comment by neikeq** [comment]
We will have to wait for .NET 6 to figure out what to do about this. It will not only be about the benefits of Xamarin.Android (like the Java/Android bindings) but also whether the way Godot does it right now is still viable with .NET 6.

**Comment by ScepticDope** [comment]
@neikeq https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/

"We’re integrating the Android, iOS, and macOS capabilities that are part of Xamarin into .NET 6"

**Comment by neikeq** [comment]
See godotengine/godot-proposals#2333 for possible (not yet decided) future changes that have some relation with this.

**Comment by aspenforest** [comment]
> @neikeq https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/
> 
> "We’re integrating the Android, iOS, and macOS capabilities that are part of Xamarin into .NET 6"

So... would it not make more sense to replace the Mono implementation of C# with .NET 6 in Godot?

**Comment by aaronfranke** [comment]
@aspenforest .NET 6 is not out yet. For when it is out, read the proposal linked directly above your comment for plans.

**Comment by BenMcLean** [comment]
> Unfortunately, the Godot developers do not own any time machines.

Speaking of things the Godot developers sadly do not have, they also do not have a grant from Microsoft to continue major C# development of the Godot engine, correct?

I am sort of looking into my crystal ball to see the future by knowledge of what happened in the past. In the past, it required a large grant from Microsoft to make Godot Mono happen in the first place and it would likely be a project similar in size to get away from Mono onto .NET 6, it is unlikely that Godot .NET 6 will happen unless there's a new grant for that. Or am I wrong?

Please support Godot, Microsoft!

**Comment by ALipAkrohk** [comment]
I have read this issue in its entirety but I still do not understand what this request wants !
https://youtube.com/playlist?list=PLQl2eWiUO8_K1BcuBjRRq5_z5xqkLosRu
https://youtu.be/oE-Wgy9o9q4
If xamarin is to be supported in C#, direct connectivity to the android api in GdScript and GdNative is also required.

**Comment by FeralBytes** [comment]
@ALipAkrohk I built a checklist of items? If the primary stakeholders of the engine wish to close this issue they always can. In the end I wrote my own Kotlin plugins for Android and will write something for iOS if I ever ship on iPhone. C# simply is not feasible at this time and that is why the issue highlights, the new issues with .NET6 just highlights it, same as no funding from Microsoft. At this point I don't intend to touch C#, because it is still broke, unless someone can point me at things that can check off the items above.

**Comment by ALipAkrohk** [comment]
> @ALipAkrohk I built a checklist of items? If the primary stakeholders of the engine wish to close this issue they always can. In the end I wrote my own Kotlin plugins for Android and will write something for iOS if I ever ship on iPhone. C# simply is not feasible at this time and that is why the issue highlights, the new issues with .NET6 just highlights it, same as no funding from Microsoft. At this point I don't intend to touch C#, because it is still broke, unless someone can point me at things that can check off the items above.

I think it might have been a lot more useful if Kotlin or dart had replaced C# in Godot, but the Csharp programming language at this point has only slowed down the ability to add features to different versions of Godot.
There are features that are not the same in the two versions of Godot. This is a contradiction.
This could have been more effort to develop Godot with Haxe or GDscript optimization for better performance output.
We also have options such as Rust programming language on the table that do not have the complexities of the past (or C and its family) and can be much more useful than Csharp.

**Comment by BenMcLean** [comment]
If Godot Mono was to be discontinued without a clear upgrade path to more C# development on Godot, then I'd be switching game engines for my next project to something that does C#. I might be doing that anyway, but this would make it for sure. When coding games, I want to be able to use the same real programming tools I get to use in my job writing business software: not have to completely switch languages.

**Comment by ALipAkrohk** [comment]
> If Godot Mono was to be discontinued without a clear upgrade path to more C# development on Godot, then I'd be switching game engines for my next project to something that does C#. I might be doing that anyway, but this would make it for sure. When coding games, I want to be able to use the same real programming tools I get to use in my job writing business software: not have to completely switch languages.

There are two options in your content.
1 - GDscript is a very complete language and as you know it can even be used to produce software.
2 - The alternative languages I mentioned are practically better and more complete than C # in software development
  I criticized the development of C # in Godot (there are many reasons, from the language development method to ...) but my main criticism was that there should be no features in the mono version but not in the official version.
  There is nothing wrong with having a mono version, after all, the choice is free for the users of a free society, but not until there is a contradiction.
