### ISSUE TITLE
Input Latency

### ISSUE THREAD

**Issue by LapizGaming7751** [godotengine/godot#33056]
**Godot version:**
3.1.1
**OS/device including version:**
Almost any.
**Issue description:**
The letter I type doesn't show up until I start typing my next letter.
**Steps to reproduce:**
Type two letters

**Comment by Zireael07** [comment]
We had similar reports in the past, are your devices using Intel integrated graphics?

**Comment by Calinou** [comment]
Duplicate of #23069. Try updating your graphics driver to the latest version provided by Intel. Alternatively, start the Godot editor with the `--verbose` command-line argument, which can also mitigate the issue.
