### ISSUE TITLE
YSort node not sorting GUI items

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#3305]
Hi! 
I've stumbled upon the problem that YSort node sorts only visually the nodes, but GUI items keep their tree order. It would be great if GUI items would also be affected by YSort node.
![texturebtn](https://cloud.githubusercontent.com/assets/9309589/12222626/7506c8c2-b7b9-11e5-823a-94810c70ed7d.jpg)
In a preview you can see that sprites are y sorted. The red dot is the area user clicked- normally the house that is in front should be highlighted, but since the Texture button isn't y sorted, the house that's behind highlights.

**Comment by bojidar-bg** [comment]
:+1:

**Comment by DualMatrix** [comment]
Tested in master, Ysort works fine with both nodes and controls now.

**Comment by Chaosus** [comment]
Thanks ! Closed.
