### ISSUE TITLE
Node renaming filters out the at signs

### ISSUE THREAD

**Issue by T4g1** [godotengine/godot#33068]
**Godot version:** v3.1.1.stable.official

**OS/device including version:**: 5.3.7-arch1-1-ARCH

**Issue description:** At signs in node names are filtered on node renaming

**Steps to reproduce:**
1: Adds any two same scene in the scene tree
2: Do `node.name = node.name` on the one renamed by the engine

**Minimal reproduction project:** [name_issue.zip](https://github.com/godotengine/godot/files/3772426/name_issue.zip)

**Some screenshots:**
Expected behavior:
![DeepinScreenshot_select-area_20191025160758](https://user-images.githubusercontent.com/1417856/67577914-ada94f80-f741-11e9-9716-fb0f2e7e2080.png)

Observed behavior:
![DeepinScreenshot_select-area_20191025160811](https://user-images.githubusercontent.com/1417856/67577929-bac63e80-f741-11e9-9ea3-f54224b89c4b.png)

**Comment by girng** [comment]
I don't believe this is a bug?
https://github.com/godotengine/godot/issues/27608#issuecomment-479670136

**Comment by T4g1** [comment]
Example of why one would want to re-use the name given by the engine: [https://github.com/Razzeeyy/godot-networked-instancing-example/issues/6](url)

**Comment by mclark4386** [comment]
yeah, just spent the day figuring out why this happens... the easy solution to your situation is:
```
extends Node2D

var scene = load("res://Node2D.tscn")

func _ready():
	yield(get_tree(), "idle_frame")

	var node1 = scene.instance()
	add_child(node1)

	var node2 = scene.instance()
	add_child(node2,true)

	print(node2.name)
	# Do some magic
	node2.name = node2.name
	print(node2.name)
```

(note the optional second parameter to `add_child`, this enforces unique names if set to true ^^)

**Comment by T4g1** [comment]
Good to know, I'll make use of that. But imho, the instruction `node.name = node.name` modifying the node name should still be addressed either by documentation (feature) or by fixing the code (bug)

**Comment by name-here** [comment]
If stripping the @ isn't a bug, it seems like naming things with "@"s in the editor shouldn't be possible.  It should probably also output a warning to the console when stripping the "@".  Another solution would be to add an escape character or replace it with something else internally.

**Comment by KoBeWi** [comment]
Node name is validated when it's added to a tree. `@` is reserved for this operation, here's related comment:
https://github.com/godotengine/godot/blob/94e5f66cbb399ffd3e501a237d7eb3de79ce1607/scene/main/node.cpp#L1056-L1057
This should be probably documented.
