### ISSUE TITLE
Green "+" not showing added node on animation dialog

### ISSUE THREAD

**Issue by Cobradabest** [godotengine/godot#3306]
When I attempt to add a node on the dialog that appears when you select an animation player, nothing shows until I fiddle about with timeline, settings and changing animations back and forth.

This should be replicated by adding a function call animation track and attempting to add a node to that track.

I am using the latest fixnum Linux build of Godot, which can be downloaded here: http://fixnum.org/godot/

![selection_091](https://cloud.githubusercontent.com/assets/8548727/12222876/019b9f28-b7c0-11e5-851a-dd6bed7bd035.png)

**Comment by hetdegon** [comment]
This is strange. When you commented on it on IRC, I was able to reproduce, but I updated to current just now and suddenly it works fine again. Seems animation_editor.cpp was altered, so maybe it's fixed in master now?

**Comment by Cobradabest** [comment]
That's strange.. Well, unfortunately, I haven't had a good history of compiling things from source...

**Comment by neikeq** [comment]
Is this issue still valid? If it could have been fixed in 2.0 alpha as @hetdegon mentioned, then you should be able to test it now that 2.0 stable was already released.

**Comment by vnen** [comment]
This was probably fixed in later versions (in particular in the upcoming 3.1, in which the AnimationPlayer was re-made). If it's not the case then it's better to open a new issue.
