### ISSUE TITLE
Extra Space in play window

### ISSUE THREAD

**Issue by triko88** [godotengine/godot#33067]
**Godot version: 3.1**

**OS/device including version**
- **Device:** MacBook Pro (2017)  
- **OS:** MacOS Catalina (10.15)

**Issue description:** I was working on a module and while testing it, the majority of the screen of the scene was filled with a flickering background. I don't why it is happening, I compiled the engine without that module and the problem still persists.

<img width="1136" alt="Screenshot 2019-10-25 at 7 01 11 PM" src="https://user-images.githubusercontent.com/24989067/67575356-0a186900-f75a-11e9-8d48-f00f1236d7b0.png">

 
**Steps to reproduce:** Simply play a scene.

**Minimal reproduction project:** Just one dummy scene with ```Control``` node as root and a ```Label``` node.

**Comment by clayjohn** [comment]
Already fixed in master https://github.com/godotengine/godot/pull/32818

Thanks anyways. :)

You can download 3.2 release candidate 3 for an up to date version containing the fix

**Comment by clayjohn** [comment]
Already fixed in master https://github.com/godotengine/godot/pull/32818

Thanks anyways. :)

You can download 3.2 release candidate 3 for an up to date version containing the fix

**Comment by akien-mga** [comment]
Actually fixed by #32809 in the `master` branch. The other PR is for the `vulkan` branch.
