### ISSUE TITLE
AudioStreamGibberish gone?

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#3307]
When I picked up Godot I saw a "gibberish" function which I wanted to make use of in my game, but after mentioning it on IRC, it seems it's been disabled. Is it scheduled for removal, or will it come back eventually?

I can live without it, but it'd be really convenient to have around.

**Comment by akien-mga** [comment]
For the record, it was disabled in 9741374 when the AudioStream API was rewritten. My guess is that it was just disabled temporarily to be able to build everything and push the API rewrite, and then likely forgotten/seen as low priority.
By checking thoroughly the diff in 9741374, one might eventually be able to do the needed changes to AudioStreamGibberish to write the new AudioStreamPlaybackGibberish I guess.

**Comment by akien-mga** [comment]
Assigning to 2.1 for now, but if someone wants to handle it before 2.0, feel free to of course :)

**Comment by akien-mga** [comment]
Nobody cares and the audio server became even less compatible for 3.0, so I'll drop the obsolete code.

**Comment by reduz** [comment]
it's also technically doable with GDNative eventually
