### ISSUE TITLE
Adding a custom project setting type is off by 1.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#33075]
**Godot version:**
3.2 alpha2
**OS/device including version:**
Mac OS X Mojave

**Issue description:**
Adding a custom project setting type is off by 1. That means an int is added as a bool, a float as an int, a String as a float, a Vector2 as a string and so  on.

![image](https://user-images.githubusercontent.com/930478/67600703-9fa6ff00-f740-11e9-84ba-e3f19a872dfb.png)

**Steps to reproduce:**

- Open Project Settings.
- Select General tab
- Enter in `Category`: Custom/Settings, `Property`: Test, `Type`: Vector2

Click Add. Notice that the entry field Test is a String instead of Vector2

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
CC @Calinou
