### ISSUE TITLE
WebGL Context lost

### ISSUE THREAD

**Issue by tadaaagames** [godotengine/godot#33085]
**Godot version:**
3.2 alpha 3

**OS/device including version:**
Macbook Pro 13, Intel 640, OSX 101.4.6
Browser latest Chrome and Firefox

**Issue description:**
When testing with the new webserver from Godot (great new feature!) most of the time as soon as you move the mouse around this error pops up and the execution stops

<img width="526" alt="context" src="https://user-images.githubusercontent.com/46694168/67619820-32ef3b80-f7f8-11e9-8e8e-b16f5173264c.png">

This does not happen if I launch an external web server (python -m SimpleHTTPServer).

**Steps to reproduce:**
Create a simple GLES2 or GLES3 with the godot logo sprite moving around and preview on web browser.

**Minimal reproduction project:**

**Comment by Faless** [comment]
Does the error also happen when using a different web server? Or only on
the debug http server? I don't see how our server could be the coulprit...

**Comment by Faless** [comment]
Sorry, my bad, didn't read the bottom text.
Seems really weird, and I couldn't reproduce on Linux.
Does it happens only the first time? (I.e. only after pressing the html5
button the first time and not when the server is already running in
successive calls)
anyone else also experiencing this issue?

**Comment by tadaaagames** [comment]
It happens both the first time and on subsequent tries.
Sometimes it doesn't happen for a while and then it starts again.
This is what I get from the web inspector:

<img width="777" alt="inspector" src="https://user-images.githubusercontent.com/46694168/67623047-99845180-f818-11e9-8c84-f213b6ba67eb.png">

I've also attached a simple project that has the issue for me. I wonder if it's something that has to do with osx.

[simple_test.zip](https://github.com/godotengine/godot/files/3775053/simple_test.zip)

**Comment by follower** [comment]
It would probably be helpful if you could provide more details on your hardware configuration, e.g. GPU, VRAM, etc.

Also, does the problem occur when the browser only has one window/tab open and/or no other GPU-using software is running?

Possibly useful to someone in reproducing/debugging/fixing the issue: https://www.khronos.org/webgl/wiki/HandlingContextLost

**Comment by Faless** [comment]
Not having a Mac it is really hard for me to debug this.
You mentioned the same error happens with firefox right? Can you provide the Firefox console log too? Can you also provide the "Network Tab" of the firefox devel tools to see what it is trying to download and if something fails there?

**Comment by tadaaagames** [comment]
Sure! I'll try to post something later in the day

**Comment by tadaaagames** [comment]
I've been testing it with Beta 3.2.
So far seem good, although I have just tried with ES2 projects.
Also had a lot of updates to browsers inbetween, which might be the reason is working better now.
Will test better tonight and report back.

**Comment by Anutrix** [comment]
@tadaaagames Any updates?

**Comment by tadaaagames** [comment]
This seems solved as of Beta 3.2

**Comment by robbertzzz** [comment]
I just saw this issue with one of my testers. This was on a pretty old Macbook pro 13 inch (I think 2012 version) on Chrome. I've got several people testing the game and only this one person with this issue.

**Comment by robbertzzz** [comment]
This happens in both debug and release builds, built in Godot 3.2.1 stable.

**Comment by Calinou** [comment]
@robbertzzz Which macOS version are they using?

**Comment by robbertzzz** [comment]
@Calinou they're on Sierra. Yes I've used gles2 for this project, thanks for the tip
