### ISSUE TITLE
GDNative File open() crash

### ISSUE THREAD

**Issue by rarsp** [godotengine/godot#33088]
**Godot version:** 3.1.1

**OS/device including version:** Windows 8.1

**Issue description:** I have no idea how to translate this gdscript code to gdnative
`
var save_game = File.new()
save_game.open("user://savegame.save", File.WRITE)`

this code crashes:
`    Ref<File> file;
    file->open("user://save.save", File::WRITE);`

this also crashes:
`File file;
    file.open("user://save.save", File::WRITE);`

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
You need to initialize the ref probably. Something like `Ref<File> file = File::new();`.

**Comment by bruvzg** [comment]
>Something like Ref<File> file = File::new();. 

In GDNative it's `File::_new();`

**Comment by rarsp** [comment]
ok thanks, it works!
