### ISSUE TITLE
Black screen with Msaa enabled GLES2

### ISSUE THREAD

**Issue by yetha** [godotengine/godot#33108]
**Godot version:**
3.2.alpha3

**OS/device including version:**
Android  5.1 / Motorola XT1039, GPU: Andreno 305

**Issue description:**
After the splash screen, nothing is visible, completely black screen.
The error I get in my project, not in the minimal reproduction project:
`E 0:00:01:0719   _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
  <C++ Source>   drivers/gles2/rasterizer_storage_gles2.cpp:4744 @ _render_target_allocate()
`
GLES3 causes black screen on my device regardless of Msaa.

**Steps to reproduce:**
Use GLES2, set Msaa to 2x, export to android.

**Minimal reproduction project:**
[New Game Project.zip](https://github.com/godotengine/godot/files/3775815/New.Game.Project.zip)

**Comment by Calinou** [comment]
cc @clayjohn
