### ISSUE TITLE
HTML5 Export crash when mouse crosses edge of view port during load

### ISSUE THREAD

**Issue by piratechipgames** [godotengine/godot#33113]
**Godot version:** 3.1.1 and 3.2.alpha2 (only two versions I've tested)

**OS/device including version:**
Windows 10 version 1903 (64-bit)
Chrome Version 77.0.3865.120 (64-bit)
Firefox 69.0.3 (64-bit)

Tested on GTX 1060, GTX 1050, GTX 970, and Radeon 5700 XT 
(only had the opportunity to test alpha2 on the Radeon 5700 XT)

**Issue description:**
When exporting an HTML5 game, moving the mouse in and out of the game view port while the game is loading will cause a black screen. Sound still seems to play.

The crash occurs in both gles2 and gles3.

I get abort(101) errors from 3.1.1 and abort(107) errors in 3.2.alpha2 in the browser console

This is easiest to reproduce by rapidly moving the mouse in and out of the game screen as it loads but can be reproduced vary easily on accident.

I've been trying to figure out how to properly reproduce this bug for a bit and have found a very hacky way to get around this to be able to release our web games.

Within the generated javascript code:
`(['mouseover', 'mouseleave', 'focus', 'blur']).forEach(function(event, index) {
			Module.canvas.addEventListener(event, send_notification.bind(null, notifications[index]));
		});`

Which i think comes from:
https://github.com/godotengine/godot/blob/master/platform/javascript/os_javascript.cpp#L1011

Replace: 
`Module.canvas.addEventListener(event,send_notification.bind(null, notifications[index]))`

With: 
`setTimeout(function(){Module.canvas.addEventListener(event, send_notification.bind(null, notifications[index]))}, 10000);`

This is obviously not an actual fix to the problem, hoping sharing this hack will help identify the root cause of the issue. I don't know enough about the structure of the engine at this time to fix this myself in a timely manner. It seems like some mouse stuff is being used before its ready in some way?

**Steps to reproduce:**
0: Ensure correct export templates are installed for your version of Godot
1: Create new default empty project
2: Create empty scene (tried with 2d and 3d so far)
3: Export project to HTML5 with default settings
4: Host game from a web server of some kind 
    (tested on gamejolt, kongregate, newgrounds, itch, and with simple python http server (only python server was used in testing 3.2.alpha2))
5: navigate to game from browser
6: move mouse in and out of the view port
7: game displays black screen

**Minimal reproduction project:**
Default empty project

**Comment by Faless** [comment]
Fixed in 3.2.2 via #39538 (and the rest of JS improvements) . Closing, but feel free to comment if you still encounter it.
