### ISSUE TITLE
CollisionShape2D duplicate will change with parent.

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#3311]
I created a CollisionShape2D and set it to SegmentShape2D.
When I duplicate that CollisionShape and change it by the inner handles, the first created changes too.
This happens with other shape-types too, that have inner handles (capsule, circle, ray...).
I'll attach a picture with mouse-cursor pointing at what I call "inner handle".

![segmentshape2d](https://cloud.githubusercontent.com/assets/16130334/12228275/2cb41f04-b839-11e5-8791-4d1d0e22e564.png)

**Comment by bojidar-bg** [comment]
@nopeson ~ This is a feature of the engine. Actually, what happens is that CollisionShape2D nodes use a Shape2D resource. But.. when you duplicate a CollisionShape2D node, you don't duplicate the resource; it stays the same. Which means that they are synchronized.

"Ok, good", you say, "but how to fix?". It is simple, you should go in the Inspector, then click the small white arrow, and select "Make Unique". This would duplicate the resource, destroying the link.
![image](https://cloud.githubusercontent.com/assets/5276727/12229831/f1c56b94-b853-11e5-8a01-5731c972baa7.png)

**Comment by nopeson** [comment]
Oh, I see.
thx :)

**Comment by bojidar-bg** [comment]
Please close this issue ( @nopeson @akien-mga )
