### ISSUE TITLE
Translated text in right to left language is left to right.

### ISSUE THREAD

**Issue by hohfchns** [godotengine/godot#33111]
**Godot version:**
3.1.1
**OS/device including version:**
Windows
**Issue description:**
When switching language to Hebrew, which is read from right to left, the text appears reversed, as if read from left to right.
**Steps to reproduce:**
Switch language to Hebrew (and probably any other right to left language)
**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is caused by Godot not supporting right-to-left text display yet, see #982.
