### ISSUE TITLE
CSG geometry bug

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#33117]
**Godot version:**
Godot 3.2 alpha3

**OS/device including version:**
Win7 Nvidia

**Issue description:**
Geometry (or rendering?) bug showing visible faces with two CSG boxes, the second child one in subtraction operation. There should be no diagonal faces visible, since this area is "subtracted" by the second child CSG box.

**Steps to reproduce:**
Add CSG box node, change height, width and depth to your liking,
Add another CSG box as child of the first, set Operation to "Subtraction", change height, width and depth to see the bug (visible diagonal faces).

![csg_renderbug01](https://user-images.githubusercontent.com/47016402/67642169-6a014200-f909-11e9-886a-b761e3a28e83.gif)

**Comment by name-here** [comment]
Does this happen in earlier versions of Godot as well?

**Comment by Calinou** [comment]
For the record, this seems different than #21125.

**Comment by golddotasksquestions** [comment]
@name-here Yes, can confirm in 3.1 as well. This bug appears when the diagonal edges of both boxes align.
