### ISSUE TITLE
Particles not working

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#33114]
**Godot version:**
Godot 3.2 Alpha Official build 3

**OS/device including version:**
Windows 10

**Issue description:**
When Process Material is added, no longer draws particles, however converts to CPU Particles to what it is supposed to.. Works just fine in 3.1.1 stable

**Steps to reproduce:**
1. Create Particle (not CPU particles, they work just fine)
2. Add a mesh to Draw Passes (mesh shows up, all is fine so far)
3. Add Process Material Particles -> mesh disappears, no particles showing, but is supposed to be emitting

**Minimal reproduction project:**
[Particle Bug.zip](https://github.com/godotengine/godot/files/3776133/Particle.Bug.zip)

**Comment by clayjohn** [comment]
Can't reproduce, Ubuntu 16.04 Intel integrated graphics. 

Please post your GPU info as well. Maybe this is driver related? So try updating your GPU drivers as well.

**Comment by KoBeWi** [comment]
Also can't reproduce. Windows 10 with GTX 1060.

**Comment by mrjustaguy** [comment]
Nvidia Geforce 9500 GT, doesn't seem to be driver stuff... tho the graphics card is antique..

**Comment by mrjustaguy** [comment]
Upon further investigation it is indeed an issue with an antique graphics card that doesn't support these particles properly, so i'm closing the comment as it isn't very probable that anyone that can run Godot Games or such would even be using a 10 year old Graphics card (and those that would be using such an old Graphics card would probably understand that they need an upgrade, as any low tier GPU now is stronger then one from a decade ago)
