### ISSUE TITLE
[WIP] Reconsider need for macOS 10.14-specific DisplayLink vsync workaround?

### ISSUE THREAD

**Issue by follower** [godotengine/godot#33125]
During research for #33116 I encountered suggestions that the underlying V-Sync issue was fixed in a subsequent minor OS point release. [1]

This made me wonder if the workaround added via https://github.com/godotengine/godot/commit/b53f2d1d598193ab1d1c02345fc321be254364ca was still required.

My primary reason for asking is that I have suspicions that the `DisplayLink`-based workaround may be causing Godot editor and/or games to hang (when V-Sync is enabled) when my MacBook Pro on Mac OS X 10.9.5 goes to sleep automatically.

I did some preliminary investigations which suggested the DisplayLink thread may not survive the sleep/wake cycle but haven't had the chance to investigate properly.

**Next steps**:
 * Someone may wish to test if the DisplayLink patch is still necessary for 10.14+
 * At some point I may be able to dig deeper into the sleep issue I observed.

----

[1] e.g.
 * https://github.com/openframeworks/openFrameworks/issues/6146#issuecomment-470499466
 * https://twitter.com/FlohOfWoe/status/1103296098834305026
 * https://github.com/openframeworks/openFrameworks/issues/6146#issuecomment-519195854
 * https://github.com/glfw/glfw/issues/1337#issuecomment-476482317
 * https://github.com/cocos2d/cocos2d-x/issues/19080#issuecomment-478640731
 * https://stackoverflow.com/questions/52938516/opengl-not-rendering-on-macos-mojave#52938517
 * https://hg.libsdl.org/SDL/rev/73f3ca85ac0e

[2] Here are some other recent Mac OpenGL patches I noticed in other projects in case we encounter the same issues at some point:
 * https://github.com/wxWidgets/wxWidgets/pull/1617 & "[wxGLCanvas macOS texture issues with 10.13 and lower](https://groups.google.com/forum/#!topic/wx-users/KivbyKAB0Po)"
 * https://github.com/wxWidgets/wxWidgets/pull/1354
 * https://github.com/qt/qtbase/commit/f39230fcac4de01f26945bde16c3a10c5ac74afb

[3] Random other semi-related links I encountered:
 * https://stackoverflow.com/questions/20083027/nsopenglview-and-cvdisplaylink-no-default-frame-buffer#44301471
 * https://stackoverflow.com/questions/54891914/nsopenglview-drops-its-nsopenglcontext-on-macos-10-9

----

*Edit:* Link to Mac OS sleep-related issue which *might* be related: https://github.com/godotengine/godot/issues/28039

----
cc: @BastiaanOlij due to being author of the original patch

**Comment by bruvzg** [comment]
SDL have removed it in https://hg.libsdl.org/SDL/rev/1b6f67e84802

**Comment by BastiaanOlij** [comment]
If Apple fixed the issue I don't see any reason why we shouldn't undo the DisplayLink fix. It really was just a bandaid imho.

**Comment by follower** [comment]
BTW in the unlikely case this information is useful to someone in future, as noted in the above issue, at some point I discovered that almost no `CVDisplayLink` implementations correctly handle a situation that can occur (via Fast User Switching) where the link is destroyed & then a new link created later:

> _"In macOS 10.4 and later, the display link thread is automatically stopped if the user employs Fast User Switching. The display link is restarted when switching back to the original user. "_
>
> -- <https://developer.apple.com/documentation/corevideo/1457281-cvdisplaylinkstop?language=objc>

As I understand it this was the cause of a Godot hang I encountered (at the time) of uncertain origin but turned out to be related to the use of Fast User Switching while Godot was running.
