### ISSUE TITLE
CSG flicker rendering bug with all union, one subtraction box

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#33121]
**Godot version:**
Godot 3.2 alpha3

**OS/device including version:**
Win7 Nvidia

**Issue description:**
Stable visual positional flicker on the mesh with almost overlapping CSG boxes with one subtraction box covering the area (outerbox)

![csg_renderbug03](https://user-images.githubusercontent.com/47016402/67643391-4a711600-f917-11e9-9c35-6c477107e131.gif)

**Steps to reproduce:**
Move the CSG boxes on the z-axis until they almost overlapp in the minimal project:

**Minimal reproduction project:**
[csg_flicker_bug.zip](https://github.com/godotengine/godot/files/3776561/csg_flicker_bug.zip)

**Comment by golddotasksquestions** [comment]
Though it looks not as bad anymore, this issue is still present in Godot 3.2.3 stable and Godot 3.2.4 beta2:
![csg_issue](https://user-images.githubusercontent.com/47016402/99859443-5833b200-2b90-11eb-9f64-93abc94640d6.png)

**Comment by Calinou** [comment]
@golddotasksquestions Please open a new issue with a minimal reproduction project attached.
