### ISSUE TITLE
SampleLibrary editor window needs stop functionality(button)

### ISSUE THREAD

**Issue by dillikumar** [godotengine/godot#3312]
In the SampleLibrary editor window, we need a stop button. Currently when a sample file which is set to loop is played, there is no easy way to make it stop. The only way to stop it is closing the window and reopen it again. It needs to be reopened since closing the window has no effect.
![samplelibrary_editor_missing_stop_function](https://cloud.githubusercontent.com/assets/9153651/12229265/e6d5405c-b86b-11e5-8fac-9dec38bf99dc.jpg)

**Comment by dillikumar** [comment]
Well, as @reduz and Roderick Lagunas pointed in the FB, There is a stop button near the add to library button in the top left of the window. But the problem is, it doesn't look like a stop button. Its best to have a stop button replacing the play button while playing the sample.

**Comment by akien-mga** [comment]
I fixed this in #4033 a while ago actually.
