### ISSUE TITLE
Particles2D animation ending prematurely

### ISSUE THREAD

**Issue by PapaCheese** [godotengine/godot#33122]
**Godot version:**
3.2 alpha3

**OS/device including version:**
windows 10

**Issue description:**
particles animation ending prematurely if life time is set below 1

**Steps to reproduce:**
create Particle2D node and give the process material some sort of animation and set the life time to below 1

**Minimal reproduction project:**
[minimalRecreation.zip](https://github.com/godotengine/godot/files/3776591/minimalRecreation.zip)

see that the color is suppose to go from blue to green to red but it never reaches red unless the life time is above 0.8

first time posting sorry for any noobness

**Comment by hbina** [comment]
I assume the problem is it using some kind of integer type?

**Comment by ssd71** [comment]
Bug is absent in the v3.1.1 stable release on steam

**Comment by Kaonnull** [comment]
I stumbled over a question in relation to the lifetime randomness together with particle animation. 

What if the particles get a shorter lifetime through the lifetime randomness modifier.
Should the animation play faster to complete in time?

If someone wants to test it, this is my current implementation: https://github.com/Kaonnull/godot/commit/b7f6b9b4d0b65300e9f316f824aad7e760f60cab

**Comment by clayjohn** [comment]
Your current commit will completely break "lifetime_randomness" CUSTOM.y increases up to lifetime. CUSTOM.W stores a value less than lifetime at which point the particle resets. 

This bug just needs something that takes lifetime into account when blending values over lifetime.

**Comment by Kaonnull** [comment]
Are you sure that `CUSTOM.y` increases to `LIFETIME`? 
It looks like that `CUSTOM.y` is normalized, in every tick `CUSTOM.y` is increased by a normalized `DELTA`:
https://github.com/godotengine/godot/blob/36a785513fb1424b17c7ae217668f7ca402b5790/scene/resources/particles_material.cpp#L379-L382

I currently have two working fixes, one where the animation is played faster when a particle gets a shorter lifetime:
https://github.com/Kaonnull/godot/commit/b7f6b9b4d0b65300e9f316f824aad7e760f60cab
Build: https://gofile.io/?c=PyCCEd 

![fix2 3](https://user-images.githubusercontent.com/10180455/68044910-a1406c00-fcd8-11e9-82d2-35f584354f51.gif)
With "lifetime_randomness":
![fix2 2](https://user-images.githubusercontent.com/10180455/68044914-a6052000-fcd8-11e9-89fc-e5c18e8ebc79.gif)


My other approach is that the particle just disappears when its lifetime ends:
https://github.com/Kaonnull/godot/commit/cb7e65e564e7f95089f094f038858fbf7427afd4
Build: https://gofile.io/?c=IuZBZc

![fix1](https://user-images.githubusercontent.com/10180455/68044928-abfb0100-fcd8-11e9-8591-8ab94382ff99.gif)
With "lifetime_randomness":
![fix1 1](https://user-images.githubusercontent.com/10180455/68044937-ae5d5b00-fcd8-11e9-8a75-975f6f1b309d.gif)


I think in both is the "lifetime_randomness" still working correctly. 
But in the first one, the minimal reconstruction example looks kind of odd with  "lifetime_randomness". If a particle has a relay short lifetime, it reaches its maximum size really fast.
