### ISSUE TITLE
Angle does not allow use sampler2D in transform feedback in some cases, WebGL2

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#33134]
**Godot version:**
3.1.1 stable

**OS/device including version:**
Windows 7 (Chrome/Firefox latest)

**Issue description:**
Angle does not allow use sampler2D in transform feedback shader(particle/etc)

**Steps to reproduce:**
1. Create particles, make particle material as shader
2. Bind any texture(or viewport) as sampler2D - **it will work**
3. Create viewport, bind viewport texture to *second* sampler2D - **all sampler2D are lost**

check this [web build link](https://danilw.github.io/godot-utils-and-other/BUG_Angle_trf/web/BUG_Angle_trfeedback.html) (left is texture, right is texture+viewport) they should be equal, they equal only with Angle-disabled(or in native build).

**Minimal reproduction project:**
https://danilw.github.io/godot-utils-and-other/BUG_Angle_trf/BUG_Angle_trfeedback.zip

**Comment by KoBeWi** [comment]
Looks still valid in 3.2.3

**Comment by danilw** [comment]
this is not godot bug, this is WebGL2 ANGLE-only bug
Godot4 drop WebGL2 support so this bug can be closed I think... as you wish ofc

**Comment by danilw** [comment]
I report this bug to Chrome 30 days ago https://bugs.chromium.org/p/chromium/issues/detail?id=1139633
so this can be closed
