### ISSUE TITLE
MeshDataTool create_from_surface crashes on "incomplete" mesh

### ISSUE THREAD

**Issue by TheSHEEEP** [godotengine/godot#33138]
**Godot version:**
3.2.alpha3

**OS/device including version:**
Manjaro Linux

**Issue description:**
create_from_surface is extremely crash-prone when passed anything that isn't 100% optimal.
Combined [with this unfixed-so-far problem](https://github.com/godotengine/godot/issues/29275) it produces a surefire crash.  
Might be that the CSGShape is the underlying problem here, but I don't see why MeshDataTool shouldn't be able to work with ArrayMeshes that have nothing except their vertices that.  
Vertices is all that you need in many circumstances. The rest should be optional.

Looking [at the code](https://github.com/godotengine/godot/blob/master/scene/resources/mesh_data_tool.cpp), the function just accesses all the non-essentials without even checking if they exist, leading to the crash.

You can still use ArrayMesh directly to iterate vertices if needed, but that is rather cumbersome compared to MeshDataTool.

**Steps to reproduce:**
Put any mesh into create_from_surface that does not have anything optional set (tangents, uv_coords, etc.). 
ArrayMesh produced from any CSGShape works, e.g.
```
        var csgCombiner :CSGCombiner = get_node("CSGCombiner")
	csgCombiner._update_shape()
	var arrayMesh :ArrayMesh = csgCombiner.get_meshes()[1] 
       
        # Crashes
        meshDataTool.create_from_surface(arrayMesh, 0) 
```

**Minimal reproduction project:**
Doesn't seem necessary. See steps to reproduce.

**Comment by Zireael07** [comment]
I have an even funnier case, where MeshDataTool modifies a surface just once - the result of the first modification somehow doesn't work for create_from_surface xDDD

**Comment by hoontee** [comment]
Not reproducible on 3.2.3.rc3.

**Comment by clayjohn** [comment]
Thanks for checking! 

Closing, I can reopen if someone is experiences this later. :)
