### ISSUE TITLE
High GPU usage in editor

### ISSUE THREAD

**Issue by 44m0n** [godotengine/godot#33136]
**Godot version:**
Godot v3.1.1

**OS/device including version:**
Windows 10 Pro 1809 (build 17763.805)
Intel(R) UHD Graphics 620 (driver version: 22.20.16.4735)
NVIDIA GeForce MX150 (driver version: 26.21.14.3615)

**Issue description:**
Running Godot on the dedicated NVIDIA GPU

1.  I have a 2D scene with a node with few sprites. When that tab is open and displayed on the screen the GPU usage increases from 0 to 30-40% (even if I have the program running in the background). The update spinner is constantly spinning. 
If I switch to other tab the GPU usage drops back to 0 and the update spinner works fine.

2. I deleted the node with the sprites and created it back as it was before and everything works fine. 
The GPU and spinner update works normal.

**EDIT**
**I found the reason:**

- All of this is happening when I have selected `VBoxContainer` or `TextureRect` in the scene menu.

**Steps to reproduce:**
Just select TextureRect or VBoxContainer in editor.
Video Capture: https://imgur.com/a/XqupVCm
Old video capture: https://imgur.com/a/4uDq1VN

**Comment by 44m0n** [comment]
I updated the original issue.
**Added:** reason and steps to reproduce.

**Comment by Calinou** [comment]
> Running Godot on the dedicated Intel GPU

It's either an integrated Intel GPU, or a dedicated NVIDIA GPU :slightly_smiling_face:

**Comment by 44m0n** [comment]
> You're running Godot on either an integrated Intel GPU, or a dedicated NVIDIA GPU 🙂
Dedicated NVIDIA GPU. I change it now, sorry 👼 
> Can you reproduce this on [3.2alpha3](https://godotengine.org/article/dev-snapshot-godot-3-2-alpha-3)?
I just tested. This issue doesn't exist in [3.2alpha3](https://godotengine.org/article/dev-snapshot-godot-3-2-alpha-3)

**Comment by Chaosus** [comment]
> I just tested. This issue doesn't exist in 3.2alpha3

If it is fixed in the master branch, then this issue should be closed because 3.2 designed to replace 3.1.1 in the near future.

**Comment by rolbr** [comment]
**Just wanted to confirm:** same issue on 3.1.2 where GPU load would go from 0-3% idle (simply having the Godot editor open) to a staggering 50-60% (sometimes even 99%) when selecting either an HBoxContainer or VBoxContainer. Thanks @44m0n for catching that!

Win 10 (version 10.0.18362 build 18362)
Intel(R) HD Graphics 630 (driver 26.20.100.7263)
NVIDIA GeForce GTX 1050 (driver 26.21.14.4145)

**Upgrading to 3.2-rc2 fixed that.** Thanks! 👌
