### ISSUE TITLE
srgb_to_linear turns rgb 255 values into 0

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [godotengine/godot#33133]
**Godot version:**
3.2 alpha 2
EDIT: Same issue in 3.2 alpha 3

**OS/device including version:**
Windoze 10

**Issue description:**
It appears any Color value that uses maximum 255 becomes 0. 

So for example if red is 255 after conversion red becomes 0. Same issue with green and blue.

I do not think this is intended behavior. Possibly an upper boundary check  issue?

**Steps to reproduce:**

In my test below pixel at location 21,21 is black alpha 0.0 then I place a white alpha 1.0 and after conversion it becomes black alpha 1.0

![image](https://user-images.githubusercontent.com/36826319/67659137-07706c00-f932-11e9-8f17-d4ff0f1985ec.png)

**Minimal reproduction project:**

Sorry I do not have a test project.

**Comment by lawnjelly** [comment]
`core/image.cpp line 2933`
`Image::srgb_to_linear()`

I think the srgb2lin lookup table is missing one element, probably should be 255.

I think ajweeks may be doing a PR. :+1:

**Comment by ajweeks** [comment]
Oh wow, what strange timing as I just came across this issue randomly in the code base two days ago. I didn't think anyone was using the function but if you are then 'll make a PR in a few hours.

**Comment by lawnjelly** [comment]
> Oh wow, what strange timing as I just came across this issue randomly in the code base two days ago. I didn't think anyone was using the function but if you are then 'll make a PR in a few hours.

Haha I had assumed you were asking about this when you asked in IRC!! I had seen the issue earlier but not examined. Spooky stuff! :smile: Must be getting close to Halloween. :smiling_imp:
