### ISSUE TITLE
Deprecate expecting data.pck and only look for binaryname.{pck,zip} + engine.cfg

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3313]
Based on this comment by @reduz in https://github.com/godotengine/godot/pull/2788#issuecomment-158920824:

> I will probably need to add some changes (noting down)
> -writing and reading zips (done in #2879)
> -deprecating expecting data.pck and only use the code provided by this patch

**Comment by akien-mga** [comment]
Why do you want to deprecate data.pck though? I don't have a strong opinion, but it could become a bother at least for packaging: to package Godot games current, I just put the good linux template in the $PATH as e.g. /usr/games/godot-runner and can then use it to load a packaged data.pck (actually I plan to package libre games, so I'll probably packaged them unpacked, but the use case is still relevant).

Or did you have something more specific in mind?

**Comment by punto-** [comment]
on some platforms it's not clear what the binary name is because the system
doesn't provide it (or it has different names depending how you launch the
game, ie launching from a host computer will have one name, launching from
a game installed on the devkit will have a different one). A "hardcoded"
name like data.pck is useful for those cases.

Also if you distribute a .zip users might try to unpack it, just like it
happened to the templates file before we renamed it to .tpz, so an option
to open with a different extension like .pcz would be useful

**Comment by reduz** [comment]
yes, this would only be useful in Linux and Windows, in many other platforms the binaryname is less meaningful, such as OSX, Android, HTML5, etc. so you have to rely on a data.pck

**Comment by reduz** [comment]
we should only make this work and deprecate data.pck on linux and windows

**Comment by akien-mga** [comment]
But should we really deprecate it at all? As I said above, it can still be quite useful if you want to be independent from the binary name; though as long as the behaviour can be specified by a command-line, it's fine by me if it no longer searches for data.pck in the runtime dir.

**Comment by reduz** [comment]
I would deprecate it because it happened countless times that users manage
to put a data.pck in a project directory, making it no longer work

**Comment by reduz** [comment]
But let's wait for 2.1 for this

**Comment by punto-** [comment]
Yeah, sometimes many platforms will share the same pck, for example on
Steam you create a package (they call it a "depot") with the pck which is
downloaded on all platforms, then one depot for each binary, for each
platform. So they all share the same pck, but only download the depot with
the binary for the current platform. The code already tries to open
multiple files, trying to open 1 more file doesn't really make a
difference..

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Done for 3.0.
