### ISSUE TITLE
Visual shader translates in generated shader

### ISSUE THREAD

**Issue by fire** [godotengine/godot#33142]
**Godot version:**
aad4d8648b4593b5edb479e85984730770e77c70

**OS/device including version:**
OSX 10.14

**Issue description:**
The visual shader is translated in comments and then saved in the shader. Should autogenerated shaders translate?

https://github.com/godotengine/godot/blob/aad4d8648b4593b5edb479e85984730770e77c70/scene/resources/visual_shader.cpp#L247-L256

https://github.com/godotengine/godot/blob/aad4d8648b4593b5edb479e85984730770e77c70/scene/resources/visual_shader.cpp#L1602

Translations should not be in auto-generated shader code. The generated code should be the same between different languages.

This is bad because it causes merging flip-flops.

This behavior is also not standard across every visual shader.

**Steps to reproduce:**
Use a translated language and create a shader.

**Comment by Chaosus** [comment]
Yeah, seems like a bug
