### ISSUE TITLE
Scene tabs are gone when closing or selecting scene

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3314]
tested with 725b61bb6c71b0f3bd469bc9a9252c4e49ec5598 commit on Windows 7 and Ubuntu 14.04.

**Comment by neikeq** [comment]
I can confirm this bug. It was probably introduced by 6eb742d. I think this commit tried to fix #3128

**Comment by akien-mga** [comment]
Hm, this was well hidden in a mipmaps-related commit (/me looks at @reduz ;)).

**Comment by reduz** [comment]
seems i commited this by mistake :|

**Comment by akien-mga** [comment]
Pro-tip (that I discovered a few days ago): you can commit with ```git commit -v``` to get the full diff displayed in the text editor used to write the commit log. Can be useful to check what you're actually committing and/or adapt the log accordingly.

**Comment by akien-mga** [comment]
(alternatively ```git diff``` for files that haven't been "added" yet, or ```git show``` to see what's going to be committed once files have been added, you know the drill :))

**Comment by reduz** [comment]
commited this by accident :| was working on it and forgot

**Comment by akien-mga** [comment]
> commited this by accident :| was working on it and forgot


Yeah I don't blame you :) With the impressive amount of bug fixing you're doing, I don't think we can complain about a couple mistakes within tons of commits. That's why the rest of us are doing watchdogs and trying to spot mistakes if they happen :)

**Comment by reduz** [comment]
Will push fix tonight, still want to refactor that class a little

**Comment by akien-mga** [comment]
From @neikeq on https://github.com/godotengine/godot/issues/3128#issuecomment-171300957: 
> This issue is not fixed. However, the behaviour is different now. After closing two tabs, all of remaining tabs are hidden (may be related to issue #3314).
![gif](https://cloud.githubusercontent.com/assets/7718100/12296340/5a6d7b82-ba07-11e5-9645-1e2a8a238635.gif)
