### ISSUE TITLE
Game crash using GodotSteam module

### ISSUE THREAD

**Issue by GabiLarbi** [godotengine/godot#33140]
**Godot version:**
Godot Engine v3.2.alpha.custom_build.24e1039eb

**OS/device including version:**
Windows 10 1809 / 17763.805

**Issue description:**
Try to use GodotSteam module for Godot
Everything just went fine during the compilation and i got all the methods and else working for this module (i mean Godot recognize the syntax for Steam module)
But when i try to initialize Steam in Godot Editor, the game crash and this error happens:

**"drivers\unix\net_socket_posix.cpp:197 - Socket error: 10054"**
------------------------
**Steps to reproduce:**
Compile Godot source with the GodotSteam module in it
Run project

**Minimal reproduction project:**
[myProject.zip](https://github.com/godotengine/godot/files/3779150/myProject.zip)

![socket error](https://user-images.githubusercontent.com/37615043/67687170-2dc8f280-f998-11e9-841f-0aaa00faecf8.JPG)

**Comment by akien-mga** [comment]
> `drivers\unix\net_socket_posix.cpp:197 - Socket error: 10054`

This is not a relevant error, it's just raised by the debugger because your game crash, so the debugger connection stopped.

This should likely be reported at the GodotSteam repository, and here only once you've seen with developers there that it's a Godot issue.
