### ISSUE TITLE
Imported WAV AudioStreamSample has Loop End = 0

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#33141]
**Godot version:** 3.1.2.devel.custom_build.8f3fea2

**OS/device including version:** Windows 10

**Issue description:**
Imported WAV file has Loop End equal zero in AudioStreamSample. In effect, loops don't work - you need to set Loop End offset manually, and editor has no help for that.

Additionally, entering Loop End larger than sample size crashes the editor when playing the sample.

**Steps to reproduce:**
Import a WAV. Observe Loop End = 0

**Expected result:**
* Loop End should be set to end of the sample by default.
* Entering Loop End larger than sample length should set it to sample length.

Possible additional enhancement: allow setting Loop Begin/End visually from waveform in exporter.

**Comment by lekoder** [comment]
It also happens in 3.2/alpha3

**Comment by mikkac** [comment]
Hi,
probably thing you are looking for is already here.
In "Import" tab, you can click "Loop" checkbox- screenshot below.
When "on" is checked, loop end is calculated properly.
 
![loop_end](https://user-images.githubusercontent.com/31192615/67722698-2b878800-f9da-11e9-91de-9a3f70bc3c31.jpg)

**Comment by lekoder** [comment]
Okay, that works - but still it should not crash when you manually input the value outside of the range - it should clip to max value. I also don't see any use-case where setting this to 0, even if sample is *not* looped would be desirable.

**Comment by KoBeWi** [comment]
I can't reproduce the crash. Do you have any reproduction project with steps? Does it happen in the newest beta?

**Comment by Calinou** [comment]
@lekoder Bump :slightly_smiling_face: 

Can you upload a minimal reproduction project that contains the WAV sample in question?

**Comment by lekoder** [comment]
I can't reproduce it with 3.2.1, so whatever was causing it is likely fixed.

**Comment by KoBeWi** [comment]
Cool.
