### ISSUE TITLE
GDscript error $../../../.. BUG for UI

### ISSUE THREAD

**Issue by ilyafuu** [godotengine/godot#33158]
**Godot version:**
Godot 3.2 Alpha 3 and same Godot 3.1.1
**OS/device including version:**
Debian 10
**Issue description:**

![image](https://user-images.githubusercontent.com/17591539/67757871-a8a01500-fa4d-11e9-9e98-0cac652c484a.png)

![image](https://user-images.githubusercontent.com/17591539/67757469-eb152200-fa4c-11e9-9fcf-5ecbf56ed2b1.png)

![image](https://user-images.githubusercontent.com/17591539/67757690-53640380-fa4d-11e9-89be-77619bf45794.png)

I wanted a UI interface but why the error is `$ .. / .. / .. / ..`
only `get_node ('../../../ ..')` and `$'.. / .. / .. / ..'` work

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
That's not a bug, if you use `/` you need to use quotes otherwise we can't know if `$SomeNode.x/2` is `get_node("SomeNode.x/2")` or `get_node("SomeNode").x / 2`.
