### ISSUE TITLE
Android: correct documentation build android modules

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#3315]
commit: 9e8f647
when trying to build the engine produces an error:
![error_module](https://cloud.githubusercontent.com/assets/233268/12236774/b4c1f9cc-b88c-11e5-914a-463ff15b954d.jpg)
before everything worked

**Comment by volzhs** [comment]
see this one #3285

**Comment by ret80** [comment]
dublicate #3285

**Comment by reduz** [comment]
still need to update the docs on how to use the new functions

**Comment by ret80** [comment]
Let any one of the developers to improve the documentation of modules. It did not take much time, but will help users.

**Comment by ret80** [comment]
Let any one of the developers to improve the documentation of modules. It did not take much time, but will help users.

**Comment by akien-mga** [comment]
Closing as dup of #3561, we don't need to issues for it :)
