### ISSUE TITLE
Godot editor GUI issue

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#33155]
**Godot version:**
7b28f79f9
Also tested with Godot official Alpha 3 and the issue is still there. In Alpha 2 and earlier the issue does not exist.

**OS/device including version:**
Windows 10 Version 1903 Build 18362
Intel HD Graphics 620

**Issue description:**
I'm not sure how to describe this so i will just attach screenshots.
ERROR:
![error](https://user-images.githubusercontent.com/1850856/67749964-e9d8fa80-fa36-11e9-955b-6d74f022cd29.png)

CORRECT:
![correct](https://user-images.githubusercontent.com/1850856/67749986-f5c4bc80-fa36-11e9-9f5f-05b8e2e2ad2d.png)

The screenshots are taken at the start of the taskbar so basically the bottom of the Godot Editor GUI is hidden.

EDIT: Looks like if i do Editor > Toggle fullscreen (shift+f11) and then undo it the GUI returns to normal and the bottom part of the editor is visible again so this might be related.

**Comment by KoBeWi** [comment]
Are you running it maximized? If not, maybe the editor remembered a layout where it's outside the screen.

**Comment by zaksnet** [comment]
> Are you running it maximized? If not, maybe the editor remembered a layout where it's outside the screen.

It seems to be related to Editor feature profiles. Every time i set a custom editor feature profile this happens and when i unset it everything is good.
So to replicate it go at:
![image](https://user-images.githubusercontent.com/1850856/67779561-7bfbf580-fa6d-11e9-9479-a212b52b5807.png)
Then create/set a custom profile. So far it does not matter which features i enable or not. In fact, i have all features enabled and the issue still happens. It only stops if i unset the profile.

**Comment by DmitriySalnikov** [comment]
i have the same problem
only with enabled editor feature profile
![image](https://user-images.githubusercontent.com/7782218/67823140-f7dc5900-fad2-11e9-84e9-49a8f835e4f3.png)

**Comment by allkhor** [comment]
Same here, tested on Godot master: c1b0800784fd2538
When enabled feature profile It's making the whole editor to sink down.
Regression from 8df330bacd61529d7d cc @pouleyKetchoupp
