### ISSUE TITLE
weakref in process will make objects to skyrocket

### ISSUE THREAD

**Issue by shmellyorc** [godotengine/godot#33150]
Godot version:
Godot 3.2 Alpha 3 (from your website)

OS/device including version:
Windows 10

Issue description:
Using weakref inside process or physic process will make your object resources to skyrocket.

Steps to reproduce:
start a new godot project, add this script code to your scene:
```gdscript
var is_item_empty = null

func _process(delta: float) -> void:
	if weakref(is_item_empty).get_ref():
		pass
```
Run the project and view debugger -> monitors -> objects

Minimal reproduction project:
example above should be good.

**Comment by Zylann** [comment]
`WeakRef` is a `Reference` so it should be cleaned up properly after each `_process`, and the argument is null so there is nothing else creating new objects here... that's really odd.
