### ISSUE TITLE
JSON parsing errors aren't caught in the debugger as JSON errors

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#33169]
**Godot version:**
Godot 3.2 Alpha 2

**OS/device including version:**
Windows 10

**Issue description:**
If you miss a comma in a JSON file, making it invalid JSON, the debugger doesn't capture this in the error tab. When your code then tries to reference a structure from the JSON, you get an error "Invalid get index '<structure you're trying to reference>' (on base: 'Nil')." which is misleading. It should mention the JSON error which has caused the JSON not to load (explaining why the reference is 'Nil')

If, while the application is in a crashed state, I click the variable the JSON has been assigned to in the "locals" panel of the debugger tab, and check the inspector, it shows the error string.

**Steps to reproduce:**
Create a json file and remove a comma from the end of a line.

**Minimal reproduction project:**
JSON : (Note the "," missing from the Height line)
{
  "Name": "Bill",
  "Height": "123"
  "Weight": "456"
}

GDScript
	var file = File.new()
	file.open("res://<path-to-json-file>", file.READ)
	var filetext = file.get_as_text()
	var myjsondata=JSON.parse(filetext)
	file.close()

        var dummyvar=int(myjsondata.result["Weight"])

Error will be "Invalid get index 'Height' (on base: 'Nil')." instead of something like "JSON Error - Expected '{' or ',' on line <xyz>"

![image](https://user-images.githubusercontent.com/5151242/67827211-621cea00-fb23-11e9-92b9-2b8fb76ac12d.png)

**Comment by KoBeWi** [comment]
`parse_json` returns null on invalid string. Maybe it could inform that there was an error, but your problem comes from not checking the value, not the JSON itself.

**Comment by Xrayez** [comment]
Somewhat similar `str2var` parser function does show errors, but that's built-in function so it's expected for those errors to be caught by the debugger. I'm currently attempting to debug JSON bugs in #33161 so I have to print those `error_strings` via script though.

**Comment by balloonpopper** [comment]
I agree that the code fragment should include error checking, however I believe that the error  - as seen in the inspector - should be reflected in the error tab. It doesn't get reflected in the stdout error window either.

**Comment by Xrayez** [comment]
I think this might create problems with how the code currently *handles* those JSON errors as they might be part of the logic rather than actual errors. For example see this usage:

https://github.com/godotengine/godot/blob/aa96481c8fe350d7223304589f1256e2b9ae8e2b/modules/jsonrpc/jsonrpc.cpp#L157-L166

But yeah I think it makes sense to provide an error message for parts which are exposed to scripting specifically without touching the core.
