### ISSUE TITLE
Audio Panel/Section Goes Past The Taskbar

### ISSUE THREAD

**Issue by InsomniaWins** [godotengine/godot#33167]
**Godot version: 3.1.1**

**OS/device including version:**
Windows 10

**Issue description:**
Audio panel at the bottom of the screen (while working on project) goes past the taskbar, not allowing the user to switch back from audio unless they hide the taskbar. (and maybe due to low res monitor?).

**Steps to reproduce:**
While inside of a project click the audio section of the bottom panel (the section that says "output, debugger, search results... " Doing this on a low res monitor (mine is 1366x768) will cause the audio panel to go lower than the taskbar.
It seems to ignore the taskbar and just lock to the bottom of the monitor below the taskbar.

**Minimal reproduction project:**
Happens in all projects, so the report doesn't need any project files?

**Comment by drentsoft** [comment]
Is this related to #33155

**Comment by InsomniaWins** [comment]
> 
> 
> Is this related to #33155
It may be, but it only happens on the audio panel, not output, debugger, or animation. For the other panels it works perfectly fine.

**Comment by InsomniaWins** [comment]
It seems to have fixed itself. It was happening for several days, then it just stopped... weird but as long as it works I'm good lol.

**Comment by KoBeWi** [comment]
Closing as fixed then. Feel free to reopen this if it starts happening again.
