### ISSUE TITLE
Artifacts when rendering HTML5 export on Samsung Galaxy Tab A (2019)

### ISSUE THREAD

**Issue by uldall** [godotengine/godot#33178]
**Godot version:**
7d710a745e3eecbde482349fff78f0a4e14f6371

**OS/device including version:**
Device with issue: Samsung Galaxy Tab A (2019)
Browser on device: Chrome 77.0.3865.116

**Issue description:**
Our game doesn't render correctly.

Example:
![Screenshot_20191030-122954_Chrome](https://user-images.githubusercontent.com/628383/67855184-3cd3b000-fb12-11e9-824b-0e8a13121455.jpg)

Correct rendering on Desktop Chrome:
![Screenshot at 2019-10-30 12-33-46](https://user-images.githubusercontent.com/628383/67855129-29284980-fb12-11e9-8b23-68b677dab41e.png)

**Steps to reproduce:**
More info will follow on what render features this game specifically uses.

**Minimal reproduction project:**
Will follow if needed.

**Comment by uldall** [comment]
@clayjohn This is the same version of the game that I sent you.

**Comment by clayjohn** [comment]
@uldall Thank you. But I don't actually have this one. I have Orbs and Treasure. I have a few assets from disco-wild from another bug report from you guys, but I don't have enough to reproduce this bug. Please send me the files over email if that is what you are most comfortable with :)

**Comment by Calinou** [comment]
We should look at implementing a workaround in the long run using two separate textures (RGB + alpha). It could be done by Godot automatically on import. IIRC, this is what Unity does.

**Comment by clayjohn** [comment]
I have spoken to Juan about the best way to fix this issue. He does not like the idea of using two separate textures automatically on import. It would increase rendering cost to the user in a completely opaque way. Currently, users can specify an alpha texture manually if they want. 

The alternative we settled on is to simply use the RGBA4444 format when etc compression is used on a texture with an alpha channel. This will store the texture as uncompressed, but with half the bits. Alternatively, users can specific not to compress the texture on import if they want full bit depth. 

I will make a PR shortly that adds this functionality, hopefully in time to be included in 3.2 definitely, the fix will make it in for 3.2.1.
