### ISSUE TITLE
Rendering issues on Android GLES2 with MSAA (depth buffer issue?)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#33187]
**Godot version:**
3.2 master (8570b9b0), including with manual cherrypick of #33181 

**OS/device including version:**
Android 9, Xiaomi Pocophone F1, Adreno 630
http://opengles.gpuinfo.org/displayreport.php?id=3448

**Issue description:**
Follow up to #33172.

When enabling MSAA 2x or more on a simple 3D scene, I get rendering issues seemingly related to the depth buffer.

With the test project included below, I get:

  * PanoramaSky, no MSAA (as expected):
![f1-sky-no-msaa](https://user-images.githubusercontent.com/4701338/67854750-2e38c900-fb11-11e9-83b4-9ece8c4500a5.png)
  * PanoramaSky, MSAA 2x (broken):
![f1-sky-msaa-2x](https://user-images.githubusercontent.com/4701338/67854776-385ac780-fb11-11e9-8116-f13a5328a304.png)
  * Clear Color, MSAA 2x (kind of works, weird transparency effect):
![f1-no-sky-msaa-2x](https://user-images.githubusercontent.com/4701338/67854794-4577b680-fb11-11e9-865d-716b4d195b2c.png)

In all scenarios (so also without MSAA) I get this error spammed in the logs:
```
ERROR: GL ERROR: Source: OpenGL	Type: Error	ID: 2147483647	Severity: High	Message: location of the uniform is -1
At: drivers/gles2/rasterizer_gles2.cpp:133:_gl_debug_print() - GL ERROR: Source: OpenGL	Type: Error	ID: 2147483647	Severity: High	Message: location of the uniform is -1
```

When MSAA is enabled, I get this additional error:
```
**ERROR**: GL ERROR: Source: OpenGL	Type: Error	ID: 2147483647	Severity: High	Message: internalformat 6402 is not a renderbuffer format
   At: drivers/gles2/rasterizer_gles2.cpp:133:_gl_debug_print() - GL ERROR: Source: OpenGL	Type: Error	ID: 2147483647	Severity: High	Message: internalformat 6402 is not a renderbuffer format
```

**Steps to reproduce:**
- Set up a simple 3D scene
- Enable MSAA 2x or more
- Export to a device with Adreno 630 or similar

**Minimal reproduction project:**
[Test 3D.zip](https://github.com/godotengine/godot/files/3789936/Test.3D.zip)

**Comment by NeoSpark314** [comment]
As mentioned in https://github.com/godotengine/godot/issues/33188
the issue might be that in line
https://github.com/godotengine/godot/blob/23a381d8827dbcb2d295fa393a5400f7a7e0a1c1/drivers/gles2/rasterizer_storage_gles2.cpp#L4717
no 24bit depth buffer is created; forcing a 24bit buffer via the line
```
glRenderbufferStorageMultisample(GL_RENDERBUFFER, msaa, _DEPTH_COMPONENT24_OES, rt->width, rt->height);
```
seemed to fix the issue on the Oculus Quest with GLES2 msaa
