### ISSUE TITLE
Not possible to get the focused id in PopupMenu, without using signals

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#33180]
**Godot version:**
3.2 alpha 3

**Issue description:**
I want to get the focused item id in a PopupMenu node, to calculate the position of the focused item on the screen. It is currently only possible using the "id_focused" signal. 
get_item_count() method is already there, so it would be nice with a get_focused_id() method.

**Comment by Devination** [comment]
It looks like this has been added as `get_current_index` in https://github.com/godotengine/godot/commit/35f30086de7069df2854949948ae26642c5a1452 perhaps we can Close this ticket?

**Comment by akien-mga** [comment]
Indeed, fixed by #38520.
