### ISSUE TITLE
Making new scripts using no comment template removes the function type.

### ISSUE THREAD

**Issue by Jedzkie** [godotengine/godot#33185]
**Godot version:**
3.1.1

**OS/device including version:**
Mac OS Catalina 10.15.1 / Windows 10 64Bit 1803

**Issue description:**
When creating new script by using `no comment` template, the type of ready function is missing.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Xrayez** [comment]
It might be that the new script templates are not overwritten by new ones:
https://github.com/godotengine/godot/blob/8570b9b0c2972b7aa191475342d0dd8030fd4188/editor/editor_settings.cpp#L752

try deleting them first from `%AppData%\Godot\script_templates`.

**Comment by Jedzkie** [comment]
@Xrayez Yeah you're right. thank you! Closing this report now.
