### ISSUE TITLE
Array.append(null) should stop program with error

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3318]
I think that there should be an assertion inside Array.append() with null check. This would allow to find bugs quicker and closer their source. Was quite confused when that code throw an error:
```
if(array.empty()):
  return;
else:
  array[0].doSomething(); #<-ERROR nonexisting function in base "NIL"
```
also it didn't help to find a place where null was added to the array.

**Comment by reduz** [comment]
it should be perfectly valid to append null values to array, in fact they
are initialized null when you resize them

**Comment by kubecz3k** [comment]
@reduz Well I know that array is holding nulls sometimes that's why I only asked to add check to append (while still allowing array[3] = null). But since it's intentional I will close this issue.

**Comment by kubecz3k** [comment]
But one way or another I guess you will admit that the sample I pasted at the first post is little confusing,

**Comment by kubecz3k** [comment]
@reduz small ping since I think you might find above argument a reasonable one. (Or if not, just ignore :))
