### ISSUE TITLE
In 3D on Android transparent textures not displaying correctly

### ISSUE THREAD

**Issue by usbhell** [godotengine/godot#33198]
**Godot version:**
3.1.1 and higher
**OS/device including version:**
GLES2
Android
MOTOROLA E3 Android 6.0
CUBOT X11 Android 4.4.2

**Issue description:**
Perhaps I'm doing something wrong here. I'm trying to display a transparent texture in a 3d Node.

In the example I have 2 Sprite3Ds and a Mesh using the builtin Quadmesh and a material, both with transparent ticked. but when I run the project on an Android device the corners of the Texture should be rounded but in fact they are square which was not what I expected.

Working on Mac
![mac](https://user-images.githubusercontent.com/14961837/67938671-3d328080-fbd0-11e9-9411-fd396047e9d4.png)

Not Working Android
![android](https://user-images.githubusercontent.com/14961837/67938685-43c0f800-fbd0-11e9-9ed7-a27139497702.png)

**Steps to reproduce:**
Run attached project on an Android device. Edges of the Godot Icon should be rounded not square.

**Minimal reproduction project:**
[3dtest.zip](https://github.com/godotengine/godot/files/3793260/3dtest.zip)

**Comment by usbhell** [comment]
After a little research it seems the issue is with using a compression Mode of Video RAM and changing this to one of the other choices such as Lossless fixes my issue.

**Comment by akien-mga** [comment]
That's normal because the ETC VRAM compression format used on GLES2 does not support transparency.

If you reimport `icon.png` as Lossless, Lossy or Uncompressed, it should work.

@clayjohn Maybe something to mention in https://docs.godotengine.org/en/latest/tutorials/misc/gles2_gles3_differences.html#texture-compression ?

**Comment by usbhell** [comment]
Thanks a lot anyway.
