### ISSUE TITLE
Colored emojis are broken

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#33193]
**Godot version:**
d482a1d

**OS/device including version:**
Manjaro GNU/Linux

**Issue description:**
- Setting `outline` to any value bigger than 0 makes them render all at the same position.
- Also with `outline`, they show "tofu" behind them, even if they are rendered successfully.
- Their size ignores the viewport, being rendered at resolution size always.

Non-colored emoji fonts work completely fine.
Tested with Google's [Noto Color Emoji](https://www.google.com/get/noto/#emoji-zsye-color).

**Comment by volzhs** [comment]
![image](https://user-images.githubusercontent.com/8281454/67906338-8d511900-fbb7-11e9-873e-5fb49a163bfe.png)


can't reproduce it with 924db5fa58
would you provide a sample project and screenshot?

**Comment by YeldhamDev** [comment]
Here @volzhs, my viewport settings are `2d` and `keep_height`.
![Screenshot_20191030_203936](https://user-images.githubusercontent.com/30739239/67907068-97025e80-fb6e-11e9-8d00-a7bd5fd63be3.png)

I also updated the report with an issue with the `outline` value.

**Comment by volzhs** [comment]
try `Use Oversampling` off at Rendering > Quality

**Comment by YeldhamDev** [comment]
Already on.

**Comment by volzhs** [comment]
off, not on.

**Comment by YeldhamDev** [comment]
Sorry, that fixes size problem, but the others persist.

**Comment by YeldhamDev** [comment]
@volzhs Outline still only just shows the "unknown character" symbol behind the emojis.

**Comment by volzhs** [comment]
I couldn't reproduce that one. even with alpha.
would you share a demo project?

**Comment by YeldhamDev** [comment]
The problem only happens when the emoji font is defined as a fallback.

**Comment by volzhs** [comment]
ah, i understood now. would you open new issue for it?

**Comment by YeldhamDev** [comment]
Sure thing.

**Comment by YeldhamDev** [comment]
Here it is: #34870
