### ISSUE TITLE
Waiting too long while writing a method call triggers error highlighting and completion becomes useless (fixed in GDScript 2.0)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#33191]
Godot 3.2 alpha3

I ended up again in a case like this one:

![image](https://user-images.githubusercontent.com/1311555/67904842-8b5f6980-fb67-11e9-9aa7-316d107d06ab.png)

Argument hints don't work, Ctrl+Click to lookup the method doesn't work. Even though the script editor surely knows what method it is (I gave a type to the variable), it looks like it just forgot or something? I'm left having to lookup the method manually to remember what arguments it takes. Or rewrite it until I get completion.

I'm noticing this quite often and it breaks my flow. Not all script assists should be turned off in this situation.

Update: in fact even after I fixed the error, Ctrl+Click on the method still doesn't work, so looks like two issues in here.

**Comment by Calinou** [comment]
This is resolved in `master` with the [GDScript rewrite](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged), but it's unlikely that this can be fixed in `3.x`.

**Comment by akien-mga** [comment]
Let's close as fixed in 4.0 then, it's not a critical issue that requires spending too much time on `3.x` specifically (but if any contributor wants to work on it, feel free to).
