### ISSUE TITLE
Regression: Batch Rename menu not openning

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#33208]
**Godot version:**
3.2.alpha.official

**OS/device including version:**
Solus 4.0 Gnome 3.34.1

**Issue description:**
The batch rename menu is not opening when we <kbd>RMB</kbd> and chose "Batch Rename" from the dropdown menu 

**Steps to reproduce:**
1. Create a scene with multiple nodes
2. Select multiple nodes in the same level of the hierarchy
3. <kbd>RMB</kbd> on the nodes and select "Batch Rename" from the dropdown menu

**Comment by kraghot** [comment]
Same thing happens for me.

I'll try and look into this
