### ISSUE TITLE
Export All fails to find export path

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#33205]
**Godot version:**
3.2.alpha3.official

**OS/device including version:**
Solus 4 Gnome 3.34.1

**Issue description:**
When configuring a default export path and pressing "export all" Godot fails to find path, I think it is not converting the relative path to absolute path on export time, and it doesn't allow us to keep the absolute path, i.e. it always automatically convert absolute path to relative path.

![image](https://user-images.githubusercontent.com/10171059/67954326-83d3ab00-fbcf-11e9-8560-9e90c3acef45.png)

Exporting by pressing the **`Export Project`** instead does not cause this error.

**Steps to reproduce:**
1. Setup a project
2. Setup its export template
3. Setup an export preset
4. Configure the `Export Path` property
5. Hit the `Export All` button

**Comment by fsy98** [comment]
I tried the same reproduce but didn't have that error.
But I think is maybe your file path makes the problem, so just try differnt file path and see what would happen.
![image](https://user-images.githubusercontent.com/30133945/68424367-d1bd5580-0171-11ea-9add-84951f494c59.png)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by henriiquecampos** [comment]
@KoBeWi I think this is fixed! Thanks a lot.
