### ISSUE TITLE
Duplicating CollisionShape2Ds causes them to set both of their shape's dimensions at once

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [godotengine/godot#33217]
**Godot version:**

_3.2 alpha 3_ and _3.1 stable_

**OS/device including version:**

All

**Issue description:**

*Occurs in Editor*

When you duplicate a CollisionShape2D and change the size of one, they both get changed.

**Steps to reproduce:**

Create a CollisionShape2D, add a shape, duplicate it, modify the dimensions of it's shape and they both get changed.

**Minimal reproduction project:**

[Linked CollisionShape2Ds Demo.zip](https://github.com/godotengine/godot/files/3795249/Linked.CollisionShape2Ds.Demo.zip)

**Comment by KoBeWi** [comment]
This is expected. Their Shape resource is shared, so to avoid this, you need to make it unique.
![image](https://user-images.githubusercontent.com/2223172/67977406-52330200-fc18-11e9-8874-a7f3050b6d46.png)
(Make Unique)
