### ISSUE TITLE
Cannot construct scene tree in the Getting Started 

### ISSUE THREAD

**Issue by nicolls1** [godotengine/godot#33248]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
macOS High Sierra 10.13.6

**Issue description:**

I'm going through the tutorial here:
https://docs.godotengine.org/en/3.1/getting_started/step_by_step/scripting.html#scene-setup

After creating a panel and then right clicking and adding a label and button as a child, they do not show up in the Scene dialog. There is a picture with the scene tree and I cannot figure out how to get it to look like that.

Might be related to [#23637](https://github.com/godotengine/godot/issues/23637)

Maybe I'm doing something wrong as I am just getting started but would be happy to update the docs if that is the case.

**Steps to reproduce:**

Create new empty project. Add Panel as root node in scene. Add Label and Button as a child node (I used right click on Panel -> Add Child Node). Both do not show up in the Scene box on the left. 

**Minimal reproduction project:**
N/A

**Comment by KoBeWi** [comment]
Any screenshot/video of this happening? Aren't there any errors in the console? Isn't the tree folded? Is filter field empty? Is this reproducible in any project or happened once? (can't reproduce it btw)

**Comment by nicolls1** [comment]
I just made a scratch project and started to do a screen recording and this time it worked. Really not sure what I did differently. Sorry for the trouble.

**Comment by KoBeWi** [comment]
For the future, if you find something that works in unexpected way, make sure it is a bug and it's reproducible. Vague issues with little details usually don't get any activity for months and just get closed.
