### ISSUE TITLE
Curve lines are invisible in exported curve

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#33251]
**Godot version:**
3.2 alpha 3
**OS/device including version:**
Arch Linux
**Issue description:**
The lines on an exported `Curve` variable are invisible
**Steps to reproduce:**
1. Export a curve like `export (Curve) var my_curve`
2. Go to the editor and create a new curve on the `my_curve` property
3. Right click on the graph then select a preset such as `linear`
4. Although the line is visible at first, after moving one of the nodes on the path, it  turns invisible.

Screenshot provided 
![image](https://user-images.githubusercontent.com/28424206/68063064-7865aa00-fccb-11e9-8ff1-19d5945eac86.png)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/e4d734725ad7433cb2d75cd71f43e4f7c2b92417.

**Comment by creikey** [comment]
I can confirm that this issue is fixed on the latest commit @Calinou
