### ISSUE TITLE
Godot 3.1.1 android screen flickering

### ISSUE THREAD

**Issue by MungMoongYi** [godotengine/godot#33250]
**Godot version:**
3.1.1

**OS/device including version:**
version : android 9

**Issue description:**
When I start a game on Android, the screen flickers and nothing happens
A few months ago there was nothing wrong with exporting to Android
But I've had a problem since I changed my developing pc
The newly created project will run fine without any problems.
I changed the path of the files again and downloaded and set the Android custom template again.

I am using a separate splash image
Image with white background, GODOT logo is not set as splash image

**Steps to reproduce:**
Connect your Android device to your pc
Click One-Click Deployment
The screen flickers when the game is run on an Android device after all deployments

**Minimal reproduction project:**
I don't know what's mean

<details>
<summary>Seizure warning (flickering screen)</summary>

![screen flicker](https://user-images.githubusercontent.com/45917152/68060336-4001b280-fd43-11e9-8126-05ff7795eb86.gif)
</details>

**Comment by FeralBytes** [comment]
@MungMoongYi I recommend trying Godot in GLES 2 mode. [See this comment](https://github.com/godotengine/godot/issues/33223#issuecomment-548628338) If that does not fix the issue then report back with more details like adb logcat output and more phone specs.

**Comment by Faless** [comment]
I remember having similar issues quite some time ago, turns out I was using the wrong export template (different godot versions for template and editor).
Just something you could double check given that you say you are using a custom export template

**Comment by MungMoongYi** [comment]
> @MungMoongYi I recommend trying Godot in GLES 2 mode. [See this comment](https://github.com/godotengine/godot/issues/33223#issuecomment-548628338) If that does not fix the issue then report back with more details like adb logcat output and more phone specs.

I've been using GLES2 since the beginning.

**Comment by MungMoongYi** [comment]
> I remember having similar issues quite some time ago, turns out I was using the wrong export template (different godot versions for template and editor).
> Just something you could double check given that you say you are using a custom export template

Thank you!
As you said, the version of the custom package was a problem.
Now I can run the game successfully
There's still a problem with so laggy

**Comment by akien-mga** [comment]
I'm surprised that the splash screen on your custom template is a Godot 2.1 logo. Is that on purpose, or do we actually still have an occurrence of the old logo somewhere that is used on Android?
