### ISSUE TITLE
Core/Math/Octree is emmiting empty error to debug console

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3325]
This error should provide some additional information for dev on what exactly goes wrong:
![emptyconsoleerror](https://cloud.githubusercontent.com/assets/6129594/12265250/5b399774-b93c-11e5-9843-01927442d0c7.png)
It's in e291294c7981f108dbb8658976b109df1850d303

**Comment by kubecz3k** [comment]
Some further observations: I have a lot of these errors, each one of them is somehow related to ImmediateGeometry node that I'm using to draw debug info (I deducted this because when I remove these nodes from the scene there is no error). In the case when these errors are showing in the console, and I remove problematic ImmediateGeometry nodes in runtime from the scene tree, the game is ocasionally crashing with no indicator on what goes wrong, here is backtrace of this crash:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000012431c1 in Set<VisualServerRaster::Instance*, Comparator<VisualServerRaster::Instance*>, VisualServerRaster::OctreeAllocator>::_insert_rb(VisualServerRaster::Instance* const&) ()
(gdb) bt
#0  0x00000000012431c1 in Set<VisualServerRaster::Instance*, Comparator<VisualServerRaster::Instance*>, VisualServerRaster::OctreeAllocator>::_insert_rb(VisualServerRaster::Instance* const&) ()
#1  0x000000000122dd96 in VisualServerRaster::instance_pair(void*, unsigned int, VisualServerRaster::Instance*, int, unsigned int, VisualServerRaster::Instance*, int) ()
#2  0x0000000001240a8a in Octree<VisualServerRaster::Instance, true, DefaultAllocator>::_element_check_pairs(Octree<VisualServerRaster::Instance, true, DefaultAllocator>::Element*) ()
#3  0x0000000001257962 in Octree<VisualServerRaster::Instance, true, DefaultAllocator>::move(unsigned int, AABB const&) ()
#4  0x0000000001233561 in VisualServerRaster::_update_instance(VisualServerRaster::Instance*) ()
#5  0x000000000123371b in VisualServerRaster::_update_instances() ()
#6  0x0000000001236346 in VisualServerRaster::_draw_viewport_camera(VisualServerRaster::Viewport*, bool) ()
#7  0x00000000012379b1 in VisualServerRaster::_draw_viewport(VisualServerRaster::Viewport*, int, int, int, int) ()
#8  0x0000000001238b18 in VisualServerRaster::_draw_viewports() ()
#9  0x0000000001238de1 in VisualServerRaster::draw() ()
#10 0x0000000000417266 in Main::iteration() ()
#11 0x000000000041285d in OS_X11::run() ()
#12 0x000000000040ef80 in main ()
```
Unfortunatelly I'm unable to recreate this bug in any other smaller project.

**Comment by Chaosus** [comment]
(bugsquad) I do not observe this error in current master and 2.1.5, its also very old and have no other information or example project. if you still have this issue, please recreate a new one.
