### ISSUE TITLE
Using TileMaps in editor causes it to shakes / very quickly resizes back and forth whilst editing

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [godotengine/godot#33269]
**Godot version:**

_3.2 alpha 3_ but **not in _3.1 stable_**

**OS/device including version:**

All

**Issue description:**

When editing or placing Tiles in a TileMap the editor shakes / very quickly resizes back and forth.

**Steps to reproduce:**

Create a TileMap, edit the Tiles placed / place tiles.

**Minimal reproduction project:**

[TileMap Editor Shake Demo.zip](https://github.com/godotengine/godot/files/3800536/TileMap.Editor.Shake.Demo.zip)

**Comment by Calinou** [comment]
Duplicate of #31836.

**Comment by AtomaFajrovulpo** [comment]
@Calinou This issue is different, it does not just happen when the Animation tab is open.

**Comment by AtomaFajrovulpo** [comment]
Infact this bug can be prevented by opening the Animation tab and the bug won't happen until the next time you open the project.

**Comment by AtomaFajrovulpo** [comment]
@akien-mga @Calinou Could you re-open this issue please ?

**Comment by akien-mga** [comment]
See #32099 which aims to solve that.

IMO the better solution is to move this label out of the toolbar, we should avoid dynamically sized content there. This could indeed be an overlay on the viewport.

**Comment by AtomaFajrovulpo** [comment]
What about making it overlap like this?
That seems to be the solution in the node tree when it is shrinked.
![1](https://user-images.githubusercontent.com/55881826/68082923-97bf1d00-fe1a-11e9-9012-3d8555931899.PNG)

**Comment by bojidar-bg** [comment]
Problem seems to be this label:
<table><tr>
<td>

![image](https://user-images.githubusercontent.com/5276727/68082567-220d7e00-fe27-11e9-976f-5d25467502bf.png)

</td>
<td>

![image](https://user-images.githubusercontent.com/5276727/68082568-28035f00-fe27-11e9-8c17-4f7c74a6598e.png)

</td>
</tr></table>

("icon.png 0" takes more space than "none")

On larger window sizes this is not a problem, but on smaller screens (wheneven the toolbar is full), the resizing of the label causes the docks on the right to be shifted back and forth.

**Comment by StyrmirNathrakh** [comment]
Still happens in Godot 3.2 beta 1. Like @bojidar-bg posted on smaller screen that label with numbers changes the size of the dock, on my 1366x768 laptop it even happens when the numbers gets above 9.

**Comment by AtomaFajrovulpo** [comment]
This is a duplicate of https://github.com/godotengine/godot/issues/28135.
