### ISSUE TITLE
Node inspector does not update properly when editing gradient

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot#33265]
**Godot version:**
c5279432f

**OS/device including version:**

ubuntu 19 but probably irrelevant

**Issue description:**

When I add new points to gradient color picker in node inspector window list of offsets/colors does not update automaticly - one needs to open/close it to see new entries.

https://giphy.com/gifs/Ss5y0fdKy0DFqHUTZL

**Steps to reproduce:**
1. create texture rect with gradient texture
2. open list of gradient offsets
3. add new offsets in colorpicker (or whatever it's called)
4. opened list contains old data because it is not updated
5. close list to see that it gets finally updated

expected:
when i add new offset points list should update on spot

It seems that the reason for bug is that gradient_edit is not communicating it's changes to inspector but only to gradient class. Gradient classes are not aware of existance of list properties and inspector as far as I can tell so it is not as easy as connect some signal to force an update. Update only happens when list classes are updated because they are aware of existance of gradient and pull new data from it on change.

**Comment by ssd71** [comment]
I am working on this

**Comment by KoBeWi** [comment]
Still valid in 94e5f66
![image](https://user-images.githubusercontent.com/2223172/96321632-73058a80-1016-11eb-9375-af49d3a1f29d.png)

**Comment by KoBeWi** [comment]
Fixed in 4.0
![godot windows tools 64_MG2K4c2xCw](https://user-images.githubusercontent.com/2223172/164112845-bd07f9b9-6517-4a4f-bbe9-80d2c9db10ea.gif)
