### ISSUE TITLE
Ctrl+left click on editor(jump to function or variable) sometimes not jump to token line in the same script

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#33262]
**Godot version:** 3.1.1 from website

**OS/device including version:** linux mint

**Issue description:** this only happened if the intended function is below the current function. This is also happened in declared variable in the same script.

**Steps to reproduce:**-

**Minimal reproduction project:**-

**Comment by KoBeWi** [comment]
Duplicate of #20393

Fixed in 3.2
