### ISSUE TITLE
Inconsistencies in documentation (true and [code]true[/code])

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#33263]
In some cases true is used as a normal word, and in others it is considered code. What is the right version?

**Comment by akien-mga** [comment]
It should always be code when referring to the boolean value: https://docs.godotengine.org/en/3.1/community/contributing/docs_writing_guidelines.html#use-if-true-to-describe-booleans

**Comment by KoBeWi** [comment]
This was already fixed once #28125

**Comment by Jummit** [comment]
Sorry, I thought it was already fixed. But since #28125 there have been more cases of this problem.
