### ISSUE TITLE
Material is not updated immediately when assigning albedo texture

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#33276]
**Godot version:**
3.2-alpha 7210bed2b1

**OS/device including version:**
Linux mint 19.2

**Issue description:**
Material is not updated immediately when assigning albedo texture.

**Steps to reproduce:**
1. create new `Spatial Material`
2. assign `Albedo` texture
3. see if it's updated on viewport
4. check `Enabled` with `Emission` or `Normal Map`

![spatial_mat_albedo](https://user-images.githubusercontent.com/8281454/68078156-e7e6b100-fe13-11e9-9146-cba688903519.gif)

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
This is the same underlying cause as https://github.com/godotengine/godot/issues/33234

I am putting together a PR already.
