### ISSUE TITLE
Opening Animation tab with TileMap open or vica versa causes editor to widen off-screen

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [godotengine/godot#33271]
**Godot version:**

_3.2 alpha 3_

**OS/device including version:**

All

**Issue description:**

Opening Animation tab with TileMap open or vica versa causes editor to widen off-screen.

Might be linked to #33269, #31836 and #32099.

**Steps to reproduce:**

Click on the Animation tab, click on a TileMap.
_or_
Click on a TileMap, click on the Animation tab.

**Minimal reproduction project:**

[TileMap Editor Shake Demo.zip](https://github.com/godotengine/godot/files/3800663/TileMap.Editor.Shake.Demo.zip)

**Comment by arkology** [comment]
In alpha 3, the editor off-screen expansion is present not only in these tabs, but everywhere (for example, when switching to the script tab, of shader tab)

**Comment by AtomaFajrovulpo** [comment]
@arkology It only happens to me on the Animation tab strangely.

**Comment by AtomaFajrovulpo** [comment]
Fixed in 3.2 beta 1. These labels ![image](https://user-images.githubusercontent.com/55881826/68476074-aeea7a00-0221-11ea-8d71-c71b2db75914.png) still push the left hand side columns and make them smaller but no longer pushes them offscreen.
