### ISSUE TITLE
Editor is remained dimmed after creating resource.

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#33274]
**Godot version:**
Godot 3.2-alpha 7210bed2b1

**OS/device including version:**
Linux mint 19.2

**Issue description:**
Editor is remained dimmed after creating resource on FileSystem panel.

**Steps to reproduce:**
![editor_dimming](https://user-images.githubusercontent.com/8281454/68077868-00080180-fe0f-11e9-822d-1caa0aa6b8c5.gif)

**Minimal reproduction project:**

**Comment by volzhs** [comment]
cc @YeldhamDev

**Comment by YeldhamDev** [comment]
Damn those corner cases, I will see what I can do.
