### ISSUE TITLE
C# Task Async for Remote method doesn't work

### ISSUE THREAD

**Issue by ricardoalcantara** [godotengine/godot#33272]
**Godot version:** 3.1.1 mono

**OS/device including version:** PopOS 18.04

**Issue description:** 
This code doesn't work
```C#
    [Remote]
    private async Task Login(string email, string hash_password)
    {
        await Task.Delay(2000);
        var user = await _database.LoginUserAsync(email, hash_password);
        if (user != null)
        {
            GD.Print("User Logged in ", user.Email);
            RpcId(senderId, "LoginAccepted");
        }
        else
        {
            ((NetworkedMultiplayerENet)Multiplayer.GetNetworkPeer()).DisconnectPeer(senderId);
        }
    }
```
The Task.Delay is set just for testing.
It shows this error:
```bash
ERROR: mono_object_to_variant: Attempted to convert an unmarshallable managed type to Variant. Name: 'Task`1' Encoding: 21
   At: modules/mono/mono_gd/gd_mono_marshal.cpp:766.
```

**Steps to reproduce:**
Create a remote method with Async Task

**Minimal reproduction project:**

**Comment by WizzardMaker** [comment]
Why are you using Task as a return type? You could just use void, when Login is just an async method, or what is your use case for the Task return?

The error comes probably, because the type Task can not be interpreted by the C++ side of the engine.

**Comment by ricardoalcantara** [comment]
@WizzardMaker I am returning Talk because it's an async method and any async method should return Task for void return or Task<T> for T return (AFAIK). 

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

I understand that C++ cannot interpret it but for me it's a bug. But I wanted to confirm that it cannot be implemented this way. it could run asynchronously and since it's a remote method that is already 'async' it could call others async methods. 

Reading the documentation

https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_differences.html#yield

It looks like the mono implementation has used custom implementation of the async aways, but I haven't dig into the code to try to understand it.

**Comment by WizzardMaker** [comment]
The Task return type is debatable, but it's more than okay to use void, when you are using it for event handlers or when you know, that you will not wait (`await`) for them.
[https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/async/async-return-types](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/async/async-return-types#BKMK_VoidReturnType)

Godot doesn't really have a custom implementation for the `await` "method". It is using special methods to handle Godot signals, so that you can wait for a signal, with `ToSignal()`. You use `await ToSignal(Object, SignalName)` to wait for signals. You shouldn't run into problems, when you use `await` any other way. I used await a lot in my project.

**Comment by ricardoalcantara** [comment]
@WizzardMaker 
> The Task return type is debatable, but it's more than okay to use void, when you are using it for event handlers or when you know, that you will not wait (await) for the async method.

Sorry, I didn't mean to impose anything I made a test using async with void and it didn't compile, maybe I had made something.

I am just used to have the base function async but now I know I cannot have it, this is why I opened this issue.

**Comment by WizzardMaker** [comment]
No problem! Could you show me the method, that failed to compile?

**Comment by ricardoalcantara** [comment]
I tried again @WizzardMaker and compiled fine this time, as I sad I may have made something wrong together. But I noticed that I won't be able to use asynt methods because it looses the context and I can no longer get `Multiplayer.GetRpcSenderId();`

I will close my issue. Thanks for your patience.
