### ISSUE TITLE
Collada files import into Godot with missing geometry

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#3328]
An FBX file with animation (converted to Collada format using Autodesk FBX converter) imports into Godot with part of the geometry missing.
The FBX converter used:
![colladageometry-04](https://cloud.githubusercontent.com/assets/15687516/12267286/ac57b7f2-b947-11e5-94a4-6bf7c6725723.png)
The resulting Collada filed opened in 3DS Max 2016:
![colladageometry-01](https://cloud.githubusercontent.com/assets/15687516/12267708/b9181be2-b949-11e5-8778-0306773212bb.png)
Imported into 3DS Max using these settings:
![colladageometry-05](https://cloud.githubusercontent.com/assets/15687516/12267326/e2677ee0-b947-11e5-8ac9-63d684341fa6.png)
The Collada file as it appears in Godot after importing:
![colladageometry-02](https://cloud.githubusercontent.com/assets/15687516/12267347/f5a3f092-b947-11e5-84f7-de8815c7d577.png)
Using these import settings:
![colladageometry-03](https://cloud.githubusercontent.com/assets/15687516/12267354/0060fab6-b948-11e5-9447-de921ff91367.png)
As the red outline indicates the characters arrow is missing in Godot but not in 3DS Max.

**Comment by reduz** [comment]
Use the OpenCollada exporter and export directly as dae

https://github.com/KhronosGroup/OpenCOLLADA/wiki/OpenCOLLADA-Tools

Autodesk DAE support sucks.
