### ISSUE TITLE
Exported non-initialized typed string has "Null" value

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33288]
**Godot version:**
3.2 alpha3

**Steps to reproduce:**
1.
```
export var test: String
```
2.
![image](https://user-images.githubusercontent.com/2223172/68087443-1e452000-fe56-11e9-8372-d336910b632f.png)

**Issue description:**
`export(String) var test` works correctly, but it doesn't have a type. `export(String) var test: String` is just awkward...

**Comment by tom-jk** [comment]
Testing on linux mint 18.3.

Can reproduce in 3.1.stable thru 3.2.beta6
Can't reproduce in 3.2.rc1 thru 3.2.3.rc3

Issue appears to be resolved.
