### ISSUE TITLE
When connecting a signal, new line should be created only if necessary

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33287]
**Godot version:**
3.2 alpha3

**Issue description:**
I recently noticed that when I connect a signal to a script, it always adds an empty line above the method and below the method. This often results in double newlines, especially after #29262. The upper newline should be added only if there's no newline already. Or not at all, because it's rarely needed.

**Comment by Eoin-ONeill-Yokai** [comment]
I've noticed this behavior as well and it bothers me. I've gone ahead and made a patch to resolve this.

**Comment by KoBeWi** [comment]
I forgot about this issue tbh. Looks like saving a script now truncates all extra empty lines, so it's unlikely you will end up with more than 2 when creating signal callback. The "double newlines" are apparently intended, so closing.
