### ISSUE TITLE
Order of h_frames/v_frames in the inspector

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33289]
**Godot version:**
3.2 alpha3

**Issue description:**
This always bothered me, so I though I'd create an issue. Why Sprite's `v_frames` are in the inspector before the `h_frames`? Usually, horizontal properties are listed before vertical ones. Like in vectors (x/y) and rectangles (width/height) etc. Even in CanvasItemMaterial, when you enable `particles_animation`, h frames are before v. Camera2D used to have this problem with offset, but I ninja-swapped it in one of PRs.

So, could this be changed for Sprite and Sprite3D, so `h_frames` are before `v_frames`? >_>
It doesn't break compatibility, just inspector-only visual thing. (also it's fit for Junior Job)

**Comment by akien-mga** [comment]
> (also it's fit for Junior Job)

Only once there is a consensus :)
"Discussion" issues are bad first issues as new contributors will often make a PR which may not be merged if not consensual.

**Comment by KoBeWi** [comment]
> Only once there is a consensus :)

That's why I haven't labelled it yet.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Hello. The opposite argument is valid. Why should you put h before v? I think we should stick with what we have and not worry about is is vertical or horizontal that's first.  I happen to prefer the way it is now.

**Comment by MaaaxiKing** [comment]
I agree with you, @KoBeWi . Another reason is that h comes before v in the alphabet.

**Comment by vnen** [comment]
Is this really a problem? I think it makes more sense for `v_frames` to come first. That is the amount of columns, and with `x` you select the column, so it has the same order in this sense.

If people prefer the `h` first I don't mind. I think that an issue like this should be decided to change or not change quickly and close it either way.

**Comment by EricEzaM** [comment]
@vnen agree with you here regarding minor issues like this. Personally I dont mind but I think an executive decision should be made; yes/no, and then we move on. Otherwise we just end up with a stack of minor issues/suggestions that live on for many months/years.
