### ISSUE TITLE
Searching for O in editor shortcuts shows all Nones

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33299]
**Godot version:**
3.2 alpha3

**Steps to reproduce:**
1. Open Editor Settings
2. Go to shortcuts
3. Try to find a shortcut using "O"
4. You can't, because every non-assigned shortcut shows
![image](https://user-images.githubusercontent.com/2223172/68091161-94f51400-fe7c-11e9-9730-308cc20a8170.png)

IMO searching shortcut name and assigned keys should be separate, either by separate text fields or with checkboxes. Also "None" shouldn't show in single-letter searches :/

**Comment by Calinou** [comment]
Blender has a dropdown for this:

![image](https://user-images.githubusercontent.com/180032/68352796-dea55f00-0107-11ea-9d40-342649b1b2b1.png)

**Comment by KafeleW** [comment]
"None" shows because of the search looking for any word containing the letters typed, but I agree that it should be changed.
