### ISSUE TITLE
godot 3.1.1 crashes and crashes NVIDIA OpenGL driver with it

### ISSUE THREAD

**Issue by mhamedoyt** [godotengine/godot#33292]
(my English is not good but I will try my best)

when I open Godot it opens perfectly but when I open project the screen turn black and hen this message pop-out 
![sdasdasdd](https://user-images.githubusercontent.com/57325386/68088756-d8468700-fe6a-11e9-9078-70c35488b2a0.png)

and then the screen keeps glitching until I restart the pc 

my pc is :
windows 7 64-bit
OpenGL 2.1
GeForce 6150SE nForce 430 

the console behind Godot shows nothing and nothing else happen

(sorry if I made nothing wrong, first time reporting an issue) , (sorry if its duplicated, found no solution)

**Comment by Calinou** [comment]
> GeForce 6150SE nForce 430

This is a very low-end integrated graphics card. I'm afraid it's too old and slow to run Godot (even the GLES2) renderer :slightly_frowning_face:

**Comment by mhamedoyt** [comment]
thank you , i know i haven't upgraded the graphic card for 4-5 years ... will try to upgrade it soon

**Comment by KoBeWi** [comment]
> any good open-source game engine for my requirements?

You can see a nice list of open-source engines here: https://github.com/Calinou/awesome-gamedev#engines

I think this issue can be closed, because it's not about something we can fix, is it?
