### ISSUE TITLE
"Export All" shouldn't require selection

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33293]
**Godot version:**
3.2 alpha3

**Issue description:**
When you try to export project, there's the "Export All" option that basically exports for all defined presets. However, it is only clickable when you have any preset selected, which makes sense for "Export Project", but not "Export All". You should be able to export everything if there's at least one preset, not if something is selected.

**Comment by Calinou** [comment]
For the Export All button to be enabled, all presets must have an export path defined. To solve this issue, the check should be performed when initially opening the dialog, in addition to clicking an export preset.
