### ISSUE TITLE
Invisible Contents of FileDialog

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#3330]
There seem to be multiple conditions which cause a FileDialog to have invisible contents in 1.1 Stable. The behavior may be less deterministic in 2.0 Alpha.

In my experience (and in the attached example), all FileDialogs left with the default settings will not show the contents of the resources directory, although if you double-click where files and folders ought to be it will navigate through them.

The default access mode appears to be ACCESS_RESOURCES. Manually setting this will have no effect; the contents will still be invisible. For example:

    extends FileDialog
    func _ready():
    	set_access(ACCESS_RESOURCES)

will not be usable. Setting the access mode to any other access mode behaves as expected. Furthermore, setting the access mode to something else and then back to ACCESS_RESOURCES before the FileDialog is even drawn appears to help in some cases:

    extends FileDialog
    func _ready():
    	set_access(ACCESS_RESOURCES)
    	set_access(ACCESS_USERDATA)
    	set_access(ACCESS_RESOURCES)

The above will behave as expected in the example project, where the contents of the resources directory are visible.

But that workaround does not work in the actual project for which I'm trying to add a FileDialog. I have yet to figure out how to access the resources directory without the FileDialog's display of the resources directory's contents being invisible.

[FileExample.zip](https://github.com/godotengine/godot/files/87998/FileExample.zip)

**Comment by kubecz3k** [comment]
Downloaded your sample but can't reproduce the bug in e291294c7981f108dbb8658976b109df1850d303 build. Looks like it's fixed now, compile new build or download it from http://fixnum.org/godot/ and try to check your issue.

**Comment by trollworkout** [comment]
@kubecz3k  I am trying right now. Thank you for the swift reponse btw

**Comment by trollworkout** [comment]
@kubecz3k  I am on OSX. I cannot use the builds from  the link you provided since they are all for windows. This is a platform specific issue and likely Yosemite only issue.

**Comment by trollworkout** [comment]
@kubecz3k  disregard my previous comments i erased them . posted on the wrong issue

**Comment by Gastronok** [comment]
I just downloaded the newest build from http://fixnum.org/godot/15_11_03__12_34_12/tools/godot.windows.tools.64.exe and opened up the example attached in my previous post. Here's a video of it behaving badly: [Video.zip](https://github.com/godotengine/godot/files/89297/Video.zip)

**Comment by vnen** [comment]
Might be related to #3263.

**Comment by Gastronok** [comment]
I just tested my original example again on a different computer, with both 1.1 Stable and Godot_v2.0_alpha_20150930_win64.exe. I observe the same issue there, even though there is little in common between the two machines. They're both running Windows 7 (only one is SP1), and they both have Nvidia cards, but one's a desktop with an older card and the other is a workstation laptop with a more recent GPU. I don't think I'll have access to a graphical Linux system anytime soon to see if that makes a difference.

**Comment by Gastronok** [comment]
My project seems to behave as expected in 2.0 RC1, although I don't remember the precise feature I was trying to add now. But also adding a call to popup() in my example causes it to work. There might be some initialization code there that was otherwise being skipped. Which maybe only affects certain video drivers.

I'll close this off, since I no longer have impacted use cases and perhaps the bug was fixed along the way.
