### ISSUE TITLE
Polling non-existent action doesn't raise any errors

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33303]
**Godot version:**
3.2 alpha3

**Issue description:**
Try this code
```
func _process(delta: float) -> void:
	print(Input.is_action_pressed("this action totally doesn't exist'"))
```
It will just print `false`. It should probably show some error if the action isn't defined.

**Comment by Calinou** [comment]
It seems you get an error when using `event.is_action_pressed()`, but not `Input.is_action_pressed()` (tested on https://github.com/godotengine/godot/commit/86da206b84e107585deddfebc2c311c9dcc10795).
