### ISSUE TITLE
String's replace_first isn't bound in GDScript

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33308]
**Godot version:**
3.2 alpha3

**Issue description:**
I once noticed in source code a method called `replace_first`, which sounds useful. But it's not bound to GDScript :<
Exposing it to GDScript is literally one-line, so IMO there's no reason it's not there. (also, again arguable Junior Job)

**Comment by Calinou** [comment]
Should we also have `replace_firstn` for case-insensitive replacements?
