### ISSUE TITLE
F2 in Input Map and Editor Shortcuts dialog have space between F and 2

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33305]
**Godot version:**
3.2 beta3

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/68091512-03d46c00-fe81-11e9-9fc6-d5e0c202ba15.png)

Ofc happens to other Fs too. Displays properly in Editor Shortcut list, but same problem on Input Actions list.
![image](https://user-images.githubusercontent.com/2223172/68091557-8826ef00-fe81-11e9-82e0-264207a00349.png)
![image](https://user-images.githubusercontent.com/2223172/68091559-9412b100-fe81-11e9-9990-758e4933ee54.png)

**Comment by Calinou** [comment]
This is presumably because the `String::capitalize()` function is used behind the scenes, which separates letters from numbers.
