### ISSUE TITLE
Node paths in quotes should have the same color

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33316]
**Godot version:**
3.2 alpha

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/68092522-641cdb00-fe8c-11e9-8cbb-d3feb8fa2fe3.png)
Both should be green in this case IMO.

**Comment by Calinou** [comment]
This could work in theory, but since the string highlighting takes priority over node path highlighting, it's not visible in practice:

```diff
diff --git a/modules/gdscript/editor/gdscript_highlighter.cpp b/modules/gdscript/editor/gdscript_highlighter.cpp
index 4d6279074c..7cbff7ea68 100644
--- a/modules/gdscript/editor/gdscript_highlighter.cpp
+++ b/modules/gdscript/editor/gdscript_highlighter.cpp
@@ -275,7 +275,7 @@ Map<int, TextEdit::HighlighterInfo> GDScriptSyntaxHighlighter::_get_line_syntax_

                if (!in_node_path && in_region == -1 && str[j] == '$') {
                        in_node_path = true;
-               } else if (in_region != -1 || (is_symbol && str[j] != '/')) {
+               } else if (in_region != -1 || (is_symbol && str[j] != '/' && str[j] != '"' && str[j] != '\'')) {
                        in_node_path = false;
                }
```

(The effect will be visible if you disable string highlighting in `script_text_editor.cpp`.)

**Comment by hilfazer** [comment]
> 
> 
> With the method below, this could work in theory. However, since the string highlighting takes priority over node path highlighting, it's not visible in practice:
> 
> ```diff
> diff --git a/modules/gdscript/editor/gdscript_highlighter.cpp b/modules/gdscript/editor/gdscript_highlighter.cpp
> index 4d6279074c..7cbff7ea68 100644
> --- a/modules/gdscript/editor/gdscript_highlighter.cpp
> +++ b/modules/gdscript/editor/gdscript_highlighter.cpp
> @@ -275,7 +275,7 @@ Map<int, TextEdit::HighlighterInfo> GDScriptSyntaxHighlighter::_get_line_syntax_
> 
>                 if (!in_node_path && in_region == -1 && str[j] == '$') {
>                         in_node_path = true;
> -               } else if (in_region != -1 || (is_symbol && str[j] != '/')) {
> +               } else if (in_region != -1 || (is_symbol && str[j] != '/' && str[j] != '"' && str[j] != '\'')) {
>                         in_node_path = false;
>                 }
> ```
> 
> (The effect will be visible if you disable string highlighting in `script_text_editor.cpp`.)

Will that change colouring of just dollar NodePath or all NodePath (`get_node`, `find_node`) ?
I ask since i like consistency and want all my NodePath to have same colour.

TBH i'd prefer DollarWithoutQuotes syntax to have yellow coloured NodePath. I like all my string literals having same colour.

**Comment by Calinou** [comment]
@hilfazer A NodePath is a different type compared to a String, so I think it should be colored differently regardless of whether the name is quoted or not.

**Comment by hilfazer** [comment]
@Calinou i know NodePath is not String but it's also created from string literal. As you can see in `get_node()`/`find_node()` methods.

But all right, let's say i just want to have all of my NodePaths to have same colouring. Which means they should have same colour in $ syntax sugar as well as function calls and NodePath's constructor. It can be green, it's fine, i just want that consistency option.
