### ISSUE TITLE
Method not found: uint Godot.InputEventKey.get_Scancode()

### ISSUE THREAD

**Issue by uSources** [godotengine/godot#33310]
**Godot version:** 3.1.1 Mono version

**OS/device including version:** Windows 10 x64

**Issue description:** Method not found: uint Godot.InputEventKey.get_Scancode()

**Steps to reproduce:** 

> Trying to get an scancode of IputEvent in mono version throws next error Unhandled Exception:
> System.MissingMethodException: Method not found: uint Godot.InputEventKey.get_Scancode()

**Minimal reproduction project:**

**Comment by TheFlamyy** [comment]
I think you should be able to use `InputEventKey.Scancode` on its own as it's a variable.

Here's a snippet from the "source code":
```
/// <summary>
/// <para>Key scancode, one of the <see cref="T:Godot.KeyList" /> constants.</para>
/// </summary>
public uint Scancode {
	get;
	set;
}
```

It might be useful to add the C# equivalents in the documentation as currently only the GDScript properties/functions are visible

**Comment by KoBeWi** [comment]
Is this resolved or what?
