### ISSUE TITLE
Dragging a node into Script Editor always adds quotes to the path

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33317]
**Godot version:**
3.2 alpha3

**Issue description:**
When you drag and drop a node into Script Editor it automatically inserts the node path, but the path always contains quotes. I found myself always using this feature with $ operator, which doesn't need quotes, so they could probably appear only if necessary.

**Comment by Calinou** [comment]
So far, the rules for non-quoted `$` paths seem to be:

- No spaces or special characters (only A-Z, a-z, numbers and underscores).
- No `..` or absolute paths (`/root/…`).
- Each component of the path must not start with a number.

**Comment by KoBeWi** [comment]
Well, it already works for like this for path autocompletion, so this code could be reused probably.

**Comment by KoBeWi** [comment]
I just discovered that "Copy Path" button handles this correctly too. So only dropping needs a tweak.

**Comment by Eoin-ONeill-Yokai** [comment]
It's strange, but perhaps always having double quotes for drag-and-drop paths is actually the best design? 

I think that double quotes after a dollar sign will **always** work, which is actually the ideal situation for a casual user. If we were to have inconsistent behavior, it would mean that if the user changes their node hierarchy and has to update olds paths in their script, they might end up being confused if they've added an inappropriate character (space) to the tree and the compiler raises an error.

I have no strong feelings about it either way though, but from a UX perspective, it might make sense to always use double quotes for drag and drop node paths.
