### ISSUE TITLE
.gdignore file doesn't take effect until you reload the editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33314]
**Godot version:**
3.2 alpha3

**Issue description:**
\>title
(there's no other way to refresh it other than restarting AFAIK)

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by michael-conrad** [comment]
still an issue RC7 ?

**Comment by orion78fr** [comment]
Can confirm this still happens in 3.3.2, `.gdignore` was not taken into account until I reloaded the project
