### ISSUE TITLE
text_changed in LineEdit is emitted even if text doesn't change due to maximum length

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33318]
**Godot version:**
3.2 alpha3

**Steps to reproduce:**
1. Add LineEdit
2. Connect text_changed signal to a method that prints something
3. Add maximum length to the edit
4. Run the project and hold some letter key
5. The signal keeps being emitted

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/3802198/ReproductionProject.zip)

**Comment by akien-mga** [comment]
Started a discussion on #33417, but I'm not sure if it's a bug per se, or if fixing this bug would actually create a missing feature.

Currently you would be able to use the `text_changed` signal in such a situation to find out that the text input was actually discarded (you cache previous text, on text changed you check that the new text is still the same as old text). If we remove the signal, users attempting to input new characters in a full LineEdit will trigger no signal, so you can't handle it in a way that gives them relevant feedback.

**Comment by KoBeWi** [comment]
How about a new signal for text overflow?

**Comment by Paulb23** [comment]
Agreed, a new signal along the lines of `text_change_rejected` would be an ideal, rather then providing no feedback.
