### ISSUE TITLE
printerr from game looks like normal text

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33324]
**Godot version:**
3.2 alpha3

**Issue description:**
When you use `printerr` in a tool script, it will correctly show red errors in the console. However, this does not happen in game.

E.g. this script:
```
tool
extends Node2D

func _process(delta: float) -> void:
	printerr("I AM ERROR")
```
after running game produces this
![image](https://user-images.githubusercontent.com/2223172/68094052-d09fd600-fe9c-11e9-9a2b-2e41e2deba06.png)
(this is output both from game and editor)

**Comment by Calinou** [comment]
I think it's generally expected that `printerr()` doesn't apply any formatting to its own (`push_error()` can be used for formatted errors instead).

It makes sense to display the message in red in the output log, but the terminal output should stay unaffected.
