### ISSUE TITLE
Websockets doesn't connect

### ISSUE THREAD

**Issue by NovemberDev** [godotengine/godot#33329]
**Godot version:**
3.1.1 and latest 3.2 nightly 

**OS/device including version:**
Windows 10, reproducible on 4 PCs

**Issue description:**
When I write a simple websocket server and client, the client will not connect. Samples such as the Chat work fine.

**Steps to reproduce:**
Run the project and look at the debug output

**Minimal reproduction project:**
[Websockets.zip](https://github.com/godotengine/godot/files/3802944/Websockets.zip)

@Faless

**Comment by Faless** [comment]
You are connecting to the wrong signal.
If you use the high level multiplayer api you need to connect to `connection_succeeded` from [`NetworkedMultiplayerPeer`](http://docs.godotengine.org/en/3.1/classes/class_networkedmultiplayerpeer.html#class-networkedmultiplayerpeer).

**Comment by NovemberDev** [comment]
Thank you for the insight! It works now. For future googlers I'll leave this here:

>`get_tree().set_network_peer(WS)
   get_tree().network_peer.connect("connection_succeeded", self, "on_connection_established1")`
