### ISSUE TITLE
When you don't save unsaved scene on exit, it's not remembered

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33326]
**Godot version:**
3.2 alpha3

**Issue description:**
This is similar to #28263

**Steps to reproduce:**
1. Open multiple scenes
2. Edit one of them
3. Make sure "Restore Scenes on Load" in Editor Settings is enabled
4. Close the editor
5. The one edited scene will ask if you want to save
6. Don't
7. When you reload the project, the scene is not automatically opened

Works correctly if you choose save instead.

**Comment by Arunkumar1998BOM** [comment]
I dont understand one thing, Why would you want to remember a scene, if the user itself did not want to save it in the first place. 
In point 7, when you say "scene is not automatically opened", you mean the other un-edited scenes also do not open?

**Comment by KoBeWi** [comment]
I mean if you want scenes restored on load, it should apply to any opened scene tab, whether you save it when closing or not.

**Comment by Arunkumar1998BOM** [comment]
Okay, so irrespective of whether the scene is saved or not, the scenes must be restored if restored on load is set. I will look into this change and raise a PR

**Comment by Arunkumar1998BOM** [comment]
I tried reproducing the issue, 
1.) I created and save a new node "Node2D.tscn". Along with this, I have two other scenes. 
2.) I make changes to this scene "Node2D.tscn" 
3.) I press on exit editor and then i get prompted whether to save the scene before exit or not. I click on "dont save"
4.) When I open the same project again, the scene is also automatically opened and is under the File system dropdown at bottom left, under "res://"
5.) I observed the behavior also if you save while exiting, but the observed behavior is still the exact same. 
I think this issue is already fixed with the fixes for other issues.
Please correct me if my testing is inaccurate.

**Comment by KoBeWi** [comment]
Weird, because I can still reproduce it in 245c99175

**Comment by Arunkumar1998BOM** [comment]
![Screenshot from 2019-11-06 01-11-53](https://user-images.githubusercontent.com/51031229/68240248-8f412f00-0032-11ea-8dbb-c4e744e1daa7.png)

This is what I see, if I exit with saving or without saving the edited scene

**Comment by KoBeWi** [comment]
There might be misunderstanding here. I mean the scene tabs.
![image](https://user-images.githubusercontent.com/2223172/68240519-635f8280-000d-11ea-8ebc-f4600c6403fe.png)
Just open few of them and when you don't save one when exiting, it's not restored.

**Comment by Arunkumar1998BOM** [comment]
Hey @KoBeWi , I was able to reproduce the issue, but the scene tab does not open even if I click on "Save and Exit" option, prompted to me while trying to close the editor. But if I perform save operation, before I attempt to quit the editor, the scene remains. I understood the issue, Ill look through the codebase and see how I can push the fix. If there is an codebase reference I could use, that would be helpful.

**Comment by KoBeWi** [comment]
You might want to look what this PR did #28067

**Comment by Arunkumar1998BOM** [comment]
I tried putting these two APIs _save_default_environment and save_layout for the cases FILE_CLOSE and FILE_SAVE_SCENE cases for under the _menu_option_confirm function, but still I do not see the environment getting saved. Am I using the correct APIs or am I going wrong somewhere else
This is my first PR, so excuse me if my doubts are silly.

**Comment by KoBeWi** [comment]
`save_layout()` should be enough. Make sure the method is actually called. I also noticed that when you don't save the scene, the tab is closed, which might be the reason why it's not stored.

**Comment by Arunkumar1998BOM** [comment]
When I press on "Save&Close" when prompted when trying to exit the editor, still the scene is getting closed. I am sure the method save_layout() is begin called as I placed it right under "save_confirmation->set_text(vformat(TTR("Save changes to '%s' before closing?"), scene_filename != "" ? scene_filename : "unsaved scene"));". This line is executed for the case FILE_CLOSE. 

The same is for the case if I try to quit the editor without saving it. save_layout() gets executed, but layout is not getting saved

**Comment by Arunkumar1998BOM** [comment]
Otherwise if you can show me how to use the debugger, Ill figure out the process flow myself

**Comment by KoBeWi** [comment]
I never used a C++ debugger. I just put `print_line`s to check if something is executed or what value it has >_>

**Comment by themvl** [comment]
I tried with the print statements and as far as i can find the exact same code gets executed when you click save and when you click don't save with the mere exception of _save_scene_with_preview getting called when you click save.

**Comment by themvl** [comment]
This btw includes that when you save the tab also gets closed

**Comment by KoBeWi** [comment]
> This btw includes that when you save the tab also gets closed

Yeah, I noticed it recently and forgot to comment here. Seems like whole popup is the problem.

**Comment by themvl** [comment]
if this was the actual fix i was so damn close!
