### ISSUE TITLE
Hold multitouch on TouchScreenButton

### ISSUE THREAD

**Issue by ibenx** [godotengine/godot#33328]
**Godot version:**
3.1 - 3.2.dev.custom_build

**OS/device including version:**
Android 7 (nougat)

**Issue description:**
When i make 3 or more touch in same time (one button = one touch) and hold for 3 or more sec, all buttons is auto released even my fingers still touching the screen. It's not happen when i make 2 or less touch.

Issue gone when i make 1 touch (any position on screen) first (hold), after that holding 3 or more touch in same time is work.

**Steps to reproduce:**
1. Add 5 or more TouchScreenButton
2. Use different image on normal & pressed (to know when button is pressed or released)
3. Export to android
4. Make 3 or more touch (in same time) on different button (on finger one button)

**Comment by RandomShaper** [comment]
Which phone model is it exactly?

I have the suspicion that the three-finger gesture is being handled by the OS (for screen capture or something) and that is interfering somehow.

Just an idea.

**Comment by ibenx** [comment]
> Which phone model is it exactly?
> 
> I have the suspicion that the three-finger gesture is being handled by the OS (for screen capture or something) and that is interfering somehow.
> 
> Just an idea.

You right, i just test (disable 3 finger screenshot) and issue gone.. Thanks
I close this..
