### ISSUE TITLE
Overflowing maximum length of LineEdit in inspector clears the text

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33321]
**Godot version:**
3.2 alpha3

**Issue description:**
When you set maximum length for LineEdit and set the `text` property in the inspector to something longer, the text is clear completely instead of trimmed. It disappears from node, but remains in the inspector until you re-select the LineEdit.

**Comment by name-here** [comment]
So would correct behavior be to trim the text when you hit enter or something, or for it to just not let you type more than the maximum length into the property in the inspector?

**Comment by KoBeWi** [comment]
Trimming would be easier to do.

**Comment by akien-mga** [comment]
Reopening as #41520 was reverted.
