### ISSUE TITLE
SceneTreeTimer ignores SceneTree.paused state

### ISSUE THREAD

**Issue by benbishopnz** [godotengine/godot#33327]
**Godot version:**
3.1.1

**OS/device including version:**
MacOS 10.14.6 (Mohave)

**Issue description:**
The SceneTreeTimer continues to process even when the scene is paused (no matter what the pause_mode is set to.)

**Steps to reproduce:**
- Create a SceneTreeTimer using `get_tree().create_timer(5)`
- Pause the scene by setting `get_tree().paused = true`
- The SceneTreeTimer will continue to run and timeout.

**Minimal reproduction project:**
[createTimerExample.zip](https://github.com/godotengine/godot/files/3802466/createTimerExample.zip)

**Comment by KoBeWi** [comment]
SceneTreeTimers by default are set to process on pause. You can control this with the second argument of `create_timer`.

Likely related to #33102

**Comment by benbishopnz** [comment]
Oh, duh. Sorry, I was looking everywhere trying to find how to change a `pause_mode_process` variable under SceneTree or SceneTreeTimer but I missed the second argument there.
I will close this issue.
