### ISSUE TITLE
vulkan - 4.0 dev - GIProbe  Editor slows to a crawl when GIProbe is on and 

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#33334]
Windows 10 64 bits
Nvidia GTX 1060
Godot vulkan branch 20191104

Setting a GiProbe (baked 64subdiv, more crashes) with one Mesh with "use dynamic GI" enabled, the scene goes to a crawl 1FPS

steps:
.-create a scene 3D
.-add a GIProbe
.-set GIProbe subdiv to 64
.-bake GIProbe
.-add a Mesh, set it to anything (sphere)
.-move the Mesh o camera, it will move correctly
.-set the Mesh->Geometry->Use dynamic GI, the scene now moves at 1FPS

Log:

Godot Engine v4.0.devel.custom_build - https://godotengine.org
ERROR: VulkanContext::_debug_messenger_callback: WARNING : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 00000234F33D5BA0

   At: drivers\vulkan\vulkan_context.cpp:125
VK_KHR_incremental_present extension NOT AVAILABLE

VK_GOOGLE_display_timing extension NOT AVAILABLE

Vulkan physical device creation success o_O
uniform total: 0
uniform total: 0
uniform total: 0
compilation success

Editing project: C:/Users/Sistemas/Documents/Godot/projects/VK_prueba00 (C:::Users::Sistemas::Documents::Godot::projects::VK_prueba00)
Godot Engine v4.0.devel.custom_build - https://godotengine.org
ERROR: ShaderRD::~ShaderRD: 3 shaders of type SceneForwardShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type GiprobeDebugShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type GiprobeShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: RasterizerCanvasRD::~RasterizerCanvasRD: Some texture bindings were not properly freed (leaked canvasitems?
   At: servers\visual\rasterizer_rd\rasterizer_canvas_rd.cpp:2525
ERROR: ShaderRD::~ShaderRD: 1 shaders of type CopyShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type TonemapShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type SkyShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type CubemapRoughnessShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type GiprobeSdfShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: 3 RID allocations of type 'struct RasterizerStorageRD::Material' were leaked at exit.
ERROR: 3 RID allocations of type 'struct RasterizerStorageRD::Shader' were leaked at exit.
WARNING: RenderingDeviceVulkan::_free_rids: 2 RIDs of type 'StorageBuffer' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7231
WARNING: RenderingDeviceVulkan::_free_rids: 4 RIDs of type 'UniformBuffer' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7231
WARNING: RenderingDeviceVulkan::_free_rids: 2 RIDs of type 'Framebuffer' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7231
WARNING: RenderingDeviceVulkan::_free_rids: 1 RIDs of type 'Sampler' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7231
WARNING: RenderingDeviceVulkan::finalize: 2 RIDs of type 'Texture' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7374
ERROR: VulkanContext::_debug_messenger_callback: WARNING : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 00000245345575F0

   At: drivers\vulkan\vulkan_context.cpp:125
VK_KHR_incremental_present extension NOT AVAILABLE

VK_GOOGLE_display_timing extension NOT AVAILABLE

Vulkan physical device creation success o_O
uniform total: 0
uniform total: 0
uniform total: 0
compilation success

uniform total: 0
uniform total: 36
ERROR: In Object of type 'EditorNetworkProfiler': Attempt to connect nonexistent signal 'break_request' to method 'ScriptEditorDebugger._profiler_seeked'.
   At: core\object.cpp:1452
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
erasing C:\Users\Sistemas\AppData\Roaming/Godot/projects/VK_prueba00-884b35e7c7ed6aaf7c9353f2682e14bc/filesystem_update4
uniform total: 156
uniform total: 124
ERROR: RasterizerScene::InstanceBase::clean_up_dependencies: Condition ' !F ' is true. Continuing..:
   At: C:\Users\Sistemas\Documents\Godot\build\godot-vulkan\servers/visual/rasterizer.h:177
ERROR: RasterizerScene::InstanceBase::clean_up_dependencies: Condition ' !F ' is true. Continuing..:
   At: C:\Users\Sistemas\Documents\Godot\build\godot-vulkan\servers/visual/rasterizer.h:177
ERROR: RasterizerScene::InstanceBase::clean_up_dependencies: Condition ' !F ' is true. Continuing..:
   At: C:\Users\Sistemas\Documents\Godot\build\godot-vulkan\servers/visual/rasterizer.h:177
ERROR: RasterizerScene::InstanceBase::clean_up_dependencies: Condition ' !F ' is true. Continuing..:
   At: C:\Users\Sistemas\Documents\Godot\build\godot-vulkan\servers/visual/rasterizer.h:177

**Comment by rubenjavier** [comment]
Forgot to add
Intel i7 8750H 16G RAM
so I dont think is a CPU o RAM deficit issue

**Comment by rubenjavier** [comment]
Solved!
removed the vulkan version apparently installed by the graphics driver, 1.0.3, restarted and installed the most recent vulkan rt version 1.1.121 from 
https://vulkan.lunarg.com/sdk/home

**Comment by akien-mga** [comment]
Thanks, closing then. Things are still very WIP but yes, we're probably going to add vefrsion checks to ensure that Vulkan 1.1 and some common extensions are present.

**Comment by rubenjavier** [comment]
https://github.com/godotengine/godot/issues/33381#issuecomment-550264129

@akien-mga Found the reason for very slow performance, is on the issue on the link above

If GIProbe and a MeshInstance with "Use In Baked Light" are not childs of the same parent-node, then the baking can crash or take a lot of time, and adding another MeshInstance with "Use Dynamic GI" enabled will make the editor and the scene crawl...

a project and instaructions are attached on the link to the issue above
