### ISSUE TITLE
An option to remember project specific ui settings like opened scenes, resource browser last folder/settings etc

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3333]
I make a project. Work on a scene. I quit and restart Godot no scene is opened. It does not remember the last opened scene(s) and I have to manually open every single scene I was working on every time I open Godot.. 

I browse a certain folder in my resource browser and set the view to list small icons. Every time I restart the browser the resource browser current folder is reset to root and the view settings back to default. It does not remember last settings and folder opened.

Any scripts or resources I had open before closing Godot are not automatically reopened. I have to do it manually every time.

**Comment by KoBeWi** [comment]
Scenes/scripts are already remembered, folders are somewhat irrelevant with new filesystem doc.

**Comment by Calinou** [comment]
@KoBeWi Scene tabs are currently only restored if **Interface → Scene Tabs → Restore Scenes on Load** is enabled in the Editor Settings. Personally, I'd like to see this enabled by default.

**Comment by KoBeWi** [comment]
I know it is disabled by default and there's even an issue related to that: #16317

**Comment by akien-mga** [comment]
Closing as solved then, further discussion on Restore Scenes on Load can happen in the dedicated issue.
