### ISSUE TITLE
GDScript EditorExportPlugin not working and missing from C#

### ISSUE THREAD

**Issue by WizzardMaker** [godotengine/godot#33344]
**Godot version:** 3.1.1 Mono

**OS/device including version:** Windows 10

**Issue description:**
The EditorExportPlugin does not call the _export_begin or _export_end functions.
EditorExportPlugin is also not in the Godot C# assembly.

**Steps to reproduce:**
1. Create simple EditorExportPlugin script
```
tool
extends EditorExportPlugin

func _export_begin(features, is_debug, path, flags):	
	print(flags)
	print("Hello!")
```
2. Create a simple Windows Desktop executable export template
3. Export Project
4. Expected output of at least "Hello", but there is no output.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/3804933/Test.zip)

**Comment by Zylann** [comment]
I think export plugins are supposed to be added through an editor plugin, using this function http://docs.godotengine.org/en/3.0/classes/class_editorplugin.html#class-editorplugin-add-export-plugin

**Comment by WizzardMaker** [comment]
How do you use this function? Plugins are so ominous to me.

**Comment by WizzardMaker** [comment]
Ok, I think I know the answer to both questions. You are right @Zylann you need to add it with a plugin for it to work.

The class is not really missing, but because I use Visual Studio Code, it wont show up in InteliSense, because it does not know, that we are working on a tool script, when inside the addons folder. thats why VS doesn't add the Editor assembly.

**Comment by WizzardMaker** [comment]
I am experiencing a different issue here. Gonna close this and create a more fitting issue for the new problem
