### ISSUE TITLE
C# EditorExportPlugin is missing the _ExportEnd method

### ISSUE THREAD

**Issue by WizzardMaker** [godotengine/godot#33349]
**Godot version:** 3.1.1 Mono

**OS/device including version:** Windows 10

**Issue description:**
The `EditorExportPlugin` is missing the method `_ExportEnd()`

**Steps to reproduce:**
Create a C# `EditorExportPlugin` script and add an overload for `_ExportEnd()`. The build will fail, because the method is not defined

**Comment by neikeq** [comment]
CC @akien-mga 
The fix would be to cherry-pick aebca30c43708a2ee6a1abc4d869eda88a3c27bb

**Comment by akien-mga** [comment]
Which I did 4 hours ago :P
https://github.com/godotengine/godot/pull/29139#issuecomment-552838361

**Comment by neikeq** [comment]
Wow, that was fast. If that's even the correct way to describe it. This is some real time travel sh!t right here.
