### ISSUE TITLE
option to customize Godot Engine UI skin color / warmth / saturation / hue

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3335]
There are options to change colors for many features in the engine from text editor to bg clear color but nothing for the UI skin itself.

**Comment by Zephilinox** [comment]
This can be closed now right?

**Comment by bojidar-bg** [comment]
Seems implemented in the new 3.0 GUI indeed.

**Comment by Zephilinox** [comment]
@bojidar-bg would it be worthwhile if I had a look through other issues and pointed out any worth closing?

**Comment by bojidar-bg** [comment]
@Zephilinox Well, yes, feel free to do so 😃
