### ISSUE TITLE
Request: Revert automatically "playing" animations when selected

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#33353]
**Godot version:**
3.2.alpha.official

**OS/device including version:**
Solus 4 Gnome 3.34.1

**Issue description:**
PReviously on 3.1.1 when we change an animation in the editor the values from its keys weren't applied until we scroll (scrub?) the animation's cursor on the timeline, this was a very forgiving feature because it prevented the scene to take changes unless we wanted to.

Some animations work with values with the assumption that the default is different from the key's value. What I mean by that:

I have a ProgressBar, which by default should be hidden unless the animation that shows it starts playing. Currently, every time said animation is *just* selected the ProgressBar is made visible and I have to hide it again manually

This can cause some bugs, for instance, I have some nodes that have an `active` property, which by no means should be changed unless the time is right, which is when their animation is called. With the current way, they are made active when their animation is *selected*, note: just selected, not played. I had 3 bugs fixed in this regard and I can expect to have more.

**Steps to reproduce:**
1. Create a scene with some Node2Ds
2. Set some default values, for instance modulation, os visibility. These are the ideal "initial state" of your scene
3. Create some animations that play with these properties
4. Select (don't play) these animations

**Comment by KoBeWi** [comment]
Tbh, this was always a problem with animations, see #812
The proper fix would be preventing animations from breaking your scenes.

**Comment by henriiquecampos** [comment]
Yeah, exactly, #214 offers a good solution indeed. Have a mode where animations don't actually affect the scene.

**Comment by henriiquecampos** [comment]
This is fixed with the release of 3.2
