### ISSUE TITLE
vulkan - 4.0 dev - incorrect texture format (with potential solution)

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#33358]
I've been testing my game on the Vulkan branch and found a bug.

I am trying to create a texture with the format FORMAT_RGBH.

RasterizerStorageRD::texture_2d_create is being called which calls _validate_texture_format
it correctly hits this case statement:

```
case Image::FORMAT_RGBH: {
			//this format is not mandatory for specification, check if supported first
			if (RD::get_singleton()->texture_is_format_supported_for_usage(RD::DATA_FORMAT_R16G16B16_SFLOAT, RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_UPDATE_BIT)) {
				r_format.format = RD::DATA_FORMAT_R16G16B16_SFLOAT;
			} else {
				//not supported, reconvert
				r_format.format = RD::DATA_FORMAT_R16G16B16A16_SFLOAT;
				image->convert(Image::FORMAT_RGBAH);
			}

			r_format.format = RD::DATA_FORMAT_R16G16B16A16_SFLOAT;
			r_format.swizzle_r = RD::TEXTURE_SWIZZLE_R;
			r_format.swizzle_g = RD::TEXTURE_SWIZZLE_G;
			r_format.swizzle_b = RD::TEXTURE_SWIZZLE_B;
			r_format.swizzle_a = RD::TEXTURE_SWIZZLE_ONE;
		} break;
```

the first if statement here is true, so format becomes:
`r_format.format = RD::DATA_FORMAT_R16G16B16_SFLOAT;`
which looks correct

but as soon as it leaves the if statement it hits this line:
`r_format.format = RD::DATA_FORMAT_R16G16B16A16_SFLOAT;`
which looks incorrect! 
Removing this line fixes the problem.

as a result this causes the error to occur:
ERR_EXPLAIN("Data for slice index " + itos(i) + " (mapped to layer " + itos(i) + ") differs in size (supplied: " + itos(p_data[i].size()) + ") than what is required by the format (" + itos(required_size) + ").");

**Comment by KoBeWi** [comment]
Seems fixed in 6c173e2?
