### ISSUE TITLE
Container nodes don't refresh when contents change

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3336]
The hassles of scene refresh.

When manipulating scene components they don't refresh automatically in the editor. Only when running the app , changing the container of the elements you modify or switching to another scene and back the editor refreshes the scene components.

Example 1  

I move a button in the scene. Note that it should be automatically ordered and centered based on the CenterContainer VBox Container but scene does not refresh automatically.  

![screen shot 2016-01-13 at 6 22 23 am](https://cloud.githubusercontent.com/assets/6987027/12292897/18713398-b9be-11e5-8f21-030095b43343.png)

Instead I have to make the container bigger than back to small to refresh.
![screen shot 2016-01-13 at 6 21 17 am](https://cloud.githubusercontent.com/assets/6987027/12292900/197f2bbe-b9be-11e5-9b34-498a8d66de6e.png)

Example 2
Switching to another scene and back to the scene you are working on refreshes the scene.

![screen shot 2016-01-13 at 6 26 07 am](https://cloud.githubusercontent.com/assets/6987027/12293012/b5039cc8-b9be-11e5-8d08-68c78a6c4e98.png)

![screen shot 2016-01-13 at 6 26 17 am](https://cloud.githubusercontent.com/assets/6987027/12293018/b8e57000-b9be-11e5-8a0c-4a9ac9e4f8a0.png)

![screen shot 2016-01-13 at 6 26 19 am](https://cloud.githubusercontent.com/assets/6987027/12293020/bce63a0e-b9be-11e5-87b5-67740e46e6df.png)

I simply ask for a button or shortcut that refreshes the scene manually AND/OR every time you save a scene it's automatically refreshed.

**Comment by kubecz3k** [comment]
It looks like https://github.com/godotengine/godot/issues/3201 duplicate. Also from the screens you are using old godot version, compile new one the issue is already partially addressed.

**Comment by akien-mga** [comment]
Not sure that it's a #3201 duplicate as there are no subscenes involved. On the other it looks more like a Button node bug than a general "refreshing" issue that would require a workaround. We just need to ensure that Button position is changed when alignment is modified in the Inspector.

**Comment by bojidar-bg** [comment]
@akien-mga To me it looks like a container issue, and not a button one xD

**Comment by akien-mga** [comment]
Yeah probably :)

**Comment by trollworkout** [comment]
@akien-mga  @kubecz3k  @bojidar-bg  I am on OSX El Capitan now. If you need any further testing please let me know I will help with what I can.

**Comment by bojidar-bg** [comment]
@trollworkout ~ I guess you wanted to comment on the other issue, as this one can be reproduced with ease on any platform :wink:

**Comment by trollworkout** [comment]
@bojidar-bg  maybe i should change title to something more relevant . yes i wanted to comment on the other one heh

**Comment by bojidar-bg** [comment]
@trollworkout I propose "Container nodes don't refresh when contents change".

(Also, you can delete your last comment, after which I will delete mine)

**Comment by DualMatrix** [comment]
Still relevant in master

**Comment by KoBeWi** [comment]
The Containers seem to refresh now when you modify nodes, however you can break the preview when you move something (it is possible by manually editing properties in the inspector, as otherwise movement in Containers is now locked). "Broken" Container returns to normal when following steps from the OP.

Somewhat related to #26403

**Comment by akien-mga** [comment]
CC @groud

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in [Godot 3.4](https://godotengine.org/article/godot-3-4-is-released) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment]
As per my previous comment, all containers should now refresh properly. Also now in 4.0 it's pretty impossible to break the layout, because you can't move nodes inside container in any way, so the issue can be considered resolved.

I did recently encounter a bug in 3.x where sometimes the nodes in container aren't properly laid out, but I don't have any concrete reproduction steps. I'll open a new issue if it happens again.
