### ISSUE TITLE
TextEdit.center_viewport_to_cursor doesn't work after a search, unless waiting a frame before calling it

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#33375]
Godot 3.2 alpha3

I want to trigger a `search` in a `TextEdit` and select occurences with the cursor. This has the effect of pushing the cursor to the very last visible line on each occurrence, which is impractical. I initially wanted to scroll it down to give a few lines of context, but there is no function to scroll. So I figured I would call `center_viewport_to_cursor` so that the cursor is centered, but that didn't work. Instead, the cursor would be seen at random heights and rarely centered.
Then I found that if I add a wait for `idle_frame` before the call, it works...

```gdscript
	var res = _text_edit.search(text, flags, search_line, search_col)
	
	if len(res) == 0:
		_label.text = "No results"
		
	else:
		_result_col = res[0]
		_result_line = res[1]
		_text_edit.cursor_set_line(_result_line)
		_text_edit.cursor_set_column(_result_col)
		_text_edit.select(_result_line, _result_col, _result_line, _result_col + len(text))

	# Had to add this
	yield(get_tree(), "idle_frame")
	_text_edit.center_viewport_to_cursor()
```

`center_viewport_to_cursor` is not documented. It's quite impractal having to do this systematically, is it a bug?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Zylann** [comment]
I tried to reproduce it again in 3.2 alpha3, and for some reason I could not. I clearly remember it happening, but there might be more conditions at play here. Of course I could not reproduce in 3.2.3 either.

**Comment by KoBeWi** [comment]
Closing then.
