### ISSUE TITLE
[Windows 10] OS.shell_open uses cmd.exe to open file:// protocol

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#33388]
**Godot version:**
3.x

**OS/device including version:**
Windows 10 x64

**Issue description:**
OS.shell_open launches cmd.exe to open a folder path using the file:// protocol instead of explorer.exe.

I tested other ways of using that protocol:
- Windows "Run" dialog
![image](https://user-images.githubusercontent.com/10672233/68297268-6c446880-008e-11ea-8ffa-22f11fb7fc49.png)

- start.exe via Command Prompt
![image](https://user-images.githubusercontent.com/10672233/68297365-a7469c00-008e-11ea-9c92-2f9ac133b08a.png)

- VBscript
```vba
Set objShell = CreateObject("Shell.Application")
objShell.ShellExecute "file://C:/Users", "", "", "", 1
```
- C#, from the Mono version of Godot
```csharp
using System.Diagnostics;
(...)
    Process p = new Process();
    p.StartInfo.FileName = "file://C:/Users";
    p.Start();
(...)
```

And they all worked as expected, launching explorer.exe.
So this seems to be something weird with Godot.

**Steps to reproduce:**
Open a project and right-click a file or folder in the FileSystem dock, then select "Show in File Manager".
Alternatively, run a script with something like OS.shell_open("file://C:/Users")

**Minimal reproduction project:**
\-

**Comment by akien-mga** [comment]
For the reference, I also tried this on Linux (Mageia 7 x86_64) and Windows 10 and could not reproduce the issue.

So it seems to be system-specific, but it would be good to figure out what exactly triggers this wrong behavior of `ShellExecuteW` interpreting `file://` paths as a request to open `cmd.exe` instead of `explorer.exe`.

**Comment by bojidar-bg** [comment]
Does the C# example still work if you use `p.StartInfo.UseShellExecute = true`?

**Comment by piratesephiroth** [comment]
> 
> 
> Does the C# example still work if you use `p.StartInfo.UseShellExecute = true?

yeah, it's set to true by default. If I set it to false it just errors out, not being able to open the path.

**Comment by piratesephiroth** [comment]
> 
> 
> For the reference, I also tried this on Linux (Mageia 7 x86_64) and Windows 10 and could not reproduce the issue.
> 
> So it seems to be system-specific, but it would be good to figure out what exactly triggers this wrong behavior of `ShellExecuteW` interpreting `file://` paths as a request to open `cmd.exe` instead of `explorer.exe`.
Yeah, I made a quick C++ test in Visual Studio and got the same wrong result with the "open" operation.

But then... I'm not sure if it's a valid solution but it works as expected if I just pass NULL as verb.

```cpp
#include <iostream>
#include <shlwapi.h>
#include <objbase.h>

int main()
{
    std::cout << "Hello World!\n";
	ShellExecuteW(NULL, NULL, L"file://C:/Users", NULL, NULL, SW_SHOWNORMAL);
}
```
Boom, the path was opened in File Explorer.
