### ISSUE TITLE
vulkan - 4.0 dev - Instance mesh colours not working (with a fix for the bug)

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#33383]
In Vulkan branch, I'm testing instances with custom colours.
it bails because it hits an error in:
RasterizerStorageRD::multimesh_instance_set_color

The line:
ERR_FAIL_INDEX(p_index, !multimesh->uses_colors);

needs to change to:
ERR_FAIL_COND(!multimesh->uses_colors);

and this fixes the problem. This occured as the multimesh used to take a count of the colours to allocate and has now been changed to just be a bool. It looks like this error condition was not correctly fixed.

**Comment by akien-mga** [comment]
Fixed by #34487.
