### ISSUE TITLE
"draw_line" snaps positions to integer

### ISSUE THREAD

**Issue by TheFlamyy** [godotengine/godot#33393]
**Godot version:** 
3.2.beta1

**OS/device including version:** 
Ubuntu

**Issue description:**
When calling `draw_line()` inside the `CanvasItem` it seems like the values are snapped to the next integer. The effect becomes very apparent when you use a `Control` with a `rect_scale`.
It's a regression from the previous version.
3.2.alpha3
![Screenshot from 2019-11-06 16-29-59](https://user-images.githubusercontent.com/8056898/68312429-55fcd380-00b3-11ea-9ecc-4f739ec3daa4.png)

3.2.beta1
![Screenshot from 2019-11-06 16-29-30](https://user-images.githubusercontent.com/8056898/68312448-5bf2b480-00b3-11ea-9641-e76f8dd7f4e0.png)

My example uses a `Control` node with `rect_scale` set to `(4, 4)`, this is probably the reason why each "angled" line is 4 pixels tall.

**Steps to reproduce:**
- Create a `Control` node.
- Set it's `rect_scale` to something bigger.
- Call `draw_line()` inside of `_draw()` with floating point numbers.

**Comment by akien-mga** [comment]
Probably a consequence of #32657, CC @ptrojahn.
