### ISSUE TITLE
min()/max() numerically incorrect

### ISSUE THREAD

**Issue by Kobrar** [godotengine/godot#33394]
**Godot version:** 3.1.1

**OS/device including version:** Windows 7

**Issue description:** According to min(), smaller of two numbers doesn't have to be one of those numbers

**Steps to reproduce:** Run the following function:

    func stuff():
	var nums = []
	for i in range(999):
		nums.append(randf() * 99999.0 + 999.0)
	
	var min_min = 999999.0
	var max_max = 0.0
	var min_if = 999999.0
	var max_if = 0.0
	
	for num in nums:
		min_min = min(min_min, num)
		max_max = max(max_max, num)
		
		if num < min_if:
			min_if = num
		if num > max_if:
			max_if = num
	
	var min_found = false
	var if_found = false
	
	for num in nums:
		min_found = min_found or (num == min_min)
		if_found = if_found or (num == min_if)
	
	print("min() found!" if min_found else "min() not found!")
	print("if found!" if if_found else "if not found!")

Ideally you should be able to assume that the smaller of two numbers is one of those numbers and that your number generally don't change unless you do some math on them.

**Comment by Calinou** [comment]
This sounds like a floating-point precision issue to me. To compare floating-point values, you should generally use `is_equal_approx()` instead of the `==` operator.

**Comment by Chaosus** [comment]
I've checked this code and found that it's definitely a floating-point precision issue as mentioned in a comment above.
is_equal_approx does not exist on 3.1.1 but exists on 3.2. Either use this snippet "abs(a - b) < 0.0001" to simulate its behavior or wait for 3.2. (num == min_min) should be changed to is_equal_approx(num, min_min) in your case. Closed.
