### ISSUE TITLE
Saving a script during debugging causes 2D editor to steal focus

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#33409]
Godot 3.2 alpha1, beta1
Godot 3.2.2 rc1

When I test my game (or debug), it happens that I leave the game running while I do some corrections to my code, and doing so I sometimes press Ctrl+S, which in my shortcut settings saves the current script.
However, when I do, Godot switches to the 2D editor. It does that also if I use the File->Save menu.

It doesn't always happen, but when following the same steps in my project it happens everytime. I'm not sure which specific step causes it.

My project has a main scene with instances of other scenes in it. What I do:
- Have main scene open
- Start debugging session
- In the main scene, click on an instance icon to open its scene (that one might be optional but I'm not sure)
- Click on a node from the scene tree
- Switch to the Script editor
- Write something
- Save script: boom, editor switches to 2D editor.

**Comment by NumberSixOx** [comment]
Affects 3.2 final also. 
Since my automatic muscle memory ctrl-S hand saves every 30 seconds this makes Godot 3.2 almost unusable for me.

**Comment by SleepProgger** [comment]
Just another +1. Its super annoying.
Only happens when a node is selected in the scene AND currently running debug (Thx Zylan i didn't realized before that it  only occurs when running debug).

**Comment by jh62** [comment]
Keeps happening...

**Comment by nathanfranke** [comment]
By the way, I think the way to reproduce this is to have a _process method on the selected node. Still not 100% sure since the bug was in a really different place.

**Comment by djrain** [comment]
What exactly is meant by "debug mode" here? I've unchecked everything under "Debug" menu, but this still happens to me on play, depending on the node selected, and without making any changes or manually saving.

**Comment by Zylann** [comment]
> Start debugging session

Means you click the "Play" button of the editor
