### ISSUE TITLE
Audio panel breaks UI

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#33407]
**Godot version:**
Godot 3.2.beta1

**OS/device including version:**
Linux - KDENeon

**Issue description:**

Open the audio panel. I'm not sure if this will happen on other systems.

Below is a video.

**Steps to reproduce:**

[Video](https://youtu.be/x9h5jlLobB8)

**Comment by KoBeWi** [comment]
Duplicate of #26835
