### ISSUE TITLE
android build template fails

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#33405]
**Godot version:** 3.2.beta

**OS/device including version:** linux 4.19.69-1-MANJARO

**Issue description:**
gradlew fails:

$ ./gradlew generateGodotTemplates
> Task :Godot:lib:preBuild UP-TO-DATE
> Task :Godot:lib:preReleaseBuild UP-TO-DATE
> Task :Godot:lib:compileReleaseAidl UP-TO-DATE
> Task :Godot:lib:compileReleaseRenderscript NO-SOURCE
> Task :Godot:lib:checkReleaseManifest UP-TO-DATE
> Task :Godot:lib:generateReleaseBuildConfig UP-TO-DATE
> Task :Godot:lib:generateReleaseResValues UP-TO-DATE
> Task :Godot:lib:generateReleaseResources UP-TO-DATE
> Task :Godot:lib:packageReleaseResources UP-TO-DATE
> Task :Godot:lib:processReleaseManifest UP-TO-DATE
> Task :Godot:lib:generateReleaseRFile FAILED
> Task :generateGodotTemplates FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Godot:lib:generateReleaseRFile'.
> Failed file name validation for file /home/dario/godot/sources/godot/platform/android/java/lib/build/intermediates/packaged_res/release/drawable-hdpi-v4/notify_panel_notification_icon_bg.png.import

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
1 actionable task: 1 executed

**Steps to reproduce:**
scons platform=android target=release_debug android_arch=armv7
scons platform=android target=release_debug android_arch=arm64v8
./gradlew generateGodotTemplates

**Comment by Calinou** [comment]
It seems like you placed the Godot source directory in a project, which causes `.import` files to be created for all icons contained in the source directory (as Godot is importing them into your project).

You can solve this by creating a file called `.gdignore` at the root of the Godot source directory. There was a [pull request](https://github.com/godotengine/godot/pull/28343) for this, but it wasn't merged.

**Comment by GrandFunkR** [comment]
ty
