### ISSUE TITLE
KinematicBody2D get_slide_count() cannot detect multiple collisions

### ISSUE THREAD

**Issue by Langrisser001** [godotengine/godot#33415]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 Pro

**Issue description:**
KinematicBody2D get_slide_count() only return 1 collision

**Steps to reproduce:**
1. Create three or more KinematicBody2D
2. move_and_slide() them so they collide with each other(in my case, 1 kinematic goes from left to right, and the other 2 goes from right to left)

**Minimal reproduction project:**
[TEST_Collision.zip](https://github.com/godotengine/godot/files/3817671/TEST_Collision.zip)

**Comment by capnm** [comment]
int get_slide_count() const

Returns the number of times the body **collided and changed direction** during the last call to move_and_slide().

![Screenshot from 2019-11-08 22-43-17](https://user-images.githubusercontent.com/4047289/68512644-44652880-0279-11ea-886a-0a6128f6cc41.png)

**Comment by Langrisser001** [comment]
My mistakes,
I thought get_slide_count() is the function to get all the colliding object, but it turns out if it didn't change directions the count won't increase.
Thanks "capnm" for pointing this.
