### ISSUE TITLE
Export may not work message(ignore,abort), if old export template

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3341]
Is it possible to show a info message that the export template is not up to date when you try to export?
I get an error when I start the game.
I want this information on export time not on game start time..

ERROR: Bytecode is too New! Please use a newer engine version.
   At: modules/gdscript/gd_tokenizer.cpp:1061
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:128

**Comment by eska014** [comment]
People often have issues with incompatible editor and templates, so +1 from me

**Comment by akien-mga** [comment]
Looks like I made a duplicate of this issue as I couldn't find this one (#6086). I'll close this one as a duplicate of mine as I started writing possibilities of implementation, but in my heart I'll always remember you as the one who helped bring this feature to Godot :D
