### ISSUE TITLE
Console window on C# project

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#33410]
Hi,

I'm trying to create  a Godot game that has the main game window, but also the actual console window (native console). This is for accessibility purposes - blind players can use the console window naturally with a screen reader to hear descriptions of the game and type in commands.

I seem to always explain this poorly, so here's a simple video of what it looks like: https://twitter.com/nightblade99/status/1191919468882145280/video/1

I wrote this project in MonoGame, and simply edited the `csproj` of the default project to be a console project. I tried the same thing with Godot, but evidently it uses the compiled library, so it won't work.

Is there any way to create something like this in Godot? I'm looking for a Windows (ideally, desktop) C# project with a native (not emulated) console.

**Comment by KoBeWi** [comment]
Godot in debug mode (non-release) is a console application by default. Is it different with Mono?

**Comment by nightblade9** [comment]
> Godot in debug mode (non-release) is a console application by default. Is it different with Mono?

I don't know. The built-in console outputs a fair amount of debug information, warnings, etc. so it's not suitable for use by players who use a screen-reader. I also can't write `Console.ReadLine` or something similar and get the input back, so I can't use it as an input device.

Or did I misunderstand what you mean?

**Comment by KoBeWi** [comment]
Hmmm, I don't think it's possible to have, like, _another_ console. The console you see in Godot IS the native console, so it's impossible to use it in another way.

But if it's for accessibility purposes, you might be interested in this #14011

**Comment by nightblade9** [comment]
I suspected as much.

Thanks for the feedback. I'll look into the screen reader issue you mentioned.
