### ISSUE TITLE
keyword "as" does not work in export release mode for custom classes

### ISSUE THREAD

**Issue by salvob41** [godotengine/godot#33418]
**Godot version:**
Godot3.1+ tested also with Godot3.2 beta1

**OS/device including version:**
All

**Issue description:**
If you define a custom class with 
`class_name NewClass`

and you use the keyword `as` if one of your script to access to method and var of those classes ... something like

`object_var as NewClass`

this won't work in a release export build

**Steps to reproduce:**

make a custom class
use the `as` keyword in another script

**Minimal reproduction project:**
I attached a small example.
[issue33418.zip](https://github.com/godotengine/godot/files/3818846/issue33418.zip)

**Comment by Xrayez** [comment]
Similar #28680.

**Comment by akien-mga** [comment]
Seems like duplicate of #28680 indeed.
