### ISSUE TITLE
Manage Editor Features does not removes nodes from Recent list

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#33420]
**Godot version:**
3.2 beta
**OS/device including version:**
Windows 7
**Issue description:**
I have disabled 3D editor features and Spatial nodes.
![image](https://user-images.githubusercontent.com/47214394/68382265-5e1f4680-0179-11ea-9e5d-410a23a84713.png)
![image](https://user-images.githubusercontent.com/47214394/68382284-67a8ae80-0179-11ea-9295-4cbf58b0adb8.png)

But Spatial nodes are still present in recent list
![image](https://user-images.githubusercontent.com/47214394/68382305-72634380-0179-11ea-893d-bcec5bfe578d.png)

**Steps to reproduce:**
1.Disable Spatial nodes
2. See Recent in new node dialog
**Minimal reproduction project:**

**Comment by veryprofessionaldodo** [comment]
I can't promise anything, but I'll try it :) I miss contributing to open-source, so I'm gonna check it out

**Comment by veryprofessionaldodo** [comment]
Aw, darn it. I forgot to check whether it was already fixed. Sorry guys!

**Comment by akien-mga** [comment]
Ah too late.. I missed that there was already a pending PR for that indeed.

**Comment by veryprofessionaldodo** [comment]
I'll pay more attention to it next time, but thanks for the merge! @akien-mga
