### ISSUE TITLE
v3.2.beta1: Tileset Editor snap grid lines are 0.5 pixels off

### ISSUE THREAD

**Issue by themangomago** [godotengine/godot#33421]
**Godot version:**
v3.2.beta1 (not in alpha 3)

**OS/device including version:**
win10 64 latest

**Issue description:**
In the tileset editor the snapping grid lines are off by 0.5 pixels. see screenshot:
![image](https://user-images.githubusercontent.com/29095714/68386133-ae87ab80-015b-11ea-8334-87678e3568ff.png)
Same project in 3.2 alpha 3 is on point but the beta 1 is off.

Might also be related to:
https://github.com/godotengine/godot/issues/33393

**Steps to reproduce:**
Create a tilemap, set snapping options.

**Minimal reproduction project:**
2ez ;)

**Comment by akien-mga** [comment]
Probably a consequence of #32657, CC @ptrojahn.
