### ISSUE TITLE
BaseButton toggle mode behavior changed, should be documented

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#33422]
**Godot version: 3.2.beta**

**OS/device including version: All**

**Issue description:** Before when I set **pressed=True** button just change self visual state without a call  "_toggled". After commit 2cedf7173a104a1b17af38b9c663a339c5fa664d this state call "_toggled" method always and I can't change visual state of my buttons and can't handle real click and click from code. All my code based on toggled callback with change visual state through "pressed" is broken now..

**Steps to reproduce:** 
1. add any button with toggle mode
2. handle "toggled" event to callback
3. try to change VISUAL state of the button "btn.pressed = true/false" without call a "toggled" callback

**Minimal reproduction project:**

**Comment by ealataur** [comment]
temporary returned all code from files base_button.cpp and base_button.h from stable 3.1 and my code is working fine..

In my project switch buttons can change self visual state from outside signals (over BLE) but when I  real click this button code must send a BLE command to channel. And now when outside event change the state over pressed property my toggled callback is called too and I have a recursion loop

**Comment by volzhs** [comment]
it was changed that way to propagate `toggled` event when `pressed` state changed visually.
without it, you never get any event by changing its state by code.
use `pressed` event for the real click.

```gdscript
func _ready():
	$Button.connect("pressed", self, "on_pressed")
	$Button.connect("toggled", self, "on_toggled")

func on_pressed():
	prints("pressed", $Button.pressed)

func on_toggled(p_state):
	prints("toggled", p_state)
```

the `pressed` event is fired after `toggled` and only with actual click.

**Comment by volzhs** [comment]
can you share a minimal project to show your problem?

**Comment by charliewhitfield** [comment]
This change breaks existing code. For example, if one has a "three-state" system coded:
```
enum {STATE1, STATE2, STATE3}

func _ready() -> void:
	$Button1.connect("toggled", self, "_change_state", [STATE1])
	$Button2.connect("toggled", self, "_change_state", [STATE2])
	$Button3.connect("toggled", self, "_change_state", [STATE3])
	SomeOtherNode.connect("state_changed", self, "_update_state_buttons")

func _change_state(button_pressed: bool, new_state: bool) -> void:
	# Order the state to change

func _update_state_buttons(new_state: bool) -> void:
	$Button1.pressed = (new_state == STATE1)
	$Button2.pressed = (new_state == STATE2)
	$Button3.pressed = (new_state == STATE3)
```
...then the change results in an infinite loop.

Of course, I can change all of my "toggled" signal connections to "pressed". I don't mind doing this if there is good motivation for this breaking change...

**Comment by akien-mga** [comment]
> Of course, I can change all of my "toggled" button connections to "pressed". I don't mind doing this if there is good motivation for this breaking change...

There's one in the issues fixed by #29717: #18715 and #29604.

**Comment by volzhs** [comment]
it was changed in a current way because you can't get a `toggled` signal when you changed `Button` pressed state by code, even it's really toggled in view.

```gdscript
extends Control

enum {STATE1, STATE2, STATE3}

func _ready():
	var group = ButtonGroup.new()
	$Button1.group = group
	$Button2.group = group
	$Button3.group = group
	
	$Button1.connect("toggled", self, "_change_state", [STATE1])
	$Button2.connect("toggled", self, "_change_state", [STATE2])
	$Button3.connect("toggled", self, "_change_state", [STATE3])
	
	$Button_test.connect("pressed", self, "_update_state_buttons", [STATE1])

func _change_state(button_pressed, new_state):
	# Order the state to change
	printt("_change_state", button_pressed, new_state)
	pass

func _update_state_buttons(new_state):
	$Button1.pressed = (new_state == STATE1)
	$Button2.pressed = (new_state == STATE2)
	$Button3.pressed = (new_state == STATE3)
```

or just change `toggled` to `pressed`

**Comment by charliewhitfield** [comment]
Sounds fine to me. I'll update my button code for 3.2.

**Comment by KoBeWi** [comment]
So basically this can be closed? Seems like the problem can be solved by a ButtonGroup instead of managing the buttons manually.

**Comment by YeldhamDev** [comment]
Maybe the new behaviour should be documented?

**Comment by KoBeWi** [comment]
Soo I actually encountered an issue with this behavior recently. I have a custom editor with checkboxes for certain properties and the checkboxes have their toggled signal connected to a script. Buut when I load the edited object, these checkboxes get pressed or released based on the values in the object. Which triggers the signal and I don't want it during initialization. My workaround is doing
```
toggling = true
container.simulated.pressed = simulated
toggling = false
```
And then `return`ing in the connected method if it shouldn't be called.

But I wonder if maybe there should be a cleaner solution for such cases. Or maybe it's not worth it?

**Comment by soloparatolos** [comment]
I'm woking on a small app that uses checkboxes and I ended up here. The thing is that I only really need to set a pressed state without triggering the signal. The "set_pressed_no_signal()" would be really useful for these kind of cases.
