### ISSUE TITLE
ItemList new 3.2 behavior on touchscreen is weird (Android)

### ISSUE THREAD

**Issue by Coldragon** [godotengine/godot#33428]
**Godot version:** 3.2.beta1

**OS/device including version:** Android 10, Android 6.0.1, Android 8.1

**Issue description:** Before 3.2 ( =< 3.1.1) ItemList didn't have a reaction to touchscreen beside touching the scrollbar, now it behave strangely and go straight up or straight down (not smoothly). It conflict with the script I used that was smooth : https://github.com/godotengine/godot/issues/13235#issuecomment-402303376 even if I disable the script.

**Steps to reproduce:** Create an ItemList with more element than it can be showed (to be scrollable)

**Videos**: 
https://streamable.com/77eeh Godot 3.2.beta1.official on OnePlus 7T Android 10 GLES3 (Without custom script)
https://streamable.com/wdcru Godot 3.1.1.stable.official on OnePlus 7T Android 10 GLES (Without custom script)
https://streamable.com/t8dvd Godot 3.1.1.stable.official on OnePlus 7T Android 10 GLES (With custom script)

**Comment by akien-mga** [comment]
I can reproduce the issue on my Android phone with 3.2 beta 1. No problem on the other hand on my Linux laptop with a touchscreen.

**Comment by akien-mga** [comment]
The issue on Android is probably caused by #25474, CC @jeremyz.

> OS/device including version: iOS 12.x, Android 10, Android 6.x, Android 8.1

Do you actually reproduce the issue on iOS? Because InputEventPanGesture should only be implemented on macOS and Android right now.

**Comment by akien-mga** [comment]
Reproduction project (with display of event type): [ItemListScroll.zip](https://github.com/godotengine/godot/files/3820448/ItemListScroll.zip)

**Comment by Coldragon** [comment]
No, it's a mistake for iOS, ItemList doesn't behave on scroll outside of the scrollbar. (I'll edit my issue)

**Comment by jeremyz** [comment]
@akien-mga I think I have a fix for the android issue, see my last comment on #25474,
I'll try to test it in the next 48 hours.

**Comment by chungnx** [comment]
how can i fix it on GodoScript 3.2

**Comment by tavurth** [comment]
@chungnx [see my comment here](https://github.com/godotengine/godot/issues/13235#issuecomment-660614154)
