### ISSUE TITLE
Still able to create 3D Scenes after disabling 3D in "Manage Editor Features"

### ISSUE THREAD

**Issue by NelloDev** [godotengine/godot#33439]
**Godot version:**
3.2.beta 31f327a4a9c2637a8d2ada01b293ed138c3e6f99
**OS/device including version:**
5.3.8-arch1-1
**Issue description:**
After disabling "3D Editor" and all "Spatial" nodes in Manage Editor Features the Scene panel still gives the option to create a 3D Scene. By clicking on this option the scene's root node becomes a Spatial node. 

Since all Spatial nodes and the 3D editor are disabled the option to create a 3D Scene should be disabled as well
**Steps to reproduce:**
1. In the editor navigate to Editor > Manage Editor Features
2. Click New to create a new profile
3. Uncheck Enabled Features > 3D Editor and Enabled Classes > Nodes > Spatial
4. Click Make Current to enable the new profile
![2019-11-08-042054_1920x1080_scrot](https://user-images.githubusercontent.com/55169213/68464733-7ded5380-01e7-11ea-9d82-e9f2dd6a4581.png)
5. In the Scene panel click "3D Scene" to create a scene with a Spatial root node
![2019-11-08-042352_1920x1080_scrot](https://user-images.githubusercontent.com/55169213/68464931-de7c9080-01e7-11ea-9414-70eb7d8b2c6f.png)

**Comment by ssd71** [comment]
I would like to work on this

**Comment by MCrafterzz** [comment]
go ahead!

**Comment by code-xD** [comment]
I looked into the issue the main problem is that the scene dock is created only once and never updated. We need to restructure the instantiation of the scene panel.

**Comment by ssd71** [comment]
I apologise for delaying this, my computer is fried so regretfully I am unable to work on this issue :(

**Comment by amit6663** [comment]
Sir, i want to work on this issue.
