### ISSUE TITLE
Autocompletion may use wrong type if "as" is not used

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33434]
**Godot version:**
3.2 beta1

**Issue description:**
Consider this code
```
export var target_path: NodePath
onready var target: Node2D = get_node(target_path)
onready var hinge = get_parent()
```
Now see this
![image](https://user-images.githubusercontent.com/2223172/68440261-c0ecfe00-01ca-11ea-9263-4fd24a5dc098.png)
Autocompletion doesn't suggest `position`. Looking at the list, looks like it assumes that `target` is of type Node. Using "as" like this
```
onready var target: Node2D = get_node(target_path) as Node2D
```
or this
```
onready var target := get_node(target_path) as Node2D
```
will fix the completion.
![image](https://user-images.githubusercontent.com/2223172/68440347-07425d00-01cb-11ea-8a51-cf1e5c34f042.png)
So looks like the variable has wrong type in the first case. The casting should be automatic.

(btw, notice how on the second image there's no suggestion for `get_postion_in_parent()`, but it's suggested if `position` is absent. Another case of #33425)

**Comment by bojidar-bg** [comment]
So basically, the opposite of #31818? :smile:

**Comment by KoBeWi** [comment]
I think I know why this happens. When you use onready get_node variable, the type is inferred from the scene, bypassing the declared type. Using `as` will enforce the type.

I don't think this is expected behavior.
