### ISSUE TITLE
Sprite3d + SRGB active in worldEnviroment does not show in android

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#3344]
when you add a sprite3d object and active the srgb in world enviroment then you export it to android, in android it does not show the sprite3d.

**Comment by bojidar-bg** [comment]
@mohaalak Does it show under other platforms? What about textured plane objects :smile: ?

**Comment by mohaalak** [comment]
@bojidar-bg  yeah it will show in linux,mac but not in android.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch, in the GLES2 and GLES3 renderers respectively?

**Comment by aaronfranke** [comment]
Closing, no response for over 1 year after the above comment.
