### ISSUE TITLE
move_child/raise does not properly update order of execution

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#33449]
**Godot version:**
3.1.1 (Steam), 3.2-beta1

**OS/device including version:**
PC, Windows 10

**Issue description:**
Children rearranged with `move_child` method of `Node` (and `raise` method by its extension) sometimes receive input events in their initial order, not the actual tree order. The issue does not happen if the script with the `_unhandled_input` event bound is attached to the root of the child. But if handling is performed by one of the inner nodes of the child, then the order of execution is unexpected.

You can freely rearrange children with `move_child` and receive input events in tree order, if you have this hierarchy:
```
Root
- Child 3
- Child 1
- Child 4
- Child 2
```

The events will go through nodes in the order (2, 4, 1, 3). However, the order of execution will remain (4, 3, 2, 1) for the following hierarchy:
```
Root
- Child 3
-- ActualClickDetector
- Child 1
-- ActualClickDetector
- Child 4
-- ActualClickDetector
- Child 2
-- ActualClickDetector
```

By description `move_child` and `raise` should rearrange nodes inside their parent with the goal to affect [the order of execution for signals and events](https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-move-child) as well as [the draw order](https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-raise). It seems to me, that the inner hierarchy of moved children is not notified that the tree order has been changed.

The issue can be worked around by removing and adding back child (for `raise` case). But that workaround may not work for all `move_child` cases, because for that you would need to utilize `add_child_below_node`, and that method relies back on `move_child` internally.

**Steps to reproduce:**
1. Have a stack of nodes on top of each other (Children), each node (Child) having a shape that serves as a hitbox or boundaries.
2. Inside each Child there is a structure of nodes for whatever visual and logic purposes it requires; one of those inner nodes is there to detect clicks inside the hitbox (Detector).
3. Detector has `_unhandled_input` bound and expects `InputEventMouseButton` with `pressed` state; it then checks if a click hit inside its boundaries and performs some action if it did.
4. Whichever Child detects a click inside the hitbox first, marks input as handled, so other nodes do not receive it; Children receive the unhandled input event in tree order (topmost drawn/last in the hierarchy branch is the first).
5. Rearrange Children with `move_child` method, so that they do not follow the initial tree order.
6. Draw order is updated and respects tree order, however unhandled input is not respecting tree order and events are received in the initial order of Children.

**Minimal reproduction project:**
Attached: [godot-bug-repro-move_child.zip](https://github.com/godotengine/godot/files/3824694/godot-bug-repro-move_child.zip)

In this project there are 4 squares, which are added in particular order. Clicking on the topmost node under the mouse will rotate it 45 degrees.

Pressing a `move_child` button will randomly rearrange nodes with the `move_child` method. Clicking on the topmost node no longer works, initial order of elements is considered instead. 

Pressing a `remove_child + add_child` button will randomly rearrange nodes with those two methods. Clicking on the topmost nodes still works as expected, actual order of elements is considered.

Clicking a `reset order` button will revert nodes to their initial order (using `remove_child` and `add_child` to achieve consistency).

Note: the example project uses `raise` instead of `move_child` for brevity. To my understanding of `scene/main/node.cpp` the end result is the same.

**Comment by xsellier** [comment]
Not an expert, but I noticed that this piece of code does not propagate the event through the whole SceneTree, so I think this issue might come from there:
https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L363

**Comment by KoBeWi** [comment]
Still valid in 2c0d1c3
