### ISSUE TITLE
_render_target_allocate: Cannot allocate mipmaps for 3D post processing effects

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#33458]
**Godot version:**
3.2 Beta 1

**OS/device including version:**
Android 9 / Nokia 7 Plus

**Issue description:**
When you run a new Android GLES 2 project and run it on a device with remote debugging enabled, you get the following warning in the Errors panel:

```
W 0:00:00:0282   _render_target_allocate: Cannot allocate mipmaps for 3D post processing effects
  <C++ Source>   drivers/gles2/rasterizer_storage_gles2.cpp:4905 @ _render_target_allocate()
```

This problem was not present in 3.2 Alpha 3.

**Steps to reproduce:**

1. Create new Android GLES 2 project
2. Run it on an Android device

**Minimal reproduction project:**
[androidproblem.zip](https://github.com/godotengine/godot/files/3826290/androidproblem.zip)

**Comment by clayjohn** [comment]
This is just a warning saying that your device doesn't support MSAA. Previously it just silently didn't allocate the MSAA buffers.

**Comment by AlexRixhardson** [comment]
OK. Closing the issue, then.
