### ISSUE TITLE
3.2 Beta 1 issue: touch events are not working properly anymore on Android devices

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#33459]
**Godot version:**
3.2 Beta 1

**OS/device including version:**
Probably all Android devices. Tested on Android 9 / Nokia 7 Plus and Android Android 6.0.1 / Samsung S5 Neo

**Issue description:**
Touch events behave differently (wrong) on Android devices when project is built with 3.2 Beta 1 versus previous version (e.g. 3.2 Alpha 3, where they worked fine).

One example of the erratic behavior is `InputEventScreenDrag` event and its `speed` variable, which is returning different values in 3.2 Beta 1 versus previous versions (see steps to reproduce below). Beta 1 is returning values that are on average 1/100th of what previous versions of Godot returned. There seem to be many other issues as well -- e.g. the frequency of how often `_unhandled_input` event is called is also much slower on Beta 1. In addition to that, I have a suspicion that touch events are randomly not triggered at all (or at least with a huge delay).

**Steps to reproduce:**
1. Create new Android GLES 2 project
2. Add the following code to the main scene:
```
func _unhandled_input(event):
	if event is InputEventScreenDrag:
		print("Dragging: ", event.speed)
```
3. Run the project on an Android device
4. Start dragging your finger across the screen
5. Project built with 3.2 Beta 1 will return something like this:

```
Godot Engine v3.2.beta1.official - https://godotengine.org
OpenGL ES 2.0 Renderer: Adreno (TM) 512
 
Dragging: (0, 0)
Dragging: (0, 0)
Dragging: (17.991678, 0)
Dragging: (17.991678, 0)
Dragging: (17.991678, 0)
Dragging: (17.991678, 0)
Dragging: (-3.398338, 4.000867)
Dragging: (2.779894, 15.517185)
Dragging: (12.470333, 10.947922)
Dragging: (5.440369, 27.471069)
Dragging: (5.440369, 27.471069)
Dragging: (-17.489464, 10.462004)
Dragging: (-11.207641, 8.123693)
Dragging: (-11.207641, 8.123693)
Dragging: (0, 0)
Dragging: (-17.11792, 0)
```

6. Project built with 3.2 Alpha 3 will return correct values, something like the ones below (note the extreme differences in the values):

```
Godot Engine v3.2.alpha3.official - https://godotengine.org
OpenGL ES 2.0 Renderer: Adreno (TM) 512
 
Dragging: (0, 0)
Dragging: (0, 0)
Dragging: (0, 0)
Dragging: (-195.651947, 11.508937)
Dragging: (-195.651947, 11.508937)
Dragging: (-195.651947, 11.508937)
Dragging: (-195.651947, 11.508937)
Dragging: (-195.651947, 11.508937)
Dragging: (-195.651947, 11.508937)
Dragging: (-1040.91748, 340.965759)
Dragging: (-1040.91748, 340.965759)
Dragging: (-1040.91748, 340.965759)
Dragging: (-1040.91748, 340.965759)
Dragging: (-1040.91748, 340.965759)
Dragging: (-1040.91748, 340.965759)
Dragging: (-1337.544678, 722.691284)
Dragging: (-1337.544678, 722.691284)
Dragging: (-1337.544678, 722.691284)
Dragging: (-1337.544678, 722.691284)
Dragging: (-1337.544678, 722.691284)
Dragging: (-147.712769, 687.558289)
Dragging: (-147.712769, 687.558289)
Dragging: (-147.712769, 687.558289)
Dragging: (-147.712769, 687.558289)
Dragging: (-147.712769, 687.558289)
Dragging: (-147.712769, 687.558289)
Dragging: (1371.751953, -713.292908)
Dragging: (1371.751953, -713.292908)
Dragging: (1371.751953, -713.292908)
Dragging: (1371.751953, -713.292908)
Dragging: (1371.751953, -713.292908)
Dragging: (1371.751953, -713.292908)
Dragging: (1371.751953, -713.292908)
Dragging: (-1045.173584, -113.478699)
Dragging: (-1045.173584, -113.478699)
Dragging: (-1045.173584, -113.478699)
Dragging: (-1045.173584, -113.478699)
Dragging: (-1045.173584, -113.478699)
Dragging: (-442.407288, 445.455292)
Dragging: (-442.407288, 445.455292)
Dragging: (-442.407288, 445.455292)
```

**Minimal reproduction project:**
[androidproblem.zip](https://github.com/godotengine/godot/files/3826302/androidproblem.zip)

**Comment by alexzheng** [comment]
Also the event.relative is not correct.
