### ISSUE TITLE
Adding GodotPaymentV3 (IAP module) to the project causes error "Java_org_godotengine_godot_GodotLib_calldeferred: Condition ' !obj ' is true."

### ISSUE THREAD

**Issue by AlexRixhardson** [godotengine/godot#33461]
**Godot version:**
3.2 Beta 1

**OS/device including version:**
Android 9.0 / Nokia 7 Plus

**Issue description:**
If you add "org/godotengine/godot/GodotPaymentV3" module to the project (as per instructions in https://docs.godotengine.org/en/3.1/tutorials/platform/android_in_app_purchases.html), then you get the following error when you start the game:

```
E 0:00:00:0042   Java_org_godotengine_godot_GodotLib_calldeferred: Condition ' !obj ' is true.
  <C++ Source>   platform/android/java_godot_lib_jni.cpp:1368 @ Java_org_godotengine_godot_GodotLib_calldeferred()
```

Is GodotPaymentV3 supposed to be compatible with 3.2 Beta 1, or should we use something else now if we want to use IAP's in our Android games?

**Steps to reproduce:**
1. Create a new game,
2. Add Android module "org/godotengine/godot/GodotPaymentV3" to the project.
3. Run game on a device.

**Minimal reproduction project:**
[jniproblem.zip](https://github.com/godotengine/godot/files/3826498/jniproblem.zip)

**Comment by akien-mga** [comment]
There was some refactoring of the Android platform code and the code for `GodotPayment` moved from `platform/android/java/src/org/godotengine/godot/GodotPaymentV3.java` to `platform/android/java/lib/src/org/godotengine/godot/GodotPaymentV3.java` (i.e. now in the `lib/` folder).

I don't know if it only requires updating the documentation to match what's now required, or if we lost the compatibility with the previous way to register it. Either way this needs to be solved for 3.2.

**Comment by akien-mga** [comment]
I misinterpreted the issue, loading the module with `org/godotengine/godot/GodotPaymentsV3` and accessing it with `Engine.get_singleton("GodotPayments")` still seems to work, but indeed it raises this error in the logs:
```
11-27 11:06:16.499  7238  7286 I godot   : Loading Android module: org/godotengine/godot/GodotPaymentV3
11-27 11:06:16.502  7238  7238 E godot   : **ERROR**: Condition ' !obj ' is true.
11-27 11:06:16.502  7238  7238 E godot   :    At: platform/android/java_godot_lib_jni.cpp:1368:Java_org_godotengine_godot_GodotLib_calldeferred() - Condition ' !obj ' is true.
```

**Comment by akien-mga** [comment]
`calldeferred` is only used in the `GodotPaymentsV3` module it seems:
```
$ rg calldeferred
java_godot_lib_jni.cpp
1365:JNIEXPORT void JNICALL Java_org_godotengine_godot_GodotLib_calldeferred(JNIEnv *env, jobject p_obj, jint ID, jstring method, jobjectArray params) {

java_godot_lib_jni.h
65:JNIEXPORT void JNICALL Java_org_godotengine_godot_GodotLib_calldeferred(JNIEnv *env, jobject p_obj, jint ID, jstring method, jobjectArray params);

java/lib/src/org/godotengine/godot/GodotLib.java
205:    public static native void calldeferred(int p_id, String p_method, Object[] p_params);

java/lib/src/org/godotengine/godot/GodotPaymentV3.java
90:             GodotLib.calldeferred(purchaseCallbackId, "purchase_success", new Object[] { ticket, signature, sku });
95:             GodotLib.calldeferred(purchaseCallbackId, "consume_success", new Object[] { ticket, signature, sku });
99:             GodotLib.calldeferred(purchaseCallbackId, "consume_not_required", new Object[] {});
103:            GodotLib.calldeferred(purchaseCallbackId, "consume_fail", new Object[] { message });
107:            GodotLib.calldeferred(purchaseCallbackId, "purchase_fail", new Object[] { message });
111:            GodotLib.calldeferred(purchaseCallbackId, "purchase_cancel", new Object[] {});
115:            GodotLib.calldeferred(purchaseCallbackId, "purchase_owned", new Object[] { sku });
162:            GodotLib.calldeferred(purchaseCallbackId, "has_purchased", new Object[] { receipt, signature, sku });
166:            GodotLib.calldeferred(purchaseCallbackId, "iap_disconnected", new Object[] {});
170:            GodotLib.calldeferred(purchaseCallbackId, "iap_connected", new Object[] {});
224:            GodotLib.calldeferred(purchaseCallbackId, "sku_details_complete", new Object[] { mSkuDetails });
228:            GodotLib.calldeferred(purchaseCallbackId, "sku_details_error", new Object[] { errorMessage });
```

**Comment by akien-mga** [comment]
This actually doesn't seem to be a regression, the same issue happens in 3.1.2 RC 1:
```
11-27 11:17:49.828  9257  9325 I godot   : Loading Android module: org/godotengine/godot/GodotPaymentV3
11-27 11:17:49.844  9257  9257 E godot   : **ERROR**: Condition ' !obj ' is true.
11-27 11:17:49.844  9257  9257 E godot   :    At: platform/android/java_glue.cpp:1568:Java_org_godotengine_godot_GodotLib_calldeferred() - Condition ' !obj ' is true.
```

In the `iap.gd` example, you can see that `setPurchaseCallbackId` has to be set manually:
```
	if payment:
		# set callback with this script instance
		payment.setPurchaseCallbackId(get_instance_id())
```
If you do that it should work.

It could use better documentation, but that's probably best discussed on https://github.com/godotengine/godot-docs

**Comment by martinpelli** [comment]
@akien-mga Sorry to bother you, but I have exactly the same error but with the admob plugin, I have been trying to solve it for many days, maybe, you know of something that I have to change in the admob.gd, similar to this

**Comment by akien-mga** [comment]
You should ask for support on the Admob plugins GitHub repo, it's outside the scope of Godot itself.
