### ISSUE TITLE
Icons in "Create Root Node" are not changed when switching dark and light theme

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#33477]
**Godot version:**
3.2.beta

**Issue description:**
![root_node_icons_theme_dark_changed](https://user-images.githubusercontent.com/17108460/68525727-4cef4a80-02dd-11ea-9948-c9c24e3d2f91.png)

Expected (only on editor restarted):

![root_node_icons_theme_dark_changed_must](https://user-images.githubusercontent.com/17108460/68525737-685a5580-02dd-11ea-9b5d-33ca68ceffde.png)

**Steps to reproduce:**
1. `Scene` → `New Scene`, "Create Root Node" should appear in scene tree dock.
2. Try to switch from any "dark/black" theme to any "light/white" theme or vice versa.

You can change theme in editor settings (from "Default" which is dark, to "Light" which is light)

![godot_light_theme](https://user-images.githubusercontent.com/17108460/68580104-5237cb00-047e-11ea-8114-39568af5ed73.png)

**Comment by Xrayez** [comment]
I think these kind of bugs can be prevented with some approach as described in #11096.

**Comment by code-xD** [comment]
Can you explain more about the issue? I can't get a clear picture by the screenshots you have posted.

**Comment by Xrayez** [comment]
@code-xD updated issue description, should be fixed by #33481 though.
