### ISSUE TITLE
Godot 3.2: The relative of InputEventScreenDrag not work as expected on Android.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#33470]
**Godot version:**
3.2 beta 1

**OS/device including version:**
Android MIUI 11.0.3.0

**Issue description:**
the relative only can report very slow movement, for fast and long distant movement, the value is not correct.
On Mac OS the value is correct.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by AlexRixhardson** [comment]
This is probably related to https://github.com/godotengine/godot/issues/33461. Something strange has happened to the input events in the 3.2 Beta 1.

**Comment by avril-gh** [comment]
this issue is perhaps not fixed,
(its been closed by PR that has to fix it, then PR has been reverted but this issue remain closed)

I can confirm im experiencing exact same issue on android from some time a go
where very slow touch motions are detected but faster than this are ignored.

**Comment by akien-mga** [comment]
No, it's the revert PR that closed this issue, as it was caused by the now-reverted former PR :)

If you experience a similar issue on 3.2 alpha 3 or a future 3.2 beta 2, please file a new issue with detailed steps to reproduce.

**Comment by avril-gh** [comment]
@akien-mga 

oh, i see.
just compiled and tested v3.2.beta.custom_build.8d7de9a9e
and indeed it work nicely, like before. awesome. Thanks
