### ISSUE TITLE
select mode is changed to another when 2d or 3d viewport is not focused.

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3348]
reproduce steps.

1. create a node
2. make editable node name by double click
3. try to change name to ``qwe``

this will change select mode to another continuously

edit : I found it happens also when 2d or 3d viewport is not focused

**Comment by akien-mga** [comment]
What do you mean exactly by "select mode is changed to another"?

**Comment by volzhs** [comment]
I not sure what I should call it.

Select mode by <kbd>q</kbd>
Move mode by <kbd>w</kbd>
Rotation mode by <kbd>e</kbd>

**Comment by volzhs** [comment]
I did more tests.
This Select/Move/Rotation mode is changed when it's not focused.
Open any window(Project Settings, Project Export Settings, Editor Settings...) and try to type <kbd>q</kbd>, <kbd>w</kbd>, <kbd>e</kbd>.

**Comment by RebelliousX** [comment]
When you edit the node name, does it contain any of these letters (Q, W and E)?
If it does, it means there is a window focus issue which keeps the viewport to receive keyboard input while renaming.

**Comment by akien-mga** [comment]
Ah thanks, I had not understood that you mean the select mode in the viewport. Looks like LineEdit needs to stop the propagation of keyboard events @MarianoGnu :)

**Comment by MarianoGnu** [comment]
I'll take a look, i'm very sure propagation is stopped in LineEdit

**Comment by neikeq** [comment]
This is my fault. It was introduced by #3269. Fixing ASAP.

**Comment by volzhs** [comment]
as I commented above, there is more problems.

This Select/Move/Rotation mode is changed when viewport is not focused.
Open any window(Project Settings, Project Export Settings, Editor Settings...) and try to type <kbd>q</kbd>, <kbd>w</kbd>, <kbd>e</kbd>.

**Comment by volzhs** [comment]
just type <kbd>q</kbd>, <kbd>w</kbd>, <kbd>e</kbd> while another window is opened.

![anim](https://cloud.githubusercontent.com/assets/8281454/12343733/ca7c5ac4-bb79-11e5-9301-bfdc3ff5b50c.gif)

**Comment by neikeq** [comment]
The above PR should fix this particular issue of editors handling input when a dialog is visible. I am not sure if there is another situation that should be prevented. Currently, both canvas and spatial editor will check if they are visible and if there is no dialog.
