### ISSUE TITLE
Set As Main Scene needs an icon

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33487]
**Godot version:**
3.2 beta1

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/68530213-b172cf80-0306-11ea-938d-dac940ce9156.png)

**Comment by Xrayez** [comment]
Many of those icons were added in #32009.

There's a concern that it's probably not required to provide an icon for each option https://github.com/godotengine/godot/pull/32009#issuecomment-528829289:

> Also I'm not really sure it makes sense to have icons everywhere, especially when there is not a perfect fit

I think it would be a good idea to organize them in a way which doesn't create "empty icon spaces". But nobody is stopping anyone from drawing more icons of course. 🙂

**Comment by Calinou** [comment]
We could move "Set as Main Scene" below "Instance" so it looks less jarring.

**Comment by aaronfranke** [comment]
The existing "icon_play_scene.svg" would work well for this: ![f](https://user-images.githubusercontent.com/1646875/68550635-8f468380-03d2-11ea-9cee-47ae69c062c3.png)
