### ISSUE TITLE
Quick-open scene should match scene name first than whole path

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33504]
**Godot version:**
3.2 beta1

**Issue description:**
Just look at this
![image](https://user-images.githubusercontent.com/2223172/68536943-b57d0c80-035b-11ea-96e6-a33754317107.png)
I want to open a scene called GameMenu. But because it's in a folder named GameMenu and there's lots of other stuff there, the actual scene shows at the end. It should be on the top :/

(not sure if this shouldn't go into proposals tho)

**Comment by code-xD** [comment]
Can you add a dummy project file which can be used to prototype this issue?

**Comment by KoBeWi** [comment]
Sure, here:
[TestProject.zip](https://github.com/godotengine/godot/files/3831425/TestProject.zip)
