### ISSUE TITLE
Mono - Unhelpful Errors + Native SIGSEGV Stacktrace from an invalid transform

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#33506]
**Godot version:**
3.2.2 Beta 1 Mono

**OS/device including version:**
Ubuntu 19.10 eoan
x86_64 Linux 5.3.0-19-generic
Mono JIT compiler version 6.4.0.198

**Issue description:**
Mono runtime sometimes provides very unhelpful errors and native stack traces. While the attached project is an example of one, my personal project has experienced countless other varieties.
Also, the error crashes the entire game rather than just posting it in console and continuing to run (Arguable behavior)

![image](https://user-images.githubusercontent.com/14253836/68538501-eef15000-033a-11ea-90f8-bdf32cec29a1.png)
Console output: https://pastebin.com/e0GF0BHp
Mono crash memory blob: [mono_crash.mem.3390.1.blob.zip](https://github.com/godotengine/godot/files/3828047/mono_crash.mem.3390.1.blob.zip)

**Steps to reproduce:**
1. Set an invalid transform on a `MeshInstance` (does not work on `Spatial`)
Example: `GetNode<MeshInstance>("MeshInstance").Translation = new Vector3(float.NaN, float.NaN, float.NaN);`

**Minimal reproduction project:**
[GodotTestProject.zip](https://github.com/godotengine/godot/files/3828044/GodotTestProject.zip)
![image](https://user-images.githubusercontent.com/14253836/68538543-d6356a00-033b-11ea-99a1-072e03a0a5ee.png)

Lists of seemingly random errors:

- https://pastebin.com/0yi9t6xV

**Comment by Tobi-Mob** [comment]
Godot 3.3.3: I am unable to trigger a crash with the reproduction project.

![grafik](https://user-images.githubusercontent.com/69400800/132901777-c6d34cd1-bc17-4bd9-bf49-d1a8d9bdb204.png)

**Comment by akien-mga** [comment]
Also seems to build and run fine for me on 3.4 beta 4, so assuming fixed.
