### ISSUE TITLE
Project manager search is hiding all the projects

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3350]
Search in project manager is not working, it hides all the projects and the only way to see them again is to restart Godot.
![pmsearchnotworking](https://cloud.githubusercontent.com/assets/6129594/12324985/49ac8fd4-bac7-11e5-8ba3-c2a227e382b0.gif)

**Comment by neikeq** [comment]
I can't reproduce this behaviour on e2be837. Are you using a HEAD build?

**Comment by reduz** [comment]
This was contributed by somebody, no idea why it might have broken, here's
the file:

https://github.com/godotengine/godot/blob/master/tools/editor/project_manager.cpp

**Comment by akien-mga** [comment]
> This was contributed by somebody, no idea why it might have broken, here's
the file:
>
> https://github.com/godotengine/godot/blob/master/tools/editor/project_manager.cpp

And the commit that added the filter back in 2014: 57ab93b

**Comment by kubecz3k** [comment]
@neikeq good point I'm using couple days old build, will test in head

**Comment by kubecz3k** [comment]
Sorry a lot for false issue! As @neikeq said this bug is no longer present in main.
