### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by Schweini07** [godotengine/godot#33510]
3.1

Linux/Ubuntu 18.04

Godot report an internal Script Error! -opcode #0(report please). The error is here E 0:00:38:0602   Condition ' (ip + 5) > _code_size ' is true. Breaking..:
  <C Source>     modules/gdscript/gdscript_function.cpp:441 @ call()
  <Stacktrace>   Island2.gd:15 @ _physics_process()

![Bildschirmfoto vom 2019-11-10 09-22-10](https://user-images.githubusercontent.com/47503977/68541133-175d6680-039c-11ea-90dd-8786fc37d915.png)

**Comment by aaronfranke** [comment]
> Island2.gd:15 

That's strange considering that the file only has 5 lines.

Can you please provide a minimal reproduction project? Have you tested Godot 3.2 beta?

Also, ensure that the file ends with a newline. This is done automatically in 3.2.

**Comment by Zireael07** [comment]
The debugger often gets confused when inheritance is involved. What is in Rigidbody2D at line 15?

**Comment by Schweini07** [comment]
I really don't know what happened here. It's complete weird but the compiler said "report please". And so I did

**Comment by KoBeWi** [comment]
Has this happened only once or can be reproduced? If it was one-time thing, there's no reason to keep it open with so little information.

**Comment by aaronfranke** [comment]
This issue may be caused by the file not ending with a newline. Starting with 3.2, Godot will auto-append newlines. I think it should be closed unless someone can reproduce in Godot 3.2.
