### ISSUE TITLE
When scene is empty an "instance scene" icon, should show a hint on how to create inherited scene

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3352]
**Current info about this issue** is basically inside this comment: https://github.com/godotengine/godot/issues/3352#issuecomment-171688699

------

When empty scene is opened, some people would generally want to use inheritance scene feature but they are not aware of the fact that it's under Scene->New Inherited scene. They are trying to click + sign above the scene tree tab, and because it's dimmed, it looks like it's impossible to create new scene with root from the different scene. 
![inheritancescenehint](https://cloud.githubusercontent.com/assets/6129594/12328843/988a1dd6-badd-11e5-9d38-36fb9813e171.png)
**I think that the '+' should not be dimmed so much in this case, and after click there should be dialog popup with text something like: _"To create inherited scene you need to click Scene->New inherited scene"_**

As a side note: Some might think it would be good to remove Scene->New inherited scene, and put this functionality under '+' sign when scene tree is empty. I don't think it's a good idea since Inherited Scenes works slightly different then regular scene instancing, and the fact that it's creation is putted somewhere else might be good indicator of that (and hint for users to check documentation on how exactly it's working).

It would be ideal to have this in 2.0 since this is first stable with this functionality.

**Comment by akien-mga** [comment]
I'm not for adding a custom behaviour to the '+' button that would be enabled only in empty scenes, that would be more confusing than the current situation IMO. If the '+' button is normally used only to instance scenes, it should stay like that. It is also in the scene tree panel which is specific to members of the current scene tree. Creating an inherited scene is a behaviour which is clearly separated from the currently opened scene (and also independent of whether we want to use this opened scene as base for the inherited scene), so it's normal that it is not in the scene tree of the current scene.

Now for the question of making the inherited scene creation more evident, I don't have a strong opinion. It's a quite advanced feature after all, and also not one that would be used very often by most devs (for example in @KOBUGE-Games' current Project Kumquat game we used it only four times so far to create four tower scenes based on a common base scene), so I don't find it overly complicated to use in Scene->New inherited scene. Creating an inherited scene is like creating a normal scene, but you get to select a base scene to use for some shared parts, so IMO it's normal to have it next to Scene->New (empty) scene.

**Comment by kubecz3k** [comment]
@akien-mga well I don't have problem eighter but quite a few times people on irc were thinking that it's impossible to do that because + sign was dimmed. Yesterday I had one of this situations again that's why I decided to open this issue.

**Comment by trollworkout** [comment]
junior job :)))))))))

**Comment by reduz** [comment]
It makes sense I guess

**Comment by akien-mga** [comment]
> quite a few times people on irc were thinking that it's impossible to do that because + sign was dimmed.

In this case it's more that they misunderstood what inherited scenes are IMO, as creating them is not related to instancing. Once they are created, they can of course be instanced using '+' like any other subscene, but we should not accomate these user's misunderstand by modifying the subscene instancing button IMO.

We just need to find a better way to make the concept of inherited scenes easier to understand.

**Comment by reduz** [comment]
I plan on removing those buttons and replacing them with a contextenu for
2.1
There are two reasons for this:

1) Can't add more node related features (no room)
2) text should make it more clear what each function is

**Comment by kubecz3k** [comment]
@reduz not sure what to do with the issue, close and open new one with your context menu idea as a reminder?

**Comment by kubecz3k** [comment]
Closing this issue since it's not valid anymore after recent context menu changes in current 2.1 alpha branch.
