### ISSUE TITLE
Ruler's text colour option does not exist in Editor Settings

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [godotengine/godot#33523]
**Godot version:**

_3.2 beta 1_

**OS/device including version:**

All

**Issue description:**

In the Editor Settings, there lacks an option to set the ruler's text colour.

**Steps to reproduce:**

Open the Editor Settings, look for an option to change the ruler's text colour.

**Comment by Calinou** [comment]
Is this option necessary per se? If you have difficulty seeing the numbers, you could increase the theme's contrast in **Editor > Theme > Contrast**.

**Comment by KoBeWi** [comment]
I also noticed that ruler texts might not be visible enough on bright backgrounds. Maybe some dark translucent background below their text would be a good idea.

**Comment by AtomaFajrovulpo** [comment]
@Calinou Contrast seems not to affect the ruler text. ¯\_(ツ)_/¯
