### ISSUE TITLE
GDNative - get_aabb on mesh is not exposed

### ISSUE THREAD

**Issue by MilosLukic** [godotengine/godot#33535]
**Godot version:**
3.2 
**OS/device including version:**
Any OS
**Issue description:**
Normally this would be a feature request, but the absence of this function makes it hard to achieve some simple functionalities.

Example: If you want to have meshes, that are used for internal calculations instead of making them visible - e.g. navigation meshes. You can't access the get_aabb function on ArrayMesh/PrimitiveMesh. get_aabb function is already public in source code, but it's not exposed. Instead you have to create a MeshInstance, to get the aabb function. But the MeshInstance should be present in the tree (otherwise I get an error), which is not what one would want with internal meshes, and it also creates overhead, as all the needed functionalities are already in AMesh/PMesh. So currently I have no other option than to create a separate instance of AABB and set it as custom (which is exposed for some reason). But that duplicates the AABB creation logic which is lame.

EDIT: Since it's quite specific issue (not a lot of people use GDNative) and also looks like a simple one, I can volounteer to create a PR, just need a green light, or an explanation if a fix is not wanted.

**Comment by Zylann** [comment]
Just ended up on this too, but in GDScript. I had a look at the C++ of `Mesh`, `get_aabb()` is clearly present, just not exposed. In fact, it is only exposed on `MultiMesh` for some reason.

I think this issue is broader than just GDNative.
