### ISSUE TITLE
Document new scene inheritance concept

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3354]
We need a wiki page about scene inheritance to explain its purpose, how it works and how it should be used. We can then reference it in the changelog for 2.0.

Related to #3352.

**Comment by akien-mga** [comment]
@kubecz3k or @bojidar-bg Want to get started on this one? ;)
I think for starters a description on how to use it would be enough, @reduz can probably build on it later on if he wants to explain the philosophy/implementation some more.

**Comment by kubecz3k** [comment]
@akien-mga I was thinking more about creating demo project project about inheritance, but if couple words on how to use it will be enough then I can write this as well.

**Comment by kubecz3k** [comment]
[SceneInheritanceDemo.zip](https://github.com/godotengine/godot/files/139310/SceneInheritanceDemo.zip)
This is first version of the demo I'm working on. I'm not sure if it develops in the right direction or if it garbage. If someone know how I can make it better it would be nice.

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-docs/issues/481.
