### ISSUE TITLE
DirectionalLight is not work as expected on mobile device

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#33543]
**Godot version:**
3.1

**OS/device including version:**

**Issue description:**
The light is not show correctly on Android and iOS device
On Mac OS and Windows the result is correct, just like the preview in the Godot editor. 

**Steps to reproduce:**

**Minimal reproduction project:**
![1](https://user-images.githubusercontent.com/1130047/68595456-6ad2d000-04d4-11ea-9796-67d4f14b8f61.jpg)
<img width="712" alt="Screen Shot 2019-11-11 at 10 37 26 PM" src="https://user-images.githubusercontent.com/1130047/68595458-6b6b6680-04d4-11ea-8a6e-089abc395492.png">

**Comment by clayjohn** [comment]
Can you test on 3.2 beta 1? Many things have changed since 3.1 was released.

**Comment by alexzheng** [comment]
the same result on 3.2 beta 1 as 3.1.

**Comment by alexzheng** [comment]
After changed to GLES2, everything works as expected, and the render result is much better.

**Comment by clayjohn** [comment]
So the issue is only when using GLES3?

**Comment by alexzheng** [comment]
Yes.

**Comment by alexzheng** [comment]
BTW, the texture rendered by GLES2 is much better than GLES3

This is rendered by 2
<img width="261" alt="Screen Shot 2019-11-12 at 3 59 28 PM" src="https://user-images.githubusercontent.com/1130047/68652883-73bfb200-0565-11ea-8b03-5c94bc940094.png">

This is rendered by 3
<img width="271" alt="Screen Shot 2019-11-12 at 4 01 07 PM" src="https://user-images.githubusercontent.com/1130047/68653065-d153fe80-0565-11ea-9643-b6c3afb0a60a.png">

**Comment by clayjohn** [comment]
Can you test your project with the rendering/quality/shading/force_vertex_shading project setting and tell me if it makes the light appear the same way as it does on mobile?

You will have to check that setting and then close the editor and reopen it to see if it changes anything.

**Comment by alexzheng** [comment]
yes, you are right.

**Comment by clayjohn** [comment]
If that worked, then https://github.com/godotengine/godot/pull/33836 will fix this.
