### ISSUE TITLE
Segfault (core dumped) when running on Linux (manjaro)

### ISSUE THREAD

**Issue by Sajo8** [godotengine/godot#33546]
**Godot version:**

3.1.1.stable.official  

**OS/device including version:**

![device info](https://i.imgur.com/n3fCKFp.png)

**Issue description:**

Trying to start godot, and i get this error.

![ss](https://i.imgur.com/RsGYRgu.png)

It shows the initial splash screen, but crashes before it reaches the project manager.

Interestingly, if i cd to /usr/share/applications or /usr/bin then it works. But trying to launch from /home or from my taskbar doesn't work.

**Steps to reproduce:**

1. Install godot, be it through the AUR or from the self-contained executable on the website. 
2. Try to launch it.
3. You'll get this error

**Minimal reproduction project:**

None to be had

**Comment by Zireael07** [comment]
A permission problem I guess? I have the exact same chipset and it works, although I'm on Ubuntu not Manjaro.

**Comment by Sajo8** [comment]
`sudo godot` seems to work, but it doesn't load the same editor preferences, and opening the terminal first is a bit cumbersome anyways

**Comment by Calinou** [comment]
Could you install `strace` then run the Godot binary using `strace`?

**Comment by Sajo8** [comment]
The output from strace is too long for the terminal (it seems to discard it and I can't scroll up to it), and I'm not able to get it to print out to a file. I'll try compiling it and running `gdb` later and let you know

**Comment by Zireael07** [comment]
Do some of those help? https://askubuntu.com/questions/690703/save-current-terminal-scrollback-to-file

**Comment by Sajo8** [comment]
Here's the log: https://bin.privacytools.io/?ebc11f3f9b4caa11#J7VL7zf6AndnjoQgxB80YynRzD1Zxurgpb1gcCXeS+A=

It seems to be same thing over and over again (not even sure why it's calling the epic games store). I don't think the issue I was talking about got resolved though @Zireael07 some of the output (a lot of it actually im guessing) gets cut out because the terminal just discards it since it's too much. However, I figured some log was better than none so there you go. Not sure if the log will help much but oh well

**Comment by Calinou** [comment]
@Sajo8 It might be better to post the log here as a comment (in a code block, surround it with \`\`\`) so it doesn't expire over time :slightly_smiling_face:

**Comment by Sajo8** [comment]
You sure? It's really long. Here's a version which doesn't expire: https://bin.privacytools.io/?e74e6ee947360c42#o5BIwSBB9CgPmK0pCJn/YmxtsVxnmJQfbvDI+NUP33Q=

**Comment by Sajo8** [comment]
You sure? It's really long. Here's a link which doesn't expire: https://bin.privacytools.io/?6cea05757ebd84e0#JfMEWoKrSb/2JS2GA2GAxz3BBVZ/gvPu90BX4uMi6lw=

**Comment by novemberist** [comment]
So running **/usr/bin/godot** works but **godot** doesn't? Could you post the output of **alias godot** and **cat ~/.config/godot/editor_settings-3.tres | grep projects
** from your terminal?

**Comment by Sajo8** [comment]
No, `/usr/bin/godot` and `godot` both fail (when running it from the home dir). `cd /usr/bin/` and then `godot` works. It also works if you cd to `/usr/share/applications` and run `godot`.

I don't have any alias set for godot so `alias godot` just returns a "not found" error (`bash: alias: godot: not found`)

output of the other command:
```
projects/::home::sajo::Desktop::saj::godot::chukwas-labyrinth = "/home/sajo/Desktop/saj/godot/chukwas-labyrinth"
favorite_projects/::home::sajo::Desktop::saj::godot::chukwas-labyrinth = "/home/sajo/Desktop/saj/godot/chukwas-labyrinth"
projects/::home::sajo::Desktop::saj::godot::demoplatformer = "/home/sajo/Desktop/saj/godot/demoplatformer"
projects/::home::sajo::Desktop::saj::godot::demomultiplatformer = "/home/sajo/Desktop/saj/godot/demomultiplatformer"
projects/::home::sajo::Desktop::saj::godot::fbla = "/home/sajo/Desktop/saj/godot/fbla"
projects/::home::sajo::Desktop::saj::godot::demoplatformerrigid = "/home/sajo/Desktop/saj/godot/demoplatformerrigid"
favorite_projects/::home::sajo::Desktop::saj::godot::fbla = "/home/sajo/Desktop/saj/godot/fbla"
```

**Comment by akien-mga** [comment]
Sorry for the late answer. Can you still reproduce the issue?

Given that it works from `/usr/bin` and `/usr/share/applications`, but not from `/home/sajo`, I suspect that you have a `project.godot` file in `/home/sajo` which Godot tries to open, and then it imports your whole home folder as a Godot project.
It then hits stuff like this as shown in your strace;
```
stat("/home/sajo/Games/epic-games-store/dosdevices/z:/etc/audisp/plugins.d", {st_mode=S_IFDIR|0750, st_size=4096, ...}) = 0
```
Which seems to be an EGS install with a wine prefix that has a symlink to your root filesystem `/` and so it tries to load the whole `/` and eventually loops back to itself and explodes.

**Comment by qarmin** [comment]
Closing due lack of response
