### ISSUE TITLE
3.2 Beta 1 new project wizard can't create directory

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot#33549]
**Godot version:**
3.2 beta 1

**OS/device including version:**
Windows 10

**Issue description:**
The new project wizard can't seem to create a directory for the project.
Even creating a directory for the new project outside of the wizard, and then selecting it in the wizard has a problem. It supposedly creates the project, but then shows a broken icon in the project list and won't open it.

I'm running as a normal user. The Godot exe is on my desktop, and I'm trying to create the project in a directory that the user has full permissions to (in the desktop, dir)

**Steps to reproduce:**
1. Open Godot
2. Click "NewProject"
3. Click "Create Folder"

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
I can't reproduce it. Does it work with earlier versions in the same directory?

**Comment by Wavesonics** [comment]
Ha, I figured it out, maybe this will be helpful to someone else. Windows 10 has a (_new?_) feature:
"**Controller Folder Access**" under `Settings -> Virus & threat protection -> Ransomware protection`

It will block programs it finds suspicious from modifying files. You can allow individual folder/app access, but some times it doesn't notify you that it has blocked things apparently.

So you can just turn the feature off entirely if it's a problem for you.

Turning off **Controller Folder Access** fixed this problem for me.
