### ISSUE TITLE
Button flashing "hover" style after releasing away from it

### ISSUE THREAD

**Issue by MatthewJulian** [godotengine/godot#33553]
**Godot version:** 3.1.1 Stable

**OS/device including version:** Windows 10

**Issue description:** When you click off of a button (like when you change your mind), the button "flashes". I couldn't figure it out, but finally discovered that it looks like it's reporting as being "hovered" for a frame (or two). This doesn't really make sense, as it's not being hovered, and it looks weird when it flashes.
[Here is a gif](https://giant.gfycat.com/FearfulColossalAcornweevil.webm)

**Steps to reproduce:** Use a button, click and hold, release outside of button. It'll flash

**Minimal reproduction project:** 
[ButtonProblem.zip](https://github.com/godotengine/godot/files/3834020/ButtonProblem.zip)

**Comment by MatthewJulian** [comment]
Along with the above problems, the `is_hovered()` method returns true on the frame you let go (it shouldn't).
I assume this is a pretty easy fix for anyone familiar with the engine and how the GUI works. I couldn't figure it out in the engine, but I have a workaround I'm using with GDscript (it's not pretty though)

Thanks

**Comment by Calinou** [comment]
@MatthewJulian Can you post the code for the workaround here, please? :slightly_smiling_face:

**Comment by MatthewJulian** [comment]
Sure, here's what I'm currently doing on my TextureButtons:
![image](https://user-images.githubusercontent.com/39678120/69179334-9c492e00-0ac8-11ea-865c-d6417cae8d06.png)
```
extends Node2D
const normal := preload("res://normal.png")
const hover := preload("res://hover.png")

func _on_TextureButton_button_up() -> void:
	if !$TextureButton.get_rect().has_point(get_local_mouse_position()):
		$TextureButton.texture_hover = normal

func _on_TextureButton_mouse_entered() -> void:
	if $TextureButton.texture_hover != hover:
		$TextureButton.texture_hover = hover
```
So it changes the hover texture only when you release OUTSIDE of the button (that way, pressing it normally inside the button doesn't change). Then it just changes back to hover when your mouse enters it.

I was hesitant to post it because it's not really elegant, and also I don't know if changing the textures has a performance impact. (I assume it's just a matter of changing references, but you never know)

**Comment by fossegutten** [comment]
NOTIFICATION_MOUSE_EXIT is not called if mouse button is held down, when cursor is exiting a control node. So hovering is not set to false immediately in this case.
