### ISSUE TITLE
3.2 beta - shadows from DirectionalLight broken on android gles2

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#33551]
**Godot version:**
Godot Engine v3.2.beta.custom_build.953f37f49

**OS/device including version:**
```
Android GLES: ARM, Mali-450 MP, OpenGL ES 2.0
GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
EGL:
EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_framebuffer_target EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache
```
**Issue description:**
DirectionalLight shadows are broken on android gles2 device.
SpotLight shadows seems to work as intended on android gles2 device.
OmniLight shadows seems to work as intended on android gles2 device.
All three light types seems to work ok on desktop PC.
There are no error's in log.

![directionallight_shadow](https://user-images.githubusercontent.com/3224132/68629370-df613b00-04e3-11ea-8ae4-dbf8e715c270.jpg)
(there are grid because image is taken from editor)

but on android it looks like whole scene is covered with one huge shadow
![Screenshot_2019-11-12-00-36-25](https://user-images.githubusercontent.com/3224132/68629619-c311ce00-04e4-11ea-8b2f-ec3ba3f1b637.jpg)
(whole scene is more dark and there are no shadow shape)

**Steps to reproduce:**
try example project on android gles2 device

**Minimal reproduction project:**
[DirectionalLight_shadow.zip](https://github.com/godotengine/godot/files/3833604/DirectionalLight_shadow.zip)

**Comment by clayjohn** [comment]
Are you getting any errors?

I can't reproduce on my Google Pixel (but it also supports GLES3)

**Comment by avril-gh** [comment]
> Are you getting any errors?

dont know, will see when i'll be back home.

**Comment by avril-gh** [comment]
tested it more and thats what i got

DirectionalLight shadows are broken on android gles2 device.
SpotLight shadows seems to work as intended on android gles2 device.
OmniLight shadows seems to work as intended on android gles2 device.
All three light types seems to work ok on desktop PC.
There are no error's in log.

i have updated issue title and first post to better describe issue.

**Comment by avril-gh** [comment]
this is OmniLight shadow on android (seems ok)
![omnilight](https://user-images.githubusercontent.com/3224132/68688369-e4b79780-056e-11ea-9887-9e72f67b37e7.jpg)

this is DirectionalLight shadow on android (seems broken)
![directionallight](https://user-images.githubusercontent.com/3224132/68688432-ff8a0c00-056e-11ea-80d2-4ebd965799a2.jpg)

There are additional properties on DirectionalLight - DirectionalShadow, when you change it you can see different outcomes (like on picture above)

**Comment by Calinou** [comment]
@avril-gh Does the DirectionalLight shadow look correct on Android in 3.1.1?

**Comment by avril-gh** [comment]
@Calinou 
No idea... i use only latest godot available for all those awesome features and constantly improved gles2 support 😄
...but ok, ill try 3.1 branch... Be back in few moments.

**Comment by avril-gh** [comment]
@Calinou

3.1.1-stable
directional on android gles2 mali400
![directional](https://user-images.githubusercontent.com/3224132/68702168-9a431480-0588-11ea-98a4-7947a78142c6.jpg)
omni on android gles2 mali400
![omni](https://user-images.githubusercontent.com/3224132/68702169-9a431480-0588-11ea-92f6-c10949e8f56b.jpg)
spot on android gles2 mali400
![spot](https://user-images.githubusercontent.com/3224132/68702170-9a431480-0588-11ea-868f-97bf8bd42867.jpg)

v3.2.beta.custom_build.953f37f49
directional on android gles2 mali400
![directional](https://user-images.githubusercontent.com/3224132/68702288-da09fc00-0588-11ea-9942-a25225e60194.jpg)
omni on android gles2 mali400
![omni](https://user-images.githubusercontent.com/3224132/68702287-da09fc00-0588-11ea-8393-1e12db657ca9.jpg)
spot on android gles2 mali400
![spot](https://user-images.githubusercontent.com/3224132/68702286-da09fc00-0588-11ea-8a55-4e1b66dc518d.jpg)

test project used
[DirectionalLight_shadow.zip](https://github.com/godotengine/godot/files/3837812/DirectionalLight_shadow.zip)

device caps

```
GLES: ARM, Mali-400 MP, OpenGL ES 2.0
GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
EGL:
EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable EGL_ANDROID_framebuffer_target EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache

GLES: ARM, Mali-450 MP, OpenGL ES 2.0
GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
EGL:
EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_framebuffer_target EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache

```

seems like there are more shadow glitches than just directional on master
(eg. spot light on both 3.1.1 and 3.2)

**Comment by clayjohn** [comment]
I wonder if this has the same cause as https://github.com/godotengine/godot/issues/33825

@avril-gh Can you check out this PR and see if it helps? https://github.com/akien-mga/godot/pull/4

**Comment by avril-gh** [comment]
@clayjohn

directional on gles2 mali450
![dir](https://user-images.githubusercontent.com/3224132/69539746-69e67780-0f85-11ea-8e8d-aaa6d8ecd2c3.jpg)

omni on gles2 mali450
![omni](https://user-images.githubusercontent.com/3224132/69539795-7ff43800-0f85-11ea-810e-1034e6a30098.jpg)

spot on gles2 mali450
![spot](https://user-images.githubusercontent.com/3224132/69539829-94383500-0f85-11ea-9f16-bc88e5788693.jpg)

device caps
```
Android GLES: ARM, Mali-450 MP, OpenGL ES 2.0
GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
EGL:
EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_framebuffer_target EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache

```

tested on project
[DirectionalLight_shadow.zip](https://github.com/godotengine/godot/files/3886522/DirectionalLight_shadow.zip)

**Comment by akien-mga** [comment]
I can confirm that #33844 fixes it on Samsung Galaxy S3 (as @avril-gh just did, nice timing :)).

**Comment by avril-gh** [comment]
@akien-mga  
:)

**Comment by avril-gh** [comment]
directional light seems ok, but what with this spotlight ?
![spot](https://user-images.githubusercontent.com/3224132/69541574-bfbd1e80-0f89-11ea-88ac-12b0c6cffa5e.jpg)

**Comment by akien-mga** [comment]
@avril-gh According to your previous screenshots it's the same as in 3.1.1, so it's a different bug and not a regression.
