### ISSUE TITLE
Autocompleting searched signal callback inserts method call

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33550]
**Godot version:**
3.2 beta1

**Issue description:**
![wqq8ksn1QT](https://user-images.githubusercontent.com/2223172/68627686-ae323c00-04de-11ea-9d02-e92d9486c4e7.gif)

Works correctly if you just select the method from list, but it means you can't search for method.

**Comment by code-xD** [comment]
Could you elaborate on this issue? The gif is not clear to me.

**Comment by bojidar-bg** [comment]
It should insert `"on_sword_hit"` (a string containing the function's name) rather than `on_sword_hit()` (a call to that function). This might or might not be related to the OP not starting autocompletion with `"` or `'`, but directly with the function name. Could also be related to #33425.

**Comment by code-xD** [comment]
I found similar issues in the issues tab. I guess there is a common fix for all these issues?

**Comment by bojidar-bg** [comment]
There currently is not a common fix for all the similar issues, mainly because there has been little work on fixing them. There could be a common fix, but it is not as much of a priority as is fixing the issues.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4
In 4.0 the autocompletion seems broken right now, but the issue is probably gone, because `connect` takes Callables (i.e. method name without parentheses). Should be fine to close.
