### ISSUE TITLE
the export path in export window does not work.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#33567]
**Godot version:**
3.2 beta1

**OS/device including version:**

**Issue description:**
Whatever the path set, when click export project, the current directory is alway the project root folder.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by nathanwfranke** [comment]
Placing a local directory also doesn't work for me, however, placing a global directory like `/home` or `C:/Users` does work.

Local directories should work, though #28701.

**Comment by SolarLune** [comment]
I am also seeing this problem with Beta 2. Tthe export path always changes to be a relative path starting from the project directory folder name, regardless of where you browse or even enter into the export dialog. It also does this with (seemingly) any export template you specify; I've tried Android and Linux/X11. When attempting to proceed with the export, I am told the path doesn't exist when I attempt to actually export a project. Running Linux, Solus OS, fully updated, Godot 3.2 Beta 2 from the website.

![Screenshot from 2019-11-27 15-52-19](https://user-images.githubusercontent.com/4733521/69766678-ed42cd00-112d-11ea-952b-ba317deefabe.png)

![Screenshot from 2019-11-27 15-54-52](https://user-images.githubusercontent.com/4733521/69766777-5c202600-112e-11ea-909f-5e015062c32b.png)
