### ISSUE TITLE
ERROR: store_buffer: Condition ' !p_src ' is true when doing some operations.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#33564]
**Godot version:**
3.2.beta.custom_build. 157246ae8
**OS/device including version:**
Ubuntu 19.10
**Issue description:**

Using null buffer pointer in fwrite function is Undefinied Behaviour
```
size_t fwrite(
   const void *buffer,
   size_t size,
   size_t count,
   FILE *stream
);
```
and this cause this error
```
ERROR: store_buffer: Condition ' !p_src ' is true.
   At: drivers/unix/file_access_unix.cpp:278.
```

It can be easily silenced but probably this is not the best solution

**Steps to reproduce:**
1. Download "FirstPersonStarter" from Template in Project Manager

https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/scene/main/http_request.cpp#L358
2. 
Import GLTF File [Katalog bez nazwy.zip](https://github.com/godotengine/godot/files/3835035/Katalog.bez.nazwy.zip)

https://github.com/godotengine/godot/blob/dec10dd776fca2994277faa3a97b13e70317f784/core/io/resource_format_binary.cpp#L1538

**Comment by flyingpimonster** [comment]
I'm also seeing this issue when downloading files with the HTTPRequest node. The download still works, though.

**Comment by git2013vb** [comment]
I have the exactly error when I use this plugin: https://github.com/fenix-hub/godot-engine.text-editor

**Comment by Touitoui** [comment]
I have the same error. I don't have any plugin and i don't use HTTPRequest but i do have GLTF files imported from blender. (Created from scratch and exported by me with the latest version of blender).

It always happen in the script editor when i have an "error" in my code (ex: when writting an "if" before putting the ":" at the end).

It freeze the whole program for a few minutes... But if godot was started from a terminal, i can do a ctrl+c in it and godot will unfreeze like nothing happened ! Not exiting the program, just unfreezing it.

I use Godot_v3.2.1-stable_x11.64 on Ubuntu 18.04.4 LTS

**Comment by dpensky** [comment]
I also have this problem every time I use http_request to download a file on the android exported version of my game.
The download works correctly, only the debug log is too flooded:

![godot-error](https://user-images.githubusercontent.com/7250660/112188811-18361780-8be2-11eb-9bc7-9d626636c9a8.png)

**Comment by avnerh1** [comment]
This solved the problem in my case:
`$HTTPRequest.download_chunk_size = 65535`

**Comment by Calinou** [comment]
> This solved the problem in my case:
> `$HTTPRequest.download_chunk_size = 65535`

For reference, this is now the default in 3.3rc: https://github.com/godotengine/godot/pull/42896

**Comment by avnerh1** [comment]
> > This solved the problem in my case:
> > `$HTTPRequest.download_chunk_size = 65535`
> 
> For reference, this is now the default in 3.3rc: #42896

In 3.3, this doesn't solve the problem.
And although the file is still downloaded successfully, HTTPRequest.get_body_size() returns -1 instead of the actual file size.

**Comment by Calinou** [comment]
> HTTPRequest.get_body_size() returns -1 instead of the actual file size.

This is expected with some file hosts such as GitHub because they don't report the body size for files that were generated on-the-fly (such as ZIP archives). In this situation, you will get the body size if you try downloading the same file a second time in a short enough interval.

**Comment by avnerh1** [comment]
> > HTTPRequest.get_body_size() returns -1 instead of the actual file size.
> 
> This is expected with some file hosts such as GitHub because they don't report the body size for files that were generated on-the-fly (such as ZIP archives). In this situation, you will get the body size if you try downloading the same file a second time in a short enough interval.

That's generally true, but in my case these are the same specific files of which get_body_size() returns the actual size when exporting with Godot v3.2.3 but not when exporting with v3.3.

**Comment by Calinou** [comment]
@avnerh1 Which platform are you testing this with? The HTML5 HTTPClient has been rewritten to use `fetch()`, so it's possible that there may be regressions. Please create a new issue with a minimal reproduction project attached.

**Comment by volzhs** [comment]
I got the same error when running on android device via editor. 305c364c13
![Screenshot_20210424_015107](https://user-images.githubusercontent.com/8281454/115904346-a29ebf00-a49f-11eb-859d-db5edb73de5f.png)

**Comment by avnerh1** [comment]
> @avnerh1 Which platform are you testing this with? The HTML5 HTTPClient has been rewritten to use `fetch()`, so it's possible that there may be regressions. Please create a new issue with a minimal reproduction project attached.

I'm using Win10/Edge.

**Comment by tavurth** [comment]
I'm having this issue on Mac OS X.

The problem occurs in both debug mode (editor) and exported versions.

<img width="300" alt="Screenshot 2021-05-03 at 18 18 50" src="https://user-images.githubusercontent.com/100964/116895572-0497bb00-ac3c-11eb-9deb-877e34eaeafd.png">

<img width="300" alt="Screenshot 2021-05-03 at 18 19 03" src="https://user-images.githubusercontent.com/100964/116895628-12e5d700-ac3c-11eb-9c68-fe62815b12e5.png">


```gdscript
const endpoint = "https://query1.finance.yahoo.com/v8/finance/chart/AAPL?symbol=AAPL&period1=1614957299&period2=1620054899&useYfid=true&interval=15m&includePrePost=false"
const headers = [
	"user-agent: CustomTrader",
	"Content-Type: application/json",
	"Accept-Encoding: gzip"
]

var http
http = HTTPRequest.new()
http.download_chunk_size = 65535
http.download_file = "user://test.gz"

self.add_child(http)

var result = http.request(endpoint, headers(), true)
assert(result == OK)

result = yield(http, "request_completed")
```

**Comment by dpensky** [comment]
> > > HTTPRequest.get_body_size() returns -1 instead of the actual file size.
> > 
> > 
> > This is expected with some file hosts such as GitHub because they don't report the body size for files that were generated on-the-fly (such as ZIP archives). In this situation, you will get the body size if you try downloading the same file a second time in a short enough interval.
> 
> That's generally true, but in my case these are the same specific files of which get_body_size() returns the actual size when exporting with Godot v3.2.3 but not when exporting with v3.3.

I am also having this same problem. It worked in version 3.2.3 and in version 3.3 the function get_body_size () always returns -1 in the same file and server that returned correctly in the version exported with 3.2.3.
Does anyone have any fix or workaround for this? I used this function to show a progress bar.

```
download_request = HTTPRequest.new()
add_child(download_request)
# download_request.download_chunk_size = 65535;
download_request.download_file = download_destination
download_request.connect("request_completed", self, "_http_request_completed")

func _process(_delta):
  if download_request:
    var size = download_request.get_body_size()
    if size > 0:
      var done = float(download_request.get_downloaded_bytes()) / size
```

I have full access to the server (AWS) and the file. Is there any configuration that can solve this?

File is a pck with about 20Mb

**Comment by tavurth** [comment]
> but progress bar stoped working @dpensky 

It's probably not working because the server on the other end is responding with `-1` as the content length.

If you could make a small repo to test that it would help narrow down the issue a lot!

**Comment by dpensky** [comment]
Running directly in the editor, and downloading the same file from the same location, everything works perfectly, it only happens when I export to html

**Comment by dpensky** [comment]
Log when running from the EDITOR (this works)

```
[pck_loader] - Downloading: [https://server.address.com:8080/game_name.pck]
[pck_loader] - 	To: [user://game_name.pck]
[pck_loader] - _http_request_completed(0, 200, [Server: TornadoServer/6.1, Content-Type: application/octet-stream, Date: Fri, 14 May 2021 11:17:39 GMT, Accept-Ranges: bytes, Etag: "0fe59c74512f93f843904cc9a2ff201ffa838967e28a1bd8014258a36a11cc702f50f19ce32a9546575cfa727ef3ac2b59bd9451ff43f67af07f84090c1a6197", Last-Modified: Thu, 13 May 2021 19:58:15 GMT, Content-Length: 15809392], )
```

Log when running from the HTML EXPORT (this don't work)

```
[pck_loader] - Downloading: [https://server.address.com:8080/game_name.pck]
[pck_loader] - 	To: [user://game_name.pck]
**ERROR**: Condition "!p_src" is true.
game-lobby.js?v=…2b1d2ad644eabc5:354    At: drivers/unix/file_access_unix.cpp:279:store_buffer() - Condition "!p_src" is true.
game-lobby.js?v=…2b1d2ad644eabc5:354 **ERROR**: Condition "!p_src" is true.
game-lobby.js?v=…2b1d2ad644eabc5:354    At: drivers/unix/file_access_unix.cpp:279:store_buffer() - Condition "!p_src" is true.
[pck_loader] - _http_request_completed(0, 200, [Server: TornadoServer/6.1, Content-Type: application/octet-stream, Date: Fri, 14 May 2021 11:17:39 GMT, Accept-Ranges: bytes, Etag: "0fe59c74512f93f843904cc9a2ff201ffa838967e28a1bd8014258a36a11cc702f50f19ce32a9546575cfa727ef3ac2b59bd9451ff43f67af07f84090c1a6197", Last-Modified: Thu, 13 May 2021 19:58:15 GMT, Content-Length: 15809392], )
```

**Comment by yuyutsupoudel** [comment]
Has anyone found solution for this error? Im trying to download files using httprequest node but only sometimes issue is present.

**Comment by Calinou** [comment]
> Has anyone found solution for this error? Im trying to download files using httprequest node but only sometimes issue is present.

Which operating system and Godot version are you usign?

**Comment by yuyutsupoudel** [comment]
> Which operating system and Godot version are you using? If this is HTML5, see above.

Im using popos with godot 3.3.2. Error seems to come off at random interval. Tested with filesize less than 1 mb, issue isn't present. Tested with 10mb file issue is present.

**Comment by Calinou** [comment]
> > Which operating system and Godot version are you using? If this is HTML5, see above.
> 
> Im using popos with godot 3.3.2. Error seems to come off at random interval. Tested with filesize less than 1 mb, issue isn't present. Tested with 10mb file issue is present.

Which website are you downloading the file from? Many hosts such as GitHub will not report content lengths unless the file was already recently downloaded. This is because the file is generated on-the-fly, so GitHub doesn't even know the file size until the file is generated.

**Comment by yuyutsupoudel** [comment]
Mainly itch io and various other sites. Including couple of pictures from wikipedia. Although error is present, file is downloaded.

**Comment by avnerh1** [comment]
I noticed that the problem is not consistent. I suspect it has something to do with caching the file by CDN. I will look into it and report back if I find anything useful.

**Comment by darcio-studiobluechip** [comment]
For me the error of httprequet.get_body_size () returning -1 always happens in version 3.3 (and 3.3.2)

This function returns the correct value in version 3.2.3 when downloading the same file, on the same server in the same game

**Comment by tavurth** [comment]
@darcio-studiobluechip which file? Could you provide a sample project?

**Comment by darcio-studiobluechip** [comment]
> > > > HTTPRequest.get_body_size() returns -1 instead of the actual file size.
> > > 
> > > 
> > > This is expected with some file hosts such as GitHub because they don't report the body size for files that were generated on-the-fly (such as ZIP archives). In this situation, you will get the body size if you try downloading the same file a second time in a short enough interval.
> > 
> > 
> > That's generally true, but in my case these are the same specific files of which get_body_size() returns the actual size when exporting with Godot v3.2.3 but not when exporting with v3.3.
> 
> I am also having this same problem. It worked in version 3.2.3 and in version 3.3 the function get_body_size () always returns -1 in the same file and server that returned correctly in the version exported with 3.2.3.
> Does anyone have any fix or workaround for this? I used this function to show a progress bar.
> 
> ```
> var download_url = 'https://myawsserver.com/game.pck'
> var download_destination = "user://game.pck"
> download_request = HTTPRequest.new()
> add_child(download_request)
> # download_request.download_chunk_size = 65535;
> download_request.download_file = download_destination
> download_request.connect("request_completed", self, "_http_request_completed")
> var error = download_request.request(download_url)
> 
> func _process(_delta):
>   if download_request:
>     var size = download_request.get_body_size()
>     if size > 0:
>       var done = float(download_request.get_downloaded_bytes()) / size
> ```
> 
> I have full access to the server (AWS) and the file. Is there any configuration that can solve this?
> 
> File is a pck with about 20Mb. File is downloaded correctly, buy progress bar stoped working

My code is the above one.
- file is a godot game (only pck)
- host is in a amazon instance (s3)
- webserver is python tornado
- http exported game and files are stored in the same place/server/instance
- file is always downloaded correctly
- get_body_size works when running from the engine editor

**Comment by dpensky** [comment]
get_body_size also works when running the same code and requesting the same file from the same server on the android exported version of the game

**Comment by avnerh1** [comment]
Just switched from v3.2.3 to v3.3.2 and with HTML export the problem immediately showed up again, for every file.
Do we know the root cause of the problem, and what was changed from 3.2 to 3.3 that caused it?

**Comment by Calinou** [comment]
> Just switched from v3.2.3 to v3.3.2 and with HTML export the problem immediately showed up again, for every file.
> Do we know the root cause of the problem, and what was changed from 3.2 to 3.3 that caused it?

Quoting myself above:

> This is likely a regression from #46731 (see also #47597)

**Comment by akien-mga** [comment]
The fix is simple:
```diff
diff --git a/drivers/unix/file_access_unix.cpp b/drivers/unix/file_access_unix.cpp
index ec23df62d0..6ea55219bb 100644
--- a/drivers/unix/file_access_unix.cpp
+++ b/drivers/unix/file_access_unix.cpp
@@ -264,7 +264,7 @@ void FileAccessUnix::store_8(uint8_t p_dest) {

 void FileAccessUnix::store_buffer(const uint8_t *p_src, uint64_t p_length) {
        ERR_FAIL_COND_MSG(!f, "File must be opened before use.");
-       ERR_FAIL_COND(!p_src);
+       ERR_FAIL_COND(!p_src && p_length > 0);
        ERR_FAIL_COND(fwrite(p_src, 1, p_length, f) != p_length);
 }
 
```
Cf. #49394.
