### ISSUE TITLE
[macos 10.15] Compiling error in bullet physics

### ISSUE THREAD

**Issue by thisismike97** [godotengine/godot#33573]
**Godot version:**
3.1.1 stable release
**OS/device including version:**
macos 10.15 catalina / scons 3.1.1 / xcode 11.1
**Issue description:**
compiling error
**Steps to reproduce:**
compiling with "sudo scons bits=64 p=osx -j 6"

**Detailed log:**

thirdparty/bullet/LinearMath/btMatrix3x3.h:910:14: error: argument value 10880 is
outside the valid range [0, 255] [-Wargument-outside-range]
__m128 vk = bt_splat_ps(_mm_load_ss((float*)&k), 0x80);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/bullet/LinearMath/btVector3.h:43:29: note: expanded from macro
'bt_splat_ps'
#define bt_splat_ps(_a, _i) bt_pshufd_ps((_a), BT_SHUFFLE(_i, _i, _i, _i))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/bullet/LinearMath/btVector3.h:41:33: note: expanded from macro
'bt_pshufd_ps'
#define bt_pshufd_ps(_a, _mask) _mm_shuffle_ps((_a), (_a), (_mask))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/xmmintrin.h:2608:11: note:
expanded from macro '_mm_shuffle_ps'
(__m128)__builtin_ia32_shufps((__v4sf)(__m128)(a), (__v4sf)(__m128)(b), \
^
In file included from modules/bullet/bullet_physics_server.cpp:31:
In file included from modules/bullet/bullet_physics_server.h:34:
In file included from modules/bullet/area_bullet.h:34:
In file included from modules/bullet/collision_object_bullet.h:40:
In file included from thirdparty/bullet/LinearMath/btTransform.h:18:
In file included from thirdparty/bullet/LinearMath/btMatrix3x3.h:18:

**Comment by bruvzg** [comment]
It's fixed in master and backported to 3.1 in #32303
