### ISSUE TITLE
The tilemap editor become very hard to paint and erase tile in 3.2 beta 1

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#33588]
**Godot version:**
3.2 beta 1

**OS/device including version:**

**Issue description:**
Compared to 3.1, 3.2 is very hard to use.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
Compared to other issues, this one is hard to understand.

Mind if you give a bit more details?

**Comment by TheWhiteLlama** [comment]
Here some thoughts you could ask yourself and add the answers to your description when creating these kind of issues on github to make it more understandable for users who are not familiar working with tilemaps:

- What is the difference between painting / erasing tiles in version 3.1, 3.2 compared to version 3.2 beta
- What does it make harder for you to do it?
- How could we know what you're talking about without providing at least something like a youtube video or something which shows the differences

Would be nice if you provided more information :-)

**Comment by alexzheng** [comment]
I known how to report an issue.
However, just too many bugs for this function.
I think it's very easy to notice all these strange behaviors if just test it.

Just list some: 
1. the Inspector and TileMap will shake while painting. 
2.hold the control to eraser and release to paint will require one more action to select a tile.
.....

**Comment by groud** [comment]
> However, just too many bugs for this function.

Yeah, that's why such issues are useless for developers. 

Please check whether or not an issue exists for each problem, eventually open an issue for each of them and provide, as asked in the issue template, the steps to reproduce and eventually a reproduction project.

**Comment by alexzheng** [comment]
It's just one issue for the tilemap editor.
