### ISSUE TITLE
Tooltips with dynamic fonts will have extra empty space if oversampling is enabled in 2D stretch mode

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#33584]
**Godot version:**
3544457

**OS/device including version:**
Manjaro GNU/Linux

**Issue description:**
If you're using dynamic fonts in tooltips, while having the `stretch_mode` set to `2d`, making the window larger than the original size will result in extra empty space in the tooltip if `use_oversampling` is enabled:
![Screenshot_20191112_204939](https://user-images.githubusercontent.com/30739239/68720429-1a787280-05a7-11ea-9358-a40e81835287.png)

**Minimal reproduction project:**
[oversample_tooltip_bug.zip](https://github.com/godotengine/godot/files/3838675/oversample_tooltip_bug.zip)

**Comment by volzhs** [comment]
![image](https://user-images.githubusercontent.com/8281454/71822659-bff82000-30d8-11ea-94df-c8cac907ea17.png)

it seems fixed at some point before 3.2.beta5.
can't reproduce it with 3.2.beta5.

**Comment by volzhs** [comment]
![image](https://user-images.githubusercontent.com/8281454/71822858-4c0a4780-30d9-11ea-8968-655d6b3745a1.png)

here's test screenshot with 61dd7748ca
showing tooltip after resizing window bigger.

**Comment by akien-mga** [comment]
I can reproduce the "too narrow" issue from https://github.com/godotengine/godot/issues/33584#issuecomment-571150857 in the current master branch too. It's somewhat better than the original bug, but it would be nice to ensure a better consistency between different scaling ratios.
