### ISSUE TITLE
Debugger not stopping at ELIF any more

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#33587]
**v3.2.alpha.calinou.af4fd9**

In 3.1 the debugger would stop on each IF/ELIF line when stepping through code.

![31](https://user-images.githubusercontent.com/26915986/68735780-eea3bf80-059b-11ea-9434-65ed5756a498.gif)

In 3.2 the debugger jumps over the code.

![32](https://user-images.githubusercontent.com/26915986/68735790-fa8f8180-059b-11ea-8f8d-4c9a563023af.gif)

though different, this may be related to this bug [#32782](https://github.com/godotengine/godot/issues/32782)

**Comment by tygree** [comment]
I'll look into this

**Comment by akien-mga** [comment]
I can confirm the regression, which is already present in 3.1.1-stable, so it was cherry-picked.

In my quick tests the behavior is also buggy in 3.1 to some extent, but somewhat better than in 3.1.1 or the current master branch.
