### ISSUE TITLE
Key releases are ignored when the game window is not in focus

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#33582]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 7

**Issue description:**
When the moment of minimizing/unfocusing the game window coincides with some key being in pressed state, the key's state is stuck until pressing and releasing again.

Probably, the key states should rather be auto-released at the moment of minimizing/unfocusing the game window.

**Steps to reproduce:**
- Press right arrow key (or other key triggering movement in the game)
- Without releasing the key, unfocus the game window (by clicking with mouse outside of the window) 
- Release the key
- Watch the movement happening even that the key is not pressed

**Minimal reproduction project:**
Any project with direct hero control, like official Platformer 2D demo

**Comment by KoBeWi** [comment]
This is already fixed in 3.2

**Comment by starry-abyss** [comment]
@KoBeWi Cool! Will it be also fixed in 3.1.2? Can't find the corresponding commit.

**Comment by KoBeWi** [comment]
Here's the PR: #28061

It doesn't have cherrypick label though, so it won't be in 3.1.2.
