### ISSUE TITLE
Editor: FileSystem Show in FileSystem doesn't work

### ISSUE THREAD

**Issue by BTK-InterBlock** [godotengine/godot#33590]
Godot version: 3.2 beta 1

OS/device including version: windows 10

in TextureRect under Texture if you click on "Show in FileSystem" it doesn't work. For me that just collapse everything to res://  or it just changes path at the top but doesn't open the actual folder.
A bug is that FileSystem doest open folder even if there is a path to it.

![test](https://user-images.githubusercontent.com/57711479/68763454-c3ab8100-0618-11ea-8c32-3d58a3db7f72.png)

**Comment by akien-mga** [comment]
> Godot version: 3.2

Please be more specific, that goes back to March 2019.

**Comment by volzhs** [comment]
![show_in_filesystem](https://user-images.githubusercontent.com/8281454/68875643-85ac7b00-0746-11ea-8aab-30ff3f059b6b.gif)

I have the same issue and this gif shows what happened.

**Comment by volzhs** [comment]
it seems from 469acbfd0c4f2131cc4d57fec8a1d9d02390563f #33183

**Comment by akien-mga** [comment]
CC @silvanocerza

**Comment by silvanocerza** [comment]
I'll take a look at it. 😃

**Comment by pgoral** [comment]
I have found commit which broke this. It is b964e911b67769257959b7a592faf55b90c44ea9
Last working commit is 8e76c5701b5af2b185eab504786cb66b28a01b4a
