### ISSUE TITLE
Error while compiling Godot 3.2 (current branch) on windows using MinGW

### ISSUE THREAD

**Issue by aikoncwd** [godotengine/godot#33599]
**Godot version:** 3.2 current branch

**OS/device including version:** Windows 10 Pro 64 bits

**Issue description:** When trying to compile Godot 3.2 current branch from source, using the documentation: https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_windows.html I get this error:

    [Initial build] progress_finish(["progress_finish"], [])
    [Initial build] Linking Static Library ==> modules\freetype\libfreetype_builtin.windows.opt.tools.64.a
    [Initial build] Ranlib Library         ==> modules\freetype\libfreetype_builtin.windows.opt.tools.64.a
    [Initial build] Linking Static Library ==> core\libcore.windows.opt.tools.64.a
    Ranlib Library         ==> core\libcore.windows.opt.tools.64.a
    [Initial build] Linking Program        ==> bin\godot.windows.opt.tools.64.exe
    =====
    b"C:/Users/jgonzalez/scoop/apps/gcc/current/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: hq2x.windows.opt.tools.64.o (symbol from plugin): warning: No symbol for section '_ZZN4Math9fast_ftoiEfE1b' found
    lto-wrapper.exe: fatal error: CreateProcess: No such file or directory
    compilation terminated.
    C:/Users/jgonzalez/scoop/apps/gcc/current/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
    collect2.exe: error: ld returned 1 exit status"
    =====
    scons: *** [bin\godot.windows.opt.tools.64.exe] Error 1
    scons: building terminated because of errors.

**Steps to reproduce:** The command line used is: `C:\godot>scons -j4 use_mingw=yes platform=windows bits=64 target=release_debug use_lto=yes`

**Comment by Calinou** [comment]
Try installing `make` as described at the bottom of #12516.

**Comment by aikoncwd** [comment]
Thanks @Calinou , installing `make` solved the problem.
