### ISSUE TITLE
build fails: error C3861: 'format_error_message': identifier not found

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#33600]
**Godot version:**
1b65967e0

**OS/device including version:**
win10

**Issue description:**
build fail
call scons platform=windows target=release_debug tools=no use_lto=yes -j8
[ 13%] platform\windows\os_windows.cpp(2259): error C3861: 'format_error_message': identifier not found
[ 13%] platform\windows\os_windows.cpp(2860): error C3861: 'format_error_message': identifier not found
platform\windows\os_windows.cpp(2870): error C3861: 'format_error_message': identifier not found
platform\windows\os_windows.cpp(2878): error C3861: 'format_error_message': identifier not found
platform\windows\os_windows.cpp(2882): error C3861: 'format_error_message': identifier not found
 
**Steps to reproduce:**
build in x64_x86 Cross Tools

**Minimal reproduction project:**
current 3.2 source code

**Comment by bruvzg** [comment]
`format_error_message'` function is in `#ifdef DEBUG_ENABLED`, but calls to it are not.

Regressing from #29797 (added `ifdef`) and #31227 (`ERR_EXPLAIN` has been defined in debug mode only, `ERR_FAIL` is not) combined.
