### ISSUE TITLE
Arrow keys and enter don't work anymore in "Quick open" dialog

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3362]
@TheHX @neikeq @MarianoGnu

**Comment by neikeq** [comment]
Regression from 7fa3bd4. Looks like _Tree_ [is not selecting cells properly](https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L1877) with _SELECT_MULTI_ mode.

**Comment by neikeq** [comment]
Looks like you have to select the scenes with KEY_SPACE. However, if the search LineEdit is focused, that won't work.

**Comment by TheHX** [comment]
@akien-mga @neikeq

Maybe i can add a shortcut, for example pressing ```CTRL+KEY_SPACE``` will select the current selected cell, even with the search box focused.

**Comment by akien-mga** [comment]
@TheHX Well if it's possible I'd prefer to get back the previous behaviour. In 1.1-stable, the quick open window used to behave like this:
- on start, first item is selected
- up and down arrow are used to navigate the Tree
- enter/return open the currently selected item
- all other input is used in the line edit as usual (input, selection of letters with left/right arrows + shift, etc.)
Even if the LineEdit was selected on purpose, the up/down arrows would still change the selection in the Tree.

**Comment by MarianoGnu** [comment]
Just connect a new method to line_edit->"_input" signal, should call both methods even if event is accepted...

**Comment by TheHX** [comment]
To me the best option is when search box is focused the Tree, when navigating with up and down, will select only one item, and the dialog will behave like in Godot 1.1. And with the Tree focused it will allow multiselection with mouse and up and down with space to select the current cell.

**Comment by neikeq** [comment]
@TheHX Sounds good to me. Most of the time when selecting with arrow keys, the LineEdit is focused.

**Comment by TheHX** [comment]
@neikeq yes and the user can easily focus the Tree pressing tab.
