### ISSUE TITLE
Can't compare arrays by reference

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#33627]
Godot 3.1.1

I want to compare the arrays for uniqueness. I can't do it using array comparison.

```
var test = [1, 2]
var test2 = test
var test3 = [1, 2]
print(test == test)
print(test == test2)
print(test == test3)
```

The output is:
```
True 
True 
True
```
I expect: 
```
True 
True
False
```

I want to be able to tell the difference between `test2` and `test3` as appending new values to `test2` will not have them appended to `test3`.

i.e.
```
var test = [1, 2]
var test3 = [1, 2]
print(test == test3)
test3.append(4)
print(test == test3)
```
The output is:
```
True 
False
```

I need a way to compare the arrays by reference. There is no way to do it (?).
In other words, how do I get the pre-"fix" #1485 results?

**Comment by charliewhitfield** [comment]
I would like a solution to this problem too. Note that dictionaries act "correctly" (imho):
```
print({a=1} == {a=1})
print([1] == [1])
```
prints...
```
False
True
```
I'd much prefer to see arrays work as dictionaries. Otherwise, we need some way to test whether two arrays are different arrays, as stated by OP.

**Comment by tygree** [comment]
I'll look into this. Would you like this to be a change to the "==" operator or should an additional function be added to compare two arrays by reference?

**Comment by charliewhitfield** [comment]
I'm just expression my own preference. But I think arrays should work like dictionaries and objects, where "==" tests identity not content. I believe we are currently lacking any way to do an identity test for arrays (this is currently holding me up for a procedural save system).

I can certainly see the convenience value of one or more array (& dictionary) functions that compare content. But these should not be "==".

**Comment by charliewhitfield** [comment]
I opened [a feature request](https://github.com/godotengine/godot-proposals/issues/874) to ask for some way to test array identity, whether it be `==` or some other way. If you need this functionality, or has an opinion on implementation, please go over there to comment.

**Comment by akien-mga** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/874.
