### ISSUE TITLE
Move to dialog isn't using the file open dialog

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#33638]
**Godot version:**
067c259

**Issue description:**
The file move to dialog is using an old directory selection dialog.

**Steps to reproduce:**
Right click on a file and select "Move to".
![20191115](https://user-images.githubusercontent.com/28286961/68947971-22a6fc80-07b7-11ea-83ce-fc32469aec42.png)

**Comment by KoBeWi** [comment]
It might be intended. It's easier to select directory this way than navigating the standard dialog.

**Comment by KoBeWi** [comment]
This is not a bug, so closing. If you think there should be a file dialog there, [please open a proposal](https://github.com/godotengine/godot-proposals/).
