### ISSUE TITLE
CameraTexture Bug

### ISSUE THREAD

**Issue by AstemirK** [godotengine/godot#33642]
**Godot version:**
3.2 beta 1

**OS/device including version:**
MAC OS 10.14.2
**Issue description:**
CameraTexture texture has red color when turned on.
Also it very bugged.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by asmaloney** [comment]
It doesn't seem like this report has enough information to (1) describe the issue, and (2) reproduce it.

**Comment by vanoak** [comment]
I'm having the same issue. I believe this is documented in  https://docs.godotengine.org/en/stable/classes/class_camerafeed.html. The red image is actually the first of the two images returned by the camera. The main concern for me is that the documentation states "_need to be combined in a shader. Godot does this automatically for you if you set the environment to show the camera image in the background._" and an example of the shader isn't provided.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/51830, which has more information about the issue at hand.
