### ISSUE TITLE
Tabs don't show a close (X) icon

### ISSUE THREAD

**Issue by rdmtt** [godotengine/godot#33649]
**Godot version:**
3.0+
Tested on Windows 10.

**Issue description:**
**Tab** nodes can't be closed by interface, they don't show a close icon (X). They ignore the _tab_close_display_policy_ value. The tabs in the editor work fine.

**Steps to reproduce:**
Add a **TabContainer**, add a few **Tabs**, set _tab_close_display_policy_ to **Show Always** or **Show Active Only**. Run. You won't see the X icons.

**Minimal reproduction project:**
[Tabs_Github.zip](https://github.com/godotengine/godot/files/3853467/Tabs_Github.zip)

**Comment by KoBeWi** [comment]
See this comment https://github.com/godotengine/godot/pull/9773#issuecomment-317223566

**Comment by rdmtt** [comment]
But wouldn't it be better if Tab nodes acted more like the tabs in the Godot editor? There is even a close_icon parameter in Custom Icons:
![close_icon](https://user-images.githubusercontent.com/49587900/68992907-f43a2780-0871-11ea-91f0-ae368f511924.PNG)

The problem is that there is no way to show that icon anywhere on the tab, because there's only one icon slot on a tab (and it's positioned on the left). Maybe there is a bug in the code that's preventing the close button from showing up?

**Comment by TheDuriel** [comment]
arent the decrement and increment buttons also broken still?

tab headers will also occasionally overflow past the width of the node. a deeper look at how that header works is probably warranted. especially since the tab containers the editor uses function as expected.

**Comment by golddotasksquestions** [comment]
This is pretty stupid. TabContainer does not produce a close icon/button on the tabs it creates, which it probably should.
So the user after a bit of research finds the Tabs node, which does have the close functionality, however does not make the button and icon appear if you add the Tabs in the editor or via duplicate, even though this makes tabs visually appear. The only option is to add them in code.

Instead of having either as working option, neither option is working as it should. :(

**Comment by TheDuriel** [comment]
The Tabs node is not meant for use with the TabContainer. The Tabs node is a, now, outdated way of displaying a list of Buttons. The same can be achieved better and easier with normal Containers, normal Buttons, and a ButtonList.

**Comment by KoBeWi** [comment]
Tabs were renamed to TabBar and it's now mentioned in TabContainer description.
Also TabContainer now internally uses TabBar for displaying tabs, so you can access it via script and change the tab close display policy.

Closing.
