### ISSUE TITLE
Some items on the scons help page are duplicated

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#33651]
**Godot version:** master

**OS/device including version:** Linux, Ubuntu 18.04 64-bit

**Issue description:** Some of the items on the `scons --help` page are duplicated. For example, `use_llvm` is listed twice, as well as `use_static_cpp`, `use_lsan`, and several more.

**Steps to reproduce:** Run `scons --help` inside of a folder with the Godot source code.

**Minimal reproduction project:** N/A

**Comment by KoBeWi** [comment]
Looks resolved in master.
