### ISSUE TITLE
Editor issue

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33669]
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
Win10 Home 64

**Issue description:**
The Transform data type does not specify that it is of the 2D type.
There are two types of transform, "Transform" and "Transform2D", that should be specified as it confuses new users.

**Steps to reproduce:**
Create a node of type KinematicBody2D.
Note that the "Transform" property (of Node2D) does not specify that it is of type 2D.
![1](https://user-images.githubusercontent.com/19652075/69005412-40dd3b80-0922-11ea-9191-ee1fb1199273.png)

**Minimal reproduction project:**
It is not necessary

**Comment by TheFlamyy** [comment]
I don't think that "Transform" in this case refers to the class `Transform`/`Transform2D` but rather the local property (or a group of properties).
The same can be observed with other groups such as "Collision" with "Layer" and "Mask" (inside `KinematicBody2D`)

**Comment by groud** [comment]
Yes, as stated above this has nothing to do with the Transform2D class. It's just the title of a group of properties relate to each other.

**Comment by Torguen** [comment]
Ok thanks guys.
