### ISSUE TITLE
linear_damp and angular_damp should be 0 to 1

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#33676]
**Issue description:**
In Area2D, in the description of linear_damp and angular_damp it states they can be between 0 and 1, but they have a slider that goes beyond that.

**Comment by Calinou** [comment]
It seems we allow linear/angular damp to go from 0 to 100 in both 2D and 3D, but I don't know if this always makes sense. Maybe it does, but only in 2D?

**Comment by fsy98** [comment]
I don't know what happened to your probelm, but in the code it shows it allow the range from 0-100 ,and  each interval could be 0.001.
<img width="664" alt="Capture" src="https://user-images.githubusercontent.com/30133945/69373556-11a43280-0c72-11ea-9fed-bb56b9090a12.PNG">

**Comment by Jummit** [comment]
> I don't know what happened to your probelm, but in the code it shows it allow the range from 0-100 ,and each interval could be 0.001.
> <img alt="Capture" width="664" src="https://user-images.githubusercontent.com/30133945/69373556-11a43280-0c72-11ea-9fed-bb56b9090a12.PNG">

The problem is that linear_damp and angular_damp should be from 0 to 1, as stated in the documentation. Maybe the docs are wrong, I don't know.

**Comment by fsy98** [comment]
> > I don't know what happened to your probelm, but in the code it shows it allow the range from 0-100 ,and each interval could be 0.001.
> > <img alt="Capture" width="664" src="https://user-images.githubusercontent.com/30133945/69373556-11a43280-0c72-11ea-9fed-bb56b9090a12.PNG">
> 
> The problem is that linear_damp and angular_damp should be from 0 to 1, as stated in the documentation. Maybe the docs are wrong, I don't know.

I just read the code,the code shows that the range is  0-100, where you find the documation that shows is from 0 to 1?

**Comment by Jummit** [comment]
http://docs.godotengine.org/en/latest/classes/class_area2d.html#class-area2d-property-linear-damp
