### ISSUE TITLE
Weird behavior of 2D skeleton with atlas textures

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33674]
**Godot version:**
3.2 beta1

**Issue description:**
Not sure if the title describes it correctly, but I noticed a VERY strange behavior regarding a rigged 2D skeleton, using Polygon2Ds with single texture.

When I have two models on the screen and a Sprite 2D, all of them using the same texture (with models using Polygon2Ds and Sprite using region), the models break in different ways. When I make any of the objects invisible (strangely, including the Camera2D), it causes different effects. Just look at the GIF.
![epuk91nQTJ](https://user-images.githubusercontent.com/2223172/69007778-96294500-0942-11ea-8259-cee7beff0fd9.gif)

Notice how the knight to the right loses his head when the severed arm is visible. Also there's this weird floating leg at the bottom happening only if both knights are visible.

**Minimal reproduction project:**
[KnightReprodudction.zip](https://github.com/godotengine/godot/files/3855567/KnightReprodudction.zip)

**Comment by shylicks** [comment]
I really wish more was being done with this bug, but I'm new here and probably can't help much. If I had to guess, it looks like a matrix initialization bug when the renderer uses the same texture. The Sprite2D sets a region, and then the next shape drawn (possibly the next frame) is repositioned using that region's offset. Similarly, the camera's matrix affects the next shape drawn somehow.

It's interesting that the red knight being disabled fixes all issues. Maybe it happens because two skeleton rigs with the same texture are rendered at the same time, and it incorrectly thinks they are the same rig?

**Comment by JohnMeadow1** [comment]
I have remade every polygon for the character, to see when the problem appears. 
And it is all fine until you need to set z-index on polygons. I managed to record this behavior on run-time using remote.
![z-index-error](https://user-images.githubusercontent.com/23294139/70667186-89152280-1c70-11ea-8dc1-4d5289cac621.gif)

This is a bit more difficult to replicate in editor if all polygons have z-index set to 0

**Comment by JohnMeadow1** [comment]
Another unexpected behavior happens if you disable visibility of affected Polygon2D, then the bug finds another victim, and other Polygon2D glitches out. Looks like an issue with sorting that somehow affects positions . . . ?

**Comment by KoBeWi** [comment]
> Looks like an issue with sorting that somehow affects positions . . . ?

Everything is possible in the magical world of rendering 🌈

btw, when I tried to track this issue in the source, I discovered that it happens only if polygons have skeleton attached. I then traced it as far as to rasterizer and gave up on looking further :/

**Comment by tpwrules** [comment]
I ran into this bug also I think, where having a non-zero Z index on my Polygon2D with a skeleton applied an unexpected offset during runtime. [My hacky fix](https://github.com/tpwrules/skgame/blob/45062598b87a4e6a2c118d1a6c6cd0e49caa56b4/the_game/player/graphics.gd#L1) was to automatically move the Polygon2D and its skeleton into a viewport, then render that into a ViewportContainer in place of the original object. It works great, but there is probably some performance impact.

**Comment by JohnMeadow1** [comment]
Can't use your workaround, as my character has about 30 different parts as Polygon2D, but thanks for sharing. Will have to wait for the fix a bit more.
