### ISSUE TITLE
Weird GLES3 editor render behavior, when added MeshInstance

### ISSUE THREAD

**Issue by imjp94** [godotengine/godot#33680]
**Godot version:**
3.1.1.stable.official-win64

**OS/device including version:**
Windows 10 Home, Version 1903

**Issue description:**
Adding/Activate MeshInstance in GLES3 editor cause rendering problem
![gles3](https://user-images.githubusercontent.com/11486079/69010758-b5a18b80-099d-11ea-9fd7-7d2b31005b2c.gif)

GLES2 works as usual
![gles2](https://user-images.githubusercontent.com/11486079/69010883-31e89e80-099f-11ea-9a02-297ca9eb1cc8.gif)

**Steps to reproduce:**
GLES3 editor on any project with default project & editor setting

**Comment by Calinou** [comment]
@imjp94 Which graphics card do you have?

**Comment by imjp94** [comment]
@Calinou I was testing with NVIDIA GeForce GTX 1060
By the way, I just tested it on Godot 3.0.6 and the problem still persist, seem like its really hardware related.

**Comment by KoBeWi** [comment]
> I was testing with NVIDIA GeForce GTX 1060

Me too and I can't reproduce it.

**Comment by imjp94** [comment]
Fixed, it was actually caused by my multi-display & single graphic card setup. 

My primary display is not utilizing graphic card, thus, the OpenGL ES 3.0 was actually rendered by my cpu graphic.
![log](https://user-images.githubusercontent.com/11486079/69265422-319d0d00-0c04-11ea-9e0d-6839ab703c20.png)
