### ISSUE TITLE
Runtime error: index 1 out of bounds for type 'Elem [1]' in compressed_translation.cpp

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#33696]
**Godot version:**
3.2.beta.custom_build. fea3890e1

**OS/device including version:**
Ubuntu 19.10
**Issue description:**
```
core/compressed_translation.cpp:252:20: runtime error: index 1 out of bounds for type 'Elem [1]'
core/compressed_translation.cpp:263:21: runtime error: index 1 out of bounds for type 'Elem [1]'
core/compressed_translation.cpp:263:51: runtime error: index 1 out of bounds for type 'Elem [1]'
core/compressed_translation.cpp:266:70: runtime error: index 1 out of bounds for type 'Elem [1]'
core/compressed_translation.cpp:266:40: runtime error: index 1 out of bounds for type 'Elem [1]'
core/compressed_translation.cpp:272:32: runtime error: index 1 out of bounds for type 'Elem [1]'
core/compressed_translation.cpp:273:113: runtime error: index 1 out of bounds for type 'Elem [1]'
core/compressed_translation.cpp:273:70: runtime error: index 1 out of bounds for type 'Elem [1]'
core/compressed_translation.cpp:273:40: runtime error: index 1 out of bounds for type 'Elem [1]'
```
**Steps to reproduce:**
1. Add if conditions and put breakpoint inside it in provided files and lines e.g.
```
if (i > 0){
	ERR_PRINT("PUT_BREAKPOINT_HERE");
}
if (bucket.elem[i].key == h) {

	idx = i;
	break;
}
```
or compile Godot with llvm and ubsan sanitizer support `scons use_llvm=yes use_ubsan=yes`

or compile Godot from this branch https://github.com/qarmin/godot/tree/bb with ubsan sanitizer support `use_ubsan=yes`(this will need probably gcc 9 or clang 9)
2. Import and run minimal project

**Minimal reproduction project:**
https://github.com/alex-evelyn/Sweet-Tea/archive/master.zip

**Comment by akien-mga** [comment]
That's not really a minimal project...
I can't reproduce with the given step(s?), but I do get:
```
ERROR: set_locale: Invalid locale: mz.
   At: core/translation.cpp:851.
```
And import errors in the editor due to the locale not being found.

**Comment by qarmin** [comment]
I updated steps to reproduce.
This is not my project and I think that creating new with only few files will take more time than fixing issue.

**Comment by qarmin** [comment]
Another project with same problem - https://github.com/GDQuest/godot-power-pitch, but this time only opening projects show this error(also need ubsan support)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by qarmin** [comment]
I can't reproduce this errors with 3.2.4 beta 2
