### ISSUE TITLE
'fatal error: openssl/opensslconf.h: No such file or directory' while building x11 32-bit export templates

### ISSUE THREAD

**Issue by nepitard** [godotengine/godot#3369]
Location of opensslconf.h file is /usr/include/x86_64-linux-gnu/openssl/ so builder can't find it.

**Comment by akien-mga** [comment]
What distro are you building on? It seems quite weird to me to have an arch-dependent path for headers, usually Debian-based distros will use ```/usr/lib/x86_64-linux-gnu``` for binary libraries and ```/usr/include``` for arch-independent headers.

**Comment by akien-mga** [comment]
Ah actually I checked and it looks like Debian does put this very header in an arch-dependent path, I guess it's generated at build time and contains arch-dependent info (like the path to the .so or something): https://packages.debian.org/sid/amd64/libssl-dev/filelist

**Comment by akien-mga** [comment]
I would say that it's a Debian bug though, as they should expose this path in the pkgconfig file. They can't expect all downstream projects to hardcode arch-specific paths in their buildsystem, we rely on pkgconfig for precisely that purpose: https://github.com/godotengine/godot/blob/master/platform/x11/detect.py#L134-L135

Can you check the contents of /usr/lib/x86_64-linux-gnu/pkgconfig/openssl.pc, and file a bug report upstream to Debian (or *buntu if it's what you're using, they would likely handle getting a fix upstream to Debian) if it lacks a mention to ```/usr/include/x86_64-linux-gnu``` in the include flags?

**Comment by nepitard** [comment]
Solved this problem by installing libssl-dev:i386. However there are some i386 libraries required to compile x11 templates that conflict with each other(libfreetype6-dev:i386, libgl1-mesa-dev:i386, libglu1-mesa-dev:i386, ibpng12-dev:i386, mesa-common-dev:i386). Can't build 32-bit x11 templates on 64-bit ubuntu.

**Comment by nepitard** [comment]
"Note that cross compiling for the opposite bits (64/32) as your host platform in linux is quite difficult and might need a chroot environment."
Got it. Sorry for disturbing.
