### ISSUE TITLE
Mono: Data template directory not found

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#33699]
**Godot version:**
98caeb635
**OS/device including version:**
Windows 10 1903
**Issue description:**
Gives me this error when trying to export for windows:
![image](https://user-images.githubusercontent.com/1850856/69041771-badff400-09f8-11ea-990c-5718f012e7fd.png)
All files are properly placed and the data folders are properly named (to my understanding):
![image](https://user-images.githubusercontent.com/1850856/69041833-dc40e000-09f8-11ea-819a-0d17cb57c808.png)

**Comment by zaksnet** [comment]
Looks like it was looking for `data.mono.windows.64.release_debug` instead:
![image](https://user-images.githubusercontent.com/1850856/69042479-e9aa9a00-09f9-11ea-8714-70fa6751b44c.png)
is this desired? The release folder inside the binary is named `data.mono.windows.release` not `data.mono.windows.64.release_debug`

**Comment by akien-mga** [comment]
`debug ? ".release_debug" : ".release"` means that `release_debug` is used for debug builds, so it's the `debug` one that you should rename, not the `release` one.

That's indeed expected, `release_debug` is the target used for "debug" templates (they're still optimized like release builds, but with added debug code - versus the pure `debug` target which is unoptimized, and thus only relevant for engine developers).

**Comment by zaksnet** [comment]
> `debug ? ".release_debug" : ".release"` means that `release_debug` is used for debug builds, so it's the `debug` one that you should rename, not the `release` one.
> 
> That's indeed expected, `release_debug` is the target used for "debug" templates (they're still optimized like release builds, but with added debug code - versus the pure `debug` target which is unoptimized, and thus only relevant for engine developers).

Alright, just a side note that the folders should also be named properly when compiling. I wouldn't  of known this without looking at the source code :grimacing:

**Comment by akien-mga** [comment]
What command did you use to build your debug template?

**Comment by zaksnet** [comment]
> What command did you use to build your debug template?

scons p=windows target=debug tools=no module_mono_enabled=yes disable_3d=yes disable_advanced_gui=yes use_lto=yes -j6 
Should i change target to debug_release? 
Also, after changing `debug` folder as you suggested i end up with `data.mono.windows.64.release` and `data.mono.windows.64.release_debug` which gives me the same error as before

**Comment by akien-mga** [comment]
You should use `target=release_debug`, and the folder should be properly named out of the box. As mentioned, `target=debug` is only for engine developers, the debug export templates are compiled with `target=release_debug`.

@neikeq Looks like you don't support exporting `target=debug` binaries for now. The code should likely check for both `release_debug` (default) and `debug` as fallback (which means that one could export a `target=debug` binary together with the `target=release_debug` data, but I guess that might be fine?).

**Comment by akien-mga** [comment]
>  It searches for `data.mono.windows.64.release_debug` and `data.mono.windows.64.debug`

It shouldn't, as per the code you linked. It's either `data.mono.windows.64.release` (release template) or `data.mono.windows.64.release_debug` (debug template).

**Comment by zaksnet** [comment]
> You should use `target=release_debug`, and the folder should be properly named out of the box. As mentioned, `target=debug` is only for engine developers, the debug export templates are compiled with `target=release_debug`.
> 
> @neikeq Looks like you don't support exporting `target=debug` binaries for now. The code should likely check for both `release_debug` (default) and `debug` as fallback (which means that one could export a `target=debug` binary together with the `target=release_debug` data, but I guess that might be fine?).

I guess the documentation on this should be fixed:
`# Build temporary binary
scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
# Generate glue sources
bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue

### Build binaries normally
# Editor
scons p=windows target=release_debug tools=yes module_mono_enabled=yes
# Export templates
scons p=windows target=debug tools=no module_mono_enabled=yes
scons p=windows target=release tools=no module_mono_enabled=yes`
The target for export templates there is `debug` instead of `release_debug`

**Comment by akien-mga** [comment]
Indeed, that part of the documentation is wrong. All other platform docs use `release_debug` for the debug template.

**Comment by zaksnet** [comment]
> > It searches for `data.mono.windows.64.release_debug` and `data.mono.windows.64.debug`
> 
> It shouldn't, as per the code you linked. It's either `data.mono.windows.64.release` (release template) or `data.mono.windows.64.release_debug` (debug template).

Recompiling with `release_debug` seems to have fixed this :relaxed:. My data folders now are `data.mono.windows.64.release` and `data.mono.windows.64.release_debug`

**Comment by zaksnet** [comment]
> Indeed, that part of the documentation is wrong. All other platform docs use `release_debug` for the debug template.

So i guess its only a documentation issue now? Also it used to search for `debug` instead of `release_debug`. A few versions back i was compiling with `debug`. I made a pull request the docs change.

**Comment by neikeq** [comment]
We should already support both `debug` and `release_debug` as of de7c2ad21b4cc2d889a5aeda64ead962036d2aa4: https://github.com/godotengine/godot/commit/de7c2ad21b4cc2d889a5aeda64ead962036d2aa4#diff-452afcfd0c57cc1e4800975b71fd2249R148

**Comment by akien-mga** [comment]
> We should already support both `debug` and `release_debug` as of [de7c2ad](https://github.com/godotengine/godot/commit/de7c2ad21b4cc2d889a5aeda64ead962036d2aa4): [de7c2ad#diff-452afcfd0c57cc1e4800975b71fd2249R148](https://github.com/godotengine/godot/commit/de7c2ad21b4cc2d889a5aeda64ead962036d2aa4#diff-452afcfd0c57cc1e4800975b71fd2249R148)

Ah great, so this is fixed in the latest master branch then.

**Comment by zaksnet** [comment]
> We should already support both `debug` and `release_debug` as of [de7c2ad](https://github.com/godotengine/godot/commit/de7c2ad21b4cc2d889a5aeda64ead962036d2aa4): [de7c2ad#diff-452afcfd0c57cc1e4800975b71fd2249R148](https://github.com/godotengine/godot/commit/de7c2ad21b4cc2d889a5aeda64ead962036d2aa4#diff-452afcfd0c57cc1e4800975b71fd2249R148)

Shouldn't there be a check for `data.mono.windows.64.debug` forlder also then? When i compiled with `debug` flag the data folder was named `data.mono.windows.64.debug`.
![image](https://user-images.githubusercontent.com/1850856/69052691-56309380-0a10-11ea-84e2-2f343c22b226.png)
