### ISSUE TITLE
GLES2 GL_RGB buffer breaks OpenVR

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#33705]
**Godot version:**
Commit # 35444576ff684aebb0133d46495be85d3d434900 but seems to have changed in Godot 3.2 some time ago

**OS/device including version:**
Tested on Windows, but any OpenVR capable OS will exhibit this

**Issue description:**
In Godot 3.2 the code here was changed:
https://github.com/godotengine/godot/blob/master/drivers/gles2/rasterizer_storage_gles2.cpp#L4587
We now create a GL_RGB buffer if we're not using a transparent background. In Godot 3.1 we always created an GL_RGBA buffer regardless. 

When sending the render output to OpenVR, GL_RGB is not a supported format, likely because the 24bit color buffer is more inefficient then a 32bit color buffer (data alignment wise)

I'm wondering if there is a good reason to use GL_RGB here other than slightly less memory usage (if the hardware doesn't decide to use a 32bit based buffer anyway)?

I'd hate to introduce a new switch to force GL_RGBA...

While I think its unrelated it is also interesting to note that the texture object returned for the viewport always assumes GL_RGBA:
https://github.com/godotengine/godot/blob/master/drivers/gles2/rasterizer_storage_gles2.cpp#L4679

**Steps to reproduce:**
Run the OpenVR demo project in GLES2 mode (https://github.com/godotvr/godot_openvr)

**Minimal reproduction project:**
https://github.com/godotvr/godot_openvr

**Comment by akien-mga** [comment]
>  Commit # 3544457 but seems to have changed in Godot 3.2 some time ago

Wrong commit hash?

**Comment by BastiaanOlij** [comment]
@akien-mga nah, thats the commit i'm on, last pulled a few days ago :)

Got feedback from Valve that GL_RGB8 is supported, I remember that the internal format should include the bit indicator, ran into problems with that before. I guess GL_RGB doesn't always resolve properly.

Just made the change and it seems to work like a charm. Need others to verify :)

**Comment by clayjohn** [comment]
That sounds great! I just recently did that with the depth texture to make it run on more Android devices. Glad to hear the solution was so simple!
