### ISSUE TITLE
Vector2 constants bug with C#

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33712]
**Godot version:**
3.2 beta 1

**OS/device including version:**
Win10 64 Home

**Issue description:**
Using the Vector2.Right (and Left and other constants) constant in a case (of a switch) indicates the error "A constant value was expected."

**Steps to reproduce:**
Just write this code:

        Vector2 movedir = new Vector2(0, 0);

        switch( movedir )
        {
            case Vector2.Right:
                break;
        }

**Minimal reproduction project:**
[testVector2Const.zip](https://github.com/godotengine/godot/files/3859637/testVector2Const.zip)

**Comment by bojidar-bg** [comment]
Probably related to the fact that `Vector*.Right` is defined as a static property and not as a constant:
https://github.com/godotengine/godot/blob/17ee8d0465726fc7b6b657a5d14bda46565edf33/modules/mono/glue/Managed/Files/Vector3.cs#L347

**Comment by aaronfranke** [comment]
This is not possible for Godot to fix, it's a C# limitation. One, switch statements only work with constants, and two, only C# built-in types can be constant.

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constants 

>Only the C# built-in types (excluding System.Object) may be declared as const. For a list of the built-in types, see Built-In Types Table. User-defined types, including classes, structs, and arrays, cannot be const. ...

> C# does not support const methods, properties, or events.

Instead, consider using `if () {} else if () {}` etc.

**Comment by Torguen** [comment]
> This is not possible for Godot to fix, it's a C# limitation. One, switch statements only work with constants, and two, **only C# primitive types can be constant.**
> 
> https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constants
> 
> > Only the C# built-in types (excluding System.Object) may be declared as const. For a list of the built-in types, see Built-In Types Table. User-defined types, including classes, structs, and arrays, cannot be const. ...
> 
> > C# does not support const methods, properties, or events.
> 
> Instead, consider using `if () {} else if () {}` etc.

That would be the reason for the error.
Vector2.Right is a constant of the Vector2 class of godot and is not a primitive type of C # so C # does not recognize it as a constant.

**Comment by Torguen** [comment]
> Probably related to the fact that `Vector*.Right` is defined as a static property and not as a constant:
> https://github.com/godotengine/godot/blob/17ee8d0465726fc7b6b657a5d14bda46565edf33/modules/mono/glue/Managed/Files/Vector3.cs#L347

I guided myself by the information of the Vector2 class in the official DOC, there it is indicated as constant:

![1](https://user-images.githubusercontent.com/19652075/69224037-1d153200-0b7c-11ea-9a9e-89b5c8e38dfa.png)

**Comment by aaronfranke** [comment]
Constants in GDScript are not the same as constants in C#. [Structs cannot be constants in C#](https://stackoverflow.com/questions/4590796/why-cant-structs-be-declared-as-const). There is nothing that we can do to change this. For documenting this, I opened https://github.com/godotengine/godot-docs/pull/4212

**Comment by Ivinia** [comment]
FYI, in C#, try using readonly instead of const in this situation:

readonly Vector2 movedir = new Vector2(0, 0);
