### ISSUE TITLE
Camera and raycast previews don't show in subscenes

### ISSUE THREAD

**Issue by Cobradabest** [godotengine/godot#3371]
When I import a scene with a camera and/or a raycast, the previews for both disappear, I recreated this by using Oxrock's raycast demo, by converting the player node into a subscene and then reimporting it after deleting the original. I've been experiencing this in a game I'm developing as well.
Before:
![godot engine - raydemo - new_scene scn - _107](https://cloud.githubusercontent.com/assets/8548727/12380671/7fe97af2-bd70-11e5-9ec8-f0303d66c6cd.png)

After (as a subscene):
![godot engine - raydemo - new_scene scn_108](https://cloud.githubusercontent.com/assets/8548727/12380672/816cc302-bd70-11e5-9f41-3477270fc707.png)

Link to Demo: https://github.com/oxrock/Godot-camera-raycasting-demo

Version used: Linux x86.64, compiled from source the same day as I posted this.

**Comment by bojidar-bg** [comment]
Does this happen when the raycast is a sibling of the camera, instead of a direct child?

**Comment by oxrock** [comment]
the raycast can be independent of the camera, the problem persists.

**Comment by DualMatrix** [comment]
Tested on master, both camera and raycast are visible now.

**Comment by Chaosus** [comment]
@DualMatrix Thanks !

**Comment by Chaosus** [comment]
Hmm.. I think it still could be issue for 2.x version, so I better reopen it.. @DualMatrix if you have free time can you download a 2.1.5 and check if the problem exist ?

**Comment by akien-mga** [comment]
I don't think it will be fixed in 2.1 by now, only critical bug fixes will be considered for that platform. Closing as fixed in 3.1 (potentially 3.0 too).
