### ISSUE TITLE
Importing file with name which contains number bigger than int64_t show error

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#33713]
**Godot version:**
Godot 3.2 beta 1
**OS/device including version:**
Ubuntu 19.10
**Issue description:**
Godot when compare two file names which contains big number, trying to convert it to int64_t which can overflow  
```
ERROR: to_int: Cannot represent 12541241242142142152352352353453446346346 (kopia).jpg as integer, provided value is too big.
   At: core/ustring.cpp:2166.
ERROR: to_int: Cannot represent 12541241242142142152352352353453446346346.jpg as integer, provided value is too big.
   At: core/ustring.cpp:2166.
```
![Zrzut ekranu z 2019-11-18 18-32-41](https://user-images.githubusercontent.com/41945903/69075996-cfd97900-0a32-11ea-920a-fcd96a620b41.png)

**Minimal reproduction project:**
[mport.zip](https://github.com/godotengine/godot/files/3859883/mport.zip)

**Comment by aaronfranke** [comment]
Perhaps it should fall back to lexicographical comparison, or always use lexicographical comparison? Is there a reason that we need to convert file names to integers?
