### ISSUE TITLE
[CLOSED] Opensimplexnoise on Android

### ISSUE THREAD

**Issue by MarvinKehl** [godotengine/godot#33726]
Hello,

I run into a problem lately with exporting a game prototype to android which is using opensimplexnosie for an terrain editor. 

While the app works quite well under GLES3 it won´t start under GLES2. Trying to isolate the problem I found out, that the app works until the opensimplexnoise is implemented.

Is this an issue with the different imports (ETC2 and ETC) or did I run into a bug?

Thanks for your answers.

**Comment by Zylann** [comment]
Is your app not starting because of the use of `OpenSimplexNoise` alone, or `NoiseTexture`?

**Comment by MarvinKehl** [comment]
No, only OpenSimplexNoise, this is the part of the code, that breaks my game:

    func _ready():

	start = 0
	player = get_node("Player")

	randomize()

	# Instantiate
	noise = OpenSimplexNoise.new()

	# Configure
	noise.seed = randi()
	noise.octaves = 1
	noise.period = planesize*10
	#noise.persistence = 1
	water_height = .5


	get_node("Player").translation = Vector3(0,(noise.get_noise_2d(0, 0)+1)/2*max_height+get_node("Player").radius,0)

	water = get_node("map/water")
	water.translation.y = water_height
	water.visible = false

**Comment by MarvinKehl** [comment]
Oh, my Smartphone ist the Nokia 7 plus by the was.
I also tried it in the Motorola Moto X2, but I cant get any App running in this device

**Comment by MarvinKehl** [comment]
Hello,
I made a mistake, the Opensimplexnoise wasnt the problem.

My App crashes on android, because I create my terrain with gdscript and give them collision planes with create_convex-collision.
It seams that this function as well as the create_trimesh_collision isnt working with the standard android exporter.
Because I dont know how to fix it, I will continue with GLES3, thank you for your answer.
