### ISSUE TITLE
Mono: Export fails with "C# export failed"

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#33725]
**Godot version:**
ab8135315
**OS/device including version:**
Windows 10 1903
**Issue description:**
Exported game crashes when i try to run it:
```
ERROR: Failed to load one of the API assemblies.
   At: modules\mono\mono_gd\gd_mono.cpp:945
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] GDMono::_load_api_assemblies (C:\Users\Zak\Documents\GodotSourceCode\modules\mono\mono_gd\gd_mono.cpp:945)
[1] GDMono::initialize_load_assemblies (C:\Users\Zak\Documents\GodotSourceCode\modules\mono\mono_gd\gd_mono.cpp:423)
[2] ScriptServer::init_languages (C:\Users\Zak\Documents\GodotSourceCode\core\script_language.cpp:176)
[3] Main::setup2 (C:\Users\Zak\Documents\GodotSourceCode\main\main.cpp:1331)
[4] Main::setup (C:\Users\Zak\Documents\GodotSourceCode\main\main.cpp:1111)
[5] widechar_main (C:\Users\Zak\Documents\GodotSourceCode\platform\windows\godot_windows.cpp:152)
[6] _main (C:\Users\Zak\Documents\GodotSourceCode\platform\windows\godot_windows.cpp:186)
[7] main (C:\Users\Zak\Documents\GodotSourceCode\platform\windows\godot_windows.cpp:196)
[8] __scrt_common_main_seh (d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[9] BaseThreadInitThunk
-- END OF BACKTRACE --
```

Also when exporting the game i get the folowing error:
![image](https://user-images.githubusercontent.com/1850856/69121948-321f9180-0aa6-11ea-9c18-f4e47050551d.png)
But i think the export was completed since all files are in place and that message has something to do with cleaning up temp files.
![image](https://user-images.githubusercontent.com/1850856/69121996-58453180-0aa6-11ea-9b5e-0b4d24863918.png)

**Comment by akien-mga** [comment]
Steps to reproduce?

You're obviously using a custom build since you reference a specific commit sha, which means that you built templates yourselves, which means that it's important to tell us how and how you're using them.

**Comment by zaksnet** [comment]
```
# Build temporary binary
scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
# Generate glue sources
bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue

### Build binaries normally
# Editor
scons p=windows target=release_debug tools=yes module_mono_enabled=yes
# Export templates
scons p=windows target=debug tools=no module_mono_enabled=yes
scons p=windows target=release tools=no module_mono_enabled=yes
```
I'm always using the steps from the [website](https://docs.godotengine.org/en/3.1/development/compiling/compiling_with_mono.html). This time i used `scons p=windows target=release_debug tools=yes module_mono_enabled=yes` instead of `target=debug` for the export templates though.

I have tried recompiling it and generating the glue code again but still the same issue.
Anyway, just tested it with `Mono beta 1` and it seems to work. I will assume that the error is something with my compilation process and close this issue. Also, I'm sticking with the official builds for now (save us all the headache!).

**Comment by akien-mga** [comment]
I can reproduce the issue in the latest master branch, which is weird as it worked yesterday when I tested WebAssembly exports...

Any export, whether through the export manager or one-click deploy, seems to end with "C# export failed" and no details.

**Comment by zaksnet** [comment]
> I can reproduce the issue in the latest master branch, which is weird as it worked yesterday when I tested WebAssembly exports...
> 
> Any export, whether through the export manager or one-click deploy, seems to end with "C# export failed" and no details.
[ExportPlugins.cs](https://github.com/godotengine/godot/blob/master/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs)
```
        public override void _ExportEnd()
        {
            base._ExportEnd();

            string aotTempDir = Path.Combine(Path.GetTempPath(), $"godot-aot-{Process.GetCurrentProcess().Id}");

            if (Directory.Exists(aotTempDir))
                Directory.Delete(aotTempDir, recursive: true);

            // TODO: Just a workaround until the export plugins can be made to abort with errors
            if (string.IsNullOrEmpty(maybeLastExportError)) // Check empty as well, because it's set to empty after hot-reloading
            {
                string lastExportError = maybeLastExportError;
                maybeLastExportError = null;

                GodotSharpEditor.Instance.ShowErrorDialog(lastExportError, "C# export failed");
            }
        }
```

`// Check empty as well, because it's set to empty after hot-reloading` I'm not sure how usefull it is to display an error dialog if the error is empty 😕

**Comment by neikeq** [comment]
The error message when exporting seems to be false positive. The game is actually exported correctly. There's a problem with the WASM export templates though which @akien-mga and I are discussing how to fix right now.
