### ISSUE TITLE
Emscripten 1.39.1+ javascript export fails: IDBFS is not defined

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#33724]
**Godot version:**
cc3b7d2ee

**OS/device including version:**
10

**Issue description:**
custom emscripten build
export javascript and start in chrome
results in error:
exception thrown: ReferenceError: IDBFS is not defined,ReferenceError: IDBFS is not defined
line 58 in
platform\javascript\javascript_main.cpp uses IDBFS but it's nowhere defined (should be in emscripten)

**Steps to reproduce:**
scons platform=javascript target=release_debug tools=no optimize=size use_lto=yes -j8 javascript_eval=no

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
I can reproduce it on `1.39.3-upstream` too, now testing with fastcomp.

You mention 1.39.1+, did you test different versions to narrow it down as a regression in 1.39.1?
If so it might be linked to #33374 and the upstream change that caused it as discussed in emscripten-core/emscripten#9806.

**Comment by akien-mga** [comment]
Same issue with `1.39.3-fastcomp`, so at least it doesn't seem related to the compiler backend.

**Comment by akien-mga** [comment]
It's the same issue as emscripten-core/emscripten#9827.

It seems to be an intended change, we now need to link those manually: https://github.com/emscripten-core/emscripten/blob/incoming/ChangeLog.md#v1391-10302019

I guess we can't assume that patch releases are safe with Emscripten, we should always double check the changelog on any update.
