### ISSUE TITLE
Parameter blend mode incorrect on mobile (GLES2 CPUPArticles in 3D)

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#33730]
**Godot version:**
3.1 and 3.1.2 rc1

**OS/device including version:**
Android

**Issue description:**
Using GLES2 and CPUParticles with materials override seam to use wrong blend mode on mobile (Android at least). If I leave mix as blending particles on pc I have the right transparency, on mobile are shown with a black background.

**Steps to reproduce:**
Create CPUParticle in a 3D environment with GLES2. Create a material override and flag transparency, unshaded, vertex color as albedo and billboard_mode to the particle. Set as albedo a texture with alpha channel, on PC you can see the right result, on mobile you can't see transparent.

**Comment by clayjohn** [comment]
Can you upload an image of what you are describing?

**Comment by grevius5** [comment]
Here it is:
![PC Version](https://user-images.githubusercontent.com/16955149/69162441-f8be4480-0aec-11ea-9a94-87e985122c2a.png)
![Android version](https://user-images.githubusercontent.com/16955149/69162490-0a9fe780-0aed-11ea-964f-847634ae736c.jpg)

**Comment by clayjohn** [comment]
Thank you. That is very helpful :)

This is the result of using the ETC compression algorithm to compress your textures. ETC textures do not support the alpha channel. For now, you can either provide a second alpha texture to use for your material, or you can import your textures without VRAM compression.

A bug report for this has already been made and we are exploring potential solutions here: https://github.com/godotengine/godot/issues/33178
