### ISSUE TITLE
Visual anomaly with the values of the "Ruler" tool

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33732]
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
Win10 64 Home

**Issue description:**
Some numbers are not drawn in full when using the "Ruler" tool.

**Steps to reproduce:**
1 - Activate the "Ruler" tool
2 - Press the left mouse button and observe the drawing of the values that appear.
3 - Some values are not drawn correctly and the upper part of the number is missing.

![1](https://user-images.githubusercontent.com/19652075/69150534-2b5e4200-0ad9-11ea-999d-4e11ae22b770.png)

**Minimal reproduction project:**
Any empty project.

**Comment by groud** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
Looks more like font/rendering issue than with ruler.

**Comment by tom-jk** [comment]
Testing on linux mint 18.3.
Can reproduce in 3.2.beta1, 3.2.3.rc3

If you start using the ruler, then (without releasing the mouse) zoom in or out with mousewheel, you'll see that the text looks fine on every zoom level _except_ the one it was started on. If you zoom to some other level where it looks ok, then release the mouse and start a new ruler, this ruler will look bad on _that_ zoom level but fine on any other (including the level where the first ruler looked bad).

Note: might be easier to test starting on/around 100% zoom (maybe floating-point rounding keeps zoom level from landing exactly on the same amount for other values). Especially easier on new versions that snap to 100%, 200%, 400% etc. Also at nearest zoom (12800%) but oddly not at farthest (0.8%).

**Comment by Torguen** [comment]
This does not happen in v3.5.beta1.official [b9b23d222]
