### ISSUE TITLE
EditorScript 's compile errors are not logged in Console

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#3373]
When writing an script to run in the editor bugs like undefined vars are not logged and when trying to run only feedback is a reminder to use tool keyword, same happens if you try to inherit another class instead of EditorScript.

Error logs are in godot's command window (if std-out is enabled)

**Comment by akien-mga** [comment]
Does this still happen in 2.1-beta?

**Comment by MarianoGnu** [comment]
Yes

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by bojidar-bg** [comment]
That would be really nice to fix anyway. Having to keep a terminal open while debugging tool scripts is not a very nice experience.

**Comment by MarianoGnu** [comment]
Moved to milestone 3 to make sure this is not missed, can probably be cherypicked for 2.2
