### ISSUE TITLE
Mono: Game crash when setting Physics > 2D > Thread model to Multi-Threading

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#33735]
**Godot version:**
Godot Mono Beta.1
**OS/device including version:**
Windows 10 1903
**Issue description:**
While doing a physics stress test (snow ❤️) setting Thread model for physics to `Multi-Threading` in Godot (Mono) causes the game  to crash with the following error:
![image](https://user-images.githubusercontent.com/1850856/69156061-8436d600-0aeb-11ea-8c88-30b8d477508e.png)
`ERROR: Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state` which makes no sense and gives no more clues of what might be wrong. I also tried as suggested to change the code to use `call_deffered` and `set_deffered` but it made no difference.
![PhysicsStressTest](https://user-images.githubusercontent.com/1850856/69156223-c3652700-0aeb-11ea-880e-bb2683158c9e.gif)

When running the same project in `Godot 3.1.1 Stable` it does not crash when enabling `Multi-Threading` but also it doesn't seem to be making any difference. CPU usage does not go beyond 30~40% (which is the maximum of the main core i assume).

**Steps to reproduce:**
Run the attached project.
**Minimal reproduction project:**
[Physics stress test.zip](https://github.com/godotengine/godot/files/3864345/Physics.stress.test.zip)

EDIT: Its the same error in 3.1.1. The difference is that the game does not crash (then again Mono version seems to be crashing on every error?)
![image](https://user-images.githubusercontent.com/1850856/69157759-193ace80-0aee-11ea-87e8-3e001279c81e.png)
So this is 2 issues in this post:
- Godot Mono is crashing on every error.
- `ERROR: Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state` when enabling `Physics > 2D > Multi-Threading`
EDIT: Also tried running `queue_free` inside `_physics_process` instead of `_process`. Same error.

**Comment by gururise** [comment]
### Single Threaded Physics on Godot 3.1.1 does not Crash
* No crashes, no error messages.
* CPU Usage is at 100% on the Godot Process.

### Multi Threaded Physics on Godot 3.1.1 does not Crash
* On Linux x64, I get a bunch of these errors:
![image](https://user-images.githubusercontent.com/4380009/69486379-e0f20380-0dff-11ea-9876-4c46712efcae.png)
* CPU Usage is around 115% on Godot Process, so it appears some type of multi-threading is going on.

**Comment by gururise** [comment]
### Godot 3.2 Beta 2 - MONO version crashes:
```
ERROR: bind: Method/Function Failed, returning: ERR_UNAVAILABLE
   At: drivers/unix/net_socket_posix.cpp:390.
Running: /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 --path /home/gene/Documents/Godot/Physics%20stress%20test --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 553816 --position 3328,420
Godot Engine v3.2.beta2.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
 
Mono: Logfile is: /home/gene/.local/share/godot/mono/mono_logs/2019_11_23 16.14.03 (553885).txt
ERROR: body_set_shape_disabled: Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
   At: servers/physics_2d/physics_2d_server_sw.cpp:730.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0xcfef34 - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : (null)
	0xcff2ac - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : (null)
	0xcf1d58 - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : (null)
	0xd01fbe - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : (null)
	0x7f6fab042930 - /usr/lib/libpthread.so.0 : (null)
	0xe3ce97 - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : (null)
	0xe3fb39 - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : (null)
	0xe3fbab - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : mono_object_new
	0x2d7657b - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : _ZN14CSharpLanguage28debug_get_current_stack_infoEv
	0x1775037 - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : _ZN20ScriptDebuggerRemote12_err_handlerEPvPKcS2_iS2_S2_16ErrorHandlerType
	0x12b7d0d - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : _Z16_err_print_errorPKcS0_iS0_S0_16ErrorHandlerType
	0x1667269 - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : _ZN21Physics2DServerWrapMT11thread_loopEv
	0x29a97b5 - /home/gene/Downloads/Godot_v3.2-beta2_mono_x11_64/Godot_v3.2-beta2_mono_x11.64 : _ZN11ThreadPosix15thread_callbackEPv
	0x7f6fab0374cf - /usr/lib/libpthread.so.0 : (null)
	0x7f6faae102d3 - /usr/lib/libc.so.6 : clone

=================================================================
	Telemetry Dumper:
=================================================================
Thread 0x7f6f878f9700 may have been prematurely finalized* Assertion at mono-threads.c:650, condition `info' not met, function:mono_thread_info_current,
```

**Comment by neikeq** [comment]
Can you still reproduce this with 3.2 RC1?

**Comment by gururise** [comment]
> Can you still reproduce this with 3.2 RC1?

Yes. Under 3.2 RC1 (Mono x64 Linux): 
`Godot Engine v3.2.rc1.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
 
Mono: Logfile is: /home/gene/.local/share/godot/mono/mono_logs/2020_01_18 10.28.25 (533276).txt
ERROR: body_set_shape_disabled: Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
   At: servers/physics_2d/physics_2d_server_sw.cpp:730.
ERROR: body_set_shape_as_one_way_collision: Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
   At: servers/physics_2d/physics_2d_server_sw.cpp:739.
ERROR: mono_log_callback: Mono: FATAL ERROR, ABORTING! Logfile: '/home/gene/.local/share/godot/mono/mono_logs/2020_01_18 10.28.25 (533276).txt'.
   At: modules/mono/mono_gd/gd_mono_log.cpp:86.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================`
Log File
[2020_01_18 10.28.25 (533276).txt](https://github.com/godotengine/godot/files/4081405/2020_01_18.10.28.25.533276.txt)

**Comment by neikeq** [comment]
It's a different crash now. Mono's debugger agent has an assertion that doesn't take into account the possibility of a thread attaching, detaching and then attaching again. Looks like Unity had the same issue as they patched it in their fork of Mono: https://github.com/Unity-Technologies/mono/commit/995768f7dc3af7b3d19fcedd1244087a4a89bc5c

**Comment by akien-mga** [comment]
Test builds with Mono rebuilt using the patch mentioned by @neikeq:

- Linux: https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/Godot_v3.2-mono-tls-test_mono_x11_64.zip
- Windows: https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/Godot_v3.2-mono-tls-test_mono_win64.zip
- macOS: https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/Godot_v3.2-mono-tls-test_mono_osx.64.zip

The Linux build does fix the crash for me.

**Comment by zaksnet** [comment]
> Test builds with Mono rebuilt using the patch mentioned by @neikeq:
> 
> * Linux: https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/Godot_v3.2-mono-tls-test_mono_x11_64.zip
> * Windows: https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/Godot_v3.2-mono-tls-test_mono_win64.zip
> * macOS: https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/Godot_v3.2-mono-tls-test_mono_osx.64.zip
> 
> The Linux build does fix the crash for me.

This commit seems to fix the crash for me. I will wait for @gururise to confirm also before closing as hes been spending more time on this.

**Comment by akien-mga** [comment]
> I'm not sure what that commit does, but i'm concerned as to why the performance is exactly the same with Multi-Threading and with single threading. Is multi threading actually working for physics? I might be opening a new issue with some test projects and videos to demonstrate the case.

That's a different issue though. And the example project has so many errors that performance tanks because of printing errors to the Output panel/terminal.

**Comment by zaksnet** [comment]
> > I'm not sure what that commit does, but i'm concerned as to why the performance is exactly the same with Multi-Threading and with single threading. Is multi threading actually working for physics? I might be opening a new issue with some test projects and videos to demonstrate the case.
> 
> That's a different issue though. And the example project has so many errors that performance tanks because of printing errors to the Output panel/terminal.

Well, looking back at the issue posted, my original problem was not the crash, it was the errors. The code is minimal and there is no indication as to what might be causing the errors. Also they seem to be linked to multi-threading which would make sense. I'd appreciate re-opening and i will strike-through the `Mono` part with the commit.

**Comment by neikeq** [comment]
@zaksnet Can that be considered the same as #26518?

**Comment by zaksnet** [comment]
@neikeq Yeah sure I'm good with that.

**Comment by gururise** [comment]
Can confirm new build does not crash using multi-threaded 2D physics. Although as @zaksnet indicated, there appear to be nearly no performance difference between single-threaded and multi-threaded physics in this example.  Might be worth looking into.
