### ISSUE TITLE
.GLB bones' name get weird after importing back to blender from godot

### ISSUE THREAD

**Issue by cenullum** [godotengine/godot#33747]
**Godot version:** 
3.1.1 stable
Blender version 2.8

**OS/device including version:**
 Window7

**Issue description:**
 I made some animation with blender then imported to godot. Everything was okey so far. After while I needed to rework on it however bones' name is changed in blender after importing from godot. And some bones doesn't move. It seems because of my language's chars like "ş ğ ü ç".

**Steps to reproduce:** 
made a animation in blender and name bones with "çşğü" and save as .glb
import to godot (still animations work properly)
import back to blender ( problem here)

**Minimal reproduction project:**
![kkkk](https://user-images.githubusercontent.com/57962685/69178973-b95b1c80-0b1b-11ea-923d-0f88784f5e05.PNG)
![kjnkjb](https://user-images.githubusercontent.com/57962685/69179187-28387580-0b1c-11ea-80c8-04551f49dadf.PNG)

![jnlkjn](https://user-images.githubusercontent.com/57962685/69178975-b9f3b300-0b1b-11ea-892f-f0a2537fe0b0.PNG)

**Comment by fire** [comment]
How did you import back to blender?

**Comment by cenullum** [comment]
I have deleted .blend version of my model so I had to import .glb to blender from my game project files directly. By import button with assigning .glb format that at bottom of all format options

**Comment by fire** [comment]
So this is a blender export and then blender import being corrupted?

As of this moment I don't think Godot has a glTF2 exporter. So this sounds like a Blender bug. Is that correct?

**Comment by cenullum** [comment]
if godot doesn't change anything of file while importing to project so yes it is a blender bug

**Comment by KoBeWi** [comment]
> if godot doesn't change anything of file while importing to project so yes it is a blender bug

Godot doesn't modify imported files directly, at most it creates a related resource in .import directory. So yeah, probably not Godot bug.
