### ISSUE TITLE
Syntax Checker bug with non-self function

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#33744]
**Godot version:**
7a0228fbb

**OS/device including version:**
Windows 10 x64

**Issue description:**

1.
![image](https://i.imgur.com/qJL5yk0.png)

2.
![image](https://i.imgur.com/hSqCimH.png)

As you can see, it complains that self.set_begin takes 2 arguments instead of one. It should be the same for an $IMG.set_begin, but it does not complain for some reason. Result is a runtime error:

![image](https://i.imgur.com/knf3PLH.png)

**Steps to reproduce:**
Above.

**Minimal reproduction project:**
http://www.mediafire.com/file/vte9yj2obv535vs/Error_Bug_Test.zip/file

**Comment by bojidar-bg** [comment]
Not sure if this is a bug. The script might be applied to multiple nodes, and thus the type of `$IMG` is unknown. As you might notice, the line numbers 19 through  21 are grayed out, since GDScript is not sure about the types involved there.

**Comment by Teashrock** [comment]
@bojidar-bg 
So this is what it is, huh? I didn't read about it in the documentation, so didn't know about it. Are you really sure that grayed lines mean an unknown typing?

**Comment by bojidar-bg** [comment]
From the description of #19264:
> * Will this affect my existing code?

> It shouldn't. If it does then it's a bug. Whenever a type check is possible it will make one, but this won't affect duck-typing. **Lines that are fully type-checked are indicated by a highlight in the line number.** However, GDScript was very lenient about some behaviors that can be considered an error, so your script might break if it relied on those behaviors. [emphasis mine]

But yeah, it might not be in the documentation, in case no one went through documenting it yet.

**Comment by Teashrock** [comment]
So, I might as well close it. And now... It's closed! Thank you.
