### ISSUE TITLE
Don't work NavMesh

### ISSUE THREAD

**Issue by Hromon** [godotengine/godot#33746]
**Godot version:**
3.2 beta1 | 3.1.1 stable
**OS/device including version:**
Windows 10
**Issue description:**
Don’t work bake, no matter how I try, it does not work and does not view in the editor. And also the projects that are in the demo do not work if you repeatedly press the bake.
**Steps to reproduce:**
Download "Navmesh Demo" press bake, and play this - don't work(
**Minimal reproduction project:**
[Nav.zip](https://github.com/godotengine/godot/files/3865642/Nav.zip)

**Comment by slapin** [comment]
NavMesh demo has incorrect set up for baking, don't use it.
Just put all your MeshInstance under NavigationMesh node, and make sure all NavigationMesh nodes are under navigation node, that should work. Also group-based mesh selection was added to master branch, try to use that one for better flexibility or wait for 3.2 release.

**Comment by Hromon** [comment]
> NavMesh demo has incorrect set up for baking, don't use it.
> Just put all your MeshInstance under NavigationMesh node, and make sure all NavigationMesh nodes are under navigation node, that should work. Also group-based mesh selection was added to master branch, try to use that one for better flexibility or wait for 3.2 release.

I tried, but it failed.
I changed everything and twisted the nodes to achieve the result.
I would not write this issue if everything was so simple.

**Comment by slapin** [comment]
Please check with 3.2 if that still have your issue.

**Comment by Hromon** [comment]
>Please check with 3.2 if that still have your issue.

I had to delete all the AppData content that belonged to Godot, and it worked on 3.2
