### ISSUE TITLE
.glb/.gltf import does not correctly import the camera Far and Fov values. 

### ISSUE THREAD

**Issue by LaBodilsen** [godotengine/godot#33756]
**Godot version:**
Godot Engine v3.1.1.stable.official

**OS/device including version:**
Window 10 pro 1909

**Issue description:**
.glb/.gltf import does not correctly import the camera Clip end value from Blender to Camera Far value in Godot, and Camera Field of View value from Blender to Fov value in Godot.  tested with .glb and .gltf.   When re-importing the same file to blender, the camera clip end and Field of View values is correct in blender. 

**Steps to reproduce:**
1. Open Godot 3.1 and create a new project.
2. Open Blender, and export the default cube scene to .glb/.gltf, with the option under Objects to include camera, and save it in the new godot project folder.  (notice that the Clip end value is 100m, and Field of View is 50mm / 39.6degree)
3. In Godot: wait for the import to run automatically, double click the new .glb/.gltf file, and choose "New Inherited", click the camera node, and check that the "Far " value is 0.1 instead of 100m, and Fov is 22 instead of 39.6

**Minimal reproduction project:**

**Workaround:**
Manually set the Camera Far and Fov values to the correct value from blender (eg. 100m and 39.6)

**Comment by fire** [comment]
It's part of the GLTF2 spec, but not sure what is stored inside of the gltf file. https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#cameras

Can you give a sample project with a gltf (json) file?

**Comment by LaBodilsen** [comment]
I have attached a sample project which include a .glb and a .gltf file.   looking in the file, the values are described as zfar and yfov as follows: 

**From .gltf:**
```
    "cameras" : [
        {
            "name" : "Camera",
            "perspective" : {
                "yfov" : 0.39959652046304894,
                "zfar" : 100,
                "znear" : 0.10000000149011612
            },
            "type" : "perspective"
        }
    ],
```

**From .glb: (json)**
`"cameras":[{"name":"Camera","perspective":{"yfov":0.39959652046304894,"zfar":100,"znear":0.10000000149011612},"type":"perspective"}]`

Looking in the code tree here:
https://github.com/godotengine/godot/blob/master/editor/import/editor_scene_importer_gltf.cpp

It seems the importer assumes that the .gltf specs are in radians, which do not seem to be the case (0.39959652 * 180 / π = 22.8952) about the zfar value, i can't really see why that fails.
```
camera.perspective = true;
if (d.has("perspective")) {
	const Dictionary &ppt = d["perspective"];
	**// GLTF spec is in radians, Godot's camera is in degrees.**
	camera.fov_size = (double)ppt["yfov"] * 180.0 / Math_PI;
	camera.zfar = ppt["zfar"];
	camera.znear = ppt["znear"];
```

[DefaultCube.zip](https://github.com/godotengine/godot/files/3873209/DefaultCube.zip)

**Comment by LaBodilsen** [comment]
I've been looking further into this, and regarding the fov value, it seems it's the blender exporter that is not working correctly.  i tried exporting as .dae, and then using an online converter to convert it to .glb. and using that file with godot.  and the camera fov value is then correctly importet. 

But the zfar value is still missing in godot.  so this bug report should only fix the Camera Far value import.

**Comment by fire** [comment]
https://github.com/godotengine/godot/blob/master/editor/import/editor_scene_importer_gltf.cpp#L2495-L2499

Should this be..
```
camera->set_perspective(c.fov_size, c.znear, c.zfar);
camera->set_orthogonal(c.fov_size, c.znear, c.zfar);
```

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/33793
