### ISSUE TITLE
Resize mouse cursor icon is not showing anymore

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3375]
In current 4290a25bd54623be1fee4db2911f7ddcc9b88ba8 build, the resize mouse cursor is not appearing anymore near the docs and other resizable elements. It's still possible to resize normally however.

Old (correct)   |  Current
------------------- | -------------------
![cursorold](https://cloud.githubusercontent.com/assets/6129594/12390213/56b048d2-bdde-11e5-987b-feef5e84be3c.gif) | ![newcursor](https://cloud.githubusercontent.com/assets/6129594/12390216/5df66338-bdde-11e5-979f-e2467d9142c7.gif)

**Comment by neikeq** [comment]
Duplicate of #3366

**Comment by kubecz3k** [comment]
@neikeq eh, always forgot to check, thx
