### ISSUE TITLE
Button.txt does not work with several containers... but works with on_button_pressed.

### ISSUE THREAD

**Issue by stevenabb** [godotengine/godot#33751]
**Godot version:** 3.1
**OS/device including version:** Linux DesktopMint 4.15.0-50-generic x86_64 x86_64 x86_64 GNU/Linux

**Issue description:** - Button.txt does not work under multiple containers under func_ready
**Steps to reproduce:**
1) Create a fresh project, Node,VBoxContainer(full rect), button
   Attach the script: 
extends Node
func _ready():
	$VBoxContainer/Button.text="Hello World."

2) Create a fresh project, put in a lot of  of containers (around 50+), with a button on 4
layers of containers...
extends Control
func _ready():
   $MarginContainer/VBoxContainer/HBoxContainer/HBoxContainer/Button.text="Hello World" 
Error Given - Invalid set index "text" (on base: 'null instance') with value of type 'String'

Now, when I put the exact same line
   $MarginContainer/VBoxContainer/HBoxContainer/HBoxContainer/Button.text="Hello World" 
Under a "button" on_Button_pressed(): method  with signal pressed(), it works as soon as the signal . The button has the text "Hello World" . My theory is that the gdscript needs to "wake up" or has some initialization/race condition? 

**Minimal reproduction project:**

**Comment by stevenabb** [comment]
global.mygame.push_front(savegame2) --> If I put the button.txt under this, it also eliminates the error??? That is inside the _on_Button_pressed() method... ? But before this line the button.txt is ignored.

**Comment by bojidar-bg** [comment]
To make it easier to test the issue, a minimal reproduction project would be nice. For example, an empty project which has step 2 applied would suffice.

Currently, I cannot reproduce the issue on my machine by adding a bunch of Containers and a button in the location expected by the script. Note that `$x/y/z` (and `get_node("x/y/z")`) work with paths relative to where the script is. Thus, the script written in step 2 would expect a node to named Button to exists as a child of a node named HBoxContainer which is a child of another node named HBoxContainer which is a child of a node named VBoxContainer which is a child of a node named MarginContainer which is a child of the node the current script is attached to.

**Comment by stevenabb** [comment]
Than you so very much for your response. Yes I have a big complex project, I cannot include everything. Now I am looking through the code today. I just can't figure out why a button.txt would throw off strange errors or fail to work. ( There are no tab indent issues, github makes the copy and paste look bad.)

func _on_BSave_pressed():
	# This line is ignored.
	$MarginContainer/VBoxContainer/HBoxContainer/LoadGameHBox1/LoadGame3.text=" Have a nice day. "
        # This line is ignored.
	if savegame2.length() > 32:
		$MarginContainer/VBoxContainer/HBoxContainer/TextSave.text="SAVE NAME TOO LONG - REJECTED"
	else:
		global.mygame.push_front(savegame2)
		print("Value of mygame 0 is : ",global.mygame[0])
# This line is run and the button text works.
	$MarginContainer/VBoxContainer/HBoxContainer/LoadGameHBox1/LoadGame3.text=" This line is honoured. "
# This line is run.

**Comment by stevenabb** [comment]
So for some reason, even after the method _on_button_pressed(): is executed the button.txt line is ignored. Now, after I run a simple if/else if statement with a push_front on an array ( global.mygame ), the button.txt will display the text. I cannot understand why button.txt has any correlation between running an if / else if control  and , pushing a value onto an array. Bizzare for sure...

**Comment by bojidar-bg** [comment]
I'm not sure if I can help you without a minimal reproduction project. At any rate, trying to recreate the issue might give you insight as to what causes it.

**Comment by girng** [comment]
> Under a "button" on_Button_pressed(): method with signal pressed(), it works as soon as the signal .

As the signal? What's that mean? If you can, create an example project it will help a lot

**Comment by stevenabb** [comment]
So here is the problem, GODOT and the set_text built in function cannot figure out the location of a node item in the path. 

This was reported back in 2016. 
https://godotengine.org/qa/1887/setting-label-text-throws-a-null-instance-error

Even when I simplified the path, and use a different syntax to set the text, I get the exact same error. 
get_node("MC/VBC/HBC/CenterContainer/Label1").set_text("hello world")

and this does not work... 

(The following is one long line).
$MarginContainer/VBoxContainer/HBoxContainerLoadGameHBox1LoadGame1.text=str(global.mygame[0])
(The following is one long line.).

I even changed LoadGameHBox1 ~ changed type from a button to a label... exact same error. 

For some reason, the set_text function does not understand the path to the button or label?  If I do some math stuff inside of a press button, suddenly set_text understands the path??
func _on_BSave_pressed():

I put this if statement under a press button method.
if savegame2.length() > 32:
		$MarginContainer/VBoxContainer/HBoxContainer/TextSave.text="SAVE NAME TOO LONG - REJECTED"
	else:
		global.mygame.push_front(savegame2)

And after that if statement, the set.text understands where is the node in the path? Some kind of bug is preventing  set_text from 'knowing' the path to a node? Please keep this issue open.

**Comment by stevenabb** [comment]
I just rebuilt the scene. There is some kind of a glitch with printing  the text on an item that is "quirky" with containers. I don't know what it is... but this is something to remember, even if the the problem cannot be duplicated. Thank for your time, per your discretion close or keep this open?

**Comment by bojidar-bg** [comment]
I still think you are either giving an incorrect path, or setting the text before those nodes have loaded (before _ready).

**Comment by stevenabb** [comment]
Respectfully, no. The path was completed by tab line completion. I also modified the path to use shorter words and put that into a function that was called by "  func_ready() ... I also put some of the .text lines directly under the func_ready() method directly. This is not a simple typo problem or something armature like putting code before func_ready... There really is some odd glitch. I have rebuild the scene with new containers and now it works without issue. When I have the time I will try to dig into the old code.

**Comment by volzhs** [comment]
Looking **Remote** tab on scene panel also helps what was wrong.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
