### ISSUE TITLE
Editor can't find MonoDevelop on Windows 10

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#33761]
**Godot version:**
v3.2.beta.mono 1bd32388a

**OS/device including version:**
Windows 10 x64

**Issue description:**
Mono's External Editor is set to MonoDevelop.
Monodevelop's bin folder is present in the PATH.
Any attempt to edit a C# script results in the error: `Cannot find code editor: MonoDevelop`

![image](https://user-images.githubusercontent.com/10672233/69229188-bedc5500-0b63-11ea-9e76-f70272e8e831.png)

**Steps to reproduce:**
Set the mono external editor to MonoDevelop and try editing a C# script file.

**Minimal reproduction project:**
\-

**Comment by neikeq** [comment]
What executable files are in your  MonoDevelop's bin folder?

**Comment by piratesephiroth** [comment]
> 
> 
> What executable files are in your MonoDevelop's bin folder?

![image](https://user-images.githubusercontent.com/10672233/69262523-637d8780-0ba2-11ea-9acd-123ece60c0eb.png)
