### ISSUE TITLE
Warning about possible wrong usage of emit_signal in script_editor_debugger

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3376]
I caught this warning while compiling with gcc:

```
tools/editor/script_editor_debugger.cpp: In member function 'void ScriptEditorDebugger::_parse_message(const String&, const Array&)':
tools/editor/script_editor_debugger.cpp:224:36: warning: converting 'false' to pointer type for argument 2 of 'void Object::emit_signal(const StringName&, const Variant**, int)' [-Wconversion-null]
   emit_signal("breaked",false,false);
                                    ^
```

It comes from this line: https://github.com/godotengine/godot/blob/74a48a0/tools/editor/script_editor_debugger.cpp#L226
though this one might also trigger a similar warning: https://github.com/godotengine/godot/blob/74a48a0/tools/editor/script_editor_debugger.cpp#L209.

It looks like the call is matched to this function:
https://github.com/godotengine/godot/blob/3d0bd1a/core/object.h#L596
`void emit_signal(const StringName& p_name,VARIANT_ARG_LIST);`
when what is intended is probably the first one:
https://github.com/godotengine/godot/blob/3d0bd1a/core/object.h#L595
`void emit_signal(const StringName& p_name, const Variant** p_args, int p_argcount);`

Would changing the order of the two declarations fix the issue? Or is there a better way?

**Comment by Algrin6** [comment]
I had some problems with debugging. Maybe they're linked with this bug.

**Comment by akien-mga** [comment]
This has been fixed a while ago AFAIK.
