### ISSUE TITLE
Godot is incorrectly marked as 32-bit (Catalina incompatible) on Steam.

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#33768]
**Godot version:**
Steam Distribution (3.1.1)

**OS/device including version:**
macOS 10.15.1

**Issue description:**
New Steam interface incorrectly marks Godot as 32-bit (incompatible with the macOS Catalina) by placing crossed circle at the app list and displaying warning message in the app info page. As well as on the app store page in browser running on macOS 10.15.

Actual Godot executable and app bundle `.plist` are 64-bit only, should be some sort of Steam configuration flag missing.

This seems to be common problem, many (but not all) Steam games are marked as incompatible while they in fact are either fat or 64-bit only.

*Note: this is not related to the new notarizing and signing requirements, macOS Gatekeeper only check apps marked as download from unknown source by browser or `.DMG` image mounter, apps installed via Steam (or any other package manager) should work fine regardless their signing state.*

![Screenshot 2019-11-20 at 19 48 53](https://user-images.githubusercontent.com/7645683/69264036-309db880-0bcf-11ea-96cd-38857fe78ad2.png)

![Screenshot 2019-11-20 at 19 55 05](https://user-images.githubusercontent.com/7645683/69264409-f2ed5f80-0bcf-11ea-9acd-33eef47bff8b.png)

**Comment by akien-mga** [comment]
I changed the depot from "All Architectures" to "64-bit Only". Please tell me if it worked (might need a few minutes to update, or a Steam restart).

**Comment by bruvzg** [comment]
> Please tell me if it worked

No, it's still the same.

**Comment by akien-mga** [comment]
Found yet another checkbox to tick:
![image](https://user-images.githubusercontent.com/4701338/69273470-b5d99b00-0bd8-11ea-96e5-5c589bd454b3.png)

Does it work now?

**Comment by bruvzg** [comment]
> Does it work now?

Yep, now it's fixed.
