### ISSUE TITLE
Separate ImageTexture repeat/clamp/mirror flags into each axis

### ISSUE THREAD

**Issue by nanaian** [godotengine/godot#33775]
##### (I considered throwing this in the proposals repository, but it looks like that's for full feature proposals - this is a minor change, IMO, and I just want to check its okay to work on before making a PR!)

Godot currently doesn't support a separate repeat/mirror/clamp texture wrapping mode on each axis. I can't see any reason for this in [the renderer sourcecode](https://github.com/godotengine/godot/blob/083d088de3fe7cd5d825cebebc46ce32fc87b4b0/drivers/gles3/rasterizer_storage_gles3.cpp#L846-L860). Given a backwards-compatible implementation (eg. new flags for each axis), would a PR adding this be accepted? Have I missed something that means we can't implement this feature?

Context: I'm working on a project which allows the user to load/create a texture dynamically, at runtime, and want to apply separate wrapping modes for each axis. I'm not at liberty to modify the texture images themselves, really, especially in GDScript. I'm using **Godot 3.1**.

**Comment by clayjohn** [comment]
This won't be considered for 3.x releases. But is something that may be considered for 4.0. 

IMO a full discussion on the proposals repo would be better than an enhancement post here. That way it is easier to tell if other people would find this useful. And your issue won't be buried by bug reports.
