### ISSUE TITLE
GL_INVALID_OPERATION error with GLES3 when loading project in verbose mode

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#33787]
**Godot version:**
Master 2981915f19f6c168128afffcfe18fcd122401b65

**OS/device including version:**
Windows 10

**Issue description:**
In the editor, when loading any project setup with GLES3 in verbose mode, an error systematically occurs on startup.

No error occurs when the project is setup with GLES2.

*Logged error:*
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. Wrong component type or count.
   At: drivers\gles3\rasterizer_gles3.cpp:123
```

*Callstack:*
```
CubemapFilterShaderGLES3::set_uniform(CubemapFilterShaderGLES3::Uniforms p_uniform, float p_value) Line 44	C++
RasterizerStorageGLES3::sky_set_texture(RID p_sky, RID p_panorama, int p_radiance_size) Line 1858	C++
VisualServerRaster::sky_set_texture(RID arg1, RID arg2, int arg3) Line 179	C++
VisualServerWrapMT::sky_set_texture(RID p1, RID p2, int p3) Line 115	C++
ProceduralSky::_radiance_changed() Line 131	C++
ProceduralSky::_update_sky() Line 420	C++
MethodBind0<ProceduralSky>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 149	C++
Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 921	C++
MessageQueue::_call_function(Object * p_target, const StringName & p_func, const Variant * p_args, int p_argcount, bool p_show_error) Line 254	C++
MessageQueue::flush() Line 303	C++
SceneTree::iteration(float p_time) Line 486	C++
Main::iteration() Line 1957	C++
```

**Steps to reproduce:**
- Create an empty project setup with GLES3
- Start godot editor with the following command line arguments:
`-v -e --path [project_path]`
- Observe error

**Minimal reproduction project:**
Any project loaded in verbose mode and configured with GLES3.

**Comment by akien-mga** [comment]
I can confirm on Linux (Mesa 19.2.2). The error message is a bit more explicit:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 16  Severity: High  Message: GL_INVALID_OPERATION in glUniform1("source_mip_level"@1 is int, not float)
   At: drivers/gles3/rasterizer_gles3.cpp:123.
```

Related to #33779.

**Comment by clayjohn** [comment]
Looks like I didn't correct fix this last night. 

This line needs to be float

https://github.com/godotengine/godot/blob/37b230fe3af3c7e20a6f938d03b61a79b117d354/drivers/gles3/shaders/cubemap_filter.glsl#L38
