### ISSUE TITLE
Editable Children's local children aren't displayed in the Connect Signal Dialogue

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#33795]
**Godot version:**
3.2.beta1

**OS/device including version:**
Solus 4.0 Gnome 3.34.1

**Issue description:**
When trying to connect signals to Editable Children's children, they aren't displayed in the **Connect a Signal to a Method** dialogue, not even when `Advanced = true`. This happens even if the child is local to the current scene, e.g. if you add a new child to an Editable Children Node.

**Steps to reproduce:**
- Create a new Scene, A, with some (3?) children
- Save it
- Create a new Scene, B
- Instance A as a child of B
- Add a new Node, C, to B (<kbd>CTRL</kbd>+<kbd>A</kbd>)
- Toggle "Editable Children" on the instance of A in B
- Move C to the A's instance's hierarchy, i.e. make C a child of A's instance
- Try to connect a signal from B to C using the Editor
- (Plus) Toggle "Advanced" in the **Connect a Signal to a Method** dialogue

**Comment by capnm** [comment]
A workaround is to close the scene and edit the *.tscn file. 

The signal callback is correctly listed in the inspector signal list,
but isn't marked (in text editor) in the instanced children's script  → **BUG2**.

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by hilfazer** [comment]
Invalid in 3.3 RC 6.

**Comment by akien-mga** [comment]
You mean it's fixed?

**Comment by hilfazer** [comment]
That's right (: The opposite of what KoBeWi wrote before.
