### ISSUE TITLE
Groups are not duplicated when using duplicate()

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3379]
1. Create a scene and put it into a group: "SampleGroup" from the editor interface.
2. Duplicate this scene in runtime with duplicate() method.
3. Duplicated scene will not be in the "SampleGroup".

Similar issue but with signals: https://github.com/godotengine/godot/issues/1888

**Comment by Hinsbart** [comment]
As a workaround, if the node you want to duplicate is the root of a scene file, you can use `duplicate(true)`.
In this case, the duplicated node will be in "SampleGroup".
Unfortunately this doesn't seem to work for signals.
