### ISSUE TITLE
StyleBoxFlat preview doesn't take shadow into account

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#33801]
Godot 3.2 beta1

When editing a `StyleBoxFlat` resource with a shadow, the preview cuts it short and it's not visible:

![image](https://user-images.githubusercontent.com/1311555/69370610-30b4bb80-0c96-11ea-9e40-c98687ec3def.png)

**Comment by Calinou** [comment]
This could be solved by adding a small margin around the previewed StyleBox.

**Comment by pouleyKetchoupp** [comment]
There's now an optional offset on the shadow so we might have to take that into account to make sure it fits in the preview.
