### ISSUE TITLE
(GLES3) Default Material matches clear color

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#33805]
**Godot version:**
3.2 Beta 1 Mono

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
Cube mesh without material (or default) is very difficult to see as it always matches the clear color
![image](https://user-images.githubusercontent.com/14253836/69378156-6c8a5980-0c73-11ea-83ff-75b1b297ec5a.png)

Red Clear Color:
![image](https://user-images.githubusercontent.com/14253836/69378179-74e29480-0c73-11ea-9f11-aad51e9292b9.png)

**Steps to reproduce:**
- Open the reproduction project
- Modify Project Settings->Rendering->Environment->Default Clear Color

**Minimal reproduction project:**
[GodotTestProject.zip](https://github.com/godotengine/godot/files/3876843/GodotTestProject.zip)

**Comment by clayjohn** [comment]
What is the bug here? 

You have a white object in an environment with a single color. Of course it takes its color from the environment. This is a consequence of PBR rendering.

**Comment by nathanwfranke** [comment]
The problem is usability. It is impossible to see an object without using the Gismos.

The problem goes away instantly when I add the default environment. How about when no environment is set, it uses the default environment (To be consistent with Material)
![image](https://user-images.githubusercontent.com/14253836/69383100-5fbf3300-0c7e-11ea-8a02-6f90557fd11c.png)

**Comment by clayjohn** [comment]
> The problem is usability. It is impossible to see an object without using the Gismos.

I think showing what the object will actually look like in the final rendered scene is much more important than highlighting the object in the Viewport. 

> The problem goes away instantly when I add the default environment.

This is expected. The default environment isn't a flat color so you don't get the same effect. 

In 4.0 you will be able to specify a background color and a different color to use for radiance. So we will not have this problem the same way.

**Comment by nathanwfranke** [comment]
> I think showing what the object will actually look like in the final rendered scene is much more important than highlighting the object in the Viewport.

The object should be visible in both the viewport and the rendered scene. One could argue that the bug is even more prominent in the rendered game because the object is literally invisible if there are no lights.

> The default environment isn't a flat color so you don't get the same effect.

This problem can be easily fixed by making a null environment behave as the default environment. This way it would at least be consistent with other rendering elements such as materials.

**Comment by nathanwfranke** [comment]
Apologies for this issue, no change is directly needed right now. Godot projects automatically come with a default environment in `default_env.tres` which I have mistakingly deleted.
