### ISSUE TITLE
Dock will shake while edit the TileMap

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#33818]
**Godot version:**
3.2 beta 2

**OS/device including version:**
Mac OS 10.15.1

**Issue description:**
While edit the TileMap(such as drag on TileMap to paint cells), the docks (the Inspector and the TileMap dock) on the right will shake.

Another issue:
Select a tile, and then hold down the control to remove tiles, then release the control, the selected tile will become empty.

**Steps to reproduce:**
1 add a tilemap
2 edit the tilemap like dragging to paint tiles

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Duplicate of #28135.
