### ISSUE TITLE
Creating a Physical bones for Ragdoll will Crash the Engine after Changing/Reloading a Scene

### ISSUE THREAD

**Issue by owstetra** [godotengine/godot#33812]
**Godot version:**
Godot 3.2 Beta 1

**OS/device including version:**
Windows 7 x64bit

**Issue description:**
i think this is a Duplicate issue maybe ?

Creating a Physical bones for Ragdoll will Crash the Game after Changing/Reloading a Scene also Spamming the Engine with this :
```
W 0:00:04:0853   assert_no_constraints: A body with a joints is destroyed. Please check the implementation in order to destroy the joint before the body.
  <C++ Source>   modules/bullet/rigid_body_bullet.cpp:465 @ assert_no_constraints()
```

Edit : yes it's a Duplicate issue : https://github.com/godotengine/godot/issues/28495

@AndreaCatania you did this Massive improvements to the Skeleton https://github.com/godotengine/godot/pull/28909 , is there any Chance to fix at least this issue without breaking compatibility with code ? so we can use Ragdolls on 3.2 without waiting for Godot 4 ?

**Steps to reproduce:**
after creating a Physical bones for your Character , Play the game then Change your Level/Scene.

**Comment by KoBeWi** [comment]
> Edit : yes it's a Duplicate issue : #28495
