### ISSUE TITLE
Panel plugin does not show button child nodes.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#33821]
**Godot version:**
3.2Beta1
**OS/device including version:**
Mac OS X, Mojave

**Issue description:**
Panel plugin does not show button child nodes. Screen shots below

**Steps to reproduce:**
Create a new project ButtonDialog and add empty Control scene.
Create addons folder called ButtonDialog.. Create ButtonDialog.tscn with a Panel control (name it ButtonDialog) and add 4 buttons (e.g. Add,Edit,Delete Cancel).

Add the following gd files in the addons folder.

**ButtonDialog.gd**
```gdscript
tool
extends EditorPlugin

func _enter_tree():
	# Initialization of the plugin goes here
	add_custom_type("ButtonDialog", "Panel", preload("ButtonDialogNode.gd"), preload("icon.png"))
	pass

func _exit_tree():
	# Clean-up of the plugin goes here
	remove_custom_type("ButtonDialog")
	pass

```
**ButtonDialogNode.gd**
```gdscript
tool
extends Panel

func _ready():
	pass
```
**plugin.cfg**
```
[plugin]

name="Button Dialog"
description="Button Dialog""
author="author"
version="1.0"
script="ButtonDialog.gd"
```

Enable the plugin in the Project.
Add scene ButtonDialog using + to Control scene.
Notice buttons do not show up when added as child plugin. (+)
However buttons do show up when added as instance scene.

ButtonDialog.tscn
![image](https://user-images.githubusercontent.com/930478/69443152-da8a5b80-0d1b-11ea-87ec-eb52581915bb.png)

Control.tscn
![image](https://user-images.githubusercontent.com/930478/69443282-132a3500-0d1c-11ea-83d2-3296eb541a82.png)

**Comment by Zylann** [comment]
> `add_custom_type("ButtonDialog", "Panel", preload("ButtonDialogNode.gd"), preload("icon.png"))`

This line means when you ask to add a `ButtonDialog`, Godot will instanciate a `Panel` and put the `ButtonDialogNode.gd` on it with the specified custom icon. The script does not do anything so the result is just a panel.

**Comment by wyattbiker** [comment]
ok thanks will look at alternate ways.
