### ISSUE TITLE
 i can't compile for android via gdnative

### ISSUE THREAD

**Issue by IuryBorges1993** [godotengine/godot#33826]
**Godot 3.1+**

**Ubuntu 18.04**

**I
i can't compile for android via gdnative**

![Captura de tela de 2019-11-22 18-17-19](https://user-images.githubusercontent.com/39449626/69463919-bc445000-0d5b-11ea-9c34-ed2c7356dd69.png)
![Captura de tela de 2019-11-22 18-18-03](https://user-images.githubusercontent.com/39449626/69463928-c1090400-0d5b-11ea-86f9-e0437984c7b2.png)
![Captura de tela de 2019-11-22 18-41-38](https://user-images.githubusercontent.com/39449626/69463932-c403f480-0d5b-11ea-93c9-939a983a8499.png)

everything was going well, when I got to the final stage the error started -> aarch64-linux-android/bin/ld: cannot find -lgodot-cpp.android.debug.armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Project github: https://github.com/IuryBorges1993/port-demo-kinematic_character-para-android

**Comment by IuryBorges1993** [comment]
I followed this tutorial, still the error at the end -> https://github.com/GodotNativeTools/godot-cpp#compiling-the-cpp-bindings-library

**Comment by somefoo** [comment]
Hi @IuryBorges1993,

the linker is trying to inform you, that I cannot find the required library (the one created in the previous step). The -l flags tells the linker which library you want to link, the -L flag tells the linker where to look for this library (path).

<YOUR_COMPILER> -o bin/libtest.so -shared src/init.os **-Lgodot-cpp/bin -l\<name of the godot-cpp\>**

Please make sure, the path is correctly set. Your GitHub project seems to have a very different structure than the one presented in your images. For example, the godot-cpp/bin folder seems to be in the root directory of your project; not the assets folder. Perhaps this is where this is going wrong?

In the future, please provide the actual commands you used for compilation etc. not just images; it makes our lives a little easier :)

You can have a look here, to learn more about the linker (specifically the sections about -l and -L should be of interest): https://linux.die.net/man/1/ld

Pit.

**Comment by KoBeWi** [comment]
OP didn't respond to previous comment, so per that comment let's assume this was resolved.
