### ISSUE TITLE
collisionShape.make_convex_from_brothers() doesnt work.

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#3383]
There is a problem with convex and concave physic shapes.
I tried a lot but I couldn´t get it working. It changes the shape and it applies the right array to it but the physic engine still uses the shape settings I applied in the editor.

**Comment by KoBeWi** [comment]
Well, this is the code of this method (it was always almost the same):
https://github.com/godotengine/godot/blob/a940b4cf640930b2decb356d395ac4cd89beefaf/scene/3d/collision_shape.cpp#L45-L65

Looks like it sets the shape from each of the sibling Meshes, effectively setting it to the last one.
