### ISSUE TITLE
please replace the android.defaultConfig.applicationId in build.gradle with the package/unique_name 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#33838]
**Godot version:**
3.2 beta 2

**OS/device including version:**
Mac OS
**Issue description:**
When use android custom build, the value of android.defaultConfig.applicationId in build.gradle is always com.godot.game, then cause the error  INSTALL_FAILED_CONFLICTING_PROVIDER when compile with some plugins, we must modify this value manually, it wil be nice to replace this applicationId to the value of package/unique_name on the export dialog.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Shin-NiL** [comment]
It's one of the reasons that is stopping me to use a newer version of the Admob SDK.

**Comment by m4gr3d** [comment]
Sorry for the delay. I'll take a look at the issue tomorrow.

**Comment by m4gr3d** [comment]
@alexzheng @Shin-NiL can you test PR https://github.com/godotengine/godot/pull/34317 and see if it fixes your issues.

**Comment by alexzheng** [comment]
I test the 3.2 beta4, still the same
 defaultConfig {
        // Feel free to modify the application id to your own.
        applicationId "com.godot.game"

**Comment by akien-mga** [comment]
PR #34317 has not been merged yet into 3.2 beta 4, we need it tested to see if it works.

**Comment by m4gr3d** [comment]
@Shin-NiL @alexzheng the linked PR fixes the issue as described in the issue description section (i.e: _replace this applicationId to the value of package/unique_name on the export dialog_), so I'm gonna mark it as ready for review.

**Comment by Shin-NiL** [comment]
@m4gr3d Sorry for the delay. I finally was able to make a test and it's worked fine. Thank you very much!
