### ISSUE TITLE
FORCE_VERTEX_LIGHTING ignores roughness in SpatialMaterials

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#33835]
**Godot version:**
3.2 beta 2 

**Issue description:**
The project setting force_vertex_lighting forces vertex lighting at the level of the rendering backend (in rasterizer_scene_gles*.cpp). However, in order for the object to have a proper roughness set, ROUGHNESS needs to be assigned in the SpatialMaterial's (or ShaderMaterial's) vertex function. SpatialMaterial adds this automatically when the render mode "vertex_lighting" is true. 

The issue is that force_vertex_lighting doesn't set "vertex_lighting" in each material, so the proper ``ROUGHNESS = roughness`` assignment code isn't added to the vertex shader and the resulting shader doesn't properly use roughness. This is a large problem for mobile, which has force_vertex_lighting enabled by default. 

**Steps to reproduce:**
1. use force_vertex_lighting
2. add an object with a SpatialMaterial
3. adjust roughness

**Comment by akien-mga** [comment]
@clayjohn Is this still reproducible in 3.2.3-stable? If yes, sounds like something I would normally assign to you :P

**Comment by clayjohn** [comment]
I just checked, yes it is still reproducible, I think it will be relevant for master, but it looks like vertex shading isn't working in master yet.

**Comment by akien-mga** [comment]
Fixed by #42543.
