### ISSUE TITLE
 can't compile a custom apk on android godot 3.2

### ISSUE THREAD

**Issue by IuryBorges1993** [godotengine/godot#33839]
I can't compile a custom apk on android, simply from error

**Comment by IuryBorges1993** [comment]
A compilação do projeto Android falhou, verifique a saída pelo erro.
Alternativamente, visi
![Captura de tela de 2019-11-23 07-49-53](https://user-images.githubusercontent.com/39449626/69477507-dadf3100-0dc5-11ea-939a-172ededb2653.png)
te docs.godotengine.org para ver a documentação de compilação do Android.

**Comment by IuryBorges1993** [comment]
https://github.com/IuryBorges1993/plugingodotandroid

**Comment by IuryBorges1993** [comment]
Code java: https://github.com/IuryBorges1993/plugingodotandroid/blob/master/androidPlugin/android/build/src/com/godot/game/MySingleton.java

**Comment by cagdasc** [comment]
@IuryBorges1993 you need to add package name to head of java file but this is not an issue, please close. For your information @akien-mga
