### ISSUE TITLE
Camera.project_position return camera's globla_transform.origin when the camera'projection is orthogonal and the parameter depth is 0,

### ISSUE THREAD

**Issue by Jiaming00** [godotengine/godot#33837]
**Godot version:**
Godot 3.2 beta 1

**OS/device including version:**
Windows 10 64 bits

**Issue description:**
When the camera's projection is orthogonal and the parameter depth is 0, project_position will return the camera's globla_transform.origin, yes, if the projection is perspective or frustum, this is of course correct.

**Steps to reproduce:**
Create new 3D scene, put a camera, change projection to orthogonal  andwrite print(project_position(get_viewport().get_mouse_position(),0))
print(project_position(get_viewport().get_mouse_position(),1)) 

**Minimal reproduction project:**

**Comment by fsy98** [comment]
I read the source code I think this may solve your concern:
<img width="615" alt="Capture" src="https://user-images.githubusercontent.com/30133945/70459849-0a0ec700-1a83-11ea-9431-153837a0b4bc.PNG">
Because when your parameter depth is 0, it just return the  global_transform.origin whatever what kind of projection you are in. So if you don't want return the  global_transform.origin, the depth can not be 0. You change the depth then your global_transform.origin won't return when you in orthogonal projection.

**Comment by fsy98** [comment]
sorry my English is not good, so if make any mistake just tell me thank you.

**Comment by Jiaming00** [comment]
@fsy98  I think the value of depth == 0 is meaningless. I think project_pisition is seeking the global position of the point on the pixel ray. The other two projection modes return the origin position (when depth == 0), because all pixel rays intersect at the camera origin  (or "the starting point of the frustum"), but there is no intersection in the orthogonal projection mode (or "no frustum"), This is why I asked the question.
Or that my understanding is wrong.

**Comment by fsy98** [comment]
OK i get it I will try to fix it

**Comment by fsy98** [comment]
but if in the orthogonal projection mode and the parameter depth is 0, what you think should return?

**Comment by Jiaming00** [comment]
@fsy98 

This is a schematic diagram. The blue point is the origin of the camera. When depth == 0, project_position returns the point on the red line. I think that if you remove the depth == 0 judgment statement in the source code, the correct result will be returned.

![](https://raw.githubusercontent.com/Jiaming00/lib0/master/0.png)

**Comment by fsy98** [comment]
> @fsy98
> 
> This is a schematic diagram. The blue point is the origin of the camera. When depth == 0, project_position returns the point on the red line. I think that if you remove the depth == 0 judgment statement in the source code, the correct result will be returned.
> 
> ![](https://raw.githubusercontent.com/Jiaming00/lib0/master/0.png)

same idea I just do the pull request, remove that

**Comment by Jiaming00** [comment]
As shown in the diagram above,I may have misunderstood the frustum projection mode, its global_transform.origin is not the intersection of all rays.

**Comment by akien-mga** [comment]
Fixed by #34233 / d80e979a48.
