### ISSUE TITLE
Android one-click deploy tooltip not updated with one device

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33845]
**Godot version:**
3.2 beta2

**Issue description:**
It always says "Select device from the list" even if only one device is connected (and with recent update it will instantly deploy, so even no list appears).

**Comment by capnm** [comment]
Looks like a new (half-baked) feature for the case of a single Android device with a wrong tooltip.
If you connect multiple devices, it works as expected.

**Comment by Calinou** [comment]
It worked when I implemented #28236, so this may come from an unrelated regression or be OS/device-specific :slightly_smiling_face:

**Comment by capnm** [comment]
> It worked when I implemented #28236, so this may come from an unrelated regression or be OS/device-specific :slightly_smiling_face: 

At least I guessed correctly that it is feature :smiley_cat:

**Comment by Calinou** [comment]
> There does not seem to be a knob to stop the debug / logcat process. I would prefer to undo the change and add an entry for that instead.

Shouldn't the "stop" button do that already?

**Comment by capnm** [comment]
> Shouldn't the "stop" button in the top bar do that already?

That isn't related to. Enable debug and hit the Android button. The only way I found to stop the debugging connection is to kill the Android app ?!?!

Honestly, someone should rework how those buttons work. Currently 'playing' / debug Android collides horribly with playing / debug a desktop app.

**Comment by akien-mga** [comment]
Is this still reproducible in 3.2.3-stable? If so, I believe this might qualify as a junior job.

**Comment by KoBeWi** [comment]
> If not

You probably meant if yes 🤔

Still valid in 42f209850

**Comment by killerkpoke** [comment]
Hi, i am currently working on a side project in godot 3.2.x and the answer is yes, i could reproduce that bug when i connect only 1 device is still not updating the UI, but with 2 device the icon showing up and working well as expected. I tested on 3.2.2 and 3.2.3.
