### ISSUE TITLE
BitmapFont documentation misleading

### ISSUE THREAD

**Issue by BenMcLean** [godotengine/godot#33841]
Right now, [the BitmapFont class documentation says](https://docs.godotengine.org/en/3.1/classes/class_bitmapfont.html) it supports "FNT" format. FNT is an older Microsoft Windows bitmap font format. Godot does not in fact support FNT format, never has (far as I know) and should not say that it does.

The bitmap font format which Godot actually supports is [Angel Code font format](https://www.angelcode.com/products/bmfont/) only. Trying to import real FNT files, such as old Windows fonts or FNT fonts created with [FontForge](https://fontforge.org/) will not work. This can be confusing because Angel Code font files happen to use the same ".fnt" extension, but just knowing the extension does not communicate what format is supported. It needs to say Angel Code font format. Please update the documentation to include this information.

**Comment by akien-mga** [comment]
Documentation can be adapted from what I wrote for `ResourceFormatLoaderBMFont` initially, before we figured out that it didn't need to be exposed as a public class (and thus documented):

https://github.com/godotengine/godot/commit/f792a05acaf54b57447f3322b533e289788688a5#diff-9a60d080ee6765c2ac063b0cf64a7353R7-R9
