### ISSUE TITLE
viewport.cpp:1307:50: error - templates compilation error.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3384]
48 hours ago everything was compiling without errors.
Today compilation of templates after git pull always stops at:
```
scene/main/viewport.cpp: In member function 'void Viewport::_vp_input(const InputEvent&)':
scene/main/viewport.cpp:1282:50: error: 'class SceneTree' has no member named 'get_edited_scene_root'
  if (get_tree()->is_editor_hint() && get_tree()->get_edited_scene_root()->is_a_parent_of(this)) {
                                                  ^
scene/main/viewport.cpp: In member function 'void Viewport::_vp_unhandled_input(const InputEvent&)':
scene/main/viewport.cpp:1307:50: error: 'class SceneTree' has no member named 'get_edited_scene_root'
  if (get_tree()->is_editor_hint() && get_tree()->get_edited_scene_root()->is_a_parent_of(this)) {
```

Godot engine compiles without error in the same time.

I use xubuntu 14.04 LTS.

**Comment by akien-mga** [comment]
Similar to #3166 and #3213, both of which were fixed by using ```#ifdef TOOLS_ENABLED``` in the right places.

**Comment by freemanfromgodotengine** [comment]
This one affects templates for Windows, Linux and Android.

**Comment by akien-mga** [comment]
Well it affects any ```tools=no``` build as get_edited_scene_root is only defined if building with tools enabled :)

**Comment by akien-mga** [comment]
@reduz I've pushed a quick fix, though feel free to improve it if you think these ifdef everywhere are getting bothersome :) (for exemple get_edited_scene_root could be defined and return null when TOOLS_ENABLED is not defined - though I'm not sure it would be better for the readability).
