### ISSUE TITLE
Shader language doesn't allow assigning constants with constant arithmetic

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#33840]
**Godot version:** Git https://github.com/godotengine/godot/commit/80b1604fa95b048307815c5eee96426942dd207a

**OS/device including version:** Fedora 31, NVIDIA GeForce GTX 1080

**Issue description:**

The shader language doesn't seem to accept constants that use arithmetic operations. In comparison, this seems to work in raw GLSL (tested in [SHADERed](https://github.com/dfranx/SHADERed)).

**Steps to reproduce:**

Paste the following shader into a ColorRect node's material:

```glsl
shader_type canvas_item;

const float QUARTER_COLOR = 1.0 / 1024.0; // 0.0009765625

void fragment() {
	COLOR = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0);
	vec4 col = COLOR;

	// Increase/decrease the pixel colour values slightly in a 
	// chessboard pattern to achieve a simple dithering against banding.
	// Assume 8-bit RGB values and offset values a bit to affect rounding.
	if (mod(FRAGCOORD.x + FRAGCOORD.y, 2) == 1.0) {
		COLOR.rgb += vec3(QUARTER_COLOR);
	} else {
		COLOR.rgb -= vec3(QUARTER_COLOR);
	}
}
```

This will result in the error message: `error(3): Expected constant expression after '='`

**Minimal reproduction project:** [test_dithering.zip](https://github.com/godotengine/godot/files/3882355/test_dithering.zip)

**Comment by Chaosus** [comment]
I will look to fix this...

**Comment by arthur109** [comment]
This is still not fix btw

**Comment by Calinou** [comment]
@arthur109 Please open a new issue with a minimal reproduction project attached.
