### ISSUE TITLE
Editor Settings -> Mono just showing numbers

### ISSUE THREAD

**Issue by vekkna** [godotengine/godot#33842]
**Godot version:**

3.2 beta 2

**OS/device including version:**

Windows 10 1909

**Issue description:**

The Editor Settings -> Mono -> Editor's textbox shows 4 instead of VSCode.
The Mono -> Build textbox shows 1 instead of VS Build Tools.
 

**Steps to reproduce:**

As above.

**Minimal reproduction project:**

Empty project will do.

**Comment by akien-mga** [comment]
That's another (weird) symptom of the bug that causes #33822.

**Comment by neikeq** [comment]
@akien-mga Can this be closed now?

**Comment by akien-mga** [comment]
Yes, it seems good on that front in 3.2 beta 4.
