### ISSUE TITLE
Ctrl + click on a relative file path in .gd file doesn't open that file

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#33859]
**Godot version:**
3.2 beta2

**OS/device including version:**
Windows 7 SP1

**Issue description:**
Ctrl + click on a relative file path in .gd file doesn't open that file. It does for absolute paths (starting with "res://").

**Steps to reproduce:**
Hold Ctrl and click on relative paths in Main.gd from example project.

**Minimal reproduction project:**
https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/RelativePathCtrlClick

It might be the cause of **autocompletion not working** for scripts preloaded with relative paths.

**Comment by Zylann** [comment]
Mentionned in https://github.com/godotengine/godot/issues/7080#issuecomment-379563833
