### ISSUE TITLE
set_pressed in button don't work

### ISSUE THREAD

**Issue by supermoaaa** [godotengine/godot#33854]
**Godot version:**

**OS/device including version:**
win7 32bit godot 3.2 beta2
**Issue description:**
the property set_pressed(value) in base button haven't any effect 

for more information you can see my post on this forum
https://godotforums.org/discussion/comment/30367#Comment_30367

**Comment by codecustard** [comment]
The issue seems to stem from the fact that if toggle_mode is false, `set_pressed()` will immediately exit and do nothing. Does set_pressed work if you try enabling toggle mode? `set_toggle_mode(true)`

**Comment by Calinou** [comment]
@codecustard I guess it'd make sense to print an error message when using `set_pressed()` with a non-toggle button.

**Comment by supermoaaa** [comment]
but why not make it work with no toggle mode ??

will be more intuitive to manipulate
the interface with an exotic controller or a midi interface

and it's work with toggle mode

**Comment by TheSHEEEP** [comment]
I also fail to see the point in not allowing any button that can be pressed (aka every button ever) to have a pressed state that can be toggled.

**Comment by Calinou** [comment]
@TheSHEEEP What would the button do once it's set to be pressed? Would it stay pressed until it's clicked again?

**Comment by TheSHEEEP** [comment]
I would indeed say stay pressed until clicked again (or until set_pressed with false).
There are a bunch of default behaviours possible here, any of them are fine IMO (as long as they are documented).

**Comment by hammeron-art** [comment]
@Calinou I think he is suggesting it should do the same thing as clicking and holding it with the mouse. It keeps the down state until you release it.

It should at least perform the same actions as clicking it; fire events, call the virtual methods, change to the down state for the current frame, etc. Currently, we have to simulate an Input event to press a button with code. It could be made easier if set_pressed() worked for non-toggle button too.

**Comment by TheSHEEEP** [comment]
Actually, if such a function should call triggers is a wholly different question.
Either way, it wouldn't be a problem to disconnect from triggers for a moment if that wasn't desired.

**Comment by hammeron-art** [comment]
There is disconnect function for this. Pressing the button with code should have the same effect as pressing it with input. In case you are looking just for the visual changes, you can use custom styleboxes.

**Comment by Calinou** [comment]
@hammeron-art If we change the pressed state for a single frame only, it might not be visible at all if the game runs fast enough :slightly_smiling_face:

**Comment by j5E01** [comment]
Using official 3.2 release I am not getting set_pressed() to work using textureButtons with toggled property enabled. Just thought I should submit some feedback, as the conversation above is only regarding buttons _without_ the toggled property checked.
