### ISSUE TITLE
Index line=17 out of size when creating new script

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#33853]
**Godot version:**
3.2.beta.custom_build. 083d088de

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
When I create new script in new project, then Godot show this error:
```
ERROR: times_line_wraps: Index line=17 out of size (text.size()=17)
   At: scene/gui/text_edit.cpp:4328.
ERROR: times_line_wraps: Index line=17 out of size (text.size()=17)
   At: scene/gui/text_edit.cpp:4328.
```
This happens only from time to time

**Steps to reproduce(sometimes works):**
1. Create new project
2. Create new node
3. Create and attach script to node(it automatically open script editor)
4. Close script
5. Open script again

**Comment by pouleyKetchoupp** [comment]
I've actually reproduced this issue systematically when working on PR #33760 and made a simple fix. I'm going to extract it from there and make a separate PR.
