### ISSUE TITLE
"Debug" menu in top bar hides on click while its set not to

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#33850]
**Godot version:**
636bc5c

**Issue description:**
I noticed that the "Debug" menu in the the top bar of the editor hid itself on click, I thought to myself that since its only items where checkboxes, it would be better if it stayed even after clicking an item, but when I inspected the code, it was already set to that:
https://github.com/godotengine/godot/blob/636bc5c32f07050fb387a7f8f5f78f7dc9aef7be/editor/editor_node.cpp#L6124

But it still hides after clicking an item, ignoring the setting.

**Comment by pouleyKetchoupp** [comment]
Looks like there's a separate property `hide_on_checkable_item_selection` for checkable items.

**Comment by avril-gh** [comment]
additionally
- state of debug menu check boxes are not saved
- remote debug (eg. scene changes) does not work with android

**Comment by pouleyKetchoupp** [comment]
@avril-gh 
> - state of debug menu check boxes are not saved.

Can you open a new issue for this with more details about your expectations?

> - remote debug (eg. scene changes) does not work with android over wifi

Is it the same as this issue? #32814

**Comment by avril-gh** [comment]
@pouleyKetchoupp

after last merge its ok now. Thank you
