### ISSUE TITLE
Theme changes don't take effect immediately

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33866]
**Godot version:**
3.2 beta2

**Steps to reproduce:**
1. Create a Label
2. Assign it a Theme
3. Change label font color in that theme
4. It doesn't update until you change scene tab and back
![w6yg69oaK1](https://user-images.githubusercontent.com/2223172/69505201-e72fcf00-0f28-11ea-9dc8-9623537fd465.gif)

**Comment by akien-mga** [comment]
Still reproducible in 3.2.3-stable.

**Comment by seppoday** [comment]
Bug still exists in 3.3-stable

**Comment by KoBeWi** [comment]
Fixed in 4.0
