### ISSUE TITLE
Project becomes unopenable (in editor) if you set Message Queue Size to a low number.

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#33868]
**Godot version:** v3.2.beta2

**OS/device including version:**
Intel Core i7-4790K CPU
16GB ram
Windows 8.1 64bit

**Issue description:**
This is probably not something someone should be doing anyway, so I'm sure this is a low priority issue.
When changing the value the editor tells you to save and restart to apply changes, do that and you can no longer open your project to even change it back. You must manually edit the ``project.godot`` file to change the setting so your project can be opened again.

**Steps to reproduce:**
1. Start new project
2. Project Settings -> Memory -> Limits -> Message Queue -> Max Size Kb -> change to a low number.
3. Click save and restart

Godot editor will stay at the loading screen while the console endlessly floods with messages.
![loading screen](https://user-images.githubusercontent.com/15337628/69510947-cc924000-0f92-11ea-9947-f3aaa5977942.png)
![console](https://user-images.githubusercontent.com/15337628/69510971-df0c7980-0f92-11ea-9976-491898ea75a9.png)
![console2](https://user-images.githubusercontent.com/15337628/69510975-e0d63d00-0f92-11ea-8067-13e6a25491bb.png)

**Comment by slapin** [comment]
I think editor should be intelligent enough to check project settings sanity and that should be unit tested. Looks like good newbie onboarding work to do.

**Comment by RaTcHeT302** [comment]
This is pretty bad, there should just be a basic limit by default. Which shouldn't allow you to go this low.

**Comment by RaTcHeT302** [comment]
> 
> 
> I think editor should be intelligent enough to check project settings sanity and that should be unit tested. Looks like good newbie onboarding work to do.

I think that's overly complicated, just limit what values you can use.

**Comment by slapin** [comment]
Values like this can change with changes to editor code, changing some
constant every time is tedious and prone to error.
Adding simple test which would run at CI time to make sure this (and
other similar values) are correct is not too hard job.
Also using project values for editor might not be good idea at all as
requirements for these might be quite different.
Series of shortcuts like these often make people chose another
software due to high use costs.

**Comment by Calinou** [comment]
On paper, it makes sense to use an hardcoded value in the editor, but remember that the editor can run tool scripts. If those tool scripts require a raised value, you won't be able to benefit from the raised value in the editor.

Therefore, I think we should rather add a setting hint to prevent decreasing the value below the default.

**Comment by slapin** [comment]
This is why I think editor could autotune queue size in tool mode which is just a few lines of code.
The minimal thing which could be done - use constant for editor to run. In case of tool scripts, print meaningful error message. If scene can't be run with tools it is fine, leaving user clueless is not. Nice dialogue asking to reset value to default is a must as first step. Not being able to get perfect solution does not mean good one can't be found.

**Comment by akien-mga** [comment]
Superseded by #35653.
