### ISSUE TITLE
(Cosmetic) (Minor) UI Elements, Leak Out or Overlap on Each Other, When Using, Non Standard, Font Sizes

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#33874]
Godot 3.1.1

On the Top Left. Select Editor, Editor Settings.
Under Interface, Select Editor.
Set the Main Font Size to 16.
https://i.imgur.com/8RwSYxF.png
https://i.imgur.com/wxOkaZN.png

Font Size 20
https://i.imgur.com/R7Po11j.png
https://i.imgur.com/zPgY5Bk.png
https://i.imgur.com/Mnp2JtK.png
https://i.imgur.com/zGm8KoO.png
https://i.imgur.com/ztuDE2f.png
https://i.imgur.com/uTKSBg1.png
https://i.imgur.com/pbuwM8k.png

I think this is confusing behaviour for new users, I've never used Godot, and to me it seemed like the UI was broken at first, as I'm used to most user interfaces fixing themselves, without having to restart the whole program. 

I didn't find restarting Godot to be intuitive, and while I did figure out what was going on, I think this problem should be adressed. 

Even the most minor of issues, can put off new users from using the engine in my mind.

I think this message lacks clarity, as I wasn't really sure what it really ment, until I restarted the whole engine.
https://i.imgur.com/OMVUvGW.png

I think this should be fixed, it's janky as hell, and even experienced users once in a while can get confused by weird one time behaviours, and I really think that, such visible problems shouldn't be there. Anyway, ideally just, update the UI, without forcing a restart, or something, I don't know.

I know that a lot of people are gonna complain that, this is such a minor problem, that's not even worth bringing up, but I really want to point out such issues, as a new user, because more often than not, these "minor" problems add up, and they all start to pile up in the future, and it can have a larger impact on everything else. 

I also think it's a very good idea, to provide an enjoyable, and intuitive first time user experience, with the least amount of jank possible. I think the engine should be fun and enjoyable to use at it's core.

I'm not gonna be able to use Godot for the first time ever again, and I hope people don't underestimate such feedback. I hope people won't dismiss this, just because it seems like a "minor" or "not important" problem at a first glance.

I would fix this myself, but I'm not experienced enough, sorry.

**Comment by RaTcHeT302** [comment]
While I wrote that, I actually had a small idea, as to how to help users out.

Just add one extra warning, if you detected that the font sizes have been changed.
![oaT70Ob](https://user-images.githubusercontent.com/43797325/69540844-63113200-0f90-11ea-9a57-5f870a0b3dd3.png)

This would only be a temporary thing, but at least there would be some feedback.

**Comment by girng** [comment]
Hi @RaTcHeT302! If you have time, please reduce your issue, it will help a lot. To my understanding, it seems like when modifying the font size for the Editor, some UI elements are not updated correctly.

**Comment by Calinou** [comment]
Changing the message to fit specific settings would require a lot of work compared to the gain.

**Comment by aaronfranke** [comment]
> as I'm used to most user interfaces fixing themselves, without having to restart the whole program.

Like what? If I change themes or similar settings on Windows or Linux, I fully expect to have to restart some apps or even the whole system to apply the changes. I don't see the issue with requiring users to restart the editor to correctly apply these changes.

**Comment by Calinou** [comment]
Closing, as there is already a hint to restart the editor after changing the font size.
