### ISSUE TITLE
(Cosmetic) Allow Favourites, To Be Deleted (Destructive), To Be Hidden (Non Destructive)

### ISSUE THREAD

**Issue by RaTcHeT302** [godotengine/godot#33879]
Right Clicking on the Favourites, does nothing at all. I think it's inconsistent behaviour.
https://i.imgur.com/sckYjQV.png

I think the Favourites, should be it's own folder, and I think users should be allowed to either delete it (destructive changes) or to hide it (non destructive changes).

**Comment by akien-mga** [comment]
This is not a bug report, please open such proposals on the dedicated repository: https://github.com/godotengine/godot-proposals
