### ISSUE TITLE
Rename "Default_Env.tres" to Something More Obvious

### ISSUE THREAD

**Issue by RaTcHeT302** [godotengine/godot#33877]
Something like, "Environmental Settings" or "Level Settings", or "Graphical Settings". 

I don't think having more clarity can hurt.
https://i.imgur.com/8O2DEJI.png

It also looks less scary to new users.
https://i.imgur.com/HlYY7P3.png
https://i.imgur.com/rO0Wzgi.png

**Comment by akien-mga** [comment]
This is not a bug report, please open such proposals on the dedicated repository: https://github.com/godotengine/godot-proposals
