### ISSUE TITLE
(Cosmetic) Allow "Res://" to be Renamed (Visually Only)

### ISSUE THREAD

**Issue by RaTcHeT302** [godotengine/godot#33878]
I think Res:// should be renamed, to use the name of the folder, the project is in, or it should be renamed to something generic, such "Resources".
https://i.imgur.com/hjnCEE4.png

You cannot rename the folder, even from a cosmetic point of view. Renaming it does nothing.
https://i.imgur.com/9g42U86.png

I think users should be allowed to rename it, even if it's only a visual thing.

**Comment by Zylann** [comment]
Why does it exist though? Could we simply remove it and just straight display what's inside?

**Comment by akien-mga** [comment]
This is not a bug report, please open such proposals on the dedicated repository: https://github.com/godotengine/godot-proposals
