### ISSUE TITLE
PackedScene data type support for exported array

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3388]
Currently it's impossible to put PackedScene into an exported array. It would be neat to have support for this data type. At the moment these types are supported: 
![packedscenearray](https://cloud.githubusercontent.com/assets/6129594/12422155/c2aa4d66-bec5-11e5-98c6-4735fc4bc30f.png)

**Comment by vnen** [comment]
The `Object` type accepts a PackedScene, along with any other type of resource.

**Comment by kubecz3k** [comment]
@vnen thanks, haven't  seen this :) But in this case I think it would be reasonable if godot editor would allow to choose resource filepath via some kind of filemanager.

**Comment by vnen** [comment]
The Object type does allow you to select a file. But maybe a `Resource` type would make more sense.

**Comment by kubecz3k** [comment]
@vnen Well I assume, it allows to select a file, but you need to write filepath manually:
![arraypackedscene mp4](https://cloud.githubusercontent.com/assets/6129594/12424521/d4dd9faa-bed0-11e5-9ab9-12622e5ac827.gif)

**Comment by vnen** [comment]
Instead of selecting "new PackedScene", go to the bottom of the list and select "Load".

![2016-01-19_14-32-40](https://cloud.githubusercontent.com/assets/5599796/12424954/a8cf422c-beb9-11e5-9845-07c227389b2a.png)

**Comment by kubecz3k** [comment]
@vnen you are the best :+1: :)
