### ISSUE TITLE
Add a "View" Drop Down Menu to Customize the Visibility of Elements on the Interface

### ISSUE THREAD

**Issue by RaTcHeT302** [godotengine/godot#33880]
I think a View menu should be added, as I think it would be nice to sometimes be able to hide, things I won't be personally using. It can also be used, to make the UI, less overwhelming to new users, if they would like to have less stuff on the screen by default. I think this would be a useful feature for educators also.
![85Hit43](https://user-images.githubusercontent.com/43797325/69544074-a58a3d00-0f97-11ea-8611-83b15b1a77bb.png)

(yes, I know the mockup is garbage, it's just to get the idea across)

For the sake of consistency, I think everything should be able to be hidden. 

There should also a be a button, which resets all the windows, to the Default ones. Just in case a user screws up.

**Comment by akien-mga** [comment]
This is not a bug report, please open such proposals on the dedicated repository: https://github.com/godotengine/godot-proposals
