### ISSUE TITLE
Contextual Drop Down Menus on Right Click + Different Project Manager Layout

### ISSUE THREAD

**Issue by RaTcHeT302** [godotengine/godot#33882]
I think some menus badly need contextual menus, when you Right Click, in certain places. I think it goes agains the Windows design of doing things, it's janky as hell, and having this in some places, would improve the usability by a lot.

New Project
![new project 2 context menu](https://user-images.githubusercontent.com/43797325/69544610-bf784f80-0f98-11ea-924f-fe2fbcb9bdea.png)

![new project context menu](https://user-images.githubusercontent.com/43797325/69544487-8049fe80-0f98-11ea-90de-4e065f7f0d2d.png)

I think the buttons themselves, are also fairly awkward, and I would re-arrange the UI as an experiment like this. Edit is renamed to Open in Godot, Run to Run the Project.
![new ui](https://user-images.githubusercontent.com/43797325/69545033-a328e280-0f99-11ea-9e32-aa3b3914b16a.png)

I thought Edit was going to bring up some kind of window, to edit the project settings, but it actually opens the project in Godot, which I found really confusing.

I re-arranged the UI by functionality, instead of cluttering everything in one place.

The search bar gets more real estate, Scan is renamed to Update List (scan is really vague).

I find this to be much easier on my eyes, and I no longer have to deal with the information overload.
Here's a side by side comparison.

![sDB9owQ](https://user-images.githubusercontent.com/43797325/69545320-44179d80-0f9a-11ea-8988-cac1440f0d32.png)

**Comment by akien-mga** [comment]
This is not a bug report, please open such proposals on the dedicated repository: https://github.com/godotengine/godot-proposals
