### ISSUE TITLE
Accidentally Overwrote the Default Layout? No Warnings? No Fail Safes?

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#33884]
Did I permanently screw myself over? I used the name "Default" as it seemed like an obvious choice, but then all of sudden, with no warning, Godot suddenly told me, that I overwrote the Default layout in itself.

I think this is not intuitive at all. I really don't think it should be possible to do this, I received no warning when I did this, Godot just overwrote it.
![what](https://user-images.githubusercontent.com/43797325/69547321-09afff80-0f9e-11ea-92b1-6cec9bb3983e.png)

The default layout, should not be able to be overwritten, unless you edit the file by hand, with an external text editor.

**Comment by RaTcHeT302** [comment]
1. Top Left, Editor, Editor Layout, Save Layout.
2. Type Default
3. Select Save
4. What?

**Comment by novemberist** [comment]
For now you can simply click "Editor > Open Editor Settings Folder" and delete "editor_layouts.cfg" for a fresh start. I agree though, that you shouldn't be able to overwrite the Default layout.

**Comment by Anutrix** [comment]
Note: If you just delete the layout "Default" that you created and click default again, it will reset to default layout.
