### ISSUE TITLE
Separate signal name color

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33886]
**Godot version:**
3.2 beta2

**Issue description:**
Right now, signal names after `signal` keyword might have two different colors, depending on how they are declared.
![image](https://user-images.githubusercontent.com/2223172/69552220-63182e80-0f9e-11ea-9a8d-317e26f4e730.png)
Either white, from identifier or blue, from method call. It would be probably better and more consistent if they had their own color or at least use one color, no matter if declared with braces or not.

**Comment by jbuck3** [comment]
Since signal names are passed around as strings, maybe use the string color? Or a different shade of yellow?

**Comment by kimjiy9607** [comment]
Hi, I am trying to see if I can tackle this bug. What file can I possibly find the code about this part?

**Comment by Calinou** [comment]
@kimjiy9607 Look in `modules/gdscript/editor/gdscript_highlighter.cpp` and maybe `editor/plugins/script_text_editor.cpp`. Make sure the syntax highlighting is set to **GDScript** while testing the feature:

![image](https://user-images.githubusercontent.com/180032/73143688-81cd9b00-409d-11ea-998f-03b7b95a3cf3.png)

**Comment by kimjiy9607** [comment]
@Calinou Thank you so much!
