### ISSUE TITLE
No BILLING permission in export settings

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33890]
**Godot version:**
3.2 beta2

**Issue description:**
Not sure how Android permission list is constructed, but you can't find Billing there (`com.android.vending.BILLING`). You need to add it manually via "Custom Permissions", which is weird, because it's rather common one to use. IMO it should be there.

**Comment by cagdasc** [comment]
Hi,
I found [this](https://developer.android.com/google/play/billing/billing_library_releases_notes#release-1_0) But I can not see any google play billing library in source so how you can operate billing? If you must add the billing permission according to godot billing implementation, I will add missing permission to export list.

**Comment by KoBeWi** [comment]
Google Play told me to add billing permission to use payments and adding `com.android.vending.BILLING` to custom permissions helped, so I guess it should be on the export list.

**Comment by m4gr3d** [comment]
This issue was resolved when the play billing library was updated and moved to its [own repo](https://github.com/godotengine/godot-google-play-billing).
