### ISSUE TITLE
Project GUI Theme settings don't apply/inconsistent behavior

### ISSUE THREAD

**Issue by hammeron-art** [godotengine/godot#33902]
**Godot version:**
3.2.beta.custom_build.(fa4f52521)

**OS/device including version:**
Windows 10

**Issue description:**
I can set a custom default theme and font in Project Setting -> General -> GUI -> Theme. It affects the running game but it doesn't affect the nodes in the scene unless I restart the editor. Changes in the theme don't take effect immediately as well.

When I set a Control's theme directly, the changes update immediately. There should be no need to restart the editor to apply the default theme.

Also, the project's font always replaces the theme's even when it's null. For example, when the theme has a default font and there is no custom default font in the project settings, the theme's font is ignored.

**Steps to reproduce:**

- Create a customized theme resource with a customized default font
- Set a path to it in Project Setting -> General -> GUI -> Theme -> Custom
- It takes no effect in the editor
- Run the game
- It takes effect in the game but the theme's font is ignored

**Minimal reproduction project:**
[ProjectTheme.zip](https://github.com/godotengine/godot/files/3889359/ProjectTheme.zip)

**Comment by KoBeWi** [comment]
Related to #24067 and #33866

**Comment by kimjiy9607** [comment]
<img width="1258" alt="Screen Shot 2020-02-07 at 2 34 05 PM" src="https://user-images.githubusercontent.com/47190933/74059967-ffa37780-49b6-11ea-83ee-c0fcf6ee0570.png">
Hi,
I am trying to reproduce it but what do I from here?
Theme -> Custom and do I hit close button?
Thank you in advance!

**Comment by Calinou** [comment]
@kimjiy9607 You need to load a theme file (`.tres` or `.theme`) by clicking the folder icon on the right of the "Custom" property.

**Comment by Calinou** [comment]
> Also, the project's font always replaces the theme's even when it's null. For example, when the theme has a default font and there is no custom default font in the project settings, the theme's font is ignored.

This is being tracked in #36614.

**Comment by Misignu** [comment]
+1 The default theme is applied when reloading the editor. But it messes up some dialog windows.
![image](https://user-images.githubusercontent.com/28039158/108833362-794ed900-75ab-11eb-8143-1536988f174f.png)
![image](https://user-images.githubusercontent.com/28039158/108833966-4bb65f80-75ac-11eb-96af-68754cf4485c.png)
