### ISSUE TITLE
A strange feature or bug in shader.

### ISSUE THREAD

**Issue by Obr00007576** [godotengine/godot#33905]
**Godot version:3.1.1**

**OS/device including version:Windows10 **

**Issue description:I found that the SCREEN_TEXTURE in the shader is the entire node window but not viewport. It means that when I's using scroller of mouse to zoom out/in the node window, SCREEN_TEXTURE includes the entire game-maker's viewport but not game's viewport. It results in difficulty debugging some effects of shader. In the example of amberation shader, when zooming the node's window, the proportion of effect changes with the zooming amount(The effect even almost disappear, if I zoom too much in the node's window).If I want to check the real effect of shader, I should every time run the project.**

**Steps to reproduce:
code of shader(It is a shader of amberation effect):
```
shader_type canvas_item;
void fragment()
{
	COLOR.r=textureLod(SCREEN_TEXTURE,SCREEN_UV*(1.0+5.0*SCREEN_PIXEL_SIZE),0.0).r;
	COLOR.g=textureLod(SCREEN_TEXTURE,SCREEN_UV,0.0).g;
	COLOR.b=textureLod(SCREEN_TEXTURE,SCREEN_UV,0.0).b;
}
```
**

**Minimal reproduction project:**
![FJ8WDZ{6S7Y5D~DL9 HN0AC](https://user-images.githubusercontent.com/51303014/69593107-4238f300-1009-11ea-8d8d-8480cb887098.png)
![A{O1HXU%DPP_`GODYWLD%{0](https://user-images.githubusercontent.com/51303014/69593108-4238f300-1009-11ea-8c02-aae17209521c.png)

**Comment by clayjohn** [comment]
This is neither a bug nor a feature. You have misunderstood what SCREEN_UV represents. It is a variable that goes from 0-1 across the Viewport. So when reading from screen_texture, you get the actual screen shown on the Viewport. Not the Viewport as shown by the markers in the editor.

**Comment by Obr00007576** [comment]
> This is neither a bug nor a feature. You have misunderstood what SCREEN_UV represents. It is a variable that goes from 0-1 across the Viewport. So when reading from screen_texture, you get the actual screen shown on the Viewport. Not the Viewport as shown by the markers in the editor.

I think SCREEN_UV goes from 0-1 not accross the Viewport of the game but Viewport of the node editor. I will show you a picture. In this picture, obviously, the bottom left corner is black, which meas the UV_SCREEN at the bottom left corner is (0.0, 0.0). But the bottom left corner is not corner of Viewport of game but Viewport of node editor.
![2019-11-26](https://user-images.githubusercontent.com/51303014/69609420-6e359200-1064-11ea-8b4a-6a4276c9e1b9.png)

**Comment by clayjohn** [comment]
Yes.

**Comment by Obr00007576** [comment]
> Yes.

So, the prorotrtion of effect will change when zooming the viewport, because it just cuts a piece from the whole viweport of editor while those parameters won't change with zooming. Any method to avoid this case?

**Comment by bluenote10** [comment]
This is indeed somewhat surprising behavior, because it messes up the preview in the editor. I would have assumed that the editor is aware of the viewport area and the `SCREEN_UV` and `FRAGCOORD` built-in get normalized appropriately. But essentially it is only an issue of the editor.

![Peek 2019-12-29 21-05](https://user-images.githubusercontent.com/3620703/71562135-04ebd900-2a7f-11ea-8ecc-a872ff3e4b29.gif)

@Obr00007576 Perhaps you could rename this issue to something like _Editor viewport affects behavior of SCREEN_UV / FRAGCOORD_ to make it easier for others to find? I almost opened a new issue, and only found it by chance (generic title).

**Comment by hsandt** [comment]
Yes, a title like this would help. I found the issue thanks to content text search.

And for people who like this behavior for quick previewing, we could make it an option to select current viewport, or a specific one, or the editor viewport to apply shader preview.

In my case I was working with a subtle gradient so it was more disturbing than helpful. My results were asymmetrical when switching x to y and sometimes the gradient was almost invisible.

**Comment by Obr00007576** [comment]
> Yes, a title like this would help. I found the issue thanks to content text search.
> 
> And for people who like this behavior for quick previewing, we could make it an option to select current viewport, or a specific one, or the editor viewport to apply shader preview.
> 
> In my case I was working with a subtle gradient so it was more disturbing than helpful. My results were asymmetrical when switching x to y and sometimes the gradient was almost invisible.

So, it is not fixed so far? Or I should create a new issue with another titile. I've been not using godot for about a year. I nearly forgot about this issue. This odd behavior of the editor will be fixed?

**Comment by hsandt** [comment]
@Obr00007576 SInce you're not using Godot these days I reopened a new bug for Godot 4 myself, reusing your shader: https://github.com/godotengine/godot/issues/92311

@bluenote10 I couldn't make FRAGCOORD work (it was always (1, 1, 0, 0) causing color to be yellow) so if you want to test that you can add your own shader example on the issue.
