### ISSUE TITLE
"Cannot get ratio when minimum and maximum value are equal" error at run time

### ISSUE THREAD

**Issue by georgikoemdzhiev** [godotengine/godot#33907]
**Godot version:**
3.2 Beta 2 Mono
**OS/device including version:**
Manjaro/XPS 15 9560
**Issue description:**
When I run the project it throws the following error:
```
Godot_v3.2-beta2_mono_x11_64]$ Mono: Logfile is: /home/user/mono_logs/2019_11_25 19.51.24 (6867).txt
ERROR: get_as_ratio: Cannot get ratio when minimum and maximum value are equal.
   At: scene/gui/range.cpp:176.
```
**Steps to reproduce:**

1. Create a (mono) Project
2. Create a scene with Node2D root and add an icon (drag the Godot logo into the scene)
3. Attach a C# Script to the Node2D
4. Save; Build and run the project

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/3890770/project.zip)

**Comment by akien-mga** [comment]
I've seen that too in the current master branch (5ddce7a9d) on classical builds.

**Comment by akien-mga** [comment]
The error is raised due to the changes in #33583, so it indicates that something in the editor uses `min == max` for `Range`.

**Comment by me2beats** [comment]
still get the error
3.2.3 Windows
reproduce: set min and max to 0

**Comment by akien-mga** [comment]
Please open a dedicated issue with a reproduction project, this variant of the error was fixed a year ago.
