### ISSUE TITLE
Editor shows wrong string value for string export with choices

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#33914]
**Godot version:**

3.1.1.stable.custom_build

**OS/device including version:**

Linux 5.3.11-arch1-1 x86_64 GNU/Linux

**Issue description:**

An exported `String` with several choices but no assigned default will show the first choice rather than the true default value of `null`.

We should either:

1. Actually make the default equal to the first choice
2. Show an empty string in the editor to reflect that the actual value is `""`

This is similar to #25357.

I realize you can fix this by assigning a default value, but it is still a confusing issue you can lose time on because the editor is misleading.

**Steps to reproduce:**

```
extends Spatial

export(String, "red", "blue") var team
```

Initially, the editor shows "red" as the value, but it is really `""`

![1574771285](https://user-images.githubusercontent.com/2496231/69633786-e0838380-101e-11ea-8742-fdf5e23719f2.png)

Switch `team` to blue in the editor ...

![1574771292](https://user-images.githubusercontent.com/2496231/69633787-e0838380-101e-11ea-8db0-75423914744d.png)

... then switch it back to "red". Now the value is truly "red".
![1574771299](https://user-images.githubusercontent.com/2496231/69633788-e0838380-101e-11ea-964b-a4ac5682f9a6.png)
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Still reproducible in 3.2.3-stable.

I'd expect `team` to actually be `null` and not an empty string since it has no default value and no type hint. And the inspector should somehow show it as "Null", with the drop down to choose "red" or "blue" (and then no way to go back to null I guess, apart from using the revert button).

**Comment by akien-mga** [comment]
This is also still reproducible in the current master branch (cbcec0d0567b0b5e173f1e9f90f2c03317156275), with the following syntax:
```
@export_enum("red", "blue") var team
```

@vnen I think we should use the opportunity to break compat in 4.0 to fix this, if fixing it properly requires compat breaking changes. For example we could force this to default to the first value if no assignment is done, OR we could force users to assign a default value to such exported values which don't make sense without one.
