### ISSUE TITLE
ProjectSettings.localize_path eats `/` on relative path

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#33913]
Considering this function:

```gdscript
func localize_then_globalize():
    var path = "foo/bar/spam.txt"
    var localized = ProjectSettings.localize_path(path)
    var globalized = ProjectSettings.globalize_path(localized)
    print("localized: ", localized)
    print("globalized: ", globalized)
```

output:
```shell
$ ~/projects/godot/bin/godot.x11.tools.64 
Godot Engine v3.2.beta.custom_build.ae04d23cc - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
 
localized: res://foobarspam.txt
globalized: /home/emmanuel/projects/godot-python-2-electric-boogaloo/tests/helloworld_gd/foobarspam.txt
```

so `foo/bar/spam.txt` gets localized as `res://foobarspam.txt` (I would have expected `res://foo/bar/spam.txt`)
And globalizing this `res://foobarspam.txt` ends up in a different path than the original one...

**bonus point**

Running the same script but with `var path = /foo/bar/spam.txt` gives:
```shell
$ ~/projects/godot/bin/godot.x11.tools.64
Godot Engine v3.2.beta.custom_build.ae04d23cc - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
 
localized: /foo/bar/spam.txt
globalized: /foo/bar/spam.txt
```

This time the localization hasn't even occured.
This behavior may be valid (given it's complicated to convert an absolute path into a `res://`, especially if the absolute path doesn't point within the project directory), but I think it should be documented then.

**Godot version:**
3.2.beta.custom_build.ae04d23cc

**OS/device including version:**
Ubuntu 19.10

**Comment by akien-mga** [comment]
That's a regression which happened between 3.2 beta 1 and beta 2.

**Comment by akien-mga** [comment]
Regression from #33380 (CC @SaracenOne)

**Comment by touilleMan** [comment]
@akien-mga  Do you want me to submit a PR on this ?

**Comment by akien-mga** [comment]
That would be great yeah :)

An option is to revert #33380 but it appeared to address a valid issue, so a better fix might be needed to solve the regression while keeping the bugfix.

**Comment by SaracenOne** [comment]
Always the challenge of bugfixes, the many intended consequences which can reverberate in other ways...
