### ISSUE TITLE
Signal declaration is not marked safe

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33927]
**Godot version:**
3.2 beta2

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/69676869-f1290d80-10a1-11ea-9a4a-e8d52b87fb4b.png)

**Comment by Zylann** [comment]
`signal step_finished(idx)` has no indication as to what `idx` is though

**Comment by dalexeev** [comment]
![191128-1](https://user-images.githubusercontent.com/47700418/69797494-d7daab00-11e0-11ea-8eea-df70a805c16e.png)

Two more errors:
1. Multiline arrays.
2. Empty lines and comment lines after unsafe lines.

**Comment by akien-mga** [comment]
Still reproducible in 3.2.3-stable.

**Comment by ThakeeNathees** [comment]
class level variable declaration isn't marked as safe

![Capture copy](https://user-images.githubusercontent.com/41085900/94804405-66731680-0408-11eb-99dc-7fc3cfc9cef1.jpg)

**Comment by akien-mga** [comment]
Seems fixed in `master`, and #42460 fixed it for 3.2.

For the other issues with lines not properly marked as safe, please open dedicated issues.
