### ISSUE TITLE
Harmful new error "start: Timer was not added to the SceneTree!"

### ISSUE THREAD

**Issue by x2f** [godotengine/godot#33929]
**Godot version:** 3.2 beta2

**OS/device including version:** Windows 10

**Issue description:** Overzealous error (?)

**Steps to reproduce:** call start() on a timer prior to add the timer to the scene tree

For now the biggest pain when porting an existing project to 3.2. Timer.start() is called in the constructor in several objects, which then are added in the scene tree. This workflow was working fine in 3.1. Fixing this is a  pain, as it requires a convoluted logic to start the timer later (it is not as simple as this, since the timer is not always started, depending on some state).

On the other side, this error seems to only prevent forgetting adding a started timer to the scene. But then it would only result in the timer never timing out, right? This seems easy to detect when coding, and should not trigger an error IMO.

So I would like to know if you would consider removing this error...

**Comment by bojidar-bg** [comment]
You could use `Timer.autostart = true` for this purpose, no?

**Comment by KoBeWi** [comment]
Yep, just change `Timer.start()` to `Timer.autostart = true` and it will work.
https://docs.godotengine.org/en/latest/classes/class_timer.html#class-timer-property-autostart

Starting Timers before adding to tree is wrong (Timers don't process outside tree), so it's no longer possible. You can still achieve the same functionality without convoluted code.

**Comment by x2f** [comment]
Thanks for the answers. May I suggest changing the error string to "start: Timer was not added to the SceneTree! (Consider setting autostart to true instead)."

**Comment by KoBeWi** [comment]
> May I suggest changing the error string to "start: Timer was not added to the SceneTree! (Consider setting autostart to true instead)."

This probably makes sense.

**Comment by x2f** [comment]
Okay, please see the pull request. I set the additional text to "(To fix: add to SceneTree before or set autostart to true instead.)". Hope it makes sense and is not too long.

**Comment by DisDoh** [comment]
To add the name of the Timer in question would be useful.
Actually searching which one is not ok...
