### ISSUE TITLE
GraphEdit zoom causes exponential displacement of added nodes

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#33935]
**Godot version:**
3.2
**OS/device including version:**
ArcoLinux
**Issue description:**
Zooming in or out in VisualScript, panning away from the origin scroll offset, and attempting to add any graph node to the script will result in the node being spawned far away from where it should be located; this problem gets worse the further from 0, 0 you get.

I ran into this problem when attempting to implement a game mechanic with GraphEdit, which prompted me to see if VisualScript had this problem solved, but it's the same deal; there's seemingly no code for GraphEdit which makes it simple to translate the mouse's position to an offset on the graph, taking into account the graph's scroll offset and zoom.

**Comment by codecustard** [comment]
Dividing your offset by `get_zoom()` might be what you're looking for. Does that help?

**Comment by somnivore** [comment]
@codecustard That does the trick, thanks a ton.

**Comment by akien-mga** [comment]
Fixed by #34107.
