### ISSUE TITLE
Camera2D in a viewport while running as an editor plugin doesn't work

### ISSUE THREAD

**Issue by Nukiloco** [godotengine/godot#33931]
**Godot version:**
Godot v3.1.2

**OS/device including version:**
Windows 10

**Issue description:**
Whenever running as an editor plugin, Camera2D nodes won't work in a separate viewport.

**Steps to reproduce:**
1. Make an EditorPlugin.
2. Make a scene with a Viewport, Sprite and a Camera2D node.
3. Add a script to make the Camera2D node move around.
3. Run the editor plugin and try to move the camera around.
4. The Camera2D node doesn't work at all.

**Minimal reproduction project:**
https://github.com/Flairieve/GraphicsEditor/

**Comment by novemberist** [comment]
I don't think your Camera2D script will actually run, unless you make it a tool, too. At least if I understand this article correctly: [](https://docs.godotengine.org/en/3.1/tutorials/misc/running_code_in_the_editor.html)

**Comment by Flairieve** [comment]
The camera script isn't a tool script on purpose so it doesn't run in the editor scene. I have tried it before as a tool script and that didn't work also. I think it's something that has to do with using viewports in the editor.

**Comment by bojidar-bg** [comment]
You might have to use a custom script which modifies the viewport's "canvas_transform", as Camera2D is specifically made to not run while `Engine.editor_hint` is true.

**Comment by Flairieve** [comment]
If that's the case then shouldn't camera nodes be allowed to run in the editor if they are under a viewport?

**Comment by bojidar-bg** [comment]
The thing in the middle of the editor screen is already a viewport, so this would require some changes to how viewports work.

**Comment by Flairieve** [comment]
Wait so the editor can only run a couple of viewports at a time?

**Comment by Flairieve** [comment]
Even with that, you should be able to use a viewport with a camera in it as an editor plugin.
