### ISSUE TITLE
Mono Android export WebClient.DownloadString() method not working.

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#33934]
**Godot version:**  3.2 Beta 1

**OS/device including version:** Windows 10 Host / Android Emulator

**Issue description:** 
In my android project, I have a small task of reading an html source code into a string via WebClient.DownloadString method. When I do so, I get the following ADB Logcat output:

```
11-27 11:57:45.111 24793 24818 I godot   : System.Net.WebException: An exception occurred during a WebClient request. ---> System.NotSupportedException: The URI prefix is not recognized.
11-27 11:57:45.111 24793 24818 I godot   :   at System.Net.WebRequest.Create (System.Uri requestUri, System.Boolean useUriBase) [0x000ae] in <748af814b14a45f7803e4fe5c9300d51>:0
11-27 11:57:45.111 24793 24818 I godot   :   at System.Net.WebRequest.Create (System.Uri requestUri) [0x00014] in <748af814b14a45f7803e4fe5c9300d51>:0
11-27 11:57:45.111 24793 24818 I godot   :   at System.Net.WebClient.GetWebRequest (System.Uri address) [0x00000] in <748af814b14a45f7803e4fe5c9300d51>:0
11-27 11:57:45.111 24793 24818 I godot   :   at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x0000d] in <748af814b14a45f7803e4fe5c9300d51>:0
11-27 11:57:45.111 24793 24818 I godot   :    --- End of inner exception stack trace ---
11-27 11:57:45.111 24793 24818 I godot   :   at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x0006e] in <748af814b14a45f7803e4fe5c9300d51>:0
11-27 11:57:45.111 24793 24818 I godot   :   at System.Net.WebClient.DownloadString (System.Uri address) [0x00011] in <748af814b14a45f7803e4fe5c9300d51>:0
11-27 11:57:45.111 24793 24818 I godot   :   at System.Net.WebClient.DownloadString (System.String addre
```
I have tried different URL's and different methods to read any html source code into a string but no chance. I think we might have a bug here.

**Comment by akien-mga** [comment]
Did you enable relevant permissions for Internet access on Android?

**Comment by dunyakilavuz** [comment]
Thanks for your fast response @akien-mga. I've got Access Fine Location, Network State and Internet checked but I think Internet access alone would be sufficient as well.

**Comment by ricardoalcantara** [comment]
@dunyakilavuz It looks like the URL is not right, can you run it on desktop? How are you executing that line? can you create an demo to replicate it?

**Comment by dunyakilavuz** [comment]
@ricardoalcantara Thanks for your response! I am afraid in my case adding the "http://" part doesn't solve the issue. When I run the app on the editor it parses the html code just fine, however when I run it on the android with the same configuration I get an error.

 I have prepared a small sample project to demonstrate the issue. If you're able to try it, try running it on both the editor and an android emulator. You should see that it prints; a html source code on the editor side and an exception error on the android side.

[SampleProject.zip](https://github.com/godotengine/godot/files/3900524/SampleProject.zip)

If you can manage to run it on both platforms maybe I am doing something wrong? Hopefully we can find out.

**Comment by KoBeWi** [comment]
> Windows 10 Host / Android Emulator

Does it happen on real device too?

**Comment by dunyakilavuz** [comment]
@KoBeWi Sadly I don't own an android device that I can freely test on. However I borrowed a friends phone and tried the sample project on it real quick. The app crashed on the fetching source code phase but I couldn't get the crash logs to make sure. At this point I'm uncertain but I think it happens on real devices as well.

**Comment by ricardoalcantara** [comment]
@dunyakilavuz I could test your project on my phone, it's a `Moto g 5s plus`, and WebClient is not working indeed, but I got another Stacktrace.
```
System.Net.WebException: An exception occurred during a WebClient request. ---> System.TypeInitializationException: The type initializer for 'System.AndroidPlatform' threw an exception. ---> System.TypeLoadException: Could not load type 'Android.Runtime.AndroidEnvironment' from assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
  at (wrapper managed-to-native) System.RuntimeTypeHandle.internal_from_name(string,System.Threading.StackCrawlMark&,System.Reflection.Assembly,bool,bool,bool)
  at System.RuntimeTypeHandle.GetTypeByName (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark, System.Boolean loadTypeFromPartialName) [0x0008d] in <3b08f2249ec641d8b691b85bde6bce48>:0 
  at System.RuntimeType.GetType (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark) [0x0000e] in <3b08f2249ec

System.Net.WebException: An exception occurred during a WebClient request. ---> System.TypeInitializationException: The type initializer for 'System.AndroidPlatform' threw an exception. ---> System.TypeLoadException: Could not load type 'Android.Runtime.AndroidEnvironment' from assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
  at (wrapper managed-to-native) System.RuntimeTypeHandle.internal_from_name(string,System.Threading.StackCrawlMark&,System.Reflection.Assembly,bool,bool,bool)
  at System.RuntimeTypeHandle.GetTypeByName (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark, System.Boolean loadTypeFromPartialName) [0x0008d] in <3b08f2249ec641d8b691b85bde6bce48>:0 
  at System.RuntimeType.GetType (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark) [0x0000e] in <3b08f2249ec
```
I made my test using
Godot 3.2 Beta 2

However I could use HttpClient with success, I have a long time I don't use WebClient, I guess since HttpClient came out, I didn't dig in too deeply in that stacktrace, and since I can use HttpClient I would leave this issue here and move on to use HttpClient instead.

I also tested it with HTTPRequest (godot's builtin HTTP request implementation) with no issue.

I am sending back your sample project updated to use HttpClient and HTTPRequest too, 

![Screenshot from 2019-11-30 11-52-36](https://user-images.githubusercontent.com/2466466/69902073-26668180-1368-11ea-9412-60495c886bb9.png)
I had to add the System.Net.Http reference to make it work

[SampleProject2.zip](https://github.com/godotengine/godot/files/3907201/SampleProject2.zip)

**Comment by dunyakilavuz** [comment]
@ricardoalcantara Both HttpClient and HTTPRequest are working for me as well. I guess there is no need to use WebClient instead of these two. Closing the issue as it's solved, thank you so much for your time.

**Comment by neikeq** [comment]
I don't know about the exception in the original description, but #34101 potentially fixes this one @ricardoalcantara mentioned:

>```
>System.Net.WebException: An exception occurred during a WebClient request. ---> System.TypeInitializationException: The type initializer for 'System.AndroidPlatform' threw an exception. ---> System.TypeLoadException: Could not load type 'Android.Runtime.AndroidEnvironment' from assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
>  at (wrapper managed-to-native) System.RuntimeTypeHandle.internal_from_name(string,System.Threading.StackCrawlMark&,System.Reflection.Assembly,bool,bool,bool)
>  at System.RuntimeTypeHandle.GetTypeByName (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark, System.Boolean loadTypeFromPartialName) [0x0008d] in <3b08f2249ec641d8b691b85bde6bce48>:0 
>  at System.RuntimeType.GetType (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark) [0x0000e] in <3b08f2249ec
>
>System.Net.WebException: An exception occurred during a WebClient request. ---> System.TypeInitializationException: The type initializer for 'System.AndroidPlatform' threw an exception. ---> System.TypeLoadException: Could not load type 'Android.Runtime.AndroidEnvironment' from assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
>  at (wrapper managed-to-native) System.RuntimeTypeHandle.internal_from_name(string,System.Threading.StackCrawlMark&,System.Reflection.Assembly,bool,bool,bool)
>  at System.RuntimeTypeHandle.GetTypeByName (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark, System.Boolean loadTypeFromPartialName) [0x0008d] in <3b08f2249ec641d8b691b85bde6bce48>:0 
>  at System.RuntimeType.GetType (System.String typeName, System.Boolean throwOnError, System.Boolean ignoreCase, System.Boolean reflectionOnly, System.Threading.StackCrawlMark& stackMark) [0x0000e] in <3b08f2249ec
>```

**Comment by neikeq** [comment]
Can anyone still reproduce this in 3.2 beta4?

**Comment by ricardoalcantara** [comment]
@neikeq I tested the SampleProject2.zip in 3.2 beta4 and it's worked fine for me.

**Comment by neikeq** [comment]
I will assume this is fixed then. If any one still experiences this we can re-open.
