### ISSUE TITLE
Incomplete intellisense / dropdown method list

### ISSUE THREAD

**Issue by jtrlombard** [godotengine/godot#33947]
In Godot v3.1.1. GDScript, when typing some method name, for example "instance", it does not appear anywhere in the dropdown help list.

**Comment by Calinou** [comment]
The `instance()` method will only appear if the object you're calling it on is a PackedScene. Can you post the script in which autocompletion fails?

Also, remember that if the script you're currently editing has errors, you must solve them before autocompletion appears again.

**Comment by KoBeWi** [comment]
This is too vague, so closing. You can reopen if you have some particular example with reproduction steps. Also be sure to try 3.1.2.
