### ISSUE TITLE
NavigationPolygon use wrong values in x - just 16px

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#33942]
**Godot version:**
3.2beta
**OS/device including version:**
Win 7
**Issue description:**
Wrong values in export resources
Wrong values during navigation_2d.cpp

**Steps to reproduce:**
Using NavigationPolygonInstance make a polygon and export it.
Debug navigation_2d.cpp into E->_value->navpoly->reference

**Minimal reproduction project:**
In my example the value in x is with 16px of offset
expected: PoolVector2Array( 9344, 5120,.....)
current value: PoolVector2Array( 9328, 5120,.... )

**Comment by KoBeWi** [comment]
Reproduction project?

**Comment by git2013vb** [comment]
I was debugging the code so I saw this issue. Honestly I didn't investigate further but somewhere in the code someone added 16px ... Why? It was difficult to keep track all values between debug and resource file. Btw for me is a bug.

**Comment by Calinou** [comment]
@git2013vb Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by git2013vb** [comment]
The "minimal reproduction project" is .. Godot :)

**Comment by Calinou** [comment]
@git2013vb I would still like you to upload a minimal reproduction project, as there may be quirks in the specific project that cause the issue to pop up.

**Comment by git2013vb** [comment]
[NavPolOffset.zip](https://github.com/godotengine/godot/files/4528904/NavPolOffset.zip)

```
[gd_scene load_steps=2 format=2]

[sub_resource type="NavigationPolygon" id=1]
resource_local_to_scene = true
vertices = PoolVector2Array( 346, 44, 584, 137, 457, 294, 206, 128 )
polygons = [ PoolIntArray( 0, 1, 2, 3 ) ]
outlines = [ PoolVector2Array( 206, 128, 457, 294, 584, 137, 346, 44 ) ]

[node name="Node2D" type="Node2D"]

[node name="Navigation2D" type="Navigation2D" parent="."]

[node name="NavigationPolygonInstance" type="NavigationPolygonInstance" parent="Navigation2D"]
navpoly = SubResource( 1 )

```
If I remember correctly "vertices" and "outlines" are the two sections where dev have to looking in

Have fun

**Comment by tom-jk** [comment]
Can't reproduce (insofar as I understand the issue) in 3.2.2.stable (non-mono).

The given project shows the navpoly in the correct place specified in the file (no -16px on load).
Save and reload, still correct (no -16px on save).
Save navpoly as resource, file correct (no -16px on save resource).
Load navpoly, also correct (no -16px on load resource).

Also did these steps with a larger navpoly (approx 30000x15000px), also no offset problems.

Also checked values in-game, looks fine.

@git2013vb, can you still reproduce this problem?

**Comment by KoBeWi** [comment]
Closing as per above comment (and lack of response from OP).
