### ISSUE TITLE
Scenes are unable to remember it's nodes fold state

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3395]
**Edit: from Eska tests it seems this bug is related to scene inheritance**
Currently when we are opening new scene all the nodes in the tree in 'scene' tab are unfolded at the start. I think the scene should remember 'fold status' between sessions. Eventually all the nodes below first level should be folded by default.
Further more if we change scene and come back the tree always will be unfolded  - despite the fact we have already folded it in mean time: 
![scenetreefolded](https://cloud.githubusercontent.com/assets/6129594/12455387/c72ecc96-bf9b-11e5-9958-23662eb34261.gif)

**Comment by Ace-Dragon** [comment]
Yes, this would be quite useful to have by default, especially as scenes get bigger.

I don't think it should be too hard a task for the developers and would be a good fit for the upcoming usability release.

**Comment by bojidar-bg** [comment]
I don't think this should be default, as it is counter-intuitive on small scenes. I would propose this to go into the settings.

**Comment by Ace-Dragon** [comment]
Could there be a threshold value that folds the tree or not based on the number of nodes that are inside it?

You do have a point of this possibly being counter-intuitive for some scenes, but then you would have the far larger scenes people might have for game levels.

**Comment by kubecz3k** [comment]
Personally I assume it would be the best to just remember fold state between sessions, but if this is problematic I guess everyone will be pleased for an option in editor settings.

**Comment by neikeq** [comment]
Could another option be a keyboard shortcut to _**Collapse All**_ (e.x.: _Ctrl Shift +_)/_**Expand All**_ (e.x.: _Ctrl Shift -_)?

**Comment by reduz** [comment]
at some point it did remember fold state..  maybe it broke?

**Comment by akien-mga** [comment]
> at some point it did remember fold state..  maybe it broke?

Maybe it was in the scene metadata that were for the major part removed? There is still some (IMO) VCS-annoying metadata about whether the panel to open is 2D, 3D or Script. I think we should keep metadata as they are useful but make sure to save them in the user datadir (~/.godot) instead of hardcoding them in scene files.

**Comment by reduz** [comment]
no, I think it was saved in the node metadata, just like bone information
and other stuff.. will have to check it

**Comment by eska014** [comment]
Maybe another `.tscn` parser bug, `_edit_group_`, `_edit_lock_` also seem to be affected by this

**Comment by reduz** [comment]
it works on scn but fails on tscn?

**Comment by neikeq** [comment]
Just tested and it remembers the folded state fine. Maybe 2493cb1 fixed it?

**Comment by reduz** [comment]
no i don' t thinl that's related..

**Comment by eska014** [comment]
Gave it a test with current master head, looks like it only happens for instanced scenes, independently of file type. Not sure if that is even unintended

**Comment by kubecz3k** [comment]
@eska014 looks like you are right, but I don't think it might be intended.

**Comment by chanon** [comment]
This is a big productivity killer for me. If it is not fixed at least a collapse all button would be nice.

**Comment by kubecz3k** [comment]
@eska014 suggested this happens only for inherited scenes, well I can tell for sure that this is not a rule, I can tell for sure some bigger 'normal' scenes in my project are affected as well.

**Comment by kubecz3k** [comment]
Was testing this today, and will test more in next days. So far it works splendidly!
