### ISSUE TITLE
File API uses 32 bit integers

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#33962]
**Godot version:**
3.2 Beta 2

**OS/device including version:**

**Issue description:**
Godot.File methods such as `get_len()` and `get_buffer(int)` return/take 32 bit signed integers, meaning over ~2GB files cannot be read

**Steps to reproduce:**

**Minimal reproduction project:**

Related to #288

**Comment by bruvzg** [comment]
There's PR to address this #27247

**Comment by girng** [comment]
What kind of game asset is over 2GB?

**Comment by akien-mga** [comment]
> What kind of game asset is over 2GB?

That's not really relevant to the issue, but anyway:
```
$ du -sh projects/tps-demo/level/geometry/demolevel.dae
322M   projects/tps-demo/level/geometry/demolevel.da
```

That's just for the very small TPS demo level. Not 2GB, but not that far from this order of magnitude.

And more importantly, `.pck` packages can definitely be over 2GB: #27168.

**Comment by slapin** [comment]
Well, for your tetris you don't need this, I'm sure. But "not all games need this" banner is a bit rugged now, don't you think?

In general why set limits when you don't have to?
Also limits like this hit in unusual cases, when, for example you use Godot as a tool to prepare your game assets (you have a city in blend file, you export it and then generate all lods/annotation/paths, split it into chunks for loading in Godot as part of import process. This way you don't need to patch engine too much to implement tooling required to do your job. If you need to patch engine for everything, then what remains?

But I wonder that even this small limitaton relaxation has its resistance, imagine how hard it s to "sell" new features to people who don't want anything.

**Comment by akien-mga** [comment]
Closing as superseded by https://github.com/godotengine/godot-proposals/issues/400 to keep everything in one place.
