### ISSUE TITLE
Usage of area_shape_entered

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33977]
**Godot version:**
3.2 beta

**Issue description:**
I wanted to use `area_shape_entered` from Area2D, but had hard time figuring out how to use `area_shape` and `self_shape` to get their respective nodes. After some trying and Discording turns out that you need to do `shape_owner_get_owner(shape_find_owner(self_shape))`. It should be mentioned somewhere in Area2D's documentation (and Area too).

**Comment by matlawsky** [comment]
Can I work on that ?

**Comment by lakshay-angrish** [comment]
@KoBeWi 
The methods `shape_find_owner` and `shape_owner_get_owner` are part of the `CollisionObject2D` class, which `Area2D` inherits. Similarly, `Area` inherits `CollisionObject`. Maybe `Area` and `Area2D` docs should state that they inherit said methods. Would that be an appropriate fix?

**Comment by KoBeWi** [comment]
No, there should be an usage example in the docs. Simply mentioning the methods is not enough.

Just include my code snipped, saying this is how you can get the shape.
