### ISSUE TITLE
Script.reload() function break the game in case of error

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#33972]
**Godot version:**
3.1 and 3.2 b2

**OS/device including version:**
Linux Manjaro

**Issue description:**
When I try to load dynamic code at runtime I have the following problem:
I can create the script object on the fly and if it's all correct the script work, but if I have some error the game goes like in breakpoint state, give me the error in the console and if I press the button to continue it continue the execution of the game. In the documentation I found this:

> Reloads the script’s class implementation. Returns an error code.

But this also break the game and i think that wasn't the right behavior.

**Steps to reproduce:**
```
var script : = GDScript.new()
script.source_code = "extends Node2D\nfunc exec():\n\tprint(\"ok\"" # missing )
var error = script.reload() # give the error and break the game
print_request(error)
```

**Comment by FeralBytes** [comment]
@grevius5 does this also happen when the game is exported without debug?

**Comment by grevius5** [comment]
I have tried only in the editor, I think tomorrow I'll try with the export

**Comment by grevius5** [comment]
In the release without debug it work as aspected without breaking the game

**Comment by grevius5** [comment]
I think the problem is at this [line](https://github.com/godotengine/godot/blob/a5dcabbbfb2a0b9c6688ea0b6f788491f350f5da/modules/gdscript/gdscript.cpp#L572)

**Comment by KoBeWi** [comment]
Ok so this is actually not a bug. The editor debugger breaks on parse error, this is intended behavior. If you think it should be changed, [please open a proposal](https://github.com/godotengine/godot-proposals).
