### ISSUE TITLE
"CSV" import preset (for CSV files) doesn't work as default preset

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#33979]
**Godot version:**
3.2 beta2

**OS/device including version:**
W10

**Issue description:**
Setting CSV default import preset to "CSV" (instead of "CSV Translation") allow editor to import as "CSV" the selected file only

**Steps to reproduce:**
Create a blank project
create 4 CSV file, names file1.csv, file2.csv, file3.csv, file4.csv in project folder
go back to editor to allow autoimport: 4 errors are reported, one for each csv file, that's normal
![immagine](https://user-images.githubusercontent.com/47447512/69830761-8b19c300-1226-11ea-8a90-b8f9e55f7930.png)

select file1.csv,
click "import" tab
in "import" dropdown box you see "CSV translation": choose "CSV"
click "preset" button next ro the import dropdown box
select "set as default for CSV"
![immagine](https://user-images.githubusercontent.com/47447512/69830743-70dfe500-1226-11ea-9f7e-cfc410d5bd2e.png)

click "Reimport" button at the bottom 
click "Save scene, reimport and restart"
Now 3 import errors are reported: yes, they were 4 before, but I'm expecting no import errors.
[CSVtest.zip](https://github.com/godotengine/godot/files/3902992/CSVtest.zip)
![immagine](https://user-images.githubusercontent.com/47447512/69830711-4beb7200-1226-11ea-88cb-ede3679a3ae5.png)
![immagine](https://user-images.githubusercontent.com/47447512/69830726-5c9be800-1226-11ea-8343-2c7556458a15.png)

I'm expecting this:
![immagine](https://user-images.githubusercontent.com/47447512/69830779-a7b5fb00-1226-11ea-95f1-01b6d12b2644.png)

**Minimal reproduction project:**

[CSVtest.zip](https://github.com/godotengine/godot/files/3902993/CSVtest.zip)

**Comment by akien-mga** [comment]
The option to set a default preset applies to *new* imports, not already imported resources. So you need to reimport those (you can multi-select and click "Import"), or delete them `.import` file to let them be reimported with the new default preset.

**Comment by burstina** [comment]
I did it.
Same result.
To be sure, I deleted ".import" folder and all ".import" files in the directory, but no luck.

**Comment by burstina** [comment]
I also created a "file5.csv" to check if new files are imported as expected, but editor tries for translation file and report error.

**Comment by akien-mga** [comment]
Ah yes, "Save as Default for "Import Type"" doesn't change the default for the file, but the default settings when using this import type. For example if you use "CSV Translation" and change the delimter option to "Semicolon", you can set this as default for all future imports of "CSV Translation".

As it is now I don't think there's a way to define what kind of import type should be used as default for a given file extension.

**Comment by burstina** [comment]
Ah, now I understand.

> As it is now I don't think there's a way to define what kind of import type should be used as default for a given file extension.
Ouch, sad story.

I guess any other file has no issue like that due to direct extension's nature (jpg=image, ogg=sound,TXT=text, ecc); CSV is different, it can store virtually anything.
For example, in project A I use CSV files to store data for each game level, in project B I used CSV to store item list and data.
Moreover the ability to use Excel to edit CSV files make it a really easy file.

**Comment by akien-mga** [comment]
I'll close this as "fixed" since the plain "CSV" importer is removed with #47301, and the proper way to achieve what was likely intended is now to use the "Keep" import option (see #47268), to prevent `.csv` files from being imported.

This doesn't address the more general issue about not being able to define what should be the default, but that should likely be re-opened as a formal proposal in https://github.com/godotengine/godot-proposals to match the current UX. Notably, there is now a Project Settings tab to set Importer Defaults: #46354. This could be expended to allow setting which importer to use by default for a given extension (including the new "Keep").

**Comment by akien-mga** [comment]
> This doesn't address the more general issue about not being able to define what should be the default, but that should likely be re-opened as a formal proposal in https://github.com/godotengine/godot-proposals to match the current UX. Notably, there is now a Project Settings tab to set Importer Defaults: #46354. This could be expended to allow setting which importer to use by default for a given extension (including the new "Keep").

I opened a proposal for this: https://github.com/godotengine/godot-proposals/issues/2500
