### ISSUE TITLE
GDScript: Cast Float to Int gives wrong result with complex calculations.

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#33973]
**Godot version:**
3.2-beta2
**OS/device including version:**
Linux Mint 19.2 64-Bit and GitLab CI runner using "image: openjdk:8-jdk"
**Issue description:**
Casting a Float of certian complex calculations with a value 2.000000  to int(2.000000) ==  1 but it should be int(2.000000) == 2.
This requires a complex calculation to cause the error, so I think it is either an overflow issue or a precision issue.
**Steps to reproduce:**
```gdscript
var x_int = int((float(32)/float(30) - float(1)) * float(30))
var x_float = float((float(32)/float(30) - float(1)) * float(30))
print(x_float, " == ", x_int)
```
I will have to make a minimal reproduction project later on, sorry.

**A Request**
@vnen would you be willing to allow me to add GUT to your CI tests on GitHub, so that contributors can add tests to help make sure GDScript is passing tests like this, to make sure the bugs do not come back? I would be willing to implement it, i just need some help understanding how GitHub does CI as I use GitLab. My GitLab runner caught this error for me.

**Comment by lawnjelly** [comment]
This seems to be correct. I tried it in c++. If the calculations are done as 32 bit float
```
	float f = 32.0f / 30.0f;
	f -= 1.0f;
	f *= 30.0f;
```
The result is: 2.00000167

If the calculations are done as 64 bit double:
```
	double f = 32.0 / 30.0;
	f -= 1.0;
	f *= 30.0;
```
The result is : 1.9999999999999996

**Comment by bruvzg** [comment]
It's OK, floats are not what they seem - https://0.30000000000000004.com/

Probably we should add some sort of "Floating-point and numerical precision primer" to the documentation.

**Comment by FeralBytes** [comment]
@lawnjelly thanks, I now am trying to figure out how to smartly round, because simply rounding has caused other subtle errors. For reference implementing [hexagon grid system.](https://www.redblobgames.com/grids/hexagons/)

@bruvzg I agree more documentation could definitely help. I suspected a floating point precision issue, just not sure how to deal with it.

@vnen I would still like to implement some GUT testing but before pushing a PR I would like to first get your approval.

**Comment by vnen** [comment]
@FeralBytes I do want to make automated tests for GDScript eventually. But using GDScript code to test itself might be a bit problematic because the bug we want to catch might seep into the test.

**Comment by aaronfranke** [comment]
@FeralBytes Starting with 3.2, if you wish to compare numbers, use the new `is_equal_approx` method.

    print(is_equal_approx(1.9999999, 2)) # true

**Comment by FeralBytes** [comment]
@vnen good point.
@aaronfranke thanks!
