### ISSUE TITLE
RigiBody not colliding with negative gravity scale

### ISSUE THREAD

**Issue by LaurentTreguier** [godotengine/godot#33989]
**Godot version:**
3.2 beta 2

**OS/device including version:**
Ubuntu 18.04 (KDE Neon)

**Issue description:**
After setting a `RigidBody`'s gravity scale to a negative value, it will not collide will other bodies when moving upwards.
However, I noticed that placing another physics body _below_ it will stop it, as if the `RigidBody` was still, internally, falling down instead of going up.

**Steps to reproduce:**
- Create a new scene
- Add a `RigidBody`
- Set its gravity scale to `-1`
- Add a `StaticBody` above it
- Test the scene; the `RigidBody` will go right through the `StaticBody` instead of being stopped by it

**Minimal reproduction project:**
[gravity.zip](https://github.com/godotengine/godot/files/3904413/gravity.zip)

**Comment by capnm** [comment]
> Set its gravity scale to -1

I think you get what you asked, a kind of wormhole physics :-P

**Comment by LaurentTreguier** [comment]
Silly me, I didn't see that only my MeshInstance was above my ball. The StaticBody was actually below it... Nevermind this issue, I had this problem in another project but the issue must come from somewhere else
