### ISSUE TITLE
8BitDo SN30 is not supported

### ISSUE THREAD

**Issue by Bombfuse** [godotengine/godot#33981]
**Godot version:**
3.1.1

**OS/device including version:**
MacOSX
**Issue description:**
8BitDo SN30 is not a supported controller according to https://github.com/godotengine/godot/blob/master/main/gamecontrollerdb.txt.

I tested the controller and can confirm it does not work.
**Steps to reproduce:**
Attempt to use an 8BitDo controller with a project.

**Comment by aaronfranke** [comment]
@Bombfuse Please submit a pull request to https://github.com/gabomdq/SDL_GameControllerDB. You can configure your controller from within Steam Big Picture, then export the config. The README file in the repo explains how.

**Comment by akien-mga** [comment]
It seems like bindings for 8BitDo SN30 were added recently: https://github.com/gabomdq/SDL_GameControllerDB/commit/5973f6c0d93f19355375bed7cc5253b1fcbfa187
