### ISSUE TITLE
AudioServer.sample_set_signed_data may overflow.

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#3399]
AudioServer.sample_set_signed_data assumes the destination sample is SAMPLE_PCM16. If it tries to write that 16-bit sample to a 8-bit one, it could overflow (or, at least, give an illogical error). While I can make it convert to PCM8 as needed, I don't think I can pull the IMA_ADPCM (need info about the IMA preamble).
Should I put a console warning for IMA_ADPCM, and call it a day?

**Comment by neikeq** [comment]
This issue was not closed automatically after merging the above PR, because _Solves_ is not a [keyword for closing issues](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues).
