### ISSUE TITLE
Transforms look_at has a hard coded axis

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#33999]
**Godot version:**

a88afd22c

**Issue description:**

I faced a problem yesterday where I needed to use looking_at but with a different axis. To fix that and make it more inline with the other operations, I propose adding the axis as an argument.

Just for reference, here is what it does:

> Returns a copy of the transform rotated such that its -Z axis (this is the hardcoded axis) points towards the target position.

**Comment by hammeron-art** [comment]
What do you mean by different axis? You can set the up axis as an argument. The Z-axis is the forward vector that points from transform.origin to target. The other axis must be orthogonal to these two and you can't change it.

**Comment by Jummit** [comment]
Oh, I probably didn't quite understand it then. My problem is that I want my character's feet to face towards a planet, but since looking_at uses the local -Z axis, it ended up facing to the ground. How would I use looking_at correctly in this case?

**Comment by hammeron-art** [comment]
If the planet center is exactly bellow the foot, the up vector is the direction from the planet to the feet `(foot.global_transform.origin - planet.global_transform.origin)`. The foot is already pointing in the right direction and you can get it with `feet.global_transform.basis.z`. Basis.z is the forward direction of the transform.

Something like this:
```
foot.look_at(foot.global_transform.origin + foot.global_transform.basis.z, foot.global_transform.origin - planet.global_transform.origin)
```
