### ISSUE TITLE
godot crashes when a instanced scene changes its root-node then changes its back to normal

### ISSUE THREAD

**Issue by dryluggage** [godotengine/godot#33996]
**Godot version:**3.1.1

**OS/device including version:**Linux mint 19.2

**Issue description:**

**Steps to reproduce:**

to replicate this bug you start with making an empty scene adding a node into it and making another scene and adding a node into it as well then you instance one of them in the other scene,
and now go to the scene that was insanced and add a node, then make the newly made node the scene-root-node though the contextmenu when right-clicking then make the node that was originaly the root-node the root node again save and go to the scene this scene was instanced it and it loads and crashes

**Minimal reproduction project:**

**Comment by pouleyKetchoupp** [comment]
Confirmed in 3.1.1
Can't repro in 3.2 Beta 2

**Comment by akien-mga** [comment]
Closing as fixed in 3.2 then.
