### ISSUE TITLE
Polygon2D and CollisionPolygon2D have the same icons

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33993]
**Godot version:**
3.2 beta2

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/69869218-80a20c80-12ac-11ea-82e3-a1d924cbc210.png)
They should be different.

**Comment by name-here** [comment]
Maybe CollisionPolygon and CollisionPolygon2D should have dotted or dashed outlines? (CollisionShape could too)
