### ISSUE TITLE
ResourceLoader doesn't recognize IMA_ADPCM sounds.

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#3401]
It tries to load them as PCM8,but fails silently, leaving an empty sample.

Is it worth it to keep this apparent support for ADPCM, or should we drop it?

```
extends Button

var sound=ResourceLoader.load("res://Coin_ima.wav")
var voice=AudioServer.voice_create()

func _ready():
	AudioServer.voice_set_mix_rate(voice,44100)
	AudioServer.voice_set_volume(voice,1.0)
	connect("released",self,"_on_released")

func _on_released():
	AudioServer.voice_play(voice,sound.get_rid())
	print(sound.get_format())
```
In fact, when loading an IMA sample, get_format returns PCM8.

**Comment by reduz** [comment]
loading those from wavs is not supported, the ima adpcm format in wav files is chunked, what makes it kind of useless without reconversion and will result in degradation of quality.

Juse use import -> sample
or go to export settings and choose to export to ima adpcm

**Comment by Ovnuniarchos** [comment]
Unfortunately, import->sample creates a 0-length 8-bit sample when loading IMAs.

**Comment by reduz** [comment]
just don't load .wavs with ima-adpcm, don't convert them to that format

**Comment by Ovnuniarchos** [comment]
Then, the apparent support for IMAs is just that, apparent, and should be removed. Don't you think?
