### ISSUE TITLE
CallDeferred not work with C#

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#34015]
**Godot version:**
Godot 3.2 beta 1 mono

**OS/device including version:**
Win10 64 home

**Issue description:**
It is not possible to add a node to the tree from _Ready.

The node does not appear on the screen, is not visible and does not appear on the "Remote" tab.
The node does not enter the tree.

**Steps to reproduce:**
Try adding a node to the tree from _Ready using the image code.

![1](https://user-images.githubusercontent.com/19652075/69901077-d47c2680-137c-11ea-8383-a924774ce98b.png)

**Minimal reproduction project:**
[testDeferred.zip](https://github.com/godotengine/godot/files/3907131/testDeferred.zip)

**Comment by Sslaxx** [comment]
What does it say/do (or not say/do)? Does anything show up in the terminal?

**Comment by Torguen** [comment]
In the terminal no information is provided that something wrong is happening.

**Comment by Torguen** [comment]
Ok, the error is to use "AddChild" instead of "add_child", however, in other cases it will be done:

explosion.Set ("GlobalPosition", GlobalPosition);
OR
explosion.Set ("global_position", GlobalPosition);

Both work, this is a mess.
