### ISSUE TITLE
Updating scene crash after renaming

### ISSUE THREAD

**Issue by sudoman281** [godotengine/godot#34017]
**Godot version:**
3.1.1
**OS/device including version:**
Anarchy Linux, Gnome. Kernel version: 5.3.11.1-1, Gnome version: 1:3.34.1-1
**Issue description:**
Sometimes when I rename something in the assets folder the editor shows a window saying "Updating the scene" and it crashes almost immediately. 
**Steps to reproduce:**
As mentioned before, it only happens sometimes, but not rarely. Try creating some tscn files, materials, and folders in the assets folder, using them in your scene and then renaming them from the editor.

**Comment by KoBeWi** [comment]
This should've been already fixed in 3.1.2 by #29459
Upgrade your Godot version and you can reopen this if the issue persists.
