### ISSUE TITLE
OmniLight Pixelated Shadows artifact

### ISSUE THREAD

**Issue by owstetra** [godotengine/godot#34010]
**Godot version:**
Godot 3.2 Beta

**OS/device including version:**
Windows 7 x64bit

**Issue description:**
OmniLight have a Weird Pixelated Shadows Like this :
even if increasing Shadow Atlas size

![editor_screenshot_2019-11-30T015304+0100](https://user-images.githubusercontent.com/51128638/69893660-28ebbb80-1315-11ea-9528-d9603dbb4024.png)

and the issue is huge if those cubes are moving

**Minimal reproduction project:**
[TestLightShadow.zip](https://github.com/godotengine/godot/files/3906622/TestLightShadow.zip)

**Comment by clayjohn** [comment]
You can alleviate these artifacts by, 1) increasing your shadow atlas size, 2) disabling all but the first shadow atlas quadrant, and 3) setting filter mode to PCF13. 

These artifacts are a limitation of how shadows work. We plan to improve shadow mapping for 4.0.

**Comment by owstetra** [comment]
> You can alleviate these artifacts by, 1) increasing your shadow atlas size, 2) disabling all but the first shadow atlas quadrant, and 3) setting filter mode to PCF13.
> 
> These artifacts are a limitation of how shadows work. We plan to improve shadow mapping for 4.0.

i did all these steps , but still the shadows look very pixaleted

**Comment by clayjohn** [comment]
They don't solve the issue completely, but they help. A better Shadow mapping algorithm will be used for version 4.0.
