### ISSUE TITLE
2D corner collision issue

### ISSUE THREAD

**Issue by subtyven** [godotengine/godot#34025]
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
If you create a wall composed of multiples shapes, with tilemap for example, and then you hit the intersection between 2 shapes with a ball, the physics engine will considere that the ball should bump in a corner, even if the corner is filled by the adjacent shape.

This basically makes some 2D ball based games impossible to create.

**Steps to reproduce:**
Just run the project below with collision shapes visible

**Minimal reproduction project:**
https://github.com/sollidsnake/godot-corner-collision-issue

**Comment by KoBeWi** [comment]
Related to #32182

**Comment by subtyven** [comment]
Related to #32182 (probably)
