### ISSUE TITLE
Freelook mode vertical movement is done along camera Y axis

### ISSUE THREAD

**Issue by escargot-sans-gluten** [godotengine/godot#34034]
**Godot version:** 3.2 beta 2

**OS/device including version:** PopOs 19.04

**Issue description:**
In freelook mode, up/down movement is done along the camera's local y axis rather than the global one, which makes it pretty unusable if the view is tilted.

**Steps to reproduce:**
1. open the 3d editor
2. freelook mode (Shift + F)
3. tilt the view vertically
4. move up/down (Q/E by default)
5. notice it doesn't move up or down

**Minimal reproduction project:**

**Comment by Calinou** [comment]
> In freelook mode, up/down movement is done along the camera's local y axis rather than the global one, which makes it pretty unusable if the view is tilted.

On the other hand, if you make up/down movement use the global Y axis, you can't move forward while looking down anymore (among other things). This may be viewed as a downside by some.

**Comment by escargot-sans-gluten** [comment]
This would indeed imply loosing a feature so a good option imo would be to let the user choose, as there seem to be use-cases for both options.

**Comment by Cyber4** [comment]
seconded, an option for switching between axis-locked (minecraft-style) freelook and the current freelook would make workflow much easier as even once getting used to it freelook just feels clunky and disorienting.

**Comment by Calinou** [comment]
To provide all common navigation patterns, we may need to have a "Freelook Movement Scheme" setting with 3 values:

- Default (like it currently is).
- Partially axis-locked
  -  Vertical movement won't take camera pitch into account. This is similar to id Tech games' `noclip` mode, among many others.
- Fully axis-locked
  - Same as "Partially axis-locked", but forward/backward movement also won't take camera pitch into account. This is similar to Minecraft.
