### ISSUE TITLE
MonoDevelop doesn't open the solution when sln path contains spaces

### ISSUE THREAD

**Issue by SeleDreams** [godotengine/godot#34035]
**Godot version:**
3.1.2 stable mono version

**OS/device including version:**
KDE neon 5.17 amd64

**Issue description:**
MonoDevelop when launched from Godot doesn't open the game solution and just displays the startup page when the file path of the sln contains spaces.
Since in the first place, MonoDevelop doesn't allow to create solutions with spaces in them
![image](https://user-images.githubusercontent.com/16335601/69906973-52b3e980-13cc-11ea-91b7-582f574bebc7.png)
 it would feel natural that if MonoDevelop is officially supported as an external editor, Godot should comply with its official limitations
An other approach could be to add a warning when creating a project with spaces that some editors could have difficulties working properly with it.

**Steps to reproduce:**
Create a Godot Project with spaces in the path
Set MonoDevelop as the Mono editor

**Minimal reproduction project:**
here is a small test project containing spaces
trying to open Node.cs will try to open monodevelop but monodevelop will just display its home page
[test project.tar.gz](https://github.com/godotengine/godot/files/3907662/test.project.tar.gz)

**Comment by neikeq** [comment]
MonoDevelop is able to open solutions with spaces from the GUI and when I drag and drop the solution file from the file system, so this seems to be a bug with its cli.

Regarding whether Godot should allow solutions with spaces (ideally by replacing them with either dots or underscores) I'm not really against such a rule but if this could be fixed in MonoDevelop instead that would be better.

**Comment by pikachuk** [comment]
SInce this issue is present in MonoDevelop since a long time, I am not sure the devs are willing to fix it.
They maybe want to enforce their choice of not having spaces in solutions.
I will post an issue about it on their repo as well, but I don't really know how it will go.

**Comment by pikachuk** [comment]
https://github.com/mono/monodevelop/issues/9406 I've opened an issue on their repo

**Comment by KoBeWi** [comment]
This doesn't look like Godot bug and it even has an issue on another repo, so closing.
