### ISSUE TITLE
Problem placing node in tree with drag and drop

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#34033]
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
win10 64 home

**Issue description:**
The problem is that a node that is the son of another node cannot be located off of it.
To place it below you have to take the node out of the father.

In this GIF you can see that to locate the node "key_door2" under (not inside) of "key_door" I have to:
1st place "key_door2" above "key_door"
2nd now you can put "key_door2" under "key_door"

In conclusion, a child node cannot relocate to a lower position (not inside it) than the parent node.

![GIF](https://user-images.githubusercontent.com/19652075/69906163-686ee200-13bf-11ea-8582-30b17293b50b.gif)

**Steps to reproduce:**
Make a node a relative of another and then try to locate the innermost node just below its parent node, for this you will have to break the parent / child relationship.

**Minimal reproduction project:**
I do not think it's necessary.

**Comment by KoBeWi** [comment]
If you drop it on parent of `key_door`, it will be appended as last child.

**Comment by Torguen** [comment]
I'm not sure what I meant was understood.

Can you do this in only two steps?
If so, then could you record a GIF so you can see how it does it?
![1](https://user-images.githubusercontent.com/19652075/69906335-504c9200-13c2-11ea-9c78-34d1f2d7e5e4.png)
![2](https://user-images.githubusercontent.com/19652075/69906336-504c9200-13c2-11ea-8769-6ebaed7f1816.png)

**Comment by KoBeWi** [comment]
![Y6g2VYgyNK](https://user-images.githubusercontent.com/2223172/69906391-dd8fe680-13c2-11ea-98c8-0250625e8acc.gif)

**Comment by Torguen** [comment]
Yes, thanks, it is a way to get it but it is a hindrance if you have a list of 40 nodes.
The method that I use in the GIF should work, so I consider this a bug.

**Comment by giarve** [comment]
Working on it. I will try to make the pull request soon.

**Comment by marcospb19** [comment]
This is not an issue, this is how it is supposed to behave.

![image](https://user-images.githubusercontent.com/38900226/82524401-36844000-9b05-11ea-8435-f158266b8ec1.png)

Look at this example, if I wanna take `Orphan` and make it a child of `Father Of Many`, I just need to drag it to the level he should be, there are 3 ways of dragging it.

![image](https://user-images.githubusercontent.com/38900226/82524820-42243680-9b06-11ea-9b32-318f41a976d5.png)

![image](https://user-images.githubusercontent.com/38900226/82524598-c32efe00-9b05-11ea-81f6-dfd1e9c73fb2.png)

![image](https://user-images.githubusercontent.com/38900226/82524862-56683380-9b06-11ea-971f-04d708979abf.png)

All three ways are valid, the "issue" you explained is the third case, you're trying to insert it in this first slot.

However, the pull request by @giarve is brilliant, helps with usability.

**Comment by Torguen** [comment]
This is fixed in: v3.5.beta1.official [b9b23d222]

Now that space does not appear as available and does not give rise to confusion.
