### ISSUE TITLE
Lerp function not work on ARM arch(Linux x11)

### ISSUE THREAD

**Issue by shar0** [godotengine/godot#34031]
**Godot version:** 3.1.2

**OS/device including version:** Debian(Clockwork OS) based on ARM (Cortex-A7), Linux X11

**Issue description:** lerp() function not work.

**Steps to reproduce:** linear_vel.x = lerp(linear_vel.x, target_speed, 0.1)

**Minimal reproduction project:** Platformer 2D (Godot Official Project)

**Comment by akien-mga** [comment]
What does it mean that it doesn't work?

**Comment by lawnjelly** [comment]
Yes .. more info. If you place a breakpoint on this line when it is 'not working', what are the input values, and what is the result?

**Comment by shar0** [comment]
In GodotScript lerp() return 0 and whatever params input.

**Comment by FeralBytes** [comment]
@shar0 please provide your test input values and the matched output values, thank you.

**Comment by KoBeWi** [comment]
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.
