### ISSUE TITLE
Bookmark list shows unknown symbol for tabs

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34046]
**Godot version:**
3.2 beta2

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/69917691-14b8d300-1469-11ea-8b95-32b1deb5c492.png)
![image](https://user-images.githubusercontent.com/2223172/69917693-1edad180-1469-11ea-8113-2b66f92cfb36.png)
Might happen when toggling comment, because it puts # at the beginning of the line.

**Comment by Calinou** [comment]
This could be solved by replacing `\t` with four spaces in the bookmarks list (or nothing, maybe).

**Comment by andrycodestuffs** [comment]
I'm new in the Godot developers community and I'd like to help solve this issue.
I'd like to reproduce the bug before proposing a possible solution, any information would be very appreciated

**Comment by KoBeWi** [comment]
> I'd like to reproduce the bug before proposing a possible solution, any information would be very appreciated

You can find bookmark list in Script Editor's "Go To" menu. Add a bookmark using Ctrl + B and if the line has a tab after a non-whitespace character, it will display wrongly on the list.

**Comment by andrycodestuffs** [comment]
I decided to follow @Calinou advice and replace tabs with "nothing" (I used a single space)

Before:
<img width="675" alt="Screenshot 2019-12-02 at 22 08 38" src="https://user-images.githubusercontent.com/22056177/69995495-7142ed80-1550-11ea-8512-45e664bb9bb3.png">

After fixing the issue:
<img width="675" alt="Screenshot 2019-12-02 at 22 05 25" src="https://user-images.githubusercontent.com/22056177/69995576-a3544f80-1550-11ea-8d9d-c3f83d708dbf.png">
