### ISSUE TITLE
Autocomplete fails in for loop if method is defined after current line

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34045]
**Godot version:**
3.2 beta2

**Issue description:**
```
func autotest():
	pass

func autocomplete_me() -> Array:
	return []
```
![image](https://user-images.githubusercontent.com/2223172/69917606-f6060c80-1467-11ea-8007-6456aabb77a3.png)

![image](https://user-images.githubusercontent.com/2223172/69917614-1afa7f80-1468-11ea-9c21-1185efeef0ee.png)

Works if `autocomplete_me()` is above `autotest()`.

EDIT:
`if` has the same problem.

**Comment by bojidar-bg** [comment]
Duplicate of #23264?

**Comment by KoBeWi** [comment]
Ah, seems like it.
