### ISSUE TITLE
Scale curve does not work: CPUParticles2D

### ISSUE THREAD

**Issue by IL7Games** [godotengine/godot#34051]
**Godot version:** 3.1.1
**OS/device including version:**  Solus 4 OS

Hello devs, 👋

I am using **Godot version 3.1.1** stable with **GLES2** and my problem is as follows.
Whenever I try to create a scale curve for my particle, it doesn't work. It is useless to put any minimum or maximum value, the particles do not appear!

Already have a fix for this issue?

**Comment by Zylann** [comment]
Do you mean `Particles2D`? (`GPUParticles2D` doesn't exist, closest is `CPUParticles2D`).

**Comment by Zylann** [comment]
In fact GPU particles are just not supported in GLES2. It's not mentionned in the doc, but a configuration warning is visible in the scene tree, and this is shown if you click on it:
![image](https://user-images.githubusercontent.com/1311555/69920101-ce20a400-147b-11ea-8fde-71beb61506ef.png)
Is it visible to you?

**Comment by IL7Games** [comment]
Sorry, I ended up writing it wrong. I am CPUParticles2D here in my project, in the scale/scale_amount_curve property, when I try to create a curve for my particle it stops working.
![CPUParticles2D-ScaleTesting](https://user-images.githubusercontent.com/46099583/69920142-023b9b00-1463-11ea-8d7b-dcd47886af18.gif)

**Comment by Zylann** [comment]
That happens because when you create a Curve, it starts with no points inside. So it probably evaluates to zero at all times.
Add points to the curve by right-clicking on the graph (choose preset or add point).
![image](https://user-images.githubusercontent.com/1311555/69920217-fc52b380-147c-11ea-9eae-3142c715a04c.png)

**Comment by IL7Games** [comment]
> In fact GPU particles are just not supported in GLES2. It's not mentionned in the doc, but a configuration warning is visible in the scene tree, and this is shown if you click on it:
> ![image](https://user-images.githubusercontent.com/1311555/69920101-ce20a400-147b-11ea-8fde-71beb61506ef.png)
> Is it visible to you?

This warning didn't come to me Zylann, and I would like to know why there are Particles2D and CPUParticles2D nodes, could you please explain to me please?

**Comment by Zylann** [comment]
`CPUParticles2D` are simulated on your CPU. `Particles2D` are simulated on your GPU (graphics card). The latter can handle much higher amounts of particles but depends on more recent graphics cards.

See my answer for your problem https://github.com/godotengine/godot/issues/34051#issuecomment-560158010

**Comment by IL7Games** [comment]
Thanks so much Zylan, you took away this frustration that I was feeling about my project!

> Add points to the curve by right-clicking on the graph (choose preset or add point).

I didn't know that doing this to make the scale property work, thanks. 😊
