### ISSUE TITLE
GPU particles don't work in GLES2

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34052]
Godot 3.2 beta2
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

Steps:
1) Create a `Particles` node
2) Assign a new default `ParticlesMaterial`
3) Add a draw pass with cubes: nothing shows up so far.

The same steps in Godot 3.1.1 successfully show falling cubes.

The same issue happens with `Particles2D`.

**Comment by clayjohn** [comment]
Why are you closing?

**Comment by Zylann** [comment]
Because I didn't realize I was actually trying this using the GLES2 renderer. I got the OpenGL version wrong in the report.

**Comment by Calinou** [comment]
I wonder if we should print an error message when instancing a Particles or Particles2D node when using the GLES2 renderer. This would complement the existing node configuration warning, which may be missed when instancing nodes at run-time.
