### ISSUE TITLE
Crashing Editor caused by a particular C# Scripted Node being loaded into the inspector

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot#34057]
**Godot version:**
Mono 3.2 Beta 2

**OS/device including version:**
Manjaro Arch Linux "Juhraya" 18.1.2

**Issue description:**
My editor crashes every time I click on my Ship objects in my scene tree with the Script on it. It won't crash if I make the script invalid and remove it but once I attach it back to the Ship object, inspecting the Ship object will crash my editor.

[Mono Error Log](https://github.com/godotengine/godot/files/3909217/mono.error.log.txt)
[Console Report](https://gist.github.com/Spartan322/fff165f4a213eb4a21e97c144faa934d) (it stops at the bottom appearing as if its frozen, I need to manually terminate the application)

**Steps to reproduce:**
Open my project
Open any Ship scene in the node inspector

**Minimal reproduction project:**
[The Project on Mediafire](https://www.mediafire.com/file/k8yw3df6gxok1ff/Maimed_Stars_%28Spartan322%29.zip/file)

Apologies I can not upload a smaller project because I can't seem to reliably test the problem in a small project.

Edit: I'm aware there are multiple runtime errors, however they shouldn't be able to cause the editor to crash, and I have since managed to stop the editor crashing but I have no idea how, the best I got is I commented out most of the functionality in the Ship class and then uncommented it. And I don't believe it had anything to do with building the csproj because I've done that twice, once cleaning in MonoDevelop and once deleting the .Mono directory.

This might be a misdiagnosed issue already from my end in that case, however I am unsure of the root of the issue.

**Comment by Lindenk** [comment]
I seem to be having a very similar issue as well.

**Godot version:**
3.1.2.stable.mono.official

**OS/device including version:**
Arch Linux  5.4.2-arch1-1

The crash report is [here](https://gist.github.com/Lindenk/f82e26d26824493be55b79b82c33670c) and my project is [here](https://github.com/Tankooni/OwlMan)

**Comment by aaronfranke** [comment]
@Spartan322 Your reproduction project is no longer available to download.

@Lindenk I can't reproduce any crashes in your project in Godot 3.2.3.

Please re-test with Godot 3.2.3 and/or the master branch. Also, check if you have the latest Mono and .NET Core.

**Comment by raulsntos** [comment]
Closing due to lack of response. If anyone can still reproduce this issue in [Godot 3.6 beta 2](https://godotengine.org/article/dev-snapshot-godot-3-6-beta-2/) or [Godot 4.1 RC 3](https://godotengine.org/article/release-candidate-godot-4-1-rc-3/) or any later release, please open a new issue.
