### ISSUE TITLE
RichTextLabel doesn't translate

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34050]
Godot 3.2 beta2
Windows 10 64 bits

I used a `RichTextLabel` in my app's credits window, and added a translation of its contents to my translation resources. However, it doesn't get localized. I tried a much simpler text, but it still doesn't work. BBCode or not doesn't change it.

[RichTextLabelLocalization.zip](https://github.com/godotengine/godot/files/3908641/RichTextLabelLocalization.zip)
Run main scene: see only regular Label gets translated into french.

**Comment by devvoid** [comment]
I'm having the same issue here on 3.1.1 stable, on Linux Mint 19.

**Comment by HaSa1002** [comment]
That's because there is no translation done for rich text labels. I don't see a nice way to implement this, based on the current implementation of the rich text label.

**Comment by devvoid** [comment]
As a workaround, you can set the bbcode text in a script, using the `tr` function to get the translation.

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by HaSa1002** [comment]
@KoBeWi Yes because the RTL doesn't has a string that it could translate, because it stores everything directly in the tag tree. I would go as far as stating, that this won't be fixed in 3.x. I haven't looked at bruvzgs RTL PR in depth, so I don't know if it fixes some of the bugs
