### ISSUE TITLE
Icon.png suddenly appears modulated blue, when it is not.

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#34068]
**Godot version:** 3.1.2 stable

**OS/device including version:**
Win 

**Issue description:**
I clicked the "+" to create a new scene, selected Node2D as root node, dragged the icon.png into the viewport to create a new sprite with the icon texture.
The result is this:

![blue_sprite](https://user-images.githubusercontent.com/47016402/69996320-17432780-1552-11ea-913f-b4389863f647.png)

- The icon appears unmodulated if I check the color picker in visible.
- The icon is looks unchanged in the OS filebrowser, as well as in the Godot texture preview on the right, in the browser, in my graphics editing software. Neither would I expect it to look different, because I did not alter the icon texture.
- I closed and restarted the editor if I repeat the steps above the result is the same.
- Other graphics in my project do not seem changed in contrast or color.
- It does not matter how many Sprites I add, or if I use the + Add Node or just drag it in the viewport, it's always dark blue.
- It does not seem to matter if I add a new Sprite to a new scene or to a existing scene, it's always dark blue. Existing default Spites with icon.pgn textures do not seem to be affected. They look unchanged, only newly created ones.
- Resetting the default environment in the Project Settings > Rendering and repeating the steps did not change anything. Still dark blue Sprite.
- The last edits I did in the project was to adjust the Worldenvironment node in one of my scenes. It's a 3D scene. Even though I don't think the WE node of another scene should have an effect on this scene, I tested disabling all Adjustments and Ambient colors from the WE node in the other scene. Saved. No effect. Closed and restarted, still the same. Completely removed the WE ... still the same blue Sprite ...

I'm out of ideas.

**Comment by KoBeWi** [comment]
I had it happen once too. It's because the texture is imported with sRGB enabled, while the default option is "Detect" (which probably turns it off). Set this in texture's import settings
![image](https://user-images.githubusercontent.com/2223172/70002856-9c820880-1561-11ea-99d8-3d1d9e0eaeb1.png)

As to why it changed, it's probably related to this #33709
