### ISSUE TITLE
CheckBox Artifact

### ISSUE THREAD

**Issue by erammos** [godotengine/godot#34069]
**Godot version:**
v3.2.custom_build.055d7ace5
**OS/device including version:**
Ubuntu + Android
**Issue description:**
There is an outter bluish rectangle in my toggle button, when i press it
![artifact_toggle](https://user-images.githubusercontent.com/10757118/69997119-1adbac00-155c-11ea-8a9f-45cb63fb11f9.png)
**Steps to reproduce:**
A simple checkbox with custom icons-> checked and unchecked only. toggle mode on

**Comment by erammos** [comment]
if clip content is on, the rectangle goes away

**Comment by Zylann** [comment]
Does it go away if you override the `focus` style with a `StyleBoxEmpty`?

**Comment by erammos** [comment]
It does go away! That looks a bit strange for default focus style btw! thanks!
