### ISSUE TITLE
Adding viewport node causes editor to go blank

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#3406]
I had this happen when I tried it on a fresh windows build, and someone on the Facebook group also said they had this issue on a fresh linux build. I've just tried it on my linux (ubuntu) machine, but it appears to be okay here.. 

That's all the information I have at the moment, I'll see if I can add more later. Just wanted to bring attention to it in case anyone else was having this issue, or if anyone else was able to try it out on their machine.

**Comment by sketchyfun** [comment]
This is how it looks before I add the viewport node
![screenshot1](https://i.imgur.com/9UQrjHa.png)


This is how it looks after I add the viewport node as a child of the "Game" node
![screenshot2](https://i.imgur.com/vlk8wHe.png)

**Comment by MarianoGnu** [comment]
@reduz this may be because of viewport/control merge
