### ISSUE TITLE
The editor always is Unresponsive

### ISSUE THREAD

**Issue by Straw8** [godotengine/godot#34071]
1.When I click the exit button,the editor always is Unresponsive on MacbookPro,so I need to close it forcely;The editor verison is 3.1.1.stable.official.

2.By the way,I choice an action named UI_SELECT for the button,however the event is not active when I pressed the SpaceBar.Why?What should I do?

Thanks!
![image](https://user-images.githubusercontent.com/30140019/70013328-3376b100-15b2-11ea-9a75-f1c51abd8fa2.png)

**Comment by FeralBytes** [comment]
Have you tried the latest Godot 3.1.2, is the bug/issue still present in this latest release of the 3.1 branch?

**Comment by Straw8** [comment]
> Have you tried the latest Godot 3.1.2, is the bug/issue still present in this latest release of the 3.1 branch?
I hava tried the latest Godot,It can exit normally if you have no change for game,unfortunately It will show Accidental Withdrawal message if you click the exit button even if you only save the game without any changes and the mac advice me to reopen concurrently.

**Comment by FeralBytes** [comment]
So it is having a hard time saving on your Mac Book pro. Do any other applications have this problem? Is it possibly a permissions issue since Godot is downloaded and then executed? Sorry I do not use Mac enough to know.

**Comment by Straw8** [comment]
@FeralBytes 
**Error message as follow,I hope it is useful.**

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff7b4892c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7b544bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff7b3f36a6 abort + 127
3   org.godotengine.godot         	0x00000001004a4b00 handle_crash(int) + 1776
4   libsystem_platform.dylib      	0x00007fff7b539b5d _sigtramp + 29
5   ???                           	000000000000000000 0 + 0
6   org.godotengine.godot         	0x0000000102753916 RefPtr::unref() + 54
7   org.godotengine.godot         	0x00000001027bda72 Variant::clear() + 114
8   org.godotengine.godot         	0x00000001026958a6 HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::clear() + 86
9   org.godotengine.godot         	0x00000001026903f0 HashMap<StringName, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::clear() + 80
10  org.godotengine.godot         	0x00000001026901cc ClassDB::cleanup() + 492
11  org.godotengine.godot         	0x000000010275dbbe unregister_core_types() + 1230
12  org.godotengine.godot         	0x00000001004dad62 Main::cleanup() + 914
13  org.godotengine.godot         	0x00000001004b2240 main + 816
14  libdyld.dylib                 	0x00007fff7b34e3d5 start + 1

**Comment by Straw8** [comment]
@FeralBytes 
It seems that the error is disappear in 3.2.beta3,Thanks for every dalao.The dalao is awesome man or woman in Chinese,ha..
The issue should be closed Now?

**Comment by KoBeWi** [comment]
> The issue should be closed Now?

If it's resolved, then yes.
