### ISSUE TITLE
Saving built-in script as file suggest tres extension

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34080]
**Godot version:**
3.2 beta2

**Steps to reproduce:**
1. Add a node
2. Add a built-in script to it
3. Go to the script in the inspector and save it as file
![image](https://user-images.githubusercontent.com/2223172/70052789-5fa32980-15d4-11ea-8e0a-1151ecdad8a6.png)
4. This happens
![image](https://user-images.githubusercontent.com/2223172/70052813-6b8eeb80-15d4-11ea-9dd7-84e4fa878e4d.png)

You can either manually enter correct extension or select "All files" filter and then "gd" again.

EDIT:
After some more testing, this also happens when you save the script from the Script Editor (Ctrl + Alt + S), but only after the scene was saved with the script.

**Comment by lyuma** [comment]
Still a bug on master (4.0 alpha 11)
