### ISSUE TITLE
area_body_entered signal triggers instantly on node load

### ISSUE THREAD

**Issue by droc101** [godotengine/godot#34093]
**Godot version:**
3.1
**OS/device including version:**
macOS 10.13.4
**Issue description:**
Area_body_entered triggers instantly on node load
**Steps to reproduce:**
add an area and another node to a scene and connect the signal. it will trigger once instantly when the area node loads

**Note:**
this also happens with an area2d

**Comment by KoBeWi** [comment]
Any reproduction project? The steps are too vague.

**Comment by KoBeWi** [comment]
No response for a month (lol), closing. If the objects are overlapping and compatible this is probably expected, but hard to say given the insufficient description.
