### ISSUE TITLE
Not able to translate the "Last Modified" string

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34095]
**Godot version:** v3.1.2 stable & v3.2.beta.custom_build.40d1486cb

**OS/device including version:** macOS Catalina 10.15.1

**Issue description:**
The sort option "Last Modified" string in project manager is not generated for translation. The string is missing in the .pot file and Hosted Weblate. Thus, remain untranslated for all languages.

**Steps to reproduce:**
* In the project manager, change language to Simplfied Chinese (or any other language)
* Click the sort option box, only "Last Modified" is untranslated.

---

The strings for the sort options are defined here:

https://github.com/godotengine/godot/blob/40d1486cb317a60dc0e982cbc7ff3e6645cd5280/editor/project_manager.cpp#L2468-L2471

and the `TTR` is applied here:

https://github.com/godotengine/godot/blob/40d1486cb317a60dc0e982cbc7ff3e6645cd5280/editor/project_manager.cpp#L2695-L2700

I think the cause of this issue is that using `TTR` this way will do the l10n work at runtime. But the .pot generator won't detect the actual string (as it's just a variable name here).

The other two sort options here ("Name" and "Path") are not actually detected for translation either. They are in the .pot file because the strings are marked for translation in some other files explicitly with `TTR("Name")` and `TTR("Path")`.

**Comment by akien-mga** [comment]
You're correct, `TTR()` is just used to extract strings via a Python script, there's no evaluation involved, so the current code is wrong. The `TTR()` should be used when `sort_filter_titles` is set up.

Do you want to do a Pull Request with those changes?
