### ISSUE TITLE
Panel with StyleBoxFlat looks different in Godot 3.2

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#34104]
**Godot version:**
3.2 beta 2
**OS/device including version:**
MX Linux 64 bits

**Issue description:**
I'm not sure if this was intended, panels with the same ui style look different between Godot 3.1 and Godot 3.2

This is how a panel looks in 3.2
![image](https://user-images.githubusercontent.com/18746022/70177371-02cd6f00-16b9-11ea-9e18-880748db9cce.png)
And this is how it looked in 3.1
![image](https://user-images.githubusercontent.com/18746022/70177413-17116c00-16b9-11ea-8366-ecbccb95acf5.png)

**Steps to reproduce:**
Create ui theme and give panels a StyleBoxFlat style, change the values and compare the results between Godot 3.1 and Godot 3.2

**Comment by pouleyKetchoupp** [comment]
Confirmed on 3.2 master. Border is too large when AA is on, probably caused by PR #26609. I'll have a look.
