### ISSUE TITLE
Crash when clearing guides in empty scene

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34111]
**Godot version:** v3.2.beta.custom_build.129a22cd9

**OS/device including version:** macOS Catalina 10.15.1

**Issue description:**
The editor crashes when I click the "Clear Guides" menu item in an empty scene.

**Steps to reproduce:**
1. Open an empty scene (without the root node)
2. Swith to the 2D workspace
3. In the editor toolbar, open the "View" menu, and click "Clear Guides".
4. The editor crashes. 

**Minimal reproduction project:** Any project.

---

The cause is that `EditorNode::get_singleton()->get_edited_scene()`  returns `NULL` for an empty scene, making the `has_meta` function crash.

(The function actually returns the root node of the edited scene instead of the scene itself.)

https://github.com/godotengine/godot/blob/129a22cd905d1163641a56a956a69747e4e3c17a/editor/plugins/canvas_item_editor_plugin.cpp#L4753-L4757

I'd like to make a pull request to fix this. But I have some questions: This `case` block has a lot of repeated `EditorNode::get_singleton()->get_edited_scene()` expression. Is there a technical requirement that they are not extracted into a local variable? If extracting into a local varaible is allowed, could I put that modification in the crash-fixing PR, or do that in a separate PR?

**Comment by akien-mga** [comment]
> I'd like to make a pull request to fix this. But I have some questions: This `case` block has a lot of repeated `EditorNode::get_singleton()->get_edited_scene()` expression. Is there a technical requirement that they are not extracted into a local variable? If extracting into a local varaible is allowed, could I put that modification in the crash-fixing PR, or do that in a separate PR?

There's no technical requirement not to do it. We usually don't use a local variable for this when it's 2 or 3 occurrences, but in this case it does make sense to factorize a bit and thus do the null check before check `has_meta`.
