### ISSUE TITLE
FBX Meshes get culled/clipped unless viewport cam is very close

### ISSUE THREAD

**Issue by Acissathar** [godotengine/godot#34110]
**Godot version:** 3.2 beta 3

**OS/device including version:** Windows (10.0.18362)

**Issue description:** 

Easier to see in the video, but basically an imported FBX has a weird culling/clipping issue unless the viewport camera is almost right next to the mesh in question. Same FBX imported into Unity has no issues. Exporting the FBX as a DAE does not have the culling issue.

**Steps to reproduce:** 

1. Import FBX
2. Open Inherited FBX scene and notice.

Video of issue: https://streamable.com/w6ewq

**Comment by lawnjelly** [comment]
That looks like a z buffer issue. I'd be suspecting the scale of the model, or more likely the material applied. Is it even using the z buffer?

**Comment by Acissathar** [comment]
I will check out the zbuffer when home tonight to verify, but scale didn’t seem to matter, and neither did viewport clip planes.

The DAE for reference imported at a scale of ~100 times larger but didn’t experience this using the same materials as well.

**Comment by Acissathar** [comment]
I tried various settings on the materials and even created brand new materials, but I still see the same result.

I've attached all properties for the materials along with the DAE version and FBX version. Both have the same materials on the same meshes, but I get vastly different rendering results.
![DaeVersion](https://user-images.githubusercontent.com/10227954/70269872-7bd3d180-1760-11ea-8f64-9f3305a2cf38.PNG)
![FbxVersion](https://user-images.githubusercontent.com/10227954/70269874-7bd3d180-1760-11ea-9e8f-916a9cd27ec9.PNG)
![Properites1](https://user-images.githubusercontent.com/10227954/70269875-7c6c6800-1760-11ea-89bd-b816df48f7b7.PNG)
![Properties2](https://user-images.githubusercontent.com/10227954/70269876-7c6c6800-1760-11ea-89ce-7e80d9b5a785.PNG)
![Properties3](https://user-images.githubusercontent.com/10227954/70269877-7c6c6800-1760-11ea-8d63-b96b7d79eff7.PNG)
