### ISSUE TITLE
Text unable to center properly

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot#34112]
**Godot version:**
3.2.beta2

**OS/device including version:**
MacOS Catalina

**Issue description:**
If I set a Label to Center the text it is still slightly off. If I have several Lines, every Line is not centered and also slightly off. I tried several Fonts and still the same issue.

In the picture you can see how it is in the Editor, looks quite centered and at the bottom image how it looks in-game.

![notcentered](https://user-images.githubusercontent.com/4989757/70215662-45855a80-173e-11ea-926f-217e598c00ca.png)

**Comment by volzhs** [comment]
what about disabling `Use Oversampling` at Project settings > General > Rendering > Quality > Dynamic Fonts?

**Comment by letsgamedev** [comment]
Indeed, that works! I just have to trick around the game dimensions. Go from 90x160 to 360x640 and then scale everything up. Its a Workaround but it's okay.

But it would be nice if this will be fixed in the future somehow^^

**Comment by volzhs** [comment]
There isn't attached demo project so I'm not 100% sure but it seems fixed by #34838

![image](https://user-images.githubusercontent.com/8281454/71821231-ef0c9280-30d4-11ea-8ff1-2437a6f6caac.png)

**Comment by akien-mga** [comment]
It seems likely indeed, I'll close as fixed by #34838.
Please comment if you can still reproduce the issue in the next 3.2 build.
