### ISSUE TITLE
Godot main application gui interface

### ISSUE THREAD

**Issue by arahulc91** [godotengine/godot#34115]
Hi, sorry to bother...but i am a noob in programming and I have started learning about C and C++. I am just wondering what library(s) is godot using to layout items on screen i.e. the interface, the window system. My guess would be something that is cross platform as it looks similar on major operating systems.

**Comment by Zireael07** [comment]
Godot's GUI is made out of Godot's own GUI elements such as Controls and TreeNodes and HBoxContainers.

**Comment by KoBeWi** [comment]
This is not a question for GitHub. This is a place for reporting bugs, so unless you have one, use [other community channels](https://godotengine.org/community) next time.

As for the question, Godot has its own GUI system and doesn't use any library for that (AFAIK).

**Comment by arahulc91** [comment]
Thanks for the reply guys
