### ISSUE TITLE
Possible memory conflict with Photoshop

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#3411]
Every time I run the latest Godot 2.0 development build and Photoshop CC 2015 (the newest version) at the same time my computer gives me a low memory warning and crashes unless I close one of the programs. Now is this related to Godot? I do not know but maybe someone else has had the same problem?
I'm on a 16GB  Windows 8.1 machine.

**Comment by kubecz3k** [comment]
@PullTheStrings Sounds like some program on your computer have memory leak... Try to check with system monitor which one consumes your memory (it might be as well a browser or some system process)

**Comment by reduz** [comment]
maybe the machine you are running both on has low amount of GPU memory?

**Comment by Marqin** [comment]
Btw. you can use [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) ( from MS website ) to monitor also GPU Memory usage.

**Comment by Calinou** [comment]
[Process Hacker](http://processhacker.sourceforge.net/) is an handy debugging tool as well.

**Comment by PullTheStrings** [comment]
Thanks for the tips everyone. I'll try the tools you suggest.

**Comment by PullTheStrings** [comment]
I just used Process Explorer and apparently it's the System Commit that hits the roof at about 22 GB. According to the graphs the GPU memory is not the problem.
So it's Virtual Memory (Wikipedia said that's what System Commit means) that maxes out, but I still don't know why. The search continues.
Thanks again everyone.

**Comment by PullTheStrings** [comment]
Setting the memory usage of Photoshop CC 2015 to about 55 percent seems to have fixed problem. This is fair amount lower than previous versions of Photoshop.

**Comment by akien-mga** [comment]
Thanks for letting us now about how you could fix it, that might be useful if someone else has a similar issue (though I'm still puzzled why Godot would eat up so much memory when run next to Photoshop). Closing as it's likely not a Godot bug though :)
