### ISSUE TITLE
unexpected behaviour of array.erase( array[index] ) 

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#34116]
Godot 3.1.1
Windows 10

running this code:
```gdscript
	var array = [
		[1, 1, 1],
		[0, 0, 0],
		[1, 1, 1],
	]
	array.erase( array[2] )
	for line in array: print(line)
```

produces this output:
```
[0, 0, 0]
[1, 1, 1]
```
expected output:
```
[1, 1, 1]
[0, 0, 0]
```

I am aware I can do `array.remove[2]` instead.

Regardless, the described behaviour is not expected and can lead to an unexpected source of bugs, which is exactly how I found this.

I assume this is to the array equality comparison being done by element (#33627)
Arrays being unique to dictionaries and objects is a significant source of frustration.

**Comment by mikebow** [comment]
Hello rokasv,

As the documentation states in regards to the Array.erase(value) method: "Removes the first occurrence of a value from the array." 

Documentation link here: https://docs.godotengine.org/en/3.1/classes/class_array.html#class-array-method-erase

**Comment by fsy98** [comment]
I think you may have some misunderstand of the erase function, actually is to removes the first occurrence of a value from the array. So for your cases, It remove first line [1, 1, 1] .

**Comment by rokasv** [comment]
I understand it perfectly well, I just don't find it consistent with the rest of the language.

for example:
```
	var array = [
		{0:1},
		{0:0},
		{0:1},
	]
	array.erase( array[2] )
	for line in array: print(line)
```
produces:
```
{0:1}
{0:0}
```

I know why it's happening, I don't think I should have to remember whether I'm storing arrays or dictionaries. I do concede this is now essentially the same discussion as #33627

**Comment by KoBeWi** [comment]
Yep, this issue is covered by #33627, so closing.

The only thing that could be done (other than "resolving" #33627) is providing a way to use `erase` with custom comparator, but that's a thing for https://github.com/godotengine/godot-proposals/issues and would probably wait until lambda methods are implemented.
