### ISSUE TITLE
range(x,y) malfunctions for values greater than 0x1000000

### ISSUE THREAD

**Issue by rslepon** [godotengine/godot#34121]
**Godot version:**
Godot_v3.1.2-stable_win64

**Issue description:**
Using range(x,y) with values greater than 0x1000000 (16777216), where x and/or y are odd, results in an incorrect array with one or two extra values (as if x were x-1 and/or y were y+1).

Here is a code snippet to show this:
```
   for i in range(16777213, 16777215):
      print(i)
   print("====")
   for i in range(16777217, 16777219):
      print(i)
   print("====")
```

Its output is:
```
16777213
16777214
====
16777216
16777217
16777218
16777219
====
```

The former is correct, the latter is wrong.

P.S. The bug is slightly more complex than I had described. Not only may it result in one or two extra values; it may also result in one or two missing values. For example, range(16777219, 16777221) returns an empty array.

P.P.S. This bug also affects the range(x,y,step) flavour.

**Comment by Zylann** [comment]
They might have been converted to `float`, `16777219` is the maximum integer value they can accurately represent.

**Comment by rslepon** [comment]
Updated OP with P.S. and P.P.S.

**Comment by staddy** [comment]
The problem is here:
```
	switch (args.size()) {
		case 1: tn->vtype = Variant::INT; break;
		case 2: tn->vtype = Variant::VECTOR2; break;
		case 3: tn->vtype = Variant::VECTOR3; break;
	}
```
For the sake of optimization gdscript parser stores small ranges in 'for' loops (but not in standalone expressions of 'range') in Vector: Vector2 for 2 iterations and Vector3 for 3 respectively. Vector in Godot stores float values (to increase performance) so we have this problem here.
The simple solution is to check if the values can be stored in 24 bits for integers and avoid this optimization they can not.

**Comment by Zylann** [comment]
Another point for integer vectors to be added to the engine... unless there is a way to use some other data structure here? `Vector2` sounds quite an overuse here.

**Comment by Calinou** [comment]
@Zylann I can see `Vector2i` in the codebase, but no `Vector3i`. (`Vector2i` isn't exposed to GDScript.)

**Comment by staddy** [comment]
Turning off this optimization vanishes the bug:
```
	if (op->op == OperatorNode::OP_CALL && op->arguments[0]->type == Node::TYPE_BUILT_IN_FUNCTION && static_cast<BuiltInFunctionNode *>(op->arguments[0])->function == GDScriptFunctions::GEN_RANGE) {
		//iterating a range, so see if range() can be optimized without allocating memory, by replacing it by vectors (which can work as iterable too!)
	/* ... */
```
The solution for constant int 'range' arguments would be something like also checking (static_cast<int>(0xFF000000) > value) && (value < static_cast<int>(0x01000000)
Though this code for ConstantNodes is never executed, guess it's another minor bug:
```
	bool constant = false; // should be true

	for (int i = 1; i < op->arguments.size(); i++) {
		args.push_back(op->arguments[i]);
		if (constant && op->arguments[i]->type == Node::TYPE_CONSTANT) {
			ConstantNode *c = static_cast<ConstantNode *>(op->arguments[i]);
			if (c->value.get_type() == Variant::REAL || c->value.get_type() == Variant::INT) {
				constants.push_back(c->value);
				constant = true;
			}
		} else {
			constant = false;
		}
	}
```
But for int variables a larger iterable structure is needed.
