### ISSUE TITLE
Collision detected only when moving

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#34124]
**Godot version:** 3.1.2 stable

**OS/device including version:** Win7

**Issue description:**
Collision is only detected when either colliding object is moving.
![collision_only_when_moving](https://user-images.githubusercontent.com/47016402/70263854-91b0b900-1797-11ea-96ef-ec9508da56e4.gif)

**Steps to reproduce:**
Animate the CollisionShape of an Area2D and try to detect it in another not moving object.

**Minimal reproduction project:**
[Collision_only_when_moving.zip](https://github.com/godotengine/godot/files/3928544/Collision_only_when_moving.zip)

**Comment by golddotasksquestions** [comment]
Can confirm same bug in 3.0.6 as well.
Minimal 3.0.6 project:
[3.0.6_Collision_only_when_moving.zip](https://github.com/godotengine/godot/files/3953834/3.0.6_Collision_only_when_moving.zip)

**Comment by golddotasksquestions** [comment]
Can confirm the same effect without the AnimationPlayer, just using code:
![collision_only_when_moving_code1](https://user-images.githubusercontent.com/47016402/71487202-7119d300-281a-11ea-8c9d-50f29eb88d37.gif)

**Comment by golddotasksquestions** [comment]
Tested with RigidBodies2D, exactly the same effect. Collision are not detected when shape properties are changed in code or via animation.

**Comment by iamiota** [comment]
Add `position = position` in the last line of `func _physics_process`.

**Comment by golddotasksquestions** [comment]
This works @iamiota  but makes absolutely no sense to me whatsoever.
