### ISSUE TITLE
Can't instantiate external subclass in other subclasses (identifier not declared)

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#34137]
**Godot version:** v3.1.1 stable

**OS/device including version:** Linux, Solus OS, v4.0 Fortitude

**Issue description:** You can't instantiate a class from an external custom class in another custom class.

**Steps to reproduce:**
```
extends Node

var ext = load("res://ExternalClass.gd")  # File contains class titled Subclass.

func _ready():
    var sub = ext.Subclass.new() # Works fine
	
class Another:
    func _init():	
        var sub = ext.Subclass.new() # Doesn't work

```

**Minimal reproduction project:** [BuggedInstantiation.zip](https://github.com/godotengine/godot/files/3930969/BuggedInstantiation.zip)

**Comment by KoBeWi** [comment]
Well, this does not work either
```
var a = 1
class Another:
	func _init():
		print(a)
```
Sub-classes aren't like internal classes in Java - they don't have access to properties of the script they are in.

So either provide `ext` in the constructor of Another or use `class_name` for external class.

**Comment by SolarLune** [comment]
Thanks for the information - sounds like this is a scope issue, then. It might be good to [update the documentation](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#inner-classes) to mention that.
