### ISSUE TITLE
RichTextLabel: BBCode [color] tags break DynamicFont extra Char spacing

### ISSUE THREAD

**Issue by cwook** [godotengine/godot#34130]
**Godot version:**
3.2 beta2 official, tested with both GLES2 and GLES3 renderer.
**OS/device including version:**
Windows 7 Ultimate, 64-bit 
**Issue description:**
In RichTextLabel bbcode, a [color] tag will replace the char spacing specified in the given DynamicFont with the default char spacing.

![image](https://user-images.githubusercontent.com/1891696/70284445-e9f9b200-17bb-11ea-9699-74fa318ad7e8.png)

**Steps to reproduce:**
1. Add a RichTextLabel and enable bbcode.
2. Add some bbcode using color tags:
```` 
[center]|||||[/center]
[color=#ff00ff00]||||||[/color][color=#ffffff00]||||||[/color][color=#ffff0000]||||||[/color]
||[color=#ffffffff]|||||||[/color]
````
3. Add a custom font and adjust the extra spacing for char.

**Minimal reproduction project:**
[DemoRTLDynamicFontCharSpacing.zip](https://github.com/godotengine/godot/files/3929689/DemoRTLDynamicFontCharSpacing.zip)

**Comment by Calinou** [comment]
Related to #31089.
