### ISSUE TITLE
iOS build error Entry point (_main) undefined. for architecture armv7

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#34135]
**Godot version:**
3.2beta3
**OS/device including version:**
Linux / Pop OS 19.10 
**Issue description:**
iOS build error Entry point (_main) undefined. for architecture armv7 when exporting iOS with armv7 checked on

missing required architecture armv7 in file .../.../.../project.a (2 slices)
entry point (_main) undefined.  for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Steps to reproduce:**
export project to iOS with armv7 checked on
**Minimal reproduction project:**

**Comment by bruvzg** [comment]
Official 3.2 beta export templates are shipped without ARMv7 support.

**Comment by oeleo1** [comment]
> Official 3.2 beta export templates are shipped without ARMv7 support.
Which is a problem even on MacOS and precisely the subject of this issue. 

The default behavior is to have the arm7 checkbox ticked at export time, the generated project has arm7 and arm64 as supported architectures and Xcode hits you with this error when trying to compile the project.

While I am on it, another systematic problem I have with the generated .xcodeproj is that I always have to manually fill in "LaunchScreen" in the Launch Screen File field, otherwise the opening screen at launch is always white when loading and initializing the engine (before the splash screen), while I want it black as configured in the game (and most certainly other people want it in another color).

**Comment by akien-mga** [comment]
BTW @Calinou, could you add in the 3.2 changelog for iOS that `armv7` and `x86` libraries are no longer included in the official templates, as they are no longer relevant for the current iOS market (so only `arm64` (v8) and `x86_64` remain). Users can still ship projects with `armv7` support if they compile their own templates.

**Comment by oeleo1** [comment]
The basic question is whether Apple still requires arm7 support to be included when publishing to the AppStore. Has anyone tested it?

**Comment by akien-mga** [comment]
That would be important to check indeed, reopening until we get a confirmation.
I doubt that Apple would require armv7 support when it has pushed so hard to obsolete it (and the newest armv7 devices are stuck on iOS 10.x), but we should double check.

**Comment by Calinou** [comment]
@akien-mga Added to the changelog.

**Comment by HEAVYPOLY** [comment]
Tested publishing to AppStore without armv7 and works!

**Comment by akien-mga** [comment]
Thanks!

**Comment by RocketBlueAutomation** [comment]
I’m still getting the message “Entry point (_main) undefined for architecture armv7” when compiling Xcode generated by Godot 3.2.1 for my iPad gen5 and iPhone 8.  I just finished setting my system up with all the latest, including macOS Catalina 10.15.5.
How do I disable a need to compile for arm7 in Xcode 11?

**Comment by vanoak** [comment]
Why have the armv7 checkbox on the templates if the architecture is no longer included in the official support? 

(Not critical, but I have spent a couple of hours on this - made an app for my 7 year old kid who inherited an old iPad 2)

**Comment by Calinou** [comment]
> Why have the armv7 checkbox on the templates if the architecture is no longer included in the official support?

It can be included in self-compiled export templates, although there are no plans to do this officially.

**Comment by vanoak** [comment]
Thank you @Calinou.
