### ISSUE TITLE
Access exported script vars on a scene that is not yet loaded and instanced

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#3413]
**Lukas Sägesser:**
Is it somehow possible to read exported vars on a node in a scene that is not yet loaded and not yet instanced? While it is still being loaded with resource loader?

I like to use exported vars to configure on each level-scene the enemies and powerups that are allowed in this level. And I'd like to display info on these while the level is loading, to pass the time.

**Juan Alpaca:**
ah.. I think there is an API for this but not sure if it is exported to script, I guess it could be exported to script.

**Rémi Verschelde:** 
+1, for our current game with the Kobuge guys we also had to workaround this to display the characteristics of towers (defined as export vars in the tower scenes) in the game HUD, by instancing dummy tower scenes just for the HUD.

**Juan Alpaca:** 
make an issue request and mark it as a bug, as this API should be available to script

**Comment by reduz** [comment]
It's a crude API but should allow to access all data inside a PackedScene
