### ISSUE TITLE
Wierd path using Navigation on 3D Gridmap

### ISSUE THREAD

**Issue by grusad** [godotengine/godot#34139]
**Godot version:**

3.2.2

**OS/device including version:**

Linux Min

**Issue description:**
by getting the path with optimization to false this is the path retrived. What is going on?
The final target is correct but the path to travel to the target is not very good.
Am i doing something wrong?

![image](https://user-images.githubusercontent.com/23147905/70308416-7ed7cc00-180b-11ea-929f-3999e77c3908.png)

**Steps to reproduce:**

Create a navigation and give it a child gridmap with with a meshlib. Apply a navigationMeshinstance to the floortile. Draw a map with floor (navigationmeshinstance) and some walls. The moving object should be a kinematic body and apply get try moving the kinematicbody along the gridmap by getting the path from the Navigation.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@grusad Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
