### ISSUE TITLE
base64_to_utf8  removes closing bracket :(

### ISSUE THREAD

**Issue by kodkuce** [godotengine/godot#34145]
**Godot version:**
3.2.beta2

**OS/device including version:**
Void Linux 
5.3.15_1

**Issue description:**
So i just want to base64 decode my string
but for some reason it removes closing bracked } form it
tested here https://www.base64decode.org/ and on some other sites and it
works normal so i am like 95% sure this is a bug

**Steps to reproduce:**
run this code in any script

```
var zzz:String = "eyJpZCI6IjIiLCJleHAiOjE1NzU3MjQ0MzcsInJvbGUiOiJwbGF5ZXIiLCJwb2ludHMiOiIxOTgwMDAifQ"
var wtf = Marshalls.base64_to_utf8(zzz)
print(wtf)  #it misses closing }
print(wtf.length()) #gives 60 instead  61 so guess it isent print issue
```

**Minimal reproduction project:**
just copy paste :)

**Comment by akien-mga** [comment]
While https://www.base64decode.org/ does decode your string correctly, there seems to be something missing from it.

For the source string `{"id":"2","exp":1575724437,"role":"player","points":"198000"}`, https://www.base64encode.org/ gives `eyJpZCI6IjIiLCJleHAiOjE1NzU3MjQ0MzcsInJvbGUiOiJwbGF5ZXIiLCJwb2ludHMiOiIxOTgwMDAifQ==`. Note the `==` at the end.

Godot gives the same:
```
var test = '{"id":"2","exp":1575724437,"role":"player","points":"198000"}'
var base64 = Marshalls.utf8_to_base64(test)
print(base64)
var utf8 = Marshalls.base64_to_utf8(base64)
print(utf8)
print(utf8 == test)
```
gives:
```
eyJpZCI6IjIiLCJleHAiOjE1NzU3MjQ0MzcsInJvbGUiOiJwbGF5ZXIiLCJwb2ludHMiOiIxOTgwMDAifQ==
{"id":"2","exp":1575724437,"role":"player","points":"198000"}
True
```

And indeed, both Godot and base64encode.org encode `}` as `fQ==`, so your source string is bogus. I guess base64decode.org is more lenient than Godot and can figure out that `fQ` might be a truncated `}`, while Godot expects a valid base64 string.

**Comment by kodkuce** [comment]
yep you are right, its my bad i mixed base64 with base64uri from JWT, sorry
