### ISSUE TITLE
Selected items in ItemList are too offset to the left

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3414]
Related to #3096 and the PR that attempts to fix it, #3409. Once the background colour part of the issue is fixed, there is still the error that the selected item is too offset to the left, and thus the left part of the StyleBox is not visible. With PR #3409, it's extended to all items since the custom background colour will extend to the same width as the StyleBox selector, so it will also have a start position out of the ItemList panel.

Current status (with PR #3409, but without it's still similar for the StyleBox, only the background colour area changes):
![r pos x-4_](https://cloud.githubusercontent.com/assets/4701338/12518064/8424c3dc-c136-11e5-8982-73e8363f7427.png)

What it should be:
![r pos x1_](https://cloud.githubusercontent.com/assets/4701338/12518069/89055722-c136-11e5-90a6-44dd3dfb41f5.png)
(or maybe with a bit more offset between the left part of the StyleBox and the icon, i.e. the icon and text should be offset to the right a bit).

**Comment by akien-mga** [comment]
I've looked a bit into it by myself already, but I chose to write this issue to ask someone more experienced to fix, as I can't come up with a clever solution :)

The code responsible for this placement is here: https://github.com/akien-mga/godot/blob/1120b6ae0dd997b67e178b903fc32c1a169f1448/scene/gui/item_list.cpp#L830-L837
(this comes from PR #3409, so if it's not merged, the code that should be considered is https://github.com/godotengine/godot/blob/081a236/scene/gui/item_list.cpp#L835-L841, but the logic is exactly the same)

The problem is that by default (or at least as used in the script editor plugin), ```base_ofs``` is (4,4) and all the margins of ```sbsel``` are 8, so ```r.pos.x``` ends up being -4. For the screenshot I put above as the "correct looks", I just hacked it this way:
```
diff --git a/scene/gui/item_list.cpp b/scene/gui/item_list.cpp
index 2d2cabf..13bd362 100644
--- a/scene/gui/item_list.cpp
+++ b/scene/gui/item_list.cpp
@@ -832,9 +832,11 @@ void ItemList::_notification(int p_what) {
 
                        // Use stylebox to dimension potential bg color, even if not selected
                        r.pos.x-=sbsel->get_margin(MARGIN_LEFT);
+                        r.pos.x=MAX(r.pos.x,1);
                        r.size.x+=sbsel->get_margin(MARGIN_LEFT)+sbsel->get_margin(MARGIN_RIGHT);
                        r.pos.y-=sbsel->get_margin(MARGIN_TOP);
                        r.size.y+=sbsel->get_margin(MARGIN_TOP)+sbsel->get_margin(MARGIN_BOTTOM);
+                        r.pos.y=MAX(r.pos.y,1);
 
                        if (items[i].selected) {
                                draw_style_box(sbsel,r);
```

But it's obviously not a good solution as if some styles use different margins, or if there are several columns in the ItemList (I think it's designed for multiple columns? but I haven't looked much into this), it might mess things up.

So, setting as a junior job as it should not be so hard to fix, but right now I'm clueless as for the "good way" to fix it :)

**Comment by akien-mga** [comment]
A solution might be to drop all this custom margin stuff and just make the StyleBox (and thus the bg colour + actually icon + text positions) scale on the available width (as seems to be started in the ```if``` just before the code I linked, but then with all the offsets and margins I get lost :p).

**Comment by bojidar-bg** [comment]
Is this still valid?

**Comment by volzhs** [comment]
@bojidar-bg yes. Windows 10, current head.
