### ISSUE TITLE
Command line export doesn't work in Windows 10 for Godot 3.1.2 due to error code 12

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot#34148]
**Godot version:**

3.1.2 (the official one)

**OS/device including version:**

Windows 10

**Issue description:**

Exporting a Godot project (even a brand-new one) doesn't work in the command line as it returns an error:
![failure_export_312](https://user-images.githubusercontent.com/42484461/70344257-8a51e400-1859-11ea-8ecc-f925e25f92d2.PNG)

**Steps to reproduce:**

- Make a new Godot Project in 3.1.2
- Create some node (in my case I created a Node2D) and configure it to be the main scene.
- Make an export preset for windows: "Windows Desktop"
- Run following command in powershell (or any other cmd tool):
`godot -e -v --export-debug "Windows Desktop" build/test.exe`
- Exporting fails due to error code 12

Downgrade to Godot v3.1.1 and do the exact same steps. The export completes successfully without any issues... as seen here:

![succes_export_311](https://user-images.githubusercontent.com/42484461/70344269-95a50f80-1859-11ea-85ec-c5dd570237be.PNG)

**Comment by akien-mga** [comment]
Tested on Linux, it seems to work fine there:
```
~/tmp/godot/stable/3.1/Godot_v3.1.2-stable_x11.64 -e -v --export-debug "Linux/X11" build/test.x86_64
```

Note that I created the `build` folder beforehand. If I don't and the directory is missing, I get:
```
ERROR: _fs_changed: Project export failed with error code 9.
   At: editor/editor_node.cpp:495.
```
Maybe that's your issue?

It seems to fail the same in 3.1.1 so that wouldn't be a regression.

**Comment by 2shady4u** [comment]
I also get error code 9 when I don't make the folder beforehand.
(in both 3.1.1 and 3.1.2)

However, the error code 12 only appears when I try to export with 3.1.2 in Windows 10.
I didnt try this yet with Linux or MacOsX so I have no idea if those OS' have the same issue...

**Comment by 2shady4u** [comment]
So on Ubuntu LTS (18), I get following behaviour:

Godot v3.1.1, exporting to Windows:
![linux-311](https://user-images.githubusercontent.com/42484461/70362064-fcd7b980-1883-11ea-9466-c712befbb498.PNG)

Godot v3.1.2, exporting to Windows:
![linux-312](https://user-images.githubusercontent.com/42484461/70362065-fd705000-1883-11ea-8831-d48df0aa3db3.PNG)

So it works on Linux (except for the memory leak, but whatever)

**Comment by garyritchie** [comment]
Export path seems _relative to project location_.

Example: `godot -v --export "Windows Desktop" ../BUILD/LTG.exe --path ENGINE/`

This works for me where I have `ENGINE/project.godot` and `BUILD/` within my repo. Tell all your friends and save 'em some frustration.

**Comment by 2shady4u** [comment]
@garyritchie 
Thanks that did the trick!

Also shout-out to Calinou for adding this to the --help command (https://github.com/godotengine/godot/pull/34589) to spare future generations from running into this issue.

Closing this...
