### ISSUE TITLE
Changing SpinBox values in inspector is made unpractical by the "revert" button in instanced scenes

### ISSUE THREAD

**Issue by fry-** [godotengine/godot#3415]
![godot_spinbox_issue](https://cloud.githubusercontent.com/assets/10758005/12523932/17cfcd98-c15a-11e5-864a-1f9377cb3549.png)
When you have an instanced scene, and want to change values in any SpinBox within the inspector by clicking the arrows, the "revert" button appears at every 2nd click on an arrow and by that causes an annoying resizing of the SpinBox. 1st click = revert appears, 2nd click = disappears, 3rd = appears, ....

The problem here is, that by resizing the SpinBox, the arrow buttons move around every time you click them. So you can't make a simple *klick, klick, klick* to add +3 quickly, you always have to move around the mouse to find that arrow key again. Check the images for better understanding :grinning:

**Comment by reduz** [comment]
yes indeed. I wonder how to fix this..  maybe we should leave the space of
the revert empty just in case?


On Fri, Jan 22, 2016 at 6:57 PM, Johannes Danneker <notifications@github.com

**Comment by akien-mga** [comment]
> maybe we should leave the space of the revert empty just in case?

I thought that too, it's probably the simplest solution. The other possibility would be to put the revert icon on the left, but that wouldn't look good IMO.

**Comment by akien-mga** [comment]
If we're concerned by losing some space by moving all fields somewhat to the left, we can probably mitigate it by reducing a bit the padding between the revert icon and the actual SpinBox (or other controls where it might be relevant btw).

**Comment by neikeq** [comment]
The only solution that comes to my mind would be to put the revert button before the Spinbox (or even before the property name) and perhaps use a smaller icon.

**Comment by akien-mga** [comment]
+1 for using a smaller icon, as currently it changes the height of the lines when it appears, as it's slighter bigger than the default height.
