### ISSUE TITLE
TCP_Server opens 2 connections

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#34151]
**Godot version:**
Tried Beta 1, Beta 3, Stable 1.1
**OS/device including version:**
Windows 10 1903
**Issue description:**
I'm building an HTTP File server and so far everything works fine (even posting large files). But, after spending a few hours to figure out why its lossing a few packets sometimes i saw that it opens connections twice. At first i ignred it and clossed the second connection, but then i realized its missing packets.
**Steps to reproduce:**

```
	if TCPServer.is_connection_available(): # TAKES 2 CONNECTIONS
		var conn = TCPServer.take_connection()
		print("Client connected! ", conn)
```
![image](https://user-images.githubusercontent.com/1850856/70348294-13bde200-186b-11ea-994f-a1a7604edada.png)
**Minimal reproduction project:**
[HTTP-Server-Test.zip](https://github.com/godotengine/godot/files/3933559/HTTP-Server-Test.zip)

EDIT: Also, `client.is_connected_to_host()` doesn't work unless you invoke `client.get_status()`. This means that if i do the following check inside `_process` `if client.is_connected_to_host()` without the `get_status()` the client will never disconnect.
![image](https://user-images.githubusercontent.com/1850856/70351463-a2cdf880-1871-11ea-89ed-32905cc7c90d.png)

**Comment by groud** [comment]
If you don't describe your problem, it cannot be solved.

**Comment by zaksnet** [comment]
> If you don't describe your problem, it cannot be solved.

Yeah sorry for the mess, i lagged >.<

**Comment by groud** [comment]
No problem :)

**Comment by Faless** [comment]
> I'm building an HTTP File server and so far everything works fine (even posting large files). But, after spending a few hours to figure out why its lossing a few packets sometimes i saw that it opens connections twice. At first i ignred it and clossed the second connection, but then i realized its missing packets.

I'm unable to reproduce this issue, I only get one connection (and with the demo it gets immediately disconnected because you don't keep the connection reference).
May it be that the program you are using try to connect 2 times if the first time fails? Many software do, even browsers. Can you try with `telnet`?

![one_conn](https://user-images.githubusercontent.com/1687918/70862567-4f793b80-1f3e-11ea-99de-1af613dd5dd1.png)

> EDIT: Also, `client.is_connected_to_host()` doesn't work unless you invoke `client.get_status()`. This means that if i do the following check inside `_process` `if client.is_connected_to_host()` without the `get_status()` the client will never disconnect.

This is a known issue, will be changed in `4.0`, in general, streams need refactoring exposing `poll`. See discussion in #22605 and #22191 .

**Comment by zaksnet** [comment]
Sorry i forgot to update the status on this. The problem was with the program i used to make the calls [POSTMAN](https://www.getpostman.com/). It kept opening 2 connections for some reason, maybe the first one was failing as you say but I'm pretty sure i kept a reference. Then i used another program called [INSOMNIA](https://insomnia.rest/) (i needed these because i also needed the headers) and it seemed to work fine. Finally, i am now using your excellent implementation of web-sockets as a file-server (never though i could use this to serve files) which seem to be much better, at-least for local network file transfers (i still don't know how to handle the lost packets, while TCP handled these itself).
