### ISSUE TITLE
Websocket Server Communication is much slower on 3.2 

### ISSUE THREAD

**Issue by Fr0sk** [godotengine/godot#34153]
**Godot version:** Godot_v3.2-beta3_win64

**OS/device including version:** Windows 10

**Issue description:** The communication between a Websocket Server on Godot and a client in another language is much slower than it was on Godot v3.1.1. The latency of the messages is practically unnoticeable on 3.1.1 and on 3.2 it is quite visible. Is there a way to make it more responsive?

**Steps to reproduce:** Creating a Websocket Server on Godot and a client on another language. Send messages from the server to the client.

**Comment by Calinou** [comment]
Can you upload a minimal reproduction project to make this easier to troubleshoot?

**Comment by Fr0sk** [comment]
Well, I created a sample project with Godot as a server and a Python client and the latency is pretty much okay, no noticeable delay. The problem I described was connecting Godot to a microcontroller (ESP32), but it might be a problem with my main project. I do not have access to the ESP for about 12 hours, so if the issue can be opened for that time, I can test this sample project I created with it. 

It looks like it's something on my side, but it is strange as the same project opened with Godot v3.1.1 works well and 3.2 has about 300 to 500ms of latency...

**Comment by gururise** [comment]
UDP or TCP?  I've used Godot to communicate with an ESP8266 using UDP websockets and had no issue, but that was with 3.1.1

I'll try with 3.2 tomorrow.  By the way, how are you testing latency?

**Comment by Fr0sk** [comment]
Sorry, I forgot to update this. The sample project works well with the ESP32, so I'm still trying to pinpoint the problem, but the issue might be on the main project. I am using quite a few Websocket Servers, that might be it. I'll try to change the way it works to use only one and route the messages based on the protocol.

@gururise I'm not sure if I'm using TCP or UDP, I would assume it is TCP as it is the standard for WebSockets. Is there a way to change it? I'm using the [WebSocketServer Class](https://docs.godotengine.org/en/3.1/classes/class_websocketserver.html). Also, I'm not using any scientific method to test the latency, just have the ESP toggling a LED each time it receives a message, and Godot sending one after a certain keypress. While I don't need the latency to be super low, I will be needing to send at least 10 messages a second, and right now it can only do 2, 3 at most. There is a visible and noticeable latency that when tried with Godot 3.1 does not happen.

**Comment by Fr0sk** [comment]
Well, sorry folks, it was my fault. Multiple Websocket Servers weren't the issue (although I might still change the way it works) but I completely forgot I had set 

> low_processor_usage_mode = true

That was probably affecting the polling time and resulting in the high latency I was experiencing. If nobody has anything else to add, I think this issue can be closed.

**Comment by Faless** [comment]
> That was probably affecting the polling time and resulting in the high latency I was experiencing. If nobody has anything else to add, I think this issue can be closed.

I'm glad you solved you issue.
Closing, feel free to add more comments or open a new issue if experience any new problem.
