### ISSUE TITLE
Is there any problem with the option Billboard Mode of Particles 3D?

### ISSUE THREAD

**Issue by jhojantobonm** [godotengine/godot#34158]
**Godot version:**
All versions

**OS/device including version:**
Windows 10 Home Single Language

**Issue description:**

I have been trying to make the particles visualizing the same way from all angles (always looking at camera) with the option "Billboard Mode" set to "Enabled" but nothing seems to work, it keeps up looking the same as with that option "Disabled", I mean nothing change. I tried all versions including 3.2b, but nothing. What am I doing wrong?. Kind regards.

**Steps to reproduce:**

1. Create New Project - GLES3
2. Create 3D scene.
3. Add Partcles Node.

Options Particles Node

4. Create NewProcessMaterial
5. Assign NewQuadMesh to Draw Passes
6. In Geometry Instance - Create NewSpatialMaterial

Options Spatial Material

7. In Parameters set Billboard Mode to Enabled
8. In Albedo assign a texture.

End

**Minimal reproduction project:**

[ParticlesTest.zip](https://github.com/godotengine/godot/files/3933951/ParticlesTest.zip)

**Comment by Chaosus** [comment]
Strange, in the provided example it looks correct...

![image](https://user-images.githubusercontent.com/3036176/70374336-20d9e000-1902-11ea-8a61-9ea69a524565.png)

**Comment by jhojantobonm** [comment]
Yes, It looks correct. Will it be the CPU? I have AMD in both my laptop and PC.
And this is what I see.
![1](https://user-images.githubusercontent.com/42913311/70374644-a178ec00-18c2-11ea-811a-d3020e14c98d.jpg)

**Comment by Chaosus** [comment]
Particles are GPU-accelerated, for the CPU you should use CPUParticles. I have an NVidia card so it may be a driver related problem.

**Comment by Chaosus** [comment]
Please post information about your card, so developers can fix your problem

**Comment by jhojantobonm** [comment]
This is strange, I have to say the Unity3D Particle System works well in both my PC and laptop.
![unity](https://user-images.githubusercontent.com/42913311/70375124-39c59f80-18c8-11ea-9a0f-1512420abd13.jpg)
I think Godot should bihave of similar way without any special GPU or CPU. 
These are the specifications of my PC
![PC_SYSTEM](https://user-images.githubusercontent.com/42913311/70375173-ddaf4b00-18c8-11ea-95ff-4b7251159f45.jpg)
![PC_GRPHICS](https://user-images.githubusercontent.com/42913311/70375179-e43dc280-18c8-11ea-8b57-1304265c8242.jpg)
And these are from my laptop.
![LAPTOP_SYSTEM](https://user-images.githubusercontent.com/42913311/70375207-19e2ab80-18c9-11ea-9819-1d818b74d849.jpg)
![LAPTOP_GRAPHICS](https://user-images.githubusercontent.com/42913311/70375209-1e0ec900-18c9-11ea-9d73-815124e8e2cd.jpg)
Kind regards.

**Comment by Calinou** [comment]
@jhojantobonm For simple use cases, you can use the CPUParticles node which will work regardless of driver support.

Unfortunately, AMD's graphics drivers on Windows have a poor OpenGL implementation, especially on older/low-end cards like the one you have. We don't have the resources to fix this bug, as most contributors don't even have access to such hardware.

**Comment by jhojantobonm** [comment]
Bad news, So I need to have a PC with Intel CPU for running this particles well?  What a shame.

**Comment by jhojantobonm** [comment]
I wondering How does Unity to not have this problem.

**Comment by jhojantobonm** [comment]
Well, I tried. Thanks.

**Comment by Calinou** [comment]
@jhojantobonm It's not about the CPU, but about the GPU (graphics card).

**Comment by akien-mga** [comment]
> I wondering How does Unity to not have this problem.

Either their particles are CPU based as @Calinou mentioned, or if they're GPU-based, keep in mind that Unity uses DirectX on Windows, while we use OpenGL. So bad OpenGL drivers on older cards is not a problem for them as long as the DirectX drivers work ok (which they typically do, as GPU vendors spend a lot more resources on DirectX than OpenGL on Windows).

**Comment by jhojantobonm** [comment]
Hello guys, I am very happy because I was be able to solve this problem simply just by updating my AMD controller. This is the result.

![1](https://user-images.githubusercontent.com/42913311/70713583-5a20a000-1cb4-11ea-9204-d67e4d3eeff5.png)
