### ISSUE TITLE
The doc page for ProjectSettings has presentation issues due to InputEventKey serialization

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34154]
Godot 3.2 beta2

Looked up properties of `ProjectSettings` in the doc: strings are cut off, and values shown as data trees are not prettified.

![image](https://user-images.githubusercontent.com/1311555/70351601-34813a00-1861-11ea-9024-ef3a06a8cdf7.png)

**Comment by akien-mga** [comment]
The type column should likely get a higher min width, or better compute its required width to fit its contents, and enforce that (assuming we won't have types like `LoremIpsumDolorSitAmetConsecteturAdipiscingElitConstructionSiteBuilderFactoryManager`).

The issue right now seems to be caused by the InputEvent serialization for `input/` properties, which as mentioned is not prettied, but also a very long string without spaces, so it squishes the left column to fit as much as possible on one line before being forced to wrap mid-word.

CC @bojidar-bg @Calinou @YeldhamDev

**Comment by lakshay-angrish** [comment]
Where can the column width be changed in the code? And how would you correct the prettifying problem?

**Comment by Calinou** [comment]
@lakshay-angrish The margins were added in #31588, but I'd prefer we not remove them as these help with readability in all other documentation pages.

**Comment by akien-mga** [comment]
The default value for default InputMap events can be overridden to alleviate this issue, with:
```diff
diff --git a/core/project_settings.cpp b/core/project_settings.cpp
index a01a8a35c6..8e6e9528c6 100644
--- a/core/project_settings.cpp
+++ b/core/project_settings.cpp
@@ -1005,11 +1005,6 @@ ProjectSettings::ProjectSettings() {
 	disable_feature_overrides = false;
 	registering_order = true;
 
-	Array events;
-	Dictionary action;
-	Ref<InputEventKey> key;
-	Ref<InputEventJoypadButton> joyb;
-
 	GLOBAL_DEF("application/config/name", "");
 	GLOBAL_DEF("application/config/description", "");
 	custom_prop_info["application/config/description"] = PropertyInfo(Variant::STRING, "application/config/description", PROPERTY_HINT_MULTILINE_TEXT);
@@ -1035,6 +1030,12 @@ ProjectSettings::ProjectSettings() {
 	GLOBAL_DEF("editor/script_templates_search_path", "res://script_templates");
 	custom_prop_info["editor/script_templates_search_path"] = PropertyInfo(Variant::STRING, "editor/script_templates_search_path", PROPERTY_HINT_DIR);
 
+	// Default InputMap.
+	Array events;
+	Dictionary action;
+	Ref<InputEventKey> key;
+	Ref<InputEventJoypadButton> joyb;
+
 	action = Dictionary();
 	action["deadzone"] = Variant(0.5f);
 	events = Array();
@@ -1193,6 +1194,15 @@ ProjectSettings::ProjectSettings() {
 	GLOBAL_DEF("input/ui_end", action);
 	input_presets.push_back("input/ui_end");
 
+	// Hide default value in the docs, InputEvents serialization is not really
+	// human-readable for now (GH-34154).
+	action = Dictionary();
+	action["deadzone"] = Variant(0.5f);
+	action["events"] = Array();
+	for (int i = 0; i < input_presets.size(); i++) {
+		ADD_PROPERTY_DEFAULT(input_presets[i], action);
+	}
+
 	custom_prop_info["display/window/handheld/orientation"] = PropertyInfo(Variant::STRING, "display/window/handheld/orientation", PROPERTY_HINT_ENUM, "landscape,portrait,reverse_landscape,reverse_portrait,sensor_landscape,sensor_portrait,sensor");
 	custom_prop_info["rendering/threads/thread_model"] = PropertyInfo(Variant::INT, "rendering/threads/thread_model", PROPERTY_HINT_ENUM, "Single-Unsafe,Single-Safe,Multi-Threaded");
 	custom_prop_info["physics/2d/thread_model"] = PropertyInfo(Variant::INT, "physics/2d/thread_model", PROPERTY_HINT_ENUM, "Single-Unsafe,Single-Safe,Multi-Threaded");
```

But the formatting problem is still not solved, as the ProjectSettings docs also include properties from the edited project's `project.godot`...

![Screenshot_20200122_131206](https://user-images.githubusercontent.com/4701338/72893298-f8bf0880-3d18-11ea-9c43-4f7f1b03b2cc.png)
