### ISSUE TITLE
Autocomplete not showing properties of a class that is itself a property

### ISSUE THREAD

**Issue by scurvycapn** [godotengine/godot#34150]
**Godot version:** 3.2.beta3

**OS/device including version:** Windows 10

**Issue description:**
I noticed a change in autofill functionality from 3.1.1. Apologies if the title is confusing, but hopefully these examples get the point across. (Edit: I just downloaded 3.1.2 and it displays the same behavior as 3.2beta3)

In my testing, the scene simply has a Node2D (I have tried with a Spatial and get the same results for translation).

In the first example (left column), in 3.1.1, if I access the Node2D's position property, the x and y properties of the Vector2 are displayed along with all of the methods in the autocomplete (top image). If I try this in 3.2beta3, I only see the methods of the position (second image). However, if I declare a Vector2, the properties show up in autocomplete as expected (third image).

For the second example (right column), I declare a Transform2D. In 3.1.1, I can access the Transform2D's origin property's properties in the autocomplete (top image). In 3.2beta3, only the methods appear (second image), as x/y are the properties of the origin property. But as before, I can access the properties of the Transform2D itself in the autocomplete as it is not nested within a property itself (third image).

![propertyissue](https://user-images.githubusercontent.com/46951652/70344182-10086c00-1827-11ea-8fa8-8928bf8847d1.png)

**Steps to reproduce:**
Create a Node2D and try to access the properties of the position property or any other property that has "nested" properties.

**Comment by KoBeWi** [comment]
Seems fixed in 3.2.3
