### ISSUE TITLE
Matrix multiplication inverted ingame and in editor??

### ISSUE THREAD

**Issue by Kobrar** [godotengine/godot#34162]
**Godot version:** 3.1.1

**OS/device including version:** Windows 7

**Issue description:** at a glance it looks like vec3 * mat3 and mat3 * vec3 are swapped ingame in shaders.

**Steps to reproduce:**
1. Multiply vector by a matrix in shaders.
2. Observe difference in output in editor and ingame.

Attached a project that displays the issue on my end.
I can't get anyone to confirm it for me right now so I might as well report it.

**Minimal reproduction project:**  
[Shader Bug Report.zip](https://github.com/godotengine/godot/files/3934436/Shader.Bug.Report.zip)

**Comment by akien-mga** [comment]
What's the issue exactly?

It's normal that `vec3 * mat3` and `mat3 * vec3` give different results, matrix multiplication is not a commutative operation unlike scalar multiplication.

**Comment by Kobrar** [comment]
I have different results in editor preview and ingame. Included screenshot.
![shader_bug](https://user-images.githubusercontent.com/5860567/70365394-788c3300-1891-11ea-8862-e50eac6e404b.PNG)

**Comment by Kobrar** [comment]
I confirmed that the issue was purely on my end and not really a Godot thing. If Godot got confused somehow by the way I was using it, I don't have the steps to reproduce that behaviour.
