### ISSUE TITLE
TextEdit is not exposing a way to set completion items

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34168]
Godot 3.2 beta2

`TextEdit` exposes all sorts of properties about completion and a signal to trigger it, but nothing to actually set which items will be proposed in such completion. In C++ there are several public methods dealing with that, but they are not exposed. Should they be exposed? How can it be scripted otherwise?

**Comment by lupoDharkael** [comment]
I've just found about this, any news or discussion about this feature? Should a proposal be created?
