### ISSUE TITLE
Menu not dimmed when exit confirm dialog appears

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34169]
**Godot version:** v3.1.2.stable.official & v3.2.beta.custom_build.ff58030ed

**OS/device including version:** macOS Catalina 10.15.1

**Issue description:**
The "Exit the editor" dialog dims everything in the editor expect popups like menus and dialogs.

![snapshot menu](https://user-images.githubusercontent.com/372476/70368254-57543280-18e3-11ea-8be9-3875faf025dd.png)
![snapshot dock](https://user-images.githubusercontent.com/372476/70368257-5d4a1380-18e3-11ea-96dd-52aa23656e3a.png)
![snapshot dialog](https://user-images.githubusercontent.com/372476/70368260-60dd9a80-18e3-11ea-9522-6a68db3f0092.png)

It looks strange for other popups to stay lit, especially for menus. It may be better to hide the menus when new popups appear. Menu are supposed to be temporary, aren't they?

**Steps to reproduce:**
1. In the editor, click to open any menu (say "Project")
2. Click the exit button of the window
3. The "Exit the editor?" dialog appears: the menu popup is not hidden or dimmed

**Minimal reproduction project:** Any project

**Comment by YeldhamDev** [comment]
The dimming works by changing the editor's root control's `modulate` to be darker, but modals aren't affected by the `modulate` of its parent, so for this to be "fixed", the way dimming works would need to be changed.

**Comment by capnm** [comment]
> so for this to be "fixed", the way dimming works would need to be changed.

Or as I mentioned elsewhere, I would prefer to remove the dimming from the editor ;-)

**Comment by Calinou** [comment]
Note that dimming was disabled in the `master` branch, even when using single window mode. Its code is still present internally, but I think it'll be removed as it no longer serves a purpose.

**Comment by pwnorbitals** [comment]
In this case, I suggest we can close this issue

**Comment by Calinou** [comment]
Closing per @pwnorbitals' comment (since this isn't a critical issue).
