### ISSUE TITLE
render_priority is not working properly

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#34177]
**Godot version:**
3.2 beta 3

**OS/device including version:**
Linux Manjaro

**Issue description:**
If you use the transparent flag or the no_depth flag in material the render priority seam to be ignored. You can see it by setting some material on next_pass.

**Steps to reproduce:**
Create a mesh instance with new material, add new next_pass and in that material set unshaded and no_depth. Set the render priority of the first material to 1, nothing change. Changing the depth_draw_mode has also no effect.

**Comment by KoBeWi** [comment]
See #35247 and #15873
