### ISSUE TITLE
2D Shadows don't work in HTML5 with GLES2

### ISSUE THREAD

**Issue by f000x** [godotengine/godot#34176]
**Godot version:** 3.1.2

**OS/device including version:** Windows 10

**Issue description:** 2D lighting shadows aren't working when exported to HTML5 with the GLES2 renderer, but the GLES2 renderer works fine with shadows when it is not in HTML5. I'm using Chrome.

**Steps to reproduce:** Have a project with Light2Ds that have shadows enabled. Export the project to HTML5 with the GLES2 renderer. The shadows won't work.

**Minimal reproduction project:** With the 2D Lighting example project on Godot, just set it to GLES2. It will work when ran directly in Godot (or exported to .exe), but shadows won't work when it is exported to HTML5.

The logs in developer console are also displaying this error over and over again, very likely related with the issue.
![chrome_2019-12-07_01-39-53](https://user-images.githubusercontent.com/12120644/70370312-ce61da80-1893-11ea-9ab4-5b81a5d3d919.png)

**Comment by akien-mga** [comment]
Does it work with 3.2 beta 3?

**Comment by f000x** [comment]
Oh yes, the shadows work in 3.2 beta. Thank you.
