### ISSUE TITLE
vulkan - 4.0 dev - non-debug targets do not render - blank black screen

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#34174]
**Godot version:** 4.0 vulkan branch

**OS/device including version:** linux (arch/manjaro) and windows

**Issue description:** supplying target=release_debug or target=release to scons builds exe's that just load a black blank screen. Game still appears to be running just there is no rendering.

**Steps to reproduce:** add target=release_debug or target=release to scons build command.

**Comment by RaTcHeT302** [comment]
i'm not sure what i'm doing differently, but i tried release_debug and this is what i get
![](https://i.imgur.com/9LPWwv5.png)

i don't know how to test the "release" parameter as i don't know where to download export templates for the vulkan release
![](https://i.imgur.com/Dpudsc7.png)

**Comment by Calinou** [comment]
> i don't know how to test the "release" parameter as i don't know where to download export templates for the vulkan release

There are no pre-built binaries for the `vulkan` branch yet, so you have to compile them from source. Also, the `vulkan` branch is currently missing support for some platforms (namely Android, iOS, HTML5 and UWP).

**Comment by supagu** [comment]
This appears to be working now that Vulkan has moved to master
