### ISSUE TITLE
"Center Selection" in 2D editor introduces graphic bias

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34186]
Godot 3.2 beta2

When you use `Center Selection` in the 2D editor, it correctly moves the view to that node, however it introduces a graphic bias.

Before centering:
![image](https://user-images.githubusercontent.com/1311555/70379641-0bc37800-1927-11ea-8ee6-184ce9670cd6.png)

After centering:
![image](https://user-images.githubusercontent.com/1311555/70379645-167e0d00-1927-11ea-9520-995607c58762.png)

See the text is now blurry.
This happens even when centering on a Node2D at origin.
Clicking the `100%` zoom control brings visuals back to normal.

Note: it may depend on the resolution of your editor.

**Comment by pycbouh** [comment]
Note that this is happening in 3.1 as well.

**Comment by Calinou** [comment]
I wonder if this is due to coordinates not being rounded somehow, or the zoom level being *almost* 100% but not exactly 100%.

**Comment by MissKraya** [comment]
@Calinou was right, I made sure that the numbers got rounded and it seems to have fixed the issue.

Interesting that moving arounf the viewport didnt fix it and you had to reset the zoom to fix it, I assume all movement is being done using ints but no checking of the actual value was being done so the offset was kept.
