### ISSUE TITLE
MSAA in viewport not working in 2d in 3d 

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot#34183]
**Godot version:** v3.2.1.stable.offical

**OS/device including version:** Solus ( Linux ) 

**Graphic Device:** Intel HD 620

**Issue description:** I am working with 2d in 3d and I have set msaa to 2x in the project setting and also for the viewport, which used as a texture for the cube. Cube's edges are anti-aliased perfectly but graphics inside viewport aren't anti-aliasing. So I can say that it might not be a hardware problem. 

![s](https://user-images.githubusercontent.com/29702428/70376211-8347d600-192c-11ea-85c7-bd30522dab46.gif)

**Minimal reproduction project:** 
[2d in 3d (copy).zip](https://github.com/godotengine/godot/files/3935163/2d.in.3d.copy.zip)

**Comment by Calinou** [comment]
2D rendering doesn't make use of MSAA yet, this is a known issue.

**Comment by Janglee123** [comment]
is there anything I can do ? ~~my game needs it badly~~

**Comment by Calinou** [comment]
@Janglee123 On a second look, it appears your issue isn't related to the lack of MSAA in 2D, but rather than MSAA doesn't affect the "insides" of a texture. You can solve this by enabling filtering on the ViewportTexture, but this will make it blurrier. This limitation is inherent to MSAA; screen-space algorithms such as FXAA or SMAA do not have this limitation.

**Comment by Janglee123** [comment]
@Calinou I can't find how to apply filtering on the ViewportTexture. Could you please show me?!

**Comment by Calinou** [comment]
@Janglee123 Edit the ViewportTexture by clicking on it, then check the **Filter** flag:

![image](https://user-images.githubusercontent.com/180032/70394012-cec3b800-19f0-11ea-9956-f92949870d71.png)

Then save the scene and run the project.

**Comment by Janglee123** [comment]
Thanks @Calinou, it works like a charm.
