### ISSUE TITLE
Debugger dock keep old stack trace from breakpoint when running new instance without breakpoint

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#34198]
**Godot version:**
3.2 beta3
**OS/device including version:**
win7-64
**Issue description:**
I seeing the stack trace in debug dock 

**Steps to reproduce:**
I set a breakpoint ,then  in debug dock I see the stack trace.
Then if I run the game I can still se the previous stack trace.
**Minimal reproduction project:**
none

**Comment by lupoDharkael** [comment]
The description was a bit confusing for me but now I understand.
Here some reproduction steps:
- set a breakpoint in an script.
- run in debug mode until you reach the breakpoint. It generates stack trace in debug dock.
- remove breakpoint.
- run it again.

The project runs showing the previous stack trace as (without breakpoints) it didn't need to generate a new one. The question here is, do we want to clear the stack trace on every execution? I guess it could be considered intuitive clearing the stack trace on every run so the user doesn't gets the feel of having a trace not related to the actual execution. But I don't think it hurts that much leaving the last generated stack trace in the debug dock.

**Comment by git2013vb** [comment]
"But I don't think it hurts that much leaving the last generated stack trace in the debug dock even if it is not related to the actual execution."

Is is a quality code that someone want to delivery.  How we will know if what we left here it will be not the culprit for another nasty bug somewhere else?

**Comment by akien-mga** [comment]
I can confirm that it behaves as described and IMO it should be clear when running a new instance.

It's already fixed in 4.0, but not in 3.x.

**Comment by akien-mga** [comment]
Fixed by #66654.
