### ISSUE TITLE
Class initializers are broken

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#34196]
**Godot version:**
8eb813a

**Issue description:**
Class initializers are not working how they are supposed to (or I just don't understand them).

**Steps to reproduce:**
```gdscript
class State:
	var entity
	var message
	func _init(e, m):
		entity = e
		message = m

class Idle extends State:
	var gun
	func _init(g).(e, m):
		gun = g

func _ready():
	# error: expected one argument
	Idle.new(2, 3, 1)
```

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/3936074/test.zip)

[Here is the documentation for this feature.](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#class-constructor)

**Comment by allkhor** [comment]
Maybe this works:
```gdscript
class State:
	var entity
	var message
	func _init(e, m):
		entity = e
		message = m

class Idle extends State:
	var gun
	func _init(g, e, m).(e, m):
		gun = g

func _ready():
	# error: expected one argument
	Idle.new(2, 3, 1)
```

**Comment by KoBeWi** [comment]
The syntax is somewhat confusing, but this works as intended.
```
func _init(g).(e, m):
		gun = g
```
This method takes only one argument, g. `(e, m)` is not argument declaration, but constructor call. You could do e.g.
```
func _init(g).(1, "Mmm"):
		gun = g
```
