### ISSUE TITLE
Shift key still considered pressed after open link in browser

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34191]
**Godot version:** v3.1.2.stable.offical

**OS/device including version:** macOS Catalina 10.15.1 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**
In the "Download Templates" dialog, you can Shift + Click to open the link in browser.

<img width="920" alt="dialog" src="https://user-images.githubusercontent.com/372476/70383666-766ac700-19ac-11ea-8ea3-0434c10f60e7.png">

If I shift click the link and then get back to Godot, clicking the link again without the shift key pressed will still open the link in the browser.

Godot thinks that the shift key is still pressed even if I close the Export Template Manager dialogs and open them again.

I think it's because that the shift key is pressed in Godot and unpressed in the browser. So that godot never get the unpressed event. When I go back to Godot from the browser, press the shift key once indeed reset the shift key state, and then the click works as normal.

**Steps to reproduce:**
1. Open any project
2. Click menu: Editor -> Manage Export Templates
3. Click the Download button to open the "Download Templates" dialog
4. Shift click the link, to open it in the browser. DON'T release the shift key untill you are in the browser.
5. Switch back to Godot, click the link again without the shift key pressed
6. The browser still opens
7. Switch back to Godot, close the "Download Templates" and "Export Template Manager" dialogs, and open the dialogs again
8. Clicking the link without shift key still opens the browser
9. Switch back to Godot, press the shift key once, and click the link without shift key pressed
10. The download starts as normal

**Comment by Calinou** [comment]
Related to #33928.
