### ISSUE TITLE
Script list dock inconsistent list

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#34199]
**Godot version:**
3.2 beta3
**OS/device including version:**
win7-64
**Issue description:**
script list in dock are not "update" correctly
**Steps to reproduce:**
open few scripts, change scene and script position in folders then open again script editor. 
**Minimal reproduction project:**
none

**Comment by Xrayez** [comment]
I don't quite understand the issue. Is this somehow related to #27635? Or is it sorting issue?

**Comment by git2013vb** [comment]
I'm not sure, However, I switched to linux so I cant check it any-more. Also its a old version,  Ill close this issue. If it happen again Ill open a new issue.
