### ISSUE TITLE
max_axis() and min_axis() - intended behaviour?

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#34190]
**Godot version:**  v3.2.beta3

The help file says max_axis() returns the axis that is "largest". However it is currently returning the axis that is highest. ``Vector3(-100,7,3).max_axis()`` will return AXIS_Y, while I would personally describe AXIS_X as the "largest", I don't think I'm alone on this.

Vector3 typically deals with 3D space, so I think retrieving the real largest vector axis even if it's negative would be the much more popular use-case for the majority of people. Tell me if you agree or disagree.

I am aware ``.abs().max_axis()`` can be used as a workaround.

If this is not a bug then the help file could be clarified.

**Comment by aaronfranke** [comment]
This is intended behavior, and should not be changed.

Comparing by "largest" as you put it would require finding the absolute value of everything. This would add complexity which for most users would only end up producing the wrong output.

However, you're right that the documentation could be slightly clearer, so I added this to #34005.

**Comment by rainlizard** [comment]
Thanks for the clarification aaronfranke.
