### ISSUE TITLE
Using up and down arrows in an ItemList makes it scroll in strange ways

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34204]
Godot 3.2 beta3

With an ItemList like this one:
![image](https://user-images.githubusercontent.com/1311555/70392719-e85a0500-19da-11ea-81be-86408a264940.png)

If I use up or down arrow, it ends up in this state:
![image](https://user-images.githubusercontent.com/1311555/70392725-f4de5d80-19da-11ea-898d-7ff34d9f82dd.png)

There is no reason for such scroll to happen here.

Project:
[ItemList.zip](https://github.com/godotengine/godot/files/3936578/ItemList.zip)

**Comment by allkhor** [comment]
Reproduced on Linux Godot 3.2 beta3, not reproduced on Godot 3.2-beta2.
