### ISSUE TITLE
PRIMITIVE_LINE_LOOP has distance "vanishing" issue in HTML5 export only (in 3.2beta3 only, ok in 3.1.2)

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot#34211]
**Godot version:**
3.2-beta 3 (official) **HTML5 export only**, GLES2

**OS/device including version:**
Chrome, Firefox, MSEdge (Exported from Windows 10)

**Issue description:**
PRIMITIVE_LINE_LOOP is "vanishing" at some distance [EDIT: at << camera.far; see comments]. Note that the icons below are QuadMeshes and some are much further away than the invisible part of the orbits. This problem occurs when viewed with Chrome, Firefox or MSEdge. The problem does **not** happen in a Godot 3.2beta3 Windows export nor in Godot 3.1.2 HTML5 export.
![I Voyager Web 32beta](https://user-images.githubusercontent.com/41218520/70399829-3ed43d00-19f5-11ea-9a52-36cbbb2f1d4f.jpg)

Below is the proper appearance. This happens to be an HTML5 export from Godot 3.1.2 using the same browser as above. This is what I see with any Godot version tested (3.1.1, 3.1.2, 3.2beta3) in an editor run or Windows export.
![I Voyager Web 312](https://user-images.githubusercontent.com/41218520/70399834-48f63b80-19f5-11ea-90a6-781ebcbb222e.jpg)

**Steps to reproduce:**
In any project that displays a Mesh.PRIMITIVE_LINE_LOOP (and you can move closer/further), export to HTML5 using 3.2beta. Then move closer and further away. Compare to 3.1.2 HTML5 export.

**Minimal reproduction project:**
This is not exactly a _minimal_ project, but you can download "Planetarium" under Godot Projects on the [I, Voyager Download page](https://ivoyager.dev/download/). Click "Orbits" in the panel on the lower left. Sorry, this will take a while to download & import due to image assets. Please let me know if a smaller project is needed for testing.

**Comment by charliewhitfield** [comment]
Here are some results of troubleshooting:

1. The lines **don't** disappear when I deleted my Panorama Sky. (It is as if the lines are disappearing "behind" the sky image.)
2. The same thing happens in a non-HTML5 export, but at >100x further distance.
3. So far, I haven't been able to solve by adjusting Camera.far.

In HTML5 export, the lines disappear at ~8e8 km, which happens to be 0.88 Godot length units.
In non-HTML5 export, the lines disappear at ~1e11 km, which happens to be about 100 Godot length units.

**Comment by Calinou** [comment]
@charliewhitfield I wonder if this is due to the depth buffer being forced to 16-bit in the HTML5 export (due to the WebGL driver). Try increasing `Camera.near` while leaving `Camera.far` untouched.

**Comment by charliewhitfield** [comment]
@Calinou, does that explanation work, given that it is a difference between Godot versions (not common to HTML5 exports from different versions)?

OK, more information, and more near/far tweaking...
In a solar system simulator it is necessary to change near and far dynamically based on current camera translation. Before, I was only adjusting near (because that's where I had problems) and leaving far at a fixed high value. I've re-written code to adjust both near and far dynamically.

Here's the relevant dynamic camera code I'm now using:
`
const NEAR_DIST_MULTIPLIER := 4e-3
const FAR_DIST_MULTIPLIER := 4e7

func _process(delta):
	var dist := translation.length()
	near = dist * NEAR_DIST_MULTIPLIER
	far = dist * FAR_DIST_MULTIPLIER
`

Result: it fixed the problem in the opening post (I can now move out as far as I want). However, it is still the case that HTML5 export from 3.2beta is _much_ _much_ more restrictive in visible range than HTML5 export from 3.1.2. The test case below examines this quantitatively.

**Test case:** The Camera is child of Enceladas (a small moon of Saturn). As I move closer to Enceladas, the orbital paths of Mercury & Venus will eventually disappear (as near & far are both lowered). These inner planet orbits are 1.5e9 km away (=**1.5 Godot units**; the scale is 1e9 km/Godot unit).
In **3.1.2 HTML5 export (exactly same as non-export)**: I can zoom in to 8.5e3 km (=8.5e-6 Godot units) from Enceladas before inner planet orbits disappear. By code, near and far are now set at 3.4e-8 and **340**, respectively.
In **3.2-beta3 HTML5 export**: I can zoom in to ~3.0e6 km (=3.0e-3 Godot units) before inner planet orbits disappear. By code, near and far are now set at 1.2e-5 and **1.2e5**.

Result: Well, it appears that PRIMITIVE_LINE_LOOP has always disappeared at way less that the Camera.far setting. However, 3.2-beta3 has gotten worse by 7 orders of magnitude.

**Comment by Zireael07** [comment]
Nitpick: the moon is Encelad**u**s (I happen to be a complete space fan xD)

**Comment by charliewhitfield** [comment]
@Zireael07, ouch! Will fix. My spell checker kept insisting on Enchiladas.

**Comment by clayjohn** [comment]
I think I know what the issue is. I will try to reproduce tonight. 

@charliewhitfield if I can't reproduce, can I send you code to try building it yourself?

**Comment by charliewhitfield** [comment]
@clayjohn, I've haven't complied Godot yet. Been meaning to, so I'll give it a try. But it might take me a while.
