### ISSUE TITLE
2D Physics Collision is 'Squishy'

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot#34215]
**Godot version:**
3.1.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
When two a `RigidBody2D` collides with a `StaticBody2D`, they 'squish' into each other and then the `RigidBody2D` slowly returns to the edge of the collision over a few frames. This makes the collision not feel quite so 'rigid' but instead like the `StaticBody2D` is squishy and allows other bodies to enter it temporarily. I have not checked to see if this behavior presents in 3D Nodes as well.

![collision](https://user-images.githubusercontent.com/911508/70408223-35020800-19fc-11ea-9408-33b0fb246c77.gif)

**Steps to reproduce:**
Create a 2D scene with a `RigidBody2D` and a `StaticBody2D`. Have the `RigidBody2D` collide into the other body with some velocity. You'll observe the `RigidBody2D` enter the `StaticBody2D`.

**Minimal reproduction project:**
Zipped Project, open at run the scene.
[Bouncy.zip](https://github.com/godotengine/godot/files/3937910/Bouncy.zip)

**Comment by gururise** [comment]
If you enable continuous collision detection (CCD), then the bodies should not overlap; however, CCD for 2D is currently not working, see issue #9071

**Comment by ZingBlue** [comment]
This almost breaks my entire game at times. I have no idea how to fix it.

**Comment by Exxion** [comment]
I believe setting the custom solver bias of any collision shapes involved to 1 should fix this, though given that it doesn't default to that, doing so probably causes other problems elsewhere. At a guess, it probably causes instability with collisions involving multiple bodies.
