### ISSUE TITLE
[iOS] Crash on exit

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#34221]
**Godot version:** 3.2 [fa4f525216]

**OS/device including version:** iPhone

**Issue description:**
Some times crashed on exit with error **malloc_error_brake**
**"core/string_name.cpp:107:unref()"**

**Steps to reproduce:**
Just close the app with swipe up

**Minimal reproduction project:**
I have a patch that fixing it. But need a review. Maybe problem somewhere dipper.

This is a screenshot from XCode
https://mega.nz/#!kwoFFKYJ!VISZj_TKrAWIb3U2_AD5YCP8Bg6j41U_NvmoxgmKJiU

Patch:
https://mega.nz/#!Is502QpL!xy-vbYR5mjd8-YkuWGZSvzZ9KJD7vhZ10e2odmggUJU

**Comment by samgreen** [comment]
If I'm not mistaken, force closing the app like you described with a debugger attached to Xcode will trigger a `SIGABRT`. If that is indeed the scenario that's happening here, the later `memdelete` calls will never be executed as exception handlers are generally _non re-entrant_.

I don't think there's a bug here, but I'd be interested in viewing the crash report to confirm via the stack trace that the other threads aren't doing anything funky.

**Comment by ealataur** [comment]
@samgreen 
I started to research it because my coworkers had the same bug on different devices without debugger. And after this patch their reports about crashes is gone.

**Comment by Tobi-La** [comment]
Could someone merge this? I also have a lot of reports of the app crashing when closed

**Comment by akien-mga** [comment]
A Pull Request would be more convenient than a patch file on Mega for peer review and possibly merging.

**Comment by Tobi-La** [comment]
@ealataur Could you do a pull request?

**Comment by Tobi-La** [comment]
I tested the patch, but it didn't fix the issue for me. So this is still open and needs further investigation

**Comment by Valeryn4** [comment]
[Same problem](https://github.com/godotengine/godot/issues/34696). Error statistics spoil application statistics

**Comment by HEAVYPOLY** [comment]
Still getting crash on exit here.  Using Godot 3.2 Stable on iOS 13.3.1 iPad

**Comment by ealataur** [comment]
Hi all

I will supplement my report. 
I got a crash and catch repeatedly situation.

When I close the app with "swipe up" afte double click on home button - the app crashed every time. But if I click once on home button and the app goes to backgraound and after I swipe up the app then app close correctly

The problem in first argument in "print_err" function in OS module. When I swipe up the app, the app is in run mode and didn't go to background or pausing.. And I think iOS is freed some resources early than main loop closed.. 

I research apple dev documentation and get info that after applicationWillTerminate callback we have 5 seconds before closing app. But app still crashed.. Any thoughts?..

Screenshoot from xcode
[https://drive.google.com/file/d/1J-tfEFrqejiJz6wGezfuzMSbR5hI4mTh/view?usp=sharing](url)

Video of crashing
[https://drive.google.com/open?id=10dsmo2--x9QMEXvNBJtM_Rxket1HWIiF](url)

**Comment by jkb0o** [comment]
This also happens if assign script to engine meta and then close application:
```gdscript
var resource = preload("some_script.gd").new()
Engine.set_meta("cached_instance", resource)
```
