### ISSUE TITLE
AnimationPlayer is not being recognized as a return type by GDScript.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#34245]
**Godot version:**
c868baf65

**OS/device including version:**
Win10 64-bit

**Issue description:**
When returning an AnimationPlayer the static typing flags this as a mismatch of type, and it considers it only as far as a Node.  (Other types may be affected, haven't looked too far into it.)

![godot windows tools 64_0VxuinMs5R](https://user-images.githubusercontent.com/13004169/70543347-ee82e980-1b72-11ea-9947-c802771b5d16.png)

**Steps to reproduce:**

Using the following function signature and a get_node() or $ to retrieve an AnimationPlayer.

```
func get_anim_player() -> AnimationPlayer:
	return $anims
```

**Minimal reproduction project:**
[Return Type Issue.zip](https://github.com/godotengine/godot/files/3945656/Return.Type.Issue.zip)

**Comment by akien-mga** [comment]
The error is correct, `get_node()` or `$` returns `Node`, so it can't be used as is if the expected return type is `AnimationPlayer`. You should cast the result before returning it:
```
return $anims as Animation player
```

**Comment by avencherus** [comment]
Ah I see, thanks for the fast response.  I did end up using `as`, but was thinking that the returned Node had it's type resolved, or maybe it was intended to be understood when using static typing.

I will close this, unless there is something else to the issue.
