### ISSUE TITLE
Windows 10  ant release error

### ISSUE THREAD

**Issue by Abhicse079** [godotengine/godot#3424]
-code-gen:
[mergemanifest] Found Deleted Target File
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] Found 1 AIDL files.
     [aidl] Compiling 1 AIDL files.
     [aidl] aidl: can't open preprocessed file: C:\godot\platform\android\java\${project.target.framework.aidl}

BUILD FAILED
C:\sdk\sdk\tools\ant\build.xml:649: The following error occurred while executing this line:
C:\sdk\sdk\tools\ant\build.xml:655: null returned: 1

**Comment by Hinsbart** [comment]
ant has been replaced by gradle.
Use `./gradlew build` instead

**Comment by volzhs** [comment]
http://www.godotengine.org/projects/godot-engine/wiki/Compiling_for_Android#Building-the-APK-for-Godot-2x

**Comment by reduz** [comment]
I would just deprecate the old ant stuff and remove it and replace it by
the new instructions. In the worst case make another page with the old info
with a warning that it's deprecated

**Comment by Abhicse079** [comment]
I am using commit  <a href="https://github.com/godotengine/godot/tree/a028840ea5cfc6ac4e80d99c4850ae3f10eeb353">2418c</a> because got an error 

drivers\libdrivers1.android.opt.debug.armv7.neon.a(pngrutil.android.opt.debug.armv7.neon.o):pngrutil.c:function png_read_filter_row: error: undefined reference to 'png_init_filter_functions_neon'
collect2.exe: error: ld returned 1 exit statu 
on latest commit
