### ISSUE TITLE
Cubic and linear interpolation in Animation have too similar icons

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34249]
**Godot version:**
3.2 beta3

**Issue description:**
Some of these tracks have cubic interpolation. Can you find them all? 😉
![image](https://user-images.githubusercontent.com/2223172/70571596-79c5a480-1b9e-11ea-9dd0-0ffb42d7da7d.png)

**Comment by Calinou** [comment]
The icons could have a slightly different color for easier differentiation.

**Comment by fire** [comment]
I wonder what things we can do to help color blind and low vision people use Godot Engine.

https://www.gdcvault.com/play/1025754/Solving-an-Invisible-Problem-Designing

**Comment by sketchyfun** [comment]
Gonna work on this soon, along with a few other animation player improvements I've been thinking about lately

**Comment by KoBeWi** [comment]
Seems sufficiently different.
![image](https://user-images.githubusercontent.com/2223172/195899876-734fdc3e-36aa-4242-a2cb-7e4d98a6c298.png)

**Comment by Calinou** [comment]
This was fixed by https://github.com/godotengine/godot/pull/54275.
