### ISSUE TITLE
Shapes without flat bottom can't jump on a rising moving platform

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#34242]
**Godot version:**
**OS/device including version:**
Tested on Win & mac, version 3.1 & 3.2 beta 3

**Issue description:**
Some shape can not jump if they do not have a flat bottom on a rising plateform, here is a [screenshot](https://i.ibb.co/F8cpM5p/shape.png)

EDIT:
_If I increase the safe margin (KinematicBody2D) from 0.08 to 0.5, the behaviour is ok. I don't know if it's an issue or the correct behaviour, I let the issue open just in case._

**Minimal reproduction project:**
[Here](https://mega.nz/#!IU90XASb!jW8On_P1E_RLWeM-SbSksbMpbE-3Ymun-Dqdz35yF4M)

**Comment by fabriceci** [comment]
I was thinking that increase the `safe margin`(KinematicBody2D) wis problematic shapes was a good workaround, but you need to increase (too much) this value relative to the platform speed, so it’s not good at all.

Unfortunately, I don't find any workaround.

**Comment by capnm** [comment]
I can confirm that this is broken in 3.2.3.stable and that #35945 with #42574 fixed for me the issue on the 3.2 branch.
