### ISSUE TITLE
Add option to hide/disable GraphEdit zoom controls

### ISSUE THREAD

**Issue by MissKraya** [godotengine/godot#34258]
Godot version: 3.2 (master revision: c868baf65)

Windows 10

Removing GraphEdit's zoom controls results in a Socket error: 10054 when resizing. This was not the case in Godot 3.1.

Call:
get_zoom_hbox().queue_free() 
in the _ready function of a GraphEdit script.

[Project.zip](https://github.com/godotengine/godot/files/3948141/Project.zip)

**Comment by akien-mga** [comment]
I don't think we can reasonably support the use case of freeing internal components of Controls. We'd have to add null checks everywhere to cater for the possibility that someone may have decided to remove some components, but the node's logic would probably end up broken even if we can prevent crashes.

If you want to hide the zoom controls, an option should be added for that.

**Comment by MissKraya** [comment]
> If you want to hide the zoom controls, an option should be added for that.

get_zoom_hbox().visible = false

is a valid workaround it seems as it prevents the use clicking it, I was just kinda blindsided by it due to it working in 3.1 but it does make sense as to why it's not supported.

To be honest this whole thing was a workout for a completely seperate bug I should report when I get time that makes it impossible to connect nodes or pull wires off of pins in GraphEdit whenever the user is zoomed out even a tiny amount, the whole thing relies on zoom level 1.

**Comment by MissKraya** [comment]
That being said I'm happy for this specific issue to be closed due to a valid workaround unless you think we'd be better actually having a built in hide_zoom_controls() function exposed to GDScript.

If we're in there anyway I dont think that zoom_hbox is a very descriptive name for what it actually is and the only reason I found it was due to some helpful people on discord.

**Comment by akien-mga** [comment]
I'll repurpose it as a proposal to allow disabling those controls properly.

I'm not sure why this hbox is expose to the scripting API in the first place, but IMO it should not be, and instead there should be a boolean option to disable/hide it.

**Comment by MissKraya** [comment]
> I'm not sure why this hbox is expose to the scripting API in the first place, but IMO it should not be, and instead there should be a boolean option to disable/hide it.

If that worries you you should have seen my solution to this before I knew that function existed ;)

$"@@2/@@4".queue_free() was totally valid and seemed stable in 3.1, discord found this amusing but pointed me towards the get_zoom_hbox() function.

I might create a PR for exposing a proper way to do this if I get time soon.

**Comment by MissKraya** [comment]
I'm not sure I agree with removing the get_zoom_hbox function though, as people may want to reposition it, or add an extra button, or set certian buttons to be invisible. Maybe a line in the documentation for the function warning people not to remove the node?

**Comment by MissKraya** [comment]
This will be my first contribution to Godot so sorry if there is an outlined process for things like this but how likely is doing something like renaming get_zoom_hbox to get_controls_hbox going to get a PR denied?

**Comment by akien-mga** [comment]
> how likely is doing something like renaming get_zoom_hbox to get_controls_hbox going to get a PR denied?

That breaks compatibility for the API, so it would be set for the 4.0 milestone (which is expected to break compat). But since we're in release freeze for 3.2, and 4.0 is the next milestone, that's actually the right time to PR such changes.

**Comment by MissKraya** [comment]
Makes sense, thanks! I've left the existing function alone and added some additional documentation to it in addition to a new function to hide the controls.

**Comment by MissKraya** [comment]
Ahh I've actually misread your sentiments with regards to the API breakage, I'll make a seperate PR to get that function renamed for the 4.0 release.

**Comment by akien-mga** [comment]
As discussed on #34272, we chose to keep the flexibility of exposing the inner control  but warn about potential misuse, so this can be considered solved.
