### ISSUE TITLE
Regression UI container child size

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#34252]
**Godot version:**
3.2 beta 3
**OS/device including version:**
Linux Manjaro
**Issue description:**
The first time I show a hidden tab container it's content is not filling all the available space. If I hide and then show again it's content it's all well contained

Godot 3.1.2 stable
![regression UI](https://user-images.githubusercontent.com/16955149/70574810-42a6c180-1ba5-11ea-9b8e-abd0e4a39500.png)

Godot 3.2 beta 3
![regression UI _2](https://user-images.githubusercontent.com/16955149/70574823-4cc8c000-1ba5-11ea-84a4-1565edc65b39.png)

**Comment by Calinou** [comment]
I've seen this in the editor inspector's multiline text boxes (which use TextEdit under the hood). I think there's an issue about it, but I can't find it right now.

**Comment by akien-mga** [comment]
Is this still reproducible in 3.2 RC?
Can you provide a project that reproduces it?

**Comment by tom-jk** [comment]
Tried and failed to reproduce in 3.2.2.stable.

Test project I made (following only the description given in original comment): [34252.zip](https://github.com/godotengine/godot/files/4933178/34252.zip)

@grevius5 do you still have this issue? Can you reproduce it with this project? If not, could you supply one that does?

**Comment by grevius5** [comment]
I don't have the project at the moment and I'm a little busy to try with a new one. If I'll some spare time I'll check and let you know

**Comment by akien-mga** [comment]
I'll close for now as @tom-jk couldn't reproduce and we don't have a project that can exhibit the issue.
