### ISSUE TITLE
Playhead in inspector audio preview goes negative

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34268]
**Godot version:** v3.2.beta.custom_build.cd9d51328

**OS/device including version:** macOS Catalina 10.15.1 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

In the inspector audio preview:

* Current time goes negative
* When the current time is negative, the playhead goes out of the inspector

The blue vertical line on the left is the playhead:
<img width="522" alt="audio-playhead" src="https://user-images.githubusercontent.com/372476/70624864-2a45ae00-1c5c-11ea-8d23-5562a89f71eb.png">

**Steps to reproduce:**
* Double click a sound in FileSystem
* Play it in the inspector audio preview
    * So now the playhead is at the end (Showing 0.28 / 0.28s in my case)
* Change the "Loop Mode" to "Ping-Pong", and leave "Loop Begin" and "Loop End" zero
* Hit the Play button again
    * The playhead goes out of the inspector (Showing -0.28 / 0.28s)

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by timothyqiu** [comment]
No longer reproducible, I think this has been fixed by #46740.
