### ISSUE TITLE
Editor stuck panning when focus is lost

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34278]
**Godot version:**
3.2 beta3

**Issue description:**
This is similar to other focus-related issues, but probably not a duplicate.

**Steps to reproduce:**
1. Start panning in 2D editor (using middle mouse for example)
2. Alt + Tab out of the editor while still panning
3. Focus editor again, but don't click in the viewport
4. Heh

This happened to me when reimport fired while I was panning.

**Comment by capnm** [comment]
5. Huh, also works with all LMB 2D ops and even survives switching the 2D / 3D viewport, nice ;-)

**Comment by Calinou** [comment]
Would it be possible to send a mouse release event when losing the window focus? Is there any case where you would actually want the pressed event to be kept when the window loses focus?

**Comment by KoBeWi** [comment]
> Is there any case where you would actually want the pressed event to be kept when the window loses focus?

I never had one, so probably not. Might be related to #10949 actually.

**Comment by KoBeWi** [comment]
I just found another case of this issue. When this happens if you pan using Space, you will lose ability to select nodes, because your LMB will keep panning. You need to press Space again to fix this.

**Comment by greatmomo** [comment]
This doesn't seem to happen in the 4.0.dev build, but I did see it in the 3.3.2 stable release.

Another thing I noticed while trying this out, is that after I click back into the editor, I can't close it using the "x" at the top right anymore.

**Comment by KoBeWi** [comment]
I can still reproduce in 9ace46a7d

**Comment by greatmomo** [comment]
Interestingly enough, I wasn't able to reproduce it while Debugging, but I was able to reproduce it on a release build

**Comment by KoBeWi** [comment]
@greatmomo What is your OS? I'm on Windows and it happens in debug too.

**Comment by greatmomo** [comment]
I'm on Windows 10
