### ISSUE TITLE
Visual Shader does not allow layered texture uniforms

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#34276]
**Godot version:**
3.2 calinous latest, from 10.12.2019

**OS/device including version:**
windows

**Issue description:**
Visual Shaders Texture Uniform Node does not allow sampler2DArray or sampler3D and related inputs. And there is no way to circumvent this using the expression node.

@Chaosus ping cuz ifire told me to

**Steps to reproduce:**

Add a texture node. Set it to Texture2D. Note the lack of a Texture2DLayered option.
Add a texture uniform node. Feed it into the texture node.
Note that the exported uniform property in the material resource, only supports normal textures.

![image](https://user-images.githubusercontent.com/44248915/70641948-b2b55600-1c3e-11ea-9b87-60d35c90e384.png)

**Minimal reproduction project:**

**Comment by Chaosus** [comment]
> And there is no way to circumvent this using the expression node.

Did you try to use GlobalExpression and define the required uniforms in them? 

Sure, I can implement these types, probably not sooner than 3.2 release (due to feature freeze).  
sampler3D should probably be implemented as a separate node type.

**Comment by TheDuriel** [comment]
This is how one would use a Flipbook in a typical code based shader. Which is what i tried to do with visual shaders in 3.2. Might help clarify what this is about ;P

```shader_type canvas_item;

uniform sampler2DArray my_flipbook;

void fragment() {
    COLOR = texture(my_flipbook, vec3(UV, TIME)); 
}```

When defining a Uniform with this type, the Inspector will provide a different selection of Texture resources in the Uniform field of the Material Resource.

Since it does not do that for the current TextureUniform Node, you can't use those kinds of Resources. Even though the Texture node seems to support them.

**Comment by Chaosus** [comment]
Well, this construction actually works:

![image](https://user-images.githubusercontent.com/3036176/70691057-37e54d00-1cc9-11ea-8817-70870d2ec074.png)

Use it, until this issue will be fixed.
