### ISSUE TITLE
UV editor undesired scroll limit

### ISSUE THREAD

**Issue by JohnMeadow1** [godotengine/godot#34270]
**Godot version:**
Godot 3.2 beta5

**OS/device including version:**
WIN 10
**Issue description:**
When you open UV editor on Polygon2D there is a scroll limit that blocks you from viewing full a sprite. This limit changes when you place first point in the editor the texture.
Zooming out in editor is a work around, but it does not feel right. And working in higher resolution also mitigates somewhat. 

This might be related to similar limit in 2D scene editor scrolling. 

**Steps to reproduce:**
Just add Polygon2D to a scene with large enough texture.

![UV_editor_bug](https://user-images.githubusercontent.com/23294139/70627573-c1900e80-1c26-11ea-857e-db928c1f0c7a.gif)

**Comment by kozaluss** [comment]
I have the same problem. Ver. 3.2.2 stable. Really annoying. I have 4096x4096 textures used in polygons to make animations. Why can't the editor just stick to texture size?

**Comment by KibaGasteiz** [comment]
I'm affected by this too, using 3.3 on Arch Linux.

**Comment by KaikyuLotus** [comment]
I'm affected by this too, I'm using 3.3.2 on Windows.

**Comment by KoBeWi** [comment]
Fixed in 4.0
