### ISSUE TITLE
Using cut in first line of a script file does not remove the line

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#34289]
**Godot version:**
9abc0ad8a5cf400d848fd25a33bd562db08d1046

**Issue description:**
When using `Cut` in the first line of a script file (without any selection) the cut operation is executed, but an empty line remains.

**Steps to reproduce:**
1. Place cursor anywhere in the first line
2. Press `Ctrl + X` or use the context menu to execute `Cut`
3. See that the content of the line is cut, but the line still remains

**Comment by akien-mga** [comment]
Similar to #34212.
