### ISSUE TITLE
MSBuild Path Config for VS 2017 15.0

### ISSUE THREAD

**Issue by lunoctis** [godotengine/godot#34297]
`MsBuildFinder.cs` uses "vswhere.exe" to find MSBuild, but it only auto setuped above VS2017 15.2.
And if I use VS 32bit and Godot 64bit, it will fail, because it use "Program Files (x86)".
Why not give a setting item to config the path directly?

**Comment by lunoctis** [comment]
I downloaded an “vswhere.exe" manually, put it to "C:\Program Files\Microsoft Visual Studio\Installer\vswhere.exe", and it works.

Visual Studio 2017 15.0.0 x86 at "C:\Program Files (x86)\Microsoft Visual Studio\2017"
Godot_v3.1.2-stable_mono_win64

This did cause unnecessary trouble.

**Comment by neikeq** [comment]
I think vswhere is only supported starting with 15.2 and I don't think the effort required to support 15.0 would be worth it.
I find it weird VS 32bit would not put vswhere in "ProgramFiles(x86)", but if that's really the case we can fallback to "ProgramFiles" on 64-bit.

**Comment by lunoctis** [comment]
> I think vswhere is only supported starting with 15.2 and I don't think the effort required to support 15.0 would be worth it.
> I find it weird VS 32bit would not put vswhere in "ProgramFiles(x86)", but if that's really the case we can fallback to "ProgramFiles" on 64-bit.

My mistake that not know where the auto-installed "vswhere" would be put.
Indeed, this problem doesn't exist if VisualStudio is frequently updated. And the mono part supports C# 7.0 syntax， will not works in older environment. But since it need "msbuild" rather than "visualstudio", maybe this issue is optional.
