### ISSUE TITLE
Tiny icons in FileDialog on retina display

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34291]
**Godot version:** v3.2.beta.custom_build.cd9d51328

**OS/device including version:** macOS Catalina 10.15.1 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

Icons in some of the FileDialogs are small on retina display.

The project path dialog in Project Manager: (top normal display, bottom retina display)

![icon-sizes](https://user-images.githubusercontent.com/372476/70680164-3f5d2400-1cd2-11ea-8f89-7bb105674b79.png)

The find in files dialog:

<img width="1136" alt="script-search-find-in-files-folder" src="https://user-images.githubusercontent.com/372476/70680171-43894180-1cd2-11ea-9c16-70bd23c0e28e.png">

But most other dialogs (e.g. the Save Scene dialog) have a normal icon size.

**Steps to reproduce:**

1. Open Godot editor on a retina display
2. In the project manager:
    1. Click "New Project"
    2. Click "Browse" button, tool icons in the dialog is small
3. Open any project:
    1. Switch to the Script Editor
    2. Click "Search" menu, and choose "Find in Files"
    3. Click "..." button, tool icons in the dialog is small

**Comment by volzhs** [comment]
it also happens with **Export > Manage Export Templates > Install From File**.
