### ISSUE TITLE
Tilemap / Tileset suggestions

### ISSUE THREAD

**Issue by meniku** [godotengine/godot#343]
* Tilemap Usage: SHIFT Selection and META+D should be available as Icons, else nobody knows that this optin exists
* Tileset creation: Would be nice if it would be possible to import an Tilemap without having to creat every tile by hand
* Tilemap: Would be nice if it would arrange the tiles in that left bar like I arranged them during the creation of the tilemap - also with multiple columns

**Comment by blendi-93** [comment]
+

**Comment by jminix** [comment]
I also would like the ability to have multiple columns when working with a tile map as using over 250 tiles can be time consuming.

In terms of tile map creation and importing, I have employed gdscript to help me with that.

**Comment by akien-mga** [comment]
Closing as duplicate of #843, I'll add a comment there with the contents of OP.
