### ISSUE TITLE
New Vector convenience method - rand

### ISSUE THREAD

**Issue by Beechside** [godotengine/godot#34301]
I find myself needing random vectors for enemy movements and use something like this:

```
func new_direction() -> Vector2:
   var new_dir: = Vector2()
   new_dir.x = rand_range(-1, 1)
   new_dir.y = rand_range(-1, 1)
   return new_dir.normalized()
```

I wonder if this might be generalised for 2D and 3D and new convenience methods be created.  For certain type of games,  the resulting vector might be constrained to orthogonal movement so arguments might be considered for that and/or other constraints.

In the first instance, floats in the range (-1, -1) to  (1, 1) and orthogonal would prove useful.
I would not expect `randomize` to be part of the method, as is the case elsewhere.

**Comment by KoBeWi** [comment]
```
func new_direction() -> Vector2:
    return Vector2(-1 + randf() * 2, -1 + randf() * 2).normalized()
```

**Comment by Beechside** [comment]
Thanks @KoBeWi.  I'm aware of that but, if you look at the methods in vector2.cpp, more than 25 of them are single lines of code.  It's not the difficulty of writing but the convenience that I'm asking about.

As a Godot noob, I don't know what the criteria are for enhancing existing classes but this seems like a candidate, hence my enquiring...

**Comment by Calinou** [comment]
I'm not sure about this either, as none of the other engine types (Color, Transform) have built-in random methods. If we add random methods for Vector2/Vector3, people will likely start asking them to be added to every engine type out there, which will bloat the class reference.

**Comment by Zylann** [comment]
Unity has random methods like that, which are quite specific https://docs.unity3d.com/ScriptReference/Random-insideUnitCircle.html

**Comment by lupoDharkael** [comment]
@Calinou @Zylann Unreal Engine has methods to generate random vectors too: 
https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FMath/VRand/index.html
https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FRandomStream/GetUnitVector/index.html

**Comment by Chaosus** [comment]
Maybe adding these methods to RandomNumberGenerator make more sense?

**Comment by JohnMeadow1** [comment]
@Beechside
For 2D random unit vectors I'm using:
```
var angle = randf() * 2 * PI
var rand_direction_vector = Vector2( sin(angle), cos(angle) )
```

For 3D it is more complicated, as you need to calculate a point on the sphere, and using:
```
func new_direction() -> Vector3:
   var new_dir: = Vector3()
   new_dir.x = rand_range(-1, 1)
   new_dir.y = rand_range(-1, 1)
   new_dir.z = rand_range(-1, 1)
   return new_dir.normalized()
```
will mess up random distribution as, you will get more vectors pointing to the corners of a 2x2x2 cube. 

It would be nice to have something built-in e.g.:
```
var new_2d = Vector2.RAND
var new_3d = Vector3.RAND
```
for random unit vector.

Surely everyone will have different use case, but random unit vector would be quite useful, especially if the user is less math oriented.

**Comment by name-here** [comment]
Relevant math Stackexchange post to help with implementing the function: <https://math.stackexchange.com/questions/44689/how-to-find-a-random-axis-or-unit-vector-in-3d>

**Comment by Xrayez** [comment]
I've come up with a general-purpose solution for this in #43103.

See also godotengine/godot-proposals#1731 which may as well supersede this feature request.

**Comment by jitspoe** [comment]
Should this issue be closed in favor of the proposal https://github.com/godotengine/godot-proposals/issues/1731?

**Comment by AThousandShips** [comment]
Thank you for your proposal, consolidating in:
* https://github.com/godotengine/godot-proposals/issues/1731
