### ISSUE TITLE
Editor crash on sync scenes

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#3430]
I insert one scene into other, and when update the scene I expect that it appears when running. But it not show! And when I change tables in Editor to see the inserted node the editor crash.
I was doing a video when it occurs.

https://www.youtube.com/watch?v=BRRKzuGVTjw

**Comment by zoiba** [comment]
I confirm, the same happens to me

**Comment by reduz** [comment]
please make a small example scene that shows how to reproduce this

**Comment by reduz** [comment]
again, I can't reproduce it so please make a small scene where it happens so I can test

**Comment by marcosbitetti** [comment]
I not see this bug in latest releases

**Comment by akien-mga** [comment]
Great, closing then.
