### ISSUE TITLE
SCREEN_TEXTURE Doesn't Work on GLES3 Android

### ISSUE THREAD

**Issue by cybereality** [godotengine/godot#34318]
**Godot version:**
v3.1.2.stable.official and v3.2.beta3.official

**OS/device including version:**
Amazon Kindle Fire 7 (2019)
Google Pixel 2 XL (Android 10)

**Issue description:**
Trying to access SCREEN_TEXTURE in a custom post process shader is not working in GLES3 on Android. It works on the Ubuntu desktop and does also work in GLES2 on Android (though the color rendering is different) but on GLES3 on Android SCREEN_TEXTURE seems to be blank.

Expected results (GLES2 Android):
![negative](https://user-images.githubusercontent.com/3398643/70767080-badfc500-1d14-11ea-9e87-d0764dc06b11.png)

Observed Results (GLES3 Android):
![blank](https://user-images.githubusercontent.com/3398643/70767097-caf7a480-1d14-11ea-9038-de75f8ce3330.png)

**Steps to reproduce:**
Create a test scene (cube, camera, light, etc.)
Create a Mesh Instance Quad and set size to (2, 2).
Attach a shader material to the quad and use the following code:
~~~
shader_type spatial;
render_mode unshaded, skip_vertex_transform;

void vertex() {
	POSITION = vec4(VERTEX, 1.0);
}

void fragment() {
	ALBEDO.rgb = vec3(1.0, 1.0, 0.0);
	vec3 finalColor = texture(SCREEN_TEXTURE, SCREEN_UV).rgb;
	ALBEDO.rgb = ALBEDO.rgb - finalColor;
}
~~~
**Minimal reproduction project:**
[Screen.zip](https://github.com/godotengine/godot/files/3958840/Screen.zip)

**Comment by nathanwfranke** [comment]
Reproducible on my Google Pixel 3a
Works fine in GLES2 as stated

**Comment by nathanwfranke** [comment]
Related to #34316

**Comment by cybereality** [comment]
I discovered that my mobile project settings were set to "3D without effects". If I change to "3D" then the shader now works on Android. It's really slow, but working.

The setting is under Project -> Project Settings -> Rendering -> Quality -> Intended Uses -> Framebuffer Allocation.mobile. I set it to 3D (it was on 3D without effects before).

**Comment by cybereality** [comment]
Sorry, I closed it by mistake. I agree that maybe this should be noted in the docs. Thanks.
