### ISSUE TITLE
Warnings crash when the number of warnings is greater than 100

### ISSUE THREAD

**Issue by Jiaming00** [godotengine/godot#34324]
**Godot version:**
godot 3.2 beta 2

**OS/device including version:**
windows10

**Issue description:**
When the number of warnings is greater than 100, each frame outputs "Too many warnings! Ignoring warnings for up to 1 second."

**Steps to reproduce:**
101 warnings need to be made, but I still want to ask if this is really a bug or was meant to warn the developer

**Minimal reproduction project:**

**Comment by qarmin** [comment]
This isn't a bug, it prevents from too big error spam in Output tab.
It can be configured in Project -> Project Settings -> Network -> Limits -> Debugger Stdout
