### ISSUE TITLE
No error is raised when a nonexistent variable is used inside an array

### ISSUE THREAD

**Issue by katoneko** [godotengine/godot#34337]
**Godot version:**
3.1.2

**OS/device including version:**
Windows 10

**Issue description:**
Placing a variable that wasn't declared before inside an array doesn't raise any errors. It should, though, because the variable is not declared and the compilation will, therefore, fail.

The editor doesn't see any error here.
![image](https://user-images.githubusercontent.com/48890128/70830795-dc26db00-1e12-11ea-8c6e-f59352f3219e.png)

The compilation, obviously, fails.
![image](https://user-images.githubusercontent.com/48890128/70830837-f2cd3200-1e12-11ea-8abe-e8d34dcbe958.png)

Also, trying to preload a script with that error fails, citing cyclic or compilation error as the reason. So, the editor seems to acknowledge the error's there but doesn't report it?

**Steps to reproduce:**
Declare an array and place a variable inside that wasn't defined before. The editor shouldn't raise any errors. Try to run the game, the compilation should fail.

**Minimal reproduction project:**
N/A, easy to reproduce.

**Comment by ThakeeNathees** [comment]
this issue has been fixed and should be closed

**Comment by akien-mga** [comment]
It seems fixed in the master and 3.2 branches indeed, though not by the still unmerged #34342.
It's still reproducible in 3.1.2, but given that 3.2 is released and this is a minor annoyance, I don't plan to fix it there (unless someone finds what fixed it and it's a *very* safe change to cherry-pick).
