### ISSUE TITLE
Tileset Zoom is not enough for pixel art

### ISSUE THREAD

**Issue by securas** [godotengine/godot#34346]
**Godot version:**
3.2 beta 3

Perhaps its just my very poor eyesight. But the maximum zoom of the tileset editor is not sufficient for detailed pixel art games.

I realize its feature freeze but it would certainly help this impaired vision dev to increase the maximum zoom limit.

**Comment by JohnMeadow1** [comment]
+1 on that. 
UV editor has similar limit of x4 zoom, and it is not enough for comfortable work with pIxelart.
My eyesight is fine, but I would prefer to be able to zoom at least twice the current limit.

**Comment by MissKraya** [comment]
I'm not sure I understand, the maximum zoom level on the tileset editor is huge. This is the max on my 1440p monitor.

![image](https://user-images.githubusercontent.com/20043270/70849861-fc3eb480-1e7b-11ea-88c1-4a10314f4c2e.png)
