### ISSUE TITLE
Regression with missing `Skeleton.bones_in_world_transform`

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#34347]
**Godot version:**
`master` / 3740ec25f7dd

**OS/device including version:**
Manjaro Linux/KDE 18.1.4

**Issue description:**
`Skeleton` class used to provide `bones_in_world_transform` property which was required to make a model imported with Godot(.escn) Exporter to work properly (see #26997).

But upon updating Godot to the latest revision, I found that the property no longer exists so I'm having the same problem as described in #26997.

**Comment by mysticfall** [comment]
By the way, the commit which removed the property in question seems to be d81ddaf33ecddab.

**Comment by akien-mga** [comment]
Related to #32766 (caused by same commit, likely due to the removal of this feature).

**Comment by reduz** [comment]
This requires modifying the .escn exporter, unfortunately. The change in how skeletons were processed was required to significantly improve compatibility with all sorts of models.

**Comment by mysticfall** [comment]
Thanks for the info. I opened a separate issue in godotengine/godot-blender-exporter to request necessary changes to the .escn exporter.

**Comment by akien-mga** [comment]
Closed as moved to godotengine/godot-blender-exporter#302.
