### ISSUE TITLE
Wierd issue with stylebox

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#34354]
**Godot version:**
At first i though it was me messing with the source code of stylebox (#34320) but then i tried with official commit 3a9284b56 and the issue seems to persist.
**OS/device including version:**
Linux mint (first day! After windows crashing 10 times in 2 days.) 

**Issue description:**
So if you set `Corner Detail` to a high enough value (i set it to 100, there will also be a project attached) **AND** have `borders` enabled **AND** have `Shadow` enabled **AND** have anti aliasing enabled, the results are... well, with GLES2 i get the following:
![image](https://user-images.githubusercontent.com/1850856/70853779-7d696c00-1ebb-11ea-9e00-c33aee42b263.png)
While if i disable the shadow **OR** the border **OR** anti aliasing, it returns to normal:
![image](https://user-images.githubusercontent.com/1850856/70853798-b73a7280-1ebb-11ea-811b-b57e2d13a2aa.png)
GLES3 seems to be more intuitive and gives me a clue:
![image](https://user-images.githubusercontent.com/1850856/70853869-80189100-1ebc-11ea-8788-d0216117b77e.png)
With GLES3 the panel is never drawn.
I did make an attempt (for the first time) to try to debug this with Qt-creator but with no veil.

**Steps to reproduce:**
So to reproduce this you need to: Set the `Corner Detail` to a high value **AND** have `Shadow` enalbed **AND** have `anti aliasing` enabled **AND** have `borders` enabled (or download the attached project!).
**Minimal reproduction project:**
[InnerShadowTest.zip](https://github.com/godotengine/godot/files/3964284/InnerShadowTest.zip)

**Comment by Calinou** [comment]
Try increasing **Rendering > Limits > Canvas Polygon Buffer Size Kb** in the Project Settings.

That said, we should probably limit the corner radius to a lower value…

**Comment by YeldhamDev** [comment]
> Linux mint (first day! After windows crashing 10 times in 2 days.)

Welcome to GNU/Linux, my friend! :smile:
