### ISSUE TITLE
Incomplete abs() docs and editor hints

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34351]
**Godot version:** v3.2.beta.custom_build.3a9284b56

**OS/device including version:** macOS Catalina 10.15.1 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

The argument of `abs()` can be either an `int` or `float`, and the function returns a value of the corresponding type.

```gdscript
var i = abs(1)
var f = abs(1.0)
assert(typeof(i) == TYPE_INT)
assert(typeof(f) == TYPE_REAL)
```

Although this behavior is partially mentioned in the function description, it only shows the `float` version of function signature in the documentation and editor hints:

![Screenshot of abs function in docs and editor hints](https://user-images.githubusercontent.com/372476/70848856-2f9c3600-1eb2-11ea-85d7-9d423cf3167d.png)

So there are actually two `abs` functions, but currently it seems complicated to change the documentation. Because the two versions are made different by code under the same `GDScriptFunctions::Function::MATH_ABS` enum, and the signature in documentation is generated per `GDScriptFunctions::Function` enum.

p.s. The same goes for `sign()`, `min()`, `max()`, and `clamp()` too.

**Comment by lakshay-angrish** [comment]
Am I just required to modify the documentation for the said functions?

**Comment by timothyqiu** [comment]
Ideally, there should be `float abs(s: float)` and `int abs(s: int)`, both in the documentation and editor hints.

I didn't look very deep into the source code. But from what I can tell, the documentation XML structures are generated/updated by code, probably the same code that provides the editor hint content. It seems that we can't simply add one new function definition to the XML and call it a day. (Maybe I overthinked it.)

To C++, there is only one `abs` function, identified by the `MATH_ABS` enum. The logically different signatures are implemented as hard coded type checks:
https://github.com/godotengine/godot/blob/7d34d1a85f95edd1b29b8eb24cda49b355db2c3d/modules/gdscript/gdscript_functions.cpp#L270-L286

This seems to be a place that defines the signature for `abs` (I'm not sure). And it's one signature per enum.
https://github.com/godotengine/godot/blob/7d34d1a85f95edd1b29b8eb24cda49b355db2c3d/modules/gdscript/gdscript_functions.cpp#L1626-L1629

So I think, to make the `abs` signature in the documenttion two, the code above should be changed first, which requires a better understanding of the code around.

**Comment by lakshay-angrish** [comment]
I tried creating two different signatures: one as MATH_ABS_INT and one as MATH_ABS_FLOAT. 
```
	        case MATH_ABS_INT: {
			MethodInfo mi("abs", PropertyInfo(Variant::INT, "s"));
			mi.return_val.type = Variant::INT;
			return mi;
		} break;
                case MATH_ABS_FLOAT: {
			MethodInfo mi("abs", PropertyInfo(Variant::REAL, "s"));
			mi.return_val.type = Variant::REAL;
			return mi;
		} break;
```
This way, the docs are generated just fine, but when you look up abs() int the editor, it always points to the one with the float args. This probably happens because both the functions have the same name: "abs". So, should I define two new functions with different names, each for float and int args?
