### ISSUE TITLE
_init issue for OOP

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#34365]
**Godot version:**
3.2
**OS/device including version:**
ubuntu 18
**Issue description:**
` class FSM:
var manager = null
func _init(man):
manager = man

class FSM_Test extends FSM:
 pass

func _on_ready():
 var manager = "test"
   var state = FSM_Test.new(manager) `
If you pass the manager arg the following error occurs:
Invalid call to function new Expected 0 args
if you does not pass the arg:
Too few arguments for _init() expected at least 1

**Comment by KoBeWi** [comment]
I can't seem to reproduce it. If you don't provide a constructor for FSM_Test, it will inherit one. The code works perfectly for me (except that it complains about `pass` after `class`).

If you write your own constructor in the inheriting class, you pass the arguments like this: https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#class-constructor

**Comment by nonunknown** [comment]
Try to reproduce with this one.

Utils.gd - AutoLoad
```
class FSM_Manager:
	var current:FSM = null
	var statefunc _on_ready():
	manager = Utils.FSM_Manager.new()
	manager.states[ST_UNSELECTED] = St_unselected.new()s = {}

class FSM:
	var manager = null
	func _init(m):
		manager = m

	func _on_enter():
		pass
```

Selectable.gd

```
func _on_ready():
	manager = Utils.FSM_Manager.new()
	manager.states[ST_UNSELECTED] = St_unselected.new(manager)
```

**Comment by KoBeWi** [comment]
Ok, this is weird. I don't see any significant difference from previous code, but this one doesn't work.

**Comment by nonunknown** [comment]
thanks for testing dude, I think its because the Autoload (singleton) but its only a tought

**Comment by eon-s** [comment]
Utils is not a class (autoloaded elements are node instances) and you refer to the internal classes defined in the script (which should be loaded first and get a reference), if you name it with `class_name` it should work.

**Comment by nonunknown** [comment]
@eon-s I'll give a try, but if it is a node instance extending a node this code should work...

**Comment by eon-s** [comment]
No, it can't work because you are trying to access to class definitions via a node instance and not via the script.
It should be something like  `extends load("res://Utils.gd").FSM` but I do not think it will work on a class definition, unlike named classes.

**Comment by KoBeWi** [comment]
Aaand I just encountered the same issue, with a script inheriting a class defined with `class_name`. What I did is however this
```
export var event_script: Script
export var events: MapEvents

func _ready():
    if event_script:
        events = event_script.new(self)
```
where provided `event_script` resource extends `MapEvents`, but does not have a name itself (it's also a built-in script, but I don't think it's relevant).

**Comment by eon-s** [comment]
@KoBeWi built in scripts do not support some features, like named classes, see #27876

**Comment by KoBeWi** [comment]
I can't reproduce anymore with the code in https://github.com/godotengine/godot/issues/34365#issuecomment-565828135

Can anyone else reproduce in 3.2.4 beta2?

**Comment by nonunknown** [comment]
@KoBeWi Tested here, no error 
![image](https://user-images.githubusercontent.com/58845030/99578827-24a02e80-29bc-11eb-8380-d06a66d4a2a2.png)

**Comment by KoBeWi** [comment]
So looks like it's resolved.
