### ISSUE TITLE
Animation: Auto key options missing in 3D editor

### ISSUE THREAD

**Issue by STcraft** [godotengine/godot#34363]
**Godot version:**
3.1.2.stable

**OS/device including version:**
Kubuntu 19.10 (Linux 5.2.11-050211-generic #201908290731 x86_64)

**Issue description:**
Auto keying is not available in the 3D editor, A helpful feature of the animation aspect of Godot.

Toolbar in the 2D Editor:
![Screenshot_2019-12-15_13:50:59](https://user-images.githubusercontent.com/18143080/70862859-0e832600-1f42-11ea-8ef2-2b55f8ab9572.png)

Now in the 3D editor, these buttons are absent:
![Screenshot_2019-12-15_13:51:15](https://user-images.githubusercontent.com/18143080/70862858-0e832600-1f42-11ea-9b70-045bf0bc866b.png)

**Steps to reproduce:**
In the 3D editor:  
Place an AnimationPlayer somewhere in the scene and open its Animation Editor (Bottom toolbar)
You should notice that the animation controls on the viewport's toolbar are absent.

**Minimal reproduction project:**
[bugs.tar.gz](https://github.com/godotengine/godot/files/3964929/bugs.tar.gz)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/234, as feature proposals are now tracked on the Godot proposals repository.
