### ISSUE TITLE
tween_all_completed is never called if Tween leaves SceneTree while active

### ISSUE THREAD

**Issue by ntsik** [godotengine/godot#34369]
**Godot version:**
3.1.2.stable.official

**Issue description:**
`tween_all_completed` is never called in certain specific circumstances. For instance, take a `Tween` which has an animation running, e.g. `interpolate_property(sprite, 'modulate', ...)`. When that `Tween` is removed from the `SceneTree`, `tween_all_completed` is never called. (My assumption is that this is expected.)

However, if the `Tween` is then re-added to the `SceneTree` and the animation is restarted (by calling `interpolate_property(sprite, 'modulate', ...)` again), `tween_all_completed` is still never called. Additionally, `Tween.is_active()` will always return `true` from then on.

**Minimal reproduction project:**
[tween_all_completed.zip](https://github.com/godotengine/godot/files/3965419/tween_all_completed.zip)

**Comment by Xrayez** [comment]
Noticed that if you remove all pending commands with `remove_all`, it works again:

```gdscript
tween()

# Commenting these two lines makes it work again
remove_child(tween)
add_child(tween)

# This resolves the issue even if the tween is re-added
# to the scene tree as above
tween.remove_all()

tween()
```

**Comment by ntsik** [comment]
Either `remove_all()` or `remove(sprite, 'modulate')` works to fix the issue (the latter is in the reproduction project). So the current workaround is essentially to either:

1. Call `tween.remove_all()` any time the node exits/re-enters the `SceneTree`
2. Call `tween.remove` for all active interpolations before restarting them

In more complex cases, the root cause of this can be difficult to pinpoint, particularly since `Tween` does not provide any sort of introspection about which interpolations are currently considered active. This can also potentially lead to subtle memory leaks (which is how I first discovered the issue) if the object being tweened is something that needs to be freed manually, i.e. an `Object`.

**Comment by jluini** [comment]
I have a similar problem. I'm relying in signal _tween_all_completed_ being emitted to trigger some important actions.
In some (pretty random) cases I'm not getting the signal and I **never removed the Tween from the tree** (it's just a node that is in the tree from the start and never removed). I'm doing some weird use of the Tween though, like calling "stop_all()" repeatedly.

According to my recent tests I don't get _tween_all_completed_ but **do** get _tween_completed_, so replacing it probably works for me. I also will of course stop relying in the signal and doing weirds things and have lots of possible workarounds like just using a Timer.

I'm just commenting to help and to remark that removing the Tween from the tree is not necessary to get problems with the signal.

**Comment by polytect** [comment]
Have similar issue, tween just stops randomly, it shows active but randomly the `$Tween.get_runtime()` switches from any number immediately to 0. Cant rely on a signal also. Will try more hacks on this, and if those will fail as well I could construct a prototype to trap the bug. 

This was done with interpolate_property. It has something to do with nodes exiting the scene. 

`pull_target DONE [RigidBody2D:4295]
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
0.376628
pull_target DONE [RigidBody2D:4300]
0
0
0
0
`

**Comment by puthre** [comment]
One thing I've noticed is that it won't work if you first call start and then connect. You must first call connect then start the tween.

**Comment by KoBeWi** [comment]
Fixed in Tween rework.

**Comment by Szesan** [comment]
@jluini It makes perfect sense if you think about.

The pretty random cases you mention is when you call `stop_all()` while at least one tween is active and not finished. If you don't remove this instance with `remove_all()` for example, then `tween_all_completed` will never be emitted again, because there always will be reference to at least one unfinished tween (the aforementioned, interrupted one).

(`tween_all_completed` is only emitted when there is no reference to any unfinished tween. As it should be imho )
