### ISSUE TITLE
Renaming a Resource in the Filebrowser deletes all unsaved progress

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#34366]
**Godot version:** 3.1.2 stable

**OS/device including version:** Win 7

**Issue description:**
This is a weird one and it took me quite a while to hunt down. It appeared a couple of times so far, but I never realized what just happened:

If you rename a resource which is present in the scene, all unsaved progress instantly disappears. (Added nodes, changes to nodes in the inspector or the Scene Panel. Unsaved scripts however seem unaffected) 

![rename_bug](https://user-images.githubusercontent.com/47016402/70866433-ea3b3f80-1f69-11ea-98b4-edea2ace5833.gif)

I've tested the renaming with image files and .res files. As long as they are loaded in the scene, the result is the same with both. 

**Steps to reproduce:**
1. Create a new 2D scene, drag the icon into the viewport to create a Sprite. Save the scene.
2. Now add some more nodes of whatever kind, make some changes in the Inspector to the Sprite without saving or running the scene.
3. Go to the FileBrower and RMB Rename the Sprite icon.png to something else.
4. Hit enter and watch your unsaved progress being instantly consumed by the void.

**Comment by KoBeWi** [comment]
This does not happen in 3.2
