### ISSUE TITLE
Engine.target_fps doesn't work on android

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#34379]
**Godot version:**
3.2 beta 2 mono using

**OS/device including version:**
Android 6.0

**Issue description:**
Engine.target_fps doesn't seem to do anything on android

**Steps to reproduce:**
Set target_fps to something like 30 and run the game on android, the game will run as fast as the refresh rate of the screen allows it(vsync settings don't do anything on android either).

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Calinou** [comment]
We should implement half-vsync support to get a proper 30 FPS cap on 60 Hz displays. Limiting the FPS to 30 when using V-Sync may introduce stuttering due to it not being perfectly in sync.

**Comment by Alex2782** [comment]
I think this issue can be closed.

With Godot 4 and on my Samsung tablet, I was able to configure everything between 1 and 120 FPS in other tests over the last few weeks.
