### ISSUE TITLE
Changes in node structure are not propagated to its instances used with "editable children"

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#34385]
**Godot version:**
master @ 21dec856f2a7482fc69e18ffc60f64e90e10fcc5

**OS/device including version:**
Manjaro linux 18

**Issue description:**
Given the scene called `S` which has subnode `X` which has subnode `Y` (tree: `S/X/Y`)
and the scene called `User` which instantiates `S` and turns "editable children" on it
and the node `K` which is made a child of `User/S/X/Y` (so it's `User/S/X/Y/K`)
When I add some extra nodes to `S` (so that its structure is: `S/Q/W/X/Y`)
Then I'd expect `User` to update and have the following structure: `User/S/Q/W/X/Y/K`
but in current Godot, the path to `K` remains unchanged (`User.tscn` file is not changed at all) and hence this node is not accessible - I'm unable to use it.

**Steps to reproduce:**
Use the description above.

**Minimal reproduction project:**
Use the description above.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by SomeSortOfSam** [comment]
As of at least 4.1.1, nodes who's parents are editable children, and whose parental structure changes, appear to become children of the scene root. This also happens in inherited scenes. This issue appears resolved, and should be closed.
(bumping only while on a quest to see if a different bug I'm running into has an open issue)
