### ISSUE TITLE
String.format(Dictionary) doesn't work as it should

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#34381]
**Godot version:**
3.1.2
**OS/device including version:**
Windows 10
**Issue description:**
String.format use with Dictionary as the variable doesn't comply with examples with hardcoded Dictionary.
[Little tricks.zip](https://github.com/godotengine/godot/files/3969238/Little.tricks.zip)

**Steps to reproduce:**
var test: String = "Hi, {name} v{version}!"
var variables: Dictionary = {"name":"Godette", "version":"3.0"}

var example: String = "Hi, {name} v{version}!".format({"name":"Godette", "version":"3.0"})

func _ready()->void:
	test.format(variables)
	print(test)
	print(example)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
`.format` does not modify the original string, so you need to do `print(test.format(variables))`.

**Comment by nezvers** [comment]
My bad in that case.
