### ISSUE TITLE
False error "using assignment with operation on a variable" when using match

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#34384]
**Godot version:**
Godot 3.2 beta 3
**OS/device including version:**
Ubuntu 19.10
**Issue description:**

Code which should work according to - https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#match or just should show error about using constants.
```
match randi() % 26:
  2:
    pass
  var rr:
    rr += 2
```
but show this error
```
 res://Operators.gd:117 - Parse Error: Using assignment with operation on a variable that was never assigned.
 modules/gdscript/gdscript.cpp:576 - Method/Function Failed, returning: ERR_PARSE_ERROR
```

**Comment by KoBeWi** [comment]
Fixed in 4.0
