### ISSUE TITLE
Empty item in "Search Help" dialog

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#34387]
**Godot version:**
2ba96f0

**Issue description:**
The "Search Help" can sometimes show an empty item on the very top of the tree, just like how it happened in #21640. I couldn't find a proper way to reproduce this, however.

![Screenshot_20200821_223708](https://user-images.githubusercontent.com/30739239/90945966-1885ee80-e418-11ea-9233-c97ced4685bb.png)

**Comment by YeldhamDev** [comment]
Haven't seen the bug for a long while, I think it's actually gone now. If it isn't, I will reopen the original one instead of creating a new. Closing it.

**Comment by KoBeWi** [comment]
@YeldhamDev Is the bug gone again? I don't see it.

**Comment by YeldhamDev** [comment]
@KoBeWi It literally comes and goes. I have no clue what triggers it.

**Comment by YeldhamDev** [comment]
Haven't run into it for a good while, so...
