### ISSUE TITLE
Exported project on android crashes immediately in master

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#34392]
**Godot version:**
Master

**OS/device including version:**
Android 10
Google Pixel

**Issue description:**
Running anything exported from a master build causes the app to crash immediately.

Reverting all the commits in https://github.com/godotengine/godot/pull/33910 makes the issue go away CC @Faless @m4gr3d 

**Steps to reproduce:**
1. Build from master
2. export to android

Output from adb logcat:
[log.txt](https://github.com/godotengine/godot/files/3971757/log.txt)
The following line appears to be the most prominent error 
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.godotengine.test3d-0O2E8CAMe9vWVpzNZ2brXw==/base.apk"],nativeLibraryDirectories=[/data/app/org.godotengine.test3d-0O2E8CAMe9vWVpzNZ2brXw==/lib/arm, /data/app/org.godotengine.test3d-0O2E8CAMe9vWVpzNZ2brXw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/product/lib]]] couldn't find "libgodot_android.so"
```

**Comment by Anutrix** [comment]
I have same issue but got this in adb:
```
12-17 14:13:27.070: E/AndroidRuntime(904): 	at org.godotengine.godot.utils.PermissionsUtil.hasManifestPermission(PermissionsUtil.java:172)
12-17 14:13:27.070: E/AndroidRuntime(904): 	at org.godotengine.godot.utils.GodotNetUtils.<init>(GodotNetUtils.java:50)
12-17 14:13:27.070: E/AndroidRuntime(904): 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:507)
12-17 14:13:27.070: E/AndroidRuntime(904): 	at org.godotengine.godot.Godot.onCreate(Godot.java:673)
```
As you can see, a error message says GodotNetUtils.java:50 which does seem to have been changed in https://github.com/godotengine/godot/pull/33910.
