### ISSUE TITLE
Physics. Joints. Motor.

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#34398]
**Godot version:**
3.x (Bullet)
**OS/device including version:**
Windows 10 (not testing another)
**Issue description:**
Motor make "Fly" rigidbody.
![image](https://user-images.githubusercontent.com/22836285/70996348-99e7ed00-20e3-11ea-86ab-70d8502604f8.png)

Bug? Bullet? Godot? Settings? Or my arms?
**Steps to reproduce:**
Make 2 rigidbody 
![image](https://user-images.githubusercontent.com/22836285/70996098-280fa380-20e3-11ea-95da-7a3339e9631f.png)
and you get helicopter
**Minimal reproduction project:**
[test3.zip](https://github.com/godotengine/godot/files/3973287/test3.zip)

**Comment by Anutrix** [comment]
Isn't it fine?
Both are rigid bodies so when one is trying to rotate the other is getting affected due to momentum(since their mass is same).
Try setting one of the rigid bodies to static mode and they'll look fine. Or better yet, set mass of one of the bodies to 1000.

**Comment by SuperDIMMaX** [comment]
> Isn't it fine?

Not fine. this is bug. Unity along time ago has samiliar problem. Gravity, momentum, impulse - prevent lifting effect. 

> Both are rigid bodies so when one is trying to rotate the other is getting affected due to momentum(since their mass is same).

Nope... 1st it rotate both. 2nd if you take hand another human with some mass and start spin(Y axies) - you... fly? Or if i take dumbbell and start rotate it along X? short answer - center of mass

> Try setting one of the rigid bodies to static mode and they'll look fine. Or better yet, set mass of one of the bodies to 1000.

This is trivial... or rotate without physics... so many variants... but, bug still exist.

**Comment by Calinou** [comment]
> Not fine. this is bug. Unity along time ago has samiliar problem. Gravity, momentum, impulse - prevent lifting effect.

Maybe this is because gravity is too low? Does it improve if you increase the gravity scale for all RigidBodies (or the default gravity in the Project Settings)?

**Comment by SuperDIMMaX** [comment]
no... gravity can affected this, but this break calculations for mass, slide, rebound(?), etc... 
1 kg(in Bullet 1 is 1 kg and in Unity 1 is 1kg) - 9.8 (this is Earth constant for all physics engine) 
If this tested in Unity and Blender(have Bullet physics(tested in old 2.7)) / etc. - works excellent. 
In theoric, this imposible - how objects can lifted? ( no air calculations, this in not helicopter :) ) and not gyroscopic effect ( probality yes, but wrong calculate? ). 
I not see any logic reason - why this produce "fly" effect.

**Comment by Klowner** [comment]
The motor between the two cubes is causing them to thrash and bounce around on the ground? I've looked at this and tweaked the motor forces and stuff and this all seems like expected behavior.

Could you upload the .blend file showing this working correctly in Blender, @SuperDIMMaX

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
