### ISSUE TITLE
libevdev2:i386 is not installed on ubuntu by default

### ISSUE THREAD

**Issue by nepitard** [godotengine/godot#3439]
"error while loading shared libraries: libevdev.so.2: cannot open shared object file: No such file or directory" when opening built game binary either on 32/64-bit ubuntu. 32-bit linux templates were built on ubuntu chroot with libevdev installed.

**Comment by akien-mga** [comment]
You probably just need to install libevdev.

**Comment by nepitard** [comment]
libevdev2 and libevdev-dev packages are already installed.

**Comment by reduz** [comment]
maybe the release binaries should like that static

**Comment by akien-mga** [comment]
> libevdev2 and libevdev-dev packages are already installed.

You need libevdev2:i386 to run the 32-bit binaries.

> maybe the release binaries should like that static

That could be an option yeah.

**Comment by nepitard** [comment]
Fixed it by installing libevdev2 on 32-bit system, but anyway it could be an improvement when player doesn't need to install any libraries to start the game

**Comment by punto-** [comment]
Yeah this should be statically linked. Does the editor fail the same way?

**Comment by nepitard** [comment]
I'm using 64-bit editor so no problems with that. Also don't know if libevdev installed by default or I installed it before.

**Comment by Hinsbart** [comment]
I just had a quick look at this, but couldn't quite figure it out. How to tell scons to link a single lib statically?
I remember doing something like `-Wl,-Bstatic "lib" -Wl,-Bdynamic` in the past. But it seems to me there's no easy way to do that using scons..?
