### ISSUE TITLE
Mono IDE not detecting EditorPlugin class

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot#34404]
**Godot version:**
c3ea4ea

**OS/device including version:**
Linux Mint 19.2

**Issue description:**
When creating a class that inherits from `EditorPlugin`, the ide is not detecting the class and gives the error `The type or namespace name 'EditorPlugin' could not be found (are you missing a using directive or an assembly reference?)`. I've tested this on Monodevelop, vscode, and rider.

Compiling the plugin on godot works, but when invoking msbuild manually the error persists.

**Steps to reproduce:**
Create a class in C# that inherits `EditorPlugin`

**Comment by neikeq** [comment]
The workflow for editor scripting is not the ideal right now. Basically, the editor API is only referenced when building with `Configuration=Tools` which is what the editor and editor player use.
In MonoDevelop, changing the configuration to `Tools` should allow it to resolve these. I haven't tried this with Rider yet but it should work as well. VS Code on the other hand may be more complicated.

**Comment by TritiatedWater** [comment]
I've just changed the config to `Tools` and it worked as expected.

**Comment by Pizzaernam** [comment]
I'm developing a plugin in C# with Visual Studio Code, and I was having the same problem.
For VS Code it was as simple as changing the .csproj file.

I changed the this line near the top.
`<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>`
to
`<Configuration Condition=" '$(Configuration)' == '' ">Tools</Configuration>`

This instantly enabled all of the Editor API such as EditorPlugin and EditorInspector in VS Code.
This information could be useful to have in the docs.
