### ISSUE TITLE
Mono unable to multiply Color

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot#34403]
**Godot version:**
c3ea4ea9b
**OS/device including version:**
Linux Mint 19.2
**Issue description:**
Unable to multiply Color with Color or integer. This only happens to C#. The workaround is to decompose the Color and multiplying the components.
**Steps to reproduce:**
```cs
var col = new Color(5,5,5,5);
col = col * col; //Error Operator '*' cannot be applied to operands of type 'Color' and 'Color'
col = col * 2; //Error Operator '*' cannot be applied to operands of type 'Color' and int''
```

**Comment by clayjohn** [comment]
Can you multiply Colors in GDScript?

**Comment by Calinou** [comment]
@clayjohn Sure :slightly_smiling_face: 

```gdscript
# Prints 1,2,3,2 (the alpha chanel is also multiplied…)
print(Color(0.5, 1, 1.5) * 2)
# Prints 0,0.5,1.5,1
print(Color(0.5, 1, 1.5) * Color(0, 1, 1))
```

**Comment by TritiatedWater** [comment]
It seems that the operator overloading for `Color` isn't working. A can confirm that this doesn't effect vectors.
