### ISSUE TITLE
IK bones with magnet enabled deform the mesh 

### ISSUE THREAD

**Issue by yaelatletl** [godotengine/godot#34415]
**Godot version:** 
3.2 at 7d34d1a85f95edd1b29b8eb24cda49b355db2c3d

**OS/device including version:**

Windows 10

**Issue description:**
Using Magnet on the IK deforms the mesh like this:

![imagen](https://user-images.githubusercontent.com/28612272/71054855-15b05c80-2119-11ea-84b0-fb89fbe7d25c.png)

**Steps to reproduce:**
Node setup:
![imagen](https://user-images.githubusercontent.com/28612272/71055009-b1da6380-2119-11ea-9f86-7654fec7f698.png)

Create an IK rig in the engine, and then add this script to the IKskeleton 

`tool
extends SkeletonIK

func _process(delta):
	magnet = $Magnet.translation
`

**Comment by yaelatletl** [comment]
@AndreaCatania Found out in 3.2 Release that now the IK bones break a model, no matter if it uses magnets or not, so IK bones are pretty much broken, I'd call it a regression

**Comment by AndreaCatania** [comment]
Can you please send me the model?

**Comment by yaelatletl** [comment]
@AndreaCatania I tested it with https://github.com/GDquest/godot-3d-mannequin/

**Comment by yaelatletl** [comment]
Checked once again, reverted the IK skeleton code to 3.1.2 and found out the issue still exists. Verified that the issue manifests on the IK bones, but the actual bones move acordingly, it's the mesh that won't follow the bone correctly

**Comment by yaelatletl** [comment]
Found some more information for this, seems to be that using set_global_pose_override will cause the mesh to deform

**Comment by AndreaCatania** [comment]
I'll give it a check soon.

**Comment by SVA-developer** [comment]
I met the same problem, found where it came from, but I don’t know the engine code very well. Therefore, I left a request for improvement for specialists here: https://github.com/godotengine/godot/issues/37095

**Comment by AndreaCatania** [comment]
This should be already fixed with this: https://github.com/godotengine/godot/pull/37272

**Comment by akien-mga** [comment]
Fixed by #37272.
