### ISSUE TITLE
object property named 'break' can be mixed up by gd script break statement

### ISSUE THREAD

**Issue by Be101** [godotengine/godot#34422]
The VehicleBody object has a property called 'break' used to set the break force.
when using it from a gd script assigned to that body it would look like this:
```
extends VehicleBody

func _physics_process(delta):
	engine_force = 100.0
	break = 100.0
```
however, this throws an error, because it reads "break" as the gd script break statement.
A workaround is:
```
extends VehicleBody

func _physics_process(delta):
	engine_force = 100.0
	get_node(".").break = 100.0
```
or more ugly:
`$".".break = 100.0`
Notice how the syntax highlight is still confused in both cases.
So I would suggest to change the 'break' property to 'break_force'.

**Comment by Zireael07** [comment]
It is not 'break', it is **brake**, see: https://docs.godotengine.org/en/latest/classes/class_vehiclebody.html

**Comment by Be101** [comment]
Jup, sorry
