### ISSUE TITLE
Mono Bug. Crash in Windows build due to using DateTime. Possibly the DateTime.Now call in particular.

### ISSUE THREAD

**Issue by RaoulMarz** [godotengine/godot#34428]
**Version:**
3.2 beta 2 mono

Windows (Wine) in Ubuntu 19.10 but also confirmed by others running the application that had the same crash.

Using DateTime in certain ways causes a crash. I am yet unable to exactly trace the exact call. Will try to get a more detailed stack trace.

The code is included, and when run, causes this crash. It seems likely a call to DateTime.Now is the trigger of the crash. The Windows build is created from within Ubuntu 19.10 and the 3.2 beta mono version from the official website is used.

**Minimal reproduction project:**

![godot_mono_datetime_crash_18Dec2019](https://user-images.githubusercontent.com/22550764/71088767-eeed3700-21a7-11ea-8cfe-4c24ee763b2b.png)

[Mono-Bug-DateTime-Crash#18Dec2019.zip](https://github.com/godotengine/godot/files/3978496/Mono-Bug-DateTime-Crash.18Dec2019.zip)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Tobi-Mob** [comment]
@KoBeWi  I am unable to reproduce this with Godot 3.3.3 on Linux(Ubuntu/Mint) and Windows 10.
Works all fine for me.
