### ISSUE TITLE
GraphEdit's AddValidConnectionType args are reversed

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#34420]
**Godot version:**
269145a346bddae5cbbf00fd17b6c8eac4cd4665 Mono
**OS/device including version:**
ArcoLinux
**Issue description:**
AddValidConnectionType takes two arguments: fromType, and then toType.  However, in order to get a right-side slot (from) to connect with a left-side slot(to), you actually have to supply the arguments in the reverse order: toType first, then fromType, despite the argument names.  These should probably be swapped around, or renamed.

I'm not sure if GDScript also has this same issue or if it's another C# inconsistency.

**Comment by sheshire63** [comment]
in gd script it allows the connection if you start the connection from the "to" slot type regardless of left or right side
therefore if you allow a connection from slot type 0 to slot type 1 you connect it both ways if you start with the slot type 1

**Comment by akien-mga** [comment]
CC @godotengine/gui-nodes

**Comment by KoBeWi** [comment]
Yep, seems like they are really reversed. Not sure why there weren't other reports about it, but it doesn't affect visual editors, because connections are two-way.
