### ISSUE TITLE
Segmentation Fault when reparenting a node in a signal callback

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#34426]
**Godot version:**
7d34d1a85

**Issue description:**
```gdscript
node.get_parent().remove_child(node)
to.add_child(node)
```
leads to a segmentation fault when called in a signal callback.

Here is the stacktrace:
![image](https://user-images.githubusercontent.com/28286961/71085790-995d5e00-2198-11ea-9019-6652cacf86f6.png)
It seems to have to do with removing the groups in SceneTree after the node is removed.

**Steps to reproduce:**
Call this in a signal callback:
```gdscript
node.get_parent().remove_child(node)
to.add_child(node)
```

**Minimal reproduction project:**
[ReparentTest.zip](https://github.com/godotengine/godot/files/3978330/ReparentTest.zip)

**Comment by qarmin** [comment]
Similar or duplicate to #34207

**Comment by Jummit** [comment]
> Similar or duplicate to #34207

Seems like a duplicate. If anyone wants to fix this, I have some more information in this issue, like a smaller example and a stack trace.
