### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by Abhicse079** [godotengine/godot#3443]
Using window 7 for compiling  scons platform=android target=relase

I changed the max_src 64 to 128 in the file drivers/SCsub still facing same error.

scons: *** [drivers\libdrivers.android.opt.armv7.neon.a] The filename or extension is too long
scons: building terminated because of errors.

**Comment by Abhicse079** [comment]
Now getting

scons: *** [drivers\libdrivers2.android.debug.armv7.neon.a] The parameter is incorrect
scons: building terminated because of errors.

**Comment by reduz** [comment]
this might have been fixed, can you test again with latest github head?

**Comment by vnen** [comment]
This should be working now.

**Comment by Gramps** [comment]
I actually get this error in 2.1.2 when compiling the Android template, though it is in modules:
```
scons: *** [modules\libmodules.android.opt.armv7.neon.a] The filename or extension is too long
scons: building terminated because of errors.
```

**Comment by vnen** [comment]
@Gramps how long is the path before the Godot source?

**Comment by Gramps** [comment]
Mmm, it is 36 characters.

**Comment by vnen** [comment]
I just built 2.1.3 here and it went fine. I don't know what could be wrong.

**Comment by Gramps** [comment]
I tried compiling on Linux to bypass the weird character limit issue, which worked.  However, doing the ./gradlew build step just results in failure as well:
`Could not resolve all dependencies for configuration ':_debugCompile'.`
Not sure why but I'd wager this has nothing to do with Godot itself.  Thanks for the help!

**Comment by YeeshuRastogi** [comment]
I am having the same error. Extension Too long. I built the game on 2.1.2 executable. and now i have to use source files in order to use adds modules. I built the executable, but the android (debug/release) is not happening, due to this error. ANy help? other than doing this on Linux? Thanks

**Comment by Calinou** [comment]
I wonder if this is related to the [260-character limit on file path lengths](https://stackoverflow.com/questions/27680647/does-max-path-issue-still-exists-in-windows-10); perhaps it could be worth trying to disable it if you're on Windows 10.

**Comment by Gramps** [comment]
Since then I just used Linux.  However, I'll give that a shot to see if it works.  Cheers!
