### ISSUE TITLE
Error and unable to open Visual Studio Code from Godot editor

### ISSUE THREAD

**Issue by Miniputs** [godotengine/godot#34434]
Godot version: 3.2.beta4.mono

OS/device including version: Windows 10 Home. 64 bit.

Issue description: When trying to open a cs file from Godot editor it fails to open Visual Studio Code.
Error message:  modules/mono/glue/gd_glue.cpp:184 - Error when trying to run code editor: VSCode. Exception message: 'ApplicationName='C:\Users\Henrik\AppData\Local\Programs\Microsoft VS Code\bin\code', CommandLine='C:/Users/Henrik/Documents/Godot/VisualStudioCodeError/ -g C:/Users/Henrik/Documents/Godot/VisualStudioCodeError/test.cs:1:0', CurrentDirectory='', Native error= %1 is not a valid Win32 application. 

Steps to reproduce: Set Mono External Editor to Visual Studio Code. Open a C# file or make new.

Minimal reproduction project:
[VisualStudioCodeError.zip](https://github.com/godotengine/godot/files/3979529/VisualStudioCodeError.zip)

**Comment by neikeq** [comment]
Looks like a regression from f91416d9acabb76f6efcdc2d09835d04cd98c881.

https://github.com/godotengine/godot/blob/28599e6c2092a1b4e5a9cd7a831efbaed479c3be/modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs#L108

should be

```C#
bool hasPathExt = !string.IsNullOrEmpty(nameExt) && windowsExts.Contains(nameExt, StringComparer.OrdinalIgnoreCase);
```

**Comment by Miniputs** [comment]
Makes sense.
I assume it will implemented in future version.

**Comment by neikeq** [comment]
No need to close, it will be auto-closed once it's fixed :smile:
I've been busy for the last days and I couldn't check this yet. I commented the possible cause just in case I forget about it or in case someone else may want to give it a try before I do.
