### ISSUE TITLE
Godot ERROR IN VIDEO DRIVER ON START ENGINE!!

### ISSUE THREAD

**Issue by indexart** [godotengine/godot#34446]
**Godot version:** 3.2 BETA 4

**OS/device including version:** Windows 7

**Issue description:** DRIVER ERROR ON START AND EDIT PROJECT ( GLES 3)

**Steps to reproduce:**ON START

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Please fill out the template provided. As it stands now you have not provided enough information for anyone to help you.
