### ISSUE TITLE
Cannot export enums in C#

### ISSUE THREAD

**Issue by CathodeRayBlues** [godotengine/godot#34447]
**Godot version:**
3.1.2 mono
**OS/device including version:**
Windows 10
**Issue description:**
`error CS0592: Attribute 'Export' is not valid on this declaration type. It is only valid on 'property, indexer, field' declarations.`
**Steps to reproduce:**
```
[Export]
public enum TYPE{ALPHA, BETA}
```
**Minimal reproduction project:**

**Comment by neikeq** [comment]
I think what you want to do is export a field whose type is an enum:

```
enum TYPE{ALPHA, BETA}

[Export]
TYPE myEnumField = TYPE.BETA;
```
