### ISSUE TITLE
Array append does not trigger setter

### ISSUE THREAD

**Issue by haonkrub** [godotengine/godot#34451]
**Godot version:**
3.1.2
**OS/device including version:**
Ubuntu Studio 19.10
**Issue description:**
setter method not triggered on modifying methods of object
**Steps to reproduce:**
`var x = [] setget test
func _ready():
    x.append("henlo")
    print(x) # "henlo"
func test(val):
    print(val) # does not print`

~~I'm not sure whether this is an intended behavior or not.~~ Could either solve by adding pure methods that return a copy of the array (and any kind of object with modifying methods that return void) with the modification, or by actually just patching to trigger setters on methods append, erase, remove, etc.

**Comment by shvelo** [comment]
Why would Array append ever trigger a setter? You're not replacing it with another array.

If you want to watch array changes, you can write your own wrapper.

**Comment by KoBeWi** [comment]
> I'm not sure whether this is an intended behavior or not.

It is intended. The variable stores reference to the array, so unless you assign another array to the variable, the setter will not be called. Instead of appending to the array directly, you can write a method that does this and acts as "setter".

**Comment by haonkrub** [comment]
Yeah, I suppose since append is a method called on an object, it would count as the object modifying itself, even if something external is calling the method. Maybe this should be a feature request then? There isn't really another simple way to catch modification on collection-y types in that way, unless you create some kind of custom object to wrap them which emits a signal on all those modifications, which sounds like it would be pretty inefficient.

**Comment by KoBeWi** [comment]
> Maybe this should be a feature request then?

Sounds like something that should go here: https://github.com/godotengine/godot-proposals/issues
