### ISSUE TITLE
GraphNode's ports selectable through other graph nodes

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#34457]
**Godot version:**
269145a346bddae5cbbf00fd17b6c8eac4cd4665

**OS/device including version:**
ArcoLinux
**Issue description:**
Whether or not a graph node is covering another graph node's port, it's still possible to drag a connection off.  This leads to annoyances where you're trying to move the graph node out of the way, but instead you're disconnecting things by accident.  Ideally, ports would not be manipulable while being covered by other graph nodes.

![portissue](https://user-images.githubusercontent.com/28724859/71148960-ba529d00-21f2-11ea-884b-1ab2548d24dd.gif)

**Comment by KoBeWi** [comment]
Still valid in 9e7348f

**Comment by Geometror** [comment]
Seems to be fixed, I can't reproduce this in 4.3-dev6. Can someone confirm?
