### ISSUE TITLE
GraphEdit's connection_from_empty signal gives the wrong slot

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#34454]
**Godot version:**
269145a346bddae5cbbf00fd17b6c8eac4cd4665 Mono
**OS/device including version:**
ArcoLinux
**Issue description:**
The value given from the signals connection_from_empty and connection_to_empty will be wrong if not every slot is enabled.

![image](https://user-images.githubusercontent.com/28724859/71147057-32b65f80-21ed-11ea-9d13-9270c6206c75.png)

In this example, Godot will report in connection_from_empty that Slot 1 is slot 0, Slot 2 is slot 1, and Slot 3 is slot 2.  Meanwhile, with connection_to_empty, Godot reports that Slot 2 is slot 0, and Slot 3 is slot 1.  So, it seems to be ignoring slots that aren't enabled, and starts with the first enabled slot for counting.

This is a big problem when you need to get, for example, the type of the slot you're dragging from, but are given an entirely different slot based on what's active and what's not.  To my knowledge, no other signal in GraphEdit operates this way.

Tested in both GDScript and C#.

**Comment by somnivore** [comment]
As it turns out, the other signals do seem to operate with this slot offset.

Nonetheless, it's not usable with `get_slot_type_x()`, since that does not take it into account.  So if I set Slot 2's type to 1 and attempted to reference it, I would instead get Slot 3's type of 0, since that then becomes slot 2 in this configuration.

**Comment by mrushyendra** [comment]
This can be closed in favor of #37227
