### ISSUE TITLE
Light2D shadows not working in HTML5 / GLES2

### ISSUE THREAD

**Issue by gfeller** [godotengine/godot#34459]
**Godot version:**
3.1.2

**OS/device including version:**
Windows 10: HTML Export

**Issue description:**
Shadow does not working after upgrading to 3.1.2. Only with HTML5 Export.

Error: 
**ERROR**: Condition ' status != 0x8CD5 ' is true. returned: RID() HSR-QUEST.js:7:32615
   At: drivers/gles2/rasterizer_storage_gles2.cpp:4857:canvas_light_shadow_buffer_create() - Condition ' status != 0x8CD5 ' is true. returned: RID() HSR-QUEST.js:7:32615
Error: WebGL warning: renderbufferStorage: Invalid `internalFormat`: 0x1902. HSR-QUEST.js:7:268798
Error: WebGL warning: checkFramebufferStatus: Framebuffer not complete. (status: 0x8cd6) DEPTH_ATTACHMENT: Attachment has no width or height.

**Steps to reproduce:**
Create a scene with:
Node2d > Sprite -> Light2d 
Activate Shadow
Export as HTML5

**Minimal reproduction project:**
[light.zip](https://github.com/godotengine/godot/files/3982596/light.zip)

**Comment by akien-mga** [comment]
So it was working properly in 3.1.1?

Does it work with 3.2 beta 4?

**Comment by gfeller** [comment]
Same error with 3.2 beta 4 not sure about 3.1.1

**Comment by akien-mga** [comment]
Ah, but you wrote:

> Shadow does not working after upgrading to 3.1.2.

Didn't you mean that they used to work fine before upgrading to 3.1.2? If so, what version were you using?

**Comment by gfeller** [comment]
I used before: Godot_v3.1-stable_win64

**Comment by akien-mga** [comment]
What browser are you using?

Could you include a screenshot of what the shadow problem is?
The minimal project that you linked has no `LightOccluder2D`, so there are understandably no shadows (there's also no background/object to cast the light on either).

**Comment by akien-mga** [comment]
I improved the reproduction project to actually include `LightOccluder2D`s, and I can now reproduce the issue:
[light.zip](https://github.com/godotengine/godot/files/3982827/light.zip)

With 3.2 beta 4:

Desktop Linux GLES2:
![Screenshot_20191219_104759](https://user-images.githubusercontent.com/4701338/71163278-07635d00-224d-11ea-841a-4e6700dc08ea.png)

HTML5 GLES2 (Firefox Nightly, Linux):
![Screenshot_20191219_104836](https://user-images.githubusercontent.com/4701338/71163310-1cd88700-224d-11ea-86b3-eb2d4ef34ca3.png)

**Comment by akien-mga** [comment]
I can confirm that the bug also happens in 3.1.2-stable, but the shadows work fine in 3.1.1-stable.

**Comment by akien-mga** [comment]
Errors raised by 3.2 beta 4 in Firefox Nightly on Linux (Intel HD 630 / Mesa 19.2.6):
```
The script from “http://localhost:8060/tmp_js_export.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type. tmp_js_export.html
Godot Engine v3.2.beta4.official - https://godotengine.org tmp_js_export.js:7:37652
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. tmp_js_export.js:7:17162
OpenGL ES 2.0 Renderer: Mozilla tmp_js_export.js:7:37652
 tmp_js_export.js:7:37652
Error: WebGL warning: renderbufferStorage: Invalid `internalFormat`: 0x1902. tmp_js_export.js:7:275233
Error: WebGL warning: checkFramebufferStatus: Framebuffer not complete. (status: 0x8cd6) DEPTH_ATTACHMENT: Attachment has no width or height. tmp_js_export.js:7:262656
**ERROR**: Condition ' status != 0x8CD5 ' is true. returned: RID() tmp_js_export.js:7:37921
   At: drivers/gles2/rasterizer_storage_gles2.cpp:5343:canvas_light_shadow_buffer_create() - Condition ' status != 0x8CD5 ' is true. returned: RID() tmp_js_export.js:7:37921
Error: WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_POSITIVE_X level 0 is incurring lazy initialization. tmp_js_export.js:7:269507
Error: WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_NEGATIVE_X level 0 is incurring lazy initialization. tmp_js_export.js:7:269507
Error: WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_POSITIVE_Y level 0 is incurring lazy initialization. tmp_js_export.js:7:269507
Error: WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_NEGATIVE_Y level 0 is incurring lazy initialization. tmp_js_export.js:7:269507
Error: WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_POSITIVE_Z level 0 is incurring lazy initialization. tmp_js_export.js:7:269507
Error: WebGL warning: generateMipmap: Tex image TEXTURE_CUBE_MAP_NEGATIVE_Z level 0 is incurring lazy initialization. tmp_js_export.js:7:269507
```

**Comment by clayjohn** [comment]
Looks like

https://github.com/godotengine/godot/blob/981c6aa102ba50d314a023a96d7affb7081334e5/drivers/gles2/rasterizer_storage_gles2.cpp#L5818

Needs to be GL_DEPTH_COMPONENT16
