### ISSUE TITLE
Show out of screen in full screen phone

### ISSUE THREAD

**Issue by jihuayu** [godotengine/godot#34466]
**Godot version:**
3.1.2.stable 

**OS/device including version:**
manjaro
Honor v20 Android 10

**Issue description:**
Label show out of screen in full screen phone.
- pic in my phone:
![1](https://user-images.githubusercontent.com/32858525/71190542-bb9dcb80-22bf-11ea-9a8a-d6429f3b6c9f.png)

- pic in my computer:
![2](https://user-images.githubusercontent.com/32858525/71190562-c8222400-22bf-11ea-9a8c-0c6ce1392ad5.png)

**Steps to reproduce:**
set a label near the screen.

**Minimal reproduction project:**

**Comment by jihuayu** [comment]
It looks like a problem could not be sloved.
The best way is dont set the sprite in 4 corners.

**Comment by NoFr1ends** [comment]
This is a general problem with display cut outs / notch too. 
We should think about a way to provide the OS SafeArea via GDScript/Mono or a general control to prevent placing outside the SafeArea.

https://developer.android.com/reference/android/view/DisplayCutout
https://developer.apple.com/documentation/uikit/uiview/2891102-safearealayoutguide

I will create a feature proposal.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/321, which has more information about the feature to be implemented.
