### ISSUE TITLE
3d transform tools and grid are affected by environments

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#34463]
**Godot version:**
28859e6c2

**Issue description:**
The 3d viewport transform tools and the grid lines are affected by environments, which makes them look pretty bad in some cases:
![20191219](https://user-images.githubusercontent.com/28286961/71186215-20840200-227d-11ea-8db9-3fdba12235c3.png)

**Steps to reproduce:**
1. Change the default environment, enable bloom for example.
2. Create a 3d scene and select something.

**Comment by qarmin** [comment]
I'm almost sure, that this is duplicate of other issue.
I have also problem with Light, because it cause, that gizmos are very dark
![jfile](https://user-images.githubusercontent.com/41945903/71198414-0275cc00-2294-11ea-8c69-6984f0494eb8.gif)

**Comment by clayjohn** [comment]
Does this affect GLES2 and GLES3?

**Comment by Calinou** [comment]
Duplicate of #10478. This is related to Godot not using render layers for gizmos (which may be possible with the upcoming Vulkan renderer).
