### ISSUE TITLE
Editor crashes when opening project on windows with Nvidia card(only GLES 3)

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#34461]
**Godot version:**
3.2 5bc427a95
**OS/device including version:**
Windows 10 1903 Nvidia NVS 310 392.58
**Issue description:**
Editor crash when I try to open this project - https://github.com/GDQuest/godot-demos/tree/master/2018/06-16-intro-to-shaders-2d-water/start

This happens only with GLES 3, in GLES 2 everything works
![Bez nazwy](https://user-images.githubusercontent.com/41945903/71162530-ad15cc80-224b-11ea-9161-423d116e10b8.png)

**Comment by MadEqua** [comment]
Seems device/driver specific, it doesn't crash with a Geforce GTX 1050 Ti (driver 436.48) on Windows 10.

**Comment by raphael10241024** [comment]
Works fine with my GTX 1050Ti on windows 10 too.

**Comment by qarmin** [comment]
I don't have windows anymore, so I can't reproduce this anymore
