### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3446]
I've successfully compiled Godot from github source code. commit 87517c564b832
when I run the output I get:
$ ./godot.x11.tools.64
Segmentation fault (core dumped)

halp!
(using ubuntu gnome 15.04 64bits)

**Comment by akien-mga** [comment]
Can you try running it through gdb so that there is more info about the crash?
Also, were you able to run earlier versions fine?

**Comment by lordadamson** [comment]
No I wasn't able to run previous versions it gave me the same error. I'll try to debug and will update you.

**Comment by lordadamson** [comment]
Okay I switched machines and the bug no longer occurs so it does not affect me anymore.
but it did happen on the old machine it was a core dual machine by the way.

**Comment by akien-mga** [comment]
It would still be quite interesting to get the output from gdb, you can run it as:
```gdb ./bin/godot.x11.tools.64```
Then ```run``` and after the crash ```bt``` to get the backtrace.

**Comment by lordadamson** [comment]
I will as soon as I can. I'm in a challenge to create a game in 7 days now so I don't have that much time but I'll do it later today.

**Comment by bojidar-bg** [comment]
BTW, it *might* be from old OpenGL or drivers version...

**Comment by bojidar-bg** [comment]
Also, related to #67, #2067 and #977 (segmentation fault, linux)

**Comment by reduz** [comment]
most likely OpenGL not supported

**Comment by akien-mga** [comment]
Yeah, closing as a duplicate of #156.

**Comment by lordadamson** [comment]
Sorry I couldn't debug it guys. It wasn't my computer. it was a computer in a co-working space that I had access to for a limited amount of time.
