### ISSUE TITLE
set_broadcast_enabled() required for UDP broadcast breaking change between beta2 and beta4

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#34469]
**Godot version:**
Prior to Godot 3.2 beta2 you did not have to call this function.
After Godot 3.2 beta 4 you do have to call it.
**OS/device including version:**
Linux Mint & Android.
**Issue description:**
PacketPeerUDP.set_broadcast_enabled() should have the documentation showing that it is a breaking change. I wasted a whole day tracking down why my UDP broadcast was suddenly broken.
**Steps to reproduce:**
Utilize Godot 3.2 Beta2 to send a udp broadcast note that the set_broadcast_enabled() function is not even an option.
```shell
SCRIPT ERROR: search_for_peers: Invalid call. Nonexistent function 'set_broadcast_enabled' in base 'PacketPeerUDP'.
```
Now utilize Godot 3.2 Beta 4 note that no broadcast messages are sent at all, and there is no warning for them not being sent. Just nothing happens. A warning would be good too.
**Minimal reproduction project:**
I will try to build a reproduction project latter. But it really is simple, just build a PacketPeerUDP and set it to transmit and listen on the braodcast address 255.255.255.255 and notice that prior to beta 2 it works fine and after beta4 it fails unless you call set_broadcast_enabled(true).

[Reference the Pull Request that made the change](https://github.com/godotengine/godot/pull/33910)

Don't get me wrong the change was needed but it still does not provide any kind of warning as to why the messages are not being transmitted.

**Comment by Calinou** [comment]
We don't have any compatibility guarantees between development cycles of a same recycle, but we can look at adding an error message if possible.

**Comment by FeralBytes** [comment]
@Calinou OK, thank you that will work.

**Comment by Faless** [comment]
This is documented in docs:
https://docs.godotengine.org/en/latest/classes/class_packetpeerudp.html#class-packetpeerudp-method-set-broadcast-enabled

Something we could also add to the release notes when 3.2 is out.
Closing, as this is no bug, and the documentation is already updated.

**Comment by akien-mga** [comment]
> Something we could also add to the release notes when 3.2 is out.

@Calinou Can you add this to the changelog?

**Comment by Calinou** [comment]
@akien-mga Done.
