### ISSUE TITLE
Temporary blocking in 3.2 beta 4 with opengl 3

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#34462]
**Godot version:**
3.2 beta 4 Mono
3.2 beta 4 Classic

**OS/device including version:**
Win10 64 Home

**Issue description:**
A temporary lock occurs when the editor is started.
A temporary lock occurs when executing any scene.

This did not happen in beta 1.

**Steps to reproduce:**
Simply start the editor or run any scene and move the cursor to see how it temporarily locks while the editor starts.

You can see in this video how the cursor is locked in both cases.
https://youtu.be/XQGdyZt-UTM

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Could you try other beta builds between beta 1 and beta 4 to check if you can narrow down when the problem started?

**Comment by Torguen** [comment]
> Could you try other beta builds between beta 1 and beta 4 to check if you can narrow down when the problem started?

This was magnified in beta 2.
In beta 1 it also happened but it was almost imperceptible.

**Comment by Torguen** [comment]
More info, this only happens with OpenGL 3.

**Comment by clayjohn** [comment]
Sounds like it may just be shaders compiling.

**Comment by Torguen** [comment]
Well ... in the tests I did I didn't use shaders.

**Comment by Zireael07** [comment]
Any scene with anything rendered (2d or 3d) uses shaders under the hood. Yes, the Spatial Material and Canvas Material are ultimately just shaders.

**Comment by Torguen** [comment]
Well, maybe something broke, since that didn't happen in beta 1, it started happening in beta 2.

**Comment by akien-mga** [comment]
Is this still reproducible in the current 3.2 RC 1?

What GPU and GPU drivers are you using?

@clayjohn I seem to remember a PR where we discussed an increase in compilation time of the default shader (something like 12 ms to 70 ms or something), but I can't find it anymore. Do you remember what it was? It's likely related.

**Comment by Torguen** [comment]
This no longer happens in 3.2 RC 1.

**Comment by akien-mga** [comment]
Ah, good to know! Closing then.
