### ISSUE TITLE
Creating Android export template fails

### ISSUE THREAD

**Issue by xkenoma** [godotengine/godot#34477]
**Godot version:**
2a4c528d067826dd1af865c93c3dc945c9a0e196

**OS/device including version:**
Windows 10 64x

**Issue description:**
`C:\Build Godot\godot\platform\android\java>.\gradlew build --info
Initialized native services in: C:\Users\GoCrayons\.gradle\native
Found daemon DaemonInfo{pid=10468, address=[20075fda-61ef-43c3-8408-486eba4c81b1 port:61000, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1576818897201, context=DefaultDaemonContext[uid=ca3c7cf4-07cc-4585-a9e4-495d5d3a7a6c,javaHome=C:\Program Files (x86)\Java\jdk1.8.0_181,daemonRegistryDir=C:\Users\GoCrayons\.gradle\daemon,pid=10468,idleTimeout=10800000,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]} however its context does not match the desired criteria.
At least one daemon option is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=C:\Program Files (x86)\Java\jdk1.8.0_181,daemonRegistryDir=C:\Users\GoCrayons\.gradle\daemon,pid=7812,idleTimeout=null,priority=NORMAL,daemonOpts=-Xmx1536m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=ca3c7cf4-07cc-4585-a9e4-495d5d3a7a6c,javaHome=C:\Program Files (x86)\Java\jdk1.8.0_181,daemonRegistryDir=C:\Users\GoCrayons\.gradle\daemon,pid=10468,idleTimeout=10800000,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]

  Looking for a different daemon...
The client will now receive all logging from the daemon (pid: 14344). The daemon log file: C:\Users\GoCrayons\.gradle\daemon\5.1.1\daemon-14344.out.log
Starting 19th build in daemon [uptime: 2 hrs 17 mins 7.941 secs, performance: 93%, no major garbage collections]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file 'C:\Build Godot\godot\platform\android\java\settings.gradle'.
Projects loaded. Root project using build file 'C:\Build Godot\godot\platform\android\java\build.gradle'.
Included projects: [root project 'godot', project ':app', project ':lib']

> Configure project :
Evaluating root project 'godot' using build file 'C:\Build Godot\godot\platform\android\java\build.gradle'.

> Configure project :app
Evaluating project ':app' using build file 'C:\Build Godot\godot\platform\android\java\app\build.gradle'.
Creating configuration androidTestUtil
Creating configuration compile
Creating configuration apk
Creating configuration provided
Creating configuration api
Creating configuration implementation
Creating configuration runtimeOnly
Creating configuration compileOnly
Creating configuration wearApp
Creating configuration annotationProcessor
Creating configuration androidTestCompile
Creating configuration androidTestApk
Creating configuration androidTestProvided
Creating configuration androidTestApi
Creating configuration androidTestImplementation
Creating configuration androidTestRuntimeOnly
Creating configuration androidTestCompileOnly
Creating configuration androidTestWearApp
Creating configuration androidTestAnnotationProcessor
Creating configuration testCompile
Creating configuration testApk
Creating configuration testProvided
Creating configuration testApi
Creating configuration testImplementation
Creating configuration testRuntimeOnly
Creating configuration testCompileOnly
Creating configuration testWearApp
Creating configuration testAnnotationProcessor
Creating configuration debugCompile
Creating configuration debugApk
Creating configuration debugProvided
Creating configuration debugApi
Creating configuration debugImplementation
Creating configuration debugRuntimeOnly
Creating configuration debugCompileOnly
Creating configuration debugWearApp
Creating configuration debugAnnotationProcessor
Creating configuration androidTestDebugCompile
Creating configuration androidTestDebugApk
Creating configuration androidTestDebugProvided
Creating configuration androidTestDebugApi
Creating configuration androidTestDebugImplementation
Creating configuration androidTestDebugRuntimeOnly
Creating configuration androidTestDebugCompileOnly
Creating configuration androidTestDebugWearApp
Creating configuration androidTestDebugAnnotationProcessor
Creating configuration testDebugCompile
Creating configuration testDebugApk
Creating configuration testDebugProvided
Creating configuration testDebugApi
Creating configuration testDebugImplementation
Creating configuration testDebugRuntimeOnly
Creating configuration testDebugCompileOnly
Creating configuration testDebugWearApp
Creating configuration testDebugAnnotationProcessor
Creating configuration releaseCompile
Creating configuration releaseApk
Creating configuration releaseProvided
Creating configuration releaseApi
Creating configuration releaseImplementation
Creating configuration releaseRuntimeOnly
Creating configuration releaseCompileOnly
Creating configuration releaseWearApp
Creating configuration releaseAnnotationProcessor
Creating configuration testReleaseCompile
Creating configuration testReleaseApk
Creating configuration testReleaseProvided
Creating configuration testReleaseApi
Creating configuration testReleaseImplementation
Creating configuration testReleaseRuntimeOnly
Creating configuration testReleaseCompileOnly
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor
Parsing the SDK, no caching allowed
SDK initialized in 813 ms

> Configure project :lib
Evaluating project ':lib' using build file 'C:\Build Godot\godot\platform\android\java\lib\build.gradle'.
Creating configuration androidTestUtil
Creating configuration compile
Creating configuration publish
Creating configuration provided
Creating configuration api
Creating configuration implementation
Creating configuration runtimeOnly
Creating configuration compileOnly
Creating configuration wearApp
Creating configuration annotationProcessor
Creating configuration androidTestCompile
Creating configuration androidTestPublish
Creating configuration androidTestProvided
Creating configuration androidTestApi
Creating configuration androidTestImplementation
Creating configuration androidTestRuntimeOnly
Creating configuration androidTestCompileOnly
Creating configuration androidTestWearApp
Creating configuration androidTestAnnotationProcessor
Creating configuration testCompile
Creating configuration testPublish
Creating configuration testProvided
Creating configuration testApi
Creating configuration testImplementation
Creating configuration testRuntimeOnly
Creating configuration testCompileOnly
Creating configuration testWearApp
Creating configuration testAnnotationProcessor
Creating configuration debugCompile
Creating configuration debugPublish
Creating configuration debugProvided
Creating configuration debugApi
Creating configuration debugImplementation
Creating configuration debugRuntimeOnly
Creating configuration debugCompileOnly
Creating configuration debugWearApp
Creating configuration debugAnnotationProcessor
Creating configuration androidTestDebugCompile
Creating configuration androidTestDebugPublish
Creating configuration androidTestDebugProvided
Creating configuration androidTestDebugApi
Creating configuration androidTestDebugImplementation
Creating configuration androidTestDebugRuntimeOnly
Creating configuration androidTestDebugCompileOnly
Creating configuration androidTestDebugWearApp
Creating configuration androidTestDebugAnnotationProcessor
Creating configuration testDebugCompile
Creating configuration testDebugPublish
Creating configuration testDebugProvided
Creating configuration testDebugApi
Creating configuration testDebugImplementation
Creating configuration testDebugRuntimeOnly
Creating configuration testDebugCompileOnly
Creating configuration testDebugWearApp
Creating configuration testDebugAnnotationProcessor
Creating configuration releaseCompile
Creating configuration releasePublish
Creating configuration releaseProvided
Creating configuration releaseApi
Creating configuration releaseImplementation
Creating configuration releaseRuntimeOnly
Creating configuration releaseCompileOnly
Creating configuration releaseWearApp
Creating configuration releaseAnnotationProcessor
Creating configuration testReleaseCompile
Creating configuration testReleasePublish
Creating configuration testReleaseProvided
Creating configuration testReleaseApi
Creating configuration testReleaseImplementation
Creating configuration testReleaseRuntimeOnly
Creating configuration testReleaseCompileOnly
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor
Parsing the SDK, no caching allowed
SDK initialized in 0 ms
debug|native Gradle local properties file not found at C:\Build Godot\godot\platform\android\java\local.properties
debug|native No CMake version was specified in build.gradle. Choosing a suitable version.
debug|native Trying to locate CMake in local SDK repository.
debug|native - Downloading '3.6.4111459'.
debug|native Trying to locate CMake in PATH.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':lib'.
> Invalid revision: 3.15.19101501-MSVC_2

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s`
**Steps to reproduce:**

**Minimal reproduction project:**
N/A

**Comment by volzhs** [comment]
for 3.2, it was changed a bit.
https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html#building-the-export-templates

**Comment by xkenoma** [comment]
> for 3.2, it was changed a bit.
> https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html#building-the-export-templates

**Comment by xkenoma** [comment]
Still getting the same problem :(

`SDK initialized in 0 ms
debug|native Gradle local properties file not found at C:\Build Godot\godot\platform\android\java\local.properties
debug|native No CMake version was specified in build.gradle. Choosing a suitable version.
debug|native Trying to locate CMake in local SDK repository.
debug|native - Downloading '3.6.4111459'.
debug|native Trying to locate CMake in PATH.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':lib'.
> Invalid revision: 3.15.19101501-MSVC_2

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s`

**Comment by xkenoma** [comment]
I've fixed it :)

I'm not sure what the problem is exactly to be honest, but this is what I did:

I've downloaded this: https://cmake.org/files/v3.15/
Then I just updated the build.grade file with the appropriate cmake version: https://prnt.sc/qeibc1.
