### ISSUE TITLE
Attempt to disconnect signal 'popup_hide' while in emission callback.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#34471]
**Godot version:**
3.2.beta.custom_build. 981c6aa10

**OS/device including version:**
Ubuntu 19.10
**Issue description:**
Error
```
Attempt to disconnect signal 'popup_hide' while in emission callback. Use CONNECT_DEFERRED (to be able to safely disconnect) or CONNECT_ONESHOT (for automatic disconnection) as connection flags.
````
**Steps to reproduce:**
Try to connect signal(happens rarely) via Node dock
or
Create new node, and create/attach script to it
![jfile](https://user-images.githubusercontent.com/41945903/71231512-96748180-22ee-11ea-90eb-afbaa32cc49f.gif)

**Comment by FeralBytes** [comment]
I have also been seeing this in Godot 3.2Beta4

**Comment by qarmin** [comment]
via Node dock.
Seems like "Attach Node Script" popup and others have problem with signal popup_hide.
![Zrzut ekranu z 2019-12-20 06-06-01](https://user-images.githubusercontent.com/41945903/71231613-0a168e80-22ef-11ea-8f47-c9ff75039e7a.png)

**Comment by FeralBytes** [comment]
I planned to post back sooner, but it had seemed like the problem had disappeared. I finally got it to pop back up. I now suspect my issue may be different than the OPs issue. The issue presents it's self when I open a script of a button that has a built-in script. The error is below:
```shell
 core/object.cpp:1955 - Object was freed or unreferenced while signal 'timeout' is being emitted from it. Try connecting to the signal using 'CONNECT_DEFERRED' flag, or use queue_free() to free the object (if this object is a Node) to avoid this error and potential crashes.
```

**Comment by ndarilek** [comment]
Don't know if this is related, but I'm getting mega-spammed with this error. As in, if I redirect it to a file and let it run for a few seconds, the file is 85M:

```
ERROR: _disconnect: Attempt to disconnect signal 'tree_exiting' while in emission callback. Use CONNECT_DEFERRED (to be able to safely disconnect) or CONNECT_ONESHOT (for automatic disconnection) as connectio
n flags.
   At: core/object.cpp:1522.
```

This worked in Beta3. Bisecting to find where it broke, will report back once I've got it.

**Comment by ndarilek** [comment]
Again, not sure if these are the same issues, but my error is introduced here, 22637beb2ed625c3e43ab75ab5865b57d7470948:

```
22637beb2ed625c3e43ab75ab5865b57d7470948 is the first bad commit
commit 22637beb2ed625c3e43ab75ab5865b57d7470948
Author: Juan Linietsky <reduzio@gmail.com>
Date:   Tue Dec 17 10:43:18 2019 -0300
    Restore signal locking, for some reason missing.

```

**Comment by qarmin** [comment]
This commit prevent to delete signal if is still used, which is good and prevents from crashing and unexpected behaviour.
It is a little strange that this commit was introduced in beta stage.
You should fix your code or create issue if you are sure that this engine bug.

**Comment by ndarilek** [comment]
If it's an engine bug that's going to crash my code, then if this 
behavior remains, it should have the decency to point out *where* in my 
own code the crash originates. Otherwise, as implemented it's buggy, and 
breaks code that ran fine in 3.1.1, 3.1.2, and Beta3. Besides, I 
genuinely have no idea where to even begin fixing this. Where should I 
look for a problem whose cause I don't know, in code that works 
perfectly fine?

**Comment by ndarilek** [comment]
OK, so if I change my code to:

```node.connect("tree_exiting", self, "free", [], Object.CONNECT_DEFERRED)`

My errors go away. But can we please have a nicer way of flagging this than spamming 85 MB of error messages to the game console, and maybe at least a warning that this is in the GDScript subsystem? I've seen so many warnings/assertion failures like this that I generally assume they're internal failures, because more times than not that seems to be true. If this is caused by my code, then it should do a better job of indicating my code is at fault.

Thanks. Beta4 is working for me now with that change made.

**Comment by capnm** [comment]
> I generally assume they're internal failures

In general, you should avoid writing code that generates errors or warnings, even if it seems to be working.
