### ISSUE TITLE
Inappropriate automatic scrolling

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#34486]
**Godot version:**
3.2 beta 4 Mono

**OS/device including version:**
Win10 64 Home

**Issue description:**
When you edit the collision layers, the dock automatically scrolls down.

**Steps to reproduce:**
Edit the collision layers and masks by pressing the "..." button.
Observe in GIF.

![GIF](https://user-images.githubusercontent.com/19652075/71248047-44e1ec00-231a-11ea-85e7-f8305ce936ac.gif)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
I can't reproduce it
![FQ4mDJimN5](https://user-images.githubusercontent.com/2223172/71249339-3812c780-231d-11ea-8f8d-febeaf0cfedf.gif)
The inspector scrolls correctly to fit the popup.

**Comment by Torguen** [comment]
The fact is that the scroll of the dock should not move at all when the "..." button is pressed

Why does it move automatically?

**Comment by timothyqiu** [comment]
I also encoutered something similar in the Visual Script editor:

![demo](https://user-images.githubusercontent.com/372476/71250162-ed637080-2359-11ea-8f53-09b5fd924720.gif)

This is recorded on a HiDPI monitor. On a normal DPI monitor, it scrolls a much smaller amount.

**Comment by akien-mga** [comment]
Might be related to #34269 (and follow-up #34389).

**Comment by KoBeWi** [comment]
Most likely. Maybe the follow behavior should just be optional? The only benefit for the inspector is that you can scroll it using arrows.

**Comment by timothyqiu** [comment]
I just tried beta 3, not reproducible.

**Comment by Anutrix** [comment]
It happened to me too but only once. It worked fine after I restarted Godot though. It was a build of few days.
