### ISSUE TITLE
Godot 3.2 beta4 - Save_exr() doesn't works when res:// is used in the path output

### ISSUE THREAD

**Issue by RonanZe** [godotengine/godot#34490]
I've talk about this problem to Zylann. Seems to be a problem with this line of code:
int ret = SaveEXRImageToFile(&image, &header, utf8_filename.ptr(), &err);

He said: this line do a save with a fwrite in C and need to have a translation of res:// before

**Comment by felaugmar** [comment]
Shouldn't this be cherrypicked into 3.* ?

**Comment by Calinou** [comment]
@felaugmar The commit in question hasn't even been submitted in a pull request, hence its `[WIP]` suffix. I couldn't test it back then.

**Comment by YuriSizov** [comment]
This should be fixed in `master`, as we now use `FileAccess` to write to the path. The engine also uses this method for some internal, debugging purposes.
