### ISSUE TITLE
Gui size inconsistency

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#34501]
**Godot version:**
3.1.2.
**OS/device including version:**
Windows 10
**Issue description:**
1) Nodes don't fill the parent when flags are set for fill inside control/ container.
2) The middle child doesn't respect the size of its child (Label in the example), but when it's only Label size is kept.
**Steps to reproduce:**
1) Any GUI node as a child for a control/ container with set flags to fill.
2) HBoxContainer with Fill | Expand | Expand, Label in fill slot determines the size but as soon it's put in one level deeper the fill slot gets crushed and Label.text clips.
**Minimal reproduction project:**
The project has both problems.

[GuiBug.zip](https://github.com/godotengine/godot/files/3990833/GuiBug.zip)

**Comment by nezvers** [comment]
The current workaround is to use the button with custom style to have a Label on a ColorRect look. But now that's creating problems to create a system for keyboard/ gamepad focusing on buttons.

**Comment by bojidar-bg** [comment]
1. Size flags are interpreted by Containers; a non-container Control parent will not automatically size children with size flags.
2. Likewise, Controls do not care about the min_size-s of their children. In the specific example, the ColorRect might be replaced by a PanelContainer with StyleboxFlat or by a MarginContainer with all margins set to 0 and a ColorRect child with Expand size flags.

**Comment by nezvers** [comment]
That is too confusing and means that I need to have one or two extra nodes to be able to make same thing with just 2 nodes and multiply it in list scenario - (Control rebinding in my GameTemplate - https://github.com/nezvers/Godot-GameTemplate)

**Comment by groud** [comment]
All problems you describe here are in fact expected behaviors. Only containers care about their child's mine size and size flags.
I am right now working on a piece of documentation that should hopefully make this clearer.
