### ISSUE TITLE
Rigidbody. Number of contacts reported < 0?

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#34505]
**Godot version:**
3.X
**OS/device including version:**
Any?
**Issue description:**
It can be set -1? Or in editor settings not set min-max value?
This not critical, but ... strange.
Or if it set -1, then one substract from contacts reported? (Don`t know how ^_^)
If it set -X... unpredicteble logick results.

**Comment by SuperDIMMaX** [comment]
yep, just need some tweaks in editor - min value.
i missclick and not see "-" before number.

**Comment by Anutrix** [comment]
But I agree that it shouldn't be allowed to be negative.
