### ISSUE TITLE
Mono: Exporting to Mac from Linux & Windows fails.

### ISSUE THREAD

**Issue by exts** [godotengine/godot#34517]
**Godot version:**
3.2 beta4 (latest mac fix) + latest export templates

**OS/device including version:**
osx majave (mac mini)

**Issue description:**
After redownloading export templates again and testing, windows to mac and linux to mac exports do not work. Both say they cannot find the pck file.

```
Error: Could not load game data at path '.'. Is the .pck file missing?
```

**Steps to reproduce:**
1. https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4 follow updated instructions here
2. Create basic c# project
3. export release & debug builds for mac on linux and windows, then run them on mac.

**Comment by exts** [comment]
(CC: @akien-mga )

**Comment by akien-mga** [comment]
I have no idea why that would happen. macOS binaries and all templates were built from the same source. Any clue @neikeq?

**Comment by neikeq** [comment]
If no mistakes were made with the builds it may be some API portability breakage on macOS. I'll have a look.

**Comment by exts** [comment]
I'll retest the latest export tpz & macos editor executable download from the server today just to reconfirm this finding just to make sure it wasn't an error on my behalf. I'll retest on all platforms and export from all platforms while I'm at it.

**Comment by neikeq** [comment]
I just tried exporting from Mac to Windows and I could not reproduce this.

**Comment by exts** [comment]
@neikeq I'm still testing, after redownloading latest template files

**From Mac to Windows:**
- release [works]
- debug [works]

**From Mac to Linux:**
- release [TBD]
- debug [TBD]

**From Windows to Mac:**
- release [fails]
- debug [fails]

Error:
```
Lamontes-Mac-mini:MacOS lamonte$ ./ShortServe 
arguments
0: ./ShortServe
Error: Could not load game data at path '.'. Is the .pck file missing?
```

**From Windows to Linux:**
- release [TBD]
- debug [TBD]

**From Linux to Mac:**
- release [TBD]
- debug [TBD]

**From Linux to Windows:**
- release [TBD]
- debug [TBD]

I'll have this updated within the next 2 hours

**Comment by exts** [comment]
@neikeq @akien-mga alright, I redownloaded export templates for every platform and tested exporting the same project to each platform from each platform (win -> mac, win -> linux, mac -> win, mac -> linux, linux -> mac, linux -> windows)

Come to conclusion win -> mac and linux -> mac fails with the error

```
Error: Could not load game data at path '.'. Is the .pck file missing?
```

More details in my previous message. Also bonus errors on a few debug exports

**Comment by exts** [comment]
@akien-mga @hpvb @neikeq new update

Systems(s): MacOS 10.15.2 Catalina, Windows 10 (home? idk), Linux Ubuntu 19.04 - all 64bit OS.

# Exporting 

**mac** -> **mac** [release - **fail**], [debug - **fail**]
**mac** -> **win10** [release - **success**], [debug - **success**]
**mac** -> **linux** [release - **success**], [debug - **success**]

**win10** -> **win10** [release - **success**], [debug - **success**]
**win10** -> **mac** [release - **fail**], [debug - **fail**]
**win10** -> **linux** [release - **success**], [debug - **success**]

**linux** -> **mac** -> [release - **fail**], [debug - **fail**]
**linux** -> **linux** -> [release - **success**], [debug - **success**]
**linux** -> **win10** -> [release - **success**], [debug - **success**]

Difference: Exporting mac to mac fails now, even when changing execution permissions. :/

Is it a catalina issue? Or a Mac issue. I'm unsure.

**Comment by name-here** [comment]
Could it have anything to do with [this](https://support.apple.com/en-us/HT208436)?  Is it working on systems running Mac OS versions before 10.15?

**Comment by Calinou** [comment]
@name-here Godot now only supports 64-bit on macOS, so that shouldn't be the issue.

**Comment by exts** [comment]
@akien-mga @neikeq @hpvb and the error that I can only get spit out is the same one in the original post, sorry I forgot to mention that bit:

`Error: Could not load game data at path '.'. Is the .pck file missing?`

I can't get it to give me anything else when trying to run the executables on mac.

**Comment by akien-mga** [comment]
Just to be sure that the problem is with Mono, can you try the classical 3.2 beta5 builds to check that it works fine on macOS?

**Comment by exts** [comment]
@akien-mga yeah sure I'll test classic

**Comment by neikeq** [comment]
I also get the pck not found error at the start. I don't know why this happens yet, but moving the pck from the Resources folder to the Godot executable folder fixed it.

Now there's another issue, which is the assembly `System.Native` not being found. Apparently the mono config file doesn't include this fix: https://github.com/godotengine/build-containers/commit/65e94a9acbfaee78ce66893d5e0d521f1d166040

There is one more issue I have to fix: both data folders for debug and release are exported.
Also the data folder is not renamed to the correct name (`data_Godot` or `data_AppName`) when exporting, so Godot can't find it.

**Comment by akien-mga** [comment]
> Now there's another issue, which is the assembly System.Native not being found. Apparently the mono config file doesn't include this fix: godotengine/build-containers@65e94a9

It should. Are you sure that you're checking 3.2 beta 5?
```
$ unzip ~/Downloads/Godot_v3.2-beta5_mono_osx.64.zip
$ cat Godot_mono.app/Contents/Resources/GodotSharp/Mono/etc/mono/config | grep native
        <dllmap dll="System.Native" target="$mono_libdir/libmono-native-compat.dylib" os="!windows" />
        <dllmap dll="System.Net.Security.Native" target="$mono_libdir/libmono-native-compat.dylib" os="!windows" />
        <dllmap dll="System.Security.Cryptography.Native.Apple" target="$mono_libdir/libmono-native-compat.dylib" os="osx" />
```

> There is one more issue I have to fix: both data folders for debug and release are exported.

That's #24299, was already the case in 3.1.x. But yeah that would be great to fix.

**Comment by bruvzg** [comment]
Both `ZIP` and `DMG` exports are extracting `data.mono.osx.64.release\Mono\...` AND `data.mono.osx.64.release_debug\Mono\...` to the exported `.app`, while Windows export only have one `Mono\...` folder, that's probably wrong.

**Comment by bruvzg** [comment]
`Error: Could not load game data at path '.'. Is the .pck file missing?` - this error is not mono specific, when you run executable directly and using relative path (e.g running it from terminal via `./exename` or terminal file manager like `mc`) Godot can't find PCK in the bundle resources, running `.app` bundle or executable from Finder or using absolute path should work.

**Comment by exts** [comment]
@bruvzg I've been able to do it in the past directly from the MacOS directory, especially for finding any errors and using finder _never_ opens the executable on b5. It'll instantly close.

**Comment by neikeq** [comment]
@akien-mga The Mono config for the Godot editor seems to be fine. But the one in the macOS export templates is definitely wrong.

I can confirm what @bruvzg says. Opening the game works with an absolute path to the executable. The `open` command works too.
I think Godot should still be able to find the pck even with relative paths. IMO it should probe for `executable_dir/../Resources/APP_NAME.pck`.

This issue can be closed once the macOS export templates are fixed (we can probably do a hotfix like we did with beta4).
I think we should also fix the one about not finding the pck, but that depends whether others agree it's a bug or not.

**Comment by bruvzg** [comment]
Currently, it's done by changing working dir to resource, but it's checking for path to start wiht `/` - https://github.com/godotengine/godot/blob/master/platform/osx/godot_main_osx.mm#L48-L70, probably it's better to move it to `Project Settings` and just add extra search path in `_setup`.

**Comment by akien-mga** [comment]
> The Mono config for the Godot editor seems to be fine. But the one in the macOS export templates is definitely wrong.

The one in the export templates would be from the `net_4_x` BCL I guess? Which is the Linux one.
Do we need a separate BCL for all desktop platforms? Or how should we handle the two `config`s on Linux and macOS in the same BCL?

**Comment by bruvzg** [comment]
> Both ZIP and DMG exports are extracting data.mono.osx.64.release\Mono\... AND data.mono.osx.64.release_debug\Mono\... to the exported .app

Seems like it should be renamed to `data_{APP_NAME}` - https://github.com/godotengine/godot/blob/master/modules/mono/godotsharp_dirs.cpp#L200, Linux and Windows export do rename it.

**Comment by exts** [comment]
yeah neikeq mentioend that one above

```
There is one more issue I have to fix: both data folders for debug and release are exported.
Also the data folder is not renamed to the correct name (data_Godot or data_AppName) when exporting, so Godot can't find it.
```

**Comment by akien-mga** [comment]
All issues should now be solved, but we'll have to test the next official build to confirm (the problem with the `config` file should normally be fixed now, but I'll double check when making the next build).

**Comment by exts** [comment]
@akien-mga cool, I'll test when it goes up

**Comment by exts** [comment]
Mac -> HTML **works**
Mac -> Mac **works** (debug+release)
Mac -> Mac DMG **works** (debug+release)
Mac -> Linux **works** (debug+release)
Mac -> Win **works** (debug+release)

Win -> HTML **works**
Win -> Win **works** (debug+release)
Win -> Linux **works** (debug+release)
Win -> Mac **works** (debug+release)

Linux -> HTML **works**
Linux -> Linux **works** (debug+release)
Linux -> Mac **works** (debug+release)
Linux -> Win **works** (debug+release)

I'll test android exports later this weekend when I get some time.

gj @neikeq @bruvzg @akien-mga

**Comment by akien-mga** [comment]
Thanks for the extensive testing!
