### ISSUE TITLE
Mono 3.2 beta2, cannot run new project, cannot open old project

### ISSUE THREAD

**Issue by colludium** [godotengine/godot#34521]
**Godot version:**
Mono 3.2 Beta 2

**OS/device including version:**
Windows 10 Pro x64  version 10.0.18362 

**Issue description:**
I am unable to open my old C# project - the editor flashes a list of failure lines in the console and then shuts down (most these are in the "open failure console warnings.txt" file). These are listed in the Output as

"modules/mono/mono_gd/gd_mono_utils.cpp:344 - System.DllNotFoundException: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)"

If I create a new project and create a node with a C# script and then run the scene the console shows the following:

" modules/mono/mono_gd/gd_mono_utils.cpp:344 - System.DllNotFoundException: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)
 editor/editor_node.cpp:5178 - An EditorPlugin build callback failed."

**Steps to reproduce:**

Open and attempt to run the project.

**Minimal reproduction project:**

[DoesNotRun.zip](https://github.com/godotengine/godot/files/3991648/DoesNotRun.zip)

**Comment by exts** [comment]
Have you tried beta 4?

**Comment by colludium** [comment]
@exts - damn, no, I'm out of date..! No bugs here....
