### ISSUE TITLE
Android Export with "*.import" export filter tries to export the same file multiple times resulting in an error.

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#34525]
**Godot version:**
3.2.3 Stable

**OS/device including version:**
Linux Mint 19.2
Kernel: x86_64 Linux 4.15.0-72-generic

**Issue description:**
"*.import" whitelist will try to export import files twice which causes jarsigner to fail.

**Steps to reproduce:**
Export to Android on the Project

**Minimal reproduction project:**
[Test1.zip](https://github.com/godotengine/godot/files/3991818/Test1.zip)

**Comment by akien-mga** [comment]
Regression from when? It's normal that exporting `*` exports everything. The include filter is specifically to give you full control instead of letting the engine figure out what's relevant.

**Comment by nathanwfranke** [comment]
Usually it isn't an issue, but for Android specifically when it tries to sign the same file many times it crashes. Also, it can be a usability problem because if you want to include an entire folder like Maps/* it would crash if there is even a single resource in that folder

**Comment by KoBeWi** [comment]
So why is this a bug? It's normal that `*.import` files are exported. The exported project doesn't include the `.png`, `.wav` etc. files, only their imported versions from the `.import` directory. The `.import` files are included, because they contain path to the imported resource.

**Comment by nathanfranke** [comment]
This should be a simple one to fix- it's possible for the build to try to export the same resource multiple times. The files exported should probably be stored in a set rather than a list. I might try to fix this now, give a few days.

**Comment by nathanfranke** [comment]
I could be wrong, I will try to reproduce this since looking at my original issue is confusing.

**Comment by nathanfranke** [comment]
Reproducible:
```
  signing: assets/icon.png.import
  signing: assets/icon.png.import
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: assets/icon.png.import
ERROR: _export_project_to_path: Failed to export the project for platform 'Android'.
   At: editor/project_export.cpp:984.
```
