### ISSUE TITLE
Android Export corrupts apk file 

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#3452]
It seems after exporting an apk of the same game a few times in debug when you change export to release it corrupts the apk file. Here is the logcat of the parse https://gist.github.com/carlosmarti/3c2c75ec6ef44fd00b02

**Comment by freemanfromgodotengine** [comment]
I have been exporting apks debug and release many times and never got corrupted apk release from Godot. Can you describe how to reproduce this step by step?
Which version of Godot do you work with and what android devices you test your apk's on?

**Comment by carlosmarti** [comment]
I add the custom apk that i made (i have both debug and release). I export like you would normally do, I first exported debug about 12+ times and then i added release into my project and then added the release keystore. When i exported it seems to have corrupted the project. The apk file would still parse even without the custom templates. The file size had the same size as with my custom debug template. Even though it should have shrunk a little bit. I suspect it holds on to the custom debug template even though i am telling it, It's release. 

My Device: Moto g 2nd gen, android 5.1
godot version: 2.0

**Comment by reduz** [comment]
sounds like a bug with release mode

**Comment by reduz** [comment]
this was a buildsystem bug in azure, it's been fixed there so closing this.
next beta/rc will have working android templates again
