### ISSUE TITLE
FeedImage enum has duplicate values

### ISSUE THREAD

**Issue by Waridley** [godotengine/godot#34534]
**Godot version:** 3.2 (source code/docs/generated gdnative api)

**Issue description:** FEED_RGBA_IMAGE, FEED_YCBCR_IMAGE, and FEED_Y_IMAGE all have the value 0

https://github.com/godotengine/godot/blob/e21872f4b9798c14b2840f205eff7aa931f02c0d/servers/camera_server.h#L53-L60

This does not appear to be intentional, as it does not seem like these image types should have the same value.

**Comment by qarmin** [comment]
Duplicate of https://github.com/godotengine/godot/issues/29857

**Comment by Waridley** [comment]
Oops, I made the mistake of only searching open issues. Thanks.
