### ISSUE TITLE
Process Priority behavior opposite of documentation

### ISSUE THREAD

**Issue by spencewenski** [godotengine/godot#34531]
**Godot version:**
3.2 beta 4

**OS/device including version:**
Windows 10 Pro version 1903 build 18362.535

**Issue description:**
The documentation tool-tip in Godot says, "Nodes with a higher process priority will have their processing callbacks executed first." However, the observed behavior is the opposite; nodes with a lower process priority are executed first.

**Steps to reproduce:**
1. Node1 has Process Priority of 0
2. Node2 has Process Priority of 1
3. Both nodes have the same script that just prints its name + the number of times executed
4. Run the project
5. Observe that Node1 always executes first instead of Node2 even though Node2 has a higher process priority (1) than Node1 (0)

**Minimal reproduction project:**
[ProcessPriorityDemo.zip](https://github.com/godotengine/godot/files/3992155/ProcessPriorityDemo.zip)

![Screenshot 2019-12-21 21 09 10](https://user-images.githubusercontent.com/3319370/71317550-b95e7d00-2437-11ea-985e-53e96f940889.png)

![Screenshot 2019-12-21 21 22 45](https://user-images.githubusercontent.com/3319370/71317574-296d0300-2438-11ea-9451-af276d715392.png)

**Comment by capnm** [comment]
> The documentation tool-tip in Godot says, "Nodes with a higher process priority will have their processing callbacks executed first."

IIRC this is only related to processing signal callbacks.
