### ISSUE TITLE
OpenGL ES 2 shadows.

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#34530]
**Godot version:**
Testing from 3.1 to last night build
**OS/device including version:**
Windows 10 x64 with integrated Intel HD
Windows 10 x64 with integrated Radeon HD 3650m
**Issue description:**
OpenGL ES 2. Shadows bugs. Pic from integrated Intel HD. DirectionalLight
![image](https://user-images.githubusercontent.com/22836285/71316731-1c770080-2486-11ea-85db-c4b9173c07dc.png)
Seems only one shadow created. Other objects no have shadows.
OmniLight
![image](https://user-images.githubusercontent.com/22836285/71316745-7c6da700-2486-11ea-9154-d6e0f362a62d.png)
shrange, OmniLight work in 90deg.

run with Mesa For Windows x64 version 19.2.7 
![image](https://user-images.githubusercontent.com/22836285/71316713-bc805a00-2485-11ea-8a0b-30a3ac86a83f.png)
no bug O_O
I try all posible settings.
And sometims if run - black screen when shadows on. (if reproduce this bug, update post)
On Radeon - testing 3.1, 3.2 - black screen when shadows on.
This bug on integrated graphics Intel and Radeon. Nvidia 730m - ok. Web - ok

**Comment by clayjohn** [comment]
If it's only affecting your Intel device then it is most likely a driver bug.

Have you updated your Intel graphics drivers recently?

**Comment by SuperDIMMaX** [comment]
No, samiliar i see on Radeon.

in Unity forum have samiliar problems and i see

> I was about to say that perhaps the GPU doesn't support stencil buffer (since that is needed for shadows i think)

and remember Radeon on Godot 3.0.6, and several next version show errors in log - direction shadow framebuffer is invalid.
Now i not have this notebook, but last version 3.1 or 3.2 (not remember) - no errors in log

I search in google and many people have problems with Intel graphics. (no shadows OpenGL)
I think problem in GL_EXT... (extentions) Godot use not exist OpenGL function in 2.0. probality shadows use some func from OpenGL 3.3 or... example: GL_EXT_texture_array - it broken in severals video cards with some drivers [GL_EXT_texture_array] (https://feedback.wildfiregames.com/report/opengl/feature/GL_EXT_texture_array)
in [Radeon 3650](https://feedback.wildfiregames.com/report/opengl/device/Mobility%20Radeon%20HD%203650)
Mobility Radeon HD 3650 (Windows):6.14.10.11653 - works
Mobility Radeon HD 3650 (Windows):6.14.10.11672 - works
Mobility Radeon HD 3650 (Windows):6.14.10.11672 - works
Mobility Radeon HD 3650 (Windows):6.14.10.74156.   14.10.7417 - broken
Mobility Radeon HD 3650 (Windows):6.14.10.7659 - broken
Mobility Radeon HD 3650 (Windows):6.14.10.7769 - broken
Mobility Radeon HD 3650 (Windows):6.14.10.8787 - works

see strange? 6.14.10.11672 - works - next driver 74156 - no works

Driver theoretical can "fix" that, but if video card not support some functions - drivers "fix" that like as i fix - use opengl.dll from Mesa For Windows x64 version 19.2.7 - software emulate. Like DX11 emulate on DX10... deep problem not in drivers. problem in some GL_EXTentions.... i think.

**Comment by SuperDIMMaX** [comment]
If it be Vulcan... yep, Update driver can help. OpenGL 2? This version OpenGL exist 
long before Windows 10

**Comment by Calinou** [comment]
The Radeon HD 3000 series is very old and no longer supported by AMD. Since most engine contributors don't have access to such hardware, we can't fix bugs that occur when using it, even in the GLES2 renderer.

**Comment by SuperDIMMaX** [comment]
Testing HD first series and 3000.
I know, this old graphics card, and not super critical problem, but if this bug is depended on incurrect Godot render - it may be a problem. example - on behavior how AMD and Intel graphics card / diver works. And how i say, if theorical graphics card support OpenGL features, this in theoretical must work. (what different bitween godot 2 and 3 render, if v2.x - use ES2.0 and v3.x use ES2.0 ? )
Question - this problem based on... videocard OpenGL ext. , or how graphics card works, or Godot render? If it - render <->how graphics card works(AMD and Intel), then problem can suspect on new GPU from AMD and Intel with last drivers. If OpenGL<->graphics card, then problem based on drivers. (see upper post - "see strange? 6.14.10.11672 - works - next driver 74156 - no works") - not allways new driver work property. and theorical you can get not working render on new GPU / drivers. Now render works on mostly GPU, but tomorrow...

If you think this bug -  very old GPU - you can close this issues, but if it - not property render...
Web version work fine. (but it use google ANGLE to translate (yes?))

**Comment by SuperDIMMaX** [comment]
who draw shadow depends on object position.
testing in ubuntu - all ok.

**Comment by clayjohn** [comment]
@SuperDIMMaX Based on what you are saying, the issue lies completely with your graphics drivers so it is not something that we can fix. This is why you are having trouble with Godot and with Unity. Ubuntu uses Mesa drivers so that is why shadows are working on Ubuntu. 

> Upd3. - i bugreport this, because it very, very strange bug. i can undestand if i not see all shadows(GPU not support some GL_EXT), but... one shadow exist... if GPU can draw shadow - GPU can work with shadows and this GL function... i don`t see any logic reason why only one shadow. Render draw on buffer one shadow and in next shadow... what? what happening? buffer becomes read only? or... list of shadow clipped to 0(1 object). and why Omni works 1/4 (90deg).

It is indeed concerning that it would draw one shadow only. But this is sometimes the sort of thing that happens with driver bugs. You often get undefined behaviour rather than outright errors or crashes. 

Unfortunately with driver bugs like this we really can't do anything to help.

**Comment by SuperDIMMaX** [comment]
i fix that.... 
![image](https://user-images.githubusercontent.com/22836285/71384310-a2638a80-25f1-11ea-96b7-706aa8134ffb.png)
