### ISSUE TITLE
to_json loses float precision

### ISSUE THREAD

**Issue by bluenote10** [godotengine/godot#34541]
**Godot version:** 3.1.2.stable.official

**OS/device including version:** Linux (Ubuntu 18.04)

**Issue description:**

Storing floating point values with `to_json` loses precision.

I would have expected `to_json` to always store full information, so that a serialization/deserialization round-trip is guaranteed to be lossless. If lossy representation is desired for size reduction, it could be passed as a flag `lossy_flots` like `to_json(data, true)`.

Note: The problem applies to recursive application of `to_json` as well, which makes manual work-arounds on user side difficult, e.g. in a situation where a high level object is to be serialized, but a deeply nested float must be stored in full precision.

**Steps to reproduce:**

```gdscript
# To check actual precision of floats:
print("%.16f" % PI)
print("%.16f" % (1.0 / 3.0))

# Results after going through `to_json`
print(to_json(PI))
print(to_json(1.0 / 3.0))

# Round-trip test
print("%.16f" % (PI - parse_json(to_json(PI))))
```
Outputs:
```
3.1415926535897931
0.3333333333333333
3.141593
0.333333
-0.0000003464102067
```

**Minimal reproduction project:** Let me know if needed...

**Comment by Xrayez** [comment]
I'm not completely sure but this issue may also be resolved by #33241 as it likely has to do with how floats are "stringified" vs "being written with `VariantWriter`" (aka `var2str`).
