### ISSUE TITLE
Position2D is using .global_position as a relative coordinate and position is....

### ISSUE THREAD

**Issue by codercommand** [godotengine/godot#34549]
**Godot version:3.1.2**

**OS/device including version:Windows 10**

**Issue description:**
I've found a bug or I don't understand this... Position2D is using .global_position as a relative coordinate to its parent, and position as its global coordinate.

**Steps to reproduce:**
I have a sprite (the sprite can move about) with a Position2D as its child.
The following code causes my projectile to spawn at the location relative to the sprite
*projectile.position = $Sprite/LaunchLocation.global_position*

This code causes the projectile to spawn at the global location on the scene.
*projectile.position = $Sprite/LaunchLocation.position*

I would expect it to be the other way around. I hope someone has an answer, thank you.

**Comment by wingedadventurer** [comment]
The behaviour you're getting is intended.

`global_position` tells where any 2D node is located **in the world**. If you go and spawn a projectile, and place it at `LaunchLocation.global_position`, it will spawn at the `LaunchLocation`.

`position` tells where any 2D node is located **relative to its parent 2D node**. Think of it as "offset from the parent". If you spawn a projectile, and place it at `LaunchLocation.position`, it will likely spawn somewhere in top-left corner of world origin (which is `(0, 0)`).

Let's say your `Sprite` node is positioned at `(200, 100)`. Its `global_position` is the same `(200, 100)`.
You then add `LaunchLocation` as its child, and place it about 50 pixels to the right from the `Sprite`.
Its `global_position` would be `(250, 100)`. However its `position` would be `(50, 0)`, which is its position relative to its parent (`Sprite`).

What about `Sprite.position`? Assuming its parent is some main world `Node2D` that you didn't move from the origin, `Sprite.position` would then be the same as `Sprite.global_position`.

Hope this clarifies it for you.

**Comment by KoBeWi** [comment]
The above comment explains it (somewhat). You should use
```
projectile.global_position = $Sprite/LaunchLocation.global_position
```
if you want to go with `global_position`.

Next time make sure it's really an issue with Godot by asking at [other community channels](https://godotengine.org/community).
