### ISSUE TITLE
[Mono] DynamicObject needs a reference in .csproj file

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#34546]
**Godot version:** v3.2.beta4.mono.official

**OS/device including version:** Windos 10 Pro

**Issue description:**
To use the `DynamicObject` feature added in 3.2 we need to reference `Microsoft.CSharp` in the generated `.csproj` file.  
I'm not quite sure if this is platform dependent or not.

**Steps to reproduce:**
* Create a C# script and add this to its `_Ready()` method:
```csharp
dynamic parent = GetParent().DynamicObject;
```
* Compile and get an error
```
error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
```
* Add this reference line to your `.csproj` file
```xml
<Reference Include="Microsoft.CSharp" />
```
* Compile and everything should work fine

**Comment by neikeq** [comment]
If you want to use `dynamic` you have to add a reference to `Microsoft.CSharp`. This has always been the case in C# AFAIK.

**Comment by paulloz** [comment]
@neikeq yeah. But as Godot is managing the `.csproj` file, maybe there should be a project settings option to handle that? Or at least we should note that it's going to need to be documented.

**Comment by neikeq** [comment]
We could make it possible to edit references. Also maybe in the future, when we use Roslyn, we could detect usage of `dynamic` and suggest adding the reference. In any case that would be a feature request.

**Comment by paulloz** [comment]
Noted, sorry I forgot there was a _new_ repo for that.  
In the meantime I'll mention it in the docs.
