### ISSUE TITLE
"Attempt to disconnect signal 'changed' while emitting" when zooming Script Editor.

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34548]
**Godot version:**
3.2 beta4

**Steps to reproduce:**
1. Open script editor.
2. Hold Ctrl
3. Move mouse wheel to zoom
4.
![image](https://user-images.githubusercontent.com/2223172/71325324-7827a500-24eb-11ea-8787-12ed35428b1f.png)

**Comment by capnm** [comment]
At: core/object.cpp:1522
ERROR: _disconnect: Attempt to disconnect signal 'changed' while in emission callback. Use CONNECT_DEFERRED (to be able to safely disconnect) or CONNECT_ONESHOT (for automatic disconnection) as connection flags.

1x in all its new glory 8-)

**Comment by akien-mga** [comment]
It's not a regression, like other issues, it's a previously unnoticed unsafe behaviour which is now being flagged as such. The editor code which tries to disconnect the signal in its own callback should be fixed as advised.
