### ISSUE TITLE
LargeTexture doesn't work when passed as uniform to a fragment shader

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#34552]
**Godot version:**
3.2 beta 4

**OS/device including version:**
MXLinux19 64 bits

**Issue description:**
Large textures don't work when used from a shader using texture(sampler2D tex,vec2 uv) and get_data returns null.

**Steps to reproduce:**
Make a large texture and use it on a shader.(tested using GLES2)

**Minimal reproduction project:**
[LargeTextureTest.zip](https://github.com/godotengine/godot/files/3993185/LargeTextureTest.zip)

**Comment by clayjohn** [comment]
Can you post about your GPU? Older GPUs just don't support textures of a certain size.

**Comment by MightyPrinny** [comment]
does it work for you? It works if I just use TEXTURE instead of a uniform and the texture is small

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

I tried the project in a6d4484 and the texture appears empty. Not sure how to create a new one to test (in case it's an incompatibility).
