### ISSUE TITLE
rename node not in place

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3455]
![screenshot from 2016-01-26 16-21-41](https://cloud.githubusercontent.com/assets/6195060/12583007/29754edc-c449-11e5-9ce6-18b008c69634.png)
as shown in the picture when I rename a scene that I've imported I find the renaming box misplaced.

**Comment by neikeq** [comment]
Possible duplicate of #3353

**Comment by akien-mga** [comment]
Are you using a custom font for the editor, maybe with a different size than the default one? If so it would indeed be the same issue as #3353.

**Comment by neikeq** [comment]
I don't use custom font and I am still able to reproduce this issue. Perhaps it's not related to that.

**Comment by lordadamson** [comment]
No I don't use a custom font

**Comment by trollworkout** [comment]
i had this happening and it fixes itself after a while
