### ISSUE TITLE
Create New Resource Broken Beta 4

### ISSUE THREAD

**Issue by stickynoteme** [godotengine/godot#34557]
**Godot version:**
3.2 Beta4
**OS/device including version:**
Windows 32/64
**Issue description:**
When you click the create new resource button now all you are getting is a window with a single item in the list named, "resource"

More things may be broken, I went to create a tileset and this is where I got stuck as this is broken. When I opened a 3.1x project that already had a preexisting tileset I found that it is usable but you can not edit the tileset.  
**Steps to reproduce:**
Open Godot make scene click Create New Resource Icon
**Minimal reproduction project:**

**Comment by somnivore** [comment]
I'm not getting this issue in beta 4

**Comment by stickynoteme** [comment]
Here's a video of what I get with a fresh download of Beta 4 in a fresh project:
[Video_2019-12-23_194503.zip](https://github.com/godotengine/godot/files/3997140/Video_2019-12-23_194503.zip)

![Video_2019-12-23_194503](https://user-images.githubusercontent.com/43216581/71392575-57c81b00-25bd-11ea-9a92-afa2bc6a1168.gif)

**Comment by stickynoteme** [comment]
For reference here is the current stable 3.1 on the same system:
[Video_2019-12-23_195153.zip](https://github.com/godotengine/godot/files/3997147/Video_2019-12-23_195153.zip)
![Video_2019-12-23_195153](https://user-images.githubusercontent.com/43216581/71392681-cd33eb80-25bd-11ea-8265-2fa6dd267712.gif)

**Comment by TheFlamyy** [comment]
I'm also unable to recreate this issue. (Ubuntu)
https://streamable.com/fuusw

It could be a windows related issue(?)

**Comment by stickynoteme** [comment]
> 
> 
> I'm also unable to recreate this issue. (Ubuntu)
> https://streamable.com/fuusw
> 
> It could be a windows related issue(?)

Could be. I don't have a Linux system at the moment, but I've tried it on 6 very different windows 10 system [System hardware is very broad and covers a large spectrum of newer and older Intel, AMD, and NVIDIA so I seriously doubt it's hardware related. They are all windows 10 64 Pro that's about the only commonality between them.] with the same result.

**Comment by stickynoteme** [comment]
I deleted everything in the:
Users\AppData\Roaming\Godot
folder on each system and that seemed to fix the issue. 
So my guess is that this is a result of some left over files or settings from an older version of godot that cause issues in the current betas based on the fact that all of the systems I tested have all had godot 3.0x, 3.1x 3.2x used on them so they could have all easily had old settings.
