### ISSUE TITLE
Cannot compile mono version on MacOS

### ISSUE THREAD

**Issue by rafaelgdp** [godotengine/godot#34558]
**Godot version:** Master Branch Commit 56d44aaac96747d2311b11702598c2e65551f411

**OS/device including version:** MacOS Catalina 10.15.2. Mono JIT compiler version 6.4.0.198.

**Issue description:** Cannot compile mono version because Dictionary<string, string> does not contain a definition for "Duplicate" method. File path on source code: modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs, line 145.

**Steps to reproduce:** followed the usual scons commands from documentation to compile mono version.

**Minimal reproduction project:** compiling issue.

Here's a print of the error:

<img width="1805" alt="Screen Shot 2019-12-23 at 03 03 21" src="https://user-images.githubusercontent.com/9672536/71339012-cf9c3400-2530-11ea-82c1-a8c2f6578696.png">

**Comment by neikeq** [comment]
Try building with `mono_glue=no` and regenerating the glue.

**Comment by rafaelgdp** [comment]
@neikeq , I had compiled successfully with the mono_glue=no option. I don't know what the problem was exactly, but it is now compiling normally. I'm closing this issue.
