### ISSUE TITLE
Mouse_exited

### ISSUE THREAD

**Issue by Lev227** [godotengine/godot#34556]
Trying to set a command where upon mouse exiting an Area2D's CollisionShape2D (this Area2D does not move), it would execute. It works fine, most of the time, but if you swipe the mouse and cursor quickly across the screen, it'll catch my "dragged" Area2D onto the Area2D (that does not move), signal the body entered (which subsequently signals that my mouse has also entered, as this "dragged" Area2D is extremely minuscule), and not have the time to signal the mouse_exited.

Edit: V3.1.1

**Comment by Calinou** [comment]
@Lev227 Please provide more information according to the issue template, such as the Godot version you're using.

**Comment by clayjohn** [comment]
This needs to be filled out according the template. Further, it needs to include more information. As it stands now we can't understand what the issue is.
