### ISSUE TITLE
Additional lines drawn when using draw_polygon

### ISSUE THREAD

**Issue by TicklesTheBrain** [godotengine/godot#34568]
**Godot version:** Godot 3.2 Beta 3/4

**OS/device including version:** Windows 10

**Issue description:**
There are additional lines when drawing a concave polygon, that were not there in Beta 2 and all previous Godot versions

**Steps to reproduce:**
Draw a shape with a cutout shape inside it as a single concave polygon.
Or run the attached repro project.
Try the same in beta 3 and beta 2 and compare the results.

**Minimal reproduction project:**
[bug_repro_proj.zip](https://github.com/godotengine/godot/files/3995787/bug_repro_proj.zip)

Screenshots of repro project in Beta 2
![image](https://user-images.githubusercontent.com/21967696/71372280-94474700-25bc-11ea-9832-cfc75a9c3976.png)
 And that same project in Beta 3 and beyond:
![image](https://user-images.githubusercontent.com/21967696/71372302-a923da80-25bc-11ea-8b8f-3e6e2398594f.png)

**Comment by MadEqua** [comment]
I ran a bisect and it seems this was introduced on this commit: 

https://github.com/godotengine/godot/commit/e6ebc43d725710f69094afa6ff47d91e50cce1ad?diff=unified#diff-e64fc7b93ef7deefed9e5978c3615901L825-L829

by drawing lines for AA using the indices. I'm not sure what to do, so I'll leave this here open for discussion.

**Comment by clayjohn** [comment]
CC @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment]
@TicklesTheBrain This case will be fixed with PR #34726. Note that you also need to disable hdr in your example project for antialiasing to work properly.
