### ISSUE TITLE
Some of inspector UI is hidden after editing Resource type export variable on Saved Custom Resource file.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#34560]
**Godot version:**
Godot 3.2 beta 4

**OS/device including version:**
Windows 10

**Issue description:**
Just as the title says. Some of the export variable is hidden.
This is the right inspector view:
![asli](https://user-images.githubusercontent.com/8316851/71343928-c7291500-2593-11ea-8a8e-4f5fe35c6515.jpg)
After clicking empty on Res variable and back.
![bug](https://user-images.githubusercontent.com/8316851/71343960-dd36d580-2593-11ea-909d-6713da42a927.jpg)

**Steps to reproduce:**
- Open project below.
- double click new_resource.tres file so that it open in inspector. Inspector should be like this:
![asli](https://user-images.githubusercontent.com/8316851/71343928-c7291500-2593-11ea-8a8e-4f5fe35c6515.jpg)
- press the [empty] on Res variable so that the resource type list appear.
- discard/cancel the list by clicking outside of it.
- now look the inspector is missing something, like this:
![bug](https://user-images.githubusercontent.com/8316851/71343960-dd36d580-2593-11ea-909d-6713da42a927.jpg)
- The string field is disappear from inspector view.

**Minimal reproduction project:**
[InspectorBug.zip](https://github.com/godotengine/godot/files/3994074/InspectorBug.zip)

**Comment by timothyqiu** [comment]
I think the variable is automatically scrolled out of view instead of being hidden, the same as [what I encountered](https://github.com/godotengine/godot/issues/34486#issuecomment-567884829) in #34486.

**Comment by KoBeWi** [comment]
This is weird, because there's no scrollbar. But yeah, it might be related because in master the whole inspector goes blank.
