### ISSUE TITLE
This weird underline when i code keeps appearing 

### ISSUE THREAD

**Issue by Drawsi** [godotengine/godot#34562]
So whenever i have a problem with my code, this "_" keeps appearing instead of my usual "I".
I don't know what causes this. When i type something to rewrite some code, it replaces the old code with the new code instead of adding to it.
Please help me, i do not have much experience with this software. 
Thank you.
![Screenshot (2)](https://user-images.githubusercontent.com/36633561/71359723-34d64080-2596-11ea-9085-c3ede54e0e52.png)
![Screenshot (3)](https://user-images.githubusercontent.com/36633561/71359724-356ed700-2596-11ea-82e5-d3674a3e43e9.png)

**Comment by smt923** [comment]
if you press your insert key does it fix this? I think this isn't a godot issue specifically, there's those two modes that you can switch between with insert

**Comment by FlashDaggerX** [comment]
This is just insert mode. When you enter insert mode, you can work with the character the cursor is sitting under. I'm not sure if it can do much else.

**Comment by Calinou** [comment]
To avoid confusion, we could disable this behavior by default like in Visual Studio Code. Most people never use the replace mode intentionally in my experience :slightly_smiling_face:

**Comment by Drawsi** [comment]
> if you press your insert key does it fix this? I think this isn't a godot issue specifically, there's those two modes that you can switch between with insert

YES! Thank you! Thank you soo much!
Have a great day,week,month and holiday!

**Comment by akien-mga** [comment]
> To avoid confusion, we could disable this behavior by default like in Visual Studio Code. From what I've seen, most people never use the replace mode intentionally slightly_smiling_face

This should be discussed at godot-proposals. Most text editors I've used have and support insert mode, so I'm not sure disabling it would be good.

Closing as the initial issue was a misunderstanding.

**Comment by VictorB884** [comment]
![afbeelding](https://github.com/user-attachments/assets/30d065b0-bd02-4c53-92d4-3c539b94aed3)
insert key
