### ISSUE TITLE
C++11 and Godot

### ISSUE THREAD

**Issue by primesoftware** [godotengine/godot#3456]
Is Godot tolerant to the C++11 standard? It seems Windows, Linux, Android, iOS, and Mac all support C++11 (at least the newer versions) so I was wondering if it was ok to write modules using it.

**Comment by akien-mga** [comment]
You can write modules using it as far as I know, but it's not used in the main code base (by choice AFAIK).

**Comment by reduz** [comment]
For modules i can't see why not. Godot does and will not use C++11 in the
near or medium future

**Comment by primesoftware** [comment]
Awesome! I just wanted to make sure I wasn't going against any design standards / requirements by the Godot team.
