### ISSUE TITLE
VehicleBody behaves weirdly with CollisionPolygon

### ISSUE THREAD

**Issue by 2tefan** [godotengine/godot#34567]
**Godot version:** 3.1.2.stable

**OS/device including version:** Manjaro / Windows 10

**Issue description:** When using a VehicleBody with a CollisionShape everything works perfectly. But if I use a CollisionPolygon everything works normally in the editor, but when I export the project, I can't really steer and the Vehicle just moves forward. And if I replace the CollisionPolygon with a CollisionShape everything works normally again.

**Steps to reproduce:** 
1. Create a VehicleBody with some (4) wheels.
2. Add a CollisionPolygon.
3. Export the game to any platform and run it.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by angad-k** [comment]
Added a cuboidal collision polygon in place of the collision shape and exported the project.  Could control the car in the exported just as I could in the editor.

**Comment by KoBeWi** [comment]
Closing as resolved. If you can still reproduce in Godot 3.2.4 rc3 or newer, comment with a reproduction project.
