### ISSUE TITLE
Crash when focus is lost during changing name of node that's decorating external scene

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3457]
1. We have inherited scene, or we are editing instance of external scene with 'Editable children' 
2. We are adding new scene instance to one of the children possessed by inherited scene.
3. Click on recently added scene, in the way like we would like to change it's name.
4. Click with your mouse on **another node** in scene tree tab to lost 'change name' focus
5. Godot will crash.

Note that we can normally change the name of this node if we will accept it with keyboard 'enter' key

Tested in e4cb104e6daa9c2e5781535ac8790f406ae53f08 commit
Video for quick judge: https://youtu.be/orM0doUT_JU 
Sample project: [CrashOnNameChange.zip](https://github.com/godotengine/godot/files/105100/CrashOnNameChange.zip)

**Comment by Hinsbart** [comment]
mhh, I can't see to be able to reproduce this using your example project. Renaming the "TestCube" node using focus loss did not crash for me.

**Comment by kubecz3k** [comment]
@Hinsbart are you on the newest Godot?

**Comment by kubecz3k** [comment]
@Hinsbart Thanks for the tip, to recreate this bug we need to actually click on other node in scene tree

**Comment by Hinsbart** [comment]
@kubecz3k ok, that did it. Can confirm it's crashing when clicking on another node
