### ISSUE TITLE
Cannot Tween the region_rect of a Sprite2D

### ISSUE THREAD

**Issue by acedogblast** [godotengine/godot#34575]
**Godot version:** 3.1.2

**OS/device including version:** Linux x86_64 bit

**Issue description:** Cannot Tween the region_rect of a Sprite using either interpolate_method() or interpolateproperty()

**Steps to reproduce:** Create a Sprite and Tween node. Add script to root node:
```
extends Node2D
func _ready():
        $Tween.interpolate_property($Sprite, "region_rect", $Sprite.region_rect, Rect2(0,0,0,0),5.0 , Tween.TRANS_LINEAR, Tween.EASE_IN_OUT, 0.0)
	$Tween.start()
	yield($Tween, "tween_all_completed")
	pass
```
**Minimal reproduction project:**
[project](https://drive.google.com/file/d/1oxaZw8KUBcjhnJIFHKX-yi95USWZWsww/view?usp=sharing)

**Comment by volzhs** [comment]
![image](https://user-images.githubusercontent.com/8281454/71391931-8db2e100-2649-11ea-95e8-f076d6cb63f4.png)
```
E 0:00:00:0445   Invalid param type, except(int/real/vector2/vector/matrix/matrix32/quat/aabb/transform/color)
  <C Source>     scene/animation/tween.cpp:1004 @ _calc_delta_val()
  <Stack Trace>  Node2D.gd:4 @ _ready()
```

for further information, `Tween.interpolate_property` seems not to support for `Rect2`

**Comment by Jedi18** [comment]
Can I be assigned this issue to add support for Rect2 for interpolate_property?

**Comment by volzhs** [comment]
go ahead :+1:
