### ISSUE TITLE
GLES2 Strange shading on far distances

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#34573]
**Godot version:**
3.2 beta 4

**OS/device including version:**
Android phone Alcatel One

**Issue description:**
Only happens on an actual Android phone, there is a strange shading on far distances.
![StrangeShading2](https://user-images.githubusercontent.com/27329423/71385635-f61da600-25e8-11ea-94b8-2f448b242a8a.jpeg)
The "black zone" shouldn't be there.

**Steps to reproduce:**
Export to android with meshes far away form the camera

**Comment by clayjohn** [comment]
Looks like a duplicate of https://github.com/godotengine/godot/issues/34529

**Comment by Janders1800** [comment]
This bug happens even if there is no directional light in the scene

**Comment by clayjohn** [comment]
Thanks for clarifying!

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Janders1800** [comment]
The bug seems gone in stable

**Comment by akien-mga** [comment]
Thanks, closing.
