### ISSUE TITLE
setget is no longer working

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#34586]
**Godot version:**
3.1.2 >

**OS/device including version:**
Linux

**Issue description:**
setget command is no longer working, the value of var is correctly changing but the set function is not called.

**Steps to reproduce:**
```
var is_active : = false setget set_active, get_active

func _ready():
	is_active = true
	print(is_active)


func set_active(value : bool) -> void:
        print("test")
	is_active = value


func get_active() -> bool:
	return is_active
```

**Comment by Zylann** [comment]
This is where `self` comes into play. From within the script, if you want the setter to be called when setting the property, use `self.is_active = value`, or `set_active(value)`.

**Comment by grevius5** [comment]
no sorry, this is my fault! This is also written in the documentation, I totally missed it!

**Comment by grevius5** [comment]
no sorry, this is my fault! This is also written in the documentation, I totally missed it!
