### ISSUE TITLE
Duplicate area+collision shape causes a bug

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#34581]
**Godot version:**
3.2 beta3
**OS/device including version:**
ubutu 18.04
**Issue description:**
When you duplicate a area with a child of collision shape, and then modify the shape of the copy, the original one modify too.

**Comment by KoBeWi** [comment]
That's because Shape is a resource and when you duplicate the Area, both copies will share the same shape. To avoid this, make the shape unique by right-clicking it and using "Make Unique".

This is intended behavior.
