### ISSUE TITLE
Attach Node Script buttons are hidden

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#34591]
**Godot version:**
3.2 beta 4
**OS/device including version:**
Windows 10
**Issue description:**
![image](https://user-images.githubusercontent.com/28724859/71425602-7df4c600-2664-11ea-9742-c4c0cad4ef7b.png)

Changing the language to C# then back to GDScript results in this.  All the other languages appear to affected as well, except for C#.

![image](https://user-images.githubusercontent.com/28724859/71425609-a4b2fc80-2664-11ea-967a-0b9d77e5e1a6.png)
![image](https://user-images.githubusercontent.com/28724859/71425612-aed4fb00-2664-11ea-9b92-addf0ff0fc8d.png)

**Comment by Calinou** [comment]
I guess this is caused by the Built-in Script checkbox disappearing then appearing again.
