### ISSUE TITLE
Godot Input)

### ISSUE THREAD

**Issue by Conrim** [godotengine/godot#34599]
- v3.1.stable.offficial / Windows 10

- one Key isn't detected if you press left, up, right  at the same time (arrowkeys)

[bug report.zip](https://github.com/godotengine/godot/files/4000118/bug.report.zip)

**Comment by Zireael07** [comment]
Most likely, this is not Godot's fault, but a phenomenon known as "keyboard ghosting".

**Comment by KoBeWi** [comment]
^
This. It's a hardware problem.

**Comment by Conrim** [comment]
Thx
