### ISSUE TITLE
Editor Tabbing hotkeys for OSX

### ISSUE THREAD

**Issue by meniku** [godotengine/godot#346]
For OSX selecting next/previous tab should be possible with META+SHIFT+[ and META+SHIFT+] as it's default behaviour by all other applications

**Comment by akien-mga** [comment]
See also #2745 for a general-purpose feature request about hotkey listing and redefinition.

**Comment by djrm** [comment]
Oh, i already added tab switching, but only works with CTRL + TAB, im going to add configurable shortcuts or a custom case for OSX so this gets solved
