### ISSUE TITLE
it's  not possible to select a point on line.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#34600]
**Godot version:**
3.1.2

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**
1.add a Line2D
2.draw some points
<img width="361" alt="Screen Shot 2019-12-28 at 7 13 12 PM" src="https://user-images.githubusercontent.com/1130047/71444279-0f3e6800-274b-11ea-8de9-f49446a89dca.png">
3. drag point 3 onto the line
<img width="399" alt="Screen Shot 2019-12-28 at 7 13 31 PM" src="https://user-images.githubusercontent.com/1130047/71444289-254c2880-274b-11ea-8140-d8f83917bf0e.png">
4. now, it's impossible to select point 3
<img width="376" alt="Screen Shot 2019-12-28 at 7 14 01 PM" src="https://user-images.githubusercontent.com/1130047/71444294-2a10dc80-274b-11ea-8d17-1a3fe312055f.png">

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
It's possible, but you need to zoom in much.

**Comment by alexzheng** [comment]
I have zoom in to the maximus, it's still impossible.
It is treated as insert a point.

**Comment by KoBeWi** [comment]
![image](https://user-images.githubusercontent.com/2223172/71445122-45fa8b00-2717-11ea-9130-952cb4cc1397.png)
Although this is rather cumbersome.

**Comment by alexzheng** [comment]
Another cumbersome operation:
We can drag point 3 onto the line, but we can not add point 3 on the line directly, it will insert a point between the end points  of the line. 
It would be nice to ignore checking whether the mouse is on a line when the control or option button is hold down.

**Comment by KoBeWi** [comment]
Still valid in 3.2.3
