### ISSUE TITLE
AnimationPlayer signal OnFInished does not emmit

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#34608]
**Godot version:**
3.2 beta 4
**OS/device including version:**
ubuntu 18.04
**Issue description:**
Maybe this is intentional, but if your animation loops the signal onfinished doesnt emmit, if so a new type of signal is needed OnLoopFinished.
**Steps to reproduce:**
create a looping animation and register signal onFinished

**Comment by KoBeWi** [comment]
Yep, this just needs some `loop` signal. I've seen similar request about AudioStreamPlayer.

**Comment by avencherus** [comment]
Yes, would be nice.  I have to tread lightly and handle looping animations with special cases in code when using yields, since I can't easily know when they have ended.

**Comment by Jedzkie** [comment]
Confirmed this also, using 3.1.2

**Comment by golddotasksquestions** [comment]
Should this not be a proposal rather than a bug?
No _on_finished signal when looping is enabled sounds to me like perfectly expected behavior.

**Comment by KoBeWi** [comment]
Well, it is not labelled as a bug.

**Comment by golddotasksquestions** [comment]
@nonunknown You might want to submit this issue as proposal here: https://github.com/godotengine/godot-proposals

**Comment by bojidar-bg** [comment]
Might be related to #27509.

**Comment by golddotasksquestions** [comment]
There definitely should also be consistency with ``on_finished`` signal when a queue is playing (#27509). 
The more I think about it, the more I would find it consistent to have ``on_finished`` emitted at the end of the animation, no matter what (with or without active loop or queue). And then have a new signal ``on_queue_finished`` emitted at the end of the queue.

**Comment by akien-mga** [comment]
Seems like duplicate of #27509.
