### ISSUE TITLE
Need godot cpp compile for a lib

### ISSUE THREAD

**Issue by jaccen** [godotengine/godot#34601]
when i use gogot found can make a template or through Editor  for a user , but i  want to learn how to Make an engine, and rewrite some codes for my project，so how can i do the flows:
  1、how can i make a project for ios or android through godot cpp ;
  2 、how can i view the project codes  through Xcode or Adnroid Studio?

**Comment by groud** [comment]
Sorry, this is not the place to ask questions about how to use the engine, but to report bugs and ask for enhancements. Please use the other community channels for asking questions.
