### ISSUE TITLE
Sub Viewport interferes with Gizmos

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#34602]
**Godot version:**

3.1.2.stable.custom_build

**OS/device including version:**

Linux midova 5.4.6-arch1-1 #1 SMP PREEMPT Sat, 21 Dec 2019 16:34:41 +0000 x86_64 GNU/Linux

**Issue description:**

When instancing a 3D scene under a ViewportContainer, type-specific gizmos (light/camera/etc.) are invisible.

**Steps to reproduce:**

1. Set up the following tree:

- Spatial
    - Camera

2. Instance the scene from 1 in the following tree

- ViewportContainer
    - Viewport
        - Spatial (instanced)

3. Select the `Spatial` or `Camera` in the second scene
4. Note that there is no camera-gizmo (the purple box that shows where the camera points).
   There _is_ still the standard 3D gizmo.

**Minimal reproduction project:**

Reproes in the [multitouch cubes demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/multitouch_cubes) on current master (c34a2b423bcbf5134dbccb0836c0da33696621a2).
![1577278019](https://user-images.githubusercontent.com/2496231/71445943-6f51f180-26ec-11ea-910d-7ab634555be7.png)

**Comment by KoBeWi** [comment]
Seems fixed in 3.2

**Comment by rcorre** [comment]
Confirmed fixed in 3.2.3. Thanks!
