### ISSUE TITLE
3D CPU-Particles preprocess doesn't work

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#34610]
**Godot version:**
3.2 beta 4

**OS/device including version:**
Zorin OS 15 (Ubuntu 18.04)

**Issue description:**
CPU-Particles preprocess doesn't work, particles should start as if has been running for the specified seconds (don't start from zero).

**Steps to reproduce:**
Add CPU-Particles to a scene change preprocess property.

**Comment by clayjohn** [comment]
#40369 duplicates this issue, but includes an MRP, so I am closing this in favour of it. 

Closed in favour of #40369
