### ISSUE TITLE
Autoloads and Signal Consumption

### ISSUE THREAD

**Issue by lexwraith** [godotengine/godot#34616]
**Godot version:**
3.1.2

**OS/device including version:**
Ubuntu 16.04

**Issue description:**
Autoloaded scenes can't seem to emit signals

**Steps to reproduce:**
Suppose I have an autoloaded Scene called `TimerProducerSingleton`:

```
extends Node

func _ready():
    $Timer.one_shot = true
    $Timer.start(1)
```

and a consuming scene called Consumer1

```
extends Node2D

func _ready():
    $Label.text = 'Hello world!'

func _on_TimerProducerSingleton_timeout():
    $Label.text = 'Received the timer signal!'
```

On running the Consumer1 scene, nothing seems to happen. In the script, it can auto complete and even call on the references to the singleton's methods, but implicit or explicit `emit_signals` don't seem to ever reach it. Calling `connect` manually (which doesn't seem like it would be best practice as it would mean every scene would need to do some kind of registration with all singletons) didn't seem to work either. Clicking on the timer node to connect signals in the GUI does not show other scenes. The docs here: https://docs.godotengine.org/en/3.1/getting_started/step_by_step/singletons_autoload.html

don't seem to apply to this situation.

Could be missing something though; pretty new to Godot. I'm trying to create more of a 'service' in domain driven design terms, e.g. `HTTPService` that all scenes can call via autoload but also subscribe to for signals.

**Minimal reproduction project:**
See above

**Comment by bojidar-bg** [comment]
Have you connected the `_on_TimerProducerSingleton_timeout` method in any way? The connect dialog makes saves the connections in the scene which are then deserialized, it does not just create a function on a script.

Doing something like this in the second script might work:
```gdscript
func _ready():
    TimerProducerSingleton.get_node("Timer").connect("timeout", self, "_on_TimerProducerSingleton_timeout")
    #... $Label.text = 'Hello world!'
```

**Comment by lexwraith** [comment]
So just to be clear here, once a scene 'registers' it is listening to a signal from a service and binds a method to it, does that registration hold between scenes? Can we declare that in the GUI somewhere, or does it have to be in code?
