### ISSUE TITLE
when trying to click on sliders to change value the slider disappears

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3461]
![screenshot from 2016-01-26 20-44-46](https://cloud.githubusercontent.com/assets/6195060/12590889/edfea4dc-c46d-11e5-8abd-4d83dc43328a.png)

So I'm under the impression that I can left click and drag that slider to change value right? nope, it just disappears and the value remains the same.

**Comment by akien-mga** [comment]
I can confirm this, I've noticed it too recently but forgot to report it.
