### ISSUE TITLE
Lag hiccup in first instance of a preloaded scene with CPUParticles

### ISSUE THREAD

**Issue by rafaelgdp** [godotengine/godot#34627]
**Godot version:** 3.2 custom build (commit 318c69351624f7794c51b5385d252af397c0404a)

**OS/device including version:** MacOS Catalina 10.15.2. MBP 2018.

**Issue description:** I am using GDScript for all scripting. I made a custom scene with CPUParticles to be instantiated whenever a spell hits an enemy. The enemy scene preloads this "SpellEffect" scene inside its script. After the animation is finished, it queues free from memory. The problem is that the first time this scene is instantiated, the game freezes for a brief moment. All the subsequent instantiations are totally smooth (lag-free).

**Steps to reproduce:** Create a custom scene with CPUParticles and preload it inside another scene, add as a child to a visible scene, and emit the particles. The game will lag for a brief moment. All subsequent instantiations are lag-free.

**Minimal reproduction project:** If I have the time and it's necessary, I'll make a minimal reproduction project eventually as the main project I am making is for a game jam.

**Comment by rafaelgdp** [comment]
For further context. I Googled this issue and found [this thread](https://godotengine.org/qa/50936/preloading-scenes-seems-not-to-work). However, all the answers seem pretty hacky and I am not sure what the right approach should be.

**Comment by clayjohn** [comment]
This is caused by shaders compiling. It is a known issue that will be solved in 4.0. this thread contains some tips to fix that https://github.com/godotengine/godot/issues/13954
