### ISSUE TITLE
My own graphic benchmark between Godot and Unity.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#34628]
**Godot version:**
Godot 3.1.2 windows 64 bits

**OS/device including version:**
Windows 7 64 bits.
GPU = geforce 210
RAM = 4 GB
CPU = E8500

**Issue description:**
I made the same basic test on both unity and godot (a simple rotating mesh on top of a plane with a skybox background).
Unity so far has better graphics (At least post processing stack options) and performance (not sure, but unity runs a bit smoother).
So far it seems my real performance issue is that the GLES 3D performance using Ubuntu default repos nvidia driver (the one you get from the add controllers window, drivers 340) are quite poor, by a lot.
On windows the performance is a lot better, but still couldn't get a documented way to import an hdi skybox from google, there wasn't a clear tutorial on it, nor the documentation had any proper explanation and the tutorials on youtube used 2.1 version with some plugin. Is not as easy as unity where you simply drag and drop it and import into the camera.
Also, GLES 2 lacks proper post processing options, but that's not a real issue since they appear on GLES 3.
Also, couldn't get the default albedo and normal map textures properly imported into Godot, from PBR materials I got from google.
Downloaded a couple of PBR materials, but Godot couldn't understand the png or jpg or the picture, even while re saving on windows paint and paint net as diferent format.

GLES 2 video of my test:
https://twitter.com/ca3studio/status/1210422119923953664
GLES 3 video:
https://twitter.com/ca3studio/status/1210420996097921025
GLES 3 Linux test:
https://twitter.com/ca3studio/status/1208325552249212928

The issue with the Linux test is that is a diferent project, using simpler meshes and the textures were made by hand on GIMP, trying to make PBR textures by hand, on windows I used zbrush for the mesh and Substance Painter for the PBR textures of the dice.

Unity test on windows:
https://twitter.com/ca3studio/status/1210342158059917312

**Steps to reproduce:**
I followed this tutorial with unity on how to improve graphics:
https://www.youtube.com/watch?v=jrgN_71s_Go

**Minimal reproduction project:**
Unity project:
https://github.com/ca3games/Unity/tree/master/Graphic%20Test

Godot project:
https://github.com/ca3games/Godot/tree/master/3.2%20alpha/graphic%20test

**Comment by clayjohn** [comment]
What is the bug that you are reporting? 

Also, the post-processing options have been added to GLES2 in 3.2

**Comment by ca3games** [comment]
> What is the bug that you are reporting?
> 
> Also, the post-processing options have been added to GLES2 in 3.2

Dunno where really to put it, since is not a bug report nor a feature requested.
Still reduzio asked me on twitter to post my results.

**Comment by aaronfranke** [comment]
@ca3games Typically one would post such things on a social media site, such as Twitter, Reddit, or YouTube, depending on the type of content. You can also share links on the other platforms if you make a post on one.

But also, these kinds of benchmarks aren't really useful to the Godot developers right now because the renderer is being rewritten to use Vulkan in Godot 4.0, which will have very different results.

**Comment by Calinou** [comment]
Indeed, as @aaronfranke said, I'll close this issue since it's not actionable as it is right now.
