### ISSUE TITLE
integer division warning fails

### ISSUE THREAD

**Issue by Salvakiya** [godotengine/godot#34623]
Godot version: 3.2

OS/device including version: Windows

Issue description: Godot fails to warn when doing integer division in some cases

Steps to reproduce: consider the following...
```
	# No warnings... c = 0
	var a := 10
	var b = 20
	var c = a/b
	
	# No warnings... f = 0
	var d = 10
	var e = 20
	var f = d/e
	
	# No warnings... i = .5
	var g = 10.0
	var h = 20.0
	var i = g/h
	
	# Warning! integer division!
	var j := 10
	var k := 20
	var l = j/k
```
in any of these cases if the value is 0 it should be producing a warning when `integer division warning` is on.

- **in the case of C one is an integer and dividing of both results in an integer.**
- **in the case of F both are an integer and it results in an integer**
- in the case of I both are floats and it produces an expected result
- in the case of L both are integers and it produces an expected result

**Comment by Calinou** [comment]
> in any of these cases if the value is 0 it should be producing a warning when `integer division warning` is on.

How do other programming languages linters' proceed in this case? Do they also emit a warning in this case?

**Comment by bojidar-bg** [comment]
Actually, `b`, `d`, and `e` are not ints, as far as the warning system is concerned.
Consider the following code:
```gdscript
func _process(delta):
    var a := 10 # int
    var b = 20 # int?
    if delta > 0.12:
        b = 2.0 # float!
    else:
        b = 1.0 # float!
    var c = a / b # int / int? int / float?
```
Until the GDScript compiler gets some SSA support (which would help it realize that `b` cannot have an integer value at the last line), we cannot reliably raise warnings for untyped division.

**Comment by akien-mga** [comment]
So it seems like it's working as expected, no? CC @vnen

**Comment by vnen** [comment]
Yeah, this is working as intended. Like @bojidar-bg said, we could keep track of actual type and value in the parser to throw warnings in those cases. But in the current state we can't, so the warning only happens for typed variables.

**Comment by Salvakiya** [comment]
why not make all number values floats unless typed to an integer?

**Comment by vnen** [comment]
Floats and ints have different semantics. Float can lose precision on higher values and has special values such as NaN and infinity. We expect the programmer to use what's needed, so Godot can't just force the type of the value.

**Comment by jluini** [comment]
I'm doing an integer division on purpose and having the warning.
How should I proceed? Am I forced to disable the warning or use the #warning-ignore trick?
Thanks!

**Comment by vnen** [comment]
> How should I proceed? Am I forced to disable the warning or use the #warning-ignore trick?

You can disable per project, per file, or per line, it's up to you to decide.
