### ISSUE TITLE
WebSocketClient issue

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#34631]
**PLATFORM**
Linux Mint 19.3
Godot 3.2 Beta 4

**ISSUE**
I think something is broken with the WebSocketClient of Godot since i cant seem to be able to send any data to the server from my project. I also tested this with @Faless [WebSocketChat](https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo) demo and in that case the client just disconnects right after the connection is established.
Some notes:
- Using [Simple Websocket client](https://addons.mozilla.org/en-US/firefox/addon/simple-websocket-client/) for firefox connects and sends the messages as expected
- In my project, using `client.get_connection_status()` inside `send_message` returns 0 (the client is disconnected) **BUT** inside `_process` it returns 2 (connected)
- `assert(_client.get_peer(1).put_data(someData) == OK)` returns 1 (Generic error) instead of 0 
![image](https://user-images.githubusercontent.com/1850856/71513389-d0232a80-28a2-11ea-9983-88ff8dc2f93d.png)

**SAMPLE PROJECT**
[WebSocketChat](https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo)

**Comment by Faless** [comment]
What version of Godot are you running? I also see an error (red) in the debugger tab, would be nice if you could post the error too

**Comment by zaksnet** [comment]
> What version of Godot are you running? I also see an error (red) in the debugger tab, would be nice if you could post the error too

Sorry forgot the mention the version -_-. Its the latest Godot 3.2 Beta 4. I'm not sure about the error (probably some missing signal connection i had messed with) and i have deleted the test project folder so i cant test it :/. But i just tested with a fresh download of [WebSocketChat](https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo) and there is no error in the debugger tab but the issue remains.

**Comment by Faless** [comment]
@zaksnet can you run the project in verbose mode? (project -> project settings -> debug -> settings -> `Verbose Stdout`) and see if any socket error pops out? Is it possible that port `8000` is already in use in your machine and the server fails to start?

**Comment by zaksnet** [comment]
Nope, no errors:
![image](https://user-images.githubusercontent.com/1850856/71521158-34a4b080-28c8-11ea-881a-17da1bc8edac.png)
The server is running as far as i can tell and from my project i could connect using [Simple websocket client](https://addons.mozilla.org/en-US/firefox/addon/simple-websocket-client/). But now:
![image](https://user-images.githubusercontent.com/1850856/71521468-a2051100-28c9-11ea-86f0-a74da3614bea.png)

**Comment by zaksnet** [comment]
Also, just noticed these:
![image](https://user-images.githubusercontent.com/1850856/71521535-e4c6e900-28c9-11ea-8164-b3116c7080a2.png)

**Comment by zaksnet** [comment]
@Faless , the connection was refused because of the protocols. If i change them to an empty array it is fine. That brings us to my main issue with my project, let me see if i can replicate it with the chat application

**Comment by zaksnet** [comment]
Nope, 100% my fault. Messy code, everything works fine, sorry for the trouble!
