### ISSUE TITLE
NetworkedMultiplayerENet.create_server() does not work with max_clients=4096

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#34636]
**Godot version:** 
3.1

**OS/device including version:** 
Ubuntu 18.04

**Issue description:**
The docs say that 4096 is the highest acceptable number for max_clients.
(https://docs.godotengine.org/en/3.1/classes/class_networkedmultiplayerenet.html#class-networkedmultiplayerenet-method-create-server)
Actually it is 4095. With 4096, networking just silently stops working, no connections are accepted and no error message is logged.

Also interesting: This number is NOT concurrent connected clients, but total connection attempts. If I start a server with max_clients=4 and then connect and disconnect 4 times with the same client, the server will not accept any more connections.

**Steps to reproduce:**
	host = NetworkedMultiplayerENet.new()
	host.create_server(self.LISTEN_PORT, 4096) 

Then try to connect.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
> Also interesting: This number is NOT concurrent connected clients, but total connection attempts. If I start a server with max_clients=4 and then connect and disconnect 4 times with the same client, the server will not accept any more connections.

This sounds like a bug to me, if not a security issue (due to denial of service).

**Comment by ScyDev** [comment]
Indeed!

**Comment by Faless** [comment]
Yep, ENet limit is 4095, should be fixed in the docs.

**Comment by Faless** [comment]
> Also interesting: This number is NOT concurrent connected clients, but total connection attempts. If I start a server with max_clients=4 and then connect and disconnect 4 times with the same client, the server will not accept any more connections.

This I'm unable to reproduce, please provided a minimum reproduction project.
Works as expected for me.

**Comment by Calinou** [comment]
@Faless It makes sense to print an error message when trying to listen with more than 4095 clients too.

**Comment by ScyDev** [comment]
@Faless Ah, I guess my error in thinking might have been that I (by accident) created 4 concurrent clients, and never closed the existing connection. Therefore I was actually exhausting the max number of connections. 

I just tested it again, after making sure the connection is actually closed, and I can connect more than  4 times successfully. So that's alright.
