### ISSUE TITLE
error: on this platform, thread can be renamed only with calls from the threads to be renamed

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3463]
this error comes up every time i test my game.

OSX El Capitan 
Godot BETA 32 bit 

C Error: Method function failed: ERR_UNAVAILABLE
C Source: drivers/unix/thread_posix.cpp
C Function: set_name

**Comment by akien-mga** [comment]
Is this the full error load?

**Comment by trollworkout** [comment]
@akien-mga  Is a constant error in Godot Engine. I originally thought it was from testing the game but it also happens when the engine loads. It gives a crash report every time I test the game.

That's all the details I could find.

**Comment by akien-mga** [comment]
But what is the exact error message? It's a bit hard to know if it's what you put in the issue title or the lines that start with "C", or both.

**Comment by trollworkout** [comment]
@akien-mga  i copied exactly what i see on the screen

![screen shot 2016-01-26 at 4 32 42 pm](https://cloud.githubusercontent.com/assets/6987027/12595640/75264038-c44a-11e5-9eb9-7fb14bca14ae.png)

**Comment by trollworkout** [comment]
overtime i test my app i get this report error dialogue  because that error is consistently happening in the background ? I have no idea.

![screen shot 2016-01-26 at 4 33 45 pm](https://cloud.githubusercontent.com/assets/6987027/12595676/a276ae74-c44a-11e5-9614-0a74ee6046cf.png)

**Comment by punto-** [comment]
it's because there's a call to rename a thread somewhere (probably the
audio thread), and osx and ios can't rename a thread that is not the
calling thread itself. It shouldn't cause any crash..

**Comment by trollworkout** [comment]
@punto-  Is not a crash. Is more like an annoyance. It gives me a crash report every time I do anything in Godot.

**Comment by trollworkout** [comment]
may be related with the audio crash bug

**Comment by jackmakesthings** [comment]
Can confirm, I've been seeing the same error in the debugger as screenshotted above. It doesn't appear immediately, but shows up the first time I try to run a scene (any scene) and persists as long as the program's open. This is happening in the latest build from this repo, on Mac OS X 10.9.5 (Mavericks).

**Comment by punto-** [comment]
How late is your latest build? This should be fixed by my commit from
yesterday

**Comment by trollworkout** [comment]
I can't test it cause I don't compile and build my own Godot Engine atm. if someone else can test this on mac OR you could leave it open and wait until next release then close it.

**Comment by trollworkout** [comment]
@punto-  this bug is fixed i can confirm on osx in the latest build that i just compiled myself today

**Comment by trollworkout** [comment]
i'll leave you the pleasure of closing this

**Comment by akien-mga** [comment]
Thanks for cheking :)

**Comment by trollworkout** [comment]
@akien-mga i  got you dawg :+1:

**Comment by trollworkout** [comment]
@akien-mga @punto-   this error still happens sometimes just rarely or almost not at all. so there is some other thread that's doing a similar thing . i consider the matter closed for now.
