### ISSUE TITLE
TileSet Editor automatically resets the view

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#34639]
**Godot version:**
3.2.beta4

**OS/device including version:**
Solus Gnome

**Issue description:**
When working in the TileSet Editor interface, every action automatically resets the view, making it extremely annoying to work with.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10171059/71524417-39f40200-28ac-11ea-882e-bc82c58fb917.gif)

**Steps to reproduce:**
1. Create a TileSet Editor
2. Add a relatively big Texture to it
3. Optionally zoom in the texture to have more precision
4. Try to make an Auto Tile
5. View resets

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Looks like another issue caused by #34269 .-.

**Comment by henriiquecampos** [comment]
> Looks like another issue caused by #34269 .-.

Yeah I felt like it had to do with the scrolls, but I didn't know how to describe it. Should I change the title?
