### ISSUE TITLE
The bomber demo HTML5 output does not run on IIS

### ISSUE THREAD

**Issue by nrcionline** [godotengine/godot#34635]
3.1.2 stable win64 (windows 10 1909)

For the bomber demo, exporting to HTML5 does not run when using IIS (microsoft's Internet Information Server). But reports:

Failed loading file 'Bomb.pck': Not Found

(output program named "Bomb" and saved as "Bomb.html", "Bomb.js", "Bomb.pck", etc.)

If this line: 			const MAIN_PACK = 'Bomb.pck';
is changed to 			const MAIN_PACK = '.\Bomb.pck';
Then it passes further, but stops with:
Failed loading file '.wasm': Not Found

Does IIS need configuring in order to run the output? Is there any help file that goes through these steps?

**Comment by akien-mga** [comment]
Can you provide the exported project files?

Does it work in 3.1.1-stable?
If so, do you use a Custom Html Shell in your export preset? If so you need to update it to take into account changes in 3.1.2-stable (see #32448).

**Comment by nrcionline** [comment]
![Bomb](https://user-images.githubusercontent.com/32943620/71823794-2132db80-3066-11ea-84b3-a8305a4d8472.png)


Here are the files. I used the default settings (didn't change anything). I only have the latest version installed.

**Comment by Zireael07** [comment]
Nope, there's only a png.
IIRC for multiple files you have to zip them

**Comment by nrcionline** [comment]
[bomb.zip](https://github.com/godotengine/godot/files/4026431/bomb.zip)

**Comment by akien-mga** [comment]
It seems to run fine with a python `SimpleHTTPServer`, so the issue seems indeed specific to IIS.

**Comment by Faless** [comment]
> so the issue seems indeed specific to IIS.

Yes, a quick googling suggests IIS does not specify a mime type for `.wasm` files. It needs to be configured.
Closing as it's not a godot bug.

**Comment by nrcionline** [comment]
I'm not convinced that's the only problem because it also complains about the .pck file and if I alter the path, then it finds the file. Even if it's not a "bug" - there needs to be documentation for how to configure a webserver so that it works without making assumptions. Hasn't anyone every testings godot with IIS?

**Comment by nrcionline** [comment]
In my system, I already have this defined:
.wasm application/wasm Local
and it doesn't work
So how should IIS be setup to handle .pck and .wasm files? I don't understand. Even if it's not a bug, can someone help?

**Comment by nrcionline** [comment]
If this isn't the right place to post this for some help, where should I post it?

**Comment by Faless** [comment]
@nrcionline the `.pck` is a binary file, so you can specify it as `application/octet-stream`.

**Comment by Faless** [comment]
For general support, you can try the official [Q&A](https://godotengine.org/qa/).
The official web export tutorial [also mention the mime-type](http://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_for_web.html#serving-the-files) configuration.

**Comment by nrcionline** [comment]
I will try the Q&A, but after I added the .pck mime type, it get:
Unable to get property 'getParameter' of undefined or null reference

**Comment by Faless** [comment]
Also please note that the multiplayer bomber demo will not work as expected in HTML5 exports (although it should load) because it uses a UDP connection, which is not supported by browsers. I'll add a line to explicitly mention that in the class documentation, though it's still mentioned in the [web export limitations](http://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_for_web.html#unimplemented-functionality)
