### ISSUE TITLE
FileSystem dock and search cannot find some folders/files

### ISSUE THREAD

**Issue by rafaelgdp** [godotengine/godot#34646]
**Godot version:** 3.2 custom build 318c69351624f7794c51b5385d252af397c0404a

**OS/device including version:** MacOS Catalina. MPB 2018.

**Issue description:** Some folders/scene files cannot be found from within the Editor FileSystem dock/Editor search tool. However, they are there and I can open them by clicking on Scene > Open Scene. They are all recognizable files, like .tscn. This does not make any sense.

**Steps to reproduce:** This is the first time this happened, I don't know how to reproduce from a blank project.

**Minimal reproduction project:** I cannot share my current project because it is for a game jam and I haven't noticed this behavior in other projects.

Some screenshots:

<img width="1533" alt="Screen Shot 2019-12-28 at 03 01 34" src="https://user-images.githubusercontent.com/9672536/71539728-701e9980-291f-11ea-8e6a-7d70d7b74b9e.png">
<img width="1301" alt="Screen Shot 2019-12-28 at 02 59 02" src="https://user-images.githubusercontent.com/9672536/71539731-76ad1100-291f-11ea-8be2-0ecd23bc54da.png">

As you can see, the ui folder within the scenes folder is completely hidden, but still there.

**Comment by bojidar-bg** [comment]
Does it still happen after an editor restart?

**Comment by KoBeWi** [comment]
Why there's `project.godot` in that folder? Godot automatically ignores folders like that, because it treats them as sub-projects.

**Comment by rafaelgdp** [comment]
> Why there's `project.godot` in that folder? Godot automatically ignores folders like that, because it treats them as sub-projects.

This was the cause of this issue. I was not aware of this detail. My fault! When I deleted this out-of-place `project.godot` file and restarted the editor, everything came back to normal. Closing.
