### ISSUE TITLE
HTML5 build error with Emscripten 1.39.5: 'timestamp' undefined, should be replaced by emscripten_get_now()

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#34648]
**Godot version:** Git 318c69351624f7794c51b5385d252af397c0404a

**OS/device including version:** Fedora 30, Emscripten 1.39.5

**Issue description:** I get a build error when compiling for HTML5:

```text
Compiling ==> platform/javascript/os_javascript.cpp
platform/javascript/os_javascript.cpp:315:28: error: no member named 'timestamp' in 'EmscriptenMouseEvent'
                uint64_t diff = p_event->timestamp - os->last_click_ms;
                                ~~~~~~~  ^
1 error generated.
shared:ERROR: '/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=5 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/emscripten/system/include -Xclang -isystem/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/root/.emscripten_cache/wasm-obj/include -c -std=c++11 -Os -fno-exceptions -fno-rtti -Wall -Werror=return-type -DJAVASCRIPT_ENABLED -DUNIX_ENABLED -DNO_THREADS -DNO_SAFE_CAST -DJAVASCRIPT_EVAL_ENABLED -DNDEBUG -DPTRCALL_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DFREETYPE_ENABLED -DSVG_ENABLED -DHAVE_MNTENT -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/javascript -I. -DEMSCRIPTEN platform/javascript/os_javascript.cpp -fno-inline-functions -Xclang -isystem/builds/Calinou/godot-builds-ci/godot/emsdk/upstream/emscripten/system/include/SDL -c -o platform/javascript/os_javascript.javascript.opt.bc -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
scons: *** [platform/javascript/os_javascript.javascript.opt.bc] Error 1
scons: building terminated because of errors.
```

[Full build log on GitLab CI](https://gitlab.com/Calinou/godot-builds-ci/-/jobs/389971570)

**Steps to reproduce:** Build Godot with `scons platform=javascript`.

**Comment by creikey** [comment]
I'm getting a different error on arch linux:
```shared:ERROR: BINARYEN_TRAP_MODE is not supported by the LLVM wasm backend```

**Comment by creikey** [comment]
After changing like 139 in `platform/javascript/detect.py` from
```env.Append(LINKFLAGS=['-s', 'BINARYEN_TRAP_MODE=\'clamp\''])```
to
```env.Append(LINKFLAGS=['-s'])```

 the emscripten build runs successfully on release. Seems to be due to https://groups.google.com/forum/#!topic/emscripten-discuss/NpxVAOirSl4 , can be seen in imgui in this issue: https://github.com/ocornut/imgui/issues/2877

**Comment by creikey** [comment]
The release_debug build of webassembly also builds successfully on arch linux, maybe an outdated library on fedora?

**Comment by creikey** [comment]
I'm using emscripten `1.39.1`

**Comment by akien-mga** [comment]
What's the output of `grep EMSCRIPTEN_ROOT ~/.emscripten`?

**Comment by akien-mga** [comment]
@Calinou and @creikey's issues don't appear to be linked for the record.

**Comment by akien-mga** [comment]
For @Calinou's issue, it's because emscipten 1.39.5 broke compatibility again: https://github.com/emscripten-core/emscripten/blob/incoming/ChangeLog.md#v1395-12202019

**Comment by notmushroomoverhere** [comment]
I have the same error as @Calinou , @akien-mga what exactly do I replace with emscripten_get_now()?
Apologies, I am a little confused.

**Comment by akien-mga** [comment]
If I knew the issue would be fixed already :)

You should look up the code using `timestamp` in `platform/javascript` and figure out what to replace it with.
