### ISSUE TITLE
RPC {Method} is not allowed from {ID}. Mode is 0. Master is 1.

### ISSUE THREAD

**Issue by TheSporkBard** [godotengine/godot#34643]
**Godot version: v3.1.2.stable.offical**

**OS/device including version: Windows10, 1903**

Issue description: 

When trying to call a remote function with RPC i get the error message,

`ERROR: RPC 'newPlayer' is not allowed on node /root/Node from: 1. Mode is 0, master is 1.
   At: core/io/multiplayer_api.cpp:288`

I am having the same or a similar issue that the user Ghost was having in 2018, i have followed the recommendations in the comments of the post and i can't seem to fix the issue.

Ive attached the three scripts that i am running, note that the serverside script is running in a separate project, ill also add the code snippets here;

[serverside](https://github.com/godotengine/godot/files/4006640/serverside.gd.txt)
```
extends Node


const PORT        = 5000
const MAX_PLAYERS = 200
var players = [MAX_PLAYERS]
func _ready():
	var server = NetworkedMultiplayerENet.new()
	server.create_server(PORT, MAX_PLAYERS)
	get_tree().set_network_peer(server)
# warning-ignore:return_value_discarded
	get_tree().connect("network_peer_connected",    self, "_client_connected"   )
# warning-ignore:return_value_discarded
	get_tree().connect("network_peer_disconnected", self, "_client_disconnected")

func _client_connected(id):
	rpc_config("newPlayer", 1)
	players.append(id)
	print_debug('Client ' + str(id) + ' connected to Server')
	for i in players:
		if i != id:
			print_debug("calling new player, lets hope it works this time")
			rpc_id(i,"newPlayer", id)

func _client_disconnected(id):
	print('Client ' + str(id) + ' left the Server')

sync func _update_client_position(new_position):
	rpc_id(2,"_update_others_position", new_position)

#thought this might help 
remote func newPlayer(name1):
	pass
```
[clientside](https://github.com/godotengine/godot/files/4006641/clientside.gd.txt)
```
extends Node2D

func _ready():
	var network = NetworkedMultiplayerENet.new()
	network.create_client("127.0.0.1", 5000)
	get_tree().set_network_peer(network)
	network.connect("connection_failed",self,"_on_connection_failed")
	get_tree().multiplayer.connect("network_peer_packet",self,"_on_packet_received")
	set_network_master(get_tree().get_network_unique_id())
	var newPlayer = preload("res://Player.tscn").instance()
	newPlayer.set_name(str(get_tree().get_network_unique_id()))
	newPlayer.set_network_master(1)
	add_child(newPlayer)
	


func _on_connection_failed(error):
	$labelStatus.text = "Error connecting to server " + error

  
remote func newPlayer(name1):
	print("newplaycalled")
	var newPlayer = preload("res://Player.tscn").instance()
	newPlayer.set_name(str(name1))
	newPlayer.set_network_master(name1)
	add_child(newPlayer)
```
[playercontroller](https://github.com/godotengine/godot/files/4006639/playercontroller.gd.txt)
```
extends KinematicBody2D

var motion = Vector2()

func _physics_process(delta):
	#gonna need an if statment here 
	motion.x = 0
	motion.y = 0
	if Input.is_action_pressed("ui_left"):
		motion.x = -500
		#moved()
	if Input.is_action_pressed("ui_right"):
		motion.x = 500
		#moved()
	if Input.is_action_pressed("ui_up"):
		motion.y = -500
		#moved()
	if Input.is_action_pressed("ui_down"):
		motion.y = 500
		#moved()
	move_and_slide(motion)
	

#func moved():
	#rpc_id(1,"_update_client_position", position)

remote func _update_others_position(newPos, namei):
	if self.name != namei:
		position = newPos

```

**Comment by Calinou** [comment]
> I am having the same or a similar issue that the user Ghost was having in 2018

For future reference, @ghost isn't an actual person, it's a placeholder that takes the spot of deleted accounts :slightly_smiling_face:

**Comment by TheSporkBard** [comment]
Ah sorry about that

**Comment by Faless** [comment]
@TheSporkBard can you provide the reproduction project? The scene structure is important.

**Comment by TheSporkBard** [comment]
Ah, thank you for this but i've actually just fixed the problem, the problem i was having is that my scene root on client side was a blank Node, with the Node2D as a child, where the script was running. so it was running in the wrong place. Now the script is placed correctly it functions properly. thank you however.
