### ISSUE TITLE
Searching in project manager and clicking opens the wrong project

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#34645]
**Godot version:** 3.2 beta 4

**OS/device including version:** Xubuntu 18.04 LTS 64-bit

**Issue description:** When I search in the project manager, and then click on one of the results, it opens the wrong project. Clicking without searching works fine.

**Steps to reproduce:** https://www.youtube.com/watch?v=KutFjKN4pYc

As you can see in this video, I searched for "in", double-clicked on the Input Mapping GUI demo, and it opened the Rich Text Label demo, which is not what I clicked on.

I can't reproduce this issue in 3.1.1, so I think it's a regression.

**Comment by bojidar-bg** [comment]
Can't reproduce on 3.2 318c69351; can you make check if the ordering by "Last Modified" makes any difference?

**Comment by aaronfranke** [comment]
It seems that if I search, then change the sorting order, then click on a project, it always opens the incorrect one. I'm able to reliably reproduce this problem on my computer.

**Comment by dankan1890** [comment]
It seems to be an issue of how the selected items are indexed (the index always uses the full list of projects and not one displayed / filtered).
Probably introduced by this PR #30735, @Zylann can you take a look at it? :)

**Comment by Zylann** [comment]
This isn't an ItemList: when they are filtered the nodes are just hidden, they are still there, and their indexes should match the array. Yet something makes it not match...
