### ISSUE TITLE
Properties in the Inspector no longer have an icon showing what type they are.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#3464]
As the title says, there is no longer an icon next to the properties. I'm using the first 2.0 Beta that was uploaded to the website.
Here is a comparison of 2.0 Beta and the 1.1 Stable builds:
![godot](https://cloud.githubusercontent.com/assets/11450875/12592045/b7c9a842-c438-11e5-9128-4901ece86977.png)

**Comment by neikeq** [comment]
It was disabled by default, IIRC. You still can enable it from _Editor Settings -> Inspector -> Show Type Icons_ (I think it requires restarting the editor).

**Comment by trollworkout** [comment]
you can enable it i think i saw it in the editor preferences

**Comment by CowThing** [comment]
Oh alright, thank you. There is indeed an option to turn the icons back on.

**Comment by trollworkout** [comment]
@CowThing  next time just log in IRC freenode godotengine and just ask this to whoever is online is much faster than posting it as a bug plus you can confirm with others is a bug or not.
