### ISSUE TITLE
export3D models of a compiled project

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#34652]
english:
There is a way to export 3D models of a compiled project, for example in .exe, I want to create an application with Godot Engine that is possible to choose 3D models and then from the same program to be able to export them in .obj or collada format.

Some ideas or suggestions

spanish
Existe una forma de exportar modelos3D de un proyecto compilado,por ejemplo en .exe,quiero crear una aplicación con Godot Engine que sea posible elegir modelos3D y luego desde el mismo programa poder exportarlos en formato .obj o collada.

Algunas ideas o sugerencias
![Captura de pantalla_2019-12-28_09-45-12](https://user-images.githubusercontent.com/12847027/71545931-05497e80-2970-11ea-8e86-7ab5a066c153.png)

**Comment by Calinou** [comment]
Please open feature proposals on [godot-proposals](https://github.com/godotengine/godot-proposals) instead. Make sure to give some example use cases for your proposal too.
