### ISSUE TITLE
Animation Player + Blend Shapes bug

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#34658]
**Godot version:**
3.2 beta 4 
**OS/device including version:**
ubuntu 18.04
**Issue description:**
I Have 2 object crates (bounce crate) they are a box animated using shape keys, but when in the test scene the animation sometimes doesnt play , sometimes they play , and sometimes they play at the same time being different objects 
**Steps to reproduce:** and **Minimal reproduction project:**
download source files and play Lab.tscn and look for the bounce crate
https://github.com/nonunknown/crashcreator/tree/alpha

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by MJacred** [comment]
related to / duplicate of https://github.com/godotengine/godot/issues/38443?

**Comment by KoBeWi** [comment]
Well my question didn't get any reply, so closing this anyway.
