### ISSUE TITLE
Tilemap show flickering lines between grid when scale increased

### ISSUE THREAD

**Issue by iamrahul404** [godotengine/godot#34669]
**Godot version:**
3.2.beta4 
**OS/device including version:**
windows 10 with Nvidia mx150
**Issue description:**
I don't know is it because of Nvidia or something, but connecting lines between tiles flicker when we move around the map. (Scale is increased to 2-3) 
**Steps to reproduce:**
I am attaching the project zip, just run the TilemapTest scene and drive the car around. 
**Minimal reproduction project:**
[RacingTest.zip](https://github.com/godotengine/godot/files/4007839/RacingTest.zip)
![image](https://user-images.githubusercontent.com/25437077/71553397-f082ee80-2a34-11ea-9c81-3e3a2271857d.png)

**Comment by arkology** [comment]
It's not really a bug. Because the "filter" flag in the imported sprite is enabled.
Disable it or make another tileset with more space between tiles.

**Comment by iamrahul404** [comment]
Thanks  @arkology for a quick reply.
