### ISSUE TITLE
Connection error when using the ScriptCreateDialog

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#34661]
**Godot version:**
318c693

**Issue description:**
When creating/loading scripts with the ScriptCreateDialog, this error will appear:
```
Attempt to disconnect signal 'popup_hide' while in emission callback. Use CONNECT_DEFERRED (to be able to safely disconnect) or CONNECT_ONESHOT (for automatic disconnection) as connection flags.
```
Which is likely caused by it emitting the `script_created` signal while closing via either `_create_new()` or `_load_exist()`:
https://github.com/godotengine/godot/blob/318c69351624f7794c51b5385d252af397c0404a/editor/script_create_dialog.cpp#L269-L279

**Comment by qarmin** [comment]
Duplicate of #34471

**Comment by YeldhamDev** [comment]
Oh, didn't catch that one.
