### ISSUE TITLE
Invalid Audio Driver: PulseAudio error with pre-compiled 2.0 beta

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#3466]
Using the 2.0 beta downloaded from the website today (Ubuntu 15.10), if I load an old project that has

```
[audio]
driver="PulseAudio"
```

in the engine.cfg then the project fails to load, Godot exits, and I get a popup window that says:

`Invalid Audio Driver: PulseAudio`

If I remove the `driver` line from engine.cfg then the project loads and audio seems to work fine. If I compile Godot myself then `driver="PulseAudio"` works. Seems like the beta was compiled without PulseAudio support?

**Comment by akien-mga** [comment]
Did you build without pulseaudio support @reduz?

**Comment by Algrin6** [comment]
Building without pulseaudio support occurs automatically if pulseaudio development libraries
are not installed.

**Comment by reduz** [comment]
just erase that line from engine.cfg
I don't think that property should even be exported, this will change in
the future
