### ISSUE TITLE
Incorrect parsing of language server request headers

### ISSUE THREAD

**Issue by ofrank123** [godotengine/godot#34667]
**Godot version:**
3.2.beta

**OS/device including version:**
archlinux x86_64

**Issue description:**
Starting a message to the language server websocket with "Content-Length:" makes the server ignore the message.  This header is required by the the current lsp specification(3.14) and so it seems very odd to ignore it.  I believe this may be a shortcut taken to make it easier for the only current client implementation (the one for vscode) to communicate, but because it does not comply to the specification it is very confusing for a developer who is attempting to implement another client (I am currently trying to write one in emacs for lsp-mode, which sends headers the correct way).

**Steps to reproduce:**
Send a message to the language server (using a tool like websocat) starting with a "Content-Length: <size>" header.  There will be no output.

**Comment by Geequlim** [comment]
If you can seperate the header and body to two messages it should be fine. But it is not really follow the LSP specification.

https://github.com/godotengine/godot/blob/5fa1905131bc20e8a4a939d0edf8370091c88a50/modules/gdscript/language_server/gdscript_language_protocol.cpp#L44-L46

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Faless** [comment]
This is fixed since `3.2.2` where LSP has been ported to plain TCP instead of websocket: #35864
