### ISSUE TITLE
When adding new script, manually typing "Inherits" field overwrites "Path" field

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#34677]
**Godot version:**
3.2.beta4 (I've seen this in previous versions recently as well, but don't have a list of ones that I've seen affected, as I keep updating as new betas come out)

**OS/device including version:**
macOS Mojave - 10.14.6

**Issue description:**
After the first letter is typed in the "Inherits" field of the Attach Node Script editor, it moves editing to the "Path" field and begins overwriting the part is has auto-selected. This seems to happen only the first time the dialog is opened - if you correct what happened and go back and try with the same popup, it doesn't happen again. However, if you cancel the popup or open it again, it happens again. I couldn't find anything regarding this in the issues, forgive me if it's already listed.

**Steps to reproduce:**
Open a project, any project
Find a node with no script
Tap the button to add a new script in the editor
Manually type anything into the "Inherits" field

**Minimal reproduction project:**
Not project-specific, but attached an animated gif to show it. Keep in mind that I press no buttons (no tab or anything) when typing into the "Inherits" field.

![NewScriptInheritsEditorBug](https://user-images.githubusercontent.com/148612/71557721-08984500-2a18-11ea-91d2-fe9755deca13.gif)

**Comment by YeldhamDev** [comment]
Unable to reproduce it on GNU/Linux in beta4, nor in the master.

**Comment by WolfgangSenff** [comment]
I just double-checked this in the latest RC build and it is no longer happening. Can't recall if I'm allowed to close this directly, but will try...
