### ISSUE TITLE
Audio stream player (changing pitch/ tempo but not both)

### ISSUE THREAD

**Issue by iusegodot** [godotengine/godot#34675]
Hi all,

Using **Pitch scale** , you can change the pitch and the tempo.
But, how do I just change the tempo without affecting the pitch?

_Or vice versa?_

Pitch scale --> Changes both pitch and tempo (you can't only change one of them)

I am suggesting that you add the following properties:
1.  **Tempo**
2.  **Pitch**
to individually change them

Thanks,
iusegodot

**Comment by iusegodot** [comment]
@reduz   @akien-mga    @neikeq   @volzhs  @YeldhamDev   @Calinou      @Faless

**Comment by timothyqiu** [comment]
To change the pitch without affecting the tempo, you can add a PitchShift effect inside the audio bus.

**Comment by Calinou** [comment]
Please open feature proposals on [godot-proposals](https://github.com/godotengine/godot-proposals) (with example use cases), not here.
