### ISSUE TITLE
Creating a new empty project theme breaks Godot's editor (eg. color assignment)

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#34679]
**Godot version:** 3.1.1 (stable/official)

**OS/device including version:** Linux (Manjaro)

**Issue description:** In some circumstances, creating an incomplete theme and assigning it as the project theme, and then restarting the editor, causes the actual Godot editor to break; for example, you can't see anything you type when setting a color:

![image](https://user-images.githubusercontent.com/31222662/71558391-c293af00-2a20-11ea-8cdc-990949c4d547.png)

**Steps to reproduce:**

I was not able to reproduce this issue entirely by following these steps, but here goes:

- Create a new project
- Create a 2D scene, add a progress bar, specify a new theme object on it, and save the theme
- Go back to project settings, and assign that theme as the project theme (under Theme)
- Edit the theme, and pick "create new empty theme"
- Restart the editor
- Add a ColorRect and try to assign the color

This didn't reproduce the problem, but when I copied these contents over my global theme file (from a project where this does break), the problem reproduced. I didn't create/edit this file by hand, it was made by some combination of creation in the editor (I think creating a new theme, or creating a theme from the current Godot editor theme):

```
[gd_resource type="Theme" load_steps=3 format=2]

[sub_resource type="StyleBoxFlat" id=1]
bg_color = Color( 0.2, 0.2, 0.2, 1 )

[sub_resource type="StyleBoxFlat" id=2]
bg_color = Color( 0.752941, 0, 0, 1 )

[resource]
ProgressBar/colors/font_color = Color( 0.941176, 0.941176, 0.941176, 1 )
ProgressBar/colors/font_color_shadow = Color( 0, 0, 0, 1 )
ProgressBar/fonts/font = null
ProgressBar/styles/bg = SubResource( 1 )
ProgressBar/styles/fg = SubResource( 2 )
```

**Minimal reproduction project:**

[ThemeBreaks.zip](https://github.com/godotengine/godot/files/4008154/ThemeBreaks.zip)

**Comment by KoBeWi** [comment]
Seems fixed in 3.2.3
