### ISSUE TITLE
VideoPlayer does not play 60FPS videos while Display mode is 60Hz

### ISSUE THREAD

**Issue by gdesecrate** [godotengine/godot#34678]
Godot version: v3.1.2.stable.official

OS/device including version: linux

Issue description:
VideoPlayer does not play 60FPS Webms unless I overclock my display to 70Hz. I tried loading lower FPS webm while display still 60Hz and it worked.

Steps to reproduce:
Add videoplayer node
Load stream of 60FPS webm by script
Play it

Minimal reproduction project:
VideoPlayer node

**Comment by Calinou** [comment]
Does this happen with OGG Theora videos? Also, is the WebM video you're playing encoded with VP8 or VP9?

**Comment by gdesecrate** [comment]
My webs are encoded in VP8. It seems it happened with ogv as well.

I resolved by encoding all videos to 49FPS in my game as temporary measure.

**Comment by gdesecrate** [comment]
For some reason on windows netbook webms do not play (is it because low framerate?).  I got reports that they do play on other windows machines.
Here is the game: https://vetta-vetka.itch.io/project-huesos

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(whole game is not minimal project)

**Comment by gdesecrate** [comment]
Sorry, that game was finished and released (it was year ago)

In 3.2.3 I recall is difference between output on linux and on windows. If you get the texture of videoplayer - when you loop the video - windows give you one black frame when you start it over, while linux does not.

Also there some weird bitrate/vs cpu horsepower issue that can hang the video playback I believe.

I shall try to generate some synthetic tests next week.

**Comment by KoBeWi** [comment]
> I shall try to generate some synthetic tests next week.

This never happened, so I guess the issue can be closed.
