### ISSUE TITLE
When creating inherited scene making changes in AnimatedSprite makes changes in parent class

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#34687]
**Godot version:**

3.1.2

**OS/device including version:**

Windows 10 

**Issue description:**

I have a simple scene for a pill to pick up in breakout clone. Pill has following structure
![1](https://user-images.githubusercontent.com/30668026/71560255-64d28780-2a5f-11ea-92b1-a7be3b08e4e3.jpg)

If in a inherited pill say PillSlowdown I add animation in AnimatedSprite display letter S sliding across it it adds the same animation to PillParent and by doing so to every instance of a Pill. This shouldn't happen I should be able to edit inherited scene without changing properties of a parent. 

I can do it with regular Sprite. Changing sprite texture doesn't change a sprite texture in partner nor should changing animation in child affect parent in any way. 

On further inspection this only happens if user creates new sprite frames in parent object. If there is no frames created user can create new frames in a child without affecting parent. 

**Steps to reproduce:**

Create parrent scene and child scene in parrent add AnimationPlayer and then add new animation to Animation Player in child and notice animation being also created in parent. 

**Minimal reproduction project:**

N/A

**Comment by Zylann** [comment]
Note: resources are shared. Modifying one modifies every place it's been used. You can change properties of the *node*, but properties of the resource itself is not affected by inheritance.
`SpriteFrames` is a resource. So if you re-used it, inheritance becomes irrelevant.

It works with `Sprite` because you only changed the `texture` property, but not the `Texture` itself, so inheritance works.

**Comment by clayjohn** [comment]
@Feniks-Gaming Did @Zylann's explanation clear things up for you? Or do you think there is still a bug underneath this?

**Comment by Feniks-Gaming** [comment]
He is right I understand why it doesn't work the way I thought it should. It comes more to my inexperienced and wrong expectations rather than a bug.
