### ISSUE TITLE
Remember to link linux binaries with static stdc++ 

### ISSUE THREAD

**Issue by Nighttraveler** [godotengine/godot#3468]
Then this error will be solved
./Godot_v2.0_beta_20160126_x11.64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./Godot_v2.0_beta_20160126_x11.64)

**Comment by akien-mga** [comment]
Statically linking stdc++ is _not_ a good idea. We just need to build binaries on an old enough distro, like Ubuntu 12.04 LTS.

**Comment by reduz** [comment]
i think only the editor relies on libstdc++ for some dependencies

**Comment by Algrin6** [comment]
If somebody has this error and don't want to compile Godot yourself,
you may use this build (but it's 32-bit):
Godot forum: [http://www.godotengine.org/topics/13860](url)
Direct link: [http://www.filedropper.com/godotx11tools32](url)

**Comment by jarlarntzen** [comment]
Just wanted to say I probably got the same thing here.
$ godot
godot: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by godot)

Is there any way to `apt-get install` this particular missing library?

**Comment by akien-mga** [comment]
So it looks like the additional of libstdc++ as a dependency is recent, probably pe_bliss? IMO it would be better if we enforce *no usage of STL* so that we don't need to link against libstdc++ and have to handle glibc incompatibilities.

This pe_bliss inclusion has brought more trouble than features so far I feel :-/ Is it used for anything on X11, or only for icon inclusion on Windows? If it's not used, maybe we could just skip in on the non-Windows platforms?

**Comment by Algrin6** [comment]
@jarlarntzen yes, there is.
Run the following in the terminal:
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade`
That should update the libstdc++ library to the last version from PPA.

**Comment by jarlarntzen** [comment]
Thanks! But will I really need to do a dist-upgrade too?? Sounds
scary...I'm on Ubuntu 14.04 LTS BTW

**Comment by akien-mga** [comment]
You can also build yourself from the source repository, then it will link against your version of libstdc++. For the upcoming 2.0 RC we're working on a solution to bypass this issue.

**Comment by jarlarntzen** [comment]
Think I'm going to wait for the 2.0 RC, then. I'm not too proficient with building the lib. But thanks for your help!

**Comment by Algrin6** [comment]
@jarlarntzen you can use my 32-bit build for Ubuntu 14.04 LTS:
[https://github.com/godotengine/godot/issues/3468#issuecomment-176988708](url)

**Comment by reduz** [comment]
I Added the option to compile statically, building new templates right now
using it

**Comment by akien-mga** [comment]
Fixed. (we should still remember about it when making the final 2.0 binaries of course, I'll make sure to check).

**Comment by jarlarntzen** [comment]
@akien-mga Koool! I'll download again when they are ready!
