### ISSUE TITLE
Replace uses of `ERR_PRINTS` and `WARN_PRINTS` with `ERR_PRINT` and `WARN_PRINT`

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#34686]
[It seems those macros are now equivalent](https://github.com/godotengine/godot/blob/12482bf8840ce2fa84d6eea7999628be426cba8d/core/error_macros.h#L385-L393), so we should probably only keep `ERR_PRINT` and `WARN_PRINT`.

@reduz agreed with this, but I figure it'd be better to wait for the `vulkan` rebase before starting work on this :slightly_smiling_face:

**Comment by Anutrix** [comment]
https://github.com/godotengine/godot/blob/a7f49ac9a107820a62677ee3fb49d38982a25165/modules/mono/mono_gd/gd_mono_android.cpp#L318 seems to be last place ERR_PRINTS is used.
Couldn't find WARN_PRINTS at all. It seems the rest are already replaced.

**Comment by clayjohn** [comment]
Great! Looks like https://github.com/godotengine/godot/pull/33391 closes this issue.
