### ISSUE TITLE
Line Break not working in export()

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#34689]
**Godot version:**
Godot 3.1.2

**OS/device including version:**
Win 10

**Issue description:**
Line break allowing to split long statement into easier to read format is supported across many places in Godot like inside functions and dictionaries for some reason when using export() it is not. 
It makes creating long export hard to read. I have 10 different colours to select in the below example resulting in my line if code being over 120 long. 

![1](https://user-images.githubusercontent.com/30668026/71562699-331be980-2a7c-11ea-9725-32d391580eec.PNG)

This merge was meant to fix it but I think it missed some things https://github.com/godotengine/godot/pull/6694

**Steps to reproduce:**

N/A

**Minimal reproduction project:**

N/A

**Comment by Calinou** [comment]
As a stop-gap solution, does it work if you use a backslash?

```gdscript
export(String, "White", "Yellow", "Orange", "Cyan", "Green", "Red", \
        "Blue", "Violet", "Silver", "Gold") var my_color: String
```

**Comment by Feniks-Gaming** [comment]
Thanks `\` works for me too so at least there is a work around for now.
