### ISSUE TITLE
When selecting the animation dialog on tiled window, the right panels are cut off or dissapear completely.

### ISSUE THREAD

**Issue by Cobradabest** [godotengine/godot#3469]
As the title says, when I have my window tiled to the side, and I select on the animation dialog on the bottom, the right panels cut off completely if there are panels on the left, or only get partially cut off if there isn't.
![godot engine - hypnofire 3d - menu xml_006](https://cloud.githubusercontent.com/assets/8548727/12596019/13d86d0c-c476-11e5-8778-3f21dc41893c.png)
![godot engine - splash screen - splash xml - _005](https://cloud.githubusercontent.com/assets/8548727/12596021/167dfe14-c476-11e5-9b42-509bd8e0918e.png)

I am running Godot 2.0 on Ubuntu 15.10. (Both 64-bit)

**Comment by reduz** [comment]
I don't understand the steps to reproduce this bug at all

**Comment by vnen** [comment]
I guess this is the same as #3526 (which seems easier to understand).

**Comment by Cobradabest** [comment]
Click on the "Animation" button on the button, it pushes the right 
panels out of view.
