### ISSUE TITLE
Shift-tab doesn't trigger `ui_focus_prev` on Android

### ISSUE THREAD

**Issue by ndarilek** [godotengine/godot#34709]
Using 3.2.0beta4 and recently began attempting to port my game to Android. I was attempting to debug a UI issue, and plugged my desktop keyboard into my phone to try something. I noticed that Shift-tab doesn't appear to trigger `ui_focus_prev`. Could this be related to #34405 ?

Additionally, Escape doesn't appear to trigger `ui_cancel`.

I realize a keyboard plugged into an Android device isn't a common setup, but it mostly worked, and was useful for debugging. Are these bindings defined on a platform-by-platform basis, or does this indicate a deeper issue with keyboard-handling on Android?

Thanks.

**Comment by ndarilek** [comment]
Looking into it, it seems like Android keyboard events don't ship any modifier details at all. Is that correct?

Might be interested in adding this, but what would be the suggested way? Should I add a bool for each modifier (I.e. shift, alt, ctrl, etc.) or something else?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
