### ISSUE TITLE
ItemList ERROR: get_item_text: Index p_idx

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#34719]
**Godot version:**
3.2beta4.mono
**OS/device including version:**
debian 10
**Issue description:**
I have an error when I delete an item from ItemList
here the explanation: https://godotforums.org/discussion/21727/how-to-remove-an-item-from-itemlist#latest
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
This is because you are modifying the list while iterating it. So you are going for e.g. 10 elements, but you remove 2 of them and still try to access 9th one, which no longer exists (because indexes shifted).

The proper solution would be:
```
var i = 0
while i < _item_list.get_item_count():
    if _item_list.get_item_text(i) == my_text_key :
        _item_list.remove_item(i)
    else:
        i += 1
```

**Comment by git2013vb** [comment]
Or after I found what I need I can use break. Right?

**Comment by KoBeWi** [comment]
If you want to remove just one element then yeah. My code will remove all found elements.
