### ISSUE TITLE
Gizmo doesn't update wen rotating in local mode for a Spatial

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#34718]
**Godot version:**
3.2 beta 4

**OS/device including version:**
Zorin OS 15

**Issue description:**
Gizmo doesn't update wen rotating in local mode for a spatial if there is nothing rendering on his children.

![Gizmo](https://user-images.githubusercontent.com/27329423/71630403-0c3bef80-2c03-11ea-8fc1-07be9866b449.gif)

If there is a mesh or something that renders on screen then it works ok, but if there are more spatials or things that do not render to screen (audiostream, animationplayer, etc.) then the gizmo doesn't update wen you rotate on local mode.

**Steps to reproduce:**

- Create a Spatial
- Switch to local mode
- Rotate the Spatial

**Comment by Zylann** [comment]
Can confirm in Godot 3.2 beta5, it's very unintuitive

**Comment by fossegutten** [comment]
It does not update when toggling local mode either
