### ISSUE TITLE
Children of ScrollContainer are not shown properly

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#3472]
Setup: 
[root] Control
---ScrollContainer
------GridContainer
Script is wired up to put an instance of InventorySlot scene inside GridContainer. 

As you can see at http://postimg.org/image/okw36jgt7/ last row of elements is not fully displayed and ScrollContainer doesn't allow to scroll the list to the actual end. 
Setting "MinumumSize" property for elements seems to increase space BETWEEN elements, rather than forcing elements to show up completely. Several kinds of anchor combinations were tried (it seems that this whole issue is closely tied to anchors) but, alas, to no avail.

More info in forum topic: http://godotengine.org/topics/13791?r=13802

**Comment by VictorSeven** [comment]
I also want to point out that (as I said in the forum) it also happens with an HBoxContainer instead of a GridContainer.

**Comment by trollworkout** [comment]
offtopic but Children of the Scroll Container sounds like a badass band name

**Comment by bojidar-bg** [comment]
Is this still valid in master?

**Comment by vnen** [comment]
I can't reproduce this, so it seems to have been fixed. If I'm wrong then comment and I'll reopen.
