### ISSUE TITLE
[TRACKER] GDNative: High priority issues for 3.2

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#34728]
We're close to releasing Godot 3.2-stable, and when we do we'll commit to not breaking the API (nor ABI for GDNative plugins) in the 3.2 branch. So this means that if there are some GDNative issues which *must* be fixed in priority, now would be the right time to make sure that we're happy with the current state of the issues and the API we'll support for 3.2.

I haven't really had time to look over existing issues/PRs in other GDNative-related repositories (https://github.com/GodotNativeTools/godot_headers - https://github.com/GodotNativeTools/godot-cpp - https://github.com/GodotNativeTools/GDNative-demos - and the other language bindings and plugins like for VR support). Are there issues that need to be handled as high priority for 3.2, and are there PRs which would be good to merge ASAP?

We can link all relevant issues/PRs in this tracker and make sure to reach a decision for each item on a merge/fix or postponing for a future release. We can also identify issues which need to be solved soon but could be fixed without breaking compatibility with 3.2.

CC @godotengine/gdnative @sheepandshepherd @toasteater 

------

### PRs

- https://github.com/godotengine/godot/pull/34688 - merged.
- add more

### Issues

- https://github.com/godotengine/godot/issues/34254 - ptrcall on OS.get_static_memory_usage cause segfault due to godot_int != uint64_t
- add more

**Comment by FilipLundby** [comment]
I'm really hoping someone would look into [this one](https://github.com/GodotNativeTools/godot-cpp/issues/357), as it makes it impossible to create GDNative modules on Linux/Mac at the moment. It might just be an issue with the documentation, who knows. I've tried finding clues, but I have no idea what to look for. 

I'm sorry if I don't say, then just ignore me ;)

**Comment by MightyPrinny** [comment]
> I'm really hoping someone would look into [this one](https://github.com/GodotNativeTools/godot-cpp/issues/357), as it makes it impossible to create GDNative modules on Linux/Mac at the moment. It might just be an issue with the documentation, who knows. I've tried finding clues, but I have no idea what to look for.
> 
> I'm sorry if I don't have a say, then just ignore me ;)

I've used gdnative on linux and I'm terrible with c++ but I don't remember spending much time making it work.

**Comment by FilipLundby** [comment]
@MightyPrinny [See my answer](https://github.com/GodotNativeTools/godot-cpp/issues/357#issuecomment-570787263). For some reason I cannot replicate the error anymore. I wish knew what I did differently the first few times.

**Comment by akien-mga** [comment]
Closing as we're about to release 3.2 and this tracker tracks only one issue, also in the milestone :)
