### ISSUE TITLE
CheckButton and CheckBox hover pressed color does not draw

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#34727]
___

***Bugsquad edit:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
3.2 beta 4

**Issue description:**
font_color_hover_pressed does not draw, when hovering/focusing them when they are pressed. The CheckButton and CheckBox just draws the font_color_pressed instead.

![check button font color hover pressed](https://user-images.githubusercontent.com/15088582/71640696-5f5b8400-2c8f-11ea-97c3-78d990842f06.gif)

**Comment by JohnMeadow1** [comment]
Win 10, Godot 3.2.1
The problem with Font Color Hover Pressed on CheckButton is still present.
![check_button](https://user-images.githubusercontent.com/23294139/78995663-30cd2f00-7b43-11ea-87ab-e1ac49d36184.gif)

**Comment by beregolas** [comment]
on Manjaro Linux with Godot v3.2.1, I can also confirm this

**Comment by fossegutten** [comment]
Hey guys, they didnt merge my fix, so here is the workaround that you can use in the meantime:
Add a stylebox direcly on a node, then it should work.

**Comment by Calinou** [comment]
@fossegutten Since the `master` branch is currently undergoing heavy refactoring, the PR backlog has been growing steadily. But we'll still review and merge pull requests eventually, don't worry :slightly_smiling_face:

**Comment by fossegutten** [comment]
No problem, I just wanted to let the others know it is possible to workaround this. I am not sure if my fix is the best possible solution. I will leave you guys to decide :)

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Still an issue in 3.2.4 beta 2

**Comment by SuzukaDev** [comment]
Also stills in v3.3 stable.official
Hover pressed is not working on CheckBoxes
