### ISSUE TITLE
Vulkan - 4.0 dev - OS.set_borderless_window causes crash

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#34722]
**Godot version:** Vulkan branch

**OS/device including version:** Linux/Manjaro/Arch

**Issue description:** I call OS.set_borderless_window when my game menu loads up in _ready and it is causing a crash:

in the console:

> double free or corruption (!prev)

the crash is in vulkan_context.cpp on the line:
`fpDestroySwapchainKHR(device, window->swapchain, NULL);`

indeed fpDestroySwapchainKHR is called twice with the same address.

but it looks like fpCreateSwapchainKHR is returning the same address even after the previous swapchain is destroyed?

this might be a potential threading problem as I can see one thread is in VulkanContext::_update_swap_chain due to preparing to draw

while the main thread also in the same code due to a window resize event...

Is this code thread safe?

**Comment by Anutrix** [comment]
Is this related https://www.gamedev.net/forums/topic/698431-solved-recreated-dxgi-swap-chain-has-incorrect-previous-buffer-dimensions/ ?

**Comment by KoBeWi** [comment]
Doesn't seem like the method is still available, so like resolved.
