### ISSUE TITLE
"has right" sentence printed in the console.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3473]
Is there a reason for this line of the code?
'''
if (tabs[p_idx].right_button.is_valid()) {
		***print_line("has right");***
		Ref<Texture> rb=tabs[p_idx].right_button;
'''
in the file:
https://github.com/godotengine/godot/blob/dfbc2dce177462506d9c41dfaa867dd76bd136a7/scene/gui/tabs.cpp

It prints "has right" all the time in the terminal.

**Comment by est31** [comment]
I guess there's no reason, godot is full of debug statements. Probably the policy on them is to remove them.
