### ISSUE TITLE
OS.get_user_data_dir() return wrong path for Windows

### ISSUE THREAD

**Issue by danielkariv** [godotengine/godot#34733]
**Godot version: 3.2.beta4.official**

**OS/device including version: Windows 10 Pro**

**Issue description:**
When I use the OS.get_user_data_dir() to get path to user data directory, it gives back a path but it is written wrong. 

Example:
**C:/Users/Daniel/AppData/Roaming/Godot/app_userdata/New Game Project**
But to actually use it, you have to replace [ / ] with [ \\ ], so it will look like:
**C:\Users\Daniel\AppData\Roaming\Godot\app_userdata\New Game Project**

![Before After Effect](https://user-images.githubusercontent.com/38776931/71646106-37017300-2ceb-11ea-92dd-ac20564201a0.png)

**Steps to reproduce:**
Connect a button to a script.
Use code below:
![Code](https://user-images.githubusercontent.com/38776931/71646107-3d8fea80-2ceb-11ea-9803-863882a69604.png)
Then run the game, and click the button, it should open first with wrong path, than with a fix one.

**Minimal reproduction project:**
[New Game Project.zip](https://github.com/godotengine/godot/files/4014534/New.Game.Project.zip)

**Comment by Calinou** [comment]
Godot is supposed to replace slashes automatically behind the scenes, so using forward slashes should always work.

**Comment by Calinou** [comment]
Closing, as `OS.shell_open()` should be able to provide the desired functionality without hacks.
