### ISSUE TITLE
Clicking the New Scene "+" button in the editor tabs doesn't remove 2D gizmos until the mouse is moved to the 2D editor canvas

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#34746]
**Godot version:**
3.2 beta 4 mono

**OS/device including version:**
Win10 64

**Issue description:**
When there is an open scene with a selected node and a new scene is created by clicking twice on the empty scene area.
The new scene created contains markers of the previously selected scene.

This does not happen if the "+" symbol is pressed

![GIF](https://user-images.githubusercontent.com/19652075/71661631-2387f380-2d4f-11ea-958b-d236587311dc.gif)

**Steps to reproduce:**
-Open a scene and select a node.
-Create a new scene by clicking twice in a free area where the tabs of the open scenes are displayed.

**Minimal reproduction project:**
I do not think it's necessary

**Comment by KoBeWi** [comment]
Tested in 27b74f42b, can't reproduce.
![ixXX5nrxP6](https://user-images.githubusercontent.com/2223172/71666990-808da480-2d63-11ea-92b8-7dcbcba69fa5.gif)

**Comment by FlashDaggerX** [comment]
I couldn't reproduce this. Used **3.2.beta.custom_build.71d372a8a** (commit 71d372a)

**Comment by Torguen** [comment]
In beta 5 it does not occur either.
It seems to have been fixed.

**Comment by akien-mga** [comment]
@Torguen Can you test with 3.2 beta 5?

**Comment by Torguen** [comment]
It still happens in beta 5.

![GIF](https://user-images.githubusercontent.com/19652075/71818672-e2af1800-3089-11ea-8cdf-6f6c3454d0aa.gif)

**Comment by akien-mga** [comment]
I can't reproduce it in beta 5 nor the current master branch, on Linux. I doubt it's OS specific though so I think it might be related to your scene setup, can you share a project that triggers the issue reliably?

**Comment by Torguen** [comment]
Here it is.
Open the "src / Actors / Player.tscn" and select the "Player" node scene.

[plataformasTutorial.zip](https://github.com/godotengine/godot/files/4026096/plataformasTutorial.zip)

**Comment by akien-mga** [comment]
Thanks!

I still couldn't reproduce the issue with 3.2 beta 5 Mono... It's quite strange.

**Comment by Torguen** [comment]
I can send you my Godoy executable and the other configuration files, if it's any use.

**Comment by Torguen** [comment]
I made a small change, I do not remember why, someone told me in discord, he tried to add the file "_sc_" for something related to the editor.
![1](https://user-images.githubusercontent.com/19652075/71827038-a5ee1b80-309f-11ea-8642-418994e299bf.png)

**Comment by FlashDaggerX** [comment]
I still can't reproduce the issue in **3.2.beta.custom_build.a7853fc04** (commit a7853fc), even after adding the `_sc_` file, which seems to change the configuration directory. Maybe it's an issue with one of the settings in the editor?

@Torguen, could you provide your **edtior_settings-3.tres** file? It's in that **editor_data** folder.

For anyone who would like to find this feature in source, it's present in the [mono module](https://github.com/godotengine/godot/blob/a00ead2a1f79acbabaf504770a8e1d7491c29f57/modules/mono/godotsharp_dirs.cpp#L74) and the [editor_settings.cpp file](https://github.com/godotengine/godot/blob/a00ead2a1f79acbabaf504770a8e1d7491c29f57/editor/editor_settings.cpp#L793)

**Comment by Torguen** [comment]
Ok.

[editor_data.zip](https://github.com/godotengine/godot/files/4026806/editor_data.zip)

**Comment by FlashDaggerX** [comment]
I still can't reproduce it...

**Comment by Torguen** [comment]
Later I will send my complete Godot file.

I tried it on my laptop and it also happens.

**Comment by Torguen** [comment]
Okay, this is all.
[https://www.dropbox.com/s/7xxhglif2nbtzym/godot.zip?dl=0](url)

**Comment by Torguen** [comment]
In my case this is maintained in 3.2 RC2 mono.
It seems that the screen does not update the area where the nodes are displayed.
I say this because when I select a new icon or open a menu (like the help one) the garbage disappears.

![GIF](https://user-images.githubusercontent.com/19652075/72723772-d47cf380-3b81-11ea-9e00-727a1b3ced96.gif)

**Comment by Calinou** [comment]
@Torguen Which graphics card do you have?

**Comment by Torguen** [comment]
This happens to me on both computers.
A laptop with Radeon Vega8 graphics.
A desktop computer with NVidia gforce gt440.

**Comment by KoBeWi** [comment]
I can confirm this issue, I had it happen in 3.3, but I can't reproduce reliably. Not sure what causes it.

Buut, I found another issue that always happens. When you hover over node to show its name and then unfocus editor, this happens:
![b0ZPM7lQPT](https://user-images.githubusercontent.com/2223172/120998307-43afb380-c788-11eb-86b0-f22ee2028797.gif)
Fixing it should fix the original issue too.

**Comment by Torguen** [comment]
More information (3.3.3 stable mono).
2 ways to delete trash:
1 - If there is an open scene (A) and you create a new scene (B), the garbage from scene A will be removed when the cursor enters the node positioning area.
2 - (In the gif) If you only have one scene open and you close it, the garbage will not be deleted as in the first method, now you will have to select some tool.
![gif gif](https://user-images.githubusercontent.com/19652075/131640945-35c7e395-d2f8-4920-aff5-097439cf09d0.gif)

**Comment by Torguen** [comment]
Still in v3.5.beta1.official [b9b23d222]

**Comment by Torguen** [comment]
v3.5.beta5.official [815f7fe63]

**Comment by KoBeWi** [comment]
It's happening in 4.0 beta
![godot_qKaEdS6cWk](https://user-images.githubusercontent.com/2223172/195719113-b818c920-e6f8-4101-9236-7595399b2a74.gif)
Not sure why I wasn't able to reproduce it before.
