### ISSUE TITLE
Ipad pro 11 wont use full screen tried everything

### ISSUE THREAD

**Issue by made10223** [godotengine/godot#34742]
**Godot version:**
3.1.2
**OS/device including version:**
macOS 10.15.2
**Issue description:**
I'm trying to test out my game on my iPad Pro 11 but the screen isn't the full screen and I have tried tons of different things and can't figure it out. It's on both the sim and the actual device.

 [Image](https://cvws.icloud-content.com/B/AaqUKDgWzNyPVk7Fzx_2vXdiiR92AW3cCkLwSm1-4EV_YK_atDkLUzcI/Untitled.png?o=AhCfDlZCy9Zfq-sRanJ5JAT4hFihLmlvKSLwXzHXQwoi&v=1&x=3&a=CAogVIaacXncbj_rLCTVKIyQs-VnoglWp_VgiNh6Z810oQMSHRC2z9Oj9i0Y1saKpPYtIgEAUgRiiR92WgQLUzcI&e=1577939280&k=GuUaRMdPRt36MwoDP_W4uw&fl=&r=35919708-fa66-43cc-8142-e7d8cdd38bd0-1&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=12&s=ifufLB85P4Vz6DjR37JLC-dA6Yo&cd=i)

**Comment by bojidar-bg** [comment]
Image is "Gone", mind if you upload it on GitHub?

**Comment by made10223** [comment]
[https://drive.google.com/open?id=1h6wutnmdd6ua0pcAolHbRx-tVrxaL5BN](image)

**Comment by Zireael07** [comment]
Maybe the device is reporting wrong resolution back to GLES? IIRC we had that kind of issues...

**Comment by made10223** [comment]
Did you manage to fix it I’ve try using viewport and 2d and tried different things in Xcode

**Comment by Calinou** [comment]
Try setting the stretch aspect to `expand` instead of `keep`. Otherwise, your game won't be able to support multiple aspect ratios.

**Comment by made10223** [comment]
It’s on expand now and it’s still doing it

**Comment by made10223** [comment]
I have kept trying all-day could it be the sdk and it is stuck in compatibility

**Comment by made10223** [comment]
Manage to fix it. It was caused by the launch image because the launch screen use has deprecated and it doesn't have the newer devices on it. So all you have to is add a new launch screen storyboard then in general tab on targets under app icons and launch image change to the new launch screen. This should fix it but it may not. Thanks to the people that tried to help.
