### ISSUE TITLE
GD.PrintErr() output not showing

### ISSUE THREAD

**Issue by jasonswearingen** [godotengine/godot#34744]
**Godot version:**  v3.2-beta4_mono_win64

**OS/device including version:**  Win10 (PC)

**Issue description:**  ```GD.PrintErr()``` doesn't show up in output.  ```GD.Print()``` works fine.  this is while developing (not publishing/exporting)

**Steps to reproduce:**  make a '''.cs''' script and put:
```
	public override void _Ready()
	{
		GD.Print("Hello Godot");
		GD.PrintErr("Hello Err");

	}
```

**Minimal reproduction project:**  see attached
[PrintErr Repro.zip](https://github.com/godotengine/godot/files/4014939/PrintErr.Repro.zip)

**Comment by neikeq** [comment]
Not a bug AFAIK. `PrintErr` prints directly to stderr. Maybe you're looking for `GD.PushError`.

**Comment by bojidar-bg** [comment]
GDScript's `printerr` does show up in the output tab, as seen by issues such as #33324.

**Comment by neikeq** [comment]
Ah, yes. Looks like this was changed long ago by #12930. So the C# version must be updated to do the same.

**Comment by jasonswearingen** [comment]
@bojidar-bg   thank you for clarifying about gdscript's printErr showing.  I should have mentioned that  👍 

@neikeq  super props for the  fast fix!
