### ISSUE TITLE
will the call_deferred ( String method, … ) return value?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#34743]
**Godot version:3.1 documents

**OS/device including version:**

**Issue description:**
In the document it says:
Variant call_deferred ( String method, … ) vararg
Calls the method on the object during idle time and returns the result. 

However, it always return null.
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
It always returns null (`Variant()`):
https://github.com/godotengine/godot/blob/1788b22b118db02ed57487c62157f83ab73b4165/core/object.cpp#L678-L700
However, `create_vararg_method_bind` expects a `Variant` return type:
https://github.com/godotengine/godot/blob/a7f49ac9a107820a62677ee3fb49d38982a25165/core/method_bind.h#L390

Likewise, [`UndoRedo.add_do_method`](https://docs.godotengine.org/en/3.1/classes/class_undoredo.html#class-undoredo-method-add-do-method) returns `null`, but is listed as returning `Variant`.

**Comment by akien-mga** [comment]
A quick fix would be to simply change the `call_deferred` description to be explicit about the fact that it returns `null` and not the called function's result.

Given the method bind requirements, I'm not sure if we can easily fix this method being advertised as returning `Variant()` when it's always a null Variant. We have `PROPERTY_USAGE_NIL_IS_VARIANT` but not `PROPERTY_USAGE_VARIANT_IS_NIL` :)
