### ISSUE TITLE
draw_arc anti-aliasing doesn't work in windows

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#34754]
**Godot version:** v3.2.beta.calinou.27b74f42b

**OS/device including version:** Windows 10

**Issue description:** Using the new `draw_arc` function in windows doesn't have any anti-alias even if you set the argument to true.

**Steps to reproduce:** Use the draw_arc function and try setting the last argument to true or false. I tested this on Mac OS and the anti-alias was working properly, I'll try to get a Mac again to make some screenshots 

**Minimal reproduction project:** Coming soon if needed?

**Comment by Calinou** [comment]
What's the graphics card in the macOS and Windows machine (respectively)?

**Comment by coppolaemilio** [comment]
On Windows 10 I have a **GeForce GTX 1060 6GB**
The mac one (MacBook Air mid 2013) was a **Intel HD Graphics 5000 1536MB**

**Comment by clayjohn** [comment]
I wonder if this has to do with HDR conflicting with AA? Have you tried disabling HDR?

**Comment by coppolaemilio** [comment]
@clayjohn I'm not really sure if you mean HDR in the project itself. If that is what you mean, the setting doesn't seem to change anything when running the project, I'll upload it soon so you can see the issues I'm having.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
This is probably fixed in `master` thanks to https://github.com/godotengine/godot/pull/43828.

**Comment by coppolaemilio** [comment]
This is fixed in 3.2.4.beta3
![image](https://user-images.githubusercontent.com/2206700/100540653-d2be9a80-323e-11eb-8b28-68e281863bc5.png)

**Comment by coppolaemilio** [comment]
This is fixed in 3.2.4.beta3
![image](https://user-images.githubusercontent.com/2206700/100540748-8c1d7000-323f-11eb-85ea-be9377f0772f.png)
