### ISSUE TITLE
WebSocketServer listen() ignores specified port when called from GDScript

### ISSUE THREAD

**Issue by Houkime** [godotengine/godot#34751]
**Godot version:**
3.2.beta.custom_build.1788b22b1  
(current master)

**OS/device including version:**
Arch Linux, x86_64, 5.4.1 kernel
`OpenGL ES 3.0 Renderer: Radeon 550 Series (POLARIS12, DRM 3.35.0, 5.4.1-arch1-1, LLVM 9.0.0)`

**Issue description:**
If you try to make a new WebSocketServer and ask it to listen on a certain port, it will ignore port you specified and it seems like will use 6007 instead.

**Steps to reproduce:**

* Make an empty 2D project and attach this script to your main node.

```
extends Node2D

func _ready():
	var server = WebSocketServer.new()
	server.listen(9607)

```

* Start the game
* With the game runnning, check open ports. 
 
On Linux you can check ports by running, for example, lsof -i
There is **no 9607 port getting open** , at least on Linux, but 6007 gets invariably open.
here is an example of `lsof` output:

```
[user@COMPUTER ~]$ lsof -i
COMMAND     PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
godot     21333 user   13u  IPv6 168037      0t0  TCP *:6007 (LISTEN)
godot     21333 user   14u  IPv6 165811      0t0  TCP *:6008 (LISTEN)
godot     21333 user   15u  IPv6 168040      0t0  TCP localhost:6007->localhost:57602 (ESTABLISHED)
adb       21370 user   10u  IPv4 166227      0t0  TCP localhost:5037 (LISTEN)
godot     21481 user    3u  IPv4 166640      0t0  TCP localhost:57602->localhost:6007 (ESTABLISHED)
```

* 6008 is GDScript language server of the editor. (see PR https://github.com/godotengine/godot/pull/34539 about stopping it to listen to everybody)
* adb is an android debugger used by godot. 
* 6007 gets opened when you run this game. Probably a WebSocketServer we're running.
* `server.is_listening()` returns `True`

**Minimal reproduction project:**

[bind_tests_vanilla.zip](https://github.com/godotengine/godot/files/4015914/bind_tests_vanilla.zip)

**Comment by Faless** [comment]
The server goes out of scope, so it gets closed.
You see port 6007 open because that's the debugger, not your program.
You program open the server, and immediately closes it.

This is the proper code:
```
extends Node2D

var server

func _ready():
	server = WebSocketServer.new()
	server.listen(9607)
```

**Comment by Houkime** [comment]
That fixes it.
Sorry.
Closing the issue.
