### ISSUE TITLE
Editor freeze after setting focus neighbor and changing scene tab

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34769]
**Godot version:**
27b74f42b

**Issue description:**
So uh... See the steps.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4017866/ReproductionProject.zip)

**Steps to reproduce:**
1. Open the minimal project
2. Select Name node
3. Set `focus_next` to whatever node
4. Open the second scene
5. The editor wi-

**Comment by qarmin** [comment]
I have this error in terminal
```
ERROR: _disconnect: Attempt to disconnect signal 'node_removed' while in emission callback. Use CONNECT_DEFERRED (to be able to safely disconnect) or CONNECT_ONESHOT (for automatic disconnection) as connection flags.
   At: core/object.cpp:1522.
```

**Comment by akien-mga** [comment]
Related to #34650 (likely the same issue in `editor_inspector.cpp`).
