### ISSUE TITLE
bug with custom fonts in the window "Create script for node"

### ISSUE THREAD

**Issue by DimOkGamer** [godotengine/godot#3476]
![bug with fonts](https://cloud.githubusercontent.com/assets/7782218/12600086/ec828fc6-c4a7-11e5-8158-a700c25918c3.gif)

**Comment by vnen** [comment]
Indeed.

![screenshot from 2016-01-26 22-57-36](https://cloud.githubusercontent.com/assets/5599796/12600343/407f6cac-c480-11e5-8057-e984ab104cb2.png)

**Comment by akien-mga** [comment]
Duplicate of #1893.
