### ISSUE TITLE
After clicking the [Bake] button, there are display problems in the property interface

### ISSUE THREAD

**Issue by Jiaming00** [godotengine/godot#34764]
**Godot version:**
3.2 beta 4
**OS/device including version:**
window10
**Issue description:**
After clicking the [Bake] button, the property interface displays problems:

 (1) popmenu in the right attribute ui cannot be displayed, and the problem disappears after clicking any button other than Bake Button and NavigationMesh NodeButton and NavigationMesh property UI
 

~~(2) as long as the NavigationMesh Node is selected, UI size adjustments on both sides fail~~
(This problem is the same problem as #33741)

![godot_editor_bug](https://github.com/Jiaming00/lib0/raw/master/godot_editor_bug_01.gif)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
> (2) as long as the NavigationMesh Node is selected, UI adjustments on both sides fail

This is likely due to the long node name. This was already reported in #33741.

**Comment by Jiaming00** [comment]
> > (2) as long as the NavigationMesh Node is selected, UI adjustments on both sides fail
> 
> This is likely due to the long node name. This was already reported in #33741.

Thanks for reminding, this should be the same problem, but #33741 did not mention that ui size adjustment does not work.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by smix8** [comment]
@KoBeWi
@Calinou

I remember this was definitely an issue in earlier Godot versions as I experienced this bug constantly but cannot reproduce in Godot 4.0 and Godot 3.5. Maybe meanwhile this was fixed and can be closed?
