### ISSUE TITLE
Cannot view EditableChildren in signal connect menu

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#34768]
**Godot version:**
~~3.1 Release~~ (Outdated)
~~3.2 Beta 4~~ (Outdated)

32b31a5fa47b1e068be98f3196cf5d83a2260667 (See https://github.com/godotengine/godot/issues/34768#issuecomment-733381977)

**OS/device including version:**
Windows 10

**Issue description:**
![image](https://user-images.githubusercontent.com/14253836/71700456-344d5f00-2d79-11ea-8478-2646db7a7bdb.png)
![image](https://user-images.githubusercontent.com/14253836/71700444-27307000-2d79-11ea-8c94-bab8c1b3f6bb.png)

**Steps to reproduce:**
Try to connect a signal and all children of instanced scenes are not visible

**Minimal reproduction project:**
Try connecting the button to the script in the other scene

[Test.zip](https://github.com/godotengine/godot/files/4017792/Test.zip)

**Comment by KoBeWi** [comment]
Still valid in 32b31a5
