### ISSUE TITLE
HTML5 Export of "2D in 3D" results in black screen.

### ISSUE THREAD

**Issue by jeduden** [godotengine/godot#34773]
**Godot version:**
3.1.2 (stable)

**OS/device including version:**
Host Machine: Mac OSX (Mojave)

Chrome 79.0.3945.88 (Official Build) (64-bit)
Firefox 71.0 (64-bit)

**Issue description:**
HTML5 Export of "2D in 3D" results in black screen.

**Steps to reproduce:**
Install "2D in 3D" and export project to HTML5.
Serve exported files via static file server. 
Open browser and enter url of exported html file. 

**Minimal reproduction project:**
"2D in 3D" example project.

**Additional Information**
I exported "Crypth of Necrodancers mechanics" on the same system to HTML5. That works as expected.

**Comment by Calinou** [comment]
Try switching the renderer to GLES2 in the Project Settings (**Rendering > Quality > Driver > Driver Name**). Restart the editor, then export the project again.

**Comment by KoBeWi** [comment]
Seems ok in 3.2.4 beta4
