### ISSUE TITLE
Godot on ios 13.X 

### ISSUE THREAD

**Issue by made10223** [godotengine/godot#34774]
I have been trying to export to my iPad pro but its full screen I believe its a compatibility thing but I have no idea how to fix it. I have tried changing the resolution, stretch aspect by expand and the rest, please help

**Comment by clayjohn** [comment]
If you a reporting a bug. please fill out the issue template provided.

If you need help working with the engine please ask your question on one of the [Community Channels](http://docs.godotengine.org/en/latest/community/channels.html) (reddit, discord, or the Q&A are likely the best places to ask)
