### ISSUE TITLE
Search and Replace tool from the Script editor doesn't filtrer by selection.

### ISSUE THREAD

**Issue by Mautar55** [godotengine/godot#34787]
**Godot version:** 3.1.2.stable.official

**OS/device including version:** Windows 7 SP1, Edit: also Ubuntu.

**Issue description:** When use the "Replace..." Tool from the text editor (in menu Search), the tool does not limit the search to the selection, even with "Selection Only" marked. Happens either replacing oneor all instances of the word, that the search begins at the start of the file.

**Steps to reproduce:** 
1 - Open a Script. (The main node in the example file has one)
2 - Open the toon in Menu Search -> Replace...
3 - Type the words to search and replace.
4 - Mark selection only.
5 - Select the desired section of the text.
6 - Click either replace or replace all.

**Minimal reproduction project:** 
[search_and_replace_bug.zip](https://github.com/godotengine/godot/files/4020255/search_and_replace_bug.zip)

**Comment by code-xD** [comment]
I would like to work on this issue.
