### ISSUE TITLE
Right-aligned label with custom font not aligned in grid container

### ISSUE THREAD

**Issue by nebs** [godotengine/godot#34799]
**Godot version:**
v3.1.2.stable.official

**OS/device including version:**
MacOS 10.14.6 / Macbook Pro 2014 (Graphics: Intel Iris 1536 MB)

**Issue description:**
I have a simple 2D scene with the following node hierarchy:
Control -> CenterContainer -> GridContainer -> Label (x10)

I have a custom font set to all labels. The grid container has 2 columns. The right column labels are set to "Right" alignment. 

When all text is the same it works fine. But if some of the right-column labels have varying text sized then it stops being right-aligned and there is some unpredictable offset from the right side. 

The effect seems more pronounced when certain characters are present.

What's strange is that in the editor it looks fine. It only breaks when you run the scene.

Here's what it looks like in the editor (this is fine):
<img width="350" alt="Screen Shot 2020-01-03 at 7 02 59 PM" src="https://user-images.githubusercontent.com/2637098/71756249-c5e1cd00-2e5c-11ea-8fbc-e5112f7eb0d2.png">

Here's what it looks like when you run the scene (notice the right edge is not aligned fully):
<img width="271" alt="Screen Shot 2020-01-03 at 7 03 09 PM" src="https://user-images.githubusercontent.com/2637098/71756252-cc704480-2e5c-11ea-80ef-fdeb463e6d87.png">

There are no scripts running, all the data is hard coded in the editor.

NOTE: This bug might be related to [#30859](https://github.com/godotengine/godot/issues/30859). I created a separate issue because that bug refers to "fullscreen" whereas mine happens even without fullscreen.

**Steps to reproduce:**
The simplest way is to just run the minimal project I uploaded below. You don't have to change anything, just run the project. There is only one scene and there are no scripts.

You should see the bug as soon as you run it. The bug makes it look like the second screenshot above (the right side of the text looks like an arc and isn't fully aligned to the right horizontally even though it looks ok in the editor preview).

**Minimal reproduction project:**
[Simple project to reproduce the bug (LabelTest.zip))](https://github.com/godotengine/godot/files/4021306/LabelTest.zip)

**Comment by timothyqiu** [comment]
This may be related to the "2d" Stretch Mode.

The issue is gone if you disable window resize, or use a stretch mode other than 2d.

**Comment by volzhs** [comment]
disabling `Use Oversampling` at Project settings > Rendering > Quality > Dynamic Fonts will fix it also.
