### ISSUE TITLE
Collision with a rescaled collision shape on a KinematicBody

### ISSUE THREAD

**Issue by ennQ** [godotengine/godot#34797]
**Godot version:** 3.1.2

**Issue description:** When rescaling a capsule collision, it will not collide properly with another collision shape

**Steps to reproduce:** Create a KinematicBody, attach it a Capsule collision shape, rescale the transform and it will not collide properly with for example a floor.

**Minimal reproduction project:** [reproduction project](https://github.com/godotengine/godot/files/4021199/TEST.godot.zip)

Here is also a gif of the issue, on the left is a capsule collision shape resized with the collision shape parameters and on the right a capsule collision shape resized using his scale transform values :
![gif](https://user-images.githubusercontent.com/58097205/71754199-811e5c00-2e85-11ea-92e6-3ad89b9ca97e.gif)

**Comment by jayaarrgh** [comment]
That's just how collision shapes work. You cannot resize them this way. You should always use the handles of the collision shape to resize.
https://docs.godotengine.org/en/3.1/tutorials/physics/physics_introduction.html#collision-shapes

**Comment by ennQ** [comment]
Alright i guess its not going to change. I'll close this, thanks.
