### ISSUE TITLE
There is no way to disable multitouch

### ISSUE THREAD

**Issue by SmithJohnFirst** [godotengine/godot#34796]
**Godot version:**
3.2
**OS/device including version:**
Android/iOS
**Issue description:**
In many situations, it is necessary to limit the operation of the screen on mobile devices with just one touch. Godot does not allow you to disable multitouch.
We need a mechanism similar to `Input.multiTouchEnabled = false;` in Unity.

**Comment by akien-mga** [comment]
Please open a proposal on https://github.com/godotengine/godot-proposals with some more details about the use cases for which you'd need multitouch disabled.
