### ISSUE TITLE
`2d` or `viewport` stretch mode does not scale mouse coordinates

### ISSUE THREAD

**Issue by Bleuzen** [godotengine/godot#34805]
**Godot version:**
Godot_v3.2-beta5_x11

**OS/device including version:**
Manjaro Linux (rolling (as of 2020-01-04))

**Issue description:**
I placed my games view in a viewport which itself is placed within a ViewportContainer.
I attached a script to it to scale the viewport to the current display/window size.
The scaling of the graphics work, but the mouse coordinates are not scaled with them.
Mouse detection on Controls is still acting as if the Viewport would not be scaled up.

You can see it in action in the beginning of this video I made:
https://www.youtube.com/watch?v=c58L8MyqYEU

Additional / what I found out so far:
If i disable and re-enable the "handle input locally" option of the viewport during runtime, it works as long as I don't change the window size. (another bug?)

**Steps to reproduce:**
Make a 2D scene with some controls in it (for example buttons).
Scale up this scene with with a Viewport within a ViewportContainer.
(You can do it easier and during the game is running for example by using a script like the one that I used in the demo / reproduction project linked below.)

**Minimal reproduction project:**
https://github.com/Bleuzen/godot-viewport-scaling-bug-demo

**Comment by Calinou** [comment]
You can manually compensate the mouse coordinates to take scaling into account:

```gdscript
# `get_size_override()` will return a valid size only if the stretch mode is `2d`.
		# Otherwise, the viewport size is used directly.
		var viewport_base_size := (
				get_viewport().get_size_override() if get_viewport().get_size_override() > Vector2(0, 0)
				else get_viewport().size
		)
```

**Comment by Bleuzen** [comment]
@Calinou Sorry, I'm still not a pro with Godot. Where do I have to place this code in my demo project?

I tried it in the Viewport.gd script and in a script attached only to the real Viewport in the scene. Both didn't work.
If i paste it as you wrote it, the game crashes with a null instance error.
So I replaced the `get_viewport()` calls with my viewport.
But this changes nothing, mouse position is still not scaled up.

I guess I will have to use this var somehow in my code, but I'm not sure how exectly.

**Comment by hardikbhalodi** [comment]
@Calinou same issue as @Bleuzen mentioned in 3.2 stable and 3.2.2 beta

**Comment by Duehok** [comment]
I just got bitten by that one!

Workaround: instead of using ```GetViewport().GetMousePosition()```
use
```GetViewport().GetFinalTransform().XformInv(GlobalMousePosition())```
(In C#)

**Comment by RedHeadphone** [comment]
> You can manually compensate the mouse coordinates to take scaling into account:
> 
> ```gdscript
> # `get_size_override()` will return a valid size only if the stretch mode is `2d`.
> # Otherwise, the viewport size is used directly.
> var viewport_base_size = (
> 		get_viewport().get_size_override() if get_viewport().get_size_override() > Vector2(0, 0)
> 		else get_viewport().size
> )
> ```
> 
> This should make the coordinates behave seamlessly regardless of the current stretch mode.

@Calinou In 3d gui , code uses "on mouse enter" how can I fix it?

**Comment by Calinou** [comment]
@RedHeadphone This repository is meant to be used for bug reports only. For support questions, please use one of the other [community channels](godotengine.org/community) instead.

**Comment by theludovyc** [comment]
Hello,

We have the same error, you can see the projet here https://github.com/salty64/Godot_Obj_viewer/tree/master/src. I made the little project with this error in a days.

Parameters are "2d" and "Keep".

We correct it with :
```gdscript
#get the real size of the viewport
var root_size = $"/root".size

#calculate black strip
var correction = (OS.get_window_size() - root_size)/2.0

#we use fixed resolution of 1600 * 900
var ratio = Vector2(1600.0, 900.0)/root_size

var real_mouse_position = (get_viewport().get_mouse_position()-correction)*ratio
```

Scene Tree :
root <= it's a viewport
 ViewportContainer
  Viewport <= current viewport
   Gimbal <= script is here
    InnerGimbal
     Camera <= current camera

Where get_mouse_position() is declared in scene/main/viewport.cpp : [here](https://github.com/godotengine/godot/blob/46de553473b4bea49176fb4316176a5662931160/scene/main/viewport.cpp#L1475)

**Comment by Calinou** [comment]
For drag-and-drop code, use something like this (tested with the `2d` stretch mode):

```gdscript
		var viewport_base_size = (
			get_viewport().get_size_override() if get_viewport().get_size_override() > Vector2(0, 0)
			else get_viewport().size
		)
		var scale_factor = OS.window_size / viewport_base_size

		target.global_position = event.global_position / scale_factor
```
