### ISSUE TITLE
Tilemap editor: resets when we selects a tile

### ISSUE THREAD

**Issue by iamrahul404** [godotengine/godot#34815]
**Godot version:**
3.2.beta4
**OS/device including version:**
Windows 10 64 bit
**Issue description:**
I want to select a new single tile from a large tileset and zoom in that tileset, as soon as I select a particular tilemap moved to somewhere else and I need to come back again to that tile, this is not an issue if I have 1-2 tile to select but definitely an issue if I have to select 100s of tile to select.
**Steps to reproduce:**
take a large tileset (one from Kenney's 2d racing pack) and try to select a new tile with zoom in from the middle, try with 2-3 tiles you can see it.
**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
This is fixed in beta5.

**Comment by iamrahul404** [comment]
Thanks @KoBeWi for the quick reply.
