### ISSUE TITLE
AutoLoad not able to change NodeName

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3481]
I don't want to re add the Node to update the name.
Suggestion: Add double click on the name to update?

**Comment by vnen** [comment]
+1

As a workaround, you can use a text editor to change the file `engine.cfg` in the project root.

**Comment by reduz** [comment]
should be done somewhere in this file.. make sure it supports undo/redo and make sure to keep the order (set_order) when doing undo redo. Check how undo for delete works.

https://github.com/godotengine/godot/blob/master/tools/editor/project_settings.cpp
