### ISSUE TITLE
AutoLoad, Node position moves up on singleton enable/disable 

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3482]
Add  a few Autoload Nodes enable Singleton on one of the bottom Nodes press close, reopen Autoload see that it moved up.

**Comment by akien-mga** [comment]
I guess that might be a feature? i.e. autoloads are sorted with singleton ones first, and the rest after.
But it's open to discussion if users think it would be better not to sort autoloads this way; personally I don't have a strong opinion.

**Comment by bojidar-bg** [comment]
I don't mind how they are sorted, as long as it is stable (git diffs) and intuitive (no sorting by MD5 checksum)...

**Comment by AlexHolly** [comment]
I could live with this feature if it would update instand and not after I closed the window.

**Comment by bojidar-bg** [comment]
I agree with @AlexHolly, it should resort them automatically, to be more intuitive

**Comment by reduz** [comment]
i have no idea what is going on

**Comment by reduz** [comment]
don't understand the report

**Comment by vnen** [comment]
@reduz autoloads marked as singletons move to the top of the list, but the UI doesn't reflect that immediately.

**Comment by akien-mga** [comment]
IMO they should just not move, the star (`*`) should be added in engine.cfg, but without doing any reordering.
