### ISSUE TITLE
[Mono] Unable to use Android Export Templates in Ubuntu

### ISSUE THREAD

**Issue by tj4752** [godotengine/godot#34822]
**Godot version:**
3.1.2 Mono-64 bit

**OS/device including version:**
Ubuntu 18.04 LTS

**Issue description:**
An error is generated named "Missing android export templates" in Export Window even after installing it from the mirror link. When trying to install the project directly to the device, error named "Package not found" pops up.

**Steps to reproduce:**
1. Open export window and click on error displayed at bottom of the window. 
2. After installation of the template from the mirror link given. Close the export window and open it again.
3. The above error is still displayed.

**Comment by Calinou** [comment]
Godot 3.1 doesn't support exporting C# projects to Android. This was added in the 3.2 betas (try [3.2 beta5](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-5)).
