### ISSUE TITLE
StyleBox antialiasing is broken

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#34830]
**Godot version:**
3.2 beta5 mono
**OS/device including version:**
ArcoLinux
**Issue description:**
StyleBoxes stopped antialiasing between beta4 and beta5.

beta4
![Screenshot_2020-01-04_22-43-31](https://user-images.githubusercontent.com/28724859/71775289-1d0e9d00-2f44-11ea-87f1-8187d05eca31.png)

beta5
![Screenshot_2020-01-04_22-44-32](https://user-images.githubusercontent.com/28724859/71775292-239d1480-2f44-11ea-9436-464d242fd869.png)

**Comment by akien-mga** [comment]
CC @pouleyKetchoupp
