### ISSUE TITLE
TextureProgress doesn't work with AtlasTexture in radial fill mode

### ISSUE THREAD

**Issue by arkology** [godotengine/godot#34837]
**Godot version:**
3.2 beta 5 official
**OS/device including version:**
Win10
**Issue description:**
related issue: https://github.com/godotengine/godot/issues/33855
![Godot_v3 2-beta5_win64_wjmSfnPkOy](https://user-images.githubusercontent.com/43543909/71782435-dde75700-2fea-11ea-8455-48b68e6437aa.png)

**Steps to reproduce:**
1) Set AtlasTexture to progress texture of TextureProgress node
2) Set fill mode to radial

**Minimal reproduction project:**

[ProgressAtlas.zip](https://github.com/godotengine/godot/files/4023543/ProgressAtlas.zip)

**Comment by Calinou** [comment]
> Set fill mode to radial

Is it only broken with the radial fill mode, or with other fill modes as well?

**Comment by arkology** [comment]
@Calinou only radial.

**Comment by Relintai** [comment]
Actually, it's not implemented. I wanted to do it a while ago, but never got around doing it.

**Comment by KoBeWi** [comment]
Still valid in 32b31a5

**Comment by floppyhammer** [comment]
https://github.com/godotengine/godot/blob/d956904091b620bea5ee6eec9bd1413a97bba69a/scene/gui/texture_progress_bar.cpp#L483-L485

The issue might be caused by `CanvasItem::draw_polygon()` not properly handling `AtlasTexture`.
