### ISSUE TITLE
LineEdit: "focus_exit" signal misbehaviour

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#3483]
LineEdit is emitting signal "focus_exit" when enter-key is pressed.
As the focus stays on the LineEdit on hitting enter (is it on purpose?),
this signal should not be fired.

**Comment by vnen** [comment]
Might be on purpose (so you handle enter), but I also don't think it's a good idea to trigger `focus_exit` when the focus is still there.

**Comment by reduz** [comment]
whoa should have paid more attention to a PR two years ago :P
