### ISSUE TITLE
Unexpected "shadows" with SS reflections

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#34846]
**Godot version:**

Godot Engine v3.1.2.stable.custom_build
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2

**OS/device including version:**

Linux 5.4.7-arch1-1

**Issue description:**

A [reddit commenter](https://www.reddit.com/r/godot/comments/ek4xp7/sharing_progress_on_my_vehiclestrategy_game_to/fdb91lr?utm_source=share&utm_medium=web2x) pointed out some unusual visual artifacts in my game with SS reflections. It almost appears that a mesh is casting shadows over the reflections, but there's no light source behind the mesh that would be casting those shadows.

![1578263432](https://user-images.githubusercontent.com/2496231/71787075-efc3fc80-2fe0-11ea-8c88-deade66f7060.png)

Possibly related to https://github.com/godotengine/godot/issues/9017, https://github.com/godotengine/godot/issues/15527, https://github.com/godotengine/godot/issues/17995

**Steps to reproduce:**

1. Create a plane with a `SpatialMaterial` that has `roughness=0`, `metallic=1`
2. Create a cube with a `SpatialMaterial` that has `emission=4`
3. In the environment, set `Background.mode=CustomColor=black`, and enable `SS Reflections`
4. The cube should reflect off the plane
5. Add another MeshInstance and move it around between the cube and the camera
6. Note that it blocks parts of the reflection, even if it is not between the cube and the plane

**Minimal reproduction project:**
[example.zip](https://github.com/godotengine/godot/files/4024111/example.zip)
![1578262936](https://user-images.githubusercontent.com/2496231/71786980-d4a4bd00-2fdf-11ea-9adb-167986db8e5f.png)
^^^ note that the sphere is well above the cube in this picture, but it is taking a "chunk" out of the reflection.

**Comment by golddotasksquestions** [comment]
Glad to see you were able to isolate and replicate the issue!
Here is a quick gif from your project that shows it in action.
![Uploading ss_reflection_issue.gif…]()
I noticed even the laser beams in your video cause the same effect.

**Comment by Calinou** [comment]
I'm not sure if this is a bug or a limitation of the screen-space reflection algorithm.

**Comment by rcorre** [comment]
**Rendering > Quality > Depth Prepass > Enable** does not change it. Setting `no_depth_test` on the sphere does (though isn't a viable solution), and setting `depth_draw_mode` to `Never` produces a different effect:

![1578311677](https://user-images.githubusercontent.com/2496231/71816658-4d902d00-3051-11ea-97ca-57eae076d7d8.png)

**Comment by Janders1800** [comment]
Thta's a limitation of SS Reflections work, not even in big budget games like RE2 Remake found a way to fix it.

![RE2R-SSR](https://user-images.githubusercontent.com/27329423/71830377-e309dc00-30a6-11ea-872d-304e54b3d26e.jpg)

**Comment by rcorre** [comment]
Makes sense, feel free to close if this is just considered an implementation limitation that we're unlikely to fix in Godot. At least in my game, I consider it pretty minor, I never even noticed it without @golddotasksquestions's eagle eye!

**Comment by Calinou** [comment]
We should improve the documentation to mention such limitations. I'll try to do this ASAP.
