### ISSUE TITLE
MultiMesh custom data format usage is counterintuitive

### ISSUE THREAD

**Issue by brendor** [godotengine/godot#34845]
Hello, I've been working with the new MultiMeshInstance2D in the beta4 and I noticed something strange about how the custom data format works.
The problem lies in `RasterizerStorageGLES3::multimesh_instance_set_custom_data`.
The docs state that the Color type is only used to hold 4 numbers, however inside the mentioned function, the color is converted from float to 8 bit representation like this
```
data8[0] = CLAMP(p_custom_data.r * 255.0, 0, 255);
data8[1] = CLAMP(p_custom_data.g * 255.0, 0, 255);
data8[2] = CLAMP(p_custom_data.b * 255.0, 0, 255);
data8[3] = CLAMP(p_custom_data.a * 255.0, 0, 255);
```
which is fine for colors, but does in fact change the values of the colors sent to the method.
i.e. I want to send value 2 to the shader, this value lies in the interval 0-255 which I expect to fit in a byte. However, this will not work, because of the transformation which treats the value as if it was a color and clamps it to 255, which will be transformed to 1 inside shader due to how the data attrib pointers are set up. With floats, this works fine, because the numbers are set directly as they are:
```
dataptr[0] = p_custom_data.r;
dataptr[1] = p_custom_data.g;
dataptr[2] = p_custom_data.b;
dataptr[3] = p_custom_data.a;
```
So the number 2 will be usable in the shader as one would expect.
This can be, of course, fixed by sending numbers in the supported float range of 0-1, which would be transformed to the 0-255 range and then multiplying in the shader to get the desired value, but I think such a thing should either not work like this, or be explained in the docs - changing the data type drastically changes how one should work with the API.
I suggest either:
- change the docs and make this obvious to the user
- do not transform the numbers and multiply by 255 in the generated shader, so the values remain the same, limiting usage of "byte" data type to integral numbers (this being made obvious in the docs), while if someone wants to work with floats, they would just pick "float" without having to do any extra computations inside shaders or when calling the functions. Which is, imho a better method of fixing this.

I think this should be discussed and I can make a PR if someone reviews this and agrees on a fix method.

**Comment by clayjohn** [comment]
You need to use a float to store a value larger than 1, you can do this by setting ``CustomDataFormat`` to ``CUSTOM_DATA_FLOAT``. 

8 bits can only store numbers between 0-255 as integers, However, OpenGL converts bytes in the range 0-255 into floats in the range 0-1. 

It sounds like what you really need is a way of passing 4 custom integer values per instance. However, that is currently unsupported. The current work flow is that custom data holds a ``vec4`` (``vec4``s hold 4 floats) and the user can decide whether to compress that float into a byte, or to pass it as a full 32bit float. Arbitrarily switching to ints would be confusing for users. 

I suggest for your use case you pass in ``value/255`` to ``set_instance_custom_data`` and then in the shader just multiply by 255 i.e. ``vec4 custom_data = INSTANCE_CUSTOM * 255.0``

**Comment by brendor** [comment]
I understand this, but the approach seems rather as a workaround than the expected workflow to me.
I believe this should be at least stated and explained in the docs, because I can imagine it could be not so intuitive to some users, or users that don't know how the engine transforms these internally.
The docs only mention that:
> Format of custom data in custom data array that gets passed to shader.

And for the API function:

> Sets custom data for a specific instance. Although Color is used, it is just a container for 4 numbers.

I know this is still beta, but from these two it's not at all obvious that the workflow for byte and float is so different.

**Comment by clayjohn** [comment]
> I know this is still beta, but from these two it's not at all obvious that the workflow for byte and float is so different.

Currently the workflow is the same for float and for byte. The user passes in a float and they access a float from the shader. However, the user has the option of compressing the float into a byte if they choose. 

You are asking for a completely different workflow which would allow the user to pass data in as an integer instead of a float. This would create a completely different and IMO unexpected workflow for users. Further it will be supported poorly on low-end (GLES2) devices.

**Comment by brendor** [comment]
Not at all, I'm asking for a function that's documented enough so that the user does not have to trace the code and find out why the value is not the same as the input. "Compressed into byte", even if mentioned in the docs, would not imply that a number ie. 2 would result in 1 when using "byte" and 2 when using "float". This is not compression, it's clamping. 2 would well fit into the byte range 0-255, but due to how the values are compressed internally, this is outside of the range. I'm not saying the API needs to change, only that the user should know about this clamping from the docs.
