### ISSUE TITLE
GridMap lose its visibility setting when added through call_deferred("add_child")

### ISSUE THREAD

**Issue by imjp94** [godotengine/godot#34858]
**Godot version:**
v3.1.2.stable

**OS/device including version:**
Windows 10

**Issue description:**
If GridMap was set to be invisible in editor, it will still be rendered if added through call_deferred("add_child", gridmap), while other methods work as expected.

**Steps to reproduce:**
Add GridMap through call_deferred("add_child", gridmap)

**Minimal reproduction project:**

[InstanceVisibilityBug.zip](https://github.com/godotengine/godot/files/4025866/InstanceVisibilityBug.zip)

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3
Weird, because after non-deferred add there's no issue. Even `yield(get_tree(), "idle_frame")` breaks the visibility.

**Comment by KoBeWi** [comment]
Fixed in Godot 4.
