### ISSUE TITLE
embedding game in <iframe> size issues between browsers

### ISSUE THREAD

**Issue by define-private-public** [godotengine/godot#34851]
**Godot version:**
3.1.2

**OS/device including version:**
HTML5 Export

**Issue description:**
So I have a game that I created to run at 800x800 pixels.  I was able to export it for HTML5. After reading the "Exporting for the Web" document, I got the idea to put the game in an `<iframe>`.  The only issue is that in Firefox, my game only looks good if I do `<iframe width="640" height="640">` and in Chromium I need to do `<iframe width="615" height="615">`

Something about this doesn't feel right, or work right.  I have to add some JavaScript to check what the browser is, and then resize the iframe.

**Comment by Calinou** [comment]
Can you provide a minimal reproduction project? This would make it much easier to diagnose the issue.

**Comment by define-private-public** [comment]
I'll try to get a reproduction up within a day or two.  I also want to report that when I switched to my Windows partition (same machine), and then tested Firefox and Chrome, there were also sizing differences w/ the iframe that made things look quite ugly.

**Comment by define-private-public** [comment]
Got this done a bit quicker than planned.  The full game I have is up here: https://16bpp.net/games/pucker-godot-edition-2020/

 Attached is a very stripped down version of the game that I was making  (most scripts are removed, had to remove the custom font for licensing reasons).  Do the HTML5 export to the directory `html5/`,  and make sure the file is called `game.html`.  You can then visit the `test.html` file where I have that `<iframe width="640" height="640">` set up (though I want 800x800).

[PUG_stripped_down.zip](https://github.com/godotengine/godot/files/4028684/PUG_stripped_down.zip)

I also suggest visiting `game.html` by itself as well.  As there are some layout discrepancies as well too.

**Comment by define-private-public** [comment]
Someone on Reddit pointed out I was missing the `test.html` in the .zip file.  It's now been included in there.

**Comment by define-private-public** [comment]
I was able to resolve the issue by changing the project settings of "Stretch Mode" to `2d` and "Aspect Ratio" to `keep`.

I think that something should be mentioned about this in the [Exporting for the Web](https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_for_web.html) doc.  Since I'm pretty sure that other newcomers might have this same thing happen to them too.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Faless** [comment]
Closing as fixed in `3.3`, feel free to comment if you can still reproduce.
