### ISSUE TITLE
two area2d in one node

### ISSUE THREAD

**Issue by t2dk49580** [godotengine/godot#34859]
**Godot version:3.1.2

**OS/device including version:*windows 10*

**Issue description:
        var look = $lookRange/collision as CollisionShape2D
	look.shape.radius = 100

	var attack = $attackRange/collision as CollisionShape2D
	attack.shape.radius = 10

        print(look.shape.radius,attack.shape.radius)

        # result:    10 10

**Steps to reproduce:
add a node2d
add 2 area2d
add script
run

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
That's because their shape is shared. Right-click one's shape resource and select "Make Unique".
