### ISSUE TITLE
Flickering tilemaps

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [godotengine/godot#34864]
**Godot version:** 3.2.beta4 and beta5, I can't tell what causes it or what other versions may have this bug since it doesn't happen to me.

**OS/device including version:** Windows 10 64 bits

**Issue description:** When the player gets to certain places in the level, the entire map and some objects start flickering for no reason.

**Steps to reproduce:** I have no idea, as I seem to have no control over the bug at all. In the project I'm linking, you have to get to this area:

![Sin título](https://user-images.githubusercontent.com/56773311/71834464-4b43c800-307d-11ea-9267-3be0bd600620.png)

**Minimal reproduction project:** https://www.dropbox.com/s/ymglddjhipa1hvr/New%20Game.zip?dl=0

This is as minimal as it can get since I can't seem to recreate it on my computer, so I don't know what causes it. If anyone needs the controls of the game to check if the bug happens to them, the controls are the arrow keys plus C to jump, V to dash and X to climb and hold on to walls.

**Comment by Calinou** [comment]
Does this occur with both GLES3 and GLES2 renderers? Does enabling **Rendering > Quality > Gles 2 Use Nvidia Rect Flicker Workaround** in the Project Settings solve the issue?

**Comment by Lilith-In-Starlight** [comment]
I thought about it but I didn't try it since their graphic cards aren't from Nvidia.

**Comment by Lilith-In-Starlight** [comment]
After further testing the bug seems to be related to the amount of elements in the scene, which is weird because it doesn't affect me. I have a few objects that generate particles and reducing them reduces (but doesn't stop) the issue. I can't say for certain, tho

**Comment by Lilith-In-Starlight** [comment]
After further testing I notice it doesn't only affect tilemaps and that it's related to the number of particles being emitted, so I *think* this might be related to or the same issue as #28719, but I can't tell for certain.

**Comment by Lilith-In-Starlight** [comment]
The fix was to summon the particles in `_physics_process()` rather than in `_process()`, just as described in #28719. I'm pretty sure this is a thing that shouldn't happen. Issue closed.
