### ISSUE TITLE
Rotation tool in 2D Editor inverts its direction.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#34861]
**Godot version:**
cab97f4b504a6

**OS/device including version:**
Win10 64-bit

**Issue description:**
When setting negative scaling in a node, it will influence how the rotation dragging works in its children.

Making the tool rotate in an inverted direction.  I understand it's from the transform inheritance, but for artists It's very unintuitive, especially since the parent node isn't affected by this change.  

The tool should apply a global rotation.

![image](https://user-images.githubusercontent.com/13004169/71821576-28281100-309b-11ea-8a17-d3e7b209143b.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/71821936-31fe4400-309c-11ea-8505-5d49f797e4fb.gif)

**Steps to reproduce:**

Create a hierarchy of 2D nodes, flip the scaling of the parent, and try using the editor rotation to rotate it's children. 

**Minimal reproduction project:**
[Rotation Issue.zip](https://github.com/godotengine/godot/files/4026262/Rotation.Issue.zip)

**Comment by Phischermen** [comment]
In the 3D editor, there is a button that's used to toggle "local mode." I think it would make most sense to add this button to the 2D editor as well.

**Comment by Phischermen** [comment]
I can look into this one. I'll try the solution I mentioned above.

**Comment by avencherus** [comment]
Thanks, would be much appreciated.

**Comment by name-here** [comment]
Is this because scale -1 flips the node and its children around the corresponding axis?  If so, I think the fix for this would be to invert the rotation tool's applied rotation by -1 if an odd number of scale values for the parents of the node being manipulated are negative.

**Comment by groud** [comment]
There is no need to implement a local mode in 2D. It simply requires the global transform to be checked, and revert the rotation direction if the transform flips the object.

**Comment by Phischermen** [comment]
@groud You're right. After giving it some more thought, making a local transformation mode would imply a global transformation mode as well. I don't think that's accurate to how the tools work. I think I'll implement your solution, as it sounds like the simplest way to fix this issue.
