### ISSUE TITLE
.obj .escn .gltf .dae models cannot be loaded

### ISSUE THREAD

**Issue by ligazetom** [godotengine/godot#34866]
**Godot version:**
3.2.beta.custom_build.24281cd9c

**OS/device including version:**
Windows 10 Pro (Version: 1903, Build 18362.535)

**Issue description:**
Any format exported from blender cannot be opened in Godot Editor

Editor output:
![image](https://user-images.githubusercontent.com/11858829/71841040-ced1d900-30be-11ea-8d24-d640797b66cb.png)

Editor console output:
![image](https://user-images.githubusercontent.com/11858829/71841094-e5783000-30be-11ea-9ae7-cb22fa052c65.png)

This happend after updating to the latest build of the engine.

To be honest I am tired a little bit. Past 5 days I spent trying to import everything I want to work with (Geometry, Collision, Animations, Shape Keys, UVs, Materials, Textures) with versions from 3.0 up to latest one with no success. Is Godot still such a young project to not have this worked out?

**Comment by aaronfranke** [comment]
Can you provide a minimal reproduction project, including a source Blender file?

**Comment by akien-mga** [comment]
Regression from #34829, CC @timothyqiu.

**Comment by ligazetom** [comment]
Literally just export default blender cube in any of mentioned formats and try to open in godot.
