### ISSUE TITLE
Allow to manually edit path for exported NodePath

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3486]
Currently there is no way to manually change path for exported NodePath. It would be great if there would be ability to normally modify the path from the keyboard. It would be especially helpful in cases when we want to write absolute path or when the node we want to target is on another scene (and we are targeting from subscene).

**Comment by bojidar-bg** [comment]
I remember being able to edit it by hand recently.... is this still an issue?

**Comment by kubecz3k** [comment]
@bojidar-bg tehre is no option to write path manually on the 2.1 alpha build from this week:
![nodepath](https://cloud.githubusercontent.com/assets/6129594/15629373/c581ff62-2517-11e6-9fcc-e4f5cf7337e5.png)

**Comment by bojidar-bg** [comment]
@kubecz3k Indeed... The funny thing is that I have a path leading outside some of the scenes (xD), so it should be a recent regression.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.
