### ISSUE TITLE
Dragging/dropping TSCN into NodeTree multiple times corrupts NodePaths

### ISSUE THREAD

**Issue by benstopics** [godotengine/godot#34872]
**Godot version:**
3.1.2.stable

**OS/device including version:**
Windows 10

**Issue description:**
I had a PackedScene called Person.tscn which had an AnimationPlayer and multiple Sprites. I wanted to play around with a couple of these people on the TileMap, so instead of programmatically spawning them I thought I could simply drag and drop the resource onto the TileMap to add children. This seemed to work fine, however when I renamed my nodes to Bob, Joe, and Mary, it apparently changed all the track NodePath properties for all the Animations in my AnimationPlayer in the TSCN file. Unfortunately I didn't know this immediately, it took me a couple hours playing around with Resource Local to Scene, load vs preload, onready, overriding the default AnimationPlayer.play parameters. Finally I figured out that the animation would play but only if the node was called Person, the same name as the PackedScene. I have only been using this software a week or so, but I was able to research the TSCN file format and all the NodePath properties started with ../Person/ so I removed this and it uncorrupted my PackedScene.

[Person-fixed.tscn.txt](https://github.com/godotengine/godot/files/4027791/Person-fixed.tscn.txt)
[Person-corrupted.tscn.txt](https://github.com/godotengine/godot/files/4027792/Person-corrupted.tscn.txt)

**Steps to reproduce:**
Create a PackedScene with a Sprite importing a spritesheet and an AnimationPlayer
Create an Animation in the AnimationPlayer using keyframes from the Sprite's spritesheet
Save the PackedScene and observe the NodePath in Notepad of the TSCN
Create a new Node2D Scene and drag and drop a couple of the TSCN's into a Node2D
Rename each instance of the PackedScene to something unique
Open the TSCN in Notepad and observe that the NodePath has changed in the TSCN

**Comment by KoBeWi** [comment]
This was likely fixed with #42314
Comment if you can still reproduce in 3.2.4 beta3.
