### ISSUE TITLE
`Degrees of Freedom` options cause corruption of the AndroidManifest binary

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot#34873]
**Godot version:**
3.2

**OS/device including version:**
Android

**Issue description:**
When exporting an Android apk, select `6DOF` or `3DOF and 6DOF` for `Degrees of Freedom`.
While the exported apk is able to be installed manually on a device, attempting to inspect its `AndroidManifest` binary (via Android Studio or android apkanalyzer tool) causes an error. 

The error seems to be affecting submission to official channels.

**Steps to reproduce:**
- Export an Android apk
- Select `6DOF` or `3DOF and 6DOF` for `Degrees of Freedom`
- Examine the apk `AndroidManifest` binary

**Minimal reproduction project:**

**Comment by m4gr3d** [comment]
cc @creikey

**Comment by creikey** [comment]
@m4gr3d using apktool should print better errors, although I've found the way it dissects the information differs slightly from apkanalyzer
