### ISSUE TITLE
Mono/C#: Anonymous async lambda function freezes editor

### ISSUE THREAD

**Issue by slango0513** [godotengine/godot#34894]
Godot_v3.2-beta5_mono_win64
Windows 10 1909 x64

**Issue description:**
Anonymous async lambda function freezes editor

**Steps to reproduce:**
1. Open Godot editor, Add following code inside any C# script, then F5 once.
`void NoNeedToInvoke() { Func<Task> func = async () => await Task.CompletedTask; }`
2. With editor OPENED use Notepad or VS Code modify anything in this script, like rename method name or just add a comment. The important thing is to SAVE externally.
3. Back to the editor, it should freeze.

**Comment by akien-mga** [comment]
Can you provide a project that triggers the issue?

I tried to follow the steps to reproduce but the given line doesn't compile. I tried adding `using System.Threading.Tasks;` but it still doesn't compile:
```
'Task' does not contain a definition for 'CompletedTask'
```

**Comment by ericrybick** [comment]
@akien-mga 
You probably need a newer .net/mono version.
https://apisof.net/catalog/System.Threading.Tasks.Task.CompletedTask

Unfortunately, I wasn't able to reproduce the freezing.

**Comment by akien-mga** [comment]
Well I have Mono 6.6.0.161 from our official binaries, which should be new enough. But if this requires changing the target framework in the solution to have access to newer APIs, then it definitely needs a MRP.

**Comment by neikeq** [comment]
Even though we default to net45 for Godot projects, you can change it to net46 if you want for new features like this one.
In any case, with #35473 we will default to net47 for new Godot projects.

**Comment by neikeq** [comment]
Sorry, I misunderstood the issue. OP already changed the project to a newer framework. Let me check if I can reproduce the freeze.

**Comment by neikeq** [comment]
Cannot reproduce with 3.2 RC2 on Windows 10 64-bits.

**Comment by slango0513** [comment]
[new_game_project.zip](https://github.com/godotengine/godot/files/4155419/new_game_project.zip)
Sorry for the late reply. The issue appears 100% on my computer with 3.2-beta to 3.2-stable.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by tvardero** [comment]
Unable to reproduce on 3.5-rc8.
Any modification made in external editor (in my case VS Code), were shown in editor immediately, despite Game was running or not.
