### ISSUE TITLE
**Not A Bug**

### ISSUE THREAD

**Issue by AdarshRise** [godotengine/godot#34897]
I recently found GoDot, and I started reading and knowing what is what, and how powerful Godot is as an game engine.
Honestly, It's really super, it's so less bulky and has such nice interface. 

Though, even after spending more than 9Hrs reading and learning about Godot, I didn't find any link to Godot's  Patreon Page.

When I found the page I almost thought it to be fake, but as I read more, I found it to be real.

I wanted to say to the Project Team, Put the Patreon Page link in the readme file under **Support** tab. 

Or at least mention that such patreon Page exists.

Awesome Engine 😄 
 
This is the link.
https://www.patreon.com/godotengine

**Comment by clayjohn** [comment]
If you click the big pink heart on the GitHub page that says "sponsor" it opens a link to the patreon. Likewise on the website the link to the patreon is found under "donate" https://godotengine.org/donate

Please note this issue tracker is for bug reports only.
