### ISSUE TITLE
Godot treats applications made using it as one of its windows

### ISSUE THREAD

**Issue by PopeRigby** [godotengine/godot#34895]
**Godot version:** v3.1.2.stable.flathub

**OS/device including version:**
* Software
  * Operating System: Arch Linux (x86_64)
  * Desktop Environment: KDE Plasma
  * KDE Plasma Version: 5.17.4
  * KDE Frameworks Version: 5.65.0
  * Qt Version: 5.14.0
  * Kernel Version: 5.4.6-arch3-1
  * OS Type: 64-bit
* Hardware
  * Processor: 8 × Intel® Core™ i7-7700 CPU @ 3.60GHz
  * Memory: 15.6 GiB of RAM
  * GPU: GeForce GTX 1060 6 GiB

**Issue description:**
When Godot is opened, and then an application made using Godot is opened, Godot treats that application as one of it's windows, and puts it under the same icon in the KDE Plasma taskbar. This only happens when Godot is opened first, opening the application made using Godot, and then opening Godot treats them as two separate applications in the KDE Plasma taskbar. 

This has been tested using [Pixelorama](https://github.com/Orama-Interactive/Pixelorama) and [Material Maker](https://github.com/RodZill4/godot-procedural-textures), and both the [AUR](https://aur.archlinux.org/packages/godot/) and [Flathub](https://flathub.org/apps/details/org.godotengine.Godot) version of Godot.

**Steps to reproduce:**
1. Open an application made using Godot
2. Open a project in Godot

**Behavior:**
In the taskbar, Godot will have a green plus on its icon, meaning that there are multiple windows open under Godot.
![image](https://user-images.githubusercontent.com/20866468/71918559-63781d80-3137-11ea-9b9b-4264330b3f78.png)
Clicking on the Godot icon gives me the option to either bring the Godot window or the Godot-made application window to the foreground.

**Expected Behavior:**
The Godot-made application is treated as it's own application.

**Comment by FlashDaggerX** [comment]
Just to clarify, you're saying the exported project isn't using its own icon?

**Comment by PopeRigby** [comment]
Yeah. The exported version of Pixelorama still thinks it's part of Godot.

**Comment by FlashDaggerX** [comment]
The code that sets native icons is located in [main/main.cpp, on line 1835](https://github.com/godotengine/godot/blob/5a8107f70a6dc3c43e89df0ad69a5a0124bfc2df/main/main.cpp#L1835).

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by PopeRigby** [comment]
I don't use KDE Plasma anymore, so I can't help. Sorry.

**Comment by KoBeWi** [comment]
So let's just assume this was fixed.
If someone can reproduce in Godot 3.2.3 or newer please comment.
