### ISSUE TITLE
Variable assign to another one isnt possible

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#34899]
**Godot version:**
3.2 beta 4
**OS/device including version:**
ubuntu 18.04
**Issue description:**
Why when you assign this way isnt possible?

`update_func = init_func = exit_func = funcref(self,"method_name")`

this should be possible.

**Comment by Calinou** [comment]
This isn't a bug. Support for Python-style multi-way assignment was never implemented, as most people don't need it often. Please [open a proposal](https://github.com/godotengine/godot-proposals) if you feel a need for this.
