### ISSUE TITLE
html5 export with custom template fail to load game

### ISSUE THREAD

**Issue by artemtech** [godotengine/godot#34903]
**Godot version: 3.1.2-stable 64bit**

**OS/device including version: ArchLinux 64bit- EMScripten latest (1.39.5) - Nodejs (12.9.1)**

**Issue description:**
compiling custom html5 export template optimized by size caused godot fail to load game. After progressbar fully loaded, it return error `"" is not a valid selector` in Firefox 70.0.1 (64-bit).
dunno where is the problem, whether compiled custom export template issue or my project settings. would you help me ?
My projects are entirely 2D based game, just playing with click, and 2D collisions for drag and drop, sound and will use networking. So i dont need extras module like hdr, vr, 3d stuff.

Scene workaround:
```
BaseQuiz (Control)
|-> Background (TextureRect) -> with png texture loaded
|-> Button (Button) -> with assigned text attribute "Hello World"
```
Export setting:
```
1. Vram compression desktop (false), Vram compression mobile (true)
2. Custom Template Release -> locate to webassembly_release.zip below
3. Export name: quiz.html (Enable Debug = false)
```

error generated in python http server:
```
python -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [08/Jan/2020 07:44:59] "GET /quiz.html HTTP/1.1" 200 -
127.0.0.1 - - [08/Jan/2020 07:44:59] "GET /quiz.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Jan/2020 07:44:59] "GET /quiz.wasm HTTP/1.1" 200 -
127.0.0.1 - - [08/Jan/2020 07:44:59] "GET /quiz.pck HTTP/1.1" 200 -
127.0.0.1 - - [08/Jan/2020 07:44:59] code 404, message File not found
127.0.0.1 - - [08/Jan/2020 07:44:59] "GET /favicon.ico HTTP/1.1" 404 -
```
Error generated in browser
![gambar](https://user-images.githubusercontent.com/22854966/71944928-e19bf900-31f7-11ea-92e6-590290361d9f.png)

command to compile custom export template:
`scons platform=javascript target=release tools=no module_visual_script_enabled=no module_gdnative=no disable_3d=yes module_mobile_vr_enabled=no module_hdr_enabled=no javascript_eval=no`

**Minimal reproduction project:**
[base project quiz.zip](https://github.com/godotengine/godot/files/4033305/quiz.zip)
[custom webassembly_release.zip](https://github.com/godotengine/godot/files/4033308/webassembly_release.zip)

**Comment by Calinou** [comment]
> error generated in python http server:

The web server only complains about a 404 error due to the `favicon.ico` request automatically made by the browser. It's completely harmless :slightly_smiling_face:

**Comment by artemtech** [comment]
@Calinou i think it's related with issue #35238, because, i was using emscripten 1.39.5 when compiling the export templates.

**Comment by akien-mga** [comment]
Indeed, 3.1.2 is not compatible with Emscripten 1.39.5, I would advise to downgrade to an older version (e.g. 1.38.47 using `latest-fastcomp`), or move to Godot 3.2 RC 3.
For 3.1.3 I'll aim to cherry-pick relevant changes to make it compatible with the latest Emscripten, but it's getting increasingly complex.
