### ISSUE TITLE
Contributors: Help triage remaining issues in 3.2 milestone

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#34929]
I'm a bit late for our usual call to action (similar to #21855 and #24822), but better late than never :)

We're already at 3.2 beta 5 and things are going relatively well, barring occasional regressions on bugfixes that are always fixed in a timely manner.

I spent quite some time triaging the remaining [**open issues in the 3.2 milestone**](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2), and many of you have done the same, thank you!

This post is a reminder for the others to try and go through issues in the 3.2 milestone which are assigned to you and/or which have a `topic:` label that you're maintainer or co-maintainer of.
Please assess whether you do want to work on the for 3.2, or if they should be kicked back to a later milestone. If you consider that you're wrongly assigned, you can change that too of course (but then try to assess the severity nevertheless and handle the milestone accordingly).

At this stage, we only care about critical bugs, but if you see a few low hanging fruits that you could fix easily, feel free to do so nevertheless.

For contributors who may not have triaging permissions to this repo, you are also very welcome to give us a hand in triaging issues by checking open issues in the 3.2 milestone, check if they are still reproducible in the latest 3.2 build, and leave a comment about your findings.

**Link:** [**Issues in 3.2 milestone**](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2) (493 right now - was 600 a couple days ago before I stormed through the oldest ones)

----

Contributor specific links / tally:

- @akien-mga: [21 bugs](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3Aakien-mga)
- @AndreaCatania: [8 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+assignee%3AAndreaCatania)
- @BastiaanOlij: [2 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3ABastiaanOlij)
- @bojidar-bg: [9 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3Abojidar-bg)
- @Faless: [5 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3AFaless) (check also `topic:network`)
- @groud: [9 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3Agroud)
- @hpvb: [21 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3Ahpvb)
- @JFonS: [4 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3AJFonS)
- @m4gr3d: [2 bugs](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3Am4gr3d)
- @neikeq: [26 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3Aneikeq) (check also `topic:mono`)
- @Paulb23: [2 bugs](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3APaulb23)
- @RandomShaper: [7 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3ARandomShaper)
- @reduz: [30 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3Areduz) (but not expecting much from you given the focus on `vulkan`)
- @vnen: [18 bugs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3Avnen) (check also `topic:gdscript`)
- @YeldhamDev: [3 bugs](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3A3.2+label%3Abug+assignee%3AYeldhamDev)

If you're not listed, either you don't have issues assigned to you, or I missed you :)

Everyone is welcome to use the GitHub search filters to see their issues, or issues in topics they're interested in.

Thanks for your help, let's bring this counter to 0 and release 3.2!

**Comment by clayjohn** [comment]
Can we get a 3.2.1 milestone? For large but low priority bug fixes. For me this is important for GLES3 bug fixes. I don't want to set the milestone to 4.0 but they are low priority and shouldn't block 3.2 either.

**Comment by akien-mga** [comment]
> Can we get a 3.2.1 milestone? For large but low priority bug fixes. For me this is important for GLES3 bug fixes. I don't want to set the milestone to 4.0 but they are low priority and shouldn't block 3.2 either.

As we discussed on IRC, for most issues the usual workflow would be to move them to the `4.0` milestone as that's when they will next be fixed. Any fix can then be cherrypicked for the 3.2.x releases if relevant.

Still, for GLES3 specifically which will go away in 4.0, the proposal is instead to remove them from the 3.2 milestone without setting a new milestone, and instead set the `cherrypick:3.2` label so that we know that those issues are still intended for fixing in later 3.2.x releases if possible.

**Comment by akien-mga** [comment]
Down to 267 issues in the 3.2 milestone today :)

Thanks to all contributors going through the issues to test their validity or assess whether they're critical or easily fixable for 3.2.

Still a bunch to go, but we're on the right track :)

**Comment by akien-mga** [comment]
Now below 50 issues. Let's close this issue and reduce the count further by one :)

**Comment by neikeq** [comment]
> Let's close this issue and reduce the count further by one :)

That's cheating!
