### ISSUE TITLE
Nonexistent latency functions in Audioserver

### ISSUE THREAD

**Issue by Anthys** [godotengine/godot#34922]
**Godot version: 3.1**

Hi,

I've tried to follow [this tutorial](https://docs.godotengine.org/en/latest/tutorials/audio/sync_with_audio.html) on syncing audio with gameplay. However, the [AudioServer class](https://docs.godotengine.org/en/3.1/classes/class_audioserver.html) changed during the Godot 3 update. I can't find any functions related to finding the latency/delay of audio outputs in this class as they were before, are there other alternatives, or did I just missed it?

**Comment by akien-mga** [comment]
This is a tutorial for Godot 3.2, the relevant functions are not backported in the 3.1 branch.
