### ISSUE TITLE
Godot NEEDS a solution for 2D animations with many frames AND normal maps

### ISSUE THREAD

**Issue by davidbejlej** [godotengine/godot#34925]
I have a 2D pixelart animation made in 24fps, around 160 frames and separate normal maps.

At this moment, I have to use animation player and sprite node, and _by hand_ key the change for both diffuse and normal map. Obviously, that's ridiculous.

Adding a normal map layer to AnimatedSprite node would solve this problem.

I know nobody cares about my opinion, but I think it is really necessary since godot prides itself in being great for pixel art.

Also, a build-in toon shader for 2D shaders would be nice.

**Comment by Calinou** [comment]
This repository is now meant to be used for bug reports exclusively. Please open feature proposals on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.
