### ISSUE TITLE
ColorPicker defaults to red and loses focus when dragging mouse out of the canvas

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3492]
As the title says. It actually happens only on the left and bottom sides, i.e. `local_mouse_pos.x<0` and `local_mouse_pos.y>height`.

It's quite annoying as the previous position in the colour scale is lost, and the focus is somehow lost too so you can't click on the color scale to adjust it, you need first to click in the main canvas, and only then you can change the colour "scale" (or ladder or specter or however it's named, the part on the right :p).

It should behave as for dragging on the top and right sides: the picker cursor stays on the edge and moves to match either the x or y mouse coordinate.

**Comment by MarianoGnu** [comment]
Problem is the way Color.set_hsv() implemented, it changes the h s v values and doesn't match the ones selected by hand, a possible approach is to save a hsv cache in color

**Comment by MarianoGnu** [comment]
PS, if you drag hue to the top it clamps to violet for the same reason

**Comment by akien-mga** [comment]
Just to make sure we speak about the same thing, I made a small screencast (I tried the "byzanz" tool to record a gif directly, don't mind the crappy gradients :D - I just want to show out the bug can be reproduced).

![test](https://cloud.githubusercontent.com/assets/4701338/12626294/591cff28-c538-11e5-8543-12ea25213d7b.gif)

**Comment by MarianoGnu** [comment]
Yes, this is because when v is 0 no matter what hue you set, the color is always black.
A hvs cache should fix.this.

**Comment by reduz** [comment]
this is probably one of the only few important issues pending before making an RC, think you could give it a check asap?
