### ISSUE TITLE
Action Mode "Button Press" in BaseButton nodes acts like "Button Release"

### ISSUE THREAD

**Issue by OverloadedOrama** [godotengine/godot#34935]
**Godot version:**
3.2.beta5

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
On BaseButton nodes, if you put their Action Mode to "Button Press", the pressed signal gets sent on button release, and not on button press.

**Steps to reproduce:**
Create a node that derives from Base Button, set its Action Mode to "Button Press", connect the pressed signal to a script that prints something. The value will get printed on button release, not on button press.

**Minimal reproduction project:**
[Godot 3.2 Button Problem.zip](https://github.com/godotengine/godot/files/4037351/Godot.3.2.Button.Problem.zip)

**Comment by volzhs** [comment]
according to source code, it works only with `toggle_mode = true` state.
I'm not sure if it's doc issue or bug.

**Comment by OverloadedOrama** [comment]
This issue wasn't happening in 3.1.x though. And it doesn't make much sense to only be working with `toggle_mode = true`.

**Comment by volzhs** [comment]
it's a regression then.

**Comment by Calinou** [comment]
Is this related to #33422?

**Comment by volzhs** [comment]
different issue
