### ISSUE TITLE
CenterContainer blocks parent from receiving drag and drop

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#34933]
**Godot version:**
Godot (Mono*) 3.2 Beta 5
*The reproduction project uses GDScript to demonstrate the issue

**OS/device including version:**
Manjaro Linux x86_64

**Issue description:**
When the mouse drag is released over a CenterContainer it prevents its parent from receiving the drag data.

**Steps to reproduce:**
See reproduction project + explanation

**Minimal reproduction project:**
[DragAndDrop.zip](https://github.com/godotengine/godot/files/4037238/DragAndDrop.zip)
When dragging on the grey Panel the number `42` is given to Godot as the drag data. When it is released on the left side of the screen the HBoxContainer receives this and prints it. However when released on the right side of the screen the CenterContainer instead blocks it. The VBoxContainers on both sides of the screen do not exhibit this behavior.

**Comment by KoBeWi** [comment]
That's because your CenterContainer has `mouse_filter` set to Stop. When it's set to Pass (same as BoxContainers), it works correctly.

Although I wonder why CenterContainer's default is different. It's still a container.

**Comment by akien-mga** [comment]
> Although I wonder why CenterContainer's default is different. It's still a container.

`mouse_filter` defaults to `MOUSE_FILTER_STOP` in `Control`, which `Container` and thus `CenterContainer` inherit. 
`BoxContainer` and `GridContainer` seem to have local overrides to `MOUSE_FILTER_PASS`. The discrepancy is probably not intended.
