### ISSUE TITLE
Left focus neighbour of Button in HBoxContainer is computed incorrectly

### ISSUE THREAD

**Issue by rburing** [godotengine/godot#34936]
**Godot version:** 3.2-beta5 (also 3.1.2-stable)

**OS/device including version:** Debian Linux 9

**Issue description:**

![Left focus neighbor bug](https://user-images.githubusercontent.com/229837/72057693-14fd8700-32cf-11ea-9302-88c9cac27942.gif)

The description of the property Control → Focus → Neighbour Left (i.e. `focus_neighbour_left`) says:

> If this property is not set, Godot will give focus to the closest Control to the left of this one.

This can fail in a simple HBoxContainer filled with Buttons, with the default settings.

(By contrast, moving to the right works correctly, as does up/down in a VBoxContainer.)

(Also Tab and Shift+Tab work correctly, but I think they use the scene tree layout.)

**Steps to reproduce:**

1. Create a HBoxContainer.
2. Create six Buttons as children with the texts:
    "Greet", "Introduce", "Inquire", "Greet", "Introduce", "Inquire".
3. Play the scene.
4. Click the rightmost button.
5. Press the left arrow a few times and observe the problem.

The size of the buttons (or length of the text) has some influence.

The same buttons with the texts "A", "B", "C", "D", "E", "F" are not a problem.

**Minimal reproduction project:**

[godot-focus.zip](https://github.com/godotengine/godot/files/4037312/godot-focus.zip)

**Comment by rburing** [comment]
The issue must be somewhere in [`Control::_window_find_focus_neighbour`](https://github.com/godotengine/godot/blob/a7f49ac9a107820a62677ee3fb49d38982a25165/scene/gui/control.cpp#L2463).

I guess it may be in the computation of `min` and/or the comparison

    if (min > (p_min - CMP_EPSILON)) {

Probably there should be some (two) cases, based on `p_dir`, for left/right/up/down.

**Comment by rburing** [comment]
Another point is that the `separation` of the HBoxContainer can be `0`, as it is in the example. I think this means that the use of `CMP_EPSILON` may cause the correct neighbour to be overlooked.

**Comment by rburing** [comment]
Maybe @groud could comment on this?

**Comment by groud** [comment]
I never modified the focusing behavior, but I might have a look

**Comment by rburing** [comment]
It turns out this is a regression from 3.0.6-stable; the bug is first introduced in release 3.1-alpha1.

Bisection identifies the commit [4d78e16bc1](https://github.com/godotengine/godot/commit/4d78e16bc1bf265da32858a38aa75a1233421da4) as the cause.

**Comment by groud** [comment]
Wow, that's kind of an unexpected side effect from this commit...  There is likely a weird thing done to find the next element to focus.

**Comment by rburing** [comment]
Found the bug! Basically, it was a typo. Inside `_window_find_focus_neighbor`, in the definition of the `points` array, the call to `get_size()` should be `c->get_size()` instead. (Hence, the bug is invisible when the buttons are of a similar size.)

**Comment by rburing** [comment]
This should be labeled a regression, and it would be nice to have the fix merged in 3.2.

@groud could you review the pull request?
