### ISSUE TITLE
animationtree statemachine animation speed (2d) solved

### ISSUE THREAD

**Issue by zomman** [godotengine/godot#34947]
**Godot version:**
godot 3.1 & godot 3.2

**OS/device including version:**
windows 10

**Issue description:**
I tried animationtree statemachine in 2d animation, animation travel between nodes worked fine, but I can't change the speed of animation. I set the speed of animation in animationplayer playback options to any number, it won't work. if i use animationplayer to play the animation, the changes of speed worked.

**Steps to reproduce:**
Sprite
    AnimationPlayer(sprite:frame)
    AnimationTree(statemachine)

**Comment by zomman** [comment]
You had to change the speed use  timescale node in blendtree. so i think it should be disable the speed of animationplayer or warning if you had add a animationtree node, or adding an alternative 
 to choose to keep animationplayer speed in animationtree node. because you had provide to use the statemachine only to control animation playback.

**Comment by Calinou** [comment]
@zomman Should this issue be closed? It seems you found a solution to your problem. Let us know if the documentation should be improved.

**Comment by zomman** [comment]
I think there could be a warning about the disable of animationplayer speed in animationtree in the document. I made my animation in other tool, then imported into godot. I naturally ajusted the speed of my animation to run as my design, when I bumped into this problem, I found no info about this.
 
---Original---
