### ISSUE TITLE
File.get_csv_line() should accept custom delimiter

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#3495]
I can't use this nice function now, because it's fixed comma delimiter. It would be nice if it could be called with a delimiter given like File.get_csv_line(";") in my case.

**Comment by akien-mga** [comment]
Sounds like a good idea, and as long as the parameter is made opt-in (i.e. defaults to ","), it should not break existing projects.

**Comment by reduz** [comment]
csv format is pretty standard, but a contribution for adding this is fine

**Comment by trtstm** [comment]
I added it here https://github.com/trtstm/godot/commit/bc721a9c20a6bd953543611a8f5b887ecfbb1d5d
But I have some questions:
Is there a better way than using

    ERR_FAIL_COND_V(delim.length()!=1,Vector<String>());

Also what's the point of

	String l;
	int qc=0;
	do {
		l+=get_line();
		qc=0;
		for(int i=0;i<l.length();i++) {

			if (l[i]=='"')
				qc++;
		}


	} while (qc%2);

in https://github.com/trtstm/godot/blob/bc721a9c20a6bd953543611a8f5b887ecfbb1d5d/core/os/file_access.cpp#L284

**Comment by reduz** [comment]
Last code is because a newline may be contained inside quoted text, as this
is valid csv

**Comment by trtstm** [comment]
Well if you approve this, ill make a pull request.

**Comment by vnen** [comment]
@trtstm if the code is already done, you can make a pull request. It'll be merged if approved or otherwise closed. That's what PRs are for :wink:

**Comment by akien-mga** [comment]
Fixed by #3502.
