### ISSUE TITLE
Godot crashes when a scene has the tool keyword and _exit_tree() method

### ISSUE THREAD

**Issue by TheSkyOne** [godotengine/godot#34959]
**Godot version:**
godot 3.2beta5
**OS/device including version:**
windows 10 pro 64 bit
**Issue description:**
when a scene has the tool key word and the method _exit_tree(): which contains queue_free()
the project editor will crush with no errors
**Steps to reproduce:**
--create a new scene (doesnt matter what node type)
--save the scene and create a script for the scene
--add the following code to it:
tool
extends <the node type of your scene>
func _exit_tree():
queue_free()
-- save the script and go to the inspector
--try to create an empty scene, or try to switch from current scene to a different one

**Minimal reproduction project:**

[minimal_project_to_reproduce.zip](https://github.com/godotengine/godot/files/4041771/minimal_project_to_reproduce.zip)

**Comment by fire** [comment]
The function breaks at void EditorNode::_update_scene_tabs();

The _update_scene_tabs function tries to use an is_queued_for_deletion function.

**Comment by timothyqiu** [comment]
I think this is in the same situation as #35422.

**Comment by akien-mga** [comment]
Indeed, `tool` scripts give you access to the scene tree, which means that they also let you do dangerous operations like freeing the scene which is currently being edited, leading to a crash. This is expected and one of the limitations involved in having such a feature.
