### ISSUE TITLE
Mono editor leaks orphan nodes

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#34954]
**Godot version:**
3.2 beta 5 mono
Master branch (e97e951)

**OS/device including version:**
Linux 64-bit

**Issue description:**
When running a minimal project with a single scene and script, nodes are leaked:
```
Mono: Unloading scripts domain...
Mono: Runtime cleanup...
Mono: Finalized
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2076.
Leaked instance: AnimationPlayer:19747 - Node name: 
Orphan StringName: ..
Orphan StringName: AnimationPlayer
StringName: 2 unclaimed string names at exit.
```

**Steps to reproduce:**
- Run attached project with `-v`

**Minimal reproduction project:**
[Test Mono.zip](https://github.com/godotengine/godot/files/4040690/Test.Mono.zip)

**Comment by akien-mga** [comment]
Tested a few older releases and the same happens in all official betas (did not try alphas).
The leaked `AnimationPlayer` matches the root and only node of my main scene.

**Comment by akien-mga** [comment]
If I then export this project for Linux and close the editor, I leak a couple more nodes:
```
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2076.
Leaked instance: Image:3496 - Resource name:  Path: 
Leaked instance: AnimationPlayer:19760 - Node name: 
Leaked instance: Image:3500 - Resource name:  Path: 
Orphan StringName: ..
Orphan StringName: AnimationPlayer
Orphan StringName: Image
StringName: 3 unclaimed string names at exit.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```

**Comment by neikeq** [comment]
I'm going to push a fix for the AnimationPlayer leak. Can you open a new issue for the Image leak? It's a different bug and may need some more thought to fix it.

**Comment by neikeq** [comment]
As commented, the PR only fixes the AnimationPlayer leak.
