### ISSUE TITLE
FileSystem panel resets view mode when opening a new scene

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#3496]
this is only a little glitch but could be annoying.
If you set the FileSystem panel to show files as a list, when you load a scene from disk, the panel will switch back to icons view mode.

**Comment by reduz** [comment]
i think there is an option to choose default view mode in editor settings, is this not what is desired?

**Comment by zoiba** [comment]
the option in editor setting is ok and it works fine. I know, is a small quirk, but what I mean is if you switch mode from the panel's icon, the mode you set in that moment should persist if you open a new scene.

**Comment by reduz** [comment]
moving to 2.1, far too close to stable release to add enhacements now, please wait 2 weeks :)

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.
