### ISSUE TITLE
debugger video mem section works only after refresh

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3497]
![screenshot from 2016-01-28 17-59-33](https://cloud.githubusercontent.com/assets/6195060/12651099/e289600c-c5ed-11e5-9c53-5421b0daff8b.png)
Not sure if a bug but I set a break point and went to the video mem section to find it empty. I have to hit the refresh button for it to work.
Maybe have it refreshed automatically on breakpoints?

**Comment by reduz** [comment]
not a bug, it's a lot of information to send automatically, plus you are meant to inspect the data so you don't want autorefresh either

**Comment by lordadamson** [comment]
I suggest that at the first time instead of having to hit the refresh button there would be a button in the middle saying "retrieve info" or something.
It would be more usable because hitting refresh at the first time wasn't obvious to me.
