### ISSUE TITLE
Inconsistent trimming of spaces when editing group name

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34973]
**Godot version:** 3.2.beta.custom_build.76678b260

**OS/device including version:** macOS Catalina 10.15.2 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

The editor has different ways of handling the leading and trailing spaces in group name. I'm not sure which one is the expected behavior.

In the Node dock:
* Add current node to group: the spaces are kept

In the Group Editor dialog:
* Create new group: the spaces are trimmed
* Rename group: the spaces are kept

Also, in all the three cases, a string with only spaces in it is considered invalid.

Should these spaces be trimmed? I think it's better to trim them, because it's hard to tell if there is any trailing spaces.

**Steps to reproduce:**
1. Select any node in any scene
2. Switch to the Node dock, and choose Groups
3. Type " X " (X surrounded by one space) in the LineEdit and click the Add button
    * The group added is named " X ", the spaces are kept
4. Click the Manage Groups button to open the Group Editor
5. Type " Y " (Y surrounded by one space) in the LineEdit and click the Add button
    * The group added is named "Y", the spaces are trimmed
6. Double click "Y" in the list to edit the group name
7. Type " Z " ( Z surrounded by one space) and hit enter
    * The group is renamed to " Z ", the spaces are kept

**Comment by akien-mga** [comment]
I think it should be changed to always trim spaces.
