### ISSUE TITLE
Instancing a scene by tool script vs. dragging from FileSystem -bug

### ISSUE THREAD

**Issue by takaturre** [godotengine/godot#34971]
**Godot version:**
3.1.2 stable

**OS**:
Win 10

**Issue description:**
- When instancing a scene by script and adding it to the currently edited scene (and setting owner), the scene works fine except for one thing: When modifying the original scene and saving it, the modifications are not updated to the main scene (where it was instanced).
- However, if you then drag the same scene from the FileSystem dock to the scene (so there are now two nodes referencing the same scene), and then modify the original scene and save, *both* are updated (~ problem gets fixed). 
- Another way to "fix" the problem, is to save the main scene (where the instancing was going on), and close it and reopen it. After that, you can again modify the original scene and save it, to get updates on the main scene.

**Steps to reproduce:**
1. Instance a scene by script, and add it to the edited root as editable:
```
var new_scene : Node = load("res://Child.tscn").instance()
add_child(new_scene)
new_scene.owner = get_tree().get_edited_scene_root()
```
2. Click the scene icon to open up the original scene.
3. Do some modifications (eg. move a child node around), and save the original scene.
4. Go back to the main scene: Situation is not refreshed. Dragging the node around (to `_enter_tree` / `_exit_tree` won't help either).

**Minimal project:**
[InstancedSceneByScript.zip](https://github.com/godotengine/godot/files/4043582/InstancedSceneByScript.zip)

**Comment by volzhs** [comment]
```gdscript
var new_scene : Node = load("res://Child.tscn").instance(PackedScene.GEN_EDIT_STATE_INSTANCE)
```
this will fix your issue.

**Comment by takaturre** [comment]
Thanks - works like a charm..! I had been wondering earlier what those edit states mean :)
So, seems this is a feature, so I close this.
