### ISSUE TITLE
Exported app crashes if opened with a command line argument

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#34972]
**Godot version:**
3.1 classic
3.2 beta 5 mono

**OS/device including version:**
MXLinux 19 x64

**Issue description:**
I get this on the console after opening the app

ERROR: _load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:285.
ERROR: start: Condition ' !scene ' is true. returned: false
   At: main/main.cpp:1739.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2095.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425.

**Steps to reproduce:**
Export a project and pass a command line argument to it

**Comment by akien-mga** [comment]
What argument? Please give the exact command.

This error is expected of the argument is not recognised and interpreted as the path to a scene.

**Comment by MightyPrinny** [comment]
@akien-mga  any argument, I wanted to load a file on the app through a command line argument using OS.get_cmdline_args, but any argument causes the app to crash

**Comment by akien-mga** [comment]
That's normal, you can't pass custom arguments this way currently. See #8721 for details.
