### ISSUE TITLE
'X509Certificate' is not instantiable on html5

### ISSUE THREAD

**Issue by Vadimledyaev** [godotengine/godot#34993]
**Godot version:**
Godot v3.2.beta.calinou.7f56ef365
**OS/device including version:**
Chrome Win10 / Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)
**Issue description:**
I am trying to set up a wss server using Linux server and HTML5.
First I set up an insecure connection and it worked pretty well, but I can't let it work with wss; I get **ERROR**: Class type: 'X509Certificate' is not instantiable.
**Steps to reproduce:**
Compile for html5 with this code:

> var certificate:X509Certificate = X509Certificate.new()

**Minimal reproduction project:**
```
extends Node

# The URL we will connect to
var websocket_url:String = "wss://82.223.204.60:443"
var connected:bool

# Our WebSocketClient instance
var _client = WebSocketClient.new()
var reconnectTimer:Timer 
const reconnectionTimeout:int = 5


func _ready():
    # Connect base signals to get notified of connection open, close, and errors.
    _client.connect("connection_closed", self, "_closed")
    _client.connect("connection_error", self, "_closed")
    _client.connect("connection_established", self, "_connected")
    # This signal is emitted when not using the Multiplayer API every time
    # a full packet is received.
    # Alternatively, you could check get_peer(1).get_available_packets() in a loop.
    _client.connect("data_received", self, "_on_data")

    reconnectTimer = Timer.new()

    var certificate:X509Certificate = X509Certificate.new()
    print(certificate.load("res://starville.world_ssl_certificate.crt"))
    _client.trusted_ssl_certificate = certificate
    #_client.verify_ssl = true

    # Initiate connection to the given URL.
    reconnect()

func reconnect():
    print("reconnect, url: " + websocket_url)
    var err = _client.connect_to_url(websocket_url)
    if err != OK:
        print("unable to connect")
        set_process(false)
        if(!reconnectTimer.get_parent()): 
            add_child(reconnectTimer)
        reconnectTimer.stop()
        reconnectTimer.set_wait_time(reconnectionTimeout)
        if(!reconnectTimer.is_connected("timeout", self, "reconnect")):
            reconnectTimer.connect("timeout", self, "reconnect")
        reconnectTimer.start()
    else:
        print("Connected")
        reconnectTimer.stop()
        if(reconnectTimer.get_parent()): remove_child(reconnectTimer)
        set_process(true)

func _process(delta):
    # Call this in _process or _physics_process. Data transfer, and signals
    # emission will only happen when calling this function.
    if(_client != null): _client.poll()

func _closed(was_clean = false):
    # was_clean will tell you if the disconnection was correctly notified
    # by the remote peer before closing the socket.
    print("Connection closed, clean: ", was_clean)
    set_process(false)
    if(!reconnectTimer.get_parent()): 
        add_child(reconnectTimer)
    reconnectTimer.stop()
    reconnectTimer.set_wait_time(reconnectionTimeout)
    if(!reconnectTimer.is_connected("timeout", self, "reconnect")) :
        reconnectTimer.connect("timeout", self, "reconnect")
    reconnectTimer.start()
    connected = false

func _connected(proto = ""):
    # This is called on connection, "proto" will be the selected WebSocket
    # sub-protocol (which is optional)
    print("Connected with protocol: ", proto)
    # You MUST always use get_peer(1).put_packet to send data to server,
    # and not put_packet directly when not using the MultiplayerAPI.
    var varvar = {"hello": "world"}
    _client.get_peer(1).put_var(varvar, true)
    connected = true

func _on_data():
    # Print the received packet, you MUST always use get_peer(1).get_packet
    # to receive data from server, and not get_packet directly when not
    # using the MultiplayerAPI.
    var received = _client.get_peer(1).get_var(true)
    print("Got data from server: ", str(received))


func _exit_tree():
    _client.disconnect_from_host() 
```

**Comment by Calinou** [comment]
As far as I know, the HTML5 export uses the browser's WebSocket features rather than relying on a custom implementation. Therefore, you can't bypass the browser's security policies.

**Comment by Faless** [comment]
> As far as I know, the HTML5 export uses the browser's WebSocket features rather than relying on a custom implementation.
> (It's technically impossible to have an implementation that behaves identically to native exports, as it'd let you bypass the browser's security policies.)

Correct, and the `X509Certificate` class is not instantiable because the mbedtls module is disabled by default in HTML5 builds (but would still not work with WebSocket due to browser limitations as you explained).
I'm wondering if we should enable the mbedtls module by default though, to provide the `Crypto` class implementation (or alternatively provide a `Crypto` class based on [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API)).
As a bare minimum, documentation should be updated to mention/explain these limitations. I'm adding the documentation tag for now.

**Comment by Vadimledyaev** [comment]
Thanks! I'm sorry for being silent for a while. 
At this moment I have a headless server running on one IP and a html5  game on a website running on another IP/domain.

I am sorry but I'm a bit frustrated with all the security stuff; I have a couple of cer files (world and world_intermediate) and a private key of the **web** server, and I also figured out how to generate and save a self-signed pair in Godot.

Which one should I use in websocketClient to connect to the server ip?

Thanks!

**Comment by Faless** [comment]
@Vadimledyaev you can't use self-signed certificates in HTML5 exports. The users would have to manually install the certificate in their browsers. What you want to do is get a valid certificate for the hostname that is running the websocket server, install it appropriately on the server, and connect to that hostname (not the IP address directly).
You can get free valid certificates from CAs like [letsencrypt](https://letsencrypt.org/)

**Comment by Vadimledyaev** [comment]
Thanks for clarifying, but do you mean the server is only accessible by domain name and shall also host the web pages with client html5 builds?

**Comment by Faless** [comment]
> and shall also host the web pages with client html5 builds?

No, the build could potentially be served by a different machine running its own HTTP server

**Comment by Vadimledyaev** [comment]
THanks a lot Faless and Calinou!
