### ISSUE TITLE
Rename Project dialog size sometimes too large

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#35008]
**Godot version:** v3.2.beta.custom_build.0b185278f

**OS/device including version:** macOS Catalina 10.15.2 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

The Rename Project dialog has extra space at the bottom:
* the first time it opens, or
* after the New Project dialog was opened

If you close the wrong sized dialog and open again, it has the correct size.

**Steps to reproduce:**
1. Open the Project Manager
2. Select an existing project, and click Rename
    * The dialog has extra space at the bottom (the same size as the New Project dialog)
3. Close the dialog, and click Rename again
    * The dialog has no extra space at the bottom (the expected size)
4. Close the dialog, and click New Project
5. Close the dialog, and click Rename again
    * The dialog has extra space at the bottom

![demo](https://user-images.githubusercontent.com/372476/72203986-fb666600-34ad-11ea-8fbf-83dc1ad30a0d.gif)

**Comment by nathanwfranke** [comment]
I can easily reproduce this in 3.2 beta 5

**Comment by nathanfranke** [comment]
This was fixed in master, I made a new pull request that we can merge to 3.2 so that this annoying bug can be fixed.

**Comment by akien-mga** [comment]
Closed by #38706.
