### ISSUE TITLE
Show joystick axis names for InputMap actions

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#3501]
Joystick buttons have these little helper strings in the InputMap actions,  like `"XBOX A, PS X,..."`.
I think the same should also be done for joystick axes, as it might not be obvious for new users which index to choose.

Also related to this: why can you choose between 11 axes? I think we officially only support 7

![too_many_axes.png](http://i65.tinypic.com/2iup7h3_th.png "too many axes?")

**Comment by Hinsbart** [comment]
Although, I think it's generally a bad idea to bind axes to Input actions. One should do it the proper way and check for deadzones etc.
Maybe this should be removed at some point?

**Comment by reduz** [comment]
it uses 0.5 as treshold so it should generally work. Tested it with a few joypads. This is used mainly for making joy axis work with UIs (move between buttons).

Regarding names, I don't really know, are the axis numbers standard? If so what are the names?

**Comment by Hinsbart** [comment]
Ok, 0.5 is reasonably for UIs, didn't check that sorry :P 

I would call the axis numbering standard, yes. Platforms should send gamepad events using the following indexing:

```
0 left stick x
1 left stick y
2 right stick x
3 right stick y
4 
5
6 L2
7 R2
```
Of course I can say this only for the open-source code, so I don't know if there are any platforms that might use axes 4 and 5. 
Also, the button variant has entries for the wii, don't know if the nunchuk stick is regarded as the left or right one, or whether the wiimote's rotation is recieved as joystick axes.

**Comment by reduz** [comment]
Is this how it usually works in most joypads? in all desktop platforms?
I ask out of curiosity, don't really know

**Comment by punto-** [comment]
No :p But the remapping code should recognize the device and map to this on
desktops. On consoles we can hardcode the remapping, so if we name the axes
somewhere, they'll get remapped correctly, it shouldn't be a problem.
