### ISSUE TITLE
Node groups doesnt work for instances

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#35023]
**Godot version:**
3.2 beta 5, was happening in beta 4 too
**OS/device including version:**
ubuntu 18.04
**Issue description:**
Imagine a kinematic body character, which has a group called "player" attached, i have a built-in script attached, and when _ready() occurs it instantiate this character , and then instantiate a camera which needs this character reference to look at, but it does not detect any node in group player

update: printed get_groups() of character->
[player, idle_process, physics_process]

**Steps to reproduce:**
 Described above, and below
**Minimal reproduction project:**
clone this repo: https://github.com/nonunknown/crashcreator
and play this scene: res://scenes/scn_Gameplay.tscn

**Comment by bojidar-bg** [comment]
Tested with https://github.com/nonunknown/crashcreator/tree/74a9021e0724fd65291f8238f15328aba5cf971b and https://github.com/nonunknown/crashcreator/tree/alpha. Could not locate the issue in either.

Please submit an actual minimal project, one that does not require waiting a minute or so for reimporting the assets.
