### ISSUE TITLE
some signals doesn't work with label

### ISSUE THREAD

**Issue by tsrite88** [godotengine/godot#35028]
**Godot version**: 3.1.2 stable
**OS/device including version**:Windows 10
**Issue description**: some signals (mouse_entered(), mouse_exited() and gui_input() ) doesnt work on label

**Steps to reproduce:**
create a new project
add a control
add a child label
resize the label to make it half the window
select the label, create and connect a signal for mouse_entered() or mouse_exited() or gui_input()
put a print("work!!") in the created function
launch the project, move the mouse everywhere
no message displayed in the output
try exactly the same with a button, it's work very well

**Comment by Calinou** [comment]
Label has its mouse mode set to Ignore by default. This means it won't intercept any mouse events, and is done by design.
