### ISSUE TITLE
C# Cant change (properly) exported variables in the inspector after closing the game

### ISSUE THREAD

**Issue by Flyboy1010** [godotengine/godot#35029]
Godot_v3.1.2-stable_mono_win64

Windows 10 home 10.0.18362

Cant change (properly) exported variables after closing the game

Run your game scene, close it and then try to change an exported variable in the inspector, you cant select them but if you write the number (which is not showing in the textbox) and then press enter it changes so i think its a visual bug or something but is quite annoying

Of course when i closed the game i didnt modify the c# script so i didnt need to recompilate

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Flyboy1010** [comment]
yep, the issue is still there

**Comment by Tobi-Mob** [comment]
Works properly on Godot 3.3.3 Linux (Ubuntu/Mint) for me.

**Comment by Calinou** [comment]
Closing as resolved per @Tobi-Mob's comment.
