### ISSUE TITLE
Remote debug suddenly stopped unable connected. Error status 1

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#35020]
**Godot version:**
3.1.2
**OS/device including version:**
windows x64
**Issue description:**
![2020-01-12_012736](https://user-images.githubusercontent.com/34160378/72208914-49459300-34db-11ea-9966-044dea39dc5f.png)
I don't know why but i have checked that port 6007 are not used by any other program and localhost was 127.0.0.1. Sometime it will random display this error, the only way to fix it was reset my computer, re-open it not fix this
When this error happen, the program still running, but i have to wait about 5-6s before it running

**Comment by Calinou** [comment]
@rieniter Are you able to reproduce this in all projects or just in a specific project?

**Comment by rieniter** [comment]
> @rieniter Are you able to reproduce this in all projects or just in a specific project?

It just happen in Godot 3.1.2, i already import my project to 3.2 and still not get this problem. I think that error was caused when i tried to open my webserver localhost and some Emulator machine

Thank you!

**Comment by Calinou** [comment]
@rieniter Thanks for replying :slightly_smiling_face: I'll close this as resolved then.
