### ISSUE TITLE
HTML5 temp files remain locked after first run from IDE

### ISSUE THREAD

**Issue by tinyBigGAMES** [godotengine/godot#35036]
**Godot version:**
3.2 beta 6

**OS/device including version:**
Windows 10 Pro 1909 (build 18363.535)

**Issue description:**
If you run HTML5 from the IDE, it updates and runs the first time, on subsequent runs, the /temp_js_*. files remain locked by the IDE apparently and will not update until you close and restart the IDE.

**Steps to reproduce:**
Add html5 export (tick it runnable) and run, then run again.

**Minimal reproduction project:**
Seems to have this issue with any project I try.

**And yes...**
* I have Godot related folders excluded from Windows defender (even turned it off, same problem).
* Stopping the HTTP server does not solve the problem

**Comment by akien-mga** [comment]
I guess they would be unlocked if you use "Stop HTTP Server" before re-deploying.

@Faless I guess it might be better to always restart the HTTP server and thus free the lock on previous files before re-exporting?

**Comment by tinyBigGAMES** [comment]
Yes, I've tried stopping the HTTP server, still files remain locked because of the IDE it seems. If you go to the temp folder and try to remove them from explorer, you get message saying they are locked by Godot. Once you shut it down, then they can be removed/updated.
