### ISSUE TITLE
When Using maths inside inspector apply it to each selected node individually

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#35039]
In this https://github.com/godotengine/godot-proposals/issues/369 I was advised to rise it as bug report 

**Godot version:**

3.1.2

**OS/device including version:**

Win 10 

**Issue description:**

Inspector allows users to use paths inside it rather than type numbers for example if we select a sprite and in transform x we type +25 it will be moved by 25 pixels . Problem starts when we have multiple selected nodes if we select multiple nodes and type +50 position will be calculated only once and assigned to all nodes

https://streamable.com/m170v

This is not what we want to accomplish at all. 

What user really wants is to move all sprites by 50 pixels like this

![1](https://user-images.githubusercontent.com/30668026/72075270-4c7a2c80-32eb-11ea-84fa-31b6d885f8b7.PNG)

**Steps to reproduce:**

Described above

**Minimal reproduction project:**

Happens in every project ever.

**Comment by Calinou** [comment]
I could see it being difficult to fix. Right now, EditorInspector will pass its numeric fields to the Expression class. However, how can we distinguish an expression result (e.g. `350 + 50`) from a single value entered directly (`400`)? At the end of the day, the engine will "see" the same thing.

**Comment by KoBeWi** [comment]
This is not really a bug, more a limitation of MultiNodeEdit. Although "fixing" this makes sense.

Still, either this or [the proposal](https://github.com/godotengine/godot-proposals/issues/369) should be closed.

**Comment by YuriSizov** [comment]
I agree, this is not a bug, and opening a proposal was the correct idea. This is indeed something that is not supported at all and must be figured out and then implemented.
