### ISSUE TITLE
Tab container with invisible tabs still expands rect size

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#35030]
**Godot version:** 3.2 Beta 5

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
![image](https://user-images.githubusercontent.com/14253836/72212165-aff78c00-349c-11ea-93b7-f6e13d9028ab.png)
![image](https://user-images.githubusercontent.com/14253836/72212167-b1c14f80-349c-11ea-873d-329e7b5e7857.png)

The rect size calculation does not reduce when tabs are not visible

**Steps to reproduce:**
Create a tab container with a child such as a label with a single line of text
Disable tabs visible, and you will see that the panel has a huge margin on the bottom

Other Notes:

- If you make a tab with a ridiculous margin, it continue to match the same height. Even while the tabs are not visible, it will expand immediately
![image](https://user-images.githubusercontent.com/14253836/72212231-cf42e900-349d-11ea-98c0-4e3ee5058190.png)
![image](https://user-images.githubusercontent.com/14253836/72212235-d964e780-349d-11ea-80b1-9f62df03908d.png)
- "Use Hidden Tabs for min size" really sounds like it would cause this, but it is referring to the content below the tabs. Regardless, it is disabled currently
- Cherry pick 3.2?

**Minimal reproduction project:**
[Test4.zip](https://github.com/godotengine/godot/files/4050080/Test4.zip)

**Comment by aaronfranke** [comment]
I'm assigning this to the 3.2 milestone because there is already a simple PR that fixes the problem.

@akien-mga If that was the wrong decision, please let me know, since this isn't a critical problem and we're really close to the release of 3.2.

**Comment by akien-mga** [comment]
@aaronfranke At beta stage it would have been fine, but it's too late now after RC 3. Next release is meant to be stable, so I won't pull in a `scene/gui` change that can impact both the editor and games in unexpected ways. It can be merged after 3.2, and cherrypicked for 3.2.1.
