### ISSUE TITLE
3.2 beta 6: enabling both use_vsync and sync_via_compositor halves the refresh rate of windowed games

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#35038]
**Godot version:**
3.2.beta6

**OS/device including version:**
Windows 10 1909
Radeon VII
Adrenalin 19.9.3, 20.1.1

**Issue description:**
Enabling both _use_vsync_ and _sync_via_compositor_ halves the refresh rate of windowed games. Also occurs in the editor. Issue may be present in earlier builds.

**Comment by akien-mga** [comment]
CC @Calinou @TerminalJack, this is probably due to syncing with the compositor which was enabled by default in beta 6: #34968.

**Comment by TerminalJack** [comment]
> 
> 
> CC @Calinou @TerminalJack, this is probably due to syncing with the compositor which was enabled by default in beta 6: #34968.

Yes, I bet you're correct.  There must be video drivers or driver settings that proactively do a `DwmFlush()` each time `SwapBuffers()` is called--even though the swap interval is set to 0.  Basically they are already doing what we do when the sync_via_compositor setting is enabled.

It seems like most people aren't affected by the stutter/jitter issue that the setting is meant to correct so it might be a good idea to revert the change that makes it enabled by default.  This would address the issue in the short-term.

**Comment by hoontee** [comment]
Can confirm that disabling it fixes the issue.

**Comment by Calinou** [comment]
@hoontee Out of curiosity, which graphics card model do you have (and which driver version are you using)?

**Comment by hoontee** [comment]
> 
> 
> @hoontee Out of curiosity, which graphics card model do you have (and which driver version are you using)?

AMD Radeon VII - Tested with Adrenalin 19.9.3 and 20.1.1.

**Comment by Jakob-PB** [comment]
I'd like to point out that this issue doesn't necessarily lock the editor/game to 30 FPS but rather to half of the monitor refresh rate (see #35065).

**Comment by hoontee** [comment]
Updated the issue to reflect new findings.

**Comment by hoontee** [comment]
So I've discovered that forcing vsync in graphics card settings is what's causing the halved framerate. Letting the application decide fixes the issue.

![image](https://user-images.githubusercontent.com/5272529/72309954-1075fd00-3646-11ea-84b2-a1135feb08e2.png)
