### ISSUE TITLE
Test Width / Height in Project Settings should be ignored on exported game.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#35041]
**Godot version:**
Godot Engine 3.2 beta 6

**OS/device including version:**
Windows 10

**Issue description:**
If you set Test Width and Test Height in Project Settings > Display > Window > Size, the exported game (platform windows, havent test on other platform) also runs in this size.
CMIIW, this should only work on Editor.

**Steps to reproduce:**
Go To Project Settings > Display > Window > Size
Fill Test Width and Test Height (use different value from Width and Height)
Export
Play

**Minimal reproduction project:**

**Comment by timothyqiu** [comment]
According to #16863, these two are meant to be the window width and window height.

**Comment by Calinou** [comment]
You can make this property only effective in the editor by overriding it with the `editor` [feature tag](http://docs.godotengine.org/en/latest/getting_started/workflow/export/feature_tags.html).

That said, those project settings should probably be renamed for 4.0.

**Comment by Calinou** [comment]
I'll close this, as renaming settings for Godot 4.0 is better covered in #16863.
