### ISSUE TITLE
Godot Crashs on Edit Game in GLES3 -> Win7 32

### ISSUE THREAD

**Issue by FragileBoxGames** [godotengine/godot#35047]
![Sem títul1](https://user-images.githubusercontent.com/53179496/72220246-728f0f00-352d-11ea-867a-331d71f3fa88.png)

ON EDIT GAME IN GLES3 THE WINDOWS CRASH VIDEO DRIVER! PLIS FIX
gd 3.2 beta 6

**Comment by akien-mga** [comment]
This cannot be fixed on our side. Possible causes:
- Your GPU is too old to support GLES3. You should use GLES2.
- Your GPU drivers are not up to date and have a bug.
- Your GPU drivers are up to date but are buggy and don't properly support GLES3.
