### ISSUE TITLE
3.2 BETA 6 - Android Crash - No implementation found for double_tap(int, int) exception.

### ISSUE THREAD

**Issue by skoovo** [godotengine/godot#35049]
**Godot version:**
3.2 BETA 6

**OS/device including version:**
Windows 10 Pro  64 bit 1909

**Issue description:**
Since updating to BETA 6, my Android app now crashes when the screen is touched too rapidly. Same app worked fine in BETA 5. This issue is present when using regular Android deployment, as well as a custom build. Logcat output points to:

`java.lang.UnsatisfiedLinkError: No implementation found for void org.godotengine.godot.GodotLib.double_tap(int, int) (tried Java_org_godotengine_godot_GodotLib_double_1tap and Java_org_godotengine_godot_GodotLib_double_1tap__II)`

**Steps to reproduce:**
Deploy an app to Android and tap the screen rapidly

If you need any more information, please let me know. Thanks.

**Comment by akien-mga** [comment]
Regression from #33630, CC @AlexHolly.

**Comment by Janders1800** [comment]
Can confirm. Happens to me as wel l.

**Comment by HEAVYPOLY** [comment]
Confirming here on Samsung Note 9, happens with Pen or touch

**Comment by Toshiwoz** [comment]
Oh gosh, I was going crazy trying to find out where I made a mistake, or where godot's behaviour has changed since beta5.
Gosh, thanks guys for reporting and also for those who have worked a fix for this regression... cant' wait for beta 7!
