### ISSUE TITLE
Class reference is permanently case-sensitive

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#35048]
**Godot version:**
Godot 3.2 beta6

**Issue description:**
I noticed that since few versions the built-in class reference is case sensitive and there's no way to disable it.

**Steps to reproduce:**
1. Open class reference
2. Go to `@GlobalScope`
3. Type "key_enter"
4. Expect KEY_ENTER to show
5. Nope, not happening

**Comment by akien-mga** [comment]
Works for me:
![Screenshot_20200112_200851](https://user-images.githubusercontent.com/4701338/72224166-63cd4a00-3577-11ea-8e72-fee27183d702.png)

You probably enabled case sensitivity?
![Screenshot_20200112_200928](https://user-images.githubusercontent.com/4701338/72224175-73e52980-3577-11ea-8949-f2621a5419fa.png)

**Comment by KoBeWi** [comment]
I mean the class reference, not help search.
