### ISSUE TITLE
Zoom levels not working correctly in scene editor with custom editor display scale

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#35059]
**Godot version:**
3.2 beta 6 mono

**OS/device including version:**
MXLinux19 64 bits

**Issue description:**
I have my editor display scale set to 0.85, in beta 5 the scene editor could zoom correctly, values like 100%,200%,400%, etc, would give a pixel perfect look, but in beta 6 everything looks off(smaller), this is highly noticeable on small unfiltered textures.

**Steps to reproduce:**
Change your editor display scale and see how zoom levels like 100% don't look as good as you'd expect on unfiltered textures.

**Comment by YeldhamDev** [comment]
CC @Calinou

**Comment by akien-mga** [comment]
Likely regression from #34824.

**Comment by Calinou** [comment]
I guess we can solve this by clamping the editor scale to 1 for editor zoom operations.
