### ISSUE TITLE
Child nodes of a viewport node are not selectable

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#3505]
I can't tell since when, but objects that are children of a Viewport cannot seem to be selected, highlighted or movable in the editor. For example, adding a Camera2D will be practically invisible, and Sprite2D will be seen but they won't get their resize/move boxes. They work as before in-game, though, and this is only editor behavior.

**Comment by akien-mga** [comment]
It was actually done on purpose in e997c0d by @reduz.

**Comment by hetdegon** [comment]
Ah I see, that makes sense. I'll close this then.
