### ISSUE TITLE
CollisionObject2D nodes inside CanvasLayer with FollowViewport enabled are not affected by movement

### ISSUE THREAD

**Issue by adamz5k** [godotengine/godot#35052]
**Godot version:** 3.2 Beta 6

**OS/device including version:** Windows 64bit

**Issue description:** `CollisionObject2D`s inside a `CanvasLayer` do not take the layer offset/position into account when FollowViewport is enabled in the `CanvasLayer`

**Steps to reproduce:**
- Create a 2D scene with: 
-- `Camera2D` (current with movement)
-- `CanvasLayer` with FollowViewport enabled. (changing scale doesn't seem to matter)
-- `CollisionObject2D` (like `Area2D`) with a `CollisionShape2D` with a connected signal (I used mouse entered/exited - easiest to see the issue with)
-- Turn on visible collision shapes
Note that the `CollisionShape2D` appears to move when the camera moves, but the area on the screen where the collision shape registers collisions remains the same.

**Minimal reproduction project:**
[FollowViewportIssue.zip](https://github.com/godotengine/godot/files/4051269/FollowViewportIssue.zip)

**Comment by cgbeutler** [comment]
This may be related to: #35965 ???  Could be wrong, but they both deal with matrix space transforms maybe not being applied right.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by lawand** [comment]
still happening in 3.4.3.stable

**Comment by Sauermann** [comment]
I verified, that this is a duplicate of #35965
and that it gets fixed in V4 by #59682

**Comment by KoBeWi** [comment]
I tested #https://github.com/godotengine/godot/pull/59682 and it does not seem to fix the issue.

**Comment by Sauermann** [comment]
@KoBeWi This MRP also makes #64652 visible.
 If you apply #59682 together with #66076, you will see, that this MRP works as expected.

**Comment by akien-mga** [comment]
Duplicate of #35965 and #64652.
