### ISSUE TITLE
Breakpoint when load() causes undismissible alert

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#35055]
**Godot version:**
 godot 3.2 beta 5
**OS/device including version:**
ubuntu 18.04
**Issue description:**
If you mark a breakpoint that any moment pass through a load() function loading specifically scenes at "user://" folder, causes a warning which is undimissible.
 
**Steps to reproduce:**
the issue description defines clearly how to reproduce

**Minimal reproduction project:**
https://github.com/nonunknown/crashcreator/tree/alpha

go to scripts/Editor/LevelBuilder and attach breakpoint to load function

**Comment by bojidar-bg** [comment]
>  If you mark a breakpoint that any moment pass through a load() function

I have some trouble understanding how the breakpoint is supposed to "pass through" a load() function. Do you mean that one has to place the breakpoint on the line which includes load function, or does one place it on a previous line and step into/step over the load function?

>  causes a warning which is undimissible.

What is the warning?

> the issue description defines clearly how to reproduce

The steps to reproduce section should be a list of steps which lead to the bug. For example:
1. Clone https://github.com/nonunknown/crashcreator/tree/alpha
2. Open LevelBuilder.gd
3. Add breakpoint on line 48 (`var to_load = load("res://scenes/scn_Gameplay.tscn")`)
4. Run the game
5. Add a path using the path editor
6. Add a start and finish entity using the entity editor
7. Press the test level button
8. See that the breakpoint is hit
9. The bug appears? I could not reproduce, so I cannot say for this point.

> **Minimal reproduction project:**
> https://github.com/nonunknown/crashcreator/tree/alpha

Again, as mentioned on another issue, this is hardly "minimal". A minimal reproduction project should contain as unnecessary cruft as possible. Effective minimal reproduction projects are very helpful for contributors to understand the cause of an issue quickly.
