### ISSUE TITLE
Area2D collision mask set not work in process

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#35069]
I got a nodeA set collision layer to 1, nodeB no mask layer

If I code nodeB like this:
```
extends Area2D

func _ready():
	pass

func _process(delta):
	self.set_collision_mask(1)
	if !get_overlapping_areas().empty():
		print("BoxBcollide")
```
it will not print anything

but if I move the set_collision mask to ready, it collide
extends Area2D

```
func _ready():
        self.set_collision_mask(1)
	pass

func _process(delta):
	if !get_overlapping_areas().empty():
		print("BoxBcollide")
#	set_collision_mask_bit(0, false)
```

I use to breakpoint debug and I see the mask layer actually changed but it wont work

**Comment by firecloud888** [comment]
I see, if I put the code in _physics_process(), it worked. But the collision layer/mask change still need to wait to next time to apply, the changes not work immediately

**Comment by Calinou** [comment]
I'm not sure if this is a bug or documentation issue (if it can't be solved).
