### ISSUE TITLE
vulkan - 4.0 dev - removing giprobe_sdf.glsl from shaders/SCsub brakes compilation on Windows

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#35066]
**Godot version:**
vulkan branch https://github.com/godotengine/godot/commit/a36bb5a475b7dcd22358da8cc18e7d57b80e2d9a from 20200112

**OS/device including version:**
Windows 10 64 bits
VS 2017
python 3.8.0
scons 3.1.1
Intel i7 8750H 16G RAM
Nvidia GTX 1060

**Issue description:**
the vulkan branch cannot be compiled due to changes to reenable and add post processing effects like bloom mix, glow, etc because giprobe_sdf.glsl was removed from the list that create its .h file from:
servers\visual\rasterizer_rd\shaders\SCsub
but is still used in the file:
servers\visual\rasterizer_rd\rasterizer_storage_rd.h

**Steps to reproduce:**
download vulkan branch https://github.com/godotengine/godot/commit/a36bb5a475b7dcd22358da8cc18e7d57b80e2d9a 
try to compile with:
scons platform=windows -j 8 tools=yes target=release_debug bits=64

to compile, readd in SCsub the line :
env.RD_GLSL('giprobe_sdf.glsl');

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Will be fixed by https://github.com/godotengine/godot/pull/35061

**Comment by fire** [comment]
The pull request was merged and so this issue is fixed.
