### ISSUE TITLE
GLES2 Background Mode Clear/Custom Color do not work on Samsung Galaxy S III

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#35071]
**Godot version:**
3.2 master (7a15569c6f)

**OS/device including version:**
Samsung Galaxy S III (GT-I9300): http://opengles.gpuinfo.org/displayreport.php?id=3407
GLES2-only.

**Issue description:**
Several of the `Environment` `Background Mode` options do not work properly on this GLES2-only low end phone.

I did a quick review of all modes (with more or less default settings each time):

- Clear Color: **BUG** Should be neon pink, gives black screen.
- Custom Color: **BUG** Should be green, gives black screen.
- Sky > PanoramaSky: OK.
- Sky > ProceduralSky: OK.
- Color + Sky > ProceduralSky: OK.
- Canvas: OK.
- Keep: **BUG** Should be same as Clear Color a priori, gives black screen.

No relevant output in `adb logcat` AFAICT.

Related to #32458 which was fixed by #32613, I haven't tested yet if this is a regression or if it was a scenario that the above didn't cover (in this issue I'm using a `MeshInstance`).
*Edit:* Nevermind, above issue was about "Canvas" mode and this one works fine.

BTW, when it works fine, I can also reproduce #34257.
I don't have any light in the scene apart from the environment's.

**Steps to reproduce:**
- Load MRP in Godot
- Set main scene for one of the available one to test the Background Mode in its name
- Deploy to device

**Minimal reproduction project:**
[Env Bg Mode GLES2.zip](https://github.com/godotengine/godot/files/4052906/Env.Bg.Mode.GLES2.zip)

**Comment by clayjohn** [comment]
I can't reproduce the issue with clear color and custom color. But I was able to reproduce the issue with BG Mode keep.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment]
This might still be reproducible, but it's such an old low-end phone that it's probably not worth spending too much time on it anymore. Godot 4.0 will have a GLES3 renderer and probably won't support this specific phone anymore.

> Keep: BUG Should be same as Clear Color a priori, gives black screen.

Actually I'm not sure this was a bug, "Keep" keeps whatever was in the viewport already, so when starting the app it's probably normal if it's pitch black or white.
