### ISSUE TITLE
Flipped environment background texture when using viewport + render tex or viewport stretch display mode

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#3507]
Here's a simple scene that is setup to show the issue: 
https://dl.dropboxusercontent.com/u/3292249/flipped_texture_env_BG.zip

Run the scene first and you'll see the texture is the correct way up

Now go to project settings > Display and set stretch_mode to 'viewport'

Now run the scene again and you'll see that the texture is flipped vertically

This is probably related to the same issue that caused  #2180

**Comment by akien-mga** [comment]
@sketchyfun Could you have a look that the fix that was just pushed might not invalidate your already merged PR #2180? (e.g. if reduz fixed the root issue and your PR was fixing a consequence of it).

**Comment by sketchyfun** [comment]
@akien-mga I wondered that too, but I just built and checked it and it both environment background texture and billboard sprites display correctly when using viewports, so looks like it's fine

**Comment by akien-mga** [comment]
Great, thanks for checking :)
