### ISSUE TITLE
Wrong ScrollContainer size after toggling scrolls

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#35085]
**Godot version:**
3.2 beta6

**Issue description:**
When you disable and then enable horizontal/vertical scrollbar of ScrollContainer, it can't be shrunk under the content minimal size until you switch out of the scene tab and back. However if you disable both scrolls and enable again, you will be able to shrink it, but it triggers the "auto-magical" shrinking behavior similar to #21803.
![mfZcuTLEgF](https://user-images.githubusercontent.com/2223172/72269733-5b7f1880-3624-11ea-9e70-5a70e5a34c4b.gif)

**Steps to reproduce:**
1. Create a ScrollContainer
2. Add some Control child (possibly a Panel) and set minimal size to bigger than the container
3. Disable any of the scrolls (the container expands) and enable it again
4. Try shrinking the container to original size

EDIT:
This seems similar to #19252

**Comment by malbach** [comment]
confirmed here, build [6e8eb0d ](https://github.com/godotengine/godot/commit/6e8eb0d98dea1f77a8ec199fe04ba5a44e88faee) on Win10
even weirder, when you do it like this :
 - add a scrollcontainer, size 200 x 200
 - add a panel inside, min size 250 x 250
 - uncheck one of the scroll (let's say horizontal)
    the scrollcontainer extends itself to the size of its child, the x size of the scrollcontainer should now be 262 (250 from the child, 12 from the vertical scrollbar)
 - recheck it without modifying anything
 - uncheck the other scroll (vertical now)
    the scrollcontainer extends itself vertically, but shrinks to its orignal size horizontally 😒

**Comment by KoBeWi** [comment]
Looks fixed in 3.2.4 beta2 (i.e. you don't need to reload the scene to shrink the container)
