### ISSUE TITLE
Texture import srgb detection regression

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#35086]
**Godot version:**
3.1.1 Stable (works) **and** 3.2 Beta 6 (broken)

**OS/device including version:**
Manjaro Linux x86_64

**Issue description:**
I have image assets (png) which Gimp's metadata viewer says is in in srgb colorspace.
![image](https://user-images.githubusercontent.com/30666851/72270212-cf083200-35f2-11ea-82bf-86159e25fca3.png)
In 3.0.x and 3.1.x it is imported correctly but when reimported in 3.2 Beta 6 (this is also present in all 3.2 builds I've tried including 3.1 Alpha 1) the image is washed out. Once the Srgb import setting is changed from Detect to Enable and the texture is reimported it is displayed correctly.

3.1.1 Stable
![image](https://user-images.githubusercontent.com/30666851/72269815-37a2df00-35f2-11ea-8063-522c40b4512f.png)

3.2 Beta 6 and the texture reimported with same settings
![image](https://user-images.githubusercontent.com/30666851/72269959-6caf3180-35f2-11ea-879b-956601cc3b2e.png)

Once Srgb is set to Enable and the texture reimported it displays correctly in 3.2 Beta 6
![image](https://user-images.githubusercontent.com/30666851/72270083-9a947600-35f2-11ea-8aa6-94a19f0c8c3a.png)

**Steps to reproduce:**
See above explanation and reproduction project below

**Minimal reproduction project:**
[TextureSrgb.zip](https://github.com/godotengine/godot/files/4054432/TextureSrgb.zip)

**Comment by Calinou** [comment]
Does Godot even make use of the image metadata? I thought it was only using sRGB if the texture is *detected* to be used in 3D. 2D rendering in Godot doesn't make use of sRGB.

**Comment by clayjohn** [comment]
@Calinou that's what I thought as well, but it's worth checking into. It may check for sRGB metadata to ensure that the conversion isn't applied twice.

**Comment by KoBeWi** [comment]
Tried in 3.2.4 beta2, this is how the texture looks with sRGB detect or disabled
![image](https://user-images.githubusercontent.com/2223172/100013012-75f15900-2dd4-11eb-8f7e-be982042f2a5.png)
And this is enabled
![image](https://user-images.githubusercontent.com/2223172/100013034-7e499400-2dd4-11eb-8ae2-8f5b3216d2a5.png)

Not sure if it's better or worse...

**Comment by akien-mga** [comment]
This was fixed by #40242 in 3.2.3-stable.
