### ISSUE TITLE
Popup - Exclusive bool overrides Mouse filter

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#35098]
**Godot version:**
godot 3.2 beta 5
**OS/device including version:**
ubuntu 18.04
**Issue description:**
If the user wants a popup window that can be draggable and stay always in front of other Control nodes and still can interact with them but still showing the popup (like an output dialog) actually its not possible 
**Steps to reproduce:**
Create a window dialog that shows when click a button, set mouse filter to pass or ignore  and set exclusive to true , try to interact with other controls when the popup is shown, you see that you cant
**Minimal reproduction project:**
https://github.com/nonunknown/crashcreator/tree/alpha
Load scene -> scn_Level_editor, and press the last button on top menu (console icon)

**Comment by Calinou** [comment]
> Minimal reproduction project:
> noone

Please provide a minimal reproduction project, it'll make it much easier to diagnose and fix the issue.

**Comment by nonunknown** [comment]
> > **Minimal reproduction project:**
> > noone
> 
> Please upload a minimal reproduction project, it'll make it much easier to diagnose and fix the issue.

Done

**Comment by KoBeWi** [comment]
No longer valid in 4.0 due to popup rework.
