### ISSUE TITLE
EMScription build error on Stable 1.1

### ISSUE THREAD

**Issue by godofgrunts** [godotengine/godot#3510]
Log dump: http://dumptext.com/e7KqPSTN

uname -a
Linux arch-laptop 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux

pacman -Q scons
scons 2.4.1-1

pacman -Q emscripten
emscripten 1.35.22-1

whereis emscripten
emscripten: /usr/lib/emscripten /usr/lib/emscripten/emscripten.py

pacman -Q llvm-libs
llvm-libs 3.7.1-1

Code used to produce error:

export EMSCRIPTEN_ROOT=/usr/lib/emscripten    
scons -j 4 platform=javascript tools=no target=release

**Comment by akien-mga** [comment]
Thanks for the report. The HTML5 templates were kind of broken in 1.1, could you try the current git master branch to see if it works better for you?

**Comment by godofgrunts** [comment]
Problem is that I'm writing a PKGBUILD for the AUR for the stable branch (and I'll be doing one for the -git branch afterward). See https://github.com/godofgrunts/arch-PKGBUILDs/blob/master/godot-export

**Comment by reduz** [comment]
stable branch does not really work with HTML5, but we'll release a new
stable in some weeks

**Comment by godofgrunts** [comment]
Okay, you can close as wontfix if you'd like, I'll comment out the build until the next stable.

**Comment by akien-mga** [comment]
Thanks for working on AUR packages, that's great! As far as your stable package is concerned, you could probably go with the 2.0-beta tag directly, it's IMO as stable as 1.1 and with many fixed bugs.

/me should finish his Mageia package and push it live :)

**Comment by godofgrunts** [comment]
I'm only referring to it as "stable" because there isn't a 2.0 stable yet. :+1:

**Comment by akien-mga** [comment]
Yeah I know that :) But as a fellow packager I'd still advise you to package the beta as godotengine-stable, it will save you some headache. 1.1 was not so packaging friendly IMO (especially since it did not support system wide templates).
