### ISSUE TITLE
mouse events incorrect on BoxContainer with ColorRect

### ISSUE THREAD

**Issue by AndHalfAFish** [godotengine/godot#35112]
**Godot version:**
3.2beta4

**OS/device including version:**
Windows 10

**Issue description:**
ScrollContainer > VBoxContainer > several HBoxContainers with (ColorRect, Label)
eg/ scroll list with saved games
Issue : mouse events set on HBoxContainer (eg/ gui_input, mouse default cursor) only registers when over Label ; ColorRect is ignored.
Mouse event should register over entire HBox area.
![in_editor](https://user-images.githubusercontent.com/59080934/72333194-b1eb6600-36bb-11ea-8730-84aaff8e5fe9.png)
![in_game](https://user-images.githubusercontent.com/59080934/72333196-b283fc80-36bb-11ea-830e-c4e3da181caa.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
That is an expected behavior. The ColorRect mouse_filter property is by default set to stop.
Change that to pass and it should work.

**Comment by clayjohn** [comment]
@AndHalfAFish Did you try groud's suggestion?

**Comment by AndHalfAFish** [comment]
Sorry, I didn't realize there was a reply to my messsage ...
Yes, just tried it and it works perfectly. Thanks !

In retrospect, 2 things tripped me up : 1) child nodes are actually rendered on top of parents , 2) 'stop' means 'ignore' + 'stop'

**Comment by groud** [comment]
Ok closing as solved then. :)
