### ISSUE TITLE
Undo/Redo per scene

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#3511]
Undo and redo would be much more useful if they worked per scene rather than globally. Currently, switching scenes is itself an undo action, which is rarely helpful, especially when working on multiple scenes at once.

**Comment by reduz** [comment]
I know this, but given scenes share resources and you can also edit global
settings with undo/redo, there is simply no way to make undo/redo work per
scene

**Comment by reduz** [comment]
well, closnig as there really isn't a way to fix this :(

**Comment by nunodonato** [comment]
I don't know how viable these could be but, two possible solutions

- have one undo/redo system per scene
- have some sort of scene ID per action in undo/redo history, and filter based on current scene

I think both involve discarding the undo/redo of global settings. Minor problem or not a problem at all, I don't think anyone expects undo to switch a setting in a hidden dialog screen. In fact, seems to be very counter-UX (as is undo/redoing across scenes)

**Comment by reduz** [comment]
As mentioned before, problem is not just global settings but shared
resources. I honestly don't think there is a different way of doing this.
Anything I can think of is extremely hacky.
