### ISSUE TITLE
"Marshalls" singleton has type Reference in @GlobalScope page

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#35127]
**Godot version:**
v3.2.beta6.official

**Issue description:**
![200114-1](https://user-images.githubusercontent.com/47700418/72363322-b6d50780-3705-11ea-834d-6d639d99f172.png)

I tried changing this line, but nothing changed, which is a bit strange.

https://github.com/godotengine/godot/blob/1bafd2d2c8824570310e63686cfad42a879452a6/doc/classes/%40GlobalScope.xml#L48

Perhaps related: #35090

**Comment by akien-mga** [comment]
Fair warning for anyone looking into this: this is not a junior job, fixing it requires changes some of the core bindings of the engine and is likely best left to @reduz / @vnen. Feel free to investigate and propose solutions nevertheless though :)
