### ISSUE TITLE
External module issues with const char*

### ISSUE THREAD

**Issue by guzzard** [godotengine/godot#3512]
I'm trying to get an external module working but have issues with functions using const char*. In the module i need to send and receive text to an external DLL library which source code I do not have access to. When compiling the module together with Godot I run into some issues.

I have made a tiny example module below to demonstrate the issues. See comments in the code.

```c++
/* chartest.h */
#ifndef CHARTEST_H
#define CHARTEST_H

#include "reference.h"

class Chartest : public Reference {
	OBJ_TYPE(Chartest,Reference);

protected:
	static void _bind_methods();
public:
	const char* getString(); // compiles ok, but Godot crashes on startup
	
	int putString(const char* str); // causes compilation error:
	// e:\godot-2.0-beta\core\method_bind.h(61): error C2440: 'return' : cannot convert from 'const Variant' to 'const char *'
	// No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
	
	Chartest();
};

#endif
```
```c++
/* chartest.cpp */

#include "chartest.h"

Chartest::Chartest() {
}

void Chartest::_bind_methods() {
	ObjectTypeDB::bind_method("getString",&Chartest::getString);
	ObjectTypeDB::bind_method("putString",&Chartest::putString);

}

const char* Chartest::getString(){
	return "a string";
}

int Chartest::putString(const char* str){
		return 0;
}
```

I have tried to use the Godot 'String' but when doing so the external DLL only receive the first letter in the text string I try to send.

What is the proper way to handle this? Implement functions in the Variant class to be able to handle const char* or is there another/intended/better way to do what I'm trying to do here?

**Comment by reduz** [comment]
use String class, not const char *. Godot needs to be able to convert to
and from variant for arguments

String getString(); int putString(String str);

**Comment by reduz** [comment]
you can convert a const char * to String on assignment, and to convert to
const char *, you use:

String("hello").utf8.get_data()

**Comment by guzzard** [comment]
Got it! Thanks for the quick help!
