### ISSUE TITLE
Some bugs  I have found with the godot gui

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#35136]
**Godot version:**
v3.1.2
**OS/device including version:**
Windows 10 Pro education 64 bit 

**Issue(s) description:**
- Selecting the SubBtn and AddBtn nodes and pressing left makes the root node steal the focus when it is not a focus neighbor.
- When I press left or right when SubBtn and AddBtn node is focused it doesn't simulate a press with SubBtn and AddBtn event though I grab the focus and set pressed to true.
- Clicking on the String node with the mouse doesn't grab the focus and redirect it to the SubBtn node even though I use set_focus_mode()
- **(NEW)** selection from alternative version does opposite of expected.
setting focus neighbour in Menu1 scene doesn't allow one below it to be selected
unsetting focus neighbour allows the one below it to be selected

**Steps to reproduce first issue:**
- download the project if you don't have it
- debug the GUIOption scene 
- press enter
- press left
- notice the root node steals the focus

**Steps to reproduce second issue:**
- download the project if you don't have it
- debug the GUIOption scene 
- press enter
- press right
- notice the AddBtn isn't being pressed pressing enter after this works though

**Steps to reproduce third issue:**
- download the project if you don't have it
- debug the GUIOption scene 
- click on charg mk 1 text
- notice the root node is selected and not the label I marked as focusable in the script

**Steps to reproduce fourth issue:**
- **Re**download the project if you have the old version
- debug the Menu1 scene 
- press down
- notice the left arrow below it is selected
- edit Menu1 scene and set Weapon1 top and bottom focus neighbours to the Weapon2 node
- debug the Menu1 again
- press down 
- notice that the focus didn't change and the exact opposite of what should happen happened

**Minimal reproduction project:**
[AstroWars.zip](https://github.com/godotengine/godot/files/4062392/AstroWars.zip)

**UPDATED TO INCLUDE NEW ISSUE**

**Comment by groud** [comment]
Thanks for the report. Could you please open a separate issue for each of the issues, so that they can be reviewed one by one ?

**Comment by Shadowblitz16** [comment]
sure just a sec
