### ISSUE TITLE
Incorrect runresolution when windows setting scale not at 100%

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#35135]
**Godot version:**
3.2beta6
**OS/device including version:**
Windows 10
**Issue description:**
When you change the scale parameter (just on to of screen resolution) in windows settings, the launchable runs in full screen at different resolution than the acual screen resolution.

A high monitor resolution causes one to up the scale to retain size of OS features, however the resolution of the launchable seems to go down I tested on a 3840x2160 with scale parameter of 200% which result in a reported resolution of 1920x1080, with scaling of 300% a resolution of 1280x720
with resolution of 600x800 and scale of 125% screen resolution is 819x614

with 100% it shows correct resolution, but the editor and OS text is TINY.
**Steps to reproduce:**
1. Open project
2. change OS scale to something other than 100%
3. Run project
4. watch the printout
5. Note that the window size and screen size are equal, but different from the resolution defined by the OS.
  @##
**Minimal reproduction project:**
[errorous project.zip](https://github.com/godotengine/godot/files/4061698/errorous.project.zip)

**Comment by clayjohn** [comment]
Is this with a HiDPI monitor by any chance?

And is the issue just within the editor, or does it affect the running game?

**Comment by albinaask** [comment]
It does effect the running game when running it from the editor, how about any other circumstances I do not know. I am currently using a 3840x2160 28 inch monitor, but I tested running i on a 1366x768 at 14 inches as well, as I said I even dropped the resolution on the big monitor

**Comment by Calinou** [comment]
You need to enable **Allow Hidpi** in the Project Settings for the process to be marked as DPI-aware on Windows. This is not done by default as your game must support [multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) for this to work as expected.

**Comment by albinaask** [comment]
Yap, realised. :)
