### ISSUE TITLE
Godot Project Manager segfaults when moving it to another display

### ISSUE THREAD

**Issue by j-mckim** [godotengine/godot#35137]
**Godot version:**
3.1.2
**OS/device including version:**
Mac OS X 10.15.2 (19C57)
**Issue description:**
The Godot application fails with a segfault after I try to move (drag) its GUI window from one display to another.

This fault doesn't always happen. Roughly, 10% of the time there is no fault; it works.
When it fails, I first see the spinning pinwheel of death for 30 seconds or so before being informed of the fault by MacOS.

Based on a bit of testing, the fault only seems to happen when I am moving the window from an attached display to the laptop's main screen. Never in the other direction.

Some additional observations, FWIW:

This may have no bearing, but when moved, the Godot window doesn't track retina settings; when I move it to the attached non-retina display the content (fonts, icons) are enlarged. The few times I successfully moved the other direction (to the main display), everything (fonts, icons) are minuscule.

When I force the app to run on the main screen, the main window (project manager) appears with a normal size, but the content is extremely magnified, such that most of it is out of bounds. The 'Exit' button appears at the extreme right bottom, but is not responsive. When I move the mouse to where the exit button should be (bottom middle) and click on the empty space there, the app exits.

<img width="1136" alt="Screen Shot 2020-01-14 at 5 10 28 PM" src="https://user-images.githubusercontent.com/15632330/72388097-09f18f00-36f3-11ea-8de9-425c80737589.png">

If I then move the window from the main display to the attached display, it appears thus:

![Screen Shot 2020-01-14 at 5 28 00 PM](https://user-images.githubusercontent.com/15632330/72388178-3c9b8780-36f3-11ea-985b-76cac42f6da0.png)

When I try to move it back again to the main display, it usually crashes. When it works, I see normally-sized contents.

I've attached the problem report MacOS generated and offered to send to Apple; maybe some of its content can help identify the cause.
[report.txt](https://github.com/godotengine/godot/files/4061864/report.txt)

**Steps to reproduce:**

Start the app such that it opens in the attached display. Move the window to the main display. As noted above, this occasionally works for me but usually fails.

**Minimal reproduction project:**
N/A - no project is yet open.

**Comment by bruvzg** [comment]
Should be fixed in 3.2 (#34202).

**Comment by akien-mga** [comment]
Let's keep this one as a reminder to cherry-pick #34202 (and last time I tried, more previous changes to macOS display handling) for the `3.1` branch and 3.1.3.

**Comment by akien-mga** [comment]
> Let's keep this one as a reminder to cherry-pick #34202 (and last time I tried, more previous changes to macOS display handling) for the `3.1` branch and 3.1.3.

I have no clear plans to make a 3.1.3 right now, as my focus is on the 3.2 branch. PRs welcome to cherry-pick these changes if anyone needs them in `3.1`.
