### ISSUE TITLE
'Recent' panel in 'Create new node' popup is never cleared.

### ISSUE THREAD

**Issue by AndHalfAFish** [godotengine/godot#35146]
**Godot version:**
3.2beta4

**OS/device including version:**
Windows 10

**Issue description:**
'Recent' panel in 'Create new node' popup is never cleared, which makes it useless.

**Steps to reproduce:**
In the scene tab > add new node > 'create new node' popup > add a node
Repeat a couple of times.
When Godot is restarted, all those nodes are still present in 'recent'. They should have been cleared.
![recent_panel](https://user-images.githubusercontent.com/59080934/72423082-eaef0d80-3783-11ea-84fa-22bf268f740c.png)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Why does it make it useless?

The point is that it lists what nodes you last use, regardless of the session.
All software does that with their "Recent files" features.

**Comment by AndHalfAFish** [comment]
If it's never cleared, it just becomes identical to the main list.
The behavior I expect is : no clearing during 1 session , clearing after I restart Godot. I think this is what the behaviour used to be in previous versions of Godot.

**Comment by akien-mga** [comment]
It should be ordered by reverse chronological order (last used nodes come first), so it's not the same as the main list.

But it should likely be limited to ~10-15 entries or so, removing the older ones as new ones come in.

**Comment by AndHalfAFish** [comment]
Yes. That would be an option too.
That, or just a simple clear.

**Comment by Calinou** [comment]
Limiting the Recent menu to about 10 entries is probably a better idea indeed.

**Comment by tektrip-biggles** [comment]
Another issue with this never being cleared (whether manually or automatically) is that if you move / rename files with custom classes, you can end up with broken links in the "Recent" panel, along with a couple of error messages every time you open the "create new node" dialog:

```
Attempt to open script 'res://MyOldScriptName.gd' resulted in error 'File not found'.
  editor/create_dialog.cpp:266 - Condition "inherits.is_empty()" is true.
```
