### ISSUE TITLE
3dSprite invisible in editor/game if not rotated & billboard y still broken

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3514]
3DSprites behave strangely . They seem to be invisible by default until you rotate it 90 degrees then they become visible. editor only!

Billboard fix y property still broken both in code and in the editor interface.  

Also I get strange octant face null issues if  try to translate a 3DSprite (with billboard property on?).  

When 2 or more 3DSprites with same dimensions and billboard on are at the same position (ye on top of one another) the draw Z order is based on the order in the node list. However! When the game begins the top most sprite is drawn then only after 2 second delay all other sprites are drawn as well. It seems like the visual engine rushes to draw the scene but forgets to draw ALL the billboard sprites save the top most one right away. it may be same without billboard. 

See #1366 & #2061

**Comment by reduz** [comment]
not much more work will be done on 3D engine, as it will be rewritten this year

**Comment by trollworkout** [comment]
i understand for now i implemented my own billboard y is no biggie just making devs aware this is happening

**Comment by trollworkout** [comment]
also this is 2 issues in 1 probably needs to be split in 2 issues

**Comment by reduz** [comment]
billboard was rewritten so this is obsolete
