### ISSUE TITLE
Shader language "Only integer constants are allowed as index at the moment"

### ISSUE THREAD

**Issue by xix-xeaon** [godotengine/godot#35149]
**Issue description:**
Couldn't find an issue about this, seems like part of the implementation left undone and forgotten.

I was trying to implement an alpha dissolve (discard some pixels instead of blending) with the thresholds in a _mat4_ (for a simple 4x4 dissolve) and pixel coordinates mod 4, but I got the error "Only integer constants are allowed as index at the moment". Same for vectors.

I tried using the new local arrays instead but it doesn't work in GLES2 (I'll make a separate issue). _Edit: It seems the issue in GLES2 is not related to the arrays._ Regardless, it's still a bug.

**Steps to reproduce:**
```
int n = 0;
float r = vec2(0.0)[n];
```

**Comment by clayjohn** [comment]
This isn't a bug. ``vec2(0.0)[n];`` is not valid glsl, it should cause an error. Vec2's are not arrays they cannot be accessed with array syntax. The engine rightly should give you an error when you make a syntax mistake like that. 

In this case, you have made two syntax mistakes. The first is described above, the second was properly reported by the engine. You can only use constant indexes to look up elements of an array. When you try to use a variable, as you did, the engine should and does provide an error message.

**Comment by xix-xeaon** [comment]
Not sure what's up @clayjohn 
- The error messages seems pretty clear that it should work, just not implemented yet, if that's not the case then the message needs to be changed.
- I've found plenty of examples of using a mat4 exactly this way for stipple/screen-door/dithered  transparency or whatever they want to call it for other game engines.
- @Chaosus has already implemented the fix? Only @akien-mga says it may not work on GLES1, although I wouldn't know why that version would matter.

**Comment by clayjohn** [comment]
> The error messages seems pretty clear that it should work, just not implemented yet, if that's not the case then the message needs to be changed.

The error message relates to the use of ``n`` inside the array. The message should be changed as GLES2 will never support variable indexing of arrays.

> I've found plenty of examples of using a mat4 exactly this way for stipple/screen-door/dithered transparency or whatever they want to call it for other game engines.

A ``vec2`` and a ``mat4`` are two different data types. In GLSL 120 you can index a ``mat4`` with the [] syntax, but you cannot index a ``vec2`` with []. In GLSL 120, you can only access ``vec2``s with ``rg`` or ``xy``.

That being said, the Godot Shader Language still hasn't implemented array indexing for ``mat4``s either as far as I know.

> @Chaosus has already implemented the fix? Only @akien-mga says it may not work on GLES1, although I wouldn't know why that version would matter.

The "fix" is only for the first part, it allows you to access arrays using certain non-constant values. And even then it is dubious whether it will work in GLSL 120, we need to investigate more.

**Comment by xix-xeaon** [comment]
I just assumed vec and mat would work the same for indexing and vec was shorter as a reproduction example. But as I wrote in the issue, I was trying to do it with a mat4, which you're saying should actually work?

If I understand it correctly though, it should only work (or rather, is only required to work) for constants and like for loop counters? That doesn't really make any sense to me. Constants are different things sure, but a for loop counter is just a local variable really. I would think you'd have to go out of your way to prevent it from working with non-loop local variables =P Why would the spec leave them out?

However, the fix does seem to work on at least some devices. If this technique has been used for a long time then maybe it works everywhere? It kind of reminds me of working on http servers many years ago; the spec was one thing, and the real world was an other. You could ignore a whole bunch of spec-behavior because Apache didn't support it anyway. But then there were these other things outside of spec you had to discover and support anyway because it was de facto spec. Such a mess =P

**Comment by clayjohn** [comment]
> But as I wrote in the issue, I was trying to do it with a mat4, which you're saying should actually work?

The spec allows it for ``mat4``s but we haven't implemented it in the Godot Shading Language yet.

> Why would the spec leave them out?

I can't answer that. The spec is a big mystery to me. Your last paragraph makes me think you understand my pain. :P

When running GLES2 on devices that support GLES3 a lot of venders allow you to use GLES3 features even though they are technically not supported. This makes cross platform (especially low-end) support extremely difficult for us.
