### ISSUE TITLE
External module, function with more than 5 parameters

### ISSUE THREAD

**Issue by guzzard** [godotengine/godot#3515]
I'm trying to create an external module and I have functions that take more than 5 parameters and get compilation errors. If i reduce the number of parameters to max 5 the code compiles ok.

Example:
```c++
int send_event(int slot, int num, int pos, int vel, int mod, int ctl, int val); // compilation error
int send_event(int slot, int num, int pos, int vel, int mod); // compilation OK!
```

The error seem to indicate that there is no suitable template: "e:\godot-2.0-beta\core\object_type_db.h(337): error C2784: 'MethodBind *create_method_bind(R (__thiscall T::* )(P1,P2,P3,P4,P5) const)' : could not deduce template argument for 'R (__thiscall T::* )(P1,P2,P3,P4,P5) const' from 'int (__thiscall myModule::* )(int,int,int,int,int,int,int)'"

Is the number of parameters limited to 5?

Would it be possible to extend the limit to a higher number, or remove the limit?

**Comment by eska014** [comment]
Try with `#include "method_bind_ext.inc"`

**Comment by reduz** [comment]
not a bug, and yes, including method_bind_ext solves it
