### ISSUE TITLE
Triplanar projection seems to have issues when faces face more than one valid projection

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot#35158]
Godot 3.2 beta

macOS High Sierra 10.13.6

When using the triplanar in a spatial shader it projects unwanted lines

Note in screenshot, cyan marks an unwanted consequence, magenta seems to be the explanation for this line (the top projection)

Create a triplanar shader, project it to a cube, more the cube around rotate a bit etc
![Screen Shot 2020-01-13 at 16 33 21](https://user-images.githubusercontent.com/5873361/72449491-acbc1300-37b0-11ea-8030-09ce6cefcc52.png)

This may be unintended consequences of how this is coded. In Blender when using UV projectors you don't get this issue, in the video games i hoped to emulate (the texture mapping in quake)... you didn't have this issue

I hope this issue is not seen as unavoidable, surely only one of the 3 valid axis should project a texture to a surface (the closest one?)

**Comment by lawnjelly** [comment]
This is what triplanar projection does, by definition, it blends the 3 textures from the 3 axes. This is so you can texture map a sphere for example, without seams. It is easy to use but quite expensive in terms of texture lookups. Quake texture mapping doesn't use this, if I remember correctly.

If you want to apply some kind of UV projection you probably need to do it yourself (I haven't found any built in auto mapping in Godot).

You can do the approach you are after pretty easily when building geometry, just e.g. look at the x,y,z values of triangle normals to find the principle axis (it will be the largest of the 3 values), then use e.g. x,y to map to u,v with scaling etc as you wish. However it probably won't look all that great except in the case of polys almost matching the axes.

What you can also do is use the length of the edges to determine the mapping, which may be more what you are after.

**Comment by Calinou** [comment]
You can play with the intensity of the triplanar blend smoothing by tweaking the Triplanar Sharp property in the material.
