### ISSUE TITLE
OGG files don't have an icon

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#35163]
**Godot version:**
3.2 beta6

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/72468380-50bbb380-37dd-11ea-855c-ee5d75f910ac.png)
The .wav icon could be re-used or slightly altered for OGGs.

**Comment by aaronfranke** [comment]
The logo for OGG Vorbis is a fish. Perhaps the icon should have a tiny fish in the bottom-right corner?

![](https://botw-pd.s3.amazonaws.com/styles/logo-thumbnail/s3/0018/5679/brand.gif?itok=9l69xPQq)

**Comment by Calinou** [comment]
@aaronfranke Maybe we can re-use the WAV icon but use a blue-yellow gradient instead of red-yellow-green?

**Comment by KoBeWi** [comment]
How about something like this?
![image](https://user-images.githubusercontent.com/2223172/72470659-68953680-37e1-11ea-9dd0-3a60a9d8b92c.png)
With the left one for .wav (also +colors)

**Comment by akien-mga** [comment]
IMO it would be OK to simply use the same icon.

I've been using OGG Vorbis for 15+ years and I definitely don't associate it with a fish, I had never seen/noticed this logo :)
