### ISSUE TITLE
Setting Button pressed to true doesn't work without toggle mode

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#35172]
**Godot version:**
v3.1.2

**OS/device including version:**
Windows 10 Pro education 64 bit

**Issue description:**
When I press left or right when SubBtn and AddBtn node is focused it doesn't simulate a press with SubBtn and AddBtn event though I grab the focus and set pressed to true.

**Steps to reproduce:**
download the project if you don't have it
debug the GUIOption scene
press enter
press right
notice the AddBtn isn't being pressed pressing enter after this works though

**Minimal reproduction project:**
[AstroWars.zip](https://github.com/godotengine/godot/files/4068149/AstroWars.zip)

**Comment by Poobslag** [comment]
Thankfully the workaround is simple: temporarily set `toggle_mode` to true while the player holds the button down.

```
	if event.is_action_pressed("ui_cancel"):
		$Window/UiArea/SettingsArea/Ok.toggle_mode = true
		$Window/UiArea/SettingsArea/Ok.pressed = true
	if event.is_action_released("ui_cancel"):
		$Window/UiArea/SettingsArea/Ok.toggle_mode = false
		$Window/UiArea/SettingsArea/Ok.emit_signal("pressed")
```

I use this code where I want a button to have two shortcut keys; a player can close a pause menu with 'ui_cancel' (the B button) or with 'ui_menu' (the start button)
