### ISSUE TITLE
Error about modified time when loading scenes from ".pck" files

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#35179]
**Godot version:**
e889100

**Issue description:**
When loading a scene originated from a ".pck" file, if said scene uses assets, the engine will complain about not being able to get the modified time of the assets:
```
E 0:00:00.518   _get_modified_time: Failed to get modified time for: res://icon.png.
  <C++ Error>   Method/Function Failed, returning: 0
  <C++ Source>  drivers/unix/file_access_unix.cpp:321 @ _get_modified_time()
  <Stack Trace> main.gd:8 @ _ready()
```

**Minimal reproduction project:**
[modified_time_pck.zip](https://github.com/godotengine/godot/files/4068933/modified_time_pck.zip)

**Comment by graydwarf** [comment]
Is there a workaround for this issue? I'm in 3.2.3 and it seems to be a blocking issue for loading resource packs. Some pck files seem to work while others don't.

**Comment by Calinou** [comment]
@graydwarf Could you upload one working PCK and one broken PCK here? You can put each of them in a ZIP archive and upload them here.

**Comment by graydwarf** [comment]
The only working pck uses the default icon.png so I'm not sure that it's an
apples to apples comparison. I have yet to create a pck file with other
images that works.

**Comment by graydwarf** [comment]
https://github.com/graydwarf/gc-animations <- No errors project
https://github.com/graydwarf/gc-dialogs <- Errors project

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 4.x builds?

**Comment by YeldhamDev** [comment]
@akien-mga Doesn't seem so, I will close this then.
