### ISSUE TITLE
Controls steal focus

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#35171]
**Godot version:**
v3.1.2

**OS/device including version:**
Windows 10 Pro education 64 bit

**Issue description:**
Selecting the SubBtn and AddBtn nodes and pressing left makes the root node steal the focus when it is not a focus neighbor.

**Steps to reproduce:**
download the project if you don't have it
debug the GUIOption scene
press enter
press left
notice the root node steals the focus

**Minimal reproduction project:**
[AstroWars.zip](https://github.com/godotengine/godot/files/4068131/AstroWars.zip)

**Comment by MightyPrinny** [comment]
I haven't checked your project, but if you don't set the neighbors Godot will guess them, a little hack you can use is to set them to NodePath(".") (the same node)

**Comment by Shadowblitz16** [comment]
The can be closed I actually just recently found this out and have posted a fix and part of [this](https://github.com/godotengine/godot-proposals/issues/385) suggestion. 

looks for the auto focus flag.
