### ISSUE TITLE
HTML5 GLES3 Shadows Not Rendering

### ISSUE THREAD

**Issue by Quadtree** [godotengine/godot#35188]
**Godot version:** 3.1.1 or 3.2 Beta 6

**OS/device including version:** Windows 10, tested with both a RTX 2070 Super and a GTX 1050, on both Firefox and Chrome.

**Issue description:** Shadows cast by omni and spot lights don't render at all when a project is exported in HTML5 mode and the GLES3 driver is used. I'm fairly new to Godot so it's possible it's just something I'm doing wrong. Example screenshots:

HTML5, Chrome, GLES3:
![image](https://user-images.githubusercontent.com/7550567/72505632-3261b200-37f5-11ea-8cb3-d61d5f522dc3.png)

HTML5, Chrome, GLES2:
![image](https://user-images.githubusercontent.com/7550567/72505771-7359c680-37f5-11ea-9b91-d57239eb40fa.png)

Desktop, GLES3:
![image](https://user-images.githubusercontent.com/7550567/72505668-46a5af00-37f5-11ea-8ecd-721fe98a5b93.png)

**Steps to reproduce:** Open project linked below. Click launch in HTML5 mode button. View resulting project.

**Minimal reproduction project:** https://github.com/Quadtree/GodotShadowTest1

**Comment by Quadtree** [comment]
I feel a little silly for not noticing this earlier, but if the scene has any animation, the issue doesn't happen. I think this is because Godot only recomputes shadows if something changes, and for whatever reason only the first calculation fails in HTML5/GLES3.

Example: https://github.com/Quadtree/GodotShadowTest1/tree/animation_workaround

Since most games have animation, this now looks like an edge case, even if I think it's still a bug. Unless it's pretty easy to fix, I'd recommend closing this, but I'll leave that call up to someone with more knowledge of this.

**Comment by Calinou** [comment]
We no longer support using the GLES3 renderer in HTML5 (as WebGL 2 support is poor across the board), so it makes sense to close this indeed.

Thanks for reporting it anyway :slightly_smiling_face:
