### ISSUE TITLE
Inspector's scrollbar has wrong position on HiDPI display

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#35181]
**Godot version:** v3.2.beta.custom_build.f2d45676c

**OS/device including version:** macOS Catalina 10.15.2 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

The Inspector's vertical scrollbar is half way into the view border on HiDPI display:

<img width="193" alt="snapshot" src="https://user-images.githubusercontent.com/372476/72487939-7fbc3e80-384a-11ea-9fef-f891494d3cbb.png">

Also, if I change the editor scale to 300%, the scrollbar ~~is completely gone~~ goes further right.

The scrollbar works fine in beta 6.

**Steps to reproduce:**
1. Open Godot on a HiDPI monitor, or change the editor scale to 200%
2. Open any scene, and select any node 
3. See the vertical scrollbar in the Inspector

**Comment by YeldhamDev** [comment]
Does this still happen without #35133?

**Comment by timothyqiu** [comment]
It's good before #35133 is merged.

Tested `42d3d0619` (last commit before merge) and `7971ec74f` (the merge commit).
