### ISSUE TITLE
-Wnon-virtual-dtor warning with MinGW/GCC in AudioDriverWasapi

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#35194]
**Godot version:**
3.2 master (a2c90fe2f)

**OS/device including version:**
Linux, cross-compiling for Windows with MinGW 5.0.4 and GCC 8.3.0

**Issue description:**
With the above compiler, this warning is raised in `scons p=windows tools=yes target=debug`:
```
drivers/wasapi/audio_driver_wasapi.cpp:71:7: warning: base class 'struct IMMNotificationClient' has accessible non-virtual destructor [-Wnon-virtual-dtor]
 class CMMNotificationClient : public IMMNotificationClient {
       ^~~~~~~~~~~~~~~~~~~~~
```

Our implementation seems directly taken from https://docs.microsoft.com/en-us/windows/win32/coreaudio/device-events, and this warning would normally be fixed by changing `IMMNotificationClient`'s destructor to `virtual`, but it's a Windows SDK struct and we have no control over it.

**Steps to reproduce:**
See above.

**Comment by bruvzg** [comment]
This one probably should be suppressed. AFAIK it's not a bug, just COM interface weirdness. COM objects aren't created or destroyed in the normal C++ way.
