### ISSUE TITLE
Get touch position (mobile) in MOUSE_BUTTON event

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#3519]
In Anroid device, I get position touch from input event with get_viewport().get_mouse_pos() it return old position 1 step

ex:
First touch on [top, left] return (0, 0)
Second touch on [bottom, right] return low value (position from first touch)
Third touch return high value (position from second touch)

On PC, use mouse it return correct.

There is test project:
https://www.dropbox.com/s/wtcgvx3wgdtv8be/testTouchPos.zip?dl=0

**Comment by reduz** [comment]
don't use MOUSE_BUTTON events for this, use SCREEN_TOUCH and SCREEN_DRAG

**Comment by Mavhod** [comment]
Ok, but maybe screen touch should not enter to MOUSE_BUTTON event?
I use mouse on PC for test, so it confuse on mobile because touch will enter to 2 events.

**Comment by reduz** [comment]
yes, this is intended by design. You get both touch events and mouse events on mobile, use the one you prefer

**Comment by reduz** [comment]
basically 
-if you don't use multitouch, just use mouse events and they will work everywhere
-if you really want to know if you will get touch events, use OS.has_touchscreen_ui_hint()
