### ISSUE TITLE
Custom types can't be favorited

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#35205]
**Godot version:**
40f0649e5

**Issue description:**
Custom types can't be favorited in the node selection.
They also don't appear in the `Recent` section.

**Steps to reproduce:**
1. Install a plugin from the asset library (For example my `Replicator Node` plugin).
2. Open the `Add Node` dialog.
3. Favorite the custom type.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4
This only applies to types added via `add_custom_type()`. `class_name`s work fine.
