### ISSUE TITLE
ERROR: get_breakpoints: Condition ' base.begins_with("local://") 

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#35211]
OS: Debian 10

```
ERROR: get_breakpoints: Condition ' base.begins_with("local://") || base == "" ' is true. Continuing..:
   At: editor/plugins/script_editor_plugin.cpp:1566.
Running: /home/vale/Desktop/Godot_v3.2-beta6_mono_x11_64/Godot_v3.2-beta6_mono_x11.64 --path /home/vale/godot/desert_edge --remote-debug 127.0.0.1:6008 --allow_focus_steal_pid 20370 --position 0,0
Godot Engine v3.2.beta6.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
 
Mono: Logfile is: /home/vale/.local/share/godot/mono/mono_logs/2020_01_16 17.03.32 (27279).txt
debugger-agent: Unable to listen on 27
ERROR: get_breakpoints: Condition ' base.begins_with("local://") || base == "" ' is true. Continuing..:
   At: editor/plugins/script_editor_plugin.cpp:1566.
Running: /home/vale/Desktop/Godot_v3.2-beta6_mono_x11_64/Godot_v3.2-beta6_mono_x11.64 --path /home/vale/godot/desert_edge --remote-debug 127.0.0.1:6008 --allow_focus_steal_pid 20370 --position 0,0
Godot Engine v3.2.beta6.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
 
Mono: Logfile is: /home/vale/.local/share/godot/mono/mono_logs/2020_01_16 17.03.42 (27295).txt
debugger-agent: Unable to listen on 27

```

No idea where this error come from. 
I got nothing in local://

in Output docker:
![image](https://user-images.githubusercontent.com/13235119/72546835-6388c380-3883-11ea-91bd-c23d18d9a07f.png)

Why godot give me error on port 6008? The other open project is on port 6007

**Comment by Calinou** [comment]
Can you reproduce this with a non-Mono-enabled version of Godot?

**Comment by t-mw** [comment]
Repro steps in regular godot:
1. Create a new project
1. `Create Root Node` -> `2D Scene` in outliner
1. `Attach script` to the new node and click `Create`
1. Right-click on node in outliner, and select `Attach script` to replace the previous script
1. Change name of script to `Node2D2` and click `Create`
1. Delete the first script `Node2D.gd` from the filesystem tab
1. Ctrl-S to save the scene
1. Click play, select the scene as the default
