### ISSUE TITLE
ERROR: create: Condition and grab_focus

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3521]
OS: Ubuntu 14 - 64bit
No crash.

When I open a project I get this
```
ERROR: grab_focus: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:1600.
```

And on close that
```
ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
```

Maby it's already fixed my build is ~5 days old. I can't test the recent build right now.

**Comment by bojidar-bg** [comment]
I get only the first one on 987bfb4b5e99bb11ecfd914e80d59b9bde62e26f.

**Comment by Ace-Dragon** [comment]
I can confirm this as well (Windows 10 64bit using a build slightly newer than the official beta release).

**Comment by akien-mga** [comment]
Assigning to 2.0 as even though it's not critical (probably doesn't impact anything), it's the kind of console spam that makes it harder to debug real issues.

**Comment by AlexHolly** [comment]
Tested on [519c866](https://github.com/godotengine/godot/commit/519c8667032225d2c987562a716c7a2629198772) and still both errors.
