### ISSUE TITLE
Changing vsync via code doesn't work

### ISSUE THREAD

**Issue by benbishopnz** [godotengine/godot#35221]
**Godot version:**
v3.2.beta2

**OS/device including version:**
MacOS Mohave 10.14.6

**Issue description:**
Changing vsync setting via code doesn't seem to do anything. I notice the editor requires a restart now when switching the setting, so perhaps the game would need to restart too. Is there a command line run option to override the project setting? I could not find one in the documentation.

**Steps to reproduce:**
Set `OS.vsync_enabled = false/true` in code.

**Comment by Calinou** [comment]
> Is there a command line run option to override the project setting? I could not find one in the documentation.

There's one for the Vsync via Compositor setting, but not for the general Vsync setting. We should probably add one to bypass forced Vsync in gamejam games :slightly_smiling_face:

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1923, as feature proposals are now tracked on the Godot proposals repository.
