### ISSUE TITLE
Cannot change root node type by script

### ISSUE THREAD

**Issue by takaturre** [godotengine/godot#35222]
**Godot version:**
3.0-3.2 (probably older too)

**Issue description:**
There is no way to change the type of the root node of a scene *by script*. It can be done by right clicking the node in the tree list and choosing Change Type however. If trying `replace_by( new_node )` the following error is thrown in 3.2 : `Cannot get path of node as it is not in a scene tree.`. The same error is thrown if you remove the current root node and add another to replace it (or first add new node and then remove old - it happens when the old root gets removed). 

**Steps to reproduce:**
1. Make a new scene.
2. Add the root node of whatever type, and attach a tool script to it.
3. Try to replace the root node with another node, either by: `replace_by( )` or writing a custom script to do the replacing.
+ Click the root node and change type manually - it works. 

**Workarounds:**
- My current workaround is to ask the user to do it, the script will handle other parts of the process of which changing the node type is one (Node2D <-> KinematicBody2D).
- Another one would be to duplicate the whole scene and save it on the disk and then open it in a new tab (or possibly use `reload` on the existing path, if has been saved). But this is even hackier.

<-- Or am I missing a command, is there something else besides `replace_by` to change the node type ?

**Comment by bojidar-bg** [comment]
Here is the code the SceneTreeDock uses to ensure that the node is properly reinstated as the current scene:
https://github.com/godotengine/godot/blob/e7ee9e01a64bb1296431d82f9f1d888a90b6ea1c/editor/scene_tree_dock.cpp#L2130-L2134

**Comment by takaturre** [comment]
Thanks a lot! (Also for the help on other issues!)

There "magical" line I was missing is that `set_edited_scene`. Couldn't find it in the docs, though finally found this: [Adding a root node from a script](https://godotengine.org/qa/4222/adding-a-root-node-from-a-script). Also tried it on the EditorPlugin and EditorInterface but it needs to be the EditorNode (which there's no docs about?).

Btw. Do you have any more info on the `set_editable_instances` ? What does it do (hoping it's related to Editable Children - and solve other hacks for me) and how to use it in tool scripts?

Anyway, here's the current solution (without Editable Instances) for anyone with the same problem:
```
# "Hard-Swap" the root node.
static func swap_root_node(orig_root : Node, new_node : Node, no_wait := false):
	# Prepare.
	var editor := orig_root.get_node("/root/EditorNode")
	# Wait.
	if not no_wait:
		yield(editor.get_tree(), "idle_frame")
	# Add the new node.
	orig_root.get_parent().add_child(new_node)
	# Finish the root node swap. Do not remove the old node after (causes an error). Setting owner makes no difference.
	editor.set_edited_scene(new_node)
