### ISSUE TITLE
OS.window_fullscreen causing input latency

### ISSUE THREAD

**Issue by benbishopnz** [godotengine/godot#35220]
**Godot version:**
v3.2.beta2

**OS/device including version:**
Windows 10

**Issue description:**
I was trying to debug input latency in my game and noticed that there were 3-5 additional frames while vsync was enabled.
After some more testing I found that there was only 1 extra frame if project setting **display/window/size/fullscreen** was set to **false** (or **OS.window_fullscreen = false**)

**Steps to reproduce:**
Run project with fullscreen option off and on to compare input delay.
I recorded the project running with screen capturing software and a key overlay so I could count frames between keypress and when the action was applied.

**Minimal reproduction project:**
[input_latency_test.zip](https://github.com/godotengine/godot/files/4073779/input_latency_test.zip)
Press W to toggle/test input latency

**Comment by Calinou** [comment]
Which graphics card model do you have? Try disabling Vsync in the project settings.

**Comment by benbishopnz** [comment]
A GTX970. I have a label on my hud which shows `Engine.get_frames_per_second()` so it's obvious when it is on/off too.
I tried disabling Vsync and yes the input latency is lower, but it also burns 100% of the CPU time trying to generate as many frames as possible. This is fine on my desktop but seems like a bad idea for low-spec devices and laptops (don't want to set fire to anybody's knees.)
debug/force_fps seems somewhat choppy in my testing, and isn't supposed to be used outside of testing anyway.
frame_delay_msec project setting seems to just tack on the delay to every frame to limit the number of frames drawn, but you can't hit any consistent frame timing that way.

**Comment by lawnjelly** [comment]
Your GPU might be using triple buffering, have a look in the control panel options. With double / triple buffering and vsync the GPU is writing to a different back buffer to the one being displayed. This adds extra frames of latency, but removes tearing and helps prevent dropped frames. There can also potentially be more latency from e.g. the compositor.

In platform/windows there is a PFD_DOUBLEBUFFER flag which is applied when initializing the context. No idea what happens if you don't apply it lol. There doesn't seem to be a triple buffer flag for OpenGL so maybe it is just up to the graphics driver to decide.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

I tried the project and don't see anything wrong. Windows 10.

**Comment by benbishopnz** [comment]
I tested again last night and saw the same results as in the initial issue description.
To add a little more info I found my GPU settings and confirmed that triple buffering is disabled. I can't see any other obvious settings that might have helped here.

Is it correct that Godot does not use [Windows exclusive fullscreen](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.fullscreenpresentationconfiguration.isexclusive?view=winrt-19041)? I've heard that this can help avoid any input latency introduced by the compositing process.

On a related note, is it just me or is turning Vsync off mostly pointless? (Without a good way to limit the framerate)
I suppose there is a scenario where someone might want their game to process thousands of times per second but it seems unlikely most of the time.

**Comment by Calinou** [comment]
> Is it correct that Godot does not use Windows exclusive fullscreen? I've heard that this can help avoid any input latency introduced by the compositing process.

Indeed, Godot doesn't use exclusive fullscreen. That said, Windows 10 is supposed to be smart about this and avoids adding latency when using a borderless window.

**Comment by Calinou** [comment]
@benbishopnz Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

PS: Godot 3.x only uses exclusive fullscreen if the window size is equal to the screen size, and if Borderless is unchecked in the project settings.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
