### ISSUE TITLE
Godot crash on Window switch while game running

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3522]
running:

```
/home/.../projects/games/godot/bin/godot.x11.tools.64 -path /home/.../projects/games/client -rdebug localhost:6007 -p 128x100 res://main.scn
ERROR: set_item_checked: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:591.
********* listening on port 6007
OK! 17
has connection!
has connection!
shit?: Connection reset by peer
ERROR: read: Server disconnected!

   At: drivers/unix/stream_peer_tcp_posix.cpp:276.
pre-removing print handler...
removing print handler...
found
print handler list is (nil)
```

OS Ubuntu 14 - 64bit
1.Start Godot, open project and run the game.
2.The game has the focus, select godot in the background.
3.Game window is now behind the godot window.
4.Go to the left ubuntu bar press the godot process.
5.Select the running game, now godot crashes but the game is still running.

Maybe again some strange nvidia driver issue?

**Comment by reduz** [comment]
can't reproduce, most likely driver issue

**Comment by reduz** [comment]
I will close as not enough information was given to reproduce. Repoen if more info to reproduce is added

**Comment by akien-mga** [comment]
Can't reproduce either (though not using Ubuntu/Unity so I can't really test point 4 as it was done when finding the bug).

**Comment by Algrin6** [comment]
@AlexHolly 
Your problem may be caused by many 3d applications running (including Unity (Ubuntu interface)).
1. You can try to run your game while the script editor is active (not 2d nor 3d).
2. You can try to use Xubuntu or Lubuntu.

**Comment by punto-** [comment]
what's the window manager? we saw this on a "mint linux" yesterday..

**Comment by AlexHolly** [comment]
I use Unity...
I can't confirm 1. but I can add one more thing, sometimes the godot windows don't get stacked in the left bar in that case it is (almost?) never crashing. 
But when it stacks and I have to choose which godot window I want it's crashing.
I will try to test 2.

**Comment by akien-mga** [comment]
> I use Unity...

What for Beckett's sake are you doing here then?! [/joke]

**Comment by AlexHolly** [comment]
:D jeah at least I'm not on windows anymore hahah

**Comment by nunodonato** [comment]
I get this too
(Xfce Manjaro)

**Comment by punto-** [comment]
Can anyone on a system that can reproduce this get a stack trace of the
crash?

**Comment by nunodonato** [comment]
Sorry, I was comenting on another issue I selected the wrong tab. I do 
*not* experience this issue :)

Às 22:21 de 17-02-2016, punto- escreveu:
> Can anyone on a system that can reproduce this get a stack trace of the
> crash?
>
> On 17 February 2016 at 19:19, Nuno Donato <notifications@github.com> 
> wrote:
>
> > I get this too
> > (Xfce Manjaro)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/godotengine/godot/issues/3522#issuecomment-185432698>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/godotengine/godot/issues/3522#issuecomment-185433541>.
>

-- 
Nuno Donato
nuno@estudiodigital.pt | 966956602

estúdio digital <http://www.estudiodigital.pt>
www.estudiodigital.pt
Programação e Artes Digitais

**Comment by bojidar-bg** [comment]
Bump, can anyone reproduce it in the end?

**Comment by AlexHolly** [comment]
Can't reproduce with Godot_v2.1.2-stable_x11
