### ISSUE TITLE
Changing the preset settings of the textures can't be applied

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#35232]
**Godot version:** 3.2 RC

**OS/device including version:** Windows 10

**Issue description:** If I select a texture or multiple textures in Godot 3.2 RC and go in the Import tab and use a preset, then press Import, when I click on the image again I can see that his import settings are unchanged. But if I click manually on the settings I want without using the presets and reimport, the settings are changed correctly.

If we use a preset then set as default, the new default settings are registered correctly.

It does maybe the same with other file format by using the presets.

**Steps to reproduce:** select one or multiple images, go in the import tab and use a preset, click Reimport.

**Minimal reproduction project:** this can be done with the default godot icon in each project.

**Comment by groud** [comment]
Could you please fill in the issue template (and not delete it right away)?

**Comment by YeldhamDev** [comment]
I'm unable to reproduce this on master.

**Comment by Calinou** [comment]
Maybe this is due to the individual checkboxes next to each import option? Checking them will control whether the option will be changed for all selected files or not.

**Comment by YeldhamDev** [comment]
Nope, just encountered the bug.
