### ISSUE TITLE
Option to allow for selecting between different subtiles with the same bitmask in an autotile.

### ISSUE THREAD

**Issue by seriousCoolness** [godotengine/godot#35239]
To elaborate, I mean that if multiple subtiles have the same bitmask in a single autotile, you should be able to select between which tile you want to place in the tilemap. This would allow for things like being able to have one-way platforms and solid platforms exist seamlessly within the same autotile by giving the one-way platforms the same bitmask as the solid platforms. It would also probably be pretty easy to add, considering that you could reuse the same subtile selection thing that you see when "disable autotile" is on.

**Comment by KoBeWi** [comment]
Sounds like something for https://github.com/godotengine/godot-proposals

**Comment by Calinou** [comment]
Indeed, please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now meant to be used for bug reports only.
