### ISSUE TITLE
BakedLightInstance crashes editor if textures are not square

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#3524]
I'm using BakedLightInstance for baking some ligths.
Some models contained in a MeshLibrary have not-square textures (for example 256x512).
Editor crashes  with error  "malloc(): memory corruption: 0x10735708 ***".
It hapens on linux 32 and 64 bit.
Same models with square textures bake just fine.

**Comment by reduz** [comment]
light baker is kind of unfinished and won't be doing much work on this until the 3D rewrite, but feel free to check out the baker code here, you might find something:

https://github.com/godotengine/godot/blob/master/tools/editor/plugins/baked_light_baker.cpp

**Comment by reduz** [comment]
BakedLightInstance no longer exists, so closing this
