### ISSUE TITLE
Saving custom resource causes weird variable assign

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#35250]
**Godot version:**
3.2 beta 5
**OS/device including version:**
ubuntu 18.04
**Issue description:**

I'm creating a custom resource to save level editor data.

Project.gd
```
extends Resource
class_name Project

export var path_models:Array = []

export var crate_ids:Array = []
export var crate_time_ids:Array = []
export var crate_pos:PoolVector3Array = []

export var entity_ids:Array = []
export var entity_pos:PoolVector3Array = []

```
Save.gd
``` 
func save_level(project_name:String, paths:Array):
	var project:Project = Project.new()
	save_path(project,paths)
	var save_dir = project_dir+project_name+".tres"
	
	var err = ResourceSaver.save(save_dir,project)
	if err == OK:
		print("saved")
	else:
		print("Error saving: "+str(err) )

func save_path(project:Project, paths:Array):
	if paths.size() == 0: return
	print(paths.size())
	for path in paths:
		var dir = path.file_path # outputs a resource directory string
		project.path_models.append(dir)
	pass
 ```

Output file *.tres
 ```
[gd_resource type="Resource" load_steps=2 format=2]

[ext_resource path="res://resources/editor/Project.gd" type="Script" id=1]

[resource]
script = ExtResource( 1 )
path_models = [ "res://gameplay/level/tv/model_tv_ground_t0_b0_e0_v1.tscn", "res://gameplay/level/tv/model_tv_ground_t0_b0_e0_v1.tscn" ]
crate_ids = [ "res://gameplay/level/tv/model_tv_ground_t0_b0_e0_v1.tscn", "res://gameplay/level/tv/model_tv_ground_t0_b0_e0_v1.tscn" ]
crate_time_ids = [ "res://gameplay/level/tv/model_tv_ground_t0_b0_e0_v1.tscn", "res://gameplay/level/tv/model_tv_ground_t0_b0_e0_v1.tscn" ]
crate_pos = PoolVector3Array(  )
entity_ids = [ "res://gameplay/level/tv/model_tv_ground_t0_b0_e0_v1.tscn", "res://gameplay/level/tv/model_tv_ground_t0_b0_e0_v1.tscn" ]
entity_pos = PoolVector3Array(  )

 ```
As you can see above every variant of type Array was assigned with same value!!

**Steps to reproduce:**

Described above

**Minimal reproduction project:**
https://github.com/nonunknown/crashcreator/tree/f69ed64805d50721d58570537b08e74aae61aa5c

Test Snc_LevelEditos.tscn place two paths, click save button, then open app data folder in "user://projects/nameyougave.tres"

**Comment by KoBeWi** [comment]
Sorry for late reply, but seems like saving is not working in your project. Also what you describe is a bug that should've already been fixed (I use arrays in resources in my game and can confirm that they work correctly). Is this issue still valid in the stable release? Are you sure that you put correct elements into the array?

If the issue still happens, some actually minimal project would be helpful.

**Comment by nonunknown** [comment]
well, actually i'm saving in json format and is working fine to me, but i'll do a minimal reproduction project and post here!
