### ISSUE TITLE
Switching on "Raw" for any color in the editor allows RGB values above max

### ISSUE THREAD

**Issue by ktosox** [godotengine/godot#35253]
**Godot version: 3.2 RC**

**OS/device including version:  Ubuntu 19.10 **

**Issue description: after switching on raw for any color in the editor you can set the RGB values in a range from 0 to 100 , which seems wrong as it should only go from 0 to 1.**

**Steps to reproduce: go to the visibility tab on any 2d node, click on modulate then switch to raw**

**Minimal reproduction project: screen included**

![image](https://user-images.githubusercontent.com/28764702/72647718-741b6580-3979-11ea-8b0c-72a3329ed874.png)

**Comment by ktosox** [comment]
nvm, it's not a problem with the RC, this issue was present before, but I was oblivious to it

**Comment by Calinou** [comment]
I believe this is intended behavior. Otherwise, *overbright* colors would be clamped to `Color(1, 1, 1)` if their values were clamped when you turned off RAW mode.
