### ISSUE TITLE
C# script references break when being moved to a different folder

### ISSUE THREAD

**Issue by redmoss** [godotengine/godot#35252]
**Godot version:**
3.1.2 Mono

**OS/device including version:**
Windows 10

**Issue description:**
C# script references break when being moved to a different folder, with the error: "Source file xyz could not be found", and a reference to the location of the script file before it was moved; presumably Godot is still referencing the old location and it wasn't updated.

This works fine if you select something else, like GDScript instead of C#.

**Steps to reproduce:**

- Start a new project
- Create a scene with a single node
- Attach a C# script to the node
- Select both the scene file and the script file and right click -> Move To...
- Create a new directory and select Move
- When attempting to run, the error will show as described above

**Comment by JupiterRider** [comment]
The .csproj-File still points to the old .cs-Skript in the <Compile Include/> section.
**Solution:**
Remove the obsolete line.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by DeathTBO** [comment]
It seems to work correctly as of Godot 3.2.4 Beta 1
