### ISSUE TITLE
Custom Resources Crash Editor in 3.2 RC1 Mono

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot#35259]
**Godot version:** Godot Mono 3.2 RC1 (appears to also happen in beta 6, can only confirm did not happen in beta 2)

**OS/device including version:** Manjaro Arch Linux 18.1.5

**Issue description:** Upon loading a custom resource file into a scripted node that accepts a resource, it appears to crash Mono, and in turn crashes the editor, and leave the project in a state it will continue to crash whenever it has a .mono folder. The only way to stop the crashes if you put the resource script in the tres beforehand (look at the Reproduction Steps) is to delete .mono, strip every reference to the resource from Godot and Mono, rebuild in Godot (which may crash) then clean the build in an IDE, then start Godot back up.

**Steps to reproduce:**
1. Create a Project
2. Setup a scripted Node that accepts a resource export variable
3. Create an empty resource script
4. Create an empty resource file
5. Put the tres file into the Node's resource variable
6. Try to put the resource script into the tres file

It will crash at step 6.

If you don't follow these steps and instead put the resource script in the resource file first, the moment you stick the resource file into the Node variable, it will continue to crash Mono until .mono is deleted.

**Minimal reproduction project:**
[mono_test_proj.zip](https://github.com/godotengine/godot/files/4079617/mono_test_proj.zip)

**Comment by akien-mga** [comment]
I can reproduce the crash with the attached project on Linux in the current master branch (e7e8318):
```
ERROR: _unref: Condition ' !_p ' is true.
   At: core/dictionary.cpp:185.
free(): double free detected in tcache 2

Thread 19 "godot-mono" received signal SIGABRT, Aborted.

(gdb) bt
#0  0x00007ffff70f5a7a in raise () from /lib64/libc.so.6
#1  0x00007ffff70de524 in abort () from /lib64/libc.so.6
#2  0x00007ffff7137ff8 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff713e89a in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff71402a5 in _int_free () from /lib64/libc.so.6
#5  0x0000000003abfd6d in Memory::free_static (p_ptr=0x7fff94000c80, p_pad_align=false) at core/os/memory.cpp:178
#6  0x00000000014d4731 in memdelete<Object> (p_class=0x7fff94000c80) at ./core/os/memory.h:119
#7  0x0000000001a38fd7 in CSharpScript::_update_exports (this=0x7fff94006520) at modules/mono/csharp_script.cpp:2429
#8  0x0000000001a3e876 in CSharpScript::reload (this=0x7fff94006520, p_keep_state=false) at modules/mono/csharp_script.cpp:3232
#9  0x0000000001a3f625 in ResourceFormatLoaderCSharpScript::load (this=0x6663430, p_path=..., p_original_path=..., r_error=0x0) at modules/mono/csharp_script.cpp:3381
#10 0x0000000003b9019e in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:270
#11 0x0000000003b90ca5 in ResourceLoader::load (p_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:401
#12 0x000000000234581f in EditorResourcePreviewGenerator::generate_from_path (this=0xc47a160, p_path=..., p_size=...) at editor/editor_resource_preview.cpp:66
#13 0x0000000002347207 in EditorResourcePreview::_generate_preview (this=0x80e5670, r_texture=..., r_small_texture=..., p_item=..., cache_base=...) at editor/editor_resource_preview.cpp:167
#14 0x00000000023483b6 in EditorResourcePreview::_thread (this=0x80e5670) at editor/editor_resource_preview.cpp:269
#15 0x00000000023469be in EditorResourcePreview::_thread_func (ud=0x80e5670) at editor/editor_resource_preview.cpp:107
#16 0x000000000207d51d in ThreadPosix::thread_callback (userdata=0xd217900) at drivers/unix/thread_posix.cpp:74
#17 0x00007ffff756e04c in start_thread () from /lib64/libpthread.so.0
#18 0x00007ffff71bd58f in clone () from /lib64/libc.so.6
```

**Comment by neikeq** [comment]
This is a regression from ea737db43cba15e5d57442a647e9abcb91ed4ea7.
