### ISSUE TITLE
How to make parallax background follow vertically your character?

### ISSUE THREAD

**Issue by BrunoFerreira94** [godotengine/godot#3525]
How to make parallax background follow vertically your character like Plataformer 2D?

**Comment by Hinsbart** [comment]
For the future, please ask these kind of questions on the forums/reddit/irc/facebook first before opening an issue on github.
This is for bug reports and feature requests/enhancement discussions, thanks :)

Regarding your problem, just take a look at the platformer demo and see how it's done.
Remember you need at least one "ParallaxLayer" as a child of the "ParallaxBackground".
I think the parallax background automatically adapts to your camera movement, check `Motion/Scale` in the properties of the `parallax layer` to change the amount the layer moves relative to the camera movement. Also see how the platformer demo uses the `Mirroring` property to make scrolling seem infinite.

**Comment by BrunoFerreira94** [comment]
Ok, thank you so much :)
