### ISSUE TITLE
Godot 3.2 RC1 crashing again on issue solved in beta 6

### ISSUE THREAD

**Issue by Berkru** [godotengine/godot#35257]
**Godot version:**
3.2 RC1 - GLES3

**OS/device including version:**
Ubuntu Budgie 19.10 - AMD Ryzen 5 1600 - Radeon 550 Series 

**Issue description:**
[3D scene issue] Godot crashes when hit the Play Button. It has to do with the rendering of lights ( doesn't happen with lights off ).
This issue appeared in previous beta versions, but solved in beta 6.

**Screens:**
(First Screen shows the Crash)
(the second Screen is the log when I hit alt+Crtl+ F1) 
(the third  Screen shows it working with lights off)
https://imgur.com/k4uxJiu
https://imgur.com/f8bcIPV
https://imgur.com/PO6xqym

**Comment by Berkru** [comment]
![20200117_144054](https://user-images.githubusercontent.com/49285088/72650652-57ae0780-393e-11ea-925e-c9a98976804e.jpg)

**Comment by clayjohn** [comment]
This looks to be an issue with the amd linux drivers. See this thread for assistance https://forum.manjaro.org/t/amdgpu-fatal-error-during-gpu-init-solved/72700/8

**Comment by akien-mga** [comment]
@Berkru Are you able to compile from source? https://docs.godotengine.org/en/latest/development/compiling/compiling_for_x11.html

If so, it would be great if you could try to run a `git bisect` between 0ab1726b43dbe81c96d208a41a582435b76fd058 (beta 6, good) and ba7aca4199019529dec60555a5ff005f6692d281 (RC 1, bad).

But a first test to do before starting a long git bisect would be to try a local revert of 796d35d8b3af2ea78767149c07a2aae4bd0510cf (can be done from the `master` branch, or on top of ba7aca4199019529dec60555a5ff005f6692d281 (RC 1) to be sure), which has been identified as likely problematic in https://github.com/godotengine/godot/issues/35242#issuecomment-575884889

**Comment by akien-mga** [comment]
> But a first test to do before starting a long git bisect would be to try a local revert of [796d35d](https://github.com/godotengine/godot/commit/796d35d8b3af2ea78767149c07a2aae4bd0510cf) (can be done from the `master` branch, or on top of [ba7aca4](https://github.com/godotengine/godot/commit/ba7aca4199019529dec60555a5ff005f6692d281) (RC 1) to be sure), which has been identified as likely problematic in [#35242 (comment)](https://github.com/godotengine/godot/issues/35242#issuecomment-575884889)

I actually made a test build for this change, so you can try it directly: https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/godot.3.2.rc1.796d35d-reverted.x86_64.zip

If it works, that would confirm that this bug is the same as #35242 (but also affecting Linux drivers).

**Comment by Berkru** [comment]
> > But a first test to do before starting a long git bisect would be to try a local revert of [796d35d](https://github.com/godotengine/godot/commit/796d35d8b3af2ea78767149c07a2aae4bd0510cf) (can be done from the `master` branch, or on top of [ba7aca4](https://github.com/godotengine/godot/commit/ba7aca4199019529dec60555a5ff005f6692d281) (RC 1) to be sure), which has been identified as likely problematic in [#35242 (comment)](https://github.com/godotengine/godot/issues/35242#issuecomment-575884889)
> 
> I actually made a test build for this change, so you can try it directly: https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/godot.3.2.rc1.796d35d-reverted.x86_64.zip
> 
> If it works, that would confirm that this bug is the same as #35242 (but also affecting Linux drivers).

I'll give a try and post the feedback soon.
thanks.

**Comment by Berkru** [comment]
In the Scene I have a group of Omni Lights and a Directional as well.
it works fine if I enable either the group of omni lights or the directional light.
Enabling both, it crashes.
Not sure what I should do...

**Comment by Berkru** [comment]
**UPDATE**
it may be something to do with the Ubuntu update. tested again on beta 6 and it's also crashing.
3.1.2 version still runs smoothly though

**Comment by Berkru** [comment]
**UPDATE 2**
godot.3.2.rc1.796d35d-reverted.x86_64 worked on kernel v5.3.0 (my actual version is v5.4.0)
it gave some glitches at the beginning but didn't crash.
godot 3.1.2 version still runs smoother though (no glitches)

**Comment by Berkru** [comment]
Made this and the crash is solved on RC1: 
https://github.com/godotengine/godot/issues/35298#issuecomment-575956634
SOLVED!

**Comment by clayjohn** [comment]
Great! To that means #35302 will fix this for you!
