### ISSUE TITLE
texturerect set mouse filter is pass, scrollcontainer mouse enter signal cannot detected

### ISSUE THREAD

**Issue by yuyubibibobibo** [godotengine/godot#35262]
**Godot version:**
3.2rc1

**OS/device including version:**
windows

**Issue description:**
texturerect set mouse filter is pass and follow cursor, scrollcontainer mouse enter signal cannot detected
same issue：
#6362   #20881
*Steps to reproduce:**

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/4079859/bug.zip)

**Comment by KoBeWi** [comment]
I don't really see issue here. The signal is properly detected when I connect it. Also
> same issue：

closing as duplicate.

I can reopen if you provide more details and the issue is valid (i.e. bug and not duplicate).
