### ISSUE TITLE
OpenGL: Garbage collection lag spikes

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#35264]
**Godot version:**
**2.0 to 3.2**.rc1, possibly all versions

**OS/device including version:**
Windows 10 1909
Radeon VII - Adrenalin 20.1.1
GTX 1660 Ti Max-Q - 441.20 DCH
GTX 980 Ti

**Issue description:**
All projects - including blank ones - have cyclic lag spikes in the editor, tests, and exports which last between 8 and 19 seconds. Spikes last for only a few frames.
This is most likely due to a poorly optimized OpenGL garbage collector.

![image](https://user-images.githubusercontent.com/5272529/72660504-a4bcc880-3994-11ea-803f-119c6fd78094.png)

**Comment by Calinou** [comment]
See also #34732.

Does it improve if you disable ETC2 texture importing in the Project Settings?

**Comment by hoontee** [comment]
Unrelated to the bug you've referenced. This one's related to system memory, not video memory.

Radeon VII - Adrenalin 20.1.1.
This issue occurs in empty projects.
Disabling ETC2 doesn't improve anything.

**Comment by hoontee** [comment]
Issue also occurs on 1660 Ti.

**Comment by hoontee** [comment]
Looks like this might have been a known issue since 2016: https://godotengine.org/qa/4244/frame-rate-consistently-stutters-about-every-ten-seconds

**Comment by hoontee** [comment]
Memory usage does not increase while game is paused. (Radeon VII GLES3)

**Comment by hoontee** [comment]
Placebo. The FPS monitor was reporting incorrect amounts.

**Comment by Calinou** [comment]
@hoontee If you want to test this more accurately, you could print the difference between `Engine.get_ticks_msec()` and the last frame (store the last value in a variable) in `process()`.

**Comment by hoontee** [comment]
@Calinou Always stays between 16-18 milliseconds despite the monitor stats.
