### ISSUE TITLE
Cannot access AnimationNode methods from an AnimationNodeStateMachine or AnimationNodeAnimation

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#35272]
**Godot version:**
3.2 beta 4 / 3.2 RC1

**OS/device including version:**
Windows 10 Professional 64bits 1909 (18363.592)

**Issue description:**
Cannot access AnimationNode methods from an AnimationNodeStateMachine or AnimationNodeAnimation in GDScript while they inherit from AnimationNode.

![bug_animationNodeStateMachine](https://user-images.githubusercontent.com/46683101/72663171-a9fb3100-39ef-11ea-9708-b8e955f7d036.jpg)

[AnimationNodeStateMachine](https://docs.godotengine.org/en/latest/classes/class_animationnodestatemachine.html)

**Steps to reproduce:**
Just create an `AnimationNodeStateMachine` and try to access an `AnimationNode` method from it.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Is this related to #19878 and #22129?

**Comment by KoBeWi** [comment]
Still valid in 210ebb0
These methods have `virtual` in the documentation, not sure what it means here.

**Comment by akien-mga** [comment]
Fixed by #64537.
