### ISSUE TITLE
error message with "save scene as" if scene is still open

### ISSUE THREAD

**Issue by AndHalfAFish** [godotengine/godot#35274]
**Godot version:**
Godot 3.2beta4

**OS/device including version:**
Win 10

**Issue description:**
if you try to save a scene (that you're currently working on) with : "scene > save scene as", you get an error message "Warning! Can't overwrite scene that is still open!".

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by YeldhamDev** [comment]
Can't reproduce this on master, could you try again with the latest release candidate version?

**Comment by veryprofessionaldodo** [comment]
I have the same result than @YeldhamDev , can't reproduce this on my end using master.

**Comment by akien-mga** [comment]
I can reproduce it by using "Save Scene As" with the same filename as the original scene I'm re-saving.

This is expected, "Save Scene As" is meant to save the current scene under a different name. It's good that it shows a warning if you reuse the same name.
