### ISSUE TITLE
Custom c++ modules not working in exported builds?

### ISSUE THREAD

**Issue by D00T24** [godotengine/godot#35299]
Godot version: 3.1.2 stable custom build

Build flags: scons platform=x11 -j2  target=debug

Module source : `https://github.com/D00T24/testnode`

OS/device including version: Arch Linux x86_64  Kernel:5.4.12-arch1-1 

Issue description: custom modules don't work in exported builds but work perfectly fine in the editor

I made a simple node that derives from Node2D this custom node works fine in the editor but when running a exported build it's not loaded. trying to find the custom node from other nodes with get_node() returns null.

this also happens when making a simple class. I followed the Custom modules in C++ guide from the docs and using the example class in exported build throws out this error:

`SCRIPT ERROR: GDScript::reload: Parse Error: Identifier 'Summator' is not declared in the current scope. At: built-in:4.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
At: modules/gdscript/gdscript.cpp:580.

Steps to reproduce: 
1.add a custom c++ module to modules folder
2.recompile godot and add the node in the scene then export
3.the node will not be in the exported build this can be verified by either making the custom node scene root (which crashes the build) or by trying to find it with get_node() from another node which returns null
`

**Comment by Calinou** [comment]
You need to recompile the export template from source as well. Make sure to specify it in the export preset (Custom Release or Custom Debug path).

**Comment by Xrayez** [comment]
Specifically for compiling export templates:
```
scons platform=x11 -j2 tools=no target=release
```
If you find the terminology confusing, take a look at this proposal if interested: godotengine/godot-proposals#288.

**Comment by D00T24** [comment]
> When you build a C++ module statically into the engine, you need to recompile the export template from source as well. Make sure to specify it in the export preset (Custom Release or Custom Debug path).

Thanks Calinou! this fixes the issue.

This step should be mentioned in Custom modules in C++ documentation, it should at least link to the export templates documentation as it's really confusing when you follow the tutorial and your custom module doesn't work when exported.
