### ISSUE TITLE
android build template fails -  Task :lint 

### ISSUE THREAD

**Issue by jugrigori** [godotengine/godot#35296]
**Godot version:**  2.1

**OS/device including version:**  Microsoft Windows  10.0.18362

**Issue description:** > Task :lint 
> Task :lint
Ran lint on variant debug: 166 issues found
Ran lint on variant release: 166 issues found
Wrote HTML report to file: .../godot-2.1/platform/android/java/build/reports/lint-results.html
Wrote XML report to file: .../godot-2.1/platform/android/java/build/reports/lint-results.xml
BUILD SUCCESSFUL in 1m 16s
54 actionable tasks: 19 executed, 35 up-to-date

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is not an error. As it says at the end of the log, the build was successful. Gradle just reports some deprecations and style issues.
