### ISSUE TITLE
Qauternion get_euler returnign wrong value

### ISSUE THREAD

**Issue by rasikrodri** [godotengine/godot#35292]
**Godot version:**
Godot 3.2 Beta 6

**OS/device including version:**
Windows 10

**Issue description:**
I am writing a mesh and animation importer for Hash Animation Master.
I import the bone as quaternion and then when I get the euler fromn the quaternion y and z are completely wrong.

This does not seem to be happening for all the bones while importing them.
The rotation in Animation Master in degrees is x=-90.047, y=0, z=0,. The quaternion loaded form the file is:
-0.707399249 -2.14412967e-06 7.73862681e-08 0.706814349
After the quaternion is created it has the following values x=-0.707399, y=-0.000002, z=0, w=0.706814

I should be able to get the Euler in degrees of x=-90.047, y=0, z=0, or very close to it but I am getting the Euler in degrees of x=-89.951546, y=-179.782471, z=-179.782318

If you go to https://www.andre-gaschler.com/rotationconverter/ and enter the values of the created quaternion an Euler of degrees x:-90.0473935, y:-0.000162, z:-0.0001621 which is much closer
**Steps to reproduce:**

**Minimal reproduction project:**
Just create a new node and attach the following code and inspect the values.
var quat:Quat = Quat(-0.707399249, -2.14412967e-06, 7.73862681e-08, 0.706814349)
		var euler:Vector3 = Vector3(rad2deg(quat.get_euler().x), rad2deg(quat.get_euler().y), rad2deg(quat.get_euler().z))

**Comment by kesinger** [comment]
Are you sure those aren't the same rotation? Euler angles aren't unique, and if you think about what it's doing, the y- and z- movements should cancel each other out.

**Comment by rasikrodri** [comment]
As I understand Eulers axis are applied in order to get to the same
position the quaternion should be.

If this is the case then y and z cannot cancel each other

Please correct me if I am wrong.

**Comment by rasikrodri** [comment]
Also the website I provided gives the correct euler values from the same
quaternion

**Comment by rasikrodri** [comment]
After calculating in my mind how the bone will end, and if you meant that
the bone will end up in the same position, I think you might me rigth.

I will test this when I get home

**Comment by rasikrodri** [comment]
I have just tested and the bone should end having the same orientation. 

I am closing the issue.
