### ISSUE TITLE
Godot requirements (and their run-time check)

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#3529]
Godot runs extremely slow. How find out why? I guess I need to profile it at run-time somehow.

**Comment by reduz** [comment]
Alterntively, and only if you get tired of profiling, you could describe
your OS, hardware configuration, driver, etc.

**Comment by reduz** [comment]
Otherwise feel free to keep profiling :)

**Comment by techtonik** [comment]
@reduz can you point to How To that explains how to do the profiling? My system is pretty low end, but I don't see why I can't create 2D games with it.

**Comment by reduz** [comment]
Godot uses 2D to render and requires OpenGL ES 2.1. your system most likely does not support OpenGL ES 2.1 and instead uses software emulation.  This causes slowness. Nothing can be do to fix it.

**Comment by techtonik** [comment]
Is Godot able to test for available OpenGL ES 2.1 features? Because in future it may require ES 3, 4 and 5, and there is no point in using it - if I want to develop games for the top hardware - I will probably choose UE4. And when something like FTL which moves a dozen of pixels at a time doesn't work on a 4Gb machine with 3GHz in year 2016 - it is a degradation. In 1999 without those GLs it would be faster than light.

**Comment by techtonik** [comment]
> Nothing can be do to fix it.

How about https://github.com/google/angle ?

**Comment by reduz** [comment]
Computers like yours are extremely rare nowadays, which is why Angle is not
used. If you want to contribute optional Angle support it's welcome.

**Comment by techtonik** [comment]
> Computers like yours are extremely rare nowadays
Where do you get this data?

> If you want to contribute optional Angle support it's welcome.
I'd like to try replacing the opengl32.dll first - https://groups.google.com/forum/#!topic/angleproject/j97Ps7gtkug - but I guess #3546 is a more important bug at the moment.

**Comment by punto-** [comment]
We don't actually use gles2 on desktop, just normal gl.. To get it to run
angle you'll probably need a context_gl that uses egl and then use the
gles2 headers directly on the rasterizer. the winrt platform already does
this, but the context is for winrt, which is a different api, but it
shouldn't be too hard to do one for normal windows

**Comment by techtonik** [comment]
@punto when I run Godot with `-h` flag, it shows GLES2 as video driver.

         -vd DRIVER       : Video Driver (GLES2)

Where does it get this string? Can this key display all drivers available? It would be nice to see some info about chosen driver if `-d` or `-d -v` is specified.

>  To get it to run angle you'll probably need a context_gl that uses egl and then use the
gles2 headers directly on the rasterizer.

Do I need to compile it? If yes, then I guess I am out of luck. Is it possible to use this `-vd GLES2` option to choose GLES2 and make sure that it finds required libGLESv2.dll driver (I mean provide debug information if driver is not found)?

**Comment by punto-** [comment]
I don't think there's a native gles dll for desktops, is there? It has to
compile at least the part that uses egl, and I would also compile angle
otherwise you have to also distribute those dlls.. The "gles2" string just
means it's the gles2 rasterizer with a few #ifdefs to get it to also
compile on desktops.

**Comment by techtonik** [comment]
@punto if I understand correctly, ANGLE is that native GLES driver (that translates hard stuff to DirectX) with libEGL.dll and libGLESv2.dll  Google Chrome ships both .dlls and renders all WebGL stuff through it.

> The "gles2" string just means it's the gles2 rasterizer with a few #ifdefs to get it to also compile on desktops.

I am not sure that does this mean. For me `driver` is the stuff that is responsible to get rendered picture (or 3D graph) to the screen (or stream). So, SDL or OpenGL or DirectX are drivers for me.

**Comment by akien-mga** [comment]
>> The "gles2" string just means it's the gles2 rasterizer with a few #ifdefs to get it to also compile on desktops.

> I am not sure that does this mean.

It means that "gles2" is the name uses for the Godot driver code that will select either GLES2 or GL2 features depending on the platform: https://github.com/godotengine/godot/tree/master/drivers/gles2
It's just the name we use, but it could be displayed as "GLES2 (embedded)/GL2 (desktop) driver" or "Coffee maker" ;)

**Comment by techtonik** [comment]
"Coffee maker" is less confusing. =) It may even come with a small manual that contains some advertisement pictures and instructions how to force it to make ES 2.0 or plain GL presso. For example, I'd expect it to respond to invalid `-vd` option with a list of possible modes, and react to `-d` with at least the following information:

```
Video driver selected: "Coffee maker"
Coffee maker: No options specified, using default detection routine
Coffee maker: Windows detected, trying OpenGL ES 2.0
Coffee maker: OpenGL ES 2.0: libGLESv2.dll is not found
Coffee maker: Trying OpenGL 2.0
Coffee maker: OpenGL 2.0: Found opengl32.dll, linking
Coffee maker: OpenGL 2.0: 24/124 symbols found, ...
Coffee maker: OpenGL 2.0: Loading emulation layer for 100 methods
Coffee maker: OpenGL 2.0: Loading regal32.dll
Coffee maker: ...
```


```
