### ISSUE TITLE
Visible inactive plugin

### ISSUE THREAD

**Issue by q4a** [godotengine/godot#35291]
**Godot version:** 3.2 beta 6, and same after update to 3.2 RC 1

**OS/device including version:** Windows 10 1909 (18363.535) Home

**Issue description:** I changed gd script file from external text editor and then come back to Godot. I saw duplicate of tab "ResImporter". Then I tried to disable my plugin, but one tab "ResImporter" was still visible. Removing and import same project don't help.
If i click on it, i got error:
 editor/editor_node.cpp:2875 - Index p_which=5 out of size (editor_table.size()=5)
![inactive plugin](https://user-images.githubusercontent.com/1950719/72668679-71cd1000-3a3a-11ea-8d6f-c9a99ca159c3.png)

**Steps to reproduce:** Sorry, but I don't know.

**Minimal reproduction project:** here is my project, where bug happend
https://github.com/q4a/opengri/tree/2ef6cba082e0effbb742627cbe387c0891a39d43

**Comment by q4a** [comment]
I found my problem: i renamed plugin folder name from opengri to OpenGRI and got this string in project.godot:
enabled=PoolStringArray( "OpenGRI", "godot-plugin-refresher", "opengri" )

Removing "opengri" fix error.

**Comment by Calinou** [comment]
I suppose this is due to case insensitivity on Windows. I'm not sure if anything can be done about it.
