### ISSUE TITLE
Error with Exported C# Game: "Mono: Core API hash mismatch."

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#35290]
**Godot version:**
Any Godot 3.2 Version

**OS/device including version:**
Windows 10, Linux 

**Issue description:**
Executing Mono Games build with the Default Templates gives you following Error Message in the Command Line:
```
ERROR: _init_godot_api_hashes: Mono: Core API hash mismatch.
   At: modules/mono/mono_gd/gd_mono.cpp:465.
```

**Steps to reproduce:**
Export a C# game by using the default templates.
Execute it on Windows or Linux.
![vcghyfun8db41](https://user-images.githubusercontent.com/60042618/72668233-03318780-3a25-11ea-9b1f-469b8057f894.png)

**Comment by akien-mga** [comment]
Indeed, this error has been around for a while on debug export templates.

It doesn't impact use however, and it seems to be a false positive (at least the Core API used to build the glue and the template is from the same commit).

@neikeq is aware of the issue, but I don't know if any fix has been tested yet.

**Comment by akien-mga** [comment]
For the reference, this is likely still due to #30496, but keeping this issue open as users will look for this error message in the issue tracker.
