### ISSUE TITLE
Tilemap : Can only edit tilemap in select mode

### ISSUE THREAD

**Issue by securas** [godotengine/godot#35309]
**Godot version:**
3.2 RC1

**OS/device including version:**
Windows 10

**Issue description:**
Can only edit a tilemap when setting "Select Mode". Don't know if this is intentional but it goes against the behavior of 3.1.x and before. It should be possible to edit the tilemap in "Select Mode", "Move Mode", or "Rotate Mode"

**Comment by bojidar-bg** [comment]
This was discussed in #23343, and then implemented in #31535. While this is certainly a change of behavior, it was mostly intended to be a bugfix, as visually moving/rotating/scaling the tilemap was previously impossible.

**Comment by securas** [comment]
I see. Makes sense, I suppose. I guess, entering a tilemap "edit" mode when clicking a tile would be too complex to implement.
