### ISSUE TITLE
ColorRamps don't seem to work reliably with alpha in 2D (.tscn format)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#3530]
ColorRamps seem to lose alpha information in .tscn scenes, when used with Particles2D.

You can find an example project below. The alpha in the 2nd stage of the ColorRamp was set to 0 (also tried 1), but it resets itself to 255 when the project is loaded.
[particle-fade-2d.zip](https://github.com/godotengine/godot/files/111308/particle-fade-2d.zip)

[Video without alpha (appears when running game)](https://up1.ca/#Ye0l1OOiA242jj4vTWxWhg)
[Video with alpha (appears in editor)](https://up1.ca/#vVyxHB4Bi3ydBAcXPhkYGQ)

Tested on 2.0beta with commit https://github.com/godotengine/godot/commit/987bfb4b5e99bb11ecfd914e80d59b9bde62e26f.

**Comment by bojidar-bg** [comment]
I can confirm.

**Comment by Biliogadafr** [comment]
Indeed it works bad with tscn. Colors are interpreted in a wrong way. With some shift. Alpha from the first point of color ramp changes red channel of the second point. Alpha of the second point changes green channel of the third point. Alpha of the third point changes blue channel of the fourth point.
