### ISSUE TITLE
texturerect get_global_transform.rotated is nowork

### ISSUE THREAD

**Issue by yuyubibibobibo** [godotengine/godot#35308]
**Godot version:**
3.2 rc1

**OS/device including version:**
windows

**Issue description:**
cuz transform.rotated() is nowork, many this is reason why rect2 cannot rotate

**Steps to reproduce:**

**Minimal reproduction project:** [bug2.zip](https://github.com/godotengine/godot/files/4082438/bug2.zip)

**Comment by KoBeWi** [comment]
`Transform2D.rotated()` *returns* a new transform with applied rotation. It does not apply the rotation to original transform.

Also seems like there's no way to directly modify transform of Control nodes (at least in obvious way). Node2D might be better suited here.

**Comment by yuyubibibobibo** [comment]
> `Transform2D.rotated()` _returns_ a new transform with applied rotation. It does not apply the rotation to original transform.
> 
> Also seems like there's no way to directly modify transform of Control nodes (at least in obvious way). Node2D might be better suited here.

global_transform  relates to world coord，so it isnot object space...
