### ISSUE TITLE
3.2RC1, crate collision body from mesh all missing effect with static body 3d

### ISSUE THREAD

**Issue by cg1743gmail** [godotengine/godot#35318]
**Godot version:**3.2RC1

**OS/device including version:**

**Issue description:**   3.2RC1, crate collision body from mesh all missing effect with static body 3d

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Ace-Dragon** [comment]
This is a bit vague, and the report does not contain reproduction steps nor a reproduction project.

It also does not indicate whether or not there was a regression.

**Comment by Chaosus** [comment]
Yeah, I don't think too that its a correctly formed issue. Please recreate it more explained, for now, I close it.
