### ISSUE TITLE
AudioStreamPlayer ignores Resource loop option

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#35314]
**Godot version:** 43caf83c

**OS/device including version:** Linux 5.4.12-1-MANJARO # 1 SMP PREEMPT Wed Jan 15 08:05:08 UTC 2020 x86_64 GNU/Linux

**Issue description:** Despite the loopback option turned off, a call to `play()` causes the sound to play continuously in a loop.

**Steps to reproduce:**
* Add AudioStreamPlayer
* Import OGG-sound
* Uncheck loop option in OGG-resource settings
* Bind `play()` method on pressing button
* Press the button

**Minimal reproduction project:** [test.tar.gz](https://github.com/godotengine/godot/files/4082668/test.tar.gz)

**Comment by akien-mga** [comment]
I can't reproduce it, it works fine for me.
It even works with Live scene editing by toggling off "Loop" while the game and sound are playing.

**Comment by toby3d** [comment]
Oops, the problem was in PulseAudio.

**Comment by toby3d** [comment]
Ah, no, it doesn't seem to be in PA. The checkbox is not updates option in the resource properties, I have to open the scene in a text editor and change the `loop` parameter from `true` to `false` manually.
![image](https://user-images.githubusercontent.com/5412322/72690079-711ba300-3b3a-11ea-8977-4b00af33f571.png)

**Comment by PapaCheese** [comment]
is there a way around this? i want to use ogg because its light but i cant make it not loop

**Comment by akien-mga** [comment]
I still can't reproduce the issue.

When you import an OGG file, you can define whether you want it to loop or not in the Import tab. If you change your mind, you can reimport it.

![Screenshot_20200708_090455](https://user-images.githubusercontent.com/4701338/86888209-1979ef80-c0fa-11ea-8e6e-7c2bc18808a0.png)
This will loop.

![Screenshot_20200708_090514](https://user-images.githubusercontent.com/4701338/86888243-2565b180-c0fa-11ea-92fb-86d3e43f6f43.png)
This won't (you should click "Reimport" to apply changes).

Alternatively, if you don't want to reimport the OGG (e.g. you use it looping in some places, non looping in others), you can save the imported resource as a .tres file (with "Save as" in the inspector) and then you are able to change its import options on a per-resource basis.
