### ISSUE TITLE
RigidBody always rotation locked in Bullet Engine

### ISSUE THREAD

**Issue by ZainlessBrombie** [godotengine/godot#35315]
**Godot version:**
v3.1.2.stable.official

**OS/device including version:**
Linux 4.15.0-54-generic #58-Ubuntu (Mint)

**Issue description:**
The scene contains two rigidbodies, one being controlled by the keys "w" and "a". Neither the apply_torque_impulse method nor the collision causes the body to rotate. Switching the physics engine to Godot Physics "fixes" the problem

**Steps to reproduce:**
Create a rigidbody with a collision shape. Set the physics engine to Bullet. Attempt to rotate the body. But don't bother with that, just download the sample project.
[rotation_locked.zip](https://github.com/godotengine/godot/files/4082669/rotation_locked.zip)

**Comment by ZainlessBrombie** [comment]
Possibly related: https://github.com/godotengine/godot/issues/24380

**Comment by fossegutten** [comment]
Not sure if this is new information. But I encountered similar bugs in 3D. Works fine in 2D it seems, after having tested it. 
In RigidBody (3D) nodes, `add_torque_impulse `seems to do nothing. `add_impulse` behaves similar to `add_central_impulse`, no matter what i put into the `position` parameter. This narrows it down to some problem with the applied_torque, in my mind.

**Comment by tom-jk** [comment]
The CollisionShape on your player body was invalid (it says you can't use ConcavePolygonShape on non-static mode rigid bodies). Swapping it out for some other valid shape (eg. a cylinder) allowed it to be rotated in game. It looks as though collision shapes are used to calculate the centre of mass, so: no valid shape, no centre of mass, no rotation.

**Comment by ZainlessBrombie** [comment]
Thank you. Seems then users should either provide a center of mass or be warned that the thing is rotation locked despite its options not being set so.

**Comment by pouleyKetchoupp** [comment]
Given there's already a warning in the editor tree stating that you shouldn't use `ConcavePolygonShape` with a non-static body, there's already enough information for the user, so closing.
