### ISSUE TITLE
C# bug with Position()

### ISSUE THREAD

**Issue by 111ukasz111** [godotengine/godot#35329]
**Godot version:**
v3.2-rc1_mono_win64
**OS/device including version:**
Windows 10 

**Issue description:**
this.Position(); does not work
**Steps to reproduce:**
1.Write this.GetPosition();
2.GetPosition is deprecated. Use the Position property instead.” [flappybird]csharp(CS0618
3.Write this.Position(); 
this.Position(); does not work
**Minimal reproduction project:**
[flappybird.zip](https://github.com/godotengine/godot/files/4083476/flappybird.zip)

**Comment by MordechaiHadad** [comment]
Position is a property not a method so if you wanna change it you gotta write something like:

`this.Position = new Vector{x = 10, y =10};`

**Comment by 111ukasz111** [comment]
Thanks
