### ISSUE TITLE
3.2 RC1 Regression.  Inspector panel sizes change when using debugger.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#35324]
**Godot version:**
3.2 RC1

**OS/device including version:**
Win10 64-bit

**Issue description:**
When I step through code using the debugger the inspector now changes size and quickly changes back.  This misplaces the buttons which can result in mis-clicking, and it is very jarring when trying to watch where the code is stepping to.

Not happening in the versions of 3.1 I have been using.

May be related to:  https://github.com/godotengine/godot/issues/33741

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/72686216-e2d3fc80-3afa-11ea-9b0c-12e1867c9f93.gif)

**Steps to reproduce:**
Step along a GDScript break point.

**Minimal reproduction project:**
Any project will do.

**Comment by Calinou** [comment]
Can you reproduce this in any of the older 3.2 betas? This may be hard to fix without knowing which commit caused the regression exactly.

**Comment by avencherus** [comment]
Not present in 3.2 beta 1.

Will look further if I get a chance tomorrow.

**Comment by avencherus** [comment]
Can't imagine what the cause from this, but bisected to cc85be3aaeb183eb1d9a991317ac3b7d1b3aafe2, it must be exposing the other issue.

@lupoDharkael any ideas?

**Comment by avencherus** [comment]
Bisected the other issue to f275de24eeebf954736f3a1278ed8875e7f861d6
