### ISSUE TITLE
 MSAA does not work for GODOT v3.2.rc1.official ,GLES2, HTML export 

### ISSUE THREAD

**Issue by ssatguru** [godotengine/godot#35335]
**Godot version:**
Godot Engine v3.2.rc1.official
OpenGL ES 2.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

**OS/device including version:**
Windows 10 Home
Version 1809
OS build 17763.973

**Issue description:**
MSAA does not work in HTML5 export for a 3D GLES2 project .
I get lot of aliasing.
MSAA works when Played (F5) from IDE and works for Windows Desktop export

For now using the workaround mentioned here
https://godotengine.org/qa/54752/no-fxaa-support-in-3-1-1
Adding the FXAA.tscn to my scene, as mentioned there, provides anit-aliasing

**Steps to reproduce:**
Enable MSAA
Goto Project Settings->General->Rendering->Quality->Filters->Msaa
Select a Msaa setting - one of 2x, 4x, 8x or 16x
Export to HTML ,export to Windows Desktop,
 run
HTML - no anti-aliasing 
Windows - anit-aliasing

Also  tried
Project Settings->General->Global->Msaa
NOTE: Here Msaa is repeated twice

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
WebGL 1.0 doesn't support MSAA, so we can't implement it for WebGL builds. 

This limitation should be documented somewhere to make it easier for users to discover.

**Comment by Calinou** [comment]
@clayjohn I remember seeing many WebGL 1.0 applications supporting MSAA. I'm not sure how they did it (is there an optional extension)?

**Comment by clayjohn** [comment]
@Calinou they can support it on the backbuffer. There is a flag you can use to request it on context creation. But it is optional, and doesn't apply to any other Framebuffers. 

Godot renders everything to a Framebuffer and then copies it directly to the back buffer. So it's not possible to get MSAA.

**Comment by ssatguru** [comment]
Does it make sense to provide FXAA support then? user can select MSAA or FXAA?

**Comment by Calinou** [comment]
@ssatguru It can already be provided using a shader like [this one](https://gist.github.com/cart/7d2da58eb28c75c0952787f29f3e562f). We might add a built-in option in 4.0, but no guarantees.

**Comment by ssatguru** [comment]
Yes I am using that for now, but not having much expertise in shaders not sure how it works or its implications. Would be nice to have some "official" support.
