### ISSUE TITLE
Doc items breaking into groups by first sentence rather than alphabetically

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#35347]
**Godot version:**
3.1 - 3.2rc1

**Issue description:**
Looks like incorrect spacing where it shouldn't and not breaking where it should:
![image](https://user-images.githubusercontent.com/3036176/72701394-34fb3900-3b60-11ea-9a66-5b0b4235f036.png)

**Comment by Chaosus** [comment]
Ah, maybe it's just a matter of taste... They are grouped by first sub-sentence rather than alphabetically,  which may be ok.

**Comment by mdante97** [comment]
Hi, I would like to take on this issue, but not exactly sure on how assigning these work. I would be happy in helping to sort out the doc items alphabetically.

**Comment by Calinou** [comment]
@mdante97 I think the current way of sorting is fine. It's already alphabetical, it just happens to group by first sub-sentence like `distance` or `is_`.

This issue can probably be closed.

**Comment by akien-mga** [comment]
I think the grouping by prefix similarity could simply be removed now. I assume it was done back in the days when we didn't have properties and had dozens of `set_`, `get_` and `is_` methods. This is no longer the case so I think the prefix grouping is rarely meaningful.

**Comment by Anukriti12** [comment]
Removing additional newline command in editor_help.cpp at line 675 should do it.
I'm not sure how exactly should I make a pull request now that master branch is unstable (https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable)

**Comment by Calinou** [comment]
@Anukriti12 Feel free to open a pull request right now, you can rebase it in the future if it gets conflicts due to refactorings. That said, I believe editor-related refactorings have mostly been completed by now (especially for parts that could affect the editor help).

**Comment by ChristopheLY** [comment]
@Anukriti12 without newline, it's hard to read and find a method when they are a lot.

**Comment by ChristopheLY** [comment]
something else, if we break by alphabetically the section Methods, we need to do the same for Properties which above Methods for the same reason

**Comment by ChristopheLY** [comment]
#8a1ed47ddd2ff1f8da74a038bf462b44657d3c63

**Comment by ChristopheLY** [comment]
#39141

**Comment by Chaosus** [comment]
I think this looks okayish now (compared to the original screenshot):

![изображение](https://github.com/user-attachments/assets/1b4a49c1-3c27-4533-a602-02ecc5cf4b5d)
