### ISSUE TITLE
Different arranging behavior in Godot 2.0 Alpa and Beta

### ISSUE THREAD

**Issue by ArsCreativa** [godotengine/godot#3535]
Hi, I'm attaching an image of the issue and an example.
In Beta version, the code to arrange 100 child buttons in rows and columns doesn't work as expected.
The left image is from Beta, the right one from Alpha

![arrissue](https://cloud.githubusercontent.com/assets/14160478/12713881/82471aea-c8d1-11e5-95fc-a1992ab77815.jpg)

[ArrangingIssue.zip](https://github.com/godotengine/godot/files/111988/ArrangingIssue.zip)

**Comment by nopeson** [comment]
I tried it... same here (with the beta).

**Comment by reduz** [comment]
Ah yes, i think a PR changed this because it made it difficult to work with containers and the most common case was putting them vertically.  That said, in 2.1 buttongroups will be changed with the addition of resources local to scene, and will use that instead.

**Comment by akien-mga** [comment]
What's the status on this issue in the 2.1-beta release?

**Comment by reduz** [comment]
nothing was done.. this requires breaking compatibility so noting it down there for 3.0

**Comment by reduz** [comment]
this can be closed, as ButtonGroups were rewritten in 3.0 and the node no longer exists
