### ISSUE TITLE
New Autotile Hides to half Inspector

### ISSUE THREAD

**Issue by rakun99** [godotengine/godot#35356]
**Godot version: 3.2 rc2 ** 

**OS/device including version: Windows 7 **

**Issue description:When I create a new autotile, it makes Inspector on right panel to hide by half ** 

**Steps to reproduce:**

**Minimal reproduction project:**

![bug](https://user-images.githubusercontent.com/46073558/72723012-25e4ad00-3b99-11ea-93ac-23215f423327.PNG)

**Comment by akien-mga** [comment]
Consolidating all issues regarding to the inspector going out of the window due to too many/long buttons in main screen toolbars in #31133.

**Comment by rakun99** [comment]
> Consolidating all issues regarding to the inspector going out of the window due to too many/long buttons in main screen toolbars in #31133.
Well I guess I need to emigrate on eng version.
