### ISSUE TITLE
Vulkan: 2D GPU Particles dont work

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#35353]
GPU Particles are not working on the Vulkan 4.0 branch.
Ticking the enable check box doesn't turn the particle system on.

**Comment by ilyafuu** [comment]
soon merger master + vulkan is still too early to wait for release 3.2 :D

**Comment by Calinou** [comment]
This is expected; GPU particles haven't been reimplemented yet.

**Comment by KoBeWi** [comment]
With #41711 merged, 3D particles are back. 2D particles are waiting for 2D engine rewrite, so they still don't work.
