### ISSUE TITLE
Android export with custom build failed

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#35354]
**Godot version:**
Godot 3.2.rc (5f99e3396f)

**OS/device including version:**
MacOSX 10.14.6 (18G95)

**Issue description:**

I'm trying to export my project (which I made before in 3.2.beta4). It have custom android template. I updated godot from master, rebuild it and all android templates. Then I remove `android` folder from my project and recreated it with new template.

When I try to build the project I have errors:

![Снимок экрана 2020-01-20 в 11 45 47](https://user-images.githubusercontent.com/1177068/72711650-78fb3780-3b7a-11ea-9e29-3e1f09f055d0.png)

(I don't know how to copy the text log from this view)

I have found that this (https://github.com/godotengine/godot/commit/50ab6decfef) commit changed `config.gradle` so it must use property `export_package_name` which is set as `package/unique_name` from project export settings. 

But it looks like the game resources must be modified in order to be found in new path.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by DrMoriarty** [comment]
Minimal project:
[test-project.zip](https://github.com/godotengine/godot/files/4085270/test-project.zip)

**Comment by DrMoriarty** [comment]
Seems to be fixed in 11260fb87f

**Comment by akien-mga** [comment]
That's surprising, as not much changed for that between rc1 and rc2...
I'll close for now, but we can reopen if you can reproduce it again.
