### ISSUE TITLE
GLES 3 DRIVER ERROR! = Win 7 : 32bits = Engine 3.2 rc2

### ISSUE THREAD

**Issue by QJPG** [godotengine/godot#35366]
![2020-01-20-12-44-44](https://user-images.githubusercontent.com/53179496/72739947-76e9a680-3b83-11ea-9330-05bdc694b2ca.png)
Win 32 V. 7 
Godot 3.2 rc2

**Comment by clayjohn** [comment]
We're you able to run the engine in version 3.1?

Also, please provide more information about your hardware.

**Comment by FragileBoxGames** [comment]
It works fine in 3.1 but in this version (3.2) is giving this error in the driver / video card!
My pc is Windows 7 32bit 2 gbram

**Comment by clayjohn** [comment]
Hardware means CPU and GPU. Could you provide what CPU you have and what GPU you have?

**Comment by FragileBoxGames** [comment]
processor: AMD E-350 Processor(2CPUs), ~1.6ghz

**Comment by aaronfranke** [comment]
Have you tested if it works on Windows 10 or Linux? Windows 7 is fairly old, and it would help to know if it a driver-specific issue, or an OS-specific issue.

> processor: AMD E-350 Processor(2CPUs), ~1.6ghz

Your CPU is capable of running 64-bit operating systems, I highly recommend you do so.

**Comment by FragileBoxGames** [comment]
Unfortunately only 32 bits and yes I already tested with GLES2 and it worked but when I start using GLES3 it crashes

**Comment by KoBeWi** [comment]
@effectALISSON Can you still reproduce this issue in Godot 3.2.3?

**Comment by QJPG** [comment]
Unfortunately, I ended up losing my old computer along with the project for that version. The problem was possibly the internal graphics card, as it didn't even have an external one. I tested that version on my current computer with Windows 10, and it didn't show any errors.

Thank you for the help; it took me a while to remember this open issue."
