### ISSUE TITLE
Godot 3.2 RC2 still crashes [GLES3]

### ISSUE THREAD

**Issue by Berkru** [godotengine/godot#35370]
**Godot version:**
Godot 3.2 RC2

**OS/device including version:**
Ubuntu 19.10 [kernel v5.4.0]
AMD® Ryzen 5 1600
Radeon 550 Series

**Issue description:**

1. WITHOUT "quality/reflections/high_quality_ggx=false" on project.godot:
. it takes longer to open
. Shaders doesn't look right in editor
. It crashes when hit the play button.
![sss1](https://user-images.githubusercontent.com/49285088/72746793-3cc2d980-3b70-11ea-8673-db7ffd7ca341.png)

2.WITH "quality/reflections/high_quality_ggx=false" on project.godot:
.open the project faster
.Shaders are ok
.Won't Crash
![sss2](https://user-images.githubusercontent.com/49285088/72746894-827fa200-3b70-11ea-9292-693ea582adad.png)

OBS: 
It Runs smoothly on Godot 3.1.2
I previously present this Bug on RC1 #35257 
I know you guys have been working so hard to solve the issues, thank you for that!

**Comment by clayjohn** [comment]
Are you receiving the same error printing as before?

**Comment by Berkru** [comment]
Yes. I still receiving that log. 
This is what I did,
duplicated the project and deleted all .import content ( allowing godot reimport)
It didn't crash but the shader showed all messed 
![sss3](https://user-images.githubusercontent.com/49285088/72749651-de99f480-3b77-11ea-8474-5cb1e4715684.png)
yep. it may be a driver issue. not sure. I'll try to update and try again later.

**Comment by clayjohn** [comment]
The shader issues are definitely a driver issue. I would guess the crash is as well.

**Comment by Berkru** [comment]
Tried Kernel v.5.3 and the latest 5.4.13 with no luck.
It may be related to the driver... but I haven't been having any problem with Blender, krita, 3Dcoat Kdenlive and others software...
I'll keep that line in the project.godot for awhile....

**Comment by Berkru** [comment]
Question @clayjohn :
Would I be able to compile 3.2 with GLES3 module from 3.1.2?

**Comment by clayjohn** [comment]
I think so. As far as I can remember there were no major API changes between 3.1 and 3.2. However, you will re-introduce bugs, and you may run into issues. 

It is likely much better to just use GLES2. The fact that your GPU is having trouble running the radiance computation means it likely will have a lot of problem with any of the features that GLES3 has that GLES2 doesnt (particles, GIProbes).

**Comment by Berkru** [comment]
After updating the driver and reducing radiance size. I can confirm it's fixed.

**Comment by clayjohn** [comment]
@Berkru Wooohoooo that's great news! Enjoy version 3.2 :)
