### ISSUE TITLE
Changing export float to INF, then saving will write `inf.0` to tscn and prevent it from opening

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#35388]
**Godot version:**
3.2 RC 2

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
Setting an `export(float)` through code such as `my_float_value = INF` followed by saving will save the float to the tscn file with a value `inf.0`.

**Steps to reproduce:**
- Open TestScene.tscn in the reproduction project
- Click on TestScene and view Script Variables
- Click on "Make Infinite" boolean thing in order to test the problem
- No modifications will be seen due to #21009 
- Scene -> Save Scene (or Control + S)
- Scene -> Close Scene (or Control + Shift + W)
- Open the scene again
![image](https://user-images.githubusercontent.com/14253836/72764552-49feb900-3bae-11ea-8420-d451cd04cd9a.png)

```
$ cat TestScene.tscn
...
[node name="TestScene" type="Node2D"]
script = ExtResource( 1 )
my_float_value = inf.0
```

**Minimal reproduction project:**
[Test1.zip](https://github.com/godotengine/godot/files/4088527/Test1.zip)

**Comment by tastesliketriangle** [comment]
I was able to reproduce this error. On Windows 7 with a version of godot built from source a couple weeks ago.

**Comment by aaronfranke** [comment]
Can reproduce on Linux (Ubuntu 18.04 64-bit, 3.2 rc2), same error as described in the OP.

Can't reproduce on Windows 10 (3.2 rc2). In the editor it says `1.#IO`, but `1.#INF` is saved into the TSCN file. Still a weird issue, but neither causes the file from failing to load.
