### ISSUE TITLE
MacOS Application Not Responding on First Launch

### ISSUE THREAD

**Issue by toddgibson** [godotengine/godot#35383]
**Godot version:**
3.2 RC 2 (Mono)

**OS/device including version:**
MacOS Catalina 10.15.2

**Issue description:**
When I downloaded the latest RC and launch the first time, after allowing the unsigned app to launch in System Prefs -> Security, Godot just sits running fairly intensively but doesn't launch.  The icon shows "Application Not Responding" and so I have to Force Quit.  After that, it works.

**Steps to reproduce:**
1) Download on macOS
2) Launch Godot, macOS will give warnings
3) Go to System Preferences -> Security and allow the app to run
4) Launch Godot again
5) It's spinning and doing nothing, right click the icon to see "Application Not Responding", click Force Quit.
6) Relaunch Godot again, all is well.

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
Related: #35400.
