### ISSUE TITLE
Crash on scenes changing

### ISSUE THREAD

**Issue by ja-brouil** [godotengine/godot#35386]
**Godot version:** 
3.1.2

**OS/device including version:**
MacOS Mojave, Macbook Pro 2018

**Issue description:**
The debugger seems to lose track of autoload nodes after switching scenes. If you click on such a node, it will crash the game and give you a drivers/unix/net_socket_posix.cpp:199 - Socket error: 54 error. If it's something in my code, I apologize but I can't seem to find out what the issue is. 

**Steps to reproduce:**
Run project, change the scene a few times, and then try and click on the autoloaded node.

**Minimal reproduction project:**
https://github.com/ja-brouil/TBS_GoDot

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(20+ MB is not minimal btw)

**Comment by ja-brouil** [comment]
You can close this. Something was fixed in the update on Godot.
