### ISSUE TITLE
draw_rect is drawn at wrong position. Also size and shape is wrong if filled parapeter is false.

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#35384]
**Godot version:**
3.2 RC 2 Open GLES 3

**OS/device including version:**
Windows 10
Nvidia GTX 1650

**Issue description:**
If filled is set to false, the bottom left pixel appears to be missing, but this is not correct. The size is actually one pixel too wide on both axes. Size and shape works as expected if filled is true. Also all rectangles appear to be drawn at wrong positions. See pictures below.
Related to #32279

Edit: problem is probably related to drawing lines: Drawing a 3 pixel line only shows 2 pixels, omitting the first one. Also horisontal lines are offset 1 pixel down on the y axis. Would probably be a good idea to fix lines first, if rectangles depend on them?

Blue and green are rectangles of 1 by 1 pixel size.
Red and blue are rectangles of 4 by 4 pixel size.
Green and blue have filled = false
Yellow and red have filled = true
![Godot_v3 2-rc2_win64_7h1IAE1juE](https://user-images.githubusercontent.com/15088582/72761752-46365b00-3bdd-11ea-8060-25a02719554e.png)

filled = false drawn at Vector(1,1) - Shows at position (1,2)
![Godot_v3 2-rc2_win64_qL4B1N6vcg](https://user-images.githubusercontent.com/15088582/72762090-9cf06480-3bde-11ea-9bfd-8c3bd4432618.png)

filled = true drawn at Vector(1,1) - Shows at position (2,2)
![Godot_v3 2-rc2_win64_TXjYe5qXlT](https://user-images.githubusercontent.com/15088582/72762098-a4b00900-3bde-11ea-89d7-3a8837a6d99c.png)

**Steps to reproduce:**
Draw a rect with filled, and another without filled at the same size. Compare.

**Minimal reproduction project:**
[Draw_rect.zip](https://github.com/godotengine/godot/files/4088225/Draw_rect.zip)

**Comment by sszigeti** [comment]
Getting the same missing pixels when tried `draw_line` calls for my rectangles.

(Used a NinePatchRect instead as speed wasn't as issue for my case.)

**Comment by mrimvo** [comment]
I think I got the same issue in Godot 4.0 Beta 4.

![image](https://user-images.githubusercontent.com/6030346/202667077-fd2996c8-e1a5-4f7b-8447-716e158f15e5.png)

The corner pieces of the rectangle are missing, iff `rect.x<0`.

```draw_rect(rect, Color.LIME_GREEN, false, 6)```

**Comment by dalexeev** [comment]
Will be fixed by a combination of the following PRs:

* #69851
* #41239
* godotengine/godot-docs#6455
