### ISSUE TITLE
Exporting APK in Ubuntu Linux. 

### ISSUE THREAD

**Issue by Oussama-dev** [godotengine/godot#3539]
Hello,
I am trying to export my game to apk in Ubuntu but i can't find the jarsigner binary,
when i use the` jarsigner ` command in the terminal i got this:
`Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Usage: jarsigner [options] jar-file alias
       jarsigner -verify [options] jar-file [alias...]`

i tried to use it for the export but the apk doesn't run on my phone.

**Comment by freemanfromgodotengine** [comment]
You need JDK 6.
Also system needs to know where you java is installed, so you need for example if you use oracles jdk6:
export JAVA_HOME=/usr/lib/jvm/java-6-oracle

In this case the jarsigner should be located for at /usr/lib/jvm/java-6-oracle/bin . 
You should be able to also run it from that directory.

**Comment by akien-mga** [comment]
> You need JDK 6.

As far as I know OpenJDK 8 works fine too.

**Comment by volzhs** [comment]
I have used OpenJDK 7 recently, and it's fine.

**Comment by freemanfromgodotengine** [comment]
I used SDK 7 before, but wanted to be save when helping and I remember that official wiki says about SDK 6.

**Comment by akien-mga** [comment]
@godotengine/documentation The wiki needs to be fixed indeed:
- http://godotengine.org/projects/godot-engine/wiki/Exporting_for_Android (mentions JDK 6 and not that other versions work too)
- http://godotengine.org/projects/godot-engine/wiki/Compiling_for_Android (mentions JDK6 in the Troubleshooting section)

**Comment by Oussama-dev** [comment]
i am using OpenJDK 8, i will try OpenJDK6 and i will see.

**Comment by akien-mga** [comment]
IIRC I fixed this in the documentation.

**Comment by akien-mga** [comment]
@Oussama-dev About your last comment, it seems that your keystore is invalid, you might have to generate a new one.
