### ISSUE TITLE
Range class's 'changed' signal passes an argument in 3.1, when docs says it doesn't.

### ISSUE THREAD

**Issue by Neerti** [godotengine/godot#35395]
In [this section](https://github.com/godotengine/godot-docs/blob/3.1/classes/class_range.rst#signals) of the documentation for 3.1, the ``changed`` signal for the ``Range`` class says that it does not pass any arguments to the method being called, however that is not actually true in 3.1, where it will pass an integer, presumably used to determine which of the four things the ``Range`` object had changed.

In the current (as of this issue being made) master code for Godot, the documentation does appear to be accurate, but the 3.1 version has it also say it doesn't pass anything, when it actually does.

I found this out when I was having a lot of trouble connecting the ``changed`` signal to a method with no parameters. I checked the source code, and it certainly does appear that there is a difference to the signal between [3.1](https://github.com/godotengine/godot/blob/3.1/scene/gui/range.cpp#L66) and [master](https://github.com/godotengine/godot/blob/master/scene/gui/range.cpp#L66).

It's not the worst thing to happen, since eventually 3.2 will come out and it'll be correct, but it might still cause some confusion until then, and for anyone who might stay on 3.1 for whatever reason.

**Comment by akien-mga** [comment]
Fixed by #35396.
