### ISSUE TITLE
Mesh/Skeleton does not return to original pose when unplay the SkeletonIK inside editor

### ISSUE THREAD

**Issue by bunianox** [godotengine/godot#35409]
**Godot version:** Godot 3.2 RC 2

**OS/device including version:** Windows 10

**Issue description:** Thanks for the fix for #35035.

The mesh/skeleton does not return to its original pose when unplay the SkeletonIK inside editor. It does reset when you close and reopen the scene.
![bug](https://user-images.githubusercontent.com/53292215/72837560-9db1f500-3cc9-11ea-90e9-7d3b8f12ca55.gif)
 
This tested in v3.2 beta 6, before the fix
![expected](https://user-images.githubusercontent.com/53292215/72837763-fed9c880-3cc9-11ea-9eb0-215bd22a10f7.gif)

**Steps to reproduce:**
Open the project, play the SkeletonIKLeft inside the editor, move around the TargetRight, unplay the SkeletonIKLeft

**Minimal reproduction project:**
[ik-test.zip](https://github.com/godotengine/godot/files/4093369/ik-test.zip)

**Comment by ericrybick** [comment]
Argh, my fault. I'm on it.
