### ISSUE TITLE
Projects can't be edited since Godot 3.2 RC 1 on macOS Catalina

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#35400]
**Godot version:** Godot 3.2 RC2

**OS/device including version:** macOS Catalina 10.15.2 / MacBookPro11,1

**Issue description:** Project created with Godot 3.1.2 Stable doesn't open in Godot 3.2 RC2

**Steps to reproduce:** Tested only on one particular 2D project, with 1000+ lines of code.

**Minimal reproduction project:** N/A

**Comment by akien-mga** [comment]
Good to know, but there's nothing for us to act upon here.

Is there any error? Does it crash? Does the editor run fine on a simple project?

**Comment by frewq** [comment]
Hi, I had tested these two  projects in 3.1.2 and they both work, but in 3.2 rc1 and rc2 they freeze Godot, it can't get into the editor.

https://github.com/akselakon/Cannon-Bros
https://github.com/ikicapitan/Frogger

**Comment by akien-mga** [comment]
CC @bruvzg @timothyqiu @clayjohn

**Comment by akien-mga** [comment]
@frewq Did you try with older beta versions for 3.2? It would help pinpoint when the regression arised.
https://downloads.tuxfamily.org/godotengine/3.2/

**Comment by drmar** [comment]
I have an updateI deleted Godot 3.2 RC 2 and then redownloaded it and installed it. Now it seems to work fine, can't figure out why or what I did differently.

All I did was to duplicate my Godot 3.1.2 project and renamed it in FInder (not in Godot Editor), then I tried to open it with Godot 3.2 RC 2. Maybe naming had something to do with it?

First time I tried it, when I pressed the Edit button, it tried to open the project, but then it kept returning to the Main Window.

I will keep testing Godot 3.2 RC 2 and report any other problems that I might encounter.

**Comment by bruvzg** [comment]
macOS 10.15.2 - both aforementioned projects work fine in d4ac0ca153 master and RC2 (tested editing and running projects form Project Manager, command line and '.godot' file association in Finder).

**Comment by bruvzg** [comment]
@frewq try opening projects with the GLES2 renderer (`{GODOT_PATH}/Godot.app/Contents/MacOS/Godot -e --path {PROJECT_PATH} --video-driver GLES2`), and get crash reports from `Applications > Utilities > Console.app > Crash Reports` (look for "Godot" and crash time, reports might appear a few minutes after the crash).

**Comment by frewq** [comment]
> @frewq Did you try with older beta versions for 3.2? It would help pinpoint when the regression arised.
> https://downloads.tuxfamily.org/godotengine/3.2/
> 
> Also related: #35383.

They are working fine until beta6. The problems starts in rc1

**Comment by frewq** [comment]
> @frewq try opening projects with the GLES2 renderer (`{GODOT_PATH}/Godot.app/Contents/MacOS/Godot -e --path {PROJECT_PATH} --video-driver GLES2`), and get crash reports from `Applications > Utilities > Console.app > Crash Reports` (look for "Godot" and crash time, reports might appear a few minutes after the crash).

I'm going to try it

**Comment by frewq** [comment]
Ok, these are the logs, i'm using Windows:



Error	21/01/2020 11:26:19 a. m.	Application Hang	1002	(101)
Información	21/01/2020 11:26:18 a. m.	Windows Error Reporting	1001	Ninguno
Información	21/01/2020 11:26:03 a. m.	Windows Error Reporting	1001	Ninguno
Información	21/01/2020 11:26:03 a. m.	Windows Error Reporting	1001	Ninguno

--------------------------------------------------------------------------

Nombre de registro:Application
Origen:        Application Hang
Fecha:         21/01/2020 11:26:19 a. m.
Id. del evento:1002
Categoría de la tarea:(101)
Nivel:         Error
Palabras clave:Clásico
Usuario:       No disponible
Equipo:        DESKTOP-1886BPV
Descripción:
El programa Godot_v3.2-rc1_win64.exe (versión 3.2.0.0) dejó de interactuar con Windows y se cerró. Para ver si hay más información disponible sobre el problema, comprueba el historial de problemas en el panel de control de seguridad y mantenimiento.
 Id. de proceso: 884
 Hora de Inicio: 01d5d066af4125cd
 Hora de finalización: 5
 Ruta de la aplicación: C:\Godot Betas\Godot_v3.2-rc1_win64.exe
 Id. de informe: f969626d-2a18-47e7-9ff9-e3b71e92fab2
 Nombre completo del paquete con errores: 
 Id. de la aplicación relativa al paquete con errores: 
 Tipo de bloqueo: Unknown

XML de evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Level>2</Level>
    <Task>101</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-01-21T14:26:19.796086700Z" />
    <EventRecordID>8672</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-1886BPV</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Godot_v3.2-rc1_win64.exe</Data>
    <Data>3.2.0.0</Data>
    <Data>884</Data>
    <Data>01d5d066af4125cd</Data>
    <Data>5</Data>
    <Data>C:\Godot Betas\Godot_v3.2-rc1_win64.exe</Data>
    <Data>f969626d-2a18-47e7-9ff9-e3b71e92fab2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>Unknown</Data>
    <Binary>55006E006B006E006F0077006E0000000000</Binary>
  </EventData>
</Event>

Nombre de registro:Application
Origen:        Windows Error Reporting
Fecha:         21/01/2020 11:26:18 a. m.
Id. del evento:1001
Categoría de la tarea:Ninguno
Nivel:         Información
Palabras clave:Clásico
Usuario:       No disponible
Equipo:        DESKTOP-1886BPV
Descripción:
Depósito con errores 2074935249921374362, tipo 5
Nombre de evento: AppHangB1
Respuesta: No disponible
Identificador de archivo .cab: 0

Firma del problema:
P1: Godot_v3.2-rc1_win64.exe
P2: 3.2.0.0
P3: 00000000
P4: 1664
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Archivos adjuntos:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BE4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C14.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C25.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C74.tmp.txt
\\?\C:\Users\Fabi8\AppData\Local\Temp\WER32AD.tmp.appcompat.txt

Es posible que estos archivos estén disponibles aquí:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Godot_v3.2-rc1_w_73b592e169856a07919f6aabbc884d74b9fe5_0c64aa29_2d71b270-87d8-4350-b2d8-d3b9c9ecf5fe

Símbolo de análisis: 
Nueva búsqueda de una solución: 0
Id. de informe: f969626d-2a18-47e7-9ff9-e3b71e92fab2
Estado del informe: 268435456
Depósito con algoritmo hash: cbb8bc23a0fe653cfccba69dc77ff89a
GUID de archivo .cab: 0
XML de evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-01-21T14:26:18.710851700Z" />
    <EventRecordID>8671</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-1886BPV</Computer>
    <Security />
  </System>
  <EventData>
    <Data>2074935249921374362</Data>
    <Data>5</Data>
    <Data>AppHangB1</Data>
    <Data>No disponible</Data>
    <Data>0</Data>
    <Data>Godot_v3.2-rc1_win64.exe</Data>
    <Data>3.2.0.0</Data>
    <Data>00000000</Data>
    <Data>1664</Data>
    <Data>134217728</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2BE4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C14.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C25.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2C74.tmp.txt
\\?\C:\Users\Fabi8\AppData\Local\Temp\WER32AD.tmp.appcompat.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Godot_v3.2-rc1_w_73b592e169856a07919f6aabbc884d74b9fe5_0c64aa29_2d71b270-87d8-4350-b2d8-d3b9c9ecf5fe</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>f969626d-2a18-47e7-9ff9-e3b71e92fab2</Data>
    <Data>268435456</Data>
    <Data>cbb8bc23a0fe653cfccba69dc77ff89a</Data>
    <Data>0</Data>
  </EventData>
</Event>

Nombre de registro:Application
Origen:        Windows Error Reporting
Fecha:         21/01/2020 11:26:03 a. m.
Id. del evento:1001
Categoría de la tarea:Ninguno
Nivel:         Información
Palabras clave:Clásico
Usuario:       No disponible
Equipo:        DESKTOP-1886BPV
Descripción:
Depósito con errores , tipo 0
Nombre de evento: LiveKernelEvent
Respuesta: No disponible
Identificador de archivo .cab: 0

Firma del problema:
P1: 141
P2: ffff900f230e8010
P3: fffff8021358cf38
P4: 0
P5: 884
P6: 10_0_18363
P7: 0_0
P8: 768_1
P9: 
P10: 

Archivos adjuntos:
\\?\C:\Windows\LiveKernelReports\WATCHDOG\WATCHDOG-20200121-1125.dmp
\\?\C:\Windows\TEMP\WER-403956046-0.sysdata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD81.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDFF.tmp.txt

Es posible que estos archivos estén disponibles aquí:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Kernel_141_be6692984a33b0db682480f3c8ffba1f87c815c1_00000000_cab_b5b0f88f-aedd-443f-955a-6f09fafec457

Símbolo de análisis: 
Nueva búsqueda de una solución: 0
Id. de informe: b5b0f88f-aedd-443f-955a-6f09fafec457
Estado del informe: 2049
Depósito con algoritmo hash: 
GUID de archivo .cab: 0
XML de evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-01-21T14:26:03.638326900Z" />
    <EventRecordID>8670</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-1886BPV</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>LiveKernelEvent</Data>
    <Data>No disponible</Data>
    <Data>0</Data>
    <Data>141</Data>
    <Data>ffff900f230e8010</Data>
    <Data>fffff8021358cf38</Data>
    <Data>0</Data>
    <Data>884</Data>
    <Data>10_0_18363</Data>
    <Data>0_0</Data>
    <Data>768_1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\Windows\LiveKernelReports\WATCHDOG\WATCHDOG-20200121-1125.dmp
\\?\C:\Windows\TEMP\WER-403956046-0.sysdata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD81.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDFF.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Kernel_141_be6692984a33b0db682480f3c8ffba1f87c815c1_00000000_cab_b5b0f88f-aedd-443f-955a-6f09fafec457</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>b5b0f88f-aedd-443f-955a-6f09fafec457</Data>
    <Data>2049</Data>
    <Data>
    </Data>
    <Data>0</Data>
  </EventData>
</Event>

Nombre de registro:Application
Origen:        Windows Error Reporting
Fecha:         21/01/2020 11:26:03 a. m.
Id. del evento:1001
Categoría de la tarea:Ninguno
Nivel:         Información
Palabras clave:Clásico
Usuario:       No disponible
Equipo:        DESKTOP-1886BPV
Descripción:
Depósito con errores , tipo 0
Nombre de evento: LiveKernelEvent
Respuesta: No disponible
Identificador de archivo .cab: 0

Firma del problema:
P1: 141
P2: ffff900f230e8010
P3: fffff8021358cf38
P4: 0
P5: 884
P6: 10_0_18363
P7: 0_0
P8: 768_1
P9: 
P10: 

Archivos adjuntos:
\\?\C:\Windows\LiveKernelReports\WATCHDOG\WATCHDOG-20200121-1125.dmp
\\?\C:\Windows\TEMP\WER-403956046-0.sysdata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD81.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDFF.tmp.txt

Es posible que estos archivos estén disponibles aquí:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Kernel_141_be6692984a33b0db682480f3c8ffba1f87c815c1_00000000_b5b0f88f-aedd-443f-955a-6f09fafec457

Símbolo de análisis: 
Nueva búsqueda de una solución: 0
Id. de informe: b5b0f88f-aedd-443f-955a-6f09fafec457
Estado del informe: 4
Depósito con algoritmo hash: 
GUID de archivo .cab: 0
XML de evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-01-21T14:26:03.428968300Z" />
    <EventRecordID>8669</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-1886BPV</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>LiveKernelEvent</Data>
    <Data>No disponible</Data>
    <Data>0</Data>
    <Data>141</Data>
    <Data>ffff900f230e8010</Data>
    <Data>fffff8021358cf38</Data>
    <Data>0</Data>
    <Data>884</Data>
    <Data>10_0_18363</Data>
    <Data>0_0</Data>
    <Data>768_1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\Windows\LiveKernelReports\WATCHDOG\WATCHDOG-20200121-1125.dmp
\\?\C:\Windows\TEMP\WER-403956046-0.sysdata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD81.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDB0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDFF.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Kernel_141_be6692984a33b0db682480f3c8ffba1f87c815c1_00000000_b5b0f88f-aedd-443f-955a-6f09fafec457</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>b5b0f88f-aedd-443f-955a-6f09fafec457</Data>
    <Data>4</Data>
    <Data>
    </Data>
    <Data>0</Data>
  </EventData>
</Event>

**Comment by akien-mga** [comment]
@frewq It's unclear whether your issue would be the same as @drmar (which is on macOS).

Could you test 3.2 RC 2 (which fixes a hang problem from RC 1 which seems similar to what your logs mention), and if it still fails, open a dedicated issue with details on your Windows version, hardware, drivers, etc.?

**Comment by frewq** [comment]
Yes, I also tested in RC 2. But, If I do what bruvzg says, at least it enters to the editor in RC 1 and 2. But still hangs when I run it.

I'm going to open an issue later. thanks!

**Comment by timothyqiu** [comment]
macOS Catalina 10.15.2 here, I can't reproduce the freeze. (I deleted the Data/Settings folder and created several new projects in 3.1.2, including unicode named ones.)

I also tried the Cannon-Bros and Forgger project, seems OK on macOS.

**Comment by clayjohn** [comment]
@frewq can you post your hardware specs here so we can see if that is part of the issue?

**Comment by frewq** [comment]
Ok, I think that I found a solution.

1. I do what @bruvzg says:
try opening projects with the GLES2 renderer `({GODOT_PATH}/Godot.app/Contents/MacOS/Godot -e --path {PROJECT_PATH} --video-driver GLES2)`

2. Once inside the project go to:
Project Setting --> Rendering --> Quality --> set 'Driver Name' to 'GLES2'

With this the project runs perfect.

**Comment by frewq** [comment]
> @frewq can you post your hardware specs here so we can see if that is part of the issue?

CPU: Intel 2500K
GPU: AMD Radeon HD 6670
OS: Windows 10 64 bits 1909

**Comment by clayjohn** [comment]
Looks like this issue can be closed then. The original Mac specific issue seems to have solved itself and/or cannot be reproduced.

@frewq your issue is unrelated to this issue. You are experiencing https://github.com/godotengine/godot/issues/35366, this is caused by older graphics cards having trouble running the computations necessary to set up 3D scenes in GLES3. The proper solution is indeed to use GLES2. :)
