### ISSUE TITLE
ScrollBar smooth scrolling not exposed to GDScript

### ISSUE THREAD

**Issue by devvoid** [godotengine/godot#35405]
**Godot version:**
3.2 RC2

**OS/device including version:**
Linux Mint 19

**Issue description:**
ScrollBar has a property for smooth scrolling, but it isn't exposed to GDScript.

**Steps to reproduce:**
- Create a VScrollBar or HScrollBar
- Observe that smooth scrolling is not exposed.

**Minimal reproduction project:**
None is needed.

**Comment by Calinou** [comment]
Related to #12965.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/12965 (same cause).
