### ISSUE TITLE
Videoplayer.get_video_texture ( ) doesn't return the current frame as a texture

### ISSUE THREAD

**Issue by FrazzleTime** [godotengine/godot#35410]
**Godot version:**
3.1.2 stable
**OS/device including version:**
w10 64 bit
**Issue description:**
The docs state that get_video_texture()  returns the current frame as a texture.
 but  it returns the whole video as a texture instead.

**Steps to reproduce:**
create VideoPlayer
create TextureButton
$TextureButton.set_normal_texture ($VideoPlayer.get_video_texture())

**Comment by timothyqiu** [comment]
It's returning the texture, but the texture will be updated by the player when playing. (The texture button's texture is referencing the same object as the video player's.)

You may want something like this:

```gdscript
var image = player.get_video_texture().get_data()
var texture = ImageTexture.new()
texture.create_from_image(image)
$TextureButton.set_normal_texture(texture)
```

**Comment by FrazzleTime** [comment]
Very nice that worked, thank you for the clarification.

**Comment by trekfan42** [comment]
> It's returning the texture, but the texture will be updated by the video player when playing. The texture button's texture updates because it is referencing the same object as the video player's.
> 
> You may want something like this:
> 
> ```gdscript
> var image = player.get_video_texture().get_data()
> var texture = ImageTexture.new()
> texture.create_from_image(image)
> $TextureButton.set_normal_texture(texture)
> ```

get_video_texture() is returning an image texture already, and when i try to load it into a texture recot or sprite, it does'nt error, but it also doesn't display... 

finding myself frustrated that the imagetexture has far less methods to work with, so im struggling with handling it
