### ISSUE TITLE
Crash when selecting multiple TextureFrames with SHIFT pressed on MAC OSX.

### ISSUE THREAD

**Issue by lizistorm** [godotengine/godot#3541]
Maybe other node will crash too with SHIFT pressed. I just tried TextureFrame and HBoxContainer in my case.

**Comment by reduz** [comment]
make example scene that crashes please

**Comment by lizistorm** [comment]
This is the crash scene:
[CrashScene.zip](https://github.com/godotengine/godot/files/114138/CrashScene.zip)

**Comment by trollworkout** [comment]
@lizistorm 
for me it works fine both on the beta from the site and my own godot build i compiled today.

**Comment by trollworkout** [comment]
@lizistorm  since you have osx could you test out this problem as well  https://github.com/godotengine/godot/issues/3552

**Comment by lizistorm** [comment]
@trollworkout I tried your problem, the SHIFT and CONTROL key not work.

Maybe this issue is the SHIFT key not trigger the SHIFT event.

**Comment by trollworkout** [comment]
@lizistorm  so they don't work for you either?

**Comment by lizistorm** [comment]
@trollworkout Yes I have the same problem as yours on OSX.

**Comment by batiste** [comment]
I think I have a similar problem but simply with 2 sprites (godot v2.0.beta.custom_build) I made a video here:

https://www.youtube.com/watch?v=vg_98ZKzfOQ&feature=youtu.be

If it helps I can submit the full stack trace if necessary.

**Comment by batiste** [comment]
More complete stack if it helps:

`Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x9074058a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x92c45448 pthread_kill + 101
2   libsystem_c.dylib             	0x94c7dc34 abort + 156
3   libsystem_c.dylib             	0x94c46009 __assert_rtn + 393
4   libunwind.dylib               	0x91d62ebc _Unwind_Resume + 121
5   org.godotengine.godot         	0x0000cef1 InputDefault::parse_input_event(InputEvent const&) + 1201
6   org.godotengine.godot         	0x00002deb -[GodotContentView mouseDown:] + 363
7   com.apple.AppKit              	0x9a83a5b7 -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6266
8   com.apple.AppKit              	0x9a83c0ea -[NSWindow _reallySendEvent:isDelayedEvent:] + 2303
9   com.apple.AppKit              	0x9a0df927 -[NSWindow sendEvent:] + 567
10  com.apple.AppKit              	0x9a0db942 -[NSApplication sendEvent:] + 2919
11  org.godotengine.godot         	0x000027d4 -[GodotApplication sendEvent:] + 148
12  org.godotengine.godot         	0x000069e8 OS_OSX::run() + 200
13  org.godotengine.godot         	0x0000848d main + 365
14  org.godotengine.godot         	0x000026f5 start + 53
`

**Comment by batiste** [comment]
This still does happen for me with the latest 2.0 version.

Weirdly enough when I compile the software by hand, the crash doesn't happen. Anything I can do to help?

**Comment by lizistorm** [comment]
Yes it still happens with 2.0 STABLE and will crash to click any node with SHIFT pressed.

**Comment by akien-mga** [comment]
> Weirdly enough when I compile the software by hand, the crash doesn't happen.

Thanks, that's quite interesting. It might indicate that something is wrong due to the official binaries being cross-compiled from Linux with OSXCross.

Any idea @punto-?

**Comment by bojidar-bg** [comment]
Any updates? As far as I remember we aren't using OSXCross lately, but I might be wrong as well.

**Comment by Keyaku** [comment]
I don't think I understand the issue (but that's just because I wasn't around when Godot was in 2.0 beta): is the crash related to selecting multiple nodes (with Shift)?

If so, it doesn't crash on my end. Using 2.2-legacy.

**Comment by bojidar-bg** [comment]
Ok, closing then as fixed (somehow). If anyone runs into it again, we might reopen.
