### ISSUE TITLE
Godot 2.0 Beta will popup an exception window when closing  editor on MAC OSX

### ISSUE THREAD

**Issue by lizistorm** [godotengine/godot#3542]
Also popup the error after open a project by project manager and close played game window.

Here is the pop up error:
![image](https://cloud.githubusercontent.com/assets/2263255/12723352/fec5a4fc-c943-11e5-82f1-3bc74c130205.png)

**Comment by akien-mga** [comment]
Thanks, that seems to be a duplicate of #3498 and was fixed recently in the master branch, so it should work in the next beta/RC.

**Comment by punto-** [comment]
Is this from the latest on github? I think it's fixed.

**Comment by lizistorm** [comment]
Oh sorry! I should checkout fixed issues first.
