### ISSUE TITLE
Animation buttons in the canvas item editor are taking up too much space

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#35420]
**Godot version:** Godot 3.2 master (d4ac0ca15397932960403d595f2e08f926411471)

**OS/device including version:** Manjaro Linux 18.1.5

**Issue description:**
Godot 3.2 now have a new "Auto insert keys" feature but these animation buttons are taking up too much space. When I select a Sprite node, the docks on the right are "compacted".

![2020-01-21 18-48-51](https://user-images.githubusercontent.com/10428035/72848677-db8c2a80-3c83-11ea-9484-c833929e473b.gif)

I have a partial solution for this (#35421) but I think the best solution would be moving these buttons to the Animation dock. Example:

![image](https://user-images.githubusercontent.com/10428035/72849013-9ae0e100-3c84-11ea-8cce-62d9de898067.png)

**Steps to reproduce:**
Try the editor in a "medium" resolution (mine is 720p).
Add a Sprite (no texture required) and an AnimationPlayer node.
Select the Sprite and try to toggle the Animation dock.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
The toolbar didn't change since the report, so it's likely still valid.

**Comment by pycbouh** [comment]
We seem to be collecting all such issues under https://github.com/godotengine/godot/issues/31133, so I'll close this one.
