### ISSUE TITLE
VR controller misbehavior

### ISSUE THREAD

**Issue by BenMcLean** [godotengine/godot#35427]
**Godot version:** 3.2 Beta 1 (but relevant areas of code haven't changed in more recent Godot AFAIK)

**OS/device including version:** Windows 10 and Oculus Quest

**Issue description:**

If you start with the left controller not found, then polling the left controller's joystick returns the value from the right controller's joystick.

This happens both on native Oculus Quest apps built with the Oculus Mobile VR Plugin and on Oculus Link via the Open VR plugin.

**Steps to reproduce:**

Take the battery out of your left controller, then start the Godot app. The right controller joystick value gets returned when polling the left controller joystick! (using the `GetJoystickAxis` method)

Instead, I would expect a joystick that isn't there should either return 0 when polled or that there should be some way to indicate that the VR controller is not present. Maybe throw an exception?

Mux213 on Discord theorized that the issue is with this line here: https://github.com/godotengine/godot/blob/master/scene/3d/arvr_nodes.cpp#L298

Perhaps it should return -1 instead of 0?

**Comment by BastiaanOlij** [comment]
Same issue on Index controllers
