### ISSUE TITLE
Godot 3.1.2 ConcavePolygonShape is not accurate

### ISSUE THREAD

**Issue by RichardR01** [godotengine/godot#35426]
**Godot version:**
3.1.2

**OS/device including version:**
Windows 10 v1909

**Issue description:**
I decided to bring in a mesh obj from Blender instead of using a grid matrix. I turned on debug option, "Show collision shapes" and I noticed the left side is poking out the geometry. The right side is just fine. I ran a test using a Orthographic camera facing directly down so I could see how the collision was working with the mesh. It is as it shows from the collision shape. It is off, just outside the mesh on the left side. I have included the mesh object as well as a snapshot during run time.
[outerwall.zip](https://github.com/godotengine/godot/files/4095256/outerwall.zip)

![godot_collision_concavepoly](https://user-images.githubusercontent.com/46553425/72865580-3ece8a80-3c8d-11ea-958d-5ad3905fe963.jpg)

**Comment by Calinou** [comment]
@RichardR01 Please upload a complete minimal reproduction project to make this easier to troubleshoot. Having just the `.glb` file doesn't suffice here.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
