### ISSUE TITLE
AutoLoad, Drag and Drop

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3543]
With many Nodes in Autoload it takes more and more time to move a new Node from top to bottom. Maybe a drag and drop feature will speed it up some day...

**Comment by captainwasabi** [comment]
I see the bug where this was supposed to be fixed.  And I guess you see the arrows, but I don't see the arrows.

**Comment by reduz** [comment]
old version of godot?

**Comment by captainwasabi** [comment]
Ah, you didn't see my additional comment:

Edit: ok, I downloaded the nightly build and I seen them. I don't see them in the build I made when the 2.0 beta came out. I'll update from git and rebuild when I get home.
