### ISSUE TITLE
macOS: editor window opens on a different screen than the current one

### ISSUE THREAD

**Issue by jacopofar** [godotengine/godot#35434]
Godot version: 3.2rc2

OS/device including version: macOS Catalina

Issue description: If I open the editor on the screen where I intend to use the editor the resolution of the project selection window is correct (it doesn't adapt if I move it to another screen but that is already known from #5688 ). But after the initial window when I open a project the editor window appears on a different screen, in my case the retina one, and then if I move the window to the intended screen the resolution is wrong.

Steps to reproduce: start Godot while the focus is on an external monitor, the initial project choice window opens there and with the correct resolution. Choose a project and the editor will open in a different monitor.

Minimal reproduction project: any project

**Comment by KoBeWi** [comment]
This should've been fixed in 3.2.3. Please comment if you can still reproduce.

**Comment by Calinou** [comment]
> This should've been fixed in 3.2.3. Please comment if you can still reproduce.

For the record, this was likely fixed by https://github.com/godotengine/godot/pull/40084.
