### ISSUE TITLE
Godot 3.2 rc2 Mono Crashes with GLES3 on Android

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#35443]
**3.2 rc2 mono**

**Windows 10 /  Testing on Android**

**the same game with the same scripts works fine in GLES2 and crashes with GLES3**

**I tried to run my game on android with GLES2 it works fine but in GLES3 it crashes right after the splashscreen**
PS : the device supports GLES3

**Comment by Calinou** [comment]
> PS : the device supports GLES3

Which device is it exactly? Many devices claim to support GLES3 but do so very poorly.

Still, we recommend always using GLES2 on Android due to poor support across devices.

**Comment by MrZak-dev** [comment]
The only thing i get by running `adb -d logcat godot:V mono:V *:S` is
`01-22 19:47:15.270 24982 25002 I godot   : Godot Engine v3.2.rc2.mono.official - https://godotengine.org
01-22 19:47:15.281 24982 25002 I godot   : OpenGL ES 3.0 Renderer: Adreno (TM) 505
01-22 19:47:15.367 24982 25002 I godot   :
01-22 19:47:15.730 24982 25002 I godot   : Mono: Logfile is: /data/data/com.example.spacerider/files/mono/mono_logs/2020_01_22 19.47.15 (24982).txt`

**Comment by MadaraZ** [comment]
@MrZak-dev why do you need gles3? -_-
use only gles2 everything works great for old android

**Comment by MadaraZ** [comment]
Godot 4.0 GLES3 completely removed will replace Vulkan API
