### ISSUE TITLE
LineEdit error when move with mouse over area

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3544]
Move the mouse over the LineEdit input area and you get a lot of these
```
ERROR: emit_signal: Error calling method from signal 'input_event': 'Area2D(pipe.gd)::_on_InputArea2D_input_event': Method not found.
   At: core/object.cpp:1210.
```

**Comment by nopeson** [comment]
Do you have a script called pipe.gd? It seems, that you connect a signal to a method that doesn't exists there.
like
`lineedit.connect("input_event", self, "foo")`

**Comment by AlexHolly** [comment]
I think you are right, I looked at two projects and both had the same issue.
I did some refactoring in both project so the problem should be there. I close it for now maybe I find the issue. Thanks.
