### ISSUE TITLE
Cannot change the case when renaming files/folders (MacOS)

### ISSUE THREAD

**Issue by paulineribeyre** [godotengine/godot#35457]
**Godot version:** 3.1.2

**OS/device including version:** MacOS 10.13.6

**Issue description:** When renaming a file or a folder in `res://` and only changing the case, Godot displays a warning "A file or folder with this name already exists" and doesn't rename. The check for files/folders with the same name should be case sensitive.

**Steps to reproduce:** Rename a file or folder name and change the case of one or more letters

**Comment by Calinou** [comment]
See also #19592.

**Comment by paulineribeyre** [comment]
@Calinou thanks for checking - I can rename files and change the case fine outside of Godot. I don't think it's a duplicate of #19592, which seems to be about an unexpected error on Windows 10 only, while this one is about a warning message that's displayed on purpose

**Comment by akien-mga** [comment]
@paulineribeyre Do you have macOS installed with a case-sensitive or case-insensitive FileSystem?
If the latter, that would indeed be the same issue as #19592, but its scope should be extended to also include macOS with case-insensitive filesystems.

**Comment by paulineribeyre** [comment]
@Calinou @akien-mga You're right, my system is case insensitive - The issues could be related but the warning message differs from the error reported in #19592
