### ISSUE TITLE
Editor display bugs on MacOS

### ISSUE THREAD

**Issue by benbishopnz** [godotengine/godot#35456]
**Godot version:**
First witnessed the bug on 3.2.beta2, upgraded to 3.2.rc2 and problem persists.

**OS/device including version:**
MacOS 10.14.6 Mohave

**Issue description:**
When opening my project, the editor loads and the display is almost always broken.
Here are some salient points:

- My project is somewhat large, it takes 10-20 seconds to load initially before the display goes wacky
- It doesn't happen on a fresh project
- Adjusting the window size/layout doesn't help
- I have the 3D view and nodes turned off in the editor, but I reset that to the default and it still occurred
- It's also inconsistent in the display behaviour, the below screenshot is an extreme example. Usually I can see the code window, but it often displays for some files and not for others, the debugging pane is almost always invisible. Node editor is usually unusable.

![macos_godot_display_bug](https://user-images.githubusercontent.com/1631516/72951052-06948c80-3df2-11ea-9657-fe585104ed54.png)

**Steps to reproduce:**
Open my specific project :(

If anybody has seen anything like this or has some ideas on what I could try then I would be glad to help.

**Comment by benbishopnz** [comment]
Also I should mention that I haven't seen this behaviour with the same project on Windows.

**Comment by benbishopnz** [comment]
I figured out what was causing this. I had 100+ scripts open in the pane at the left.
After going to File -> Close All and then quitting and reopening Godot it loaded instantly and everything looked perfect again.

**Comment by Calinou** [comment]
This sounds very difficult to reproduce. If anyone else manages to reproduce this by opening a large number of scripts in the editor, please comment. Otherwise, I'll have to close this issue.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by benbishopnz** [comment]
FWIW I just tried opening over 100 scripts, closed and reopened the editor and it loaded fine. Same Mac laptop as I was using previously (new OS version now though.)

**Comment by akien-mga** [comment]
Thanks, closing then.
