### ISSUE TITLE
TileSet.tile_set_shapes() doesn't work in a TileSet already assigned to a TileMap.

### ISSUE THREAD

**Issue by qarlosh** [godotengine/godot#35466]
**Godot version:**
3.2beta1

**OS/device including version:**
Linux Mint 19.1

**Issue description:**
When calling `TileSet.tile_set_shapes()` the tilemap collision information is not updated. You must make a call to `TileSet.emit_signal("changed")` to make it work.
Taking a look to Godot source, I see that other functions like `TileSet.tile_set_shape()` make a call to `emit_changed()` at the end, but `TileSet.tile_set_shapes()` doesn't. Probably adding it should fix it.
**Steps to reproduce:**
Make a call to `TileSet.tile_set_shapes()` on a `TileSet` assigned to a `TileMap`. The TileMap collision doesn't get updated.

**Comment by YeldhamDev** [comment]
It appears that it already does:
https://github.com/godotengine/godot/blob/e7e8318546cef3aa482d71c5b0ddd5a664e241eb/scene/resources/tile_set.cpp#L954-L962
Could you test that in the newest release candidate?

**Comment by qarlosh** [comment]
I'm not sure, but I think that the function called when using GDScript is `_tile_set_shapes()` (with leading underscore), and this function doesn't call `emit_changed()`

**Comment by YeldhamDev** [comment]
Oh, indeed, I just reproduced the bug. Will try to apply the fix.

**Comment by qarlosh** [comment]
Thank you!
