### ISSUE TITLE
3.2 RC2 Regression - PathFollow2D unit offset can no longer support looping for anything that doesn't start at 0.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#35485]
**Godot version:**
3.2 RC2

**OS/device including version:**
Win10 64-bit

**Issue description:**

When trying to create an animation set of looping PathFollow2Ds at different spacings using the Unit Offset, one has to keyframe first say 0.2, then to get it to make it move the whole path, the ending keyframe would have to be 1.2.

This is no longer possible to do in 3.2, because it truncates everything from 0.0 to 1.0.

![image](https://user-images.githubusercontent.com/13004169/73008718-ce07a980-3e17-11ea-9c76-d1341e92dfad.png)

![image](https://user-images.githubusercontent.com/13004169/73008723-d364f400-3e17-11ea-981b-c8e8894b7fdc.png)

It also seems to break an existing project when working with it, as the AnimationPlayer also forces the values.

(Before)
![image](https://user-images.githubusercontent.com/13004169/73010164-8cc4c900-3e1a-11ea-8388-bf84319e7247.png)

(After)
![image](https://user-images.githubusercontent.com/13004169/73010177-977f5e00-3e1a-11ea-8597-f5a908cb9a46.png)

Also notice what the AnimationPlayer is saying for one value (though in the TSCN file it is 1.6), and what the Inspector value is.

![image](https://user-images.githubusercontent.com/13004169/73009924-060fec00-3e1a-11ea-801d-cd2c37597e47.png)

![image](https://user-images.githubusercontent.com/13004169/73009939-0b6d3680-3e1a-11ea-9169-9c17a9d338d9.png)

May be related to this:  https://github.com/godotengine/godot/pull/34012/commits/7e6fa6c7a808840243637dc4b07947a93beb88c5

Will try to test it and post back with results.

**Steps to reproduce:**
Make a Path2D and try to set the Unit Offsets in a way to get looping when the offset must start at a value other than 0.0.

Or open the project below in 3.1, and them in 3.2 and try adjusting the keyframe values.

**Minimal reproduction project:**

(Recommend looking at this in 3.1 first, as work in 3.2 can overwrite it.)

[Unit Offset Path2D Issues.zip](https://github.com/godotengine/godot/files/4104675/Unit.Offset.Path2D.Issues.zip)

**Comment by YeldhamDev** [comment]
CC @KoBeWi

**Comment by KoBeWi** [comment]
This is a result of #29172

I guess it makes sense to allow both `is_lesser` and `is_greater`, since the offset is clamped/wrapped anyways...
