### ISSUE TITLE
Rendering issues with camera bounding box in editor

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#35486]
**Godot version:**
94d3bcbc9

**Issue description:**
The camera bounding boxes are scaled when zooming in, which results in flickering when zooming far away.
This is not the case for the origin lines for example.

**Steps to reproduce:**
Add a Camera2D and zoom out.

**Comment by tom-jk** [comment]
3.2.2.stable, looks to be resolved.

![35486](https://user-images.githubusercontent.com/64640811/87646252-7b63d600-c746-11ea-8f85-b45c1f3747da.gif)

**Comment by Calinou** [comment]
Closing as resolved per @tom-jk's comment.
