### ISSUE TITLE
BaseButton and other virtual Node and Resource types can't be instantiated even when derived in custom types

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#35484]
Unsure if this is a bug, or should really be a feature request, but I feel it needs discussion.

**Godot version:**
3.1.2 (Mono)

**Issue description:**
It is not possible to create a node of type `BaseButton` in the editor. 

Unsure if this is to stop people using it accidentally, but `BaseButton` is a sensible base class to implement custom buttons from. `BaseButton` contains useful code for handling mouse states (over, pressed etc), and also accommodates touch behaviour when a button is dragged in a scroll container (so the press becomes a drag, not a press). 

We allow the use of other node types which also must be extended before they can be used (e.g. `Container`). These classes display a warning in the editor indicating a script should be attached. The same behaviour should be used for `BaseButton`.

**Minimal reproduction project:**
No project. Node cannot be created in Godot editor.

**Comment by akien-mga** [comment]
For the record, this lists BaseButton but the same is true for many virtual classes in Godot, which are flagged as non instantiable (because it doesn't make sense to instantiate them as is in the editor - but it would make sense for custom classes that derive from them).

`Texture` is another example, or `CanvasItem`.

**Comment by neikeq** [comment]
One way this could be solved, is to add stub classes. All a stub class would do is declare the `BaseButton` abstract methods and add a creation function, but it would not be added to `ClassDB` (nor need to use `GDCLASS` for that matter). Basically, `ClassDB::register_virtual_class<T>` would either take a second type parameter for the stub class, or just take the creation function as an argument:

```
class BaseButtonStub : BaseButton
{
    int abstract_method_to_declare() { return 0; }

public:
    BaseButtonStub() {};
};

`ClassDB::register_virtual_class<BaseButton, BaseButtonStub>`
// or passing a `Object *(*)()` function pointer
`ClassDB::register_virtual_class<BaseButton>([]() { return memnew(BaseButtonStub); })`.
```

This way the C++ class can still be abstract (forcing inheritors to declare the methods).
We could also add information in `ClassDB` about which methods are abstract, to allow generated bindings to still declare them abstract as well if they want (I would use that for C#).

cc @reduz

**Comment by akien-mga** [comment]
See discussion on https://chat.godotengine.org/channel/core?msg=zouZx6g6qDCM7L5Ji onward for @reduz's current plan.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/58972.
