### ISSUE TITLE
Font Size in Search Results doesn't follow font in editor (Find in Files dialog)

### ISSUE THREAD

**Issue by Beechside** [godotengine/godot#35499]
Godot version: 3.2 RC2

MAC OSX 10.14.6 Mojave

Text in Search Results follows font in editor window to start with but gets out of sync and then ends up at wrong size.  

Additionally, highlight box does not stay with search term in Search Results so is not scaling correctly.

Possibly linked to #35269

Steps:
Open project
Search in files for text that appears in the project
Note that font size in Search Results is fine
Use Cmd +- to change size
Search results eventually lock out at wrong size

**Comment by Calinou** [comment]
I suppose you're referring to the search results displayed after using the Find in Files dialog, right?

**Comment by Beechside** [comment]
Correct - this is Find in Files

**Comment by elizaho** [comment]
I'd like to work on this.

**Comment by Calinou** [comment]
@elizaho Go ahead :slightly_smiling_face:

**Comment by Calinou** [comment]
@elizaho Any progress on this?

**Comment by MCrafterzz** [comment]
I'll work on it

**Comment by MCrafterzz** [comment]
Font size seams to be changed in  CodeTextEditor::_add_font_size, It doesn't update anything so I don't know how the find and replace dialog would get updated. Maybe the dialog looses focus?

**Comment by MCrafterzz** [comment]
There must be some sort of easy fix as it's a junior job but I can't find it.
