### ISSUE TITLE
GPU particles don't work without disable z

### ISSUE THREAD

**Issue by Plopsiskopsis** [godotengine/godot#35492]
3.2.rc2 and alpha3 or earlier on 3.1 stable it works 

Windows 10

Particles do not work without putting disable z on.
3.2.rc2
![bug](https://user-images.githubusercontent.com/35765659/73032071-a0862480-3e46-11ea-99d6-33f466310b7c.gif)

3.1 stable
![bug](https://user-images.githubusercontent.com/35765659/73032422-bc3dfa80-3e47-11ea-9e03-5cc307b43bbe.gif)

Just add particle put some mesh on pass 1 and add process material.

**Comment by clayjohn** [comment]
I can't reproduce this issue on Windows 10 NVidia GTX 1050 GPU.

Are you getting any sort of error message? I can see that you have an error in your output from the video.

**Comment by timothyqiu** [comment]
Might be related: #30906

**Comment by Plopsiskopsis** [comment]
Still happening on 3.2 stable. 
output/debugger/console don't show any errors. 
GPU is OpenGL ES 3.0 Renderer: GeForce GTX 950M/PCIe/SSE2

**Comment by akien-mga** [comment]
Tested on Linux with Intel HD 630 and AMD Radeon RX Vega M (both using Mesa 19.3.2) and I can't reproduce the issue.

It does seem to affect both some Windows Nvidia and iOS users judging by duplicate issues.

**Comment by Zireael07** [comment]
Intel 620 on Linux Manjaro (Mesa 19.3.2) here and I can't reproduce either.

**Comment by zxcvdev** [comment]
This commit seems to be the issue: 00b15c19b7adcad21465f731f76e1888f1553da2

I guess the specifications for the `atan(y,x)` function in GLSL ES 3.0 isn't clear enough, so the special case `atan(y,0)` returns `undefined` on some machines and `+-pi/2` on others.

I'm making a PR with a possible fix.
