### ISSUE TITLE
Mono: Can't compile project dummy preprocessor error

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#35496]
**Godot version:**
3.2 RC3

**OS/device including version:**
MXLinux19 64bits

**Issue description:**
When I try to compile my project I get this and the editor starts hoarding memory.

ERROR: run_dummy_preprocessor: Found unexpected '#endif' directive.
   At: modules/mono/editor/script_class_parser.cpp:677.

I'm not sure which #If causes it, I have a bunch of them

**Steps to reproduce:**
not sure tbh, hopefully it can be figured out with the error.

**Comment by akien-mga** [comment]
Without code it will be difficult to debug, I suggest that you review all your `#if`/`#endif` branches to ensure that they're valid.

**Comment by MightyPrinny** [comment]
I'm not sure what could make them invalid, the project compiles in RC2.

**Comment by MightyPrinny** [comment]
I have some nested branches and some are inside #region, not sure if that could be the cause, Mono Develop and VSCode don't have any problem parsing my files

**Comment by neikeq** [comment]
Please include an example source file where you can reproduce the error.

**Comment by MightyPrinny** [comment]
I found the problem, it was some #if with a ! without a space

#if!STUFF
#endif

I also found that preprocesor directives in comments such as this

/*
#if DEBUG
#else
#endif*/

cause this error

modules/mono/glue/gd_glue.cpp:250 - Failed to determine namespace and class for script: res://Scripts/Test.cs. Parse error: Unterminated comment.

**Comment by neikeq** [comment]
Thanks, I will fix these two.

**Comment by neikeq** [comment]
Actually, I will only fix the first one. The second one requires much more work that is simply not worth it because right after 3.2 stable is released we will switch to Roslyn and all that work would go to waste.
