### ISSUE TITLE
Linux - Segmentation Error on start

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#3550]
On start godot in linux (Gentoo) I see this output..
![snapshot1](https://cloud.githubusercontent.com/assets/7677575/12747284/258a9f50-c9b4-11e5-9ea2-3832c1744ba3.png)

After start PHYSICS 2D THREAD I see segmentation error.. But engine starts fine and work correctly

P.S. commit f6a8a0f51358e42295cc5a049074a59466161ad8 
scons -j5 p=x11 pulseaudio=no bits=64 openssl=builtin
[1] x86_64-pc-linux-gnu-4.9.3 *

CXXFLAGS="-O2 -pipe -march=core-avx2 -mavx -mcx16 -mmmx -msse -msse2 -msse4"
(from make.conf)

**Comment by ealataur** [comment]
On the Mac OS segmentation fault too.. And after error engine works fine
![capture image](https://cloud.githubusercontent.com/assets/7677575/12747644/35bddac0-c9b6-11e5-996f-04d7497fad97.png)

**Comment by reduz** [comment]
this is for physics 2d using threads?

**Comment by reduz** [comment]
also your osx build seems old

**Comment by ealataur** [comment]
> this is for physics 2d using threads?

[core]

message_queue_size_kb=1024
rid_pool_prealloc=20
thread_rid_pool_prealloc=20

[debug]

verbose_stdout=false

[display]

keep_screen_on=false
emulate_touchscreen=true
height=1334
orientation="portrait"
stretch_aspect="keep"
stretch_mode="2d"
width=750

[display.iOS]

use_cadisplaylink=true

[input]

ui_ok=[key(Return)]

[physics_2d]

thread_model=2

[rasterizer.iOS]

fp16_framebuffer=true

[render]

thread_model=2

**Comment by reduz** [comment]
yes, change 2 back to 1 and let me know if it works

**Comment by reduz** [comment]
also use a newer version of godot, current you are using is pretty old

**Comment by ealataur** [comment]
On Mac OS maybe but on linux I pull and build engine few minutes ago..
With 1 thread all ok
But if I want to use multithreads?

**Comment by reduz** [comment]
can you make a test scene that crashes when created with threads and post it here? I'm not sure what you might be doing. Also is the crash OSX only? I don't completely understand that

**Comment by ealataur** [comment]
It is only message about Segfault in console.. This message displayed after open project where physics thread sets in 2.. But engine work fine after that and visualy not crashed. But I decided that it is no good behavior of engine. It segfault displayed after open any project with setting physics thread 2

**Comment by akien-mga** [comment]
Can this still be reproduced in the current stable branch or development branch?

**Comment by akien-mga** [comment]
Closing as old.
