### ISSUE TITLE
References that are followed by a character will result in errors in .rst files

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#35501]
**Godot version:**
1c6d1fc

**Issue description:**
In some docs, like `SpatialMaterial`'s, some references have a character right after then:
https://github.com/godotengine/godot/blob/1c6d1fcf956b882fc8a14fa595b7f1e9b15e1574/doc/classes/SpatialMaterial.xml#L165-L166

The problem is that it results in errors when generating .rst files:
```
godot-docs/classes/class_spatialmaterial.rst:1130: WARNING: Inline interpreted text or phrase reference start-string without end-string.
```
There needs to be a `\` between the reference and the character to avoid errors.

**Comment by akien-mga** [comment]
`makerst.py` should already handle this properly for `[Class]s` AFAIK, but maybe it doesn't apply this for other kinds of references.
