### ISSUE TITLE
Malware Warning in Godot 3.2 (Mono) RC2 and RC3 Export Templates

### ISSUE THREAD

**Issue by alexfriesen** [godotengine/godot#35507]
**Godot version:**
Godot 3.2 (Mono) RC3

**OS/device including version:**
Windows 10 64bit

**Issue description:**
I am getting an Malware warning when downloading and installing the export templates for the recent RC of 3.2.mono.
The files "windows_32_release.exe" and "windows_32_debug.exe" in "Godot/templates/3.2.rc3.mono" are suspected to contain the Malware: [BDS/ZeroAccess.Gen7](https://www.avira.com/en/support-threats-summary/4192)
It only appears for the mono Version.

**Steps to reproduce:**
Install avira and download export templates

**Minimal reproduction project:**
any

**Comment by akien-mga** [comment]
Thanks for the report.

I submitted those files as false positives to Avira, hopefully they'll review and fix what triggered it.

**Comment by akien-mga** [comment]
Closing as there's nothing else to do from our end, there's no malware whatsoever in Godot binaries, so antiviruses have to fix their false positives.

**Comment by jgestiot** [comment]
You should submit them to AVG too
