### ISSUE TITLE
modifier keys (shift, ctrl...) should also work by themselves in input map

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3551]
Generally games don't really care much about modifier keys other than just another button to press.  I'm asking for the ability to use Shift, Control, Alt, Meta, Function, Caps Lock as extra buttons  by themselves in Input Map. Right now they only work when modifying another key and not by themselves.

**Comment by vnen** [comment]
As I stated in #3552, this might be an OSX-only issue. I can successfully create input map actions with only a modifier key on Linux.

**Comment by akien-mga** [comment]
Indeed, it works fine here on Linux.

**Comment by trollworkout** [comment]
hmm strange it seems godot on osx (or on my system) only detects modifiers when thy are combined with another key

**Comment by trollworkout** [comment]
@akien-mga  @vnen  im trying to learn to build my own .  i got scons working i m just trying to figure out how to download the master and make a repo i got smartgit installed but i also can run git in the shell. im gonna try to build my own cause whenever im reporting bugs my godot is a bit older.

if you got any advice or suggestions please let me know. ideally i only need the osx source

**Comment by trollworkout** [comment]
@akien-mga  @vnen  i have just successfully compiled godot for osx 32 bit and this problem is still there.

**Comment by trollworkout** [comment]
hey guys i noticed something strange looking into my engine.cfg

i defined an ui_sneak function as Shift+Z
shows up as 
ui_sneak=[key(Z,S)]

but if i put
ui_sneak=[key(S)]
shows up as S

how you make Shift show up by itself?

could you guys set your input map to Shift then lookinto the engine.cfg see what's written there?

**Comment by neikeq** [comment]
``` ini
[input]

test=[key(Shift)]
```

**Comment by trollworkout** [comment]
i don't see that. all my shifts get saved as [*,S] lemme try it

**Comment by trollworkout** [comment]
After further testing I conclude that modifier keys on my system (or OSX?) do not get detected by themselves until another key is pressed as well then they get detected. This seems to be the case everywhere in Godot Engine for me. Further testing reveals if manually inputed in the InputMap Shift does appear so is just my system that is not detecting it when pressed alone.

**Comment by trollworkout** [comment]
#4943 closes this issue
