### ISSUE TITLE
PathFollow does not update when unit_offset set to 0

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#35511]
**Godot version:**

3.1.2.stable.custom_build

**OS/device including version:**

Linux 5.4.13-arch1-1

**Issue description:**

My game contains paths that trains follow. Every path has a tunnel at the start and the end.
I'd like to be able to modify the path and have the tunnels always stay at the start and the end.
I'm able to get the end tunnel to update, but not the start, as setting `PathFollow.unit_offset` to `0` does not seem to update the Transform.

**Steps to reproduce:**

1. Create the following script
```
tool
extends PathFollow
class_name PathPin

export(float, 0, 1) var pin := 0.0

onready var path: Path = get_parent()

func _ready():
	path.connect("curve_changed", self, "_on_curve_changed")

func _on_curve_changed():
	unit_offset = pin
```

2. Attach it to a pathfollow that is child to a Path
2a. Ensure `loop=false` otherwise it will [wrap back to the start](https://github.com/godotengine/godot/issues/7665) (probably fixed in 3.2)
3. Drag the first point of the path around
4. Note that the `PathFollow` does not update its transform to match the start of the path
5. Set `pin > 0`
6. Drag the path around
7. Note that the `PathFollow` now _does_ update its transform

**Minimal reproduction project:**
![1579872219](https://user-images.githubusercontent.com/2496231/73072333-df39d000-3e82-11ea-9c65-67beb851ad7f.png)
[example.zip](https://github.com/godotengine/godot/files/4108618/example.zip)

**Comment by KoBeWi** [comment]
Godot version?

**Comment by rcorre** [comment]
Sorry, updated. Building master now to try that, as I see there have been some PathFollow-related changes.

**Comment by KoBeWi** [comment]
You can try with the official 3.2 release-candidate: https://godotengine.org/article/release-candidate-godot-3-2-rc-3

**Comment by rcorre** [comment]
No luck building RC-3 or master.

```
main/default_controller_mappings.gen.cpp:3:10: fatal error: typedefs.h: No such file or directory
    3 | #include "typedefs.h"
```

Should that be `core/typedefs.h`?

**Comment by KoBeWi** [comment]
I mean you don't need to build. Just download the executable.

**Comment by akien-mga** [comment]
@rcorre you have an old `.gen.cpp`, run `find -name "*.gen.*" -delete` (or `git clean -fxd`).

**Comment by rcorre** [comment]
Thanks @akien-mga, that worked!
FWIW I prefer to build because:

a) I like to be able to hack around with the engine
b) I want debug bits when I'm reporting issues

I can confirm this reproes on RC-3 (but #7665 is fixed, so it doesn't matter if `loop` is set).

**Comment by KoBeWi** [comment]
Still valid in 32c06df

The cause is this condition:
https://github.com/godotengine/godot/blob/32c06dfc8dbf4c3e29232b7dbccc6a34ba257027/scene/3d/path_3d.cpp#L97-L99
`delta_offset` equals to the difference of the previous `offset` and new `offset` when `unit_offset` changes. If the curve changes, the `offset` pretty much always changes, unless the curve length somehow doesn't change. The exception is offset of 0, which always stays the same, thus `delta_offset` is 0.
