### ISSUE TITLE
Adjusting settings in Editor Settings spams the output with errors

### ISSUE THREAD

**Issue by katoneko** [godotengine/godot#35518]
**Godot version:**
3.2 RC3

**OS/device including version:**
Windows 10

**Issue description:**
Changing values in Editor Setting causes the output to be spammed with the same error.

`Time should be greater than zero.`

![7hVRnU7v1q](https://user-images.githubusercontent.com/48890128/73076238-8b110900-3edf-11ea-9234-031eca799b5c.gif)

This error is also printed to the console when the project starts.

The bug is present in 3.2 RC3 and the earliest version where the bug is observed is 3.2.beta1. 3.1.2.stable is not affected however the same error message does get printed when the project starts.

In 3.2.beta1 the error text is different and more technical but seems identical in meaning:

`scene/main/timer.cpp:83 - Condition ' p_time <= 0 ' is true`

![image](https://user-images.githubusercontent.com/48890128/73076608-433eb180-3ee0-11ea-8326-043c9c2a3545.png)

The bug is observed in an empty project with no scenes or nodes added as well as in existing ones.

**Steps to reproduce:**
Open a project or create a new one. See the error printed to the console once loading is complete. Try to edit values in Editor Settings, see the output carpet-bombed with errors.

**Comment by akien-mga** [comment]
I can't reproduce it here on Linux, but one difference is that I don't have the info message about the GDScript language server starting. The issue might be linked to that feature.

**Comment by akien-mga** [comment]
Could you share your `project.godot` (for project settings) and `editor_settings-3.tres` (for editor settings)? This might be triggered by an option that would set a timer somewhere with a non positive value (though I reviewed most `set_wait_time()` calls and I can't see which one could lead to this error).

**Comment by katoneko** [comment]
https://pastebin.com/UKBmhRve - project.godot
https://pastebin.com/w4m17hfT - editor_settings-3.tres

**Comment by akien-mga** [comment]
Thanks, I can confirm the bug with your editor settings. Now to find the setting that triggers the issue :)

**Comment by akien-mga** [comment]
That's because of:
```
text_editor/completion/idle_parse_delay = 0
```
It should not be possible to set it to 0 as it has a minimum value of 0.1 in the editor settings dialog. But Godot 3.1 did not have this security so you might have set it to 0 then, and it causes problems now. If you remove that line it should be fixed.

**Comment by katoneko** [comment]
Yeah, I've just figured it out as well! The error went away when I changed the setting from 0. The issue's resolved, so closing now.
