### ISSUE TITLE
Make shift clicking the arrows in FileSystem dock work like in the node tree

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#35529]
**Godot version:**
97cc2e53f

**Issue description:**
You can only close / open all folders in the FileSystem dock by alt+left/right, not by shift clicking on the arrow like in the node tree.

**Steps to reproduce:**
Create some folders and shift click the arrows.

**Comment by FeatherAntennae** [comment]
I'm actually working on this! https://github.com/godotengine/godot/pull/33984

**Comment by akien-mga** [comment]
Fixed by #62666.
