### ISSUE TITLE
modifier keys are not detected in Input. polling under _process(delta)

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3552]
This code does not work for me either in _process or _fixed_process. I am using Godot Beta OSX release (the one on the website not the master).

```
func _ready():
	set_process(true)
func _process(delta):
   if(Input.is_key_pressed(KEY_ESCAPE)):
      if(Input.is_key_pressed(KEY_SHIFT)): # here nothing is detected
         get_tree().quit()
```

Modifier keys are not detected at all. I tried shift, control, meta nothing.  The only way I can detect them is event.shift in _input(event) and worst of all they can only be detected when modifying another key (see below). Has something changed or is this intentional or is it my system? I am following an older tutorial that did it this way so I assume it used to work before. 

the tutorial is here
http://www.gamefromscratch.com/post/2015/01/28/Godot-Engine-Tutorial-Part-3-Program-Lifecycle-and-Input-Handling.aspx

So as i said before modifiers only get detected in events under _input(event) the event.shift (or any other modifier specific event) is not detected unless another key is pressed making Shift press detection  by itself currently impossible.

if (control.shift): # this works but the input event is not triggered when shift (or any modifier is pressed by itself) so nothing happens until you press another random key 

And last point is Shift (or any other modifier key) does not work by themselves in InputMap (I made another issue for this one #3551)

**Comment by trollworkout** [comment]
further testing seems the issue is caused by modifier keys being constantly pressed while game is running  while the other issue of modifiers not working by themselves in InputMap is just not an implemented feature

**Comment by vnen** [comment]
Your code works for me with current HEAD (d2f2eed). `Input.is_key_pressed()` does detect modifier keys.

**Comment by vnen** [comment]
> i did a test with a an action set as Shift+Z and when running the game all I have to do is push Z no Shift needed.

Does not run like this for me. I do have to press <kbd>SHIFT</kbd>+<kbd>Z</kbd> to trigger the action. Pressing only <kbd>Z</kbd> do not trigger it.

Maybe this is OSX only?

**Comment by trollworkout** [comment]
cloned the repo locally and compiled my own osx build  and this problem is still there

**Comment by lizistorm** [comment]
I tried this and also have the problem. SHIFT and CONTROL not work.

**Comment by trollworkout** [comment]
@lizistorm  thank you for testing this. so far this only happens on macs.

**Comment by trollworkout** [comment]
#4943 closes this issue

**Comment by Keyaku** [comment]
I'm really sorry, but if I use `is_action_pressed()`, it still won't detect the modifiers.

Example code could be the same as yours but with this method:
```
func _ready():
    set_process(true)
func _process(delta):
    if Input.is_action_pressed("quit"): # composed of Meta+Q or ALT+F4
        get_tree().quit() # pressing only Q will reach here
```

Am I wrong in any of this and somehow missed that `is_action_pressed()` should be avoided?

**Comment by vnen** [comment]
@Keyaku actions ignores the modifiers, see https://github.com/godotengine/godot/issues/2597#issuecomment-167782955

**Comment by Keyaku** [comment]
@vnen Thank you! Is this documented somewhere or not yet (other than that comment)?

**Comment by Keyaku** [comment]
@vnen Thank you!

**Comment by trollworkout** [comment]
@Keyaku  I was unaware that Input ignores polling  but you can probably do some magic and check for is_key_pressed("KEY_META") if the action has meta in it.

**Comment by hedin-hiervard** [comment]
Sorry to reopen the old issue, but what is a proper way to check for action WITH modifiers? So that a check would trigger Shift+D action but won't trigger D action?
