### ISSUE TITLE
Game crash with android custom build and using vibrate

### ISSUE THREAD

**Issue by BloodOrange** [godotengine/godot#35533]
**Godot version:**
3.2 RC3
**OS/device including version:**
Android 7
**Issue description:**
I am developping a game with godot 3.2 RC3. I use smartphone vibrate thank the function Input.vibrate_handheld(200).
I try to use the custom build. The export on my android phone is good.
But when the smartphone have to vibrate, the game crash.

**Steps to reproduce:**
Use the default custom build for android.
Make the smartphone vibrate.
**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @volzhs

**Comment by BloodOrange** [comment]
Thank @Calinou, I forget to add labels

**Comment by Calinou** [comment]
@BloodOrange It's OK, only maintainers can add labels anyway :wink:

**Comment by akien-mga** [comment]
Tested on my Xiaomi Pocophone F1 running Android 9, I can confirm the bug.

On a test project using `Input.vibrate_handheld(300)`, I tested the following scenarios:

- Normal export (prebuilt template) with `VIBRATE` permission *disabled*: nothing happens, no error in logs (we should probably have an `ERR_FAIL` to make it clear to the user why it's not working)
- Normal export with `VIBRATE` permission *enabled*: works perfectly.
- Custom build (using Android source template and "Use Custom Build") with `VIBRATE` permission *enabled*: crashes with the following stacktrace:

```
1-25 18:33:59.889  1942  2070 E AndroidRuntime: FATAL EXCEPTION: GLThread 69234
01-25 18:33:59.889  1942  2070 E AndroidRuntime: Process: org.godotengine.bringoutyourdead, PID: 1942
01-25 18:33:59.889  1942  2070 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at org.godotengine.godot.utils.PermissionsUtil.requestPermission(PermissionsUtil.java:79)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at org.godotengine.godot.Godot.requestPermission(Godot.java:1009)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at org.godotengine.godot.Godot.vibrate(Godot.java:365)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at org.godotengine.godot.GodotLib.step(Native Method)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at org.godotengine.godot.GodotRenderer.onDrawFrame(GodotRenderer.java:51)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/org.godotengine.bringoutyourdead-g3gi68psd1xd3b_YG9kvLg==/base.apk"],nativeLibraryDirectories=[/data/app/org.godotengine.bringoutyourdead-g3gi68psd1xd3b_YG9kvLg==/lib/arm64, /data/app/org.godotengine.bringoutyourdead-g3gi68psd1xd3b_YG9kvLg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-25 18:33:59.889  1942  2070 E AndroidRuntime: 	... 7 more
```

**Comment by volzhs** [comment]
it seems `android.support.v4.content.ContextCompat` is missing while creating a custom build.
i have no clue right now.

**Comment by kjav** [comment]
Is there any way to hotfix this inside a live project without using a custom build of Godot? E.g. installing the missing dependency as a library?
