### ISSUE TITLE
Normal maps do not work for 3D models in Godot_v3.2-rc3

### ISSUE THREAD

**Issue by codeape** [godotengine/godot#35532]
**Godot version:**
Godot_v3.2-rc2

Also tested: Godot_v3.2-rc2 and Godot_v3.2-rc1

**OS/device including version:**
Windows 10 Version 1903 (OS Build: 18362.592)

**Issue description:**
Normal maps do not work. It looks like the normal is not used. Tried removing the normal and the result is like when I have the normal.

**Steps to reproduce:**
1. Create project using OpenGL ES 3.0
2. Create a sub folder called 'model' in root of project
3. Drag Diffuse and Normal (4k textures in png format) texture to 'model' dir in editor from File Explorer
4. Drag fbx model with animation (exported for blender with built in fbx exporter) to 'model' dir in editor from File Explorer
5. Inspect material: Fbx model has two materials after export. One for body and one for eyes exactly as in blender. Albedo and Normal textures assigned automaticly and correct to the Diffuse and Normal properties of the material from the import. 
6. Double click on the fbx model in GD Editor and select "New Inherited"
7. Save resulting scene to 'model' dir

**Minimal reproduction project:**
I can send that to the person who is willing to take a look at this problem I am also willing to attach blender file in that case. (if that is ok)

I have attached screenshots of the problem for now, and the normal texture. The same model in Blender and Godot using Diffuse and Normal textures.

![blender_with_normal](https://user-images.githubusercontent.com/1051317/73100625-34f79200-3eee-11ea-89c9-176ed39bdb6e.png)

![godot_with_normal](https://user-images.githubusercontent.com/1051317/73100650-43de4480-3eee-11ea-940a-ff2bd99789a0.png)

![troll_normal_4k](https://user-images.githubusercontent.com/1051317/73100855-bc450580-3eee-11ea-8c26-ee5f89d5f4fa.png)

**Comment by clayjohn** [comment]
You mention that you tested on rc1 and rc2 as well. Did it work in those?

**Comment by codeape** [comment]
It did not work in rc1 and rc2

**Comment by codeape** [comment]
If I hit unshaded on the body material it kind of looks like the normal is used ... but I am not sure. See the difference between the eye and the body. The body looks smother almost like the one in blender. 
![godot_unshaded](https://user-images.githubusercontent.com/1051317/73101415-e814bb00-3eef-11ea-917e-d5357f730d8a.png)

**Comment by codeape** [comment]
I will close this and create a new simple model to reproduce this and attach it to a new issue.

**Comment by codeape** [comment]
To end this for real. The stable release of 3.2 fixed normal maps for me. Thanks guys. Sorry for my bad 3D art but here is the proof:

![works](https://user-images.githubusercontent.com/1051317/73593355-b01b0280-4503-11ea-8deb-d624e437c372.png)
