### ISSUE TITLE
Godot crashes while loading C# project after update

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#35544]
**Godot version:**
`master` / 1c6d1fcf

**OS/device including version:**
Manjaro Linux (Testing branch)

**Issue description:**
After updating Godot from d711c57 to 1c6d1fcf, I'm no longer able to open my project (written in C#) as it crashes with a core dump.

At this moment, I don't have much information except for the trace (attached below) but I'll update the issue if I happen to find more details.
[dump.txt](https://github.com/godotengine/godot/files/4111661/dump.txt)
[mono_crash.0.0.zip](https://github.com/godotengine/godot/files/4111662/mono_crash.0.0.zip)

**Comment by MightyPrinny** [comment]
Does it work if you delete the .mono folder? something similar has been happening to me, sometimes the editor crashes some time after the project loads, but it works again after I delete the .mono folder.

**Comment by mysticfall** [comment]
If I delete `.mono` the editor opens the project. However, if I restore the NuGet dependencies (as they are stored in the directory) and build the project, it crashes again with the same output.

**Comment by mysticfall** [comment]
Today, I updated Godot to 0f80df0 and tested it again. This time, the editor ignored its project history and preferences, but somehow it didn't crash so I was able to run my project again.

I'll close the issue for now.
