### ISSUE TITLE
Godot stops drawing background after extended use

### ISSUE THREAD

**Issue by 66945** [godotengine/godot#35545]
**Operating system or device - Godot version**
Godot Engine v3.1.2

Microsoft Windows Version 1809 (OS Build 17763.973)
(AMD Radeon(TM) Vega 3 Graphics)

**Issue description**
Godots editor will stop redrawing the background after about an 2-4 hours (sooner if there are particles or other similar things)

**Steps to reproduce:**
Oddly enough I haven't been able to reproduce this on other devices, but it happens consistently on the computer I am experiencing the bug on

**Minimal reproduction project:**
Any project will do this on my laptop. Even just a single sprite.

![image](https://user-images.githubusercontent.com/54561572/73117422-ab05f400-3f02-11ea-9161-4c7b11933229.png)

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by mhilbrunner** [comment]
Closing as there are no other reports and no reproduction with a more current version. Lets hope this one is fixed!
