### ISSUE TITLE
GLTF/GLB imported ignores child meshes, ESCN seems to work

### ISSUE THREAD

**Issue by ligazetom** [godotengine/godot#35548]
Godot version:
3.2.beta.custom_build.24281cd9c

OS/device including version:
Windows 10 Pro (Version: 1903, Build 18362.535)

**Issue description:**
Result of gltf/glb importer:
![image](https://user-images.githubusercontent.com/11858829/73119073-301df700-3f5d-11ea-8b95-29f314bfee2d.png)

Result of escn importer:
![image](https://user-images.githubusercontent.com/11858829/73119084-3ad88c00-3f5d-11ea-84e7-8798d4f682ef.png)

**Steps to reproduce:**
Just export from the .blend and try to import it in godot.

**Minimal reproduction project:**
[hovercraft.zip](https://github.com/godotengine/godot/files/4111813/hovercraft.zip)

I needed to put raycasts nodes to certain places, so I first tried to place empties where I want them to be, so I get the coordinates. It did not work, so I decided to use meshes, but they did not import as well. As you can see in images, gltf/glb importer ignores all children. I checked the .gltf file to see if they are being exported and they do, so it is on the importer side.

**EDIT**
Wanted heirarchy (ESCN):
![image](https://user-images.githubusercontent.com/11858829/73119156-103b0300-3f5e-11ea-83ad-8e17f0f3b769.png)

What I get from gltf/glb:
![image](https://user-images.githubusercontent.com/11858829/73119162-234dd300-3f5e-11ea-8693-1504c546dd01.png)

I know I could just "use" .escn, but it has other issues. There are a lot of discrepancies in import process. None of them works the same and there is not one that supports all it should.

**Comment by fire** [comment]
Is there a reason why you're nesting the meshes as a a child of the skeleton?

[hovercraft.zip](https://github.com/godotengine/godot/files/4112265/hovercraft.zip)

![image](https://user-images.githubusercontent.com/32321/73124451-981a1080-3f50-11ea-9ffb-76b9d31de701.png)

Here is it without the skeleton.

**Comment by ligazetom** [comment]
Hey, obviously I made them "parentless" in blender because I really needed the transforms only, however, yes, I had some animations, so that's why they were children of skeleton.

**Comment by fire** [comment]
Can confirm this is still a bug.

**Comment by aaronfranke** [comment]
Tested in Godot 4.0-stable, 4.1-stable, and the latest master, and can't reproduce the issue. I think this is fixed.

This is the GLB I exported from Blender 3.6.1: [hovercraft.glb.zip](https://github.com/godotengine/godot/files/12316602/hovercraft.glb.zip)
