### ISSUE TITLE
Having a Custom Module Emit a Signal

### ISSUE THREAD

**Issue by primesoftware** [godotengine/godot#3554]
I'm finishing up my HTTPS module and would like for the class to emit a signal once the program has processed the HTTP response. How exactly does one go about using Godot's emit signal system in a custom module?

**Comment by freemanfromgodotengine** [comment]
Great to hear about your work on the module, but I think with this kind of question you should better ask at [Godot's forum](http://godotengine.org/projects/godot-engine/boards) or developers IRC chanel  #godotengine-devel at freenode.net
Github is used for reporting bugs and feature requests.

**Comment by primesoftware** [comment]
@freemanfromgodotengine Thanks for pointing that out. I'm not sure why I thought the forums got removed.....

**Comment by reduz** [comment]
more reason to work on an asset sharing site for 2.1, so everyone can find
your work more easily
