### ISSUE TITLE
ReflectionProbe not showing my HDRI map

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#35551]
**Godot version:**
3.2 rc3 and I think previous too

**OS/device including version:**
Linux Manjaro

**Issue description:**
I have set the world environment in my camera3d and the result that I have WITHOUT the reflection probe is this:
![NoReflectionProbe](https://user-images.githubusercontent.com/16955149/73122179-32df1300-3f82-11ea-8e06-dec8d8adc3f1.jpeg)
if I put a reflection probe in the scene the result that I have is the following:
![ReflectionProbe](https://user-images.githubusercontent.com/16955149/73122200-6de14680-3f82-11ea-9208-d89a34251b90.jpeg)
As you can see in the first one I can see my hdri sky map reflected, in the second one I can see the "default" sky reflected and not my hdri map.
Also if I move to the end of the area of the reflection probe I can see that there are a mix with my hdri map and at the border of the reflection probe I have this result:
![RflectionProbeOut](https://user-images.githubusercontent.com/16955149/73122331-c5cc7d00-3f83-11ea-959e-b413a28535d1.jpeg)

**Comment by Calinou** [comment]
Try creating a WorldEnvironment node and assigning the Environment resource there instead of assigning it to the Camera node.

**Comment by grevius5** [comment]
Ok, if I put a WorldEnvironment node in the scene (with or without the ReflectionProbe as a child) I can see in the viewport the right reflection with the HDRI map, but when I start the game I see this:
![ReflectionProbeInWorldEnvironment](https://user-images.githubusercontent.com/16955149/73124029-ba368180-3f96-11ea-9da7-5f9443f93a8f.jpeg)
and it seems to reflect the grey background. If I go to the border the result is the same as before.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
