### ISSUE TITLE
RichTextLabel's text is not copied on duplication

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#35553]
**Godot version:**
f678141

**Issue description:**
When duplicating a `RichTextLabel` node via the editor, its `text` property will not be copied to the new node.

The `bbcode_text`, however, will be copied, and I think it overrides the `text`property and clears it, causing the bug.

**Comment by dankan1890** [comment]
I'm unable to reproduce it on windows 10 and Godot version 72c44bafac6e280b5e1e99b417588624bfb5ecc6
![bug](https://user-images.githubusercontent.com/7107228/73143559-f9022f80-409b-11ea-936f-3ff3091a623c.gif)

**Comment by YeldhamDev** [comment]
Oops, wrong node, I meant `RichTextLabel`.

**Comment by dankan1890** [comment]
Ah ok, I confirm that "text" is overwritten by "bbcode_text" in the duplication.

Ps: out of the issue, in the RichTextLabel node, wouldn't it be more logical to have only one text box?

**Comment by leodimano** [comment]
Commited a fix to the issue #36037
