### ISSUE TITLE
TextEdit scroll position jumps when the previous caret position is outside of the visible area

### ISSUE THREAD

**Issue by issork** [godotengine/godot#35587]
**Godot version:**
fe26e53065827f83bb5f720d1b20e83850624d8c

**OS/device including version:**
Linux Mint 19.3 Cinnamon 4.4.8

**Issue description:**

When clicking on a character inside of a TextEdit to change the carets position and the previous carets position is outside of the visible area, the scroll position is adjusted in a weird manner that leads to the users mouse no longer being positioned over the clicked character, which can be rather confusing.
The scroll position should not be adjusted at all in this case.

**Steps to reproduce:**

1. Place the caret somewhere on the TextEdit.
![Screenshot from 2020-01-26 14-27-45](https://user-images.githubusercontent.com/12477395/73135945-a9464880-4048-11ea-9221-e947a101b130.png)

2. Scroll, so that the caret leaves the visible area and click on a character.
![Screenshot from 2020-01-26 14-28-30](https://user-images.githubusercontent.com/12477395/73135946-a9464880-4048-11ea-9a84-0b798c710367.png)

3. Your mouse now is no longer positioned on the character you clicked on, because the scroll position has been adjusted.
![Screenshot from 2020-01-26 14-29-13](https://user-images.githubusercontent.com/12477395/73135947-a9464880-4048-11ea-9c1f-0271b6619888.png)

**Minimal reproduction project:**
[TextEditTest.zip](https://github.com/godotengine/godot/files/4141834/TextEditTest.zip)

**Comment by creikey** [comment]
Seems to me like the bug is likely located in the function `cursor_set_line` after stepping through the debugger

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by KoBeWi** [comment]
Seems fixed in 4.0
