### ISSUE TITLE
Opened scenes are still remembered after project deletion

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#35585]
**Godot version:** v3.2.rc3

**OS/device including version:** macOS 10.15.2

**Issue description:**

When "Restore Scenes On Load" is on, reopening a project will try to open the previously opened scene.

After deleted a project, I created a new project using the same path as the deleted one. When Godot opens the new project, it still tries to restore the scene tab as if it's the old project. So I get this alert:

> Can't open 'TestScene.tscn'. The file could have been moved or deleted.

I think maybe Godot should forget the opened scenes once I click "Remove Missing" in the project manager. Or, at least when a new project at the same path is created.

**Steps to reproduce:**
1. Create a new project
2. Create a new scene, and save it as "TestScene.tscn"
3. Turn on Interface / Scene Tabs / Restore Scenes On Load in editor settings
4. Keep the TestScene open, and quit Godot
5. Delete the project directory manually
6. Open Godot, the deleted project will be labeled as "Missing Project"
7. Remove the missing project
8. Create a new project at the same path as the previous one
9. Open the newly created project, and you'll get the alert.

**Minimal reproduction project:** N/A

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by Flavelius** [comment]
Additionally, when the restore on load option is disabled in the settings, scenes are still restored irrespective of its value with what seems to be the scene setup that was saved before the setting was toggled. This state cache should be reset when the setting is changed.
3.3.rc6

**Comment by KoBeWi** [comment]
This is resolved in 4.0

**Comment by timothyqiu** [comment]
Is this resolved in 3.x?

**Comment by KoBeWi** [comment]
No, and the fix can't be backported.

**Comment by KoBeWi** [comment]
The original bug can't happen in Godot 4. Open a new issue, as it's likely something different.
