### ISSUE TITLE
Toolbar: Light Theme Accent Color Not Accenting

### ISSUE THREAD

**Issue by rontarrant** [godotengine/godot#35582]
**Godot version:** 3.1.2.stable.official

**OS/device including version:** Windows 10 Build 18363.592, MSI GE72 2QF Apache Pro

**Issue description:** When selecting either of the light themes available in (menu) Editor > Settings, the accent color is ignored in the Toolbar, making it impossible to tell which Mode is selected.

**Steps to reproduce:** Using (menu) Editor > Settings > Preset, switch to either Light theme, Solarized Light theme, or change Base Color to any light color.

**Minimal reproduction project:** Any

**Comment by Chaosus** [comment]
Its a duplicate of #28941 and fixed in 3.2

**Comment by rontarrant** [comment]
Thanks, Yuri.
