### ISSUE TITLE
Multi-monitor Readiness

### ISSUE THREAD

**Issue by rontarrant** [godotengine/godot#35594]
On my multi-monitor set-up, each time I open a Godot project, the window is maximized and moved to my middle monitor which means I have to un-maximize it and move it to another monitor. And because—un-maximized—Godot's window is tiny, I have to resize it rather drastically in order to a work.

Also, whenever I switch to the Project Manager, it also jumps to the middle monitor. All this may be seen as a simple inconvenience, but the amount of time wasted moving and sizing windows, plus the fact that it has to be done at all, add up to a lot of annoyance.

So what I'm considering proposaling is to have all windows and dialogs remember their size, placement, and maximize state from the last time they were open so they can reopen in the same size and position.

The way the windows are handled now is fine for single-display—but not for multi-display—systems.

**Comment by Calinou** [comment]
There's a WIP pull request to address this: https://github.com/godotengine/godot/pull/32056

Also, next time, please open feature proposals on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository, not here. This repository's issue tracker is now meant to be used for bug reports only.

**Comment by rontarrant** [comment]
Hi Hugo,

> There's a WIP pull request to address this: #32056
<https://github.com/godotengine/godot/pull/32056>
Glad to hear it. Thanks for pointing this out.

> Also, next time, please open feature proposals on the Godot Proposals
<https://github.com/godotengine/godot-proposals> repository, not here. This
repository's issue tracker is now meant to be used for bug reports only.

Noted.
I followed the advice given on this page: Will your contribution be merged?
Here's how to tell
<https://godotengine.org/article/will-your-contribution-be-merged-heres-how-tell>
in the section entitled, "Ask First." The sole paragraph in this section
reads:

*Ask about what you want to do, by either opening an issue
<https://github.com/godotengine/godot/issues/new>, or asking in the
#godotengine-devel IRC channel on Freenode. This will defintely save you
time and effort, as other contributors will better guide you on whether
your proposal is desired or not (or what needs to be changed so it would
be). *

I'd like to suggest this be reworded to avoid future confusion.
