### ISSUE TITLE
Some fragment shaders work in the editor, but don't work in the game

### ISSUE THREAD

**Issue by MxZhur** [godotengine/godot#35591]
**Godot version:**
- 3.1.2-stable Standard edition
- 3.2-rc3 Standard edition

**OS/device including version:**
OS: Windows 10 Pro 64-bit
Graphics card: NVIDIA GeForce GTX 1050 Ti

**Issue description:**
Some fragment shaders work in the editor, but don't work in the game. For example, the palette swap shader given in the _Steps to reproduce_ section.

That palette swap shader works on the first sprite I assigned it to, but when I tried to assign it to another one and duplicate it in order to control its parameters independently, it stopped working in the game. Making a brand new ShaderMaterial object with a brand new Shader and copying the code of the original shader didn't help either.
However, the original shader material in the first sprite still works.

The only workaround I found was to assign the original shader to the second sprite and duplicate it via code like this:

```gdscript
func _ready():
	# Duplicate the material...
	$AnimatedSprite.set_material($AnimatedSprite.get_material().duplicate(true))
	
	# ... and then change the colors
	var sprite_shader = $AnimatedSprite.get_material()

	sprite_shader.set_shader_param("target_armor_color_1", color1)
	sprite_shader.set_shader_param("target_armor_color_2", color2)
```

Also, some shaders _do_ work both in the editor and the game. For example, the following simple shader works:

```shader
shader_type canvas_item;

void fragment() {
    vec4 color = texture(TEXTURE, UV);
    COLOR = vec4(1, 1, 1, color.a);
}
```

**Steps to reproduce:**

1. Create an AnimatedSprite with at least 1 animation and 1 frame. The sprite should have at least 2 different colors so the changes would be visible.

2. Add a ShaderMaterial to it.
3. Load an external .shader file with the following content:
```shader
shader_type canvas_item;

uniform vec4 armor_color_1 : hint_color;
uniform vec4 armor_color_2 : hint_color;
uniform vec4 armor_outline_color : hint_color;

uniform vec4 target_armor_color_1 : hint_color;
uniform vec4 target_armor_color_2 : hint_color;
uniform vec4 target_armor_outline_color : hint_color;

void fragment() {
	vec4 pixel = texture(TEXTURE, UV);
	
	if (pixel.r == armor_color_1.r && pixel.g == armor_color_1.g && pixel.b == armor_color_1.b) {
		COLOR = vec4(target_armor_color_1.rgb, pixel.a);
	} else if (pixel.r == armor_color_2.r && pixel.g == armor_color_2.g && pixel.b == armor_color_2.b) {
		COLOR = vec4(target_armor_color_2.rgb, pixel.a);
	} else if (pixel.r == armor_outline_color.r && pixel.g == armor_outline_color.g && pixel.b == armor_outline_color.b) {
		COLOR = vec4(target_armor_outline_color.rgb, pixel.a);
	} else {
		COLOR = pixel;
	}
}
```
4. Set `armor_color1` and `armor_color2` to two colors from the sprite, and `target_color1` and `target_color2` to any custom colors. The colors should change in the editor (but not in the game, due to that bug).

**Minimal reproduction project:**
A new project with a Node2D root and an AnimatedSprite.

**Comment by clayjohn** [comment]
This likely due to you trying to compare floating point numbers with ``==``. This is something that does not work reliably in any programming languages. See: http://www.cs.technion.ac.il/users/yechiel/c++-faq/floating-point-arith.html

Instead you should be using something like ``if (abs(color1 - color2) < 0.01)``

**Comment by MxZhur** [comment]
> This likely due to you trying to compare floating point numbers with `==`. This is something that does not work reliably in any programming languages. See: http://www.cs.technion.ac.il/users/yechiel/c++-faq/floating-point-arith.html
> 
> Instead you should be using something like `if (abs(color1 - color2) < 0.01)`

@clayjohn Thank you, that helped! 👍
