### ISSUE TITLE
GraphEdit has a lot of code about bezier curves, but doesn't use Curve

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#35593]
**Godot version:**
02ca4c49fa3a089e48718b26276660895cdb0cf6

**Issue description:**
GraphEdit could use Curve instead of using it's own functions, because there is a lot of duplicate code.

https://github.com/godotengine/godot/blob/fde0579ed1d79ba1561c0dbc566dd8374dc8cf73/scene/gui/graph_edit.cpp#L623-L633
https://github.com/godotengine/godot/blob/af5e0fff66d55d07a7910bcd7f170da2f952f7cb/scene/resources/curve.cpp#L35-L45

**Comment by mechPenSketch** [comment]
While waiting for my pull request to be approved, I think I can work on this refactoring.

On `graph_edit.cpp`, the function `_bezier_interp(...)` is call 3 times. I could swap them out for calling `curve.cpp`'s `_bezier_interp(...)` while deleting `graph_edit.cpp` and `graph_edit.h`'s `_bezier_interp(...)`. However, from `graph_edit.cpp`, how do I call `_bezier_interp(...)` from `curve.cpp`?

**Comment by Jummit** [comment]
I worked on this in #40513, where most of the work is already done. I stopped when Vulkan moved to the master branch because I couldn't test it.

**Comment by mechPenSketch** [comment]
Oh, nvm then. Unfortunately, I can't help test either as my gpu isn't compatible with vulkan.

**Comment by Jummit** [comment]
I forgot to mention that this is resolved in #51952
