### ISSUE TITLE
Copying hex code from exported Color variable does not copy anything to clipboard

### ISSUE THREAD

**Issue by Kiel97** [godotengine/godot#35603]
**Godot version:**
~~3.2 RC 3~~
3.2 Stable

**OS/device including version:**
Windows 7 Home Premium Service Pack 1
Windows 10 Home

**Issue description:**
When user tries to copy hex code of color he picked using exported Color variable, he gets ~~"color" string when pasted instead~~ nothing copied to clipboard.

**Steps to reproduce:**
1. Export Color variable so it becomes visible in Inspector
2. Change that variable value in Inspector
3. Try to copy Hex Code visible in bottom right corner of dialog
4. Paste copied value

**Minimal reproduction project:**
[ExportColorIssueProject.zip](https://github.com/godotengine/godot/files/4114741/ExportColorIssueProject.zip)

**Comment by Calinou** [comment]
I can't reproduce this on commit https://github.com/godotengine/godot/commit/9daaa12bae0cd3637da8f401333b3bc522aee66e. Make sure the hexadecimal code is displayed instead of the color string:

### Hexadecimal code

![image](https://user-images.githubusercontent.com/180032/73143652-0835ad00-409d-11ea-9792-930ab8db7c60.png)

### Color string

![image](https://user-images.githubusercontent.com/180032/73143654-0c61ca80-409d-11ea-82c7-7c8a6f793d9e.png)

**Comment by Kiel97** [comment]
According to color string, I meant I got in clipboard literally "color" text, 5 chars, not color value as Godot's Color object.

Well, I have discovered something else. I downloaded Godot 3.2 RC 3 on my another PC with Windows 10 Home installed. I tried to reproduce this bug with attached project and it seems copying hex code from that dialog doesn't work at all. Both Control+C and Right Mouse Context Menu are not working. I made sure my clipboard board works my copying and pasting random text in Node description and it's fine. Also I made sure I'm trying to copy hex code, not the Color object as you showed on images above.

**Comment by nathanwfranke** [comment]
Cannot reproduce this on RC 3 Mono, I am using Linux Mint 19.3.

It is likely that this is a Windows-only issue, but "needs testing" indeed

**Comment by MennoMax** [comment]
I have discovered something else which might be related - Linux Mint 19.3;

Could it be that you already had "color" in your clipboard? When I attempt to copy the hex value using the rmb context menu, the selection is cleared as soon as the mouse enters it, resulting in nothing actually being copied.

**Comment by Kiel97** [comment]
@MennoMax Sorry for my late response. Well, I tried reproducing this issue on both Windows 7 and 10 with Godot 3.2 stable and it's just like you say. Actually, nothing is copied to clipboard while trying to copy Hex Code of color variable. You are right. Here you can see this issue.

**Windows 7**
![Windows7](https://user-images.githubusercontent.com/26723223/74092595-a460aa80-4ac6-11ea-91c9-c3a6c9ecac50.gif)

**Windows 10**
![Windows10](https://user-images.githubusercontent.com/26723223/74092596-a75b9b00-4ac6-11ea-8460-0276a39e8486.gif)

**Comment by jluini** [comment]
I have this issue in 3.2 and noted that **only happens if you copy with mouse (using right-click menu), not with keyboard (ctrl-c)**.
