### ISSUE TITLE
update android module tutorial

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#3561]
i hope this tutorial will be updated:
https://github.com/godotengine/godot/wiki/tutorial_android_module

because of android module use gradle

**Comment by akien-mga** [comment]
It's actually this one that has to be updated (the GitHub wiki is no longer in use), and you can help :) http://godotengine.org/projects/godot-engine/wiki/Creating_Android_modules

**Comment by GrandFunkR** [comment]
uhm but  there is
ant
in build paragraph

**Comment by akien-mga** [comment]
Yes, that's why I said it has to be updated :) But the GitHub page is no longer in use, I'll soon add a mention to each of them to make it clearer.

**Comment by GrandFunkR** [comment]
Ok sorry for misunderstanding.
But I can not contribute to update this tutorial because of I want to create an android module and I'm not able to compile with it.

**Comment by GrandFunkR** [comment]
I tried to replace 
env.android_module_file("android/MySingleton.java")
by 
env.android_add_java_dir("android")

having this error:
package Godot does not exist
public class MySingleton extends Godot.SingletonBase {

**Comment by reduz** [comment]
I think you have to import org.godotengine.godot now

**Comment by GrandFunkR** [comment]
thanks
added these imports:

import org.godotengine.godot.Godot;
import android.app.Activity;
import android.content.Intent;
import javax.microedition.khronos.opengles.GL10;
import org.godotengine.godot.GodotLib;

now I have two errors to this:

error: cannot find symbol
                    SDK.initializeHere();
                    ^
  symbol: variable SDK
/home/dario/godot/sources/godot/modules/googleplayservice/android/MySingleton.java:26: error: cannot find symbol
          activity.runOnUiThread(new Runnable() {
          ^
  symbol:   variable activity
  location: class MySingleton
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

**Comment by djrm** [comment]
Movable to documentation repo

**Comment by akien-mga** [comment]
The tutorial has been updated already: https://github.com/godotengine/godot-docs/blob/master/reference/creating_android_modules.rst

Feel free to reopen an issue on the godot-docs repo if there are still things to improve.
