### ISSUE TITLE
Vulkan: version compilation OK, launch OK but errors in the console

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#35611]
**Godot version:**
v4.0.devel.custom_build.b75112f5c (just updated)

**OS/device including version:**
Windows 10 64bits 

**Issue description:**

When launching the Project Manager, the following error appears in the console : 

`ERROR: Method definition provides more arguments than the method actually has 'VisualServer::environment_set_ssao'.
At: core\class_db.cpp:1257`

When starting a new project, the following error appears:

`ERROR: In Object of type 'EditorNetworkProfiler': Attempt to connect nonexistent signal 'break_request' to method 'ScriptEditorDebugger._profiler_seeked'.
At: core\object.cpp:1452`

And when the editor is displayed, the following error is repeated indefinitely: 

`ERROR: uniform_set_create: Condition ' !shader ' is true. returned: RID()
At: drivers\vulkan\rendering_device_vulkan.cpp:4217`

Finally, when the editor closes:

`ERROR: ~ShaderRD: 3 shaders of type SceneHighEndShaderRD were never freed
At: servers\visual\rasterizer_rd\shader_rd.cpp:490`

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
The Vulkan branch is in heavy development and it is expected that there will be many errors.

**Comment by TheMoye** [comment]
> 
> 
> The Vulkan branch is in heavy development and it is expected that there will be many errors.

Hello,
I know that, I'm flagging it in case it helps. 😉

**Comment by bitmammoth** [comment]
Since this is already opened, for what its worth I also have this on Ubuntu 18.04 lts

**Comment by lliberadzki** [comment]
Upvoting, since this problem still exists. In my case editor is launched and then instantly closed with OP error.

**Comment by Calinou** [comment]
@lliberadzki The crash is being tracked in #36246. It should be fixed in 1 or 2 days if all goes well.

**Comment by nathanwfranke** [comment]
> `ERROR: In Object of type 'EditorNetworkProfiler': Attempt to connect nonexistent signal 'break_request' to method 'ScriptEditorDebugger._profiler_seeked'. At: core\object.cpp:1452`

This was fixed in https://github.com/godotengine/godot/pull/36340

However there is a similar error that will be fixed in https://github.com/godotengine/godot/pull/36502

`ERROR: In Object of type 'EditorVisualProfiler': Attempt to connect nonexistent signal 'break_request' to callable 'ScriptEditorDebugger::_profiler_seeked'.
   at: connect (core/object.cpp:1427)`
Note "Visual" profiler not Network profiler

**Comment by nathanwfranke** [comment]
Most of the shader leaks posted here are now fixed by https://github.com/godotengine/godot/pull/36627. Still WIP

**Comment by clayjohn** [comment]
The last of these errors should have been fixed in https://github.com/godotengine/godot/pull/36679

Please open a new issue if you experience more errors. :)
