### ISSUE TITLE
2D tween animation - bad performance on 3.2rc4

### ISSUE THREAD

**Issue by PelegMedia** [godotengine/godot#35621]
**Godot version:**
3,2rc4

**OS/device including version:**
Windows7
**Issue description:**
Running a game with 2D twin animation jitters and the animation is very slow on 3.2rc4 (and rc1) compared to 3,1 where it is running smooth.

**Steps to reproduce:**

**Minimal reproduction project:**

The games runs perfect on 3.1. I duplicate it and imported into 3.2rc4 and the performance is very bad. 

Sprite movement jitters. Mouse control seems to lag but not sure. Could be the sprite movement makes it look like input lag.
A shader animate slowly. It do run perfect in the editor, same as it runs in editor or launched game in 3.1. I stopped it to make sure it is not the source but the sprite animation is still very slow.

Don't know why or where to start checking.
Since it is the same project it is expected to have the same performance not worse.

**Comment by akien-mga** [comment]
Can you share a project t hat reproduces the issue? It's hard to debug otherwise, all projects I've tried perform similarly on 3.1 and 3.2.

**Comment by PelegMedia** [comment]
@akien-mga the project is large. I saw frames drop but didn't yet find the source.
I will try to create a smaller one and look again in the profiler.

How can I find which object and methods highly use the CPU and GPU?

**Comment by Calinou** [comment]
> How can I find which object and methods highly use the CPU and GPU?

You can use the **Profiler** panel which is located in the **Debugger** window available at the bottom of the editor. Make sure to click **Start**, wait a bit then click **Stop** to get visible information.

**Comment by PelegMedia** [comment]
Hi @Calinou 
I checked the profiler and monitor and didn't seem to find the source of my problem.

I see that the Frame-Time peaks at 0.05365 (frame time -seconds) however none of the other parameters including my scripts show even close value.
I don't understand how to know what causes these peaks.

The Fps is 73 in ideal and goes to 34 when animating. Using 3.1 on the same project gives 73 FPS all the time (You can see in the screen captures).

These screens are from the 3.2 run:
![image](https://user-images.githubusercontent.com/39774781/73369300-0b0de900-42bb-11ea-9350-3d74450cae00.png)
![image](https://user-images.githubusercontent.com/39774781/73369306-106b3380-42bb-11ea-8836-daec73f34ca8.png)

As you can see in the next image playing the same game level in 3.1 has an almost fixed 73 FPS.
![image](https://user-images.githubusercontent.com/39774781/73369760-cdf62680-42bb-11ea-8be1-b3d4b4c60089.png)

**Comment by Calinou** [comment]
@PelegMedia We really need a minimal reproduction project to be able to diagnose this.

**Comment by PelegMedia** [comment]
@Calinou I will try to create one.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
