### ISSUE TITLE
Deleting a node deletes all animation tracks referencing that node.

### ISSUE THREAD

**Issue by GalanCM** [godotengine/godot#3562]
I noticed this while working on a game for Global Game Jam this past weekend. Say you have an animation set up in the animation player, and you are referencing a node that exists in the current scene file; If you then delete that node, any tracks that reference it will also be deleted.

I can see how this might make sense, but I found myself in a situation where I lost a good chunk of work:

I had a item–a sword specifically–attached to the player, and was animating it from the player scene. I later decided that it should be a pickup and removed it from the player, deleting several animations. Since you can create animations that reference a node path that doesn't exist, and then add the node via script at run time, I had assumed this would work, but instead wound up having to redo my work.

Given that we can create an animation with an invalid path, and that the engine will provide a helpful error if the path isn't valid at runtime, should Godot not keep the animation tracks? Or ask before deleting them?

**Comment by Ace-Dragon** [comment]
I believe Godot allows you to save animations to a file so they can be reused (have you tried doing that)?

**Comment by reduz** [comment]
I think you can disable this behavior in the project settings... but maybe
we could add something with quiker access (within anim editor) to
enable/disable the behavior?

**Comment by reduz** [comment]
or maybe when you delete, remind the user that some animation tracks will
be erased?

**Comment by freemanfromgodotengine** [comment]
Maybe just a pop-up with a question? For example "This node is animated. Do you want to delete all it's animation tracks as well?"and yes, no buttons?

**Comment by akien-mga** [comment]
> or maybe when you delete, remind the user that some animation tracks will be erased?

+1, I got hit by this one when renaming an AnimationPlayer node too, all its animations were lost when doing so (actually I was then able to port them easily to use the new name by editing the tscn directly, but if not they simply got removed from the scene).

**Comment by pphysch** [comment]
We already have the "Clean-Up Animation" option, so it would be really nice if "invalid" keys/tracks were marked red or something and leave it to the user to clean them up either on pop-up dialog or later.

I just got burned by merging a scene, apparently deleting some of the _merged_ anim-reliant nodes in a bad order, which led to _all_ my animations getting wiped everywhere without warning, and I didn't manage to recover the .tscn in time.

**Comment by akien-mga** [comment]
> Maybe just a pop-up with a question? For example "This node is animated. Do you want to delete all it's animation tracks as well?"and yes no buttons?

I suggest doing this. When you delete the Node through the editor, there's already a confirmation dialog:
![Screenshot_20200904_134634](https://user-images.githubusercontent.com/4701338/92236106-0d6d9c80-eeb5-11ea-9829-84ff54feb014.png)

The related code could be expanded to also check if the node being deleted is used in animations, and if so show a different dialog with the option to delete the node and remove any tracks referencing it, delete the node but keep the tracks, or abort.

**Comment by strank** [comment]
I had a look at this and added a checkbox to the Confirmation Dialog to directly see and change the editor setting that controls if animation tracks are deleted or left alone. That effectively implements what @akien-mga suggested. But: see the draft PR #42001 for some issues that I think should be decided on.
