### ISSUE TITLE
Custom drawing don't work on Control node

### ISSUE THREAD

**Issue by SteapaSnotor** [godotengine/godot#35638]
**Godot version:** 
3.2.rc4.official

**OS/device including version:**
Windows 7 64-bits

**Issue description:**
Drawing a rect2d inside a Control node won't work. 

**Steps to reproduce:**
Add a Control node.
Try to draw a rect using draw_rect() function.
Try the same thing with a Node2D.

**Minimal reproduction project:**
[bugs_testing.zip](https://github.com/godotengine/godot/files/4119487/bugs_testing.zip)

**Comment by SteapaSnotor** [comment]
> The control node is being culled. Change the size to be above zero, or enable "Clip Content" to make its behaviour predictable.
> 
> However, this is a usability problem. I am not sure what the ideal behaviour should be, but I think at least having a Control at `(0,0)` with size `(0,0)` should render (Right now you have to push it up to `(0.5, 0.5)` so it rounds up to `(1, 1)`)

Sorry, I did not know about that. I always drew things on Node2D and I thought the behavior would be the same.

**Comment by nathanwfranke** [comment]
@SteapaSnotor For future reference, this issue should not have been closed since it is a usability issue. However, it seems to be a duplicate of #17917. So for that reason it should be closed and archived.
