### ISSUE TITLE
C# Color constructors from int and long not working for big values

### ISSUE THREAD

**Issue by raulsntos** [godotengine/godot#35636]
**Godot version:**
Godot_v3.2-rc3_mono_x11_64

**OS/device including version:**
Linux (Pop OS 19.10) but should affect every platform

**Issue description:**
`Color` constructors `Color(int rgba)` and `Color(long rgba)` are not working or producing an unexpected `Color` struct because it should be using `uint` and `ulong`:

| Method Call | Expected (r,g,b,a) | Actual (r,g,b,a) | Notes |
| ----------- | -------- | ------ | ----- |
| `new Color(0xffffffff);` | `1,1,1,1` | `0,0,1,1` | Uses `new Color(long)` since the value does not fit in an `int` but should be using `new Color(int)` or rather `new Color(uint)` which does not exist |
| `new Color(0xff0000ff);` | `1,0,0,1` | `0, 0, 0.99610895, 0.0038910506` | Same as before, it uses `new Color(long)` because the value is too big to fit in an `int` |
| `new Color(0x00ff00ff);` | `0,1,0,1` | `0,1,0,1` | Works since the value fits in an `int` |
| `new Color(0x0000ffff);` | `0,0,1,1` | `0,0,1,1` | Works since the value fits in an `int` |
| `new Color(0xffffffffffffffff);` | `1,1,1,1` | - | Does not compile, the value is too `long` to fit in a `long`, would have to use an `ulong` but no constructor exists for that type |
| `new Color(0xffff00000000ffff);` | `1,0,0,1` | - | Does not compile, the value is too `long` to fit in a `long`, would have to use an `ulong` but no constructor exists for that type |
| `new Color(0x0000ffff0000ffff);` | `0,1,0,1` | `0,1,0,1` | Works since the value fits in a `long` |
| `new Color(0x00000000ffffffff);` | `0,0,1,1` | `0,0,1,1` | Works since the value fits in a `long` |

The problem is there is no way to represent colors like white or red since the value is too big to fit in an `int`, so it tries to use the constructor for `long` and when you try to use the `long` version the value that you need to pass to create such colors is too big to fit in a `long`.

The solution would be to change the paremeter type in the constructors to be `uint` and `ulong`, that way we can fit the correct values.

With those constructors C# would automatically use the right version without the need for casting except for small `ulong` values that could be confused with an `uint` (like blue) in which case you would have to specify `new Color((ulong)0x00000000ffffffff)` but it would work.

My proposed solution would be to change these lines:

https://github.com/godotengine/godot/blob/6a5c8c867281fb3ed13cce1e7d9acf287161bc03/modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs#L422

https://github.com/godotengine/godot/blob/6a5c8c867281fb3ed13cce1e7d9acf287161bc03/modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs#L433

To this:
```csharp
public Color(uint rgba)
```
```csharp
public Color(ulong rgba)
```

I can create the PR if this is an acceptable way to fix the bug

**Minimal reproduction project:**
[ColorBug.zip](https://github.com/godotengine/godot/files/4119257/ColorBug.zip)
The project includes 2 scenes (ColorBug and ColorFix) that execute some simple test functions that print to the console the expected and actual values as well as OK or FAIL based on if the expected and actual values are equal or not.
The script attached to ColorFix uses methods to construct the `Color` struct that are copied from Godot source with the parameter type changed as explained above.

**Comment by aaronfranke** [comment]
We have a few options of what we could do here. For one, yes your fix does make sense, and it would be the simplest/best solution from a purely C# perspective.

Since core/Variant/GDScript use `int64_t` as their only integer type, to be consistent it might make more sense to use `long` in this file, which would mean that constructing from `long` uses the lower 32 bits only with red/white colors being positive values, and then of course we would use `ulong` for the 64-bit constructor (note that there is no 64-bit constructor in GDScript, a high-precision color must be constructed from floats in GDScript).
