### ISSUE TITLE
cpp Error when importing .glb or .gltf

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#35637]
**Godot version:**
Any 3.2 Version 

**OS/device including version:**
Linux 5.4.15-arch1-1

**Issue description:**
Error message when importing a .glb or .gltf file:
```
ERROR: store_buffer: Condition ' !p_src ' is true.
   At: drivers/unix/file_access_unix.cpp:278.
```
![Screenshot_20200127_223735](https://user-images.githubusercontent.com/60042618/73216115-a7b67680-4155-11ea-8812-2d24356a827f.png)

**Steps to reproduce:**
Export a .glb or .gltf file from Blender 2.81.a and import into Godot.

**Minimal reproduction project:**
https://github.com/JupiterRider/godot_gltf_import_error

**Comment by fire** [comment]
Your box_2.gltf appears to be missing a .bin file. Will check the glb.

**Comment by fire** [comment]
To be clear the error is the message?

**Comment by fire** [comment]
Godot Engine currently doesn't handle the form:

```

    "buffers" : [
        {
            "byteLength" : 840,
            "uri" : "data:application/octet-stream;base64,AACAPwAAgD8AAIC/AACAPwAAgL8AAIC/AACAvwAAgL8AAIC/AACAvwAAgD8AAIC/AACAvwAAgD8AAIC/AACAvwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIC/AACAvwAAgL8AAIC/AACAvwAAgL8AAIA/AACAvwAAgD8AAIA/AACAvwAAgD8AAIC/AACAvwAAgD8AAIA/AACAvwAAgL8AAIA/AACAPwAAgL8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIC/AACAPwAAgD8AAIA/AACAPwAAgL8AAIA/AACAPwAAgL8AAIC/AACAPwAAgL8AAIC/AACAPwAAgL8AAIA/AACAvwAAgL8AAIA/AACAvwAAgL8AAIC/AAAAAAAAAAAAAIC/AAAAAAAAAAAAAIC/AAAAAAAAAAAAAIC/AAAAAAAAAAAAAIC/AAAAAAAAgD8AAACAAAAAAAAAgD8AAACAAAAAAAAAgD8AAACAAAAAAAAAgD8AAACAAACAvwAAAAAAAACAAACAvwAAAAAAAACAAACAvwAAAAAAAACAAACAvwAAAAAAAACAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AACAPwAAAAAAAACAAACAPwAAAAAAAACAAACAPwAAAAAAAACAAACAPwAAAAAAAACAAAAAAAAAgL8AAACAAAAAAAAAgL8AAACAAAAAAAAAgL8AAACAAAAAAAAAgL8AAACAAAAgPwAAgD4AACA/AAAAPwAAYD8AAAA/AABgPwAAgD4AACA/AAAAAAAAwD4AAAAAAADAPgAAgD4AACA/AACAPgAAID8AAEA/AADAPgAAQD8AAMA+AACAPwAAID8AAIA/AAAAPgAAgD4AAAA+AAAAPwAAwD4AAAA/AADAPgAAgD4AACA/AACAPgAAwD4AAIA+AADAPgAAAD8AACA/AAAAPwAAID8AAAA/AADAPgAAAD8AAMA+AABAPwAAID8AAEA/AAABAAIAAAACAAMABAAFAAYABAAGAAcACAAJAAoACAAKAAsADAANAA4ADAAOAA8AEAARABIAEAASABMAFAAVABYAFAAWABcA"
        }
    ]
```

The gltf2 importer assumes the entire binary data is placed after the json as part of the same binary file or that the data is in a separate bin file.

**Comment by JupiterRider** [comment]
> To be clear the error is the message?

This Error appears in Godot 3.2 RC 3/2, when starting from terminal.  I can always reproduce that error by deleting the .import folder of my project.

Godot 3.1 works fine.

**Comment by Mantissa-23** [comment]
Contributing my repro for this bug:

![image](https://user-images.githubusercontent.com/11467714/83954140-75f4a100-a814-11ea-8225-150a50bf8747.png)

The following simple Blender 2.83 scene structure fails to import into Godot via the `.glb` or `.gltf` formats. Imported in Godot 3.2.1.stable.official.

**Comment by voylin** [comment]
Using Arch Linux and I have the exact same problem, anybody has a fix already for this issue?

**Comment by fire** [comment]
Can you both post reproduction projects? I suspect it's a different cause that the original poster.

**Comment by JupiterRider** [comment]
I think @fire is right! Mine was just one mesh and the import was successful. Just an error message appeared.

I tried my original "Minimal reproduction project" today in Godot_v3.2.2-rc2_mono_x11_64 and the error doesn't appear anymore.
