### ISSUE TITLE
VisibilityNotifier2D not emitting signals when child of PathFollow2D

### ISSUE THREAD

**Issue by benbishopnz** [godotengine/godot#35634]
**Godot version:**
3.2.rc3, 3.2.rc4

**OS/device including version:**
Windows 10, MacOS10.15.2 Catalina

**Issue description:**
I have enemies structured like so:
![image](https://user-images.githubusercontent.com/1631516/73209223-aebca380-41ac-11ea-834d-89410b02f53d.png)
I create the PathFollow2D in code and add it to a Path2D.
When an enemy moves off the screen the VisibilityNotifier2D never emits **screen_exited** or **viewport_exited**. I suspect it is because its parent node's (The Area2D) position never changes from (0, 0).
To test this I changed the Area2D's position manually via the Local tree editor once it had moved offscreen and the VisibilityNotifier2D immediately emitted the correct signal.

I've been using this same code which has worked since 3.0, the regression seems to have occurred in 3.2 somewhere (I think it occurred in 3.2.rc2 as well.)

**Comment by Calinou** [comment]
Can you test this in all older Godot 3.2 alphas and betas? Binaries are available [here](https://downloads.tuxfamily.org/godotengine/3.2/).

**Comment by benbishopnz** [comment]
I tried several versions going back to 3.2.alpha0 and it still happened :(

**Comment by benbishopnz** [comment]
I'm starting to suspect it might have been something I changed somewhere at some point, I can't reproduce easily with a minimal project, and I think this was previously working in a 3.2 beta build at some point.

**Comment by benbishopnz** [comment]
Alright, I figured out what was causing this, and I am fairly sure it is a regression in 3.2 (I tried an older build of my game and confirmed it didn't happen in it.)

- I made the Rect size of the VisibilityNotifier2D bigger to better match the size of my enemy - I'm not sure if this is a relevant detail or not. 
- If the PathFollow2D containing the VisibilityNotifier does not go far enough off the screen then the signals mentioned above do not emit. I'm positive the VisibilityNotifier is completely off the screen, but it doesn't trigger until it goes much further off the screen.
- I added some points to my paths to make them go way off the screen to make sure it triggered which fixed my game.

**Comment by tom-jk** [comment]
From [the docs](docs.godotengine.org/en/stable/classes/class_visibilitynotifier2d.html):

> Note: For performance reasons, VisibilityNotifier2D uses an approximate heuristic with precision determined by ProjectSettings.world/2d/cell_size. If you need exact visibility checking, use another method such as adding an Area2D node as a child of a Camera2D node.

so, having to go a bit further out of the screen for it to signal is expected and normal.

Minimal reproduction project: [35634.zip](https://github.com/godotengine/godot/files/4915472/35634.zip)
This is based on the given screenshot/description. Main.tscn has the nodes in the scene, Main2.tscn makes them in code.

@benbishopnz is this issue resolved for you?

**Comment by benbishopnz** [comment]
The issue still exists in the sense that something changed between versions (ie. something used to work, I upgraded version and it stopped working.)
That said, the problem I was having in my project has been resolved, so I will close this issue.
