### ISSUE TITLE
ERROR: set_item_checked: Index p_idx out of size (items.size()).

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3564]
I often see in console:
```
ERROR: set_item_checked: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:591.
ERROR: select: Index p_idx out of size (items.size()).
   At: scene/gui/item_list.cpp:177.
ERROR: get_item_metadata: Index p_idx out of size (items.size()).
   At: scene/gui/item_list.cpp:171.
ERROR: select: Index p_idx out of size (items.size()).
   At: scene/gui/item_list.cpp:177.
ERROR: get_item_metadata: Index p_idx out of size (items.size()).
   At: scene/gui/item_list.cpp:171.
```

Looks like I am not the only one:
https://github.com/godotengine/godot/issues/3522

but nothing crushing here. Godot is stable.

CPU: AMD C-60 APU with Radeon HD 6290 Graphics (proprietary drivers). Running Xubuntu 14.04 64-bit.

**Comment by Algrin6** [comment]
I confirm this bug. I can add that there are no any menus at the moment. It happens when starting and closing the game from the editor.

**Comment by reduz** [comment]
most importantly, how do you reproduce it?

**Comment by akien-mga** [comment]
For me, just by starting or quitting a game from within the editor:
```
/// Start
running: /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64 -path /home/akien/Projects/kobuge/project-kumquat -rdebug localhost:6007 -p 0x0 res://main/menu.tscn
ERROR: set_item_checked: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:591.
********* listening on port 6007
OK! 11
has connection!
has connection!
/// Quit
pre-removing print handler...
removing print handler...
found
print handler list is (nil)
CLOSING CONNECTION
ERROR: set_item_checked: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:591.
ERROR: set_item_checked: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:591.
```

**Comment by freemanfromgodotengine** [comment]
The same here. Errors appear at playing the project (F5) or after stopping it (F8).
With head from two days ago, starting always brings:

> ERROR: set_item_checked: Index p_idx out of size (items.size()).
>    At: scene/gui/popup_menu.cpp:591.
> ********* listening on port 6007
> OK! 24
> has connection!
> has connection!

and stopping

> CLOSING CONNECTION
> ERROR: set_item_checked: Index p_idx out of size (items.size()).
>    At: scene/gui/popup_menu.cpp:591.
>

**Comment by akien-mga** [comment]
ping @reduz, one cosmetic bug annoying bug that we could do without for 2.0.

**Comment by nunodonato** [comment]
I get this too
