### ISSUE TITLE
Godot editor only redraws screen when window resized

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#35640]
**Godot version:**
v3.2.rc.custom_build.40c659867 , also present on 3.1 and 3.2 beta
**OS/device including version:**
Manjaro Linux
**Issue description:**
On launch Godot is frozen on the splash screen.

Screenshot:
![image](https://user-images.githubusercontent.com/28424206/73220556-92205d00-4113-11ea-8d42-fc05ddb41b32.png)

Here is the verbose logs:
```➜  bin git:(master) ./godot.x11.tools.64 -v
Godot Engine v3.2.rc.custom_build.40c659867 - https://godotengine.org
XInput: Refreshing devices.
XInput: Using touch device: Virtual core pointer
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Only one GPU found, using default.
Failed loading custom cursor: X_cursor
Using GLES3 video driver
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) UHD Graphics (Ice Lake 4x8 GT1) 
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
 
CORE API HASH: 4727206355675663924
EDITOR API HASH: 6320410190936379010
Loading resource: /home/creikey/.config/godot/editor_settings-3.tres
EditorSettings: Load OK!
EditorSettings: Save OK!
Loaded builtin certs
```
**Steps to reproduce:**
Run godot from the command line
**Minimal reproduction project:**
No project needed

**Comment by Calinou** [comment]
Does it display correctly if you resize the window?

**Comment by creikey** [comment]
Yes @Calinou

**Comment by creikey** [comment]
Even when update continuously is checked the issue persists

**Comment by creikey** [comment]
Input events are still processed.

**Comment by creikey** [comment]
Issue is also present in Visual Studio Code, but not applications like firefox or the terminal on GNOME, closing this issue as this seems to be a bug in X11 although I'm not sure how to fix it...
