### ISSUE TITLE
Can't shift+mouse select multiple files to import.

### ISSUE THREAD

**Issue by animanoir** [godotengine/godot#35645]
**Godot version:** 3.1.2

**OS/device including version:** Windows 10

**Issue description:**

I'm trying to import some .png images to an `AnimatedSprite ` node, but Godot's own "file management system" doesn't let me _shit+mouse select_ multiple files at once, therefore I can only just import 1.

**Steps to reproduce:**

1. AnimatedSprite > Inspector > "Load an existing resource..."

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is expected. A SpriteFrames resource is a single resource, not a set of images. It can however *contain* a set of images. Create a new SpriteFrames resource and edit it. Then click the **Add a Texture from File** button:

![image](https://user-images.githubusercontent.com/180032/73285297-18ad6b00-41f6-11ea-8213-6b0ebc5cbabf.png)

**Comment by animanoir** [comment]
Thanks. I was following a really old tutorial then.
