### ISSUE TITLE
Smart Snap (Shift+S) flipping & doesn't toggling sometimes

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#35642]
**Godot version:**
3.2-rc4

**OS/device including version:**
Windows 10

**Issue description:**
Smart Snap sometimes inverts it's value and/or only toggles when Shift+S is inputted twice.
I don't know exactly what's triggering this so I made this gif showing what happens

**Steps to reproduce:**
![SmartSnap](https://user-images.githubusercontent.com/37383316/73226637-979b9880-414f-11ea-9011-c2c97cbfe69d.gif)

Also it seems that the "Use Rotation Snap" option is inverted
![SnapRot](https://user-images.githubusercontent.com/37383316/73227919-df242380-4153-11ea-8b6c-cad97c5a6630.gif)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @groud

**Comment by groud** [comment]
The first issue is unclear, it's hard to tell what is happening without clear reproduction steps.
And yes, the second issue is due to the fact the CTRL key toggles the snapping status temporarily, so you have to release control once you activated the rotation.

**Comment by Muller-Castro** [comment]
Snap icon on but snapping off:
![Cut](https://user-images.githubusercontent.com/37383316/73287583-37046e00-41d8-11ea-97bd-fd473fed2f85.gif)

Shift+S having to be inputted twice to toggle the snap icon
![Cut2](https://user-images.githubusercontent.com/37383316/73288121-2a344a00-41d9-11ea-8634-d319b85a2038.gif)

Snap icon toggles with Shift+S but its snap value doesn't change
![Cut3](https://user-images.githubusercontent.com/37383316/73288661-27862480-41da-11ea-9b7a-2e0d02c646a7.gif)

**Comment by KoBeWi** [comment]
I can't reproduce this. Also I remember snapping got some improvements since then, so it's likely fixed. Comment if you can still reproduce in Godot 3.2.3.
