### ISSUE TITLE
Unable to scroll script editor horizontally with mouse horizontal scrolling feature

### ISSUE THREAD

**Issue by kirilledelman** [godotengine/godot#3565]
When editor ends up being scrolled horizontally ( when editing a very long line in smaller window, for example ), horizontal scroll bar does not appear on the bottom of the window, nor is it possible to use horizontal scrolling mousewheel to scroll back to the beginning ( or a Magic Mouse touch-scrolling on a Mac ).

**Comment by akien-mga** [comment]
I can't reproduce this on Linux, I guess you got the issue on Mac OSX since you mention Magic Mouse touch-scrolling?

**Comment by kirilledelman** [comment]
A way to reproduce it would be:
* Resize the editor to be pretty narrow ( let's say 1024px or so ), and switch to Script tab to show script editor.
* Type a long line in the editor, that would cause the caret to go past the right edge, resulting in editor auto-scrolling to the right to show the caret.

I don't know about other OSes, but on a Mac, no horizontal scrollbar appears for the script editor. It's also not possible to scroll horizontally, using your mouse wheel ( well, Magic Mouse - which uses the mouse surface as a scrolling pad, not mouse wheel per se ). The only way to scroll back to the far left is using keyboard arrow keys.

**Comment by Calinou** [comment]
I can confirm that horizontal mouse scrolling is not supported in Godot. (Fedora 23)

**Comment by Hinsbart** [comment]
Seems like we only have support for `BUTTON_WHEEL_UP` and `BUTTON_WHEEL_DOWN` events. I'll look into it ^^

**Comment by kirilledelman** [comment]
Thank you!

**Comment by Hinsbart** [comment]
@kirilledelman you're using a mac right? Is it working? ^^

**Comment by kirilledelman** [comment]
Is there an easy way for me to get latest Mac binary without having to build it myself?

**Comment by kirilledelman** [comment]
Yay, you did it. Thank you.

**Comment by Hinsbart** [comment]
awesome :)
