### ISSUE TITLE
Line2D rendered at the wrong position

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#35661]
**Godot version:** 3.2 rc4

**OS/device including version:** Win

**Issue description:**
Child Line2D will draw at the wrong position when parent was moved

**Steps to reproduce:**
Create new Node2D scene
Add Sprite node add texture to Sprite
Add Line2D node as child to Sprite node
Move Sprite with the viewport move tool
Add this script to Sprite node:
```
extends Sprite

onready var line = $Line2D

func _ready():
	line.add_point(global_position)
	line.add_point(get_global_mouse_position())
	line.width = 2

func _physics_process(delta):
	line.points[1] = get_global_mouse_position()
```
play scene:
![Line2D_bug](https://user-images.githubusercontent.com/47016402/73271112-4e475980-41e0-11ea-983b-bac015fe6f12.gif)
The result is the same when the steps are done in a different order, like when the Sprite is moved as a last Step or the script added as a 3rd step.
Line2D will draw at the right position again when the parent node position is reset to Vector2(0,0).

**Minimal reproduction project:**
[Line2D_bug.zip](https://github.com/godotengine/godot/files/4122784/Line2D_bug.zip)

**Comment by akien-mga** [comment]
That's not a bug, you're using global positions as input for a feature which expects local positions. The code is in Sprite's script, so it's relative to Sprite's position.

This works fine:
```gdscript
extends Sprite

onready var line = $Line2D

func _ready():
	line.add_point(Vector2(0, 0))
	line.add_point(get_local_mouse_position())
	line.width = 2

func _physics_process(delta):
	line.points[1] = get_local_mouse_position()
```

**Comment by golddotasksquestions** [comment]
That totally makes sense. Thy Akien

**Comment by golddotasksquestions** [comment]
@akien-mga  The more I think about it the less sense it makes:
```
extends Sprite

onready var line = $Line2D

func _ready():
	line.add_point(Vector2(0, 0))
	line.add_point(get_local_mouse_position())
	line.width = 2

func _physics_process(delta):
	line.points[1] = get_local_mouse_position()
```
get_local_mouse_position() gets the global position of the mouse cursor. If the points would only interpret the Vector2s assigned to them as local coordinates, get_local_mouse_position() would have to result in an offset as well, but it does not.

**Comment by akien-mga** [comment]
It is working properly.

I advise taking a piece of paper and actually laying out the 2D vectors. You're still thinking in terms of global coordinates, but your origin is the center of Sprite, and you're drawing a line from point 0 (origin, aka center of Sprite) to point 1 (local position of mouse relative to the Sprite, which happens to be the origin).

If your Sprite is at position (100, 100), and the mouse is at the global position (300, 400), i.e. (200, 300) as local position in the Sprite script, the line will be drawn from local (0, 0) to local (200, 300), i.e. a (200, 300) vector starting at (100, 100).

**Comment by akien-mga** [comment]
BTW, the positions you see in the inspector are not global positions. They're the local position with regard to their parent node.

Sprite is at position 200, 150 in Node2D's referential. If you move Node2D, Sprite's `position` (local) will be preserved. Its global position will change. That's why most code uses local positions so that it's independent of movement of the parent nodes.

**Comment by golddotasksquestions** [comment]
Well I know about the basics of Vector addition, but this makes no sense to me as get_global_mouse_position() as the name implies gets the global_position vector. It even says so in the documentation https://docs.godotengine.org/en/3.1/classes/class_canvasitem.html#class-canvasitem-method-get-global-mouse-position
Is the documentation not correct?

**Comment by akien-mga** [comment]
Yes, but the fixed code I gave you, and the one you're testing, does **not** use `get_global_mouse_position()`...

**Comment by golddotasksquestions** [comment]
Sorry for the inconvenience, this was my oversight.
