### ISSUE TITLE
Label set_percent_visible is not correct if there are spaces in the text

### ISSUE THREAD

**Issue by johnnygossdev** [godotengine/godot#35668]
**Godot version:**
3.2.rc4

**OS/device including version:**
pop_os!

**Issue description:**
The difference between 99% and 100% is not correct. The extra 1% adds way too many characters.
![label-bug](https://user-images.githubusercontent.com/3285214/73292326-c66e4900-41f9-11ea-8d50-55ea6b87ceca.gif)

Of note this is not an issue with text without spaces.

I think it's because `total_char_cache` in `lable.cpp` skips over `" "` and this isn't taken into account when setting the value but I'm not overly familiar with the engine.

**Steps to reproduce:**
Have a label and write text with spaces in the text. Alter the percent visible value as above.

**Comment by akien-mga** [comment]
Confirmed, that's a regression from #34874.
