### ISSUE TITLE
Compiler Error on Custom Module

### ISSUE THREAD

**Issue by primesoftware** [godotengine/godot#3566]
I am getting the following error for a module I'm working on:

```
modules/NewHTTPClient/src/NewHTTPClient.cpp: In static member function 'static void NewHTTPClient::_bind_methods()':
modules/NewHTTPClient/src/NewHTTPClient.cpp:301:73: error: cannot call member function 'bool NewHTTPClient::configureTLS()' without object
  ObjectTypeDB::bind_method("configureTLS",&NewHTTPClient::configureTLS());
                                                                         ^
modules/NewHTTPClient/src/NewHTTPClient.cpp:302:83: error: cannot call member function 'void NewHTTPClient::startDataTransfer()' without object
  ObjectTypeDB::bind_method("startDataTransfer",&NewHTTPClient::startDataTransfer());
```

The module works fine in my test with a main function, but plugging it into Godot is a hangup for me. Any ideas?

**Comment by akien-mga** [comment]
Search for "bind_method" in the GitHub repo to see how the syntax should be, you got it wrong :)

**Comment by reduz** [comment]
ObjectTypeDB::bind_method("startDataTransfer",&NewHTTPClient::startDataTransfer())
 <- extra () at the end of function reference

**Comment by primesoftware** [comment]
@reduz Ahhh.....such a stupid error on my part. Coding at 1AM after rocking an almost 1 year old is never a good idea.....
