### ISSUE TITLE
Right panel extreme resizing problem.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3567]
Head compiled few minutes ago. When the right panel (Inspector panel by default I think) is extremely resized to the left side by clicking, holding and dragging, the resize edge between the panel and editor window is not visible anymore. 
The problem appears when to edge starts to overlap icon/menu/tabs of the editor's section of the screen, to be exact.
When mouse holding is released in that position, the right panel resizing is not possible from that point, because panel edge is not visible.
The only way user can get the edge of the Inspector panel back is to open animation editor, debugger or output console that creates an edge between panels.

Probably related to https://github.com/godotengine/godot/issues/3565

**Comment by akien-mga** [comment]
I can confirm this on Linux.
