### ISSUE TITLE
Images with "Gray" colourspace don't render correctly

### ISSUE THREAD

**Issue by atoms118** [godotengine/godot#35681]
**Godot version:**

3.1.2

**OS/device including version:**

Gentoo, Thinkpad /w RX Vega 10 graphics

**Issue description:**

Images using the "Gray" colourspace, with only black and white, do not render correctly. They are loaded as a solid black rectangle. Adding additional shades to the image causes it to be displayed correctly.

**Steps to reproduce:**
![test image](https://framapic.org/4FZ1RwC0sWOH/QoAA97Tl6o83.png)

When displayed correctly, various white pixels should be visible. When loaded into Godot, they are not visible. Note that the small size of the pixels has no effect; adding larger shapes to the image has the same effect, so long as the image exclusively uses black and white.

This image was generated using `convert "stars.xcf[0]" "stars0.png"`. This took a layer from an XCF file, created with GIMP, and converted it to a PNG. Images created this way work fine in programs other than Godot, and work fine in Godot when colours other than black and white are present in the image.

**Comment by Zylann** [comment]
Could not reproduce in editor 3.2 rc4, Windows 10 64 bits. I downloaded the PNG from here though, it miiight have been processed by Github's image service.

**Comment by atoms118** [comment]
Just to confirm, I downloaded the image from GitHub and was able to reproduce again, so I don't think GitHub's image service has messed it up

**Comment by clayjohn** [comment]
@atoms118 can you try in 3.2 beta 4 then? Maybe it's already fixed!

**Comment by atoms118** [comment]
The bug is fixed in 3.2 beta 4, thank you for your patience
