### ISSUE TITLE
gdscript reading an elif statement after if statement has already been met

### ISSUE THREAD

**Issue by bnicholl** [godotengine/godot#35683]
I have a function, _input() that causes my character to go left when I press the left arrow on my keyboard

```
var velocity = Vector2(0, 0)
var x_vel = 0

func  _physics_process(delta):
	velocity.y += 800 * delta
	velocity.x += x_vel
	# first argument is how the object moves, second parameter is how the object moves
	# if it hits something 
	velocity = move_and_slide(velocity, Vector2(40, -1) )


func  _input(event):
	if event.is_action("moveLeft"):
		if event.is_pressed():
			x_vel = -20
			
		elif x_vel < 0:
			x_vel = 20
```

When I press the left arrow, the character begins to go left, thus signifying that the if statement in
```
if event.is_pressed():
	x_vel = -20 
```
has been met, and therefore, 
```
elif x_vel < 0:
	x_vel = 20
```

Should not be read. This is not the case. My character goes left for a split second, then the elif statement seems to get read, causing my character to begin moving right. If I remove this elif statement, the code works fine.

**Comment by volzhs** [comment]
try to print out what event is by `print(event.as_text())`

**Comment by pycbouh** [comment]
If I understand your code correctly, then you actually handle two separate events in a succession. You say that you visibly notice your character going in the right direction, and then changing it. It could not have happened during one execution of `_input` function. You receive `moveLeft` action twice in a row, but the second time it is not pressed anymore, so instead you check for `x_vel` being negative.

If you want to check if the action was *just* pressed, you should filter your events out with `InputEvent.is_echo` method:
https://docs.godotengine.org/en/3.1/classes/class_inputevent.html#class-inputevent-method-is-echo

Either way, something is not right with the logic you present, as this code will autocorrect each negative `x_vel` into a positive one the next tick after it gets set. So each time you press left arrow key, you get one move left and then indefinitely move right.

**Comment by akien-mga** [comment]
Indeed, the problem is in the project's code, not the engine.
