### ISSUE TITLE
Two major UI issues with the shader visual node editor.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#3568]
This being present in very recent builds (newer than the beta).

**Bug # 1**
-------------------------------------------
When making a very long connection between an output socket and an input socket, the node editor view will scale 2x on the X axis (and then snap back when you do another edit).

**Bug # 2**
-----------------------------------------------
Whenever a node is deleted, it will immediately invoke a grab operation on a random node and give it an offset relative to the mouse (deleting a selection should leave nothing selected and movable because what was selected was deleted).

_________________________________________________

These two bugs should be very simple to reproduce as you don't need any specific setup. These are also confirmed on a machine with Windows10 64 bit, an ATI 7xxx GPU with the Crimson drivers, a third-gen i7 GPU, and 24 gigs of RAM. I was also using the shader node editor by the way.

Hope this can be confirmed on your side and fixed.

Thanks.

**Comment by ni-code** [comment]
I can confirm this, in Ubuntu 15.10.

**Comment by MarianoGnu** [comment]
I couldn`t reproduce these bugs, can you give a better description on how to do it?
i tryed long conections with and without scaling the zoom and also deletting selected nodes worked fine to me.
I tryed both Win7 and Win10

i have a different issue thought, where the position of some node changes unexpectedly

**Comment by MarianoGnu** [comment]
Maybe this should be worked rewriting the update block in GraphEditEditorPlugin, since it deletes and recreates all nodes in the graph every time something changes...

**Comment by Ace-Dragon** [comment]
"i have a different issue thought, where the position of some node changes unexpectedly'

I think what you found may have actually confirmed the problem, perhaps it might be the bugs only occur when the nodes in question have connections?

**Comment by MarianoGnu** [comment]
what visual editor are you using? is it shader visual editor?

**Comment by Ace-Dragon** [comment]
I'm using the shader visual editor.

**Comment by MarianoGnu** [comment]
i just tested and there's still some cases where creating/deleting new nodes change other nodes positions and sometimes are moved along with the mouse, So i'm reopening this issue.

**Comment by akien-mga** [comment]
Closing as duplicate of #4433 for "Bug 2" (if the "Bug 1" part of the OP is still valid, please open a new issue for it, having several bugs in one issue is harder to work with).
