### ISSUE TITLE
Unable to move imported materials from glTF

### ISSUE THREAD

**Issue by Shatur95** [godotengine/godot#35697]
**Godot version:**
68eae6b6e

**OS/device including version:**
Arch Linux

**Issue description:**
When moving materials imported from glTF, their paths for the model are not updated and I get "Broken dependencies". If I try to fix the paths manually through the "Edit Dependencies" menu, then they are not saved.

**Steps to reproduce:**
1. Download [Strump.blend](https://github.com/Zoriya/asset-sources/blob/master/Objects/Vegetation/Trees/Strump.blend)
2. Open in Blender.
3. Export as glTF.
4. Import to Godot.
5. Move or rename materials that imported with model.
6. Press "Edit Dependencies" on imported models.
7. You will see broken dependencies (I would expect automatic path updates).
8. Try to fix this manually by specifying the correct path by clicking on the folder icon.
9. You will see that the updated path will not be saved.

**Minimal reproduction project:**
[Unable to move imported materials from glTF.tar.gz](https://github.com/godotengine/godot/files/4128264/Unable.to.move.imported.materials.from.glTF.tar.gz)

**Comment by Shatur95** [comment]
As a temporary solution to the problem, you can import the meshes in separate files, then the assigned materials will be saved during re-import. This is not very convenient, because there will be 2 times more files and all materials must be assigned manually. But it works :)

**Comment by Shatur95** [comment]
I was mistaken about the temporary solution. Meshes with several material slots must be imported with the materials, otherwise only one slot will be available. But if you import with materials, after re-importing the materials will be placed in the old place. So every reimport I need to remove created material files and specify correct path to moved material.
This is very inconvenient. For example, if I have wood material - I can't share them between several models. So, it looks like GLTF is not very usable in Godot for me.

**Comment by fire** [comment]
Consolidating into https://github.com/godotengine/godot/issues/42278.
