### ISSUE TITLE
Export templates manager buttons go out of bounds after installing template

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#35695]
**Godot version:**
3.2

**OS/device including version:**
Windows 10 x64

**Issue description:**
I thought that it was already reported, but I can't find the issue now, soo
![image](https://user-images.githubusercontent.com/2223172/73359177-87df9980-42a0-11ea-8821-fe3a6b271bd4.png)

**Steps to reproduce:**
1. Open Export Templates Manager
2. Install templates

This only happens if the templates weren't installed and is probably caused by the appearance of the second button.

**Comment by Calinou** [comment]
This is probably caused by the translation text being too long. We could increase the width of the export template manager dialog to solve this.

**Comment by KoBeWi** [comment]
The thing is that after you close and reopen it, the buttons are correctly inside. So it looks like the size updates incorrectly (i.e. not at all).

**Comment by Calinou** [comment]
@KoBeWi Indeed, I've had this issue while working on #35568 but I don't know how to fix it.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by KoBeWi** [comment]
Although this is fixed in 4.0, so it should be fine to close this (it's not a critical issue).
