### ISSUE TITLE
"HSV" and "Raw" text in ColorPicker are not appearing on export (Tested on Windows)

### ISSUE THREAD

**Issue by OverloadedOrama** [godotengine/godot#35693]
**Godot version:**
3.2.stable

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
When exporting a project that has ColorPicker (or ColorPickerButton) nodes, the "HSV" and "Raw" text do not appear, but they do when running the project inside Godot. I've only tested it in **Windows Desktop** so far. It looks like this 
![image](https://user-images.githubusercontent.com/35376950/73358345-148d5600-42a7-11ea-8ad4-73d21c1fcbbe.png)

**EDIT**: I tested it on HTML5 too, same problem there.

**Steps to reproduce:**
Create an empty project, add a ColorPicker or ColorPickerButton node and run it. You'll see the "HSV" and "Raw" text as it's supposed to be. Then, export it to Windows. The text does not appear and it just shows two On/Off buttons without text, like the image I uploaded above.

**Minimal reproduction project:**
[Godot 3.2 Color Picker export problem.zip](https://github.com/godotengine/godot/files/4128040/Godot.3.2.Color.Picker.export.problem.zip)

**Comment by Calinou** [comment]
I wonder if this is caused by the CheckButton texture taking too much space and hiding the texts. Try replacing it by a 1×1 texture in the theme.

**Comment by OverloadedOrama** [comment]
@Calinou I tried changing the "Off" icons of the CheckButton nodes to a 1×1 texture in the theme like you suggested, but the problem still occurs. The text appears fine when running the game inside the editor, but does not appear when exporting (to Windows at least) or when running the project on a browser (tested only in Chrome). Could this be an issue with the export templates?

**Comment by Calinou** [comment]
@OverloadedOrama If the export template versions match the editor version exactly, there shouldn't be any issue with them.

**Comment by Calinou** [comment]
@OverloadedOrama Can you (or anyone else) still reproduce this bug in [Godot 3.2.3](https://godotengine.org/article/maintenance-release-godot-3-2-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by OverloadedOrama** [comment]
> @OverloadedOrama Can you (or anyone else) still reproduce this bug in [Godot 3.2.3](https://godotengine.org/article/maintenance-release-godot-3-2-3) or any later release?

@Calinou Yes, the bug can still be reproduced in Godot 3.2.3. I tested it both with the minimal project I uploaded, and with Pixelorama's GitHub Actions builds.
