### ISSUE TITLE
Stack Underflow (Engine Bug) on yields.

### ISSUE THREAD

**Issue by acedogblast** [godotengine/godot#35705]
**Godot version:** v3.2.stable.official (Works on v3.1.2.stable)

**OS/device including version:** Linux/GNU Kubtunu 19.04

**Issue description:** This bug occurs after a large complex sequence of yields and signals in my group's project.  It may be related to issues #30269 and #31455 since the error message in the editor is "Stack Underflow (Engine Bug)".

The only error in the errors tab is:
E 0:00:34.283   _disconnect: Disconnecting nonexistent signal 'loop_end', slot: 2474:_signal_callback.
  <C++ Error>   Condition "!s->slot_map.has(target)" is true.
  <C++ Source>  core/object.cpp:1522 @ _disconnect()
  <Stack Trace> BattleBars.gd:83 @ slide_player_exp_bar()

The confusing thing is that the signal 'loop_end' is not part of BattleBars.gd and we are not disconnecting any signals in our code. Again, this bug is not present in version 3.1.2. 

**Minimal reproduction project:** We have not been able to recreate this bug in a minimal project yet.

**Comment by acedogblast** [comment]
Using `call_deferred()` fixes our problem. Closing.

**Comment by avnerh1** [comment]
> Using `call_deferred("method")` before yield fixes our problem. Closing.

I have the same problem. I couldn't understand what the solution is. Can you provide a short code example with the solution you suggested?

**Comment by acedogblast** [comment]
call_deferred(string) is a Godot Object function that calls a specified function during the idle time of the node. It fixed our problem because the function I needed to call is part of a separate node than the one the code is in. The reason why it fixed our problem is that sometimes the node we are trying to call already finished its task and can not be updated in the current frame so call_deferred will make it so that that node on the next frame will then run that specified function.
