### ISSUE TITLE
HTML5 template should notify user when WebGL support is missing

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3570]
When trying to run an export game using the 2.0-beta HTML5 template, I get:

```
has res dir: 
exists engine cfg? 0
loaded engine.cfg
Init OS
Could not create canvas: ?,:(,{"antialias":false,"alpha":false,"depth":true,"stencil":false,"majorVersion":1,"minorVersion":0}
Init Audio
Init VS
```

And no canvas is shown, instead: "Exception thrown, see JavaScript console".

It would be nice to get this one fixed for 2.0, as currently it seems HTML5 is completely broken.

I tested this with two projects so far:
- https://github.com/bojidar-bg/top-down-inertia (uses the TSCN format, converted on export to SCN)
- https://github.com/KOBUGE-Games/minilens (uses the XML format, also converted on export to SCN I guess)

**Comment by reduz** [comment]
sounds like an emscripten error,  does your browser have webgl enabled?

**Comment by akien-mga** [comment]
> does your browser have webgl enabled?

I'll check that tonight, it was with Firefox 44.0 in safe mode (in normal mode by ad blocker makes the game use up all my CPU + RAM + fill up the swap and I almost get a deadlock :D).

I'll also upload a project so that other users can try to confirm the bug.

**Comment by kakoeimon** [comment]
Just got "deadlock" and had to restart my pc with top-down-inertia and kinematic character demo.
But runs with Chromium.
WebGL is enabled in both browsers.

**Comment by reduz** [comment]
worst case we should add webgl detection in html template

**Comment by akien-mga** [comment]
> Just got "deadlock" and had to restart my pc with top-down-inertia and kinematic character demo.

Try in safe mode or after disabling your ad blocker, it should run better.

**Comment by Hinsbart** [comment]
I also got this using firefox on my laptop, while it's working on the desktop.
Both systems are running arch, so they have the same versions.

Also, chromium works fine on both machines.

**Comment by akien-mga** [comment]
For me chromium doesn't work either, it seems to just get stuck at "Download data...", it doesn't get past it even after 15 min.

**Comment by kakoeimon** [comment]
I forgot to say that I tested this on a laptop. 
I tried firefox in safe mode to run it and I got the same message as akien-mga said.
But after the msg I got and this msg
"Error: WebGL: WebGL creation is disabled, and so disallowed here."
So I tried and some three.js demos in safe mode and I got again
"Error: WebGL: WebGL creation is disabled, and so disallowed here."
I think the error msg is caused cause in safe mode Add-ons are Disabled.
But this does not explains the "deadlock" in normal mode where WebGL is working.

**Comment by akien-mga** [comment]
> I think the error msg is caused cause in safe mode Add-ons are Disabled.

Ah right so WebGL might be disabled in safe mode. Do you confirm the "ad blocker causes a deadlock" theory? I'll try disabling my ad blocker completely and run a game in non-safe mode to see how it behaves.

**Comment by kakoeimon** [comment]
I cannot confirm that "ad blocker causes a deadlock". I have no Add-ons installed in my firefox. Unless this is a build in function which I am not aware of.

**Comment by reduz** [comment]
I think we should add a nerw feature like "HTML5 exporter should warn the
user if WebGL is disable and explain how to enable it" or something like
this?

**Comment by akien-mga** [comment]
This was indeed due to missing WebGL support. As reduz mentioned, we could add a feature that detects this and warns the user, so adapting milestone and title accordingly.

**Comment by reduz** [comment]
yes but it must be done on the HTML5 template, not inside Godot..

**Comment by djrm** [comment]
this may be moved to a later godot version since webgl will be reworked.
