### ISSUE TITLE
Godot give error "missing scripts_meta file" when try to export without C# script.

### ISSUE THREAD

**Issue by faxfrag** [godotengine/godot#35707]
**Godot version:**
3.2 mono stable

**OS/device including version:**
Windows 10 1903

**Issue description:**
Godot give an error saying ` modules/mono/glue/gd_glue.cpp:250 - Failed to export project: Could not find file "D:\My Documents\Godot\Test3D\.mono\metadata\scripts_metadata.debug"
` when try to export a project that doesn't have at least one .cs script file

**Steps to reproduce:**
1. Create new mono project
2. Try putting something into a new scene but without C# script, save
3. Try exporting to Windows Desktop

**FIX**
create at least one C# script.

**Comment by cgbeutler** [comment]
I am getting this error even with .cs scripts.  I have turned off the `Auto Update Project` setting and added:
```
  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <PackageReference Include="Newtonsoft.Json"> <Version>12.0.3</Version> </PackageReference>
    <Compile Include="$(ProjectDir)\mono\**\*.cs" />
    <Compile Include="$(ProjectDir)\scenes\**\*.cs" />
  </ItemGroup>
```
It runs in editor, but maybe that is making things undetectable? I don't know. I'll keep poking around and update this comment as I find more.

**Comment by NeverEnd-Exe** [comment]
Any updates on this? I am having the same issue...

**Comment by Calinou** [comment]
> Any updates on this? I am having the same issue...

As far as I know, nobody found a solution to this yet.

**Comment by raulsntos** [comment]
Can anyone still reproduce this issue in Godot 3.5 or any later release? If so, please upload a minimal reproduction project since I have been unable to reproduce this myself.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
