### ISSUE TITLE
Clicking on node with unselectable children will select it even if it's locked

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#35703]
**Godot version:**
3.2

**Issue description:**
When you click a child of node with unselectable children, the parent node is selected instead. I guess this is intended, but what probably isn't is the fact that the node gets selected even if it's locked from selection.

**Steps to reproduce:**
1.
![image](https://user-images.githubusercontent.com/2223172/73375426-1281c200-42bc-11ea-8bfc-afc0f7bce046.png)
2. Click on the sprite
3. Node2D gets selected even though it's locked

**Comment by tom-jk** [comment]
Can't reproduce in 3.2.2.stable.

![Godot35703_Screen](https://user-images.githubusercontent.com/64640811/87563560-4a889000-c6b7-11ea-9217-190c9b2fadc3.png)
(the blue rectangle is the selection marquee)

**Comment by KoBeWi** [comment]
Yep, fixed. Thanks for testing.
