### ISSUE TITLE
TouchScreenButton - Shape Centered property is reversed in 3.2

### ISSUE THREAD

**Issue by AdamA9** [godotengine/godot#35711]
Hi

All my TouchScreenButton Nodes are offset due to reversal in behavior of the "Shape Centered" property. when it set it as false it puts them as centered and all of them used to be "true" in 3.1.2

**Comment by KoBeWi** [comment]
The doc about this property says

_If true, the button's shape is centered in the provided texture. If no texture is used, this property has no effect._

I checked and that is the observed behavior. If it was different in 3.1, it was most likely a bug.

**Comment by AdamA9** [comment]
yeah, my ported project from 3.1.2 had that set to true and now everything is not centred.
if I put it on false (uncheck) it is re-centered, if I check it again (true) it is offset to the corner.
new projects don't have that I guess

**Comment by KoBeWi** [comment]
You mean centered on the corner or centered on the texture?
Also any chance you can make a reproduction project?

**Comment by AdamA9** [comment]
I'm new here. not sure about what is a reproduction project... 
here is a video of how it behaves in a fresh project inside 3.2: https://streamable.com/hzon4
it worked in reverse in 3.1.2 and now all the nodes across my project needs to be set again manually one by one

**Comment by KoBeWi** [comment]
> not sure about what is a reproduction project...

It's a minimal test project that reproduces the issue. In your case it would be some project with the inverted behavior you describe. Obviously you can't show the whole game, but maybe you can extract a scene from your project, which has this bug. Or somehow manage to make a new project that reproduces this.

Not sure about your bug, but there seems to be another one. `shape_centered` is supposed to have no effect without texture, so it's either documentation mistake or something is wrong.

**Comment by AdamA9** [comment]
like this? 
https://drive.google.com/drive/folders/1w5s8B_324-XuNFqNTyRJ5kDQca1dtSqk?usp=sharing

**Comment by KoBeWi** [comment]
Ah wait, the video was enough actually. I missed that it's the unwanted behavior.

So yeah, the shape should always stay at (0,0) when the button has no texture. At least according to documentation.

**Comment by AdamA9** [comment]
Not sure if this is the place to ask, but I've just learned how to compile the source code with scons.
How does one go about fixing issues like that and providing the "commits" for it for everyone else to have them too?

**Comment by KoBeWi** [comment]
See https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html
Also the two PRs I linked in my previous comment. The problem would be somewhere in that file probably.

**Comment by Plopsiskopsis** [comment]
I created a TouchScreenButton like this
![image](https://user-images.githubusercontent.com/35765659/74084002-dba56c00-4a72-11ea-9f78-a1830ae0f522.png)

And the area did not seem to be doing anything unless I took of the shape centered. Some regression between betas as this works different in beta5 and beta6.

**Comment by akien-mga** [comment]
Thanks for checking which betas reproduce the issue.
The bug is likely caused by #32967, CC @Groud.

**Comment by follower** [comment]
From a quick look, this seems like the problematic area: https://github.com/godotengine/godot/pull/32967/files#diff-a435ad70755c63a0f2c7245dace9947eL138

```diff
-	Vector2 pos = shape_centered ? _edit_get_rect().size * 0.5f : Vector2();
+
+	Vector2 size = texture.is_null() ? shape->get_rect().size : texture->get_size();
+	Vector2 pos = shape_centered ? size * 0.5f : Vector2();
```

Seems like maybe `shape->get_rect().size` should be just `Vector2()` to match the original behaviour?

Or, if texture returns a size of (0,0) for null textures something like this might work (untested):

    Vector2 pos = shape_centered ? texture->get_size() * 0.5f : Vector2();

But I don't know if that's how null texture works--which may be why the original change using the intermediate `size` variable was made.

(There is some logic to *not* matching the original behaviour--I saw one example where instead of a texture someone was using an animated sprite as a sibling node--but it seems it would be backwardly incompatible.)

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4
