### ISSUE TITLE
Android export template for 2.0 beta does not working.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#3573]
I was using Alpha version and everything worked ok. But with Beta the application terminates immediately.
Samsung Galaxy S5.

**Comment by razvanc87** [comment]
I think you're referring to this issue https://github.com/godotengine/godot/issues/3478. I haven't tried it yet, but I guess if you compile the export templates for android yourself using the latest git version then all will go back to normal.

**Comment by reduz** [comment]
making new ones to test

**Comment by akien-mga** [comment]
Duplicate of #3478 indeed.
