### ISSUE TITLE
Kerning pairs not available in DynamicFont

### ISSUE THREAD

**Issue by Chaosinism** [godotengine/godot#35730]
**Godot version:**
Godot v3.1.1 Stable
Godot v3.2 Stable

**OS/device including version:**
Windows 10

**Issue description:**
![kerning](https://user-images.githubusercontent.com/27929868/73416864-322ce080-42e4-11ea-8f09-20995c6456c6.png)
Different from BitmapFont, the kerning is rendered identically for every character pair in DynamicFont. 
It seems that the next character in the text (`p_next`) is not really taken into consideration in functions such as `DynamicFont::get_char_size` and `DynamicFontAtSize::draw_char` (unlike `BitmapFont::get_char_size` which queries the kerning pair map).

**Steps to reproduce:**
Any Label or RichTextLabel

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/49377.
