### ISSUE TITLE
Material is not being rendered correctly on Samsung Galaxy Tab A

### ISSUE THREAD

**Issue by uldall** [godotengine/godot#35732]
**Godot version:**
3.2

**OS/device including version:**
Samsung Galaxy Tab A
Web build

**Issue description:**
Material is not being rendered correctly on Samsung Galaxy Tab A. The tablet likely uses etc vram compression.

The game on Linux desktop (The game looks fine in both Firefox and Chrome):
![Screenshot at 2020-01-30 09-26-47](https://user-images.githubusercontent.com/628383/73433768-b1063580-4345-11ea-8226-c85516188c43.png)

The game on Samsung Galaxy Tab A in Chrome (Firefox has the same issue):
![Screenshot_20200130-093513_Chrome](https://user-images.githubusercontent.com/628383/73433792-bc596100-4345-11ea-97ef-4fbb5ec4fea8.jpg)

In these screenshots the watermelon and the stars are rendered incorrectly.

**Comment by uldall** [comment]
@clayjohn Let me know if you don't have a new enough version of the game to reproduce the issue.

**Comment by uldall** [comment]
@jesperkondrup will you add some more info about this issue?

**Comment by jesperkondrup** [comment]
We tried swapping the materials between the watermelon and grapes. The result can be seen in the image below and it looks like the watermelon is now rendered correct and the grapes are incorrect.

![Screenshot_20200130-105612_Chrome](https://user-images.githubusercontent.com/24936603/73439129-6e495b00-434f-11ea-967d-918a568b9a3c.jpg)

We also tried copying the settings from the grapes material to the watermelon material (the red dots). But it still gives the same result. This is only on the tablet though. Everything still looks correct on Linux in Firefox and chrome. 
 
![materialissue2020](https://user-images.githubusercontent.com/24936603/73446487-24677180-435d-11ea-8835-64a39b60a7a2.jpg)

**Comment by Zireael07** [comment]
Have you tried disabling the ao completely and/or changing the watermelon texture?

**Comment by jesperkondrup** [comment]
@Zireael07 
It's a good suggestion. There is also the possibility that the material has been "corrupted" somehow and a new Spatial material could fix the issue.

**Comment by clayjohn** [comment]
Looks like there is actually two underlying issues going on here. 

The first is the obvious, somehow textures are getting corrupted either on import or on load. 

The second doesn't appear in the above screenshot, but does appear in the test case you sent. It is related to a few other reported problems with GLES2 on mobile. (https://github.com/godotengine/godot/issues/33633 and https://github.com/godotengine/godot/issues/34257, maybe related https://github.com/godotengine/godot/issues/35459)

I am going to focus on the first issue and then we can reassess.

**Comment by akien-mga** [comment]
Fixed by #36694.
