### ISSUE TITLE
Godot 3.2 not working well with moving platform

### ISSUE THREAD

**Issue by mohsenph69** [godotengine/godot#35748]
**Godot version:3.2**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

I use Godot 3.1.2 for my game and for physics I used move_and_collide, I added the velocity of moving platform to the velocity of my player and in Godot 3.1.2 everything work well, But when I switched to Godot 3.2 my player pass through the platform and not working well.
For now I continue making my game with Godot 3.1.2 and I hope this problem will be solved!

**Comment by Calinou** [comment]
@mohsenph69 Please upload a minimal reproduction project so this issue can be diagnosed.

**Comment by ChainedLupine** [comment]
I'm seeing this too.  My setup:

Path2D
  -> AnimationPlayer
  -> PathFollow2D
     -> Platform (Kinematic2D object with SyncToPhysics=true and no move_xxx commands)

My character now falls through the platform and only collides with where it starts out (at offset=0).

**Comment by mohsenph69** [comment]
So this problem for me is solved.
I think Godot 3.2 is not back compatible with Godot 3.1.2, What I did, I just delete the kinematic_body_2d and I created another one and now everything also work well in Godot 3.2
