### ISSUE TITLE
Freeing TabContainer with direct child of type AnimationPlayer produces Error

### ISSUE THREAD

**Issue by jeanlucami** [godotengine/godot#35741]
**Godot version:** 3.2 Stable

**OS/device including version:** Win 10

**Issue description:**
Freeing TabContainer with direct child of type AnimationPlayer produces following Error
``` 
_disconnect: Nonexistent signal 'renamed' in [AnimationPlayer:3588].
  <C++ Error>   Condition "!s" is true.
  <C++ Source>  core/object.cpp:1518 @ _disconnect()
```

If AnimationPlayer is a grandchild of TabContainer, error does not come up.
**Steps to reproduce:**
Run Attached Project, main scene has two instanced child scenes, one with direct child AnimationPlayer which produces error on queue_free, and one with AnimationPlayer as grandchild ( a Control inbetween ) which produces no error on queue_free.

**Minimal reproduction project:**
[animationplayerbug.zip](https://github.com/godotengine/godot/files/4134326/animationplayerbug.zip)

**Comment by tom-jk** [comment]
Can reproduce error in 3.2.2.stable on linux mint 18.3.

However, is your minimal reproduction project set up as you intended?

![Godot35741_Screen](https://user-images.githubusercontent.com/64640811/87418229-3f573680-c5c9-11ea-92f9-5b016ca61cba.png)

As I said it still produces the error, but the grandchilded AnimationPlayer seemed an important detail in your description.

**Comment by jeanlucami** [comment]
The error should not occur if the animation player is a grandchild of the tabbed container but with a control parent.

**Comment by qarmin** [comment]
Still happens with 3.2.4.beta.custom_build. 2d904127d
```
ERROR: _disconnect: Attempt to disconnect a nonexistent connection to signal 'renamed' in [AcceptDialog:2723], with target '_child_renamed_callback' in [TabContainer:2786].
   At: core/object.cpp:1569.
```
Automatic minimal project
[RegressionTestProject.zip](https://github.com/godotengine/godot/files/5875380/RegressionTestProject.zip)

**Comment by filipworksdev** [comment]
Happens on any control as well if you set it to `drag_to_rearrange_enabled` and drag a tab. Seems like any time you remove a node will force disconnect `rename` signal even if it hasn't been set.
