### ISSUE TITLE
Cannot open nor create project

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot#35745]
**Godot version:**
-godot 3.2-stable

**OS/device including version:**
-Windows 10

**Issue description:**
-Cannot open nor open projects

**Steps to reproduce:**
-Open/Create a project

**Minimal reproduction project:**
[3.2 test.zip](https://github.com/godotengine/godot/files/4135032/3.2.test.zip)

**Comment by Calinou** [comment]
Please add more detail on what happens when you try to open a project.

**Comment by LoneDespair** [comment]
Godot just hangs/keeps on loading when opening/creating a project
Godot 3.1.2 and other former versions works very well on same machine

Exact Download path: https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_win64.exe.zip
My machine info: OpenGL ES 3.0 Renderer: AMD Radeon HD 7310 Graphics
Thank you so much in advance

**Comment by Calinou** [comment]
Try switching the video driver to GLES2 in the Project Settings. (If you can't open the project anymore, you can do so by editing `project.godot` with a text editor and replacing `GLES3` with `GLES2`.)

**Comment by LoneDespair** [comment]
Thank you, it worked

**Comment by LoneDespair** [comment]
Btw just want to add, after testing on linux(ubuntu), gles3 works completely fine

tho gles3 is probably just going to be replaced by vulkan
