### ISSUE TITLE
can godot open real Camera hardware?

### ISSUE THREAD

**Issue by 2439905184** [godotengine/godot#35742]
I want to try to make a ar game.
I learned about ar/vr in godot docs.
code 
func ready():
   var arvr=ArVrServer.get_interfaces()
   print(arvr)
#I get a array [id:0 Native mobile]
#then I close godot and connect my Usb Camera 
#run it again , There still only Native mobile
#so is ar function still in developing
if arvr.initialize():
     get_viewport.arvr=true 
#then I run it i see the chages in game ,I know it is for vr
#but is There a way to render Picture of camera in reality or in real wrold(现实中的相机) to game/view_port ?
(有没有办法把现实中相机的画面渲染到游戏里) 
just see/view real world in game .
I searched about unity .
Find it can open hardware Camera and render it to game.
I wont't try unity because when my computer run it  it always crash ,but godot will not.
So does godot have similar function?
I think godot will become popular in the world.
I like open source software .
Thanks every developer make it.
I made  some Easy tutorials about godot 
in China website bilibili.com.
I think they may help some people.

**Comment by Calinou** [comment]
Please don't ask support questions here. Use one of the other [community channels](https://godotengine.org/community) instead.
