### ISSUE TITLE
Godot 3.2 slows down when I enable shadows :(

### ISSUE THREAD

**Issue by 19PHOBOSS98** [godotengine/godot#35746]
**Godot version:** 3.2

**OS/device including version:** MacOS/Macbook pro

**Issue description:**
 just downloaded the latest version. This wasn't an issue when I was using 3.1.2. It starts lagging like crazy when my Mirror is in view. When I disabled shadows it started working fine. Is there anyway around this?
![Screenshot 2020-01-30 at 11 43 49 AM](https://user-images.githubusercontent.com/37253663/73468935-8a391500-43c0-11ea-8858-06457af259b5.jpg)

**Steps to reproduce:**
-create a plane MeshInstance with a ViewportTexture rendering a camera that follows the player around
-have a directional light with shadows enabled
-adjust the Viewport's Shadow Atlas to 1
-run game
-quickly end game cause you're scared of the immense lag spike :(

**Minimal reproduction project:**
https://drive.google.com/drive/folders/1UQJFH0cg0OEs8RWHEHLh9GcP4aZwt4DS?usp=sharing

**Comment by Schweini07** [comment]
Using Arch Linux on a pretty weak laptop the reproduction project worked just fine for me. Could be a problem with your OS or hardware, although it's very strange that everything worked in 3.1.2.

**Comment by Calinou** [comment]
@19PHOBOSS98 Can you reproduce this in any of the older [3.2 alphas/betas/RCs](https://downloads.tuxfamily.org/godotengine/3.2/)? (Make a backup of your project before opening them with older versions.)

**Comment by 19PHOBOSS98** [comment]
> @19PHOBOSS98 Can you reproduce this in any of the older [3.2 alphas/betas/RCs](https://downloads.tuxfamily.org/godotengine/3.2/)? (Make a backup of your project before opening them with older versions.)

It starts happening at beta 2 :(
this is 3.2 before cocain (Beta1):
![Screenshot 2020-01-31 at 9 37 22 AM](https://user-images.githubusercontent.com/37253663/73505460-867faf80-440d-11ea-8e0c-b350e77a289d.jpg)
![Screenshot 2020-01-31 at 9 37 30 AM](https://user-images.githubusercontent.com/37253663/73505462-87184600-440d-11ea-8d81-9624d260a53b.jpg)
this is 3.2 after cocain (Beta2):
![Screenshot 2020-01-31 at 9 37 54 AM](https://user-images.githubusercontent.com/37253663/73505589-e24a3880-440d-11ea-8120-146284ed7b6d.jpg)
![Screenshot 2020-01-31 at 9 38 14 AM](https://user-images.githubusercontent.com/37253663/73505590-e2e2cf00-440d-11ea-8947-6b9f505e99c4.jpg)

**Comment by clayjohn** [comment]
Does this affect GLES2 and GLES3?

**Comment by 19PHOBOSS98** [comment]
> Does this affect GLES2 and GLES3?

I think it has something to do with Beta2's GLES3:
![Screenshot 2020-01-31 at 11 17 41 AM](https://user-images.githubusercontent.com/37253663/73509886-9f8f5d00-441b-11ea-8855-f5f1bd4bc669.jpg)
![Screenshot 2020-01-31 at 11 17 58 AM](https://user-images.githubusercontent.com/37253663/73509887-9f8f5d00-441b-11ea-99a3-29daae513a7d.jpg)

**Comment by clayjohn** [comment]
To confirm, you are not experiencing any lag in GLES2, right? I can't tell how fast the program is running based on your screenshots.

**Comment by 19PHOBOSS98** [comment]
> To confirm, you are not experiencing any lag in GLES2, right? I can't tell how fast the program is running based on your screenshots.

yeah it's faster in GLES2... and also is GLES3 meant to look like that in the new version?

**Comment by clayjohn** [comment]
Unfortunately no. For the rest of us it looks the same in 3.1.2 as it does in 3.2. 

Can you please post what hardware you have including CPU, GPU, OS, and graphics driver. 

Also try updating your graphics driver to the newest version.

**Comment by 19PHOBOSS98** [comment]
![Screenshot 2020-01-31 at 2 50 19 PM](https://user-images.githubusercontent.com/37253663/73518358-0e2ee380-4439-11ea-908d-be145ac5a5c1.jpg)
is there still any hope for me doc ?
(overlooking the fact that I'm using a Mac)

**Comment by Schroedi** [comment]
I can kind of reproduce the issue. There is definitely something going on. On my system (similar MacBook with GT 750 though), the stuttering is very visible in 3.2 when vsync is disabled - even though it reports >200 fps. On 3.1 vsync is always enabled for me, or at least the framerate is capped at 60 fps.

I would like to investigate this without the Nvidia GPU, but I don't know how to force the Intel GPU for Godot.

Here is the profiler graph for 3.1:
<img width="1048" alt="3 1" src="https://user-images.githubusercontent.com/97124/73519500-91ccde00-4401-11ea-8255-9d441ecc4bfa.png">

The same with 3.2 without vsync:
<img width="1048" alt="3 2_no_vsync_about_240_fps" src="https://user-images.githubusercontent.com/97124/73519499-91ccde00-4401-11ea-8bcd-846e7da5569f.png">

3.2 with vsync enabled:
<img width="1048" alt="3 2_vsync" src="https://user-images.githubusercontent.com/97124/73519501-91ccde00-4401-11ea-9e2d-1eb5fb901ebb.png">

**Comment by 19PHOBOSS98** [comment]
so... what can I do to help?

**Comment by bruvzg** [comment]
macOS 10.15.2, AMD FirePro D300, Godot 3.2 stable, GLES3 - no lags with mirror is in view, shadows looks the same way as in beta 1.

**Comment by 19PHOBOSS98** [comment]
still happens in 3.2.1 :( is there any news about this?

**Comment by Calinou** [comment]
@19PHOBOSS98 Shadow mapping was rewritten entirely in the Vulkan renderer. Either way, no matter what you do, directional shadows will always have a significant cost.

**Comment by Calinou** [comment]
@19PHOBOSS98 Can you (or anyone else) still reproduce this bug in [Godot 3.3.2](https://godotengine.org/article/maintenance-release-godot-3-3-2) or any later release?

**Comment by 19PHOBOSS98** [comment]
> @19PHOBOSS98 Can you (or anyone else) still reproduce this bug in [Godot 3.3.2](https://godotengine.org/article/maintenance-release-godot-3-3-2) or any later release?

Hi, sorry for the late reply. I'm using 3.3.2-stable. So directional shadows still slows everything down... running the game in the editor, that is. I suspected it was just the editor since I looked at the debugger. It said the game was running at 75FPS (with directional shadows (PSSM4 Split) without the recursive "mirror"). The game runs smooth when I compiled it.

GLES3's default lighting is still dark tho.

**Comment by ismailgamedev** [comment]
I still have this problem

**Comment by Calinou** [comment]
> I still have this problem

It's expected that performance decreases when you enable shadows. Not doing stuff is faster than doing stuff 🙂 

If performance is unexpectedly low, please upload a minimal reproduction project that demonstrates it.

**Comment by ismailgamedev** [comment]
> > hala bu sorunu yaşıyorum
> 
> Gölgeleri etkinleştirdiğinizde performansın düşmesi beklenir. Bir şeyler yapmamak, bir şeyler yapmaktan daha hızlıdır🙂
> 
> Performans beklenmedik şekilde düşükse, lütfen bunu gösteren minimal bir reprodüksiyon projesi yükleyin.

![unknown-17](https://user-images.githubusercontent.com/64804972/132134021-6f289423-d897-429a-ad8f-581e9428add8.png)
![unknown-23](https://user-images.githubusercontent.com/64804972/132134023-871075cf-f5fe-4f77-8777-ea785c7c17ce.png)

**Comment by Calinou** [comment]
@ismailgamedev What graphics adapter do you have? Can you upload the project somewhere so that someone else can try to reproduce this?

**Comment by ismailgamedev** [comment]
> @ismailgamedev What graphics adapter do you have? Can you upload the project somewhere so that someone else can try to reproduce this?

![image](https://user-images.githubusercontent.com/64804972/132134963-7aebcbd1-d74b-4272-9408-1cfda6118eb6.png)

**Comment by ismailgamedev** [comment]
> @ismailgamedev What graphics adapter do you have? Can you upload the project somewhere so that someone else can try to reproduce this?

By the way, I didn't have this kind of problem in Unity.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/57549, which has more information about what can be improved.
