### ISSUE TITLE
Using a TextureAtlas in a Tile Map TileSet shows error for multiple files

### ISSUE THREAD

**Issue by jself** [godotengine/godot#35756]
**Godot version:**
3.2

**OS/device including version:**
Manjaro Linux (up to date, rolling release)

**Issue description:**
Importing individual PNGs as a texture atlas and then trying to add them to a tile set shows the error:
"1 file(s) were not added because was already on the list"

**Steps to reproduce:**
Select multiple pngs, change import type to TextureAtlas on the Import tab.
Create a new TileSet and attempt to drag files to tileset.

The first one works fine, but future ones do not.

Saving a separate Atlas File and then using it as the image is a workaround, but it is more troublesome to create individual tiles if they are different sizes

**Minimal reproduction project:**
Attached, TileMap has one tile but dragging additional shows the error
[AtlasExample.zip](https://github.com/godotengine/godot/files/4136262/AtlasExample.zip)

**Comment by arkology** [comment]
If i understand correctly, you're talking about TextureAtlas import option in Import dock. If it's true, look https://github.com/godotengine/godot/issues/32869 This happens not only in TileSet.

**Comment by arkology** [comment]
If i understand correctly, you're talking about TextureAtlas import option in Import dock. If it's true, look https://github.com/godotengine/godot/issues/32869 This happens not only in TileSet.

**Comment by jself** [comment]
@arkology Hmm, possibly, I was able to use the Texture Atlas files elsewhere (like in a Sprite or AnimatedSprite frames) so I think this specific error may be specific to the TileSet. 

I did use the Import dock to designate them as TextureAtlas files, but that part worked fine. I didn't see the error in that ticket.

**Comment by jself** [comment]
I've attached a screenshot of the error I'm seeing.
![Screenshot from 2020-01-30 21-58-50](https://user-images.githubusercontent.com/115785/73511591-bb5b1a80-43ab-11ea-8e46-f74c1b81d6c2.png)

**Comment by jself** [comment]
Here's the error I'm seeing after trying to drag BGTile (2).png into the TileSet
![Screenshot from 2020-01-30 21-59-51](https://user-images.githubusercontent.com/115785/73511624-e5144180-43ab-11ea-9bd6-b926946a8af5.png)

**Comment by akien-mga** [comment]
Fixed by #38388.
