### ISSUE TITLE
Version 3.2 Stable completely unusable on Oculus Quest

### ISSUE THREAD

**Issue by SoapSpangledGames** [godotengine/godot#35763]
Godot version: 3.2 Stable
OS/device including version: Oculus Quest

While 3.2 Alpha worked well on the Quest, 3.2 Stable completely breaks Quest support. I would post a video, but trying to run a Godot 3.2 Stable program on the Quest causes recording to stop.

There are three main modes of failure I've seen so far:

1) Installing the game onto the Quest from the IDE allows the game to run, but the controllers cease to function in any meaningful manner. Controller movement works; but pointer location if WAY off, the buttons and triggers are no longer detected, and the joysticks no longer work. This happens with both the GLES2 and GLES3 renderers. Headset tracking works, but there is a small black border on the bottom of the viewport.

2) Trying to restart the game within the Quest causes the Godot splash screen to appear without switching into fullscreen, and then just rapidly flickers endlessly in that same non-fullscreen mode.

3) Trying to restart the game within the Quest immediately crashes the game, with no other display than the regular Quest display saying the game has stopped.

**Comment by Calinou** [comment]
@SoapSpangledGames Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by SoapSpangledGames** [comment]
I found the problem.  When I re-downloaded the Android export, the Xr Mode got reset from "Oculus Mobile VR" to "Regular", and the Degrees of Freedom got reset from "6DOF" to "None".

When I restored both those settings, my game worked again.
