### ISSUE TITLE
KinematicBody2D when pushed falls if it touches two one way collision static bodies.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#35776]
**Godot version:**
3.2 stable
**OS/device including version:**
Windows 10 64-bit
**Issue description:**
When a kinematic body 2d is touching two one way collision static bodies and another kinematic body 2d falls on it then it falls from the one way collisions.

**Minimal reproduction project:**
[one_way_bug.zip](https://github.com/godotengine/godot/files/4138570/one_way_bug.zip)

**Comment by Calinou** [comment]
Can you reproduce this in Godot 3.1.2 or any of the older 3.2 alphas, betas or RCs? You can download them [here](https://downloads.tuxfamily.org/godotengine/3.2/).

**Comment by kakoeimon** [comment]
Reproduced and in Godot 3.1.2 stable.

**Comment by capnm** [comment]
I can confirm that this is broken in 3.2.3.stable and that #42574 fixes the issue for me on the 3.2 branch.
