### ISSUE TITLE
False positive "Unreachable code" warning (for loop)

### ISSUE THREAD

**Issue by zinnschlag** [godotengine/godot#35775]
**Godot version:**

3.2.0

**OS/device including version:**

Ubuntu 19.10

**Issue description:**

Having an unconditional return in a for loop triggers an unreachable code warning when there is more code after the loop. This is not correct, because the loop condition may never be fulfilled (e.g. iterating over an empty array).

Note: I am aware that the example code below doesn't make any sense. I simplified it to the bare minimum that still shows the bug.

**Steps to reproduce:**

Paste the following code into any GDScript:

```
func test():
    var a = []
    for b in a:
        return b
    return null
```

**Minimal reproduction project:**

Not useful in this case IMO. Pasting the code into a script is quicker than downloading a project.

**Comment by LoneDespair** [comment]
I believe calling a return will stop the function including the loop, causing the bottom code to be unreachable

and if the (b in a) doesn't have a value it will automatically return null

**Comment by zinnschlag** [comment]
> I believe calling a return will stop the function including the loop, causing the bottom code to be unreachable, as the loop is run unconditionally

Sorry, but that is simply not true. The bottom code is reachable if the loop condition is never fulfilled, because in this case the loop body (with the unconditional return) is never executed.

**Comment by LoneDespair** [comment]
My bad, i see it doesn't loop because there's nothing to loop at, thus not executing the return, and making the bottom reachable

**Comment by KoBeWi** [comment]
But that requires parser to know if the array has elements or not. This one is obvious case, but solving the problem universally is not worth it IMO.

**Comment by zinnschlag** [comment]
The empty array is just an example, the simplest example possible to be precise. That is an universal problem and it does require a universal solution, namely not to consider unconditional return in loops as ending the execution of the function.

You can easily construct an example with a loop that does execute the loop body with an unconditional return statement in it, that still does not make the code after the loop unreachable (continue keyword).

**Comment by KoBeWi** [comment]
Ah, that makes sense.
