### ISSUE TITLE
Camera Limit not working well with changing offset

### ISSUE THREAD

**Issue by mohsenph69** [godotengine/godot#35774]
**Godot version:3.2**

So the problem is when I put a right limit for my camera for example 1000, if my offset of my camera is vec2(0,0) everything will working well and camera will stop at 1000, But for example if I change my offset to vec2(200,0), then my camera will stop at 1200. in Godot 3.1.2 there was not such problem and camera would stop with any offset at 1000.

**Comment by Calinou** [comment]
@mohsenph69 Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by mohsenph69** [comment]
@Calinou I know about camera2d margin
Please look at this project for example: https://github.com/mohsenph69/godot_camera_limit
As camera Limit define it should stop at white box 1000 px, but it show 200 px more to the right, It is because it has 200 px offset in x direction

**Comment by raunovillberg** [comment]
Seems to have happened due to #30361.

**Comment by KoBeWi** [comment]
Yeah, this is intended behavior.
