### ISSUE TITLE
Event streams errors with XM modules.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3577]
When trying to import xm module I get:

```
> ERROR: set_volume_fadeout: Condition ' p_amount>MAX_FADEOUT ' is true.
>    At: drivers/chibi/cp_instrument.cpp:133.
> ERROR: set_volume_fadeout: Condition ' p_amount>MAX_FADEOUT ' is true.
>    At: drivers/chibi/cp_instrument.cpp:133.
> ERROR: set_volume_fadeout: Condition ' p_amount>MAX_FADEOUT ' is true.
>    At: drivers/chibi/cp_instrument.cpp:133.
> ERROR: set_volume_fadeout: Condition ' p_amount>MAX_FADEOUT ' is true.
>    At: drivers/chibi/cp_instrument.cpp:133.
> ERROR: get_instrument: Index p_instrument out of size (MAX_INSTRUMENTS).
>    At: drivers/chibi/cp_song.cpp:349.
```

Testing XM module was created in MilkyTracker.
4 voices used with 4 instruments (one each), 1 sample in each instrument. Samples are stereo 16-bit 44100 wave files, approx. 30 sec long, imported with mixing channels option.
All 4 instruments are playing together, only one, long note at the beginning of the song first and only pattern. All of that is a 10Mb xm file.

At first few times Godot were just quitting after this errors.
After manipulating with playback mode in MilkyTracker, Godot was able to import the xm file and play it. The errors in console are still there.

May be related to https://github.com/godotengine/godot/issues/2553

**Comment by reduz** [comment]
post an xm that causes the error...

**Comment by freemanfromgodotengine** [comment]
Here you are [test.xm](https://github.com/freemanfromgodotengine/my_repository/blob/master/xm/test.xm)

**Comment by spookdogg** [comment]
Can confirm crashing editor on my system

**Comment by bojidar-bg** [comment]
Adding "needs testing" label since it is unsure if this is still present in master (this issue and this xm importer)

**Comment by KoBeWi** [comment]
Module support was removed AFAIK.

**Comment by akien-mga** [comment]
Indeed.

**Comment by reduz** [comment]
I wrote a tiny xm playback library a long time ago, may be extended to play
back .mod files easily I think.
It's so tiny it may not be a problem to add it to Godot if anyone wants to
do it (and extend it to mods)
https://github.com/reduz/chibi-xmplay

**Comment by mdahlgrengadd** [comment]
I can look into it... I’ve got xm’s playing in Godot 3.1 using jar_xm.h which is based of ar1stocrats libxm with public domain license.
