### ISSUE TITLE
Optimized ios template for size larger than unoptimized

### ISSUE THREAD

**Issue by Myran** [godotengine/godot#35789]
**Godot version:**
11d28b2
**OS/device including version:**
MacOS 10.15.2
**Issue description:**
when optimizing for size for iOS as described in https://docs.godotengine.org/en/latest/development/compiling/optimizing_for_size.html the resulting file is larger than unoptimized.

```
scons p=iphone tools=no target=release arch=arm64 -j8
58101704  libgodot.iphone.opt.arm64.a 
```

```
scons p=iphone tools=no target=release arch=arm64 -j8 module_bmp_enabled=no module_bullet_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etc_enabled=no module_gdnative_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_mbedtls_enabled=no module_mobile_vr_enabled=no module_opus_enabled=no module_pvr_enabled=no module_recast_enabled=no module_regex_enabled=no module_squish_enabled=no module_tga_enabled=no module_thekla_unwrap_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_vorbis_enabled=no module_webm_enabled=no module_websocket_enabled=no disable_advanced_gui=yes disable_3d=yes optimize=size use_lto=yes
71307600 libgodot.iphone.opt.arm64.a
```

It seems the guide was based on an android test #18253, maybe there is additional steps for iOS?

**Comment by Calinou** [comment]
LTO is known to give weird results on iOS, try removing `use_lto=yes` from the optimized SCons command line.

**Comment by bruvzg** [comment]
iOS templates are static libraries, probably LTO saves some extra info for the optimization, actual optimization will happen when final executable is linked.

Compare size of executables exported and linked by Xcode instead.

**Comment by Myran** [comment]
> iOS templates are static libraries, probably LTO saves some extra info for the optimization, actual optimization will happen when final executable is linked.
> 
> Compare size of executables exported and linked by Xcode instead

Thanks. when built, the ipa file decrease from 10 to 7,2 mb in size
