### ISSUE TITLE
Godot Project Manager Created Under the Windows Taskbar

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3578]
After the console is created it proceeds to spawn the Godot Project Manager, however, I like having my   taskbar at the top of my monitor, and when the Project Manager window is created it is positioned under the taskbar, which normally wouldn't be that big of an issue, but the location isn't remembered from run to run meaning it always appears in the same location. The real issue is that the windows header frame is completely under the task bar meaning that I have to always shift-click, select move, hit an arrow key, reposition. Technically, I don't need to move the window since nothing within the client I need to click is obscured, but to me its an annoying visual bug. The ideal fix would be to have the project manager remember its position between runs (and while your at it perhaps do the same for the editor).

Thank you for your time, and all your hard work on Godot, I really think Godot's got something special about it.

![godotcreatedunderwindows](https://cloud.githubusercontent.com/assets/17059062/12806169/82d8975c-cad1-11e5-8b8c-cbc8c4a3c35d.png)

**Comment by Faustabov** [comment]
I just wanted to add that the issue is also present when using the play project option (I didn't mention this in the original post), which means you always will have to right-click close the created Godot game window, since its header is obscured.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by vnen** [comment]
I don't think this is even an issue anymore, since the window is now always centered when opened. The game window placement can be configured in project settings.

**Comment by akien-mga** [comment]
Assuming fixed as mentioned by @vnen.
