### ISSUE TITLE
UPnP discover does not work on Windows

### ISSUE THREAD

**Issue by Lathuys** [godotengine/godot#35792]
**Godot version:**
3.1.2 and 3.2, with and without Mono

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
UPnP discovery does not work. All I'm getting is this:
```
Socket error: bind, 10049
ERROR: get_gateway: Condition "devices.size() < 1" is true. Returned: __null
   At: modules/upnp/upnp.cpp:267
```
I talked about this with someone on Discord, and Linux version is working just fine.

**Steps to reproduce:**
1. Create new project
2. Create a scene
3. Add a root Node named "TEST" to the scene
4. Attach GDScript/C# script to the root node
5. Replace generated code with this one:
* GDScript version:
```
extends Node

func _ready():
    var upnp = UPNP.new()
    upnp.discover()
    print(upnp.get_gateway())
```
* C# version:
```
using Godot;
using System;

public class TEST : Node
{
    public override void _Ready()
    {
        var upnp = new UPNP();
        upnp.Discover();
        GD.Print(upnp.GetGateway());
    }
}
```

**Minimal reproduction project:**
See above

**Comment by Topicranger** [comment]
Same issue here. I reproduced the project with 3.2 without Mono. 
Disabling my firewall opened up the Windows Firewall permission dialog, but changed nothing. Additionally disabling the Windows Firewall made no difference, so I assume that it is not a problem of restricted permission.

**Comment by Faless** [comment]
Quick questions:
- Does your router support UPNP IGDP?
- Is UPNP IGDP enabled on your router (most routers do come with it disabled due to security concerns).

**Comment by Faless** [comment]
Additionally, can you post the output of  `print(IP.get_local_interfaces())` in Godot 3.2?

**Comment by Topicranger** [comment]
> Does your router support UPNP IGDP?

UPNP is activated and should support IGDP. (FRITZ!Box 7590)

`print(IP.get_local_interfaces())` prints this:
`[{addresses:[192.168.178.43], friendly:WLAN, index:26, name:{F389FF61-3CE5-43F3-852C-EB12A8AC0554}}, {addresses:[169.254.147.135, 192.168.137.1], friendly:Ethernet, index:23, name:{E713771D-2EBC-426D-9D5A-8939889FCC7B}}, {addresses:[0:0:0:0:0:0:0:1, 127.0.0.1], friendly:Loopback Pseudo-Interface 1, index:1, name:{E0EA33F7-40D0-11E8-9C40-806E6F6E6963}}, {addresses:[fe80:0:0:0:8516:4f8f:7d2f:1ca5, 169.254.28.165], friendly:LAN-Verbindung* 2, index:21, name:{DBF7C955-2E25-4713-A8AE-AD3E79FB3430}}, {addresses:[fe80:0:0:0:b0f6:bbc6:5b06:390b, 169.254.57.11], friendly:LAN-Verbindung* 3, index:9, name:{65ABB40D-826D-46C5-BBCE-E2AE503655FB}}]`

**Comment by Faless** [comment]
So can you confirm that "Permit independent port sharing for this device"
option is enabled on your device?
https://en.avm.de/service/fritzbox/fritzbox-7590/knowledge-base/publication/show/894_Setting-up-automatic-port-sharing/

**Comment by Topicranger** [comment]
Yes, this option is enabled.

**Comment by Faless** [comment]
Okay thank you very much, I'll investigate further, thanks for the
information.

**Comment by vicguedez** [comment]
Ran a project that uses UPnP and it works with 3.1.1, indeed UPNP.discover() fails in 3.1.2 and 3.2.

In both 3.1.2 and 3.2 all I got in console was "Socket error: bind, 10049", which of course returned UPNP_RESULT_SOCKET_ERROR = 24.

**Comment by Iddmeister** [comment]
I'm getting this as well, works on Linux fine but Windows just gives error "Socket error: bind 10049" and the UPNPResult is 24 (Socket Error)

**Comment by Faless** [comment]
Regression from ( 78907d91f140dd047a2eebb2736ed1762897003d ) . Potentially an issue upstream. Will investigate further.
