### ISSUE TITLE
Pressure isn't correct on Linux with Huion 420 Pen Tablet using wacom driver

### ISSUE THREAD

**Issue by SleepProgger** [godotengine/godot#35793]
**Godot version:**
3.2.stable

**OS/device including version:**
Manjaro stable with Xfce
Kernel: 5.4.15-2

**Issue description:**
With the Huion 420 Pen Tablet `InputEventMouseMotion.pressure` reports pressure in the range of 0 - MAX_USHORT (65535) while it should be in the 0-1 range.
This only happens when using the wacom driver. Using evdev the reported pressure is fine, but the wacom driver is required for different settings.
Gimp detects the pressure just fine with both drivers which points to a bug in Godot.

**Steps to reproduce:**
Use wacom driver with HUION 420 (or probably other tablets), and print event.pressure of `InputEventMouseMotion` events

**Minimal reproduction project:**
Do i really need this ?
Its just:
```py
func _input(event):
	if event is InputEventMouseMotion:
		print(event.pressure)
```

I can work around this for now using something like:
`event.pressure = event.pressure if event.pressure <= 1 else event.pressure / 65536.0`
but that's a bit iffy.

*Is there a way to get the pressure for a InputEventMouseButton event btw ?*

**Comment by bruvzg** [comment]
> Is there a way to get the pressure for a InputEventMouseButton event btw ?

No, it's implemented only for `InputEventMouseMotion` events.

> Use wacom driver with HUION 420

Wacom driver is `xf86-input-wacom` or some proprietary one?

Pressure range is provided by libxi - https://github.com/godotengine/godot/blob/master/platform/x11/os_x11.cpp#L699-L702

**Comment by SleepProgger** [comment]
Yes, wacom = xf86-input-wacom

I currently don't have a C++ dev environment set up, but will see if i can find whats going wrong in that code.

**Comment by SleepProgger** [comment]
When running [this](https://termbin.com/tco6n) snipped based on the linked code i get:
```
Device HUION 420 Pad pad:
 - Resolution: 1
 - Min: 0.000000
 - Max: 1.000000
Device HUION 420 Pen stylus:
 - Resolution: 1
 - Min: 0.000000
 - Max: 65536.000000
```

Same with `xinput list "HUION 420 Pen stylus"`.
So it might be the driver (or my setup) that does strange things, but at least GIMP seem to be able to work around that.
For godot too it might make sense to ignore a resolution of 1 if the `(max - min) / resolution` > 1.
I have no clue about that whole area tho, so no clue if that would break other things ?

**Comment by bruvzg** [comment]
Currently, it's using `resolution` if it's `> 0`, and `max - min` otherwise: [os_x11.cpp#L731-L733](https://github.com/godotengine/godot/blob/master/platform/x11/os_x11.cpp#L731-L733), that's seems to be wrong - probably we should always use `max - min`, resolution is something else:

libxi man:

    min and max are the minimum and maximum values allowed on this
    axis. If both are zero, no minumum or maximum values are set on
    this device. value is the current value of this axis.

    The resolution field specifies the resolution of the device in
    units/m.

**Comment by SleepProgger** [comment]
That's good news for me. Thanks for checking.
Probably the same with tilt and maybe the other values too ?

**Comment by bruvzg** [comment]
Yep, that's should be the same for the all axis.

**Comment by bruvzg** [comment]
And absolute mouse X,Y calculations might be wrong as well.

**Comment by bruvzg** [comment]
I have tested it on Ubuntu 18.04 with libinput/evdev drivers, it gives min-max = 0-2047 for tablet and 0-1 for touchscreen, resolution is always 1.

**Comment by capnm** [comment]
> The resolution field specifies the resolution of the device in units/m. 

@bruvzg I wonder what the resolution means for the tilt angle?
After your patch, I now get about half of the tilt-range from the Wacom stylus (-0.5 ... 0.5):
```
Device Wacom Intuos4 4x6 Pen stylus:
 - PRESSURE Resolution: 1
 - Min: 0.000000
 - Max: 65536.000000
 - TILTX Resolution: 57
 - Min: -64.000000
 - Max: 63.000000
 - TILTY Resolution: 57
 - Min: -64.000000
 - Max: 63.000000
```
