### ISSUE TITLE
Failed to export project: Could not find a part of the path

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#35817]
**Godot version:**
3.2 Stable Mono
**OS/device including version:**
Windows 10
**Issue description:**
If Aot is enabled ~~(which is by default)~~, when trying to export for Windows Desktop i get the following error:
`ERROR: godot_icall_GD_pusherror: Failed to export project: Could not find a part of the path 'C:\Users\zak\Desktop\Godot\GodotSharp\Tools\aot-compilers\windows-x86_64\bin'.`
![Screenshot_5](https://user-images.githubusercontent.com/1850856/73589351-d9c13300-44dd-11ea-9aa8-51c0818518ac.png)

**Steps to reproduce:**
This is reproducible for as long as this: `GodotSharp\Tools\Tools\aot-compilers\windows-x86_64\bin` folder does not exist **and** Aot is enabled.
EDIT: I just installed on a new machine and and if i create the folder manually i get the following error:
![Screenshot_6](https://user-images.githubusercontent.com/1850856/73589694-6ff75800-44e2-11ea-9e90-cf3d6a8339a7.png)
It seems to be trying to find mono.exe in that path?

**Comment by JupiterRider** [comment]
1. AOT is not enabled by default. 
2. If you want to use AOT, then you have to build the AOT Compiler yourself:
https://github.com/godotengine/godot-mono-builds

You can read about more here: https://godotengine.org/article/csharp-wasm-aot
