### ISSUE TITLE
The entries are duplicated in Projects Manager's projects list

### ISSUE THREAD

**Issue by MxZhur** [godotengine/godot#35815]
**Godot version:**
3.2-stable, Standard edition

**OS/device including version:**
Windows 10 Pro 64-bit

**Issue description:**
All the entries in the Project Manager's projects list get duplicated after you scan a projects folder. You can remove the duplicates from the list, but if you scan again, you will see there are two entries for every project again.

Here's the screenshot:
![изображение](https://user-images.githubusercontent.com/25201113/73588086-4d236e80-44f7-11ea-9742-554bff49e9e7.png)

**Steps to reproduce:**
1. Go the the Project Manager.
2. Click Scan and select a folder with Godot projects.

**Minimal reproduction project:**
A folder with at least one any Godot project.

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.dev.custom_build.8c3b14bed (Linux).

**Comment by MxZhur** [comment]
> 
> 
> I can't reproduce this on commit [8c3b14b](https://github.com/godotengine/godot/commit/8c3b14bed79404eb32a9e6efbb2007807109eaa7) on Linux. I've tried scanning the cloned https://github.com/godotengine/godot-demo-projects repository several times.
> 
> Maybe this happens only on Windows, or because the path contains non-ASCII characters?

Is there any way to clear the projects list _on Windows_ so I could scan it with ASCII-only paths and see how it fills the initially empty list?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
