### ISSUE TITLE
Buttons get skipped when Toggling/Switching with arrow keys

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#35823]
**Godot version:**
Mono 3.2 Stable

**OS/device including version:**
5.4.15-arch1-1

**Issue description:**
Toggling/Switching between buttons doesn't work when using arrow keys -> Buttons get skipped. 

Tabulator works fine.

**Steps to reproduce:**
I have no Idea. I could never reproduce it on other projects.

**Minimal reproduction project:**
https://github.com/JupiterRider/ballntower_cs

When running my project in Window Mode, you'll see that buttons get skipped, when using arrow keys. But Fullscreen works fine.

![Peek 2020-02-01 13-52](https://user-images.githubusercontent.com/60042618/73592399-421e0d80-44fa-11ea-9575-d8b642e86b4c.gif)

**Comment by DegradedMind** [comment]
I remember this issue was also present in 3.1.2, but i just decided then to manually assign the neighbours.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, GDScript project would be useful.

**Comment by JupiterRider** [comment]
@KoBeWi No. It works now .
