### ISSUE TITLE
Project Setting application/run/main_loop_type: existing classes not found

### ISSUE THREAD

**Issue by simaimch** [godotengine/godot#35822]
**Godot version:** 3.2

**OS/device including version:** Win 8.1

**Issue description:**

It appears as if the project setting `application/run/main_loop_type` can't be set to any valid custom class. Any setting will result in the error message "Error: MainLoop type doesn't exist: `main_loop_type`" and a crash.

The script checks for the existence of the class in ClassDB. Maybe not all scripts have been loaded to ClassDB at this point of time?

**Steps to reproduce:**

1. Create Project.
2. Create class extending MainLoop. Exmple:

```
extends SceneTree

class_name MyClass


var time_elapsed = 0

func _initialize():
	print("Initialized:")
	print("  Starting time: %s" % str(time_elapsed))
```
3. Set project setting `application/run/main_loop_type` to `MyClass`.
4. Run.

**Comment by eon-s** [comment]
This never worked (like, ever) unless you compiled the engine with your class in it, but you can set a script to the scene tree at runtime, it may work for testing purposes but is not practical at all.

Custom main loops will run from the command line, though, maybe the parameters are not correct in the editor?

**Comment by ByteSizeOtter** [comment]
I have a project currently in which I need to override the MainLoop to have it run its own things and manage some internals more closely, but unfortunately I've run into a wall because of this bug.

**Comment by Xrayez** [comment]
Yeah, it works if you set this option explicitly to `SceneTree` or `MainLoop` (warning: screen flicker on startup), any other option fails, of course there's little to no benefit in doing so (`--script` command-line option is more useful currently).

#41190 is there to handle global script classes, so this option will actually become more useful to regular users, which also works for exported projects (unlike `--script`, which also doesn't work when the engine is compiled with `tools=no`: #17778).
