### ISSUE TITLE
Export option "embed pck" does not work on 32-bit x86

### ISSUE THREAD

**Issue by madelfagam** [godotengine/godot#35830]
**Godot version:**  3.2.stable  **Not Mono**

**OS/device including version:**
Windows 10 x64

**Issue description:** When you try to export any project with the x64 unchecked, the startup file throws an error:

Error: Could not load game data at path '.'. Is the .pck file missing?

If the startup file is x64, then an error does not occur. Changing other export settings does not affect anything.

**Steps to reproduce:** Create an empty project and export it as a Windows application with unchecked x64

**Similar to**
#33466 
![удаляй](https://user-images.githubusercontent.com/59872337/73597527-effedb80-453d-11ea-950a-017c470badf1.png)

**Comment by KoBeWi** [comment]
Tried in 3.2.4 beta4 and 64 bits don't work either.

**Comment by akien-mga** [comment]
@RandomShaper The easy solution would be to prevent using the option when exporting 32-bits for Windows I guess, at least until a fix can be found.

**Comment by akien-mga** [comment]
Seems fixed in 4.0 RC 3, possibly by #56093.
