### ISSUE TITLE
Capsulte Collider Shape

### ISSUE THREAD

**Issue by MostafaMThabet** [godotengine/godot#35835]
**Godot version:**3.2
**OS/device including version:** Manjaro Linux 18.1.5 Kernel 5.4

Issue description:Capsule Collider Shape Appears Rotate horizontally even though transform rotation is on 0

**Steps to reproduce:**
1. Create new 3D Scene 
2. Add Kinematic, or Rigid body
3. Create a Collision Shape and Select Capsule

![bugscreenshot](https://user-images.githubusercontent.com/54177443/73599745-825bab00-454f-11ea-8f6f-b9fc06335432.png)

**Comment by Calinou** [comment]
Capsules are horizontal by default. They will be changed to be vertical by default in 4.0: #5813

Closing, as this isn't a bug :slightly_smiling_face:
