### ISSUE TITLE
Error stack sometimes won't go to line definition if script is built-in

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#35838]
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
When encountering a runtime error inside a built-in script, the editor fails to go to the definition.  This might affect other parts of the call stack, but I've only tested it with an error at the top.  

**Steps to reproduce:**
1.  Create a normal script at scene root. 
2.  Create a built-in script.  Add a function `test()` to it.
3.  Introduce a runtime error in `test()`.  (`assert(false)` will probably work)
4. Call `test()` from the root script's `_ready()` function.
5.  Run program.
6.  Click the line defs at different parts of the call stack.  The external scripts should work, but the built-in script should fail.

**Comment by YeldhamDev** [comment]
Unable to reproduce this on Manjaro GNU/Linux.

**Comment by nobuyukinyuu** [comment]
I'm no longer able to reproduce this myself in my project.  May have been related to other issues such as cyclic dependency checks.  I can close the issue until I encounter it again.
