### ISSUE TITLE
Curve2D::set_point_position() only works when entering the scene

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#35837]
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
The function only seems to work when nodes are entering the scene

**Steps to reproduce:**
![curve2d](https://user-images.githubusercontent.com/37383316/73600561-97751180-4530-11ea-8265-6825f4c00a0b.gif)

**Minimal reproduction project:**
[Project.zip](https://github.com/godotengine/godot/files/4143412/Project.zip)

------------------------------------------------------------------------------

EDIT: It also works (only once) with _physics_process()
![curve2d](https://user-images.githubusercontent.com/37383316/73600651-30f0f300-4532-11ea-8eda-515af0a1ac7b.gif)

**Comment by Calinou** [comment]
@Muller-Castro Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by Muller-Castro** [comment]
@Calinou Done 👍

**Comment by bojidar-bg** [comment]
Path2D's `NOTIFICATION_DRAW` check is not the same as in the code calling `update()`:

https://github.com/godotengine/godot/blob/0edcb8ed58be8bf6a5145ceaae5ff96778afb2a2/scene/2d/path_2d.cpp#L93-L98

https://github.com/godotengine/godot/blob/0edcb8ed58be8bf6a5145ceaae5ff96778afb2a2/scene/2d/path_2d.cpp#L122-L126

Note that only the display of the curve is wrong. The curve itself updates properly.
