### ISSUE TITLE
Regression:  line edit ignores Android OS popup keyboard input

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#35839]
**Godot version:**
3.2 Stable
**OS/device including version:**
Android 9
**Issue description:**
godot line edit ignores Android OS popup keyboard input
**Steps to reproduce:**
add line edit, try typing with Android OS popup keyboard
**Minimal reproduction project:**
Same project works with 3.2 rc1

**Comment by HEAVYPOLY** [comment]
Seems like a couple people are seeing this on a demo project:  https://www.reddit.com/r/godot/comments/ew5ljl/lineedit_problem_on_android/

**Comment by HEAVYPOLY** [comment]
Also line edit not working with bluetooth keyboard on Android 9 / Godot 3.2 stable

**Comment by allkhor** [comment]
Duplicate of #35753, fixed in master, but not cherry picked to 3.2.

**Comment by HEAVYPOLY** [comment]
ok!  Thanks
