### ISSUE TITLE
Font size when animated, does not interpolate between set frames.

### ISSUE THREAD

**Issue by RichardR01** [godotengine/godot#35836]
**Godot version:**
3.2 stable
**OS/device including version:**
Windows 10 v1909
**Issue description:**
Font size when animated, does not interpolate between set frames.
**Steps to reproduce:**
Create new scene as user interface. add a child node of type label. Resize the label if you want.
Set the text to whatever. I used "Testing" for this example.
Set the custom font to a new dynamic font. Use any ttf font file for the font.
In the font settings, set the size to 1. Add a child node to the label as an animation player.
In the animation player, create a new animation, name it anything.
Click on the label on the tree and click on the key symbol next to the font size in font settings.
It will ask you if you want to create a new key for it. Select Yes.
Set the animation position to 1. Back at the label, set the custom font size to 80. Click the key symbol to create a new keyframe.
In the animation editor move the current verticle bar or type in the animation position to a value less than 1. 
You will notice the value of the font size stays the same, at 1, except for the last frame which the font size then becomes 80.
See test project for proof.
**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/4143350/TestProject.zip)

**Comment by RichardR01** [comment]
Update: I found out why it was doing this. It seems the animation player set the update mode to discreet on default. Setting it to continuous fixed the problem.

**Comment by Calinou** [comment]
I wouldn't recommend animating a font size for two reasons:

- The font size must be an integer, which means the animation will look choppy.
- The font will have to be re-rendered every time its size changes, leading to stuttering during gameplay.

Instead, look into using an higher base font size, downscaling the Control that hosts it under normal conditions and change its scale as needed. Make sure its scale doesn't exceed 1 to avoid visible pixelation/blurriness.

**Comment by Calinou** [comment]
I'll close this as this isn't a bug with animating the font size per https://github.com/godotengine/godot/issues/35836#issuecomment-581081872.
