### ISSUE TITLE
can not set texture_albedo on a new ShaderMaterial from Script

### ISSUE THREAD

**Issue by jasonswearingen** [godotengine/godot#35842]
**Godot version:**  3.2 mono x64

**OS/device including version:**  windows 10

**Issue description:** constructing a MeshInstance node from script (GDScript or C#), can not apply a texture.  It seems that the texture is applied but the mesh renders black.    

**Steps to reproduce:**

gdscript:
```
	var mesh = load("res://asset/cube/cube.obj");
	var shader = load("res://asset/cube/cube.shader");
	var diffuse = load("res://asset/cube/cube-diffuse.png");
	
	var shadMat = ShaderMaterial.new();
	shadMat.shader = shader;
	shadMat.set_shader_param("texture_albedo",diffuse);
	# shadMat.set_shader_param("albedo",Color.white);

	var meshInst = MeshInstance.new();
	meshInst.set_mesh(mesh);
	meshInst.material_override = shadMat;
	add_child(meshInst);
```

C#:
```
		//doesn't work
		var meshInstBroken = new MeshInstance();
		meshInstBroken.Mesh = mesh;
		var shadMat = new ShaderMaterial();
		shadMat.Shader = shader;
		shadMat.SetShaderParam("texture_albedo", diffuse);
		//shadMat.SetShaderParam("albedo", Colors.White);
		meshInstBroken.MaterialOverride = shadMat;
		AddChild(meshInstBroken);

```

 Additionally, setting the albedo color from code seems to not work properly either.    uncommenting the above ```shadMat.set_shader_param("albedo",Color.white);``` lines causes the mesh to be a dark red color.

If I create a ShaderMaterial from the editor and save it, I can load that from script properly, but not if I create a new shaderMaterial directly.

**Minimal reproduction project:**  see attached.  both C# and GDScript repros are present.

- GDSCript repro is in Test.gd
- C# repro is in assets/cube/ProcCube.cs
[repro-shader-texture-bug.zip](https://github.com/godotengine/godot/files/4143516/repro-shader-texture-bug.zip)

**Comment by clayjohn** [comment]
I ran your reproduction project. The issue you are having is not a bug. You are forgetting to set most of the uniforms you need. For example, you have ``albedo`` set to a default of ``vec3(0,0,0)`` so even when you add ``texture_albedo`` your cube is still black. As any color multiplied by black is black. 

Similarly, you have the ``uv_scale`` set to ``vec3(0,0,0)``, so even when you set albedo, your texture is only read from one corner of the texture. 

To solve this issue, you need to set default values for all your uniforms, or you need to set the values to appropriate numbers before running.

**Comment by jasonswearingen** [comment]
@clayjohn fyi I often try to ask questions via community channels but nobody replies, such as:  https://godotforums.org/discussion/21975/is-this-a-bug-color-hex-code-results-in-different-rgb-values-than-in-blender#latest

Thanks for the hint regarding this.

this code works, if anyone runs into the problem
```
		//put together a ShaderMaterial via code		
		var shader = GD.Load<Shader>("res://asset/cube/cube.shader");
		var diffuse = GD.Load<Texture>("res://asset/cube/cube-diffuse.png");
		var meshInstWithShadMat = new MeshInstance();
		meshInstWithShadMat.Mesh = mesh;
		var shadMat = new ShaderMaterial();
		shadMat.Shader = shader;
		//need to explicitly set default shader params yourself when setting up a ShaderMaterial through code
		shadMat.SetShaderParam("albedo", Colors.White);
		shadMat.SetShaderParam("uv1_scale", Vector3.One);
		shadMat.SetShaderParam("uv1_offset", Vector3.Zero);
		shadMat.SetShaderParam("uv2_scale", Vector3.One);
		shadMat.SetShaderParam("uv2_offset", Vector3.Zero);
		shadMat.SetShaderParam("texture_albedo", diffuse);
		meshInstWithShadMat.MaterialOverride = shadMat;
		AddChild(meshInstWithShadMat);
```
