### ISSUE TITLE
Toggle Bookmark hotkeys not always working.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#35844]
**Godot version:**
0edcb8ed58be8b

**OS/device including version:**
Win10 64-bit

**Issue description:**
Most the time the CTRL+ALT+B bookmark hotkey does not do anything in the script editor.

![image](https://user-images.githubusercontent.com/13004169/73606184-87047b80-45b0-11ea-9e97-d92b012f1908.png)

The context menu option still works.

**Steps to reproduce:**
Create a script, locate a line, and using the default key settings try using CTRL+ALT+B to toggle a bookmark.

**Comment by YeldhamDev** [comment]
Unable to reproduce this on Manjaro GNU/Linux.

**Comment by SkyLucilfer** [comment]
It works for me on Windows 10 x64 with godot version [c482379](https://github.com/godotengine/godot/commit/c48237967a0a4d3901c157a828017d7330df0578)

**Comment by avencherus** [comment]
It has began working again today.  It's unclear why.  I will close this for now, as it can no longer be reproduced.

**Comment by avencherus** [comment]
Quite possibly a duplicate of this https://github.com/godotengine/godot/issues/28511
