### ISSUE TITLE
GDScript breakpoints can shift around, multiply, and can become invisible.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#35843]
**Godot version:**
3.2 Stable (Likely in master)

**OS/device including version:**
Win10 64-bit

**Issue description:**
When breakpoints are used for debugging, if one modifies the script and while using script sync, the breakpoints get shuffled around.

After toggling off the breakpoint on the line it appears, breakpoints continue to get hit, but in my example I hit continue, and it seems to get stopped three times.  Suggesting there are three invisible breakpoints, which correlates to the number of lines added above it.

The only way to get rid of these invisible breakpoints is to toggle them on and off at the side.

1. Original code with original breakpoint.
![godot windows tools 64_RqvKdrjQgB](https://user-images.githubusercontent.com/13004169/73606141-b1a20480-45af-11ea-91fc-509810b21abc.png)

2. Modified and saved code while running.  The breakpoint hits here on the next iteration.
![godot windows tools 64_RllHKy8uOL](https://user-images.githubusercontent.com/13004169/73606140-afd84100-45af-11ea-983d-7a9ea602d210.png)

3. Breakpoint below is disabled, but breaks still persist.
![godot windows tools 64_vaeOTZpb0F](https://user-images.githubusercontent.com/13004169/73606142-b2d33180-45af-11ea-8ac5-c1d6ea2df8e6.png)

4. GIF shows using Continue steps through a set of invisible breakpoints.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/73606143-b797e580-45af-11ea-9f3d-65bd31441413.gif)

**Steps to reproduce:**

1. Create a simple script, set a breakpoint, and run the script that will break.  
2. Upon breaking, add and save the code as you would for live editing.

The breakpoint should be hitting somewhere else and possibly multiple times.

**Minimal reproduction project:**
This doesn't persist in a minimal project, it has to be recreated with the above steps.

**Comment by KoBeWi** [comment]
Fixed in 4.0

**Comment by avencherus** [comment]
No interest to fix it in 3.2?

**Comment by KoBeWi** [comment]
It's not a critical bug and the fix can't be backported, because it's probably side-effect of major debugger and script editor changes. Not really worth it I'd say.
