### ISSUE TITLE
Reversed TileMap tiles spanning more than one cell are positioned differently in 3.2 vs 3.1

### ISSUE THREAD

**Issue by soundgnome** [godotengine/godot#35841]
This may well fall into the category of "not worth fixing" because the behavior of Godot 3.2 is not really wrong, but it is different than 3.1.2 in a way that will break some projects. At the very least seems worth documenting as a known compatibility change.

**Godot version:**
3.2 (as compared to 3.1.2)

**OS/device including version:**
Ubuntu 19.04 x86_64

**Issue description:**
When opening a 3.1.2 project in Godot, some TileMap tiles appear in different positions. This happens when 1) the tile spans more than one cell; and 2) the tile is reversed. Here is a composite of screenshots showing the difference:

![image](https://www.dropbox.com/s/ezgwlmor8tuq1eh/tile-positions.png?raw=1)

**Steps to reproduce:**
1. Create a project in Godot 3.1.2 with a TileMap
2. Create a tile that spans more than one cell
3. Add reversed and non-reversed tiles for comparison
4. Open project in Godot 3.2

**Minimal reproduction project:**
https://www.dropbox.com/s/b761np6slii5mui/tilemap-example.zip?dl=1

**Comment by akien-mga** [comment]
See the changelog, it should be mentioned there. There's also documentation about it in the TileMap class ref, look for Tile Origin and Compatibility Mode.

**Comment by soundgnome** [comment]
Thank you fort the quick response! I still don't see this behavior mentioned in the changelog but the TileMap documentation addresses the issue for me so I'm going to close the ticket. Although if possible I would suggest adding the "breaks compat" label (I don't seem to have permissions to do so) to make this ticket easier to find in case other users run into the same thing.

**Comment by akien-mga** [comment]
> I still don't see this behavior mentioned in the changelog

Indeed, this was an oversight. I'm fixing this with #35926.
