### ISSUE TITLE
Add option for Dichoptic Contrast Enhancement (DiCE)

### ISSUE THREAD

**Issue by RMKD** [godotengine/godot#35850]
A recent paper examines a technique adjusting contrast differently for each eye to enhance image perceptions (DiCE) https://www.cl.cam.ac.uk/research/rainbow/projects/dice/ 

They include detailed tests and descriptions of how to balance the tradeoffs between 'contrast gain' and 'binocular rivalry' to maximum effect and released a Unity plugin implemation. 

It'd be great to see this incorporated as an option in the ARVRCamera.

**Comment by fire** [comment]
Can you write a proposal in https://github.com/godotengine/godot-proposals ?

**Comment by clayjohn** [comment]
Further, to @fire's request. Feature proposals should only be made in the proposals repo. This issue tracker is for bug reports only.
