### ISSUE TITLE
WindowDialog diagonal resize cursor not shown on Linux

### ISSUE THREAD

**Issue by MennoMax** [godotengine/godot#35852]
**Godot version:**
Godot Engine v3.2.stable.official

**OS/device including version:**
Linux Mint 19.3 - Cinnamon 4.4.8

**Issue description:**
When resizing a WindowDialog diagonally, no diagonal resize cursor is shown.

**Steps to reproduce:**
Place the mouse cursor on one of the corners of a WindowDialog that can be resized.
![Screenshot from 2020-02-02 14-38-37](https://user-images.githubusercontent.com/12477395/73609107-a6100700-45ca-11ea-9420-189301f8cb7d.png)

**Minimal reproduction project:**
[BugReport.zip](https://github.com/godotengine/godot/files/4144234/BugReport.zip)

**Comment by YeldhamDev** [comment]
See https://github.com/godotengine/godot/issues/14878#issuecomment-355674377.

**Comment by MennoMax** [comment]
Unlike Windows, most Linux distributions I know use the single-direction corner/side arrow instead of the double sided ones - those aren't even present in the cursor enums. I will open a feature proposal instead then.

**Comment by Calinou** [comment]
@MennoMax See also #35767.
