### ISSUE TITLE
Area doesn't detect ConcaveCollisionShape StaticBody

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot#35854]
**Godot version:** 3.2 stable

**OS/device including version:**
Linux Mint 19.3

**Issue description:** Area doesn't detect collisions with ConcaveCollisionShapes created from Meshes.

Note that I create the collision at runtime, because then I don't have to recreate the Create Trimesh Collision in the interface every time I edit the .glb on Blender. It happens even if I create the trimesh manually, tho.

**Steps to reproduce:**
Download MRP, enable visible collision shapes, run Spatial.tscn scene.

Note that the ball does collide with the ConcaveCollisionShape, but the Area ignores it.

**Minimal reproduction project:**
[MRP.tar.gz](https://github.com/godotengine/godot/files/4144680/MRP.tar.gz)

**Comment by lakshay-angrish** [comment]
What am I supposed to observe after the reproduction? Is it this: The ball collides with the monkey and passes through the cube? Also, I couldn't find any ConcaveCollisionShape in the MRP.

**Comment by jabcross** [comment]
@lakshay-angrish, the Area prints its collisions to output every frame. The ball collides with the monkey to demonstrate that the collision shape is there and working. I'd expect it to print the name of the monkey, but it doesn't.

The shape of the monkey is generated at runtime, use the Remote scene tree to view it when the game is running.

**Comment by Phischermen** [comment]
Hello @jabcross 
I made a PR (#33690) a little while ago hoping to fix this issue. Maybe you could see if it solves your problem?

**Comment by jabcross** [comment]
Awesome, thanks! I'll check asap.

**Comment by jabcross** [comment]
It works. Thanks!

**Comment by AndreaCatania** [comment]
This seems fixed, so I'm closing it :)

**Comment by akien-mga** [comment]
@AndreaCatania It's fixed by a yet unmerged PR from what I read.

**Comment by AndreaCatania** [comment]
Ops,
