### ISSUE TITLE
Gridmap doesn't import meshlib item transform and doesn't allow edit 

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#35860]
**Godot version:**
3.2

**OS/device including version:**
Win10

**Issue description:**
I make a brand new meshlib, 1 single item. When editing meshlib.tscn, I set item scale to 10,10,10, then export to meshlib.meshlib
Now I create new gridmap node, where I link meshlib.meshlib.: item scale has been lost.
I try to set manually, the inspector always reset to default.

[mrpMeshlib.zip](https://github.com/godotengine/godot/files/4145279/mrpMeshlib.zip)

**Steps to reproduce:**

open mrpMeshlib.zip in godot, open spatial.tscn, select gridmap, select meshlib, select item 1, try to change transform.

**Comment by rilpires** [comment]
This is the kind of feature that I thought it wasn't even proposed to be there, but it would be very useful

**Comment by akien-mga** [comment]
Fixed by #52298.
