### ISSUE TITLE
Gradient.remove_point does not allow fewer than two points. 

### ISSUE THREAD

**Issue by ntsik** [godotengine/godot#35863]
**Godot version:** 3.2.stable.official

**Issue description:** `Gradient.remove_point` explicitly disallows removing points when there are already `<= 2` points. However, the editor itself does allow having fewer than two points in a `Gradient`, and having only one point does indeed seem to work.

IMO it makes sense to disallow removing all points, but I do think allowing a single point should be acceptable. In my case, I'm passing an array of one or more `Color`s to use for the given `GradientTexture`. As a workaround, I'm currently setting `gradient.colors` and `gradient.offsets` directly:

```
var color_count := colors.size()

if color_count == 1 && gradient.get_point_count() != 1:
	gradient.colors = PoolColorArray(colors)
	gradient.offsets = PoolRealArray()
	gradient.offsets.append(0)
else:
	for i in range(color_count, gradient.get_point_count()):
		gradient.remove_point(i)
```

**Steps to reproduce:**
1. Create a `Gradient` (by default it has only two points)
2. Create a script that calls `Gradient.remove_point`
3. Observe the error: `remove_point: Condition "points.size() <= 2" is true.`

**Minimal reproduction project:**
Link to relevant source code here: https://github.com/godotengine/godot/blob/0edcb8ed58be8bf6a5145ceaae5ff96778afb2a2/scene/resources/gradient.cpp#L134

**Comment by aaronfranke** [comment]
Fixed by #35924.
