### ISSUE TITLE
String.humanize_size fails when "size" is large

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#35872]
**Godot version:**
Godot Engine v3.2.stable.official

**OS/device including version:**
Linux

**Issue description:**
—

**Steps to reproduce:**

```gdscript
tool
extends EditorScript

func _run():
    print(String.humanize_size(9223372036854775807))
```

[error.log](https://github.com/godotengine/godot/files/4147066/error.log)

**Comment by qarmin** [comment]
There is no need to use tool in script to crash project
```
extends Node2D
func _ready():
    print(String.humanize_size(9223372036854775807))
```
![AAAA](https://user-images.githubusercontent.com/41945903/73644960-a1089180-4676-11ea-9c0f-7e6fe141283a.png)
