### ISSUE TITLE
[Godot 3.1.2] Windows Universal Logo 150x150 issue

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#35871]
**Godot version:**
3.1.2

**OS/device including version:**
macOS Catalina 10.15.3

**Issue description:**
In Export - Windows Universal - Images, the Logo image 150x150 is having problems recognising the image, even though the image is precisely 150x150.

**Steps to reproduce:**

**Minimal reproduction project:**

![Screenshot 2020-02-03 at 10 07 26](https://user-images.githubusercontent.com/13488692/73640930-d366be80-4677-11ea-9c34-d14f92e2eb17.png)

**Comment by qarmin** [comment]
https://github.com/godotengine/godot/blob/6fa716c67b6f17f3818858785619839da060abe7/platform/uwp/export/export.cpp#L1179
At the end should be probably 150, 150

**Comment by drmar** [comment]
Yes, indeed. I think I see the problem. How do I go about helping with this issue?

I never contributed to Godot before and I should mention that I am a beginner when it comes to coding.

**Comment by eon-s** [comment]
@drmar if you can first compile form source and test the change, it will help.
Then you can try to follow the docs on contributing, it may be easy for this kind of changes (using git could be the hardest part), or wait until somebody else does it and use your fixed version meanwhile.

https://docs.godotengine.org/en/3.1/community/contributing/pr_workflow.html

**Comment by doot24** [comment]
Same issue is present on 3.2, i can submit a PR but should it be for 3.1 or 3.2? or both?

**Comment by Zireael07** [comment]
Submit a PR against master, it'll go into 3.2. and probably be cherrypicked (=copied, in simplest terms) into 3.1.
