### ISSUE TITLE
Vehicle-Wheels gets a random engine_force at start

### ISSUE THREAD

**Issue by tobiblender** [godotengine/godot#35879]
**Godot version:**
3.2 stable
**OS/device including version:**
win8
**Issue description:**
everytime i start the game, every wheel (of every vehicle) gets a different random engine_force applied out of nowhere.
It just happens as long as i dont apply a engine_force to the wheels or vehicle-body.
Surly has to do with the new per-wheel engine_force options.
worked in Version 3.1.2 (same project)
**Steps to reproduce:**
open the project-file an press F5
**Minimal reproduction project:**
[Vehicle_Bug_Demo1.zip](https://github.com/godotengine/godot/files/4148449/Vehicle_Bug_Demo1.zip)
no settings, no script, just a standard vehicle that goes crazy :)

**Comment by owstetra** [comment]
Yes i have this Issue too , but i set engine_force = 0 in _ready function to avoid that.
you can do that as a Temporary solution.

**Comment by tobiblender** [comment]
thank you for the confirmation.  :)
yes i did that workaround, BUT i noticed that this random force adds to the engine_force that i apply somehow... sometimes... very strange. So some vehicles are faster now... some tend to steer to the right/left depending on the random force bugy thingy added at the start.
Needs to be fixed anyway for sure.

**Comment by Janglee123** [comment]
Please share the demo project.  Also correct the version name to 3.2.

**Comment by tobiblender** [comment]
Hi, okay i made a little demo project.
no scripts, no settings... just a plane and a vehicle.
press play to see the bug... if you start it again you see, the effect is little bit different each time.
thank you for helping :)
[Vehicle_Bug_Demo1.zip](https://github.com/godotengine/godot/files/4148397/Vehicle_Bug_Demo1.zip)

**Comment by Janglee123** [comment]
Woah. I can reproduce this. Sometimes vehicle standstill and sometimes it spins like a hell.
I changed y coordinate to +5 and I get a similar result when the vehicle touches the plane. until then the vehicle doesn't show any movement.

**Comment by tobiblender** [comment]
yeah, of course this just happens if the wheels touch the ground.
because the reason of the spinning vehicle is the different random engine_force bug on every wheel

**Comment by tobiblender** [comment]
so its fixed for 4.0 ?
can it be closed ?

**Comment by Calinou** [comment]
@tobiblender I don't know if this was fixed in the `master` branch. It's currently very unstable, but you could try recreating a minimal project there.

**Comment by Janglee123** [comment]
@tobiblender I have opened pull request for 3.2 branch. It might get merged for the maintenance release.

**Comment by akien-mga** [comment]
Fixed by #36236.
