### ISSUE TITLE
Renaming nodes in scene tree pane causes unexpected edit box location

### ISSUE THREAD

**Issue by Beechside** [godotengine/godot#35876]
Godot 3.2 Stable

Mac OS Catalina 10.15.2

Description:
Renaming nodes in scene tree pane causes unexpected edit box location

Steps:
Select a node in the scene tree
Use cursor keys to select the another node
Press Return to edit node name
Edit box appears in top left instead of above the node name

Possibly linked to #8652

![Rename box in wrong position](https://user-images.githubusercontent.com/5500886/73646089-9519d100-4670-11ea-904d-d4a7f58415ba.png)

Minimal reproduction project:

[rename test.zip](https://github.com/godotengine/godot/files/4147382/rename.test.zip)

**Comment by Torguen** [comment]
It also happens in 3.2 stable mono win10 64

**Comment by YeldhamDev** [comment]
Unable to reproduce this on Manjaro GNU/Linux.

**Comment by KoBeWi** [comment]
This happens when a different node gets focused than currently selected one. Enter renames the focused node but name edit appears at selected node.

But it doesn't seem to be possible to focus non-selected node as using arrows will select nodes, so not sure how to reproduce.
