### ISSUE TITLE
Vehicle Instance is broken (nan error)

### ISSUE THREAD

**Issue by tobiblender** [godotengine/godot#35877]
**Godot version:**
3.2 stable
**OS/device including version:**
Win8
**Issue description:**
i instance a vehicle (tscn) several times per gdscipt (preload) in a for-loop.
the first instance is allways somehow broken - it gets transform-vectors with "-1.#QO" throws an error. 
i found out about the cause via the debugger > breakpoints feature

the console puts Error NAN 
**E 0:00:00.712   instance_set_transform: Condition "Math::is_nan(v.x)" is true.
  <C++-Quellcode>servers/visual/visual_server_scene.cpp:601 @ instance_set_transform()**

**Steps to reproduce:**
- open the project
- open the scene vehicle_instance_bug.tscn
- press F5
- the output throws the NAN Error

as i said - i investigated via debugger and found out that the error is allways from the first instance
the following instances are fine. 

**Minimal reproduction project:**
[Vehicle_instance_bug_1.zip](https://github.com/godotengine/godot/files/4148877/Vehicle_instance_bug_1.zip)

**Comment by tobiblender** [comment]
PS: this does not happen in 3.1.2  (with same project)

**Comment by groud** [comment]
Please provide a minimal reproduction project.

**Comment by tobiblender** [comment]
Hi again :)
okay i made a mini-project to show it off.

**Comment by matkoniecz** [comment]
It appeared to me after clean Godot install, downloading Truck Town project and selecting Tow Truck as an option.

**Comment by Demindiro** [comment]
I suspect it is a thread synchronization issue, since changing seemingly unrelated things "fixes" it (e.g. if the VehicleBody node is not in a separate scene the bug won't occur, if it is it does) and it doesn't happen consistently. In either case, I tried to narrow it down as much as possible.

[vehicle_is_nan.zip](https://github.com/godotengine/godot/files/5281567/vehicle_is_nan.zip)

When spamming the "Spawn" button, the issue does occur eventually.

**Comment by qarmin** [comment]
I found that `m_suspensionLength` variable was uninitialised and sometime had Nan value.
From my tests initializing it with zero fixes problem.

**Comment by pouleyKetchoupp** [comment]
Junior job hint:
Based on https://github.com/godotengine/godot/pull/44125#issuecomment-772445577, this issue can be fixed separately from #44630/#44125 by just setting the default value to `m_suspensionLength`.
