### ISSUE TITLE
forward_gui_input function in tool script doesn't work

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#35889]
**Godot version:**

be1bc53d4

**Issue description:**

Both `forward_canvas_gui_input` and `forward_spatial_gui_input` require  `handles` to be implemented, but the examples don't have it, which leads to confusion when trying them out.

I suggest including `handles` in the examples.

**Comment by KoBeWi** [comment]
You need to implement [handles](https://docs.godotengine.org/en/latest/classes/class_editorplugin.html#class-editorplugin-method-handles) method for it to work.

**Comment by Jummit** [comment]
```Called when there is a root node in the current edited scene, handles() is implemented and an InputEvent happens in the 3D viewport. Intercepts the InputEvent, if return true EditorPlugin consumes the event, otherwise forwards event to other Editor classes.
```
Totaly overread the important part.
I thought the example provided would work on its own:
```
 Example:

# Prevents the InputEvent to reach other Editor classes
func forward_spatial_gui_input(camera, event):
    var forward = true
    return forward

Must return false in order to forward the InputEvent to other Editor classes. Example:

# Consumes InputEventMouseMotion and forwards other InputEvent types
func forward_spatial_gui_input(camera, event):
    var forward = false
    if event is InputEventMouseMotion:
        forward = true
    return forward
```
Maybe that could be clarified.

**Comment by KoBeWi** [comment]
Maybe let's just repurpose this for a documentation issue, so other users don't get confused. The requirements to use this method could certainly be written more clearly.

**Comment by Jummit** [comment]
The new documentation addresses this.
