### ISSUE TITLE
Godot autogenerated signals functions doesnt create in VSCode

### ISSUE THREAD

**Issue by uSources** [godotengine/godot#35885]
**Godot version:** 3.2 Mono

**OS/device including version:** Windows 10

**Issue description:** Godot doesnt add singal function to a script file.

**Steps to reproduce:** Using Godot Mono and VSCode as IDE. Try to attach one signal to script, VSCode opens up but doesnt add signal function to C# script.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Duplicate of #23208.
