### ISSUE TITLE
Several erros occur when saving a scene with only a Script Class node in the tree

### ISSUE THREAD

**Issue by mausedev** [godotengine/godot#35895]
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10 x64 version 1909

**Issue description:**
Several errors that seem to be related to image handling occur when saving a scene with a _Script Class_ and no other nodes. Adding another node to the scene that is not a _Script Class_ or the Class that it extends from seems to solve the issue. Adding a custom icon to the _Script Class_, saving the script and reopening the project also stops the errors, so it may be related to #35896.

![error_1](https://user-images.githubusercontent.com/37230539/73702751-819c5380-46cc-11ea-8cb4-f4992726e1e0.png)

**Steps to reproduce:**
1. create a new project.
2. create a GDScript script and open it.
3. register the script as a _Script Class_ with `class_name MyClass` and save it.
4. open the node creation dialog, search for the _Script Class_ and add it to the tree. 
5. save the scene. The editor will output several erros.
6. Add any other node to the scene that is not the _Script Class_ or the Class that it extends from.
7. Save the scene. The erros won't occur anymore.

**Comment by Anutrix** [comment]
Could Image.duplicate() or Image.decompress() be the issue?

**Comment by KoBeWi** [comment]
I can't reproduce this error following the given steps.
Does the script need to extend some particular node? Any minimal project?

**Comment by Calinou** [comment]
@mausedev It seems following the steps isn't enough to reproduce the bug (per @KoBeWi's comment). Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
