### ISSUE TITLE
Editor crashes with no warning when a resource contains itself

### ISSUE THREAD

**Issue by Hasenn** [godotengine/godot#35890]
I experimented with an editor-time decorator pattern like this one:
```python
#inside Coffee.gd
extends Resource

class_name Coffee

export(String) var description = ""
#inside AddonsDecorator
extends Coffee

class_name AddonsDecorator
export(Resource) var decoratee
```

It works well, but if you:
-create a new AddonsDecorator resource
-drag and drop it to its decoratee slot
it will crash godot instantly with no warning

I think this pattern is pretty usefull when working with designers that don't want to touch code,
for example in an RPG for spells you could use that to add effects to a spell, from subclasses of that decorator that a programmer coded, easily and with good single-responsibility.

It is especially easy to accidentally drag and drop the decorator in itself when wanting to place it in a scene node's script variables due to the disposition of the editor, and a simple misclick might result in loosing everything you worked on in the last hours or so.

It would be great if godot **threw a warning** asking if you really want to put that resource in itself before attempting to do it and crashing

Attached is an example project, **to reproduce** open myCaramelAddon and drag'n'drop it on it's decoratee slot
[Godot_Editor_Time_Decorator.zip](https://github.com/godotengine/godot/files/4149518/Godot_Editor_Time_Decorator.zip)

Godot 3.2 on windows 10

**Comment by KoBeWi** [comment]
Looks related to #24146
Probably same issue, but more general case.

**Comment by groud** [comment]
Indeed, this is a specific sub-case of #24146. Closing as a duplicate.
