### ISSUE TITLE
Duplicate InputEventJoypadButtons

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#35903]
**Godot version:**
3.2

**Issue description:**
I have an XBox One controller. Whenever I press any button, I get double input events.
This
```
func _input(event: InputEvent) -> void:
	if not event.is_action_type():
		return
	if event is InputEventJoypadButton:
		prints(event.button_index, event.pressed, event.pressure)
```
results in
```
0 True 0
0 True 0
0 False 0
0 False 0
```
This is weird though, because I don't remember having this issue before and it's the same in 3.1 and 3.0. I checked if my controller isn't somehow duplicated in the system, but it doesn't seem to be the case and also non-Godot games don't have this issue.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4154395/ReproductionProject.zip)

**Comment by akien-mga** [comment]
Seems to work fine here on Linux with a generic PS3/PC controller, as well as with a Steam Controller emulating an Xbox 360 controller:
```
0 True 0 Prepare for trouble
0 False 0 and make it double
```

It does sound like something's off with your device, especially if it used to work fine but now you get the same issue from 3.0 to 3.2.

**Comment by zenvoid** [comment]
@KoBeWi : Are you on OS X, by any chance? I don't know if it's the same issue, we have recently noticed duplicated input events that only seems to happen on OS X...

**Comment by KoBeWi** [comment]
I'm on Windows 10. The issue seems to have stopped btw :I

**Comment by 27thLiz** [comment]
I can't reproduce this on win10 / xbox360 controller.
However, there's a similar issue on master: https://github.com/godotengine/godot/pull/40770#issuecomment-667544538
But rather than duplicated events, `_input()` is called twice

**Comment by KoBeWi** [comment]
Well, I can still reproduce it (on a Xbox ONE controller as I mentioned). The issue doesn't happen with an emulated Xbox 360 controller.

The master issue is unrelated.

**Comment by KoBeWi** [comment]
Ok, I found out what is the potential cause, although it doesn't make much sense xd

My controller is wireless. I used to plug it with cable, but the socket broke and I switched to using it wireless. The duplicate input happens only when the controller is connected via bluetooth. It doesn't happen on USB.

**Comment by williamd1k0** [comment]
> @KoBeWi  The duplicate input happens only when the controller is connected via bluetooth. It doesn't happen on USB.

I tried using Xbox One Controller via bluetooth and it's working fine, but I'm using the [xpadneo](https://github.com/atar-axis/xpadneo) driver (Manjaro Linux).

Btw, I came from #21550.
