### ISSUE TITLE
Editor runs at 100% CPU and refuses to quit with 0s sound.

### ISSUE THREAD

**Issue by Beuc** [godotengine/godot#35907]
**Godot version:**
3.2

**OS/device including version:**
GNU/Linux

**Issue description:**
When importing an empty sound file, the editor goes 100%, can't quit and has to be killed.
There is no way to understand where this comes from, short of removing all project files bisect-style.

**Steps to reproduce:**
Place empty.ogg in a Godot project, let auto-import happen.
[empty.ogg.zip](https://github.com/godotengine/godot/files/4154863/empty.ogg.zip)
empty.ogg was created by running Audacity, adding a new (empty) mono track, and saving as .ogg.

**Minimal reproduction project:**
[empty_ogg_of_death.zip](https://github.com/godotengine/godot/files/4154897/empty_ogg_of_death.zip)

**Comment by Anutrix** [comment]
Related https://github.com/godotengine/godot/issues/34734.

**Comment by bruce965** [comment]
Hi, the bug seems to be triggered from the preview generator, entering an infinite loop while trying to fill the buffer of a loopable audio of length zero.

The following patch would fix this problem.

I would like to open a PR as my first contribution, if this is fine for you.

```diff
diff --git a/modules/stb_vorbis/audio_stream_ogg_vorbis.cpp b/modules/stb_vorbis/audio_stream_ogg_vorbis.cpp
index b80b126bde..f2d0f5c9a6 100644
--- a/modules/stb_vorbis/audio_stream_ogg_vorbis.cpp
+++ b/modules/stb_vorbis/audio_stream_ogg_vorbis.cpp
@@ -57,7 +57,7 @@ void AudioStreamPlaybackOGGVorbis::_mix_internal(AudioFrame *p_buffer, int p_fra
 
                if (todo) {
                        //end of file!
-                       if (vorbis_stream->loop) {
+                       if (vorbis_stream->loop && mixed > 0) {
                                //loop
                                seek(vorbis_stream->loop_offset);
                                loops++;
				// we still have buffer to fill, start from this element in the next iteration.
				start_buffer = p_frames - todo;
			} else {
				for (int i = p_frames - todo; i < p_frames; i++) {
					p_buffer[i] = AudioFrame(0, 0);
				}
				active = false;
				todo = 0;
			}
		}
```

**Comment by Calinou** [comment]
@bruce965 Feel free to open a pull request for this :slightly_smiling_face:
