### ISSUE TITLE
Suggestion - Project list organization

### ISSUE THREAD

**Issue by basteez** [godotengine/godot#35905]
It would be great if the project in project list could be filterable (i.e. using tags) or organized in folders.

For example: I have both tutorials and work project loaded and need to hide the tutorials while I'm working

**Comment by volzhs** [comment]
better to post it here with filling all required fields.
https://github.com/godotengine/godot-proposals/issues

**Comment by KoBeWi** [comment]
It was already suggested in #8167 an #7128.

Closing as duplicate (you can still make a proper proposal as suggested above).
