### ISSUE TITLE
Debugger string var values not visible using light themes

### ISSUE THREAD

**Issue by tx350z** [godotengine/godot#35904]
**Godot version:**
3.2.stable.office

**OS/device including version:**
Windows 8.1 with all patches

**Issue description:**
When using any light editor theme debugger string values are not visible due to text color.

**Steps to reproduce:
Editor/Editor Settings/Theme/Preset = Solarized (Light)
[code]var astring = "This is a string"[/code]
Set break point to see the var in the debugger
The value of astring barely visible. Click on the value and select-all, value appears when highlighted.
![debugger_string_bug1](https://user-images.githubusercontent.com/956567/73763903-b85b8380-4737-11ea-8ce3-804fe8325b80.PNG)
![debugger_string_bug2](https://user-images.githubusercontent.com/956567/73763915-bbef0a80-4737-11ea-8c30-d53936a504da.PNG)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
I had a look at this issue in [editor/debugger/script_editor_debugger.cpp](https://github.com/godotengine/godot/blob/master/editor/debugger/script_editor_debugger.cpp) and [https://github.com/godotengine/godot/blob/master/editor/debugger/editor_debugger_tree.cpp](https://github.com/godotengine/godot/blob/master/editor/debugger/editor_debugger_tree.cpp) to no avail. I don't know what's causing this :slightly_frowning_face:
