### ISSUE TITLE
_get_minimum_size() is not called for non-abstract containers

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#35909]
**Godot version:**
3.2

**Issue description:**
The `Control` virtual method `_get_minimum_size()` is not called on any scripts that inherit from the existing concrete container types (e.g. `ScrollContainer`, `MarginContainer`, `HBoxContainer` etc). It will only be called if the base class is the generic `Container` class, or any of the other `Control` derived classes.

This especially a problem when implementing custom containers that share functionality with the existing types, and hence use them as a base class.

**Steps to reproduce:**
1. Create a script that uses Control as the base class and implements `_get_minimum_size()`. Add a debug print statement (or breakpoint).
2. Create a scene with a control of type `Container`, and another control with one of the more concrete types, such as `MarginContainer`, and add the script to both of these.
3. When run, only the `Container` will trigger the print.

**Minimal reproduction project:**
[Testing-ContainerMinSize.zip](https://github.com/godotengine/godot/files/4155800/Testing-ContainerMinSize.zip)

**Comment by groud** [comment]
As I stated in the PR made for this issue, I don't think this is a good idea, there is no point in overriding the minimum size provided by the base container. Even if you would need a custom behavior that looks like a built-in container, their positioning of children node (and thus their computation of minimum size) is not meant to be overridden.

You should use the base Container node if you need custom positioning or custom minimum size computation.

**Comment by Xrayez** [comment]
I've stumbled upon recently, definitely worth documenting at least.
