### ISSUE TITLE
Viewport mouse position only updated after touch release, not touch press.

### ISSUE THREAD

**Issue by mpatraw** [godotengine/godot#3590]
Here is the example I'm using: https://www.dropbox.com/s/bngu083qctasmal/example.tar.gz?dl=0

When a mouse button is pressed _**and held**_ on desktop the viewport.get_mouse_pos() function returns the correct position. On mobile, touching and holding does not update get_mouse_position until the touch is over. I feel this is slightly inconsistent.

This may be a duplicate of #1212

**Comment by reduz** [comment]
Godot supports many mobile platforms, could you please specify which?

**Comment by reduz** [comment]
Also I don't understand the problem.. from the code it will only update the text on touch and release..  when else do you expect it to be updated?

**Comment by mpatraw** [comment]
Android. I was expecting that get_mouse_pos() would be equal to the event.pos I get on a mouse button press event. Instead get_mouse_pos() is updated after the button is released.

**Comment by akien-mga** [comment]
Closing as a duplicate of #1212. I'll add the text example there as a reference.
