### ISSUE TITLE
Editor Warning Error but still running

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#35917]
**Godot version:**
3.2 stable
**OS/device including version:**
Windows
**Issue description:**
![2020-02-05_114528](https://user-images.githubusercontent.com/34160378/73811959-9c2a1600-480d-11ea-8068-7853a6f70410.png)

My game is still running without problem, but it keep display this error in debug windows

**Comment by groud** [comment]
Sorry, but dropping an error message without the step to reproduce the error is pointless. Please describe how you manage to have this error message displayed and provide a minimal reproduction project.

**Comment by akien-mga** [comment]
Indeed, with only a screenshot it's hard to fix anything.

You might be able to solve it by cleaning up your open scripts, there might be a reference to a non-existing script in there.
