### ISSUE TITLE
Allow using different script for the root node of an inherited scene

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#3591]
This is a feature request.

Recently added feature of inheriting scene is very helpful, allowing us to derive slightly different scenes based on existing ones. It complements GDScript's extends mechanism to build on from existing code base. However, it doesn't look like these two features play well together yet.

Here's which I believe a typical scenario: I have a base character scene, with a root node KinematicBody and a script attached to it. Now, I can use "New Inherited Scene" and start adding new features (meaning, adding new nodes, which apparently I can) and so on, but this also means I need to add new behavior in the attached script. Unfortunately, the inherited scene and the base scene share the same script file, and it seems Godot doesn't (yet?) allow me to use a different script file for the root node of the inherited scene.

If it did, I could have simply use extends and build upon the base script. I think this is a necessary feature in order to have true inheritance.

**Comment by tagcup** [comment]
In other words: if we are allowed to add new nodes under the inherited scene, we should be allowed to modify the script (which is typically attached to the root node of the scene) control these new nodes.

**Comment by akien-mga** [comment]
Well, you can do this already :)

Though most of the time it's not something I would do with inherited scenes. It's more convenient to have all scenes inheriting from a common scene use an abstract script as the root node, and then be extended by specific scripts in some child node. But you can of course change the root script directly if you prefer.

**Comment by bojidar-bg** [comment]
@tagcup ~ You can already do it easily - just go to the inspector, and edit the `Node/Script` property:
![image](https://cloud.githubusercontent.com/assets/5276727/12842110/39a02892-cbf9-11e5-8c1e-5164e7bb5420.png)

**Comment by tagcup** [comment]
My gosh, this is so embarrassing.
I've been trying to use the script icon above the nodes, which didn't work. Thanks a lot, and sorry about the meaningless issue.

> Though most of the time it's not something I would do with inherited scenes. It's more convenient to have all scenes inheriting from a common scene use an abstract script as the root node, and then be extended by specific scripts in some child node. But you can of course change the root script directly if you prefer.

I've been looking for a discussion along these lines. It would be great if there was a tutorial about this, because I'm not sure if there is a best practice known to community about composing/inheriting scenes.

I'm trying to understand what benefit would that have? Does this mean you need to make an auxiliary root node (something like ``Node``) in your base scene, which has the actual scene (let's say `KinetmaticBody`) as the child?

In my particular simple use case, the base scene only contains the common behavior that will be common in all the inherited ones.

**Comment by akien-mga** [comment]
> In my particular simple use case, the base scene only contains the common behavior that will be common in all the inherited ones.

Yes, that's why its script should be shared among all nodes. It would typically be a child node (e.g. Node) that would have the script "plug-in" that enhances a given inherited scene.

There is no real documentation about this yet as it's a pretty new feature, but you can check the tower scenes in https://github.com/KOBUGE-Games/project-kumquat

**Comment by tagcup** [comment]
I'm still not clear about the advantages of that over what I'm doing right now though.

On the other hand, in what I'm doing, I don't have to create auxiliary script nodes & pass a reference of the parent to children, I don't have to split script into two parts (behaviors contained in root and node) and I can override any behavior from the parent (a behavior that belongs in tower_dispatcher cannot be overridden by children for example).
