### ISSUE TITLE
Is is possible to have [system menu bar] on Mac OS X?

### ISSUE THREAD

**Issue by zzz6519003** [godotengine/godot#35919]
**IMPORTANT, PLEASE READ**

Feature / Enhancement requests are no longer accepted in the main Godot repository.
Please open an item by filling the relevant fields in the *Proposals* repository:

https://github.com/godotengine/godot-proposals/issues/new/choose

Do not submit to this repository or your issue will be closed.

**IMPORTANT, PLEASE READ**

**Comment by groud** [comment]
Please read the message ! -_-
