### ISSUE TITLE
Unable to build with VS2019 and vsproj=yes, invalid option after "Assimp.cpp"

### ISSUE THREAD

**Issue by StarWolf3000** [godotengine/godot#35920]
**Godot version:** 3.2 stable x64 (build process)

**OS/device including version:** Windows 10 Enterprise x64 up-to-date

**Issue description:**
I cannot seem to build 3.2 stable with Visual Studio 2019 Community. I have all requirements installed, and use `scons` from `MSYS2/MINGW-w64`, which is 3.1.1:
```
$ scons --version
SCons by Steven Knight et al.:
        script: v3.1.1.72ae09dc35ac2626f8ff711d8c4b30b6138e08e3, 2019-08-08 14:50:06, by bdeegan on octodog
        engine: v3.1.1.72ae09dc35ac2626f8ff711d8c4b30b6138e08e3, 2019-08-08 14:50:06, by bdeegan on octodog
        engine path: ['c:/msys64/mingw64/lib/python3.8/site-packages/scons/SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
```

**Steps to reproduce:**
1) Have an up-to-date MSYS2 environment and install `scons` from MINGW subsystem:
`$ pacman -S mingw-w64-x86_64-scons` (will install `mingw-w64-x86_64-python` and required packages)
2) Make sure, you're using the MINGW shell, not the MSYS2 shell.
3) Clone `godotengine/godot` and change into the directory:
`$ git clone https://github.com/godotengine/godot.git && cd godot`
4) Invoke `scons` with arguments `p=windows vsproj=yes`:
`$ scons p=windows vsproj=yes`

**Output:**
Some unknown "option" appears after `Assimp.cpp`, breaking the build process in its entirety.
[Build log](https://gist.github.com/StarWolf3000/6ecb629f0877ecef26a2ac68e38589e7)

**Expected:** Build continues and provides Visual Studio solution files.

**Comment by akien-mga** [comment]
I'm not sure to understand, why are you trying to generate the `vsproj` solution with MinGW, when it's meant to be used in Visual Studio? You should use the VS 2019 command prompt for that.

**Comment by StarWolf3000** [comment]
I wanted to use the existing scons and Python from the already installed MSYS2/MinGW, instead of installing another standalone copy on the machine, and then use the generated files from that in VS. In hindsight, this should not make any difference from installing a separate copy, as the binaries from the MinGW subsystem are running natively.

Interestingly scons itself detects the already installed Visual Studio and tries to configure the build system itself.

Everything that happened until the aforementioned error is inside the Gist I've linked in my opening comment. It complains about an invalid option "Users" (the error message is in german, so I translate it here). MinGW-w64 itself is not involved in the build process for my case.

But tomorrow I will try it again with everything from inside a VS command prompt.

**Comment by akien-mga** [comment]
Right, I forgot that you could use MSVC from a MSYS2 command prompt (I use it from `git-bash.exe` myself, but both should work).

Can you run it in verbose mode (`verbose=yes`) so that we get more details on where this "Users" comes from?

**Comment by akien-mga** [comment]
Note that you don't need to use `vsproj=yes` if you just want to build the engine. This option is to generate a solution that can be used for engine development/debugging within Visual Studio, but to use the `cl.exe` compiler, you can simply use `scons p=windows`.

**Comment by StarWolf3000** [comment]
Will do that tomorrow, and report back afterwards.

**Comment by StarWolf3000** [comment]
Found the problem with `verbose=yes`:
`cl @C:/Users/dresden/AppData/Local/Temp/tmp1d1vl1ak.lnk`

Running it in MSYS2 default shell (mintty) does not have the correct path style. I think it requires to be Unix-style with escaped spaces for the includes (`cl @/c/Users/dresden/AppData/Local/Temp/tmp1d1vl1ak.lnk`) or escaped double backslashes (`cl @"C:\\Users\\dresden\\AppData\\Local\\Temp\\tmp1d1vl1ak.lnk"`). Running it in a CMD-style shell and invoking scons with a full path, the build succeeds.

**Comment by ShlomiRex** [comment]
If you fixed it please close it

**Comment by akien-mga** [comment]
Well it's not fixed...

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by StarWolf3000** [comment]
I no longer have access to that build PC, unfortunately, so I can't test this. However, if the build script didn't change for the output of VS solutions, then it should still error out, when calling MSVC from a MSYS2/MINGW prompt outside of the Windows console host.

**Comment by Calinou** [comment]
@StarWolf3000  Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by StarWolf3000** [comment]
I have not attempted to build Godot on my own since then.

**Comment by Calinou** [comment]
Closing for now. Please comment if you (or anyone else) can reproduce this on the latest Godot version.
