### ISSUE TITLE
Sprite is gone when move position inside CanvasLayer

### ISSUE THREAD

**Issue by mliitfall** [godotengine/godot#35921]
When you make child node like this :
-Node
--CanvasLayer
---Sprite
----Sprite2

When you move Sprite2 position, it will be gone. I don't know where it goes.
But if using just Sprite, and move it, it will run normally.
Can you explain this?

**Comment by doot24** [comment]
Can you post some additional information? Godot version, OS/device information, and a Minimal reproduction project.

**Comment by groud** [comment]
Sorry, this is not the place to ask about how to use the engine. Please use the [other community channels](https://godotengine.org/community) for this purpose.
