### ISSUE TITLE
Area2D get_overlapping_areas not update if area not move

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#35927]
**Godot version:**
Godot 3.2 Steam

**OS/device including version:**
Windows 10 Profession

**Issue description:**
Area.get_overlapping not update if it not change the position, seems its a old problem
https://godotengine.org/qa/56354/get_overlapping_areas-working-when-changing-collision-size

**Steps to reproduce:**
Add two Area 2D node, then let them overlap in the editor. Set the one node only has 1 collision layer, and the other mask layer to 1. So it's will collide now. Then set one node's mask layer false, so they should not collide now, but if you use Area.get_overlapping_area, it still shows they collide

If you set the position of area2D after you change its mask layer, then you'll get the right result.

Code

```
extends Node2D

var tick = 12

func _process(delta):
	tick -= 1
	if !$Area2D.get_overlapping_areas().empty():
		print("BoxBcollide")
	if tick == 0:
		$Area2D.set_collision_layer_bit(0, false)#disable area layer
		$Area2D.position = Vector2(0, 0)#change the position of Area2D so it's update now


```
The node will keep print"BoxCollide" if comment the set position code.

I'm not sure whether that is a feature, if it is, It should mention that in the documentation

**Comment by groud** [comment]
Please fill in the issue template instead of deleting it right away. I will reopen once it is done.

**Comment by firecloud888** [comment]
Please reopen it, thank you :D

**Comment by groud** [comment]
Related to, if not duplicate, of #23484
