### ISSUE TITLE
Warning: ColorPicker gets too friendly

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3592]
Following a small change in ddf2173, we get this warning:
```
In file included from ./tools/editor/property_editor.h:37:0,
                 from ./tools/editor/editor_node.h:47,
                 from main/main.cpp:57:
./scene/gui/color_picker.h:93:14: warning: class 'ColorPicker' is implicitly friends with itself
 friend class ColorPicker;
              ^
```

**Comment by akien-mga** [comment]
I'm not familiar yet with the concept of friend classes, but I guess we just need to drop https://github.com/godotengine/godot/blob/ddf21735ba202bb2668205c055a37a5e8f55b8e9/scene/gui/color_picker.h#L93 ?

**Comment by bojidar-bg** [comment]
@akien-mga I think so

Also, :+1: for the issue title XD

**Comment by reduz** [comment]
Should stop picking itself

**Comment by MarianoGnu** [comment]
this issue should go to @TheStrangeLog on twitter...
