### ISSUE TITLE
Bug: Particlesystem and the amount of particles?

### ISSUE THREAD

**Issue by UnityFuchs** [godotengine/godot#35928]
**Godot version:**
3.1.1.stable.official

**OS/device including version:**
Ubuntu 18.04.3 LTS

**Issue description:**
If you move a particle-system (change position), it seems that it doesn't emit as it should, respectively it seems that the particle-system has an implemented timer, that "ticks" every 0.01 seconds or so.

I understand particles this way:
If I emit 100 particles and move the particle-system, in 1 second, from point_a to point_b,and the emitted particles won't overlap each other, then I need to raise the amount of particles, so that the particle-system will produce more in the same time. With enough particles, I should get a continuous line of particles, but I don't.

Watch the Video: There is no difference between 100, 1000 and 10000 particles.

[particle-system-bug.zip](https://github.com/godotengine/godot/files/4160236/particle-system-bug.zip)

If this is not a bug, please tell me how I can achieve my goal.

Thank you

**Steps to reproduce:**
1. Create particles
2. Move them by animation-player or drag with mouse
3. Change the amount of particles and notice, nothing changes.

**Minimal reproduction project:**

**Comment by groud** [comment]
The thing is that particles are generated every frame, so you are limited by the frame rate of your screen. There is kind of no way around it, if you want to have a continuous line, you will need ribbons particles as proposed in #22217, which is not implemented yet.

**Comment by clayjohn** [comment]
You can also use ``fixed_fps`` to get much closer to a continuous stream of particles. But you will still be limited by your frame rate. http://docs.godotengine.org/en/latest/classes/class_particles.html#class-particles-property-fixed-fps
