### ISSUE TITLE
IP.get_local_addresses() has different order for Windows and Linux

### ISSUE THREAD

**Issue by Iddmeister** [godotengine/godot#35931]
Godot 3.2

on Linux Ubuntu 18

Not sure if this really constitutes as a bug but I'm just gonna point it out, the get_local_addresses method in IP seems to have a different order for Windows and Linux (not sure for Mac) the list might just be different for each platform but the local ip address of your computer (192.128... whatever) is element 1 on linux (IP.get_local_addresses[0]) and element 2 on Windows (IP.get_local_addresses[1])

Just thought I would point this out, not the most horrific problem in the world (can just solve it by getting the platform and then using element 1 or 2) but would be nice if they were both in the same place

**Comment by andy-noisyduck** [comment]
I think this is device specific. You would perhaps need to determine what local address actually means to your application? On my Windows laptop (which has a built in WiFi networking, a wired connection via USB, and a VPN, and also has IPv6 setup), what I would consider to be my IP4 address is element 19.
