### ISSUE TITLE
Area collision via tool function does not work in editor

### ISSUE THREAD

**Issue by rhossack** [godotengine/godot#35946]
**Godot version:** 3.2 64

**OS/device including version:** Windows 10 64

**Issue description:** I have an object with 4 areas, intended to work as snapping points. If the front area of one object overlaps the back area of another, then the object should set its position to its own position plus the difference of the two areas' positions. However, when the code runs, it always returns an empty array, even when the overlap should be registering.

**Steps to reproduce:** Create two areas that overlap. Give one a tool script that prints a list of its overlapping areas. Observe that the list is always empty.

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
IIRC there's no physics running in editor?

**Comment by Zireael07** [comment]
If I were you, I'd reopen, just someone would have to relabel it as enhancement and not as bug.

**Comment by rhossack** [comment]
I closed it because enabling the physics server fixes the problem. `PhysicsServer.set_active(true)`

**Comment by Zireael07** [comment]
Can we get that tidbit added to tool scripts documentation pages, please? I'd tag the godot-docs but it doesn't seem to let me...
