### ISSUE TITLE
Creating a shader for a label does not work as intended.

### ISSUE THREAD

**Issue by RichardR01** [godotengine/godot#35940]
**Godot version:**
3.2

**OS/device including version:**
Windows 10 v1909

**Issue description:**
Creating a shader for a label does not work as intended. It used to work in a previous version of Godot as seen in this video tutorial: https://youtu.be/6zuSFP0702w
However I found 2 issues:
Issue 1: Creating a new CanvasItemMaterial.
As shown in the image I provided, the material is useless as it has no field for a new shader or some material to work with. So how do I even work with this?
Issue 2: Creating a new Shader -> Visual Shader -> mode: Canvas Item
Creating a canvas item visual shader (or code) creates a box over each letter in my text instead of masking it. See the project for proof.

**Steps to reproduce:**
Create a new scene with a 2d node.
Add a label, type in some random text in the Text property. Change the font if you want.
Create a new shader in the material property of the label. Make it a visual shader for ease.
Add a color uniform node (or a texture node or any other color changing node).
attach the color from the Color node to the Color to the output node.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/4163228/TestProject.zip)

![canvas_item_material](https://user-images.githubusercontent.com/46553425/73906259-25b20600-4857-11ea-940e-6d47f1d071d5.jpg)

![test_project_proof](https://user-images.githubusercontent.com/46553425/73906615-61010480-4858-11ea-8ea5-349a98bbbf63.jpg)

**Comment by clayjohn** [comment]
I will address each of your 2 issues separately. First I will note, that it is expected that things in Godot 3 will work differently than in Godot 2.

**Issue 1**
> Issue 1: Creating a new CanvasItemMaterial.
As shown in the image I provided, the material is useless as it has no field for a new shader or some material to work with. So how do I even work with this?

Materials are different from shaders. If you want to use a shader, you must use a [ShaderMaterial](http://docs.godotengine.org/en/latest/classes/class_shadermaterial.html). Materials are used for drawing objects using the built-in shader. 

As you can see in the image, you can change various settings in the CanvasItemMaterial. Please see the [CanvasItemMaterial](http://docs.godotengine.org/en/latest/classes/class_canvasitemmaterial.html#class-canvasitemmaterial) for what each setting does. (Alternatively, you can just hover over each property to get the description)

**Issue 2**
> Creating a canvas item visual shader (or code) creates a box over each letter in my text instead of masking it. See the project for proof.

In the example you posted you are setting the label to a solid color (``ColorUniform``). ``ColorUniform`` is set to solid black. Accordingly, your label is appearing solid black. This is not a bug, it is exactly as intended. If you want the text to appear, you should not be making the label solid black, you should continue to use the ``TEXTURE`` uniform to get the font. 

Now, before you say it isn't documented (as you claim on discord) it is documented [here](http://docs.godotengine.org/en/latest/tutorials/shading/your_first_shader/your_first_canvasitem_shader.html#using-texture-built-in) and [here](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/canvas_item_shader.html#fragment-built-ins)


Now, as a final note, myself and others were attempting to assist you on discord. Discord is the proper place to get help when you need assistance figuring out the basics of the engine. The issue tracker is for bug reports only. We are overburdened enough with issue reports as it is and asking for help on basic issues in the form of a bug report is not okay. By doing so you are forcing devs to take time away from improving the engine and documentation to assist you on a basic problem. In the future, please continue seeking assistance on discord.
