### ISSUE TITLE
Per Pixel Transparency in html5

### ISSUE THREAD

**Issue by evandikt** [godotengine/godot#35951]
**Godot version:** 3.2 GLES2

**OS/device including version:** Linux 5.4.14-2-MANJARO

**Issue description:**
Hi

Per Pixel Transparency works in html5 export ? 

get_tree().get_root().set_transparent_background(true) in my _ready
Display/Window/Per Pixel Transparency/Allowed => true
Display/Window/Per Pixel Transparency/Enabled => true

On export linux, everythings is good and transparent but in html5 i got a black background !
I change the export template to have `background-color: transparent;` in body html and #canvas 

thx

**Comment by bruvzg** [comment]
Per pixel transparency is implemented on Linux, macOS and Windows only.

`Display/Window` properties do nothing on other platforms. `set_transparent_background` disables background rendering.

**Comment by evandikt** [comment]
Humm ok
And how can we have a transparent background on html5 platform @bruvzg ?

**Comment by muiroc** [comment]
Looks like something like this could work! 5d1cbc887bf94fcba714635e932fb61e44aec215 

test export, html body blue background is visible
[TransparentCanvasExport.zip](https://github.com/godotengine/godot/files/4168429/TransparentCanvasExport.zip)

Not sure about the EmscriptenWebGLContextAttributes premultipliedAlpha option,
also I guess the alpha option should be setted only if required in the project preferences

**Comment by evandikt** [comment]
@muiroc i have to rebuild godot to get this bug fix ?

**Comment by Calinou** [comment]
@evandikt Yes, you need to recompile the HTML5 export template by following the instructions in [Compiling for the Web](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_web.html).

**Comment by muiroc** [comment]
@evandikt meanwhile here's the debug-opt export template built from #36075 if you need it
[godot.javascript.opt.debug.zip](https://github.com/godotengine/godot/files/4181075/godot.javascript.opt.debug.zip)
