### ISSUE TITLE
CanvasLayer's Follow Viewport doesn't translate inputs correctly

### ISSUE THREAD

**Issue by cgbeutler** [godotengine/godot#35965]
**Godot version:**
3.2

**OS/device including version:**
Windows10

**Issue description:**
Turning on `Follow Viewport` `Enable` on a `CanvasLayer` translates child controls to the right place, but inputs are triggering in the non-follow spot
![ViewportBug](https://user-images.githubusercontent.com/9751923/73982217-1089b580-48f1-11ea-8c5f-4aee4e5371a8.gif)

**Steps to reproduce:**
In a Node2D scene, add a centered Camera2D set as the current camera
Add a `CanvasLayer` with `Follow Viewport > Enable` set to true
In the `CanvasLayer` add a button
Hit play. The button will get hover and click events when the mouse is in the top left corner of the screen instead of when the mouse is over the button

**Minimal reproduction project:**
https://github.com/cgbeutler/FollowViewportBug

**Comment by chepulis** [comment]
I'm experiencing this bug, separately, in my project.

**Comment by Byteron** [comment]
Same issue here, using 3.2.1

**Comment by renatodex** [comment]
Omg, can't believe this bug already exists and it's not fixed!

**Comment by renatodex** [comment]
@Calinou , can you help me to know where this needs to be changed? I can make a PR for that, just need some orientation.

**Comment by Calinou** [comment]
@renatodex I don't know why this bug happens, but the CanvasLayer source code is here: https://github.com/godotengine/godot/blob/master/scene/main/canvas_layer.cpp

**Comment by cgbeutler** [comment]
@renatodex Are you experiencing it with Camera2D or Camera (3D)? Part of me thinks it's tied to the fact that Camera2D is kinda just a hack for setting a viewport's transforms and isn't actually a real camera. I haven't really dug into, though. Good luck

**Comment by cgbeutler** [comment]
@renatodex Disregard my deleted comment. I forgot what this was about.
Camera2D does work in a strange way. From the Camera2D docs:
>This node is intended to be a simple helper to get things going quickly and it may happen that more functionality is desired to change how the camera works. To make your own custom camera node, inherit from Node2D and change the transform of the canvas by setting Viewport.canvas_transform in Viewport (you can obtain the current Viewport by using Node.get_viewport).

I think the camera2D's transform applied on the canvas seems to be the issue.
If you don't use a Camera2D at all and put in the following code:

```coffeescript
func _ready():
	var viewport :Viewport = get_viewport()
	viewport.canvas_transform = Transform2D(0, Vector2(100,100))
```
You get the same error as above. Therefore, it would seem that the viewport's canvas_transform is not being applied to the input events? Maybe?

**Comment by cgbeutler** [comment]
Looks like it could be related to `make_input_local` in CanvasItem:
https://github.com/godotengine/godot/blob/master/scene/main/canvas_item.cpp
It currently does this:
```cpp
Ref<InputEvent> CanvasItem::make_input_local(const Ref<InputEvent> &p_event) const {
	ERR_FAIL_COND_V(p_event.is_null(), p_event);
	ERR_FAIL_COND_V(!is_inside_tree(), p_event);

	return p_event->xformed_by((get_canvas_transform() * get_global_transform()).affine_inverse());
}
```
Which, if my tired brain is correct, it shouldn't apply the canvas transform AND the global transform if it's layer is set to "follow viewport"? Maybe? I should get some sleep then come back to it...

**Comment by Okatt** [comment]
I'm having the same issue in 3.2.3 :/

**Comment by GabrieleTorini** [comment]
Still relevant in 3.3

**Comment by renatodex** [comment]
And I believe it will be for a long time, so the best option so far is to
workaround

Em seg., 26 de abr. de 2021 às 19:40, Gabriele Torini <
***@***.***> escreveu:

**Comment by cgbeutler** [comment]
Just discovered a possible clue:
With this setup
![image](https://user-images.githubusercontent.com/9751923/149641435-0e648d7b-d76e-4148-8dc4-d87e79bd856f.png)

When a camera is active `$RootButton.get_global_mouse_position()` returns the correct global position while `$CLButton.get_global_mouse_position()` seems to return a local mouse position. Pretty sure it shouldn't do that..?

I am _definitly_ to naive to fix this myself. Poking around in the code has only made me more confused about how canvases and transforms work.

**Comment by Sauermann** [comment]
Here is a MRP for Godot 4: [BugCanvasLayerFollow.zip](https://github.com/godotengine/godot/files/8375657/BugCanvasLayerFollow.zip)

**Comment by MASTRIO** [comment]
I'm having this issue in 4.0.3

**Comment by Sauermann** [comment]
@MASTRIO I'm unable to replicate the issue in v4.0.3.stable.official [5222a99f5] and v4.1.beta.custom_build [01453ab7f].
Please provide a minimal reproduction project, so that we can verify, if this is the same issue. If this is not the same issue, then it  would be best to open a new bug-report.
