### ISSUE TITLE
Editor doesn't remember Scene's snap settings

### ISSUE THREAD

**Issue by rodri042** [godotengine/godot#35960]
**Godot version:**
3.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
The editor doesn't remember my grid options in 3D. When I open my scene, the grid is always set as 0.1, 0.333333 and 0.625.

**Steps to reproduce:**
Here's a GIF:
![asdasf](https://user-images.githubusercontent.com/1631752/73968155-f6070a80-48f7-11ea-89d9-50fbdac1573a.gif)

**Minimal reproduction project:**
https://github.com/rodri042/test-godot-3d/tree/b773cdf38d51531a51cb5a809be858bc7ce22f99

**Comment by SkyLucilfer** [comment]
Hello. I will try to solve this issue.

**Comment by SkyLucilfer** [comment]
It doesn't reproduce on my computer. I tried with your project too.. 
Running on Windows 10. Tested both on development build and stable 3.2 build.

**Comment by KoBeWi** [comment]
Seems fixed in 3.2.4 beta4
