### ISSUE TITLE
Godot Code Editor Parameter Info Display Obscures Current Line

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3596]
I'm using the Godot Beta build released most recently (05 February 2016 12:56 PM) and when using the code editor the parameter suggestion popup obscures part of the line currently being edited.

![godotapisuggestionsobscurecurrentline](https://cloud.githubusercontent.com/assets/17059062/12855482/b0da4b40-cc0d-11e5-88f3-82faba20a12a.png)

**Comment by reduz** [comment]
Will be doing some changes here in 2.1 so waiting until then

**Comment by akien-mga** [comment]
Should be fixed in the current master branch, the tooltip placement was improved and is configurable.
