### ISSUE TITLE
Editor font is blurry, running the game displays the font correctly

### ISSUE THREAD

**Issue by MakMcFly** [godotengine/godot#35970]
**Godot version: 3.2

**OS/device including version: Windows 10

**Issue description: Font is blurry except when running game.

**Steps to reproduce: Editor shows blurry text, rendering game shows font correctly

**Minimal reproduction project: [font-issue.zip](https://github.com/godotengine/godot/files/4168853/font-issue.zip)

![image](https://user-images.githubusercontent.com/12297919/73998754-37171300-4928-11ea-811a-4fb889c250be.png)

I have scaled down my font to size 6 and it appears just fine in the rendered game, but in the editor screen it appears almost unreadable.

I have a custom theme with the font set on it as well as using it as the custom font.

![image](https://user-images.githubusercontent.com/12297919/73998839-72194680-4928-11ea-8da4-57ba7e97d879.png)

**Comment by MakMcFly** [comment]
Closing, because I realized it's because of the upscaling that happens for the test preview.

**Comment by jordanlis** [comment]
@KaufmanDeveloper Hey, I have the same issue, did you find a way to have a nice font in the editor ?

**Comment by Calinou** [comment]
> @KaufmanDeveloper Hey, I have the same issue, did you find a way to have a nice font in the editor ?

This issue is a duplicate of https://github.com/godotengine/godot/issues/33968. To resolve this, design your project with a higher base resolution.

**Comment by jordanlis** [comment]
> 
> 
> > @KaufmanDeveloper Hey, I have the same issue, did you find a way to have a nice font in the editor ?
> 
> This issue is a duplicate of #33968. To resolve this, design your project with a higher base resolution.

Not a solution for my game, which is as you said in a low resolution. It is by purpose but I get that this issue wont be solved, that's not a big issue for me, I was just wondering why we can't just have an option which says "I want the text to be rendered as in the game with the test resolution". 

Not a big deal again, thanks for the reply ;p

**Comment by Calinou** [comment]
>  I was just wondering why we can't just have an option which says "I want the text to be rendered as in the game with the test resolution".

It's not technically possible to achieve this with DynamicFont, but it is with the new MSDF fonts that are coming to Godot 4.0. Nonetheless, MSDF fonts are a bad fit for pixel fonts as they don't provide any hinting and generally don't look as crisp at small sizes.

**Comment by jordanlis** [comment]
> 
> 
> > I was just wondering why we can't just have an option which says "I want the text to be rendered as in the game with the test resolution".
> 
> It's not technically possible to achieve this with DynamicFont, but it is with the [new MSDF fonts](https://github.com/godotengine/godot/pull/51908) that are coming to Godot 4.0. Nonetheless, MSDF fonts are a bad fit for pixel fonts as they don't provide any hinting and generally don't look as crisp at small sizes.

Okay, I understand that this is a technical limitation. 

FYI, I don't use pixel art font, because I want a scaled UI with pixel art assets. I imagine that my choices are not common, since pixel artists usually prefer pixel art UI, but that's not my case so that's why I wanted a nice and clean UI with a scaled and antialiased font. 

Thanks for taking your time to explain this and have a nice day ;p
