### ISSUE TITLE
Inspector: Move between editable fields with Tab

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3598]
When working in the inspector it would be very convenient to be able to move between a series of input fields using the tab key. In the below image the Left Margin input field is currently selected, it would be a massive improvement in usability if you were able to hit tab to move to the next input field. Right now you have to either click between the different fields, yet, because of the slider that is often present you can't even conveniently click into the next field, meaning instead you have to hit enter then click the next input field, or you can choose to use the arrow keys and enter to move into the next field, both of which are far less convenient then a simple hit of the tab key.

![godottabtocontinue](https://cloud.githubusercontent.com/assets/17059062/12856163/77e22066-cc11-11e5-8134-9e08ae94c7fe.png)

**Comment by unpause** [comment]
+1

**Comment by kirilledelman** [comment]
Don't forget Shift + TAB to go to previous field.

How would this work with fields that are made up of two or more values ( as Vector2 fields are )? In those, TAB does move between components only.

**Comment by Faustabov** [comment]
After hitting the last field in a multi-value field it should then proceed to the next field in the property editor, would be the most natural and intuitive in my opinion. Same thing with shift-tab, if you step back it should take you through a multi-element "backwards". For instance if you stepped through two vectors it would go forward x,y,z then x,y,z and backwards z,y,x then z,y,x. Do you agree with something like that?

**Comment by RebelliousX** [comment]
This should have been done since v1.Current behavior always frustrates me.

**Comment by Demmios** [comment]
I dont like the idea of just clicking everywhere to setup the value +1 for keyboard jump throught fields

**Comment by vnen** [comment]
The Inspector is meant to be remade for 3.1, this can probably be fixed by then.

**Comment by bojidar-bg** [comment]
The inspector was remade, is this issue fixed in the new inspector?

**Comment by akien-mga** [comment]
Yes, that works fine in the new inspector (both Tab and Shift+Tab).
