### ISSUE TITLE
The connect() function conflicts with system connect()

### ISSUE THREAD

**Issue by NotHawthorne** [godotengine/godot#35987]
**Godot version:**
v4.0.dev.custom_build.c4daac279

**OS/device including version:**
Manjaro 5.4.14

**Issue description:**
In using the connect() system call, there is a naming conflict with what appears to be a signal hook function called connect(). This limits the ability to use system libraries for socket programming. I propose changing the connect() call to connect_signal(), or utilizing a namespace. 

**Steps to reproduce:**
Call connect() with system's connect() arguments.

**Minimal reproduction project:**
https://github.com/nothawthorne/godot -- Not a reproduction, but a version with that function's name changed.

I know it'd be a pain to change this call but I think it'd benefit the project to not create naming conflicts with any existing system calls.

**Comment by akien-mga** [comment]
I don't understand. `connect` is a function of `Object`, it's only available on Godot `Object`s, therefore it *is* namespaced. How does it conflict with system libraries?

**Comment by timothyqiu** [comment]
Maybe you are trying to call the socket `connect` function inside a member function of a `Object` subclass? You can explicitly select the global one with `::` operator. For example:

```c++
void FileDialog::foo() {
    // Object::connect
    connect("confirmed", this, "_action_pressed");

    // socket connect system call
    ::connect(sockfd, &serv_addr, sizeof(serv_addr));
}
```

**Comment by akien-mga** [comment]
Closing as we won't change the name of `connect`, there are many common words used in library APIs and we can't make all our API overly explicit.
