### ISSUE TITLE
KinematicBody applying force to RigidBody makes it bounce

### ISSUE THREAD

**Issue by ShlomiRex** [godotengine/godot#35985]
**Godot version:**
3.2 Stable (STEAM)

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
Here is a gif:
![Peek 2020-02-07 17-04](https://user-images.githubusercontent.com/17744127/74040504-8747b100-49cc-11ea-80b9-b590ff5696db.gif)

I am jumping high and landing on a rigidbody box collider which in turn make is bounce
**Steps to reproduce:**

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/4171454/project.zip)

**Comment by KoBeWi** [comment]
This is expected. `KinematicBody` by default enabled `infinite_inertia`, which makes it push RigidBodies. You can set it to `false` (the last argument of `move_and_slide`) to prevent this behavior, but if you want KinematicBody interact correctly with the RigidBody, you need to make it RigidBody too or handle their interactions manually by code.

As for the bouncing, you are pushing the box into the ground, so it tries to escape and might bounce as the result.
