### ISSUE TITLE
Per pixel transparency fails on Linux

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot#35980]
**Godot version:**
v3.2

**OS/device including version:**
Windows 10
Ubuntu LTS Bionic Beaver
Arch Linux

**Issue description:**
Per pixel transparency doesn't seem to work on Linux (always get black background)

**Steps to reproduce:**
- Clone the project at "https://github.com/2shady4u/godot-little-helper"
- Run the project (in the Godot Editor is ok) and see if the background is transparent.
- Linux will display a black background, while Windows will correctly show a transparent background.

**Minimal reproduction project:**
https://github.com/2shady4u/godot-little-helper

I was toying around with the transparency per pixel features and noticed they don't seem to work on Linux. Could this be verified/double-checked?

I'm doing the following:
- Allow per pixel transparency = true
- Enable per pixel transparency = true
- get_tree().get_root().set_transparent_background(true)

which works perfectly on Windows.

### Some pictures:

Linux Ubuntu:
![ubuntu_helper](https://user-images.githubusercontent.com/42484461/74021053-1fc53d80-499b-11ea-8f80-1ac8c2814905.PNG)

Windows:
![windows_helper](https://user-images.githubusercontent.com/42484461/74021057-205dd400-499b-11ea-8066-54222ecaaae4.png)

**Comment by bruvzg** [comment]
Unset `Fullscreen`, it's not compatible with per-pixel transparency, if you do need to cover the screen - use borderless window stretched to the size of the screen, but this will significantly decrease performance, and on some platforms can block all input on transparent areas. I would limit window size to the size of the visible graphics.

**Comment by akien-mga** [comment]
I tested locally and it's not working for me even without fullscreen though.
![Screenshot_20200207_112742](https://user-images.githubusercontent.com/4701338/74021950-de359200-499c-11ea-88a2-8ffbb07087d1.png)

**Comment by bruvzg** [comment]
For me it works on Kubuntu 18.04 with AMD drivers, but not on the same OS in the VM (llvm-pipe software rasterizer).

![scr](https://user-images.githubusercontent.com/7645683/74023141-9700ce80-49a7-11ea-9986-d74c8b0c37c9.png)

**Comment by jabcross** [comment]
Works for me on Linux Mint and AMD chipset.

**Comment by allkhor** [comment]
Xubuntu 16.04.6, Nvidia Geforce gtx 1060, works as expected.

**Comment by 2shady4u** [comment]
@jabcross & @allkhor Is this in full-screen mode? or in windowed mode?

Just tested again on my Ubuntu VM and it seems to work when I unset full-screen.
I'll try on my Arch as well to see if disabling full-screen also fixes this there.

**Comment by allkhor** [comment]
@2shady4u works in both cases.

**Comment by jabcross** [comment]
@2shady4u Maybe it's an issue with your window compositor. What window manager / desktop environment are you using?

**Comment by 2shady4u** [comment]
@jabcross I'm currently using KDE Plasma on my Arch Linux

**Comment by jabcross** [comment]
Maybe try a different one. Install Gnome or XFCE or something just to see if it works.

**Comment by Zireael07** [comment]
Seems to work on KDE on Manjaro, except the top bar disappeared:
![Screenshot_20200217_170053](https://user-images.githubusercontent.com/4525388/74669310-30e62980-51a7-11ea-941f-5d27932ae1a6.png)

**Comment by williamd1k0** [comment]
It's working for me.
Manjaro Linux Xfce 4.14
Godot 3.1.1

![image](https://user-images.githubusercontent.com/10428035/74680859-ad293e80-51a0-11ea-96ec-eb47e5a96022.png)

**Comment by 2shady4u** [comment]
Just tried again on Arch Linux:
Full-screen:
![fullscreen](https://user-images.githubusercontent.com/42484461/74689788-bf28d280-51dc-11ea-9f8d-b0d5b2da6794.png)

No Full-screen:
![no-fullscreen](https://user-images.githubusercontent.com/42484461/74689790-c059ff80-51dc-11ea-8852-497b7fe611df.png)

Ok, so it seems to be a problem that only specifically appears on Arch Linux...
Except the input pass-through seems to be blocked on Manjaro according @williamd1k0 ?

Someone with a Arch Linux who can double-check?

**Comment by Calinou** [comment]
@2shady4u Out of curiosity, is compositing enabled in your window manager?

**Comment by akien-mga** [comment]
When I tried earlier on Mageia 7 with KDE Plasma 5 on X11 it was also failing for me: https://github.com/godotengine/godot/issues/35980#issuecomment-583329434

**Comment by akien-mga** [comment]
> Out of curiosity, is compositing enabled in your window manager? It's optional in KWin after all.

I checked my KWin settings and this was indeed a compositing-related issue.

My compositor is enabled, but this had been overridden by KDE due to past crashes of the OpenGL rendering backend. I had a warning notifying me of it in the settings, and after re-enabling the compositor and change the rendering backend to OpenGL 3.1 (and then back to OpenGL 2.0), transparency works.

Is it the same for you @2shady4u? If so it's not a Godot bug, but a KDE quirk.

**Comment by 2shady4u** [comment]
@akien-mga yeah, it works now :D In my case the compositor was enabled but was using OpenGL2 for some reason (???). I set it the rendering back-end to OpenGL3 and now all is good!

So if @williamd1k0 's case (no input pass-through) is ok, we can close this non-issue :D
It's probably also a setting in his Manjaro.

**Comment by akien-mga** [comment]
>  In my case the compositor was enabled but was using OpenGL2 for some reason (???). I set it the rendering back-end to OpenGL3 and now all is good!

For me it still works after going back to OpenGL 2 (which is the default value IINM). So I think you had the same issue I did where it deactivated itself due to a past crash, and needed manually reactivation by changing the setting.

**Comment by 2shady4u** [comment]
@akien-mga sounds plausible :D 
It indeed also works both with XRender an OpenGL2 so it must have crashed at some point and your hypothesis is correct.

**Comment by akien-mga** [comment]
> So if @williamd1k0 's case (no input pass-through) is ok, we can close this non-issue :D
It's probably also a setting in his Manjaro.

I can confirm that I have no input pass-through either, but I think that it's expected. This feature enables transparency for the game window, but it's still a Godot window which intercepts input (which is why you're able to drag the helper around in this example, since it gets input).

If at all possible, a separate feature would likely need to be developed if this is wanted. (But that's starting to stretch the use case for a game engine a bit, even if it's cool ;)).
