### ISSUE TITLE
Inspector fields for script variables don't focus/display correctly after running project

### ISSUE THREAD

**Issue by schertudi** [godotengine/godot#36006]
**Godot version:**
3.2

**OS/device including version:**
Xubuntu 18.04
Haswell graphics with Mesa 19.2.8, if relevant.

**Issue description:**
If I have a script variable displayed in the Inspector and I run the project, the box for editing the variable breaks. It won't highlight or update when I click on it. If I type in a number, it doesn't update until I press enter. I can have the box highlight/update again by switching to another node and switching back. Switching to the "Node" tab next to the "Inspector" tab does nothing. This happens with both cs and gd scripts. Very annoying when trying to tweak variables.

On occasion, this bug doesn't happen. Some things that appear to influence this include:
- Switching to another window and running the project immediately after switching back
- Resetting the value to 0 (default)

..however it's too unreliable to get it to "work" consistently. So I'm not so sure. I think focus before/during run time has something to do with it.

**Steps to reproduce:**
Open the reproduction project, click on a Spatial node and press play. Click on the variable box for "Foo" - you (should) see the border for it flashing blue for a second before it appears to be unfocused. If you type in a number and press enter, it will update again.

**Minimal reproduction project:**
[var-display-broken.zip](https://github.com/godotengine/godot/files/4173818/var-display-broken.zip)

**Comment by KoBeWi** [comment]
Doesn't happen to me. Any chance you could record a video?

**Comment by woodbyte** [comment]
I'm experiencing the same issue on Windows 10. Here's what it looks like: https://www.youtube.com/watch?v=inTadWQfYN0

**Comment by Calinou** [comment]
I can't reproduce this on 3.5.1 (Linux).

@schertudi @woodbyte Are you viewing the Local or Remote scene tree dock on the left while editing the variable?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
