### ISSUE TITLE
Auto brace complete tries to close single quote within double-quoted string

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#36002]
**Godot version:**
3.2

**OS/device including version:**
Windows 10 x64

**Issue description:**
With Auto brace complete enabled, typing a single quote (`'`) inside a double-quoted string will insert an extra single quote as if the string was part of an evaluation block, even when the editor setting `Use Single Quotes` is disabled.  Possible regression to #16223.

**Steps to reproduce:**
Begin to type something like `"Godot's extra apostrophe"` in any script editor.  The output will try to auto-complete the apostrophe while typing inside the string.

**Comment by dreamsComeTrue** [comment]
Should the solution cover only additional` '` character inside of` ""` String (and vice-versa) ?
Or should it take also brackets` [,(,{ `into considerations.
I will push a PR fixing that, but only for first case - let me know if more changes are needed.

**Comment by nobuyukinyuu** [comment]
I haven't tried the other ones, but in my mind I imagine that when a string block is open (or the text cursor is inside one), no automatic characters should be inserted.

**Comment by dreamsComeTrue** [comment]
So, well - currently they are, auto-brace completion works inside of Strings as well.
So - should we disable those sort of feature inside of a String?

**Comment by dreamsComeTrue** [comment]
I've checked how it works in VS Code - currently they're following my first solution - so they DON'T interpolate only quotes/double-quotes inside of respective Strings (brackets are treated as being completeable) - and I will follow that path with my PR. 
If there would be any complaints - we could rework that a bit :)
