### ISSUE TITLE
Documentation Improvements (Long-term?)

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3600]
I've been reading through the website and I think it would be really great if there was a system that allowed users to submit improvements and updates to the documentation, for instance, I've seen a couple simple spelling mistakes in the documentation and yet, there isn't a direct way for me to improve the documentation currently (for instance like wikis provide).

Since this project is open-source it would be beneficial if users could submit improvements to the documentation, that way suddenly you get a ton more "editors" looking over the documentation for issues like spelling, punctuation, and even improvements, like, rewording a section of the documentation to clarify something that might be confusing to a beginner, such as knowledge that the original writer might have taken for granted.

For instance, on this page:
http://www.godotengine.org/projects/godot-engine/wiki/Creating_2D_Games

Within the first section of the page there are a few improvements that could be made, one, make the download link more prominent (did you find the link easily?).

Two, note the following line: 

> the game will be in 640x400 pixels resolution. This can be configured in the Project Settings (see previous tutorials)

I see two issues with this, first, tutorials should attempt to be as self-contained as possible. It would a small addition to the tutorial to add a line and an image showing how to modify the resolution of the game, even if it has been previously covered. However, the more egregious issue is that this line actively deceives the reader, if you follow the tutorials as they are currently setup on the website none of the previous tutorials have shown how to modify the resolution of the game. Once more, this is why tutorials ought to attempt to remain self-contained and reduce external references where possible. External references, and especially assumptions like, that greatly reduce the ability of the documentation to avoid logical issues when the documentation is modified over time.

In particular, each tutorial or piece of documentation has an intended audience, this particular piece of documentation is intended for very new beginners, and two very important steps are easy to either miss or be miss led by.

**Comment by neikeq** [comment]
About being able to edit the documentation, you can ask for permissions in the forum. However, now it seems to be set as read-only since it will be migrated to Sphinx soon. The new docs will be accessible from [readthedocs](https://readthedocs.org/) and hosted on a github repository, which means you will be able to contribute with pull requests.

**Comment by Faustabov** [comment]
Alright, that sounds pretty good, perhaps someone could do a tutorial showing the process for how you would contribute to the documentation, when that system is up and running?

**Comment by techtonik** [comment]
> Alright, that sounds pretty good, perhaps someone could do a tutorial showing the process for how you would contribute to the documentation, when that system is up and running?

The most effective way is to help those people who need the tutorial to record that tutorial themselves. =)

**Comment by techtonik** [comment]
@Faustabov new doc sources along with instructions are here - https://github.com/godotengine/godot-docs  Let me know if anything about them is unclear, hard or doesn't work.

**Comment by djrm** [comment]
movable to documentation repo

**Comment by akien-mga** [comment]
There's not much to move, apart from a comment about:

> the game will be in 640x400 pixels resolution. This can be configured in the Project Settings (see previous tutorials)

This can always be improved, pull requests welcome on https://github.com/godotengine/godot-docs
