### ISSUE TITLE
Editor input dialogs will close randomly

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#36005]
**Godot version:**
Godot Engine v4.0.dev.custom_build.1efae74bc

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
All editor input dialogs have a chance to close randomly. This can be reproduced by changing Editor theme color

**Steps to reproduce:**
![t](https://user-images.githubusercontent.com/14253836/74078438-04d0e880-49f0-11ea-89c0-84a69c8f5037.gif)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Duplicate of #23626
