### ISSUE TITLE
The script creation icon is not displayed

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#36010]
**Godot version:**
3.2 stable mono

**OS/device including version:**
win10 64 home

**Issue description:**
When a new script is created and the C # option is accepted, the language icon is not displayed.

**Steps to reproduce:**
Add a script to any node, when choosing the language select C #, now you can see that the icon does not appear symbolizing the language.

![Captura2](https://user-images.githubusercontent.com/19652075/74082712-f0770500-4a5c-11ea-848b-b8e3f18ea062.PNG)

![Captura](https://user-images.githubusercontent.com/19652075/74082714-f5d44f80-4a5c-11ea-9ac9-8a32883c3090.PNG)

**Minimal reproduction project:**

**Comment by SkyLucilfer** [comment]
Hello. I'm a new contributor. I think this issue is accessible for me. I will take a look into it

**Comment by Torguen** [comment]
If it doesn't happen to you in the first script, then try adding several (you will have to have several nodes to be able to add more than one script).
