### ISSUE TITLE
Editor crash when editing an item and then clicking in scene

### ISSUE THREAD

**Issue by auzden** [godotengine/godot#3601]
Found on Windows x64 using a compiled build from Feb 3rd, 2016. Attached is a video of how to reproduce. Call stack below.

[capture.zip](https://github.com/godotengine/godot/files/119927/capture.zip)

>	godot.windows.tools.exe!Vector<TreeItem::Cell>::_get_size() Line 59	C++
 	godot.windows.tools.exe!Vector<TreeItem::Cell>::size() Line 91	C++
 	godot.windows.tools.exe!TreeItem::get_metadata(int p_column) Line 276	C++
 	godot.windows.tools.exe!PropertyEditor::_item_edited() Line 3200	C++
 	godot.windows.tools.exe!MethodBind0<PropertyEditor>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 119	C++
 	godot.windows.tools.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 891	C++
 	godot.windows.tools.exe!MessageQueue::_call_function(Object * p_target, const StringName & p_func, const Variant * p_args, int p_argcount, bool p_show_error) Line 312	C++
 	godot.windows.tools.exe!MessageQueue::flush() Line 355	C++
 	godot.windows.tools.exe!SceneTree::input_event(const InputEvent & p_event) Line 440	C++
 	godot.windows.tools.exe!InputDefault::parse_input_event(const InputEvent & p_event) Line 269	C++
 	godot.windows.tools.exe!OS_Windows::WndProc(HWND__ * hWnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 591	C++

-- 

I'm new to godot but am continuing to investigate a fix. Thanks!

**Comment by akien-mga** [comment]
Nice, I also got such a crash this morning but could not reproduce it, so I hadn't reported it.

**Comment by reduz** [comment]
the secret was clicking on a different node
