### ISSUE TITLE
Possible to embed Godot into a GUI application

### ISSUE THREAD

**Issue by define-private-public** [godotengine/godot#36022]
I'm currently working on a graphical application that's built in Gtk.  But I want to add in a 3D editing area and have been looking at various 3D engines.  While Godot is a game engine (and it could be a little bit overkill), it came to mind since it has nice real time capabilities.

I know that given enough time anything is possible, but right now, how workable do you think this would be to embed the Godot engine inside of another (Desktop) application?  I'm using Gtk right now, but I'd be interested in how it would work for Qt as well.

**Comment by clayjohn** [comment]
This space is for bug reports only. Please ask your question on one of the [Community Channels](http://docs.godotengine.org/en/latest/community/channels.html) (reddit, discord, or the Q&A are likely the best places to ask)
