### ISSUE TITLE
Thread requires argument even when not providing 'userdata'

### ISSUE THREAD

**Issue by wilska** [godotengine/godot#36032]
**OS:** Windows 7 SP1
**Godot version:** 3.2

**Bug:**
When you call Thread.start using a method which doesnt accept arguments, the following error occurs:

> E 0:00:00.431   _start_func: Could not call function 'work' to start thread 4788: Too Many Arguments.
>   <C++ Error>   Method failed.
>   <C++ Source>  core/bind/core_bind.cpp:2694 @ _start_func()

**Example code:**

```
extends Spatial

var _thread = Thread.new()

func work(): 
	print('done')

func _ready():
	_thread.start(self, "work")
```
Probably the internal call try to pass some argument and since work() doenst accept, it throws that error.
The code bellow runs fine:
```
extends Spatial

var _thread = Thread.new()

func work(abc): # <---
	print('done')

func _ready():
	_thread.start(self, "work")
```

**Comment by Calinou** [comment]
This is documented on [Using multiple threads](https://docs.godotengine.org/en/latest/tutorials/threads/using_multiple_threads.html), but it doesn't explain why the `userdata` parameter must always be specified.

**Comment by wilska** [comment]
I overlooked the doc (my mistake) about the [Thread.start()](https://docs.godotengine.org/en/latest/classes/class_thread.html#class-thread-method-start), it was there:

> Starts a new Thread that **runs method on object instance with userdata passed as an argument.** The priority of the Thread can be changed by passing a value from the Priority enum.
> 
> Returns @GlobalScope.OK on success, or @GlobalScope.ERR_CANT_CREATE on failure.

Maybe making it more clearer (like the tutorial you linked):
> Starts a new Thread that **runs method on object instance with userdata passed as an argument (even if no userdata argument is passed, the method must accept one argument and it will be null).** The priority of the Thread can be changed by passing a value from the Priority enum.
> 
> Returns @GlobalScope.OK on success, or @GlobalScope.ERR_CANT_CREATE on failure.
