### ISSUE TITLE
Changing a single file in the engine sometimes cause scons to build tons of other files

### ISSUE THREAD

**Issue by ShlomiRex** [godotengine/godot#36038]
**Godot version:**
Godot 3.2 stable

**OS/device including version:**
Ubuntu 18.4.4 LTS

**Issue description:**
When I change a single file in the engine (for example file_access.cpp) and recompile it also compiles other stuff, image:

![Screenshot from 2020-02-09 02-01-17](https://user-images.githubusercontent.com/17744127/74093853-a2a3e080-4ae0-11ea-869a-befbe6ff49b6.png)

I checked that I did not changed the code with git (no pull, no branch, no checkout... so only I changed the code)

**Steps to reproduce:**
It happens only sometimes
Usually happens when 2+ minutes passed or something like that from last compile

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
That's normal, you're change `file_access.h` so any file that includes it, and any file that includes those files, etc., needs to be recompiled.
