### ISSUE TITLE
Can not open c# script by editor

### ISSUE THREAD

**Issue by Ling2121** [godotengine/godot#36046]
**Godot version:** 3.2
**OS/device including version:** Windows10

**Issue description:** can not open c# script by editor

**Steps to reproduce:** 
 modules\mono\mono_gd\gd_mono_utils.cpp:357 - System.ArgumentException: Illegal characters in path.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@Ling2121 What does the *full path* to the C# script look like?

**Comment by Ling2121** [comment]
> @ Ling2121 C＃脚本的_完整路径_是什么样的？

Previous version no problem

**Comment by akien-mga** [comment]
There isn't much to go on, but I assume it's a duplicate of #35810.
