### ISSUE TITLE
Tree SELECT_ROW allows de-selecting rows, not emitting _tree_selected (compared to SELECT_SINGLE)

### ISSUE THREAD

**Issue by ShlomiRex** [godotengine/godot#36047]
**Godot version:**
3.2 Stable

**OS/device including version:**
Ubuntu 18.4.4 LTS

**Issue description:**
When creating Tree with TreeItems and setting the tree's select mode to SELECT_ROW it doesn't actually trigger _tree_select function, even though emit_signal("item_selected"); is called.

(It omits inside function `tree.cpp::select_single_item()`)

When the mode is SELECT_SINGLE it does omit emit_signal("item_selected"); and _tree_select is called.

Moreover when the select mode is SELECT_ROW you can also de-select items in the tree 

**GIF**
![Peek 2020-02-11 00-49](https://user-images.githubusercontent.com/17744127/74197582-6c916880-4c68-11ea-9617-64de2e15ef42.gif)

I think I found the problem:
Signal "item_select" is not connected inside file_dialog , only cell_selected is binded, which in turn calls _tree_select
"item_select" needs some use

I fixed the signal problem but now I can deselect the row...
I also get :

> ERROR: deselect_all: Condition "item == prev_item" is true.
   At: scene/gui/tree.cpp:3217.

errors when I go up / inside a folder

**Steps to reproduce:**
In godot engine inside file_dialog.cpp in function set_mode(Mode p_mode) you change the line:
`tree->set_select_mode(Tree::SELECT_SINGLE);`
to:
`tree->set_select_mode(Tree::SELECT_ROW);`

**Minimal reproduction project:**
[minimal.zip](https://github.com/godotengine/godot/files/4183400/minimal.zip)

**Comment by ShlomiRex** [comment]
Pull request Better file dialogue uses this pull request

**Comment by me2beats** [comment]
I think deselecting rows should be either prohibited or allowed for any SelectMode (then a boolean property `allow_deselect` could be added)

**Comment by eazrael** [comment]
Any chance to get this fix into 3.4.x branch? 

I am currently having the same problem, being able to deselect the selected row is not wanted. Additionally no event is triggered on deselection, I tried item_selected, nothing_selected, cell_selected and button_pressed and none fired on deselecting.

Currently i am tapping gui_input  for toggling a confirmation button disabled state, not a nice work around :-(

**Comment by Calinou** [comment]
> Any chance to get this fix into 3.4.x branch?

https://github.com/godotengine/godot/pull/36094 was closed by its author – it needs to be recreated by someone else (and tested again) before it can be merged.

**Comment by eazrael** [comment]
I adapted #36094 to the current state of the master branch: #56408

@Calinou, are you sure that patches to 3.x should really go to master? Now someone has to backport the changes to 3.x as the file changed quite a bit.  I can provide pull requests to both branches (master & 3.x or 3.4) if that helps.

**Comment by ShlomiRex** [comment]
@Calinou You can use @eazrael 's pull request.
I don't mind that he uses my closed merge request.
I hope this will help Godot, and thats whats important.
Thanks for the update, I tought this feature was bad, but apperantly it is useful.

**Comment by Calinou** [comment]
> @Calinou, are you sure that patches to 3.x should really go to master? Now someone has to backport the changes to 3.x as the file changed quite a bit. I can provide pull requests to both branches (master & 3.x or 3.4) if that helps.

Yes, pull requests should always be made against `master` first except if they are irrelevant there. For features that have changed significantly since `3.x`, you will have to create two pull requests – one for `master`, one for `3.x`.
