### ISSUE TITLE
Steam version crashes when changing workspaces

### ISSUE THREAD

**Issue by swashdev** [godotengine/godot#36055]
**Godot version:** 3.2.stable, Steam version

**OS/device including version:** Ubuntu 18.04 w/ Linux kernel 4.15.0-76-generic, Steam API version v020, Steam package versions 1579321278

**Issue description:** My desktop manager supports multiple workspaces, also known as desktops.  I generally keep Steam in my "Gaming Desktop" and try to do work on my Primary and Secondary Workspaces.

However, when launching Godot from Steam and attempting to switch to my Primary Workspace I found that the Godot program quits out abruptly and without explanation.  The problem persists any time the program is on a different workspace than me.  Notably, it does not present if I make the Godot window omnipresent so that it follows me any time I switch workspaces.

Steam doesn't produce any problems or error messages as a result of this, as if the program had quit under completely normal circumstances.

While testing the version 3.2.stable program outside of Steam as downloaded from the website, this problem did not occur.  However, we can rule out Steam itself having the error because other programs do not present this problem.

I am not currently able to test this behavior myself on operating systems other than Linux.

**Steps to reproduce:** Open Godot via the Steam client and then either move the program to a different workspace or switch your own focus to a different workspace.

**Comment by Calinou** [comment]
Does this occur with other applications started via Steam (such as Blender or Krita)?

**Comment by swashdev** [comment]
This does not occur with any other application I have tested; after this problem presented in Godot I tested it with Half-Life and then with Blender and the problem appears to be unique to Godot.

**Comment by Calinou** [comment]
Could you try getting some logs by doing the following steps?

- Edit a project, go to the **Project > Project Settings** and enable **Logging > File Logging > Enable File Logging**.
- Quit and restart Godot, then edit the same project again. At the top of the editor, click **Project > Open Project Data Folder** to view the logs folder.
- Switch workspaces to make Godot crash.
- Look at the resulting log and post it here.

**Comment by swashdev** [comment]
Okay, I gave that a shot, but when I switched workspaces the editor window didn't close.  Then I tried moving the window itself to a different workspace and same story.  So I quit back to the project list and switched workspaces again and sure enough it quit.  I guess the problem doesn't present on the editor window.

Is there a way to get log messages on the project list window?

**Comment by Calinou** [comment]
> Is there a way to get log messages on the project list window?

You could do so by running the binary in a terminal, but I don't know if you can still do this while letting Steam do its wrapping thing.

**Comment by Calinou** [comment]
@swashdev Can you (or anyone else) still reproduce this bug in [Godot 3.4.2](https://godotengine.org/article/maintenance-release-godot-3-4-2) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
