### ISSUE TITLE
Write a GDScript lexer for Pygments

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3606]
Since we're now using sphinx-doc to handle the Godot documentation, we can have syntax highlighting very easily using Pygments. But it obviously doesn't support GDScript yet, and falling-back to python3 is fine but not perfect (no highlighting for "var", "func", "extends", etc.).

So if we have some Python experts wanting to give it a try, here is the Pygments documentation about writing lexers: http://pygments.org/docs/lexerdevelopment/
The existing "python3" lexer could likely be taken as a base and enhanced (though it is likely far more advanced than what GDScript actually needs).

Once done, we would try to use it to generate our own doc, and also get it merged upstream in a future Pygments release.

**Comment by djrm** [comment]
im working on this

**Comment by djrm** [comment]
ok i have the lexer, i think this can be close, im going to push it to godot-docs

**Comment by vnen** [comment]
@djrm I'm missing your PR [here](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/) :wink:

**Comment by djrm** [comment]
@vnen i was thinking in doing that

**Comment by djrm** [comment]
closable
