### ISSUE TITLE
Tileset Resource "Merge from Scene" freezes Editor and limits Tiles to 200

### ISSUE THREAD

**Issue by CaptainSusuwatari** [godotengine/godot#36080]
**Godot version:**
3.2.stable.official

**OS/device including version:**
Linux

Issue description:
When a larger number of Sprites (200>) is "merged from Scene" for a Tileset-Resource  my editor  freezes and has to be SIGTERMed. So i merged smaller amount of sprites from scene (like 50) but this only goes up to 200 Tiles inside the Tileset-Resource. No more can be added and the editor slows down. (Is this intended?)

Steps to reproduce:
1. Take like 210 Sprites (16x16 ) and Add it to a Node2D. 
2. Create a Resource "Tileset" from the inspector. 
3. Use the feature "Create/Merge from Scene" 
4. My Editor freezes.

**Comment by Calinou** [comment]
Does it still happen if you increase the message queue size as explained in #35653?

**Comment by CaptainSusuwatari** [comment]
Nope then its gone!
Thank your for your fast response!
Can be closed;)
