### ISSUE TITLE
Video Card crash

### ISSUE THREAD

**Issue by Nateao7** [godotengine/godot#36096]
Window 7 64 bit
AMD E-300 APU with Radeon
Description:
  A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	Godot_v3.2-stable_win64.exe
  Application Version:	3.2.0.0
  Application Timestamp:	00000000
  Hang Signature:	bb77
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Hang Signature 1:	bb77cf0a1e5dbc782df8c1e76f106233
  Additional Hang Signature 2:	9a3b
  Additional Hang Signature 3:	9a3ba73b736903ffc2040c9541a6b06a
  Additional Hang Signature 4:	bb77
  Additional Hang Signature 5:	bb77cf0a1e5dbc782df8c1e76f106233
  Additional Hang Signature 6:	9a3b
  Additional Hang Signature 7:	9a3ba73b736903ffc2040c9541a6b06a
**Minimal reproduction project:**
Every time i try to load a project or a new project
this happen with 3.2 beta 2 to 3.2 release
3.2 beta 1 work fine

**Comment by Zireael07** [comment]
GLES 3 or GLES 2?

**Comment by Nateao7** [comment]
On 3.2 beta 1 work in  GLES 3 and GLES 2

**Comment by clayjohn** [comment]
Does it work okay on GLES2? Your graphics card is almost 10 years old. I wouldn't expect it to work with GLES3.

**Comment by Nateao7** [comment]
![Gles3](https://user-images.githubusercontent.com/58160321/74291263-4ddfb000-4d02-11ea-8ac8-72f5c8da343f.png)

**Comment by Nateao7** [comment]
![Gles2](https://user-images.githubusercontent.com/58160321/74291558-335a0680-4d03-11ea-8a86-407ac0715edb.png)

**Comment by clayjohn** [comment]
@Nateao7 does that mean it is working on GLES2?

**Comment by Nateao7** [comment]
Yes only beta 1 not the stable 3.2 and that what am wandering what have they change that 1 version work but not the other version from 3.2 beta 2 to the stable release .

**Comment by clayjohn** [comment]
@Nateao7 In GLES3 the radiance map generation was changed which created a lot of problems for users with low-end hardware. But nothing was changed in GLES2 that should be causing you issues. 

What kind of project are you running that is making the crash happen?

**Comment by Nateao7** [comment]
On that note i was able to Open GLES2 in 3.2 stable release ,I use beta 1 to change from GLES3 to GLES2, Now am able to use 3.2 with GLES2, So GLES3 crash the video card.
So maybe radiance map generator don't work with my video card.
I was using First_Person_Character from the templates.

**Comment by clayjohn** [comment]
Yes. That is not surprising with such an old graphics card. You should be using GLES2 which is much better suited for your hardware. 

In fact, the entire reason we have GLES2 is so that people with hardware like yours can still benefit from the engine. :)

**Comment by Calinou** [comment]
@clayjohn Should we close this issue, or wait until someone implements a list of GPUs that should always use GLES2?

**Comment by clayjohn** [comment]
I guess we should just close it. Either way it is a video card that is not supported by our GLES3 renderer.
