### ISSUE TITLE
& in project name shouldn't be escaped

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#3609]
When the project name contains '&' character, it is replaced by the HTML escape sequence "&amp;" and appears as such in the project list.

**Comment by punto-** [comment]
That would suck for someone who was about to release a game with a name
like "Cat Mendoza & Taco Boy" or something like that

**Comment by tagcup** [comment]
I noticed that github escaped the escape sequence!
What I mean is, & is replaced by \&amp; of course (it seems like in Markdown code, I have to put a backslash before & to avoid that).

**Comment by nunodonato** [comment]
I can't replicate this. What version and OS are you on?

**Comment by tagcup** [comment]
Tip, Linux.

**Comment by reduz** [comment]
This will be fixed in 2.1 when we move globals to use VariantParser

**Comment by akien-mga** [comment]
It looks like only the project manager displays it wrong. In the X11 window title it's still correct (both in editor and in the running game). In engine.cfg, it's encoded as ``&amp;``.
