### ISSUE TITLE
Allow a state with no selection in VButtonArray

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#3610]
At the moment, one of the buttons in VButtonArray has to be selected. This makes sense for keyboard/joypad controlled menus, but it doesn't feel right for touchpad/mouse oriented menus.

It would be nice if, for example, we could set Selected to -1, corresponding to the state in which none of the buttons is selected.

**Comment by akien-mga** [comment]
"Fixed" as there is no more `VButtonArray` in the master branch.

**Comment by tagcup** [comment]
So I assume all 2.x related issues can be closed now

**Comment by akien-mga** [comment]
Not necessarily all of them, but old enhancements suggestions could be yeah. Actual bugs would still be worth fixing as there will still be 2.1.x releases.

**Comment by akien-mga** [comment]
If you think this one would still be worth fixing in 2.1.x, we can reopen it.

**Comment by chanon** [comment]
Is there any explanation why VButtonArray was removed?

**Comment by Noshyaar** [comment]
ButtonArray is removed in favor of [ButtonGroup](http://docs.godotengine.org/en/latest/classes/class_buttongroup.html).
