### ISSUE TITLE
Editor Theme items not accessible by nodes inside Popups unless root node has any theme

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#36103]
**Godot version:**
3.2 (Steam)

**OS/device including version:**
Windows 10

**Issue description:**
When developing an Editor Plugin one can rely on Editor Theme constants to give it consistent look. For example, using editor colors with 
```swift
get_color("property_color", "Editor")
```

As Editor Theme is implicitly applied to every node within the tree this piece of code works anywhere within plugin scripts (attached to plugin nodes). However, this is not the case for nodes within `Popup` and its derivatives. If a node is located within a `Popup`, then its call of  `get_color("property_color", "Editor")` returns a default black color. That is unless the root of your plugin scene has **any** `Theme` resource in its `theme` property.

**Steps to reproduce:**
Make a plugin that adds your scene to the top bar:
```swift
func _enter_tree() -> void:
	scene_instance = preload("res://addons/test-theme2/Addon.tscn").instance()
	get_editor_interface().get_editor_viewport().add_child(scene_instance)
```

Create a scene `Addon.tscn` that has a `Control` node within a `Popup`. For comparison, add nodes that are not within a `Popup`.
![image](https://user-images.githubusercontent.com/11782833/74239229-765ab080-4ce8-11ea-9f04-7545694a5f80.png)

To each node attach a script similar to this (but with a different text and extending a corresponding type):
```swift
tool
extends Control

func _ready() -> void:
	var label_color = get_color("property_color", "Editor")
	print("Control Color is ", label_color)
```

Enable your plugin and look at the output:
```
SubControl Color is 0.645588,0.64902,0.651961,1
Control Color is 0.645588,0.64902,0.651961,1
PopupControl Color is 0,0,0,1
Popup Color is 0.645588,0.64902,0.651961,1
```

You can see, that every node has access to the Editor Theme constants, even `Popup` itself, but not its children. Now, select root node `Addon` and create a new `Theme` resource for its `theme` property. Do not edit this theme in any way. Then restart your plugin in project settings and look at the output:
```
SubControl Color is 0.645588,0.64902,0.651961,1
Control Color is 0.645588,0.64902,0.651961,1
PopupControl Color is 0.645588,0.64902,0.651961,1
Popup Color is 0.645588,0.64902,0.651961,1
```

Even though the theme of your root node does nothing, nodes within a `Popup` can now access Editor Theme constants.

**Minimal reproduction project:**
[bug-theme-dialogs.zip](https://github.com/godotengine/godot/files/4185837/bug-theme-dialogs.zip)

**Comment by pycbouh** [comment]
It seems, that the `theme` property must have a non-empty value specifically on a node, that is the closest parent node to your `Popup` and is *instantiated in code*.

In the OP example, the `Addon` scene instance is created in code of `plugin.gd` script. If we put a `Popup` in another scene `PopupScene` and then add it to `Addon` via the Scene Panel option `Instance Child Scene`, then the `theme` property must be set to `Addon` node. However, if we add `PopupScene` via code, then its root must have a non-empty `theme` property.

#### 1. All nodes in one scene
* Addon <- add theme here
* * Popup
* * * Control

#### 2. Popup is in another scene, but that scene is added via Scene Panel
* Addon <- add theme here
* * AnotherSceneWithPopup

#### 3. Popup is in another scene, but that scene is added via code
* Addon <- irrelevant if it has theme

* AnotherSceneWithPopup <- add theme here

**Comment by KoBeWi** [comment]
Still valid in 2cbc0b6
And seems worse or something
```
SubControl Color is 0.65,0.65375,0.66375,1
Control Color is 0.65,0.65375,0.66375,1
PopupControl Color is 0,0,0,1
Popup Color is 0,0,0,1
```
