### ISSUE TITLE
Godot 3.2 - NativeScript - "No valid library handle, can't get symbol from GDNative object"

### ISSUE THREAD

**Issue by atari83** [godotengine/godot#36114]
Godot version: 3.2
OS/device including version: FreeBSD 12.1

Well, I've built freshly cloned godot-cpp and its headers and built the native script binding.
I've followed the instructions : https://docs.godotengine.org/en/3.2/tutorials/plugins/gdnative/gdnative-cpp-example.html

and created a basic project that built successfully.
Too keep story short, i've attached the .gdns file to a Node2D scene, when i execute the project i receive these errors:

Output Errors:
 modules/gdnative/gdnative.cpp:483 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/gdnative.cpp:388 - No valid library handle, can't terminate GDNative object

Debugger Errors:
 Can't open dynamic library: /home/user1/project1/res/src_common/lib/libTest.so. Error: /home/user1/project1/res/src_common/lib/libTest.so: Undefined symbol "_ZN5godot14_RegisterState19nativescript_handleE"

 
 E 0:00:00.477   open_dynamic_library: Can't open dynamic library: /home/user1/project1/res/src_common/lib/libTest.so. Error: /home/user1/project1/res/src_common/lib/libTest.so: Undefined symbol "_ZN5godot14_RegisterState19nativescript_handleE"
  <C++ Error>   Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <C++ Source>  drivers/unix/os_unix.cpp:424 @ open_dynamic_library()

  
E 0:00:00.477   get_symbol: No valid library handle, can't get symbol from GDNative object
  <C++ Source>  modules/gdnative/gdnative.cpp:483 @ get_symbol()

  
E 0:00:00.477   init_library: No nativescript_init in "res://res/src_common/lib/libTest.so" found
  <C++ Source>  modules/gdnative/nativescript/nativescript.cpp:1506 @ init_library()

Could anybody help me on this case ?

**Comment by atari83** [comment]
./libTest.so:
        libc++.so.1 => /usr/lib/libc++.so.1 (0x800677000)
        libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x800747000)
        libm.so.5 => /lib/libm.so.5 (0x800769000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x80079b000)
        libc.so.7 => /lib/libc.so.7 (0x80024a000)

**Comment by atari83** [comment]
It was my bad, it is soo bad that i dont want to talk about it ^^

**Comment by Pierre-Narcisi** [comment]
Could you at least explain your error, someone could have the same one, not cool

**Comment by molo0824** [comment]
im having same issue please explain

**Comment by thesquaregroot** [comment]
I just encountered this error and the issue was that I was not defining the `_init` method on my class.

Given that the example even has an explicit warning about this ("The _init function has to exist even if you don't place any code in it. Otherwise, the class won't be instantiable."), I'm assuming that's why atari83 didn't want to mention it.
