### ISSUE TITLE
Array out of bounds in sprite_3d.cpp

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#36115]
**Godot version:**
Godot 4.0 master(vulkan)
**OS/device including version:**
Ubuntu 19.10
**Issue description:**
Here is created uvs with only 4 elements
https://github.com/godotengine/godot/blob/1eb424ec9549bdd086dfb54c847d107519be73d9/scene/3d/sprite_3d.cpp#L455

but here is readed also element 5 and 6
https://github.com/godotengine/godot/blob/1eb424ec9549bdd086dfb54c847d107519be73d9/scene/3d/sprite_3d.cpp#L507-L514

also here is same problem
https://github.com/godotengine/godot/blob/1eb424ec9549bdd086dfb54c847d107519be73d9/scene/3d/sprite_3d.cpp#L848

**Comment by Calinou** [comment]
(By the way, Sprite3D needs a refactor to avoid using ImmediateGeometry, which is slow.)

**Comment by Calinou** [comment]
If you can build Godot from source, please build the `3.2` branch and test this again now that https://github.com/godotengine/godot/pull/39867 has been merged. (That pull request also makes Sprite3D much faster to render.)

You can also use this [Windows 64-bit editor binary](https://ci.appveyor.com/api/buildjobs/14y1r5yqju7jr7rc/artifacts/bin%2Fgodot_3.2-1f886d1f3_win64.zip) for testing.

**Comment by qarmin** [comment]
Out of bounds code was added only in Godot 4.0, so there is no need to test it with 3.2.

https://github.com/godotengine/godot/blame/1eb424ec9549bdd086dfb54c847d107519be73d9/scene/3d/sprite_3d.cpp#L507

**Comment by qarmin** [comment]
Fixed by #44199
