### ISSUE TITLE
Hold modifier key to edit(rotate/scale) in fixed steps

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3611]
A few useful feature to edit objects in blender, is to hold ctrl while editing, in order to change the values in fixed steps.
So I can easily rotate a mesh 45º or 90º using nothing but the ctrl key and my mouse. same thing for scaling (and perhaps moving).

**Comment by eska014** [comment]
Rotating/scaling/moving in fixed steps is already possible with `Edit`→`Use Snap`/`Use Rotate Snap` in 2D and `Transform`→`Use Snap` in 3D. Hotkeys to disable snap are being discussed in #3225.

**Comment by nunodonato** [comment]
oh... I always forget to check that menu :) good to know, but yeah, an hotkey would be great. if its already being discussed, maybe we could just close this issue then
