### ISSUE TITLE
Vulkan: Artifacts with OmniLight shadows

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#36116]
**Godot version:** Git https://github.com/godotengine/godot/commit/11cd8b8e4afdbd42f82459c48c9f6fd604ea1455

**OS/device including version:** Fedora 31, NVIDIA 440.44, GeForce GTX 1080

**Issue description:** OmniLights exhibit artifacts when enabling shadows:

![image](https://user-images.githubusercontent.com/180032/74277781-68248880-4d18-11ea-8673-554fb04f5f3c.png)

When the Reverse Cull Face property is enabled and the bias is set to -0.01, they barely light up anything:

![image](https://user-images.githubusercontent.com/180032/74277978-b9347c80-4d18-11ea-9b00-4fa143e02045.png)

If you go close enough, you can notice the pixelation pattern:

![image](https://user-images.githubusercontent.com/180032/74277869-8e4a2880-4d18-11ea-9d90-e141ce5ea75c.png)

**Steps to reproduce:** Edit and run the attached reproduction project.

**Minimal reproduction project:** [test_lights_4.0.zip](https://github.com/godotengine/godot/files/4188260/test_lights_4.0.zip)

**Comment by KoBeWi** [comment]
30d469a
![image](https://user-images.githubusercontent.com/2223172/102884704-60fafa80-4452-11eb-9433-5077f2834e5f.png)

Looks somewhat better, not sure if it's fixed.

**Comment by Calinou** [comment]
Looks fixed to me, closing.
