### ISSUE TITLE
Vulkan: Moving a light in a VoxelGI is extremely slow if no mesh has a Global Illumination Mode set to Baked

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#36121]
**Godot version:** Git https://github.com/godotengine/godot/commit/11cd8b8e4afdbd42f82459c48c9f6fd604ea1455

**OS/device including version:** Fedora 31, NVIDIA 440.44, GeForce GTX 1080

**Issue description:** After baking a GIProbe in a simple scene with a few lights, moving an OmniLight inside will take several *seconds* just to update the editor viewport. Attempting to move a light without using snapping will likely freeze the editor for more than 10 seconds.

Moving the VoxelGI node itself can cause this slowdown if the VoxelGI node is moved in a way that puts some of the lights outside its bounding box (notice the update spinner in the top-right corner):

https://user-images.githubusercontent.com/180032/150573031-4b898771-ff0f-460a-8bab-4e397347626a.mp4

Moving a MeshInstance3D node does not cause this slowdown.

**Steps to reproduce:** Edit the attached reproduction project and try to move an OmniLight.

**Minimal reproduction project:** [test_giprobe_vulkan.zip](https://github.com/godotengine/godot/files/7915578/test_giprobe_vulkan.zip)
<sub>Old MRP from February 2020: [test_giprobe_vulkan.zip](https://github.com/godotengine/godot/files/4188663/test_giprobe_vulkan.zip)</sub>

**Comment by Ace-Dragon** [comment]
I think the issue really stems from the fact that even moving the view can be pretty glacial, and this is on a machine that has no problem rendering out _multiple_ GI Probes at high resolutions in Godot 3.2 (GTX 1060 GPU).

The actual computing part (creating the data) does not take that long.

**Comment by Calinou** [comment]
I can still reproduce this on commit 2a9dd654b. It occurs as soon as no mesh with its global illumination mode set to **Baked** is present within the VoxelGI's extents: [test_voxelgi_dynamic_only.zip](https://github.com/godotengine/godot/files/7677812/test_voxelgi_dynamic_only.zip)

**Comment by Zireael07** [comment]
I seem to have triggered it on alpha 1. Before that, voxelgi performed fairly well even on my integrated Kaby Lake GPU.

**Comment by Calinou** [comment]
> I seem to have triggered it on alpha 1. Before that, voxelgi performed fairly well even on my integrated Kaby Lake GPU.

I didn't notice VoxelGI performance regressions on `master` lately, although my above comment still applies if you have *no* meshes with the Static bake mode within the VoxelGI's extents.

**Comment by Calinou** [comment]
I can't reproduce this on 4.2.dev 6758a7f8c (Linux, GeForce RTX 4090 with NVIDIA 535.98), but I can reproduce it on 4.1.1. This was likely fixed at some point.
