### ISSUE TITLE
Vulkan: Reimport Results in Error Unable to Write to File xxxx File in Use, Locked or Lacking Permission

### ISSUE THREAD

**Issue by paulhocker** [godotengine/godot#36122]
**Godot version:**

4.0.dev.948d95897

**OS/device including version:**

Windows 10

Have not tested on Linux/Mac yet, but I will be and will update results here.

**Issue description:**

REIMPOIRTing a resource after using it results in a file lock error message.

The term "using" is pretty broad here. But in my testing it will lock when looking at the resource in the inspector. Or if it is used in a Scene, or in a Node property, etc.

Exact error message is:

`
Unable to write to file "c:/Development/Workspace/Sandbox/godot-vulkan/.import/icon.png-4872[snip].stex. File in use, locked or lacking permissions.
`

**Steps to reproduce:**

1. Start Vulkan Build
2. Create New Project
3. Single Click on icon.png
4. Select IMPORT Tab and REIMPORT
5. No Error
6. Double Click on icon.png
7. Select IMPORT Tab and REIMPORT
8. You will receive the error message reported above.

**Minimal reproduction project:**

A project can be added if requested. However, I have been able to consistently do this with a brand new project. Obviously it also affects existing projects too.

**Comment by Xrayez** [comment]
This error message also appears:

![godot-safe-save](https://user-images.githubusercontent.com/17108460/74291401-6f11c200-4d3d-11ea-9f2f-761c3a122ca5.png)

>  Safe save failed. This may be a permissions problem, but also may happen because you are running a paranoid antivirus. If this is the case, please switch to Windows Defender or disable the 'safe save' option in editor settings. This makes it work, but increases the risk of file corruption in a crash.

**Comment by paulhocker** [comment]
Yeah, saw that. So my problem here is that it does not happen on 3.1 or 3.2 and I have never had this issue before on any project. Only the Vulkan (now master 4.0) branch. I was waiting for this to get into master before reporting just in case it was something specific on the Vulkan branch.

**Comment by paulhocker** [comment]
I just created brand new project in 3.1, 3.2 and 4.0 and 4.0 was the only version that gave me this error.

**Comment by paulhocker** [comment]
This no longer appears to be a problem with the latest pull f65781fe7. I will do a few more tests.

**Comment by fire** [comment]
Closing due to report.
