### ISSUE TITLE
PopupPanel disregards outer MarginContainer in Nested MarginContainer

### ISSUE THREAD

**Issue by Ramh5** [godotengine/godot#36125]
**Godot version:**
3.2.stable.official
**OS/device including version:**
Windows 10 Pro 64 bit 

**Issue description:**
I am trying to control the position of a PopupPanel by placing them as child of MarginContainers and calling .popup(). I am not sure it is the best way but it is the only way I found and it works well until I have nested MarginContainers, then the PopupPanel inside disregards the left and top margins of the top level MarginContainer and seems to add it to the bottom and right instead.

![GodotPopupMarginContainerBug](https://user-images.githubusercontent.com/16180873/74297274-59d46d80-4d14-11ea-89a1-9442bbe239da.png)

**Steps to reproduce:**
-MarginContainer1
--MarginContainer2
---PopupPanel
**Minimal reproduction project:**
[popupTest.zip](https://github.com/godotengine/godot/files/4189516/popupTest.zip)

**Comment by KoBeWi** [comment]
No longer relevant in 4.0, where popups are separate windows.
