### ISSUE TITLE
Vulkan: Sky doesn't produce ambient light.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#36120]
**Godot version:**
Godot 4 hash 8c73e813

**OS/device including version:**
Win10 64 bit; Nvidia GTX 1060 with latest studio drivers; Ryzen 2700X CPU; 32 gigs RAM.

**Issue description:**
Sky-based environments are producing no ambient lighting, geometry in the scene stays black.

**Steps to reproduce:**
Replicate this setup
![VulkanBug1](https://user-images.githubusercontent.com/10081256/74281703-87a1be00-4ce4-11ea-98d1-c377b9d07fe0.png)

**Minimal reproduction project:**
[Vulkan_Testing.zip](https://github.com/godotengine/godot/files/4188535/Vulkan_Testing.zip)

**Comment by Calinou** [comment]
This only seems to happen with the Environment in Sky mode (either PanoramaSky or ProceduralSky), not with Clear Color or Custom Color.

Example project with a PanoramaSky: [test_hdri.zip](https://github.com/godotengine/godot/files/4188659/test_hdri.zip)

**Comment by clayjohn** [comment]
I can not reproduce in current master. @Ace-Dragon Can you confirm that this has been fixed?

**Comment by Ace-Dragon** [comment]
Ambient light works now.
