### ISSUE TITLE
scroll_to_line does not work while scroll active is disabled

### ISSUE THREAD

**Issue by MoonsPod** [godotengine/godot#36134]
(3.2.stable.official) For Rich Text Label, If scroll_active is False, scroll_to_line(n) does not scroll to the line number given. Despite the on hover message for Scroll Active in the Inspector saying 'Setting this to false does not block scrolling completely. See scroll_to_line()'

**Comment by dreamsComeTrue** [comment]
Could you formulate that sentence properly once again? Can't understand what it says. Try to describe a scenario which causes that issue.

**Comment by dreamsComeTrue** [comment]
Are you using `_ready()` func to perform that scrolling? Like:

`
func _ready():
	$RichTextLabel.scroll_to_line(4)
`

I've tried to replicate it - and even I've disabled scrolling, I am still able to offset it with above code.
Could you record simple GIF with issue? Or prepare simple project which reproduces that error?

**Comment by MoonsPod** [comment]
Im changing the line on a timer timeout

`func _on_LineChange_timeout():
	if globals.level != 0:
		linecred += 1
		linelist += 1
		$Credits.scroll_to_line(linecred)
		$Results/TimeList.scroll_to_line(linelist)
		$Results/DeathsList.scroll_to_line(linelist)
		if linecred >= 36:
			$Credits.scroll_to_line(0)
			linecred = 0
		if linelist >= n - 5:
			$Results/TimeList.scroll_to_line(0)
			$Results/DeathsList.scroll_to_line(0)
			linelist = 0
	else:
		print("Looks like ya hecked up mister")`

Heres a [video](https://streamable.com/99bpu), the list of times/deaths would scroll down until it reached the end then reset and 'credits' would scroll up the bottom area on the previous version of Godot. Was functioning fine before i updated :x hope i'm not making a silly mistake here now ive posted this.

**Comment by dreamsComeTrue** [comment]
Are you able to reproduce that issue with similar setup as mine?
![demo](https://user-images.githubusercontent.com/1110337/74606357-2442d200-50d0-11ea-9d04-d57e394c8cf8.gif)

**Comment by MoonsPod** [comment]
The issue comes when Scroll Active in Rich Text Label is set false (when scroll bar is hidden) the on hover message for Scroll Active says scrolling is not blocked completely, see scroll_to_line https://streamable.com/37hl6

**Comment by dreamsComeTrue** [comment]
OK, I've got it now. It was actually connected with other issue reported back then - please go to my PR to find out more :)

**Comment by KoBeWi** [comment]
This seems to work correctly in 3.2.2 beta3.
