### ISSUE TITLE
Godot Code Editor Highlight All Occurrences

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3614]
Something that I really miss from more featured code editors is being able to highlight all occurrences of a selected portion of the code. On the most basic level this act like a find all feature that immediately highlights everything that matches the highlighted (or selected) portion of the code, this helps you see the flow of a particular variable or function through a script, allowing you to identify where it is introduced and where it is utilized. On a more advanced level this type of feature can be paired with multiple cursors for a powerful and more flexible reversion of replace, quick limited replace, etc.

It is particular useful since you can use different forms of selection for different results, for instance, if you have nothing highlighted, but your caret is over something, then the feature will expand the "selection" to the name that caret is hovering over, this can be done intelligently since the editor understands the syntax of GDScript, and find all matching instances of the selected name. On the other hand if you have something highlighted it acts like a "dumb" find where it will find anything that has the matching text, to better explain the difference:

If you have variables and functions with the following names:
player, player1_score, player2_score, get_player, and find_all_players

and you place your caret on an instance of player, then hit find-all-occurrences (or find next/previous occurrence) it will find all instances of the variable player, it will NOT highlight player1_score, player_score, get_player or find_all_players, however it would highlight player.get_node("something"), as it would understand that the dot operator isn't changing the variable name player into something else.

However, on the other end of the spectrum, if you highlight "player" from any of the instances mentioned above, it will do a dumb search and find the occurrence of player in all of the above, so it will highlight the text "player" in all instances of player1_score, player2_score, get_player and find_all_players.

I'm not sure if adding multiple cursors is really within the scope of this issue post, but potential keybindings for this feature could be split into three different features:

Alt-J : Find Next Occurrence (Go down in the script, if the last occurrence is found then tell the user, if they hit this key again it will wrap to the top of the script)

Shift-Alt-J : Find Previous Occurrence (Go up in the script, if the first occurrence is found then tell the user, if they hit this key again then the search will wrap to the bottom of the script)

Ctrl-Shift-Alt-J : Find All Occurrences (Highlights all occurrences in the script)

Highlighted sections will remain shown until a key is pressed or your click off with the mouse, you should be free to scroll to look at everything. Without a multiple cursor feature, find next and previous occurrence should leave the cursor at the last found occurrence, while find all occurrences will leave the cursor where it was when the feature was activated. Find next and previous should move your view of the script so that you can see the next or previous occurrence, however, find all occurrences should leave the screen location where it is.

**Comment by AlexHolly** [comment]
#2982

**Comment by vnen** [comment]
Highlighting selected text and highlighting all search occurrences are already implemented. The bit about multi-line editing is asked more specifically in #4884.

And the general tracker for editor improvements is #2982, which is better organized. So I'll close this issue as resolved and if I missed something you can create another issue with a specific request.
