### ISSUE TITLE
Vulkan: Sky Environment Mode Produces Constant Errors

### ISSUE THREAD

**Issue by luke13139** [godotengine/godot#36149]
**Godot version:**
4.0.dev, issue present since the merging of Vulkan branch.
Latest commit: 525c40a488c07ac072469cf9a694de77672d27bc

**OS/device including version:**
Windows 10 Version 1909, with 2020-02 Cumulative Update
GTX 1070 TI with driver version 442.19

**Issue description:**
When the current environment has the background mode set to "Sky", it produces a constant stream of identical errors. It does not produce these errors with any other mode.

```
ERROR: Condition "!shader" is true. returned: RID()
at: RenderingDeviceVulkan::uniform_set_create (drivers\vulkan\rendering_device_vulkan.cpp:4217)
```

I have seen other issues relating to the "Sky" environment mode, but nothing that mentions this error. Since this error may be specific to me and I have several console errors on load, I have included a trimmed version of a log file below. I have added comments to the log, which all begin with "#".
[SkyErrorLog.txt](https://github.com/godotengine/godot/files/4193159/SkyErrorLog.txt)

**Steps to reproduce:**
Set the current environment to mode "Sky" and switch to the 3D Editor. Also triggers on project creation since "Sky" is the default for default_env.tres.

**Comment by luke13139** [comment]
Can this issue be unarchived, as the issue this was a duplicate of was closed due to less information than this issue. Or was their another reason for marking this issue as archived?

**Comment by quantmint** [comment]
The same it's happening to me opening an empty project on linux 64bit, godot 4.0.dev.
`ERROR: Condition "!shader" is true. returned: RID()
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:4217)`
