### ISSUE TITLE
Enum not recognised in match statement if read from json file

### ISSUE THREAD

**Issue by MagellanicGames** [godotengine/godot#36147]
**Godot version: 3.2**

**OS/device including version: Kubuntu 18.04**

**Issue description:** If using an enum in a match statement, it will not match if the value is read from a file (in this specific case, json file) and assigned to a var without static typing.

The code below will cause the match statement to not recognise the enum type:
`var enum_type = parsed_json["enum_type"]`

This code will be recognised in the match statement:
`var enum_type : int = parsed_json["enum_type"]`

**Steps to reproduce:**
Create a json file with a single value held in a dictionary:
`{ "enum_type" : 2}`

1. Read file from disk
2. Parse the source with JSON.parse() giving you a Dictionary
3. Assign the parsed value from the Dictionary to a var without typing.

**Minimal reproduction project:**
[MatchBug.zip](https://github.com/godotengine/godot/files/4193003/MatchBug.zip)
![match_bug](https://user-images.githubusercontent.com/32498309/74347670-57702300-4da9-11ea-8e07-00c6069d6bde.png)

Of course if I am doing something fundamentally wrong please let me know, but I would have thought that if you're not using static typing then this could cause some real headaches.

**Comment by qarmin** [comment]
As you can see in a picture below, both variables have value 1, but `test_enum.type1` is integer(2 - Search TYPE_INT in builtin docs) and `enum_val` is a float value.

Comparison of integer and float usually show correct result, but as you can see not this time, so it is better to use typed gdscript or make sure, that variables are same type `enum_val = int(enum_val)`

![Zrzut ekranu z 2020-02-12 18-02-38](https://user-images.githubusercontent.com/41945903/74358946-9ced1a00-4dc2-11ea-85d3-8b0c31cda182.png)

**Comment by groud** [comment]
This is an expected behavior. As the JSON format does not differentiate between floats and int, the parser always interpret it as a float. Consequently, when you do your parsing, you need to cast the value to an int yourself. (which the type int does)

**Comment by Xrayez** [comment]
While JSON format does not differentiate between floats and int, it's still easy to make serialization errors like this. 

The part of the code responsible for parsing a JSON number in Godot:

https://github.com/godotengine/godot/blob/cf8c679a23b21d6c6f29cba6a54eaa2eed88bf92/core/io/json.cpp#L271-L279

So, `String::to_double` forces the value to be converted to floating point number. I do think it makes sense to allow parsing values which are recognized by Godot natively for serialization purposes so there's no "one-way conversion". It means that `to_json` and `parse_json` should be "idempotent", so to speak.

This issue can possibly be solved very similarly to how #33241 converts incompatible values to and from JSON.

**Comment by groud** [comment]
> It means that to_json and parse_json should be "idempotent", so to speak.

This is simply not possible. The JSON format does not even handle keys that are not string, and the parser shouldn't any unexpected black magic behind the scene to solve the problem. The JSON format has limitations, it's up to the user to know about them (we can document it though, to avoid future issues).

**Comment by Xrayez** [comment]
Sorry I was mostly talking about the ability to encode JSON-incompatible Variants within JSON-compatible strings the way it's proposed by #33241, but yeah currently it's not possible.
