### ISSUE TITLE
Unable to compile for Windows on Windows 10 after latest commit

### ISSUE THREAD

**Issue by luke13139** [godotengine/godot#36156]
**Godot version:**
Latest Commit: cf8c679a23b21d6c6f29cba6a54eaa2eed88bf92

**OS/device including version:**
Windows 10, Version 1909, 2020-02 Cumulative Update

**Issue description:**
The most recent commit has caused a compilation error for me. Compilation succeeds after reverting the latest commit. I am using Visual Studio. I also tested 32-bit, and I received the same error.
Using:
`scons -j6 platform=windows`
Compilation fails here:
```
video_stream_gdnative.cpp
register_types.cpp
[ 35%] Compiling ==> modules\gdnative\gdnative_api_struct.gen.cpp
[ 35%] gdnative_api_struct.gen.cpp
[ 36%] modules\gdnative\gdnative_api_struct.gen.cpp(60): error C2440: 'initializing': cannot convert from 'void (__cdecl *)(godot_int,godot_rid *,godot_rect2 *)' to 'void (__cdecl *)(int,godot_rid *,godot_rect2 *)'
modules\gdnative\gdnative_api_struct.gen.cpp(60): note: None of the functions with this name in scope match the target type
[ 36%] Compiling ==> modules\etc\image_etc.cpp
scons: *** [modules\gdnative\gdnative_api_struct.gen.windows.tools.64.obj] Error 2
image_etc.cpp
scons: building terminated because of errors.
```
output with `scons -j6 verbose=on warnings=all platform=windows`: 
[failed_build.log](https://github.com/godotengine/godot/files/4194244/failed_build.log)

**Steps to reproduce:**
Compile on Windows 10 using above setup.

**Comment by avencherus** [comment]
Same issue after clean -dfx:

**platform=windows tools=yes target=debug bits=64 -j4**

```
gdnative_api_struct.gen.cpp
modules\gdnative\gdnative_api_struct.gen.cpp(60): error C2440: 'initializing': cannot convert from 'void (__cdecl *)(godot_int,godot_rid *,godot_rect2 *)' to 'void (__cdecl *)(int,godot_rid *,godot_rect2 *)'
modules\gdnative\gdnative_api_struct.gen.cpp(60): note: None of the functions with this name in scope match the target type
scons: *** [modules\gdnative\gdnative_api_struct.gen.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Same on Windows and all CI builds (GCC, Clang, MSVC).
#36157 fixes it.
