### ISSUE TITLE
C# Project script errors with directory spaces

### ISSUE THREAD

**Issue by DeathTBO** [godotengine/godot#36168]
**Godot version:** 3.2

**OS/device including version:** Linux Fedora 32 x64

**Main Issue:** Godot writes to the project file with "%20" instead of spaces. This causes errors when attempting to compile Mono. It still 'works' and is playable as long as there are no duplicate entries.

I think it's partially related to: #35252 But it's not the same issue.

**Reproduce:** Create a new project. Create a folder with spaces. Add a new CSharp script in that folder. Build the Mono Project. Check the output.

In my test I created a C# class in "res://CSharp/Script Folder With Space/Test.cs". The output after attempting to build the Mono Project spits this out:

```
 Cannot open file 'res://CSharp/Script%20Folder%20With%20Space/Test.cs'.
 Failed to read file: 'res://CSharp/Script%20Folder%20With%20Space/Test.cs'.
 modules/mono/glue/gd_glue.cpp:250 - Failed to determine namespace and class for script: res://CSharp/Script%20Folder%20With%20Space/Test.cs. Parse error: FileNotFound
```
In the project file the script is added as:

```<Compile Include="CSharp\Script%20Folder%20With%20Space\Test.cs" />```

After replacing them with regular spaces the errors disappear.

In addition to that, it also causes a bunch of issues with my IDE (Rider) and possibly others. There end up being duplicate entries in the project file, one with regular spaces (from Rider) and one with the "%20". When the duplicate entries are there it will prevent compiling until it's resolved. On my main project it will also rewrite to the project file and add back the %20 entries. I'm not sure what triggers the rewrite, but it's tedious to constantly resolve them.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by DeathTBO** [comment]
I could not reproduce this on Godot 3.2.4 Beta 1
