### ISSUE TITLE
Terrain Node and Terrain Engine

### ISSUE THREAD

**Issue by unpause** [godotengine/godot#3616]
Hello,

I recently started using Godot and I like it a lot.

I really miss a terrain node for 3D which would make a lot of things much easier.
You can do terrains by importing another mesh or writing scripts but thats really a lot of work.
- unpause

**Comment by akien-mga** [comment]
This plugin should be a good start :) https://github.com/Zylann/godot_terrain_plugin

**Comment by MirceaKitsune** [comment]
I am very interested in seeing support for in-editor / in-game heightmap terrains, which some of my ideas may ultimately depend on. Godot 3.0 lacks this capability, which I'd consider one of its greatest missing features in my opinion.

Here is the Godot 3.0 version of the terrain plugin, which I'm hoping may become official soon:

https://github.com/Zylann/godot_heightmap_module

Here's also a video of it in action... I really like how that looks and works:

https://www.youtube.com/watch?v=pfVAfUEmNJs

**Comment by pgruenbacher** [comment]
https://github.com/godotengine/godot/issues/9046 is the tracker for terrain. @akien-mga @unpause someone can close this.
