### ISSUE TITLE
Cannot assign int to const ObjectID&

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#36162]
I didn't see anything mentioning ObjectID. Sorry if I missed a duplicate.

**Godot version:**
master cf8c679

**OS/device including version:**
Windows 10

**Issue description:**
Travis CI failure on [this line](https://github.com/godotengine/godot/blob/master/modules/mono/csharp_script.cpp#L165):

    modules/mono/csharp_script.cpp:165:30: error: invalid initialization of reference of type 'const ObjectID&' from expression of type 'int'

Code (`const ObjectID &id = E->get();`):

    #ifdef DEBUG_ENABLED
    for (Map<ObjectID, int>::Element *E = unsafe_object_references.front(); E; E = E->next()) {
        const ObjectID id = E->get();
        Object *obj = ObjectDB::get_instance(id);
    
        if (obj) {
            ERR_PRINT("Leaked unsafe reference to object: " + obj->get_class() + ":" + itos(id));
        } else {
            ERR_PRINT("Leaked unsafe reference to deleted object: " + itos(id));
        }
    }
    #endif

**Steps to reproduce:**
Run Godot through Travis CI. Built fine locally in Visual Studio.

**Minimal reproduction project:**
N/A

**Comment by clayjohn** [comment]
The Mono issue is already fixed in latest [master](https://github.com/godotengine/godot/commit/8080e5c4f3685b062190be3e1b54a18f0e2229a7). The recent ObjectID change did break a few other things though so master may be especially unstable
