### ISSUE TITLE
Content of the `ScrollContainer` can be drawn outside of its bounds

### ISSUE THREAD

**Issue by drichardson** [godotengine/godot#36164]
**Godot version:**
8080e5c4f3685b062190be3e1b54a18f0e2229a7

**OS/device including version:**
Microsoft Windows 10 Pro 64-bit Version 10.0.18363 Build 18363

**Issue description:**

The About window's Authors and Donors lists draw part of the list above the about window when scrolling down through the lists. See screenshot below.

![image](https://user-images.githubusercontent.com/36176/74377347-95188000-4d98-11ea-8b27-594acdd8dc25.png)

**Steps to reproduce:**

1. Go to the Help Menu > About
2. Select Donor list.
3. Scroll down.

At certain scroll locations, another part of the list will be drawn out of the bounds of the About window.

**Minimal reproduction project:**

Issue occurs in a new empty project.

**Comment by Calinou** [comment]
Can you reproduce this in 3.2-stable? I wonder if this is a regression from the (new and unstable) Vulkan renderer.

**Comment by drichardson** [comment]
@Calinou I wondered the same thing. I was going to compare against GL ES 2.0 with a new project, but as we discussed on IRC that crashed. I'll try 3.2 and get back to you.

**Comment by drichardson** [comment]
@Calinou The issue does not occur on 3.2 with either GLES2 or GLES3.

**Comment by KoBeWi** [comment]
Still valid in 2cbc0b6 but less severe.
![image](https://user-images.githubusercontent.com/2223172/102830161-fbbeef00-43e8-11eb-9991-9a632c6e00d8.png)

**Comment by pycbouh** [comment]
Just to reiterate my comment from #48179, this issue is not related to the "About" window, it happens with other `ScrollContainer`s as well.

**Comment by timothyqiu** [comment]
Still valid in 4.0 dev snapshot (20210727, pre-alpha, b4778082d1d8afe74eb5900e114b015faab4a526)

This happens in single window mode too, but still clipped inside the window.

**Comment by pycbouh** [comment]
> though it could use a MRP which is not the editor about dialog

@akien-mga I've run into the same issue in the Theme editor. Just make a theme by copying the editor theme and open some big type, say EditorIcons on the icons tab. Then:

https://user-images.githubusercontent.com/11782833/134893041-d5c24faa-796f-4c9d-932c-3a7dfae5119e.mp4


Doesn't break like that in `3.x` though. It's like the issue reported in https://github.com/godotengine/godot/issues/9612 was fixed, but now it's happening again in `master`.
