### ISSUE TITLE
PanelContainer hint does not show if it has a MarginContainer child

### ISSUE THREAD

**Issue by ntsik** [godotengine/godot#36170]
**Godot version:** 3.2.stable.official

**Issue description:** `Control`s have a `hint_tooltip` field which displays a hint when hovered. For a `PanelContainer` with a `MarginContainer` child, this hint does not display when hovered (by default).

By default, `MarginContainer`'s `mouse_filter` is set to `MOUSE_FILTER_STOP`. If it's changed to `MOUSE_FILTER_IGNORE`, then the parent `PanelContainer`'s hint tooltip will work again.

**Steps to reproduce:**

1. Create a `PanelContainer`
2. Add a `hint_tooltip` to the `PanelContainer`
3. Add a `MarginContainer` child to the `PanelContainer` (by default using `MOUSE_FILTER_STOP`)
4. Observe the hint tooltip does not appear upon hovering

**Minimal reproduction project:**
[panel_container_hint_bug.zip](https://github.com/godotengine/godot/files/4196227/panel_container_hint_bug.zip)

**Comment by akien-mga** [comment]
This is not a bug per se, it's as you described it: if a Control has `MOUSE_FILTER_STOP`, it will prevent its parent container's tooltip from being shown. You should change to `MOUSE_FILTER_PASS` if you want to forward the event to the parent.

The default mouse filter has been changed for containers in #35068, which incidentally solves this. It's a compat breaking change so it will not be backported to 3.2.
