### ISSUE TITLE
has_user_signal() returns false while it should not

### ISSUE THREAD

**Issue by groud** [godotengine/godot#36196]
**Godot version:** 3.2 stable

**OS/device including version:** Windows

**Issue description:**
The function `has_user_signal()` from object always return false, even if a signal is declared in the given node.

**Steps to reproduce:**
- Create a node with a "my_signal" signal defined at the top
- Try to call `has_user_signal("my_signal")` on the node

**Minimal reproduction project:**
[HasSignalBug.zip](https://github.com/godotengine/godot/files/4201443/HasSignalBug.zip)

**Comment by ShlomiRex** [comment]
i can confirm this ill try to fix it

**Comment by groud** [comment]
Note that I am not sure if this is a real issue. I believe it is, but apparently, only signals added with `add_user_signal(...)` work with `has_user_signal()`.
Maybe the solving the problem is only about implementing a distinct `has_signal(...)` function.

**Comment by Janglee123** [comment]
It should be a bug. Although why to distinguish user signals and built-in signals?

**Comment by pouleyKetchoupp** [comment]
I've proposed some changes some time ago in PR #33508 to address this issue.
