### ISSUE TITLE
Show C# syntax in docs

### ISSUE THREAD

**Issue by TZubiri** [godotengine/godot#36204]
**Godot version:** 3.2

**Issue description:**

The methods TileMap.Clear and TileMap.SetCell are defined in the documentation as clear and set_cell

https://docs.godotengine.org/en/3.2/classes/class_tilemap.html

**Comment by YeldhamDev** [comment]
The documentation uses GDScript's snake_case syntax.

**Comment by TZubiri** [comment]
Perhaps I forgot  to mention I am using C#, this syntax does not correspond to the actual method names in C#

**Comment by Calinou** [comment]
I'm not sure if we can do anything about the online documentation. As for the editor help, this could be still misleading as inline code examples will always use GDScript.

**Comment by TZubiri** [comment]
Changing casing to comply with language conventions was a very bad idea. Can godot catch errors for undefined methods and try to suggest the appropriate casing?

**Comment by TZubiri** [comment]
> Changing casing to comply with language conventions was a very bad idea. Can godot catch errors for undefined methods and try to suggest the appropriate casing?

There's a precedent for this aliasing behaviour.

using the function name _ready instead of _Ready works fine, but emits the following warning:

` modules/mono/mono_gd/gd_mono_class.cpp:189 - Method 'void _ready()' should be 'void _Ready()'. In class '.MapGenerator'.`

**Comment by Calinou** [comment]
Duplicate of #19655.
