### ISSUE TITLE
While in script editor ctrl+D paste a line instead of the duplicating node

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot#36205]
**Godot version:** 3.2
cant reproduce in 3.1.2

**OS/device including version:** Linux

**Issue description:** 
![Peek 2020-02-14 10-37](https://user-images.githubusercontent.com/29702428/74503262-632d2800-4f16-11ea-9d5b-8d98fdd183b7.gif)

**Steps to reproduce:** 
1. Create project, add node like Timer or Tween
2. Open Script editor 
3. select Timer node and Press Ctrl+D

**Comment by Calinou** [comment]
The original behavior (duplicating the current line) is intended. It just shouldn't happen while the Scene tree dock is focused.

**Comment by HaSa1002** [comment]
That is one of the most annoying bugs, I deal with. Especially since it is also present in the Shader Editor and I am normaly in the script tab... Let's see if I manage to fix it.

**Comment by HaSa1002** [comment]
Found it. https://github.com/godotengine/godot/blob/39f7a4092533a600eeada6638016af8bd4bd2271/editor/code_editor.cpp#L672-L702
There a no checks at all
