### ISSUE TITLE
Thick 2D grid on HiDPI display

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#36207]
**Godot version:** 4.0.dev.custom_build.8bcceee94

**OS/device including version:** macOS 10.15.2

**Issue description:**
The grid in the 2D editor is thick on a HiDPI display. I thought the grid was blurry at first, but the bars on the ruler is also thicker.

<img width="329" alt="demo" src="https://user-images.githubusercontent.com/372476/74511738-9b962b80-4f41-11ea-8244-01af30734297.png">

This happens after the Vulkan merge.

_Edit:_ This also affects Path2D/Curve display: (current master vs 3.2)
<img width="505" alt="curve" src="https://user-images.githubusercontent.com/372476/74891204-4cc51780-53c1-11ea-952e-53c438649d86.png">

**Steps to reproduce:**
1. Open Godot on a HiDPI display, or set the Display Scale to 200%
2. Create a new 2D scene, and turn on "Always Show Grid"

**Minimal reproduction project:** N/A

**Comment by Calinou** [comment]
I'm not sure if this is entirely a bug, as line thicknesses are generally expected to scale with the editor scale. I guess it was inadvertenly changed in the Vulkan merge somehow?

**Comment by timothyqiu** [comment]
This can still be reproduced on the current master.

Seamless display scaling is now implemented on macOS. The grid now looks blurry on a LoDPI monitor too, as long as there is a HiDPI monitor available.

**Comment by timothyqiu** [comment]
Compared with the screenshot two years ago, I think this is fixed. The lines look normal now. 

| Before | After |
| -- | -- |
| ![then](https://user-images.githubusercontent.com/372476/74511738-9b962b80-4f41-11ea-8244-01af30734297.png) | ![now](https://user-images.githubusercontent.com/372476/160263563-b0b57d36-ac7c-44b2-afc5-7de44fff520f.png) |
