### ISSUE TITLE
ui_up and ui_down not changing menu focus with cursor keys for a RichTextLabel list (but work with other keys)

### ISSUE THREAD

**Issue by emik** [godotengine/godot#36211]
**Godot version:**
Godot_v3.2-stable_win64

**OS/device including version:**
Windows 10

**Issue description:**
A simple menu list has navigable up and down focus with default gamepad dpad settings or added input for ui_up and ui_down (e.g. setting up to W, down to S), but up and down cursor keys do not navigate up and down in the menu.

**Steps to reproduce:**
1. Create control with a list of RichTextLabel elements
2. Ensure labels have visible focus settings for debugging
3. Play scene and attempt to navigate up and down.

Use gamepad D-pad or set other ui_up and ui_down keys to ensure menu otherwise works normally.

Sidenote: GD documentation mentions [ui_top](https://docs.godotengine.org/en/3.2/classes/class_control.html#class-control-property-focus-neighbour-top) input when it should be ui_up.

**Minimal reproduction project:**
[ui_bug.zip](https://github.com/godotengine/godot/files/4204488/ui_bug.zip)

**Comment by dreamsComeTrue** [comment]
I've attached detailed explanation of how it works under the hood - and PR with a fix for that issue.
Hope, that will clear out that confussion.
