### ISSUE TITLE
Incompatible TextFile resource between Windows 10 and macOS

### ISSUE THREAD

**Issue by JohnCWakley** [godotengine/godot#36216]
**Godot version:** v3.2.stable.official

**OS/device including version:** Windows 10 v10.0.18362 Build 18362 & macOS 10.15.3

**Issue description:**
I created a TextFile resource ("design.tres") on my Windows machine. After pulling changes (git version 2.21.1 (Apple Git-122.3)) to work remotely on my MacBook Air, I tried to open the resource and received this error (on the mac):
```
scene/resources/resource_format_text.cpp:1190 - res://design.tres:1 - Parse Error: Expected '['
scene/resources/resource_format_text.cpp:843 - res://design.tres:1 - Parse Error: Expected '['
Failed to load resource 'res://design.tres'.
Failed loading resource: res://design.tres.
editor/editor_node.cpp:735 - Condition "!res.is_valid()" is true. Returned: ERR_CANT_OPEN
```
Using VS Code, I copied the text from "design.tres" and then from within Godot Editor, created a new TextFile "design.res", pasted the text, and saved.

Later, on my Windows machine, I pulled (git version 2.22.0.windows.1) my changes, and when opening the resource received the following error:
```
Unrecognized binary resource file: res://design.res.
Failed to load resource 'res://design.res'.
Failed loading resource: res://design.res.
editor/editor_node.cpp:735 - Condition "!res.is_valid()" is true. Returned: ERR_CANT_OPEN
```

**Steps to reproduce:**

1. On a Windows machine, create a TextFile resource and add some text, then commit and push to a git repo.
2. On a macOS machine, checkout the repo and open in Godot.
3. Double-click the resource.

**Expected Result:**
File opens normally.

**Actual Result:**
Received an error.

**Comment by akien-mga** [comment]
I don't understand what's the incompatibility between macOS and Windows 10? It seems like it's not working in either case, likely because of a misunderstanding about what `TextFile` is (or isn't).

`TextFile` is being unexposed in 4.0 as it's not meant for use via the public API, it's only for the script editor to internally load text files as a suitable resource type. #36182

**Comment by JohnCWakley** [comment]
> I don't understand what's the incompatibility between macOS and Windows 10?

If I create the file on Windows, close it and reopen (still in Windows), it opens fine. When I try to open it on my mac, it does not open at all and the error is logged.

> It seems like it's not working in either case, likely because of a misunderstanding about what TextFile is (or isn't).

I thought the TextFile resource was a place to store any text, like JSON for instance. I wanted to use it to store some design notes. I've moved to just using a .txt file, but that isn't editable from within Godot Editor.

No worries, I will continue using a .txt and just edit that with another editor. Thank you for such a quick reply and helping me understand the TextFile resource purpose!

I absolutely love this engine!  :)

**Comment by Paulb23** [comment]
@JohnCWakley You should be able to edit `.txt` files in editor. 

The only way to do so currently is in the script tab, click `File --> Open` in the bottom right of the file dialog select `All Files (*)`, then open your `.txt` file.

**Comment by JohnCWakley** [comment]
Oh, thank you Paul, I didn't even think to open it from within the script
editor. I just assumed they weren't accessible since my design.txt doesn't
show up in the FileSystem tab. Thank you! :)
