### ISSUE TITLE
Array mesh ignores light

### ISSUE THREAD

**Issue by cobreen** [godotengine/godot#36210]
**Godot version:**
3.2.stable official

**OS/device including version:**
windows 10.  acer Nitro AN515-52

**Issue description:**
I've created Mesh instance with array mesh and created a primitive triangle from vertexes.
After that, I've set material override to spatial and changed colour to red.
This color is very dark and I tried to light it up by Omni light. It looks like array mesh ignores light
![Img](https://user-images.githubusercontent.com/22748041/74529934-8fa26d80-4f31-11ea-9524-a8b564208d53.png)

**Minimal reproduction project:**
[godot.zip](https://github.com/godotengine/godot/files/4204326/godot.zip)

**Comment by Zireael07** [comment]
If you only gave it the vertexes, it doesn't have normals.
https://docs.godotengine.org/en/3.2/tutorials/content/procedural_geometry/arraymesh.html#doc-arraymesh

**Comment by clayjohn** [comment]
As Zireael has pointed out, you need normals in your mesh for lighting to work. The tutorial they linked has all the info you need. 

In the future, instead of reporting a bug, first ask for help on one of the [Community Channels](http://docs.godotengine.org/en/latest/community/channels.html)
