### ISSUE TITLE
Cannot run scene by tool script in 3.2: OS.execute(scene_path, [], false) gives error: ' ret == 0 ' is true

### ISSUE THREAD

**Issue by takaturre** [godotengine/godot#36227]
**Godot version:**
3.2. stable

**OS/device including version:**
Win 10

**Issue description:**
In 3.1.2, you could still launch a scene by script by: `OS.execute(scene_path, [], false)`. However, in 3.2 (at least beta5 and stable), this produces an error:  `platform/windows/os_windows.cpp:2737 - Condition ' ret == 0 ' is true. returned: ERR_CANT_FORK`. 

If this change was done on purpose, then what is the correct way to launch a Godot scene by a tool script? 

**Steps to reproduce:**
1. Save a scene.
2. Make a tool script and execute the saved scene from it by: `OS.execute(scene_path, [], false)`
3. The given error is thrown.

**Workarounds:**
In 3.1.2 you could also do a workaround for some cases by simulating an F6 key press in an earlier version (by making a new `InputEventKey`, assigning `scancode` and `pressed` to it, and calling `Input.parse_input_event(e)`.) But even that doesn't seem to work anymore. (And doesn't apply to all cases, and is kind of awkward anyhow.)

**Minimal reproduction project:**
Open the project and click the scene root, and in the inspector *Launch Scene*.
[CannotExecuteScene.zip](https://github.com/godotengine/godot/files/4208969/CannotExecuteScene.zip)

**Comment by Calinou** [comment]
I don't see how the script can work in the first place. A `.tscn` file isn't executable, so you need to specify it as a command-line argument to the Godot executable rather than trying to run the `.tscn` file directly:

```text
OS.execute("path/to/godot.exe", scene_path, false)
```

**Comment by takaturre** [comment]
Sorry, my bad - still quite new to Godot. I grabbed the original from some thread, and it did work in 3.1.2, so assumed a bug. Anyway, thanks a lot..!
( Got it working with: `OS.execute(OS.get_executable_path(), [ scene_path ], false)` )
