### ISSUE TITLE
Godot 4.0 dev crash after open especific project

### ISSUE THREAD

**Issue by matheusmdx** [godotengine/godot#36220]
**Godot version:**
4.0 Dev

**OS/device including version:**
Windows 10 Pro x64 - Version 1809
Pegatron IPMH61P1
Intel core I7-2600
Nvidia GTX 1060 3GB - Driver: Game ready driver 441.87
2 X 4GB Ram

**Issue description:**
After click to open the project, godot print a lot of errors and close

![Engine Crash](https://user-images.githubusercontent.com/44306054/74550405-16eee180-4f30-11ea-960d-a485759855d0.png)

And after try open project again, godot printed this errors (aparentily is same error with some bugged characters)

![Captura 1581697624 13-27-04 14-02-2020](https://user-images.githubusercontent.com/44306054/74550529-4c93ca80-4f30-11ea-9320-7afc09fcd95c.png)

Godot 3.1 and 3.2 open this project normally

Edit: I don't know if this has any connection but every time I open the godot I get the following errors

![Abrindo o godot pela primeira vez](https://user-images.githubusercontent.com/44306054/74551927-e65c7700-4f32-11ea-81b5-ceafbc0b1c88.png)

**Steps to reproduce:**
Open the project in project manager

**Minimal reproduction project:**
[Global Game Jam 2020 - Shattered Mininal.zip](https://github.com/godotengine/godot/files/4205513/Global.Game.Jam.2020.-.Shattered.Mininal.zip)

**Comment by Anutrix** [comment]
Please mention commit hash.

**Comment by Anutrix** [comment]
It seems it was using GLES2 which is currently broken and disabled.
In your project,godot, around the end, there's a line ```quality/driver/driver_name="GLES2"```.
Change that `"GLES2"` to `"Vulkan"` which should delete it on next run (or you can even delete it yourself probably).

It should run now(i.e, not crash). Note that master is unstable so it might not work properly.

**Comment by matheusmdx** [comment]
> 
> 
> Please mention commit hash.

Sorry for my lack of knowledge but where do I check the hash?

**Comment by clayjohn** [comment]
You also need to delete the .import folder before trying to open a project made in 3.x in 4.0

**Comment by Anutrix** [comment]
> 
> 
> > Please mention commit hash.
> 
> Sorry for my lack of knowledge but where do I check the hash?

It's fine. Hashes allow us to pin point which version of custom build of Godot you are using.
![Capture81](https://user-images.githubusercontent.com/11459028/74553454-6c051480-4f7d-11ea-8850-7f4b8e0cdacb.png)
You can also find it Help->About after opening the project.
Usually XXXXXXXXX in v4.0.dev.custom_build.XXXXXXXXX everywhere is the hash.
Just realized that it's on the first line of the Godot console too.

**Comment by matheusmdx** [comment]
> 
> 
> It seems that the project was using GLES2 which is currently broken and disabled.
> In your project,godot, around the end, there's a line `quality/driver/driver_name="GLES2"`.
> Change that `"GLES2"` to `"Vulkan"` using a text editor.
> [It will delete it on next run (or you can even delete it yourself probably)].
> It should run now(i.e, not crash).
> 
> Note that master is unstable so it might not work properly.

This change resolved the issue

<br/>

> 
> 
> You also need to delete the .import folder before trying to open a project made in 3.x in 4.0

Hm I didn't know that, thanks for the warning
