### ISSUE TITLE
Websocket HTML5 ws.get_peer(1).put_var("hi") causes black screen (put_packet fails too)

### ISSUE THREAD

**Issue by Ivan-Tigan** [godotengine/godot#36239]
**Godot version:**
3.2
**OS/device including version:**
Linux/Ubuntu/PopOS
Browser is Google Chrome
**Issue description:**
I have a simple WebSocketClient.
Connection works fine for HTML5, Linux, and Android.
ws.get_peer(1).put_var("hi") (put_packet fails, too)
is the line that works on Linux and Android (Connection Established picture) but causes a black screen on HTML5 (no picture because it is just blackness).
(Found it out by commenting it out and in)
When I comment it out I get the Connection Established picture in the Browser, too.
Can't really get debug information. Can't do inspect element or anything like that either.
Google didn't help despite my best efforts.
Please help!
**Steps to reproduce:**
Create project -> Create Websocket Client -> Connect to ws://echo.websocket.org (or wss://...) -> put put_var related code in process -> Run in Browser
**Minimal reproduction project:**
![image](https://user-images.githubusercontent.com/44375889/74584435-40f4e200-4fca-11ea-889d-57222855a03b.png)
![image](https://user-images.githubusercontent.com/44375889/74584438-481bf000-4fca-11ea-82b1-514db07afdc8.png)
![image](https://user-images.githubusercontent.com/44375889/74584443-4eaa6780-4fca-11ea-9e94-d26dabf75bbf.png)

[ws_echo_tester_2.zip](https://github.com/godotengine/godot/files/4207917/ws_echo_tester_2.zip)

**Comment by Faless** [comment]
I confirm this issue, investigating.

**Comment by Faless** [comment]
the cause seems to be `get_connection_status` returning the wrong value when the peer is connecting. Working on a fix

**Comment by Faless** [comment]
Note that you can temporarily workaround this issue by programmatically keeping track of the connection state via the `connection_established` signal and only using put_var after you receive that signal.

**Comment by Ivan-Tigan** [comment]
Thanks a lot!
