### ISSUE TITLE
Y-Billboard mode doesn't work

### ISSUE THREAD

**Issue by zio-hub** [godotengine/godot#36238]
**Godot version:**

3.2 stable

**OS/device including version:**

Windows 10 x64

**Device:**

AMD A4 7300 x86_64 APU

**GPU model:**

Radeon HD 8470D

**Issue description:**

Spatial Material and Sprite3D Flag Billboard mode not working.

**Steps to reproduce:**

Sprite3D with Spatial Material Billboard Mode:
![with_material](https://user-images.githubusercontent.com/52806598/74583887-da140080-4faa-11ea-969e-149b4e260061.png)

Sprite3D with Billboard flag:
![with_flag](https://user-images.githubusercontent.com/52806598/74583954-cae18280-4fab-11ea-8849-94d7de96d0e7.png)

How it looks in game:
![y-billboard](https://user-images.githubusercontent.com/52806598/74583965-e9477e00-4fab-11ea-9e94-c54db4e4f8db.gif)

**Minimal reproduction project:**
[Y-Billboard test.zip](https://github.com/godotengine/godot/files/4207885/Y-Billboard.test.zip)

**Comment by Calinou** [comment]
Does it work if you use a MeshInstance with a PlaneMesh (or QuadMesh) attached?

**Comment by zio-hub** [comment]
I tried with a PlaneMesh and QuadMesh, same results.
![planemesh](https://user-images.githubusercontent.com/52806598/74595192-58a98600-501d-11ea-897f-fde64b83ea2c.gif)

**Comment by zio-hub** [comment]
Just in case, i tried the same scene in my linux boot (same pc) and everything works well:
![ybillboardlinux](https://user-images.githubusercontent.com/52806598/74596465-4552e680-502e-11ea-8d55-48971252c08d.gif)

On Xubuntu x86_64

**Comment by Calinou** [comment]
@zio-hub Try switching to the GLES2 renderer. The GLES3 renderer is known to behave poorly on old/low-end AMD GPUs.

**Comment by zio-hub** [comment]
Same results with GLES2.

**Comment by noass** [comment]
This exact thing happens to me too 
I have Windows

**Comment by clayjohn** [comment]
Might have been fixed by #39867 which will be in 3.2.3. Once 3.2.3 releases, please let us know if it is fixed. Alternatively, you can build from the 3.2 branch to test if it works.

**Comment by noass** [comment]
I switched to Linux and it works there...

**Comment by akien-mga** [comment]
You can test with 3.2.3 beta 1: https://godotengine.org/article/dev-snapshot-godot-3-2-3-beta-1

**Comment by bagelpigeon** [comment]
I know this is a little late, but I just ran into the same problem. I don't think this is an issue with Godot, seems to be an issue with the graphics drivers- I also have an AMD gpu. I fixed this by updating my AMD card drivers from device manager (my card was OEM and not a separate part so you might have to download from AMD's website if device manager can't update it). It also fixed a bunch of issues like particle effects not rotating properly.

**Comment by zio-hub** [comment]
> I know this is a little late, but I just ran into the same problem. I don't think this is an issue with Godot, seems to be an issue with the graphics drivers- I also have an AMD gpu. I fixed this by updating my AMD card drivers (2015 drivers to 2016) from device manager (my card was OEM and not a separate part so you might have to download from AMD's website if device manager can't update it). It also fixed a bunch of issues like particle effects not rotating properly.

This fixed the problem for me too. Thanks!
