### ISSUE TITLE
increasing max_render_elements has no effect

### ISSUE THREAD

**Issue by paulmiller** [godotengine/godot#36240]
**Godot version:**
3.1 & 3.2

**OS/device including version:**
Arch Linux (i7-6700, GTX 1070, nvidia driver 440.59-7) & Windows 8.1 (i7-3517U, HD 4000, Intel driver 10.18.10.3496)

**Issue description:**
Increasing max_render_elements doesn't seem to have any effect. The attached project draws 100,000 cubes. The project's max_render_elements has been increased from the default 65,536 to 100,000, but the result looks the same as when it was 65,536; not all the cubes are drawn. On the other hand, decreasing max_render_elements does reduce the number of cubes drawn.

**Steps to reproduce:**
Run the attached project. See that not all objects are rendered. Drag with the mouse to rotate the camera. Try changing max_render_elements (Project > Project Settings > Rendering > Limits > Max Renderable Elements), restart Godot, and check again. Still, not all objects are rendered.

**Minimal reproduction project:**
[max-objects-bug.zip](https://github.com/godotengine/godot/files/4207934/max-objects-bug.zip)

**Comment by Calinou** [comment]
This should be fixed by https://github.com/godotengine/godot/pull/35447.

**Comment by akien-mga** [comment]
Fixed by #44435.
