### ISSUE TITLE
Exporting exe doesnt work

### ISSUE THREAD

**Issue by Favkis** [godotengine/godot#36249]
v3.2.stable

windows 10

when I export game and start it on other pcs it says something like  
Can't load dependency: C:/Users/yiffstorage/Documents/Dark Field/materials/map/env/metal.png

EVEN THOUGH THAT IS F*CKING name of MY PC, not PCs I try to run game on. And on MY PC game runs fine when exported. 

Make big project that is not a tech demo made in 10 hours, export it and run on other pc.

**Comment by Calinou** [comment]
Please upload a minimal reproduction project and follow the issue template. At this point, I think you're better off asking on one of the [community channels](https://godotengine.org/community).
