### ISSUE TITLE
GDScript but not C# is able to set Blend Shapes values via code 

### ISSUE THREAD

**Issue by GeorgeS2019** [godotengine/godot#36243]
**Godot version:** 3.2 (stable) mono

**OS/device including version:** Windows 10 19014

**Issue description:**
The attached project shows GDScript (but not a similar c#) is able to set the blend_shape value via code

**Steps to reproduce:**
See the attached project, run Game scene with 2 sphere, the one (red) with GDscript works, not the green sphere with c#

**Minimal reproduction project:**
[BlendShapeCsharp.zip]
(https://github.com/godotengine/godot/files/4208427/BlendShapeCsharp.zip)
[Ref ](https://www.youtube.com/watch?v=ZJClHuIXRUM)of the modified project: 

Other open issues with blend shapes
Most relevant: 
https://github.com/godotengine/godot/issues/15778

Other FYI isseus:
https://github.com/godotengine/godot/issues/31595
https://github.com/godotengine/godot/issues/34658
https://github.com/godotengine/godot/issues/24226
https://github.com/godotengine/godot/issues/17749

**Comment by GeorgeS2019** [comment]
In Csharp,  BlendShape are get and set through two classes
ArrayMesh.cs and VisualServer.cs

Interestingly, in ArrayMesh.cs there is no corresponding SetBlendShapeWeight method
Could this explain why the above bug happens?


================================================
There is this method in VisualServer.cs

```csharp
/// <summary>
/// <para>Sets the weight for a given blend shape associated with this instance.</para>
/// </summary>
[GodotMethod("instance_set_blend_shape_weight")]
public static void InstanceSetBlendShapeWeight(RID instance, int shape, float weight)
{
     NativeCalls.godot_icall_3_630(method_bind_262, ptr, RID.GetPtr(instance), shape, ref weight);
}
```

**Comment by GeorgeS2019** [comment]
One way to by pass bugs in Csharp is to call [GDScript ](https://github.com/godotengine/godot/issues/23164)from c#

**Comment by BastiaanOlij** [comment]
instance_set_blend_shape_weight is a method that is called from MeshInstance and takes data from the mesh instance consuming the mesh. I'm guessing each mesh instance can set their own weights even when they reuse the same mesh.

If you try and call that method on the visual server and pass it an ArrayMesh instead of a MeshInstance I can imagine it will crash.

**Comment by neikeq** [comment]
From a quick look, you're calling `set` in GDScript but `_Set` in C# instead of `Set`. Could that be the cause?

**Comment by GeorgeS2019** [comment]
@neikeq I just check, U are right. Next time, I go straight to u without waiting too long here :-)
