### ISSUE TITLE
RayCast2D will not collide with TileMap if it's fully inside tile

### ISSUE THREAD

**Issue by gforceg** [godotengine/godot#36259]
**Godot version:**
3.2.stable

**OS/device including version:**
elementary OS 5.1 Hera (Ubuntu 18.04.3 LTS)

**Issue description:**
I have a RayCast2D that is a child node of an Area2D. When RayCast2D does not overlap with its parent, is_colliding() is always false when the ray overlaps with a tile.
The ray is enabled and it does ignores its parent.

![unknown](https://user-images.githubusercontent.com/14267747/74597755-ac1dd300-5021-11ea-8065-c7d877ced63b.png)

**Steps to reproduce:**
Create an Area2D scene with a RayCast2D element that does not overlap with its parent Area2D. The RayCast2D will not collide with tiles that have a collision shape

**Minimal reproduction project:**
https://gitlab.com/gforceg/raycast-problem

**Comment by gforceg** [comment]
The rays are 32px in length which is half the TileMap cell size. I notice that if I increase them to 64 they collision works.

**Comment by Xrayez** [comment]
In the second case you linked in the project the raycast lies inside the tile, so no intersection is detected against the tile's geometry. I think it would be preferred that the raycast could return the intersection *point* if the origin lies inside the geometry. Related to #35845.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4
