### ISSUE TITLE
GLFT import, can't find object

### ISSUE THREAD

**Issue by chitalian** [godotengine/godot#36254]
**Godot version:**
3.1
**OS/device including version:**
MacOS Mojave, 10.14.3
**Issue description:**

I am having issues finding my GLTF file after I import it. 

The offset of it is really large. When I step through the source code here: https://gltf-viewer.donmccurdy.com/. I notice that the board is offset by this much:
``` javascript
x: -299510456
y: 98424296
z: -975000
```

**Steps to reproduce:**

Import thus glb file into GoDot and try to offset it by the coords listed above.
[F.Cu.glb.zip](https://github.com/godotengine/godot/files/4209048/F.Cu.glb.zip)

Still cannot see it.

**Comment by Calinou** [comment]
I think this is expected if the object is very far from the origin. You'd need to navigate to those coordinates whose precision isn't guaranteed (due to floating-point precision issues).

**Comment by Calinou** [comment]
I'll close this as I don't think this is something that can be fixed on our end. The source scene should be fixed to use a reasonable offset (ideally none, for easier placement into the game world).
