### ISSUE TITLE
Feature removal in MeshLibrary.get_item_preview()

### ISSUE THREAD

**Issue by Alvati** [godotengine/godot#36268]
**Godot version:** 3.2

**OS/device including version:** Any

**Issue description:**

Commit a199e2b2631064015daab94780e06bfbb24ae3d5 removes the abilty to use `MeshLibrary.get_item_preview() in a runing game, with the explanation that preview generation only works in the editor.

However, MeshLibrary never generates any preview, contrary to what the commit says, it merely fetches back a Texture from a Map, previously put in the with set_item_texture()

**Commit proposall:**
The restriction at the start of MeshLibrary.get_item_preview() can just be commented out to return to pre-3.2 behaviour.
```
//if (!Engine::get_singleton()->is_editor_hint()) {
//	ERR_PRINT("MeshLibrary item previews are only generated in an editor context, which means they aren't available in a running project.");
//	return Ref<Texture>();
//}
```

The documentation, on top of reffering to the GridMap tutorial which presents a practical way of generating MeshLibraries, could include a snippet to automatically update the previous:
```
# Retrieving the meshes of mesh_library
var meshes = []
for id in mesh_library.get_item_list():
	meshes.append(mesh_library.get_item_mesh(id))

# Generating previews in bulk
var previews = get_editor_interface().make_mesh_previews(meshes, 400)

# Setting the previews
for id in mesh_library.get_item_list():
	mesh_library.set_item_preview(id, previews[id])
```

   **Post Scriptum:**
I'm sorry to put this in a bug report, but I have no clue on how to make a commit request and had to recompile the engine with that whange to keep my project working.

**Comment by mourning20s** [comment]
@Alvati Here's the documentation/tutorial on Godot's PR workflow if you still wanted to submit one:
https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html
