### ISSUE TITLE
Editor crashes when pressing Enter in ConnectDialog with nothing selected

### ISSUE THREAD

**Issue by 2821869675** [godotengine/godot#36264]
**Godot version:**
3.2
**OS/device including version:**
Windows 7 64
**Issue description:**
collapse
**Steps to reproduce:**
The following is Chinese, if you do not understand, please translate

对一个没有自定义脚本的组件添加信号连接
输入函数名后按回车崩溃

![图片](https://user-images.githubusercontent.com/35617666/74603997-75fd5380-50f4-11ea-8b12-6e374a5bdb1f.png)
![图片](https://user-images.githubusercontent.com/35617666/74604003-8f9e9b00-50f4-11ea-869a-e824b5be4dcb.png)

没有自定义脚本时
**Minimal reproduction project:**

**Comment by dreamsComeTrue** [comment]
That's very rude way of composing an issue. Change it's title and language - if you need some help, please - provide it as much as you can first, to as many people as can understand that.

**Comment by golddotasksquestions** [comment]
@dreamsComeTrue 
Why not assume the tone is lost in translation and lack of foreign language skills? One could equally say it is rude to demand English as the only allowed language here, when clearly not spoken by everyone. Users from all around the World use Godot and not everyone who likes to make a game can also speak a second language. OP could be very young too. 

It's just a crash report.
I doubt anything can be done about it with that little info given, though.

不幸的是，这还不足以让任何人做任何事情。 您能重现崩溃吗？ 如果是这样，您能否列出一个人从空白项目到崩溃所需要采取的确切步骤？

**Comment by dreamsComeTrue** [comment]
I am not a native eng speaker too, but there are some unspoken rules across dev communities - and one of them is common language to communicate, which for whatever reasons always been English :)

If person makes an Issue and have some time and effort for preparing them, he/she could also spend 1 minute more, putting anything that could help developers to understand his/hers problem better - it's not a big deal, it's just a matter of respecting ourselves.

**Comment by LinuxUserGD** [comment]
"Add a signal connection to a component without a custom script
  Crash by pressing enter after entering the function name

  When there is no custom script"

"Unfortunately, this is not enough for anyone to do anything.  Can you reproduce the crash?  If so, can you list the exact steps a person needs to take from a blank project to a crash?"

**Comment by 2821869675** [comment]
![1](https://user-images.githubusercontent.com/35617666/75601820-222e3980-5afa-11ea-8d4f-e239935f94a0.png)
![2](https://user-images.githubusercontent.com/35617666/75601822-23f7fd00-5afa-11ea-8606-e4aea7497c35.png)
![3](https://user-images.githubusercontent.com/35617666/75601824-265a5700-5afa-11ea-94ca-f7200034bb3f.png)
![4](https://user-images.githubusercontent.com/35617666/75601825-278b8400-5afa-11ea-9033-28e7f0054f48.png)
@golddotasksquestions

**Comment by LinuxUserGD** [comment]
@2821869675 It's fixed in Vulkan master (and future 3.2.1) when compiling from source (see PR) so it's only reproducible in current 3.2 stable e. g. when using Godot on Steam.
