### ISSUE TITLE
array.pop_back() doesn't cause an error

### ISSUE THREAD

**Issue by CodeDarigan** [godotengine/godot#36265]
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
When using Array.pop_back() while it has no elements it returns null instead of raising an error leading to unclear behaviour.

**Steps to reproduce:**

```
extends Node

func _ready():
	var source = []
	var destination = []
	for i in 5:
		var result = source.pop_back()
		print(result)
		destination.append(result)
	print(destination)
```

Which gives the result:
null
null
null
null
null
[null, null, null, null, null]

**Comment by mrcdk** [comment]
This isn't an issue, it's clearly stated in [the documentation](https://docs.godotengine.org/en/3.2/classes/class_array.html#class-array-method-pop-back).

**Comment by CodeDarigan** [comment]
Ah it was a 3.2 change. Alright.

**Comment by dreamsComeTrue** [comment]
There are no exceptions (currently) in GDScript - so don't know how would you imagine rising that error.

**Comment by Calinou** [comment]
Should we make `pop_back()` print an error message in this case?
