### ISSUE TITLE
Negative videos in format .ogv - Godot Engine Issues

### ISSUE THREAD

**Issue by diegohiroshi** [godotengine/godot#36278]
**Godot version:**
Godot_v3.1.2-stable_win64

**OS/device including version:**
Windows 10 

**Issue description:**
On node VideoPlayer, try to play an OGV format video (with colour).

- Into runtime vídeo plays in negative.

- Original video be find it color.

**Steps to reproduce:**
Just is simple animation video for tiles / symbols animation in reward.
![CQalgk](https://user-images.githubusercontent.com/59515243/74610123-04f77500-50cf-11ea-9bc4-5f191d9883ab.gif)

**Minimal reproduction project:**
I don't find a function optional that permit change this parameter. I suggest put invert option.

![issue-godot2-2020](https://user-images.githubusercontent.com/59515243/74610392-98ca4080-50d1-11ea-9c48-d131b8fb4907.jpg)

![issue-godot-2020](https://user-images.githubusercontent.com/59515243/74610255-50f6e980-50d0-11ea-83b0-6e644514d49c.jpg)

Ok that's it all, I hope any solution. Thanks for reading. 
Regards and blessings from Argentina 😊

**Comment by Calinou** [comment]
@diegohiroshi Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by diegohiroshi** [comment]
Ok, It serves you right now?.

**Minimal reproduction project:**
[Minimal reproduction project - VideoPlayer Issues.zip](https://github.com/godotengine/godot/files/4211249/Minimal.reproduction.project.-.VideoPlayer.Issues.zip)

**Comment by KoBeWi** [comment]
Looks fixed in 3.2.4 beta4
