### ISSUE TITLE
OS.get_unique_id only implemented on Android and iOS

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3628]
_Bugsquad edit:_ This issue is actually not specific to HTML5, but `OS.get_unique_ID` is only implemented on Android and iOS; on all other platforms it returns an empty string and an error message.

See https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=get_unique_ID

---

Seen while testing Minilens in Firefox 64-bit on Linux, Godot 2.0 Beta:

```
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
ERROR OPENING FILE: icon.png
close data.pck flags 1
[1;31mERROR: get_unique_ID: [0m[1mMethod/Function Failed, returning: ""
[0;31m   At: core/os/os.cpp:459.[0m
close data.pck flags 1
close /userfs/options.txt flags 2
close /userfs/options.txt flags 1
[SUTjoystick]: mouse emulation enabled
close data.pck flags 1
close data.pck flags 1
elapsed 8 tts 4992
elapsed 287 tts 4705
elapsed 89 tts 4616
```

I don't know if the `get_unique_ID` error is related to the previous error about icon.png, so in doubt I give a good chunk of the log.

**Comment by akien-mga** [comment]
Further down the log, after `DOING SYNCH!`:
```
[SUTjoystick]: mouse emulation disabled
close /userfs/options.txt flags 1
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
close data.pck flags 1
[1;31mERROR: get_unique_ID: [0m[1mMethod/Function Failed, returning: ""
[0;31m   At: core/os/os.cpp:459.[0m
[1;31mERROR: get_unique_ID: [0m[1mMethod/Function Failed, returning: ""
[0;31m   At: core/os/os.cpp:459.[0m
close /userfs/savedata.bin flags 2
[1;31mERROR: get_unique_ID: [0m[1mMethod/Function Failed, returning: ""
[0;31m   At: core/os/os.cpp:459.[0m
MAGIC: 1128612935
MODE: 1
close /userfs/savedata.bin flags 1
[1;31mERROR: get_unique_ID: [0m[1mMethod/Function Failed, returning: ""
[0;31m   At: core/os/os.cpp:459.[0m
close /userfs/savedata.bin flags 2
elapsed 43 tts 4957
[SUTjoystick]: mouse emulation enabled
elapsed 75 tts 4882
```
and several other occurences. It seems to happen often while trying to handle stuff in the user filesystem.

**Comment by est31** [comment]
Also it shouldn't probably print the ASCII control characters.

**Comment by akien-mga** [comment]
> Also it shouldn't probably print the ASCII control characters.

Yeah that's a bit weird as IIRC those should only be printed on unix. Does it consider the javascript platform as unix, or does it detected my desktop's platform?

**Comment by est31** [comment]
asm.js emulates linux as its "host" AFAIK.

**Comment by bojidar-bg** [comment]
I can confirm on linux. Prints:
````
ERROR: get_unique_ID: Method/Function Failed, returning: ""
   At: core/os/os.cpp:459.
````

**Comment by bojidar-bg** [comment]
(bump)

A quick search through the code uncovers that `get_unique_ID` is implemented only on android and ios... which means that the "This will make the file unreadable to users, but will still not avoid them to share savefiles" point from [the encrypting save games tutorial](http://docs.godotengine.org/en/latest/tutorials/engine/encrypting_save_games.html) is invalid on those platforms

**Comment by akien-mga** [comment]
This issue is actually a duplicate of #196, but the latter was closed as "won't fix". I'm not happy with this resolution though, as a method named `OS.get_unique_ID()` that only works on mobile platforms is quite misleading.

At the very least the documentation should be written and state clearly where it works and where it doesn't (and it shouldn't be mentioned in the [Encrypting save games](http://docs.godotengine.org/en/latest/tutorials/engine/encrypting_save_games.html) tutorials if it works only on mobile where 98% of users won't even know how to browse their filesystem :)

The best would be to find a way to implement this on desktop platforms too of course :)

**Comment by kingarthurpt** [comment]
I don't know if [this](http://unix.stackexchange.com/questions/144812/generate-consistent-machine-unique-id#144821) helps or if it is some kind of overkill, but it is just me trying to help.

**Comment by akien-mga** [comment]
Yeah that's a solution, though it's hard to maintain something on all platforms that would rely on parsing shell commands, as the command output can change in later versions, etc.

A better solution might be to use existing C++ or C libraries for that: boost-uuid (we don't want to link boost, so bad idea), [ossp-uuid](http://stackoverflow.com/a/24366029) (cross-platform?), [libuuid](http://stackoverflow.com/a/24366029) (util-linux), [UuidCreate](http://msdn.microsoft.com/en-us/library/windows/desktop/aa379205%28v=vs.85%29.aspx) (Windows)

**Comment by Zylann** [comment]
Generating unique IDs is used in more places than just savegame encryption, so I believe we can have this feature on any OS.
This library could help: https://github.com/graeme-hill/crossguid
Most of the time it's as easy as calling an OS-specific function.

**Comment by reduz** [comment]
As mentioned before, I don't think this makes much sense on PC, we could
try to find some way to generate an ID from stuff like hardware serial
numbers, but if the user changes hardware and the game depends on this ID
(for example, as salt to encrypt a savegame, so it can't be shared with
other phones which is one of the most common use cases), that would be a
disaster.

**Comment by est31** [comment]
Microsoft's OEM license is not affected if you change parts of the computer, except the mainboard. Maybe only take mainboard serial numbers?

**Comment by akien-mga** [comment]
Well we don't have to reinvent the wheel, there are already a lot of people who worked on UUIDs and even wrote standards: https://en.wikipedia.org/wiki/Universally_unique_identifier#RFC_4122_Variant

> we could try to find some way to generate an ID from stuff like hardware serial
numbers, but if the user changes hardware and the game depends on this ID
(for example, as salt to encrypt a savegame, so it can't be shared with
other phones which is one of the most common use cases), that would be a
disaster.

I wouldn't say a "disaster". An UUID would typically be used to check that the encrypted savegame was made on the same machine, and if the UUID changes after a hardware change, it would just make the save broken for this user. So if you change your hardware on desktop, it won't allow you to share your saved game with other machines, it will just prevent you from using it further.

Moreover, crackers will always find a way to crack stuff. This is more about providing an easy way to get a "unique for 99.99% of users" ID, instead of providing an empty string...

**Comment by akien-mga** [comment]
Then of course if we implement such a UUID we should not advertise it as a fully secure solution. But there are no fully secure solutions anyway, and I'm pretty sure the UUIDs we serve on mobile platforms can be broken too.

**Comment by punto-** [comment]
Why not just generate a random number and put it on a global place, then
use that number subsequently? It works as a unique id, and lets the user
take control of their privacy if they want. Also I think that's what we do
on certain versions of iOS.

**Comment by J08nY** [comment]
Well, what is the goal of this function? What is it supposed to be bound to? The hardware? What hardware? What if it changes? There is no one simple solution. We either do something like what @punto- says and sacrifice real security or generate it from some hardware ids/MAC and risk the user changing some components and breaking stuff. 
It really matters on what the purpose is. Maybe it will be best to provide both. OS.get_id() for an id that is generated on the first run of Godot and stored somewhere and OS.get_hardware_id() that is generated from hardware. That way the choice is on the developer and his/her intent.

**Comment by Zylann** [comment]
Hang on, so far this function is undocumented and I need to clarify something:
Is OS.get_unique_id() supposed to return the same ID on every call for the same machine? Or does it generates a new one?

Also, as I said, a unique IDs (or should I say GUID? Is that the same thing?) can be generated in case your game runs in a distributed environment, if you want to identify something (a player? a user-generated content? A game session? anything). If the reason it's only present on iOS and Android is because of savegames and unmodifiable hardware, it misses other usages IMO.

**Comment by est31** [comment]
Hardware modifications of smartphones are possible, you just need to have a professional do it. But yes, they are very very uncommon. Its even more uncommon to modify them in a way the ID changes. What is farly more common is that you want to migrate devices. E.g. you have an old phone, and want to put your savegame on a new phone. What now? Then this unique id feature fails as well.

Also, how many people change their motherboards? Not many. If you change your motherboard, and you have an OEM license, you already have to call microsoft, and explain them that you changed your hardware. So from that its only a small step to emailing the developers of the game as well. Its no service the game developers have to offer, they simply can chose to not use the function!

This feature is not about pleasing the player: its precisely the opposite. Its there to force things upon the players, and stand against the player's will. Well, godot's users are not the players but the game creators. If they see that godot has no DRM features, then they will think godot is shit. Its like if godot was GPL licensed: The game creators wouldn't applaud "oh great more freedom for the users", they would simply not use godot. So if the game creators want something that may or may not annoy some players, then they should get it. Its their decision after all if they want to use that function or not.

Maybe the docs can include a hint that if the motherboard is changed, the ID changes as well.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by gau-veldt** [comment]
Can't you use RFC-4122 or one of its version variants?

**Comment by gau-veldt** [comment]
Here's my hacktastic workaround (and it's not RFC-4122 complaint).  It can probably be made better but it should work across platforms and generate reasonably non-collided IDs.  If you need internet-scoped uniqueness then the random numbers should be switched for a 48-bit hash of a hardware (ie: unspoofed) MAC address.  This still isn't a total guarantee but works for most use cases.  I don't need internet-wide uniqueness in my case (it's identifying serverside objects) hence the pseudo-random generation for the 48 MAC address bits.

```
func julian(date):
	var jd=0
	for mo in range(date['month']-1):
		if mo in [0,2,4,6,7,9,11]:
			jd+=31
		if mo in [3,5,8,10]:
			jd+=30
		if mo in [1]:
			jd+=29
	jd+=date['day']
	return jd

var guid_state={
	'serial':0,
	'mac':[int(65535.0*randf()),int(65535.0*randf()),int(65535.0*randf())]
}
func generate_guid():
	#
	#  GUID generation for game objects
	#  NB: This is not an RFC-compliant guid generator!
	#
	var uid="%X%X-%X-F" % guid_state['mac']
	var now=OS.get_datetime()
	var ms=OS.get_ticks_msec()
	var yr=now['year']-1582
	var jd=julian(now)
	uid+="%03X-%04X-" % [yr,0x8000+(jd*24)+now['hour']]
	var msm=now['minute']
	msm=(msm*60)+now['second']
	msm=(msm*1000)+ms
	uid+="%06X" % msm
	uid+="%06X" % guid_state['serial']
	guid_state['serial']=(guid_state['serial']+1)%0x1000000
	return uid

```

**Comment by Marqin** [comment]
On Windows you can get motherboard UUID easly from API (and changing your mobo would onvalidate your Windoes license - bigger problem than game). On OS X you can ge serial number of that Mac device. But dunno what for Linux.

**Comment by gau-veldt** [comment]
@Marqin I believe a mainboard change only invalidates an OEM Windows license.  I wonder if the mobo UUID would be accessible via ACPI layer in linux?

**Comment by Marqin** [comment]
[This](http://git.savannah.gnu.org/cgit/dmidecode.git/tree/) app has ability to get motherboard Serial Number. May be helpful.

**Comment by punto-** [comment]
Just use a random number, and store it somewhere in user:// or the engine
configuration, use it on subsequent runs. It'll be portable, and nobody
actually needs a fingerprint of the hardware for this. If that is actually
needed, we'll look into it at the time.

**Comment by est31** [comment]
I doubt its accessible to any non-root app.

**Comment by supaiku-o** [comment]
Just my 2 cents: systemd (which most Linux distributions use nowadays) generates a unique 128-bit machine id (/etc/machine-id) during installation.

    The machine ID does not change based on user configuration or when
    hardware is replaced.

http://man7.org/linux/man-pages/man5/machine-id.5.html

Sounds like the right thing to me?

**Comment by est31** [comment]
Would be fun to have godot to depend on systemd xD

**Comment by gau-veldt** [comment]
@est31 the other problem with platform-specific alternatives is the id's may then clash with those from Godot's other platform.  There may then be a vector to attack salted savegames to make them shareable across platforms.  Something the DLC monetizers definitely don't want happening.
