### ISSUE TITLE
Modifying a built-in script doesn't mark the scene as modified

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#36281]
**Godot version:**
3.2

**Issue description:**
When you modify a built-in script, the script nor scene containing it isn't marked as modified. This potentially leads to accidentally unsaved changes on quit.
![EbT7Y98UnP](https://user-images.githubusercontent.com/2223172/74612411-810caf80-5105-11ea-89b2-a4cc896526fd.gif)

**Steps to reproduce:**
1. Create a scene
2. Add a built-in script
3. Save
4. Type something in the script

EDIT:
This also affects Shaders.

**Comment by Serenitor** [comment]
perhaps that is also the reason why built-in scripts are not being updated when you edit them during test play? or would that be another issue?

**Comment by KoBeWi** [comment]
Resolved by #67503
