### ISSUE TITLE
C# godot: Show compiler warnings 

### ISSUE THREAD

**Issue by TZubiri** [godotengine/godot#36292]
**Godot version:** 3.2 mono

**OS/device including version:** Ubuntu 18.04

**Issue description:**  When there are no errors, warning are not displayed anywhere, when there are errors, warnings might be displayed. For example, if one places an illegal line at the start of a file, only that error will appear, if one places an illegal line in the middle of a file, all warnings in lines above the illegal line will appear.

**Minimal reproduction project:** :
**Steps to reproduce:** Write the following lines in the middle of any working file:

```
public int Num(){ int unused; return 4;} 
intt illegal;
```

This should issue a warning for an unused variable, and an error for an unknown intt type.

If you switch the order into:
```
intt illegal;
public int Num(){ int unused; return 4;} 
```
Only the error will appear.

If you remove the illegal line

```
public int Num(){ int unused; return 4;} 
```
No warnings or errors will appear.

The solution is to always display warnings.

**Comment by Anutrix** [comment]
Please give us the Godot version and it's commit hash too if you compiled it yourself.

**Comment by akien-mga** [comment]
> Please give us the Godot version (and it's commit hash too if you compiled it yourself).

It's already included, just with a typo. What's mean is likely 3.2-stable.

**Comment by Anutrix** [comment]
> 
> 
> > Please give us the Godot version (and it's commit hash too if you compiled it yourself).
> 
> It's already included, just with a typo. What's meant is likely 3.2-stable.

My bad. I thought that was mono version or something.

**Comment by Tobi-Mob** [comment]
Godot 3.3.3: Looks good to me.
If the build outputs a warning, it seems like Godot also outputs a warning.


![grafik](https://user-images.githubusercontent.com/69400800/132905166-022d0eba-5e4f-42fe-96e6-be88d7c025b3.png)

> Running: "/usr/bin/dotnet" msbuild "/home/tobi/projects/Godot/PongC#/Pong with C#.sln" /restore /t:Build "/p:Configuration=Debug" /v:normal "/l:GodotTools.BuildLogger.GodotBuildLogger,/home/tobi/apps/Godot_v3.3.3/GodotSharp/Tools/GodotTools.BuildLogger.dll;/home/tobi/.local/share/godot/mono/build_logs/c96ffabe6e2cbe37591058296f39d402_Debug" /p:GodotTargetPlatform=x11
Microsoft (R)-Build-Engine, Version 16.11.0+0538acc04 für .NET

**Comment by akien-mga** [comment]
Thanks, closing as fixed.
