### ISSUE TITLE
Problems with form size when is in scripting mode and press Audio section under

### ISSUE THREAD

**Issue by Emin981** [godotengine/godot#36304]
**Godot version:3.2 stable**

**OS/device including version: Windows 10**

**Issue description:Problems with form size when is in scripting mode and press Audio section under**

**Steps to reproduce:Go to scripting mode and press audio section down near animation and debugger**
![issues](https://user-images.githubusercontent.com/58749001/74664421-f88e1d80-519d-11ea-8655-5cb761c6770a.png)
![issues2](https://user-images.githubusercontent.com/58749001/74664424-f9bf4a80-519d-11ea-9e63-27816512620a.png)

**Comment by Calinou** [comment]
Duplicate of #26835.
