### ISSUE TITLE
Godot 4.0 errors.

### ISSUE THREAD

**Issue by quantmint** [godotengine/godot#36308]
**Godot version:**
v4.0.dev.custom_build.c7faf2e16
**OS/device including version:**
arch linux, intel i7 4500u
**Issue description:**
While opening godot in the terminal a lot of issues shows up.

`Vulkan physical device creation success o_O
ERROR: 1 shaders of type GiprobeDebugShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type GiprobeShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: Some texture bindings were not properly freed (leaked canvasitems?
   at: ~RasterizerCanvasRD (servers/visual/rasterizer_rd/rasterizer_canvas_rd.cpp:2525)
ERROR: 1 shaders of type RoughnessLimiterShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type SsaoBlurShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type SsaoShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type SsaoMinifyShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type BokehDofShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type CopyShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type LuminanceReduceShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type TonemapShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type SkyShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type CubemapRoughnessShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
ERROR: 1 shaders of type GiprobeSdfShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:490)
WARNING: 2 RIDs of type 'StorageBuffer' were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:6879)
WARNING: 4 RIDs of type 'UniformBuffer' were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:6879)
WARNING: 2 RIDs of type 'Framebuffer' were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:6879)
WARNING: 2 RIDs of type 'Sampler' were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:6879)
WARNING: 2 RIDs of type 'Texture' were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:7022)
ERROR: Condition "object_slots[slot].object != p_object" is true.
   at: remove_instance (core/object.cpp:2084)
ERROR: Condition "!_p" is true.
   at: _unref (core/dictionary.cpp:185)
double free or corruption (!prev)
uniform total: 0
uniform total: 0
uniform total: 0
compilation success
 
uniform total: 0
Aborted (core dumped)
[quantmint@archlinux ~]$ ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
uniform total: 36
ERROR: In Object of type 'EditorNetworkProfiler': Attempt to connect nonexistent signal 'break_request' to method 'ScriptEditorDebugger._profiler_seeked'.
   at: connect (core/object.cpp:1452)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
ERROR: Cannot get class 'TextFile'.
   at: get_parent_class (core/class_db.cpp:356)
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
format: 1 size 64, 64 mipmaps: 0`
**Steps to reproduce:**
Create a new project.

**Comment by Calinou** [comment]
Duplicate of #35611 and #36297.
