### ISSUE TITLE
Scene tree dock: Can't drag node to last position if last item is a lower-level nested child node

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#36300]
**Godot version:**
3.2-stable

**OS/device including version:**
Any

**Issue description:**
In the scene tree, when the last item is the child of a parent node, it's not possible to drag another node as a sibling to that parent that would come in the last position. See:
![Screenshot_20200217_143145](https://user-images.githubusercontent.com/4701338/74658396-7cdaa380-5192-11ea-8555-77e99dd8e2a3.png)

When releasing the cursor, the "Parent2" node would become a sibling of "Child2", which is a valid use case, but it should be possible by dragging further down to have it come after "Parent3":
![Screenshot_20200217_143516](https://user-images.githubusercontent.com/4701338/74658488-ba3f3100-5192-11ea-8672-c55b14ea8d63.png)

This can be achieved currently by dragging "Parent3" onto "Root", which will make it the last child of that new parent.

If the last item in the scene tree is not a lower-level child, it is possible to achieve the intended result by drag and drop (notice the longer underline showing what the parent level will be):
![Screenshot_20200217_143603](https://user-images.githubusercontent.com/4701338/74658609-f4103780-5192-11ea-9ebe-8fecf55a686c.png)

**Steps to reproduce:**
- See MRP, try to drag "Parent2" to be the last child of "Root"

**Minimal reproduction project:**
[scene_tree_drag.zip](https://github.com/godotengine/godot/files/4214027/scene_tree_drag.zip)

**Comment by KoBeWi** [comment]
Isn't it duplicate of #34033?

**Comment by akien-mga** [comment]
Indeed :)
