### ISSUE TITLE
Vulkan: changing filter mode doesn't work on TileMaps

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#36328]
**Godot version:**
Godot 4.0 dev

**OS/device including version:**
Windows 10

**Issue description:**
Filtering options are now on each CanvasItem node, but it seems changing them has no effect on TileMap nodes:
![oxPKRj5](https://user-images.githubusercontent.com/19392104/74749529-92bb9780-526a-11ea-9689-77974f8931c8.png)
![4VMdjfa](https://user-images.githubusercontent.com/19392104/74749537-951df180-526a-11ea-91d9-168c9a8b37fa.png)

**Steps to reproduce:**
Create a TileMap, set its filter mode to Nearest and add one or more tiles.

**Comment by abueide** [comment]
Will this be fixed for the alpha?

**Comment by Calinou** [comment]
There's already an open pull request that should fix this: https://github.com/godotengine/godot/pull/36374
