### ISSUE TITLE
Missing header guard in platform/android/api/api.h

### ISSUE THREAD

**Issue by IronicallySerious** [godotengine/godot#36324]
**Godot version:**
4.0 master

**Issue description:**
Missing header guard in android/api/api.h. Detected via [LGTM](https://lgtm.com/projects/g/godotengine/godot/snapshot/be834fecef2e4d398cb9570d23e8f3b9f5d61f39/files/platform/android/api/api.h?sort=name&dir=ASC&mode=heatmap#x239b4089bba58f53:1) on the main README file. 
File: https://github.com/godotengine/godot/blob/master/platform/android/api/api.h

**Comment by akien-mga** [comment]
Feel free to make a PR directly for such defects :)

**Comment by IronicallySerious** [comment]
Alright, I was going to send a PR after this anyway. Thanks for the heads up

**Comment by Anutrix** [comment]
Isn't this fixed by https://github.com/godotengine/godot/pull/37219?

**Comment by akien-mga** [comment]
Yes.
