### ISSUE TITLE
Dynamic backend selection on Windows

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#3632]
From https://github.com/godotengine/godot/blob/c6971308e76a1fdf8d4f72e43f8515a0754b0e14/platform/windows/os_windows.cpp#L941 it looks like the choice of renderer is hardcoded and chosen at engine compile time. So there are 4 renderers:

 - OPENGL_ENABLED
 - GLES2_ENABLED
 - LEGACYGL_ENABLED
 - DirectX9

It would be nice to be able to select renderer dynamically at run-time or from command line. For example on Windows OpenGL support is historically poor.

**Comment by bojidar-bg** [comment]
@techtonik ~ Three points:
1. DirectX is not (and would not be AFAIK) supported in Godot
2. 3D is relatively Waiting for Vulkan™
3. OpenGl and GLES are the only working renderers (again, AFAIK)

**Comment by techtonik** [comment]
https://www.reddit.com/r/linux_gaming/comments/392xsx/godot_engine_waiting_for_vulkan_those_of_us_who/ - the link is offline, but https://www.khronos.org/vulkan/ is wow. The rest of the day is wasted.

Anyway, even if it is only two backends, I would like to choose between OpenGL and OpenGL ES at run-time.

**Comment by akien-mga** [comment]
OpenGL is for desktop, OpenGL ES is for embedded system. There's nothing to choose at runtime, it depends on your platform.

**Comment by techtonik** [comment]
@akien-mga I want to use ANGLE, which is OpenGL ES for desktop, which Chrome uses on Windows.

**Comment by akien-mga** [comment]
Then you'd have to implement yourself an alternate backend and then select it at runtime.

**Comment by techtonik** [comment]
@akien-mga ANGLE already implements OpenGL ES calls. So how to select it at runtime?
