### ISSUE TITLE
Color picker: can't select hue without selecting the shade first

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3633]
When selecting a color, it's quite common to first go to the correct hue and then select the shading.
In godot this is impossible to do at the moment as the vertical hue bar is unresponsive until you select the shading. 

When saturation is 0 (max left in the square shading area) the hue vertical bar becomes unresponsive again. Actually this might be the cause of the problem as when choosing a new color, saturation starts at 0.

**Comment by reduz** [comment]
i think this was fixed recently, are you using the latest version?

**Comment by nunodonato** [comment]
my version is 2 days old...

**Comment by akien-mga** [comment]
> i think this was fixed recently, are you using the latest version?

A related issue was fixed recently (#3492), but the one described here is still valid indeed.

**Comment by nunodonato** [comment]
I stand corrected, the problem has been fixed. I just tested with the current git version. Closing the issue.
