### ISSUE TITLE
No way to interrupt PacketPeerUDP.wait()

### ISSUE THREAD

**Issue by vganin** [godotengine/godot#36335]
**Godot version:** v3.2.stable.official

**OS/device including version:** macOS 10.15.3

**Issue description:**
I'm starting a new thread with `PacketPeerUDP` listening to specific port with `wait`. Unfortunately there is no way to tell it to stop because I want it to listen only in the right
 time. I tried
- Calling `close`
- Calling `listen` with other port

**Steps to reproduce:**
```gdscript
var thread = Thread.new()
var socket = PacketPeerUDP.new()

func _ready():
    thread.start(self, "_do_on_bg")
    yield(get_tree().create_timer(1), "timeout") # Let the thread settle
    socket.close()
    socket.listen(0)
    thread.wait_to_finish() # Deadlocked forever

func _do_on_bg(_null):
    if socket.listen(789) != OK:
        print("Failed")
        return
    
    while socket.wait() == OK:
        print("Received connection")
```

**Minimal reproduction project:**
[wait-repro.zip](https://github.com/godotengine/godot/files/4222143/wait-repro.zip)

**Comment by vganin** [comment]
I found a workaround. One can put a message (a death pill) to the socket
```gdscript
socket.set_dest_address("127.0.0.1", 789)
socket.put_packet("Time to stop".to_ascii())
...
while socket.wait() == OK:
    var data = socket.get_packet().get_string_from_ascii()
    if data == "Time to stop":
        return
```

**Comment by jonbonazza** [comment]
The poison pill approach is likely the best we can do here. @Calinou you can probably close this

**Comment by Xrayez** [comment]
Marginally related but I think the same technique could be applied for killing a thread, worth documenting that too (I've never done this though). https://godotengine.org/qa/76386/is-it-possible-to-kill-a-thread
