### ISSUE TITLE
Fix: Replace CRLF to LF from revision.template

### ISSUE THREAD

**Issue by MateoMiccino** [godotengine/godot#36337]
**Godot version:** 4.0 master

**OS/device including version:** Ubuntu 16.04 (i tried in two different machines with Ubuntu 16.04)

**Issue description:** ./thirdparty/glslang/glslang/Include/revision.template has CRLF for new lines and makes git modify it automatically, generating unwanted changes

![image](https://user-images.githubusercontent.com/12563266/74787818-e0e29200-528e-11ea-8c2d-0a17373bdac6.png)

I search the entire project with a script (searching for 0x0d0a), and no other file has CLRF.

**Steps to reproduce:** Download the repository on Ubuntu 16.04 with Git 2.7.4 without setting "git config core.autocrlf input" and simple type "git diff"

**Comment by MateoMiccino** [comment]
Merged

**Comment by akien-mga** [comment]
A tip for future PRs :) https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
