### ISSUE TITLE
Orthogonal mode in 3D viewport is not sustained

### ISSUE THREAD

**Issue by funkeh** [godotengine/godot#36339]
**Godot version:** 3.2.stable

**OS/device including version:** Windows 10 v1909

**Issue description:**
When adding a new scene, the 3D viewport is in Perspective mode, despite last scene being set to Orthogonal and the option being "selected".

![ezgif-2-f714517f21c7](https://user-images.githubusercontent.com/1741893/74788811-e5e32800-5306-11ea-9d01-b6a3ca28224d.gif)

**Steps to reproduce:**
1. Set viewport mode to Orthogonal.
2. Add a new scene.
3. Observe that viewport is in Perspective mode but Orthogonal mode is selected in viewport menu.

**Minimal reproduction project:**
[orthogonal.zip](https://github.com/godotengine/godot/files/4222420/orthogonal.zip)

**Comment by Janglee123** [comment]
I can also reproduce this in 3.1. I will make a pr.
