### ISSUE TITLE
Clicking background of editor popup to close does not stop input event propagation

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#36341]
**Godot version:**
Master

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
Clicking the background should stop that input from continuing on to other elements. Instead of Spatial immediately being selected, the click should only close the popup

![problem](https://user-images.githubusercontent.com/14253836/74790110-48431680-527c-11ea-9668-3e93d682d004.gif)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Uh, I'm pretty sure it's a duplicate, but can't find it now.

**Comment by theoway** [comment]
Is it an issue regarding editor dialog or gui popup?

**Comment by KoBeWi** [comment]
I think this applies to all popups, even though it's about editor specifically (the other one did too).

**Comment by theoway** [comment]
This issue is only in Popups. Popup menus, panels etc are working fine. I'll check into it.

**Comment by theoway** [comment]
@KoBeWi After digging into the code, I found out that only editor dialogs have this bug. And editor dialogs uses gui dialogs. Maybe the bug is in gui dialog class. I'm new to Godot codebase, that's why took this long to reply. If you could verify this, I'll start to work on the bug.

**Comment by KoBeWi** [comment]
Yep, GUI dialogs have this problem (it's easy to test), but in editor it's just more unexpected, because the background is dimmed.
