### ISSUE TITLE
collision in tileset resource not in scene

### ISSUE THREAD

**Issue by sturm30** [godotengine/godot#36344]
**Godot version:**
3.2
**OS/device including version:**
Linux 64bit
**Issue description:**
collision shape on tileset are not visible on tilemap in scene
**Steps to reproduce:**
(I followed the official tutorialat: http://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html#tileset-scene)
Debug-> show Collision
create a scene with Node2D root node
create a Sprite2D, 
enable region,
put the texture
create a StaticBody2D as Sprite2D child
create a CollisionShape2D as StaticBody2D child
define a shate for the CollisionShape2D (any)
save the scene  (tileset.tscn)
convert the scene to tileset  (tileset.tres)
create a scene with Node2D root node
create a TileMap
assign its tileset as tileset.tres up above
put the unique tile on the scene

As far as I tried, tiles has no collision.
I tried also to edit the tileset from the inspector, using the Collision tab. I got the same result: no collision visible on scene.
I know it is similar to https://github.com/godotengine/godot/issues/9409 
**Minimal reproduction project:**
[CollisionOnTilemap.zip](https://github.com/godotengine/godot/files/4223147/CollisionOnTilemap.zip)

**Comment by KoBeWi** [comment]
![image](https://user-images.githubusercontent.com/2223172/74838268-99f2ac00-5323-11ea-9ae1-7041eb726424.png)
I get the shape correctly.

**Comment by sturm30** [comment]
@KoBeWi what is the Godot version and OS you are running on?

**Comment by KoBeWi** [comment]
3.2, Windows 10
The shape just doesn't show or it doesn't collide too?

**Comment by sturm30** [comment]
@KoBeWi it doesn't show at all.

**Comment by KoBeWi** [comment]
Do you run the scene with TileMap with "Visible Collision Shapes"?

**Comment by sturm30** [comment]
Yes I do. The running scene actually has the collision shape. What makes me wonder now is why I can not see the tile's collision shapes while editing the scene.

**Comment by KoBeWi** [comment]
Well, TileMap doesn't show collision in the editor. It would make it unreadable. If you think this should be an option, you could create a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by sturm30** [comment]
Thank you @KoBeWi

**Comment by akien-mga** [comment]
For the reference, this is a duplicate of #19858.
