### ISSUE TITLE
Sync scene in mobile device do not work

### ISSUE THREAD

**Issue by Rannn1288210** [godotengine/godot#36343]
**Godot version:**
3.2 stable standard(GDscript)

**OS/device including version:**
mobile device in android version 9

**Issue description:**
Export the new and simple project to mobile device with one click deploy.
![image](https://user-images.githubusercontent.com/61216852/74796636-4b421380-531d-11ea-9cd1-c2d82f2014c1.png)
All the necessary debug check-boxes has been checked. 
With the export template(standard) that reinstalled from auto download within the Godot editor(freeze in 99%) to manually download from Godot website.
Using android studio to download android api level 29 and 28 (version 10 and 9).
![image](https://user-images.githubusercontent.com/61216852/74796933-15515f00-531e-11ea-8a67-9fe8b3e17128.png)
And also tried two different ojdk file.
![image](https://user-images.githubusercontent.com/61216852/74798434-dae9c100-5321-11ea-9064-dc9ce15879e4.png)

with editor setting on android:
![image](https://user-images.githubusercontent.com/61216852/74797229-c22bdc00-531e-11ea-93cb-f2169ef5a700.png)

when I click one click deploy, receive this warning:
![image](https://user-images.githubusercontent.com/61216852/74797342-028b5a00-531f-11ea-9671-0b888f65c822.png)
This is the build information

> Adding permission android.permission.INTERNET
ADDING: AndroidManifest.xml
ADDING: classes.dex
ADDING: lib/arm64-v8a/libc++_shared.so
ADDING: lib/arm64-v8a/libgodot_android.so
ADDING: lib/armeabi-v7a/libc++_shared.so
ADDING: lib/armeabi-v7a/libgodot_android.so
ADDING: res/drawable-hdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-hdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-mdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-v21/notification_action_background.xml
ADDING: res/drawable-xhdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-xxhdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable/notification_bg.xml
ADDING: res/drawable/notification_bg_low.xml
ADDING: res/drawable/notification_icon_background.xml
ADDING: res/drawable/notification_tile_bg.xml
ADDING: res/layout-v16/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_action.xml
ADDING: res/layout-v21/notification_action_tombstone.xml
ADDING: res/layout-v21/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_template_icon_group.xml
ADDING: res/layout/downloading_expansion.xml
ADDING: res/layout/notification_action.xml
ADDING: res/layout/notification_action_tombstone.xml
ADDING: res/layout/notification_template_icon_group.xml
ADDING: res/layout/notification_template_part_chronometer.xml
ADDING: res/layout/notification_template_part_time.xml
ADDING: res/layout/status_bar_ongoing_event_progress_bar.xml
ADDING: res/mipmap-anydpi-v26/icon.xml
ADDING: res/mipmap-hdpi-v4/icon.png
ADDING: res/mipmap-hdpi-v4/icon_background.png
ADDING: res/mipmap-hdpi-v4/icon_foreground.png
ADDING: res/mipmap-mdpi-v4/icon.png
ADDING: res/mipmap-mdpi-v4/icon_background.png
ADDING: res/mipmap-mdpi-v4/icon_foreground.png
ADDING: res/mipmap-xhdpi-v4/icon.png
ADDING: res/mipmap-xhdpi-v4/icon_background.png
ADDING: res/mipmap-xhdpi-v4/icon_foreground.png
ADDING: res/mipmap-xxhdpi-v4/icon.png
ADDING: res/mipmap-xxhdpi-v4/icon_background.png
ADDING: res/mipmap-xxhdpi-v4/icon_foreground.png
ADDING: res/mipmap-xxxhdpi-v4/icon.png
ADDING: res/mipmap-xxxhdpi-v4/icon_background.png
ADDING: res/mipmap-xxxhdpi-v4/icon_foreground.png
ADDING: res/mipmap/icon.png
ADDING: res/mipmap/icon_background.png
ADDING: res/mipmap/icon_foreground.png
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: no space left
ADDING: resources.arsc
0 param: --remote-fs
1 param: localhost:6010
2 param: --remote-debug
3 param: localhost:6007
4 param: --xr_mode_regular
5 param: --use_depth_32
6 param: --use_immersive

I have tried in different android phone with the same project. When I move the button around in the editor, the same button in the mobile screen do not change position at all.

**Steps to reproduce**
open a new project
add a node and child node(button)
one click deploy to android device with usb connection
move button within editor

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/4223041/New.Game.Project.zip)

**Comment by Rannn1288210** [comment]
Also I find in godot 3.2 stable have the same problem with#28821
but I don't know whether that is normal

**Comment by flexflak** [comment]
Hello, I have the exact same issue, did you solved it? Thank you

**Comment by hannojg** [comment]
I just used a fresh installation of Godot mono 3.4.3 and this just worked as expected for me 🤔 (I have to restart the app after making changes, but I guess that's expected, right?)

**Comment by Calinou** [comment]
Closing per hannojg's comment.
