### ISSUE TITLE
More keyboard shortcuts please. 

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#3635]
The keyboard shortcuts that the editor already has are great, but there are some obvious (to me) ones missing that would make production way faster. Primarily:

**Ctrl-N** - new scene
**Ctrl-Tab** and **Ctrl-Shift-Tab** - switch scene, next and previous
 

And a couple others that would make sense: 

**Ctrl-Shift-N** - new inherited scene
**Ctrl-Shift-A** - add scene file instance as a node

A haven't used the engine a lot yet, but as far as I can tell none of those combinations are used anywhere.

**Comment by reduz** [comment]
we´ll be reworking this in 2.1

**Comment by rgrams** [comment]
Cool. Is there any estimated release date for 2.1?

**Comment by reduz** [comment]
half this year

**Comment by rgrams** [comment]
OK, thanks!

**Comment by vjrossi** [comment]
Ctrl-Tab and Ctrl-Shift-Tab

Please..

Ctrl-F4 would be nice for us poor Windows users too but Ctrl-W will suffice. If only it remembered your previous tab...

**Comment by oliver-ruehl** [comment]
Zoom in = Ctrl +-
Focus on selected node = E or F

**Comment by djrm** [comment]
Now there are customizable shortcuts, new scene and new inherited scene can be asigned, switching tabs and instance child scene are missing.

**Comment by djrm** [comment]
Working on this
