### ISSUE TITLE
draw_arc ignores starting and end angles

### ISSUE THREAD

**Issue by deusalgor** [godotengine/godot#36356]
Godot v3.2.stable.official GLES3
Windows 10 x64

draw_arc function ignores starting and end angles and always draws full cirlcle.

Here is code for testing
![image](https://user-images.githubusercontent.com/32928519/74821322-15e0fa00-530c-11ea-98b3-af0bf2a5ed16.png)
Here is output
![image](https://user-images.githubusercontent.com/32928519/74821353-22655280-530c-11ea-9381-fa5020b3f273.png)

Example project
[draw_arc_bug.zip](https://github.com/godotengine/godot/files/4224745/draw_arc_bug.zip)

DxDiag
[DxDiag.txt](https://github.com/godotengine/godot/files/4224791/DxDiag.txt)

**Comment by Zireael07** [comment]
Are you 100% sure this takes degrees, and not radians?

**Comment by TheDuriel** [comment]
![image](https://user-images.githubusercontent.com/44248915/74835929-a3c5e080-531e-11ea-9e90-b8255ff04398.png)
takes radians, as expected.

**Comment by KoBeWi** [comment]
The documentation doesn't mention it though.

**Comment by TheDuriel** [comment]
"Angle" == Radians in all cases unless otherwise specified. (Everything that uses or produces degrees is clearly labelled as such, or has `d` as a suffix.) I don't think there's a global space to clarify this at. And putting it into _every single_ docstring that does this would be excessive.

**Comment by KoBeWi** [comment]
> "Angle" == Radians in all cases unless otherwise specified.

We could note somewhere at least that. I don't see any mention of that aside from the tutorial (very briefly).

> I don't think there's a global space to clarify this at.

CanvasItem description maybe.

**Comment by TheDuriel** [comment]
Except this also applies to Spatials.

**Comment by Zireael07** [comment]
Both CanvasItem and Spatial class descriptions, then?

**Comment by deusalgor** [comment]
Thanks a lot for answer.
It's clearly my bad to not trying radians.
Also there is mention about radians in this tutorial which I totally missed.
https://docs.godotengine.org/en/3.1/tutorials/2d/custom_drawing_in_2d.html
Sorry again.
