### ISSUE TITLE
Special char in folder using OS.get_system_dir()

### ISSUE THREAD

**Issue by Cosciad** [godotengine/godot#36352]
**Godot version:**
3.2

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
When we call the OS.get_system_dir function if the folder contains special char, they aren't displayed. For example, my download folder is called "téléchargements" and the OS.get_system_dir function return "/home/user/tlchargements"

**Steps to reproduce:**
Set your download folder to a folder with a special char

**Minimal reproduction project:**

**Comment by IronicallySerious** [comment]
This is likely a problem with either xdg-user-dirs or how xdg-user-dirs is used in https://github.com/godotengine/godot/blob/b5729a82e9925062f88b06023db679623b3a3808/platform/x11/os_x11.cpp#L2970

**Comment by MateoMiccino** [comment]
I fix it parsing de output command from utf8

I test it on Linux (Ubuntu 16.04), can someone test it from Windows and Mac?
https://github.com/MateoMiccino/godot/tree/os_getsystemdir

**Comment by namedtoaster** [comment]
I'd like to try. How can I test the change on my Mac? I edited the unix/os_unix.cpp file as you did in your fork. I'm not sure how to test it though

**Comment by Calinou** [comment]
@namedtoaster Follow the instructions in [Compiling for macOS](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_osx.html) :slightly_smiling_face: 

After building Godot, run the editor and create a new project. Add any node and attach the following script to it:

```gdscript
extends Node

func _ready():
    print(OS.get_system_dir(SYSTEM_DIR_DOWNLOADS)
```

Then save the scene and run it.

**Comment by namedtoaster** [comment]
How do you change the download (or any other) directory? All the system directories don't have any special characters on my machine. Renaming them does nothing either. I can't find any documentation on how to do this

**Comment by Calinou** [comment]
@namedtoaster You'll need to create a new user account to do this, I guess.

**Comment by namedtoaster** [comment]
@Calinou they don't seem to unfortunately

**Comment by Janglee123** [comment]
@namedtoaster Changing system language might help. but be aware that whole os will use new language.

**Comment by namedtoaster** [comment]
@Janglee123 I changed the system language to spanish but it still didn't do the trick. I'll keep searching for ways to test

**Comment by namtran166** [comment]
I can take a took at testing for MacOS. My Macbook language is in Spanish and I believe I can create user directory with non-ASCII characters

**Comment by NickSacoman** [comment]
@Calinou I attempted to test this for Windows. I reproduced using the steps you gave for Mac and pasted the same code within the script of the node I created however I'm getting an error that states the identifier "SYSTEM_DIR_DOWNLOADS" is not declared in the current scope. Is there something different I have to do to test on Windows?

**Comment by Calinou** [comment]
@NickSacoman It needs to be `OS.SYSTEM_DIR_DOWNLOADS`, not just `SYSTEM_DIR_DOWNLOADS`.

**Comment by namtran166** [comment]
It is working as expected on MacOS as I changed like what @kuruk-mm did in his commit 360b4ad64e527bf98b87623270cc796e76b16892.

**Comment by kuruk-mm** [comment]
> It is working as expected on MacOS as I changed like what @kuruk-mm did in his commit [360b4ad](https://github.com/godotengine/godot/commit/360b4ad64e527bf98b87623270cc796e76b16892).

Ok. So I will make a PR in two days (I'm traveling)
