### ISSUE TITLE
GDScript Module is deleting _marshalls Singleton

### ISSUE THREAD

**Issue by kuruk-mm** [godotengine/godot#36364]
**Godot version:** 4.0

**OS/device including version:** Ubuntu 16.04

**Issue description:**
_Marshalls singleton inherit from Reference, and when we instantiate it directly from memnew the Ref counter is not counting the first iteration.

This Singleton is added to GDScriptLanguage class as variant, and when this class is destroyed, GDScriptLanguage destroy _Marshalls too. And we try to destroy Marshall again closing the project ( unregister_core_types() ) executing memdelete(null).

This can make undefined behavior too if someone get the reference, and unreference, and other module try to use from the get_singleton().

**Steps to reproduce:** Open the project (just on project loader), and close. This will be a crash on "memdelete(_marshalls);" (because is relased from GDScriptLanguage)

**Propose:**
I don't know exactly why _Marshall is a Reference and not an Object, but I test it making a Ref<> in the Singleton and works fine.

I see in #35127 akians said this need core changes. So I will make a PR just for making correction to use it as Ref<> and if we need to change the _Marshall inherit to Object, just change this.

**Comment by MateoMiccino** [comment]
I test making _Marshalls an Object and works totally fine. I don't know why it's a reference.
