### ISSUE TITLE
AssetLib items do not show up as nodes in the "Create New Node" selection

### ISSUE THREAD

**Issue by Calamari** [godotengine/godot#36378]
**Godot version:** 3.1 & 3.2

**OS/device including version:** Ubuntu 18/Mint

**Issue description:**
This might be a dummy noob problem, but all the "how-to"-videos I saw suggest this should work:
After downloading & installing an (any) addon from the AssetLib, they never show up as node that I can add to a scene as they supposedly should be.

**Steps to reproduce:**
1. Download and install an addon form the AssetLib (e.g. "FSM (Finite State Machine)" by kubecz3k)
2. Click button "Add Node" (+) to scene
3. Type "finite" (or look on every node)
4. See that the addon is not there.

It is the same with all other assets I installed which say they should be selectable as node.

**Minimal reproduction project:**
_See steps to reproduce._

If I can add more information to help narrow the problem down, I am happy to give it.

**Comment by mrcdk** [comment]
Do you enable them in the `project settings/plugins` section?

**Comment by Calamari** [comment]
Well, nope :)
Didn't know that I had to. so I guess that was a noob question.

Somehow noone mentioned that part and I didn't read it somewhere. Maybe an option would be nice to directly activate it when it got installed so people like me can figure that part out on their own :)

**Comment by Calinou** [comment]
Enabling plugins by default is implemented by #35234, but it hasn't been merged yet.

**Comment by Calamari** [comment]
Ah nice. I am waiting for the next release then. And until then, I know what to do.

Thanks a lot.
I definitely like Godot :)
