### ISSUE TITLE
TileMap doesn't show most Sprite parameters

### ISSUE THREAD

**Issue by kirilledelman** [godotengine/godot#3637]
It would be super awesome if when converting a scene to a tileset, Sprites retained all properties.
Things like modulate color, opacity, transforms, offset etc. 

The way TileMap works now limits its usefulness quite severely. It's easier to design levels just using the grid and scene instances. I think many users would agree with me that adding the ability to add scenes as tiles ( with scripts attached ) would help make things like doors, animated tiles etc much easier.

**Comment by reduz** [comment]
more stuff could be eventually added, but in truth the idea is that you
should combine the tilemap with instanced objects, not use one or the other.

Tilemap is designed to draw large amount of quads quickly, so adding more
flexibility would beat the purpose. What is the problem of combining both?

**Comment by kirilledelman** [comment]
Ok. That explanation makes sense.
I guess adding some more options for modulate / opacity / offset would be nice then.
Thanks!

**Comment by eska014** [comment]
Properties requested in other issues:
 - #4321: Vframes, Hframes, Frame
 - #5982: Rotation and flipping (Flip H & V)

**Comment by Skaruts** [comment]
> more stuff could be eventually added, but in truth the idea is that you
> should combine the tilemap with instanced objects, not use one or the other.
> 
> Tilemap is designed to draw large amount of quads quickly, so adding more
> flexibility would beat the purpose. What is the problem of combining both?

What about a classic platformer where a lot of the world is made of one-way platforms (like the old Sonics), or moving platforms and conveyor belts (like the Shinobi 2's factory, I think)? A few of the tiles could be set through the tilemap but the rest would be left inconveniently scattered in scenes.

I don't know how the engine handles the tiles, but I'm guessing there could be a way to implement scripted tiles. Even if in a separate type of tilemap.

**Comment by hubbyist** [comment]
What about a proxy tile which will be a placeholder quad and be replaced with an instance of the scripted scene when it entered the scene.

**Comment by KoBeWi** [comment]
3.0 added support for additional tile parameters from Sprites.
![image](https://user-images.githubusercontent.com/2223172/59644345-dbb3cd00-916c-11e9-88fc-c67e98053197.png)
Modulate (+opacity), offset and region are supported, so I guess this can be closed.

**Comment by Skaruts** [comment]
Personally I think the Tilemap (or another version of it) ought to allow modulating cells individually. It would be useful for a lot of things, for example, a day/night cycle where the tint of the tiles changes (though I guess a CanvasModulate might work too), or for a text based roguelike where each cell can have its own color.

But I guess this is slightly off-topic here.

**Comment by KoBeWi** [comment]
But it already allows that. You can modulate individual tiles, as well as whole Tilemap.

**Comment by Zireael07** [comment]
If you modulate e.g. a ground tile, all ground tiles change. I think he wants to modulate individual cells of a type. That, I believe, is not possible, since the Tilemap works by essentially batching the cells of a single type?

**Comment by KoBeWi** [comment]
Ah, yeah. That would be impossible. But it's a thing for a new issue then.

As a workaround, you can also add another Tilemap on the top, set draw mode to mix and use fully saturated tiles to emulate individual modulation of underlying tiles.

**Comment by Skaruts** [comment]
@Zireael07 yea that's the problem exactly. It modulates the tiles, not the cells.

@KoBeWi I guess that could work. Though it's a bit more cumbersome to deal with.

Although for my purpose of a classic roguelike (text based) I still had to colorize the text and the background separately, so I needed to use sprites and a simple shader. (Seemed to perform better than sprites with transparent background and Poligon2Ds behind them, iirc.) I couldn't figure out a way to do it with TileMaps.
