### ISSUE TITLE
Can not represent 0xfffff... as 64 bit integer

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#36387]
**Godot version:**
3.2
**OS/device including version:**
Windows
**Issue description:**
![2020-02-20_224232](https://user-images.githubusercontent.com/34160378/74951438-884bfa00-5432-11ea-868d-f8ab36a822bb.png)

The project still running, but keep appear this error in debug
![2020-02-20_224700](https://user-images.githubusercontent.com/34160378/74952494-ea0c6400-5432-11ea-98fb-71a460489e9d.png)

**Comment by Calinou** [comment]
Can you upload a minimal reproduction project in which this error occurs?

**Comment by qarmin** [comment]
Hex can only be only represented as unsigned int, but in code hex_to_int64 return int64 which can overflow when putting to it value bigger that 2^63

https://github.com/godotengine/godot/blob/1eb424ec9549bdd086dfb54c847d107519be73d9/core/ustring.h#L248-L251

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by wilmer-daza** [comment]
Hi guys !

I'm having the exact same problem when using Ncryp class from: https://github.com/johngirvin/godot-ncrypt

The class producing the problem is the script NCrypt.gd: https://github.com/johngirvin/godot-ncrypt/blob/master/project/NCrypt/NCrypt.gd

Is still present in Godot 3.3.2.stable

**Comment by Calinou** [comment]
I can reproduce this on `master` with the following script:

```gdscript
extends Node
func _ready():
	# Any number larger than `0x8fff_ffff_ffff_ffff` seems to trigger this.
    print(str(0xffff_ffff_ffff_ffff))
```

What would be the correct way to solve this? GDScript does not have an unsigned 64-bit integer type (or unsigned integer types in the first place).

**Comment by eerbin13** [comment]
The bug still exists on 3.4.3.

**Comment by KoBeWi** [comment]
There is no way to solve this without adding an unsigned integer type. Godot will already print an error for numbers it can't represent, so this is handled properly.
