### ISSUE TITLE
Error building on Linux

### ISSUE THREAD

**Issue by jefvaia** [godotengine/godot#36386]
Hi,

I am trying to build godot on a raspberry pi 4B (4GB model) with ubuntu 64 bit. I have the latest version of godot and ubuntu 19.10.
When I do the command 
`scons -j8 platform=x11`
 it starts building but at some point it gives me this error:
`g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
scons: *** [editor/editor_fonts.x11.tools.64.o] Error 1
scons: building terminated because of errors.`

Does anyone know how to fix this?

**Comment by akien-mga** [comment]
Lower the number of CPU cores you're using, `-j8` on a 4GB Pi is likely too much to build the 30 MB `editor/builtin_fonts.gen.h`.

**Comment by jefvaia** [comment]
Thanks for the tip.
I have tried building with `-j3` but it gave me another error: 
`collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.`

**Comment by jefvaia** [comment]
I finally succeeded building it by using `-j2`.
The next problem is that the executable file gives me the following error: 
`ERROR: Condition "err" is true. returned: ERR_CANT_CREATE
   at: _create_physical_device (drivers/vulkan/vulkan_context.cpp:342)`

**Comment by Janglee123** [comment]
As far as I know, signal 9 error indicates the process used too much ram and the system killed it. Try without the `-j3` parameter but I will take too long.

**Comment by akien-mga** [comment]
I don't think that current RasPi OSes support Vulkan, so yeah, you can't use the master branch there. Use the `3.2` branch for the stable release with GLES2 and GLES3.

**Comment by jefvaia** [comment]
It Worked!
I downloaded the 3.2 branch and compiled it.
I just had to wait 2 hours for the compiler to finish.
The editor is a bit slow, but i could always overclock the Pi.

Thank you!
