### ISSUE TITLE
Strange line(copy paste bug?) in gdscript_workspace.cpp 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#36389]
**Godot version:**
Godot 4.0 5a8107f70a6dc3c43e89

**Issue description:**

This line looks very, very strange.
`script->get()` always return same value

https://github.com/godotengine/godot/blob/5a8107f70a6dc3c43e89df0ad69a5a0124bfc2df/modules/gdscript/language_server/gdscript_workspace.cpp#L52-L54

**Comment by Geequlim** [comment]
Sorry for the copy paste bug. It should be compare parser and script is point to same value.
