### ISSUE TITLE
godotengine.org/qa/ email confirmation appears to be broken

### ISSUE THREAD

**Issue by proarunas** [godotengine/godot#36383]
Discord told me to drop the report here.

When trying to create a new account by linking github, it still requires an email + confirmation to post, but the form rejects my definitely-valid gmail account as invalid.

When trying to create an account the normal way, the email gets stored and is displayed in the correct form field, but "send confirmation link" does not appear to do anything.

**Comment by KoBeWi** [comment]
Seems like this option is not available anymore.
