### ISSUE TITLE
"modules" subdirectory is not added to VSProj

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#36384]
**Godot version:**
f5bb6d6a7c6d225b15a8022a8511e3918fd02048

**OS/device including version:**
Win10

**Issue description:**
Seems like files in "modules" subdirectory does not being added to the generated VisualStudio solution:

![image](https://user-images.githubusercontent.com/3036176/74938461-1efec380-53ff-11ea-9f74-8256e6a16399.png)

Which prevent their debugging and force a user to manually add them.

**Steps to reproduce:**

Type `scons p=windows vsproj=yes` and open a resulted solution.

**Comment by HaSa1002** [comment]
This happens because when generate_vs_project is called, the modules are only set to register_module_types. That happens because `env.modules_sources` is resetted after every module.

**Comment by HaSa1002** [comment]
ok I have a fix and will create a pr in about an hour. I fixed it in my master ^^
