### ISSUE TITLE
Node.instance() not found

### ISSUE THREAD

**Issue by teko1987** [godotengine/godot#36397]
**Godot version:** 3.2.stable.version

**OS/device including version:** Windows 10

**Issue description:** Hi all! I'm new using the Godot, and I'm loving eery moment of it. But I've stumbled into a small problem. It all started with the game I was working on crashing while the remote inspector where selected. It was giving a windows error: access violation. I've eventually figured it out that the problem lied on my ChangeScene.gd code. So to test it, I've created a simple project that switches between 2 scenes using the brackground loading script that I've used (it is the same that is at https://docs.godotengine.org/en/3.2/tutorials/io/background_loading.html). But now, in this new project, the Debugger displays the error: _Invalid Call. Nonexistent function 'instance' in base GDScript._

The thing is that it works (almost) normally on my other project.

**Steps to reproduce:** Just run the project an click the button.

**Minimal reproduction project:** https://github.com/teko1987/InstanceError

![error](https://user-images.githubusercontent.com/14178065/74974208-92a2cf80-5403-11ea-9463-f266db7c7f9b.png)

**Comment by teko1987** [comment]
Sorru, the steps to reproduce is to run the scene and click the button!

**Comment by bojidar-bg** [comment]
The error is correct. `instance()` is a method of `PackedScene`, not of `GDScript`.
Note that in the project you uploaded, you are doing [`ChangeScene.load_scene("res://Scene2.gd")`](https://github.com/teko1987/InstanceError/blob/master/Test/Scene1.gd#L4), when it should be `ChangeScene.load_scene("res://Scene2.`**`tres`**`")`.

**Comment by teko1987** [comment]
Thank you! I feel bad for not seeing that mistake... ^^'
