### ISSUE TITLE
Every time I try to run my project, I get an error that says  drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054(CSharp)

### ISSUE THREAD

**Issue by LuizAntonioPereira** [godotengine/godot#36398]
**Godot version:** Godot_v3.1.2-stable_mono_win64

**OS/device including version:** Windows10

**Issue description:**
Create a game from a tutorial and this error is appearing when I play, it tries to run and the same stop appears in the video.
Every time I try to run my project, I get an error that says 
drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054
https://cdn.discordapp.com/attachments/471147340779094047/680138633986179088/2020-02-20_16-46-33.mp4

**Steps to reproduce:**
Create the project with CSharp.
And I followed this YouTube Tutorial.
https://www.youtube.com/watch?v=_urHlep2P84&t=126s

**Minimal reproduction project:**
https://cdn.discordapp.com/attachments/471147340779094047/680140514330411022/NavMesh.zip
[NavMesh.zip](https://github.com/godotengine/godot/files/4233034/NavMesh.zip)

**Comment by kuruk-mm** [comment]
Error 10054 is WSAECONNRESET
> Connection reset by peer.
> An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or remote network interface is disabled, or the remote host uses a hard close (see setsockopt for more information on the SO_LINGER option on the remote socket). This error may also result if a connection was broken due to keep-alive activity detecting a failure while one or more operations are in progress. Operations that were in progress fail with WSAENETRESET. Subsequent operations fail with WSAECONNRESET.
> (source: https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2)

Are you sure the server is not kicking you instantly?
Anyway I'm testing your project

**Comment by kuruk-mm** [comment]
Ok, I seen your project, it is nothing about what I said.

It is related with this issue #28678

If you go to **Project Settings > Mono > Debugger Agent > Wait for Debugger > Unchecked**

It will works.

**Comment by LuizAntonioPereira** [comment]
![image](https://user-images.githubusercontent.com/19380442/75034173-67fc5980-548b-11ea-8b98-d426156aedb0.png)
![image](https://user-images.githubusercontent.com/19380442/75034203-777ba280-548b-11ea-93e5-17254630ffe6.png)
Here he made an error he did the same thing as always but this time he debugged.

**Comment by Zireael07** [comment]
In that case, it's an error in your own code and this issue can be closed.

**Comment by kuruk-mm** [comment]
> Ok, I seen your project, it is nothing about what I said.
> 
> It is related with this issue #28678
> 
> If you go to **Project Settings > Mono > Debugger Agent > Wait for Debugger > Unchecked**
> 
> It will works.



> ![image](https://user-images.githubusercontent.com/19380442/75034173-67fc5980-548b-11ea-8b98-d426156aedb0.png)
> ![image](https://user-images.githubusercontent.com/19380442/75034203-777ba280-548b-11ea-93e5-17254630ffe6.png)
> Here he made an error he did the same thing as always but this time he debugged.

But you try this?

**Comment by LuizAntonioPereira** [comment]
I did and when I gave play this error appeared there that is saying that line 21 is not being referenced.

**Comment by LuizAntonioPereira** [comment]
I did and when I gave play this error appeared there that is saying that line 21 is not being referenced.

> Here he made an error he did the same thing as always but this time he debugged.
> 
> But you try this?
> 
> Project Settings > Mono > Debugger Agent > Wait for Debugger > Unchecked

I did and when I gave play this error appeared there that is saying that line 21 is not being referenced.

How do I open the commit unintentionally I closed I wanted to reference your commit.

**Comment by LuizAntonioPereira** [comment]
@kuruk-mm When did you test it work?

**Comment by kuruk-mm** [comment]
> @kuruk-mm When did you test it work?

Yes, with "Wait for Debugger" unchecked.

> Here he made an error he did the same thing as always but this time he debugged.

But that error is because in your "_PhysicsProcess" function is crashing because KinematicBody.cs line 21 you're "path" is null, and is trying to access to null variable. So as @Zireael07 says it's an error of your own code.

Quickly solution:
![image](https://user-images.githubusercontent.com/12563266/75045896-d7317800-54a2-11ea-9094-59170e151f06.png)

**Comment by LuizAntonioPereira** [comment]
But when you clicked the player go to the position that was clicked?

**Comment by kuruk-mm** [comment]
> But when you clicked the player go to the position that was clicked?

I didn't try it, but is not a engine issue, and I'm not a C# programmer. So I don't know what is going on... You can get a better answer here https://godotengine.org/qa/questions

**Comment by LuizAntonioPereira** [comment]
Thanks for all the help you gave me.
