### ISSUE TITLE
Godot 3.2 on MacOS is completely different from Windows 10 version.

### ISSUE THREAD

**Issue by ThomasUijlen** [godotengine/godot#36401]
[Godot 3.2 stable from steam]

macOS Catalina 10.15.1
Windows 10

I currently have the problem that a project of mine behaves completely different on both laptops.
They fist of all look completely different, the windows version is how its supposed to look. The windows version is the picture that has 10x more color.

The other weird bug is with rotation. My particles ingame have a different rotation on both versions.
On both versions the rotation is (0,90,0). One of them rotates around the x-axis (windows) and the other one around the z-axis (mac). (look at this link for reference https://i.stack.imgur.com/FS7OG.png)

To reproduce the rotation bug you just need to rotate stuff on both versions and you'll see the difference. I have no idea what causes the visual bug.

![image2](https://user-images.githubusercontent.com/48672748/74986325-a0734780-5439-11ea-9add-d61b97580fb9.jpeg)
![image0](https://user-images.githubusercontent.com/48672748/74986356-a2d5a180-5439-11ea-8827-2e18f4f27f1d.jpeg)

**Comment by Calinou** [comment]
> They fist of all look completely different, the windows version is how its supposed to look. The windows version is the picture that has 10x more color.

Different displays have different color output :slightly_smiling_face: 

There's no way to completely solve this, but you can calibrate your displays to make them look more correct.

**Comment by kuruk-mm** [comment]
And remember Mac resolutions are unique having an aspect ratio of 8:5 usually (or always). And default monitor has 16:9 aspect ratio.

And about particle rotation. It just with particles?
Can you send a video/gif to see this different? Thanks

**Comment by swaggerbeer1** [comment]
@Calinou I wish this was the case. But this color difference what not there in Godot 3.1 :(

**Comment by swaggerbeer1** [comment]
@kuruk-mm I’ll try to get a gif tomorrow. And yes, it is caused by the rotation and not by the screen.

I know this because my gun has a shooting effect that shoots blue circles out the front, they are currently flying out the right side of the gun. xD

**Comment by kuruk-mm** [comment]
> @kuruk-mm I’ll try to get a gif tomorrow. And yes, it is caused by the rotation and not by the screen.
> 
> I know this because my gun has a shooting effect that shoots blue circles out the front, they are currently flying out the right side of the gun. xD

But it just with particles? Or everything?

**Comment by swaggerbeer1** [comment]
I think I have found the problem. The particles come out at a different side on macOS. The screenshot where te particles are going up is macOS, the other one is windows. As you can clearly see the rotation for both is (0,0,0).

So rotation is not the cause, it is the direction the particles come out.
![thumbnail_image0](https://user-images.githubusercontent.com/48672748/75014496-b78c5680-5486-11ea-9936-3c0ad016e35b.jpg)
![thumbnail_image1](https://user-images.githubusercontent.com/48672748/75014501-b9561a00-5486-11ea-9eed-84a4080be32d.jpg)

**Comment by kuruk-mm** [comment]
Ok. Can you send me this particle or a project with this particle? I going to test it. I need to install a Mac VM so it can take a while (tonight or tomorrow). Thanks

**Comment by swaggerbeer1** [comment]
@kuruk-mm 
Here is a project that perfectly demonstrates the issue. Here are also some extra screenshot from what I'm experiencing.

![thumbnail_image0](https://user-images.githubusercontent.com/48672748/75081588-ff0af500-550f-11ea-8a75-cbab1215feac.jpg)
![thumbnail_image1](https://user-images.githubusercontent.com/48672748/75081590-00d4b880-5510-11ea-8a31-cc6f7a7c08ce.jpg)
[ParticleBug.zip](https://github.com/godotengine/godot/files/4238541/ParticleBug.zip)

**Comment by clayjohn** [comment]
The particles issue may already be solved by https://github.com/godotengine/godot/pull/36031

**Comment by swaggerbeer1** [comment]
@clayjohn @kuruk-mm Is it a better idea to just get 3.2 from github instead of steam? Since the github version gets regular bug fixes.

**Comment by clayjohn** [comment]
@swaggerbeer1 if you get it from GitHub you have to build it yourself. But you do get bug fixes as soon as they are submitted. So it's up to you.

**Comment by danilw** [comment]
I saw in Godot particles(default build in particle shader) problems with /0 (or that linked UB by trigonometric functions)
its not Mac/other OS, its about Driver/GPU hardware

...particles has too many options that very unsafe in Godot(and docs absolutely silent about it) and trigger UB in shaders, only launching own project on many platforms is fastest way to debug it and make work correctly

**Comment by akien-mga** [comment]
You can try Godot 3.2.1 RC 1 which has a fix for a Particles bug: https://godotengine.org/article/release-candidate-godot-3-2-1-rc-1

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
