### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#36408]
**Godot version:**
3.2
**OS/device including version:**
 Mac OS X 10.15.3 (19D76)

**Issue description:**
The scene editor has no response when switch scene tab, then it quit. 
It happens very frequently.

**Steps to reproduce:**
It happens randomly without any particular steps.

**Minimal reproduction project:**
[crash.txt](https://github.com/godotengine/godot/files/4234155/crash.txt)

**Comment by clayjohn** [comment]
Please fill out the template. We need more info to help you!

**Comment by kant1989** [comment]
**Godot version:**
3.2.1.rc1.official
**OS/device including version:**
Windows 7 SP1 x64

**Steps to reproduce:**

1. Create new project
2. Add Node2D (for example)
3. Save Scene and closed tab - tab1
4. Reopened closed scene
5. Add new tab - tab2
6. Go to previous tab (tab1) and delete node
7. Go to tab2 and back to tab1
8. Crash
![Steps-to-reproduce](https://user-images.githubusercontent.com/61357517/75096430-958ef300-55b0-11ea-9526-d33a5f6c5607.gif)
