### ISSUE TITLE
Reason why get_texture().get_data().get_pixel() is 8bit on Web, and 16-32 bit on Native ?

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#36416]
**Godot version:**
3.2 stable

**OS/device including version:**
Web/linux/windows

**Issue description:**
**This is question.**
Why Godot Web build does not use FORMAT_RGBAF same as native?

**Steps to reproduce:**
Launch web/native build, check "get pixel active" and move mouse to white square(that >1 in viewport)
in Native build it read correct value, in Web only 8bit
I made test project: [Web build](https://danilw.github.io/godot-utils-and-other/fbo_get_pixel_test/web/getpixel.html)
[Windows build(exe)](https://danilw.github.io/godot-utils-and-other/fbo_get_pixel_test/fbo_test_win.zip)

**Minimal reproduction project:**
[source of that test zip](https://danilw.github.io/godot-utils-and-other/fbo_get_pixel_test/fbo_test_src.zip)

**Comment by danilw** [comment]
also I have second question:
**Memory leak** because of using get_texture().get_data().get_pixel()
this happened not always, like 50% of launches...and it hit "whole application" like random text appeared on random UI elements(in big project)
I do not have test for this bug, but as I see this bug exist... 
(this test also has it in like 20% of launches, open source project in Godot editor, run it few times(from Godot editor), and UI elements in Godot(editor) become broken randomly...)
...complicated bug I dont think someone want waste time to debug it...

**Comment by hammeron-art** [comment]
I can't reproduce. I get FORMAT_RGBAH (GL_RGBA32F 16-BIT "HALF-PRECISION") in Chrome, Firefox, and Desktop on Windows 10 from your test project.

**Comment by danilw** [comment]
ye but Value readed is 1.0 when in Native build is correct >1.0

in **Godot 3.2 standard**
the Format is FORMAT_RGBAH always in both Web and Native

in Custom **Godot build** with enabling 32bit FBO(not 16 bit that by default in Godot)
WebBrowser report FORMAT_RGBAH 
when Native FORMAT_RGBAF (to store real 32bit value)

**Comment by Calinou** [comment]
@danilw Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by danilw** [comment]
@Calinou Tested now on Godot 3.5.1 web-export template. **(this bug is Web-export-only)**

Tested on Chrome 105.0.5195.52

**Result still bug.** (if I understand correcrly how it work)
(low fps on screenshot because launched in chrome-vulkan, but behavior same with OpenGL)
![image](https://user-images.githubusercontent.com/24825887/200121131-79a558df-559b-4e13-ad6f-8f60582eea51.png)

**Expected result** - "white region of image" should show values > 1,0 and 
![image](https://user-images.githubusercontent.com/24825887/200121522-4bbc641c-7e45-41d1-be1c-f20055b10c74.png)
As you see on this screenshot - FBO set to HDR, I tested with HDR-32 bit - result same as on first screenshot.

Tested only in Vulkan and OpenGL, in Windows ANGLE not tested.
--use-angle=vulkan
--use-angle=gl

**Comment by clayjohn** [comment]
Here is the chunk of code responsible:
https://github.com/godotengine/godot/blob/92aedd506375356d3323d8896a02d6c9bc11661e/drivers/gles3/rasterizer_storage_gles3.cpp#L1211-L1282

The reason it forces using RGBA8 is that it needs to render the texture to a Framebuffer and then read the framebuffer with glReadPixels (This is the only way that WebGL2 supports reading data from a texture). However, OpenGL ES 3.0 / WebGL2 do not support rendering to framebuffers with floating point pixel formats. So you can't render to an RGBA16 or RGBA32 render target. This is a limitation in WebGL2 and not in Godot itself. The extensions that allow to use floating point render targets are not very well supported in WebGL2 so we do not rely on them.
