### ISSUE TITLE
CircleShape2D's radius is restricted to 16384

### ISSUE THREAD

**Issue by udit** [godotengine/godot#36419]
**Godot version:** 3.2

**Issue description:**
https://github.com/godotengine/godot/blob/master/scene/resources/circle_shape_2d.cpp#L63 restricts max radius of `CircleShape2D` to 16384. Hint range should be removed so it is consistent with other shapes like `CapsuleShape2D` and `RectangleShape2D`.

**Comment by Calinou** [comment]
Note that as a workaround, you can change its size using a script. Hints only apply to the editor.
