### ISSUE TITLE
Asset library doesn't load when using a dual stack IPv4/IPv6 network

### ISSUE THREAD

**Issue by affemannen** [godotengine/godot#36418]
**Godot version:**
3.2
**OS/device including version:**
Linux Mint Cinnamon 19.3
**Issue description:**
Get the message "Can't connect to host: https://godotengine.org/asset-library/api" 
**Steps to reproduce:**
Top middle choice "AssetLib"
**Minimal reproduction project:**
![assetlib](https://user-images.githubusercontent.com/17325494/75036824-0223c800-54b3-11ea-9078-19b7ea9f6179.png)

**Comment by Calinou** [comment]
Are you using a proxy on your system? Godot doesn't support HTTP proxies yet, see #6100.
Also, double-check there's not a firewall blocking access to http://godotengine.org/asset-library/api/asset (try loading that URL in your browser).

**Comment by affemannen** [comment]
No proxy, exceptions in Firewall are in place. The URL works in browser, yes.
Could my HMA-VPN be causing this?

**Comment by affemannen** [comment]
https://godotengine.org/asset-library/api/asset (worked) 
https://godotengine.org/asset-library/api/ (didn't work)

**Comment by Calinou** [comment]
> https://godotengine.org/asset-library/api/ (didn't work in browser)

This is expected, as that URL is the base API URL. The resource URL (such as `/asset`) is appended to that URL

**Comment by affemannen** [comment]
https://godotengine.org/asset-library/api/ (didn't work in browser)

above address is what is displayed in Godot. Can I add /asset to it or is it done automatically?

**Comment by Faless** [comment]
> Could my HMA-VPN be causing this?

Well, maybe, try disabling it and we'll know. Maybe another case of #27864 ?

**Comment by affemannen** [comment]
No, disabling VPN didn't work.

**Comment by Faless** [comment]
I see, can you run the editor in verbose mode (via `--verbose`) and post the console output after clicking on the assetlib tab? Should give more informations about the network failure.
Can you also post the output of `ifconfig` in your machine (with VPN disabled)

**Comment by affemannen** [comment]
Thanks Faless, could you elaborate on what I need to do? I'm kind of to Linux so I could use some help to give you what you need.

**Comment by Faless** [comment]
@affemannen 
- Open a terminal, type `ifconfig` press enter. Copy paste the result here.
- Open a terminal, type `/path/to/godot.bin --verbose -e --path /path/to/your/project`. Change `/path/to/godot.bin` to the path of the godot binary, and `/path/to/your/project` with the path of your project folder.

**Comment by affemannen** [comment]
The ifconfig gives:
`enp5s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether c8:60:00:4a:38:03  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2597  bytes 231100 (231.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2597  bytes 231100 (231.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 100.120.93.60  netmask 255.255.248.0  destination 100.120.93.60
        inet6 2001:db8:123::2  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::c2ae:7f96:6c24:5e1  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 1023752  bytes 1339108558 (1.3 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 526950  bytes 34825539 (34.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.112  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::8aad:6f8b:763b:f753  prefixlen 64  scopeid 0x20<link>
        inet6 fdaa:bbcc:ddee:0:a0d1:428b:96f5:3f2b  prefixlen 64  scopeid 0x0<global>
        inet6 fdaa:bbcc:ddee:0:3dd5:c868:6242:98e5  prefixlen 64  scopeid 0x0<global>
        inet6 fdaa:bbcc:ddee:0:c460:316c:848:1fbe  prefixlen 128  scopeid 0x0<global>
        ether 00:08:ca:f3:ac:74  txqueuelen 1000  (Ethernet)
        RX packets 1991575  bytes 2577236899 (2.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1025126  bytes 179129388 (179.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`
Without the VPN
`enp5s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether c8:60:00:4a:38:03  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2599  bytes 231178 (231.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2599  bytes 231178 (231.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.112  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::8aad:6f8b:763b:f753  prefixlen 64  scopeid 0x20<link>
        inet6 fdaa:bbcc:ddee:0:a0d1:428b:96f5:3f2b  prefixlen 64  scopeid 0x0<global>
        inet6 fdaa:bbcc:ddee:0:3dd5:c868:6242:98e5  prefixlen 64  scopeid 0x0<global>
        inet6 fdaa:bbcc:ddee:0:c460:316c:848:1fbe  prefixlen 128  scopeid 0x0<global>
        ether 00:08:ca:f3:ac:74  txqueuelen 1000  (Ethernet)
        RX packets 1992811  bytes 2577547693 (2.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1025853  bytes 179288579 (179.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`
I don't understand your second request as I've just installed Godot and was about to start using it when this problem occurred. I've made a project but it doesn't contain much.

**Comment by Calinou** [comment]
> Ah, shit, I'm trying to make this readable but the forum fails...

Wrap the pasted text in triple backticks (\`\`\`).

**Comment by affemannen** [comment]
Ok, that's better :-)

**Comment by Faless** [comment]
Mmhhh, might be a case of broken dual stack?  Can you try those 2 commands in terminal? (I hope they are installed)
- `ping -c 5 godotengine.org`
- `ping6 -c 5 godotengine.org`

and post the result?

**Comment by affemannen** [comment]
```
PING godotengine.org (212.85.158.4) 56(84) bytes of data.
64 bytes from web.tuxfamily.net (212.85.158.4): icmp_seq=1 ttl=47 time=59.0 ms
64 bytes from web.tuxfamily.net (212.85.158.4): icmp_seq=2 ttl=47 time=56.2 ms
64 bytes from web.tuxfamily.net (212.85.158.4): icmp_seq=3 ttl=47 time=60.3 ms
64 bytes from web.tuxfamily.net (212.85.158.4): icmp_seq=4 ttl=47 time=58.8 ms
64 bytes from web.tuxfamily.net (212.85.158.4): icmp_seq=5 ttl=47 time=59.0 ms

--- godotengine.org ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4005ms
rtt min/avg/max/mdev = 56.240/58.708/60.312/1.354 ms
```
Clearly, it has something to do with my VPN. I shut it down for the command but I don't want to not have it up and running, it has to. Maybe there is something in the VPN script that can be edited?

**Comment by Faless** [comment]
@affemannen oh, so **it does work** without your VPN? I thought it still didn't work :confused: 
Anyway, what about the second command?
`ping6 -c 5 godotengine.org`
What does that output?

**Comment by affemannen** [comment]
```
~$ ping6 -c 5 godotengine.org
connect: Network is unreachable
```

**Comment by affemannen** [comment]
However, with VPN active this came up:

```
~$ ping6 -c 5 godotengine.org
PING godotengine.org(web.tuxfamily.net (2a02:2178:1000:201::4)) 56 data bytes

--- godotengine.org ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4084ms
```

**Comment by Faless** [comment]
Yep, that's what a broken dual stack network looks like.
Probably something to do with the VPN tunnels tricking the engine into thinking there is an IPv6 network thus resolving the address as IPv6.
Not much we can do here unless someone wants to implement [Happy Eyeballs](https://tools.ietf.org/html/rfc8305) into `HTTPClient` (which is the standardized hack to deal with broken dual stack network).
I wish we could finally call IPv4 dead and move on :sob:

**Comment by affemannen** [comment]
I'll contact the HMA support on this and see what they come up with... probably nothing.

Thanks for all your help anyway, very much appreciated.

**Comment by jonbonazza** [comment]
I wonder if you can use some /etc/hosts hackery to force that particular domain to resolve to an ipv4 addr

**Comment by jamie-pate** [comment]
See also here: https://godotengine.org/qa/21458/https-request-failing-on-a-request-that-acts-weird

**Comment by jabcross** [comment]
I just managed to work around this problem on my end, so posting here to help fellow Google users, as as of 3.3.4 stable the fix is not merged yet.

I managed to solve it by setting up a IPV6 DNS override on my network adapter, as apparently the one provided my my ISP wasn't working. (I used OpenDNS). Try this before cherry-picking a commit!

**Comment by jamie-pate** [comment]
Workarounds are good, but Ideally the engine can work around broken
networks in general since it's not feasible to ensure that all users can
fix their broken dual stack themselves :)
