### ISSUE TITLE
Overlapping 3D RigidBodies not moving with the physics engine.

### ISSUE THREAD

**Issue by Ramshell** [godotengine/godot#36423]
**Godot version:**
3.2 stable

**OS/device including version:**
Ubuntu 19.10
**Issue description:**
I want to reproduce this behavior in 3D:

![2D overlapping rigid body movement](https://user-images.githubusercontent.com/12850723/75046572-1f04cf00-54a4-11ea-92a3-9af424f2f1c1.gif)
 
The rigid bodies are set in Character mode, and the gravity is set to 0.

When I try to do that same in 3D (locking the Y-axis in the rigid body) I get this result:

![3d_overlapping_rigid_body_movement](https://user-images.githubusercontent.com/12850723/75046814-8cb0fb00-54a4-11ea-9f30-54950ec981e7.gif)

The bodies stay still no matter what.

**Minimal reproduction project:**
[minimal_reproduction_project.zip](https://github.com/godotengine/godot/files/4236745/minimal_reproduction_project.zip)

**Comment by pouleyKetchoupp** [comment]
`ConcavePolygonShape` is not supposed to be used for moving rigid bodies. There are warnings about that on the `CollisionShape` nodes in your project:
```
ConcavePolygonShape doesn't support RigidBody in another mode than static.
```

It works as expected if you use a `ConvexPolygonShape` or `BoxShape` instead, so closing.
