### ISSUE TITLE
3.2 android custom IAP plugin help

### ISSUE THREAD

**Issue by SinaZK** [godotengine/godot#36420]
Hi, For releasing my mobile game for local market, i need to implement market in app purchase. This local market use exactly the same libraries as GooglePlay with different url. In Pre 3.2 versions i changed the engine PaymentManager code (platform/android/java/src/org/godotengine/payments) line 74:
Intent intent = new Intent("com.android.vending.billing.InAppBillingService.BIND");
to 
local market url and compiled the engine and it works fine. But in 3.2 I can't find any way to change this without compiling the engine and using custom templates. But then i can not use my custom 3.2 plugins. I don't have any idea how to overcome this issue.

**Comment by m4gr3d** [comment]
The IAP plugin was moved to its [own repo](https://github.com/godotengine/godot-google-play-billing). Please reopen the issue there if needed.
