### ISSUE TITLE
Scene thumbnail is flipped vertically

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#36425]
**Godot version:**
Master 8b058d4b9a63799e29d3e9ef551bbdf8144f8f8b

**OS/device including version:**
OS: Windows 10
GPU: Nvidia GeForce 940M

**Issue description:**
Scene preview thumbnails are systematically generated upside down when saving a scene in the editor.

<img src="https://user-images.githubusercontent.com/1075032/75053577-d532dd80-54d1-11ea-8da7-f6b0091729d9.png" width="400"/>

![image](https://user-images.githubusercontent.com/1075032/75053768-217e1d80-54d2-11ea-91ff-f67462030fe6.png)

**Steps to reproduce:**
- Create a new project
- Create a new scene
- Save
- Check the thumbnail in the open scene dialog or when hovering mouse cursor in the scene tabs

**Minimal reproduction project:**
Any project

**Comment by dreamsComeTrue** [comment]
Yep, confirming that too - as if UVs were reversed or smth..
