### ISSUE TITLE
Collision detection not always working using move_and_collide on KinematicBody2D with save_margin at 0.001

### ISSUE THREAD

**Issue by marzecdawid** [godotengine/godot#36432]
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
[Video showing the problem.](https://i.imgur.com/ndTF24V.mp4)
Collision detection is not always working using two KinematicBody2D objects with save_margin set to very low value like 0.001-0.004. In the gif above all three objects have save_margin at 0.001 and the only difference is a starting position.

**Minimal reproduction project:**
[CollisionBug.zip](https://github.com/godotengine/godot/files/4238398/CollisionBug.zip)
Don't forget to enable collision drawing in debugging menu.
Press up arrow key to move objects.

**Comment by marzecdawid** [comment]
Retested on version **3.1.2** and **3.0.6**.
**3.1.2**: problem is present
**3.0.6**: wasn't able to reproduce the bug

_Am I not allowed to add a label to my issue if I'm not a contributor?_

**Comment by akien-mga** [comment]
Still reproducible in a18df71789a36b318c40d691efdb4da1e574bbfd (`3.2`).

**Comment by madmiraal** [comment]
Fixed with #43616 and its 3.2 version #43617.
