### ISSUE TITLE
Include search box in the Classes list window (Script editor)

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3645]
When looking for Class info, I prefer to go to the "Search Help" button instead of the more logical "Classes", just because I can quickly type the name. Navigating the huge class tree takes longer. Would be great if we could add the same search box with auto-filter as we type.

**Comment by neikeq** [comment]
I agree. You can already search for classes in the _Search Help_ dialog, but the results are mixed with functions, variables and other types. You can't either see the parents while searching, as you would do with the _Create New Node/Resource_ dialogs.
