### ISSUE TITLE
Export resource return empty C# script file

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#36458]
**Godot version:**
3.2 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
When I export a c# script in PCK/Zip format the  script inside is empty
**Steps to reproduce:**
Make a basic project in c#
add a basic c#script with any text inside
then export it
Project->Export->Resources->Export Selected resources (and dependencies)
Select a c# script
press button "Export PCK/Zip"
give a name + extension

**Minimal reproduction project:**
NA

**Comment by Mek101** [comment]
C# is compiled to bytecode, I'm surprised the source files still exist in the exported game

**Comment by git2013vb** [comment]
I guess you are referring to "Export Project" options but
We talk about "Export PCK/Zip" options.  In this case I expect to have the whole project exported (scripts included)

**Comment by git2013vb** [comment]
Export and Docs changed. Close.
