### ISSUE TITLE
4.0: Editor hangs for several seconds on project load (Regression from 3.2.x)

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#36468]
**Godot version:**
Godot Engine v4.0.dev.custom_build.f2d8c4eb8

**OS/device including version:**
Linux Mint 19.3
GeForce GTX 960
NVIDIA Driver 435.21-0ubuntu0.18.04.2

**Issue description:**
Editor takes a long time to load initially, and game also takes (not as much) time to start

https://i.imgur.com/7boLC8r.mp4

**Steps to reproduce:**
Start editing a project while the editor is running using Vulkan

**Minimal reproduction project:**

**Comment by Calinou** [comment]
I noticed a regression in startup time too. I'm not sure if it can be completely brought back to 3.2 levels though.

**Comment by clayjohn** [comment]
Part of this load time is shaders compiling. That's where the uniform printing is coming from.

**Comment by Anutrix** [comment]
But doesn't shader compilation happen just once?

**Comment by clayjohn** [comment]
@Anutrix yes, while the editor/game loads.

**Comment by Calinou** [comment]
I remember seeing reduz talking about caching shaders on disk, is that still planned?

**Comment by clayjohn** [comment]
@Calinou With Vulkan it is possible. I don't think reduz has implemented it yet.

**Comment by KoBeWi** [comment]
Still valid in bccbd4b although the uniform total doesn't appear anymore.

**Comment by akien-mga** [comment]
Closing as duplicate of #43351 as it's likely the same issue (shader compilation takes a while, no caching yet), and that other issue has a lot of profiling info.
