### ISSUE TITLE
AssetLib does not load in 4.0

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#36469]
**Clarification**: Is this because there is an issue in 4.0 or because there are no Assets made yet for 4.0?

**Godot version:**
Godot Engine v4.0.dev.custom_build.f2d8c4eb8

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
AssetLib loads fine in 3.2
![image](https://user-images.githubusercontent.com/14253836/75101330-9e77c880-55a0-11ea-8607-713db042afc9.png)

> No results for ""

in latest master

![image](https://user-images.githubusercontent.com/14253836/75101521-48585480-55a3-11ea-9397-8acca5f8cd80.png)

**Steps to reproduce:**
Open AssetLib or Templates in 4.0

**Minimal reproduction project:**

**Comment by Calinou** [comment]
> Clarification: Is this because there is an issue in 4.0 or because there are no Assets made yet for 4.0?

It's probably the former, as the asset library can be contacted successfully by the editor.

**Comment by nathanwfranke** [comment]
> I guess we can change the message displayed in case there are no results for an empty search string

This will only be a problem while there are no other assets, which shouldn't be a problem after people start updating to 4.0. What should the error be? "There are currently no assets for [version]"?

**Comment by aaronfranke** [comment]
Well, people could also be confused about something not showing up even if there are some assets targeting 4.0. I think maybe there should be a general message of "Note: Only assets made for Godot [version] will appear on this list".

**Comment by Calinou** [comment]
> BTW, maybe we should allow the asset library to simultaneously have multiple versions of an asset for different Godot versions, so that users of older releases don't have assets disappearing as the assets are updated for the latest Godot version.

This is what the [asset library rewrite](https://github.com/Calinou/godot-asset-library-laravel) allows :slightly_smiling_face:

**Comment by nathanwfranke** [comment]
> Still, adding a checkbox to toggle displaying incompatible assets would be useful for non-code assets.

When one uploads an asset, they should have an option of what versions they work on, or they can say all versions. (There may be issues if we ever change .import formats since they are present in almost every asset pack).

As for versioned things, how about something like:

> No results for "search" (v4.0)

> No assets found (v4.0)

And all versions

> No results for "search"

> No assets found

**Comment by Calinou** [comment]
@nathanwfranke The asset library rewrite also allows specifying that an asset works with any Godot version. This is specifically intended for non-code assets as I said.
