### ISSUE TITLE
Options to make it easier to include/exclude folders on export.

### ISSUE THREAD

**Issue by KioriSun** [godotengine/godot#3646]
When you opt for select items to export, the export/bundle action should also be available for folder(in which case all sub folder content would be affected/included.

Having to manually include each file inside a given folder is a shore.

Also, as an alternative to that, when exporting all resources, it could be useful if folder wildcards like /assets/\* could also be used, along side extension wildcards like *.txt .

The main use for this is for making extra content packed into select .pcks, to be used later.(dlcs, expansions, etc.)

Having a decent select exporter could also make prototyping inside your main project a possibility, since its easy to decide what gets exported in the end.

**Comment by vnen** [comment]
Adding the Hacktoberfest tag, shouldn't be hard to add this.

**Comment by Gibbz** [comment]
yep, would be good to exclude my assets folders in a simple way as suggested!

**Comment by williamd1k0** [comment]
+1
I always create a folder called `devel` in my projects to store development stuff, things like prototype scenes/scripts, random data, localization stuff.

**Comment by dreamsComeTrue** [comment]
![image](https://user-images.githubusercontent.com/1110337/66254825-0c4f5f00-e77c-11e9-9ffb-e5a6eaa4bd69.png)

Isn't that already done?

**Comment by Calinou** [comment]
@dreamsComeTrue Not to my knowledge, the option displayed in the screenshot requires the user to explicitly check all resources they'd like to export.

A good way to fix this would be to run the non-resource export filter over the full file path, not just the file name. This way, you could exclude patterns like `docs/*`.
