### ISSUE TITLE
Blender's glTF/glb addon fails to export rig proxy properly

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#36475]
**Godot version:**
`master` / 0f80df0dc

**OS/device including version:**
Manjaro Linux (KDE/Testing)

**Issue description:**
In my project, I have a master .blend file containing a character model on which all other Blender sources for assets (e.g. animations, hair, clothes, and so on) depend (by linking to the source object).

In order to create animations this way, I need to create a proxy (`Make Proxy` command) of the linked rig from the dependent .blend file, since the original rig cannot be modified directly.

However, when I export the result using glTF addon shipped with Blender 2.82.7, it treats each bone as a `Spatial` node instead of exporting the skeleton as other exporters do which results in an unusable result as shown below:
![image](https://user-images.githubusercontent.com/2367032/75104572-37185200-564e-11ea-97f5-14762fd8ae6b.png)

**Comment by aaronfranke** [comment]
If this is a Blender bug, then why are you reporting it here?

**Comment by mysticfall** [comment]
@aaronfranke Because I'm not sure of that. I wouldn't mind closing this issue if someone can confirm that this should be fixed on Blender's side.

**Comment by fire** [comment]
Please try using Blender 2.83. A pr was made on Jan 4th and be release with the stable release of Blender 2.83.

**Comment by vnen** [comment]
Any news on this? Is there something that needs to be fixed in Godot?

**Comment by aaronfranke** [comment]
@mysticfall Please attach a minimal reproduction project.

**Comment by mysticfall** [comment]
I'm sorry it's been a while since I worked on my Godot project, and currently I'm engaged with different projects.
