### ISSUE TITLE
Can't open editor.  Vulkan context error.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#36479]
**Godot version:**
f2d8c4eb8

**OS/device including version:**
Win10 64-bit GeForce 9600 GT/PCIe/SSE2

**Issue description:**
When trying to open, it immediately closes, with this error.
```

ERROR: Condition "err" is true. returned: ERR_CANT_CREATE
   at: _initialize_extensions (drivers/vulkan/vulkan_context.cpp:229)
ERROR: Method/Function Failed, returning: m_value
   at: initialize (platform/windows/os_windows.cpp:1470)
```

**Comment by akien-mga** [comment]
I doubt this GPU has any Vulkan support, it's D3D 10 level hardware from ~2008.

But the error message could be improved.

**Comment by avencherus** [comment]
I suspect not either, but is it intended to fallback to OpenGL 2.0 at some point?  Would seem a bit exclusive for those just wanting to make 2D games that aren't very demanding and can run well on old hardware, like in previous versions.

**Comment by akien-mga** [comment]
Yes it will fallback to GLES2 if Vulkan is not supported. But GLES2 is not ported yet.

**Comment by Calinou** [comment]
> I doubt this GPU has any Vulkan support, it's D3D 10 level hardware from ~2008.

Indeed, Vulkan support is limited to Kepler GPUs (GeForce 600 series) and newer.

**Comment by akien-mga** [comment]
Closing as it's a fairly old issue. The error has been improved since then. It's not perfect yet but suggestions to improve it would best be served with a new issue.
