### ISSUE TITLE
DIFFUSE usable from fragment shader

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#3647]
Operating System: Ubuntu 15.10
Device: ASUS U31S
GPU: GeForce GT 520M, NVIDIA proprietary driver 352.63
GODOT version: 2.0 RC1 (09 FEB 2016)

### Steps to reproduce

Open up GODOT, create a `Sprite2D` node, add new material, add new `CanvasItemShader`, go to fragment and write `DIFFUSE = vec4(1,0,0,1) + vec4(1,1,1,1) * mod(TIME,1.0);` giving: `error(1,0): Nonexistent identifier in expression: DIFFUSE`. 

I see this is an older problem, but nobody checked it out: http://www.godotengine.org/topics/13145?board_id=11... or at least, I don't know what's happening, cause in a closed issues I've seen this `DIFFUSE` used (in a different problem: #912) and the guy wasn't complaining about it... so at that time it must have worked.

**Comment by Hinsbart** [comment]
Well, #912 was probably a 3d shader.

Take a look at the [shader docs](http://www.godotengine.org/projects/godot-engine/wiki/Shader#CanvasItem-2D-FragmentShader). You'll see that only 3d shaders have the `DIFFUSE` keyword. 
For CanvasItem shaders you're looking for `COLOR`

**Comment by razvanc87** [comment]
Right, I was looking at [these docs](http://docs.godotengine.org/en/latest/reference/shading_language.html#material-fragmentshader) and  further in the page there is indeed something about `CanvasItem` 2D shaders, but lack of experience... I didn't know that Materials is for 3D, cause in the inspector, under `CanvasItem`, there's the `Material` portion of parameters... I think it's a bit confusing for beginners such as myself... it should be stated explicitly that `Materials` are for 3D cause I stopped there and didn't look further down, cause I didn't see the point then :)...

**Comment by rgrams** [comment]
Ah! I was just having this issue myself. I was looking at [these docs](https://github.com/godotengine/godot/wiki/shader) and totally missed that (btw how many different copies of the docs are there?!). It would be nice if the distinction between 3D and 2D materials was clearer. It should be a big header on the page, not smaller-than-average text.

**Comment by akien-mga** [comment]
> btw how many different copies of the docs are there?!

Hehe. The GitHub wiki is the oldest one but was kept around as the OpenProject wiki (godotengine.org/projects/godot/wiki) is super slow and kind of un-cool for several reasons. The docs.godotengine.org one will be the new official wiki and the rest will soon be closed, but it's not 100% ready yet. You can still use it though.

**Comment by rgrams** [comment]
Ah, gotcha, thanks!

**Comment by MarianoGnu** [comment]
@akien-mga i think this issue can be closed. CanvasItemShader has not DIFUSE builting variable, instead COLOR should be used.

**Comment by razvanc-r** [comment]
Yah, I see you closed this issue but it still remains, as @rgrams also pointed out. It would help if (3D) would be added to the Material tables like (2D) is for CanvasItem because new people that come to that page (http://docs.godotengine.org/en/latest/reference/shading_language.html) first see the Material tables with no indication that they are for 3D only and they will wonder why the DIFFUSE or some of the other variables won't work. That's what happened to me, I never saw the CavansItem because I stopped at Material. Now I know better but for new devs, you could very well just loose half a day just because of this little detail...

**Comment by akien-mga** [comment]
Pull requests welcome on the docs repo :)

**Comment by MarianoGnu** [comment]
This is because Material and CanvasItemMaterial are the name of the classes :confused: docs are welcome to be updated
