### ISSUE TITLE
Strange code inside editor_debugger_node.h

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#36477]
**Godot version:**
92332eb23d7b000cbd

**Issue description:**

Always is returned `line < p_b.line` but code also contains `if` which doesn't change anything

https://github.com/godotengine/godot/blob/92332eb23d7b000cbd0b7838b355c9f9f3ad4d0e/editor/debugger/editor_debugger_node.h#L60-L64

CC @Faless

**Comment by Faless** [comment]
Oh yeah, that was silly! Thanks for reporting! :+1:
