### ISSUE TITLE
Glitch playing SpatialStreamPlayer on top of Camera

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3649]
If a SpatialStreamPlayer has the exact same location as the Camera, the sound will not play. Instead we just hear a short noise.

Additional bug: having 5 (or more) SpatialStreamPlayers playing at the same time crashes the game without any errors. (I used autoplay, not sure if its the same if we play it manually, probably yes)

Sample scene attached
[sndtest.zip](https://github.com/godotengine/godot/files/124686/sndtest.zip)

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Assuming fixed in the master branch as the audio engine was completely rewritten.
