### ISSUE TITLE
Setter not called with default value

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#36496]
**Godot version:**
3.2

**Issue description:**
This is actually somewhat related to https://github.com/godotengine/godot/issues/33413#issuecomment-590124241 (same repro)
Not sure if a bug.

Setters are only called when the value is serialized in tscn. So if you have something set to default value, it most likely won't serialize and thus not call the setter. The thing is, the setter will be called when the default value is serialized (see #33413), which totally caught me off-guard. IMO the setter should always be called.

**Steps to reproduce:**
1. Open the repro project
2. Run it, see that "set" is printed (probably)
3. Open Abyss.tscn
4. The setter is no longer called

The reason is that variable magically disappears from tscn file (again, see #33413). When it's not inside tscn, the setter is not called. Otherwise it will be called, even if the variable is saved with default value.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4242684/ReproductionProject.zip)

**Comment by Xrayez** [comment]
You may find something about f2e54057aec3a4e4fbb9f9da5729915deb2f4648 which likely affected this, I recall the setters were always called before this change in <=3.0.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4
Can't test in master due to #42463

**Comment by derammo** [comment]
@KoBeWi still valid in v3.4.4.stable.mono.official [419e713a2] and the PR blocking it from testing in master is resolved, so maybe worth another look?  Sorry I am not set up to confirm myself at the moment

**Comment by vnen** [comment]
This is working as intended. The scene saving a value equals to the default is also okay for me, since you may want to pin the value even if the default in the script change later. If you don't want this you need to restore the default value in the inspector.

If it's saved in the scene it will be set after the instance is created, so it will call the setter, no matter the value. If not, then only the initialization of the script itself will set it, which by design doesn't call the setter.

**Comment by KoBeWi** [comment]
> The scene saving a value equals to the default is also okay for me, since you may want to pin the value even if the default in the script change later.

Yeah, the problem with that is that it can trigger as a result of a bug (it can e.g. happen with instanced scenes and you need to open the scene and save it to fix it), in which case it's not a desired behavior. But that's another issue.

**Comment by KoBeWi** [comment]
Ok closing since this is intended behavior.
The other bug I mentioned is already fixed (#33413), so it shouldn't happen unexpectedly.
