### ISSUE TITLE
Viewport window stretch mode does not reduce performance cost

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#36507]
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10

**Issue description:**
When i chose window stretch mode to be "Viewport", with a low resolution, i expected the performance cost to be reduced accordingly. However i found that stretching a 640 x 360 sized viewport costs the same as rendering at 4k resolution, with disabled window stretch mode
This is with the setting "Allow HiDPI" set to true.

There are two ways/workarounds to get lower drawing cost (but with the same visual results):

1. Set "Allow HiDPI" back to false again. Put the high dpi scale in windows to max (but only x00%, because non-integer scaling will distort distort the pixels in the game). This works because godot scales every pixel by the high dpi scale value set in windows, if "Allow HiDPI" is set to false.
2. Set the resolution in windows to be the same as the target viewport size in godot game.

This issue worries me, because I think it is too much to ask the users to go change their resolution settings in Windows, before playing a game. Also in my case, I could not reduce windows resolution lower than 1280 x 720, so I probably could have gotten 4x more performance if i used 3rd party software to get even lower resolution. I think this might be one of Godot biggest performance issues, as a doubling in resolution seems to cost about 4x more, which is logical because the amount of pixels is quadrupled. 

With the games target resolution of 640 x 360 pixels: Here you can see i increased FPS by over 1000%, just by changing settings in windows.

4K resolution with allow HIDPI disabled, window stretch mode = disabled:
![2020-02-24 (8)](https://user-images.githubusercontent.com/15088582/75156884-5a590500-5713-11ea-9178-0b0df98d9569.png)

4K resolution with allow HIDPI disabled, window stretch mode = viewport:
![2020-02-24 (4)](https://user-images.githubusercontent.com/15088582/75156421-655f6580-5712-11ea-9542-3e3308bb485b.png)

4K resolution with allow HIDPI enabled (200% scaling in windows), window stretch mode = viewport
![2020-02-24 (5)](https://user-images.githubusercontent.com/15088582/75156546-a192c600-5712-11ea-8a03-42785a14692b.png)

1280 x 720 resolution in windows:
![2020-02-24 (6)](https://user-images.githubusercontent.com/15088582/75156684-e4549e00-5712-11ea-9991-06f5de964068.png)

800 x 600 resolution in windows ( distorted, but still proves that FPS increases dramatically):
![2020-02-24 (7)](https://user-images.githubusercontent.com/15088582/75156718-02ba9980-5713-11ea-8b8b-4b4dcf0599fa.png)

**Steps to reproduce:**
Open my test project. Experiment with resolution and high dpi scaling in Windows (and other OS's).
Also experiment with toggling "Allow HiDPI" in ProjectSettings.

**Minimal reproduction project:**
[FPS-test.zip](https://github.com/godotengine/godot/files/4244728/FPS-test.zip)

Edit: changed a picture to correct one.

**Comment by Calinou** [comment]
Letting the engine scale the viewport will always be slower than switching the desktop resolution, but it's far more convenient and less troublesome down the road. The arguments in favor of it also apply to things like color correction shaders being preferred over hardware gamma.

See #24720 for details.

**Comment by danilw** [comment]
@fossegutten 
I made resolution change(can set any even 64*64)(press Esc-Settings-set Resolutinon autodetect) in [this project (itch.io link)](https://danilw.itch.io/e-ani) link to source code look on that page.
Changing resolution to low decrease GPU usage 2x or more, like on my GPU on 1080p and Shadows On I have 80% GPU usage, on 720p (by changing resolution in Settings)

so on your project, reason why you do not see any change in GPU usage is because - you scene way too simple, so rescaling resolution(from Native) cost GPU same as render this single cube
if you add 500k particles and enable shadows, then youl see that GPU usage go down on changing render resolution.

**Comment by fossegutten** [comment]
> Anyway, I expect the performance difference to be significantly lower in a more complex project. Feel free to test [godot-sponza](https://github.com/Calinou/godot-sponza) to confirm this.

This is a great project for benchmark by the way, thanks! Will use as a reference for my own games :)

I tested the sponza demo with a viewport size of 1280 x 720 pixels, on a 4k screen. This scales perfectly to 4k with a 300% hi dpi scaling in windows. Fps drops from ~150 FPS to ~100 FPS, when enabling the "Allow HiDPI". Not as dramatic change as my simple test project. However, I still think this is a significant FPS drop, when the visual result is identical.

Hardware:
Intel I7-9750H 
Nvidia GeForce GTX 1650 mobile

**Comment by Calinou** [comment]
@clayjohn Is there actually a way to fix this, or should we just document it?

**Comment by clayjohn** [comment]
@Calinou I agree with @danilw I doubt this is an actual issue with rendering. Many things contribute to performance beyond pixel fill-rate. On such simple demos (even sponza is overly simple) fill rate will not limit your FPS. Accordingly, the performance metrics here are of very little value. What we would need is GPU timing metrics (which are available in Master). My guess is that something in the HiDPI code (CPU side) is causing a bottleneck (maybe with the window drivers) that is resulting in the FPS changes. 

At this point though, there is not enough information to take any action. Raw FPS is a terrible way of measuring performance, and such a simplistic demo tells doesn't assist us.

**Comment by Calinou** [comment]
If anyone has spare time, feel free to try comparing Godot's results with other games that feature some kind of viewport scaling. This way, we can determine whether this is something we can actually solve. If not, we'll just document this limitation.

In both cases, make sure V-Sync is disabled in the game's settings and your graphics driver.

## [Tesseract](http://tesseract.gg/)

Uses OpenGL 3.3-4.3 and deferred rendering. SVN build recommended (but the stable version also supports this).

### Viewport scaling

- Run Tesseract. Press <kbd>T</kbd>, enter `/map complex` into the chat box then press <kbd>Enter</kbd>.
- Press <kbd>T</kbd> then enter `/gscale 50` to lower the rendering resolution (this doesn't affect 2D elements).
- Use <kbd>W/A/S/D</kbd> to walk into a spot where you can see most of the level. Look at your FPS in the bottom-right corner and write it down.
- Move into a spot in front of a wall and look towards the wall. This simulates a scene with a lower load on the GPU and CPU. Look at your FPS in the bottom-right corner and write it down.
- Press <kbd>T</kbd> then enter `/gscale 100` to restore the origial rendering resolution.
- Quit the game. Change your desktop resolution to half of your native monitor's resolution (e.g. 1280×720 if you use a 2560×1440 monitor).
- Run the game again, follow the same instructions but **do not run the `/gscale` commands this time**. Write down your FPS in both scenarios again. Make sure to use the exact same positions and angles in the map for testing!

## [Xonotic](https://xonotic.org/)

Uses OpenGL 2.1-3.3 and forward rendering. Stable release recommended. `master` is unstable as of writing.

- Run Xonotic. Press <kbd>Shift + Escape</kbd>, enter `showfps 1; map xoylent` into the console then press <kbd>Enter</kbd>.
- Press <kbd>Shift + Escape</kbd> (if the console has closed) and enter `r_viewscale 0.5` into the console. Like Tesseract, this doesn't affect 2D elements.
- Use <kbd>W/A/S/D</kbd> to walk into a spot where you can see most of the level. Look at your FPS in the bottom-right corner and write it down.
- Move into a spot in front of a wall and look towards the wall. This simulates a scene with a lower load on the GPU and CPU. Look at your FPS in the bottom-right corner and write it down.
- Press <kbd>Shift + Escape</kbd> then enter `r_viewscale 1` to restore the origial rendering resolution.
- Quit the game. Change your desktop resolution to half of your native monitor's resolution (e.g. 1280×720 if you use a 2560×1440 monitor).
- Run the game again, follow the same instructions but **do not run the `r_viewscale` commands this time**. Write down your FPS in both scenarios again. Make sure to use the exact same positions and angles in the map for testing!

**Comment by Calinou** [comment]
I've done some testing in Tesseract (4K laptop with Windows 10 and Intel HD 620) and can confirm this isn't a Godot-specific issue.

Look at the FPS numbers in the bottom-right corner:

## 2160p native (native display resolution)

![2160p_native](https://user-images.githubusercontent.com/180032/97599023-dc6a9d80-1a07-11eb-9d2c-d89a916b5c66.png)

## 1080p native (display resolution manually changed)

![1080p_native](https://user-images.githubusercontent.com/180032/97599014-daa0da00-1a07-11eb-8b93-2643c20a280b.png)

## 1080p on 2160p (`/screenres 1920 1080` in-game or `/gscale 50`)

![1080p_on_2160p_hidpi](https://user-images.githubusercontent.com/180032/97599020-dbd20700-1a07-11eb-8591-587e29a1643b.png)

**Comment by Calinou** [comment]
Closing, as this isn't a Godot-specific issue and is now [documented](https://github.com/Calinou/godot-docs/blob/004654a1145ee1b1792ba296be880ad47c1f52d8/tutorials/rendering/multiple_resolutions.rst#L72-L85).
