### ISSUE TITLE
[GodotEditor 3.2 official release][BUG]Tabs->TabCloseDisplayPolicy->ShowAlways doesn't work

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#36505]
**Godot version: 3.2 stable official**

**OS/device including version: Windows10, i9, NVidia GeForce GTX 1060**

**Issue description: ShowAlways option Tabs node type doesn't work. The same as "Show Active Only"**

**Steps to reproduce:
1) Create new project
2) Create one scene as an User Interface
3) Add a TabContainer Node
2) Add a few Tabs as children of TabContainer
3) Set either "ShowAlways" or "Show Active Only" in the "Tab Close Display Policy" property of all Tabs children
4) Observe that there are no close buttons on the tabs (any of them)
5) Run the project and see observer again step 4)**

**Minimal reproduction project: https://github.com/radubolovan/TabContainerExample**

**Comment by BigRed-118** [comment]
Looks like this has been reported before, #33649, and there was more discussion before that here #9773

**Comment by radubolovan** [comment]
> Looks like this has been reported before, #33649, and there was more discussion before that here #9773

This is a duplicate then. Closing.
