### ISSUE TITLE
ConcavePolygonShape2D crash when empty

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#3650]
Steps to reproduce:

1. Create a CollisionShape2D with a ConcaveShape2D and edit its segments
2. Set the _Size_ to some value greater than 0, and then set it back to 0. Godot will crash.

Related to #3169, which mentioned ConcavePolygonShape (not 2D). Possible fix ([servers/physics_2d/shape_2d_sw.cpp](https://github.com/godotengine/godot/blob/master/servers/physics_2d/shape_2d_sw.cpp#L967)):

``` diff

@@ -979,6 +979,11 @@ void ConcavePolygonShape2DSW::set_data(const Variant& p_data) {
 
 		DVector<Vector2> p2arr = p_data;
 		int len = p2arr.size();
+		if (len==0) {
+			configure(aabb); // aabb == Rect2()
+		}
 		DVector<Vector2>::Read arr = p2arr.read();
 
 
```

However, changing the _Size_ from 0 to 2 also causes a crash. The reason is that _pointmap_ is empty [at this point](https://github.com/godotengine/godot/blob/master/servers/physics_2d/shape_2d_sw.cpp#L1015). I thought of:

``` diff
@@ -1010,6 +1010,11 @@ void ConcavePolygonShape2DSW::set_data(const Variant& p_data) {
 			s.points[1]=idx_p2;
 			segments.push_back(s);
 		}
+		
+		if (pointmap.size()==0) {
+			configure(aabb); // aabb == Rect2()
+			return;
+		}
 
 		points.resize(pointmap.size());
 		aabb.pos=pointmap.front()->key();
```

But this just resets the Size to 0. When settling the Size to 1, the value is automatically changed to 2, and no crash occurs...

**Comment by akien-mga** [comment]
@neikeq If you want to continue digging and find the good fix, that would be awesome :D
