### ISSUE TITLE
ERROR: call_build: An EditorPlugin build callback failed. (editor/editor_node.cpp:5268)

### ISSUE THREAD

**Issue by MSaIim** [godotengine/godot#36517]
**Godot version:** 3.2 stable mono 64bit

**OS/device including version:** Windows 10 v1909

**Issue description:** Started a new project and tried to build. I  receive the following error:

```
"C:\Games\Godot\Games\Outburst\Outburst.sln" (Build target) (1) ->
"C:\Games\Godot\Games\Outburst\Outburst.csproj" (default target) (2) ->
(GetReferenceAssemblyPaths target) ->
  C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1193,5):
error MSB3644: The reference assemblies for .NETFramework,Version=v4.7 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
 [C:\Games\Godot\Games\Outburst\Outburst.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.59
ERROR: call_build: An EditorPlugin build callback failed.
   At: editor/editor_node.cpp:5268
```
I downloaded the Visual Build tools and the Mono SDK.  I have .NETFramework 4.7 and .NETCore 3.1. I tried to switch the build tool from MSBuild(VS Build Tool) to MSBuild(Mono), but I still get the same error.

**Steps to reproduce:** Not sure

**Minimal reproduction project:** Any new project

**Comment by akien-mga** [comment]
> I have .NETFramework 4.7

Are you 100% sure that it's 4.7 and not 4.7.2? It needs to be that exact version (4.7).

**Comment by MSaIim** [comment]
Oh, thank you very much! I had version 4.7.1.

**Comment by rulz-coder** [comment]
Hey, I've same probleme. How did you fix?

**Comment by MSaIim** [comment]
@rulz-coder In the Visual Studio Installer, uncheck the .NETFramework versions you don't want and check version 4.7 to install. It only worked when I had only version 4.7 on my system. 

I believe you can also download it from here: https://www.microsoft.com/en-us/download/details.aspx?id=55167

**Comment by rulz-coder** [comment]
@MSaIim Ialready download 4.7 version.
