### ISSUE TITLE
shader texscreen incorrectly documented

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#3651]
In the documentation it says `color texscreen( vec2 )` but it should be `vec3 texscreen(vec2)` as this function returns a `vec3`. I think it should actually return `color`, even tho' alpha will always be `1`. Makes things easier to work with it since you're looking for `color` and converting the `vec3` to it anyway...

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot-docs/commit/bfd4549c807103abed4d516c5b6b7a806ae45084
