### ISSUE TITLE
HBoxContainer and VBoxContainer make the last node too big (with "Expand" size flag)

### ISSUE THREAD

**Issue by ShawkMusic** [godotengine/godot#36522]
**Godot version:** 3.2.stable

**OS/device including version:** Windows 10

**Issue description:** HBoxContainer and VBoxContainer make the last node too big

**Steps to reproduce:**

1. Add a VBoxContainer (it also happens with HBoxContainer but I'm going to describe it for V for the sake of simplicity.)
![image](https://user-images.githubusercontent.com/48574225/75207047-b2a8fa80-5745-11ea-9bb2-fa2cda04b765.png)

2. Set the VBoxContainer's size to (50, 1000)
![image](https://user-images.githubusercontent.com/48574225/75207067-c0f71680-5745-11ea-8a9f-993962e19306.png)

3. Add a ColorRect node as a child (it can be almost any control node, the ColorRect just helps to see it better)
![image](https://user-images.githubusercontent.com/48574225/75207086-c81e2480-5745-11ea-99c4-08a0670ed390.png)

4. Go on the ColorRect's size flags and check "Expand" on Vertical
![image](https://user-images.githubusercontent.com/48574225/75207122-dec47b80-5745-11ea-83fe-3b122ebe6dbc.png)

5. Duplicate the ColorRect until there are 60 of them. (It seems the more you add, the more noticeable it becomes, but let's stick to 60 for now). You will notice the last node is much bigger than its siblings, even though they should all be the same size since they all have the "Expand" flag. 
![image](https://user-images.githubusercontent.com/48574225/75207164-f69bff80-5745-11ea-901b-34c38a369ec8.png)

Observation: if you drag the VBoxContainer's bottom handle, as it goes up and gets smaller it seems to only update all the node's sizes once the lowest node shrinks to the same size as all the others, the it squishes all the nodes back and makes the lowest one too big again and repeats.
(Animated GIF)
![2020-02-24-20-44-10](https://user-images.githubusercontent.com/48574225/75207751-a160ed80-5747-11ea-86fe-2eaf221ee437.gif)

**Minimal reproduction project:**
[vboxcontainer_bug.zip](https://github.com/godotengine/godot/files/4247712/vboxcontainer_bug.zip)

**Comment by groud** [comment]
Hmm, this is likely due to the fact the container has to split it's available size on all its children, while always using integers numbers. So there is always space left if the division is not perfect, which is apparently given to the last child.

I guess the solution might be to spread this space evenly over all expanding children.

**Comment by pycbouh** [comment]
@groud But why is it using integers in the first place? What you suggest is equal to using floating point numbers to begin with, but divided into two steps. What is the inherent limitation?

**Comment by groud** [comment]
The size of control nodes uses Integers.This kind of make sense in a world of pixels.
We could find a way to have float values for Control's position and size, but I am not sure we can ensure they are going to render properly with such changes. We don't want Controls to look blurry.

**Comment by name-here** [comment]
One way to set lengths while keeping error even would be to keep a tally of total length, something like the following:

For each block (go from one end to the other in order):

1. set  length = (container length) * index / (number of control nodes in it) – (length tally)
2. add length to the length tally

**Comment by DanielZTing** [comment]
OK, I actually kinda depend on this working correctly in my game, so I've been taking a look at the relevant code.

I think the cause is line 123 of `scene/gui/box_container.cpp`:

```cpp
int final_pixel_size = stretch_avail * c->get_stretch_ratio() / stretch_ratio_total;
```

Let's say `stretch_avail` is 599 and there's 60 ColorRects equally expanded, ignoring separation for simplicity's sake. `final_pixel_size` would be floor(599 / 60) = 9, but 59 * 9 = 531. If my calculations are right, that leaves 68 pixels for the last ColorRect! That's also why adding more ColorRects exacerbates the problem: the "error multiplier" is greater.

If nobody else is working on a better implementation, I will try to make it so the size calculations use floats all the way until the final rendering step, then round to the nearest integer.

**Comment by ShawkMusic** [comment]
> OK, I actually kinda depend on this working correctly in my game, so I've been taking a look at the relevant code.
> 
> I think the cause is line 123 of `scene/gui/box_container.cpp`:
> 
> ```c++
> int final_pixel_size = stretch_avail * c->get_stretch_ratio() / stretch_ratio_total;
> ```
> 
> Let's say `stretch_avail` is 599 and there's 60 ColorRects equally expanded, ignoring separation for simplicity's sake. `final_pixel_size` would be floor(599 / 60) = 9, but 59 * 9 = 531. If my calculations are right, that leaves 68 pixels for the last ColorRect! That's also why adding more ColorRects exacerbates the problem: the "error multiplier" is greater.
> 
> If nobody else is working on a better implementation, I will try to make it so the size calculations use floats all the way until the final rendering step, then round to the nearest integer. But one side effect of this is that the ColorRects and the separation between them may differ in size plus-or-minus 1 pixel. So there will be a noticeable loss of "pixel perfection" if the ColorRects/separation is only a few pixels in size. I don't know if this can be avoided but I think it's preferable to what we have now.

I feel like that's the best solution we can get and I don't think anyone else is working on this, considering you're the first person to reply in the past 4 months and I'm not familiar with changing Godot's source code. If you could make that pull request, I would be very grateful!
