### ISSUE TITLE
Editor Crash when setting subscene with Control root as a placeholder

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3652]
Tested on Ubuntu in 595de75641e0fae1f4e6924530da7a3308371a07 build.

1. Open new scene. 
2. Put Control node inside.
3. Save scene as "subscene.tscn"
4. Open new scene, put "Node" as a root. 
5. Save the scene as "main.tscn"
6. Instance "subscene.tscn" into main scene.
7. In inspector set subscene to "load as placeholder"
8. Do "ctrl + s" to save main scene.
9. Editor will crash.

Sample project in which you need to set subscene as placeholder and save: 
[ControlPlaceholderCrash.zip](https://github.com/godotengine/godot/files/125262/ControlPlaceholderCrash.zip)
Console log from crash:
```
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:128.
```

**Comment by nunodonato** [comment]
Tried it now from the current git version, can't replicate. Saves ok without crashing. Can you double check?

**Comment by kubecz3k** [comment]
@nunodonato Thanks for effort.. unfortunately in current 16b0cf8bcbaacb02533e8f334b30931139b6d6dd build the problem is still there. I recorded small vid on how you can reproduce it with project provided in first post: https://www.youtube.com/watch?v=yxW5zCX5TJ4&feature=youtu.be
Also updated info in first post (added console log)

**Comment by vnen** [comment]
I can confirm this with the test project project provided. If I set the control as placeholder and save, Godot just closes.

**Comment by akien-mga** [comment]
Just for my culture, what does this "Load as placeholder" option do?

**Comment by kubecz3k** [comment]
@akien-mga if something is a placeholder it's not loaded when the scene is created/instanced, you need to load it manually from the code at time when you need it (it's handy in some scenarios).

**Comment by reduz** [comment]
seems placeholder support was missing from tscn, it should now work

**Comment by kubecz3k** [comment]
It's working now, this had to be it, thanks!
