### ISSUE TITLE
Can not statically type custom resource

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#36535]
**Godot version:**
3.2

**OS/device including version:**
Win 10

**Issue description:**
`var _time_multiplier: =  preload("res://Core/BulletTime/BulletTimeMultiplier.tres")`

Works, and correctly infers the type.

`var _time_multiplier: BulletTimeMultiplier =  preload("res://Core/BulletTime/BulletTimeMultiplier.tres")`

Causes a Cyclic/Script Error.

BulletTimeMultiplier looks like this:

```
extends Resource
class_name BulletTimeMultiplier

export(float, 0.0, 2.0) var multiplier: float = BulletTimeConfig.DEFAULT_MULTIPLIER setget set_multiplier


func set_multiplier(new_value: float) -> void:
	multiplier = clamp(new_value, 0.0, 2.0)
```

BulletTimeConfig.DEFAULT_MULTIPLIER is just a constant float.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/18, as feature proposals are now tracked in the Godot proposals repository;
