### ISSUE TITLE
Expanding MarginContainer with RichTextLabel inside VBoxContainer breaks from v3.1.1 to v3.2.0

### ISSUE THREAD

**Issue by naturally-intelligent** [godotengine/godot#36539]
**Godot version:**
v3.2.0

**Issue description:**
In Godot 3.1.1 and below, creating a RichTextLabel inside a VBoxContainer (text is inside MarginContainers) that use an expanding animation, don't show up at all in 3.2.0.  Have also tried 3.2.1 RC1 and same issue.  I thought I'd wait for the RC to make sure.

Now, I'm not sure if I was using Godot 3.1 improperly, and now what I did has become improper in 3.2, or if 3.2 has broken.  Either way, need to know how to resolve, as this makes 3.2 unusable for my project!

**Steps to reproduce:**
Use minimum viable project included in issue.  Run with Godot 3.1, then with Godot 3.2, and you'll find the text does not show.

**Minimal reproduction project:**
[dialog320.zip](https://github.com/godotengine/godot/files/4251658/dialog320.zip)

**Comment by Calinou** [comment]
It seems you meant RichTextLabel instead of TextLabel, so I corrected the issue title.

**Comment by naturally-intelligent** [comment]
Thanks for clarifying the issue and looking into it Calinou.  It's very possible it's the same issue as #4055, I will do a some digging!

**Comment by naturally-intelligent** [comment]
So far, toying with min_size hasn't helped.  But, I appear to have solved the issue though!  :)

Related to this issue #19948, where setting the height/width before adding the Control node to the scene, is ignored.  Setting these _afterwards_ does make things work as expected.  So far so good, I'll test a bit more to make sure!!

**Comment by naturally-intelligent** [comment]
Everything works great now, and as a bonus, same solution works in 3.1 as well.  

[dialog321-fixed.zip](https://github.com/godotengine/godot/files/4253379/dialog321-fixed.zip)

The problem was calling **set_size()** functions and interpolating **rect_size** property before calling **add_child()**
