### ISSUE TITLE
Condition ' len < 4 ' is true. returned: ERR_INVALID_DATA

### ISSUE THREAD

**Issue by jefvaia** [godotengine/godot#36554]
**Godot version:**
Godot 3.1.2 for Windows 64-bit

**OS/device including version:**
Windows 10 laptop with nvidia gt540m

**Issue description:**
This is the error I am having:
`E 0:00:45:0860   Condition ' len < 4 ' is true. returned: ERR_INVALID_DATA
  <C Source>     core/io/marshalls.cpp:110 @ decode_variant()
  <Stack Trace>  Panel.gd:95 @ _process()
`
sometimes it takes longer for the error to come
when I build the project with debug and run the exe file, it still gives me this error.
I think it has to do something with the TCP connection with my game server

**Steps to reproduce:**
I have no idea how I got this error.

**Minimal reproduction project:**
This is the full project with node js server included
[Project.zip](https://github.com/godotengine/godot/files/4254836/Project.zip)

**Comment by clayjohn** [comment]
Can you try the project in the newer 3.2 releases? either 3.2 or 3.2.1?

**Comment by jefvaia** [comment]
I think that was the problem. I tried the project with godot 3.2 and it didn't gave me an error.

Thank you!

**Comment by VanDeiMin** [comment]
I experienced this error  today for the first time. It happend when I switched from Remote scene tree dock to Local.  "Synchronize scene/script changes" were enabled.

**Comment by mooneatstar** [comment]
I'm using Godot 4.3 and this happens to me when I open remote scene tree to have a look:

  core/io/marshalls.cpp:117 - Condition "len < 4" is true. Returning: ERR_INVALID_DATA
  core/debugger/remote_debugger_peer.cpp:145 - Condition "read != in_pos || err != OK" is true. Continuing.
  core/debugger/remote_debugger_peer.cpp:134 - Condition "read != 4 || err != OK || size > (uint32_t)in_buf.size()" is true. Continuing.

My specific case is that I have thousands of nodes in total, and the main node has a really large dictionary which contains hundrends of dictionaries where each of them contain hundreds of nodes (I guess it's the scale of the tree, or stacked dictionaries to blame)

**Comment by jefvaia** [comment]
I vaguely remember this issue I had, since it is 4 years ago. It had to do with me trying to send a lot of tcp packets to a node js server instead of combining the data into one packet and sending that thing. I don't know your specific situation and I don't know about this problem in godot 4.3, since the version I was using at the time I wrote this issue was 3.1.2
If you wish to receive fitting help, maybe open a new issue and specify your problem there. This is an issue opened 4 years ago after all and you'll have more help that way.

**Comment by rbaker87** [comment]
> I'm using Godot 4.3 and this happens to me when I open remote scene tree to have a look:
> 
> core/io/marshalls.cpp:117 - Condition "len < 4" is true. Returning: ERR_INVALID_DATA core/debugger/remote_debugger_peer.cpp:145 - Condition "read != in_pos || err != OK" is true. Continuing. core/debugger/remote_debugger_peer.cpp:134 - Condition "read != 4 || err != OK || size > (uint32_t)in_buf.size()" is true. Continuing.
> 
> My specific case is that I have thousands of nodes in total, and the main node has a really large dictionary which contains hundrends of dictionaries where each of them contain hundreds of nodes (I guess it's the scale of the tree, or stacked dictionaries to blame)

I have a similar situation and just received this error for the first time today. I don't know yet if I can reproduce it (it only happened after playing the game in the editor for nearly 20 minutes), but I think I can safely say that it isn't related to overly large dictionaries/data-structures. Nothing I do is storing anywhere near that much in a single structure, but I do have thousands of nodes in the scene tree. Oddly enough - this didn't seem to really break anything while it was occurring. I just got hundreds/thousands of errors each second until I restarted.

**Comment by HyperGameDev** [comment]
This just happened to me in 4.4, and it turned out to be related to an array that was getting thousands of lines longer every frame. Once that array was removed, this exact error went away.

For others experiencing it, consider looking for an array or dictionary (or something like that) that's overflowing.
