### ISSUE TITLE
Failed to build Godot engine from Source (MSVC Version)

### ISSUE THREAD

**Issue by sps014** [godotengine/godot#36565]
## I have the latest  visual studio 2019 Preview installed.
When I use ```scons platform=windows tools=yes target=release_debug vsproj=yes```
tried various solutions but none of them worked.

# Here is the error 
scons: Reading SConscript files ...
Configuring for Windows: target=release_debug, bits=default
Found MSVC compiler: amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
KeyError: 'MSVC_VERSION':
  File "C:\Users\shive\Desktop\Test\godot\SConstruct", line 319:
    detect.configure(env)
  File "./platform/windows\detect.py", line 404:
    configure_msvc(env, manual_msvc_config)
  File "./platform/windows\detect.py", line 201:
    if int(env['MSVC_VERSION'].split('.')[0]) >= 14: #vs2015 and later
  File "C:\Users\shive\AppData\Local\Programs\Python\Python38-32\scons\SCons\Environment.py", line 405:
    return self._dict[key]

## Pardon if it is a duplicate issue since none of the solutions I checked worked for me.

**Comment by Calinou** [comment]
It seems reinstalling the latest version of Visual Studio should solve the issue, see https://github.com/godotengine/godot/issues/35446. Make sure to check the C++ workflow during the installation.

**Comment by sps014** [comment]
#### Reinstalling fixed 1st issue but now I can't generate vsproj

## Error

scons: Reading SConscript files ...
Automatically detected platform: windows
Configuring for Windows: target=debug, bits=default
Using MinGW
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
UnsupportedVersion: Unknown version None:
  File "C:\Users\shive\Desktop\Test\godot\SConstruct", line 572:
    methods.generate_vs_project(env, GetOption("num_jobs"))
  File "C:\Users\shive\Desktop\Test\godot\methods.py", line 452:
    batch_file = find_visual_c_batch_file(env)
  File "C:\Users\shive\Desktop\Test\godot\methods.py", line 438:
    return find_batch_file(env, version, host_platform, target_platform)[0]
  File "C:\Users\shive\AppData\Local\Programs\Python\Python38-32\scons\SCons\Tool\MSCommon\vc.py", line 407:
    pdir = find_vc_pdir(msvc_version)
  File "C:\Users\shive\AppData\Local\Programs\Python\Python38-32\scons\SCons\Tool\MSCommon\vc.py", line 368:
    raise UnsupportedVersion("Unknown version %s" % msvc_version)


### Any help will be appreciated.

**Comment by madmiraal** [comment]
It still looks like you don't have Visual Studio installed properly. From your log above:
> Using MinGW

It's found the `MinGW` compiler and it's compiling using that, but `vsproj=yes` requires Visual Studio to be installed. Note: The default is to use Visual Studio. It will only use `MinGW` if it can't find Visual Studio or you specifiy `use_mingw=yes`.

I would suggest checking out Microsoft's [Troubleshoot Visual Studio installation and upgrade issues](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-installation-issues?view=vs-2019).

**Comment by aaronfranke** [comment]
@sps014 Are you still experiencing issues? This seems like a configuration issue on your end, not a bug with Godot. However, it is possible that we could update the documentation to avoid whatever problem you're experiencing.

**Comment by sps014** [comment]
I forgot to close this issue, was able to fix by reinstalling VS.
