### ISSUE TITLE
Expected behavior on macOS?

### ISSUE THREAD

**Issue by blueberrymountains** [godotengine/godot#36577]
When attempting to run Godot, macOS would alert me the file wasn't signed etc.; being cautious, I eventually ran Godot.app through VirusTotal. No issues found. I came across some things which I found puzzling, though — wondering if someone would help clarify.

According to the 'Behaviors' tab on VirusTotal, Godot accesses things like:

`/Library/Keychains/login.keychain-db\ ` 

...and writes to things like:

`/System/Library/PrivateFrameworks/login.framework/login`

Are these the expected and necessary behaviors for Godot to run on macOS? (If my questions should be directed to another forum, please let me know.)

Thank you very much for your time.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
`/System` is covered by system integrity protection, it's impossible to write there even with the root access, probably library loading is reported as write for some reason.
`login.framework` and other private frameworks are loaded to almost every app on macOS.

**Comment by blueberrymountains** [comment]
Thanks for your responses @bruvzg and @Calinou. 

Are there any plans to move towards signing & notarizing Godot for Mac?

**Comment by Calinou** [comment]
@blueberrymountains Yes, see #11984. I doubt it's going to happen anytime soon, judging how complex the process now is.

**Comment by akien-mga** [comment]
Closing as it behaves as expected / as best we can reasonably do with Apple's developer-adverse policies.

**Comment by blueberrymountains** [comment]
@Calinou Thanks again. Is signing and notarizing significantly more complex for Godot than for a project like Krita? I was reading about how Krita was notarized specifically, and it was a hassle, but sounded doable from their blog post: https://krita.org/en/item/first-notarized-macos-build-of-krita/

**Comment by akien-mga** [comment]
It's definitely possible, but I don't want to have to send every single build we make to Apple for notarizing. It's a pointless step and would put a needless delay on all our releases.
