### ISSUE TITLE
Xbox Elite Controller Mappings

### ISSUE THREAD

**Issue by KyleFromOhio** [godotengine/godot#36571]
**Godot version:**
3.2

**OS/device including version:**
Mac OSX Catalina 10.15.2

**Issue description:**
Mapping of my Xbox Elite controller was all funky until I added the following to my project. Godot was reporting GUID as the first one while other tools outside Godot reporting as the second one. Not sure which one made it work but works perfect now using the mappngs below and the latest alpha driver (because of Catalina) at https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.5

xbox elite one mappings

Input.add_joy_mapping("5e04000000000000e302000000000000,Xbox One Elite Wired Controller,platform:Mac OS X,a:b0,b:b1,x:b2,y:b3,back:b9,guide:b10,start:b8,leftstick:b6,rightstick:b7,leftshoulder:b4,rightshoulder:b5,dpup:b11,dpdown:b12,dpleft:b13,dpright:b14,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,", true)

Input.add_joy_mapping("030000005e040000e302000000000000,Xbox One Elite Wired Controller,platform:Mac OS X,a:b0,b:b1,x:b2,y:b3,back:b9,guide:b10,start:b8,leftstick:b6,rightstick:b7,leftshoulder:b4,rightshoulder:b5,dpup:b11,dpdown:b12,dpleft:b13,dpright:b14,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,", true)

**Comment by aaronfranke** [comment]
Normally these things would be implemented upstream on the SDL game controller DB repo, but that repo has recently been DMCA claimed, so we can't use that for now. This issue will most likely have to wait until that issue is resolved.

**Comment by Zireael07** [comment]
Seriously? DMCA claim on a game controller database??

**Comment by aaronfranke** [comment]
@Zireael07 Yes, last week https://github.com/github/dmca/blob/master/2020/02/2020-02-19-SDL-GameController.md

@akien-mga has an up-to-date fork with the copyright issues resolved: https://github.com/akien-mga/SDL_GameControllerDB

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
