### ISSUE TITLE
Multi-threaded rendering and Fullscreen causing screen stutter/lag.

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [godotengine/godot#36576]
**Godot version:** 3.2, 3.2.1.rc1

**OS/device including version:** Windows 8.1 64 bits

**Issue description:** Selecting Multi-threaded thread model in project settings makes the entire screen stutter when in fullscreen, showing a previous or following frame. This did not happen in previous versions. It doesn't show any sort of error. Using VSync with compositor doesn't make any difference.

I can't record it with OBS, so I think more load in the processor, the less it happens.

**Steps to reproduce:** 
Project Settings > Rendering > Threads > Thread Model: Multi-threaded.

An object has to be moving for it to be noticeable.

**Minimal reproduction project:**

[Minimal Reproduction.zip](https://github.com/godotengine/godot/files/4258113/Minimal.Reproduction.zip)

**Comment by smix8** [comment]
Tried your test project in both Godot versions cause I thought it might relate to my own issue with Godot random thread stuttering on windows. Your test project runs buttersmooth for me on win10. Selecting single-threaded or multi-threaded and windowed or fullscreen mode makes no difference so I can't confirm this issue. Tested with GTX980Ti and i7-9700k on freshly updated windows/drivers.

**Comment by Lilith-In-Starlight** [comment]
Forgot to put my OS version, my bad. The OS is probably why the test project works perfectly on your end.

**Comment by Lilith-In-Starlight** [comment]
Also, forgot to specify that to set fullscreen in the project you use the enter key. I don't know if it happens when you set it from project settings

**Comment by smix8** [comment]
If I spam-switch between fullscreen and windowed with enter key it runs fine immediately without stuttering. Can not test on a win8.1 system.

**Comment by Lilith-In-Starlight** [comment]
Then I guess it's a W8.1 thing. The minimal reproduction project I sent is actually the most minimal I could make. In bigger projects with more moving parts, the entire screen lags behind. Usually just horizontal sections of it. Sometimes random rectangular "chunks" too. 

These descriptions may be wrong tho, they're too fast for me to notice them.

**Comment by Lilith-In-Starlight** [comment]
Accidentally closed it, oops

**Comment by Lilith-In-Starlight** [comment]
It's fixed in 3.2.1.
