### ISSUE TITLE
Problem while compiling Godot source with some extra modules

### ISSUE THREAD

**Issue by Yashwanth-CN** [godotengine/godot#36589]
Hi 

I was trying to compile Godot with MySQL and SQLite modules, but it's throwing some error listed below, please give me a solution regarding this because I'm new to Godot.

$scons
scons: Reading SConscript files ...
Automatically detected platform: windows
Configuring for Windows: target=debug, bits=default
Found MSVC version 14.2, arch amd64, bits=64
TypeError: can_build() takes 1 positional argument but 2 were given:
  File "C:\godot\SConstruct", line 475:
    if config.can_build(env, selected_platform):

Thanks.

**Comment by akien-mga** [comment]
Please fill the export template. You're not giving very important information such as the Godot version you try to compile.

One or more of the modules you use is outdated and needs to be adapted to support Godot 3.0+. Godot 4.0 no longer supports the outdated `can_build()` method with a single argument.

**Comment by Yashwanth-CN** [comment]
I was using Godot master and module which I used for installation was "https://github.com/wowtomi/godot-mysql-module" and this module is in master version

**Comment by akien-mga** [comment]
That module was last updated in June 2018, so it's not compatible with Godot 3.1+.
