### ISSUE TITLE
ParticleSystem crashes Godot if Amount > Max

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3659]
If the 'amount' attribute in a particle system is equal or higher than the maximum (1024) Godot crashes instantly.
The inspector should not allow the user to input numbers higher than the maximum.

Affects 3d only, in 2D the inspector limits the number at 1024

**Comment by freemanfromgodotengine** [comment]
I can confirm that.
Godot quits with error

> ERROR: prepare: Condition ' p_system->amount<=0 || p_system->amount>=ParticleSystemSW::MAX_PARTICLES ' is true.
>    At: servers/visual/particle_system_sw.cpp:288.

**Comment by nunodonato** [comment]
@reduz can you confirm if I can fix this by limiting the number in the inspector to 1024? or is it really supposed to go higher than that?
