### ISSUE TITLE
Problem While Compiling Godot with MySQL Module

### ISSUE THREAD

**Issue by Yashwanth-CN** [godotengine/godot#36590]
**Godot version:  Master Version**

**OS/device including version: Windows 10**

**Issue description: Godot source code compilation problem**

Hi

I was trying to compile Godot with MySQL module, but it's throwing some error listed below, please give me a solution regarding this because I'm new to Godot.

$scons
scons: Reading SConscript files ...
Automatically detected platform: windows
Configuring for Windows: target=debug, bits=default
Found MSVC version 14.2, arch amd64, bits=64
TypeError: can_build() takes 1 positional argument but 2 were given:
File "C:\godot\SConstruct", line 475:
if config.can_build(env, selected_platform):

The module which I used for installation was "https://github.com/wowtomi/godot-mysql-module" and this module is in master version.

Thanks.

**Comment by Calinou** [comment]
Judging by its last commit date, the module is probably outdated and doesn't support Godot 3.1 or 3.2. Please report an issue on the [module's repository](https://github.com/wowtomi/godot-mysql-module/issues), not here.
