### ISSUE TITLE
No autocomplete for Transform2D

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#36609]
**Godot version:**

ed0f1940cbdbe470da85f446f315ee12897038a1

**Issue description:**

Some things are missing from the autocompletion of Transform2D, for example "origin" is not there for Transform2Ds.

**Steps to reproduce:**

Type `Transform2D.IDENTITY.ori` and hit ctrl+space. Origin is missing.

**Comment by KoBeWi** [comment]
I've noticed it on 3.2 stable too. It's like that even on `transform` property, you don't get `origin` autocompletion, only `get_origin()`.

**Comment by BigRed-118** [comment]
I rebuilt from ed0f194 and 3.2 stable, but I do not see those issues. I'm running on Windows.
![image](https://user-images.githubusercontent.com/52541536/75510307-23ebe600-59b0-11ea-9274-fb7b2c4486d8.png)
