### ISSUE TITLE
audio import error

### ISSUE THREAD

**Issue by mashmawsh** [godotengine/godot#36601]
im using latest godot and im unable to import audio as it shows me this error

 editor/editor_file_system.cpp:1783 - Error importing 'res://game bgm.ogg'

**Comment by Calinou** [comment]
We need more information to be able to diagnose this issue. Please include all information as requested in the bug report template: https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Chaosus** [comment]
Yeah, unfortunately, we can't help you without more information. Your file may probably be corrupted because OGG files seem correctly playing, for example: (https://file-examples.com/index.php/sample-audio-files/sample-ogg-download/). Closed.
