### ISSUE TITLE
Missing shortcuts in the Project Manager

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#36608]
**Godot version:**

ed0f1940cbdbe470da85f446f315ee12897038a1

**Issue description:**

No buttons have keyboard shortcuts in the Project Manager.

**Steps to reproduce:**

Open the Project Manager.

**Comment by akien-mga** [comment]
Why is that a problem? Which buttons should have shortcuts, and which key combinations should they use?

Please put more effort in proposals, and especially open them on the actual tracker created for that: https://github.com/godotengine/godot-proposals
