### ISSUE TITLE
Controls do not use default font from project's custom theme

### ISSUE THREAD

**Issue by AaronWizard** [godotengine/godot#36614]
**Godot version:** 3.2.stable.official

**OS/device including version:** macOS Catalina 10.15.3

**Issue description:**

I created a custom theme for my project, that has a custom default font. Any GUI text in my scenes however still has Godot's default font, both in the editor and at runtime.

**Steps to reproduce:**

1. Create and save a DynamicFont resource
1. Create and save a Theme resource
1. Set the theme's Default Font property to the font resource created in step 1
1. Under Project Settings, go to Gui > Theme and set the Custom Theme property to the theme created in step 2
1. Create and run a scene that has GUI controls with text

**Minimal reproduction project:**

[CustomThemeFontTest.zip](https://github.com/godotengine/godot/files/4264024/CustomThemeFontTest.zip)

**Comment by Calinou** [comment]
Does it work if you define the Theme resource on your scene's root Control node?

**Comment by AaronWizard** [comment]
Yes. If I assign the theme to the control itself the font works correctly.

Should I not use the custom theme project setting?

**Comment by atbigelow** [comment]
Was just fighting this for the last 30 minutes or so. Font was showing up in the theme preview, but never applying to any controls when running.

**Comment by MHillier98** [comment]
I've found the same issue - new user here, following HeartBeast's [Mobile RPG tutorial](https://www.youtube.com/watch?v=V6Zsg27n__Y&list=PL9FzW-m48fn1JgK_mavg7ym6nvchF9Yjb&index=3&t=0s).

Setting the "Custom Font" and then reloading also made it work for me, but I would have assumed that the custom theme's font should have applied.

**Comment by giulianob** [comment]
> 
> 
> Does it work if you define the Theme resource on your scene's root Control node? I generally advise doing this in every Control-based scene rather than relying on the custom theme project setting.

I actually wouldn't recommend this. I used the Godot editor's theme as a starting point and it ended up completely crashing the editor when I had it assigned manually. The editor would just get slower and slower. So be very careful it seems there's some issue if you assign it to every control.

**Comment by Calinou** [comment]
@giulianob This is because the editor theme contains lots of resources that will be serialized as Base64 (such as icons) once you convert it to a project theme. I think we should remove that option entirely or severely discourage it.

**Comment by giuliano-barberi-tf** [comment]
> @giulianob This is because the editor theme contains lots of resources that will be serialized as Base64 (such as icons) once you convert it to a project theme. I think we should remove that option entirely or severely discourage it. If you plan to use it, at the very least, you should save it as a `.res` file instead of a `.tres` file (or manually remove the built-in icons/save them as external resources).
> 
> See also #33902.

That makes sense. I ended up just writing a script to remove all the unwanted stuff including icons but still using it as a global theme. I like the global theme approach after doing both ways but wish fonts would work properly.

**Comment by giulianob** [comment]
@Calinou I did clear out all of the editor icons and saved it as a res file. Would you say it's now safe to set it on the controls directly or would you still expect me to run into issues where it freezes the editor?

**Comment by Calinou** [comment]
@giulianob It should be safe to use in this case.

**Comment by RabbitB** [comment]
> I think we should remove that option entirely or severely discourage it. If you plan to use it, at the very least, you should save it as a `.res` file instead of a `.tres` file (or manually remove the built-in icons/save them as external resources).

Please do not remove this option; I create a lot of small utilities, and this is basically the only way I have of making a quick, decent looking and usable theme. I make some quick changes to the editor, save it as a theme and I'm ready to go. I don't have the time to spend hours on this for every minor project.

If it's a serious issue, please consider adding an additional dialog when creating from an editor theme, that allows you to quickly select only the theme elements you actually need (plus an "all" button if you truly need a full theme layout.)

**Comment by pycbouh** [comment]
Is this still an issue on master after https://github.com/godotengine/godot/pull/47544? I've improved theme propagation including better recognition of styles from the project and the default themes while working on it.

**Comment by MewPurPur** [comment]
Seems to still be an issue in Godot 3.4

**Comment by grimmtotal** [comment]
This is still an issue for me

**Comment by akien-mga** [comment]
Fixed by #55497.
