### ISSUE TITLE
cfprefsd process at 100% CPU usage

### ISSUE THREAD

**Issue by JosephHalter** [godotengine/godot#36616]
**Godot version:**
Godot 3.2.1 rc1

**OS/device including version:**
MacOS Catalina 10.15.3 (19D76)

**Issue description:**
cfprefsd process regularly jumps to 100%, sometimes just launching Godot is enough to cause it to happen, sometimes it happens while I'm using the UI, everything is unresponsive, the cfprefsd progress can't be closed even with `kill -9` and only restarting the computer is possible.

**Steps to reproduce:**
It happened to me the first time when I copied Godot 3.2.1.rc1.mono to the Applications folder then launched it. I tried uninstalling Godot entirely and starting it again. It doesn't happen all the time. But if I use Godot long enough (1h+) it always end up happening at some point.

I reverted to 3.2.stable.mono - I'm sending it so that it gets looked at before going from rc1 to the final version.

**Comment by bruvzg** [comment]
`cfprefsd` is responsible for user setting, it's probably too much stuff in Godot setting folder, AFAIK it's never cleaned automatically.

Try cleaning cache in `~/Library/Caches/Godot`, logs in `~/Library/Application Support/Godot/mono` and maybe project/app settings for unused projects in `~/Library/Application Support/Godot/projects` and `app_userdata`.

**Comment by JosephHalter** [comment]
Thank you @bruvzg for your very quick help, I tried following your suggestions but it's still happening. I deleted `~/Library/Caches/Godot` and `~/Library/Application Support/Godot` entirely, installed 3.2.1.rc1.mono from scratch again but right on launch it showed me this dialog:

<img width="451" alt="Screenshot 2020-02-27 at 22 34 57" src="https://user-images.githubusercontent.com/116534/75488946-8d202900-59b1-11ea-8356-417e357ae22a.png">

I entered the password but Godot got stuck anyway:

<img width="281" alt="Screenshot 2020-02-27 at 22 36 23" src="https://user-images.githubusercontent.com/116534/75489040-c8baf300-59b1-11ea-806e-85c18f648c28.png">

I had to restart my computer once again.

**Comment by JonathanTron** [comment]
I have the same issue, I narrowed it down to an issue when Mono crashes.

It happens with 3.2 and 3.2rc1.

**Comment by jzgenius** [comment]
same issue v3.2.1 by first launch Godot.
reboot macbook worked.

**Comment by 19PHOBOSS98** [comment]
I thought I was the only one:
https://github.com/godotengine/godot/issues/38454
