### ISSUE TITLE
The Better Collada addon puts all the code in one file, is this a good idea?

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#3661]
Noting the recent discussion elsewhere regarding the Collada situation with Blender, I took a quick look at the code for the Better Collada addon and found that much of the code is in a file nearly 2000 lines long. I'm not really sure if that is such a good idea for the following reasons...
- It becomes harder to maintain
- It becomes more prone to bugs
- It becomes more difficult to add functionality
- It's more difficult to find certain pieces of code

I think in a sense, it would really help the cause of pushing the new exporter if the code can at least, as a start, be split into different files where possible (so as to organize everything and make it easier to maintain/expand/fix). One example would be the common case of defining your functions in one file for use in another.

Just something to think about.

**Comment by Ace-Dragon** [comment]
By the way, I'm talking about this file here
https://github.com/godotengine/godot/blob/master/tools/export/blender25/io_scene_dae/export_dae.py

**Comment by akien-mga** [comment]
I don't have any particular opinion, but it doesn't seem to be an issue to me. At any rate, this should be discussed at https://github.com/godotengine/collada-exporter.
