### ISSUE TITLE
No undo for "Paste Params"

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#36610]
**Godot version:**

ed0f1940cbdbe470da85f446f315ee12897038a1

**Issue description:**

`Paste Params` in the inspector is not undoable.

**Steps to reproduce:**

Go to the inspector and click the options on the top right and select "Copy Params" and then "Copy Params". Then hit ctrl+z.

**Comment by theoway** [comment]
Is it required? Because there already appears a 'revert changes' icon for each property that has been changed.

**Comment by aaronfranke** [comment]
@theoway The use case is if the old params were not the default value. The revert button resets that value to its default value, not to the previous value.

**Comment by theoway** [comment]
@aaronfranke  Right. Thanks for the clarification. 
What will be the best way to implement it? Should we make the ctrl+z command functional for it or add an "undo" option in the options menu?
