### ISSUE TITLE
Filesystem can show duplicated subfolders after creating new folder

### ISSUE THREAD

**Issue by KioriSun** [godotengine/godot#3662]
Like the title says after doing that the contents of res appeared also, and in a strange fashion(as links? not sure) inside the new folder. and the res registered 2 folders.
After restarting everything was normal again. But this leads me to another issue, there isnt really an option to create a new folder, in the Filesystem window.

This was all using 2
![saved script and created new folder](https://cloud.githubusercontent.com/assets/10463922/12968825/53a92842-d05e-11e5-8127-09b4013833d4.png)
.0rc1 of course.

**Comment by kubecz3k** [comment]
Are you able to provide reproduction steps? Or maybe provide sample project in which it's easy to reproduce? Also let us know what is your system.

**Comment by bojidar-bg** [comment]
@kubecz3k I'm pretty sure I was able to reproduce this a few days ago, but I unable to do it on 285c400288e3a7ccb41d14b1751c88b09c1df294...

**Comment by KioriSun** [comment]
Sorry, i've tried, haven't been able to reproduce it. :/

The way i did it was simply, click on a node, click on the button at the top of the scene list, that creates a new script, create a new folder, save the new script in it.
And somehow that generated artifacts.

**Comment by bojidar-bg** [comment]
@kubecz3k @KioriSun ~ Ok, I was able to reproduce it on 285c400288e3a7ccb41d14b1751c88b09c1df294
1. Create a few folders, files, and stuff in the `res://` folder.
2. Select a random node, from a random scene.
3. Click the script button, and create one.
4. Press the `..` button to select path, "Create Folder", pick a random name.
5. Create the script, see that the tree on the left shows it correctly.
6. Open the folder in the file tree.
7. See that all `res://` folders are shown alongside.
8. Press the Refresh button on the file tree.
9. See it is all fine. 
10. Hack the code and submit a PR (not needed to reproduce the bug) :stuck_out_tongue_winking_eye:

**Comment by kubecz3k** [comment]
Almost opened new issue about this, but fortunately found this one... Already prepared gif on which I'm reproducing this so I will add it below
![peek 2016-09-15 18-07](https://cloud.githubusercontent.com/assets/6129594/18558446/74e4645c-7b73-11e6-8de9-104dcefd51c8.gif)

**Comment by bfloch** [comment]
Got the same issue. Is someone looking into it?

**Comment by bfloch** [comment]
Oh boy tracking this down is not so easy. It is a threading issue in the editor_file_system.cpp.

On the first iteration the p_dir of the new folder is set correctly. But a second thread kicks in a adds the root as subdir pointer to the ia somehow.

I haven't found a proper fix yet, but as workaround disabling threading in the settings for the asset library fixes the issue.

It probably is easier for the author to find the issue but in case no one has time I can take a look in a week.

Cheers!

**Comment by akien-mga** [comment]
Renamed the issue to better match its various duplicates.
