### ISSUE TITLE
Implement `OS.get_screen_dpi()` on iOS

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#36628]
**Godot version:**
3.2 stable
**OS/device including version:**
iOS
**Issue description:**
OS.get_screen_dpi(OS.get_current_screen()) yields wrong value on iOS
using iPad Pro first generation, dpi is returned as 72, when in reality it is 264
Same code works correctly on MacOSX, Windows, and Android devices
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
`get_screen_dpi()` isn't implemented on iOS, which means the [fallback value of 72 is returned.](https://github.com/godotengine/godot/blob/b7b39786840a41a057f531ed13b64e26366befac/core/os/os.h#L195)

**Comment by HEAVYPOLY** [comment]
Thanks for the clarification, excited for this enhancement!

**Comment by ViktorEvil** [comment]
Need this for a pixel art game I’m making for iOS, my scaling script to get pixel perfect art has different results on devices that use @3 resolution. My workaround involves using OS.get_model_name and setting the scaling depending on a list of all iOS devices but this isn’t a very elegant solution

**Comment by naithar** [comment]
Was implemented for `3.2` in https://github.com/godotengine/godot/pull/42582. Should be available in 3.2.4 RCs.
@HEAVYPOLY can you please check if it's working?

**Comment by HEAVYPOLY** [comment]
@naithar getting correct 264 dpi on 1st gen iPad Pro.  Thank you!

**Comment by Calinou** [comment]
This was implemented in 3.3 and later per the above comment, closing.
