### ISSUE TITLE
[HTML5] Mouse Events doesn't work in Godot 3.2

### ISSUE THREAD

**Issue by SamToorchi** [godotengine/godot#36634]
**Godot version:** 3.2 Stable

**Browser:** all browsers

**Issue description:**
mouse movement and touch events doen't work by html-export.
console error:
` Ignoring ‘preventDefault()’ call on event of type ‘touchstart’ from a listener registered as ‘passive’.   godotloader.js:10538`

**Comment by akien-mga** [comment]
Might be fixed by #36557, though the error differs (CC @Schroedi).
