### ISSUE TITLE
Failed to submit batchbuffer: Input/output error - GLES3 with Linux/Intel GPU

### ISSUE THREAD

**Issue by kryzmak** [godotengine/godot#36633]
OS: Fedora 31
Kernel: 5.5.5-200.fc31.x86_64
VGA: Intel Corporation HD Graphics 630 (rev 04)
Subsystem: Lenovo Device 505d
Kernel driver in use: i915
Kernel modules: i915
Godot: 3.2 with GLES3

Description: After loading the project, Godot closes with error "i965: Failed to submit batchbuffer: Input/output error"

**Comment by akien-mga** [comment]
I have the same iGPU on Mageia 7, and it runs without problem (Mes 19.3.4).
There must be an issue with your system's package, or given the I/O error, it could also be hardware failure.

**Comment by kryzmak** [comment]
Or maybe a failure in Mesa Version? Latest version of mesa provided in Fedora 31 is Mesa 19.2.8

**Comment by akien-mga** [comment]
Could be a packaging issue yes, if it's reproduced reliably it might be worth opening a bug report at Fedora. I used to have 19.2.x too and it also worked fine, but again it's a different distro and packaging may slightly differ.

**Comment by Calinou** [comment]
@kryzmak Can you still reproduce this with the latest Mesa version?

**Comment by kryzmak** [comment]
Seems that it is been fixed. Thanks for your help.
