### ISSUE TITLE
Can't create new plugin from Project settings dialog.

### ISSUE THREAD

**Issue by Zoomulator** [godotengine/godot#36636]
**Godot version:**
3.2.stable.official

**OS/device including version:**
Windows 10.1903

**Issue description:**
The "create" button in the "Create a Plugin" dialog is permanently disabled.

**Steps to reproduce:**
Create a new empty project.
Go to *Project* -> *Project Settings*.
Then the *Plugin* tab and press *Create*.
The *Create a Plugin* dialog will not enable the *Create* button no matter what you fill in.

**Minimal reproduction project:**
Just an new empty project should do.

**Comment by GeorgeS2019** [comment]
If you create a new plugin based on c# it will fail. GDScript should be fine.

**Comment by Zoomulator** [comment]
@GeorgeS2019 I'm not using the C# version of Godot. 
The "Create" button is greyed out. You can't click it, so it won't even attempt to create the plugin.

**Comment by aaronfranke** [comment]
Can't reproduce with Godot 3.2 stable on Linux. The create button is enabled just fine.

![Screenshot from 2020-02-29 01-50-54](https://user-images.githubusercontent.com/1646875/75602777-0f821900-5a96-11ea-8fd5-4efcf6571787.png)

**Comment by Zoomulator** [comment]
I'm a fool.

I was convinced that the Script Name gave a default value of "plugin.gd" and that you didn't have to put it in. I guess I never tried writing a name with the proper file ending.

Sorry for the time wasting!

@aaronfranke Tho, is it weird that my dialog shows the Create button on the left side?
![create_plugin](https://user-images.githubusercontent.com/1069303/75602970-78838400-5aca-11ea-95ca-f8510e96490d.JPG)

**Comment by Calinou** [comment]
Maybe we should allow leaving the field empty, putting a placeholder to explain it's optional?

**Comment by Zoomulator** [comment]
@Calinou It sure would've saved a daft guy like me some time! ;)
