### ISSUE TITLE
Image resizing not working as intended

### ISSUE THREAD

**Issue by KioriSun** [godotengine/godot#3663]
A simple idea, one set of sprites, and in order to generate an sd version of your game all you do is reduce the sprites by 2(half) export the new set and be happy. That's not how things work though.

Today i tested the image resizing exports, again this is **on 2.0rc1**, basically **resizing the individual images** doesn't work. However **resizing them once you export them in an atlas**, that does work, but it does that in a way that leaves questions... 

You can see the black borders in the picture(the orig tex were 32x32 btw), I'm guessing it has to do with the way atlasses are handled. Also one thing that i was thinking, lets say i resize my images in half, whats gonna happen with the actual objects in the game?
Do i have to do further maintenance to get it to work, will the distances now be twice as large, what about objects and speed?
There isnt a doc on the subject, supporting sd/hd/xhd etc, seems to be quite possible with godot, maybe its just not polished yet.

Again, with the atas export, i dont know what '_default_' is, vs. '_keep original_'. but it  seems keep original takes less ram when running... maybe just an impression...
![resizing](https://cloud.githubusercontent.com/assets/10463922/12977675/59602ae2-d0b3-11e5-9ff6-08d0b15ab429.png)

**Comment by KioriSun** [comment]
@kubecz3k This is not only a discussion, but -also- a bug report.
Image resizing is not working properly.

**Comment by KioriSun** [comment]
I tested with higher res assets, namely 512 and 128 and got the same black bar around the left and top of the resized sprite(in this case resized to half the size).
![resizing2](https://cloud.githubusercontent.com/assets/10463922/12993105/74912d9c-d0ff-11e5-86d7-20a1c1eee4cb.png)


My guess is that after the exporter resizes the images, something goes wrong with the code that reads the textures inside of the atlas, that leaves the exported/resized ones like this.
 Or maybe the exporter puts them into an atlas and then, afterwards resizes, which could mean the resizing process is to blame.

My experience with manually resizing texture, inside the editor(resizing not scaling), is that you need to toggle center on/off for it to work properly.

At any rate, this is the only thing keeping godot from being a one-stop solution to distributing different builds with differently sized assets easily.
At the moment if you wanna have a HD and a SD build, I think you gotta do it yourself, possibly through code.

**Comment by AfterRebelion** [comment]
This doesn't seem valid anymore. Here an example with 0.5 and 2.0 scale on 3.0.6
![godot image resize 2018-11-22 211544](https://user-images.githubusercontent.com/559819/48920902-1508b080-ee9c-11e8-9a9b-1450f831bb2f.jpg)
No black shadow.

Also the last post makes a reference to 
> My experience with manually resizing texture, inside the editor(resizing not scaling)

And I don't know what it means by that. When you resize a sprite in the editor, what you are really doing is change x and y scale property visible on the inspector.
This is true for Godot 3 and to make sure, in Godot 2 as well.
![imagen](https://user-images.githubusercontent.com/559819/48921146-ff948600-ee9d-11e8-94c5-445c327e4609.png)

**Comment by akien-mga** [comment]
Thanks for the thorough test, this indeed does not seem relevant anymore.
