### ISSUE TITLE
Auto-completion in comments not entirely useful for apostrophes.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#36638]
**Godot version:** 3.2.0 stable

**OS/device including version:** N/A

**Issue description:** Auto-completion has its issues when you're writing comments. For example `# Can't and won't do this.` would duplicate the `'` character (i.e. treat it as a single quote). This is a minor issue, but makes contractions (i.e. "it's", "can't" etc) slightly more difficult than it needs to be. Maybe look at the way other projects such as Inform 7 (for example) handle this?

**Steps to reproduce:** Just press `'`.

**Comment by dreamsComeTrue** [comment]
Fixed in PR (it was done in 'master' but probably can be cherrypicked to 3.2) :)
