### ISSUE TITLE
[HTML5] Audio stuttering in iOS Safari caused by AudioContext sample rate

### ISSUE THREAD

**Issue by ChronoDK** [godotengine/godot#36643]
**Godot version:**
3.2 stable

**OS/device including version:**
Safari on iOS 13.3.1 

**Issue description:**
Audio stutters because iOS Safari does not like the AudioContext to have a sample rate of 48000, which is the default when an AudioContext is created.  The AudioContext should instead be created using the sample rate specified in Project Settings (the Godot default is 44100, which is also what iOS likes).

Here is how to create an AudioContext with a specific sample rate using JavaScript:
var AudioContext = window.AudioContext || window.webkitAudioContext;
var audioCtx = new AudioContext({sampleRate: 44100});

I would implement this in the engine if I knew how :-)

**Comment by ChronoDK** [comment]
Nevermind my attempted solution. I implemented it myself, but sadly it didn't work. Audio is still stuttering. So I guess it's not related to sample rate. Not sure why then.

I still think AudioContext should use the samplerate from Project Settings, but it won't fix this issue.

**Comment by Faless** [comment]
This is implemented via #38816 (and follow ups).
The JavaScript audio driver now respects both the `audio/mix_rate` and `audio/output_latency` settings, and compute the buffer size accordingly. If you experience stutters, you can try raising the `output_latency` (at the cost of delay).
Available in 3.2.2 and up.

**Comment by ChronoDK** [comment]
Would it be possible to adjust latency for specific sounds only? I have background music stuttering on scene change or when many nodes are added, but if I increase the latency dramatically (200) the stuttering goes away. This delay obviously wont work for gameplay sounds, but is fine for background music.

**Comment by Faless** [comment]
No, sadly you can't have different settings for different sounds, those settings are for the whole AudioContext.
Hopefully, we'll be able to get even better results when we manage to do audio mixing in a separate thread, but browser support for that is still limited.

**Comment by ChronoDK** [comment]
It would likely be a huge refactor, but perhaps if each audio bus used a different AudioContext with separate latency settings? Then music could be assigned to an audio bus with high latency. But yeah, it might be smarter to just wait for thread support.
