### ISSUE TITLE
VideoStreamPlayer has Expand enabled by default, causing it to be sized at 0×0 by default (therefore being invisible)

### ISSUE THREAD

**Issue by lszl84** [godotengine/godot#36647]
**Godot version:** master (947a6636f70ea5a051efd6e470147072f2bc7f13)

**OS/device including version:** mac OS 10.15.3

**Issue description:** Video does not play in Godot 4. Works in Godot 3.

**Steps to reproduce:** Open attached project in Godot 3.2. Run it and verify that the video is playing. Close the project and open it in Godot 4. No video is being played when running the project.

**Minimal reproduction project:**
[godot3vid-3.zip](https://github.com/godotengine/godot/files/4267994/godot3vid-3.zip)

**Comment by hungrymonkey** [comment]
```
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
ERROR: Condition "texture.is_null()" is true.
   at: update (scene/resources/texture.cpp:196)
````
[bug_video 2.zip](https://github.com/godotengine/godot/files/4604934/bug_video.2.zip)

I can hear sound but the video does not work.

<img width="1136" alt="Screen Shot 2020-05-09 at 5 21 09 PM" src="https://user-images.githubusercontent.com/771339/81488120-874c8c80-9219-11ea-9d8d-b4fa0adfefd7.png">

**Comment by Jayman2000** [comment]
I don’t think that this issue is still valid. See:

- godotengine/godot-proposals#3286
- #53833

**Comment by Calinou** [comment]
@Jayman2000 Theora is still supported in `master` – it's just that WebM support was removed in `master`.

**Comment by Calinou** [comment]
> I can hear sound but the video does not work.

This is because you resized the VideoStreamPlayer node to a 0×0 size. Disable the **Expand** property on the VideoStreamPlayer node, or set the **Layout** to Full Rect (will cause aspect ratio distortion unless the video's aspect ratio matches).[^1]

![image](https://user-images.githubusercontent.com/180032/177428035-9e878b78-92bf-4c62-a944-7bd96e013f46.png)

[^1]: To preserve the aspect ratio on wider window aspect ratios, set the **Layout** to Full Rect, then use the **Anchors Only** submenu to set the anchors to **VCenter Wide**.
