### ISSUE TITLE
Vulkan: Fog not reimplemented yet

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#36654]
**Godot version:** Git https://github.com/godotengine/godot/commit/a9c2ab81cf09cc278c188385a5c801d002f9fc55

**OS/device including version:** Fedora 31, NVIDIA 440.44, GeForce GTX 1080

**Issue description:** Fog isn't implemented yet in the Vulkan renderer.

**Steps to reproduce:** Add a MeshInstance and WorldEnvironment node to a 3D scene then add an Environment resource to it. Edit the Environment resource and enable its Fog property. No fog appears after doing this.

**Comment by akien-mga** [comment]
Fixed by #41240.
