### ISSUE TITLE
Avast anti-virus blocks Godot in some cases

### ISSUE THREAD

**Issue by KioriSun** [godotengine/godot#3665]
Avast keeps detecting Godot as some sort of hacking device, in order to reproduce all i have to do is run the engine, export a build, run the build.(while the engine is running)
It also did it once i ran the engine the first time.
However if i close the engine and run only the build it runs fine.(mostly)
But these sorts of cases are a warning, what is the average user gonna think?
So maybe there is something to look into, or at least users should be foretold of this issue with Avast(and maybe other anti-viruses?).

**Comment by akien-mga** [comment]
It could come from the upx compression, some anti-viruses are touchy with it.
What export templates were you using (architecture, release vs debug)?

**Comment by punto-** [comment]
If it only happens when launching from the editor, it could be because the
editor opens a tcp port to connect with the game for the debugger, etc,
that usually triggers one of those firewall warnings. The average user
won't see that, just run the exported game normally.

**Comment by KioriSun** [comment]
yeah I did get the firewall warning at some point.

I'm using 2.0rc1, win10, 64bit. with debug active i believe.
The auxiliary black windows means debug right?

Maybe like punto said that's what it's all about. If that's the case good, but you guys should add a warning for developers, somewhere in the docs.

**Comment by Marqin** [comment]
It was [reported](http://steamcommunity.com/app/404790/discussions/0/412448158142425159/) also for Avira.

According to [VirusTotal](https://www.virustotal.com/en/file/2bb9442f6630300b097a94740ee15e0d8ca61a57d0f3562fd5c3256eeddcf79f/analysis/1456331658/) it's only problematic in 4 cases.

**Comment by reduz** [comment]
we have to sign the binaries to make this less likely to happen

**Comment by tomreyn** [comment]
According to a [recent scan of the 2.0 (stable) release for 64-bit Windows](https://www.virustotal.com/de/file/bb215f599f69a0201ce6b3612199cc9538d6dc892d82e94e83de0e77724e40a9/analysis/), this issue seems to be (temporarily?) solved / worked around.

**Comment by Marqin** [comment]
The issue was about 32-bit version, could you check it out also?

2016-03-03 0:45 GMT+01:00 Tom Reynolds <notifications@github.com>:

**Comment by Marqin** [comment]
Also, is the Steam version any different? If yes then it also should be
again scanned.

2016-03-03 10:15 GMT+01:00 Hubert Jarosz <hubert.jarosz@gmail.com>:

**Comment by tomreyn** [comment]
According to VirusTotal, the 32-bit Windows release was not detected by any AV [a week ago](https://www.virustotal.com/de/file/78adf091d44141a6d8043d8add974335b7b42f0b2fbe84d62d16d0838954dc93/analysis/1456398243/), nor is it [now](https://www.virustotal.com/de/file/78adf091d44141a6d8043d8add974335b7b42f0b2fbe84d62d16d0838954dc93/analysis/1457037350/).

**Comment by Marqin** [comment]
@tomreyn no, 32-bit Steam version was deteted by 4 AV's, as I've linked it before. I can link you again - [here](https://www.virustotal.com/de/file/2bb9442f6630300b097a94740ee15e0d8ca61a57d0f3562fd5c3256eeddcf79f/analysis/1456331658/).

**Comment by tomreyn** [comment]
I saw the link last time you posted it, but was not aware it's the Steam version. Thanks for reposting, though.

**Comment by KioriSun** [comment]
Haven't had this bug with standalone download(64-bit) and steam version(32-bit) since stable release. I guess it's fixed. I use Avast btw.

**Comment by techtonik** [comment]
So, can this be closed until next positive?

**Comment by akien-mga** [comment]
Yes, thanks for the notice.

**Comment by Crax97** [comment]
I noticed today that Avast won't let the Godot editor connect to the running game, resulting in the editor not showing the content of `print()` calls and not being notified when the game is closed.
Adding the editor to Avast's exception list makes everything run fine
