### ISSUE TITLE
Faliure on Launch: failed init DINPUT

### ISSUE THREAD

**Issue by somedumbfox** [godotengine/godot#36662]
**Godot version:**
 Godot_v3.2-stable_win64
**OS/device including version:**
Windows 10
**Issue description:**
First time trying to use this program. My understanding is the standard version is self contained and doesn't need anything else to run, yet upon trying to launch I get an error:

E:\Downloads\Godot_v3.2-stable_win64.exe>Godot_v3.2-stable_win64.exe --verbose
Godot Engine v3.2.stable.official - https://godotengine.org
Using GLES3 video driver
OpenGL ES 3.0 Renderer: GeForce RTX 2070/PCIe/SSE2
failed init DINPUT: -2147467259

**Steps to reproduce:**
N/A Godot fails to launch

**Minimal reproduction project:**
N/A

I saw a similar issue that was closed already (#28394, #23165) But the fix doesn't seem to work for me nor am I using the mono version. This file is not in an administrator restricted space.

**Comment by somedumbfox** [comment]
No idea why, but for some reason my computer needed to restart in order for this program to launch. This issue seems to be related to Directx acting up.

**Comment by goatchurchprime** [comment]
I hit this one to today.  Restarted windows machine after a week, and all versions of godot failed completely with this error.  Nothing, not even the --no-window option made it get further or provide a more informative error.  Worked after computer rebooted a second time.  Would be good to get to the bottom of this mystery to avoid it resurfacing in a worse way in the future.

**Comment by Calinou** [comment]
I suppose we could change the error message to tell the user that restarting their PC might fix it :slightly_smiling_face:

**Comment by goatchurchprime** [comment]
Should it have printed a stack-dump?  It looked like the failure was so catastrophic it wasn't even doing that (though at least the --help option worked).  I am very wary of these heisenbugs, because it feels like one day you could do a release and it could start happening every 20 minutes.

**Comment by somedumbfox** [comment]
I do agree with @goatchurchprime 

This issue occurs to me quite a bit, and the error is never verbose enough for me to really understand why it's throwing this error. In turn, there's nothing I can really provide other than this simple message I see. So I doubt it's very helpful for the main contributors of this repo.

I'd say a computer restart is a normal option for a machine that has running 24/7 for several days straight, and that could be something out of GoDots realm of fixing. But I can confidentially say I've encountered this after a fresh reboot on many occasions. Only for a second reboot to fix it. It's honestly confusing and inconsistent to reproduce.

**Comment by somedumbfox** [comment]
Reopening this issue so other contributors may see it and provide any insight on a path forward (if one can be brought forward at this time).

In all honesty, it's not a terrible bug that breaks stuff and isn't a super high priority to fix. It's only a mild inconvenience. But, if it were to occur to a first time user (like it has for me) it can definitely leave a negative impact them. I do remember my first thought being "well that sucks, looks like I can't use this at all." and I almost moved on to try other options before even giving this a chance.

**Comment by akien-mga** [comment]
#39140 improved the error message, and #39143 should improve it further and make it possible to start Godot even when this error is raised (albeit without joypad support).
