### ISSUE TITLE
In Visual Script functions for AnimationPlayer there's no autoplay() method . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot#36666]
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
I am looking through the documentation, and I want the autoplay() function under AnimationPlayer, in Visual Script, however when I click " Add Node " and, search for it, when adding  a script to an AnimationPlayer, so it's particular functions are there, in the ' add node list ', autoplay isn't there . . Is this a bug, I don't know . . .

**Steps to reproduce:**
Make an AnimationPlayer node, add a visual script, then with the Base Type being AnimationPlayer, click Add Node at the top, of Visual script . . There comes a list, with all the functions, in official documentation there's an autoplay function, in the list it is not there . .? 

**Minimal reproduction project:**
I'm not sure, don't know . .

**Comment by theoway** [comment]
@jasperbrooks79  Autoplay is a property, not a function. That's why, it doesn't appear in the Add Nodes list.

**Comment by KoBeWi** [comment]
See above comment.
