### ISSUE TITLE
Compilation errors on Windows 10 with Visual Studio 2019

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#36671]
**Godot version:**
Master 8ffa35e44f93321d618b81ec48817f5de8668a83

**OS/device including version:**
Windows 10
Visual Studio Community 2019, version 16.4.5

**Issue description:**
This error appears during compilation:
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\combaseapi.h(234): error C2760: syntax error: unexpected token 'identifier', expected 'type specifier'

**Steps to reproduce:**
n/a

**Minimal reproduction project:**
n/a

**Comment by akien-mga** [comment]
The error doesn't make much sense by itself, doesn't it give more information about the include chain like GCC and Clang do?

**Comment by pouleyKetchoupp** [comment]
By default all I can get is this error (I just know it happens first while compiling platform\windows\godot_windows.cpp). I'm going to try and compile with some flags to get more information.

**Comment by dreamsComeTrue** [comment]
I've just built latest master on Win10 and it works fine.
Might it be a problem with Windows PlatformSDK that you are using?

**Comment by pouleyKetchoupp** [comment]
Yes, it seems there's an issue related to `/permissive-` compiler flag in some situations:
https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019
```The /permissive- option is compatible with almost all of the header files from the latest Windows Kits, such as the Software Development Kit (SDK) or Windows Driver Kit (WDK), starting in the Windows Fall Creators SDK (10.0.16299.0). Older versions of the SDK may fail to compile under /permissive- for various source code conformance reasons. The compiler and SDKs ship on different release timelines, therefore there are some remaining issues. For specific header file issues, see Windows header issues below.```

So the Windows SDK I'm using (10.0.10586.0) is not good. I'm checking if it's a problem with scons or the SDK installed on my machine.

**Comment by pouleyKetchoupp** [comment]
Confirmed to work after adding Windows 10 SDK (10.0.16299.0) to Visual Studio 2019 installation. I'm going to update the doc to make it clear this is a required component.

**Comment by akien-mga** [comment]
Alternatively we can remove `/permissive-` or make it optional and enable only on CI. I added it for consistency with GCC and Clang's non-permissive behavior, but we don't actually need it per se.

**Comment by pouleyKetchoupp** [comment]
Ok, making it optional sounds like a good idea if it's not really needed. What about checking the sdk version and adding the flag only on version 10.0.16299.0 or higher?
Looks like we could use `os.getenv("WindowsSDKVersion")` for that.

**Comment by pouleyKetchoupp** [comment]
@akien-mga I went ahead and made a PR that addresses the issue by checking the sdk version number, but I'm fine with implementing a different fix if you prefer a command line option or just removing the flag.
