### ISSUE TITLE
Scene Animation Import plugin is not yet implemented though the class definition is there

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3667]
The code for this seems to be empty. I guess it would be nicer to remove it from the menu or else people click and nothing happens

**Comment by akien-mga** [comment]
The solution for 2.0 would be to comment it out indeed.

**Comment by akien-mga** [comment]
I commented it out in 01cf698 the code responsible for adding the Scene Animation Import plugin in the "Import" menu, so this part is catered for. Now the question is whether this feature should actually be implemented, or if the dead code should be dropped.

Moving this to the next milestone, for 2.0 we've done all that was needed.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.
