### ISSUE TITLE
Vulkan: Mipmaps aren't generated automatically for a NoiseTexture applied to a StandardMaterial3D

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#36675]
**Godot version:** Git https://github.com/godotengine/godot/commit/e4bc16b7b6a7a9354e6037cb571de934a8ec1430

**OS/device including version:** Fedora 31, NVIDIA 440.44, GeForce GTX 1080

**Issue description:** Mipmaps aren't being generated when applying a NoiseTexture in a 3D environment, which makes the texture grainy at a distance. This doesn't happen with ImageTexture. Interestingly, enabling anisotropic filtering on the texture *slightly* improves the appearance, but not by much.

**Steps to reproduce:** Create a MeshInstance and a StandardMaterial3D. Assign a NoiseTexture with OpenSimplexNoise to the material's Albedo property. Compare the result with an ImageTexture.

![image](https://user-images.githubusercontent.com/180032/75608929-3aa35180-5b04-11ea-807a-dafe562ae984.png)

**Minimal reproduction project:** [test_mipmap.zip](https://github.com/godotengine/godot/files/4270376/test_mipmap.zip)

**Comment by akien-mga** [comment]
Confirmed in the current master branch (201d5a7fc53c041e011ad7a79b805f5989216d28).

**Comment by Xrayez** [comment]
Did it work in 3.2?

![godot_noise_texture_mipmaps](https://user-images.githubusercontent.com/17108460/96911379-729f4080-14a9-11eb-8a6a-ea25d88f035e.png)

See https://github.com/Xrayez/godot/commit/8ae82725849584de944f64f49183d5c8163ac871.

> Compare the result with an ImageTexture.

The MRP doesn't generate `ImageTexture` dynamically, but instead uses `StreamTexture`, which is imported with mipmaps to be generated by default. `NoiseTexture` is generated procedurally, but there's no texture flags to configure this in `master`.

**Comment by Calinou** [comment]
@Xrayez The NoiseTexture definitely appears smoothed out in the distance on your screenshot.

**Comment by Xrayez** [comment]
No, I was just curious whether it used to work in 3.2. 🙂

Just tested, it's not an issue in 3.2. Texture flags were removed in `master`, but available in 3.2:

![godot_noise_texture_flags](https://user-images.githubusercontent.com/17108460/96912454-16d5b700-14ab-11eb-9933-38171652e73f.png)

I don't know how it works internally.

**Test project**:
[test_mipmap-3.2.zip](https://github.com/godotengine/godot/files/5424829/test_mipmap-3.2.zip)
