### ISSUE TITLE
Duplicate Line missing shortcut setting

### ISSUE THREAD

**Issue by xix-xeaon** [godotengine/godot#36670]
**Godot version:**
Godot_v3.2.1-rc1_x11.64

**Issue description:**
I've got CTRL+D set to Toggle Comment for scripts because that's what I'm used to from other editors and it's way more convenient than CTRL+K. There are several other settings for duplication in the rest of the editor (which I use with CTRL+D just fine). But I can find no shortcut setting for duplicating lines (which I don't need as a shortcut). So I can't easily toggle comments anymore.

Also: After resetting the Toggle Comment, I can't set it to CTRL+D again if any text editor is open (script or shader) because it detects only CTRL and then duplicates a line in the editor instead.

**Comment by dreamsComeTrue** [comment]
You're welcome :) 
![obraz](https://user-images.githubusercontent.com/1110337/75606895-d9728280-5af1-11ea-9fcf-5f41ea82ae3c.png)

**Comment by xix-xeaon** [comment]
"Clone Down"... wow, I would never have guessed that. Thanks! But it should probably be renamed. I don't know if "Duplicate Line" is the best name but at least it's in line with all the other CTRL-D.

**Comment by dreamsComeTrue** [comment]
That always annoy me too, so I've made PR to finally sort that out :)
