### ISSUE TITLE
Godot 2.0 Beta/RC1 Tileset Collision Bug

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#3668]
Hello! unfortunately I've ran into finding a problem while testing the _convert to_ options in Godot, apparently it doesn't allow the collision object to be exported to the res or tres file. The tres file reads:

```
[gd_resource type="TileSet" load_steps=2 format=1]

[ext_resource path="res://icon.png" type="Texture" id=1]

[resource]

0/name = "Sprite"
0/texture = ExtResource( 1 )
0/tex_offset = Vector2( 0, 0 )
0/region = Rect2( 0, 0, 0, 0 )
0/occluder_offset = Vector2( 32, 32 )
0/navigation_offset = Vector2( 32, 32 )
0/shape_offset = Vector2( 0, 0 )
0/shapes = [  ]

```

Shapes (A.K.A. collision) is not saved during the Convert to progress, both CollisionShape2D and CollisionPolygon2D doesn't work anymore. resulting on one of the kinematic characters I've been testing with to phase through the floor.

Has anybody noticed that exporting collisions to tilesets doesn't work? I've tried this on both the 32 and 64 bit Windows version on the RC1 release version already. Just for heads up before the final 2.0 is released.

**Comment by akien-mga** [comment]
Hm I haven't tested in the last couple of days, but I've been creating tilesets with collision shapes during the whole development of 2.0 and never had any issue.

Could you upload a simple project that reproduces the issue? (with the tileset source scene)

**Comment by akien-mga** [comment]
I guess you probably forgot to use StaticBody2D as parent of your Collision{Polygon,Shape}2D. As far as I know, such shapes don't do anything if they're not children of a \*Body2D.

**Comment by Corruptinator** [comment]
Hello! Sorry for the delay, but here's the project in a zip file uploaded on my google drive:
https://drive.google.com/folderview?id=0B9c8Y0ut0CxYTExRUm1WVkRWUnc&usp=sharing

There are two scn files where one is the test level with the platform physics problem and the other is where the tilemap is compliated before using "Convert To"

**Comment by bojidar-bg** [comment]
@Corruptinator Do it with
````
Node2D/
- Sprite
  - StaticBody2D
    - Shapes....
````
Instead of
````
Node2D/
- StaticBody2D
  - Sprite
  - Shapes....
````

**Comment by Corruptinator** [comment]
Ok, I'll give that a try...

**Comment by Corruptinator** [comment]
It actually works! Turns out that the layout for making a tileset is way different in 2.0. This is kinda jarring for me especially when I've been looking at the 1.0 demos and remembering what the original layout was originally set as.

**Comment by akien-mga** [comment]
Hm the layout as always been as shown by @bojidar-bg as far as I can remember :)
