### ISSUE TITLE
SoftBody is not affected by space override

### ISSUE THREAD

**Issue by bmolyneaux** [godotengine/godot#36693]
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:** 
Area nodes have a space override which allows the gravity to be replaced. It works for RigidBody, but not for SoftBody.

**Steps to reproduce:**

1. Create a SoftBody within an Area.
2. Set the Area's Space Override to Replace and change its Gravity Vec.
3. The SoftBody will not be affected by the Area's overrides.

**Minimal reproduction project:**
This example project has a RigidBody and a SoftBody. The RigidBody falls to the right because of the Area's gravity override, but the SoftBody falls down.
[SoftBodyBug.zip](https://github.com/godotengine/godot/files/4271205/SoftBodyBug.zip)

**Comment by WilliamTambellini** [comment]
@Chaosus Coud that one be tagged for 4.0 ?
