### ISSUE TITLE
Need RegEx::get_capture_start(int capture)

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#3670]
NOTE : I'll do this myself tonight, just issuing to avoid forgetting it.

This RegEx method is needed in order to ease substitutions. It should return the starting position of the 'capture' group in the tested string.
Currently, `RegEx::get_capture(int capture)` only returns the substring, not its starting position in the string and `RegEx::find(...)` only returns the position of the first matched capture.

Nothing difficult for this method : 
 `
int RegEx::get_capture_start(int capture) {
    ERR_FAIL_COND_V( get_capture_count() <= capture, String() );
    return captures[capture].start;
`

Without forgetting to bind this method, ofc.

**Comment by akien-mga** [comment]
Fixed by #3680.
