### ISSUE TITLE
Unwanted newlines in AndroidManifest.xml and build.gradle with custom templates

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#36708]
**Godot version:**
3.2, 3.2.1.rc and master

**OS/device including version:**
Manjaro Linux and Windows 10

**Issue description:**
When using custom Android templates every time you make a build, Godot appends a newline to AndroidManifest.xml and build.gradle in the `android/build` folder resulting in hundreds of newlines at the end of those files if you don't remove them every time by hand. This is especially annoying if you use a version control system since both files will change with every build.

**Steps to reproduce:**
Setup an empty Godot project and enable custom Android build templates. Now make an Android build and observe that every time you build a newline will be appeded.

I'm currently working on a fix. Should be up in an hour or two.

**Comment by akien-mga** [comment]
Fixed by #36754.
