### ISSUE TITLE
Array.back() says it should return `null` if the array is Empty. It does not.

### ISSUE THREAD

**Issue by novemberisms** [godotengine/godot#36701]
**Godot version:**
Godot 3.2 Stable (non-mono)

**OS/device including version:**
MacOS Mojave

**Issue description:**
`Array.back` specifically states in the documentation:

> Returns the last element of the array, or null if the array is empty.

However as of Godot 3.2, `null` is not returned from an empty array. Instead, the following error appears in the debugger log:

```
E 0:00:00.312   back: Can't take value from empty array.
  <C++ Error>   Condition "_p->array.size() == 0" is true. Returned: Variant()
  <C++ Source>  core/array.cpp:141 @ back()
  <Stack Trace> Node.gd:12 @ _ready()
```

**Steps to reproduce:**
```
var my_array = []

func _ready():
    assert(my_array.back() == null)
```

**Minimal reproduction project:**
Attached is an MRP. Just run the game and you'll see the error appear in the console.

[Array Back MRP.zip](https://github.com/godotengine/godot/files/4271729/Array.Back.MRP.zip)

**Comment by simpuid** [comment]
Sure, the error appears in the console but I think it is intentional. `Array.back` causes that error but it also returns `null` when called on an empty array.
Just run
```
func _ready() -> void:
	assert(non_empty.back() == 1)
	assert(empty.back() == null)
	print(empty.back())
```
It will print Null and the error in debugger console.

**Comment by giarve** [comment]
May not be a bug: see https://github.com/godotengine/godot/pull/7149#issuecomment-261665870.

In case you wanted to modify it instead of modifying the docs, I have prepared a commit and can issue a PR if necessary...

**Comment by novemberisms** [comment]
Ah I see. I recognize this may not be a bug after all. Rather it is a miscommunication in the docs.

This reply from @Kazuo256 makes sense

> The assert was a suggestion in the original issue's thread.
>
> But now that I think about it, I believe that returning null could be confusing, because it would be no different from succesfully returning the first or last element of the array when they are, in fact, null.

However,  if this is the case it should state in the docs that it will throw an error if the array is empty, rather than stating that it will return null.

Either that, or maybe do what C# does: provide a `FirstOrDefault` and `LastOrDefault` function

something like

```gdscript
var arr = []

var a = arr.back_or_default(null)

assert(a == null)

var b = arr.front_or_default("")

assert(b == "")
```

**Comment by Calinou** [comment]
The documentation was updated accordingly, closing: https://github.com/godotengine/godot/blob/56838ca009ca7d20eb89e7b1c182beff1ce1190d/doc/classes/Array.xml#L149-L150
