### ISSUE TITLE
Text problem Bb Code Enabled / disabled

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#36711]
**Godot version:**
3.2.1 RC1 mono

**OS/device including version:**
win10 64

**Issue description:**
Deactivating the option Bb Code "Enabled" does not make the written text appear again.

**Steps to reproduce:**
1-Enter some text in the "Text" box.
The text is displayed.

2-In the Bb Code section click on "Enabled".
Now the text disappears from the screen.

3-Deactivate the option Bb Code "Enabled" again.
The text is not displayed again.
---
In the GIF, ENTER was pressed in the "Text" box after step 3 for the text to be seen again.

![8colores](https://user-images.githubusercontent.com/19652075/75632222-4ffaa780-5bfa-11ea-8740-26822af2209f.gif)

**Minimal reproduction project:**
[textTest.zip](https://github.com/godotengine/godot/files/4272297/textTest.zip)

**Comment by timothyqiu** [comment]
The main cause of the "issue" is that the `text` property is not stored, it's just an easy way to update / inspect the tag stack.

When enabling BBCode, the current `bbcode` property is used to update the tag stack. Since the `bbcode` property is empty, the tag stack becomes empty. Disabling BBCode does nothing to the tag stack, it only affects the setter of `bbcode` property. So toggling BBCode's enabled property won't make the content non-empty.

Maybe the documentation needs to make it clear.

**Comment by Ydjeen** [comment]
There is some inconsistency in how two text fields from Inspector interact with a text, shown in a view-port and how the text is stored, i.e., how text behaves after the scene is reloaded.

- First of all, the text that is displayed in a view-port is always the text that was last edited.
For example, i've put some text into BBCode text field and then some into normal one. Second one will be completly ignored, but is still shown in the view-port.
![richtextlabel_before_save](https://user-images.githubusercontent.com/6872975/76255493-8cf41900-624e-11ea-9923-6abc501d09a6.png)

- Second, if some text is present in the BBCode text field, only it will be saved. In other words, after the scene is reopened, text from BBCode text field will be duplicated in the usual text field and it will be displayed in the view-port. This behavior is described in documentation, but i still find it somehow not intuitive.

- And also this bug with the BBCode checkbox, mentioned by Torguen.

I would like to know, if the two text fields are really necessary ?

The way i see it - there should be only one text field, and the BBCode check-box should only inform a renderer how the text should be drawn - as a simple text tag, or should it be parsed taking into account the BBCode markup.
