### ISSUE TITLE
Links are only clickable under public methods in editor help

### ISSUE THREAD

**Issue by henkz1** [godotengine/godot#3671]
For example open up Transform in help, you can click on Matrix32 under "Public Methods", but not Matrix32 under "Members".
Tiny issue but frustrating in some cases

**Comment by bojidar-bg** [comment]
Hm, retested in master, it seems like now only "Members" ' links can be clicked, but "Public Methods" ' can't (probably as a result of them being moved around).

But, this is only in case there are "Members" in the class, otherwise, it is all good with the "Public Methods"...

**Comment by bojidar-bg** [comment]
From https://github.com/godotengine/godot/issues/9641#issuecomment-317149065:
> @quinnyo
> I think this issue is the same as one I noticed a while ago. It's been like this for quite a long time on the 3.0 master branch at least.
>
> In most pages, (test Node, Viewport) - without scrolling, links below "Public Methods" do not work, but links above do. You can also see the cursor is stuck as the "link clicking" cursor while over the non-working region. If you scroll down so that "Public Methods" is the first visible line, the links work.
> 
> In pages like `@GDScript` (because it has no links before Public Methods?), all the links work without scrolling.
