### ISSUE TITLE
Android export: Validate .apk contents before exporting

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#36727]
**Godot version:**
3.2-stable, master (e2b66ca)

**OS/device including version:**
Export to Android from any OS.

**Issue description:**
When exporting to Android with custom-built templates, I often fall into the trap of having a custom template with only an armv7 or arm64v8 library, while my export preset has the other one enabled. (Or, on an arm64v8 capable device, having both armv7 and arm64v8 enabled but only armv7 provided will also reproduce the issue.)

In such case, the game will crash on the device and one has to dig through `adb logcat` to figure out that `libgodot_android.so` is missing.

We should perform a basic validation of the contents of the APK (at least checking that the libs are present for the enabled architectures in the preset) before allowing export. (Or, if we can't do that easily, the export should fail if the libs are found missing while creating the new APK.)

**Steps to reproduce:**
- Build custom APK with only `armv7`
- Export to arm64v8 device with `arm64-v8a` enabled.

CC @godotengine/android

**Comment by m4gr3d** [comment]
@akien-mga this only affects dev builds though, since for release and stable builds, the provided `android_source.zip` contains all supported abis.

As such, maybe we should update the gradle generation task to fail if one of the abi is missing instead of adding an explicit check in the editor which would never be used for production builds.

**Comment by akien-mga** [comment]
>  this only affects dev builds though, since for release and stable builds, the provided `android_source.zip` contains all supported abis.

Actually I was referring to the non-custom workflow. If you set a "Custom Debug Template" with only one arch lib, and export with another, higher priority support arch enabled, it will crash on device.

**Comment by m4gr3d** [comment]
Okay that makes sense then, thanks for the clarification.
