### ISSUE TITLE
Godot RC1 (script editor, 3d object, game pause)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#3672]
1. Do not save changes to edit the script, if not open the scene in which this script should be executed.
2. Changing the orientation of 3D objects on Y axis entails a spontaneous change of the value of adjacent axles.
3. In the particle system does not act pause.

**Comment by akien-mga** [comment]
Please read the instructions on how to report bugs properly: https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md

Right now it's pretty hard to understand what are your issues, and the issue title says nothing about the bugs either. You should open one issue per bug, with a descriptive title, and give more details on how to reproduce.
Thanks in advance :)

**Comment by akien-mga** [comment]
Reopening for now as those are probably still valid bugs, but they should be split each into their own GitHub issue.

**Comment by akien-mga** [comment]
Issue 1 was created as #3674 and issue 3 was created as #3675.

Please open a new issue just for your second point ("Changing the orientation of 3D objects on Y axis entails a spontaneous change of the value of adjacent axes.") with steps to reproduce and maybe a test project that shows the bug easily.

**Comment by DimaKiva** [comment]
Ok

**Comment by akien-mga** [comment]
Issue 2 was created as #3681, thanks @DimaKiva :)
