### ISSUE TITLE
Vulkan: Inspector previews for materials, meshes now broken

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#36721]
**Godot version:**
4.0 https://github.com/godotengine/godot/commit/e2b66cacf78ae39b94df748e9740b98a1f011e77
Edit: Still reproducible 2020-07-01 0a8dbe7f7

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
Two cubes of different colours with different materials
![image](https://user-images.githubusercontent.com/14253836/75657702-69b4e280-5c2c-11ea-9dce-ed3b6301819e.png)

**CubeA**
![image](https://user-images.githubusercontent.com/14253836/75657734-7a655880-5c2c-11ea-8659-03580eda17b1.png)
**CubeB**
![image](https://user-images.githubusercontent.com/14253836/75657748-8224fd00-5c2c-11ea-955a-4df79d9e5c7f.png)

Both materials appear to be red when only one of them is red

File System materials also have incorrect previews.

![image](https://user-images.githubusercontent.com/14253836/75657795-99fc8100-5c2c-11ea-9123-44613ea3640f.png)

All of these bugs are still reproducible even after **restarting the project**.

```
ERROR: Condition "!F" is true. Continuing.
   at: clean_up_dependencies (./servers/visual/rasterizer.h:185)
ERROR: Condition "!F" is true. Continuing.
   at: clean_up_dependencies (./servers/visual/rasterizer.h:185)
ERROR: Condition "!F" is true. Continuing.
   at: clean_up_dependencies (./servers/visual/rasterizer.h:185)
```

**Steps to reproduce:**
Open project main scene and look at the material previews

**Minimal reproduction project:**
[Test11.zip](https://github.com/godotengine/godot/files/4274202/Test11.zip)

Edit: Not sure about other previews so removed that part of the title for now

Edit 2: Meshes also display incorrectly like this 
![image](https://user-images.githubusercontent.com/14253836/75658493-0d52c280-5c2e-11ea-9ac0-25ddb2e6e7b1.png)

**Comment by akien-mga** [comment]
> Godot version:
4.0

Be sure to specify the commit, this won't make much sense in a matter of weeks.

**Comment by bruvzg** [comment]
Still relevant, also affects font previews.

> All of these bugs are still reproducible even after restarting the project.

I'm not getting any errors printed with Font and Material preview, but it's still broken.

Seems like the viewport texture updates only when `generate` method of the `Editor*PreviewPlugin` is called for the first time, the rest of previews have the same image as the first one generated (`generate` is called for all resources, and drawing preview seems to be correct, but the resulting texture is not updated).

Creating a new viewport on each `generate` call seems to fix it, but it's clearly not the correct fix, probably something is wrong with the viewport updating (maybe only when it's updated from the non-main thread).
