### ISSUE TITLE
`Align Transform with View` should not move the view

### ISSUE THREAD

**Issue by greenfox1505** [godotengine/godot#36738]
**Godot version:** 3.2

**OS/device including version:** Pop_OS! 19.10

**Issue description:** `Align Transform with View` moves the view. This makes it very hard to make a minor adjustment after this button has been pressed or copy the same transform to multiple objects. (it's been a few years but) My experience with Unreal and Unity is that they do not move the view while doing this action.

**Steps to reproduce:** In 3d preview, select a camera node (or any spacial node), click `perspective`, then `Align Transform with View`

**Minimal reproduction project:** Any 3d project

**Comment by 2shady4u** [comment]
@greenfox1505 Heyo! I checked this out and the only thing that needs to be done to make it work
like you prefer is to comment one line:

![alignment](https://user-images.githubusercontent.com/42484461/75832349-4e75de80-5db6-11ea-8c77-ea27def8f295.gif)

The line that has to be commented to achieve this effect is "focus_selection":
![Capture](https://user-images.githubusercontent.com/42484461/75832354-4fa70b80-5db6-11ea-94ed-50e9eddcae12.PNG)

I don't know the original reason why this focus was added, but I do think there's good arguments to be made for the opposite case as well.

**Comment by malbach** [comment]
> I don't know the original reason why this focus was added, but I do think there's good arguments to be made for the opposite case as well.

It was made so you can have an immediate view of the scene (as almost everyone do, we step back after moving something, to have a better overall view), but I have to admit it might be cumbersome in certain cases. 
As @2shady4u noted it can be easily removed, as "focus selection" can be simply accessed with shortcut "F".
