### ISSUE TITLE
Polygon2D with Skeleton2D assigned does not render in the browser with GLES2

### ISSUE THREAD

**Issue by Waridley** [godotengine/godot#36749]
**Godot version:** 3.2

**OS/device including version:** HTML5 (multiple browsers tested on both Windows and Linux)

**Issue description:**
Any Polygon2D with a Skeleton2D assigned to it does not render in the browser with the GLES2 backend enabled. WebGL does not recognize `GL_UNSIGNED_INT` as a valid enum variant for the 3rd argument to `glVertexAttribPointer` in https://github.com/godotengine/godot/blob/416cd715a3f51b7d74676fa7d4c8e34c3c2823c9/drivers/gles2/rasterizer_canvas_gles2.cpp#L337

Changing it to `GL_UNSIGNED_SHORT` or `GL_UNSIGNED_BYTE` causes the polygons to render, but of course transformations of the bones result in mangled textures when they overflow the type.

Switching to GLES3 fixes the issue, but of course this is generally not recommended for HTML5 games, which caused me to dig into the Godot source before even trying this.

**Steps to reproduce:**
In a GLES2 project, create a Polygon2D and Skeleton2D node. The Skeleton2D can have bones in it or not; it will not work either way. Assign the Skeleton2D to the Polygon2D, and export the project to HTML5. The polygon will not render, but If you switch the project to GLES3, it will render properly.

**Comment by Calinou** [comment]
See also #35772, which reports the same issue but on Android.

**Comment by Waridley** [comment]
The Android issue may not have the same root cause, though, because I had no issues getting it to run on Android before trying GLES3.

**Comment by Valeryn4** [comment]
> The Android issue may not have the same root cause, though, because I had no issues getting it to run on Android before trying GLES3. Unless it is device-specific.

I protested on [ this issue](https://github.com/godotengine/godot/issues/35772). Changed GL_UNSIGNED_INT to GL_UNSIGNED_SHORT. I protested on this issue. Changed A to B. The problem was not solved ...

**Comment by akien-mga** [comment]
Fixed by #42119.
