### ISSUE TITLE
freeze at launch with this minimal project

### ISSUE THREAD

**Issue by argento2** [godotengine/godot#36741]
**Godot version:** 3.2.1-rc1_x11

**OS/device including version:** fedora 31

**Issue description:** godot freezes at launch with this minimal project

**Steps to reproduce:** open the minimal reproduction project

**Minimal reproduction project:** create a simple project with 
1 Spatial node with this script attached

```
tool
extends Spatial

func do_something(number: int):
	var itex = ImageTexture.new()

func _ready():
	var thread:= Thread.new()
	thread.start(self, "do_something", 1)
	thread.wait_to_finish()
```

zip file: [bug1.zip](https://github.com/godotengine/godot/files/4278024/bug1.zip)

**Comment by Chaosus** [comment]
Tool scripts are not safe things, this means you can shoot a leg with them and freeze the editor like this.

**Comment by Calinou** [comment]
This is an issue with the script itself (it will freeze the running project if it's a non-tool script as well).
