### ISSUE TITLE
Editing a script without having an open scene results in odd behaviour

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3674]
Steps to reproduce:

1. open a scene
2. open a script from that scene
3. close all scenes
4. attempt to save any change to that script (or any other script)

If we can re-use scripts in more than one scene, it doesnt make sense not to allow editing scripts without an open scene. Right now, without opened scenes, the script editor is unusable.

**Comment by neikeq** [comment]
Is this message the odd behaviour you mention?: _"The operation can't be done without a tree root"_. If that's the case, it's not a bug. The shortcut _Ctrl+S_ is used for saving the current scene and its unsaved resources (including scripts). The shortcut for saving a script is Ctrl+Alt+S, which does nothing for me though (not sure if there is an issue about that). But using _File -> Save_ in the script editor should work.

**Comment by akien-mga** [comment]
That's indeed not a bug as mentioned by @neikeq. Ctrl+Alt+S works fine here to save the script when no scene is open.
