### ISSUE TITLE
Godot 4.0 : Multiple errors in the system console when adding a panorama to an environment

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#36755]
**Godot version:**
Godot Engine v4.0.dev.custom_build.e2b66cacf built on March 2nd

**OS/device including version:**
Windows 64bits Professionnal 10.0.18363

**Issue description:**
When switching a sky environment from procedural sky to panorama, as long as no image is added to the "Panorama" field, the console writes the following error non-stop:

`ERROR: Condition "!panorama.is_valid()" is true.
   at: _draw_sky (servers/visual/rasterizer_rd/rasterizer_scene_high_end_rd.cpp:1300)`

**Steps to reproduce:**
Edit the default environment : replace the procedural sky by a panorama sky

**Bonus question:**
 What happened to the "Sky + color" option in the environment fields?

**Comment by Calinou** [comment]
> What happened to the "Sky + color" option in the environment fields?

You can now control the background and reflected light separately, though I don't know if "Color + Sky" is still available. The opposite now seems to be available though.

**Comment by TheMoye** [comment]
>  I don't know if "Color + Sky" is still available.

This option no longer exists. It's a pity, it's extremely practical, especially in the editor.

![color sky](https://user-images.githubusercontent.com/46683101/75783689-3fb10c80-5d61-11ea-838e-c5e8a0ede6b5.jpg)

> You can now control the background and reflected light separately

I'm not sure, but it doesn't seem to be working. 🤷
If I take the sky out of the background, the sphere's reflection no longer exists.

![reflectedLight](https://user-images.githubusercontent.com/46683101/75784069-f01f1080-5d61-11ea-869b-26eb329f8584.jpg)

**Comment by akien-mga** [comment]
Tested in latest `master`, changing Sky materials doesn't seem to trigger errors anymore.
