### ISSUE TITLE
Particles (3D) are never paused

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3675]
Steps to reproduce:
1. Add a Particle system to your 3d scene
2. setup a way to pause the game
3. run and pause the game. The particle system is still running as usual

Particles2D are working fine and are paused correctly.

**Comment by nunodonato** [comment]
this is still valid for 3.0. can you re-tag, @akien-mga ? :)

**Comment by reduz** [comment]
this got worse, neither particles are actually paused now :D leaving open
