### ISSUE TITLE
Godot 4.0 : Cannot move a file to another folder by right-clicking, Error 'dir_selected' Method expected 2 arguments, but called with 1

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#36753]
**Godot version:**
Godot Engine v4.0.dev.custom_build.e2b66cacf built on March 2nd

**OS/device including version:**
Windows 64bits Professionnal 10.0.18363

**Issue description:**
When I try to move a file between folders, nothing happens and I get the following error in the Windows system console : 

`ERROR: Error calling from signal 'dir_selected' to callable: FileSystemDock::_move_operation_confirm : Method expected 2 arguments, but called with 1..
   at: emit_signal (core/object.cpp:1210)`

But it works by dragging and dropping

**Steps to reproduce:**
Just try to move a file to another folder by right-clicking

**Minimal reproduction project:**
Create a new project, create a folder, try to move `default_env.tres` or `Icon.png` by right-clicking -> move

**Comment by akien-mga** [comment]
Regression from #36426, I'll fix it.
