### ISSUE TITLE
Godot 4.0 : Save Scene As : GUI does not refresh when changing folders.

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#36757]
**Godot version:**
Godot Engine v4.0.dev.custom_build.e2b66cacf built on March 2nd

**OS/device including version:**
Windows 64bits Professionnal 10.0.18363

**Issue description:**
When I try to save a scene in the `res://scenes/` folder (for the example), double clicking on the folder icons correctly changes the path in the address bar but does not update the folder change in the main viewport.
Changing the file type (.tscn, .scn, .res) forces the view to be updated.

**Steps to reproduce:**
Trying to save a scene in one of the project directories

**Comment by akien-mga** [comment]
Confirme in 48ed841.
