### ISSUE TITLE
Do macros used in source code work correctly?

### ISSUE THREAD

**Issue by Valeryn4** [godotengine/godot#36763]
**Godot version:**any

**OS/device including version:**anu

**Issue description:**
Why does a macro substitute an empty variable when checking?
```cpp
#define ERR_FAIL_COND(m_cond)                                                                          \
	if (unlikely(m_cond)) {                                                                            \
		_err_print_error(FUNCTION_STR, __FILE__, __LINE__, "Condition \"" _STR(m_cond) "\" is true."); \
		return;                                                                                        \
	} else                                                                                             \
		((void)0)
```

example:
```cpp
void foo() {
   ERR_FAIL_COND(var1 != nullptr)
   var2 = Vector2(1,2);
}
```
When using a macro, wouldn't the code look like this?
```cpp
void foo() {
   (void(0))var2 = Vector2(1,2);
}
```

It is correct?
Why not do that?
What is the meaning of the “else” operator?

```cpp
#define ERR_FAIL_COND(m_cond)                                                                          \
	if (unlikely(m_cond)) {                                                                            \
		_err_print_error(FUNCTION_STR, __FILE__, __LINE__, "Condition \"" _STR(m_cond) "\" is true."); \
		return;                                                                                        \
	} 

```

Since there are many compilers, I fear that not everything may work correctly.
Is this an attempted appropriation?

**Comment by Valeryn4** [comment]
apparently there is this bug)
```cpp
_ALWAYS_INLINE_ void *operator new(size_t p_size, void *p_pointer, size_t check, const char *p_description) {
	//void *failptr=0;
	//ERR_FAIL_COND_V( check < p_size , failptr); /** bug, or strange compiler, most likely */

	return p_pointer;
}
```
When a macro expands, it looks like this!
```cpp
_ALWAYS_INLINE_ void *operator new(size_t p_size, void *p_pointer, size_t check, const char *p_description) {
	(void(0))return p_pointer;
}

```

**Comment by akien-mga** [comment]
```
void foo() {
   ERR_FAIL_COND(var1 != nullptr)
   var2 = Vector2(1,2);
}
```

That's invalid and should fail compiling. The `(void(0))` is there specifically to enforce having a semicolon at the end of the macro call.

**Comment by akien-mga** [comment]
> apparently there is this bug?
> 
> ```c++
> _ALWAYS_INLINE_ void *operator new(size_t p_size, void *p_pointer, size_t check, const char *p_description) {
> 	//void *failptr=0;
> 	//ERR_FAIL_COND_V( check < p_size , failptr); /** bug, or strange compiler, most likely */
> 
> 	return p_pointer;
> }
> ```
> 
> When a macro expands, it looks like this!
> 
> ```c++
> _ALWAYS_INLINE_ void *operator new(size_t p_size, void *p_pointer, size_t check, const char *p_description) {
> 	(void(0))return p_pointer;
> }
> ```

It's in a comment and should stay in a comment, no? So it would expand to:
```
_ALWAYS_INLINE_ void *operator new(size_t p_size, void *p_pointer, size_t check, const char *p_description) {
	//void *failptr=0;
	//(void(0)); /** bug, or strange compiler, most likely */

	return p_pointer;
}
```
which is not a problem.

**Comment by vnen** [comment]
This is not really an issue and the question was already answered, so I'm closing this.
