### ISSUE TITLE
get_node(node_path) for a path from a sub-scene can find node, game crashes

### ISSUE THREAD

**Issue by huhund** [godotengine/godot#36766]
Godot 3.2

get_node(node_path) for a path from a sub-scene can find node.

---
Create a 3d scene and add following script:
```
extends Spatial
func _ready():
	var sub_scene = get_node("SubScene")
	print("sub scene: " + sub_scene.name)
	var node_path = sub_scene.node_path
	print("node path: " + node_path)
	var sub_node = get_node(node_path)
	print("sub node: " + sub_node.name)
```
Create 3d sub-scene, add this script
```
extends Spatial
export(NodePath) var node_path
```
Create a spatial node in this scene, link it to the NodePath member.
Link the sub-scene int the main scene.

Run the main scene.

Game crashes with node not found when trying to acquire the node in the sub-scene via the node_path.

**Comment by Zireael07** [comment]
Get_node() is relative to the object you're calling it from, so you just effectively skipped sub_scene.
Use sub_scene,get_node(node_path).

**Comment by groud** [comment]
Sorry, but what you have here is likely a bug with your project, not with the engine.
Please use the other [community channels](https://godotengine.org/community) to ask for help first.

**Comment by huhund** [comment]
You are correct. Now I look like and idiot for for posting a bug report. Sorry for wasting your time :(.

**Comment by groud** [comment]
No problem. :)
