### ISSUE TITLE
Errors in the Editor from core classes?

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3676]
I'm getting two odd errors reported in the debugger when working with the release candidate, these errors don't appear to be related to anything in my project, the errors are always present when I'm working in this release candidate, if this error isn't present for others I'm not sure how to recreate the issue. System is Windows 10, graphics card is Geforce 780. Here are the specific errors being reported:

Type: Error
Description:
Time: 0:00:00:0340
C Error: Condition '!elem' is true. returned: __null
C Source: core/rid.h:146
C Function: get

Type: Error
Description:
Time 0:00:00:0342
C Error: Condition '!texture' is true
C Source drivers/gles2/rasterizer_gles2.cpp:1268
C Function: texture_set_flags

**Comment by bojidar-bg** [comment]
What is the status on current master? (I don't think its fixed, but still)

**Comment by akien-mga** [comment]
Assumed fixed in master, I haven't seen similar reports recently.
