### ISSUE TITLE
ColorPicker's size theme constants don't have effect

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#36761]
**Godot version:**
3.2

**Issue description:**
So there's stuff like `h_width`, `sv_width` and `sv_height` in ColorPicker, but changing them does nothing.

**Steps to reproduce:**
1. Add a ColorPicker
2. Set `sv_width` to some insane value like 100000
3. Run the game
4. The ColorPicker still has default size

**Comment by Calinou** [comment]
Should these constants also be renamed? I have no idea what they do without looking at the class reference :slightly_smiling_face:

**Comment by BigRed-118** [comment]
In https://github.com/godotengine/godot/blob/master/scene/gui/color_picker.cpp, it looks like those constants are set once at creation and then not used again. I tried throwing a call in one of the update functions to set the uv size using sv_width and sv_height and the ColorPicker changed. It might take a little work to make sure the overall ColorPicker is formatted correctly with each change.
