### ISSUE TITLE
a bug in array.erase()

### ISSUE THREAD

**Issue by dijam8** [godotengine/godot#36770]
**Godot version:**
3.2
**OS/device including version:**
ubuntu 18.4 / hp 620
**Issue description:**
i am working on a project managing program and i want to use an array to determine tasks bars position so i am using the array.find() function to find the bar that have been moved from the "to do list" to "in progress list" so all bars have a special number in its script and in the control root script 
and i am sending the special number from the bar node to the control root node via a signal then store it in the array 
then when i want to move the bar from the first list to the second list i do it via the mouse 
then i use a signal to determine wish node the mouse is colliding with and sending the selected nodes special number to the control root then i use array.find() to find the position of the special number in the array then i store it in a "var" then i use array.erase(var) to erase it
it all sound fine but the problem is that when i move so many bars to the white bar  the array.erase() dont work any more , some times it erase nothing or erase  some thing but  it is the  wrong one
i will put the full project bellow and hire some screen shots .

![Screenshot from 2020-03-03 16-27-19](https://user-images.githubusercontent.com/50689412/75794341-f23c9b80-5d70-11ea-93dd-46f817ca0b17.png)
![Screenshot from 2020-03-03 16-27-35](https://user-images.githubusercontent.com/50689412/75794349-f49ef580-5d70-11ea-9399-9552a3f8e512.png)
![Screenshot from 2020-03-03 16-27-44](https://user-images.githubusercontent.com/50689412/75794356-f8cb1300-5d70-11ea-9534-19bc7d1d034e.png)
![Screenshot from 2020-03-03 16-28-02](https://user-images.githubusercontent.com/50689412/75794360-fb2d6d00-5d70-11ea-9939-617077afea3c.png)
![Screenshot from 2020-03-03 16-28-13](https://user-images.githubusercontent.com/50689412/75794370-fe285d80-5d70-11ea-977e-c475919b8573.png)
![Screenshot from 2020-03-03 16-28-24](https://user-images.githubusercontent.com/50689412/75794373-008ab780-5d71-11ea-965b-2bf668edf68a.png)
![Screenshot from 2020-03-03 16-28-32](https://user-images.githubusercontent.com/50689412/75794379-0385a800-5d71-11ea-8e7f-09f94a847cd8.png)
![Screenshot from 2020-03-03 16-28-45](https://user-images.githubusercontent.com/50689412/75794390-05e80200-5d71-11ea-95b1-5ba982fa5e22.png)
![Screenshot from 2020-03-03 16-29-07](https://user-images.githubusercontent.com/50689412/75794400-084a5c00-5d71-11ea-9947-8261b7e47549.png)

![Screenshot from 2020-03-03 16-26-58](https://user-images.githubusercontent.com/50689412/75794333-ef41ab00-5d70-11ea-9bf0-32f133940d5d.png)
  
**Steps to reproduce:**
declare an array then use the array.find() to find multiple elements in the array so many times 
**Minimal reproduction project:**

[to do , and progress bar.zip](https://github.com/godotengine/godot/files/4282313/to.do.and.progress.bar.zip)

**Comment by 2shady4u** [comment]
@dijam8 I downloaded your project and played around with it for a bit.

**Comment by dijam8** [comment]
i am sorry i was thinking that erase() is remove()
