### ISSUE TITLE
RayCast2D force_raycast_update() not having any effect on my project

### ISSUE THREAD

**Issue by gabrielf82** [godotengine/godot#36775]
**Godot version: 3.2.stable.official

**OS/device including version: Windows10

**Issue description: I have a project developed with 3.1.2 and the RayCast2D force_raycast_update() works just fine. When I open the same project on 3.2 it does not work. I narrowed it down to the force_raycast. When I comment the RayCast2D force_raycast_update() line on 3.1.2 it generates the same error as the 3.2.

**Steps to reproduce: call RayCast2D force_raycast_update() and see if it works on 3.2

**Comment by kuruk-mm** [comment]
Can you upload a minimal reproduce project?

Thanks!

**Comment by Calinou** [comment]
I'll close this as @gabrielf82  didn't upload a minimal reproduction project in time.

The issue can be reopened if someone uploads a minimal reproduction project.
