### ISSUE TITLE
RayCast2D collision fails when any TileMap cell is set to -1

### ISSUE THREAD

**Issue by juancolacelli** [godotengine/godot#36778]
**Godot version:**
3.2.stable.official (Steam)

**OS/device including version:**
macOS Catalina version 10.15.2 (19C57)

**Issue description:**
When I set_cell to -1 in a TileMap, RayCast2D stops colliding with any of it's cells for a short period.

**Steps to reproduce:**
- Create a scene
- Add a TileMap (and TileSet)
- Add a RayCast2D colliding with a cell (tile)
- Add a Timer (simulating runtime)
- Connect Timer timeout with a function that makes a set_cell to -1
- Check RayCast2D is_colliding() and it will return false for a short period

**Minimal reproduction project:**
[tilemap_raycast.zip](https://github.com/godotengine/godot/files/4284929/tilemap_raycast.zip)

**Comment by juancolacelli** [comment]
I forgot to mention that the only way to make it work, it's calling force_raycast_update() just before checking if is_colliding().

**Comment by aaronfranke** [comment]
This isn't specific to -1, it occurs with any value.

This is intended behavior. As stated in the documentation:

https://docs.godotengine.org/en/latest/classes/class_tilemap.html#class-tilemap-method-set-cellv

> Note: Data such as navigation polygons and collision shapes are not immediately updated for performance reasons.
> 
> If you need these to be immediately updated, you can call update_dirty_quadrants.

Before opening issues, please read the documentation.
