### ISSUE TITLE
Particles (3D):: The color phases don't work

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#3678]
To give more information, the color phase feature in the 3D particle settings are broken for all channels including alpha (though the 2D particles work just fine).

A screenshot to illustrate the problem
![godot_bug](https://cloud.githubusercontent.com/assets/10081256/12997295/7903051e-d0fd-11e5-9f62-35e43b5dd446.jpg)

---------------------------------------------------------
To see for yourself, simply open the 3D navmesh demo (in the pack of demos available from the main site) and inspect the particle object. The object already has color phases set, but none of them work.

This has been an issue for a while (at least since version 1), so it would be nice to see it fixed for version 2.

**Comment by Algrin6** [comment]
@Ace-Dragon I'd say it's not a full bug, but a bad default setup. To make color phases working, you should click Particles' "Material" property (right arrow), and there check "Use Color Array" flag.
Checking that flag in such cases has been need since far times.

**Comment by kubecz3k** [comment]
Just tested this and the colors are working. Just like @Algrin6 said check 'use color array' inside the material.
