### ISSUE TITLE
Destructive behavior when rename a c# script from editor

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#36785]
**Godot version:**
3.2 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
When I rename a c# script from editor I lose part if not all content of it.  
Hours of  work lost. It happen of my trust in a "stable" godot version
**Steps to reproduce:**
Rename a c# script
I think I guessed what happened.: 
When the editor make a new file it don't use the current script content but it use the content before modify. So It put in the old version content.
**Minimal reproduction project:**
NA. It is easy to check I guess.

**Comment by aaronfranke** [comment]
Can't reproduce, I renamed a script and it is still 100% intact.

**Comment by git2013vb** [comment]
> Can't reproduce, I renamed a script and it is still 100% intact.

To reproduce I think you need to change the content save and rename. Also I have both files in Autoload (Singletons) Maybe is this the problem.
 As I said it is possible the issue came out when the file is modified.

**Comment by akien-mga** [comment]
Can you still reproduce this issue in 3.3 or later?

**Comment by git2013vb** [comment]
I will try

**Comment by aaronfranke** [comment]
@git2013vb Try creating a new empty project, and copying the `.csproj` into your own project. Godot now defaults to the new `.csproj` format, which doesn't reference scripts by name.

**Comment by git2013vb** [comment]
I deleted all things not necessary any more and it seems a better solution: less code less bugs
I guess we can close this one
