### ISSUE TITLE
ProjectSettings.globalize_path() is not working on exported game.

### ISSUE THREAD

**Issue by AureaFUNSoft** [godotengine/godot#36781]
**Godot version:**
Godot 3.2.stable

**OS/device including version:**
Windows 10

**Issue description:**
I want to get the executable path of my exported game. According to [this](https://godotengine.org/qa/14833/get-the-executables-directory) i can use Globals.globalize_path() to do that. So, in Godot 3.2 the method moved to ProjectSettings.globalize_path() (?,CMIIW). It works well when I play the game from editor. But when I export it the method is not working.

**Steps to reproduce:**
Use my test project below.
Play it directly in editor, it works!
Export, execute, it doesnt work!

**Minimal reproduction project:**
[GlobalizePathBug.zip](https://github.com/godotengine/godot/files/4285717/GlobalizePathBug.zip)

**Comment by mrcdk** [comment]
To get the executable path use [`OS.get_executable_path()`](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-executable-path) `Projectsettings.globalize_path()` may not give you the correct path depending on the system and how it's configured.

**Comment by AureaFUNSoft** [comment]
Oh thank you. I didn't know that method exist. So the `Projectsettings.globalize_path()`, is not suppose to work on exported game?

**Comment by KoBeWi** [comment]
I guess docs should mention it if it's intended.

**Comment by BastiaanOlij** [comment]
I think we need to investigate why this doesn't work, it is kind of important that parsing a path with `user://` or `res://` in it actually results in returning the full path on disk, including on exports.

Simply adding the executable path in front won't work consistently and is not a fix. 

@akien-mga any idea who should know how this is intended to work and why it may fail on exports?

**Comment by BrianMWest** [comment]
Has anyone had a chance to look at this issue? On a Mac build, I see this behavior in 3.2 if I export without debug. If I export with debug enabled, then the directory works fine. With debug disabled, it does create a directory for `user://` and puts logs in it, but any scripts I have written that access the directory fail

**Comment by Calinou** [comment]
> Has anyone had a chance to look at this issue? On a Mac build, I see this behavior in 3.2 if I export without debug. If I export with debug enabled, then the directory works fine. With debug disabled, it does create a directory for `user://` and puts logs in it, but any scripts I have written that access the directory fail

[Godot 3.2.x is not supported anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to 3.3.3 and test this again.

**Comment by BrianMWest** [comment]
Ah, I actually am on 3.3 stable. Forgot I had upgraded.

Reproduction is simple: An autoload singleton `Save` that looks like:

```
const VERSION := "v3"
const SAVES_DIR := "user://saves.%s" % VERSION

func _ready() -> void:
    var dir := Directory.new()
    if not dir.dir_exists(SAVES_DIR):
        assert(dir.make_dir(SAVES_DIR) == OK)
```

The assert appears to pass. But the directory doesn't appear. At first I thought this might be related to a quotation mark in the configured app run name, but that didn't appear to do anything. If other people are not experiencing the same behavior, could this be a mac specific thing?

**Comment by BrianMWest** [comment]
Ok, I was able to track down my issue. It appears to be unrelated to this issue. It was pointed out to me that rather than `assert` being a non-op in release mode, it actually strips out that entire branch of the script's AST before packaging, so the call to `dir.make_dir(SAVES_DIR)` doesn't get included. The solution is to bind to an error variable and assert against the error variable instead.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 4.x builds?

**Comment by KoBeWi** [comment]
It's already documented.
