### ISSUE TITLE
Godot 4.0  Can not find 'ICD' object in ICD JSON

### ISSUE THREAD

**Issue by Darkheron** [godotengine/godot#36790]
**Godot version:**
Godot Engine v4.0.dev.custom_build.794a56b1c March 2

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When starting an application the following error occurs:

ERROR: WARNING : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loader_icd_scan: Can not find 'ICD' object in ICD JSON file /usr/share/vulkan/icd.d/nvidia_layers.json.  Skipping ICD JSON
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 137194512
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:142)

**Steps to reproduce:**
1: Compile
2: Run

The problem seems to be that the loading algorithm expects the ICD object in the nvidia_layers.json file; however, on my machine, the ICD object is in a seperate file: nvidia_icd.json.
I don't know if that is standard or not.. or what the remediation strategy is, but I though someone should know.
Here Is my local nvidia_layers.json file:
```
{
    "file_format_version" : "1.0.0",
    "layer": {
        "name": "VK_LAYER_NV_optimus",
        "type": "INSTANCE",
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.1.109",
        "implementation_version" : "1",
        "description" : "NVIDIA Optimus layer",
        "functions": {
            "vkGetInstanceProcAddr": "vk_optimusGetInstanceProcAddr",
            "vkGetDeviceProcAddr": "vk_optimusGetDeviceProcAddr"
        },
        "enable_environment": {
            "__NV_PRIME_RENDER_OFFLOAD": "1"
        },
        "disable_environment": {
            "DISABLE_LAYER_NV_OPTIMUS_1": ""
        }
    }
}
```
Here is my nvidia_icd_json file:
```
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.1.109"
    }
}
```
Can provide more info if needed.

**Comment by akien-mga** [comment]
It seems to be done on purpose by the Vulkan-Loader library: https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/loader.c#L4417-L4420

I assume that it still works fine regardless of that warning? After skipping `nvidia_layers.json`, it should parse and succeed loading `nvidia_icd.json`.

I don't know if it's standard for Ubuntu to put `nvidia_layers.json` in `/usr/share/vulkan/icd.d/`, which as the name indicates, is meant for ICDs. I suspect that's a packaging bug on their end.

**Comment by akien-mga** [comment]
> I don't know if it's standard for Ubuntu to put `nvidia_layers.json` in `/usr/share/vulkan/icd.d/`, which as the name indicates, is meant for ICDs. I suspect that's a packaging bug on their end.

Yeah it should likely go either in `/usr/share/vulkan/explicit_layer.d` or `/usr/share/vulkan/implicit_layer.d`.

I would advise filing a bug report against Ubuntu's nvidia drivers packaging. This is not a Godot bug so I'll close it, but feel free to reference this issue in the Ubuntu bug report.

**Comment by akien-mga** [comment]
#36792 should make it appear as a yellow warning instead of a red error now.
