### ISSUE TITLE
Recent Projects in Project Manager doesn't often re-pose items after running or editing projects

### ISSUE THREAD

**Issue by Algrin6** [godotengine/godot#3679]
But it sometimes works. And I haven't noticed some factor that could cause working or not working.
In "editor_settings.xml", recent projects are always being written.
Adding favorites always works.

**Comment by AfterRebelion** [comment]
Didn't run into this issue. Take into account that projects are only moved up on the list if they save an update, not if they are opened, so you can open a project, go back to the Project Manager without making any change, and the list will remain the same as before.

This issue would needs more feedback, and even a rundown testing enviroment to verify it (Nothing crazy, just a folder with a lot of empty projects, and a list of things to do to trigger it).
But with it being two years old, I can see this simply going back to inactivity.
