### ISSUE TITLE
Wrong Documentation on Signal item_selected from OptionButton

### ISSUE THREAD

**Issue by viniciusaportela** [godotengine/godot#36803]
**Godot version:**
3.2.stable

**OS/device including version:**
Windows 10 18363

**Issue description:**
On [docs](http://docs.godotengine.org/en/3.2/classes/class_optionbutton.html) show that the signal **item_selected** from **OptionButton** has the **ID** parameter when it actually the **Index**, that's a small thing but it really confused me at first that passed over 30 min trying to figure out what was wrong (cause I used the id to be the same to index)

**Steps to reproduce:**
1. Create the nodes

![image](https://user-images.githubusercontent.com/46164681/75943859-fc47c280-5e74-11ea-9742-e285598128eb.png)

2. Create the items

![image](https://user-images.githubusercontent.com/46164681/75943886-07025780-5e75-11ea-9de1-e66d97d3d29c.png)

3. Connect item_select

```gdscript
$Option.connect("item_selected", self, 'on_option_changed')
```

4. Start Clicking

**Minimal reproduction project:**
```gdscript
extends Control

func _ready():
	$Option.connect("item_selected", self, 'on_option_changed')
	$Option.remove_item(0)

func on_option_changed(idx):
	print('item changed')
	print(idx)
```

Selecting from bottom to top it returns:

![image](https://user-images.githubusercontent.com/46164681/75944046-72e4c000-5e75-11ea-9cf8-f8bd8aa25ebf.png)

Not 30, 20, 10 as expected

**Comment by aaronfranke** [comment]
Yes, I can confirm that "id" should be changed to "index" in `option_button.cpp` line 344, but I don't know if the same should be done for `item_focused`.

However, while testing, I encountered really weird behavior.

![Screenshot from 2020-03-05 02-58-41](https://user-images.githubusercontent.com/1646875/75960108-7be18b80-5e8d-11ea-948f-9d63395c1e0c.png)

Code:

```gdscript
func on_option_changed(idx):
	print('item changed')
	print(idx)
	print($Option.get_selected_id())
	print($Option.get_item_id(idx))
	print($Option.get_item_index($Option.get_item_id(idx)))
```

Output:

```
item changed
1
20
20
1
item changed
0
10
10
0
```

Seems that the index in the item list editor does not match up with the index at runtime. The item with an ID of 20 has an index of 2 in the editor, but when selected, it has an index of 1. I'm also unable to reselect "Item 0" with an ID of 0.

**Comment by zak-grumbles** [comment]
Submitted merge request #37303 as a fix for this, although the changes only cover fixing documentation and the ADD_SIGNAL call in code and do not address the editor-runtime index mismatch.
