### ISSUE TITLE
signals in subclasses not connectable

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#36804]
**Godot version:** master branch

**OS/device including version:** arch/linux/manjaro

**Issue description:**

with the refactoring of gdscript, the change from

blah.connect("from", self, "to"); 
to:
blah.from.connect(self.to)

does not work if a subclass is used.

I have a class called InputActions which has:

class Action:
	
	# basically just pressed or just released
	signal pressed(p_event);
	signal released(p_event);

if I create an action I cannot do this:

action.pressed.connect(self.to)

I get an error:

Invalid get index 'pressed' (on base: 'Reference ()').

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by ThakeeNathees** [comment]
according to the godot doc (https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html) you can only connect a signal like 
```$Timer.connect("timeout", self, "_on_Timer_timeout")```
but you're trying to do something like this
```$Timer.timeout.connect(self._on_Timer_timeout)```
and that's why you are getting the error like : `invalid get index 'timeout'`

```gdscript
extends Node2D

class MyClass:
	signal my_signal

	func _recv():
		print("receved signal")

func _init():
	var instance = MyClass.new()
	instance.my_signal.connect(instance._recv)
	## change the above line to this
	instance.connect("my_signal", instance, "_recv" )
```

**Comment by MennoMax** [comment]
@ThakeeNathees Callables were recently introduced, which is why there aren't in the docs yet. Heres the relevant article; https://godotengine.org/article/core-refactoring-progress-report-1 (search for callables)

**Comment by ZingBlue** [comment]
Does this affect Godot 3.2 or am I having a different issue?

**Comment by supagu** [comment]
I can't even seem to get any signals specified in gdscript classes and connect to them...

**Comment by akien-mga** [comment]
Fixed in current `master` (as per https://github.com/godotengine/godot/pull/37708#issuecomment-783710900).
