### ISSUE TITLE
move_and_slide has different results with different fps

### ISSUE THREAD

**Issue by juancolacelli** [godotengine/godot#36805]
**Godot version:**
3.2.stable.official (Steam)

**OS/device including version:**
macOS Catalina 10.15.2

**Issue description:**
When I "jump" using move_and_slide with 60 fps and 10 fps, I'm having different results (jump height).

```gdscript
extends Node
var motion := Vector2(0, 10)
func _process(delta):
  if $KinematicBody2D.is_on_floor() and Input.is_action_just_pressed("ui_accept"):
    motion.y = -100
  else:
    motion.y += 10
  $KinematicBody2D.move_and_slide(motion, Vector2.UP)
  if motion.y == 0:
    print($KinematicBody2D.position.y)
```

60 fps:
196.642624
196.753326
196.753433
196.753403
196.753448

10 fps:
150.681808
150.29213
150.920074
150.920074
150.920074

**Steps to reproduce:**
- Create a scene with a StaticBody2d (used as a floor) and a KinematicBody2d (the player)
- Use the code put above
- Check the numbers with regular fps
- Limit fps to 10
- Check the numbers again

![Screen Shot 2020-03-05 at 2 30 09 AM](https://user-images.githubusercontent.com/423381/75951420-c44b7a00-5e8a-11ea-86aa-c140ea7bd6a6.png)

**Minimal reproduction project:**
[test_fps.zip](https://github.com/godotengine/godot/files/4291146/test_fps.zip)

**Comment by Duroxxigar** [comment]
`move_and_slide()` should be used in `_physics_process()` and not `_process()`

**Comment by aaronfranke** [comment]
This definitely needs to be documented better, however. We'll use this issue to track that.

**Comment by nathanwfranke** [comment]
We should have warnings between `_process` and `_physics_process`

`Input` should have warnings in `_physics_process`
`move_and_slide`, `move_and_collide` should have warnings in `_process`

**Comment by theoway** [comment]
I'm new to Godot contribution community. I'd like to work on this issue.

**Comment by aaronfranke** [comment]
@theoway No need to ask permission, you can just get started. Be sure to read [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) (or watch [this video](https://www.youtube.com/watch?v=0XKy8YpP5Ww)) to get familiar with the pull request workflow. The files you want to edit are `doc/classes/KinematicBody2D.xml` and `doc/classes/KinematicBody.xml`.

**Comment by Calinou** [comment]
If #33653 is merged, you could use `move_and_slide()` in `_process()` by passing the `delta` parameter as follows:

```gdscript
func _process(delta):
    motion = Vector2(100, 0)
    move_and_slide(motion, delta)
```

**Comment by theoway** [comment]
@aaronfranke Thanks for the information. I'll start editing the documentation.

**Comment by theoway** [comment]
I've made a PR for change in docs. #36849
