### ISSUE TITLE
Debugger show large variable as [null] when getting Image from Viewport texture (the reference still works)

### ISSUE THREAD

**Issue by bitsydoge** [godotengine/godot#36801]
**Godot version:**
Issue in 3.2 and and 3.2.rc1
No issue in 3.1.2

**OS/device including version:**
Tested on Windows on two computer but the bug doesn't appear in 3.1.2 so I didn't tried in another OS because I assumed it's not a OS related issue

**Issue description:**
When I get the image from the texture of an instanced Viewport the resulting image (duplicate() or not) appear [null] in the debugger but print() actually print it's ID and the use of this var work.

Even other var appeared to be [null] in the debugger but the only problem I isolated was the viewport one. (I'll link a project with the viewport bug)

**Steps to reproduce:**
get_texture().get_data() from a Viewport inside your scene and assign it in a var

**Minimal reproduction project:**
Isolated Viewport
[Bug-null-ref-debugger.zip](https://github.com/godotengine/godot/files/4289354/Bug-null-ref-debugger.zip)

![image](https://user-images.githubusercontent.com/471393/75916101-fa233b00-5e57-11ea-8ee7-68bdff56abae.png)

Another little project with this issue but when I was writing that issue and changing project multiple time with the minimal it work now (but the minimal still bug)

https://github.com/Coldragon/godot-voronoi-shader-generator

![image](https://user-images.githubusercontent.com/471393/75916839-5470cb80-5e59-11ea-8c96-376ef7f7bd37.png)
![image](https://user-images.githubusercontent.com/471393/75916889-6ce0e600-5e59-11ea-929f-a8e261a92051.png)

The bug is inconsistent for me now exept for the minimal project, it's really weird

edit : you can see the conversation I got with another user from the Discord 
https://discordapp.com/channels/212250894228652034/477544613511692358/684839269033967639

**Comment by baptr** [comment]
I updated the original MRP to work at HEAD and confirm this matches #74148:

Fresh MRP: [36801.zip](https://github.com/godotengine/godot/files/10858458/36801.zip)

With:

```
@onready var viewport = $SubViewport

func _ready():
	var tex = viewport.get_texture()
	print(tex)
	var img = tex.get_image()
	print(img)
	var dims = img.get_size()
	print(dims)
	var size = img.get_data().size()
	print(size)
	pass # break here
```

Locally I get:
![image](https://user-images.githubusercontent.com/1522777/222078421-7b8f6192-f719-4ece-a818-c95925c98366.png)

Output:
```
<ViewportTexture#-9223372010313219669>
<Image#-9223372010229333471>
(1024, 1024)
3145728
```

Debugger errors:
```
W 0:00:00:0738   Node2D.gd:14 @ _ready(): Variable img too large to serialize for debugger: 3145964 > 1048576
  <C++ Source>   core/debugger/debugger_marshalls.cpp:83 @ serialize()
  <Stack Trace>  Node2D.gd:14 @ _ready()
```

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/39465, as this is due to the same cause.
