### ISSUE TITLE
Even though I have the full requirments for Godot Mono version the scene still woul'dnt run and will show this error here

### ISSUE THREAD

**Issue by Crispian-Troyo369** [godotengine/godot#36818]
**Godot version:**
Godot 3.2 version stable mono official
**OS/device including version:**

**Issue description:**
It would'nt run my scene and would show that I did'nt have any of the existing requirments even though I have.
**Steps to reproduce:**
1) Install The Godot Mono for C# users.
2) Install .Net Framework latest version.
3) Install MSBuild Visual studio extension
4) Install Mono latest version
5) Start Godot
6) Create Panel node with two child Label node and Button node
7) Play the scene
8) And boom I have the error

**Minimal reproduction project:**

[This.zip](https://github.com/godotengine/godot/files/4293780/This.zip)

**Comment by Calinou** [comment]
> **Minimal reproduction project:**
> idk what does this mean sorry

See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project

**Comment by akien-mga** [comment]
> And boom I have the error

What is "the error"?

**Comment by Crispian-Troyo369** [comment]
> > And boom I have the error
> 
> What is "the error"?

I copied this from the error log, so here:

Project "First.sln" (Build target(s)):
	Message: Building solution configuration "Tools|Any CPU".
	Project "First.csproj" (default targets):
		C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\A\Desktop\My Projects\First\First.csproj]
	Done building project "First.csproj" -- FAILED.
Done building project "First.sln" -- FAILED.

**Comment by akien-mga** [comment]
You need .NET Framework 4.7 exactly, not the latest version.

**Comment by Crispian-Troyo369** [comment]
> You need .NET Framework 4.7 exactly, not the latest version.

Well that fix it. What a relief from frustration lmao. Thank you sir!

**Comment by Calinou** [comment]
Closing, as the original issue has been solved.
