### ISSUE TITLE
Extends keyword prevents eol or semicolon from being found

### ISSUE THREAD

**Issue by lolzyman** [godotengine/godot#36811]
**Godot version:**
3.1.2 Stable

**OS/device including version:**
Laptop
Linux Mint 19.1 Cinnamon
Cinnamon Version 4.0.10
Linux Kernel 4.15.0-20-generic
Intel Core i3-7100U

**Issue description:**
I am trying to use the following segment of code

```
if variable extends Array:
	pass
```
I receive an error saying  ": expected at end of line"

if i try doing the following

```
var condition = self extends Node2D
if condition:
	pass
``` 
 I receive an error saying "expected end of statement (var)"

**Steps to reproduce:**

To reproduce this error use the following code
```
var _dummy = self extends Node
```

**Minimal reproduction project:**
I have posted a project containing the error on Github [here](https://github.com/lolzyman/Extends_Error_Project)

**Comment by akien-mga** [comment]
That's an invalid use of `extends`, which is meant for declare class inheritance, not testing it:
```
extends Node

...

func _ready():
     if some_node is KinematicBody:
         print("That's how to test class inheritance.")
```

Still, the error messages could be improved.

**Comment by lolzyman** [comment]
Alright, Thank you for that clarification. I found a [tutorial](https://godotengine.org/qa/2849/how-do-i-get-instanceof-an-object) on the forums that indicated that indicated that this was possible. Was this a functionality in previous versions?

**Comment by akien-mga** [comment]
This was changed in #8933 for Godot 3.0, that Q&A answer predates it. I'll add an updated answer there.

**Comment by lolzyman** [comment]
Alright. Thanks for all your help and the work you do for Godot.

**Comment by akien-mga** [comment]
We can keep this open as the errors returned by the parser are not clear enough.
