### ISSUE TITLE
StringName changes pollute projects git diffs

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#36826]
**Godot version:**
4.0.dev.custom_build. 42595085a

**OS/device including version:**
Ubuntu 19.10

**Issue description:**

Recent changes in StringName, causes adding to some names @ at the beginning.

```
 "base": "Button",
-"class": "CircleButton",
-"language": "GDScript",
+"class": @"CircleButton",
+"language": @"GDScript",
 "path": "res://source/interface/hud/components/buttons/CircleButton.gd"
 }, {
 "base": "PanelContainer",
-"class": "CombatPlate",
-"language": "GDScript",
+"class": @"CombatPlate",
+"language": @"GDScript",
```

This is part of fixed issue #36438.

**Steps to reproduce:**

1. Open project in editor
2. Save any scene
3. Look at scene in text editor

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project

**Comment by kuruk-mm** [comment]
This is caused on "VariantWriter::write" to identify when is a StringName
```
case Variant::STRING_NAME: {

	String str = p_variant;

	str = "@\"" + str.c_escape() + "\"";
	p_store_string_func(p_store_string_ud, str);

} break;
```

And is discriminated in get_token when we use:

```
case '@': {
	cchar = p_stream->get_char();
	if (cchar != '"') {
		r_err_str = "Expected '\"' after '@'";
		r_token.type = TK_ERROR;
		return ERR_PARSE_ERROR;
	}

	string_name = true;
	[[fallthrough]];
}
```

and transformed to Variant on

```
if (string_name) {
	r_token.type = TK_STRING_NAME;
	r_token.value = StringName(str);
	string_name = false; //reset
} else {
	r_token.type = TK_STRING;
	r_token.value = str;
}
```

Are we sure it's a bug?

**Comment by kuruk-mm** [comment]
I was thinking about this.
And no matter if is a bug or not, I think it's something that generate inconsistent.

The objetive of project.godot format, is to be predictable, and this is not easy to figure out why is putting @ or not.

If someone can give me a feedback from I'm saying, I will review a way to avoid to put @ on project.godot

**Comment by reduz** [comment]
This is on purpose, although we are discussing changing @ to &.
