### ISSUE TITLE
when export android apk, my android gdnative so not export into apk

### ISSUE THREAD

**Issue by zhangshiqian1214** [godotengine/godot#36827]
**Godot version: 3.2.stable.offical

**OS/device including version: android

**Issue description: I write a module libsproto.so by gdnative, and then I export apk, I open the apk as zip. No libsproto.so find in apk. And I also can not find the solution in https://docs.godotengine.org/zh_CN/latest/tutorials/plugins/gdnative/gdnative-cpp-example.html

![QQ截图20200306012416](https://user-images.githubusercontent.com/9353330/76007582-3c787500-5f49-11ea-941a-6c58f0f064ae.jpg)

**Comment by bruvzg** [comment]
On Android all libs should be exported to the `lib/{ABI}/{name.so}` instead of `assets`.
Also make sure correct APIs are specified in the `.gdnlib` (valid ABIs are: "armeabi-v7a", "arm64-v8a", "x86" and "x86_64") and selected in the export settings, `architectures` section.

**Comment by zhangshiqian1214** [comment]
@bruvzg I'm now use godot to export apk,  Do I need use AndroidStudio to build apk.
