### ISSUE TITLE
Change type always says Node

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#36831]
**Godot version:**
3.2

**Issue description:**
When you select Change Type in scene tree, you always see this
![image](https://user-images.githubusercontent.com/2223172/76024148-e4327a80-5f2a-11ea-846c-07c9bc679d37.png)
But the format for this string is `Change %s Type`. It's filled incorrectly.

**Comment by timothyqiu** [comment]
The `%s` part shows the base type of the available types. It shows "Node" when using scene tree's Change Type, and shows "Object" when using Visual Script editor's Change Base Type.

(It means something like: I want to change the type of this `Node` object from `Label` to `AnimationPlayer`.)

**Comment by Calinou** [comment]
Maybe we could change the string so it says `Change Node "MyAnimatedSprite"'s type` to be more explicit.

**Comment by theoway** [comment]
@Calinou Sounds good. I'll start working on it.

**Comment by theoway** [comment]
@Calinou  `void CreateDialog::popup_create(bool p_dont_clear, bool p_replace_mode, const String &p_select_type) ` 
This function is called to create the dialog for changing the node. Looking at the parameters, it would make sense to change the message to `Change Node MyNodeType`. This way the users can know the type of the node they are going to change without closing the dialog for checking.

**Comment by Janglee123** [comment]
I think `convert` is more suitable than `change`. i.e. `Convert MyNode from "CurrentType"`

**Comment by theoway** [comment]
@Janglee123 Much better. I'll make a PR for this.
