### ISSUE TITLE
Running with AnimationPlayer selected opens Animation tab

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#36836]
**Godot version:**
3.2

**Steps to reproduce:**
1. Add AnimationPlayer
2. Select it
3. Switch to Output tab or just close Animation
4. Run the game
5. Animation tab opens upon run

**Comment by kuruk-mm** [comment]
I couldn't reproduce it on Ubuntu 16.04

**Comment by dreamsComeTrue** [comment]
Also tested that on Fedora and Win10 - for both current master and 3.2.
@KoBeWi - can you prepare a GIF of something that shows your setup? I did literally 1:1 of what you wrote above - and issue doesn't appear.

**Comment by KoBeWi** [comment]
![m0m6HTS60t](https://user-images.githubusercontent.com/2223172/76257431-fb86a600-6251-11ea-87bd-3c16cc8f892c.gif)

**Comment by tom-jk** [comment]
Can't reproduce in 3.2.stable or 3.2.2.stable on linux mint 18.3. Performed given steps, plus changing editor settings for things that seemed most likely to be related or to match the gif (eg. auto switch to remote scene tree on play). Strange though, I'm fairly sure I've had this (or very similar behaviour) before too... :confused:

**Comment by KoBeWi** [comment]
Looks fixed.
