### ISSUE TITLE
XBox 360 triggers report wrong analog value after pressed

### ISSUE THREAD

**Issue by NPohl** [godotengine/godot#3683]
In the joysticks demo, axis 6 and 7 start with a value of 0.0. They show correct values while I press one or both triggers. But once released after pressing, they will default to 0.5 in idle position (instead of 0.0).

I'm using a XBox 360 Wireless Receiver with an XBox 360 Wireless Gamepad on Windows 10 and the latest godot version (2.0 RC1, 09 February 2016 12:22 AM).

**Comment by akien-mga** [comment]
CC @Hinsbart @punto-.

**Comment by NPohl** [comment]
Wow, thanks! That was quick!
I downloaded and built the source, works now.

Cheers
