### ISSUE TITLE
Contextual autocompletion works for wrong arguments

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#36835]
**Godot version:**
3.2

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/76024854-1c868880-5f2c-11ea-807e-da19dcd67e33.png)
![image](https://user-images.githubusercontent.com/2223172/76024898-2a3c0e00-5f2c-11ea-8d74-6aa7cd37f486.png)
Only first argument should suggest animation names. Likely happens with all similar nodes.

**Comment by ThakeeNathees** [comment]
> Only first argument should suggest animation names. Likely happens with all similar nodes.
what are the other nodes have this issue ??
@KoBeWi

**Comment by KoBeWi** [comment]
Seems like this is the only one actually.
