### ISSUE TITLE
func name autocomplete doesn't appear until you type something

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#36833]
**Godot version:**
3.2

**Issue description:**
Title.
![image](https://user-images.githubusercontent.com/2223172/76024664-c9143a80-5f2b-11ea-8d17-c75dc7bbcc13.png)
![image](https://user-images.githubusercontent.com/2223172/76024672-cfa2b200-5f2b-11ea-863d-b433b98580d1.png)
You should be able to use Ctrl + Space at least to force the popup.

**Comment by ThakeeNathees** [comment]
Also if you type the letter v and expect auto complete for var inside a class (not inside a function) or on an empty script it doesn't show any auto complete option. 

As I was debugging it the cursor token (`TOKEN_CURSOR`) didn't generated for the case I've mentioned and the one one the issue above.

But inside a function typing v  there is `TOKEN_CURSOR` at the generated tokens, also the above issue after the `func` keyword there is no `TOKEN_CURSOR` only an EoF token but as soon as you type a letter there is a cursor token generated
