### ISSUE TITLE
ARVR Controller reports is_button_pressed with the return type int instead of bool

### ISSUE THREAD

**Issue by haekb** [godotengine/godot#36841]
**Godot version:**
3.2 Mono

**OS/device including version:**
Windows 10 Pro

**Issue description:**
`is_button_pressed` reports the return type of int instead of bool. Not a huge problem, but a weird inconsistency that makes it slightly annoying to use in C#. 

Code can be found here, and it looks like it would only ever return true or false.
https://github.com/godotengine/godot/blob/2f237d181b6fd769b52bded49cafc9bc5eb9f087/scene/3d/arvr_nodes.cpp#L303

`is_button_pressed` docs:
https://docs.godotengine.org/en/stable/classes/class_arvrcontroller.html#class-arvrcontroller-method-is-button-pressed

`is_joy_button_pressed` docs:
https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-is-joy-button-pressed

**Comment by BastiaanOlij** [comment]
That's pretty silly of me! :)
