### ISSUE TITLE
All textures become black

### ISSUE THREAD

**Issue by Toxlc** [godotengine/godot#36857]
![Снимок](https://user-images.githubusercontent.com/44618834/76094646-c7f31400-5fe4-11ea-9c27-2c5affed40a6.PNG)
![Снимок2](https://user-images.githubusercontent.com/44618834/76094656-cb869b00-5fe4-11ea-8ff1-b7f9cb624def.PNG)

3.2.1

Win 10 1909

All textures become black

Just move cam randomly

3D platformer with raycast and gridmap

**Comment by FlashDaggerX** [comment]
Could you possibly provide a minimal reproduction project? If not, could you tell us how you came across the bug (steps to reproduce the bug)?

**Comment by Anutrix** [comment]
@Toxlc Does this happen with GLES3 only?

**Comment by Calinou** [comment]
I'll close this issue as OP didn't provide a minimal reproduction project in time. Moreover, there's little information to work with (we don't know which GPU they're using).
