### ISSUE TITLE
(Source file... could not be found error) how to fix?

### ISSUE THREAD

**Issue by Crispian-Troyo369** [godotengine/godot#36850]
**Godot version:**
v3.2.Stable.Mono
**OS/device including version:**
Windows 10
**Issue description:**
(note: The script that Godot does not detect is for sure there in the right place in the path. Please help)

Here's the error log :

Project "Dodge The Creeps.sln" (Build target(s)):
Message: Building solution configuration "Tools|Any CPU".
Project "Dodge The Creeps.csproj" (default targets):
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Csc: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:GODOT_WINDOWS;GODOT_64;GODOT;DEBUG;TOOLS /highentropyva+ /reference:"C:\Users\A\Desktop\My Projects\Dodge The Creeps\.mono\assemblies\Debug\GodotSharp.dll" /reference:"C:\Users\A\Desktop\My Projects\Dodge The Creeps\.mono\assemblies\Debug\GodotSharpEditor.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\System.dll" /debug+ /debug:portable /optimize- /out:".mono\temp\obj\Tools\Dodge The Creeps.dll" /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /utf8output /langversion:7.3 Player.cs Properties\AssemblyInfo.cs Scenes\Player.cs Scripts\Player.cs "C:\Users\A\AppData\Local\Temp\.NETFramework,Version=v4.7.AssemblyAttributes.cs"
Csc: Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn
CSC(0,0): error CS2001: Source file 'C:\Users\A\Desktop\My Projects\Dodge The Creeps\Player.cs' could not be found. [C:\Users\A\Desktop\My Projects\Dodge The Creeps\Dodge The Creeps.csproj]
CSC(0,0): error CS2001: Source file 'C:\Users\A\Desktop\My Projects\Dodge The Creeps\Scenes\Player.cs' could not be found. [C:\Users\A\Desktop\My Projects\Dodge The Creeps\Dodge The Creeps.csproj]

Done building project "Dodge The Creeps.csproj" -- FAILED.
Done building project "Dodge The Creeps.sln" -- FAILED.

**Steps to reproduce:**

1) Create an attached c# script to a node
2) Build and then that error above

**Minimal reproduction project:**
[Dodge The Creeps - Copy.zip](https://github.com/godotengine/godot/files/4298411/Dodge.The.Creeps.-.Copy.zip)

**Comment by groud** [comment]
This is likely a problem with your project and not with the engine. 
As this is not the place to ask for help, but to report bugs, please use the other [community channels](https://godotengine.org/community) first.

**Comment by groud** [comment]
Note that this source file : `C:\Users\A\Desktop\My Projects\Dodge The Creeps\Player.cs` is not in your archive, that's likely the source of your problem.
