### ISSUE TITLE
Cannot open GLES3 projects using NVidia GeForce 9300 GS GPU

### ISSUE THREAD

**Issue by D-TurboKiller** [godotengine/godot#36856]
NOTE: This is a formal request from a fellow member of our Discord servers. Let me know if you require additional info regarding this issue.

**Godot version:**
v3.2 Stable

**OS/device including version:**
Windows 7 Professional SP1 64-bits
CPU: Intel Core i5-2320 @ 3.00 Ghz
GPU: NVidia GeForce 9300 GS (important, see detailed info below)

**GPU detailed info:**
![nvidia gpu 1](https://user-images.githubusercontent.com/61838439/76092570-826c2200-5fb7-11ea-916c-996fec2df8ba.png)
![nvidia gpu 2](https://user-images.githubusercontent.com/61838439/76092587-8a2bc680-5fb7-11ea-8e17-e5e14d9db406.png)

**Issue description:**
I've recently introduced one of your Discord server members to Godot Engine and unfortunately he didn't have any luck trying out the templates. This is what happens:
![gles3 issue](https://user-images.githubusercontent.com/61838439/76093429-d7f4fe80-5fb8-11ea-9e08-ca39d03fad81.png)
I was surprised to find that even the older templates, such as the old 2D Platformer Example (you're a square and have to reach the top to rescue the "princess"), which I'm pretty sure used GLES2, didn't work either. (Do they default to GLES3 now?)
However, by creating a new project that uses GLES2, he has no problems whatsoever. I've come to the conclusion that, while the GPU indicates OpenGL 3.3 support, it's very likely bugged and doesn't work as intended.

**Steps to reproduce:**
Just open any GLES3 project.

**Possible Workarounds:**
1. Using a different machine to alter a project, changing it from GLES3 to GLES2. I've done this myself with a few of Godot's available templates and he's had no issues with them.
2. Godot Engine having a list of GPUs with known issues related to GLES3 and forcing them to use GLES2 instead when detected. I heard the engine detects GPUs that only support OpenGL 3.1 instead of 3.3 and fall back to GLES2 that way, so this would be fantastic.

**Minimal reproduction project:**
Any GLES3 project (or older projects that default to GLES3) will cause this issue.

**Comment by akien-mga** [comment]
That GPU and drivers are too low-end to run Godot's GLES3 renderer properly. While the drivers claim OpenGL 3.3 support in terms of API, the hardware doesn't seem capable to handle a typical GL 3.3 renderer.

It *might* work after removing `default_env.tres`, as the default ProceduralSky used is known to be hard on lower-end graphics.
If not, this user should stick to GLES2 which should work fine on this GPU.

BTW I've checked and the drivers used are indeed the latest available from Nvidia, from 2016 (so this GPU is no longer maintained): https://www.nvidia.com/Download/driverResults.aspx/112594/en-us

There's sadly nothing we can do for very low-end GPUs like this (it's from 2008!), so closing.
