### ISSUE TITLE
Type not found. Creating placeholder: 'Texture2D'. while generating glue on 3.2

### ISSUE THREAD

**Issue by cbaal83** [godotengine/godot#36869]
**Godot version:**
3.2
**OS/device including version:**
Windows 10
**Issue description:**
Can't build 3.2 branch on windows 10. Build error:

ERROR: BindingsGenerator::_get_type_or_placeholder: Type not found. Creating placeholder: 'Texture2D'.
   At: modules\mono\editor\bindings_generator.cpp:2137

**Steps to reproduce:**
checkout 3.2 branch, follow this process:
https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html#example-windows

**Minimal reproduction project:**
none

**Comment by cbaal83** [comment]
most likely it's because of this commit:
https://github.com/godotengine/godot/commit/99d424042f00fc435177da93f9ffd2115501818d

Not 100% sure though :)

At least this:

https://github.com/godotengine/godot/commit/75164169c43f6dcef237ac9a7bf842598f5f20f2

Compiles perfectly fine :)

**Comment by akien-mga** [comment]
Fixed in 69c1805735df2a7a35e826e2f1bd40bac7dc1058.
Note that I force-pushed the `3.2` branch, so you might need to use `git pull --rebase` and not just `git pull` to sync your local branch.

**Comment by cbaal83** [comment]
That was superfast, thank you :)
