### ISSUE TITLE
ProgressBar max value property

### ISSUE THREAD

**Issue by Matshiro** [godotengine/godot#36867]
There isn't too much on the documentation, so I've checked in engine how to change max value in progressbar in code.
It showed that Max Value property is: max_value, so naturally I've set it in my script as $ProgressBar.set_max_value(value) - but it didn't work, because correct way to do it is:
$ProgressBar.set_max(value) - it's maybe not too much, but it can throw off few users.
(Same problem is with min value)

**Comment by dreamsComeTrue** [comment]
ProgressBar inherits from Range, and for that case everything is pretty documented:

![image](https://user-images.githubusercontent.com/1110337/76121850-f24ccd80-5ff4-11ea-9e91-94519832058d.png)

**Comment by Calinou** [comment]
Closing, as this is not an engine issue per se. Please use one of the other [community channels](https://godotengine.org/community) for support questions.
