### ISSUE TITLE
EventPlayer:Stream:Clear crash

### ISSUE THREAD

**Issue by kopias** [godotengine/godot#3687]
win7x64 godot 2.0 rc1

node EventPlayer:
when you click on "Clear" in Stream propertie (you need to load something first) godot crashes
![eventplayer-crash](https://cloud.githubusercontent.com/assets/3462746/13005057/b7036db8-d17f-11e5-994d-d5bdf5d01d2d.png)

**Comment by akien-mga** [comment]
Apparently the test project from #2553 can be used to reproduce.
