### ISSUE TITLE
Clang 10 failure with glslang

### ISSUE THREAD

**Issue by fire** [godotengine/godot#36888]
**Godot version:**
https://github.com/godotengine/godot/commit/8cb6d5daa4e41443d658265379b6079d8a087b41

**OS/device including version:**
Fedora 31

**Issue description:**

> TPoolAllocator is not copy assignable, so this setter could never have
been used. After a recent change (878a24ee2), new versions of Clang
reject this code. Make it compile by removing the method.

Upgrade to current glslang.

https://github.com/KhronosGroup/glslang/pull/2010

Clang failure with glslang

**Steps to reproduce:**

Use a newer clang compiler.

**Minimal reproduction project:**
Use godot master.

**Comment by akien-mga** [comment]
For the reference, I've been building with Clang 10.0 RC 2 on Linux without any issue for some time.

Still, I've prepared an upgrade to the Vulkan SDK and glslang that should include that PR.
