### ISSUE TITLE
GridMap with MeshLib always throws error

### ISSUE THREAD

**Issue by kubaxius** [godotengine/godot#36881]
**Godot version:**
Godot Engine v3.2.stable.official

**OS/device including version:**
Windows 10 Home Edition

**Issue description:**
Whenever you put Gridmap with MeshLib connected in your scene it always throws this error:

> get_item_preview: MeshLibrary item previews are only generated in an editor context, which means they aren't available in a running project.
>   <C++ Source>  scene/resources/mesh_library.cpp:206 @ get_item_preview()

Which in my case completely floods game console.

**Steps to reproduce:**
1. Create GridMap instance and connect some MeshLib to it
2. Start project

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/4301677/test.zip)

**Comment by Calinou** [comment]
This was fixed in #36288, closing.
