### ISSUE TITLE
No loop in audio streams on iOS

### ISSUE THREAD

**Issue by tidanneels** [godotengine/godot#36884]
**Godot version:** 3.2

**OS/device including version:** iOS 12 or more

**Issue description:** An audio stream in an AudioStreamPlayer with the "loop" option enabled does not loop on iOS

**Steps to reproduce:** Export and run on iOS a project with looped audiostream

**Comment by volzhs** [comment]
seems fixed on 3.2.1 #36742

**Comment by tidanneels** [comment]
Thank you, it works.
