### ISSUE TITLE
lerp_angle(0, PI, 0.5) == -1.570796 is this result intend?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#36886]
**Godot version:**
godot 3.2.1
**OS/device including version:**
macOS

**Issue description:**
the result of lerp_angle(0, PI, 0.5) is -1.570796,
it seems not as expected.
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
cc @Chaosus who added the function

https://github.com/godotengine/godot/blob/a7f49ac9a107820a62677ee3fb49d38982a25165/core/math/math_funcs.h#L218-L222

Looks like:
```
difference = PI
distance = 0-PI
return -PI*0.5
```
