### ISSUE TITLE
Dictionary of References export breaks compilation

### ISSUE THREAD

**Issue by CawawaC** [godotengine/godot#36899]
**Godot version:**
Godot 3.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
An export of a dictionary of References (or Resources) breaks compilation and the scene itself: it can't be opened again. This happens when both 1) and 2) are true: 1) the dictionary is modified in any way that makes it different from the initialization specified for it in the script 2) the dictionary holds more than 1 key-value pair.

**Steps to reproduce:**
- Create a node
- Add script to it
- Script content: `export var dictionary = {
	0: Reference,
	1: Reference
}`
- From the inspector, replace one of the values of the dictionary with any resource.
- Play scene (crash at compilation, no log)
- Also, save scene, close it and try to re-open: "Error while parsing 'scene_name.tscn'."

**Minimal reproduction project:**
[dictionary test.zip](https://github.com/godotengine/godot/files/4303022/dictionary.test.zip)

**Comment by ThakeeNathees** [comment]
Not any resource only for `GDNativeLibrary` which dosen't attached to any binary (script).
when first time running or reopen the scene it tries to create a native script instance but, 
no script => can't create an instance of that => BUG!!
