### ISSUE TITLE
AudioEffectPitchShift pitch_scale has incorrect documentation/tooltips

### ISSUE THREAD

**Issue by CatThingy** [godotengine/godot#36897]
**Godot version:** 3.2.stable.mono

**OS/device including version:** Windows 10

**Issue description:** The documentation for the pitch_scale property explicitly states that it shifts the pitch by that number of octaves. However, the pitch_scale property actually scales the pitch by that number.

**Steps to reproduce:** 

1. Add a PitchShift effect to an audio bus
2. Change the pitch_scale property to 0.5
3. Play audio to that audio bus
4. The audio will be shifted down by 1 octave, not 1/2 an octave.
**Minimal reproduction project:** [pitch_scale.zip](https://github.com/godotengine/godot/files/4302858/pitch_scale.zip)

**Comment by akien-mga** [comment]
Can be changed in https://github.com/godotengine/godot/blob/master/doc/classes/AudioEffectPitchShift.xml
