### ISSUE TITLE
Problem drag WindowDialog in stretch mode 

### ISSUE THREAD

**Issue by sanikoyes** [godotengine/godot#369]
I was use stretch mode in porject settings with stretch_mode = 2d and stretch_aspect = keep, then resize then window and drag WindowDialog, the dialog's pos seems is wrong

![image](https://cloud.githubusercontent.com/assets/6880378/2872971/2a70f954-d386-11e3-8b2d-242eb1487563.png)

Original screen size is 1136*960, my scene tree is:
![image](https://cloud.githubusercontent.com/assets/6880378/2872966/0721aa98-d386-11e3-8685-4d76f5d9cd7c.png)

"debug" node is WindowDialog, and anchor options are:
![image](https://cloud.githubusercontent.com/assets/6880378/2872968/19a117b2-d386-11e3-88e9-e538b143b65f.png)

**Comment by akien-mga** [comment]
Not sure I understand the issue properly, but is it still valid in the current master branch?

**Comment by akien-mga** [comment]
Still not clear what the issue was, so I'll archive it.
