### ISSUE TITLE
get_tree().paused , yield() still continues in for loop

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#36907]
**Godot version:**
3.2
**OS/device including version:**
Windows 10
**Issue description:**
Yield does not pause at get_tree().paused
**Steps to reproduce:**
You can paste this code under a NODE2D extends:

```
extends Node2D

var x = load("res://icon.png")
var t = Timer.new()
func _ready():
	t.one_shot = true
	self.add_child(t)
	t.start(1)

func emit():
	for each in 100:
		var sprite : Sprite = Sprite.new()
		sprite.texture = x
		sprite.position = Vector2(rand_range(0, 1000), rand_range(0, 1000))
		self.add_child(sprite)
		yield(get_tree().create_timer(0.2), "timeout")

func _process(delta):
	print(t.time_left)
	if t.is_stopped():
		emit()
		get_tree().paused = true
```
	

![issue](https://user-images.githubusercontent.com/37254287/76164769-401a2080-6130-11ea-967e-65448f5e2f28.gif)

**Minimal reproduction project:**
see code above

**Comment by KoBeWi** [comment]
Pause only stops `_process()` from being called and `yield` continues on an existing call. Not sure if `yield` even has necessary context to make stopping it possible.

**Comment by Faless** [comment]
Simply pass `false` as second argument to `create_timer` and the timer created will not process during pause.
`yield(get_tree().create_timer(0.2, false), "timeout")`

**Comment by shafnaz** [comment]
> @shafnaz Simply pass `false` as second argument to `create_timer` and the timer created will not process during pause.
> `yield(get_tree().create_timer(0.2, false), "timeout")`

@Faless That works very well indeed! Thank you!
I suppose I should close this issue. What do you guys think?

**Comment by KoBeWi** [comment]
Well, if it's only about the timer, then the issue can be closed.

**Comment by rcanpahali** [comment]
> @shafnaz Simply pass `false` as second argument to `create_timer` and the timer created will not process during pause. `yield(get_tree().create_timer(0.2, false), "timeout")`

It's a shame that I overlooked that second parameter 😄  thanks for reminding me of it. 👍
