### ISSUE TITLE
Curve2D : get_baked_points() : not starting at first point.

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#3690]
When points are added to a Curve2D, the function get_baked_points() won't start at the very first added point. Instead, the first point is set fixed after reaching bake interval the first time.

For example: adding points Vector2(0,0)...Vector2(13,0) with bake interval set to 10 will end in baked points: Vector2(10.000001,0) and Vector2(13,0).

The last point is always alternating, until a new interval is reached, what feels fine. But I think, that the starting point of the curve must not be alternating.

[curve2d_demo.zip](https://github.com/godotengine/godot/files/128000/curve2d_demo.zip)

**Comment by akien-mga** [comment]
Tested against the current master branch, it seems to work fine, at least as far as I understand the feature. The attached script outputs:
```
(0, 0)
---
(0, 0)
(1, 0)
---
(0, 0)
(2, 0)
---
(0, 0)
(3, 0)
---
(0, 0)
(4, 0)
---
(0, 0)
(5, 0)
---
(0, 0)
(6, 0)
---
(0, 0)
(7, 0)
---
(0, 0)
(8, 0)
---
(0, 0)
(9, 0)
---
(0, 0)
(10, 0)
---
(0, 0)
(10.000001, 0)
(11, 0)
---
(0, 0)
(10.000001, 0)
(12, 0)
---
(0, 0)
(10.000001, 0)
(13, 0)
[...]
```
