### ISSUE TITLE
GDScript Regression - can't use enum as const keys in dictionary.

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#36900]
**Godot version:**
Master: 78adce8

**OS/device including version:**
X11

**Issue description:**
Regression introduced with: https://github.com/godotengine/godot/pull/36441 not sure how... 

Before that commit I was able to use named enums as const dictionary key:
```gdscript
enum Types {
	Type1
}

const Test = {
	Types.Type1: 4321
}
```
Now this error appears:
![Screenshot from 2020-03-08 11-14-11](https://user-images.githubusercontent.com/8342599/76160856-ff210c80-612d-11ea-9e24-199ef6bdab17.png)

**Steps to reproduce:**
Just open any project and paste the above code inside.

**Comment by AndreaCatania** [comment]
Probably related to: #36672

**Comment by AndreaCatania** [comment]
This solves the problem: https://github.com/godotengine/godot/issues/36511

**Comment by TechnoPorg** [comment]
I can no longer reproduce this in 4.0 alpha.

**Comment by Calinou** [comment]
Closing per @TechnoPorg's comment.
