### ISSUE TITLE
Crash in Assimp, when importing project

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#36908]
**Godot version:**
4.0.dev.custom_build. d4b31c698

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
```
godot: thirdparty/assimp/code/PostProcessing/ArmaturePopulate.cpp:173: static void Assimp::ArmaturePopulate::BuildBoneStack(aiNode*, const aiNode*, const aiScene*, const std::vector<aiBone*>&, std::map<aiBone*, aiNode*>&, std::vector<aiNode*>&): Assertion `!node_stack.empty()' failed.
```
**Steps to reproduce:**
1. Import Project

**Minimal reproduction project:**
https://github.com/Revolutionary-Games/Thrive/tree/godot

**Comment by akien-mga** [comment]
CC @RevoluPowered 

Does it also happen before #36852?

**Comment by akien-mga** [comment]
I confirm that it's a regression from 78b2239. I'll revert it for now.

Here's a properly *minimal* (i.e. not 660 MiB ;)) reproduction project: 
[thrive-models.zip](https://github.com/godotengine/godot/files/4305799/thrive-models.zip)
