### ISSUE TITLE
InputEventMouseMotion relative doesn't end with [0, 0]

### ISSUE THREAD

**Issue by gitcatrat** [godotengine/godot#36916]
**Godot version:**
3.2.stable.mono

**OS/device including version:**
macOS Catalina 10.15.3/MacBook Pro

**Issue description:**
I was expecting that `InputEventMouseMotion` `relative` (and `speed`) last event is **always** `[0, 0]` after cursor/pointing device stops moving but that's not the case.

Here's one use case among many that's not properly working due to this issue: camera uses motion object (or struct in case of C#) calculating and applying next position (angle, etc) in `_process`. If motion values are not set to `0f`, camera moves indefinitely. Motion is set using mouse motion event `relative` and if last `relative` value is not `[0, 0]` (after cursor stops), we have an ugly bug.

**Steps to reproduce:**
* Add `unhandled_input` method/function
* Print motion event `relative` and `speed` properties
* Play the scene, move the cursor and witness it happening

**Comment by Zylann** [comment]
> I was expecting that InputEventMouseMotion relative (and speed) last event is always [0, 0] after cursor/pointing device stops moving but that's not the case.

How could that be the case? It would be `[0, 0]`, only if there was no movement. If there is no movement, there can't be an `InputEventMouseMotion`, isn't it?

**Comment by gitcatrat** [comment]
I don't know, `[0, 0]` is the last event most of the time. I probably based my expectation on that.

**Comment by Zylann** [comment]
> camera uses motion object (or struct in case of C#) calculating and applying next position (angle, etc) in _process. If motion values are not set to 0f, camera moves indefinitely.

Usually camera movement using `InputEventMouseMotion` resets its speed, or damp it after applying it.

**Comment by gitcatrat** [comment]
Can this be closed then? Not a bug? There are waaaay too many issues already.

**Comment by Calinou** [comment]
This should probably still be documented, so I'd leave it open until this is mentioned somewhere in the class reference.

**Comment by theoway** [comment]
The mouse position relative to the previous position (position at the last frame). This is what is written in the documentation. It should be 'position at the last frame when last mouse motion input was received'

**Comment by Calinou** [comment]
@theoway That makes sense, but that description would lose the "relative" part compared to the one we currently have. How about this?

> The mouse position relative to the previous position (position at the last frame).
> [b]Note:[/b] Since [InputEventMouseMotion] is emitted only when the mouse moves, the last event won't have a relative motion of `Vector2(0, 0)` when the user stops moving the mouse.
