### ISSUE TITLE
Shader parameter taking a 256x1 pixel image raises an error.

### ISSUE THREAD

**Issue by hagsteel** [godotengine/godot#36940]
**Godot version:**
3.2 stable

**OS/device including version:**
Linux 5.5.8

**Issue description:**
adding a `uniform sampler2D` shader parameter and assigning a png which is 256x1 pixels causes the error `ERROR: resize: Image height must be greater than 0. At: core/image.cpp:891.`.

**Steps to reproduce:**
1.  Create a new project
2.  Add a Sprite
3.  Add a shader
4. Add the following shader code:
```
shader_type canvas_item;
uniform sampler2D foo : hint_albedo;
```
5.  Assign a 256x1 pixel image to the "foo" shader parameter.
6.  Save, restart editor and select the sprite and the error message should be visible in the terminal.

Note: changing the image to a 256x2 pixel image doesn't cause the error anymore

**Comment by Calinou** [comment]
What are the import settings of the PNG file in question? You can view them by selecting the image in the FileSystem dock then going to the Import dock. There are known issue when using VRAM compression modes for very small images (< 16 pixels in either dimension).

**Comment by hagsteel** [comment]
```
[remap]

importer="texture"
type="StreamTexture"
path="res://.import/base-palette.png-610a3708b32f0be1839fb098e30bdc66.stex"
metadata={
"vram_texture": false
}

[deps]

source_file="res://assets/player/base-palette.png"
dest_files=[ "res://.import/base-palette.png-610a3708b32f0be1839fb098e30bdc66.stex" ]

[params]

compress/mode=0
compress/lossy_quality=0.7
compress/hdr_mode=0
compress/bptc_ldr=0
compress/normal_map=0
flags/repeat=0
flags/filter=false
flags/mipmaps=false
flags/anisotropic=false
flags/srgb=2
process/fix_alpha_border=true
process/premult_alpha=false
process/HDR_as_SRGB=false
process/invert_color=false
stream=false
size_limit=0
detect_3d=false
svg/scale=1.0
```
