### ISSUE TITLE
Tweens jitter in android 6.0.1

### ISSUE THREAD

**Issue by cgeadas** [godotengine/godot#36952]
**Godot version:**
3.2
**OS/device including version:**
Asus Zenfone 2
Android 6.0.1
**Issue description:**
Tweens work with jitter. Noticed on scaling and rotation.

**Steps to reproduce:**
Any scaling or rotating tween will jitter.

For example:

```
func _ready():
	
	
	var texto = $Label
	var efeito = $Tween
	
	for x in range (3, 0, -1): 
		texto.text = str(x)
		efeito.interpolate_property(texto, "rect_scale", Vector2(1, 1), Vector2(0, 0), 1,
			Tween.TRANS_LINEAR, Tween.EASE_OUT)
		efeito.start()
			
		yield(efeito, "tween_completed")
	
	
```
Will produce noticeable jitter.

This can also be observed in the Tween Demo project.
(https://godotengine.org/asset-library/asset/146)

**Minimal reproduction project:**
[Teste8.zip](https://github.com/godotengine/godot/files/4309568/Teste8.zip)

**Comment by Calinou** [comment]
Can you reproduce this on other devices or desktop PCs?

**Comment by cgeadas** [comment]
I can test on a Asus Zenfone 2 with Android 6, a Asus Zenfone 5 lite with Android 9 and a Apple Macbook Pro with macOS Catalina. I only see this behaviour with Android 6, the other work ok.

**Comment by cgeadas** [comment]
If I change to GLES2 instead of GLES3, the problem disappears.
(But the equipment supports GLES3)

**Comment by Calinou** [comment]
> If I change to GLES2 instead of GLES3, the problem disappears.
(But the equipment supports GLES3)

Unfortunately, many devices *claim* to support GLES3 but do so very poorly in practice. Therefore, we recommend you use the GLES2 renderer when targeting mobile/Web platforms.

**Comment by cgeadas** [comment]
> > If I change to GLES2 instead of GLES3, the problem disappears.
> > (But the equipment supports GLES3)
> 
> Unfortunately, many devices _claim_ to support GLES3 but do so very poorly in practice. Therefore, we recommend you use the GLES2 renderer when targeting mobile/Web platforms. The GLES3 renderer will be removed in Godot 4.0, as it will be replaced by a Vulkan renderer (GLES2 will remain).

This is very useful information. It should be well displayed in the official documentation, so that new godot users can choose right way the most adequate GLES level they require.
I've changed my project to GLES2, but otherwise I wouldn't know that it is the best for the mobile platform. Thank you.

**Comment by Calinou** [comment]
@cgeadas It's already displayed in the project creation dialog:

![image](https://user-images.githubusercontent.com/180032/76361376-31de2700-631f-11ea-9e9a-1fe527029e16.png)

I'm not sure if this could be mentioned anywhere else (where it makes sense).

**Comment by cgeadas** [comment]
"Lower visual quality" kills the rest of the phrase :-)
Some short guide, probably in Best Pratices (https://docs.godotengine.org/en/stable/getting_started/workflow/best_practices/index.html), describing some basic considerations, maybe... "If you're planning to develop mobile games have in mind... etc etc". Just an idea.
