### ISSUE TITLE
will a master function called locally  if local peer is the master of that node?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#36955]
**Godot version:**
3.2.1
**OS/device including version:**
macOS

**Issue description:**
according to the document
RPC_MODE_MASTER = 2
Used with Node.rpc_config() or Node.rset_config() to set a method to be called or a property to be changed only on the network master for this node. Analogous to the master keyword. Only accepts calls or property changes from the node's network puppets, see Node.set_network_master().

a function tagged as master, for example:
master func test():
    print("test")

can only be called from the node's network puppets.
However, when call rcp("test") on the network master of that node, this function will called on that peer locally as mastersync. 
but in this way it is not called from the the node's network puppets.

Is this behavior  intended or there is a mistake in the documents?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
Sorry, this is not the place to ask questions about how to use the engine. Please use the other community channels for this purpose. If you feel like the documentation is lacking information about this topic, please open an issue in the documentation repository.

**Comment by alexzheng** [comment]
This is not a question if you have really read the content.

**Comment by groud** [comment]
I did. This is your question : 

> Is this behavior intended or there is a mistake in the documents?

Please ask those kind of questions on the other community channels first. And once you have your answer, you can open an issue explaining where the problem is (if it is on the engine side or on the documentation one). For such questions, you can ask to developers on the #godotengine-devel IRC channel, Faless is probably the person that can answer you.

**Comment by alexzheng** [comment]
OK, thanks.
I have just checked the source code, and confirmed that  rpc will make local call even without the sync  keyword is intended. So undoubtedly, the document is misleading.

**Comment by groud** [comment]
>  So undoubtedly, the document is misleading.

Ok. Then could you open an issue on the documentation repository ?

**Comment by alexzheng** [comment]
Sure!
