### ISSUE TITLE
Nine-patch image scale incorrect on TextureProgress mode Clockwise

### ISSUE THREAD

**Issue by Developpix** [godotengine/godot#36969]
**Godot version:** Godot 3.2

**OS/device including version:** Windows 10

**Issue description:**
When use a TextureProgress in clockwise mode if the nine patch strech is enable and we have value equal to max value (max value not equal to 1) the scale of the image displayed don't use nine patch.

**Steps to reproduce:**
* Create a TextureProgress
* Set a min size and size for the TextureProgress
* Set a image for the progress texture with a size bigger than the TextureProgress
* Use Nine patch stretch
* Set Fill Mode to Clockwise
* Set a Max Value > 100
* Set Value equal to Max Value
* The TextureProgress use the scale of the image file and don't use nine patch stretch.

**Minimal reproduction project:**
Juste create a project with a TextureProgress.

**Comment by Calinou** [comment]
Do nine-patch textures even make sense with clockwise/counterclockwise progress bars? I don't see how it could work.
