### ISSUE TITLE
fix temporary bug export gles2 and fix bug crashing gles3 render model 3d pvrtc bug

### ISSUE THREAD

**Issue by matiashak** [godotengine/godot#36967]
**Godot version:**3.0 3.1. 3 3.2
target nvidia gt210
**OS/device including version:** android 5.0

I have many errors with the 3D renderings with Android pvrtc the models are stretched and move from here for there I have also tested in bluestack and it gives me the same error
**Minimal reproduction project:**
Only when exporting to Android does this happen
test dae, gltf format 3D
GLES2

I have been inserting several 3D modeling to test if that is the problem but the problem persists, I am still waiting for good results since last year. Hopefully it will be solved soon since I have been pausing my prototypes for these reasons, we would be grateful to you if they focused more on the solutions to problems for mobile exports

GLES3 

Another error that I have been dragging is that since version 3.1.2 when activating gles3 from the creation of the project when opening the project the system crashes and the screen goes black and the engine closes I think it is not compatible with my nvidia or something So
![bug](https://user-images.githubusercontent.com/58227174/76344515-026cf180-6302-11ea-9d4a-a8c1314efe5c.png)

[2020-03-10 15-19-37.zip](https://github.com/godotengine/godot/files/4314090/2020-03-10.15-19-37.zip) 
video zip
Another error that I also know is that with the pvrtc you have to deactivate the illuminations so that the nose works if it has something to do with it, but I think that the error will be there
![godot](https://user-images.githubusercontent.com/58227174/76450575-4f1dfe80-63ce-11ea-9a37-e2331f3004b0.png)
solution temporary bug crashing in GLES3 nvidia error 7 
![fix](https://user-images.githubusercontent.com/58227174/76710423-c40f7200-6707-11ea-832b-a60d0f8511b1.png)
FIX bug gles2 rendering material error solution temporary PVRTC
![fix material ](https://user-images.githubusercontent.com/58227174/76710857-2027c580-670b-11ea-8d91-20947534e826.png)

**Comment by Calinou** [comment]
@matiashak Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by matiashak** [comment]
wait

**Comment by matiashak** [comment]
help me :c

**Comment by Calinou** [comment]
@matiashak Sorry, but we can't help you if you don't upload a minimal reproduction project. We'll have to close this issue in 7 days otherwise.

**Comment by zacharytyhacz** [comment]
Hm, I have a hunch that this issue is related to the 3D model asset itself, not the engine. 
Couple questions:
- What format is this 3D model in?
- Can you open the 3D model in a 3D editor ( 3ds Max, Maya, Blender, etc ) and see if it exists there too?
- Does the 3D model have animations embedded?

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
