### ISSUE TITLE
Start two Godot instances Editor-Debug -> output empty

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3696]
When I start godot twice to work on client/server(two projects) only one of both outputs is working.
The terminal is showing the output but not the editor.
Can anyone confirm this?

Does it have something to do with the default port(already in use..)? I can't see any errors.

OS: Ubuntu 64-bit, XUbuntu 

EDIT:
Still an issue in 3.0
** Error listening on port 6007 **

**Comment by akien-mga** [comment]
Closing as superseded by #20020 which describes the issue too and a potential feature that would fix it.
