### ISSUE TITLE
Tileset: Atlas Tiles do not show modulation

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#36964]
**Godot version:** 3.2.1 stable

**OS/device including version:** Win64

**Issue description:**
Atlas Tiles do not show their modulation in the Tilemap preview. This can be especially confusing when there are also tiles of the same texture without modulation:
![Tileset_atlas_nomodulate_preview](https://user-images.githubusercontent.com/47016402/76334903-0b56c680-62f4-11ea-8dd5-27187d740873.png)
spritesheet.png is the AtlasTile. Those Tiles 1-8 underneath in the lower right corner should be equally blue.

**Steps to reproduce:**
Create Atlas Tiles Tileset, set modulation, select Tilemap, select AtlasTile

**Comment by kleonc** [comment]
Fixed by #48403.

**Comment by Calinou** [comment]
Closing per @kleonc's comment.
