### ISSUE TITLE
Not exact or whole scaling

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#36974]
**I have updated the project for the minimum possible code**

**Godot version:**
3.2.1 mono

**OS/device including version:**
win10 64

**Issue description:**
The scaling is different from 3.2. rc2, this includes las version 3.2.1.
I am not sure how I should describe this.
The position of the object during scaling seems to use integers and that is why these movements occur on the X and Y axes, this does not happen in 3.2 rc1.

In this gif the scaling is nice and apparently correct with 3.2 rc1
![3 2 rc1](https://user-images.githubusercontent.com/19652075/76364103-aff0fc80-6324-11ea-837f-8c460f3b9528.gif)

In this gif the label object has more abrupt movements, it seems that its position is changed and it is located again with integer values, this happens from 3.2 rc2
![3 2rc2](https://user-images.githubusercontent.com/19652075/76364124-bbdcbe80-6324-11ea-9f4f-a5550109e02e.gif)

**Steps to reproduce:**
Open the Node2D scene and run the scene.

**Minimal reproduction project:**
[testGenerales.zip](https://github.com/godotengine/godot/files/4319613/testGenerales.zip)

**Comment by akien-mga** [comment]
I tested 3.2 beta6, RC 1 and RC 2 but it behaves the same (abrupt, like second GIF) in both versions.

**Comment by Calinou** [comment]
Note that you probably want to enable **Filter** on the DynamicFont when changing its scale at runtime.

**Comment by dankan1890** [comment]
I tried the versions: 3.1.2 stable - 3.2 alpha 1 and 3.2.1 stable, but all of them behave as in the 2nd GIF.

**Comment by Torguen** [comment]
I have tested on my laptop and on my desktop computer.

The difference occurs as I previously put in the GIF.
In 3.2.1 rc1 everything happens correctly (first GIF)
In 3.2.1 stable abrupt scaling happens (second GIF)

**Comment by dankan1890** [comment]
I think it's related to https://github.com/godotengine/godot/pull/32959

**Comment by Torguen** [comment]
> I think it's related to #32959

I think the same, it's the same problem.

**Comment by Torguen** [comment]
It seems that this problem (in my case) is due to the activation of the "Snap Control to Pixels" option.

When you deactivate it the problem disappears, I do not know what is the use of this option, why would someone activate it?
I would recommend that it be disabled by default, don't you think?
![1](https://user-images.githubusercontent.com/19652075/77848284-fa4af800-71c3-11ea-9ab9-653c5570f3e2.png)

**Comment by Calinou** [comment]
@Torguen "Snap Controls To Pixels" is basically "Use Pixel Snap", but for Control-derived nodes instead of Node2D-derived nodes. You generally want to leave it on as disabling it will make controls look less crisp.

**Comment by Torguen** [comment]
> @Torguen "Snap Controls To Pixels" is basically "Use Pixel Snap", but for Control-derived nodes instead of Node2D-derived nodes. You generally want to leave it on as disabling it will make controls look less crisp.

So there is a conflict here.
Activating the option reduces the quality of the scaling as we have already seen.

**Comment by pwnorbitals** [comment]
Well, it’s more a bug than a conflict, the "snap controls to pixels" option’s behaviour is suspicious here

**Comment by asheraryam** [comment]
This seems to be the same issue that's fixed in https://github.com/godotengine/godot/pull/46409

**Comment by akien-mga** [comment]
Fixed in `master` a while ago, and fixed in `3.2` by #46409.
