### ISSUE TITLE
Atlas reimport procedure does not create atlas file

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#36976]
**Godot version:**
3.2.1.stable

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
Reproducing the procedure described in the image of @reduz' news post here : https://godotengine.org/article/atlas-support-returns-godot-3-2

Does not seem to create the atlas file.

**Steps to reproduce:**
- Create a project
- Add image files into a folder of the project (eg. Kenney tileset)
- Select images in Filesystem dock
- In Import tab, choose TextureAtlas
- Set a filename and a mode
- Click on Reimport button
- Validate in popup
<editor restarts>
- Confirm that the atlas filename that was supposed to be created is not there

**Minimal reproduction project:**
N/A

**Comment by arkology** [comment]
Related to https://github.com/godotengine/godot/issues/32869

**Comment by dankan1890** [comment]
With 3.2.1 for Windows, the file is created physically in the target path, but is not displayed on the internal file system.
This, I think, is due to a failed refresh.

**Comment by DrMoriarty** [comment]
Tested on macosx:

When I create new atlas from multiple files it doesn't work.

When I create new atlas from a single image - it works!

When I add one more image to exists atlas - in works again!

When I add several images to exists atlas - in doesn't work.

Also in the last case it shows me very interesting error message:
![Снимок экрана 2020-03-13 в 23 24 28](https://user-images.githubusercontent.com/1177068/76656978-d8c1fd80-6581-11ea-9343-6ff4dd828a37.png)

Did we already have threaded resource loading in 3.2 branch? It looks like many resources loading blocking the atlas file.

**Comment by AiurTemplar** [comment]
> With 3.2.1 for Windows, the file is created physically in the target path, but is not displayed on the internal file system.
> This, I think, is due to a failed refresh.

In my occasion there is no file created at all, check here: #37429

**Comment by dankan1890** [comment]
Regression introduced by #36630 @YeldhamDev

**Comment by firecloud888** [comment]
Seems the bug not fixed, please reopen it
It must be a bug. I try the godot 3.2 beta 6 and it solve my problem
https://godotengine.org/article/dev-snapshot-godot-3-2-beta-6

**Comment by Calinou** [comment]
@firecloud888 See https://github.com/godotengine/godot/pull/37610#issuecomment-626176466.

**Comment by asheraryam** [comment]
I can confirm this is fixed on 3.2.2 beta 3 
![image](https://user-images.githubusercontent.com/43449832/83537245-f9548080-a4fc-11ea-8988-e81973b66fbd.png)
