### ISSUE TITLE
Add deep copy functions to Dictionary and Array

### ISSUE THREAD

**Issue by kirilledelman** [godotengine/godot#3697]
Hi,
I found that there's no built-in way to deep-clone Dictionary or an Array.
I use these data structures for in-game templates that get data appended by instances, and I needed to clone them, completely and recursively.

The best way to do so right now, without writing an even clumsier / less efficient recursive function is to do it like so:

`dictionaryDeepCopy = str2var( var2str( originalDictionary ) )`

Please add `.copy()` method to both Dictionary and Array classes to make a deep / recursive copy of the object ( all elements / values should be deep-copied recursively as well )

**Comment by nopeson** [comment]
Oh yes, missed those functions some times too.
I think a good way according to the former style would be
`var new_array = Array(old_array)`
it's the (one) way, I would handle it in Python too.
Otherwise a `.copy()` method sounds good too.

**Comment by trollworkout** [comment]
+1

**Comment by WalasPrime** [comment]
+1

**Comment by 1Snakel** [comment]
+1

**Comment by reduz** [comment]
I think I added to Dictionary

**Comment by EIREXE** [comment]
Hey  @reduz will this make it into 2.1 or is it too late?

**Comment by reduz** [comment]
too late, but you can always compile from github I guess

**Comment by dodgyville** [comment]
I think dict now has a duplicate() method which appears to copy the dict.

**Comment by akien-mga** [comment]
Indeed, this was implemented by #17382.
