### ISSUE TITLE
Scene with many nodes and 512px script icon causes bad lag spikes

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#36981]
**Godot version:**
`cdbf0332902d34cfb3be7899fb738b5447bbb755`

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
Multiple instances of a node that has a high resolution script icon causes bad lag spikes.
![image](https://user-images.githubusercontent.com/14253836/76379928-710c7800-631f-11ea-81ff-cf2539c6904c.png)

https://www.youtube.com/watch?v=tnT5knlqbqI

**Steps to reproduce:**
Move any nodes in `Scene.tscn` and it will have a 1-2 second lag spike.

**Minimal reproduction project:**
[Lag.zip](https://github.com/godotengine/godot/files/4315906/Lag.zip)

**Comment by Calinou** [comment]
Note that you generally don't need node icons to be larger than 32×32 (if you want to support hiDPI displays) or 16×16 (if you don't want to support hiDPI displays).

**Comment by nathanwfranke** [comment]
@Calinou that's true, so this isn't the highest priority. Although the bug seems to be more prominent when there are more instances which could cause noticeable delay even with 64px (+ many instances)
