### ISSUE TITLE
AStar2D cannot override _estimate_cost or _compute_cost in GDScript

### ISSUE THREAD

**Issue by Adinimys** [godotengine/godot#36990]
Godot version : 3.2.1, also present in 4.0

Issue description :
AStar provides a way to override its cost calculation from GDScript. Since AStar2D is a wrapper around it with an `AStar astar` member there is no way to override the `_evaluate_cost()` and `_compute_cost()` inside of it

Steps to reproduce :

`class CustomAStar2D :
	extends AStar2D
	
	func _estimate_cost(u, v):
		print("this isn't called")
		var dist = (get_point_position(u) - get_point_position(v)).abs()
		return dist.x + dist.y

	func _compute_cost(u, v):
                print("not called either")
		return _estimate_cost(u, v)`

I'm not sure if the best would be to rewrite AStar2D to use its own _solve() which might also slightly improve performance by removing useless calculations. Or completly rewrite AStar2D to not be a wrapper ? Or maybe there is a way to reach `astar._estimate_cost()` from its wrapper class ?

At least if it's intended that advance uses needing to overwrite those methods should use AStar regardless of 2D/3D, it should be documented here : https://docs.godotengine.org/en/3.2/classes/class_astar2d.html

**Comment by bojidar-bg** [comment]
CC @Chaosus ( https://github.com/godotengine/godot/pull/27237#issuecomment-496490667 ).

**Comment by Adinimys** [comment]
Wouldn't the best approach be using templates ? With AStar<Vector3> and AStar<Vector2> exposed as AStar and AStar2D ?
It would also mean that it would be easier to then expand to other datat types to support non-spatial pathfinding (such as in GOAP)

**Comment by Chaosus** [comment]
You cannot use templates with GDScript so this is not a correct way to solve a problem. I will try to use function pointer instead...

**Comment by Adinimys** [comment]
Thanks ! @Chaosus
