### ISSUE TITLE
input_event signal never fires

### ISSUE THREAD

**Issue by songangel72** [godotengine/godot#36996]
Godot version: 3.2.1

OS/device including version: Windows 10 Version	10.0.18363 Build 18363 / Desktop PC

Issue description:  Connecting an input_event signal will not call the function even though input_ray_pickable is set to true.  

I tried this with a static body as well as an area node and neither would work.  My mouse was captured so I also tried commenting that out and I cannot get a click event to fire.

Steps to reproduce:
Add a spatial node
Add an area node as a child of spatial
Add a collision shape as a child of area
Set the collision shape to new BoxShape
Connect the areas input_event signal to any script and debug_print a message from that function
Run game and try to click on the object
No debug message is ever printed

Minimal reproduction project:  None

**Comment by Calinou** [comment]
@songangel72 Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by songangel72** [comment]
I tried but it's more than 10 MB.  I was unable to reproduce it myself by creating a new project.  The only difference between the project with the issue is that the mouse is captured which apparently causing the event to never be triggered.

Just looking for a simple way to click on objects in a game with a FPS camera when the mouse is captured but I guess it's not possible.
