### ISSUE TITLE
Warning on project initialization: Property not found: mono/editor/editor_path_optional

### ISSUE THREAD

**Issue by MirrasHue** [godotengine/godot#36995]
**Godot version:** 3.2.1-stable_mono_win64

**OS/device including version:** Win10 1909

**Issue description:** Godot is trying to find a property, but it is failing to do so

**Steps to reproduce:** Just edit a project
```
editor/editor_settings.cpp:151 - EditorSettings::_get - Property not found: mono/editor/editor_path_optional
```

**Minimal reproduction project:** Sorry, I didn't get this field's gist

**Comment by Ev1lbl0w** [comment]
`editor_path_optional` looks like an optional path to an editor for you to edit C# code. This doesn't look like a problem.

**Comment by aaronfranke** [comment]
Please provide a minimal reproduction project. I edit projects all the time and don't have this issue.

**Comment by MirrasHue** [comment]
Before installing 3.2.1, I cleaned all godot files, even those from appdata, and now it's showing this warning. I'll remove them again and download 3.2 to see if the warning persist, then I'll come back to update you.

**Comment by MirrasHue** [comment]
Oh, nothing appeared in 3.2. Regarding what our friend Ricardo said, seems not to be the case, in 3.2.1 I had already chosen vscode as the default editor for c#, and now back in 3.2 this wasn't necessary.

**Comment by MirrasHue** [comment]
I tested it out on my college's pc, unfortunately the same warning was showing up.

**Comment by MirrasHue** [comment]
Should I close this?

**Comment by aaronfranke** [comment]
Feel free to continue the discussion, specifically if you find a reliable way to reproduce it. You should also test on Linux to see if it's an OS-specific issue.

**Comment by MirrasHue** [comment]
Sorry, I thought that it was clear that there's simply nothing to reproduce it, I just open a project and the warning is there. Have a good day.

**Comment by MirrasHue** [comment]
But it's not harmful to the workflow, just odd to occur every time.

**Comment by akien-mga** [comment]
You can remove your `%APPDATA%/Godot/editor_settongs-3.tres` to fix it (or just remove the line setting this invalid option).

**Comment by akien-mga** [comment]
Actually it's probably related to f0b63b47aae33a497c6444f32c6e90cf6670f6bb, CC @van800.

**Comment by van800** [comment]
Hm. I can't reproduce it, even if `mono/editor/editor_path_optional` is not initialized in settings.
@neikeq As far as I understand, managed stacktraces are not printed to GD output together with unmanaged exception. Is it printed elsewhere maybe?

**Comment by van800** [comment]
@MirrasHue Do you use Rider?

**Comment by MirrasHue** [comment]
@van800 No, I use vscode

@akien-mga Is this a regression? In 3.2 this doesn't happen.
And I removed that setting from %appdata%, nothing changed.

I wonder if everybody in this issue is using the mono version.

**Comment by van800** [comment]
Reproduced. I hope to have a fix shortly.

**Comment by akien-mga** [comment]
@MirrasHue It was a regression from f0b63b4, but it's harmless. It's just that it could now happen that the MSBuild detection code queries this Rider-specific parameter, which may not be defined if you didn't configure Godot to work with Rider. #37210 fixes it.

**Comment by MirrasHue** [comment]
@van800 Oh, now I see, when we select Rider a new option appear, but for vscode it doesn't.

Unlike 3.2,  3.2.1 can't figure out the path automatically, so that's why this 'mono/editor/editor_path_optional' is not in my 'editor_settings-3.tres'.

**Comment by MirrasHue** [comment]
After switching back the External Editor to vscode, the Editor Path Optional property kept there, so I put the absolute path to Code.exe and seems to work just fine, no more warnings.
