### ISSUE TITLE
Tilemap editor keyboard shortcut ctrl+b doesn't work has expected

### ISSUE THREAD

**Issue by Levrault** [godotengine/godot#37004]
**Godot version:**
3.2.1

**OS/device including version:**
Linux mint 19.2

**Issue description:**
Since Godot version 3.2, tilemap shortcut like ctrl+b for select doesn't the same as 3.1. We now need to press ctrl+b and keep the Ctrl key pressed to make the selection. It could lead to some strange behavior if we click on ctrl+b one time and try to select.

**Steps to reproduce:**
- Create a tilemap
- Add it to a scene
- Add some tiles
- Press ctrl+b
- Doesn't keep select active
![Peek 2020-03-12 10-05](https://user-images.githubusercontent.com/1162446/76505530-ebd1b200-6449-11ea-87b0-09d9df068de2.gif)

- If pressing ctrl+b one time and keep ctrl pressed
![Peek 2020-03-12 10-22](https://user-images.githubusercontent.com/1162446/76506492-88e11a80-644b-11ea-80b5-04751cff8f40.gif)

**Expected:**
Pressing ctrl+b should active the select behavior.

**Minimal reproduction project:**
[tilemap-conflict.zip](https://github.com/godotengine/godot/files/4323326/tilemap-conflict.zip)

**Comment by akien-mga** [comment]
The shortcuts were changed in #36054 to fix conflicts.

**Comment by Levrault** [comment]
Should the wording be updating in this case?

![image](https://user-images.githubusercontent.com/1162446/76506981-4ff57580-644c-11ea-936e-f171a07f84dc.png)

It could be confusing since it took me some time before realizing that keeping ctrl will do the job.

**Comment by akien-mga** [comment]
Indeed, CC @Calinou.

**Comment by dreamsComeTrue** [comment]
That is fixed already in fact :)

![image](https://user-images.githubusercontent.com/1110337/76526463-d79fac00-646d-11ea-8b6d-0558adb65ef4.png)

**Comment by akien-mga** [comment]
Well, I checked 3.2.1-stable and the tooltips are correct there too, I guess @Levrault was back on 3.2-stable when doing the previous screenshot.

**Comment by Levrault** [comment]
You're right, the issue was linked to itch that notifies to update but didn't work. Wording behavior was indeed already fixed. Thanks a lot
