### ISSUE TITLE
Tweening for progress bars

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3700]
Right now Progress Bar and Texture Progress Bar don't have tweening functionality and steps on progress look kinda bad (especially when you have a range of, let's say, 1 to 20). Smooth progression in bars would be a very nice feature to have out of the box since they can be used not only to show loading progress, but to show HP and a lot of other UI stuff in game.

**Comment by Calinou** [comment]
Can't the `Tween` node be used for this?

**Comment by ArcFutahito** [comment]
Hmmm... Probably? I'll look into it.

**Comment by volzhs** [comment]
I used ``Tween`` for animating progress bar too.
I guess everyone wants differently how animation looks like.

**Comment by ArcFutahito** [comment]
Hmm, Looked into `Tween`. Yeah, it can be used. Still, having a tweening mode selectable inside inspector (for buttons highlighting, progress bars and all the UI stuff) would make workflow a lot faster, since most of the people would like to have smooth transitions on those elements anyway.

**Comment by akien-mga** [comment]
Closing as this is already possible.
