### ISSUE TITLE
Remote inspector does not display texture and mesh previews in 3.2.1 (did in 3.2)

### ISSUE THREAD

**Issue by x2f** [godotengine/godot#37000]
**Godot version:**
3.2.1-stable
**OS/device including version:**
Windows 10
**Issue description:**
Inspector used to display a preview of a texture in a remote object in 3.2.
The same operation in 3.2.1 shows "Object ID: <number>".
Note: I deleted .import directory and restarted Godot to re-import all assets. This does not solve the issue.
Note2: something similar happened in the past in #20476 (but now it only happens in remote inspect. Normal inspector shows textures correctly)
**Steps to reproduce:**
Run inspector on remote object containing a texture.

With 3.2.1: 
![texture-preview-3 2 1-stable](https://user-images.githubusercontent.com/10355421/76482552-d8dbc500-63ea-11ea-8c65-eca5a369f1a0.png)

With 3.2:
![texture-preview-3 2-stable](https://user-images.githubusercontent.com/10355421/76482564-e09b6980-63ea-11ea-8d07-1135cddae05b.png)

**Comment by akien-mga** [comment]
What kind of texture is it?

**Comment by x2f** [comment]
This is a StreamTexture

**Comment by akien-mga** [comment]
I can confirm the issue with this test project: 
[New Game Project.zip](https://github.com/godotengine/godot/files/4328695/New.Game.Project.zip)

It's reproducible in 3.2.1-stable and 3.2.1-rc2, but not in 3.2-stable and 3.2.1-rc1.

**Comment by akien-mga** [comment]
That's a regression from e92669654a, CC @Faless.
The bug is however not reproducible in the `master` branch (951ecc4f79a760160bdc7adc3b0b40e9e4c6b82d), so I guess my cherry-pick was a bit careless.
