### ISSUE TITLE
Y Axis Gizmo randomly disappears at some angles

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#37016]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
951ecc4f7

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
Y Axis (Maybe others) randomly disappear

[Godot Y Axis Gizmo randomly disappears [TqutiJX70xE].webm](https://user-images.githubusercontent.com/14253836/229338122-5d4d96c2-0eef-4ac9-a469-942e438082cf.webm)

**Steps to reproduce:**

Use mouse wheel to orbit the viewport

**Minimal reproduction project:**
I just made an empty project and saw this

**Comment by Calinou** [comment]
Can you reproduce this in 3.2 stable as well?

**Comment by nathanwfranke** [comment]
No but it seems to shift around 1 pixel instead so shouldn't matter
![0441d861](https://user-images.githubusercontent.com/14253836/76671901-09e10480-6567-11ea-84cc-7af048d1fe67.gif)

**Comment by Zylann** [comment]
I've seen this happen in 2D with lines drawn with `draw_line()`, with a particular drawing transform. I don't have a repro right now though

**Comment by aaronfranke** [comment]
This might not be a good solution, but maybe we should just force the 3D viewport to be an odd number of pixels wide? This could be done in the Node3D EditorPlugin so that this restriction doesn't exist for the other main screen plugins.

**Comment by nathanwfranke** [comment]
@aaronfranke while still not the best solution we should either fix the draw line call for the axis or round that to one pixel

**Comment by Calinou** [comment]
We could draw two lines to ensure one of them is always visible, but this may make it too thick.

**Comment by nathanwfranke** [comment]
Someone should do a bisect from 3.2 since there it seems to shift instead (unless this is some problem with vulkan)

**Comment by Thane5** [comment]
I always used to have this bug, but in v4.0.dev.calinou [7188cb601] it looks fine now.

**Comment by Kemeros** [comment]
Did more tests.

An empty project doesn't do the problem on version v4.0.dev.custom_build [92a2380d9]

However. if i load a project, the bug is there.

So i started testing a bit. It's quite easy to reproduce.

Step 1: Make an empty project.
Step 2: Switch to 3D editor.
Step 3: Notice that the bug is NOT present.
Step 4: Add a node. Any base type node will do but i suggest 3D Scene so the editor doesn't switch to 2D.
Step 5: Notice that the bug IS present.
Step 6: Delete the previously added node.
Step 7: The problem stops again.

So adding a node, any node, triggers this issue.

**Comment by Kemeros** [comment]
@Calinou: Now that i think about it, wouldn't it also affect X and Z if it was the viewport size?

**Comment by nathanfranke** [comment]
I can no longer reproduce this as of v4.0.alpha.custom_build [898e09e2e], even after resizing the docks.
I also can no longer reproduce the similar 1px shifting in 3.4.4.stable

https://user-images.githubusercontent.com/14253836/175855509-290d97ff-7776-4121-b12b-8d8a1d5fbc55.mp4

**Comment by Calinou** [comment]
I can also reproduce this on 4.0.alpha d1dac8427 in a 2560×1440 maximized editor window (Linux, NVIDIA 510.68.02).

**Comment by nathanfranke** [comment]
Could be an Nvidia issue since I changed from Nvidia to AMD a few months ago

**Comment by Kemeros** [comment]
I indeed use a Nvidia card. I do not pocess a AMD card to test sadly.

**Comment by nathanfranke** [comment]
I can't reproduce on my laptop with a GTX 960M

Godot 4 alpha10

**Comment by Kemeros** [comment]
I'm using a GTX 1080 TI

**Comment by Chaosus** [comment]
I can no longer reproduce this issue (8c7be63588bf3e4ef4b780ff57936c68db5939c7) too

**Comment by Calinou** [comment]
I can still reproduce the issue on 4.0.alpha 0c5f25495 (Linux, NVIDIA 515.65.01):

https://user-images.githubusercontent.com/180032/188029411-9bf099e6-1e21-45d8-abb0-a6deb2a0ba56.mp4

**Comment by gelvinp** [comment]
Also encountering this (small) issue in 4.0.beta3.official

https://user-images.githubusercontent.com/61520531/197461714-b2b86607-13e3-4264-99cd-7eaa887b3bb5.mp4

**Comment by Jasuse** [comment]
It seems to be dependent on project config
If ```renderer/rendering_method="gl_compatibility"``` (under ```[rendering]```) is present in project,godot, the Y axis just flickers(relatively unnoticable), but if not, it will dissapear at certain angles

**Comment by Calinou** [comment]
> the Y axis just flickers(relatively unnoticable), but if not, it will dissapear at certain angles

This likely means OpenGL and Vulkan have different ways of rounding line widths when drawing lines. OpenGL prefers rounding up (meaning the line goes from 1 to 2 pixels wide), while Vulkan prefers rounding down (meaning the line goes from 1 to 0 pixels wide).

**Comment by HeraldOD** [comment]
I can reproduce this with v4.0.stable.official [92bee43ad], Windows 10, Nvidia GTX 1650, Forward+ renderer
It seems to only happen around the normal zoom level, it gradually stops flickering when zooming out past ~500u, or in past ~1.8u
My monitor is 1680x1050 if that matters at all

**Comment by krummja** [comment]
Not sure if this is useful information but I just noticed that the line stops disappearing when the viewport camera's angle is as high or low as it's able to go -- meaning that the Y axis that intersects the XZ plane is no longer visible.

Flickering:
![image](https://user-images.githubusercontent.com/36119791/235033795-b988e3d3-8040-4da8-85c2-431fddd4888f.png)

No flickering:
![image](https://user-images.githubusercontent.com/36119791/235033834-d822d072-d967-4278-bfff-2b9e903c6035.png)

Only difference between the first and second is a minute adjustment in camera angle.

**Comment by andersmmg** [comment]
This is still an issue, and I've seen it mentioned by people trying out the engine and being confused, notably [here](https://youtu.be/kIMHRQWorkE?t=932). It seems like it would be good to at least work around it soon

**Comment by Kemeros** [comment]
Still present in 4.1 RC3

**Comment by biswas08433** [comment]
I think there should be an option(s) to hide the origin axis gizmos

**Comment by aaronfranke** [comment]
@biswas08433 There already is. Click "View" -> "View Origin".

**Comment by biswas08433** [comment]
@aaronfranke I meant individually. So that we can disable the y axis. Its not that needed.

**Comment by aaronfranke** [comment]
For those experiencing this issue, please test this PR, which should fix it: https://github.com/godotengine/godot/pull/83895

**Comment by filipworksdev** [comment]
I do not see the axis dissappear in my Godot 4.1 . I'm on Windows 10  Intel Iris Xe 96 EU but on an older driver  which is more stable for me. Instead my grid flickers when I move. Do you guys think it could be related to the driver/gpu?

**Comment by Calinou** [comment]
> Do you guys think it could be related to the driver/gpu?

Yes, this issue only occurs on NVIDIA GPUs as described above.

**Comment by IGame4FUN** [comment]
why not add some red and blue in there and make it subpixel? would solve the issue and make it look better
btw, for me resizing the viewport fixed it as well (nvidia gpu, godot 4.2.1)

**Comment by Calinou** [comment]
> why not add some red and blue in there and make it subpixel? would solve the issue and make it look better btw, for me resizing the viewport fixed it as well (nvidia gpu, godot 4.2.1)

A solution has already been found: https://github.com/godotengine/godot/pull/83895
