### ISSUE TITLE
Pressing TAB in Snap Configure doesn't preselect values

### ISSUE THREAD

**Issue by theMotionblur** [godotengine/godot#37011]
This is more an inconsistency than a bug but it's certainly not a feature request.
So I hop this fits the description better.

**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
When entering values in the Snap settings (2D and 3D "Snap Configure" settings in the scene view)
does not preselect the values like the other numeric field inputs do.

**Steps to reproduce:**
Go to 3D or 2D Scene view,
Open the "Configure Snap..." dialog
Enter a value
Tab to another field

Values are not preselected. This is inconsistent to all the other numeric fields found in Godot.

**Comment by dreamsComeTrue** [comment]
Nope, current 3.2.1 on Win10 doesn't seem to have that issue :( 

![3 2 1 Win10](https://user-images.githubusercontent.com/1110337/76570009-ab5b4e00-64b4-11ea-99ca-d5964bce3a99.gif)

**Comment by dreamsComeTrue** [comment]
Actually not only 'Snap settings' doesn't highlight its controls while changing focus - I am proposing PR fixing those and other popups as well :)
