### ISSUE TITLE
KinematicBody move_lock_y does not do anything

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#37017]
**Godot version:**
951ecc4f7

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
![66f00ab9](https://user-images.githubusercontent.com/14253836/76577634-06307d80-6494-11ea-8a2d-10361026d9a8.gif)

```swift
func _physics_process(delta):
	move_lock_y = true
	move_and_slide(Vector3.RIGHT)
```

**Steps to reproduce:**

**Minimal reproduction project:**
[Test14.zip](https://github.com/godotengine/godot/files/4327166/Test14.zip)

**Comment by akien-mga** [comment]
I'm not sure that's a bug, I think `move_lock_y` only blocks translation on Y, not rotation.
There used to be an angular axis block too, but @reduz removed the property in c7e4527a88b without clear explanation (by mistake?).

**Comment by akien-mga** [comment]
CC @AndreaCatania who originally implemented this in 5dee44bbc13605348b65bc74878a5a8be2b50cbd.

**Comment by Ev1lbl0w** [comment]
Might be related to #36847

**Comment by RichardEllicott** [comment]
i also get this issue

so the move lock doesn't work, some of my objects are floating off

it is not the rotation, it is the position, it should lock the y position

**Comment by AndreaCatania** [comment]
Fixed with: https://github.com/godotengine/godot/pull/38852
