### ISSUE TITLE
CollisionObject._input_event click_position name is misleading

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#37019]
**Godot version:**

3.2.stable.custom_build

**OS/device including version:**

Linux 5.5.8-arch1-1

**Issue description:**

[CollisionObject._input_event](https://docs.godotengine.org/en/latest/classes/class_collisionobject.html#class-collisionobject-method-input-event) has the args `click_position` and `click_normal`.
The naming suggests that they are only valid for click events, but they in fact seem to be valid for `InputEventMouseMotion` as well.
This is great, but it seems like they should be called `mouse_(position,normal)` to indicate that they aren't just for clicks.

It seems like an easy fix, but I'm not sure if renaming an argument is considered a breaking change.
Would it affect language bindings for languages that support named arguments?

**Comment by Chaosus** [comment]
The naming issues are being collected and created within https://github.com/godotengine/godot/issues/16863. I've transferred your request to it. Closed.
