### ISSUE TITLE
Problems with NinePatchRect shrinking.

### ISSUE THREAD

**Issue by qq715152910** [godotengine/godot#37027]
**Problems with NinePatchRect shrinking.**

**Test:**

1.Use a 640x479 resolution picture, set the corner borders, and set the stretch to on.
2.Set rect_size to greater than 640x479, the corners and borders are normal.
3. Set rect_size to less than 640x479,  the corners and border cannot maintain the original size,and the pixels are completely distorted.
Cocos and Unity will not have such a similar problem.

**Error:**
Set rect_size <640x479, 
When reduced to 363x455, the corners and border cannot maintain the original size, and the pixels are completely distorted.

**Demo:**
[Demo-Download](https://codeload.github.com/qq715152910/Godot-Bug/zip/master)

**Bottleneck:**
This will cause confusion for some 2D developers. If the picture is reduced from the original size to the specified size and the corners and borders remain the same, this is definitely a bottleneck for now.

**Suggest:**
Add an Option to the Control-> NinePatchRect property menu to let developers freely choose whether it is turned on to reduce the size and keep the corner borders unchanged. At present, this will be the demand of many 2D developers.

**Comment by Ev1lbl0w** [comment]
Can you provide a sample project replicating this? I tried, but I probably didn't understood the issue, and couldn't reproduce it.

**Comment by qq715152910** [comment]
> Can you provide a sample project replicating this? I tried, but I probably didn't understood the issue, and couldn't reproduce it.
When zooming out, the border cannot maintain the original size, and the pixels are completely distorted.
[Demo](https://codeload.github.com/qq715152910/Godot-Bug/zip/master)

**Comment by qq715152910** [comment]
> 您可以提供一个示例项目来复制吗？我尝试过，但是我可能不理解这个问题，并且无法重现它。



> Can you provide a sample project replicating this? I tried, but I probably didn't understood the issue, and couldn't reproduce it.
