### ISSUE TITLE
Panning the 3D view at high zoom doesn't respond to the mouse

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#37034]
Godot 3.2
Godot 3.2.1
Windows 10 64 bits

When you are very zoomed in, panning in 3D doesn't respond well to the mouse.
![image](https://user-images.githubusercontent.com/1311555/76662570-449e6900-6576-11ea-9905-ec54f07fd765.png)

Use mouse wheel to zoom in, and try to pan holding Shift and MMB. If you pan slow enough, it stops moving. The closer you are to the maximum zoom, the worse it gets.

note: it is normal that panning happens over shorter distances as zooming makes the reference frame smaller. However I'm reporting an erratic/complete absence of movement.

https://youtu.be/XITvPpI8PxY

**Comment by Calinou** [comment]
This is surely due to a floating-point precision error, but I'm not sure where it comes from.

**Comment by Zylann** [comment]
I'm skeptical about the floating-point error though, that zoom doesnt seem high enough. Something (like a hardcoded threshold?) might amplify this by a lot...
Also moving with arrow keys at very low speed remains possible.
