### ISSUE TITLE
Engine.is_editor_hint() does return false while running inside the editor

### ISSUE THREAD

**Issue by CaptainDario** [godotengine/godot#37049]
**Godot version:**
Godot 3.2 stable official

**OS/device including version:**
Manjaro i3
cat /etc/lsb-release:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=19.0.2
DISTRIB_CODENAME=Kyria
DISTRIB_DESCRIPTION="Manjaro Linux"

**Issue description:**
Maybe this is just a misleading description of this variable, but to my mind it sounds like "editor_hint" can be used to check if the game is running inside of the editor. I read this [thread](https://godotengine.org/qa/15966/how-can-i-check-if-tool-script-is-running-on-editor) and the [docs](https://docs.godotengine.org/en/3.2/classes/class_engine.html#class-engine-property-editor-hint) 

> If true, it is running inside the editor. Useful for tool scripts..

However Engine.is_editor_hint() returns false for me inside the editor

**Steps to reproduce:**

1. Create a project
2. Create a script
3. add:
```	
func _ready():
    if(Engine.is_editor_hint()):  
        print("asd")
```

**Minimal reproduction project:**
Does work with an empty project and only the script from above.

**Comment by Zireael07** [comment]
The script is not a "tool" script. In that case, it only runs once you launch the game instance, which is not "inside the editor".

**Comment by CaptainDario** [comment]
Thank you!
This was my fault I understood the docs otherwise. So there does not exist a way to check if the game is an "compiled executable" or not?

**Comment by Zireael07** [comment]
It has nothing to do with the game being a compiled executable or not. The function is there to let you do things within Godot editor itself, e.g. automate creating a map or draw helper lines within the editor viewport.

**Comment by CaptainDario** [comment]
Yes, I understand that this is not the function I am searching.
But does such a function exist?

**Comment by dalexeev** [comment]
> But does such a function exist?

See `OS.is_debug_build()`, `OS.has_feature()`.

**Comment by CaptainDario** [comment]
Thank you very much.
Somehow I did expect something like [this](https://docs.unity3d.com/ScriptReference/Application-isEditor.html). Most probably because I just switched to Godot.

**Comment by doot24** [comment]
For anyone who might come across this issue later on, you can use OS.get_name() to get the platform your game is currently running on.

**Comment by berarma** [comment]
> Thank you very much. Somehow I did expect something like [this](https://docs.unity3d.com/ScriptReference/Application-isEditor.html). Most probably because I just switched to Godot.

I think this is what you want:

`OS.has_feature("editor")`

It will return `true` when running from the editor. There's also a "standalone" feature that I think is complementary.

See: https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html

**Comment by Nsyse** [comment]
Came here looking for the same thing and think I found a way to do it now :

Engine.is_embedded_in_editor()
