### ISSUE TITLE
Mac OSX compilation produces a not executable application and templates

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#37041]
macOS Catalina 10.15.3
Macbook Air

Steps:
```
-downloaded 3.2 Godot source from https://github.com/godotengine/godot/releases
-compiled code using http://docs.godotengine.org/en/stable/development/compiling/compiling_for_osx.html
-compiled templates using https://godotforums.org/discussion/20550/how-to-create-export-templates using Calinou's response
-used template in exporting a mac build from both windows and same mac
-running the template gives "LSOpenURLsWithRole() failed with error -10810 for the file"
```

This is preventing me from supporting mac steam build.

**Comment by Calinou** [comment]
The export template will have its executable flag disabled due to macOS security restrictions. I'm not sure if we can do anything about it just yet. See also #36332 where I had the same problem.

**Comment by rokasv** [comment]
The compilation also fails for creating the Editor application with the same error (using 3.2.1 source).
In effect, I can't compile the engine from source.

**Comment by rokasv** [comment]
Yeah, turns out this happens if the folder structure required by the module I was trying to integrate is not maintained. It's not a Godot issue. Closing.

If anyone's hitting the same wall as the dumb me, don't skip the
```NOTE: For OSX, the libsteam_api.dylib and steam_appid.txt must be in the Content/MacOS/ folder in your application zip or the game will crash```
part of the godot steam tutorial.
