### ISSUE TITLE
Face3::get_area() returns twice the area it should

### ISSUE THREAD

**Issue by GNSS-Stylist** [godotengine/godot#37048]
**Godot version:** 3.2.2 (most probably all)

**Issue description:**
While twiddling with the (quite nice) hydro module ( https://gitlab.com/ringtechsolutions/godot-tools/hydro/hydro ) I stumbled upon strange behavior with buoyancy. For example a cube with a volume of 1 and mass of 990 dropped into water with a density of 1000 caused it to float about half when it should "almost sink" instead:
![990kg_1m3_Cube_Before](https://user-images.githubusercontent.com/50438441/76683153-7eb94a80-660a-11ea-8fe6-359d5c40657f.PNG)

After trying to find out a bug in my own project and hydro module I took a look at the lower level code. It looks like the function Face3::get_area() in core/math/face3.cpp returns twice the area it should: 

`return vec3_cross(vertex[0] - vertex[1], vertex[0] - vertex[2]).length();`

After adding " / 2.0" to the formula above, the buoyancy seemed to be correct:
![990kg_1m3_Cube_After](https://user-images.githubusercontent.com/50438441/76683226-220a5f80-660b-11ea-859b-e7f0471a9035.PNG)

"Reference": http://www.maths.usyd.edu.au/u/MOW/vectors/vectors-11/v-11-7.html

Fixed this in my forked repo (3.2-branch): https://github.com/GNSS-Stylist/godot/commit/e3cd0fe8516842291adac0e123f7552183b54a6a

**Minimal reproduction project:**
[BuoyancyTest.zip](https://github.com/godotengine/godot/files/4332840/BuoyancyTest.zip)
(Note that this needs the hydro module mentioned above to work.)

This is actually my first bug report (and/or possible bug fix?) to a github-project of this scale so forgive me if this there's something wrong somehow. Not even trying to make a pull request for now as this function is used in some other places like ParticlesEditorBase and MultiMeshEditor. I have no idea what the side effects with this change could be.

**Comment by simpuid** [comment]
Go ahead and open a PR. The only change I would suggest is to multiply the value with 0.5 instead of dividing it with 2.0, multiplications are faster than division.
