### ISSUE TITLE
Select All in the inspector text boxes might trigger Create New Node dialog

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37054]
**Godot version:**
3.2.1

**Steps to reproduce:**
1. Create a new node (must be done via shortcut, i.e. Ctrl + A)
2. Enter some text to the Editor Description of that node
3. Press Ctrl + A to select all text
4. ->Create New Node appears again

If you try to do Ctrl + A again or didn't use the shortcut to add the node, the text will be correctly selected.

**Comment by dreamsComeTrue** [comment]
It was all about improper event propagation, as Add Node button was stealing it, while GUI event occured on other control. I explained more in attached PR.
