### ISSUE TITLE
Mono Project whose name and folder contain spaces won't compile properly

### ISSUE THREAD

**Issue by rafaelgdp** [godotengine/godot#37059]
**Godot version:** 3.2.1 stable

**OS/device including version:** MacOS Catalina. MBP 2018.

**Issue description:** Whenever I create a Godot Mono Project inside a project folder with spaces (" ") in its name and the project name itself also has spaces, new C# scripts will not be included automatically inside its ItemGroup in the csproj file. I think this issue is related to issue #36168, but I have not noticed the %20 in the csproj file nor in the Godot console logs when I press build.

**Steps to reproduce:** Create a Godot Mono project whose name and folder have words separated by spaces. Then, inside Godot, create a new scene and add a C# script to it with some logic. The game builds with errors. If you run the game inside Godot, it actually initializes the game, but none of the C# scripts are run because they were not compiled.

**Minimal reproduction project:** NA

**Comment by aaronfranke** [comment]
Does the project work if you change the folder name to not have spaces? [These projects](https://github.com/godotengine/godot-demo-projects/tree/master/mono) all have spaces in the project names but not in the folder names, so I'm wondering if it's just the folder name.

**Comment by Tobi-Mob** [comment]
Godot 3.3.3 on Linux does not show that problem.
The mentioned issue is also already closed: https://github.com/godotengine/godot/issues/36168

![grafik](https://user-images.githubusercontent.com/69400800/133039441-8353fa16-59ae-47f3-9322-91bde4e66089.png)
