### ISSUE TITLE
(Vulkan) 2D Pixel Import Not Working

### ISSUE THREAD

**Issue by paulhocker** [godotengine/godot#37057]
**Godot version:**
4.0 custom build f65781fe7

**OS/device including version:**
Windows 10

**Issue description:**

Importing PNG and attempting to re-import using 2d Pixel does not result in a pixel perfect texture. This problem has actually been for while now and I was waiting to report it.

**Steps to reproduce:**

Start a new 4.0 project. Add a new pixel like texture. Drag the Texture onto a new scene and notice how the image is blurry. Select the Import Tab. Select 2D Pixel from the drop down. Click Re import button. Notice that nothing happened to the Texture. 

See video below for example.

[2020-03-14_18-20-28.zip](https://github.com/godotengine/godot/files/4333527/2020-03-14_18-20-28.zip)

**Minimal reproduction project:**

Sample project is attached.

[2dpixel-vulkan.zip](https://github.com/godotengine/godot/files/4333530/2dpixel-vulkan.zip)

**Comment by clayjohn** [comment]
Filter options are set on materials now rather than on the textures themselves. Have you tried looking in the material options?

**Comment by paulhocker** [comment]
Oh?!? I did not realize that. I will try that out.

**Comment by paulhocker** [comment]
Okay. I have searched the interwebs, is there any information on how to do this? I do not see anything yet in the new Master Branch docs yet.

**Comment by clayjohn** [comment]
This is all very new and the API isn't set in stone yet. So you won't find many docs. 

To set the default texture filter for a sprite, look in the Sprite's inspector > CanvasItem > Texture > Filter - set to "Nearest"

**Comment by paulhocker** [comment]
Got it Thanks. So that works great for individual sprites but does not seem to work on my tilemaps? Is there a different setting for that somewhere? I changed the same setting on the Tilemap object.

**Comment by clayjohn** [comment]
@paulhocker sorry, I don't know. I haven't spent any time with 2D. 

It's too early to expect everything to work. Just be patient and things will get implemented and the docs will get written.

**Comment by paulhocker** [comment]
no worries -- i really do appreciate the help -- i will open another ticket on the tilemaps -- thanks

**Comment by KoBeWi** [comment]
@paulhocker You can try changing Project Settings -> Rendering -> Canvas Textures -> Default Texture Filter. Although if you say that the local setting doesn't work for TileMaps, I doubt the global one will...

**Comment by Chaosus** [comment]
This should probably be added to the documentation.

**Comment by paulhocker** [comment]
I have confirmed that globally changing the default texture filter does not change the texture for tilemaps nor does it help changing existing ones -- as i mentioned i will be opening a separate ticket for this -- I have never done documentation before but I might take a stab at it for this one -- thanks everyone

**Comment by MCrafterzz** [comment]
The filter property in the Texture tab for the tilemap has no effect regardless of which option is set so it is not a problem specifically with the nearest option.

**Comment by Calinou** [comment]
@MCrafterzz If the filter option has no effect on a given node, this should be reported in a separate issue (after searching for duplicates).
