### ISSUE TITLE
How to Destroy Proyect Option's window

### ISSUE THREAD

**Issue by SergioJimenezM** [godotengine/godot#37052]
GodotEngine V3.2 Stable from steam

Opensuse Tumbleweed

the project options window looks like this
![BUG GodotEngine](https://user-images.githubusercontent.com/17734990/76689524-5f1b2580-65fc-11ea-9e04-ae2a2c9266a4.png)

In the section memory > limits, lower the maximum value of Max Size Kb to 256, the other projects work well, but the menu is damaged in this specific project

![ventanaBien](https://user-images.githubusercontent.com/17734990/76689588-0009e080-65fd-11ea-95ea-96c2312fd0f2.png)

**Comment by Calinou** [comment]
I guess we should change the setting it to prevent decreasing its value below 1024 :slightly_smiling_face:

**Comment by SergioJimenezM** [comment]
I have been trying to break something for a long time and this is the first time that I succeed, maybe it will even be useful for the project XD
