### ISSUE TITLE
[3.2.1] struct error in shader

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#37079]
**Godot version:**
3.2.1
**OS/device including version:**
Win 10
**Issue description:**
the struct key word doesn't seem to exist as per the godot documentation 
([doc](https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#structs))

when typed in to the shader editor in the global scope it returns the error [ Expected constant, function, uniform or varying]

**Steps to reproduce:**
1. open attached project
2. open errorous shader.shader
3. note error
**Minimal reproduction project:**
[errorous project.zip](https://github.com/godotengine/godot/files/4335611/errorous.project.zip)

**Comment by akien-mga** [comment]
https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#structs is the documentation for the `latest` branch, i.e. 4.0.

Godot 3.2 doesn't have `struct`s: https://docs.godotengine.org/en/3.2/tutorials/shading/shading_reference/shading_language.html

**Comment by albinaask** [comment]
Ah, my bad! thanks
