### ISSUE TITLE
`p_validate_certs` is set to `false` while it is set to true in parent class.

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#37084]
**Godot version:**
master build 2a49798

**OS/device including version:**
Windows 10 1909 Pro 64 bit

**Issue description:**
A potential bug.
https://github.com/godotengine/godot/blob/2a49798c7b92b332c2198f52b9c5ae10bd944bd0/modules/mbedtls/packet_peer_mbed_dtls.h#L70

`p_validate_certs` is set to `false` while it is set to true in parent class.
`p_validate_certs` will always be `true`.
Found by LGTM.
Alert: _Parameter p_validate_certs redefines its default value to 0 from the inherited default value 1 (in PacketPeerDTLS). The default value will be resolved statically, not by dispatch, so this can cause confusion._([more info](https://lgtm.com/rules/2153510663/))

**Steps to reproduce:**
1. Visit https://lgtm.com/projects/g/godotengine/godot/snapshot/e391652803e06ad84627e5e591c219c9dd20e8b1/files/modules/mbedtls/packet_peer_mbed_dtls.h.

**Minimal reproduction project:**
NA.

I couldn't find any issue related to this.

**Comment by Faless** [comment]
Yeah, can just be changed to `true` there.
The behaviour is correct, probably forgot to update the `= false` to `= true` there during refactor.
