### ISSUE TITLE
Error to buid project

### ISSUE THREAD

**Issue by DaviDevLop** [godotengine/godot#37092]
**Godot version:**
3.2.1
**OS/device including version:**
Windows 10
**Issue description:**
When I try to execute my game this happens:
Projeto "AprendendoGodot.sln" (Build destino(s)):
	Message: Compilando a configuração de solução "Tools|Any CPU".
	Projeto "AprendendoGodot.csproj" (destinos padrão):
		C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: os assemblies de referência para .NETFramework,Version=v4.7 não foram encontrados. Para resolver isso, instale o Pacote do Desenvolvedor (SDK/Pacote de Direcionamento) dessa versão do Framework ou redirecione seu aplicativo. É possível baixar Pacotes do Desenvolvedor do .NET Framework em https://aka.ms/msbuild/developerpacks [D:\Projetos C# Godot\AprendendoC#\AprendendoGodot.csproj]
	Projeto de compilação pronto "AprendendoGodot.csproj" -- FALHA.
Projeto de compilação pronto "AprendendoGodot.sln" -- FALHA.

**Comment by Anutrix** [comment]
As the error states, have you tried downloading and installing Developer Pack for DotNet Framework 4.7?

**Comment by DaviDevLop** [comment]
> Como o erro indica, você tentou baixar e instalar o Developer Pack for DotNet Framework 4.7?

Yes!

**Comment by Anutrix** [comment]
Do you have that exact version?
Are you sure you the developer pack not just dotnet framework?
Download from here: https://www.microsoft.com/en-us/download/details.aspx?id=55168.

**Comment by groud** [comment]
As suggested, you probably miss the the .Net framework for your project. This is not a bug with Godot itself.
Please use the other community channels to ask for help.
