### ISSUE TITLE
Godot Mono fails to check for .cs files added by external tools

### ISSUE THREAD

**Issue by KvaGram** [godotengine/godot#37093]
**Godot version:**
Godot Engine v3.2.1.stable.mono.official
**OS/device including version:**
Linux Mint 19.3 Cinnamon, kernel 4.15.0-72-generic
**Issue description:**
I was setting up the backend logic of my game demo, creating classes, structs and enums using Visual Studio Code, and one 'main' class set as a singleton Node (autoload).
When attempting to compile and run, Godot report a list of build errors,
eg: The type or namespace name X could not be found (are you missing...
One error for each type refrenced in my 'main' class.

Workaround:
Opening the .csproj file, I located the Compile Include list.
Manually entering each .cs file did the trick.

**Steps to reproduce:**
1: Add c# script in godot
2: create new c# class in same directory, using any external tools
3: use/reference the externally created class in the first class
4: press play in Godot engine
5: observe error log

**Minimal reproduction project:**

**Comment by spacechase0** [comment]
I'm not familiar with VSCode, but in Visual Studio I have to press "Save all" so it saves the project file after adding new .cs files.

**Comment by KvaGram** [comment]
Unlike visual studio, VSCode is not a full IDE. It is an enhanced text editor designed for programming.
There are plugins that providesyntax hilights, intellisense, debug support, etc, making it is very good universal substitute.
I did find a plugin for Godot engine, and I am trying it now.

**Comment by KvaGram** [comment]
The plugin did not fix the issue.

**Comment by groud** [comment]
cc @neikeq

**Comment by neikeq** [comment]
I'm closing this as it's unlikely to be addressed in 3.2.x and it won't be a problem in 4.0 with project sdks.
For 3.2, make sure to create the script from Godot or an IDE. In the case of VSCode, this extension may help: https://marketplace.visualstudio.com/items?itemName=lucasazzola.vscode-csproj
You could also change your csproj to use wildcards to include all files in the project (`<Compile Include="**/*.cs" />`). This way it won't need to be updated every time there's a new file or when a file is removed.
