### ISSUE TITLE
Exported dictionary resetting it's value

### ISSUE THREAD

**Issue by doot24** [godotengine/godot#37098]
Godot version: 3.2.1

OS/device including version: Arch Linux,Kernel 5.5.8

Issue description: Adding a second value to a exported dictionary resets the added value, but if you add a third value, the second value doesn't reset.

here is the video demonstrating the issue.
[issue.zip](https://github.com/godotengine/godot/files/4340111/issue.zip)

**Comment by groud** [comment]
This is the expected behavior, you have to click on the "add key/value pair" button for the value to be added. On your video you only added two value, not three.

If you don't do it, the fields are reset if you unselect the node (since you did not validate your input).

**Comment by Calinou** [comment]
@groud We should find a way to make it clearer somehow, but I'm not sure how exactly.

**Comment by groud** [comment]
> @groud We should find a way to make it clearer somehow, but I'm not sure how exactly.

Yes, me neither. It seemed clear to me, but if anyone has a way to improve it, a specific proposal could be made I guess.

**Comment by doot24** [comment]
@Calinou  What if when you fill in both key and value fields it just gets automatically added to the dictionary without having to click Add Key/Value Pair button again?

**Comment by groud** [comment]
No, this would really confuse users. The one thing we could do is maybe automatically change the focus to the button once you're done filling the values, so that pressing enter would add it right away. 

Also, the button should be grayed out if you have invalid values.

**Comment by doot24** [comment]
@groud Having the button grayed out until you have invalid values is a better option.

**Comment by CrumblingAway** [comment]
For what it's worth this is still relevant today. In hindsight the behavior does make sense but it was unclear to me as well.

**Comment by shawcmat** [comment]
This caused quite the headache for me as well recently. I think the problem is that the "Add key/value pair" button could also appear to simply be adding a new blank item to the dictionary which the user then can then fill afterward, instead of its intended behavior of submitting the previously entered values as a new key/value pair. Honestly this could be resolved as easily as renaming the button. "Add" as a verb could be taken in multiple different ways. Something like "submit", "save", "commit",  etc. might be more intuitive.

**Comment by mutecanary** [comment]
I had the same exact problem for hours now and tried so many different things, this is NOT intuitive ui in the inspector. "+ Key/Value Pair" implies adding a new pair, NOT confirming the current pair. This needs to change. It should say "Confirm selection" or something to that effect.
