### ISSUE TITLE
Baked lightmap traces a strange glow around some adjacent mesh edges

### ISSUE THREAD

**Issue by rhossack** [godotengine/godot#37100]
**Godot version:** 3.2

**OS/device including version:** Windows 10

**Issue description:**
Here, there are two lights, both on one side of a wall comprised of 6 thin meshes. I would expect the other side of the wall to be dark; instead, it's dark, with streaks of light shining through at some of the seams for no good reason. I zoomed in and made sure that each mesh had a very slight overlap, and used a high-quality ray traced baked lightmap, so I'm not sure what's causing this if not a bug.

![lighting issue](https://user-images.githubusercontent.com/21226177/76797536-00d07d00-678b-11ea-9d62-64199d07714e.PNG)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Related to #37100. The lightmapper is undergoing a full rewrite in Godot 4.0.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. (Either way, the lightmapper will be rewritten very soon.)
