### ISSUE TITLE
Windows 10: mouse cursor is not shown again after setting MOUSE_MODE_VISIBLE

### ISSUE THREAD

**Issue by miskatonicstudio** [godotengine/godot#37103]
**Godot version:**

3.2.1 stable

**OS/device including version:**

Windows 10, with or without Nvidia drivers

**Issue description:**

In specific cases, setting MOUSE_MODE_HIDDEN and then MOUSE_MODE_VISIBLE does not bring the cursor back. It's possible that it only happens when another mode (e.g. CAPTURED) is involved in between.

**Steps to reproduce:**

* start the default GOAT game
* finish the game
* wait for the credits scene to end
* the program goes back to main menu
* the cursor is not shown, but it is detected (buttons can be hovered)

Notes:
* switching to another window and back using Alt+Tab brings back the cursor
* going to credits directly from the main menu and then back to main menu does not cause this issue
* the issue does not occur on Ubuntu 18.04

**Minimal reproduction project:**

Reported as part of the GOAT project, original issue with comments:
https://github.com/miskatonicstudio/goat/issues/219

**Comment by Cheeseness** [comment]
I also had reports of this on both Mac and Windows with Hive Time.

**Comment by akien-mga** [comment]
CC @guilhermefelipecgs @bruvzg

**Comment by bruvzg** [comment]
In case of macOS issue is probably cased by multiple `CGDisplayHideCursor` calls followed by a single `CGDisplayShowCursor`, according to docs `CGDisplayShowCursor` "decrements the hide cursor count, and shows the mouse cursor if the count is 0."

https://github.com/godotengine/godot/blob/75791358c6ab3f2a4217aec1af399ef10ccd7407/platform/osx/os_osx.mm#L3071-L3083

**Comment by bruvzg** [comment]
On Windows it seems to be similar, `SetCursor(nullptr)` which returns current cursor handle is called multiple times without checking current mouse mode on overwrites saved old cursor with the `nullptr` on second call.

https://github.com/godotengine/godot/blob/3e0708094276fdb80a6b6929070fecf6fe5858bc/platform/windows/display_server_windows.cpp#L105-L111

**Comment by bruvzg** [comment]
Another part of the issue on Windows: `mouse_mode` is set after `_set_mouse_mode_impl` call, which calls `cursor_set_shape` to restore cursor, and fails cause `mouse_mode` is still set to `HIDDEN`/`CAPTURED`.

https://github.com/godotengine/godot/blob/417d15a23ae6d4a4227eea40a72472d9c932f26f/platform/windows/display_server_windows.cpp#L1147-L1150

https://github.com/godotengine/godot/blob/417d15a23ae6d4a4227eea40a72472d9c932f26f/platform/windows/display_server_windows.cpp#L120-L122

**Comment by Cheeseness** [comment]
#39750 mentioned that the Windows fix had only been confirmed via Wine on MacOS. If it's helpful to know, I've had a user confirm the corresponding version of this fix from the 3.2 branch as resolving previously reported problems in Hive Time. Many thanks :)

**Comment by miskatonicstudio** [comment]
I can confirm that the original issue from GOAT is resolved :) Thank you for taking care of this!
