### ISSUE TITLE
Properties don't appear in autocompletion outside functions

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37119]
**Godot version:**
3.2

**Issue description:**
Ok
![image](https://user-images.githubusercontent.com/2223172/76889908-b3393a80-6886-11ea-9cc4-cdd7c37e6991.png)
Not ok
![image](https://user-images.githubusercontent.com/2223172/76889965-c815ce00-6886-11ea-8edc-93044ed3a3cd.png)

(script extends Node2D-derived class)

**Comment by theoway** [comment]
@KoBeWi  I'd like to work on this issue. Could you tell me where can I find the code for auto completion feature? Is it in gdscript_pasrser file?

**Comment by KoBeWi** [comment]
It's in `gdscript_editor`. You could check this PR for reference #34286 (or some similar ones)

**Comment by theoway** [comment]
@KoBeWi  Thanks. I'll start looking into it.

**Comment by theoway** [comment]
I've found out where the issue is. I'll be opening a PR soon.
