### ISSUE TITLE
AnimationTreePlayer does not properly animate transform properties when using Normal Tracks

### ISSUE THREAD

**Issue by xelivous** [godotengine/godot#3711]
#### Problem

* Create a Skeleton
* Attach a hierarchy of BoneAttachment
* Create an animation using AnimationPlayer
* Using Normal Tracks, modify/insert keyframes for position/rotation of the various BoneAttachment nodes
* Play animation using the AnimationPlayer, and everything works as expected

Then,

* Create AnimationTreePlayer
* Specify the "Master Player" as the previously created AnimationPlayer, modifying the base node if necessary.
* In the nodegraph editor, create an Animation Node to output into the Out node
* Click play in AnimationTreePlayer editor, and all bones affected in the animation have their transforms reset to 0.

---

#### Specs

* **OS:** Windows 7 x64
* **Godot Build Version:** https://github.com/godotengine/godot/commit/ad405ade17630c927e06530dbbaad4e730193774
* **Graphics Card:** Nvidia 660 Ti (Driver: v10.18.13.5891)

---

#### Example Project

I included some helpful controls for ease of debugging while the game is playing, just for posterity.

[AnimationTreePlayer.zip](https://github.com/godotengine/godot/files/130077/AnimationTreePlayer.zip)

---

#### Unnecessarily complex example video

This is an example video of the project that I originally discovered the issue in, and then stripped down to make the example project above. As such, it's far more complex than the example project, but it still gives a good example of showcasing the issue at hand.

https://www.youtube.com/watch?v=AcAKR65RNEA

**Comment by JoshuaGrams** [comment]
Sorry, I haven't been following the issue tracker lately. I *think* that it just doesn't know how to blend 3D rotations except in the Transform Track code. If that's the case it's definitely my fault and it should be a quick fix...

**Comment by JoshuaGrams** [comment]
Yeah...but not *just* that. It was also treating it as if an (empty) transform track was there even though they were all supposed to be value tracks.

And hmm...it didn't automatically reference this issue, so... pull request #3991 fixes your example for me...

**Comment by xelivous** [comment]
Yep it fixes it for me as well, thanks for looking into it.
