### ISSUE TITLE
LineEdit, Placeholder being affected by Max Length

### ISSUE THREAD

**Issue by Firty** [godotengine/godot#37120]
Godot version: 3.2.1 64x
OS: Windows 10 Pro 64x
Issue description: Placeholder being affected by Max Legth.
Steps to reproduce: LineEdit: Align = Center; Max Legth = 3; Placeholder.text = any word with more than three letters.

I may be wrong but the Placeholder could not be affected by Max Legth, because it only happens with align center.

**Comment by simpuid** [comment]
Can confirm, placeholder is misaligned when it is greater then max length. Working on a fix.
