### ISSUE TITLE
Little typo in the import_textures wiki page

### ISSUE THREAD

**Issue by batiste** [godotengine/godot#3712]
It starts with

"Do NOT to import them in most cases."

Which sounds wrong. Should be: 

"Do NOT import them in most cases."

or

"in most cases you should no import them"

**Comment by neikeq** [comment]
The new wiki will be http://docs.godotengine.org (the github wiki will be removed soon)
It is hosted in a github repository, so you can make pull requests: https://github.com/godotengine/godot-docs

**Comment by djrm** [comment]
Now the github wiki has been removed maybe this should be moved to https://github.com/godotengine/godot-docs

**Comment by neikeq** [comment]
Yes, but this is fixed already: https://github.com/godotengine/godot-docs/blob/master/tutorials/asset_pipeline/importing_textures.rst#do-not-import-them-in-most-cases
