### ISSUE TITLE
KinematicBody's move methods are inconsistent

### ISSUE THREAD

**Issue by Ev1lbl0w** [godotengine/godot#37132]
`move_and_collide` requires we multiply the argument with `delta` to have consistent movement, while in `move_and_slide` we shouldn't do this, as it is done internally.

Is there a good reason for this behaviour? Right now it's very confusing why I need to multiply `delta` on one method and not on another, considering they do similar stuff. Not to mention, having to "remember" which one should and shouldn't have it.

I propose making `move_and_slide` need the `delta` argument too, so it's consistent. But of course, this would be a breaking change.

**Comment by Calinou** [comment]
#33653 will allow you to pass an optional argument to `move_and_slide()`.

**Comment by Calinou** [comment]
I'm pretty sure there's already an issue discussing this, but I can't find it right now.

**Comment by Ev1lbl0w** [comment]
Yeah, I figured someone must have talked about it by now, but when I searched for it, I couldn't find anything.

Should I close this issue then?

**Comment by Calinou** [comment]
Yes, it seems the same discussion is occurring in #30029.
