### ISSUE TITLE
Mono crash using SQLite - Dapper

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#37137]
**Godot version:**
3.2.1 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
When i run the project crash. See file attached as result

I'm using 
using Mono.Data.Sqlite;
using Dapper.Contrib.Extensions;

**Steps to reproduce:**

Add the follow code in any _ready function
Add the class Employee too
Change Log.Printi with Print

I have this configuration in .csproj
```
  <ItemGroup>
    <PackageReference Include="CsvHelper">
      <Version>15.0.1</Version>
    </PackageReference>
    <PackageReference Include="Dapper">
      <Version>2.0.30</Version>
    </PackageReference>
    <PackageReference Include="Dapper.Contrib">
      <Version>2.0.30</Version>
    </PackageReference>
    <PackageReference Include="Mono.Data.Sqlite">
      <Version>1.0.61</Version>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" /
```

**Minimal reproduction project:**
```
       string strCheckTable = "SELECT name FROM sqlite_master WHERE type='table' AND name='{Employees}'";
        string strCreateTable = "CREATE TABLE Employee (Id intchar (2), FirstName nvarchar(32), LastName nvarchar(32))";


        string cs = "Data Source==SqliteTest.db";
        using (var con = new SqliteConnection(cs))
        {
            con.Open();

            using (var _checkTableCmd = new SqliteCommand(strCheckTable, con))
            {
                if (_checkTableCmd.ExecuteNonQuery() == 0)
                {
                    Log.Printi("Table employees not found. Creating.. ");

                    using (var _createTableCmd = new SqliteCommand(strCreateTable, con))
                    {
                        string _rows = _createTableCmd.ExecuteNonQuery().ToString();

                        Log.Printi("Rows addded ", _rows);
                    }
                }
                else
                {
                    Log.Printi("Table employees found");
                }
            }
            Employee _get = con.Get<Employee>(0);
            Log.Printi(_get);
        }
[Table("Employee")]
public class Employee
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

[mono_crash.35eaae22c.0.json.zip](https://github.com/godotengine/godot/files/4348655/mono_crash.35eaae22c.0.json.zip)

**Comment by git2013vb** [comment]
I think I found the problem:
Employee _get = con.Get<Employee>(0);
The Get method require not the first record but the Id value (I read again the Dapper documentation)
Means the Employee table the first record "Id" is 1 as value

![image](https://user-images.githubusercontent.com/13235119/76962244-c693e680-6916-11ea-9f82-0c80c7c16dc9.png)

Also I use `string _tableFound = _checkTableCmd.ExecuteScalar() as string;` to check if the table exist. Seems `ExecuteNonQuery` return every time 0. With `ExecuteScalar` I'll check the table name instead.

You can close this one for now - it remain as troubleshooting I guess-.

**Comment by Calinou** [comment]
Closing per @git2013vb's request.
