### ISSUE TITLE
OpenGL ES 2.0 does not allow retrieving mesh array data

### ISSUE THREAD

**Issue by CaptainDario** [godotengine/godot#37147]
**Godot version:**
latest stable: GodotEngine v3.2.1.stable.official

**OS/device including version:**
Manjaro i3
cat /etc/lsb-release:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=19.0.2
DISTRIB_CODENAME=Kyria
DISTRIB_DESCRIPTION="Manjaro Linux"

**Issue description:**
I build a small puzzle game and it is running just fine in the editor. However when I export the game this message pops up in the output. I am using the debug mode.
WARNING: _update_root_rect: Font oversampling does not work in 'Viewport' stretch mode, only '2D'.
   At: scene/main/scene_tree.cpp:1236.
ERROR: mesh_surface_get_array: OpenGL ES 2.0 does not allow retrieving mesh array data
   At: drivers/gles2/rasterizer_storage_gles2.cpp:2596.
ERROR: mesh_surface_get_array: OpenGL ES 2.0 does not allow retrieving mesh array data
   At: drivers/gles2/rasterizer_storage_gles2.cpp:2596.

**Steps to reproduce:**
Build the project and run in on linux.

**Minimal reproduction project:**
I can upload the whole project if necessary next week.

**Comment by Calinou** [comment]
> I can upload the whole project if necessary next week.

We really need the project to be available to be able to troubleshoot this, so please upload it when you can.

**Comment by CaptainDario** [comment]
Thank you for the quick reply.
I wasn't sure if this error was maybe due to an (obvious) miss use from my usage.
Because I have to hand in a paper about the game I cannot give it out now.
But I will do that as fast as I can.

**Comment by CaptainDario** [comment]
Hello,
I have uploaded the project [https://github.com/CaptainDario/DaBlocksWorld](herel)

**Comment by SuperDIMMaX** [comment]
Some problem(3.2.2.stable), but exporting on Web - in chrome developer console log: _OpenGL ES 2.0 does not allow retrieving mesh array data_

**Comment by Calinou** [comment]
Closing, as this appears to be resolved in 3.3 and later as per https://github.com/Revolutionary-Games/Thrive/issues/1576.
