### ISSUE TITLE
Linux Compilation problem: platform/x11/joystick_linux.cpp:36:21: fatal error: libudev.h: No such file or directory

### ISSUE THREAD

**Issue by purpleorangegames** [godotengine/godot#3714]
All my linux builds failed with this error.

platform/x11/joystick_linux.cpp:36:21: fatal error: libudev.h: No such file or directory

I'm compiling on linux with gamepad=no to avoid this issues.

**Comment by purpleorangegames** [comment]
It seems they changed from gamepad to udev

on platform/x11/detect.py:
before: ('gamepad','Gamepad support, requires libudev and libevdev','yes'),
after: ('udev','Use udev for gamepad connection callbacks','no'),

**Comment by Hinsbart** [comment]
oops, sorry. Forgot to `#ifdef` the `#include <libudev.h>`
I'll fix it right away

**Comment by purpleorangegames** [comment]
Thanks!
