### ISSUE TITLE
Audio buses are ignored while playing sound in the editor

### ISSUE THREAD

**Issue by lukaskotik** [godotengine/godot#37157]
**Godot version:** Godot 3.2.1 stable

**OS/device including version:** Ubuntu 18.04.4 Gnome

**Issue description:** `AudioStreamPlayer bus` property is ignored when playing sound in the editor (prewiev sound in the bottom of AudioStreamPlayer inspector). Whatever bus I set the stream is always sent to `MasterBus`. Whe running project, everything works as expected.

**Steps to reproduce:** Add `AudioStreamPlayer` to the scene, add new bus and set e.g. reverb effect for it, connect this bus to masterbus, connect `AudioStreamPlayer` to the new bus. When run stream in editor there is no reverb effect.

**Comment by Calinou** [comment]
Duplicate of #28060.
