### ISSUE TITLE
StaticBody rotation 3d normal

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot#37177]
**Godot version:** 3.2.stable.official

**OS/device including version:** Windows 10

**Issue description:** Hello everyone! I'm having a issue with StaticBody rotation collision:
In my player scene, I have a Raycast pointing downwards to detect floor normal, so my player follow
the floor rotation. Everything is fine with a simple static body with a not rotated collision shape 
(Please note that scalling the bodies still works).
The problem is when I try to rotate a StaticBody so I can create different directions for each object,
the normal isn't affected by the body rotation, so the normal is exactly the same as the original object.

![Issue](https://user-images.githubusercontent.com/43936806/77131039-e6bbc680-6a38-11ea-83bc-ed4974894d30.png)

**Steps to reproduce:**
1.Create a moveable KinematicBody scene with a floor normal detection with Raycast;
2.Create a StaticBody scene with some collision;
3.Instantiate in a main scene the KinematicBody scene and the StaticBody scene;
4.Create a copy of the StaticBody scene with some rotation;
5.Run the main scene, move to above the two StaticBody objects and view the normal.

**Minimal reproduction project:** If it's really necessary, I will upload a one

**Comment by aaronfranke** [comment]
As a workaround, couldn't you just use `xform` or `xform_inv`?

**Comment by ghsoares** [comment]
@aaronfranke Thank you for you response, could you explain how to use this function?

**Comment by ghsoares** [comment]
I'm closing, because after a better look, the normal is affected by the object rotation, the problem is the method i'm using to rotate with the floor normal, so excuse me for opening a wrong issue

**Comment by ghsoares** [comment]
If anyone are having same issue on floor rotation, there's a link with a useful function implementation:
https://www.reddit.com/r/godot/comments/a8q93e/orient_node_to_normal_of_ground/
