### ISSUE TITLE
Engine freeze if using 'for' loop in canvas item shader

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#37189]
**Godot version:**
cce0a27ec7dd7c11fcb37eb724b0b7e97b3b1478

**OS/device including version:**
Win10/GTX1060

**Issue description:**
The following shader sentence make engine freeze in endless loop of errors:

```
      shader_type canvas_item;

       void fragment() 
       {
          for(int i; i < 1; i++)
	  {
	  }
       }
```
Interestingly that this sentence proceeds correctly:
```
        for(int i = 0; i < 1; i++)
	{
	}	
```	

**Steps to reproduce:**
Create a ShaderMaterial, assign it to `ColorRect`, and push the shader code with that sentence to it.

The error you observe is probably:

>               Object[0] - VK_OBJECT_TYPE_SWAPCHAIN_KHR, Handle 2420212087392
>    at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:137)
> ERROR: Condition "err" is true. returned: ERR_CANT_CREATE
>    at: VulkanContext::prepare_buffers (drivers\vulkan\vulkan_context.cpp:1240)
> ERROR: Condition "err" is true. returned: ERR_CANT_CREATE
>    at: VulkanContext::swap_buffers (drivers\vulkan\vulkan_context.cpp:1304)
> ERROR: VALIDATION - Message Id Number: 3 | Message Id Name: NVIDIA
>         vkAcquireNextImageKHR: An attempt was made to acquire an image when the maximum number of images are already acquired.

**Minimal reproduction project:**
[ForFreeze.zip](https://github.com/godotengine/godot/files/4360416/ForFreeze.zip)

**Comment by giarve** [comment]
It seems to be working at ed9a0d0484

on debian using intel integrated graphics, no errors, could play a webm video next to the ColorRect without delay.

**Comment by Chaosus** [comment]
Seems fixed currently.
