### ISSUE TITLE
separate Godot modules, so it will be possible to integrate them into server with custom netcode and main loop 

### ISSUE THREAD

**Issue by blockspacer** [godotengine/godot#37182]
Hi,

It is not possible now to use Godot with custom server (server requires custom netcode and main loop), Godot modules are tightly coupled and require Godot engine to be running.

Problem 1:
It may be useful to separate physics module (at least) from main engine, so people will be able to run custom server with physics module from Godot.

Problem 2:
Godot uses scons. 
Please read possible solution at https://github.com/godotengine/godot/issues/37180
NOTE: Godot can keep existing SCons build system and add conan integration with minimal changes

**Comment by akien-mga** [comment]
>  It may be useful to separate physics module (at least) from main engine, so people will be able to run custom server with physics module from Godot.

That's not possible, Godot modules are made *for* Godot, they can't be used without Godot.
You can't just compile `modules/bullet` without Godot, it relies on code in `core`, `scene` and `server` (i.e., it relies on Godot...).

>  Godot uses scons.

I fail to see how that's a problem.
