### ISSUE TITLE
Input actions mapped to joystick axes don't work with is_action_pressed

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#3718]
You can get those through InputEvents in the input callback, but `Input.is_action_pressed()` doesn't work with joystick axes.

**Comment by GalanCM** [comment]
Assuming this commit made it into the 2.0.2 branch, it seems to only work in the editor. Once a game is exported (on Linux at least, I haven't had time to test other platforms), it seems to no longer work.

**Comment by akien-mga** [comment]
> Assuming this commit made it into the 2.0.2 branch

It's in 2.0.2 as it was commited and merged before the 2.0 release and thus before the branching.
