### ISSUE TITLE
Native classes with internally '_' prefixed cause class naming error and autocomplete error

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#37184]
**Godot version:** 3.2.1

**OS/device including version:** Any

**Issue description:**
1. can't name a class as `_File`. false error
2. auto completing mode arg of `File.open()` suggest `_File.*`

**Steps to reproduce:**
![native-class-with-underscore-bug](https://user-images.githubusercontent.com/41085900/77158969-6776d300-6aca-11ea-912e-51a61b8a0988.JPG)

**Minimal reproduction project:**
N/A

**Comment by Xrayez** [comment]
There's a solution underway: #26990.

**Comment by Janglee123** [comment]
Duplicate of #35469

**Comment by madmiraal** [comment]
Closing as duplicate of #35469.
