### ISSUE TITLE
Enet client does not disconnect even android background apps is removed

### ISSUE THREAD

**Issue by nightrobin** [godotengine/godot#37186]
**Godot version:**
3.2.1-stable

**OS/device including version:**
Workstation: Ubuntu 18.04 LTS x64
Testing Device: Android 9 - Xiaomi Redmi 6

**Issue description:**
Enet client does not disconnect to server quickly even android background app is removed.
It took 23 seconds after the force closing of the app for the server to tell that the client is disconnected.

The only things to make it disconnected instantly is for me to:

- Uninstall the app in android
- Turn off the wifi in android

**Steps to reproduce:**
1. Run the app in the desktop that will act as the server.
2. Run the app in the android that will act as the client.
3. Close the android app. Then check the desktop for prints regarding the client disconnection.
4. Force close the android app.
5. Still check the desktop for prints.
6. Then after sometime the desktop will print that the client is disconnected.

**Minimal reproduction project:**
[Enet.zip](https://github.com/godotengine/godot/files/4359941/Enet.zip)

**Comment by jonbonazza** [comment]
I wouldn't call this a bug. In the even if a crash or other unexpected exit where a client can't explicitly disconnect from the server, the best you can do is rely on a heartbeat timeout. IIRC this is currently set to 30s. You can't make this timeout too small or you risk disconnecting prematurely during actual gameplay under poor network conditions.

**Comment by Faless** [comment]
Yeah, not much we can do about this. Closing.
