### ISSUE TITLE
conan support (make all happy with scons, inluding CMake users)

### ISSUE THREAD

**Issue by blockspacer** [godotengine/godot#37180]
conan is awesome C++ Open Source Package Manager https://conan.io/

it can be used with scons, makefiles, pre-built binaries, CMake like so https://jfreeman.dev/blog/2019/05/22/trying-conan-with-modern-cmake:-dependencies/

If Godot used conan + scons, then it would be easier to integrate Godot modules with apps (**especially important if you want to create server with custom netcode and main loop, but integrate some Godot modules, like physics**).

scons is not popular and it is big downside of Godot. **conan can solve a lot of problems** (just make sure that Godot module used conan+scons and can be imported into cmake+conan based project)

Related to
https://github.com/godotengine/godot/issues/9694
https://github.com/godotengine/godot/issues/81
https://github.com/godotengine/godot/issues/8983

**Comment by akien-mga** [comment]
Please open a formal proposal on https://github.com/godotengine/godot-proposals following the template.

"scons is not popular" is not an argument for any change, it works well for our contributors and that's what matters.

**Comment by blockspacer** [comment]
@akien-mga 

> it works well for our contributors

it don't work well for contributors - it stops people from creating integration with Godot modules, especially important if you want to create server with custom netcode and main loop, but integrate some Godot modules, like physics).

**NOTE: Godot can keep existing SCons build system and add conan integration with minimal changes**

Please, reopen the issue

**Comment by akien-mga** [comment]
As I said, this should go through the proposals repository. This issue tracker is for bug reports.

**Comment by blockspacer** [comment]
moved to https://github.com/godotengine/godot-proposals/issues/606
