### ISSUE TITLE
Invalid operands error located on wrong line in if/elif statement

### ISSUE THREAD

**Issue by FabianoFabiouchi** [godotengine/godot#37197]
**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
Windows 10/Acer Swift SF315/41

**Issue description:**
I tried to access the position of an instanced Node2D in an if elif statement for comparison with an '<' operator. In the elif condition I accidently compared the position vector to the number and the error message led me to the wrong line, took me half an hour realizing it :p.

**Steps to reproduce:**
Create a Scene with a Node2D as Root
Create another Scene with this script attached:
`var scene = load("res://scene.tscn")

func _init():
	add_child(scene.instance())
	var child= get_children()[0]
	
	# error message leads to the line below
	if child.position.x > 42:
		pass
	# error down here
	elif child.position > 42:
		pass`

**Comment by Calinou** [comment]
> I tried to access the position of an instanced Node2D in an if elif statement for comparison with an '<' operator. In the elif condition I accidently compared the position vector to the number and the error message led me to the wrong line, took me half an hour realizing it :p.

While this is still a bug, I strongly advise always looking at the line above and the line below when you get an error trace. This will greatly ease your debugging sessions :wink:

**Comment by FabianoFabiouchi** [comment]
Had my lesson, thank you :D
