### ISSUE TITLE
Tooltips show off-screen

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#37191]
**Godot version:**
v3.2.1
**Issue description:**
Tooltips show off-screen when they are near the edge of the screen.
![image](https://user-images.githubusercontent.com/28286961/77185198-4d8cbe80-6ad1-11ea-9d02-23383187082c.png)
**Steps to reproduce:**
Go to the inspector and hover over the pause mode property.

**Comment by CrackedP0t** [comment]
This no longer occurs in 4.0
