### ISSUE TITLE
OS.get_locale in Windows does not match sublang

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#37203]
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**

OS.get_locale() does not return full locale
Ex: 'zh_TW' or 'zh_CN' will return 'zh' only

```
String OS_Windows::get_locale() const {

	const _WinLocale *wl = &_win_locales[0];

	LANGID langid = GetUserDefaultUILanguage();
	String neutral;
	int lang = langid & ((1 << 9) - 1);
	int sublang = langid & ~((1 << 9) - 1);

	while (wl->locale) {

		if (wl->main_lang == lang && wl->sublang == SUBLANG_NEUTRAL)
			neutral = wl->locale;

		if (lang == wl->main_lang && sublang == wl->sublang)
			return wl->locale;

		wl++;
	}

	if (neutral != "")
		return neutral;

	return "en";
}
```

may be change to ` int sublang = langid >> 10; `  will work.

**Comment by Calinou** [comment]
This seems to be Windows-specific, as I get `en_US` on Linux (with my system configured in English).

**Comment by denormative** [comment]
Looks like this is OS-specific. I get "en-AU" on OSX (correct), "en_US" on linux (correct), and "en" on windows (only half correct).
