### ISSUE TITLE
Default HTML-5 export option forces scaling to fit viewport, even for non-resizable games

### ISSUE THREAD

**Issue by madprogramer** [godotengine/godot#37205]
**Godot version:**
3.2
**OS/device including version:**
MacOS
**Issue description:**
Default HTML-5 export option forces scaling to fit viewport, even for non-resizable games
**Steps to reproduce:**
Use HTML-5 export for any project, compare the visible screen in Godot with the HTML-5 version when running.
**Minimal reproduction project:**
Any project with a pre-specified window width/height, smaller than the viewport it'll be run in.

### Quick-Fix:

Open up the Project.html of your export in a text-editor.
Scroll down to the line 
```js
function adjustCanvasDimensions() {
```
change the function from

```js
function adjustCanvasDimensions() {
	var scale = window.devicePixelRatio || 1;
	var width = window.innerWidth;
	var height = window.innerHeight;
	canvas.width = width * scale;
	canvas.height = height * scale;
	canvas.style.width = width + "px";
	canvas.style.height = height + "px";
	}
```

to

```js
function adjustCanvasDimensions() {
	canvas.width = innerWidth;
	canvas.height = innerHeight;
        }
```

**Comment by Calinou** [comment]
If you want the project to display at a fixed size, you can use the fixed size HTML template.

1. Save [this HTML template](https://raw.githubusercontent.com/godotengine/godot/3.2.1-stable/misc/dist/html/fixed-size.html) as a file.
2. In your HTML5 export preset, specify a custom HTML template and point to the file you saved.
3. Export your project.

**Comment by hazarek** [comment]
> If you want the project to display at a fixed size, you can use the fixed size HTML template.
> 
> 1. Save [this HTML template](https://raw.githubusercontent.com/godotengine/godot/3.2.1-stable/misc/dist/html/fixed-size.html) as a file.
> 2. In the editor, open the Export dialog, select your HTML5 export preset, specify a custom HTML template and point to the file you saved.
> 3. Export your project.
> 
> That said, I would advise making your game window resizable so it handles [multiple aspect ratios and hiDPI](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) 🙂

impossible to make fixed size from project settings. settings do not behave as expected.

<img width="714" alt="cap 3" src="https://user-images.githubusercontent.com/36481442/92298876-195d6b00-ef56-11ea-80e8-52882317ceed.png">


Also There is a output window under the canvas in your fixed-size.html.

<img width="835" alt="cap 2" src="https://user-images.githubusercontent.com/36481442/92298839-b9ff5b00-ef55-11ea-88a6-a4912f3e6abe.png">
