### ISSUE TITLE
AnimationPlayer.set_speed() does not set the relative speed of the animation

### ISSUE THREAD

**Issue by gitnob** [godotengine/godot#3721]
Tried this code in an animation on Debian Jessie, 2.0, RC1
```
extends AnimationPlayer
var bMoving=true
var speed=5.0

func _ready():
	set_speed(speed)
	print(get_speed())

```
result was 1.0 instead of expected 5.0.
Seems as if the method does not change the relative speed.

**Comment by Hinsbart** [comment]
This prints "5" for me (current master).
The code for these functions: 
```
void AnimationPlayer::set_speed(float p_speed) {
	speed_scale=p_speed;
}

float AnimationPlayer::get_speed() const {
	return speed_scale;
}
```
I can't see any problem there ^^ 
Could you upload an example project where it fails? Maybe the issue is something else

**Comment by gitnob** [comment]
After investigating in my code again, I found a bug in MY code. Shame on me.
No issues anymore. Thx Hinsbart.
Closing now.
