### ISSUE TITLE
Button's set_pressed() does not work anymore

### ISSUE THREAD

**Issue by j5E01** [godotengine/godot#37213]
**Godot version:** Godot_v3.2.1-stable_win64

**OS/device including version:** Windows 10: fully updated

**Issue description:** set_pressed() using textureButtons with toggled property enabled does not work anymore, ever since 3.2 came out. 

**Steps to reproduce:** have a script try to set_pressed(false) a button that is currently toggled true.

**Minimal reproduction project:**
Create multiple toggle-enabled buttons in a group. Create a script that checks all buttons in the group and set_pressed(false) all buttons except the one currently clicked. Essentialy make only 1 button able to be toggled at any given time.

**Comment by jluini** [comment]
And what happens when you do so? Do you get an error or what?
Did you remember to set 'toggle_mode' to true? I think 'pressed' can't be set in buttons if toggle_mode=false.

**Comment by j5E01** [comment]
Sorry, all of a sudden I can't reproduce the issue. 
Closed for now.
