### ISSUE TITLE
Godot 3.2.1-stable-osx Has Incorrect Version String (Reads 3.2, Not 3.2.1)

### ISSUE THREAD

**Issue by name-here** [godotengine/godot#37229]
**Godot version:**
Godot_v3.2.1-stable_osx.64
**OS/device including version:**
Any mac
**Issue description:**
When viewing the Godot app info in MacOS, it says the version is 3.2 instead of 3.2.1  For other versions (I checked 3.1.2 and 3.1), it displays the correct version.  The version number is stored in Godot.app/Contents/Info.plist under the keys "CFBundleShortVersionString" and "CFBundleVersion", and changing these  manually does indeed fix the bug.  I don't know how Godot's build system works for making Mac apps, but since the version number displayed on the "About Godot" screen are correct, I guess the version number for the Mac app must be stored elsewhere in the code, and wasn't updated with 3.2.1
**Steps to reproduce:**
Press CMD+I  or SPACE on the app to get info, and look at the version number displayed.  Alternatively, look at the version number stored in the plist file in the app contents.  Both are incorrect.
**Minimal reproduction project:**
Download the zip from the official website ([here](https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_osx.64.zip)).

**Comment by akien-mga** [comment]
Fixed for 3.2.2 with da4eb7101d.

**Comment by name-here** [comment]
So the application available on the website will remain broken until the 3.2.2 release?  Would be difficult to make the 2-line fix in the one available on the website?  Or would that cause confusion with version separation or something.

**Comment by akien-mga** [comment]
There's nothing "broken" in macOS reporting it being version 3.2 in the metadata. It's also accurate, it's the 3.2 stable branch.

**Comment by Calinou** [comment]
It's also considered bad practice to silently update a version, as that breaks checksums for people who rely on it (e.g. for unattended installs) :slightly_smiling_face:

**Comment by name-here** [comment]
Okay.  That makes sense.
