### ISSUE TITLE
OS.shell_open() is calling the input function twice

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#37221]
**Godot version:** v3.2.1.stable

**OS/device including version:**
Intel Core i7-4790K CPU
16GB ram
Windows 8.1 64bit

Related: #4353
It's probably a windows only bug like that one.

```
func _input(event):
	if Input.is_action_just_pressed("ui_accept"):
		print("Hello")
		OS.shell_open("C:\\")
```
Hello text appears twice.
[OS_shell_open_bug.zip](https://github.com/godotengine/godot/files/4364743/OS_shell_open_bug.zip)

Putting ``yield(get_tree(),'idle_frame')`` before the ``OS.shell_open`` line fixes it.

**Comment by Calinou** [comment]
Does this happen if you trigger the input event using another key (such as <kbd>T</kbd> or a mouse button)?

**Comment by rainlizard** [comment]
Yes all buttons are affected. Though I'm now getting a little inconsistency with the amount of "Hello" text it's printing at one time, it seems to always be between 1-3 times.

**Comment by nisovin** [comment]
You should probably use `event.is_action_pressed("ui_accept")` instead. If you get more than one (unrelated) input event in a single frame, `is_action_just_pressed` will return true each time.

**Comment by rainlizard** [comment]
You're right, I was using the input event incorrectly, my bad.

It never looks cool reporting a bug when you're the one at fault, haha.
