### ISSUE TITLE
Graph node confusing slot indexing

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#37227]
**Godot version:** 3.2.1

**OS/device including version:** Windows 10

**Issue description:**
It's not actually bug, but some confusing slot indexing. Real slot and connection slot have different indexing. Real slot index it's node index inside GraphNode, but connection slot index start from 0 and considers only active slot (enabled connection)
![image](https://user-images.githubusercontent.com/1756388/77249678-7948a980-6c75-11ea-9b68-0dd5c7a8c283.png)

**Example 1:**
![image](https://user-images.githubusercontent.com/1756388/77249799-3935f680-6c76-11ea-8a5b-f0f4d186e6e9.png)
_Connection request from node 'Node0' from slot '0' to node 'Node1' to slot '0'_

**Example 2:**
![image](https://user-images.githubusercontent.com/1756388/77249832-5b2f7900-6c76-11ea-94a6-17c4d6863862.png)
_Connection request from node 'Node1' from slot '0' to node 'Node0' to slot '1'_

**Comment by pycbouh** [comment]
I guess the fact that "slots" are referred as "ports" in some cases is related to this. It would make sense, that a "slot" is an inner concept for a `GraphNode` and a "port" is an external representation for active slot, as perceived by `GraphEdit`. But there is no way to convert one to the other. And it is still not consistent, as `connection_request` signal calls them "slots", while `connect_node` method calls them "ports".
```
connection_request ( String from, int from_slot, String to, int to_slot )
```
```
connect_node ( String from, int from_port, String to, int to_port )
```

**Comment by TomNCatz** [comment]
Personally I would always refer to the slot as the index for the node being referred to, not the number of slots active on that side. 

- Since it currently refers to the number of slots that are enabled for connection, enabling a slot changes the index of all the slots below it.
- Since there is no built in way to retrieve the node that a slot refers to, you are currently can't do anything with the slot number

Right now I am getting around this by turning all slots on, but coloring them as transparent and setting their type numbers to -1 on the left and -2 on the right so they can't be connected to anything. This is SUPER hacky, but it makes the nodes function as expected.

**Comment by DarkMessiah** [comment]
> Right now I am getting around this by turning all slots on, but coloring them as transparent and setting their type numbers to -1 on the left and -2 on the right so they can't be connected to anything. This is SUPER hacky, but it makes the nodes function as expected.

Nice hack :D

>Since there is no built in way to retrieve the node that a slot refers to, you are currently can't do anything with the slot number

I tried replace `vector<ConnCache>` to `map<int, ConnCache>` to store slot index like key. This worked as expected for my code, but broke visual scripting logic and I think visual shader too. Easy way it's add new property `int slot` to `struct ConnCache` and methods to get slot index by port index.

**Comment by mrushyendra** [comment]
To summarize, would the following changes suffice?

1. Add a function to `GraphNode` to get the slot index from the port/connection index
2. Modify `GraphEdit` class documentation to clarify difference between ports and slots, and change any ambiguous method/signal argument names

This would be the least disruptive and non-compatibility breaking change. If that sounds good, I can make a PR soon

**Comment by TomNCatz** [comment]
I would feel that solves the problem.
