### ISSUE TITLE
Joystick is not recognized; "add_joy_mapping" and "SDL_GAMECONTROLLERCONFIG" do not help

### ISSUE THREAD

**Issue by m6c7l** [godotengine/godot#37239]
**Godot version:**
3.2.1-stable

**OS/device including version:**
Linux 5.5.8-11 x86_64 GNU/Linux w/ GNOME 3.34.3 on x11

**Issue description:**
* "Joystick" is not recognized in Godot
* "Joystick" is working in Unity as well as several applications running on the same machine
* "Joystick" is recognized by tools like "controllermap", "gamepad-tool", "sdl2-jstest", and "sdl-jstest"

**Steps to reproduce:**
1) Create a new project,
2) add a mesh (or just a node) to the scene,
3) attach a GDScript to the mesh,
4) connect signal "joy_connection_changed" to a callback function with a debug message if something happens, and optionally, set the SDL2 mapping of "Joystick" with "add_joy_mapping" in "_ready()"
5) run the scene in Godot,
5) attach "Joystick" to the machine running the Godot scene,
6) no debug message from the callback function is showing up

**Further description:**
* The "Joystick" converts analog stick signals to USB emulating a joystick (with V-USB and some user code running on a AVR microcontroller). It is working very well in other applications on Windows and GNU/Linux.
* I set (and exported) the environment variable "SDL_GAMECONTROLLERCONFIG" with the corresponding SDL2 mapping, which is even used this way in several Unity applications.
* The SDL2 mapping looks like this:
`03000000c0160000dc05000001010000,v-usb-joy,leftx:a3,lefty:a2,rightx:a0,righty:a1,platform:Linux,`

**Comment by akien-mga** [comment]
Does it work on Windows?

`SDL_GAMECONTROLLERCONFIG` and `add_joy_mapping` do work to add new mappings or override existing ones in my experience, I actually made sure of that in 3.2 (#34908).

If you can, I'd suggest trying to build Godot from source and debug the `InputDefault::add_joy_mapping()` method in `main/input_default.cpp`.

**Comment by m6c7l** [comment]
Thank you for the quick response. I will check both, Windows and add_joy_mapping().

**Comment by Calinou** [comment]
If you're built Godot yourself on Linux, do note that it doesn't support controller hotplugging unless you build it with `udev=yes` on the SCons command line.

**Comment by m6c7l** [comment]
@Calinou: Thank you for the hint. Regarding this issue, I was using the official Godot release build 3.2.1-stable.

**Comment by m6c7l** [comment]
@akien-mga
> Does it work on Windows?

It works on Windows. The input event system of Godot is publishing events, i.e. "InputEventJoypadMotion" on all axes available from "Joystick".

**Comment by m6c7l** [comment]
The method `InputDefault::add_joy_mapping()` in `main/input_default.cpp`is fine.

The "Joystick" has lots of axes but no buttons, thus it can not become an input device from `JoypadLinux::open_joypad`'s point of view (in `platform/x11/joypad_linux.cpp`).

However, every other application on my machine including Unity recognize it as being a joystick, hence I guess the check condition in `JoypadLinux::open_joypad` is too restrictive. The pull request adds a relaxation to the check routine.
