### ISSUE TITLE
Buttons disappear on window resize due to font oversampling

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#37242]
**Godot version:**
3.2.1

**OS/device including version:**
macOS Catalina 10.15.3 / MacBookPro11,1

**Issue description:**
Buttons seem to disappear when the window is resized vertically.
Check the attached video.

[Godot-_Bug.mov.zip](https://github.com/godotengine/godot/files/4368333/Godot-_Bug.mov.zip)

**Steps to reproduce:**
Control Node -> Center Container -> Vertical Box Container -> Button_1, Button_2... 

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@drmar Please upload a minimal reproduction project to make this easier to troubleshoot.

Also, which stretch mode settings did you use in the project?

**Comment by drmar** [comment]
> Also, which stretch mode settings did you use in the project?

Stretch Mode: 2d
Stretch Aspect: keep

> Please upload a minimal reproduction project to make this easier to troubleshoot.

I will do this shortly.

**Comment by drmar** [comment]
Minimal reproduction project:

[Godot Bug.zip](https://github.com/godotengine/godot/files/4368551/Godot.Bug.zip)

**Comment by Janglee123** [comment]
I can reproduce this on Godot 3.2.

**Comment by Calinou** [comment]
I can reproduce this on Godot 3.2 on Linux. It happens whenever you resize the window width or height to be 1 pixel wide.

You can work around this by defining a minimum window size in any script:

```gdscript
func _ready():
	OS.min_window_size = Vector2(64, 64)
```

**Comment by drmar** [comment]
I actually don't think that the bug happens necessarily when the window is 1px by itself.
I believe something else has to happen for the bug to appear.
I will do more testing tomorrow.

**Comment by Calinou** [comment]
This doesn't occur if you set the stretch mode to `disabled` or `viewport`. It only occurs when setting the stretch mode to `2d` with font oversampling enabled. If you disable **Rendering > Quality > Dynamic Fonts > Use Oversampling** in the project settings, it won't occur when using the `2d` stretch mode.

So it's yet another bug related to font oversampling.

**Comment by Janglee123** [comment]
The size and position of the button node increase unacceptably, and it gets out of the window. This only happens to buttons. 

[Here](https://github.com/godotengine/godot/files/4373580/Godot.Bug.zip) is the demo. Resize the window to the smallest size and restore it, and You can see the size of the play button increases.

**Comment by drmar** [comment]
> This means it's yet another bug related to font oversampling.

I also believe that it has something to do with custom fonts. It you recreate my minimal project that I uploaded initially without custom fonts, the buttons will NOT disappear, even when the window is resized to 1px.

**Comment by Calinou** [comment]
@drmar The default font is a BitmapFont. BitmapFonts don't make use of font oversampling, which is why this bug doesn't occur with BitmapFonts.

**Comment by drmar** [comment]
@Calinou Thanks for the info!
