### ISSUE TITLE
Nonexistent function 'is_cell_transposed' in base 'TileMap'

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#3724]
I wan't to get the rotation off tile in tilemap and got this error message.
_Invalid call. Nonexistent function 'is_cell_transposed' in base 'TileMap'._

Function seams available but not in editor help and code completion.
![image](https://cloud.githubusercontent.com/assets/10463138/13061283/552dedd8-d437-11e5-8d51-7c95f8628354.png)

Godot Version: Godot_v2.0_rc1_20160209_win64.exe
System: Windows 7 64bit

**Comment by akien-mga** [comment]
Thanks for the report, the two other is_cell_x_flipped and is_cell_y_flipped methods are bound, so there is no reason not to bind this one too, I'll do it.
