### ISSUE TITLE
RigidBody2D ignore transformation on runtime

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#37244]
**Godot version:** 3.2.1

**OS/device including version:** Any

**Issue description:**
there was already an issue and documentations about that the scale property of RigidBody2D wont work ( Issue: #5734 ) but it's not just ignoring the scale only, the whole transformation (position, scale, angle) which is overridden by the physics engine.

I was trying to set the rigid body a constant position but when running the game in debug mode with visible collision shape, the body just move and collide but the shape still at the position.
![rigid-body-bug](https://user-images.githubusercontent.com/41085900/77304322-47d5e980-6d1a-11ea-8848-3d86510685a3.gif)

**Steps to reproduce:**
create a rigid body and a static body
add them collision shapes 
place in a way that the rigid body intend to collide
set the rigid body position a constant value in _process
set collision shape visible in debug menu.
run the game

**Minimal reproduction project:**
N/A

**Comment by nisovin** [comment]
You aren't supposed to set a RigidBody's position every frame, the documentation is clear about this. You're effectively fighting with the physics engine, which is meant to control the RigidBody. If you want to hold it at one place, switch it to kinematic or static.

**Comment by Anutrix** [comment]
>  set the rigid body position a constant value in _process
This can be closed I think as above is not allowed.

**Comment by Calinou** [comment]
Indeed, this is a limitation inherent to RigidBody which can't be solved. I wonder if we could detect the translation/rotation being set every frame and print an error message in this case.

**Comment by Anutrix** [comment]
> 
> 
> Indeed, this is a limitation inherent to RigidBody which can't be solved. Still, I wonder if we could detect the translation/rotation being manually set every frame and print a warning message in this case.

Maybe when can override RigidBody's transformation's set methods to display a warning whenever it is being used in a script.
