### ISSUE TITLE
Cursor doesn't follow pen movement when using a pen tablet.

### ISSUE THREAD

**Issue by indubitablement2** [godotengine/godot#37251]
**Godot version:**
Godot 3.2.1 stable win64

**OS/device including version:**
Windows 10, Huion 420 pen tablet
Tried with and without driver.

**Issue description:**
Cursor doesn't follow my pen movement.

**Steps to reproduce:**
Use a pen tablet (only tested with Huion 420).
Try to move the pen or Ctrl+click a links in code.
The cursor only move when I input left/right/middle click.
![Lx58rx3Qd1](https://user-images.githubusercontent.com/62550921/77323386-8c965c00-6ceb-11ea-887a-395dd1608f05.gif)

**Expected behaviors:**
The cursor should follow my pen movement like it used to in version 3.1.
![iLXSiHy1Oy](https://user-images.githubusercontent.com/62550921/77323858-4988b880-6cec-11ea-835e-0be3c9df7a8e.gif)

**Minimal reproduction project:**
Can easily be seen with this code. There is my pen position (where the cursor should be) followed by the godot icon and there is the cursor that only move when I click. If the cursor is inside a Godot windows, clicking shift, ctrl or alt flicker between the two.
```
func _process(delta):
    $icon.set_position(get_local_mouse_position())
```
https://www.youtube.com/watch?v=VxH5SWYbQLU

**Comment by Calinou** [comment]
Related to #36319?

**Comment by indubitablement2** [comment]
#36319 seem to be about presure and tilt which I haven't tested yet. For me, the cursor isn't following the pen unless I click somewhere.

Just tested version 3.1 and everything work as it should. You can see my cursor moving unlike version 3.2 where my cursor doesn't move unless I click somewhere.
![uwxOM6u0Uu](https://user-images.githubusercontent.com/62550921/77326895-da619300-6cf0-11ea-952a-72c0814bd478.gif)

**Comment by Anutrix** [comment]
It works in 3.1 but not 3.2 so it's a regression bug.

**Comment by TheFlamyy** [comment]
I can't reproduce it with my Wacom Intuos PT S on v3.2.1

**Comment by SleepProgger** [comment]
Heads up:  Works on Manjaro with the same tablet/pen on 3.2.1-stable

**Comment by indubitablement2** [comment]
I fixed my issue by running my tablet driver as administrator.
