### ISSUE TITLE
Lines using `assert` are never marked as safe

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#37258]
Godot 3.2.1

I noticed that even though all GDScript type hints are present, when I use `assert`, the line is never marked as safe.

Example:
```gdscript
static func test(x: int):
	assert(x == 1)
```

**Comment by BigRed-118** [comment]
@Zylann The assert lines were marked safe after that change. If I missed the mark (Marc) on this one just let me know. Thanks.

**Comment by TheDuriel** [comment]
asserts can contain unsafe code... which is to say _any_ code which is not an evaluation of truth hood. Else you end up with your application crashing/working incorrectly because the assert does not run. I keep running into people doing this.

**Comment by BigRed-118** [comment]
@TheDuriel That's a good point. The changes in the pull request for this issue should work in the same way an if statement is handled to determine if it's safe or not. If you want, check out #37265 and let me know if you have an issues.
