### ISSUE TITLE
I am unable to use GDscript because of an error in gdscript_tokenizer.cpp

### ISSUE THREAD

**Issue by Large-Lad** [godotengine/godot#37267]
**Godot version:**
Version 3.2.1
**OS/device including version:**
Linux Ubuntu 18.04
**Issue description:**
I am unable to use GDscript. The only things that do not return an error are comments, setting variables, and making functions. I can write code in a function with no error. Everything else I type returns this error:
 modules/gdscript/gdscript_tokenizer.cpp:1129 - Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()

This error happens everywhere. Editing a project  or even starting a new one. 

 
**Steps to reproduce:**
I have no idea how this happened. I simply loaded up one of my projects and then I could no longer use GDscript.

**Comment by aaronfranke** [comment]
Please provide a minimal reproduction project.

**Comment by Large-Lad** [comment]
Sure thing. 
[godottokenizerbug.zip](https://github.com/godotengine/godot/files/4373474/godottokenizerbug.zip)

**Comment by aaronfranke** [comment]
You can't write print statements outside of functions. This is intended behavior.

**Comment by Calinou** [comment]
We should probably add an error explanation or a dedicated GDScript error case so we get a better error message when someone tries to call methods in the top-level.
