### ISSUE TITLE
Metaballs (alpha threshold)

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#3726]
Someone in the IRC channel linked this page: https://www.scirra.com/forum/viewtopic.php?t=74372&start=0. Don't know how difficult to implement it would be, but seems like a very very nice addition to have around for the particles especially. Consider this as an enhancement please? :)

**Comment by bojidar-bg** [comment]
Probably doable with canvas item shaders (though gaussian blur and the like are going to be harder).

**Comment by kubecz3k** [comment]
@razvanc-r can you link to some video on what this was? There is no video currently under the link from first post... (video link is broken). It's hard to tell what this issue is about without this...

**Comment by razvanc-r** [comment]
Yah, unfortunately the vid is gone, luckily there's a bunch of material out there, most notably, blender has them: https://youtu.be/E8YeCtvQufw?t=58. Here's another link for 2d stuff: https://www.scirra.com/tutorials/813/how-to-make-fluids

**Comment by razcore-art** [comment]
After playing a bit with some shader code and ideas I think that it doesn't make sense to have as a game object/node because it's an effect which can be achieved through shader material both in 2D and 3D so I'll mark this as closed for now.
