### ISSUE TITLE
when use scons to build godot on windows got a error(mingw)

### ISSUE THREAD

**Issue by 2439905184** [godotengine/godot#37270]
**Godot version:*3.2*

**OS/device including version:*window764*

**Issue description:*b'cc1plus.exe: error: unrecognized command line option "-Werror=return-type"\r\n
cc1plus.exe: error: unrecognized command line option "-std=c++11"\r\n'
=====
scons: *** [platform\windows\godot_windows.windows.tools.64.o] Error 1
scons: building terminated because of errors.
*

**Steps to reproduce:*i use mingw and add it to path ,can use gcc command 
than I follow the doc ,run scons got this problem,
So is my scons version not correct? 
*

**Minimal reproduction project:**
![scons](https://user-images.githubusercontent.com/29478722/77394559-a6629c80-6dda-11ea-92e1-e4b1e94bb043.png)
![QQ截图20200324142626](https://user-images.githubusercontent.com/29478722/77394941-77005f80-6ddb-11ea-913d-057ab54df67d.png)

**Comment by aaronfranke** [comment]
Does it work if you move Godot to a folder that doesn't have Chinese characters in the path?

**Comment by 2439905184** [comment]
I will try it

**Comment by 2439905184** [comment]
still get the problem
my path is E:\godot3.2

**Comment by 2439905184** [comment]
MinGW version 5.1.6

**Comment by Calinou** [comment]
@2439905184 Try downloading MinGW-w64 using [MSYS2](https://www.msys2.org/) instead of using the legacy MinGW32 (which is no longer maintained).

**Comment by akien-mga** [comment]
I suspect you have a very old GCC version, older than 4.8. You need at least GCC 6 to build Godot 3.2 from source.
