### ISSUE TITLE
Editor freezes after editing localization .csv and launching project

### ISSUE THREAD

**Issue by MennoMax** [godotengine/godot#37282]
**Godot version:**
v3.2.stable.official

**OS/device including version:**
Linux Mint 19.3 Cinnamon 4.4.8

**Issue description:**
Upon launching a project after changing a .csv file used to translate strings within the project, the editor freezes. It doesn't seem to ever start responding again, only closing and restarting the editor fixes this.

Since this might be relevant; I am using LibreOffice Calc to edit the .csv file.

**Steps to reproduce:**
In a project that uses localization;
1. Open the .csv file
2. Edit any translation and save the file
3. Launch the project

The editor will no longer respond.

**Minimal reproduction project:**
[IssueTest.zip](https://github.com/godotengine/godot/files/4378112/IssueTest.zip)

**Comment by tom-jk** [comment]
Can't reproduce in 3.2.2.stable on linux mint 18.3. Tried editing with godot open and closed, changing text, adding and removing locales etc. Godot editor and game run fine.

@MennoMax can you still reproduce this?

(ps. LibreOffice Calc csv output is identical to text-edited .csv afaics)

**Comment by Calinou** [comment]
Can you check the file encoding of the CSV file? You can use the `file` command to do this: `file /path/to/file.csv`.

The CSV file should be encoded in UTF-8 *without BOM*, as stated in the documentation.

**Comment by MennoMax** [comment]
I am no longer able to reproduce this issue, seems to be fixed.

**Comment by MennoMax** [comment]
This issue was definitely present in 3.2, but something must've fixed it by now.
