### ISSUE TITLE
[Mono] Some Methods and Property Don't get Translated to PascalCase

### ISSUE THREAD

**Issue by NutmegStudio** [godotengine/godot#37284]
**Godot version:**
e9ecb06cf
**OS/device including version:**
Linux Mint 19.3
**Issue description:**
It seems that when calling built in property or methods using quots `" "`, godot only recognises `snake_case` and not `PascalCase`. I've only tested this with `InterpolateProperty` and `InterpolateMethod` not sure if it affect other methods such as `Call`.
This Doesn't happen in godot 3.2.1.
**Steps to reproduce:**
Would give an `ERROR: Tween target object has no property named: RotationDegrees.`
```C#
tween.InterpolateProperty(this, "RotationDegrees", origRot, new Vector3(90, 90, 90), 2f, Tween.TransitionType.Linear, Tween.EaseType.InOut, 0f);
```
Works
```C#
tween.InterpolateProperty(this, "rotation_degrees", origRot, new Vector3(90, 90, 90), 2f, Tween.TransitionType.Linear, Tween.EaseType.InOut, 0f);
```
**Minimal reproduction project:**
[monobug.zip](https://github.com/godotengine/godot/files/4378188/monobug.zip)

**Comment by neikeq** [comment]
Closing as duplicated of #16872
