### ISSUE TITLE
Doc viewer selection works only on upper half

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3731]
I have problems selecting doc text in the godot doc viewer. I can select the upper half but not the lower. I have to scroll down first to select the lower half.

**Comment by akien-mga** [comment]
I believe this might have been fixed by #5023, can someone confirm?

**Comment by AlexHolly** [comment]
Looks a bit buggy.(Start selecting from "Public Methods:" to the last word "The" at the bottom)

![screenshot - 15 07 2016 - 14 46 13](https://cloud.githubusercontent.com/assets/4741886/16874871/37ef9d94-4a9c-11e6-8f7e-32ce7c70e782.png)

**Comment by reduz** [comment]
Yeah, you have to use the scroll wheel to selcet more stuff.. if anyone wants to improve it, it's welcome

**Comment by akien-mga** [comment]
I'm pretty sure this has been fixed since July 2016.
