### ISSUE TITLE
Editor crash when creating Window node

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37329]
**Godot version:**
5f1107a

**OS/device including version:**
Windows 10

**Issue description:**
When you add a node of type Window, the editor will crash without backtrace.

**Comment by bruvzg** [comment]
Can't reproduce on macOS, adding `Window` node opens new window (deleting node closes it), and all of its children are displayed in this Window and are not interactive, that's probably is not a right way to handle it.

**Comment by ThakeeNathees** [comment]
for me (windows10) it just creates 33 windows nodes at the top left corner of the screen and then the editor become extremely slow.
I guess when a new window get focus it tries to handle the event which handled earlier by the last window, 

![window-node-bug](https://user-images.githubusercontent.com/41085900/77855743-0b215b00-7210-11ea-964a-35524b0bcf75.JPG)

**Comment by bruvzg** [comment]
> I guess when a new window get focus it tries to handle the event which handled earlier by the last window

I fixed similar behaviour on macOS in #37339 (event handler called for a second time from the `windowDidBecomeKey` event, causing multiple error prints when popup is opened), Window might have the same issue.
