### ISSUE TITLE
Permanent black rectangle

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37322]
**Godot version:**
5f1107a

**OS/device including version:**
Windows 10

**Steps to reproduce:**
1. Run any project
2.
![image](https://user-images.githubusercontent.com/2223172/77676588-cfc42980-6f8e-11ea-92d7-4de8dac33fe6.png)
This is likely a leftover from loading popup.

EDIT:
Here's a gif from another (duplicate) issue:
![image](https://user-images.githubusercontent.com/41085900/77822456-ef875900-7118-11ea-864c-99551f0c7eb1.gif)

**Comment by Anutrix** [comment]
It is from Saving Scene window.
