### ISSUE TITLE
Project Manager appears in the corner of the screen

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37323]
**Godot version:**
5f1107a

**OS/device including version:**
Windows 10

**Issue description:**
When you start Godot, the Project Manager appears in the top-left corner with title bar out of screen, so you can't move it. Resizing the window fixes it.

**Comment by Anutrix** [comment]
I am not sure of this but I think there's a bigger/broader issue here. Every Window's position is somehow dependent on its parent window.
Hence we get:
```
ERROR: Condition "!windows.has(p_window_id)" is true.
   at: window_destroy (drivers\vulkan\vulkan_context.cpp:754)
ERROR: Condition "!windows.has(p_window)" is true.
   at: window_resize (drivers\vulkan\vulkan_context.cpp:722)
```
often whenever we interact with windows.
