### ISSUE TITLE
github wiki VS godotengine.org wiki  = which one is main wiki? should you get rid of one?

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3732]
There are 2 wikis but which one is the main one? Which one has the freshest information and gets updated the most?

From what I understand the godotengine.org wiki was made later to give more editing access to  everyone because the github one only main devs have access to.

I prefer github one but  I can see how godotengine.org one would be more accessible to editors. should you get rid of github one? I would personally prefer the github one. Or if possible another github account could have the documentation. I am not sure. Or maybe even using a wiki site.

**Comment by akien-mga** [comment]
Actually the most recent one is a third wiki: http://docs.godotengine.org/ ;)

We'll soon get rid of both the GH and OpenProject wikis.

**Comment by trollworkout** [comment]
thanks @akien-mga  I will try and use that docs one . looks ugly but if that's what you guys use fine with me

**Comment by akien-mga** [comment]
> looks ugly but if that's what you guys use fine with me

Matter of taste I guess :-D

**Comment by nunodonato** [comment]
ugly? looks awesome! simple, fast and to the point. its a doc page, not a css demo playground :P

**Comment by 29jm** [comment]
@nunodonato Agreed, it's great

**Comment by trollworkout** [comment]
haha come on guys  i know this is not about looks. i personally find it ugly so what. is it functional? does it have the information i need? then is good. is not meant to be pretty but to be useful

**Comment by akien-mga** [comment]
For the reference, I've added a header to all GitHub wiki pages saying that they are deprecated. This will all get cleaned up in a couple of days, but we won't need this issue to remember about it, so closing.
