### ISSUE TITLE
Restoring minimized Project Manager makes it bigger

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37328]
**Godot version:**
5f1107a

**OS/device including version:**
Windows 10

**Issue description:**
Uh, I had this happen once and can't reproduce anymore because of #37327, but when you minimize Project Manager and restore it, the window is bigger and gets bigger with each repeat of this action. Might be related to DPI scaling.

**Comment by bruvzg** [comment]
Can't reproduce on macOS (5f1107aa30), probably `window_get_size` and `window_get_real_size` aren't used correctly somewhere in the Windows implementation.

**Comment by ThakeeNathees** [comment]
I can reproduce on windows with this fix: #37382

**Comment by reduz** [comment]
I can reproduce but I can't figure out what the problem is. Help appreciated.

**Comment by reduz** [comment]
wrong button

**Comment by hinlopen** [comment]
@reduz #39640 fixes it. Not sure if it is a good fix though.

**Comment by KoBeWi** [comment]
Looks fixed in 9b637fa
