### ISSUE TITLE
Sub-windows don't move smoothly

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37325]
**Godot version:**
5f1107a (release_debug)

**OS/device including version:**
Windows 10

**Issue description:**
When you open any sub-window (like Editor Settings), moving it is very choppy. Just compare it to e.g. file explorer or browser windows.

**Comment by ThakeeNathees** [comment]
also clicking a node in the scene tree takes some time to highlight the selected, like a .5 seconds but slower than the previous versions

**Comment by Calinou** [comment]
This is also noticeable when hovering options in a dropdown menu. It feels like highlighting updates at ~10 FPS where it was previously butter smooth (as long as you weren't using integrated graphics with a large resolution).

**Comment by reduz** [comment]
I can't reproduce this at all. Is it still a problem?

**Comment by KoBeWi** [comment]
Seems like it was fixed.
