### ISSUE TITLE
Window has empty limits section in the inspector

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37330]
**Godot version:**
5f1107a

**OS/device including version:**
Windows 10

**Issue description:**
![d4jdMtCln6](https://user-images.githubusercontent.com/2223172/77682057-98f21180-6f96-11ea-97a7-6b6a4f95f28c.gif)

**Comment by hinlopen** [comment]
I can't reproduce this issue on commit 1cd8e83 (latest) on Windows 10.

**Comment by KoBeWi** [comment]
Ok, the section is no longer empty.
