### ISSUE TITLE
Unicode letters absent from editor font

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37332]
**Godot version:**
5f1107a

**OS/device including version:**
Windows 10

**Issue description:**
Before
![image](https://user-images.githubusercontent.com/2223172/77682369-20d81b80-6f97-11ea-9460-bcab8f234bca.png)

Now
![image](https://user-images.githubusercontent.com/2223172/77682442-4107da80-6f97-11ea-8c2d-9a2a5d82a55d.png)

**Comment by bruvzg** [comment]
Editor theme font is not set correctly for any controls (as well as some other theme properties, editor scale for example), and default basic latin only bitmap font is used.
