### ISSUE TITLE
Godot opens popup like AcceptDialog even if project is not running

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#37334]
**Godot version:**
4.0.dev.custom_build.5f1107aa3

**OS/device including version:**
Ubuntu 19.10
**Issue description:**
When I open project, then 2/3 popups shows, which should be visible only when project is running.
![Zrzut ekranu z 2020-03-26 20-35-05](https://user-images.githubusercontent.com/41945903/77689350-cf815980-6fa1-11ea-9e89-ff9c1938605a.png)

**Minimal reproduction project:**
Just open project - https://github.com/qarmin/The-worst-Godot-test-project

**Comment by Anutrix** [comment]
I tried to open the test project in v4.0.alpha.custom_build [3fe3c4399] but it asked me to convert it(which I accepted). Even though I got a lot of errors the bug could not be reproduced.

@qarmin If this bug is producible, please upload 4.0 version MRP.

**Comment by qarmin** [comment]
Also cannot reproduce with latest version
