### ISSUE TITLE
Looped animation uses value from the beginning when it shouldn't

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37343]
**Godot version:**
3.2.1

**Steps to reproduce:**
1. Create an animation, e.g. for scale
2. Set length to 0.9 and snapping to 0.1
3. Add a key at the beginning and end
4. Enable looping
5. When you move cursor to the end of animation, it gets the initial value
![mCaKp9Loxu](https://user-images.githubusercontent.com/2223172/77706039-8fca6a00-6fc1-11ea-9ea7-e0a82682a081.gif)

It might be because of some rounding error, but it happens even if Loop Wrap Mode is set to Clamp. That's obviously a bug.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4390567/ReproductionProject.zip)

**Comment by dankan1890** [comment]
Reading the code, the problem is, as you thought, due to a conversion between double values (the Range control uses these to operate) and float (those that use Animations).
Personally I would change the values of the Animations to double, but before spending time, I would prefer to hear the opinion of some team member :)

**Comment by ThakeeNathees** [comment]
here the animation's loop property decide whether to interpolate or not when time is 0.9
if time is 0.9 and no loop -> don't interpolate
if time is 0.9 and has loop -> interpolate ( time becomes 0.0005 or something )

the tracks loop wrap/ loop clamp has nothing to do with it.
https://github.com/godotengine/godot/blob/307b1b3a5835ecdb477859785c673a07e248f904/scene/animation/animation_player.cpp#L818
to fix this issue this behavior need to changed 
```
Animation {
    loop_or_not
    track1 { loop_wrap_or_not }
    track2 { loop_wrap_or_not }
}
```
