### ISSUE TITLE
tween incompletion error

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#37346]
**Godot version:**
3.2 stable
**OS/device including version:**
Windows 10
**Issue description:**
when printing out a float variable it prints out as an integer but when using the (int) parser it parses to a different int than which I printed first

**Steps to reproduce:**
Just move the character around using arrow keys, I've got it printing out the coordinates of the tile in front of you (before it is wrapped around) as a float then again after I parsed it. I need to use these coordinates as an int in order to use them as indexes for an array as seen in my wrap_tile function in my level class. The value printed as a float is accurate but the value as an int isn't always. I can't use round to get the value I need because that returns a float. 

Possible explanations:
1. The tween isn't setting it to the exact value it should be upon completion and (int) could be performing a floor on a float that is barely less than 3. In which case it should print 2.99999999 or something. 
2. Something is seriously wrong with the int parser. 

**Minimal reproduction project:**
[int problem (2).zip](https://github.com/godotengine/godot/files/4658260/int.problem.2.zip)

**Comment by Anutrix** [comment]
Give an example set of numbers.

**Comment by Calinou** [comment]
Duplicate of #33095.

**Comment by Anutrix** [comment]
Isn't #33095 for large ints? Here the numbers are small.

**Comment by lukostello** [comment]
> Give some example code with expected output and the output you are getting.
> Make project bare minimum if you can.
> Running in it does show different values after int and floor.

This is the bare minimum project I took all the elements out of my game that weren't related to things causing the problem. I want the int values to be the same as what is printed for the float values but I need it as a int type so I can use it as an index for the array in the wrap_tile function in the level class.

**Comment by lukostello** [comment]
if I use the code
```
facing = get_parent().wrap_tile(int(round(translation.x + cos(rotation.y))), int(round(translation.z - sin(rotation.y))))
```
instead it works as expected. But..
1. This code looks ridiculus
2. Why should I trust round() any more than I should trust my tweens to get me where I asked it to take me. Tweens should arrive with at least the amount of accuracy the function round() provides. If I got to where I expected to be upon completion of the tween I wouldn't have to round and int() would return the expected value. So perhaps this is an issue with tween accuracy.

**Comment by pycbouh** [comment]
I know, it can be frustrating, but it's not exactly an error.

What happens is when you print a float, it operates on a limited number of significant digits after the dot. Your value is actually 2.99(9), but it cannot be displayed that way, it has to be limited by an arbitrary number of displayed digits. The conversion to string tries to find the closest value to yours within the given number of significant digits. Lets say, that we are only displaying 4 significant digits. In case of 2.99(9) the closest representation is going to be "3.0000", which is simplified to just "3". If your value was 2.099(9) it  would be rounded to and displayed as "2.1".

When you use `int()` your value gets converted by taking the integer part of your float. Which is basically rounding your value down. If it was 2.99(9), it's going to be turned into 2.

If you need your floats to be converted into ints, round them to a closest integer value using `round` function. Especially when dealing with rotations.

**Comment by lukostello** [comment]
@pycbouh Then the issue is why is it 2.999 when I asked the tween to take me to 3?

**Comment by pycbouh** [comment]
@lukostello It's hard to tell from your example, but it seems to me, that you use a lot of floating point math to get your end value. It can be very imprecise by the point it gets to the `tween.interpolate_*`.

**Comment by lukostello** [comment]
@pycbouh I understand it can be impercise along the way but surely when its doing whatever check it does to see if the tween is complete that when it decides its sufficiently close it sets the property to exactly the end value of the tween. I swear I saw it do exactly that in the engine code, which made me suspect I might be asking it to go to an imprecise value. So I changed my tween code to be as precise as possible:
```
tween.interpolate_method(self, 
					"movement", 
					translation, 
					Vector3(int(round(translation.x + cos(to_angle))), 
					0, 
					int(round(translation.z - sin(to_angle)))), 
					.25, 
					Tween.TRANS_LINEAR, Tween.EASE_OUT) 
```
but without using round in the facing = line it still differs between the prints. Which makes me think that the tween method doesn't set itself to its target value once its sufficiently close.

**Comment by lukostello** [comment]
I'm closing this because I made a new code and the same problem popped up but in a way that was easier to catch. The code was:
```
rotation.x = somevariable
print(str(rotation.x == somevariable))
```
this would print false. I've asked about this in the discord and it is a result of rotation.x having getters and setters which don't guarantee they are equal because of funky float math. This seems inevitable on some level but I didn't expect it to cause errors when rotation.x was the only variable I was changing and I was only setting it to multiples of pi/2.
