### ISSUE TITLE
Custom builds for Android gradle error

### ISSUE THREAD

**Issue by kristiannotari** [godotengine/godot#37348]
**Godot version:**
3.2

**OS/device including version:**
MacOS 10.15.3

**Issue description:**
I've tried following [this](https://docs.godotengine.org/en/3.2/getting_started/workflow/export/android_custom_build.html) official guide in order to create a custom android build for my game project, so that I can integrate [this](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin) Admob plugin (Godot 3.2 now offers the ability to do so without recompiling, so I'm trying).

Everything else (default android build) seems to work, but after following the steps in the guide and enabling an export template with custom build enabled, when I try to export the project it shows a gradle error, quite instantly after I try to export.

The error occurs _before_ adding the Admob plugin, on a fresh "install android build template" installation.

[Here](https://files.slack.com/files-pri/TUDAC0KHR-F010K7H63U1/image.png?pub_secret=913bde040f) you can find an image of the error shown.

[Here](https://godotengine.org/qa/65353/godot-3-2-custom-builds-for-android-gradle-error?show=65417#c65417) you can find the same question asked (by me) on the Godot Q&A site. They advised me to ask here instead.

Possible differences between the guide and my setup:

- I have installed the Android SDK command line tools in a folder name ".android-sdk" instead of "android-sdk", so that I don't see it often using the finder. Is it a problem? I have used [this](https://stackoverflow.com/questions/60440509/android-command-line-tools-sdkmanager-always-shows-warning-could-not-create-se) fix in order to have the sdkmanager find the correct Android SDK root path. $ANDROID_HOME variable is setup correctly tough.

- I have jenv installed with brew that manages my installed java versions. Before setting up anything I set the correct java version (1.8) (I have tried both globally and locally). $JAVA_HOME is correctly set, paths in the Godot editor settings too. Don't know if it can cause problems.

**Steps to reproduce:**

**Minimal reproduction project:**
Tell me if you need it, as currently the project is 2 days old and the only thing I have done is setting up a scene and tried an android "default" build (success), then tried the custom one (error).

**Comment by akien-mga** [comment]
It seems like gradle is not working properly for you.

CC @m4gr3d

**Comment by kristiannotari** [comment]
Update (hopefully useful):

I’m using zsh as the default shell on my macos. I have set the variables in the .zshrc file which should be the same as the .bash_profile, but for the zsh shell. I’m not setting the variables each time I run a new terminal, because they should be (and actually are) already available.

Could this be the cause of the problem?

**Comment by akien-mga** [comment]
You can test with `echo $ANDROID_HOME $JAVA_HOME` in a terminal from which you'd run Godot in the same session.

**Comment by kristiannotari** [comment]
> You can test with `echo $ANDROID_HOME $JAVA_HOME` in a terminal from which you'd run Godot in the same session.

Ok that seems to work. What I have done:

1. checked if the variables were set in the current terminal session (zsh) (they were)
2. started the Godot app with the command `open -a Godot.app` from the macOS Applications folder
3. started the custom android build export and it worked

Should I always start the Godot app via zsh terminal or is there another fancier solution? Because I think internally the gradle commands are launched within a different environment if Godot has been started "normally". Maybe I can just put those env variables also in the .bash_profile, if that's the environment which is loaded when launching Godot "normally". The only problem with that solution is that I'm using jenv for managing multiple java versions and I should remember to write back to the .bash_profile every changes I do about java versions.

**Comment by akien-mga** [comment]
Yeah macOS handles things differently depending on whether you run apps from the shell or from Finder/GUI. @bruvzg can maybe advise more about this.

**Comment by kristiannotari** [comment]
Thanks a lot akien-mga.

I have tried unsuccessfully to copy and paste all the settings I have in the .zshrc file to the .bash_profile file and then run Godot "normally" from the dock. The error is still the same one of the issue and I can't successfully export an android custom build.

Until we find a solution, I'm going to keep launching it from the zsh terminal.

**Comment by bruvzg** [comment]
> started the Godot app with the command open -a Godot.app from the macOS Applications folder

If it's set in the shell config like `~/.bash_profile` or `~/.zprofile` it will be used in the shell only. You can set global env variable by creating launch agent, like this: https://support.shotgunsoftware.com/hc/en-us/articles/219042108-Setting-global-environment-variables-on-OS-X

**Comment by kristiannotari** [comment]
Maybe it's not inherent to the issue anymore, but that's not the case when using, for example visual code. When I run it, extensions do use the $JAVA_HOME variable or similar environments variables. Moreover, in the terminals inside the editor I can find the environment variables correctly set. And I have not setup something special for anything similar before. Is it supposed to be working that way?

**Comment by themangomago** [comment]
I've got the same issues on Win10.

Versions:
Godot 3.2

openjdk version "14" 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

Gradle 6.3

JAVA_HOME and ANDROID_HOME set

**Comment by ulvido** [comment]
exactly same problem with linux 

**OS:** elementaryOS Hera (an ubuntu based distro)

**Godot:** v3.2.2.stable.flathub

**java -version**
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

**terminal:** zsh

**.zshrc**
```
...
# ANDROID SDK & ADB & JAVA8
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK=$HOME/Android/Sdk
export ANDROID_NDK_HOME=$HOME/Android/Sdk/ndk
export ANDROID_NDK_ROOT=$HOME/Android/Sdk/ndk

export PATH=$HOME/Android/Sdk/tools:$PATH
export PATH=$HOME/Android/Sdk/platform-tools:$PATH

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
export PATH=$JAVA_HOME/bin:$PATH
```

your fix didn't work me. start the project with terminal

```bash
flatpak run org.godotengine.Godot project.godot
```

and tried to export the project. no luck.

**Comment by ulvido** [comment]
ok. here is the quick fix for linux users.

add your java path to gradlew.

![Ekran Alıntısı](https://user-images.githubusercontent.com/27722274/92361558-367d6f80-f0f7-11ea-8aa4-42a0ce9fe9a4.PNG)

**Comment by Calinou** [comment]
@ulvido If you start Godot via your desktop environment, it won't read the environment variables defined in your `.bashrc`. You need to edit `/etc/environment` with superuser privileges and log out and back in.

**Comment by m4gr3d** [comment]
Closing as the original issue was resolved.
