### ISSUE TITLE
GDScript Animation `:=` false parser error

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#37357]
**Godot version:** 3.2.1

**OS/device including version:** windows

**Issue description:**
1. this line throws a false error 
```
var anim := Animation.new()
```
2. and there was no autocompletion for animation
3. Ctrl+Click also not working for animation methods

![animation-not-working](https://user-images.githubusercontent.com/41085900/77768128-0cb01f00-7068-11ea-9cf3-e33c9f0f4d20.JPG)

**Comment by KoBeWi** [comment]
I can't reproduce it.

**Comment by dankan1890** [comment]
I think there is a conflict with Sprite's "Animation" property, but I don't know how to fix it.

**Comment by katoneko** [comment]
Can reproduce. Plus, it also fails with `Material` and not only on base `Sprite `but on `TileMap `too.
![image](https://user-images.githubusercontent.com/48890128/77819295-8e04c180-70fb-11ea-8cc4-64cdb17cbfe8.png)

**Comment by KoBeWi** [comment]
Ok, this seems to be type-specific. I tried with another node and it doesn't happen.
