### ISSUE TITLE
OptionButton/PopupMenu's letter jumping jumps multiple times when pressing a key

### ISSUE THREAD

**Issue by Leleat** [godotengine/godot#37355]
**Godot version:**
3.2.1 stable

**OS/device including version:**
Fedora 31

**Issue description:**
When using an OptionButton or PopupMenu and trying to jump to an item in the list by pressing a key every single input event gets registered. For example by pressing a key for the first time you will jump to the second item (to the first upon the press and to the second on the release; holding the key cycles through everything). ItemList and Tree work normally.

**Steps to reproduce:**
Create an OptionButton/PopupMenu. Add multiple items that start the same and press a key to jump to one of those items.

**Minimal reproduction project:**
[OptionButtonPopupMenu.zip](https://github.com/godotengine/godot/files/4393875/OptionButtonPopupMenu.zip)

**Comment by BigRed-118** [comment]
Tried it running on Windows 10 64-bit, don't think I'm seeing the same behavior.

**Comment by Leleat** [comment]
tried it on MacOS 10.15.3 now and it works as it does on my fedora machine. Here is a gif (of my linux machine). I only pressed the "a" twice but the focus jumped 4 times. 

![OptionButton](https://user-images.githubusercontent.com/53054301/77845576-7a129b80-719f-11ea-91b9-5bdc041f0474.gif)

**Comment by BigRed-118** [comment]
"PopupMenu::_gui_input" has the spot for handling key inputs and searching the items. I'd be curious what it does on Mac or Fedora. Seems like that input might be getting called twice for some reason. Tree and ItemList also have that _gui_input function with similar implementation. OptionButton actually allocates a PopupMenu, so it makes some more sense that you'd see it for both of those.

**Comment by Leleat** [comment]
@BigRed-118 Looks like in the ItemList the entire code for the jump is wrapped in a big` if (is_pressed)` statement. In the PopupMenu that isn't the case, so the jump happens on press and release of a key. Not sure why windows wouldnt be effected though.

**Comment by BigRed-118** [comment]
This was annoying to debug because every time it hit breakpoints for the WM_KEYDOWN message, it would focus on Visual Studio. WM_KEYUP won't be present unless focus is maintained on the godot window.

But after hitting the right spot for the WM_KEYUP handle, on the following line in _gui_input:

`if (allow_search && k.is_valid() && k->get_unicode()) {`

k->get_unicode() is returning 0 for me on Windows, so it doesn't enter that code to change the selection.

**Comment by BigRed-118** [comment]
@Leleat This seems to be just a coincidence, otherwise Windows would see the same behavior. I think adding in the is_pressed check like the ItemList and Tree have would be valid.
