### ISSUE TITLE
Tileset: Autotile 3x3 corner bitmask not behaving consistently

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#37360]
**Godot version:** 3.2.1.stable

**OS/device including version:** Win64

**Issue description:**
![corner_bit_not working](https://user-images.githubusercontent.com/47016402/77780296-0f087e00-7054-11ea-9370-fc1c8c9c2367.png)
(3x3 minimum, icon is tile 1)

If Godot is able to differentiate between the bitmask set in tile 4 and 7 (green circles), I would also expect it to identify 8(red circles), because the bitmask there is the only thing that differentiates 4 and 7.

**Steps to reproduce:**
test texture (cells are 64x64)
![spritesheet](https://user-images.githubusercontent.com/47016402/77780518-69094380-7054-11ea-8f7d-f386592bdc54.png)

**Comment by TheDuriel** [comment]
It should behave correctly once you provide the required 48 tiles for 3x3 MINIMAL. 3x3 requires many times more.

https://lh5.googleusercontent.com/-o9pKag3Gt5o/UTp4Vu2MYHI/AAAAAAAAAK0/A7PkNHFMj3s/s800/ctm_template.png

**Comment by golddotasksquestions** [comment]
Requiring all 48 bitmasks is stupid if the game I'm working on does not need that many tiles.
What's even more stupid is that the editor gives absolutely no hint or information that this would be an requirement.
If it is necessary to have all 48 bitmasks set for logic reasons, why does Godot not define those "behind the courtain" and just swaps transparent empty cells with those the user has assigned if the user draws one of the bitmasks patterns?
Or maybe provide visible overlay hinting that those are all the tiles needed. 
At the very very least it should be mentioned in the [documentation](https://docs.godotengine.org/en/3.2/tutorials/2d/using_tilemaps.html), which it is not.

All of that is besides the point though, because it does not work with 48 tiles either. See the "0" here:
![image](https://user-images.githubusercontent.com/47016402/77826349-1e003680-710f-11ea-8339-a08105c4d718.png)

**Comment by TheDuriel** [comment]
You assigned a mask to a tile distinctly labeled as "not used". So that's not helping as you are creating configuration conflicts.

The way you've configured the maps is also not entirely correct.

I do agree that 2x2 and 3x3 minimal do need better documentation, and an official template. But from an art pipeline standpoint there is nothing inherently wrong here in terms of functionality.

**Comment by golddotasksquestions** [comment]
Of course I have tested it without setting a bitmask to "not used" as well. It's the same result. "48 tiles 3x3 minimal" does not cover those diagonals, as you yourself stated in the reddit comment I liked above.

**Comment by arturertel** [comment]
Hello, I have the problem with the tilemap that the icon interferes with the AutoTile function. How can I avoid this?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/11181906/79322234-d5b58680-7f0c-11ea-8d9f-84792637939e.gif)

**Comment by zzz-assault** [comment]
This can be solved by using WILDCARD.

In addition, please be aware that in 3x3 minimal the diagonals do not exist (tile 8 in your example), if you need them you have to use 3x3.

**Comment by golddotasksquestions** [comment]
> This can be solved by using WILDCARD.

Would you mind sharing a bitmask screenshot of how this would be solved?

**Comment by zzz-assault** [comment]
Fo what set of tiles do you need a setting? … there is no standard rule available, it always depends what you want to achieve and how much awkward transitions you are tolerating (because WILDCARD will allow tile combinations which might not look great) -> this is something you need to Experiment, start minimal and try to add if something is not good looking.

**Comment by guilhermefelipecgs** [comment]
@golddotasksquestions 3x3 minimal is intended to be used only for cases like this:
![carpet](https://user-images.githubusercontent.com/1387165/82161727-7f25ca00-9875-11ea-87e1-96e4bd6d00c6.png)
This means that you cannot create rules with only corners, for this you must use 3x3.

**Comment by golddotasksquestions** [comment]
How come then Godot can differentiate between 4 and 7 in my original post @guilhermefelipecgs 

Also would you by any chance have a reference Tileset of what a complete 3x3 would look like?
Preferably a ref sheet with ordered tiles and each tile just appearing once like these here: https://github.com/godotengine/godot-docs/issues/3316#issuecomment-614923124

**Comment by guilhermefelipecgs** [comment]
> How come then Godot can differentiate between 4 and 7 in my original post @guilhermefelipecgs

The minimum version was designed to work like this, it will not work with just one bit set in one of the corners (top-left, top-right, bottom-left, bottom-right), it only works if it has a corner plus some other two bit next to it (top, left, bottom, right). I think that the "3x3 minimal" exists only to fill a gap between 2x2 and 3x3 for a very specific set of rules as in the example I sent. Particularly I don't use it much, I prefer the 3x3.

> Also would you by any chance have a reference Tileset of what a complete 3x3 would look like?
Preferably a ref sheet with ordered tiles and each tile just appearing once like these here: godotengine/godot-docs#3316 (comment)

Like @zzz-assault said, it depends a lot on the type of game you are creating. A top-down genre will be quite different from a platform for eg. You must be more specific.

**Comment by guilhermefelipecgs** [comment]
The example you sent here https://github.com/godotengine/godot-docs/issues/3316#issuecomment-614923124 is a good example, note that none of the tiles has a corner alone, that's why it works for a  3x3 minimal.

**Comment by golddotasksquestions** [comment]
@guilhermefelipecgs 
Yes, the Tilemaps in https://github.com/godotengine/godot/issues/37360#issuecomment-630419223 are for 2x2 and 3x3 minimal.
Despite extensive research, I don't know what a complete 3x3 Tileset would look like. Where would I even start?
Like I said in the https://github.com/godotengine/godot/issues/37360#issuecomment-630419223 we really need an example in the documentation. Using less than a complete 3x3 Tileset and still make it work with wildcards sounds amazing, but how would you do that? By what logic could I find out which tiles I need, and which I instead skip by setting a wildcard? How would that wildcard be set? https://github.com/godotengine/godot-docs/issues/3491

I'm not the only one with this problem: https://github.com/godotengine/godot-docs/issues/3070

**Comment by guilhermefelipecgs** [comment]
> Despite extensive research, I don't know what a complete 3x3 Tileset would look like. Where would I even start?

To have a complete set of 3x3 bitmask, just gather all possible combinations, but I don't think that's necessary for 99% of cases :)
![Screenshot from 2020-05-19 16-49-05](https://user-images.githubusercontent.com/1387165/82371660-f03dbc80-99f0-11ea-90ed-f813dafa88e8.png)
And I agree that we need to better document all of this.

**Comment by golddotasksquestions** [comment]
Hm, yes, well, what I meant was more like the other two Tilesets I linked, a Tileset where each tile appears once, but is arranged and structured so you can actually work with it. No artist will want to work with a Tileset like that.

But I suppose you don't have such an arranged Tileset either.
This complete 3x3 set is definitely better than nothing though, and we should also add it to the Tileset tutorial until someone makes something better.

**Comment by PeterJSFChaplin** [comment]
I don't know if this will clarify or confuse things more, but in the hope of helping:

In 3x3 minimal, a corner bit is only satisfied if all three adjacent cells connected to that corner are set, but the edge buts only check the one adjacent cell.

So in your first example, no. 4 has the conditions:

1. Cell to the left must be set
2. Cell below must be set
3. At least one of the cells left, below, or diagonally left-below must not be set.

no. 7 has the conditions:

1. Cell to the left must be set
2. Cell below must be set
3. All three of the cells left, below, and diagonally left-below must be set.

no. 8 has the conditions:

1. Left must not be set
2. Below must not be set
3. Left, below, and left-below must all be set.

...which is why no. 8 can never be used - those conditions contradict themselves.

There _are_ only 47 bitmasks that can be specified in 3x3 minimal (without using ignore flags), and Godot _does not check_ how many of them you have provided. You could provide a tileset with only 2 tiles, and Godot would apply them as specifed - checking to see if any bitmask matches the current cell, and falling back to the "icon" cell if not.

**Comment by golddotasksquestions** [comment]
@PeterJSFChaplin Thanks! After weeks for experimentation and trail and error I finally understood the issue here. The only reason why it did not work as expected in the OP was because I used x3 minimal not 3x3.

I really wish the Godot UI and documentation would do a better job at explaining what is going on here, what the differences are and how they are supposed to be used. [Including Tileset reference examples](https://github.com/godotengine/godot-docs/issues/3316) in the documentation pages would already be a great and necessary improvement, I think.

I am closing this issue now, as this is quite obviously no bug, just a UI and documentation issue.
If someone comes to this page here are two links were here are two proposals where further UI improvements can be discussed:
https://github.com/godotengine/godot-proposals/issues/574
https://github.com/godotengine/godot-proposals/issues/896

**Comment by devEyesgood** [comment]
I tried making a sample 3x3 256-tile set.  It took me days to do.  But when I try using it, it does not look proper.
![256-tile-fail](https://user-images.githubusercontent.com/16976618/120007462-eeb1b780-bfa7-11eb-97d1-8aa271c6637f.png)
