### ISSUE TITLE
Scons does not detect X11

### ISSUE THREAD

**Issue by CatsNipYummy** [godotengine/godot#37367]
**Godot version:**
major = 4
minor = 0
patch = 0
status = "dev"
module_config = ""
year = 2020

**OS/device including version:**
Ubuntu 18.04.4

**Issue description:**
Scons does not detect X11

**Steps to reproduce:**
1. Clone the repo
2. `cd godot`
3. `scons3 -j4 platform=x11 (scons3="/usr/bin/env python3 $(which scons)")`

Output:

```
scons: Reading SConscript files ...
Invalid target platform "x11".
The following platforms were detected:

	haiku
	linuxbsd
	server

Please run SCons again and select a valid platform: platform=<string>
```

But I have X11 installed. Here the output of my `dpkg -l | grep xserver-xorg-core`

`ii  xserver-xorg-core-hwe-18.04                                 2:1.20.5+git20191008-0ubuntu1~18.04.1                       amd64        Xorg X server - core server`

**Comment by Ev1lbl0w** [comment]
[This commit](https://github.com/godotengine/godot/commit/f8a79a97c7d12da43b111a756f09ee7ad5ea28e9) seems to imply that `x11` was renamed to `linuxbsd`.

But if that's the case, then the [documentation](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_x11.html#compiling) has to be changed.

**Comment by Calinou** [comment]
I wonder if we should alias `x11` to `linuxbsd` to prevent errors like this. Many third-party documentation websites will never be updated :slightly_frowning_face:

**Comment by CatsNipYummy** [comment]
@Ev1lbl0w  That is how I got it to work. Ran it with platform=linuxbsd and everything went off fine.

**Comment by rcorre** [comment]
This should make it rather obvious:

```
The following platforms were detected:

        haiku
        linuxbsd
        server
```

Still, I somehow missed that and ended up finding this issue instead :man_facepalming:
