### ISSUE TITLE
Add demo project for CRT and GameBoy shaders

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3736]
_**Bugsquad note:** this is a request for a demo project, not for an internal feature._

I have encountered this shaders when reading about emulators.
http://emulation-general.wikia.com/wiki/Shaders_and_Filters
Maybe they can be implemented into Godot?

Gameboy shader:
![gameboy](https://cloud.githubusercontent.com/assets/11817561/13094330/4747e15a-d50a-11e5-90e4-7d572c2a7219.png)

CRT shader:
![crt](https://cloud.githubusercontent.com/assets/11817561/13094333/4d1ef988-d50a-11e5-9549-27a228f802f4.png)

**Comment by GlaDOSik** [comment]
You are asking engine devs to do your work. Godot has a programmable shaders, you can already do it. [https://www.facebook.com/groups/godotengine/permalink/732192463584017/](url)

**Comment by vnen** [comment]
AFAIK Godot doesn't have any built-in shader but comes with the ability for you to create your own. Hopefully by 2.1 we will have a proper way to share assets (including shaders) so it'll be easier to find those kind of things.

**Comment by reduz** [comment]
New asset sharing section in Godot website will eventually allow you to add
these things

**Comment by freemanfromgodotengine** [comment]
Sorry @vnen, @reduz, I guess I should of be more precise.
I just remember reduz asking on irc, back when he was working on shader code and was preparing shaders demos in the same time, what kind of shader fx demo should be included.
So, there are two more that are not present in shader demo, but in my oppinion would make a nice addition.
Good to hear webpage will have a sharing secion.

@GlaDOSik, what's that facebook logging page link for?

**Comment by vnen** [comment]
So I'm gonna reopen this as a request for demos and change the title and description to match.

@freemanfromgodotengine the link to the actual shader on the Facebook post: https://github.com/henriquelalves/SimpleGodotCRTShader

**Comment by reduz** [comment]
Yeah, demos right now are in github, but the plan is to move them to the
new site

**Comment by freemanfromgodotengine** [comment]
thx @vnen for reopening, cleaning my subject mess and providing the link.
Godot related things are so scattered on the web.

@reduz setting a place similar to unity shop, where all creators could present their things and share or offer for others, would certainly benefit Godot's community.

**Comment by neikeq** [comment]
This issue should probably be moved to the new [godot-demo-projects](https://github.com/godotengine/godot-demo-projects) repository.

**Comment by djrm** [comment]
movable to demos repo (just a reminder)

**Comment by akien-mga** [comment]
More than extended the shaders demo with various new shaders, wouldn't it be better to just get as many good shaders as possible under a libre license in the asset sharing platform?

**Comment by neikeq** [comment]
I agree with @akien-mga. Demos are not supposed to teach you how to use shaders, not to provide you every possible shader. You will be able to share your shaders with the asset sharing platform.

**Comment by akien-mga** [comment]
Let's close then.

**Comment by Tybobobo** [comment]
Almost a year later; @freemanfromgodotengine 

I have just worked on this myself, and believe I have managed to create a pretty good GameBoy shader. 

Written a tutorial and added the shader codes here:
http://ivanskodje.com/node/10

Always looking for ways to improve upon my projects, so if you can manage to make it better, please let me know! :)
