### ISSUE TITLE
Saving a scene cause an empty black window appearing

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#37378]
**Godot version:** 307b1b3

**OS/device including version:** Windows10

**Issue description:**
saving a scene cause an empty black window appearing instead of saving progress window, which takes the main window's focus.
![saving-script-window-bug](https://user-images.githubusercontent.com/41085900/77822456-ef875900-7118-11ea-864c-99551f0c7eb1.gif)

**Comment by Ev1lbl0w** [comment]
Probably related to #37322

**Comment by KoBeWi** [comment]
Duplicate of #37322
