### ISSUE TITLE
android build template fails

### ISSUE THREAD

**Issue by eminvergil** [godotengine/godot#37374]
**Godot version**: 3.1.2-stable

**OS/device including version**: windows 10

**Issue description**:

FAILURE: Build failed with an exception.

* What went wrong:
Task 'generateGodotTemplates' not found in root project 'java'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU¦LD FAILED in 13s

**picture**:

![Untitled](https://user-images.githubusercontent.com/17277419/77820793-efc22d00-70f5-11ea-99b4-a8c2f5deef4d.jpeg)

any response would be appreciated.

**Comment by akien-mga** [comment]
If you build Godot 3.1.2, you should use the matching version of the docs: http://docs.godotengine.org/en/3.1/development/compiling/compiling_for_android.html

`generateGodotTemplates` is for 3.2 and later, in 3.1 it was `gradlew build`.
