### ISSUE TITLE
non english community resources? 

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3737]
i was chatting with a russian godot engine dev on irc and said there are about 300 people on a russian social network site they made.
http://vk.com/godot_engine

however i think their community is isolated from rest of godot because they don't speak english so im wondering if there are any plans for non english speaking users.

what are the plans for non english resources/community (like links , urls etc)
or are there any plants in translating the site into different languages?

**Comment by volzhs** [comment]
does http://www.godotengine.org/ have already multi-language resources? (not perfect though)

![image](https://cloud.githubusercontent.com/assets/8281454/13100910/f891e116-d584-11e5-99e8-6629a0e4ae49.png)

**Comment by trollworkout** [comment]
@volzhs  you're right it does. but what about url links to non english communities  some sort of links area

**Comment by trollworkout** [comment]
i guess this is kinda redundant i'm gonna close it looking again at the site seems like is quite capable of multi language stuff

**Comment by akien-mga** [comment]
Please don't use the GitHub issues as a Q&A though, it's meant for bugs and feature requests, not for getting a quicker answer than on IRC, Facebook, the mailing list or the soon-to-be Q&A :)
