### ISSUE TITLE
stretch only certain area of image

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#3738]
it is possible to set an image in a panel and stretch image when panel it is resized.
But it would be useful to stretch only certain area of image.
e.g. in this image I want to stretch only yellow areas and not to stretch red areas

![box](https://cloud.githubusercontent.com/assets/12212708/13106161/1eee71f8-d567-11e5-9b2f-f8368da50ebd.png)

**Comment by volzhs** [comment]
AFAIK, godot already can do it.
There is ``Patch9Frame`` control.
And you can skin panel. http://www.godotengine.org/projects/godot-engine/wiki/GUI_Skinning

**Comment by GrandFunkR** [comment]
oh thank you,
I did not know this.
sorry for the issue.
I close it
