### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by Hamed2012-dr** [godotengine/godot#37393]
Hello. Please add javascript programming language API to the Engine ...

**Comment by ThakeeNathees** [comment]
@Hamed2012-dr This repository no longer accepts feature / enhancement requests. your proposals should be created on https://github.com/godotengine/godot-proposals with more details

**Comment by akien-mga** [comment]
More importantly, we don't have time for such low efforts proposals, either here or on godot-proposals.

There's no plan for JavaScript support officially. There's a community effort that you can use though.

Duplicate of #19294 and #937.
