### ISSUE TITLE
Basis.is_equal_approx() not working

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#37390]
**Godot version:**
3.2 stable official

**OS/device including version:**
Windows 10

**Issue description:**

Basis.is_equal_approx() is failing even when the difference is less than Epsilon.

As an example, I am using: `transform.basis = transform.basis.slerp(_target_rotation, ROTATION_SPEED)` within _physics_process() to rotate a body.

When I try to check if the rotation is complete using `	if transform.basis.is_equal_approx(_target_rotation, 0.01):` the condition never equates to true. Note the ridiculously high epsilon. (Which would surely cause issues if it worked.)

If I print the current and target Basis after the comparison fails, I get:

Current:  `((0.000004, 0, 1), (0, 1, 0), (-1, 0, 0.000004))`

Target: `((-0, 0, 1), (0, 1, 0), (-1, 0, -0))`

Which are well within the Epsilon range.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by TheDuriel** [comment]
```
	if transform.basis.x.is_equal_approx(_target_rotation.x) \
	and transform.basis.y.is_equal_approx(_target_rotation.y) \
	and transform.basis.z.is_equal_approx(_target_rotation.z):```

This works btw.

**Comment by TheDuriel** [comment]
https://github.com/godotengine/godot/blob/1eb424ec9549bdd086dfb54c847d107519be73d9/core/math/basis.cpp#L572 Relevant source. Pretty much does exactly what my GDScript reimplementation does.

**Comment by TheDuriel** [comment]
Someone also please look into this: Is the epsilon value you pass actually used? Its somewhat difficult to track down how the Variant methods are bound.

**Comment by winston-yallow** [comment]
For me `is_equal_approx` can give false positives too additionally to the false negative:

```swift
tool
extends EditorScript

func _run() -> void:
    var a := Basis(Vector3.ZERO).rotated(Vector3.UP, PI)
    var b := Basis(Vector3.ZERO)
    print(a)
    print(b)
    print(a.is_equal_approx(b))
    print(gdscript_approx_equal(a, b))

func gdscript_approx_equal(a: Basis, b: Basis) -> bool:
    return (
        a.x.is_equal_approx(b.x)
        and a.y.is_equal_approx(b.y)
        and a.z.is_equal_approx(b.z)
    )
```

Output:
```
((-1, 0, -0), (0, 1, 0), (0, 0, -1))
((1, 0, 0), (0, 1, 0), (0, 0, 1))
True
False
```

**Comment by TheDuriel** [comment]
Getting the same issue with Vector3, though less pronounced.

**Comment by aaronfranke** [comment]
@TheDuriel Can you post a minimal reproduction project that shows this happening with Vector3?

**Comment by TheDuriel** [comment]
My workaround in my previous post. It worked better, but not perfectly.

I since moved on to using quats to perform my motion, and comparing only a single vector in the end. So I don't have the MRP anymore.

That said, Vector3 seems to be missing the ability to pass a custom epsilon. (Which is actually a cool feature as it lets you make fuzzy comparisons easily.)
