### ISSUE TITLE
Is mingw-w64 8.1 the latest version.(got a problem while compile ,need newer gcc version)

### ISSUE THREAD

**Issue by 2439905184** [godotengine/godot#37404]
**Godot version:*3.2.1*

**OS/device including version:*windows7 64bits*

**Issue description:*Is mingw-w64 8.1 the latest version.(got a problem while compile ,need newer gcc version)*

**Steps to reproduce:*I use scons command to build for windows ,but It tell me need newer gcc,But seems mingw-w64 8.1 is the latest version, I dowoload from SourceForge .*

**Minimal reproduction project:**
![捕获](https://user-images.githubusercontent.com/29478722/77846084-0a73cf00-71e6-11ea-8270-22d58e75d784.PNG)
![捕获2 (2)](https://user-images.githubusercontent.com/29478722/77846103-24adad00-71e6-11ea-9c85-204cdcd3f8e3.PNG)

**Comment by akien-mga** [comment]
Try MSYS2 which has a newer version of GCC (9.2.0): http://mingw-w64.org/doku.php/download

This is not a Godot bug though, so this is not the right issue tracker to ask for support.
Might be worth discussing further on https://github.com/godotengine/godot-docs if Windows MinGW installation instructions need to be further specified.

**Comment by akien-mga** [comment]
> **Godot version:3.2.1

BTW, if you're using Godot 3.2.1 you should not have any issue. You're not building 3.2.1 here but the `master` branch (4.0).
