### ISSUE TITLE
Printing JSON Parse Result in C# Causes A Project To Break Permanently

### ISSUE THREAD

**Issue by thorlucas** [godotengine/godot#37400]
**Godot version:**
Godot v3.2.1.stable.mono.official
Mono JIT compiler version 6.6.0.166
.NET version 3.1.201

**OS/device including version:** macOS Catalina 10.15.2

**Issue description:** When using the JSON.Parse followed by a cast to Dictionary<object, object> followed by a GD.Print(dict) in C#, upon compilation, Godot hangs forever. Force quitting the application does nothing. Activity monitor hangs forever too. `killall Godot` does nothing. The computer must be force shut down. When attempting to open this project again, the same thing happens. The project is broken permanently, even after removing this line of code. Other projects continue to work. I had to completely rebuild this whole project twice because of this issue, since I could not find a way to be able to open this project without Godot crashing.

**Steps to reproduce:** Clone [this project](https://github.com/thorlucas/GodotBug) and run it.

**Minimal reproduction project:** I could not come up with a minimal reproduction project. Doing the same thing in a blank project causes the editor to crash, but it’s recoverable. I tried coming up with one but I'm tired of force shutting down my computer every time. Will post back if I can come up with one. (However the project itself is already fairly minimal).

**Comment by Tobi-Mob** [comment]
The reproduce project is no longer available, so I am unable to test this.

Maybe this is the core issue: #1289 ?

https://github.com/godotengine/godot/issues/1289#issuecomment-71005562

>The actual cause is that currLine is a dictionary which contains values that can reference back to currLine, thus creating a recursive reference. This crashes the game when trying to print() it.

If this is still happening, maybe deleting the .mono directory could help.

**Comment by akien-mga** [comment]
Closing as this can't be reproduced without a project.
