### ISSUE TITLE
Time line zoom is confusing in Animation player

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot#37409]
**Godot version:** 3.2.1

**OS/device including version:** Solus

**Issue description:** 
It supposed to be zoom in but it zooms out.
![Peek 2020-03-29 21-12](https://user-images.githubusercontent.com/29702428/77853515-13729980-7202-11ea-8225-0b6fe1497754.gif)

**Steps to reproduce:**
N/A
**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
I agree the timeline zoom slider should be reversed as well.

**Comment by dankan1890** [comment]
> (The question is, what would be 100% zoom in this context?)
Animation length ?

**Comment by Janglee123** [comment]
@Calinou Percentage might be not useful information, but to answer your question, 100% supposed to be 0 zoom level as web browsers do.
