### ISSUE TITLE
There is wrong button for the accept action of Nintendo controllers 

### ISSUE THREAD

**Issue by NicholasShatokhin** [godotengine/godot#37406]
**Godot version:**
3.2

**OS/device including version:**
Any

**Issue description:**
There is no possible to remap gamepad keys for different platforms. I want to use A button for accept action in Nintendo (as used on this platform by default) and B for cancel with keeping X and O at Ps4. But Godot don't allow to remap keys. It allows only pairs A/X or B/O. 

I just want to keep intuitive controls on different platforms as player expected. 

**Steps to reproduce:**
Add gamepad action to Input map. Try to remap keys for different platforms 

**Minimal reproduction project:**
Empty

**Comment by miv391** [comment]
I suggest adding a feature that allows swapping controller buttons 0 and 1 and adding the following methods to Input:

```gdscript
# enable/disable automatic swapping
Input.use_automatic_joy_ok_cancel_swapping(automatic_swap: boolean)

# enable/disable swapping for specific controller
Input.swap_joy_ok_cancel(device: int, swap: boolean)
boolean Input.is_joy_ok_cancel_swapped(device: int) -> boolean
```

If the controller is detected to be a Nintendo controller, buttons 0 and 1 would be swapped automatically. This automatic action could also be disabled. Then by default if the player is using a Nintendo Controller, Ok (A) and Cancel (B) would work like usual with that controller (assuming that the player usually plays Nintendo's games).

Now the game programmer would have the following options:
- Use automatic swapping. Nintendo controllers would work like they usually work with Nintendo's games.
	- If the game is localized to Japan, the programmer could also swap PS controller buttons.
- Do not use automatic swapping. All controllers are equal, only the button location is important, not the button label or controller manufacturer.
	- For example the game uses ABXY buttons for moving instead of making UI selections.
- Give the player an option to explicitly swap / not swap the buttons.
	- For example an Xbox owner is playing at friend's place using friend's Nintendo Pro controller and just wants the controller to work like an Xbox controller.


I also suggest that the `Input.get_joy_name()` would be changed to return more easily usable data if technically possible. Currently game programmer needs to have all possible game controllers to know what strings this method can return and then doing string parsing to figure out if the controller is for example Nintendo's controller. Maybe `Input.get_joy_name` could return a dictionary like this:
```
{"family": "Nintendo", "type": "Nintendo Pro Controller"}
```
The few controller families could be listed in the documentation. I guess that most often the controller family would be enough for the game programmers and they would not need to care about the exact controller type at all.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4242, as feature proposals are now tracked in the Godot proposals repository.

@miv391 I recommend posting your comment here on the proposal above so it doesn't get lost here.
