### ISSUE TITLE
Crash on Script Editor Replace with Empty String

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#37416]
**Godot version:**
3.2.1-stable
**OS/device including version:**
Windows 10 Pro x64
X570 chipset; Ryzen 7 3rd gen; DDR4;
**Issue description:**
When attempting to replace "var " with "", the editor crashes. Maybe accessing invalid memory at a pointer address that doesn't exist because the replace box is blank?
**Steps to reproduce:**
Select a block of text. Replace "var " with nothing in the replace box. Make sure "in selection" is checked (thanks @Anutrix for finding this)

**Comment by Calinou** [comment]
This is strange because it worked when I implemented #29029...

**Comment by Jimmio92** [comment]
Any chance this can get cherry-picked back to 3.2.x or is the 3.2.x line no longer being updated?

I didn't even know there _was_ find-in-files. Maybe find-in-files and find-replace is duplicated code and that's why one half works? I haven't had the time to look in the src, personally.

**Comment by Calinou** [comment]
@Jimmio92 The `3.2` branch is still maintained and will be so for a while (at least until 4.0 is released).

**Comment by Anutrix** [comment]
I couldn't reproduce this in master actually. Can someone confirm?

**Comment by Anutrix** [comment]
Reproduced now after checking selection only and selecting a block of code. Maybe you can update issue title to mention this.

**Comment by Jimmio92** [comment]
"Select a block of text. Replace "var " with nothing in the replace box."

Selecting a block and pressing the Ctrl+R auto-selects in selection; I thought that was implied. I will add details to the issue.
