### ISSUE TITLE
Copy/Paste not working in ColorPicker

### ISSUE THREAD

**Issue by stebulba** [godotengine/godot#37410]
**Godot version:**
 Godot_v3.2.1-stable_x11, AND 3.2
**OS/device including version:**
Ubuntu LTS 16.04
**Issue description:**
The copy paste ( CTRL+C, CTRL+V, CTRL+X, ctrl+Z and ctrl+shift+Z) not working in the ColorPicker pannel.
The context menu is visible, but not working too.
Ctrl+A and option erase in menu are working.  
**Steps to reproduce:**
![godot_copy_paste_not_working](https://user-images.githubusercontent.com/26193340/77856023-688ebb00-71c2-11ea-8d08-14f8be4f1ea9.jpg)

This is a lot of frustration ;-)
I didn't found any where else the same issue.

**Comment by Calinou** [comment]
I'm fairly sure I've seen this issue on GitHub already, but I can't find it right now.

**Comment by Zireael07** [comment]
Yep, and IIRC it was something to do with focus?

**Comment by dreamsComeTrue** [comment]
Can't reproduce on current master (Fedora Linux) :/

**Comment by stebulba** [comment]
> Can't reproduce on current master (Fedora Linux) :/
>Yep, and IIRC it was something to do with focus?

After to read you., I am suspicious. I try again, I some time I got it. The trouble look to be the focus.
Nice coincidence, because I just worked in my project, on the lineEdit focus.

**Comment by ThakeeNathees** [comment]
@Calinou it's already closed #35603

**Comment by akien-mga** [comment]
Duplicate of #35603.
