### ISSUE TITLE
Godot stops running scenes and stops booting the editor

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#37420]
**Godot version:**
Godot v3.2.1 stable

**OS/device including version:**
Windows 10 Pro Education

**Issue description:**
The Godot editor ceases to run any scene debug or normally, and if I close the godot editor my computer requires a restart before the godot editor and scenes run again.

there are no errors besides ones in the external console. it just doesn't do anything

**Steps to reproduce:**
I'm not sure I just use the editor for a extended period of time.
I rename and move objects alot so that might be part of it.

here is the console printouts if it helps.
[Console (2).txt](https://github.com/godotengine/godot/files/4400900/Console.2.txt)

**Minimal reproduction project:**
I don't think this has anything to do with the project but here it is.
[AstroWars (2).zip](https://github.com/godotengine/godot/files/4400905/AstroWars.2.zip)

**Comment by Calinou** [comment]
Looking at the log, it seems Godot is unable to create a directory when running the project from the editor:

```text
ERROR: make_dir_recursive: Method failed. Returning: err
   At: core/os/dir_access.cpp:175
```

**Comment by Shadowblitz16** [comment]
I forgot to mention my computer will not fully soft shutdown or soft restart after this happens.
It basically just idles with the screen turned off until I hold the power button

**Comment by Zireael07** [comment]
@Shadowblitz16: In that case it looks like your RAM/GPU or HDD might be faulty. For instance, I had issues where Godot would sometimes not save project settings, and months later the HDD completely failed. Godot was the only software displaying any issues earlier on.

**Comment by Shadowblitz16** [comment]
hmm ok I can try to get another computer. 
I just don't have alot of money right now.

it could also just be the operating system.
I have heard windows 10 is still buggy

**Comment by Zireael07** [comment]
Are you running as an administrator? Maybe Windows 10 is indeed messing something up...

**Comment by Calinou** [comment]
I wonder if this is yet another issue related to file locking and antivirus programs. Try adding Godot in the list of exceptions of your antivirus (or Windows Defender).

**Comment by Shadowblitz16** [comment]
I have both malwarebytes and windows defender should I add them to both?

**Comment by Calinou** [comment]
@Shadowblitz16 Yes. (That said, Windows Defender generally disables its core functions once you enable another antivirus.)

**Comment by Shadowblitz16** [comment]
ok I did it. 
now its time to wait and see.
I will reopen this if it happens again

**Comment by Shadowblitz16** [comment]
@Calinou just did this again

**Comment by Shadowblitz16** [comment]
this seems to be happening with a game called king arthur's gold too so I don't think this is godot related  
![image](https://user-images.githubusercontent.com/2453707/78624259-155ddd80-783e-11ea-8e39-ec184e7739e8.png)

its either windows 10 being a shit operating system or my pc is dying
