### ISSUE TITLE
when will mono build be used in actual production

### ISSUE THREAD

**Issue by Jiaming00** [godotengine/godot#37422]
About mono build, when will it be used in actual production, or when will the alpha phase end.

**Comment by Calinou** [comment]
There is no ETA for the Mono build being marked as production-ready, but the main missing features such as iOS export and AOT compilation are expected to be added in Godot 4.0.

**Comment by Jiaming00** [comment]
> There's no ETA for the Mono build being marked as production-ready, but the main missing features such as iOS export and AOT compilation are expected to be added in Godot 4.0.

Thank you for your reply, aside from platform support and feature support, I would like to know what other specific reasons for "cannot be used for actual production",  if there is any, such as unstable and major changes at any time.If these problems do not exist, I think it can be used for actual production for me.

**Comment by Anutrix** [comment]
Due to the Vulkan merge, followed by recent core refactorings including the OS/DisplayServer split, the master build is currently unstable. Other than the main missing features, these seem to be the current things that need to be stabilized

**Comment by neikeq** [comment]
The information dialog about it being alpha will be removed in 4.0. It's already quite stable as of 3.2, but there are a lot of breaking changes incoming for C# in 4.0, so I decided not to remove it until then.
