### ISSUE TITLE
OS.Execute C# Invalid expression term [

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#37437]
**Godot version:**
3.2.1 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
Using OS.Execute I have this error in the first opened "[" : 
`Invalid expression term '[' [SimNet]csharp(CS1525)`

**Steps to reproduce:**
```
 public void _on_Button_pressed()
    {
        int _exitCode = OS.Execute("tc", ["qdisc",  "show",  "dev",  "lo" ], false);
        GD.Print("ok");
    }

```

But if I use it  in this way it work:
```
    public void _on_Button_pressed()
    {
        string[] _myArrayString = {"qdisc",  "show",  "dev",  "lo"};
        int _exitCode = OS.Execute("tc", _myArrayString, false);
        GD.Print("ok");
    } 
```
Because there is no different indication in Documentation I assume it is a bug.
**Minimal reproduction project:**
NA

**Comment by bojidar-bg** [comment]
The code given in steps to reproduce contains invalid C# syntax.
For example, doing `Console.WriteLine(["a", "b", "c"]);` in https://dotnetfiddle.net/ results in:
```
Compilation error (line 7, col 21): Invalid expression term '['
```
To make an inline array, use `new [] {…}`, as in `Console.WriteLine(new [] {"a", "b", "c"})`.


---

Closing as non-issue. If you think it should be reopened, feel free to comment.

**Comment by git2013vb** [comment]
@bojidar-bg  Thank you for your explanation. This issue no need to be re-open But there are some missing C# documentation in https://docs.godotengine.org/en/latest/classes/class_os.html#class-os-method-execute  I found gdscript example only.

**Comment by Calinou** [comment]
@git2013vb We don't have a way to add C# code samples to the class reference, so we're sticking to GDScript examples only for now.
