### ISSUE TITLE
Contributors: Update your pre-commit hooks

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#37431]
I just merged #37421 which formats our Python files using [psf/black](https://github.com/psf/black), and to keep things well formatted in PRs, we now also have a check on Travis that will ensure that changes to Python files respect the formatting.

There's a new pre-commit hook for black that I encourage you to install locally. You should re-install all hooks since the main `pre-commit` one has an added reference to `pre-commit-black`, so:

```
cp -f misc/hooks/* .git/hooks/
```

For the new hook, you'll need `black` available in your PATH. You can install it with `pip3 install black` (either with `sudo`, `--user` or in your venv).

If you didn't have the `clang-format` pre-commit hook set up yet, the above comment will enable it too. You'll need `clang-format` 8 or later in your PATH (you might need to edit `pre-commit-clang-format` to point to it otherwise).

Finally, you can install pygments (`pip3 install pygments`) to have a nice colorized diff output when the pre-commit hooks find any issue.

**Comment by akien-mga** [comment]
Note: I haven't tried the pre-commit hooks on Windows but it should be possible to make them work at least in `git-bash.exe` or WSL. If anyone gives it a try and wants to improve the installation instructions in `misc/hooks/README.md`, that would be great.

**Comment by pouleyKetchoupp** [comment]
I was able to make `clang-format` and `black` hooks work on Windows 10, in git bash & git extensions. It's pretty straightforward, but I'm going update the readme with a few details:

**clang-format**
*Download LLVM for Windows (version 8 or later) from https://releases.llvm.org/download.html*
*Make sure LLVM is added to the PATH during installation*

**black**
*Make sure Python is added to the PATH during installation*
*In any console: pip3 install black*

No luck with `pygmentize` so far though. It works on its own with patch files but the colors are not displayed during the pre-commit hook for some reason.

I haven't tested `makerst` hook yet.

**Comment by Calinou** [comment]
> No luck with `pygmentize` so far though. It works on its own with patch files but the colors are not displayed during the pre-commit hook for some reason.

This might be due to pre-commit stripping color codes on Windows.

**Comment by akien-mga** [comment]
Note: I fixed a bug in black's patch generation (https://github.com/psf/black/pull/1328) which could impact users of our pre-commit hook when you have formatting issues at the end of a file.

You can install the latest version from git until it lands in a stable release, with:
```
pip install --user git+https://github.com/psf/black@master
```

**Comment by akien-mga** [comment]
Closing as this was just meant as a temporary announcement.

**Comment by mhilbrunner** [comment]
For anyone arriving via search engines: this is long outdated, for up-to-date instructions see https://github.com/godotengine/godot/pull/88866.
