### ISSUE TITLE
Create Scene Dialog (Name) is ignored?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#37448]
**Godot version:**

3.2.1

**OS/device including version:**

Windows 10

**Issue description:**

when create scene from file system context menu instead of main menu a dialog appears, asks for name, and ignores it

- should work
- should be consistant? ask for name or not in both places?

**Steps to reproduce:**

![2020-03-30 (4)](https://user-images.githubusercontent.com/962340/77972959-d6b9a780-72c0-11ea-9ed0-49b814057a5f.png)
![2020-03-30 (5)](https://user-images.githubusercontent.com/962340/77972967-db7e5b80-72c0-11ea-9880-fd3f62a7b407.png)

sorry to nitpick :) not a serious problem

thanks

**Comment by ThakeeNathees** [comment]
@rakkarage you already selected the folder for the scene but to complete the path it needs the scene name and once you add a root node and save it, it doesn't ask the path again just save it inside the folder with the path you've given.

**Comment by rakkarage** [comment]
sorry thanks
