### ISSUE TITLE
Shader language doesn't allow assigning constants with constant arithmetic with other constants

### ISSUE THREAD

**Issue by IceCubeDev** [godotengine/godot#37457]
**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
PC running Windows 10 (10.0.18362)
Intel Core i5-8600K @ 3.60GHz, 6cores
NVidia GeForce GTX 1060 6GB (Driver version 432.00)
8GB RAM

**Issue description:**
The shader language doesn't seem to accept constants that use arithmetic operations involving other constants. In comparison, this seems to work in raw GLSL (https://github.com/McNopper/OpenGL/blob/master/Example11/shader/glass.vert.glsl).

**Steps to reproduce:**
Paste the following shader into a MeshInstance node's material:

```
shader_type spatial;
// Indices of refraction
const float Air = 1.0;
const float Glass = 1.51714;

// Air to glass ratio of the indices of refraction (Eta)
const float Eta = Air / Glass;
 
// see http://en.wikipedia.org/wiki/Refractive_index Reflectivity
const float R0 = ((Air - Glass) * (Air - Glass)) / ((Air + Glass) * (Air + Glass));

void fragment() {
    ALBEDO = vec3(1.0, 0.8, 0.5);
}
```
The shader breaks:
![ShaderBug_ConstantAritmetic](https://user-images.githubusercontent.com/8280670/78009010-12984f80-7349-11ea-82b8-379250e53e68.png)

If I rewrite the shader constants as:
`const float Eta = 1.0/ 1.51714;`
then the shader does not break.

**Minimal reproduction project:**
[ShaderBug_ConstantAritmetic.zip](https://github.com/godotengine/godot/files/4407871/ShaderBug_ConstantAritmetic.zip)

**Comment by Calinou** [comment]
cc @Chaosus 

This was fixed in https://github.com/godotengine/godot/issues/33840, but I guess it broke again?

**Comment by Chaosus** [comment]
They are parsed correctly but in wrong order, the topic code translated to:

```
const float m_Glass=1.51714;
const float m_R0=(((m_Air-m_Glass)*(m_Air-m_Glass))/((m_Air+m_Glass)*(m_Air+m_Glass)));
const float m_Air=1.0;
const float m_Eta=(m_Air/m_Glass);
```
m_Air seems defined after m_R0 which fails compilation, I will take a look to solve this problem.
