### ISSUE TITLE
Getting vertices/edges from any Shape2D for Navigation2D

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3745]
I'm working with the navigation2D and I'm trying to make it dynamic. so I have to set the navigation polygon at runtime.
obstacles usually are collision objects that has some collision shape/polygon attached to it. so I wanted to use that collision shape to feed the navigation polygon. I think that would work with collision polygon since you do have the option to retrieve an array of Vector2's (I still can't get the outline from them).

so please add a function that retrieves vertices/edges from any shape2D?

**Comment by bojidar-bg** [comment]
@lordadamson ~ What about circles? :smile:

**Comment by lordadamson** [comment]
I don't know :D maybe add an exception for them?

**Comment by akien-mga** [comment]
Shapes will be reworked for 3.0.

**Comment by reduz** [comment]
pushing to 3.1, where we might enable recast..

**Comment by akien-mga** [comment]
Is this fixed in the current master branch? We have some integration of Recast, but I don't know if it covers this use case.

**Comment by akien-mga** [comment]
No answer, I'll close for now. If it's still relevant, it would be best to open a detailed feature request on https://github.com/godotengine/godot-proposals.
