### ISSUE TITLE
The print shows only. No assignment

### ISSUE THREAD

**Issue by ZhiTravelsNorth** [godotengine/godot#37453]
#suffix:suffix,path:path
func Read_file(path, suffix):#:读取文件
       var ai
	var dir = Directory.new()
	var files = []
	if dir.open(path) == OK:
		dir.list_dir_begin()
		var file_name = dir.get_next()
		while (file_name != ""):
			ai.append(file_name) 
			print(file_name) #All files can be printed out to see the results
			if dir.current_is_dir():
				pass
			elif file_name.split(".")[-1] == suffix: 
				files.append(file_name.split("_")[1])
		dir.list_dir_end()	
	else:
		print("无法读取文件，访问路径错误。")
	return files
![QQ图片20200331123033](https://user-images.githubusercontent.com/62843593/77987147-9a7f5900-734b-11ea-96c8-ade9b0ec93f7.png)

**Comment by ZhiTravelsNorth** [comment]
After opening the file, use list dir begin() to list the streams of all files and directories, and get next() to get the file name. But it cannot be assigned to AI and can be printed out. File_name. Split (".") [- 1] = = suffix: available on PC but empty on mobile phone.

**Comment by Calinou** [comment]
On mobile platforms like Android, you can't list directories as the filesystem isn't readable like a standard file/folder sructure. You'll have to find another way (such as saving the list of folders into a text file and loading the text file in Godot).
