### ISSUE TITLE
PopupMenu doesn't keep his position when set visible

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#37460]
**Godot version:**
3.2.1 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
![image](https://user-images.githubusercontent.com/13235119/78020408-5428fa80-7349-11ea-9b04-e0e4526f04e3.png)

Expected:
![image](https://user-images.githubusercontent.com/13235119/78020485-73c02300-7349-11ea-928a-b0e843f9307e.png)

Current tree:
![image](https://user-images.githubusercontent.com/13235119/78020569-98b49600-7349-11ea-8b61-c3e8ba6708ff.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by dreamsComeTrue** [comment]
Can you describe steps needed to reproduce that potential issue?

**Comment by git2013vb** [comment]
I did't use any script. I just set the tree as you can see in my post then i run the scene.
I point out the difference between design time and execution time

**Comment by carmel4a** [comment]
@git2013vb Properties may differ, as margins, anchors. Can you provide minimal project (and still reproduce this), as scene with this `Main` Control node?

**Comment by git2013vb** [comment]
[Control.cs.zip](https://github.com/godotengine/godot/files/4421578/Control.cs.zip)
I cent give you the project because I changed it - I cannot use PopupMenu - with another control.
But this zip hhave a scene + C# script( just show popupmenu in ready) that can show you how popup get all space he need until top when he is visible. Also I think this problem is related with TextEdit control togheter with  popupmenu  control show weird behaviour. Also grid container behave weird... Honestly I'm not sure how many problems there are in such small scene :)

**Comment by akien-mga** [comment]
The attached scene works fine for me:
![Screenshot_20200726_224249](https://user-images.githubusercontent.com/4701338/88488952-5a468500-cf91-11ea-9b01-866bac6bf02b.png)

It matches the way it's set up in the editor:
![Screenshot_20200726_224315](https://user-images.githubusercontent.com/4701338/88488958-692d3780-cf91-11ea-801d-6a4892f34273.png)

Testing in 3.2.2-stable.
