### ISSUE TITLE
look into iPadOS support

### ISSUE THREAD

**Issue by eff96** [godotengine/godot#37469]
im not saying you should, but if you can do that, that would be awesome.

**Comment by Calinou** [comment]
This issue tracker is intended to be used for bug reports only. Please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository if you feel there are missing features in the iOS export to target iPadOS.

Note that Godot already supports exporting to iOS, so you have to describe which features need to be added for better integration with iPadOS (and justify why they're needed in Godot's context).
