### ISSUE TITLE
No way to call Dictionary.erase() in VisualScript due to missing white arrows

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#37478]
**Godot version:** 3.2.1

**Issue description:** `Dictionary.erase()` is missing white arrows, so there's no way to execute this method in VisualScript unless you want to use the return boolean somewhere.

![](https://user-images.githubusercontent.com/1646875/78004365-02ac4b80-7308-11ea-8b3f-cc8e67a9d702.png)

I think that the white arrows aren't present because this method returns a value, but for this method, I don't care about the boolean value it returns. I want something equivalent to this in GDScript:

```
if condition:
	dict.erase()
```

**Steps to reproduce:** Add `Dictionary.erase()` in VisualScript and notice there's no way to run it.

**Minimal reproduction project:** https://github.com/aaronfranke/godot-demo-projects/tree/fully-visual-touch and see https://github.com/godotengine/godot-demo-projects/issues/280

**Comment by Calinou** [comment]
Is this a duplicate of #34777?

**Comment by aaronfranke** [comment]
Yes, we opened them at the same time.
