### ISSUE TITLE
Autoscroll down deactivate in output

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#37476]
**Godot version:**
3.2.1 stable mono

**OS/device including version:**
win10 64

**Issue description:**
If you print values in the "Output" window, then the window will automatically scroll so you can always see the last value printed, all OK.

But ... you finish executing the scene and scroll up in the "Output" window to see previous values, then you rerun and now the "Output" window no longer does automatic scrolling, you can no longer view values printing in real time.

To solve this you will have to manually lower the scroll of the "Output" window again towards the lower end, then now the window will automatically scroll down again when printing values.

![EasyMovement gif](https://user-images.githubusercontent.com/19652075/78080183-01cdf500-73ae-11ea-9a47-e0ef8cfa0d5f.gif)

**Steps to reproduce:**
1 - Print a large number of values ​​so that the output window must scroll down.
2 - Finish the execution and scroll the scroll of the exit window upwards
3 - Run again and print values ​​again, you can check that the output window no longer scrolls down automatically

**Minimal reproduction project:**

**Comment by Anutrix** [comment]
I always thought this was a feature. If you are at the end of scroll, it scrolls down. Else it stays where it is or stays at top.

**Comment by Torguen** [comment]
In my opinion this should not be passed as a feature.

It doesn't make sense that you are printing values and the scroll does not automatically scroll down.

**Comment by Calinou** [comment]
@Torguen Some people precisely find this to be an annoyance because you can't scroll up at all if values are being printed continuously.

**Comment by Torguen** [comment]
I think the behavior could be:

1 - The scroll at the beginning of each execution ALWAYS automatically scrolls down if you print values.
2 - You can upload the scroll and this will make the scroll stop automatically scroll down until the next execution.

**Comment by kimjiy9607** [comment]
Hi,
I am trying to work on this bug. On rich_text_label, there are validate_line_caches and int first_invalid_line which I do not understand. I tried so hard to understand but it just doesn't click.
This might be obvious for some people. If it is can you kindly tell what each one does?
Thank you so much:)
