### ISSUE TITLE
Play custom scene(quick run scene) icon remains checked

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3747]
The Icon is not releasing.
1.Press "Play custom scene buggy".
2.Close the window or "Open/select" scene. It is still showing icon_folder is pressed.

**Comment by AlexHolly** [comment]
Is this really fixed? 
1.Press "Play custom scene".
2.Press close or X it is still checked.

**Comment by akien-mga** [comment]
It's working for me in the master branch.

**Comment by neikeq** [comment]
Ops... I forgot one line :|
