### ISSUE TITLE
Visual Script dictionary erase is not sequenced.

### ISSUE THREAD

**Issue by fire** [godotengine/godot#37477]
**Godot version:**
3.2.1-stable

**OS/device including version:**
win 10

**Issue description:**
Dictionary erase in Godot isn't sequenced so the order is undetermined.

@swarnimarun @kidrigger I think it's just a boolean that isn't selected.

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/32321/78080137-72e7bb00-7362-11ea-9b25-4ead01b51ac6.png)

Array erase does it properly.

**Minimal reproduction project:**
[New Game Project.zip](https://github.com/godotengine/godot/files/4411809/New.Game.Project.zip)

**Comment by bojidar-bg** [comment]
Basically, it should be marked `ADDFUNC1RNC` here:
https://github.com/godotengine/godot/blob/ff14d071ccfdf25b899ab49312ef639da7c71fd6/core/variant_call.cpp#L1960
