### ISSUE TITLE
Graphical artifacts when shadow is off

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#37499]
**Godot version:**
3.2.1 

**OS/device including version:**
5.5.13-arch2-1

**Issue description:**
Graphical artifacts appear, but disappear when shadows a are enabled 

**Steps to reproduce:**
Open some project and look at a mesh
![Peek 2020-04-01 17-50](https://user-images.githubusercontent.com/60042618/78159085-5cb12c00-7442-11ea-9958-bdf8f96e939f.gif)

**Comment by clayjohn** [comment]
Is this GLES3or GLES2? And are you using your own shaders or are you using SpatialMaterials?

**Comment by Calinou** [comment]
Also, which graapics card and driver are you using?

**Comment by JupiterRider** [comment]
@clayjohn GLES3 and SpatialMaterials

@Calinou 
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290/390] (rev 80)
        Subsystem: PC Partner Limited / Sapphire Technology Sapphire Nitro R9 390
        Kernel driver in use: amdgpu
        Kernel modules: radeon, amdgpu

Name            : xf86-video-amdgpu
Version         : 19.1.0-1

Name            : mesa
Version         : 20.0.2-1
```

**Comment by JupiterRider** [comment]
The issue came after any Archlinux update and gone after any Archlinux update.
