### ISSUE TITLE
LineEdit min width

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37493]
**Godot version:**
3.2.1

**Issue description:**
LineEdit seems to have minimal width that comes from nowhere. I tried to make a one-character-big LineEdit, but it's impossible even with `max_length` of 1.
![VpRLjQ4U3L](https://user-images.githubusercontent.com/2223172/78146964-261fe500-7433-11ea-88e1-d53c2e4d027b.gif)

**Steps to reproduce:**
1. Add LineEdit
2. Try to shrink it

**Comment by bojidar-bg** [comment]
Try changing the "minimum_spaces" constant.

**Comment by KoBeWi** [comment]
Nevermind 🙃
