### ISSUE TITLE
TileSet Editor collision display error in the case of  isometric tile

### ISSUE THREAD

**Issue by colorworlds** [godotengine/godot#37496]
**Godot version:**
3.2
**OS/device including version:**
win7
**Issue description:**
I create a isometric tile in a scene like this:
[screenshot](https://s1.ax1x.com/2020/04/01/G8yBkT.png)
then,I convert it to a tileset.
but when I open the TileSet Editor I find that the collision of tile moved to the top left:
[screenshot](https://s1.ax1x.com/2020/04/01/G86luR.png)
however when it's used, it's all right.
The trajectory of the rigid body draws its collision shape:
[screenshot](https://s1.ax1x.com/2020/04/01/G8gPwq.png)
[screenshot](https://s1.ax1x.com/2020/04/01/G8gSyj.png)
[screenshot](https://s1.ax1x.com/2020/04/01/G8gpOs.png)

**Comment by Calinou** [comment]
@colorworlds Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
