### ISSUE TITLE
OptionButton popup does not follow OptionButton into negative coordinates

### ISSUE THREAD

**Issue by VoidMagick** [godotengine/godot#37507]
**Godot version:**
v3.2.1

**OS/device including version:**
Windows 10.0.18363

**Issue description:**
Popup appears offset away from the OptionButton instead of directly underneath.

**Steps to reproduce:**
Create and interface in 2D, add camera so that instead of the origin 0,0 being in the top left, it's centered in the screen. Add an OptionButton to the top left of the origin (-x and -y space).

Pressing the OptionButton, the popup will appear down by the origin 0,0.

![godot_optionbutton](https://user-images.githubusercontent.com/60553754/78179089-439a8200-7426-11ea-98b8-88f4b8c398df.png)

**Comment by ThakeeNathees** [comment]
(on Windows10) try right click on colorpicker color hex value

![context menu placement](https://user-images.githubusercontent.com/41085900/78199502-78035200-74a9-11ea-9d2a-d3b80299fa65.png)

**Comment by FeralBytes** [comment]
I managed to overcome this issue by catching the on_pressed() signal then using this code.
`gdscript
func _on_OptionButton_pressed():
    get_child(0).rect_global_position = rect_global_position + Vector2(0, rect_size.y)
`

**Comment by Sauermann** [comment]
I am unable to replicate this issue in v4.1.beta3.official [ada712e06].
Have tested it with embedded Windows and without embedded Windows.

**Comment by akien-mga** [comment]
Closing as fixed.
