### ISSUE TITLE
[code] does not set a monospace font as expected

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3750]
The code that parses the ``[code]`` tag when displaying the in-editor help claims to be setting the font to a monospaced one [1], but it does not appear to be working.

See e.g., after adding the tag in this method:
![spectacle tj1713](https://cloud.githubusercontent.com/assets/4701338/13123848/9b52c13e-d5be-11e5-84b3-87d0815f0b46.png)

The output in the editor:
![spectacle bc1713](https://cloud.githubusercontent.com/assets/4701338/13123882/c853ad2e-d5be-11e5-90d5-d7c262ad745a.png)

No particular formatting is visible.

[1] https://github.com/godotengine/godot/blob/master/tools/editor/editor_help.cpp#L1204-L1209

**Comment by akien-mga** [comment]
Just to be sure, I tested with just _one_ word within the ``[code]``/``[/code]`` tags, but the result is the same.

**Comment by bojidar-bg** [comment]
:+1:, please fix :smile:

**Comment by reduz** [comment]
yeah this is a mess, I'm going to add variable size fonts soon to attempt
to solve the problem

**Comment by neikeq** [comment]
DynamicFont was already added. What's the progress on this?

**Comment by akien-mga** [comment]
It works fine for both `[code]` and `[codeblock]` in the in-editor help now. (`[codeblock]` is still not display in a nice way, but this very bug is fixed).
