### ISSUE TITLE
changing dictionary size during iteration doesn't raise an error/warning

### ISSUE THREAD

**Issue by Axeltherabbit** [godotengine/godot#37511]
**Godot version:**
3.2.1.stable.custom_build - Aur
**OS/device including version:**
Linux 5.5.10-arch1-1  x86_64 GNU/Linux

**Issue description:**
```
for key in dict:
   dict.erase(key)
```
it doesn't raise any error or warning, I know I can use  `for key in dict.keys()` but I should at least see a warning

**Comment by Calinou** [comment]
Duplicate of #32261.
