### ISSUE TITLE
Open inspector tabs by hovering over them during drag and drop

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#37524]
**Godot version:**
3.2.1

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
It's been a few times now that I've tried to drag a script onto an object only to realize that the script area is folded. Then I have to stop dragging the script, unfold the tab, then drag the script again.

![2dcc9b45](https://user-images.githubusercontent.com/14253836/78265697-6da58000-74ca-11ea-8b9f-4a34a02983da.gif)

While it is a small thing to complain about, it can break the flow of work

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
I suppose we have to add some kind of timer so you can't accidentally unfold all sections while trying to reach a section at the bottom of the inspector.
