### ISSUE TITLE
No way to edit/create built-in AnimatedTextures in TileSet

### ISSUE THREAD

**Issue by NedAlex94** [godotengine/godot#37522]
**Godot version:**
3.2.1
**OS/device including version:**
Windows 10
**Issue description:**
I cannot access the following menu in Godot 3.2.1. In Godot 3.2 and lower it appear simply by clicking on a TileSet in the editor.

Here is a picture of what I am talking about. How it looks in Godot 3.2 and lower

![immagine](https://user-images.githubusercontent.com/17100058/78263026-b6c4f680-7501-11ea-8b27-a73e9851a8e1.png)

And there is how it looks in Godot 3.2.1 
![immagine](https://user-images.githubusercontent.com/17100058/78263145-e07e1d80-7501-11ea-9155-c147f1235f14.png)

_Bugsquad edit:_ See https://github.com/godotengine/godot/issues/37522#issuecomment-608353979 for relevant info

**Comment by KoBeWi** [comment]
They were hidden on purpose, see #35908

**Comment by NedAlex94** [comment]
I understand. However, I cannot figure this out.
I cannot seem to find the AnimatedTexture proprieties, especially for those animations made in the previous Godot versions. I cannot seem to make new AnimatedTextures either.

Can you help me?

**Comment by KoBeWi** [comment]
I think you need to save the AnimatedTexture as a Resource and edit its properties outside tileset.

**Comment by NedAlex94** [comment]
Thanks for the answer.
Does not seem to work. All the previous animations are inaccessible, and new animations in previously made TileMaps don't work either.

I will keep editing them in 3.2 while using future version for the rest. Hopefully it won't break anything.

**Comment by KoBeWi** [comment]
@NedAlex94 Could you send some example scene with animations from 3.2?

**Comment by NedAlex94** [comment]
> 
> 
> @NedAlex94 Could you send some example scene with animations from 3.2?

Of course. 
[AniamtedTilset.zip](https://github.com/godotengine/godot/files/4426180/AniamtedTilset.zip)

I made a new project. It is a Tilemap with animated textures made in 3.2 (the puddles are animated). Can you edit the frames in 3.2.1?

**Comment by KoBeWi** [comment]
Ok, it's impossible. The AnimatedTexture is a sub-resource inside the scene and there's no way to access it without inspecting the TileSet.

There's a workaround for this though. You can open the project in 3.2, right-click the AnimatedTexture in the inspector and save it as file. Then you will be able to edit it in 3.2.1 via the resource file.

This basically means that you can no longer create built-in AnimatedTextures for TileSet, but you need to keep each of them in a file (I assume previously you created them via inspector). I can re-open this issue as a usability problem if you want.

**Comment by NedAlex94** [comment]
> 
> 
> Ok, it's impossible. The AnimatedTexture is a sub-resource inside the scene and there's no way to access it without inspecting the TileSet.
> 
> There's a workaround for this though. You can open the project in 3.2, right-click the AnimatedTexture in the inspector and save it as file. Then you will be able to edit it in 3.2.1 via the resource file.
> 
> This basically means that you can no longer create built-in AnimatedTextures for TileSet, but you need to keep each of them in a file (I assume previously you created them via inspector). I **can re-open this issue as a usability problem if you want.**

I think that would be great! I loved the way it was handled before, and we used AnimatedTextures a lot.

**Comment by akien-mga** [comment]
Fixed by #60770.
