### ISSUE TITLE
math/octree.h: Condition ' Math::is_nan(p_aabb.size.x) ' is true

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3752]
Seen when closing the editor with a project open:

```
ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core/math/octree.h:827.
```

(printed 6 times in a row, if that can give a clue as to what triggers it)

**Comment by AlexHolly** [comment]
+1
Also 6 times on close project.
#3521

**Comment by henkz1** [comment]
Another clue is that it only happens for 2d projects, but if you switch to 3d tab before closing it won't happen. I guess it's nan because it have never been set.

**Comment by alexolin** [comment]
+1 
this print in console when opening project.

**Comment by AlexHolly** [comment]
Can't see the error anymore.

Tested on ubuntu

**Comment by bojidar-bg** [comment]
@AlexHolly Ahem. Which version of Godot did you test?

**Comment by AlexHolly** [comment]
2.1 ~2 weeks old

**Comment by akien-mga** [comment]
Closing as fixed.

**Comment by justinluk** [comment]
I'm experiencing this error message being printed 15+ times upon opening my project. Using 3.0.3-rc3. Any  idea what causes it?

**Comment by volzhs** [comment]
it's because of 0 width or height of node.
especially scaled (0,0) node in my case.

**Comment by justinluk** [comment]
Is there a way to find out which nodes are causing the error?

**Comment by volzhs** [comment]
that's an interesting question.
I'm not sure which is better between avoiding this error or showing what node causes this.

**Comment by Zireael07** [comment]
@volzhs: showing what node is the cause would be better, since 0 width or height is likely to break other things, too

**Comment by justinluk** [comment]
I'm a little in the dark, in this case but let me know if anyone needs anything from me to figure out a solution. I'm happy to help if I can.

**Comment by volzhs** [comment]
then we should open another issue not to forget about this or reopen this one.
@akien-mga what do you think?

**Comment by mr746866** [comment]
Facing the same issue after I imported some transparent png images.

**Steps to reproduce:**
1. Create new scene
2. Add a sprite
3. Load texture from a transparent png file

The issue doesn't happen for other image files. Also the problem happens only in one of my projects. If I create a new project and use the same png file there, the issue doesn't arise. I think it may be related to corrupted import files.

**OS:** Mac OS 10.13.5 (High Sierra)
**Godot Editor:** 3.0.4.stable

**Comment by KevinStephens** [comment]
This is error is showing up in my project, but as yet does not appear to be disrupting execution. I am not certain what changes I've made to cause it, and I do not know of steps to reproduce it from scratch.

I believe that reopening this issue or opening another one (as suggested by @volzhs ) is in order given the number of people that appear to be experiencing this in stable versions of the editor. Thoughts, @akien-mga ?

**OS:** Mac OS 10.13.6 (High Sierra)
**Godot Editor:** 3.0.5.stable

**Comment by akien-mga** [comment]
The original bug report was about a very specific reproducing scenario where this message was printed 6 times when opening, and 6 times when closing, *any* project. This has long since been fixed, which is why this issue is closed.

The same error message in current builds doesn't mean that the same bug came back, but that another bug is triggering a similar symptom, and as such it would be better to open a new bug report for it.
