### ISSUE TITLE
Animation frames excluded in baked animation with .fbx and .glb 

### ISSUE THREAD

**Issue by Xekkel** [godotengine/godot#37535]
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
Godot doesn't import all key frames of baked animations on bones, when using .fbx or glb formats.

**Steps to reproduce:**
1. Create any exported animation file that contains an armature/rig with key framed animations, baked onto every frame. (Can be as simple as a single bone/joint, and any geometry attached.
2. Drop exported .fbx or glb file into Godot project folder and open project.
3. Double click file and click "New Inherited" when prompted.
4. Go to animation play and see all the missing key frames.

**Minimal reproduction project:**
1. In Blender(Or whatever software you use for your workflow): Create a bone. Create cube.
2. Apply automatic weights to cube.
3. Animate bone to 'wiggle' back and forth every frame.
4. Export animation and geometry using .fbx or .glb.
5. Import into a new project folder for Godot.
6. Double click file and click "New Inherited" when prompted.
7. Go to animation play and see all the missing key frames.

**Comment by akien-mga** [comment]
Is this still reproducible in the current Godot releases? (3.5 beta 3 and 4.0 alpha 6)

**Comment by Xekkel** [comment]
> Is this still reproducible in the current Godot releases? (3.5 beta 3 and 4.0 alpha 6)

Hi Akien,

I apologize for not coming back to this sooner. This can be closed. I figured out the problem was with the import settings. They aren't naturally at 60fps. So, that needed to be adjusted to match the animation frame rate. 

Thank you for looking into it.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/3442, which was addressed in `master` by increasing the default animation import rate.
