### ISSUE TITLE
Curve baked points not respecting parent node (local space only?)

### ISSUE THREAD

**Issue by TheOnlyJoey** [godotengine/godot#37538]
**Godot version:** 3.2.1

**OS/device including version:** Ubuntu 18.04

**Issue description:** When using a curve and getting the point positions with get_baked_points, it seems to report the positions in local space, not respecting orientation or position of the child node.
I have played around with workarounds but could not find anything sensible.
Reporting the curve points in world space (optionally, or by default) seems like me to be a desired result.

**Steps to reproduce:** Add Spatial, create path as child node, draw a curve, rotate the Spatial 90 degrees, the points reported by get_baked_points will report the local points without the rotation of the parent.

**Comment by TheOnlyJoey** [comment]
Seems rotation can be converted by Node3D::to_global, but parent position is still wrong.
Regardless of moving the Curve, i still get the original locations.

**Comment by akien-mga** [comment]
Conversion from local to global position seems to work fine for me in a quick test (using 2D):

[Test Curve pos.zip](https://github.com/godotengine/godot/files/4432499/Test.Curve.pos.zip)

Could you provide a project that reproduces the issue you have?

**Comment by TheOnlyJoey** [comment]
[curve_test.zip](https://github.com/godotengine/godot/files/4434478/curve_test.zip)

So in this setup you can see that when using local coordinates, it ignores the offset from the parent, and with using global coordinates, it does not take the parent's rotation into consideration.

**Comment by akien-mga** [comment]
The problem is that you're using `to_global()` in the `MeshInstance` script, so it uses the transform of `MeshInstance` to compute the global coordinates.

Since it's the `Path` node itself that you transformed, you should call `to_global` on it:
```
tcube.global_transform.origin = $Path.to_global(i)
```

You might also be running into issues because you set up global position of a node which has not yet been added to the scene tree, as you call `add_child` as deferred. In your test project, the engine raises error about it.

This works fine for me:
```gdscript
extends MeshInstance

var testcube = preload("res://TestCube.tscn")

func setup():
	var path_points = get_node("Path").curve.get_baked_points()
	for i in path_points:
		var tcube = testcube.instance()
		#get_parent().call_deferred("add_child", tcube)
		get_parent().add_child(tcube)
		
		#Using local position
		#tcube.global_transform.origin = i
	
		#Using global position
		tcube.global_transform.origin = $Path.to_global(i)

# Called when the node enters the scene tree for the first time.
func _ready():
	call_deferred("setup")
```

[curve_test.zip](https://github.com/godotengine/godot/files/4436416/curve_test.zip)

**Comment by TheOnlyJoey** [comment]
Ah my bad, really used to coordinate conversions being global functions so did not really think about on what level to call it.
I think i might have missed this in the documentation?
