### ISSUE TITLE
Detect when the player touch the screen but not on when he touches TouchScreenButton

### ISSUE THREAD

**Issue by wannabewallaby** [godotengine/godot#37534]
Godot Engine 3.2

I want to be able to detect when the player touches anywhere the screen except for TouchScreenButtons. I've seen that if it was normal Buttons, it would work fine by using _unhandled_input, but that's not the case.
Is there any way to do that withou needing to check one by one on positions, etc?

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
