### ISSUE TITLE
Please stop making Ubuntu Package management unusable!

### ISSUE THREAD

**Issue by SourceSkyBoxer** [godotengine/godot#37546]
Hello everyone, 

I am very disappointed because scons said like this:
I should change to Python 3.6 because it said like this
![image](https://user-images.githubusercontent.com/57066679/78352904-76b94e80-75a9-11ea-93fd-6a47f47f9473.png)
Than I change via update-alternative with python to installed latest python version
Than scons build successfully.

Than I want get sudo apt update -y tha it throws
```
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 8, in <module>
    from CommandNotFound.db.creator import DbCreator
ImportError: No module named 'CommandNotFound'
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code
```

Please stop making my Ubuntu unusable!
I don't want reinstall Ubuntu version because It has hard work for rocm dkms with AMDGPU.

PLEASE TELL ME!
How do I fix if I change Python version from update-alternative if scons said "Python 3.5 or greater but you have Python 2.7.17"

Why does it not work. Please help me - I want fix with working apt command. If you make unusable my Ubuntu than I will report police because you make my Ubuntu badly.

I really hate problem with apt if changing python version.
Please calm me! I want stay my Ubuntu default. I don't want reinstall again.

Thank you for understanding!

**Comment by akien-mga** [comment]
We're not making Ubuntu package management unusable...

If you have a problem with apt after changing your Python alternatives, you should refer to the Ubuntu documentation and/or report a bug to Ubuntu. This has nothing to do with Godot.

**Comment by akien-mga** [comment]
Note that you were already using a `venv`, so you don't have to change your default Python version, you should just create and use a Python 3 `venv` (Ubuntu should support having both Python 2.7 and Python 3.x installed in parallel).

**Comment by SourceSkyBoxer** [comment]
OK thanks I will try

**Comment by SourceSkyBoxer** [comment]
Now I calm my resinstalling of Ubuntu 18.04.4 

Now I can't expect that if I change with virtualenv of Python. But it won't work .. Why does it always force??

1. Clone from Github: 
2. Change directory to godot
3. Create virtualenv for Python when you have parallel python installations under Linux and macOS
`virtualenv -p /usr/bin/python3.6 .`

4. Change to virtual directory
`source ./bin/activate`

5. Check current version of python
`python --version`

Result: It looks safe because in venv with current version of python.
```
(godot) jens@jens-desktop:~/Build-Developments/godot$ python --version
Python 3.6.9
```
6. Try with Godot's sconsript
`scons platform=linuxbsd use_llvm=yes use_lto=yes target=release_debug -j32`
Yeah but scons won't but why?
Result looks like crazy.
```
scons: Reading SConscript files ...
Python 3.5 or greater required, but you have Python 2.7.17
(godot) jens@jens-desktop:~/Build-Developments/godot$
```
Why does it not work now? Please tell me - I already tried. No success....

**Comment by ni-code** [comment]
I'm getting the same issue on solus linux when compiling master, although it works fine when I try to compile older branches such as 3.2.

The way I managed to workaround this is by using an alias to force the use of python 3.

alias scons="/usr/bin/env python3 $(which scons)"

@SourceSkyBoxer 
It should also work for you in ubuntu

**Comment by SourceSkyBoxer** [comment]
Wow it works well thank you for magic!

**Comment by fregate** [comment]
> alias scons="/usr/bin/env python3 $(which scons)"

Think it should be in the official godot "Compiling from source" doc

**Comment by Calinou** [comment]
> Think it should be in the official godot "Compiling from source on Ubuntu" doc

The proper way to fix this is to add `$HOME/.local/bin` to your `PATH` environment variable. pip will warn you about this if you run `pip3 install --user --upgrade scons` but `$HOME/.local/bin` is not present in your `PATH` :slightly_smiling_face:
