### ISSUE TITLE
Editor crash on exit due to not unregistered callbacks

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#37548]
**Godot version:**
v4.0.dev.custom_build.af443dff4

**OS/device including version:**
Windows 10 1903

**Issue description:**
Editor crashes without backtrace on exit, because a deleted window recieves an event. (WM_UNFOCUS).

**Steps to reproduce:**
1. Open the editor
2. Close the editor

**Comment by reduz** [comment]
I cant reproduce this, could anyone else verify?

**Comment by HaSa1002** [comment]
The root of the issue is the binding of INVALID_WINDOW_ID to some callbacks.

**Comment by HaSa1002** [comment]
I cannot access my workstation currently so I cannot test whether or not it still happens. Last time this happend on other events too. Like focus/unfocus. But again that was I think all because of what I wrote above

**Comment by HaSa1002** [comment]
Was fixed along the way
