### ISSUE TITLE
No error when assigning wrong type to onready var

### ISSUE THREAD

**Issue by arthurkehrwald** [godotengine/godot#37545]
**Godot version:** 3.2.1

**OS/device including version:** Windows 10 64bit

**Issue description:** It is possible to assign values of the wrong type to statically typed onready vars in the same line they are declared. When assigning the same value in the _ready() function, you do get an error.

**Steps to reproduce:** Make a scene with two nodes of the basic node type, one a child of the other. Then attach this script to the parent node:
 ```
extends Node

onready var spatial_node: Spatial = get_node("Node")

func _ready():
	spatial_node = get_node("Node")
	var pos = spatial_node.get_global_transform().origin
```
Two lines assign the same value to the same varible, but only the one in `_ready()` throws an error.

**Minimal reproduction project:** [TypedOnReadyBug.zip](https://github.com/godotengine/godot/files/4425619/TypedOnReadyBug.zip)

**Comment by ThakeeNathees** [comment]
I don't think this is a bug, and that's why the line is marked as unsafe.
since the `get_ndoe("some_string")` could return any type of node which could only be
determine at run time
