### ISSUE TITLE
Cannot compile Godot 4.0 on MacOS

### ISSUE THREAD

**Issue by rafaelgdp** [godotengine/godot#37550]
**Godot version:** Godot master branch, commit aeb95ef006109cbebc1a7d1e15f09e509c864583

**OS/device including version:** MacOS Catalina.

**Issue description:** Some of the commits of the past weeks or so (I have not identified which one specifically) rendered my compilation unsuccessful on my machine. If I roll back commits from weeks ago I can compile, but not the latest. I noticed there was a bump from Python2 to Python3 in the SConstruct file, but I managed to change my python environment variable to be able to successfully trigger the scons command. Apparently, there is a .cpp file missing. Particularly, this one:

`main/default_controller_mappings.gen.cpp:3:10: fatal error: 'main/default_controller_mappings.h' file not found
#include "main/default_controller_mappings.h"`

Am I doing something wrong?

Here is a screenshot of my scons command:

![image](https://user-images.githubusercontent.com/9672536/78378222-0f9a9a80-75a7-11ea-8832-665765c01213.png)

 
**Steps to reproduce:** Run scons normally on a macos machine.

**Minimal reproduction project:** NA

**Comment by giarve** [comment]
Deleting `main/default_controller_mappings.gen.cpp` and then compiling again will be enough.

**Comment by akien-mga** [comment]
It's actually the `.gen.cpp` file that should be removed.
