### ISSUE TITLE
Export project to windows reuses existing files from previous export

### ISSUE THREAD

**Issue by h4de5** [godotengine/godot#37568]
**Godot version:** v3.2.1

**OS/device including version:** Win 10

**Issue description:** Exporting to windows does not rebuild the game, but reuses previously exported game code

**Steps to reproduce:**
1. send "this is a test" to stdout using print
1. create an export present for HTML, set the export path to "dist/test.html"
1. create an export present for windows, set the flag "Embed Pck" [x] and set the export path to "dist/test.exe"
1. click on "export all" and export in debug mode
1. test the exported executable to see if "this is a test" is shown
1. now change the text to "this is another test"
1. export the game just for windows using the "export project" button
1. when saving the file, godot should tell you that the file does already exist
1. confirm to overwrite that file
1. test the exported executable and still see the old text
1. export all presents at once, test the binary - and see that the text has finally changed

**expected behaviour**
- When exporting a single present, it should rebuild the binary completly using the current game code

**Minimal reproduction project:**
[godot-exporttest.zip](https://github.com/godotengine/godot/files/4430371/godot-exporttest.zip)

screencast of how to reproduce the problem:
![2020-04-04_011254_x_jZcf](https://user-images.githubusercontent.com/6115324/78412671-828e2a80-7614-11ea-9af9-59e010067310.gif)

My guess is, that the pck file from the HTML export is somehow reused instead of recreated when exporting to windows only. The problem does not occure if I export all presents, if I have different names in the export paths, or if I do not activate "Embed Pck".

**Comment by Calinou** [comment]
Maybe it's because Godot prefers loading the PCK file with the same name as the binary instead of the embedded PCK.

**Comment by h4de5** [comment]
you're absolutly right. so its just a runtime problem and not the actual export ...
was pulling my hairs out yesterday ..

is this behaviour known/intended? or should I rephrase the issue?

**Comment by Calinou** [comment]
@h4de5 I don't think this behavior is intended, it's probably an oversight.
