### ISSUE TITLE
OS.get_time_zone_info() does not adjust bias during DST

### ISSUE THREAD

**Issue by Beefster09** [godotengine/godot#37571]
**Godot version:** 3.2

**OS/device including version:** Windows 10

**Issue description:** When calling OS.get_time_zone_info() during part of the year when DST is active, the bias field returned does not take daylight saving time into account, so for instance, Mountain Daylight Time reads as a bias of 420 (7 hours) instead of 360 (6 hours). A bias of 420 would be correct for the standard time part of the year, but is incorrect when DST is active.

**Steps to reproduce:** Call OS.get_time_zone_info(), print the result to console, and observe the incorrect bias.

**Minimal reproduction project:** Any project will do.

**Comment by Calinou** [comment]
It seems to be taken into account on Linux. I live in France (which is GMT+1), and I get the following on Linux: `{bias:120, name:CEST}`

This is probably OS-specific. Further testing on macOS, mobile and HTML5 is welcome.

**Comment by michasng** [comment]
I'm on windows 10 in germany. Should be getting a bias of 120 as well right now, but I get this:
`{bias:60, name:Mitteleuropäische Sommerzeit}`
(Also note that `CEST` has been automatically translated for me.)

Exporting to the web results in this:
`{bias:120, name:GMT}`
Now `GMT` is wrong, but the bias is correct.

**Comment by jamie-pate** [comment]
Workaround:

```
# Get time zone info with a bug fix for windows time zone issues.
func get_time_zone_info_fixed() -> Dictionary:
	var result = OS.get_time_zone_info()
	if OS.get_name() == "Windows":
		var output = []
		OS.execute('WMIC.exe', ["OS","Get","CurrentTimeZone"],true, output)
		var bias = int(output[0].split("\n")[1])
		result.bias = bias
	return result
```

**Comment by bati22** [comment]
I tried to reproduce the bug, but failed. Maybe it's because it's winter time.
![17](https://user-images.githubusercontent.com/40314986/105414505-de737f80-5c37-11eb-9342-7808218dfa4c.png)

**Comment by jamie-pate** [comment]
@bati22 afaik it only affects windows, and may only happen during Daylight Savings. You could set your computer clock to the summer to test.
