### ISSUE TITLE
Current master is not compiling on Linux 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3758]
Can't compile 16b0cf8bcbaacb02533e8f334b30931139b6d6dd on 64 bit Linux (Ubuntu).
I used ```scons platform=x11 target=release_debug -j 3``` in order to start compilation, here is an error:
```
scene/gui/item_list.cpp: In member function 'void ItemList::_notification(int)':
scene/gui/item_list.cpp:856:15: error: no match for 'operator=' (operand types are 'Vector2' and 'int')
      icon_ofs = 0; // (min_icon_size - items[i].icon->get_size())/2;
               ^
In file included from core/image.h:34:0,
                 from core/variant.h:43,
                 from core/object.h:33,
                 from ./scene/main/node.h:32,
                 from ./scene/gui/control.h:32,
                 from scene/gui/item_list.h:4,
                 from scene/gui/item_list.cpp:1:
core/math/math_2d.h:65:8: note: candidate: Vector2& Vector2::operator=(const Vector2&)
 struct Vector2 {
        ^
core/math/math_2d.h:65:8: note:   no known conversion for argument 1 from 'int' to 'const Vector2&'
scons: *** [scene/gui/item_list.x11.opt.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Hm, Travis-CI built it just fine: https://travis-ci.org/godotengine/godot/builds/109990105

It builds by default without ``target`` argument, i.e. that would be ``target=debug`` I think, so maybe release_debug is broken? I built debug just fine too yesterday.

**Comment by akien-mga** [comment]
Just to be sure, check your ``git status`` to ensure you don't have untracked files laying around.

**Comment by akien-mga** [comment]
I guess *you* modified ``scene/gui/item_list.cpp`` and broke it ;)
See https://github.com/godotengine/godot/blob/master/scene/gui/item_list.cpp#L856, there is no 0.

**Comment by kubecz3k** [comment]
@akien-mga oh my! It turns out you are right! Sorry a lot for confusion!
