### ISSUE TITLE
Can't select multiple lines in the documentation window

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#37585]
**Godot version:**
master 321ce4d4c

**OS/device including version:**
Windows 10 Pro

**Issue description:**
We can't select multiple lines in the documentation window. Instead, the window just scrolls on dragging with left click.

**Steps to reproduce:**
1. Open any documentation in the editor.
2. Try to drag more than one line to copy some text or example code.

**Comment by Calinou** [comment]
Closing in favor of #38665 as it better describes the issue at hand.
