### ISSUE TITLE
Fullscreen setting is broken

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#37588]
**Godot version:**
master 321ce4d4c

**OS/device including version:**
Windows 10 Pro

**Issue description:**
Setting the fullscreen option just makes the window of the game borderless. The size remains same and doesn't cover the whole screen.
Fullscreen unchecked:
![Screenshot (656)](https://user-images.githubusercontent.com/11459028/78459264-73bb7c80-76d5-11ea-9667-e851b0b0bea4.png)
Fullscreen checked:
![Screenshot (657)](https://user-images.githubusercontent.com/11459028/78459269-76b66d00-76d5-11ea-84bd-98a858d214fa.png)

**Steps to reproduce:**
1. Check fullscreen option in Project Settings.
2. Run the project.

**Minimal reproduction project:**
Any

**Comment by Anutrix** [comment]
Before: ![Screenshot (658)](https://user-images.githubusercontent.com/11459028/78821682-7d0b5880-79f7-11ea-9001-1831e3627b3a.png)
After Shift+F11:![Screenshot (659)](https://user-images.githubusercontent.com/11459028/78821738-97ddcd00-79f7-11ea-9406-998817f181af.png)
Issue is that input still works and it works on the window behind it. Can wreck havoc. Should be high priority issue in a way.

**Comment by KoBeWi** [comment]
For some reason this still exists in 9e34ba4 (although the PR did fix it, so it just broke again)

**Comment by Anutrix** [comment]
Anyone worked/working on this?
It can still be reproduced in latest master https://github.com/godotengine/godot/commit/41f66761fd8e41760dbffce9b9a4a4d8ceb7af0b.

**Comment by DimitriyPS** [comment]
@Anutrix Do you have multiple screens? What permission?

**Comment by Anutrix** [comment]
> @Anutrix Do you have multiple screens? What screen resolution?

Sorry about the super long delay, but no. I only have one display.

Haven't checked if it's reproducible in recent builds.

**Comment by KoBeWi** [comment]
I checked. `fullscreen` makes window borderless and `borderless` makes the window fullscreen. Looks like the flags are swapped for some reason.

**Comment by Calinou** [comment]
> I checked in [f7ca732](https://github.com/godotengine/godot/commit/f7ca732df19c968693d5d1300f54a88a71c1bf11). `fullscreen` makes window borderless and `borderless` makes the window fullscreen. Looks like the flags are swapped for some reason.

Good catch :slightly_smiling_face: 

See also my suggestion in https://github.com/godotengine/godot-proposals/issues/4413, which could resolve this issue at the same time.

**Comment by KoBeWi** [comment]
I tried to find out what causes the issue, but no luck. It's probably something in Window initialization code as setting fullscreen/borderless after initialization works fine.

Also it's not that the flags are swapped. Fullscreen makes the window borderless and it's correct, but the bug is that you need *both* fullscreen and borderless enabled for the window to be fullscreen at start.

**Comment by tinmanjuggernaut** [comment]
alpha12, two 1920x1080 screens, win10/64 gtx1060

* 1024x600, resizable => 1024x600 resizable
* 1024x600, borderless => 1024x600 borderless 
* **1024x600, full screen => 1920x1080 moveable window w/ title !!!**
* **1024x600, resizable, full screen => 1024x600 borderless window !!!**
* 1024x600, borderless, full screen => 1920x1080 full screen borderless window
* 1024x600, borderless, resizable, full screen => 1920x1080 full screen borderless window

There are two permutations that are wrong. Maybe all that is needed is for `fullscreen` to imply `borderless`, as it did in gd3. That could be a one line fix in the class that reads the options.

**Comment by KoBeWi** [comment]
Can confirm it's fixed.

Although I noticed that when you have both `borderless` and `fullscreen` enabled, it causes a weird 1px outline at the borders. But that's another issue I guess.
