### ISSUE TITLE
Attempt to connect nonexistent signal 'popup_hide' to 'SceneTreeDock::_script_creation_closed'.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#37583]
**Godot version:**
4.0.dev.custom_build. 1957c99ab
**OS/device including version:**
Ubuntu 19.10
**Issue description:**

```
ERROR: Signal 'script_created' is already connected to given callable 'SceneTreeDock::_script_created' in that object.
   at: connect (core/object.cpp:1462)
ERROR: In Object of type 'ScriptCreateDialog': Attempt to connect nonexistent signal 'popup_hide' to callable 'SceneTreeDock::_script_creation_closed'.
   at: connect (core/object.cpp:1449)

```
**Steps to reproduce:**
![jfile](https://user-images.githubusercontent.com/41945903/78453952-4222c100-7695-11ea-87fe-5689c10c57b3.gif)

**Comment by akien-mga** [comment]
Still reproducible in current `master` branch.

`ScriptCreateDialog` inherits `ConfirmationDialog`, and dialogs now inherit `Window` directly and no longer `Popup`, so they don't have `popup_hide`.

Instead they have `confirmed` and `cancelled`, but overall the logic used to connect a specific signal only when using the dialog in "Attach Script" mode, to disconnect it on close, is a bit messy. So some cleanup of this logic would be welcome.
