### ISSUE TITLE
Godot Mono C# KinematicBody2D isOnFloor() doesn't work

### ISSUE THREAD

**Issue by RuiPDeJe** [godotengine/godot#37593]
**Godot version:**
Godot Mono v.3.2.1

**OS/device including version:**
Windows 10 1909

**Issue description:**
isOnFloor() method from KinematicBody2D doesn't seems to work in godot mono while using C#.

**Steps to reproduce:**
Check isOnFloor() result

**Minimal reproduction project:**

**Comment by aaronfranke** [comment]
Please provide a minimal reproduction project.

**Comment by NoohAlavi** [comment]
Are you calling `MoveAndSlide()` and setting the floor normal? Because If you don't, it won't detect `IsOnFloor`

**Comment by RuiPDeJe** [comment]
> Are you calling `MoveAndSlide()` and setting the floor normal? Because If you don't, it won't detect `IsOnFloor`

Yes, I set a normal vector(0,1) called vDefault (for normal floor)

> Please provide a minimal reproduction project.

Here _
`using Godot;
using System;

public class cs_PlayerMotor : KinematicBody2D
{
    // Instance & variables
    public static Vector2 velocity = new Vector2(0,0);
    public Vector2 vDefault = new Vector2(0,1);
    Boolean canDoubleJump = false;
    int speed;
    int jump;
    int gravity;
    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        // Initialize values
        speed = 200;
        jump = 500;
        gravity = 25;
    }

    public override void _Process(float delta)
    {
        // Simple gravity effect
        velocity.y += gravity;
        // Horizontal slide
        velocity.x = getDirection() * speed;
        // Apply velocity effect
        velocity=MoveAndSlide(velocity,vDefault);
        
        // Jump and double jump
        if((isOnFloor() == true) && Input.IsActionJustPressed("ui_up") == true) // Check if player can jump
        {
            velocity.y = -jump; // jump
            canDoubleJump = true;   // Allow double jump
        }
        else if(Input.IsActionJustPressed("ui_up") == true && canDoubleJump && (isOnFloor() == true)) // Check if player can double jump
        {
            velocity.y = -jump; // double jump
            canDoubleJump = false; // deny double jump
        }

    }
`

**Comment by Calinou** [comment]
@RuiPDeJe A minimal reproduction project is a *complete* project that can be imported into Godot as-is. This way, we can test the project with the same collision shapes you've used in your own project. Otherwise, we don't get a full picture of what we should be testing.

**Comment by RuiPDeJe** [comment]
> @RuiPDeJe A minimal reproduction project is a _complete_ project that can be imported into Godot as-is. This way, we can test the project with the same collision shapes you've used in your own project. Otherwise, we don't get a full picture of what we should be testing.


@Calinou 
> 
> You can compress your project into a ZIP archive and upload it here by drag-and-dropping it.


Ha un français ! Oui pardon, mon anglais est pas terrible... Je vais l'upload dans un instant

**Comment by RuiPDeJe** [comment]
Here is the project, u need to change .csproj

https://www.mediafire.com/folder/eh74tuy2nsd3i/

**Comment by RuiPDeJe** [comment]
The script is cs_PlayerMotor.cs, I used a condition if(velocity.y == 0) instead of if(isOnFloor())

**Comment by aaronfranke** [comment]
```cs
    public Vector2 vDefault = new Vector2(0,1);

        velocity=MoveAndSlide(velocity,vDefault);
```

This code fails because `MoveAndSlide` expects an up vector but you've given it a vector pointing down (+Y is down in 2D, so -Y is up). If you replace the first line with:

```cs
    public Vector2 vDefault = Vector2.Up; // Same as new Vector2(0, -1)
```

Then `IsOnFloor()` works as expected.

Fun fact: If you leave the above code as-is, you could also use `IsOnCeiling()` :)

**Comment by RuiPDeJe** [comment]
> ```cs
>     public Vector2 vDefault = new Vector2(0,1);
> 
>         velocity=MoveAndSlide(velocity,vDefault);
> ```
> 
> This code fails because `MoveAndSlide` expects an up vector but you've given it a vector pointing down (+Y is down in 2D, so -Y is up). If you replace the first line with:
> 
> ```cs
>     public Vector2 vDefault = Vector2.Up; // Same as new Vector2(0, -1)
> ```
> 
> Then `IsOnFloor()` works as expected.
> 
> Fun fact: If you leave the above code as-is, you could also use `IsOnCeiling()` :)

Oh, thank u !
