### ISSUE TITLE
Vulkan SSS Blurs background

### ISSUE THREAD

**Issue by patrickWarvene** [godotengine/godot#37597]
**Godot version:** Godot Engien v4.0.dev.custom_build.321ce4d4c

**OS/device including version:** Windows 10 Pro ver. 1903 build 18362.720

**Issue description:**
Enabling sub-surface scattering in a material will cause the background to blur slightly as well as have the mesh bleed out. 

**Steps to reproduce:**
-new scene
-add light and world environment with a sky background
-add a csgsphere3d or other object and assign a material
-enable subsurf scatter in the material options.

Here is a couple of screenshots with the bug.
![noss](https://user-images.githubusercontent.com/16790240/78465327-20cbd000-76a9-11ea-8d03-3bfe665d68cb.png)
![ss](https://user-images.githubusercontent.com/16790240/78465329-26291a80-76a9-11ea-9c90-753721d8a004.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@patrickWarvene Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by patrickWarvene** [comment]
Just enabling SSS will cause the error even if the strength is 0. It also appears to mess with the depth as Dof and transparency also do not work correctly.
[SSSBug.zip](https://github.com/godotengine/godot/files/4435660/SSSBug.zip)
