### ISSUE TITLE
Inspector UI Enhancement

### ISSUE THREAD

**Issue by mrmoon117** [godotengine/godot#37605]
Hey, developers. I know feature/enhancement requests are not accepted for the time being. But, I wanted to suggest an UI enhancement for the future, if possible.

Godot is a great game engine and has a great potential for competing with giants in near future. With that being said, I would like to tell that the "**_Inspector_**" tab in Godot seems little obstructive (please, don't be offended by use of the adjective) in my view. I don't know much about others, but the UI of the inspector breaks my attention while I am working in Godot. In the inspector tab, there are some attributes for certain nodes which have different height from others. For instance, the Sprite2D node has a texture attribute and a normal map attribute and they are much more bigger in term of their height than others. And, the texture attribute when you put some texture in it, it gives a preview and textures usually have a mixer of colors. So, I get my attention easily diverted from level designing to the inspector.

So, I would like to **suggest** if you make the height each of the attributes in the Inspector tab equal and add something like preview toggling thing to disable the preview of the texture, then I think it will fix the attention breaking aspect.

**Please pardon me if I talk something in a manner that I am not supposed to talk.**

**Comment by Ev1lbl0w** [comment]
Hey, just to say that features/enhancements are encouraged, just not on this repository. There is a dedicated repo just for that: [godot-proposals](https://github.com/godotengine/godot-proposals)

I don't know how strict this rule is, but if your issue gets closed, post it on the other repo instead.

**Comment by Calinou** [comment]
As @Ev1lbl0w, we now track feature proposals on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This is to keep feature proposals *actionable*, so we know exactly what needs to be done to improve a feature.
