### ISSUE TITLE
search and replace in selection only for single character hangs

### ISSUE THREAD

**Issue by squished-01** [godotengine/godot#37618]
**Godot version:**
3.2.1-stable.official

**OS/device including version:**
Win7

**Issue description:**
search and replace in selection only for single character hangs

**Steps to reproduce:**
create a file of text (might or might not have to be a few thousand lines), 
also contains about 5 lines of very long texts (at least 300 characters per line) containing a single character lots of times. for example, the @ in:
jfsa@kdsjf@ijL@fajd@kldsf@jfsa@kdsjf@ijL@fajd@kldsf@jfsa@kdsjf@ijL@fajd@kldsf@ .... 

ctrl+R, search for @, click selection only, highlight the 5 lines, replace all with empty string
editor hangs

**Comment by ThakeeNathees** [comment]
possible duplicate of : #37416

**Comment by squished-01** [comment]
It might be.  I forgot to mention I was replacing with an empty string.

**Comment by Calinou** [comment]
Duplicate of #37416.
