### ISSUE TITLE
Can't load some sprites in Html Godot game

### ISSUE THREAD

**Issue by KenderM** [godotengine/godot#37627]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10/ Chrome

**Issue description:**
The game work fine. but if I export to HTML5, same Sprites doesn't work. Chrome console show this message:

pollito.js:7 **ERROR**: In Object of type 'Area2D': Attempt to connect nonexistent signal 'player' to method 'Area2D.on_body_enter'.
pollito.js:7    At: core/object.cpp:1452:connect() - Condition "!signal_is_valid" is true. Returned: ERR_INVALID_PARAMETER

pollito.js:7 **ERROR**: No loader found for resource: res://player/POLLO1.png.
pollito.js:7    At: core/io/resource_loader.cpp:285:_load() - Method failed. Returning: RES()

**Steps to reproduce:**
I thing the problem is in this signal:
```
func _on_Fruta_body_entered(body):	
	if body.name == "Player":
             #some Code
```
The loader ERROR in console, is for preload textures. I thing that is other problem.

**Comment by Calinou** [comment]
@KenderM Please upload a minimal reproduction project to make this issue easier to troubleshoot.

**Comment by Calinou** [comment]
I'll close this issue as no minimal reproduction project was provided in time. The issue can be reopened if someone uploads a minimal reproduction project.
