### ISSUE TITLE
Label::_notification() crashes once in a blue moon

### ISSUE THREAD

**Issue by norton-corbett** [godotengine/godot#37622]
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
There is a rare crash in Label::_notification() on this line: https://github.com/godotengine/godot/blob/94fab213482fd944debc50e255e7b395d391cc33/scene/gui/label.cpp#L272

In some unknown situation the index being produced by the expression `i + pos + 1` will be one greater than the size of the buffer, triggering CRASH_BAD_INDEX in CowData::get().

I have no idea what actually causes this scenario. I tried to understand the code but it's pretty nebulous. I built a debug version of Godot 3.2 and eventually managed to catch the crash in Visual Studio (sorry I didn't save the stack trace). The crash happens very rarely so it is a pain to reproduce. Maybe someone who feels they understand this code could review how that index is being generated.

**Steps to reproduce:**
Pretty hard to provide a reproduction case since the crash occurs so infrequently. As a guess perhaps emitting signals from background threads has something to do with it.

In my case, I have a project where I can drag a files into the game window. The file is loaded in a background thread which eventually emits a signal. The signal is connected to a function which simply sets the label text via `Label.text = text`. About once in every 100-200 times I drag a file, the engine crashes at the line above.

As a follower of the "call_deferred fixes everything" school of thought I've modified my script to `call_deferred("set_text",)` instead and I've not yet seen another crash, though I'm not quite ready to claim the workaround since the crash is so inconsistent.

**Comment by Calinou** [comment]
> In my case, I have a project where I can drag a files into the game window. The file is loaded in a background thread which eventually emits a signal. The signal is connected to a function which simply sets the label text via Label.text = text. About once in every 100-200 times I drag a file, the engine crashes at the line above.

Please upload the project in question to make this easier to troubleshoot :slightly_smiling_face:

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
