### ISSUE TITLE
Broken MultiplayerENet w/ RPC using Linux Server runtime

### ISSUE THREAD

**Issue by sinoz** [godotengine/godot#37628]
**Godot version:** 3.2

**OS/device including version:** Ubuntu 19

**Issue description:**

MultiplayerENet with RPC doesn't work after exporting and running on Linux Server runtime. Getting the following error:

```
ERROR: _process_get_node: Condition "!F" is true. Returned: __null
   At: core/io/multiplayer_api.cpp:265.
ERROR: _process_packet: Condition "node == __null" is true.
   At: core/io/multiplayer_api.cpp:204.
ERROR: _process_get_node: Condition "!F" is true. Returned: __null
   At: core/io/multiplayer_api.cpp:265.
ERROR: _process_packet: Condition "node == __null" is true.
   At: core/io/multiplayer_api.cpp:204.
```

I build the client-and server as separate projects (thus in separate Editor instances).

**Steps to reproduce:**

1. Take sample code from below
2. Export server project to .PCK file
3. Download Linux server runtime from https://godotengine.org/download/server
4. Rename .PCK file and runtime to be the same and in the same directory
5. Run runtime as for example: `./sample-server.64`
6. Run client code

**Minimal reproduction project:**

Server:
```
extends Node

func _ready():
	var peer = NetworkedMultiplayerENet.new()
	peer.create_server(43594, 16)
	get_tree().set_network_peer(peer)
	
remote func hello_world():
	print("Hello World!")
	rpc_id(get_tree().get_rpc_sender_id(), "reply")
```

Client:
```
extends Node

func _ready():
	get_tree().connect("connected_to_server", self, "_connected_to_host_ok")
	get_tree().connect("connection_failed", self, "_failed_to_connect_to_host")
	
	var peer = NetworkedMultiplayerENet.new()
	peer.create_client("localhost", 43594)
	get_tree().set_network_peer(peer)
	
func _connected_to_host_ok():
	print("Telling server to print Hello World!")
	rpc_id(1, "hello_world")

remote func reply():
	print("Received a reply from the server to also print Hello World!")
```

**Comment by sinoz** [comment]
This broke somewhere in 3.1 or 3.2. I've just tried this on 3.0.6 and it works just fine.

**Comment by Faless** [comment]
I'm unable to reproduce with the given  minimal project (attached):
[MinProj.zip](https://github.com/godotengine/godot/files/4449874/MinProj.zip)

Worth noticing that this will not work in `4.0` branch  unless both scripts have the same number of RPC functions and with the same name (content may be different).

That said, it works for me with `3.2.1`. Weird... Can someone else give it a try?

**Comment by sinoz** [comment]
> I'm unable to reproduce with the given minimal project (attached):
> [MinProj.zip](https://github.com/godotengine/godot/files/4449874/MinProj.zip)
> 
> Worth noticing that this will not work in `4.0` branch unless both scripts have the same number of RPC functions and with the same name (content may be different).
> 
> That said, it works for me with `3.2.1`. Weird... Can someone else give it a try?

I've just tried your minimal project and I am failing to reproduce the issue as well. I've just reconstructed how I did it when that issue arose and I am also failing to reproduce the issue. It could be that I tested with two applications with incompatible scene structures which makes sense why it would fail.

**Comment by Calinou** [comment]
> It could be that I tested with two applications with incompatible scene structures which makes sense why it would fail.

We strongly recommend using the same project for both the client and server for this reason :slightly_smiling_face:

**Comment by sinoz** [comment]
> > It could be that I tested with two applications with incompatible scene structures which makes sense why it would fail.
> 
> We strongly recommend using the same project for both the client and server for this reason

The problem I have with this is that it deviates from the (industry) standard. Client-server model have always been a separated thing and I personally find it confusing to merge the two. Having master/puppet keywords helps but there needs to be a boundary. Do you assign a server to one scene and the client to another?

**Comment by Calinou** [comment]
@sinoz There are quite a few large/established games which have their client and server code in the same repository. Pretty much all of [id Software](https://github.com/id-software)'s open source codebases for instance :wink:

**Comment by maksloboda** [comment]
@sinoz Same issue in godot 3.3.2 stable with webrtc.
My server runs correctly when sever is run locally, but when i host it on the cloud (Microsoft Azure) it breaks producing same errors.

**Comment by Calinou** [comment]
@maksloboda Please open a new issue with a minimal reproduction project attached.
