### ISSUE TITLE
Tooltips vanished between 2.0 beta and 2.0 RC1 (Win 64 bit)

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#3762]
I'm not getting tooltips anywhere in the 2.0 RC1 build, but they work fine in the beta. I am using Windows 7 64 bit.

**Comment by Calinou** [comment]
I can't reproduce this on Fedora 23 with commit https://github.com/godotengine/godot/commit/cc7cca55b0a845aaac7be27265cb76ab60b7c504. I tested using a button with a tooltip defined.

**Comment by JoshuaGrams** [comment]
Yep, seems to be something about our project: open one of the demo projects and the editor tooltips show up just fine...any idea how a project could break editor tooltips?  The only setting I can find that looks relevant is display/tooltip_delay, and changing that doesn't affect anything.

**Comment by JoshuaGrams** [comment]
Yeah. For some reason Viewport::_notification(int p_what) (scene/main/viewport.cpp) stops getting notifications when you load our project. It will get called a few times when you load a new scene, either with 10,000 (NOTIFICATION_EDITOR_SETTINGS_CHANGED) or 5 or 6 which I can't identify yet. But it's not getting called continuously like it should be. I'll keep digging.

**Comment by reduz** [comment]
try editing engine.cfg for that project to look for anything tooltip related

**Comment by JoshuaGrams** [comment]
Ha. Found it. Cleared the .fscache and tooltips work again.
Not sure how they got out of sync: I made sure not to put them in version control.

**Comment by JoshuaGrams** [comment]
Or...maybe it's physics_object_picking?

https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L2326

The tooltip timer is on the fixed_process notification...

**Comment by vnen** [comment]
I believe tooltips are working fine now. If someone have problems they can comment here or create another issue.
