### ISSUE TITLE
Code editor horizontal scroll bar isn't positioned at the far left when first opening a script

### ISSUE THREAD

**Issue by TheSecurityDev** [godotengine/godot#37632]
**Godot version:** 3.2.1

**OS/device including version:** Windows 7

**Issue description:** I have a small screen. When opening a script in the code editor for the first time after opening Godot, the horizontal scroll doesn't start off at the far left. It usually is positioned around the middle. This means for every script I have to adjust the scroll position every time I open Godot. This started in v3.2.

**Comment by Calinou** [comment]
Duplicate of #33865.
