### ISSUE TITLE
Dropping file on first position under directory might put it in parent directory

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37634]
**Godot version:**
3.2.1

**Issue description:**
![sS7L7cDCEG](https://user-images.githubusercontent.com/2223172/78578073-471b7800-782f-11ea-8a3d-0a108cf36e0a.gif)
See that the line can be short and long, which might be confusing if you don't notice.

**Comment by dreamsComeTrue** [comment]
IMO, I think, when parent dir is selected as a target, it could be emphsized more clearly, like:

![image](https://user-images.githubusercontent.com/1110337/78605007-0c2f3980-785b-11ea-85b0-cc2c5740ae34.png)

**Comment by DashCell** [comment]
https://github.com/godotengine/godot/pull/42092
