### ISSUE TITLE
Loading Texture on Sprite3D not working.

### ISSUE THREAD

**Issue by stmSi** [godotengine/godot#37649]
**Godot version:** current master branch https://github.com/godotengine/godot/commit/befbdda7f269cae440640b88e3cbf8fbb7e6a614

**OS/device including version:** Manjaro Linux

**Issue description:** Both Sprite3D and AnimatedSprite3D don't show texture.

**Steps to reproduce:**

1. Create New Sprite3D node
2. Drag and Drop godot icon png on Sprite3D Texture.

**Minimal reproduction project:**

**Comment by lobinuxsoft** [comment]
The same problem in windows 10

**Comment by Na-r** [comment]
The following error messages seem to be relevant.
```
ERROR: In Object of type 'Sprite3D': Attempt to connect nonexistent signal 'changed' to callable 'TextureRegionEditor::_texture_changed'.
   at: connect (core/object/object.cpp:1274)
ERROR: Disconnecting nonexistent signal 'changed' in [Sprite3D:2929369111693].
   at: _disconnect (core/object/object.cpp:1350)
```

**Comment by Na-r** [comment]
Even after adding a new signal to fix the above errors, It seems that `Sprite3D::_draw()` is never actually called.

**Comment by clayjohn** [comment]
In master, Sprite3D relies on ImmediateGeometry, which hasn't been implemented on the Vulkan backend yet.

Ah, turns out we have two copies of the same issue, closing this one so we only have one

Please see https://github.com/godotengine/godot/issues/45304
