### ISSUE TITLE
Camera `float near; far;` private properties are defined in `minwindef.h`

### ISSUE THREAD

**Issue by sebastian-heinz** [godotengine/godot#37653]
**Godot version:** 3.2.1-stable

**OS/device including version:** win-x64

**Issue description:**
When I was creating a new module, inside the `module` folder, I used the following header:
```
#ifndef TACHY_SCENE_DEBUG_H
#define TACHY_SCENE_DEBUG_H

#include <core/os/input_event.h>
#include <core/reference.h>
#include <scene/3d/camera.h>
#include <scene/gui/label.h>

#include "tachy_scene.h"
#include "tachy_setting.h"
```
Which seems to get the cameras variables `float near; far;` confused with an existing definition.
My module folder was called `tachy`, maybe it imports camera to early?

![Capture](https://user-images.githubusercontent.com/7891178/78653356-94621d00-78f5-11ea-9010-acc4f43755bd.PNG)

![Capture1](https://user-images.githubusercontent.com/7891178/78653364-96c47700-78f5-11ea-92f8-43f55fd99f0b.PNG)

**Comment by akien-mga** [comment]
Are you including windows headers in your module code?

**Comment by sebastian-heinz** [comment]
yes I do infact have a block

```

**Comment by sebastian-heinz** [comment]
Thank you for the hint, I suppose this is a issue with how I designed it and not on godot. Again thank you for quick response and I will close this.

**Comment by akien-mga** [comment]
Yes you should be extremely careful with `windows.h`, it's a bloated mess of defines that reserve very common identifiers and do break Godot or many other big projects that need to use those common words.

You should always ensure that if you need `windows.h`, it should be included as late as possible, and ideally in `.cpp` files to avoid polluting the shared namespace.

**Comment by sebastian-heinz** [comment]
Thanks, I only use it in a single .h file so I can bind a shortcut to attach a debugger to the game.exe as it is a separate process.

```
#ifndef TACHY_DEBUGGER_H
#define TACHY_DEBUGGER_H

#if defined(WINDOWS_ENABLED)
#include <windows.h>
#include <debugapi.h>
#include <handleapi.h>
#include <processthreadsapi.h>
#include <synchapi.h>
#include <sysinfoapi.h>
#include <string>
#endif

class TachyDebugger {
public:
	static void attach_debugger() {

#if defined(WINDOWS_ENABLED)
		// Get System directory, typically c:\windows\system32
		std::wstring systemDir(MAX_PATH + 1, '\0');
		UINT nChars = GetSystemDirectoryW(&systemDir[0], systemDir.length());
		if (nChars == 0) return; // failed to get system directory
		systemDir.resize(nChars);

		// Get process ID and create the command line
		DWORD pid = GetCurrentProcessId();
		std::wstring cmdLine = systemDir + L"\\vsjitdebugger.exe -p " + std::to_wstring(pid);

		// Start debugger process
		STARTUPINFOW si;
		ZeroMemory(&si, sizeof(si));
		si.cb = sizeof(si);

		PROCESS_INFORMATION pi;
		ZeroMemory(&pi, sizeof(pi));

		if (!CreateProcessW(NULL, &cmdLine[0], NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi)) return;

		// Close debugger process handles to eliminate resource leak
		CloseHandle(pi.hThread);
		CloseHandle(pi.hProcess);

		// Wait for the debugger to attach
		while (!IsDebuggerPresent())
			Sleep(100);

		// Stop execution so the debugger can take over
		DebugBreak();
		return;
#endif
	}
};

#endif
```

But as you correctly pointed out, It was imported to early.

**Comment by akien-mga** [comment]
You can just move the implementation (and relevant includes) to a `.cpp` file instead of the header and it should be fine.

Always put all the includes you can in the `.cpp` in priority to avoid polluting the namespace.
