### ISSUE TITLE
3D elements not correctly displayed in the current version of Firefox

### ISSUE THREAD

**Issue by mvpggez** [godotengine/godot#37659]
**Godot version:**
3.1, 3.1.1, 3.2, 3.2.1

**OS/device including version:**
Ubuntu 18 and Windows 10
Firefox 74.0.1 (64Bit)

**Issue description:**
3D content is not displayed correctly in the current version of Firefox. Even older games, that worked on older Firefox versions, are showing the same problems. The 2D and control elements are displayed correctly.

The problems seems very similar to #35733, but it happens on desktop devices.

**Steps to reproduce:**    
1. Create a new project
2. Create a new scene with a Spatial as root. Select this scene as main scene.
3. Add the icon.png as a Sprite (2D) to the scene. Place it somewhere visible.
4. Add a MeshInstance with mesh and material
5. Add a Camera and let it point to the mesh
6. Export for HTML5

The result works correctly in Chromium (showing mesh, sprite and sky) while Firefox only shows the sky and the sprite.

**Comment by akien-mga** [comment]
That's likely a duplicate of #37245, which is a Firefox regression in 74, fixed in 75.

**Comment by mvpggez** [comment]
Thank you for your quick reply, I didn't see, that the issue was already adressed. I'll close this issue!
