### ISSUE TITLE
shadow_item_cull_mask is not initialized properly

### ISSUE THREAD

**Issue by Serenitor** [godotengine/godot#37650]
**Godot version:**
3.2

**OS/device including version:**
Win10

**Issue description:**
I have been looking for a way to have a sprite be illuminated by a Light2D, but NOT be rendered underneath a shadow casted by that Light2D. I got it to work by setting the Light Mask of the Sprite to a different layer than the Light2D's Shadow Item Cull Mask. I did this change while the game was running in test play. Then, after restarted the game I was perplexed to see that the effect was lost again, and the Sprite was once again darkened by the shadow.

After some testing, I was able to consistently produce the desired effect by putting this line into a _ready func:
```$Light2D.shadow_item_cull_mask = $Light2D.shadow_item_cull_mask```

I think the fact that this line makes a difference in the first place illustrates nicely that there's something wrong here.

**Steps to reproduce:**
1. Download project
2. Checkout comments in test.gd

**Minimal reproduction project:**
https://up.r00t.li/shadow_item_cull_mask_bug.zip

**Comment by Serenitor** [comment]
Happy to report that this issue no longer occurring in 3.2.3.
I am not sure if I am supposed to close as it hasn't been addressed specifically.
Hopefully it's not going to be back in 4.0.

**Comment by clayjohn** [comment]
Thanks for the follow up! We prefer to link the PR that closed it, but if we can't it's fine to just close.
