### ISSUE TITLE
KinematicBody (3D) move_and_collide() does not work as described in the documentation.

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#37651]
**Godot version:**

3.2.1.stable.official

**OS/device including version:**

Fedora 31

**Issue description:**

Documentation says "The body will stop if it collides.", but it will actually slide the body along the surface of whatever it's colliding with. From move_and_slide "If the body collides with another, it will slide along the other body rather than stop immediately", is a bit misleading at best.
If using it only as a test and then applying the collision.travel vector you get the same sliding. At further inspection I can see that the travel vector is wrong, it has tiny fractions in directions it shouldn't.

Expected behaviour: it should stop exactly on the first point of contact, no sliding or compensating for surface normal. If moving, for example (1, 0, 0) on a sloped surface the travel should be exactly (1, 0, 0) * t where t is point of entry in time, the normal should be ignored completely for the travel. Remember, this is supposed to be the travel up to the collision point and if I'm moving exactly with (1, 0, 0) it should be impossible for the y or z components to have any values.

It would be nice to have a "pure" collision testing function which does not add any response at all to the collision result, with the correct travel and remainder values implementing slide, reflection and snap responses is fairly straightforward.

Here are a couple of videos on the problem of trying to use move_and_collide() with custom collision responses for those cases where move_and_slide() is not what you want. I found when trying to find someone who has solved this.

https://www.youtube.com/watch?v=_RylZgnhPSk
https://www.youtube.com/watch?v=NSNe91lMe_Q

**Steps to reproduce:**

Add a constant movement vector against a surface with a slope.

**Comment by DragonStorm97** [comment]
https://github.com/godotengine/godot/pull/34442

**Comment by spongeboburu** [comment]
Seeing how this is a dup and the issue is tagged for the 4.0 milestone I'm closing this issue.
