### ISSUE TITLE
For loop with true iterators instead of arrays

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#3765]
Often need a simple classic "for" both "с".
Create an array and a listing of the iterator is not the best option. It's slow and consumes a lot of memory. A realization of the cycle through "while" is not always convenient.

Discuss?

**Comment by nunodonato** [comment]
for i in range(1,10) ?

**Comment by sheepandshepherd** [comment]
@nunodonato `range` currently just [generates an Array](https://github.com/godotengine/godot/blob/6a25a647b73e352f3c447cb97bdf01550be4a6cd/modules/gdscript/gd_functions.cpp#L696) with all the values, which is inefficient. The GDScript documentation says `range` *doesn't* allocate, which means it's probably supposed to create an iterator, not an array.

Custom iterators are actually implemented in Godot already in [the Variant class](https://github.com/godotengine/godot/blob/6a25a647b73e352f3c447cb97bdf01550be4a6cd/core/variant_op.cpp#L3047), but they're not documented. You can turn any class into an iterator by overriding `bool _iter_init(arg)`, `bool _iter_next(arg)`, and `Variant _iter_get(arg)`. I don't know what the arguments are for, but they seem to always contain `[self]`. [Example of one in GDScript](https://gist.github.com/sheepandshepherd/23c6f12caa0f8364118d).

Should we change `range` into an actual iterator?

**Comment by ret80** [comment]
```
for i in range(1000000): # create a huge array that is not effective

for i in range(10, 0): # instead of the [10, 9, 8, ...] becomes [0, 1, 2, ...] which also creates some difficulties
```

**Comment by akien-mga** [comment]
```
for i in range(10, 0): # instead of the [10, 9, 8, ...] becomes [0, 1, 2, ...] which also creates some difficulties
```
I believe you should use this instead:
```
for i in range(10, 0, -1):
```

**Comment by nunodonato** [comment]
the point is, it seems GDScript is trying to stay close to the python syntax (similar discussions have been happening in other issues), so in this case, too, I think it would be better to do it as python does and not reinvent the wheel. for large numbers you can use a while as it seems in python a 'for' is used to iterate over "iteratable" things :)

**Comment by akien-mga** [comment]
> for large numbers you can use a while as it seems in python a 'for' is used to iterate over "iteratable" things :)

+1. Fixing the crash of #3756 is anyway a good thing and @est31 has done a nice job in his PR. A further step would be to prevent using such big sizes for range as it's very inefficient anyway. As you say, if one needs to iterate over 1M elements, better use a while loop.

**Comment by reduz** [comment]
I thought it was working with a true iterator, the code was added to Variant to handle this, but seems I forgot to add it..

**Comment by sheepandshepherd** [comment]
> the point is, it seems GDScript is trying to stay close to the python syntax
Interesting. [Python's range()](http://pythoncentral.io/pythons-range-function-explained/) had this same situation: in Python 2 it created a list, but in Python 3 it was changed to an iterator. In Python 2 the iterator was called `xrange`.

The Python 3 way would break code that's intentionally using `range` to create an Array. Of course, a "RangeIterator" object could have a "toArray" function to replace the current `range` as well. Just depends on which API we'd rather use in Godot :)

**Comment by bojidar-bg** [comment]
Maybe we can generate an iterator only in some cases? Or make the iterator switch to Array mode whenever you change it...

**Comment by est31** [comment]
> Or make the iterator switch to Array mode whenever you change it...

That'd be an useful modification. The array allocation should only happen if you add, change, or remove elements.

I'm sure we can do better than python here.

**Comment by sheepandshepherd** [comment]
Hmm. I don't think a variable can change its own type, so changing to an Array automatically would be difficult. `range` knows nothing about the context it's called in; it's just a function with a return value (either Array or iterator).

The RangeIterator class I made now has a `to_array` method like the current `range` function. Isn't an explicit conversion better? But I can hold off on making a PR until we've discussed what we actually want GDScript's `range` to do.

**Comment by est31** [comment]
`range` could be made return a `PseudoArray` object which only allocates an actual array internally when somebody writes to it. The type to the outside always stays `Array`. So for gdscript code, there is no difference, but its far more efficient.

**Comment by sheepandshepherd** [comment]
Are the index and index-assignment operators overridable for GDScript? That would allow me to turn the iterator into a pseudo-array.

**Comment by est31** [comment]
@sheepandshepherd theoretically they can be overridden, yes (functions `get` and `set`). But modifying this in a way where nothing is broken is really hard. Think of legacy code that passes the return value of `range` to methods which have params typed `Array`.

I've added your commit to #3814 the PR is I think the best way to solve this issue. It takes a conservative approach, mimicking Python 2. It optimizes the common use case of the for loop.

**Comment by bojidar-bg** [comment]
BTW, there are some other things that _might_ <sub>(or... might not)</sub> work better with iterators, like `Node::get_children()`.

**Comment by akien-mga** [comment]
Reopening as the previous fix has been reverted.

**Comment by bojidar-bg** [comment]
I think that's closable after @reduz's recent commits...

**Comment by Giacom** [comment]
What was changed? I think this issue is still worth looking into.

**Comment by reduz** [comment]
corner case, use while() instead

On Thu, Oct 26, 2017 at 10:26 AM, Alexander Taylor <notifications@github.com
