### ISSUE TITLE
Can't debug inner classes with breakpoints

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#3766]
If the class is declared in the first script and then create it in another script, we can not put a breakpoint.

Example:
file a.gd
```
extends Node

class Test:
   var i = 0
   func _init(i):
      self.i = i # breakpoint does not work
```

file: b.gd
```
extends Node

func _ready():
   var n = get_node("../test")
   var t = n.Test.new(10)
```

**Comment by ret80** [comment]
In version 2.0:
1 Set a breakpoint (can be several)
2 Run the project
3 Catch breakpoint
4 All breakpoints are reset (they are no more)

**Comment by ret80** [comment]
Or you can like this:
1 Set a breakpoint (can be several)
2 Minimize window editor.
3 Maximize window the editor.
4 All breakpoints are reset (they are no more)

**Comment by Zylann** [comment]
It might be related, so I put it here:
When I put a breakpoint and the execution flow goes inside an inner class, the debugger is completely lost.
It doesn't switches to the file and doesn't go to the current line, and indicates the line without filename.
The console says "no loader found for resource".
![godot_debug_inner_classes](https://cloud.githubusercontent.com/assets/1311555/15994055/5e42fd5e-30f9-11e6-901a-ec39c951aaff.png)
(also there is 16-bit text displayed in 8-bit character console :p)
