### ISSUE TITLE
3D Light shader doesn't work as it should

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot#37668]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10 

**Issue description:**
I wanted to make a custom toon shader and it works with a single light, but if there are more lights their interaction is wrong. This problem isn't limited to a toon effect, it's a bug of the light shader itself.

**Steps to reproduce:**
Put a colored ball between two lights and use this simple shader with the light function copied from the documentation here:
https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/spatial_shader.html
```glsl
shader_type spatial;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;
uniform vec4 albedo : hint_color=vec4(1.0);

void fragment() 
{
	ALBEDO = albedo.rgb;
}

void light()
{
	DIFFUSE_LIGHT += dot(NORMAL, LIGHT) * ATTENUATION * ALBEDO;
}
```
Then move the lights and you will see that the lights don't add but it seems more like that one "prevails" over the other when they affect the same areas.

<a href='https://postimg.cc/MMzGH4Br' target='_blank'><img src='https://i.postimg.cc/DZX4j3wF/errore.png' border='0' alt='errore'/></a>

The image on the left seems right(but it isn't), the one on the right shows what happens if you make one light closer, if you make it even closer the ball is completely black.

**Minimal reproduction project:**
Just make a new scene and follow the instrunctions in "steps to reproduce".

**Comment by guilhermefelipecgs** [comment]
If you are trying to create a toon shader, this `DIFFUSE_LIGHT += dot(NORMAL, LIGHT) * ATTENUATION * ALBEDO;` is not the right way.

I suggest to you look at this example https://github.com/EXPWorlds/Godot-Cel-Shader/blob/master/Shaders/cel.shader.

To enable multiple lines on the example shader, just change this line `DIFFUSE_LIGHT = diffuse;` to this `DIFFUSE_LIGHT += diffuse;`

**Comment by guilhermefelipecgs** [comment]
If you want to correct your example to create a standard light behavior, do the following:
`DIFFUSE_LIGHT += max(dot(NORMAL, LIGHT), 0.0) * ATTENUATION * ALBEDO;`

**Comment by 2plus2makes5** [comment]
@guilhermefelipecgs 
1) about the toon shader, I know how to do one ;) and i tried that shader you linked and that doesn't work correctly with more lights.

2)that light function i put in the code was taken from the documentation, so if it's wrong the documentation is wrong.
Your code produce better results... but not 100% correct.

Here's an image, that toon shader on the left, your code on the right
![error2](https://user-images.githubusercontent.com/35235318/78819225-2e999200-79d6-11ea-95de-6304f21a0b9b.png)

**Comment by clayjohn** [comment]
After looking @guilhermefelipecgs's comments, it appears this is not a bug, but rather a misunderstanding. Light shaders allow you to override the standard light calculations and substitute your own custom light calculations. It is up to you to decide what those functions look like. 

In this case, the interaction of light was not "wrong". The interaction of light was exactly as you coded it. The problem is that what you coded and what you expected were two different things. That is not a bug with Godot. 

As for the documentation, the documentation is not saying "here is a line of code that will make perfect lights for your game" the line says "here is what the syntax looks like for making your own custom light"

**Comment by 2plus2makes5** [comment]
@clayjohn 
The documentation says: 

"Below is an example of a custom light function using a Lambertian lighting model" 

now i understand i was wrong expecting a similar result as the diffuse_lambert render_mode, but don't you think that line is at least a little misleading?

That light function is the only example that i'm aware of in the entire documentation so i think it should have been more clear and useful, especially considering that the light function works differently from the vertex and fragment ones.

Anyway i'm sorry for the opening a non-issue.

**Comment by clayjohn** [comment]
> now i understand i was wrong expecting a similar result as the diffuse_lambert render_mode, but don't you think that line is at least a little misleading?

Not really, it *is* an example of a lambertian lighting model. It's just a really ugly one! The benefit is that it is as simple as possible.

I have been planning on writing a full lighting shader tutorial for awhile but haven't found the time. Having more info on lighting shaders will really help clear up confusion.
