### ISSUE TITLE
Tooltip renders under window

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot#37674]
**Godot version:** 4.0 branch, commit 1222541c95

**OS/device including version:**
Linux Mint 19.3, kernel 5.3.0-45, Cinnamon

**Issue description:**
As title says. I just thought they weren't showing up at all until I unmaximized the screen. Happens with both system tooltips and Godot-styled ones.

**Steps to reproduce:**
Just compile and run a new project. Didn't make any changes to the default settings.

![1](https://user-images.githubusercontent.com/6402237/78713166-367f0680-78f0-11ea-943a-687f94fd17f0.gif)

**Comment by neikeq** [comment]
I can reproduce this as well on Ubuntu 20.04.

**Comment by pouleyKetchoupp** [comment]
Can't reproduce on Windows or Mac.
