### ISSUE TITLE
HTTPClient Headers - Discussion

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3767]
The HTTPClient makes the whole header to lower case that destroys one of my header values(linux path to a file)

https://github.com/godotengine/godot/blob/3db379376fd55a1d5851bf6172affd0765b67b7c/core/io/http_client.cpp#L310

http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

So maybe godot could provide the raw header and one that is to_lower() or leave the header as he is.

**Comment by punto-** [comment]
Is it breaking the name of the header, or the contents? The problem we were
having is that a server was sending the header "transfer-encoding:
chunked", and the engine was checking for "Transfer-Encoding".. so maybe
only the name could be made lowercase?

**Comment by est31** [comment]
The standard says that the name is case-insensitive, and the value is case sensitive. So converting only the name to lowercase is needed to be conformant here.

**Comment by AlexHolly** [comment]
It is breaking the content. I don't care about the name(key). Another example is a Token that contains upper case characters...

**Comment by AlexHolly** [comment]
Okay the first issue is solved. I have another one.

Right now I do this manually in gd but I think HTTPClient should support this.
HTTPClient::request is not doing any URL encoding see https://en.wikipedia.org/wiki/Percent-encoding

https://github.com/godotengine/godot/blob/cc7cca55b0a845aaac7be27265cb76ab60b7c504/core/io/http_client.cpp#L88

Example: http://someurl.test?path=/a b -> http://someurl.test?path=/a%20b
