### ISSUE TITLE
rect_clip_content of Control node does not clip children in all cases

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#37683]
**Godot version:** 3.2.1

**OS/device including version:** Windows 10

**Issue description:**
In some cases children and their children get displayed outside of the rect of the parent, even though _rect_clip_content_ is set to _true_ on the parent.

According to the documentation of the control class https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-property-rect-clip-content I would expect, that all children get clipped within the bounds of the clipping parent.

This happens in the following setup:

```
- Control
  - Node
    - TileMap
```

Thank you for having a look at this issue.

**Steps to reproduce:**
Create a scene according to the described setup.
Add Tiles to the TileMap that are outside of the rect of the Control node.
Set rect_clip_content on the node Control to true.
The issue is visible in the editor and when the scene is run.

**Workaround:**
Change the type of Node to Control or Node2D.

**Alternative solution:**
Change the documentation of rect_clip_content and describe this behavior.

**Minimal reproduction project:**
[ClipTileMapBug.zip](https://github.com/godotengine/godot/files/4449448/ClipTileMapBug.zip)

**Comment by Zireael07** [comment]
Probably happens because Node isn't a CanvasItem, right?

**Comment by Sauermann** [comment]
Thanks for the reply. In regard to this information, am I right to assume, that this is intended behavior?

**Comment by Zireael07** [comment]
Most likely yes, though I'm not a core contributor :)

**Comment by groud** [comment]
I would say this is an expected behavior. When you put an intermediate basic node in your hierarchy, this does reset the "transform inheritance" too. By that I mean that, in your example, the Tilemap node wont be positioned relatively to the Control node.

So I guess it is kind of expected that the rect clipping works the same way.

**Comment by Sauermann** [comment]
Thank you for confirming that this works as intended. Closing this issue accordingly.

**Comment by Sauermann** [comment]
I would like to reopen this issue and suggest to resolve this by clarifying the documentation of rect_clip_content:

`Enables whether rendering of children should be clipped to this control’s rectangle.`
should be changed to
`Enables whether rendering of CanvasItem based children should be clipped to this control's rectangle.`

If approvable, I would like to create a pull request for this.

**Comment by Calinou** [comment]
@Sauermann Feel free to open a pull request for this :slightly_smiling_face:

**Comment by Sauermann** [comment]
Will do.
I assume that  https://github.com/godotengine/godot/blob/047cdea7fa24e2e9e73a9f65064cfe97b820184c/doc/classes/Control.xml#L841 is the correct place for such a PR and that https://github.com/godotengine/godot-docs/blob/master/classes/class_control.rst is automatically generated?

**Comment by Calinou** [comment]
@Sauermann Yes, that's correct :slightly_smiling_face:
