### ISSUE TITLE
history navigation doesnt work with mouse forward and back

### ISSUE THREAD

**Issue by voidplayer** [godotengine/godot#37685]
**Godot version:** 3.2.1.stable

**OS/device including version:** debian/testing

**Issue description:** Mouses have a couple of buttons that emulates alt + left and alt + right. They are used to ease the navigation. Since you have to grab it to go to the help (ctrl + click) its very annoying that they dont work because you cant do a quick peak of the help
![](https://user-images.githubusercontent.com/1072425/45116657-aeed7680-b153-11e8-82da-ec986e5cd010.png)

**Steps to reproduce:** ctrl click on a help item. Press back or forward button. It does neither

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is implemented by #36910. I'm pretty sure I've seen other issues about this but I can't find them right now.

**Comment by KoBeWi** [comment]
Also implemented by #32071. There were issues about binding these buttons for history, but none of them is directly about scripts.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/954, as feature proposals are now tracked in the Godot proposals repository.
