### ISSUE TITLE
'EditorSettings' does not contain a constructor that takes 0 arguments

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#37687]
**Godot version:**
3.2.1 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
I tried to get/set properties from Editor settings in C# But I have this error:

`'EditorSettings' does not contain a constructor that takes 0 arguments`
**Steps to reproduce:**
```
  public class MySetting: EditorSettings
    {   
    }
```
**Minimal reproduction project:**
NA

**Comment by akien-mga** [comment]
`EditorSettings` is not a class that can be instantiated/inherited from.

It's meant to be used via the instance that `EditorInterface.get_editor_settings()` will give you (in GDScript, make it PascalCase for C#).

The `EditorSettings` documentation is not clear about that at all though, and should be improved.

**Comment by git2013vb** [comment]
I tried but I have this error:

`An object reference is required for the non-static field, method, or property 'EditorInterface.GetEditorSettings()'`

I'm missing something?

Thank you

**Comment by aaronfranke** [comment]
Please post a minimal reproduction project.

**Comment by git2013vb** [comment]
> Please post a minimal reproduction project.

No need :) Its just a attempt to read editor settings. Following @akien-mga suggestions I tried to convert gdscrit line of code in C# but with no success.. Any C# project are enough.

If you still need a project  means we are without hope :))

**Comment by aaronfranke** [comment]
Oh, wait. You're not trying to use a method in EditorSettings, you're... trying to inherit it?

This is impossible, but maybe we can make that more clear. @neikeq Can we generate the API such that this is a `sealed` class?

> Edit: I give you an hint: Its not related to any project.

It's not that it's a bug *with a specific project* (if it was, the issue would be closed).

It's that the project *reproduces a bug* in Godot.

The point of a minimal reproduction project is to make it easier for the Godot devs to reproduce the issue (saving us time). If it is possible to have a minimal reproduction project, and you are wondering if you should attach one, the answer is usually "yes".

**Comment by git2013vb** [comment]
> Oh, wait. You're not trying to use a method in EditorSettings, you're... trying to inherit it?

I tried to get/set a propery in EditorSettings. It doesn't matter to me if I have to use/inherit/somethingelse. Do you have maybe an answer? Because at this moment what I tried give me errors. 
Thanks

**Comment by neikeq** [comment]
I think the only way to access `EditorSettings` from script is from a class that inherits `EditorPlugin`:

``` C#
public class MyEditorPlugin : EditorPlugin
{
    public override void EnablePlugin()
    {
        EditorSettings editorSettings = this.GetEditorInterface().GetEditorSettings();
        editorSettings.Set("...", "...");
    }
}
```

You have to activate the plugin in the plugins dialog first.

**Comment by git2013vb** [comment]
> I think the only way to access `EditorSettings` from script is from a class that inherits `EditorPlugin`:
> 
> ```cs
> public class MyEditorPlugin : EditorPlugin
> {
>     public override void EnablePlugin()
>     {
>         EditorSettings editorSettings = this.GetEditorInterface().GetEditorSettings();
>         editorSettings.Set("...", "...");
>     }
> }
> ```
> 
> You have to activate the plugin in the plugins dialog first.

Thank you for your hint :) I will try it asap.
