### ISSUE TITLE
Clicking something in File System doesn't unfocus/deselect node in SceneTree; Risky delete key operation.

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#37697]
**Godot version:**
Godot master d89dc5794

**OS/device including version:**
Windows 10 Pro

**Issue description:**
Clicking something in File System doesn't unfocus/deselect node in SceneTree. The issue occurs when you press something like delete key. Popup to delete both selected node and file appears.
**Update**: In 3.2.1, both are still selected but only one(last selected) shows delete confirmation dialog. So, it seems like a regression.

**Steps to reproduce:**
1. Click a node in SceneTree.
2. Click a file in File System(notice node is still selected).
3. Press Delete Key.

**Minimal reproduction project:**
Any project.

**Comment by KoBeWi** [comment]
Fixed in 9b637fa
File delete confirmation only appears when file dock is focused (in which case scene tree doesn't get the Delete).
