### ISSUE TITLE
Set_axis_velocity bug

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#37692]
Godot 3.2.1
Win 7 64 bits

Set_axis_velocity does not work when velocity is Vector(0,0,0), the object continue moving.

1) Download Godot project
https://github.com/DevMagicLord/Godot3/blob/master/bugs/A/BugVelocity.zip

2) Load main scene "Spatial" 

3) Press key "X" to make cube start moving
     While cube is moving, press "C" key to call  Set_axis_velocity(Vector(0,0,0))
     This should stop object moving, but it does not work.

**Comment by Gogsi** [comment]
Seems intended to me. set_axis_velocity modifies an axis of your linear velocity. Since (0,0,0) is not really an axis it doesn't change anything. To stop you should use set_linear_velocity.

**Comment by Calinou** [comment]
Closing, as this isn't an issue with `set_axis_velocity` per se. In the future, please use one of the other [community channels](https://godotengine.org/community) for support questions :slightly_smiling_face:
