### ISSUE TITLE
Mono Unable to Find `Input` Class

### ISSUE THREAD

**Issue by NutmegStudio** [godotengine/godot#37690]
**Godot version:**
d89dc5794
**OS/device including version:**
Linux Mint 19.3
**Issue description:**
Error `Input` class not found
For example:
```C#
Input.SetMouseMode(InputFilter.MouseMode.Captured);
```

It works in GDScript
```gdscript
Input.set_mouse_mode(InputFilter.MOUSE_MODE_CAPTURED)
```
**Steps to reproduce:**
Create a C# script then use the Input class. Like `SetMouseMode`.

**Comment by Calinou** [comment]
Is this due to the Input -> InputFilter singleton rename?

**Comment by NutmegStudio** [comment]
If I use InputFilter it says `An object reference is required for the non-static field, method, or property 'InputFilter.SetMouseMode(InputFilter.MouseMode)'`

**Comment by NutmegStudio** [comment]
Other singletons (`OS`, `Engine`) would generate a static class in C#, but `InputFilter` won't.


https://github.com/godotengine/godot/blob/c9de04b628e225e74aededb3dc0fa7b772090660/core/register_core_types.cpp#L267 This is probably why using `Input` in GDScript would work.

I'm working on a fix, lets see how it goes
