### ISSUE TITLE
The window title blinks when opening context menus

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#37709]
**Godot version:**
4.0.dev.calinou.fafb0ba06

**OS/device including version:**
Kubuntu 19.10, KDE Plasma 5.16.5

**Issue description:**
The main window becomes inactive when a context menu (not a dialog box) is opened. This is a bit annoying.

**Steps to reproduce:**
![1](https://user-images.githubusercontent.com/47700418/78866007-4fe69680-7a47-11ea-95da-f9e2d1f9e962.gif)

**Minimal reproduction project:**
—

**Comment by Calinou** [comment]
This is because context menus are opened in new windows. Can anything be done about this, or should we make context menus part of the main window again?

**Comment by dalexeev** [comment]
I think we should try to get the same behavior as in other programs.

![200409-1](https://user-images.githubusercontent.com/47700418/78867939-a6090900-7a4a-11ea-90a7-a39ed0f99d68.png)

**Comment by mhilbrunner** [comment]
This may be a duplicate of https://github.com/godotengine/godot/issues/37531

**Comment by dalexeev** [comment]
> This may be a duplicate of #37531

Yes, that is right. I reported exactly the same thing, but in other words. Sorry.
