### ISSUE TITLE
OpenGL ES 2.0 Renderer: GeForce 7025 / nForce 630a/integrated/SSE2 not working

### ISSUE THREAD

**Issue by andersongomes001** [godotengine/godot#37715]
**Godot version:**
Godot Engine v3.2.1.stable.official

**OS/device including version:**
Windows 10 
OpenGL ES 2.0 Renderer: GeForce 7025 / nForce 630a/integrated/SSE2

**Issue description:**
Godot Engine starts transparent, if I start from the terminal in fullscreen mode, open the main screen, create a new project and become transparent again
**Steps to reproduce:**

**Minimal reproduction project:**
![transparent](https://user-images.githubusercontent.com/25740574/78904005-4f073200-7a52-11ea-862e-575b057ea26c.jpg)
![process](https://user-images.githubusercontent.com/25740574/78904036-5fb7a800-7a52-11ea-8299-4cd49b936d63.jpg)

**Comment by Calinou** [comment]
I don't think the GLES2 renderer is expected to work on such an old, onboard GPU. Even if it did, it would have lots of trouble rendering the editor fast enough to make it usable.

**Comment by clayjohn** [comment]
Unfortunately I have to agree. This GPU was released around the same time as OpenGL 2.1. It probably never fully supported it. 

That being said, your drivers are more than 5 years out of date. Updating your drivers may be enough to get it to run.

**Comment by andersongomes001** [comment]
Thanks, I will try to update the drives, if it still doesn't work I will do a hardware update.
