### ISSUE TITLE
Game Crashes when resizing window

### ISSUE THREAD

**Issue by stuatk** [godotengine/godot#37711]
**Godot version:**
v3.2.1 stable official

**OS/device including version:**
Windows 10 10.0.18362 build 18362

**Issue description:**
A simple project, launch game by pressing play in the editor, then resize the window (make it smaller) causes the game to crash - editor remains fine.

**Steps to reproduce:**
Run attached project by pressing play in the editor, resize the game window making it smaller, it should crash when the window is quit small.

**Minimal reproduction project:**

[crash project.zip](https://github.com/godotengine/godot/files/4455079/crash.project.zip)

**Comment by Calinou** [comment]
Duplicate of #24702.
