### ISSUE TITLE
Help window closes when filter is selected

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#37710]
**Godot version:**
4.0.dev.calinou.fafb0ba06

**OS/device including version:**
Kubuntu 19.10, KDE Plasma 5.16.5

**Issue description:**
Help window closes when filter is selected.

**Steps to reproduce:**
![2](https://user-images.githubusercontent.com/47700418/78866779-b4562580-7a48-11ea-97b1-a429f5ebc34c.gif)

**Minimal reproduction project:**
—

**Comment by qarmin** [comment]
For me this also happens randomly with other types of windows on Ubuntu 19.10

**Comment by dreamsComeTrue** [comment]
I am confirming the same with Scene/Recent files submenu - as soon as I am hovering over it, full menu hides. Build from master, Fedora 31

**Comment by giarve** [comment]
I have found this happens on "Project -> Tools -> Orphan Resource Explorer" dropdowns too. Project dropdown closes when hovering Tools.
Probably with any type of popup and those that inherit it. 

Being the same issue as #37732, this could be a functionality programmed to allow closing dropdowns when changing the focus inside the editor and had unintended consequences like messing up all popups.
