### ISSUE TITLE
The editor crashes on exit, after taking 15 minutes to close (with debugger attached)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#37727]
Godot 4 b3310a00743d65d8baa2b5730ecfaed8bf8842a6
Windows 10 64 bits
GeForce GTX 1060 6GB/PCIe/SSE2
Compiled with MSVC

I tried Godot for the first time, running the editor on top of an empty 3.2.1 project.
After having started with a spam of:
```
ERROR: Condition "!uniform_set" is true.
   at: RenderingDeviceVulkan::draw_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:5774)
```
I created a few things in 3D, opened some popups, which worked okay, despite some lag.
Then I closed the editor. It took 15 minutes.
Then at the end those errors appeared:
```
ERROR: Condition "!F" is true. Continuing.
   at: RasterizerScene::InstanceBase::clean_up_dependencies (C:\Projects\Godot\Engine\godot_fork\servers/rendering/rasterizer.h:188)
```
And it ended up crashing here:

![image](https://user-images.githubusercontent.com/1311555/78938411-185d0600-7aaa-11ea-8834-cd8f5cd9e6f0.png)

The 15-minute wait doesnt happen again so far, but the crash keeps happening.
The project: 
[TestGodot4.zip](https://github.com/godotengine/godot/files/4458593/TestGodot4.zip)
It's possible that the project doesnt matter much, as I keep getting the crash on exit with other projects.

**Comment by Gogsi** [comment]
I also get a spam of similar messages, but no issues upon exiting

`ERROR: Condition "!uniform_set" is true.
   at: RenderingDeviceVulkan::draw_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:5780)`

Godot 5698a9ec
Windows 10 64 bit
Intel i5 8250u
NVIDIA GeForce MX150
 Compiled with MSVC

**Comment by corjohnson** [comment]
I'm getting these errors as well:

```
ERROR: Condition "!uniform_set" is true.
   at: RenderingDeviceVulkan::draw_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:5957)
```
Godot [32f95c2](https://github.com/godotengine/godot/commit/32f95c2f8782f7e524310b4c040f86cb475fdab2)
Windows 10 64 bit
intel i7-9700
Not sure where to find my gpu but it does have a vulkan driver; as I've ran the vulkan samples before!

**Comment by Damianu** [comment]
```
ERROR: Condition "!uniform_set" is true.
   at: RenderingDeviceVulkan::draw_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:5960)
```
Still happens on https://github.com/godotengine/godot/commit/4e4fcbd79352b96210929eab8f6cd1670af0462a

Windows 10 64 bit
AMD Ryzen 5 3600
GTX 2070 Super
I am also at latest GPU driver at the time.

**Comment by RicardRC** [comment]
Still happens on 163687d

**Comment by williamclarkmcbride** [comment]
I think this may occur if the Vulkan SDK is not installed. I was having this and a similar issue (https://github.com/godotengine/godot/issues/37102) and both were resolved by installing the Vulkan SDK from LunarG: https://vulkan.lunarg.com/home/welcome

**Comment by KoBeWi** [comment]
@Zylann Can you still reproduce this?

**Comment by Zylann** [comment]
I didn't get this since. But I dont think I ever ran Godot 4 in the exact same conditions either.

**Comment by Calinou** [comment]
Closing for now, please comment if you can still reproduce this.
