### ISSUE TITLE
Inconsistent file sort order in editor

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#37721]
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Linux

**Issue description:**
Files with the prefixes `_`, `!` etc. are sorted differently in different windows and editor panels. This is a bit confusing.

![200409-1](https://user-images.githubusercontent.com/47700418/78924518-acc36a80-7aa2-11ea-99e7-bd3858eb9ff1.png)

**Steps to reproduce:**
—

**Minimal reproduction project:**
—

**Comment by KoBeWi** [comment]
This is probably because EditorFileDialog uses a regular `DirAccess`, while FileSystemDock uses EditorFileSystem.

**Comment by Gogsi** [comment]
So I checked it out and here's what I found:
1) FileSystemDock uses EditorFileSystem and sorts only the files with a NaturalNoCaseComparator. The directories are left in the order of the EditorFileSystem, which seems to be sorted by ASCII.
https://github.com/godotengine/godot/blob/feeef52feb0eb968b227b239f19ebb9d000ab2f8/editor/filesystem_dock.cpp#L752
https://github.com/godotengine/godot/blob/f33bba15b16e85c1400cff8a755836690676f8d6/editor/filesystem_dock.h#L257-L259
2) EditorFileDialog uses DirAccess and sorts both the directories and the files using NaturalNoCaseComparator
https://github.com/godotengine/godot/blob/feeef52feb0eb968b227b239f19ebb9d000ab2f8/editor/editor_file_dialog.cpp#L774-L775
3) ScriptEditor sorts the script names by operator< in _ScriptEditorItemData which seems to also (eventually) do ASCII sorting (though ScriptEditor allows for rearranging the scripts)
https://github.com/godotengine/godot/blob/f33bba15b16e85c1400cff8a755836690676f8d6/editor/plugins/script_editor_plugin.cpp#L1852
https://github.com/godotengine/godot/blob/f33bba15b16e85c1400cff8a755836690676f8d6/editor/plugins/script_editor_plugin.cpp#L1595-L1606

I believe the intended sorting order for all of these is NaturalNoCaseComparator, so I can try to fix these.

**Comment by dploeger** [comment]
Another thing is (or should I open another bug for this):

When you add a new resource or script using right click/new ressource in a folder using the Filesystem browser, the contents of the folder aren't sorted.They're only sorted once you restart Godot again.

**Comment by KoBeWi** [comment]
@dploeger Open a new issue (if there isn't one already).
