### ISSUE TITLE
[TRACKER] DisplayServer, Window & UI issues

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#37734]
Tracker for DisplayServer/Window bugs in 4.0. Feel free to edit.

DisplayServer PR: godotengine/godot#37317

Multi-window proposal: https://github.com/godotengine/godot-proposals/issues/28

### Bugs

- [x] godotengine/godot#37732
- [x] godotengine/godot#37731
- [x] godotengine/godot#37730
- [x] godotengine/godot#37710
- [x] godotengine/godot#37548
- [x] godotengine/godot#37531
- [x] godotengine/godot#37401
- [x] godotengine/godot#37425
- [ ] godotengine/godot#37377
- [x] godotengine/godot#37327
- [x] godotengine/godot#37341
- [x] godotengine/godot#37335
- [x] godotengine/godot#37334
- [x] godotengine/godot#37331
- [x] godotengine/godot#37330
- [x] godotengine/godot#37329
- [x] godotengine/godot#37328
- [x] godotengine/godot#37325
- [x] godotengine/godot#37323
- [x] godotengine/godot#37322
- [ ] godotengine/godot#37320
- [x] godotengine/godot#37792
- [x] godotengine/godot#38311
- [x] godotengine/godot#38591
- [x] godotengine/godot#38726
- [x] godotengine/godot#39235
- [x] godotengine/godot#39596
- [x] godotengine/godot#40227
- [x] godotengine/godot#39087
- [x] godotengine/godot#37930
- [x] godotengine/godot#45199
- [x] godotengine/godot#45200
- [x] godotengine/godot#58032
- [ ] https://github.com/godotengine/godot/issues/63500

### May be relevant

- [x] godotengine/godot#37724
- [x] godotengine/godot#37941
- [x] godotengine/godot#38665
- [x] godotengine/godot#37588
- [x] godotengine/godot#37665
- [x] godotengine/godot#37520
- [x] godotengine/godot#37748
- [x] godotengine/godot#38312
- [x] godotengine/godot#38316
- [x] godotengine/godot#38311
- [x] godotengine/godot#38817
- [x] godotengine/godot#39892

### Pull requests

- [x] godotengine/godot#37366
  - Superseded by godotengine/godot#37802
- [x] godotengine/godot#37382
  - Superseded by godotengine/godot#37327 
- [x] godotengine/godot#37389
- [x] godotengine/godot#37430
- [x] godotengine/godot#37506
- [x] godotengine/godot#37519
- [x] godotengine/godot#37528
- [x] godotengine/godot#37549
- [x] godotengine/godot#37557
- [x] godotengine/godot#37559
- [x] godotengine/godot#37771
- [x] godotengine/godot#39145
- [x] godotengine/godot#39640
- [x] godotengine/godot#38727

**Comment by ThakeeNathees** [comment]
- [ ] pr: fix project manager window position bug #37366

**Comment by Anutrix** [comment]
https://github.com/godotengine/godot/issues/39235 closed by https://github.com/godotengine/godot/pull/40107.

**Comment by nathanfranke** [comment]
#39087

**Comment by Riteo** [comment]
Could you add #37930 and its relative PR #38727 to this list?

**Comment by akien-mga** [comment]
Done.

**Comment by Riteo** [comment]
#37930 closed with the merging of #38727. Could you mark them as such?

**Comment by Calinou** [comment]
@Riteo Done.

**Comment by h0lley** [comment]
#58032 should go in here as well I think

**Comment by Calinou** [comment]
> #58032 should go in here as well I think

Added.

**Comment by Anutrix** [comment]
> [4.0] Camera2D's preview box uses editor viewport size instead of project settings size

can be checked off. #38316 seems to be fixed.

**Comment by RedMser** [comment]
This list is missing #63500

**Comment by Anutrix** [comment]
> Improve editor popups with multiple screens #37506

can be checked off.

**Comment by YuriSizov** [comment]
Most of this tracker is now fixed, and the remaining couple of issues are out of scope for 4.0 at this point. I'm going to close this issue. Feel free to report new problems if you run into them.
