### ISSUE TITLE
Creating or choosing a folder when creating a project closes all popups and doesn't create the project

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#37731]
Godot 4 b3310a00743d65d8baa2b5730ecfaed8bf8842a6
Windows 10 64 bits

I try to create a project using the project manager but each time I choose a folder, all popups close and I'm left with the empty project manager, having created no project.
This makes it impossible to create a project.

1) Open project manager
2) Choose New Project
3) Choose Browse to select a folder, then validate: observe all popups close.

I expected the selected folder path to be written to the "Project Path" and be able to resume creating the project.

**Comment by Anutrix** [comment]
Could be related to Issue 3 in https://github.com/godotengine/godot/issues/37401.

**Comment by clay53** [comment]
Currently having this problem on pop!os 20.04 w/ Nvidia GPU on https://github.com/godotengine/godot/commit/d2887ea78b5256faaaae7e0ba66fc9146d35dceb
