### ISSUE TITLE
All popups close when the main window is hidden, minimized, moved or resized

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#37732]
Godot 4 b3310a00743d65d8baa2b5730ecfaed8bf8842a6
Windows 10 64 bits

In the project manager, when a popup is opened (to create a project for example), focusing another app or minimizing Godot and then focusing it again will restore popups as they were, but they will immediately all close, instead of being focused back.
It also happens when interacting with the decoration of the main window, and it's quite annoying to have such popups behaving in such a "volatile" way (that no other native app does).

1) Open Project Manager
2) Choose New Project
3) Click on another app (or interact with Godot's main window decoration)
4) Click back onto Godot: the New Project popup closes.

Also reproduces with editor popups, such as project settings.

This did not happen in Godot 3.2.1.

**Comment by giarve** [comment]
I think this is exactly the same as #37710. Dropdowns are implemented as windows and when focus is lost they're closed. If somebody decides to take a look notice that it may be the same issue about loosing focus (main window is hidden, minimized, moved or resized requires changing focus).

**Comment by Anutrix** [comment]
The issue leads to this: https://github.com/godotengine/godot/blob/f65787a63e53013aab6c373f1a5381308bf46009/scene/gui/dialogs.cpp#L53-L55
The `focus_entered` signal seems to be a problem.
