### ISSUE TITLE
An easier way to close script and document files

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#3774]
It could be nice to have an (x) at the end of file item to close it easier, specially the docs files.
![](https://lut.im/w6SyadLDuG/0xLOE4vOhjU5uT5u.png)

Thanks.

**Comment by kubecz3k** [comment]
+1 for 'x' on every tab :)

**Comment by kubecz3k** [comment]
Also it would be nice to have an option to have ('x') on every tab  - not only the active one :)

**Comment by toger5** [comment]
You can use Ctrl + W to closet scripts. (you can use that until buttons get implemented)
But I also agree that an ('x') butten would be very good

**Comment by StraToN** [comment]
@kubecz3k The close button on every tab is already possible, one just need to change one parameter in editor_node.cpp. However, it would be interesting to know if most users want this instead of what is currently used.

**Comment by neikeq** [comment]
It's going a bit outside the scope of this issue, but I don't like the idea of displaying ('x') for every tab. Having a option to enable that in settings wouldn't hurt anyone though :)

**Comment by kubecz3k** [comment]
@StraToN @neikeq well I probably should open new issue if we want to discuss this, so here it's: https://github.com/godotengine/godot/issues/3777

**Comment by balloonpopper** [comment]
How about using the middle mouse button for closing files instead of the "X"?

**Comment by bojidar-bg** [comment]
The `X` script button might be also shown only when the script is currently selected, though it would make sense to have them always-on for doc tabs (since you would like to close those all the time).

**Comment by hubbyist** [comment]
Or `x` can be seen when tab heading is hovered for not active tabs by overlapping text.

**Comment by KoBeWi** [comment]
> How about using the middle mouse button for closing files instead of the "X"?

This is already done. Maybe the X is unnecessary then?

**Comment by akien-mga** [comment]
Personally I feel it's fine as is, I've never found myself needing this feature. Ctrl+W or Right click > Close seem sufficient to me.

Middle mouse button is handy though, its availability should maybe be made more prominent, I just learned about it :)

I'll close this for now as it's an old feature request without a lot of engagement and with good alternatives already. But if there's a strong interest in this feature, it can be reopened/implemented.
