### ISSUE TITLE
Can't build project with C# script MacOS 10.15

### ISSUE THREAD

**Issue by instantaphex** [godotengine/godot#37741]
**Godot version:**
3.2.1
**OS/device including version:**
Macbook Pro - Catalina 10.15.3 Beta
**Issue description:**
Can't build any project that has a C# script
**Steps to reproduce:**
1.) New project
2.) Create Kinematic Body
3.) Give it a capsule collision shape
4.) Attach a C# script (default template will do)
5.) Build
6.) Observe this error in the console.  editor/editor_node.cpp:5268 - An EditorPlugin build callback failed.

**Comment by aaronfranke** [comment]
Do you have Mono installed? Have you tested the official demo projects?

**Comment by instantaphex** [comment]
I reinstalled mono and it built.  I'm not sure if my initial mono install had failed for some reason or if I had the wrong version.  Thanks.
