### ISSUE TITLE
LineEdit caret sometimes invisible in sub-window

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37748]
**Godot version:**
c2f0d58

**Issue description:**
![STTd7eYnot](https://user-images.githubusercontent.com/2223172/78980209-bb9b3300-7b1d-11ea-92f8-ce98ffd1e336.gif)
This appears when you rename a file in Filesystem Dock.

**Comment by reduz** [comment]
I can't reproduce this, which OS are you using to test?

**Comment by KoBeWi** [comment]
Windows 10
Seems to happen when the rename dialog appears more than once (i.e. you rename two files).

**Comment by KoBeWi** [comment]
Doesn't seem to happen anymore.
