### ISSUE TITLE
Window option Always On Top not working

### ISSUE THREAD

**Issue by yoskeleton** [godotengine/godot#37762]
**Godot version:**
3.2.1.stable.official

**Issue description:**
The option Always On Top in project settings > display > window is not working
https://i.imgur.com/6THy5nF.png

**Comment by yoskeleton** [comment]
i tested on a blank project and it work
it work on my project too now
i think restarting godot fixed it

**Comment by danreeves** [comment]
I also had this issue. Restarting the PC was the only fix. (Windows 10, Godot 3.2.1)
