### ISSUE TITLE
String.insert implicitly takes string index

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37767]
**Godot version:**
ae42cb7b0

**Issue description:**
```
var s = "abc"
print(s.insert("2", "d"))
```
This prints `abdc`. Fails if `insert` is called on typed variable or directly on string.

**Comment by CaptainProton42** [comment]
This is my first attempt at somewhat contributing to Godot, so please bear with me, but I did some digging, and I _think_ I somewhat know what's going on here:

Let's take a look at this minimal example, similar to yours:

```
var s = "abc"
var pos = "2"
print(s.insert(pos, "d")
```

This will print `abdc` just fine.

Let's type `s`: 

```
var s : String = "abc"
var pos = "2"
print(s.insert(pos, "d")
```
This will also work fine.

But if we now also type `pos`:

```
var s : String = "abc"
var pos : String = "2"
print(s.insert(pos, "d")
```

The parser will throw an error: `Parser Error: At "insert()" call, argument 1. Assigned type (String) doesn't match the function argument's type (int).`

If we only type `pos` however,

```
var s = "abc"
var pos : String = "2"
print(s.insert(pos, "d")
```

this will again run just fine.

Note: calling insert directly on the string or passing `pos` directly as a string is the same as typing them.

I tried to debug this by adding some debug messages around the critical section in `gdscript_parser.cpp`.

Apparently, what happens is that as long as `s` is not typed, the parser does not check the types of the arguments to its member function `insert` so the parser will not flag it and both an untyped as well as a typed variable `pos` will be converted to `int` if possible.

However, when `s` is typed, the parser checks the argument types. If `pos` is now untyped, the parser will compare the types `var` and `int` internally and not complain, `pos` is later converted from `var` to `int`. But if `pos` is typed as `String`, the parser will conclude that the types are not compatible and throw an error.

This is obivously _not_ only limited to `String::insert`. I don't know enough about the parser's architecture to say whether this is desired behaviour or not but I guess it makes sense to have more rigorous checks on typed variables. Maybe also adding argument checks to member functions of _untyped_ variables will make it more consistent but, again, I don't know about this stuff to make any conclusions on whether that is even feasible.

Again, this is my first real attempt at digging through Godot's code so there is a good chance that some of the above might be inaccurate.

**Comment by KoBeWi** [comment]
Fixed, probably long ago.
