### ISSUE TITLE
Close [x] icon on every scene tab 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3777]
I think it would be more straightforward to have [x] icon on every tab. Currently when I need to close some tab I need to make 2 clicks, and further more when using 'open dominant script on scene change', I'm ending up with closed scene but opened script.  Also when looking how other software deals with this, browsers have 'x' visible on default. Some text editors like Atom hide 'x' by default, but shows it on mouse hover. Don't know any other program that force me to open tab first when I want to close it.
Know not every body will like this idea, that's why I opened the issue. What do you think?

**Comment by akien-mga** [comment]
Yes from me, but opt-in or opt-out in the editor settings. For some workflows where one only works with two or three scenes at a time, it's IMO better to only have the [x] on the current tab. For workflows where one works with 15 scenes at time like @kubecz3k and his extensive scene inheritance usage, being able to close scenes fast is indeed a nice feature.

@StraToN said the feature is already in the code, so IMO let's expose it to the editor settings, and maybe keep the current behaviour as default (unless there's a consensus to go the other way around, i.e. [x] on each tab as default).

**Comment by kubecz3k** [comment]
@akien-mga well the middle ground that would probably satisfy most of the people would be atom approach: clean default look on default -> show icon when mouse is hovering.

**Comment by akien-mga** [comment]
That was actually implemented by @StraToN initially, but then @reduz removed it (don't remember exactly when though, a few months ago).

**Comment by StraToN** [comment]
I'll reimplement this better:
- no width change when hovering a tab
- add an option in Godot parameters.

**Comment by rgrams** [comment]
Yeah, it would be awesome to have a close button on each tab. It's a real pain to close things without them. Select, close, select, close, select, close . . . I don't know why you _wouldn't_ want a close button, but to each his own. Especially when you have only a few tabs, there's plenty of room, so you can't miss.

**Comment by puppetmaster-** [comment]
How about middle mouse button click on scene tab, same like closing webbrowser tab.

**Comment by StraToN** [comment]
@puppetmaster- Same, I had this developed back in time, and set a PR #2371

**Comment by reduz** [comment]
No, just leave it like it is now, there is not that much area for showing
tabs, so adding an X to each one makes it bigger.
If you reaaally want to have an X on every tab, add it as an optional
editor setting

**Comment by StraToN** [comment]
@reduz This could be a solution, indeed. Either the current way Tabs show Close button (Active only), or Always shown. Choice made using an editor setting as you suggest.

**Comment by reduz** [comment]
Fine for me.  Keep in mind that a lot of people has small notebook screens
and now the room for scene tabs has shrunk, so this option must remain off
by default. Enable it if you have a large screen :)

**Comment by StraToN** [comment]
@reduz Sure, that is what I intended ^^.

**Comment by kubecz3k** [comment]
@reduz  @StraToN @akien-mga 
I'm wondering, currently we have green/grey dots on the every tab... why not put [x] button there? This way it would not change anything when it comes to size or appearance, the circle could simply change to cross on mouse hover.. 
![dots](https://cloud.githubusercontent.com/assets/6129594/13196666/0d5fa2de-d7d5-11e5-9d6c-08585c8f530f.png)

**Comment by reduz** [comment]
It's not a green/grey dot, it's the type of the root node

**Comment by rgrams** [comment]
Speaking of saving space for scene tabs, is there any good reason to show the file extension? It seems like the kind of thing that could be shown in a tooltip or somewhere else, and removing it would make the scene tabs significantly smaller and more readable.

**Comment by akien-mga** [comment]
> Speaking of saving space for scene tabs, is there any good reason to show the file extension? 

For me it was often useful, e.g. when porting a game from xscn to tscn. But indeed it's not an information that one needs to *always* have visible. A nice compromise could be to hide the extension by default, and show it only if scenes with different extensions are opened. Or add an editor setting for that of course.

**Comment by reduz** [comment]
if you are opening a file, so it makes sense it shows the file extension. I
would not hide it. I think we shouldn't over complicate this aspect of
Godot any more IMO let's try to improve based on actual problems users find.

**Comment by rgrams** [comment]
>  let's try to improve based on actual problems users find. 

It's called the interface, and it's arguably the single biggest problem with every machine and piece of software, including Godot. :P 

But I know what you mean, I'll shut up now. Haha.
