### ISSUE TITLE
Append_bbcode doesn't pop tags without adding them in the same call

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37774]
**Godot version:**
3.2.1

**Issue description:**
```
$RichTextLabel.append_bbcode("[color=red]test[/color]test2")
```
![image](https://user-images.githubusercontent.com/2223172/79021014-c0420480-7b7a-11ea-98df-1752495ffff3.png)
```
$RichTextLabel.append_bbcode("[color=red]")
$RichTextLabel.append_bbcode("test")
$RichTextLabel.append_bbcode("[/color]")
$RichTextLabel.append_bbcode("test2")
```
![image](https://user-images.githubusercontent.com/2223172/79021059-d9e34c00-7b7a-11ea-8a76-6e6dd73643f0.png)

**Comment by JulianHeuser** [comment]
In case anyone is banging their head against the wall like I was, a decent workaround for this is to use pop() instead.
