### ISSUE TITLE
Disconnect doesn't support autocompletion

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37789]
**Godot version:**
3.2.1

**Issue description:**
You disconnect the same signals that you would connect, so it makes sense that both methods should suggest the same signals (and methods) in autocompletion. This can be probably copy-pasted.

**Comment by dreamsComeTrue** [comment]
Are you considering adding that to maintenance (3.x) version? With 4 there is much rework (which breaks compat) in that area already taken (with Callables).
