### ISSUE TITLE
OS.set_video_mode() not working on Android

### ISSUE THREAD

**Issue by czlowiekimadlo** [godotengine/godot#3778]
**Operating system or device:**
Samsung Galaxy Tab S with Android 5.0.1

**Issue description** (what happened, and what was expected):
Changing video modes in runtime is not working on Android devices. Same funcionality for Windows, Linux and OSX works fine.

**Steps to reproduce:**
- Run a game on android
- Try to change resolution from a script using OS.set_video_mode() to one that is different

**Link to minimal example project** (optional but very welcome):
http://w84death.itch.io/tanks-of-freedom - game built with default settings should adapt to low-resolution screen (less than 1280x720)
I will prepare smaller demo for easier debug

**Comment by czlowiekimadlo** [comment]
This is not exactly a bug, as this appears to not be implemented at all:
https://github.com/godotengine/godot/blob/master/platform/android/os_android.cpp#L291

**Comment by akien-mga** [comment]
It's not implemented on X11 either: https://github.com/godotengine/godot/blob/master/platform/x11/os_x11.cpp#L583-L584 :)

You said it's working fine on desktop though? Are you also using OS.set_video_mode() on desktop?

IMO the "bug" is that we have those empty functions in OS that should be either implemented or dropped :)

**Comment by reduz** [comment]
This function call is deprecated, will go away soon.

**Comment by czlowiekimadlo** [comment]
Ah, that explains it. Yes, I am using it on desktop, exact code is:
`
    OS.set_window_resizable(true)
    OS.set_window_fullscreen(fullscreen)
    OS.set_video_mode(newsize, fullscreen, false)
    OS.set_window_size(newsize)
    OS.set_window_resizable(false)`

It works on Linux, but does not on Android.

**Comment by punto-** [comment]
but what do you expect to happen? android doesn't have windows or video
modes. it's just a screen :p

**Comment by vnen** [comment]
BTW, if this is deprecated, it should go to the docs and to the changelog.

**Comment by akien-mga** [comment]
It was already deprecated in 1.1 and maybe before as far as I know. Actually it was in the docs until now, but I just dropped it as I think the docs should focus on 2.0+, and not on telling people how to not do stuff with no-longer existing functions :)

**Comment by akien-mga** [comment]
On the other hand it should be removed altogether from the source code. But I guess that will have to wait for 2.1 :/

**Comment by vnen** [comment]
@akien-mga Even in the in-editor help?

**Comment by akien-mga** [comment]
Marked for deprecation in #4398.

**Comment by reduz** [comment]
will be removed in 3.0

**Comment by gau-veldt** [comment]
So games will eventually not be able to change their screen size, not even on platforms that support it, as what I get from this.

**Comment by vnen** [comment]
@gau-veldt 
> In this case the viewport might need an "ugly black bar" option 

I don't know what you mean, since such option [already exists](http://docs.godotengine.org/en/latest/tutorials/engine/multiple_resolutions.html#stretch-settings).

Also, there are other functions to change fullscreen mode, resizability and window size.

**Comment by akien-mga** [comment]
"Fixed" in 78e90ac.
