### ISSUE TITLE
Moving Control with min_size to bottom/right_wide moves it out of screen

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37781]
**Godot version:**
3.2.1

**Steps to reproduce:**
1. Create a User Interface scene
2. Add ColorRect
3. Set min_size y to 100
4. Use anchors button to bottom wide
5. The rectangle goes out of Control

![image](https://user-images.githubusercontent.com/2223172/79027485-add0c680-7b8c-11ea-9cb8-5279ace35a44.png)

**Comment by Tyrannicodin** [comment]
Stale post, but did you find a work around for this?

**Comment by KoBeWi** [comment]
Huh, this still exists in 3.5 🤔 I think I just manually placed the control. Even if you move it, it will respect the anchors, so it's not a big deal.

The issue is fixed in Godot 4, as the Control layout system had a major rewrite. Closing.
