### ISSUE TITLE
Stretch ratio has weird value range

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37786]
**Godot version:**
3.2.1

**Issue description:**
Sooo there's this `size_flags_stretch_ratio` property in Control nodes, which controls how much of available space the control will take (relatively). But it's awkward to use. The range goes from 0 to 128, with step value of 0.01. This makes the slider basically useless (although you can set to rounded values with Control key, but you need to know it first; and the small values are still awkward). I mean, the useful range would be something between 1 to 5. I doubt anyone would want a control in a container to be 100 times bigger than the other one. And even if you ignore that the slider allows for such big values, the small useful range compared to the whole range makes it difficult to set anything.

So the range should be tweaked to some more useful/sane values, possibly including a step change. IMO.

**Comment by Calinou** [comment]
If values below 1 make sense, they should still be exposed in the slider. How about `0..5`?

**Comment by KoBeWi** [comment]
> How about 0..5 with an or_greater hint to allow manually entering larger values?

Sounds good. Also the step could be increased to 0.1.

**Comment by Calinou** [comment]
@KoBeWi I'm not sure about increasing the step to 0.1, you may need to do precise adjustments and there's no way to bypass them by manually entering the value.
