### ISSUE TITLE
GraphNode shouldn't allow to change its position (or it should update offset)

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37780]
**Godot version:**
3.2.1

**Issue description:**
I found it quite confusing that my GraphNode doesn't stay where I put it. Turns out it has `offset` property used for its actual position and changing `rect_position` effectively has no effect (even if it looks like it has). Editing position of this node should be impossible or it should automatically set the `offset`.

**Comment by theoway** [comment]
Yeah, just noticed it.  It'd be better if the `offset` also changed with the `rect_position.`  I'll dig in the source code and see what can be done.

**Comment by theoway** [comment]
The offset of the GraphNode, relative to the scroll offset of the GraphEdit.
Note: You cannot use position directly, as GraphEdit is a Container.
(In the documentation of GraphNode)

**Comment by theoway** [comment]
@KoBeWi I think the offset should get updated with the change in rect position of the GraphNode. What do you think?

**Comment by KoBeWi** [comment]
Yeah, setting offset changes rect_position, so it should work both ways.

**Comment by theoway** [comment]
> Yeah, setting offset changes rect_position, so it should work both ways.

Indeed, makes sense this way. I'll look into the code and see what can be done.

**Comment by theoway** [comment]
@KoBeWi I've managed to update the `offset` with change in `rect_position` but the updated value of the `offset` shows up after saving the scene only. So, kinda stuck here but will work my way out.
