### ISSUE TITLE
Both search and replace can be selected at the same time

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37788]
**Godot version:**
3.2.1

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/79030598-17a39d00-7b9a-11ea-9b58-37cebbe70cc2.png)
This is impossible in typical code editors (and it's not a feature xd).

**Comment by Anutrix** [comment]
Not reproducible on master c4279fe3e and v3.5.3.stable.official [6c814135b].

Is there a specific way to trigger this? Select, Ctrl+Select and Shift+Select didn't work.

**Comment by KoBeWi** [comment]
Looks like it was fixed at some point.
