### ISSUE TITLE
Button "Keep Pressed Outside" has no effect

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#37790]
**Godot version:**
3.2.1 Stable

**OS/device including version:**
Win10 Version 1909

**Issue description:**
When using buttons the keep_pressed_outside property only affects the visual function of buttons.
Signals aren't emitted until the mouse is released.

**Steps to reproduce:**
Use a button, print the button_up and button_down signals

**Minimal reproduction project:**
Base project with button.

**Comment by Calinou** [comment]
I think this is intended. Otherwise, there would be no way for the user to "cancel" pressing a button after pressing down the button and moving the cursor away from it.

**Comment by addmix** [comment]
> I think this is intended. Otherwise, there would be no way for the user to "cancel" pressing a button after pressing down the button and moving the cursor away from it.
> 
> Still, the documentation should be updated to reflect this.

but the button visual state and functional state do not match, meaning only the visual state changes and has no function. For cancelling a button if dragged away, set the button activation to be on the released rather than pressed.

**Comment by Anutrix** [comment]
> 
> 
> > I think this is intended. Otherwise, there would be no way for the user to "cancel" pressing a button after pressing down the button and moving the cursor away from it.
> > Still, the documentation should be updated to reflect this.
> 
> but the button visual state and functional state do not match, meaning only the visual state changes and has no function. For cancelling a button if dragged away, set the button activation to be on the released rather than pressed.

I think you are right.
