### ISSUE TITLE
Building Main branch Godot from source for Windows(constant errors)

### ISSUE THREAD

**Issue by CROmartin** [godotengine/godot#37799]
**Godot version:**
Master branch 
**OS/device including version:**
Win 10 home
**Issue description:**
Error occur image:
![Image](https://preview.redd.it/pun3k1wow5s41.png?width=1442&format=png&auto=webp&s=bb28bdbcd6dd6c383b185d235e4ffefb51950e96)
**Steps to reproduce:**
Download Python 3.8.2 install it with all requirements, install VS with required c++ packages, install SCons 3.1.1(stable), install pywin32 for multi threading, clone master branch with Git Bash, try to build Godot with  SCons and then it fails while building. 
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Did you install the Windows SDK?

**Comment by CROmartin** [comment]
> Did you install the Windows SDK?

![image](https://user-images.githubusercontent.com/26621064/79048947-d86c5f00-7c20-11ea-896c-ebeaa4c2bae4.png)

**Comment by Anutrix** [comment]
Try a different compiler for now.

**Comment by Anutrix** [comment]
>  In a future version of MSVC, <string> doesn't transitively include<ostream>.

https://github.com/BinomialLLC/basis_universal/commit/8cd007442103174a12733301a7508a7e9c1a441f is most probably the reason.
But there hasn't been a new release version upstream with this patch so I am not sure if should get the latest commit or wait for a new release.

**Comment by akien-mga** [comment]
> But there hasn't been a new release version upstream with this patch so I am not sure if should get the latest commit or wait for a new release.

We're already tracking an upstream commit and not a stable release, so we can update to latest `master`.

**Comment by CROmartin** [comment]
> > In a future version of MSVC,  doesn't transitively include.
> 
> [BinomialLLC/basis_universal@8cd0074](https://github.com/BinomialLLC/basis_universal/commit/8cd007442103174a12733301a7508a7e9c1a441f) is most probably the reason.
> But there hasn't been a new release version upstream with this patch so I am not sure if should get the latest commit or wait for a new release.

Adding <ostream> library in basisu_enc.h will solve problem. So as I understand all older versions of Godot will not compatible with VS 2019(then it is better use older version like VS 2017?)  with out adding this library, new version of Godot will adapt to a changes made by VS 2019? 

Thanks on help @akien-mga && @Anutrix

**Comment by akien-mga** [comment]
> So as I understand all older versions of Godot will not compatible with VS 2019(then it is better use older version like VS 2017?) with out adding this library, new version of Godot will adapt to a changes made by VS 2019?

Basis universal is a new dependency for Godot 4.0, the 3.2 branch and earlier don't include it and won't have this build issue.
