### ISSUE TITLE
Android: LineEdit does not respond correctly to ENTER pressed on virtual  keyboard

### ISSUE THREAD

**Issue by mudbile** [godotengine/godot#37793]
**Godot version:**
Godot 3.2

**OS/device including version:**
Tested on Android 6.0

**Issue description:**
Pressing the ENTER button on the virtual keyboard while focused on a LineEdit node does not fire the "text_entered" signal. Instead, the first time you press ENTER it might change to a recommendation, and then actual newlines are appended (I think), resulting in abnormal graphical effects (I think either the node moves up or the view moves down). When you close the virtual keyboard the LineEdit reappears where it's supposed to be.

**Steps to reproduce:**

1. Create a project with a LineEdit and a Label
2. Connect the LineEdit's "text_entered" to a function that updates the text on the Label
3. Run on Android
4. Type something into the LineEdit and press the ENTER key
5. Observe that the Label does not update
6. Keep pressing ENTER
7. Observe weird graphical effects

**Minimal reproduction project:**
[LineEditBug.zip](https://github.com/godotengine/godot/files/4464187/LineEditBug.zip)

**Comment by kalbfled** [comment]
I might be encountering this bug with Godot 3.2.1. Pressing ENTER works fine on my desktop but not on Android.

My desktop: Ubuntu 18.04, Godot 3.2.1
My Android device (phone): LineageOS 16.0 (based on Android 9)

**Comment by capnm** [comment]
At least for us this is a **big regression** in the controls **LineEdit** or **TextEdit**.
We don't have such problems when we revert our projects to v3.2.1.stable. The ENTER key on the Android keyboard broken behavior makes a text editing under Android in v3.2.2.stable completely unusable :-(

**Comment by capnm** [comment]
A similar effects as described in #37190 also occur, or the TextEdit simply disappears, after pressing the Android ENTER key. And the virtual keyboard with the LineEdit now remains open :-(

**Comment by capnm** [comment]
Tested the official **3.2.3.rc2** and it is broken for reasons unknown to me:
the **enter-key** doesn't cause a new-line in the TextEdit and doesn't close the virtual Android keyboard in LineEdit.

Also that AFAIK:
* woks in 3.2.1
* is broken in 3.2.2
* works in 3.2.2 + https://github.com/capnm/godot/commit/13456724f56cf5dad2ddd852ae2fcdee7574e74c
* is broken in 3.2.3.rc2

**Comment by pouleyKetchoupp** [comment]
I can confirm #40469 & #40672 both seem to be missing in the official 3.2.3.rc2 release.

@akien-mga Is there an easy way to check that java changes have been included into the 3.2.3.rc2 android template?

**Comment by akien-mga** [comment]
Welp no, it's built from 0835b3a15b9b084a095b0bb699a2a2f2b6a8f3ea so it's the same as RC 1... :upside_down_face: 

Damn :D

**Comment by akien-mga** [comment]
It's still uploading and the binaries will be fully online within ~30 min, but here's 3.2.3 RC 3: https://downloads.tuxfamily.org/godotengine/3.2.3/rc3/

This time properly built from 78a6a578843928017c1fe40f23a31a620e76d2ef.

@capnm @pouleyKetchoupp Could you test it as soon as possible and make sure that it works as intended? If it works, I'd likely publish 3.2.3-stable tomorrow or on Sunday (otherwise it will have to wait after my holidays so more mid-August :)).

**Comment by capnm** [comment]
The Godot executable thinks it's rc2, you probably didn't run the script mentioned in the README ...

![grafik](https://user-images.githubusercontent.com/4047289/89025512-48653900-d327-11ea-951c-73d283d4d905.png)

**Comment by pouleyKetchoupp** [comment]
@akien-mga Apart from the editor still set as rc2, I can confirm the Android fixes work properly if I set the rc3 templates manually during export.

**Comment by capnm** [comment]
> the Android fixes work properly if I set the rc3 templates manually during export.

Yeah, after editing the installed rc3 templates to rc2, it now works :+1:

**Comment by akien-mga** [comment]
Oh well... I need to improve that part of the build workflow to prevent these issues from happening... 

I'll rebuild 3.2.3 RC 3 properly then, including a couple more fixes.

**Comment by capnm** [comment]
@pouleyKetchoupp Unfortunately I found a new issue in the RC3 with your other PR that makes the adjustment fixes. The virtual touch-pad from Android now is/remains open if the virtual KB is closed and cuts off part of the Godot viewport window:

![Screenshot_20200731-134450](https://user-images.githubusercontent.com/4047289/89033587-62a71300-d337-11ea-8c11-13a545f7e3f8.png)

**Comment by pouleyKetchoupp** [comment]
@capnm I can reproduce it too. I'm checking if there's an easy fix for this bug.

**Comment by pouleyKetchoupp** [comment]
@akien-mga @capnm I've just opened #40944 to address the regression on 3.2.

**Comment by xuppr** [comment]
Yes, I found the same issue with the LineEdit. On Android when I try to append a child to a Vbox container on text_entered signal the app freezes. The code works fine with a Button and his button_pressed signal.
