### ISSUE TITLE
Godot UI improvements [Mockups]

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3779]
Godot UI, despite being nice, could use space better, so I've made a couple of mockups to give an idea where environment could be better. Nothing ambitious, just little changes to make space for what matters the most (Viewport area and sidebar).

![untitled](https://cloud.githubusercontent.com/assets/10696955/13177626/018fc2f2-d723-11e5-9952-ea8d615bfa44.png)
This one has all the elements on top bar (which, to be honest, could hold even Play Project group to give more space for scene tabs). It adds to mouse movement between animation player and animation button but looks pretty clean. 
![untitled1](https://cloud.githubusercontent.com/assets/10696955/13178109/e1b11cee-d725-11e5-8bee-9b0c52090166.png)
In this mockup Animation, Output and Debugger elements are left on bottom, which adds to mouse movements to them, but makes bottom bar popping up a bit more intuitive. Scroll bar is moved a little bit. 

Also, I'd like to talk about right click and drag-n-drop friendly nodes in scene tree. Right click is just not used in Godot for some reason. Presenting all the buttons right away is nice and all, but there's a hardware button that can give so much more. 
- Some of the options (Delete, Reparent, Node connections, Node groups, Replace by another type, Duplicate) can be placed in contextual menu on right click. 
- Reparenting should be possible with dragging nodes inside the tree. 
- Right click on resources in the FileSystem tab should open up a menu with rename or move, delete, view owners. 
- By dragging and dropping files in folders people should be able to move resources.
- Right click on element inside the scene should open up a contextual menu that shows node type, name and script bound to the node (with quick option to jump to script).

This way it's possible to reduce the overall amount of all the buttons (or give more ways to get to a feature for a user).

**Comment by rgrams** [comment]
Interesting. Yeah having a whole bar for Output, Debugger, and Animation is kind of a waste, though I see why they did it. I like what you did with them in the second mockup. It's a little bit strange, but it saves a lot of space. 

There's no drag-and-drop or right-click menus simple because they haven't found the time to do them yet. I'm pretty sure both are planned for 2.1. 

Do you think that all those buttons should be removed when they add right-click menus? I've been thinking about that myself and I'm conflicted about it. You could remove about half the buttons and make the UI much more spacious and clean, but it would make some common actions invisible and add an extra click for each of them.

**Comment by kubecz3k** [comment]
I just would like to suggest to move [2d,3d,script,(...)] more to the top, the way you are doing it currently is eating the scenetabs space :)

**Comment by ArcFutahito** [comment]
I'm not really sure whether "2d, 3d, script" or "start project, start scene etc." should be moved to the top. I think usability would be better with "start project, start scene etc."  being in the top bar, rather than "2d, 3d, script"

**Comment by kubecz3k** [comment]
@ArcFutahito I wont argue with you, guess it's matter of taste, but you said you would like to make space for what matter the most, and well for me one of these things is number of tabs I'm able to see on my laptop screen :)

**Comment by ArcFutahito** [comment]
@kubecz3k Well, "2d, 3d, script" doesn't take as much space and it's more frequently used when looking through scenes, so I think that getting "start project, start scene etc." on top would make more sense. Especially if "Animation, Output, Debugger" will stay on bottom.

**Comment by rgrams** [comment]
I'm not too sure about squeezing the menu bar to let the sidebar go up to the top. It seems fine with just one sidebar, you get that extra line, but what if you have two sidebars, like the default, or you could even have three, and if you're working on a smaller screen . . . 

What size is your screen @kubecz3k ? I have no idea what a normal laptop is these days.

**Comment by kubecz3k** [comment]
@rgrams It's a 1366x768 screen

**Comment by ArcFutahito** [comment]
@rgrams With two sidebars it's just going to give place to second sidebar. You still have a lot of free space in there so I'm sure that this shouldn't be a problem

**Comment by volzhs** [comment]
@akien-mga can this be closed now?

**Comment by akien-mga** [comment]
Yes, a lot as changed since then.
