### ISSUE TITLE
Error in the remove_child() function when using "Visible Collision Shapes" 

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#3780]
**Operating system or device:**
Windows

**Issue description** (what happened, and what was expected):
When I use the remove_child() function i get an error when "Visible Collision Shapes" is enabled

**Steps to reproduce:**
- Create 3d scene
- add staticBody with cube collider
- activate "Visible Collision Shapes"

![image](https://cloud.githubusercontent.com/assets/16718859/13184726/c873b42c-d73d-11e5-9bfc-fc57d4e61ae3.png)
- attach a script like this one:

``` python
extends StaticBody
var bool = true
func _ready():
    set_process(true)
func _process(delta):
    if Input.is_key_pressed(KEY_L)and bool:
        remove_child(get_child(0))
                bool = false
```

Then I get this error:
![image](https://cloud.githubusercontent.com/assets/16718859/13184803/398b0a66-d73e-11e5-9122-5a59e953d45a.png)

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by eon-s** [comment]
On 2.1.4 only throws one error (also happens with `queue_free` and deferred calls).

On master cannot be reproduced with any physics engine.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
