### ISSUE TITLE
Input Map Ctrl+D assign issue

### ISSUE THREAD

**Issue by luokka** [godotengine/godot#37807]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 7 Professional 64-bit

**Issue description:**
Assigning Ctrl+D to an action doesn't work while the GDScript editor is open in the background, but assign works when editor is closed.
Noticed this while testing key combo assigns.

**Steps to reproduce:**
Press Ctrl+D when Input Map assign window is open and GDScript editor is open in the background.

**Minimal reproduction project:**

![GodotBug](https://user-images.githubusercontent.com/22845932/79048542-7f9fc500-7c26-11ea-910b-e27717d152ce.gif)

**Comment by Phischermen** [comment]
I tried this out myself. I would have expected other shortcuts relevant to the script editor to cause problems, but it appears CTRL + D is the only one.

**Comment by Janglee123** [comment]
I can't reproduce this on the master. But the issue is related to #36205.

**Comment by luokka** [comment]
These Script Text Editor shortcuts seem to override any other shortcut actions done in the main window:
Clone Down: Ctrl+D
Delete Line: Ctrl+Shift+K
Move Up: Alt+Up
Move Down: Alt+Down

Problem doesn't occur in the latest master since it gives editor settings its own window, however trying to e.g. duplicate a file (Ctrl+D) or clear output (Ctrl+Shift+K) won't work when code editor is open.

Issue might have something to do with this:
(godot\editor\code_editor.cpp)
```
/*** CODE EDITOR ****/

// This function should be used to handle shortcuts that could otherwise
// be handled too late if they weren't handled here.
void CodeTextEditor::_input(const Ref<InputEvent> &event) {

	const Ref<InputEventKey> key_event = event;
	if (!key_event.is_valid() || !key_event->is_pressed())
		return;

	if (ED_IS_SHORTCUT("script_text_editor/move_up", key_event)) {
		move_lines_up();
		accept_event();
		return;
	}
	if (ED_IS_SHORTCUT("script_text_editor/move_down", key_event)) {
		move_lines_down();
		accept_event();
		return;
	}
	if (ED_IS_SHORTCUT("script_text_editor/delete_line", key_event)) {
		delete_lines();
		accept_event();
		return;
	}
	if (ED_IS_SHORTCUT("script_text_editor/clone_down", key_event)) {
		clone_lines_down();
		accept_event();
		return;
	}
}
```
