### ISSUE TITLE
Godot Engine 3.2 GLES2 does not support blendshapes

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#37804]
**Godot version:**
![Captura de pantalla_2020-04-11_11-55-23](https://user-images.githubusercontent.com/12847027/79047157-5d3c8600-7beb-11ea-97fe-9a47fbf2085c.png)

**OS/device including version:**
![Captura de pantalla_2020-04-11_11-56-34](https://user-images.githubusercontent.com/12847027/79047192-9117ab80-7beb-11ea-8a6b-2b59183d1da6.png)

**Issue description:**
Importing shapeKeys from blender 2.82 in gltf 2.0 format or from blender 2.79 with godot DAE shapeKeys don't work.
If possible it would be good to fix it for the glTF 2.0 format in Blender 2.82

**Steps to reproduce:**
Create 1 cube in Blender 2.82 and add a shape key to deform the mesh
Importing shapeKeys from blender 2.82 in gltf 2.0 format or from blendert 2.79 with godot DAE shapeKeys don't work.
If possible it would be good to fix it for the glTF 2.0 format in Blender 2.82
Create 1 cube in Blender 2.82 and add a shape key to deform the mesh
Export the scene in gltf 2.0 format
check the mesh containing the shapeKey, you will see that it appears, but it does not work.
https://youtu.be/gNXgbOeqHr4

**Minimal reproduction project:**
[cubo_shape_animation_2.82.blend.zip](https://github.com/godotengine/godot/files/4464812/cubo_shape_animation_2.82.blend.zip)
[cubo_shape_animation 2.79.blend.zip](https://github.com/godotengine/godot/files/4464813/cubo_shape_animation.2.79.blend.zip)
[prueba godot rigging.zip](https://github.com/godotengine/godot/files/4464819/prueba.godot.rigging.zip)

**Comment by kone9** [comment]
I just verified in the Godot console that shapeKeys are not supported in GLES2 ..
And they work in GLSL3 I hope they will work in GLSL2 soon.
![Captura de pantalla_2020-04-11_12-35-39](https://user-images.githubusercontent.com/12847027/79048112-223d5100-7bf1-11ea-986f-819b3512a219.png)
https://www.youtube.com/watch?v=zqVNiJSIUZA&feature=youtu.be

**Comment by volzhs** [comment]
i'm just facing the same issue.
@pouleyKetchoupp @lawnjelly @clayjohn any possible solution for gles2?

here is my simple project for demonstrating it.
[blend_shape_gles2.zip](https://github.com/godotengine/godot/files/5192544/blend_shape_gles2.zip)

in gles3
![blend_shape_gles3](https://user-images.githubusercontent.com/8281454/92553125-2acbad80-f29d-11ea-9d40-498e4f43c650.gif)

in gles2
![blend_shape_gles2](https://user-images.githubusercontent.com/8281454/92553132-2e5f3480-f29d-11ea-97ee-8379d56a7944.gif)

it actually worked fine with godot 2.1.5 in gles2
![blend_shape_godot2 1 5](https://user-images.githubusercontent.com/8281454/92553476-f3113580-f29d-11ea-81f0-de8649921473.gif)

**Comment by fire** [comment]
@Calinou I think this is a feature request rather than bug unless it's not documented.

**Comment by Calinou** [comment]
@fire Are blendshapes even technically possible using GLES2?

**Comment by fire** [comment]
Since this is a part of Godot Engine 3.2 and there is nothing we can do except implement the GLES2 blendshape proposal, I'm not sure what can be done.

Also, I don't think any developers are working on this within the next 6 months.

**Comment by betotulkas** [comment]
in the same pc unity suport blendshapes and .blend files, sorry godot i go to unity

**Comment by Calinou** [comment]
> in the same pc unity suport blendshapes and .blend files, sorry godot i go to unity

Software blendshapes are being implemented for GLES2 as we speak :slightly_smiling_face: 

https://github.com/godotengine/godot/pull/48480

**Comment by betotulkas** [comment]
It would be a good implementation, I should not criticize Godot much, that is, I did a course in systems technology and my project to finish was a video game for Android and I presented it in Godot, although I had already worked with the unit, but wanted to test it.
