### ISSUE TITLE
Wrong popup menu position if window is moved or resized

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#37806]
**Godot version:** 4.0.dev.custom_build.4bb3f9d4b

**OS/device including version:** macOS Catalina 10.15.4

**Issue description:**
The position and size of the main window affects the popup menu window position:

![demo](https://user-images.githubusercontent.com/372476/79048005-a7098880-7c4c-11ea-8ae3-88610ca08ae9.gif)

Moving / resizing the window changes the popup menu window position. Maximizing the window restores the position.

One thing might also be related is that even when the window is maximized, the main menu is a bit offset, covering the menu button itself:

![main-menu](https://user-images.githubusercontent.com/372476/79048136-7e35c300-7c4d-11ea-9760-00b52ca923af.png)

Also, I don't know if it's related, but the console keeps printing the following error:

```
ERROR: Condition "!uniform_set" is true.
   at: draw_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:5780)
```

**Steps to reproduce:**
Move the window away from the top-left corner, and/or resize the window, and then try to open a popup menu.

**Minimal reproduction project:** N/A

**Comment by Anutrix** [comment]
I couldn't reproduce this with build #cbcec0d0567b0b5e173f1e9f90f2c03317156275 on Windows. So it's a duplicate of #38591 which was fixed by #40028 or mac specific issue now.

**Comment by timothyqiu** [comment]
Yeah, I can't reproduce this on master either. I think it's fixed.

But the popup menu still covers the menu button itself, and I don't know whether it's intended: 

![demo](https://user-images.githubusercontent.com/372476/79048136-7e35c300-7c4d-11ea-9760-00b52ca923af.png)

**Comment by KoBeWi** [comment]
@timothyqiu Can you still reproduce this?

**Comment by timothyqiu** [comment]
I can no longer reproduce this.
