### ISSUE TITLE
Animation Player Keyframe callback track doesn't allow setting a callback from attached script unless script has same name as AnimationPlayer node using C#

### ISSUE THREAD

**Issue by instantaphex** [godotengine/godot#37803]
**Godot version:**
3.2.1
**OS/device including version:**
MacOS Catalina 10.15
**Issue description:**
When adding a Call Method Track to the AnimationPlayer, I'm not able to use methods from attached script unless that script has the same name as the AnimationPlayer node itself.  
**Steps to reproduce:**
1.) Create an animation player
2.) Attach a C# script with a name that differs from the node name
3.) Add a Call Method Track to the animation player
4.) Add a keyframe and notice that none of the Script Methods are available for selection
5.) Change the name of the script to match the node name and add a keyframe.  The methods are now available

**Comment by IRONIC3D** [comment]
I had similar issue with GDScripts Built-in. After saving I have to quit and open Godot, the call-back function will see the script functions. That seems to solve the problem for me.

**Comment by akien-mga** [comment]
Fixed by #52607.
