### ISSUE TITLE
rpc_id() executes remotely, but not locally, even with the `remotesync` keyword

### ISSUE THREAD

**Issue by sapporovhs** [godotengine/godot#37809]
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Ubuntu 18.04 64-bit
**Issue description:**

`rpc_id()` executes remotely, but not locally, even with the `remotesync` keyword.

Details:

I created a simple match making server (remote, aws) that waits for two clients to connect (my pc and cellphone), pairs them and then provides them with each others' network peer ids.
That all works great.

The game starts and each client session remains connected to the server but performs `rpc_id()` calls on some game functions with the `remotesync' keyword, since I would like the functions to execute on the matched clients, but not the server or any other potentially connected clients.

The function is correctly called on the peer with id specified in my 'rpc_id(id, "func")' call, but it is not executed locally as it should be.

Replacing `rpc_id(id,"func")` with `rpc("func")` calls and executes correctly both locally and on the peer (but obviously also on the server and every other peer... so this is not really a solution)

Is this intended functionality? It seems a bit counterintuitive, since the docs claim that `remotesync` and `rpc_id()` are designed for this purpose.

Thank you.

**Comment by sapporovhs** [comment]
Update:

`rpc_id(id, "func")` + `remotesync` seems to work okay when `"func"` is a function in the calling node.
Calling, `child_node.rpc_id(id, "func")` in the parent node, where `"func"` is in the child, causes it to be called remotely but not locally, still.

**Comment by jonbonazza** [comment]
Do you have a minimal reproduction project you can provide as an example here?

**Comment by Faless** [comment]
Closing as there is no signal from the OP.

Feel free to comment if you still experience the issue, so we can reopen it in case.

**Comment by marcol1** [comment]
Currently experiencing this issue, or at least a similar one.

In the parent class, I have the following code:
`
@rpc("any_peer", "call_local")
func Sync_addImpulse(swingImpulseString : String):
	if multiplayer.get_remote_sender_id() == 0:
		rpc("Sync_addImpulse", swingImpulseString)
                print("forwarding rpc")
	else:
                # some code
		print("some code")
`

When I call Sync_addImpulse in the child class, the function is called (e.g., "forwarding rpc" is printed). However, the RPC isn't received.

To fix, this, I simply echoed the call in the child as follows:
`

@rpc("call_local", "any_peer")
func Sync_addImpulse(impulse): super.Sync_addImpulse(impulse)

`

Let me know if you have any questions or if I can help at all.

**Comment by marcol1** [comment]
@Faless, @Calinou sorry for the ping - not sure who to ask but can someone reopen this?
