### ISSUE TITLE
Consider moving time methods and enums out of OS

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#37800]
**Issue description:** https://docs.godotengine.org/en/latest/classes/class_os.html

The `Weekday` enum, the `Month` enum, and methods using them, such as `get_date`* and `get_unix_time_from_datetime`, aren't really related to operating systems, so it would make sense if they were moved elsewhere. Perhaps there should be a dedicated class for working with time?

4.0 milestone since this would break compat and therefore we should decide on it before 4.0 is out.

**Comment by Anutrix** [comment]
When doing so, I recommend replacing gmtime and localtime with thread safe versions.
