### ISSUE TITLE
Setting to configuring the 3D grid color

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#3781]
**Grid color**
it would be nice to change the grid color without recompiling the editor because with some background colors the green grid is really hard to see (and in my opinion i doesn't look good).
A color picker in ``Settings / Editor Settings / 3d Editor`` would be really nice
![image](https://cloud.githubusercontent.com/assets/16718859/13185191/1be1adec-d740-11e5-8913-eabb6f28f01a.png)

**Comment by nunodonato** [comment]
I've also experienced this inconvenience before, when using cubemaps for my background. I think the suggestion makes sense.
If the bosses are ok with it, I can do it and make a PR. :)

**Comment by toger5** [comment]
I got it done myself
![image](https://cloud.githubusercontent.com/assets/16718859/13193580/4b4b6df8-d77b-11e5-997e-688bc77e963e.png)
![image](https://cloud.githubusercontent.com/assets/16718859/13193638/fb7dfef2-d77b-11e5-96ff-4898e53c92db.png)

The way I did it you still have to restart Godot that the changes take effect. ;(
So it would be nice of you if you would do that. (If the bosses are ok)

**Comment by bojidar-bg** [comment]
I think nobody would be against such a feature, and as I like to say "more options in more options" ;)
