### ISSUE TITLE
Android export crashes on start

### ISSUE THREAD

**Issue by KutayGuler** [godotengine/godot#37814]
**Godot version:** 3.2.1

**OS/device including version:** Windows 10/Android

**Issue description:** Android export crashes when it's opened after a second of a black screen.

I have applied the solutions regarding this problem from different threads but the problem persists. But I couldn't find an identical error.

Here is the `adb logcat -s godot` output on cmd:

```
04-11 21:55:36.234 21610 21712 I godot   : Loading Android module: True
04-11 21:55:36.235 21610 21712 E godot   : **ERROR**: Couldn't find singleton for class: True.
04-11 21:55:36.235 21610 21712 E godot   :    At: platform/android/java_godot_lib_jni.cpp:691:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.
```
As for the errors in the output of Godot it's this:

```
Unicode error: invalid skip
Unicode error: no space left

```

Both Godot and export template versions are 3.2.1

**Comment by volzhs** [comment]
didn't you add an Android module at Project Settings > Android?

**Comment by KutayGuler** [comment]
> didn't you add an Android module at Project Settings > Android?

Android - Modules is on if that's what you are asking

**Comment by akien-mga** [comment]
> Android - Modules is on if that's what you are asking

That's not a boolean, it's a list of names of Android modules you want to enable. Unless your Android module is named "True", your config is wrong.

See https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html#using-it-from-gdscript
