### ISSUE TITLE
Dynamically loaded images not showing

### ISSUE THREAD

**Issue by michaelpbl** [godotengine/godot#37827]
Godot 3.2.1 64 bit version Running on Windows 10, latest update
A Player sits in a Seat spaced evenly around a Table.  If I add players chairs and players manually, it works just fine.
Chairs all use the same image so creating them dynamically works fine.

Player Scene is a 2DNode named Player with a single child, a Sprite Node. Currently Player images are just simple filled circles, distinguished by color. Dragging the white image to the Sprite node yields identical seats, each containing a white circle.

Code below is supposed to add them dynamically, giving a different colored player at each seat but (a) if I clear the Sprite image manually no images appears. (b) if I leave the manual Sprite image all seats contain a white circle.

The print statement reports
texture is set to [StreamTexture:1323]
texture is set to [StreamTexture:1332]
texture is set to [StreamTexture:1341]
texture is set to [StreamTexture:1350]
etc.

```
extends Node2D
var myPlayer
var isPresent
var playerName

# const references to the player sprite resources
const PLAYER_FILE1 = "res://sprites//player1.png"
const PLAYER_FILE2 = "res://sprites//player2.png"
const PLAYER_FILE3 = "res://sprites//player3.png"
const PLAYER_FILE4 = "res://sprites//player4.png"
const PLAYER_FILE5 = "res://sprites//player5.png"
const PLAYER_FILE6 = "res://sprites//player6.png"
const PLAYER_FILE7 = "res://sprites//player7.png"
const PLAYER_FILE8 = "res://sprites//player8.png"
const PLAYER_FILE9 = "res://sprites//player9.png"

var images = {1: PLAYER_FILE1, 2: PLAYER_FILE2,	3: PLAYER_FILE3,
	4: PLAYER_FILE4, 5: PLAYER_FILE5, 6: PLAYER_FILE6,
	7: PLAYER_FILE7, 8: PLAYER_FILE8, 9: PLAYER_FILE9
}

func _setMyPlayer(player, name):
	myPlayer = player
	playerName = name
	isPresent = true
	get_node("Sprite").texture = load(images[player])
	print("texture is set to " + str(get_node("Sprite").texture))
```

**Comment by KoBeWi** [comment]
Some minimal project?

**Comment by michaelpbl** [comment]
[Poker.zip](https://github.com/godotengine/godot/files/4466637/Poker.zip)

**Comment by KoBeWi** [comment]
So I ran the `Player.tscn` (had to add `_setMyPlayer` call to ready) and it works fine. Are you sure you call that method correctly?

**Comment by michaelpbl** [comment]
I don't understand what you mean exactly. 
The call is in the _setTable(numseats) function in Table.gd which sets the table with numSeats chairs around it

The code creates a new seat and then positions it about the round table then adds the seat as a node to the table. The seat itself already has a player node so I then execute a call to set the player node. Really unclear why it should be in _ready function. or how that would even work unless I can somehow pass number of seats I require to the ready function.
Sorry.  I was an experienced C++ and Java programmer but brand new to GDScript. I've read the documents carefully and looked at numerous other questions and answers before posting this. Here's the code I'm using. call at the end

		angleChange = deg2rad(360/numSeats)
		radius = (pHeight-60)/2
		for i in range(numSeats):
			newSeat = seatScene.instance()
			newSeat.position.x = pWidth/2  - radius * sin(angle)
			newSeat.position.y = pHeight/2 + radius * cos(angle)
			newSeat.rotation = angle
			angle += angleChange
		
		# Make sure seat node is part of the tree before calling one of its functions
			add_child(newSeat)
			# Find out why seats[i] = newSeat is not allowed
			seats.append(newSeat)
			newSeat._setMyPlayer(i+1, names[i])

**Comment by Zireael07** [comment]
I think you have your wires crossed. newSeat is an instance of seatScene. The code in OP you described as being for the player scene. Unless they are one and the same, you can't call newSeat._setMyPlayer(), you have to do whateveryourplayervariable._setMyPlayer. Think Player::_setMyPlayer() in C++

**Comment by michaelpbl** [comment]
My bad, I should have added that the Chair.tcsn script (which is the script for Seat nodes - I should fix that) has it's own function for relaying the call on to the Seat's Player node

func _setMyPlayer(player, name):
	var newPlayer = playerScene.instance()
	newPlayer._setMyPlayer(player, name)

**Comment by Zireael07** [comment]
It's likely you can't see the sprites because you're instancing the player scene, but not actually adding it to tree - only thing you're achieving is a memory leak.
Please post the project to make it possible for us to check whether it's a genuine bug, or a user error.

**Comment by michaelpbl** [comment]
I did post it. However, I created a much simpler example to duplicate the problem and got that to work. I'm sure you're close to right. Thank you and KoBeWi for your very timely help. It's been a long day so I'm going to call it quits right now. Pretty sure I can compare the two project sets and track down the problem tomorrow. I'll post the result when I do and close the thread. Thanks again!

**Comment by michaelpbl** [comment]
I'm beginning to think this might be a bug. I've created two simple versions to demonstrate. 

The first version creates a Table with 9 players arranged evenly around it. The players are created dynamically in the following function:

`func _setTable(numPlayers):
	print("Trying to set table with " + str(numPlayers) + " players")
	var newPlayer
	var angleChange
	var angle = 0
	var radius
	angleChange = deg2rad(360/numPlayers)
	radius = (pHeight-60)/2
	for i in range(numPlayers):
		newPlayer = playerScene.instance()
		newPlayer.position.x = pWidth/2  - radius * sin(angle)
		newPlayer.position.y = pHeight/2 + radius * cos(angle)
		newPlayer.rotation = angle
		angle += angleChange
	
	# Make sure seat node is part of the tree before calling one of its functions
		add_child(newPlayer)
		# Find out why seats[i] = newSeat is not allowed
		players.append(newPlayer)
		newPlayer._setMyPlayer(i+1, names[i])
`
_setMyPlayer is in the Player script as follows:

`var myPlayer
var isPresent
var playerName

# const references to the player sprite resources
const PLAYER_FILE1 = "res://sprites//player1.png"
const PLAYER_FILE2 = "res://sprites//player2.png"
const PLAYER_FILE3 = "res://sprites//player3.png"
const PLAYER_FILE4 = "res://sprites//player4.png"
const PLAYER_FILE5 = "res://sprites//player5.png"
const PLAYER_FILE6 = "res://sprites//player6.png"
const PLAYER_FILE7 = "res://sprites//player7.png"
const PLAYER_FILE8 = "res://sprites//player8.png"
const PLAYER_FILE9 = "res://sprites//player9.png"

var images = {1: PLAYER_FILE1, 2: PLAYER_FILE2,	3: PLAYER_FILE3,
	4: PLAYER_FILE4, 5: PLAYER_FILE5, 6: PLAYER_FILE6,
	7: PLAYER_FILE7, 8: PLAYER_FILE8, 9: PLAYER_FILE9
}


# Called when the node enters the scene tree for the first time.
func _ready():
	pass
#			

# 
func _setMyPlayer(player, name):
	myPlayer = player
	playerName = name
	isPresent = true
	get_node("PlayerSprite").texture = load(images[player])
	print("texture is set to " + str(get_node("PlayerSprite").texture))
'
This results in a table with 9 players arranged around it, each with it's own colored circle image, as expected.

Now we introduce an intermediate layer. Because a player may or may not be present, we create a simple chair. All chairs are identical. They are arranged around the table and each one has exactly one player. The Table script is identical except that Chairs are substituted for Players. here's the setTable function

`func _setTable(numSeats):
	var newSeat
	var angleChange
	var angle = 0
	var radius
	angleChange = deg2rad(360/numSeats)
	radius = (pHeight-60)/2
	for i in range(numSeats):
		newSeat = seatScene.instance()
		newSeat.position.x = pWidth/2  - radius * sin(angle)
		newSeat.position.y = pHeight/2 + radius * cos(angle)
		newSeat.rotation = angle
		angle += angleChange
	
	# Make sure seat node is part of the tree before calling one of its functions
		add_child(newSeat)
		# Find out why seats[i] = newSeat is not allowed
		seats.append(newSeat)
		newSeat._setMyPlayer(i+1, names[i])
`
The Seat is a simple 2DNode with a Chair sprite and a player. Its _setMyPlayer function simply relays the message

`func _setMyPlayer(player, name):
	print("Trying to set player no. " + str(player) + " to " + name)
	get_node("Player")._setMyPlayer(player, name)
`
The player Scene is identical to the original, as is it script
`# 
func _setMyPlayer(player, name):
	myPlayer = player
	playerName = name
	isPresent = true
	get_node("PlayerSprite").texture = load(images[player])
	print("texture is set to " + str(get_node("PlayerSprite").texture))
`
But The seats remain empty. The print statement proves that the function is being called but the sprite never shows

Here are the two complete demo projects

[DynamicImageLoad.zip](https://github.com/godotengine/godot/files/4469950/DynamicImageLoad.zip)

[DynamicImageLoadToSeat.zip](https://github.com/godotengine/godot/files/4469951/DynamicImageLoadToSeat.zip)

**Comment by KoBeWi** [comment]
Player sprite shows behind chair.
![image](https://user-images.githubusercontent.com/2223172/79134963-e6e88100-7dae-11ea-88b9-62c05abbaa5f.png)
![image](https://user-images.githubusercontent.com/2223172/79134976-ed76f880-7dae-11ea-835a-bdc6ea81f22b.png)

**Comment by michaelpbl** [comment]
The funny thing is I actually had that order in my original game but re-ordered it when reconstructing the simple example. Makes sense that they would be drawn in the listed order. Now I'll go back, look at the original and see what I'm not doing that I did do in the simple example
Thank you very much for your time and your patience.
