### ISSUE TITLE
Round or Switch Bug

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#37844]
**Godot version:**
3.2.1 stable
**OS/device including version:**
Windows 10
**Issue description:**
For some unknown reason, it doesn't understand that when a float is rounded to an int it should be an int and not still a float. in the example below, i have a vector with (90,0) that i use round on the X value, plug that value in to the switch and if it is an int=90 it should print 90... however it acts like 90!=90 and doesn't print that last print.
**Steps to reproduce:**
use round on any float, plug the int in to a switch, make sure the values are equal on both the round you get out and the switch case you want to run
**Minimal reproduction project:**
[Bug.zip](https://github.com/godotengine/godot/files/4469253/Bug.zip)

**Comment by bojidar-bg** [comment]
(Related to #19262)

Bug comes from the fact that round is listed as returning "int", but then proceeds to return "double".
https://github.com/godotengine/godot/blob/d4b211bb3d8c71dc48b933fe1cede6250069b857/modules/visual_script/visual_script_builtin_funcs.cpp#L510-L511
https://github.com/godotengine/godot/blob/d4b211bb3d8c71dc48b933fe1cede6250069b857/modules/visual_script/visual_script_builtin_funcs.cpp#L773-L777
https://github.com/godotengine/godot/blob/d4b211bb3d8c71dc48b933fe1cede6250069b857/core/math/math_funcs.h#L254
