### ISSUE TITLE
Android 2.3 compatibility [broken in 2.0, worked in 1.1]

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3784]
AndroidManifest.xml specifies **minimum API level 10** (corresponding to Android 2.3), so naturally one would assume that Godot would work on **Android 2.3** devices, but when I test a **Godot 2.0** app on what Godot identifies as "**Cingular Us HTC Holiday**" (ARMv7) it **fails silently**. When I install from storage, it says that there was a **problem parsing the package**.

I am able to run everything **without issue on Android 4.x devices**. (The only other difference is that the SD card for the 2.3 device is currently misplaced while the other two have SD cards.)

[image of my unscientific comparison: http://i.imgur.com/1KE8giM.png ]

Interestingly, **without the export templates** installed I was **able to install apps on 2.3** but of course they just gave me a **flashing grey screen** as there was no engine.

(Note: I don't have high expectations for the device as one of my rich neighbors left it in a freebie bin, and it may not represent all Android 2.3 devices, but I would recommend that some developer pick up a 2.3 device at the dollar store or something just to be able to test for compatibility. Maybe it's not a priority as 2.3 is kind of old now, but it supports the NDK and most of the phones from them have the same hardware as now so I don't really see any reason for them to be incapable of running Godot.)

Has anyone else tested Godot on a 2.3 device?

**Comment by kubecz3k** [comment]
@fluffrabbit well I was testing with 2.3 on Godot 1.0 (or 1.1 not sure) and it was working fine. Not sure if current state is intended/known.

**Comment by fluffrabbit** [comment]
@kubecz3k Thanks! I should have specified I was running 2.0. I'll have to test on 1.0 on the device to more scientifically deduce things as soon as I get a chance.

**Comment by fluffrabbit** [comment]
**IT WORKS WITH GODOT 1.1 STABLE** (1.1 stable of both editor and export templates)

Image: Truck Town running on Android 2.3
http://i.imgur.com/XbJJs1M.jpg

Albeit the Truck Town map never loads as there were other bugs related to Android at the time, but nowadays if whatever piece of code that broke compatibility were regressed I'm sure everything would be awesome.

**Comment by reduz** [comment]
I stopped caring about 2.3 compatibility long ago, too many problems and
very inefficient OS for 3D.

**Comment by reduz** [comment]
Officially Godot is 4.0+

**Comment by fluffrabbit** [comment]
Good to know.

**Comment by akien-mga** [comment]
Should the manifest be updated then to reflect that? https://github.com/godotengine/godot/blob/master/platform/android/AndroidManifest.xml.template

**Comment by kubecz3k** [comment]
It definitelly should, as far as I know the line 203 should be:
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="19"/>

since sdk=14 is an android 4.0

**Comment by fluffrabbit** [comment]
Woah, not so fast. There's always the off chance that Godot could run on some platform in between in an unexpected way. Rather than locking people out and forcing them to recompile the runtime with a lower API version (which nobody would think to do) I think it's better to document which versions of Android on which Godot is confirmed to work and not work. That sure beats trial and error and all that cryptic figuring that new users would have to do to correlate an API version with an Android OS version. I'd say put a comment about it in AndroidManifest.xml and update the relevant wiki page to specify which versions of Android Godot is supposed to work with.

**Comment by freemanfromgodotengine** [comment]
I have to say, that I am not really happy about not supporting old devices. From my Google Play stats it looks like Android 2.3.3-2.3.7 is still around 13% of all the users who downloaded my App.

I still own and use the smartphone (2-3 years old) with 2.3.6 that works just fine as a phone, map + gps, etc., keeping charge for a week or so (main reason I don't want newer models that last for a day or two).
Pity.

**Comment by fluffrabbit** [comment]
@freemanfromgodotengine I'm a little rusty in conventional Android app development (SDK & Java). I'm curious-- Is your app of the Godot variety or something else? What tells Google Play which versions of Android your app is compatible with?

**Comment by freemanfromgodotengine** [comment]
@fluffrabbit afaik Google Play knows the supported android version from AndroidManifest.xml that is always stored at the root of the apk file (in case of Godot it's build automatically when spitting out the apk).
I am afraid I do not follow? What do you mean by "Godot variety or something else"?

**Comment by fluffrabbit** [comment]
@freemanfromgodotengine

API level then?

What I mean is do you have a Godot app working on 2.3?

**Comment by freemanfromgodotengine** [comment]
Yes I do, but app was created with version around 2.0 alpha I think. Compiled from github, generally sometime short before Christmas. I tested it on Android 2.3.6

**Comment by fluffrabbit** [comment]
@freemanfromgodotengine The devs have every right not to support 2.3. I'm aware of certain problems with that version of Android. Still, that being a 2.0 build I can't help but wonder what changed between then and now that broke compatibility, or if the Android version is even the issue at all. Not a lot of 2.3 users I guess.

**Comment by fluffrabbit** [comment]
These days anyone can buy a new device with pretty badass hardware for $20, so I'm closing this issue under the assumption that nobody cares about Android 2.3 anymore.

**Comment by foxp552** [comment]
> These days anyone can buy a new device with pretty badass hardware for $20, so I'm closing this issue under the assumption that nobody cares about Android 2.3 anymore.
> 

Well I would do
