### ISSUE TITLE
Add option to create navigation mesh inside the editor itself.

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#3785]
If we need navigation in a level, we need to create the whole level in blender and create a navmesh and import it all along to the editor. 
Then later on, if we need to change the position of an object, we need to recreate the navmesh for that in blender(or any 3d application) and re import it.

If we can create the navmesh by a simple click of a button, similar to Unity, it would be better I think.
Thanks.

**Comment by kubecz3k** [comment]
Related feature request: https://github.com/godotengine/godot/issues/3271

**Comment by reduz** [comment]
Yeah, must integrate Recast

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by lorenzobeccaro** [comment]
3.0 will have this feature?? 😀 pretty pleaase!

**Comment by akien-mga** [comment]
Nope, but that's on the current roadmap for 3.1.

**Comment by Zireael07** [comment]
We have recast integration now, closing?

**Comment by akien-mga** [comment]
Recast is integrated indeed.
