### ISSUE TITLE
custom build template gives error when exporting project

### ISSUE THREAD

**Issue by eminvergil** [godotengine/godot#37852]
**Godot version**: 3.2.1-stable

**OS/device including version**: windows 10

**Issue Description**: 

when i export project with custom build template it gives this error : 

![Untitled](https://user-images.githubusercontent.com/17277419/79133196-4ac17880-7db4-11ea-85bd-022bd1bcd280.jpg)

**gradle version** : 6.3
**android gradle plugin version**: 3.6.0

**java version**:
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

any response would be appreciated.

**Comment by eminvergil** [comment]
i fixed this issue . if you come accross with this problem you can send me message so i can help you

**Comment by yazidyazidyazid** [comment]
Did you solve the problem. How did you do that? Am I suffering here?
