### ISSUE TITLE
Minor GUI Issues when setting the editor Additional Spacing above 0

### ISSUE THREAD

**Issue by Peter-Crawley** [godotengine/godot#37853]
**Godot version:** 3.2.1

**OS/device including version:** Ubuntu 18.04

**Issue description:** When using "Additional Spacing" on the editor gui customisation, it causes icons on the node tree to be misaligned.
![Screenshot from 2020-04-13 18-29-35](https://user-images.githubusercontent.com/49043380/79143674-90327580-7db5-11ea-867c-9a3c73866d68.png)

**Steps to reproduce:** Change Editor Settings > Theme > Additional Spacing, the misalignment becomes noticeable around 3.

**Minimal reproduction project:** A brand new project will do.

**Comment by Calinou** [comment]
I think we should do away with the Additional Spacing setting entirely, it adds a lot of complexity to the theme setup for little benefit.

**Comment by Peter-Crawley** [comment]
I now regret opening this issue... :(

**Comment by Calinou** [comment]
@Peter-Crawley We're in the process of simplifying the editor settings to remove seldom-used options anyway :wink:

**Comment by Peter-Crawley** [comment]
Will there be aa replacement for this option?

**Comment by Calinou** [comment]
@Peter-Crawley No, I don't think there needs to be one.

**Comment by PucklaMotzer09** [comment]
With `additional_spacing` set to 5:
![2022-10-12_19-31](https://user-images.githubusercontent.com/25499721/195409858-1e61e152-a580-4ee1-a77a-6fc9094324ef.png)

Looks good to me on Godot 4 beta 2

**Comment by YuriSizov** [comment]
Seems to be fixed in 4.0, according to reports.

**Comment by Peter-Crawley** [comment]
Nice to see this fixed lol, tbh I forgot this issue existed
