### ISSUE TITLE
Shift + f1 should always open help

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3786]
I think it would be great if shift+f1 could always open help popup. Currently there is no way to quickly open help f you are not in text editor (lets say I'm looking at 3d scene, and I'm wondering how some concrete node works). And even in text editor you need to select _something_, for this shortcut to work.
I'm quite sure there was a way to open help with keyboard in 1.1

**Comment by adderly** [comment]
+1

**Comment by nunodonato** [comment]
+1 I've also experienced this

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
To be honest I think it was nice when F1 was used for the help panel, F**2** for the **2**D viewport, F**3** for the **3**D viewport and F4 for the script editor. Since the help panel was removed, all shortcuts were moved one key to the left (F1 for 2D, F2 for 3D, F3 for script editor), but found the previous system more logical.

We could go back to the previous shortcuts and have F1 open the help search popup maybe.

**Comment by Faless** [comment]
> We could go back to the previous shortcuts and have F1 open the help search popup maybe.

Shouldn't we also move the `Help` section (tutorials/classref/help) into the main menu near `Export`? I always found it strange that they were hidden in the script tab (and that when you open the editor there is no help button at first).

![help](https://cloud.githubusercontent.com/assets/1687918/22327993/45f8a5c2-e3ba-11e6-8008-26a62ccfb1fc.png)

That button (and F1 shortcut) could also open a "unified" help:

![help_unif](https://cloud.githubusercontent.com/assets/1687918/22328005/58bf0548-e3ba-11e6-8a60-8efbf1d95f49.png)

Of course upon double clicking an element the full help will be opened in the script editor.
Does this make sense?

**Comment by akien-mga** [comment]
A kind of unified help dialog as proposed above would be really cool, I'm always puzzled as the two "Search Help" and "Classes List" in the script editor, where the former searches for strings in the whole help while the second one searches only for class names.

**Comment by RayKoopa** [comment]
I've been playing around with some unified dialog implementation. What no longer works is up/down/pgUp/pgDown from the textbox - how should I know in which list to move the selection up and down?

**Comment by Jerome67000** [comment]
This should be moved to 3.1 milestone if the PR is wainting 3.1

**Comment by akien-mga** [comment]
Not necessarily as the scope of the PR is 10 times bigger than what is being asked here, so this issue could be fixed independently. But it's also not critical for 3.0 at all (nor to any release IMO), so unassigning the milestone.

**Comment by 201604830** [comment]
I'm going to try to fix this.

**Comment by vorabrijesh** [comment]
I tried to fix this
Shortcut to open help menu - Shift + F1 #27114
see if this fixes the issue
