### ISSUE TITLE
"Export with Debug" - pdb files are not present in packed game.

### ISSUE THREAD

**Issue by Meister1593** [godotengine/godot#37864]
**Godot version:**
3.2.1 Mono release 64 bit

**OS/device including version:**
Linux  5.6.3-arch1-1, Arch rolling, 
mono 6.4.0, 
mono-msbuild  16.5.xamarinxplat.2020.01.10.05.36-1

**Issue description:**
When exporting project into folder, option **Export With Debug** actually doesn't copy mono pdb file into game to allow remote debugging exported project with c#.
Manually editing exported .pck file and placing .pdb file from `Project/.mono/temp/bin/Debug/Project.pdb`
into .pck file into `Project.pck/.mono/assemblies/Debug/Project.pdb` allows to catch breakpoints with debugger when running through `GODOT_MONO_DEBUGGER_AGENT` env var.
I used [this](https://github.com/bruvzg/gdsdecomp) program to unpack and pack game files with pdb.
**Steps to reproduce:**
1. Open any Godot Mono project that contains .cs (c#) files.
2. Export game with checkbox **Export With Debug**.
3. Listen for incoming connections through Mono Remote on port in your IDE.
4. Launch exported game with env var set
 Example: `GODOT_MONO_DEBUGGER_AGENT=--debugger-agent=transport=dt_socket,address=127.0.0.1:50500,server=n`
5. Connect and try to catch any debugger breakpoint in your program.

**Comment by Calinou** [comment]
cc @neikeq
