### ISSUE TITLE
SpringArm's "add_excluded_object" function does nothing

### ISSUE THREAD

**Issue by maksimp04** [godotengine/godot#37865]
**Godot version:**
3.2.1 stable (Steam latest version)

Situation: I've placed SpringArm at bottom of my character collision and writed "add_excluded_object" to my character so SpringArm shouldn't detect my character but it doesn't works. No errors. No warnings.

Code line:

> $leg.add_excluded_object(get_rid())

*leg = SpringArm
*script attached to KinematicBody (player)

**Comment by Calinou** [comment]
@maksimp04 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by maksimp04** [comment]
Just fixed it. Sorry for bother.

**Comment by Calinou** [comment]
@maksimp04 It would be useful to document how you fixed it so other people know how to solve the issue at hand :slightly_smiling_face:

**Comment by maksimp04** [comment]
Nothing unusual. Just forgot to apply gravity to player. But I can say one thing: SpringArm starts at _init() so when I print out hit point it says 0.0 (because it "was in player") until _ready() fires.
