### ISSUE TITLE
AnimatedTexture not working with AtlasTexture

### ISSUE THREAD

**Issue by metalfrog2018** [godotengine/godot#37860]
**Godot version:**
Godot 3.2.1

**OS/device including version:**
Windows 10 x64
GTX 960

**Issue description:**
AnimatedTexture not working with AtlasTexture

**Steps to reproduce:**
1. Setup the materal on a Non-quad mesh
3. use AnimatedTexture on Albedo
4. use AtlasTexture for each frame

![screen](https://user-images.githubusercontent.com/24874965/79180726-3b3a4200-7e3d-11ea-994c-d20c021cfe73.png)
![screen](https://user-images.githubusercontent.com/24874965/79180827-805e7400-7e3d-11ea-82e8-7969743e7a94.png)

**Minimal reproduction project:**
[AnimatedTexture.zip](https://github.com/godotengine/godot/files/4472832/AnimatedTexture.zip)

**Comment by metalfrog2018** [comment]
I know we can use separated image textures for AnimatedTexture, but it's useless when we have hundreds frames, also use too much image textures are inefficient on mobile platforms

**Comment by KoBeWi** [comment]
Atlases for AnimatedTextures are not going to be supported, see https://github.com/godotengine/godot/issues/33855#issuecomment-558367212

You should however be able to use AtlasTexture directly and animate its region with AnimationPlayer or script.

**Comment by kruglinski** [comment]
> 
> 
> Atlases for AnimatedTextures are not going to be supported, see [#33855 (comment)](https://github.com/godotengine/godot/issues/33855#issuecomment-558367212)
> 
> You should however be able to use AtlasTexture directly and animate its region with AnimationPlayer or script.

Manually insert 200 key frames in AnimationPlayer? forget about it, that's so fucked up!

and AtlasTexture are not support to use on Albedo in Godot 3.2, just tested it!

**Comment by KoBeWi** [comment]
> Manually insert 200 key frames in AnimationPlayer? forget about it, that's so fucked up!

You don't need to do this manually. Also you can use a Tween.

> and AtlasTexture are not support to use on Albedo in Godot 3.2, just tested it!

This might be a bug actually.

**Comment by elvisish** [comment]
Are there any plans for atlas to be supported in animated texture? This seems like a huge oversight and makes no sense why it wouldn't be supported.

**Comment by Gnumaru** [comment]
Quick note for future googlers.

Even though using an AtlasTexture as an AnimatedTexture frame is not supported, the opposite works. First you create and AnimatedTexture from an entire SpriteSheet. Then, create an AtlasTexture and use the previously created AnimatedTexture as your atlas, then setup the desired region.
