### ISSUE TITLE
Slider (and probably other Range-based controls) emit value_changed events when their values are updated directly

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#37876]
**Godot version:**
3.2 (Mono)

**OS/device including version:**
Win 10

**Issue description:**
When using sliders (`HSlider`, `VSlider`) that if you set the slider `value` property in code, then the `value_changed` signal is emitted. It is unclear if this is by design, but it does not match the the behaviour of other controls (e.g. `LineEdit`, which does not trigger a signal when you set the text value). It also makes working with the control a bit of a pain - every time you set a value to some new state, a signal is fired, and you end up with a bunch of boiler plate code to determine whether this was a user change, or a change by your own program.

I would normally expect that UI Controls should only send "changed" style signals when the user changes the value by interacting with the control, not when a state is set through code. Even if this is not the case, the behaviour should at least be consistent across Godot Controls.

**Steps to reproduce:**
1. Create a Slider control and listen to it's 'value_changed' signal.
2. Set the value of the slider in code (e.g. `$slider.value = 0.5`).
3. Observe the signal is fired without any user interaction.

**Minimal reproduction project:**
[Testing-Slider.zip](https://github.com/godotengine/godot/files/4476327/Testing-Slider.zip)

**Comment by andy-noisyduck** [comment]
Related to #19372. That ticket proposes "setter signals" for changed values, and mentions the inconsistent Range behaviour as an example, but we should probably track the 2 issues independently (they can be solved independently even if closely coupled).

The other ticket does raise a good point that fixing this would break backward compatibility for anyone relying on the current signal.

**Comment by ahmed6192** [comment]
https://github.com/godotengine/godot/files/4476327/Testing-Slider.zip

**Comment by allkhor** [comment]
Still here, tested on Godot 3.4.3 Stable.

**Comment by KoBeWi** [comment]
BaseButton has the same behavior. Changing `pressed` property emits `pressed` signal. The solution was to add `set_pressed_no_signal()` method (as there was some rationale for keeping the behavior). We could do similar for Ranges, i.e. add `set_value_no_signal()`.

**Comment by yikescloud** [comment]
You can use the "drag_ended" signal in HSlide  to achieve this effect
