### ISSUE TITLE
Vehicle and wheels not working correctly.

### ISSUE THREAD

**Issue by Albertolopezs** [godotengine/godot#37879]
Hello there, 

I've only been around a short time and this is the first time I've done video game development, so forgive me if the doubts are too basic. I haven't found a similar issue that could help me either, so I decided to open one.
I'm trying to make a scene of a car, I have everything configured, the wheels, with the rear as traction and the front as steering, and a small script to move. It doesn't work, though.
In the car scene I put a small plane to test the movement and the wheels move without control, even without applying any force to the engine. Then when I put it in the main scene I can't get it to move an inch.
The steering of the wheels works properly.

I hope you can help me, I upload a copy of the project so you can test it. The related scene is the VTC one, it is in the root path.

[Google Drive link](https://drive.google.com/file/d/1UrlvAibfsYVHPVkEEn9Iw7T1njcBxv6l/view?usp=sharing)

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
