### ISSUE TITLE
Windows: Screen tearing with borderless fullscreen

### ISSUE THREAD

**Issue by Demiu** [godotengine/godot#37889]
**Godot version:** 3.2.1-stable_win64

**OS/device including version:** Win10 Pro N 1909, 6600k, NVIDIA 1060 6GB

**Issue description:** There is screen tearing even with vsync enabled in project setting, but only if the borderless mode is enabled and if the window is the same size as display. 

**Steps to reproduce:** Download the project, run it, drag the black square around using RMB. There should be no screen tearing. Change the resolution to slightly below your display (so 1900x1000 for me) and enable borderless. Drag the black square around. There should be no screen tearing. Change the resolution to exactly match your display (with borderless still enabled), _there now should be tearing_. Disable borderless, the tearing should go away.

If it's necessary I may provide a recording of the screen illustrating this

**Minimal reproduction project:**
[VSyncTest.zip](https://github.com/godotengine/godot/files/4477785/VSyncTest.zip)

**Comment by Gerarama** [comment]
Same problem am talking about here : #35899

**Comment by Calinou** [comment]
@Demiu Can you still reproduce this after enabling **Display > Window > Vsync > Vsync Via Compositor** in the Project Settings?

**Comment by Gerarama** [comment]
> 
> 
> @Demiu Can you still reproduce this after enabling **Display > Window > Vsync > Vsync Via Compositor** in the Project Settings?

Check the comments i have done in #35899  for more information.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
