### ISSUE TITLE
Exported variables behave weirdly

### ISSUE THREAD

**Issue by CyborgCabbage** [godotengine/godot#37882]
**Godot version:**
v3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
Global variables initialized with an exported variable will use its default value and not the value that has been set in the inspector.

**Steps to reproduce:**

1. Create a new project.
2. Set Node2D as the root node.
3. Give it a script.
4. Paste in:
```
extends Node2D

export var exported: int

var test = exported

func _ready():
	print("These should always be the same: ")
	print(exported)
	print(test)
```
5. Set the value of "Exported" in the inspector to 100 
6. Run the project.
7. Observe the weird results:

These should always be the same:
100
0

**Minimal reproduction project:**
It would be faster to just do as described above.

**Comment by Calinou** [comment]
Does it work if you use `export var exported: int = 0`?

**Comment by MWFIAE** [comment]
This is because of the exported variables are set at a later point in time. 
(I did read that somewhere... But don't ask me where :D )

An easy solution would be to have your var test be an onready variable

```onready var test = exported```

Or just initialize it in the _ready function.

**Comment by CyborgCabbage** [comment]
Thank you, I didn't know "onready" was a thing. I still think it isn't intuitive but I'll close the issue because, from what you said, it seems that it has already been accounted for.
