### ISSUE TITLE
Launching on Arcolinux freezes system, won't launch

### ISSUE THREAD

**Issue by Validbit** [godotengine/godot#37886]
**Godot version:** (latest) 3.2.1-stable_x11.64

**OS/device including version:** 
- ArcolinuxB BSPWM (latest - 20.3.3)
- Device: Lenovo Yoga 720
CPU: Intel i5-7300HQ (4) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 1050 Mobile 
GPU: Intel HD Graphics 630 
Memory: 1463MiB / 7695MiB

**Issue description:** Gotod won't launch at all even at clean install of OS and full update (via pacman)
Detail:
It either:
- completlely freezes OS (with cursor, no change after 4m)
- shows only header ("Godot Engine v3.2.1.stable.official - https://godotengine.org")
- shows header and "nvc_screen_create:1111 - Error allocating PGRAPH context for M2MF: -16"

Tried with both dual and single monitor setup with reopening termite to launch godot. Could install proprietary graphics drivers or more dependencies for Godot but I don't see them listed anywhere.

**Steps to reproduce:** after extracting (default, stock extractor) just run it in terminal (default - termite)

**Minimal reproduction project:** (none)  - won't launch itself

**Comment by Calinou** [comment]
Which graphics driver are you using (Nouveau or NVIDIA proprietary)? Do other 3D games and applications work?

**Comment by Validbit** [comment]
Nouveau, just tried Blender and it seems to be working without a problem. Couldn't it really be just lack of dependencies? 

Thank you for the quick response.

**Comment by Calinou** [comment]
If you use open source drivers, Godot tries to use the dedicated GPU automatically as it sets the `DRI_PRIME=1` environment variable. Blender is most likely not doing this, which means it runs on the integrated GPU instead.

Does it work if you run `DRI_PRIME=0 path/to/godot.bin`?

**Comment by adabru** [comment]
> Couldn't it really be just lack of dependencies?

You can try installing the dependencies that are listed on godot's [AUR package](https://aur.archlinux.org/packages/godot/):

libxcursor
libxinerama
freetype2
alsa-lib
libxrandr
libxi
libglvnd

**Comment by Calinou** [comment]
@adabru Godot will most likely not even start at all if some of those dependencie are missing. Here, it's starting as expected, it just freezes early on, presumably due to a driver issue (`nvc_` is hinting at Nouveau).

**Comment by akien-mga** [comment]
@Validbit Could you post the output of those two commands:
```
DRI_PRIME=0 glxinfo | grep "OpenGL vendor"
DRI_PRIME=1 glxinfo | grep "OpenGL vendor"
```

**Comment by Ev1lbl0w** [comment]
Are you using a recent kernel? *(>5.4, at least)* I had some issues in my setup because the iGPU was hanging my whole system as soon as I started doing something intensive on the dGPU. From version 5.5 this issue was fixed.

**Comment by Validbit** [comment]
> If you use open source drivers, Godot tries to use the dedicated GPU automatically as it sets the `DRI_PRIME=1` environment variable. Blender is most likely not doing this, which means it runs on the integrated GPU instead.
> 
> Does it work if you run `DRI_PRIME=0 path/to/godot.bin`?

**Solved the problem**, seems to be working well now (tested some projects).

> DRI_PRIME=0 glxinfo | grep "OpenGL vendor"
_OpenGL vendor string: Intel_

> DRI_PRIME=1 glxinfo | grep "OpenGL vendor"
(the error described) 
_nvc_screen_create:1111 - Error allocating PGRAPH context for M2MF: -16_

> Are you using recent kernel?...
Yes, _5.6.4-arch1-1_

I have some observations and I'll create them as separate issues (as understood by guidelines)
Thank you for your quick support and have a nice day you all. :)

**Comment by Validbit** [comment]
Sorry for reopening - just wanted to ask what should I do want/need to use the nvidia graphics. If the proprietary is necessary if I wait or there is something else causing this.

_(I personally have no problem with installing those, just wanted to know current options)_

**Comment by Calinou** [comment]
@Validbit The proprietary NVIDIA drivers are often faster and more reliable than the Nouveau driver. Nouveau is the fruit of reverse engineering; it doesn't support reclocking on Maxwell and newer GPUs. This means the GPU and VRAM will always run at their boot clocks, even when a 3D application is running. This makes the graphics card very slow.
