### ISSUE TITLE
Blendmodes don't extend to children.

### ISSUE THREAD

**Issue by paraclete-pizza** [godotengine/godot#3789]
Children of a Node2D inherit its visibility, its opacity, etc. But do not inherit its blend mode.

As an example: I'm trying to set up a simple 2D 'spotlight' effect using blend modes and overlays (similar to [this older project made in Flixel](http://gildedgreen.com/cavepals/)).

To this end, I have a Node2D created, with its Blendmode set to multiply, then within that node, I have two sprites, a dark textured overlay, and a light flickering 'spotlight' overlay. I would assume the images within the Node2D would essentially function as a single, multiplying, layer. But, instead, both sprites just use the normal 'mix' blendmode, and are totally opaque, not inheriting their parent's blendmode.

![image](https://cloud.githubusercontent.com/assets/6827480/13198476/6da2a19e-d7d7-11e5-8da9-b2074949e4f7.png)

Actual result:
![image](https://cloud.githubusercontent.com/assets/6827480/13198481/8c11e0c2-d7d7-11e5-941a-1124839b7f8b.png)

Expected result:
![image](https://cloud.githubusercontent.com/assets/6827480/13198487/9f8a4da6-d7d7-11e5-9b21-2334893d28b2.png)

**Comment by akien-mga** [comment]
This is now solved in Godot 3.0 / the master branch.

Blend modes are still not automatically inherited, but they are now part of a CanvasItemMaterial, and all CanvasItem nodes have a `use_parent_material` property that can be toggled to achieve the required behaviour.
