### ISSUE TITLE
Button text FreeType-based outline out of sync if missing glyph exists

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#37901]
**Godot version:**
* 3.2.1.stable.official
* 4.0.dev.custom_build.5b4ea6529

**OS/device including version:** macOS 10.15.4

**Issue description:**

Button's text outline and the text itself go out of sync if there are characters not included in the font.

This does not happen to Label.

![demo](https://user-images.githubusercontent.com/372476/79326086-dbc75980-7f44-11ea-9dc3-2a5f61958e15.png)

**Steps to reproduce:**

Add a button, make sure it's using a Dynamic Font and font outline is enabled. Add some characters that are not included in the font.

**Minimal reproduction project:**

[FullwidthSpace-3.2.zip](https://github.com/godotengine/godot/files/4480544/FullwidthSpace-3.2.zip) is a 3.2.1 project (the issue also exists on current master). Text contains a fullwidth space and some Chineses characters that the InputMono font does not include. The scene should look like the screenshot above.

**Comment by akien-mga** [comment]
Fixed by #44679.
