### ISSUE TITLE
Invalid call. Nonexistent function called on a function that does exist

### ISSUE THREAD

**Issue by michaelpbl** [godotengine/godot#37907]
**Godot version: 3.2.1**

**OS/device including version: Windows 10 latest update
[PokerLightDemo.zip](https://github.com/godotengine/godot/files/4481372/PokerLightDemo.zip)
**
![TableScene](https://user-images.githubusercontent.com/63122053/79342544-d7308000-7f07-11ea-8db1-4668e1de655d.png)

I have a TableScene which includes a TableTop Sprite, a Dealer Node2D and a button. Dealer is a Scene itself and the inspector shows the script gas been loaded properly

The TableScript has a call to the Dealer Script that occurs when the button is pushed

`func _on_FreshDeckButton_pressed():
	print("Calling " + str(get_node("Dealer")) + " for a fresh deck")
	dealer.freshDeck()     # alternate version. Both calls trip the same error
	get_node("Dealer").freshDeck();

`
where dealer has been declared at the top of the script as
onready var dealer = $Dealer

Either version of the call trips the same error:
 Invalid call. Nonexistent function 'freshDeck' on base

The Dealer Script **does have the function**
`func freshDeck():
	print("Reached Dealer.freshDeck()")
	get_node("Deck").freshDeck()`

Moreover the editor recognizes it as a valid function. When I type out the first two letter as below

![EditorRecognition](https://user-images.githubusercontent.com/63122053/79343848-86218b80-7f09-11ea-9727-0de7fd562044.png)

the editor pops up freshDeck as a valid pick (I can't capture the popup as it disappears the moment I touch a screen capture key)

Yet when I run the program and hit the freshDeck button the InvalidCall appears, I thought this might have to do with the object somehow not being instantiated when the call was made but the debug clearly shows that the variable dealer DOES contain an object
![InvalidCall](https://user-images.githubusercontent.com/63122053/79344177-0942e180-7f0a-11ea-9ab0-8e47c68650fb.png)
ger 

I have been chasing this problem for days. It has done one thing for me, I certainly know the debugger a lot better than I did!
It sure seems like a bug that the editor recognizes the call as valid then it trips an error at run time.

**Comment by Zireael07** [comment]
If you click on the nodes in debugger, are they exactly the nodes you expect them to be? Do the names match up?

**Comment by michaelpbl** [comment]
As far as I can tell, yes. They're exactly what I expect. I'm clicking on the scene and checked Nodes in both Local and Remote. I exported an int variable in Dealer just to make sure. It shows up in Local mode with the value set correctly. However, in Remote mode, I'm not seeing any of its local variable where I am seeing them for other Nodes
Here are Table Members in inspector. Members are exactly what I would expect.
![TableMembers-6](https://user-images.githubusercontent.com/63122053/79360443-7f514380-7f1e-11ea-9fc9-5c3dee26eac9.png)
Table HAS a Dealer but its members don't show 
![DealerNoMembers](https://user-images.githubusercontent.com/63122053/79360529-a27bf300-7f1e-11ea-90be-0010286bd745.png)
However, Dealer, in its turn, HAS a Deck. whose member do show. Hard to believe that would happen if Dealer wasn't there. Maybe a clue???
![DeckMembers](https://user-images.githubusercontent.com/63122053/79360687-d5be8200-7f1e-11ea-8713-0b04ab9617b1.png)

**Comment by MWFIAE** [comment]
I found following error while running your code:

![image](https://user-images.githubusercontent.com/6072971/79382300-9bc39f00-7f63-11ea-9f89-790e878c6572.png)

Not sure whats causing it, but seems like an error while creating an object.

**Comment by MWFIAE** [comment]
Ah think I found it. 
You do have an init script in dealer which expects an argument. 
You can't do that since you placed the dealer in the scene itself. 
![image](https://user-images.githubusercontent.com/6072971/79382547-f230dd80-7f63-11ea-96d0-7b2ac41411c0.png)

after deleting it:
![image](https://user-images.githubusercontent.com/6072971/79382490-e0e7d100-7f63-11ea-8132-a3e1b3dfec32.png)

**Comment by michaelpbl** [comment]
That is exactly the error. I was trying a bunch of different things to try to understand instantiation and at one point created the init function. Since then I've realized that an init() function with arguments is only invoked by a new() call and not by a getInstance(). I guess I left it in because it didn't seem to be doing any harm. 
Of course, it is not caught at edit/compile time because it is quite possible that a script somewhere actually does invoke a Dealer with new().

Knowing what I know now, the lesson is, **if you are going to write an init() function with arguments always provide defaults for the arguments so the init function can be used with getInstance() or when your node is added directly to a scene**.

Thank you very much for your assistance. I was getting close to giving up on this.
It is a little intimidating to find this kind of error is so difficult to uncover in the debugger but I will certainly use expandAll on any errors that get thrown from now on.

**Comment by ThakeeNathees** [comment]
> I have been chasing this problem for days. 

@michaelpbl the invalid constructor must warn or throw some error, it does when tried to return a value but not for arguments, the parser might be enhanced for that case.
