### ISSUE TITLE
AnimationTrackEditor::_root_removed emits signal without arguments.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#37905]
**Godot version:**
Godot 3.2.1

**OS/device including version:**
Win10 64-bit

**Issue description:**
Not sure the exact way to trip this up, but on certain occasions when switching to and from tabs after doing some Animation, I get the following error message.

> ERROR: Object::emit_signal: Error calling method from signal 'tree_exiting': 'AnimationTrackEditor::_root_removed': Method expected 1 arguments, but called with 0..
>    At: core\object.cpp:1228
> ERROR: Nonexistent signal 'tree_exiting' in [AnimationPlayer:837170].
>    At: core\object.cpp:1537

Since I was able to trigger it for the time being by switching tabs, I attached a debugger and got the following trace.  Seems maybe a missing argument, but not sure what it was supposed to be.

> godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1228
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(1228)
> godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1275
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(1275)
> godot.windows.tools.64.exe!Node::_propagate_exit_tree() Line 303
> 	at C:\Godot\Version 3.2\Source\scene\main\node.cpp(303)
> godot.windows.tools.64.exe!Node::_propagate_exit_tree() Line 295
> 	at C:\Godot\Version 3.2\Source\scene\main\node.cpp(295)
> godot.windows.tools.64.exe!Node::_set_tree(SceneTree * p_tree) Line 2553
> 	at C:\Godot\Version 3.2\Source\scene\main\node.cpp(2553)
> godot.windows.tools.64.exe!Node::remove_child(Node * p_child) Line 1264
> 	at C:\Godot\Version 3.2\Source\scene\main\node.cpp(1264)
> godot.windows.tools.64.exe!EditorNode::set_current_scene(int p_idx) Line 3266
> 	at C:\Godot\Version 3.2\Source\editor\editor_node.cpp(3266)
> godot.windows.tools.64.exe!MethodBind1<EditorNode,int>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867
> 	at C:\Godot\Version 3.2\Source\core\method_bind.gen.inc(867)
> godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 921
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(921)
> godot.windows.tools.64.exe!UndoRedo::_process_operation_list(List<UndoRedo::Operation,DefaultAllocator>::Element * E) Line 294
> 	at C:\Godot\Version 3.2\Source\core\undo_redo.cpp(294)
> godot.windows.tools.64.exe!UndoRedo::redo() Line 338
> 	at C:\Godot\Version 3.2\Source\core\undo_redo.cpp(338)
> godot.windows.tools.64.exe!UndoRedo::commit_action() Line 260
> 	at C:\Godot\Version 3.2\Source\core\undo_redo.cpp(260)
> godot.windows.tools.64.exe!EditorNode::_scene_tab_changed(int p_tab) Line 4764
> 	at C:\Godot\Version 3.2\Source\editor\editor_node.cpp(4764)
> godot.windows.tools.64.exe!MethodBind1<EditorNode,int>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867
> 	at C:\Godot\Version 3.2\Source\core\method_bind.gen.inc(867)
> godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 921
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(921)
> godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1217
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(1217)
> godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1275
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(1275)
> godot.windows.tools.64.exe!Tabs::set_current_tab(int p_current) Line 417
> 	at C:\Godot\Version 3.2\Source\scene\gui\tabs.cpp(417)
> godot.windows.tools.64.exe!Tabs::_gui_input(const Ref<InputEvent> & p_event) Line 215
> 	at C:\Godot\Version 3.2\Source\scene\gui\tabs.cpp(215)
> godot.windows.tools.64.exe!MethodBind1<Tabs,Ref<InputEvent> const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867
> 	at C:\Godot\Version 3.2\Source\core\method_bind.gen.inc(867)
> godot.windows.tools.64.exe!Object::call_multilevel(const StringName & p_method, const Variant * * p_args, int p_argcount) Line 763
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(763)
> godot.windows.tools.64.exe!Object::call_multilevel(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 864
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(864)
> godot.windows.tools.64.exe!Viewport::_gui_call_input(Control * p_control, const Ref<InputEvent> & p_input) Line 1669
> 	at C:\Godot\Version 3.2\Source\scene\main\viewport.cpp(1669)
> godot.windows.tools.64.exe!Viewport::_gui_input_event(Ref<InputEvent> p_event) Line 1979
> 	at C:\Godot\Version 3.2\Source\scene\main\viewport.cpp(1979)
> godot.windows.tools.64.exe!Viewport::input(const Ref<InputEvent> & p_event) Line 2828
> 	at C:\Godot\Version 3.2\Source\scene\main\viewport.cpp(2828)
> godot.windows.tools.64.exe!Viewport::_vp_input(const Ref<InputEvent> & p_ev) Line 1446
> 	at C:\Godot\Version 3.2\Source\scene\main\viewport.cpp(1446)
> godot.windows.tools.64.exe!MethodBind1<Viewport,Ref<InputEvent> const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867
> 	at C:\Godot\Version 3.2\Source\core\method_bind.gen.inc(867)
> godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 921
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(921)
> godot.windows.tools.64.exe!Object::call(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 847
> 	at C:\Godot\Version 3.2\Source\core\object.cpp(847)
> godot.windows.tools.64.exe!SceneTree::call_group_flags(unsigned int p_call_flags, const StringName & p_group, const StringName & p_function, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 275
> 	at C:\Godot\Version 3.2\Source\scene\main\scene_tree.cpp(275)
> godot.windows.tools.64.exe!SceneTree::input_event(const Ref<InputEvent> & p_event) Line 431
> 	at C:\Godot\Version 3.2\Source\scene\main\scene_tree.cpp(431)
> godot.windows.tools.64.exe!InputDefault::_parse_input_event_impl(const Ref<InputEvent> & p_event, bool p_is_emulated) Line 442
> 	at C:\Godot\Version 3.2\Source\main\input_default.cpp(442)
> godot.windows.tools.64.exe!InputDefault::parse_input_event(const Ref<InputEvent> & p_event) Line 260
> 	at C:\Godot\Version 3.2\Source\main\input_default.cpp(260)
> godot.windows.tools.64.exe!InputDefault::flush_accumulated_events() Line 679
> 	at C:\Godot\Version 3.2\Source\main\input_default.cpp(679)
> godot.windows.tools.64.exe!OS_Windows::process_events() Line 2464
> 	at C:\Godot\Version 3.2\Source\platform\windows\os_windows.cpp(2464)
> godot.windows.tools.64.exe!OS_Windows::run() Line 3159
> 	at C:\Godot\Version 3.2\Source\platform\windows\os_windows.cpp(3159)
> godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 162
> 	at C:\Godot\Version 3.2\Source\platform\windows\godot_windows.cpp(162)
> godot.windows.tools.64.exe!_main() Line 184
> 	at C:\Godot\Version 3.2\Source\platform\windows\godot_windows.cpp(184)
> godot.windows.tools.64.exe!main(int _argc, char * * _argv) Line 196
> 	at C:\Godot\Version 3.2\Source\platform\windows\godot_windows.cpp(196)
> 

**Steps to reproduce:**
Unclear at the moment.  Is related to switching scenes in the editor and the state of one's AnimationPlayer.

**Minimal reproduction project:**
N/A

**Comment by dweremeichik** [comment]
I am also seeing this, but when I close out of a scene that has an animation player:

> ERROR: emit_signal: Error calling method from signal 'tree_exiting': 'AnimationTrackEditor::_root_removed': Method expected 1 arguments, but called with 0..
>    At: core/object.cpp:1257
> ERROR: Attempt to disconnect a nonexistent connection to signal 'tree_exiting' in [AnimationPlayer:29805], with target '_root_removed' in [AnimationTrackEditor:9502].
>    At: core/object.cpp:1569
