### ISSUE TITLE
Load all AARs with android plugins by default

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#37916]
**Godot version:**
Godot 3.2.2.rc (36a30f681f)

**OS/device including version:**
MacOSX 10.14.6 (18G95)
Android 8.1

**Issue description:**
I have spend one hour in order to find why my own android plugins does't work.
https://github.com/godotengine/godot/blob/master/platform/android/java/app/build.gradle#L44
I think that instead of `GodotPayment*.aar` should be `*.aar`

@m4gr3d What do you think?
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by m4gr3d** [comment]
@DrMoriarty in order for the plugins to be loaded, their names (which should match their filenames prefix) should be added to the Plugins in the Android export window.

If you look at the Gradle build file, there's logic below the line that you're referring to which gets the location and the names of the plugins to load.

This is done too ensure that the user has control over what plugins actually get to run at runtime. For example even though GodoPayment is listed in the Gradle build file, it's not activated at runtime unless the user adds it to the list of Plugins in the Android export window.

**Comment by DrMoriarty** [comment]
I have added my plugins in project export settings and they have not been linked when I export APK.
So I need add them in plugins list. Then I have go to android/build/build.gradle line 59 and again add them in line `implementation fileTree(dir: 'libs/plugins', include: ["GodotPayment*.aar", "MyOwnPluginOne*.aar", "MyOwnPluginTwo*.aar"]) `

I think that this is too complicated.

**Comment by m4gr3d** [comment]
All the plugins must go in the `res://android/plugins` directory, not in the `res://android/build/libs/plugins`.
That's likely why your plugins were not picked up since they were in the wrong directory.

**Comment by DrMoriarty** [comment]
Ok. My fault.

**Comment by m4gr3d** [comment]
No problem :)

Let me know if you run into other issues, or have additional feedback.
I'm trying to polish the implementation prior to the 3.2.2 release so any feedback is appreciated.

**Comment by kienvn** [comment]
hi, i tried build admob plugin aar, when use this plugin, I have to still add Admob's dependence in android/build/build.gradle?

**Comment by DrMoriarty** [comment]
@kienvn what exactly plugin do you use?

**Comment by kienvn** [comment]
[Admob.zip](https://github.com/godotengine/godot/files/4516810/Admob.zip)
I build Admob plugin, which has dependency: 'com.google.android.gms:play-services-ads:19.1.0'

**Comment by DrMoriarty** [comment]
yes, you should add manually dependencies into your android/build

**Comment by kienvn** [comment]
Hmm, not easy to implement, I think we need some script or config for plugin to do this
