### ISSUE TITLE
Tileable 3D texture not displaying correctly: flags are not saved properly for a JPG texture

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#3791]
On a 3d object, I have changed the UV texture to UVform and am trying to get it to tile 2 times. The UV Xform is all set to zero except for xx,yy,zz which are all on 2. I have the "repeat" flag on in the texture.

All looks correct in the 3d viewport exactly a I would suspect. However when I run the game, the "repeat" flag is quite clearly turned off (with the telltale striped stretched texture on the edges) and looks the same as if I had the flag turned off in the viewport.

I have attached a basic project highlighting the bug. When you open this project you will notice that the repeat flag is turned off, but I had saved it with it on! Try turning on the repeat flag, then saving, close down Godot and reload. the flag will have been automaticially turned off.

[uv_repeat_bug.zip](https://github.com/godotengine/godot/files/139463/uv_repeat_bug.zip)

Viewport screencap
![uvx2_viewport](https://cloud.githubusercontent.com/assets/7741669/13201001/00af0622-d8b3-11e5-9592-fa4b8e0d9ebd.png)

Ingame screencap
![uvx2_ingame](https://cloud.githubusercontent.com/assets/7741669/13201004/180b6d24-d8b3-11e5-9ca6-774cca3fbdf2.png)

**Comment by akien-mga** [comment]
Thanks for the test project, I could reproduce the issue.
It seems indeed that the flags are not saved when changing them in the diffuse texture of the material override. I tried clicking "Save" but it then gives an alert "Error saving resource!".

I could workaround the issue by creating ``ground.jpg.flags`` manually and adding ``repeat=true`` into it, but that's clearly not the intended design :)

**Comment by zendorf** [comment]
Just found out that there is a "repeat" global flag under Project Setting>Image Loader. When I turn it on, this scene works correctly. Which begs the question, why would you need a global flag for this when obviously every texture in your project will not be repeated, and why would the flag be off?

Wouldn't it be better to have this global flag enabled by default and then get rid of it in the Project Settings? What advantage would there be to having this turned off? Regardless, there is still some sort of buginess with the local repeat flag turning itself off in the project file that would be worth investigation!

**Comment by fracteed** [comment]
@akien-mga this issue can be closed!
