### ISSUE TITLE
GDScript nested if else parse error

### ISSUE THREAD

**Issue by NightIsland** [godotengine/godot#37925]
This code doesn't compile:
`

	if Input.is_action_pressed("ui_up"):
		if speed < 32: speed++
	else:
		if speed > 0: speed--
`
I gives an "Error parsing expression, misplaced '\n'" on the first character of the else: line.
I assume it's trying to bind the else to the most recent if, but ignoring the tab indentation (classic problem with languages that rely on indentation and don't have block delimiters).
It's hard to see how else I could write this code without being really long winded.

**Comment by MWFIAE** [comment]
Note to future Readers: Error is caused by the not supported ++ and -- expression. 
Please use += 1 or -= 1 instead.
