### ISSUE TITLE
[Mono] [Linux] Exported game crashing while outside project directory

### ISSUE THREAD

**Issue by Mek101** [godotengine/godot#37920]
**Godot version:** 3.2.1.stable.mono.official

**OS/device including version:** Linux Mint 19.3

**Issue description:**
After exporting a C# scripted game and copying the the file (executable and .pck) outside the project folder, attempting to start the game results in a crash.

According to my investigations so far, when launched the game opens the `libmono-native.so` file in the project directory (my case: `Invaders. 19782 mek101  mem       REG                8,2  3503977 18743425 /mnt/Dati Linux/mek101/Projects/Giochi/Godot/Invaders/data_Invaders/Mono/lib/libmono-native.so`), which isn't exported with the rest of the game. If it fails to do so, the game appears to crash, in my case with the following exception:
```
mek101@mint19-desktop:~/Scrivania$ ./Invaders.x86_64 
Godot Engine v3.2.1.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 950/PCIe/SSE2
 
Mono: Logfile is: /home/mek101/.local/share/godot/app_userdata/Invaders/mono/mono_logs/2020_04_15 22.33.48 (20247).txt

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'System.Random' threw an exception. ---> System.DllNotFoundException: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.GetNonCryptographicallySecureRandomBytes(byte*,int)
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) [0x00000] in <8a11cb089f0046488a9b0fb26e056b58>:0 
  at System.Random.GenerateGlobalSeed () [0x00000] in <8a11cb089f0046488a9b0fb26e056b58>:0 
  at System.Random..cctor () [0x00000] in <8a11cb089f0046488a9b0fb26e056b58>:0 
   --- End of inner exception stack trace ---
  at Invaders.Level.SpawnPointController..ctor () [0x00019] in <fa5289159e2f4bc89124cc2897c07114>:0
```

But I doubt it a problem related only to System.Random

**Steps to reproduce:**
Create a new godot project, instantiate a node with a C# script and create a new `System.Random` instance inside the script. Then, export the project, copy the executable outside the project folder (with it's .pck), and run it from the terminal

**Comment by Mek101** [comment]
Here's the related log: [2020_04_15 22.33.48 (20247).txt](https://github.com/godotengine/godot/files/4483717/2020_04_15.22.33.48.20247.txt)

**Comment by akien-mga** [comment]
Did you forget to copy the data_Invaders folder? Make an export in a dedicated folder to see all files which are part of the export.

**Comment by Mek101** [comment]
> Did you forget to copy the data_Invaders folder? Make an export in a dedicated folder to see all files which are part of the export.

I... didn't know that. Probably there should be a more explanatory error in place, but I'll close the issue anyway
