### ISSUE TITLE
Accessing exported C# Lists elements altered by the editor crashes the engine

### ISSUE THREAD

**Issue by realbrazilhours** [godotengine/godot#37934]
**Godot version:**
v3.2.1.stable.mono.official (Win64)

**OS/device including version:**
Microsoft Windows 10 [version 10.0.18362.592]

**Issue description:**
C# Lists created & exported to editor crashes the engine when trying to access one of it's elements.
Doesn't matter if it's an int or a custom Godot type, it will crash.

**Steps to reproduce:**
The steps I took to get the error purposefully (I first discovered it on my personal project and rectified it already by using the Godot.Collections Array type):

Create Node/Scene/Whatever -> Create .cs script -> Create an exported (don't forget to use System.Collections.Generic) List<T> variable -> Add values through editor -> Save/Build

Then try to access any of the elements, doesn't matter if it's a GD.Print or a `foreach` function.

Included project will have a `GD.Print()` commented out on the script. Lists whose values were added by code won't crash (also included with the project).

**Minimal reproduction project:**
[ListCrash.zip](https://github.com/godotengine/godot/files/4486887/ListCrash.zip)

**Comment by IlyaStuurFedorov** [comment]
Is System.Collections.Generic.List even unmarshallable by Godot in the first place?

**Comment by realbrazilhours** [comment]
> Is System.Collections.Generic.List even unmarshallable by Godot in the first place?

honestly idk, doesn't seem to give any errors other than "invalid index" when trying to access an int list; my previous attempt using Resource didn't give anything nor a log when it crashed. 
One "enhancement" report from 2018 (Issue #15467) mentions they're not currently supported, but I've not seen any other reports since then related to this issue nor any known gotchas though.

**Comment by neikeq** [comment]
Yes, the marshalling for these types is broken right now. I'll try to fix it for 3.2.2.

**Comment by realbrazilhours** [comment]
thanks!

**Comment by nhold** [comment]
Yep, there is a simple workaround for this:

```
using System.Collections.Generic;
using System.Linq;

public class Example : Node2D
{
	[Export] private List<int> test;

	public override void _Ready()
	{
		test = test.ToList(); // Now use test as normal.
	}
}
```

The reason why it does this can be found here:

[Smoosh!](https://github.com/godotengine/godot/blob/058a0afdeca83145d58a95c426dd01216c397ea9/modules/mono/mono_gd/gd_mono_marshal.cpp#L1084)

I'm wondering if it's better to just call a constructor if one exists for the IEnumerable type on the type we are actually assigning to. [e.g original code here: ](https://github.com/godotengine/godot/blob/058a0afdeca83145d58a95c426dd01216c397ea9/modules/mono/mono_gd/gd_mono_marshal.cpp#L778)
