### ISSUE TITLE
Method move_and_collide always returns null 

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#37936]
**Godot version:**
v3.2.2.rc.custom_build.36a30f681

**OS/device including version:**
Windows 10

**Issue description:**
Method move_and_collide returns null when KineticBody2D collides with RigidBody2D
and should return instance of KinematicCollision

**Minimal reproduction project:**
[GodotCollisionBug.zip](https://github.com/godotengine/godot/files/4487479/GodotCollisionBug.zip)
Remember to enable Debug->Visible Collision Shapes

**Comment by pgoral** [comment]
I just noticed that when I set infinite_inertia = false than it works.

**Comment by madmiraal** [comment]
This is by design. As per the [documentation](https://docs.godotengine.org/en/stable/classes/class_kinematicbody2d.html#class-kinematicbody2d-method-move-and-slide) (for `move_and_slide()`):
> If `infinite_inertia` is `true`, body will be able to push `RigidBody2D` nodes, but it won’t also detect any collisions with them. If `false`, it will interact with `RigidBody2D` nodes like with `StaticBody2D`.
