### ISSUE TITLE
"Fix Dependencies" dialog opens, but does not work for non-binary scenes types

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#3794]
**Operating system or device:**
Tested on FreeBSD & Win7

**Issue description** (what happened, and what was expected):
The dialog to fix missing dependencies when opening a scene opens for all scene types, but actually setting a new file is only possible for `.scn` files.

Also, there's a `Fix Broken` button at the top of of the `Fix Dependencies` dialog, does this have any use or can it be removed?

**Steps to reproduce:**
1. Create a new project
2. Add a Sprite root node and set `icon.png` as texture
3. Save scene as .tscn 
4. Close scene
5. Rename `icon.png` to e.g. `icon2.png`
6. Reopen scene
7. In the missing dependency dialog, click `Fix Dependencies`
8. try to fix external resource `icon.png` by reassigning it to e.g. `icon2.png`
9. Observe that reassigning does not work (assigned file does not change)
10. Repeat with .scn -> reassigning works

**Comment by reduz** [comment]
works for me...

**Comment by eska014** [comment]
That's weird, can anyone else reproduce this? Made a gif of the Fix dependencies dialog:

For `.tscn`:
![fix-deps-tscn](https://cloud.githubusercontent.com/assets/6996191/13204948/4ca25a06-d8dc-11e5-87ad-0bca8ac16b9f.gif)

For `.scn`:
![fix-deps-scn](https://cloud.githubusercontent.com/assets/6996191/13204953/5e7d938a-d8dc-11e5-8ba2-32fbeb15fc81.gif)

**Comment by rgrams** [comment]
Never used binary files, but can definitely confirm that it doesn't work with .tscn. Also Win 7 here.

**Comment by eska014** [comment]
Checked again and it actually does work on FreeBSD. It only happens on Windows.
The FileAccess blocks and needs to be closed, I'll make a PR

**Comment by quantum-entangler** [comment]
Still having this issue with the 2.0 official release/build and .scn files on Windows 7 64 bit.

 `core/io/resource_format_binary.cpp:434 - Couldn't load resource: res://GUI/Themes/Fonts/CinzBitmap16.fnt`
