### ISSUE TITLE
Scroll wheel doesn't scroll script editor in IDE with Smooth Scrolling enabled.

### ISSUE THREAD

**Issue by jomilam** [godotengine/godot#37943]
v3.2.1.stable.official

Windows 10

The mouse scroll wheel doesn't scroll the file up or down in the script editor window in the IDE, when "Smooth Scrolling" is on. The scroll wheel works in other windows/panes with "Smooth Scrolling" on, but not in the main text editor pane of the script editor. To allow scrolling of script files, turn "Smooth Scrolling" off.

To Reproduce:
Go to Editor > Editor Settings... > Text Editor > Navigation 
Check "On" next to "Smooth Scrolling".

**Comment by Calinou** [comment]
> The scroll wheel works in other windows/panes with "Smooth Scrolling" on

This is because smooth scrolling only applies to the script editor, not other ScrollContainers.

**Comment by jomilam** [comment]
You're right. I did increase the projects's physics FPS, so this is a duplicate.
Sorry, my mistake.
Duplicate of #28385
