### ISSUE TITLE
Inconsistent warning behavior for Dictionary.erase return value

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#37952]
**Godot version:** V3.2.1

**OS/device including version:** Windows 10

**Issue description:**
The [Dictionary.erase](https://docs.godotengine.org/en/stable/classes/class_dictionary.html#class-dictionary-method-erase) function returns a value.
Usually when I do not use the return value, then I get a "RETURN_VALUE_DISCARDED" warning.

However in some cases I do not get the "RETURN_VALUE_DISCARDED" warning when not using the return value.

I would expect that either I get the warning in all cases or that I never get the warning.

**Steps to reproduce:**

```
func _ready():
	var m: Dictionary = {"a": {"b":{}}}
	if m.a.b.empty():
		m.a.erase("b") # I get no warning
		if m.a.empty():
			m.erase("a") # I get a warning
```
Edited: and a simpler example:
```
func _ready():
	var m: Dictionary = {"a": {"b": 1}}
	m.a.erase("b") # I get no warning
	m.erase("a") # I get a warning
```

**Minimal reproduction project:**
[EraseReturnValue.zip](https://github.com/godotengine/godot/files/4491212/EraseReturnValue.zip)

**Comment by HaSa1002** [comment]
The second warning is shown, because a bool is returned. Investigating further. Perhaps I find some more

**Comment by HaSa1002** [comment]
The first time `func_type.has_type == false` and the `func_type.kind == UNRESOLVED`

**Comment by Sauermann** [comment]
So `m` is known to be a dictionary and `m.erase()` is known to be `Dictionary.erase()`.
But the type of `m.a` is not known and the debugger does not associate `m.a.erase()` with `Dictionary.erase()` and can not issue the warning.
The more I think about it, the more I believe, that this works as intended, because the debugger can not identify the type of `m.a` in this stage?

**Comment by HaSa1002** [comment]
Speaking of return values... shouldn't that https://github.com/godotengine/godot/blob/3fb4db96287404ff393f8cf8086148707a9ae9a3/modules/gdscript/gdscript_parser.cpp#L7091-L7094
be saved into `base_type`?

**Comment by gantsevdenis** [comment]
Just for the record: in python's shell, the type is inferred
```
d = {'a':{},"b":[]}
>>> d['b'].appe # "append" is auto comleted here
```

**Comment by HaSa1002** [comment]
@gantsevdenis What has that to do with the issue?

**Comment by gantsevdenis** [comment]
Documentation clearly compares gdscript to python in many aspects, so i found interesting to underline the behaviour, contrary to the following questionning `The more I think about it, the more I believe, that this works as intended..`

**Comment by HaSa1002** [comment]
Yeah okay, but GDScript is *not* Python and it's not the intent to copy Python. However I agree, that it feels like a bug, because the parser should know what it is calling.

**Comment by Sauermann** [comment]
Have a look at this case:
```
var m: Dictionary = {"a": {"b": 1}}
if file.open(path):
    m.a = []
m.a.erase("b")
```
The type of `m.a` for the erase function depends on whether the file at `path` exists.
If the file exists then it would be correct to not show the warning, because m.a is an Array and Array.erase() returns void.
If the file does not exist, then the warning should appear, because m.a is a dictionary.

The python example is a different case, because at the moment of the autocompletion, python knows what d['b'] is.
In contrast to this, in my case the warning generator would have to make a runtime-analysis of what m.a is. (Continue this example and let concurrently run a shell script, that loops and generates the file at `path` and deletes it afterwards once every 5 seconds ... should the warning appear and disappear every 5 seconds?)

I am closing this issue, because now I am quite certain, that the warning generator is not supposed to make a runtime-analysis of the code.
