### ISSUE TITLE
Bug When Playing A Scene With A Video Player

### ISSUE THREAD

**Issue by CDGames1** [godotengine/godot#37978]
**Godot version:**
3.2.1 Stable

**OS/device including version:**
Windows

**Issue description:**
when I start A Godot Scene With A VIdeo Player It Just Goes To Not Responding

**Steps to reproduce:**
Try To Fix The Crash Rate ???????????????

![image](https://user-images.githubusercontent.com/63894306/79628607-736fb680-8196-11ea-894a-499f634e7a55.png)

**Comment by akien-mga** [comment]
We can't do anything if you don't provide steps to reproduce or a minimal reproduction project.

**Comment by volzhs** [comment]
prefer to give a minimal project in this case...

**Comment by bojidar-bg** [comment]
Potential duplicate of #37648?

**Comment by Calinou** [comment]
Duplicate of #37648.
