### ISSUE TITLE
Should Transform2D.xform transforms Rect2 width and height?

### ISSUE THREAD

**Issue by pgoral** [godotengine/godot#37979]
**Godot version:**
v3.2.2.rc.custom_build.36a30f681

**Issue description:**
I have just noticed that xform also transforms width and height of Rect2. I'm little surprised. Should it work like that? Shouldn't it just translate the position?

**Comment by aaronfranke** [comment]
Yes, it should work like it currently does. If you just want to change the position. you can use:

    my_rect.position += my_transform.origin
