### ISSUE TITLE
Building from code 3.2 branch (dozen of errors related to strings)

### ISSUE THREAD

**Issue by CROmartin** [godotengine/godot#37986]
**Godot version:**
Godot 3.2 pulled from github branch
**OS/device including version:**
Windows 10
**Issue description:**
 Initializing building Godot 3.2 with scons in VS native tools CMD results in dozens of error I am guessing related to c++ string library, probably because it is undeclared. 
Here is errors picture:
![image](https://user-images.githubusercontent.com/26621064/79637948-34843580-8183-11ea-9b9d-13c327bf952b.png)

**Steps to reproduce:**
Classical win 10 setup for building Godot from source: python 3.8.0, pywin32, scons 3.1.1., godot 3.2 pulled from github. Initializing building with scons 10 threads and targeted win platform. 
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
You probably lack the Windows 10 SDK in your Visual Studio installation.

**Comment by CROmartin** [comment]
> You probably lack the Windows 10 SDK in your Visual Studio installation.

Ah the classic shot with Win 10 SDK, it is not that. I also should hint that I can build Godot 4.0 with no problems, of course after I fix missing library problem.

**Comment by RaTcHeT302** [comment]
did you download these?
![](https://i.imgur.com/wxETCAX.png)
![](https://i.imgur.com/sACy1cC.png)

**Comment by CROmartin** [comment]
> did you download these? i haven't had time to play with godot so i can't help much
> ![](https://camo.githubusercontent.com/183c281efeb75166508dfa343920ea6324e732c1/68747470733a2f2f692e696d6775722e636f6d2f777845544341582e706e67)
> ![](https://camo.githubusercontent.com/5354d40ecbd4d158bd7455a42743a3c7c7f358fe/68747470733a2f2f692e696d6775722e636f6d2f734143793163432e706e67)
> 
> i had to run this first, so that things would be setup correctly for me
> ![](https://camo.githubusercontent.com/7c4a752afb35b4cb7710b0253ef8303e9482e59c/68747470733a2f2f692e696d6775722e636f6d2f734e4b36596c4f2e706e67)
> 
> i just close it after it says "environment initialized"
> ![](https://camo.githubusercontent.com/6882e045d2d87e5246ee923e9cbbcc7d43ed0153/68747470733a2f2f692e696d6775722e636f6d2f4d5041526a4b4e2e706e67)
> 
> when i compile the engine, i just have a bat file which runs these commands
> (i don't use the "native tools" command prompt like you did, just a plain bat file)
> pushd just selects a folder called "Engine"
> 
> ```
> pushd "Engine"
> scons -j 16 platform=windows target=debug vsproj=yes
> ```
> 
> ![](https://camo.githubusercontent.com/f5acfd1b1fcbf8c712b2865f6c0d4516740d9e90/68747470733a2f2f692e696d6775722e636f6d2f696f4639416b412e706e67)

I did install everything needed, as I said I am 100% sure that errors is happening because Godots 3.2 instability. I am quite confused where did you find this .bat files?

**Comment by CROmartin** [comment]
Bug still exists
