### ISSUE TITLE
Clicking new scene from "Scene" popup menu opens 2 new scene tabs

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#37988]
**Godot version:**
Godot Engine v4.0.dev.custom_build.d817be92c
Does **NOT** occur on 3.2 Stable

**OS/device including version:**
Win 10 1903

**Issue description:**
Scene > New Scene opens 2 scene tabs, not one (2 new scenes are created)

**Steps to reproduce:**
As above.

**Minimal reproduction project:**
N/A

Via breakpoints I have seen that

https://github.com/godotengine/godot/blob/d817be92c2d9edce842ab37ab13117743f8a3bee/scene/gui/popup_menu.cpp#L296-L304

Is reached twice, both with pressed = false.
Through some print strings at:
https://github.com/godotengine/godot/blob/d817be92c2d9edce842ab37ab13117743f8a3bee/scene/main/window.cpp#L884

The mouse up (pressed = false) event is being fired twice.

![image](https://user-images.githubusercontent.com/41730826/79639357-c5ccc980-81ce-11ea-98a8-55bcd58f9816.png)

I think this issue is beyond my knowledge at this stage.

**Comment by KoBeWi** [comment]
Could be related to #37331 (and thus will fixed by the same PR)

**Comment by akien-mga** [comment]
Assuming fixed by #37519 as mentioned by @KoBeWi. Please comment if you can still reproduce it.
