### ISSUE TITLE
Array size differs when explicitly declared

### ISSUE THREAD

**Issue by michaelpbl** [godotengine/godot#37993]
**Godot version:** 3.2.1 stable official

**OS/device including version:** Windows 10 updated on desktop

**Issue description:** Array size depends on how it's declared in very deceiving fashion

**Steps to reproduce:** `extends Node2D

const ARRAY_SIZE = 10

var array1 = [ARRAY_SIZE]
var array2 = []

func _ready():
	for i in range(ARRAY_SIZE):
		array1.append(i)
		array2.append(i)
	print("Array1 size is " + str(array1.size()))
	print("Array2 size is " + str(array2.size()))
	
`
**Output:** 
Array1 size is 11
Array2 size is 10

**Minimal reproduction project:**  
[ArraySizeProblem.zip](https://github.com/godotengine/godot/files/4497056/ArraySizeProblem.zip)

**Comment by arkology** [comment]
var array1 = [ARRAY_SIZE] creates array with ARRAY_SIZE element. var array2 = [] creates empty array. That's why for array1 it prints 11, and 10 for array2. That's wrong?

**Comment by KoBeWi** [comment]
You can't declare array size in GDScript. Print the contents of the arrays instead of their size and it should clear the problem for you.
