### ISSUE TITLE
Can't edit text file resource after renaming

### ISSUE THREAD

**Issue by Deftwun** [godotengine/godot#37999]
**Godot version:**
3.2.1

**OS/device including version:**
Win 10

**Issue description:**
Renaming .tres textfile resource causes file to become uneditable inside godot editor

**Steps to reproduce:**
- create a new project
- right-click & add new textfile resource to "res://" folder
- save / edit / close / re-open file as expected
- rename file to anything else
- you can no longer view or edit the file inside godot editor

**Comment by Paulb23** [comment]
Related #21787
