### ISSUE TITLE
Linux X11 fails to compile

### ISSUE THREAD

**Issue by PucklaMotzer09** [godotengine/godot#38005]
**Godot version:** v4.0.dev.custom_build.495b28765

**OS/device including version:** Ubuntu 18.04.4

**Issue description:** When trying to build for X11 the process fails with the following errors:
scene/3d/voxelizer.cpp: In member function 'void Voxelizer::plot_mesh(const Transform&,  Ref<Mesh>&, const Vector<Ref<Material> >&, const Ref<Material>&)':
scene/3d/voxelizer.cpp:597:18: error: 'nr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   const Vector3 *nr;
                  ^~
scene/3d/voxelizer.cpp:595:18: error: 'uvr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   const Vector2 *uvr;

I fixed it with changing the lines to:
const Vector3 *nr = nullptr;
and
const Vector2 *uvr = nullptr;

**Comment by Ev1lbl0w** [comment]
Huum, I tried compiling and got no problems. And looking at the code, it seems it is safe, since `nr/uvr` won't be used if they're not initialized.

What is the compiler you're using *(GCC or Clang)*, and what version?

**Comment by PucklaMotzer09** [comment]
I am using gcc 7.5.0. I am thinking the same. It should be fine, but for some reason I got this error.

**Comment by ni-code** [comment]
Compiling master fails fore me as  well on solus linux using gcc 9.3.0, with the same error. But I can compile the engine using llvm.
