### ISSUE TITLE
2D Polygon indices are barely visible on bright background

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#38009]
**Godot version:**
3.2.1

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/79686557-87242700-8241-11ea-82a5-aeb046d94213.png)
Could be fixed with something like this #36530 probably

**Comment by akien-mga** [comment]
Still reproducible in the current `master` branch.

**Comment by Cretezy** [comment]
I've got an updated fix (in the style of https://github.com/godotengine/godot/pull/36530):

https://github.com/godotengine/godot/pull/70902
