### ISSUE TITLE
Recording Audio on linux and Android

### ISSUE THREAD

**Issue by gudenis** [godotengine/godot#38003]
**Godot version:**
v3.2.1 Stable

**OS/device including version:**
Ubuntu 19.10
Android 10 with Samsung S10E

**Issue description:**
I'm trying to make audio recordings using busses and AudioStreamPlayer.
But I think my busses is always disable (because the bus have blue color)

**Steps to reproduce:**
I tried to do the tutorial: https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record

I enable Audio input in Project>Setting>Audio

**Minimal reproduction project:**
my code : 

```gdscript
func _ready():
var idx = AudioServer.get_bus_index("Record")
effect = AudioServer.get_bus_effect(idx, 0)

func onListen_pressed():
find_node("ListenAudio").play()

func onRecord_pressed():
if effect.is_recording_active():
    endRecording()
    print("end recording")

else:
    effect.set_recording_active(true)
    print("recording")
    find_node("Timer").start()

func onListenRecord_pressed():
find_node("ListenRecordAudio").play()
func onTimer_timeout():

endRecording()
find_node("Timer").stop()
print("end recording timer")

func endRecording():
find_node("ListenRecord").modulate.a = 1
effect.set_recording_active(false)
recording = effect.get_recording()
print(recording)
print(recording.format)
print(recording.mix_rate)
print(recording.stereo)
var data = recording.get_data()
for i in range(0, data.size()):
    print(data[i])
print(data)
print(data.size())
find_node("ListenRecordAudio").stream = recording
```

Thanks

**Comment by Calinou** [comment]
Audio recording is known not to work on Linux, see #33184.

**Comment by Saxito** [comment]
And on android ?
Is there an alternative to recording with using something else ?

**Comment by Calinou** [comment]
> And on android ?

Did you enable the required permissions in the Export dialog?

> Is there an alternative to recording with using something else ?

Not that I know of, I'm afraid :slightly_frowning_face:

**Comment by Saxito** [comment]
Yes, in Project>Export>Option>Permission 
I enable RecordAudio

**Comment by Calinou** [comment]
@gudenis Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
