### ISSUE TITLE
Can not rotate ``Control`` nodes with Rotate tool

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3800]
**Operating system or device:**
Windows 10, Ubuntu 14.04

**Issue description** (what happened, and what was expected):
Can rotate ``Node2D`` nodes with rotate tool, but can not rotate ``Control`` nodes.

**Steps to reproduce:**
1. add Sprite and Button
2. select ``Rotate tool``
3. try to rotate Sprite and Button
4. can not rotate Button

**Comment by StraToN** [comment]
I am not sure GUI elements are supposed to be rotated. Can they?

**Comment by volzhs** [comment]
Yes. It's supported from 890b462ffbe6b3ece94b90170d95d719bc4a9075

**Comment by StraToN** [comment]
Can you add a Sprite and a Button to a root Control node and rotate the root Control node ? Just for verifying.

**Comment by volzhs** [comment]
* Control (root)
    * Button
    * Sprite

I can rotate all nodes include root with inspector.

**Comment by StraToN** [comment]
Ok, so it is a bug concerning the rotate helpers of the element in the grid. I can't label the issue, let's wait for @godotengine/bugsquad
