### ISSUE TITLE
Vulkan: Add a Decal property to change the texture sampling mode (also for OmniLight and SpotLight projectors)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#38007]
As of https://github.com/godotengine/godot/commit/495b28765d03aa9459bc312ebba190ec208979e7, there doesn't appear to be a way to change the sampling mode for Decal nodes. This means they will always use linear filtering, regardless of the texture they're applied onto. This makes it impossible to disable filtering (for pixel art decals) or enable anisotropic filtering (for better appearance when viewed at oblique angles).

**Comment by sketchyfun** [comment]
Appears to be true for the spotlight projector texture as well

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2247.
