### ISSUE TITLE
Still some metadata in tscn format

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3801]
Follow up of #3060.

@akien-mga:

> There seems to still be one piece of metadata saved: https://github.com/KOBUGE-Games/project-kumquat/blob/fccc7a622e65cbc7a5592a07fbb0c33b5ca8e85c/levels/level.tscn#L11
``__meta__ = { "__editor_plugin_screen__":"2D" }``
This one is IMO the most important to get rid of version control-wise, as it changes basically all the time, it just depends whether you pressed Ctrl+S while looking at the script of the 2D screen.

> IMO it might be useful to keep the distinction 2D vs 3D using a meta argument (i.e. whether the scene should open by default the 2D plugin screen or the 3D one?), but maybe we could simply ignore the Script screen?
Then when saving the scene on the 2D screen, it would define ``"__editor_plugin_screen__":"2D"``, on the 3D screen it would define ``"__editor_plugin_screen__":"3D"`` (just like it does now), but on the Script screen it would keep the previous definition (2D or 3D). WDYT?

@eska014:

> Agree, this ``__meta__ = { "__editor_plugin_screen__":"2D" }`` is annoying

Maybe just use the scene root node type to determine initial view?
I don't really care for this in the first place, I'd rather do an extra click than make version control more complicated

**Comment by akien-mga** [comment]
+1 for @eska014's proposal, that was also my thoughts recently. Just dropping the metadata and relying on the root node to select the initial tab would be just perfect.

Another option is to put this metadata in the user path instead of the scene files.

**Comment by adolson** [comment]
I see no reason to remember which tab a scene was on last, so +1 to choosing 2D or 3D based on the root node.
