### ISSUE TITLE
Children of TextEdit nodes disappear when outside their parent node's area

### ISSUE THREAD

**Issue by Teradile** [godotengine/godot#38016]
Godot version: 3.2.1

OS: Manjaro i3 Edition 20.0

Issue description: Any part of a child of a TextEdit that is outside its area isn't visible. It's still not visible when I run the project.
![texteditbug](https://user-images.githubusercontent.com/56076296/79695992-deda8680-8271-11ea-95f9-2187cce16711.gif)

Steps to reproduce: Create a 2D scene. Create a TextEdit node, and put another node inside it. Move it away from the TextEdit node.

I don't know if this is expected behaviour or not, but I can't find any information about it, so I'm guessing not.

**Comment by dreamsComeTrue** [comment]
TextEdit is using
```cpp
RenderingServer::get_singleton()->canvas_item_set_clip(get_canvas_item(), true);
```
which means it will cut out all of its children. 

Why do you want to attach visual Node as a child of TextEdit ?

**Comment by Teradile** [comment]
I'm trying to make a right click context menu to replace the built-in one. Should I close the issue and find another way to do it?

**Comment by dreamsComeTrue** [comment]
Maybe you could try to put both of them - TextEdit and Popup under one common parent instead?

**Comment by Teradile** [comment]
That works. I'm closing this issue.
