### ISSUE TITLE
FPS randomly dropping when not in fullscreen

### ISSUE THREAD

**Issue by emperorofmars** [godotengine/godot#38010]
**Godot version:** 3.2.1

**OS/device including version:**
OS: KDE neon (Ubuntu 18.04) and Windows 10
Gpu: Nvidia Rtx 2070 Super (Propriteary Driver 440.82)
Cpu: Amd r7 3700x
Ram. 32GB
Monitor: 60fps

**Issue description:**
Linux:
When i run my project in windowed mode, it renders sometimes only 30 fps, sometimes 60 fps.
It happens randomly, without changing anything in the project. It usually changes every few seconds to every few minutes within a run.
All the while the output of the engine says the game is running at 60fps. Printing the delta is always 16.6 ms.
This is not affected by the vsync settings. Even with vsync off, the stutter happens randomly.
Even if it runs at 1800 fps according to the output, it will still sometimes show only 30 fps on screen.
Setting "sync via compositor" makes no difference on Linux either.

It doesn't happen only in my project, but also in all the demo projects i tried.
It doesnt seem to be tied to physics, as the same behaviour happens when changing the transform of a non-physics object manually. (in the example project drag player_regular into the scene and delete the other player_... node)

The exact same issue happens in the editor itself as well.

On Windows this happens also, but its more of a stutter, happening maybe for a few frames on and off. Setting "sync via compositor" seems to fix this, but i tried it only 2 times, maybe i just got lucky.

When i run a project in fullscreen, it runs smooth at 60fps(on screen) with every vsync setting on Linux and Windows.

**Steps to reproduce:**
Run any project and have "luck" seeing the low framerate. You might have to wait many minutes for it to appear or disappear.

I have attached my project, and a video showing the issue, including a 10x slowed down part. Look at the mouse cursor moving vs the game.

[godot_fps_issue.zip](https://github.com/godotengine/godot/files/4499133/godot_fps_issue.zip)
[godot_fps_issue_video.zip](https://github.com/godotengine/godot/files/4499136/godot_fps_issue_video.zip)

**Comment by MightyPrinny** [comment]
are you sure that's a thing that only happens in godot?, I've been using MXLinux for 2 years without a composition and I only get vsync and smooth frame rate on games in full screen

**Comment by MightyPrinny** [comment]
I''ve also noticed that forcing the fps(Engine.target_fps or in project settings) to refresh rate +1 makes things smoother on windows with vsync

**Comment by Calinou** [comment]
On Windows, this can't be fully fixed without adding some kind of fixed step interpolation. See [Fixing jitter and stutter](https://docs.godotengine.org/en/latest/tutorials/misc/jitter_stutter.html) in the documentation for more information.

You can use [this smoothing add-on](https://github.com/lawnjelly/smoothing-addon) to add physics interpolation to your project.

**Comment by emperorofmars** [comment]
@MightyPrinny I've ran Tomb Raider 2013 for 10 minutes in windowed mode and it was smooth all the time, on the other hand, Blender seems to show the same behaviour, as well as the Unity engine now that i've tried it.

@Calinou I dont think that this has anything to to do with physics, i update in the _process method anyway for kinematicBody and my non physics based player implementation. no differences between those.

Interestingly, when i turned vsync in Godot off, in windowed mode, i saw no tearing. So i turned vsync in nvidia-settings off and in kwin. Now i had tearing, and the stutter didnt appear in the 10 minutes where i let it run. When i turned vsync in Godot on, i hat still tearing and stutter in windowed and now also in fullscreen.

To summarize (at least for Linux):
vsync godot: off, vsync kwin&nvidia: off, fullscreen: yes = smooth & tearing
vsync godot: off, vsync kwin&nvidia: off, fullscreen: no = smooth & tearing
vsync godot: on, vsync kwin&nvidia: off, fullscreen: no = stutter & tearing
vsync godot: on, vsync kwin&nvidia: off, fullscreen: yes = stutter & tearing
vsync godot: on, vsync kwin&nvidia: on, fullscreen: yes = smooth & no tearing
vsync godot: off, vsync kwin&nvidia: on, fullscreen: yes = smooth & no tearing
vsync godot: off, vsync kwin&nvidia: on, fullscreen: no = long periods of low fps and smoothness & no tearing
vsync godot: on, vsync kwin&nvidia: on, fullscreen: yes = smooth & tearing is visible for the first few seconds (and only one tear-line) without vsync its multiple ones that persist
vsync godot: on, vsync kwin&nvidia: on, fullscreen: no = long periods of low fps and smoothness & no tearing

I am not sure if this is still a Godot issue, might be a compositor or driver one. Can i be that one of those things "eats" rendered frames? Godot output still shows 60fps when i see only about 30 on screen.

**Comment by Ev1lbl0w** [comment]
What happens if you run your project like this?

```
vblank_mode=0 %command%
```

**Comment by Calinou** [comment]
@Ev1lbl0w `vblank_mode` environment variable is only effective for open source drivers, not the NVIDIA proprietary driver.

**Comment by Ev1lbl0w** [comment]
> @Ev1lbl0w Last time I checked, the `vblank_mode` environment variable is only effective with open source drivers, not the NVIDIA proprietary driver.

Ah, I had no idea :stuck_out_tongue:
Then, for some reason in my setup I have to specify that to get >60FPS anywhere, but now that I think of it, it might be some Optimus/Hybrid graphics  shenanigans.

**Comment by emperorofmars** [comment]
After more testing, i really dont think the error is godot specific. Closing
