### ISSUE TITLE
TextEdit: color doesn't change to font_color_selected when selecting text

### ISSUE THREAD

**Issue by xarrynator** [godotengine/godot#38017]
**Godot version:** 3.2.1

**OS/device including version:** Windows 10, GLES3

**Issue description:**  I'm still experiencing bug #27760 even on version 3.2.1 (3.2 seemed to be affected as well), even though the fix indicated on the PR closing this bug seems to be included in the source code. (I did NOT compile the engine myself, just looked at the source code of the release.)

**Steps to reproduce:**
Change the font_color_selected (under "Custom Colors") of a TextEdit and try selecting text when running the scene. It still displays the normal font color. It's working fine for LineEdit.
OR
Change the above-mentioned property of a theme and then try to select the text in the "demo TextEdit" of the Theme editor. Same result as above.

Please let me know if this was worth opening a new issue or if there would have been some way for me to reopen the issue #27760, I'm not this familiar as this is my first-ever submitted issue on GitHub. Thanks!

**Comment by dreamsComeTrue** [comment]
That's not enough, you need to tick that one switch :)

![obraz](https://user-images.githubusercontent.com/1110337/79699758-bb273880-8291-11ea-98f6-f178b73a6a6c.png)
