### ISSUE TITLE
Output prints " Signal 'node_removed' is already connected " when the editor settings window is closed

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#38012]
**Godot version:**
3.2.2 beta 1 mono

**OS/device including version:**
MXLinux 19 64 bits

**Issue description:**
I get this printed every time I close the editor settings window: " Signal 'node_removed' is already connected to given method '_node_removed' in that object."

**Steps to reproduce:**
Open editor settings and close the window.

**Comment by dankan1890** [comment]
Related #37412 @KoBeWi

**Comment by KoBeWi** [comment]
Well, this can be fixed by a simple check whether the signal is already connected, but this shouldn't have happened in the first place. Seems like TileMap editor is added to the tree (reinitialized?) each time the settings dialog is closed, not sure why though.
