### ISSUE TITLE
Editor's subwindows are always squeezed and not placed in the Editor's center

### ISSUE THREAD

**Issue by dreamsComeTrue** [godotengine/godot#38023]
**Godot version:**
current master, d817be92c2d9edce842ab37ab13117743f8a3bee

**OS/device including version:**

Win10, Vulkan backend

**Issue description:**

All of the sub-windows (Open/Save dialogs) are very tight, like those were forced to be at minimum size.
Also - those are not properly placed, their top-left point is at the editor's center, instead of their middle point.

![issue](https://user-images.githubusercontent.com/1110337/79700024-4d7c0c00-8293-11ea-8b9c-88d5f065c051.gif)

**Comment by Calinou** [comment]
The "squeezing" part was already reported in #37401.

**Comment by dreamsComeTrue** [comment]
Thanks, will close that one to not pollute Issues then :) I was just afraid, that nobody suffered from that behavior and it's just me.
