### ISSUE TITLE
Invalid packet received. Unabled to find requested cached node

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot#38029]
**Godot version:**
3.2.1-stable
**OS/device including version:**
Windows<->Mac
**Issue description:**
Communication between Mac and Windows with High Level Multiplayer doesn't work on 3.2.1-stable git branch.
On Windows log printed : Invalid packet received. Unabled to find requested cached node.
**Steps to reproduce:**
Try to host a windows server and to connect with a mac client and reverse too.(Works on 3.1.2-stable git branch)
**Minimal reproduction project:**
Any network game with High Level Multiplayer abstraction.

**Comment by groud** [comment]
Sorry, but without a minimal reproduction project this is not going to be solved.

**Comment by DisDoh** [comment]
So my bad... wasn't using 3.2.1 on both computer...
