### ISSUE TITLE
Tiling not working for AtlasTexture image for both canvas TextureRect and Sprite

### ISSUE THREAD

**Issue by vickylance** [godotengine/godot#38021]
**Godot version:**
v3.2.1

**OS/device including version:**
Windows 10 Pro

**Issue description:**
Tiling not working for AtlasTexture image for both canvas TextureRect and Sprite

**Steps to reproduce:**
Add an AtlasTexture to the project and try to tile using any one of TextureRect or Sprite. It won't tile.

**Minimal reproduction project:**
[bug-report.zip](https://github.com/godotengine/godot/files/4500089/bug-report.zip)

**Comment by guilhermefelipecgs** [comment]
Unfortunately atlas texture don't support tile yet.

**Comment by vickylance** [comment]
@guilhermefelipecgs  ok for now I guess I have to use normal png image

**Comment by Calinou** [comment]
Closing in favor of #5660 and #20472.
