### ISSUE TITLE
"Open in File Manager" no longer works on linux

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#38028]
**Godot version:**
3.2.2 beta 1 mono

**OS/device including version:**
MXLinux 19 64bits

**Issue description:**
In 3.2.1 I could right click a folder in the file explorer and open the folder in my file manager but this no longer works.

**Steps to reproduce:**
Right click on folder in file manager and click on "Open in File Manager"

**Comment by allkhor** [comment]
Can't reproduce on linux Xubuntu 16.04.6 LTS, Godot 3.2.2.beta.custom_build 2a10e30.

**Comment by nonunknown** [comment]
Can't reproduce on linux Ubuntu 19.10 , Godot 3.2.2 beta 1 official build

**Comment by Ev1lbl0w** [comment]
What happens when you type this in the terminal?

```bash
xdg-open ~
```

**Comment by akien-mga** [comment]
Can't reproduce either on Mageia 8 with Godot 3.2.2 beta 1 Mono.

**Comment by MightyPrinny** [comment]
Xdg-open ~ opens my file manager

**Comment by MightyPrinny** [comment]
Well it works now, it wasn't working yesterday for some reason.
