### ISSUE TITLE
SpringArm does not work

### ISSUE THREAD

**Issue by bunianox** [godotengine/godot#38037]
**Godot version:** Godot v3.2.2 beta 1

**OS/device including version:** Manjaro Linux x86_64

**Issue description:** SpringArm does not move its children to the collision point with the latest beta. Works fine with v3.2.1

SpringArm does not move the camera when it collide with the ground
![beta 1](https://user-images.githubusercontent.com/53292215/79737614-27577a00-832e-11ea-921b-6aa93e9c4dd8.gif)

v.3.2.1
![stable](https://user-images.githubusercontent.com/53292215/79737727-52da6480-832e-11ea-94b4-2b888545cbb5.gif)

**Steps to reproduce:** run the minimal reproduction project

**Minimal reproduction project:** 
[bug.zip](https://github.com/godotengine/godot/files/4502527/bug.zip)

**Comment by akien-mga** [comment]
Indeed, it was a regression from #37911, which was fixed by #37964.
