### ISSUE TITLE
Unable to run any Godot project on mac os Catalina 10.15.4 

### ISSUE THREAD

**Issue by dariuspranskus** [godotengine/godot#38038]
**Godot version:**
3.2.1, 3.2.2b1, 4.0

**OS/device including version:**
Mac OS Catalina 10.15.4.

**Issue description:**
When I try to run any of Godot project I get the following error
ERROR: Condition "_sock.is_null() || !_sock->is_open()" is true. returned: ERR_UNAVAILABLE
   at: poll (core/io/stream_peer_tcp.cpp:292)
ERROR: Condition "_sock.is_null() || !_sock->is_open()" is true. returned: ERR_UNAVAILABLE
   at: poll (core/io/stream_peer_tcp.cpp:292)

**Steps to reproduce:**
Download and install any Godot demo project and try to run.
Run won't start but immediately gives the following output in the console.

--- Debugging process started ---
--- Debugging process stopped ---

I tried various versions 3.2.1, 3.2.2.b1 and then tried to compile and run 4.0 version and it gave me the above error

**Comment by akien-mga** [comment]
Did macOS ask you to give permission to Godot to use Internet/TCP connections, and if so, did you refuse it? Godot's debugger uses TCP to communicate with the running game.

**Comment by dariuspranskus** [comment]
@akien-mga No it did not ask me

**Comment by akien-mga** [comment]
CC @bruvzg @Faless

**Comment by dariuspranskus** [comment]
I know the problem. it was the eset antivirus.
