### ISSUE TITLE
No selection handles on Android TextEdit/LineEdit

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#38049]
**Godot version:**
3.2.1
**OS/device including version:**
Android
**Issue description:**
I am 30% into a huge project that heavily relies on the TextEdit and LineEdit controls being used between the desktop and Android devices.  There are many problems that have already been reported recently concerning the TextEdit and LineEdit controls (no auto popup of virtual keyboard, jumbled text being inserted when moving caret, no tap and hold context menu). This morning I came across a problem no reported yet to my knowledge. 
Mobile devices have tried to make text entry and editing as easy as possible.  When you select text, 2 handles always appear allowing the user to do precision selecting.  This does not occur in Godot.
**Steps to reproduce:**
Create a TextEdit or LineEdit.  Run the app in Android.
Type a sentence then try to select a word.  No handles appear as you expect on a mobile device.

Here are 3 pictures.  The first one shows the handle that appears when you simply touch the editbox on the android device. 

![select-caret](https://user-images.githubusercontent.com/26915986/79775200-25bb9100-82f1-11ea-9f5a-fcc7cdcfc313.png)

This one shows the handles for selecting:

![select2](https://user-images.githubusercontent.com/26915986/79775289-408e0580-82f1-11ea-8449-aaf2e8b2751a.png)

Here is me trying to select the word "sentence" in android godot.  Almost impossible without these handles.

![select3](https://user-images.githubusercontent.com/26915986/79775381-64514b80-82f1-11ea-91fc-de6b86872fb6.png)

**Comment by Calinou** [comment]
Related to #31411.

**Comment by ondesic** [comment]
It would be great if Godot exposed the native textbox control for our use.  Then all the function would just be present.

**Comment by Calinou** [comment]
@ondesic I don't think that's really feasible as the GUI system in Godot doesn't rely on any "native" controls. Moreover, the theming would likely clash with most projects' visual styles.

**Comment by Calinou** [comment]
@ondesic I'd recommend joining `#godotengine-devel` on freenode IRC ([webchat](http://webchat.freenode.net/?channels=#godotengine)) to ask engine developers directly. If you use the webchat, make sure to enter `/join #godotengine-devel` to join the engine developer channel.

**Comment by ondesic** [comment]
@Calinou, I spent the day on there yesterday.  I posted my question twice but no one answered.  I finally figured out on my own how to accomplish the 50 pixels higher.
Is there a way to get the default line_spacing of a font in godot?  I can get the line Height, but unless the user actually specifies the line spacing, my solution won't work.

**Comment by ondesic** [comment]
Ok.  I have been working on this since April.  I am almost done.  I have created my own scene for a TextEdit and LineEdit that can be used on a mobile device.  On press and hold a word is selected and handles appear.  The handles can be moved to change the selection.  This has been a lot of work but has helped me tremendously when using these 2 nodes on a mobile device!
Here is a sample:
![linescroll](https://user-images.githubusercontent.com/26915986/97390154-c3e07300-18a1-11eb-9a41-1c3294e13909.png)

One problem that I have run into is the fact that currently the LineEdit does not expose the horizontal scroll value like the TextEdit does.  Therefore if I use the arrow to scroll to the end, the calculations for the position of the handles are incorrect:
![line2](https://user-images.githubusercontent.com/26915986/97390477-90eaaf00-18a2-11eb-934e-c6df0db0bd5a.png)

How can I find how much scrolling has occurred with a LineEdit?

**Comment by ondesic** [comment]
In the docs under "caret_position" it says "The cursor's position inside the LineEdit. When set, the text may scroll to accommodate it."
There needs to be a way to return the scroll value spoken about.

**Comment by ondesic** [comment]
@Calinou, is there any insight you have to this, or someone who would know?

**Comment by Calinou** [comment]
cc @pouleyKetchoupp 

I don't know much about the specifics of porting to Android/iOS.

**Comment by ondesic** [comment]
Thanks, actually the question isn't about porting.  I need to know the value of the scroll of the lineedit which is not exposed.

**Comment by pouleyKetchoupp** [comment]
Yeah at this point the problem doesn't seem Android related anymore.

Looking at `LineEdit` it should be possible to expose the horizontal scroll, but it would require some extra conversion. Right now, we have `window_pos` which could be easily exposed, but it's set as a number of characters. So in order to be useful, we would need to calculate the offset in pixels from this value, a little bit like the `LineEdit` drawing process does.

@ondesic Also, what about using `TextEdit` instead of `LineEdit` in all cases, since it has more information exposed for your needs?

**Comment by ondesic** [comment]
@pouleyKetchoupp I thought about just using the `textedit`. The problem is the `LineEdit` has features that I would have to program into the TextEdit.  Alignment, Max length, Secret character are a few of the benefits of the `LineEdit` that are not present in the TextEdit.
Somehow under the hood there is code for the `LineEdit` that calculates the amount of scrolling. If you (1) use the arrow keys and  scroll to the right, and then (2) you click on a word, the Caret is placed in the right position.
If I can just get help finding the offset, all would be well.

**Comment by pouleyKetchoupp** [comment]
@ondesic It's possible to easily expose the offset as a number of characters, but would that be enough for your system to work? I imagine you would need the offset in pixels, and that requires more work as the code doing this calculation is not that straightforward, unfortunately.

I would suggest to open a proposal ticket for this need so we can go through the proper workflow:
https://github.com/godotengine/godot-proposals/issues

Once it's approved, one of the contributors can take care of the implementation (depending on their availability) or you can contribute yourself if you feel like doing some c++ changes.

In the meantime, if this is a blocker for your project, the best compromise would be to use TextEdit and see if you can work around the missing features by script.

**Comment by ondesic** [comment]
@pouleyKetchoupp I would love to know the offset in characters.  How do I do this?

**Comment by pouleyKetchoupp** [comment]
@ondesic I've just opened #43449 to access the offset from scripts. If you want to test it, you can compile godot from the 3.2 branch and include this change.

**Comment by ondesic** [comment]
Excellent!  I was able to use that offset to calculate the correct position.  Thank you!

**Comment by pouleyKetchoupp** [comment]
Nice to hear it's working for you! I'm closing this ticket since all problems related to implementing custom handles seem to be addressed now.

**Comment by codingfever-anishmishra** [comment]
@ondesic I was also trying to create selection handle but I couldn't get it right. It would be great if you could share your code with me.
