### ISSUE TITLE
Android export crashes

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#38046]
**Godot version:**
Godot 3.2.2.beta1

**OS/device including version:**
MacOSX 10.14.6 (18G95)
Android 8.1

**Issue description:**
Update godot to 3.2.2.beta1, download and install export templates, run game, crash:
![Screenshot_2020-04-20-18-30-45-899_com miui bugreport](https://user-images.githubusercontent.com/1177068/79770295-e499a000-8335-11ea-8f1f-2e31fd4377d6.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@DrMoriarty Are you using any third-party modules in your build (C++ or Android modules)?

**Comment by DrMoriarty** [comment]
@Calinou thanks for the idea! I clean upped android build folder and it worked now.
