### ISSUE TITLE
Android Module Compilation

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#3805]
I am building a module for android in the newest version of godot , I am using linux , ndk10

when I run scons p=android I get this error 

```
AttributeError: 'SConsEnvironment' object has no attribute 'android_module_file':

```
as the instruction [here](http://docs.godotengine.org/en/latest/reference/creating_android_modules.html?highlight=android) I add my files using 
```
def can_build(plat):
    return plat=="android" or plat=="iphone"

def configure(env):
    if env['platform'] == 'android':
        # will copy this to the java folder
        env.android_module_file("MySingleton.java")
```

I build it before the gradle version of android, I think there is a new way to build module for android but there is no doc or I don't find any.

**Comment by freemanfromgodotengine** [comment]
I have read on irc or old forum that unfortunately is gone, that modules have to be remake slightly to work with grade.
If author of the module did not do that, the module will not compile. I had this problem with AdMob module just after reduz dropped ant and implemented gradle. So I think it might be more of a module issue than godot itself.

**Comment by mohaalak** [comment]
I write the module myself it just share texts and pics , I don't know the workaround , I want to create some modules for android.

**Comment by volzhs** [comment]
that is old config.
you should write config.py like this.
```python
def can_build(plat):
	return plat=="android"

def configure(env):
	if (env['platform'] == 'android'):
		env.android_add_dependency("compile 'com.google.android.gms:play-services-ads:8.4.0'")
		env.android_add_java_dir("android/src")
		env.android_add_to_manifest("android/AndroidManifestChunk.xml")
```

**Comment by mohaalak** [comment]
thank you we should add it to doc.

**Comment by akien-mga** [comment]
Reopening until it's added to the docs then: https://github.com/godotengine/godot-docs/blob/master/reference/creating_android_modules.rst

**Comment by mohaalak** [comment]
I am writing right now :smile:

**Comment by mohaalak** [comment]
@akien-mga [pull request for documentation](https://github.com/godotengine/godot-docs/pull/14)

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/14
