### ISSUE TITLE
Unable to export to Android on mac os catalina using latest stable version

### ISSUE THREAD

**Issue by vickylance** [godotengine/godot#38057]
**Godot version:**
Godot 3.2.1

**OS/device including version:**
Mac OS catalina

**Issue description:**
adb devices shows the device
the phone is connected using debugging mode and as well as file transfer mode
but when I try to run on my phone using the android run button in godot I am getting this error.

![image](https://user-images.githubusercontent.com/5861833/79792095-f8f88f80-836b-11ea-9a69-29bc7e461ced.png)

**Steps to reproduce:**
Clone the below project and try to export to android
https://github.com/vickylance/godot-asteroids

**Minimal reproduction project:**
https://github.com/vickylance/godot-asteroids

**Comment by Calinou** [comment]
Are you using OpenJDK 8 (not a newer version)? Are the paths to `adb` and `jarsigner` configured in the Editor Settings?

**Comment by akien-mga** [comment]
Do you accept the prompt to install the app on your phone?
I also have Mi OS and it gives me 10 s to accept the install prompted by adb, otherwise it will abort (and give this error in Godot).

**Comment by vickylance** [comment]
@Calinou  I am using the latest OpenJDK 14, I have also tried switching to the default Java in my mac book which is Oracle JDK 13, nothing worked I don't think its the jarsigner problem.
And yes the paths to adb and jarsigner and debug.keystore are correct.
I have already installed a few other projects from this mac book to my phone it was working. This particular project was a project I worked on my windows machine and then I cloned it in my macbook and tried to install in my android.

@akien-mga  Yes I have accepted to install everytime it asks for the prompt I also clicked that checkmark to not to ask everytime.

**Comment by vickylance** [comment]
One thing to note is when I clone and open this project for the first time godot gets stuck in the reimporting loader. After 15 mins or so I have to force quit godot and reopen it but this time it opens without reimporting and everything seems to be in place.

**Comment by m4gr3d** [comment]
@vickylance Your version of `jarsigner` may have been the issue as before only OpenJDK 8 was supported.
This was fixed in https://github.com/godotengine/godot/pull/44646, so give a try to the latest `3.2.4` beta release and see if that fixes the issue.
