### ISSUE TITLE
Android templates got bigger (+25% size) since plugin system re-architecture

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#38068]
**Godot version:**
3.2.2-beta1 / `3.2` 2a10e301195abf1ad4894cf54aab71a9b6e1a734
(Likely also `master` 40b2aea222807ab50a31c7ca718bfca76080caa0, but it's easier to compare on 3.2.)

**OS/device including version:**
Android

**Issue description:**
Most likely following the merge of #36336 and possibly other related Android refactoring PRs (CC @m4gr3d), the overall size of the Android export templates has grown significantly between 3.2.1-stable (before those changes) and 3.2.2-beta1 (current state):

```
$ ls -lh 3.2.1.stable/android_*
-rw-r--r-- 1 akien akien 46M Mar 10 14:27 3.2.1.stable/android_debug.apk
-rw-r--r-- 1 akien akien 37M Mar 10 14:27 3.2.1.stable/android_release.apk
-rw-r--r-- 1 akien akien 77M Mar 10 14:27 3.2.1.stable/android_source.zip
$ ls -lh 3.2.2.beta1/android_*
-rw-r--r-- 1 akien akien 57M Apr 21 09:08 3.2.2.beta1/android_debug.apk
-rw-r--r-- 1 akien akien 47M Apr 21 09:08 3.2.2.beta1/android_release.apk
-rw-r--r-- 1 akien akien 95M Apr 21 09:08 3.2.2.beta1/android_source.zip
```

Upon inspecting the contents of `android_release.apk`, I found:
```
$ du -s release-3.2.1/*
4,0K    release-3.2.1/AndroidManifest.xml
912K    release-3.2.1/classes.dex
103M    release-3.2.1/lib
4,0K    release-3.2.1/list
56K     release-3.2.1/META-INF
320K    release-3.2.1/res
44K     release-3.2.1/resources.arsc
$ du -s release-3.2.2-beta1/*              
8,0K    release-3.2.2-beta1/AndroidManifest.xml
2,9M    release-3.2.2-beta1/classes.dex
1,3M    release-3.2.2-beta1/kotlin
142M    release-3.2.2-beta1/lib
20K     release-3.2.2-beta1/list
128K    release-3.2.2-beta1/META-INF
348K    release-3.2.2-beta1/res
48K     release-3.2.2-beta1/resources.arsc

$ du -s release-3.2.1/lib/arm64-v8a/*
900K    release-3.2.1/lib/arm64-v8a/libc++_shared.so
23M     release-3.2.1/lib/arm64-v8a/libgodot_android.so
$ du -s release-3.2.2-beta1/lib/arm64-v8a/* 
6,0M    release-3.2.2-beta1/lib/arm64-v8a/libc++_shared.so
29M     release-3.2.2-beta1/lib/arm64-v8a/libgodot_android.so
```

So `classes.dex` became 2M bigger, and the new kotlin support adds ~1M, but compressed those two shouldn't make a huge difference.
On the other hand on the libs side, both `libgodot_android.so` and `libc++_shared.so` got 5-6M extra each, for all four architectures (`lib` went from 103M to 142M uncompressed).

Similarly, the `android_source.zip` size difference stems mainly from a difference in the size of the release and debug AAR archives:
```
$ du -s source-3.2.1/libs/debug/*
41M     source-3.2.1/libs/debug/godot-lib.debug.aar
$ du -s source-3.2.2-beta1/libs/debug/*
50M     source-3.2.2-beta1/libs/debug/godot-lib.debug.aar
```

I did upgrade the Android NDK to r21 for 3.2.2-beta1, which could have an impact, but AFAIR my earlier testing builds at https://downloads.tuxfamily.org/godotengine/testing/3.2.2-gles2_batching_build1/ had the same size difference and used the same NDK version as 3.2.1-stable.

I can do a rebuild of the 3.2.1-stable Android templates with the 3.2.2-beta1 build container if needed, to compare further.

**Comment by allkhor** [comment]
Maybe i found what's happen here.
I compile custom build based on 3.2.2 in docker container, with one android_arch=armv7 and disabled some modules.
And compile with same setup, but reverted cd2b2bf [PR](https://github.com/godotengine/godot/pull/36906)
Result:
```
du -sh custom_3.2.2/*
8,0K	custom_3.2.2/AndroidManifest.xml
9,4M	custom_3.2.2/android_release.apk
2,9M	custom_3.2.2/classes.dex
1,3M	custom_3.2.2/kotlin
28M	custom_3.2.2/lib
128K	custom_3.2.2/META-INF
348K	custom_3.2.2/res
48K	custom_3.2.2/resources.arsc
```
```
du -sh custom_3.2.2_revert/*
8,0K	custom_3.2.2_revert/AndroidManifest.xml
7,4M	custom_3.2.2_revert/android_release.apk
2,9M	custom_3.2.2_revert/classes.dex
1,3M	custom_3.2.2_revert/kotlin
18M	custom_3.2.2_revert/lib
128K	custom_3.2.2_revert/META-INF
348K	custom_3.2.2_revert/res
48K	custom_3.2.2_revert/resources.arsc
```
Maybe Kotlin must be optional, if i don't use any Kotlin code, how to disabled it, only way is edit gradle?
