### ISSUE TITLE
Resizing instanced CollisionShape2D resizes all instances (and original)

### ISSUE THREAD

**Issue by LotsaBugs** [godotengine/godot#38066]
**Godot version:**
3.2.2 beta 1
**OS/device including version:**
Windows 10.18362
**Issue description:**
I have a scene like this:
```
Button
-- Area2D
-- -- CollisionShape2D
```
It has this script:
```
tool
extends Button

func _on_resized():
	var CS2D: CollisionShape2D = self.find_node("CollisionShape2D")
	var half_size := self.rect_size/2
	CS2D.position = half_size
	CS2D.shape.extents = half_size


func _ready():
	self.connect("resized", self, "_on_resized")
```
When resizing an instanced button in the editor, all the other instances have their CollisionShapes resized, even the original scene.
Clicking `Make Sub-Resources Unique` doesn't do anything.

![Area2D Bug](https://user-images.githubusercontent.com/52873190/79822579-1b33e280-8357-11ea-859a-bcc782692f48.gif)

**Steps to reproduce:**
Open the Minimal reproduction project or create your own scene as described and give it the script provided above.
Resize any instanced button to see the bug.

**Minimal reproduction project:**
[Area2D Bug -1.zip](https://github.com/godotengine/godot/files/4507544/Area2D.Bug.-1.zip)

**Comment by Calinou** [comment]
As far as I know, you need to edit the CollisionShape resource and check **Local to Scene** in the Inspector to avoid this.

**Comment by LotsaBugs** [comment]
Ah, that fixes it, thanks!
However, that property is really hidden.
Do you think **Local to Scene** should be enabled by default?

**Comment by Calinou** [comment]
@LotsaBugs No, as this would duplicate every resource even if they're not being modified individually. This would result in worse performance.

**Comment by LotsaBugs** [comment]
I see. Thanks for your help! Closing.

**Comment by city41** [comment]
I had the same issue. I need to programatically resize a CollisionShape2D's sub shape resource. I had the same problem of all my scenes sharing the same RectangleShape2D. Choosing "Local To Scene" solved my problem.

However, when choosing the shape for a CollisionShape2D, there is the option of "Make Unique"

![image](https://user-images.githubusercontent.com/141159/92968617-76bb5580-f449-11ea-854f-ff2718bc9d41.png)

Choosing "Make Unique" does not seem to do anything. My scene's .tscn file does not change and the resource is still shared across scene instances. Is this "Make Unique" option supposed to do the same thing as "Local To Scene", or something else?

I am using Godot v3.2.2.stable.official on Ubuntu
