### ISSUE TITLE
Help tabs get shuffled

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#38079]
**Godot version:**
79f82bd

**Issue description:**
Not sure what exactly happens here, but looks like jumping to different links in editor help might break tab references.
![OHXAclGQSF](https://user-images.githubusercontent.com/2223172/79872021-8926eb00-83e5-11ea-9f12-6126046b9de0.gif)
(this is with #38074 applied)

**Comment by akien-mga** [comment]
Fixed by #38235.
