### ISSUE TITLE
Creating a .AAR file doesn't really create a .AAR file (using #31919)

### ISSUE THREAD

**Issue by Altair1234** [godotengine/godot#38077]
Godot Version 3.2

Windows 10

I'm trying to get a .AAR file as described by the method in #31919. Some steps which I think are needed before it can be used:

The directory on my device was: <disk>\<my project>\android\build. Then I had to write a local.properties and a settings.gradle file. Also, my command was .\gradlew :libs:build

Now I can't seem to find the .AAR file generated by this. My terminal (using Cmder) does show "BUILD SUCCESSFULL in 2s/ 1 actionable task: 1 executed".

I'm unsure if I messed up writing the two files or in some other part of the process. In case it is a bug, I hope it is fixed soon and the relevant steps are added to the documentation because it's a neat feature.

**Comment by m4gr3d** [comment]
@Altair1234 I'm not sure what you're referring to as the PR you link is for Gradle custom build process and not for creating a AAR file.

**Comment by Altair1234** [comment]
I'm new to this but according to #26469, in which the person was asking about creating an AAR file, you replied that this does fix the issue. Either way, I do not get a file as a result of the build.

**Comment by m4gr3d** [comment]
While it's possible to generate a `godot-lib.aar` file, this is usually reserved for developers with experience with the engine, and is not recommended for regular users of the engine.

If you have a specific need, the best approach is to ask members of the community (irc, discord, etc...) about the available options to resolve that need.
