### ISSUE TITLE
Signals of StaticBody2D not working

### ISSUE THREAD

**Issue by SamToorchi** [godotengine/godot#38085]
**Godot version:** 3.2

**Issue description:** the signals of StaticBody2D specially from category "CollisionObject2D" never  works. I have always make a Area2D with the same Collisionshape and use the signals of Area2D. 

**Steps to reproduce:** 
* Node2D
    * StaticBody2D (e.g. Signals like: Input_event, mouse_entered, mouse_exited)
        * CollisionPolygon2D

and just add a print to the signal. 
Result: nothing happends.

If I replace StaticBody2D with an Area2D everything works fine again!

**Comment by KoBeWi** [comment]
Did you turn `pickable` on? Area2D has it enabled by default, while StaticBody2D doesn't.

**Comment by SamToorchi** [comment]
oh, that was the problem. Thank you :)
