### ISSUE TITLE
Animation Playback Track not seeking properly in the Animation Editor

### ISSUE THREAD

**Issue by EspeuteClement** [godotengine/godot#38093]
**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
Window 10 64bit
18362.778

**Issue description:**

When seeking through an Animation that has a Animation Playback Track, the Animation Playback Track is not updated accordingly if the selected animation is not a looped animation. "Play the Animation from current pos" also doesn't play the Animation Playback Track correctly if the play bar is in the middle of the animation track.

Here is a capture of the expected result that is obtained when playing the animation from the start
![000024](https://user-images.githubusercontent.com/11552304/79893765-d1a1d100-8404-11ea-84d4-c19b8eada457.gif)

Here is a capture of the seeking in the editor that does not play the expected animation
![000026](https://user-images.githubusercontent.com/11552304/79893868-ee3e0900-8404-11ea-8075-a9d696b53e97.gif)

**Steps to reproduce:**
1. Create an object with an attached animation player (A)
2. Create a simple one shot animation
3. Create another animation player B
4. Inside of the animation player B, create an Animation Playback Track, targeting the animation player A
5. Add a key inside the Animation Playback Track, with the animation created in step 2 as the Animation parameter.
6. Scroll through the timeline using the mouse, and notice that the animation from the animation player A is not updating accordingly. 

Or using the included reproduction project : 

1. Open the Main.tscn scene
1. Open the GlobalAnimationPlayer node
1. Select the GlobalAnimationWithOneShot animation
1. Scroll through the timeline using the mouse, and notice that the animation clip is not playing the correct animation (the Sprite should move up and down)

**Minimal reproduction project:**
[AnimPlaybackBug.zip](https://github.com/godotengine/godot/files/4511516/AnimPlaybackBug.zip)

**Additional notes:**

I have a fix available here https://github.com/EspeuteClement/godot/commit/d6f24f87395bffc83175162dc52b35e756756c1c , but I didn't know if I could make a pull request for a bug that doesn't have an open issue.

**Comment by avencherus** [comment]
Confirmed in 3.2 beta.

This is a good description of the problem.  I don't think there would be an issue submitting a PR.

**Comment by avencherus** [comment]
@EspeuteClement Tested your fix, it doesn't fully fix it.  For me it works if you allow the playing animation to hit the start point of that keyframed animation track, but if you try scrubbing through the timeline, seeking to a position after the sub-animation's starting point it will not update the positions.

This also fails in runtime using the script below.  The seeking functionality would need fixing as well.

```
func _ready() -> void:
	$GlobalAnimationPlayer.play("GlobalAnimationWithOneShot")
	$GlobalAnimationPlayer.seek(1.0, true)
```



I would imagine the intended complete functionality is that where-ever you seek to in the animation, it will update the position of that "one-shot" animation as well.

**Comment by EspeuteClement** [comment]
So you mean if you scrubb at a point after the end of the animation track, the animation should update to reflect the last frame of the animation track ?

I'll try to see if I can fix that, using the code of the looping animation as an example, as this behavior is correct when scrubbing through animations that loops (it correctly update even if you scrub past the end of the animation)

**Comment by avencherus** [comment]
Anywhere one scrubs to that time should be sent to the sub-animation's seek.  I'm assuming it's doing a little math and using relative time.

Hopefully that helps.  I could be failing to explain this.

If in doubt though, there is ground truth in your GlobalAnimationWithLoop animation in the GlobalAnimationPlayer.  It shows the correct results when scrubbing.  You can compare against that.

**Comment by EspeuteClement** [comment]
So I tried to reproduce that on my end using my fix on the 3.2 branch, and I don't think I see the issue you are describing, unless I'm mistaken. Using your code show the expected result on my side. 

Here is a gif of me scrubbing through the one shot and non looping animation, that have a clear start (green dot) and end (red dot).
![000034](https://user-images.githubusercontent.com/11552304/79973461-e24f5700-8497-11ea-8c1a-a003d8fc8c86.gif)

And here is an updated reproduction project :
[AnimPlaybackBug2.zip](https://github.com/godotengine/godot/files/4515612/AnimPlaybackBug2.zip)

One could argue that the animation don't seek at the beginning of the animation when scrubbing before that, but I don't think it's the intended behavior anyways, as it's the same for the looping animation.

**Comment by avencherus** [comment]
I think I may be the one who is mistaken here.  Apologies if that is the case.

Upon retesting it is behaving as expected.

Not clear what I did previously to encounter it.  The initial play triggered the sub animation, but the seeking did not...  Likely a mistake in testing on my part.

**Comment by EspeuteClement** [comment]
Okay, in that case I'll open the pull request.
