### ISSUE TITLE
"Always show close Button In Scene Tab" option is not working correctly

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3810]
I have tested this on Ubuntu, 2.0 stable
Unfortunately option "Always show close Button In Scene Tab" is not working correctly. 
If we open many scenes and will try to close them while they are not active, the first click will not work, the second one will close two scenes.  You don't need any particular setup to reproduce this.
@StraToN could you take a look?

**Comment by StraToN** [comment]
@kubecz3k Ok, I'll try this tonight. I guess this is not related to the Setting option, but to the way the Tabs::CLOSE_BUTTON_SHOW_ALWAYS is managed. I remember @reduz  rewrote this part of the source code a few weeks ago, maybe he broke it.

**Comment by StraToN** [comment]
My apologies to #reduz. He was absolutely not in cause. I was, I commented a line out which was not needed before, which forced updating tabs after closing. Force update is new needed.

**Comment by kubecz3k** [comment]
@StraToN Working nicely now! Thanks :)
