### ISSUE TITLE
[3.2.2 beta1.mono] Crash after move scripts in other folder

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#38129]
**Godot version:**
3.2.2 beta1 mono
**OS/device including version:**
Debian 10
**Issue description:**
I tried to create and delete c# script files and it work as intended (update  .csproj correctly)
I tried to move scripts from a folder in a sub-folder: it move the scripts and update the .csproj correctly but godot crash.
edit: i tried to replicate it but it don't happen again. Ill update this issue if I can replicate it again
edit2: It crash when I start to build then it compile correctly after restart. **Happen each time I do some modifications in scripts**
**Steps to reproduce:**
see before
**Minimal reproduction project:**
NA

**Comment by neikeq** [comment]
I cannot reproduce. Can you provide an example project where this is reproducible? Also the crash backtrace and the mono log would be helpful.

**Comment by git2013vb** [comment]
I tried with a new project but so far I didn't reproduce it. But I ca give you the mono log from my original project. the crash backtrace can you explain me where I can find it? And its name?

**Comment by neikeq** [comment]
In the zip you uploaded, in the `log.txt` file: the path to the mono log file is in the line that starts with `Mono: Logfile is:`.

**Comment by git2013vb** [comment]
[2020_04_23 16.50.07 (6060).txt.zip](https://github.com/godotengine/godot/files/4524060/2020_04_23.16.50.07.6060.txt.zip)
 :) Have fun

**Comment by neikeq** [comment]
Everything looks normal in the mono log. I can't do much without an example project.

**Comment by git2013vb** [comment]
I know its a weird situation also because happen only when you move the file and immediately after that try to compile. It will not happen again after that. However, It is possible I didn't gave you the right log file. Now I 'm back to stable version..

**Comment by git2013vb** [comment]
I close. If happen gain I'll open a new one.
