### ISSUE TITLE
Starting Godot returns a windows with a black screen

### ISSUE THREAD

**Issue by Ridote** [godotengine/godot#38138]
**Godot version:**
Godot 3.2.1

**OS/device including version:**
Windows 10 Home 64 bits

**Issue description:**
When opening Godot, before I can select or create a project or anything, I see a black screen instead. If I download the x32 version it works perfectly.

My graphics card is a 1080ti and my drivers are up to date, just in case since some people keeping telling me it´s about my graphics card. Last time I used Godot was in 3.2 rc3 and it worked with the x64 version just fine.

![Untitled](https://user-images.githubusercontent.com/5918735/80095213-79331680-855f-11ea-816a-7b8bc05a48e0.png)

**Comment by Calinou** [comment]
While this shouldn't be an issue with the editor, did you happen to force MSAA in the NVIDIA Control Panel? See #18320.

**Comment by Ridote** [comment]
Oh my god this is quite embarrasing. I cleaned my PC the other day and when connecting things back I connected the display port to the wrong socket, hence it was taking my integrated graphics card.

I actually noticed when trying to open the NVidia Control Panel, so you actually solved it. 

Thanks and sorry!!
