### ISSUE TITLE
GLES2 Batching lights not respecting z index

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#38133]
**Godot version:**
3.2.2 beta

**Issue description:**
As a result of joining items across z_indices, it turns out that this breaks the ability to limit lights to only affecting items between a specified z range.

This is rather annoying because it means that with a ranged light it isn't always possible to batch between z_indices:

i.e. if you have an isometric game with
```
z 0 - grass
z 1 - house
z 2 - flowers
```
and a ranged light that only affects z_index 1-2, we can no longer batch together the grass, house and flowers, only the house and flowers.

My first thoughts were simply to disable batching between z_indices when there is _any_ light present, however, this would be unnecessarily limiting. So I'm now thinking in terms of if a light is set to the maximum ranges (-4096 to 4096), then there is no need to break batching between z_indices, so this gives a way of lighting such games without breaking batching. This will fix any visual regressions.

(I noted that the default range for lights is -1024 to 1024, is this for historical reasons, as the max range is now -4096 to 4096 I believe?)

I should be able to sort out a basic PR this morning.

As a more advanced feature, that may take a little more time, I may be able to make an even more intelligent system that records the active light ranges, and only batches over z_indices that would not affect the lighting. I'll have a think about how practical this is to do over the basic approach. Something like this would open up a lot more options for isometric game lighting while retaining high performance.

**Comment by akien-mga** [comment]
Fixed by #38137.
