### ISSUE TITLE
UPNP.add_port_mapping() outputs error regarding delete_port_mapping()

### ISSUE THREAD

**Issue by Aeropulu** [godotengine/godot#38149]
**Godot version:**
3.2.1 stable

**OS/device including version:**
Windows 10
The router I use is a Orange Livebox, I'm not sure what parts of the description .xml might be useful and safe to share. Also I don't have admin access to it.

**Issue description:**
Adding a port mapping outputs an error regarding delete_port_mapping. The port mapping seems to get properly added and can be deleted later with no error.
Issue described in this question https://godotengine.org/qa/65365/delete_port_mapping-condition-i-0-is-true
Outputs `E 0:00:03.211   delete_port_mapping: Condition "i != (0)" is true. Returned: UPNP::upnp_result(i)
  <C++ Source>  modules/upnp/upnp_device.cpp:90 @ delete_port_mapping()
  <Stack Trace> UPNPTest.gd:8 @ _ready()
`

**Steps to reproduce:**
Run the following:
`var upnp = UPNP.new()`
`upnp.discover()`
`upnp.add_port_mapping(4200)`
**Minimal reproduction project:**
[upnp bug repro.zip](https://github.com/godotengine/godot/files/4523814/upnp.bug.repro.zip)

**Comment by Jose-Paulo-FaD** [comment]
This is a pretty annoying bug that is also happening in my project.

**Comment by mhilbrunner** [comment]
PR to fix this behaviour: https://github.com/godotengine/godot/pull/63809
Notably, this is only a cosmetic log message that shouldn't effect anything, so you can just ignore the message.
