### ISSUE TITLE
Improve Android plugin v1 setup and dependency resolution process

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot#38157]
**Godot version:**
3.2.2.beta

**Issue description:**
Based on feedback from @DrMoriarty (see #37916), the setup process of the new v1 Android plugins should be simplified and easily allow support for remote and local plugin dependencies.

**Comment by m4gr3d** [comment]
To facilitate the setup process for Android plugins, a configuration file is introduced:

- The config file extension is **.gdap** which stands for **G**o**d**ot **A**ndroid **P**lugin.

- The config format is a follow:

```
[config]

name="MyPlugin"
binary_type="local"
binary="MyPlugin.aar"

[dependencies]

local=["local_dep1.aar", "local_dep2.aar"]
remote=["example.plugin.android:remote-dep1:0.0.1", "example.plugin.android:remote-dep2:0.0.1"]
```

The `config` section and fields are required and defined as follow:

- **name**: name of the plugin
- **binary_type**: can be either `local` or `remote`.  The type affects the **binary** field
- **binary**: 
  - if **binary_type** is `local`, then this should be the filename of the plugin `aar` file in the `res://android/plugins` directory (e.g: `MyPlugin.aar`).
  - if **binary_type** is `remote`, then this should be a declaration for a [remote gradle binary](https://developer.android.com/studio/build/dependencies#dependency-types) (e.g: "org.godot.example:my-plugin:0.0.0").

The `dependencies` section and fields are optional and defined as follow:
- **local**: contains a list of local `.aar` binary files the plugin depends on. The local binary dependencies must also be located in the `res://android/plugins` directory.
- **remote**: contains a list of remote binary gradle dependencies for the plugin.

The config file must also be located in the `res://android/plugins` directory. The `Plugins` field in the Android export window will be updated to now take a list of plugin config files.

**Comment by m4gr3d** [comment]
@DrMoriarty I believe the config file defined above should address the issues you add with the new Android plugin system. Let me know if you have feedback on its format.

**Comment by DrMoriarty** [comment]
@m4gr3d Very good! But can we also add some parameters to add custom maven repositories for dependencies and some option to add gradle plugin like section `global` in old gradle.conf

**Comment by m4gr3d** [comment]
@DrMoriarty Unfortunately these are outside of the scope, as we are limited by the capability of the gradle build system at compile time. 
Anything else (including the old `gradle.conf` mechanism) would be a hack and would make the system more fragile and complex to develop and support in the future.

What functionality do you think the new system would not be able to support?

**Comment by DrMoriarty** [comment]
@m4gr3d Ok, in my godot plugin for appodeal I add maven repository `"url 'https://adcolony.bintray.com/AdColony'"` for additional mediation SDKs.
Without such thirdparty dependencies appodeal sdk became mostly useless.

**Comment by m4gr3d** [comment]
The declaration of custom repository by url should be possible. I thought you were referring to repositories like `mavenCenter()` or `google()` which are actually object in the `build.gradle` file and thus much harder to generate from a config file.

Can you provide an example dependency to the custom `"url 'https://adcolony.bintray.com/AdColony'"` repo so I can validate if that's doable.

**Comment by DrMoriarty** [comment]
For example you can check on:
```
repositories {
    maven {
        url "https://artifactory.appodeal.com/appodeal"
    }
}

dependencies {
    implementation 'com.appodeal.ads:sdk:2.6.3.+'
}
```
Typical mediation settings from https://wiki.appodeal.com/ru/android/integratsiya-android-sdk-2-6-3/mediation-wizard

**Comment by m4gr3d** [comment]
@DrMoriarty I opened #38174 (for the `master` branch) and #38175 (for the `3.2` branch) if you want to give it a try.

**Comment by akien-mga** [comment]
Writing down what we discussed on IRC here:

Instead of having to pick `.gdap` files manually to populate the `custom_template/plugins` array, I suggest instead to have the editor parse all `.gdap` files in `res://android/plugins/` automatically to extract the metadata, and then show a list of installed plugins with a checkbox to toggle them, directly in the Android export presets.

This way installing a plugin will only require to put the `.aar` and matching `.gdap` file in `res://android/plugins/` (which could be done by the plugin provider on the asset library).

I think we can assume that if a user installs a plugin, they want it enabled by default, so I'd suggest doing that in the export presets.

Note that this imply that changes to the filesystem might require re-parsing the `.gdap` files automatically. Not sure if it's best to do on any change, or only when accessing the export dialog.

**Comment by NeoSpark314** [comment]
so with using the inverse scale the controller size is again correct; but setting the scale breaks the current setup of having the right controller mesh scale set to [-1, -1, -1] to get a mirrored controller:

![image](https://user-images.githubusercontent.com/1610621/82345300-66442280-99f5-11ea-9152-4a9e0877d298.png)
