### ISSUE TITLE
Improve readability of the layers flyout panel

### ISSUE THREAD

**Issue by zendorf** [godotengine/godot#3815]
The layers flyout panel appearance should mirror the docked layer panel. Currently it is almost impossible to detect the difference between what is selected and de-selected. The only difference being a slight change in the gradient used.

If this was changed to a solid black color, it would massively improve its usability and readability. Here is a mockup to illustrate my point:

![layer_gui_proposal](https://cloud.githubusercontent.com/assets/7741669/13275320/c71fc7f0-db07-11e5-80c4-9a313b1029ea.png)

**Comment by bojidar-bg** [comment]
:+1:

**Comment by UgisBrekis** [comment]
Thanks for the input! I'm working on a new theme proposal and I will definitely take this into account.

**Comment by zendorf** [comment]
@UgisBrekis , Sounds good. A solid white color would probably be more readable against the overall grey. Regardless of the actual color used, as long as the layers and flyout use the same style, it would be an improvement.

**Comment by akien-mga** [comment]
It has already been made much more readable in the current master branch for 2.1, so I'll consider this issue fixed:
![spectacle jh6147](https://cloud.githubusercontent.com/assets/4701338/16128917/e0d2bcc6-3402-11e6-92b2-5bce4e8b8338.png)
