### ISSUE TITLE
tileset editor takes up too much space

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#38159]
**Godot version:**
3.2.1
**OS/device including version:**
Window 10 Pro Education 64 bit

**Issue description:**
tileset editor is taking up way too much space and I am unable to drag to move the window border.
![image](https://user-images.githubusercontent.com/2453707/80148870-89042800-856a-11ea-8d24-dd1ca7182320.png)

things to note
- text has way too much margin
- side panels are not closable
- border between tile sprites and the tile view can't be dragged because it has too big of a limit

fixes I would suggest making
- make inspector, node, scene, input and filesystem panels drag and dropable and closeable
- remove margin between text
- remove limit between tile sprite panel and tile view panel

**Steps to reproduce:**
- create tilemap
- add isometric tileset
- edit tileset
- try to see what your doing

**Minimal reproduction project:**
it has nothing to do with the project

**Comment by Shadowblitz16** [comment]
I can't look up a reference on how to lay my tiles out because of this massive oversight

**Comment by Calinou** [comment]
> make inspector, node, scene, input and filesystem panels drag and dropable and closeable

This is already the case in the `master` branch.

**Comment by groud** [comment]
Closing as this is not needed anymore on master, where you can reduce the TileSet editor's size a lot more.
