### ISSUE TITLE
RichTextLabel's append_bbcode stops animated rich text effects

### ISSUE THREAD

**Issue by lijamez** [godotengine/godot#38169]
**Godot version:** 3.2.1.stable.official

**OS/device including version:** Windows 10 version 1909

**Issue description:**
If a RichTextLabel has BBCode tags that animate the text (such as ``[tornado]`` and ``[shake]``) and then append_bbcode function is called, the animations stop.

The documentation for [append_bbcode](https://docs.godotengine.org/en/stable/classes/class_richtextlabel.html?#class-richtextlabel-method-append-bbcode) does not suggest this behavior.

Root cause:
``set_process_internal(false)`` is called at the beginning of ``append_bbcode()`` and if the bbcode doesn't contain any animated effects, process_internal may not be set to true again.
https://github.com/godotengine/godot/blob/5247fdb3f386cdd3de8ab2c27f1d4332905df4eb/scene/gui/rich_text_label.cpp#L2071

**Steps to reproduce:**

Create a RichTextLabel, enable BB Code, enter the following as BB Code Text in the inspector:
```
[color=red]Some red text.[/color] [tornado radius=5 freq=2]Tornado Effect[/tornado] [shake rate=5 level=10]Shake Effect[/shake]
```

The text will be animated properly.

Then, append any string that does *not* contain an animated BBCode tag to the label by calling ``RichTextLabel.append_bbcode("")``

Current behavior: Animations are paused.
Expected behavior: Animations continue playing.

**Minimal reproduction project:** 
[RTLEffectsDemo.zip](https://github.com/godotengine/godot/files/4526781/RTLEffectsDemo.zip)

**Comment by Eoin-ONeill-Yokai** [comment]
I'll get on this --- I wish I could assign myself. :)
