### ISSUE TITLE
Godot (v2 stable) command line window title has "alpha" in it

### ISSUE THREAD

**Issue by goldenratio** [godotengine/godot#3818]
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
Godot (v2 stable) command line window has title text "alpha" it.
![image](https://cloud.githubusercontent.com/assets/3019293/13280106/c31cbfdc-dae4-11e5-93e0-dce2edce3fc7.png)

**Steps to reproduce:**
1. Open Godot v2 stable
2. Click the Godot icon in taskbar
3. Command line window title has wrong text

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Thanks, this would be the same bug as #3686.
