### ISSUE TITLE
TextEdit true Line Count and position with Autowrap.

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#38180]
**Godot version:**
3.2.1
**OS/device including version:**
Windows 10
Three related problems:
1) When text is wrapped in a TextEdit, there are now more lines.  The current `get_line_count()` does not take this into account.
2) `get_cursor_pos()` gives the wrong X and Y position of the cursor, saying the cursor is off the edge of the TextEdit control.
3) Because of this, if you select a word on a wrapped line, the `GetCursorLine()` and `GetCursorColumn()` returns a different number than you visually see.  The same problem with `SelectionFromLine(), SelectionToLine(), SelectionFromColumn() and SelectionToColumn()`.
All of the above functions need to give the correct position when the text is wrapped.

**Comment by ondesic** [comment]
I fixed the wording of this problem.  Can you please update the label?  This is a bug not an enhancement.

**Comment by Paulb23** [comment]
Fixed by #50371 which exposed a lot of method get get this information.
