### ISSUE TITLE
Improve discoverability for searching projects by full path in the project manager

### ISSUE THREAD

**Issue by voidplayer** [godotengine/godot#38185]
**Godot version:** v3.2.1.stable.official

**OS/device including version:** Debian/testing

**Issue description:** Type something included in the path, it doesnt filter them

**Comment by Calinou** [comment]
This is intended behavior. If the filter doesn't contain a slash, it will only search in the last path component (i.e. the project folder name). If it contains at least one slash, the entire path will be searched for. See #31356 for details.

**Comment by voidplayer** [comment]
Having to add a / to the search to include paths in the search works but is very convoluted and virtually undiscoverable unless somebody tells you about it

I have projects filtered by folders years. It just felt like a bug when typing 20 didnt yield any result... Although /2018 did worked

Also, it happened a few time where i knew the name of the folder but not the name of the project and it felt really weird that it couldnt find it on the list

Your example is also weird. People were having issues because all your projects were showing... Who was searching for ```Documents``` or ```Godot```?

I admit it wont happen again now that i know the / trick :)

But a checkbox "path" next to the search box would be more discoverable for new users

Such as
- [ ] path

Optimal solution would be fuzzy search, that allows you to type several strings and filters anything that contain any of those strings anywhere

Like this: https://github.com/farzher/fuzzysort

**Comment by Calinou** [comment]
> Having to add a / to the search to include paths in the search works but is very convoluted and virtually undiscoverable unless somebody tells you about it

I'll add a tooltip about it.
