### ISSUE TITLE
[Display Server] Dialogs are placed on the wrong monitor

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#38190]
**Godot version:**
0b8cb945c

**OS/device including version:**
Linux Mint 19.3 - XFWM, Compiz
Manjaro 20.0.1 - KDE

**Issue description:**
New dialogs such as Editor settings show up on the wrong monitor in Multi-monitor setups

Demonstration: https://youtu.be/hURCRhbVFg4

Dropdown dialogs (such as the project button) open in the correct location

**Steps to reproduce:**
Try Project->Quit to Project Manager (Most reproducible I could find)

**Minimal reproduction project:**
Not applicable

**Comment by Anutrix** [comment]
This is probably fixed now or is Linux specific. I couldn't reproduce in latest master https://github.com/godotengine/godot/commit/4c8832701b291b8f7bc64e22d93972f6bc968a24 for any dialog on Windows.

**Comment by nathanfranke** [comment]
Tested on d4599fff6 (Same configuration as my original issue)

Now, all windows are opening on the center of the left monitor (Godot is in my middle monitor)

**Comment by Anutrix** [comment]
@nathanfranke Maybe you should rename the title of this issue to something like "Dialogs are centered showing up on wrong monitor" or close this and make a new issue with that title.

**Comment by nathanfranke** [comment]
Right, thanks. Not sure if I will be able to reproduce this since I just switched distros, but if I can then I will update the issue with new content.

**Comment by Anutrix** [comment]
Related or same as #37320 so it might be fixed by #37506.
@nathanfranke Please test if #37506 fixes this issue too.

**Comment by nathanfranke** [comment]
Duplicate of #37320
