### ISSUE TITLE
Mesh with multiply Surfaces and Blend shapes does not work in Web, and size of tres file of mesh

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#38194]
**Godot version:**
3.2.1 stable

**OS/device including version:**
Chrome 78 Linux (OpenGL webbrowser mode)

**Issue description:**
I use model opened in Godot **from FBX file.**
_maybe it problem only with this model, I did export it to GLTF format(in Blender) result same_
Mesh that has many surfaces and lots of blend-shapes
![12](https://user-images.githubusercontent.com/24825887/80267906-2f0b7b80-86ac-11ea-80f8-28baad97311c.png)

**Only bug I care:**
Size of Godot `*.tres` file after saving that mesh with lots blend-shapes, outside of `*.fbx` file, _rightclick Save_ in Godot editor, **this `*.tres` become 130Mb size(from `*.glb/gltf` tres size is 40Mb), when original model in `*.fbx` file is 3Mb(6Mb gltf).** I can keep model in `*.fbx` file, and make 3d-editing outside Godot, this is not big problem.

**native GLES3 Godot build work without any bugs, and everything work.**

_Everything else I launch just for testing._

**in GLES3:**
only this mesh broken in web-build
![1](https://user-images.githubusercontent.com/24825887/80268109-89f1a280-86ad-11ea-9981-696904c7ef06.png)
![11](https://user-images.githubusercontent.com/24825887/80268117-9118b080-86ad-11ea-884f-a6b4fb5c51db.png)
as error say I edit `drivers/gles3/shaders/blend_shape.glsl` line 106 to
```
#ifdef ENABLE_SKELETON
flat out ivec4 bone_out; //tfb:ENABLE_SKELETON
out vec4 weight_out; //tfb:ENABLE_SKELETON
#endif
```
it launched, but result is broken:
![2](https://user-images.githubusercontent.com/24825887/80268250-4b101c80-86ae-11ea-9926-95894d4aa909.png)

**In GLES2:**
I have no plans to use GLES2 in this project, launch just for testing.

in Native GLES2 build:
**Blend-shapes do not work at all, in GLES2 mode in Editor or after exporting project, model work(visible).** I do not know if Blend shapes supported in GLES2 Godot, maybe it expected.

in GLES2 web export build:
(with and without `flat` shader-code editing result same)
no shader errors, model do not work(empty/transparent) and other errors come:
![13](https://user-images.githubusercontent.com/24825887/80268444-a262bc80-86af-11ea-8521-f580932e016f.png)

I use 3.2.1 custom build, I have open this mesh in 3.2.1 stable export templates result are same.

**Steps to reproduce:**
I can not share testing model, it way too complex and it not my model, I just use it.

**Comment by Calinou** [comment]
We don't support the WebGL 2.0 renderer anymore, sorry.
