### ISSUE TITLE
Only gltf import 3D model can work!

### ISSUE THREAD

**Issue by wijat** [godotengine/godot#38197]
Godot version:3.2.1 stable
OS/device including version: window

**Issue description:**

**Godot import Blender model really gets big pain !!!!**
So many issues!

I try many ways, only gltf can work, fbx or dae can not work!

But gltf not work perfect, when I import animation I made in Blender, it just fill the wrong key frame on animation!!!
And I need to disable the rigfy add-on in Blender!!! To rig Character step by step on hands!

When I reimport the glb file in godot at many times, the 3D model will disappear!

It just let me feel some hopeless, I don't understand, Godot Engine seem not work well on 3D Character!!!

**Steps to reproduce:**
Once you made a easy 3D model in Blender, and try to make animation export to Godot Engine.

**minimal reproduction project:**
[FemaleBaseNew.zip](https://github.com/godotengine/godot/files/4534782/FemaleBaseNew.zip)
Open it on Blender, and export to gltf, you can found the animation is wrong, watch the feet location on Godot. It will auto-fill the wrong key frame I didn't wanted.

**Comment by Calinou** [comment]
@wijat Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by fire** [comment]
If you drop a blender file, I could find time to debug the gltf2 export.

**Comment by wijat** [comment]
> 
> 
> @wijat Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

I uploaded it.

**Comment by fire** [comment]
I cannot export a gltf from blender 2.83 dailies. I think the problem is related to rigify needed to bake animation and remove itself.

**Comment by wijat** [comment]
I use Blender 2.82

**Comment by wijat** [comment]
I work it on with Blender Riggify add-on, It needs to give material and need to select the rig and mesh when export gltf. But the animation still not same as Blender, It still will change a little position on Godot.

Here my situation:

![ezgif-1-f5bd555f58ee](https://user-images.githubusercontent.com/8220843/81382712-657fd680-9141-11ea-87c1-8dbc21868cc2.gif)

**Comment by fire** [comment]
There are two possible bugs that can cause this.

One is for 2.83 and the other is for 2.9.

https://github.com/KhronosGroup/glTF-Blender-IO/issues/700

https://github.com/KhronosGroup/glTF-Blender-IO/pull/880

**Comment by fire** [comment]
I tried using Blender 2.9 and a branch that was based on a recent version of godot engine 3.2.

![editor_screenshot_2020-10-18T084908-0800](https://user-images.githubusercontent.com/32321/96373045-e1ce0b00-111e-11eb-911a-4ff0e8dde1c8.png)

Can you still recreate the bug?

**Comment by fire** [comment]
I can't reproduce the bug on Blender 2.9 and a branch that was based on a recent version of godot engine 3.2.
