### ISSUE TITLE
Incorrect File Autocompletion When Using FileDialog Filters

### ISSUE THREAD

**Issue by homchom** [godotengine/godot#38195]
**Godot version:** 3.2.1.stable.official

**OS/device including version:** Windows 10 Home Version 1903

**Issue description:** When the `filters` property for FileDialog nodes is set, weird autocompletion occurs when the dialog is in use. If you click the dropdown menu near the bottom right corner of the dialog, and select a specific file type (eg. the filter `*.png ; PNG Files`), the file LineEdit is autocompleted incorrectly (in this example, it would be ".*.png ; png files").

If you do this multiple times (for example, switching between file types), the file extension will continue to be appended at the end; for some weird reason, the semicolon and lowercase description only ever appears once at the end and gets overwritten if used multiple times. See below for an image showing the result.

![image](https://user-images.githubusercontent.com/41265646/80269959-55b4bc80-8682-11ea-8234-cf35aef83f42.png)

**Steps to reproduce:**

1. Create a scene with a FileDialog. In my code, I made it popup when a TextureRect is pressed, and the bug showcase project uses a Button, but any way should work.
2. Set the `filters` property. Define at least two file types. I used `*.png ; PNG Files` and `*.jpg ; JPG Files`.
3. Run the program and open the FileDialog.
4. Select one of the two custom filters by selecting the dropdown menu near the bottom right corner. Observe the weird autocompletion.
5. Do this a few more times. Observe the additional autocompletion.

**Minimal reproduction project:** [FileDialog Bug Showcase.zip](https://github.com/godotengine/godot/files/4532269/FileDialog.Bug.Showcase.zip)

**Comment by rasikrodri** [comment]
Is there a workaround for this?

**Comment by jmb462** [comment]
> Is there a workaround for this?

Just use extension in filter. No star, no point, no description.

just : PNG
instead of :  *.PNG ; PNG Picture 

works for me but no format description anymore
