### ISSUE TITLE
Editor gets stuck at splash screen sometimes

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot#38202]
**Godot version:**
`v3.2.1-stable`

**OS/device including version:**
Arch Linux

**Issue description:**
Sometimes when I open my project in the editor, it gets stuck at the splash screen forever. Sometimes restarting the session by logging out and back in fixes it, sometimes it doesn't.

**Steps to reproduce:**
1. Launch Godot
2. Select project
3. Editor gets stuck at the splash screen.

**Comment by Calinou** [comment]
Does it work if you resize the editor window?

**Comment by mhilbrunner** [comment]
Do/can you run Godot from the terminal, is there any output?

**Comment by Tooniis** [comment]
> Do/can you run Godot from the terminal, is there any output?

nope. nothing.

**Comment by Tooniis** [comment]
> Does it work if you resize the editor window while it appears to be frozen?
It happened again now and I tried that, but it only caused weird glitches
![Screenshot from 2020-04-26 19-43-23](https://user-images.githubusercontent.com/36982494/80312451-5c644080-87f6-11ea-844a-9a434d5cf544.png)

**Comment by Ev1lbl0w** [comment]
Can you try running it under `gdb`, and when it freezes stop the program, to see where it is freezing?

**Comment by Tooniis** [comment]
> Can you try running it under `gdb`, and when it freezes stop the program, to see where it is freezing?

It happened again today. Here's the output of `gdb`:

	Starting program: /home/yassine/Code/Source/godot-3.2.1-stable/bin/godot.x11.opt.tools.64 godot.x11.opt.tools.64
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/usr/lib/libthread_db.so.1".
	[New Thread 0x7ffff7fca700 (LWP 47057)]
	Godot Engine v3.2.1.stable.custom_build - https://godotengine.org
	[Detaching after fork from child process 47058]
	[Detaching after fork from child process 47063]
	Found discrete GPU, setting DRI_PRIME=1 to use it.
	Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
	[New Thread 0x7ffff4d4b700 (LWP 47076)]
	[New Thread 0x7fffe90ed700 (LWP 47077)]
	[New Thread 0x7fffe88ec700 (LWP 47078)]
	[New Thread 0x7fffdbfff700 (LWP 47079)]
	[New Thread 0x7fffdb7fe700 (LWP 47080)]
	[New Thread 0x7fffdaffd700 (LWP 47081)]
	[New Thread 0x7fffda7fc700 (LWP 47082)]
	[New Thread 0x7fffd9ffb700 (LWP 47083)]
	[New Thread 0x7fffd97fa700 (LWP 47084)]
	[New Thread 0x7fffd8ff9700 (LWP 47085)]
	[New Thread 0x7fffbbfff700 (LWP 47086)]
	[New Thread 0x7ffff6a88700 (LWP 47087)]
	OpenGL ES 3.0 Renderer: AMD Radeon (TM) R5 M330 (HAINAN, DRM 3.36.0, 5.6.13-arch1-1, LLVM 10.0.0)
	[New Thread 0x7fffe804a700 (LWP 47088)]
	[New Thread 0x7fffd8077700 (LWP 47089)]
	 
	ERROR: load_default_certificates: Condition "default_certs != __null" is true.
	   At: modules/mbedtls/crypto_mbedtls.cpp:201.
	Editing project: /home/yassine/Code/Godot/yeet (::home::yassine::Code::Godot::yeet)
	[Detaching after fork from child process 47092]
	Godot Engine v3.2.1.stable.custom_build - https://godotengine.org
	[Thread 0x7fffe804a700 (LWP 47088) exited]
	OpenGL ES 3.0 Renderer: AMD Radeon (TM) R5 M330 (HAINAN, DRM 3.36.0, 5.6.13-arch1-1, LLVM 10.0.0)
	 
	[Thread 0x7fffd8077700 (LWP 47089) exited]
	[Thread 0x7ffff6a88700 (LWP 47087) exited]
	[Thread 0x7fffbbfff700 (LWP 47086) exited]
	[Thread 0x7fffdaffd700 (LWP 47081) exited]
	[Thread 0x7fffd9ffb700 (LWP 47083) exited]
	[Thread 0x7fffda7fc700 (LWP 47082) exited]
	[Thread 0x7fffd8ff9700 (LWP 47085) exited]
	[Thread 0x7ffff4d4b700 (LWP 47076) exited]
	[Thread 0x7fffd97fa700 (LWP 47084) exited]
	[Thread 0x7fffdbfff700 (LWP 47079) exited]
	[Thread 0x7ffff7fca700 (LWP 47057) exited]
	[Thread 0x7fffdb7fe700 (LWP 47080) exited]
	[Thread 0x7fffe90ed700 (LWP 47077) exited]
	[Thread 0x7fffe88ec700 (LWP 47078) exited]

**Comment by japalekhin** [comment]
finally, something that is the same as my problem. been searching high and low for this.

in my situation, i have a VPS running Ubuntu 20.10. when i try to run the headless server i get this error and crashes(?). all i know is that it doesn't even go through my game code. it just stops right then and there.

```
Godot Engine v3.2.3.stable.official - https://godotengine.org
 
ERROR: load_default_certificates: Condition "default_certs != __null" is true.
   At: modules/mbedtls/crypto_mbedtls.cpp:201.
```

the weird thing is i also have a desktop Ubuntu 20.10 and it runs fine. so i'm thinking this is about certificates (or packages) not being installed. hope this bit of info helps.

**Comment by Calinou** [comment]
> the weird thing is i also have a desktop Ubuntu 20.10 and it runs fine. so i'm thinking this is about certificates (or packages) not being installed. hope this bit of info helps.

Godot embeds the [Mozilla certificate bundle](https://github.com/godotengine/godot/blob/master/thirdparty/certs/ca-certificates.crt) in the binary. It doesn't use the OS' certificate bundle.

**Comment by akien-mga** [comment]
This error is a red herring, it can happen if you pass invalid arguments to the Godot binary. Most likely you're using the headless binary with wrong arguments.

```
$ godot thisisbogus
Godot Engine v3.2.3.stable.mageia - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
 
ERROR: load_default_certificates: Condition "default_certs != __null" is true.
   At: modules/mbedtls/crypto_mbedtls.cpp:201.
```

**Comment by boban-dj** [comment]
Just to conform: I got the same error, and run it with `godot &`
Just running `godot`  with no arguments solved this

**Comment by akien-mga** [comment]
@Toonis You seem to be running Godot with a wrong argument, repeating the executable name:
```
/home/yassine/Code/Source/godot-3.2.1-stable/bin/godot.x11.opt.tools.64 godot.x11.opt.tools.64
```

Can you still reproduce the issue, and if so how do you run Godot exactly?

**Comment by Lecrapouille** [comment]
> This error is a red herring, it can happen if you pass invalid arguments to the Godot binary. Most likely you're using the headless binary with wrong arguments.
> 
> ```
> $ godot thisisbogus
> Godot Engine v3.2.3.stable.mageia - https://godotengine.org
> OpenGL ES 3.0 Renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
>  
> ERROR: load_default_certificates: Condition "default_certs != __null" is true.
>    At: modules/mbedtls/crypto_mbedtls.cpp:201.
> ```

Thank you, I got this issue because I modified Godot to add a third-part which needs to access to argv and argc, but it modified them, so I needed to make backups and restorations.
