### ISSUE TITLE
MD5 checksum for files

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3820]
Is there a way to create a MD5 checksum for a File(in GDScript)?

**Comment by techtonik** [comment]
Why?

**Comment by punto-** [comment]
Yes, the FileAccess object has a get_md5 method. I'm not sure if it's
exported to gdscript tho.

**Comment by Calinou** [comment]
A quick search in the editor help says that MD5 functions exist only for `String` and `ResourceImportMetadata`.

**Comment by AlexHolly** [comment]
I made a quick hack it looks like it is working but it takes ~1min to make a md5 for a 2.7gb file is that normal?

Why is the name p_file and not p_path?
https://github.com/godotengine/godot/blob/7cb930dbede1b9c21cf138e4a38ebb9e3dbd099f/core/os/file_access.cpp#L482
https://github.com/godotengine/godot/blob/7cb930dbede1b9c21cf138e4a38ebb9e3dbd099f/core/os/file_access.cpp#L469


```
String _File::get_md5(const String& p_path) const {
	
	ERR_FAIL_COND_V(!f,String());

	String md5 = f->get_md5(p_path);
	return md5;


}
```

**Comment by akien-mga** [comment]
> I made a quick hack it looks like it is working but it takes ~1min to make a md5 for a 2.7gb file is that normal?

That's normal yes, try ``md5sum`` directly on your file, it should be in the same order of magnitude.

> Why is the name p_file and not p_path?

That's arbitrary I guess :)

**Comment by kubecz3k** [comment]
I will archive this one since there is proper feature request in this issue now: https://github.com/godotengine/godot/pull/3833

**Comment by akien-mga** [comment]
Actually #3833 is a pull request meant to fix this very issue, so I guess it's best to keep it open if e.g. the pull request was rejected but the feature request still valid.

**Comment by kubecz3k** [comment]
Oh my, it's my mistake, very sorry haven't drink morning coffee yet :)
