### ISSUE TITLE
NavigationPolygon: Unable to make polygons from outlines when a vertex is used twice

### ISSUE THREAD

**Issue by T4g1** [godotengine/godot#38204]
**Godot version:** 3.2

**OS/device including version:** Windows 10

**Issue description:**
When using NavigationPolygon, it's impossible to create polygons from outlines when a vertex is used twice

**Steps to reproduce:**
1. Create a script
2. Instantiate a NavigationPolyon
3. Add two outlines sharing one vertex
4. Call make_polygons_from_outlines()

**Minimal reproduction project:**
[gd-bug.zip](https://github.com/godotengine/godot/files/4533381/gd-bug.zip)

**Comment by Calinou** [comment]
cc @AndreaCatania

**Comment by jh62** [comment]
Yes. If you try to manually create a polygon, you can visualize this problem too with the message: _NavigationPolygon: Convex partition failed!_

![kNOnUJyt04](https://user-images.githubusercontent.com/22467336/136646449-ff80378e-fa8b-4c72-9007-77ba16fb4d9b.gif)

It's pretty annoying. I need to disable the navigation in certain areas based on the tiles used and I can't.

**Comment by dweremeichik** [comment]
From my testing, this does not seem to be limited to a vertex being used twice (unless there is a bit of rounding goin on under the hood). In my tests, when outlines overlap, you will also receive this error. It seems likely that `make_polygons_from_outlines()` does not know how to handle (merge) overlapping polygons.

**Comment by ivakam** [comment]
Issue seems to persist as of version 4.0 alpha 11. Very annoying when trying to do custom navpolys based on tilemap colliders :/

**Comment by Calinou** [comment]
cc @smix8

**Comment by smix8** [comment]
2D navigation polygons create Navigationmesh resources from outlines specifically and outlines cannot cross oder overlap, ever.

What ppl are trying to do here with the navigation polygon draw tool wouldn't work even if the tool would allow it. A single navigation polygon does not merge individual polygons so all those navigation cells would be disconnected. Instead, ppl should use navigationregions (for each) cell as those are merged by the NavigationServer.
