### ISSUE TITLE
code editor space small on 4:3 monitors

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#38212]
**Version Godot 3.2.2.beta**

On 4:3 monitors, code editor space is a little small

![godot_editor](https://user-images.githubusercontent.com/3224132/80297187-39e41000-8781-11ea-8ccc-36c6b9c33c63.jpg)

closing `scripts panel` on the left and minimap on right side could help a little,
but **`scripts panel` does not have option to close it by default**,
so there is **never ending fun of closing it manually** for thousand time every time editor opens.

i added a small fix where script panel, when closed will stay closed after reopening project, to aid my self from closing it for 100 times, and i found it very useful so i think i could share.

**Comment by avril-gh** [comment]
PR https://github.com/godotengine/godot/pull/38213

**Comment by pycbouh** [comment]
Related to godotengine/godot-proposals#512.

**Comment by avril-gh** [comment]
updated PR #38351 as suggested by @YeldhamDev and @Calinou

**Comment by dreamsComeTrue** [comment]
CTRL + Shift + F11 ?

**Comment by avril-gh** [comment]
we're talking here about hiding `script panel`.

**Comment by kitbdev** [comment]
The scripts panel state is stored per project.
- fixed in 3.3 https://github.com/godotengine/godot/pull/38351
- fixed in 4.0 #66715
