### ISSUE TITLE
Vulkan BadDrawable - Engine crashes on startup

### ISSUE THREAD

**Issue by TheFlamyy** [godotengine/godot#38225]
**Godot version:** 
master - 7899b3e

**OS/device including version:**
Kubuntu 20.04 LTS
GeForce GTX 950M/PCIe/SSE2 (nvidia-driver-440)

**Issue description:**
The engine crashes on startup. The following output log is printed:
```
Godot Engine v4.0.dev.custom_build.7899b3e73 - https://godotengine.org
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x3600006
  Serial number of failed request:  66
  Current serial number in output stream:  72
```

**Steps to reproduce:**
Start the compiled engine.

_This issue has been extracted from_ https://github.com/godotengine/godot/issues/37102#issuecomment-619533192

**Comment by Calinou** [comment]
If you've updated your NVIDIA graphics driver, you need to restart your PC so you can start 3D applications again.

**Comment by akien-mga** [comment]
Are you running Plasma on Wayland? If so, do you have `xwayland` installed?
Does the Nvidia GPU otherwise support Vulkan application? Check `vulkaninfo` or `vkcube`.

**Comment by TheFlamyy** [comment]
@Calinou I'm quite novice to the topic of drivers (especially graphics drivers), so here's what I did: I changed to NVIDIA only in the nvidia-settings, disabled the nouveau drivers and that was it (I think)

@akien-mga Thanks for the tip with `vkcube`. Last time I used a vulkan application it worked fine, but it was still on my old OS (where I have bodged many things so I don't recall much). After installing `primus-nvidia` the `vkcube` worked again and the master is working fine

TIL for anybody with the same issue: take a look at [this page](https://wiki.archlinux.org/index.php/Vulkan) maybe it can also help you
