### ISSUE TITLE
No main scene has ever been defined

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#3822]
The tutorial is missing this:

![image](https://cloud.githubusercontent.com/assets/515889/13286657/d6ae4320-db13-11e5-9500-eeb2c6767e0c.png)

http://docs.godotengine.org/en/latest/tutorials/step_by_step/scenes_and_nodes.html#editor

**Comment by akien-mga** [comment]
Actually, there is: http://docs.godotengine.org/en/latest/tutorials/step_by_step/scenes_and_nodes.html#configuring-the-project :)

This will all be improved anyway when #1134 gets implemented.

**Comment by techtonik** [comment]
@akien-mga well, yes, but doc says the application should run before the configure step, which doesn't happen. =)

**Comment by akien-mga** [comment]
It should if you click "Run Scene" instead of "Run Project" :)

**Comment by akien-mga** [comment]
Of course the tutorial could always be improved. Feel free to make a pull request on https://raw.githubusercontent.com/godotengine/godot-docs/master/tutorials/step_by_step/scenes_and_nodes.rst

**Comment by techtonik** [comment]
Yea, wrong button.

![image](https://cloud.githubusercontent.com/assets/515889/13287058/04de4720-db16-11e5-8b5d-05525b8fef51.png)

**Comment by DogDod** [comment]
Oh, the wrong button I sucked on also.
