### ISSUE TITLE
Godot crashes when merging from scene

### ISSUE THREAD

**Issue by seeQuayah** [godotengine/godot#38220]
**Godot version:** 3.2.1

**OS/device including version:** Windows 10

**Issue description:** Godot crashes

**Steps to reproduce:** Imaginine having a scene called scene1. Scene1 has a node Node. From scene 2, when I click "merge from scene" the Node from scene1 it works. But if I do the same step on scene3 (after doing it once on scene2) godot crashes

To sum it up, when I merge the same node on multiple scenes it crashes. Well, it doesn't happens necesseraly after second merge. The crash may happen after third or fourth merge.

**Minimal reproduction project:** Sometimes

**Comment by Ev1lbl0w** [comment]
> Minimal reproduction project: Sometimes

You understood that wrong :stuck_out_tongue: 

Can you provide a sample project and then some instructions to easily reproduce this crash? I followed your steps but wasn't able to reproduce that error.

**Comment by seeQuayah** [comment]
> > Minimal reproduction project: Sometimes
> 
> You understood that wrong 😛
> 
> Can you provide a sample project and then some instructions to easily reproduce this crash? I followed your steps but wasn't able to reproduce that error.

Unfortunately I can't reproduce it either now, it was a scene with lot of garbage and I can't remind how exactly it was. Nvm I close the post
