### ISSUE TITLE
Resource: _init with arg makes resource unusable

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#38222]
**Godot version:**
3.2.1 stable

**OS/device including version:**
windows 10

**Issue description:**
In the Resource script:
When i define a func _init() with an argument, I wont be able to access any of the data inside the resource (seems like it can load the resource-script). Neither via debugger nor via script.

But in the scene-view in the inspector (not while debugging) you can see the Resource and edit it properly.

I wanted to use this for some Tool-Script magic, where certain Resources preload some information when added to a Resource export in a scene. This way it  would behave like a template.

This worked when used in a tool script, and properly initialized me those resources, but when running, it has that error.

Expected Behaviour:
Resources still works with _init(_args): or if this is not intended, display error-message in script-editor.

**Steps to reproduce:**
Open the reproduction project and just run the project. The scene will have 2 defined Resources as export.

When running, the script wont be able to access the "resource_bugged" field "text". But when you remove the _init function in the 'Text_Resource_Bugged.gd' script, the scene should run properly.

Without reproduction project:

Add something like 
```
func _init(_args1):
pass
```

to a ressource script.

**Minimal reproduction project:**
[Resource init bug.zip](https://github.com/godotengine/godot/files/4535252/Resource.init.bug.zip)

**Comment by ThakeeNathees** [comment]
the exported resource never called the script with any arguments -> the resource never constructed, a base Resource instance was constructed instead which doesn't has `text` property

IMO the solution, it has to throw some error if the object cannot be instantiated

**Comment by Reneator** [comment]
@ThakeeNathees Agreed! I think this is some kind of problem that can throw off users/beginners, as its currently not telling them what they are doing wrong, so it might produce a lot frustration (without an error-message)

I solved this problem with a workaround, where i initialize the resource i want inside the _init() of the parent object, and just set the variable directly.

So it would be:

_init():
resource.text = "bla"

instead of

_init(text):
resource.text = text

(im using it in this capacity, as i want to initialize certain custom objects with fixed informations on initial creation in the editor, in my example its directly setting a resource via preload(""))

**Comment by ThakeeNathees** [comment]
btw related to #37907

**Comment by Reneator** [comment]
@ThakeeNathees Thanks!

So it seems to be solved by https://github.com/godotengine/godot/pull/37923 in master.
