### ISSUE TITLE
Strech mode settings stopped working on master

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#38234]
**Godot version:**
master (23b7670d32c566acd62870c73676531eb187aa94)

**OS/device including version:**
Linux 5.6.7-arch1-1

**Issue description:**
Expected result (3.2.1):
![Captura de tela de 2020-04-26 13-52-01](https://user-images.githubusercontent.com/1387165/80314090-9e28c300-87c5-11ea-9307-3dcb7d34471a.png)
What I got (master):
![Captura de tela de 2020-04-26 13-53-08](https://user-images.githubusercontent.com/1387165/80314091-9f59f000-87c5-11ea-98b5-75f61b0bb319.png)

**Steps to reproduce:**
![Captura de tela de 2020-04-26 13-53-22](https://user-images.githubusercontent.com/1387165/80314087-9b2dd280-87c5-11ea-8a06-25c150c3c64b.png)
![Captura de tela de 2020-04-26 13-53-30](https://user-images.githubusercontent.com/1387165/80314089-9c5eff80-87c5-11ea-8397-7cf4dbe330d1.png)

**Minimal reproduction project:**
[Strech_Mode_Not_Working.zip](https://github.com/godotengine/godot/files/4535987/Strech_Mode_Not_Working.zip)

**Comment by akien-mga** [comment]
Seems to work fine in current `master` (after taking into account the rename of Test Width and Test Height).
