### ISSUE TITLE
macOS build error: use of undeclared identifier 'NSAppKitVersionNumber10_14'

### ISSUE THREAD

**Issue by daniellimws** [godotengine/godot#38236]
**Godot version:**
master (`23b7670`)

**OS/device including version:**
macOS 10.14.6

**Issue description:**
Got the following error when building Godot on macOS.
```
[Initial build] Linking Static Library ==> modules/libmodule_upnp.osx.tools.64.a
platform/osx/display_server_osx.mm:3249:32: error: use of undeclared identifier 'NSAppKitVersionNumber10_14'
                if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_14) {
                                             ^
```

It seems that `NSAppKitVersionNumber10_14` was defined in https://github.com/godotengine/godot/pull/23822/commits/bbac90c85901f9b15afa12075024d11860cd4330 but now it is no longer in the code base. As seen here when I try to grep for occurrences of this identifier, only the following line was found.

```
godot on  master
➜ rg NSAppKitVersionNumber10_14 .
./platform/osx/display_server_osx.mm
3249:		if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_14) {
```

I believe that there will also be errors with `NSAppKitVersionNumber10_12` due to the same reason.

```
godot on  master
➜ rg NSAppKitVersionNumber .
./platform/osx/os_osx.mm
63:				if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_12) {
72:				if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_12) {
81:				if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_12) {
91:				if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_12) {

./platform/osx/display_server_osx.mm
3249:		if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_14) {
```

**Steps to reproduce:**
Run the build command `scons platform=osx --jobs=$(sysctl -n hw.logicalcpu)`

Or is there something wrong with my setup? I am using the xcode command line tools, and my SDK path is as follows:

```
godot on  master
➜ xcrun --sdk macosx --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
```

**Comment by daniellimws** [comment]
If the suggested fix is to add back the `define` statements as done in https://github.com/godotengine/godot/commit/bbac90c85901f9b15afa12075024d11860cd4330, I can try it locally and make a PR.

**Comment by akien-mga** [comment]
If those are undefined, it means your macOS SDK is too old. Which Xcode version are you using?

CC @bruvzg

**Comment by daniellimws** [comment]
I am using the command line tools `xcode-select version 2354`.

As mentioned by @bruvzg in https://github.com/godotengine/godot/pull/21339, only the 10.15 SDK would have `NSAppKitVersionNumber10_14` defined, while I only have the 10.14 SDK. As I am using macOS 10.14 now, is it possible to get the 10.15 SDK?

**Comment by bruvzg** [comment]
`NSAppKitVersionNumber10_14` is defined only in 10.15 SDKs (Xcode 11.x), Xcode 11.3.1 should work on 10.14.

**Comment by daniellimws** [comment]
Do I need to install xcode (not only the command line tools) to get it?

**Comment by bruvzg** [comment]
Command line tools should include SDK too. Old versions are available at https://developer.apple.com/download/more.

**Comment by akien-mga** [comment]
@bruvzg I guess it shouldn't hurt to re-add the defines for compatibility? Our min OSX version is 10.12 in the master branch so we can likely drop the `NSAppKitVersionNumber10_12` checks.

**Comment by bruvzg** [comment]
> @bruvzg I guess it shouldn't hurt to re-add the defines for compatibility? Our min OSX version is 10.12 in the master branch so we can likely drop the NSAppKitVersionNumber10_12 checks.

Yep, re-add `NSAppKitVersionNumber10_14` to the display server and remove 10_12 checks from the `os_osx.mm`.

**Comment by daniellimws** [comment]
I'm not sure if I'm right about this but wouldn't `NSAppKitVersionNumber >= NSAppKitVersionNumber10_14` always be true if `NSAppKitVersionNumber10_14` is defined, since it will only be defined at SDK versions equal or higher than 10.14?

**Comment by daniellimws** [comment]
@bruvzg Thanks! Now I am able to build without errors
