### ISSUE TITLE
Godot can't load CSV file as TextFile resource

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#38245]
**Godot version:** 3.2.1 (Stable)

**OS/device including version:** Manjaro

**Issue description:** Godot doesn't seems to be able to load non-localization CSV files in the editor. Trying to load it in any `export(Resource) var` or `export(TextFile) var` gives:
 
```
ERROR: _load: Failed loading resource: res://test.csv.
   At: core/io/resource_loader.cpp:278.
```
and clicking it twice gives:

```
ERROR: load_resource: Condition "!res.is_valid()" is true. Returned: ERR_CANT_OPEN
   At: editor/editor_node.cpp:735.
```

Not sure if it is related, but are `.txt` files supposed to be hidden in Editor? Trying to change a .csv file to .txt makes it impossible to be selected as a file in the inspector.

**Steps to reproduce:** Any .CSV file in the project (imported as a normal CSV file, not localization) should be able to reproduce this.

**Minimal reproduction project:** Annexed to the issue.
[csv-problem.tar.gz](https://github.com/godotengine/godot/files/4537028/csv-problem.tar.gz)

**Comment by Xrayez** [comment]
CC @willnationsdev as he worked on some CSV related import stuff.

**Comment by willnationsdev** [comment]
Afaik, the TextFile class only has usability from the editor itself (there's no API exposed for working with it). You can only open a TextFile directly in the ScriptEditor and save it. I don't think it works when you try to export it as a property, but I haven't really tried much.

**Comment by henriquelalves** [comment]
@willnationsdev I see. But CSV files are not being loaded even as normal resources; is this normal?

**Comment by willnationsdev** [comment]
As I understand it, `*.csv` files are imported and translation resources are generated from configuring the .csv's use in the Localization part of the ProjectSettings. So, yeah, the .csv files are not, strictly speaking, the "source" of the Translation resource object instance. They aren't like regular resources.

**Comment by henriquelalves** [comment]
That's weird because there is a 'normal' CSV importing option on the file itself, along with the 'Localization CSV' option. If it can't be imported as a regular resource, what is its purpose? Should I be able to import non-resource, non-object files to the project?

**Comment by willnationsdev** [comment]
@henriquelalves Not sure. Maybe I'm misunderstanding something about it. Would have to check back through the source code.

**Comment by golddotasksquestions** [comment]
The workaround is to rename your **yourfile.csv** file to **yourfile.csv.txt**
This is **really** annoying though, and I really wish Godot would change the automated "import as translation" asap.

**Comment by Calinou** [comment]
I suppose we should change the file extension for translation CSVs to something else. This would require people exporting CSVs to rename their extension manually though.

**Comment by Paulb23** [comment]
See #36297

**Comment by YLL** [comment]
Same here. The CSV import option makes it unable to load the file in any exported game.

Moreover, if I **RENAME** the .csv file which imported as CSV in the filesystem dock to .txt file, the .csv.import file created by the editor will **NOT** be deleted, it's just renamed to .txt.import and the content is untouched leaving something like:
-----
[dep]
source_file="res://xxx.csv"
-----
That makes the .txt file **NOT** packing into any export.
Don't know whether I should post this here or make a new issue.

**Comment by willnationsdev** [comment]
@YLL I feel like the import issue is a slightly different problem that should have its own bug issue. If the same PR can fix both problems at once, then great, but otherwise, you wouldn't want to close this Issue if only one part of the problem was resolved. If you make a bug Issue, make sure to mention this one so that people know they're related.

**Comment by golddotasksquestions** [comment]
Does anyone still have this issue in 3.2.3 stable and 3.2.4? I can load and parse `file.csv` as textfiles now without problems without the `file.csv.txt` renaming workaround.

**Comment by henricazottes** [comment]
I can parse csv files with `file.open("res://path/to/file.csv")` with no problem but I have an error in the editor stating:
``` error
 editor/import/resource_importer_csv_translation.cpp:96 - Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
 editor/editor_file_system.cpp:1801 - Error importing 'res://data/input/booster_profile/F15_TC.csv'.
```

**Comment by Calinou** [comment]
@henricazottes Select the CSV file in the FileSystem dock, go to the Import dock and change the import type from Translation to CSV file.

**Comment by henricazottes** [comment]
Thanks @Calinou , now I  have this error when I double click on it:
```
 Failed loading resource: res://data/input/booster_profile/F15_TC.csv. Make sure resources have been imported by opening the project in the editor at least once.
 editor/editor_node.cpp:854 - Condition "!res.is_valid()" is true. Returned: ERR_CANT_OPEN
```
Is it supposed to display the data / be editable ?

**Comment by Calinou** [comment]
> Is it supposed to display the data / be editable ?

No, Godot doesn't have a built-in CSV editor.

**Comment by henricazottes** [comment]
So the error above is normal?

Here you go (`.txt` for github to accept the file)
[F15_TC.csv.txt](https://github.com/godotengine/godot/files/5629705/F15_TC.csv.txt)

**Comment by Calinou** [comment]
> So the error above is normal?

Yes, I think it's expected since importing it as a pure CSV file will make sure Godot "ignores" it during the exporting process.

**Comment by akien-mga** [comment]
The no-op "CSV" importer is removed by #47301 as it's superseded by #47268 - you can now configure `.csv` files *not to* be imported at all, so you can parse them from script, and they will still be properly exported.

This doesn't allow actually editing the CSV files in the GDScript editor, but this issue seems to have mostly comments related to the workflow of avoiding CSV files from being used as translations, which is now properly fixed. The whole TextFile business is quite limited in its current implementation (see #36297), and the needs for manual editing of CSV in the editor might be better served by https://github.com/godotengine/godot-proposals/issues/13.

**Comment by PyramidHead01** [comment]
Hello, I am having the same problem in godot 4 and I not found another post with this issue.

I can work with the csv files, the only problem is than upset me the 2 error lines for every csv file, even changed to UTF-8 and not worked and if I go to import window I can't interact with they.

The txt works fine and delete the problem, but I want to have a few CSV, and I would like not change the file type every moment.

I am new in godot and there is so many thing than I don't understand, I assume than there is a problem created just by me.

**Comment by ultrasuperpingu** [comment]
I still get this error in 4.3.dev5.mono:
`editor/import/resource_importer_csv_translation.cpp:95 - Condition "line.size() <= 1" is true. Returning: ERR_PARSE_ERROR
Error importing 'res://test/test.csv'.`

And the Import dock show nothing. Is it normal ? Am I missing something ?

**Comment by pozitiffcat** [comment]
Godot 4.2.1. stable
editor/import/resource_importer_csv_translation.cpp:95 - Condition "line.size() <= 1" is true. Returning: ERR_PARSE_ERROR
  Error importing 'res://Text.csv'.
  
 Can't import any csv
for example:

keys;en
fsafsd;fsfsdaf

**Comment by Calinou** [comment]
@pozitiffcat If your CSV uses semicolons as separators, you need to change the separator to `Semicolon (;)` in the Import dock for the CSV file.

**Comment by ultrasuperpingu** [comment]
If your file does not use a comma separator (o have any other problem making the translation importer fail) when you're importing it, the Import dock will not shows up (see #82002). I had this problem, the only way out I found is to make the file a "valid csv", changed its import options, and changed the csv back.

Hope this helps :)

**Comment by pozitiffcat** [comment]
> If your file does not use a comma separator (or have any other problem making the translation importer fail) when you're importing it, the Import dock will not shows up (see #82002). I had this problem, the only way out I found is to make the file a "valid csv" (like a file with content:",\n"), changed its import options, and changed the csv back.
> 
> Hope this helps :)

It helped me. Not able to import CSV first time with semicolon separator. Import settings is empty.
