### ISSUE TITLE
tween_all_complete is never called if one or many of the tweened objects gets destroyed on the way 

### ISSUE THREAD

**Issue by dariuspranskus** [godotengine/godot#38246]
**Godot version:**
3.2

**OS/device including version:**
macos catalina 10.5

**Issue description:**
If I start the tween and the need to destroy the object with queue_free() while it is still tweening, tween_all_complete callback is never called or statement yield(tween, "tween_all_completed") never finishes. Shouldn't queue_free wait until the tweening completes, or tween with the destroyed object be destroyed automatically and excluded from completion?

**Comment by TheDuriel** [comment]
Correct behavior, if unintuitive. Check your output, Tween should be spamming you with errors about the deleted Object. Informing you to stop the tweens first, then delete the Object.
