### ISSUE TITLE
IntelliSense does not respond

### ISSUE THREAD

**Issue by liryu1973** [godotengine/godot#38258]
**Godot version:**
Steam 3.2.1
**OS/device including version:**
Windows10 pro 1803
**Issue description:**
IntelliSense does not respond
**Steps to reproduce:**
![aaa](https://user-images.githubusercontent.com/64412290/80369821-dd403c80-88c9-11ea-93df-9091cc00cf34.png)

onready is not displayed before func _ready().
onready is displayed after func _ready().
No IntelliSense will work in front of func.
I asked a question on the Forum and was told that this is not happening.
I'm Japanese, but a friend of mine who is learning Godot with me has the same symptoms.
Is this a bug?
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Fixed by #40598 (`master`) and #41318 (`3.2`).
