### ISSUE TITLE
CSGShape won't display/add faces

### ISSUE THREAD

**Issue by TheSHEEEP** [godotengine/godot#38259]
**Godot version:**
3.2.1

**OS/device including version:**
Linux, Manjaro KDE

**Issue description:**
It seems that CSGShape is still quite suboptimal, not producing usable results even in simple setups sometimes.

**Steps to reproduce:**
Add the following CSG-setup to your project (the material doesn't matter, same happens without any material):
```
[node name="CSGCombiner" type="CSGCombiner" parent="."]

[node name="CSGBox" type="CSGBox" parent="CSGCombiner"]
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 1.128, 1.5, 1.907 )
width = 1.4
height = 3.0
depth = 0.2
material = ExtResource( 6 )

[node name="CSGBox2" type="CSGBox" parent="CSGCombiner"]
transform = Transform( -1.62921e-07, 0, 1, 0, 1, 0, -1, 0, -1.62921e-07, 40.1, 1.5, 20.903 )
width = 38.193
height = 3.0
depth = 0.2
material = ExtResource( 6 )

[node name="CSGBox3" type="CSGBox" parent="CSGCombiner"]
transform = Transform( -1, 0, -3.25841e-07, 0, 1, 0, 3.25841e-07, 0, -1, 20.214, 1.5, 39.9 )
width = 39.572
height = 3.0
depth = 0.2
material = ExtResource( 6 )

[node name="CSGBox4" type="CSGBox" parent="CSGCombiner"]
transform = Transform( 1.19249e-08, 0, -1, 0, 1, 0, 1, 0, 1.19249e-08, 0.328, 1.5, 20.903 )
width = 38.193
height = 3.0
depth = 0.2
material = ExtResource( 6 )

[node name="CSGBox5" type="CSGBox" parent="CSGCombiner"]
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 38.627, 1.5, 1.907 )
width = 2.746
height = 3.0
depth = 0.2
material = ExtResource( 6 )

[node name="CSGBox6" type="CSGBox" parent="CSGCombiner"]
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 19.541, 1.5, 1.907 )
width = 33.026
height = 3.0
depth = 0.2
material = ExtResource( 6 )
```
Run the project and see that faces in one direction, next to the "doors", will be missing.
It will look like this:
![Oh no, a bug](https://i.imgur.com/EVLuETi.png)

Playing around with the "snap" value didn't result in any improvements.
Moving the three CSGBoxes in the affected wall around a bit (say, 0.02 in x-direction) does make the missing faces reappear. Why it doesn't work 0.02 points more to the left? That's quite probably a bug.

**Minimal reproduction project:**
See above.

**Comment by Calinou** [comment]
This should improve in 3.2.x once #38011 is merged. You can test the `master` branch already, as it was already merged there.

**Comment by TheSHEEEP** [comment]
Oh my.
You were even faster than I edited my post.

I'll give that a go in the next days.

**Comment by TheSHEEEP** [comment]
Tried the 3.2.2 with the merged fixed - works fine now, so this can be closed.
