### ISSUE TITLE
Rigidbody is not rolling using Bullet physics

### ISSUE THREAD

**Issue by ReubenU** [godotengine/godot#38269]
**Godot version:**
3.2.stable.mono

**OS/device including version:**
Windows 10 Home

**Issue description:**
Rigidbody with triangle mesh collision shape does not roll and behaves like it has angular/axis locks on.

**Steps to reproduce:**
Create a rigidbody object and have a triangle mesh collision shape attached (save as scene). Add to main scene and rotate it and let it fall on a flat floor (static body with box collider).

![image](https://user-images.githubusercontent.com/15871822/80408894-f0d1b000-8895-11ea-8c9a-af439eae68c3.png)

**Minimum Reproduction Project**
[MRP_RigidbodyBug.zip](https://github.com/godotengine/godot/files/4542322/MRP_RigidbodyBug.zip)

**Comment by Calinou** [comment]
@ReubenU Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by ReubenU** [comment]
I have uploaded an MRP.

**Comment by pwab** [comment]
Hey @ReubenU I opened your MRP and noticed you are using a `ConcavePolygonShape` as your collision shape for your RigidBody (`crate.tscn`). As far as I know those don't support RigidBodies in another mode than `static`.

Using a `BoxShape `would be a simple solution in case of your sample. Are there any restrictions of your real mesh that you have to use a `ConcavePolygonShape`?

**Comment by madmiraal** [comment]
As @pwab has pointed out, and the editor warns:

![ConcavePolygonShape warning](https://user-images.githubusercontent.com/9253928/84138244-de769480-aa45-11ea-8be9-c6bc6d65619a.png)

`ConcavePolygonShape` is not supported on `Rigidbodys` that are not in `Static` mode.

I've tested and confirmed that a `BoxShape` works as expected.
