### ISSUE TITLE
GLES2 Batching - custom multi-rect modulate bug with lights

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#38260]
**Godot version:**
3.2.2 beta

**Issue description:**
Just while adding some optimizations to the batching for lights, I've noticed a slight oversight - When drawing the light passes, the correct modulate is not being used when there is more than one modulate on a set of rects within an item.

This is because the final modulate used for the non light pass takes into account things like canvas_modulate, but the light passes do not, hence the baked colors need to be different.

This doesn't seem to normally appear in typical use with tilemaps / sprites etc (indeed no one has reported it), but it can exhibit when using custom drawing with multiple rects for an item (node), under a light, particularly when using a canvas modulate.

I should be able to fix this as part of the lighting optimizations, so this is just a note for anyone who sees it in the mean time.

**Comment by akien-mga** [comment]
Fixed by #38320.
