### ISSUE TITLE
The mouse should be confined to the 3D view rotation widget

### ISSUE THREAD

**Issue by programaths** [godotengine/godot#38264]
**Godot version:**

3.2.2-beta1

**OS/device including version:**

Windows10

**Issue description:**

In 3D, there is a new Widget on top right corner. When dragging it, it change the view accordingly, but the mouse is also moving and is also wrapped. The mouse can quickly be lost!

Expectation: mouse stays confined (a hot topic today!) to the widget.

**Steps to reproduce:**

Create a 3D scene, drag the widget.

**Minimal reproduction project:**

Any empty project with a 3D scene will do!

**Comment by Calinou** [comment]
cc @JFonS, who implemented the 3D rotation widget.
