### ISSUE TITLE
Ability to copy text from Search Help to OS Clipboard

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3826]
If you look in Search Help you will notice you are able to select text but if you Meta+C or any other possible copy shortcut nothing gets copied to OS Clipboard. At least this is the case for the latest 2.0 on OSX.

You can copy paste text to OS clipboard from Godot Script Editor just not from Search Help.

**Comment by kubecz3k** [comment]
Hmm on Ubuntu it's working fine,  so it's platform related
