### ISSUE TITLE
**_ready()** method called multiple times?

### ISSUE THREAD

**Issue by RickSanch3z** [godotengine/godot#38296]
**Godot version:**
3.2.1.stable.official
**OS/device including version:**
Windows 10 Professional, 64bit
**Issue description:**
Debugger complain about error related to *pressed* signal being connected to a given method.
![godot__ready_bug](https://user-images.githubusercontent.com/28632149/80494714-4629c200-8967-11ea-955d-d9fe3c265cae.jpg)
**Steps to reproduce:**
Just follow the steps from this lesson:
https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting.html
**Minimal reproduction project:**
Nothing special.

**Note**
I've tested using global variable to count number of times *_ready()* method is called. And it shows me it was called only once. So problem is not related to this method being called multiple times.

**Comment by EricEzaM** [comment]
You already connected it via the GUI interface. You shouldn't connect it both via script and the GUI, pick one or the other.

**Comment by RickSanch3z** [comment]
@EricEzaM yes, indeed. I thought when you use GUI to connect it's a convenient way to add handler. Not that it will create conflicts.
