### ISSUE TITLE
GLES2 2D light pass can draw in wrong position

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#38291]
**Godot version:**
GLES2 but not GLES3
3.1 stable - 3.2.2 beta
(may occur earlier versions too)

**OS/device including version:**
Linux Mint but will probably affect all

**Issue description:**
While working on the batching and fixing regressions in lighting, I noticed one regression that was actually correct in the batching but incorrect in the old renderer.

When using the custom _draw() function to draw rects manually, in some situations the locations of the alpha blended versions in the light pass are incorrect.

The minimum reproduction project shows as seen in this screenshot, without light on the left (5 rects) and with light on the right (appears as 6 rects):

![light_position_bug](https://user-images.githubusercontent.com/21999379/80487011-09080480-8954-11ea-88a7-b595447245b8.png)

**Steps to reproduce:**
Use custom draw with lots of transforms, I haven't pinned down exactly which causes it.

**Minimal reproduction project:**
[Light_Position_Bug.zip](https://github.com/godotengine/godot/files/4545675/Light_Position_Bug.zip)

Note that this appears fixed in my current (soon to be pushed) version of the batching, so there is less pressing need to fix this in the legacy renderer. I suspect it is an extra_matrix bug (where the GPU extra matrix gets out of sync with the logic CPU side).

It doesn't occur in GLES3, presumably because it uses a single pass for lighting.

**Comment by akien-mga** [comment]
Fixed by #38320.
