### ISSUE TITLE
Characters variable in text_edit.cpp is reassigned

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#38305]
**Issue description:**

Variable `characters` is increased by 1 and this value isn't used anymore because a little later 0 is set to it

https://github.com/godotengine/godot/blob/d44c5cfcf72eec2fbf76afe6fd9e43ee3bcab216/scene/gui/text_edit.cpp#L1068-L1077

**Comment by Paulb23** [comment]
It's incremented further up in the loop before a continue here:

https://github.com/godotengine/godot/blob/d44c5cfcf72eec2fbf76afe6fd9e43ee3bcab216/scene/gui/text_edit.cpp#L1037-L1041
