### ISSUE TITLE
Brackets and quotes should wrap around selected word in the script editor

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#3831]
This is an idea to improve the script editor.
If we select a word on the editor and type any of these symbols
' " ( { [ 
the selected text is replaced by these symbols.

It will be good if the behaviour is like those in sublime or atom editor. The word will be wrapped around with the symbol and it's closing symbol.

**Comment by AlexHolly** [comment]
#2982

**Comment by Paulb23** [comment]
This one can be closed, as it works when `auto_brace_completion` is enabled. Similar to that in sublime text.
