### ISSUE TITLE
[4.0] Camera2D's preview box uses editor viewport size instead of project settings size

### ISSUE THREAD

**Issue by verdog** [godotengine/godot#38316]
**Godot version:** 4.0 abf5132a32
**OS/device including version:** Manjaro Linux
**Issue description:**
The preview bounds for Camera2D use the aspect ratio of the editor viewport rather than the actual size of the game defined in settings.

I think this stems from using the size of the viewport that the camera is in, in places such as
https://github.com/godotengine/godot/blob/75e4ccc00e0741db9bdfe3d0f0422afe796a0844/scene/2d/camera_2d.cpp#L100
and
https://github.com/godotengine/godot/blob/75e4ccc00e0741db9bdfe3d0f0422afe796a0844/scene/2d/camera_2d.cpp#L284

I was able to hack a partial quick fix by changing those lines to look up the size in the project settings instead of the viewport, but I don't know if that's the best approach. It also led to some issues with the transform, i.e. the aspect ratio of the preview box was correct but its transform was off. This might be because my hacky fix only fixed the get screen size call in the draw notification response and not in `get_camera_transform` (first example above) 

**Steps to reproduce:**
![bounds](https://user-images.githubusercontent.com/25630273/80549851-4ee0bf00-898c-11ea-963f-ff951774cc78.gif)

**Comment by akien-mga** [comment]
Reopening as #38341 was reverted.
