### ISSUE TITLE
the locale of app  is not the same the locale of the device on iOS.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#38323]
**Godot version:**
3.2.1

**OS/device including version:**

**Issue description:**
on iOS device, the locale of the app is not the same as the device.
On other platforms, the language of the app will changed to the value of the current device automatically.
But on iOS device, the return value of get_locale is not same as the device, so, it's also not possible to set the locale of the app the same as the device manually.
  

**Steps to reproduce:**
 

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@alexzheng Can you show an example of the `get_locale()` value on different platforms?

**Comment by alexzheng** [comment]
on Mac
String OS_OSX::get_locale() const {
	NSString *locale_code = [[NSLocale preferredLanguages] objectAtIndex:0];
	return [locale_code UTF8String];
}

on iPhone

String OSIPhone::get_locale() const {
	return locale_code;
}

**Comment by Calinou** [comment]
@alexzheng I meant the locale code that's actually returned when you run the code on different platforms.

**Comment by alexzheng** [comment]
Maybe this is a misreport, I test it again, and it works as expected.
