### ISSUE TITLE
Can't edit Polygon2D when shader editor is open

### ISSUE THREAD

**Issue by dolorismachina** [godotengine/godot#38329]
**Godot version:**
3.2.1

**OS/device including version:**
Microsoft Windows [Version 10.0.18362.720]

**Issue description:**
While the shader editor is open, the Polygon2D can't be edited. The toolbar doesn't display the edit buttons and the node itself doesn't display the vertices with the red outline that are visible normally.

**Steps to reproduce:**
1. Create new project.
2. Add root node.
3. Add Polygon2D as a child.
4. Add shader material to Polygon2D.
5. Add shader or visual shader to the material.
6. Edit shader.
7. Polygon 2D becomes uneditable.

**Minimal reproduction project:**
[polygon2d-shader-bug.zip](https://github.com/godotengine/godot/files/4552788/polygon2d-shader-bug.zip)

**Comment by KoBeWi** [comment]
The underlying cause is the same as in #28211 and #32002, so closing as duplicate.
