### ISSUE TITLE
Adding Input Key Event Control+D doesn't work

### ISSUE THREAD

**Issue by TheSecurityDev** [godotengine/godot#38334]
**Godot version:** v3.2.1

**OS/device including version:** Windows 7

**Issue description:** When the script editor is open, and I go to add a new key input event in the input map, it won't let me create the key combination Control+D. Instead it duplicates the code in the script editor. You have to switch to the gui editor for it to work. Basically it performs the Control+D shortcut in the script editor, ignoring the input key dialog.

**Steps to reproduce:** Open the script editor. Go to Project > Project Settings > Input Map and add a new event. For that event, click the + button and choose Key. Press the key combination Control+D to add as a shortcut. Instead of working, it duplicates the current line in the script editor.

**Comment by ThakeeNathees** [comment]
seems fixed after display server, and closing the script editor before assigning Ctrl+D would be a work around

**Comment by Calinou** [comment]
Duplicate of #37807.
