### ISSUE TITLE
Error message trying to save a scene with base node as root

### ISSUE THREAD

**Issue by Joakker** [godotengine/godot#38332]
**Godot version:** Godot Engine v3.2.1.stable.official

**OS/device including version:** Windows 10, version 2004

**Issue description:** Not really a major issue, but whenever I try to save a scene whose root node is a base node, as opposed to a node2d or node3d, I get an error message in the console, saying it was unable to create a PNG image

![image](https://user-images.githubusercontent.com/51842726/80623390-1b4b7680-8a18-11ea-94e2-3599428a1505.png)

**Steps to reproduce:** Create a new scene. In *Create Root Node*, select *Other Node->Node* and simply save this scene. The message will show up in the output console

**Minimal reproduction project:** A project consisting of a single root node scene

**Comment by volzhs** [comment]
same error with #36456
I guess this happens when editor can't create a thumbnail for the current open scene.

**Comment by pycbouh** [comment]
To reproduce the issue a scene must contain no visual nodes and "3D Editor" feature must be disabled. If this feature is enabled, preview is generated without errors. A restart of the editor is required after the change in features. Still happens in `3.2.2-beta3` precompiled and with `3.2` branch.

In `master` branch I can't get this error the same way, but as soon as you disable "3D Editor" feature another issue starts popping: "Cannot get class 'StreamTexture'." This may or may not obscure the original issue in this case, I can't really tell. However, there had been many changes in related classes, so maybe it was indeed fixed as a side effect of one of them.
