### ISSUE TITLE
Add Soft Particle to blend particle's edges

### ISSUE THREAD

**Issue by samuncle** [godotengine/godot#3834]
One of the thing that "kills" the immersion in godot is Hard edge for particles.
Sadly there is no way to smooth the edges of particle when they intersect the geometry :(.

It would be very usefull to have an option in particle emitter to enable this (since for mobile it would be probably way too expensive).

I included a screenshot to illustrate the effect

![windows-live-writer-improved-particle-rendering_b00e-soft-particles_4](https://cloud.githubusercontent.com/assets/6406045/13331768/59eddc14-dbff-11e5-95bb-bb519d8f4925.jpg)

**Comment by bojidar-bg** [comment]
:+1:

**Comment by reduz** [comment]
easy to do once you have deferred rendering, which we don't :(

**Comment by jjbandit** [comment]
I'd be willing to give it a shot if someone can give me a shove in the right direction.  I'm new to the project so filenames and a hand-wavy description of what I'm looking for would be helpful :) @reduz

**Comment by volzhs** [comment]
isn't this already implemented?

**Comment by Calinou** [comment]
This is indeed implemented in the `master` branch since last week. It is called Proximity Fade and is available in SpatialMaterial (not to be confused with Distance Fade, which fades materials in a per-pixel manner based on the camera position).

**Comment by jjbandit** [comment]
Ah, beat me to it!

**Comment by akien-mga** [comment]
Indeed, fixed by bf371dcb3294027c209cc40a42fdbf438d4261af. Feel free to check the commit to see how it was done and get more familiar with this code though :)
