### ISSUE TITLE
Mono - GDScript extends C# Script

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#38352]
**Godot version:**
3.2.2 Beta 1 Mono

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
![image](https://user-images.githubusercontent.com/14253836/80693137-35c53480-8a98-11ea-8089-f4a59b2ec087.png)
![image](https://user-images.githubusercontent.com/14253836/80693203-47a6d780-8a98-11ea-8bcd-c8510263d825.png)

Since all scripts should be compatible with each other, GDScript should be able to extend C# Scripts.

For example:

```cs
class MyMonoScript : Node
{
    public void ComplexLogic()
    {
        
    }
}
```
```python
extends MyMonoScript

func _ready():
    ComplexLogic()
```

An example of how this may be used is a World.cs file with logic that a GDScript file can inherit so that custom worlds can be made with a single GDScript file

**Steps to reproduce:**
- Make a C# Script
- Make a GDScript that inherits that C# Script

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/4557280/Test.zip)

**Comment by akien-mga** [comment]
Well, I don't think this is expected to work, so please put more written text to specify whether you see this as a bug or a missing feature.

**Comment by Calinou** [comment]
cc @neikeq

**Comment by neikeq** [comment]
>Since all scripts should be compatible with each other

All "compatibility" (I would rather call it interoperability) that is provided between different script languages is `call`/`set`/`get` as well as signals.

Anything else is not expected to work, although improvements may be made. In the case of cross-language inheritance, it's never going to happen. Even if it's somehow possible, it would be too complex and prone to introduce many bugs.

The only sane way in which a C# class could inherit a GDScript class is if GDScript compiles to C# or IL.

**Comment by hsunekichi** [comment]
If gdscript support interfaces in the future (or purely abstract classes), would it be possible to support writing the interface in gdscript and implement it in c#? It may be feasible, since there is no actual cross-code involved
