### ISSUE TITLE
Flashing tooltip in editor

### ISSUE THREAD

**Issue by Bonkuraazu** [godotengine/godot#3835]
OS/version: Windows10 64bit/Godot2.0stable

This is a duplicate issue, but the previous one has been closed
(https://github.com/godotengine/godot/issues/1959).
I posted on reddit to see if anyone else was still having this issue and got a confirmation
(https://www.reddit.com/r/godot/comments/47lwv0/anyone_else_having_this_issue_with_the_ui_tooltip/).

The tooltip seems to flash on and off when you hover your cursor over a ui element. Also the wheel in the top-right corner of the editor ticks every time the tooltip flashes on or off. I haven't noticed this problem in any other application i've used on this system.

**Comment by vnen** [comment]
I can't reproduce this. Can you provide specific instructions to reproduce? Could you maybe make a GIF or small video showing the issue?

**Comment by ScotFlux** [comment]
Tested on Windows 10 x64 and Windows 7 x64.

1] CAN'T reproduce this issue. IF a or c
2] CAN reproduce this issue. IF b

I have a program called xwidget. The software used draw order: bottom, normal, topmost, and keep topmost. I use 2 items of xwidget : Clock and CPU meter.

a) One of them (Clock and Cpu meter) doesn't use the same setting. In my case, "Keep Topmost" for the Clock, while "Topmost" for the Cpu meter.
b) Both of them (Clock and Cpu meter) use "Keep Topmost"
c) Both of them (Clock and Cpu meter) doesn't use "Keep Topmost"

So, in my case, I guess if there are 2 items (or more) that use "Keep Topmost" will produce the bug.

**Comment by Bonkuraazu** [comment]
Okay, i have a little more information about what seems to cause this issue, at least for me. Only when I run certain programs at the same time as godot does this issue occur (again, tooltips work fine on other programs under these same circumstances). Some examples are a program called NetBalancer that i often have running in the background, or iTunes when a song is being played. Those are the only programs I could find that seem to cause this problem. I tried running similar programs like task manager, and playing music and video on other media players like vlc and web browsers, but I couldn't find anything else that got the tooltip flashing. They also seem to cause flashing at different rates. Also, if I have both of these programs running at the same time, the tooltip doesn't show up at all, and the wheel doesn't tick either.

So, if anyone wants to try to reproduce this, try running one of these programs and see if the tooltip's behavior changes.

Also, I tried messing around with xwidget and came across similar results to what ScotFlux got, only instead of the tooltip flashing, it stopped showing up at all (i didn't have itunes or netbalancer running at the time). Only when I had at least 2 widgets running with the setting "keep topmost" did the tooltip stop showing up. I couldn't get the tooltip to stop working under any other condition.

**Comment by vnen** [comment]
I can't really properly reproduce this issue with iTunes. It seems to me that the tooltip does disappear if another programs calls the window focus. Otherwise all of the tooltips appears on hover and don't flash nor go away.

The thing here is that tooltips in Godot disappear if you move the mouse even if the cursor remains over the button, which is inconsistent behavior considering every other application. This might (or not) be the reason for the flashing issue here.

**Comment by bojidar-bg** [comment]
@vnen Actually, is there a chance that the window manager/mouse sends mousemove events with delta of `(0,0)`? That would be a possible cause given your explanation.

To all that can reproduce -- can you try to disconnect the mouse while the tooltip is blinking, and see if the blinking continues?

**Comment by bojidar-bg** [comment]
Another example by @Dillybob92

[![](https://embed.gyazo.com/c57b3c1746e0f490ec78a6f37484bdea.gif)](https://i.gyazo.com/c57b3c1746e0f490ec78a6f37484bdea.gif)

**Comment by vnen** [comment]
@bojidar-bg I have no idea, it's weird if it does. What I can notice is that if you move the mouse outside of the windows it shows the tooltip if you happen to pass the mouse over a control just before leaving the window. Godot seems to ignore mouse move completely if it's out of the editor window.

**Comment by Banderi** [comment]
This bug has returned on 3.1, still occurring in 3.1.1/3.2 alpha, but since it was fixed I assume it has different causes now?
