### ISSUE TITLE
Scaling HBoxContainer children results in loss of alignment

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#38356]
**Godot version:**
<img width="542" alt="Screenshot 2020-04-30 at 16 51 04" src="https://user-images.githubusercontent.com/100964/80703601-c9cbe600-8b02-11ea-89d6-5460c06e116d.png">

**OS/device including version:**
<img width="766" alt="Screenshot 2020-04-30 at 16 52 32" src="https://user-images.githubusercontent.com/100964/80703706-00096580-8b03-11ea-8245-0426c4a05bf6.png">

**Issue description:**
When scaling a child of HBoxContainer, the item no longer matches the HBox alignment.

**Steps to reproduce:**
1. Create a HBoxContainer
2. Set the layout to `Top Wide`
3. Add a child MenuButton
4. Scale the MenuButton rect `rect.scale` to (0.1, 0.1)

The MenuButton will now be half way across the HBoxContainer

**Other information**
<img width="1440" alt="Screenshot 2020-04-30 at 16 54 42" src="https://user-images.githubusercontent.com/100964/80703878-52e31d00-8b03-11ea-9afe-09a5f905c926.png">

**Comment by pycbouh** [comment]
From what I can see, the `rect_scale` property on the `MenuButton` in this case is not editable and resets if you toggle visibility. Alignment is also displayed correctly after the toggling.

**Comment by groud** [comment]
This is the expected behavior. Children of containers get their size and position (which are proxies of the margins values), overridden by the container itself. Changing those values should not be done and might lead to unexpected behaviors. 

I think there is already a PR somewhere to fix that by disabling the edit of those properties, but I could not find it.

**Comment by pycbouh** [comment]
Here it is: #30623

**Comment by groud** [comment]
Exactly, thanks ! :)

**Comment by groud** [comment]
Oh, in fact I just realized that I am probably wrong. `rect_scale` is not `rect_size` and thus is not overridden by the parent container.

But this make this issue a duplicate of #19068.

**Comment by tavurth** [comment]
Thanks guys! 

Glad to know it's not a bug. It had me confused for a while so I'm glad there's a PR to prevent editing of the properties.
