### ISSUE TITLE
Avoiding case switches (GDScript code)?

### ISSUE THREAD

**Issue by Keyaku** [godotengine/godot#3836]
This is more of a request in order to make a better-looking code, at least on [GDScript's part](https://github.com/godotengine/godot/tree/master/modules/gdscript).

The question can be read as either "Avoiding case switches?" or "Writing code with inlining on?" since they're related as I'll explain.

I understand the use of case switches: it's in order to generate a jump table (just as the comments suggest). However, I'm not sure what's the objective behind it, unless to get an algorithmic complexity of O(1), to which I say that [jump tables do not imply that we have O(1) lookup](http://stackoverflow.com/a/1837986/4103007) (source to be thoroughly verified, although it's what I also learned from data structures class).  
Even if we do get instant lookup, the code is a far cry from being good-looking (read "maintainable").

Instead of using them, at least in some instances, it's best to use an array of constant function pointers. I was going to start writing this and send a PR but I lack the knowledge to turn on inlining (or add -finline-functions to CFLAGS) with the current `scons` setup.

If you prefer using case switches for these cases (no pun intended), I'll drop this subject.

**Comment by kubecz3k** [comment]
@reduz or @punto- take a look at this issue please :)

**Comment by bojidar-bg** [comment]
Ping @reduz :smile:

**Comment by reduz** [comment]
I like the code as it is, sorry. Feel free to close.
