### ISSUE TITLE
Duplicate default shortcuts in Editor Shortcut Settings

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#38362]
**Godot version:**
Godot Engine v4.0.dev.custom_build.a6e3c84c6

**OS/device including version:**
WIN 10 1903

**Issue description:**
"Soft reload script" and "Find In Files" have same shortcut (control+shift+R) and **they can be executed at the same time from the came context (script editor)** 

**Steps to reproduce:**
View editor shortcut settings

**Minimal reproduction project:**
N/A

Probably good to do a check of all default shortcuts to ensure there are no overlaps where they can be called from the same context.

Especially considering after a shortcut is matched, no furthers are executed even if they have the same binds.

**Comment by Calinou** [comment]
I guess we could rebind Soft Reload Script to <kbd>Ctrl + Alt + R</kbd>.

**Comment by TheFlamyy** [comment]
Has the "Find in Files" shortcut been changed? Please correct me if I'm wrong but as far as I recall it's  `ctrl + shift + f` in v3.2.1

**Comment by Calinou** [comment]
@TheFlamyy I think OP meant *Replace* in Files, rather than Find in Files.
