### ISSUE TITLE
SchlickGGX subtractive on Android with GLES2

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot#38374]
**Godot version:**
`v3.2.1.stable`

**OS/device including version:**
LineageOS 16.0 (Android 9) on Xiaomi Mi Note 2

**Issue description:**
SchlickGGX specular is subtractive on Android when using GLES2:
![on android](https://user-images.githubusercontent.com/36982494/80780198-253bb980-8b7f-11ea-8f9f-d5720d236202.png)

Here's how it's supposed to look (from the editor):
![from editor](https://user-images.githubusercontent.com/36982494/80780232-443a4b80-8b7f-11ea-8707-39481324f7e8.png)

This doesn't happen with GLES3.

**Comment by clayjohn** [comment]
I think this may be related to https://github.com/godotengine/godot/issues/33633 which was partially solved by https://github.com/godotengine/godot/pull/33646

**Comment by clayjohn** [comment]
Fixed by #44489 :)
