### ISSUE TITLE
Exported onready vars don't appear in inspector

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#38379]
**Godot version:**

v3.2.1

**Issue description:**

Exported variables with the onready keyword added don't show in the value in the inspector.

**Steps to reproduce:**

Create a node with a script that contains `export onready var test = "test"`. The property "test" won't show in the inspector.

**Comment by samdze** [comment]
Isn't it just because it will only assign "test" to test on the ready notification at runtime?

**Comment by Jummit** [comment]
Yeah, that's probably what's happening. The expected result is that the exported value only gets set on the ready notification. This would be useful in combination with the setget keyword:
```gdscript
extends Node

export onready var title = "test" setget set_title

func set_title(to):
  title = to
  # would give an error if title wouldn't have the onready keyword,
  # as set_title would be called before _ready
  $TitleLabel.text = to
```

**Comment by KoBeWi** [comment]
This is just not supported yet. Closing because there's a proposal already: https://github.com/godotengine/godot-proposals/issues/325
