### ISSUE TITLE
Editor keeps GDNative DLL file open

### ISSUE THREAD

**Issue by pomalley** [godotengine/godot#38371]
**Godot version:** 3.2.1 win64 stable

**OS/device including version:** Windows 10

**Issue description:** After I run a project that uses the GDNative DLL, the editor keeps the file open. (So that it cannot be overwritten by a freshly compiled one, for example.) This means that every time I change the GDNative code, I have to quit the Godot editor.

**Steps to reproduce:** This happens with the GDNative example project from the Godot docs.

**Minimal reproduction project:** GDNative example project.

I raised [this question](https://godotengine.org/qa/68555/editor-keeps-gdnative-dll-file-open) at the Godot Q&A but got no traction. I believe this is the same issue as #29017 from a year ago, but rebooting the OS did not solve it.

**Comment by akien-mga** [comment]
That's a Windows OS limitation, if a process used a file (here Godot), you can't overwrite it.

**Comment by sheepandshepherd** [comment]
Is the GDNativeLibrary's `reloadable` property `true`? This should unload the DLL to allow recompiling when you switch away from the Godot window.

Actually, just noticed that the tutorial has it set to `false` by default. Maybe that should be changed. `reloadable` is always safe to use unless your library adds tool classes (like EditorPlugins).

**Comment by pomalley** [comment]
Thank you! I was missing `reloadable`. (I was hoping there was some kind of option somewhere.)
