### ISSUE TITLE
Can't set up Android SDK for Custom Build.

### ISSUE THREAD

**Issue by nkrapivin** [godotengine/godot#38381]
**Godot version:**
3.2.1-stable win64

**OS/device including version:**
Windows 10 1809

**Issue description:**
I have an installation of Android SDK installed on D: drive and I chose it in Editor settings. When I try to use it in Android export it says "Invalid Android SDK path", it detects an SDK installation by checking if `platform-tools` folder exists in it, and it exists, so I have no idea why it fails.

My SDK path does not contain any whitespaces `D:\SDKs\Android\Sdk`

**Steps to reproduce:**
?

**Minimal reproduction project:**
None required(?)

**Comment by dreamsComeTrue** [comment]
Just a blind guess, but can you try inverting backslashes `\` to slashes `/` ?

**Comment by nkrapivin** [comment]
I did select the SDK path in the Editor itself so the slashes are okay I guess.

**Comment by nkrapivin** [comment]
It's weird that there's no option to override an error message and build anyway, it would help a lot.

**Comment by nkrapivin** [comment]
Manually removing that error check resolved the issue for me.

**Comment by akien-mga** [comment]
This was fixed by #38172 already (and cherry-picked for 3.2.2).
