### ISSUE TITLE
Lingering context actions in toolbar

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#38389]
**Godot version:**
3.2.1.stable.mono.official

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When selecting an object that adds a context menu to the toolbar and deselecting it, the menu for that object stays in the toolbar until replaced with a different one or cleared thought an object that doesn't have an entry there. The problem is that it becomes unclear which object that entry belongs to.

![lingeringcontext](https://user-images.githubusercontent.com/8841352/80813918-38747680-8bcb-11ea-8be5-b1ea0e656cdd.jpg)

**Steps to reproduce:**
create a meshInstance, select it and deselect it (nothing selected), the 'Mesh' toolbar entry stays visible

**Comment by KoBeWi** [comment]
Related to #35989
