### ISSUE TITLE
Project directory scan hang / crash when missing execution bit

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#3838]
**Operating system or device:**

Linux 64-bit

**Issue description** (what happened, and what was expected):

Scan (or Auto-scan) a directory for projects, Godot will either crash with no console output, or hang.

**Steps to reproduce:**

Launch Godot and scan a directory. It will crash or hang (I've experienced both) if the user running Godot lacks the eXecute permission to any subdirectory of the chosen directory to scan.

For instance:

mkdir -P /home/user/projects/test
chmod 666 /home/user/projects/test
or
chown root.root /home/user/projects/test
chmod 700 /home/user/projects/test

Now, launch Godot and try to scan /home/user/projects - Godot will hang or crash.

**Link to minimal example project** (optional but very welcome):

N/A

**Comment by techtonik** [comment]
I experienced crash/hang on Windows where I just pointed Godot to drive root. I guess it is running out of memory and some operations are blocking.

**Comment by nunodonato** [comment]
It's not crashing due to the folder permissions but for the same problem as @techtonik reported.
You can't cd intro a dir you dont have permissions. When you press scan, it will scan the current dir (your home), which is probably segfaulting due to being a huge folder..

**Comment by nunodonato** [comment]
I did some debugging on this, I also got a crash when scanning home. Upon close inspection, I had a loop with symlinks, where a folder would point back to a previous folder, that seemed to cause the crash. Deleting this folder solved my problem and I can scan my home folder fully without problems

**Comment by nunodonato** [comment]
how about setting a reasonable max depth for the directory scan? like 10-15?

**Comment by techtonik** [comment]
Make it non-blocking and provide a progress bar? With ability to limit depth and other params?

**Comment by nunodonato** [comment]
directory size seems to be irrelevant, the problem is the endless loop which causes the scan function to call itself recursively an infinite number of times. A depth limit would certainly solve this, but there might be other options.

**Comment by slapin** [comment]
Depth limit will just hide issue, it should not loop or be recursive.
Adding shortcuts like this will just add more complicated problems later.

**Comment by nunodonato** [comment]
well in its current implementation, the function is recursive and doesnt track the full paths so it is impossible to avoid repeated folders.

for me its always a balance between idealistic perfection and what is good enough to solve problems. 

people scan a folder usually when they download a zip with demos, or have a place with other godot projects. nobody really needs to scan a 100-folder-deep directory structure :)

what more complicated problems do you think this could add later?

**Comment by techtonik** [comment]
>  nobody really needs to scan a 100-folder-deep directory structure 

Actually, I needed. Not that I had projects at 100th level, but at least pass those dirs successfully.
