### ISSUE TITLE
Thumbnails not generated for .tscn format 

### ISSUE THREAD

**Issue by zendorf** [godotengine/godot#3839]
I have recently started using the .tscn format instead of .scn in the stable v2.0 and noticed that there are no thumbnails being generated for this format like there are for .scn files.

![tscn_thumbnail](https://cloud.githubusercontent.com/assets/7741669/13344189/e009677a-dca7-11e5-8fa5-57e789c2ff4a.png)

**Comment by akien-mga** [comment]
Thanks for the report! This is already tracked in #3640 though, so closing this one.
