### ISSUE TITLE
Vulkan: Spatial shader ignores occlusion

### ISSUE THREAD

**Issue by RicardRC** [godotengine/godot#38399]
**Godot version:**
master branch [d2887ea]

**OS/device including version:**
Windows10

**Issue description:**
Spatial shader completely ignores foreground object in 4.0, working well in 3.2.

Godot 3.2: Notice how the cube cuts the dawn light
![Anotació 2020-05-01 212817](https://user-images.githubusercontent.com/35220750/80835959-1b07d280-8bf4-11ea-82a6-c48bd8ec79e2.png)

Godot 4.0: Even if it does not look like it, the cube is exactly at the same location
![imagen](https://user-images.githubusercontent.com/35220750/80837029-48ee1680-8bf6-11ea-9de6-810e703e547d.png)

**Steps to reproduce:**
Open the project linked at the end.
Add a mesh instance, box for example, as child of the camera.
Move it so it partially blocks view
Run the project.

(When running on 4.0, the script for the camera will need to be changed from "extends Camera" to "extends Camera3D", and the atmosphere shader from "depth_test_disable" to "depth_test_disabled")

I've positioned the blocking object like this on both cases:
![imagen](https://user-images.githubusercontent.com/35220750/80835855-e136cc00-8bf3-11ea-9abc-0ce94cf2bcb5.png)

**Minimal reproduction project:**
https://github.com/Dimev/Realistic-Atmosphere-Godot-and-UE4

**Comment by akien-mga** [comment]
Is this still reproducible in the current `master` branch / recent 4.0 alpha builds?

The minimal reproduction project isn't trivial to convert so that it can actually run in current 4.0 builds.

**Comment by RicardRC** [comment]
Sorry! I lost the original minimal repro from which I took the captures a long time ago.

**Comment by akien-mga** [comment]
Closing then, a lot of fixes have been made in the past 2.5 years so this might well be fixed.
