### ISSUE TITLE
Godot grid disappears 3d

### ISSUE THREAD

**Issue by Immortal000** [godotengine/godot#38401]
**Godot version:**
Godot 3.2.1
**OS/device including version:**
Windows 10
**Issue description:**
The grid disappears as soon as I add a mesh to the mesh instance. my "display grid" is turned on but I don't see the grid on my project. I am able to see the grid when I hide the mesh instance and when I turn to a specific angle. 
**Steps to reproduce:**

**Minimal reproduction project:**
![image](https://user-images.githubusercontent.com/54898201/80843257-78d2f500-8bc9-11ea-8ce2-bb525e31ee0c.png)

**Comment by Calinou** [comment]
@Immortal000 What graphics card model do you have?

**Comment by Immortal000** [comment]
> @Immortal000 What graphics card model do you have?
intel(R) HD Graphics 620

**Comment by Immortal000** [comment]
Its fixed. I switched to GLES2

**Comment by Calinou** [comment]
For the record, this is a duplicate of #30330.

**Comment by Immortal000** [comment]
thank you
