### ISSUE TITLE
GDScript editor erases any unsaved changes when window regains focus

### ISSUE THREAD

**Issue by Scipi** [godotengine/godot#3840]
I'm running into a major bug with scripts on 64-bit Windows in the Steam version of Godot.

If you make a change in a script and change focus to another window without saving the script, upon regaining focus the editor seems to reload the script from disc and you lose any changes you've made.

**Comment by akien-mga** [comment]
Thanks for the report. Could you specify which scene format you used (.scn, .tscn or .xscn/.xml), and if you saved the script as an external .gd file, or are using it embedded in the scene file?

**Comment by Scipi** [comment]
I have my scenes saves in .scn format and my scripts are external .gd files.

**Comment by ret80** [comment]
dublicated  #3764

**Comment by akien-mga** [comment]
Indeed, nice catch @ret80. Closing as duplicate of #3764 (I'll add some of the info from this report there too as it helps understand the bug).

**Comment by punto-** [comment]
I can't reproduce. Can you capture some video of this?

**Comment by Scipi** [comment]
@punto- I managed to get some video here: https://www.youtube.com/watch?v=PNo32_Bhtu0
