### ISSUE TITLE
Godot Crashes after importing a .ogg file on AudioStreamPlayer

### ISSUE THREAD

**Issue by rafaeldelboni** [godotengine/godot#38418]
**Godot version:**
3.2 branch with https://github.com/godotengine/godot/pull/38361

**OS/device including version:**
Arch Linux 5.6.8

**Issue description:**
importing a `.ogg` file on AudioStreamPlayer Godot crashes.

**Steps to reproduce:**
Open Godot create a scene and add a AudioStreamPlayer and import a .ogg audio file

**Minimal reproduction project:**
Attached is a sample file:
https://we.tl/t-ROYqq0xkYZ

### Logs
```
Godot Engine v3.2.2.beta.custom_build.8426ed265 - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)

godot.x11.tools.64: thirdparty/misc/stb_vorbis.c:4160: start_decoder: Assertion `f->temp_offset == f->alloc.alloc_buffer_length_in_bytes' failed.
```

**Comment by rafaeldelboni** [comment]
I recompiled with stb_vorbis v1.17 and all is working fine again.

**Comment by akien-mga** [comment]
Thanks for catching the regression so early, I'll look into it.

**Comment by RandomShaper** [comment]
I've been bitten by this, too. I'm checking it to see if it's fixable without reverting the new version of stb_vorbis.

**Comment by avencherus** [comment]
Yes, just experienced this last night when building 3.2.  My editor crashes immediately though on start up.
