### ISSUE TITLE
Upon opening a project to edit the "Fix Dependencies" dialog appears and claims

### ISSUE THREAD

**Issue by Megalomaniak** [godotengine/godot#3842]
Likely related to: https://github.com/godotengine/godot/issues/3794

Also quoting my own post from there just for completion:

> Still having this issue with the 2.0 official release/build and .scn files on Windows 7 64 bit.
> PS. My projects folder is on drive E: and godot is 'installed' to drive D: in case this might make any difference.
> 
> ![godoterrorloading](https://cloud.githubusercontent.com/assets/3162126/13362608/2984dbb6-dcce-11e5-8400-1c4e6377cbc0.png)
> 
> ![godotfixdeps](https://cloud.githubusercontent.com/assets/3162126/13362544/e0601108-dccd-11e5-8cf7-4ed168ff6506.png)
> Whats really bizarre: All those files are exactly where the paths indicate. They shouldn't even be 'broken'!
> 
>  `core/io/resource_format_binary.cpp:434 - Couldn't load resource: res://GUI/Themes/Fonts/CinzBitmap16.fnt`

**Operating system or device:**
Windows 7 64 Bit Running godot 2.0 release build downloaded from godotengine.org.

**Issue description** (what happened, and what was expected):
Error Loading: dialog opens, reporting files as missing even though they are exactly where the corresponding paths indicate.

**Steps to reproduce:**
1. open godot
2. select project(included below) and click 'edit'
3. 'profit!'

**Link to minimal example project** (optional but very welcome):
[test1.zip](https://github.com/godotengine/godot/files/148894/test1.zip)

**Comment by quantum-entangler** [comment]
Forgot to include the SIL OFL license(legally important I recon) and the source fonts in case they are needed:
[Cinzel SIL OFL.zip](https://github.com/godotengine/godot/files/148911/Cinzel.SIL.OFL.zip)

**Comment by eska014** [comment]
Was this file saved with editor setting `On Save`→`Save Paths As Relative` enabled?

**Comment by quantum-entangler** [comment]
yes, Save paths as relative is(and was) enabled. Can't see what situation would possibly benefit from the opposite.

**Comment by steelxtreme** [comment]
I have reported this issue couple weeks ago. https://github.com/godotengine/godot/issues/3706

**Comment by quantum-entangler** [comment]
@steelxtreeme Right could be related, however I have noticed in my example project that clicking open  loads(for me at least) those 'missing' files in (to the editor) anyways (with the exception of the .fnt file generated from the fonts included above).

**Comment by steelxtreme** [comment]
I guess it is exactly the same , it's happening with godot custom formats, i have tested with .mtl for    material, shader file and .scn . altough raw .XML file instead  works properly.  In your case i dont remember if .XML can be used instead .fnt format.

**Comment by eska014** [comment]
Let's close this as a duplicate of #3706, it's cross-referenced anyway

**Comment by akien-mga** [comment]
I'd actually close #3706 as duplicate of this one, here there are pictures :p (and more users involved)

**Comment by akien-mga** [comment]
From #3706:

> -Create new project
-Create 2 folders in root( I created  scene and texture folders.
.Create scene,add a node and save it into scene folder.
-put some image into texture folder.
-create sprite node and load texture. save the  scene.
-close project and open it again.
-open scene and godot is unable to load texture.

> I have attached an example project.
[test_bug.zip](https://github.com/godotengine/godot/files/129436/test_bug.zip)

**Comment by quantum-entangler** [comment]
Probably worthless info, but I tried to create a new scene with differing folder structure and thought I'd report that I ruled out 2 things:

1. tested with all folder names without any capitalization in any folder names, in case that's creating issues for some odd reason, but nope. No difference. And,
2. made sure that all the folder structures and resources would be placed deeper than the scenes loading the resources, so there would be no traversing upwards (eg. no ../folder/resource.ext)
And that didn't change anything either. :(

**Comment by quantum-entangler** [comment]
In case scenes saved with relative paths in windows version load without issues on other platforms, I propose that we change the title of this issue to:
**Windows: Issue loading scenes saved with relative paths**

This way it will be clear what the issue actually is.
I'd make the change now, but I _currently_ have no other systems setup beyond windows 7 ones to test and confirm with.

**Comment by bojidar-bg** [comment]
Is this still valid on current master?
Does it work when "save as relative" is left unchecked?
Does it happen on other platforms?
(I'll also check some of these)

**Comment by drtwisted** [comment]
Still having the issue.
I have a simple structure like:
| **scenes** (scenese here)
|---**images**
|------**sprites** (images here)
|----**helper_scenes** (scenese here)

I know, but so it went that I keep all resources under scenes directory :)
So after I added fonts directory under scenes and put a ttf font in there and used it as Dynamic font in a new scene saved in helper_scenes everything broke.
Niether do I have resources loaded in the editor, nor do they load from within the script with **preload** . The issue is quit old are there any updates on it yet?

**Comment by drtwisted** [comment]
Figured out, that somehow when I started the project and had copied the path's for sprites from the built-in File System tab the paths were like 'res://images/[...]'. And after I've added the font and the corresponding directory, path started to look like 'res://scenes/images/[..]', which is how it should've been from the start obviously. I do remember Godot updating a couple of times in between, though. (Using Steam version)

**Comment by bojidar-bg** [comment]
I think we removed the relative paths option recently, is this correct?

**Comment by drtwisted** [comment]
Have found the fix in the release notes three releases ago. Don't know how did all this thing worked out. Anyways, everything is fine now, and hope will be further on.

**Comment by Megalomaniak** [comment]
@akien-mga Good god its been so long I had forgotten. I think it is safe to close this.

**Comment by denisjecar1** [comment]
I had a similar issue but no paths were red so popup message did not work, also paths were correct in .tscn files. Only thing that got this fixed was to open the scene with broken dependencies and save it one more time
