### ISSUE TITLE
get_node returns null objects arbitrarily

### ISSUE THREAD

**Issue by eko234** [godotengine/godot#38425]
i'm trying to access one of my nodes children, but when i use the method get_node, it first returns me a [Object:Empty] and then it returns the current object, obviously crashing the game, doing something so simple as :

`var nd := get_children()
print(str(nd))`

results in the following output

[]
[[CanvasLayer:1183], [Node2D:1197]]

**Comment by eko234** [comment]
wow, apparently it had something to do with the fact that the node "GOD" was already taken for godot i guess.

**Comment by asheraryam** [comment]
If there are reserved Node names then they should definitely be documented somewhere.

**Comment by eduardonunesp** [comment]
Hey @eko234 do you have some example that can be reproduced by devs?

**Comment by Calinou** [comment]
Duplicate of #32383?

**Comment by KoBeWi** [comment]
@eko234 Can you test again in 3.2.2 beta 3?
btw there are no reserved node names.

**Comment by madmiraal** [comment]
Closing as unable to reproduce without a minimal reproduction project.
