### ISSUE TITLE
The phrase "q0" is highlighted as a keyword in the editor

### ISSUE THREAD

**Issue by umfk** [godotengine/godot#3843]
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
Typing "q0" in your script gets it highlighted in yellow even though it's not a keyword.

**Steps to reproduce:**
Type "q0" into a script and bask in the yellow light.
![bug](https://cloud.githubusercontent.com/assets/17507776/13370545/537bcc0a-dce1-11e5-8df0-409e4938a00d.png)

**Comment by bojidar-bg** [comment]
Can confirm

**Comment by akien-mga** [comment]
@bojidar-bg and I had a look and it doesn't seem obvious to find the cause of this bug, so removing the junior job tag.

**Comment by bojidar-bg** [comment]
Here is a snippet from IRC, showing our finds (not from official godot engine channels):

**\<bojidar_bg\>** BTW, searching for "q0" ( https://github.com/godotengine/godot/issues/3843 ) in the repo didn't lead to any finds...
**\<Akien\>** bojidar_bg: Yeah I've tried to understand #3843 too but couldn't
**\<bojidar_bg\>** Akien: maybe some wierd hashing stuff?
**\<bojidar_bg\>** Akien: only place outside drivers is scene/resources/animation.cpp
**\<Akien\>** Well it probably wouldn't be "q0" directly, but more likely some parsing of a 'q' token and then '0'
**\<bojidar_bg\>** Akien: where were highlighted words defined? :D
**\<bojidar_bg\>** Akien: I grepped for 'q too, no luck
**\<Akien\>** bojidar_bg: Check tools/editor/plugins/script_editor_plugin.cpp
**\<Akien\>** The part after "set_syntax_coloring(true)"
**\<Akien\>** It then refers to functions in modules/gdscript, etc.
**\<Akien\>** I've looked at it but couldn't find the culprit hehe
**\<Akien\>** I guess with some prints of the actual keywords it could be narrowed down
**\<bojidar_bg\>** Akien: they come from gdscriptLanguage::get_reserved_words :P
**\<bojidar_bg\>** so, https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_editor.cpp
**\<bojidar_bg\>** so, https://github.com/godotengine/godot/blob/6ea0863ed3e836127cfd38587a50679d40ca40bc/modules/gdscript/gd_script.cpp#L2678 :D
**\<Akien\>** Yeah I've checked that, but did not find any q :p
**\<bojidar_bg\>** Akien: https://github.com/godotengine/godot/blob/6ea0863ed3e836127cfd38587a50679d40ca40bc/modules/gdscript/gd_script.cpp#L2722
**\<Akien\>** s/q/clue/ ;
**\<bojidar_bg\>** maybe that one ? :D
**\<Akien\>** I wondered about that one too :p
**\<Akien\>** But that's still weird hehe
**\<bojidar_bg\>** Akien: who shall try removing it? :D
**\<Akien\>** Why would it make "q0" a keyword?
**\<bojidar_bg\>** Akien: no reason :P
**\<Akien\>** I have no clue what it does, but I'm not good with static const char* stuff :)
**\<bojidar_bg\>** Akien: maybe it would get the memory from another location
**\<bojidar_bg\>** so the q actually is some texture or something..
**\<Akien\>** You can try )
**\<Akien\>** :)
**\<bojidar_bg\>** Akien: also, if this makes some error... https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_functions.cpp#L110
**\<bojidar_bg\>** but it has a ERR_FAIL_INDEX_V(p_func,FUNC_MAX,""); guard
**\<bojidar_bg\>** so, no
**\<bojidar_bg\>** Akien: nope, not from that zero
**\<bojidar_bg\>** nothing has changed
**\<bojidar_bg\>** Akien: actaully it seems like a condition to terminate the loop on 2728
**\<bojidar_bg\>** Akien: seems like no luck for today :P
**\<bojidar_bg\>** Akien: so, not a junoir job
**\<bojidar_bg\>** better if they don't try :P

**Comment by nunodonato** [comment]
The problem is in String::hash() in ustring.cpp.
It seems the hash generated for "q0" is the same as for the keyword "or" :)

**Comment by nunodonato** [comment]
here's an improved algorithm for the hashing function (less collisions and better performance)
`static const unsigned int FNV_PRIME = 16777619u;
static const unsigned int OFFSET_BASIS = 2166136261u;

unsigned int hash2(char* str)
{
    unsigned int hash = OFFSET_BASIS;
    while ((*str))
    {
    	hash ^= *str++;
    	hash *=FNV_PRIME;
    }

    return hash;
}`

**Comment by nunodonato** [comment]
PS - I tested and compared the performance of the two algs in a 10000000 for cycle. My suggested solution is faster, but only when the strings are relatively small. When I switched to longer strings (14chars), the performance was only slightly worse than the current one.

**Comment by bojidar-bg** [comment]
@nunodonato ~ BTW, your solution might (must) still have collisions. That's a general problem with hashing... Maybe a better solution would be to compare strings directly, even after the same-hash test passes :smile: 

Still, if it is better, we might include your hash function too.

**Comment by reduz** [comment]
Feel free to make a PR with your hash function, if performance is about the
same there shouldn't be a problem.
That said, it may be a mistake to rely on hash functions for this feature
(or maybe longer/64 bit hashes should be used)

**Comment by hetdegon** [comment]
I found another random false positive, "acR":
![snapshot10](https://cloud.githubusercontent.com/assets/323651/13770150/49ee9d50-ea85-11e5-92c6-b660c287896a.png)

**Comment by bojidar-bg** [comment]
I guess we should both use hashes, and string comparison... or maybe the `Dictionary` class already does it?

**Comment by reduz** [comment]
I'm checking the code again, I can't find anywhere a hash alone is being used..

**Comment by reduz** [comment]
Something must be wrong and I am being unable to see it:

here the hash is computed
https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp#L836
and here the value is obtained from the hash **and the string**
https://github.com/godotengine/godot/blob/master/core/hash_map.h#L401

as you can see above, there is a string comparison happening too, so unless I'm missing something, it makes no sense that "q0" or "acR" are reported as keywords.

We should add some kind of tag "paranormal investigator job".

**Comment by SuperUserNameMan** [comment]
> We should add some kind of tag "paranormal investigator job".

Yeah, because that was actually a very StrRange bug.
