### ISSUE TITLE
error: unknown warning option '-Wshadow-local' when compiling.

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#38437]
**Godot version:**
Latest master 

**OS/device including version:**
Windows 10 Enterprise, 1909

**Issue description:**
```
godot>scons
scons: Reading SConscript files ...
Automatically detected platform: windows
Configuring for Windows: target=debug, bits=default
Using MinGW
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  1%] [94mCompiling [95m==> [93mplatform\windows\godot_windows.cpp[0m
=====
b"error: unknown warning option '-Wshadow-local' [-Werror,-Wunknown-warning-option]\r\n"
=====
scons: *** [platform\windows\godot_windows.windows.tools.64.o] Error 1
scons: building terminated because of errors
```

**Steps to reproduce:**
Run `scons` in Godot source folder.

**Compiler:**
LLVM-MinGW 9.0 and 10.0 from https://github.com/mstorsjo/llvm-mingw/releases.

**Comment by akien-mga** [comment]
Seems like your compiler is misidentified as GCC by `methods.using_gcc()`. Could you debug it further there in `methods.py` to find out why?

**Comment by Anutrix** [comment]
I just realised that `scons` never worked ever with llvm-mingw. `scons use_llvm=true` works fine like it used to.
Should I close this issue or is it supposed to detect it even without `use_llvm=true`?

**Comment by Anutrix** [comment]
I traced env["CC"] back to Windows's detect.py where it turned out that it differentiates between gcc and llvm by just presence of "use_llvm".
Hence, closing issue.

**Comment by bruvzg** [comment]
AFAIK currently, there's no standard and stable LLVM+MinGW toolchain, consistent detection probably won't be easy to do, `use_llvm=true` option was designed specifically for the https://github.com/mstorsjo/llvm-mingw toolchain, it's probably won't work with any other flavor of clang.
