### ISSUE TITLE
Can't Import shape keys animations from Blender using GLTF2

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#38443]
**Godot version:**
3.2.1

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
I'm unable to import the animation of a shape key form Blender, the shape key object and the rest of animations get imported OK
![shapes](https://user-images.githubusercontent.com/27329423/80927275-0450af80-8d9d-11ea-9cfc-98b237c2c3d7.jpg)

And I can manually animate it inside Godot, but I cannot import the animation.

**Steps to reproduce:**
Export Suzanne to Godot using GLTF2

**Minimal reproduction project:**
[SuzanneShapeKey.zip](https://github.com/godotengine/godot/files/4571908/SuzanneShapeKey.zip)

**Comment by fire** [comment]
The animation sliders in Godot don't move the shape keys manually in Godot either, so it's not an animation player problem.

Still looking.

**Comment by Janders1800** [comment]
Note: I use this settings to export.
![Captura de pantalla de 2020-05-04 00-24-32](https://user-images.githubusercontent.com/27329423/80927383-d9b32680-8d9d-11ea-8595-d133ea22f4d9.png)

**Comment by Janders1800** [comment]
I tested with another blend and it seems to try to import something (totally broken), at this point I don't know if the problem is some obscure setting in Blender.
![Captura de pantalla de 2020-05-04 00-30-36](https://user-images.githubusercontent.com/27329423/80927561-dff5d280-8d9e-11ea-9386-d355e0307b25.png)

This character was rigged using Rigify.

**Comment by fire** [comment]
Rigify needs the baked version, not the raw blender skeletal.

**Comment by fire** [comment]
I had to apply the modifier as a shapekey.

Also the action was attached to the wrong animation.

![image](https://user-images.githubusercontent.com/32321/99299929-caa73980-2800-11eb-82c6-a05b21354599.png)

![image](https://user-images.githubusercontent.com/32321/99300017-e9a5cb80-2800-11eb-9db4-a90c2c2dcf91.png)

**Comment by Janders1800** [comment]
Applying the modifier is not an option if you need to keep the bones, let's say, for IK movement.

Can you post an image of the action editor?

**Comment by fire** [comment]
Ping!

The issue was lost. What is the current status of this?

**Comment by JWBWork** [comment]
@fire any chance you ever found a fix for this?

**Comment by fire** [comment]
I'm not able to spend more time on this but posted a relevant blender screenshot.

![image](https://user-images.githubusercontent.com/32321/150429026-a0cc6494-0241-4089-bc55-0d23414e645c.png)

**Comment by JWBWork** [comment]
no luck preserving my shape keys, but thanks for replying 🙏🏻

**Comment by lyuma** [comment]
Blend shape animation tracks were redesigned in 4.0 and we believe the original issue is no longer reproducible.
@JWBWork if you still have issues with blend shape animation import in 4.0rc3 or later please open a new issue with reproduction project.
