### ISSUE TITLE
[Mono] 3.2.1 ImageTexture don't set flags in code

### ISSUE THREAD

**Issue by Hromon** [godotengine/godot#38445]
**Godot version:**
3.2.1 mono
**OS/device including version:**
Windows 10
**Issue description:**
Method CreateFromImage() on ImageTexture don't use flags.
**Steps to reproduce:**
Write this code:
Image ImageTexture;
ImageTexture Texture = new ImageTexture();
ImageTexture = new Image();
ImageTexture.Create(50, 50, false, Image.Format.Rgba8);
ImageTexture.Lock();
ImageTexture.SetPixel(new Vector(25,25), new Color(0, 0, 0));
ImageTexture.Unlock();
Texture.CreateFromImage(ImageTexture, 0);

And add this in TextureRect.

**Comment by Calinou** [comment]
Does this also occur with GDScript?

**Comment by Hromon** [comment]
> Does this also occur with GDScript?

No. I create Node and create GDS method, Call() this method in C# and all great work, but if i use CreateFromImage() in C# that don't work(

**Comment by Hromon** [comment]
Image is not cached anywhere?
