### ISSUE TITLE
translation server returns key

### ISSUE THREAD

**Issue by GoDino** [godotengine/godot#38448]
**Godot version:**
3.2

**OS/device including version:**
windows 10

**Issue description:**
if the translation is empty ("") in a certain language, the server returns the key (po files), a single quote " (csv), or the english translation if left empty without quotes. It does not seem consistent. From a developers viewpoint it should just return whatever is there (automation always being a source of error), so if "empty", it should return "empty". Returning the key, another language or a single quote all seem useless except in pointing out "there is no translation here". If "no translation" is intentional as could be the case where something is not being translated for certain markets, there is no way to achieve that.

**Steps to reproduce:**
open attached projects and run.

**Minimal reproduction project:**
[translation_csv.zip](https://github.com/godotengine/godot/files/4574155/translation_csv.zip)

**Comment by Calinou** [comment]
> if the translation is empty "" in a certain language, the server returns the key (po files)

For .po files, this is expected behavior (as specified by the gettext specification). This should be documented more clearly.

**Comment by GoDino** [comment]
I was too fast to open the ticket, will be attaching the examples, thanks for the clarification about .po files

**Comment by GoDino** [comment]
We used the workaround for using the english translation as a key in .po files but this becomes hard to handle when the text is rather long, like a description on a info page.

**Comment by GoDino** [comment]
taking a further look, the following really seems to be a bug:

"untranslated entries" with quotes ("") in a csv get replaced by a single quote ("), this is csv-only and happens when parsing the csv file.

otherwise, for all untranslated entries the fallback language is used which can be set in the propertes. If that language does not exist, the key is returned. All this is expected behaviour.

This makes it impossible to omit a translation intentionally, so I opt for an additional project-preference-localization checkbox like "use fallback", that is on by default but can be switched off if no fallback language is desired. In this case, an empty entry for a language remains empty.

It seems trivial to implement, I would be happy to do so.

**Comment by GoDino** [comment]
oh and while I am at it, I think it would be interesting to see translations in the editor, I propose a enum "editor language" and maybe a checkbox "show translations" so we are backward compatible

here is a related community question:
[https://godotengine.org/qa/10872/how-to-display-translations-in-editor](url)

**Comment by GoDino** [comment]
I should have created separate tickets as this is about more than one thing, closing it
