### ISSUE TITLE
Vulkan: ReflectionProbe is flipped

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#38442]
**Godot version:**
master (2df844d5b311fc8d8b18040020df82c73d4365dd)
**OS/device including version:**
Arch 5.6.8-arch1-1
**Issue description:**
![Peek 03-05-2020 15-56](https://user-images.githubusercontent.com/1387165/80922919-a8fbce80-8d56-11ea-94b4-d632ebfdef59.gif)

**Steps to reproduce:**

**Minimal reproduction project:**
[ReflectionFliped.zip](https://github.com/godotengine/godot/files/4571395/ReflectionFliped.zip)

**Comment by clayjohn** [comment]
Ah yea, I ran into this while doing other work. It is actually just using the incorrect culling direction. I am not sure why. But a fix may be as simple as swapping culling direction during reflection probe passes.

**Comment by guilhermefelipecgs** [comment]
Yes, this is probably simple to fix.

**Comment by Calinou** [comment]
I can confirm this on `master` fc09d783f (Linux, NVIDIA 495.46).

To demonstrate this, I added 3 meshes with the cull modes Disabled, Front and Back (from left to right). There's a red OmniLight placed to light up the mesh with the cull mode set to Disabled. In the scene, it does not light up the mesh's walls, but it lights them up in the reflection, which hints that normals are flipped:

![2022-01-27_12 20 43](https://user-images.githubusercontent.com/180032/151350116-b00e939a-882c-42a6-a883-b544a156822f.png)

**Minimal reproduction project:** [test_reflection_probe_cull_mode.zip](https://github.com/godotengine/godot/files/7949993/test_reflection_probe_cull_mode.zip)

**Comment by clayjohn** [comment]
This has been fixed in master, I am not sure when, but it is no longer reproducible
