### ISSUE TITLE
xfce freezes when opening project

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#38452]
**Godot version:**
3.2.1-stable from official website

**OS/device including version:**
 Linux 5.6.8-arch1-1

**Issue description:**
This is so weird. I've never seen any bug like this. When opening an empty project, all windows would freeze. The whole display would flicker between two recent frames. I can still move my mouse, but only the mouse. I have to switch to another pty and restart the x11 server to fix it.

OpenGL ES 2.0 has no such issue.

**Steps to reproduce:**
- Create an empty project with OpenGL ES 3.0
- Open the project

**Minimal reproduction project:**
N/A

**More info:**
```
> glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 500 (APL 2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by Calinou** [comment]
Can you reproduce this on another device or Linux distribution (try using live media)? This may be due to a driver regression.

**Comment by buckle2000** [comment]
It works on another computer.

**Comment by buckle2000** [comment]
It seems like a mesa bug.
```
> dmesg | tail
[  308.277934] i915 0000:00:02.0: Resetting rcs0 for preemption time out
[  308.277956] i915 0000:00:02.0: godot[6871] context reset due to GPU hang
[  308.300381] i915 0000:00:02.0: GPU HANG: ecode 9:1:85d7fffb, in godot [6871]
```

**Comment by buckle2000** [comment]
I found it. https://gitlab.freedesktop.org/drm/intel/-/issues/1828
