### ISSUE TITLE
Dragging a Script from the *Script Dock* onto an export Script variable doesn't work

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#38456]
**Godot version:**
3.2.2 beta 1
**OS/device including version:**
Windows 10
**Issue description:**
Dragging a script from the **_script dock_** onto an exported Script variable doesn't work.
(However, dragging a script from the **_FileSystem dock_** works.)

![DragDropBugReason](https://user-images.githubusercontent.com/60025044/80967643-5107ab00-8ddc-11ea-8c67-d867b5c2d089.png)

**Steps to reproduce:**
Create an export script variable.
Try to drag a script from the _**script dock**_ and you'll get the "red circle backslash" symbol.
![DragFromScriptDock](https://user-images.githubusercontent.com/60025044/80968020-e5720d80-8ddc-11ea-9260-2fe666af07d8.png)

(Dragging from the **_FileSystem dock_** works as expected)
![DragFromFileSystem](https://user-images.githubusercontent.com/60025044/80967982-d8edb500-8ddc-11ea-9061-b69a3ac3494b.png)

**Minimal reproduction project:**
[ScriptDragDropExample - 2.zip](https://github.com/godotengine/godot/files/4574757/ScriptDragDropExample.-.2.zip)

**Comment by rileylyman** [comment]
The above PR should fix this!
