### ISSUE TITLE
GDPrettyPrint is an empty class

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3846]
I've found that GDPrettyPrint is a completely empty class. What was it meant to be, and should we implement it, or remove it?
- https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_pretty_print.cpp
- https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_pretty_print.h

**Comment by Hinsbart** [comment]
This class has been removed, so can be closed.
