### ISSUE TITLE
CenterContainer children do not scale to parent

### ISSUE THREAD

**Issue by CowKeyMan** [godotengine/godot#38460]
**Godot version:** 3.2

**OS/device including version:** Windows 10

**Issue description:** I have a CenterContainer and a TextureRect as a child to it. When I put both 'Fill' and 'Expand' to the CenterContainer, and mark the child to 'Expand' with 'Keep Aspect', the child ends up becoming a point on the screen. The reason I want this is because the image is actually too big for the screen. The way I fixed this (dirtily) was to replace the CenterContainer with a MarginContainer and set the TextureRect to 'Keep Aspect Centered'. I have attached images below as well as the project, with 2 scenes, one with the bug, called 'MainMenu-Bugged' and the other with the dirty fix. For more context, I was following this, but with a different aspect ratio: https://docs.godotengine.org/en/3.2/getting_started/step_by_step/ui_main_menu.html.

Disclaimer: I am still a beginner at Godot, hence it might be the case that I'm misunderstanding something.

**The way I want it:**
![Correct](https://user-images.githubusercontent.com/33454325/80989293-0a926a80-8e35-11ea-9b8c-884bbccfed75.PNG)

**What happens when I used center container instead:** 
![Bugged](https://user-images.githubusercontent.com/33454325/80989229-f2225000-8e34-11ea-94ce-34cb29777cef.PNG)

**The project:**
[ui_main_menu_design.zip](https://github.com/godotengine/godot/files/4575848/ui_main_menu_design.zip)

**Comment by mrcdk** [comment]
You need to set a `rect_min_size` in the TextureRect if not it won't know how much space it should take

**Comment by groud** [comment]
This is the expected behavior. 
You can either untick the "extend" checkbox in the inspector, which will compute a minimum size out of the texture, making it 1:1 texture, or you can keep it this way and set a custom minimum size.

**Comment by Shadowblitz16** [comment]
isn't the the definition of extend to take up as much room as it needs?
