### ISSUE TITLE
GLES 2 BATCHING - Camera border renders fixed to viewport in editor in certains circumstances (3.2.2. beta1)

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#38467]
**Godot version:**
3.2.2 beta 1

**OS/device including version:**
Win 7 and Win 10

**Issue description:**

Z-Index of a node can fix camera rectangle to editor viewport in some circumstances:

Without batch:
![CameraNoBug](https://user-images.githubusercontent.com/11712737/81011384-28bd9200-8e58-11ea-96e4-7e61fab98ed5.png)

With batch:
![CameraBug](https://user-images.githubusercontent.com/11712737/81011400-2f4c0980-8e58-11ea-84a1-6c02182b750f.png)

**Steps to reproduce:**
Its so specific. Better use demo project or see the images. The demo project have a very common configuration: Camera node inside a Position2D inside a KinematicBody that is a packed scene (the character), and have a node in the same tree that has a upper Z-index that the camera... see the image and the attached project.

**Minimal reproduction project:**
[CameraGles2BatchBug.zip](https://github.com/godotengine/godot/files/4577294/CameraGles2BatchBug.zip)

Related:
https://github.com/godotengine/godot/issues/38318
https://github.com/godotengine/godot/pull/37349
Ping:
@lawnjelly 
@clayjohn

**Comment by Ranoller** [comment]
Thinking about this bug and taking into account that it only happend if the camera does not have another node with the same Z-index below, it could be the typical error of a *for x to y* loop that lacks a *"+1" in the *"y"* or something like that (I don't know, it's to give an idea, render code is hard to me)

**Comment by lawnjelly** [comment]
This already appears fixed in 3.2 since the 3.2.2 beta 1. Not sure which bug this was, but it is working now. :smile:

**Comment by lawnjelly** [comment]
I'll close this as it appears to be working, we can reopen if it does reappear in any circumstances.

**Comment by Ranoller** [comment]
Yes, is fixed in Godot 3.2.2 beta2, thanks.
