### ISSUE TITLE
Label: Setting custom_colors/font_color breaks anti-aliasing

### ISSUE THREAD

**Issue by ErwinBr** [godotengine/godot#38464]
**Godot version:**
3.2.1 Stable

**OS/device including version:**
Mac OS Catalina 10.15.2

**Issue description:**
I have a label with a custom font. This is a Dynamic Font which has Filter enabled. The font is smooth in the editor. If I change the colour of the font in the editor (Custom Colors section), it remains smooth. When I perform the same action through code, the font loses its anti-aliasing causing harsh, pixelated edges.

Code: label.set("custom_colors/font_color", my_colour)

The same happens when I try the Modulate property of its CanvasItem class. And again, works fine in Editor, but not anymore during run-time. 
   
**Steps to reproduce:**
Create a label with a custom font based on Dynamic Font.
Change the colour in code: label.set("custom_colors/font_color", my_colour)

![godot-text](https://user-images.githubusercontent.com/46350573/81007490-95815e00-8e51-11ea-9656-eb4e703eb96e.png)

**Comment by Calinou** [comment]
This is probably because you set the font color to an *overbright* color. Color's values go from 0 to 1 to standard colors, not 0 to 255. (Use Color8 if you need to set colors with integers from 0 to 255.)

**Comment by ErwinBr** [comment]
> This is probably because you set the font color to an _overbright_ color. Color's values go from 0 to 1 to standard colors, not 0 to 255. (Use Color8 if you need to set colors with integers from 0 to 255.)

Thank you for your quick reply. I was indeed setting colour values in the 0 to 255 range, never thinking about checking if that's allowed. I will close the issue. Thanks again!

https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-color8
