### ISSUE TITLE
Improving the official Godot icon

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3848]
Our current official "square" icon, which is used e.g. on Steam and could be used by distro packagers, was contributed as part of the pe_bliss integration:
- https://github.com/godotengine/godot/blob/master/godot_icon.svg
- https://github.com/godotengine/godot/blob/master/godot_icon.png

I already expressed back then that I was not fond of the "app-like" capsule, and now I also find that the grey background does not look so great.

So I'm looking for feedback on how to improve it. Godot as an official visual identity so the Godot "logo" itself should not be modified (it should stay this nice little blue robot/ogre head), but the background could be removed/enhanced.

My proposal would be to just drop this background and just keep the Godot logo as official icon, with a transparency layer. Or if people like the capsule-shaped background, I'd go for a much whiter grey than the current one, which does not fit Godot's blue at all.

Note that this icon is meant to be used in very small resolutions (32x32 px for example), so contrast is very important.

**Comment by UgisBrekis** [comment]
I am working on total visuals upgrade proposal and that includes every element, icon is not an exception. There's a lot more work than I anticipated, but I'm planning to deliver alpha version of theme by the end of the next week.

**Comment by kubecz3k** [comment]
On my machine I'm using graphic made by @ndee85 to one of his tutorials. I think it looks very pro and I'm very happy with it! :) 
![godotingnome](https://cloud.githubusercontent.com/assets/6129594/13373332/bd594ec0-dd65-11e5-96f3-0e9ff643c2f0.png)

**Comment by rgrams** [comment]
Yeah, I agree with just getting rid of the grey capsule background. That grey is kind of the worst background to put it on, since it's so close in brightness to the blue. 

I think any extra stuff will just make it less clear at smaller sizes. I mean look at the github logo. Having a fancy "mascot" version with rendering and details like what Andreas did would be cool for some things though. Splash screens and whatnot.

**Comment by toger5** [comment]
I also posted this in issue: #2207 
It is a logo which is used for the DarkDot theme for the[ Godot Q&A](http://www.godotengine.org/qa/46/darkdot-dark-theme-for-godot-q%26a). made by  Arc Futahito.

![image](https://cloud.githubusercontent.com/assets/16718859/13376077/6431b494-ddb1-11e5-9d2c-37d329341111.png)

I like that it is so simple but still has the "Godot style".
Here is a preview how it can look when it is used as a small icon.
![godoticonwhite](https://cloud.githubusercontent.com/assets/16718859/13376127/c6ea9852-ddb2-11e5-94c5-eb459f4c23d1.png)![godoticondark](https://cloud.githubusercontent.com/assets/16718859/13376128/c70347c6-ddb2-11e5-87a6-8708124df42d.png)

**Comment by ndee85** [comment]
I agree with @akien-mga 
I wouldn't change the logo design in itself. It looks good to me! But the grey background is just ugly.
I also don't think that my gbot looks good as logo. There for the simplistic logo looks much better.

My recommendation would be. Just remove the grey background. I don't think we want a rebranding of the logo now.
thats my 2cent ^^

**Comment by punto-** [comment]
why no eyes?

**Comment by shackra** [comment]
No eyes is bad idea

**Comment by akien-mga** [comment]
So I'd propose one of those three:

- Based on the default icon.png when creating a new project (same background colour, "teeth" also using the background colour)
![spectacle ra6207](https://cloud.githubusercontent.com/assets/4701338/13379121/b72ef38e-de1d-11e5-8505-c82e228c9a0e.png) ![godot_icon64_3](https://cloud.githubusercontent.com/assets/4701338/13379147/6c83c2dc-de1e-11e5-9ac1-41583d28d6e8.png)

- Same one, but with white teeth:
![spectacle wd6207](https://cloud.githubusercontent.com/assets/4701338/13379128/e2b443a6-de1d-11e5-99a3-9eec497477d2.png) ![godot_icon64_2](https://cloud.githubusercontent.com/assets/4701338/13379148/77042b7a-de1e-11e5-98e8-ad2ea2b2c4c3.png)


- Official logo, no capsule:
![spectacle vy6207](https://cloud.githubusercontent.com/assets/4701338/13379129/f863c000-de1d-11e5-8d9b-b33e80bc889f.png) ![godot_icon64](https://cloud.githubusercontent.com/assets/4701338/13379150/7a423232-de1e-11e5-91ef-a0b2acf80d26.png)

**Comment by rolfpancake** [comment]
No capsule looks best in this case. If I look on my Android or Windows machine most programs uses non quadratic icons.
Apart from that the black background has a better contrast than grey so this would be good too.

**Comment by toger5** [comment]
I also prefer the none capsule one. what about increasing the contrast a little? I think the colors look too washed out. (this maybe is just a personal preference)
![image](https://cloud.githubusercontent.com/assets/16718859/13379715/ae6a9338-de2d-11e5-9644-787fdd69910b.png)

**Comment by ScotFlux** [comment]
I do agree with @ndee85 . Just use original Godot Logo with no grey color (changed to either pure black or pure white is ok). And please, don't make the teeth goes black. :+1:

**Comment by akien-mga** [comment]
Ok, let's go with original logo without background, it's also what I prefer (and what I'm using for my Mageia package actually ;)).

**Comment by ndee85** [comment]
one last question. What about making the teeth contour transparent? That way it would adapt to any background color and you won't have the edge of the theeth on both sides.

**Comment by Calinou** [comment]
> one last question. What about making the teeth contour transparent? That way it would adapt to any background color and you won't have the edge of the theeth on both sides.

This is problematic if you have a blue background, the teeth will just "disappear" then…

**Comment by DaikoGit** [comment]
> I also posted this in issue: #2207 It is a logo which is used for the DarkDot theme for the[ Godot Q&A](http://www.godotengine.org/qa/46/darkdot-dark-theme-for-godot-q%26a). made by Arc Futahito.
> 
> ![image](https://cloud.githubusercontent.com/assets/16718859/13376077/6431b494-ddb1-11e5-9d2c-37d329341111.png)
> 
> I like that it is so simple but still has the "Godot style". Here is a preview how it can look when it is used as a small icon. ![godoticonwhite](https://cloud.githubusercontent.com/assets/16718859/13376127/c6ea9852-ddb2-11e5-94c5-eb459f4c23d1.png)![godoticondark](https://cloud.githubusercontent.com/assets/16718859/13376128/c70347c6-ddb2-11e5-87a6-8708124df42d.png)

I really like that logo.
When I started gamedev I didn't use Godot, because on my first impression I thought I won't be able to make professional game with it (because of the icon look). 
I guess I'll compile Godot from source and use this icon.
