### ISSUE TITLE
GLES2 batching - scroll bar in code editor disappears when scripts panel is collapsed

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#38499]
**Godot version:**
Godot Engine v3.2.2.beta.custom_build.a83593173

**OS/device including version:**
Windows 10 x64 GT 720

**Issue description:**
Scroll bar of code editor disappear when
- use GLES2, and
- GLES2 batching in editor is enabled, and
- scripts panel of code editor is hidden

Scroll bar of code editor does not disappear when
- GLES2 batching in editor is disabled

**Steps to reproduce:**
insert enough code into code editor window, for scroll bar to appear
in project settings, enable gles2 batching in editor
toggle scripts panel to see how scroll bar disappear when scripts panel is collapsed

**Minimal reproduction project:**
just insert enough code into code editor window in any project to observe this

![batching1](https://user-images.githubusercontent.com/3224132/81148247-35d3a180-8f7c-11ea-962e-902dc752f916.jpg)

![batching2](https://user-images.githubusercontent.com/3224132/81148756-230d9c80-8f7d-11ea-8e13-1bdc7b957290.jpg)

related to https://github.com/godotengine/godot/issues/38004

**Comment by lawnjelly** [comment]
It looks like the same bug as #38458 which I'm currently working on.

Until it is fixed, feel free to just set `rendering/gles2/batching/item_reordering_lookahead` to 0.

**Comment by akien-mga** [comment]
Fixed by #38503.

**Comment by avril-gh** [comment]
tested on Godot Engine v3.2.2.beta.custom_build.b1d41f69e
can confirm, works ok now.
Thanks!!
