### ISSUE TITLE
iOS Safari refuse IndexedDB access in iframes

### ISSUE THREAD

**Issue by ChronoDK** [godotengine/godot#38498]
**Godot version:**
3.2

**OS/device including version:**
iOS 13

**Issue description:**
You cannot load a game from another domain through an iframe. I believe this is because Godot initializes IndexedDB (even when not used), and Safari does not allow indexedDB in an iframe. 

**Minimal reproduction project:**
Create html file and try opening this project from your own domain - happens with any export though, so very easy to reproduce:
<iframe src="http://moogle.dk/html5" width="640" height="640"></iframe>

I would suggest switching to localStorage or an option in Project Settings to not initialize IndexedDB.

**Comment by ChronoDK** [comment]
Defold users are having the same problem btw:
https://forum.defold.com/t/html5-save-user-progress-inside-an-iframe/64073

**Comment by Calinou** [comment]
Related to #34102.

**Comment by akien-mga** [comment]
@Faless Would your recent fixes in #39538 solve that?

**Comment by Faless** [comment]
Yes, this should be fixed in #39538, but I can't test iOS.

**Comment by akien-mga** [comment]
@ChronoDK This should be testable in 3.2.2 RC 2 in a day or two (or any later build).

**Comment by ChronoDK** [comment]
Very cool - I'll test as soon as possible!

**Comment by ChronoDK** [comment]
I can confirm this is now fixed in 3.2.2 RC2!
