### ISSUE TITLE
Fix to a problem! Removing scenes in a C# project causes bug.

### ISSUE THREAD

**Issue by Marre246810** [godotengine/godot#38496]
**How to create the bug:**
Go into any C# project of godot and make a 2d scene. Create a script inside the 2d scene and now remove the scene by going into the project file location and removing it outside of godot, like such:
![image](https://user-images.githubusercontent.com/36279366/81115842-a8189780-8f24-11ea-8767-695fcb551a7a.png)
Now try creating another scene. Make a script inside the scene and try running the script. It will likley not work.

**What error it causes:**
Removing a scene in a C# project may cause an error where it dosen't let you compile. It will give you an error as such:
![image](https://user-images.githubusercontent.com/36279366/81115566-34768a80-8f24-11ea-8ffb-d24928e502ff.png)
This is caused because the scene that you removed is still in the compiling list.

**How to fix it:**
You go to the .csproj file inside your project file. Go to the bottom and you will find this list:
![image](https://user-images.githubusercontent.com/36279366/81116098-15c4c380-8f25-11ea-9146-cdc091e685ea.png)
I had removed the KinematicBody2d and the PlayerStats2 but it still was in the compiling list. Just remove the scene you don't have anymore. 
![image](https://user-images.githubusercontent.com/36279366/81116262-57ee0500-8f25-11ea-9ed3-fc6ffba05488.png)
That's better!

**Comment by groud** [comment]
There nothing we can do about it, we cannot control outside of Godot what you do with your files. So the error is expected.

**Comment by Marre246810** [comment]
Sorry! I did further testing and it actually happens inside the godot engine too! When you go into remove the node from inside the godot editor the same thing happens!

**Comment by groud** [comment]
Ah, in that case this issue is a duplicate of #35252. You can add a comment there about the fact the problem also happens with deleted files.
