### ISSUE TITLE
print() is not working as expected for blank string "" in the editor Output panel

### ISSUE THREAD

**Issue by pentazoe** [godotengine/godot#38490]
**Godot version:** 3.2.1

**OS/device including version:** Win 10

**Issue description:** print() is not working as expected for blank and new line character

**Steps to reproduce:** 
Create a New Godot Project and paste below code 

Code: 
```
func _ready():
    print("print blank line:")
    print("")
    print("--------")
    print("print new line character:")
    print("\n")
    print("print 2 new lines character:")
    print("\n\n")
    print("--------")
```
Output:
```
print blank line:
--------
print new line character:


print 2 new lines character:



--------
```

Bugs:
blank doesn't output newline -> expected is it should print a blank line
\n gives 2 new lines -> expected is it should print a single New Line
\n\n gives 3 new lines -> expected is it should print a 2 New Lines

**Minimal reproduction project:** New Godot Project
[Test.zip](https://github.com/godotengine/godot/files/4582002/Test.zip)

**Comment by KoBeWi** [comment]
\n and \n\n are expected, `print` always adds a newline. It works like e.g. `println` in Java. Although docs seem to not mention this.

As for blank line, this might be intended for some reason.

**Comment by pentazoe** [comment]
In that case there is 1 bug when you try to print blank
In java blank [System.out.println("");] gives a newline
whereas in godot [printl("")] doesn't output a newline

![Capture](https://user-images.githubusercontent.com/32230892/81141642-ed6fb000-8f8a-11ea-8f07-8668711116f9.PNG)

**Comment by Zireael07** [comment]
GDScript is not Java, therefore the fact that it differs from it is not a bug.

**Comment by Calinou** [comment]
I think it makes sense for `print("")` to print a blank line. It's expected behavior in all other languages I know of.

This seems to already apply to console output, but it doesn't apply to the editor's Output log.

```gdscript
extends SceneTree

func _init():
	print("")
	print("")
	print("hi")
	print("")
	print("hi2")
```

```text
❯ godot -s t.gd 
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Haswell Mobile 
 


hi

hi2
```
