### ISSUE TITLE
Extraordinary number of drawcalls with OmniLight, shadow and Gridmap

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3849]
**Operating system or device:**
Ubuntu linux 15.10 64bit, Godot 2.0 stable

**Issue description** (what happened, and what was expected):
There is something wrong with gridmap and shadows. Basically if I have a large gridmap and I put very small omni light on the scene (with radius of 1.5 tile size) I have normal nmb of draw calls (for not baked gridmap it's amount of visible tiles). 
When I turn on the shadow property on the light I will get amount of drawcalls similar to overall number of tiles (instead of 4, lets say 300). 

**Steps to reproduce:**
Short way:
1. Download sample project.
2. Find OmniLight inside Camera node
3. Run the project with shadow ON, observe nmb of draw calls 
4. Run the project with shadow OFF, observe nmb of draw calls 
5. (optional) You can play with live editing and moving camera around.

Manual way:
1. Prepare gridmap setup (mesh library + big gridmap lvl)
2. Add camera and omni light (the best setup would be ideal topdown so you could exactly see light boundaries and what's rendered on the screen)
3. Note normal number of draw calls.
4. Turn on shadow on Omni light
5. Observe extraordinary number of draw calls.

**Link to minimal example project** 
Video that ilustrates the bug: https://www.youtube.com/watch?v=1YANlODPa54&feature=youtu.be
Sample project: [Grid_and_Shadows Draw_cal_ Issue.zip](https://github.com/godotengine/godot/files/149351/Grid_and_Shadows.Draw_cal_.Issue.zip)

**Comment by kubecz3k** [comment]
Probably related issue: https://github.com/godotengine/godot/issues/559

**Comment by volzhs** [comment]
I faced same issue recently. I should wait for 3.0, right? :(

**Comment by reduz** [comment]
Unfortunately yes, deferred and instancing will speed this up enormously

**Comment by volzhs** [comment]
First of all, English is my mother language and I'm afraid that I could not represent what I really want to say.
@reduz Why I said that waiting for 3.0 is that you mentioned you will rewrite 3D rendering part in Godot 3.0.
But, this seems to be a bug.
Can I expect that rewritten renderer for Godot 3.0 will fix this even with OpenGL ES 2.0?

**Comment by vnen** [comment]
AFAIK the whole rendering engine will be remade. So, many bugs like this will be fixed even for the GLES 2.0 backend.

**Comment by reduz** [comment]
this is obsolete, renderer is new and does everything in a single draw pass
