### ISSUE TITLE
KinematicBody2Ds don't respect the 'trigger' property

### ISSUE THREAD

**Issue by bertiebaggio** [godotengine/godot#385]
The [2D physics tutorial triggers section](https://github.com/okamstudio/godot/wiki/tutorial_physics_2d#triggers) suggests that by setting the *'trigger'* property on a CollisionShape2D, the KinematicBody will ignore collisions but still trigger **body_enter** etc events.

However, even with the *'trigger'* property checked on two KinematicBody, they still collide.

(This may be superseded by for one of the bodies deselecting the _'collide_with'_ properties in the editor, or in-code via `set_collide_with_*(false)`; but there may be circumstances where this is not desirable)

**Comment by Ijatsu** [comment]
I experience the same problem, my kinematic body still collides rigid-bodies that are "triggers" while other rigidbodies don't collide but fire the collide event "on enter" ect...
Is this normal? Will it be fixed?

**Comment by okamstudio** [comment]
sounds like a bug, and yes it needs to be fixed

On Wed, Mar 18, 2015 at 8:23 PM, Ijatsu <notifications@github.com> wrote:

> I experience the same problem, my kinematic body still collides
> rigid-bodies that are "triggers" while other rigidbodies don't collide but
> fire the collide event "on enter" ect...
> Is this normal? Will it be fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/385#issuecomment-83221970>.
>



-- 

*OkamStudio*

**Comment by Ijatsu** [comment]
Do you need more informations? Do you want me to provide scenes and scripts that reproduce this?
I am using the official latest release 1.0 version from december 15 2014

**Comment by akien-mga** [comment]
Are you still able to reproduce this issue? If so, an minimal example project would indeed be useful.

**Comment by akien-mga** [comment]
Ping :)

**Comment by mohaalak** [comment]
I test it on 2.0.1 this issue has been resolved.

**Comment by akien-mga** [comment]
Thanks, closing.
