### ISSUE TITLE
Gridmap don't bake it's geometry even if 'bake' is checked. 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3850]
**Operating system or device:**
Ubuntu linux 15.10 64bit, Godot 2.0 stable

**Issue description** (what happened, and what was expected):
Gridmap is not baking it's geometry automatically even if Octant Size is bigger than 1 and "Bake" is checked. This results with extraordinary number of draw calls (like hundreds when only a couple of tiles is visible <- depending on what octant size is).
_**Note that it's easy to workaround this, just run `bake_geometry();` on GridMap in ready**_

**Steps to reproduce:**
1. Download sample project
2. Run it and observe a lot of draw calls (a lot more then number of visible tiles).
3. Open Main.gd script and uncomment manual baking in ready.
4. Run the project and observe small amount of draw calls
5. Also please take a look at sample movie and pay attention to how number of  draw calls is drastically changing when we play with octant size without baking geometry manually (despite the fact that there are always only 4 visible tiles on the scene).

**Link to minimal example project** (optional but very welcome):
Video that illustrates the problem: https://www.youtube.com/watch?v=ryM_0ObAQsM&feature=youtu.be
Sample project: [GridMapBakeGeometryProblem.zip](https://github.com/godotengine/godot/files/149354/GridMapBakeGeometryProblem.zip)

**Comment by kubecz3k** [comment]
Added additional info that it's working fine when running `bake_geometry` manually <- since this bug was looking more serious than it really is.

**Comment by reduz** [comment]
obsolete, new gridmap bakes geometry
