### ISSUE TITLE
.gen.h files are absent!

### ISSUE THREAD

**Issue by Voltini** [godotengine/godot#38502]
**Godot version: Latest**

**OS/device including version: Windows10**

**Issue description: Although the files are called in the source code they're not found in the documentation**

**Comment by pycbouh** [comment]
Files with `.gen` in their name imply that they are generated. If you have errors building from source that mention such files, make sure you have a clean copy of the repository, as sometimes such files can be left from previous build and pollute the next one. This is especially true, if you’ve changes a branch or a major change happened in the current branch.

To clean the repo run `git clean -fX`

**Comment by Calinou** [comment]
Closing, as this is very likely an issue with build cache as mentioned by @pycbouh.
