### ISSUE TITLE
Creature Plugin Export Failure

### ISSUE THREAD

**Issue by kestrelm** [godotengine/godot#38504]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
Hello, when trying to export out a scene with the Creature plugin ( https://github.com/kestrelm/Creature_Godot/tree/master/creaturegodot3 ), we get an error saying "Unknown class: 'CreatureGodot'" 
This plugin and code works as per normal in the editor, but fails on export. What should we do to resolve this issue?

**Steps to reproduce:**
Get the creature plugin and load one of the scenes here: https://github.com/kestrelm/Creature_Godot/tree/master/creaturegodot3/Godot3Demo

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Since this is a C++ module, you need to recompile all the export templates you plan to use as well.

**Comment by MelimeliDev** [comment]
Hello!

I'm using Godot 3.2.1 Stable.

This is the error I got when exporting to HTML5: 
`**SCRIPT ERROR**: Parse Error: Unknown class: "CreatureGodot" index.js:7:35827 At: res://morphTest.gdc:1:GDScript::load_byte_code() - Parse Error: Unknown class: "CreatureGodot" index.js:7:35827 **ERROR**: Method failed. Returning: ERR_PARSE_ERROR index.js:7:35827 At: modules/gdscript/gdscript.cpp:778:load_byte_code() - Method failed. Returning: ERR_PARSE_ERROR index.js:7:35827 **ERROR**: Cannot load byte code from file 'res://morphTest.gdc'. index.js:7:35827 At: modules/gdscript/gdscript.cpp:2240:load() - Condition "err != OK" is true. Returned: RES() index.js:7:35827 **ERROR**: Failed loading resource: res://morphTest.gdc. index.js:7:35827 At: core/io/resource_loader.cpp:278:_load() - Condition "found" is true. Returned: RES() index.js:7:35827 **SCRIPT ERROR**: Parse Error: Unknown class: "CreatureGodot" index.js:7:35827 At: res://morphTest.gdc:1:GDScript::load_byte_code() - Parse Error: Unknown class: "CreatureGodot" index.js:7:35827 **ERROR**: Method failed. Returning: ERR_PARSE_ERROR index.js:7:35827 At: modules/gdscript/gdscript.cpp:778:load_byte_code() - Method failed. Returning: ERR_PARSE_ERROR index.js:7:35827 **ERROR**: Cannot load byte code from file 'res://morphTest.gdc'. index.js:7:35827`


This is the error I got when exporting to desktop .exe:
http://prntscr.com/sa300u

Thanks for the help :+1:

**Comment by akien-mga** [comment]
@MelimeliDev Same question as @Calinou asked: did you compile 3.2.1-stable export templates with the Creature plugin? If not, there's no Creature code in the Javascript template and then it won't work indeed.

**Comment by kestrelm** [comment]
@akien-mga Thanks for the tips! @MelimeliDev Can you please try what they suggested. Thanks.

**Comment by kestrelm** [comment]
User compiled the templates and it worked. Thank you.
