### ISSUE TITLE
Normal and specular texture frames are undocumented in AnimatedSprite

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot#38509]
**Godot version:**
v3.2.1 Stable Official

**OS/device including version:**
Any OS

**Issue description:**
The availability of specular and normal textures is undocumented in the AnimatedSprite documentation. Basically you can add a spritesheet containing your specular and normal data and Godot will have animations with these effects applied.

**Steps to reproduce:**

Simply add an animation named "xxx" and an animation named "xxx_normal", the normal animation will automatically apply itself as the normal map of the "xxx" animation!

![frames](https://user-images.githubusercontent.com/42484461/81177828-94fadb80-8fa7-11ea-9905-338919297e42.png)
![normal_frames](https://user-images.githubusercontent.com/42484461/81177831-95937200-8fa7-11ea-9270-7b0338b75324.PNG)

Could this be documented or expanded upon? Because I will utilize this feature extensively.

**Comment by byfron** [comment]
This is indeed an issue. I also noticed that if I create an AnimatedSprite and I assign a spritesheet (with a normal map) to the frames attribute in the editor it seems to work, but if instead I load from gdscript the spritesheet resource, the normal map does not seem to get applied to the AnimatedSprite while running the game. I'll try to reproduce and report a separate bug/issue.

**Comment by byfron** [comment]
Indeed it seems to be the case: 
![in-game](https://user-images.githubusercontent.com/16748261/87189853-b3f05380-c2f1-11ea-8e03-b7ddbd3b48c9.png)
![in-editor](https://user-images.githubusercontent.com/16748261/87189857-b652ad80-c2f1-11ea-98f7-4e4d419e11c6.png)

**Comment by PixsaOJ** [comment]
I was just searching for this, please document it, really important for users. We need to make Godot more popular, so it has to have normal maps included in AnimatedSprites.

**Comment by byfron** [comment]
At the moment I feel that the problem besides documentation is that normal maps don't even work in-game with AnimatedSprite2D (I'm using a custom build of v3.2). Maybe @2shady4u could confirm this.

**Comment by PixsaOJ** [comment]
I can confirm, its not working. @byfron

**Comment by valpet** [comment]
After confirming that normal maps are not working as intended both after reloading project and not working at all in-game, was this forgotten?

**Comment by Calinou** [comment]
@valpet Please continue the discussion in https://github.com/godotengine/godot/issues/43435.
