### ISSUE TITLE
Can't change axis of capsule collider

### ISSUE THREAD

**Issue by medakk** [godotengine/godot#38514]
**Godot version:** 3.2.1

**OS/device including version:** Ubuntu 18.04

**Issue description:** If I use the control handles to modify the capsule so that it is wider than than it is tall, it turns invisible and the console says `Invalid polygon data, triangulation failed`.

This is fine:
![image](https://user-images.githubusercontent.com/10536745/81211511-b7cdc580-8f90-11ea-9d12-1d1edf0daff9.png)

And if I lower the handle on the top too much:
![image](https://user-images.githubusercontent.com/10536745/81211528-be5c3d00-8f90-11ea-9b5c-f815ca9ba44b.png)

This case probably doesn't matter, but if both the handles coincide I get:
![image](https://user-images.githubusercontent.com/10536745/81211602-d92eb180-8f90-11ea-80f0-05662edcee48.png)

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
You are not supposed to change axis of the capsule; this can only be done by rotating the CollisionShape2D node.

The editor should probably disallow moving handles to wrong position.

**Comment by MCrafterzz** [comment]
This can be fixed by preventing the xScale from being higher than the yScale. Maybe the best way is just to clamp it when generating the shape?
