### ISSUE TITLE
Blending Animations together in AnimationPlayer (Editor)

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#38513]
I see no way of blending two animations together inside the AnimationPlayer (Editor).
Why is is not possible?

**Comment by pouleyKetchoupp** [comment]
You can use an `AnimationTree` node to blend animations:
https://docs.godotengine.org/en/stable/tutorials/animation/animation_tree.html

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
