### ISSUE TITLE
Godot can't import projects from a ZIP archive if `project.godot` isn't in a subfolder

### ISSUE THREAD

**Issue by Ev1lbl0w** [godotengine/godot#38521]
**Godot version:** 3.2.1 *(and latest master)*

**OS/device including version:** Arch Linux *(rolling release, kernel 5.6.8)*

**Issue description:** Godot stopped being able to import projects with a certain structure, as is the case of the [FPS tutorial](https://docs.godotengine.org/en/stable/tutorials/3d/fps_tutorial/part_one.html):

If the compressed structure looks like this *(files not gathered in a single folder)*:
![image](https://user-images.githubusercontent.com/6501975/81238196-53931c00-8ff9-11ea-80b6-3f1f6748d4a5.png)

When importing, Godot will fail silently and show a new invalid entry:
![image](https://user-images.githubusercontent.com/6501975/81238322-ab318780-8ff9-11ea-9df2-3a53502273ca.png)

And looking at the folder structure that was imported, it seems only the contents of the `assets` folder we're copied.

If, however, the compressed structure is changed so everything is inside a folder, like this:
![image](https://user-images.githubusercontent.com/6501975/81238386-d5834500-8ff9-11ea-887c-7e659e808099.png)

Then Godot imports and opens it without issue.

I remember following this tutorial back in version 3.1.1 without this problem, so this is likely a regression.

**Steps to reproduce:**
- Try importing the sample project [FPS tutorial](https://docs.godotengine.org/en/stable/tutorials/3d/fps_tutorial/part_one.html)

**Minimal reproduction project:** [Godot_FPS_Starter](https://docs.godotengine.org/en/stable/_downloads/06eb944abda1cabe2ed92be2d4f42744/Godot_FPS_Starter.zip)

**Comment by mbrlabs** [comment]
I don't know why, but apparently all files must be contained in a subfolder, otherwise the importer skips them:
https://github.com/godotengine/godot/blob/38250ef54e439d69240f4b514f3bacb05b5d8c12/editor/project_manager.cpp#L516-L526

**Comment by Calinou** [comment]
@mbrlabs Interesting, I thought we had implemented both ways to read a ZIP archive (with and without a subfolder).

**Comment by mbrlabs** [comment]
It seems this has been implemented about 4 years ago and hasn't been changed since. I deleted the skip logic and the project imports fine (it just won't run because it hasn't been updated in a while i guess)

**Comment by Ev1lbl0w** [comment]
So, I just remembered about this issue, and since it hasn't been tackled yet, I've decided to take a shot.
