### ISSUE TITLE
Cannot compile mono version to Windows from MacOS

### ISSUE THREAD

**Issue by rafaelgdp** [godotengine/godot#38523]
**Godot version:** 4.0 master commit 804ee245a74157d82ce5f053e11f5f8e3479f30e

**OS/device including version:** MacOS Catalina. MBP 2018.

**Issue description:** I cannot cross-compile a Windows Editor build from MacOS. I can actaully compile when I set the platform to osx, but not to windows. I tried using the mono_prefix flag to point to the mono installation, but no luck so far. Am I doing something wrong or is this an actual bug in the build system?

**Steps to reproduce:** Use this script to compile:

```
scons p=windows tools=yes module_mono_enabled=yes mono_glue=no -j 12 mono_prefix=/Library/Frameworks/Mono.framework
./bin/godot.windows.tools.64.mono --generate-mono-glue ./modules/mono/glue -j 12
scons p=windows tools=yes target=release_debug module_mono_enabled=yes -j 12 mono_prefix=/Library/Frameworks/Mono.framework
```

**Minimal reproduction project:** NA

<img width="950" alt="Screen Shot 2020-05-06 at 21 48 52" src="https://user-images.githubusercontent.com/9672536/81242794-6f3ff780-8fe4-11ea-96bc-567bfad99c08.png">

Some additional info on my mono path:
<img width="1163" alt="Screen Shot 2020-05-06 at 22 02 41" src="https://user-images.githubusercontent.com/9672536/81244310-736e1400-8fe8-11ea-892e-774e19580572.png">

**Comment by akien-mga** [comment]
You have to cross compile Mono for Windows first, and use that. You can't build a Windows binary using the macOS Mono binaries.

**Comment by rafaelgdp** [comment]
OK. So, I'll close this issue as it seems not being able to compile was my fault.
