### ISSUE TITLE
Script Editor Minimap off by one line

### ISSUE THREAD

**Issue by DrAlta** [godotengine/godot#38532]
**Godot version:**
v3.2.1.stable.offical
**OS/device including version:**
win 10 home 10.0.18362 build 18362 
HP laptop 15-da0xxx
**Issue description:**
The highlighted part of the minimap to show the currently shown part of the script starts one line about the first line shown and ends about the last line shown
**Steps to reproduce:**
open script editor
**Minimal reproduction project:**

**Comment by Calinou** [comment]
I can confirm this on 3.2.1 stable (tested by scrolling `Game.gd` in the Platformer 2D demo from github.com/godotengine/godot-demo-projects).

This bug can be reproduced regardless of the Smooth Scrolling editor setting, but it may not occur as often when disabled. Still, you can reproduce it by dragging the minimap so the first line of code isn't shown. When you do this, the first line will still be highlighted on the minimap.

**Comment by ice-blaze** [comment]
@Calinou  @Paulb23 Hi, it's my first time collaborating on godot. So if you have any comments on the PR a made, I'm happy to improve the work.
