### ISSUE TITLE
Exported Release application shows Godot Engine Editor (alpha)

### ISSUE THREAD

**Issue by daafu** [godotengine/godot#3853]
**Operating system or device:**
Operating system or device:
Windows 10 host, Windows Desktop export with all variants 32/64/Debug/Release
Export template: Godot_v2.0_stable_20160223_export_templates.tpz

**Issue description** (what happened, and what was expected):
The exported application name in Windows 10 Task Manager shows up as:
Godot Enginer Editor (alpha), and contains the default Godot icon. The actual application name shows up as a subprocess and contains the actual application icon.

Expected that there would not be a parent process or that it would be named after the project name. Most importantly that it wouldn't say "Editor (alpha)"

This may be related to #3686, however that issue specifically calls out the name of the console window, which doesn't apply to release builds like this issue does. Still the source of the "alpha" name is likely the same.

**Steps to reproduce:**
Export project and run it on Windows 10 platform, look for the process in Task Manager

**Comment by akien-mga** [comment]
This is very likely the same bug as #3686.
