### ISSUE TITLE
ERROR OS_Windows::initialize WinTab context creation failed.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#38533]
**Godot version:**
bab595393c53e88b394aef3e3e010bd5c0cd2b11

**OS/device including version:**
Win10 64-bit GLES2

**Issue description:**

Have been getting this error when running Godot: 
![image](https://user-images.githubusercontent.com/13004169/81293695-6566d480-9076-11ea-95df-ead12cb81b55.png)

@bruvzg Introduced here, not sure what the error means.  (Also a typo in "failed") https://github.com/godotengine/godot/pull/38484

Trace
```
godot.windows.tools.64.exe!OS_Windows::initialize(const OS::VideoMode & p_desired, int p_video_driver, int p_audio_driver) Line 1511	C++
godot.windows.tools.64.exe!Main::setup2(unsigned __int64 p_main_tid_override) Line 1223	C++
godot.windows.tools.64.exe!Main::setup(const char * execpath, int argc, char * * argv, bool p_second_phase) Line 1168	C++
godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 150	C++
godot.windows.tools.64.exe!_main() Line 184	C++
godot.windows.tools.64.exe!main(int _argc, char * * _argv) Line 196	C++
```

**Steps to reproduce:**
Open Godot on Windows.

**Comment by bruvzg** [comment]
> Trace...

Is it crashing or just printing the error?

**Comment by avencherus** [comment]
No crashing, at least in the debug builds.  I'll build a release template and see what happens there.

**Comment by avencherus** [comment]
No crashing in release builds either.  So it's just a message when you don't have a tablet connected?

**Comment by bruvzg** [comment]
> So it's just a message when you don't have a tablet connected?

Yes, when WinTab driver is installed and unable to open tablet.
