### ISSUE TITLE
exporting to HTML5 from console throws error "Invalid export preset name: HTML5"

### ISSUE THREAD

**Issue by michasng** [godotengine/godot#38531]
**Godot version:**
Godot_v3.2.1-stable_linux_headless.64

**OS/device including version:**
Linux x64

**Issue description:**
I tried to export a project like this:
`godot --export "HTML5" "/var/www/virtual/michasng/"`

and this is my export_presets.cfg:
```
[preset.0]

name="HTML5"
platform="HTML5"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path=".build/index.html"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.0.options]

vram_texture_compression/for_desktop=true
vram_texture_compression/for_mobile=false
html/custom_html_shell=""
html/head_include=""
custom_template/release=""
custom_template/debug=""
```
Working directory is the root of my project.

I got this Error:
```
Godot Engine v3.2.1.stable.official - https://godotengine.org

ERROR: _fs_changed: Invalid export preset name: HTML5.
   At: editor/editor_node.cpp:634.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```

**Steps to reproduce:**
Create a project with a preset called "HTML5" and try to export it from the console.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Does it work if you use `godot --export "HTML5" "/var/www/virtual/michasng/index.html"`?

**Comment by davidwesst** [comment]
I was getting a similar error on my system, although I am using a significantly different version. I'll go through the details along with my workaround to get it working.

**Godot Version**
3.2.1.stable.mono.official

**OS/device including version**
Windows 10 Pro 1909

**Issue Description**
Same as above, except I tried the suggested workaround as well with no luck.

**Potential Issue Cause**
I was running Godot from within the Godot install directory, such that I would run the following from the PWSH prompt:

```
~\tools\Godot\3.2.1
> .\Godot_v3.2.1-stable_mono_win64.exe --path "D:\Users\david\projects\ld46\src\project.godot" --export "Web" "\build\web\index.html" --quit
```

_Result_
Mono: Logfile is: C:\Users\david\AppData\Roaming/Godot/mono/mono_logs/2020_05_15 00.54.40 (9204).txt
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:544
ERROR: poll: C:\Users/david/AppData/Roaming/Godot/editor_settings-3.tres:3 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/resource_format_text.cpp:565
ERROR: Failed to load resource 'C:\Users/david/AppData/Roaming/Godot/editor_settings-3.tres'.
   At: core/io/resource_loader.cpp:208
ERROR: Failed loading resource: C:\Users/david/AppData/Roaming/Godot/editor_settings-3.tres.
   At: core/io/resource_loader.cpp:278
WARNING: create: Could not open config file.
     At: editor/editor_settings.cpp:934
WARNING: _get: EditorSettings::_get - Property not found: mono/editor/editor_path_optional
     At: editor/editor_settings.cpp:151
ERROR: _fs_changed: Invalid export preset name: Web.
   At: editor/editor_node.cpp:634
debugger-agent: Unable to listen on 1920

[Log File](https://github.com/godotengine/godot/files/4632501/2020_05_15.00.46.06.16736.txt)

I also noticed the following in my cwd (which was the Godot.exe directory)
```
~\tools\Godot\3.2.1
> ls


    Directory: C:\Users\david\tools\Godot\3.2.1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2020-05-15 12:54 AM                .import
d----          2020-05-15 12:54 AM                .mono
d----          2020-04-16 10:47 AM                GodotSharp
-a---          2020-04-16 10:47 AM       69696752 Godot_v3.2.1-stable_mono_win64.exe
-a---          2020-05-15 12:54 AM            320 project.godot
```

Note that a number of new directories and an empty project.godot file have been brought in.

**Workaround / Solution**
A couple of things:

1) Set your `cwd` to be your project directory (i.e. where project.godot exists)
2) Ensure the output directory (i.e. build/web/) exists already. It appears that Godot cannot create directories for web exports (although it works fine for Windows Desktop)

---

Not sure if that helps, but hopefully it provides some extra context and help you get on your way with your build.

**Comment by michasng** [comment]
> Does it work if you use `godot --export "HTML5" "/var/www/virtual/michasng/index.html"`?
No, sadly it doesn't.

I also tried the proposed workaround, but without success. I think that one's a different issue.

> Set your cwd to be your project directory (i.e. where project.godot exists)
Did that, my project.godot is in the cwd.

> Ensure the output directory (i.e. build/web/) exists already. It appears that Godot cannot create directories for web exports (although it works fine for Windows Desktop)
The directory exists. I also tried using "./build/index.html" and "index.html" to be sure.

**Comment by evan-boissonnot** [comment]
I got the same problem too.
In my pc it works fine, but when I use godot docker image in gitlab ci, I got the same error

**Comment by davidwesst** [comment]
I didn't realize I hadn't added to this (got lost in my notifications). I did find a work around that seems to apply to specifically the web exports.

Unlike Windows and Linux exports, I needed to have the CI server create the export path folders BEFORE running the exports. For example:

`mkdir -p path/to/web/export`

then

`godot --export "HTML5" path/to/web/export/index.html`

It seems to work consistently with my docker image and GitHub Action setup, and has continued to work into 3.2.2.

--

It should be noted that I only have to do that for the web exports NOT the Windows or Linux ones. I didn't try the Android or iOS builds as my games don't support those platforms.

**Comment by Calinou** [comment]
cc @Faless

**Comment by ksjogo** [comment]
I was able to fix my problem with removing the the export_path from the config file and only having it via CLI argument.

**Comment by Faless** [comment]
I'm unable to reproduce with latest 3.2.3.
This thread is a bit messy, but I see no misbehaviour tied to `HTML5`.
Take this simple project [proj_export.zip](https://github.com/godotengine/godot/files/5548847/proj_export.zip):
Assuming you have `godot` as an executable, and you have export templates properly installed:
- `godot --export "HTML5" "/path/to/test.html" --path /path/to/projects` exports correctly.
  The directory is not recursively created, but that's not the case in Linux either, and in my opinion that is correct.
- `godot --export "HTML5" "/path/to/test.html"` exports correctly if run inside the project folder.

Any export command without the path to the destination binary fails with: `Command line includes export parameter option, but no destination path was given.` even if the preset has an `export_path`. Again, this is consistent across platforms, and is the only "weird" behaviour I've noticed.

**Comment by ChildLearningClub** [comment]
> Does it work if you use `godot --export "HTML5" "/var/www/virtual/michasng/index.html"`?

Maybe for others this is clear, but I kept trying to export my "HTML5" builds with the .pck or .zip [file extension](https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html#exporting-from-the-command-line), which would build just fine, but could not actually deploy them. My command was `godot --path /home/ubuntu/godot-project --export "HTML5" index.pck`. This actually creates the index.html and actually matches the exact number and names of files of an export that works. Anyway if it was not for @Calinou comment and replacing my command with the .html extension I would have still been trying to figure this out, thank you.
