### ISSUE TITLE
Macbook Air 13" 2015 constantly freezes when using Godot Engine

### ISSUE THREAD

**Issue by Akylzhan** [godotengine/godot#38541]
**Godot version:** 3.2.1. 
**OS/device including version:** Mojave 10.14.6

**Issue description:**
Sometimes my Macbook completely freezes and I cannot move mouse and use keyboard. Also, when I was editing my TileMap, Godot suddenly crashed
**Steps to reproduce:**
I do not know if it is my Macbook's fault or Godot; therefore, I cannot suggest steps to reproduce

**Comment by Zireael07** [comment]
I believe we had similar reports, but first we need more detail: GPU/RAM, are you using GLES3 or GLES2?

**Comment by Akylzhan** [comment]
@Zireael07  Both on GLES2 and GLES3 it happens, but now I use GLES 2

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/18871.

@Akylzhan Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Akylzhan** [comment]
@Calinou sorry, cannot test this bug as I don't have Macbook anymore.

**Comment by Calinou** [comment]
> @Calinou sorry, cannot test this bug as I don't have Macbook anymore.

Alright, I'll close this then. Please comment if you (or anyone else) can still reproduce this in the future.
