### ISSUE TITLE
RichTextLabel: a method to get the number of visible lines

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#3854]
This is a feature request for RichTextLabel. Currently, RichTextLabel only offers to set/get the number of visible characters, but it does not offer how many lines are visible. As far as I see, this is not possible to calculate in GDScript when the font is a not a fixed-width one.
### Context:

The way RichTextLabel handles long texts (scrollbars) is useful when building desktop-like GUIs, but many games (Visual Novels, JRPGs) don't work that way.

I'm trying to implement a text box for dialogue. Typically, a a text box has a fixed width and fixed number of lines visible, so a long text that doesn't fit into the text box is broken into parts (each part contains only enough characters to fill the textbox), and the next part is not shown until the user presses a button.

I essentially need to implement something along the lines of [this](https://github.com/henriquelalves/GodotTIE), but I need to use RichTextLabel for italics and bold, and the font isn't a fixed width one. A way to obtain the number of visible lines will enable implemention.

**Comment by tagcup** [comment]
To be clear: With "number of lines", I don't mean "1 + number of \n". Word wrapping creates new lines when displaying the text. And I refer to the number of lines as it appears on the screen.

**Comment by vnen** [comment]
I want this too for the same reason :smiley:

**Comment by henriquelalves** [comment]
Yeah, this feature would made GodotTIE implementation much easier. What I had to do on the code was to use the autowrap feature of Labels to check whether every character that I add would create another line on the text; than I manually add a "\n" to it, so I can parse it later. I have no idea how performance heavy is this, because I'm basically almost triple iterating through every character that I add to the text.

**Comment by tagcup** [comment]
Performance wise, that's probably OK for dialogues, but I think Label should have a function that shows the number of visible lines too. It will complement the existing functions.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by tagcup** [comment]
Update: equivalent feature has been implemented for Label in #5792

**Comment by tagcup** [comment]
Fixed by #6859

**Comment by okardec** [comment]
I made a small method that can help those who need to get the full rich text lines
https://gist.github.com/okardec/6884a6924b6e6b0fe146234938a98307
