### ISSUE TITLE
Broken joypad input after 3.2.2.beta2

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#38554]
**Godot version:**
3.2.2.beta2

**OS/device including version:**
Windows 10 1909
Xbox One Wireless Controller

**Issue description:**
Joypad inputs no longer trigger `Input.is_action_pressed`.
`Input.get_joy_axis` is unaffected.
Caused by https://github.com/godotengine/godot/commit/9b636a2ccdeeebab00e43f867a7f5e2fb30cd7c9.

**Comment by hoontee** [comment]
Restoring the [previous version of main/godotcontrollerdb.txt](https://github.com/godotengine/godot/blob/7163551a3b2da1d9c2e1ff7722fa203f10409a21/main/godotcontrollerdb.txt) fixes the issue.

**Comment by RonanZe** [comment]
Still have the issue in 3.2.2-beta3

**Comment by akien-mga** [comment]
Let's reopen #38869 as I'm confident this one was due to the `__XINPUT_DEVICE__` removal and is fixed in 3.2.2-beta3.

**Comment by madmiraal** [comment]
@hoontee, I'm working on fixing #38869, which currently includes reverting #38557. To avoid going back and forth, please explain what you mean by:
> Joypad inputs are no longer mapped correctly.

Is it simply that the mapping is different? The previous mapping, that #38557 reinserts, is different to the official mapping. Since it overrides the official mapping; it would be nice to know why this is required. I suspect it was originally created to just to provide a mapping, when none existed, and we should use the official mapping; so it's consistent across OSes.

**Comment by akien-mga** [comment]
I noticed that `gamecontrollerdb.txt` also has `xinput` mappings:
```
xinput,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b8,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Windows,

xinput,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,
```

Maybe our `__XINPUT_DEVICE__` fallback should be changed to look for the `xinput` GUID instead?

**Comment by akien-mga** [comment]
Relevant hardcoded GUIDs that we query in our code (and have in `godotcontrollerdb.txt`):
```
$ rg __XINPUT_DEVICE__
core/input/godotcontrollerdb.txt
5:__XINPUT_DEVICE__,XInput Gamepad,a:b12,b:b13,x:b14,y:b15,start:b4,back:b5,leftstick:b6,rightstick:b7,leftshoulder:b8,rightshoulder:b9,dpup:b0,dpdown:b1,dpleft:b2,dpright:b3,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,platform:Windows,

platform/windows/joypad_windows.cpp
283:                            input->joy_connection_changed(id, true, "XInput Gamepad", "__XINPUT_DEVICE__");
```
```
$ rg __UWP_GAMEPAD__
core/input/godotcontrollerdb.txt
20:__UWP_GAMEPAD__,Xbox Controller,a:b2,b:b3,x:b4,y:b5,start:b0,back:b1,leftstick:b12,rightstick:b13,leftshoulder:b10,rightshoulder:b11,dpup:b6,dpdown:b7,dpleft:b8,dpright:b9,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,platform:UWP,

platform/uwp/joypad_uwp.cpp
117:    input->joy_connection_changed(controllers[idx].id, true, "Xbox Controller", "__UWP_GAMEPAD__");
```
```
$ rg "Default Android Gamepad"
platform/android/java/lib/src/org/godotengine/godot/xr/XRMode.java
37:     REGULAR(0, "Regular", "--xr_mode_regular", "Default Android Gamepad"), // Regular/flatscreen

core/input/godotcontrollerdb.txt
8:Default Android Gamepad,Default Controller,leftx:a0,lefty:a1,dpdown:h0.4,rightstick:b8,rightshoulder:b10,rightx:a2,start:b6,righty:a3,dpleft:h0.8,lefttrigger:a4,x:b2,dpup:h0.1,back:b4,leftstick:b7,leftshoulder:b9,y:b3,a:b0,dpright:h0.2,righttrigger:a5,b:b1,platform:Android,
```
```
$ rg "Default HTML5 Gamepad"
core/input/godotcontrollerdb.txt
11:Default HTML5 Gamepad, Default Mapping,leftx:a0,lefty:a1,dpdown:b13,rightstick:b11,rightshoulder:b5,rightx:a2,start:b9,righty:a3,dpleft:b14,lefttrigger:a6,x:b2,dpup:b12,back:b8,leftstick:b10,leftshoulder:b4,y:b3,a:b0,dpright:b15,righttrigger:a7,b:b1,platform:Javascript,

platform/javascript/display_server_javascript.cpp
636:                    guid = "Default HTML5 Gamepad";
```

**Comment by madmiraal** [comment]
> Maybe our __XINPUT_DEVICE__ fallback should be changed to look for the xinput GUID instead

This appears to be the mapping used by Windows if an XInput device is detected. Would it be considered a breaking change if we suddenly start using a different, albeit official, mapping?

**Comment by akien-mga** [comment]
> > Maybe our `__XINPUT_DEVICE__` fallback should be changed to look for the xinput GUID instead
> 
> This appears to be the mapping used by Windows if an XInput device is detected. Would it be considered a breaking change if we suddenly start using a different, albeit official, mapping?

I guess, we'd have to give it a try. It's weird that our `__XINPUT_DEVICE__` mapping (which seems to work fine? At least users don't seem to complain about it) is so different to upstream SDL's.
