### ISSUE TITLE
TabContainer children can't be positioned or resized to clip content

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#38576]
**Godot version:**
3.2.1

**OS/device including version:**
Window 10 Pro Education 64 bit

**Issue description:**
The Tab Container's immediate children rect can't be changed to clip content
and in most cases the rect is wrong 

it is somewhat editable in the godot editor but its a pain in the butt and 

once you play the game it resets

**Steps to reproduce:**
- Add Tab container
- Add Tab or Panel to Tab Container
- Add VBox to Tab or Panel 
- Add two buttons to the VBox
- Change Tab or Panel's rect to desired clip area
- Play game
- See that it is not the same

**Minimal reproduction project:**
[Tab Container Clip Bug.zip](https://github.com/godotengine/godot/files/4601026/Tab.Container.Clip.Bug.zip)

**Comment by groud** [comment]
This is expected behavior, children of containers get their position and size automatically set by the parent container, so you can't expect those value to be reliable. There is already an open PR about this problem, forbidding editing the properties overridden by the parent container.

As a workaround, you may add a normal control node in the hierarchy.

**Comment by Shadowblitz16** [comment]
@groud why can't we have offsets that offset the parents positioning?
I don't see why people have such a big deal with this.
it makes things easier to edit and sometimes like here the containers don't position their parent correctly.

this makes us have to create a bunch of unnecessary children node's per container to fix it

please reopen this

**Comment by groud** [comment]
Because this is not what containers are designed for. If you believe you should be able to offset the child of container once it has been positioned correctly, then this is a feature proposal. Thus you can open an issue for it in the godot-proposals repository.
