### ISSUE TITLE
Web Build : Reflection probes not working correctly

### ISSUE THREAD

**Issue by AlveLarsson** [godotengine/godot#38571]
**Godot version:**
3.2.1

**OS/device including version:**
Web Build + GLES2
**Issue description:**
Reflection probes not working correctly in web builds, see the image.

**Steps to reproduce:**

**Minimal reproduction project:**
https://www.dropbox.com/s/ndg1i75yknqfhus/minifix.zip?dl=0

![image](https://user-images.githubusercontent.com/61861940/81419106-01afda80-914e-11ea-8aab-9475a025ccdb.png)

**Comment by Calinou** [comment]
@AlveLarsson Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, which renderer are you using? You should always use GLES2 when exporting a project to HTML5.

**Comment by AlveLarsson** [comment]
@Calinou Yep sorry, it's on the way.

yeah I'm using GLES2, and the mini-project has the same bug

**Comment by AlveLarsson** [comment]
![image](https://user-images.githubusercontent.com/61861940/81422705-a2ed5f80-9153-11ea-8adc-4b6cef84f17f.png)
and here is the mini-project with the bug in action

**Comment by WeaselShoppe** [comment]
Is this still an outstanding issue in master? I have added a fix to my own fork of 3.2. Tested on:
Chrome Windows
Chrome Android
Safari IOS

**Comment by Calinou** [comment]
> Is this still an outstanding issue in master? 

The `master` branch currently only has a Vulkan renderer which can't run on HTML5.

**Comment by WeaselShoppe** [comment]
> > Is this still an outstanding issue in master?
> 
> The `master` branch currently only has a Vulkan renderer which can't run on HTML5.

So is this a candidate for inclusion in 3.2?

**Comment by Calinou** [comment]
> So is this a candidate for inclusion in 3.2?

Yes, feel free to open a pull request against this repository's `3.2` branch :slightly_smiling_face:

**Comment by WeaselShoppe** [comment]
Done :)
https://github.com/godotengine/godot/pull/45465

**Comment by akien-mga** [comment]
Fixed by #45465.
