### ISSUE TITLE
Globals GUI not working propperly

### ISSUE THREAD

**Issue by ZippoLag** [godotengine/godot#3857]
**Operating system or device:**
Windows 7 x64

Using either Godot_v2.0_stable_20160223_win64.exe or Godot_v2.0_stable_20160223_win32.exe

**Issue description** (what happened, and what was expected):
There are a few of strange issues when trying to add/edit globals (see steps).

**Steps to reproduce:**
1. Create and open a new project in the editor.
2. Add any node as root
3. Open Scene/Project Settings/Global
4. Add a new global variable "foo" of any kind -> popup's view is set to "Application" settings for some reason
5. Enter some value for the propperty and press enter (or simply click to check the box if it's boolean) -> propperty appears to be duplicated

**Comment by akien-mga** [comment]
I can reproduce this bug on Linux too.

**Comment by ScotFlux** [comment]
Windows 10 x64. Yes, I can confirm, It's a bug.
