### ISSUE TITLE
Yield with null object causes silent crash on a headless server

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#38574]
**Godot version:**

v3.2.1

**Issue description:**

Calling yield with null as the first argument crashes silently, but only on a headless server.

**Steps to reproduce:**

Create a project where `yield(null, "")` is called in `_ready`.
Export the .pck.
Launch the Godot server with the --main-pack argument.

**Minimal reproduction project:**

[.pck file](https://github.com/godotengine/godot/files/4600584/silent_crash.zip)
[project folder](https://github.com/godotengine/godot/files/4600587/silent_crash_project.zip)

**Comment by Ev1lbl0w** [comment]
It also crashes silenty on the normal engine when run directly:
```bash
$ godot --path /path/to/project
...
SCRIPT ERROR: _ready: First argument of yield() not of type object.
   At: res://Node2D.gd:5.
```
I don't think it's a bug, Godot tries to recover from these problems without impacting the rest of the code, so it keeps running after this error.

**Comment by ThakeeNathees** [comment]
> I don't think it's a bug, Godot tries to recover from these problems without impacting the rest of the code, so it keeps running after this error.

As I'm agreeing with @Ev1lbl0w  not only yield, but almost all runtime errors are fail silently, it can be easily be noticeable when there is a runtime error in the script and it's a tool script, is this expected behavior, if not how to handle?

**Comment by Jummit** [comment]
Closing as this is a larger issue. Maybe there can be a proposal about printing an error message when the server crashes.
