### ISSUE TITLE
Renaming a node in the Editor tree causes 2D/3D editor to come into focus

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#38570]
**Godot version:**
3.2.1, master #b9f2e57

**OS/device including version:**
Windows 10

**Issue description:**
Changing the `name` property of any node in the Editor UI tree causes an unexpected side effect, if there is a scene opened in 2D/3D editor and any of its nodes is selected. Whatever the main screen editor it is currently, it will be changed to the 2D or 3D editor as soon as the code that renames the UI node is executed.

Here is an example of nothing going wrong, because no node is selected:

![2020-05-08_17-26-50](https://user-images.githubusercontent.com/11782833/81415565-48eb9a80-9151-11ea-827d-f6ecbfea8c83.gif)

And here we have a node selected, so as soon as we restart a specifically designed plugin, the 2D editor pops into view:

![2020-05-08_17-27-12](https://user-images.githubusercontent.com/11782833/81415577-4c7f2180-9151-11ea-9319-f9a10b593bf5.gif)

I've experienced this issue while working on a UI plugin, but I'm pretty sure that the issue has nothing to do with plugins. It's just much easier to reproduce the issue using a plugin and a GDScript script. At a glance it seems that the fact that the node was renamed is propagated to the whole tree and the canvas item editor plugin or the spatial editor plugin react to it as something important to them and steal focus.

The issue (with plugin at least) is resolved if the node is named before adding it to the tree. But it may not always be possible.

**Steps to reproduce:**
See the minimal reproduction project.

1. Create a new project with a single scene that has a 2D or 3D node in it.
2. Create a new plugin that adds a dock with a label with code.
3. In the plugin code after the label is added to the dock change its `name` property.
4. Open 2D or 3D editor with your only scene and select your only node.
5. Open Script editor.
6. Restart the plugin.

**Minimal reproduction project:**
[bug-eager-2d-view.zip](https://github.com/godotengine/godot/files/4599418/bug-eager-2d-view.zip)

**Comment by aaronfranke** [comment]
I think the ideal fix is to only change the focused main screen if the plugin being enabled or disabled `handles` anything. The check could be simply `plugin_script.has_method("handles");`. It might also be necessary to also check if the `has_main_screen` method exists.

**Comment by pycbouh** [comment]
@aaronfranke Plugin being enabled or disabled has nothing to do with the issue.

**Comment by coppolaemilio** [comment]
Same happens on my plugin. Attaching a video of what is going on just to add more info to the issue.

https://user-images.githubusercontent.com/2206700/124390064-456a8980-dcea-11eb-9724-f83df54b2953.mov

Still trying to make some changes to see if not naming any node would fix it

**Comment by KoBeWi** [comment]
Doesn't seem to be happening in the newest 4.0.
@YuriSizov Can you confirm?

**Comment by YuriSizov** [comment]
Indeed, I can't reproduce it in either the current master, or stable releases `3.4` and `3.5`. It is still reproduceable in `3.3`, so it must've been fixed somewhere in between.
