### ISSUE TITLE
3.2.2 beta 2 Android crash when GodotPaymentV3 module enabled

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#38581]
**Godot version:**
Broken:
3.2.2 beta 1
3.2.2 beta 2

Works fine:
3.2.1 stable

**OS/device including version:**
Android/Samsung Note 9
**Issue description:**
crash with godot payment v3 module enabled
**Steps to reproduce:**
add godot payment v3 module and export project
![image](https://user-images.githubusercontent.com/24432677/81458844-8fd99000-9151-11ea-9767-25577ec43901.png)
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Can you retrieve crash logs with `adb logcat` with a debug export?

**Comment by HEAVYPOLY** [comment]
[Uploading logcat.txt…]()

**Comment by HEAVYPOLY** [comment]
[logcat.txt](https://github.com/godotengine/godot/files/4603045/logcat.txt)

**Comment by m4gr3d** [comment]
@HEAVYPOLY This is expected behavior as `GodotPayment` has been refactored based on the new plugin architecture.
To enable it, add `GodotPayment` to the Android export window (not the project settings module window as shown in your screenshot) in the `Plugins` (under `Use custom build`) section.

**Comment by akien-mga** [comment]
@m4gr3d We should probably add some code to ease the transition.

We could either:
- Add some conversion from `android/modules` to the relevant preset options
- Raise a warning when `android/modules` is defined, so that users know that they need to port it to the new system

**Comment by HEAVYPOLY** [comment]
Thanks!  @m4gr3d is the GodotPayment a 1:1 replacement for GodotPaymentV3?  Do I need to change anything else in my working code to migrate?

**Comment by m4gr3d** [comment]
> Thanks!  @m4gr3d is the GodotPayment a 1:1 replacement for GodotPaymentV3?  Do I need to change anything else in my working code to migrate?  eg:  Engine.has_singleton("GodotPayments") is still valid?

@HEAVYPOLY yes, it's a 1:1 replacement with additional bug fixes.
The name to use in your scripts should be `GodotPayment`, instead of `GodotPayments`.
The documentation will be updated accordingly.

**Comment by HEAVYPOLY** [comment]
Great, thanks.  This won't affect iOS payment in any way right?

**Comment by akien-mga** [comment]
Fixed by #38749.
