### ISSUE TITLE
No error when trying to assign a non null to variable type hinted null.

### ISSUE THREAD

**Issue by DrAlta** [godotengine/godot#38582]
**Godot version:**
3.2.1.stable.offical

**OS/device including version:**
win 10 home 10.0.18362 build 18362
HP laptop 15-da0xxx

**Issue description:**
Type hinting a variable to null doesn't give an error when you try to set it to a non null value it just stays null.
**Steps to reproduce:**
Type hint a variable to null with ":=null"
**Minimal reproduction project:**
[Map Editor.zip](https://github.com/godotengine/godot/files/4602411/Map.Editor.zip)

**Comment by KoBeWi** [comment]
`:=null` might not type it as "null" but as Variant or Object.

**Comment by DrAlta** [comment]
Is null is a Variant or an Object then why doesn't it allow you to change the value of the variable?  Godot just ignores assignments to the variable.
