### ISSUE TITLE
From GitHub HEAD: Custom-node addon crashing Godot

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#3859]
**Operating system or device:**
LinuxMint 64bit, Godot.x11 Editor.

**Issue description** (what happened, and what was expected):
The Editor wouldn't update the Nodes list after enabling/disabling the "Heart" addon example; if you add the Node after it was disabled, the Engine will crash. 

**Steps to reproduce:**
To check on Node list update:
1- Enabling "custom_node" plugin on the addon list.
2- Click on "Add/Create a new Node"
The node won't appear on the Node List, unless you search for "Heart" node. Than it will show properly on the list.
The inverse thing will happen when you disable the Addon; it will stay appearing on the list, unless you search for him (than it won't show anymore).

To crash the Editor:
1- Enable "custom_node" plugin on the addon list
2- Disable "custom_node" plugin on the addon list
3- Enable "custom_node" plugin on the addon list
4- Add the "Heart" node to the scene.
The editor will crash; restarting it will have "Heart" Addon enabled.

**Comment by akien-mga** [comment]
Does this still happen in the current 2.1 beta?

**Comment by henriquelalves** [comment]
I lost the project in which I had the particular Heard addon demo that I tested; but using the node Addon I created myself, Godot didn't crashed.
One thing that I noticed is that, by searching the parent node that your Addon node inherits to, your addon won't appear on the list (the inherited Addon won't show it's children nodes). I will make another issue with that.
