### ISSUE TITLE
Rightclick context menu generation uses screen offset instead of window offset.

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#38591]
**Alternative Title:** Rightclick context menu generation uses the active window's parent's window offset instead of active window offset.

**Godot version:**
Latest master 46f1d4ff8e111b66c457ebcf27c72f84f96721d3

**OS/device including version:**
Windows 10 1909 

**Issue description:**
Rightclick context menu generation uses screen offset instead of window offset.
Thus, even making context menu outside window depending on the position.

**Steps to reproduce:**
1. Move window anywhere accept top left default position.
2. Right-click any right-clickable thing.
3. It will be generated at the same XY offset that it should have from screen's top-left(actual) instead of window's top-left(expected).
![godot-issue](https://user-images.githubusercontent.com/11459028/81474637-79503900-9224-11ea-80c4-e88857e14d0e.gif)

**Update:** Another way to reproduce this is to right-click anything in the file dialogue e.g,
1. Click any node.
2. In the inspector, click the Load button for the Material property.
3. Move this EditorFileDialog to any position other than the default position.
4. Right-click anything.
5. **This time it will use the main window's offset instead of the EditorFileDialog's offset.**

**Minimal reproduction project:**
Any project.

**Comment by bruvzg** [comment]
Should be fixed by #37506

**Comment by Anutrix** [comment]
> 
> 
> Should be fixed by #37506

Confirmed that it works.

**Comment by Anutrix** [comment]
Don't know which commit fixed this but I can no longer reproduce this. If someone can confirm I'll close this issue. I tested with https://github.com/godotengine/godot/commit/0f1da724924fc494bfd316c57757e0e1d7b90143.
