### ISSUE TITLE
Augmented Reality support for Godot 

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3860]
This is a very broad feature request encompassing some or most of these features:
- Video Camera Capture
- Object Recognition (likely OpenCV via haar)
- or some other form of AR Card contextual shape recognition
- Motion Tracking
- Mobile devices sensors support
- GPS Tracking

Likely 3.0 or later if at all desired for Godot Engine. AR Games are getting more popular so would be quite nice to have out of the box AR support for Godot Engine.

**Comment by benbotwin** [comment]
Is GPS tracking available in the 3.0 alpha?

**Comment by reduz** [comment]
@BastiaanOlij is working on it

**Comment by BastiaanOlij** [comment]
Note that PR #9967 show a very early ARkit implementation for AR on iPhone based on the ARVRServer architecture we added and are perfecting for Godot 3.0. Biggest issue holding us back here at the moment (other then turning a prototype into a proper implementation) is ARKit tying us into iOS 11.

I'm currently working on a more generic approach for making the Camera image available to be used in the background that should make it easier to also implement this stuff on Android. Once available I'm sure someone will be able to add support for Android, in combination with the already existing accelerometer and gyroscope that gives you enough to do a Pokomon go style AR game. 

Parsing the camera image for SLAM on Android I suggest however that someone who is more familiar with what is available on Android have a closer look. Do keep in mind that that level of tracking requires top of the line phones or tablets and that Google has put their money on their new Tango system. It may not be worth reinventing the wheel here.

GPS is a subject in its own right but should just be a matter of calling the right APIs on Android and iPhone to expose ones coordinates.

**Comment by Calinou** [comment]
I'll close this as Godot features AR/VR support since 3.0. If some features you need are still missing, please [open a new proposal](https://github.com/godotengine/godot-proposals) for each missing feature.
