### ISSUE TITLE
[codeblock]s in description tags in classes.xml show badly in editor help

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#3861]
**Operating system or device:**

Linux 64 bit, shouldn't matter.

**Issue description** (what happened, and what was expected):

In short, `[codeblock]` constructions in class description show on just one line.

When writing a description about `Tween`s in `classes.xml`, I decided I should add a code example **to the class itself**, like so:
````
	<description>
	Node useful for animations with unknown start and end points, procedural animations, making one node follow another, and other simple behavior.
	
	Because it is easy to get it wrong, here is a quick usage example:
	
	[codeblock]
	var tween = get_node("Tween")
	tween.interpolate_property(get_node("Node2D_to_move"), "transform/pos", Vector2(0,0), Vector2(100,100), Tween.TRANS_LINEAR, Tween.EASE_IN_OUT)
	tween.start()
	[/codeblock]
	</description>
````

Unfortunately, in-editor this shows on a single line:
![image](https://cloud.githubusercontent.com/assets/5276727/13379740/cad98dd6-de36-11e5-9040-9142e6039285.png)

I tried to double the newlines in the code as well, but then it would become new paragraphs (and looks even worse).

**Steps to reproduce:**

Copy-paste the example from above.

**Comment by vnen** [comment]
Codeblocks are being shown in multiple lines, so I guess this is fixed. Still doesn't look good IMO, but that's another issue.

![godot windows opt tools 64_2016-06-03_12-24-03](https://cloud.githubusercontent.com/assets/5599796/15783821/2d93b7b8-2986-11e6-9153-cfb6b32cdbee.png)
