### ISSUE TITLE
Gridmap : seperate set_cell_item and update gridmap

### ISSUE THREAD

**Issue by CptnRoughnight** [godotengine/godot#38616]
Hi, 

I'm working with Gridmap and there is a thing I don't understand. set_cell_item updates the octant of the gridmap for each call. Is there a way to seperate this, to populate the gridmap data and then update the gridmap?

**Comment by Calinou** [comment]
As the issue template says, this repository no longer accepts feature proposals. If you still need this feature, please create a proposal on the [Godot proposals](github.com/godotengine/godot-proposals) repository and follow the instructions there.
