### ISSUE TITLE
Getter method is not called for property

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#38619]
**Godot version:**
v3.1.2.stable.official
v3.2.2.rc.custom_build.36a30f681

**OS/device including version:**
Windows 10

**Issue description:**
Getter method is not called. This example prints Null instead of 10
```
extends Node2D

var test_val setget set_test_val, get_test_val
var store

func set_test_val(value):
	store = value
	
func get_test_val():
	return store
	
func _ready():
	set_test_val(10)
	print(test_val)
```
As you can see I have used different field as backing field

**Comment by Slainlight** [comment]
Thanks for closing this, i'm pretty confident that was a programming error on your end

**Comment by p10tr3k** [comment]
Yes, it was my mistake, sorry
