### ISSUE TITLE
Html5 issue with actions

### ISSUE THREAD

**Issue by kev93** [godotengine/godot#3862]
**Operating system or device:**
Windows 7 64 bits / google chrome

**Issue description** (what happened, and what was expected):
In html5 export the game only recognize 1 key for action. If the action have more than 1 key assigned it will only recognize the first and not the rest

**Steps to reproduce:**
Create an action with a least two keys assigned. And use it in code

**Link to minimal example project** (optional but very welcome):

**Comment by eska014** [comment]
Is this really an issue with actions? I think the problem might be that you're binding a key that isn't recognized in HTML5 export, see #2761
It works for me with e.g. `PageUp` and `PageDown` bound to the same action

**Comment by eska014** [comment]
I'll assume this was fixed for now
