### ISSUE TITLE
When use Godot WebSocket Client connect to WebSocket Server implemented in other languages, sometimes the connection becomes unstable

### ISSUE THREAD

**Issue by colorworlds** [godotengine/godot#38620]
**Godot version:**
3.2  

**OS/device including version:**
win7  

**Issue description:**
I use the websocket provided by Godot to connect to the websocket service of a live website, but sometimes the connection is automatically disconnected.  

**Steps to reproduce:**  
I provide the demonstration code here:  
[gd-websocket-issue](https://gitee.com/colorworlds/gd-websocket-issue)  
This includes a browser version and a Godot version for comparison.    

**Godot version**   
The Steps to run the Godot Version project:   
1.Open the Godot Project.   
2.Open and Run the Node.tscn scene.   
the information about the connection will be printed out in the console, and the important thing is that it will print "connection closed !!" sometimes,this means that the connection is broken.And then it'll start a new connection.  

**Browser version**  
1.click the biliclient.html  
2.open the console of browser.  the console will display similar information.  
browser version can run all the time without disconnecting.  

I have confirmed through Wireshark that two versions of websocket carry the same data.  

**Minimal reproduction project:**  
The above link address provides the demonstration code. There are some problems in my network speed, so it is difficult to me to transfer the file to GitHub.

**Comment by Calinou** [comment]
@colorworlds Did you find a solution to this problem? If so, please document it here to help other people who may stumble upon this issue from a web search :slightly_smiling_face:

**Comment by colorworlds** [comment]
@Calinou This problem does not appear in the 3.4.2 version. I have not changed the previous code, but there is no previous automatic disconnection. So this problem may have been fixed in a version of 3.3 or 3.4 .

**Comment by mhilbrunner** [comment]
Could be because of https://github.com/godotengine/godot/pull/54344 (backport: https://github.com/godotengine/godot/pull/54381)

https://github.com/godotengine/godot/pull/51036 wasn't backported to 3.x, so likely not relevant.

**Comment by colorworlds** [comment]
@mhilbrunner Great job! This problem bothered me for a long time.
