### ISSUE TITLE
Singleton Script Refuses to calculate valid IF conditon

### ISSUE THREAD

**Issue by MrJDR** [godotengine/godot#38643]
Script refuses to calculate [Rank Progression] on while the first IF condition is TRUE. All other conditions calculate while their respective IF/ELIFs are TRUE.

The following script is loaded as a singleton. The offending line is in bold.

=============================================

```
extends Node


var Artist_Name = ""
var Lives = 3
var Max_Health = 80
var Max_Inspiration = 3
var Rank_Title = "NOBODY"
var Rank_Progress = 0
var Fame = 100
var Max_Fame = 1000

var Rank_1 = (Max_Fame / 5)
var Rank_2 = (Max_Fame / 2.5)
var Rank_3 = round(Max_Fame / 1.6)
var Rank_4 = (Max_Fame / 1.25)
var Rank_5 = (Max_Fame / 1)


func _ready():
	#This is Rank Progression
	if Fame < Rank_1:
		Rank_Title = "NOBODY"
		Rank_Progress = float(Fame / Rank_1)
	elif Fame in range(Rank_1, Rank_2):
		Rank_Title = "Rank D"
		Rank_Progress = float(Fame / Rank_2)
	elif Fame in range(Rank_2, Rank_3):
		Rank_Title = "Rank C"
		Rank_Progress = float(Fame / Rank_3)
	elif Fame in range(Rank_3, Rank_4):
		Rank_Title = "Rank B"
		Rank_Progress = float(Fame / Rank_4)
	elif Fame in range(Rank_4, (Rank_5 + 1)):
		Rank_Title = "Rank A"
		Rank_Progress = float(Fame / Rank_5)
	elif Fame >= (Rank_5 + 1):
		Rank_Title = "LEGEND"
		Rank_Progress = float(Rank_5 / Rank_5)
	else:
		print("Broken Rank Progression")
	pass 
```

Expected Result:
if Fame < Rank_1:
Rank_Progress == .5

Actual Result:
if Fame < Rank_1:
Rank_Progress == 0

**Comment by MrJDR** [comment]
Godot Version 3.1.1
MBP Retina Mid 2014 
MacOS 10.15.4 (Catalina)

**Comment by TheDuriel** [comment]
expected behavior

youre mixing integer and float divisions

int / int = int

intorfloat / intorfloat = float

**Comment by MrJDR** [comment]
> expected behavior
> 
> youre mixing integer and float divisions
> 
> int / int = int
> 
> intorfloat / intorfloat = float

Correct. Thanks for this.

Fixed by using float(float(Fame) / Rank_1)
