### ISSUE TITLE
direct_space_state returns null when using godot 3d physics

### ISSUE THREAD

**Issue by huhund** [godotengine/godot#38653]
**Godot version:**

3.2.1_stable
also in branch 3.2 - pulled from 56a513d70d 11 May 2020 at 08:55

**OS/device including version:**

MacOSX

**Issue description:**

get_world().direct_space_state
returns null when using godot 3d physics instead of bullet physics

**Steps to reproduce:**

**Minimal reproduction project:**

* Create a 3D scene
* Change 3d physics engine to Godot
* Add the following script

```
extends Spatial

func _ready():
	print("ready")
	pass

func _process(delta):
	var space_state = get_world().direct_space_state
	var result = space_state.intersect_ray(Vector3(0, 0, 0), Vector3(50, 100, 0))
```

Script halts on a null pointer

**Comment by madmiraal** [comment]
As stated in the [documentation](https://docs.godotengine.org/en/stable/classes/class_world.html#property-descriptions) the `direct_space_state` is only available in the `_physics_process()` loop.

That been said, for consistency, Bullet physics should be returning `null` too.

**Comment by huhund** [comment]
You're right. My bad, thanks for the help.

**Comment by MightyPrinny** [comment]
This might be relevant again, I'm getting null but only when I use Godot physics even if i try to get the direct space from _physics_process

**Comment by madmiraal** [comment]
@MightyPrinny Are you referring to  #38909?
