### ISSUE TITLE
Can't select rows in editor help, because dragging mouse scrolls (ScrollContainer touch input emulation bug)

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#38665]
**Godot version:**
41f6676

**Issue description:**
![AbH9HNa9Si](https://user-images.githubusercontent.com/2223172/81569467-952c1a00-939f-11ea-9d70-0eb717a75d15.gif)
Looks like some touch control stuff to me (I have the emulate option disabled). Might happen in other places too.

**Comment by Calinou** [comment]
This is a likely a regression related to DisplayServer.

**Comment by KoBeWi** [comment]
Sooo I just noticed the same issue in Filesystem Dock. It makes it impossible to move files.

**Comment by reduz** [comment]
This is a good chance to convert all the touchscreen emulation code that is responsible for this bug to actual touchscreen events in the relevant controls. I will see to do this in the next days.

**Comment by KoBeWi** [comment]
Fixed by #49241
