### ISSUE TITLE
Materials imported from a 3D model file should use ".tres" instead of ".material"

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#38660]
**Godot version:** 3.2.2 beta

**Issue description:**

I noticed that when I imported a 3D model (GLTF `.glb`), Godot created materials, but they were using the binary `.material` format. I think it would be much better to import materials into the `.tres` format, since this is how Godot offers to save materials by default when doing so manually, and also because `.tres` is much more friendly to version control and usually a smaller file size anyway.

**Comment by Calinou** [comment]
I'm fairly sure this is a duplicate of another issue, but I can't find it right now.

**Comment by fire** [comment]
Here's my other issue about it. https://github.com/godotengine/godot-roadmap/issues/30

**Comment by fire** [comment]
@aaronfranke Can you ensure there's a proposal for this?

**Comment by aaronfranke** [comment]
This issue is now obsolete as of the new import workflow in Godot 4.0, 3D model files like `.glb` no longer have their materials saved to separate files, and there is no extract option anymore (but there is a "use external" override feature). Saving materials in the inspector offers to save as `.tres` first. Therefore, I am closing this issue as fixed in Godot 4.0.
