### ISSUE TITLE
Script Editor word highlighting

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#3867]
This is a small feature wish for the script editor and may be open for discussion.

When navigating through longer scripts and searching for special variables I found a certain feature extremely helpfull in other scripting editors.
If I mark a word (be it a variable name, or value or object) the scripteditor also marks the same word in the whole editor. This makes it supereasy to look for variables that are also used in other places. And I think this could be something that is not very hard to add.

What do you think of such feature? I think this is a small enhancement which can make life a lot easier :)

**Comment by neikeq** [comment]
I think this feature is listed in #2982

**Comment by ndee85** [comment]
Ah ok.. sorry missed that one. Ok. to keep this clean I will close this issue and link to the same as you listed.

So further discussion can go in here: https://github.com/godotengine/godot/issues/2982

**Comment by ndee85** [comment]
ups. forgot to close this one.
