### ISSUE TITLE
editor/icons/ReadMe.md links nowhere

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#38684]
**Godot version:**
master

https://github.com/godotengine/godot/edit/master/editor/icons/README.md links to a 404

Where are the svg optimization scripts? How would I correctly replace/add an Icon?

**Comment by clayjohn** [comment]
Its all in the godot-design repo. The link you have there doesn't 404 for me. Github might just be having issues. At any rate here is what it says
```
The icons here are optimized SVGs, because the editor renders the svgs at runtime, they need
to be small in size, so they can be efficiently parsed.

The original icons can be found at:
https://github.com/godotengine/godot-design/tree/master/engine/icons

There you can find the optimizer script.

If you add a new icon, please make a pull request to this repo:
https://github.com/godotengine/godot-design/

and store the optimized SVG version here.
```

**Comment by akien-mga** [comment]
The first link is broken as icons were removed from godot-design.
@Calinou

**Comment by Calinou** [comment]
That README is outdated, it should probably just point to [Editor icons](https://docs.godotengine.org/en/latest/development/editor/creating_icons.html). Also, the part about SVG optimization is now outdated as we switched to [svgcleaner](https://github.com/RazrFalcon/svgcleaner):

```bash
svgcleaner --multipass your_svg_source.svg your_svg_optimized.svg
```
