### ISSUE TITLE
[need clarification] Override to_string() method in custom module classes

### ISSUE THREAD

**Issue by desperate-coder** [godotengine/godot#38696]
Hallo folks,

I want to override to_string in custom module classes.
I have fond Issue #27886, but i am not able to quite follow it.

By testing I found out, that when I make the method virtual, I get the desired results.
Now I would like to know, if this approach is an intended one.
If so then, my suggestion is to make the to_string() method in Object class virtual.

I would be very thankful if somebody could take the time and help me (and maybe others) out with this case.

**Comment by gabrielpreviato** [comment]
Hey @desperate-coder. I'm new at the Godot Universe, but what I assume looking at the #27886 and the [Object class documentation](https://docs.godotengine.org/en/stable/classes/class_object.html) is that the method is already virtual and if you look in the PR discussion (and also in the docs) you can find the calling the method obj.to_string() will return a String, but the method that should be overridden is the virtual method "_to_string()". I think that's a little bit confusing, but it seems they made it trying to keep some consistency with other methods.

I hope I've helped you :)

**Comment by desperate-coder** [comment]
Hello @gabrielpreviato. Just wanted to thank you for taking the time to respond to my initial message and your explaination was very helpful.
Up until now i studied the engine more and i think i got the basic handling for these cases by now, as of how virtual functions are supposed to work.
So with this i will close the issue.
Thanks for your help again!
