### ISSUE TITLE
3.2 GDScript static functions no longer can reference constants.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#38700]
**Godot version:**
8cb67bb

**OS/device including version:**
Win10 64-bit

**Issue description:**
It appears that static functions can no longer reference constants.

This commit https://github.com/godotengine/godot/pull/38412 broke lots of code in my projects.  I was using static functions in various libraries type classes that relied on some simple shared constants.

I've begun removing the static keyword for starters as a work around, but also have to go and setup instancing of those classes everywhere that uses them.

I understand the PR is aiming to fix some usage of variables.

@vnen It's not clear to me if this was never intended to allow for statics to read constants as well, or if this is a regression.

**Steps to reproduce:**

Use this code in the most recent commits of 3.2 after above cherry-pick.

```
extends Node2D

const ANGLE = deg2rad(120)

static func angle_ofs(theta):
	return theta + ANGLE
```
This error follows.

![godot windows tools 64_dLdGXuCrQe](https://user-images.githubusercontent.com/13004169/81728083-8e320400-9492-11ea-8fa7-eecd458c1b70.png)

**Minimal reproduction project:**
[Static Func Const Issue.zip](https://github.com/godotengine/godot/files/4617528/Static.Func.Const.Issue.zip)

**Comment by akien-mga** [comment]
CC @vnen @ThakeeNathees

**Comment by hilfazer** [comment]
Whether static functions should be able to access constants depends on whether const arrays and dictionaries work as intended or are bugged.

In 3.2 following code will modify const dict and array:
```
const DIC = {}
const ARR = []

func _ready():
	bad(1)
	bad('1')

static func bad(x):
	DIC[x] = 3
	ARR.append(x)
```

If the content of const arrays/dict was costant too then 'const' would be a fair game for static functions (unless i'm missing something).

**Comment by avencherus** [comment]
@hilfazer Interesting, never tried this until now.  I tried appending to a constant array and it is also possible anywhere it seems, not limited to static functions.  I would think it is a separate issue.  Does one exist already?

**Comment by TheDuriel** [comment]
Entirely separate issue. Can't find it right now, but its been well known. OPs problem is certainly new.

**Comment by TheDuriel** [comment]
Entirely separate issue. Can't find it right now, but its been well known. OPs problem is certainly new.

**Comment by hilfazer** [comment]
I found this:
https://github.com/godotengine/godot/issues/30212

I remember there being another issue on const dictionaries/arrays.
