### ISSUE TITLE
Long code hints do not fit in editor window

### ISSUE THREAD

**Issue by ZippoLag** [godotengine/godot#3870]
When typing a parameters for a function with many parameters, the hint/tooltip that's displayed may sometimes appear way to the right and end up under the Inspector window as seen in the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/755062/13382433/54ac0f72-de53-11e5-9259-ee84b64c06c6.png)

**Comment by akien-mga** [comment]
Thanks, that would be issue #1257.
