### ISSUE TITLE
3.2.2 beta2 - Modulate and Self-Module keying not working with AnimationPlayer

### ISSUE THREAD

**Issue by IRONIC3D** [godotengine/godot#38715]
**Godot version:**
3.2.2 Beta 2
**OS/device including version:**
Windows 10 v2004
**Issue description:**
When animating the Modulate or Self-Modulate property (color or alpha) in the AnimationPlayer the keyframe is not respected and defaults to whatever is on the sprite material. The same effect is working without an issue with 3.2.1
**Steps to reproduce:**
(**if using the scene provided**)

Note: The sprites are using a color shader, a simple color shader fragment. This scene is working without any issues in 3.2.1 with the same exact setup)

1. Open the Circle.tscn
2. Pick the AnimationPlayer and choose the capture track
3. Select the SpriteEffect node and try to animate the alpha/color of the modulate or self-modulate
5. When adding a key to the modulate and moving the play head. The changes are not respected
6. Changing the self-modulate property doesn't change anything at all.
7. Performing those changes without the AnimationPlayer present works for both modulate and self-modulate.

**Minimal reproduction project:**
[Jumper_debug.zip](https://github.com/godotengine/godot/files/4621905/Jumper_debug.zip)

**Comment by IRONIC3D** [comment]
There are two animations in the Circle scene. Implode (which works on the original sprite) and the Capture. Which animates a duplicate of the Sprite node.

The implode animation scales down and animate the modulate effect of the Area2D node. The animation works without an issue.

The capture animation is animating the SpriteEffect node directly. Starts off by enabling the visibility, while having the alpha at 0. The Alpha in this case is not respected.

Opening this scene in 3.2.1 will render the animation correctly.

**Comment by lawnjelly** [comment]
It's already fixed in latest 3.2, as far as I can see. I did a couple of fixes in this area since the last beta. :+1:
