### ISSUE TITLE
Removing an implicitly added node from built-in nodes causes a silent crash

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot#38714]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
Some built-in nodes, like `ScrollContainer`, implicitly add various child nodes that can only be seen when the project is running. If you accidentally delete any of them, the running process silently crashes without any error reported by the engine.

![2020-05-13_12-53-55](https://user-images.githubusercontent.com/11782833/81798646-f3c8d380-9518-11ea-9264-107bc2fe94ca.gif)

While I knew that there could be additional nodes, it still took me some time to figure out why there was a crash when I had been trying to replace a single child node of a `ScrollContainer`. It is not obvious that there are other child nodes inside of the built-in node unless you run the project and look at the Remote tab. The situation is worsened by the fact that the crash, due to its nature, does not report any errors (I'm guessing some reference gets corrupted and the entire engine just panics?).

Ideally, I think that there are two things that need to be done.
1. User scripts should not be able to remove any nodes required by built-in nodes to exist. Like scrollbars in case of `ScrollContainer`. Calling `remove_child` on such a node should err and the process should recover and move on.
2. It would be really handy to be able to see implicit nodes in the Scene Tree dock. Such nodes should be disabled, of course. Maybe with some visibility toggle to reduce noise. I understand, that not all of the nodes can be presented that way unless the project is running, and to achieve anything we'd need to introduce some `get_implicit_nodes` virtual method that would report such nodes in each individual case. But silently modifying the tree away from the user's view is not a good idea.

**Steps to reproduce:**
1. Create a `ScrollContainer`.
2. Run the project.
3. Remove all child nodes from the `ScrollContainer`:
```gdscript
	for child in scroll_container.get_children():
		scroll_container.remove_child(child)
		child.queue_free()
```
4. Hover over `ScrollContainer`'s bounding box.

**Minimal reproduction project:**
[bug-scrollcontainer-crash.zip](https://github.com/godotengine/godot/files/4621299/bug-scrollcontainer-crash.zip)

**Comment by Calinou** [comment]
> User scripts should not be able to remove any nodes required by built-in nodes to exist. Like scrollbars in case of ScrollContainer. Calling remove_child on such a node should err and the process should recover and move on.

Can't we just add null checks in the C++ source to solve the issue at hand?

**Comment by pycbouh** [comment]
It may very well be more difficult, but what kind of behavior would we assume to be normal after a user accidentally deletes a node that is needed for the other node to function properly? Do we continue on with a broken `ScrollContainer` or other node of that sort? I can't imagine what type of behavior would be acceptable for the node in question after that.

As a user I'd prefer to be immediately aware that I've done something terribly wrong. Since we don't like Godot crashing in any case, and we'd prefer to recover from any error, yet we can't guarantee any reasonable continued behavior for the node missing its essentials, I'd prefer that the ability to shoot yourself in the foot be blocked completely by extending `remove_child` logic.

**Comment by WiggleWizard** [comment]
Problem with overriding `remove_child` is that it doesn't stop you from `get_child` and calling `queue_free` on it, which would likely cause a similar crash.

I don't think showing all children for a node to function is intuitive really. User will add a `ScrollContainer` and suddenly there's 3 children (each with possibly more children themselves) and wonder why there's extra children they didn't want.

Best approach here is to trap cases where the children are being used and throw an error in the command line without crashing. Alongside this perhaps throw up a Configuration Warning on the node.

**Comment by pycbouh** [comment]
> I don't think showing all children for a node to function is intuitive really. User will add a `ScrollContainer` and suddenly there's 3 children (each with possibly more children themselves) and wonder why there's extra children they didn't want.

Well, this is still the case, only the user finds it out after they run the scene (and maybe something goes awry). So wouldn't it be better to inform beforehand? But I do get that it can be excessive for some, which is why I've suggested some visibility toggle that would hide/show those extra nodes. It can even be off by default. Like the "Show hidden folders" option in Windows' File Explorer, you know. Visually such nodes should be as distinct as possible, of course.

It would be one thing, if the scene tree was not affected and it was just an implementation detail. But the problem is that this implementation detail is "leaking" into the user space.

> Best approach here is to trap cases where the children are being used

Alright, but how do you propose we trap them? It seems to be to the same effect I'm hoping for anyway. We still need to check the node before freeing it or removing it from the parent. I guess both things can happen independently (`remove_child` without freeing it and `queue_free` without explicit removing), so both can be a problem.

**Comment by WiggleWizard** [comment]
> Alright, but how do you propose we trap them? It seems to be to the same effect I'm hoping for anyway. We still need to check the node before freeing it or removing it from the parent. I guess both things can happen independently (`remove_child` without freeing it and `queue_free` without explicit removing), so both can be a problem.

I've developed a control that quietly adds controls and keeps a reference to them in memory, like most nodes do in the engine. Difference being is I listen to their `tree_exited` signal to then set the memory to null, at which point when it tries to use the object in any way, a check for null is first executed. That approach could work well.

**Comment by KoBeWi** [comment]
There's a PR that solves this by making the nodes inaccessible: #30391

**Comment by pycbouh** [comment]
@KoBeWi So the idea is the same, mark them in a specific way and then exclude from user-initiated operations? Also, what's the status? Is it waiting on core contributors' approval?

**Comment by KoBeWi** [comment]
Yes, it's waiting for approval (it got PR meeting label recently).

**Comment by avencherus** [comment]
Confirmed in 3.2

```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] Range::get_value (C:\Godot\Version 3.2\scene\gui\range.cpp:131)
[1] Range::get_value (C:\Godot\Version 3.2\scene\gui\range.cpp:131)
[2] ScrollContainer::_gui_input (C:\Godot\Version 3.2\scene\gui\scroll_container.cpp:92)
[3] MethodBind1<ScrollContainer,Ref<InputEvent> const &>::call (C:\Godot\Version 3.2\core\method_bind.gen.inc:867)
[4] Object::call_multilevel (C:\Godot\Version 3.2\core\object.cpp:764)
[5] Object::call_multilevel (C:\Godot\Version 3.2\core\object.cpp:865)
[6] Viewport::_gui_call_input (C:\Godot\Version 3.2\scene\main\viewport.cpp:1669)
[7] Viewport::_gui_input_event (C:\Godot\Version 3.2\scene\main\viewport.cpp:2265)
[8] Viewport::input (C:\Godot\Version 3.2\scene\main\viewport.cpp:2828)
[9] Viewport::_vp_input (C:\Godot\Version 3.2\scene\main\viewport.cpp:1446)
[10] MethodBind1<Viewport,Ref<InputEvent> const &>::call (C:\Godot\Version 3.2\core\method_bind.gen.inc:867)
[11] Object::call (C:\Godot\Version 3.2\core\object.cpp:922)
[12] Object::call (C:\Godot\Version 3.2\core\object.cpp:848)
[13] SceneTree::call_group_flags (C:\Godot\Version 3.2\scene\main\scene_tree.cpp:275)
[14] SceneTree::input_event (C:\Godot\Version 3.2\scene\main\scene_tree.cpp:431)
[15] InputDefault::_parse_input_event_impl (C:\Godot\Version 3.2\main\input_default.cpp:442)
[16] InputDefault::parse_input_event (C:\Godot\Version 3.2\main\input_default.cpp:260)
[17] InputDefault::flush_accumulated_events (C:\Godot\Version 3.2\main\input_default.cpp:679)
[18] OS_Windows::process_events (C:\Godot\Version 3.2\platform\windows\os_windows.cpp:2548)
[19] OS_Windows::run (C:\Godot\Version 3.2\platform\windows\os_windows.cpp:3243)
[20] widechar_main (C:\Godot\Version 3.2\platform\windows\godot_windows.cpp:162)
[21] _main (C:\Godot\Version 3.2\platform\windows\godot_windows.cpp:184)
[22] main (C:\Godot\Version 3.2\platform\windows\godot_windows.cpp:196)
[23] __scrt_common_main_seh (d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[24] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by KoBeWi** [comment]
The PR I mentioned was merged and these nodes are no longer available (unless you explicitly want it). So this is resolved.
