### ISSUE TITLE
ERROR: Tween was not added to the SceneTree!

### ISSUE THREAD

**Issue by Gamecrazy** [godotengine/godot#38728]
Godot version:
3.2.2 beta2 64

Issue description:

Steps to reproduce:
```
var _animation = Tween.new()

func _init():
	add_child(_animation)

func _enter_tree():
	_animation.start()
```

ERROR: Tween was not added to the SceneTree!
   At: scene\animation\tween.cpp:843

**Comment by akien-mga** [comment]
The error is correct, at that time the `Tween` child node has not entered the scene tree yet.

See the description of the `Node` class about the scene tree entering order for parent/children nodes: https://docs.godotengine.org/en/latest/classes/class_node.html#description

**Comment by akien-mga** [comment]
If you call `_animation.start()` in `_ready`, it should be guaranteed to be called after `_animation`'s own `_enter_tree` and `_ready`.
