### ISSUE TITLE
Some dialogue window open too small

### ISSUE THREAD

**Issue by FeatherAntennae** [godotengine/godot#38726]
**Godot version:**
v4.0.dev.custom_build.e7c9d8187

**OS/device including version:**
Windows 10 Pro 1909 (Build 18363.836)

**Issue description:**
Some dialogue window open too small, sometimes completely collapsing their main content.

Found so far:
- Browse dialogue when creating a new project:
![godot windows tools 64_CDVmB61Znb](https://user-images.githubusercontent.com/52422077/81848585-5c1cb280-9523-11ea-993f-0203ea0f554a.png)
when resized:
![godot windows tools 64_YC6LClyaFG](https://user-images.githubusercontent.com/52422077/81848715-8a01f700-9523-11ea-86a6-062b7240321c.png)

- Orphan Resource Explorer:
![godot windows tools 64_ik3w7YraFv](https://user-images.githubusercontent.com/52422077/81848825-b1f15a80-9523-11ea-94f3-7a63e0ee57e3.png)
when resized:
![godot windows tools 64_B71vd2JskA](https://user-images.githubusercontent.com/52422077/81848844-b87fd200-9523-11ea-9df4-4ddf3008f6a9.png)

**Steps to reproduce:**
- Browse dialogue when creating a new project: 
Create a new project -> Browse
- Orphan Resource Explorer:
Load any project -> Project Menu -> Tools -> Orphan Resource Explorer

**Comment by ThakeeNathees** [comment]
DisplayServer issue, tracker to be added: #37734

**Comment by Anutrix** [comment]
Related to issue 1 of https://github.com/godotengine/godot/issues/37401.

**Comment by Anutrix** [comment]
This is because of the usage of Rect2i at https://github.com/godotengine/godot/blob/163687d17a8a11da3cf1a3595c511a5f8fc94571/scene/main/window.cpp#L995 instead of Rect2.
