### ISSUE TITLE
Engine crashes when replacing text in the script editor

### ISSUE THREAD

**Issue by VedatGunel** [godotengine/godot#38720]
**Godot version:**
v3.2.1 stable
**OS/device including version:**
Windows 10 64 bit, Version 1909
**Issue description:**
Engine seems to freeze and not respond in some cases when I try to replace text in the script editor using the replace menu.
Some observations:

- It only seems to happen when "Selection Only" is selected.
- It only crashes the engine when I try to replace with empty text.
- When I select some text, open the replace menu, try to replace all with a non-empty text, it only replaces the first item. Not sure if this is a separate problem or not.

**Steps to reproduce:**

1. Select some text in your script.
2. Press Control+R to open the replace menu.
3. Find a text that's in your selection, and press "Replace All" to replace them with empty text.

**Minimal reproduction project:**

**Comment by ThakeeNathees** [comment]
Fixed: #37447

**Comment by VedatGunel** [comment]
Didn't think of checking merged PRs. Thanks for the fix!
