### ISSUE TITLE
Marketplace Google Map not working

### ISSUE THREAD

**Issue by rudrrayan** [godotengine/godot#38735]
**Godot version:**
N/A
**OS/device including version:**
Windows 10
**Issue description:**

I cannot find the Godot Marketplace github repos so im uploading the issue here

Hello there,
At the moment, I am attempting to complete my account by 15%, by adding my map location but when I load my settings to set the location, There seems to be an error in loading google maps:

<img width="960" alt="Dashboard – Godot Assets Marketplace - Google Chrome 14_05_2020 11_37_04" src="https://user-images.githubusercontent.com/47331292/81926908-ab71ea00-95da-11ea-9082-86f237c6c6a9.png">

sorry for the rushed crossing out.

Ive also checked the Javascript errors and it shows as follows:

<img width="960" alt="Dashboard – Godot Assets Marketplace - Google Chrome 14_05_2020 11_40_51" src="https://user-images.githubusercontent.com/47331292/81926921-b167cb00-95da-11ea-8d11-e47975b2549c.png">

I am using adblocker, i have tried disabling it but it doesnt work. I am using the latest version of chrome
Can anybody find a fix to this?
**Steps to reproduce:**

go to settings for your shop account, and when going to the map, you will see the bug

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Please read what you are told: https://github.com/godotengine/godot-asset-library/issues/215#issuecomment-628556520

We're not affiliated with this website, it's not for us to fix.
