### ISSUE TITLE
Expose real-time amplitude processing to GDscript

### ISSUE THREAD

**Issue by MinnowMike** [godotengine/godot#3873]
The editor currently processes real-time audio amplitude (energy) and displays it in the Amplitude meter in the top right corner of the editor. It would open many sound-based game possibilities if this logic was exposed to GDScript. Unity exposes this nicely in their FMOD wrapper, it allows you to grab an array of sample amplitudes around the current play marker. From what I can tell, godot already does this in the [compute_band_energies] method of the [bands.c/h] files, but it isn't exposed anywhere to script.

---

int channel = 0;

// similar to SpatialSamplePlayer
AudioSource audio = GetComponent<AudioSource>();

// user defined array to fill with sample amplitude values
float[] spectrum = new float[256];

// Fill the 256 array with audio sample amplitudes from the current play marker
audio.GetSpectrumData(spectrum, channel, FFTWindow.BlackmanHarris);

---

New user, but loving the structure so far, Thanks!
Michael

**Comment by trollworkout** [comment]
This is planned for 2.1 if I am not mistaken. The technical term for it is different but same idea. I think they call it audio routing which from what I understand it means exposing stream data as it plays which can be routed trough processes making visualizers, audio filters and much more.

**Comment by MinnowMike** [comment]
That's great news, thanks for the info! We have plans to take full advantage of it whenever it comes to fruition.

**Comment by neikeq** [comment]
We was discussing about this today on irc, and we decided to move this to 2.2

**Comment by reduz** [comment]
this is much simpler to do now with the new audio engine, but it wasn't done. Kicking to 3.1 or unless someone wants to do it.

**Comment by SL-RU** [comment]
It will be very useful feature in many games.

**Comment by Calinou** [comment]
@SL-RU Please refrain from bumping issues without significant new information; use the +1 reaction button on the first post instead.

**Comment by LikeLakers2** [comment]
I'm currently working on a audio-reactive layout for videos using Godot. This would be extremely useful and would let me save some time instead of having to record the data from Unity or get the data through some manual means. I hope this gets in for 3.1, if not earlier than that.

**Comment by MinnowMike** [comment]
I learned that the AudioStreamPlayer seems to expose the raw audio data in stream.data as a PoolByteArray, and started thinking this might be possible now. I wrote a working mock-up of the idea in RayLib, then tried to reproduce it in GDScript but got stuck on trying convert the raw audio PoolByteArray to usable samples (PoolRealArray? but that doesn't seem to be exposed to GDScript). StreamPeerBuffer is supposed to provide array conversion, but I don't understand how to use it. I can calculate a sufficiently accurate play head position using the sample rate and a calculated elapsed time to give me a position in the array to grab samples, but don't know what the bytes need to be converted to or how to convert.

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by KoBeWi** [comment]
Isn't it this? https://godotengine.org/article/godot-32-will-get-new-audio-features

**Comment by SL-RU** [comment]
> Isn't it this? https://godotengine.org/article/godot-32-will-get-new-audio-features

Yes, this is it!

**Comment by KoBeWi** [comment]
So this can be closed.
