### ISSUE TITLE
Renaming imported .csv file to .txt leading to not packing the file in the export package

### ISSUE THREAD

**Issue by YLL** [godotengine/godot#38733]
**Godot version:** Godot_v3.2.1-stable_win64

**OS/device including version:** Windows 10 Pro 18363.778

**Issue description:** 
As I mentioned in the comments of #38245
Trying to rename an imported .cvs file to something like .txt dose not treat the corresponding .import file and it's content properly, which leads to somehow missing the renamed file in the export process.

**Steps to reproduce:**
1. Put an empty file named "xxx.csv" into the project root dir.
2. Select the very file in the FileSystem panel and change the "Import As:" option to "CSV" in the Import panel, then click "Reimport".
3. After the reimport process, select the very file in the FileSystem panel, right click on it and choose "Rename" to rename the file name to "xxx.txt".
4. The file disappers in the FileSystem panel, but the "xxx.txt.import" file lives in the project, with something like:

> [dep]
source_file="res://xxx.csv"

5. In any scripts try to run the following code.

> `print(var2str(File.new().file_exists("res://xxx.txt")))`

6. In Editor mode, you will see "true" in the Output panel. In any exported game, you will see "false" in the console even if the "include_filter" is set to "*.txt" and "export_filter" is "all_resources" in the export_preset.cfg.
7. Try to delete the "xxx.txt.import" file in the project dir, and export again. you will see "true" in the console in the exported game.

**Minimal reproduction project:** could reproduce in an empty project

**Comment by TheDuriel** [comment]
verify that your filter is `*.txt` not `.txt`

**Comment by YLL** [comment]
> verify that your filter is `*.txt` not `.txt`

@TheDuriel 
I'm pretty sure it's `*.txt ` like I mentioned in step 6 of the issue reproduce instructions.
Cause in step 7, the `.txt` file will be accessable **ONLY** by deleting the corresponding `.import` file.
You can try to just do the export with `Export PCK/ZIP` and you'll find that neither the `.csv` or the renamed `.txt` file will be in the exported `zip` file.
Neither in the root dir of the `zip` file nor in the ".import" dir. But you'll find the `.import` file of the `.csv` or the renamed `.txt` file in the `zip`.
**Only** by deleting the `.import` file, then the txt file will be collected and packed into the pck/zip normally.
It's simple, just try with an empty project and export some zip packs and you'll see. It happens because of the `.import` file is not properly updated, or maybe it just needs to be gone after renaming an asset's extension to a type that doesn't need any import operation.

**Comment by akien-mga** [comment]
Fixed by #47268.
