### ISSUE TITLE
Production crashes with GodotPayments on Android

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#38744]
**Godot version:**
3.2.1

**OS/device including version:**
Android devices

**Issue description:**
We released a game using the godot engine last week and our users experience a lot of crashes, which get reported in the google play interface:
 
```
java.lang.NullPointerException: at 
org.godotengine.godot.GodotPaymentV3.setAutoConsume (GodotPaymentV3.java:180) at 
org.godotengine.godot.GodotLib.step (Native Method) at org.godotengine.godot.GodotRenderer.onDrawFrame (GodotRenderer.java:51) at 
android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1573) at 
android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1272) 
```
 
I wasn’t able to reproduce this issue myself yet and sadly have no other infos. From the reviews it doesn’t get clear when the crashes are occurring.
 
Here the code part where the setAutoConsume function is called:
 
```
func _ready():
                pause_mode = PAUSE_MODE_PROCESS
                # check for android
                if Engine.has_singleton("GodotPayments"):
                               payment = Engine.get_singleton("GodotPayments")
                               currentMode = modes.Android
                               payment.setAutoConsume(false)
                               print("Using Android IAP")
```

I implemented an 
`if payment:` check before calling setAutoConsume, but why is null anyway?

I also have a lot of crashes with this log:

```
java.lang.NullPointerException: 
 
  at org.godotengine.godot.GodotPaymentV3.<init> (GodotPaymentV3.java:71)
 
  at org.godotengine.godot.GodotPaymentV3.initialize (GodotPaymentV3.java:63)
 
  at org.godotengine.godot.GodotLib.setup (Native Method)
 
  at org.godotengine.godot.Godot$2.run (Godot.java:325)
 
  at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1502)
 
  at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1272)
```

There is no init function I'm calling in the code, so I can't implement a check there
 
Thanks for your support,
Tobias La

**Comment by akien-mga** [comment]
Can you test Godot 3.2.2 beta 2? It might fix this issue.

**Comment by Tobi-La** [comment]
Is the beta version save for production? I don't want to risk introducing new bugs with our first update, we already have enogugh :D

**Comment by Calinou** [comment]
@Tobi-La It might fix the bug you're encountering, so it's worth trying.

**Comment by akien-mga** [comment]
It should be fairly safe, but you should of course do some initial QA before deploying to production.

Note also that the syntax changed to enable GodotPayments: https://github.com/godotengine/godot/issues/38581#issuecomment-626133804
It is now done in the Export Preset for Android, and you can remove it from the `android/modules` project setting. The singleton is also now just `GodotPayments` instead of `GodotPaymentsV3`.

**Comment by lawnjelly** [comment]
Also double check your permissions in your Android export. It may not be causing your problem, but it is a very common reason for errors on Android (seems like > 90%) so worth mentioning.

**Comment by HEAVYPOLY** [comment]
@akien-mga  @m4gr3d told me "yes, it's a 1:1 replacement with additional bug fixes.
The name to use in your scripts should be GodotPayment, instead of GodotPayments.
The documentation will be updated accordingly."

Should we use GodotPayment or GodotPayments in scripts?

**Comment by akien-mga** [comment]
See #38749 - my understanding is that the new name for the singleton is `GodotPayment` (without s), and it's the same name for the plugin.

In 3.2.1 and earlier, the module was `org/godotengine/godot/GodotPaymentV3` and the singleton was `GodotPayments` (with an s).

**Comment by HEAVYPOLY** [comment]
I'm trying to get GodotPayment working with 3.2.2 beta.  In export options I've added "GodotPayment" to plugins text field, Also switched singleton to "GodotPayment" in my scripts.

![image](https://user-images.githubusercontent.com/24432677/82386878-6d196800-99ea-11ea-80d8-0c2c933bb28b.png)

![image](https://user-images.githubusercontent.com/24432677/82388120-98518680-99ed-11ea-9d11-ca826545b2ca.png)

It's not finding the GodotPayment singleton in game...is there something else I'm missing?

This same code was working with "GodotPayments" singleton + android module GodotPaymentV3

**Comment by m4gr3d** [comment]
@HEAVYPOLY can you provide a copy of the generated apk. It could be that your build template is not properly setup.

**Comment by m4gr3d** [comment]
Of course, if you can reproduce the issue in a sample project and share it, that'd be even better.

**Comment by HEAVYPOLY** [comment]
Here's the apk
https://www.dropbox.com/s/ev1t4gty0up7ksb/HEAVYPAINT_143.apk?dl=0

**Comment by HEAVYPOLY** [comment]
Should "Use Custom Build" be on or off?

**Comment by m4gr3d** [comment]
The apk is provided is missing the `GodotPayment` manifest entry, so something is definitely wrong with your build setup. 

> Should "Use Custom Build" be on or off?

The `GodotPayment` plugin doesn't require `Use Custom Build` to be enabled, so you can disable it if you're not using any other plugins.
For any other plugins besides `GodotPayment`, `Use Custom Build` is required to use them.

**Comment by HEAVYPOLY** [comment]
Here are my permissions settings which worked before. 
![image](https://user-images.githubusercontent.com/24432677/82390138-be2d5a00-99f2-11ea-8485-e2a16d2fd3d4.png)

How do I add the GodotPayment manifest entry?

**Comment by m4gr3d** [comment]
It should be automatic if the `res://android/` directory is properly setup.
If you only use the `GodotPayment` plugin, try disabling `Use Custom Build` and regenerate the apk.
If you use other plugins, try deleting and recreating the `res://android` directory and regenerate the apk.

**Comment by HEAVYPOLY** [comment]
Seems to be working now, I started over from scratch.  I checked "Use Custom Build" on last attempt, maybe that messed it up.

**Comment by HEAVYPOLY** [comment]
Tried again with 3.2.2.rc1 and getting this error: 

enabled "Use Custom Build" and "GodotPayment" plugin following the new instructions from 3.2.2.rc1 release news
![image](https://user-images.githubusercontent.com/24432677/84586299-365a2600-adcd-11ea-9dcb-254252b95807.png)

**Comment by m4gr3d** [comment]
@Tobi-La Based on the conversation here and the fact that the [GodotGooglePlayBilling](https://github.com/godotengine/godot-google-play-billing) is now stable, this issue seems to be obsolete.
Can you reopen if that's not the case.

Thanks!
