### ISSUE TITLE
Shader Time in Android

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#3874]
I write a water shader for my game I used TIME to pan around the shader , it was doing ok in pc ,linux ,osx but when I export it to android after a few minutes the shader movement was lagging but my fps was 60  I wrote a uniform for time and used it instead of TIME and  in gdscript I set the time uniform in _process func  , but after afew minutes I saw the lag again. so I wrote it this way

```
 var time =0
 func _process(delta):
    time+=delta
    set_shader_time(time) 
    if time > 10 :
       time = 0 
```
I suspect the problem is that after sometime the TIME variable in shader becomes too large to handle.
I will support a test project.

**Comment by reduz** [comment]
floats in fragment programs on android are all 16 bit floats (because not
all platforms support 32 bits), just reset the counter every once in a
while and send it back to 0. I think TIME does that too, you can configure
it in project settings
