### ISSUE TITLE
Godot cannot open project on other display with a certain font size

### ISSUE THREAD

**Issue by DanielZTing** [godotengine/godot#38741]
**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
Operating system and version: macOS Catalina 10.15.4 19E287 x86_64
Device: MacBookAir8,1 with Intel i5-8210Y (4) @ 1.60GHz and scaled to "Looks
GPU: Intel UHD Graphics 617

**Issue description:**
OK, this has got to be the *weirdest* bug I've ever encountered, but here goes...
If I add a Label node with the Hack font at exactly size 50 on my laptop display, I will not be able to open my project the next time I start up Godot on my external monitor, and vice versa. My laptop display is 2560x1600 scaled to "Looks like 1680x1050" mode. My monitor is the DELL U3014 at 2560x1600 native resolution.

**Steps to reproduce:**
1. Create empty project on laptop display
2. Download [the following font](https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip) and drop Hack-Regular.ttf file into the editor
3. Add a Label node and select it
4. In the inspector, go to Custom Fonts > Font > New DynamicFont
5. Click on DynamicFont and in the submenu that appears, Font > Font Data > Load > and choose Hack
6. Under the DynamicFont's Settings submenu, change Size to 50
7. Save scene and select it as the default when run
8. Quit Godot completely and open Project Manager on external monitor
9. Select project, it will get stuck at the splash screen with the spinning pinwheel

This is a lot so let me know if you'd like me to provide a screen recording of what I mean.

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/4629929/bug.zip)

**Comment by Calinou** [comment]
@DanielZTing Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by DanielZTing** [comment]
Can no longer reproduce on v3.5.stable.official [991bb6ac7]. FWIW I'm on 1920x1080 instead of 2560x1600 but you can feel free to close this.
