### ISSUE TITLE
Slider dot in settings stays on screen after window is closed

### ISSUE THREAD

**Issue by DanielZTing** [godotengine/godot#38740]
# Platform
Operating system and version: macOS Catalina 10.15.4 19E287 x86_64
Godot version: v3.2.1.stable.official
Device: MacBookAir8,1 with Intel i5-8210Y (4) @ 1.60GHz
GPU: Intel UHD Graphics 617

# Steps to reproduce
1. Open any project
2. Open Project > Project Settings...
3. Find any setting with a slider (example: General > Display > Window > Width)
4. Hover the mouse cursor over the small circular slider dot
5. Press escape key to close Project Settings window
6. The dot stays onscreen

**Comment by KoBeWi** [comment]
Hehe
![VEEoZb9kJ6](https://user-images.githubusercontent.com/2223172/81962516-1e4b8700-9614-11ea-8217-f7a708d241d0.gif)
