### ISSUE TITLE
Importing FBX of a non-Unicode encoded path causes Assimp throws error

### ISSUE THREAD

**Issue by FIF15** [godotengine/godot#38745]
**Godot version: 3.2.1**

**OS/device including version: Windows 10**

**Issue description:**
I'm using a non-English Windows system whose default encoding is not Unicode. However it turns out Assimp assumes the input path is in UTF8 encoding which causes a error when I importing a FBX of a non-Unicode encoded path.

see `/thirdparty/assimp/code/Common/DefaultIOSystem.cpp, line 86`, where `Utf8ToWide` is applied to the input path:
```CPP
bool DefaultIOSystem::Exists(const char* pFile) const
{
#ifdef _WIN32
    struct __stat64 filestat;
    if (_wstat64(Utf8ToWide(pFile).c_str(), &filestat) != 0) {
        return false;
    }
#else
    FILE* file = ::fopen(pFile, "rb");
    if (!file)
        return false;

    ::fclose(file);
#endif
    return true;
}
```

One solution was to convert the path to UTF8 encoding before call the Assimp API, where I found `String::utf8()` is very handy. I just need to change `/modules/assimp/editor_scene_importer_assimp.cpp, line 150` to:
```CPP
String g_path = ProjectSettings::get_singleton()->globalize_path(p_path);
aiScene *scene = (aiScene *)importer.ReadFile(g_path.utf8().ptr(), post_process_Steps);
```
and the problem is solved.

**Comment by fire** [comment]
@akien-mga @RevoluPowered We are in the process of testing a new revision of the fbx importer. I think patching the existing system is worth doing. Will look into it.

**Comment by MCrafterzz** [comment]
@fire are you still working on this?

**Comment by fire** [comment]
We are prioritizing getting the list of pr items in FBX like blend shape support and locators. 

Not working on this.

**Comment by MCrafterzz** [comment]
> We are prioritizing getting the list of pr items in FBX like blend shape support and locators.
> Not working on this.

I could send a quick pr with the fix suggested in the original comment.
