### ISSUE TITLE
glTF2s with blend weights being zero is being rejected

### ISSUE THREAD

**Issue by fire** [godotengine/godot#38751]
**Godot version:**
3.2 stable from Steam

**OS/device including version:**
Win10

**Issue description:**

I had a model with blend shapes defined but with 0 blend weights. It is not required to be in the model format and should not be rejected with a parse error.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#mesh

```
ERR_FAIL_COND_V(mesh->blend_weights.size() == 0, ERR_PARSE_ERROR);
```

https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/editor/import/editor_scene_importer_gltf.cpp#L2393

The fix is to be determined.

**Steps to reproduce:**

Import a gltf2 with the blend weights array deleted and it will fail to import.

**Minimal reproduction project:**

[38751.zip](https://github.com/godotengine/godot/files/4634226/38751.zip)

From https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube but with https://github.com/KhronosGroup/glTF-Sample-Models/blob/5aec133dbaf543f9bcb6cb79de9966bf9530c2fe/2.0/AnimatedMorphCube/glTF/AnimatedMorphCube.gltf#L235-L238 deleted.

**Comment by slapin** [comment]
aw these assert reverts :( totally flip my brain...

**Comment by slapin** [comment]
Anyway are you sure these checks are necessary? meshes work fine without weights.
