### ISSUE TITLE
New Lightmapper denoising library includes deep neural network library that does not support 32 bits.

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#38759]
**Godot version:** master (00949f0)

**OS/device including version:** 32 bit platforms.

**Issue description:** The new lightmapper #38386 introduced a new denoising library: [oidn](https://github.com/OpenImageDenoise/oidn) that includes a Deep Neural Network library: [oneDNN](https://github.com/oneapi-src/oneDNN) that only supports 64 bits:
> oneDNN supports platforms based on the following architectures:
>- Intel 64 or AMD64,
>- Arm 64-bit Architecture (AArch64).

**Steps to reproduce:** Try compile master (with #38757 to avoid an earlier compilation error) using: `scons -j8 platform=windows tools=yes bits=32` causes an assertion error:
> static_assert(sizeof(void*) == 8, "Intel(R) MKL-DNN supports 64 bit only");

**Minimal reproduction project:** N/A

Furthermore it includes a warning about limited support on Arm processors.
> WARNING
Arm 64-bit Architecture (AArch64) support is experimental with limited testing validation.

**Comment by akien-mga** [comment]
Its build should be restricted to `tools=yes` and desktop platforms, it won't be used in templates and even if we enable Android editor builds, it doesn't make sense to bake lightmaps on a mobile device.

I guess we can also disable it on 32-bit desktop builds.
