### ISSUE TITLE
heavy CPU usage, even with empty project.

### ISSUE THREAD

**Issue by jeangit** [godotengine/godot#38756]
**Godot version:** godot-bin-mono 3.2.1 (this one: https://downloads.tuxfamily.org/godotengine/3.2.1/mono/Godot_v3.2.1-stable_mono_x11_64.zip)

**OS/device including version:** archlinux, updated. Running Xorg.

**Hardware:** i5-3570 CPU (3.40GHz), nvidia geforce 460 GTS with nvidia proprietary drivers.

**Issue description:** heavy CPU usage. Around 318% with vsync enabled. If i remove vsync and limit FPS (debug settings) to 60, i get around 60% of cpu usage.

**Steps to reproduce:** open new project, creates node2d, run.

**Minimal reproduction project:**

[stress_test.zip](https://github.com/godotengine/godot/files/4634844/stress_test.zip)
![stress](https://user-images.githubusercontent.com/7419045/82059605-8d81b380-96c6-11ea-849f-e024ac258828.png)

**Comment by eon-s** [comment]
Does it happens with non-mono version too?

**Comment by Zylann** [comment]
If you turn on the update spinner in editor settings, does it keep spinning? (that's often a good indicator to check if the editor constantly redraws because something pings the renderer)

**Comment by jeangit** [comment]
Sorry, i had a setup problem with my config.
As it's an old PC (my Geforce 460GTX is 10 years old), the driver support has been removed from the main nvidia driver, and even from the community driver. I have to use AUR (arch user repo) for finding the driver which recognize my card.
That said, you have all guessed that after my last reboot (about three per year, i use hibernation and it's rock steady now), i had lost my nvidia driver after a kernel upgrade.
And … and i was then using the horrible MESA driver instead of nvidia DRM module.

I'm sorry for the waste of time. Thanks to Zylann with his magic spinner, it helped me to understand that something was wrong with my setup. As i'm only typing text, reading doc and surfing most of the time, the 2D FB support was enough and i hadn't noticed something fishy.

Thank for your help.
