### ISSUE TITLE
Incorrect capabilities described in LSP "initialize" method

### ISSUE THREAD

**Issue by ofrank123** [godotengine/godot#38766]
**Godot version:**
3.2.2 beta
**Issue description:**
The language server's `initialize` method mistakenly reports that it support the `textDocument/willSave` and `textDocument/didSave` methods, when it does not.  As a result, users who use text editors that report error messages will constantly get error messages while developing.
**Steps to reproduce:**
Load a project in godot, open with emacs and lsp-mode (or any other language server client that reports these errors)

**Comment by akien-mga** [comment]
Fixed by #38767 (and cherry-picks for the `master` branch).

**Comment by Mo0dy** [comment]
The errors still persist for me.

**Comment by ofrank123** [comment]
Could you send the error message/steps to reproduce?  It appears to be fixed on my end and for others.

**Comment by Mo0dy** [comment]
The lsp starts up with two warnings:
Warning (lsp-mode): Unknown notification: gdscrip_client/changeWorkspace
Warning (lsp-mode): Unknown notification: gdscript/capabilities

And this message:

LSP :: gdscript:nil initialized successfully

And wheneven I try to do something I get Errors like this:

Error processing message (lsp-unknown-message-type #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("error" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("code" -32601 "message" "Method not found: $/cancelRequest")) "id" nil "jsonrpc" "2.0"))). [2 times]

Steps to reproduce:
Use lsp mode with gdscript mode and doom emacs.

**Comment by ofrank123** [comment]
Okay, that's a new issue, I gotta figure out that $/cancelRequest method, but I knew that the startup warnings weren't fixed yet.
