### ISSUE TITLE
Sprite.RegionRect doesn't display its value in editor

### ISSUE THREAD

**Issue by genete** [godotengine/godot#3876]
Mac OSX 10.10.3. Godot 2.0 release version.

Sprite.RegionRect doesn't display its value in editor. The panel editor displays 0,0,0,0 and when you click on it to edit it it displays 0,0,50,50

I was following the TileSet tutorial and so I did this:
1) Created a Node
2) Added a Sprite to it. Renamed the sprite and saved the Scene
3) Although not mentioned in the tutorial I clicked the Sprite Region Editor button and selected the first tile (wall) located at 0,0,50,50
4) Changed the Sprite.Region value to "on". Editor reflects correctly the change and only wall was visible.
5) My surprise was that RegionRect seems to not change from 0,0,0,0

![sprite regionrectbug](https://cloud.githubusercontent.com/assets/346755/13388699/842283d4-dec2-11e5-841c-fa2091465e86.png)

**Comment by volzhs** [comment]
Did you hit <kbd>Enter</kbd> after change value?

**Comment by genete** [comment]
I didn't change value using he pop up. I used the Sprite Region Editor window. After use the Sprite Region Editor window, new values aren't reflected on the RegionRect compact display, although as you can see in the image, internal values are correct. 
Now I can't press Enter because once you load the scene again it looks fine.
