### ISSUE TITLE
Build error main/default_controller_mappings.gen.cpp

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#38773]
**Godot version:**
4.0 master

**OS/device including version:**
Win 10

**Issue description:**
When building master 6815bf42b38c7c3dfde419d86dbc1bf012b035b2 from scratch:

![image](https://user-images.githubusercontent.com/44248915/82108246-7de98580-972d-11ea-8b88-cecb1b3ebaa1.png)

Installing pywin32 does not affect the issue.

**Comment by nathanfranke** [comment]
https://github.com/godotengine/godot/issues/20074
Have you tried git clean?

**Comment by TheDuriel** [comment]
No change. This is as clean as it gets without making a whole new local dir.

**Comment by akien-mga** [comment]
`git clean -fxd` will fix it. Or just remove that old .gen.cpp file.
