### ISSUE TITLE
Unit Test in sln C# solution failed : SecurityException

### ISSUE THREAD

**Issue by evan-boissonnot** [godotengine/godot#38775]
**Godot version:**
3.2.1 mono stable

**OS/device including version:**
windows 10 pro

**Issue description:**
Creating a unit test project in Visual studio solution.
Adding a unit test to my DialogBox.
Launching and getting this error : 
_**ECall Methods Must Be Packaged Into A System Module**_

**Steps to reproduce:**
Creation a DialogBox Node with DIalogBox.cs

See this code below :
using Godot;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

/// <summary>
/// Dialog box : display content text and a texture animated sprite
/// </summary>
public class DialogBox : Node2D
{
    #region Fields
    private List<string> _messageList = new List<string>();
    private int _currentPartOfMessage = 0;
    #endregion

    #region Public methods
    public override void _Ready()
    {
        
    }
    #endregion

    #region Internal methods
    #endregion

    #region Properties

    /// <summary>
    /// Content message to display
    /// </summary>
    public string Message
    {
        get
        {
            string content = string.Empty;

            if (this.CurrentPartOfMessage < this.MessageList.Count)
            {
                content = this.MessageList[this.CurrentPartOfMessage];
            }

            return content;
        }
    }

    /// <summary>
    /// Index of the part of the message in the message list
    /// </summary>
    public int CurrentPartOfMessage { get => this._currentPartOfMessage; private set => this._currentPartOfMessage = value; }

    /// <summary>
    /// List of message text as one full message to be displayed in X steps
    /// </summary>
    [Export]
    public List<string> MessageList { get => this._messageList; set => this._messageList = value; }
    #endregion
}

**Comment by van800** [comment]
see https://github.com/godotengine/godot-proposals/issues/432

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/432, since this is more of a missing feature/documentation than a bug.

**Comment by evan-boissonnot** [comment]
Ok,  taht's right : if the next feature will drop this bug, I'm ok :)

**Comment by evan-boissonnot** [comment]
Hug I retry unit tests, and really I'm not ok, it's not a missing doc, it's really a bug for me.
Why am I not able to create a unit test as usual ?

**Comment by van800** [comment]
Hey @evan-boissonnot, you may write me on discord `van800#9412`. I can explain you the difficulty with UnitTesting support.
