### ISSUE TITLE
HTML5 Web player broken in Brave Browser

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#38788]
**Godot version:**
<img width="614" alt="Screenshot 2020-05-16 at 23 40 02" src="https://user-images.githubusercontent.com/100964/82126785-93fb5280-97ce-11ea-944c-5ef71ec00d82.png">

**OS/device including version:**
<img width="330" alt="Screenshot 2020-05-16 at 23 40 18" src="https://user-images.githubusercontent.com/100964/82126788-9b226080-97ce-11ea-81f1-7df7a78bc92c.png">

**Issue description:**
HTML5 Web player fails in [Brave Browser](http://brave.com/) (Chromium), but works in latest chrome.

Brave is a Chromium based browser, I've been using it for a while. On every site with a Godot game I get the following error:
<img width="1066" alt="Screenshot 2020-05-16 at 23 39 19" src="https://user-images.githubusercontent.com/100964/82126808-c73de180-97ce-11ea-9eef-b10f265f865a.png">

<img width="1069" alt="Screenshot 2020-05-16 at 23 39 38" src="https://user-images.githubusercontent.com/100964/82126812-cc9b2c00-97ce-11ea-9540-a7e19480c18d.png">

Whereas on the latest Chrome the same game works correctly:

<img width="1071" alt="Screenshot 2020-05-16 at 23 41 52" src="https://user-images.githubusercontent.com/100964/82126815-d58bfd80-97ce-11ea-8239-6a1fae705e79.png">

**Steps to reproduce:**
1. Install Brave browser
2. Open [this game](https://tavurth.itch.io/godot-html5-test)

**Minimal reproduction Example:**
https://tavurth.itch.io/godot-html5-test

**Minimal reproduction project:**
https://github.com/tavurth/godot-html5-brave

**Additional notes**
This bug only occurs when Brave's tracker protection is enabled, and it cites two errors:
<img width="406" alt="Screenshot 2020-05-16 at 23 48 21" src="https://user-images.githubusercontent.com/100964/82126945-cf4a5100-97cf-11ea-9ca1-14d93e4da67c.png">

**Comment by tavurth** [comment]
From the console error message, I assume that this bug is related to Brave rejecting the media devices fingerprinting and Godot doesn't know how to handle that, and throws the error:

```log
exception thrown: TypeError: Cannot read property 'length' of null,TypeError: Cannot read property 'length' of null
    at lengthBytesUTF8 (https://v6p9d9t4.ssl.hwcdn.net/html/2266777/index.js:7:8850)
    at stringToNewUTF8 (https://v6p9d9t4.ssl.hwcdn.net/html/2266777/index.js:7:200778)
    at _glGetString (https://v6p9d9t4.ssl.hwcdn.net/html/2266777/index.js:7:263514)
    at RasterizerStorageGLES3::get_video_adapter_name() const (wasm-function[14471]:0x2b2e54)
    at VisualServerRaster::get_video_adapter_name() const (wasm-function[28718]:0x70eb3a)
    at RasterizerGLES2::initialize() (wasm-function[35071]:0x8a2f8f)
    at VisualServerRaster::init() (wasm-function[28679]:0x70e571)
    at OS_JavaScript::initialize(OS::VideoMode const&, int, int) (wasm-function[37688]:0x9415bc)
    at Main::setup2(unsigned long long) (wasm-function[54008]:0xb333fb)
    at Main::setup(char const*, int, char**, bool) (wasm-function[54007]:0xb33096)
```

**Comment by Faless** [comment]
> From the console error message, I assume that this bug is related to Brave rejecting the media devices fingerprinting

Well, then maybe they should return an empty string on every device instead of breaking the standard and returning null.

**Comment by tavurth** [comment]
@Faless should I close this and report the bug on their site?

**Comment by Faless** [comment]
@tavurth I think this should be reported upstream in the browser issue tracker, yes.

**Comment by tavurth** [comment]
Thank you @Faless! I've submitted there instead.
