### ISSUE TITLE
Deleting a TreeItem does not remove it from display

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#38787]
**Godot version:** 3.2.1

**OS/device including version:** Windows 10

**Issue description:**

Deleting a TreeItem via script removes it, but the display still shows the TreeItem until one interacts with the Tree-Node.

This happens in both cases: TreeItem.free() and TreeItem.remove_child(childTreeItem)

**Steps to reproduce:**

1.a. Load and start the Minimal reproduction project
1.b. Now the windows shows a button at the top and a Tree-Node with one TreeItem-Entry at the bottom of the window.
2.a. Click on the Button at the top of the window to delete the TreeItem via TreeItem.free()
2.b. I would expect that now the item disappears
3.a. Move the mouse over the Tree-Node in the lower part of the window
3.b. Now the TreeItem disappears

**Minimal reproduction project:**

[TreeItemDeleteBug.zip](https://github.com/godotengine/godot/files/4638870/TreeItemDeleteBug.zip)

**Comment by KoBeWi** [comment]
Tree should probably detect when an item is removed and update.

**Comment by Sauermann** [comment]
As a workaround, after deleting a TreeItem, I was able to trigger a redisplay of the Tree by the following command:

    TREE.hide_root = TREE.hide_root

**Comment by 7hedubz** [comment]
You can also  call the `update()` function on the tree after removing a node.

**Comment by ondesic** [comment]
You can also use `treeRootItem.Select(0)`
I only notice this when I delete a child directly attached to the Root TreeItem.
Any children attached to children TreeItems delete immediately

**Comment by me2beats** [comment]
Is this not a feature?
Not sure but imagine if you do it in a loop - wouldn't that cause performance or flickering issues?

It seems I ran into something like this too, but I just called `update()` and it worked.

**Comment by KoBeWi** [comment]
Redrawing doesn't happen immediately, so loops aren't a problem.

**Comment by ondesic** [comment]
Removing an item from a tree should operate like the ItemList, VScrollContainer etc.  They all show that the item is removed automatically and you don't have to update() them manually.

**Comment by KoBeWi** [comment]
The problem here is that the Tree only stores pointer to the root TreeItem, the items are separate objects. If this turns out unfeasible to fix, we should at least document that you need to manually `update()` the Tree after deleting item.

**Comment by Sauermann** [comment]
Thank you for resolving this issue.

**Comment by Grilvhor** [comment]
Damn I've been scratching my head on this for more than an hour.
**Calling update() works fine.**

Some hint about this in tree or treeItem doc in engine would be appreciated. :)

The description for TreeItem already says this : 
You can remove a treeItem by using Object.free().

Just need to add something like this:
You then need to call Tree.update() to instantly stop displaying any removed item.

I guess this could be in another issue, feel free to tell me if I should create one.

**Comment by KoBeWi** [comment]
@Grilvhor What version are you using? This was fixed in 3.4

**Comment by Grilvhor** [comment]
@KoBeWi 

Thanks for your answer.
I'm using 3.3.4.
I didn't know about the .4 version, I'll check it out, thanks a lot!

Glad to hear this has been fixed in 3.4, gonna check patchnote too.

**Comment by Grilvhor** [comment]
@KoBeWi 
So i'm now on 3.4.1 and the issue is not resolved in my experience.

I noticed than tree updates when a new item is created but not when an item is deleted.
Should I upload my project? ( it's a really small one )

**Comment by KoBeWi** [comment]
@Grilvhor A reproduction project would be helpful. I tested it to make sure it's fixed and I can't reproduce the issue.
