### ISSUE TITLE
Dict get methods wont accept Variant with a String value

### ISSUE THREAD

**Issue by MrJDR** [godotengine/godot#38785]
**Godot version:**
3.1.1
**OS/device including version:**
MBP mid 2014 OSX 10.15.4 (Catalina)
**Issue description:**
get methods won't accept Variants with a String value.
Methods require a "" string to be declared and not a var with a string value. Prevent loops from accessing values from dictionaries with this syntax. 

**Steps to reproduce:**
See photo or....

1) Create an array of Vector3 in singleton
2) Create a Dictionary in a singleton using the "Vector3" as key(s) and "String_Name" as value(s)
3) Create another script
4) Call dictionary within a var 
5) Call array within a var
6) create a for loop that calls every key in the dictionary
7) create a var for each key called and convert to a String
8) Use vardict.get(varkey) or vardict[(String(varKey))] to return the value of the key in the dictionary
9) Observe that value is passed but get refuses to use it as key in get method

Note: When var.get("key"), vardict.key, or vardict["key"] is used method calls appropriate value as intended.

**Minimal reproduction project:**
<img width="969" alt="Screen Shot 2020-05-16 at 8 36 16 AM" src="https://user-images.githubusercontent.com/12093202/82124654-60301680-9755-11ea-9d72-83d937db7a6d.png">

<img width="774" alt="Screen Shot 2020-05-16 at 9 27 18 AM" src="https://user-images.githubusercontent.com/12093202/82124961-8d7dc400-9757-11ea-813d-718aa2a52ae0.png">

**Comment by ChibiDenDen** [comment]
Im not 100% sure I understand the issue or what you are trying to achieve here,
but it seems like your dictionary key is "(0,1,1)" and the key you look for is "(0, 1, 1)"
the difference is the spaces after the commas, can you try to add spaces after the commas in your dictionary building (line 58) and see if it solves the issue?

**Comment by MrJDR** [comment]
That did solve the issue! Yet, Im curious as to why the engine is spacing out my vector3? Im am passing the same value from the array to the dictionary, which is literally copy and paste (photo 2).

But overall... THANK YOU for solving my 3-day headache!!!!

**Comment by ChibiDenDen** [comment]
You are using the String conversion method of the vector to generate the lookup key, which formats the output with spaces.

Glad to help

**Comment by Calinou** [comment]
By the way, Dictionary allows you to use any Variant type as a key if I'm not mistaken. So you could use Vector3 directly.

**Comment by MrJDR** [comment]
> By the way, Dictionary allows you to use any Variant type as a key if I'm not mistaken. This means you could use Vector3 directly, without converting it to a String beforehand.
> 
> Anyway, I'll close this as the original issue has been solved.

Should another bug be create for the engine inserting space within a string post processing?

**Comment by Calinou** [comment]
@MrJDR It's known that there are some inconsistencies within string conversion methods, but these can't be solved without breaking compatibility.
