### ISSUE TITLE
Incorrect saving of files.

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#3878]
**Operating system or device:** Windows 8 / ArchLinux

**Issue description**: 
In assembled form, the draft can't save variables to a file. Or doesn't record, or not creates a file. In the editor everything works fine.

**Steps to reproduce:** 
1. export demo "read_write" (simple demo)
2. Running with console

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/sh/4tut8st36k8oejn/AACaOj5sAZPHqJfnVR9SIyu9a?dl=0

**Comment by akien-mga** [comment]
Please answer the above question, as for now there's nothing we can do on this issue, it's hard to understand what the problem was/is.

**Comment by reduz** [comment]
I think he means that he can't save files to res:// paths, which is intended. Use the user:// path to save files when exporting
