### ISSUE TITLE
Setting Wieght/Mass for an Individual RigidBody2D does not work

### ISSUE THREAD

**Issue by ZingBlue** [godotengine/godot#38786]
**Godot version:**
Master
**OS/device including version:**
Windows 10, 64bit
**Issue description:**
When one sets a RigidBody2D's weight or mass, it is not applied at runtime.
Note: Similar but not the same as #16038
**Steps to reproduce:**
Create scene with a RigidBody2D
Add a collision shape, and a sprite (for visual purposes)
Change the RigidBody2D's mass
**Minimal reproduction project:**
![Rigid2DBug](https://user-images.githubusercontent.com/23709367/82126270-8effba00-9760-11ea-9e31-6c22c4071024.gif)

**Comment by madmiraal** [comment]
Are you expecting the body to fall faster? Because changing a body's mass won't change how fast it falls.

From [wikipedia](https://en.wikipedia.org/wiki/Leaning_Tower_of_Pisa):
> Between 1589 and 1592, Galileo Galilei, who lived in Pisa at the time, is said to have dropped two cannonballs of different masses from the tower to demonstrate that their speed of descent was independent of their mass.

**Comment by ZingBlue** [comment]
Then what does mass control?

**Comment by Calinou** [comment]
@ZingBlue It's just a different way to set the weight. It should probably be removed as it's confusing.

**Comment by ZingBlue** [comment]
What does weight do if not control how fast something falls?

**Comment by akien-mga** [comment]
You can lookup physics courses/explanations on free falling objects without air resistance, there are thousands of resources online explaining that :)

**Comment by ZingBlue** [comment]
Alright, thanks I'll look it up.

**Comment by madmiraal** [comment]
For the record, here is a simple project demonstrating the impact of mass on two colliding `Rigidbodys`:
[Rigidbody Mass.zip](https://github.com/godotengine/godot/files/4639845/Rigidbody.Mass.zip)
