### ISSUE TITLE
Script attachment on a scene node does not register as dirty (in need of saving)

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#3879]
**Operating system or device:**
windows7 64-bit
Godot 2.0 stable

**Issue description** (what happened, and what was expected):
open an existing scene with unscripted root node
use the create script wizard to add script to the node
[get distracted by a phone call, bladder or other AFK event]
close the scene

The problem here is Godot does not register the creation of a script on a node as an action that 'dirties' the scene (meaning it needs saving).  Worse if the scene is then closed (but the script generated was modified and saved) it becomes impossible to reattach the orphaned script because the create script wizard sees the file already exists,

**Steps to reproduce:**

create new scene
add a root node (I used a Node2D)
save the scene
use script wizard to create script for the node
edit script content then save the script (not the scene) in the script editor

[at this point the scene is still "dirty" as it has an unsaved script relationship that will be lost if the scene is closed at this point.  however Godot editor is not aware of this and thus not indicating it to the user with a \* nor warning the user when the scene (or godot editor) is subsequently closed. if the designer gets interrupted AFK while the scene is in this state there is a good probability the scene will be closed and the unsaved script relationship lost.  Furthermore it will become impossible to reattach the scene when the user reloads the scene (and finds it no longer links the script) since the wizard complains that the file already exists.]

**Link to minimal example project** (optional but very welcome):

The reproduction is simple enough I doubt a project is needed.

**Comment by gau-veldt** [comment]
PS: I was using the external file mode of the create script wizard, rather than the built-in mode.

**Comment by bojidar-bg** [comment]
@gau-veldt ~ As a workaround, if you scroll down in the inspector, you will see the `script` property to which you can assign the previously created script (via "Load").

**Comment by gau-veldt** [comment]
Good catch, I'll have to remember that workaround.

**Comment by AfterRebelion** [comment]
This is still true on Godot 2.1.5, and Godot 3.0.6
If you don't save the scene after creating a script, it doesn't register as changed, so if you close the scene without saving it will not open a popup to save changes, and reopening it you will have a null script reference on the root node.

**Comment by KoBeWi** [comment]
Fixed in 3.1

**Comment by bojidar-bg** [comment]
Closing as fixed then. If it is still a problem in 3.0 or 2.x, the fix might potentially be cherry-picked.
