### ISSUE TITLE
Changing properties of control container's children resets anchor & margin of both

### ISSUE THREAD

**Issue by Kimapr** [godotengine/godot#38802]
**Godot version:** 3.2.1.stable.custom_build (Guix build)

**OS/device including version:** Guix System on Linux-libre 5.4.38

**Issue description:**
Changing properties of one of container's children resets anchor & margin of them both and converts anchor to margin. Somehow this can propagate up to some point.

**Steps to reproduce:**
Create a Control scene with following hierarchy:
    
    Control
    |_MarginContainer
      |_VBoxContainer (with anchor: (left: 0, top: 0, right: 0.5, bottom: 1))
        |_CenterContainer
          |_Label (with some text and anchor (left: 0, top:0, right: 1, bottom: 0))
    
Now add a custom font to the Label and remove it.
What happens is that anchor of the Label gets set to zero and its margin changes to fill the horizontal space of MarginContainer and vertical space with size of itself.
CenterContainer also has the anchor reset and margin changes to the same as of the Label. Which disobeys the choice to make it fill half of MarginContainer.

**Minimal reproduction project:**
see *Steps to reproduce*

**Comment by TheDuriel** [comment]
This is entirely intentional.
Containers take control over all of their childrens positional properties.

**Comment by Calinou** [comment]
Closing per @TheDuriel's comment.

**Comment by Kimapr** [comment]
Please re-open this. Current behaviour is completely unexpected (and unexpected behaviour equals bug by definition), if containers alter properties of their children, the editor should show that and hide/lock the properties and change them accordingly right away.
