### ISSUE TITLE
Godot vulkan doesn't render anything

### ISSUE THREAD

**Issue by BlueCannonBall** [godotengine/godot#38805]
**Godot version:** 4.0 (got it [here](https://hugo.pro/projects/godot-builds/), didn't have enough time at the moment to build it)

**OS/device including version:** Windows 10, version 1809

**Issue description:** Upon running godot, a cmd windows launches and some text appears in it, I think the text might be errors. Then, a completely black windows launches, and right after that, a much smaller windows launches. Both windows are completely black, rendering nothing.

**Steps to reproduce:** Run godot.

**Minimal reproduction project:** I don't have a minimal reproduction project for obvious reasons, but I have screenshots. https://i.imgur.com/gpdGduv.png https://i.imgur.com/XwdaZoU.png

**Comment by clayjohn** [comment]
What hardware are you using? Does your GPU support Vulkan? Also it looks like you have not downloaded the Vulkan SDK. You can try downloading that and see if it helps.

**Comment by Calinou** [comment]
> 4.0 (got it here, didn't have enough time at the moment to build it)

My nightly builds are quite out of date. You need to compile Godot from source to benefit from the latest fixes in the `master` branch.

**Comment by RaTcHeT302** [comment]
i get the same result
![](https://i.imgur.com/se5HKbW.png)

**Comment by Calinou** [comment]
@RaTcHeT302 Nightly builds are updated less frequently these days due to issues with the build system. You can check the modification dates here: https://archive.hugo.pro/builds/godot/master/editor/

**Comment by BlueCannonBall** [comment]
> 
> 
> What hardware are you using? Does your GPU support Vulkan? Also it looks like you have not downloaded the Vulkan SDK. You can try downloading that and see if it helps.

My computer has an Intel Core i7 8th Gen CPU and an Intel UHD Graphics 620 integrated GPU. I haven't tried downloading the Vulkan SDK but I will now.

**Comment by BlueCannonBall** [comment]
UPDATE: After downloading and installing the vulkan sdk, the cmd window doesn't print as much anymore, but the windows is still completely black.

SCREENSHOT: https://i.imgur.com/aYA1FbW.png

**Comment by RaTcHeT302** [comment]
i compiled it by myself and this is what it looks like
![](https://i.imgur.com/rO0j4F4.png)
![](https://i.imgur.com/18VGZuq.png)

why is my .exe file smaller? what's going on here

**Comment by akien-mga** [comment]
> why is my .exe file smaller? what's going on here

It uses a different compiler (probably MinGW-GCC while you use MSVC), which has a different output.

**Comment by RaTcHeT302** [comment]
> It uses a different compiler (probably MinGW-GCC while you use MSVC), which has a different output.

wtf

why are they giving out such wildly different results?

anyway, why doesn't the automated release work on my pc? 
is this some weird computer magic i'm not aware of? 

i thought .exe files were essentially just math, with assembly instructions sprinkled here and there

**Comment by madmiraal** [comment]
Closing as the original issue has been resolved.
