### ISSUE TITLE
Using import hints for glTF 2.0 files breaks animation references

### ISSUE THREAD

**Issue by linky00** [godotengine/godot#38809]
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Windows 10 Home v1903

**Issue description:**
When importing a glTF 2.0 file, Godot will recognise import hints to objects such as '-col', adding features such as a collision node and removing the hint, so for example 'Marker-col' turns 'Marker'. However, the animation references aren't changed, so you get an error such as:

> Node not found: Marker-col.
> On Animation: 'Marker-loop', couldn't resolve track:  'Marker-col'.

**Steps to reproduce:**

Create a .glb file with an object with a hint, and animations involving that object. Import it into Godot, open it, click on the AnimationPlayer, and the error will occur and the animations will not work.

**Minimal reproduction project:**

[Import Hint Bug Report Example.zip](https://github.com/godotengine/godot/files/4640972/Import.Hint.Bug.Report.Example.zip)

**Comment by dragonfi** [comment]
Related and possible duplicate issues:

#42041
#38163
godotengine/godot-blender-exporter#356
