### ISSUE TITLE
Gamepad support on OSX

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#3881]
Opening this as #49 is very general and full of different discussions.
It would be very nice to finally support joystick input on Mac OSX. Afaik it's the only platform that doesn't have this feature (apart from "experimental" stuff like haiku/blackberry).

I plan on working on this as soon as I get my hands on a mac, but if anyone else wants to step in before this happens, here's what you'd need to do:

- learn how osx handles gamepad input
- figure out how SDL2 generates the gamepad GUIDs and how it orders the buttons/axes
- Call `InputDefault::joy_connection_changed()` on device (dis-)connection and provide it with the device id(starting at 0), name and guid
- recieve gamepad events and send them to the engine using `InputDefault::joy_button`, `joy_axis` and `joy_hat` with the numbering SDL uses (joy_hat takes a bitmask as argument, e.g `InputDefault::HAT_MASK_LEFT | InputDefault::HAT_MASK_DOWN`)

It would be a good idea to read the events in a seperate thread, queue them and send them to the engine once per frame (right before or after it handles keyboard input). You won't have to worry about checking for duplicate events, InputDefault does that for you.

**Comment by kirilledelman** [comment]
I spent two hours today trying to get joystick to work on my Mac with Godot, only to finally find this post. At least now I know it's not my drivers.

**Comment by danreeves** [comment]
Is this issue in progress at all?

**Comment by danreeves** [comment]
🎉  nice!
