### ISSUE TITLE
Custom defines freeze editor 

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#38822]
**Godot version:**
3.2.2 beta 2

**OS/device including version:**
Windows 10 NVidia GTX 1050

**Issue description:**
If you edit the ``custom_defines`` of a shader, the editor will freeze completely as it gets trapped in an endless loop trying to compile a shader that is not able to be compiled

**Steps to reproduce:**
Open shader in inspector, start typing a new line in the ``custom_defines`` section

cc @akien-mga @m4gr3d 

I noticed that the ``custom_defines`` section was added in https://github.com/godotengine/godot/pull/36342. I don't see why it was necessary to add support for custom defines in order to allow external textures. We could easily just expose a flag ``allow external textures`` which would set the define internally. We have plenty of features that need extensions that are enabled in the shader and we haven't exposed ``custom_defines`` for them, I don't see how external textures are any different

The problem with custom defines is that they are not parsed by our shader editor, therefore, the shader editor will attempt to compile endlessly even when the syntax is not valid leading to an endless freeze no matter what you type. Plus it exposes values that should not be changed by users as they are relied upon by renderer internals.

**Comment by m4gr3d** [comment]
`custom_defines` already existed, the referred PR just makes it available to the editor.
But as mentioned in https://github.com/godotengine/godot/pull/35306#issuecomment-576456996, the primary use case for its exposure is for plugin writers and advanced users that are familiar enough with Godot shaders to know how to modify them via custom defines. 
As such we can remove its section from the editor so regular users are not exposed to it.

**Comment by m4gr3d** [comment]
See pr #38824

**Comment by akien-mga** [comment]
Fixed by #38824.

**Comment by Zylann** [comment]
I just noticed the existence of that section in Godot 3.2.2 beta1. I would add that saving this section does not even work. My shaders are written as `.shader` and can't possibly contain new defines, which are silently lost.

**Comment by SIsilicon** [comment]
I agree with @Zylann. Custom defines would better suit being a material property than a shader property. Infact, if preprocessor directives were to be implemented, that would only prove the argument more. The only problem would be finding a good way to throw errors with them involved. Maybe if the parser were to scan for each "if" directive for defines that are involved, and parse the shader with each reasonable define combination. Then remapping where the error happened depending on what code is kept or removed by the ifs.
