### ISSUE TITLE
Clicking link in rich text label fails to find resource loader on FreeBSD

### ISSUE THREAD

**Issue by sambler** [godotengine/godot#3882]
**Operating system or device:**
FreeBSD - godot 2.0

**Issue description** (what happened, and what was expected):
Just got godot 2.0 up and running and looking through the demo files. The rich text label demo located in demos/gui/rich_text_bbcode has two url links in the example text. These fail to open the url giving the following error (a new window pops up briefly then disappears)

```
ERROR: load: No loader found for resource: http:/www.google.com
   At: core/io/resource_loader.cpp:218.
ERROR: start: Failed loading scene: http:/www.google.com
   At: main/main.cpp:1425.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1904.
```

The missing / at the start of the url could be related to the issue, adding an extra / (or several) does not help as it still shows one / in the error message. The res:// url in the [img] tag in the same example text shows the image as it is meant to, so this may be limited to parsing the [url] tag

**Steps to reproduce:**
Open the demo bundled in the source tree at demos/gui/rich_text_bbcode - run it and click one of the links.

**Link to minimal example project** (optional but very welcome):
https://github.com/godotengine/godot/tree/master/demos/gui/rich_text_bbcode

**Comment by kubecz3k** [comment]
Working fine on Ubuntu, so it might be an issue related to FreeBSD platform.

**Comment by reduz** [comment]
bug is most likely somewhere here:
https://github.com/godotengine/godot/blob/master/drivers/unix/os_unix.cpp#L325

something must be different in FreeBSD but no idea what, so feel free to ask someone knowledgeable in that OS for help

**Comment by akien-mga** [comment]
Can this still be reproduced in the current master branch? And is only FreeBSD affected, or other BSDs too?

**Comment by sambler** [comment]
Sorry, should have closed this earlier.

384055c86fa7a079c fixes the cause of this.
