### ISSUE TITLE
.res Scene Launches Project Selection

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot#38823]
**Godot version:**
3.2.1.stable

**OS/device including version:**
Windows

**Issue description:**
res root scenes launches the project selection

**Steps to reproduce:**
Save a scene as .res and then run it

**Minimal reproduction project:**

**Comment by nathanfranke** [comment]
https://github.com/godotengine/godot/issues/28036

**Comment by LoneDespair** [comment]
@nathanfranke Oh sure thing, mine only shows tscn, scn and res as options for saving scenes

**Comment by nathanfranke** [comment]
Sorry, I meant .tscn. You shouldn't save your scene as .res or .tres

**Comment by Calinou** [comment]
Duplicate of #35709.
