### ISSUE TITLE
Pressing "Play" in the editor stops working after some time

### ISSUE THREAD

**Issue by martindzejky** [godotengine/godot#38838]
**Godot version:**

v3.2.1.stable.official

**OS/device including version:**

macOS Catalina  
Version 10.15.4

**Issue description:**

I was using Godot for a few hours without any problems. But, after some time, Godot cannot run the project anymore. Pressing _Play_ produces this Output:

```
--- Debugging process started ---
--- Debugging process stopped ---
```

And the game does not start. I tried multiple things to fix this - reinstalling Godot, deleting the config directory (`~/Application Support/Godot`), restarting the editor, restarting the computer. Sometimes the issue goes away and I can use Godot for a while. But it always comes back and Godot somehow loses the ability to _Play_ the project.

I should probably get more information about why this might be happening but I don't know where to look. There's no output in the console, no error. 🤷 

If you need any further information, let me know where to look and I'll update this issue.

**Steps to reproduce:**

The issue seems to be random and I don't know how to reproduce it.

**Minimal reproduction project:**

--

**Comment by Calinou** [comment]
Can you start Godot from a terminal and see if you get further output there?

```bash
# If you've installed Godot into the system Applications folder:
cd /Applications/Godot.app/
Contents/MacOS/Godot /path/to/project.godot
```

**Comment by martindzejky** [comment]
Here's the output when pressing _Play_:

```
Running: /Applications/Godot.app/Contents/MacOS/Godot --path /Users/{...}/projects/the-last-toilet-paper --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 26770 --position 0,0
arguments
0: /Applications/Godot.app/Contents/MacOS/Godot
1: --path
2: /Users/{...}/projects/{...project dir...}
3: --remote-debug
4: 127.0.0.1:6007
5: --allow_focus_steal_pid
6: 26770
7: --position
8: 0,0
Current path: /Users/{...}/projects/{...project dir...}
Godot Engine v3.2.1.stable.official - https://godotengine.org
```

**Comment by martindzejky** [comment]
Just wanted to let you know that the same Godot version is working on my other computer with the same OS. So, I guess it is something funky with that particular computer setup. 🤷

**Comment by nathanfranke** [comment]
I was working on two separate projects, both worked at one point. One project fails with this bug, I go to a different project and everything works fine, then I suddenly encounter the bug again.

**I think** what could be causing this is an error occurring in _enter_tree and the bug isn't caught since the debugger hasn't connected yet.

**Comment by TerraReveene** [comment]
Happens to me too. Restarting Godot can sometimes fix it, but, with enough restarts Godot flat out refuses to run, so a restart of the computer becomes necessary. It gets a bit annoying.

**Comment by Nekuromu** [comment]
Yup, just had this happen out of the blue. No error or anything... project simply won't run anymore.

**Comment by Calinou** [comment]
@TerraReveene @Nekuromu Wich operating system and Godot version are you using? Do you have any particulae configuration (such as third-party antivirus programs)?

**Comment by TerraReveene** [comment]
@Calinou Windows 10 20H2, Godot v3.3.2 stable mono win64

I should note that I switched to using Godot v3.3.2 stable win64 since a day or so after posting, though, and have yet to encounter the problem again

**Comment by Nekuromu** [comment]
Windows 10, and whatever the stable version of Godot was about a month ago.

**Comment by Bryce101189** [comment]
I'm currently experiencing this exact issue as well. It began occurring earlier today as I was working on a small project of mine and has not stopped since, even after restarting my computer. I've yet to experience this issue while working on any other projects.

I am using Godot v3.3.2.stable.official, running on Ubuntu 20.04.2 LTS.

I tried running Godot again, this time through the terminal, and received this output upon pressing the *Play* button:

```
OpenGL ES 2.0 Renderer: NVD9
OpenGL ES Batching: ON

Running: /home/ { ... } /Godot_v3.3.2-stable_x11.64 --path /home/ { ... } /MyProject --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 2776 --position 448,240
```

**Comment by Calinou** [comment]
> I tried running Godot again, this time through the terminal, and received this output upon pressing the Play button:

That's the expected output. Try starting Godot from a terminal, then run a project and look for additional output that may be printed.

Also, if you've updated your graphics driver, you need to reboot for the project to be able to start again.

**Comment by Darzall** [comment]
> I am using Godot v3.3.2.stable.official, running on Ubuntu 20.04.2 LTS.

Was/may still be in the same situation myself, just Linux Mint 20.2 and Godot v3.3.2.stable.mono.official.

Was having a very annoying issue before it happened, where my own small project would crash randomly. Was starting to suspect it was a godot problem. Then started having the issue mentioned here, at first restarting godot fixed it. Eventually, while writing this in fact, I decided to poke around one more time.

Right-clicking the main scene and forcing instancing while its 'playing, but not actually running' seemed to fix it for me. At least for now...no clue if it'll start up again. Maybe it'll work for you?

**Comment by Bryce101189** [comment]
That seems to have fixed the issue for me as well. Thank you for sharing @Darzall !

**Comment by GTcreyon** [comment]
Ah, loading Godot with `-d` from the command line yields "Socket error: 10054".

**Comment by GTcreyon** [comment]
I'm not sure if this is related, but I still had it happen in 3.4. What's more, I decided I'd try to be smart and build to mobile instead so I can test it manually before I restart my PC. That didn't work either. It got stuck at 99% signing the debug APK ._.;;

**Comment by LapinChat** [comment]
Maybe this can help someone:

OS: 10.15.7
Godot 3.4.stable.official [206ba70f4]

I had a similar problem while tinkering with GDscript and a lot of data. I was generating a lot of errors when running my project. Then suddenly the project stop running.

Errors are recorded in log files here: `~/Library/Godot/app_userdata/NAME_OF_YOUR_PROJECT/logs`.
Some of the files where really big (between 200Mb and 400Mb). The biggest one was `godot.log` at about 600Mb.

I erased those log files and was able to run my project successfully.
Maybe having a look a the content of those file before erasing it will probably give some hints about what is wrong with the project.

My guess is that Godot probably have to load `godot.log` to appends new errors at the end of it. This take time and memory. Maybe it crash. But don't quote me on this I haven't dig in the source code to see how it works.

**Comment by Atermnus** [comment]
> Maybe this can help someone:
> 
> OS: 10.15.7 Godot 3.4.stable.official [[206ba70](https://github.com/godotengine/godot/commit/206ba70f4b2a3eac4455bb21bd7c8af76285bd86)]
> 
> I had a similar problem while tinkering with GDscript and a lot of data. I was generating a lot of errors when running my project. Then suddenly the project stop running.
> 
> Errors are recorded in log files here: `~/Library/Godot/app_userdata/NAME_OF_YOUR_PROJECT/logs`. Some of the files were really big (between 200Mb and 400Mb). The biggest one was `godot.log` at about 600Mb.
> 
> I erased those log files and was able to run my project successfully. Maybe having a look a the content of those file before erasing it will probably give some hints about what is wrong with the project.
> 
> My guess is that Godot probably have to load `godot.log` to appends new errors at the end of it. This take time and memory. Maybe it crash. But don't quote me on this I haven't dig in the source code to see how it works.

This doesn't work unfortunately, my log file is 12 kb

I've been experiencing this bug the past few months and lately it's been getting worse, some points after only 1-2 runs, it won't start and I have to restart my PC

**Comment by Calinou** [comment]
I've experienced a similar issue on Linux on 4.0.beta4, which is generally caused by one of two things:

- The engine binary was replaced or removed while the editor is running. Windows doesn't allow doing this, but macOS and Linux do.
- One of the project's scripts causes the engine to crash on startup (infinite recursion, etc).

Double-check your project for either of these causes.

> Errors are recorded in log files here: ~/Library/Godot/app_userdata/NAME_OF_YOUR_PROJECT/logs.
Some of the files were really big (between 200Mb and 400Mb). The biggest one was godot.log at about 600Mb.

For reference, this is now tracked in https://github.com/godotengine/godot/issues/45181.

**Comment by RichGihratik** [comment]
I still dont know, what to do with this. It occuring on laptop with Arch Linux, only in 4.0 version, 3.5 vesion works fine. Also, there was an issue, where it cant open up any project, found workaround, using --rendering-driver opengl3 keys. But i cant fix this issue
Any suggestions?

**Comment by Calinou** [comment]
> I still dont know, what to do with this. It occuring on laptop with Arch Linux, only in 4.0 version, 3.5 vesion works fine. Also, there was an issue, where it cant open up any project, found workaround, using --rendering-driver opengl3 keys. But i cant fix this issue Any suggestions?

Double-check that the project is configured to use the `gl_compatibility` rendering method, as mentioned in https://github.com/godotengine/godot/issues/74159#issuecomment-1450427287.

**Comment by RichGihratik** [comment]
It didn't even occur to me that the problem might be in new Vulcan support in Godot 4.0
I will start looking in that direction then, the problem must is there at some place.
@Calinou, thank you very much!

**Comment by bricebasty** [comment]
Joining the club. On Godot 3.5.2 (and basically every 3.x version), I get this bug. Not on Godot 4 however.
More info in this short video:

https://github.com/godotengine/godot/assets/25788991/8d863064-c44d-4cb9-85ae-19e0048f9745

I've tried everything in this thread as well and nothing makes the cut.

**Comment by bricebasty** [comment]
Ok, actually launching Godot from the console with --verbose gives me this when I try to play a scene:
--- Debugger started ---
Socket error: 13
Connection to remote host failed!
--- Debugger stopped ---
So in my case, it might have to do with the debugger not being able to launch on a localhost port I guess.

**Comment by bricebasty** [comment]
Well, I found a fix! It was effectively coming from the debugger not being able to connect to localhost.

I'm showing the solution in video for anybody here who would have the same problem. Basically changed the IPv4 localhost loopback adress to IPv6 locahost loopback adresss. (127.0.0.1 to 0:0:0:0:0:0:0:1):

https://github.com/godotengine/godot/assets/25788991/5e2ca54b-3fe4-4ef7-aebe-04a16bbc9f97

Notice that I do have a DNS blocker so that might explain why it was not working. However, I already allowed 127.0.0.1 (for every port) and the debugger DOES work on 127.0.0.1 on Godot 4. So I don't understand why only Godot 3 on 127.0.0.1 doesn't work.

**Comment by devbibo** [comment]
> Well, I found a fix! It was effectively coming from the debugger not being able to connect to localhost.
> 
> I'm showing the solution in video for anybody here who would have the same problem. Basically changed the IPv4 localhost loopback adress to IPv6 locahost loopback adresss. (127.0.0.1 to 0:0:0:0:0:0:0:1):
> 
>  godot_yay-2023-09-25_15.17.26.mp4 
> Notice that I do have a DNS blocker so that might explain why it was not working. However, I already allowed 127.0.0.1 (for every port) and the debugger DOES work on 127.0.0.1 on Godot 4. So I don't understand why only Godot 3 on 127.0.0.1 doesn't work.


i tried this and it didnt work for some reason, but i have another fix.
not a real fix to the issue but at least a way to play the project which is the command line.

`E:\godot\ultimate him>"C:\Users\nmabo\Desktop\Godot\Godot_v4.1.2-stable_win64.exe" --path "E:\godot\ultiamte him" --rendering-driver opengl3`

notice that the paths are mine so u can replace those ofc . 
i created a bat file for that so i can run the command quickly every time, and i do this for every single project i work on lol XD
