### ISSUE TITLE
[center] and [right] bbcode align tags in RichTextLabel causes text to overlap itself

### ISSUE THREAD

**Issue by gubblesdev** [godotengine/godot#38846]
**Godot version:** 3.2.1 (stable release)

**OS/device including version:** Windows 10 Pro Version 1809 (build 17763.1217)

**Issue description:**
When using either the [center] or [right] align tags in a RichTextLabel, it will sometimes cause the last line to overlap the previous one under certain conditions. Both the length of the bbcode text string (after tags are parsed) and the size of the Rect are variables in causing this to happen. Additionally, the two tags do not act like their alignment counterparts in a regular Label, as seen in the attached screenshot:

![richtextlabel overlap bug](https://user-images.githubusercontent.com/11874149/82282999-216fab80-9963-11ea-9a27-0f3e300c4544.png)

_RichTextLabel on the left, plain Label on the right. Along with the overlapping issue, the RichTextLabel [center] is not a true center as displayed in the regular Label; it appears to be left aligned and simply shifted toward the middle._

**Steps to reproduce:**
-Create a RichTextLabel
-Enable BB Code
-In the BB Code Text field, type a string preceded by either the [center] or [right] tag
-Adjust the size of the Rect until the displayed text overlaps itself

**Minimal reproduction project:**
[RichTextLabel Overlap Bug.zip](https://github.com/godotengine/godot/files/4648142/RichTextLabel.Overlap.Bug.zip)

**Comment by akien-mga** [comment]
Can you test with 3.2.2 beta 2? https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-2

**Comment by gubblesdev** [comment]
> 
> 
> Can you test with 3.2.2 beta 2? https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-2

Tested with v3.2.2 beta 2, and it looks exactly the same; not seeing any improvements or changes from v3.2.1

**Comment by theoway** [comment]
Found the bug, will be making a PR soon.
