### ISSUE TITLE
Undo/Redo bug in text-editor for auto-completed functions

### ISSUE THREAD

**Issue by hydescarf** [godotengine/godot#38847]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
Undo/Redo on functions will cause bugs to appear if you use the auto-complete feature. I believe it didn't include the detection for bracket-checking into the undo-history. Say, if you are trying to replace the function name with auto-complete, it will ignore(or replace) the brackets after them if exist, and this part was not included into the history and during undo-and-redo, there will be extra brackets/words coming out afterwards.
*note*: There is also time that they put back extra brackets only (not including words like picture below), but I'm not sure how to reproduce that.

**Steps to reproduce:**
See attached picture, steps are described in it.
![gdscript bug](https://user-images.githubusercontent.com/56707567/82284966-e0ac7c80-99cc-11ea-8590-b117d433f062.jpg)

*note*: I just realized but, shouldn't step-4 not deleting the brackets? I was only erasing the words, not the brackets, but they removed it during that

**Comment by Omicron666** [comment]
i confirm this on 3.2.3
my hypothesis:
- when autocomplete is adding parenthesis, it is also eating existing following parenthesis for QoL.
- that eating action isn't saved into undo history

**Comment by Omicron666** [comment]
also related bug, but i couldn't replicate yet, sometimes i get missing leading char eaten by redo actions (maybe some previous "eating" actions wrongly inserted in undo history ?)

**Comment by KoBeWi** [comment]
Looks fixed in 4.0. Something weird happens to caret when you undo/redo, but the text doesn't get corrupted.
