### ISSUE TITLE
Find in Files: match boxes in Search Results does not change positions when changing Font Size

### ISSUE THREAD

**Issue by Akylzhan** [godotengine/godot#38858]
**Godot version:** 
3.2.stable.official
**OS/device including version:** 
Macbook Air 13' 2015
MacOS 10.14.6
**Issue description:**
![image](https://user-images.githubusercontent.com/28390596/82338155-5c7ae900-9a0e-11ea-99d8-756fa517b5ad.png)

**Steps to reproduce:**
Open Script Editor
Search for any existing word in Find in Files
Try to increasing/decreasing font size

**Comment by Anutrix** [comment]
I couldn't reproduce this on 3.2.1-stable on Windows. I tried changing the main font size and code font size editor settings.
