### ISSUE TITLE
"Replace Node by Another Node Type" doesn't confer properties of new node type onto replaced node

### ISSUE THREAD

**Issue by paraclete-pizza** [godotengine/godot#3885]
Specifically, when replacing/changing a node that is not a "body" (PhysicsBody2D) into a type of node that is one, the new PhysicsBody does not act as a PhysicsBody in the executed game, and is not detected by get_overlapping_bodies().

**Comment by akien-mga** [comment]
I guess you forgot to add a CollisionShape2D or CollisionPolygon2D to this body?

**Comment by bojidar-bg** [comment]
Also, if you have collision shapes, you should try moving them around, just in case...

**Comment by paraclete-pizza** [comment]
Nope. The nodes contained collision shapes. I did an experiment where I made two identical node structures. One was a KinematicBody2D containing a CollisionShape2D. The other was a Node2D containing a CollisionShape2D, which I then swapped into a KinematicBody2D containing a CollisionShape2D.

The first KinematicBody2D both collided with other bodies, and was detected by get_overlapping_bodies(). The second one, the one that was changed into a KinematicBody2D, did neither, despite both being identical node structures.

**Comment by mohaalak** [comment]
@paraclete-pizza  can you take a screenshot from your nodes so we can see it how you do it? cause the kinematicbody does not have get_overlapping_bodies() area have but not the kinematic body

**Comment by paraclete-pizza** [comment]
@mohaalak : Here's a video of me recreating the issue:

https://youtu.be/OqLJ2keWfLw

**Comment by bojidar-bg** [comment]
@paraclete-pizza ~ That looks weird, maybe you can try pressing <kbd>Ctrl</kbd>+<kbd>S</kbd> before each test. Also, what happens if you, instead of playing the game, save the scene and try to open it again? Plus, what OS/godot version are you on, and does the console print any errors (if you got one)?

**Comment by paraclete-pizza** [comment]
Interesting! Pressing ctrl+s before the tests does seem to fix the problem!

Which is strange, since normally just running a test seems to save the file automatically (or, at least, clears the asterisk from the filename...).

FWIW, I'm using 'v2.0.rc1.custom_build' of Godot, on Windows 7.

**Comment by bojidar-bg** [comment]
@paraclete-pizza ~ I mean, did you build it by yourself (and if so, when), or if you use 2.0 stable from the website?

**Comment by paraclete-pizza** [comment]
I used the stable Windows build from the website.

**Comment by bojidar-bg** [comment]
@paraclete-pizza ~ Ok, can you try with `.tscn` or `.xscn` scene formats, as it would be easier to guess where the bug is then?

**Comment by reduz** [comment]
same old bug with shapes, will be fixed in 3.0

**Comment by reduz** [comment]
i closed like 10 derivatives of this bug today, it's fixed now in 3.0
