### ISSUE TITLE
Godot 3.2.1 cannot import .obj file

### ISSUE THREAD

**Issue by mnkylord** [godotengine/godot#38865]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
Cannot import a seemingly good .obj file. Houdini/Blender can import it.

**Steps to reproduce:**
Try to import it as a meshinstance:
[obj file](https://drive.google.com/open?id=1XAW53LA20l1sFbSqHz6VJWGCse4npVJ3)

**Minimal reproduction project:**

**Comment by TheDuriel** [comment]
File imports fine on Godot 3.2.1 and Blender 2.8.2.

**Comment by mnkylord** [comment]
My bad, I must have forgotten to copy the latest version to my Godot directory.
