### ISSUE TITLE
Duplicating Custom VS node, makes an instance/duplicate of its script.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#38867]
**Godot version:**
Godot 3.2.1

**OS/device including version:**
Windows 10 64bit 1909

**Issue description:**
When Deplicating a Custom VS node , It makes an instance of it , not linking it to the original script.

**Steps to reproduce:**
1-Make a Custom Node in any Virtual script. Link it with a custom Vs script written in Gdscript
2- Ctrl+D to duplicate the Node.
3-Check the script of the new node. it will be NAME.vs::NUMBER

It should be ScriptName.gd
This mean that by changing the main script , this new instance node will not be effected.

Here is some images.
https://i.ibb.co/rm4nRxF/Annotation-2020-05-19-175752.png
https://i.ibb.co/KWrMCP1/Annotation-20d20-05-19-175752.png

By duplicating the First Image Script we get a new Instance or deplicate of the script, Not linking it to the same on.

Hope this help addressing this bug.
Thanks

**Comment by fire** [comment]
Spooky ghosts. Will archive. Feel free to ask to reopen.
