### ISSUE TITLE
TextureArray cannot be re-imported

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#38870]
Godot 3.2.1

1) Make an atlas of textures as PNG
2) In Godot, change its import type into TextureArray. If you click Reimport, it will ask you to restart the editor (I'm surprised how that's needed but that's currently expected), so do that
3) Once back in the editor, double-click on the PNG to make it show in inspector.
4) Go in the Import dock and click Reimport again. This pops up:

![image](https://user-images.githubusercontent.com/1311555/82359250-909add80-99ff-11ea-8fcf-bd63f155dcd1.png)

In the console:
```
ERROR: Safe save failed. This may be a permissions problem, but also may happen because you are running a paranoid antivirus. If this is the case, please switch to Windows Defender or disable the 'safe save' option in editor settings. This makes it work, but increases the risk of file corruption in a crash.
   At: drivers/windows/file_access_windows.cpp:183
```

I have Windows Defender, I suspect Godot is stepping on its own toes here.

This does not reproduce if I skip step 3). It happens all the time as soon as the resource is in the inspector's history. Re-importing works fine for other kinds of resources.

Project:
[ReimportTextureArray.zip](https://github.com/godotengine/godot/files/4652218/ReimportTextureArray.zip)

**Comment by YuriSizov** [comment]
Fixed by https://github.com/godotengine/godot/pull/71394.
