### ISSUE TITLE
RayCast2D and CollisionPolygon2D collisions are unreliable

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#38873]
**Godot version:**
3.2.1

**Issue description:**
The Sprite becomes red when the raycast's `is_colliding()` returns true.
![3dTNWfTIq1](https://user-images.githubusercontent.com/2223172/82368823-55f06f80-9a16-11ea-81a1-8ed7771ebf7d.gif)
As you can see, raycast will detect collision only with the edge of polygon's quad and will fail inside.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4652647/ReproductionProject.zip)

EDIT:
Also tested with rectangle CollisionShape2D and it works correctly, so it's indeed a bug with polygons.

**Comment by bojidar-bg** [comment]
CollisionPolygon2D decomposes into multiple ConvexShape2D shapes when in "solids" mode:
https://github.com/godotengine/godot/blob/master/scene/2d/collision_polygon_2d.cpp#L49-L59

To determine whether a shape intersects a raycast, `CollisionSolver2DSW::solve_raycast` uses `Shape2DSW::intersects_segment`:
https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/servers/physics_2d/collision_solver_2d_sw.cpp#L96

Unfortunately, `ConvexPolygonShape2DSW::intersect_segment` does not check if both points are inside:
https://github.com/godotengine/godot/blob/master/servers/physics_2d/shape_2d_sw.cpp#L559

Probably such a check could be done after failing to intersect any of the lines using `Geometry::is_point_in_polygon`. Given that `is_point_in_polygon` does the check using any point definitely outside of the polygon, maybe some part of it can be merged with the loop in `intersect_segment`. Maybe even doing something like `further_away = get_aabb().position - Vector2(1, 1)`, as any point outside the AABB of the polygon is definitely outside the polygon.

**Comment by Xrayez** [comment]
See also #38343, #35845.

**Comment by knightofiam** [comment]
Any workarounds?

**Comment by KoBeWi** [comment]
@knightofiam Area2D or KinematicBody2D and `test_move()`

**Comment by Houkime** [comment]
Still valid for v4.0.dev.custom_build [a0d800e96]
That could be said to be a perfomance feature, but then the mode probably should not be called a solid.
