### ISSUE TITLE
Compiling for X11 linking error on deepin linux with LTO

### ISSUE THREAD

**Issue by boluochoufeng** [godotengine/godot#38885]
**Godot version:**
3.2

**OS/device including version:**
deepin linux v20 beta

**Issue description:**
when I  complied godot from source codes, it falied. Here are some information:

command: scons -j8 platform=x11 target=release_debug use_lto=yes

log:
```
[100%] Linking Program        ==> bin/godot.x11.opt.tools.64
/usr/bin/ld: /tmp/cc0ck8tN.ltrans29.ltrans.o: in function `Object* ClassDB::_create_ptr_func<WebSocketServer>()':
<artificial>:(.text+0x4eb3): undefined reference to `WebSocketServer::_create'
/usr/bin/ld: /tmp/cc0ck8tN.ltrans29.ltrans.o: in function `WSLPeer::_create()':
<artificial>:(.text+0x24132): undefined reference to `WSLPeer::WSLPeer()'
/usr/bin/ld: /tmp/cc0ck8tN.ltrans29.ltrans.o: in function `WSLClient::_create()':
<artificial>:(.text+0x24162): undefined reference to `WSLClient::WSLClient()'
/usr/bin/ld: /tmp/cc0ck8tN.ltrans29.ltrans.o: in function `WSLServer::_create()':
<artificial>:(.text+0x24192): undefined reference to `WSLServer::WSLServer()'
/usr/bin/ld: /tmp/cc0ck8tN.ltrans29.ltrans.o: in function `register_websocket_types()':
<artificial>:(.text+0x10ee77): undefined reference to `WebSocketServer::_create'
/usr/bin/ld: <artificial>:(.text+0x10f21a): undefined reference to `WebSocketServer::_bind_methods()'
/usr/bin/ld: /tmp/cc0ck8tN.ltrans30.ltrans.o: in function `GDScriptLanguageServer::start()':
<artificial>:(.text+0x111ded): undefined reference to `WebSocketServer::set_bind_ip(IP_Address const&)'
/usr/bin/ld: <artificial>:(.text+0x111f36): undefined reference to `typeinfo for WebSocketServer'
/usr/bin/ld: /tmp/cc0ck8tN.ltrans31.ltrans.o: in function `register_module_types()':
<artificial>:(.text+0x15ef29): undefined reference to `register_xatlas_unwrap_types()'
/usr/bin/ld: /tmp/cc0ck8tN.ltrans31.ltrans.o: in function `Main::cleanup()':
<artificial>:(.text+0x16c7d3): undefined reference to `unregister_xatlas_unwrap_types()'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.opt.tools.64] Error 1
scons: building terminated because of errors.
```

how I can  solve the problem？Thanks

**Comment by akien-mga** [comment]
It should work without `use_lto=yes`.

What are your GCC and ld versions (`gcc --version` and `ld --version`)?

Can you retry with `use_lto=yes` with a clean build (`git clean -fxd`, though note that it will remove all untracked files from your git repository, so if you had custom ones like e.g. an IDE configuration file, it would be removed)?

**Comment by boluochoufeng** [comment]
> It should work without `use_lto=yes`.
> 
> What are your GCC and ld versions (`gcc --version` and `ld --version`)?
> 
> Can you retry with `use_lto=yes` with a clean build (`git clean -fxd`, though note that it will remove all untracked files from your git repository, so if you had custom ones like e.g. an IDE configuration file, it would be removed)?
> 
> Possibly the same issue as #36984.
gcc version is 8.3.0
ld version is 2.31.1
it work without use_lto=yes. I retry it follow your advice. Thanks

**Comment by boluochoufeng** [comment]
It does not work with a clean build. 
error log changes:
/usr/bin/ld: /tmp/cc7SftHT.ltrans31.ltrans.o: in function `register_module_types()':
<artificial>:(.text+0x163934): undefined reference to `register_websocket_types()'
/usr/bin/ld: <artificial>:(.text+0x163939): undefined reference to `register_xatlas_unwrap_types()'
/usr/bin/ld: /tmp/cc7SftHT.ltrans31.ltrans.o: in function `Main::cleanup()':
<artificial>:(.text+0x1711f9): undefined reference to `unregister_websocket_types()'
/usr/bin/ld: <artificial>:(.text+0x1711fe): undefined reference to `unregister_xatlas_unwrap_types()'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.opt.tools.64] Error 1
scons: building terminated because of errors.

**Comment by akien-mga** [comment]
I haven't been able to reproduce this issue despite making LTO builds for 3.x and 4.x branches with different versions of GCC over the years. I suspect this might have been a bug in GCC 8.3 which was fixed in later versions.
