### ISSUE TITLE
LocalVector uses unsigned int to catch int value

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#38884]
**Godot version:**
4.0 master c2151e18135817c9
**Issue description:**
find return int so idx should be probably changed to unsigned int

https://github.com/godotengine/godot/blob/c2151e18135817c9f926a5a00341016ac77301d4/core/local_vector.h#L77-L81

Vector 

https://github.com/godotengine/godot/blob/c2151e18135817c9f926a5a00341016ac77301d4/core/vector.h#L71-L75

**Comment by Zylann** [comment]
Following the logic of this vector, `find` should return `U` actually
