### ISSUE TITLE
Memory leak with godot server executable

### ISSUE THREAD

**Issue by beegor** [godotengine/godot#38883]
**Godot version:**
3.1.2, 3.2.1

**OS/device including version:** 
Ubuntu 19.10

**Issue description:**
Game with dynamic instantiation of scene nodes.  When run with godot server executable leaks memory.  

**Steps to reproduce:**
Make main scene create objects (instances of another scene) in every frame and adds them as child nodes. Nodes queue_free themselves short period after added to parent scene.
Unzip attached minimal project, and run Godot_v3.1.2-stable_linux_server.64 in project dir. Observe memory usage of the process. Memory grow slowly but steady. If left to run long enough application crashes.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/4656259/test.zip)

**Comment by Wavesonics** [comment]
I believe this was solved by: #39818
