### ISSUE TITLE
Godot's new Q&A site says I could use my Github login, but it doesn't work.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#3888]
As the title says, instead I get some error about being unable to access the page or something. I would advise to either fix it or remove the option altogether (so people won't be misled, even though it would be an incredible convenience if it did work).

**Comment by freemanfromgodotengine** [comment]
The GitHub Login works. I am logged in right now that way.
Maybe try first to log into Github, then in another tab go to godotengine.org and use GitHub Login option.
It should work.

**Comment by Ace-Dragon** [comment]
Unfortunately it doesn't seem to want to work.

What I'm doing is pressing the little 'login' with Github button (and it will give an error even if I type my username and password in the fields).

I know I am logged into Github because I otherwise wouldn't be able to make this reply.

**Comment by akien-mga** [comment]
It's working fine for most of us, you might have a caching issue.

**Comment by bojidar-bg** [comment]
@Ace-Dragon Use [godotengine.org](godotengine.org) instead of [www.godotengine.org](www.godotengine.org)

@akien-mga ~ Maybe something is wrong in the settings of the github app?

**Comment by Ace-Dragon** [comment]
Okay, removing the www works.

Thanks
