### ISSUE TITLE
Can't access direct space state in godot physics (3D)

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#38899]
**Godot version:**
3.2.2 beta 2 mono
Edit: Also happens in 3.2.1.

**OS/device including version:**
MXLinux 19 64 bits

**Issue description:**
In a 3d project I can't use GetWord().DirectSpaceState in _PhysicsProcess when using godot physics, with bullet I can access it from both _Process and _PhysicsProcess.

![Screenshot](https://user-images.githubusercontent.com/18746022/82484276-b380cc80-9aa7-11ea-8bc9-6e8760d707f3.png)

**Steps to reproduce:**
Try to get the direct space state with GetWord().DirectSpaceState using Godot physics.

**Comment by Ev1lbl0w** [comment]
Well, judging by that message, the PhysicsSpace is locked when you try accessing it. Maybe accessing it inside `_pyhsics_process` works..?

**Comment by MightyPrinny** [comment]
As I mentioned this is already in _PhysicsProcess and works with bullet physics

**Comment by MightyPrinny** [comment]
This doesn't seem to happen in a fresh project, I'll look into what causes it to make an MRP.

**Comment by MightyPrinny** [comment]
closed by accident.

**Comment by MightyPrinny** [comment]
This solved itself after I restarted the editor, weird.
