### ISSUE TITLE
"Invalid locale 'C'" - wrong locale (Linux)

### ISSUE THREAD

**Issue by vithuranvishnuthas** [godotengine/godot#38892]
**Godot version:**
Godot Engine v3.2.1.stable.custom_build
Godot Enigine v3.2.1.stable_x11
**OS/device including version:**
Manjaro Linux 
**Issue description:**
Playing the project returns following error messages (without breaking):
>  E 0:00:00.317   get_language_code: Invalid locale 'C'.
  <C++ Error>   Condition "p_locale.length() < 2" is true. Returned: p_locale
  <C++ Source>  core/translation.cpp:945 @ get_language_code()

> E 0:00:00.317   get_language_code: Invalid locale 'C'.
  <C++ Error>   Condition "p_locale.length() < 2" is true. Returned: p_locale
  <C++ Source>  core/translation.cpp:945 @ get_language_code()

In general `OS.get_locale()` returns 'C' - which is the default value for LC_* variables that have not been explicitly set. 

**Steps to reproduce:**
Create Project on mentioned OS. Create a scene. Run Project.

**Comment by sonic2kk** [comment]
This is a locale issue with your system. Have you properly enabled UTF-8 locales? You can check and run the steps for properly configuring them [here](https://wiki.archlinux.org/index.php/locale#Setting_the_locale).

**Comment by vithuranvishnuthas** [comment]
Thanks a lot. I didn't know the GUI settings only makes the changes to locale.conf without permanently updating LANG.
