### ISSUE TITLE
Unable to have an argument without a default after parameter with set default

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#38901]
**Godot version:**
3.2.1
**OS/device including version:**
Windows 10 Home 1909
**Issue description:**
If I have a function with a parameter which has a default I won't be able to set parameters without default after this first parameter with the default.
**Steps to reproduce:**
Create a script. Create a function with 2 parameters. Set a default to the first parameter.
**Minimal reproduction project:**
func say_something(string="Hello",a)

**Comment by Ev1lbl0w** [comment]
I don't think this works with any language whatsoever; the parameters with default values need to be at the end, otherwise the compiler/interpreter doesn't know which one you're trying to call.

**Comment by Calinou** [comment]
As @Ev1lbl0w said, this isn't a bug. Most programming languages out there don't support this, and there are no plans to implement this in GDScript.
