### ISSUE TITLE
Adding code completion of properties in Object.set/get

### ISSUE THREAD

**Issue by spaghiajoeojo** [godotengine/godot#3890]
Code completion is very nice now but it should be available when calling set(String property, value)! Is it possible?

**Comment by bojidar-bg** [comment]
:+1: ~ The more working code completion, the better

**Comment by vnen** [comment]
Related to #5109 and #5177.

**Comment by Anutrix** [comment]
Is this still relevant in new 4.0 GD Script?

**Comment by akien-mga** [comment]
Yes:
![image](https://user-images.githubusercontent.com/4701338/186009220-2fda533a-2dec-473b-ac80-1c4d74f93243.png)

It should show a list of property names.

**Comment by akien-mga** [comment]
Fixed by #66427.
