### ISSUE TITLE
how do i import the online 3d model like obj,dae or gltf from webserver into the godot?

### ISSUE THREAD

**Issue by garuhester** [godotengine/godot#38914]
hello everyone ,i  have a question about godot. how do i import the online 3d model like obj,dae or gltf from webserver into the godot?i use the HTTPRequest to request the online obj model url,i can get the content of the obj file by body.get_string_from_utf8(),but i don't know how to change this to mesh?thanks

**Comment by nathanfranke** [comment]
The GitHub issues form is for issues and bugs about Godot. You may want to post this question in the [Q&A](https://godotengine.org/qa/).

**Comment by garuhester** [comment]
> The GitHub issues form is for issues and bugs about Godot. You may want to post this question in the [Q&A](https://godotengine.org/qa/).

ok,thanks
