### ISSUE TITLE
Audio Playback crashes for unknown reasons when switching streams

### ISSUE THREAD

**Issue by AfterCadaver** [godotengine/godot#38915]
**Godot version: 3.2.1**

**OS/device including version:Windows 7 SP1**

**Issue description: Sound inconsistently cuts off of a sudden when attempting to switch tracks**

**Steps to reproduce: **

- Unable to find precisely what steps to reproduce. 

- I set AudioStreamPlayer to set_stream and play the next track. 

- I set the SceneTree.Pause to true which may have relevance. The AudiostreamPlayer is set to process.

- The result crashes audio playback or produces loud screeching noise and then crashes the same.

**Minimal reproduction project: Unable to ascertain the exact problem or cause. This is the only project this has happened with so far.**

**Comment by Calinou** [comment]
@AfterCadaver  Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
