### ISSUE TITLE
for loop so slow with current head 46bfcd3

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3891]
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
for loop so slow with current head (46bfcd350745d3053a0cab2985d73baae0a4a88d)
My game became so laggy because of ``for`` running time

**Steps to reproduce:**
```gdscript
var arr = range(0,100000)

func _ready():
    var time = OS.get_ticks_msec()
    var c = 0
    for i in arr:
        c += i
    print("run in ", OS.get_ticks_msec() - time, " ms")
```

It's 10 ms with 2.0 stable.
and 167 ms with current head.

I guess it's related with PR #3814

**Comment by akien-mga** [comment]
Ping @est31.

**Comment by bojidar-bg** [comment]
That's wierd, maybe try using `xrange`?

**Comment by volzhs** [comment]
I need to have an array to manage some game data.

**Comment by est31** [comment]
The weird thing is that the optimisation doesn't happen in this particular case...

@volzhs were the two binaries built by you? Was the new binary built with debug, and the old one with release?

**Comment by volzhs** [comment]
I got stable version at http://www.godotengine.org/download.
And current head build version is compiled my self.
I always use my build so far and this have not happened before.

compiled it on ubuntu 14.04 and use ``scons -j 4 p=windows target=release_debug bits=64``

**Comment by est31** [comment]
It might be due to MVC usage, I'm not sure. Can you try to get 2.0 stable source code and build it with the same params, then test it?

**Comment by volzhs** [comment]
nobody has same result with me?

**Comment by est31** [comment]
I'm trying right now, but building godot takes very long, so I've thought you can try it in parallel :)

**Comment by volzhs** [comment]
I also downloaded 2.0 branch which doesn't have xrange PR.
and compiling now...

**Comment by est31** [comment]
In fact I do get slower behaviour when using `xrange` instead of `range` in your example, but I still highly doubt that your example is slower than on 2.0. That's because the particular code you invoked does not do the `range`→`xrange` optimisation. You can check this by adding a debug line, editing `gd_parser.cpp` in `modules/gdscript`:

```C++
						if (c->function == GDFunctions::GEN_RANGE) {
							print_line("Doing range -> xrange optimisation");
							c->function = GDFunctions::GEN_XRANGE;
						}
```

Your code never triggers the change.

However, when I edit your code to indeed use xrange, it indeed runs slower:

```gdscript
func _init():
	var time = OS.get_ticks_msec()
	var c = 0
	for i in range(0,100000):
		c += i
	print("run in ", OS.get_ticks_msec() - time, " ms")
```

gives for me:

```
Doing range -> xrange optimisation
run in 191 ms
```

While

```gdscript
var arr =  range(0,100000)
func _init():
	var time = OS.get_ticks_msec()
	var c = 0
	for i in arr:
		c += i
	print("run in ", OS.get_ticks_msec() - time, " ms")
```

gives for me:

```
var time = OS.get_ticks_msec()
```

**Comment by est31** [comment]
There we go, I blindly applied the class by @sheepandshepherd without testing speed lol

**Comment by reduz** [comment]
Optimizing GDScript is is not a problem, but can we please organize making
a set of benchmarks? I don't want to work on isolates cases but the
interpreter as a whole.

I'm sure that there is a ton of optimizations possible including this one
but we need someone to take the responsability of compiling a list of
benchmarks, so far we've had no success in finding volunteers for this task.

**Comment by est31** [comment]
Benchmarks... Perhaps I could look at doing something like this.

**Comment by volzhs** [comment]
I got really weird experience.
I compiled 2.0 stable branch head and also 2.0 tag commit.
So, got 3 binaries which are current head, 2.0 head, 2.0 tagged.
when run the code with these 3 binaries, these all give me about ``170ms``.

I think I complied right sources.
I always use my build binary and I'm sure It didn't happened before some days.
So I noticed today, but... I don't know why this happened.

**Comment by est31** [comment]
@volzhs your code doesn't invoke the `range → xrange` optimisations, as I said. It assings range to a variable first and the parser isnt smart enough to optimize this. Try instead:

```
func _init():
    var time = OS.get_ticks_msec()
    var c = 0
    for i in range(0,100000):
        c += i
    print("run in ", OS.get_ticks_msec() - time, " ms")
```

**Comment by volzhs** [comment]
I tested my own build binary.

``for i in arr`` gives me about **170ms**.
``for i in range(0,100000)`` gives me about **400ms**.
