### ISSUE TITLE
Changing TabContainer hseparation property does not adjust tabs

### ISSUE THREAD

**Issue by AssimiIation** [godotengine/godot#38911]
**Godot version:**
Godot v3.2.2.beta1.mono.official

**OS/device including version:**
Windows 10 Pro version 1909

**Issue description:**
Altering the hseparation value within the TabContainer's Custom Constants menu does not adjust the horizontal separation between tabs as the tooltip suggests

**Steps to reproduce:**
Create a scene:
```
TabContainer
-Control
-Control
-Control
```
With the TabContainer node selected and using the inspector, alter the value of Hseparation in the Custom Constants dropdown. The tabs maintain position and do not move.

**Comment by KoBeWi** [comment]
This is because the `hseparation` is actually a space between tab's name and its icon. The documentation is wrong.
