### ISSUE TITLE
OS.get_system_time_secs() doesn't use NT epoch on Windows

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#38925]
**Godot version:**

Godot 3 and 4

**OS/device including version:**

Windows 10

**Issue description:**

The documentation says:
> int get_system_time_secs ( ) const
> Returns the epoch time of the operating system in seconds.

So it would be expected that the NT epoch would be used under Windows (hence using 1601 as year zero instead of UNIX's 1970), but the UNIX epoch is used instead.

This is pretty obvious in the codebase where the method does some epoch conversion:
https://github.com/godotengine/godot/blob/9239412027b6c25009efab69dc39650e0d76c56d/platform/windows/os_windows.cpp#L381-L395
(btw `get_unix_time` has a different way to do epoch conversion, but there both end up with the same result in the end...)

**Steps to reproduce:**

```gdscript
print('system_time_secs: ', OS.get_system_time_secs())
print('unix_time: ', OS.get_unix_time ())
# Prints:
# system_time_secs: 1590070826
# unix_time: 1590070826
```

**Comment by Calinou** [comment]
Should we rename the method instead, or remove it entirely in favor of `OS.get_unix_time()`?

**Comment by touilleMan** [comment]
I agree, Windows epoch is pretty much useless unless you integrate with Windows API (which is definitely not what the Godot API is designed for !)

I would say we should remove `OS.get_system_time_secs` and `OS.get_system_time_msecs` and only provide `OS.get_unix_time()` that return a `godot_float` (so that we have both seconds and msecs, just like what [is done in python](https://docs.python.org/fr/3/library/time.html#time.time) for instance).
We could also rename `OS.get_unix_time()` to `OS.get_time()` and document the fact we are always using UNIX epoch.

**Comment by Calinou** [comment]
> We could also rename OS.get_unix_time() to OS.get_time() and document the fact we are always using UNIX epoch.

I think it'd be better to leave the method name as-is, as it's a bit more explicit.
