### ISSUE TITLE
Add TileMap tile origin "Bottom" (for ysort)

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#3892]
When using YSort mode in a TileMap, for the child nodes I use y0 as the height on which e.g. a character has their feet, an object touches the ground etc.

But for tiles, y0 is the center or the top. Using the bottom as the tile origin would make it a lot easier to use.

It can be worked around by setting the offset accordingly, but it's unwieldy, as the sprite ends up a tile above the cursor:
![tile_ysort_workaround](https://cloud.githubusercontent.com/assets/6996191/13430253/a2619b70-dfc4-11e5-823b-94cdb74de5ac.png)

*(Using http://opengameart.org/content/tiny-16-basic by Lanea Zimmerman for demonstration)*

**Comment by jackmakesthings** [comment]
:+1:
This seems like it would also be very useful for isometric tilemaps with ysort.

**Comment by eska014** [comment]
closed by #5270
