### ISSUE TITLE
Tree control can loop infinitely under certain conditions

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot#38933]
**Godot version:**
3.2.stable
master@9239412

**OS/device including version:**
Windows 10

**Issue description:**
The `Tree` control is partial to infinite loops when navigating its items using incremental search (typing out names with a keyboard). Problem lies in `Tree::_search_item_text` method due to its reliance on the wrapping behavior in `get_next_visible` here:

https://github.com/godotengine/godot/blob/9239412027b6c25009efab69dc39650e0d76c56d/scene/gui/tree.cpp#L3430

**This issue is present when using editor normally!** But I guess it can also be reproduced within user projects.

**Steps to reproduce:**
1. Create a new project and a new scene within it.
2. Bring up the *Create New Node* dialog using a context menu or a keyboard shortcut.
3. Start typing "label" in the text filter; make sure that the `Label` node is selected.

![image](https://user-images.githubusercontent.com/11782833/82594691-2758cd00-9bad-11ea-9fb2-5fdcaaed75ac.png)

4. Click next to the `CanvasItem` node to toggle its branch.
5. Without moving focus away from the Tree start typing another control's name, e.g. "control".

What happens is during handling `_gui_input` the `Tree::_search_item_text` gets hit. It starts with the root item, which is `Node`, but gets to the line 3430 where it asks the tree to provide the next visible item. Unfortunately, there is no visible items left, because `CanvasItem` is disabled and others are toggled off. But the function is called with `p_wrap` set to `true`, which causes it to retrieve the same `Node` item next and continue the process ad infinitum.

**Minimal reproduction project:**
Not applicable.

**Comment by KoBeWi** [comment]
I think I managed to reproduce it once, but I can't anymore.

> Click next to the CanvasItem node to toggle its branch.

On this action, the Control node gets focused, so there's a visible selected item, which prevents the infinite loop.

@pycbouh Can you check if it still happens for you in 3.2.2?

**Comment by pycbouh** [comment]
@KoBeWi It's the same in 3.2.2. 

> On this action, the Control node gets focused

You may have mixed some steps there. After you've typed "label" and you got the state as displayed on the picture, you click next to `CanvasItem` to collapse its branch. `Control` cannot get focus there because `Control` is inside of that branch and thus is invisible after that step.

**Comment by KoBeWi** [comment]
Oh, right. I collapsed wrong branch .-.
