### ISSUE TITLE
Name conflicts between methods, properties, and signals

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#38937]
**Godot version:**
4.0-dev 9239412

**OS/device including version:**
Any

**Issue description:**
Some methods, properties, and signals share the name. This is a problem now because we have first-class signals and functions (as Callable), so accessing them becomes difficult if there's a conflict.

For example, using this GDScript code:

```gdscript
func _ready():
    await $Button.pressed
    print("Pressed!")
```

Won't work as intended because the `pressed` property shadows the `pressed` signal.

### List

Here are the duplicates that I could find. I might be missing something, but this list is actually short:

- [x] `CanvasItem::hide` (signal and method)
  * The signal can be renamed to `hidden`, since signal names are usually verbs in past tense.
- [x] `Control::minimum_size_changed` (signal and method)
  * The method is just to clear the cache, so it should be renamed to something else.
- [x] `BaseButton::pressed` (signal and property)
  * This is tricky because both make sense. `is_pressed` is the name of the getter. Not sure what to do.
- [x] `ProximityGroup3D::broadcast` (signal and method)
  * Not a good signal name (not a verb in past tense). So maybe it could be changed to `broadcast_received`?
- [x] `TouchScreenButton::pressed` (signal and property)
  * ~~This is confusing because, unlike BaseButton, this is the pressed **texture**. While I'm not fond on types in the name, `pressed_texture` might be better for the property.~~ There are plans to remove this class ([#55665](https://github.com/godotengine/godot/pull/54430#issuecomment-987901083)), so irrelevant.
- [x] `PathFollow2D::rotate` (property and method)
  * The property is a boolean, telling whether or not it should rotate. Maybe `should_rotate` is fit?
- [x] `Input::joy_connection_changed` (signal and method)
  * According to the method's description, it's internal and shouldn't be even exposed, so this is easy one.

Additionally, we should add checks in ClassDB to avoid registering duplicate names again. I noticed that virtual methods are not stored by name, so maybe they should be to facilitate this check (even if only in debug).

Related to #16863.

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
N/A

**Comment by KoBeWi** [comment]
> This is confusing because, unlike BaseButton, this is the pressed texture. While I'm not fond on types in the name, pressed_texture might be better for the property.

Or we could follow TextureProgress naming and name it `texture_pressed`.

> The property is a boolean, telling whether or not it should rotate. Maybe should_rotate is fit?

Maybe `follow_rotation` or `update_rotation` or something similar.

**Comment by aaronfranke** [comment]
Speaking of members shadowing each other due to having the same name, there's also #36382.

**Comment by MaaaxiKing** [comment]
> `BaseButton::pressed` (signal and property)
> * This is tricky because both make sense. `is_pressed` is the name of the getter. Not sure what to do.

Maybe is_pressed for property and is_being_pressed as signal🤷

**Comment by KoBeWi** [comment]
There is also `Input.joy_connection_changed`, but judging from the method description, it shouldn't be even exposed.

**Comment by KoBeWi** [comment]
About ProximityGroup:

> Not a good signal name (not a verb in past tense). So maybe it could be changed to broadcast_received?

The signal is actually for sending broadcast, not receiving it. So it should be `broadcast_sent` or `broadcasted` or something like that.

**Comment by akien-mga** [comment]
Finally fixed with the above linked PRs.
