### ISSUE TITLE
Visualscript function doesn't display its name - Unnamed functions

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#38946]
**Godot version:**
Godot 3.2.1
**OS/device including version:**
Windows 10 64bit 1909
**Issue description:**
No Name Displayed on the function block
**Steps to reproduce:**
Unkowen
![Annotation 2020-05-22 021104](https://user-images.githubusercontent.com/61591052/82620954-0fe40900-9bda-11ea-9729-23a13c6b950e.png)

**Comment by KoBeWi** [comment]
Could you attach the affected script?

**Comment by Gerarama** [comment]
Sure, Here is the one in the image.
[AT-Bot-Lite-MainSystem.tres.zip](https://github.com/godotengine/godot/files/4677907/AT-Bot-Lite-MainSystem.tres.zip)

**Comment by KoBeWi** [comment]
So inspecting the unnamed functions shows that their `resource_name` is empty. How they were created? Is the script imported from older Godot version?

**Comment by Gerarama** [comment]
No , the functions were created at the same version of Godot.

**Comment by fire** [comment]
Spooky ghosts. Will archive. Feel free to ask to reopen.
