### ISSUE TITLE
Viewport render to ViewportTexture after dynamic reparenting and moving nodes

### ISSUE THREAD

**Issue by beetbeet** [godotengine/godot#38950]
**Godot version:**
3.2.1
**OS/device including version:**
Windows 10

**Minimal reproduction project:**
https://1drv.ms/u/s!Arug_xB8WkZQtFRNDgHJ-GwbbneK?e=PnlxAB

**Issue description:**

I have scene MovingAndReparenting.tscn:

```
Spatial
-MeshInstance
-DirectionalLight
-Camera
-Spatial1
--Viewport
--MeshInstance
--Camera
```

I want to render Viewport content to ViewportTexture of first MeshInstace.

Unfortunately I have to move the node of Spatial1 to another place of the scene in space at the start function.

That's why the objects I render to Viewport are not its children at start. (Viewport is not a Spatial type, so they would not move to a new place in space).

After moving Spatial1 node to a new place and reparent child nodes to Viewport there is nothing projected from Viewport.

Script for that scene:

```
extends Spatial

onready var master_node = get_node("/root/Spatial/Spatial1")
onready var viewport_node = get_node("/root/Spatial/Spatial1/Viewport")
onready var mesh_node = get_node("/root/Spatial/MeshInstance")

func _ready():

	# translate Spatial1 to new location
	master_node.set_translation(Vector3(100,0,0))

	# parent all nodes to Viewport node
	for N in master_node.get_children():
		# leave first node because it is a Viewport
			if N != master_node.get_child(0):
				var node = N
				master_node.remove_child(node)
				# translate also child nodes
				node.set_translation(master_node.get_translation())
				viewport_node.add_child(node)
				node.set_owner(viewport_node)

	# set viewport texturte to mesh node albedo
	mesh_node.get_surface_material(0).albedo_texture = viewport_node.get_texture()
```

But scene tree is correct i think:

```
Spatial
-MeshInstance
-DirectionalLight
-Camera
-Spatial1
--Viewport
---MeshInstance
---Camera
```

In that project i made also scene WithoutMovingAndReparenting.tscn where:

- I place Spatial1 node and his child nodes to another place in scene in editor without any reparenting script operations.

Script for that scene:

```
extends Spatial

onready var viewport_node = get_node("/root/Spatial/Spatial1/Viewport")
onready var mesh_node = get_node("/root/Spatial/MeshInstance")

func _ready():
	# set viewport texturte to mesh node albedo
	mesh_node.get_surface_material(0).albedo_texture = viewport_node.get_texture()
```

And it that case Viewport works good.

Does anyone have any idea why this is happening?

How to deal with such a problem? Doesn't Viewport update the data correctly?

**Comment by clayjohn** [comment]
The ``ViewportTexture`` takes a path to the ``Viewport``. When you move the ``Viewport`` then the path no longer points to the correct place, you need to update the nodepath in the ``ViewportTexture``

Just take a look at the docs for ``ViewportTexture`` https://docs.godotengine.org/en/latest/classes/class_viewporttexture.html#class-viewporttexture-property-viewport-path

**Comment by beetbeet** [comment]
@clayjohn Hello, so i do this:

`mesh_node.get_surface_material(0).albedo_texture.set_viewport_path_in_scene("/root/Spatial/Spatial1/Viewport")`

my new _ready() function:
```
func _ready():

	# translate Spatial1 to new location
	master_node.set_translation(Vector3(100,0,0))

	# parent all nodes to Viewport node
	for N in master_node.get_children():
		# leave first node because it is a Viewport
			if N != master_node.get_child(0):
				var node = N
				master_node.remove_child(node)
				# translate also child nodes
				node.set_translation(master_node.get_translation())
				viewport_node.add_child(node)
				node.set_owner(viewport_node)


	# set viewport texturte to mesh node albedo
	mesh_node.get_surface_material(0).albedo_texture = viewport_node.get_texture()
	# update viewport path
	mesh_node.get_surface_material(0).albedo_texture.set_viewport_path_in_scene("/root/Spatial/Spatial1/Viewport")
```

And nothing happens :/

**Comment by beetbeet** [comment]
Ok, i have a wrong Camera position to see Viewport contents :)

But could someone explain why when you save a scene to the tscn file you can't see the children of Vieweport Node?
