### ISSUE TITLE
WebSocketClient disconnects on receipt of >64kB packet without any signals

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot#38959]
**Godot version:**  
3.2.1.stable

**OS/device including version:**  
Windows10

**Issue description:**
When trying to implement a very primitive VOIP system of recording and sending 1second chunks over a websocket using a server written in node-red as the relay, I discovered that, while the Godot client had no problem calling `PacketPeer.put_packet()` with several hundred kB chunks of data,  everything stopped if I sent a packet of >64000 bytes from the server back to the Godot client's websocket.  

**Steps to reproduce:**
See below

**Minimal reproduction project:**
This project has both the WebSocketClient and the WebSocketServer to make reproduction easier.
Type 64000 in the text box, hit button and it sends. Change to 65000 and the server disconnects.  

The PacketPeer object is set to null on the client, without calling the signals "connection_closed", "connection_error", or "server_close_request" as I would have expected.  

Two further  buttons are in the project to call client.disconnect and server.disconnect to prove that these signals are function as expected.

[websocketlimittest.zip](https://github.com/godotengine/godot/files/4668073/websocketlimittest.zip)

**Comment by Calinou** [comment]
cc @Faless

**Comment by jamie-pate** [comment]
![websocket_close_handshake_from_client](https://user-images.githubusercontent.com/682658/108566938-1663f600-72bc-11eb-8645-1b00dfab1c6c.png)
Looks like the websocket client sends the close handshake, but doesn't send any of the signals to the game code :(

**Comment by jamie-pate** [comment]
![image](https://user-images.githubusercontent.com/682658/108569050-17972200-72c0-11eb-864c-35dee3a4d824.png)

**Comment by jamie-pate** [comment]
Turns out that In nodejs I wasn't logging the event object which has the 1009 code:
`const wsClose = event => {console.log('Close event', event); wsocket.removeEventListener('close', wsClose)}`
`wsocket.addEventListener('close', wsClose);`

This would have saved me a lot of time.

I still get no error signal though when 1009 is sent to the server, and the event doesn't get raised on the server until i close the websocket connection after a timer event!

**Comment by Faless** [comment]
Closeing as fixed via #66594 (the base `WebSocketPeer`s no longer emits signals, and the multiplayer peer should now emit the appropriate disconnect).
