### ISSUE TITLE
Screen space reflection goes black/stretches out when object edge blocked/off screen (3.x)

### ISSUE THREAD

**Issue by puchik** [godotengine/godot#38955]
**Godot version:**
3.2.2 beta 8cf450c
**OS/device including version:**
Windows 10 1909
**Issue description:**
Edges of objects "reflect black" or get stretched out if you start blocking (off screen?) what they should be reflecting. If you keep increasing the angle, the reflection goes away. Possibly it's tracing past the screen/margins aren't working for the black reflection? 

For the stretching, it might be taking the last bit of information it found and using that to make the reflection. (See below comment for picture of stretching)

**Steps to reproduce:**
1. Add either a shiny wall or floor.
2. Slowly turn camera so it starts blocking where its reflected objects would appear.

Top to bottom
![image](https://user-images.githubusercontent.com/48544263/82646987-57629900-9bca-11ea-927c-3b868c61de90.png)
![image](https://user-images.githubusercontent.com/48544263/82647006-5e89a700-9bca-11ea-83cc-0e5154a8d471.png)

Sides
![image](https://user-images.githubusercontent.com/48544263/82647075-7b25df00-9bca-11ea-80c8-6f0a6f83a244.png)
![image](https://user-images.githubusercontent.com/48544263/82647062-73fed100-9bca-11ea-9548-16b99fb5bfee.png)

Seems to be worse with larger objects/if you scale the first floor larger.
![image](https://user-images.githubusercontent.com/48544263/82647155-a14b7f00-9bca-11ea-9429-e0742050f9c9.png)
![image](https://user-images.githubusercontent.com/48544263/82647168-a6a8c980-9bca-11ea-82c8-92886d06cca4.png)

**Minimal reproduction project:**
[ssr-black-reflection.zip](https://github.com/godotengine/godot/files/4666899/ssr-black-reflection.zip)

**Comment by puchik** [comment]
Actually I think this is more of a stretching effect, but when there is only the background/sky, the reflection is black. See:

![image](https://user-images.githubusercontent.com/48544263/82710821-b101ac80-9c38-11ea-9229-f3ef92b86d71.png)

The expected behaviour here would probably be to stop the reflection, not stretch out the last available bits of information.

**Comment by puchik** [comment]
So it turns out it _is_ the margins not being cut off. The stretching and "blackness" only shows for the top and right of the screen, not the left or bottom. After multiplying the screen size of the check by 0.5 it works (partially) as expected.

However, there is still some stretching, but that's caused by how the margin is faded out. If you only fix the above, you get something like this:

![image](https://user-images.githubusercontent.com/48544263/82723742-f00a1f00-9c85-11ea-8856-a191f2fac3e5.png)

It's a lot better but there's still some unusual stretching happening. The reason I'm saying this is because it seems to be _intentional_, There is an _external_ margin set, so it stretches out some of the reflection and only then starts fading it out. If you switch to an internal margin that fades towards the edges of the screen you get something closer to this:

![image](https://user-images.githubusercontent.com/48544263/82723796-470ff400-9c86-11ea-8121-92968b89303e.png)


This looks nicer, but before making a PR I was wondering if I'm missing something? The external margins are clearly done on purpose but they seem to be doing more harm than good. There's "more" reflection but it's noticeably fake.

**Comment by akien-mga** [comment]
Fixed by #41892.
