### ISSUE TITLE
Position transform is not working for instanced scene nodes that have bones with IK

### ISSUE THREAD

**Issue by MeiHouwang** [godotengine/godot#3896]
If you have and instanced scene added as a node, and this scene have animation with bones and IK, any transforms for this node relative to parent stopping working - it stays at the same position, rotation and scale as at the moment it was added to the parent. You can move it in the editor and transforms will be showed in the editor, but in the actual play mode they are stopping working. This is leading to very confusing state when positions of things on the game screen are suddenly very different from that was placed in the editor.

[error.zip](https://github.com/godotengine/godot/files/153731/error.zip)

**Comment by henkz1** [comment]
Your animation, which is set to autoplay, resets the position and rotation. The "Node2D" in main containing your subscene is the same node as the subscenes "Node2D"(which is animated).

**Comment by MeiHouwang** [comment]
>The "Node2D" in main containing your subscene is the same node as the subscenes "Node2D"(which is animated).
Whaaaaaat? How is that even possible??? You mean, ALL root objects in all instanced scenes are acting as the same one?????

**Comment by MeiHouwang** [comment]
I got it, animation was affecting root node of the scene. My bad, sorry.
