### ISSUE TITLE
TextureArray reported as null in the debugger, when it isn't

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#38965]
Godot 3.2.1

I have a `TextureArray` resource in my project (atlas image imported as TextureArray). I want to load it with `load` in GDScript, but no matter what I try, it always reports as `null` in the debugger. But if I print it, I get `[TextureArray:1171]`.

Test project:
[LoadTextureArray.zip](https://github.com/godotengine/godot/files/4669798/LoadTextureArray.zip)
Put a breakpoint at the `print` statement in `main.gd`, and start the scene.

**Comment by rileylyman** [comment]
Deleting the `.import` folder within your project files fixed the problem for me.

**Comment by rileylyman** [comment]
@Zylann Does deleting the folder yield any results?

**Comment by Zylann** [comment]
@rileylyman that's one way of doing it, since Godot holds a lock on the file in `.import` basically. For some reason it does that and never releases it as soon as it loads the resource...

**Comment by baptr** [comment]
I'm guessing this is a dupe with #36801 - variables greater than 1MiB in size are hidden by the debugger.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/36801.
