### ISSUE TITLE
Godot editor hang on "Play Project"

### ISSUE THREAD

**Issue by nj-designs** [godotengine/godot#38975]
**Godot version:**
v3.2.stable.mono.official

**OS/device including version:**
Apple Mac mini (2018)

macOS Catalina (10.15.4)

**Issue description:**
Had been performing usual work flow of creating scences, editing C# scripts (VSCode external editor).

Clicked "Play",  Godot editor just froze. Unable to easily kill process.

Note, targeting local Mac OSX application.

**Steps to reproduce:**
Unfortunately not repeatable, but crash logs attached below. Will update issue with more information if I can repeat.
[crash.zip](https://github.com/godotengine/godot/files/4671362/crash.zip)

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
Duplicate of #37713, fixed in 3.2.2.

**Comment by Mirodil** [comment]
I see the same issue. What was solution for this?
