### ISSUE TITLE
glTF2 blender 2.82 export error with inherit rotation 

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#38971]
**Godot version:**
![Captura de pantalla_2020-05-22_17-51-37](https://user-images.githubusercontent.com/12847027/82708554-ea481580-9c54-11ea-8101-9f73fd30eb7c.png)

**OS/device including version:**
![Captura de pantalla_2020-05-22_17-54-03](https://user-images.githubusercontent.com/12847027/82708702-4a3ebc00-9c55-11ea-9589-4b6e2d322d68.png)

**Issue description:**
The problem has to do with inheriting the rotation of the bones, in Blender3D there is an option that allows some bones to inherit rotations, the problem is that when importing into Godot the bones inherit the rotations although the Blender3D option is disabled.
![Captura de pantalla_2020-05-22_17-55-56](https://user-images.githubusercontent.com/12847027/82708827-95f16580-9c55-11ea-9502-708290abf2ff.png)

**Steps to reproduce:**
Create a bone chain in blender3D and prevent a bone from copying the rotation, you will see that when importing godot the bones keep copying the rotations
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12847027/82709166-58410c80-9c56-11ea-9629-b6c0eaef80bc.gif)
![inheret rotation](https://user-images.githubusercontent.com/12847027/82709610-57f54100-9c57-11ea-8ea5-927d1c33195a.gif)

**Minimal reproduction project:**
[rotation_blender.blend.zip](https://github.com/godotengine/godot/files/4670404/rotation_blender.blend.zip)
export model in gltf to Godot Engine and test rotation.

**Comment by fire** [comment]
Bug in blender export and not in Godot GLTF2 import.

https://github.com/KhronosGroup/glTF-Blender-IO/pull/880

**Comment by kone9** [comment]
> Bug in blender export and not in Godot GLTF2 import.
> 
> [KhronosGroup/glTF-Blender-IO#880](https://github.com/KhronosGroup/glTF-Blender-IO/pull/880)
> 
> Expected to be fixed when this pull request is merged, which is the next Blender stable version (Not the one in 2 weeks) so maybe 5+ months.

ok,thanks

**Comment by fire** [comment]
Please comment if you are able to use that pull request to import your model into Godot Engine and close the issue.

**Comment by kone9** [comment]
In the end I could not solve this problems with the rotation we will have to wait for the improvement in the plugin.

**Comment by kone9** [comment]
> Please comment if you are able to use that pull request to import your model into Godot Engine and close the issue.

Ok,thanks
