### ISSUE TITLE
C# "WARNING: cleanup: ObjectDB Instances still exist! At: core/object.cpp:2135."

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#38977]
**Godot version:**
Godot_v3.2.2-beta2_mono_x11_64

**OS/device including version:**
5.6.14-arch1-1
mono-msbuild 16.5.xamarinxplat.2020.02.20.11.54-1
mono 6.4.0.198-2

**Issue description:**
This error appears, when quitting the Godot Editor:
`WARNING: cleanup: ObjectDB Instances still exist! At: core/object.cpp:2135.`

**Steps to reproduce:**
1. Generate a new Mono project.
2. Add a node and attach a .cs-script. Save as main scene.
3. Add a new cs-script (public class) to your project.
4. Call that new class from your main scene.

**Minimal reproduction project:**
https://github.com/JupiterRider/cleanup_bug

**Comment by neikeq** [comment]
Can you run it in verbose mode (`-v`) to see if there is any extra message?

**Comment by JupiterRider** [comment]
> Can you run it in verbose mode (`-v`) to see if there is any extra message?

`[jupiterrider@linuxpc ~]$ ./GodotProjects/Godot_v3.2.2-beta2_mono_x11_64/Godot_v3.2.2-beta2_mono_x11.64 -v 
Godot Engine v3.2.2.beta2.mono.official - https://godotengine.org
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Only one GPU found, using default.
Failed loading custom cursor: X_cursor
Using GLES3 video driver
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.36.0, 5.6.14-arch1-1, LLVM 10.0.0)
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
 
Mono: Initializing module...
Mono JIT compiler version 6.6.0 ((no/d9001b5)
Mono: Logfile is: /home/jupiterrider/.local/share/godot/mono/mono_logs/2020_05_23 16.55.06 (4523).txt
Mono: Runtime initialized
Mono: Loading assembly mscorlib...
Mono: Assembly mscorlib loaded from path: /home/jupiterrider/GodotProjects/Godot_v3.2.2-beta2_mono_x11_64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll
Mono: Loading scripts domain...
Mono: Creating domain 'GodotEngine.Domain.Scripts'...
Mono: INITIALIZED
Mono: Loading assembly GodotSharp...
Mono: Assembly GodotSharp loaded from path: /home/jupiterrider/GodotProjects/Godot_v3.2.2-beta2_mono_x11_64/GodotSharp/Api/Debug/GodotSharp.dll
Mono: Loading assembly GodotSharpEditor...
Mono: Assembly GodotSharpEditor loaded from path: /home/jupiterrider/GodotProjects/Godot_v3.2.2-beta2_mono_x11_64/GodotSharp/Api/Debug/GodotSharpEditor.dll
Mono: Loading assembly GodotTools...
Mono: Assembly GodotTools loaded from path: /home/jupiterrider/GodotProjects/Godot_v3.2.2-beta2_mono_x11_64/GodotSharp/Tools/GodotTools.dll
Mono: Loading assembly GodotTools.ProjectEditor...
Mono: Assembly GodotTools.ProjectEditor loaded from path: /home/jupiterrider/GodotProjects/Godot_v3.2.2-beta2_mono_x11_64/GodotSharp/Tools/GodotTools.ProjectEditor.dll
Mono: Loading assembly UnnamedProject...
Mono: Failed to load project assembly
CORE API HASH: 8870088880104701186
EDITOR API HASH: 3192910446645059831
Loading resource: res://.config/godot/editor_settings-3.tres
EditorSettings: Load OK!
EditorSettings: Save OK!
Loaded builtin certs
Editing project: /home/jupiterrider/GodotProjects/cleanup_bug/Test (::home::jupiterrider::GodotProjects::cleanup_bug::Test)
Godot Engine v3.2.2.beta2.mono.official - https://godotengine.org
EditorSettings: Save OK!
Mono: Finalizing scripts domain...
Mono: Unloading scripts domain...
Mono: Runtime cleanup...
Mono: Finalized
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.36.0, 5.6.14-arch1-1, LLVM 10.0.0)
 
Mono: Logfile is: /home/jupiterrider/.local/share/godot/mono/mono_logs/2020_05_23 16.55.08 (4565).txt
[jupiterrider@linuxpc ~]$ Running: /home/jupiterrider/GodotProjects/Godot_v3.2.2-beta2_mono_x11_64/Godot_v3.2.2-beta2_mono_x11.64 --path /home/jupiterrider/GodotProjects/cleanup_bug/Test --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 4565 --position 448,240
Godot Engine v3.2.2.beta2.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.36.0, 5.6.14-arch1-1, LLVM 10.0.0)
 
Mono: Logfile is: /home/jupiterrider/.local/share/godot/mono/mono_logs/2020_05_23 16.55.13 (4643).txt
Hello World!
debugger-agent: Unable to listen on 17
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2135.`

**Comment by akien-mga** [comment]
The flag was only used in the project manager and not passed to the running project, you can edit the project directly with the flag using:
```
/home/jupiterrider/GodotProjects/Godot_v3.2.2-beta2_mono_x11_64/Godot_v3.2.2-beta2_mono_x11.64 --path /home/jupiterrider/GodotProjects/cleanup_bug/Test -v
```

**Comment by JupiterRider** [comment]
`Mono: Finalized
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2135.
Leaked instance: Node:1179 - Node name: 
Orphan StringName: Node
StringName: 1 unclaimed string names at exit.`

**Comment by akien-mga** [comment]
There's no reproduction to download anymore to confirm, but this is likely the same issue as #44226. If you create class instances which inherit from `Object` (e.g. `Node`), those are not reference counted and you should make sure to have them freed as needed. This is typically handled for you by the Scene Tree *if* you add the node to the scene tree with `AddChild()`. If you leave it hanging, it won't be freed until you free it manually.
