### ISSUE TITLE
Errors with GodotPayment dependency when building Android template

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#38987]
**Godot version:**
Master 07ada02cb44af22905991b558af6a4a531de44a7

**OS/device including version:**
Windows 10

**Issue description:**
Android build process failed during the configuration phase when trying to build using gradle command line.

```
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Failed to transform file 'GodotPayment.release.aar' to match attributes {artifactType=jar}
      > Execution failed for JetifyTransform: C:\dev\source\godot\platform\android\java\app\libs\plugins\GodotPayment.release.aar.
         > Failed to transform 'C:\dev\source\godot\platform\android\java\app\libs\plugins\GodotPayment.release.aar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=C:\dev\source\godot\platform\android\java\app\libs\plugins\GodotPayment.release.aar, to=C:\Users\bourr\.gradle\caches\transforms-2\files-2.1\cd1907ae86e9ea83836dc2e98a7c8c21\jetified-GodotPayment.release.aar)'. (Run with --stacktrace for more details.)
```

So it seems a debug build is looking for GodotPayment release aar?

After searching in the code I was able to pass this build step when disabling this line in `platform/android/java/app/config.gradle`:
`Set<String> binDeps = [/"libs/plugins/GodotPayment.release.aar"]`
using:
`Set<String> binDeps = [/*"libs/plugins/GodotPayment.release.aar"*/]`

But I'm not sure what the proper fix would be.

**Steps to reproduce:**
- Go to `platform/android/java`
- run `gradlew build`

**Minimal reproduction project:**
n/a

**Comment by pouleyKetchoupp** [comment]
@m4gr3d Help please :)

**Comment by m4gr3d** [comment]
@pouleyKetchoupp You're supposed to use the `gradlew generateGodotTemplates` build command instead as it sets the right build dependencies.

**Comment by m4gr3d** [comment]
Take a look at https://github.com/godotengine/godot/blob/46450979dbcb6014957d8849c98efa81d0c921f4/platform/android/java/build.gradle#L137 and you'll see it adds a dependency to a task that generates the GodotPayment library.

**Comment by pouleyKetchoupp** [comment]
Thanks for info! I had missed the change in build commands some time ago and didn't look at the doc, my bad.

**Comment by m4gr3d** [comment]
@pouleyKetchoupp no problem! 
It may make sense to update the default `build` target for that directory to depend on the `generateGodotTemplates` task since that'll most likely be the intent.
