### ISSUE TITLE
Can't disable custom android plugin

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#38986]
**Godot version:**
3.2.2 beta3

**OS/device including version:**
Windows 10

**Issue description:**
I sucessfully created an Android plugin using the new v1 system and deployed it on a phone. I then disabled it in the export settings, built again and got this gradle error:

![1](https://user-images.githubusercontent.com/8750135/82733352-8a647400-9d13-11ea-8d6c-a89d95018cb3.PNG)
![2](https://user-images.githubusercontent.com/8750135/82733358-92bcaf00-9d13-11ea-9c7f-1a240e7c9c2c.PNG)

The only way to fix this is to either:
- Enable the plugin again
- Clear/delete the `build` folder and rebuild

Note that i never enabled the GodotPayment plugin.

**Steps to reproduce:**
1. Enable custom Android template build
2. Add a barebones custom plugin to `plugins` folder
3. Enable it in export settings and build -> builds fine
4. Disable it in export settings and build -> build error

**Comment by m4gr3d** [comment]
Looking into it. We may need to automatically delete the `res://android/build/build` directory when we detect a dependency is newer than it.

**Comment by mbrlabs** [comment]
@m4gr3d @akien-mga I have a PR ready, that would fix this but i only tested it on the 3.2 branch since   i'm not sure if android builds are currently possible on master? Since this is easily cherry-pickable i'm just going to open this against master for now.
