### ISSUE TITLE
Tool Export Variable Resets When Scene Closes

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#38999]
**Godot version:**
3.2.1

**OS/device including version:**
OSX

**Issue description:**
I set my export variable on a tool node and it resets when the scene is closed.

**Steps to reproduce:**
1. Open Main.tscn
2. Select the "Regions" 
3. Change the Collision Out Path export variable.
4. Save
5. Close the scene
6. Open it again

Expected: Collision Out Path is persistent
Actual: It gets reset to the default

The scene file contains the value for the export variable but it does not use it, it's really frustrating haha

Please, I'd really like a workaround or a solution if I'm doing something wrong. This is really blocking for me :/

**Minimal reproduction project:**
I wasn't able to create a "minimal reproduction project", so I deleted most of the unnecessary nodes in my project. It's still pretty small and easy to work with, there's isn't much going on. Just 3 small tool scripts.

[gear_game.zip](https://github.com/godotengine/godot/files/4672858/gear_game.zip)

**Comment by Error7Studios** [comment]
As far as I know, if you try to use `get_path()`, `get_node()`, `get_parent()` etc. on a tool script, it will either result in an error or return null, unless the scene is actually running, since the tool script isn't considered to be in the SceneTree.

As a workaround, you can instead just check on` _ready()` that the node is valid.

This works:

```
tool
extends Node

var _collision_out_node: Node = null

export var _collision_out_path: NodePath setget _collision_out_path_set, _collision_out_path_get
func _collision_out_path_set(__path: NodePath): _collision_out_path = __path
func _collision_out_path_get() -> NodePath: return _collision_out_path

func assert_collision_out_node_if_running():
	if !Engine.editor_hint:
		assert(self.is_inside_tree())
		_collision_out_node = get_node(_collision_out_path)
		if !_collision_out_node:
			print("_collision_out_path: ", _collision_out_path)
			print("_collision_out_node: ", _collision_out_node)
			assert(false)

func _ready() -> void:
	assert_collision_out_node_if_running()
	get_tree().connect('node_added', self, '_on_node_added')
```

**Comment by Lucrecious** [comment]
I'm actually dumb. Thanks @Error7Studios 

Closed.
