### ISSUE TITLE
3dparticles in editor dont match the ones in game

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#3899]
**Operating system or device:** Linux

**Issue description:** I have to spend quite a lot of time (as I think everyone does) to tune the particle system to match exactly what I want. After running the game, the particles are totally different from what I was looking at in the editor (mainly, slower/faster)

**Steps to reproduce:** Create a particle system and tweak some values. Notice how they behave, their speed and movement. Play the game and compare.

**Comment by MarianoGnu** [comment]
This is not very likely, but maybe a randomize() call is necesary to ensure values takes the hole spectrum of the random ranges...

**Comment by nunodonato** [comment]
I have all rand params at 0

Às 13:55 de 02-03-2016, Mariano Javier Suligoy escreveu:
>
> This is not very likely, but maybe a randomize() call is necesary to 
> ensure values takes the hole spectrum of the random ranges...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/godotengine/godot/issues/3899#issuecomment-191246944>.
>

-- 
Nuno Donato
nuno@estudiodigital.pt | 966956602

estúdio digital <http://www.estudiodigital.pt>
www.estudiodigital.pt
Programação e Artes Digitais

**Comment by kubecz3k** [comment]
@nunodonato Could you maybe provide sample project? Something we can work with? I created a particle effect and unfortunately I can't reproduce your issue...

**Comment by nunodonato** [comment]
I'll try to send something later today.
I've been getting lots of strange issues with 3d particles. for 
instance, I duplicated a particle node, and without changing any 
parameters, the particles behave differently (slower)

Às 14:03 de 02-03-2016, kubecz3k escreveu:
>
> @nunodonato <https://github.com/nunodonato> Could you maybe provide 
> sample project? Something we can work with? I created a particle 
> effect and unfortunately I can't reproduce your issue...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/godotengine/godot/issues/3899#issuecomment-191248806>.
>

-- 
Nuno Donato
nuno@estudiodigital.pt | 966956602

estúdio digital <http://www.estudiodigital.pt>
www.estudiodigital.pt
Programação e Artes Digitais

**Comment by reduz** [comment]
3D particles will be rewritten in 3.0 to use GPU

**Comment by nunodonato** [comment]
this can probably be closed
