### ISSUE TITLE
Auto-completion for dictionary keys no longer works since 3.2.2beta3 (worked in 3.2.2beta2)

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#38998]
**Godot version:**
3.2.2beta3

**OS/device including version:**
Windows 10

**Issue description:**
Auto-completion for dictionary keys no longer works.

**Working in _3.2.2beta2_**
![Beta 2 Autocomplete Working](https://user-images.githubusercontent.com/60025044/82744008-a9c1c800-9d38-11ea-9200-c206322ab9e5.png)

**Not Working in _3.2.2beta3_**
![Beta 3 Autocomplete Not Working](https://user-images.githubusercontent.com/60025044/82744013-b2b29980-9d38-11ea-8c27-fbd7d22aea8c.png)

**Steps to reproduce:**
Create a dictionary with string keys.
Write `<dict_name>.` and see that autocompletion is not working in 3.2.2beta3

**Minimal reproduction project:**
[Dict Autocomplete Regression Bug.zip](https://github.com/godotengine/godot/files/4672836/Dict.Autocomplete.Regression.Bug.zip)

**Comment by akien-mga** [comment]
CC @ThakeeNathees @vnen
