### ISSUE TITLE
Keyboard Zoom does not work with keypad

### ISSUE THREAD

**Issue by AllenKll** [godotengine/godot#38991]
**Godot version:** 3.2.1

**OS/device including version:** Win10

**Issue description:**

Hovering over mouse zoom indicates that pressing "Ctrl+-" should zoom out.  This works if you use the minus key next to the Zero on a Standard US keyboad, but DOES NOT work with the minus key on the numpad.

Also, zooming in with Ctrl++ using the numpad's plus does not work.  while zooming with Ctrl-= does.  Ctrl-= doesn't even make sense... should be Ctrl++ to match zoom out.

**Steps to reproduce:**

Start new project, attempt to zoom out with Ctrl+- using the minus on the numpad

**Minimal reproduction project:** None needed.

**Comment by Calinou** [comment]
See #23905.
