### ISSUE TITLE
How to translate the project settings and details panel into a certain language, such as Chinese and Japanese, is still English as far as I know.

### ISSUE THREAD

**Issue by txj-mssl** [godotengine/godot#38997]
Godot version: 3.2.1

OS/device including version: Win10

Issue description:
How to translate the project settings and details panel into a certain language, such as Chinese and Japanese, is still English as far as I know.
Steps to reproduce:None needed.
Minimal reproduction project: None needed.

**Comment by vnen** [comment]
Duplicate of #14582
