### ISSUE TITLE
Browsing for resources in scn/xscn/xml files

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#390]
Just wondering if it would be possible to treat a scene as a directory when searching for resources. I think this would mainly be useful as I could find view-ports that are render targets easier than just knowing the path their in, and sharing resources across scenes would be easier to set up.

**Comment by akien-mga** [comment]
There are already tools in the Filesystem dock to track down the dependencies between scenes and resources, so I guess this is solved somehow.
