### ISSUE TITLE
"Editable Children" becomes unchecked when instanced scene is renamed.

### ISSUE THREAD

**Issue by sungvzer** [godotengine/godot#39005]
**Godot version:** v3.2.1.stable.official

**OS/device including version:** Windows 10 18363

**Issue description:** When using an Inherited scene, "Editable Children" becomes unchecked when the inherited scene gets renamed.

**Steps to reproduce:** 
1. Create a scene with some node elements
2. Instance it in another scene
3. Check "Editable Children"
4. Rename the instanced scene
![2020-05-24 10-38-52](https://user-images.githubusercontent.com/52582911/82749718-72d8ca00-9dab-11ea-8b54-fc0f5ebd48b8.gif)

**Comment by hilfazer** [comment]
It also happens if any ancestor to node in question gets renamed.
But when the name is changed back Editable Children is back to checked status.

.tscn file keeps editable children like this
`[editable path="Lines/integer"]`
and those paths don't get updated on node rename.

**Comment by hilfazer** [comment]
It's fixed on 3.3 RC 6, by this PR: https://github.com/godotengine/godot/pull/39533.
