### ISSUE TITLE
Why is Vulkan's queue priority set to 0.0f?

### ISSUE THREAD

**Issue by hbina** [godotengine/godot#39000]
https://github.com/godotengine/godot/blob/57d21ebeda8460036efac1f70cd9ecd0896de517/drivers/vulkan/vulkan_context.cpp#L513

According to the spec,

```
The priority of each queue is a normalized floating point value between 0.0 and 1.0, which is then translated to a discrete priority level by the implementation. Higher values indicate a higher priority, with 0.0 being the lowest priority and 1.0 being the highest.
```

Is there a reason for this?

**Comment by clayjohn** [comment]
This really isn't an appropriate place to ask a question like this. The issue tracker is for bug reports only. If you have questions about how vulkan works, I highly recommend the r/vulkan subreddit. It is very active and the community is very helpful.

Again, the issue tracker is only for bug reports, right now you are piling on top of the already overwhelming number of reports and making it more difficult for contributors to meaningfully contribute. 

That being said, I will still answer your question. The priority value only matters when you have multiple queues from the same family competing for resources and you want the drivers to prioritize one queue over another. This can be useful for certain async operations. For Godot, both queues have the same priority, so it doesn't matter if they are both set to ``1.0`` or ``0.0``. What matters is that they are set to the same priority.

**Comment by hbina** [comment]
okay, my bad
