### ISSUE TITLE
Pressing Enter in Project Manager does not edit the project in 3.2.2beta2 (worked in 3.2.1)

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#39012]
**Godot version:**
Godot_v3.2.2-beta2_win64
**OS/device including version:**
Windows 7 Pro PS1 x64
**Issue description:**
Can't edit the project by selecting it and pressing Enter. It works in Godot_v3.2.1-stable_win64.
**Steps to reproduce:**
Select a project in Project Manager and press Enter
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Likely a regression from #37281 (CC @ThakeeNathees).
It could be that the commit should not have been cherry-picked for the `3.2` branch and only made sense for `master`.
