### ISSUE TITLE
JNI emitSignal is broken

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#39018]
**Godot version:**
3.2, as of 7ccb146a55edc41a9dd14c10efb8dc8f4b87f14e
Code is the same as on current master, so I assume it's broken on master, too.

**OS/device including version:**
Android 9 with tools running on Linux

**Issue description:**
This issue is a bit weird and is beyond my understanding of C++.

The method that's broken is this the JNI binding of nativeEmitSignal: https://github.com/godotengine/godot/blob/f69760b4befd7348c443960b84dd5f4e1d372e17/platform/android/plugin/godot_plugin_jni.cpp#L112-L133

As stated in the title, calling `emitSignal` in Android Java code (and thus calling the linked method above` causes the following crash:
```
05-24 22:23:20.404 22610 22642 E godot   : **ERROR**: Method failed. Returning: ERR_BUG
05-24 22:23:20.404 22610 22642 E godot   :    At: core/io/marshalls.cpp:1384:encode_variant() - Method failed. Returning: ERR_BUG
05-24 22:23:20.404 22610 22642 E godot   : **ERROR**: Failed to encode variant.
05-24 22:23:20.404 22610 22642 E godot   :    At: scene/debugger/script_debugger_remote.cpp:116:_put_variable() - Failed to encode variant.
05-24 22:23:20.404 22610 22642 E godot   : **ERROR**: Method failed. Returning: ERR_BUG
05-24 22:23:20.404 22610 22642 E godot   :    At: core/io/marshalls.cpp:1384:encode_variant() - Method failed. Returning: ERR_BUG
```

It may be obvious why this doesn't work, but for me it isn't. The only thing I remembered was that `GodotLib.calldeferred` does work and that the JNI C++ method for `GodotLib.calldeferred` looks very similar to the one for `emitSignal`. So I hacked something together for the `emitSignal` C++ code that works similarly to the `calldeferred` one functionally:

```cpp
JNIEXPORT void JNICALL Java_org_godotengine_godot_plugin_GodotPlugin_nativeEmitSignal(JNIEnv *env, jobject obj, jstring j_plugin_name, jstring j_signal_name, jobjectArray j_signal_params) {

	String singleton_name = jstring_to_string(j_plugin_name, env);

	ERR_FAIL_COND(!jni_singletons.has(singleton_name));

	JNISingleton *singleton = jni_singletons.get(singleton_name);

	String signal_name = jstring_to_string(j_signal_name, env);

	int count = env->GetArrayLength(j_signal_params);
	Variant args[count];

	for (int i = 0; i < count; i++) {

		jobject j_param = env->GetObjectArrayElement(j_signal_params, i);
		if (j_param)
		  args[i] = _jobject_to_variant(env, j_param);
		
		env->DeleteLocalRef(j_param);
	};

	if (count == 1) singleton->emit_signal(signal_name, args[0]);
	if (count == 2) singleton->emit_signal(signal_name, args[0], args[1]);
}
```

I don't know why, but **that one works** but there has to be a better solution. 😅

CC: @m4gr3d who wrote the original code

**Steps to reproduce:**
Call `emitSignal` from Java with at least one signal parameter.

**Minimal reproduction project:**
N/A

**Comment by m4gr3d** [comment]
@timoschwarzer Can you provide the arguments you were passing to the `emitSignal` call that caused the crash.

**Comment by timoschwarzer** [comment]
Just a simple String is enough. e.g. `emitSignal("my Signal", "Hello World")`

**Comment by timoschwarzer** [comment]
I don't know if it makes a difference, but I am running the app in debug mode (launched directly from the editor by clicking the Android run button in the top right corner) and in my signal handler GDScript function I just print the string.

```
func on_my_event(arg):
    print(arg)
```

**Comment by timoschwarzer** [comment]
I also tried some other types supported by `_jobject_to_variant` (Dictionary etc.) and they result in the same crash.
