### ISSUE TITLE
Built-in script warning overlaps buttons

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39017]
**Godot version:**
3.2.2 beta3

**Issue description:**
![HRQnUgE8kT](https://user-images.githubusercontent.com/2223172/82762150-b6f5ba00-9dff-11ea-8537-d63e32d4be19.gif)

CC @Calinou 

EDIT:
It only happens first time you create a script.

**Comment by Calinou** [comment]
Maybe it can be solved by setting the minimum size of the panel again after the value of the Built-In Script checkbox is changed?

**Comment by KoBeWi** [comment]
This problem does not exist on master branch:
![cLQW7T2CK6](https://user-images.githubusercontent.com/2223172/83521715-e8494680-a4df-11ea-8693-11330f716a00.gif)

The issue needs to be fixed before 3.2.2 stable (or reverted on 3.2 branch). I assume putting `minimum_size_changed()` here
https://github.com/godotengine/godot/blob/030a26206ff70b1050c885270afce89b0430af70/editor/script_create_dialog.cpp#L508-L517
would fix this, but I don't feel like compiling 3.2 branch just to check one line .-.

**Comment by mbrlabs** [comment]
@KoBeWi yeah, calling `minimum_size_changed()` after `_update_dialog()` fixes it.

**Comment by akien-mga** [comment]
Fixed by #39319.
