### ISSUE TITLE
On Windows XP the editor can't overwrite existing files

### ISSUE THREAD

**Issue by acmepjz** [godotengine/godot#3901]
**Operating system or device:**
Windows XP 32bit

**Issue description** (what happened, and what was expected):
Create a new project, say "hello_world", create a new scene and save it, edit the project settings and set the start scene, then the console window shows

> ERROR: close: Condition ' rename_error ' is true.
>    At: drivers/windows/file_access_windows.cpp:135

and the project didn't get saved (i.e. the start scene didn't changed).

**Steps to reproduce:**
Already described in issue description.

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
Sorry, windows XP is no supported

**Comment by Ace-Dragon** [comment]
Just as a reference here, as of now there will be no part of the pipeline (relating to the 3D part of Godot at least) that is compatible with XP.

The Blender developers just officially pulled support for XP (ie. Blender 2.77 will not run on that OS) amid a decision by the Python developers to do the same thing (so future versions of the Better Collada addon will not work as well).

If you really don't want to go to Windows 10 and don't mind less software options, then I hear Linux Mint has made great strides in usability features lately.
