### ISSUE TITLE
Improve discoverability of the "Manage Editor Features" dialog

### ISSUE THREAD

**Issue by LittleDev1** [godotengine/godot#39022]
last steam release**

maybe it's not a big problem but i want to use 2D pixel art setup but i can't**

**Comment by Calinou** [comment]
Are you using the editor in a language other than English?

Also, please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) when creating issues.

**Comment by LittleDev1** [comment]
I will use that next time, i'm new to github
Yes i was, but then i tried but then i tried it in english. But it just isn't showing
![Screenshot007](https://user-images.githubusercontent.com/65874829/82801970-d2f06e80-9e86-11ea-8018-2f30c48886c6.PNG)

**Comment by Calinou** [comment]
@LittleDev1 You need to click **New** before being able to edit feature profiles. This is an UX issue which will be solved by https://github.com/godotengine/godot/pull/37235.
