### ISSUE TITLE
Moving dependencies accumulates blank lines in tscn file

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39020]
**Godot version:**
3.2.2 beta3

**Issue description:**
When a scene has dependency on a file and you move the file, a blank line appears in tscn under external resources.
![9Ptc6YBNsm](https://user-images.githubusercontent.com/2223172/82765921-3b096b00-9e1b-11ea-9c2c-2189aa2b75c6.gif)
This happens ONLY if the scene isn't currently opened.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4674500/ReproductionProject.zip)
Open the tscn in text editor and move icon around.

**Comment by rileylyman** [comment]
This should be fixed by #39056 if anyone is interested in trying it out.
