### ISSUE TITLE
The first time you open a shader, the editor scrolls all the way down

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#39021]
Godot 3.2.2 beta1

Same issue as #32777.

When you open a shader to edit it for the first time, the text editor opens at the end of it and you have to scroll back up.

![image](https://user-images.githubusercontent.com/1311555/66703995-0f17fa00-ed10-11e9-96bd-ff290882ddd3.png)

**Comment by akien-mga** [comment]
Is it a regression, or was #32777 never fixed?

**Comment by Zylann** [comment]
I believe it got fixed, at least for the script editor. I don't remember if that also fixed the shader editor, but it's having the same issue now.

**Comment by KoBeWi** [comment]
I can't reproduce it.

**Comment by Zylann** [comment]
The repro might hide some extra then, because when I posted this I could reliably make it happen... but not anymore Oo

**Comment by Zylann** [comment]
Updated repro:

1) Open a shader, scroll down to line N
2) Open another shader which has less than N lines: you get scrolled all the way down.

**Comment by KoBeWi** [comment]
The problem is that the shader editor remembers previous scroll. We should either always reset it or remember per shader.
