### ISSUE TITLE
RichTextLabel missing get_text() to return string

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#3903]
Re: http://godotengine.org/qa/662/richtextlabel-do-not-have-any-way-to-return-text
It has come to my attention that RichTextLabel do not have any get_text() equivalent. Did someone forget to implement it? Surely I am not the only one that need to get all content (text) returned to me as a string for reuse?

**Comment by xelivous** [comment]
[set_bbcode()](https://github.com/godotengine/godot/blob/master/scene/gui/rich_text_label.cpp#L1912) on RichTextLabel is equivalent to [set_text()](https://github.com/godotengine/godot/blob/master/scene/gui/label.cpp#L523) on Label. (while also supporting bbcode obviously)

[get_bbcode()](https://github.com/godotengine/godot/blob/master/scene/gui/rich_text_label.cpp#L1918) on RichTextLabel is equivalent to [get_text()](https://github.com/godotengine/godot/blob/master/scene/gui/label.cpp#L551) on Label.

They both return/set the raw stored value of the text, with or without bbcode.

It might be helpful to have a function that returns the text with bbcode stripped out, but at the very least the function isn't missing. And if you don't use bbcode in the first place it'll act exactly identical.

**Comment by Tybobobo** [comment]
I am using add_text("string\n") in order to append text input per line; so using get_bbcode() will not work unless I set_bbcode(get_bbcode() + "string\n"). This is not good, as I do not want people to be able to use bbcode :)

**Comment by akien-mga** [comment]
Fixed by #5489.
