### ISSUE TITLE
GetUsedRect used in tilemap return wrong values

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#39038]
**Godot version:**

3.2.2 beta3

**OS/device including version:**

Debian 10

**Issue description:**

if I put a tile in 0,0 position the GetUsedRect return the correct values: (0,0),(1,1)

--- first test ----
If I put  a tile in (-1,-1) position the GetUsedRect return the values: (-1,-1),(1,1)
expected result: (-1,-1),(0,0)

-- second test ---
If I put  a tile in (-1,-1) position 
and a tile in (-2,-2) position the GetUsedRect return the values: (-2,-2),(2,2)
expected result: (-2,-2),(0,0)

and so on...

**Steps to reproduce:**
Set some tile in negative coordinates eg:(-1,-1)
and print GetUsedRect return value in _Ready

**Minimal reproduction project:**

NA

**Comment by groud** [comment]
This is the expected behavior, GetUsedRect returns the top-left coordinate and the size of the rect, not the top-left and the bottom-right coordinates.

**Comment by git2013vb** [comment]
Thank you :)
I checked but in doc there is not such explanation:
```
Rect2 get_used_rect ( )
Returns a rectangle enclosing the used (non-empty) tiles of the map.
```
https://docs.godotengine.org/en/stable/classes/class_tilemap.html#class-tilemap-method-get-used-rect

It can be a good idea to explain properly it in docs :)

**Comment by groud** [comment]
I am not really sure about how you printed the values, but the function returns a generic Rect2 object. All Rect2 objects are similar, so unless the Rect2 documentation is unclear, there is nothing much to be done to be honest. 

What I mean that I don't think we should have explanations common to all Rect2 returning functions  in get_used_rect() reference.

**Comment by git2013vb** [comment]
I checked in this way
scene:
Node2D
--TileMap
In tilemap the Godot icon as tile
A script attached to TileMap
```
  public override void _Ready()
    {
        GD.Print(GetUsedRect());
    }
```
case 1 when I have the tile in 0,0 position:
![image](https://user-images.githubusercontent.com/13235119/82893530-0c89ae00-9f49-11ea-85d9-9870e19455f9.png)

case 2 when I have the tile in -1,-1 position
![image](https://user-images.githubusercontent.com/13235119/82893681-478be180-9f49-11ea-824d-8b3673f3f1d4.png)


Obviously if I red the documentation I assume GetUsedRect give a wrong result because is not stated that the second result is  the "size" of the rect instead the bottom right position.. because the first one is the "position" so people like myself are assuming the second one is still a "position". That's the error in documentation.

**Comment by groud** [comment]
Probably that the way we print a Rect2 should be modified to print something like `Rect2(0, 0, 1, 1)`.
But for now, we don't even have a way to document how an object is printed. 
And I don't know how we could do it.

**Comment by git2013vb** [comment]
> Probably that the way we print a Rect2 should be modified to print something like `Rect2(0, 0, 1, 1)`.
> But for now, we don't even have a way to document how an object is printed.
> And I don't know how we could do it.

Look the Rect2 behavior is fine. What is missing is to explain clearly what are the 2th return value. Such as: the first returned value is the position where Rect2 start. The second one is the Rect2 SIZE of the whole Rect2. Because as I said before people are going to misunderstood the meaning of the second returned value.

**Comment by groud** [comment]
What you don't seem to get is that the function returns a single value, it returns a single Rect2 object.
When you do something like `GD.Print(GetUsedRect());` you are printing a single Rect2 object.

The problem here is that the printing of a Rect2 is not obvious, so we have either to document this in the Rect2 documentation, or modify the way we print it for a more obvious representation.

**Comment by git2013vb** [comment]
> What you don't seem to get is that the function returns a single value, it returns a single Rect2 object.
> When you do something like `GD.Print(GetUsedRect());` you are printing a single Rect2 object.
> 
> The problem here is that the printing of a Rect2 is not obvious, so we have either to document this in the Rect2 documentation, or modify the way we print it for a more obvious representation.

We say the same thing. Was not clear? :) I'm not a native English but I think I explain it no so bad lol.

**Comment by arostom** [comment]
I found this a useful explanation of the Rect2 returned by get_used_rect() but I came here because I found another issue with the returned value.

As you can see in the screen shot, the TileMap is 10x17 (you can simply count them) but the size is reported as 10x18 as printed in the output is -1, -1, 10, 18).  I hope I am missing something :-)

I think it should report (-1, -1, 10, 17) instead.

![Screen Shot 2020-07-29 at 7 12 12 PM](https://user-images.githubusercontent.com/1532812/88831530-c282aa00-d1cf-11ea-92f3-ca7b6f59175e.png)
