### ISSUE TITLE
Tilemap grid isn't the same as node grid

### ISSUE THREAD

**Issue by Max-Hollywood** [godotengine/godot#39035]
**Godot version:** 3.2.1.stable

**OS/device including version:** Windows 10

**Issue description:** Tilemap is set to 24 pixels, and the grid is set to 24 pixels, but the tiles seem to be 0.0000001% larger, causing a map about 70 tiles wide to have the tiles wider than they should be, which I think is affecting the rounding of the node positions to be centered on a grid, causing the nodes to get stuck.

**Steps to reproduce:**

Top left:
![tilemap_offset_topleft](https://user-images.githubusercontent.com/29140168/82807736-b88cb400-9ecb-11ea-8cd8-570760dd0411.jpg)

Bottom right:
![tilemap_offset_bottomright](https://user-images.githubusercontent.com/29140168/82807750-bfb3c200-9ecb-11ea-84d8-b1cc4f1b29a3.jpg)

**Minimal reproduction project:**

**Comment by groud** [comment]
Honesttly, I am not sure we can do anything about it. At such zoom level, this is likely the floating point precision error which becomes visible.

**Comment by Zylann** [comment]
That looks like a really big error for grid cells of 24 pixels... (unless the screenshot is taken millions of pixels away from origin)

**Comment by KoBeWi** [comment]
I can't reproduce this
![image](https://user-images.githubusercontent.com/2223172/82823538-0ee7fb80-9ea8-11ea-8a81-5f9f4e37a977.png)

**Comment by groud** [comment]
@Max-Hollywood Please upload a minimal reproduction project.
Also, you might check if your tilemap scale is not different from (1, 1), this might cause the difference.

**Comment by Max-Hollywood** [comment]
So I've set the Tilemap "Custom Transform" to 0 for all the entries ( x [24, 0, 0] and y [0, 24, 0] were there for some reason, and came up as 24.000000001), which I assume is for the "Mode" as it didn't change anything, and the **x scale had indeed been bumped up to 1.001**.

Once I changed the scale back, the grid matched, and it ran fine.

So cheers, now looking for a 24.0000001 sized hole to hide in right now.
