### ISSUE TITLE
Stepify function problem with rounding

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#39048]
**Godot version:**
3.2.2 beta 3

**OS/device including version:**
GLES 3
Ubuntu 20.04

**Issue description:**
```
float stepify(s: float, step: float)

Snaps float value s to a given step. This can also be used to round a floating point number to an arbitrary number of decimals.

stepify(100, 32) # Returns 96
stepify(3.14159, 0.01) # Returns 3.14
```
This functions seems to not return 0 when needed. In my case I'm using it to change the float precision from: **1.512364** to **1.51** for player movement
```
func movement():
	velocity = move_and_slide(velocity,Vector3.UP,true,4,PI/3)
	velocity = vector_step(velocity,0.01)
	ScreenDebugger.dict["Velocity"] = velocity # prints (X.XX,X.XX,X.XX)
	
func vector_step(vector:Vector3,step:float):
	return Vector3(stepify(vector.x,step),stepify(vector.y,step),stepify(vector.z,step))
```

the problem comes where I use the player acceleration and deacceleration, the velocity never becomes 0:

![zero](https://imgur.com/kxmYBrp.gif)

**Steps to reproduce:**
Attach this code to a 3d object
```
var velocity:Vector3
var acc:float = 0
var speed:Vector3
const MAX_SPEED = 10
const ACC:float = 3.0
const DEACC:float = .9

func _physics_process(delta):
	velocity.y += delta * -5 

	var input_forward = -int(Input.is_action_pressed("cmd_up")) + int(Input.is_action_pressed("cmd_down"))
	
	var hvel = velocity
	hvel.y = 0
	
	var target = global_transform.basis.z * input_forward * MAX_SPEED
	var acceleration = 0
	if input_forward < 0:
		acceleration = ACC
	else: acceleration = DEACC
	hvel = hvel.linear_interpolate(target, acceleration * delta)
	velocity.x = hvel.x
	velocity.z = hvel.z

	velocity = move_and_slide(velocity,Vector3.UP,true,4,PI/3)
	velocity = vector_step(velocity,0.01)
	print(str(velocity))
	
func vector_step(vector:Vector3,step:float):
	return Vector3(stepify(vector.x,step),stepify(vector.y,step),stepify(vector.z,step))

```
**Minimal reproduction project:**
N/A

**Comment by nisovin** [comment]
Seems like the change in velocity gets small enough that it can't round smaller anymore. If the change in velocity is < 0.005 per frame, then stepify will continue to round up.

Can you create a minimal project that shows that there is in fact a problem with stepify?

**Comment by groud** [comment]
This is likely a problem with your code. As @nisovin stated, your deceleration value becomes so low that stepify always return the same value. So this is very likely a problem with your implementation.

Please ask for help in the other community channels first. And if you find out a case where the stepify function does not return a correct number, please open another issue with a *minimal* example where it does not work.

**Comment by nonunknown** [comment]
@groud I know this could be a mistake of mine implementation, but my point here is the function behaviour

in this case: 1.123456789 -> stepify to X.XX -> 1.12
if the value reaches 0.001000000 the returning value should be 0 cuz it only considers the stepify chosen

**Comment by groud** [comment]
No. If you do `stepify(0.01, 0.01)` the expected result in `0.01`.
Stepify rounds to input to the closest number that is a multiple of the step value. So this result is perfectly expected.

**Comment by nisovin** [comment]
> 
> if the value reaches 0.001000000 the returning value should be 0 cuz it only considers the stepify chosen

If you do `stepify(0.001, 0.1)` it will return 0. The issue is your code never reaches that point, you never pass in a value that small.
