### ISSUE TITLE
"-" and "=" keyboard keys become "unknown" in HTML5 using Chromium browsers

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot#39063]
**Godot version:**

3.2.1 and 3.2.2-beta3

**OS/device including version:**

Windows 10. Problem occurs in Chrome, Brave & Edge (chromium browsers) but not Firefox. Happens on my laptop and desktop computers.

**Issue description:**

In HTML5 projects, the "-" and "=" keyboard keys become "unknown" in the Godot event. However, JavaScript running in parallel in the developer console recognizes these keys correctly as Minus and Equal.

This problem does not occur for any other key on my keyboard. Function keys OK. Menu keys OK. Chromium shortcut keys OK.

**Steps to reproduce:**

Add this code to a new or existing project:
```
func _unhandled_key_input(event):
	if event.pressed:
		prints(event.scancode, OS.get_scancode_string(event.scancode))
```
Run project, then press keys: 9, 0, -, =, Backspace...

In editor run, Windows export, or HTTP server running on Firefox:
```
57 9
48 0
45 Minus
61 Equal
16777220 BackSpace
```
HTTP server running on Chrome, Brave or Edge:
```
57 9
48 0
33554431 Unknown
33554431 Unknown
16777220 BackSpace
```
However, using code `document.addEventListener('keydown', (event) => {alert(event.code)})` in the developer console (in the same web page running above), I see:
```
Digit9
Digit0
Minus
Equal
Backspace
```

**Minimal reproduction project:**

Make a new project with the small code block above.

**Comment by Faless** [comment]
Probably related to the fact that we use [keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#Constants_for_keyCode_value), which is now deprecated in favour of [`code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values).
