### ISSUE TITLE
Custom node plugin bug.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3906]
**Operating system or device:**
Xubuntu 14.04 64-bit.
Godot compiled just two hours ago.

**Issue description** (what happened, and what was expected):
Custom node plugin quits with errors.

**Steps to reproduce:**

1. Install plugins.
2. Activate custom node plugin in the Project Settings.
3. Create a heart node.
4. Deactivate the custom node plugin in the Project Settings.
5. Click the heart node.
6. Godot quits.

The last messages in the console:
```
settings changed

ERROR: select: Index p_idx out of size (items.size()).
   At: scene/gui/item_list.cpp:177.
ERROR: get_item_metadata: Index p_idx out of size (items.size()).
   At: scene/gui/item_list.cpp:171.
ERROR: select: Index p_idx out of size (items.size()).
   At: scene/gui/item_list.cpp:177.
ERROR: get_item_metadata: Index p_idx out of size (items.size()).
   At: scene/gui/item_list.cpp:171.
ERROR: set_persisting: Condition ' !props.has(p_name) ' is true.
   At: core/globals.cpp:98.

```

**Comment by reduz** [comment]
this was fixed a while ago
