### ISSUE TITLE
Frametime Weirdness in the 4.0 Vulkan Release

### ISSUE THREAD

**Issue by RaTcHeT302** [godotengine/godot#39061]
for some reason when i open this older version of godot (3.1.2), or a specific game (evil genius made it bug out), the frametime skyrockets and the framerate is reported to be in the thousands range
![](https://i.imgur.com/xGnFXoi.png)
![](https://i.imgur.com/CmqtgQj.png)

if i try clicking on the window itself, for some weird reason, it either selects the 3.1.2 window, instead of the 4.0 window, or, it just selects a random window (such as my browser)

i'm reporting this just in case anybody else was as confused as i was, when i saw godot running at 1500+ fps

if i close that other godot window, the frametime is different, and i still cannot click on the window itself unless i restart godot
![](https://i.imgur.com/7ZlizKQ.png)

sometimes it works fine, and i can click on anything, and the framerate is still in the thouands range, and the frametime is really low (???????)
![](https://i.imgur.com/akMiu14.png)

**Comment by nathanfranke** [comment]
Please fill out the issue format. What exactly is going on? Are you running two instances of the editor at once, at different versions? I am assuming from the screenshot that you are on Windows 10.

I would recommend making a short video of the behaviour so that we can clearly understand what is happening.

**Comment by RaTcHeT302** [comment]
i don't know what's going on, i don't know what to type in the issue form, or how to explain this
for some reason if i open another game or another godot instance, things get really screwed up

**Comment by RaTcHeT302** [comment]
i think the framerate counter, is adding \ doing an addition (+) instead of subtracting (-)

so like if my framerate went down my 300, instead of 900 - 300, godot is probably doing 900 + 300

**Comment by Anutrix** [comment]
Are you opening the same project in different editors(different versions) at the same time?
4.0 and 3.2.x/3.1.x have breaking changes so don't run them on same project, much less at the same time.

**Comment by Calinou** [comment]
Closing per @Anutrix's comment. When testing the `master` branch, please create new projects for the time being.
