### ISSUE TITLE
Mutex and Semaphore not working inside EditorPlugin

### ISSUE THREAD

**Issue by ballerburg9005** [godotengine/godot#39071]
**Godot version:**

3.2.1.stable.official
**OS/device including version:**
Linux 5.6.12-arch1-1 #1 SMP PREEMPT Sun, 10 May 2020 10:43:42 +0000 x86_64 GNU/Linux

**Issue description:**
I encountered this problem when handling user input from my plugin. Godot spawns a new thread for every new input event and therefore a mutex lock is required to ensure the transactionality of data manipulation performed from those threads. But when I locked my function, I noticed that it wouldn't work at all. Even if mutex.lock() is called twice in a row it does absolutely nothing.

It is in fact totally broken.

**Steps to reproduce:**
In the attached zip you will find a demonstration. Click the MutexBug register card next to the node inspector panel and hit any key inside one of the 10 or so textboxes. This will trigger the mutex lock and the textboxes are deleted instantly and recreated very slowly as if under high CPU load. During this time, again press any key inside one of the text boxes. 

Now of course the mutex is still locked and nothing should happen until all the boxes are recreated and the mutex is unlocked by the still active function that handles user input. 

But this does not happen. What happens is that the mutex remains always unlocked and the function will manipulate data that is still being manipulated on, thus leading to tons of errors.

I also fudged a semaphore in there, although of course it shouldn't be used that way, but still same issue.

**Minimal reproduction project:**
[MutexBug.zip](https://github.com/godotengine/godot/files/4684482/MutexBug.zip)

**Comment by Zylann** [comment]
> Godot spawns a new thread for every new input event

I really doubt it. Events happen on the main thread. Where did you see this?

I'm confused about the nature of the repro and what's going on in the code, however I read this:
```gdscript
func handle_ui_input(ev, obj):
	if ev is InputEventKey and ev.pressed:
		mutex.lock()
		mutex.lock()
		print("mutex cannot be locked twice, first bug already here")
```
And this printed:
```
mutex cannot be locked twice, first bug already here
```
So there is really something strange going on here. I don't see a place where this mutex would be unlocked twice to allow this line to be reached.

**Comment by Zylann** [comment]
So maybe I'm misunderstandling `Mutex` as well, but shouldn't this never print `C`?? It does, even in simple game with only this script:
```
extends Node

var mutex = Mutex.new()

func _ready():
	print("A")
	mutex.lock()
	print("B")
	mutex.lock()
	print("C")
```

**Comment by ballerburg9005** [comment]
Ok, I am sorry this is more or less false alarm.

I inferred a couple of false assumptions from unusual behaviors which were only furthered by copy&pasting and not knowing what yield() does. Now I replaced it with OS.delay_msec and I see that no new threads are spawned from the gui_input signal.

It is still true that:

mutex.lock()
mutex.lock()

doesn't deadlock inside the same thread when anybody expects it would. But it does lock when I create a new thread in GDscript.

The plugin I write is quite beefy now and I am guessing the behavior I observed is rather caused by free operations being somehow performed too late. I added remove_child now and couldn't reproduce my initial error.

**Comment by ballerburg9005** [comment]
> So maybe I'm misunderstandling `Mutex` as well, but shouldn't this never print `C`?? It does, even in simple game with only this script:
> 
> ```
> extends Node
> 
> var mutex = Mutex.new()
> 
> func _ready():
> 	print("A")
> 	mutex.lock()
> 	print("B")
> 	mutex.lock()
> 	print("C")
> ```

To be exact about this, the C documentation for example says that the behavior of mutex.lock() called inside the same thread twice in a row is "undefined" and will likely lead to a deadlock. I have never used a language where lock() didn't lock and I it just seems kind of broken to me if it doesn't.
