### ISSUE TITLE
_gui_input() not detecting ScreenTouch release events beyond the first touch

### ISSUE THREAD

**Issue by rseonp** [godotengine/godot#39107]
I'm running 3.2.1.stable.official on my One Plus HD1900 on Android 10

With a single Control node and a _gui_input(), it seems like any ScreenTouch events beyond index = 0 do not register releases. ScreenTouch presses and ScreenDrags are registering fine though.

_Originally posted by @rseonp in https://github.com/godotengine/godot/issues/27149#issuecomment-634596966_

**Comment by madmiraal** [comment]
Please don't delete the issue template. All fields need to be completed, including providing a minimal reproduction project, to enable proper issue investigation.

**Comment by akien-mga** [comment]
Indeed, as it stands we can't do anything about this issue.
We can reopen once the post has been edited with more details, or you can open a new issue and follow the issue template.
