### ISSUE TITLE
Mono: No way to disable mono_crash json files

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#39109]
**Godot version:**
3.2.2 beta 3

**OS/device including version:**
MXLinux 19 64 bits

**Issue description:**
When the game crashes a mono_crash json file is created in the project folder, if you forget they might build up and fill your project folder with noise. They should be in a subfolder and if possible, there should be a way to disable them.

**Steps to reproduce:**
Cause a game crash.

**Comment by eadmaster** [comment]
[setting envvar `MONO_CRASH_NOFILE` shoud fix this](https://github.com/mono/mono/pull/14407)

**Comment by YuriSizov** [comment]
Closing per the above comment.
