### ISSUE TITLE
Mobile Navigation2D Broke

### ISSUE THREAD

**Issue by ikicapitan** [godotengine/godot#39108]
**Godot version:**
3.1.2

**OS/device including version:**
Multiple Android Devices (More than 50)

**Issue description:**
I exported a final game made with pathfinding using navigation2D nodes.

In PC and HTML5 export it works properly, however, on mobile devices (Android) the path sometimes breaks and goes through walls, especially at the beginning of the game.

There is no error message, or absolutely nothing to indicate what the problem is, it just happens, and it only happens on Android.

Try to optimize the pathfinding system, but the problem persists, thus being an internal Godot error.

When starting the game the Navigation2D sometimes breaks, but it is not always the case, there are times that it does not (although in 80% of the cases it does).

Here is an example of someone reproducing the error in a review:
[https://youtu.be/7cyEhiFpHFU?t=152](url)

**Steps to reproduce:**
(Android)
- Start the APK.

- New game.

- Touch the mission screen until the game starts.

- Press Ok at the first instruction.

- Once the player is focused, press another 2 times Ok.

- Touch the "Selection" button (First button Down) and then touch the character.

- Touch the "Move" button (Second button below) and choose a point to move.

**Minimal reproduction project:**
https://github.com/ikicapitan/Heroes-Epicos

**Comment by Calinou** [comment]
@ikicapitan Can you (or anyone else) still reproduce this bug in [Godot 3.3.2](https://godotengine.org/article/maintenance-release-godot-3-3-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by ikicapitan** [comment]
You took 1 year and 2 months to answer me. In 1 year and 2 months I will answer you. Greetings.

**Comment by akien-mga** [comment]
Ok. Until then, this is not useful.
