### ISSUE TITLE
Add a signal for RigidBodies to determine when sleeping state has changed

### ISSUE THREAD

**Issue by kirilledelman** [godotengine/godot#3911]
It would be great if RigidBodies ( 2D and 3D ) emitted a signal that would notify when it has gone to sleep, or has been awakened.

Parts of my scene get unloaded / freed when all bodies within have settled down / gone to sleep. I can't easily determine this without having to run a timer.

**Comment by bojidar-bg** [comment]
:+1:, also make it for 2D and 3D.

**Comment by SoulKa** [comment]
please add (Object body) to the emitted signal, so I can check which bodys sleeping state has changed

**Comment by bojidar-bg** [comment]
@SoulKa Consider using binds to get the same effect:
```gdscript
$rigid_body_2d.connect(self, "sleeping_state_changed", "it_changed", [$rigid_body_2d])
# ...
func it_changed(body):
  print(body) # [RigidBody2D:XXX]
```
