### ISSUE TITLE
Where is Vector3.angle_to ?

### ISSUE THREAD

**Issue by Allexit** [godotengine/godot#3912]
Vector2.angle_to( Vector2 ) is a possible function, a useful onetoo.
So where is Vector3.angle_to( Vector3 ) ?
It isn't very complicated to implement, I don't know how the Vector2 one is made but the one I custom-make constantly works like this:

`cos(a.dot(b) / (a.length() * b.length()))`

EDIT: A more efficent way to do this;
`acos( a.dot(b) / sqrt(a.length_squared() * b.length_squared()) )`
(Thanks @bojidar-bg )

Also cos should be acos instead, sorry typo

**Comment by bojidar-bg** [comment]
To reword the issue a bit:
`Vector2.angle_to(Vector2)` exists for 2D, but there is no similar function for 3D (e.g. `Vector3.angle_to(Vector3)`).

---

I guess, @Allexit means the angle between the two vectors, when considering them as rays passing from `(0,0,0)` to `(x,y,z)`.

@Allexit ~ BTW, there is `vec.length_squared()`, which is alot faster than calling `vec.length()`

**Comment by Allexit** [comment]
@bojidar-bg yes I'm aware, though it should still be square rooted if it works likr it should, which would make the equation look like this:

‘acos( a.dot(b) / sqrt( a.length_squared() * b.length_squared() )
