### ISSUE TITLE
Threads on iOS crash whenever you leave the game.

### ISSUE THREAD

**Issue by ThomasUijlen** [godotengine/godot#39131]
**Godot version:**
3.2 from Steam

**OS/device including version:**
iPhone 11 and iPhone 7, iOS 13.5

**Issue description:**
Whenever you pause a game with a thread on an iPhone the thread ALWAYS crashes.
This means exiting the app or looking at your messages. My procedural world generation is running in this thread and it just stops everything.

**Steps to reproduce:**
Just create a constant while loop in a thread that keeps printing something.
As soon as you leave the game the printing stops, wich is expected because iOS automatically pauses your game then. But when you come back the printing doesn't start again indacting that the thread has crashed.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by naithar** [comment]
@ThomasUijlen can you still reproduce this issue on Godot `3.2.2` or `3.2.3 RC`? 
I wasn't able to reproduce the issue with this code:
```
var thread = null

func _thread_function(userdata):
	while true:
		print(1)
		
func _ready():
	
	thread = Thread.new()
	thread.start(self, "_thread_function"))
```

**Comment by ThomasUijlen** [comment]
@naithar I managed to fix it!

My while looked like this:
`while generateArray.size() > 0:`

For some reason this returned false when you exit the app and that stopped the thread. Closing this issue!
