### ISSUE TITLE
Exported values are not saved from the editor if using setget functions

### ISSUE THREAD

**Issue by Reousa** [godotengine/godot#39149]
#10859 is a potential duplicate, it states the issue is fixed but it still happens.

**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
When a variable is marked as `export`ed, and it has `setget` function(s), it's value will not be updated when edited through the editor.

Worth noting it'll still be updated if edited anywhere else.

**Steps to reproduce:**
```
extends Node
export(float) var foo: float = 5 setget set_foo
export(float) var bar: float = 10 setget set_bar

func set_foo(val):
    foo = val

func set_bar(val):
   bar = val
```
Add a script containing the code to any node, change the values `foo` and `bar` through the editor & run the game.
The values will have been unchanged.

**Comment by nathanfranke** [comment]
Add `tool` to the top of the script?

**Comment by ThakeeNathees** [comment]
I can't reproduce in v3.2.1 stable even without tool, its working could someone conform ?

**Comment by ThakeeNathees** [comment]
![export-setget](https://user-images.githubusercontent.com/41085900/83325479-1a616b00-a28a-11ea-8179-4bed328c5807.gif)

**Comment by Reousa** [comment]
@ThakeeNathees do the values save when the game is off, and then are the same after you run it? That's my exact use case.

Eitherway, I'll try to gif my issue as well later tonight 👌

**Comment by ThakeeNathees** [comment]
@Reousa "do the values save when the game is off" you mean when the engine is closed, it still working, Is it only occur on a specific case?

**Comment by ThakeeNathees** [comment]
Eureka !! I've read your game this is what's going on

first the export values will be set by the value in the editor and then when it's ready the `_ready()` called, and thats when your onready var( `lod0` ) initialize.
`lod0` is was when it's trying to set the value not a bug though.

try this
```gdscript
func _set_lod0_dist(val: float) -> void:
	if lod0 == null:
		lod0 = $LOD0Area
	if lod0 != null:
		lod0.get_node("CollisionShape").scale = Vector3.ONE * val
		lod0_max_distance = val
```

**Comment by Reousa** [comment]
> Eureka !! I've read your game this is what's going on
> 
> first the export values will be set by the value in the editor and then when it's ready the `_ready()` called, and thats when your onready var( `lod0` ) initialize.
> `lod0` was null when it's trying to set the value not a bug though.
> 
> try this
> 
> ```gdscript
> func _set_lod0_dist(val: float) -> void:
> 	if lod0 == null:
> 		lod0 = $LOD0Area
> 	if lod0 != null:
> 		lod0.get_node("CollisionShape").scale = Vector3.ONE * val
> 		lod0_max_distance = val
> ```

That's quite a sneaky one! Thanks!! 👌
