### ISSUE TITLE
Do we really need to adjust the velocity dampening when using add_force in a loop in physics_process

### ISSUE THREAD

**Issue by 19PHOBOSS98** [godotengine/godot#39146]
**Godot version:**

3.2.2 beta 3

**OS/device including version:**
MAC/Macbook Pro

**Issue description:**

I tried to follow this Unity tutorial about hover car thrusters for my spider mech build(long story):
https://www.youtube.com/watch?v=r9OEZmbD9q0
my script looped thru each raycast(hover thrusters) in a `for loop` in the `physics_process` function, adding the appropriate force each call. It was a rectangle rigidbody with 4 raycast nodes pointing down from each corner.
But the problem was, when I ran the game and left it for a bit the thing gradually starts wobbling trying to keep itself stable...desperately(it failed flipping over). 

Now I know raising the angular and linear dampening  helps calm it down but I need the angular dampening to be lenient to do other stuff too plus doesn't it raise a red flag that you don't need to set velocity dampening in unity to do the same thing?

**Steps to reproduce:**
1- make a rectangular rigidbody
2- add raycast nodes bellow it on each corner
3- loop thru raycasts and check its distance to collision point and add the calculated force
4-NOT set the angular and linear dampening
5-leave it alone for a minute or two
6-watch as it gradually bounces off the ground a lot and jiggles out of control
7-cry

**Minimal reproduction project:**

[hverfaiI.zip](https://github.com/godotengine/godot/files/4701900/hverfaiI.zip)

**Comment by Cykyrios** [comment]
I had a quick look at the video, and it looks to me like the tutorial *does* actually damp the hover car, you can see that in the car controller script (I assume Unity's drag is equivalent to Godot's damp).

For your specific issue, just think of your hover thrusters as real car suspensions: they consist in a spring and a damper, not just a spring. You would most likely get better results changing the thruster's code so it includes both a stiffness factor and a damping factor.

And to answer your question in the title, yes you do need to adjust velocity damping in one way or another, for instance by changing the rigid body's damping value temporarily or applying an equivalent damping force to each thruster.

**Comment by madmiraal** [comment]
@19PHOBOSS98 Please ask technical support questions on one of the [community channels](https://godotengine.org/community). This issue tracker is solely for bug reports.

**Comment by 19PHOBOSS98** [comment]
> I had a quick look at the video, and it looks to me like the tutorial _does_ actually damp the hover car, you can see that in the car controller script (I assume Unity's drag is equivalent to Godot's damp).
> 
> For your specific issue, just think of your hover thrusters as real car suspensions: they consist in a spring and a damper, not just a spring. You would most likely get better results changing the thruster's code so it includes both a stiffness factor and a damping factor.
> 
> And to answer your question in the title, yes you do need to adjust velocity damping in one way or another, for instance by changing the rigid body's damping value temporarily or applying an equivalent damping force to each thruster.


> @19PHOBOSS98 Please ask technical support questions on one of the [community channels](https://godotengine.org/community). This issue tracker is solely for bug reports.

sorry my bad... if it's worth anything to anyone I got it to work with a bit of code for precision dampening and by having each thruster be a separate `RigidBody` attached to a main body using the `Generic6DOFJoint`. didn't even need a for loop, each of them just adds force to their own body and the main body just follows. Just be careful in scaling gravity and to not use too much thrust on each thruster tho.

precision velocity dampening on a RigidBody based on it's own transform:
`var local_linear_velocity = global_transform.basis.xform_inv(linear_velocity)`
`local_linear_velocity.y *= 0.5`
`linear_velocity = global_transform.basis.xform(local_linear_velocity)`
