### ISSUE TITLE
[3.2.2beta3-Gles2] WorldEnvironment is not working!

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#39151]
Godot 3.2.2 beta3 

GLES2 android

WorldEnvironment is not working in playmode and android but it is working perfectly in editor

Editor 
![image](https://user-images.githubusercontent.com/13883739/83294661-3ffb5f80-a20b-11ea-9d43-ce5d5255dc6f.png)

Playmode
![image](https://user-images.githubusercontent.com/13883739/83294699-5a353d80-a20b-11ea-8b23-42128fc5363a.png)

**Comment by Zireael07** [comment]
Android defaults to vertex shading. I know it can be switched off in settings, give it a try. Because the darker look on android definitely looks like vertex shading and/or driver issues.

What is your android device and its' GPU?

**Comment by gamergamesz** [comment]
Android 9 and Adreno 512 Snapdragon 660 
Mobile - Asus Max Pro M2

Turning off forced vertex sharing don't change anything.

**Comment by clayjohn** [comment]
What settings in the Environment are you using that aren't working?

**Comment by gamergamesz** [comment]
Glow, adjustments,all

**Comment by clayjohn** [comment]
@gamergamesz you need to be more specific than that if you expect someone to help you.

**Comment by gamergamesz** [comment]
I got the problem, it's happening due to framebuffer allocation which I have set to 2D and the WorldEnvironment node belongs to 3d family and it's consuming quite a good fps

**Comment by clayjohn** [comment]
The Environment page in the documentation should mention that the effects only apply when the Viewport usage is 3D.

**Comment by Aroweeri** [comment]
Like so?

**Comment by akien-mga** [comment]
Fixed by #39333.
