### ISSUE TITLE
Ability to inspect object members values during debugging 

### ISSUE THREAD

**Issue by kirilledelman** [godotengine/godot#3915]
While debugging / stepping through code, it's desirable to view the values of variables in current scope. 

Unfortunately, the palette on the bottom with current scope displays only simple types ( numbers, strings, etc ), and not objects / nodes. Instead, objects show up as "0" when hovering over variable names in text. It would be great if one could inspect the object that variable points to, or at the very least, show something like "[KinematicBody2D: 564]", so one could at least know its type. Ideally, it would be nice to be able to inspect objects in their entirety, with fields and all.

It would also be great, if there was a console while debugging, allowing execution of statements in current scope. So I could enter "print( varName )", like in Chrome javascript console, for example.

**Comment by bojidar-bg** [comment]
:+1:

@kirilledelman ~ BTW, What do you mean by "current scope"? The scope of the errored function/script? The one scope of the currently selected line? The scope of the currently selected stack trace entry? (And also, that REPL idea isn't so easy to do, so I would propose moving it into its own issue)

**Comment by kirilledelman** [comment]
You're right - the scope of currently selected stack trace entry. So if I go up the stack ( down the list ), I should be able to see the values of variables in local scopes of the caller functions. I think it already works like that, it just doesn't let you see anything but the basic types.

**Comment by akien-mga** [comment]
I believe this was implemented in 2.1-beta. Please comment and ask me to reopen if it's not the case.

**Comment by larvasapiens** [comment]
I'm using godot 2.1-stable and nodes still appear with a '0' in the Debugger.

**Comment by reduz** [comment]
Ah maybe we should link the debugger to the remote inspector

**Comment by larvasapiens** [comment]
Would be nice. I'm generating nodes from code, so trying to figure out which variable corresponds to which node could get messy.

**Comment by jahd2602** [comment]
Is there any issue about the impossibility of inspecting the variables inside objects? 
![captura de tela 2018-04-12 as 13 36 54](https://user-images.githubusercontent.com/2841740/38691218-99a6d0d4-3e56-11e8-8ce4-6d98839fb8a6.png)
Godot 3.0.2 stable

**Comment by adabru** [comment]
@jahd2602 I had the same problem and it turned out that the variable IS inspected, but it is not shown below the arrow (as I expected) but in the `Inspector` window. In my opinion that's better than expanding. Only the arrow-down-icon suggests something different.

**Comment by jahd2602** [comment]
@adabru I understand. Maybe that arrow can be another icon like a magnifying glass, and then do a quick white-outline-blinking animation on the inspector to catch the user's attention.
