### ISSUE TITLE
AnimationPlayer Call Method Track not being able to select C# custom function from editor

### ISSUE THREAD

**Issue by StradivariT** [godotengine/godot#39156]
**Godot version:**
Godot Engine v3.2.1.stable.mono.official

**OS/device including version:**
Ubuntu 18.04.4 LTS

**Issue description:**
I added a `Call Method Track` to an `AnimationPlayer`, which is a child node of another node that has a C# script attached to it.

Then I tried to add a key to said track to call a custom function on the node's script, I am able to see the function I want to call as well as the other public functions on the script, but when selecting it I get the following error message: `Method not found in object: ChangeToNextScene`.

A workaround for this, which is pretty much the same used on this issue https://github.com/godotengine/godot/issues/19869, was to just assign any arbitrary non-custom function to the key, and on `AnimationTrackKeyEdit` on the inspector change the function name to what it actually should be, which in this case was `ChangeToNextScene` and it actually works.

At the end of the day, doing this workaround works and is not a lot of a hassle, but we probably shouldn't be relying on it.

**Comment by harrisyu** [comment]
Yes, I can confirm that, and thanks for the workaround method.

**Comment by pjdevs** [comment]
I had this problem too, what I did is to recompile the project (by starting the game) and it found my method right after.

**Comment by akien-mga** [comment]
Fixed by #52607.
