### ISSUE TITLE
cannot overwrite the resource, always get the message that is still loaded

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#39179]
**Godot version:**
Godot3.2.2.beta2

**OS/device including version:**
Windows7 x64

**Issue description:**
Cannot save Resource. Always get the error message
 _Another resource is loaded from path 'res://test_style.tres' (possible cyclic resource inclusion)._

**Steps to reproduce:**
1. add lable
2. change style
3. save style
4. clear style
5. create other style (can also be done on another node)
6. try to save on same name
Error message appears.

Only when I close the editor and start it again, then I can save the resource under the same name.

**Minimal reproduction project:**
I don't think it's necessary.

**Comment by vaartis** [comment]
Can confirm this also happens whenever I reset the resource in git or pull something new. For now it seems that it's best to close the editor before pulling and open it afterwards.

**Comment by akien-mga** [comment]
Should be fixed in the latest 4.0 betas.
