### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by chuckeles** [godotengine/godot#3917]
I think it would be a good idea to add comments to the code, mainly for the header files, comments for function definitions. This would be a great addition for example for guys that use an IDE such as Visual Studio, because when you hover over a function call, it shows these comments.

Also see #3916.

Again, I would love to make this happen, just need to see if this is desired. Existing documentation could be put into the code. Personally I think that this would be better than having a separate file for function descriptions.

**Comment by reduz** [comment]
I prefer to not have much documentation there, I would rather open a class,
see the functions and try to find what i'm looking for.
Worst case if you don't understand what anything is for, you can find the
reference online

**Comment by bojidar-bg** [comment]
BTW, I think that it would be better if instead (or, best, alongside) comments we have longer and more descriptive variable names.

**Comment by chuckeles** [comment]
Fair enough, closing the issue.

**Comment by bojidar-bg** [comment]
@chuckeles ~ no, no, that's not what I meant. I think comments are also needed... mainly to lure more developers into the depths of the source-sea :smiley_cat:.

**Comment by chuckeles** [comment]
@bojidar-bg like me :stuck_out_tongue:

**Comment by chuckeles** [comment]
Although I must admit, now that I have written a couple of pull requests, I feel pretty confident in the code. It is a bit messy, but it mostly makes sense and is pretty logical.

**Comment by bojidar-bg** [comment]
@chuckeles ~ like me :stuck_out_tongue:
