### ISSUE TITLE
Can't start Godot (GL 1.4;GLES 2.0)

### ISSUE THREAD

**Issue by artdeell** [godotengine/godot#39185]
**Godot version:**

v3.2.1-stable_x11.64

**OS/device including version:**

OS: Debian Buster 10.?
Device: Sony Vaio VGN-TZ3RXN
GPU model: Intel 945GM
GPU driver: Mesa DRI Intel(R) 945GM
OpenGL: 1.4 Mesa 18.3.6
OpenGL ES: 2.0 Mesa 18.3.6 (OpenGL ES GLSL ES 1.0.16)
Backend: ???

**Issue description:**

What happened:
As website says, Godot can use OpenGL ES v2 as a renderer. I tried to launch it. "Your video card driver does not support any of the supported OpenGL versions."
What was expected:
Normal startup with OpenGLES instead of OpenGL.

**Steps to reproduce:**
1. Start Godot with described hardware.

**Minimal reproduction project:**

No (error occurs right on startup)

**Comment by akien-mga** [comment]
Godot requires OpenGL 2.1 on desktop platforms. Your chipset is very outdated and badly supported by Mesa, and only provides OpenGL 1.4.
