### ISSUE TITLE
HTML5 export can almost bring computer to halt due to RAM filling (hardware/browser dependent)

### ISSUE THREAD

**Issue by 123maxmix123** [godotengine/godot#3918]
**Operating system or device:**

**Issue description** (what happened, and what was expected):

When i upload exported HTML5 files, and open them from browser, i see text: "DOWNLOADING", after some little time, my computer goes in loop and i cant do anything.

Idk if ist only my problem, or i am doing something wrong.

The program i trying to export is very simple: something like rotating button.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by Hinsbart** [comment]
In my experience this depends on the hardware and browser.
For me it happens on my laptop with firefox, however on my desktop both firefox and chrome work just fine..

Also I think there's already an issue talking about this, however I can't seem to find it right now.

**Comment by est31** [comment]
Improving performance for HTML5 exports is scheduled.

**Comment by akien-mga** [comment]
Indeed, this is an issue I've been having too in Firefox, especially visible when uBlock Origin is running. My RAM usages goes from ~1 GB to the full 4 GB I have available little by little, until I can't use the laptop anymore.

I was also sure there was already an issue about this, but I can't find it either :) Maybe we only discussed it on IRC/Facebook.
