### ISSUE TITLE
CanvasModulate does not update after changing scenes

### ISSUE THREAD

**Issue by mgilski** [godotengine/godot#39182]
**Godot version:**

3.2.1 stable

**OS/device including version:**

Ubuntu 16.04

**Issue description:**

CanvasModulate does not update after switching between two scenes with a CanvasModulate node.

Possibly related issue on the Q&A: https://godotengine.org/qa/53759/canvasmodulate-visible-loading-instanced-scene-level-loading

**Steps to reproduce:**
Create a master scene and two other scenes (`scene1` and `scene2`) with CanvasModulate nodes (plus something to make it visible, like a sprite). Set a different color on each of the nodes. Add `scene1` as a child of the master scene. From the master node, call `queue_free()` on the child (without calling `remove_child` first). From the same node, load, instance, and `add_child()` `scene2`. The modulating color of `scene1` will still be applied, even though the inspector shows otherwise.

This can be mitigated by calling `remove_child()` on `scene1` before freeing.

**Minimal reproduction project:**

[canvas_modulate_bug.zip](https://github.com/godotengine/godot/files/4707303/canvas_modulate_bug.zip)

**Comment by akien-mga** [comment]
Why close it? It doesn't appear fixed yet.

**Comment by SpyrosMourelatos** [comment]
Any news on that ?

**Comment by Calinou** [comment]
> Any news on that ?

Did you manage to reproduce this bug? If so, which Godot version did you test?

**Comment by kylemclean** [comment]
This issue is still occurring on 3.4.4-stable.

**Comment by juliohq** [comment]
Here's a workaround that worked for me:

```gdscript
func _ready():
	Modulate.hide()
	yield(get_tree(), "idle_frame")
	Modulate.show()
```

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 4.x builds?

**Comment by juliohq** [comment]
@akien-mga I'm using CanvasModulate animated by an AnimationPlayer in a Godot 4.0 project and it's working just fine.

**Comment by ClaudioPaterniti** [comment]
It is still reproducible on 4.1.1. 

**Minimal reproduction project:**
[canvas_modulate_bug.zip](https://github.com/godotengine/godot/files/13540258/canvas_modulate_bug.zip)
