### ISSUE TITLE
New Lightmapper denoising library doesn't support MSVC 14.1 (visual studio 2017)

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#39186]
Kinda related to #38759

**Godot version:**

Lastest master a8787d1ae56006c00b4eecc3506dbc5ec763a8a5

**OS/device including version:**

Windows 10 64bits

**Issue description:**

Compilation failed when using MSVC 14.1 (from Visual Studio 2017 [which is expected to be supported](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html#requirements))

**Steps to reproduce:**

```
$ scons
scons: Reading SConscript files ...
Automatically detected platform: windows
Configuring for Windows: target=debug, bits=default
Found MSVC version 14.1, arch amd64, bits=64
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> thirdparty\oidn\mkl-dnn\src\cpu\cpu_reorder.cpp
cpu_reorder.cpp
C:\Users\gbleu\source\repos\godot\thirdparty\oidn\mkl-dnn\src\cpu/rnn/rnn_reorders.hpp(89): error C3615: constexpr function 'mkldnn::impl::cpu::rnn_weights_reorder_t<mkldnn_f32,mkldnn_s8>::pd_t::pd_t' cannot result in a constant expression
C:\Users\gbleu\source\repos\godot\thirdparty\oidn\mkl-dnn\src\cpu/rnn/rnn_reorders.hpp(89): note: failure was caused by 'constexpr' constructor not initializing member 'mkldnn::impl::cpu::rnn_weights_reorder_t<mkldnn_f32,mkldnn_s8>::pd_t::itag_'
C:\Users\gbleu\source\repos\godot\thirdparty\oidn\mkl-dnn\src\cpu/rnn/rnn_reorders.hpp(89): note: This diagnostic occurred in the compiler generated function 'mkldnn::impl::cpu::rnn_weights_reorder_t<mkldnn_f32,mkldnn_s8>::pd_t::pd_t(mkldnn::impl::engine_t *,const mkldnn::impl::primitive_attr_t *,mkldnn::impl::engine_t *,const mkldnn::impl::memory_desc_t *,mkldnn::impl::engine_t *,const mkldnn::impl::memory_desc_t *)'
scons: *** [thirdparty\oidn\mkl-dnn\src\cpu\cpu_reorder.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

Disabling the denoise module (by manually patching `modules\denoise\config.py::can_build`) allows to finish the build without errors

**Comment by Calinou** [comment]
This should probably be reported to OpenImageDenoise upstream if not done already.

**Comment by akien-mga** [comment]
Can you try to build https://github.com/OpenImageDenoise/oidn with VS 2017 and see if that works?

If not, the bug should indeed be reported there as they document VS 2015 as minimum requirement.

We're using an older commit though so it might be that they fixed this issue since then. CC @JFonS

**Comment by akien-mga** [comment]
Actually since the error is in the intermediate library https://github.com/OpenImageDenoise/mkl-dnn, you can try to build that one directly.

**Comment by akien-mga** [comment]
This looks like it was fixed upstream by https://github.com/OpenImageDenoise/mkl-dnn/commit/1e42e6db81e1a5270ecc0191c5385ce7e7d978e9#diff-e5f00945430760a5c93f1ac56db7c82f
