### ISSUE TITLE
Tooltip in Project Manager gives ERROR: Condition "!windows.has(p_window)" is true.

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#39199]
**Godot version:**
master https://github.com/godotengine/godot/commit/a8787d1ae56006c00b4eecc3506dbc5ec763a8a5

**OS/device including version:**
Windows 10 1909

**Issue description:**
Any tooltip in Project Manager gives:
```
ERROR: Condition "!windows.has(p_window)" is true.
   at: window_resize (drivers\vulkan\vulkan_context.cpp:723)
```
every time that it is generated.

**Steps to reproduce:**
1 . Open Godot.
2A. Hover over "Show in File Manager" Button of any project.
OR
2B. Hover over the search bar.

**Minimal reproduction project:**
NA

**Comment by ThakeeNathees** [comment]
I can conform that on windows 10, display server issue : #37734(tracker) is this only in windows ??

**Comment by bruce965** [comment]
030a26206ff70b1050c885270afce89b0430af70 on Linux Mint 19.3 works fine.

**Comment by Anutrix** [comment]
Seems like a Windows-specific issue.

**Comment by ThakeeNathees** [comment]
Here is a gif 
![tooltipbug](https://user-images.githubusercontent.com/41085900/83942458-1e086b00-a811-11ea-8a5e-4474e983f018.gif)

**Comment by ThakeeNathees** [comment]
the error message (`!windows.has(p_window)`) has gone now but still the toolitp is blinking in windows (as mentioned above: https://github.com/godotengine/godot/issues/39199#issuecomment-640037209)

**Comment by pouleyKetchoupp** [comment]
@ThakeeNathees That looks like a separate issue.
On Windows: In the scene tree and script list, tooltips target the wrong item and they keep blinking. They work correctly in the inspector.
On Linux & MacOS: From what I've just tested on master, tooltips are not displayed at all in the scene tree or script list.
