### ISSUE TITLE
Godot 3.2.1 does not completely support OpenGL 2.1

### ISSUE THREAD

**Issue by NebulousWeb** [godotengine/godot#39193]
**Godot version:**

Godot 3.2.1

**OS/device including version:**

Backend is GLES2. The graphics card is an Intel Corporation Mobile GM965/GL960 Integrated Graphics Controller which supports OpenGL 2.1. I have a dual boot OS of Lubuntu 19.10 and 32 bit Windows 7.

**Issue description:**

Godot 3.2.1 loads and runs fine under Linux. When I hit the "run" key a popup Window says this:

"Your video card driver does not support any of the supported OpenGL versions.
Please update your drivers or if you have a very old or integrated GPU upgrade it."

I can emulate OpenGL by forcing software rendering using this command:

export LIBGL_ALWAYS_SOFTWARE=1

And if I run Godot after that it runs much more slowly, and there is a long wait time before the run window appears. It works but it is so slow this is not a viable workaround.

I switched to 32 bit Windows 7 on the same machine and Godot 3.2.1 does not even start, complaining about the unsupported graphic card. 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
As I replied in https://github.com/godotengine/godot/issues/24723#issuecomment-636481782, these integrated graphics are too old to run anything that makes full use of OpenGL 2.x. It supports OpenGL 2.1 in theory, but in practice, it doesn't :slightly_smiling_face:

**Comment by aaronfranke** [comment]
To clarify: This is a driver issue with Intel's Windows drivers. This hardware does support OpenGL 2.1 on Linux, and only Linux.
