### ISSUE TITLE
Line highlight overlaps code minimap when scrolling far right

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39198]
**Godot version:**
3.2.2 beta3

**Steps to reproduce:**
1. Open script with a very wide code, so there's some space to scroll horizontally
2.
![O2pm8JqSYD](https://user-images.githubusercontent.com/2223172/83357032-20c71400-a36a-11ea-90a6-56e4766b2fb8.gif)
(look at the minimap)

**Comment by MewPurPur** [comment]
This issue doesn't seem present in 4.0 (RC 2)
