### ISSUE TITLE
Godot editor UI bug right and bottom disappeared from many 3D objects

### ISSUE THREAD

**Issue by Magical10240** [godotengine/godot#39195]
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Debian 10.3

**Issue description:**
godot editor exit still launch editor UI inspector impossible recovery plus panel down version also disappeared from many objects 3D godot something there is no optimization for 3D

performance experiment helps because of LOD we need to officially support LOD 4.X

**Steps to reproduce:**
`total objects: 24k` above bad
![unknown](https://user-images.githubusercontent.com/17591539/83354930-aba51000-a364-11ea-815f-d195992724fc.png)

![2020-05-31_17-27](https://user-images.githubusercontent.com/17591539/83354836-0427dd80-a364-11ea-87cd-ad83d5108cec.png)

Error:
```ERROR: push_call: Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
   At: core/message_queue.cpp:55.
Failed method: Tree:_update_callback target ID: 6693
TOTAL BYTES: 1048560
NULL count: 0
CALL : 535
CALL _request_gizmo: 21564
CALL _update_callback: 2
```
can't click project settings brakes godot

**Minimal reproduction project:**
[LODtestPerformance.zip](https://github.com/godotengine/godot/files/4707802/LODtestPerformance.zip)

**Comment by Calinou** [comment]
@Altair1024 Can you (or anyone else) still reproduce this bug in [Godot 3.4](https://godotengine.org/article/godot-3-4-is-released) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
