### ISSUE TITLE
set_text() isn't suggested at Label

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#39206]
I don't know if it really is a bug.

**Godot version:**
3.2.1

**OS/device including version:**
Windows 10 Home 1909
GLES3

**Issue description:**
I don't know if set_text() is not suggested because there shouldn't be this function but it works, so it could either be suggested or this function could be deleted.

**Steps to reproduce:**
Create a scene with root node Label. Attach a script to it and in _ready(): type "set". Now you will see many suggestions except set_text(). Type set_text("this works"). Start the game.

**Minimal reproduction project:**

**Comment by Zylann** [comment]
`text` is a property since Godot 3.0. As a result, it was decided to no longer suggest `set_text` and `get_text`, to encourage the use of the property instead.

**Comment by MaaaxiKing** [comment]
Do you think it should be removed? I don't really care about that, I just noticed.

**Comment by Zylann** [comment]
@MaaaxiKing the property won't work anymore if it's removed though. The point is, it is now recommended to use the property instead.

**Comment by MaaaxiKing** [comment]
I meant whether the function should be removed xD

**Comment by MaaaxiKing** [comment]
Just by the way, does this make any sense to use a property instead of a function?

**Comment by Zylann** [comment]
@MaaaxiKing we *can't* remove them at the moment, because to bind a property, the setter and getter must be bound first. If they aren't, the property can't be defined. So "recommending" is all we could do in that regard, really (and it preserved compatibility with old codebases I guess).

> Just by the way, does this make any sense to use a property instead of a function?

It's cleaner, and serves well to serialization and inspector. It's still set/get under the hood, just exposed in a nicer way. That's what I know though.

**Comment by Calinou** [comment]
> So "recommending" is all we could do in that regard, really (and it preserved compatibility with old codebases I guess).

We could print a GDScript warning every time a setter/getter function is used when a property is available. Of course, this would be disableable in the Project Settings.

**Comment by MaaaxiKing** [comment]
> We could print a GDScript warning every time a setter/getter function is used when a property is available. Of course, this would be disableable in the Project Settings.

That's a very nice idea!

**Comment by dalexeev** [comment]
https://github.com/godotengine/godot-proposals/issues/844#issuecomment-631456711

<details>

![image](https://user-images.githubusercontent.com/47700418/83361211-bc1eb000-a38f-11ea-9b7f-c336770aaf51.png)

</details>

**Comment by Calinou** [comment]
Closing, as the original question has been solved. Please continue the discussion about properties in GDScript in https://github.com/godotengine/godot-proposals/issues/844#issuecomment-631456711.
