### ISSUE TITLE
Android export error when deleting the default icon.png

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#39218]
**Godot version:**

Godot_v3.2.2-beta3_mono_x11_64

**OS/device including version:**

5.6.15-arch1-1
Android Debug Bridge version 1.0.41
openjdk version "1.8.0_252"

**Issue description:**

When deleting the icon.png you get the following error when exporting to android:
`core/io/image_loader.cpp:56 - Error opening file ''.`

**Steps to reproduce:**
1. Delete the default icon.png from your project inside the godot editor
2. Build the game for Android

**Comment by eddex** [comment]
Any idea how to fix this? I tried to add the `icon.png` file again but the error is still present..

**Comment by akien-mga** [comment]
The error is still reproducible as of 4.0 RC 3.

It's however benign and shouldn't prevent the export, it just means that no icon will be used.

**Comment by EiTaNBaRiBoA** [comment]
It is still reproducible in 4.1.3. I did with Image.png and did some sub region in it and it happens
![image](https://github.com/godotengine/godot/assets/62957978/3ffd18db-a34d-486d-a9fd-f5f9e1593206)

**Comment by EiTaNBaRiBoA** [comment]
> what would the expected behavior be? If you aren't getting an icon for your export, wouldn't the error be desirable?
> 
> ```c++
> String project_icon_path = GLOBAL_GET("application/config/icon");
> ```
> 
> stores the path to the icon. If the file specified in the project settings doesn't exist, I'd say an error is warranted.

At least the error should more clarified, with what and how should it be fixed. I did check and i do have the icon. It seems the error comes from the image.png i have and not from icon. Either way it's not about whether the error is warranted or not , but allow the user understand where it came and how to fix the issue.

**Comment by UdaySathe786** [comment]
I will work on it.
