### ISSUE TITLE
editor/script_editor_debugger.cpp:261 - Condition "!breaked" is true.

### ISSUE THREAD

**Issue by Talunava** [godotengine/godot#39217]
**Godot version:**
3.2.1

**Issue description:**
mash instances spawn black instead of white. Colour change is not possible.

**Comment by Calinou** [comment]
@Talunava Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. Also, please give some steps to reproduce this bug.

**Comment by clayjohn** [comment]
No reply from OP. Without any information, we can't do anything. 

We can reopen if we get any further information. :)
