### ISSUE TITLE
Running project kills my RAM for a while

### ISSUE THREAD

**Issue by maksimp04** [godotengine/godot#39223]
**Godot version:**
v3.2.1.stable.official  // Latest Steam version

**OS/device including version:**
OS: Windows 10
CPU: AMD Ryzen 5 2400G
GPU: Nvidia GeForce GTX 1050 Ti
Using GLES3
Latest drivers installed. Checked twice

**Issue description:**
Launching project randomly can overload my RAM and crash some programs.
This can happen regardless of whether the 2D scene or 3D scene is started.
Console writes nothing about this.

Last few seconds of accident:
![image](https://user-images.githubusercontent.com/19390500/83417519-05c8d280-a444-11ea-84d6-28120fe1e37e.png)
*First window says: "Godot Engine stopped working"
*Second window says: "The instruction at address ... accessed memory at address ... . Memory cannot be read."

I can only tell you what happened with the help of a plan:
1. Project loads suspiciously long
2. Godot engine freezes
3. Monitor goes off
4. After a while monitor reboots
5. RAM error appears
6. Everything visually freezes (except cursor and browser) but works fine
7. Godot crashes
8. Computer reacts to everything very slowly
9. Even PC restart takes 15 minutes to fully load

**Comment by Anutrix** [comment]
How much RAM does your PC have?
 Are you running Chrome or something else that could use much RAM?

**Comment by maksimp04** [comment]
I have 8 GB of RAM and I'm always got an Opera running. But this thing appears randomly so I don't think this is Opera fault

**Comment by Calinou** [comment]
Have you been able to reproduce this in a minimal reproduction project? If so, please upload it.

You could also upload your full project, but it's less optimal.

**Comment by maksimp04** [comment]
Can't reproduce this in minimal reproduction project because i don't even know why and how this is happening.
I fell a little scared to upload my project but if this can help i won't mind

Project: https://dropmefiles.com/xLvqr

Steps for reproduct:
1. Change files, scenes or something just to make godot save things.
2. Launch any scene
3. Retry until things happened

**Comment by maksimp04** [comment]
20 days passed.
Updated every driver possible, speed up my computer, checked fps limit on my project to 60 fps and  no more RAM issues found yet. I will reopen this issue if problem appears again and no aforesaid things help me this time.
