### ISSUE TITLE
Timers run inside scene drag preview

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39221]
**Godot version:**

3.2.2 beta3

**Issue description:**

This is more funny bug than critical, but when you drag a scene over viewport, any Timer in that scene will run inside the preview. I discovered it when my timer connected to AnimationPlayer made the preview animated (lol).
![15jfhsY9sp](https://user-images.githubusercontent.com/2223172/83408886-a94dbf00-a413-11ea-8671-a6a94240424a.gif)
(the cursor seems to be off on the GIF for some reason, ignore it)

Luckily connecting the Timer to `queue_free()` doesn't crash the editor (just makes the preview disappear xd), so it's a rather minor bug.

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4711224/ReproductionProject.zip)

**Comment by lightspot21** [comment]
Can reproduce on Linux (Arch) 3.2.2 beta3. However, `master` doesn't exhibit this behavior (has the preview functionality been merged yet?)

**Comment by Calinou** [comment]
@lightspot21 `master` has had its windowing system rewritten from scratch, so some features may be missing.

**Comment by akien-mga** [comment]
As discussed in #39232, let's shelve it for now, and revisit if we find it to actually be a problem worth fixing.
