### ISSUE TITLE
Zero padding of a float is not working in a format string

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#39237]
**Godot version:** 3.2.1

**OS/device including version:** Linux 64b

**Issue description:**

`%07.2f` format string should insert zeroes as a padding, but instead inserts spaces.

**Steps to reproduce:**

```gdscript
print("<%07.2f>" % [0.123])
```

output:

```c
<   0.12>
```

comparison with C:

```c
$ cat 0.c && echo --- && gcc 0.c -o 0 && ./0
#include <stdio.h>

int main() {
	printf("<%07.2f>\n", 0.123);
}

---
<0000.12>
```

**Comment by Calinou** [comment]
You should be able to use `str(0.123).pad_zeros(7)` to achieve this. That said, we should probably change the format string behavior to match printf.

Does the C standard have a way to pad a number with spaces?

**Comment by mnn** [comment]
Unfortunately I can't use `str` + `pad_zeroes`, because that would significantly worsen usage of the function (it's a library function, user can pass a format string for specific numbers). For now I added a hack for default format string (just `.replace(" ", "0")`).

> Does the printf "standard" have a way to pad a number with spaces?

Yes, without the `0` in a format string: 
```c
#include <stdio.h>

int main() {
	printf("<%7.2f>\n", 0.123);
}

---
<   0.12>
```
I believe for integers Godot's `%` operator behaves same as `printf` (without `0` spaces, with `0` zeroes).

**Comment by mrushyendra** [comment]
I can work on this, if no one else is already

**Comment by Calinou** [comment]
@mrushyendra It seems nobody is currently working on this, so go ahead :slightly_smiling_face:
