### ISSUE TITLE
Godot Online Editor doesn't start

### ISSUE THREAD

**Issue by Schweini07** [godotengine/godot#39236]
**Godot version:**
The Godot online Editor (so 3.2)

**OS/device including version:**
OS: Manjaro Linux
GPU: AMD Radeon HD 8670D
GPU driver name: radeon
Browser: Firefox

**Issue description:**
When trying to start the online Godot Editor nothing happens:
![The error](https://i.imgur.com/vqR9ejN.png)
The debugger says something about `Atomics not defined`.

**Steps to reproduce:**
Try to start the editor on https://godotengine.org/online/godot.tools.html.
But this is probably GPU related(?).

**Minimal reproduction project:**
Not possible.

If more information is needed please tell me.

**Comment by nathanfranke** [comment]
What browser?

Godot Online Editor is extremely new and only works on Firefox Nightly or Chromium-based browsers. Also I wouldn't bother making bug reports since it is so new.

**Comment by groud** [comment]
Before opening an issue about a very early feature, please read the article about it completely...
It clearly state in the article that you need a very recent version of chromium or Firefox night builds to run the editor, which your error is about : https://godotengine.org/article/godot-editor-running-web-browser

**Comment by Schweini07** [comment]
The interesting is/was that I even installed chromium and it also didn't worked. I tried it again and now it works. Weird, but I can live with that.

**Comment by groud** [comment]
Hmm, indeed that more unexpected, it should likely work with a recent version of chromium.
In any case this a very early on feature which is still heavily in development, it's normal it's still has issues. Once the core development is done, we will accept bug reports on the topic.

**Comment by bruvzg** [comment]
It's working in the chromium-83.0.4103.61 (which should be the version current stable branch of Chrome use).

**Comment by Schweini07** [comment]
Is the same version I also used

**Comment by bruvzg** [comment]
It might be some CEF specific patch or GLES implementation issue, or it's just super slow, loading to the Project Manager takes almost 30 seconds for me. It prints [some errors](https://gist.github.com/bruvzg/20d33b6a62fabf2e7036c891d988d29c) to the console, but is working.

**Comment by Schweini07** [comment]
Well as @groud said, we should wait for the online editor to get stable, for error reports.
