### ISSUE TITLE
Multiple editor theme propagation errors.

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#39235]
**Godot version:**

master, a8787d1

**OS/device including version:**

Any

**Issue description:**

After OS/DisplayServer split, multiple editor UI elements use default bitmap font (no scaling and latin characters only), and have missing interface icons.

Elements with the wrong font:

- "Load errors" dialog.
- "Description" field in the "Create new node", "Create new resource" and "Search visual script", "Visual script > Change base type", "Visual shader > Add node".
- "Visual script" and "Visual shader" note titles.
- Table headers in the "Project settings" > "Input map", "Localization/Remaps", "Autoload" "Plugins" - and "GDNative"
- "Animation Tree" > "State machine" and "Blend tree" note names.
- "Feature List" field in the "Export" > "Features"
- Table header in the "Orphan resource explorer"
- Table header in "Editor settings" > "Shortcuts"
- Table headers in bottom bar "Debugger" (on multiple tabs)
- All text in the theme preview (might be intentional or was broken before split, see #25585)

File dialog icons are missing in the following dialogs:
- All file dialogs opened from "Export"
- All file dialogs opened from "Inspector"

Related PRs: #39123 (Tooltip font), #38917 (Some documentation fonts).

**Comment by Anutrix** [comment]
> File dialog icons are missing in the following dialogs:
> 
>     All file dialogs opened from "Export"
>     All file dialogs opened from "Inspector"
It seems to issue with EditorFileDialog and not EditorDialog.
Also, I am not sure if the icons for EditorFileDialog should in "EditorIcons" or if it should be in its own "EditorFileDialog"(like FileDialog and other stuff work).

**Comment by Anutrix** [comment]
[get_icon()](
https://github.com/godotengine/godot/blob/030a26206ff70b1050c885270afce89b0430af70/scene/resources/theme.cpp#L349-L355.) fails(i.e, returns default_icon) for lot of icons of type "EditorIcons" including the ones used in EditorFileDialog.

**Comment by Anutrix** [comment]
Seems like the type EditorIcons is replaced by Icons at some point.

**Comment by txj-mssl** [comment]
I hope to fix this error as soon as possible

**Comment by txj-mssl** [comment]
Estimated repair time?

**Comment by akien-mga** [comment]
> Estimated repair time?

What's your budget? :)

I already asked you not to ask for fixes in short deadlines (unless you're willing to pay someone to do the work). This is the `master` branch, and breakage is normal. There are dozens of other more critical issues that also need to be fixed. That branch is not usable in production at all, so putting so much pressure on having proper internationalization of the in-editor class reference for something which is not usable in production seems a bit far-fetched.

If all you care about is having your own version of Godot full localized, I'd suggest that you cherry-pick #37164 for your own use in the `3.2` branch, which won't be affected by this bug in the first place.

**Comment by txj-mssl** [comment]
I just want to know how long it will take to fix it. It's not mandatory.

**Comment by akien-mga** [comment]
Well unless a contributor chooses to look into it and fix it, this will be on @reduz's shoulders as his changes created the problem. Here's currently busy with rendering work and will hopefully then move on to investigate regressions related to the DisplayServer and Window changes, so maybe within a few weeks to a month.

**Comment by Anutrix** [comment]
Icon issue seems to be because of a timing issue. The icons are not ready/populated when they are set during the EditorFileDialog's creation. This can be confirmed because https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/editor/editor_file_dialog.cpp#L595 has no issues. In fact, just doing `_notification(NOTIFICATION_ENTER_TREE);` inside this function works.
