### ISSUE TITLE
UI glitch on editor view pane

### ISSUE THREAD

**Issue by mownier** [godotengine/godot#3924]
**Operating system or device:**
OS: Ubuntu 15.10 64-bit

**Issue description** (what happened, and what was expected):
I compiled the engine from source at the master branch with commit HEAD 5a9b18b using `$ scons platform=x11`. I cloned and opened an open-source project [Tanks of Freedom](https://github.com/w84death/Tanks-of-Freedom). Then, opened the game scene (`game.xscn`) under the 2D view. When I tried to super zoom in on the editor and scrolled left and right, this what happened:

![godot engine issue 1](https://cloud.githubusercontent.com/assets/3685613/13546156/b99f88f6-e2df-11e5-9d54-aaa3a66dcb63.png)

**Steps to reproduce:**
```
Prerequisite
- Compiled the engine from source
- Downloaded the `Tanks of Freedom` project
```
1. Open `Tanks of Freedom` project
2. Open the file `game.xscn` under 2D view
3. Zoom in 10x on the editor
4. Scroll left and right

**Link to minimal example project** (optional but very welcome):
https://github.com/w84death/Tanks-of-Freedom

**Comment by akien-mga** [comment]
Looks like the same bug as #1840 (which is not tilemap-specific, I'll edit that).
