### ISSUE TITLE
Global Menus get duplicated when adding items out of order

### ISSUE THREAD

**Issue by greygraphics** [godotengine/godot#39241]
<img width="479" alt="Screenshot 2020-06-02 at 14 25 01" src="https://user-images.githubusercontent.com/26239210/83520210-9dc6ca80-a4dd-11ea-88ea-c21f3162b522.png">

**Godot version:**

v3.2.1

**OS/device including version:**

MacOS 10.15.5 Catalina

**Issue description:**

Adding multiple items to different menus out of order creates multiple menus with the same name.
The `OS.global_menu_add_item()` function should add items of the same menu to the same menu.

**Steps to reproduce:**
Add multiple items to global menus and change the menu in-between items:
`OS.global_menu_add_item("My First Menu", "My First Item", 0, "First Item")
	OS.global_menu_add_item("My Second Menu", "My Second Item", 1, "Second Item")
	OS.global_menu_add_item("My First Menu", "My Third Item", 2, "Third Item")`

**Minimal reproduction project:**

[Global Menu Bug.zip](https://github.com/godotengine/godot/files/4717117/Global.Menu.Bug.zip)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by akien-mga** [comment]
Fixed by #39243.
