### ISSUE TITLE
Godot Android Exports "Default Activity not found" using Android Studio 4.0

### ISSUE THREAD

**Issue by tx350z** [godotengine/godot#39242]
**Godot version:**

v3.2.stable.official

**OS/device including version:**

Windows

**Issue description:**

Not sure if this is a bug in Godot Android Export, Android Studio 4.0, or some kind of compatibility issue with AS 4.0

I updated Android Studio to v4.0. When I "Profile or debug APK" an APK produced by Godot Android export and try to run/install I get "Default Activity not found". Tried different settings for the default activity in Android Studio and nothing works.

Also verified the default activity is in the manifest.

Tried using an older APK that worked with ASv3.5 and received the same error with ASv4.0.

I'm going to downgrade to AS3.5 and verify everything still works with it.

**Steps to reproduce:**
Upgrade Android Studio to v4.0.
Select "Profile or debug APK" and load an APK produced by Godot Android
Wait, wait, wait while AS loads and indexes the APK
Attempt to run

**Minimal reproduction project:**

N/A

**Comment by Anutrix** [comment]
Seems like it's a known issue when changing Android Studio versions.
https://medium.com/@ranjithexpertisers/default-activity-not-found-in-android-studio-f260a00edd4a shows some ways to deal with it inside Android Studio. No idea how Godot can do this internally.

**Comment by tx350z** [comment]
I've looked at that. Since the manifest produced by Android export has the default activity specified, there should be no problem.

One thing that is odd about ASv4.0 is if I attempt to choose the default activity class in the run configuration it doesn't allow expanding the DEX file to list the app classes.

I'm going to try uninstalling/reinstalling ASv4.0. If that doesn't work, I'll downgrade to ASv3.5 until they get it fixed.

**Comment by tx350z** [comment]
Update: I downgraded to ASv3.6.3 (android-studio-ide-192.6392135-windows.zip) and everything works correctly. So the problem is either a bug in ASv4.0 (most likely) or compatibility between GD Android export template and ASv4.0.

Will leave this open unless someone wants to close it.

**Comment by m4gr3d** [comment]
@tx350z I'm not sure why this is a Godot issue since you're using another tool to manipulate the APK generated by Godot. 
Are you trying to debug an APK generated by Godot within Android studio?

**Comment by tx350z** [comment]
Yes, I am just using Android Studio to side load and debug the APK. My app uses a Play Games plugin so need to see debug output from both Godot and Java.

**Comment by m4gr3d** [comment]
Closing this issue as it seems resolved. Feel free to reopen otherwise.
