### ISSUE TITLE
Set Scale of Controlnodes in HBox/VBox/Grid-Container is always reset to 1,1

### ISSUE THREAD

**Issue by UltyX** [godotengine/godot#3925]
![ijrdc1r](https://cloud.githubusercontent.com/assets/4701338/13547229/62d3be4e-e2ca-11e5-8adf-723782b3b05a.png)

Also tested setting the scale of a container item from script, in the scenes root node ready function, to no effect. 

[testttttt_1.zip](https://github.com/godotengine/godot/files/159750/testttttt_1.zip)

**Comment by akien-mga** [comment]
Note: don't hesitate to drag and drop your image directly in the issue, then we don't have to go to an external website to see it :) I've fixed it for this issue.

**Comment by UltyX** [comment]
cool, did not know you could do that :D

**Comment by mohaalak** [comment]
I don't think it's a bog cause the hbox container resize every contained node to it's min size .just change the min size to see the effect.

**Comment by UltyX** [comment]
Changed the min size to 128 (2*64) and set the scale of the TextureFrame to 2, but it gets still reset back to a scale of 1 when put into the container.

**Comment by mohaalak** [comment]
@UltyX set the min size and check the expand check box in texture frame I think you are good to go

**Comment by UltyX** [comment]
ah yes, that solves it

**Comment by mohaalak** [comment]
can you close this issue :+1: :smile:
