### ISSUE TITLE
Xbox Gamepad Mapping Incorrect in Firefox HTML5 Export

### ISSUE THREAD

**Issue by cybereality** [godotengine/godot#39253]
**Godot version:**

Godot v3.2.1.stable.official (Steam)

**OS/device including version:**

Ubuntu 20.04 and Linux Mint 19.3
Microsoft Xbox One Controller (Bluetooth edition but using wired)
Firefox 76.0

**Issue description:**

The input mapping for the controller axis is all messed up. Left and Right on the Right stick go to Up and Down. Up and Down on the Right stick do nothing. Start and Select map to the Triggers, and more, it's all wrong.

**Steps to reproduce:**
Use the Joypads example project that comes with Godot. Export for HTML5 and try in Firefox, you will see what I am saying. Chromium has no problems and the controller works as normal.

**Minimal reproduction project:**

Joypads project that comes with Godot.

**Comment by Calinou** [comment]
Related to #32831.

**Comment by kalbfled** [comment]
The input is similarly wrong for me using a Logitech F310 gamepad and Firefox with this site: https://myroom.davejk.me.

**Comment by Calinou** [comment]
@kalbfled Does it work as expected in a Chromium-based browser?

**Comment by kalbfled** [comment]
Yes, it works with Chromium on Ubuntu 18.04 with Godot 3.2.3.  On Firefox and Chromium, keyboard input seems to be ignored until I mouse click on the game window.
