### ISSUE TITLE
Tree component causes updates when simply hovering between cells

### ISSUE THREAD

**Issue by giulianob** [godotengine/godot#39251]
**Godot version:**

3.2

**OS/device including version:**

All versions

**Issue description:**

Many of the components are extremely optimized to prevent re-drawing when it's not needed but the tree component is redrawing unnecessarily. I found this issue because I am using it to render tables and I'm getting as low as 15-20 FPS in some cases when just moving the mouse around the screen on a fairly powerful desktop. It seem to be because the component causes redraw whenever the mouse moves between tree items. 

I understand it may be a stretch calling this a bug but I'm trying to use the tree component to render fairly complex tables/trees of items and it seems to actually be causing fairly huge drops in FPS.

I believe the source of the issue to be in this line which is called during mouse move event
```
		if (cache.hover_type != old_hover || cache.hover_index != old_index) {
			update();
		}
```
I'm not sure if there is an easy way to optimize this to not cause a full render of the tree when simply moving between cells.

**Steps to reproduce:**
You can easily reproduce this by watching the update spinner in Godot spin if you just simply mouse the mouse around the File System view or the Scene nodes.

**Comment by Calinou** [comment]
What happens if you comment out the `update()` call there and recompile Godot?

**Comment by giulianob** [comment]
From just looking at the source, it appears if we don't call update() when going from hovering a title column to a regular tree item then the column title will stay in the hovered state so that may be the reason for calling update() there. May be able to just optimize it and only call update() in that situation. I'll try to get a build going and create a PR if I don't run into issues!

Side question: I haven't tried it yet as I use C# and I haven't tried to get a build working yet. I'm not exactly proficient in C++. Any recommendations in the easiest way to get a C# build going? Is installing all the deps locally the easiest way or should I try using the docker build? Thanks I also pinged Remi on discord and see if he can share any wisdom. I'd definitely like to contribute.

**Comment by Calinou** [comment]
Building a Mono-enabled binary is documented [here](https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html).
