### ISSUE TITLE
no shadowing variable warning from vars initialized in loop declaration

### ISSUE THREAD

**Issue by paulmyers-0** [godotengine/godot#39268]
Hi, something like this will produce a warning

```
var x
func foo():
    var x
    x = 3
```

but this will not
```
var blahblah = ["blah"]
var x
func bar():
    for x in blahblah:
        x = "Bleh"

```
I feel like it probably should make the same warning?

Godot version: 3.2.1

OS/device including version: Windows 10

**Comment by Calinou** [comment]
@paulmyers-0 When reporting bugs, please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) so we can know which Godot version is affected.
