### ISSUE TITLE
Button/Texturebutton pushed and focused textures conflict

### ISSUE THREAD

**Issue by w84death** [godotengine/godot#3926]
**Operating system or device:**
All

**Issue description** (what happened, and what was expected):

When pushing button the pushed texture should be visible.
Instead focused texture is drawn over - so pushed texture is not visible.

Problem is not showing where no focused texture is added. But to properly support gamepads/keyboard it is important to have focus indicator.

**Steps to reproduce:**

- clone this project https://github.com/w84death/buttonbug
- hover mouse over button
- press

**Link to minimal example project** (optional but very welcome):
https://github.com/w84death/buttonbug

**Comment by reduz** [comment]
this is by design, and it's done so you don't have to create every texture again for focused mode. 
focus is an overlay for the button, not a replacement.

**Comment by reduz** [comment]
maybe this should be documented better

**Comment by bojidar-bg** [comment]
@reduz indeed

@godotengine/documentation Anyone up for this? ^^
