### ISSUE TITLE
ViewportTexture with mipmaps enabled becomes translucent and disappears

### ISSUE THREAD

**Issue by amonroejj** [godotengine/godot#39273]
(I didn't see any other issues with keywords _ViewportTexture_ and _mipmaps_ that described this.)

Godot 3.2.1.stable.official
Windows 7, Geforce GTX 460M 391.35

**Issue description:**
Expected: Apply a ViewportTexture to a Sprite3D, enable mipmaps, and view it from any distance or angle. (Actual goal is a card game in the mold of _Chronicle: Runescape Legends_ where the card text needs to be readable at small sizes)

Observed: This Sprite3D when viewed from a glancing angle or if you move too far away from it (either in the editor or during gameplay)--where mipmaps would come into play--gets more and more translucent and eventually disappears altogether.

Disabling mipmaps fixes the disappearing, but effectively makes small text unreadable.

Screen capture: https://imgur.com/a/WMYNgfM

**Steps to reproduce:**
Spatial
....Viewport
........(anything)
....Sprite3D with ViewportTexture referencing above viewport, with mipmaps enabled.

**Minimal reproduction project:**
[ViewportTextureGlitch.zip](https://github.com/godotengine/godot/files/4726989/ViewportTextureGlitch.zip)

**EDIT 1:**
Doing it in code triggers the same translucency glitch:
```
$Sprite3D.texture = $Viewport.get_texture()
$Sprite3D.texture.flags = 7
```

**Comment by danilw** [comment]
>Actual goal is a card game in the mold of Chronicle: Runescape Legends where the card text needs to be readable at small sizes

to do that you need to make your own font as texture and print its text from a shader in your "text mesh" if you need dynamic text

example shader that prints text from texture https://www.shadertoy.com/view/tsdGzN

if you do not need dynamic text, then you need to prerender all "cards with text on it" or text as textures and use it on your mesh as textures

using viewport to do this job is very mush "overkill" and not end well at all

**Comment by amonroejj** [comment]
Needs to be dynamic, yes. A stock "Text3D" object would be a welcome addition.

The defect is still valid though because the reproduction project does not use text.

**Comment by Calinou** [comment]
PS: [To improve performance, consider using MeshInstance with a PlaneMesh or a QuadMesh instead of Sprite3D.](https://github.com/godotengine/godot/issues/20855)

**Comment by akien-mga** [comment]
Seems confirmed in 3.3-stable, see this thread: https://twitter.com/Firepal3D/status/1385188174973046787

**Comment by Calinou** [comment]
Mipmaps aren't generated for ViewportTexture, so I think this is expected. Generating mipmaps in real-time is very demanding and can likely only be done for 4.0 with a fast filtering implementation.
