### ISSUE TITLE
Latest release does not have correct export templates

### ISSUE THREAD

**Issue by McFarts** [godotengine/godot#3929]
I just downloaded Godot_v2.0_stable_20160223_win32.exe

And then I used this to export my game to windows (.exe) and got an error saying:

`godot pack created with newer version of engine`

So I redownloaded the new export template from the main website and installed it. 

Now it all works wonderfully!

But I think the latest export templates should be included in the latest Godot release? Just a suggestion, thx. Engine works great now though, very fast, love it

**Comment by akien-mga** [comment]
No the templates are always distributed separately. For Windows users we could have an installer that bundles both the engine + the templates, but generally speaking each time you update the engine you have to download the new templates too.

**Comment by McFarts** [comment]
Alrighty, no problems thank you!

**Comment by reduz** [comment]
We should see about having Godot optionally download the export templates
somehow.. and warning you about incorrect version :|
