### ISSUE TITLE
GDScript debugger steps through operations in the wrong order

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#39296]
**Godot version:**

3.2.1 stable official

**Issue description:**

The debug steps through the operations in a completely nonsensical order, I expected it to step through as written. 

**Steps to reproduce:**
put a breakpoint on line 9 of test.gd and step into until you lose your mind

**Minimal reproduction project:**

[DebugWrongOrder.zip](https://github.com/godotengine/godot/files/4732212/DebugWrongOrder.zip)

**Comment by Ev1lbl0w** [comment]
Here's a GIF of what's happening, I agree that it's kinda odd :stuck_out_tongue: 
![godotgif](https://user-images.githubusercontent.com/6501975/83803580-c220d380-a6a4-11ea-9e69-3ebacbc64db5.gif)

This is probably just a "visual" bug, right?
