### ISSUE TITLE
Load errors dialog uses wrong font

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39303]
**Godot version:**

c0ff2a3

**Issue description:**

The "Load Errors" dialog doesn't support unicode letters (probably related to #37332)

![image](https://user-images.githubusercontent.com/2223172/83811455-24380380-a6ba-11ea-8a4d-94e8e1a8a966.png)
(the message should say _Nie można przenieść/zmienić nazwy źródłowego zasobu._)

**Comment by bruvzg** [comment]
#39235 duplicate

**Comment by KoBeWi** [comment]
Ok
