### ISSUE TITLE
Duplicating a file hangs Filesystem Dock

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39308]
**Godot version:**

c0ff2a3

**Steps to reproduce:**
1. Right-click a file in file panel
2. Duplicate it
3. This, forever
![image](https://user-images.githubusercontent.com/2223172/83821975-22793a80-a6d0-11ea-9d8b-fc4067907c27.png)

Stays like this until you re-focus editor.

**Comment by akien-mga** [comment]
Seems fixed in current `master`.
