### ISSUE TITLE
Converting a function into a string calls the function

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#39317]
**Godot version:**
3.2.1.stable

**OS/device including version:**
Windows 10 Home 1909
Intel(R) UHD Graphics 620
GLES3
**Issue description:**
A function was called. I expected that a function was converted to a string.
**Steps to reproduce:**
Create a scene with root node Node which has a script attached. In the script write:
```
extends Node

var my_variable

func _ready():
	my_variable = str(my_function())
	print(my_variable) #prints Null
func my_function():
	print("This function was called but it should not.")
```
Start the scene.
**Minimal reproduction project:**

[str(function) bug.zip](https://github.com/godotengine/godot/files/4735570/str.function.bug.zip)

**Comment by pycbouh** [comment]
No, this calls it:
```
my_function()
```

**Comment by MaaaxiKing** [comment]
Yes, but this shouldn't be called since it is an argument of another function (str() which should convert anything to a string)

**Comment by pycbouh** [comment]
That's not how programming languages work. A function is referred to by its name -> `my_function`. Adding parenthesis at the end makes it a function call. Function calls can totally be put inside another function call to make the result of the first function be an argument for the second function.

Besides, are you sure that GDScript can "convert function to string", as you expect it to behave? If you want to get a function's signature and body as text, I'm not sure there is such a capability (yet).

**Comment by akien-mga** [comment]
`my_function()` will always be called. The result of the `my_function()` call will then be converted to a string via `str()`. It works as designed.

**Comment by MaaaxiKing** [comment]
I thought it would print: my_function()

**Comment by akien-mga** [comment]
Functions are not first-class (yet) in GDScript, they will be in Godot 4.0.
In other languages where you might have seen this, it would be done with `str(my_function)` (without the parentheses which call the function).

**Comment by MaaaxiKing** [comment]
What do you mean with first-class?

**Comment by pycbouh** [comment]
@MaaaxiKing Here it means that you cannot refer to a function as a type of an object in your code, using exclusively its name. So you can't use `my_function` as an argument in another function to the desired effect.

If you have further questions about coding in GDScript or Godot in general, please ask people around our [community channels](https://godotengine.org/community). This issue tracker is for reporting bugs only.
