### ISSUE TITLE
glTF2 import can't import non-alphanumeric bone names

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#39327]
**Godot version:**
3.2.2 beta 4 official

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
Recently I've been getting permission issues when importing only glb files. tried opening godot with sudo but with no success

**Update**
IGNORE -> Seems this only occurs with glb file format.
But FBX and GLTF are working OK! <-

this is very strange, I've deleted the .import file and when it has imported the gltf file got the same error as glb
so this means this is not related directly to the file?

![Screenshot from 2020-06-05 17-16-16](https://user-images.githubusercontent.com/58845030/83919339-c6a2c600-a750-11ea-9671-959a687db042.png)

**Steps to reproduce:**
I don't know how to reproduce

**Minimal reproduction project:**
[file.zip](https://github.com/godotengine/godot/files/4738442/file.zip)

**Comment by Calinou** [comment]
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. (We really need one, otherwise, we can't do anything about this bug.)

**Comment by nonunknown** [comment]
well I can upload it, but I'm not sure if it will happen on another pc, I'm almost sure that this problem is with ubuntu 20.04 since I didnt saw this happening on 19.10

**Comment by nightrobin** [comment]
Can you try "sudo chmod 777 -R <path of your project>"

**Comment by mbrlabs** [comment]
This is not a permission issue. The model failed to import because something went wrong while importing the bones. You get the "Cannot open file" error in the .import folder because the .scn file does not exist.
The same thing happens on Windows 10.

**Comment by nonunknown** [comment]
@mbrlabs well if this happens on windows, I think that the problem isnt related to OS tough

**Comment by fire** [comment]
It seems to be related to the bone names in a non-English language somehow.

**Comment by fire** [comment]
Probably related to sanitization.

```c++
String EditorSceneImporterGLTF::_sanitize_bone_name(const String &name) {
	String p_name = name.camelcase_to_underscore(true);

	RegEx pattern_del("([^a-zA-Z0-9_ ])+");
	p_name = pattern_del.sub(p_name, "", true);

	RegEx pattern_nospace(" +");
	p_name = pattern_nospace.sub(p_name, "_", true);

	RegEx pattern_multiple("_+");
	p_name = pattern_multiple.sub(p_name, "_", true);

	RegEx pattern_padded("0+(\\d+)");
	p_name = pattern_padded.sub(p_name, "$1", true);

	return p_name;
}
```

Maybe the first instruction is dropping Japanese.

**Comment by fire** [comment]
I have made a pr for this.
