### ISSUE TITLE
Issues in GDScript parser with assert() function and its arguments

### ISSUE THREAD

**Issue by Arech** [godotengine/godot#39324]
**Godot version:** latest stable 3.2.1

**OS/device including version:** W7 x64, but it shouldn't matter probably

**Issue description:** put the following code in `cbasen.gd`

```python
extends RigidBody2D

class_name CBaseN

func myfunc(arg:float)->void:
	assert(arg>0) #just a valid call
	assert(ar>0) # invalid call, but NO F#@%$ ISSUES WITH THIS LINE!
	#print("d=%d" % [int(ar>0)])  #THIS LINE WON'T WORK HOWEVER,
	#as well as any other possible function call with incorrect argument I tried

```

Try the following code for derived class

```python
extends CBaseN

func _ready():
	myfunc(1) #emits error here however, despite no visible issues with cbasen.gd

```

I walked in gdscript parser under debugger while parsing code of the derived class. The parser indeed does know nothing about myfunc(), though it successfully parses `cbasen.gd`.

------

This issue cost me about half a work day to pinpoint.

It is soooo discouraging... Even more so after looking at the source code that completely lacks any sanity checks and state assertions...

**Comment by Calinou** [comment]
> It is soooo discouraging... Even more so after looking at the source code that completely lacks any sanity checks and state assertions...

GDScript is being rewritten from the ground up: #39093

**Comment by Arech** [comment]
Yes, I know, it is being rewritten, I’ve read the news post on the site. And now I've skimmed through the code of new GDScript... And now I'm feeling much more worried than before, because… well, the old GDScript is at least somehow field tested by community (though, I’m puzzled that nobody ever reported the bug I’ve described in this issue). The new code is…totally new (that is not bad by itself). But I was unable to find any tests of it (we’re aren’t calling `/main/tests/test_gdscript.cpp` “the tests”, aren’t we?). And the code almost totally lacks debugging assertions, checks of internal state/arguments/parameters during code flow… Unfortunately, that’s coherent with the all other Godot’s codebase, but it’s a recipe for disaster(((

**Comment by Calinou** [comment]
> But I was unable to find any tests of it (we’re aren’t calling /main/tests/test_gdscript.cpp “the tests”, aren’t we?).

See https://github.com/godotengine/gdscript-tests.

**Comment by akien-mga** [comment]
Can't rest right now but I think this assert evaluation but might be fixed in 3.2.2 beta 4.

**Comment by Arech** [comment]
> See https://github.com/godotengine/gdscript-tests.

That is very good to hear, thank you!

**Comment by ThakeeNathees** [comment]
this bug already fixed and cherrypicked : https://github.com/godotengine/godot/commit/bd081df51918a00f408845955d00dcbce2cea7a8

in 3.2.2 beta 3 it's working as expected
