### ISSUE TITLE
iPhone 11 and XR render at the incorrect resolution

### ISSUE THREAD

**Issue by ViktorEvil** [godotengine/godot#39325]
**Godot version:**
3.2.1

**OS/device including version:**
iOS 13.5 GLES3

**Issue description:**
iOS export template does not include the launch images that correspond to the iPhone XR and 11.
This makes the phone render at the resolution of 750 x 1334 (iPhone 6 size) instead of 828 x 1792 

![Screenshot 2020-06-05 at 17 27 36](https://user-images.githubusercontent.com/4403212/83905339-682e1580-a759-11ea-94bc-56ed7653bec2.png)

left image is when a correct launch image is used and the blurry right image is without

adding the missing launch images that are shown missing here fixes this

![Screenshot 2020-06-05 at 17 21 29](https://user-images.githubusercontent.com/4403212/83905549-c0fdae00-a759-11ea-84c3-0910f5c5f060.png)

but a better fix is to add a LaunchScreen.storyboard file to the supporting files folder and then
link to it in general setting tab in Xcode. Then deleting the LaunchImages from the assets folder

![Screenshot 2020-06-05 at 17 19 00](https://user-images.githubusercontent.com/4403212/83905995-99f3ac00-a75a-11ea-9926-689bc8b4f77d.png)

adding the storyboard file also has the bonus of getting rid of the warning that Xcode displays about LaunchImages are now deprecated in iOS 13

I had been wrestling with a problem on my iPhone 11 for weeks trying to get a pixel perfect image that I could scale for different iPhones This fixed a lot of my issues

**Steps to reproduce:**
export an iOS project

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by oeleo1** [comment]
Yes, that's been nagging us as well. Thanks for reporting it. The storyboard file is the way to go.
