### ISSUE TITLE
[Feature request] abs() for Vector types (3D and 2D)

### ISSUE THREAD

**Issue by DerRidda** [godotengine/godot#3933]
Currently abs() is not available for Vector types. But seeing how vector maths is super common in game development and abs() is just about one of the most common operations you do on vectors it's needed.
I'll use 3D vectors as an example but it concerns 2D vectors as well.

Doing it manually is tedious, long to write, poorly readable and error prone.
A single typo in this 'sqrt(pow(TESTVEC3D.x,2) + pow(TESTVEC3D.y,2) + pow(TESTVEC3D.z,2))' and awkward things happen that are hard to debug because it's still a legal operation, just not what you wanted. 

The alternative 'TESTVEC3D.distance_to(Vector3(0,0,0))' is slightly better but still heaps worse than a simple 'abs(TESTVEC3D)'.

**Comment by DerRidda** [comment]
Never mind, we have .length()

**Comment by CngKO** [comment]
> Never mind, we have .length()

You also have `Vector2.abs()`
