### ISSUE TITLE
TextureButton is not themeable

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#39344]
**Godot version:**
9f4a14ba97394d1fc08d123c40699c03f56b6aad

**OS/device including version:**
Arch Linux

**Issue description:**
Add Class Items does not include TextureButton when editing themes.

**Steps to reproduce:**
1. Create a theme.
2. Click on Edit Theme
3. Then click on 'Add Class Items'
4. Attempt to find TextureButton -- it's not there

**Comment by KoBeWi** [comment]
It's not a bug, TextureButton doesn't have any theme properties.

**Comment by Rubonnek** [comment]
Then I suppose the documentation is wrong since it claims themes can be applied to any Control nodes.

**Comment by KoBeWi** [comment]
Technically this is true, because you can apply theme to it, but it won't affect any property (although it might affect children controls). Same applies e.g. to Control and ColorRect.

Which part of the documentation says this btw?

**Comment by Gaugeforever** [comment]
Why was this closed?  Why wouldn't scaling and stretch mode, etc be able to be themed?  It clearly has properties which one would want to share across several instances.  Further, one might want the base button properties of a texture button to be different than other button types with the same properties, such as the aforementioned scaling.

**Comment by KoBeWi** [comment]
That's something for a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by schaefchenaufderweide** [comment]
I can confirm, this doesnt work. But TextureButton HAS theme properties. You can also adjust the textures in the theme. They show up in the default preview, but not in game. So ... this is bug!
