### ISSUE TITLE
Save all scenes Hotkey doesn't work while being in script tab

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#39348]
**Godot version:**
3.2.1.stable
**OS/device including version:**
Windows 10 Home 1909
**Issue description:**
If you are in the script tab and press Control+Shift+Alt+S for saving all Scenes, just the scripts are being saved.
**Steps to reproduce:**
Create a scene. Go into the script tab. Press the hotkey for saving all scenes (Control+Shift+Alt+S).
**Minimal reproduction project:**

**Comment by bill8224** [comment]
I believe this to be an issue with an overlap of the hotkey definitions.  The script editor has its own set of hotkeys, including a "save all" hotkey, which has the same key combination, Control+Shift+Alt+S, as the "save all scenes" hotkey for the scene editor. 
Can this be confirmed as intended behavior? Or should a user be able to save all scenes from the script tab?
![scriptIssue](https://user-images.githubusercontent.com/20783113/85362027-75822880-b4eb-11ea-8a61-d73ec42f1d9b.png)

**Comment by MaaaxiKing** [comment]
Since you can save the scene the script is attached to, you should also be able to save all scenes. But I'll make a proposal (when this will be fixed) anyway for that you can set whether pressing the save hotkey in a script saves the scene and the script or just the script and that when you're in the script tab and press the hotkey for saving it should only save the scene if you enabled this option.

**Comment by bill8224** [comment]
Could the key combination Shift+Alt+S be used for save all scripts? This combination isn't a default shortcut for anything currently.
