### ISSUE TITLE
Tree range cell isn't updating when using slider

### ISSUE THREAD

**Issue by giulianob** [godotengine/godot#39349]
**Godot version:**

master 23a2b4ab7d5e61dfc1e5201b95ba447c647676f4

**OS/device including version:**

Windows Vulkan

**Issue description:**

Tree range cell doesn't update when scrubbing the range slider

**Steps to reproduce:**
Click to edit cell then move slider, value should update but it doesn't until you stop editing

**Minimal reproduction project:**

[TreeSample.zip](https://github.com/godotengine/godot/files/4740969/TreeSample.zip)

**Comment by giulianob** [comment]
![cap2](https://user-images.githubusercontent.com/92303/83954380-af2e1080-a816-11ea-97f9-d086173a0ae9.gif)

**Comment by mrushyendra** [comment]
After some bisecting, it seems to be a RenderingServer/window issue. The slider works fine at commit `e2b66ca`, but not from `95a1400` onwards.

[https://github.com/godotengine/godot/commits/master/scene/gui/tree.cpp](url)
