### ISSUE TITLE
Process Material (Shader) in Particles2D makes Sprites to dissapear

### ISSUE THREAD

**Issue by davidkbd** [godotengine/godot#39347]
**Godot version:**
3.2.1-stable

**OS/device including version:**
Issue found in:

Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)

macOS Catalina 10.15.4
AMD Radeon Pro 5300M 4 GB

(Issue found too with nvidia card)

**Issue description:**

We found an issue using particles2D:
We created into our project a Particles2D which has a process material (shader) programmed by scratch. The affected sprite which is failing is placed into a parallax layer, which is also placed into a parallax background having layer = -100. 
The issue makes the background sprite to dissapear.
Also, the Particles2D is placed on the main player's layer. After the issue occurs, if we hide the Particles 2D, the background sprite appears again, and also dissappear if we enable it again.
While there are other particles in the screen emmited by other particles2D, the sprite also appears.

Finally, we detected something relevant: in case we set the background parallax layer to a positive value or 0, the background appears and some other sprites dissappears from the screen.

We attach a video with the issue and the shader code.

**Steps to reproduce:**

Create a scene with a Particles2D with a Shader as a Process Material, but we are not sure 100%.

**Minimal reproduction project:**
[Issue.zip](https://github.com/godotengine/godot/files/4740868/Issue.zip)

**Comment by clayjohn** [comment]
Hi, please attach a Minimal Reproduction Project so that someone can test out and try to reproduce the issue you are experiencing. Without an MRP, it is likely no one will reproduce your error and be able to fix it. 

For clarity, an MRP is the smallest project you can put together that reliably reproduces the issue. A video is not an MRP.

**Comment by davidkbd** [comment]
Ok, thanks. We will try isolate the problem in a small project to be upload here.

**Comment by davidkbd** [comment]
We have been able to isolate the problem and have found something interesting: it seems that with fullscreen display the problem is not present.

To reproduce the issue, is needed to have the fullscreen deactivated at startup. In case you run the project a few times, you will notice the background is gone. Check the new attach videos as a reference.

[issue.zip](https://github.com/godotengine/godot/files/4808712/issue.zip)
[reference-vid.zip](https://github.com/godotengine/godot/files/4808713/reference-vid.zip)
[reference-vid2.zip](https://github.com/godotengine/godot/files/4808720/reference-vid2.zip)

**Comment by clayjohn** [comment]
I have run your test project and followed the steps in the video, but I cannot reproduce the bug. For me the background looks fine no matter what. 

Windows 10, NVidia GTX 1050

We will have to wait and see if someone else can reproduce

**Comment by davidkbd** [comment]
In my computer (Linux Mint, Nvidia Graphs and Intel Graphs) the bug is very dificult to reproduce, I can stay for days without see the bug.
But these videos are recorded in the laptop of my coworker, is a Macos X. Here the bug is very present.

**Comment by Calinou** [comment]
@davidkbd Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
