### ISSUE TITLE
Can't zoom with a tablet

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#3935]
The 2D or 3D editor workspaces can be zoomed with a mousewheel, but it can't be done easily with a graphics tablet.

Panning the view can be done with Space + drag.

Could there be a modifier key to zoom the view also?

**Comment by Hinsbart** [comment]
+1 from me ^^

**Comment by bojidar-bg** [comment]
:+1: from me too, as it sounds reasonable to have one.

**Comment by unfa** [comment]
It's possible!
**
Rotate view: Button 2
Pan view: Shift + Button 2
Zoom view: Ctrl + Buttton 2**

**Comment by Hinsbart** [comment]
Is this also possible on desktops? What is Button 2? ^^

**Comment by neikeq** [comment]
According to those shortcuts, Button 2 is Middle Button.
