### ISSUE TITLE
Shortcuts don't work if Alt is pressed before Shift

### ISSUE THREAD

**Issue by aqt** [godotengine/godot#39351]
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Microsoft Windows [Version 10.0.17134.706]

**Issue description:**
A shortcut that uses both the <kbd>Shift</kbd> and <kbd>Alt</kbd> modifiers does not trigger its associated action if <kbd>Alt</kbd> is pressed before <kbd>Shift</kbd>.

**Steps to reproduce:**
Using the default shortcut mapping for _Quick open_, press <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>, in that order.

**Minimal reproduction project:**
N/A

**Comment by aqt** [comment]
Additionally I'm unable to create a new binding that both these modifiers if I press <kbd>Alt</kbd> before <kbd>Shift</kbd>. I believe that issue would be solved in the process of fixing this one, which is why I haven't created an issue for that.

**Comment by MaaaxiKing** [comment]
If you press Ctrl+Alt+Shift+S in this order everything works. Please rename this to "Shortcuts don't work if Alt is pressed before Shift and Control isn't used"

**Comment by masi456** [comment]
The difference seems to be that when you press the SHIFT key first, the window messages look like this:
![image](https://user-images.githubusercontent.com/9115235/84063483-66668b00-a9c1-11ea-9030-725909623b86.png)

While in the second case the messages look like this:
![image](https://user-images.githubusercontent.com/9115235/84063528-78e0c480-a9c1-11ea-8f04-f7747e23f9ba.png)

Notice the VK_SHIFT in the second case beeing a `WM_SYSKEYDOWN`. The code does not handle this case. It only sets `shift_mem` on `WM_KEYDOWN` messages.
