### ISSUE TITLE
Reloading assets take very long when there's many of them

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39354]
**Godot version:**

3.2.2 beta4

**OS/device including version:**

Windows 10 x64

**Issue description:**

My project has a huge amount of assets (2k+ right now). I tend to rely on texture reloading to make tweaks on the fly. My problem is that the time between me saving changes to image and Godot starting to reimport it keeps increasing. Right now I try re-focusing editor for good -teen seconds before the changes are reflected in Godot.

AFAIK, Godot runs a periodical file scan on a separate thread and large amount of assets makes it take longer. Not sure what can be done about this. More threads or maybe it's possible to detect change of files in a different way. But this is a big problem for my workflow .-.

**Steps to reproduce:**
1. Have a project with **LOTS** of assets
2. Change some image
3. Focus editor and wait until the texture updates in the editor

**Comment by mbrlabs** [comment]
Filesystem notifications like [FindFirstChangeNotificationW ](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstchangenotificationw) for Windows or [inotify](https://www.man7.org/linux/man-pages/man7/inotify.7.html) for Linux would probably the way to go. I actually tought that Godot was already using those APIs but apparently not.

**Comment by fire** [comment]
Is this issue still relevant after the etcpak and multithreaded improvements in master?

**Comment by KoBeWi** [comment]
This issue is about how long it takes until editor starts to re-import something, not the import length. I'd have to check, but most likely it's still relevant.

**Comment by KoBeWi** [comment]
I did a bit more testing and seems like Godot 3.x has problems with picking changes. You need to re-focus editor sometimes. Doesn't seem to happen in 4.0, so I will close this for now.
