### ISSUE TITLE
Shortcut Shift + Alt + Up/Down in script editor has two different actions

### ISSUE THREAD

**Issue by aqt** [godotengine/godot#39352]
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Microsoft Windows [Version 10.0.17134.706]

**Issue description:**
The actions are based on which one of the modifier keys was pressed first:
<kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>Up</kbd> &mdash; Moves the tab for the current file up in the list
<kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Up</kbd> &mdash; Moves the current line up

In both cases I expect the current line to be moved up.

**Steps to reproduce:**
Open two script files and observe the two different actions when pressing:
* <kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>Up</kbd>, in that order
* <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Up</kbd>, in that order

**Minimal reproduction project:**
N/A

**Comment by MaaaxiKing** [comment]
The current line will be moved up/down even without using shift. So pressing Alt+Shift+Up/Down is the same as Alt+Up/Down.

**Comment by aqt** [comment]
I did not realize that was the actual hotkey!
I'll close this issue as it's actually a symptom of the bug I'd reported in #39351
