### ISSUE TITLE
Seemingly valid ogg files fails to import

### ISSUE THREAD

**Issue by ragtag** [godotengine/godot#39358]
**Godot version:**
Godot 3.2.1 stable

**OS/device including version:**
Ubuntu 20.04, intel i7 cpu, intel integrated GPU using GLES2

**Issue description:**
Some .ogg files fail to import into Godot. These file are generated using Google Clouds text-to-speech system, and play fine in VLC and Totem and can validate with oggz, but get the following error when imported into Godot.

```
ERROR: set_data: Condition "ogg_stream == __null" is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:197.
ERROR: import: Condition "!ogg_stream->get_data().size()" is true. Returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing 'res://buggy.ogg'.
   At: editor/editor_file_system.cpp:1800
```

Running "oggz info" on it returns:
```
Content-Duration: 00:00:00.000

Unknown: serialno 0000000000
	2 packets in 3 pages, 0.7 packets/page, 3.847% Ogg overhead
```

Which actually looks wrong, as the duration should not be zero and it should look more like this:
```
Content-Duration: 00:00:00.710

Vorbis: serialno 18446744073068711464
	72 packets in 3 pages, 24.0 packets/page, 1.171% Ogg overhead
	Audio-Samplerate: 48000 Hz
	Audio-Channels: 1
```
This may just be Godot being more strict at handling Ogg Vorbis files, requiring them to have correct header info, so may not really be a bug.

**Steps to reproduce:**
Just open the attached project, and read the output.

The project includes two ogg files, buggy.ogg which has the issue and working.ogg which is the same sound, but re-converted to ogg using some random online tool. Both files are 48000 Hz Mono files.

**Minimal reproduction project:**
[OggBug.zip](https://github.com/godotengine/godot/files/4741611/OggBug.zip)

**Comment by quanixstudio** [comment]
If you try to load the buggy ogg in Audacity it will also give an error and won't open.
VLC probably just plays fine because it detects the raw contents of the file as an ogg file.

**Comment by ragtag** [comment]
Thanks for the quick reply. I guess you can just close this bug, as this really seems to be a bug with Google's text-to-speech engine generating invalid ogg files, and not a problem with Godot. :)

For reference, I used Python and the method described [here](https://cloud.google.com/text-to-speech/docs/create-audio#text-to-speech-ssml-python) to generate the files. It also supports mp3 and wav generation, so now I'm just generating wav files and converting them to ogg afterwards using oggenc, which works fine in Godot.
