### ISSUE TITLE
RigidBody2D woken up from sleeping state when parent's transform changed

### ISSUE THREAD

**Issue by Arech** [godotengine/godot#39366]
**Godot version:** latest stable 3.2.1.

**Issue description:** Changing transformation (for example, moving) parent node wakes up all it's children `RigidBody2D` nodes (via `SceneTree::flush_transform_notifications()`)

I think it's a bug, because I can't see any reason to start physics processing of a `RigidBody2D` when it's parent was moved. Imagine a most common use-case when you are using parent node just to conveniently group set of nodes and keep their relative position constant. What the parent move in that case have to do with child sleep-wake state?

If the devs are absolutely sure it's not a bug, would somebody kindly update the docs? (
the issue again cost me about half a day to pinpoint). Please, don't forget to mention, that after parent's move, children sleep state can be set again only at next processing iteration (for example, via `call_deferred()`)

**Steps to reproduce:** see MRP
[godot_test.zip](https://github.com/godotengine/godot/files/4742222/godot_test.zip)

**UPD2**: still debugging my code (not covered in MRP). It seems that there are more sources that may wake up the RigidBody2D (wrongly, I think).

For example, `CollisionObject2DSW::_shape_changed()` (I don't know why it's called, there should be no shape changes and no collisions), eventually calls `Body2DSW::wakeup_neighbours()` and `Body2DSW::set_active(true)` for object that logically must remain sleeping.

**Comment by madmiraal** [comment]
I don't understand the issue. `Rigidbodys` sleep, because they're not moving and not interacting with anything. This saves processing time; nothing more. A bug would be if the `Rigidbody` didn't wake up when it should, not that it does wake up when it didn't need to.

**Comment by Arech** [comment]
Errr... Sleeping state are meant to save processing resources, we agree on that, right?

When something must not consume resources, but it still consumes it, what is it if not a bug?

**Comment by Arech** [comment]
Also, please consider, that current behaviour renders `VisibilityEnabler2D` node totally useless one it is used in conjunction with node dynamic placement (actually, that is how I stumble on the issue - I was trying to find why nodes that must be sleepy under `VisibilityEnabler2D` condition, are still active)

**Comment by akien-mga** [comment]
> Changing transformation (for example, moving) parent node wakes up all it's children `RigidBody2D` nodes (via `SceneTree::flush_transform_notifications()`)
> 
> I think it's a bug, because I can't see any reason to start physics processing of a `RigidBody2D` when it's parent was moved.

Well, if you move the parent node, the children might end up triggering collisions with other bodies, so they shouldn't be sleeping, should they?

**Comment by madmiraal** [comment]
I still don't understand the issue. Why do you think it's important that `Rigidbodys` are asleep?

**Comment by Arech** [comment]
> Well, if you move the parent node, the children might end up triggering collisions with other bodies, so they shouldn't be sleeping, should they?

Agree with that, but shouldn't they be woken up as a result of collision? If collision indeed happened, - they must be woken up. But if not - why waste resources?

**Comment by Arech** [comment]
> Why do you think it's important that Rigidbodys are asleep?

I think that proper sleeping state is important, because it helps to conserve resources. It is a logical and most obvious and consistent to the docs way to shutdown some heavy physical processing when it is not needed.

**Comment by madmiraal** [comment]
> shouldn't they be woken up as a result of collision? If collision indeed happened, - they must be woken up. But if not - why waste resources?

They need to be awake to detect collisions.

**Comment by madmiraal** [comment]
> I think that proper sleeping state is important, because it helps to conserve resources. It is a logical and most obvious and consistent to the docs way to shutdown some heavy physical processing when it is not needed.

... and this is what Godot does.

I still don't understand the issue you're experiencing. Instead of a bug, this sounds more like an opinion on how a game engine should be designed.

**Comment by Arech** [comment]
Well, ok, I understand that.

Lets look at it in another way. That is an implementation detail, the node must be awake to be able to detect collision. I got it right?

What arguments support the claim that this implementation is correct? When a sleeping node awakes without no apparent reason - no collision, no force/impulse applied (that is how the waking are defined in the docs, btw, and this promise is very important), but just because this is how the engine works, is it a correct behaviour?

Couldn't the code be refactored to check for collisions of sleeping nodes right after these nodes were moved, and if there were no collisions, they will remain in sleeping state? That behaviour matches the promise in the docs, isn't?

**Comment by madmiraal** [comment]
I still don't understand the issue you're experiencing. Aside from saving resources, why is it important that Rigidbodys are asleep?

**Comment by Arech** [comment]
Errr... there is no "aside". Saving resources is the very issue.

I have quite a lot instances of RigidBodies with quite a heavy physics involved. I would like to suspend them because they start to introduce lags.

Sleeping state in conjunction with VisibilityEnablers in a way they are described in the docs looks precisely as the proper solution. And extremely easy to implement too.. But instead it is not, because actually the docs promise are not kept.

So, I think, proper solution is to consider the docs promise as a correct promise, it is logical, and to update the code. If for some reason it is not desirable, at least docs, I think, should correctly reflect that sleeping state is not what is.

---

It is extremely frustrating that docs confidently promise something and it does not work as promised. And then next thing doesn't work as described. And the next... I'm okay with that, it's just part of maturing a code. The problem - it's totally unexpected.

**Comment by Arech** [comment]
@madmiraal Have you seen the docs yourself? I'm struggling to not interpret your comment as a joke.

`bool can_sleep`  https://docs.godotengine.org/en/latest/classes/class_rigidbody2d.html?#class-rigidbody2d-property-can-sleep

> If true, the body will not calculate forces and will act as a static body if there is no movement. The body will wake up when other forces are applied via collisions or by using apply_impulse or add_force.

No it is not.

---

(1) If true, the engine are given a right to send the body into a sleeping state if it doesn't move. Then it will not calculate forces and will act as a static body, **untill**

(2) other forces are applied via collisions or by using apply_impulse or add_force, **OR** by some other (obscure/not obvious or detectable) reason, because there's no clear definition of what sleeping state is, which allows multiple interpretations. For example, the following may/will wake up the node:

- transform change of (probably any) parent node. For example, moving the parent of the node.
- spirituous collision from a node that must not collide at all, see #39374

---

That's a different promises and a waaay different expectations, isn't it? But at least they are kept by the current code.

Same corrections applies to `bool sleeping` property https://docs.godotengine.org/en/latest/classes/class_rigidbody2d.html?#class-rigidbody2d-property-sleeping
