### ISSUE TITLE
OptionButton's Items are saved before pressing OK

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#39360]
**Godot version:**
3.2.1.stable
**OS/device including version:**
Windows 10 Home 1909
**Issue description:**
If you add change an item of an OptionButton, it is saved, changed before you pressed the OK button. If you then decide the item should not be changed/added, you would press the x button at the top right corner. I think there should be a Cancel Button next to the OK button. https://github.com/godotengine/godot-proposals/issues/1020
**Steps to reproduce:**
Create a scene with root node OptionButton. Press the item button. Click the "+Add" button. Press the x Button.
**Minimal reproduction project:**

Not possible.

**Comment by KoBeWi** [comment]
Since you already made a proposal, I will close this issue.
