### ISSUE TITLE
Setting RigidBody2D.sleeping=true doesn't invoke sleeping_state_changed()

### ISSUE THREAD

**Issue by Arech** [godotengine/godot#39367]
**Godot version:** not so stable 3.2.1

**Issue description:** closely related to #39366.

Setting `RigidBody2D.sleeping` property to `true` (just haven't tried with `false`) doesn't invoke sleeping_state_changed() signal callback. The callback sometimes invoked though, when engine sets the node to a woken state.

**Minimal reproduction project:** use MRP of #39366.

Make sure `cbasen.gd` contains

```python
func _ready()->void:
	connect("sleeping_state_changed",self,"_on_sleeping_state")

func _on_sleeping_state():
	print("%s %s" % [get_name(), "SL" if sleeping else "w"])
```

and `main.gd`

```python
func _ready():
	$Node2D.position.x+=1
	call_deferred("sleepefy")

func sleepefy()->void:
	print("sleepefy n1, but NOT n2")
	$Node2D/n1.sleeping=true
```

Run and observe that `_on_sleeping_state()` is NOT invoked after `sleepefy()` executes `$Node2D/n1.sleeping=true`.

----------

Guys... Please stop calling the builds `stable`. This is important!

I have never-ever-ever seen in my life and 20+ years programming career software, that uses so big version numbers, labels itself as "stable" and still so full of various bugs and glitches! I consider myself a "quite" experienced C++ developer (something reflected in my profile), but I'm having to really struggle with making Godot work. I hardly imagine emotions of those who are less experienced and are stuck with numerous Godots issues... Just don't lie to your customers, that it's a stable thing. If it fails not too often, it doesn't make it deserving `stable` badge. `Early pre-alpha` is suitable much better. That doesn't make anybody love the project less, they will just know in advance what to expect.

**Comment by madmiraal** [comment]
This is by design. If you want to your manual change to send a signal then you must use the `emit_signal` function.

**Comment by akien-mga** [comment]
I think this might just be a documentation issue.

The current documentation says that `sleeping_state_changed` is emitted when the `sleeping` property changes, but that's not true. It's emitted when the sleeping state of the RigidBody changed in `PhysicsDirectBodyState2D` and the `sleeping` property is thus updated by the physics engine.

In this MRP, the body is sleeping at the start. The sleeping state is set to `true` from script, which is the same as the previous value, and since the physics state is not being updated due to the chosen sleeping status, there's no `sleeping_state_changed` to propagate.

I'd suggest making the signal's documentation clearer (both for 2D and 3D rigid bodies).

**Comment by Arech** [comment]
Errr... Well... Why not to update the docs then?

It really confuses when you read that "Emitted when sleeping changes." and it turns out, that it is actually not at all true.

**Comment by Arech** [comment]
@akien-mga Remi, thanks! You're right. The issue is in the docs then...

**Comment by Arech** [comment]
I may try to make an update to the docs, if some help needed...Need to find the docs contribution guide first...

**Comment by Calinou** [comment]
@Arech It's here: https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html

**Comment by Arech** [comment]
Made the pull..

Also, I'd suggest to append these rephrased @akien-mga words to a cut-out note somewhere in https://docs.godotengine.org/en/latest/getting_started/step_by_step/signals.html

> Signals in Godot are emitted by the engine when it does something noteworthy internally. Signals are not raised to notify you of your own action - you don't need a callback to react to you setting some object's property, as you can call a callback manually or emit your own signal in that same code block.

That would be really helpful to know in advance for a rookie. But I don't get where are the sources of that part of docs located.

**Comment by Calinou** [comment]
@Arech The documentation pages are located in this repository: https://github.com/godotengine/godot-docs

Specifically, you'll want to modify `getting_started/step_by_step/signals.rst` and open a pull request there.

**Comment by Arech** [comment]
@Calinou thank you for your help!
