### ISSUE TITLE
Upscaling an image with `resize` makes it pixelated even with BILINEAR explicitely specified

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#39371]
Godot 3.2.2 beta4
Godot 3.1.0

Windows 10 64 bits

When I use `Image.resize` to make it larger, I can clearly see it pixelated, even though the default filter is supposed to be `INTERPOLATE_BILINEAR`. Specifying it explicitely doesn't fix the problem.
This also affects my terrain plugin, which is now breaking when the user wants to resize the heightmap (format `RH`), it becomes riddled with staircases.

Test project:
[ImageResizeBilinear.zip](https://github.com/godotengine/godot/files/4742603/ImageResizeBilinear.zip)

**Comment by akien-mga** [comment]
Something for @lawnjelly maybe? :)
