### ISSUE TITLE
Godot random generator is broken

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#3937]
As we can see here https://github.com/godotengine/godot/blob/master/core/math/math_funcs.cpp#L88 Godot uses broken way of generating random double:

```
(double)rand() / (double)RANDOM_MAX;
```

which does not give us uniform distribution.

Bad news is that gcc/clang ( and probably MSVC ) also don't have perfect double genrators :disappointed:  ( with C++11 uniform_real_distribution )

On the upside - there are some libraries that try to give ~good pseudo-random doubles ( eg. https://github.com/art4711/random-double )

**Comment by Marqin** [comment]
If you want to implement your own double-generator, here are some sources:

- https://readings.owlfolio.org/2007/generating-pseudorandom-floating-point-values/
- https://news.ycombinator.com/item?id=9352905

**Comment by est31** [comment]
pcgrandom is a good algorithm too: http://www.pcg-random.org/

**Comment by tagcup** [comment]
[This algorithm](http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/ARTICLES/dSFMT.pdf) generates random doubles uniformly, and it also has an implementation from the authors under a permissive license. Maybe it can be bundled with godot?

**Comment by Calinou** [comment]
Is this issue still relevant since [PCG has been merged in early 2017](https://github.com/godotengine/godot/pull/7532)?

**Comment by est31** [comment]
I don't think so
