### ISSUE TITLE
"Parse Error: The function signature doesn't match the parent" doesn't follow class hierarchy

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#39382]
**Godot version:**

3.2.2 beta4

**OS/device including version:**

Windows 10 x64

**Issue description:**

When importing a project from godot 3.0 to 3.2.2 beta 4, I noticed several errors flagged by the parser for functions that matched a name elsewhere in the classDB but were unrelated to the class hierarchy of objects which contained these functions.  In my case, it was a `ColorRect` using `get_color()` with no arguments, believing its parent signature belongs to `Color`.  This was a blocking error the first time I opened the project, but after re-opening in 3.2.1 and coming back, the error didn't block launching the project.  The error still persists, however, despite `ColorRect` not being a child of `Color` or any other class which uses this function.

**Steps to reproduce:**
Untested:
1.  Attach script to `ColorRect` and add `get_color()` func.
2.  Call this from another script so it is reachable.

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Can you post those errors you mention and an MRP so that others can figure out what is going on?

**Comment by nobuyukinyuu** [comment]
I'd like to do this with RC1 but I read that it would change `.csproj` files automatically and am worried it might mess with my assembly ref configuration in the specific project this issue occurs in.

Project commit this should occur in can be located here however:  https://github.com/nobuyukinyuu/gdsFM/tree/a51c295ebb500f1a850624585fdfa4eaf68b007f

Will try to reproduce error in an MRP using a future build if this issue can't be trivially replicated.

**Comment by nobuyukinyuu** [comment]
Closing this issue as it no longer appears to occur in 3.2.2 mono stable.
