### ISSUE TITLE
Convert to translatable strings option does not allow to save the POT file with POT extension

### ISSUE THREAD

**Issue by olivergs** [godotengine/godot#3938]
**Operating system or device:** All

**Issue description** (what happened, and what was expected):
Tried to convert current scene to translatable strings but when tried to save the .POT file, the program insist me to use an allowed extension name from the save dialog list (SCN, XML, etc.) The expected result was to be able to save the POT file.

**Steps to reproduce:**
Go to menu:

Scene -> Convert to -> Translatable strings
Click on save button
The error mesage dialog appears

**Link to minimal example project** (optional but very welcome):
Any scene with a root node would work

**Comment by reduz** [comment]
This option is deprecated and will go away in 2.1 Check the tutorials on
internationalization

**Comment by olivergs** [comment]
Thanks reduz. Didn't know that pot translation were to be deprecated. I've seen the tutorials, and I'm familiar with use of pot/po pipeline so I preferred to use that way.

Only one question about that then. Is there a way to export all translatable strings to have them in the CSV file?

I've seen the documentation and it seems that the translation keys export is completely up to the developer to write them down in the CSV file every time he creates a new string subject to be translated.

Thanks

**Comment by neikeq** [comment]
I am closing this issue since the feature is deprecated. @reduz can still answer your last question but, in case he doesn't answer, you may want to ask in [the QA site](http://godotengine.org/qa/) or open a new issue requesting that feature.
