### ISSUE TITLE
TileSet.is_tile_bound() is not documented

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot#39381]
**Your Godot version:**
3.2.1 stable

**Issue description:**
TileSet.is_tile_bound() is not documented

**URL to the documentation page:**
https://docs.godotengine.org/en/3.2/classes/class_tileset.html#class-tileset-method-is-tile-bound

**Comment by akien-mga** [comment]
This should be documented here (under the `<description>` tag):
https://github.com/godotengine/godot/blob/ec1bf96e412b7a207ffb55d6acd56b25eb25845f/doc/classes/TileSet.xml#L39-L48
