### ISSUE TITLE
JSON file not being read when exported as a .apk even with the *.json export filter

### ISSUE THREAD

**Issue by AlecFaye** [godotengine/godot#39380]
**Godot version:**
3.2.1

**OS/device including version:**
Android 10

**Issue description:**
The JSON files were able to be read when run by Godot, but when I exported it as an apk with the *.json filter, the JSON file couldn't be read by my Android device.
![AndroidExportSettings](https://user-images.githubusercontent.com/56772678/83981542-de16b600-a8ec-11ea-8b1e-3272ee3bb431.PNG)

![ExportFilterSettings](https://user-images.githubusercontent.com/56772678/83981544-e111a680-a8ec-11ea-8952-3af98b904c16.PNG)

**Steps to reproduce:**
1. Make a simple project.
2. Make a JSON file with an array of "Hello" and "World"
3. Connect it with a label and replace the text
4. Set *.json on the export filter in resources
5. Export to Android

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/4743128/New.Game.Project.zip)

**Comment by bruvzg** [comment]
Try using `res://Tester.json` (open file from resource path or PCK/APK) instead of `Tester.json` (open file from the current directory).

**Comment by AlecFaye** [comment]
Okay. Thank you so much! I was fretting over it for so many hours and it was just that. Much appreciated.
