### ISSUE TITLE
Basis in C# missing default constructor.

### ISSUE THREAD

**Issue by vtaepe** [godotengine/godot#39397]
https://github.com/godotengine/godot/commits/master/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs

I believe the file is missing default constructor - documentation says it should produce an identity basis.

**Comment by neikeq** [comment]
This is explained here: https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_differences.html#basis
Use `Basis.Identity` to get the equivalent of the default constructor in GDScript and C++.
Unfortunately C# doesn't allow structs to have a custom parameterless constructor, nor to hide the default constructor, so we have no way to prevent this confusion.
