### ISSUE TITLE
Fix dependencies doesn't work

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#3940]
When opening scene with broken depedencies, selecting the proper ones in the pop up does not give any effect. The directory string doesn't change after selecting the correct one.
The only solution is to change dependencies manually and reaload the scene.

Windows 7. Godot 2.0 stable.

**Comment by eska014** [comment]
Was this scene file saved with editor setting `On Save`→`Save Paths As Relative` enabled?

**Comment by Krzycho666** [comment]
No. It's disabled in my editor.

**Comment by pcvonz** [comment]
I can fix gdscript dependencies, however inherited scenes saved as .tscn do not.

**Comment by akien-mga** [comment]
Is this issue still valid as of 2.1?

**Comment by KioriSun** [comment]
This is still broken.
Also, the editor should detect when a scene file has broken dependencies and the "fix dependencies" option should be available after 'first open', just in case.
Maybe as a right-click pop-up when selecting the file on the filesystem view?

**Comment by bojidar-bg** [comment]
Is this issue still valid in 3.x?

**Comment by KoBeWi** [comment]
> Is this issue still valid in 3.x?

No.

**Comment by HunterWilkins** [comment]
Yes it is - happening in Godot 4. Deleted one file (in the editor) and the entire project is "corrupted."
