### ISSUE TITLE
some editor shortcuts dont work inside tileset editor

### ISSUE THREAD

**Issue by hero2002** [godotengine/godot#39403]
i went to to disable grid snapping in tileset editor and i found that it dont work there
is there another shortcuts for it?
and thanks

**Comment by Schweini07** [comment]
Shortcuts still work in the Tileset Editor.

Grid Snapping has the shortcut `Shift+G`

**Comment by hero2002** [comment]
> Shortcuts still work in the Tileset Editor.
> 
> Grid Snapping has the shortcut `Shift+G`

not working in tileset editor i tried it

**Comment by Schweini07** [comment]
Maybe Hardware specific?

Did you try it on other devices?

**Comment by hero2002** [comment]
> Maybe Hardware specific?
> 
> Did you try it on other devices?

no i didn't
but i don't think its the problem 
i think they didn't implement it in godot

**Comment by Schweini07** [comment]
With Tileset Editor, do you mean that: 
![image](https://user-images.githubusercontent.com/47503977/84625292-45cb9300-aee3-11ea-86af-9fc7eded4bfc.png)

Or that:
![image](https://user-images.githubusercontent.com/47503977/84625327-51b75500-aee3-11ea-8e8c-88d1fba19ae8.png)

**Comment by hero2002** [comment]
The second one

**Comment by hero2002** [comment]
The second one
I needed the shortcut because I was editing my tile and when i do the collision layer every time I have to disable grid snapping every time

**Comment by Schweini07** [comment]
Oh, that makes it much clearer.
This is then more of a proposal, you want shortcuts to work in the tilemap editor, so open a Issue at godotengine/godot-proposals and close this one.
The main Github Repo is now only for bug tracking.

**Comment by hero2002** [comment]
oh sorry i thought it should work in there
