### ISSUE TITLE
Godot CLI fails exporting project due to "Invalid export preset name: HTML5".

### ISSUE THREAD

**Issue by SecretPanda420** [godotengine/godot#39406]
**Godot version:**
3.2.1 Headless 64 bit

**OS/device including version:**
Ubuntu 18.04.4 LTS

**Issue description:**
I'm setting up Github workflows for easy continuous integration while working on my project.
This is my `/.github/workflows/main.yml`:

```
name: Godot CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          mkdir -v -p project/
          mkdir -v -p godot/
          cd godot
          curl https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip > Godot_v3.2.1-stable_linux_headless.64.zip
          unzip Godot_v3.2.1-stable_linux_headless.64.zip
          chmod +x Godot_v3.2.1-stable_linux_headless.64
          cd ..

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: project/

      - name: Web Build
        run: |
          mkdir -v -p builds/web
          cd godot
          ./Godot_v3.2.1-stable_linux_headless.64 --path ../project/ --export "HTML5" ../builds/web/index.html
```

and when exporting this project I get this error:
```
Godot Engine v3.2.1.stable.official - https://godotengine.org
 
ERROR: get_language_code: Invalid locale 'C'.
   At: core/translation.cpp:945.
ERROR: set_locale: Unsupported locale 'C', falling back to 'en'.
   At: core/translation.cpp:969.
reimport: begin: (Re)Importing Assets steps: 1
	reimport: step 0: icon.png
ERROR: _fs_changed: Invalid export preset name: HTML5.
reimport: end
   At: editor/editor_node.cpp:634.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```
I guess the whole point of headless version is for easy CI. I've also tried exporting to Linux with command arguments as `./Godot_v3.2.1-stable_linux_headless.64 --path ../project/ --export "Linux/X11" ../builds/linux/game.zip` and got the same error. I personally do not own a Linux machine myself so I cannot test it locally but the CI does give me these errors I doubt testing it on CI and on a local linux machine would give different results. [Logs of the CI run.](https://pastebin.com/X3pbQtEQ)

This is similar to `#16949` but the error logs are different.

**Steps to reproduce:**
* Make a simple project
* Download 3.2.1 Godot Engine Headless
* Export your project.

**Minimal reproduction project:**
Make the most basic project possible, I just made a simple project with a button which prints out "hello" when pressed. This bug is regardless of the type of project, although I have still attached the project I was testing with if it helps.
[godot-project-master.zip](https://github.com/godotengine/godot/files/4750620/godot-project-master.zip)

**Comment by Calinou** [comment]
Is your `export_presets.cfg` file committed to version control? This must be done for CI exporting to work.

Note that this file will contain sensitive credentials if you have Android export presets in your project.

**Comment by SecretPanda420** [comment]
I indeed did not commit `export_presets.cfg`. Thanks for pointing it out!
I'm getting this now while running it in the CI 
```
EditorSettings: Save OK!
reimport: begin: (Re)Importing Assets steps: 1
	reimport: step 0: icon.png
ERROR: _fs_changed: Cannot export project with preset 'HTML5' due to configuration errors:
No export template found at the expected path:
/home/runner/.local/share/godot/templates/3.2.1.stable/webassembly_debug.zip
reimport: end
No export template found at the expected path:
/home/runner/.local/share/godot/templates/3.2.1.stable/webassembly_release.zip

   At: editor/editor_node.cpp:611.
ERROR: _fs_changed: Project export failed for preset 'HTML5', the export template appears to be missing.
   At: editor/editor_node.cpp:634.
EditorSettings: Save OK!
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```
How can I download the template managers in CLI?

**Comment by Calinou** [comment]
> How can I download the template managers in CLI?

Download export templates and extract them to the appropriate folder:

```bash
curl -fsSLO https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
unzip Godot_v3.2.1-stable_export_templates.tpz
mkdir -p "$HOME/.local/share/godot/templates/3.2.1.stable/"
mv templates/* "$HOME/.local/share/godot/templates/3.2.1.stable/"
```

We should add a CLI argument to do this in the future.

**Comment by SecretPanda420** [comment]
> > How can I download the template managers in CLI?
> 
> Download export templates and extract them to the appropriate folder:
> 
> ```shell
> curl -fsSLO https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
> unzip Godot_v3.2.1-stable_export_templates.tpz
> mkdir -p "$HOME/.local/share/godot/templates/3.2.1.stable/"
> mv templates/* "$HOME/.local/share/godot/templates/3.2.1.stable/"
> ```
> 
> We should add a CLI argument to do this in the future.

Cool I'll be looking forward to it!

**Comment by SecretPanda420** [comment]
Does Godot not check for errors in scripts while exporting, or do I have to run each script using `godot -s <script>` before exporting to confirm that nothing in my project is broken? I purposely removed a `)` from a GDScript function declaration and the CI **passed** with output:
```
Godot Engine v3.2.1.stable.official - https://godotengine.org
 
ERROR: get_language_code: Invalid locale 'C'.
Unsupported locale 'C', falling back to 'C'.
   At: core/translation.cpp:945.
ERROR: set_locale: Unsupported locale 'C', falling back to 'en'.
   At: core/translation.cpp:969.
CORE API HASH: 10822102301860774635
EDITOR API HASH: 14982495073158502407
Loading resource: res://default_env.tres
Construct gdnative interface

Destruct gdnative interface

Loaded builtin certs
EditorSettings: Save OK!
reimport: begin: (Re)Importing Assets steps: 1
	reimport: step 0: icon.png
savepack: begin: Packing steps: 102
	savepack: step 2: Storing File: res://Base.tscn
	savepack: step 27: Storing File: res://Button.gdc
	savepack: step 52: Storing File: res://default_env.tres
	savepack: step 77: Storing File: res://.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex
	savepack: step 77: Storing File: res://icon.png.import
	savepack: step 102: Storing File: res://Button.gd.remap
```
Is it just the way it should be or will it be considered another bug? I personally think it should check for errors in scripts while exporting. How should we go about this @Calinou 
I get this is not related to this issue anymore but just want to clear things up before opening another issue in case I'm misunderstanding if anything.

**Comment by Calinou** [comment]
> Does Godot not check for errors in scripts while exporting, or do I have to run each script using godot -s <script> before exporting to confirm that nothing in my project is broken? I purposely removed a ) from a GDScript function declaration and the CI passed with output:

This is expected. Exporting doesn't perform any kind of static analysis. There's a `--check-only` CLI switch you can use along with `-s`.

**Comment by SecretPanda420** [comment]
> Maybe it could be done in the future, but keep in mind doing this will slow down exporting a bit, especially in large projects.
I personally think it should be done just as all other game engines do. There could also be a flag if used checks for errors in all the scripts while exporting. Although for now I'll stick to manually having another step which checks for errors in my scripts.
Thanks!
