### ISSUE TITLE
bool_var = true == !false causes error

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#39401]
**Godot version:**

3.2.1 stable

**OS/device including version:**

WIndows 10

**Issue description:**

bool_var = true == !false causes error "unexpected two consecutive operators" Also is produced when replacing true and false with boolean variables or methods. Can be overcome by using != false instead of == !false. You can also do (!false) and that works. This specific issue is very low priority but it could be the case that the source of this issue is causing greater issues in other contexts. 

**Steps to reproduce:**
unzip file Error should be on display

**Minimal reproduction project:**

[boolError.zip](https://github.com/godotengine/godot/files/4748122/boolError.zip)

**Comment by akien-mga** [comment]
As discussed in #39408, this can't be fixed and is thus not a bug but a design decision.
The `not` operator has relatively low precedence as it can often operate to negate compound expressions like `not a in array`.

**Comment by vnen** [comment]
This actually works fine with the new parser. It doesn't break the `not a in array` case either, because precedence didn't change.
