### ISSUE TITLE
Resizing window to "minimal" size is muting AudioStreamPlayer2D

### ISSUE THREAD

**Issue by Delectus98** [godotengine/godot#39420]
**Godot version:**

Godot_v3.2.1-stable_mono_win64

**OS/device including version:**

OpenGL ES 3.0 Renderer: AMD Radeon HD 7480D
Windows

**Issue description:**

I'm trying to make a small resizable window to play music. When I play my own music, it seems that when the window is resized to a very small size, the AudioStreamPlayer2D sound is muted and then restored when the window size increases.

**Steps to reproduce:**
In a new scene, create a AudioStreamPlayer2D attached to a Node2D and load a random wav file to it. Set "Playing" value to true before starting the scene. When the window shows up, resize the window to make it the tiniest size visible. This bug only happens when Project settings set window stretch with "viewport" and "expand".

```
Scene:
> Node2D
        > AudioStreamPlayer2D [auto-playing / playing = true]
```

**Reproduction project:**

[BugReport_09_06_2020.zip](https://github.com/godotengine/godot/files/4754356/BugReport_09_06_2020.zip)

**Comment by KoBeWi** [comment]
This is because the "2D listener" is placed at the center of the screen. When you minimize window, the center moves away from the AudioStreamPlayer2D.

**Comment by Delectus98** [comment]
Ok i figured out why this is happening. The two sides (left and right)  of the window correspond to ears and when i'm resizing the window with this stretch (viewport and expand) the ears position are scaled too. This puts the positions of the ears even further away than when the size is proportional to the original size
