### ISSUE TITLE
"Can't copy executable file" when trying to export binary without specifying a binary name

### ISSUE THREAD

**Issue by sunnystormy** [godotengine/godot#3942]
*Bugsquad edit:* The issue was that the editor gives a cryptic message if one forgets to define the binary name before clicking "Export". This could be improved by either filling a binary name by default, or preventing clicking "Export" if no binary name is given.

--------------

**Operating system or device:**
OpenSUSE Tumbleweed.

**Issue description** (what happened, and what was expected):
I'm unable to get projects exported using the export templates provided.

**Steps to reproduce:**
Export a project outside of the project folder using the LinuxX11" export type.

**Link to minimal example project** (optional but very welcome):
I used the 3D platformer demo, as well as the Tetris demo and got the same result.

**Comment by akien-mga** [comment]
Why close the issue? Did you solve it yourself?

**Comment by sunnystormy** [comment]
@akien-mga I did! I realized that I wasn't writing a file name for the executable in the "file" dialog before exporting the binary. Perhaps an warning should pop up in this case? Or disable the export button altogether?

**Comment by akien-mga** [comment]
I'll reopen it as a possible usability improvement then.

**Comment by demolitions** [comment]
Would an error "You must specify a file name" do the job in this case?

**Comment by sunnystormy** [comment]
@demolitions I think that would work. :+1:
