### ISSUE TITLE
Unmatched half_float GLOBAL_DEF and GLOBAL_GET

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#39425]
**Godot version:**
9901eac9f54dc5148a668acc5767d63da0665136

**OS/device including version:**
Arch Linux

**Issue description:**
```
W 0:00:00.388   _get: Property not found: rendering/gles2/debug/disable_half_float
  <C++ Source>  core/project_settings.cpp:209 @ _get()
```

**Steps to reproduce:**
* Clear disable half float settings on project.godot directly using a text editor.
* Set disable half float using the editor on project settings.
* Run editor.

**Comment by akien-mga** [comment]
Fixed by #39426.
