### ISSUE TITLE
HDR render target not working for canvas shader (GLES3)

### ISSUE THREAD

**Issue by durson** [godotengine/godot#39435]
Version: 3.2 (branch 3.2)
Commit tested: 4f02fd7ecac9bb3d4ded324dec3b670f5e459730
Commit tested 2: [tag 3.2]
Build opts: platform=x11 tools=yes target=release_debug bits=64

Backend: GLES3
GPU: GeForce GTX 1650 (mobile)
Driver Version: 440.82

Setup:
My scene has sub-viewport as follows:
|-Camera
|-Viewport (hdr enabled)
---|-ColorRect

ColorRect is equipped with a simple shader that fills viewport with a color:
shader_type canvas_item;
void fragment() { COLOR = vec4(1, 1, 10, 1); // outside [0,1] range }

Issue:
Viewport texture is successfully filled with a color, but values are saturated to [0,1] range.
RT format is 5, so I changed viewport settings to [3d enabled]. It changed RT format to 15 [good], 
but the problem still exists. Global settings have hdr enabled.

Solution:
I created a camera, set viewport to [own_world=true]
I created f-s quad as MeshInstance and set shader_type to spatial and render_type to unshaded.
After writing hdr values to ALBEDO it works. But 2d shader still saturates value into [0, 1] range.

**Comment by filsd** [comment]
I have this as well.
On my 2d game I have a World Environment node in Canvas mode that applies Glow and other effects. The World Environment uses HDR and when I activate the canvas shader the colors get brighter and weird.

This is without problems (Only World Environment ON):
![canvas_shader_hdrBUG_off](https://user-images.githubusercontent.com/5324533/109166776-d25d6f00-775b-11eb-9690-4512f7ffdf01.jpg)

With the bug (World Environment + Simple canvas blur shader):
![canvas_shader_hdrBUG_on](https://user-images.githubusercontent.com/5324533/109167055-1ea8af00-775c-11eb-9d8a-e63bb7458fd4.jpg)

Scene Tree looks like this:
![canvas_shader_hdrBUG_SceneTree](https://user-images.githubusercontent.com/5324533/109167130-32ecac00-775c-11eb-86ee-b0e7a9fa6803.jpg)

I think its related to this bug.

**Comment by Calinou** [comment]
@durson @filsd Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by filsd** [comment]
> @durson @filsd Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Here is a simple project:
[Canvas_shader_hdrBUG.zip](https://github.com/godotengine/godot/files/6044589/Canvas_shader_hdrBUG.zip)

I did my best to reproduce the problem. Our in development game is very complex and uses 2d lamps and Tiles with Normalmap.
But when trying to reproduce the bug, it ended up making the possible source of the problem clearer:
I think it's related to CanvasModulate + Canvas Shader.
If I remove one of the two, the colors become "normal".

**Comment by filsd** [comment]
**Update:**
I researched more about shaders and found that, in my case, the problem was that I didn't skip the lighting step (using _render_mode unshaded;_) in the shader and that ended up "doubling" the lighting effects.

I apologize for the confusion.
I thought it was this bug because I previously had problems using 2d framebugger allocation and that also have hdr problems (but that's another bug).

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
