### ISSUE TITLE
Inconsistent file naming convention between docs and editor when attaching a script to a node

### ISSUE THREAD

**Issue by d0rf3n** [godotengine/godot#39441]
**Godot version:**

3.2.1

**OS/device including version:**

Windows10

**Issue description:**

The docs (https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#file-names) says to use snake_case for files, but the editors automatic naming uses PascalCase, same as Node names.

**Steps to reproduce:**
Attach a script to any node, name is same (PascalCase) instead of snake_case.

EDIT: PascalCase not camelCase...

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1211, as feature proposals are now tracked on the Godot proposals repository.
