### ISSUE TITLE
Nodes Missing Property Animation Descriptions

### ISSUE THREAD

**Issue by lyonsja** [godotengine/godot#39445]
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Platform: Windows 10 Education N Edition
Godot Version: 3.2.1.stable.official
Device: Ryzen 5 3600
GPU Model: NVIDIA GeForce GTX 1660 SUPER

**Issue description:**
When selecting a property to animate when adding an AnimationPlayer Track for a Control Node, there are no descriptions for the properties. Expected behavior is to have some text in the Description box with information about the selected property to animate.

**Steps to reproduce:**
1. Launch Godot
2. Create a new project
3. For Renderer, select OpenGL ES 3.0
4. Click Create & Edit
5. Create a Root Node with type User Interface
6. Right click the root node and select add child node
7. Choose type Control for the child Node and click OK
8. Right click the root node and select add child node
9. Choose type AnimationPlayer for the child Node and click OK
10. With the AnimationPlayer Node selected, create a new animation with any name.
11. Select Add Track > Property Track
12. Pick the child Control Node as the Node to be animated
13. User is presented with the Select Property dialog box
14. When selecting a property to animate in this view, observe that there is no description for the property in the Description box.
15. Expected behavior is to have a description of the property that is currently selected to be animated.

Sample project is included. Begin from Step 11 when using the sample project.

These descriptions already exist in the official Godot Documentation. For example, the description for the anchor_bottom property already exists here:
https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-property-anchor-bottom

**Minimal reproduction project:**
[Godot-Test-Project.zip](https://github.com/godotengine/godot/files/4761407/Godot-Test-Project.zip)

**Comment by KoBeWi** [comment]
Seems like no node will display descriptions.
![image](https://user-images.githubusercontent.com/2223172/84328282-d6237400-ab81-11ea-872d-378f7016160e.png)

**Comment by ewesche** [comment]
can I add these?

**Comment by KoBeWi** [comment]
Sure.

**Comment by ewesche** [comment]
fixed

**Comment by akien-mga** [comment]
Fixed by #51412.
