### ISSUE TITLE
Godot is not working with HD4000/GLES3

### ISSUE THREAD

**Issue by Lechjocker** [godotengine/godot#39443]
**Godot version:**
3.2.1 stable 32 bit

**OS/device including version:**
win10, hd4000 with latest drivers "10.18.10.5129"

**Issue description:**
When i create GLES3 project, godot is often not opening project and stucking on splash screen. After trying few times with new projects and restarting computer, i opened a project succesfully. after opening that it crashed again when i tried to save my scene. i tried to open my project again and its not opened. i created new project and after trying 5-10 times, its opened again succesfully. i tryed to import assets but it didn't worked. i tried to import via file explorer and it worked. i tested my 2d sprite animation in my project and when i hit to start, its gone again and gone forever. i could not opened this project again.

but surprisingly, when i select GLES2, its working fast and flawless. but i want to use GLES3 because i will make a pc game and my device  is support opengl 4.

**Steps to reproduce:**
n/a
**Minimal reproduction project:**
n/a

EDİT: spelling errors corrected

**Comment by aaronfranke** [comment]
Intel's Windows drivers are known for being quite poor. If GLES3 support is important to you, one option is to install Linux, which [will allow you to use GLES3](https://www.phoronix.com/scan.php?page=news_item&px=MTMwMDg).

**Comment by akien-mga** [comment]
You're not actually the latest drivers though, the 10 series is fairly old.

Try this one: https://downloadcenter.intel.com/download/29473/Intel-Graphics-Driver-for-Windows-15-33-?product=81499

**Comment by Ev1lbl0w** [comment]
There's also the fact that GLES3 will be deprecated for 4.0, so if you work on GLES2 it's an easier transition if you wish to use the new version when it comes out.

**Comment by Lechjocker** [comment]
> Intel's Windows drivers are known for being quite poor. If GLES3 support is important to you, one option is to install Linux, which [will allow you to use GLES3](https://www.phoronix.com/scan.php?page=news_item&px=MTMwMDg).

thank you for advive but i will prefer to stay on win10. i'll wait for new updates

**Comment by Lechjocker** [comment]
> You're not actually the latest drivers though, the 10 series is fairly old.
> 
> Try this one: https://downloadcenter.intel.com/download/29473/Intel-Graphics-Driver-for-Windows-15-33-?product=81499

i tried to install with updater and manually but it didn't worked. its saying you're up to date. i downloaded 15.33 directly, installed but it didnt even changed my version. my cpu is also supporting but idk

**Comment by Lechjocker** [comment]
> There's also the fact that GLES3 will be deprecated for 4.0, so if you work on GLES2 it's an easier transition if you wish to use the new version when it comes out.

thank you! i started to develop with gles2. if devs can solve this. i will continue with gles3

**Comment by aaronfranke** [comment]
The Godot developers can't fix your GPU drivers.

**Comment by Calinou** [comment]
Closing, as this needs to be addressed by https://github.com/godotengine/godot-proposals/issues/1609.
