### ISSUE TITLE
GridContainer element position is incorrect

### ISSUE THREAD

**Issue by mnkylord** [godotengine/godot#39447]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**

myGridContainer.get_children()[i].get_global_transform().origin
does not return the absolute screen position. This only applies to elements added by gdscript. The ones that are manually added in scene return the correct position.

**Steps to reproduce:**
> Add a GridContainer in a scene.
> Add a few elements in GridContainer.
> In _ready() of your scene, add several more elements to GridContainer
> In _ready(), loop through all children in GridContainer and print child.get_global_transform().origin
You'd see that only the manually added children returns the correct screen position.

**Minimal reproduction project:**

**Comment by groud** [comment]
Please upload a minimal reproduction project. It's required for the issue to be solved.

**Comment by mnkylord** [comment]
[bugs.zip](https://github.com/godotengine/godot/files/4765651/bugs.zip)

**Comment by mnkylord** [comment]
Please take a look at the attached .tscn and .gd. They demonstrate my problem, I need to get the screen position of elements in a GridContainer, but I am unable to do that.

**Comment by groud** [comment]
I just checked the project, I am not sure we can so something about it. I believe, that for optimization purposes, the Controls position is updated once per frame, so you have to wait the end of the frame to get correct values. So basically, you cannot expect the Control to have a correct position just after being added as a child.

It's unlikely to be changed, as running the positioning every time you add a child would require a lot of processing for little gain.

I would suggest, eventually, to use call_deferred() to get the updated position at the end of the frame.

**Comment by mnkylord** [comment]
Thank you for the explanation! I think I can find a solution now.

**Comment by mnkylord** [comment]
Thank you so much again! call_deferred() is very helpful. My core problem is that I am dynamically building item menus, skill menus, and move the cursor in the same frame, sometimes. call_deferred() appears to be the only way to do this.
