### ISSUE TITLE
Internal Script Error

### ISSUE THREAD

**Issue by sian2005** [godotengine/godot#39452]
**Your Godot version:**
3.2 stable

**Issue description:**
I got a ```internal script error``` with ```opcode #28```, it said I needed to report it so here I am.
You can see a picture of the error here:
![Internal Script Error](https://user-images.githubusercontent.com/62208362/84351355-83ff4480-abbb-11ea-9bef-cfcac476269a.PNG)
And in the output there also is a error that the resource file ```res://``` is not found, I dont know if this has anything to do with the issue above, but I'll still let you know, so here is a picture of that:
![Resource file not found](https://user-images.githubusercontent.com/62208362/84351720-359e7580-abbc-11ea-93a4-bd1c2171c667.PNG)
There also is an Error in the Errors tab in Debugger that sais this, also, I was making a pause-game feature using https://docs.godotengine.org/en/stable/tutorials/misc/pausing_games.html
![image](https://user-images.githubusercontent.com/62208362/84352369-7c409f80-abbd-11ea-9913-112aedb504f1.png)

**Comment by dreamsComeTrue** [comment]
Can you show us the script?

**Comment by sian2005** [comment]
Looking back at this now
