### ISSUE TITLE
Setting GLES2 as the Default Driver in the Project Settings does not work

### ISSUE THREAD

**Issue by nightrobin** [godotengine/godot#39456]
**Godot version:**
4.0.dev Commit: ffbea8a

**OS/device including version:**
Android 9 - Xiaomi Redmi 4
Android 9 - Xiaomi Redmi 6

**Issue description:**
Setting GLES2 as the Default Driver in the Project Settings does not work

**Error Encountered:**

```
org.godotengine.granville E/godot: ERROR: Condition "!native_window" is true.
org.godotengine.granville E/godot:    at: DisplayServerAndroid (platform\android\display_server_android.cpp:423) - Condition "!native_window" is true.
```

Upon checking the engine's source code:

```
 if (rendering_driver == "vulkan") {
            ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
            ERR_FAIL_COND(!native_window);
```

It fails when the android device does not support vulkan

**Steps to reproduce:**
1. Open Project Settings
2. Go to Rendering > Quality
3. Select GLES in the Driver > Driver Name

**Minimal reproduction project:**
Not Needed

**Comment by Zireael07** [comment]
GLES2 support is not done in master yet.

**Comment by nightrobin** [comment]
Oh, I see. Thanks for the heads up

**Comment by akien-mga** [comment]
That's not a bug, this is under heavy development and there is no GLES2 backend right now.
