### ISSUE TITLE
Mouse motion events are sent at irregular (and wrong) intervals

### ISSUE THREAD

**Issue by njor** [godotengine/godot#39459]
**Godot version:** 3.2.1

**OS/device including version:** Ubuntu 20.04 LTS, 64 bits, Gnome 3.36.2

**Issue description:** Some InputEventMouseMotion seem to be queued / delayed, in a way that makes determining the mouse speed very error prone. It looks like events received by Godot are batched and sent on a frame-based interval (ie. every 1/60 of second).
Testcase (also included as an attachment) :

```
extends Node2D

var last_mouse_motion_t_usec = 0

func _ready():
	Input.set_use_accumulated_input(false)
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

func _input(event):
	if event is InputEventMouseMotion:
		var t_usec = OS.get_ticks_usec()
		var duration_usec = t_usec - last_mouse_motion_t_usec
		var move = event.relative.length()
		print("duration (usec): %8d, move (px): %4.1f, speed (px/sec): %8.1f, official speed: %8.1f" % [duration_usec, move, move / duration_usec * 1_000_000, event.speed.length()])

		last_mouse_motion_t_usec = t_usec
```

I get this kind of results when moving the mouse quickly over the area :
```
duration (usec):    17725, move (px): 15.3, speed (px/sec):    863.0, official speed:      0.0
duration (usec):      112, move (px): 15.3, speed (px/sec): 136580.9, official speed:      0.0
duration (usec):      148, move (px): 16.1, speed (px/sec): 108949.4, official speed:      0.0
duration (usec):       70, move (px): 15.1, speed (px/sec): 216182.1, official speed:      0.0
duration (usec):       48, move (px): 14.3, speed (px/sec): 298287.9, official speed:      0.0
duration (usec):       52, move (px): 15.3, speed (px/sec): 294174.2, official speed:      0.0
duration (usec):    15009, move (px): 14.1, speed (px/sec):    942.2, official speed:      0.0
duration (usec):      115, move (px): 13.2, speed (px/sec): 114373.4, official speed:      0.0
duration (usec):       64, move (px): 13.0, speed (px/sec): 203725.1, official speed:      0.0
duration (usec):    17454, move (px): 12.0, speed (px/sec):    689.9, official speed:      0.0
duration (usec):      139, move (px): 12.0, speed (px/sec):  86630.2, official speed:      0.0
duration (usec):       83, move (px): 11.0, speed (px/sec): 133076.6, official speed:      0.0
duration (usec):       65, move (px):  9.2, speed (px/sec): 141839.1, official speed:      0.0
duration (usec):    15570, move (px):  9.1, speed (px/sec):    581.6, official speed:      0.0
duration (usec):      106, move (px):  7.0, speed (px/sec):  66037.7, official speed:      0.0
duration (usec):       60, move (px):  6.0, speed (px/sec): 100000.0, official speed:      0.0
duration (usec):       49, move (px):  6.1, speed (px/sec): 124138.0, official speed:      0.0
duration (usec):       62, move (px):  4.0, speed (px/sec):  64516.1, official speed:      0.0
duration (usec):    16246, move (px):  3.0, speed (px/sec):    184.7, official speed:      0.0
duration (usec):      148, move (px):  3.0, speed (px/sec):  20270.3, official speed:      0.0
duration (usec):       71, move (px):  2.0, speed (px/sec):  28169.0, official speed:      0.0
duration (usec):       72, move (px):  2.0, speed (px/sec):  27777.8, official speed:      0.0
```

What happened : the events are sent at irregular intervals, making it impossible to calculate the mouse speed. Please note that I am using capture, so `event.speed` is null and cannot be used.
What was expected : the events should come regularly, so that the speed can be determined with more precision.
Alternatively, every Event object could itself have a property containing the exact timestamp it was received by the Godot engine (in microseconds). This would allow perfect precision, no matter when the script is passed the event, and even if there is some batching.

(I know it is possible to keep a few values in an array, then to make a mean over a longer time period (ie. all the events received in the last 16.6 ms), but this is a workaround, and it relies on the way the engine currently works (batching events every frame), thus, relies on an undocumented behaviour that may change later.)

**Steps to reproduce:** Move the mouse quickly over the testcase area.

**Minimal reproduction project:**

[MouseMotionTest.zip](https://github.com/godotengine/godot/files/4765101/MouseMotionTest.zip)

**Comment by Calinou** [comment]
>  It looks like events received by Godot are batched and sent on a frame-based interval (ie. every 1/60 of second).

This is done by design since Godot 3.1. You can disable this behavior by calling `Input.set_use_accumulated_input(false)`.

If events aren't accumulated, then the `_input()` method could be called very often, leading to low performance and high CPU usage.

**Comment by njor** [comment]
But I did call `Input.set_use_accumulated_input(false)` in my example (in the `_ready` function). Is there something I am doing wrong ?

**Comment by Calinou** [comment]
@njor Maybe it doesn't work when the mouse is captured. On Windows and Linux, raw input is automatically used when the mouse is set to be captured. (This is done so the OS' mouse acceleration settings don't impact the game.)

**Comment by njor** [comment]
This is actually one of the problems I am trying to solve : add some custom configurable acceleration to the mouse movement (and possibly to other similar « precision-based » inputs, like ScreenDrag, and even gyroscope and accelerometer…).
But for this acceleration to be reasonably precise and reactive, I would need to know with as much precision as possible the timestamp when each input event occurred.
So, would it be possible to include some timestamp property for all Event objects, like `ticks_usec`, that would contain the exact time the event was generated ? That would be a great help. :-)

**Comment by Calinou** [comment]
@njor This was requested already in https://github.com/godotengine/godot-proposals/issues/552.

**Comment by njor** [comment]
Thank you for the pointer. I commented on the other issue and will close this one, as it is a duplicate. :-)

**Comment by ceLoFaN** [comment]
> @njor Maybe it doesn't work when the mouse is captured. On Windows and Linux, raw input is automatically used when the mouse is set to be captured. (This is done so the OS' mouse acceleration settings don't impact the game.)

I've tested in 3.2.3 on Linux, and I'm not sure this is still the case. Even with `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)` I am still getting integer values such as `(1, 0)`, `(2, -1)` etc. I expected some floats in there, can there be something wrong about my setup? How can I check?
