### ISSUE TITLE
3.2.2 b4: Project export [Win10]: not injecting 'Application' metadata into EXE (icon, company, copyright)

### ISSUE THREAD

**Issue by dreamsComeTrue** [godotengine/godot#39458]
**Godot version:**
3.2.2 beta4 official

**OS/device including version:**
Win10

**Issue description:**
**Steps to reproduce:**
When I try to export Win10 project, none of the attributes set in 'Application' section are being injected into final executable (icon, company name, copyright etc.)

![obraz](https://user-images.githubusercontent.com/1110337/84377760-71990100-abe3-11ea-9ab8-ed4910730e59.png)

------>

![obraz](https://user-images.githubusercontent.com/1110337/84378156-fedc5580-abe3-11ea-8c5a-7ec6a6cc05cc.png)

**Comment by mrcdk** [comment]
Do you have `rcedit` downloaded and configured inside Godot? Follow the documentation https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html

**Comment by dreamsComeTrue** [comment]
Yep, that did the trick, thanks. I will close that issue, but maybe it's worth adding some sort of warning to the export window, when someone is attempting to do so like I did..?

**Comment by Calinou** [comment]
@dreamsComeTrue See #27765.
