### ISSUE TITLE
Inherited scene saving parent nodes in incorrect order

### ISSUE THREAD

**Issue by bojjenclon** [godotengine/godot#3945]
I created a basic "template" level scene with the following node hierarchy:
```
Level
  -> Player
    -> Shapes
```

I then created a new scene that inherits from this template scene. When I add a new Shape to the Player/Shapes node, it appears to be added correctly in the editor. However, if I try to run the scene it throws an error (without any text) in the debugger and doesn't display the shape. Upon inspecting the tscn file, I noticed the shape's parent is set as "Shapes/Player" when it should be "Player/Shapes."

Also, if I save the scene, close it, and reopen it, the shape is gone from the scene (likely due to it not knowing where to place it).

This exact same setup works perfectly fine in an identical scene I set up that doesn't use an inherited template scene as its base.

**Comment by DriNeo** [comment]
I found an error without text on a inherited scene too.

![inhsceneerr](https://cloud.githubusercontent.com/assets/12350741/13567637/a8f5c60e-e45c-11e5-9297-3520085893d9.png)

**Comment by bojjenclon** [comment]
I went back and looked at it again, and I realized I had the base scene saved as a .tscn with the child scene saved as a .scn. That could potentially have been part of the issue. However, I feel this shows that there really needs to be a "default scene format" option so users don't have to always remember to add the "t" when saving their scenes.

**Comment by reduz** [comment]
this was fixed recently
