### ISSUE TITLE
3D orbit inertia is broken, which makes rotation in the editor jittery again

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#39467]
Godot 3.2.2 rc1
Godot 3.2.2 beta4
Godot 3.2.2 beta1

For a little while, I feel orbit/rotation inertia doesn't work. When I rotate around with the viewport camera, it feels like there is no inertia at all.
I tried to increase it, which had no effect... and I noticed that instead, if I give a quick stroke with my mouse holding MMB, rotation continues for a bit, before stopping. It's really weird.

In comparison, translation inertia seems to work fine.
Rotation inertia worked fine in Godot 3.2.1.

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/a609b30ddb77bcc1c64008a7848da07b5448a10d (but it works fine on 3.2.2 and 3.2.1).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/52378, which is more detailed.
