### ISSUE TITLE
Networking UDP + DTLS not working on Godot Engine v3.2.2.beta4.official

### ISSUE THREAD

**Issue by extremety1989** [godotengine/godot#39461]
windows 10 64
Godot Engine v3.2.2.beta4.official

I used code (server,client) from https://godotengine.org/article/enet-dtls-encryption only changed extends Node to SceneTree
and  from Self-Signed Certiicate Generator(it is an online website) to generate certs.
When i execute godot.exe c:\godot\Server.gd 

the print does not executes

```gdscript
func _ready():
	server.listen(4242)
	print("listen to 4242")
	var key = load("./CERTS/cert.key") # Your private key.
	var cert = load("./CERTS/cert.crt") # Your X509 certificate.
	dtls.setup(key, cert)
```

**Comment by Faless** [comment]
> only changed extends Node to SceneTree

You can't expect that to just work, `_ready` is only called on `Node`s and its subclasses, not on `SceneTree`.

> godot.exe c:\godot\Server.gd

That's not how you execute a script:
https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html

**Comment by extremety1989** [comment]
@Faless when i use Node it outps error

ERROR: Can't load the script "C:\Users\andre\godot\Server.gd" as it doesn't inherit from SceneTree or MainLoop.

**Comment by akien-mga** [comment]
If you want to run only a script and not a project with a pre-defined scene tree, you'll have to build the scene tree yourself in the script.

Instantiate a node, assign it the above script, etc. That's not related to networking per se and outside the scope of this bug tracker, ask on other community platforms for support on how to run complex scripts from the command line (but that's a fairly advanced use case, I would advise that you stick to make a proper server project with a scene (Node-based)).

**Comment by extremety1989** [comment]
@Faless thank you, i have fixed it with _init()  instead of _ready()
