### ISSUE TITLE
There is currently no way of identifying a node after it has been position locked.

### ISSUE THREAD

**Issue by securas** [godotengine/godot#39472]
**Godot version:**
3.2.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
On a heavily populated scene with many locked nodes, it becomes difficult/cumbersome to identify nodes in the editor. Although such nodes should not be selectable, a mouse-over name identification would be very useful.

**Comment by Calinou** [comment]
Please open proposals on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository, as this repository is meant to be used for bug reports only.
