### ISSUE TITLE
Trimesh Static bodies generated incorrectly

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#3947]
**Operating system or device:**
Windows 7

**Issue description** (what happened, and what was expected):
The [Create Trimesh Static Body] menu option produces incorrect collision meshes. The dae import has the most significant errors. Some of the dae shapes are visually wrong, and are offset from the actuall mesh. The obj import looks like rounding errors.

Obj import trimesh collision

**Steps to reproduce:**
_Files are in the zip._
**DAE:**
- Import and open mesh
- Click the [Create Trimesh Static Body] button on all  mesh nodes
- Add camera and point it at the pole with the sphere on top

Bugs:
- All collisions objects are on an offset. 
- The sphere shape is square shape

DAE Images
- http://imgur.com/0bFwyBU
- http://imgur.com/tixoYyL

**OBJ**
- Click the menu option Import > 3d Mesh
- Select the obj
- Select normals, unselect weld vertices.
- Look at back left or right corner. 

Bugs:
- The ground collision mesh does not extend to exactly the back edges

Obj images:
- http://imgur.com/kqkW5e0
- http://imgur.com/U1typag

I don't know if the bugs would accumulate the bigger the level is.

**Link to minimal example project** (optional but very welcome):
_**Turn on visible collision shapes. Run the project for easier comparison**_
[trimesh collision bug.zip](https://github.com/godotengine/godot/files/160200/trimesh.collision.bug.zip)

**Comment by DriNeo** [comment]
I hope this issue is the main cause of this:  #3845

**Comment by capnm** [comment]
This is fixed in the current Godot 3 tip:

![bildschirmfoto](https://user-images.githubusercontent.com/4047289/32549252-06528842-c489-11e7-8d67-b9b2c4604ff8.png)

**Comment by akien-mga** [comment]
Thanks for testing, closing.
