### ISSUE TITLE
gtlf export have incorrect cloth skin

### ISSUE THREAD

**Issue by wijat** [godotengine/godot#39476]
**Godot version:**
Godot 3.2.1 stable.official
Blender v2.83.0

**OS/device including version:**
Win10 x64

**Issue description:**
I export the character and her additional cloth, and it just has incorrect skin.
In Blender, the skin weight is like this:
![screenshot_2020_06_12——1](https://user-images.githubusercontent.com/8220843/84486064-71762f80-accf-11ea-9179-c10d55b2abbb.png)

In Godot, it just become this:  (The cloth is broken!)
![screenshot_2020_06_12](https://user-images.githubusercontent.com/8220843/84486132-881c8680-accf-11ea-8a88-fafda63ffdb1.png)

**Steps to reproduce:**
1.Open blender file
2.select the armature and its children to export as gltf2.0 as this option:
![option](https://user-images.githubusercontent.com/8220843/84485915-3a078300-accf-11ea-9bde-60d743f461ba.png)

3. Then go to Godot to import this glb  file.
4. You found this walk animation is not correct as it in Blender.

**Minimal reproduction project:**
Blender file:
[FemaleCloth_10001.zip](https://github.com/godotengine/godot/files/4769817/FemaleCloth_10001.zip)

**Comment by fire** [comment]
I noticed that you are using an internal animation rig, please bake it out.

That's all I can think of.

**Comment by wijat** [comment]
> 
> 
> I noticed that you are using an internal animation rig, please bake it out.
> 
> That's all I can think of.

I try to bake the action, it just fill the key frame, it can let the animation work well, but here is my problem: The cloth skin is incorrect, that is not same as blender, every time I edit the mesh in Blender, it just can not show in Godot right.

**Comment by wijat** [comment]
I can see it in the blender file
![screenshot_2020_06_13](https://user-images.githubusercontent.com/8220843/84562635-7f3bbb80-ad88-11ea-9538-c6dfc551f0d1.png)
![screenshot_2020_06_131](https://user-images.githubusercontent.com/8220843/84562638-84990600-ad88-11ea-8e7d-c95f29a4b685.png)

**Comment by wijat** [comment]
And if this issue can not fix, anyone has anyways to avoid this issue can let me keep creating my character wear and change clothes feature?

**Comment by wijat** [comment]
> 
> 
> I noticed that you are using an internal animation rig, please bake it out.
> 
> That's all I can think of.

By the way, the body mesh have shape key. I doubt it may effect.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/87345285-b8d92100-c504-11ea-9eb1-dda9c8c5e6cd.png)

Something goes wrong when I import the model from blender into ms 3d viewer. Can you check that point?

**Comment by fire** [comment]
When I tried exporting, I saw. 
[FemaleCloth_10001.zip](https://github.com/godotengine/godot/files/4914679/FemaleCloth_10001.zip)

![image](https://user-images.githubusercontent.com/32321/87345705-4ae12980-c505-11ea-8acf-b99119527318.png)

**Comment by wijat** [comment]
Are you sure your blender version is right?
![图片](https://user-images.githubusercontent.com/8220843/87781718-ccb5b780-c863-11ea-9114-01e342524c91.png)

**Comment by wijat** [comment]
I open your glb file in blender, the skeletal is right as expect.

**Comment by wijat** [comment]
But it just wrong like shit in Godot...All skeletal just incorrect!

**Comment by wijat** [comment]
I tired import this glb in Godot, it just have incorrect skeletal transform........

**Comment by wijat** [comment]
![图片](https://user-images.githubusercontent.com/8220843/87782612-70539780-c865-11ea-879c-38c9c947acfd.png)

**Comment by wijat** [comment]
At least the skin is right.....

**Comment by wijat** [comment]
By the way, Blender is the Best glb viewer, not ms 3D viewer.

**Comment by Calinou** [comment]
@wijat Please use the **Edit** button (hidden behind the **...** icon) to edit your posts instead of multi-posting. I merged your posts manually.

**Comment by fire** [comment]
Used blender 2.9 and a Godot Engine branch git branch on 3.2.

I don't see any problems now.




![GIF 2020-10-18 8-54-39 AM](https://user-images.githubusercontent.com/32321/96373196-c0215380-111f-11eb-90a6-e31f6af45808.gif)

**Comment by fire** [comment]
The incorrect skin seems to work in Blender 2.9+. Will close.
