### ISSUE TITLE
Audiostream / OGG freezes player and editor

### ISSUE THREAD

**Issue by solorvox** [godotengine/godot#39477]
**OS/device including version:**
Godot Engine v3.2.1.stable.official
Linux Mint 19.3, Kernel 5.3.0-53-generic, Cinnamon desktop, pulseaudio 1:11.1-1ubuntu7.8

**Issue description:**
When trying to play the project/scene, there is no sound and everything stops responding to input.  No errors on console (if running editor from command line) and the editor can no longer be shutdown.

**Steps to reproduce:**
Open project, press play.  Note that window cannot be closed and editor does not shut down after selecting quit.

**Minimal reproduction project:** [OGG-BUG.zip](https://github.com/godotengine/godot/files/4770010/OGG-BUG.zip)

**Comment by akien-mga** [comment]
Confirmed in 3.2.1, this has been fixed by #35912 in `master` and `3.2` (fix included in 3.2.2).
