### ISSUE TITLE
HTML5 Export - 1 frame black screen after load.

### ISSUE THREAD

**Issue by LuchitoDev** [godotengine/godot#39471]
**Godot version:**
Godot 3.2.1-stable and Godot 3.2.2-rc1

**OS/device including version:**
Html5 (GLES2) - MacOS Catalina

**Issue description:**
Hello everyone, I am trying to export a test game to Facebook Instant Games using HTML5. But I have some problems, when the engine starts always, using or not a custom html template for export, game display a black screen before render my main scene. I am not talking about the screen where default exportation render a spinner or progressbar. I have a custom loading scene waiting until next scene is loaded, but always is the same thing. And I many warning, fullscreen and this [.WebGL-0x7f887095f800]RENDER WARNING: there is no texture bound to the unit 78.. I hope somebody can help me and if you can add support for export to other platform like FB and an alternative for show loading screen while next scene is loading all resources, example... preoloadScene(scene) method would be nice regards...

![Grabacion-de-pantalla-2020-06-11](https://user-images.githubusercontent.com/19392344/84447871-7622e100-ac06-11ea-9dca-cafa964f12b7.gif)

**Comment by Calinou** [comment]
Did you enable low-processor usage mode? It's known to be broken in HTML5, especially in Firefox.

**Comment by LuchitoDev** [comment]
@Calinou thanks for your answer, I activeted low-processor like you suggest, but nothing change. I still have the issues...
