### ISSUE TITLE
Android doesn't read 'res://' directory but can read 'user://'

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#39474]
**Godot version:**
Godot 3.2.2beta4

**OS/device including version:**
Android 10 / Samsung Note 9

**Issue description:**
Listing files in directory doesn't work on android.  Same code lists files as expected on Windows.

**Steps to reproduce:**

```gdscript
var dir = Directory.new()
print(dir.dir_exists('res://BrushTextures/')) 
returns false on Android, returns True on windows

func dir_contents('res://BrushTextures/'):
	var dir = Directory.new()
	if dir.open(path) == OK:
		dir.list_dir_begin()
		var file_name = dir.get_next()
		while file_name != "":
			if dir.current_is_dir():
				print("Found directory: " + file_name)
			else:
				print("Found file: " + file_name)
			file_name = dir.get_next()
	else:
		print("An error occurred when trying to access the path.")
```
on Android prints("An error occurred when trying to access the path.")
on Windows prints a list of the files in the dir.

Accessing a specific file in this directory, for eg 'res://BrushTextures/Capturemasayasu.JPG'
works fine on Android and Windows.

**Minimal reproduction project:**

**Comment by HEAVYPOLY** [comment]
Did some more digging.
Android reads 'user://' directory properly
for some reason, when reading 'res://', Android finds [_cl_, images, webkit]
Very confused because Android is able to load textures from the res:// directory fine with exact paths, but can't seem to see the directory contents with dir_contents()

**Comment by Anutrix** [comment]
Put the code between ``` so that it stays formatted and readable.

**Comment by bruvzg** [comment]
> Android reads 'user://' directory properly
But, when reading 'res://', Android finds [cl, images, webkit]

`user://` is normal filesystem, `res://` contents of `assets` folder inside the APK. Issue should be somewhere in: [`dir_access_jandroid.cpp`](https://github.com/godotengine/godot/blob/master/platform/android/dir_access_jandroid.cpp), for loading files from the APK there are two versions for some reason: [`file_access_android.cpp`](https://github.com/godotengine/godot/blob/master/platform/android/file_access_android.cpp) and [`file_access_jandroid.cpp`](https://github.com/godotengine/godot/blob/master/platform/android/file_access_jandroid.cpp).

**Comment by bruvzg** [comment]
Unrelated note: something like `res://BrushTextures/Capturemasayasu.JPG` won't work on any platform after exporting. Texture files are converted and stored inside `.import` subfolder as `.stex` files, originals aren't packed, there will be only `res://BrushTextures/Capturemasayasu.JPG.import` with the link to `.stex`. Loading file with `load` or `preload` function by its original name will work but opening it directly won't.

**Comment by HEAVYPOLY** [comment]
Thanks for the help, would this work?
I'm working on a painting program and want to assign textures to strokes, but figure it would be too expensive to save the texture itself, so I'm saving path to the texture into the stroke so it knows which texture to load before drawing.

```
func list_files_in_directory(path, filter):
	print('List files')
	var files = []
	var dir = Directory.new()
	dir.open(path)
	dir.list_dir_begin()

	while true:
		var file = dir.get_next()
		if file == "":
			break
#		if file.ends_with(filter):
		files.append(file)
		var f = File.new()
	dir.list_dir_end()
	print('FILES LIST ', files)
	return files

func initialize_grid():
	brush_texture_paths = list_files_in_directory(brush_directory, filter)

	N.ViewportInfo.text = str(brush_texture_paths)
	for brush_texture in brush_texture_paths:
		var brush_texture_path = brush_directory+brush_texture
		print(brush_texture_path)
		var icon_bg = ColorRect.new()
		icon_bg.name = brush_texture
		icon_bg.size_flags_vertical = SIZE_EXPAND_FILL
		icon_bg.size_flags_horizontal = SIZE_EXPAND_FILL
		icon_bg.color = Color(.15,.15,.15,1)
		var icon_size = Vector2(rect_size.x / columns, rect_size.x/columns)
		icon_bg.rect_size = icon_size
		var icon = TextureRect.new()
		icon.texture = load(brush_texture_path)```

**Comment by Calinou** [comment]
This is a known issue: listing directories within `res://` on Android isn't feasible. You need to generate a file that contains the list of files within the directory and make sure it's exported so you can read it later.

**Comment by HEAVYPOLY** [comment]
Good to know, thanks @Calinou and @bruvzg

**Comment by o01eg** [comment]
It possible to list directories on Android if use android.content.res.AssetManager.list with JNI instead of AAssetManager_openDir

**Comment by HEAVYPOLY** [comment]
@o01eg interested in this solution, is this something done in GDscript or changing engine code?

**Comment by o01eg** [comment]
I did it in GDNative extension: 

https://github.com/freeorion/freeorion/blob/c266a40eccd3a99a17de8fe57c36ef6ba3771665/util/Directories.cpp#L809-L861

**Comment by HEAVYPOLY** [comment]
Thanks, I ended up using method suggested in discord to create a JSON list of the files with the editor, and reference that in the Android build.

**Comment by wajrou** [comment]
It works since Godot 3.5.

**Comment by akien-mga** [comment]
Thanks, this should indeed be fixed by the full Android scoped storage support.

**Comment by Atlinx** [comment]
@wajrou how did you get directory file listing to work? I can't seem to get listing file directories to work on my game. If I open the `res://` directory, I get `.import` when I use `directory.get_next()` and `directory.get_current_dir()`. There is no file or directory names -- there's only `.import`.

**Comment by bubu07codes** [comment]
Same problem here i cant read res:// folder on android export, but on windows yes...
