### ISSUE TITLE
Tilemap tiles are removed randomly

### ISSUE THREAD

**Issue by securas** [godotengine/godot#39473]
**Godot version:**
3.2.1 stable

**OS/device including version:**
Windows 10

**Issue description:**
On reasonably populated tilemaps, tiles are sometimes deleted at random with the cell values set to -1. 

**Steps to reproduce:**
Unfortunately, I was unable to systematically reproduce this issue due to its randomly occuring behavior.

**Comment by groud** [comment]
Sorry, but without any more information or a minimal reproduction project, it is impossible to solve the issue.

**Comment by securas** [comment]
No problem. I just wanted to report it here so other users that encounter the same issue can report it as well. If I manage to find a way to reproduce the problem I'll report back.

**Comment by Calinou** [comment]
@securas Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by securas** [comment]
> @securas Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?
> 
> If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

Hi @Calinou . I have not seen this so far in 3.5.1 but I admit that I've stopped using the Godot tilemap system instead using a "custom" resource to store tile data and avoid loosing it.

**Comment by Calinou** [comment]
Closing for now. Please comment if you can still reproduce this on the latest Godot version.
