### ISSUE TITLE
_process not called on Node when Node is orphan.

### ISSUE THREAD

**Issue by AllenKll** [godotengine/godot#39489]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10, GPU: potato

**Issue description:**
I created a new class that inherited from `Node`.  added the `_process(delta)` function.  Instantiated the class using `new()`.  `_process` was never called.

For debugging purposes, I added the instantiation to the SceneTree, and `_process` began to be called.  Unsure if this is a documentation bug or a code bug.  The docs don't indicate that a Node must be part of a tree for _process to be called.  

**Steps to reproduce:**
Create a script with class that inherits from `Node`, add `_process` function.  Instantiate the class, observe that _process is never called

**Minimal reproduction project:**
[processBug.zip](https://github.com/godotengine/godot/files/4773312/processBug.zip)

**Comment by Calinou** [comment]
I think this is done by design. I suppose we should make it more obvious in the Node class documentation.
