### ISSUE TITLE
Changing CollionsShape3D.shape.radius will paused disconnect signals 

### ISSUE THREAD

**Issue by octopus-io** [godotengine/godot#39480]
**Godot version:**
- 3.2.1
- 3.2-beta6

**OS/device including version:**
- Linux/Debian10
- GLES3

**Issue description:**
I have a scene with an area2D/CollisionShape2D. Area2D  send signals "mouse_entered" and "mouse_exited" to a script on Node2D node.
When mouse enter the Area2D i enlarge the shape radius of CollisionShape2D and reduce the size when mouse exit.

When the tree is not paused, it's work as expected. when mouse enter the CollisionShape2D grow up and when mouse exit it goes to normal size.

But is I set the  pause (get_tree().paused = true), when mouse enter the script receive 'mouse_entered' signal folow by 'mouse_exited' right after. And after once trigger 
there is not more signal send to the script.

**Minimal reproduction project:**
Here a minimal project reproducing the bug.
In the script change the value of variable generatebug to reproduce the bug.
[shapeBug.zip](https://github.com/godotengine/godot/files/4771141/shapeBug.zip)

**Comment by Ev1lbl0w** [comment]
From documentation:

> If true, the SceneTree is paused. Doing so will have the following behavior:
>
> - 2D and 3D physics will be stopped.
>
> - Node._process(), Node._physics_process() and Node._input() will not be called anymore in nodes.

I don't know if this is an issue, because it seems you're using this in the wrong way. Even if you unpause `Area2D`, the physics engine is paused, so it makes those weird behaviours.

**Comment by Anutrix** [comment]
Continuing the quoted part from the docs:
> This effectively stops the whole game. Calling this function from a script, by default, will result in an unrecoverable state (nothing will work anymore!).

Maybe this is what's happening.

**Comment by octopus-io** [comment]
yes maybe in don't understand well how paused must work but it seems to me that the behavior isn't consistent. I my example if i don't change the shape, events (mouse enter/exit) work fine, regardless of the paused_mode of the node. It is when my code change the radius of the shape  of CollisionShape2D while the game is paused that the bug appears.

I will continue to investigate, it seem that i have added "get_node('/root').pause_mode = PAUSE_MODE_PROCESS" and this can be part of the problem.

**Comment by ShraddhaDevaiya** [comment]
Hello @octopus-io , @Anutrix is right. You have set get_tree().paused , but to continue the game you should set false to get_tree().paused method. You have used it incorrectly. You can check the documentation to follow pause behavior better : https://docs.godotengine.org/en/stable/tutorials/misc/pausing_games.html. Because changing a radius of shape didn't affect the behavior in my case.

**Comment by octopus-io** [comment]
Hi, after some test and research, i finally understand pause system.
I think all my problems came from  "get_node('/root').pause_mode = PAUSE_MODE_PROCESS".
During my test i also found an other bug but already referenced as #37870.

I think we can close this issues.
Thx, all.
