### ISSUE TITLE
Node and MenuButton _unhandled_key_input function signature inconsistency

### ISSUE THREAD

**Issue by pcting** [godotengine/godot#39497]
**Godot version:**

 3.2.2.rc.custom_build.6c9b7c27d

**OS/device including version:**

 Any

**Issue description:**

I encountered a function signature inconsistency when working with `godot-headers` and writing some codegen against the `api.json`. here are the methods of interest:
```
Node._unhandled_input(InputEvent);
Node._unhandled_key_input(InputEventKey);
```

```
MenuButton._unhandled_key_input(InputEvent);
```
I found this after encountering a function overloading error developing my golang nativescript bindings. [Node](https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L2905)'s `_unhandled_key_input` accepts a `InputEventKey` type, but the [MenuButton](https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/scene/gui/menu_button.h#L45)'s version accepts an `InputEvent`. Was this intended? should the MenuButton version be renamed to `_unhandled_input` ?

The workaround is easy enough; use a different function name during code gen.
**Steps to reproduce:**
N/A

**Minimal reproduction project:**

N/A

Here's a short set of [discord messages](https://discord.com/channels/212250894228652034/342047011778068481/721066977942044792) discussing this issue

**Comment by akien-mga** [comment]
Yes the Menu button override should be fixed.

**Comment by Sauermann** [comment]
This issue can be closed, because the signature of the function in `Node` is now consistent with `MenuButton`:
``` C++
virtual void unhandled_key_input(const Ref<InputEvent> &p_key_event);
virtual void unhandled_key_input(const Ref<InputEvent> &p_event) override;
```
