### ISSUE TITLE
Can't create collision sibling on an instanced scene with Editable Children enabled

### ISSUE THREAD

**Issue by RobertBColton** [godotengine/godot#39494]
In my project, I have a node in my scene that is an instance of an automatic scene generated from an imported GLB that contains animations. I have the context menu option "Editable Children" enabled on this node so that I am able to select its AnimationPlayer for my AnimationTree state machine. In order to add collision detection to this node, I wanted to "Create Single Convex Collision Sibling" for its child mesh node.

![Collision Shape Sibling](https://user-images.githubusercontent.com/3212801/84557888-c7ad9780-acfc-11ea-883e-5d3733f6a827.png)

However, because the scene is automatic, I am not able to begin editing this generated collision shape in any way, without actually instantiating the scene. Ideally I want to move it out of this part of the subtree and place it where my other collision shape node is, so that it can be used for the kinematic body. Any attempts to move or reparent the node result in an error message. It's not even possible to delete the node without hitting undo because of this!

![Operate on Foreign Scene](https://user-images.githubusercontent.com/3212801/84557946-207d3000-acfd-11ea-97b9-3e2da787de74.png)

**Comment by Ev1lbl0w** [comment]
Did you save the imported model to a scene? Godot cannot edit the exported files directly AFAIK, so you need to save first before being able to make any changes.

**Comment by RobertBColton** [comment]
That much is understandable, and I was already aware of. However, is the creation of "Create Single Convex Collision Sibling" not an actual bug? Why is that option from the view able to modify the node, while other options from the context menu are not? Is it not confusing to the user for it to be allowed, and then not be able to reverse it unless it's still in the undo stack?

**Comment by deusinfelix** [comment]
Just my 2nd day playing with Godot and right away having similar issues with the generated Collision Shapes being grayed-out for the imported glb assets. Saving the scene and then "Scene --> Reload Saved Scene" enables the Collision Shape node and it can then be properly edited, reparented or deleted.

To me it seems like a bug with the newly generated Collision Shape inheriting some non-editable property from the source sibling, which only gets cleared when the scene is being reloaded.

**Comment by AgentSmith0** [comment]
Can confirm, in Godot 3.4 this issue is more critical, since the created CollisionShape will be vanished after reloading the scene.

**Comment by AgentSmith0** [comment]
Also present in Godot 4.
