### ISSUE TITLE
indirect call to null error on Firefox when denied cookies/storage permission

### ISSUE THREAD

**Issue by LRFLEW** [godotengine/godot#39495]
**Godot version:** v3.2.1.stable.official (and an older version the linked builds use, but I can't remember exactly which version number)

**OS/device including version:** Firefox 77.0.1 (tested on Windows 10 and macOS)

**Issue description:**
When running the game through Firefox with the domain blacklisted from cookies / local storage, an indirect call to null error occurs when starting the game. The game I made where I encountered this with has a call to `OS.is_userfs_persistent()` guarding the calls to `File.open()`, so it it shouldn't be a crash due to file IO directly. In fact, I commented out all the references to `File` (and `OS`) and it still has the error. I also tried it in Chrome, and the error doesn't occur there.

**Steps to reproduce:**
I have my game hosted on my own domain, which is probably the easiest way to see the error. (Note that it isn't built with `-s ASSERTIONS=1`, so it doesn't specify the error type.)
https://lrflew.com/ShootTheBird.html

Reproducing the issue requires blocking cookies / local storage for the domain (lrflew.com for my hosting and localhost:8060 for local testing). Steps for doing this in Chrome and Firefox are as follow (in case you need it):
Chrome: Settings (chrome://settings) -> Privacy and security -> Site Settings -> Cookies and site data -> Block -> Add
Firefox: Options (about:preferences) -> Privacy and Security -> Cookies and Site Data -> Manage Permissions

**Expected (Chrome)**

With Permissions:
![ChromeGood](https://user-images.githubusercontent.com/607715/84558791-f1fe5580-acfa-11ea-8e7c-4df96a117dcd.png)

Without Permissions:
![ChromeBad](https://user-images.githubusercontent.com/607715/84558797-faef2700-acfa-11ea-95a6-785e1ae71b68.png)

**Actual (Firefox)**

With Permissions:
![FirefoxGood](https://user-images.githubusercontent.com/607715/84558800-0cd0ca00-acfb-11ea-809a-de7199c9bfd2.png)

Without Permissions:
![FirefoxBad](https://user-images.githubusercontent.com/607715/84558801-122e1480-acfb-11ea-8d38-4074dbe59ec2.png)
![FirefoxLog](https://user-images.githubusercontent.com/607715/84558802-13f7d800-acfb-11ea-8809-0a8534f6cbbb.png)

**Minimal reproduction project:**
You can download the source ZIP from the itch.io page from the game jam I made it for. https://lrflew.itch.io/shoot-the-bird (You can also play the HTML version on there, but the CDN system itch.io uses makes it harder to reliably block/allow cookies). This is the same source ZIP uploaded here as well:
[ShootTheBird-Source.zip](https://github.com/godotengine/godot/files/4773923/ShootTheBird-Source.zip)

**Comment by akien-mga** [comment]
Fixed by #39538 

@Faless You didn't list this issue in the corresponding PR for `master`, was this bug already fixed/not relevant there?

**Comment by Faless** [comment]
@akien-mga was already fixed there, we were already using the 2-phase init, and the OS object was created before the call to setup IDBFS (since the DisplayServerJavascript implementation #38587)
