### ISSUE TITLE
3.2.2rc1 collision crash.

### ISSUE THREAD

**Issue by g2ffi** [godotengine/godot#39500]
**Godot version:**
only occurs on the 3.2.2rc1, doesn't on the 3.2.2beta4

**OS/device including version:**
GLES3
tested on Linux and Windows present on both

**Issue description:**
Collision and turning off collision bit crashes godot. 

**Steps to reproduce:**
Walk on the enemies on the project provided.
[collisionbug.zip](https://github.com/godotengine/godot/files/4774319/collisionbug.zip)

**Comment by akien-mga** [comment]
@madmiraal Probably the same issue as #39487 (but this one has a test project).

**Comment by avencherus** [comment]
@akien-mga Should be, my build with the commit reverted doesn't have any problems with this project, but the other build with the commit will crash when walk back and forth on the last objects.
