### ISSUE TITLE
Make Subresources Unique on BlendSpace2D in StateMachine crashes godot

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#39510]
**Godot version:**

3.2.1.stable.custom_build.f0a489cf4

**OS/device including version:**

Linux 5.6.15-arch1-1

**Issue description:**

I copy/pasted a state from one StateMachine to another, then tried to make the pasted state unique.
This crashed Godot

**Steps to reproduce:**

1. Select a BlendSpace2D state from a StateMachine in an AnimationTree
2. Select "Copy Resource"
3. Select a StateMachine in another AnimationTree
4. Right Click
5. Paste
6. Select the pasted state
7. Select "Make Subresources Unique"

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/4774854/example.zip)
Copy the state from Spatial.tscn to Spatial2.tscn, then try to make it unique.

**Comment by qarmin** [comment]
Closing in favour of #40974, since both issues have same root, but in second issue is detailed backtrace.
