### ISSUE TITLE
Constant editor redrawing on empty Vulkan project due to low-processor mode not being reimplemented yet

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39511]
**Godot version:**

58034f3

**OS/device including version:**

Windows 10 x64 GTX 1060

**Steps to reproduce:**
1. Create new project
2. Enable "Show Update Spinner" in Editor Settings
3. Observe the spinner spinning like crazy, both in 2D and 3D
4. CPU/GPU usage is rather high too, even if the editor is unfocused

**Comment by Calinou** [comment]
Low-processor usage mode hasn't been reimplemented yet in `master`.

**Comment by KoBeWi** [comment]
Sooo this was not about low-processor mode. The issue was fixed by #45956
