### ISSUE TITLE
HiDPI GUI theme looks non HiDPI in-editor

### ISSUE THREAD

**Issue by alvaromunoz** [godotengine/godot#39527]
**Godot version:**
3.2.2.rc1

**OS/device including version:**
macOS Catalina GLES2

**Issue description:**
I'm building a GUI in my game, and when turning the HiDPI option ON, the in-editor GUI doesn't change, only the in-game GUI changes. I expect the in-Editor GUI to change scale too.

In-Editor GUI (panel uses almost half the screen):
<img width="371" alt="image" src="https://user-images.githubusercontent.com/2722773/84582836-394e1a00-adbf-11ea-8fd0-a0627b6e1395.png">

In-game GUI (panel uses a quarter of screen):
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/2722773/84582842-5387f800-adbf-11ea-9e64-9947a157baa6.png">

**Steps to reproduce:**
Build a GUI, set HiDPI option ON. The in-editor GUI doesn't change, but the in-game GUI does.

**Minimal reproduction project:**
[GUI DPI.zip](https://github.com/godotengine/godot/files/4775749/GUI.DPI.zip)

**Comment by Calinou** [comment]
The "Enable Hidpi" option hasn't been recommended for a while. Try following the advice in [Multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) instead (use the `2d` stretch mode and `expand` stretch aspect).

**Comment by Calinou** [comment]
Closing per https://github.com/godotengine/godot/issues/39527#issuecomment-643762583. The hiDPI *theme* option will be removed in 4.0 as the new default project theme will use more vector-based elements.
