### ISSUE TITLE
PopupMenu hides itself, when click outside of game-window occurs.

### ISSUE THREAD

**Issue by marCOmics** [godotengine/godot#39536]
**Godot version:**
v.3.2.1-stable

**OS/device including version:**
* Linux Mint, Extract from system Info:
> System:    Host: JARVIS Kernel: 4.15.0-54-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
>            Desktop: Xfce 4.14.1 tk: Gtk 3.22.30 wm: Compiz dm: LightDM 
>            Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
> Machine:   Type: Laptop System: ASUSTeK product: VivoBook 15_ASUS Laptop X507MA_R507MA v: 1.0 
>            serial: <filter> 
>            Mobo: ASUSTeK model: X507MA v: 1.0 serial: <filter> UEFI: American Megatrends 
>            v: X507MA.304 date: 05/28/2019 
> Battery:   ID-1: BAT0 charge: 8.0 Wh condition: 28.8/33.3 Wh (87%) volts: 11.1/11.1 
>            model: ASUSTeK ASUS Battery serial: <filter> status: Discharging 
> CPU:       Topology: Quad Core model: Intel Pentium Silver N5000 bits: 64 type: MCP 
>            arch: Goldmont Plus rev: 1 L2 cache: 4096 KiB 
>            flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 8755 
>            Speed: 2587 MHz min/max: 800/2700 MHz Core speeds (MHz): 1: 2587 2: 2587 3: 2587 
>            4: 2587 
> Graphics:  Device-1: Intel vendor: ASUSTeK driver: i915 v: kernel bus ID: 00:02.0 
>            chip ID: 8086:3184 
>            Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
>            compositor: compiz resolution: 1920x1080~60Hz 
>            OpenGL: renderer: Mesa DRI Intel UHD Graphics 605 (Geminilake) v: 4.5 Mesa 19.2.8 
>            compat-v: 3.0 direct render: Yes 
* Backend: GLES3

**Issue description:**
The Popup Menu hides itself if you click outside the game window (no fullscreen).
Expected: Clicking outside the game windows does not affect the Popup Menu (which is a pause menu in my case) in any way.

**Steps to reproduce:**
* Have a Popup Menu node that `show()`s when `ready()`
* (Add child nodes that hide the Popupmenu rect, so that clicks on the popup menu don't hide it)
* I purposely deactivated all the "Hide on" options in the inspector, just to be sure
* Start Game, click outside the window and return to find the popup hidden

**Minimal reproduction project:**
[Bug_PopupHiddenWhenWindowLoosesFocus.zip](https://github.com/godotengine/godot/files/4776601/Bug_PopupHiddenWhenWindowLoosesFocus.zip)

**Comment by Calinou** [comment]
The current behavior seems to be intended. Dropdown menus should be closed when you click anywhere outside them, even if it's outside the window.

> Expected: Clicking outside the game windows does not affect the Popup Menu (which is a pause menu in my case) in any way.

I wouldn't use a PopupMenu for a pause menu. It's intended to be used for dropdown menus that disappear when you click outside of them.

**Comment by marCOmics** [comment]
Oh okay, allright, then thanks for the quick response!
