### ISSUE TITLE
2.0-stable cannot unpin animation player

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot#3953]
**Operating system or device:**
x11 debian

**Issue description** (what happened, and what was expected):
2.0-stable cannot unpin animation player : pin/unpin button does not work

**Steps to reproduce:**
open animation player and it stays there even if you click pin unpin button on top right corner.

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
I guess this button should no longer be there after the introduction of the bottom panel.

**Comment by vsrinu26f** [comment]
Oh, got it. I need to click Animation in bottom panel.

**Comment by neikeq** [comment]
It looks like the actual function of this button is to pin the AnimationPlayer being editor (can't edit other AnimationPlayers while pin is pressed), not to keep the Animation Editor visible.

**Comment by vsrinu26f** [comment]
good to know. thats helpful to be able to pin an instance.
