### ISSUE TITLE
a way to open all gd scripts in a project at once

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot#3954]
**Operating system or device:**

**Issue description** (what happened, and what was expected):
To learn a downloaded project, I need to traverse several directories to find gd scripts.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by vsrinu26f** [comment]
I have a workaround, Thanks to Linux.

vi **/*.gd

**Comment by KoBeWi** [comment]
There's Ctrl + Alt + O now.

**Comment by Calinou** [comment]
It's possible to select multiple entries in the **Quick Open Scene** and **Quick Open Script** dialogs by using <kbd>Shift + Left mouse button</kbd>. It'd be nice to support <kbd>Ctrl + A</kbd> in this context as well, but the base feature is there.

**Comment by akien-mga** [comment]
I'll consider this fixed as mentioned above. If someone wants to implement support for Ctrl+A in these dialogs, why not :)
