### ISSUE TITLE
LSP client id is out of bounds

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#39548]
**Godot version:**
6efab27a4142cdd59367ebdf47be08e0ab8ae0f2

**OS/device including version:**
Arch Linux

**Issue description:**
Connecting and disconnecting LSP clients stops the LSP server from working properly.

**Steps to reproduce:**
1. Connect 1 client to the LSP server
2. Disconnect the client
3. Attempt to connect the client again -- you'll get:

```
 modules/gdscript/language_server/gdscript_language_protocol.cpp:283 - Index (uint64_t)p_client_id = 1 is out of bounds (clients.size() = 1).
```

**Comment by Rubonnek** [comment]
This issue was introduced on 3edae035d55b8232bdccff73b4db9401349cdb73

**Comment by akien-mga** [comment]
The error message was added by 3edae03, but if you revert it, the above steps should give you a crash instead of an error.

**Comment by akien-mga** [comment]
CC @Geequlim @ofrank123 @NathanLovato

**Comment by Rubonnek** [comment]
@akien-mga I don't get a crash with vim-lsp when after reverting the commit under Arch Linux.

**Comment by akien-mga** [comment]
Ah I think I misunderstood what type `clients` is. It's a `HashMap`, so it uses arbitrary keys and not contiguous indices, so `clients.get(1)` might be valid if size is 1 and the only key is `1`. The error checks should use `!clients.has(p_client_id)`.
