### ISSUE TITLE
100% core CPU usage when VSync is disabled

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#39557]
**Godot version:**
Godot_v3.2.2-rc1_x11.64 and Godot_v3.2.1-stable_x11.64

**OS/device including version:**
Debian 10 / NVidia Geforce RTX 2080

**Issue description:**
One of my processor cores stabilizes at 100% utilization when the **Use VSync** setting is disabled in the project settings.

[https://www.youtube.com/watch?v=OXkL_wzIOWg](https://www.youtube.com/watch?v=OXkL_wzIOWg)

**Steps to reproduce:**
Uncheck **Use VSync** in Project Settings ⇒ Window.

**Comment by Paspartout** [comment]
Isn't that expected behaviour when disabling vsync and not limiting the fps? Since you don't wait for monitor or limit the fps the CPU will be used 100% to draw as much frames as possible by feeding the gpu as much as possible.

**Comment by akien-mga** [comment]
Yes, with VSync disabled and an overpowered GPU like RTX 2080, you're very likely going to be CPU bound (unless your project is very graphics heavy), so you'll get 100% CPU usage and a mind-boggling (and wasteful) FPS count.

**Comment by TheMoye** [comment]
I don't have this behavior on Windows when VSync is disabled: the core usage stays low and my fan doesn't get excited 🤷‍♂️

**Comment by Calinou** [comment]
@TheMoye Maybe X11 is less suited to dispaying really high frame rates compared to Windows? I don't know for certain. How many FPS are you getting on Windows and Debian respectively?

**Comment by TheMoye** [comment]
Forget it, now on Windows I have a 100% core too. 🤦‍♂️
Thanks for the comments!
