### ISSUE TITLE
Global code for visual shader custom node is missing when compiled, when there is more than one custom shader node used in a graph.

### ISSUE THREAD

**Issue by hanoixan** [godotengine/godot#39569]
**Godot version:**
v3.2.2.rc1.official

**OS/device including version:**
Windows 10 Pro

**Issue description:**
It appears that there is a bug in how global shader code is collected and compiled when creating scripts derived from VisualShaderNodeCustom. If you use more than one custom shader node at the same time, some global shader code will not be included, causing a shader compile error.

**Steps to reproduce:**
With the reproduction project:
1. Load project. It contains two custom shader nodes, CustomNodeA and CustomNodeB. CustomNodeA moves the vertex position up 1 unit in Y. CustomNodeB moves to the right in X. Combined, the position is moved to the up and to the right. 
2. Run the project in the editor. Notice the sphere appears up and to the right of the camera center.
3. Export for Windows Desktop Debug or HTML5. When it runs, it will complain:
```
SCRIPT ERROR: (null): No matching function found for: 'custom_node_A_func'
          At: :29
```
4. Bypass CustomNodeB in the MeshInstance material VisualShader vertex graph, connecting from CustomNodeA.Y direectly to Output.Vertex.
5. Reexport Windows Desktop debug, run, and you'll see that CustomNodeA (which contained the custom_node_A_func() definition in its global code) is now running correctly, making the sphere move up only.
6. I can deduce from this that more than one custom shader node in a shader graph causes one of the custom node global code sections to not be defined. In the above case, it loses the definition for CustomNodeA's global functions.

**Minimal reproduction project:**
[ShaderGlobalCodeDefectRepro.zip](https://github.com/godotengine/godot/files/4781354/ShaderGlobalCodeDefectRepro.zip)

**Comment by clayjohn** [comment]
Cc @Chaosus

**Comment by Chaosus** [comment]
After some debugging I see the problem starts at this line:
https://github.com/godotengine/godot/blob/f61e4216b70c91432f120b82101f0923274dcfba/scene/resources/visual_shader.cpp#L1271
While code is proceeded It returns an empty class for exported project which blocks shader check from process more than first Custom Shader node.
