### ISSUE TITLE
Godot Crash on Geforce 210 (both GLES 2 and GLES 3) (didn't crash on beta 4)

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#39586]
Godot used to work with 3.2.2 beta 4 without issues.
It now crashes on last RC on both GLES2 and GLES3 projects.

OS = Windows 7 x64 Professional Service Pack 1
GPU = Geforce 210 (driver 342.01)

**Comment by clayjohn** [comment]
Do you get errors printed or anything that could help us identify where the crash is coming from?

Does it crash immediately when you start the editor?

**Comment by ca3games** [comment]
@clayjohn  can confirm the Project window opens with no crashing, it crashes when you try to open a project.

Error code:
The Nvdia OpenGL driver lost connection with the display driver due to exceeding the Windows Time-Out limit and is unable to continue.
The application must close.

Error code:7

Edit = The beta4 also now crashes, It used to work, but it seems after allowing windows updates, is what causes now godot to crash, can't confirm if the crash is because of some windows update.

**Comment by ca3games** [comment]
After digging in google I realize it was the same issue I had with Substance Painter.
I followed this guide:
https://docs.substance3d.com/spdoc/gpu-drivers-crash-with-long-computations-128745489.html

Now I remember It lacked such registry key values because I reinstalled windows, so I lost my previous values.
Can confirm godot now doesn't crash and work properly.

Won't close this issue because I want godot developers to include a GPU warning when your GPU (at least on windows) needs this solution.
A pop up warning with a link to the documentation with this solution, would be perfect (similar to how Substance Painter solves this issue).

**Comment by Calinou** [comment]
> Won't close this issue because I want godot developers to include a GPU warning when your GPU (at least on windows) needs this solution.

We can't know for certain whether a specific GPU needs to have its driver timeout limit increased.

Are you using the GLES3 or GLES2 renderer in your project? On such a low-end GPU, you should always use GLES2.

**Comment by ca3games** [comment]
It crashes on both GLES2 and GLES3.

Not sure if the developers want to close this issue, will leave here for others to learn about the solution.
In any case, I would love to see some warning for new indiedevs who may not be aware of what the solution is.

**Comment by akien-mga** [comment]
We can't implement such a warning: either the GPU drivers are initialized properly based on what Godot asks them, or they crash. If they crash, there's nothing we can do.
