### ISSUE TITLE
"Favorite" star icon became unclickable

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot#39584]
**Godot version:**
v3.2.2.rc.custom_build.6c9b7c27d

**OS/device including version:**
Debian Buster amd64, Radeon RX550

**Issue description:**
In the "Project manager", clicking the "star" icon to the left of a project does not do anything.

If I launch 3.2.1.stable.official, clicking the icon causes the icon to turn "on" and "off", and the project to jump up or down in the list. If I launch 3.2.2, the "star" icon does not change its state when I click it.

**Steps to reproduce:**
- Open Godot
- Add a project
- Click the "star" icon

**Comment by akien-mga** [comment]
Fixed by #39501.

**Comment by dark-penguin** [comment]
Sorry for the noise :)
