### ISSUE TITLE
colisionshape error

### ISSUE THREAD

**Issue by japietru2004** [godotengine/godot#39591]
**Godot version:**
3.2.1

**OS/device including version:**
PC

**Issue description:**
ERROR: recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
   At: modules/bullet/space_bullet.cpp:1238
![obraz](https://user-images.githubusercontent.com/51274570/84764701-71777780-afce-11ea-8ae5-ffea7da5dc89.png)
![obraz](https://user-images.githubusercontent.com/51274570/84764728-79371c00-afce-11ea-87b6-2f58175f2d39.png)

**Steps to reproduce:**
Try to build this and move character in it. 3D
[SpaceShip.zip](https://github.com/godotengine/godot/files/4786073/SpaceShip.zip)

![obraz](https://user-images.githubusercontent.com/51274570/84764806-95d35400-afce-11ea-8a34-c816e51466b5.png)

**Minimal reproduction project:**
Zip Atached - spaceshipZip

**Comment by madmiraal** [comment]
Please provide the entire project not just the SpaceShip scene. If I load the SpaceShip scene into a new project I don't get the errors.

**Comment by japietru2004** [comment]
Here is link cutted project file were bug still exist - from my check. File is to big to attach into bug report.
Aditional: Page is safe - it is nextcloud server in my house, but it is on wrong port becose of router things.
https://esbik.myz.info:444/index.php/s/i7RK898NAoY3aT6

**Comment by madmiraal** [comment]
@japietru2004 We need a **minimal** reproduction project that generates the error. So the SpaceShip plus a floor, camera etc. whatever is the minimal amount required to produce the error. This project should be small enough to attach into the bug report.

**Comment by japietru2004** [comment]
I removed almost all scenes - without menu

**Comment by madmiraal** [comment]
Great! Can you attach it to bug report now?

**Comment by japietru2004** [comment]
this should have bug occuring
x to fly e to enter ship - fly
[SpaceStarCutted.zip](https://github.com/godotengine/godot/files/4788145/SpaceStarCutted.zip)

**Comment by japietru2004** [comment]
It was too big becose .import

**Comment by japietru2004** [comment]
also got bug ?

**Comment by madmiraal** [comment]
The error message is generated when a `KinematicBody` using `move_and_slide()` collides with the origin of a `PhysicsBody` with no shapes.

Your SpaceShip contains a `StaticBody` with no collision shape. You are warned about this in the editor:
![39591](https://user-images.githubusercontent.com/9253928/84892899-4eb09600-b096-11ea-8575-567290bcfed3.png)
The error is generated when your `Player` object "enters" the `SpaceShip`, and collides with the `Compass` origin.

You need to either change the `Compass` node type to a `Spatial` or assign a `CollisionShape`.
