### ISSUE TITLE
a scene tree HUD that can be instantiated in game

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot#3960]
**Operating system or device:**

**Issue description** (what happened, and what was expected):
To optimize a game it is important to see which nodes are in tree and which of them have process on. User can display it transparently in his game during development.

or as a kind of noob am I missing something. How pro's are dealing with this or they don't need to do this :)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by vsrinu26f** [comment]
may be I need to keep printing to console till I develop a reusable hud gd script file.

**Comment by neikeq** [comment]
I am not sure if I understand the issue. Are you looking for something like _Debugger -> Info -> Scene Tree_?

**Comment by vsrinu26f** [comment]
Thanks much. Exactly what I was looking for.

**Comment by neikeq** [comment]
However, you cannot view the nodes properties (I am not sure if you was also looking for that).

**Comment by vsrinu26f** [comment]
neikeq: Yes it will be helpful to see process flag and visibility by camera.
