### ISSUE TITLE
Misleading warning about vsync requiring an editor restart in the Project Settings

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39613]
**Godot version:**

3.2.2 rc1

**Issue description:**

When you toggle `vsync` in Project Settings, you get a warning that you need to restart editor for the change to take effect. This is untrue. It takes effect immediately, at least in the project. If the warning is about vsync in the editor, it should state that you need to restart editor to affect the editor. Right now it sounds like it won't have any effect until restart.

**Comment by Calinou** [comment]
We should rephrase the warning in the Project Settings editor so that it states only the editor needs to be restated.

**Comment by JoshMarshall756** [comment]
Hi, potential first time contributor here. I would like to give this issue a go. Where in the codebase should I look to change this warning?

**Comment by KoBeWi** [comment]
You can do a full source search (Ctrl + Shift + F) for the current warning.

**Comment by JoshMarshall756** [comment]
> You can do a full source search (Ctrl + Shift + F) for the current warning.

Thanks, I have found the string of the warning. I don't understand what the warning should be changed to. Sorry for noob questions haha but thanks for the help.

**Comment by nathanfranke** [comment]
The VSync in project settings shouldn't impact the editor, only the project. Does the project manager use VSync? What project does it read the VSync option from?

I think we should split the options into Project VSync and Editor VSync

**Comment by Calinou** [comment]
> Does the project manager use VSync?

Yes, since V-Sync is enabled by default. To my knowledge, there's no way to disable it for the project manager.

> I think we should split the options into Project VSync and Editor VSync

Definitely :slightly_smiling_face:
