### ISSUE TITLE
Android, audio recording error

### ISSUE THREAD

**Issue by 316902108** [godotengine/godot#39612]
Gdodt Editor Version : 3.2.1 Stable
Windows Version : Win10
Android Version : 10
Phone Model : Huawei ELE-AL00

Project settings--Audio--Mix Rate : (8000、16000、or other)
default_bus_layout--Record--Format : 8-Bit

Recording parameters are normal in Windows

But the parameters are abnormal after recording on Android
**Mix_Rate : always 44100**
**The recorded audio can only be played normally under 16-Bit**

**Comment by Calinou** [comment]
@316902108 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by 316902108** [comment]
> @316902108 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
**Please help me to verify this problem, thank you very much!**

**Comment by 316902108** [comment]
[sound recording.zip](https://github.com/godotengine/godot/files/4791329/sound.recording.zip)
This is my project

**Comment by 316902108** [comment]
**When using Android recording！
Project settings--Audio--Mix Rate : (8000、16000、or other)
This parameter does not take effect on Android when setting！**

**Comment by 316902108** [comment]
**It is recommended to add "Mix Rate" property setting in "Audioeffectrecord"**

**Comment by Calinou** [comment]
Superseded by #39631.
