### ISSUE TITLE
Can't favorite/unfavorite projects in project manager

### ISSUE THREAD

**Issue by Phischermen** [godotengine/godot#39627]
**Godot version:**

3.2.2.rc1.mono

**OS/device including version:**

Windows 10

**Issue description:**

Trying to star a project in the project manager (by clicking the faded star) doesn't do anything. Unstarring does not do anything either. This works in the 3.2.1 version however.

**Steps to reproduce:**
Try to star/unstar a project in the project manager

**Comment by aaronfranke** [comment]
Fixed by #39501

**Comment by Phischermen** [comment]
Glad it's been taken care of! I realize now that I ought to search for open AND closed issues before opening my own.
