### ISSUE TITLE
Custom font size flicker when changing the size of the window.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#39628]
Godot 3.2.1
Windows 10 1909
GTX 1070
Up to date drivers.
GLES2 , GLES3

**Issue description:**

What happened: When resizing the game window, Custom font labels/text flickers when resizing. like showen here:
![sa](https://user-images.githubusercontent.com/61591052/84943445-a37afd80-b0e4-11ea-954c-1ce98ab7c238.gif)

expected: to resize smoothly like non custom font labels/text like this:
![wa2](https://user-images.githubusercontent.com/61591052/84943489-b8579100-b0e4-11ea-8559-d8ecd4c5d96d.gif)

**Steps to reproduce:**
-Use 2D mode in project settings
-Create any label , richtextlabel , textline , textedit. 
-Change the font from non to your custom font.
-play and resize the window

Here is a project i created to show the bug:

[Bug.zip](https://github.com/godotengine/godot/files/4794850/Bug.zip)

I hope this get fix soon.
and Thanks.

**Comment by Gerarama** [comment]
Update #1 : 
Disabling Oversampling fixes the problem.
But truns the quality of the text.

**Comment by akien-mga** [comment]
CC @godotengine/gui-nodes

**Comment by Calinou** [comment]
I'm not sure if this is an actual bug. If you're using a pixel font, the fact that the *final* font size must be an integer will be especially noticeable, even if the font oversampling *factor* itself is a float (which you can't control).

**Comment by Calinou** [comment]
Closing, as this is better addressed by something like https://github.com/godotengine/godot-proposals/issues/1666.
