### ISSUE TITLE
Aligning a Label "Center" or "Right" does not account for leading or trailing spaces

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#39630]
**Godot version:** Occurs in 3.2 and master

**OS/device including version:** Ubuntu 20.04

**Issue description:** Aligning a Label "center" or "right" does not account for leading or trailing spaces. This was the cause of a long troubleshooting session on Discord. In the MRP posted, there are 3 nodes that show incorrect behavior.

* Label1 has leading spaces and is set to align right, and its text is pushed outside of the box by the spaces because the alignment setting does not account for the leading spaces.

* Label2 is a copy of Label1 except that there is a letter added in front of the spaces, which causes them to be counted and the text displays properly.

* Label3 has trailing spaces and is set to align center. The text is in the middle, since it does not account for the spaces, but the text should actually be pushed to the left.

**Steps to reproduce:** Open the MRP, click on the boxes, observe that the behavior is wrong in many ways.

**Minimal reproduction project:** [labels-are-broken.zip](https://github.com/godotengine/godot/files/4795538/labels-are-broken.zip)

**Comment by FlashDaggerX** [comment]
I am so happy you mentioned this... I was just looking over a similar issue I failed to fix with `LineEdit`. The issue is still present in **3.2.2rc1**.

See issue #34951.
