### ISSUE TITLE
Particles and Particles2D signal when finished

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3963]
http://godotengine.org/qa/883/how-to-remove-a-particle2d

**Comment by bojidar-bg** [comment]
You want a signal or just auto-free?

**Comment by AlexHolly** [comment]
Depends on the use case I think.

1. Someone who wants to re-use that Particle Node doesn't want auto-free.
2. In my case I need just auto-free.

A boolean would be nice but what is with someone who wants to play a sound on end or play another Particle?

**Comment by bojidar-bg** [comment]
Well, with a "emission ended" signal, we can just `particles.connect("emission_ended", particles, "queue_free")` or even `particles.connect("emission_ended", player, "queue_free")`, so it is way more useful actually (note that you can connect those through the Node panel as well).

**Comment by bojidar-bg** [comment]
Reopening, as the above PR was reverted when GPU particles were added.

**Comment by coppolaemilio** [comment]
I was about to ask about this issue. Is there a way to autofree them?

**Comment by KoBeWi** [comment]
A workaround is using a Timer.

**Comment by MatthewDLudwig** [comment]
Why was this reverted with the addition of GPU particles?

**Comment by KoBeWi** [comment]
Because the particle system was rewritten.

Also this should probably go to https://github.com/godotengine/godot-proposals/issues/815

**Comment by MatthewDLudwig** [comment]
Thanks for the link, seems it's already been suggested.  If anyone finds themselves here when looking for the solution, you can show your support for this being added to 4.0 at https://github.com/godotengine/godot-proposals/issues/815#issuecomment-665567264

**Comment by KoBeWi** [comment]
So I guess this can be closed in favor of the proposal.
