### ISSUE TITLE
The signal receiver method is not created when using an external editor.

### ISSUE THREAD

**Issue by yskang** [godotengine/godot#39642]
**Godot version:**

v3.2.1.stable.official

**OS/device including version:**

OS: Ubuntu 20.04 LTS

**Issue description:**

The editor generate the signal receiver method automatically with the "connect" menu on Node tab when I use internal script editor but it't not working when I use external editor. (I'm using the GDScript)

**Steps to reproduce:**
- Editor Settings - External
  - check the checkbox of "Use External Editor"
  - set Exec Path as "my vscode path"
  - set Exec Flag as "{project} --goto {file}:{line}:{col}"
- open any scene and select any node in the scene. (the scene has a connected script.)
- on Node tab, select any signal
- right click the signal and click the "connect"
- don't any change click the "connect" button on the popup window "Connect a Signal to a Method"

- Expected:
   - A new method has created in the script.

- Actual:
   - nothing has changed in the script.

**Minimal reproduction project:**

**Comment by Coldragon** [comment]
I think the behavior is normal because if you edit the file in the external editor and have unsaved work, when you do that there is a conflict with what's in the editor and the file on the disk.

A nice way to handle that would be to send the method created to the clipboard (with a checkbox or a button "Ok and copy")

**Comment by yskang** [comment]
I think that @Coldragon  is right. I missed something
The Godot editor can't push a text to the view memory of external editor.
