### ISSUE TITLE
[4.0] Won't build with MinGW (Warnings treated as errors)

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#39648]
**Godot version:**
4e0f31a

**OS/device including version:**
Windows 10 x64

**Issue description:**
Crashes when building in the middle with MinGW

**Steps to reproduce:**
1. Run build with MinGW (without Mono!).
2. Wait.
3. Catch this:
![image](https://i.imgur.com/T4EDll4.png)

**Comment by Byteron** [comment]
not sure if this is still the case but a couple weeks back warnings were treated as errors. Building with the `-werror=0` flag worked.

**Comment by Calinou** [comment]
@Byteron The SCons flag to use is `werror=no`, not `-werror=0`.

**Comment by Byteron** [comment]
I get the same error when building with -werror=no

**Comment by Calinou** [comment]
@Byteron Make sure not to include a leading `-` symbol. If all else fails, you can edit `SConstruct` and remove the code that enables `-Werror`.

**Comment by Byteron** [comment]
ahh yes that seems to be working, thanks. :)

**Comment by Teashrock** [comment]
@Calinou 
@Byteron 
Interesting. I'll try this as well.

**Comment by lightspot21** [comment]
Latest master builds correctly AFAICS.

**Comment by Calinou** [comment]
@Byteron @Teashrock Can you (or anyone else) still reproduce this bug in [Godot 3.4.2](https://godotengine.org/article/maintenance-release-godot-3-4-2) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
