### ISSUE TITLE
Click Events passing through Buttons if there is a Viewport underneath

### ISSUE THREAD

**Issue by Aidan-85** [godotengine/godot#39666]
**Godot version:**
3.2.1.0

**Issue description:**
Clicks seem to pass right through a Button without triggering it if there is a sub Viewport underneath the area of the button that's clicked. It happens even if the Button has a Mouse Filter set to 'Stop'. If there's a Button within the Viewport, directly below, it receives the Event without a problem.

**Steps to reproduce:**
Place a button partially over a sub viewport and click area where they both overlap.

![viewport_issue_1](https://user-images.githubusercontent.com/67119841/85086444-86245d00-b1d2-11ea-8473-00f3e24e2adc.jpg)
[Viewport_Issue.zip](https://github.com/godotengine/godot/files/4801937/Viewport_Issue.zip)

**Comment by gdelcurla** [comment]
This has become a big issue for me too. What makes it especially tricky is that it seems like any node inside the viewport can block input as well, even if the viewport itself doesn't cross boundaries with that node.

For example, If button 2 is inside a viewport, with button 1 and 3 adjacent, everything works as expected. 
![all_working](https://user-images.githubusercontent.com/319217/126052531-33023fc7-31e3-4cbd-8520-8635090845c6.png)

But if I then drag button 2 e.g. upward inside the viewport, then button 2 blocks input to button 1, EVEN THOUGH it's not even onscreen and should be contained by the bounds of its viewport. 
![interference](https://user-images.githubusercontent.com/319217/126052769-10786509-4715-4e4c-aa4d-f21e7bff44f7.png)

This also occurs if you drag button 2 down toward button 3.

Here's a sample project in C#/Mono
[ViewportBug.zip](https://github.com/godotengine/godot/files/6835498/ViewportBug.zip)

**Comment by Sauermann** [comment]
This bug report has two duplicates: #45400 and #48401

**Comment by Reneator** [comment]
Still happening in v3.5.stable.official [991bb6ac7]
