### ISSUE TITLE
Incompatible Linux and Windows android build templates

### ISSUE THREAD

**Issue by Aleksul** [godotengine/godot#39675]
**Godot version:**
Godot 3.2.1 stable official (headless version on Ubuntu)

**OS/device including version:**
Ubuntu 20.04 in docker container / Windows 10 Pro

**Issue description:**
In project export_presets.cfg "use_custom_build" is set to true.
When you add an Android build template from a MS Windows machine and after try to export this project (with build template already set) on Linux (Ubuntu in my case, but I also tried on Alpine and Arch, it's the same) it throws the error below. 
```
# godot --export-debug "Android" myproject.apk
Godot Engine v3.2.1.stable.official - https://godotengine.org

export: begin: Exporting for Android steps: 105
export: end
ERROR: _fs_changed: Project export failed with error code 20 for preset 'Android'.
   At: editor/editor_node.cpp:634.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```

Exporting project on linux **without** custom build also throws last 2 errors but it does **not** influence on success of export.
```
# godot --export-debug "Android" myproject.apk
.....
export: end
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```

However, exporting on windows shows no errors.

The problem is that I've found no way to re-set/re-build custom build template using headless version. (Even if I could, it will be really hard to configure config.gradle and gradle-wrapper.properties, I think it's better to have some settings for that in the engine)

**Steps to reproduce:**
On windows:
1. Create a project.
2. Set android build template.
3. Add android export preset with "use_custom_build" set to true.
4. Export the project for the first time.

On linux (Ubuntu):

5. Somehow get the same project on linux (in my case: via git)
6. Try to export the project using command
` # godot --export-debug "Android" myproject.apk`

**Minimal reproduction project:**
[Issue.zip](https://cloud.mail.ru/public/4K2i/3mCMQf9ny)

Also here is dockerfile for building an image that I use for exporting. (Github doesn't support files with no extension, so now it's Dockerfile.txt)
[Dockerfile.txt](https://github.com/godotengine/godot/files/4804134/Dockerfile.txt)

**Comment by akien-mga** [comment]
Are you sure it's an imcompatibility in the build template and not just that your Linux-based export pipeline doesn't work (e.g. missing `adb`, `jarsigner` or keystore)?

Can you set up the build template and export on Linux successfully?

**Comment by Aleksul** [comment]
> 
> 
> Are you sure it's an imcompatibility in the build template and not just that your Linux-based export pipeline doesn't work (e.g. missing `adb`, `jarsigner` or keystore)?
> 
> Can you set up the build template and export on Linux successfully?
Yeah, I set up everything correctly (double checked it a lot of times), also I can export projects without "use_custom_build" flag successfully. You can see dockerfile for more details.

**Comment by Aleksul** [comment]
Also, I must notice that error
`Project export failed with error code 20`
doesn't give enough information to understand what went wrong. Is there a page with description of those error codes?

**Comment by akien-mga** [comment]
Error codes are here: https://github.com/godotengine/godot/blob/master/core/error_list.h#L62

There's no simple int value to enum "name" in C++ and we haven't implemented a reverse lookup table manually (yet), so it can't be shown in a better way right now.

20 is `ERR_CANT_CREATE` which hints at a permission issue, or a missing target directory maybe?

**Comment by akien-mga** [comment]
```
 && echo 'export/android/custom_build_sdk_path = "/root/android"' >> ~/.config/godot/editor_settings-3.tres \
```
I'm not sure this is correct, your `/root/android` contains `cmdline-tools` but the SDK root is the folder which contains the `tools` and `platform-tools` folders.

Remove the extraneous `cmdline-tools` where you moved `tools`, or set the root path to `/root/android/cmdline-tools`.

**Comment by akien-mga** [comment]
In case the config is correct and the issue is confirmed to be linked to having installed the build template on Windows, try to run `gradlew clean` in `res://android/build` to ensure a clean build with Windows-made artifacts.

**Comment by Aleksul** [comment]
> 
> 
> ```
>  && mkdir -p ~/android/cmdline-tools \
>  && unzip -q commandlinetools-linux-*.zip \
>  && mv tools ~/android/cmdline-tools \
> 
> ...
> 
>  && echo 'export/android/custom_build_sdk_path = "/root/android"' >> ~/.config/godot/editor_settings-3.tres \
> ```
> 
> I'm not sure this is correct, your `/root/android` contains `cmdline-tools` but the SDK root is the folder which contains the `tools` and `platform-tools` folders.
> 
> Remove the extraneous `cmdline-tools` where you moved `tools`, or set the root path to `/root/android/cmdline-tools`.

Since _some_ version cmdline-tools have to have path tree like `android/cmdline-tools/tools`, and everything still will be installed inside `android` folder. Here is an image after building and running the container. 
![изображение](https://user-images.githubusercontent.com/63556725/85130440-9cb3ce00-b23d-11ea-8468-1d158f115f10.png)

**Comment by Aleksul** [comment]
> 
> 
> In case the config is correct and the issue is confirmed to be linked to having installed the build template on Windows, try to run `gradlew clean` in `res://android/build` to ensure a clean build with Windows-made artifacts.

Done that and here is what I have:
```
# cd android/build
# ls
AndroidManifest.xml  build.gradle  config.gradle  gradle  gradle.properties  gradlew  gradlew.bat  libs  src
# gradlew clean
/bin/sh: 9: gradlew: not found
```
Any ideas?

**Comment by Aleksul** [comment]
> 
> 
> > In case the config is correct and the issue is confirmed to be linked to having installed the build template on Windows, try to run `gradlew clean` in `res://android/build` to ensure a clean build with Windows-made artifacts.
> 
> Done that and here is what I have:
> 
> ```
> # cd android/build
> # ls
> AndroidManifest.xml  build.gradle  config.gradle  gradle  gradle.properties  gradlew  gradlew.bat  libs  src
> # gradlew clean
> /bin/sh: 9: gradlew: not found
> ```
> 
> Any ideas?

Fixed it by giving execute permissions with `chmod`. Now will try to export.

**Comment by Aleksul** [comment]
>  try to run `gradlew clean` in `res://android/build` to ensure a clean build with Windows-made artifacts.

Wow, thanks a lot, that helped.
