### ISSUE TITLE
control node button not working in 3D scene  android 

### ISSUE THREAD

**Issue by amzker** [godotengine/godot#39679]
**Subjective :** control node button not working in 3D game play scene android ( movements button)
**Objective:**
Host OS: Linux Debian Based
Guest OS(vm): Windows 10 64 bit
Godot Running on : Windows 
Downloaded from : this repo release page
Godot version : 3.2.1 stable official
Day used : 1.5
Error getting on : Android 

**Detailed issue**
I created 3D levels & 2D scenes as menu 
2D scenes have play button in which when user click on it , it take them to level selection page and from that they select level and goes to level 1,2,3 by clicking.
In android this button working. if i click on them they work perfectly and take me into level1 3D.
So i thought why add joystick. so i added buttons on level using control node like

**up**
`extends Button
func _ready():
	pass
func _on_Button_pressed():
	Input.action_press("ui_up")
` 
and same as down,right,left,jump.

problem is this button not working in android but working in PC build when click using mouse.

**Comment by amzker** [comment]
sorry for issue report. actually now it is not working in windows too, so maybe first time mistaken i putted finger on up key of keyboard

**Comment by Calinou** [comment]
If it's not working on any platform, then the issue is most likely in your project. I'd recommend using other [community channels](https://godotengine.org/community) for support questions.
