### ISSUE TITLE
Serious recent performance drop

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#39680]
**Godot version:**
3.2 branch - 307a9551ae16e494441c47420862f7095d6066f6

**OS/device including version:**
Arch Linux - GCC 10.1.0

**Issue description:**
Between commits d20485039cd2a2a0082c25759c3c92f43bc635bb and 88c22cb6488cc6be234b4bff97b66ba12818b6a0 a serious performance drop can be seen when running the SPHater demo in the asset library.

**Steps to reproduce:**
* Run the SPHater demo on commit d20485039cd2a2a0082c25759c3c92f43bc635bb
* Run the same demo using a build from commit 88c22cb6488cc6be234b4bff97b66ba12818b6a0

Notice the performance drop in the latter.

**Minimal reproduction project:**

https://github.com/SIsilicon/SPHater-Godot-Demo

**Comment by akien-mga** [comment]
Can you try beta/RC builds to narrow the range further down?

**Comment by Rubonnek** [comment]
@akien-mga I'll be glad to. Is there a link where I can find those builds? I don't see tags for RC or beta builds, and I usually compile my own builds.

**Comment by clayjohn** [comment]
Here https://downloads.tuxfamily.org/godotengine/3.2.2/ :)

**Comment by Rubonnek** [comment]
@clayjohn Thanks!

**Comment by Rubonnek** [comment]
I can't reproduce this issue with the release versions. So far only the debug builds seem to be affected.

Here's how I'm compiling my builds:

```shell
scons platform=x11 target=debug debug_symbols=full CXX=g++ builtin_openssl=yes tools=yes bits=64 -j$(nproc)
```

**Comment by clayjohn** [comment]
@Rubonnek Are you comparing two debug builds? Is there any chance you are actually comparing a debug build to a release build?

Note, the pre-built binaries are using release_debug, which can be significantly faster than regular debug builds.

**Comment by akien-mga** [comment]
> `builtin_openssl=yes`

You can drop this, Godot doesn't use OpenSSL any longer since 3.1.

**Comment by akien-mga** [comment]
I just tried and I get horrible performance (3-4 FPS) with a `target=debug` build with both d204850 (which was supposed to have good performance) and 2b737a99b (latest `3.2` or close).

With official `release_debug` builds, I get 40-60 FPS (on AMD Radeon Vega M GPU, on Linux).

**Comment by Rubonnek** [comment]
@akien-mga You are absolutely right -- I completely forgot about that lol.

What is the benefit of using a `debug` build?
