### ISSUE TITLE
Post import script seems not working at current head.

### ISSUE THREAD

**Issue by amkk** [godotengine/godot#3968]
Hello.
I'm not sure but Post import script seems not working at current head.
even if most simple code like
````gdscript
tool
extends EditorScenePostImport
func post_import(_scene)
    print(_scene)
````
is not working.

I think this is happen after this commit.
#https://github.com/godotengine/godot/commit/2a7fdb23b3381900c3dd087f567e50d2d738c43a
My simple example code work as expected before this commit. 
Please anyone confirm this?

**Comment by GlaDOSik** [comment]
I can confirm this. It throws  res://rigifyToGodot.gd:8 - Invalid get index '1' (on base: 'Array') error.

**Comment by amkk** [comment]
My old example code
```
tool
extends EditorScenePostImport
func post_import(_scene)
    print(_scene)
```
 work as expected in old version.(compiled before this march)

I don't know when it's changed.
But in current version, post_import seems to need return the edited scene.
(I read "editor_scene_import_plugin.cpp" and new Method Description of post_import.)
```
tool
extends EditorScenePostImport
func post_import(_scene)
   print(_scene)
   return _scene
```
is work with no error.

I think GlaDOSik mentioned issue is another problem.

**Comment by GlaDOSik** [comment]
I'm almost sure I did test it with the return and it didn't work. The problem was either fixed or my testing scene was somehow bugged (but I saw users with this problem on Facebook). Anyway, post script import seems to be working fine in the current version (compiled from source today).

**Comment by reduz** [comment]
I tested this and it's working, the problem was the script above is laking :  at the end of the function, and error of script not being parsed properly was not shown as it should. Will fix the error reporting
