### ISSUE TITLE
New Export Preset fileselection cleanup overwrites manual export_presets.cfg edits

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#39681]
**Godot version:**
3.2.2.rc2.official

**OS/device including version:**
win10 64x

**Issue description:**

The added (https://github.com/godotengine/godot/pull/39434) cleanup for export preset file selection seems to overwrite manual changes in the preset config file that are made while the editor is running. It seems the presets are saved with an old filelist that is created on editor startup and never updated when not opening the export menu.

This is not an issue for manual selection of files in the export preset (by using the export menu that triggers an update) but an issue that affects all scripted updates that edit the export_presets.cfg config file directly.

E.g. on a current game project there are way over 10.000+ files, no way to update this manually in the export preset by clicking them one by one. Instead all presets in the export_presets.cfg are updated with a script to add current files in the export_files=PoolStringArray().

Now everytime
a) Export menu is opened
b) Editor closes
.. the export presets save but the export_files get overwritten with the old list from the first editor startup.

Workaround:
"Crashing" the editor on purpose solves the overwrite issue currently and keeps the updated filelist on the next editor startup.

Possible fix:
The preset filelist should always update with the content from the export_presets.cfg directly before the preset save function runs to make sure it stays current and accounts for manual edits.

**Steps to reproduce:**
1.) Create export presets with file selections
2.) Start editor again
3.) Now make manual changes to the export_presets.cfg and export_files=PoolStringArray()
4.) Close editor or open export menu, all manual changes get overwriten even if all the added files exist in the project.

**Comment by akien-mga** [comment]
CC @mrushyendra

**Comment by mrushyendra** [comment]
@smix8 Just to confirm, this occurs when someone:

1. Opens the editor
2. Makes manual changes to files in export_presets.cfg
3. Opens the export dialog _(overwrites export_presets.cfg)_

It seems like in the old version a similar issue exists too, but only when selecting `Export Project`:

1. Open the editor
2. Make changes to files in export_presets.cfg
3. Open the export dialog _(does not overwrite the cfg file yet)_
4. `Export Project` _(exports project with the manual changes included)_
5. Automatically overwrites export_presets.cfg with the original version

Another temporary workaround for now could be to use the command line to export, without opening the export dialog window at all. Lastly, closing the editor did not seem to overwrite the cfg file for me.

**Comment by smix8** [comment]
I now used a clean, new godot project and retried and it overwrites the export_presets.cfg with (old) content saved at editor startup when Project -> Export is opened.

It doesn't save/overwrite on editor close with a clean, new project so might be a toggled setting or leftover in the old project.

So the Project -> Export menu button triggers a write on the config but doesn't update the filelist before it overwrites.

I still think the update of the preset filelist shouldn't be bundled with a menu click alone, it should run directly before the preset save function runs so it always stays current or else it will only fix the problem for small projects but stay a nightmare for large projects with multiple users.
