### ISSUE TITLE
Bullet engine PhysicsDirectSpaceState.intersect_shape() crash with no errors

### ISSUE THREAD

**Issue by AC-Webbyninja** [godotengine/godot#39699]
**Godot version:**
Godot 3.2.1 Stable 64 Bit

**OS/device including version:**
Windows 10

**Issue description:**
When performing a intersect_shape query using on the space state using the Bullet physics engine, if the PhysicsShapeQueryParameters object's shape is not set, there is a crash with no errors. Using the GodotPhysics physics engine, the error "get: Condition "!p_rid.is_valid()" is true." is outputted to the debugger. Also, this may or may not be a bug, setting the shape of the physics parameters object does not add to the reference counter of the shape, so if the shape was created locally and set to the physics parameter object inside that same scope, when the shape is freed it causes the same crash when using the BulletPhysics engine. PhysicsShapeQueryParameters.set_shape() isn't referencing the shape directly. Maybe that isn't a bug, it just seems that way because of the Bullet engine crash.

**Steps to reproduce:**
I created a project with three nodes. NoShapeSet has a script that performs an intersect_shape with no shape set. ShapeReferenceLost sets the shape in the local scope of a setup function so that the shape reference is lost before the intersect_shape is performed. ShapeReferenceHeld holds a reference to the shape in a script variable and set it to the physics parameters object to act as the control. No crash happens when running the test with only this node's test enabled.

I added two export variables to enable/disable the test on each node and to set whether the intersect_shape is run just once or every frame.

A simple workaround would be to just make sure all query parameters have shapes set and that all shapes used aren't accidently freed, but without error outputs, it took me a bit to track down what caused it in my personal project I am working on. So, a proper fix would be better.

**Minimal reproduction project:**

[PhysicsBug.zip](https://github.com/godotengine/godot/files/4807332/PhysicsBug.zip)

**Comment by pouleyKetchoupp** [comment]
I've just made PR #39747 to fix the crashes with invalid shapes and replace them with errors.

Note: The case where a shape has been released and is still referenced in query parameters will trigger the same error. Fixing it is possible, but it would mean storing a shape reference in the query parameters and probably requires to break compatibility (remove `PhysicsShapeQueryParameters::set_shape_rid` as it makes it more complicated to store a reference).

**Comment by AC-Webbyninja** [comment]
Does this need a fix or is this intended behavior? The physics server function calls all operate on RIDs passed to the functions to create or modify different physics shapes and bodies. Although, I can see how this is different because you're not directlty interfacing with the server and are using a object which could hold a reference to the shape and then perform the calls to the physics server by passing the shapes RID from the reference it would hold.

**Comment by pouleyKetchoupp** [comment]
I think it makes sense to fix it. I just haven't looked into the details yet because it's a bit more involved.

**Comment by pouleyKetchoupp** [comment]
I've just opened PR #39846 to properly fix this issue for 4.0.

**Comment by pouleyKetchoupp** [comment]
I've closed my new PR as @Xrayez already made a fix for this issue in PR #35633 some time ago and it doesn't break compatibility.
