### ISSUE TITLE
Godot filesystem on osx does not synchronize files.

### ISSUE THREAD

**Issue by crimsonalucard** [godotengine/godot#39698]
**Godot version:**
v3.2.1

**OS/device including version:**
OSX.

**Issue description:**
Editor filesystem viewer does not sync with new files added externally or dragged and dropped into the editor. When another folder is dragged and dropped into the editor the folder is copied into the actual folder but does not show up on the view.  

**Steps to reproduce:**
Start a new project copy a folder of files into project folder. Editor does not reflect change on OSX. It does reflect the change on windows. 

**Minimal reproduction project:**
Can be reproduced with a completely new project.

**Comment by omardelarosa** [comment]
I'm also having this issue.  Strangely, it's only happening on my newer of two macs (an M1 MacMini with BigSur) but it's not happening on my older, Intel MBP running Catalina.

**Comment by Calinou** [comment]
> Strangely, it's only happening on my newer of two macs (an M1 MacMini with BigSur) but it's not happening on my older, Intel MBP running Catalina.

It's probably caused by Rosetta x86 emulation in this case. Can you try the native ARM binaries available for [3.2.4beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-4)?

**Comment by omardelarosa** [comment]
@Calinou So I download the 3.2.4beta4.  Here's the result:

![Screen Shot 2020-12-23 at 9 45 03 AM](https://user-images.githubusercontent.com/2551722/103008705-8c89ed80-4503-11eb-84b4-0fb2c899f062.png)

1. Opened Godot it in native mode (outside of Rosetta mode)
2. Dragged and dropped a PNG file into the FileSystem tab.
3. Did not see the file in the FileSystem view.
4. Restarted Godot
5. Did not see the file in the FileSystem view (or in the project folder)

Afterwards, I enabled Rosetta mode by clicking the "open using Rosetta" checkbox:

![Screen Shot 2020-12-23 at 9 36 01 AM](https://user-images.githubusercontent.com/2551722/103008493-374ddc00-4503-11eb-9a96-88674bd7d5cc.png)

1. Opened Godot it in Rosetta mode
2. Dragged and dropped a PNG file into the FileSystem tab.
3. Did not see the file in the FileSystem view.
4. Restarted Godot
5. DID see the file in the FileSystem view (or in the project folder)

This seems to be the same behavior as the stable Godot release I was using 3.2.3 before where it only syncs after an editor restart.  It also suggests that importing assets/resources _only_ works in Rosetta mode and not at all in ARM mode.

**Comment by bruvzg** [comment]
Fixes for drag-and-drop not working on native M1 - #44619 (4.x), #44620 (3.2.x)

I can't reproduce FS panel not updating on x86-64 Big Sur.

**Comment by bruvzg** [comment]
Most likely FS panel not updating is related to the resource directory "modified time" flag not changed or read correctly (get_modified_time` / `stat`).

**Comment by omardelarosa** [comment]
Thanks @bruvzg !

**Comment by KoBeWi** [comment]
Can anyone still reproduce this issue in 4.0 alpha7?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
