### ISSUE TITLE
Can't call resume()

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#39691]
**Godot version:**
3.2.1.stable.official
**OS/device including version:**
Windows 10 Home 1909
**Issue description:**
In the debugger will be printed "Invalid call. Nonexistent fcuntion 'rseum' in base 'Nil'."
```
func _on_Buy_pressed():
	score -= live_price
	lives("+")
	live_price *= 2
	$Control/LiveContainer/Buy/Price.text = str(live_price)
	if score >= live_price - 1 and current_round % coin_getter == 0 and current_round != 0:
		buy()
	else:
		buy().resume()
	

func buy():
	if score >= live_price - 1 and current_round % coin_getter == 0 and current_round != 0:
		$Control/Pause.pressed = true
		$Control/LiveContainer/Buy.disabled = false
		$Control/LiveContainer/Buy/Time.add_color_override("font_color", ColorN("white"))
		if not buy_timer.is_processing():
			buy_timer.start()
			yield(get_tree().create_timer(buy_timer.wait_time), "timeout")
	$Control/Pause.pressed = false
	$Control/LiveContainer/Buy.disabled = true
	$Control/LiveContainer/Buy/Time.add_color_override("font_color", ColorN("dimgray"))
```
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
What do you expect this to do?
`buy()` is a function which returns `null`, and `null` doesn't have any functions defined (so of course no `resume()` function either).

**Comment by MaaaxiKing** [comment]
I just want to do that what is written under the `yield` in the function without making a new function or writing it in `_on_Buy_pressed()`.

**Comment by akien-mga** [comment]
Well you seem to misunderstand what `yield()` does. Your `buy()` function calls `yield(get_tree().create_timer(buy_timer.wait_time), "timeout")`, so it will resume automatically once the `buy_timer` times out. You don't have any control to do this on demand with a `resume()` call which doesn't exist.

Please use other community platforms for support, this issue tracker is for bug reports.

**Comment by MaaaxiKing** [comment]
I do understand `yield()` but it seems I don't understand `resume()`. https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#coroutines-with-yield
