### ISSUE TITLE
Add documentation comments to the .NET library.

### ISSUE THREAD

**Issue by HubKing** [godotengine/godot#39703]
**Your Godot version:**
3.2

**Issue description:**
It seems that the documentation data are already there,
![image](https://user-images.githubusercontent.com/10900489/85186251-f3b7b280-b2d2-11ea-9664-03bd44c66587.png)
, but the writers of the C# library [forgot to add the documentation comments to the C# library](https://godotengine.org/qa/74457) in lots of cases.

Since the data are already there, can't it be done mechanically (by some kind of code) to insert method descriptions into the C# library (like below) so that C# users could see the documentation while they code? In the example below, the usage example is GDScript, so it doest not exactly match C#, but many users will be able to guess the C# code from that, and it is better than having nothing. Even if you do not like having GDScript example in C#, you could then at least add the summary ("Converts one or ...") part.

![image](https://user-images.githubusercontent.com/10900489/85186447-04b4f380-b2d4-11ea-8153-5000ea7a9332.png)

**URL to the documentation page (if already existing):**

**Comment by Calinou** [comment]
> We need to set a rule that no new additions are undocumented. Then we need to start the process of documenting the existing cases.

This was done here: https://github.com/godotengine/godot/commit/6d0e8f9fb70ff00088185f59a627c8f65f5d78ed

**Comment by neikeq** [comment]
I'm talking specifically about the part of the C# API that's not auto-generated: https://github.com/godotengine/godot/tree/master/modules/mono/glue/GodotSharp/GodotSharp/Core

**Comment by aaronfranke** [comment]
@neikeq What are the goals here, do we want to document every single class and method? I can do that if it's desired.

**Comment by neikeq** [comment]
Yes, that would be ideal. Since this part of the API is not generated, we should also try to follow the xml comments convention more closely (the generated API adds everything into a `summary`).

**Comment by jiq4449** [comment]
I have just updated my pull request on #60128 to have all of the requested files documented.

**Comment by akien-mga** [comment]
@godotengine/dotnet Is this sufficiently solved by #60128 or is there more that needs to be documented? And if so, is that "more" still a good tasks for first time contributors?

**Comment by aaronfranke** [comment]
Closing as solved by #54581, #60128, and likely a few others.
