### ISSUE TITLE
Godot 3.2.2 RC2 crash when opening CSG made with Godot 3.2.1

### ISSUE THREAD

**Issue by Blackiris** [godotengine/godot#39718]
**Godot version: 3.2.2 rc2**

**OS/device including version:**
Linux 5.7.3-arch1-1-  Nvidia - GLES3

**Issue description:**
Godot 3.2.2 RC2 crash when opening some CSG made with 3.2.1

**Steps to reproduce:**
Open the given project with Godot 3.2.2 RC2. It will try to open the project but failed.
If you simplify the CSG enough using Godot 3.2.1, Godot 3.2.2 RC will then open it successfully.

**Minimal reproduction project:**
[csg_godot_3.2.2.zip](https://github.com/godotengine/godot/files/4808566/csg_godot_3.2.2.zip)

**Comment by Rubonnek** [comment]
I can reproduce this with bd16fd9d19599cd6550a519226f00b80a62fa915

Falls into a deadlock with this build. Here's a backtrace -> [gdb.txt](https://github.com/godotengine/godot/files/4808613/gdb.txt)
