### ISSUE TITLE
OBJ 3D mesh import failure on windows with different files

### ISSUE THREAD

**Issue by Viish** [godotengine/godot#3973]
**Operating system or device:**
Windows 10 and Godot 2.0 stable 64 bits binary (23/02/2016)

**Issue description** (what happened, and what was expected):
When I try to import an OBJ file as a 3D mesh into the scene, the importer fails

**Steps to reproduce:**
Import either RTS Orc Banner or RTS ORC Lumberjack model from https://shop.bitgem3d.com/collections/free-3d-models (it's free).

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
sorry dude, will not register to a site in order to test a model. Please directly link the model here and will reopen the issue.
