### ISSUE TITLE
Exporting .png files to pck, only the .import files where exported

### ISSUE THREAD

**Issue by nightrobin** [godotengine/godot#39746]
**Godot version:**
3.2.1-stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
Exporting .png file to pck, only the .import files where exported

**Steps to reproduce:**
1. Select Export Mode: Export selected resources (and dependencies)
2. Check the .png files
3. Click Export PCK/Zip
4. Type the filename for the exporting of .pck file (e.g. sample.pck)
5. Load the pck file in a Godot Project. Print the list of the files to terminal.

**Minimal reproduction project:**
Not needed

**Comment by akien-mga** [comment]
That's not a bug, PNG files are imported as StreamTexture resources in the `.import/` folder. The remapping between their original path and the imported StreamTextures is done automatically when you use `ResourceLoader`/`load` to load them.

**Comment by nightrobin** [comment]
> That's not a bug, PNG files are imported as StreamTexture resources in the `.import/` folder. The remapping between their original path and the imported StreamTextures is done automatically when you use `ResourceLoader`/`load` to load them.

I see, but what is the relation of this to the exporting of pck? Correct me if I'm wrong in my understanding but the exporting of resource has a selection for .png files

Scenario:
Supposedly I am creating the .pck file as a DLC for my game, inside it were the images. 

How would the published program know or load the image files if the .pck file only have the .import files inside? How would it be able to remap the original path? Does the loading of the .pck file add a reference file in the .import/ folder?

**Comment by akien-mga** [comment]
The generated PCK will have an `.import/` folder with the `.stex` files matching the original PNGs you selected. If not, that's a bug.

**Comment by nightrobin** [comment]
How would I export the .stex files to the .pck file?

**Comment by nightrobin** [comment]
> The generated PCK will have an `.import/` folder with the `.stex` files matching the original PNGs you selected. If not, that's a bug.

I rechecked, there is still no original PNG when I loaded the .pck file.

I read the .import file there is a line:
[deps]
source_file="res://Assets/Packs/dlc/Image1.png"
yet it does not exist in the pck.

Anyway, thanks but can you reopen this ticket, it is still an unresolved bug, nevertheless.

**Comment by akien-mga** [comment]
As I said, there will not be original PNGs in the PCK, there will be **imported StreamTexture (`.stex`) files in the `res://.import/` folder**.

**Comment by nightrobin** [comment]
> As I said, there will not be original PNGs in the PCK, there will be **imported StreamTexture (`.stex`) files in the `res://.import/` folder**. They should be referenced in the `.import` file like this:
> 
> ```
> [deps]
> 
> source_file="res://art/intro_alpaca.png"
> dest_files=[ "res://.import/intro_alpaca.png-db73ae36df3f82283e5eefd167c037a8.stex" ]
> ```

Ok, that is the process, so how would you load the texture? 
Do I have to parse/regex the content of the .import file?
I think this parsing/regex is too much hassle instead being straightforward.

I did that regex method but I am stopped by this error:
get_as_text: File must be opened before use.
The file I am reading is the .import file

var dlcimage = File.new()
dlcimage .open("res://Assets/dlc/Image1.png.import", File.READ)
var content = dlcimage .get_as_text()
dlcfile.close()

Do you have any alternative workaround?

**Comment by akien-mga** [comment]
No, as I mentioned the paths are automatically remapped: https://github.com/godotengine/godot/issues/39746#issuecomment-647376255

So you simply do:
```
var tex = load("res://Assets/dlc/Image1.png")
```
and it will load the `.stex` automatically.

**Comment by akien-mga** [comment]
See https://docs.godotengine.org/en/stable/getting_started/workflow/assets/import_process.html for documentation on the import process.

It lacks some details about what is discussed above, so I opened https://github.com/godotengine/godot-docs/issues/3718 so that it can be clarified.
