### ISSUE TITLE
Arm64v8 export not installing on Android 9 phone with a Cortex A53 processor 

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#39742]
**Godot version:**
3.2.2 RC2 Mono

**OS/device including version:**
LG K50S with a Cortex A53 processor running Android 9 pie

**Issue description:**
When I export a 64 bit apk I can't install it, if I try to install it from adb I get a no matching abi error, but the processor uses 64 bits instructions, it installs fine on my old phone, but for some reason it doesn't work on the LG k50S.

**Steps to reproduce:**
Export a 64 bit only apk and try it on a similar device.

Edit: ~~Doing some quick research I found out that this processor uses the ARMv8-A instruction set which is not the same as Arm64v8a.~~ Never mind, I think I got confused, I didn't find anything in developer.arm.com.

**Comment by akien-mga** [comment]
Can you confirm that the exported APK contains the arm64-v8a `.so` library? You should be able to explore the APK with a ZIP tool (`unzip`, IZArc, etc.).

**Comment by MightyPrinny** [comment]
Yes the libraries are there and the apk can be installed on my old phone.
This is the error I get from adb:
adb: failed to install /home/Fabian/Documents/Godot/Exports/CarsOnTracks/CarCrasherxARMv8x64Debug.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

Sadly I couldn't find anything useful with logcat while I was installing the apk from the phone, it just says app not installed.

**Comment by MightyPrinny** [comment]
I downloaded droid info and it says the processor uses the ARMv7 architecture, I guess the hardware info online is wrong, the processor maybe isn't a cotext a53 and the lg page doesn't specify which processor the phone is using.
