### ISSUE TITLE
Set Mouse Mode is apparently calling Input Event Mouse

### ISSUE THREAD

**Issue by Migzus** [godotengine/godot#39752]
**Godot version:**
3.2.1 Stable

**OS/device including version:**
GLES2, GLES3
Windows 10
It works fine on Linux systems (Ubuntu through VirtualBox)
(I have not tested it on Mac)

**What was attempted:**
I am trying to make a title screen where you can use the arrow keys to move between the buttons or use the mouse on the buttons. When using the arrow keys, I want the mouse cursor to be hidden, and the opposite when I start to use the mouse.

**Issue description:**

When pressing any key it gives off a proper KeyEvent signal, however; it also shoots two MouseEvent calls, both of type MouseMotion (When using set_mouse_mode). It still happens even if you hold down any key. 
However, when plugging in a controller and using the joypads' movement instead of mouse movement; it works as expected.
It appears that *set_mouse_mode* is what's causing this issue.
What is interesting is that when the mouse cursor is inside the window the bug occurs, but when you move the mouse cursor outside the window, it works as expected.

It can be replicated in C# as well.

**Steps to reproduce:**
Simply, create a new project. Then, create a GDScript and write in the _input function, checking if the incoming event type is InputEventMouse. If true, then set the mouse mode to visible. Then create a new if statement and check if event is InputEventKey. If true, then set mouse mode to hidden.
You can visually see the cursor flicker on the screen when trying to press any key, but print the event to the output for a more clear result.

**Minimal reproduction project:**

[Godot Bug.zip](https://github.com/godotengine/godot/files/4812667/Godot.Bug.zip)

**Comment by akien-mga** [comment]
Is this fixed?

**Comment by Migzus** [comment]
Yes. The bug was fixed a while ago. (In Godot 3.2.2)
Just noticed that I forgot to close the issue.
