### ISSUE TITLE
InputMap::action_erase_event doesn't actually work

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#3976]
**Operating system or device:**

Arch Linux (and again, should work on other platforms the same)

**Issue description** (what happened, and what was expected):

I used `InputMap::action_erase_event` to try to make rebinding of event (e.g. I would delete the old event, and add a new one). Unfortunately, it didn't do anything at all, so I had to fall back to erasing the whole action and making it anew.

**Steps to reproduce:**

- **A:** Call `InputMap::action_erase_event`, and see it doesn't disable the event.
- **B:**
  - Clone https://github.com/bojidar-bg/top-down-inertia/
  - Run `git checkout 3ed677089325371f4053cf11ba776594c54a772d`
  - Comment out lines 96 to 98 in https://github.com/bojidar-bg/top-down-inertia/blob/3ed677089325371f4053cf11ba776594c54a772d/main/save_manager.gd#L96-L98
  - See that rebinding of actions preserves the old event too.

**Link to minimal example project** (optional but very welcome):
https://github.com/bojidar-bg/top-down-inertia/ -- But follow the instructions above to disable the workaround.

Cross-ref: http://godotengine.org/qa/916/how-to-use-inputmap-action_erase_event

**Comment by Hinsbart** [comment]
The function checked whether the event exists for the action but then just returned. It only tried to erase the event when the action didn't have it

**Comment by bojidar-bg** [comment]
@Hinsbart ~ Thanks for looking into this issue!
