### ISSUE TITLE
Removing an Area that overlaps with an object from the tree triggers "exited", but adding it back in doesn't trigger "entered" nor detects the overlap

### ISSUE THREAD

**Issue by MikeFP** [godotengine/godot#39765]
**Godot version:**
3.2 Stable

**OS/device:**
Windows 10

**Issue description:**

When removing an Area that's inside another Area/Body from the tree, it triggers the "exited" signal and stops overlapping, which is expected. However, when adding it back in a position that supposedly overlaps with that same object, no signal is fired, and the get_overlapping_bodies/areas() stays empty.

**What was attempted:**

I tried instancing the Area at runtine and adding it in the desired position, and it works fine, although that's not my use case. I also noticed that the problem doesn't happen if the Area isn't overlapping with the object before removing it from the tree.

**Example Project:**

I set up a scene that instances a small Area inside a bigger Area, reparents the smaller Area while keeping them overlapping and prints some results. Here's the project:

[Area Issue Project.zip](https://github.com/godotengine/godot/files/4815460/Area.Issue.Project.zip)

**Comment by akien-mga** [comment]
Confirmed in 3.2.2 RC 3.

Took me a while to understand what the problem is though, so to clarify, the current / wrong output of the example project is:
```
area1 is in
yay it overlaps!!
reparenting inside
area1 is out
starting to move away
supposedly exited
reparenting outside
area1 is in
yay it overlaps!!
area1 is out
```

It should be something like:
```
area1 is in
yay it overlaps!!
reparenting inside
area1 is out
--> area1 is in
--> yay it overlaps!!
starting to move away
--> area1 is out
supposedly exited
reparenting outside
area1 is in
yay it overlaps!!
area1 is out
```
