### ISSUE TITLE
the Export path not works when Export PCK/Zip 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#39769]
**Godot version:**

3.2.1

**OS/device including version:**

macOS 10.15.5

**Issue description:**

When click Export PCK/ZIP, the default directory is the project root directory, not the Export Path.

And the Export with Debug Checkbox is always checked on.

**Steps to reproduce:**
Create a project
do export for any platform
close the project
reopen the same project
 click Export PCK/ZIP
 the default directory is not the export path and the Export with Debug  is always on.

Without restarting the project,these options are recorded on export.
 

**Minimal reproduction project:**

<img width="737" alt="Screen Shot 2020-06-23 at 9 45 01 AM" src="https://user-images.githubusercontent.com/1130047/85351765-10542480-b537-11ea-9fdc-ff46bb5922d2.png">

<img width="1079" alt="Screen Shot 2020-06-23 at 4 33 25 PM" src="https://user-images.githubusercontent.com/1130047/85380548-a310b580-b56f-11ea-9e1a-c5c30600b77c.png">

**Comment by mrushyendra** [comment]
The following change would fix the issue:
```
--- a/editor/project_export.cpp
+++ b/editor/project_export.cpp
@@ -876,6 +876,18 @@ void ProjectExportDialog::_tree_changed() {
 }
 
 void ProjectExportDialog::_export_pck_zip() {
+       Ref<EditorExportPreset> current = get_current_preset();
+       ERR_FAIL_COND(current.is_null());
+
+       String p_path = current->get_export_path();
+       if (p_path != "") {
+               int pos = MAX(p_path.find_last("/"), p_path.find_last("\\"));
+               if (pos != -1) {
+                       String dir = p_path.substr(0, pos);
+                       export_pck_zip->set_current_dir(dir);
+               }
+       }
        export_pck_zip->popup_centered_ratio();
 }
```
Before submitting a PR, I wanted to confirm what the expected behavior should be. Right now the code seems to explicitly use the export path only for the general `Export` case,  and intentionally ignores the path for the `Export PCK/ZIP` case. Is there a reason for this?

In fact, currently the Export Path is not a directory, but must be a specific file ending with the appropriate extension, e.g. `.x86-64`. To show the same folder when exporting as PCK/ZIP requires a slightly-hackish behavior to parse the file directory out from the entire path as shown above.

**Comment by alexzheng** [comment]
Take iOS export for example,
the work flow would be:

1.export the Xcode project
2.do some custom settings to the project
3.run the Xcode  project on device
4.do some modification in Godot Project
5.export  PCK/ZIP to update the Xcode project

then loop 3 - 4- 5

It would be expect the PCK/ZIP export path alway the same as the Xcode project root directory.

**Comment by alexzheng** [comment]
@mrushyendra
 How about this issue?
It's quite time consuming to reselect the directory each time when update the PCK file.

**Comment by alexzheng** [comment]
@mrushyendra
I have tested the above code, it works, please commit it. Thanks.
