### ISSUE TITLE
It's really hard to tell if the Flip Option is on or off for Tilemap 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#39770]
**Godot version:**

3.2.1

**OS/device including version:**

macOS 10.15.5

**Issue description:**

When the tiles are symmetry, it's impossible to tell the status of the Flip Horizontally and Flip Vertically Buttons.
These buttons should have different icons for on and off.

**Steps to reproduce:**

**Minimal reproduction project:**

<img width="328" alt="Screen Shot 2020-06-23 at 10 00 10 AM" src="https://user-images.githubusercontent.com/1130047/85352600-ee5ba180-b538-11ea-9444-b44a5fbb7220.png">

**Comment by groud** [comment]
They are not status, they are actions. Those buttons were status before and thus had status indication, but they were removed as they were confusing. Considering the a 180 degree rotation is equivalent to both an horizontal and a vertical mirror, it made things confusing when two rotations would cause the symmetry indicators to turn on when you rotated the tile.

You can know if a sprite is not in it's default transform if the "clean" action on the right is available. So on your example, there is no symmetry active.

**Comment by groud** [comment]
Closing as this enhancement is no more needed on master branch, as you cannot flip tiles directly in the TileMap anymore.
