### ISSUE TITLE
Crash on Android, throws "Fatal signal 11 (SIGSEGV), code 1, fault addr 0x40 in tid 27210 (GLThread 1517)"

### ISSUE THREAD

**Issue by CenTdemeern1** [godotengine/godot#39777]
I'm having an issue where I load a level scene, and it throws.
I'll add my log file in the next comment

**Comment by akien-mga** [comment]
Please don't remove the issue template when opening an issue. The information we ask is the minimum we need to be able to do anything.

**Comment by CenTdemeern1** [comment]
[log.txt](https://github.com/godotengine/godot/files/4818305/log.txt)

**Comment by CenTdemeern1** [comment]
Um, I didn't remove anything

**Comment by CenTdemeern1** [comment]
It just flat out didn't give me a template

**Comment by CenTdemeern1** [comment]
Could you send the template so I can fill it in?

**Comment by akien-mga** [comment]
That's weird, when you open an issue it should contain this initially:
```
<!-- Please search existing issues for potential duplicates before filing yours:	
https://github.com/godotengine/godot/issues?q=is%3Aissue	
-->

**Godot version:**
<!-- Specify commit hash if using non-official build. -->


**OS/device including version:**
<!-- Specify GPU model, drivers, and the backend (GLES2, GLES3, Vulkan) if graphics-related. -->


**Issue description:**
<!-- What happened, and what was expected. -->


**Steps to reproduce:**


**Minimal reproduction project:**
<!-- A small Godot project which reproduces the issue. Drag and drop a zip archive to upload it. -->
```

**Comment by CenTdemeern1** [comment]
Potential duplicate:
https://github.com/godotengine/godot/issues/18252

**Godot version:**
3.2.1.stable


**OS/device including version:**

Microsoft Windows NT Version 10.0.18363.900 running on an Intel Core i3 and integrated graphics,
I'm using GLES3.
My Android device is a Lenovo K6 (K33a48) running Android 7.0, with security patch level "November 1st 2017", build number K33_S231_171114_ROW, with an 8-core MSM8937 processor clocked at 1.4GHz. Has 2 Gigs of RAM and 16 GB of internal storage.

**Issue description:**
I expected my level (my scene) to load, or at least, everything but a crash exclusive to android.
(on Windows everything works fine)


**Steps to reproduce:**
Run the project on Android. Click the button on the temporary main menu that reads "beam me up Scotty" and it will throw you into the main menu. Select level 1 or 2 (3 and 4 haven't been made yet) and just click play. After loading, it throws.


**Minimal reproduction project:**
Sadly I can't make a "small reproduction project" because of my deadline (it's the 26th). After that, I'll be able to make one. I can provide the complete project, but that takes up "some space", so to say.

**Comment by CenTdemeern1** [comment]
I really need to work fast because of that deadline

**Comment by akien-mga** [comment]
The most likely issue is that your device's OpenGL ES 3.0 drivers are buggy, which is a common problem on phones from this generation with chipsets like this one (Adreno 505).

That's the main reason why we developed an OpenGL ES 2.0 backend to support lower end Android devices without OpenGL ES 3.0 support, or with an unreliable implementation.

So switching your project to the GLES2 backend should likely fix the issue.

**Comment by CenTdemeern1** [comment]
I'll try that!

**Comment by CenTdemeern1** [comment]
Thanks, switching to GLES2 solved the issue. Sadly my application doesn't seem to work right on GLES2 so I guess that's no Android support for me

**Comment by CenTdemeern1** [comment]
(for example, some things just don't show up)

**Comment by CenTdemeern1** [comment]
And touch input also doesn't work. Anyway, the issue is solved, I guess.

**Comment by akien-mga** [comment]
You might need to do some changes to your application as GLES3 and GLES2 have slight differences. See https://docs.godotengine.org/en/stable/tutorials/misc/gles2_gles3_differences.html for some documentation.

But unless your application was using very high end 3D features from GLES3 (e.g. GIProbe), it should be fairly easy to get it working with GLES2.

**Comment by CenTdemeern1** [comment]
It's not using those features, and it's not working. Might create an issue or something later.

**Comment by akien-mga** [comment]
Make sure to review the texture import settings: https://docs.godotengine.org/en/stable/tutorials/misc/gles2_gles3_differences.html#texture-compression

For Android with GLES3, textures would be imported as ETC2, but for GLES2, you need ETC.
So in the project settings you should enable `rendering/vram_compression/import_etc` and (optionally) disable `rendering/vram_compression/import_etc2`.

**Comment by CenTdemeern1** [comment]
That didn't fix my issues, as I've already enabled both
