### ISSUE TITLE
Code completion is wrong after opening first bracket

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3977]
**Issue description** (what happened, and what was expected):
When starting to type a function name, it works as expected:
![spectacle tq4578](https://cloud.githubusercontent.com/assets/4701338/13577440/c1a777ac-e492-11e5-8c72-87ce9d8be985.png)

But once the function name is complete, and the bracket is opened (by typing it only, pressing tab to finish the call works ok), then instead of just showing the call hint, it should the global scope functions again, which is bogus. Pressing tab will cause it to write the function name twice.
![spectacle jh4578](https://cloud.githubusercontent.com/assets/4701338/13577395/91210968-e492-11e5-96a9-10e17220630c.png)

**Steps to reproduce:**
As shown above.

It might be a regression of #3910 (@chuckeles).

**Comment by akien-mga** [comment]
> It might be a regression of #3910 (@chuckeles).

It is not, I have the same bug in 2.0 actually (but the call hint is shown on top of the code completion list, so the bug was less obvious maybe).

**Comment by akien-mga** [comment]
Also the bug happens when a method has no auto-completion match (if it has some, then the bug will appear for a fraction of second, and then the auto-completion proposals will be shown).

**Comment by chuckeles** [comment]
In #3910 I just moved the call tip and hidden it when in the way, I did not alter the behaviour of the code completion.

**Comment by akien-mga** [comment]
Bumping this one up (e.g. for @Paulb23 ;)) as this bug is pretty annoying. It's likely the main reason why we still get complaints about "missing" hints as in #4569, as you don't get the hint unless you autocomplete a hinted method name with Return.
