### ISSUE TITLE
Add option to disable margin change when anchors change

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#3979]
Currently, when changing the anchors of a `Control` node, its margins would be changed as to keep the same size and position. To me, this is rather uncomfortable, as I like things to be positioned with "mathematical" precision.

Ideally, there should be some editor setting, that would control if margins are changed when anchors are.

**Comment by YeOldeDM** [comment]
:+1: because bogidar-bg told me to. And it seems important.

**Comment by bojidar-bg** [comment]
@neikeq ~ I think you can add "junior job" too, since it doesn't seem too hard to do to me :smile:

**Comment by akien-mga** [comment]
Then you're on @bojidar-bg :)

**Comment by bojidar-bg** [comment]
@akien-mga ~ I knew it!
