### ISSUE TITLE
Error when changing scene with HTML canvas with id other than "canvas"

### ISSUE THREAD

**Issue by bsmaran** [godotengine/godot#39808]
**Godot version:**
Godot Engine v3.2.1.stable.official

**OS/device including version:**
Linux Fedora 32, 64 bits
NVIDIA Corporation, GeForce 8400Gx/PCle/SSE2

**Issue description:**
If you generate the game to HTML and create a canvas with an id other than "canvas" you will only be able to load the first scene of the game. The next scenes will not be able to load.

**Steps to reproduce:**
1) Generate the game to HTML
2) Edit the index.html file and change the canvas id to, for example, "canvasGame"
3) Change the following statement in javascript
var canvas = document.getElementById('canvasGame');
4) Save the changed file
5) Open the changed HTML page in a web browser
6) Trigger commands that change the game scene
7) Result: it will only open the initial scene but will not load the other scenes.

**Minimal reproduction project:**
[BugCanvas.zip](https://github.com/godotengine/godot/files/4827340/BugCanvas.zip)

The attached project will be useful to reproduce the error.
The index1.html page works correctly.
The index2.html page only loads the opening scene.
The index2.html page has been changed in the canvas id.

**Comment by Faless** [comment]
Yeah, the canvas ID must be `canvas` in the current released version. This will be fixed by #39604 .

**Comment by akien-mga** [comment]
Fixed by #39604.
