### ISSUE TITLE
C# files are not deleted properly from Projects

### ISSUE THREAD

**Issue by steevLP** [godotengine/godot#39809]
**Godot version:**
Godot Mono Version 3.2.1

**Issue description:**
The c# files even if they are deleted still are beeing detected as present because they dont get removed out of the `.csproj` file of the project

**Steps to reproduce:**
create a c# file and delete it again

**Minimal reproduction project:**
i have nothing code related to show here just create a c# file in godot and remove it again and then have a look in the `.csproj` file of that project

**Comment by Calinou** [comment]
This was fixed in the 3.2.2 betas: https://github.com/godotengine/godot/pull/37149
