### ISSUE TITLE
MacOS CMD+Click does not open documentation

### ISSUE THREAD

**Issue by dncnmckn** [godotengine/godot#39823]
**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
MacOS 10.15.5 / MacBook Pro (retina), 15" Early 2013

**Issue description:**
CMD + Click on code should open relevant part of documentation. On PC CTRL + Click does it.

**Steps to reproduce:**
Open Script. find command like func, press CMD + Click, func gets a line under it, click it, nothing happens.
[godot mac bug.zip](https://github.com/godotengine/godot/files/4830019/godot.mac.bug.zip)

**Minimal reproduction project:**
[godot mac bug.zip](https://github.com/godotengine/godot/files/4830019/godot.mac.bug.zip)

**Comment by Calinou** [comment]
This should be fixed in 3.2.2 RCs by https://github.com/godotengine/godot/pull/38649. Give 3.2.2rc4 a try:https://godotengine.org/article/release-candidate-godot-3-2-2-rc-4

**Comment by dncnmckn** [comment]
Nope, sorry. Downloaded the [Classical Build](https://downloads.tuxfamily.org/godotengine/3.2.2/rc4/) from that link and opened same file. Still no cmd + click go-to definiton.

**Comment by akien-mga** [comment]
The relevant code should be in `scene/gui/text_edit.cpp` (search for "symbol_lookup" and "highlight").

**Comment by name-here** [comment]
CMD + Click seems like it works to me, including going to the definition for user-defined functions, and going to the relevant documentation for non-user-defined functions.  Probably unsurprisingly, though, it can't find user-defined function definitions where the type is not determined until runtime (like calling functions on objects added to an array at runtime).

**Comment by AnantAhuja** [comment]
I didn't even know it was a feature but CMD + Click is working for me as well, it opens the docs and if clicked on a user defined function, the cursor jumps to the function definition.

**Comment by dncnmckn** [comment]
It's definitely CMD + Right Click on MacOS trackpad, right?

**Comment by Calinou** [comment]
@dncnmckn The cursor should turn into a pointer icon when you hold the right key while hovering a clickable reference. The text will also be underlined when doing so.

**Comment by dncnmckn** [comment]
It does this when I click on it.

![cmd + click](https://user-images.githubusercontent.com/5285423/85865278-8c5f9e00-b7bd-11ea-99dc-bf8c47ed10fe.gif)

**Comment by Calinou** [comment]
@dncnmckn I think keywords aren't supposed to be clickable. They're still highlighted though, but I think that's been already reported.

**Comment by dncnmckn** [comment]
That makes sense. I'll close the issue. Thanks for the help!
