### ISSUE TITLE
Arrays are not unique when initialized in the same scope

### ISSUE THREAD

**Issue by ben-humphries** [godotengine/godot#39828]
**Godot version:**
master branch, commit 75c91707a4a8b3844746c3cf21a8a767c16da79d

**OS/device including version:**
OS: Windows 10 Home, Version 10.0.18362 Build 18362
System Type:	x64-based PC
Processor:	Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz, 3801 Mhz, 4 Core(s), 4 Logical Processor(s)

**Issue description:**
When initializing a Packed[x]Array, it will be equal to another Packed[x]Array if initialized in the same scope (The objects both reference the same array).

**Steps to reproduce:**
Initialize any two Packed[x]Arrays together, append values to either of them, and they will contain the same values.

**Minimal reproduction project:**
[Array Issue Test Project.zip](https://github.com/godotengine/godot/files/4831868/Array.Issue.Test.Project.zip)

**Comment by jkirsons** [comment]
> Does any of this occur in 3.2.2?

No, only 4.0 (master)

**Comment by S0yKaf** [comment]
The same issue also happens with Arrays inside resources in 3.5 stable.

**Comment by wenqiangwang** [comment]
I tested the two repros above with Godot 4.0 RC2 and it seems they are all fixed.
