### ISSUE TITLE
Texture.get_data() cause error when use custom viewport, result in can not capture my mesh thumbnail.

### ISSUE THREAD

**Issue by wijat** [godotengine/godot#39834]
**Godot version:**
v3.2.1 stable.official

**OS/device including version:**
Win 10, GLES3

**Issue description:**
Create a viewport node in world, then call **viewport.get_texture().get_data()**
It show this error:
ERROR: create: Index p_width - 1 = -1 is out of bounds (MAX_WIDTH = 16384).
   At: core/image.cpp:1598
![screenshot_2020_06_26](https://user-images.githubusercontent.com/8220843/85788255-44119300-b75f-11ea-8604-0aafba0e32fe.png)
Then, have no image data!

**Steps to reproduce:**
Create a viewport node in world, then call **viewport.get_texture().get_data()**

**Minimal reproduction project:**
[bugy_godot.zip](https://github.com/godotengine/godot/files/4833484/bugy_godot.zip)

**Comment by name-here** [comment]
Your Viewport size is 0 by 0.  If set to, for example, 1024 by 600, the project works.

**Comment by wijat** [comment]
> 
> 
> Your Viewport size is 0 by 0. If set to, for example, 1024 by 600, the project works. The error could be more helpful and clear, though.

Now I try to set it in code, it just no use! But it can work in editor set up. It is a trap! Take me hours!

**Comment by Calinou** [comment]
You may have to wait for 1-2 idle frames before you can capture the viewport data after changing its size. You can do this using `yield(get_tree(), "idle_frame")`.
