### ISSUE TITLE
Android Plugin Method Parameter Problem

### ISSUE THREAD

**Issue by cagdasc** [godotengine/godot#39838]
**Godot version:**
3.2.2.rc3

**Issue description:**
If I create plugin and method with parameters in this plugin class, Godot can not find my method. It gives `java.lang.NoSuchMethodError: no non-static method`. If I create method without parameters or with String type parameter, everything works fine. My class defition like below.

```
public class LocationPlugin extends GodotPlugin {
// constructor definition is ok.

    @NonNull
    @Override
    public List<String> getPluginMethods() {
        return Arrays.asList(
                "startLocationUpdates"
        );
    }

    @NonNull
    @Override
    public String getPluginName() {
        return "AndroidLocationPlugin";
    }

    public void startLocationUpdates(long interval, long maxWaitTime) {
      //method body
    }
```

__Exception:__
```
 java.lang.NoSuchMethodError: no non-static method "Lcom/cacaosd/plugin/LocationPlugin;.startLocationUpdates(Ljava/lang/Object;Ljava/lang/Object;)V"
        at org.godotengine.godot.plugin.GodotPlugin.nativeRegisterMethod(Native Method)
        at org.godotengine.godot.plugin.GodotPlugin.onRegisterPluginWithGodotNative(GodotPlugin.java:136)
        at org.godotengine.godot.Godot$2.run(Godot.java:351)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1502)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

__GDScript:__
```
if Engine.has_singleton("AndroidLocationPlugin"):
	var singleton = Engine.get_singleton("AndroidLocationPlugin")
	singleton.startLocationUpdates(6000, 10000)
```

**Comment by m4gr3d** [comment]
@cagdasc I'm looking into the issue, but it's related to how the logic handles `long` types. In the meantime, you can switch to using `int` types as a workaround.

**Comment by cagdasc** [comment]
@m4gr3d I will try today, if it will work, my next step is emit signal with float parameters. There is another thing, if I define my method parameters with Object type, there is no runtime error but it crahes because godot passes null. I will share results. Thank you.

**Comment by m4gr3d** [comment]
@cagdasc That behavior is expected and it is a current limitation.
For now only the following types can be used in the plugin: `void`, `boolean`, `int`, `float`, `java.lang.String`, `org.godotengine.godot.Dictionary`, `int[]`, `byte[]`, `float[]`, `java.lang.String[]`.

@akien-mga It's probably not worth blocking the `3.2.2` release for this issue as long as we list the current type limitations in the documentation. We can look into how to expand the range of supported types in the next releases.

**Comment by cagdasc** [comment]
@m4gr3d everything is OK. Thank you.
