### ISSUE TITLE
3D model imported with wrong colors

### ISSUE THREAD

**Issue by matheusmdx** [godotengine/godot#39843]
**Godot version:**
Godot 3.2.1 stable

**OS/device including version:**
Windows 10 1909
Intel i7 2600
GTX 1060 3 gb with 451.48 driver
8 gb ram

**Issue description:**
When i import my 3d model from blender to godot, colors dont look the same, i'm using blender 2.83

In blender:
![Captura 1593137006 23-03-26 25-06-2020](https://user-images.githubusercontent.com/44306054/85813629-182fe680-b73a-11ea-82a7-a51ca72fd559.png)

In godot:
![Captura 1593136980 23-03-00 25-06-2020](https://user-images.githubusercontent.com/44306054/85813627-17975000-b73a-11ea-8405-6805edeae948.png)

**Steps to reproduce:**
Open glb file or fbx file and compare with image provided above

**Minimal reproduction project:**
[blender project.zip](https://github.com/godotengine/godot/files/4834749/blender.3d.project.zip)
[3d model test.zip](https://github.com/godotengine/godot/files/4834750/3d.model.test.zip)

**Comment by Zireael07** [comment]
You have an environment (the blue sky) that provides lighting, and that environment lighting is blue-ish. And I suspect your gun is mostly metallic, so it reflects the blue-ish light.

**Comment by JohanAR** [comment]
I could be wrong but I think your problem is that you try to use a Glossy BSDF material which isn't supported by Godot's default shader. If you change your materials in Blender to Principled BSDF it might work better.

**Comment by matheusmdx** [comment]
> 
> 
> I could be wrong but I think your problem is that you try to use a Glossy BSDF material which isn't supported by Godot's default shader. If you change your materials in Blender to Principled BSDF it might work better.


Yes, i am using this one because it combined more with what i wanted but sadly it's not supported, the way is to wait for version 4.0 to see if it will support these shaders. Thanks for the info.

**Comment by fire** [comment]
Not sure if this is a good path, but I tried solving this. 

https://github.com/godotengine/godot/pull/38438
