### ISSUE TITLE
"Close and save changes?" doesn't actually save changes

### ISSUE THREAD

**Issue by DanielZTing** [godotengine/godot#39844]
**Godot version:**

v3.2.1.stable.official

**OS/device including version:**

MacBookAir8,1
macOS Catalina 10.15.5 (19F101)

**Issue description:**

If you attempt to close an unsaved script, Godot presents a warning dialog. However, clicking "Save" doesn't actually save.

**Steps to reproduce:**
1. Create a new project
2. Right click in FileSystem and choose New Script...
3. Edit script e.g. put a print("DEBUG") in _ready()
4. Right click on script name and choose Close
5. Click "Save" on the confirmation dialog
6. Open the script outside of Godot, nothing has changed!

**Minimal reproduction project:**

**Comment by lightspot21** [comment]
I can reproduce this on latest `master`, aka `b92477d77` as of this comment. Running on Manjaro 20.0.3.

**Comment by jonbonazza** [comment]
OOF.
