### ISSUE TITLE
Add option to preserve aspect ratio in TextureFrame/UI image elements

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#3984]
There is an option to expand the image according to the width and height, but there is no option to preserve aspect ratio while expanding. It'd be nice to add one.
![screenshot from 2016-03-08 19 41 36](https://cloud.githubusercontent.com/assets/434987/13603856/30e8c0fc-e566-11e5-8a55-edb502d3b9f0.png)

**Comment by volzhs** [comment]
you can do it by <kbd>shift</kbd> + drag.

**Comment by vinod8990** [comment]
I was talking about dynamic sizing with its parent.

An example scenario: I have a box centered on the screen with its anchors set to begin and end so that it stretches according to the device screen. If we put a TextureFrame inside and set it to expand, the image will expand according to its parent dimensions. But if another device has a different aspect ratio, the stretched parent dimension will change and this image will also be stretched/squeezed.

I experienced this while I am doing a virtual joystick which has to be nicely scaled among all screens but at the same time, I don't want to stretch the images.

**Comment by vinod8990** [comment]
I believe this can be closed, in 2.1 there are options for keeping the aspect, 
However not for texture button

**Comment by bojidar-bg** [comment]
Well, do we need those settings on texturebutton as well?

**Comment by vinod8990** [comment]
It will be good of these are available for texture buttons too. The hit area should be the texture area which is displayed.

**Comment by KoBeWi** [comment]
Implemented since 3.0
