### ISSUE TITLE
Android Plugin v1 Kotlin Signal Args Problem

### ISSUE THREAD

**Issue by cagdasc** [godotengine/godot#39857]
**Godot version:**
3.2.2.rc3

**Issue description:**
I write a plugin with Kotlin and having a problem about signal parameter types. If I want to give `Float` as a parameter for signal definition, I give `Invalid type for argument #0. Should be of type float` error, same as `Int` type but not `String`. There is no problem with Java but I want to write my plugin with Kotlin. Are there any workarounds for this? Thank you.

```
private val locationSignal = SignalInfo("onLocation", Float::class.java, Float::class.java)

public fun someFunc() {
     val longitude: Float = ...
     val latitude: Float = ...
     emitSignal(locationSignal.name, longitude, latitude)
}
```

**Comment by m4gr3d** [comment]
@cagdasc Try to use `Float.javaClass` instead.

**Comment by cagdasc** [comment]
@m4gr3d I tried that and result is same.

**Comment by cagdasc** [comment]
I found a workaround but not efficient. If I pack values into a `Dictionary`, it will work.

**Comment by m4gr3d** [comment]
@cagdasc Figure it out - for kotlin you have to use `Float::class.javaObjectType` (same thing for `Int` and other supported primitives)

**Comment by cagdasc** [comment]
@m4gr3d It works. Thank you.
