### ISSUE TITLE
return in shader results in unexpected behaviour

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#39863]
**Godot version:**
3.2.2

**OS/device including version:**
GLES3
Windows 10 1903
Intel HD 4000

**Issue description:**
`return`in shader results in unexpected behaviour.

![bug](https://user-images.githubusercontent.com/14185889/85902198-c2277580-b803-11ea-9c82-91e290e197df.gif)

**Steps to reproduce:**
1. Add Sprite
2. Add ShaderMaterial to Sprite
3. Add Shader to ShaderMat
4. Write:
```glsl
void fragment() {
	COLOR = vec4(1.0);
	return;
}
```

**Minimal reproduction project:**
[shader_bug.zip](https://github.com/godotengine/godot/files/4839287/shader_bug.zip)

**Comment by clayjohn** [comment]
This is exactly what I would expect to happen.

``return`` exits the function immediately so the rest of the shader is never run and nothing gets written by the fragment shader. What you are seeing is random memory.

I guess we could throw an error when users try to use ``return`` in processor functions. 

@Chaosus Would it be hard to detect when ``return`` is used inside a processor function and to throw an error?
We could say something like "using 'return' in a processor function causes the shader to exit before writing values, leading to unexpected results."

**Comment by Chaosus** [comment]
@clayjohn I think it's easy and I can make it

**Comment by HaSa1002** [comment]
Okay, I learned something. It never came to my mind, that return in the main functions exits the whole shader and not only the processing thread. I think it could perhaps also mentioned in the documentation.
