### ISSUE TITLE
(concept mockup) new gizmo controls

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3986]
I was fooling around with new ideas for Godot gizmo and came up with this.

A new xy yz zx plane controls. The colors are a blend of the two axis they are made up of (purple, teal, yellow). These controls appear only when transform controls are turned on.

There is also a center diamond control. If you double click on it it will focus on the object. 

![new_gizmo](https://cloud.githubusercontent.com/assets/6987027/13608507/164ef3ee-e523-11e5-9c09-b558747944c1.png)

**Comment by reduz** [comment]
looks nice!

**Comment by zendorf** [comment]
And don't forget widget scaling controls :)

**Comment by unfa** [comment]
I especially like the plane handles!

**Comment by quantum-entangler** [comment]
if you click-drag on the central diamond control I take it drags along view-plane?

**Comment by akien-mga** [comment]
Fixed by #10743.
