### ISSUE TITLE
"windows" platform not detected on msys2

### ISSUE THREAD

**Issue by MichaelBelousov** [godotengine/godot#39866]
Installed `python` (pacman package version 3.8.2-1) (python version 3.7.4) for compiling the editor in windows 10, and received the following on `scons p=windows`:

```bash
$ cd godot && scons -j8 p=windows mono_prefix=/c/Program\ Files/Mono use_mingw=yes werror=no tools=yes module_mono_enabled=yes mono_glue=no
scons: Reading SConscript files ...
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Invalid target platform "windows".
The following platforms were detected:

        server

Please run SCons again and select a valid platform: platform=<string>
make: *** [Makefile:61: godot-engine] Error 255
```

Python env details:
```bash
$ python -V
Python 3.7.4
$ python -c "import os; print(os.name)"
posix
$ python -c "import sys; print(sys.platform)"
msys
```

**Comment by clayjohn** [comment]
Did you install Visual Studio or MinGW-64?

**Comment by MichaelBelousov** [comment]
Mingw64 via msys. But I also installed the visual studio build tools.

**Comment by clayjohn** [comment]
Did you make sure one (or both) were added to your PATH? It looks like scons isn't detecting them.

**Comment by MichaelBelousov** [comment]
Well it's a good point that I didn't restart after installing VS (but I did restart the shell) so vsts probably isn't in my path, but I made sure msys64/mingw64/bin was in my path

**Comment by MichaelBelousov** [comment]
I am looking to compile using msys2+mingw64 specifically though, not VS, I'm testing a mingw64 specific patch for a the DreamWorks redistributables

**Comment by MichaelBelousov** [comment]
I think I may have installed the wrong gcc package, and was confused by a cursory glance at the SConstruct code referencing win32 and nt sys.platform and os.names, (which on my other msys2 machine it is in fact win32 and nt in msys built python). I'm trying to confirm right now.

**Comment by MichaelBelousov** [comment]
yeah looks like that fixed it, sorry for the waste of time! Thank you!
