### ISSUE TITLE
C# VS Code says "unresolved dependencies" since .csproj und .sln chaned 

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#39874]
**Godot version:**

Godot_v3.2.2-stable_mono_x11_64

**OS/device including version:**

OS: 5.7.6-arch1-1
Mono: Mono JIT compiler version 6.4.0 
MSBuild: Microsoft (R) Build Engine version 16.5.0-ci for Mono
VSCode: 1.46.1-1 

**Issue description:**

When opening the a .cs script in VS Code it says: 
`There are unresolved dependencies. Please execute the restore command to continue.`
![Screenshot_20200627_120526](https://user-images.githubusercontent.com/60042618/85920318-fbe39500-b872-11ea-9d5d-ffa46c6c0265.png)

Running a `nuget restore` solved that problem, but that was never required in older Godot Versions < 3.2.2 . It's since the structure of the solution and project Files changed. 

Is that an issue or wanted behavior?

**Comment by neikeq** [comment]
This is wanted behaviour. Godot projects now references [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/) so it can be built without having to install Mono on Linux/macOS or the .NET Framework on Windows. It also allows building the project with the .NET Core CLI.

BTW starting with 3.2.2, Godot will run restore before building the project, so you don't have to run the command yourself, just build the project.

**Comment by JupiterRider** [comment]
Thank you for the quick respond Ignacio!
