### ISSUE TITLE
Tooltips don't show up in code editor.

### ISSUE THREAD

**Issue by nanoblit** [godotengine/godot#39877]
**Godot version:**

3.2.2

**OS/device including version:**

Windows 10 64bit

**Issue description:**

I don't see tooltips with variable types etc. in code editor.

**Steps to reproduce:**
Hover over anything in a script in code editor.

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/4840498/Test.zip)

**Comment by Calinou** [comment]
This is not a bug. There are no tooltips in the script editor yet :slightly_smiling_face:
