### ISSUE TITLE
Scaling ParallaxLayers via Script

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#3987]
**Operating system or device:**
Win 10 x64 / Ubuntu GNOME 15.10 x64

**Issue description**
It seems that applying scale on ParallaxLayers through GDScript in _ready isn't possible / doesn't work. The value is being updated (get_scale() returns the right value) but it seems like it's not updated graphically.

**Steps to reproduce:**
ParallaxBackground
- ParallaxLayer (Scale: 0.5, 0.5)
  - some Sprites
- ParallaxLayer (Scale: 0.3, 0.3)
  - some Sprites

_ready() of ParallaxBackground:

``` gdscript
func _ready():
    for i in range (get_child_count()):
        get_child(i).set_scale(Vector2(1,1))
        if (get_child(i) extends ParallaxLayer):
            var m_scale = get_child(i).get_motion_scale()

            get_child(i).scale(Vector2(1000,1000))

            print(get_child(i).get_motion_scale())
```

**Comment by mohaalak** [comment]
@timoschwarzer can you test it with set_motion_scale(vector2(1000,1000))

**Comment by timoschwarzer** [comment]
This does only change the motion scale. I want to change the transform scale.

**Comment by reduz** [comment]
ParallaxLayer does not allow you to change position and scale AFTER it was added to the scene.
this should be documented somewhere. 
Just put a node as child of it and change that node.

**Comment by reduz** [comment]
reopened and reassigned to the doc team

**Comment by vnen** [comment]
Ping @godotengine/documentation
