### ISSUE TITLE
Ysort not working on instances

### ISSUE THREAD

**Issue by jasonwolf493** [godotengine/godot#39872]
Just as the title says. If you try to use ysort on anything that is instanced it does not work. Nodes that aren't work fine. Not sure if this is a bug or a legitimate issue with ysorting an instance. I didn't see any documentation about you not being able to do this. If anything this needs to be added to the docs.

**Comment by bojidar-bg** [comment]
In my experience of using YSort, it has usually worked fine.
Would you mind sharing the Godot version and OS you are using, as well as either a list of steps which lead to reproducing the problem, or a minimal project exhibiting that problem?

The template is designed to both help users explain the bugs they hit and contributors to understand why those bugs occur. So, removing the template for bug reports helps no one.

**Comment by Calinou** [comment]
Closing per @bojidar-bg's comment. If you want this issue to be reopened, please edit the first post to follow the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to ease troubleshooting.
