### ISSUE TITLE
Transform movement arrows disappear when changing camera angle

### ISSUE THREAD

**Issue by Animatical** [godotengine/godot#39889]
**Godot version:**
3.1.1 stable win64

**OS/device including version:**
Windows 10, PC

**Issue description:**
When changing the camera angle, the transform movement arrows (As well as rotation and scale) disappear.

Example: Looking at it from this angle is fine.
![Help1](https://user-images.githubusercontent.com/64507221/85927750-09e6e500-b876-11ea-91b0-8a53eb876aad.PNG)

But when I look from this angle...
![Help2](https://user-images.githubusercontent.com/64507221/85927753-1d924b80-b876-11ea-8f4a-ffb4708fe219.PNG)

**Steps to reproduce:**
Place any object, choose the transform widget, and change the camera angle

Graphics: Intel HD graphics 620
Ram: 8Gb

Edit: After searching for this, I found a copy of this same bug. But no one has said anything since January, and it's still open.

**Comment by Zireael07** [comment]
If you found a copy, comment there - duplicates are closed.

**Comment by Animatical** [comment]
> If you found a copy, comment there - duplicates are closed.
> 
> EDIT: I assume it's a dupe of #30330?

It was a different dupe, but apparently me commenting caused it to be closed, and now #30330 is the only one I can find that isn't closed. So, I guess I can close this now.

**Comment by Calinou** [comment]
Closing per @Animatical's comment.
