### ISSUE TITLE
Visibility on Spatial overrides/cascades over children (no opt-out)

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#39882]
**Godot version:**
3.2.2.stable.mono.official

**Issue description:**
Toggling the 'Visible' property on a spatial also hides children of that node even though they have 'Visible' still toggled on. And as there's no toggle to disable nodes in general as in other engines (which implicitly hides children), there's no apparent accessible way to make a child visible but its parent invisible.
One cumbersome workaround would be to move parents to a different layer and adjust the camera's culling mask. This workaround is only feasible for games with little usage of layers and will fail silently if that invisible layer is used for different reasons later on.
It seems the editor even shares this toggle in the scenetree (eye-icons). Toggling visibility with the cascading effect there (in the editor) makes sense from a users standpoint. But ideally (as it's also used in builds) it should not cascade and the editor toggle be a separate state with overridable behaviour (see unity's hierarchy). Or alternatively the visibility just be overridable for children. Or alternatively a plain 'Active' toggle for nodes be added.

**Steps to reproduce:**
Nest 2 Spatials with something visible (geometry), toggle Visible on the parent.

**Comment by Calinou** [comment]
This isn't a bug. Please suggest features on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository after searching for possible duplicates.
