### ISSUE TITLE
BoneAttachment node does not work in one of the Skeleton bones

### ISSUE THREAD

**Issue by Leocesar3D** [godotengine/godot#39893]
Symptom: one of the BoneAttachment nodes, with red material, does not work. MeshInstance don’t follow bone movement with SkeletonIK node. It was working in Godot 3.2.1. 

Operating system: Windows 10
Godot version: 3.2.2 stable official

Steps to reproduce: run the provided minimal project in Godot 3.2.2. BoneAttachment node, in red material, does not follow bone rotation.

![GodotBoneAttachmentBug](https://user-images.githubusercontent.com/46840152/85929082-4e7b7c00-b888-11ea-81b6-26bb5e2054a8.gif)

[minimal project.zip](https://github.com/godotengine/godot/files/4841037/minimal.project.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania @TwistedTwigleg

**Comment by TwistedTwigleg** [comment]
I can confirm this is still an issue with Godot 3.2.3 Beta 1 on Linux. From what I can tell when running this project, the first bone in the SkeletonIK chain does not appear to be taken into account when solving.
