### ISSUE TITLE
tab does not display build mono, win_64, mono

### ISSUE THREAD

**Issue by wuramspaul** [godotengine/godot#39899]
Hi, I tried to start working with mono in 3.2.2, but got an unpleasant bug. In the Editor settings section, for mono the build tab did not appear.
I started looking for what the problem was, for this I rolled back to 3.2.1 and it turned out that there was a tab there, after I returned to 3.2.2 and got this:
![bug](https://user-images.githubusercontent.com/55180092/85933005-acd14a80-b8da-11ea-8d67-81d1dd8731d9.png)
But believe me, when I tried to come here initially, the tab simply did not display.
Could this be due to the fact that I have the ru_BY locale?

**Comment by KoBeWi** [comment]
This sounds like something hard to reproduce.

> Could this be due to the fact that I have the ru_BY locale?

Unlikely.

**Comment by Calinou** [comment]
@wuramspaul Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
