### ISSUE TITLE
Editor crashes when changing size of a CollisionPolygon2D in Segment Build Mode

### ISSUE THREAD

**Issue by batmanasb** [godotengine/godot#3990]
**Operating system or device:**
Linux Mint 17.3

**Issue description** (what happened, and what was expected):
When changing the size of the Polygon array in a CollisionPolygon2D, the editor crashes. Although this only happens when he CollisionPolygon2D is the child of a node inherited from PhysicsBody2D.

**Steps to reproduce:**

1. Add a StaticBody2D
2. Add a CollisionPolygon2D as it's child
3. Click on CollisionPolygon2D and set the Build Mode to Segments
4. Click the right arrow in the Polygon row, to the right of "Vector2[0]"
5. Click the up arrow in the Size row
6. Editor crashes

Note: Replacing the parent (StaticBody2D) with anything that isn't a PhysicsBody2D will prevent the crash.

**Link to minimal example project** (optional but very welcome):
Here's a little test project with steps 1 and 2 completed
[test.zip](https://github.com/godotengine/godot/files/164080/test.zip)

**Comment by neikeq** [comment]
Looks similar to #3650
