### ISSUE TITLE
Starting grid isn't placed properly when adding new scene

### ISSUE THREAD

**Issue by MiguelAtTweddle** [godotengine/godot#39918]
**Godot version:** 3.2.2-stable_win64

**OS/device including version:** Win10 Pro + GeForce 840M/PCIe/SSE2 GLES3

**Issue description:**
When adding new scene the starting grid is showing wrong. When restarting the application, it works back again.

**Steps to reproduce:** Not sure

**Minimal reproduction project:**

[Godot101_IntroTo3D(KidzCanCode).zip](https://github.com/godotengine/godot/files/4842268/Godot101_IntroTo3D.KidzCanCode.zip)

Screenshot:
![Godot_BUG](https://user-images.githubusercontent.com/26869871/85948062-d7f58180-b94e-11ea-8f31-401db312ccf8.png)

**Comment by aaronfranke** [comment]
It looks correct in the screenshot you posted, I don't see the issue.

Regardless, the grid has been overhauled for Godot 4.0, so any bugs with the grid likely don't exist anymore.
