### ISSUE TITLE
Mono Version does not Support Flags like [Export],[Signal]

### ISSUE THREAD

**Issue by steevLP** [godotengine/godot#39917]
**Godot version:**
Godot mono 3.2.2

**OS/device including version:**
Windows 10 Pro, Ryzen 3700X, Nvidia GTX1080TI

**Issue description:**
Code like this: 
`[Signal]` 
`public delegate void Hit(); `
`[Export]`
`public int Speed = 400;`
 isn't throwing any error in the debugger but none of these are beeing displayed in the inspector what they should after my level of understanding of godot.

**Steps to reproduce:**
create a c# file attach it to a node
paste these lines of code
`[Signal]` 
`public delegate void Hit(); `
`[Export]`
`public int Speed = 400;`

**Minimal reproduction project:**
[bugreport.zip](https://github.com/godotengine/godot/files/4842245/bugreport.zip)

**Comment by akien-mga** [comment]
It works fine for me. Did you compile the script? C# is a compiled language so you need to compile changes to see them in the editor.

**Comment by steevLP** [comment]
i didn't see it anywhere in the getting started section of the documentation
but after actually build it with visual studio (usually i use vscode tho) it works thank you

**Comment by akien-mga** [comment]
I opened an issue for the docs: godotengine/godot-docs#3740.
