### ISSUE TITLE
Asset library in-editor fails to load

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#39913]
**Godot version:**
3.2.2 stable

**OS/device including version:**
WIN 10

**Issue description:**
Asset Library does not load any assets, error below is printed to console.
` editor/plugins/asset_library_editor_plugin.cpp:1212 - Condition "!category_map.has(r["category_id"])" is true.
`

**Steps to reproduce:**
Open asset library and attempt to refresh.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/30642.
