### ISSUE TITLE
CSG - Visual Bug

### ISSUE THREAD

**Issue by dsuter76** [godotengine/godot#39919]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Windows 10, 64 Bit, GLES3

**Issue description:**
Visual Bugs

**Steps to reproduce:**
See Video. CSGCombiner and 2 CSGMesh's

**Minimal reproduction project:**
https://www.facebook.com/daniel.suter.96/videos/10223256216141733/

**Comment by aaronfranke** [comment]
Please provide a minimal reproduction project.

**Comment by SuperDIMMaX** [comment]
CSG has strange behavior 

![image](https://user-images.githubusercontent.com/22836285/85959350-97c0ee00-b9a4-11ea-99e5-18c8514e7bc1.png)
![image](https://user-images.githubusercontent.com/22836285/85959376-b9ba7080-b9a4-11ea-94cd-9d03ef4421eb.png)
![image](https://user-images.githubusercontent.com/22836285/85959387-d5be1200-b9a4-11ea-8065-22f9f9b36f36.png)

and 


make strange geometry
![image](https://user-images.githubusercontent.com/22836285/85959402-0605b080-b9a5-11ea-8049-f412fd2c308a.png)
![image](https://user-images.githubusercontent.com/22836285/85959445-541ab400-b9a5-11ea-9483-50b5c73f61f9.png)

I attach example
it have interesting Node - On :
![image](https://user-images.githubusercontent.com/22836285/85959855-9f35c680-b9a7-11ea-9bc6-19c98b2aa0dc.png)
Off :
![image](https://user-images.githubusercontent.com/22836285/85959890-e0c67180-b9a7-11ea-920b-829e1dd2af03.png)

**Example:**
[Test.zip](https://github.com/godotengine/godot/files/4843087/Test.zip)

**Comment by madmiraal** [comment]
#39956 fixes issues found in the provided test project. If there are other issues, please open a new issue and provide a minimal reproduction project.
