### ISSUE TITLE
Expose CanvasItemEditor and SpatialEditor to GDScript

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#3992]
It would be great to have access to _CanvasItemEditor_ and _SpatialEditor_ from _GDScript_.
The main usage example I can think of is creating plugins that need to draw to the CanvasItemEditor's viewport (like a TileMapEditor plugin) or to the SpatialEditorViewport (like [this grass plugin](https://github.com/marcosbitetti/grass_plugin_4_godot)).

In C++ you would access these viewports this way:

``` C++
CanvasItemEditor::get_singleton()->get_viewport_control();
SpatialEditor::get_singleton()->get_editor_viewport(0);
```

But there is no way to access them from _GDScript_ unless you use some crazy tricks like this (which could stop working if the editors child structure changes):
- [CanvasItemEditor](http://godotengine.org/qa/1028/how-can-locate-the-viewport-node-of-the-2d-editor-on-the-engine)
- [SpatialEditor](https://github.com/marcosbitetti/grass_plugin_4_godot/blob/e50f2a39bcc49e605a881956ee0839127453ab01/GrassPlugin.gd#L193-L206)

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by neikeq** [comment]
@akien-mga I was actually going to try adding this before releasing 2.1 if I had some time. Leaving it like this for now. I will check later :)

**Comment by neikeq** [comment]
Never mind. Exposing the canvas editor viewport is easy, but SpatialEditorViewport may need a better strategy. It may also be good to expose some information about the two editors, like the selected tool mode, etc.
Leaving this for 2.2.

**Comment by bojidar-bg** [comment]
It is really simple to get access to the viewport BTW (works at least for canvas):
````gd
var viewport = get_tree().get_edited_scene_root().get_parent()
````
:smile:

**Comment by winston-yallow** [comment]
Yes this is still a desired feature (at least for me). The workaround mentioned by bojidar-bg does not always work. I had some cases where the edited_scene_root was null.

**Comment by Hubber116sx** [comment]
Is this still being worked on?

**Comment by neikeq** [comment]
I'm closing this issue as I'm no longer interested in this feature right now. If anyone is still interested, feel free to open a more detailed proposal in [godotengine/godot-proposals](https://github.com/godotengine/godot-proposals). I may make one myself in the future if I regain interest.
