### ISSUE TITLE
Label's Valign property ignores bottom border of stylebox

### ISSUE THREAD

**Issue by Poobslag** [godotengine/godot#39923]
**Godot version:** v3.2.2.stable.official

**OS/device including version:** Windows 8 desktop

**Issue description:** If a Label has a StyleBox with a border, the Valign property aligns text too low. When VAlign is set to 'Center', instead of the text being centered it appears in the bottom. When VAlign is set to 'Bottom', instead of the text being positioned at the bottom, it's positioned outside the label entirely.

The 'Left' and 'Right' Align properties work OK, as does the 'Top' Valign property. They respect the StyleBox borders. The problem appears to specifically affect the bottom border.

![image](https://user-images.githubusercontent.com/5902413/85956541-615b8280-b954-11ea-9d22-44927d95b4dc.png)

**Steps to reproduce:** Create a Label and set its Valign property to 'Center' or 'Bottom'. Give the Label a StyleBox with a bottom border 5 pixels or larger. The larger the border, the more noticable the bug.

**Minimal reproduction project:** [label-glitch.zip](https://github.com/godotengine/godot/files/4842897/label-glitch.zip)

**Comment by aaronfranke** [comment]
Possibly related to #39630

**Comment by Haledire** [comment]
It'd like to note that somehow content margin bottom also has no bearing on a label.  I will certainly expand the size of the label if it's too big, but it never effects valigned text
