### ISSUE TITLE
Slow/Stutter iOS html5 Audio fix in 3.2.2 broke audio in android

### ISSUE THREAD

**Issue by fvasquezv** [godotengine/godot#39930]
**Godot version:**
3.2.2 Stable

**OS/device including version:**
Android 8/9

**Issue description:**
Audio (ogg, 44.1) Plays super chopped and slow on android devices.
https://github.com/godotengine/godot/issues/35937 

**Steps to reproduce:**
AudioStreamPlayer inside 2D Node

**Comment by Faless** [comment]
Did you try changing the `audio/ouput_latency` to a higher value? Do you get better results with that?

**Comment by fvasquezv** [comment]
> Did you try changing the `audio/ouput_latency` project setting to a higher value? Do you get better results with that? Also, I assume, you are using Chrome on Android right?

Yea is Chrome latest in android. Havent messed with output latency, doesent seems like a lag problem it is just like it was in iOS, chopped, crushed and slowed down

**Comment by fvasquezv** [comment]
For testing purposes i've uploaded the project im working on, exported with 3.2.2 and 3.2.1, same project, same settings just godot versión (and export template) are different.

https://chulengogames.cl/godot_test/3.2.2/
https://chulengogames.cl/godot_test/3.2.1/

i've also noticed some weird behavior, like, for instance, jumps seems a lot more higher in Android than iOS, but seems more like a device thing than the engine itself.

**Comment by Faless** [comment]
> Haven't messed with output latency, doesen't seems like a lag problem it is just like it was in iOS, chopped, crushed and slowed down

Yeah, that depends on the latency, the lower the latency, the higher the probability it will crackle. That commit actually implemented a buffer size based on the desired output latency instead of using a fixed buffer.
On Android, the fixed size buffer returned by the browser was probably higher then the buffer created for the default output latency (15 ms). Again, try raising that.

**Comment by fvasquezv** [comment]
THANKS!. Yeah had to ckrank it up to 40 (the lesser value that works), but its all good. Thank u both!.

**Comment by akien-mga** [comment]
Reopening as we're working on a proper fix for it that doesn't require manual changes.
