### ISSUE TITLE
Duplicate tracks on animation reimport - GLTF

### ISSUE THREAD

**Issue by CowKeyMan** [godotengine/godot#39959]
**Godot version:** 3.2.2

**OS/device including version:** Windows

**Issue description:** On presssing reimportfor a .glb file, my animation tracks that I created in blender (not custom ones that I created in godot, those are fine) for every single animation that I have, get duplicted. This didnt happen in 3.2.1, because I tested it, and had to revert to that version because of this issue. This happens for both .tres as well as .anim.

Note: turning off 'keep custom tracks' will 'fix' this bug, however I need custom tracks for my game, hence this is not a valid solution for myself

**Steps to reproduce:** Please refer to this video: https://youtu.be/rvnMbUBGHAI (notice how the tracks for bone1-3 got duplicated for every reimport I did). I also attached an image of the errors that come with the bug

**Minimal reproduction project:** You can test it out using this project: [AnimationImportingBugTest.zip](https://github.com/godotengine/godot/files/4847293/AnimationImportingBugTest.zip)

![Capture](https://user-images.githubusercontent.com/33454325/86043338-db6d3380-ba48-11ea-9ef7-b5fa29546f0c.PNG)

**Comment by Sl3dge78** [comment]
Ok this on is on me sorry, working on a fix...

Here's my reply on the pr i was cced #39968 

> Hey thank you for cc ing me and sorry if my PR caused any issues...
> 
> Just to understand your issue, you imported a scene with animation to external files, modified existing tracks and/or added new ones, and finally saved said animation. Then when pressing reimport what happened?
> 
> Here's what I just tested on my side and what happens in both cases :
> 
>     * Import a .dae file with animation and store the animation outside the dae
> 
>     * Edit an animation (by changing tracks or adding new ones) and save it
> 
>     * Reimport the .dae with the Keep Custom Tracks enabled.
> 
> 
> old behaviour (before my pr):
> 
>     * Edited tracks are reverted
> 
>     * Created tracks are kept
> 
> 
> new behaviour (with my pr):
> 
>     * It duplicates all tracks (that's a big issue!)
> 
> 
> This is where the merge happens :
> 
> https://github.com/godotengine/godot/blob/73262c0f609d2b865ae1af721c167600d120342a/editor/import/resource_importer_scene.cpp#L959-L971
> 
> The snippet above adds any track that isn't marked as imported from the old file to the new file, so that's why.
> 
> Maybe the operation shouldn't be a copy but a replace? If the track exists, replace it if its not imported.
> If the user wants to reverts the changes he has made he can untick "keep custom tracks"
