### ISSUE TITLE
[3.2.2] New gravity scale on rigid body not taken into account after a duplicate (Works fine in 3.2.1)

### ISSUE THREAD

**Issue by Datoh** [godotengine/godot#39950]
**Godot version:**

3.2.2

**OS/device including version:**

Windows 10

**Issue description:**

New gravity scale on RigidBody2D not taken into account. Works fine in 3.2.1

**Steps to reproduce:**
- Duplicate a RigidBody2D which has a gravity scale to 0.
- Set gravity scale of the clone to 1
- Add the clone to the scene
- Clone should fall but it does not

**Minimal reproduction project:**

[BugGodot.zip](https://github.com/godotengine/godot/files/4845772/BugGodot.zip)

**Comment by madmiraal** [comment]
Removing the `regression` label, because it doesn't appear to work in v3.2.1, v3.1.2 or even in v3.0.6 either.

**Comment by madmiraal** [comment]
This is not a bug. It's a simple case of the `Rigidbody` going to sleep when it's not moving, and the sleep state being duplicated too.

Add `clone.sleeping = false` to the `_on_Timer_timeout()` function to wake up the cloned body, and it will behave as expected.

**Comment by Datoh** [comment]
Weird in 3.2.1, I do not have to set the sleepping value to false...
https://www.twitch.tv/videos/665837417
