### ISSUE TITLE
Make tscn the default format for better text processors / SVCs compatibility?

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#3996]
Shouldn't the new tscn format be default over the binary scn?

**Comment by akien-mga** [comment]
I'd be in favour of it yes.

**Comment by AlexHolly** [comment]
+1
Sometimes I forget to use tscn and have to rename it later.

**Comment by reduz** [comment]
.tscn will work in most cases, but if you are dealing with 3D Geometry it' s usually a bad idea. 
I think this should be made optional in the editor settings, or project settings (preferred scene format)

**Comment by kubecz3k** [comment]
Another (little more trouble some) way would be to show alert message when editor detects that we are trying to save 3d mesh geometry data with tscn.

**Comment by slapin** [comment]
What is wrong with 3D data in .tscn?

**Comment by kubecz3k** [comment]
@slapin it's slow to save and it's slow to load (maybe reduz know more reasons why it's not the best idea)

**Comment by captainwasabi** [comment]
hmm, where are the editor settings stored?  I need to be able to set this once, have it affect all new projects, check it into svn, then when the artists pull the repo it is set for them too.  If it's saved into AppData that isn't going to work.

**Comment by bojidar-bg** [comment]
@captainwasabi ~ I guess you should open another issue for this, as it is useless to bloat this one. (i.e. "per-project editor setting" would be a nice title)

**Comment by slapin** [comment]
I think .tscn is just not ready for production yet

**Comment by captainwasabi** [comment]
Ah. Fair enough.

**Comment by akien-mga** [comment]
> I think .tscn is just not ready for production yet

Care to argument? Many users are using it for production just fine. It has a couple of bugs of course, but by this logic let's say that "I think Godot is just not ready for production yet" and stop wasting our time.

**Comment by slapin** [comment]
People use all kinds of stuff for "production". Unless you limit scope you
limit scope of what you say it is true. Godot is not ready to produce 3D
games with complex animations.
.tscn frmat is not ready to be used for 3D scenes. Godot vehicle physics
have very limited use and not ready for real usage. Godot 3D physics is not
ready for complex scenery,
this includes collision system. All that doesn't mean Godot is not ready
for 2D production use, and Godot 3D is good for static scenes and FF7-style
graphics, and if you do
all your 3D animations in "traditional" way (i.e. no animation blending),
and you don't have 10 characters on screen at the same time, it is ready
for production too.
But scene file format is different. You don't want to save your assets to
it and find it breaks or doesn't work right for you, or loses data, as long
as you save any scenery to it.
Whatever the effectiveness there is you should not lose data saving to it
as long as it is produced by Godot editor and tools. This leads to
uncertainty, also you have ..scn which
is bad but works and never lose data. This just prints "don't use .tscn
unless you're ready to lose data", there are known bugs in it and there are
no any reasonable plans about fixing them.
If you feel adventurous, please help with testing, but if you want to store
production stuff, stick with .scn for now.

**Comment by slapin** [comment]
Also, you look depressed. Cheer-up, even though 3.0 is a lie, we all still
have a shred of hope in our hearts.

**Comment by reduz** [comment]
something that doesn't exist can't be a lie.. it's just a promise

**Comment by slapin** [comment]
Well, I know cake actually probably did exist. But I still can't believe in
3.0
The reasons:

- there is no clear path curent state --- A... B.. C ... ... 3.0, so it is
just plain abstract number when everybody will be happy and grass will be
green again.
- while there are people who can do shit, the uncertainty about 3.0, no
pull requests about 3D allowed, no plans shared until Juan
(very busy person indeed) makes everyone happy. While people could
experiment and do things now the current state just forces them away.
I don't think Juan should do that. I just think a few comments from Juan
about what stuff in 3D is going to be accepted now, what is not,
some ad-hoc feature lists, etc. would do a great thing.
- Time passes, single-person projects tend do evolve very slowly and people
lose patience. Probably some people could speed things up.
Probably.
- There are some great things waiting in uncertainty (
https://www.youtube.com/watch?v=j99vFXPXHHA
https://www.youtube.com/watch?v=c8Cu_VzcL2Y
https://www.youtube.com/watch?v=lMw9gWKq7mQ
https://github.com/slapin/godot-fork/wiki/City-Geometry-creation )
people ask but don't get answers. If there were some big picture... but
only big loss of motivation persists.

**Comment by djrm** [comment]
solved by 29177e1e9b2644cfa2d5efe6fcfe2605b84ed68c?

**Comment by kubecz3k** [comment]
@djrm you are right :+1:

**Comment by reduz** [comment]
this is already the default, closing

**Comment by reduz** [comment]
oh you won
