### ISSUE TITLE
GLES3 environment light did not work as it should be [macOS, Intel driver bug]

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#39975]
**Godot version:**

3.2.2 stable

**OS/device including version:**

Device: 2013 late Macbook Pro 13-inch with  Intel Iris Graphics(No Discrete Graphics), OS: macOS 10.13.6

**Issue description:**

when use GLES3, the environment light looks weird
<a data-flickr-embed="true" href="https://www.flickr.com/photos/189186320@N08/50060835001/in/dateposted-public/" title="屏幕快照 2020-06-30 13.15.23"><img src="https://live.staticflickr.com/65535/50060835001_7cc89c77c2_c.jpg" width="800" height="446" alt="屏幕快照 2020-06-30 13.15.23"></a>

here is the GLES2 with default environment setting
<a data-flickr-embed="true" href="https://www.flickr.com/photos/189186320@N08/50061080277/in/dateposted-public/" title="屏幕快照 2020-06-30 13.17.53"><img src="https://live.staticflickr.com/65535/50061080277_9581d8f166_c.jpg" width="800" height="428" alt="屏幕快照 2020-06-30 13.17.53"></a>

PS: right now I am not sure is this OS driver bug(because I can't test it on macOS 10.15) or GLES3 bug

**Comment by snougo** [comment]
i have this problem since 3.2.x version, but I can't remember the exactly version it is

**Comment by snougo** [comment]
ok, I just download some preview version to test, this problem is from 3.2.0 beta2

3.2.0 beta1 is fine
<a data-flickr-embed="true" href="https://www.flickr.com/photos/189186320@N08/50061166826/in/dateposted-public/" title="屏幕快照 2020-06-30 16.50.29"><img src="https://live.staticflickr.com/65535/50061166826_05f1ace830_c.jpg" width="800" height="412" alt="屏幕快照 2020-06-30 16.50.29"></a>

**Comment by akien-mga** [comment]
3.2 beta 1 is 077b5f6c2c06bb2c0af525ee25f87e0db719f9d2, and 3.2 beta 2 is b7ea22c5d203da1b592a743a4c893de25cd34408.

Relevant changes to `drivers/gles3`:
```
$ git log 077b5f6c2c06bb2c0af525ee25f87e0db719f9d2..b7ea22c5d203da1b592a743a4c893de25cd34408 -- drivers/gles3
commit 203fb1b3484f621984e4595986cc77c9b9174d6a
Author: Clay John <claynjohn@gmail.com>
Date:   Thu Nov 21 07:44:09 2019 -0800

    Fix GL error by properly using float uniform

commit 4d6737ec730a1f620c20768c1792099683aca4f3
Author: Clay John <claynjohn@gmail.com>
Date:   Wed Nov 20 22:54:44 2019 -0800

    Fix bugs introduced by IBL fixes

commit 3be6e76f220f702d41ae5efc526064f87059539b
Merge: 1bd32388ae cd40154890
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Wed Nov 20 08:45:53 2019 +0100

    Merge pull request #33668 from clayjohn/Fix_environment_mapping_issues
    
    Fix issues with environment mapping

commit cd40154890ba9791b219d66beaf187a7d8dcdba5
Author: Clay John <claynjohn@gmail.com>
Date:   Sat Nov 16 16:56:34 2019 -0800

    Fix issues with environment mapping

commit 6536105af26bb3a6a18369b4647ac479816090b7
Merge: cc3b7d2ee2 1253a33423
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Tue Nov 19 09:36:30 2019 +0100

    Merge pull request #33527 from clayjohn/GLES2-bufferdata_optimization
    
commit 203fb1b3484f621984e4595986cc77c9b9174d6a
Author: Clay John <claynjohn@gmail.com>
Date:   Thu Nov 21 07:44:09 2019 -0800

    Fix GL error by properly using float uniform

commit 4d6737ec730a1f620c20768c1792099683aca4f3
Author: Clay John <claynjohn@gmail.com>
Date:   Wed Nov 20 22:54:44 2019 -0800

    Fix bugs introduced by IBL fixes

commit 3be6e76f220f702d41ae5efc526064f87059539b
Merge: 1bd32388ae cd40154890
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Wed Nov 20 08:45:53 2019 +0100

    Merge pull request #33668 from clayjohn/Fix_environment_mapping_issues
    
    Fix issues with environment mapping

commit cd40154890ba9791b219d66beaf187a7d8dcdba5
Author: Clay John <claynjohn@gmail.com>
Date:   Sat Nov 16 16:56:34 2019 -0800

    Fix issues with environment mapping
```

**Comment by fabriceci** [comment]
I tried on two mac with macOS Catalina 10.15.5

The first one use an IGPU (Intel Iris 1536): **I have the same issue**
The other use an AMD card (Radeon Pro 560x): **no issue**

**Comment by snougo** [comment]
> I tried on two mac running macOS Catalina 10.15.5
> 
> The first one use an IGPU (Intel Iris 1536): **I have the same issue**
> The other use an AMD card (Radeon Pro 560x): **no visible issue** (BUT maybe there is also one, view issue below)
> 
> This issue seems (partly) linked: https:#39952

right now it looks like this issue only appear on Mac with Intel GPU, I guess

**Comment by snougo** [comment]
I tested issue on a laptop with intel 3000HD on Windows7, but that laptop is too old. even using GLES2, environment light wouldn't lighting the scene and mesh is totally black

**Comment by name-here** [comment]
That sounds like a separate issue.  You should file a bug report for it.

**Comment by Calinou** [comment]
@name-here There's already an issue about that, so please don't open a new one :https://github.com/godotengine/godot/issues/25512

**Comment by snougo** [comment]
update: occasionally I adjusted the metallic of the material and found that the result seemed to look very similar to the GLES2 render, also I adjusted background energy to make it more similar

![屏幕快照 2020-11-21 20 07 18](https://user-images.githubusercontent.com/64188282/99877275-cd0df700-2c37-11eb-8c34-bf0ce1b084fa.png)
![屏幕快照 2020-11-21 20 10 31](https://user-images.githubusercontent.com/64188282/99877283-d26b4180-2c37-11eb-8f9f-90e47930e8a5.png)


default GLES3 render
![屏幕快照 2020-11-21 20 08 04](https://user-images.githubusercontent.com/64188282/99877206-7d2f3000-2c37-11eb-80fb-201a91ccce50.png)

GLES3 render after adjusting
![屏幕快照 2020-11-21 20 07 12](https://user-images.githubusercontent.com/64188282/99877235-a51e9380-2c37-11eb-8c17-9f7339f2129c.png)

default GLES2 render
![屏幕快照 2020-11-21 20 07 39](https://user-images.githubusercontent.com/64188282/99877266-c2536200-2c37-11eb-9446-109047f05b03.png)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/55754, which is more up-to-date.
