### ISSUE TITLE
Godot cannot open documentation links with special characters

### ISSUE THREAD

**Issue by DanielZTing** [godotengine/godot#39971]
**Godot version:**

v3.2.2.stable.official

**OS/device including version:**

macOS Catalina 10.15.5 (19F101)
MacBookAir8,1

**Issue description:**

On macOS, opening a link in the editor's built-in documentation that has special characters ('#' for example) will percent encode the URL, giving a 404.

**Steps to reproduce:**
1. Type "InputMap" in a script and CTRL/CMD click it to open the built-in documentation viewer
2. Open the link under Online Tutorials (docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html#inputmap)
3. It opens in the browser as https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html%23inputmap (note the '#' character being percent-encoded), which gives a 404

**Minimal reproduction project:**

**Notes**
I have looked at the relevant code and it appears that the macOS implementation for opening a link will percent-encode special characters. I do not know why it does this as this behavior is absent on my Windows PC. I have attached a PR that removes the offending snippet. However, I also wonder if it would be a good idea replace that link with [the actual page for InputMap](docs.godotengine.org/en/latest/classes/class_inputmap.html).

**Comment by Calinou** [comment]
> However, I also wonder if it would be a good idea replace that link with the actual page for InputMap.

No, as that would link to the online class reference for the class you're viewing, which isn't very useful.
