### ISSUE TITLE
AudioEffectDistortion MODE_CLIP only outputs positive values

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/godot#39970]
**Godot version:**
Godot 3.2.2.stable

**Issue description:**
### Code
https://github.com/godotengine/godot/blob/d41e8d8f2d94a2be74a2fe75f5f48c78346010d2/servers/audio/effects/audio_effect_distortion.cpp#L60-L66
### Plotted Graph From Code
![brave_2020-06-30_12-00-53](https://user-images.githubusercontent.com/34954180/86082016-60982d00-bac9-11ea-8377-9a898647bc04.png)
### Audio Output
![audacity_2020-06-30_11-41-11](https://user-images.githubusercontent.com/34954180/86080922-9be52c80-bac6-11ea-9a70-64c737e984e9.png)

Clip distortion only outputs positive values due to raising a negative number to a power which makes it absolute. I was expecting a clip distortion to look something like this:
![FL64_2020-06-30_12-05-16](https://user-images.githubusercontent.com/34954180/86082389-32ffb380-baca-11ea-83b9-36e76d4619c2.png)
Forgive me for not knowing how to code in C++, but I was thinking of a work-around to be something like this that includes negative values, it might not be the best though:
```gdscript
a = pow(abs(a), 1.0001 - drive_f) * sign(a) 
if a > 1.0:
    a = 1.0 
elif a < -1.0: 
    a = -1.0; 
```
![brave_2020-06-30_12-01-48](https://user-images.githubusercontent.com/34954180/86082058-7efe2880-bac9-11ea-9cc8-8ab6b8b7576e.png)

If positive outputs only are intentional, you may close & archive this issue. Thank you in advance for responding and looking into this issue.

**Comment by Calinou** [comment]
cc @reduz, as he implemented audio effects.

**Comment by NoodleSushi** [comment]
Fixed by https://github.com/godotengine/godot/pull/46199
