### ISSUE TITLE
Navigation mesh not created from script.

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#39983]
**Godot version:**
3.2.2

**OS/device including version:**
Windows 7 x64

**Issue description:**
Navigation mesh not created from script - just empty array

**Steps to reproduce:**
```
func _ready():
	var n = NavigationMesh.new()
	n.create_from_mesh(mesh)
	var nmi = NavigationMeshInstance.new()
	nmi.navmesh = n
	add_child(nmi)
```
```
E 0:00:00.896   VisualServer::mesh_add_surface_from_arrays: Condition "array_len == 0" is true.
  <C++ Source>  servers\visual_server.cpp:965 @ VisualServer::mesh_add_surface_from_arrays()
  <Stack Trace> main.tscn::31:14 @ _ready()
E 0:00:00.899   ArrayMesh::add_surface_from_arrays: Condition "len == 0" is true.
  <C++ Source>  scene\resources\mesh.cpp:849 @ ArrayMesh::add_surface_from_arrays()
  <Stack Trace> main.tscn::31:14 @ _ready()
```

or this need additional settings? but i not see this in https://github.com/godotengine/godot/blob/dffb8824db33a430aa72d4d6435c637fa1e14801/editor/plugins/mesh_instance_3d_editor_plugin.cpp#L230

**Comment by JohanAR** [comment]
I think it sounds like it's saying your mesh is empty. Where is the mesh variable coming from?

**Comment by Calinou** [comment]
@SuperDIMMaX Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by SuperDIMMaX** [comment]
Any. Example - test cube
this code from MeshInstance. `mesh` - exist and nav_mesh generate from editor

>@SuperDIMMaX Please upload a minimal reproduction project to make this easier to troubleshoot.

copy this code in MeshInstance, create test cube and run

**Comment by Calinou** [comment]
I don't know if creating a navigation mesh is supposed to work with procedural meshes.

**Comment by SuperDIMMaX** [comment]
errors in console show when - debug->visible navigation

>I don't know if creating a navigation mesh is supposed to work with procedural meshes. Does it with an OBJ mesh or a Collada/glTF scene?

test cube, OBJ mesh, and procedual geometry

**Comment by JohanAR** [comment]
I can only get this error when I'm running the scene, and since Godot forks a process for that I can't analyze it in gdb. I tried exporting the project but then I don't get the errors..

**Comment by Calinou** [comment]
> I can only get this error when I'm running the scene, and since Godot forks a process for that I can't analyze it in gdb

You can specify a project to run using the command line:

```bash
path/to/godot.binary --path /path/to/project/directory
```

**Comment by JohanAR** [comment]
> You can specify a project to run using the command line:

Thanks! Unfortunately the error didn't appear when started this way either. Seems to only happen when run through the editor. Maybe debug->visible navigation doesn't do anything without the editor?

**Comment by SuperDIMMaX** [comment]
Editor try visualize Nav_Mesh and can`t, and show errors.

**Comment by Zireael07** [comment]
@Calinou: Several versions ago, I used nav mesh built from procedural meshes, so it's definitely possible.
ArrayMesh:add_surface_from_arrays could in fact be finicky when I tried using it for my car deformations (it complained on perfectly existing meshes)

**Comment by SuperDIMMaX** [comment]
> @Calinou: Several versions ago, I used nav mesh built from procedural meshes, so it's definitely possible.
> ArrayMesh:add_surface_from_arrays could in fact be finicky when I tried using it for my car deformations (it complained on perfectly existing meshes)

@Zireael07 Zireael07 Yes, i try use this for procedural meshes, but probality need some rework(?): many interesting functions exist as part of internal functions:
```
function(){
    algoritm_1,
    algoritm_2
    return algoritm_1+ algoritm_2
}
```
example : algoritm_1 exist in Navmesh, and it very useful for part as another algoritms - _car deformations_ 

And this is offtopic, - see https://github.com/godotengine/godot-proposals/issues/1137  (this proposal more general, not only CGAL and CSG, and main idea - integrate useful algoritms as base(many exist in Godot, but as part of functions and internal) and make combinations _func_1(){algoritm_1}_ _func_2(){algoritm_2}_ _func_3(){func_1 + func_2}_)

**Comment by SuperDIMMaX** [comment]
Debug -> show navigaion - not show if nav mesh created from script(or else)( C# ?) - this is bug?

**Comment by Calinou** [comment]
@SuperDIMMaX This is a known bug: https://github.com/godotengine/godot/issues/32244

**Comment by hoontee** [comment]
Does swapping the order of `add_child(nmi)` and `nmi.navmesh = n` fix your issue? At the very least, it fixes the error message.

**Comment by Calinou** [comment]
@SuperDIMMaX Can you try applying hoontee's suggestion above?

**Comment by smix8** [comment]
The navigation debug meshes are only created when a node enters the scenetree and the navmesh is valid. There is no visual auto-update of the debug if the navmesh is added later at runtime or changed. This  https://github.com/godotengine/godot-proposals/issues/4507 proposal tries to fix this but is not ready yet.

As Zireal mentioned script created meshes do work in more recent Godot version for navigationmeshes and bake (just no visual debug meshes) but they need to be created in the proper format.

The `NavigationMesh.create_from_mesh()` requires a mesh with Mesh.PRIMITIVE_TRIANGLES and vertex for a valid triangle meshes with proper mesh array size at Mesh.ARRAY_MAX. If this is not provided the mesh surface creation fails hence this error messages later when the navigation instances / regions and SceneTree try to create debug meshes from this broken source mesh.

Best to convert the meshes before to a full ArrayMesh as this will create the proper array size to avoid trouble. Most primitive meshes from the editor are not in the proper format for this use by default and need to be converted.
