### ISSUE TITLE
[3.2.2 iOS] XCode-project not include the required frameworks and libs

### ISSUE THREAD

**Issue by PoqXert** [godotengine/godot#39989]
**Godot version:**
3.2.2.stable

**OS/device including version:**
iOS

**Issue description:**
XCode-project created by Godot does not include the required frameworks and libs. Only 'godot' included.
![](https://user-images.githubusercontent.com/3893594/86144100-932d3e80-bb38-11ea-8377-07801f9cc3e2.png)

**Steps to reproduce:**
1. Create Godot project
2. Export for iOS
3. Open Xcode-project

**Comment by bruvzg** [comment]
Frameworks should be found and linked automatically at build time, see #39762
