### ISSUE TITLE
has(Variant value) function is not working properly

### ISSUE THREAD

**Issue by KutayGuler** [godotengine/godot#39987]
**Godot version:**
3.2.2.stable.official

**Issue description:**
So I declared a variable called `array ` which takes it's elements from another array that is stored in a json file. And I want to see if a certain value is inside the array. The loop I've written to traverse the array is returning true whereas the function `has ` is returning false. I wonder if this problem is related to the engine or because of something I'm missing.

**Steps to reproduce:**
![issue](https://user-images.githubusercontent.com/58315469/86138206-74a25580-baee-11ea-8063-1011f38afbea.PNG)
![issue2](https://user-images.githubusercontent.com/58315469/86138208-75d38280-baee-11ea-9a9f-50f0cb2cc5a5.PNG)

**Comment by Calinou** [comment]
Does the JSON contain 300 as a *number* or as a *string*? The print handler won't make a difference between those.

**Comment by KutayGuler** [comment]
It contains it as a number

**Comment by Calinou** [comment]
@KutayGuler Could you upload a minimal reproduction project, please?

**Comment by KutayGuler** [comment]
@Calinou Sure, I will upload it in a moment.

**Comment by KutayGuler** [comment]
@Calinou here it is

[HasFunctionIssue.zip](https://github.com/godotengine/godot/files/4852696/HasFunctionIssue.zip)

**Comment by HazmatDemon** [comment]
As Calinou said JSON doesn't distinguish integers from floats. In your example you are trying to check if the array contains 300 (integer). But array actually contains 300.0 (floting-point number).
`array.has(300.0)` <- this will work
`array.has(300)` <- this won't work

One thing that I have noticed is when using `in` keyword you can actually use integers:
`300 in array` <- this will work
`300.0 in array` <- this will also work

**Comment by aaronfranke** [comment]
Indeed, this is intended behavior. The array contains `300.0`, not `300`.

Changing the behavior in GDScript's array `has` method is not going to happen (because GDScript does have integers so this distinction makes sense), but maybe `parse_json` could have a boolean setting to treat whole numbers as integers?

**Comment by KutayGuler** [comment]
Thanks for the explanations :) @Calinou @HazmatDemon @aaronfranke
