### ISSUE TITLE
Buttons do not respond to clicks in HTML export

### ISSUE THREAD

**Issue by triptych** [godotengine/godot#40]
I created a simple demo using the first script tutorial - click a button to change some text.
This demo works in preview, as well as an OSX export, however in the HTML export the button does not respond to clicks at all.

Here's the code
![godot_engine_-_sayhello_xml_____and_godotbug](https://f.cloud.github.com/assets/8691/2139817/7bf4add0-9343-11e3-9d48-1dc1da2de308.png)

And the layout
![godot_engine_-_sayhello_xml____-2](https://f.cloud.github.com/assets/8691/2139820/820c6316-9343-11e3-8e2a-a6e4da2fc0de.png)

Pressing the button changes the text, however this does not happen in the HTML exported version.

Tried this in both Mac OSX Chrome and Firefox.

**Comment by akien-mga** [comment]
Since there was quite some work done on the HTML5 exporter for 2.0, and the bug report being quite old, I'll assume it's fixed ans archive it. Feel free to reopen if it's not the case in the current master branch.
