### ISSUE TITLE
Godot startup and playing scene takes ~65 seconds

### ISSUE THREAD

**Issue by Prifurin** [godotengine/godot#40002]
**Godot version:** 3.2.2

**OS/device including version:** Dell Inspiron 1564, Windows 7,  ATI Mobility Radeon HD 4330, Intel Core i3 CPU M330 2.13GHz, 4GB memory, GLES2 backend(GLES3 not supported by videocard)

**Issue description:** Creating new project in Godot or playing a scene requires ~65 seconds before launching, memory usage changes in slow peaks from 50 000 KB to 300 000 KB with constant CPU usage of 24-25% for new Godot process(the scene) and ~140 000KB 1% for main one(the editor).

**Steps to reproduce:**?

**Minimal reproduction project:** Any, for example label "Hello World" from Godot Tutorial

**Comment by Calinou** [comment]
This is a very old graphics card, which is known to have issues even when using the GLES2 renderer. At this point, I'd recommend getting a newer PC.

**Comment by qarmin** [comment]
Did you try to use Linux?
Older AMD and Intel graphics cards seems to work better on Linux with Mesa than on Windows with very old graphics drivers.
You can try it without installing entire OS

**Comment by akien-mga** [comment]
Indeed, the specs are too low for using Godot efficiently.

You may gain some performance by removing the `default_env.tres` environment from your project though, as the ProceduralSky it contains is known to be performance heavy and a deal-breaker for the very low end hardware.
