### ISSUE TITLE
Fullscreen toggle by window manager does not change OS.window_fullscreen property

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#40007]
**Godot version:**
3.2 branch - 63fd0d37edc6293caa02c2c9209cb9a27a57464d

**OS/device including version:**
Arch Linux

**Issue description:**
Toggling fullscreen mode `on` and `off` using `i3` as the window manager does not update the value of `OS.window_fullscreen`.

I suppose this may be happening with other tiling/dynamic window managers.

**Steps to reproduce:**
1. Launch any project in non-fullscreen mode.
2. Toggle fullscreen using the window manager shortcut (usually Alt+F in i3)
3. Check `OS.is_window_fullscreen()`. It returns `False`.

**Minimal reproduction project:**

[fullscreen_toggle.zip](https://github.com/godotengine/godot/files/4855289/fullscreen_toggle.zip)

**Comment by Calinou** [comment]
This is probably expected. Can the application even be aware of this? Is there any precedent of an application noticing when you use the window manager to make it fullscreen or borderless?

**Comment by Rubonnek** [comment]
I believe it can be made to be aware of it. Firefox can toggle its full screen mode successfully by using its shortcut `F11` and the window manager shortcut `Alt+F` interchangeably in any order under `X11`. I'm not sure how Firefox does it yet.

I haven't tested anything on `wayland`, but I suppose the same applies.

**Comment by Ev1lbl0w** [comment]
Looking at the [FreeDesktop specification](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm45805407959456) for `_NET_WM_STATE`, and in this sentence in particular:
> A Client wishing to change the state of a window MUST send a _NET_WM_STATE client message to the root window (see below). The Window Manager MUST keep this property updated to reflect the current state of the window. 

leads me to believe that the window manager should be sending `_NET_WM_STATE_FULLSCREEN` atoms to Godot

**Comment by akien-mga** [comment]
Fixed by #62543.

**Comment by akien-mga** [comment]
Still needs to be fixed in 4.0 though (I checked and it's reproducible), so let's keep this open for now.
