### ISSUE TITLE
Two or more KinematicBody2D on top of another KinematicBody2D makes the below one to move

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#40006]
**Godot version:**

Godot 3.2.2.stable

**OS/device including version:**

Windows 8.1

**Issue description:**

Two or more KinematicBody2D on top of another KinematicBody2D causes the one below to move and knock down the others.

What I found is that the size of the KinematicBody2D influences this.

![movingKinematicBody2Dx](https://user-images.githubusercontent.com/25422687/86191569-c44c4580-bb1d-11ea-9303-475293111931.gif)

**Maybe related:**

https://github.com/godotengine/godot/issues/27652
--> I tried to put infinite inertia = false in the move_and_slide_with_snap, although this argument is only for the RigidBody2D.

https://github.com/godotengine/godot/pull/36280

**Steps to reproduce:**
Place a KinematicBody2D on the floor with move_and_slide (or move_and_slide_with_snap) idle or moving, and make two others KinematicBody2D jump on top of the first one and keep moving at least one of them.

**Minimal reproduction project:**

[KinematicMoving.zip](https://github.com/godotengine/godot/files/5419081/KinematicMoving.zip)

**Comment by AttackButton** [comment]
Closed by https://github.com/godotengine/godot/pull/36280. Just waiting for the merge to test more.

**Comment by aaronfranke** [comment]
Generally, issues shouldn't be closed until the fix has been merged. I'm reopening this and adding "Fixes #40006" to that PR.

**Comment by capnm** [comment]
I can confirm that this is broken in 3.2.3.stable and that #42574 fixes the issue for me on the 3.2 branch.
