### ISSUE TITLE
TextEdit node does not allow to enter UTF-8 symbols

### ISSUE THREAD

**Issue by albertas** [godotengine/godot#40005]
**Godot version:**
3.2.2

**OS/device including version:** 
Ubuntu 18.04 

**Issue description:** (what happened, and what was expected):
Added TextInput node, started project, focused TextInput node, entered UTF-8 characters.
Happened: UTF-8 characters were ignored - only ASCII characters were added to TextInput.
Expected: UTF-8 characters added to TextInput.

**Comment by OverloadedOrama** [comment]
Are you using the default font? AFAIK, it doesn't support UTF-8 characters. You could try finding a font that does.

**Comment by Calinou** [comment]
Closing, as this is very likely related to the default font in use. This will be (mostly) fixed by https://github.com/godotengine/godot/pull/39603, but in the meantime, you can use almost any TTF/OTF font you can find online.
