### ISSUE TITLE
Zooming out to infinity locks the camera in the 3D editor

### ISSUE THREAD

**Issue by phkeese** [godotengine/godot#40014]
**Godot version:**

Godot 3.2.2

**OS/device including version:**

Mac OS 10.15.5 Catalina

**Issue description:**

I zoomed out in the 3D view until the zoom meter hit infinity.
<img width="61" alt="infinity" src="https://user-images.githubusercontent.com/26239210/86236698-cdc7c300-bb9a-11ea-8804-ead77b51cbaf.png">
<img width="309" alt="infinity-info" src="https://user-images.githubusercontent.com/26239210/86236697-cc969600-bb9a-11ea-9ecb-0f5a485d1ef2.png">
Now the camera position is locked and does not allow zooming back in or focusing origin or objects.
Using the free-fly mode (Shift-F) will convert infinite values to NaN.
<img width="132" alt="nan" src="https://user-images.githubusercontent.com/26239210/86236699-cdc7c300-bb9a-11ea-82f5-114bcb2b420e.png">
Re-opening the scene or project preserves this state and the camera is still locked.
This occurred with both mouse and trackpad zooming.

**Steps to reproduce:**
1. Create a 3D scene
2. Zoom out until you get to `inf.0`

**Minimal reproduction project:**

[Editor Camera Lock.zip](https://github.com/godotengine/godot/files/4857406/Editor.Camera.Lock.zip)

**Comment by Calinou** [comment]
This should be fixed by #39743 once it's merged.

**Comment by greygraphics** [comment]
Deleting the cache directory did not help, but deleting the corresponding Spatial.tscn-* files in `projects/Project-Name` in the editor data directory did restore the camera.
