### ISSUE TITLE
Vulkan: Tile stretch mode doesn't work for TextureRect & TextureButton

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#40011]
**Godot version:**
Master 719609522a30fa9e3b96b028ac5a1d1a65f1678f

**OS/device including version:**
OS: Windows 10
Rendering: Vulkan (GLES can't be tested at the moment)
Graphic card: GeForce 940M

**Issue description:**
Setting the stretch mode to "Tile" in `TextureRect` or `TextureButton` doesn't result in the texture repeating itself.
![image](https://user-images.githubusercontent.com/1075032/86227226-052f7300-bb8d-11ea-9554-04404123ee03.png)

I didn't find any setting on the texture to make it repeat on stretch, so it seems tiling is not supported at the moment.

**Steps to reproduce:**
- Create new project
- Add a `TextureRect` or `TextureButton` in the scene
- Set `texture` property with icon.png
- Check `expand` property
- Select `Tile` in `Stretch Mode` property
- Scale the control up
- Observe tiling doesn't work properly

**Minimal reproduction project:**
[texture-tiling.zip](https://github.com/godotengine/godot/files/4858164/texture-tiling.zip)

**Comment by Shadowblitz16** [comment]
I can confirm this as I also have this bug

**Comment by blackwire** [comment]
I also noticed this when using an atlas resource on a texture rect and trying to tile it. Same thing happened. It just stretches.

**Comment by Poobslag** [comment]
Prior to Godot 3.3, I was able to work around this bug by adding a child to the TextureRect. After Godot 3.3, this workaround no longer works.

```
	var texture_rect_glitch_workaround: ColorRect = ColorRect.new()
	texture_rect_glitch_workaround.name = "WorkaroundForGodot40011"
	texture_rect_glitch_workaround.color = Color.transparent
	add_child(texture_rect_glitch_workaround)
```

**Comment by akien-mga** [comment]
@Poobslag This issue is Vulkan specific. If you have a similar issue in 3.3, this should be reported separately.

**Comment by Poobslag** [comment]
> 
> 
> @Poobslag This issue is Vulkan specific. If you have a similar issue in 3.3, this should be reported separately.

Thank you! My mistake.

**Comment by KoBeWi** [comment]
Doesn't seem to happen anymore in 83d2673
