### ISSUE TITLE
Physical object not ignore pause in the mode process.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#4001]
**Operating system or device:**
Ubuntu15.04

**Issue description** (what happened, and what was expected):
I wanted to cube falling down, even during a pause.

**Steps to reproduce:**
Add RigidBody/TestCube
Switch the PauseMode: Process
Start the game
Activate the get_tree().set_pause(true)

**Link to minimal example project** (optional but very welcome):
[Bug rigid pause process.zip](https://github.com/godotengine/godot/files/166100/Bug.rigid.pause.process.zip)

**Comment by EdwardAngeles** [comment]
I can confirm this happens to me too (ubuntu / linux, although I don't think it have something to do with the OS, built from source). Physics objects (in my case, RigidBody2D) won't keep processing not matter what.

**Comment by reduz** [comment]
This is not a bug, physics in it's entirety stops being processed during pause, this can't be fine-grained to different bodies since physics engine processes everything at once.

Changing this so doc team writes this down where relevant.

**Comment by bojidar-bg** [comment]
@reduz What about considering paused bodies as "static", and computing as normal? (just asking)
