### ISSUE TITLE
Program closes when I use the shift key to select two nodes

### ISSUE THREAD

**Issue by Appsmofera** [godotengine/godot#4002]
**Operating system or device:**
Mac

**Issue description** (what happened, and what was expected)
Program closes when I select the second node using the shift key

**Steps to reproduce:**
Just select tow nodes using the shift key

**Link to minimal example project** (optional but very welcome):
Happens in every project

**Comment by freemanfromgodotengine** [comment]
Can't reproduce on Linux. Godot compiled 3 days ago.

**Comment by akien-mga** [comment]
Probably a duplicate of #3541.
