### ISSUE TITLE
Toggling borderless toggle doesn't work properly in i3

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#40037]
**Godot version:**
3.2 branch - 63fd0d37edc6293caa02c2c9209cb9a27a57464d

**OS/device including version:**
Arch Linux

**Issue description:**
Toggled the `OS.window_borderless` doesn't work properly under `i3`. Turning the window border off works well, but not turning on the border.

I haven't tested this using other window managers/desktop environments.

This could be worked on at the same time as #40007

**Steps to reproduce:**
Toggle `OS.window_borderless` property under `i3` having the game running as a floating window. The window border turns off fine, but doesn't turn on.

**Minimal reproduction project:**
[borderless_toggle.zip](https://github.com/godotengine/godot/files/4860842/borderless_toggle.zip)

**Comment by Rubonnek** [comment]
Spent some time looking into this and turns out `i3` does not process `_MOTIF_WM_HINTS` as other window managers commonly do. This issue was [reported in the `i3` repository](https://github.com/i3/i3/issues/3678).

I'm not able to reproduce the borderless toggle issue in other window managers such as the one used by PopOS 22.04.

**Comment by Rubonnek** [comment]
Closing this issue since the root cause is not with the Godot Engine itself.

**Comment by orestisfl** [comment]
We recently "fixed" that in i3 and it has caused some uproar: https://github.com/i3/i3/issues/5149

So, I have some questions here:
1. Have you tried to reproduce this with `openbox`? Is the behavior different than i3?
2. Which motif values does godot set on startup?
3. Is the expectation for the wm to react on updates of the motif hint or also the initial value?

**Comment by Rubonnek** [comment]
> 1\. Have you tried to reproduce this with `openbox`? Is the behavior different than i3?

Openbox works as expected.

[openbox_godot_borderless_toggle.webm](https://user-images.githubusercontent.com/8337880/191832334-b0024128-2473-4626-95df-6fd47f3f5ec0.webm)

`i3 version 4.20.1` on the other hand does not

[i3_godot_borderless_toggle.webm](https://user-images.githubusercontent.com/8337880/191833496-2c3bcdca-ac49-40fe-a71b-27c7beba03dd.webm)

> 2\. Which motif values does godot set on startup?

There are no motif values created on startup -- `_MOTIF_WM_HINTS` atom is not created by default.

See [startup_atoms.txt](https://github.com/godotengine/godot/files/9628878/startup_atoms.txt) for the full list.

> 3\. Is the expectation for the wm to react on updates of the motif hint or also the initial value?

I was expecting the wm to react on updates to the motif hint. Specifically to `Hints.decoration` as toggled here:
https://github.com/godotengine/godot/blob/2efed1e2068a566e9e2f95aeef7b857459492cf5/platform/x11/os_x11.cpp#L1954-L1958

In my tests most window managers react automatically to toggling `Hints.decoration` as seen above. I think I recall inspecting the source code for IceWM and noting it installed callbacks to inspect the changes to the motif hint in order to toggle the window borders as needed.

**Comment by orestisfl** [comment]
Thank you for the elaborate reply!
