### ISSUE TITLE
Mesh2D doesn't render

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40039]
**Godot version:**

0a8dbe7

**Issue description:**

When you convert Sprite2D to Mesh2D (from the top Sprite2D menu), it disappears. Not sure if the converted mesh data is corrupted or any mesh doesn't render.

**Comment by JohanAR** [comment]
Any error message? I tried creating a 2D scene, and as soon as I add a Mesh to a MeshInstance2D it starts spamming: "ERROR: FIXME: Mesh, MultiMesh and Particles render commands are unimplemented currently, they need to be ported to the 4.0 rendering architecture."

**Comment by KoBeWi** [comment]
Yeah, I now noticed the error too.

**Comment by KoBeWi** [comment]
Fixed by #48617
