### ISSUE TITLE
Particle2D emitting settings create unexpected results.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#4003]
**Operating system or device:**
xubuntu 14.04 64-bit running newly compiled Godot from github. Also confirmed with a versions from 3 days ago.

**Issue description** (what happened, and what was expected):

I would expect that Particle2D setting amount to 1, lifetime to 1, timescale 1, preprocess 0.1, emit timeout 0.9 and explosiveness to 1 would create exactly one particle emitted when is_emitting(true) is called (or just Emitting check box checked in Inspector).
However it does not.
You have to set amount to a higher value to see particle or particles emitted (they might be one on top of another).
Also, setting explosiveness to 0 seems buggy too. At 0 you must bump up timeout to 1.1 to see emitted particle or particles.

**Comment by kubecz3k** [comment]
@freemanfromgodotengine  can you recheck on current main? thanks! :)

**Comment by freemanfromgodotengine** [comment]
I will try as soon as I will be back, but I will not be able to test in the same app, as in my case both, newest 2.1.1+ and master 3.0 version, get bugs, that prevent my apps from running properly at all.

**Comment by kubecz3k** [comment]
@freemanfromgodotengine sure, I think it's quite safe to close the issue since particles were rewritten in 3.0 but some confirmation would be great :)

**Comment by pwab** [comment]
Saw this on the #10239 tracker list.
I created a test project and the particles are working as expected.

**Download sample project:**
[issue-4003.zip](https://github.com/godotengine/godot/files/1610088/issue-4003.zip)

> amount to 1, lifetime to 1, ~timescale 1~, preprocess 0.1, ~emit timeout 0.9~ and explosiveness to 1 

![one_particle](https://user-images.githubusercontent.com/19271185/34652824-a919e2b2-f3e3-11e7-8e22-d99444afb3d8.png)

> explosiveness to 0

![sun_burst](https://user-images.githubusercontent.com/19271185/34652847-e289afd2-f3e3-11e7-80ff-fec23a2d7be0.png)

Seems to be fixed now.

**Comment by kubecz3k** [comment]
@pwab nice work!
