### ISSUE TITLE
Atlas auto re-importing

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#40047]
**Godot version:**
v3.2.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Does texture atlas update by detecting changing one of consist sprites? Expected behiavour like working with individual sprites.

**Steps to reproduce:**
1. unzip attached example.
2. open project.
3. open textures folder from project
4. open one of sprites (a.png, b.png,c.png.) with any image editor and redraw.
5. goto godot editor.
6. atlas doesn't updated.

_but you can manually update atlas by:_
a) close godot editor and reopen project.
or
b) choose atlas and hit re-import in "import" tab.

**Minimal reproduction project:**
here -> [example.zip](https://github.com/godotengine/godot/files/4862786/example.zip)

**Comment by abhinav4987** [comment]
while running the tscn file, got an invalid/corrupt message (am using v4.0), any clue why?

**Comment by abhinav4987** [comment]
is there a proposed feature for auto-updation?

**Comment by Calinou** [comment]
> while running the tscn file, got an invalid/corrupt message (am using v4.0), any clue why?

3.2.x and 4.0 aren't compatible with each other. Don't mix and match them :slightly_smiling_face:

**Comment by abhinav4987** [comment]
> > while running the tscn file, got an invalid/corrupt message (am using v4.0), any clue why?
> 
> Godot 3.2.x and 4.0 aren't compatible with each other. Don't mix and match them 🙂

ya i re-installed it.

**Comment by ChristopheLY** [comment]
there are another probleme
the icon ( atlas.png and a.png / b.png / ... ) in the filesystem dock was not update when you re-import the atlas

**Comment by boruok** [comment]
> there are another probleme
> the icon ( atlas.png and a.png / b.png / ... ) in the filesystem dock was not update when you re-import the atlas

confirm, forgot to mention this issue too.

**Comment by ChristopheLY** [comment]
Can I make the PR?

**Comment by Zireael07** [comment]
Of course you can, we have no rules forbidding people to PR bugfixes :)
