### ISSUE TITLE
Building master on macOS fails because 'main/default_controller_mappings.h' is missing

### ISSUE THREAD

**Issue by virtualritz** [godotengine/godot#40066]
**Godot version:**
master 

**OS/device including version:**
macOS 10.15.5

**Steps to reproduce:**
```
❯ scons platform=osx --jobs=$(sysctl -n hw.logicalcpu)
scons: Reading SConscript files ...
Building for macOS 10.12+, platform x86-64.
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
...
[  3%] Compiling ==> main/default_controller_mappings.gen.cpp
main/default_controller_mappings.gen.cpp:3:10: fatal error: 'main/default_controller_mappings.h' file not found
#include "main/default_controller_mappings.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by bruvzg** [comment]
Delete `default_controller_mappings.gen.cpp` it was renamed (and all other `.gen.` files), this type of errors can happen when repository clone is updated without cleaning up generated files first.

**Comment by josephbburg** [comment]
> Delete `default_controller_mappings.gen.cpp` it was renamed (and all other `.gen.` files), this type of errors can happen when repository clone is updated without cleaning up generated files first.

is there a tool for cleaning up like `make clean` ? Thanks.

**Comment by Calinou** [comment]
> is there a tool for cleaning up like make clean ? Thanks.

`scons -c` won't take care of `.gen.cpp` files, so you have to remove that file manually.

**Comment by akien-mga** [comment]
> As far as I know, scons -c won't take care of .gen.cpp files, so you have to remove that file manually.

It does, but you should also give other compilation arguments. E.g. `scons p=osx -c`. It should be the same arguments used for building.
