### ISSUE TITLE
UI click on mac fullscreen registered below expected point

### ISSUE THREAD

**Issue by n-smits** [godotengine/godot#40061]
**Godot version:** 3.2.2.stable.official
**OS/device including version:** mac catalina (10.15.5)

**Issue description:**
UI click registered below expected point (see gif below). The issue is only on fullscreen (I don't mean maximized), and doesn't happen at all otherwise, including on maximized.

"Click accuracy" get progressively worse down screen Y axis. So on the bottom of the screen, (supposing default layout) on e.g. Scene, click needs to be way on top of a button to be correct, while on top of screen, e.g. FileSystem, it works almost as expected. Problem is consistent with left and right click and drag, and across all UI elements (buttons, lists, dropdowns etc.) It's pretty much impossible not to misclick.

Apologies if already logged somewhere, couldn't find any.
Will investigate further upon request.

![Screen Recording 2020-07-02 at 19 01 32](https://user-images.githubusercontent.com/53984336/86389638-e5847180-bc96-11ea-80d9-1f07915e13d2.gif)

**Steps to reproduce:** fresh godot install. Since it's a gui problem, no reproduction project.

**Comment by Zireael07** [comment]
What's your GPU and monitor? Is it retina?

**Comment by mbrlabs** [comment]
This looks similar to this issue: https://github.com/godotengine/godot/issues/38778
Did you change the default font or text size of the editor ui? If so, try restoring the default values and see if it fixes it.

**Comment by n-smits** [comment]
GPU is Radeon Pro Vega 48. Monitor is retina.

Regarding [#38778](https://github.com/godotengine/godot/issues/38778), there is no problem with text, just buttons and lists. (Clicks in script editor registered as expected, I opened a script that had more lines than fit on screen and didn't scroll to bottom, as suggested by [comment](https://github.com/godotengine/godot/issues/38778#issuecomment-629639653)).

In fact, I noticed click are correct on menu bar, and get progressively worse down the screen (Y axis). So, using default view, Scene list is almost good, while File System is very off. I confirm this by moving File System view up, and it behaves better.

That would suggest this really is about retina, i.e. 2x pixel density?

As for UI text size, it is default. (Literally nothing was changed within the editor except the window background color, I'm a first time user)

**Comment by snougo** [comment]
I can't reproduce this issue in 3.2.2 stable on macOS 10.13.6(both GLES2 and GLES3), but I used a 1920x1080 external monitor to test, so I am not sure is it still same with the built-in monitor(because my built-in monitor was broken)
My device is a 2013 late 13-inch Macbook Pro with Intel Iris GPU

**Comment by idrohr** [comment]
I'm also getting this issue on a 13-inch retina, early 2015 MacBook pro running 10.15.4.

**Comment by danielkariv** [comment]
I think I got it fixed, sent the PR with the changes I made (#51718).
It seems that godot won't resize the screen when changing from or to fullscreen, and this is what lead to this weird behavior.
