### ISSUE TITLE
DirectionalLight missing directional_shadow_max_distance in editor

### ISSUE THREAD

**Issue by gdesecrate** [godotengine/godot#40060]
Godot Engine v3.2.2.stable.official

To change maximum directional_shadow_max_distance you have to script it's value.

**Comment by Calinou** [comment]
I can see it on Godot 3.2.2:

![image](https://user-images.githubusercontent.com/180032/86401277-3d78a380-bcaa-11ea-9e3a-fe0aa5101807.png)

**Comment by gdesecrate** [comment]
Oh! Why it is not in Shadow's tab?

**Comment by Calinou** [comment]
It's not in the Shadow tab because it's a property specific to DirectionalLight. (DirectionalLight, OmniLight and SpotLight all inherit from a base Light class.)
