### ISSUE TITLE
3.2.1 => 3.2.2 - degradation of the RichTextLabel (tag [fill])

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#40068]
**Godot version:**
3.2.2

**OS/device including version:**
All

**Issue description:**
And again ... again ... as always ... RichTextLabel is a disaster!
I updated Godot to version 3.2.2, after which the display of text in RichTextLabel everywhere broke in my project. Instead of justification (tag [fill]), chaotic artifacts are observed at the beginning and end of lines.

![00000](https://user-images.githubusercontent.com/11189223/86400381-2e492400-bcb1-11ea-8141-21bb0b27064c.jpg)

**Comment by bruvzg** [comment]
Regression form #39164

**Comment by akien-mga** [comment]
CC @theoway @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment]
My bad, I forgot to check fill alignment mode when testing #39164.

I'm preparing a quick fix to avoid changing the line offset with fill alignment, so we get back to the state it was in 3.2.1 for this case.
