### ISSUE TITLE
Regression.  Area2D to Area2D contacts are failing.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#40090]
**Godot version:**

44a516986db7722bb62c73d4b7a3f63c77cffea6 

**OS/device including version:**

Win10 64-bit

**Issue description:**

In my project I used Area2Ds as bullets and hit boxes for entities.  I reuse the bullets by disabling their collision masks and shapes, and re-enabling them when firing them again.

The first hits work, but following that, they cease to make contact.  From the debugger there is no indication that the masks are wrong or that the shape is not enabled.

The issue begins with this commit:  https://github.com/godotengine/godot/pull/39895

**Steps to reproduce:**
Have Area2Ds collide with each other, and disable and enable one, move it, then recollide them.

Using the project below, have the collision shapes visible, observe the first contact.  Then click the button to relaunch the process.  The second contact should fail.

**Minimal reproduction project:**

[Area2D Issue.zip](https://github.com/godotengine/godot/files/4869797/Area2D.Issue.zip)

**Comment by pouleyKetchoupp** [comment]
CC @madmiraal

**Comment by shayneoneill** [comment]
Theres no more 3.x bugfix releases before 4.0 drops? re the milestone tag?

**Comment by akien-mga** [comment]
There is, but the bug is also present in master / 4.0.
