### ISSUE TITLE
String.capitalize() doesn't work as documented

### ISSUE THREAD

**Issue by Wafflily** [godotengine/godot#40093]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 7 64 bits

**Issue description:**
> print("capitalize camelCase mixed_with_underscores".capitalize())
>  -> Capitalize Camel Case Mixed With Underscores

However, the doc states:
> Changes the case of some letters. Replaces underscores with spaces, converts all letters to lowercase, then capitalizes first and every letter following the space character. For _capitalize camelCase mixed_with_underscores_, it will return _Capitalize **Camelcase** Mixed With Underscores_.

**Steps to reproduce:**
It's just this single line of code:
> print("capitalize camelCase mixed_with_underscores".capitalize())

**Note:**
It's my first time posting on Godot github. I looked for the bug in the issue tracker by typing *capitalize* in the search bar and didn't find it. Please let me know what I can do better.
I tracked the capitalize() function down to *core/ustring.h*. I would correct it myself, but I don't know whether the code is wrong, or the doc is wrong.

**Comment by Calinou** [comment]
I'd argue the documentation is wrong. The behavior seems expected to me; this way, people writing exported variables in camelCase still get correct casing in the Inspector.

**Comment by bruvzg** [comment]
Code was changed in #12932, but documentation was not updated.
