### ISSUE TITLE
SkeletonIK not updating after the first time when Skeleton Animation is playing

### ISSUE THREAD

**Issue by Griefchief** [godotengine/godot#40099]
**Godot version:**
Godot 3.2.1 Stable official

**OS/device including version:**
Win10

**Issue description:**
SkeletonIK should update the pre solver skeleton bone positions after the first time it is created. It does not.

![image](https://user-images.githubusercontent.com/5757704/86489701-6c078480-bd65-11ea-9356-5743344f8f74.png)

 See video for example (root bone of SkeletonIK is upper left arm, and it's static, not following the animation, or any new anim/anim change in fact): https://youtu.be/anBwEMyRU-M

**Steps to reproduce:**
Just a regular SkeletonIK that is working together with AnimationPlayer (and or tree)
![image](https://user-images.githubusercontent.com/5757704/86489778-b0932000-bd65-11ea-831f-218a6495e74d.png)

Additionally, start() and stop() of SkeletonIK should be created in AnimationPlayer for every animation where SkeletonIK should run.
![image](https://user-images.githubusercontent.com/5757704/86489923-05cf3180-bd66-11ea-9cd1-686e4df57c17.png)

**Minimal reproduction project:**
[godot-3d-mannequin-SkeletonIK_Bug.zip](https://github.com/godotengine/godot/files/4870857/godot-3d-mannequin-SkeletonIK_Bug.zip)

This minimal reproduction project is also awailable here, SkeletonID_bug branch: 
https://github.com/Griefchief/godot-3d-mannequin/tree/SkeletonIK_bug

**Comment by Griefchief** [comment]
Seems fixed in 3.2.2 after I checked, was only released 6 days ago officially.
https://youtu.be/Ny4_8EJnVxQ

**Comment by snougo** [comment]
it has fixed in 3.2.2

**Comment by Griefchief** [comment]
Regression fixed by this commit. I suspect that updating the items pointer here updates the pointer of the bones, as this is the only change in SkeletonIK _update() function:

https://github.com/godotengine/godot/commit/277696d6c50eba68ca11cf3c0988be0213e5c65d#diff-33142f6c0baba2d89d20429c9ede7a44R147

Author: Andrea Catania <info@andreacatania.com>
Date:   Tue Mar 24 09:59:32 2020 +0100

    Fixed IK rotation issue

    (cherry picked from commit 277696d6c50eba68ca11cf3c0988be0213e5c65d)


git bisect log
git bisect start
 # new: [6a9fbafcbbd7954761fb17554ed08fb62e3554dd] Bump version to 3.2.2-stable
git bisect new 6a9fbafcbbd7954761fb17554ed08fb62e3554dd
 # old: [b0eca5828ccd3a5c07b77e82e567c45937de9056] Bump version to 3.2.1-stable
git bisect old b0eca5828ccd3a5c07b77e82e567c45937de9056
 # new: [c1cf8a5068f6dbe511210a4855fdd10f2f63ca7b] Tweak the editor log selection color to match the current editor theme
git bisect new c1cf8a5068f6dbe511210a4855fdd10f2f63ca7b
 # skip: [ade57c4bf0c54a04691797880dd0f0136a817ea6] Merge pull request #38099 from clayjohn/GLES2-skeleton-rebind
git bisect skip ade57c4bf0c54a04691797880dd0f0136a817ea6
 # skip: [3b44f34166a5efa068305a3160caa3415064990a] Merge pull request #38114 from lawnjelly/kessel_rulerfix
git bisect skip 3b44f34166a5efa068305a3160caa3415064990a
 # old: [36a30f681fc8c3256829616f32ee452b15674752] Merge pull request #37825 from qarmin/leak_with_drives
git bisect old 36a30f681fc8c3256829616f32ee452b15674752
 # new: [78f0cf40cb4a37b54a27da25349718d1c4b324e5] Merge pull request #38257 from RandomShaper/imvu/fix_variantrc_gdnative
git bisect new 78f0cf40cb4a37b54a27da25349718d1c4b324e5
 # new: [008e0748c158a3f9e307706ba5ffeb2c5a3f8a12] Merge pull request #37349 from lawnjelly/kessel32_1
git bisect new 008e0748c158a3f9e307706ba5ffeb2c5a3f8a12
 # new: [c0047023e6c1f3ca95f03371ddf9de716a466e97] NoiseTexture: prevent race condition because of Ref::unref()
git bisect new c0047023e6c1f3ca95f03371ddf9de716a466e97
 # new: [94f451e0702a6b4776abd5e013d514b5aaa7e2e2] Ensure COWData does not reallocate on push back, fixes #22561
git bisect new 94f451e0702a6b4776abd5e013d514b5aaa7e2e2
 # old: [373db277885606f493acae5faa86011c59442f9c] Migrate legacy apache dependency to the GodotPayment plugin
git bisect old 373db277885606f493acae5faa86011c59442f9c
 # new: [219ce2f14958321947073c1c78bc7eb429abaf79] Fix volume interpolation in positional audio nodes
git bisect new 219ce2f14958321947073c1c78bc7eb429abaf79
 # new: [a51e78528f20c410880b71c978f4038532d99659] Fixed IK rotation issue
git bisect new a51e78528f20c410880b71c978f4038532d99659
 # old: [96e381ac0371d129719b02140a06869c8063ae46] Validate supported architectures when exporting to Android
git bisect old 96e381ac0371d129719b02140a06869c8063ae46
 # first new commit: [a51e78528f20c410880b71c978f4038532d99659] Fixed IK rotation issue
