### ISSUE TITLE
ItemList's item_activated signal doesn't fire when select mode is set to "multi"

### ISSUE THREAD

**Issue by iatenine** [godotengine/godot#40104]
**Godot version:** 
3.2 stable

**OS/device including version:** 
Ubuntu 20.04, GLES2 (though not graphics related

**Issue description:** 
When trying to use item_selected signal (i.e. to make a "clicking" sound on transitions), nothing happens unless  

**Steps to reproduce:**
1) Create an Itemlist with at least one item to select
2) Set the Select mode to "Multi"
3) Connect the item_activated signal to a function with some form of output
4) Run to see nothing happen or switch mode to "single" to see the function begin to work as intended

**Minimal reproduction project:**
[item_list_signal.zip](https://github.com/godotengine/godot/files/4871236/item_list_signal.zip)

**Comment by iatenine** [comment]
Screenshot from the attached project that I believe fairly succinctly explains the issue

![Screenshot from 2020-07-03 13-27-40](https://user-images.githubusercontent.com/4423088/86494364-0cdc4c80-bd32-11ea-8b89-0e2d764e6cd0.png)

**Comment by avencherus** [comment]
There is a separate signal for multi-select.  Seems to handle the case with single selection too.  Maybe needs better documentation?

![image](https://user-images.githubusercontent.com/13004169/86515341-da5d4d00-be20-11ea-826c-2d4f7768df89.png)

**Comment by iatenine** [comment]
> There is a separate signal for multi-select. Seems to handle the case with single selection too. Maybe needs better documentation?
> 
> ![image](https://user-images.githubusercontent.com/13004169/86515341-da5d4d00-be20-11ea-826c-2d4f7768df89.png)

That works, thanks. While I would encourage docs clarification, it probably needs to be clarified in the "item_activated" signal, since the very name of the "multi_selected" signal led me to believe it was irrelevant when only selecting single elements
