### ISSUE TITLE
Modifying RigidBody rotation every frame prevents it from moving

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#40110]
**Godot version:**
3.2.2

**OS/device including version:**
Linux Mint 20

**Issue description:**
Modifying a RigidBody's transform (or a child shape's transform) in any way will prevent it from moving that frame.

The Ball should fall, but it is stuck in place

![2020-07-03 23-25-20](https://user-images.githubusercontent.com/14253836/86504953-9d437d00-bd84-11ea-96a7-a9d24f218477.gif)

**Steps to reproduce:**
Run the reproduction project
Test behaviour with different lines uncommented in `Ball.gd`

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/4872110/Test.zip)

**Comment by snougo** [comment]
it's not bug, and you shouldn't change physics body size instead you can change the children's size

<a data-flickr-embed="true" href="https://www.flickr.com/photos/189186320@N08/50074814041/in/dateposted-public/" title="屏幕快照 2020-07-04 17.56.39"><img src="https://live.staticflickr.com/65535/50074814041_61456d025b_n.jpg" width="320" height="202" alt="屏幕快照 2020-07-04 17.56.39"></a>

<a data-flickr-embed="true" href="https://www.flickr.com/photos/189186320@N08/50074239883/in/dateposted-public/" title="屏幕快照 2020-07-04 17.56.34"><img src="https://live.staticflickr.com/65535/50074239883_35c1f065ed_n.jpg" width="319" height="121" alt="屏幕快照 2020-07-04 17.56.34"></a>

<a data-flickr-embed="true" href="https://www.flickr.com/photos/189186320@N08/50075059307/in/dateposted-public/" title="屏幕快照 2020-07-04 17.56.27"><img src="https://live.staticflickr.com/65535/50075059307_6f0fd73910_n.jpg" width="320" height="104" alt="屏幕快照 2020-07-04 17.56.27"></a>

**Comment by nathanfranke** [comment]
This is unrelated to the rigidbody scaling bug. Try commenting out the scale code and using rotation instead.

**Comment by nathanfranke** [comment]
@snougo Okay, I changed the collision shape's scale, same issue :stuck_out_tongue: 
![image](https://user-images.githubusercontent.com/14253836/86522668-17c4d900-be27-11ea-8f1a-71f31b7caa41.png)

**Comment by snougo** [comment]
> @snougo Okay, I changed the collision shape's scale, same issue 😛
> ![image](https://user-images.githubusercontent.com/14253836/86522668-17c4d900-be27-11ea-8f1a-71f31b7caa41.png)

@nathanfranke you are right, and I even test $CollisionShape.shape.radius = 2.5 in _physics_process(delta), but I found it's ok in _process(delta)

**Comment by tavurth** [comment]
Perhaps this should raise an error in the development console if this is not intended behaviour?

**Comment by nathanfranke** [comment]
@tavurth Changing the scale of a CollisionShape at runtime is intended behaviour.

**Comment by nathanfranke** [comment]
Just changed the title so people would stop misinterpreting it.

**Comment by AndreaCatania** [comment]
Rotate the RigidBody in this way is not expected, and even if it may work, I don't recommend doing it.

Please, consider rotate the RigidBody using forces.

**Comment by ElliottjPierce** [comment]
I fixed my issue by putting the rigid body's would be children as children of an intermediary node and rotating the intermediary node instead.

Right now (4.0.2), directly rotating the rigid body prevents movement. Could we get at least a warning printed when this happens if it is not supported? There is a similar warning about scale, so I would love to see either this functionality added or a warning put up.
