### ISSUE TITLE
[Godot 4 feature request] Could emissive decals contribute to GI?

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#40125]
Hello,
when using an emissive texture as a decal, would it be technically possible to have that decal contribute to global illumination? Because unfortunately right now it doesn't.

**Comment by clayjohn** [comment]
Feature requests must be made in the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. So please make your request there. Also, remember to fill out the template.

**Comment by Calinou** [comment]
Remember that you could always parent a OmniLight or SpotLight to the decal.
