### ISSUE TITLE
3.2.2 language server with Threads is unusably slow

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot#40126]
**Godot version:**
3.2.2-stable

**OS/device including version:**
Windows 10 Pro 2004, AMD Ryzen 7 3800x, nVidia Geforce RTX 2080 SUPER

**Issue description:**
I initially blamed this on the transition to TCP/IP in https://github.com/godotengine/godot-vscode-plugin/issues/213, but I have found that the issue is actually cropping up when Threads is turned on in the language server settings. I took the following videos to show the issue in action. One was in 3.2.1, but the performance _without_ threads is about on par:

- 3.2.1 with websocket (about on par with TCP/IP without Threads) video: https://imgur.com/a/z6Z9ypI
- 3.2.2 with TCP/IP with Threads on video: https://imgur.com/a/QoQnWY3

**Steps to reproduce:**
- Turn on threads in language server
- Run VSCode with godot-tools extension set to TCP
- Try to use the LSP
- Turn off threads in language server
- Run VSCode with godot-tools extension set to TCP
- Successfully use the LSP

**Comment by Geequlim** [comment]
I can't reproduce this.
Compiled with 1ebfe84458373fbddf4e2b3b58d58e6a858fc662 on Arch Linux

**Comment by NathanLovato** [comment]
In Emacs here it's working fine, aside from the non-standard notifications of the server that trigger error messages at the moment (like "gdscript/capabilities").

**Comment by Anutrix** [comment]
Could be VSCode specific. @Razoric480 Do try another editor just to be sure.

**Comment by Razoric480** [comment]
Uhh, do you have a recommendation for another text editor for Windows that supports the GDScript LSP?

**Comment by Anutrix** [comment]
Nevermind. I didn't notice you were on Windows. My bad.
Not sure but emacs has a windows build iirc. Maybe that'll work.

**Comment by NathanLovato** [comment]
@Razoric480 Atom, Emacs, and Vim should all have lsp support for the Godot language server. And more now it's TCP-based.

**Comment by Razoric480** [comment]
I just ran lang-gdscript with Atom and indeed, the speed is just fine there with Threading on.

**Comment by Calinou** [comment]
@Razoric480  Can you (or anyone else) still reproduce this bug in [Godot 3.2.3](https://godotengine.org/article/maintenance-release-godot-3-2-3) or 3.2.4rc3?

**Comment by Razoric480** [comment]
Just tried it on 3.2.4rc3; it's nowhere near as bad as in the video I posted, but it is still significantly slower and not as responsive than without threading enabled.

https://user-images.githubusercontent.com/2823241/109438296-51ba9f00-79f7-11eb-8b47-c67d89e2c1fa.mp4

**Comment by Razoric480** [comment]
This appears to be fixed as of 3.4beta5, so I'll go and close the issue. Where it came from and what fixed it would need a bisect, and bisecting godot is a pretty tedious process, so... 🤷

**Comment by Igrium** [comment]
I'm sure it's 100% fixed.

I was having issues with the language server being slow, and I came across this thread so I turned off threading on the chance it might be the issue. No longer having issues. (4.4 btw)
