### ISSUE TITLE
Using yield gives return error in Vs custom node script.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#40120]
**Godot version:**
Godot 3.2.2 Stable

**OS/device including version:**
Windows 10 1909
NVIDIA GTX 1070 , Gefore Game Ready Driver 451.48 , 

**Issue description:**

Using `yield(Global.get_tree(), "physics_frame")`
In custom node scripts , gets your invalid return 
`Invalid return value from _step(), must be integer (seq out), or string (error).`

expected to wait one physical_frame before moving throw the script.

**Steps to reproduce:**

use 
`yield(Global.get_tree(), "physics_frame")`
before return

**Comment by KoBeWi** [comment]
Inactive issue and not enough details, closing.
