### ISSUE TITLE
C# scripts created outside of the Godot Edtior "New Script" dialog do not work

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#40134]
**Godot version:**
3.2.2 Stable

**OS/device including version:**
WIN 10

**Issue description:**
If I create a C# Script via the godot editor "New Script" option, and I attach it to a node, it works just fine. However, if I make a script via VS Code "New File", and put the exact same contents in the file, it does not work.

**Steps to reproduce:**
As above. Create a file via the editor, then create one outside it. The first will work, the second will produce error 
```
can_instance: Cannot instance script because the class 'NotMadeInGodotScript' could not be found. Script: 'res://NotMadeInGodotScript.cs'.
  <C++ Error>   Method failed. Returning: __null
  <C++ Source>  modules/mono/csharp_script.cpp:2942 @ can_instance()
```

**Minimal reproduction project:**
[TestSharp.zip](https://github.com/godotengine/godot/files/4874903/TestSharp.zip)

**Comment by JupiterRider** [comment]
Take a look into your `TestSharp.csproj` file:

You'll see the following part:
```
  <ItemGroup>
    <Compile Include="MadeInGodotScript.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
```

You have to add your script there. Like that:
```
  <ItemGroup>
    <Compile Include="MadeInGodotScript.cs" />
    <Compile Include="NotMadeInGodotScript.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
```

**Comment by EricEzaM** [comment]
That does it, thanks!
