### ISSUE TITLE
texelFetch for Vulkan by default

### ISSUE THREAD

**Issue by Wesxdz** [godotengine/godot#40142]
master 0287508
RTX 2070 SUPER, KDE Neon

Migrating project to Vulkan renderer,
texelFetch fails to compile, reports
```
E 0:00:00:0463   _compile_variant: Failed parse:
ERROR: 0:564: 'texelFetch' : required extension not requested: GL_EXT_samplerless_texture_functions
ERROR: 0:564: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
  <C++ Source>   servers/rendering/rasterizer_rd/shader_rd.cpp:335 @ _compile_variant()
```

**Steps to reproduce:**
Create a shader material with texelFetch

**Comment by Chaosus** [comment]
Yeah, I see the same bug on Windows/GTX1060 too

**Comment by Calinou** [comment]
For the record, this doesn't appear to be related to #40133.
