### ISSUE TITLE
Search Help showing no results for "OS"

### ISSUE THREAD

**Issue by batmanasb** [godotengine/godot#4014]
**Operating system or device:**
Linux Mint 17.3

**Issue description** (what happened, and what was expected):
When using "Search Help" to search classes in the engine, I noticed that for some reason you can't directly search for the OS class because the search only starts with a minimum for 3 characters. So the simple workaround is just to search "OS." and press on one of the methods, but it's still a little awkward.

**Steps to reproduce:**
1. Press "Script"
2. Press "Search Help"
3. Type in "OS"
4. Then type "OS." to get results but no direct "OS (class)" search result

**PS**
Sorry for wasting your time with such a tiny issue... but my "OCD" made me do it :(

**Comment by neikeq** [comment]
I would like the minimum search length to be increased to 3 characters too.

**Comment by akien-mga** [comment]
> I would like the minimum search length to be increased to 3 characters too.

That's how it works currently no? The bug report is more about the fact that "OS" has only 2 characters, so the search does not run.

**Comment by neikeq** [comment]
@akien-mga Ops... I meant 2 characters :P

**Comment by akien-mga** [comment]
As long as the performance is fine, I don't have anything against decreasing the limit to 2 characters.

**Comment by batmanasb** [comment]
Either decreasing the minimum limit to 2 characters or added a special exception for "OS". Preferably the former, but if performance ever tanks, than the later.

**Comment by neikeq** [comment]
`OS` is not the only problem. There is also `IP` and classes that start with two important characters. For example, when I am looking for _GDScript_ related classes (like _GDFunctionState_ or _GDNativeClass_), I search `GD`.

**Comment by demolitions** [comment]
I'd like to try and tackle this, as it seems to require a very simple change in tools/editor/editor_help.cpp
Any advice to compile Godot from a forked repo?

**Comment by akien-mga** [comment]
>  Any advice to compile Godot from a forked repo?

Compiling from a forked repo is the same as compiling from the main upstream one. You need to clone your fork (or add it as a remote and fetch it, depending on how proficient you are with git), make your changes, build with scons, test, and if the changes are good commit them and push them to your fork to make a pull request.

**Comment by bojidar-bg** [comment]
Close?

**Comment by akien-mga** [comment]
Fixed by 2bc4049.
