### ISSUE TITLE
no export entry in editor settings

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#40159]
**Godot version:**
3.2.2-stable 6a9fbafcb

**OS/device including version:**
windows 10

**Issue description:**
editor settings does not have an export setting
cannot follow https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html

**Steps to reproduce:**
open settings
search for export or rcedit

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
I can't reproduce. Scroll down in the Editor Settings to find it, or search "Export".
![Screenshot_20200706_145448](https://user-images.githubusercontent.com/4701338/86595195-a5740600-bf98-11ea-9c8b-7b841bb564c7.png)

Are you searching the Project Settings maybe?

**Comment by scottkunkel** [comment]
Yes! I am!

Thanks!
