### ISSUE TITLE
Translated strings shouldn't escape '\n'

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#4016]
**Operating system or device:** Linux

**Issue description** I have a couple of strings which have '\n' in the middle (bigger sentences). When calling tr(), the returned string has '\n' as a string instead of a newline character, thus messing up the final result. I confirmed this by doing a ``tr('string').replace("\\\n","\n")`` which produced the intended result.

**Comment by akien-mga** [comment]
Probably related to #1232.

**Comment by bojidar-bg** [comment]
@nunodonato ~ Note that the CSV "standard" allows newlines to be made like this:
````csv
id,en
MLT,"Multiline
test"
````

**Comment by nunodonato** [comment]
good to know.. but it seems to be removed in the translated string too, so still won't solve the problem

**Comment by bojidar-bg** [comment]
@nunodonato check #4337

**Comment by akien-mga** [comment]
Is this bug still valid after #4337?

**Comment by 29jm** [comment]
I just tested it and it works now, this can be closed.
