### ISSUE TITLE
Compilation error for ios or mac

### ISSUE THREAD

**Issue by cemeai** [godotengine/godot#40168]
**Godot version:**
3.2

**Issue description:**
I try running 
scons platform=osx arch=x86_64 --jobs=$(sysctl -n hw.logicalcpu) 
and 
scons p=iphone tools=no target=release arch=arm

I keep getting the same issue
can_build() takes 1 positional argument but 2 were given

I looked into this and I know can_build was updated to receive 2 parameters, but for some reason I dont have that. I am pointing to the master branch and did a pull before doing the command.

Is there something im missing what do you recommend I do, not sure where to look to solve this

**Comment by akien-mga** [comment]
The `master` branch is Godot 4.0, not 3.2.

The error comes from a thirdparty module that you must be using and whose `config.py` is not compatible with the version of Godot you're building.

The error is weird though as `can_build` takes **2** arguments both in `3.2` and in `master`, and not **1**. Are you sure the error is not the other way around? Otherwise you might be building a very old Godot branch instead.

**Comment by cemeai** [comment]
My bad, thought the latest was 3.2, I'll try switching to 3.2. but yeah i am sure that the message from the console. It asks for 1 argument and 2 is given.

This is the full console message

```
scons platform=osx arch=x86_64 --jobs=$(sysctl -n hw.logicalcpu)
scons: Reading SConscript files ...
Building for macOS 10.12+, platform x86-64.
TypeError: can_build() takes 1 positional argument but 2 were given:
  File "/Users/cesar.amaro/Documents/godot-3.2/SConstruct", line 544:
    if config.can_build(env, selected_platform):
```

**Comment by akien-mga** [comment]
Ok, so yes, it means you have a thirdparty module whose `can_build()` definition only takes one argument and not two. So it's not suitable for Godot 4.0.

**Comment by akien-mga** [comment]
If you want to build Godot 3.2, you should use the `3.2` branch (3.2.3-beta) or a tag specific to a stable version (e.g. `3.2.2-stable`).

**Comment by cemeai** [comment]
Got it, also how can you tell is a third party I could not pick that up from that :/

**Comment by akien-mga** [comment]
Well I know that all modules part of the Godot repository compile fine, so it must be a module that you added yourself (thus it's a third party module).

**Comment by cemeai** [comment]
Noted, apologies

**Comment by akien-mga** [comment]
No problem :)

I'll close as it's not an engine issue then. If this module comes from a thirdparty with a public issue tracker, you should open an issue there to ask them to update their `config.py` for Godot 3.1+.
