### ISSUE TITLE
Ambient Light on macOS a tenth of the power of same value on Windows

### ISSUE THREAD

**Issue by tanskudaa** [godotengine/godot#40170]
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10: GeForce GTX980, 442.50, GLES3
macOS Mojave 10.14.6: MacBook Air (13-inch, Early 2015) 1.6GHz model, GLES3

**Issue description:**
On macOS, an Ambient Light energy of 10 is the equivalent to 1 in Windows, Vice versa, on Windows a value of 0.1 is equivalent to 1 on macOS.

**Steps to reproduce:**
On both systems, create a new project
Create a new scene with a Spatial as root node
Add WorldEnvironment
Use default_env.tres created by Godot
Set Ambient Light color to white
Tweak Ambient Light energy

**Minimal reproduction project:**
[amb-light-bug-reprod.zip](https://github.com/godotengine/godot/files/4881348/amb-light-bug-reprod.zip)

**Comment by Calinou** [comment]
> reproduces on any project

We'd prefer to have a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) available so we don't have to spend time setting one up.

**Comment by akien-mga** [comment]
Does this MacBook support OpenGL 3.3? If not it might fallback to the GLES2 renderer, and if so the difference might be expected.

**Comment by tanskudaa** [comment]
According to Apple (https://support.apple.com/en-us/HT202823) that model supports OpenGL up to 4.1 (and OpenCL up to1.2). It uses Intel HD Graphics 6000 internally. Godot does state in project settings that GLES3 is in use.

Adding reproduction project file.

**Comment by JohanAR** [comment]
This is what it looks like on Linux with different ambient light energy values:

![amb-light-linux](https://user-images.githubusercontent.com/4918549/86733506-8aa1a000-c031-11ea-9630-436bed0b1db3.jpg)

I've noticed before that you get weird effects if your environment has background energy while ambient light is very low (e.g. bg energy 1 and amb light energy 0.01). It seems to add a grey specular shine to all objects regardless of how much light they receive, causing shadows to look like plastic if you have Ss Reflections enabled.

**Comment by tanskudaa** [comment]
> This is what it looks like on Linux with different ambient light energy values:

That's what it looks like on Windows for me, too.

This is my Mac on levels 1 and 10:
![Näyttökuva 2020-7-7 kello 15 21 03](https://user-images.githubusercontent.com/33719898/86780643-a32bad80-c065-11ea-86ce-eb165c2a3061.png)
![Näyttökuva 2020-7-7 kello 15 21 08](https://user-images.githubusercontent.com/33719898/86780663-a757cb00-c065-11ea-8455-3388bb34c432.png)

It doesn't go to 100, of course. 16 is the maximum and just slightly brighter than 10.

**Comment by JohanAR** [comment]
It would be interesting to know if it's the same for other Mac users.

If you add lights and materials to your scene, is it still too dark or does this only apply to ambient light on objects without a material?

**Comment by tanskudaa** [comment]
>If you add lights and materials to your scene, is it still too dark or does this only apply to ambient light on objects without a material?

Lights seem to work the same, which is interesting.

Here's pictures of Mac with omnilight on (2,2,2), with ambient light at 1 and 10:
![Näyttökuva 2020-7-11 kello 15 28 46](https://user-images.githubusercontent.com/33719898/87224175-ac7d8880-c38b-11ea-8e4c-1cc6cbbfede8.png)
![Näyttökuva 2020-7-11 kello 15 28 53](https://user-images.githubusercontent.com/33719898/87224176-b0110f80-c38b-11ea-92d8-8d98d24b6316.png)

And here's Windows with an identical setup, with ambient light at 0 and 1:
![windows-0](https://user-images.githubusercontent.com/33719898/87224184-bd2dfe80-c38b-11ea-8a95-dc2698c1bc91.png)
![windows-1](https://user-images.githubusercontent.com/33719898/87224186-bef7c200-c38b-11ea-87a9-a91dc3db35e0.png)

**Comment by asmaloney** [comment]
> It would be interesting to know if it's the same for other Mac users.

Another data point - seems to look correct for me on macOS 10.14.6.

iMac (Retina 5K, 27-inch, 2019)
Godot Engine v3.2.3.beta.mono.custom_build.[af35d0d3c](https://github.com/godotengine/godot/commit/af35d0d3c83161848fad952f24d42592b1a9b932)
OpenGL ES 3.0 Renderer: AMD Radeon Pro 580X OpenGL Engine

I loaded the repro project and only changed the Ambient Light Energy:

<img width="1353" alt="Screen Shot 2020-07-21 at 20 42 04 PM" src="https://user-images.githubusercontent.com/391371/88121298-4b2b9580-cb93-11ea-96f9-cfa1fc053410.png">
<img width="1353" alt="Screen Shot 2020-07-21 at 20 42 14 PM" src="https://user-images.githubusercontent.com/391371/88121307-5088e000-cb93-11ea-9be4-53078ac30d25.png">

**Comment by clayjohn** [comment]
@asmaloney Same OS version. But very different GPUs. Could be a driver issue then.

@tanskudaa Have you tried updating your GPU drivers recently? If not, please do and let us know how it goes.

**Comment by asmaloney** [comment]
> Have you tried updating your GPU drivers recently? 

One does not (cannot?) explicitly update drivers on macOS. As long as you are up-to-date on patches, you have the latest drivers from Apple.

I just tried this on my MacBook Pro and it works properly for me.

macOS 10.14.6
MacBook Pro (15-inch, 2016)
Godot Engine v3.2.3.beta.mono.custom_build.af35d0d3c
OpenGL ES 3.0 Renderer: AMD Radeon Pro 450 OpenGL Engine

This machine has two GPUs - the second one is an Intel HD Graphics 530 1536 MB - and macOS switches between them on-the-fly. It would be nice to try the Intel one, but I don't know if there's a way to force it. It always switches to the Radeon Pro when I run Godot.

**Comment by akien-mga** [comment]
@asmaloney Maybe you can force using the integrated GPU instead of the discrete one with https://codyschrank.github.io/gSwitch/ ?

But yes this sounds like a bug in macOS's Intel OpenGL drivers, and possibly only in older Intel generations like HD 3000/4000/6000. It should probably be reported to Apple, though they will probably not bother as their OpenGL support is deprecated.

Another possibly would be if Godot's shader uses a different codepath because the hardware doesn't support some features, and this path ends up looking different, which would be fixable in Godot. But I don't know if that's the case.

**Comment by asmaloney** [comment]
I was nervous about forcing it with gSwitch since I'd read some Bad Things (tm) and it doesn't claim to support recent machines/OS versions.

Tried it anyways.

gSwitch acts a little funny (it forces sometimes, but then switches to the Radeon, and the menus checkmarks don't work properly), but I did eventually get it to run with the Intel GPU and I think (?) it stays on it while running Godot.

OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 530

...and it looks correct.

**Comment by tanskudaa** [comment]
That's really puzzling. My MacBook has all critical updates installed that Apple offers, but I'm not updating it past 10.14.6 since 10.15 onwards drops 32-bit executable support. Still, should be up to date.

**Comment by Calinou** [comment]
@tanskudaa Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release? Also, can you reproduce this when using GLES2?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
