### ISSUE TITLE
Saving a layout with an accent in the name shows the wrong character when changing layouts

### ISSUE THREAD

**Issue by 01271** [godotengine/godot#40172]
**Godot version:**
3.2.2 mono stable

**OS/device including version:**
OSX 10.14.6

**Issue description:**
Saving a layout with an accented E in the name makes a layout with a name that's messed up.
Here's what the name should be:
![Capture d’écran, le 2020-07-06 à 15 08 56](https://user-images.githubusercontent.com/3951049/86654602-ebca6480-bf9a-11ea-8768-6192525dd57f.png)

Here's what the name looks like when I go to Editor -> Editor Layout.
![Capture d’écran, le 2020-07-06 à 15 09 10](https://user-images.githubusercontent.com/3951049/86654613-ed942800-bf9a-11ea-9a7d-b69cd0cfefc6.png)

**Steps to reproduce:**
Go to Editor -> Editor Layout -> Save Layout
Save a layout with a name that includes an accented character.
Go to Editor -> Editor Layout 
The name will be messed up.

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/18c51d3f0c4ddf0bdf347638ca2d781a42de16d2.

**Comment by 01271** [comment]
In my experience this sort of issue is due to different character encoding for saving /loading.

**Comment by Calinou** [comment]
For the record, I tested this on Fedora 31. `file` recognizes `editor_layouts.cfg` as being UTF 8-encoded:

```text
editor_layouts.cfg: UTF-8 Unicode text
```

**Comment by akien-mga** [comment]
Most likely the section is parsed by ConfigFile as ascii and not UTF-8.

**Comment by Calinou** [comment]
It looks like ConfigFile defers its parsing to VariantParser. It has one occurrence of `ascii` here, but I'm not sure if it's related: https://github.com/godotengine/godot/blob/0fa165f0c936411a775bb41f362da394074b797f/core/variant_parser.cpp#L290
