### ISSUE TITLE
Blur & Angular Distance don't affect BakedLightmap

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#40177]
**Godot version:**
master (d0e0a19)

**OS/device including version:**
NVIDIA GeForce GTX 1060 6GB 
Driver 451.48
Windows 10 Home
Backend: Vulkan

**Issue description:**
The DirectionalLight3D node contains the properties of Blur and Angular Distance. These work in realtime however they don't affect BakedLightmaps - the lightmaps always have sharp shadows, regardless of the Blur and Angular Distance values.

**Steps to reproduce:**
Create a test scene which contains a BakedLightmap node and meshes with a UV2 channel for lightmap baking. Create a DirectionalLight3D and modify the Blur and Angular Distance values. Set the DirectionalLight3D's bake mode to Static. Bake the lightmaps and notice the modifications made to Blur and Angular Distance have not affected the lightmap.

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4885006/ReproductionProject.zip)

This reproduction project shows that the modified DirectionalLight Blur and Angular Distance values have not changed the result of the bake. You can enable the visibility of the DirectionalLight to see how it was meant to be baked.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/52199, which has more information about the issue at hand.
