### ISSUE TITLE
Closing a scene with built-in script opened will open a Save Resource dialog

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40175]
**Godot version:**

3.2.3 beta 07b24de (and probably master)

**Steps to reproduce:**
1. Create/open a built-in script so it appears in the script editor
2. Close the scene tab

**Comment by akien-mga** [comment]
Probably related to 35523a46c0d948ff3c578de6808a08233b0e81c9 / #40008, CC @DanielZTing.

**Comment by DanielZTing** [comment]
Well, this is embarrassing. I'll have to add a check for built-in scripts ASAP
