### ISSUE TITLE
missing FileDialog MODE_OPEN_ANY

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#4019]
I need a way to set FileDialog.MODE_OPEN_DIR and FileDialog.MODE_OPEN_FILE
I can't see a flag for it. Setting no mode results in a save dialog I need a open dialog.

Can someone confirm that this feature is not implemented?

Looks easy to implement.
https://github.com/godotengine/godot/blob/e46e43d2aaa6339a1675eb989f41885e745bf5c3/scene/gui/file_dialog.cpp
https://github.com/godotengine/godot/blob/e46e43d2aaa6339a1675eb989f41885e745bf5c3/scene/gui/file_dialog.h

**Comment by bojidar-bg** [comment]
It looks like those constants are bound, unless I'm missing something?
https://github.com/godotengine/godot/blob/e46e43d2aaa6339a1675eb989f41885e745bf5c3/scene/gui/file_dialog.cpp#L710-L713

**Comment by neikeq** [comment]
@bojidar-bg I am not sure, but I think he mean a mode to open both files and directories.
