### ISSUE TITLE
AppVeyor - full rebuild / not working (4-5 attempts)

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#40190]
**Godot PR which will not build on appveyor :**
https://github.com/godotengine/godot/pull/40148

**Issue description:**
We have rebuilt this PR approximately 4-5 times already on request but it's not passing; not because of the PR mainly because of appveyor having a hard limit of 60m per build, which is reasonable but the resource allocated to the builds doesn't seem to be enough to complete the entire Godot build.

Honestly not got many ideas, apart from possibly splitting up or lowering the complexity of the stuff run on appveyor.

We discussed on IRC this but wanted to put an issue in for it, just in case someone has the same issue, so not really that critical I'd just like it if we can fix it somehow

**Steps to reproduce:**
1. Rebuild my pr in appveyor #40148
2. Build times out with "Build execution time has reached the maximum allowed time for your plan (60 minutes)."

I hope we can fix this somehow, I can manually do the testing on windows to temporarily work around this but we possibly need a more bulletproof solution.

**Comment by RevoluPowered** [comment]
Working on this here https://github.com/godotengine/godot/pull/40191

will try and rule out my PR by doing a clean build, it could also be a caching issue

**Comment by RevoluPowered** [comment]
Relevant fix ;) #40213  🔥 🚒

**Comment by akien-mga** [comment]
Fixed by #40282.
