### ISSUE TITLE
GraphEdit does not support multi-node selection

### ISSUE THREAD

**Issue by TomNCatz** [godotengine/godot#40196]
Godot version: 3.2.1.stable.mono
OS: Windows 10
Issue description: In the window you can click and drag to select multiple nodes and move them this way, however this does not send a selection signal. 
node_selected is only sent when a single click on a node happens. 

Steps to reproduce:
1 make a GraphEdit node with several GraphNodes in it
2 listen to the node_selected signal and GD.Print something when it is fired
3 play the app
4 click drag to select multiple nodes without directly clicking on a node
5 no text will be printed

Minimal reproduction project:
[NodeDemo.zip](https://github.com/godotengine/godot/files/4887703/NodeDemo.zip)

**Comment by Zylann** [comment]
I worked on a graph tool recently as well and I can confirm this (my local build is from 3.2.2 beta.custom_build.7b56111c2)

**Comment by breadnone** [comment]
This happens to me...

**Comment by mrushyendra** [comment]
Presumably needs some change like the following:

```
@@ -849,10 +851,15 @@ void GraphEdit::_gui_input(const Ref<InputEvent> &p_ev) {
                        r.size *= zoom;
                        bool in_box = r.intersects(box_selecting_rect);
 
-                       if (in_box)
+                       if (in_box) {
+                               if(!gn->is_selected() && box_selection_mode_additive) {
+                                       emit_signal("node_selected", gn);
+                               }
                                gn->set_selected(box_selection_mode_additive);
+                       }
                        else {
                                gn->set_selected(previus_selected.find(gn) != NULL);
                        }
                }
 
                top_layer->update();
```

Will do more testing to see if it works
