### ISSUE TITLE
Tilemaps not rendering correctly 

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [godotengine/godot#40206]
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10/GLSE3

**Issue description:**
I built a platformer game in godot. It gets rendered like this. This project is actually ported from previous version.
![image](https://user-images.githubusercontent.com/37043052/86908347-02f08a00-c134-11ea-94cf-702c8a260776.png)

While when i opened the project  in previous godot software i'm using, same map gets rendered like this:-
![image](https://user-images.githubusercontent.com/37043052/86908226-d3418200-c133-11ea-9f8a-c8f4640ecfcb.png)

A easy solution would be change position of tiles but this game generate infinite platform which means i need to change the logic of level generation. I also noticed that sometimes texturebutton work on double click while in previous version it work on single click.

**Comment by Zireael07** [comment]
Which version is 'previous version'? Also what is your GPU?

**Comment by KoBeWi** [comment]
Does it happen in a fresh project? (with the same tileset/scene)
If yes, you could attach it here.

**Comment by GAGANsinghmsitece** [comment]
Previous Godot:- 3.1.2
Current godot:- 3.2.2
GPU:- Intel HD graphics 620

**Comment by akien-mga** [comment]
That's an expected change since Godot 3.2, see the `CHANGELOG.md`:
```
- TileMap support for transform operations on cell textures bigger than the cell size has been reworked to properly support isometric tiles.
  - Breaks compatibility with some TileMaps from previous Godot versions. An opt-in `compatibility_mode` property can be used to restore the previous behavior.
```

Use the `compatibility_mode` property to keep the previous behavior, or change your tilemaps or tileset.

**Comment by GAGANsinghmsitece** [comment]
Yes, this solves the problem. Thanks for support
