### ISSUE TITLE
Able to down size windows below the min size, but bounces back immediately

### ISSUE THREAD

**Issue by hnOsmium0001** [godotengine/godot#40202]
**Godot version:**
`d0e0a19e4daa88b91613d92b0520035a1c4f5e9a`

**OS/device including version:**
Windows 10

**Issue description:**
When trying to down size a window, it should stop at whatever the minimum size is. But currently you can continue beyond the minimum size and it will bounce back, causing a weird graphical effect.

**Steps to reproduce:**
1. Open godot
2. Open any popup window with a min size (for example scan projects in the launcher)
3. Try to down size the window

**Minimal reproduction project:**
(able to reproduce in any project or even without one (in the launcher))

**Comment by Calinou** [comment]
This is most likely a regression from DisplayServer. Can you reproduce this bug in 3.2.2 (just in case)?

**Comment by hnOsmium0001** [comment]
It works perfectly fine (stops at min size) in 3.2.2, which doesn't have popups as separate windows.

**Comment by KoBeWi** [comment]
Can't reproduce in 96ffcc4d52029d5712e1a7b8d454c5751c26ceb0
