### ISSUE TITLE
Crash importing glb file with genlightmap enabled

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot#40219]
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10 / 64bit

**Issue description:**
When importing a specific GLB file with `gen light maps` enabled in import options, the Editor crashes with the following error:
```
File: thirdparty/xatlas/xatlas.cpp, Line 814
Expression: !isZero(l, epsilon)
```
I *think* this may be a regression since 3.2.1, but haven't gone back and tested yet.

**Steps to reproduce:**
With a specific GLB file, select "gen light maps" on import options and reimport.

**Minimal reproduction project:**
This opening this will cause the crash because it will attempt to import.
[glb_crash.zip](https://github.com/godotengine/godot/files/4893256/glb_crash.zip)

**Comment by qarmin** [comment]
Crash is fixed in 3.2.4.beta.custom_build. 185520c5b

**Comment by lionxvibe** [comment]
@qarmin Are you really sure that https://github.com/godotengine/godot/commit/185520c5b016a34affa1ebe6147a583c9a186e40 fix this ? I only see fix about multi touch

**Comment by akien-mga** [comment]
He meant that it's the commit he tested (recent commit in the `3.2` branch). The actual commit that fixed it was likely made earlier.

**Comment by lionxvibe** [comment]
@akien-mga Great 🥇 Sorry for the misunderstanding
