### ISSUE TITLE
Cancel/OK button order not respected on macOS

### ISSUE THREAD

**Issue by DanielZTing** [godotengine/godot#40216]
**Godot version:**

master (18c51d3f0c4ddf0bdf347638ca2d781a42de16d2)

**OS/device including version:**

macOS Catalina 10.15.5 (19F101)
MacBookAir8,1

**Issue description:**

macOS platform conventions specify "cancel" should be on the left and "OK" should be on the right, but this is swapped.

**Steps to reproduce:**
1. Quit the editor

Notes: I believe this was introduced in commit 15a9f94346c211b7afe96af500cb3405aabcf6b8 in `platform/osx/display_server_osx.mm`:

```cpp
bool DisplayServerOSX::get_swap_ok_cancel() {
	return true;
}
```

At first I was confused because if a function named `get_swap_ok_cancel` returns true, that should mean dialogs display "cancel/OK," right? But according to my testing it's the other way around. If there's not a specific reason why this was changed, I can just make it return `false`. I also propose renaming the function to `get_swap_cancel_ok` or at least adding a clarifying comment.

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
In 3.2 it was `false` on all platforms except Windows and UWP, name is confusing indeed, it was copy/pasted during OS/DisplayServer split and should be changed to return `false`.
