### ISSUE TITLE
16-bit depth PNG too bright when imported as texture

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot#40214]
**Godot version:**
3.2.2
and also on master 6e55a4fe8c799b5f19e03e9cdc959772efeedc55

**OS/device including version:**
Xubuntu 20.04, GTX1080

**Issue description:**
16-bit depth PNG images become brighter when imported into Godot. Flat surfaces

**Steps to reproduce:**
Place a 16-bit depth PNG file in a Godot res:// directory so it is imported

**Minimal reproduction project:**
[png16.zip](https://github.com/godotengine/godot/files/4892499/png16.zip)

![png16](https://user-images.githubusercontent.com/4918549/86955420-d189b580-c157-11ea-96e1-c4a1f633a9c6.png)

Providing a screen shot in case it's caused by some third party library and not reliably reproducible. The images look identical outside Godot.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/37220? Godot doesn't support 16-bit PNG images. To import HDR images, you need to use the Radiance HDR (`.hdr`) or OpenEXR (`.exr`) formats instead.

**Comment by JohanAR** [comment]
Yep, didn't find it when I was searching for old tickets
