### ISSUE TITLE
The UI for the Godot editor doesn't display any text.

### ISSUE THREAD

**Issue by Zekronz** [godotengine/godot#4021]
Windows 7 Home Premium
ATI Mobility Radeon HD 4500 Series Version 8.632.1.2000
Pentium Dual-Core T4200 2,00GHz

When i open Godot, the user interface doesn't display any text. Here is an image:
http://i.imgur.com/hfZMBYz.png

**Comment by reduz** [comment]
install driver from vendor

**Comment by vnen** [comment]
Any further info on this?

**Comment by vnen** [comment]
Seems like the same as #686, closing as duplicate.
