### ISSUE TITLE
Rendering for YSort and runtime appended children don't work properly

### ISSUE THREAD

**Issue by itsbrainmeat** [godotengine/godot#40224]
**Godot version:**
3.2.2

**OS/device including version:**
Windows10
OpenGL ES 2.0 Renderer: GeForce GTX 1060/PCIe/SSE2 (also tried with OpenGL ES 3)

**Issue description:**

_I'm fairly new to Godot and I might be doing something wrong._

My assumption is that this looks like an usual thing to do, but it seems it works for everyone but me. I saw one issue reported: https://github.com/godotengine/godot/issues/39872; but it wasn't well explained.

What I want to do is spawn objects under YSort in runtime. What happens is that editor setup objects under YSort works normally, but when I instantiate and append to YSort, the sorting does not work properly. 

I also tried with Tilemap and YSort property enabled (tried different origin types).

One of the characteristics of the objects is that they contain 2D rigid bodies. 

Image example:

![ysort_runtime_add](https://user-images.githubusercontent.com/44280034/87000324-7be7f400-c1bd-11ea-96d6-f27e2473baaf.PNG)

The image above shows two groups, the marked in red are the ones that were setup in the editor and the ones marked in blue were spawned in runtime.

**Steps to reproduce:**

1. Open the attached project
2. Run
3. Just click the left mouse button or press and hold, drag (not much), then release
4. Watch it spawn some objects and see what I described (and what the image shows)

or

1. Create a project
2. Add Node2D as a root
3. Add an YSort child
4. Create a script that appends another scene node (with a rigibody2d and a sprite centered, without gravity, and a circle collider smaller than the sprite) to the YSort node
5. Observe the objects intersection (colliders must be smaller than the sprite)

**Minimal reproduction project:**

[ysort-test.zip](https://github.com/godotengine/godot/files/4894711/ysort-test.zip)

**Extras in project (Optional)**

In Enemy.gd I have a _physics_process() function that just updates the Sprite position based on Rigidbody2D position. I do this because I don't want the sprite to rotate. I tried Character mode, but the physics behave weirdly, the collision resolution looks really off for what I want. Any tips?

**Comment by itsbrainmeat** [comment]
I have to add that while trying with Tilemap with YSort enabled, the runtime instanced objects are sorted correctly with the tiles, but not within themselves.

**Comment by lawnjelly** [comment]
I had a look. The reason they aren't sorting seems to be that their y positions are the same. (Look in the remote scene tree at runtime).

I haven't looked in detail at your project, but probably the position is stored on something lower down in the scene tree for the objects.

**Comment by itsbrainmeat** [comment]
@lawnjelly you're right, because I'm moving the rigid body, but the root stays where it spawns. I'm closing it.
