### ISSUE TITLE
OptionButton item cannot be selected due to immediate closing after mouse released

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#40227]
**Godot version:**
d629b17291347b20ef3730f97f484e807ac07f1a

**OS/device including version:**
Win10

**Issue description:**
![menu_bug](https://user-images.githubusercontent.com/3036176/87016030-d80b4200-c1d6-11ea-9b72-492a633d82bd.gif)

Note: this bug appears only if "Single Window Mode" is enabled in Editor settings

**Comment by akien-mga** [comment]
I wonder if #40226 fixes that?

**Comment by akien-mga** [comment]
> I wonder if #40226 fixes that?

Tested, it's still reproducible after that PR.

**Comment by aaronfranke** [comment]
Interestingly, this doesn't seem to happen for every `OptionButton`. For example, in #42447, in the new "Project -> Version Control -> Create Version Control Metadata" menu, the OptionButton works fine in single window mode for me, but it doesn't work in the Attach Script menu as described here in the OP.

**Comment by Calinou** [comment]
I can't reproduce this issue on latest `master` on Linux with single-window mode enabled. Can anyone else still reproduce this?

**Comment by Chaosus** [comment]
Yep, seems fixed!
