### ISSUE TITLE
Tooltip of editor doesn't shown up when launched while certain game running

### ISSUE THREAD

**Issue by runapp** [godotengine/godot#40220]
**Godot version:**
Godot Engine v3.2.2.stable.official

**OS/device including version:**
Windows 10 1809
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2

**Issue description:**
I've suffered from tooltip not showing up. After some investigation, I finally found the main cause was a game named World of Warships by wargaming.net .
Basically, if a godot editor is launched while the game running, any tooltip (both of toolbar icons and of properties) won't show up. If the game exits, all running godot instance affected immediately behaves normal.
Instance launched before the game starts remains normal after that.
I've tried removing all settings (%appdata%\Godot) but no help.

**Steps to reproduce:**
1. Run godot editor, and load/create a project (refers to godot A)
2. Run World of Warships (the game)
3. Run another godot editor, and load/create a project (refers to godot B)
4. Check if godot A has normal tooltip, and godot B doesn't show any
5. Quit World of Warships
6. Check if godot B shows tooltip now

**Minimal reproduction project:**
Any blank project is sufficient.

**Comment by runapp** [comment]
I don't know if it's worth opening an issue about it, cause the game is not a common application for daily use. Anyway feel free to close (and delete if needed) this issue if you think it's not appropriate, and take my sincere apologies.

**Comment by Calinou** [comment]
Maybe this is solved in the `master` branch with the DisplayServer refactor? I don't know. You could try installing the [Vulkan SDK](https://www.lunarg.com/vulkan-sdk/) then downloading a [nightly build](https://hugo.pro/projects/godot-builds/).

**Comment by runapp** [comment]
Yes the issue is gone with the latest nightly build. I've thought about testing on master but did failed to build myself, neither did I find the nightly binaries.
Thank you sir.
