### ISSUE TITLE
[SECURITY] CWE-330/CWE-676 - rand() used for cryptographic purpose

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#4022]
Godot uses `rand()` in `crypthead` function in [/core/io/crypt.h](https://github.com/godotengine/godot/blob/master/core/io/crypt.h) for encryption which is **unsecure**. We should at least use `/dev/random` on POSIX-like systems ( x11/os x/android?/ios? ) and [CryptGenRandom](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379942%28v=vs.85%29.aspx) function on Windows for crypto.

Btw. we also have some version of openssl ( is it the secure one, after heartbleeds etc. ? ) - maybe we can use randoms from it.

**Comment by Marqin** [comment]
On Android we don't have access to `/dev/random`, but we have [SecureRandom](http://developer.android.com/reference/java/security/SecureRandom.html) function and on

**Comment by Marqin** [comment]
On `iOS` we also not have access to `/dev/random`, but we can use those functions - https://developer.apple.com/library/prerelease/ios/documentation/Security/Reference/RandomizationReference/index.html

**Comment by Marqin** [comment]
I'm working on some patch for this.

**Comment by Marqin** [comment]
Could you review this idea - https://gist.github.com/Marqin/3d9452d8da0a1e3f5e9c ?

**Comment by Marqin** [comment]
I changed it to be inside 0-MAX_RAND range.

**Comment by akien-mga** [comment]
Note: The `crypt.h` file referred to was from minizip, it's now in `thirdparty/minizip/crypt.h`. We don't modify thirdparty code unless we have a strong reason to, and we also don't use this code at all (it's used to decrypt zip files using a given password, which is not a feature exposed by Godot), so nothing to do here.
