### ISSUE TITLE
Tween loses precision if interpolating between big numbers

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#40237]
**Godot version:**

Godot 3.2.2-Stable

**OS/device including version:**

Doesn't matter

**Issue description:**

Using the Tween node to interpolate between big numbers results in the final value being wrong.
I guess this is because Tween uses float and therefore losing precision over time. Guessing here, I haven't checked.

The core issue is that I get a wrong result when the tween is done, I don't get the actual final value.

**Steps to reproduce:**
Start the project I included.
It will interpolate from 100202000 to 100202100 over one second and print each value that the tween creates in-between.
Note that the final value printed is expected to be 100202100 but is 100202096 (in my case, I don't know if this can vary).

**Minimal reproduction project:**

[FloatTest.tar.gz](https://github.com/godotengine/godot/files/4897223/FloatTest.tar.gz)

**Comment by Keetz** [comment]
Checked. The value interpolating is converted to real_t
https://github.com/godotengine/godot/blob/master/scene/animation/tween.cpp#L1385

**Comment by KoBeWi** [comment]
Looks related to #33813

**Comment by Keetz** [comment]
@KoBeWi indeed it does. Missed that when checking for issues.
