### ISSUE TITLE
Texture drop type dialog is too thin (expands on long titles with some translations)

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40248]
**Godot version:**

3.2.2

**Issue description:**

![7ckD15kLsB](https://user-images.githubusercontent.com/2223172/87098074-cd889100-c246-11ea-9566-356814cd032e.gif)
It should be probably made bigger, so it doesn't expand awkwardly when title is too long.

EDIT:
In case someone doesn't know, the dialog appears when you drag and drop a texture into 2D view, while holding Alt.

**Comment by Insiyaa** [comment]
Hello, I am interested in working on this issue. I read through the setup for Godot engine, are there any more places I can look to for getting started? Any pointers from you would be helpful! Thank you.

**Comment by zaevi** [comment]
@Insiyaa You can give it a fixed width in constructor of CanvasItemEditorViewport.
https://github.com/godotengine/godot/blob/a474926aca8a5da810f8cf546902c6da7286b254/editor/plugins/canvas_item_editor_plugin.cpp#L6368
For contributing, [read this](https://docs.godotengine.org/en/latest/community/contributing/index.html) :)

**Comment by jiteshvm** [comment]
Hello,
I also started working on this issue yesterday and I am interested in contributing more to the project.
I have submitted my first PR and as I am new to this process, any feedback will be helpful.
@Insiyaa Sorry I didn't see that you were interested in this issue too. Not sure how to avoid this.
Is there a way to see who's currently working on an issue?
For compiling the engine, you can use this link https://docs.godotengine.org/en/latest/development/compiling/index.html
