### ISSUE TITLE
extends on Subclass doesn't resolve relative Paths to GDScript

### ISSUE THREAD

**Issue by rdcklinux** [godotengine/godot#4026]
**Operating system or device:**
Ubuntu 14.04

**Issue description** (what happened, and what was expected):

extends "MyGDScript.gd" from gdscipt file works 

but:
```
class MySubClass extends "MyGDScript.gd":
    var myvar
```
Doesn't work

but
```
class MySubClass extends "res://absolute/path/MyGDScript.gd":
    var myvar
```
works

**Steps to reproduce:**

create two gdscript files in same folder

"script1.gd and script2.gd for example.

in script2.gd put this code
```
extends "script1.gd" # works

class SubClass extends  "script1.gd": #doesn't work
    var myvar
```

**Comment by vnen** [comment]
I'm able to reproduce this. Relative paths works on the main class but not on subclasses.
