### ISSUE TITLE
'Return'-Key on virtual keyboard sends no event (LineEdit, TextEdit)

### ISSUE THREAD

**Issue by TheDarkWeasel** [godotengine/godot#40262]
**Godot version:**
3.2.2.stable.mono

**OS/device including version:**
Pixel 3 with Android 11, Pixel 4 with Android 10, iOS 13 (two devices)

**Issue description:**
If you have a LineEdit or TextEdit in your scene and export it to Android or iOS, you will get keypresses in your "public override void _UnhandledInput(InputEvent @event)" as events. But there seems to be no event triggered when you press the "return"-Key at the bottom right of the keyboard. Neither on Android, nor on iOS.

Afaik this was working in Godot 3.2.1, but has stopped working in 3.2.2.

**Steps to reproduce:**
* Setup a scene with a LineEdit or TextEdit
* Attach script to the scene with:

<pre>
public override void _UnhandledInput(InputEvent @event)
{
    GD.Print(@event);
}
</pre>

* No event is logged when you press the "Return"-Key

**Comment by TheDarkWeasel** [comment]
Maybe this is no bug, but I could not find any documentation to get the "return"-key event on the virtual keyboard...

**Comment by akien-mga** [comment]
CC @pouleyKetchoupp
