### ISSUE TITLE
Editor window font size - change not discoverable (ctrl+ / ctrl-)

### ISSUE THREAD

**Issue by monk-e-boy** [godotengine/godot#40281]
**Godot version:**

3.2.2

**OS/device including version:**

Windows

**Issue description:**

Wanted to increase font size. Hard to figure out how to do it.

**Steps to reproduce:**
Try to increase font size. ctrl> and ctrl< don't work (powerpoint / word / ms office) ctrl+ works (like chrome)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
You mean in Script Editor?

**Comment by Calinou** [comment]
<kbd>Ctrl + Mouse wheel</kbd> should do the trick. It's likely the most intuitive way to do it as long s you have a scroll wheel.

**Comment by monk-e-boy** [comment]
I assumed that it was impossible to change the font size. A menu item or button should be added to allow the user to change font size. I bet there are other things I can do that are hidden because there is no GUI

**Comment by Calinou** [comment]
@monk-e-boy The script editor menus already have a lot of options:

![image](https://user-images.githubusercontent.com/180032/87435095-90782200-c5eb-11ea-8dfe-d26d0b773776.png)

We need to do some reorganization before we can add more options to it.

**Comment by KoBeWi** [comment]
> We need to do some reorganization before we can add more options to it.

Related: https://github.com/godotengine/godot/issues/30265

**Comment by Calinou** [comment]
<kbd>Ctrl + +/-</kbd> are supported in both 3.4 and `master`, closing.

There's an issue with how zoom behaves in `master`, but that's unrelated: https://github.com/godotengine/godot/issues/62410
