### ISSUE TITLE
Variant.Type enum is not properly linked in Editor docs (web version works fine)

### ISSUE THREAD

**Issue by zacryol** [godotengine/godot#40290]
**Godot version:** 3.2.2

**OS/device including version:** Solus Linux / Linux Mint 20

**Issue description:** when clicking link to Variant.Type enum (such as under GDScript typeof() function), you get taken to the Variant class page as opposed to the Variant.Type under GlobalScope

Initially found by vonflyhighace2#6347 on Discord.

**Steps to reproduce:** open *in-editor* docs to the GDScript page; navigate to typeof() function; click "Variant.Type"

**Minimal reproduction project:** N/A

**Comment by fengjiongmax** [comment]
I have the same issue in godot 3.2.3
The link in the docs is [here](https://github.com/godotengine/godot/blob/2d904127d685b25d6c5240e8792b21f392c05f34/modules/gdscript/doc_classes/%40GDScript.xml#L1225) and the link is `[enum Variant.Type]`.

I tried to change it to `[enum @GlobalScope.Variant.Type]` and compile the engine, the editor only guides me to top of the `@GlobalScope` ,but not where `Variant.Type` is (it's way down in `@GlobalScope`).

I guess the code handles links in documents is [here](https://github.com/godotengine/godot/blob/2d904127d685b25d6c5240e8792b21f392c05f34/editor/editor_help.cpp#L1601).

But I don't know how to debug the engine...
