### ISSUE TITLE
Array of buttons,focus on the wrong index

### ISSUE THREAD

**Issue by fengjiongmax** [godotengine/godot#40293]
**Godot version:**
3.2.2

**OS/device including version:**
Godot Engine v3.2.2.stable.official 
OpenGL ES 3.0 Renderer: GeForce GTX 1060 3GB/PCIe/SSE2

**Issue description:**
Having an array of buttons,and use up/down arrow keys to loop over them to grab focus.
but the focus function grab on the wrong one.
But if I print the button.text,it prints the correct one.

**Steps to reproduce:**
A scene set up like this:
![Screenshot from 2020-07-12 01-21-21](https://user-images.githubusercontent.com/5288733/87230000-46baec00-c3df-11ea-9793-3a2920f49a68.png)

and the script attached to Node2D:
```gdscript
extends Node2D

onready var button = [
	$VBoxContainer/Button,
	$VBoxContainer/Button2,
	$VBoxContainer/Button3
]

onready var focus_button_array = 0

func _ready():
	_focus_button()
	pass # Replace with function body.

func _input(event):
	if event.is_action_pressed("ui_up"):
		focus_button_array +=2
		_focus_button()
		pass
	if event.is_action_pressed("ui_down"):
		focus_button_array +=4
		_focus_button()
		pass
	pass

func _focus_button():
	focus_button_array = focus_button_array%3
	print_debug("array index :%s,button text %s" %[focus_button_array,button[focus_button_array].text])
#	print_debug(focus_button_array)
#	print_debug(button[focus_button_array].text)
	button[focus_button_array].grab_focus()
	pass


```
then press up/down arrow keys.

**Minimal reproduction project:**

[Godot_button_array.zip](https://github.com/godotengine/godot/files/4907324/Godot_button_array.zip)

**Comment by zaevi** [comment]
This event is handled again by engine, so focus go to next one.
Try to turn Buttons' `focus_mode` property from `All` to `Click`, or set the event as handled:
```GDScript
func _input(event):
	if event.is_action_pressed("ui_up"):
		focus_button_array +=2
		_focus_button()
		get_tree().set_input_as_handled()
		pass
	if event.is_action_pressed("ui_down"):
		focus_button_array +=4
		_focus_button()
		get_tree().set_input_as_handled()
		pass
	pass
```

**Comment by fengjiongmax** [comment]
Thank you.
