### ISSUE TITLE
"animation_finished" Missing From AnimatedSprite3D

### ISSUE THREAD

**Issue by Kayomn** [godotengine/godot#40301]
**Godot version:**
3.2.2

**OS/device including version:**
Manjaro Linux x86_64
Kernel 5.4.44-1-MANJARO

**Issue description:**
There is no `animation_finished` signal for `AnimatedSprite3D` unlike `AnimatedSprite`.

As the other signal, `frame_changed`, is present I assume this is either intentional or an accidental omission as they don't share any relevant common ancestor in their inheritance hierarchy.

**Steps to reproduce:**
1. Open the editor.
2. Create an `AnimatedSprite3D` node.
3. Select it and navigate to its signals tab.

**Minimal reproduction project:**
I do not think one is necessary doesn't require any project setup, however if requested I can provide one.

**Comment by jiteshvm** [comment]
I can take this if no one else has started yet

**Comment by seltee** [comment]
I met the same problem with this and also with frame_changed not fired. Please, merge the fix provided.
