### ISSUE TITLE
The button node doesn't change the scene

### ISSUE THREAD

**Issue by Theliamx** [godotengine/godot#40306]
I have a button similar to the play, all it does is send to another scene, but it doesn't work on my smartphone, the play button if it works but the other doesn't.
Everything works correctly in the Godot editor, it just happens to me on my smartphone.
The store button works as i put it to hide in ad, but it just doesn't send the scene, and i've set myself well and it's all right.
The button hide the banner, only not change scene.
That is in my smartphone.

**Comment by nathanfranke** [comment]
Please fill out the issue template, and make sure to include a minimal reproduction project. If you need help with your project, check one of our [community channels](https://godotengine.org/community).

**Comment by Theliamx** [comment]
> Please fill out the issue template, and make sure to include a minimal reproduction project. If you need help with your project, check one of our [community channels](https://godotengine.org/community).

I've noticed well, I've created everything in one scene, and I think it's a problem implementing the Admob plugin.
Where can i look at it?

**Comment by Calinou** [comment]
We don't support third-party ad modules on this repository. Please open an issue on the repository of the ad module you're using.
