### ISSUE TITLE
problem with path2d node

### ISSUE THREAD

**Issue by MasTho0128** [godotengine/godot#40304]
**Godot version:**
3.2 oficial stable

is a bug or glitch

**OS/device including version:**

**Issue description:**

the saved path from a scene (A) and when you want to implement it in a scene (B). When drawing a path in the scene (B) this path automatically appears in the saved scene (A) and if I drag from the file system again the same saved scene (A) it will leave with the path that was drawn and if it then draws more paths, you will see how this is added to the other scene (A) and the duplicate object.

**Steps to reproduce:**
1_create a scene (A) with a path2d
2_save this scene (A)
3_valla to a scene (B)
4_set scene (A) and create a path
5_valla to the scene where the path (A) was saved
6_after creating a path you will see how the path I think appears in the scene (A)
7_ if you duplicate the scene (A) it will exit with the created path
8_if you add an extension to the created path you will see how the second object appears the same as it added.
![svero bug](https://user-images.githubusercontent.com/64819256/87236098-3b010280-c3aa-11ea-96f9-586589f3f081.png)
![svero bug](https://user-images.githubusercontent.com/64819256/87236112-68e64700-c3aa-11ea-91b5-7b354e2adace.png)

**Minimal reproduction project:**

**Comment by arrowinaknee** [comment]
The `Path2D` node uses a resource to store the path, so when you duplicate the scene both curves have the same resource attached and thus any change in the resource will affect both nodes. This behavior may seem to be a bit counter-intuitive but I don't think it is unintended. If you want a node to use a unique resource you can right-click the resource in the inspector and select `make unique` if i remember the action name correctly

**Comment by MasTho0128** [comment]
> El `Path2D`nodo utiliza un recurso para almacenar la ruta, por lo que cuando duplica la escena, ambas curvas tienen el mismo recurso adjunto y, por lo tanto, cualquier cambio en el recurso afectará a ambos nodos. Este comportamiento puede parecer un poco contra-intuitivo, pero no creo que sea involuntario. Si desea que un nodo use un recurso único, puede hacer clic con el botón derecho en el recurso en el inspector y seleccionar `make unique`si recuerdo el nombre de la acción correctamente

Thanks,  it worked for me
