### ISSUE TITLE
Logs are polluting $HOME directory

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#40305]
**Godot version:**
3.2 branch - commit c2a4ce9380736b65c27fb204c307bdd4d84b43b6

**OS/device including version:**
Arch Linux

**Issue description:**
Logs are being written to `$HOME` directory when Project Manager appears.

**Steps to reproduce:**
Simply run `godot` without opening any project in particular.

**Comment by nathanfranke** [comment]
I think this is a regression from https://github.com/godotengine/godot/pull/40121

**Comment by clayjohn** [comment]
CC @Calinou

**Comment by nathanfranke** [comment]
I checked it a bit. `user://` seems to return `$HOME` if no project is open. We should set aside a different directory like `~/.local/share/godot/`.

**Comment by Calinou** [comment]
@nathanfranke I think file logging should always be disabled in the project manager, actually.
