### ISSUE TITLE
Shadow distortion on Android

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#4031]
**Operating system or device:**
Android 5.0.2/6.0

**Issue description** (what happened, and what was expected):
Shadows get distorted on Android. (See example project)

**Steps to reproduce:**
Add a lamp, sprite and LightOccluder2D like in the example project.
![image](https://cloud.githubusercontent.com/assets/8849554/13728799/b040d8d8-e923-11e5-8416-12016b998847.png)

Desktop:
![image](https://cloud.githubusercontent.com/assets/8849554/13728800/beda65bc-e923-11e5-89a7-439ee4b95fdc.png)
Android:
![image](https://cloud.githubusercontent.com/assets/8849554/13728801/cf22027c-e923-11e5-897a-256e7805800d.png)

**Link to minimal example project** (optional but very welcome):
[occluder-android-issue.tar.gz](https://github.com/godotengine/godot/files/170971/occluder-android-issue.tar.gz)

Thanks!

**Comment by reduz** [comment]
it seems on Android, shadows are 16 bits, this needs to be fixed by always using rgba textures to encode a linear depth, but as this code will most likely changed in 3.0, will just tag for that release

**Comment by reduz** [comment]
this will be rewritten from scratch for 3.1, so closing for now. for 2.x it's too difficult to fix due to floating point precision
