### ISSUE TITLE
Godot doesn't free file lock when loading .po fails

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40324]
**Godot version:**

3cbf4971b

**Steps to reproduce:**
1. Open a project with a .po translation file
2. Edit the file while the project is opened and make some error (e.g. remove single quotation mark)
3. Run the game and close
4. Try to change the file and save
5. You can't, because the file is locked

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4909395/ReproductionProject.zip)

**Comment by akien-mga** [comment]
Are you sure it's a regression? I didn't check on Windows but on Linux, `lsof pl.po` reports the file as open by Godot 3.2.2 too after editing it with an error.

**Comment by KoBeWi** [comment]
Weird, it didn't happen in 3.2.2 when I initially tested.
