### ISSUE TITLE
Imported model is missing faces

### ISSUE THREAD

**Issue by Shulito** [godotengine/godot#40329]
**Godot version:**
3.2.2.stable

**OS/device including version:**
nvidia 1080 ti; driver version 451.48; GLES3
windows 10.0.19041.329

**Issue description:**
I created a model in Blender and I tried importing it into Godot and there are some faces missing. I tried importing it as an fbx, gltf and glb and the same faces are missing in the three imports. To test if there was a problem with the model I imported the same files into UE4 and they are displayed correctly.

Screenshot of the problem:
https://drive.google.com/file/d/11X-jmI37c_OsFnA7HF9-K0NtitRjSk7g/view?usp=sharing
![bird](https://user-images.githubusercontent.com/8281454/87262032-72c79180-c4f3-11ea-8265-4022457170e8.png)

Also, the bounding box of the imported fbx seems to be twice as big as the other two, but I don't know if this problem is related.

**Steps to reproduce:**
1. Create a GLES3 project.
2. Import de meshes.

**Minimal reproduction project:**
Godot project:
[Birb.zip](https://github.com/godotengine/godot/files/4910106/Birb.zip) ([download from google drive](https://drive.google.com/file/d/11Qu95BoXaw5vOfBXZSEEVAWgoGdi9TD9/view?usp=sharing))

Blender file:
[bird2.zip](https://github.com/godotengine/godot/files/4910107/bird2.zip) ([download from google drive](https://drive.google.com/file/d/11SRdWEWKAwa2xAiL1FeZdq7WPqDPRAaG/view?usp=sharing))

P.S.: I'm having some problems with my ISP so I had to upload the files to my drive.

**Comment by volzhs** [comment]
I edited OP to attach an image and other files.

**Comment by fire** [comment]
Here's what it looks export to gltf2 in the microsoft viewer.

![image](https://user-images.githubusercontent.com/32321/87344662-ad392a80-c503-11ea-8dbf-a3e4f8fbe589.png)

**Comment by fire** [comment]
This is different from blender.

![image](https://user-images.githubusercontent.com/32321/87344854-fee1b500-c503-11ea-88e5-123a63423d8c.png)

Perhaps something is strange with the model?

**Comment by Shulito** [comment]
In Unity an Unreal it shows fine:

![unity](https://user-images.githubusercontent.com/2199770/87556820-7f7fed00-c68d-11ea-83c0-3c581868fc01.png)

![ue4](https://user-images.githubusercontent.com/2199770/87556836-84dd3780-c68d-11ea-9034-529a36879c5f.png)

I have no idea how Godot works internally, but maybe Godot and Microsoft Viewer use the same framework to load the meshes (something like assimp) and it has a bug (?).

**Comment by fire** [comment]
I checked in https://gltf-viewer.donmccurdy.com/ and it seems to load fine, so at least it's working in other gltf2 viewers.

**Comment by nonunknown** [comment]
@fire I've found a solution for importing 3d pipeline Blender->Godot

by reading[ this reddit](https://www.reddit.com/r/godot/comments/hpzeil/how_do_i_import_a_rigged_model_from_blender/) A guys says:

`I found a solution. If I make a new bone and ensure that all vertices have non zero weight to at least one bone it imports as expected and works just fine.`

This means that if the **Master** bone is assigned to all vertices, no problem occurs in godot. here's my case:

Before:
![Screenshot from 2020-07-17 08-03-11](https://user-images.githubusercontent.com/58845030/87779913-fe973180-c803-11ea-92ec-430494b70d2a.png)


After:

![Screenshot from 2020-07-17 08-03-40](https://user-images.githubusercontent.com/58845030/87779942-0bb42080-c804-11ea-8d0a-234d6c3c396a.png)

**Comment by Shulito** [comment]
So every vertex has to have a weight assigned. Is this an issue or is that the way its supposed to be??

**Comment by fire** [comment]
I mean alternatively we can pick a random bone and set its weight to zero.. but that seems wrong? Or fail the entire import.

**Comment by scurest** [comment]
This is a bug in Blender. It is tracked by https://github.com/KhronosGroup/glTF-Blender-IO/issues/1151.

**Comment by Calinou** [comment]
Closing per @scurest's comment.
