### ISSUE TITLE
Exposed int script variables have a maximum limit of 65535

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#4032]
If you export an int variable from script like this:
export(int) var my_var

it can only be set to a maximum of 65,535 via the editor as the editor clamps it to that, despite it being able to hold a much larger number.

**Comment by neikeq** [comment]
Have you tried using the min and max parameters?

`export (int, -262140, 262140) var my_var`

**Comment by sketchyfun** [comment]
Ahh, I missed that! Good to know, but I wonder if this could still be considered a usability issue?

**Comment by neikeq** [comment]
Well, including the min and the max value of an int would be too verbose. But is it common to edit such big numbers in the inspector?

**Comment by akien-mga** [comment]
@ all devs: What do you think about this? Should we change the default max value, or is 65535 good enough?

**Comment by neikeq** [comment]
What about an INT_MAX constant?

**Comment by punto-** [comment]
It'd be funnier if it was 655360

**Comment by akien-mga** [comment]
I believe this was fixed by #5900.
