### ISSUE TITLE
Signal can only be connected to a node with an attached script

### ISSUE THREAD

**Issue by bmolyneaux** [godotengine/godot#40328]
**Godot version:**
3.2.2

**Issue description:**
Connecting a signal through the UI can only be done if the node has a script attached. This means that even if you want to connect a signal to a built-in function, you have to:

1. Attach a dummy script to the node
2. Connect the signal
3. Delete the dummy script

For example, it's useful to remove a node after a set period of time by connecting a timeout() signal of a Timer to queue_free(). There shouldn't be a requirement for a script to be attached to do this.

**Steps to reproduce:**

1. Add a Timer to a new scene
2. Select the Node / Signals tab of the Timer
3. Double-click the timeout() signal to connect it to a method

The dialog will show a message in red text "Scene does not contain any script." You will not be allowed to proceed in connecting the signal.

With the above workaround, you will be able to type the method name into the dialog and double-click the node to make the connection. That makes it clear that this is just a limitation of the UI design.

**Comment by Perfluoroalkyl** [comment]
You don't need to use a dummy script. When the "Connect a Signal to a Method" dialogue box opens up, you can simply press the "Advanced" option next to the Receiver Method input box to allow connection to a scriptless Node (along with giving you the ability to add extra call arguments, set the signal to one-shot mode, and set the signal to deferred mode). You will see that the words "Connect to Script" will change into "Connect to Node", and the warning will disappear, confirming the presence of this functionality. For example, you can type `queue_free` into the Receiver Method box, turn "Advanced" on, connect a Button's "pressed" signal to a scriptless ColorRect, and be able to free that ColorRect by pressing the button at runtime.

**Comment by bmolyneaux** [comment]
That's perfect. Thank you for the guidance.
