### ISSUE TITLE
Black screen bug on windows 10 (v3.2)

### ISSUE THREAD

**Issue by Bimi124** [godotengine/godot#40337]
# Godot version:
3.2

# OS/device including version:
Windown 10 (64 Bits)

# Graphics:
Intel(R) HD Graphics 4000

# Issue description:
I've just tried to test a games start screen using the start button.
The screen got black, my mouse pounter disappeared and I wasn't able to hit keys like `Ctrl + Tab`, `Windows-Logo + D` etc. but the power lamp was on.
I've colosed my laptop to turn the operating system into the sleeping mode but as I woke it up the Screen was still black.
I ned to hold the start button to power the laptop down and after I had rebooted it everything went right...

UPDATE:
I used the Full screen mode

# No idea how to reporducre it
If anyone here knows it, please write a comment.

**Comment by Calinou** [comment]
> No idea how to reporducre it

Please report bugs only if you know a definite way to reproduce them. Otherwise, it's not very useful as nobody will be able to help.

**Comment by Bimi124** [comment]
Hello, Calinou!
# I know:
 - That I don't know very much
 - My graphics card model is Intel(R) HD Graphics 4000 (I've updated the issue too)
 - I have already written it - and that's wat Godot writes too: `Godot Engine v3.2.stable.official - https://godotengine.org`
 - I was using full screen mode (I've added this as well)

# Why I'm writing this
 - If **anyone else** has the problem too he can write it here too and we know more (and then, **my report** becomes very useful because we konw this is not a problem of my hardware
 - Maybe someone gets an idea what had been happend if I report this (I think it was worth a try)
---
And: Why in the world are you closing this? Its not fixed I think.

**Comment by Calinou** [comment]
> And: Why in the world are you closing this? Its not fixed I think.

This issue is still open. I didn't close it.

**Comment by Bimi124** [comment]
Okay. Let's see if the bug appears again.
p.S: A automatic update function would be nice:wink:

**Comment by Calinou** [comment]
> p.S: A automatic update function would be nicewink

There are no plans to add automatic updates, as Godot updates can break compatibility. You don't want the engine to update itself while you're working on releasing a project.

**Comment by Bimi124** [comment]
The bug is still in the current version but now I know more.
I've made a mistake ina piece of code ang Godot found it. The function with the mistake was called in `_ready()`.
Godot found that bug butthis time, the problem stopped the program before it was hiding my mouse pointer. This time I was able to log out (but not do actions with my keyboard) and log in again. I saw that the debug window was still running and Godot displayed the problem. I had saved dictonarys in an arry and called them wrong. This was a new piece of code so I hadn't written it as I was opening this Issue but the problem with the black screen seems to go together with this.

**Comment by Zireael07** [comment]
If an error is found in the user code, the editor window should pop up (or the game will crash silently if the editor is not open).
Are you saying the editor window did not pop up for you?

**Comment by Bimi124** [comment]
Yes, no window did pop up. The Editor marked a line and wrote the error below it.

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment if you can still reproduce this issue.
