### ISSUE TITLE
Godot shader parser does not check mat4=mat4*vec4 incompatible types

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#40344]
**Godot version:**
Godot 3.2.2 stable

**OS/device including version:**
Linux

**Issue description:**
write in Godot shader:

```
mat4 matx=mat4(0.);
matx*=vec4(1, 1, 1, 0);
```

no error by Godot, but shader can not be compiled

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by Chaosus** [comment]
This issue is fixed in master branch - but not in 3.2.

**Comment by Chaosus** [comment]
Or not.. sorry Im bit confused
