### ISSUE TITLE
TreeItem needs some more internal left-padding

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4034]
All TreeItem elements using the default editor theme are badly centred and the actual contents (icon or string) tend to touch or go over the left side of the StyleBox:

![spectacle j11129](https://cloud.githubusercontent.com/assets/4701338/13729125/d7f72ac6-e92d-11e5-8a76-55eba4706acc.png)

![spectacle j11319](https://cloud.githubusercontent.com/assets/4701338/13729136/3d75475c-e92e-11e5-838c-84a095305e57.png)

![spectacle j11342](https://cloud.githubusercontent.com/assets/4701338/13729137/481277ca-e92e-11e5-84b4-0806d9c2c30f.png)

**Comment by bojidar-bg** [comment]
The main problem with this issue is that the selected stylebox is never included in the size calculations...

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone (/me sad).

**Comment by volzhs** [comment]
it's slightly different after ff22db3b21d2f6c93cdb1e972b2da217573f1ddc

![image](https://cloud.githubusercontent.com/assets/8281454/18079129/0f4511ba-6eca-11e6-90af-0547e024036d.png)

**Comment by akien-mga** [comment]
I guess we can consider the issue solved then :)
If there's a wish to put the icon back into the stylebox, it can be discussed in a new issue (but I like the new format personally, it looks clean enough).
