### ISSUE TITLE
Editing a label grows text box but does not shrink it. 

### ISSUE THREAD

**Issue by kojow7** [godotengine/godot#40357]
**Godot version:**
3.2.2

**OS/device including version:**
MacOS

**Issue description:**
Typing text beyond the size of a predefined label size will grow the text box but will not shrink it. This results in text being displayed incorrectly in editor. If you click to a different scene and back again (or save/close/re-open Godot) then the text box is restored to its correct size.

**Steps to reproduce:**

1. Create an object (such as StaticBody2D)
2. Create a label of a predefined size (with same width as object in step 1)
3. Set alignment to "Center"
4. Type text. Text will be centered in object from step 1.
5. Type lots of text to expand predefined text boundary.
6. Delete new text from step 5.
7. Label boundary does not return to predefined size. Therefore the text is no longer centered in the object from step 1.
8. Click the tab of a different scene.
9. Return to previous scene. Label boundary has now been restored to its proper size.

**Comment by Zireael07** [comment]
Can confirm.

**Comment by KoBeWi** [comment]
Fixed by #46702
