### ISSUE TITLE
Game freeze when ParallaxLayer.mirroring is negative

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4036]
Windows 7 64 bits, Godot 2.0.1

I created a ParallaxLayer under a ParallaxBackground and set mirroring.y to a negative value.
Then I start the game, and it freezes at the loading screen. It doesn't when I set a positive value, or disable camera.current.

Test project: http://zylannprods.fr/dl/godot/ParallaxFreeze.zip

What I initially tried to achieve is to have the background follow the player vertically, for a shoot-em-up game, hence the negative mirroring (I made a post on QA for this: http://www.godotengine.org/qa/1191/negative-parallaxlayer-mirroring-freezes-the-game)

**Comment by akien-mga** [comment]
I can confirm the bug on Mageia 6, Linux 64-bit in the current master branch.

**Comment by volzhs** [comment]
should it prevents to use negative value?

**Comment by akien-mga** [comment]
I don't have experience with ParallaxLayer so I'm not sure how mirroring should be used, but judging by the code it does look like using negative values will trigger infinite loops: https://github.com/godotengine/godot/blob/master/scene/2d/parallax_layer.cpp#L94-L112

**Comment by Zylann** [comment]
Initially, I used a negative value to mirror in the opposite direction. But if it's not possible by design, the editor should clamp the value to authorized bounds.
