### ISSUE TITLE
Externally Created .cs File Doesn't Quickly Update The .csproj File

### ISSUE THREAD

**Issue by richard14110** [godotengine/godot#40360]
**Godot version:**
v3.2.2.stable.mono.official

**OS/device including version:**
Windows 10 Pro x64 Version 1903 Build 18362.900

Device:
EliteDesk 705 G2 Mini

CPU:
A8-8600B

Integrated GPU:
R6 (Carrizo)

**Issue description:**
The .csproj file is not instantly updated after the .cs file is added to the project folder (by using anything outside of Godot to make the .cs file). I wish that the .csproj file would automatically be updated by Godot no matter what creates the .cs file. So far, I only tested the issue on Windows 10 and perhaps someone else may try the steps below with a different operating system. 

**Steps to reproduce:**
1. Get the Mono version of Godot 3.2.2 if you don't have it.
2. Download the Test.zip minimal reproduction project and extract the .zip file.
3. Open the Mono version of Godot.
4. Scan the Test folder and load the project.
5. Use another software or your operating system to create a .cs file within the Test folder.
6. Open the Test.csproj file with a text editor and read it.
The .csproj file did not seem to change in my case.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/4915708/Test.zip)

**Comment by akien-mga** [comment]
That's by design, the filesystem is rescanned each time you focus the Godot editor, but not continuously when it's not focused. Windows file access would make that impossible even if we wanted to (reading a file on Windows means locking it, so if Godot tried to read files e.g. every 50 ms, you'd have a hard time getting it written from an external editor).

CC @neikeq

**Comment by richard14110** [comment]
A workaround may be better than no solution. Can Godot at least write to the .csproj file when it gets focused again? I wonder if the following would work (only if the file is externally created):
 
1. The user gives the engine the focus after a .cs file is made outside of the engine and inside of the project folder.
2. Godot duplicates the file which generates a backup file.
3. Whenever the original file changes, the backup is updated.
4. The original file gets deleted.
5. Within the engine, a new file is created to replace the original and it has the data of the backup.
6. Godot updates the .csproj file unless if the entry is already in the file.

If the person doesn't prefer the process above, there may be an option that disables it or by default it is not enabled and optional. If the steps don't solve the problem, does anyone else have a better method?

**Comment by richard14110** [comment]
I wonder if the following would work (which only triggers if the file is externally created):
 
1. A user gives the engine the focus after a .cs file is made outside of the engine and inside of the project folder.
2. The editor gets the path and name of the .cs file and remembers those.
3. The engine reads the .csproj file and knows what to write to the project file.
4. Godot determines if the .csproj file should be updated. If that is the case, the .csproj file is no longer scanned. Else, skip to step 6.
5. The engine writes the updated .csproj file.
6. The editor can scan the .csproj file again.

If the steps above don't solve the problem, I hope for a better method in the future.

**Comment by richard14110** [comment]
Before, I meant that I want Godot to update the .csproj file instead of another program.

**Comment by richard14110** [comment]
Before, I wanted Godot to update the .csproj file instead of another program.

**Comment by richard14110** [comment]
Before, I wanted to update the .csproj file with Godot instead of another program.

**Comment by richard14110** [comment]
Before, I wanted Godot to update the .csproj file (instead of another program) after a .cs file is created outside of the engine and inside of the project folder and after the editor gets the focus.

**Comment by neikeq** [comment]
I won't make Godot check the filesystem to add files created externally. It's the same with IDEs, they only add the file if you create it from the IDE.
With 4.0 we are switching to project Sdk that includes all `.cs` in the dir and sub-dirs by default, so this will no longer be a problem.
You can get a similar effect right now with latest stable by adding `<Compile Include="**\*.cs" />` to your csproj.

**Comment by richard14110** [comment]
I already knew about that line but I hope that the user doesn't have to manually edit the .csproj file. Is there any chance that a newer Godot version 3.x.x switches to the better project SDK? Certain computers cannot use Vulkan but support OpenGL 3.3.
