### ISSUE TITLE
Non-descriptive backtrace

### ISSUE THREAD

**Issue by M4RCU5G1850N** [godotengine/godot#40378]
**Godot version:**
v3.1

**OS/device including version:**
Windows 10, GTX 1080ti

**Issue description:**
System crash logged a non-descriptive backtrace containing repeated "<couldn't map PC to FN name>"

![image](https://user-images.githubusercontent.com/60413459/87431049-69d8dc00-c629-11ea-8332-72d6d030664a.png)

**Steps to reproduce:**
1) Run 'RPG in a Box'
2) Animate multiple large assets and run multiple scripts simultaneously

**Minimal reproduction project:**
'RPG in a Box' (http://www.rpginabox.com/) source project not mine.

**Comment by M4RCU5G1850N** [comment]
Any clues on what might cause a backtrace like this?

**Comment by Zireael07** [comment]
Since it's a (presumably) release build, it lacks debug info. You won't be able to get a better backtrace. Also this is probably better reported to RPG in a Box itself.

**Comment by M4RCU5G1850N** [comment]
Thanks @Zireael07<mailto:notifications@github.com> I have reported it to Justin as well but I hoped the null backtrace was abnormal and could help him narrow down the cause. I'll close the item.

________________________________
