### ISSUE TITLE
convert user input time (Dictionary) to Unix time stamp

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#4038]
Basically I need this for a todo app - in order to track days remaining  till a future goal date.

1.To do that the user inputs time, which gets converted to a standard dictionary variable.
2. (missing) That time is then converted to unix timestamp
3. We get current time's unix timestamp and we substract the timestamp from step 2
4. (was recently implemented)The resulting timestamp is then converted back to a human readable time (get_time_from_unix_time())

**Comment by blurymind** [comment]
Another thing that is missing in godot is a function that returns seconds since 1970, jan1,00:00:00.
That would help to at least figure it out.

Most programming languages have these as a built in function, but not godot. So it is hard to figure out to do in gdscript

**Comment by akien-mga** [comment]
> Another thing that is missing in godot is a function that returns seconds since 1970, jan1,00:00:00.

Isn't that exactly what ``OS.get_unix_time()`` does?

**Comment by blurymind** [comment]
Ah yes, you are right. But how do we do the math to get unix time stamp of a custom date? I cant figure out the math

**Comment by Razzlegames** [comment]
For item **2)**. From the Facebook discussion on keeping this portable:

I could probably populate a std::tm and use std::mktime(std::tm), which returns time_t (not guaranteed to be an unsigned int), then just use std::chrono::seconds(time_t), which is guaranteed to return a portable signed integer of at least 35 bits (int64_t is fine).

http://en.cppreference.com/w/cpp/chrono/duration

That seems portable

**Comment by est31** [comment]
Not gonna work, godot doesn't use stuff from `std`, as consoles have very very bad support for it.

**Comment by akien-mga** [comment]
It shouldn't be too hard to implement that ourselves no? Apart from taking into account the leap years (modulo 4, apart from module 200) the conversion should be relatively straightforward.

**Comment by vnen** [comment]
> (modulo 4, apart from modulo 200) 

Would be "apart from modulo 400" actually. And we also have to consider leap seconds (there are 26 of those). And we are assuming this is UTC, so no way to deal with all timezones (which is something to consider if you're dealing with user input).

**Comment by est31** [comment]
Note that unix time does not skew by leap seconds. On the occasion of a leap second, the UTC timer ticks by two seconds, but the unix timer ticks one second twice -- one unix time value can mean two different UTC seconds. The unix time counter is guaranteed to be raised by 24 * 60 * 60 each and every day -- even if that day has a leap second.

**Comment by Razzlegames** [comment]
Close. Actually it's if the year is mod 4 and mod 400 AND not mod 100.

```
#define LEAPYEAR(year)  (!((year) % 4) && (((year) % 100) || !((year) % 400)))
```

@est31 
If what you're saying is true, then it's even easier than I thought.  I'll look for a reference to port similar to what I did with gmtime.

**Comment by est31** [comment]
My source is https://en.wikipedia.org/wiki/Unix_time#Leap_seconds perhaps its wrong, i haven't looked at the official posix spec if something like that exists.

**Comment by Razzlegames** [comment]
Looks to be the case.  Pull request made.  Feel free to check it out and review.

**Comment by blurymind** [comment]
Thanks to all of these awesome patches, I was able to make a little todo list with deadline time tracking :D 
@Razzlegames  thank you for these wonderful contributions to godot. They are certainly going to be handy for many other things!

**Comment by vnen** [comment]
#4071 was merged, so this issue can be closed.
