### ISSUE TITLE
Bones don't return to animation pose when SkeletonIK is stopped

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot#40384]
**Godot version:**
 `v3.2.2.stable.flathub`

**OS/device including version:**
Arch Linux

**Issue description:**
When calling `stop()` on a SkeletonIK, the bones it affected don't return to their animation pose, but just sit at the last pose set by SkeletonIK instead.

This only happens in-game; toggling "Play IK" in the editor works fine and the bones return to being animated after toggling it off.

**Steps to reproduce:**

- Call `start()` on a SkeletonIK that affects animated bones.
- Now those bones will follow the target of SkeletonIK.
- Call `stop()` on the SkeletonIK.
- Bones no more affected by the animation, and just sit at the last pose.

[**Reproduction project**](https://github.com/godotengine/godot/files/4930355/skeletonik-bug.zip)
Space to `start()` SkeletonIK
Escape to `stop()` SkeletonIK
Mouse up and down to move the target.
You might also want to try changing the played animation to `"land"`, and set it to loop in the animation editor. The animation is played in `_ready()` of the AnimationPlayer.

**Comment by Tooniis** [comment]
I added a reproduction project if that would help

**Comment by arnerak** [comment]
You can reset them with [clear_bones_global_pose_override ](https://docs.godotengine.org/de/stable/classes/class_skeleton.html#class-skeleton-method-clear-bones-global-pose-override)

**Comment by Tooniis** [comment]
> You can reset them with [clear_bones_global_pose_override ](https://docs.godotengine.org/de/stable/classes/class_skeleton.html#class-skeleton-method-clear-bones-global-pose-override)

That works. Shouldn't `stop()` include it though?

**Comment by smix8** [comment]
@Tooniis
@Calinou
This issue is fixed by #47933 and #47923

**Comment by akien-mga** [comment]
Thanks, closing.
