### ISSUE TITLE
nodes added as children in tool scripts are not visible in the editor

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#40385]
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10 Pro Education Nvidia geforce gtx 650 gles2

**Issue description:**
I have this script..
```
extends Control
tool



onready var _icon     = $Ship/Icon
onready var _def_bars = $Ship/DefBars
onready var _spd_bars = $Ship/SpdBars
onready var _pwr_bars = $Ship/PwrBars

export(Resource) var ship_resource setget _set_ship, _get_ship
export(Color   ) var def_color = Color(0x73eff7ff)
export(Color   ) var spd_color = Color(0xa7f070ff)
export(Color   ) var pwr_color = Color(0xef7d57ff)

func _set_ship(value):
	ship_resource = value
	update_controls(value)
	
func _get_ship():
	return ship_resource; 
	
func update_controls(value):
	#print("test")
	
	#del stuff
	_icon.texture = null	
	for i in _def_bars.get_children():	
		i.queue_free();
		
	for i in _spd_bars.get_children():
		i.queue_free();
		
	for i in _pwr_bars.get_children():
		i.queue_free();
		
	# add stuff
	if (value==null) || !(value is Ship): return
	
	_icon.texture=value.icon
	for i in range(value.def):
		var c = ColorRect.new()
		c.color = def_color
		c.rect_min_size.x = 2
		_def_bars.add_child(c)
		c.set_owner(_def_bars)
		print(_def_bars.get_child_count())
		
	for i in range(value.spd):
		var c = ColorRect.new()
		c.color = spd_color
		_spd_bars.add_child(c);
		c.set_owner(_spd_bars)
		
	for i in range(value.pwr):
		var c = ColorRect.new()
		c.color = pwr_color
		_pwr_bars.add_child(c);
		c.set_owner(_pwr_bars)
```

attached to this object..
![image](https://user-images.githubusercontent.com/2453707/87450041-da90e180-c5b2-11ea-8053-8f47972bca3f.png)

but as you can see the ColorRect are not appearing in the hboxcontainer even though they are there and the script is a tool script

**Steps to reproduce:**
- just add object to the scene tree in a tool script. they do not show up in the scene tree.

**Minimal reproduction project:**
*Not Needed*

**Comment by Zireael07** [comment]
That is normal. You haven't set the owner variable, so they do not show up in the scene tree.

You should try to set the scene root as owner, using set_owner() and get_tree().get_root().

**Comment by Shadowblitz16** [comment]
I have set the owner
`c.set_owner(_pwr_bars)`

**Comment by volzhs** [comment]
`owner` should be the currently open scene.

**Comment by Shadowblitz16** [comment]
@volzhs ok oh that resolves this issue.
thankyou

**Comment by AThousandShips** [comment]
You can't set owner *before* adding the node to the tree

**Comment by Radivarig** [comment]
I don't get it
```gdscript
	skeleton = Skeleton3D.new()
	add_child(skeleton)
	skeleton.owner = self
	# still not visible in the hierarchy
```
