### ISSUE TITLE
Validate_Json() and parse_json does not catch missing "}" and triggers a blank exception  

### ISSUE THREAD

**Issue by LarsGut** [godotengine/godot#40396]
**Godot version:** 3.2.2.stable.official

**OS/device including version:** windows 10, PC

**Issue description:**

while testing validate_Json() and parse_json() i noticed when i started to remove "}"  from end (not the last one) in the JSON sting it would not cast an exception with text like Expected '}' or ','  but rather a blank like 0:

**Steps to reproduce:**
Pre req:
https://www.json.org/example.html

1) remove last "}" 
2  expected:  Json_validate() cast an Expected error
3  actual:  pass

1) remove second to last "}" or third from last or even all 3 
2  expected:  Json_validate() cast an Expected error
3  actual:  blank exception:

**Minimal reproduction project:**

`onready var parseTest ={}
onready var jsonString = '{ "glossary": { "title": "example glossary", "GlossDiv": { "title": "S", "GlossList": { "GlossEntry": { "ID": "SGML", "SortAs": "SGML", "GlossTerm": "Standard Generalized Markup Language", "Acronym": "SGML", "Abbrev": "ISO 8879:1986", "GlossDef": { "para": "A meta-markup language, used to create markup languages such as DocBook.", "GlossSeeAlso": ["GML", "XML"] }, "GlossSee": "markup"  }}} }'
func _ready() -> void:
	
	var a = validate_json(jsonString)
	
	if not a:
		parseTest = parse_json(jsonString)
		print("---------------------")
		print(parseTest)
	else:
		print(a)`

**Comment by adam-bates** [comment]
The test formatted as code:

```
onready var parseTest ={}
onready var jsonString = '{ "glossary": { "title": "example glossary", "GlossDiv": { "title": "S", "GlossList": { "GlossEntry": { "ID": "SGML", "SortAs": "SGML", "GlossTerm": "Standard Generalized Markup Language", "Acronym": "SGML", "Abbrev": "ISO 8879:1986", "GlossDef": { "para": "A meta-markup language, used to create markup languages such as DocBook.", "GlossSeeAlso": ["GML", "XML"] }, "GlossSee": "markup" }}} }'
func _ready() -> void:

	var a = validate_json(jsonString)

	if not a:
		parseTest = parse_json(jsonString)
		print("---------------------")
		print(parseTest)
	else:
		print(a)
```

**Comment by adam-bates** [comment]
I've never contributed to Godot but I thought I'd give this a shot so I created the following PR which AFAIK should fix the issue: https://github.com/godotengine/godot/pull/40606
