### ISSUE TITLE
GDScript executing getter function without call when debugging

### ISSUE THREAD

**Issue by AMS21** [godotengine/godot#40390]
**Godot version:** v3.2.2.stable.official

**OS/device including version:** Winows 10 Home 2004

**Issue description:**

Before calling test function GDScript calls the `get_private_var` function although no call to it was present and the variable `_private_var` is never read from. Also the stack frames window will fill with an infinite number of calls to `get_private_var`
Actual call graph:
main.gd - _ready()
test.gd - get_private_var() (infinite times)
Expected call graph:
main.gd - _ready()
test.gd - function()

**Steps to reproduce:**
Open the provided project.
Place a break point in main.gd on line 4 (the first line of the _ready function).
Run the project.
Wait until the break point is hit
Click "step into".
You should see the bug happening.

Interestingly the bug does not happen when you click "step over" or "continue".

**Minimal reproduction project:**

[BugTest.zip](https://github.com/godotengine/godot/files/4920707/BugTest.zip)

**Comment by asheratnoveltyfactor** [comment]
I keep having this same bug in different areas of my code I'm trying to debug.  It will, at weird points where I'm calling a private method from within the script (wish I could be more specific at the moment, but I'm not sure if I can), decide it needs to call a getter function for a property with a setget (which has already been set) that isn't even referenced in the private method.  Then, the stack frames window will fill with an infinite number as the original poster reported.

I'm not sure if this is the right place to chime in "me too" or not, so I apologize in advance if it isn't, but I thought I'd note that others besides the original poster have come across this.

I'm using Godot 3.1 (to my knowledge)

**Comment by AMS21** [comment]
Just retested the bug with the latest versions:
Godot v3.5.1: Still bugged
Godot v4.0.1: Fixed

As I'm not planning on using Godot 3.x in the future, I'm going to close this as fixed.
