### ISSUE TITLE
Validate_Json() and parse_json does not catch trailing commas

### ISSUE THREAD

**Issue by LarsGut** [godotengine/godot#40394]
**Godot version:** 3.2.2.stable.official

**OS/device including version:** Windows 10 PC

**Issue description:**

Validate_Json() and parse_json does not catch trailing commas, the methods does not raise an error for maleformed JSON

while running test i noticed in the dictionary the spare commas are removed, although i would like to see that it triggers an exceptions like "expected key"  as in the other cases.

**Steps to reproduce:**
Example 1:
```
{
 "Test": [
{
"car": [
            "Dodge"
],
"operation": "ovner"
}, <-- should not be allowed
], <-- should not be allowed
}
```

Example 2:
```
{
"Test": [
{
"car": [
"Dodge"
],
"operation": "ovner"
}
]
, <-- should not be allowed
}
```

Example 3:
```
{
"Test": [
{
"car": [
"Dodge"
],
"operation": "ovner"
}
], <-- 2 adding here a coma, will trigger expected key
, <-- 1
}
```

**Minimal reproduction project:**

**Comment by Calinou** [comment]
I can confirm this on commit ecf432abc.

**Comment by filipworksdev** [comment]
Trailing commas in objects and arrays is something that should have been implemented from the start in JSON. The proposed extension JSON5 allows for trailing commas. I would prefer this was a warning only and not stop execution.

**Comment by Calinou** [comment]
> Trailing commas in objects and arrays is something that should have been implemented from the start in JSON. The proposed extension JSON5 allows for trailing commas. I would prefer this was a warning only and not stop execution.

JSON isn't designed to be convenient to write; it's designed to be a standard format for passing data around. If Godot doesn't make the same guarantees as other software/libraries when validating JSON, it can end up passing invalid JSON to other programs.

**Comment by filipworksdev** [comment]
I don't argue against any of the points you made. 

I am only saying I would prefer if the fix to not stop the execution of the program ie don't use ERR_V_COND or similar and display a warning instead similar to your comment "Warning: Your data contains trailing commans and your JSON may end up passing invalid data to other programs."

**Comment by Calinou** [comment]
> I and a lot of other people find trailing commas useful. JSON is not used just as an interchange format on the web or between applications but also to store data/settings locally as well.

For this purpose, use the ConfigFile class instead of JSON. It supports serializing any Godot datatype, allows trailing commas in arrays and dictionaries, and more.
