### ISSUE TITLE
Only partial support of standard C escape sequences?

### ISSUE THREAD

**Issue by runapp** [godotengine/godot#40402]
**Godot version:**
Godot Engine v4.0.dev.calinou.18c51d3f0
Godot Engine v3.2.2.stable.official

**Issue description:**
String contains any char among "\e\?\000\x00\U00000000" could not be parsed.
According to https://en.wikipedia.org/wiki/Escape_sequences_in_C , these all belong to standard C escape forms. Any other forms listed in wikipedia is supported by GDScript.

**Steps to reproduce:**
`var a="\e\?\0\000\x00\U00000000"`

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/38716.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/3797.
