### ISSUE TITLE
Not all unicode characters are able to be displayed even though they are in the font

### ISSUE THREAD

**Issue by kojow7** [godotengine/godot#40405]
**Godot version:**
3.2.2

**OS/device including version:**
MacOS

**Issue description:**
I am attempting to use unicode characters in my game. To do this I am using the GNU freefont-tff. It works when I use this font in the editor. However, it does not work when I use this font in gameplay. To use the font in gameplay I am using a Label, going to Custom Fonts and creating a "New DynamicFont". Everything seems to work well. However, in the game it shows up as a question mark in a diamond (indicating it cannot find the symbol). 

Why does Godot have issues with certain Unicode characters?

**Steps to reproduce:**

1. Create a Label
2. Use a Unicode font such as Gnu Free Font
3. Add a character in the 1400 range
4. The font shows up fine in the editor (when added as the editor font), but not in gameplay.

**Minimal reproduction project:**
Please see the following project which reads a JSON file and sets text of three labels. You will notice that the second label does not display correctly.

[KWGodot001-debug-unicode.zip](https://github.com/godotengine/godot/files/4923079/KWGodot001-debug-unicode.zip)

**Comment by bruvzg** [comment]
0x140B character is missing from the Bold variant of the font, you have selected.
Font viewer probably is substituting in with the one from Regular (which works fine in the Godot too).

<img width="853" alt="Screenshot 2020-07-15 at 08 53 36" src="https://user-images.githubusercontent.com/7645683/87508832-e5ae4500-c678-11ea-9792-313b0e66bb62.png">

**Comment by NathanLovato** [comment]
Addressed by #40405

**Comment by akien-mga** [comment]
> Addressed by #40405

Actually #40408 :)
