### ISSUE TITLE
Using call_deferred  on non-existing functions do not generate warnings/errors

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#40401]
**Godot version:**
3.2 branch commit 3de89f78e51eab7b2e3299098a34c9a9d0764005

**OS/device including version:**
Arch Linux

**Issue description:**
Using call_deferred  on non-existing functions do not generate warnings/errors.

No warnings are generated neither when deferring calls to functions but missing parameters to properly call those functions.

**Steps to reproduce:**
```gdscript
func _ready():
    call_deferred("non_existing_function")
    call_deferred("existing_function_but_missing_parameter")

func existing_function_but_missing_parameter(p_hello : String) -> void:
    print("Test: " + p_hello)
```

**Minimal reproduction project:**
[NoCallDeferredWarning.zip](https://github.com/godotengine/godot/files/4922293/NoCallDeferredWarning.zip)

**Comment by Calinou** [comment]
I can confirm this on 3.2.2. For the record, doing the same with `call()` will raise an error and pause the project execution (when running from the editor).

> `def _ready():`

Too much Python? :eyes:

**Comment by Rubonnek** [comment]
> Too much Python? smile

Yup, haha. Thanks for catching that.

**Comment by Rubonnek** [comment]
This issue is specific to 3.2.

I can't this reproduce this problem on the master branch.

**Comment by Xrayez** [comment]
Can reproduce in `3.1.1.stable`, and likely `3.0.6.stable`.

**Comment by Rubonnek** [comment]
This issue is also happening on the `master` branch and could be fixed by the same patch.
