### ISSUE TITLE
Undo Close Tab is unreliable

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40419]
**Godot version:**

3.2.2

**Issue description:**

Unfortunately I don't have exact reproduction steps, but sometimes when you close scene tab and use "Undo Close Tab" (in my case with shortcut), a different tab is opened. Previously I thought that the order might get messed up, but now I think that some scenes just don't get saved in scene history and trying to reopen them reopens a different tab. This seems to happen randomly and then can be reproduced multiple times on that scene, but eventually fixes itself.

**Steps to reproduce:**
1. Open a scene
2. Open another scene
3. Close both scenes
4. Reopen scene tab
5. If you are unlucky, wrong scene gets reopened

**Comment by KoBeWi** [comment]
I think I found potential cause. Reopen scene and reopen script has the same shortcut. I sometimes use it when inside script editor, which results in reopening a built-in script, which also opens the corresponding scene (which might a different scene than from the last opened). If that's really the case, not sure if there's any proper fix.

**Comment by Calinou** [comment]
@KoBeWi Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

**Comment by KoBeWi** [comment]
As I said in my previous comment, this is related to undo close tab having the same shortcut for scenes and script editor. When used in script editor, it will reopen a script, which will reopen a scene if it was a built-in script. The behavior is reliable if you keep that in mind.
