### ISSUE TITLE
Quick Open opens a scene in the Inspector as a Resource

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#40421]
**Godot version:**

Godot_v3.2.2-stable_win64

**OS/device including version:**

Windows 7 x64 SP1

**Issue description:**

A scene opened using "Quick Open..." dialog didn't open normally but in the Inspector, like a Resource.

I expected it to open like when using "Quick Open Scene..." dialog.

**Steps to reproduce:**
Open the "Quick Open..." dialog (Shift+Alt+O) then select and open any scene.

**Minimal reproduction project:**

Any project with any scene will do.

**Comment by akien-mga** [comment]
Fixed by #39928 already.
