### ISSUE TITLE
Godot-mono crashes every time game builds with 

### ISSUE THREAD

**Issue by kfpenguin** [godotengine/godot#40420]
**Godot version**:

    Godot Engine v3.2.2.stable.mono.custom_build.6a9fbafcb

**OS/device including version:**

OS

    Manjaro

GPU Model

   GeForce RTX 2080 Ti

Drivers

    440.82

Backend

    OpenGL ES 3.0 Renderer: GeForce RTX 2080 Ti/PCIe/SSE2

**Issue description:**
**What Happened**

Just recently, every time my game builds, godot-mono crashes. If I play, it will still open debug window and can play game but godot will either quietly die in background or will hang. I'm not sure what combination of things in my project is causing this crash. I've been able to open another project and build it without crashing, albeit it is a much smaller project.

**What is Expected**

I can do a build of my game and play it without godot crashing.

**Steps to reproduce:**

Play the main scene or build.

**Reproduction project:**

[godot-mono-crash.zip](https://github.com/godotengine/godot/files/4925930/godot-mono-crash.zip)

This includes entire project, plus crash report (crash-log-verbose.txt) from running "godot-mono --editor --verbose" and copying the output of the crash. So hopefully, this will help determine what the issue is.

**Comment by kfpenguin** [comment]
Sorry, forgot to include errors received:
ERROR: load_assembly: Condition "stored_assembly == __null" is true. Returned: false
   At: modules/mono/mono_gd/gd_mono.cpp:563.
ERROR: reload_scripts_domain: Mono: Failed to load 'GodotTools' assemblies.
   At: modules/mono/mono_gd/gd_mono.cpp:1108.

**Comment by raulsntos** [comment]
Can anyone still reproduce this issue in Godot 3.5.1 or Godot 4.0 RC3?

**Comment by raulsntos** [comment]
Closing due to lack of response. If anyone is able to reproduce this issue in a newer version of Godot (3.5 or greater) please open a new issue.
