### ISSUE TITLE
GDScript built in float(int) error

### ISSUE THREAD

**Issue by chrisskeddy** [godotengine/godot#40430]
OS: MXLinux
Godot Engine v3.2.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 960/PCIe/SSE2

GDScript seems to have a bug when converting large numbers from ints to floats. The large numbers are near 32bit max in other languages but should not be a problem since GDScript is using 64bit for storing the data.

```
        var f = float(4294967295)
	print(f)
	f-=1
	print(f)
	f = float(429496729)
	print(f)
	f = 4294967295.0
	print(f)
```
The above code produces the following. The conversions from int to float are wrong
Output:
4294967296
4294967295
429496736
4294967295

**Comment by TheDuriel** [comment]
Fairly sure floats are 32bit, and that changing that is slated for 4.0

**Comment by chrisskeddy** [comment]
> Fairly sure floats are 32bit, and that changing that is slated for 4.0
If that was the case the float would not be able to store/return a value of 4294967296 as that is the 33 bit set to ON/1 and all other bits set to 0.

**Comment by TheDuriel** [comment]
Let me clarifly: they're inconsistently cast in places, and should be assumed to be 32bit. I'm not sure what the state on the cleanup effort is, but there will be an issue for it.

**Comment by akien-mga** [comment]
This is fixed in the current `master` branch.
