### ISSUE TITLE
Tile floodfill not working with tiles in same atlas

### ISSUE THREAD

**Issue by dugramen** [godotengine/godot#40435]
**Godot version:** 

3.2.2

**OS/device including version:**

Windows 10

**Issue description:**

I have a tile atlas containing "floor" tiles. I expected to be able to fill in a floor with a different tile using the fill bucket, but it doesn't do anything. 
Instead, I have to fill in the floor with a different tile (one not from the same atlas) and then fill it again.

**Steps to reproduce:**

- Open TileMapBug scene and select TileMap in the tree.

- Try to use fill bucket to replace the yellow tiles with another color tile, it does not work.

- Do the same but on an X tile, it works normally here.

[TileMapBug.zip](https://github.com/godotengine/godot/files/4939275/TileMapBug.zip)

**Comment by Calinou** [comment]
@dugramen Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by dugramen** [comment]
Oh yeah sorry, I updated the main post
