### ISSUE TITLE
Export enums fail to parse when using new := declaration format

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#40433]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux Mint

**Issue description:**
When declaring an export of type enum, only the original way of declaring type in brackets work, if you use := then you get an error of 'Invalid export type. Only built-in and native resource types can be exported.'

```
extends StaticBody2D

enum TURRET_STYLE {FULL,POS1,POS2,POS3,POS4,POS5}

export(TURRET_STYLE) var temp4 = TURRET_STYLE.FULL
export var temp5:TURRET_STYLE = TURRET_STYLE.FULL    #error here but not above
```

**Comment by bojidar-bg** [comment]
> 3.2.2 stable

![image](https://user-images.githubusercontent.com/5276727/87642580-6725d600-c752-11ea-81d4-aff4f56a2945.png)

Are you sure?

**Comment by Calinou** [comment]
I believe string descriptions for exported enums are mandatory since Godot 3.2.

**Comment by chucklepie** [comment]
@bojidar-bg 
export(TURRET_STYLE) var temp4 = TURRET_STYLE.FULL

This line works. There should be no difference between casting and () as far as declaration of variables go.

Regarding your other point, yes you're right, who'd have thought the GDScript parser only shows the last error and not the first... But that does not detract from the question so I will adjust my question to make it simpler.

**Comment by bojidar-bg** [comment]
@chucklepie What I meant in my comment is that enum type hints are not implemented in 3.2.x, while you listed "3.2.2" as the Godot version in the issue template. So, it is not possible to declare such a variable even without `export` there.

**Comment by Calinou** [comment]
Enum type hints aren't supported in 3.2.x (and won't be in 3.2.x), closing.

**Comment by chucklepie** [comment]
:(

This makes using enums almost pointless as you can pass them around.
