### ISSUE TITLE
Node Type - Dictionary Node

### ISSUE THREAD

**Issue by Zaphodious** [godotengine/godot#4043]
I would like to request a special node type. This node type would have a dictionary member, with pairs editable (addable, removable, changeable) in the inspector. This node would have a resource field for a JSON file from which information would be loaded on ready(), and a method save() that takes the current values and saves them to the file. The inspector would also have a few buttons to save and load to the json file, and (potentially) the ability to mark certain pairs as read-only.

The ideal use case is with this as the root node for instanced scenes. This way, custom values can be easily changed in the editor without having to edit child nodes (making things cleaner, simpler, and more straightforward). Also, it would add a built-in way to save and load simple data sets without a developer having to copy-paste from the wiki, mitigating potential bugs and streamlining the development of many kinds of games.

**Comment by bojidar-bg** [comment]
BTW, I would rather like to be able to export dictionaries and function (for buttons) instead... That way this would be implementable via plugins/tool scripts, plus many other possibilities would abound. :smile:

**Comment by Zaphodious** [comment]
Bojidar, that's certainly a better idea. Much more flexible then mine.

**Comment by neikeq** [comment]
I think this could be implemented as an addon.

**Comment by KoBeWi** [comment]
Dictionaries are already able to be exported.
Dictionary node would be basically any Node with this: #5433

Also
> export function (for buttons)

#9380

**Comment by akien-mga** [comment]
Closing as superseded by #5433 and #9380 then.
