### ISSUE TITLE
Shortcut for adding a skeleton bone requires "launchMedia" key not found on most keyboards.

### ISSUE THREAD

**Issue by paraclete-pizza** [godotengine/godot#4044]
The keyboard shortcut for adding a bone for animation is "Ctrl+LaunchMedia." This shortcut is not useful for any standard keyboard, and should probably be remapped to a button that every user has.

![image](https://cloud.githubusercontent.com/assets/6827480/13732170/5cb5779e-e952-11e5-82a4-cf1ececb9f45.png)

**Comment by akien-mga** [comment]
I see that you're still using Godot 1.1. Is it the same in Godot 2.0.1?

**Comment by paraclete-pizza** [comment]
Yes, it is. I'm using 2.0, though that screengrab is from an older version.
