### ISSUE TITLE
EditorPlugin crashes editor on EditorInspector::update_tree

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#40452]
**Godot version:**
3.2 branch commit -- 4abebfa476c54552f55b03bb43d72bd29a7a26b1

**OS/device including version:**
Arch Linux

**Issue description:**
Relative paths on `load` function return `null`, which is normal according to the documentation.

What I didn't expect is that somehow the following plugin script crashes the editor:
```gdscript
tool
extends EditorPlugin

var instance = load("editor_inspector_test.gd").new()

func _enter_tree():
	add_inspector_plugin(instance)

func _exit_tree():
	remove_inspector_plugin(instance)
```
But the following, which basically does the same, does not crash the editor:
```gdscript
tool
extends EditorPlugin

var PluginTest = load("editor_inspector_test.gd")
var instance

func _enter_tree():
	instance = PluginTest.new()
	add_inspector_plugin(instance)

func _exit_tree():
	remove_inspector_plugin(instance)
```

**Steps to reproduce:**
Open the attached project to get the crash.

**Minimal reproduction project:**
[PluginCrash.zip](https://github.com/godotengine/godot/files/4933738/PluginCrash.zip)

**Comment by timothyqiu** [comment]
This crash is no longer reproducible. I think it has been fixed by #49564.
