### ISSUE TITLE
Editor*Plugin functions run twice due to connected signals

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#40458]
**Godot version:**
3.2 branch commit - 4abebfa476c54552f55b03bb43d72bd29a7a26b1

**OS/device including version:**
Arch Linux

**Issue description:**
Same as  #8324, but it's also happening with EditorInspectorPlugin.

The issue is that if the GDScript code executed is not idempotent, the changes might not be the ones expected.

**Steps to reproduce:**
1. Load the attached project.
2. Click on Node2D -- the only node in the SceneTree.
3. Look at output.

What's happening here is that the `SceneTreeDock`'s signals `node_selected` and `selection_changed` fire and are somehow connected to the `EditorPlugin`.

I haven't looked into this much, but here are the stack traces for the [first `can_handle`](https://github.com/godotengine/godot/files/4934995/first.txt) of outputs and the [second `can_handle`](https://github.com/godotengine/godot/files/4934996/second.txt) `OS::print`s you'll see by doing the steps above.

**Minimal reproduction project:**
[TwiceBug.zip](https://github.com/godotengine/godot/files/4935016/TwiceBug.zip)

**Comment by me2beats** [comment]
same on Windows
```gdscript
tool
extends EditorPlugin


var plugin

func _enter_tree():
	plugin = Inspector.new()
	add_inspector_plugin(plugin)


func _exit_tree():
	remove_inspector_plugin(plugin)


class Inspector:
	extends EditorInspectorPlugin

	func can_handle(obj:Object):
		print(obj)
		return true
```
clicking any node in a scene tree prints the same node twice.
Tho this doesn't happend when selecting files in FileSystem dock (`ImportDockParameters` prints once)

**Comment by avencherus** [comment]
Not sure at which commit exactly, but appears to be fixed at least as of the most recent ebe9d61ec78041c9c06cbb57ee42d7dbdcf015d8.

Have you tried the latest commit?

**Comment by me2beats** [comment]
@avencherus yeah I don't see this problem since 3.2.4.b1 cool:)

**Comment by Calinou** [comment]
Closing as resolved.
