### ISSUE TITLE
GUI Button events should pass in the button object

### ISSUE THREAD

**Issue by monk-e-boy** [godotengine/godot#40455]
3.2.2

**OS/device including version:**
Windows

**Issue description:**
Button `pressed` event does not pass in the button object that was clicked - e.g. CheckButton how do you find the stated of the button? Is it checked?

The following does not work:

![image](https://user-images.githubusercontent.com/17924807/87722685-6f146300-c7b0-11ea-896d-6d7857753d47.png)

Should follow industry standards, e.g. C#

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.click?view=netcore-3.1
https://docs.godotengine.org/en/stable/classes/class_checkbutton.html

**Comment by andy-noisyduck** [comment]
As a workaround you could bind the argument during your `connect` call so that the button is passed as an argument.
