### ISSUE TITLE
Mouse coordinate issue (not under cursor)

### ISSUE THREAD

**Issue by Frooztyes** [godotengine/godot#40456]
Hi, 

I am using Godot 3.2.2.stable on Windows 10.
I use a GeForce GTX 1060 (all my graphic drivers are up to date).

I was trying to create an archer that shoot to the cursor. But everytime when i tested my code, the arrow were above the cursor.
It was not a script error. So i created a scene that follow the mouse position but the object was above my cursor by like 150 pixels. You can find a demo here : [youtube link](https://youtu.be/YI3R2prHSiw)

I don't know if it will do same on other computers but in case, i have just created a scene with ``move_and_slide(get_global_mouse_position() - position)`` in ``func _process(delta: float) -> void:`` and the bug occurs for me

I can't drag my file in here so here is a mega link [(mega link).](https://mega.nz/file/hvRSGayI#8tRsDtOdf7UINtL7KUln7Yw5Zi2mewJ3kCJfQnLzwXc)
Don't run the .exe, it's not up to date. But go to LevelSwamp scene and start it with F6, a small mushroom should follow your cursor with an offset.

Thanks for the future answer. Bye.

**Comment by Keetz** [comment]
Seems like you just doesn't calculate the position correct.

If you go into your Dobby.gd script and change:
`move_and_slide(get_global_mouse_position() - position)`
to:
`move_and_slide(get_global_mouse_position() - global_position)`

It will now be on top of the cursor.

**Comment by Frooztyes** [comment]
Ok thank you for explanation, i am new to Godot. 

Wish you the best, thank you :)
