### ISSUE TITLE
godot export to html5, and the OmniLight or SpotLight's shadow can not show

### ISSUE THREAD

**Issue by garuhester** [godotengine/godot#40462]
**Godot version:**

v3.2.1

**OS/device including version:**

GLES3

**Issue description:**

godot export to html5, and the OmniLight or SpotLight's shadow can not show, only the directionalLight can show the shadow
![image](https://user-images.githubusercontent.com/23695326/87768944-7b033200-c84f-11ea-82ba-8ce16c4f2eeb.png)
![image](https://user-images.githubusercontent.com/23695326/87768992-88b8b780-c84f-11ea-97eb-e2060737fecb.png)

**Steps to reproduce:**

**Minimal reproduction project:**

[3ddemo.zip](https://github.com/godotengine/godot/files/4936750/3ddemo.zip)

**Comment by Calinou** [comment]
Switch to the GLES2 renderer. The GLES3 renderer isn't supported anymore when exporting to HTML5, as WebGL 2.0 support is very poor across the board.
