### ISSUE TITLE
Importing ogg vorbis with embedded cover crashes

### ISSUE THREAD

**Issue by xelivous** [godotengine/godot#40460]
**Godot version:**
v3.2.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Import an ogg file that has an embedded cover and it will crash on import

Similar to issue #27022

I've only tested a png but i can test other formats if necessary.

**Steps to reproduce:**
1. create an ogg with a cover embedded in it.
    * easy way is using foobar2000's tagging functionality
2. throw it into your project and let godot try to auto-import it
3. crash

**Minimal reproduction project:**
* [Here's a basically empty ogg file with a just a simple mspaint cover attached to it](https://github.com/godotengine/godot/files/4935246/untitled_with_cover.zip)
* [The same file, without the cover (successfully imports)](https://github.com/godotengine/godot/files/4935247/untitled_no_cover.zip)
* [A minimal project that has the ogg in the root of it i guess](https://github.com/godotengine/godot/files/4935250/testogg.zip)

**Comment by KoBeWi** [comment]
Looks like #32145

**Comment by EIREXE** [comment]
> Looks like #32145

The other issue seems to say "no longer reproducible in master" however if it's still reproducible in 3.2 (I have found it to be the case in my build) then I think it should remain open?

**Comment by akien-mga** [comment]
Try 3.2.3 beta 1, sounds like a bug I fixed already.

**Comment by KoBeWi** [comment]
Yeah, it doesn't crash in 3.2.3.
