### ISSUE TITLE
Formatting from 16-bit to 8-bit audio file

### ISSUE THREAD

**Issue by noass** [godotengine/godot#40478]
I tried this with a .wav file both from import and in the properties, but nothing changes. When I run the game and switch from 16-bit to 8-bit it works, but doesn't save when I close the game and it still stays on 8-bit, but is 16-bit...

I have Windows 10 installed

**Comment by KoBeWi** [comment]
Did you press the reimport button after changing in the Import tab?

**Comment by Calinou** [comment]
@_CHANGEME Can you (or anyone else) still reproduce this bug in [Godot 4.0.1](https://godotengine.org/article/maintenance-release-godot-4-0-1/) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment]
Pretty sure this issue is no longer valid after 3 years (and never was).
