### ISSUE TITLE
var2bytes() always returns the same value regardless of input

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#4047]
**Operating system or device:**
Ubuntu Linux 15.10 64bit, godot built from ad29ee3

**Issue description** (what happened, and what was expected):
var2bytes() always returns a RawArray consisting of [2, 0, 0, 0, 0, 0, 0, 0] regardless of what number it's given as input.

**Steps to reproduce:**
var a = var2bytes(12000)
print(a[0], a[1], a[2], a[3])
stdout: 2000

var a = var2bytes(123500)
print(a[0], a[1], a[2], a[3])
stdout: 2000

**Comment by AlexHolly** [comment]
Try this 
```
	for i in a:
		print(str(i)+",")
```

**Comment by hetdegon** [comment]
Wait, what? Sure that'll add commas to the output, but it'll still be 2,0,0,0,..., unless I am missing something?

**Comment by AlexHolly** [comment]
Hm maybe it is only there to tell godot what type it is. Do you expect the length of the array in the first bytes like the serialization is adding?

Only the first bytes are the same.This is what my code example shows.

**Comment by hetdegon** [comment]
Nah, even in the debugger it's always 2,0,0,0,0,0,0,0 no matter what.

**Comment by AlexHolly** [comment]
I use Ubuntu 14.04 , 64.bit
My godot build is max. 2 days old maybe it is a new bug?

```
	var a = var2bytes(12000)
	for i in a:
        print(str(i))
```
OUTPUT:
2
0
0
0
224
46
0
0

**Comment by hetdegon** [comment]
I just rebuilt and it works like that too, but...what kind of byte order is this following? Seems for 16-bit ints the bytes are placed in indices 4 and 5, and what's that 2 in index 0 even meant to be?

Doing the same operation with bitwise ops yields expected results
```
static func int2raw(n):
	var retval = RawArray()
	retval.resize(4)
	for i in range(0, 4):
		retval[i] = (n >> (i * 8) & 0xFF)
	print(n, ":",retval[0], ",",retval[1], ",",retval[2], ",",retval[3])
```
>4000:160,15,0,0

but using var2bytes the expected values are in indices 4 and 5...anyone can explain this?
Seems the bug is less that it's not working and more like it's just acting funny.

**Comment by AlexHolly** [comment]
Looks like 2 is the type 2 for an int. I think this var2bytes it to prepare them to send over a Stream.
http://docs.godotengine.org/en/latest/reference/binary_serialization_api.html

**Comment by hetdegon** [comment]
How come those bytes end up in positions 4 and 5 though? shouldn't they be 1,2 or 7,8 instead?
