### ISSUE TITLE
Project Settings, OS, and String, not respecting OS path conventions correctly

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#40475]
**Godot version:**

3.2 Stable

**OS/device including version:**

Win 10

**Issue description:**

```
extends PanelContainer
"""
	FileBrowser Scene Script
"""

const STORY_FILE_PATH_INTERNAL: String = "res:/Game/Stories/"
var STORY_FILE_PATH_EXTERNAL: String = ""


func _init() -> void:
	var ex: String = OS.get_executable_path()
	ex = ex.get_base_dir()
	STORY_FILE_PATH_EXTERNAL = ex.plus_file("Game").plus_file("Stories")
	print(STORY_FILE_PATH_EXTERNAL)
	
	var a = ProjectSettings.globalize_path("res://").plus_file("Game").plus_file("Stories")
	print(a)
```

Shitty example from a live project of mine, testing this. Print output:

```
D:\SoftwarePortable\Godot_v3.2-stable_win64.exe/Game/Stories
D:/Projects/NEMETON/Nemeton/Game/Stories
```

Of course, Windows is nice enough not to care about which type of slash you use. But that is not given behavior.

It also seems that this inconsistency causes get_base_dir() to fail with paths returned by the OS singleton.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Ev1lbl0w** [comment]
AFAIK Godot only works with `/` paths for consistency, and corrects them automatically for Windows. In that case, I'd say the unexpected behaviour is actually `get_base_dir` returning paths with `\`.
