### ISSUE TITLE
Mono version on Ubuntu can't find .NETFramework,Version=v4.7

### ISSUE THREAD

**Issue by TheHypeTrain** [godotengine/godot#40482]
**Godot version:**
3.2.2.stable.mono.official

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
Every time I try to build this project, it fails.
same as https://github.com/godotengine/godot/issues/36818, but I am on ubuntu and can't use .NET 4.7. Most projects work, but not isometric.

**Steps to reproduce:**
try to build any project

**Minimal reproduction project:**
isometric(godot-demo-projects/2d.isometric)

Error message: 
Project "Isometric Game.sln" (Build target(s)):
	Message: Building solution configuration "Debug|Any CPU".
	Project "Isometric Game.csproj" (default targets):
		/usr/share/dotnet/sdk/3.1.300/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/tht/Downloads/godot-demo-projects/2d/isometric/Isometric Game.csproj]
	Done building project "Isometric Game.csproj" -- FAILED.
Done building project "Isometric Game.sln" -- FAILED.

**Comment by TheHypeTrain** [comment]
I ran dotnet --version and got 3.1.300. I retargeted the application by changing line 11 of the csproj file, but I still get the same error, only now complaining that it can't find v3.1.300.
My mono version is Mono JIT compiler version 6.10.0.104

**Comment by akien-mga** [comment]
Similar to #40546, I'll let you see if you want to close either as duplicate @neikeq or keep them separate as they're for Windows and Ubuntu respectively.

**Comment by neikeq** [comment]
They're the same. Closing this one as duplicate. It was created first, but discussion continued in the other one.
