### ISSUE TITLE
2d nodes should have z property

### ISSUE THREAD

**Issue by voidplayer** [godotengine/godot#405]
most other engines i have tried have this. They draw like godot, based on their position on the tree... but have separate drawing trees for every value of z... everything goes into the z=0 by default.

This allows to set what is on top of what easily. The workaround is use get_index and move_child... and raise... and it feels hackish at best

not sure how easy would be to implement because right now you only have to travel the scene tree once to draw, but sure would be nice for game developers (maybe automatically reorder the node tree based on z when something is added to it?)

**Comment by not-surt** [comment]
Also desirable: the ability to vary z-order across a tilemap, so as to allow interleaved rendering of both tilemap-with-tilemap and tilemap-with-sprites. Necessary for proper isometric (and other axonometric) rendering.

**Comment by adolson** [comment]
2D nodes now have z property.

**Comment by not-surt** [comment]
Why is Z a limited range integer?
What if I want to independently Z order 1025 sprites?
Wouldn't full-range floats be better than this apparently arbitrary limitation?

**Comment by reduz** [comment]
nope performance issues, and the fact the main sorting is done tree-wise.
Range could be increased though (1024 was just an idea, but my be little)

**Comment by reduz** [comment]
you have other tools to sort, you can use y-sort, tree-sort, remote
transform, etc. This is mostly for consistency when splitting into many
scenes.

**Comment by akien-mga** [comment]
What's the status on this issue?

**Comment by ndee85** [comment]
This issue can be closed. A z value has been added by reduz.

**Comment by Zireael07** [comment]
Do Controls have a z value, though? I can't find it...

**Comment by vnen** [comment]
@Zireael07 no, the Z property exists only for Node2D and its descendants.

**Comment by reduz** [comment]
you can put a GUI under a Node2D and change the Z of that node, and the GUI
will change Z too

**Comment by phil123456** [comment]
there is no move_child in 2D nodes

**Comment by Noshyaar** [comment]
http://docs.godotengine.org/en/latest/classes/class_node.html#class-node-move-child
