### ISSUE TITLE
[Bullet] Gravity is applied to RigidBody even with custom_integrator turned on

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#40508]
**Godot version:**
3.2 custom build, issue bisected to commit e7d8464f

**OS/device including version:**
Linux Mint 20

**Issue description:**
The custom_integrator property of rigid bodies is ignored, which causes gravity to be applied when it should not.

**Steps to reproduce:**
Add a RigidBody to a scene, turn custom_integrator on/off, the RigidBody will fall regardless.
Building Godot from a commit prior to e7d8464f (or the latest stable 3.2 release) does not cause this issue.

**Minimal reproduction project:**
[CustomIntegrator.zip](https://github.com/godotengine/godot/files/4943606/CustomIntegrator.zip)
The custom_integrator property is turned on in this project, yet the box still falls due to gravity. I have to actively subtract gravity in `_integrate_forces()` to prevent the box from falling, but even then it will move downward slowly. In previous versions, the box stays perfectly still, or falls upward if I subtract gravity, as is expected.

**Comment by Calinou** [comment]
cc @madmiraal

**Comment by AndreaCatania** [comment]
I'm working on a fix for this.

**Comment by AndreaCatania** [comment]
Fixed with: https://github.com/godotengine/godot/pull/40252

**Comment by Cykyrios** [comment]
I just tried your changes on master, and it works properly again. Thanks! Now I'll just have to wait for the 3.2 version of it.

**Comment by madmiraal** [comment]
Reopening because #40252 was reverted with #42639.

**Comment by akien-mga** [comment]
Fixed by #62708.
