### ISSUE TITLE
[3.2][HEAD] Directories cannot be created anymore

### ISSUE THREAD

**Issue by Relintai** [godotengine/godot#40509]
**Godot version:**
https://github.com/godotengine/godot/commit/89f57ae12244f3269c9e3fe4684e16ec1fd2c989

Note that I did not test master, it might be an issue there aswell.

**OS/device including version:**
Tested it on:
Linux, Manjaro. Kernel: 5.6-4
Android 9
Windows

**Issue description:**
After the recent changes to `Directory` they have to be `open()`-ed before use, however `Directory.open()` will not actually open a non-existant directory, which means that new directories cannot be created, because now `Directory.create()` fails with an error saying `make_dir: Directory must be opened before use.`

**Steps to reproduce:**
```
var dir = Directory.new()
dir.open("user://test")
dir.make_dir("user://test")
```

If the test folder doesn't exists you get a `make_dir: Directory must be opened before use.` error on `dir.make_dir("user://test")`'s line, and that directory won't be created.

**Minimal reproduction project:**
[dir_open_test.zip](https://github.com/godotengine/godot/files/4943820/dir_open_test.zip)

output for me:
If Directory doesn't exists:

```
Trying to open directory: user://test
dir.open("user://test"): 31
Directory doesn't exists: try create
dir.make_dir("user://test"): 3
dir.make_dir_recursive("user://test"): 3
```
else (I made it delete the folder for testing purposes) (remove works):

```
Trying to open directory: user://test
dir.open("user://test"): 0
Directory exists: Removing
dir.remove("user://test"): 0
```

Human readable error codes:
```
Error 0 = OK
Error 3 = ERR_UNCONFIGURED
Error 31 = ERR_INVALID_PARAMETER
```

**Comment by Xrayez** [comment]
Yeah, I stumbled upon this in #40234, and I think I didn't got to actually test this properly because the directories existed, because most usages are in the form of:

```gdscript
static func make_dir(path):
	var fs = Directory.new()
	if not fs.dir_exists(path):
		fs.make_dir(path)
```

It likely also affects `make_dir_recursive`.

CC @nathanfranke 🙂

**Comment by Relintai** [comment]
> It likely also affects `make_dir_recursive`.

Yes it does, although I managed to not state it explicitly, my minimal reproduction project tests for it.

**Comment by avencherus** [comment]
Ran into the issue with recursive as well.

In my case, I think I worked around it by opening it to user:// when creating the directories there.

Maybe there are still circumstances when it doesn't already exist during play?

**Comment by Relintai** [comment]
> In my case, I think I worked around it by opening it to user:// when creating the directories there.

That's really clever lol
