### ISSUE TITLE
3D viewport control modifier keys acting as toggles when using a Wacom pen

### ISSUE THREAD

**Issue by profanicus** [godotengine/godot#40502]
**Godot version:**
3.2.2 stable win64

**OS/device including version:**

Windows 10 Pro 19041
Wacom Intuos Pro
Default Godot control scheme

**Issue description:**
When using the Wacom pen's middle-click button to navigate the 3D view, the modifier keys are acting as toggles.

You can no longer hold ctrl and shift to zoom and pan, you must instead press to activate and then press again to deactivate.

The keys are working as usual with a mouse, and working as usual with the Wacom in 3.2.1 stable.

**Steps to reproduce:**
**Minimal reproduction project:**

**Comment by Calinou** [comment]
@profanicus Can you test this with [3.2.2 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.2.2/) to narrow down the regression?

**Comment by profanicus** [comment]
Hey @Calinou, no problem! 

I checked and the last good version is Godot_v3.2.2-beta2_win64.

One other notable thing that may help, is the state of these toggled modifier keys seems to be remembered between sessions.

**Comment by akien-mga** [comment]
Might be related to #38658, CC @bruvzg.

**Comment by akien-mga** [comment]
(Assigning `3.2` milestone to track the regression fix for stable, but it's likely also affecting `master` too.)
