### ISSUE TITLE
Mousewheel scroll not working in the Script Editor

### ISSUE THREAD

**Issue by DJKero** [godotengine/godot#40519]
**Godot version:**
3.2.2.stable.official

**OS/device including version:**
Windows 10 (Up to date)

**Issue description:**
Out of the blue, the mousewheel didn't work anymore to scroll in the script editor.
Found out that disabling "Smooth Scroll" on Editor Settings > Text Editor > Navigation solved the issue.

**Comment by Calinou** [comment]
Did you increase Physics Fps in the Project Settings? If so, this is a duplicate of https://github.com/godotengine/godot/issues/28385.

**Comment by DJKero** [comment]
Oh, I searched "mousewheel" and didn't get any result. My bad!
