### ISSUE TITLE
Changing Scene Not Working In Exported Version of Game

### ISSUE THREAD

**Issue by QuackDuckStudios** [godotengine/godot#40516]
**Godot version:**
3.2.2 & 3.2.1 ( I tried it in both )

**OS/device including version:**
![image](https://user-images.githubusercontent.com/66213003/87882421-95ccd680-ca08-11ea-8248-2c8dc081605a.png)

**Issue description:**
I am changing scenes using `get_tree().change_scene()`. It works when I playtest it from Godot, but when I export it, it doesn't.

**Minimal Reproduction Project**
https://mega.nz/folder/fw8T0SwT#7aWT8oQiql6TUqIx82hugQ

**Comment by Calinou** [comment]
@QuackDuckStudios Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, remember that Windows' file system is case-insensitive, but the virtual PCK filesystem used by exported projects is case-sensitive. Double-check the file paths you've written in your scripts.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this issue and make sure to upload a minimal reproduction project.
