### ISSUE TITLE
Particles don't work in Godot 4.0, really want to test them . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot#40529]
**Godot version:**
Godot 4.0 hash a474926ac

**OS/device including version:**
Windows 10 PC . .

**Issue description:**
This might not be a bug, but the particlesystem doesn't work . . It's disabled . .
![2020-07-20 0716](https://user-images.githubusercontent.com/61069740/87905562-2931f600-ca61-11ea-947e-f29c3b14f44c.gif)

The particle system is getting updated, it might be why, I simply don't know . . No matter what, Godot 4.0 is already a beast, a real pro looking engine, it looks like Unreal engine and, better than Unity . .

**Steps to reproduce:**
Added a particle system, and it didn't work, sry . .

**Minimal reproduction project:**
REALLY want to test some particles, hope you add it soon, I know you work super-hard, cool stuff, CAN'T wait, for Godot 4 <3 . . Thx . . . Also, changing name from Particles, to GPUParticles helps me a lot, as it was confusing before, thank you . . .

**Comment by Calinou** [comment]
Particles haven't been implemented yet in the Vulkan renderer: https://github.com/godotengine/godot/issues/35353
