### ISSUE TITLE
error(1,0): Invalid member for expression: .xyzz; In shader code that uses swizzling.

### ISSUE THREAD

**Issue by DragonAxe** [godotengine/godot#4053]
**Operating system or device:**
Arch Linux: 4.4.5-1-ARCH x86_64 GNU/Linux

Graphics card info:

```
00:02.0 VGA compatible controller [0300]: Intel Corporation Haswell-ULT Integrated Graphics Controller [8086:0a16] (rev 09) (prog-if 00 [VGA controller])
    Subsystem: Toshiba America Info Systems Device [1179:fa48]
    Flags: bus master, fast devsel, latency 0, IRQ 44
    Memory at f7800000 (64-bit, non-prefetchable) [size=4M]
    Memory at e0000000 (64-bit, prefetchable) [size=256M]
    I/O ports at f000 [size=64]
    Expansion ROM at <unassigned> [disabled]
    Capabilities: <access denied>
    Kernel driver in use: i915
    Kernel modules: i915
```

**Godot verson:**
Godot_v2.0.1_stable_x11.64

**Issue description:**:
When using the following shader code in Godot that demonstrates 'swizzling'...

``` Python
// Blank line #1
vec3 a = vec3(1,2,3);
vec3 b = a.zyx; // b will contain vec3(3,2,1)
vec2 c = a.xy; // c will contain vec2(1,2)
vec4 d = a.xyzz; // d will contain vec4(1,2,3,3)
```

I was given the following error: `error(1,0): Invalid member for expression: .xyzz`.  Also notice that the error message points to line 1 instead of line 5.

Note: This sample code came from the Godot Docs: http://docs.godotengine.org/en/latest/reference/shading_language.html#swizzling

It appears that the vec4 dot notation doesn't work at all without throwing an error.
At first, I thought it was due to the double 'z' character, but Godot doesn't like `vec4 d = a.xyzw;` either.

It appears that the error message originates from shader_language.cpp at line 1892, but my brief look at the code didn't reveal why vec4s don't work and vec2s and vec3s do.
https://github.com/godotengine/godot/blob/master/servers/visual/shader_language.cpp#L1892

**Steps to reproduce:**
1. Open a new project
2. Add a new textureframe to the scene graph
3. Add a new CanvasItemMaterial to the Materials property of the textureframe
4. Add a new CanvasItemShader to the Shader property of the CanvasItemMaterial
5. Edit the new shader and add the sample code above to the textbox that is shown
6. Wait for the shader to be compiled and the error message to be shown below the text area

**Comment by reduz** [comment]
shader compiler will get a rewrite in 3.0, so awaiting for this version

**Comment by reduz** [comment]
shader compiler got a rewrte in 3.0, so you don't have to await any longer, reduz of a year ago.
