### ISSUE TITLE
the reference assemblies for .net framework version=v4.7 were not found

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#40546]
**Godot version:**
3.2.2 mono

**OS/device including version:**

Windows 10

**Issue description:**

Error when building a project:
`the reference assemblies for .net framework version=v4.7 were not found
`

**Steps to reproduce:**
Windows 10 builds >= 1903 are delivered with .NET Framework 4.8.0, but Godot generates a .csproj-File with `<TargetFrameworkVersion>v4.7</TargetFrameworkVersion>`  . 

Can we change the Target Framework to 4.8 or **at least tell the people** that .Net 4.7.* is required? I know about 5 people who had that problem and asked for help on the Godot Discord Server.

**Comment by akien-mga** [comment]
Godot 3.2.2 is supposed to download .NET Framework 4.7 automatically when it's missing. Seems like it's not working for everyone. @neikeq

**Comment by neikeq** [comment]
I swear there was another issue about this from a few days ago, but I can't find it now.
I just realized yesterday that the Godot editor is actually not calling `restore` when building. Both on master and 3.2. I added the logic but forgot to add the actual argument to the MSBuild command. I'll be fixing this tonight.

**Comment by JupiterRider** [comment]
@neikeq This one? https://github.com/godotengine/godot/issues/40482
