### ISSUE TITLE
Android custom build apk size issue

### ISSUE THREAD

**Issue by akirayui** [godotengine/godot#40545]
**Godot version:**
3.2.2.stable

**OS/device including version:**
Ubuntu
GLES2

**Issue description:**
I built two templates for Android following the instructions in the link below https://docs.godotengine.org/en/stable/development/compiling/compiling_for_android.html
Files:
android_release.apk 7.1MB
android_debug.apk 8.8MB

Then I followed the instructions in this link 
https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html

I successfully exported the project, but the size of the release apk surprised me. Although the template is only 7.1MB, exported empty project is 20.1MB. Why such a difference may occur and how can I reduce the apk size?

**Steps to reproduce:**
https://docs.godotengine.org/en/stable/development/compiling/compiling_for_android.html
https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html
Export empty project.

**Comment by akien-mga** [comment]
You're probably not using your custom compiled templates.

If you use the Custom Build feature, you should replace the `android_source.zip` in the templates folder, remove your `res://android` folder and re-install the template. Otherwise you're still using the original 3.2.2.stable libraries.

**Comment by akirayui** [comment]
I had placed android_souce.zip in the templates folder but it seems re-installing Android Build Template is required.
Apk size is now 7.5MB. Thank you.
