### ISSUE TITLE
HTTPRequest METHOD_GET is ignoring request data

### ISSUE THREAD

**Issue by ChronoDK** [godotengine/godot#40564]
**Godot version:** 3.2.2 stable

**OS/device including version:** Chrome 84 (latest)

**Issue description:**
In an HTML5 build when doing a GET request from an HTTPRequest, the request data is thrown away and not sent.

In my tests it works just fine from the editor, but not in the HTML5 build. There is no body data shown in the Networking tab in Chrome either. It's just not sent.

**Steps to reproduce:**
Make a HTTPRequest METHOD_GET request with request data and watch the networking tab in Chrome. No data is sent.

```gdscript
var headers = ["Content-Type: application/json"]
var url = "someUrl"
myHttpRequest.request(url, headers, true, HTTPClient.METHOD_GET, "some request data")
```

**Comment by Calinou** [comment]
@ChronoDK Please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it when reporting bugs.

**Comment by ChronoDK** [comment]
@Calinou Sorry, updated to use the template now.

**Comment by Calinou** [comment]
@ChronoDK Ah, I think I understand it now. GET requests can't send data in their body; you need to use query parameters in the URL instead.

If you need to send body data, use a POST request instead.
