### ISSUE TITLE
error on exit, is it an actual bug

### ISSUE THREAD

**Issue by 1xch** [godotengine/godot#40575]
**Godot version:**

 v3.2.1.stable.custom_build.b0eca5828

**OS/device including version:**

linux/ubuntu

**Issue description:**

just this message on exit

```
ERROR: call_funcv: Condition "!obj" is true. Returned: Variant()
   At: core/func_ref.cpp:55.
ERROR: call_funcv: Condition "!obj" is true. Returned: Variant()
   At: core/func_ref.cpp:55.
ERROR: call_funcv: Condition "!obj" is true. Returned: Variant()
   At: core/func_ref.cpp:55.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
```

**Steps to reproduce:**
after calling

`get_tree().quit()`

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Does this occur only in a specific project, or can you reproduce this in an empty project?

If you can reproduce this in a specific project, please upload it here.

**Comment by 1xch** [comment]
@Calinou 
This occurs in a specific project, my current learning project with a bunch of private stuff

I will look into replicating in a simpler context.

**Comment by 1xch** [comment]
I made some changes to closing my stack manager and now I don't get that message.

More likely my code is the issue.
