### ISSUE TITLE
VisibilityNotifier2D - very high memory usage

### ISSUE THREAD

**Issue by zzz-assault** [godotengine/godot#40577]
### **Godot version:**
- 3.2.2 (stable) - 64 Bit Windows Client

### **OS/device including version:**
- Windows 10 (64 Bit)

### **Issue description:**
Size of VisibilityNotifier2D Rect2 is exponentially increasing the required memory (static)!
This is true if you increase Rect2 size either within editor or via code.

Example:
- Rect2 (0,0 // 300000, 300000) -> Memory (static) usage = **1,76 GiB**

This example is extrem, but it shows the issue.
In my case I needed > 100 notifiers and even on small Rect2 sizes it scaled the memory effect very fast.

### **Steps to reproduce:**
Add a VisibilityNotifier2D and increase Rect2 in editor or use below code.

### **Minimal reproduction project:**
Just add following code to a new 2D Scene:

```
func _ready() -> void:
	var s := VisibilityNotifier2D.new()
	s.rect = Rect2(Vector2(0.0, 0.0), Vector2(300000.0, 300000.0))
	add_child(s)
```

**Comment by Calinou** [comment]
Out of curiosity, can you reproduce this with VisibilityNotifier (3D)?

**Comment by zzz-assault** [comment]
@Calinou just tried -> **NO!** ... VisibilityNotifier (3D) is simply staying on almost no memory usage.
Even after increasing all axis to an absurd 3.000.000.000 it had no issue.

**Comment by qarmin** [comment]
This is probably caused by too small cell size.
You can set in `Project Settings -> World -> 2d -> Cell Size` bigger value e.g. 1000 and then memory usage should drop to ~40MB

**Comment by zzz-assault** [comment]
@qarmin Thank you, will test it.

What is the downside of increasing this setting?

**Comment by zzz-assault** [comment]
Update: I can confirm, that the memory usage with increased "cell_size" in the project settings is getting better. Also it's worth noting, that the cell_size is in **PIXEL**s, for others looking up this issue!

For my project I set the cell_size to the full grid (Rect2), so the memory cost is almost non existant ... as all my Visibilty Notifier are having the same size, this is working also based on the global setting and the lost precision is not noticable.

**Question:**
I understand that heuristic is used for performance reasons, but wouldn't it be more flexible to set the cell_size inside the VisibilityNotifier2D or better directly use the dimension of the Rect2 as one Cell? ( I don't get the reason to split the notifier in multiple cells, besides flexilbility for different VisibilityNotifier2D sizes -> which could be solved by moving this setting to the Node instead of a global project setting)
