### ISSUE TITLE
Mouse move DPI on Input Events? (please change it to a better name!)

### ISSUE THREAD

**Issue by renatodex** [godotengine/godot#40579]
**Godot version:**
v.3.2.1 Stable

**OS/device including version:**
Macbook Pro 2017 13'' default model (macOS Mojave)

**Issue description:**
I have configured a mouse event to paint a Tilemap.
However, depending on the speed of your mouse movement, you can see several gaps between the painted tiles.
The greater is the speed, the greater is the number of Gaps.
Here's a video showcasing the issue:
https://share.getcloudapp.com/P8ueB6Qg

![](https://p-xbf59w.t0.n0.cdn.getcloudapp.com/items/yAuYOK7z/Screen%20Recording%202020-07-21%20at%2006.59%20PM.gif?v=5b30a625a81d9608289586b2bfbf788d)

**Steps to reproduce:**
1. Execute the project.
2. Try to draw a slow line with your left mouse button.
3. Now try to draw a very fast line.
4. You should gap between the draw event.

**Minimal reproduction project:**
[camera_drag_plus_set_tile.zip](https://github.com/godotengine/godot/files/4956491/camera_drag_plus_set_tile.zip)

**Obs**
Initially, I thought it was some issue with my mouse precision or something, but then I've noticed that when I'm painting in Tilemap with the Godot editor, I don't have this problem:
https://share.getcloudapp.com/mXuAePGZ

**Comment by renatodex** [comment]
Hey, I was looking to other examples of people implementing "draw" events, and I found a Demo with the same problem in the **Templates** tab of Godot window. The demo implements a simple paint editor, you can find it searching for called `GD Paint`:
![image](https://user-images.githubusercontent.com/68507/88118429-ee7caa80-cb93-11ea-91cf-25260345909b.png)

**Comment by TheDuriel** [comment]
Entirely expected, Godot does not simulate the traversal of the mouse from one point to another, as that would have undesired consequences for many applications.

The solution, is for you to remember the position of the mouse of the previous frame, then draw a line from there to its current position. Instead of only at its current positions. Mice _teleport_, they don't move gradually.

This is caused by the speed at which the OS provides mouse information to Godot. Not necessarily related to frames rendered, but a faster system with unlocked main loop tick rate will perform better.

**Comment by renatodex** [comment]
Hey @TheDuriel !
Thanks for the quick response!

So do you mean Godot editor actually implements this system you are talking when we draw in the editor?
https://share.getcloudapp.com/mXuAePGZ

As I shared in my initial post, I don't have this problem when I'm drawing in the Godot editor.

To be honest, I didn't quite get your idea of the algorithm, so I wanted to ask you if you could point me to some examples. Don't need to be in GDScript, any language would suffice, I just wasn't to understand the idea.

**Comment by TheDuriel** [comment]
The editor will likely be implementing it.

In rough:

Every Frame:
if  the button is held
get the mouse position
create an imaginary line from the current to the previous position
place tiles on every cell this line crosses
replace the previous mouse position with the current position

**Comment by Calinou** [comment]
What @TheDuriel describes is called [Bresenham's line algorithm](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm). It's already implemented in the TileMap editor but not in the GridMap editor yet.

**Comment by renatodex** [comment]
Thanks so much for the explanations @Calinou and @TheDuriel , you guys are doing an amazing work!
