### ISSUE TITLE
Using INF as float breaks scene

### ISSUE THREAD

**Issue by illogically** [godotengine/godot#40589]
**Godot version:**
v3.2.2.stable.mono.official

**OS/device including version:**

OS: Windows 10

**Issue description:**
After using a tool script to set a Raycast2D node's cast_to to positive y on infinity, I attempted to run the scene but the game simply crashes. After reopening the editor fails to parse the scene. Included in the log is the following:
``` 
 Invalid color code: #.
 scene/resources/resource_format_text.cpp:278 - res://Test.tscn:36 - Parse Error: Expected ',' or ')' in constructor
 Failed to load resource 'res://Test.tscn'.
 Failed loading resource: res://Test.tscn.
 editor/editor_data.cpp:567 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
```

**Steps to reproduce:**
1. Set RayCast2D "Cast To" to INF
2. Run scene or close scene and reopen.

**Minimal reproduction project:**

[INFbug.zip](https://github.com/godotengine/godot/files/4958754/INFbug.zip)

**Comment by Calinou** [comment]
See also previous occurrences of the same issue: https://github.com/godotengine/godot/issues/35388, https://github.com/godotengine/godot/issues/28883.

**Comment by pouleyKetchoupp** [comment]
I've tested on Windows (latest 3.2 branch), and it looks like it's fixed for `float` variables but still occurs with `Vector2`.

Here's the script I'm using to set the values:
```
tool
extends Node

export(float) var test_float
export(Vector2) var test_vec2

func _ready():
	test_float = INF
	test_vec2 = Vector2(INF, INF)
```

**Comment by illogically** [comment]
As a note, entering INF in the editor itself will set it to 1.#INF and displayed as 1.#IO

**Comment by bruvzg** [comment]
> 1.#INF and displayed as 1.#IO

This is non-standard format specific to pre-Visual Studio 2015 C runtime, all other CRTs should print it as `inf`.

**Comment by Calinou** [comment]
Should the editor even allow entering `INF` in the inspector?

**Comment by illogically** [comment]
The only reason why I had to do that was for an Infinite raycast. I'm not aware of any other reason to do so.

**Comment by redoxCode** [comment]
This is a quite consistent 'problem'. 
For example setting the `far` property of a camera to inf (by script or in editor) causes the camera to stop working.
I guess it is quite a task to make everything 'inf proof'. However godot is not the only software that doesn't like `inf`. So I always avoid it and just use very large numbers instead. I guess the point of `inf` is more to have it as output when something overflows, just like `NaN`. Maybe `inf` can be removed from gd script? (what is the use case that can't be solved by replacing it with a large value?)

**Comment by Calinou** [comment]
@redoxCode We can prevent using `INF` in the inspector without removing the constant from GDScript. The inspector accepts expressions written in a ad-hoc language (see the Expression class), not GDScript.

**Comment by redoxCode** [comment]
I know. Still you would have a ton of code to make `inf` prove (since it can still be set to `inf` from script). On a second thought removing `inf` from gs script is really overkill. Maybe we just have to accept that some stuff breaks when set to `inf` (for now). Making everything `inf` prove is quite a task and maybe not worth it in some cases if the checks required decrease performance or bloat the code.

**Comment by Zylann** [comment]
I had the same problem in 3.2.3. I did not input `INF` anywhere but as a result of setting some properties to particular values I ended up with an INF in the scene file and it made the scene impossible to load. While the appearance of INF should be prevented as much as possible, I think it should not break scenes like that, it's not friendly at all.
