### ISSUE TITLE
SpringArm.get_hit_length() does not behave as specified

### ISSUE THREAD

**Issue by jambonsupreme** [godotengine/godot#40585]
**Godot version:** 3.2.2

**OS/device including version:** Windows 8.1

**Issue description:**

This is the description of SpringArm.get_hit_length in the documentation: "Returns the proportion between the current arm length (after checking for collisions) and the spring_length. Ranges from 0 to 1."

Instead of returning a float ranging from 0 to 1 it returns the current spring length. For example if the spring is 4 meters long and it intersects at 2 meters of distance it will return 2 instead of the expected 0.5. An easy workaround would be to divide the result by the spring_length yourself.

I dug a little bit into the source code and found that that the current spring length is calculated correctly, but then it is multiplied by the maximum spring length. This is the relevant part of code in SpringArm.cpp (I also looked at SpringArm_3d.cpp in the master branch and found the same thing).

```
float SpringArm::get_hit_length() {
	return current_spring_length;
}

void SpringArm::process_spring() {
	// From
	real_t motion_delta(1);
	real_t motion_delta_unsafe(1);

	Vector3 motion;
	const Vector3 cast_direction(get_global_transform().basis.xform(Vector3(0, 0, 1)));

	if (shape.is_null()) {
		motion = Vector3(cast_direction * (spring_length));
		PhysicsDirectSpaceState::RayResult r;
		bool intersected = get_world()->get_direct_space_state()->intersect_ray(get_global_transform().origin, get_global_transform().origin + motion, r, excluded_objects, mask);
		if (intersected) {
			float dist = get_global_transform().origin.distance_to(r.position);
			dist -= margin;
			motion_delta = dist / (spring_length);
		}
	} else {
		motion = Vector3(cast_direction * spring_length);
		get_world()->get_direct_space_state()->cast_motion(shape->get_rid(), get_global_transform(), motion, 0, motion_delta, motion_delta_unsafe, excluded_objects, mask);
	}

	current_spring_length = spring_length * motion_delta;   //RELEVANT LINE
	Transform childs_transform;
	childs_transform.origin = get_global_transform().origin + cast_direction * (spring_length * motion_delta);

	for (int i = get_child_count() - 1; 0 <= i; --i) {

		Spatial *child = Object::cast_to<Spatial>(get_child(i));
		if (child) {
			childs_transform.basis = child->get_global_transform().basis;
			child->set_global_transform(childs_transform);
		}
	}
}

```
I would suggest changing
`current_spring_length = spring_length * motion_delta;`
to
`current_spring_length = motion_delta;`
since this variable is not used anywhere else.

**Steps to reproduce:**
Create a SpringArm and set its length to any number other than 1, then call SpringArm.get_hit_length()

**Comment by QbieShay** [comment]
@jambonsupreme thank you for reporting this. I believe this is more an error in the documentation than in the code.

**Comment by jambonsupreme** [comment]
Wow that was fast! Thank you
