### ISSUE TITLE
Can not resize the window animation.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#4058]
**Operating system or device:**
Ubuntu15.04

**Issue description** (what happened, and what was expected):
Can not resize the window animation.

**Link to minimal example project** (optional but very welcome):
![2016-03-15 07 12 54](https://cloud.githubusercontent.com/assets/11325733/13764113/503cb67e-ea76-11e5-99c8-457a8baa48b8.png)

**Comment by akien-mga** [comment]
I can confirm the bug, the icon for resizing shows up but does not work.

**Comment by akien-mga** [comment]
Actually the panel can be resized if it has been selected first using the "Animation" tab at the bottom. It then adds the dotted lines showing that it can be resized on hover, and resizing works.

So the issue appears only when the animation panel shows up after clicking an AnimationPlayer node, but without selecting the tab manually. It should IMO work in both cases.

**Comment by bojidar-bg** [comment]
Note that the same occurs with stylebox edit panel, theme edit panel, and samplelibrary panel as well
