### ISSUE TITLE
Editor crashes on startup when running the Flatpak on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by dh928** [godotengine/godot#40597]
flatpak run org.godotengine.Godot
Godot Engine v3.2.2.stable.flathub - https://godotengine.org
OpenGL ES 3.0 Renderer: llvmpipe (LLVM 9.0.1, 128 bits)
Unable to find target for this triple (no targets are registered)
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/arm-linux-gnueabihf/libc.so.6(+0x275d0) [0x766675d0] ()
-- END OF BACKTRACE --
/app/bin/godot: line 3:     4 Aborted                 /app/bin/godot-bin "$@"

**Issue description:**
I am trying to run godot on y raspberry pi 3 B+, and this happened. How can I fix this?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
You don't appear to have hardware acceleration, which is why the llvmpipe software fallback is used.

Also, try building Godot from source and running it directly instead of using the Flatpak to single out Flatpak from the equation.

**Comment by dh928** [comment]
> You don't appear to have hardware acceleration available, which is why the llvmpipe software fallback is used.
> 
> Also, try [building Godot from source](https://docs.godotengine.org/en/3.2/development/compiling/compiling_for_x11.html) and running it directly instead of using the Flatpak to single out Flatpak from the equation.

I went to the website. It says Start a terminal, go to the root dir of the engine source code and type. I am not sure where the root dir of the engine source is. Also, is my pi using Debian if I am using raspbian? 

I am so sorry. I am really new to this and have no clue what is going on at all
