### ISSUE TITLE
Sound is not reloaded when it changes on disk

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4059]
Windows 7 64 bits, Godot 2.0.1

When I open a sound in Audacity, modify and overwrite it, Godot doesn't notices the change. I have to restart the editor to listen for the new audio.
I don't know if it's a bug or usability enhancement, it would be useful for sure :)

**Comment by neikeq** [comment]
I think it's not a bug, but the sound being cached by _ResourceCache_.

**Comment by vnen** [comment]
I would consider this a bug. The cache is good but if the source changes the cache should be invalidated. Which reminds me of the quote:

> There are only two hard things in Computer Science: cache invalidation and naming things.
> —Phil Karlton
