### ISSUE TITLE
Html5 WebRTC Chrome mDNS

### ISSUE THREAD

**Issue by dantesguilherme** [godotengine/godot#40593]
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10/ Chrome 84

**Issue description:**
Simple WebRTC doesn't work on Chrome. it seems to be related to the mDNS.

**Steps to reproduce:**
try to run the minimal connection example from the docs on Chrome. Export to Html5 and/or run on Browser
if it's working for you, try to active this on  as it may be disabled by default.
chrome://flags/#enable-webrtc-hide-local-ips-with-mdns

**Minimal reproduction project:**
https://docs.godotengine.org/en/stable/tutorials/networking/webrtc.html#minimal-connection-example

**Comment by Faless** [comment]
I'm unable to reproduce on Linux with Chrome 84, although, does it work if you set it to `default`?

**Comment by dantesguilherme** [comment]
I can't reproduce anymore. I'll keep an eye on it but for now I think we can close this one.
