### ISSUE TITLE
Enable shift+del as "cut" in text editor.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#4060]
It'd be pretty nice if the text editor allowed using the keyboard shortcut shift+del, usually "cut text" in most toolkits, text editors and OSs. Using it in Godot just deletes the text without adding it to clipboard, which can be misleading when you try paste the text later. 
The shortcut shift+ins for paste and control+ins for copy already work, so it'd be nice to have its complementary in place as well

**Comment by est31** [comment]
@hetdegon which operating system do you use btw? I can confirm that this works on linux inside my browser, but I never heard of this feature

**Comment by hetdegon** [comment]
Linux here. That shortcut works in pretty much anything except terminals and games, text editors like Atom, Kate and such, browsers, etc. And works in Windows too. Not sure about Macs.

**Comment by hetdegon** [comment]
Weird, I am trying this on a freshly-built version, but it doesn't seem to work. It doesn't copy anything to clipboard. Can anyone else confirm?

**Comment by neikeq** [comment]
I'll check it when I am back home.

**Comment by bojidar-bg** [comment]
Can confirm on 3eddd46fa81cc51ecb3974da7a12883c6bedbe10, <kbd>Shift</kbd> + <kbd>Delete</kbd> would just delete the text, but the clipboard remains the same.
