### ISSUE TITLE
Random temporary files are created when building the engine and aren't always removed

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#40607]
Scons is generating random files:
- editor/st94wljB for example on my computer on linux.

It's not always reproducible but they sometimes make it into commits by error, can we please look into what they are and why they're not in a temp folder or something?

Ideally I'd like to know what exactly this file is doing.

**Godot version:**
branch feature_fbx_final_stage
4bb5e4f7545a793af15b6b5fdd4e329b366a9ebb

**OS/device including version:**
Linux 5.4.0-40-generic (ubuntu 20.10, nvidia computer)
**Issue description:**
I expect this file to not exist? or be ignored gracefully so it's not in my commits when I amend.

**Steps to reproduce:**
scons -j16? sometimes it makes this file under editor/ under a different hash.

**Minimal reproduction project:**
Will upload an example of this file someone might know how to identify what it is.

**Comment by RevoluPowered** [comment]
No idea what it is I compressed it.
[st94wljB.zip](https://github.com/godotengine/godot/files/4962210/st94wljB.zip)

**Comment by RevoluPowered** [comment]
ideally it has a file extension added to it so we can .gitignore them

**Comment by akien-mga** [comment]
I don't think they're generated by SCons, but by the compiler/linker. Try to `watch -n 0.5 git status` while building.
Every time a module is linked, such file appears to collate all object files into one and generate the `.a` file.

**Comment by Calinou** [comment]
I wonder if we could use this `.gitignore` pattern without any false positives: `st??????`

**Comment by akien-mga** [comment]
They're generated by binutils (`ar` or `ranlib`, didn't check which) following the `stXXXXXX` template: http://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=binutils/bucomm.c;h=9e6a02843e6c7ba11545f69a6a31e927d177a9b0;hb=HEAD#l482

Why they do it in-dir instead of in system tmp dir, I have no clue.



> I wonder if we could use this `.gitignore` pattern without any false positives: `st??????`

I was thinking about this, but I'd prefer to be more explicit to avoid excluding stuff like `stdn.cpp` which would match that pattern.

So maybe something like `st\w\w\w\w\w\w`, or `st\w{6}` if that's supported? Not sure what kind of regex lib is used for `.gitignore`.

**Comment by Calinou** [comment]
@akien-mga [`.gitignore` doesn't support regexes, but only some glob operations.](https://www.atlassian.com/git/tutorials/saving-changes/gitignore).

(PS: I removed my comment because I thought it was a bad idea in the end.)

**Comment by akien-mga** [comment]
Yeah I just tried it:
```
diff --git a/.gitignore b/.gitignore
index d9537edbf2..f4af79929c 100644
--- a/.gitignore
+++ b/.gitignore
@@ -34,6 +34,8 @@ platform/android/java/lib/.cxx/*
 *.os
 *.Plo
 *.lo
+# Binutils tmp linker output of the form "stXXXXXX" where "X" is alphanumeric
+st[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]
 
 # Libs generated files
 .deps/*
$ ll stX1*
-rw-r--r-- 1 akien akien 0 Jul 23 10:21 stX123d1
-rw-r--r-- 1 akien akien 0 Jul 23 10:21 stX1.cpp
[akien@cauldron godot.git (master)]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   .gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        stX1.cpp
```

I think it should be good enough.

**Comment by RevoluPowered** [comment]
Thanks for fixing this :) I appreciate it

**Comment by Calinou** [comment]
I'm surprised the fix was that simple, but I didn't bother searching for advanced `.gitignore` features until now. Sorry about that :stuck_out_tongue:
