### ISSUE TITLE
Vulkan: GridMap is not included in SDFGI baking

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot#40617]
**Godot version:**

4.0, master branch, Commit Hash: 0cd98ec7e13038d09a77cf821e930be79026f943

**OS/device including version:**

Windows 10 v. 2004, RTX 2060, NVidia GeForce Game-Ready Driver v. 451.67, Vulkan backend.

**Issue description:**
My Grid Map is not being shown in SDFGI, despite being set to be used for baked lighting. Mesh Instances are able to use SDFGI with the same settings, but if it's in a Grid Map, SDFGI doesn't work at all. The expected behavior would be the Grid Map producing the same sort of lighting as the Mesh Instances.
![image](https://user-images.githubusercontent.com/25652538/88245325-acaf3b00-cc4b-11ea-9b81-ff02565276b7.png)

**Steps to reproduce:**
Create a Grid Map and place objects with it, and then enable SDFGI. If you construct the same thing with Mesh Instances, you will notice that they affect the lighting, but the Grid map doesn't.

**Minimal reproduction project:**

[GridMapSDFGI.zip](https://github.com/godotengine/godot/files/4963489/GridMapSDFGI.zip)

**Comment by Zylann** [comment]
Does this mean all non-node-based mesh instances aren't included as well? (when using `VisualServer` only, that is) Or is it only a configuration issue?

**Comment by Syntaxxor** [comment]
> Does this mean all non-node-based mesh instances aren't included as well? (when using `VisualServer` only, that is) Or is it only a configuration issue?

@Zylann, I lack the knowledge of the Godot rendering pipeline to properly answer that question. However, I can confirm that SDFGI Baking does include MultiMeshInstance nodes and CSG nodes with or without a combiner.

**Comment by etodd** [comment]
This seems to be working for me. The lighting doesn't always update right away, but in general it works.

**Comment by Calinou** [comment]
I can confirm SDFGI works with GridMap cells on 4.0.stable. The glowing cubes are GridMap cells, they both receive and contribute to GI:

![image](https://user-images.githubusercontent.com/180032/227078915-21811ac7-9841-4193-8a81-c70e60f8007c.png)
