### ISSUE TITLE
Auto tile crashes the engine

### ISSUE THREAD

**Issue by D-Undefined** [godotengine/godot#40612]
I didn't find a duplicate

**Godot version:**

Godot V3.2.2 stable.official

**OS/device including version:**

Windows 

**Issue description:**

When i try to use auto tiler i'm not able to create a square on my tiles to start customizing. Instead it just doesn't respond, then crashes. I've tried it around 5 times also by creating a new scene for it.

p.s you guys are the best

**Steps to reproduce:**

- create tilemap node
- create new tileset
- save tileset 
- add the textures
- new auto tile
- *tries selecting the tiles multiple times*
- *Godot not responding*

**Minimal reproduction project:**

[TopDownShooter.zip](https://github.com/godotengine/godot/files/4962547/TopDownShooter.zip)
![Untitled](https://user-images.githubusercontent.com/56637726/88228153-04ab6900-cc6f-11ea-9a7e-52dbd1ad9d28.png)

**Comment by menip** [comment]
Running 3.2.2.stable on linux and following steps to reproduce (with linked project), does not result in a crash for me.

**Comment by D-Undefined** [comment]
Thanks @menip for your resonse! I think some files got corrupted and when starting the project over from scratch, it worked again.
Sorry for the trouble.
