### ISSUE TITLE
Camera Zoom causes viewport container to always be left aligned when inside a hbox container

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#40637]
**Godot version:**
3.2.2 stable

**OS/device including version:**
linux mint

**Issue description:**
Apologies if this is not a bug, but I couldn't find documentation to help. If I have a HBoxContainer set to Centre alignment and put in a viewport container/viewport/camera and set the camera to zoom to say 1.5, when I run the program the viewport container is always left aligned, I cannot find any means of make it centre in the screen.

If I use any other container type, then they are centred just fine.

**Steps to reproduce:**
1. create a hbox container, nested viewportcontainer, nested viewport. Put in a camera and some random objects
2. set the camera zoom to 2
3. run

**Minimal reproduction project:**

**Comment by groud** [comment]
This is an expected behavior. The center option in hboxcontainer is to center the content vertically. You should use a CenterContainer instead.

**Comment by chucklepie** [comment]
Well, that was simple. But why do all other containers all centre and what is the point of the 'alignment' property when it says 'the alignment of containers children'?

**Comment by groud** [comment]
No clue, it depends on your setup. That usually depends on the children computed minimum size. 
The minimum size computed with a ViewportContainer
