### ISSUE TITLE
Add a nice api to make 2D split screen easier.

### ISSUE THREAD

**Issue by lorenzobeccaro** [godotengine/godot#4064]
I found this card on [trello](https://trello.com/c/Bj3kaeQH/25-add-a-nice-api-to-make-2d-split-screen-easier) and not on github. I don't know how to workaround or solve this issue :(

**Comment by vnen** [comment]
The only workaround I can think of is to use viewports. Basically you would put one viewport for each player and repeat the game structure (via instancing) to render in each viewport. The most troublesome is the global state (things shared between players) and actual player interaction with one another. Not sure how to handle physics if you are repeating the objects for the players. If you can actually share the map, this can be handled simply with cameras, each one focused on a player and rendered in a specific viewport.

**Comment by lorenzobeccaro** [comment]
@vnen Actually it's not possible to render the same scene from two cameras to other two viewports. Juan told me that it's needed an hack in visual server to accomplish that but I don't know more.

**Comment by vnen** [comment]
> Actually it's not possible to render the same scene from two cameras to other two viewports.

I stand corrected. And then I think it might not be possible in the current engine state, unfortunately. But this must be in @reduz's plans, otherwise he wouldn't create the Trello card.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by lorenzobeccaro** [comment]
:cry:

**Comment by Zylann** [comment]
Curiously, it makes me thing of Reaper, an audio editing software, in which you can make a tree of tracks. 
Basically, tracks always send their output to their parent, and it's nice and easy to work with.
But sometimes it just don't works as you want, maybe you want to send the same output to multiple tracks, or bypass the parent.
For this reason, you can alternatively tell a track to send its output to others by unchecking "send to parent", without having to put it as child.

Back to Godot: think about the same design, but with audio AND rendering. This way you can maintain the same game world for X players, and be able to use as many cameras as you want.

**Comment by hubbyist** [comment]
4 perfect mirrors and an orthographic projection camera may do a trick may be. At least it would do in physics not sure about in a game engine.

**Comment by Hinsbart** [comment]
I guess this can be closed since it has been implemented by a4156f1.
