### ISSUE TITLE
Cannot create a HeightMap CollisionShape in Godot physics.

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#40664]
**Godot version:** 3.2.2 and master 93b50a62e3

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
Cannot create a HeightMap CollisionShape in Godot physics. Trying to creating a HeightMap generates error:
Godot 4.0:
```
E 0:00:02:0073   set_data: Condition "!d.has("cell_size")" is true.
  <C++ Source>   servers/physics_3d/shape_3d_sw.cpp:1491 @ set_data()
```
Godot 3.2:
```
E 0:00:00.204   set_data: Condition "!d.has("cell_size")" is true.
  <C++ Source>  servers/physics/shape_sw.cpp:1640 @ set_data()
```

**Steps to reproduce:**
Use Godot physics, and either create a `HeightMap` in script or select it as the `CollisionShape`.

**Minimal reproduction project:**
Godot 4.0:
[HeightMap-4.0.zip](https://github.com/godotengine/godot/files/4972744/HeightMap-4.0.zip)

Godot 3.2: 
[HeightMap-3.2.zip](https://github.com/godotengine/godot/files/4972745/HeightMap-3.2.zip)

**Comment by madmiraal** [comment]
Related to #32217.

**Comment by rburing** [comment]
The error no longer appears in Godot 3.5.1 or 4.0 RC 3.
