### ISSUE TITLE
Viewport Texture in a TextureRect is shown upside down

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#40662]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux Mint, GLES3
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
	Subsystem: Hewlett-Packard Company Haswell-ULT Integrated Graphics Controller
	Kernel driver in use: i915
	Kernel modules: i915

As screenshot, I have a TextureRect. The texture is set to be a ViewportTexture with the 'Viewport' selected as the target.

Viewport simply has a sprite.

As seen, everything is upside down. I have to set Flip V for it to work. Now, I don't know if this is just my driver, whether it will randomly happen to others if I distribute, if it's a bug, or a standard feature.

![image](https://user-images.githubusercontent.com/12863685/88402121-92e43400-cdc2-11ea-90dc-a591779e5428.png)

**Steps to reproduce:**
Here is the tscn file:

[gd_scene load_steps=3 format=2]

[ext_resource path="res://icon.png" type="Texture" id=1]

[sub_resource type="ViewportTexture" id=1]
viewport_path = NodePath("Viewport")

[node name="Node2D" type="Node2D"]

[node name="TextureRect" type="TextureRect" parent="."]
anchor_right = 1.0
anchor_bottom = 1.0
texture = SubResource( 1 )
__meta__ = {
"_edit_use_anchors_": false
}

[node name="Viewport" type="Viewport" parent="."]
size = Vector2( 960, 672 )

[node name="icon" type="Sprite" parent="Viewport"]
position = Vector2( 514.774, 328.098 )
scale = Vector2( 4.44715, 4.44715 )
texture = ExtResource( 1 )

**Comment by Calinou** [comment]
> As seen, everything is upside down. I have to set Flip V for it to work. Now, I don't know if this is just my driver, whether it will randomly happen to others if I distribute, if it's a bug, or a standard feature.

This is a known quirk in Godot 3.2, which has been solved in the `master` branch.

**Comment by chucklepie** [comment]
So this is consistent across every machine and won't be fixed until 4.0, or 3.3? Can you point me to the documentation that describes this please.

I guess I'd better make a note to remember to switch it back, but maybe waiting till 4.0 would be better ;)

**Comment by Calinou** [comment]
> So this is consistent across every machine and won't be fixed until 4.0, or 3.3?

Yes, with the exception of VirtualBox's 3D acceleration (which is a [bug](https://github.com/godotengine/godot/issues/40370)).
