### ISSUE TITLE
Godot fails to load on macOS / "Unable to initialize Video driver"

### ISSUE THREAD

**Issue by dymk** [godotengine/godot#40682]
**Godot version:** b7dc08fcf6117bc13b0b1210119e51b4c51f5086 (`~master`)

**OS/device including version:** 
- MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
- macOS 10.15.5 (19F101)
- MoltenVK from `brew install molten-vk`
- Intel Iris Plus Graphics 645 1536 MB graphics
- Metal: Supported, feature set macOS GPUFamily2 v1

**Issue description:**

Compiled Godot and ran with the following: 

```
$ scons platform=osx arch=x86_64 --jobs=(sysctl -n hw.logicalcpu)
$ cp -r misc/dist/osx_tools.app ./Godot.app
$ mkdir -p Godot.app/Contents/MacOS
$ cp bin/godot.osx.tools.x86_64 Godot.app/Contents/MacOS/Godot
$ chmod +x Godot.app/Contents/MacOS/Godot
$ open ./Godot.app
```

At that point, I was given the following error dialog: 
```
Unable to initialize Video driver
Your video card driver does not support any of the supported Metal versions.
```
<img width="433" alt="image" src="https://user-images.githubusercontent.com/1578600/88435805-db4a2480-cdb7-11ea-8347-8805293a6ad6.png">

**Steps to reproduce:**

(See above)

**Minimal reproduction project:**

(N/A)

Relevant PRs:
- https://github.com/godotengine/godot/pull/40354 (Adds the above error message)

**Comment by akien-mga** [comment]
I think you missed a step to bundle the Vulkan loader, see the end of this section: https://docs.godotengine.org/en/latest/development/compiling/compiling_for_osx.html#compiling

**Comment by bruvzg** [comment]
> MoltenVK from brew install molten-vk

homebrew `moten-vk` package seems to have wrong path (`./libMoltenVK.dylib`) in it's ICD config (`/usr/local/share/vulkan/icd.d/MoltenVK_icd.json`), it should be either absolute path or relative to the `.json` location.

Or just copy `.dylib` to the `Godot.app/Contents/Frameworks/`.

**Comment by dymk** [comment]
@akien-mga 

```
cp /usr/local/lib/libMoltenVK.dylib Godot.app/Contents/Frameworks/libMoltenVK.dylib
```

And it works! Thank you, I did miss that step. 

<img width="352" alt="image" src="https://user-images.githubusercontent.com/1578600/88437790-1a7a7480-cdbc-11ea-8b85-fdc3010c7b01.png">

@bruvzg I think you're right, modifying `MoltenVK_icd.json` to be the following:

```
{
    "file_format_version" : "1.0.0",
    "ICD": {
       // or "../../../lib/libMoltenVK.dylib",
        "library_path": "/usr/local/lib/libMoltenVK.dylib",
        "api_version" : "1.0.0"
    }
}
```

also fixes the fixes the issue and allows Godot to initialize.

**Comment by akien-mga** [comment]
It would be good to report the issue to homebrew maintainers so that they fix the package.

**Comment by supagu** [comment]
I am trying to run master branch. Following the instructions on the official documentation (https://docs.godotengine.org/en/latest/development/compiling/compiling_for_osx.html#compiling) I was able to get the editor running.

**I would like to set it up so I can easily run/debug the executable from the godot/bin directory but how do I do this?**

It seems when running from a .app somehow the executable knows to load Resources/vulkan/icd.d/MoltenVK_icd.json which then points it to the Frameworks/libMoltenVK.dylib.
