### ISSUE TITLE
CJK glyph flow in UI labels should not line break on whitespace

### ISSUE THREAD

**Issue by HybridEidolon** [godotengine/godot#40688]
**Godot version:**
3.2.2 Stable

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
When rendering east-Asian language text inside a label, the node is treating whitespace codepoints as a line break point, even though it may be inappropriate. The result is essentially showing one sentence per line, if spaces are used to separate sentences. A semi-correct behavior can be attained by _not_ placing whitespace between sentences.

![image](https://user-images.githubusercontent.com/141511/88446178-672a7380-cded-11ea-8f37-12ef4c3ac9b2.png)

(The text featured is translated with Google Translate; I apologize if it doesn't make any sense to Japanese readers)

[Wikipedia has an article on line-breaking for East-Asian Languages.](https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages) I believe this is a fairly important feature for supporting these locales as this also impacts presentation of labels in the Godot Editor, which would result in a subpar editor experience.

**Steps to reproduce:**
1. Create a Label node
2. Set its text to a combination of English and Japanese sentences.

**Minimal reproduction project:**
[CJKWordWrapIssue.zip](https://github.com/godotengine/godot/files/4974751/CJKWordWrapIssue.zip)

This zip contains `NotoSans-Regular.otf` and `NotoSansJP-Regular.ttf`, both of which are used and distributed under the terms of the SIL Open Font License.

**Comment by bruvzg** [comment]
As far as I know, breaking after arbitrary CJK glyph is not correct either, reliable detection of words in CJK, Thai and any other languages when using hyphenation will require use of dictionary. Also, many languages use alternative space marks.

See [UAX #29, Unicode Text Segmentation](https://unicode.org/reports/tr29/) and [UAX #14, Unicode Line Breaking Algorithm ](https://unicode.org/reports/tr14/) for more information.

As soon as [complex text layouts](https://github.com/godotengine/godot-proposals/issues/1180) are implemented, correct line / word breaking will be handled by use of [ICU BreakIterator](http://userguide.icu-project.org/boundaryanalysis).
