### ISSUE TITLE
CollisionPolygon2D deleting/undo/redo doesn't make effect until making new polygon/editing other

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#4068]
There is something wrong about making changes with 2D CollisionPolygons. When deleting / making some undo / redo it does changes visualy - it disapears / appears ( in scene tree, and the render itself when the debug is on ). There is also a change in the scene file, but there must be something buffered out there, because it still colides / doesn't collide until you make some new collider and you put at least one point into or edit some collider - that belongs to the same PhysicsBody2D object (!). Editing, adding new one for one PhysicsBody2D doesnt fix problem for other objects.

Godot 2.0.1, Windows 7

**Comment by reduz** [comment]
this will be rewritten/fixed in 3.0, needs to break compatibility to fix

**Comment by reduz** [comment]
already fixed in 3.0
