### ISSUE TITLE
get_tree().get_root().get_children() returns wrong scene when scene is changed

### ISSUE THREAD

**Issue by SecretPanda420** [godotengine/godot#40697]
**Godot version:**
3.2.2.stable

**Issue description:**
I was trying to make a simple game, and in the game I like to have a mechanic where I add my own type of player in code after I change a scene instead of pre-defining it in the scene already. This is because I wanted flexibility over the type of player I want to add because of my game mechanic. So I go about changing my scene to a `World` scene and then I would want to add the player node myself as a child to that world node. To do this I changed the scene using `get_tree().change_scene_to(World)` and just below this I add `get_tree().get_root().get_children()[0]`, now as the scene is changed, the only child of root should be `World` and I should be able to simply do `get_tree().get_root().get_children()[0].add_child(player_of_my_will)` but Godot returns the `Main` scene again when the only current node of root is the `World` scene at this point of time. This is confirmed because after I run and join my `World` scene, in the editor's `Remote` tab I see ROOT and the only child I see there is well `World` as it should be but if I access the same thing from code as I am, it returns `Main` again. This is either a problem with the remote tab or the `get_root().get_children()` method, based off my current understanding of Godot, it should replace the scene when calling `change_scene`/`change_scene_to` and the ROOT should have only one root node which should be the scene itself. I've tried to explain this in the most simple way as I can and have also attached the minimal reproduction project, I hope that helps it to understand what I am trying to say. I would also love to hear a workaround or a fix for this.

**Steps to reproduce:**
- Get the bug project.
- Run the program with its main scene as `Main.tscn`
- Click `Join World` and see output as `Main` resulted from `Main.gd:31` but the `Remote` tab shows only one child of `ROOT` which is `World`.
- The output should be `World` instead of `Main`.

**Minimal reproduction project:**
[thebugproject.zip](https://github.com/godotengine/godot/files/4975679/thebugproject.zip)

**Comment by Rubonnek** [comment]
This is not a bug -- you are running:

```gdscript
print(get_tree().get_root().get_children()[0].name)
```

in the same frame you ran `change_scene_to` at which point the scene hasn't changed yet. You have to wait until the next frame to query the name again, but running `yield(get_tree(), "idle_frame")` on that same function will not work because the object will be destroyed by then.

Here's the [custom scene switcher documentation](https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html?highlight=custom%20scene%20switcher#custom-scene-switcher).
