### ISSUE TITLE
C# Wrong Script attached in PackedScene when using Constructor to "build" Node in another Class

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#40699]
**Godot version:**

3.2.2 Mono

**OS/device including version:**

Linux 5.7.10-arch1-1
Mono JIT compiler version 6.10.0

**Issue description:**

When you build a Node in another Class, and than pack it as .tscn File, it attaches a wrong Script resource:
`script = SubResource( 1 )`

**Steps to reproduce:**
```
using Godot;
using System;

public class MainScene : Node
{
    public override void _Ready()
    {   
        Node node = new Node();
        Sun sun = new Sun();
        node.AddChild(sun);

        sun.Owner = node;
        
        PackedScene packedScene = new PackedScene();
        Error error = packedScene.Pack(node);
        GD.Print(error);
        error = ResourceSaver.Save("res://NewMainScene.tscn", packedScene);
        GD.Print(error);
    }
}
```

```
using Godot;
using System;

public class Sun : DirectionalLight
{
    public Sun()
    {
        ShadowEnabled = true;
        RotationDegrees = new Vector3(-45, 180, 0);
    }
}
```

**This then is the generated tscn File:**
```
[gd_scene load_steps=2 format=2]

[sub_resource type="CSharpScript" id=1]

[node name="" type="Node"]

[node name="@@2" type="DirectionalLight" parent="."]
transform = Transform( -1, 6.18172e-08, -6.18172e-08, 0, 0.707107, 0.707107, 8.74228e-08, 0.707107, -0.707107, 0, 0, 0 )
shadow_enabled = true
script = SubResource( 1 )
```
![Screenshot_20200725_172116](https://user-images.githubusercontent.com/60042618/88460290-64865780-ce9b-11ea-873e-be94f66e69ef.png)

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/4975780/Test.zip)

**Comment by akien-mga** [comment]
Related to #10189.

**Comment by raulsntos** [comment]
As I understand it, this issue seems to be the same as https://github.com/godotengine/godot/issues/48828 so I'll close it as duplicate since the other one has more information.
