### ISSUE TITLE
tileset painting z-index issues in editor

### ISSUE THREAD

**Issue by hyperglow** [godotengine/godot#4070]
Ubuntu Linux 64bit 

Tiles don't get painted in correct order in the editor. This happend the first time after I painted several tiles without problems. Maybe its the tilesize? The running game shows the correct tile z-depth... Check the screenshot.

**Steps to reproduce:**
![auswahl_008](https://cloud.githubusercontent.com/assets/8523290/13797361/49ea6afe-eb0d-11e5-8007-45ecd004c1b2.png)

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
:+1: I can reproduce, sometimes newly painted regions of the tilemap would cover existing graphics with a higher z-index and position in the tree.

**Comment by hyperglow** [comment]
I tried to recreate in a new scene and i got the same problem.
zip of the project is here:
[iso_test.zip](https://github.com/godotengine/godot/files/175952/iso_test.zip)

**Comment by bojidar-bg** [comment]
Looks like it's an issue with quadrants repainting :smile:

**Comment by bojidar-bg** [comment]
@hyperglow ~ Playing around with your demo, if you do
````
extends TileMap

func _ready():
	set_process_input(true)

func _input(event):
	if event.type == InputEvent.MOUSE_BUTTON:
		set_cell(30, 0, -1)
````
And click on the screen **in-game** the same issue occurs.

@akien-mga ~ -topic:editor +topic:core
