### ISSUE TITLE
Errors from SCons when compiling for iOS 

### ISSUE THREAD

**Issue by coolepicguy** [godotengine/godot#40716]
Godot version:

Standard

Xcode version:
11.5 (11E608c)
OS/device including version:
MacBook Pro 2016 12' running macOS Catalina 10.15.5

Issue description:
When compiling Godot Engine for iOS, several errors occur:
Build log:

Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> platform/iphone/godot_iphone.cpp
In file included from platform/iphone/godot_iphone.cpp:33:
platform/iphone/os_iphone.h:83:2: error: unknown type name 'VideoMode'
        VideoMode video_mode;
        ^
platform/iphone/os_iphone.h:91:33: error: unknown type name 'VideoMode'
        virtual Error initialize(const VideoMode &p_desired, int p_video_driver, int p_audio_driver);
                                       ^
platform/iphone/os_iphone.h:120:2: error: unknown type name 'InputDefault'
        InputDefault *input;
        ^
platform/iphone/os_iphone.h:147:48: error: use of undeclared identifier 'InputDefault'
        void joy_axis(int p_device, int p_axis, const InputDefault::JoyAxis &p_value);
                                                      ^
platform/iphone/os_iphone.h:164:36: error: unknown type name 'VideoMode'
        virtual void set_video_mode(const VideoMode &p_video_mode, int p_screen = 0);
                                          ^
platform/iphone/os_iphone.h:165:10: error: unknown type name 'VideoMode'
        virtual VideoMode get_video_mode(int p_screen = 0) const;
                ^
platform/iphone/os_iphone.h:166:45: error: use of undeclared identifier 'VideoMode'
        virtual void get_fullscreen_mode_list(List<VideoMode> *p_list, int p_screen = 0) const;
                                                   ^
7 errors generated.
scons: *** [platform/iphone/godot_iphone.iphone.debug.x86_64.o] Error 1
scons: building terminated because of errors.

Any help Is appreciated

**Comment by akien-mga** [comment]
> Godot version:

This would be the most important piece of information here :)

**Comment by coolepicguy** [comment]
> > Godot version:
> 
> This would be the most important piece of information here :)

I downloaded the latest version of source code from here https://github.com/godotengine/godot

**Comment by akien-mga** [comment]
That's the `master` branch, which did not support iOS until earlier today. Try again now as #40434 was merged.

**Comment by coolepicguy** [comment]
I really appreciate you taking your time because I am a complete newbie.

But if I understood it correct I can't add custom modules for iOS on the OpenGl version?

**Comment by akien-mga** [comment]
Yes, you can add custom modules for iOS on the current stable `3.2` version. You should refer to the documentation of the custom modules you're trying to build for instructions (or open an issue there if the instructions are unclear/incomplete).

**Comment by coolepicguy** [comment]
I have now compiled using scons p=iphone target=release and with https://github.com/kloder-games/godot-admob in the modules. 

I got this error:
modules/admob/register_types.cpp:7:10:{7:10-7:28}: fatal error: 'object_type_db.h' file not found [1]
 #include "object_type_db.h"
Any idea?

**Comment by akien-mga** [comment]
Please ask for support on https://github.com/kloder-games/godot-admob

`object_type_db.h` doesn't exist since Godot 3.0, so you're trying to compile a Godot 2.1 version of that module.
