### ISSUE TITLE
[iOS] MoltenVK shader compilation errors

### ISSUE THREAD

**Issue by naithar** [godotengine/godot#40728]
**Godot version:**

`master` branch

**OS/device including version:**

`Vulkan` backend on iPad and iPhone6

**Issue description:**

On launching any Godot's project on iOS devices using old (?) GPUs, some shaders do not compile on iOS.

In case of iPad (with A9X GPU) shaders failing to compile are the ones used in `rasterizer_effects_rd`. 
Some of them fail to compile giving `XPC_ERROR_CONNECTION_INTERRUPTED` and `Total number of indirect argument buffer resources exceeded for textures (33/31).` errors, but project still launches (at least in 2D).

In case of iPhone6 (A8 GPU) seems like all shaders fail to compile either giving black screen or freezing application and give `VK_ERROR_FEATURE_NOT_PRESENT: Device Apple A8 GPU does not support arrays of textures.` error.

iPhone XS and 8 compile shaders without a problem, but give some warnings.

iOS Simulator fails with `[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: Device Apple iOS simulator GPU does not support arrays of samplers.` and `[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: Device Apple iOS simulator GPU does not support arrays of textures.`

[Logs](https://gist.github.com/naithar/6a349dc4001c7f75a1a05ef3dd8ebf74)

**Steps to reproduce:**
Export Godot project with `Vulkan` support to iOS and run it.

**Comment by naithar** [comment]
Removing shaders usage from `rasterizer_effects_rd` allowed Godot project to run on iPhone 6 without getting stuck on shader compilation. Seems like some shader is too complex for iPhone 6 to process. As the result app was displaying a default color only.

<details>
<summary>
Rendered scene
</summary>
<img src="https://user-images.githubusercontent.com/3750083/88694269-f9da5380-d108-11ea-9135-e106f64b731c.jpg" height="250" />
</details>

Commenting arrays and their usage from `.glsl` allowed Godot to render the scene. At first glance scene is rendered the same way as it is on any other new device without this changes.

<details>
<summary>
Rendered scene
</summary>

<img src="https://user-images.githubusercontent.com/3750083/88694263-f777f980-d108-11ea-8eff-19e684fc0ed0.jpg" height="250" />

</details>

Adding a workaround for arrays to `canvas.glsl` has broken rendering to some extent, but project was still running. Changing the code that used arrays like `material_samplers[0]` to `material_samplers_0` didn't change result rendering.

<details>
<summary>
Arrays workaround in `rasterizer_canvas_rd.cpp`
</summary>

```
        global_defines += "\n#define SAMPLER_ARRAY_FOR_SHADER \\\n";

        for (int i = 0; i < 12; i++) {
            Dictionary values;
            values["index"] = i;

            global_defines += String("layout(set = 1, binding = $index) uniform sampler material_samplers_$index;\\\n").format(values, "$_");
        }

        global_defines += "\n#define LIGHT_ARRAY_FOR_SHADER \\\n";
        
        for (int i = 0; i < state.max_lights_per_item; i++) {
            int light_index = 5 + i;
            int shadow_index = 6 + state.max_lights_per_item + i;

            Dictionary values;
            values["index"] = i;
            values["light_index"] = light_index;
            values["shadow_index"] = shadow_index;

            global_defines += String("layout(set = 2, binding = $light_index) uniform texture2D light_textures_$index;\\\n"
                                     "layout(set = 2, binding = $shadow_index) uniform texture2D shadow_textures_$index;\\\n").format(values, "$_");
        }
```

</details>

<details>
<summary>
Rendered scene
</summary>

<img src="https://user-images.githubusercontent.com/3750083/88694456-3ad26800-d109-11ea-91e7-0e01139eb24d.jpg" height="250" />

</details>

**Comment by naithar** [comment]
> Adding a workaround for arrays to `canvas.glsl` has broken rendering to some extent, but project was still running. Changing the code that used arrays like `material_samplers[0]` to `material_samplers_0` didn't change result rendering.

This changes also completely breaks rendering for iPhoneXS build

**Comment by clayjohn** [comment]
I'm going to close this as the Vulkan renderers have changed dramatically in the last two years and many users are using Godot on iOS devices. If you are still experiencing issues with this device, please open an updated issue.
