### ISSUE TITLE
Can't build cross-platform

### ISSUE THREAD

**Issue by free-vbucks** [godotengine/godot#40738]
**Godot version:**
Tag 3.2.2-stable

**OS/device including version:**
Windows 10 1909 64 Bit

**Issue description:**
When trying to build Godot for Javascript, I got-
```
scons: Reading SConscript files ...
Invalid target platform "javascript".
The following platforms were detected:

        windows

Please run SCons again and select a valid platform: platform=<string>
```
It probably has something to do with SCons new update (v4.0.1 now).

**Steps to reproduce:**
Switch to 3.2.2-stable and run SCons for non-native platform on source code

**Comment by clayjohn** [comment]
Did you follow all the instructions here? https://docs.godotengine.org/en/stable/development/compiling/compiling_for_web.html

**Comment by free-vbucks** [comment]
Yes. And I tried to build for platforms like Linux too, just to see if it would get me to a different result, but the output was almost exactly the same.

**Comment by akien-mga** [comment]
Do you have `emcc` in your `PATH`? If not, your emscripten setup is not valid and Godot can't use it, so the error is expected.

For Linux, there's no crosscompilation toolchain on Windows, you have to use Linux or WSL.

**Comment by free-vbucks** [comment]
I have emcc in my path, but SCons doesn't even get far enough to check for that. It just doesn't recognize there are platforms other than Windows. It might be a broken SCons file, but I think the build system update is the reason.

**Comment by akien-mga** [comment]
> It just doesn't recognize there are platforms other than Windows.

It only lists the platforms that is *has found* as being valid. If it didn't find a valid Emscripten setup, it won't list the `javascript` platform as building for it wouldn't work.

See `can_build()` in `platform/javascript/detect.py`. You need to have `EM_CONFIG` is your environment pointing to your emscripten config file. I think `emsdk_env.bat` which Emscripten documentation asks you to run for initialization should set it up properly on Windows. https://emscripten.org/docs/getting_started/downloads.html#installation-instructions
