### ISSUE TITLE
Better Collada Exporter - export only deform bones

### ISSUE THREAD

**Issue by Lamoot** [godotengine/godot#4074]
Hello,

Testing the Better Collada Exporter for Blender, I notice all of the bones in a rig get exported to Godot. A desired way would be to only export those bones that directly influence the mesh (i.e. deform bones). In Blender, bones can be flagged as being 'deform' bones and e.g. the FBX exporter has an option to only export those. It would be nice and very much needed for Better Collada to support this.

A rig is usually made from many bones. There are deform bones which directly deform the mesh, then there are control bones that are used to animate, and also helper bones. Together they make a rig comfortable to use and animate. However, for games, you only need the deform bones, the rest can and should be discarded.

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/collada-exporter/issues/14.
