### ISSUE TITLE
Keyboard shortcuts don't work in the editor

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#40745]
**Godot version:**
Master 6de86946eab625a173a0e425d8f53a9cfe9e44ae

**OS/device including version:**
Windows 10

**Issue description:**
No keyboard shortcut seems to work in the editor: save scene, open scene, play, duplicate node, undo, redo, etc.

**Steps to reproduce:**
Open any project and try one of the shortcuts mentioned above.

**Minimal reproduction project:**
Can be reproduced in any project.

**Comment by qarmin** [comment]
Probably caused by #40670 like #40734

**Comment by pouleyKetchoupp** [comment]
CC @vnen
