### ISSUE TITLE
Cannot debug binary of godot(from scratch version)

### ISSUE THREAD

**Issue by gabimunt** [godotengine/godot#40742]
Edit: template fill

**Godot version:**
Tried both master branch and 3.2 branch.

**OS/device including version:**
Windows 10

**Issue description:**
Cannot debug. Whenever I attach the debugger at launch it throws this exception:
> Exception has occurred: W32/0xc0000008
> Unhandled exception at 0x00007FFC430EEC9A (ntdll.dll) in godot.windows.tools.64.exe: 0xC0000008: An invalid handle was specified.

This is what the devenv configuration and the exception's call stack look like in a screenshot: [ss](https://i.imgur.com/1gU42re.png).

**Steps to reproduce:**
Clone, add the .vscode folder, run debug.

**Minimal reproduction project:**
[vscode.zip](https://github.com/godotengine/godot/files/4983477/vscode.zip)
Drop in project root for vscode to pick it up. (name it a .vscode folder)

Thanks in advance.

**Comment by Calinou** [comment]
cc @bruvzg, as they implemented WinTab API support.

**Comment by akien-mga** [comment]
Please fill the issue template which was present when you created the issue.

**Comment by bruvzg** [comment]
Is it crashing when started normally or only when attaching VS debugger?

This error does not make much sense, `LoadLibraryW` should load library or return NULL.
Probably you have broken WinTab driver library installed (or it has invalid debug symbols, which debugger fails to load).

**Comment by gabimunt** [comment]
> 
> 
> Is it crashing when started normally or only when attaching VS debugger?
> 
> This error does not make much sense, `LoadLibraryW` should load library or return NULL.
> Probably you have broken WinTab driver library installed (or it has invalid debug symbols, which debugger fails to load).

Only with debugger.

I did install a driver for my tablet.

**Comment by gabimunt** [comment]
Perhaps a broken wintab32.dll. And a small update: works if hit continue through the debugging. No need to be that alarmed.

**Comment by gabimunt** [comment]
Update: I hit continue, it doesn't crash Godot but it won't hit any breakpoints so I'm guessing the gdb hook didn't work.
