### ISSUE TITLE
Android app crashes when encrypted

### ISSUE THREAD

**Issue by dbrova15** [godotengine/godot#40752]
**Godot version:**

3.2.2.stable
**OS/device including version:**

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-42-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7,7 ГиБ

GLES3

**Issue description:**

I am making an application for android.
I decided to encrypt the scripts as stated in the documentation at https://docs.godotengine.org/ru/latest/development/compiling/compiling_with_script_encryption_key.html
Compilation takes place without problems, but after installing the application on the device after launching the application, it closes without error.
The adb logcat -s godot command outputs:

> 07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: Condition "err" is true. Returned: err
07-27 13:10:16.388 17004 17043 E godot   :    At: modules/gdscript/gdscript.cpp:772:load_byte_code() - Condition "err" is true. Returned: err
07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: Cannot load byte code from file 'res://Scripts/constants.gde'.
07-27 13:10:16.388 17004 17043 E godot   :    At: modules/gdscript/gdscript.cpp:2281:load() - Condition "err != OK" is true. Returned: RES()
07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: Failed loading resource: res://Scripts/constants.gde.
07-27 13:10:16.388 17004 17043 E godot   :    At: core/io/resource_loader.cpp:278:_load() - Condition "found" is true. Returned: RES()
07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: Can't autoload: res://Scripts/constants.gd
07-27 13:10:16.388 17004 17043 E godot   :    At: main/main.cpp:1749:start() - Condition "res.is_null()" is true. Continuing.
07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: The MD5 sum of the decrypted file does not match the expected value. It could be that the file is corrupt, or that the provided decryption key is invalid.
07-27 13:10:16.388 17004 17043 E godot   :    At: core/io/file_access_encrypted.cpp:97:open_and_parse() - Condition "String::md5(hash) != String::md5(md5d)" is true. Returned: ERR_FILE_CORRUPT
07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: Condition "err" is true. Returned: err
07-27 13:10:16.388 17004 17043 E godot   :    At: modules/gdscript/gdscript.cpp:772:load_byte_code() - Condition "err" is true. Returned: err
07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: Cannot load byte code from file 'res://Plugins/Firebase.gde'.
07-27 13:10:16.388 17004 17043 E godot   :    At: modules/gdscript/gdscript.cpp:2281:load() - Condition "err != OK" is true. Returned: RES()
07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: Failed loading resource: res://Plugins/Firebase.gde.
07-27 13:10:16.388 17004 17043 E godot   :    At: core/io/resource_loader.cpp:278:_load() - Condition "found" is true. Returned: RES()
07-27 13:10:16.388 17004 17043 E godot   : **ERROR**: Can't autoload: res://Plugins/Firebase.gd
07-27 13:10:16.388 17004 17043 E godot   :    At: main/main.cpp:1749:start() - Condition "res.is_null()" is true. Continuing.

Everything works without encryption.

**Comment by volzhs** [comment]
did you set the encryption key at export setting?

![image](https://user-images.githubusercontent.com/8281454/88539084-86bed780-d04b-11ea-9887-d4b158fccd8c.png)

**Comment by dbrova15** [comment]
@volzhs 
![изображение](https://user-images.githubusercontent.com/20703983/88543137-32eac900-d020-11ea-8efa-5358f27125a9.png)
![изображение](https://user-images.githubusercontent.com/20703983/88544273-cec90480-d021-11ea-8a49-657d7d86d2cd.png)

> 07-27 15:56:28.435 21157 21193 E godot   : **ERROR**: The MD5 sum of the decrypted file does not match the expected value. It could be that the file is corrupt, or that the provided decryption key is invalid.
07-27 15:56:28.436 21157 21193 E godot   :    At: core/io/file_access_encrypted.cpp:97:open_and_parse() - Condition "String::md5(hash) != String::md5(md5d)" is true. Returned: ERR_FILE_CORRUPT
07-27 15:56:28.436 21157 21193 E godot   : **ERROR**: Condition "err" is true. Returned: err
07-27 15:56:28.436 21157 21193 E godot   :    At: modules/gdscript/gdscript.cpp:772:load_byte_code() - Condition "err" is true. Returned: err
07-27 15:56:28.436 21157 21193 E godot   : **ERROR**: Cannot load byte code from file 'res://Scripts/check_connect.gde'.
07-27 15:56:28.436 21157 21193 E godot   :    At: modules/gdscript/gdscript.cpp:2281:load() - Condition "err != OK" is true. Returned: RES()
07-27 15:56:28.436 21157 21193 E godot   : **ERROR**: Failed loading resource: res://Scripts/check_connect.gde.
07-27 15:56:28.436 21157 21193 E godot   :    At: core/io/resource_loader.cpp:278:_load() - Condition "found" is true. Returned: RES()
07-27 15:56:28.436 21157 21193 E godot   : **ERROR**: res://MainScene.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Scripts/check_connect.gd
07-27 15:56:28.436 21157 21193 E godot   :    At: scene/resources/resource_format_text.cpp:440:poll() - res://MainScene.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Scripts/check_connect.gd
07-27 15:56:28.436 21157 21193 E godot   : **ERROR**: Failed to load resource 'res://MainScene.tscn'.
07-27 15:56:28.436 21157 21193 E godot   :    At: core/io/resource_loader.cpp:208:load() - Condition "err != OK" is true. Returned: RES()
07-27 15:56:28.436 21157 21193 E godot   : **ERROR**: Failed loading resource: res://MainScene.tscn.
07-27 15:56:28.436 21157 21193 E godot   :    At: core/io/resource_loader.cpp:278:_load() - Condition "found" is true. Returned: RES()
07-27 15:56:28.436 21157 21193 E godot   : **ERROR**: Failed loading scene: res://MainScene.tscn
07-27 15:56:28.436 21157 21193 E godot   :    At: main/main.cpp:1936:start() - Condition "!scene" is true. Returned: false

**Comment by Xrayez** [comment]
Make sure to compile both editor and export templates (`tools=no`), with the same key.

**Comment by bruvzg** [comment]
Probably something went wrong with the export templates compilation, check if your encryption key is set in the `core\script_encryption_key.gen.cpp` file (it should be generated from the `SCRIPT_AES256_ENCRYPTION_KEY` variable during compilation), and you have compiled both `debug`, `release_debug` libraries for all required architectures and `apk` (see https://docs.godotengine.org/en/stable/development/compiling/compiling_for_android.html for full Android build instruction).

**Comment by volzhs** [comment]
I've been using encrypted script feature for android also.
complied editor without `SCRIPT_AES256_ENCRYPTION_KEY` and compiled android templates with `SCRIPT_AES256_ENCRYPTION_KEY`
it works for me.
I think something went wrong with templates as @bruvzg said.

**Comment by Pawel82S** [comment]
I have the same issue with newest Godot 3.2.3 version when exporting to LinuxX11. I even created empty project with one scene and attached default script template. I haven't changed any options beside export script to Encrypted and provided valid key. Project was exported without any issue. When exporting with option for script: text or compiled everything working properly after export but encrypted script option throw error when I try to run it:
```
./ExportBug.x86_64 
Godot Engine v3.2.3.stable.official - https://godotengine.org
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
OpenGL ES 3.0 Renderer: Mesa Intel(R) HD Graphics 530 (SKL GT2)
 
ERROR: open_and_parse: The MD5 sum of the decrypted file does not match the expected value. It could be that the file is corrupt, or that the provided decryption key is invalid.
   At: core/io/file_access_encrypted.cpp:97.
ERROR: load_byte_code: Condition "err" is true. Returned: err
   At: modules/gdscript/gdscript.cpp:772.
ERROR: load: Cannot load byte code from file 'res://Node.gde'.
   At: modules/gdscript/gdscript.cpp:2282.
ERROR: _load: Failed loading resource: res://Node.gde. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:279.
ERROR: poll: res://Node.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Node.gd
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Failed to load resource 'res://Node.tscn'.
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://Node.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:279.
ERROR: start: Failed loading scene: res://Node.tscn
   At: main/main.cpp:1944.
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2135.
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477.
```
[Export encrypted bug.zip](https://github.com/godotengine/godot/files/5244889/Export.encrypted.bug.zip)

I use Manjaro Linux.
```
uname -a
Linux 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64 GNU/Linux
```

**Comment by akien-mga** [comment]
Did you compile your own export template with the encryption key? https://docs.godotengine.org/en/stable/development/compiling/compiling_with_script_encryption_key.html

**Comment by akien-mga** [comment]
I'm fairly sure that OP omitted to compile the export templates, so the error is expected.
@Pawel82S opened #42162 and indeed this was the same problem.
Closing.
