### ISSUE TITLE
VK shader error - "ERROR: uniforms supplied for set" (broken screen-space reflections)

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#40779]
**Godot version:**
master 4e825539e590c6ce06e54fbb05571efce7fb181c

**OS/device including version:**
```
 sudo lshw -C video
  *-display                 
       description: VGA compatible controller
       product: Picasso
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:04:00.0
       version: c1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi msix vga_controller bus_master cap_list
       configuration: driver=amdgpu latency=0
       resources: irq:6 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:fe400000-fe47ffff
```
fedora linux kernel: 5.7.10-201-fc32.x86_64

**Issue description:**
Error in console when using a water shader (will provide a snippet tomorrow in code form)
```
   at: compute_list_dispatch (drivers/vulkan/rendering_device_vulkan.cpp:6612)
ERROR: Uniforms supplied for set (3):
Set: 1 Binding: 0 Type: CombinedSampler Length: 1
Set: 1 Binding: 1 Type: CombinedSampler Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 0 Type: Image Length: 1
Set: 0 Binding: 1 Type: Image Length: 1
Set: 1 Binding: 0 Type: Image Length: 1
Set: 1 Binding: 1 Type: Image Length: 1
Set: 2 Binding: 0 Type: Image Length: 1
Set: 3 Binding: 0 Type: CombinedSampler Length: 1
```

**Steps to reproduce:**
1. Make godot shader and assign it to an object
2. open scene with shader
3. spam of error

**Minimal reproduction project:**
TODO: will supply this tomorrow. (need permission from author first to share code and demo asset)

@QbieShay do you mind if you could make a cut down reproduction of this shader so we can see if it can be fixed?

**Comment by rkfg** [comment]
This breaks SS reflections, too. Enable them in [this project](https://github.com/Calinou/godot-reflection) and the result is this:
![2020-08-17_13-06-23](https://user-images.githubusercontent.com/184066/90384608-7fa74a00-e08a-11ea-8e24-6c5c88b8b25a.jpg)
Without SSR:
![2020-08-17_13-06-27](https://user-images.githubusercontent.com/184066/90384623-8635c180-e08a-11ea-81d8-ff3a11184179.jpg)

**Comment by quadraxas** [comment]
Even a simple empty project is broken when enabling SS Reflections:
Broken on 9b1c9cef17ef06e5ae80309189464ca6afe7e551
ss reflections turned off:
![image](https://user-images.githubusercontent.com/513247/94999948-9c112e80-05c5-11eb-8ea6-c7a8077f1eaa.png)

ss reflections turned on:
![image](https://user-images.githubusercontent.com/513247/94999962-afbc9500-05c5-11eb-861a-f0de556d1fe1.png)

resizing scene while ss reflections are enabled breaks it even further (ie, opening closing the output window below, or resizing window)
![image](https://user-images.githubusercontent.com/513247/94999973-c531bf00-05c5-11eb-96f7-e82e6f201bd8.png)

**Comment by Xartorx** [comment]
**Godot version:**
[7fc9d4c](https://github.com/godotengine/godot/commit/7fc9d4c79b3b790ff75c32317c25410f58ed1f68)


**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan


**Issue description:**
Enabling SS Reflections in Environment causes artifacts in editor viewport.
Also these errors are getting spammed in console:
<details>
<summary>Error:</summary>

>ERROR: Attempted to use an unused shader variant (shader is null),
   at: (./servers/rendering/renderer_rd/pipeline_cache_rd.h:70)
ERROR: Condition "!pipeline" is true.
   at: draw_list_bind_render_pipeline (drivers\vulkan\rendering_device_vulkan.cpp:6112)
ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6305)
ERROR: Attempted to use an unused shader variant (shader is null),
   at: (./servers/rendering/renderer_rd/pipeline_cache_rd.h:70)
ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6305)
ERROR: Source and Destination textures must be the same format.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:2805)
ERROR: Uniforms supplied for set (3):
Set: 1 Binding: 0 Type: CombinedSampler Length: 1
Set: 1 Binding: 1 Type: CombinedSampler Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 0 Type: Image Length: 1
Set: 0 Binding: 1 Type: Image Length: 1
Set: 1 Binding: 0 Type: Image Length: 1
Set: 1 Binding: 1 Type: Image Length: 1
Set: 2 Binding: 0 Type: Image Length: 1
Set: 3 Binding: 0 Type: CombinedSampler Length: 1
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6755)

</details>


[Video](https://drive.google.com/file/d/14kbgkizFya4MQn9ebmCd_41fQK1eemLv/view?usp=sharing)


**Minimal reproduction project:**
[SSRTest.zip](https://github.com/godotengine/godot/files/5832653/SSRTest.zip)

**Comment by volzhs** [comment]
attached video @Xartorx provided directly on comment.

https://user-images.githubusercontent.com/8281454/104973380-e4027700-5a37-11eb-839c-d2baf9284374.mp4

**Comment by josefkaragoli** [comment]
The bug is still present on 46de553

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/50151, which tracks the current issue with SSR in Vulkan.
