### ISSUE TITLE
Steam sees that Godot is in use only in Projects List

### ISSUE THREAD

**Issue by KappyMan** [godotengine/godot#40789]
**Godot version:** Godot Engine v3.2.2.stable.official

**OS/device including version:** Windows 10 Home Version 1909 

**Issue description:** Godot not appearing as running on Steam when leaving the Projects List, expected to be visible while in editor

**Steps to reproduce:** Install Godot from Steam, run it either in Steam or on Desktop Icon, select any project to Edit it, Godot is not showing that it is in use on Steam

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/18233.
