### ISSUE TITLE
CSGCombiner lighting breaks every other time visibility is toggled 

### ISSUE THREAD

**Issue by FrankAlbella** [godotengine/godot#40782]
**Godot version:**

3.2.2

**OS/device including version:**

Pop!_OS 20.04, GTX 1080, proprietary driver 440.100

**Issue description:**

CSGCombiners lose lightbaking from lightmaps every other time their visibility is toggled. 

**Steps to reproduce:**
1. Have a scene with a CSGCombiner node
2. Add child CSG meshes to that combiner 
3. Set up a BakedLightmap node
4. Bake the lighting
5. Run the scene
6. Set the `visible` property to false or use the `hide()` function on a CSGCombiner node
7. Set the `visible` property to true or use the `show()` function on a CSGCombiner node 
8. The CSGCombiner node now has broken lighting
9. Toggling the the visibility of it again will fix the lighting. 
10. This can be repeated infinitely. 

**Minimal reproduction project:**

[csg lighting.zip](https://github.com/godotengine/godot/files/4985898/csg.lighting.zip)

**Comment by hoontee** [comment]
The CSG shape actually recalculates every time it becomes visible. You can mitigate this issue by converting the shape into a `MeshInstance` and baking lightmaps again:
```GDScript
if child is CSGShape:
	var mesh_instance = MeshInstance.new()
	mesh_instance.mesh = child.get_meshes()[1]
	mesh_instance.material_override = child.material_override
	for child2 in child.get_children():
		if not child2 is CSGShape:
			child.remove_child(child2)
			mesh_instance.add_child(child2)
	if parent.get("interpolator_spatial"):
		parent.set("interpolator_spatial", mesh_instance)
	if parent.get("mesh"):
		parent.set("mesh", mesh_instance)
	mesh_instance.transform = child.transform
	parent.add_child(mesh_instance)
	child.queue_free()
```
