### ISSUE TITLE
func _input(event): dose not detect any inputs in v4.0.dev.custom_build.09a2b77b2

### ISSUE THREAD

**Issue by Prisalized** [godotengine/godot#40790]
**Godot version:**
 v4.0.dev.custom_build.09a2b77b2

**OS/device including version:**
windows and linux

**Issue description:**
if i try to use an input event under func _input(event): nothing will happen when i press the key

**Steps to reproduce:**
make a project add a script to a node then add func _input(event):  and add a input event then make it print something then after that play it. when you hit that key nothing will happen 

**Minimal reproduction project:**

[godot 4.0 input bug.zip](https://github.com/godotengine/godot/files/4988663/godot.4.0.input.bug.zip)

**Comment by qarmin** [comment]
This is fixed by #40770
