### ISSUE TITLE
Can't compile godot on Raspberry pi

### ISSUE THREAD

**Issue by dh928** [godotengine/godot#40799]
Raspberry pi 3 B+ Raspbian

**Issue description:**
pi@raspberrypi:~/godot $ scons -j8 platform=x11
scons: Reading SConscript files ...
Platform "x11" has been renamed to "linuxbsd" in Godot 4.0. Building for platform "linuxbsd".
Enabling ALSA
Enabling PulseAudio
Detected GCC 8 version < 8.4, which is not supported due to a regression in its C++17 guaranteed copy elision support. Use a newer GCC version, or Clang 6 or later by passing "use_llvm=yes" to the SCons command line.

This is my error. I have gcc 10.1.0 installed in opt/gcc-10.1.0. Why does it not recognize it? How can i change the gcc version? WHat does it mean by "passing "use_llvm=yes" to the SCons command line."? I typed in "use_llvm=yes" to the terminal, and I still have the same problem. WHat should i do?

**Comment by dh928** [comment]
[Initial build] Compiling ==> main/main.cpp
platform/linuxbsd/display_server_x11.cpp:659:2: warning: #warning Need to get from proper window [-Wcpp]
  659 | #warning Need to get from proper window
      |  ^~~~~~~
platform/linuxbsd/display_server_x11.cpp:740:2: warning: #warning This is an incorrect implementation, if windows overlap, it should return the topmost visible one or none if occluded by a foreign window [-Wcpp]
  740 | #warning This is an incorrect implementation, if windows overlap, it should return the topmost visible one or none if occluded by a foreign window
      |  ^~~~~~~
platform/linuxbsd/display_server_x11.cpp:3576:2: warning: #warning Forcing vulkan rendering driver because OpenGL not implemented yet [-Wcpp]
 3576 | #warning Forcing vulkan rendering driver because OpenGL not implemented yet
      |  ^~~~~~~
[Initial build] Compiling ==> main/main_timer_sync.cpp
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
scons: *** [platform/linuxbsd/display_server_x11.linuxbsd.tools.32.o] Error 1
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
scons: *** [platform/linuxbsd/os_linuxbsd.linuxbsd.tools.32.o] Error 1
^[^[^[^C^Cscons: *** [platform/linuxbsd/vulkan_context_x11.linuxbsd.tools.32.o] Build interrupted.
scons: *** [platform/linuxbsd/joypad_linux.linuxbsd.tools.32.o] Build interrupted.
scons: *** [main/main_timer_sync.linuxbsd.tools.32.o] Build interrupted.
scons: *** [platform/linuxbsd/godot_linuxbsd.linuxbsd.tools.32.o] Build interrupted.
scons: *** [platform/linuxbsd/crash_handler_linuxbsd.linuxbsd.tools.32.o] Build interrupted.
scons: *** [main/main.linuxbsd.tools.32.o] Build interrupted.
scons: Build interrupted.
scons: building terminated because of errors.
scons: writing .sconsign file.


Now I have an new error following https://raspberrypi.stackexchange.com/questions/93597/problem-with-gcc-g-versions

**Comment by bruvzg** [comment]
> How can i change the gcc version? 

Set `CC` `CXX` `AR` `RANLIB` and `LINK` variables, like:
```
scons p=linuxbsd CC=gcc-10 CXX=g++-10 AR=gcc-ar-10 RANLIB=gcc-ranlib-10 LINK=g++-10
```

> Raspberry pi 3 B+ Raspbian
> g++: fatal error: Killed signal terminated program cc1plus compilation terminated.

Are you trying to build it on Raspberry Pi itself? It's probably just running out of memory, try replacing `-j8` with `-j1`, or cross-build it on the desktop.

**Comment by dh928** [comment]
> > How can i change the gcc version?
> 
> Set `CC` `CXX` `AR` `RANLIB` and `LINK` variables, like:
> 
> ```
> scons p=linuxbsd CC=gcc-10 CXX=g++-10 AR=gcc-ar-10 RANLIB=gcc-ranlib-10 LINK=g++-10
> ```
> 
> > Raspberry pi 3 B+ Raspbian
> > g++: fatal error: Killed signal terminated program cc1plus compilation terminated.
> 
> Are you trying to build it on Raspberry Pi itself? It's probably just running out of memory, try replacing `-j8` with `-j1`, or cross-build it on the desktop.

Thank you so so so much! What does is do when you replace the -j8 by -j1?

**Comment by bruvzg** [comment]
> What does is do when you replace the -j8 by -j1?

`j` is a number of threads, usually it's set to the number of CPU cores, but you need about gig of RAM per thread.

**Comment by dh928** [comment]
> > What does is do when you replace the -j8 by -j1?
> 
> `j` is a number of threads, usually it's set to the number of CPU cores, but you need about gig of RAM per thread.

Thank you! So I tried but I got this error
~/godot $ scons p=linuxbsd CC=gcc-10 CXX=g++-10 AR=gcc-ar-10 RANLIB=gcc-ranlib-10 LINK=g++-10
scons: Reading SConscript files ...
Invalid target platform "linuxbsd".
The following platforms were detected:

	server
	x11

Please run SCons again and select a valid platform: platform=<string>
-----------------------------------------------------------------------------------------------
I also get another error like this:
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:10885:1: error: inlining failed in call to 'always_inline' 'vst1_u8': target specific option mismatch
10885 | vst1_u8 (uint8_t * __a, uint8x8_t __b)
      | ^~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:104:9: note: called from here
  104 |         vst1_u8((uint8_t *)dst_ptr, d3u8); dst_ptr += dst_pitch;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:10885:1: error: inlining failed in call to 'always_inline' 'vst1_u8': target specific option mismatch
10885 | vst1_u8 (uint8_t * __a, uint8x8_t __b)
      | ^~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:103:9: note: called from here
  103 |         vst1_u8((uint8_t *)dst_ptr, d2u8); dst_ptr += dst_pitch;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:4688:1: error: inlining failed in call to 'always_inline' 'vqrshrn_n_u16': target specific option mismatch
 4688 | vqrshrn_n_u16 (uint16x8_t __a, const int __b)
      | ^~~~~~~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:101:16: note: called from here
  101 |         d5u8 = vqrshrn_n_u16(q4u16, 7);
      |                ^~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:4688:1: error: inlining failed in call to 'always_inline' 'vqrshrn_n_u16': target specific option mismatch
 4688 | vqrshrn_n_u16 (uint16x8_t __a, const int __b)
      | ^~~~~~~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:100:16: note: called from here
  100 |         d4u8 = vqrshrn_n_u16(q3u16, 7);
      |                ^~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:4688:1: error: inlining failed in call to 'always_inline' 'vqrshrn_n_u16': target specific option mismatch
 4688 | vqrshrn_n_u16 (uint16x8_t __a, const int __b)
      | ^~~~~~~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:99:16: note: called from here
   99 |         d3u8 = vqrshrn_n_u16(q2u16, 7);
      |                ^~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:4688:1: error: inlining failed in call to 'always_inline' 'vqrshrn_n_u16': target specific option mismatch
 4688 | vqrshrn_n_u16 (uint16x8_t __a, const int __b)
      | ^~~~~~~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:98:16: note: called from here
   98 |         d2u8 = vqrshrn_n_u16(q1u16, 7);
      |                ^~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:1530:1: error: inlining failed in call to 'always_inline' 'vmlal_u8': target specific option mismatch
 1530 | vmlal_u8 (uint16x8_t __a, uint8x8_t __b, uint8x8_t __c)
      | ^~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:96:17: note: called from here
   96 |         q4u16 = vmlal_u8(q4u16, d26u8, d1u8);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:1530:1: error: inlining failed in call to 'always_inline' 'vmlal_u8': target specific option mismatch
 1530 | vmlal_u8 (uint16x8_t __a, uint8x8_t __b, uint8x8_t __c)
      | ^~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:95:17: note: called from here
   95 |         q3u16 = vmlal_u8(q3u16, d25u8, d1u8);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:1530:1: error: inlining failed in call to 'always_inline' 'vmlal_u8': target specific option mismatch
 1530 | vmlal_u8 (uint16x8_t __a, uint8x8_t __b, uint8x8_t __c)
      | ^~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:94:17: note: called from here
   94 |         q2u16 = vmlal_u8(q2u16, d24u8, d1u8);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:1530:1: error: inlining failed in call to 'always_inline' 'vmlal_u8': target specific option mismatch
 1530 | vmlal_u8 (uint16x8_t __a, uint8x8_t __b, uint8x8_t __c)
      | ^~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:93:17: note: called from here
   93 |         q1u16 = vmlal_u8(q1u16, d23u8, d1u8);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:1369:1: error: inlining failed in call to 'always_inline' 'vmull_u8': target specific option mismatch
 1369 | vmull_u8 (uint8x8_t __a, uint8x8_t __b)
      | ^~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:91:17: note: called from here
   91 |         q4u16 = vmull_u8(d25u8, d0u8);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:1369:1: error: inlining failed in call to 'always_inline' 'vmull_u8': target specific option mismatch
 1369 | vmull_u8 (uint8x8_t __a, uint8x8_t __b)
      | ^~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:90:17: note: called from here
   90 |         q3u16 = vmull_u8(d24u8, d0u8);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:1369:1: error: inlining failed in call to 'always_inline' 'vmull_u8': target specific option mismatch
 1369 | vmull_u8 (uint8x8_t __a, uint8x8_t __b)
      | ^~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:89:17: note: called from here
   89 |         q2u16 = vmull_u8(d23u8, d0u8);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:1369:1: error: inlining failed in call to 'always_inline' 'vmull_u8': target specific option mismatch
 1369 | vmull_u8 (uint8x8_t __a, uint8x8_t __b)
      | ^~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:88:17: note: called from here
   88 |         q1u16 = vmull_u8(d22u8, d0u8);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:6654:1: error: inlining failed in call to 'always_inline' 'vdup_n_u8': target specific option mismatch
 6654 | vdup_n_u8 (uint8_t __a)
      | ^~~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:86:16: note: called from here
   86 |         d1u8 = vdup_n_u8(bifilter4_coeff[yoffset][1]);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:11:
/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include/arm_neon.h:6654:1: error: inlining failed in call to 'always_inline' 'vdup_n_u8': target specific option mismatch
 6654 | vdup_n_u8 (uint8_t __a)
      | ^~~~~~~~~
thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c:85:16: note: called from here
   85 |         d0u8 = vdup_n_u8(bifilter4_coeff[yoffset][0]);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scons: *** [thirdparty/libvpx/vp8/common/arm/neon/bilinearpredict_neon.x11.tools.32.o] Error 1
scons: building terminated because of errors.

**Comment by bruvzg** [comment]
Seems like VPX still has some configuration issues on ARM Linux (it's not really maintained or officially supported platform).

You can disable it if you do not need any of these codecs by adding `module_theora_enabled=false module_webm_enabled=false module_webp_enabled=false` to the command. Or search of older ARM Linux issues, there's some set of additional variables that might work.

**Comment by dh928** [comment]
should I just type in module_theora_enabled=false module_webm_enabled=false to the terminal directly? Or should I type it with the "Scons -j1 platform=x11"?


> Seems like VPX still has some configuration issues on ARM Linux (it's not really maintained or officially supported platform).
> 
> You can disable it if you do not need any of these codecs by adding `module_theora_enabled=false module_webm_enabled=false module_webp_enabled=false` to the command. Or search of older ARM Linux issues, there's some set of additional variables that might work.

**Comment by bruvzg** [comment]
```
scons p=linuxbsd module_theora_enabled=false module_webm_enabled=false module_webp_enabled=false CC=gcc-10 CXX=g++-10 AR=gcc-ar-10 RANLIB=gcc-ranlib-10 LINK=g++-10
```

And BTW, are you building `master` branch? It currently has only Vulkan renderer implemented, and I do not think RPI support Vulkan. For OpenGL use `3.2` ?

**Comment by dh928** [comment]
> ```
> scons p=linuxbsd module_theora_enabled=false module_webm_enabled=false module_webp_enabled=false CC=gcc-10 CXX=g++-10 AR=gcc-ar-10 RANLIB=gcc-ranlib-10 LINK=g++-10
> ```
> 
> And BTW, are you building `master` branch? It currently has only Vulkan renderer implemented, and I do not think RPI support Vulkan. For OpenGL use `3.2`.

how do i use 3.2? I am so sorry I am really new to this. 
and I typed in the command in terminal, and I still get a message:
pi@raspberrypi:~/godot $ scons p=linuxbsd module_theora_enabled=false module_webm_enabled=false module_webp_enabled=false CC=gcc-10 CXX=g++-10 AR=gcc-ar-10 RANLIB=gcc-ranlib-10 LINK=g++-10
scons: Reading SConscript files ...
Invalid target platform "linuxbsd".
The following platforms were detected:

	server
	x11

Please run SCons again and select a valid platform: platform=<string>

**Comment by bruvzg** [comment]
> Invalid target platform "linuxbsd".

If it's `x11` it's already on 3.2, `p=linuxbsd` if for 4.0 (Vulkan), `p=x11` for 3.2.

**Comment by dh928** [comment]
> > Invalid target platform "linuxbsd".
> 
> If it's `x11` it's already on 3.2, `p=linuxbsd` if for 4.0 (Vulkan), `p=x11` for 3.2.

How can I switch to 3.2? I don;t think 4.0 will work on my raspberry 3 B+

**Comment by bruvzg** [comment]
Run `git checkout 3.2` if you get source by cloning this repo.

**Comment by dh928** [comment]
> git checkout 3.2

Already on '3.2'
Your branch is up to date with 'origin/3.2'.

This is what I got, but i'm not sure.

**Comment by bruvzg** [comment]
Then just change `p=linuxbsd` to `p=x11` in the command above, and it should work.

**Comment by dh928** [comment]
> Then just change `p=linuxbsd` to `p=x11` in the command above, and it should work.

pi@raspberrypi:~/godot $ scons p=x11 module_theora_enabled=false module_webm_enabled=false module_webp_enabled=false CC=gcc-10 CXX=g++-10 AR=gcc-ar-10 RANLIB=gcc-ranlib-10 LINK=g++-10
scons: Reading SConscript files ...
Couldn't parse CXX environment variable to infer compiler version.
Enabling ALSA
Enabling PulseAudio
Couldn't parse CXX environment variable to infer compiler version.
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> platform/x11/godot_x11.cpp
sh: 1: g++-10: not found
scons: *** [platform/x11/godot_x11.x11.tools.32.o] Error 127
scons: building terminated because of errors.

should I install g++? But I thought I already have gcc 10.1 and g++10.1

**Comment by dh928** [comment]
> Then just change `p=linuxbsd` to `p=x11` in the command above, and it should work.

![IMG_0784](https://user-images.githubusercontent.com/52692636/88710079-157f3300-d0e4-11ea-965b-23e6d3205718.jpeg)

**Comment by bruvzg** [comment]
If it's not in PATH, you have to set it to the full path, like `CC=/opt/gcc-10.1.0/bin/gcc-10.1` (and similar for the other variables).

**Comment by dh928** [comment]
I tried running
sudo update-alternatives --install /usr/bin/gcc gcc /opt/gcc-10.1.0/bin/gcc-10.1 60 --slave /usr/bin/g++ g++ /opt/gcc-10.1.0/bin/g++-10.1

i don't know if that was why it is affecting it

**Comment by dh928** [comment]
> If it's not in PATH, you have to set it to the full path, like `CC=/opt/gcc-10.1.0/bin/gcc-10.1` (and similar for the other variables).

thank you so so so much!

**Comment by dh928** [comment]
I followed the instruction and put in the command
scons p=x11 module_theora_enabled=false module_webm_enabled=false module_webp_enabled=false CC=/opt/gcc-10.1.0/bin/gcc-10.1 CXX=/opt/gcc-10.1.0/bin/g++-10.1 AR=/opt/gcc-10.1.0/bin/gcc-ar-10.1 RANLIB=/opt/gcc-10.1.0/bin/gcc-ranlib-10.1 LINK=/opt/gcc-10.1.0/bin/g++-10.1

It ran for an hour on the raspberry pi and suddenly had an error like this:
[Initial build] Compiling ==> editor/editor_folding.cpp
[Initial build] make_fonts_header(["editor/builtin_fonts.gen.h"], ["thirdparty/fonts/DroidSansFallback.ttf", "thirdparty/fonts/DroidSansJapanese.ttf", "thirdparty/fonts/Hack_Regular.ttf", "thirdparty/fonts/NotoNaskhArabicUI_Regular.ttf", "thirdparty/fonts/NotoSansDevanagariUI_Regular.ttf", "thirdparty/fonts/NotoSansHebrew_Regular.ttf", "thirdparty/fonts/NotoSansThaiUI_Regular.ttf", "thirdparty/fonts/NotoSansUI_Bold.ttf", "thirdparty/fonts/NotoSansUI_Regular.ttf"])
[Initial build] Compiling ==> editor/editor_fonts.cpp
g++-10.1: fatal error: Killed signal terminated program cc1plus
compilation terminated.
scons: *** [editor/editor_fonts.x11.tools.32.o] Error 1
scons: building terminated because of errors.


what should I do? (crying crying)

**Comment by pouleyKetchoupp** [comment]
Are you trying to build the editor or just for export? In any case, I would suggest export as a first step so you'll be able to disable more features.

A few things you can try to avoid running out of memory:
* `tools=no` for export build only (not editor)
* `disable_3d=yes` if you don't use 3d
* Disable some extra modules you don't need (https://docs.godotengine.org/en/latest/development/compiling/optimizing_for_size.html#disabling-unwanted-modules)
* Maybe `target=release` to avoid debug symbols (although I'm not sure what effect it could have on memory used for linking, so better try with and without to compare)
