### ISSUE TITLE
Default WindowDialog title bar

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40828]
**Godot version:**

3.2.3

**Issue description:**

So I just wasted some time trying to figure out how to do a proper title bar in WindowDialog. Turns out the `panel` style is used both for contents and title bar. Well, this is mentioned in the class ref, but what isn't mentioned is how the default WindowDialog is made. **The trick is that title bar is made with a top border and an expand margin in the panel stylebox.** Would be probably useful if the docs mentioned that.

**Comment by pret3nti0u5** [comment]
Hey, I would like to work on this issue. I am new to contributing to open source projects, so please be patient with me, from what I can understand I only have to update the documentation. If that's so I would like to contribute!

**Comment by KoBeWi** [comment]
> from what I can understand I only have to update the documentation.

Yes, somewhere in the WindowDialog doc there should be info how to re-create a basic-looking dialog.

**Comment by hhsdev** [comment]
Hi, as there has been no communication from @pret3nti0u5 for quite a while, I wonder if I could take this one? Thanks.

**Comment by Calinou** [comment]
@hhsdev Sure, feel free to give it a try :slightly_smiling_face:

**Comment by hhsdev** [comment]
> Yes, somewhere in the WindowDialog doc...

Hi! Sorry to bother but I cannot find the documentation for `WindowDialog` in this repo (closest I found was doc/classes/Window.xml but that seems unrelated?). There is, however, a [`class_windowdialog.rst`](https://github.com/godotengine/godot-docs/blob/master/classes/class_windowdialog.rst) in [godotengine/godot-docs](https://github.com/godotengine/godot-docs). Am I supposed to update the documentation there or am I misunderstanding something? Thanks in advance!

**Comment by Calinou** [comment]
@hhsdev WindowDialog was removed in the `master` branch as part of the [DisplayServer refactor](https://godotengine.org/article/core-refactoring-progress-report-2). You need to switch to the `3.2` branch, create a new branch and make a pull request against the `3.2` branch.

**Comment by KoBeWi** [comment]
AFAIK the single window mode should still use the old dialogs, so they could still be somewhere.

**Comment by hhsdev** [comment]
@Calinou Gotcha, thanks.

**Comment by kotelifelif** [comment]
If I understand correctly, this issue needs to be closed.

**Comment by Calinou** [comment]
@kotelifelif Indeed, thanks for the reminder :slightly_smiling_face:
