### ISSUE TITLE
Visual Shader preview "eye" does not show correctly

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#40820]
**Godot version:**
3.2.3 RC 2

**OS/device including version:**
GLES3, Windows 10

**Issue description:**
When attatching uniform to a node, the preview gets all wrong. does not update when i change value.

**Steps to reproduce:**
See picture below, project below

**Minimal reproduction project:**
[BugForGit.zip](https://github.com/godotengine/godot/files/4993697/BugForGit.zip)
![image](https://user-images.githubusercontent.com/13393087/88777663-c25ebc00-d187-11ea-8cd4-f6acb034f2fc.png)

**Comment by Chaosus** [comment]
This was fixed in master, but still presents in 3.2

**Comment by Chaosus** [comment]
The problem seems not to exist on 4.0, need to inspect it more deeply...

**Comment by Chaosus** [comment]
Ah, it still exists in 4.0, I was wrong.
