### ISSUE TITLE
Scrolling does not work with touchpad

### ISSUE THREAD

**Issue by DisasterMaster19** [godotengine/godot#40839]
I downloaded godot on my lenovo laptop today, and discovered that scrolling does not work in godot, but it works everywhere else.

It is really annoying having to use the scroll bar to scroll through a super long script

**Comment by akien-mga** [comment]
Please fill the issue template...

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
