### ISSUE TITLE
PopupMenu accelerators don't work.

### ISSUE THREAD

**Issue by SekoiaTree** [godotengine/godot#40836]
**Godot version:**
3.2.stable.official

**OS/device including version:**
OS: Windows 10

**Issue description:**
A PopupMenu's accelerator does not work when using any kind of add_item. The item will be clickable, will have the hint on the right of the shortcut, but the accelerator will simply not work. From the docs: 

>  Accelerators are special combinations of keys that activate the item, no matter which control is focused.

**Steps to reproduce:**
Create a popupmenu in any scene. Give the PopupMenu the following code:
```extends PopupMenu
	
func _ready():
	add_item("PopupMenu bug test", 0, KEY_A)
	call_deferred("popup_centered_ratio") #This call_deferred is only so the popupmenu would open on scene launch. This bug happens for any call of any popup, at any time.




func _on_PopupMenu_id_pressed(id):
	print("Object Pressed")
```
Connect the id_pressed signal to itself, and launch the scene.

On scene launch, the popupmenu will contain a button with the label "PopupMenu bug test" and a grayed out "A" on the right. Pressing "A" should activate the button, printing "Object Pressed". This does not happen. Upon clicking the item, it does.

**Minimal reproduction project:**
[PopupMenuBugReport.zip](https://github.com/godotengine/godot/files/4995544/PopupMenuBugReport.zip)

This project contains the above code, plus a couple practicality nodes.

**Comment by EricEzaM** [comment]
Cannot reproduce in 4.0 master 10150f7b5

**Comment by SekoiaTree** [comment]
Did you try the demo project? It's still not working for me.

**Comment by dominiks** [comment]
Can confirm for 3.2.3 that the accelerator only works for menus that belong to a `MenuButton`. It seems there is no way to call the menu's `activate_item_by_event` from somewhere else but the `MenuButton`.

I think it should be possible to send input events to the menu via `activate_item_by_event` from GDScript and make accelerators usable for context menus.

**Comment by goblinJoel** [comment]
Can confirm for 3.5.1 using the test project. Pressing A never seems to do anything, but clicking the button with the "A" at the end of it does.

**Comment by Calinou** [comment]
Still reproducible on 4.2.dev 16a93563b.
