### ISSUE TITLE
constant_linear_velocity in 3D

### ISSUE THREAD

**Issue by vesan66** [godotengine/godot#40834]
If you use a constant_linear_velocity on a staticbody. lets say for the x-axis, the a dropped rigidbody will be moved in this direction. If now, you rotate the staticbody by an angle, then the dropped rigidbody goes still along the world-x-axis. that means, the orientation of the staticbody has no effect on the direction of the constant_linear_velocity. Is this intended? I’m a bit surprised about.

**Godot version:**
3.2.2 OSX with Mono

**OS/device including version:**
OSX Catalina

**Issue description:**
Is it intended, to apply only 'Global' velocitiy direction?

**Steps to reproduce:**
Make a staticbody with linearvelocity, drop a rigidbody. the rotate staticbody, but the direction of the velocity is the same.

**Minimal reproduction project:**
-

**Comment by Calinou** [comment]
This is likely intended, especially if it works the same way in 2D already.

**Comment by vesan66** [comment]
For me it feels like putting an attribute to an object like e.g. a texture, that normally goes with the orientation.
That's why I'm asking.

**Comment by Calinou** [comment]
cc @madmiraal and @AndreaCatania

**Comment by madmiraal** [comment]
Yes, this is intended. A body's velocity is independent of its orientation. Consider a spinning object flying through the air. Its velocity is independent of its orientation.

Note: In physics, to change the direction of the velocity requires an acceleration perpendicular to the direction of the velocity.
