### ISSUE TITLE
Node disappears when animating a Tween with duration of 0

### ISSUE THREAD

**Issue by DanielZTing** [godotengine/godot#40843]
**Godot version:**

v.3.2.2.stable.official

**OS/device including version:**

macOS Catalina 10.15.5 (19F101)
MacBook Air (Retina, 13-inch, 2018)
Intel UHD Graphics 617 1536 MB
Confirmed on both GLES2 and GLES3

**Issue description:**

Animating a node with a tween with a duration of 0 causes the node to disappear. I expected it to just animate instantly.

**Steps to reproduce:**
1. Add ColorRect
2. Add Tween and Timer under ColorRect
3. Set Timer to One Shot and Autostart
4. Attach script to ColorRect
5. Connect Timer timeout() signal to the following code:

```gdscript
extends ColorRect

func _on_Timer_timeout():
    $Tween.interpolate_property(self, "rect_position", null, Vector2(100, 100), 0)
    $Tween.start()
``` 
6. Play scene

**Minimal reproduction project:**

[tween.zip](https://github.com/godotengine/godot/files/4996700/tween.zip)

**Comment by KoBeWi** [comment]
Still valid in 60dcc4f
Might be some bug with interpolaters. The easiest fix would be a special case for 0 time interpolation.
