### ISSUE TITLE
GDScript: no parser error when calling `new()`

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#40863]
**Godot version:** v4.0.dev.custom_build 5ba46ddf8

**OS/device including version:** windows 10

**Issue description:**
the below code doesn't throw any errors at compile time.
```gdscript
extends Node2D
var x = new()
```

**Comment by vnen** [comment]
This is not a bug, it's a valid way to create a new instance of the current script. While this didn't work before, a lot of people have asked for it.

**Comment by ThakeeNathees** [comment]
closing according to:
> This is not a bug, it's a valid way to create a new instance of the current script. While this didn't work before, a lot of people have asked for it.
