### ISSUE TITLE
GDScript: no parser error when invalid `preload()` used

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#40864]
**Godot version:** v4.0.dev.custom_build 5ba46ddf8

**OS/device including version:** windows 10

**Issue description:**
preloading the current script doesn't  show any errors.
```gdscript
extends Node2D
## current script path = res://Node2D.gd
var s = preload("res://Node2D.gd")
```

**Comment by adamscott** [comment]
Since #67714, it's actually a feature. A script can preload itself, then compare the type.
So this code works:
```gdscript
# res://A.gd
var SelfClass: = preload("res://A.gd")

func _ready() -> void:
    print(is_instance_of(self, SelfClass))  # true
```
