### ISSUE TITLE
GDScript: no parser error when the `_ready` function signature doesn't match the parent signature.

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#40862]
**Godot version:** v4.0.dev.custom_build 5ba46ddf8

**OS/device including version:** windows 10

**Issue description:**
the below codes are compiles and runs without any errors.
```gdscript
static func _ready():
	pass
```	
```gdscript
func _ready(p):
	pass
```

**Comment by vnen** [comment]
This is already solved by #58835.
