### ISSUE TITLE
File class's READ_WRITE Mode bug

### ISSUE THREAD

**Issue by selamba** [godotengine/godot#40878]
**Godot version:** v3.2.2.stable.official

**OS/device including version:** Pop_OS 20.04

**Issue description:**
When opening a file with File.READ_WRITE mode, it should not be truncated. However, it still gets truncated, as if File.WRITE_READ or File.WRITE was used.

**Steps to reproduce:**
Open a file in READ_WRITE mode and store anything in it. Do so twice and only the second stored value will be present.

**Minimal reproduction project:**
Attached. It is a single Node with a script. Code is commented.
[FileDemo.zip](https://github.com/godotengine/godot/files/5000985/FileDemo.zip)

**Comment by mrushyendra** [comment]
Just a small clarification, but in the attached script, should `File.WRITE` in line 15 be `File.READ_WRITE`? Either way the behavior you described occurs.
```
	# Open for the second time and write "Second"
	file.open(path, File.WRITE)
```

I believe this is not actually a bug. `READ_WRITE` mimics `r+` mode in C or Python, and the cursor is set to the beginning of the file when opened. To workaround, you can do something like this:

```
	# Open for the second time and write "Second"
	file.open(path, File.READ_WRITE)
	file.seek_end(0)
	file.store_string("Second\n")
	file.close()
```

Perhaps an 'append' (a) mode should be added, or the documentation should be clarified.
