### ISSUE TITLE
Select Frames Modal has no zoom funktionality

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot#40870]
**Godot version:**
3.2.2

**Issue description:**
It is very hard to see the different frame in tiny sprite sheets

**Steps to reproduce:**
Open a sprite sheet in the AnimatedSprite "Add Frames from Sprite Sheet" modal.

![EeKGVWVX0AAOEF8](https://user-images.githubusercontent.com/4989757/88894784-bedf3980-d248-11ea-8510-398be1bed575.png)

Would be nive if there is a zoom button like in other modals.

**Comment by Calinou** [comment]
This repository is meant to be used for bug reports only. Please open a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals/) repository instead.

**Comment by LinuxUserGD** [comment]
https://github.com/godotengine/godot-proposals/issues/1278
