### ISSUE TITLE
Glow in 4.0 looks wrong

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#40877]
**Godot version:**
4.0

**OS/device including version:**
1080ti, windows 10

**Issue description:**
The glow in 4.0 looks wierd. 3.2 i could tweak it so it was "ok"
I've used roughly the same parameters in 3.2 and 4.0
I made the same material in UE4 and Unity, and the results are a little different.
They just seems to look a little nicer?

Example project
[VulkanTest.zip](https://github.com/godotengine/godot/files/5001084/VulkanTest.zip)

Godot 4.0 
![G4](https://user-images.githubusercontent.com/13393087/88918291-81d76f00-d269-11ea-8698-6384ffedca81.png)

Godot 3.2.3
![G32](https://user-images.githubusercontent.com/13393087/88918320-8a2faa00-d269-11ea-8323-dd031d144ff2.png)

Ue4
![ue4glow](https://user-images.githubusercontent.com/13393087/88918351-94ea3f00-d269-11ea-9b1e-ee911a174097.png)

Unity Without Lights
![unityWOlight](https://user-images.githubusercontent.com/13393087/88918380-a2072e00-d269-11ea-8185-117905d41842.png)

Unity With Lights
![unityWlight](https://user-images.githubusercontent.com/13393087/88918393-a7fd0f00-d269-11ea-8157-2670315c91eb.png)

**Comment by Calinou** [comment]
> Godot 4.0 ( Bicubic upscale is gone in 4.0 ? )

It's not; it was moved to the Project Settings (like all other quality-related settings).

**Comment by Norrox** [comment]
> I wouldn't expect glow settings in 4.0 to look 100% identical to the glow settings in 3.2.
> 
> If you want a (non-realistic but good-looking) glow appearance, try using the new **Mix** glow blend mode when a mix blending value between 0 and 1.
> 
> > Godot 4.0 ( Bicubic upscale is gone in 4.0 ? )
> 
> Bicubic upscaling is still available. It was moved to the Project Settings (like all other quality-related settings).

i still get the same result, it's still looks smeared out
i'll update the first post with example project

![Anteckning 2020-07-30 140431](https://user-images.githubusercontent.com/13393087/88920820-c49b4600-d26d-11ea-975f-a9440e72847d.png)

**Comment by Zylann** [comment]
That looks like a bug to me.

**Comment by reduz** [comment]
Yeah it broke when I converted it to Compute shaders but did not have time to fix it. Was hoping someone would give it a check and do a PR but so far it did not happen. I will have to fix it myself eventually.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/41605
