### ISSUE TITLE
Closing ColorPicker in the inspector always "modifies" the scene

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40879]
**Godot version:**

3.2.3 rc2

**Steps to reproduce:**
1. Create a Node2D
2. Click on modulate to change color
3. Don't change anything, just press Escape
4. Scene was modified, bruh

It's annoying when you want to check/copy some color and it produces fake unsaved changes.

**Comment by AlphaOneProject** [comment]
Hello,
I made this pull request resolving this issue on my side.
Could you please tell me if it is what you wanted?

I'm still beginning so I'm quite likely to have made mistakes, even if I did my best to follow the guidelines.
