### ISSUE TITLE
Texture and character are not visible when I run the project on the web

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#40881]
**Godot version:**

Godot 3.2.3 RC 2 mono
![Captura de pantalla_2020-07-30_10-25-36](https://user-images.githubusercontent.com/12847027/88928282-07015a80-d24f-11ea-8ce8-5179bf3c61ac.png)

**OS/device including version:**

![Captura de pantalla_2020-07-30_10-27-46](https://user-images.githubusercontent.com/12847027/88928540-55165e00-d24f-11ea-9358-65119dcd3466.png)

**Issue description:**

Texture and character are not seen when I test the project on the web

This is how it looks when I run the project in the editor.
![Captura de pantalla_2020-07-30_10-34-52](https://user-images.githubusercontent.com/12847027/88929461-85aac780-d250-11ea-903c-729aa103f962.png)
and this is how it looks when it is on the web.
![Captura de pantalla_2020-07-30_10-39-47](https://user-images.githubusercontent.com/12847027/88929877-18e3fd00-d251-11ea-830e-4c2521136bc7.png)

**Steps to reproduce:**
run the project in the editor and then run the project in the browser using the godot button to create the server automatically.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12847027/88930737-40879500-d252-11ea-93ca-0feff0cf9478.gif)

**Minimal reproduction project:**

Download this project and run it with Godot 3.2.3 RC 2 mono
https://github.com/kone9/scavengers-3D-roguelike-godot-engine-CSharp

**Comment by Calinou** [comment]
Double-check the texture sizes: they should be powers of two and preferably not exceed 2048×2048 to work everywhere.

**Comment by kone9** [comment]
> Double-check the texture sizes; each dimension should be a power of 2. Also, textures shouldn't exceed 2048×2048 to work everywhere.

Is it clarified in the documentation?
And why does the character disappear?

**Comment by kone9** [comment]
> Double-check the texture sizes; each dimension should be a power of 2. Also, textures shouldn't exceed 2048×2048 to work everywhere.
The textures of the character have 1024x1024
![Captura de pantalla_2020-07-30_11-49-04](https://user-images.githubusercontent.com/12847027/88937667-d45d5f00-d25a-11ea-922b-09229d71070d.png)
The poster textures are 512x512.
![Captura de pantalla_2020-07-30_11-51-31](https://user-images.githubusercontent.com/12847027/88937926-21d9cc00-d25b-11ea-8212-8ba98ced86f4.jpg)
