### ISSUE TITLE
Vector3 - perpendicular

### ISSUE THREAD

**Issue by monk-e-boy** [godotengine/godot#40884]
3.2.2

**Issue description:**

Have a Vector3, would like to get a vector perpendicular to it.

For my application I want to draw a tube around a vector:

- Using v1, find perpendicular vector (v2)
- Normalize v2, the resize to desired radius
- Rotate v2 around v1.normalized() to get an array of vectors
- Construct tube using these

Also could be nice for orbiting particles, spiraling particles, etc

https://stackoverflow.com/questions/11132681/what-is-a-formula-to-get-a-vector-perpendicular-to-another-vector

**Comment by Calinou** [comment]
Are you looking for `Vector3.cross()`?

**Comment by monk-e-boy** [comment]
Cross product is something different. I'm not asking for help I'm sugesting an enhancement.

**Comment by monk-e-boy** [comment]
Sorry I guess my comment - this was what the perpendicular vector would be used for in real life - I have used it to create a tube that has my vector in the center.

**Comment by Calinou** [comment]
@monk-e-boy Please open feature proposals on [Godot proposals](http://github.com/godotengine/godot-proposals). Note that core features that aren't going to be used very often are unlikely to be accepted.
