### ISSUE TITLE
InputEvents are triggered twice when using 

### ISSUE THREAD

**Issue by nickkoro02** [godotengine/godot#40889]
**Note:** 
I can't believe this was not reported before, but I've searched the issues and didn't find anything describing it. Sorry if I overlooked it. If this is not a bug, it is confusing at best, and should be documented somewhere probably.

**Godot version:**
3.2.2 stable

**OS/device including version:**
Windows 10 x64, GLES3

**Issue description:**
Events processed with `_input` and `_process` are fired twice if the script is attached to a singleton. As simple it may sound, it is 100% reproducable on my machine.
_Update:_ This is also reproducable if you process the event in a sub-node of a singleton.

**Steps to reproduce:**
1. Create a  `Node2D`
2. Define it as a singleton:
![image](https://user-images.githubusercontent.com/19800702/88955799-b7e21680-d29c-11ea-9e34-148782b81133.png)
3. Create a keybing for mouse click:
![image](https://user-images.githubusercontent.com/19800702/88955535-59b53380-d29c-11ea-8a2a-7285fe076a29.png)
4. Attach a script to said `Node2D` with the following code:
```gdscript
extends Node2D

func _input(event):
	if event is InputEventMouseButton and event.is_action_released("click"):
		print("foo")
```
5. Start the game and click in the scene. `foo` is printed twice.
6. Close the game, and remove the node from the autoload, then start the game and click in the scene. `foo` is printed once.

**Minimal reproduction project:**
Please pardon me for the name of this project. This bug is just too annoying.
[YEEEEEEET.zip](https://github.com/godotengine/godot/files/5002915/YEEEEEEET.zip)

**Comment by akien-mga** [comment]
That's not a bug, but a misunderstanding on your end on what "AutoLoads" are. An AutoLoad is a script or scene that will be added to the scene tree automatically. So your Game scene will be added to the scene tree as `/root/Game`, and it will process events.

Then, your main scene also happens to be `Game.tscn`, so when you start the game, the main scene is added to the scene, and the `Game` autoload is added to the scene. So you have `Game` twice, thus two events (coming from two separate nodes).

![Screenshot_20200730_214909](https://user-images.githubusercontent.com/4701338/88967890-b9b4d580-d2ae-11ea-8d86-ed65da2af313.png)
