### ISSUE TITLE
Disabling 3D Editor feature makes it impossible to use ParticleMaterial resources

### ISSUE THREAD

**Issue by dejaime** [godotengine/godot#40899]
**Godot version:**
3.2.2-stable and 3.2.3-RC2

**OS/device including version:**
Linux 64, Ryzen 7 1700, Geforce GTX 1070, Up to date drivers
other specs: https://haste.rys.pw/yekiduniyi.coffeescript

**Issue description:**
Disabling 3D Editor under _Editor_ -> _Manage Editor Features_ breaks the Particle Material _editor_ / _inspector_.
If you try to create a new particle material and edit it with 3D editor disabled, you can still expand it, but it is empty. Right-click -> edit takes us to an empty editor.

**Steps to reproduce:**
https://streamable.com/348g30
- Disable **3D Editor** under **Edit -> Manage Editor Features**
- Add a Particle2D, and add a new Particle Material to it
- Try to edit the Particle Material, all options are omitted
- Reenable the **3D Editor** feature, now the options show up as expected

**Minimal reproduction project:**
[2DProfile.tar.gz](https://github.com/godotengine/godot/files/5010491/2DProfile.tar.gz)
[StandardProfile.tar.gz](https://github.com/godotengine/godot/files/5010492/StandardProfile.tar.gz)
[issue.tar.gz](https://github.com/godotengine/godot/files/5005289/issue.tar.gz)

Thank you!

**Comment by opl-** [comment]
Can't repro on 3.2.2.stable.mono running Debian.

**Comment by dejaime** [comment]
Tested on three more computers, can't reproduce. Not sure why this is only happening on my work machine.
I'll leave this closed for now. Thanks @opl- for also testing.
