### ISSUE TITLE
Templates generated by custom Android build can't be used without a custom build

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#40896]
**Godot version:**
3.2.2 Mono

**OS/device including version:**
MXLinux 19

**Issue description:**
The new plugin system slows down app deployment and runs graddle even if you never change anything in the custom build, It would be better if you could use the templates generated, but when I use the files generated at android/build/build/outputs/apk as custom templates I can't access the plugin.

Tested with https://github.com/Shin-NiL/Godot-Android-Admob-Plugin

**Steps to reproduce:**
Use the apk templates generated by a custom build with a plugin as custom templates

**Comment by Shin-NiL** [comment]
Please read [this issue](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/67). We don't know if there is an easier or cleaner way to do, but it works as a workaround at least.

**Comment by m4gr3d** [comment]
@MightyPrinny That's the intended behavior. The plugins require additional parameters which is passed to the gradle build process at export time. As such they can't be used with a (default or generated) template.

We're still in the process of improving the build and export flow, so we'll take the feedback into consideration.

Thanks!
