### ISSUE TITLE
Control handles extremely small on mobile device

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#40910]
**Godot version:**
<img width="517" alt="Screenshot 2020-07-31 at 15 07 14" src="https://user-images.githubusercontent.com/100964/89020983-85d5c080-d33f-11ea-805a-01149c7cf45b.png">

**OS/device including version:**
<img width="340" alt="Screenshot 2020-07-31 at 15 07 22" src="https://user-images.githubusercontent.com/100964/89020994-8a01de00-d33f-11ea-9643-160a8904f59a.png">

Android Nexus 6P (screen size 2560 x 1440)

**Issue description:**
Control handles are extremely small on my mobile device, which has a large resolution.

Display scaling with `expand viewport` doesn't help me much in this case as I would like to use the sensor of the device to rotate the controls without them appearing stretched or crushed.

**Desktop screenshot**
<img width="1136" alt="Screenshot 2020-07-31 at 15 04 47" src="https://user-images.githubusercontent.com/100964/89021091-aef65100-d33f-11ea-8860-8d4bf62caed1.png">

**Mobile screenshots**

Notice the handle size of the `SpinBox` is still just a couple of pixels high.
<img width="400" alt="Mobile landscape" src="https://user-images.githubusercontent.com/100964/89021129-bd446d00-d33f-11ea-821e-723bc3f9cb09.png">

As well as the HScrollBar has just a few pixels of width for the handle. On mobile this is impossible to grab, as the real screen size is less than 1mm.
<img height="400" alt="Mobile profile" src="https://user-images.githubusercontent.com/100964/89021137-c03f5d80-d33f-11ea-83c7-0330f03dc98f.png">

**Steps to reproduce:**
Take any mobile device with a high screen resolution
Controls handles will be unusably small.

**Minimal reproduction project:**
https://github.com/tavurth/godot-controlsize-bug

Perhaps there's a way to control the size of the handles?

**Comment by Calinou** [comment]
Try using the `2d` stretch mode and `expand` stretch aspect as described in the [Multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) documentation.

**Comment by tavurth** [comment]
@Calinou I see, I'd previously tried that but it was giving me a weird stretching effect of my GUI controls. 
I see now that it was because I'd `anchored` them rather than using a `VBox` or `HBox`.

Thank you for getting me to check it again! I'll close this 👍
