### ISSUE TITLE
Cannot import zipped plugin 

### ISSUE THREAD

**Issue by ShivamMukherjee** [godotengine/godot#40912]
**Godot version:**
3.2.2 (both default and Mono)

**OS/device including version:**
Windows 10

**Issue description:**
When I try to import a .zip file on my system using AssetLib, it shows this: 
![image](https://user-images.githubusercontent.com/12777564/89024173-4f4d7500-d342-11ea-97ad-7d6eae00d8f8.png)

**Steps to reproduce:**
1. Downlaod a plugin from assetlib.
2. Store it in a .zip file (the entire project addon including a project.godot file or just the addon directory)
3. Attempt to import the .zip file using `Import...`

**Minimal reproduction project:**
[godot-debug-overlay.zip](https://github.com/godotengine/godot/files/5006383/godot-debug-overlay.zip)

**Comment by Calinou** [comment]
The asset library is designed so you upload plugins directly in the VCS repository. Don't store them in ZIP files.

**Comment by akien-mga** [comment]
@Calinou The Asset Lib does have a feature to import plugins from a .ZIP files instead of downloading them from an online repo (which also retrieves them as ZIPs). I think that's what this report is about, not having a zipped file in an asset repo.

![Screenshot_20200731_142517](https://user-images.githubusercontent.com/4701338/89034638-a9960800-d339-11ea-943e-5e90e8e2edc7.png)

**Comment by akien-mga** [comment]
Nevermind, I just checked the MRP and I see the confusion. You should indeed not distribute your asset as a ZIP in `addons/` to put it on the library, it should be the unzipped, ready-to-use source files. See https://docs.godotengine.org/en/3.2/tutorials/assetlib/uploading_to_assetlib.html

With a properly formed asset, importing a manually downloaded ZIP works fine:
![Screenshot_20200731_142619](https://user-images.githubusercontent.com/4701338/89034886-245f2300-d33a-11ea-8a65-da83da7395f3.png)
(That's https://github.com/akien-mga/godot-debug-watermark/ downloaded as ZIP.)

**Comment by ShivamMukherjee** [comment]
Oh snap, I uploaded the wrong MRP. Please wait, that isn't the issue.

**Comment by ShivamMukherjee** [comment]
I think it's to do with a lack of plugin.cfg files in these plugins. Probably gitignored?

**Comment by ShivamMukherjee** [comment]
Well I see that your ZIP imported well. What is the ideal directory structure ( apart from adding the `addons/` child?)

**Comment by Calinou** [comment]
@ShivamMukherjee The ideal directory structure for the repository is something like https://github.com/akien-mga/godot-debug-watermark/. If you follow the same structure, it should work fine.

You can include multiple add-ons in the same repository as well. Just make sure they're all in the `addons/` subdirectory.

**Comment by ShivamMukherjee** [comment]
I don't understand. Could you look into this directory structure?

[PluginsTemplate.zip](https://github.com/godotengine/godot/files/5012516/PluginsTemplate.zip)

**Comment by ShivamMukherjee** [comment]
Any updates on this?

**Comment by Calinou** [comment]
@ShivamMukherjee The root folder in your `PluginsTemplate.zip` has a name that starts with a period (`.`). Try renaming it to something that doesn't start with a period.

**Comment by ShivamMukherjee** [comment]
The second one doesn't follow that convention and still can't be imported.
