### ISSUE TITLE
Can't see StreamPlayer Editor

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4091]
Hi. I'm using godot 2.0.1. It seems like the play and stop button of StreamPlayer are out of layout.

This is what it shows when I click on the StreamPlayer:

![img](https://cloud.githubusercontent.com/assets/6760623/13894196/cbc382a6-ed3b-11e5-9e7a-6a02e5e2ab13.png)

I'm on ubuntu 14.04.

**Comment by vnen** [comment]
BTW, the buttons seem to be gone in current master. They should be put in a more visible location.

**Comment by reduz** [comment]
streamplayer editor is now gone, use the play property
