### ISSUE TITLE
Error importing some PNG files.

### ISSUE THREAD

**Issue by AllenKll** [godotengine/godot#40925]
**Godot version:**
3.2.1

**OS/device including version:**
Win10

**Issue description:**
Errors recieved when attempting to use a PNG file:

```
 drivers/png/png_driver_common.cpp:56 - Not a PNG file
 drivers/png/png_driver_common.cpp:70 - Condition "!success" is true. Returned: ERR_FILE_CORRUPT
 core/io/image_loader.cpp:69 - Error loading image: res://djin.png
 editor/editor_file_system.cpp:1800 - Error importing 'res://djin.png'.

```
If I open the PNG file in GIMP, and export it as a PNG, then there is no issue.
GIMP has no problem opening file.  
Chrome/FIrefox/Edge has no problem opening file.
Windows picture viewer has no problem opening the file.

This is not the only file that I've seen the error on.  I am just including it as an example to use for debugging.

**Steps to reproduce:**
load the sample project.
observe error in output window

**Minimal reproduction project:**
[PNGError.zip](https://github.com/godotengine/godot/files/5008291/PNGError.zip)

**Comment by akien-mga** [comment]
It's a JPEG :)
```
$ file djin.png
djin.png: JPEG image data, JFIF standard 1.01, resolution (DPCM), density 28x28, segment length 16, baseline, precision 8, 512x512, components 3
```
