### ISSUE TITLE
GDScript : no error when script `class_name` shadows an existing type

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#40938]
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
the below code runs without any errors
```gdscript
extends Node2D

class_name Array
const C = 1
func _ready():
	print(Array.C) ## prints 1
```

**Comment by dalexeev** [comment]
Fixed.

![](https://user-images.githubusercontent.com/47700418/217891312-1718ddaa-181a-42b7-a886-248f37e31bbd.png)

![](https://user-images.githubusercontent.com/47700418/217891587-578cf7ac-7140-4383-8c6b-737d1f14d39a.png)
