### ISSUE TITLE
RigidBody 2D does not wake up on applied Torque

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#40939]
**Godot version:** 3.2.2.stable

**OS/device including version:** Windows

**Issue description:**

There is an inconsistent behavior regarding the wake up process of a Rigid Body 2D, to which a Torque Impulse is applied.
When a Rigid Body 2D is sleeping, the Torque Impulse does not wake up the body, but the torque is applied in the background, so that it affects the body after it gets woken up.

I would expect, that a Torque Impulse immediately wakes up the Rigid Body 2D.

**Steps to reproduce:**

The Minimal reproduction project contains a rigid body that can be steered with the arrow keys.
After starting the project, hold down the left arrow key on the keyboard for several seconds -> The object stands still and does not wake up.
Now click on arrow up key on the keyboard -> the object wakes up and moves and rotates.

**Minimal reproduction project:**

[TorqueWakeup.zip](https://github.com/godotengine/godot/files/5010296/TorqueWakeup.zip)

**Possible solution:**
As far as I can tell, all functions, that apply an impulse to a rigid body, wake up that body, with the exception of PhysicsServer2DSW::body_apply_torque_impulse:
https://github.com/godotengine/godot/blob/67e4082b1e73f3cbe518c499eb328b0f68f3419b/servers/physics_2d/physics_server_2d_sw.cpp#L817-L824

I believe that inserting `body->wakeup();` at the end of this function should resolve this issue.

In case that the issue can be resolved by this change, I can offer to create a pull request.

**Workaround:**
After applying a torque impulse in GDScript, manually wake the object with `sleeping = false`.

**Comment by madmiraal** [comment]
> I believe that inserting body->wakeup(); at the end of this function should resolve this issue.
>
> In case that the issue can be resolved by this change, I can offer to create a pull request.

Yes, please create PR. It looks like it was missed when this functions were first created in #20404.
