### ISSUE TITLE
Stuttering when toggling `CSGShape` visibility or changing its parent

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#40931]
**Godot version:**
3.2.3.rc3 - master

**OS/device including version:**
Windows 10 2004

**Issue description:**
- A `CSGShape` _without_ child shapes won't update when its visibility changes - this is the intended behavior. No lag!
- A `CSGShape` _with_ child shapes will update every time its visibility in the scene tree changes. This causes a brief lag spike, the severity of which depends on the complexity of the shape.
- Any `CSGShape`, with or without children, will update whenever it enters and exits the scene tree. This seems to only be required for collision generation, but the shape ends up getting regenerated as well.

**Steps to reproduce:**
1. Add a `CSGShape` with one or more `CSGShapes` as children to the scene (preferably ones that are complex)
2. Toggle its visibility or change its parent
3. Watch for FPS drops

**Minimal reproduction project:**
[CSG Updates.zip](https://github.com/godotengine/godot/files/5009156/CSG.Updates.zip)

**Comment by madmiraal** [comment]
This is not a bug. This is by design. The `CSGShape` needs to be reconstructed if one of its children or peers' visibility changes.

Since, #40814 is an enhancement proposal that you're looking to support, please create an issue in [Godot Improvement Proposals](https://github.com/godotengine/godot-proposals) which has a more complete template and provides a better forum for discussion.

**Comment by hoontee** [comment]
Why would the root shape need to be updated when toggling its own visibility? Does it affect something I'm unaware of?

**Comment by hoontee** [comment]
@madmiraal 
> The `CSGShape` needs to be reconstructed if one of its children or peers' visibility changes.

That's true, but this issue deals with toggling the *root shape*'s visibility.
Perhaps I worded things too vaguely! I've updated this issue to clarify the nature of the bug.

**Comment by hoontee** [comment]
Can this be reopened with the `enhancement` label (if the `bug` label isn't appropriate?)

**Comment by hoontee** [comment]
Still an issue, I would appreciate if this could be reopened.

**Comment by hoontee** [comment]
Still an issue as of 4.0 alpha 1.
