### ISSUE TITLE
Crash when GDScriptParser::CallNode::callee is nullptr

### ISSUE THREAD

**Issue by snichols** [godotengine/godot#40942]
**Godot version:**

`ec9302ceccb75f44038db3695d2f9e7c82cfe951`

**OS/device including version:**

Microsoft Windows 10 Pro 10.0.19041 Build 19041

**Issue description:**

GDScript editor crashes when typing malformed call expressions.

**Steps to reproduce:**
1. Open a GDScript resource.
2. Type `var crash = ()(1)`

**Minimal reproduction project:**

[NullCallableCrash.zip](https://github.com/godotengine/godot/files/5010468/NullCallableCrash.zip)

**Comment by akien-mga** [comment]
Fixed by #41055.
