### ISSUE TITLE
Assigning a StyleBoxTexture to a button, and then specifying it's (ninepatch) margin settings causes issues

### ISSUE THREAD

**Issue by ginobean** [godotengine/godot#40946]
**Godot version:**
v3.2.2.stable.official

**OS/device including version:**
Ubuntu Linux 20.04 LTS
GLES3
Godot Engine v3.2.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GT 710/PCIe/SSE2
 

**Issue description:**

Created a simple button, under 'Custom Styles', assigned a StyleBoxTexture to it. For this StyleBoxTexture, associated a button-texture.png as it's texture. Assigned margin values of 100 to each of 'Left Margin', 'Right Margin', 'Top Margin', 'Bottom Margin'.

Button suddenly became oversized.

What I expected was that the button would scale and handle the ninepatch texture, in such a way that the button maintained the same size as before. 

What actually seemed to happen was that specifying margins of (100, 100, 100,100) caused the button to become grossly oversized.

**Steps to reproduce:**
Just run the sample project that I've attached to this bug form. 

As a side note, the dimensions of the button-texture.png are: 377x376.

**Minimal reproduction project:**

[stylebox-test.zip](https://github.com/godotengine/godot/files/5010676/stylebox-test.zip)

**Comment by Calinou** [comment]
If you set the StyleBox's margin, it will affect its minimum size if the button in question doesn't have a size large enough already.

I'm not sure what can be done about this.

**Comment by ginobean** [comment]
Is there an alternate way to specify the proportions of the 9-patch texture? I was actually intending to set the regions of the 
9-patch texture, and it looked like the margin settings were what controlled how the 9-patch texture was being interpreted.
