### ISSUE TITLE
Vector2.angle() description is not very clear

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40956]
**Godot version:**

3.2.3 rc3

**OS/device including version:**

**Issue description:**

The description of `Vector2.angle()` says:
```
Returns this vector's angle with respect to the X axis, or (1, 0) vector, in radians.
```
This basically means that `Vector2(1, 0)` (aka `Vector2.RIGHT`) has an angle of 0. The description could say it more explicitly.

**Comment by aaronfranke** [comment]
What could be more clear about it? It seems perfectly clear to me, I don't think there's any other way to interpret this.

**Comment by KoBeWi** [comment]
> I don't think there's any other way to interpret this.

The problem is that not everyone will know how to interpret what does it mean exactly.

**Comment by menip** [comment]
I think the description is very clear, and the functionality falls in line with what you learn in maths. I don't think it's the class documentation's job to teach math, just precisely describe the functionality.

**Comment by hoontee** [comment]
Saying "Vector2.RIGHT" instead of "the X axis" would definitely make it easier to understand for me:

`Returns this vector's angle relative to Vector2.RIGHT, or (1, 0), in radians.`

**Comment by KoBeWi** [comment]
> I don't think it's the class documentation's job to teach math, just precisely describe the functionality.

I've seen many complains that the documentation isn't easy to grasp for a beginner. This is an example of that.

**Comment by Sslaxx** [comment]
> Saying "Vector2.RIGHT" instead of "the X axis" would definitely make it easier to understand for me:
> 
> `Returns this vector's angle relative to Vector2.RIGHT, or (1, 0), in radians.`
Or that it refers to both.

**Comment by hoontee** [comment]
> > `Returns this vector's angle relative to Vector2.RIGHT, or (1, 0), in radians.`
> Or that it refers to both.

The inclusion of `(1, 0)` already implies the X axis, I feel.

**Comment by Meriipu** [comment]
I would be more confused if it said `Vector2.RIGHT` than if it said X-axis.
