### ISSUE TITLE
Loading multiple scenes with thread create wrong mesh problem

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#40954]
**Godot version:**

3.2.2

**OS/device including version:**

Mac 10.15.3
Windows 10

**Issue description:**

When loading multiple scenes with thread, sometimes an empty mesh is created in ready() of the scene.
The first time you press the button in sample project's main scene, you'll get an error in the console.
```
[Error]
 mesh_surface_get_primitive_type: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
```
But after that, pressing the button will no longer give you an error, as if the cache has been resolved.
I've heard that thread loading will be improved in 4.0, will this issue be resolved as well?

**Steps to reproduce:**
Run and press button in sample project (bg_mesh.zip) main scene.
<img width="1320" alt="スクリーンショット 2020-08-02 5 03 03" src="https://user-images.githubusercontent.com/61938263/89109577-78265500-d47d-11ea-938a-375cc17b2893.png">

**Minimal reproduction project:**

[bg_mesh.zip](https://github.com/godotengine/godot/files/5011691/bg_mesh.zip)

**Comment by TokageItLab** [comment]
The sample project updated. If make waiting in main thread after wait_to_finish() and before add_child(), loaded scene's mesh is created correctly (sample scene button right). But I think that's an odd behavior that is not accurate.

[bg_mesh_v2.zip](https://github.com/godotengine/godot/files/5011704/bg_mesh_v2.zip)

**Comment by Calinou** [comment]
I believe this will be resolved by https://github.com/godotengine/godot/pull/40764.

> I've heard that thread loading will be improved in 4.0, will this issue be resolved as well?

Se https://github.com/godotengine/godot/pull/36640.

**Comment by TokageItLab** [comment]
Probably this is old issue, I will post a new issue if there are more problems.
