### ISSUE TITLE
Raycast Node stops detecting collisions

### ISSUE THREAD

**Issue by xavierocampos** [godotengine/godot#40952]
**Problem found in version 3.2.2 in Windows 10.**

I was developing a project and I was having a problem with the movement of enemies that I posed in various ways until one day I decided to activate the collision forms to see what was happening on screen and it turns out that the Raycasts at a certain point and for some strange reason start popping as if they stop detecting collisions, so that's where the problem really was, that the Raycasts stop working.

There's no need to share code because it's not the code, but at some point and for some strange reason, they just stop working.

Here I share some screenshots, first when you start the game, everything is fine, you can see how the Raycasts are in red and work properly.

![image](https://i.ibb.co/Sn3T7cv/capture-1.jpg)

But as soon as things start to happen on screen, it starts that popping and it doesn't detect collisions anymore.

![image](https://i.ibb.co/QvSHgn0/capture-2.jpg)

The ones below are normally not detecting collisions, but notice that the enemies on the top row should detect them and no longer do.

I share with you an example project so you can review it, with the visible collision forms move with the direction keys of the keyboard and shoot the ball with the space key, you will see how the calculations of the Raycasts are broken at some point and they stop working.

[Test Project](https://github.com/xavierocampos/test-project)

**EDIT:** I found the problem. It's not when anything happens, but one thing in particular: When the ball moves.

The ball is not a RigidBody (I don't like the behaviour of physics very much and it's difficult to adapt it to my tastes) but a KinematicBody that moves with move_and_collide, I've been looking for and correcting myself if I'm wrong but I've researched and read other people who indicate that when they have a Raycast touching the ground while moving the node with move_and_slide or move_and_collide the Raycasts start giving wrong behaviours, that's when I said "it's true! the ball moves with move_and_collide!"

I just tried a RigidBody and indeed, the fault does not occur. Anyway, it wasn't just about fixing the problem in my project, but about fixing the problem in Godot in general because after that I think I can say that we are actually facing a pretty important problem.

**EDIT 2:** New correction, it keeps happening even if you put the ball as RigidBody, it happens less, but it keeps happening because finally the player is a KinematicBody and it moves with move and slide... I definitely think this problem is a mess...

**Comment by girng** [comment]
Might help with an example project so devs can trigger it and fix it

**Comment by xavierocampos** [comment]
> Might help with a tiny example project so devs can trigger it and fix it

I have the project somewhat advanced, I'm going to prepare a primitive version of the project where you can appreciate the error so you can have it as a reference. I'm talking about the lack of knowledge but I have the suspicion that the problem comes from the amount of Raycasts that are on the screen simultaneously and the problem is not solved by activating and deactivating the Raycasts at the right time, on the other hand if there are only 2 or 3 enemies as I say it works perfectly, that's for sure, as long as they are 2 or 3 from the beginning because if from the beginning there are many and they are reduced to 2 or 3, once the Raycasts start to fail they don't work correctly again in the course of the game.

**Comment by Calinou** [comment]
Can you reproduce this in any earlier Godot versions such as [3.2.1](https://downloads.tuxfamily.org/godotengine/3.2.1/), [3.2](https://downloads.tuxfamily.org/godotengine/3.2/) and [3.1.2](https://downloads.tuxfamily.org/godotengine/3.1.2/)?

**Comment by xavierocampos** [comment]
Yeah, I actually forgot to mention that. I tried it in version 3.0.6 (to be tested) and obviously it didn't open the project in this version, but it did from version 3.1.2 and the problem persists although at least the inconvenience is already located: The Raycasts are not good friends of the KinematicBodies who make use of the move and collide / move and slide methods and it seems that this is happening since several versions back.

**Comment by xavierocampos** [comment]
@Calinou It's not about reporting a problem with my project, it's about reporting a problem with Godot, if the Issue is closed it won't have visibility and they won't even try to review it. It must be open so that it can be seen and reviewed, that's why I uploaded the project.

**Comment by xavierocampos** [comment]
@akien-mga An apology for being insistent but if I don't insist, you won't see the problem and I think it's an undetected problem but one that you can check when you download the project I uploaded. I have tried several solutions but the problem is always the same: The Raycasts don't work in certain cases, as they don't detect the collision because of that "popping" the collision returns false and I can keep going over it to change the condition and force it to require a true, but it's not about solving the problem in my project, but that the Raycast nodes work correctly so that I don't have to resort to tricks, because honestly and after so much time thinking about it until the failure is detected, I have even considered the idea of redoing the project with Unity because it is complicated to deal with failures that escape my hands (since I am not an expert and I cannot solve engine problems on my own).

**Comment by akien-mga** [comment]
CC @madmiraal
