### ISSUE TITLE
Editor Crashes when trying to complete _init().() on subclass

### ISSUE THREAD

**Issue by brainDOA** [godotengine/godot#40965]
Apologies if this post is janky, was told to submit this bug from the discord server and new to github.
**Godot version:**
Godot 3.2.2 Stable

**OS/device including version:**
tested on two PCs
Device 1: W10, gtx 1080, 16gb RAM i7-7820HK
Device 2: W10, integrated graphics, 6gb RAM, Ryzen 3
**Issue description:**
Was setting up a basic inheritance system, when the child class would crash while filling out _init().(variable_here,var_two):
   note, I had prewritten _init.().(): which seems to be the root cause 

**Steps to reproduce:**
first, Parent script:
var charName : String
var attack : int
func _init(baseName = "placeholder", baseAtk = 1):
  charName = baseName
  attack = baseAtk

second (ideally), Child script:
extends "res://Assets/charTemp.gd"

func _ready():
  pass

func _init().("Hunter", 5):

what happens, however, is
func _init().("Hunter",):
after adding the comma, Godot will freeze up and crash.

However, I did find that if I don't have ): written in before filling out the second set of parentheses, then it works fine.
**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/5012028/New.Game.Project.zip)

**Comment by pouleyKetchoupp** [comment]
Confirmed in 3.2.2, seems fixed in 3.2.3.rc3.

**Comment by akien-mga** [comment]
Closing then.
