### ISSUE TITLE
Modifying an Area2D's shape size emits area_exited and area_entered for all contained areas

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot#40960]
**Godot version:** 3.2.2 Stable Mono 6a9fbafcb

**OS/device including version:** Manjaro Arch Linux 5.4.44-1-MANJARO

**Issue description:**
Changing the size of the shape in an Area2D causes the Area2D to emit both area_exited and then area_entered when the area's containing areas (and I suspect other CollisionObjects, but I've yet to test that) may not actually change.

Perhaps this is expected behavior, in which case I believe it should be moved to a docs issue.

**Steps to reproduce:**
Create a project with two Area2Ds setup (enable Visible Collision Shapes under Debug to ease visibility)
Connect to area_entered with a line containing `print("entered")` and connect to area_exited with a line containing `print("exited")`
Script the connected Area2D's shape to grow to encompass the second Area2D when the game starts

**Minimal reproduction project:**
[Area2D_size_test.zip](https://github.com/godotengine/godot/files/5011719/Area2D_size_test.zip) 
Q to shrink the orange selector box, E to enlarge the orange selector box

**Comment by hoontee** [comment]
This is expected behavior. You should instead change the `scale` property of `Area2D`.

**Comment by Spartan322** [comment]
Ah nevermind, I thought I had tried scaling an Area2D before and had it fail, thought I read somewhere scaling didn't work properly for Area2Ds.
