### ISSUE TITLE
Exporting a project does not save or even prompt you that there are unsaved changes

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#40963]
I have searched for previous bugs with similar text.

**Godot version:**
3.2.2 stable

**OS/device including version:**
linux

**Issue description:**
If you have any unsaved changed (e.g. project settings), selecting Export does not auto-save or even a prompt to warn you there are unsaved changes. You would expect either the same behaviour as 'run' or at least a prompt warning you before showing the export dialog.

I know, because I spent a while debugging a fault and it was simply I had changed my project stretch mode :)

**Steps to reproduce:**
1. make a change to the game or the project
2. select export
3. Note, this was for html, I presume the same for other exporters

**Comment by AlphaOneProject** [comment]
Hello, 
I'll try to solve this issue.

I think a prompt asking if it needs to apply or drop unsaved changes (or cancel the action) might be a good answer to this.

Please tell me if you have any other idea ^^

**Comment by chucklepie** [comment]
I don't. I'd love to help out more, but works take me forever to get up to
speed.

**Comment by AlphaOneProject** [comment]
This should hopefully resolve this issue.
And don't worry, making a clear and argumented issue like you did is already helping a lot! :D

If you have any remarks or if you think the pull request doesn't solve the issue in a satisfying way, don't hesitate ^^

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3605, as feature proposals are now tracked on the Godot proposals repository.
