### ISSUE TITLE
Ability to change user data path in Project Settings

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4097]
I think it makes sense to be able to change the user data path (where `user://` points to) in the Project Settings, ideally per-OS.

Something like:
- Windows User Data Path
- Linux User Data Path
- OS X User Data Path
- Android User Data Path

**Comment by bojidar-bg** [comment]
:+1: Even better, move this to export settings.

**Comment by Calinou** [comment]
> :+1: Even better, move this to export settings.

User data is also used when running from the editor, so those settings should probably be in the Project Settings.

**Comment by bojidar-bg** [comment]
@Calinou ~ I mean `export.cfg`, since this is per-platform, and shouldn't really by in project settings....

**Comment by akien-mga** [comment]
Superseded by #13236 which has implementation details (sorry, forgot to look for this one before writing it :)).
