### ISSUE TITLE
Move community health files to a `.github` repository in this organization

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#40972]
This is more of a misceallenous reminder, but we should move files such as `.github/FUNDING.md` and `CODE_OF_CONDUCT.md` to a repository called `.github` in the @godotengine organization. (The repository in question needs to be created first.)

This way, it will be used automatically in all @godotengine repositories. See [github/.github](https://github.com/github/.github) for an example.

Speaking of which, we should probably have a security and responsible disclosure policy in `SECURITY.md` as well. We can also add a `SUPPORT.md` file that points to https://godotengine.org/community.

**Comment by fire** [comment]
I don't understand, will this remove the files from the git repository? Isn't that the opposite of what we want?

**Comment by Calinou** [comment]
@fire We would remove the files from *this* repository and add them to a new, "common" repository that will apply to all repositories in the @godotengine organization (godot-docs, godot-proposals, …).

**Comment by fire** [comment]
What happens when someone forks the repository? Don't we want the files in every single repository so they're standalone?

It's like writing your name on a document, compared to putting your badge on the document.

**Comment by Calinou** [comment]
@fire People will still be able to open pull requests against the `.github` repository.

**Comment by Calinou** [comment]
I made a repository with the required files here: https://github.com/Calinou/godot-community-health-files

Feel free to open pull requests against that repository directly if things need to be modified. Once this is approved, we can take the repository's contents and move them over to the @godotengine organization.

**Comment by akien-mga** [comment]
How does it then work? Would it be added as a submodule?

AFAIK we can't then have the GitHub Actions `workflows` folder versioned here within a submodule, and it doesn't make sense to make the godotengine/godot actions part of a separate repo, as they don't apply to other repos.

**Comment by akien-mga** [comment]
> How does it then work? Would it be added as a submodule?

Ah I read https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file, it's all automatic when there's a `.github` repo, we'd just remove the files from the `.github` folder that we want to default to the ones from the `.github` repo.

Seems good to me, feel free to move https://github.com/Calinou/godot-community-health-files to `godotengine/.github` and PR the removal of the redundant files.
