### ISSUE TITLE
Main scene is cached when checking out git branch

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#40979]
**Godot version:**

<img width="586" alt="Screenshot 2020-07-31 at 13 22 09" src="https://user-images.githubusercontent.com/100964/89011840-d7c31a00-d330-11ea-9496-e10e781ede03.png">

**OS/device including version:**
<img width="332" alt="Screenshot 2020-07-31 at 13 22 21" src="https://user-images.githubusercontent.com/100964/89011860-e01b5500-d330-11ea-94b0-bd9e4b69a36a.png">

**Issue description:**
I `git reset --hard {some_commit_hash}` where I had changed my main scene file. Godot seems to have cached the main scene file internally, and when opening, I noticed a change in my git history, as well as Godot complaining that the main scene file no longer existed.

**Steps to reproduce:**
1) Set main as `MainScene.tscn` (not important what, this is initial commit)
2) `git commit`
3) Create new scene `DidNotExistBefore.tscn`
3) Change main scene to the new scene (project-settings -> run -> main scene)
4) `git commit`
5) `git reset --hard {initial_commit}`
6) Restart godot and select the project

Godot will complain that the main scene file `DidNotExistBefore.tscn` is missing, even though the `project.godot` should be read at startup, and should select `MainScene.tscn`.

From my perspective it seems like Godot is using a cached version of the `project.godot` rather than loading it from the filesystem. Indeed, it seems to make changes to the `project.godot` as in my git tree, changes are present after re-opening the project in Godot.

This also happens when quitting Godot entirely, rather than simply to the project selector.

**Comment by qarmin** [comment]
It is cached in `~/.config/godot/projects/` on Linux and probably similar folder on MacOS.

**Comment by tavurth** [comment]
That's a pain, as it makes `git bisect` very difficult when searching for performance regression.

**Comment by Calinou** [comment]
@tavurth You could remove that folder every time you start the engine during a bisection. It should take less than a second to do :slightly_smiling_face:

**Comment by tavurth** [comment]
Yep that seems to work, although my files were stored under:

`~/Library/Application Support/Godot/projects`

Seems like there is some variance with this bug as well, as when trying a bisection just now the editor would only sometimes cause changes to the git tree after I deleted the `projects` folder only the first time.

**Comment by tavurth** [comment]
Unfortunately removing the `~/Library/Application Support/Godot/projects` no longer fixes this bug on OSX.

I have a project where I loaded an older version of the `project.godot` and the editor will not open the project from that state. Have tried:

- cleaning `~/Library/Application Support/Godot/projects`
- cleaning `~/.config/godot/projects/`

Without luck

**Comment by tavurth** [comment]
@Calinou this is fixed in 3.4.2, now the scene asks to reload 👍
