### ISSUE TITLE
Broken building for macosx

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#40988]
**Godot version:**

Godot 3.2.3-rc (23b553ba06)

**OS/device including version:**

MacOSX 10.15.5 (19F101)

**Issue description:**

I updated my local repo from upstream and can not build godot now. It shows:
```
scons: Reading SConscript files ...
Building for macOS 10.9+, platform x86-64.
TypeError: 'encoding' is an invalid keyword argument for this function:
  File "/Volumes/Work1/projects/godotframework/godot32/SConstruct", line 520:
    methods.update_version(env.module_version_string)
  File "/Volumes/Work1/projects/godotframework/godot32/methods.py", line 89:
    head = open(os.path.join(gitfolder, "HEAD"), "r", encoding="utf8").readline().strip()
```

```
% scons --version
SCons by Steven Knight et al.:
	script: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
	engine: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
	engine path: ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/scons/SCons']
```

```
% python --version
Python 3.8.5
```

I tried to change python version to 2.7.18. It shows the same error.
May be I should update scons or something else?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Make sure SCons is being run by Python 3, not Python 2.

To ensure this, you can edit the path returned by the `which scons` command and replace the shebang on the first line.

**Comment by DrMoriarty** [comment]
@Calinou  Thank you!
