### ISSUE TITLE
mac osx "Unable to initialize Video driver"

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#40983]
**Godot version:**

I'm using the latest master branch

**OS/device including version:**

macOS Catalina (Version 10.15.6)

I am using a 2016 MacBook Pro which has:
Intel HD Graphics 530, Metal: Supported, feature set macOS GPUFamily2 v1
AND
Radeon Pro 450, Metal: Supported, feature set macOS GPUFamily2 v1

**Issue description:**

Godot Loads with the error:
"Unable to initialize Video driver"
"Your video card driver does not support any of the supported Metal versions."

It looks like the problem is in 
VulkanContext::_create_validation_layers

vkEnumerateInstanceLayerProperties returns success, but instance_layer_count = 0 so returns ERR_CANT_CREATE.

Should godot be able to run on my 4 year old mac? If so is there anything I can do to help get it working?

Edit:
I tried downloading the vulkan SDK and running vulkaninfo and it gives me this:

$ ./vulkaninfo 
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /tmp/macos-sdk-build/Vulkan-Tools/vulkaninfo/vulkaninfo.h:640:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER

would this be of any help: https://github.com/KhronosGroup/MoltenVK ?

**Comment by clayjohn** [comment]
This has been reported before and the solution is explained in that issue. https://github.com/godotengine/godot/issues/40682

It appears to be an issue with the way MoltenVK is packaged. Please see the linked issue for the solution.

**Comment by supagu** [comment]
Oh thanks! Closing
