### ISSUE TITLE
Can't drag child nodes if base node of scene is a Popup node

### ISSUE THREAD

**Issue by Bonkuraazu** [godotengine/godot#4098]
in version 2.01stable 64bit windows10

If you make the base node of a scene a Popup node, it seems that you can't drag it's child nodes with your mouse. You can still change the size of the node with the mouse, but you can't change its position. You can also still change the child nodes' positions by editing their values. This only happens if the popup node is the base node of the scene, so if it were a child of a node you could still drag its children normally.

To reproduce, create a new scene and make the base node a Popup node. Then make any kind of child node and see if you can change its position by mouse.

**Comment by neikeq** [comment]
I can confirm this, but I am not sure if this is the expected behaviour or a bug. Here is a tip: you can select the node in the _SceneTree_ panel and drag it with the **Alt** key pressed.

**Comment by Bonkuraazu** [comment]
ah, thank you! Not sure why you would have to do this only for certain base nodes though. So far I've  found you only have to do this for all Popup nodes, so I'll change the title.

**Comment by reduz** [comment]
I can't really reproduce this.. how do you do it?

**Comment by neikeq** [comment]
I can't reproduce this any longer. This was probably already fixed. @Bonkuraazu feel free to re-open if you still can reproduce it (if that's the case, an example project would be very helpful).
