### ISSUE TITLE
TileMap Placement preview is innacurate if the TileMap has rotation or negative scale

### ISSUE THREAD

**Issue by threethan** [godotengine/godot#40984]
**Godot version:**

v3.2.2.stable.official

**OS/device including version:**

Windows 10 v2004 (build 19041.388)
Ryzen 5 3600
R9 290 4GB, Radeon software v20.7.2 (release: 7/11/2020)

**Issue description:**

When placing tiles on a tile map with rotation or a negative scale, the placement preview (translucent image of the tile to be placed) is inaccurate.
When placed, tiles display as expected. The expected behavior is for the placement preview to match the transform of the tile when placed.

If the tile map is rotated, the preview will not be rotated to match.
![image](https://user-images.githubusercontent.com/12588584/89153160-5f2bab80-d532-11ea-88a5-a8512887d94f.png)
_A placed tile can be seen under the un-rotated preview_

If the tile map is scaled, the preview *will* be scaled to match, but will not be positioned correctly.
![image](https://user-images.githubusercontent.com/12588584/89153323-a44fdd80-d532-11ea-8979-649c599b14a8.png)
_The placed tile is again correct, but the preview is displayed on the top of the tile below the one currently selected_

**Steps to reproduce:**
1. Create a tile map in a 2D scene
2. Assign it any tileset
3. Apply a transform to the tile map that has either: 
- a negative x and/or y value in its scale
- any rotation
4. Go into edit mode on the tile map, select a tile to add, and move the mouse into the viewport
The tile placement indicator will now be incorrect

**Minimal reproduction project:**

[TileMapError.zip](https://github.com/godotengine/godot/files/5014280/TileMapError.zip)

**Comment by mrushyendra** [comment]
Seems like `draw_texture_rect`/`draw_texture_rect_region()` is used, which will not take into account the transform:

https://github.com/godotengine/godot/blob/ec678c5e94ac1c91c099c15fabc398e80ede7bfe/editor/plugins/tile_map_editor_plugin.cpp#L895-L899

Will make a PR soon to take that into account.
