### ISSUE TITLE
Godot Mono Connecting Callbacks in C#

### ISSUE THREAD

**Issue by CodeEasyYT** [godotengine/godot#40997]
**Godot version:**
3.2.2.stable.mono

**OS/device including version:**
No need for this issue.

**Issue description:**
On Godot Mono, connecting callbacks from other nodes just work fine.
But in C#, the function generates outside of the class, which result an error.
Like this,
```
using Godot;
using System;

public class ReturnToTitle : Node2D
{

}

private void _on_Back_pressed()
{

}
```
It's easy to fix but still can be automated.

Can you make a way that results like this,
```
using Godot;
using System;

public class ReturnToTitle : Node2D
{
	private void _on_Back_pressed()
	{
		
	}
}
```
instead of that.

**Comment by Calinou** [comment]
Are you using an external editor? The **Make Function** option is said to do nothing when using C#: https://github.com/godotengine/godot/issues/23208
