### ISSUE TITLE
Docs in Godot: text visuals and selectable/clickable regions are misaligned [regression from #39164]

### ISSUE THREAD

**Issue by tom-jk** [godotengine/godot#41006]
**Godot version:**
last working: 3.2.1
first broken: 3.2.2
broken in 3.2.3.rc3

**OS/device including version:**
Linux Mint 18.3. GeForce GTX 750 Ti, driver: nvidia 384.130
Dual monitor vertical setup, 1440x900

**Issue description:**
The actual clickable position of text and links in the docs becomes offset from their visual position.

**Steps to reproduce:**
Try selecting text or clicking links in docs inside Godot.
Also try adjusting the window size, or resizing or toggling script panel.

![GodotBug_DocOffset](https://user-images.githubusercontent.com/64640811/89215551-c5f7a600-d5c0-11ea-9366-bf4d357fe10c.png)

Video (length 1m38s): https://youtu.be/C0n48jMRRpg
0:00-0:34 - working in 3.2.1
0:35-1:38 - broken in 3.2.2

**Comment by akien-mga** [comment]
Might be worth bisecting to identify which commit caused the regression. This can be started by testing beta/RC builds of 3.2.2 to see which one is the first bad one: https://downloads.tuxfamily.org/godotengine/3.2.2/

**Comment by akien-mga** [comment]
The issue seems to start with 3.2.2 beta 4. Still reproducible in 3.2.3 RC 5.

Changes between 3.2.2 beta 3 (good) and beta 4 (bad): https://github.com/godotengine/godot/compare/b6c551e8646bedde0f81ac3a4f61f9709e82668d...aeb5513babbb1840c4c210bd534a2c2bf3b4400f

I'll try a bisect later.

**Comment by akien-mga** [comment]
Bisected the regression to c1f6854adaf7c34b49848d401675369a60135cff (#39164), CC @theoway @pouleyKetchoupp.

**Comment by pouleyKetchoupp** [comment]
Just opened #41971 to fix the regression.
