### ISSUE TITLE
Android buttons shown in immersive mode

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#41013]
**Godot version:**

Godot 3.2.3.rc (23b553ba06)

**OS/device including version:**

MacOSX 10.15.5 (19F101)
Android 8.1

**Issue description:**

My game uses immersive mode. In godot 3.2.2 all was ok. In godot 3.2.3.rc in the bottom of view there are visible android soft buttons.

![Screenshot_2020-08-04-09-49-46-413_free games match three puzzle galactic adventure android](https://user-images.githubusercontent.com/1177068/89262582-75bc2a80-d638-11ea-8364-123b7b4f4701.jpg)
**Steps to reproduce:**
Run any game with immersive mode.

**Minimal reproduction project:**

**Comment by DrMoriarty** [comment]
If I press "back" soft button the buttons will disappear. But in this case I don't able to edit any text. When I activate LineEdit the keyboard don't appear.

**Comment by DrMoriarty** [comment]
I checked on history, the first time when the issue appeared is after this PR #40672

@pouleyKetchoupp Could you help to fix it?

**Comment by pouleyKetchoupp** [comment]
@DrMoriarty Yes, thanks for the ping. I'll make sure this issue will be fixed as part of #40944. I still need to work on a few more things but it's almost ready.

**Comment by DrMoriarty** [comment]
@pouleyKetchoupp Thank you!

**Comment by akien-mga** [comment]
#40672 was reverted, so this should have been fixed.
