### ISSUE TITLE
Inconsistent behavior of draw_line function

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#41023]
**Godot version:**
3.2.2, 4.0

**OS/device including version:**
Any

**Issue description:**
I wanted to fix #35384, but I ran into the fact that `draw_line` seems to behave incorrectly too.

- If I draw 1 pixel, then it is important that the second vector does not coincide with the first.
- If I draw a horizontal (or vertical) line 1 pixel thick, it doesn't matter.
- If the thickness is greater than 1, then it is important.
- I have not tested the sloped lines.

**Steps to reproduce:**
```gdscript
func _draw():
    draw_line(Vector2(00, 00), Vector2(00+1, 00+1), Color.red)
    draw_line(Vector2(20, 00), Vector2(20+0, 00+0), Color.blue)
    
    draw_line(Vector2(00, 10), Vector2(00+8, 10+0), Color.green)
    draw_line(Vector2(20, 10), Vector2(20+8, 10+1), Color.yellow)
    
    draw_line(Vector2(00, 20), Vector2(00+8, 20+0), Color.cyan, 2)
    draw_line(Vector2(20, 20), Vector2(20+8, 20+1), Color.pink, 2)
```

![image](https://user-images.githubusercontent.com/47700418/89303333-bb96e400-d674-11ea-94a7-32d9d9af4128.png)

**Minimal reproduction project:**
[draw_line_bug.zip](https://github.com/godotengine/godot/files/5022491/draw_line_bug.zip)

**Comment by dalexeev** [comment]
I tried to repeat these commands manually with given coordinates in KolourPaint. Here's what happened:

![kolourpaint](https://user-images.githubusercontent.com/47700418/89309720-724a9280-d67c-11ea-9ef0-98d48a805922.png)

Of course, KolourPaint is not an absolute authority, but the overall result is more logical. (Why the result is not the same as in the following figure, I don't know.)

![image](https://user-images.githubusercontent.com/47700418/89311358-8db69d00-d67e-11ea-90bb-c3de1b8a4d37.png)

**Comment by clayjohn** [comment]
Can you try it with pixel snap on? Also offsetting positions by 0.5 might help. E.g. try:
```
draw_line(Vector2(0.5, 0.5), Vector2(0.5+1, 0.5+1), Color.red)
```

Godot isnt a pixel art application. It uses the GPU to rasterize lines rather than drawing them pixel by pixel. So some differences are accepted and natural. Try the above tips and let me know how it goes.

**Comment by dalexeev** [comment]
'Use Pixel Snap' has no effect on this behavior.

> Also offsetting positions by 0.5 might help. E.g. try:
> 
> ```
> draw_line(Vector2(0.5, 0.5), Vector2(0.5+1, 0.5+1), Color.red)
> ```

No. You probably don't quite understand what I mean. :smiley: 

> It uses the GPU to rasterize lines rather than drawing them pixel by pixel.

It doesn't matter **how** Godot draws the line. The problem is a strange and ambiguous coordinate system.

> So some differences are accepted and natural.

Why then does `draw_rect(Rect2(x,y,w,h), Color.blue)` always draw the rectangle exactly as expected?

**Comment by clayjohn** [comment]
> Why then does draw_rect(Rect2(x,y,w,h), Color.blue) always draw the rectangle exactly as expected?

Because GPUs handle lines and rects differently. For clarity, Godot doesn't handle drawing the line. It just passes the info off to the GPU to draw. So we need to work around how the GPU chooses to draw the line.

**Comment by kleonc** [comment]
@dalexeev, that's how lines from your example would look before rasterization:

![Godot_v3 2 2-stable_win64_bihGMQn2KY](https://user-images.githubusercontent.com/9283098/89351109-9aa0b400-d6b1-11ea-8787-9266db423809.png)

Here's your a little expanded project:
[draw_line.zip](https://github.com/godotengine/godot/files/5025025/draw_line.zip)

I don't see inconsistency in here.

**Comment by dalexeev** [comment]
@kleonc Thank you, now I understand. The coordinates are the vertices of the grid, not the cells. @clayjohn was right.

This information should be documented. Also, we should probably create a similar function that works with pixel coordinates.

**Comment by bojidar-bg** [comment]
In HTML5 canvas, a trick I've seen for working in pixel coordinates is to add `Vector2(0.5, 0.5)` to all coordinates.

Not that this trick works in Godot..
![image](https://user-images.githubusercontent.com/5276727/89388810-33b0e880-d70d-11ea-8656-8fbf74a0b91e.png)

I also tested some slight variations, such as subtracting (instead of adding) the same offset from the top-left point of the line, computing the offset based on the direction of the line, etc. They didn't quite work out, however.

**Comment by dalexeev** [comment]
> In HTML5 canvas, a trick I've seen for working in pixel coordinates is to add `Vector2(0.5, 0.5)` to all coordinates.
> 
> Not that this trick works in Godot..

@bojidar-bg I think the point is that you also need to take into account the direction (angle of inclination) of the line.

**Comment by dalexeev** [comment]
This difference in coordinates seems to be the cause of the bold lines in 4.0.

![](https://user-images.githubusercontent.com/47700418/90239335-feed1180-de2f-11ea-9df2-385983d82014.png)

**Comment by dalexeev** [comment]
The problem with thick lines can be solved simply, just add the missing coefficient 0.5 in line 472:

https://github.com/godotengine/godot/blob/5100bb42ae92feff9d68d3ef080938980e666bbc/servers/rendering/rendering_server_canvas.cpp#L471-L477

But I still don't understand why the green line is drawn 1 px higher.
