### ISSUE TITLE
 The "SearchPaths" parameter has an invalid value

### ISSUE THREAD

**Issue by Burnout156** [godotengine/godot#41021]
**Godot version:**

3.2.1

**OS/device including version:**

Windows 10 Pro x64

**Issue description:**

Project "Fighting For Justice.sln" (Build target (s)):
Message: Compiling the "Tools | Any CPU" solution configuration.
"Fighting For Justice.csproj" project (default destinations):
C: \ Program Files \ Mono \ lib \ mono \ msbuild \ 15.0 \ bin \ Microsoft.Common.CurrentVersion.targets (2101,5): error MSB3248: The "SearchPaths" parameter has an invalid value "D: \ Projects \ Fighting for Justice.mono \ assemblies \ Debug \ .winmd ". Illegal characters in path. [D: \ Projects \ Fighting for Justice \ Fighting For Justice.csproj]
Ready build project "Fighting For Justice.csproj" - FAIL.
Ready build project "Fighting For Justice.sln" - FAIL.
[Fighting for Justice.zip](https://github.com/godotengine/godot/files/5022496/Fighting.for.Justice.zip)

**Steps to reproduce:**
Play...

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Please use English to report bugs (I can sort of get by because I know Spanish and Portuguese is similar, and at least one dev also knows Spanish, but that's the minority).

**Comment by Burnout156** [comment]
There is my update for english

**Comment by akien-mga** [comment]
There's something weird with the C# project files for the attached project indeed.

Using 3.2.3 RC 5, I could solve the issue by deleting all `Fighting for Future.*` files and the `Properties` folder, then opening in the editor and re-generating a C# solution. Then there was a build issue on `List<string> nomes = new List<string>();` in a script but commenting out fixed it, and then the project works fine.

**Comment by neikeq** [comment]
Closing as this seems to be the same as #36361.

**Comment by Burnout156** [comment]
> Closing as this seems to be the same as #36361.

ok, thanks
