### ISSUE TITLE
One-shot Animated Tiles of the Same Type Maintain State

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#41030]
**Godot version:**
3.2.3.rc3.mono, though I doubt it's specific to the mono build

**OS/device including version:**
Windows 10, GLES3

**Issue description:**
I attempted to make an animated tile that looks like it's "falling" off the screen, similar to how tiles in Into the Breach fall when they are "destroyed". Once a single tile has fallen, if one-shot is on for the AnimatedTexture composing the tiles with that ID, the one-shot state will be maintained throughout all tiles of that type. The AnimatedTexture should be duplicated per tile which uses it.

**Steps to reproduce:**
Create an AnimatedTexture the old way and include it in a tileset. Make a tilemap which has multiples of the animated tile, and make sure it's a one-shot AnimatedTexture. Run it. Every tile will have the state once the first one which animates is completed - they will all complete and have the same state as well, for every tile which uses the same tile id. I have a nice repro project below.

**Minimal reproduction project:**
[FallingIsometricTilesExperiment.zip](https://github.com/godotengine/godot/files/5025315/FallingIsometricTilesExperiment.zip)

**Work-around attempts**
I attempted to work around this in multiple ways, one of which is included in the above. What I realized though is the AnimatedTexture is probably a unique resource that gets loaded once and is referenced in every tile from that point. So because one finishes, the rest maintain the same finished state. To that end, I tried using "make sub-resource unique" on just about everything I could get my grubby mitts on but couldn't get any of them to work. The final work-around for this is to not use the tilemap node directly to create falling tiles, but instead a separate node which does the falling; I'm okay with that, but thought the above should not be an unreasonable usecase.

**Comment by Rubonnek** [comment]
What you can do here is create new tiles at runtime whilst duplicating the animated texture.

Replace your `World.gd` with the following:

```gdscript
extends Node2D

onready var tilemap = $TileMap

func _ready():
	var tiles = tilemap.get_used_cells()
	var tile_set = tilemap.get_tileset()
	var tile_id = len(tiles)
	for tile in tiles:
		tile_set.create_tile(tile_id)
		var duplicated_animated_texture = tile_set.tile_get_texture(0).duplicate()
		tile_set.tile_set_texture(tile_id, duplicated_animated_texture)
		tile_id += 1
		tilemap.set_cellv(tile, tile_id - 1)
		yield(get_tree().create_timer(1.0), "timeout")
```

It should work as expected.

**Comment by WolfgangSenff** [comment]
That is...quite a work-around. Alright. I still think the above should be a valid usecase, but that said, I can close this if you want, as this work-around is pretty effective.

**Comment by Rubonnek** [comment]
This is indeed a valid use case, however I'm closing this issue as it's not really a bug within the engine but rather a part of it's design.

If you would like us to follow up on this, please open a proposal at: https://github.com/godotengine/godot-proposals/
