### ISSUE TITLE
add_ios_framework always adds embedded framework

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#41037]
**Godot version:**

Godot 3.2.3.rc (23b553ba06)

**OS/device including version:**

MacOSX 10.15.5 (19F101)

**Issue description:**

I have my own editor plugin for installing system and third party frameworks in iOS export build. After https://github.com/godotengine/godot/pull/39996 all exported frameworks became embedded (even the system ones):

![Снимок экрана 2020-08-05 в 08 50 02](https://user-images.githubusercontent.com/1177068/89376601-cc893900-d6f8-11ea-9a7a-067a9547bb70.png)

In order to build the game I have to manually disable embedding for all my frameworks.

I think that embedding should be an additional parameter in `add_ios_framework`

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by DrMoriarty** [comment]
@naithar Sergey, could you help with this issue?

**Comment by naithar** [comment]
@DrMoriarty yeah `{ATTRIBUTES = (CodeSignOnCopy, )` forces Xcode to embed frameworks that uses this.
But https://github.com/godotengine/godot/pull/39762 should allow you to remove system frameworks from dependencies.

What was your workflow with this plugin before #39996? Were you embedding non system frameworks yourself?

Adding additional parameter to `add_ios_framework` might actually work for this use case.

**Comment by DrMoriarty** [comment]
@naithar 
Yes, the #39762 allows me to don't care about the system frameworks. Thanks!

The full code of my export plugin https://gist.github.com/DrMoriarty/08bf11c6d5928463dd686e7788541e88

It is pretty old however, I started it in godot2.1 age. 
My usual workflow is to copy all static frameworks and resource bundles into `res://addons/iOS` and let plugin make all dirty work. It also can process plist chunks to application Info.plist

I already tried making dynamic gdnative frameworks and it awesome! Thanks again.
I remake ApplovinMax wrapper as dynamic framework. But it more comfortable to use it's adapters and mediated SDKs as static frameworks and use them with this plugin. Especially if different projects have different set of mediations.

So for the additional parameter for `add_ios_framework` I will be very appreciated.

**Comment by naithar** [comment]
@DrMoriarty great :)

I'll look into updating ios export workflow more, once I have time. 
But I'm not sure i will be able to make into Godot 3 branch as this changes might introduce an API breaking change. On the other hand previous changes to export workflow already brought some unexpected changes =| 
Maybe adding `add_embedded_ios_framework` would work better

**Comment by DrMoriarty** [comment]
@naithar Ok, I agree that `add_embedded_ios_framework` will be good solution.

**Comment by naithar** [comment]
@DrMoriarty would you mind checking if this commit that implements `add_ios_embedded_framework` works for your case https://github.com/naithar/godot/commit/36420958afd3c2cbe26b88b2c8147bb9c6174184? 
I'll be testing it too.
