### ISSUE TITLE
get_open_scenes() should return an Array of Nodes instead of an Array of Nodes.filename

### ISSUE THREAD

**Issue by ailernx** [godotengine/godot#41035]
**Godot version:**
3.2.3.rc3

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
As in title says `EditorInterface.get_open_scenes()` method should return an Array of "root" Nodes from each scene instead of an Array of Nodes.filename.
Returning the Nodes, filenames from the open scenes is easily geted by something like that:

Assuming that EI is EditorInterface geted.
```
for i in EI.get_open_scenes():
    print(i.filename)
```
But the inverse (get Nodes from Nodes.filename) it is quite difficult (or even impossible i dont know), this will help plugins interact directly with open scenes without causing inconsistencies.

Inconsistency for example:
A plugin can decide (if scene is open) interact with scene getting the scene opened by editor and save it instead of load scene from the path and user play the project and "accidentaly" the editor save all scenes and overwite what the plugin did.

**Comment by Calinou** [comment]
This repository is intended to be used for bug reports only. Please open a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals/) repository, following the issue template there.
