### ISSUE TITLE
Show contents of dictionary type during GDScript debugging

### ISSUE THREAD

**Issue by alandao** [godotengine/godot#4103]
I use the built in debugger and dictionaries a lot in the editor. It'd save a lot of time if we were able to peek into the dictionary type while inside the debugger in order to see the contents of the dictionary.

**Comment by bojidar-bg** [comment]
:+1: ~ Though it might be even more helpful to support all kinds of object types.... like Nodes and stuff :smile:

**Comment by Srogozins** [comment]
Coming from Python background, it's annoying to not be able to inspect an object on breakpoint

**Comment by kirilledelman** [comment]
+1
Also - being able to drill deeper into object instances too. Without an ability to inspect objects that member variables point to the debugger is only a step above debugging with print statements.

**Comment by hetdegon** [comment]
I'd love to check dictionaries from the debugger as well.

**Comment by Zylann** [comment]
+1
I'm currently debugging an error I don't understand in my game, because I can't see what's inside a dictionary returned by intersect_ray...

**Comment by SchismDev** [comment]
+1, seeing key/value pairs in dictionaries as well as even Node IDs for objects while debugging would be extremely helpful and save much time and frustration.

**Comment by chanon** [comment]
+1 ... this is really important to make the Debugger actually useful.

**Comment by anneomcl** [comment]
Is there any word on this being added in 3.0? My main issue right now is not being able to examine objects from the debugger. The only thing that's slowing me down at this point.

**Comment by magyar123** [comment]
Working on it! I really dig deep into the script debugger, and the solution is not far. I can make a PR by the end of next week probably.

**Comment by magyar123** [comment]
And while I'm there maybe I'll try to make it display all kinds of objects.
BTW if we want to be able to edit not just see dictionaries, a dictionary editor has to be made, and exporting them is just (a big) step from there :)

**Comment by anneomcl** [comment]
That's good to hear! For now viewing things would be really helpful :)

**Comment by reduz** [comment]
I noted this for 3.1, as the debugger needs some rework

**Comment by akien-mga** [comment]
@magyar123 If you're looking into this, you may want to check #8206 which is likely related.

**Comment by magyar123** [comment]
Oh yeah I saw that, that's on my list too

**Comment by akien-mga** [comment]
Fixed by #8613.
