### ISSUE TITLE
Inheritance error with class_name in GDScript 2.0

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#41039]
**Godot version:**
Godot Eninge v4.0.dev.custom_build.ec678c5e9

**OS/device including version:**
All

**Issue description:**
![image](https://user-images.githubusercontent.com/1756388/89380266-6cf35380-d721-11ea-8c1a-b1f73e473fa3.png)
![image](https://user-images.githubusercontent.com/1756388/89380217-5a791a00-d721-11ea-9d5f-b010afffd7a0.png)

**Steps to reproduce:**
1) Create some script with class_name
2) Inherit another script from created class

**Minimal reproduction project:**
[godot_inheritance_issue.zip](https://github.com/godotengine/godot/files/5026592/godot_inheritance_issue.zip)

**Comment by nathanfranke** [comment]
CC @ThakeeNathees because they reported a ton of GDScript bugs after "GDScript 2.0" and this _could_ be a duplicate.

**Comment by ThakeeNathees** [comment]
not a duplicate, and seems like the parent script inheritance resolved but the base type isn't set to the child script after that.
