### ISSUE TITLE
GDScript: Compound assignment operators don't work with array elements anymore

### ISSUE THREAD

**Issue by norton-corbett** [godotengine/godot#41051]
**Godot version:**
master 6831da630f5609e1b659d65425d9da07e25df616

**OS/device including version:**
Windows 10

**Issue description:**
```gdscript
var test_number = 0
var test_array = [ 0 ]
	
test_number += 1 # fine
test_array[0] += 1 # error: Invalid operands "Variant" and "int" for assignment operator.
```

**Comment by ThakeeNathees** [comment]
seems like `if (left.is_variant() || right.is_variant()) { unsafe and continue... }` missing in #40690 I'll open a pr asap
