### ISSUE TITLE
GDScript: inferred type is used as hard type

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41064]
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
```gdscript
func _ready():
	var dynamic_type     = "string"
	var integer_type:int = dynamic_type; ## <-- invalid (should be valid)
```

**Comment by vnen** [comment]
This isn't a bug, it's correctly telling you that this is incompatible. This will give an error at runtime anyway, so it's better that you catch it in the editor.

Hard type is only for assignment so this:

```gdscript
var dynamic = "string"
dynamic = 3
```

Should still infer the type as `String` in the declaration, but should still allow the integer to be assigned.

**Comment by Sslaxx** [comment]
What error messages does it give? Sounds like it could do with being clearer if possible?

**Comment by ThakeeNathees** [comment]
the problem is that when it comes to add control flow between, we can't predict the type of the dynamic variable when it assign

the below infered dyn_var = 2 but at runtime it's node -> should be an error
![1](https://user-images.githubusercontent.com/41085900/89535830-98a33600-d814-11ea-83dc-236a75a259d1.JPG)

the below infered dyn_var = Node but at runtime it's int -> shouldn't be an error
![2](https://user-images.githubusercontent.com/41085900/89535835-9b059000-d814-11ea-837d-753f06494db5.JPG)

**Comment by vnen** [comment]
Okay, so it's an issue with inference in general. I have an idea how to fix this.

**Comment by lyuma** [comment]
Related to godotengine/godot#43503

What is the correct behavior if a variable is declared as null? If the type is unknown, must it be Variant?
