### ISSUE TITLE
GDScript: can't use get node dollar (syntax sugar) with keywords as identifier ($keyword)

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41068]
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
![Capture](https://user-images.githubusercontent.com/41085900/89509291-c2e0fd80-d7ec-11ea-965d-f04d7c205ead.JPG)

**Comment by Sslaxx** [comment]
Does it work if it's written as `var func_node = $"func"`?

**Comment by ThakeeNathees** [comment]
@Sslaxx  yeah It'll work,
`$func` isn't working because the tokenizer thinks that the `func` is a keyword instead of and identifier.
