### ISSUE TITLE
GODOT AT GDC 2016, AFTERMATH (DISCUSSION)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#4106]
What Godot can offer sponsors? What benefit sponsors receive from the investment of their funds?
Many of my friends are programmers have never heard of Godot. And when they find out about it is usually in addition to skeptical reviews, not what they say. Since open source engines are now very much and deal with every time, no no desire.
In my opinion, for the promotion of Godot need beautiful demo. And the most important living projects. And the more of them the better.
To increase community Godot would be a good idea to create a series of articles for example on artificial intelligence. Naturally all of the examples do on Godot. For AI do not need a smart graphics and many articles about AI would be interesting. If the engine is simply to promote the start of comparison unnecessary discussion where Godot may lose such engines to both Unity3D and Unrial4. But if you write about something else that will be discussed more. And advertising engine as if hidden. But this is my opinion.

**Comment by Marqin** [comment]
IMHO we should promote stuff in which Godot is very good - it's small and it's great at producing 2D mobile games. For example, my girlfriend is often enraged when she want's to install some games on her phone and they need 1GB+ space... :rage:

**Comment by Corruptinator** [comment]
Is it possible to showcase the capabilities of the Godot Engine to Educational Facilities, such as schools or universities in order to inspire students to give the game engine a try?

**Comment by ret80** [comment]
discussion failed :(

**Comment by akien-mga** [comment]
That's because GitHub is not the place for such discussions. GitHub issues are meant for developers to work on fixing bugs and discuss new features, not discuss community topics, marketing or sponsors.  We have plenty of other channels for that: http://godotengine.org/community

**Comment by Marqin** [comment]
@akien-mga no, we don't have. For this issue:
- Facebook is the best but not everyone have it and can have it.
- IRC is very bad because it's too fast and without topic.
- Q&A is bad because comments have limitations and adding answers are not good way to discuss.
Reddit is bad because it archives and blocks older threads.
- Twitter is bad, it has character limits, not everyone have/can have and it's sometimes hard to navigate in one "thread".

Please reopen.

**Comment by akien-mga** [comment]
Then use the mailing list. https://groups.google.com/forum/#!forum/godot-engine
Or the Steam forum. Or the old forum. Or the upcoming community forum.

We have enough work to do to triage thousands of issues and PRs, please don't make this bug tracker a forum.

**Comment by Marqin** [comment]
2016-03-24 10:33 GMT+01:00 Rémi Verschelde <notifications@github.com>:

> Or the upcoming community forum.
>

Send me link.

**Comment by akien-mga** [comment]
>>  Or the upcoming community forum.

> Send me link.

http://www.thefreedictionary.com/upcoming

**Comment by Marqin** [comment]
But... In this industry "upcoming" means that we have alpha/beta-passes to
give. If it's not ready for alpha we don't say about it :P
