### ISSUE TITLE
children of camera not properly updating position

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot#41063]
**Godot version:**
Godot 3.2.2

**OS/device including version:**
Linux Mint 20.0

**Issue description:**
When changing the camera position in _process(), the child nodes (UI) of the camera offset while scrolling, not keeping their position on the screen.
Even if I connect the idle-signal to a function, the child nodes don't keep their position and flicker back and forth.
It is especially apparent when exporting the project to Windows.

**Steps to reproduce:**

**Minimal reproduction project:**
file:///mnt/projs/Godot/3.2/!tests/ScreenUI.zip
Scroll the camera by moving the mouse cursor to the rims of the screen.
You can comment out _process() and uncomment _ready() and idle() to also test the idle-signal variant.

Ps:
I've set the project's resolution to a 4:3 aspect.
I wanted to only move the camera if the mouse-cursor is touching the rim of the screen, but I haven't managed to do it.
If the Window stretch mode is set to "2D" and the Aspect to "keep" in the Project Settings, it would be nice if there was a way to detect if the mouse cursor is on the rim of the screen, not just if it is outside of the rendered area.

**Comment by TheDuriel** [comment]
You should never parent your UI to the Camera. This is what CanvasLayers exist for.
