### ISSUE TITLE
GDScript: no error when there is a trailing comma in function arguments

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41066]
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
```gdscript
func f(p, ): ## <-- no errors
	print(p)

func _ready():
	f(0, ) ## <-- no error
```

**Comment by Xrayez** [comment]
When running with the [GDScript test runner](https://github.com/godotengine/gdscript-tests) for this snippet, generates this output file:
```
Parser bug: invalid inheritance.
```

**Comment by Calinou** [comment]
This may be done by design. Trailing commas in function declarations and calls make it possible to write more diff-friendly code:

```gdscript
# If we add one more argument, we have to modify only 1 line.
hello(
    "foo",
    "bar",
    "baz",
)

# If we add one more argument, we have to modify 2 lines.
hello(
    "foo",
    "bar",
    "baz"
)
```

Therefore, I would prefer this behavior to stay in :slightly_smiling_face:

**Comment by vnen** [comment]
Yes, this is intended. Many users asked for this so I added it.

**Comment by Xrayez** [comment]
I guess the problem comes from having this inline over multiple lines, but if that's difficult to solve then perhaps not worth it.
