### ISSUE TITLE
Dropdowns in editor don't close

### ISSUE THREAD

**Issue by 20PercentRendered** [godotengine/godot#41079]
**Godot version:**

v4.0.dev.custom_build.6831da630

**OS/device including version:**

Arch Linux

**Issue description:**

Clicking a dropdown and clicking another dropdown will not close the previous dropdown. You also cannot close it by clicking anywhere else. To close it, minimize the window and open it again.

**Steps to reproduce:**
1. Click a dropdown in the editor.
2. Click another dropdown, and watch as the previous one does not close.

**Minimal reproduction project:**

Any menu in the editor causes this. No project required.

**Comment by Calinou** [comment]
I can confirm this on commit 6831da630. As a workaround, you can click a non-clickable space (such as a separator or a margin) in the popup twice. The popup should then close without opening any menus.

**Comment by akien-mga** [comment]
Closing as per above comment.
