### ISSUE TITLE
Inspector curve editor needs to wrap hints

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41084]
**Godot version:**

3.2.3 rc3

**Issue description:**

![image](https://user-images.githubusercontent.com/2223172/89563872-6e557680-d81c-11ea-87f2-5435e3f7ed04.png)
(the hold Shift text is cut)

**Comment by Kartik1397** [comment]
Hi, Can I work on this issue?

**Comment by Kartik1397** [comment]
Until now I have successfully replicated it.
![godot](https://user-images.githubusercontent.com/24036721/91495696-8d559e80-e8d8-11ea-9a32-e614561c44fe.png)

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/41727#issuecomment-1173352577 for the recommended approach to solve this.
