### ISSUE TITLE
Upgrading to scons 4.0.1 breaks gradle build due to "scons.bat" reference in build.gradle 

### ISSUE THREAD

**Issue by wombatwingdings** [godotengine/godot#41099]
**Godot version:**
3.2 branch (custom build as of 6 Aug 2020)

**OS/device including version:**
Windows 10

**Issue description:**
After upgrading to Python 3.8.5 and scons 4.0.1 to comply with latest Godot "Compiling for Windows" instructions, the subsequent build failed on the gradle (Android) part:

`
C:\godot\platform\android\java>gradlew build
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> Task :lib:compileGodotNativeLibsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:compileGodotNativeLibsDebug'.
**> A problem occurred starting process 'command 'scons.bat''**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
39 actionable tasks: 1 executed, 38 up-to-date
`

The problem is caused by this [godot issue](https://github.com/godotengine/godot/issues/32270#). That "fix" appends ".bat" to the "scons" command line on Windows. There is no scons.bat in the latest version. Only scons.exe. Removing this code from build.gradle fixes the issue for me (not appending filetype to "scons" command line).

**Comment by m4gr3d** [comment]
@BastiaanOlij @Calinou Any ideas if Windows provides an utility like [`which`] to check if a binary is available prior to invoking it?

**Comment by Calinou** [comment]
@m4gr3d Apparently, there's `where`: https://superuser.com/questions/175466/determine-if-command-is-recognized-in-a-batch-file
