### ISSUE TITLE
GDScript: in signal multiple argument comma isn't consumed by the parser

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41098]
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
```gdscript
signal my_signal(arg1, arg2) ## <-- invalid

signal my_signal(arg1 arg2) ## <-- this is valid now 
```

**Comment by Sslaxx** [comment]
Invalid how? Does it cause an error? If so, what error?

**Comment by ThakeeNathees** [comment]
![Capture](https://user-images.githubusercontent.com/41085900/89640145-98667180-d8cc-11ea-9010-f011f17c1928.JPG)
@Sslaxx
