### ISSUE TITLE
Errors in renderer when assigning an empty image to TextureButton

### ISSUE THREAD

**Issue by raphipod** [godotengine/godot#41106]
**Godot version:** 3.2.2

**OS/device including version:**
- Windows 10 (Build 2004)
- Intel Integrated HD 620, Driver 27.20.100.8425
- GLES3-Renderer

**Issue description:**

![issue](https://user-images.githubusercontent.com/56308821/89658512-ee3c1900-d8ce-11ea-9e3a-8700616f003c.PNG)

If i press the highlighted [leer] (which means "empty"), I chose "New Image" on the dropdown-menu, and these errors appear in the output-tab:

GLES2:  drivers/gles2/rasterizer_storage_gles2.cpp:810 - Condition "texture->data_size == 0 && !texture->render_target" is true. Returned: Ref<Image>()

GLES3: drivers/gles3/rasterizer_storage_gles3.cpp:1101 - Condition "texture->data_size == 0 && !texture->render_target" is true. Returned: Ref<Image>()

This happens both in GLES2 and GLES3-Mode. Seems to be a driver issue.

**Steps to reproduce:**

Open a new project, in the Scene tab, add a Control-Node and add a TextureButton as a child of Control-Node. In the Inspector-tab, choose the "Textures"-dropdown menu, choose "Normal", and add a "New Image-Texture". Then, you can see a option called "Image", which is empty. If pressed, you can choose to add a image by pressing "New Image".

**Minimal reproduction project:**

[TextureButtonIssue.zip](https://github.com/godotengine/godot/files/5042140/TextureButtonIssue.zip)

**Comment by volzhs** [comment]
you can just drag and drop an image file on it.
![texturebutton](https://user-images.githubusercontent.com/8281454/89662109-90c7bc80-d90e-11ea-9960-8e25110ee3c4.gif)

is there a particular reason to do those many steps?

**Comment by pouleyKetchoupp** [comment]
As suggested by @volzhs the proper workflow is to assign an existing image file, either by drag & drop, or by selecting "Load" instead of "New ImageTexture" in the dropdown menu.

The current ux is not really beginner-friendly though so here's a possible improvement:
It would be nice to message the user when assigning an empty texture or image (probably using configuration warning) instead of errors in the renderer.

**Comment by raphipod** [comment]
@volzhs Oh god, I didn't really think of that. Thanks, this works now.
