### ISSUE TITLE
Unable to import all folders when cut-pasting project.godot to directory

### ISSUE THREAD

**Issue by Vivraan** [godotengine/godot#41101]
**Godot version:**
3.2.2-stable

**OS/device including version:**
Windows 10 Home 1909

**Issue description:**
When I initialised a new project, and cut and paste the `project.godot` file (irrespective of whether I do so for the other files and directories generated alongside it), it only imports some of the directories, and doesn't display the rest. Note that these directories are repo clones of Assetlib repos.
![image](https://user-images.githubusercontent.com/12777564/89644314-4249fc00-d8d5-11ea-8807-759b4ec70966.png)

**Steps to reproduce:**
1. Initialise new project
2. Cut and paste `project.godot` into a a folder containing cloned repos of assetlib plugins.

**Minimal reproduction project:**
Isn't trivially reproducible. Can't provide a file under 10MB. Here's a [link instead.](https://drive.google.com/file/d/1Qcux2bI98gt_Lo-cKuruaLPl4EPqF5y2/view?usp=sharing)

**Comment by fire** [comment]
Godot Engine doesn't handle when you have a top level project.godot and subfolders which also have a project.godot. 

See the following proposal for universal plugins https://github.com/godotengine/godot-proposals/issues/831.
