### ISSUE TITLE
unwanted offset added to non-square tiles in tilemap

### ISSUE THREAD

**Issue by Algorithmus** [godotengine/godot#4110]
Before using 2.0 stable, GodotEngine displays tiles like this:

![original](https://s11.postimg.org/ukt11jycj/tiles.png)

(the top one is the original tile, and the bottom one is horizontally flipped in the tilemap. The origin point is actually in the first tile rather than the middle one, but it is centered as expected anyways.)

In the stable version, it looks like this:

![stable](https://s28.postimg.org/vj05uzu3h/tiles2.png)

For some reason, an extra offset is automatically added onto the beginning of the tiles.

**Comment by akien-mga** [comment]
This is a consequence of this pull request #3204.

It improved the way tile offsets are handled when flipping tiles, but indeed as a consequence it means that tilesets from games made with Godot < 2.0 might now have issues. I think the change was good, though it has given me quite a lot of work to port levels of https://github.com/KOBUGE-Games/jetpaca to the new system.

**Comment by Algorithmus** [comment]
Okay, works now. I have to use top left instead of center and position everything manually. Center offset has become unreliable for me.
