### ISSUE TITLE
Syntax highlighting is wrong with multi line string when there is an empty line

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41120]
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
![Capture](https://user-images.githubusercontent.com/41085900/89707209-c9f14280-d989-11ea-8890-9677e1cb60a7.JPG)

**Comment by Calinou** [comment]
cc @Paulb23
