### ISSUE TITLE
Skew mysteriously appears on scenes

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41134]
**Godot version:**

3.2.3 rc3

**Issue description:**

I never set `skew` property for any 2D node, yet I see it a lot in my scenes and it has some weird ultra low value.
![image](https://user-images.githubusercontent.com/2223172/89721064-48290580-d9d9-11ea-9c18-aede82669ec8.png)
This can be some float precision issue which mistakenly saves unmodified skew.

**Comment by pouleyKetchoupp** [comment]
Looks like a duplicate of #38868.

This issue should be present only on 3.2.2 and master though, as the cherry-pick was reverted (see https://github.com/godotengine/godot/pull/38394#issuecomment-647367293).

**Comment by KoBeWi** [comment]
Closing as duplicate of #38868.

I upgraded my Godot version multiple times on this project, so it was probably a leftover from 3.2.2.
