### ISSUE TITLE
Godot does not start

### ISSUE THREAD

**Issue by moneyghost** [godotengine/godot#41141]
**Godot version:**
 Godot_v3.2.2

**OS/device including version:**
 Windows 10

**Issue description:**
When I press on the executable file, it brings up a console where only "_Godot Engine v3.2.2.stable.official - https://godotengine.org_" is written, and then it closes without starting Godot Engine.

I tried: to update the drivers, to re-download the program, to try other versions, to run as administrator and to start via console.

**Comment by Zireael07** [comment]
What is your gfx card?

**Comment by moneyghost** [comment]
> What is your gfx card?

Nvidia GTX 1050 TI

**Comment by Zireael07** [comment]
Can you run via console, adding a --verbose switch at the end of the command?

Your card should be more than capable, that means you're running into some bug... Let's hope the --verbose output helps us diagnose the issue.

**Comment by moneyghost** [comment]
i just tried to do this but the output is the same

**Comment by Calinou** [comment]
Are you running Godot in a virtual machine? Also, which antivirus program are you using?

**Comment by moneyghost** [comment]
Godot is starting on my pc and I use Avast

**Comment by moneyghost** [comment]
![Cattura](https://user-images.githubusercontent.com/61329448/89768087-6d159980-dafb-11ea-97e0-d5b09869a6bd.PNG)
today gave me this problem

**Comment by Zireael07** [comment]
Why close? Did you finally solve the problem?

**Comment by Sslaxx** [comment]
More likely he just gave up.
