### ISSUE TITLE
Godot 3.0.6 Running SUPER SLOW on raspberry pi 4, blue tint don't know how to remove

### ISSUE THREAD

**Issue by dh928** [godotengine/godot#41142]
I tried downloading Godot 3.0.6 onto my raspberry pi 4 B+, I could edit my program. But it is just so slow. I tried running the program on my laptop, and the FPS was like 3000+. But when I tried running Godot on my pi, the FPS was like 1 or 2. I really hope there is a way to boost up the FPS. 

Additionally, I tried to change the colors of my mesh instances in the scene by Create new Spatial Material >> Albedo >> change color. But everything keeps having this bluish added color to the color I want them to have. I tried going into Project Setting >> General >> Rendering >> Environment, and I changed the Default Clear Color to white, but it still has this blue tint.

Does anyone know how to solve these problems?

**Comment by Zireael07** [comment]
Clear color is the color in 2D IIRC. The blue tint is from the WorldEnvironment node, click around in it to either decrease Ambient Light intensity or change the colors.

As for the other problem, try switching to GLES 2 either in editor or by using, in the command line, --GLES2 - IIRC that should do it

**Comment by Calinou** [comment]
The 3D editor will probably be too slow to be usable on a Raspberry Pi for a while. I'm not sure if it'll ever be usable due to the sheer amount of 2D and 3D controls that need to be rendered.

**Comment by quantmint** [comment]
> I tried downloading Godot 3.0.6 onto my raspberry pi 4 B+, I could edit my program. But it is just so slow. I tried running the program on my laptop, and the FPS was like 3000+. But when I tried running Godot on my pi, the FPS was like 1 or 2. I really hope there is a way to boost up the FPS.
> 
> Additionally, I tried to change the colors of my mesh instances in the scene by Create new Spatial Material >> Albedo >> change color. But everything keeps having this bluish added color to the color I want them to have. I tried going into Project Setting >> General >> Rendering >> Environment, and I changed the Default Clear Color to white, but it still has this blue tint.
> 
> Does anyone know how to solve these problems?
Have you enabled dtoverlay=vc4-fkms-v3d in config.txt?

**Comment by dh928** [comment]
> > I tried downloading Godot 3.0.6 onto my raspberry pi 4 B+, I could edit my program. But it is just so slow. I tried running the program on my laptop, and the FPS was like 3000+. But when I tried running Godot on my pi, the FPS was like 1 or 2. I really hope there is a way to boost up the FPS.
> > Additionally, I tried to change the colors of my mesh instances in the scene by Create new Spatial Material >> Albedo >> change color. But everything keeps having this bluish added color to the color I want them to have. I tried going into Project Setting >> General >> Rendering >> Environment, and I changed the Default Clear Color to white, but it still has this blue tint.
> > Does anyone know how to solve these problems?
> 
> Have you enabled dtoverlay=vc4-fkms-v3d in config.txt?

What does that do?

**Comment by quantmint** [comment]
> > > I tried downloading Godot 3.0.6 onto my raspberry pi 4 B+, I could edit my program. But it is just so slow. I tried running the program on my laptop, and the FPS was like 3000+. But when I tried running Godot on my pi, the FPS was like 1 or 2. I really hope there is a way to boost up the FPS.
> > > Additionally, I tried to change the colors of my mesh instances in the scene by Create new Spatial Material >> Albedo >> change color. But everything keeps having this bluish added color to the color I want them to have. I tried going into Project Setting >> General >> Rendering >> Environment, and I changed the Default Clear Color to white, but it still has this blue tint.
> > > Does anyone know how to solve these problems?
> > 
> > 
> > Have you enabled dtoverlay=vc4-fkms-v3d in config.txt?
> 
> What does that do?

https://blogs.igalia.com/itoral/2020/01/17/i-am-working-on-the-raspberry-pi-4-mesa-v3d-driver/

**Comment by efornara** [comment]
As far as I know, the Raspberry Pi 4 driver doesn't support hardware accelerated OpenGL 3. It does support OpenGL *ES* 3, but that doesn't help much with Godot / x11.

It is unfortunate that the version in the official repository, just like debian stable, is Godot 3.0.6.

If you are using a Raspberry Pi 3/4, you are probably better off forgetting about Godot 3.0.6 from the official repository and compile Godot 3.2.x yourself; you can then create a GLES2 project that should be hardware accelerated.

**Comment by Calinou** [comment]
The Raspberry Pi 4 should do much better with 3.2.3 onwards ([unofficial builds here](https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi)), closing.
