### ISSUE TITLE
Built-in Scripts aren't searched through.

### ISSUE THREAD

**Issue by MJBrune** [godotengine/godot#41147]
**Godot version:** 

3.2.2

**OS/device including version:** 

Windows 10

**Issue description:**

Built-in scripts aren't searched through when using find in files from the search drop down. This means when you are renaming a variable or such you can miss scripts that have included it.

**Steps to reproduce:**
1. use
`export (Script) var interaction_script`
in a script.

2. create a "new GDScript" from that variable.
![image](https://user-images.githubusercontent.com/420072/89739587-928c9f80-da36-11ea-9763-10bd3a09a160.png)

3. write some usage of a variable you want to search for. e.g `get_parent().test_variable = true`

4. find in files the name of that variable.
![image](https://user-images.githubusercontent.com/420072/89739598-c2d43e00-da36-11ea-8c87-ca2bfa8f59b1.png)

5. notice that only gd script files are searched through and not scripts stored in tscn's.
![image](https://user-images.githubusercontent.com/420072/89739613-ea2b0b00-da36-11ea-8108-eef2657ba6c4.png)

**Minimal reproduction project:**

[instancedscriptbug.zip](https://github.com/godotengine/godot/files/5048229/instancedscriptbug.zip)

**Comment by MJBrune** [comment]
I'm not sure how the search works now and how performant it is. Maybe there can be a checkbox to search through tscn's that is defaulted off that way if you are instancing scripts like this you have the option to search through them?

**Comment by Zireael07** [comment]
Tip: they're not called instanced scripts, they're called built-in scripts. IIRC this is one of their many limitations?

**Comment by MJBrune** [comment]
Updated to built-in. Is there a list of limitations with built-in scripts? It's easy enough to save every script to a gdscript then just hit load instead but it feels like maybe a limitation that we could fix? It feels like going through every tscn file and looking for "script/source" of a sub_resource and including that content within the search system.  I think ideally any code you put into the editor shows up in the search system in order to keep things organized. I might be able to look into this.

**Comment by MJBrune** [comment]
hmm okay I see now, duplicate of https://github.com/godotengine/godot/issues/20692

**Comment by Calinou** [comment]
See also #issuecomment-629664428.

**Comment by gnat** [comment]
Solution: This is how you enable it, built-in script enjoyers rejoice.

<img width="979" height="846" alt="Image" src="https://github.com/user-attachments/assets/c36793ac-b6e1-47bf-924f-608d9aafd62c" />
