### ISSUE TITLE
Framebuffer Allocation : "2D" disabled HDR

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#41151]
**Godot version:**
3.2.2

**OS/device including version:**
GLES3, Nvidia 2080, Windows 10

**Issue description:**
Switching from Framebuffer Allocation: 3D to 2D disables HDR effects (for example the glow effect on the World Environment) when running the game (still shows in the editor)

**Steps to reproduce:**
Change Frambuffer Allocation in render settings to 2D or to 3D and have a node with RAW colors and a high hdr value, start the project.

**Minimal reproduction project:**
[bug_frambuffer_allocation.zip](https://github.com/godotengine/godot/files/5048334/bug_frambuffer_allocation.zip)

**Comment by clayjohn** [comment]
I guess more information should be added to https://docs.godotengine.org/en/stable/classes/class_viewport.html#enum-viewport-usage

To clear things up. Setting the framebuffer mode to 2D only allocates the buffers needed for 2D rendering so 3D rendering effects are not available (glow, HDR, SSAO, etc.)

**Comment by RPicster** [comment]
> I guess more information should be added to https://docs.godotengine.org/en/stable/classes/class_viewport.html#enum-viewport-usage
> 
> To clear things up. Setting the framebuffer mode to 2D only allocates the buffers needed for 2D rendering so 3D rendering effects are not available (glow, HDR, SSAO, etc.)

Thanks for the information :)
I supposed HDR wasn't a pure 3D feature.

**Comment by Yetizone** [comment]
Hello ! Newcomer here. 

I'm interested in contributing to Godot so I've submitted a PR for this issue.
Let me know if the submitted changes are alright.

**Comment by Yetizone** [comment]
Should this Issue still be Opened ? 

I've included "Fixes https://github.com/godotengine/godot/issues/41151" in the merged PR description, but it seems it didn't close this automatically. 
Strangely enough, when hovering over the "Fixes" keyword in the PR description there's even a tooltip saying it will close this. :)

**Comment by akien-mga** [comment]
> I've included "Fixes #41151" in the merged PR description, but it seems it didn't close this automatically.
Strangely enough, when hovering over the "Fixes" keyword in the PR description there's even a tooltip saying it will close this. :)

Those keywords only work when PRs are merged in the `master` branch, to prevent closing an issue that would only get fixed in a feature or maintenance branch and not in the mainline.

**Comment by Yetizone** [comment]
Ah, yeah that makes sense. 

Thanks for answering !

**Comment by Zylann** [comment]
I just got confused by this.
In my plugin I use a viewport to paint on a 16-bit texture using the GPU, however I don't need all the fancy 3D effects and buffer, I just need the framebuffer to be able to hold 16-bit data... yet I apparently can't?
So for now I let it set to 3D, probably wasting some resources there...

**Comment by Calinou** [comment]
@Zylann The performance difference between 2D and 3D framebuffer allocation is quite minimal in experience. It's mainly about RAM/VRAM usage.

**Comment by Zylann** [comment]
Except that's precisely what I'm talking about here, memory usage.

**Comment by Calinou** [comment]
The notion of viewport usage doesn't exist anymore in `master`, and I doubt support for 2D HDR is easily implementable in the `3.2` branch.

**Comment by DriNeo** [comment]
It was hard for me to figure out the default framebuffer allocation disable glow for 2D. It needs very technical knowledge to find this without help.
