### ISSUE TITLE
Vulkan layers not found

### ISSUE THREAD

**Issue by free-vbucks** [godotengine/godot#41158]
**Godot version:**
4.0 `f2149fe763a5678237b417fb9fefec5a5c74ae9d` through 4.0 `1ff139cb28137d5b1b492f74e5fc58cbeee01e4a`, currently

**OS/device including version:**
Windows 10 64-bit 1908, Intel HD 520, with the Vulkan runtime installed through my drivers, and the Vulkan SDK installed before/while/after compiling.

**Issue description:**
Godot crashed about a half second after the window showed up.
<img width="512" alt="godot vk failure" src="https://user-images.githubusercontent.com/60723221/89744160-e2d42380-da6f-11ea-9533-664774cfe84a.png">
The window, which showed up a second after the text-
<img width="512" alt="godot vk failure window" src="https://user-images.githubusercontent.com/60723221/89744539-91c62e80-da73-11ea-8897-674a35be31ab.png">
And the windows that show up when built with `target=debug` (same error in console)
<img width="514" alt="godot vk windows" src="https://user-images.githubusercontent.com/60723221/91668656-eb020a80-ead3-11ea-88a7-207a2072c9f9.png">
You can actually use the window, even when nothing shows up, which makes this a major Vulkan rendering problem.

**Steps to reproduce:**
Build Godot `master` branch on Windows. I don't know the exact issue.

**Minimal reproduction project:**
https://github.com/godotengine/godot/tree/master

**As a sidenote:**
The Vulkan Cube provided with the SDK works fine. I have found out that my drivers work successfully, and the problem is Godot's, per my knowledge.

**Comment by Francesco149** [comment]
same issue on linux on a rx 570

also trying to select vulkan display driver from the command line says

```
$ godot --display-driver vulkan
Unknown display driver 'vulkan', aborting.
Valid options are  and 'x11'.
```

**Comment by Francesco149** [comment]
actually, building with target=debug works fine, release_debug gives the blank screen

**Comment by free-vbucks** [comment]
@Francesco149 building debug gives this
<img width="514" alt="godot vk windows" src="https://user-images.githubusercontent.com/60723221/91668627-ad04e680-ead3-11ea-82be-1abe7dbe987e.png">

**Comment by free-vbucks** [comment]
It was my crappy drivers that caused the crash. Dell hasn't released new OEM drivers since 2018 for me. I used the ones on Intel's website, and they worked after I uninstalled my Dell ones. A big thanks to Intel, which had great support webpages, and an ever bigger, albeit sarcastic, thanks to Dell.

**Comment by Calinou** [comment]
@free-vbucks This is why I advise always upgrading graphics drivers from Intel directly in https://github.com/godotengine/godot-docs/pull/4058 :slightly_smiling_face:
