### ISSUE TITLE
Cannot use operator '%' for string formatting if the string is a variable

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#41161]
**Godot version:**
f2149fe763a5678237b417fb9fefec5a5c74ae9d

**OS/device including version:**
Linux Mint 20

**Issue description:**
```py
var format = "%s%s%s"
print(format % ["a", "b", "c"]) # Error
```
```py
print("%s".repeat(3) % ["a", "b", "c"]) # Error
```

**Steps to reproduce:**
Put this code in any script, or test out the MRP

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/5049115/Test.zip)

**Comment by TheDuriel** [comment]
Needs 4.0 tag, issue is in Master only.
