### ISSUE TITLE
GridMap does not support navigation meshes.

### ISSUE THREAD

**Issue by Anarchid** [godotengine/godot#4116]
Currently, a GridMap's MeshLibrary can have the following date for each of its tiles:
1) The Mesh itself, which is to be rendered
2) The collision shape for the mesh, to be used for people to bump into and walk on.

![meshlib_editing](https://cloud.githubusercontent.com/assets/3822768/13930171/6dcdfbe6-efa6-11e5-872f-273dcd2014df.png)

My problem is that i want to use a GridMap for generating a 3d maze, which should be navigated by game characters. That is not possible, because upon conversion of a Scene into a MeshLib, navmeshes for each tile are lost.

I think being able to navigate gridmap mazes is a pretty important thing to have for gridmaps as long as they exist at all, so it would be very nice to be able to attach navigation data to meshlib tiles.

Here's an example of an unfortunate situation where the GridMap simply stops sufficing, in the form of a modified navmesh demo.

![godot_mergemesh](https://cloud.githubusercontent.com/assets/3822768/13930220/c5e22cda-efa6-11e5-9625-03db8b24b52d.png)
[navmesh-vs-gridmap.zip](https://github.com/godotengine/godot/files/182903/navmesh-vs-gridmap.zip)

**Comment by kubecz3k** [comment]
Related issue: https://github.com/godotengine/godot/issues/3271

**Comment by Anarchid** [comment]
This was actually fixed for a while via https://github.com/godotengine/godot/pull/4302
