### ISSUE TITLE
GDScript: no error when assigning invalid type with subscription

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41170]
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
```gdscript
func _ready():
	var s := "Hello"   ## <-- typeof(s) = String (inferred)
	s[0] = 42  ## <-- should be invalid
```

**Comment by vnen** [comment]
Did this trigger an error in 3.2?

**Comment by ThakeeNathees** [comment]
@vnen yes here is the error:
![Capture](https://user-images.githubusercontent.com/41085900/89900914-f7e0bc00-dc01-11ea-92a4-1b75d573757d.JPG)
