### ISSUE TITLE
4.0 TextureRect Stretch Tile Render mode error 

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#41175]
**Godot version:**
4.0

**OS/device including version:**
win10

**Issue description:**
4.0 TextureRect Stretch Tile Render mode error 

![图片](https://user-images.githubusercontent.com/2855349/89792507-3a998a00-db57-11ea-8979-9f5257b92fa3.png)
project  [godottest.zip](https://github.com/godotengine/godot/files/5051658/godottest.zip)

**Comment by Calinou** [comment]
@cjmxp Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by pouleyKetchoupp** [comment]
Closing as duplicate of #40011.
