### ISSUE TITLE
Editor is blinking when saving a script

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4118]
Windows 7 64 bits, Godot 2.0.1

When I save a script with CTRL+S, the text editor blinks, showing the current scene for a few milliseconds + a progress bar popup.
This is annoying, because I use this shortcut as frequently as an end-of-line, the editor flashes a lot.

**Comment by vnen** [comment]
I guess it's because <kbd>Ctrl</kbd>+<kbd>S</kbd> saves the *scene*, so it goes to the scene tab quickly to generate the thumbnail. The shortcut to save the script is <kbd>Alt</kbd>+<kbd>Ctrl</kbd>+<kbd>S</kbd>.

**Comment by Zylann** [comment]
Oh... I think it should be context-sensitive, use CTRL+S to save what I see. Or at least, it shouldn't produce this flashing behaviour, save in background maybe?

**Comment by bojidar-bg** [comment]
:+1: for any of the two solutions

**Comment by bojidar-bg** [comment]
Close?
