### ISSUE TITLE
Tablet input firing mouse motion events when not in motion

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#41192]
**Godot version:**
3.2.3 RC3

**OS/device including version:**
Windows 10
wintab driver selected in editor
windows ink turned off in wacom tablet settings

**Issue description:**
Wacom tablet input fires mouse motion events when not in motion.  Happens with button pressed/release and hover
Video of the behavior:
[wintab_mousemotion_bug.zip](https://github.com/godotengine/godot/files/5059084/wintab_mousemotion_bug.zip)
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by HEAVYPOLY** [comment]
This is my current workaround which works fine for now:
'''func _input(event):
    if event is InputEventMouseMotion:
        if event.relative == Vector2.ZERO:
            return'''

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/66528
