### ISSUE TITLE
Array.front() and back() show an error on empty arrays

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41204]
**Godot version:**

3.2.3 rc3

**Issue description:**

```
func _ready() -> void:
	var arr := []
	print(arr.back())
```
shows
```
back: Can't take value from empty array.
```

According to the docs, it should just return null so either the error should be removed or docs should mention it.

**Comment by Xrayez** [comment]
If I find myself in a situation where I need to use those methods, I'd assume an array to contain some values. Returning `null` could already create troubles down the ~road~ script anyway, so it's alright to check whether an array is empty beforehand.

Technically it might be a correct behavior, and documentation can state that those methods could result in an actual error to be printed. But there are no exceptions handling mechanism (`try/catch`) to take advantage of this on the GDScript level (nor C++ with Godot's philosophy of "[should not crash](https://docs.godotengine.org/en/latest/development/cpp/common_engine_methods_and_macros.html#error-macros)"), so I'd just remove "or null if the array is empty" from the docs.

**Comment by KoBeWi** [comment]
Actually the only valid use for not throwing the error I can think of is something like `if e = array.front()`, which won't work in GDScript. In every other case you need additional check if element is not null, so checking for empty array is pretty much equivalent. So yeah, docs should just say that it throws error.

**Comment by sszigeti** [comment]
The current error message is rather useless, because it doesn't specify which array is empty and where. I happen to have a couple locations where I'm using `.front`, but all I can see is this:

```
E 0:00:11.470   front: Can't take value from empty array.
  <C++ Error>   Condition "_p->array.size() == 0" is true. Returned: Variant()
  <C++ Source>  core/array.cpp:155 @ front()
```

Would it be possible to enhance this error message?
