### ISSUE TITLE
3D armature import is broken

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4120]
The only case for 3D import for armatured animated meshes now is:
The tested revision is a895e2e372c9df2a9972f38134ae0ea9c8bf45a8
1. No mechanism bones in scene, no non-deforms in scene and no IK setups.
2. No morph targets on armatured meshes.

Any added detail breaks animations and produce distorted meshes or meshes fail to import.

**Comment by slapin** [comment]
So the conclusion - it is not possible to filter-out non-modifier bones.
morph + skeleton is another issue, looks like this configuration is not really tested at all.

**Comment by thirite** [comment]
I've got an FK/IK rig working fine in my project. The actual animation seems to affect the FK armature in Godot, but the animations import fine as long as I remember to put at least one key from the FK armature (normally only the IK armature is keyed) in each animation track.

**Comment by reduz** [comment]
IK setups won't get exported by any format I know. IK is planned for 3.1 and already opened in another issue (can't find it).
for the rest, it all works fine now, so closing this
