### ISSUE TITLE
Changing exported Windows Icon doesn't work

### ISSUE THREAD

**Issue by TheNeoGameFactory** [godotengine/godot#41202]
**Godot version:**
Godot 3.2.1 -> 3.2.2 tested
Classic Version (No C#)

**OS/device including version:**
Windows Export

**Issue description:**
I exported a 32x32 .ico from Gimp and add it to the export Settings "Icon" for windows export but the Icon doesn't appear.
We tested it with some of our Community Members and everyone has the same Problem, the Icon change doesn't work.
Godot Icon stays after Export.

**Steps to reproduce:**
Export a Windows Project with setting a .ico on the Icon export Settings.

**Comment by bruvzg** [comment]
Do you have `rcedit` installed and configured? See [Changing application icon for Windows](https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html) for details.

**Comment by TheNeoGameFactory** [comment]
> Do you have `rcedit` installed and configured? See [Changing application icon for Windows](https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html) for details.

Isn't it enough to Export a .ico File with Gimp?

**Comment by bruvzg** [comment]
> Isn't it enough to Export a .ico File with Gimp?

No it's not, Godot relies on external tool (`rcedit`) to modify executable and add icon and information strings.

**Comment by TheNeoGameFactory** [comment]
I will ask the Community If they has do it, because i hasn't do it 😔

**Comment by TheNeoGameFactory** [comment]
same with the Community, no install of rcedit. 
So i will Close it, because of stupid users, including me 😅

Sorry for that.
