### ISSUE TITLE
String format argument error

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#41218]
**Godot version:**
Commit f2149fe763a5678237b417fb9fefec5a5c74ae9d

**OS/device including version:**
Debian SID

**Issue description:**
Any non-string value inside an array passed to a format operator triggers a

> Parse Error: Invalid operands "String" and "Array" for "%" operator.

**Steps to reproduce:**
```
func _ready():
	var k:int=0
	print("%d %d"%[k,k])
```
This code doesn't even parse.

**Comment by akien-mga** [comment]
` func _ready(): var k:int=0 print("%d %d"%[k,k]) ` is invalid code, you can't chain statements on a single line without `;`.

**Comment by ThakeeNathees** [comment]
related issue : #41161

**Comment by vnen** [comment]
Yeah, this is the same as #41161 so it's already fixed.
