### ISSUE TITLE
GD.Randf() causes black screen in html5 project

### ISSUE THREAD

**Issue by MakovWait** [godotengine/godot#41210]
**Godot version:** 3.2.2.stable.mono

**Issue description:** usage of GD.Randf() causes black screen in html5 project. Without it all works perfectly.

**Steps to reproduce:**
1. Call GD.Randf() in any .cs script.
2. Export project with html5 template.

**Minimal reproduction project:** [randf_test.zip](https://github.com/godotengine/godot/files/5066297/randf_test.zip)

Windows and Linux exporting works as expected.

Thank you!

**Comment by mariothedog** [comment]
I can confirm this bug still occurs in 3.2.3.stable.mono.

**Comment by Calinou** [comment]
cc @neikeq

**Comment by neikeq** [comment]
Closing as duplicate of #36858 (same cause)
