### ISSUE TITLE
Feature request tilemap drawing shortcuts for whole cols and rows

### ISSUE THREAD

**Issue by hyperglow** [godotengine/godot#4122]
I would like to suggest a feature for the tilemap drawing functionality.
It would be great to draw whole rows or columns by marking the start point while holding shift key and then the endpoint. Then the tiles between those points get painted. 
Also it would be great if we could fill a previous made selection.

**Comment by akien-mga** [comment]
Those features have been implemented in the master branch already, and will be in Godot 2.1 :)

**Comment by akien-mga** [comment]
See #4006.

**Comment by hyperglow** [comment]
Wohoo. Thanks. Great News!
