### ISSUE TITLE
CPUParticles2D generate particles at a single point when running the game

### ISSUE THREAD

**Issue by osmiumforge** [godotengine/godot#41232]
**Godot version:**

3.2.1

**OS/device including version:**

**Issue description:**

CPUParticles2D generates all particles at a single point when a parent node is scale

**Steps to reproduce:**

**Minimal reproduction project:**

[CPUparticles glitch.zip](https://github.com/godotengine/godot/files/5073949/CPUparticles.glitch.zip)

**Comment by Calinou** [comment]
@osmiumforge Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by YeldhamDev** [comment]
The particle node that is a child of the scaled node has a scale of 0, changing that, the particles are emitted correctly:
![Screenshot_20200814_184354](https://user-images.githubusercontent.com/30739239/90294961-421ea300-de77-11ea-842b-564c81bb62cf.png)

**Comment by Calinou** [comment]
Closing per @YeldhamDev's comment.
