### ISSUE TITLE
Non-English keyboard shortcut problem.

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot#41237]
**Godot version:**

Godot 3.2.3.rc3

**OS/device including version:**

Macbook pro 2016 /  Turkish keyboard

**Issue description:**

I cannot use some keys and Turkish characters as shortcuts. for example command+ö , because English keyboard keys are mixed with Turkish keyboard. It takes the `ö` key as a `comma`. So since there are two commas, I have to use only one.

**Steps to reproduce:**
Try assigning one of these keys as an editor shortcut.;
ü ğ ç ö ş ı *

![o](https://user-images.githubusercontent.com/36481442/90194587-50fe4a80-ddd0-11ea-82a0-6382592aba50.gif)

**Comment by TheDuriel** [comment]
This should functionally work completely fine. The hotkeys are being mapped to the _physical_ key, not the character.

**Comment by Calinou** [comment]
> The hotkeys are being mapped to the physical (as far as the OS determines) key, not the character.

Actually, this isn't the case until Godot 4.0 which offers a "physical key" option. See https://github.com/godotengine/godot/pull/18020.
