### ISSUE TITLE
Godot closes while trying to import soundfile

### ISSUE THREAD

**Issue by hyperglow** [godotengine/godot#4123]
**Operating system or device:** Ubuntu 15.04 64bit

**Issue description** (what happened, and what was expected): Wanted to import a soundfile. While browsing my directories godot just closed without any message. Had no chance to choose a file.

**Steps to reproduce:** Import soundfile, browse directories. 

**Link to minimal example project** (optional but very welcome):

**Comment by hyperglow** [comment]
Tried with different folders. Seems to crash everywhere after a few seconds!

**Comment by akien-mga** [comment]
What kind of sound files are in those folders? Does it crash also when browsing to a folder with e.g. only scripts or PNG files, but no sound files?

What version of Godot do you use?

**Comment by slapin** [comment]
please provide backtrace or the file and what you do with it. Also the
engine version and where you got it.

**Comment by ni-code** [comment]
I'm also having problems with the sound. Sometimes the engine crash but I dint find a reliable way to reproduce it. The crashes appends(not always) when I press the play or the edit button in the sample editor.

OS: ubuntu 15.10 
self compiled from git master (c844c2d604ab7e8824659e1f6b6011039a552cbe)
![sound-issue_2016-03-22 16-23-23](https://cloud.githubusercontent.com/assets/10292929/13959249/647a88f2-f04b-11e5-9d34-d36c1ff161dd.png)

**Comment by akien-mga** [comment]
@ni-code Thanks for the confirmation. Just to rule out a potential regression from #4033, could you check if you get the same issue with Godot 2.0.1?

Also, could you upload a file that triggers such issues (or better a zipped simple project with this file already included in a scene)?

**Comment by ni-code** [comment]
@akien-mga Ok. I'll do it in the next hour or so.

**Comment by ni-code** [comment]
Tested in 2.0.1 and it works fine in there.
I've made a simple test project to reproduce the issue
· Import the project
· In the Inspector click on: SamplePlayer->Config->Samples->Edit
· Press the play button in the sample library
· Crach
[sound_issue.zip](https://github.com/godotengine/godot/files/184657/sound_issue.zip)

hope it helps.

**Comment by akien-mga** [comment]
Thanks @ni-code, that's very helpful. I tested on 2.0.1 and the current master branch, and had no issue in both cases. My guess is that you might have built the master branch without pulseaudio development libraries installed, so it doesn't find a suitable audio driver and crashes. Would that match your case?

**Comment by ni-code** [comment]
I have libpulse-dev installed. But maybe there is something on my system causing it. If I find something I'll drop a comment here.

**Comment by hyperglow** [comment]
Sorry, guys for being precise. I was in a rush.
I am using Godot_v2.0.1_stable_x11.64
I now think it might has to do with verry big wav files. I was able to import a smaller wav file wich i oput in my resource directory for tesing. After putting a bigger file into that directory it crashes again. Maybe it is caused during generation of the waveform icon? Small file is 5,3mb big file is 207mb.
Now it crashed again during the setting of the main scene which lives in the same directory. 
Ok it seems its crashing after a while after opening the project. Whithout doing anything. Shall i upload the project with a big soundfile?
