### ISSUE TITLE
Error Message "The given export path doesn't exist: exports" for Export All/Release to MacOS

### ISSUE THREAD

**Issue by adxsoft** [godotengine/godot#41246]
**Godot version:**
3.2.2 Stable

**OS/device including version:**
Mac OSX Sierra

**Issue description:**
Using Mac OSX Runnable export template 3.2.2 stable
Project -> Export ->  Export All -> Release 
Correctly creates the dmg file but produces popup that says
"The given export path doesn't exist: exports"

The created dmg file is correctly located in the export path folder

 So I get the desired outcome .. a working dmg .. but this message is strange. Not a showstopper but just confusing

Note it is an old project which I have hacked so it might be a pre 3.2.2 issue. New projects don't 

**Steps to reproduce:**
![Screen Shot 2020-08-14 at 5 49 12 pm](https://user-images.githubusercontent.com/24862237/90228045-e9401200-de58-11ea-8aaf-2120e6d81aff.png)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
What is the configured "Export Path" for all three presets?

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
