### ISSUE TITLE
can we please-please-please have wireframe on Z?

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4124]
I think it is a very good idea (please-please-please with a cherry on top) to have a shortcut on
wireframe/normal view toggle on Z key to be similar to blender, is it not?

**Comment by unfa** [comment]
Sounds like a great idea to me.

**Comment by nunodonato** [comment]
easy to do. if the bosses approve :)

**Comment by akien-mga** [comment]
As long as it doesn't conflict with another hotkey, it's fine with me.
