### ISSUE TITLE
modules/mono/mono_gd/gd_mono_utils.cpp:371 - System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by dancroote** [godotengine/godot#41259]
I am having precisely this issue, which the original person has closed since they cannot replicate it.
I am receiving the same errors as described in the console every time Godot is opened.

https://github.com/godotengine/godot/issues/39432

**Comment by Calinou** [comment]
Duplicate of #39432. (Please be more patient when requesting issues to be reopened.)

**Comment by dancroote** [comment]
Apologies, and thanks.
