### ISSUE TITLE
Loading (Collada) Model is crashing

### ISSUE THREAD

**Issue by TypeOverride2** [godotengine/godot#41253]
**Godot version:**
Latest master 4.0

**OS/device including version:**
Windows 7 tested

**Issue description:**
On editor automatic importing the model, this crash occurs:
"CRASH_BAD_INDEX" on Vector

Seems that `reasterizer_storage_rd::mesh_owner.getornull(p_mesh)` is catching the data not correctly for `rendering_server::mesh_surface_get_arrays`

on `editor_import:collada::_create_mesh_surfaces` he is crashes when he wants to dereference d
`a[Mesh::ARRAY_WEIGHTS] = d[Mesh::ARRAY_WEIGHTS];`
He would crash on next line as well:
`a[Mesh::ARRAY_BONES] = d[Mesh::ARRAY_BONES];`
i think

so something wrong with `RID_Alloc::getornull(const RID &p_rid)` class rid_owner.h i guess.

**Steps to reproduce:**
Loading a dae file with skeleton and blend shapes

[model_test.zip](https://github.com/godotengine/godot/files/5074857/model_test.zip)

(The model is working on 3.2.2. Import is working. And everyting else as well)

**Comment by Calinou** [comment]
@TypeOverride2 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by TypeOverride2** [comment]
> @TypeOverride2 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

[model_test.zip](https://github.com/godotengine/godot/files/5074857/model_test.zip)

Here. Its only a dae file i created. Make it simple. Added a skeleton. And a blend shape.

I used Blender and exporter Better-Collada-Expoter with this config:
![crash0](https://user-images.githubusercontent.com/69324102/90255572-bee45980-de44-11ea-8770-a3d0e6fdd43d.png)

But anyway. I tested it in 3.2.2 and it is imported like it should.

**Comment by Calinou** [comment]
> `editor/collada/collada.cpp:1060 - Primitive type "polygons" is not well supported (concave shapes may fail). To ensure that the geometry is properly imported, please re-export using "triangles" or "polylist".`
> `editor/collada/collada.cpp:1060 - Primitive type "polygons" is not well supported (concave shapes may fail). To ensure that the geometry is properly imported, please re-export using "triangles" or "polylist".`

You should probably triangulate your mesh when exporting it, either by checking **Triangulate** in the Blender export options or by adding a Triangulate modifier and ensuring **Apply Modifiers** is enabled in the export options.

**Comment by TypeOverride2** [comment]
> hecking **Triangulate** in the Blender export options or by adding a Triangulate modifier and ensuring **Apply Modifiers** is enabled in the export options.

ok ok. But thats not the problem ^^ (maybe I shouldn't have mentioned it. Never bothered me on projects) Or isit on latest 4.0 the problem that he is crashing? But anyway. He shouldnt crash anyway.

**Comment by fire** [comment]
I can confirm it crashes on 9e7348f78

**Comment by akien-mga** [comment]
Crash backtrace:
```
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:6957)
[Thread 0x7fffc1a7f700 (LWP 74623) exited]
WARNING: Primitive type "polygons" is not well supported (concave shapes may fail). To ensure that the geometry is properly imported, please re-export using "triangles" or "polylist".
     at: _parse_mesh_geometry (editor/import/collada.cpp:985)
WARNING: Primitive type "polygons" is not well supported (concave shapes may fail). To ensure that the geometry is properly imported, please re-export using "triangles" or "polylist".
     at: _parse_mesh_geometry (editor/import/collada.cpp:985)
WARNING: Collada: Unreferenced material in geometry instance: id-trimat-16
     at: _create_mesh_surfaces (editor/import/editor_import_collada.cpp:837)
ERROR: Size of data provided (5440) does not match expected (5984)
   at: mesh_add_surface (servers/rendering/rasterizer_rd/rasterizer_storage_rd.cpp:2473)
ERROR: Index (uint32_t)p_surface = 0 is out of bounds (mesh->surface_count = 0).
   at: mesh_get_surface (servers/rendering/rasterizer_rd/rasterizer_storage_rd.cpp:2592)
ERROR: Condition "vertex_data.size() == 0" is true. Returning: Array()
   at: mesh_create_arrays_from_surface_data (servers/rendering_server.cpp:1422)
ERROR: FATAL: Index p_index = 7 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 0).
   at: operator[] (./core/templates/vector.h:50)

Thread 1 "godot-git" received signal SIGILL, Illegal instruction.
0x0000000001d5b9d1 in VectorWriteProxy<Variant>::operator[] (this=0x172f9a78, p_index=7) at ./core/templates/vector.h:50
50                      CRASH_BAD_INDEX(p_index, ((Vector<T> *)(this))->_cowdata.size());
(gdb) bt
#0  0x0000000001d5b9d1 in VectorWriteProxy<Variant>::operator[] (this=0x172f9a78, p_index=7) at ./core/templates/vector.h:50
#1  0x0000000004c9b47f in Array::operator[] (this=0x7fffffff9ec8, p_idx=7) at core/variant/array.cpp:78
#2  0x00000000032e0ac9 in ColladaImport::_create_mesh_surfaces (this=0x7fffffffb160, p_optimize=false, p_mesh=..., p_material_map=..., meshdata=..., p_local_xform=..., bone_remap=..., 
    p_skin_controller=0x172d0cb8, p_morph_data=0x172e1b58, p_morph_meshes=..., p_use_compression=true, p_use_mesh_material=true) at editor/import/editor_import_collada.cpp:917
#3  0x00000000032e329c in ColladaImport::_create_resources (this=0x7fffffffb160, p_node=0x172554e0, p_use_compression=true) at editor/import/editor_import_collada.cpp:1136
#4  0x00000000032e374b in ColladaImport::_create_resources (this=0x7fffffffb160, p_node=0x164dd810, p_use_compression=true) at editor/import/editor_import_collada.cpp:1177
#5  0x00000000032e374b in ColladaImport::_create_resources (this=0x7fffffffb160, p_node=0x1723fd80, p_use_compression=true) at editor/import/editor_import_collada.cpp:1177
#6  0x00000000032e3f4e in ColladaImport::load (this=0x7fffffffb160, p_path=..., p_flags=3, p_force_make_tangents=true, p_use_compression=true) at editor/import/editor_import_collada.cpp:1216
#7  0x00000000032e7985 in EditorSceneImporterCollada::import_scene (this=0x9800db0, p_path=..., p_flags=6406, p_bake_fps=15, r_missing_deps=0x7fffffffb740, r_err=0x7fffffffb74c)
    at editor/import/editor_import_collada.cpp:1661
#8  0x0000000003359bda in ResourceImporterScene::import (this=0x946d1c0, p_source_file=..., p_save_path=..., p_options=..., r_platform_variants=0x7fffffffbf48, r_gen_files=0x7fffffffbf40, 
    r_metadata=0x7fffffffbf20) at editor/import/resource_importer_scene.cpp:1274
#9  0x0000000002f3b424 in EditorFileSystem::_reimport_file (this=0xa4dfe10, p_file=...) at editor/editor_file_system.cpp:1734
#10 0x0000000002f3e132 in EditorFileSystem::reimport_files (this=0xa4dfe10, p_files=...) at editor/editor_file_system.cpp:1923
#11 0x0000000002f308c2 in EditorFileSystem::_update_scan_actions (this=0xa4dfe10) at editor/editor_file_system.cpp:563
#12 0x0000000002f34ae7 in EditorFileSystem::_notification (this=0xa4dfe10, p_what=17) at editor/editor_file_system.cpp:1127
#13 0x0000000002f4130c in EditorFileSystem::_notificationv (this=0xa4dfe10, p_notification=17, p_reversed=false) at editor/editor_file_system.h:107
#14 0x0000000004ec2387 in Object::notification (this=0xa4dfe10, p_notification=17, p_reversed=false) at core/object/object.cpp:793
#15 0x0000000003b09d6a in SceneTree::_notify_group_pause (this=0x80a71f0, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:818
#16 0x0000000003b08028 in SceneTree::idle (this=0x80a71f0, p_time=0.150000095) at scene/main/scene_tree.cpp:447
#17 0x0000000001d513d8 in Main::iteration () at main/main.cpp:2430
#18 0x0000000001d1a108 in OS_LinuxBSD::run (this=0x7fffffffd180) at platform/linuxbsd/os_linuxbsd.cpp:261
#19 0x0000000001d17b67 in main (argc=2, argv=0x7fffffffd688) at platform/linuxbsd/godot_linuxbsd.cpp:58
```

**Comment by fire** [comment]
Can't cause this to crash anymore on 96410f55b24e47af045e3ad31545331ce124d999
