### ISSUE TITLE
Division by zero should return +INF

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#41252]
**Godot version:**
<img width="563" alt="Screenshot 2020-08-14 at 18 26 41" src="https://user-images.githubusercontent.com/100964/90250394-b3e8f380-de5b-11ea-8a66-1a286becac71.png">

**OS/device including version:**
<img width="334" alt="Screenshot 2020-08-14 at 18 26 59" src="https://user-images.githubusercontent.com/100964/90250418-bf3c1f00-de5b-11ea-89ba-80b77c6ed593.png">

**Issue description:**
I've been building a trading system in Godot, and my code has many mathematical transformations.
I'm getting a bit tired of crashes whenever I accidentally don't check if I divide by zero or not.

An example:

```gdscript
y_change = (next_candle.c - curr_candle.c) / curr_candle.c
```

`y_change` is quite commonly `zero`, and so I have to always add an extra check:

```gdscript
y_change = (next_candle.c - curr_candle.c) / curr_candle.c
if y_change == 0:
    y_change = 0.000000001
````

or the following will fail, with an error (Division by zero):

```
curr_candle.c / y_change
```

This is a bit frustrating and sometimes leads to bugs in production when I accidentally forget to check this.

**Steps to reproduce:**
1) Divide by zero

**Expected behavior**
I notice that in JS `1/0` is `Infinity`, and I'd suggest this is a good solution.

In python `1/0` is a runtime error, but since most stats systems use `numpy` or `pandas` anyway, they usually take care of this to be `+INF`.

I'd be interested in hearing other contributors thoughts, as this lies outside the realm of normal game dev stuff, and perhaps returning `+INF` when we divide by zero is not a great solution for some?

**Comment by Calinou** [comment]
This should probably be opened as a [proposal](https://github.com/godotengine/godot-proposals/) rather than a bug report.

**Comment by tavurth** [comment]
Yep sorry, forgot about the proposal repo!
