### ISSUE TITLE
Godot v3.2.3 rc 3 won't run

### ISSUE THREAD

**Issue by James-San** [godotengine/godot#41276]
**Godot version:**
23b553ba0603161346526e1821bff5002520173c

**OS/device including version:**
Ubuntu 20.04.1 LTS 

**Issue description:**
After downloading headless version of Godot ( v.3.2.3 rc3 ), it doesn't boot into any GUI and running CLI only prints out: "Godot Engine v3.2.3.rc3 official - https://godotengine.org". 3.2.2 stable version isn't experiencing this issue.

**Steps to reproduce:**
1.Download specified image on ubuntu 20.04.1 LTS
2.Extract executable 
3.Run executable

**Comment by akien-mga** [comment]
The headless version doesn't have any GUI - that's what "headless" means.

**Comment by akien-mga** [comment]
Closing as it seems to be a misunderstanding. Feel free to comment and I'll reopen if I misinterpreted the issue.
