### ISSUE TITLE
"Always on top" doesn't work on macOS

### ISSUE THREAD

**Issue by DanielZTing** [godotengine/godot#41275]
**Godot version:**

v3.2.2.stable.official

**OS/device including version:**

MacBookAir8,1 (Retina, 13-inch, 2018)
macOS Catalina 10.15.5 (19F101)
Intel UHD Graphics 617 1536 MB

**Issue description:**

The property "display/window/size/always_on_top" does not work on macOS. (It does work on my Windows machine. I took a peek at the source code and it looks like `os_windows.cpp` actually detects the option and sets it during initialization while `os_osx.mm` doesn't. I guess that's also why interestingly, `OS.set_window_always_on_top` does work.) (On a side note, I poked around on the `master` branch and it seems like this functionality is completely absent in the new DisplayServer implementation for macOS.)

**Steps to reproduce:**
1. Check "Always on top" in Project Settings > Display > Window
2. Run game and pull up another app, the window will get covered over

**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
> On a side note, I poked around on the master branch and it seems like this functionality is completely absent in the new DisplayServer implementation for macOS.

It's moved to `DisplayServer.window_set_flag`.
