### ISSUE TITLE
Add PCK Packer to release

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#4129]
```
SCRIPT ERROR: GDScript::load_byte_code: Compile Error: Identifier not found: PCK Packer
```

 Compiling for Windows
scons p=windows tools=no target=release_debug

**Comment by akien-mga** [comment]
Please follow the template to report issues, there is a lot of lacking information in this bug report.

What were you doing? What's the script line that triggers the script error? What Godot version? etc.

**Comment by cjmxp** [comment]
godot  version  2.0  and 2.1
Compiling for Windows
scons p=windows tools=no target=release_debug

script  https://github.com/cjmxp/godotbug/tree/master/PCKPackerBUG

Export -> Windows Desktop Debug

**Comment by cjmxp** [comment]
https://github.com/cjmxp/godot/commit/2138225f1d315b83dab186a12f35533f7251754d

**Comment by cjmxp** [comment]
https://github.com/cjmxp/godot/commit/605dfe0ff9d6f103efdf74eabd5aaf6ca98bf403

**Comment by punto-** [comment]
probably the release build doesn't have the PKPacker class because it's
from tools. if it's just a script that packs stuff you can run it with the
normal editor binary, no need to export

**Comment by cjmxp** [comment]
All objects in the editor should be supported to run after the export.

**Comment by neikeq** [comment]
No, not all objects in the editor should be supported. However, a warning, label or annotation in the docs that specifies that the class requires tools enabled could be helpful.
Apart from that, I think `PCKPacker` should be included in non-tools builds. It may be very useful for modding or other situations where a game generates extra PCK files.

**Comment by reduz** [comment]
i guess it makes sense that PCKPacker could be available from outside the
editor.. could be moved to core/

**Comment by reduz** [comment]
generally anything available only from the editor begins with Editor* in
the name
