### ISSUE TITLE
Expose data about exact graphics API

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#4130]
**Operating system or device:**
Any with questionable OpenGL support.

**Issue description** (what happened, and what was expected):
It is hard to debug Godot driver issues, because Godot doesn't expose any information about required graphics API, see
https://github.com/godotengine/godot/issues/4079#issuecomment-197876319
https://github.com/godotengine/godot/issues/4079#issuecomment-198079545

Expected that engine could at least output all OpenGL API functions that are linked in the code. Then some script could use that list to show minimal compatible OpenGL version. Then https://piglit.freedesktop.org/ tests could be run to see what exactly is missing from target OpenGL API to match needed requirements.

When this mechanism is in place, it can also be used to detect which specific graphics API is needed by specific game and lower its hardware requirements.

Graphics API requirements can also be tracked in CI scripts to ensure that they don't climb up from certain standard.

This is a prerequisite for #1162.

**Steps to reproduce:**
Run Godot under QEMU?

**Comment by akien-mga** [comment]
I don't think this is feasible easily, and we already found a way to fix #1162, so closing.

**Comment by techtonik** [comment]
I hoped to use Godot game engine to troubleshoot graphics platform issues the same way `darktable -d` works for troubleshooting OpenCL - https://askubuntu.com/questions/576338/why-opencl-is-not-default-14-04-nvidia-331
