### ISSUE TITLE
Input.get_gravity() and Input.get_accelerometer() are not supported on Windows Desktop export

### ISSUE THREAD

**Issue by ZodmanPerth** [godotengine/godot#41303]
**Godot version:**
3.2.stable.official

**OS/device including version:**
OS: Windows 10 Pro, 64 bit, version 1909
Device: Surface Pro 7

**Issue description:**
I need the gravity vector when running my game on a Windows Desktop export.   I currently access it on an Android Export using `Input.get_accelerometer()` however I would would also be happy if `Input.get_gravity()` was supported.

**Steps to reproduce:**
1. In `func _process(delta)`, print the values of `Input.get_accelerometer()` and `Input.get_gravity()` to the output window.
1. Export the project to Windows Desktop and run.
1. Observe the `Vector3` of each function always reports `(0, 0, 0)`.

**Minimal reproduction project:**
[AccelerometerTest.zip](https://github.com/godotengine/godot/files/5080032/AccelerometerTest.zip)

**Comment by SekoiaTree** [comment]
I'm pretty sure this is expected behavior, since laptops and computers usually don't have an accelerometer.

**Comment by ZodmanPerth** [comment]
I think the term "usually" got downgraded with the creation of the Surface line, and subsequent hybrids.  That's now a mature model that should be considered.

Any sensor supported by Windows could be present or not.  I believe Godot could dynamically implement support by testing for the presence for various sensors.

In this issue I only ask for support of the accelerometer, as that is what I require for my current game design.

**Comment by Calinou** [comment]
Please open a [proposal](https://github.com/godotengine/godot-proposals) to request this feature, since this repository is meant to be used for bug reports only now.

**Comment by ZodmanPerth** [comment]
Thanks, I wasn't aware.  I will.

FYI this information probably needs to be found via the https://godotengine.org/ homepage; that's what led me here.

**Comment by Calinou** [comment]
> FYI this information probably needs to be found via the godotengine.org homepage; that's what led me here.

Done: https://github.com/godotengine/godot-website/pull/173
