### ISSUE TITLE
Can't find deg2rad in Godot C#

### ISSUE THREAD

**Issue by Pete-The-Penguin** [godotengine/godot#41311]
**Godot version:**
3.2.2-stable

**OS/device including version:**
Manjaro Lysia 20.0.3

**Issue description:**
Was trying to make a FPS script in C#, but when trying to find deg2rad for camera movement, it wasn't there?

**Steps to reproduce:**
1. Make a C# script (any IDE will do.)
2. Search for deg2rad in C# script

**Minimal reproduction project:**
None so far (i can put one here, if need be.)

**Comment by TheDuriel** [comment]
Its in Mathf http://godotsharp.net/api/3.2.0/Godot.Mathf/

**Comment by Calinou** [comment]
Closing per @TheDuriel's comment.

**Comment by Pete-The-Penguin** [comment]
Thank you!!
