### ISSUE TITLE
Warning: Standalone expression (the line has no effect).

### ISSUE THREAD

**Issue by holybreath** [godotengine/godot#41317]
Hi, I'm just starting a small project of godot, this is a simple func to change view but always with this warning when run. Is there any problem? thanks!
![捕获](https://user-images.githubusercontent.com/1182619/90368561-d3229380-e09c-11ea-9745-a73cc278dd1b.JPG)

**Comment by Zireael07** [comment]
You have two == (assignment) instead of one = (a check)

**Comment by holybreath** [comment]
> You have two == (assignment) instead of one = (a check)

Thanks for your reply! but I'm confused, here I mean to check if v is equal to view, so I use two = =. However, when I just add some space this line, then the warning disappeared, and never get out when I make it back just as the pic shows. I think it's the editor's something. Anyway, though it can't be reproduced now, I will close this and thanks.

**Comment by akien-mga** [comment]
> You have two == (assignment) instead of one = (a check)

That's the other way around.

But I suspect that the original code that triggered the warning might have been `v=view`, and it was then fixed but the warning was still visible until the next run of the project.
