### ISSUE TITLE
2D normal mapping rotations incorrect

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#41324]
**Godot version:**
3.2.2

**OS/device including version:**
All (GLES2 and GLES3)

**Issue description:**
_Note this is a stub issue for reference, to illustrate the problem which is now hopefully fixed with 2 PRs._

When using normal mapping in 2D, flips and rotations only produce correct results in the old TEXTURE_RECT (uniform draw) method. The results are incorrect with GLES2 and GLES3 nvidia workarounds, and with GLES2 batching.

i.e. If you rotate a sprite, or flip, the normal mapping will not adjust according to the new orientation with the light.

In GLES2 and GLES3 nvidia workaround, rotations work but flips do not.
In GLES2 batching, both flips and rotations do not work.

**Steps to reproduce:**
Add a normal mapped sprite using GLES2 or GLES3 using `nvidia_workaround` project setting, or GLES2 batching.
Add a 2D light so you can see the normal map lighting.

Flip and rotate the sprite. Note that the normal maps do not rotate correctly to match the lighting.

**Comment by akien-mga** [comment]
Fixed by #41323 and #41254.
