### ISSUE TITLE
Flickering editor window focus due to system console

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41328]
**Godot version:**

a17fba3

**OS/device including version:**

Windows 10

**Issue description:**

When you open a project, the editor window will lose focus every second for a brief moment. A console window appears stealing the focus, but it disappears immediately and editor is focused again. It can be fixed after toggling System Console option twice, but after restarting it happens again.

**Comment by akien-mga** [comment]
Related to #41307 and #41325 I guess.

**Comment by bruvzg** [comment]
Can't reproduce it, and have no idea why it can do something like this.

I guess it's better to revert #41164 and use build option instead.

**Comment by AlphaOneProject** [comment]
I can reproduce this bug with ba1109a on Windows 10.
Here is a Gif so you can see for yourself the loss of focus:
![Flickering editor window focus due to system console](https://user-images.githubusercontent.com/48980641/90415043-d889d900-e0b0-11ea-8849-72b903d95924.gif)
I hope it helped you :D

**Comment by pouleyKetchoupp** [comment]
I can reproduce this issue again in 377c3bb25672fb7060cbd465a698661a93290e07 (Windows 10, debug).

There's no workaround this time as it's not possible to disable the console anymore (even when reverting #42065, the toggle console option doesn't have any effect).

**Comment by KoBeWi** [comment]
@pouleyKetchoupp I noticed it works fine if you do console build (default is GUI).

**Comment by bruvzg** [comment]
> I can reproduce this issue again in 377c3bb (Windows 10, debug).
There's no workaround this time as it's not possible to disable the console anymore (even when reverting #42065, the toggle console option doesn't have any effect).

That's strange, then #41164 was probably fine and editor have issues with gui mode for some other reason.

**Comment by pouleyKetchoupp** [comment]
@bruvzg Yep, I'm puzzled too. I'm not sure if it's still the same exact problem, but I had it working correctly by reverting #41164 at some point, with the default options in debug.

**Comment by akien-mga** [comment]
Is this still reproducible? Can we give #41164 another try if it was not the cause for this bug?

**Comment by KoBeWi** [comment]
Doesn't seem to be happening in 43fa911, tried with GUI build.

**Comment by pouleyKetchoupp** [comment]
@akien-mga I tried #41164 again on latest master, and I can't reproduce the flickering issue, although "Toggle System Console" doesn't disable the console (it works ok on master without the PR changes).
