### ISSUE TITLE
ERROR: create: Cannot find path for cache directory!

### ISSUE THREAD

**Issue by Ajgamer28** [godotengine/godot#41331]
**Godot version:v3.0.6.stable.custom_buid**

**OS/device including version:Debian GNU/Linux 10 (buster) on Chrome OS x86_64**

**Issue description:
every time I open the graphics engine the program just exits**

**Steps to reproduce:
I enter the application,
then I create a new project and enter this one but just when the edit screen is shown the program closes**

**Minimal reproduction project:**

**Comment by fire** [comment]
What video card are you using on the Chrome OS?

**Comment by Ajgamer28** [comment]
How can I get that information?

**Comment by Ajgamer28** [comment]
these are the errors it shows me
ERROR: create: Cannot find path for cache directory!
   At: editor/editor_settings.cpp:760.
ERROR: save_image: Method/Function Failed, returning: err
   At: drivers/png/resource_saver_png.cpp:93.

**Comment by Ajgamer28** [comment]
#bug

**Comment by Calinou** [comment]
You're using a very old version of Godot (3.0.6). The latest version available is 3.2.2.

**Comment by Ajgamer28** [comment]
ok thanks
i will update godot
