### ISSUE TITLE
Window Dialogs Don't Show

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#4133]
**Operating system or device:**
Linux

**Issue description** (what happened, and what was expected):
Just last night I got Window Dialogs to show, but today they won't. Only thing that has changed is that I moved the Godot executable to /usr/bin last night. Today I opened the project and the windows don't show when running. They show in edit mode, though. Clicking the visibility (eye icon) does nothing to show it. I have to add a script to the window and add.. 

`func _init(): 
    show()` 

for it to show. (show() should be indented on the next line in that statement but I couldn't get it to work on github.
[WindowTest.tar.gz](https://github.com/godotengine/godot/files/186594/WindowTest.tar.gz)

**Steps to reproduce:**
Create a Window Dialog, any kind and it won't show on my system.

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
_WindowDialog_ is an inheritor of_Popup_, so you must use either _popup()_, _popup_centered( Vector2 size=Vector2(0,0) )_, _popup_centered_ratio( float ratio=0.75 )_ or _popup_centered_minsize( Vector2 minsize=Vector2(0,0) )_ to show it.

**Comment by toliaferrode** [comment]
I'm wondering why it worked last night. I had it as a child of a control node. No popup nodes involved at all.

**Comment by toliaferrode** [comment]
I'm not quite sure what you're telling me to do. I need to dig deep into Godot again. I made WindowDialog a child of Popup, which is a child of Control and it still won't show.

**Comment by neikeq** [comment]
I mean WindowDialog is a derived class of Popup (check the [WindowDialog reference](http://docs.godotengine.org/en/latest/classes/class_windowdialog.html)).

You must call _popup()_ (which is a method [from the Popup class](http://docs.godotengine.org/en/latest/classes/class_popup.html)) to show it in a modal form. If you want to show your dialog automatically when starting, you have two options:

- Add a script to the WindowDialog, override _\_ready()_ method and call _popup()_ there:

``` GDScript

extends WindowDialog

func _ready():
    popup()
    # or popup_centered()
    # or popup_centered_minsize()
    # or popup_centered_ratio()
```
- You can also do it from the editor by connecting the signal `enter_tree` with the _popup_ method in deferred mode, like explained here: https://github.com/godotengine/godot/issues/2431#issuecomment-198761429

**Comment by toliaferrode** [comment]
Thanks, I think I understand. I just don't get why it worked automatically last night and not today. Either way I have a lot of learning to do. This has inspired me to redouble my efforts.
