### ISSUE TITLE
SVG icon is showing blue but only contains red shapes when edited in Inkscape

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#41339]
Godot 3.2.3 rc3, Windows 10 64 bits

I took a blue icon from Godot and changed all its colors to red variants. But once in Godot, one of the shapes is showing blue, while none of the blue remains when I check the SVG in Inkscape... I have no idea where it comes from, or how to fix it

![image](https://user-images.githubusercontent.com/1311555/90452374-e0b03b80-e0e5-11ea-8fca-caace57481d7.png)

![image](https://user-images.githubusercontent.com/1311555/90452475-2cfb7b80-e0e6-11ea-9e1b-2b91001aa0f6.png)

To reproduce:
Drop the following icon in a project: 
[icon_voxel_terrain.zip](https://github.com/godotengine/godot/files/5087214/icon_voxel_terrain.zip)

**Comment by Xrayez** [comment]
May be related to color conversion added in #10382 (light/dark modulation mixup?).

**Comment by sammycage** [comment]
> May be related to color conversion added in #10382 (light/dark modulation mixup?).

Inline `style` overrides presentation `attributes`

```xml
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <rect x="20" y="20" width="160" height="160" fill="red" style="fill:green"/>
</svg>
```

output :
![inline_style_overrides_presentation_attribute svg](https://user-images.githubusercontent.com/29164324/123792143-36459f00-d8d8-11eb-9157-0e74b4d4fdac.png)

**Comment by Zylann** [comment]
```xml
  <g
     transform="translate(0 -1036.4)"
     fill-rule="evenodd"
     id="g8">
    <path
       transform="translate(0 1036.4)"
       d="m8 1l-7 3v8l7 3 7-3v-8l-7-3z"
       fill="#2998ff"
       id="path2"
       style="fill:#fb6d6d;fill-opacity:0.99607843" />
    <path
       d="m8 1051.4-7-3v-8l7 3z"
       id="path4"
       style="fill:#fc9c9c;fill-opacity:0.99607843"
       fill="#68b6ff" />
    <path
       d="m1 1040.4 7 3 7-3-7-3z"
       fill="#a2d2ff"
       id="path6"
       style="fill:#fdcbcb;fill-opacity:0.99607843" />
  </g>
```

I see there are `fill` attributes containing blue colors, and `style` takes over with red. However I haven't edited this by hand, I only made these changes in Inkscape. I don't know how to not have this superposition of override, I didn't know that was even a thing.
Still, it's quite unclear to me how Godot arrives to the outcome of replacing one path with blue, when it sounds like styles should have been used anyways?

**Comment by sammycage** [comment]
[The order is not important](https://stackoverflow.com/a/36755226)

**Comment by Calinou** [comment]
This is likely an issue with NanoSVG we can't fix on our end, especially since NanoSVG is not maintained anymore.

**Comment by Zireael07** [comment]
Wasn't there a proposal to replace NanoSVG with some other library?

**Comment by Calinou** [comment]
> Wasn't there a proposal to replace NanoSVG with some other library?

See https://github.com/godotengine/godot/pull/49645, but editor icon conversion code is currently missing before it can be merged.
