### ISSUE TITLE
Wrong Gdscript UTI type for macOS

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot#41356]
**Godot version:**
3.2.3 rc official

**OS/device including version:**

macos 10.15.6

**Issue description:**

Quicklook cannot preview gdscript files because the gd extension is defined as public.data in this file;
https://github.com/godotengine/godot/blob/65730ab9f6fbae34bb161113161b43f8b3fcd4d2/misc/dist/osx_tools.app/Contents/Info.plist#L114

**Steps to reproduce:**
Open it with Quicklook, only the icon will appear.

terminal command for UTI info
```
> mdsl player.gd
...
kMDItemContentType                     = "public.gd"
kMDItemContentTypeTree                 = (
    "public.gd",
    "public.data",
    "public.item"
)
...
```
It should be something like this;

```
kMDItemContentType                     = "public.gd-script"
kMDItemContentTypeTree                 = (
    "public.gd-script",
    "public.shell-script",
    "public.script",
    "public.source-code",
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```

https://en.wikipedia.org/wiki/Uniform_Type_Identifier#UTI_structure

**Comment by Calinou** [comment]
Feel free to open a pull request to fix this :slightly_smiling_face:

**Comment by hazarek** [comment]
> Feel free to open a pull request to fix this 🙂

I don't have time to build and test it. i am not an apple developer. I am not an expert.

**Comment by brokeyourbike** [comment]
> > Feel free to open a pull request to fix this 🙂
> 
> I don't have time to build and test it. i am not an apple developer. I am not an expert.

So sad 😞

**Comment by hazarek** [comment]
I'll change `public.data` to `public.script` it should work, but I'm not sure.
so that QuickLook can display it as plaintext. because public.script conforms to plain-text.
[Uniform Type Identifiers Reference](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html#//apple_ref/doc/uid/TP40009259)
public.script < public.source-code < public.plain-text
