### ISSUE TITLE
Visual artifacts when using OmniLights with volumetric fog enabled (likely related to clustering)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#41357]
**Godot version:** Git 87ae50990

**OS/device including version:** Fedora 31, GeForce GTX 1080 (NVIDIA 440.100)

**Issue description:** Visual artifacts can be seen when using OmniLights with volumetric fog enabled. This is likely related to clustering.

![image](https://user-images.githubusercontent.com/180032/90549776-44db0a00-e18f-11ea-9b3e-2e436f44361a.png)

**Steps to reproduce:** Add several OmniLights to a scene with volumetric fog enabled and use freelook to navigate in the scene. You will likely encounter a clustering artifact sooner or later.

**Minimal reproduction project:** [volumetric_fog_clustering_bug.zip](https://github.com/godotengine/godot/files/5092076/volumetric_fog_clustering_bug.zip)

**Comment by Calinou** [comment]
I can still reproduce this in https://github.com/godotengine/godot/commit/a22c7eff0.

**Comment by fire** [comment]
[Fog Atomospheric.zip](https://github.com/godotengine/godot/files/5586253/Fog.Atomospheric.zip)

Can reproduce with spot lights too.

https://cdn.discordapp.com/attachments/604227989550530561/780566268427632660/Screen_Recording_2020-11-23_at_2.51.04_PM.mov

* atmospheric fog on 
* auto exposure
* geometry as in project file

**Comment by clayjohn** [comment]
I think I fixed this in https://github.com/godotengine/godot/pull/53353

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.alpha15, closing.
