### ISSUE TITLE
Error Export Android

### ISSUE THREAD

**Issue by Ismel94** [godotengine/godot#41353]
![errorGodot](https://user-images.githubusercontent.com/52164665/90531974-e9c7f980-e133-11ea-8033-f5733bc221fd.jpg)

**Comment by Calinou** [comment]
@Ismel94 When reporting bugs, please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it.

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
