### ISSUE TITLE
Per-light semi-dynamic lightmaps?

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#4136]
In the good old Unreal I the first scene demonstrates very well this feature.

Take a look at all the blinking lights around - they all are using lightmaps, but the lighmaps seem to be individual for every light and mixed in realtime allowing per-light changes, like flickering just one of the lights without dimming the rest, and of course - still using baked shadows and stuff. Dynamic lights are only used for moving objects like projectiles and explosions in this game (and they don't cast any shadows).

https://www.youtube.com/watch?v=Op-tys_98Ek

Can this be achieved with Godot?

**Comment by reduz** [comment]
We have realtime GI now, so this is obsolete, closing
