### ISSUE TITLE
 Can't Rename folder when only changing letter from small to capital

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#41368]
**Godot version:**
3.2.3.rc3 official

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
When I want to rename a folder from lower-case to upper-case, i only get "error moving".
Was expecting for it to just change the folder-name.

When using 3.2.3 rc3 with macOS, it only tells me "Folder with that name already exists" but not error-message. Still would expect it to just change the folder-name

**Steps to reproduce:**
Add folder "head" to the project file-system, click rename and try to rename it to "Head". Then it should throw the error "Error moving"

This can be circumvented when just removing the folder and creating a new one with the correct naming "Head".

**Minimal reproduction project:**
happens in any kind of project

**Comment by akien-mga** [comment]
Duplicate #19592.
