### ISSUE TITLE
Dictionary keys by variable do not store correctly

### ISSUE THREAD

**Issue by jimbeauphloyd** [godotengine/godot#41377]
**Godot version:**
Godot Engine v4.0.dev.custom_buld.f97280a01

**OS/device including version:**
Mac OSX 10.15.5
Vulkan

**Issue description:**
Passing a variable key to a dictionary does not place values in the correct key.

Result:
```
{A:[A entry 0, B entry 1, A entry 2, B entry 3, A entry 4, B entry 5], B:[...]}
```

Expected Result:
```
{A:[A entry 0, A entry 1, A entry 2], B:[B entry 0, B entry 1, B entry 2]}
```

**Steps to reproduce:**

```gdscript
extends Node

var _entries = {}

func _ready():
	var key
	key = "A"
	_entries[key] = []
	key = "B"
	_entries[key] = []
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	print(_entries)

func _add_entry(key):
	_entries[key].append(key + " entry " + str(_entries[key].size()))
```

**Minimal reproduction project:** [DictionaryBug.zip](https://github.com/godotengine/godot/files/5098253/DictionaryBug.zip)

**Comment by EricEzaM** [comment]
Seems to be with the initialization of the values. This gives the expected output:

```gdscript
extends Node

var _entries = {}

func _ready():
	_entries = {
		"A": [],
		"B": []
	}
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	print(_entries)

func _add_entry(key):
	_entries[key].append(key + " entry " + str(_entries[key].size()))
```

**Comment by EricEzaM** [comment]
Additionally, expanding this to:

```gdscript
	_entries = {
		"A": [],
		"B": []
	}
	_entries["C"] = []
	var key = "D"
	_entries[key] = []
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	_add_entry("C")
	_add_entry("D")
	_add_entry("C")
	_add_entry("D")
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	print(_entries["A"]) # [A entry 0, A entry 1, A entry 2, A entry 3, A entry 4]
	print(_entries["B"]) # [B entry 0, B entry 1, B entry 2, B entry 3, B entry 4]
	print(_entries["C"]) # [C entry 0, D entry 1, C entry 2, D entry 3]
	print(_entries["D"]) # [C entry 0, D entry 1, C entry 2, D entry 3]
```

"A" and "B" remain correct, but "C" and "D" get mixed up. However, they do not get values from "A" and "B" even when they are added after.

**Comment by DangerChaser** [comment]
Initializing each array with **UNIQUE** values seems to give the expected output, but only if it's unique. Otherwise, Godot writes to the same array, e.g.
```
	var key
	key = "A"
	_entries[key] = [1]
	key = "B"
	_entries[key] = [2]
        key = "C"
        _entries[key] = [2] # Same as B
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	_add_entry("A")
	_add_entry("B")
	_add_entry("C")
	_add_entry("C")
	_add_entry("C")
	print(_entries["A"]) # [1, A entry 1, A entry 2, A entry 3]
	print(_entries["B"]) # [2, B entry 1, B entry 2, B entry 3, C entry 4, C entry 5, C entry 6]
	print(_entries["C"]) # [2, B entry 1, B entry 2, B entry 3, C entry 4, C entry 5, C entry 6]
```

**Comment by ThakeeNathees** [comment]
A simplified version of the issue
```gdscript
func _ready():
	var v1 = []
	var v2 = []  ## both arrays are reduced to Array const and shares the same memory in constant map.
	
	v1.append(42)
	print(v2)   ## prints [42]
```
In 3.2 the literal array doesn't reduced to variant (even if all elements are compile time const) but it was `ArrayNode` and constructed at runtime (`OPCODE_CONSTRUCT_ARRAY`) but in 4.0 it's reduced to `Array` constant at `GDScriptAnalyzer::reduce_array()` and since it's a constant value every other similar array will points to the same location in the local constant map.

similar issue : https://github.com/godotengine/godot/issues/20436

adding constant to constant_map first search if it already exists, is it okey to ignore that existence search for arrays/ and dictionaries @vnen ?

**Comment by vnen** [comment]
> adding constant to constant_map first search if it already exists, is it okey to ignore that existence search for arrays/ and dictionaries

Yeah, I was thinking about that. Though I'm not sure if we actually want to keep arrays/dictionaries in the constant map. It is theoretically faster (since it doesn't need to be built at runtime) but the space needed might not be worth it.
