### ISSUE TITLE
GridMap remains visible if parent is set to not visible

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#41374]
**Godot version:**
3.2.2

**OS/device including version:**
Ubuntu Linux 16.04, 64-bit
GeForce GTX 970 with NVIDIA 384.130 driver
GLES3 backend

**Issue description:**
GridMaps remain visible in the editor and at runtime while parent spatial nodes are set to invisible.

**Steps to reproduce:**
1. Create a GridMap node in a 3D scene
2. Set the scene root to invisible
3. Notice the GridMap remains visible while the rest of the scene is hidden.

**Minimal reproduction project:**
[GridMap-Visible.zip](https://github.com/godotengine/godot/files/5097532/GridMap-Visible.zip)

If you run the project you can press space to toggle the visibility of the scene. Note that the DirectionalLight and the Sprite3D correctly hide while the GridMap remains on the screen.

**Comment by Calinou** [comment]
This was reported a long time ago in https://github.com/godotengine/godot/issues/907, but it seems the bug appeared again according to https://github.com/godotengine/godot/issues/10418#issuecomment-597557161.

**Comment by Blizbor** [comment]
Hi,

I just entered github to report same issue but found that existing report.
I can confirm problem exist - same version (3.2.2 official binaries) on Windows 10, backend GLES3.

Anyway - amazing work guys, I like GODOT so much.

Cheers,

**Comment by jamesdkay** [comment]
Does anyone know if this issue is related to #40245, and if this solution will resolve that issue too?
