### ISSUE TITLE
CanvasLayer is unselectable 

### ISSUE THREAD

**Issue by SamToorchi** [godotengine/godot#41370]
**Godot version: 3.2.2 stable**

**OS/device including version: MacOS Mojave**

**Issue description:**
**_Sometimes_** is it not possible to add "CanvasLayer" Node to a empty scene or as child of a 2DNode. The Node is unselected. But if the Node is in the history of Node List, you can select and add it to the scene and it works.

![Bildschirmfoto 2020-08-19 um 15 17 49](https://user-images.githubusercontent.com/22751446/90639779-773c4400-e22f-11ea-88ba-01223659832a.png)

**Comment by bruvzg** [comment]
It's `CanvasItem` that's grayed out, because it is virtual type (always should be non-selectable), `CanvasLayer` is another node.

![90639779-773c4400-e22f-11ea-88ba-01223659832a](https://user-images.githubusercontent.com/7645683/90640305-7fe54800-e238-11ea-9fd7-62fbfec4f45c.png)

**Comment by SamToorchi** [comment]
oh, i'm sorry. 
Thank you very much!
