### ISSUE TITLE
AudioStreamPlayer.seek() does not update playback position

### ISSUE THREAD

**Issue by Cheeseness** [godotengine/godot#41389]
**Godot version:**
3.2.2.stable

**OS/device including version:**
Fedora 29

**Issue description:**
Calling AudioStreamPlayer's seek() function does not update the AudioStreamPlayback's internal position, resulting AudioStreamPlayer.get_playback_position() returning unexpected values.

**Steps to reproduce:**
1. Run attached project
2. Wait for some time to pass
3. Click the pause button to pause playback
4. Click the reset button to call seek(0), noting the displayed value from get_playback_position() after seek() is called
5. Click the play button to resume playback, noting the displayed value from get_playback_position() after resuming playback is still not zero

**Minimal reproduction project:**
[audiostreamplayer_seek_test.tar.gz](https://github.com/godotengine/godot/files/5100719/audiostreamplayer_seek_test.tar.gz)

**Comment by EricEzaM** [comment]
Confirmed on Win 10
