### ISSUE TITLE
Add Input.get_gyroscope to godot, it is NOT the same as accelerometers!

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#4138]
I've been trying to do something akin to
https://alastaira.wordpress.com/2013/08/24/the-7dfps-game-jam-augmented-reality-and-spectral-echoes/

or this:
http://blog.heyworks.com/how-to-write-gyroscope-controller-with-unity3d/

even youtube and facebook now supports this feature - you can view 360 degree videos using your phone's gyroscope:
https://www.youtube.com/watch?v=aQd41nbQM-U
https://www.youtube.com/watch?v=f-7qq8n2iqw
http://www.digitaltrends.com/mobile/youtube-360-degree-videos-look-great/

I thought that this would be an interesting game mechanic and indeed it has been used in a nintendo 3ds game:
https://youtu.be/vX44AVkwFmc?t=2m11s

So i tried to implement it in gdscript only to find that it is impossible to get any good results with the accelerometer alone. Unity on the other hand does have access to the device's gyroscope and most implementations use the gyroscope to do that.

There is a difference in what this sensor does - it is not the same as accelerometer:
http://www.livescience.com/40103-accelerometer-vs-gyroscope.html
Almost every tablet device and phone has a gyro. It is becoming more and more relevant with the boom of VR and AR devices too. I just think that there is a missed opportunity for godot here.

Is gyro input on the roadmap? Are devs interested in implementing it at some point? If so, this would be complimentary to another feature - to support google cardboard/vr camera. :)
A google cardboard unit costs 5$ on ebay and turns most smartphones into a cheap vr headset.

**Comment by Marqin** [comment]
:+1:

**Comment by blurymind** [comment]
The second item on the list to vr is support for a stereoscopic camera mode. Here is some of the official documentation from google:
https://developers.google.com/cardboard/unity/reference

please note that gyroscope support would be immensely useful even for projects that are not targetted at vr headsets or google cardboard!

**Comment by VadeFOAM** [comment]
blurymind, I have an android module that may fulfill your needs until and official solution is implemented. 

https://github.com/VadeFOAM/Godot-SensorFusion

It uses code developed by Alexander Pacha to fuse sensors(accel,gyro,etc..) and was created specifically for AR/VR. As you discovered using raw Accel/Gyro data is unsuited to use in AR/VR so to get the best results you need to fuse various sensors, Thankfully Alexander made this much easier for the rest of us. To use the module you will have to compile your own android export template.

**Comment by blurymind** [comment]
Hi @VadeFOAM , I will wait for an official implementation. My goal is not in implementing ar/vr, but rather just making a simple first person camera controlled by the gyroscope. At least for now.

Could this solution or a part of it at least be merged to godot trunk?

**Comment by VadeFOAM** [comment]
The Orientation Providers are the meat of the module and do the work, they could be added fairly easy but it would require some rethinking on how hardware sensors are handled in general within the engine. Also this module is android only so it would still require similar code to be written for the other platforms.

On a side note, using just the gyro to control an in-game camera is not a good idea. The orientation providers provided in the module are much better suited for that task. There is a demo scene provided with the module that will show you why the fused sensors are better, you can also get the original demo at the google play store: https://play.google.com/store/apps/details?id=org.hitlabnz.sensor_fusion_demo

**Comment by punto-** [comment]
Didn't we get to patch for th 2 weeks ago? It looked good fo android, but I didn't have the setup to test it.

**Comment by Marqin** [comment]
@punto- It was for magnetometer and it was rejected by @akien-mga - https://github.com/godotengine/godot/pull/4010

**Comment by blurymind** [comment]
@ghost the link you provided is dead
https://github.com/VadeFOAM/Godot-SensorFusion
he seems to have removed it. Is there a mirror I can download this?

@akien-mga @Marquin what was wrong with the patch?

Is this gyroscope a planned feature or should I forget about it for now?

**Comment by blurymind** [comment]
This has been solved by
https://github.com/godotengine/godot/commit/370ae3512deda40b2659a1192f302298e269305f

**Comment by blurymind** [comment]
Time to make the next Pokemon Go now :P
