### ISSUE TITLE
C++ comments cause crash

### ISSUE THREAD

**Issue by Jiaming00** [godotengine/godot#41383]
**Godot version:**
3.2.2

**OS/device including version:**
windows10

**Issue description:**
I am writing code that is completely unrelated to godot in a native script environment. A line of Chinese comment caused a crash: 
**System.Net.Sockets.SocketException (0x80004005): The remote host forced an existing connection to be closed.
    In Mono.Debugger.Soft.TcpConnection.TransportReceive(Byte[] buf, Int32 buf_offset, Int32 len)
    In Mono.Debugger.Soft.Connection.Receive(Byte[] buf, Int32 buf_offset, Int32 len)
    In Mono.Debugger.Soft.Connection.ReadPacket()
    In Mono.Debugger.Soft.Connection.ReceivePacket()
    In Mono.Debugger.Soft.Connection.receiver_thread_main()
Godot player terminated with exit code -1073741819**

I tried a lot of Chinese examples, and there is no crash in rare cases. Does it support only English comments or a few specific languages by default.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@Jiaming00 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Jiaming00** [comment]
Sorry for disturbing you guys.
This should be because the vs compiler mistaken utf-8 for unicode. Because I use vscode.
😅
