### ISSUE TITLE
Export/ImageGroup: the problem with the same name in atlases

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#4139]
**Operating system or device:**
Win10, Android 5.1 (Jiayu s3)

**Issue description** (what happened, and what was expected):
I created a group (Atlas) for units and received a strange result. In version 1.1, this was not.
It should be like this:
![godot_v2 2016-03-25 03-34-55-47](https://cloud.githubusercontent.com/assets/233268/14035150/f372f520-f23b-11e5-8451-5623cc71e35a.jpg)

and it turns out like this:
![prj_x_32 2016-03-25 03-35-22-57](https://cloud.githubusercontent.com/assets/233268/14035172/28984354-f23c-11e5-9022-18af41fc7a35.jpg)

How to accurately reproduce this problem, I do not know yet. I have another atlas with icons and interface with it all right. In the near future I will try to provide more detailed information.

PS
This is a different story in the performance somehow low enough for 100 units. And I do not understand what it is connected. Because I disabled all the animation almost all processes. You're a couple who can not so much influence the speed. :(

**Comment by ret80** [comment]
I find out the reason. All character names identical pictures. But they are in different folders. Previously, they were considered as unique and not now. And it's very bad :(

**Comment by bojidar-bg** [comment]
@ret80 ~ If this is the case, maybe you should edit the title of the issue?

**Comment by ret80** [comment]
Please fix this bug already. Very much needed support atlases.

**Comment by reduz** [comment]
Make a test project, i have no idea what's going on from your description

**Comment by ret80** [comment]
If you run this project on the desktop, you will see three pictures "A", "B", "C". But if you collect under androyd the three images will only be at all "C".
https://yadi.sk/d/qtTmVt4esJZNe

**Comment by ret80** [comment]
I hope that this is enough to solve the problem.

**Comment by reduz** [comment]
it was of great help, thanks!

**Comment by ret80** [comment]
Atlases do not work for AnimatedSprite3D.
1 create AnimatedSprite3D
2 add frames in AnimatedSprite3D
3 add sptites in atlas
4 run

**Comment by ret80** [comment]
I created a example project #6338

**Comment by ret80** [comment]
Have somebody look issue #6338? There is an example showing the problem. At least otmette this as a bug!
