### ISSUE TITLE
'_body_enter_tree: Condition "!E" is true' errors when a scene containing an Area is removed and re-added to the tree

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#41397]
**Godot version:**
3.2.2, but also reproduced in upcoming 3.2.3, in commit 9bf5a0b791faf8e960bdb07009b5fe8003206e4f on the 3.2 branch

**OS/device including version:**
Ubuntu Linux 16.04, 64-bit
GeForce GTX 970 with NVIDIA 384.130 driver
GLES3 backend
Bullet Physics

**Issue description:**
If you remove a scene containing an Area overlapping a few bodies, then re-add the same scene strange errors appear in the error log.

```
E 0:00:02.384   _body_enter_tree: Condition "!E" is true.
  <C++ Source>  scene/3d/area.cpp:123 @ _body_enter_tree()
  <Stack Trace> Reproducer.gd:23 @ _input()
E 0:00:02.384   _body_enter_tree: Condition "!E" is true.
  <C++ Source>  scene/3d/area.cpp:123 @ _body_enter_tree()
  <Stack Trace> Reproducer.gd:23 @ _input()
E 0:00:04.217   connect: Signal 'tree_entered' is already connected to given method '_body_enter_tree' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1515 @ connect()
E 0:00:04.217   connect: Signal 'tree_exiting' is already connected to given method '_body_exit_tree' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1515 @ connect()
E 0:00:05.167   _body_exit_tree: Condition "!E" is true.
  <C++ Source>  scene/3d/area.cpp:140 @ _body_exit_tree()
```

**Steps to reproduce:**
1. Run the reproducer
2. Press space when any of the kinematic or rigid bodies in the scene is inside the semi-transparent red Area
3. Wait a second
4. Close the window
5. Check the error log

**Minimal reproduction project:**
[Physics-RemovedNodes.zip](https://github.com/godotengine/godot/files/5103230/Physics-RemovedNodes.zip)

The Reproducer scene contains a number of physics bodies:
1. A green CSGBox providing a static collision
2. A semi-transparent red box, demarcating the boundaries of the Area in question.
3. A red bouncy ball (a RigidBody), set up to bounce in and out of the Area
4. A white capsule (a KinematicBody) scripted to move back and forth through the Area
5. A brown beam (a RigidBody on a HingeJoint) that is not relevant to this issue

When you press space, the scene is scripted to:
1. Pause the tree
2. Remove itself from the tree root
3. Wait 0.1 seconds (which may not be necessary?)
4. Then re-add itself to the root and unpause the tree

**Comment by akien-mga** [comment]
CC @madmiraal
