### ISSUE TITLE
HingeJoints stop working when the scene containing them is reparented

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#41398]
**Godot version:**
3.2.2, but also reproduced in upcoming 3.2.3, in commit 9bf5a0b791faf8e960bdb07009b5fe8003206e4f on the 3.2 branch

**OS/device including version:**
Ubuntu Linux 16.04, 64-bit
GeForce GTX 970 with NVIDIA 384.130 driver
GLES3 backend
Bullet Physics

**Issue description:**
Removing a scene containing a HingeJoint from the tree and then re-adding it causes the HingeJoint to stop working.

**Steps to reproduce:**
1. Run the reproducer
2. Observe the brown beam at the back of the scene swinging in the XZ plane, on a hinge
3. Press space bar to remove the scene from the tree for a split second
4. Observe that the brown beam collapses and falls out of the plane. The hinge is no longer affecting it

**Minimal reproduction project:**
[Physics-RemovedNodes.zip](https://github.com/godotengine/godot/files/5103230/Physics-RemovedNodes.zip)

The Reproducer scene contains a number of physics bodies:
1. A green CSGBox providing a static collision
2. A brown beam (a RigidBody on a HingeJoint) that is central to this issue
3. A white capsule (a KinematicBody) scripted to move back and forth, pushing the beam back on its hinge
4. The other elements of the scene are not relevant to this issue (they're for #41397)

When you press space, the scene is scripted to:
1. Pause the tree
2. Remove itself from the tree root
3. Wait 0.1 seconds (which may not be necessary?)
4. Then re-add itself to the root and unpause the tree

**Comment by akien-mga** [comment]
CC @madmiraal @AndreaCatania

**Comment by WilliamTambellini** [comment]
@akien-mga  could you please flag that one for a 3.2 bug fix release ?

**Comment by akien-mga** [comment]
Any bugfix relevant for the `3.2` branch will be considered once there is a fix (the PR gets the `cherrypick:3.2` label).

**Comment by madmiraal** [comment]
Related to #31711
