### ISSUE TITLE
Stereoscopic camera support - for google cardboard apps

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#4141]
Adding a Stereoscopic camera node to godot would allow developers to create google cardboard apps for the android and iOS app stores.

Currently godot is also missing support for gyroscope input. I filed that as a separate issue, since gyro has application in a wider spectrum of apps - not only vr/ar.
https://github.com/godotengine/godot/issues/4138

A stereoscopic camera simply splits the device screen into two screens - one for the left and one for the right eyes. The user can then put their mobile device into a google cardboard unit (costs 5$ on ebay) and use it as a VR headset. With some of the later models with better screen users can really get an experience closer to the more expensive headsets (oculus and vive).

My guess is that this is already becoming the widest spread form of vr experience because of it's low entry price tag. So supporting it in godot will open the engine to a new and vibrant market that is not saturated yet.
https://play.google.com/store/apps/collection/promotion_3001011_cardboard_featured_apps?hl=en

here is google's official plugin reference:
https://developers.google.com/cardboard/unity/reference#package_contents

**Comment by bojidar-bg** [comment]
It would also be nice to support other modes for stereoscopy, like red-cyan, etc.
Also, note that the might be solved by a simple way to make split-screen.

**Comment by william01110111** [comment]
Me and a friend have been working on a project for cardboard. We used two control nodes side-by-side with viewports in each. We put a camera under each viewport and then wrote a short script to make the cameras move with a spacial. Now all we have to do is move the spacial and we get nice 3D. We do need the gyro and are looking into implementing it ourselves.

**Comment by LikeLakers2** [comment]
Apologies for the bump, but isn't this now implemented by the `Native mobile` ARVR interface?

**Comment by akien-mga** [comment]
CC @BastiaanOlij

**Comment by BastiaanOlij** [comment]
Yeah I would say this has all been done ages ago :)

**Comment by TheWhiteLlama** [comment]
Is this relevant now? Google open sourced the cardboard source recently:
https://github.com/googlevr/cardboard
