### ISSUE TITLE
For loop increment/decrement inside the body doesn't work

### ISSUE THREAD

**Issue by c2titan** [godotengine/godot#41413]
**Godot version:**
3.2.2-stable_win64

**OS/device including version:**
Windows 10, 64bit

**Issue description:**
Trying to change the control value inside the For loop during a cycle doesn't work. 
_The While function does the job, but other languages normally support it in the For loop._

**Minimal reproduction project:**

![for-loop-issue](https://user-images.githubusercontent.com/69998248/90843874-e36b9480-e362-11ea-9d1b-8975d608ae64.jpg)

**Comment by Giwayume** [comment]
I'm not buying it. The same behavior is in Python.

![image](https://user-images.githubusercontent.com/4075314/90848856-e901b400-e33b-11ea-8805-568b753ef552.png)

for...in is meant to loop through the keys of something, an array or a dictionary. "i" is set to the next key in the array every loop iteration. This is how for...in is treated in any language.

For example, compare these Javascript for loops:
```
const array = [0,1,2,3,4,5,6,7,8,9];
for (let i = 0; i < array.length; i++) {
  i++;
  console.log(i);
}
```

```
const array = [0,1,2,3,4,5,6,7,8,9];
for (let i in array) {
  i++;
  console.log(i);
}
```

**Comment by c2titan** [comment]
I come from C/C++ where I used it often. Nevermind, I can do almost everything with While. 
It would be nice to mention this in the online documentation. I spent 2 days to debug my not working godot arrays, while they were working in C++ 🔢
