### ISSUE TITLE
MultiplayerAPI::_add_peer inserts into path_get_cache when a relevant PathGetCache already exists

### ISSUE THREAD

**Issue by ASavchenkov** [godotengine/godot#41412]
**Godot version:** 3.2.2 mono (also 3.2.3.rc.mono)

**OS/device including version: Windows 10 Build 19041**

**Issue description:**

When receiving some packets, the error

`ERROR: Invalid packet received. Unabled to find requested cached node.`
Building Godot 3.2.3.rc manually and debugging shows that:

~~When _process_simplify_path attempts to insert the NodeInfo it creates,
path_get_cache[p_from].nodes[id] = ni;
it fails to do so silently. (The key and value are not present in the map immediately afterwards.)
When stepping into Map._insert, I found that the value is missing a lot of the information (in the debugger) but this is where things go above my pay grade.~~

It turns out to be simpler than that. For some reason, MultiplayerAPI::_add_peer assumes no rpcs would have come in prior to _add_peer being called, but this is not the case.

**Steps to reproduce:**

1. Run three instances of the project manager (to keep terminal outputs separate)
2. Run the project in all three instances.
3. Press "Start" in the menu of one of them.
4. Press "Join" in the menu of a second one.
5. When the terminals calm down and start printing "NOMINAL" in both, press "Join" in the third.
6. It is highly likely to produce 
`ERROR: Invalid packet received. Unabled to find requested cached node.` in either the second or third instance.

~~**For setting the breakpoint just before the failure:**

1. Place a breakpoint at `path_get_cache[p_from].nodes[id] = ni;`
2. Condition ` id == 4`. (This is the cache id of the node that triggers this error in this project.)
3. And ` Hit Count = 1`. (The issue occurs when the second peer connects)
4. Attach to whichever instance you plan on pressing "Join" on last.~~

**Minimal reproduction project:**
I'm not sure how to guarantee this happens, so I'm leaving the most stripped down variant of my own project here.
~~Because I don't know why this is happening, I've struggled to make a smaller reproduction example. The project below is as minimal as I can reliably reproduce the error, but it still only happens approximately %70 of the time. There is only one node that triggers the issue in operation, but its path is identical on all peers, and even arrives correctly to `_process_simplify_path`.~~

This can occur with multiple nodes depending on how early their first RPCs arrive and how late _add_peer is called.

[Combined-Harms.zip](https://github.com/godotengine/godot/files/5105841/Combined-Harms.zip)

**Comment by ASavchenkov** [comment]
So **_add_peer** has this line of code `path_get_cache.insert(p_id, PathGetCache());`

implying that _add_peer needs to be called before any caching can happen,
but **_process_simplify_path** has

```
if (!path_get_cache.has(p_from)) {
		path_get_cache[p_from] = PathGetCache();
}
```

implying that the PathGetCache should be initialized only when it becomes necessary.

The latter seems to be the more elegant manner of operation (since if the peer isn't sending any RPCs, do you need a cache for it anyways?)

**Fix**
Simply deleting `path_get_cache.insert(p_id, PathGetCache());` from **_add_peer** solves the issue and doesn't step on any toes (as per my understanding so far).

**Comment by Calinou** [comment]
cc @Faless

**Comment by ASavchenkov** [comment]
I'd like to bump this topic since the bug has what seems to be a trivial solution. Is there something that needs to happen before I can make a pull request for this or can I just do it?

**Comment by akien-mga** [comment]
You can make a PR :)

**Comment by Faless** [comment]
I'm unable to run the test project (it seems never to connect?), anyway, can you try if this patch to the webrtc module fixes the issue?
```diff
diff --git a/modules/webrtc/webrtc_multiplayer.cpp b/modules/webrtc/webrtc_multiplayer.cpp
index 9df2420bbc..93f2b52775 100644
--- a/modules/webrtc/webrtc_multiplayer.cpp
+++ b/modules/webrtc/webrtc_multiplayer.cpp
@@ -147,6 +147,10 @@ void WebRTCMultiplayer::_find_next_peer() {
 	if (E) E = E->next();
 	// After last.
 	while (E) {
+		if (!E->get()->connected) {
+			E = E->next();
+			continue;
+		}
 		for (List<Ref<WebRTCDataChannel> >::Element *F = E->get()->channels.front(); F; F = F->next()) {
 			if (F->get()->get_available_packet_count()) {
 				next_packet_peer = E->key();
@@ -158,6 +162,10 @@ void WebRTCMultiplayer::_find_next_peer() {
 	E = peer_map.front();
 	// Before last
 	while (E) {
+		if (!E->get()->connected) {
+			E = E->next();
+			continue;
+		}
 		for (List<Ref<WebRTCDataChannel> >::Element *F = E->get()->channels.front(); F; F = F->next()) {
 			if (F->get()->get_available_packet_count()) {
 				next_packet_peer = E->key();
@@ -348,6 +356,9 @@ int WebRTCMultiplayer::get_available_packet_count() const {
 		return 0; // To be sure next call to get_packet works if size > 0 .
 	int size = 0;
 	for (Map<int, Ref<ConnectedPeer> >::Element *E = peer_map.front(); E; E = E->next()) {
+		if (!E->get()->connected) {
+			continue;
+		}
 		for (List<Ref<WebRTCDataChannel> >::Element *F = E->get()->channels.front(); F; F = F->next()) {
 			size += F->get()->get_available_packet_count();
 		}
```

**Comment by akien-mga** [comment]
@ASavchenkov Are you able to test the patch proposed by @Faless?

**Comment by ASavchenkov** [comment]
Just tested the patch, and it works as expected. Apologies for the late response. Had a slew of more urgent issues to deal with.
