### ISSUE TITLE
Texture altas import breaking sometimes - Cutting off sprite

### ISSUE THREAD

**Issue by Giwayume** [godotengine/godot#41414]
**Godot version:**
3.2.3.rc3

**OS/device including version:**
Windows 7

**Issue description:**
I have a specific set of images where changing their import settings to texture atlas causes them to be cut off in the atlas.

**Steps to reproduce:**
Check the reproduction project. All I did was select all the images and re-import them as an atlas file. Import mode doesn't make a difference. The result looks like this where half the sprite is cut off:

![atlas](https://user-images.githubusercontent.com/4075314/90847823-68da4f00-e339-11ea-9758-24f68c56bbd1.png)

**Minimal reproduction project:**
[atlas-bug.zip](https://github.com/godotengine/godot/files/5106577/atlas-bug.zip)

**Comment by Calinou** [comment]
@Giwayume Did you find a solution to this issue? Can you still reproduce this on 3.4?

**Comment by Giwayume** [comment]
Oh, I assumed at some point it started working because I have gotten past this point in my project, so I closed it. But no, looks like I never set up the atlas for this character. It's still broken in 3.4.

This is especially weird, since the atlas works great for literally every other sprite I've created.

**Comment by Rubonnek** [comment]
For what is worth, and for future reference to anyone stumbling upon this issue, as a workaround I wrote an [`EditorImportPlugin`](https://github.com/Rubonnek/godot-libgdx-texture-packer-atlas-importer) for [GDX Texture Packer GUI](https://github.com/crashinvaders/gdx-texture-packer-gui) some time ago.

The workflow to get the AtlasTexture would be a bit different since you'd have to first build the atlas with the GDX Texture Packer instead, then drop the spritesheet along with the associated `.atlas` file into the Godot project so that the importer can generate a set of `AtlasTexture` resources you can use.

I've been meaning to document the whole process in the plugin repository for a while but never got around to it. Maybe I will soon.

**Comment by Giwayume** [comment]
My first thought is maybe Image::get_used_rect() is failing somehow, but I recreated the bounding boxes in GIMP using the numbers it outputs during (Re)import and they're correct.

![image](https://user-images.githubusercontent.com/4075314/142339806-8f854060-510e-4405-be4b-8a27df02edd4.png)

![image](https://user-images.githubusercontent.com/4075314/142339938-e68a22eb-e03f-4d8f-8b05-9917b5cf2821.png)

Actually now that I look at it, the atlas region and margin appear to be correct if the atlas image itself didn't cut off the sprite.

![image](https://user-images.githubusercontent.com/4075314/142340180-dde77734-1e5e-40f4-974d-075fa80e3c6b.png)

This must be a problem when the importer draws the image to the atlas itself. We can assume the image data in memory is correct because it generated a good bounding box.

**Comment by Giwayume** [comment]
Ok I don't fully understand this code but I kinda see the problem.

https://github.com/godotengine/godot/blob/3.4/editor/import/resource_importer_texture_atlas.cpp#L134

In this line, "xf" starts at the left margin in the original sprite frame (source) image. Which in my case is a 512x512 image with the eyeball in the middle and a lot of empty space around it. This 512x512 dimension is set to the `src_width` and `src_height` variables respectively.

![image](https://user-images.githubusercontent.com/4075314/142348662-0770be02-8d24-4bda-aae0-7944a273a5b6.png)

The variables `width` and `height` in this function refer to the final atlas texture's width and height, which is 256x252 in this case. So the entire generated texture atlas (256x252) is smaller than a single source animation frame (512x512). That exposes this bug.

It looks like in this loop it's limiting by the generated atlas's width when it's actually looping through the source image's pixels.

`for (int xi = (xf > 0 ? int(xf) : 0); xi < (xt < width ? xt : width - 1); xi++) {`

So instead it should limit by the source image's width.

`for (int xi = (xf > 0 ? int(xf) : 0); xi < (xt < src_width ? xt : src_width - 1); xi++) {`

This indeed produces the correct results. And it makes sens why the images were getting cut off before.

![image](https://user-images.githubusercontent.com/4075314/142349072-f8a3335a-cbaa-405c-a64c-baad29d9a530.png)

I don't yet know the full implications of changing this line, though. The code doesn't seem to crash when I regenerate another atlas where the atlas size is much larger than a source animation frame size.
