### ISSUE TITLE
Tree item_selected event firing twice

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#4142]
**Operating system or device:**

**Issue description** (what happened, and what was expected):

When connecting item_selected to a function it fires that function twice

**Steps to reproduce:**

Connect tree to function, it will fire twice

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
The description is a bit short. How do you connect the three to the function? Via the editor, or via a script? If it's via a script, please give the code snippet. If it's via the editor, do you bind parameters or just bind ``item_selected`` to a function without anything specific?

When does it fire twice? When you connect the tree to the function? Or when you actually trigger the signal in game?

**Comment by EIREXE** [comment]
I bind item selected to a function in the editor, when I go in-game and I click an item in the list the function is called twice.

**Comment by EIREXE** [comment]
This seems to not happen anymore.

**Comment by volzhs** [comment]
@EIREXE did you check with Godot 3.0?

**Comment by EIREXE** [comment]
@volzhs yes
