### ISSUE TITLE
Collisionshape2D's disabled property is broken

### ISSUE THREAD

**Issue by MaxIsJoe** [godotengine/godot#41424]
**Godot version:**
3.2.2 Stable [STEAM]

**OS/device including version:**
OS : Windows 64-bit
CPU : AMD A6
GPU : AMD Radeon HD 7250G
RAM : 4GB

**Issue description:**
Collisionshape2D's "disabled" property does not change correctly while the game is running, if the game starts with the disabled property enabled and you try to change it to `disabled = true` during runtime the debug shapes (the blue indicators) will disappear but objects can still collide with the collisionshape as if it was still enabled.

**Steps to reproduce:**

1. Create a kinematicbody 2D then adding a collision shape to it
2. Via a script, create a function that disables or enables the collision shape manually. example : `$Door2/CollisionShape2D.disabled = false`
3. Call the function, can be done from a signal or any method.
4. While "Visible collision shapes" is enabled, you'll notice that the collision shape disappears
5. If you try moving an object that has a collision shape on it through that disabled collision the object will collide with the disabled collision shape as if it's still enabled.

**Comment by MaxIsJoe** [comment]
> 
> 
> @MaxIsJoe Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

[Issue-CS2D.zip](https://github.com/godotengine/godot/files/5116878/Issue-CS2D.zip)
I'm sorry it took so long! I was busy lately so I couldn't upload this.

this project contains a test scene with three different scenarios, one where the the collision shape is disabled normally by setting `disabled = true` and another using the method provided by @Xrayez and a scenario where the object is disabled from the start.

**Comment by madmiraal** [comment]
@MaxIsJoe In your MRP, your `RigidBodies` are going to sleep. You either need to wake them up by setting their `sleeping` property to `false`, or disable their `Can Sleep` property.

@Giwayume You appear to be describing a different issue. Please create a new issue and upload a Minimal Reproduction Project.
