### ISSUE TITLE
Comments trigger auto-complete.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#41438]
**Godot version:**

dbb0ad3b5

**OS/device including version:**

Win10 64-bit

**Issue description:**

When typing comments, auto-complete hints keep appearing.
From testing it seems to be a regression from 3.2.2.

![image](https://user-images.githubusercontent.com/13004169/90936732-78779780-e40e-11ea-9aba-2fb1ad17e7f7.png)

**Steps to reproduce:**
Start a comment in the build at the commit above.  Continue typing.

**Minimal reproduction project:**

None needed.

**Comment by akien-mga** [comment]
Fixed by #41451.
