### ISSUE TITLE
Running `--doctool` creates `logs` directory in the current working directory

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#41435]
**Godot version:**
3.2.3.rc

**OS/device including version:**
Windows 10

**Issue description:**
Generating documentation produces `logs` directory directly within root of project repository (I have the engine added as a submodule in a repository). Expected behavior: write to `user://` directory.

I guess the problem is similar to #40305.

The workaround is simply adding `logs` to `.gitignore` of course.

**Steps to reproduce:**
Running: `godot --doctool .` should be enough to reproduce this. The logs may end up directly in `bin` folder, but it depends on where you run the command from.

**Comment by akien-mga** [comment]
Still reproducible in current `3.2`.
