### ISSUE TITLE
CanvasItem.draw_line() width depends on display resolution

### ISSUE THREAD

**Issue by fractilegames** [godotengine/godot#4143]
When drawing lines in Node2D using `draw_line()` function, the line width seems to be in display pixels instead of node coordinates.

Line drawn with same width looks a lot wider on low DPI desktop than on high DPI Android device. Positions of lines work as expected.

I can fix this by multiplying the line width by `get_viewport_transform().get_scale().x`, but shouldn't the function take the line width in same units as the positions?

**Comment by akien-mga** [comment]
I tried this in the current master branch and it seems to behave fine as far as I understand (I don't have a HiDPI display to test, but I used a tool script to draw in the editor directly and changed the editor DPI scaling).

Test project: 
[draw_line_width.zip](https://github.com/godotengine/godot/files/2610914/draw_line_width.zip)

Closing as it's an old issue and might no longer be relevant now, but please comment if I misunderstood the issue and you can still reproduce it.
