### ISSUE TITLE
EditorPlugin do not correct preload scene, script functions not available

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#41445]
**Godot version:**
Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 980/PCIe/SSE2

**OS/device including version:**
Windows 10 / GLSES3

**Issue description:**
I try to build a editor plugin where adds a custom view/inspector into the editor UI on the top left side.
The plugin loads a predefined scene with attached script and custom functions
```
onready var _uiInspectorTab = preload("res://addons/gUnit/src/ui/TestRunnerResultView.tscn").instance()
```
The scene is instanciated but _ready() is never called and the scritpt variables are not initalisized
Second problem i can't access the script function an error is thrown
```
 res://addons/gUnit/src/GUnit.gd:27 - Invalid call. Nonexistent function 'initProgress' in base 'Control (TestRunnerResultView.gd)'.
```
 

**Steps to reproduce:**
a) Use the linked project and activate the plugin
see the console output 
```

Godot Engine v3.2.2.stable.mono.official (c) 2007-2020 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started ---
Szenentab wechseln
_ready [Control:21635] 17
initProgress
{args:[{class_name:, hint:0, hint_string:, name:, type:2, usage:7}], default_args:[], flags:1, id:0, name:initProgress, return:{class_name:, hint:0, hint_string:, name:, type:0, usage:524295}}
 res://addons/gUnit/src/GUnit.gd:27 - Invalid call. Nonexistent function 'initProgress' in base 'Control (TestRunnerResultView.gd)'.
```
seams the flag is missleading and should be 65 

b) use the TestA and run 
the preloades scene is correct loaded and _ready() is called
the script function is available
```
Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 980/PCIe/SSE2
 
_ready [Control:1192] 17
_ready [ProgressBar:1194] [Label:1195]
initProgress
{args:[{class_name:, hint:0, hint_string:, name:arg0, type:0, usage:7}], default_args:[], flags:65, id:0, name:initProgress, return:{class_name:, hint:0, hint_string:, name:, type:0, usage:7}}
initProgress [ProgressBar:1194] [Label:1195]
```

**Minimal reproduction project:**
[issue_editor_plugin.zip](https://github.com/godotengine/godot/files/5112176/issue_editor_plugin.zip)

**Comment by pouleyKetchoupp** [comment]
Can you try to add `tool` keyword in `TestRunnerResultView.gd` to make sure it runs in the editor? It seems to help.

**Comment by MikeSchulze** [comment]
you are right so can be closed
