### ISSUE TITLE
Editor Crash after opening project

### ISSUE THREAD

**Issue by VincentSinel** [godotengine/godot#41450]
# Godot version:
Godot Mono 3.2.2 Stable Win64
Even try on
Godot Mono 3.2.3-rc4 Win64

# OS/device including version:
Windows 10 64bit V1909

# Issue description:
The editor crash just after opening my project. I don't no how to reproduce it

[Evolution.zip](https://github.com/godotengine/godot/files/5112364/Evolution.zip)

**Comment by neikeq** [comment]
Can you open Godot from the command line and copy the output here when it crashes?

**Comment by ZackyGameDev** [comment]
I had the same issue when I would open a project and Godot would just crash, turned out that the project I was trying to open was running on OpenGL ES 3.0 Renderer, opening a project that was running on OpenGL ES 2.0 Renderer seemed to fix the issue for me.

**Comment by VincentSinel** [comment]
Sorry for the late response.
Pete-The-Penguin = > I don't know how to use MSBuild, Can you let me know ?
neikeq => How can i do it ? i try by the cmd but i cannot get return.

Finaly i make another project and copy everything from this one to the new one and all work fine.

Sorry for the english i'm not really use to.

**Comment by Pete-The-Penguin** [comment]
So the problem is fixed?

**Comment by VincentSinel** [comment]
It is fixed, but how have you changed the project to MSBuild ?

**Comment by Pete-The-Penguin** [comment]
In editor settings, if you scroll all the way down, you should find a
section called mono, inside mono is builds, that's how you change it to
msbuild.

**Comment by akien-mga** [comment]
Seems solved as per above discussion. Please comment if you still experience this issue.
