### ISSUE TITLE
Vehicle physics is broken with current Godot.

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4146]
**Operating system or device:**
Linux, but seems unrelated

**Issue description** (what happened, and what was expected):
Setup a car using the same parameters as in truck town demo.
Don't add collision shape. Use y-offset of 0 for the wheels from body, and setup
every wheel parameter to the same configuration as in demo.
Don't add collision shape yet, test your car - it should be stable on flat ground,
no jumping, just stationary.

**Steps to reproduce:**
Add collision shape (I used Box). The expected outcome is nothing changed in car behavior.
Actually, car starts to vibrate at high pitch rate. Delete collision shape - nothing changes, still vibrating and jumping around surface. The only way out is delete scene and start anew.
Not adding collision shape avoids this bug, but everything passes through your car then.

**Link to minimal example project** (optional but very welcome):
Will add if nobody can reproduce this.

It seems that other tweaking of parameters lead tho this problem, but it is quite random and unrelated,
as returning to known set won't fix it and problem still persists.

Video, demonstrating this bug: https://youtu.be/IzwvcN0Jbo0

**Comment by slapin** [comment]
Another workaround is replace the VehicleBody node with Spatial using UI button,
then *run scene once*, then replace it back with VehicleBody.

**Comment by slapin** [comment]
well, it seems you have to delete CollisionShape then use above workaround to get rid of vibration and jumpiness.

**Comment by slapin** [comment]
Single huge CollisionShape fixes this problem, it seems that stability depends on CollisionShape size,
which is really really weird.

**Comment by slapin** [comment]
it seems that everything depends on CollisionShape size, looks like the bigger the collision shape,
the more stable we are. Wiat it is used for? Momentum? At leas this should be configurable,
as adding one smaller CollisionShape  makes car go haywire.

**Comment by slapin** [comment]
At least some multiplier should exist to control this behavior...

**Comment by slapin** [comment]
Trying to setup vehicle Godot crashes without any errors specified. Console output:

CLOSING CONNECTION
TextureButton: 16,-4
Label: 108,63
HBoxContainer: 112,27
SAVING: res://vehicles/new_scene.scn
SAVING: res://vehicles/new_scene.scn
running: /home/slapin/godot/bin/godot.x11.opt.tools.64 -path /home/slapin/school-rage/main -rdebug localhost:6007 -p 0x0 res://vehicles/new_scene.scn
********* listening on port 6007
OK! 15
has connection!
has connection!
shit?: Connection reset by peer
ERROR: read: Server disconnected!

   At: drivers/unix/stream_peer_tcp_posix.cpp:276.
CLOSING CONNECTION

**Comment by slapin** [comment]
Well, I will stop digging on this, hope somebody will fix this can of worms.

**Comment by DriNeo** [comment]
Center of mass is a too critical setting.

If the center of the body shape is approximately the same of the body origin  the vehicle is stable.
But it must be desirable to set the center of mass as real cars.

**Comment by slapin** [comment]
The thing which troubles me most is car stability depending on collision shapes.
Also random problems requiring swapping VehicleBody to Spatial and back.

**Comment by Zireael07** [comment]
Is this still an issue?

**Comment by slapin** [comment]
Dunno, not used Godot for a long time now, and will not be able to for several months.
If anybody cares, please re-test. If not, feel free to close.

**Comment by Zireael07** [comment]
I'm seeing the vibrations on my project exported to 3.0 (strangely, no vibrations in 2.0).

This is in the same test project as #8651

**Comment by LinuxUserGD** [comment]
#12521

**Comment by akien-mga** [comment]
Closing as superseded by #12521.
