### ISSUE TITLE
Tool script changes to export var do not mark scene as unsaved

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#41465]
Godot version: Godot_v3.2-stable_win64

Tool script changes to exported var do not mark scene as unsaved.

Is there a way to mark the scene as unsaved manually?

test code:
```
tool
extends Node2D

export(bool) var bool_test:bool = false

var timer:float = 0.0

func _process(delta):
	timer += delta
	if timer > 4.0:
		bool_test = !bool_test
		property_list_changed_notify()
		print("changed bool_test")
		timer = 0.0
```

**Comment by KoBeWi** [comment]
That's just how tool scripts work. They can move, modify, remove and add nodes, but the editor will not detect it. You need to explicitly tell it that something was modified. It's not possible normally, you need an EditorPlugin and access editor's UndoRedo (not sure if it's possible).

So this is not a bug, but something for a [proposal](https://github.com/godotengine/godot-proposals).
