### ISSUE TITLE
Autocompletion triggers on numbers

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41479]
**Godot version:**

3.2.3 rc4

**Issue description:**

I noticed that autocompletion is overzealous recently. When you type any standalone number, it will suggest some class containing this number in name. Which often leads to accidental inserting.
![0LxKHJZ116](https://user-images.githubusercontent.com/2223172/90990377-49ddf600-e5a1-11ea-8be4-4cf2c9f1dfd1.gif)

**Comment by akien-mga** [comment]
CC @ThakeeNathees

**Comment by ThakeeNathees** [comment]
introduced by: #41318 a refactor of #36950 (one of my early PR)
fixed by : #41451

I have to run more tests before making anymore PR.

**Comment by akien-mga** [comment]
Fixed by #41451.
