### ISSUE TITLE
using emscripten fiber.h

### ISSUE THREAD

**Issue by unicomp21** [godotengine/godot#41478]
Are there any examples of godot using emscripten fibers?

https://emscripten.org/docs/api_reference/fiber.h.html?highlight=emscripten_fiber_swap

I realize mono has async/await, but thought I might give fibers a try.

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
Asyncify makes the code base much much bigger, causing significant drop in
performance, so I don't think it's a good idea.

**Comment by unicomp21** [comment]
Got it, thanks for the advice.  Just to be clear, if I did everything in c++ (ie no gdscript or mono), the c++ optimizer won't help shrink things?  On top of that, if I were to brotli compress everything, would I have a hope of getting something small? @Faless

**Comment by unicomp21** [comment]
In the spirit of exploration, where would I set the

-s ASYNCIFY

flag?  And one last question, has any thought been given to co_await support in c++20?

So far, this is the only place I've seen a co_await supporting implementation w/ tests ...
https://github.com/chriskohlhoff/asio/search?q=co_await&unscoped_q=co_await

**Comment by Faless** [comment]
> Got it, thanks for the advice. Just to be clear, if I did everything in c++ (ie no gdscript or mono), the c++ optimizer won't help shrink things?

See: https://emscripten.org/docs/porting/asyncify.html#optimizing



> In the spirit of exploration, where would I set the
> 
> -s ASYNCIFY

In `platform/javascript/detect.py` to both `LINKFLAGS` and `CCFLAGS`

> And one last question, has any thought been given to co_await support in c++20?

No, we don't support C++20, we don't plan to in the short term, and I'm not sure it would even work with emscripten
