### ISSUE TITLE
godot is totally broken (can't execute any scene)

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4147]
Godot finally broken for me completely.
It is unable to execute any scene and spews this on the console"

SAVING: res://vehicles/new_scene.scn
running: /home/slapin/godot/bin/godot.x11.opt.tools.64 -path /home/slapin/school-rage/main -rdebug localhost:6007 -p 0x0 res://vehicles/new_scene.scn
********* listening on port 6007
OK! 15
has connection!
has connection!
shit?: Connection reset by peer
ERROR: read: Server disconnected!

   At: drivers/unix/stream_peer_tcp_posix.cpp:276.
CLOSING CONNECTION
SAVING: res://vehicles/new_scene.scn
running: /home/slapin/godot/bin/godot.x11.opt.tools.64 -path /home/slapin/school-rage/main -rdebug localhost:6007 -p 0x0 res://vehicles/new_scene.scn
********* listening on port 6007
OK! 15
has connection!
has connection!
shit?: Connection reset by peer
ERROR: read: Server disconnected!

   At: drivers/unix/stream_peer_tcp_posix.cpp:276.
CLOSING CONNECTION
SAVING: res://vehicles/new_scene.scn
running: /home/slapin/godot/bin/godot.x11.opt.tools.64 -path /home/slapin/school-rage/main -rdebug localhost:6007 -p 0x0 res://vehicles/new_scene.scn
********* listening on port 6007
OK! 15
has connection!
has connection!
shit?: Connection reset by peer
ERROR: read: Server disconnected!

   At: drivers/unix/stream_peer_tcp_posix.cpp:276.

**Operating system or device:**
Linux

**Issue description** (what happened, and what was expected):

See above

**Steps to reproduce:**
Just do it.

**Link to minimal example project** (optional but very welcome):
Any demo will do.

**Comment by slapin** [comment]
Of course port 6007 is not occupied by anything.

**Comment by AlexHolly** [comment]
Working with the master branch over a few hours and it's all fine. I was only using network and gui stuff.

OS:Ubuntu 64-bit

**Comment by akien-mga** [comment]
> Steps to reproduce:
Just do it.

Please give some real steps to reproduce. "Just do it." does not mean anything, and _obviously_ Godot is not "totally broken" as most of us are using it just fine.

**Comment by slapin** [comment]
The requirement seems to be using RigidBodies and VehicleBodies (3D stuff).
As nobody use 3D stuff this will never be noticed, I found my way around
it, so I think it can be closed

**Comment by vichug** [comment]
i doubt "nobody use 3D stuff"

2016-03-30 14:16 GMT+02:00 Sergey Lapin <notifications@github.com>:

**Comment by slapin** [comment]
Well, 3D bugs are veryr rare to be found by anyone, so it is sad but true.
