### ISSUE TITLE
Unable to see AnimatedSprite frames in AnimationPlayer

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#41482]
**Godot version:**
3.2 branch commit dbb0ad3b59e4d9150d41a0f5177069224cb2f837

**OS/device including version:**

Arch Linux

**Issue description:**

Ran the `create_spriteframes.gd` script (included in the proyect) to create a new `SpriteFrames` resource but when using this resource the frame texture on the `AnimationPlayer` is not visible.

The following output is also shown on the console when attempting to add a keyframe into the `AnimationPlayer` track:
```
ERROR: track_find_key: Index p_track = -1 is out of bounds (tracks.size() = 1).
   At: scene/resources/animation.cpp:948.
ERROR: track_get_key_value: Index p_track = -1 is out of bounds (tracks.size() = 1).
   At: scene/resources/animation.cpp:1175.
ERROR: get_frame: Animation 'Null' doesn't exist.
   At: ./scene/2d/animated_sprite.h:88.
```

**Steps to reproduce:**
1. Open the attached project.
2. Click the AnimationPlayer node on the Scene tree.
3. Click on the Node2D node on the Scene tree.
3. On the bottom of the screen, click on "Animation" to bring up the `AnimationPlayer` track editor.
3. On Inspector, click on the only visible key with a green plus sign -- the `Frame` option to insert a frame into the track.
4. You'll get the `ERROR` messages mentioned above and the frame will not be visible in the track, but the animation can still be played in the AnimationPlayer and when the project runs too:

![novisibleframes](https://user-images.githubusercontent.com/8337880/90996660-6cfeaa80-e58d-11ea-9c07-db6059e71753.png)

It's worth pointing out that on the same project, if you use the Editor to create a new `SpriteFrames` resource and add an animation to it and a couple of frames, the texture of the frames will be visible in the `AnimationPlayer` track editor:

![visible_frames](https://user-images.githubusercontent.com/8337880/90996737-a2a39380-e58d-11ea-8424-e01f10853590.png)

**Minimal reproduction project:**

[AnimationPlayerTrackIDBug.zip](https://github.com/godotengine/godot/files/5115403/AnimationPlayerTrackIDBug.zip)

**Comment by Rubonnek** [comment]
Welp, turns out that what's happening here is that the current `SpriteFrames` is not picked up by the Editor for some reason, but after adding a track for the `AnimatedSprite` animation, everything works as expected.

This is only user-error on my end, not a real issue.

**Comment by akien-mga** [comment]
Well the error message is still something that should probably be fixed though, I could reproduce it too. I think it's due to using this plugin without having the proper set up to do so, but in this case the plugin should not appear/be usable.
