### ISSUE TITLE
setget in superclass ignores subclass override

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#41488]
**Godot version:**
3.2.2 stable

**OS/device including version:**
linux

**Issue description:**
Apologies if this is not a bug, but I have a scene/class defined with the following extern:

**StraightProjectile Superclass**
```
extends Area2D
class_name StraightProjectile
export(int) var speed = 420 setget set_speed

func set_speed(new_speed):
	speed=new_speed
```

If I subclass this as a new scene, with no new code and override the extern speed to 350 as in following picture:

**Subclass**
![image](https://user-images.githubusercontent.com/12863685/91041227-91976880-e607-11ea-9eee-c97e985f1932.png)

When I instance my new subclass the setget method on the superclass is being called setting the value to 420 but I cannot see it being called for 350 as set for the subclass.

**Instance variable during runtime**
![image](https://user-images.githubusercontent.com/12863685/91047975-d83e9000-e612-11ea-932e-305428780f99.png)

If I change the class to this:
```
extends Area2D
class_name StraightProjectile
export(int) var speed = 420
```
Then it works as expected and the subclass gets the value 350.

I don't know how setget is meant to work, but it seems wrong that setget is being called, in effect, during the construction of the instance and after the subclass changes its value. If I remove setget then inheritance order works as expected.

Thanks.

**Steps to reproduce:**
1. create class with extern setget
2. create subclass and override value in ide
3. run code and check value
4. profit

**Comment by TheDuriel** [comment]
presumably your setter function isnt actually setting the new value to speed. post code.

**Comment by chucklepie** [comment]
That is the code. I do not set the value anywhere else. The setter method
is being called automatically by the declaration line you see when the
subclass is instanced.

My subclass has the value overridden as per the screenshot, but is not
being set, or is simply being overridden by the super class.

**Comment by TheDuriel** [comment]
dont see code of set_projectile() anywhere.

**Comment by chucklepie** [comment]
I updated the original to make it clearer.

**Comment by Calinou** [comment]
> Maybe if I create a test project it may make it easier?

Yes. Please upload a minimal reproduction project whenever possible :slightly_smiling_face:

**Comment by TheDuriel** [comment]
Things seem to be working normally though?

setters are called when the scene is instanced, so as to set the value saved in the scene file.

**Comment by chucklepie** [comment]
Yes, but the subclass overrides this value as my picture. So the order
should be parent then child. However the node value override is not being
used and its still 420 not 350.

**Comment by TheDuriel** [comment]
Overriding variable declarations via inheritance is not a supported feature... so I'm not sure what you mean with subclasses overriding values in this context.

**Comment by chucklepie** [comment]
I mean in my subclass I set Speed to 350 via the inspector as image.

When I instance this node in code I can see the setter being called for the
default 420 as defined in the parent. So the value 350 is being ignored.

**Comment by chucklepie** [comment]
Okay, I found a mistake in my code. It is working as expected, the node overridden value does override the setget, so inheritance is working as expected.

Sorry for the wasted time.

**Comment by chucklepie** [comment]
Okay, I found a mistake in my code. It is working as expected, the node overridden value does override the setget, so inheritance is working as expected.

Sorry for the wasted time.
