### ISSUE TITLE
`get_collision_point` incorrectly returning `(0, 0, _)` against `QuadMesh`/`MeshInstance`

### ISSUE THREAD

**Issue by georgewsinger** [godotengine/godot#41496]
**Godot version:** 3.2 on Linux

**OS/device including version:** GLES3 + NVIDIA GTX 1080i

**Issue description:** I have a 3D Godot game in which I am raycasting against a `MeshInstance` with a `QuadMesh`. My goal is to get the precise `(sx, sy)` local X/Y coordinates on the `MeshInstance`/`QuadMesh` where the ray is intersecting.  To do this, I first grab the global coordinates via `get_collision_point`.  Unfortunately, the global x/y coordinates are consistently coming up as `(0, 0, _)` when I run the raycast through `get_collision_point` (technically this function returns a `Vector3`, but I don't care about the third coordinate in this context).

Is this a bug with godot? Or is there anything that must be done to a `MeshInstance` with a `QuadMesh` loaded in order to get collision detection like this to work as intended?

**Comment by Calinou** [comment]
@georgewsinger Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by georgewsinger** [comment]
@Calinou It's a fork of godot at https://github.com/SimulaVR/godot/commit/0ab1726b43dbe81c96d208a41a582435b76fd058, which I believe is godot 3.2

**Comment by pouleyKetchoupp** [comment]
Closing as there's no minimal project available.

If you can reproduce it in godot 3.2.3 stable or any later release, feel free to re-open with a minimal project to this case can be investigated.
