### ISSUE TITLE
HTTPClient status does not change when calling HTTPClient.close

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#41503]
**Godot version:**
--
<img width="400" alt="Screenshot 2020-08-25 at 17 47 50" src="https://user-images.githubusercontent.com/100964/91171929-19aa6a80-e6fb-11ea-93a9-82b1ab98fef7.png">

**OS/device including version:**
--
<img width="334" alt="Screenshot 2020-08-25 at 17 48 06" src="https://user-images.githubusercontent.com/100964/91171950-2333d280-e6fb-11ea-92a0-43ab03abc948.png">

**Issue description:**
--
I use HTTPClient to gather streaming data from a data provider.
I use a combination of a while loop and `client.get_status`, which then emits data on each new chunk that arrives.

In another thread, I call `client.close()`, expecting the `client` to show any status except `HTTPClient.STATUS_BODY`, but the status remains the same after closing the client.

**Steps to reproduce:**
--
`StreamProcess.gd`
```gdscript
	func stream(interface, remote_url):
		# Perform stream connection...

		while interface.get_status() == HTTPClient.STATUS_BODY:
			chunk = interface.read_response_body_chunk()
			if chunk.size() != 0:
				# Perform some extraction of payload
				# Emit signal that new data has been received
```

Somewhere else in the code (another thread)
```gdscript
interface.close()
```

I would expect that after calling `close()` the interface would no longer present `HTTPClient.STATUS_BODY` but rather something like `HTTPClient.STATUS_DISCONNECTED` but this is not the case.

**Workaround**
--
I've worked around this in my project by extending `HTTPClient` and adding a `running` toggle. I then check to see if the client should be `running` each iteration of the loop.

`CustomHttpClient.gd`
```gdscript
extends HTTPClient

var running = true
```

`StreamProcess.gd`
```gdscript
	func stream(interface, remote_url):
		# Perform stream connection...

		while interface.get_status() == HTTPClient.STATUS_BODY and interface.running:
			chunk = interface.read_response_body_chunk()
			if chunk.size() != 0:
				# Perform some extraction of payload
				# Emit signal that new data has been received
```

Now in another thread I can use:

```gdscript
interface.running = false
```

**Comment by jonbonazza** [comment]
I'm not so sure this is a bug but rather a limitation in the current design. Changing this would not be backwwrds compatible, so if we want to change it, we should consider doing so for 4.0 and noting the incompatibility

**Comment by tavurth** [comment]
@jonbonazza is there some reason you don't believe it to be a bug? Most code from my perspective should be multi-thread compliant. (Especially networking code).

This could also be tested in the same thread, I think but have not verified the bug exists in that case too

**Comment by jonbonazza** [comment]
@tavurth im not saying whether its a bug or not. Im saying im unsure. You are right that it probably should return status_disconnected, but it might not di so by design. It was just an observation.

If it IS by design, then changing it outside of 4.0 isn't possible since there may be people relying on this behavior.

We'd need @Faless to chime in to see if he has any thoughts.

**Comment by Faless** [comment]
> is there some reason you don't believe it to be a bug? Most code from my perspective should be multi-thread compliant. (Especially networking code).

In general, functions are not thread-safe, and the reason is that thread safety always has a cost (very high if you make everything thread safe). And you don't want to pay that price when you know you are always using a given resource in the same thread (i.e. most of the time).
The rule of thumb is that shared data across threads must be protected with [Mutex](https://docs.godotengine.org/en/stable/classes/class_mutex.html)es (or other synchronization techniques). This is also mentioned in the [Thread documentation](https://docs.godotengine.org/en/stable/classes/class_thread.html)

**Comment by tavurth** [comment]
Hmm then I would highly recommend flagging the network streaming components as `NOT_THREAD_SAFE` since this bug cost me, (and will likely cost other developers in future), many hours of debugging to find.

From my pespective there is a common use case to access the status of a `HTTPStream` from a separate thread. Using mutexes seems like a good alternative, but only if we protect those variables from being read in the wrong thread.

Perhaps some warning: `This variable is not thread safe` would suffice?

**Comment by Calinou** [comment]
> Hmm then I would highly recommend flagging the network streaming components as `NOT_THREAD_SAFE` since this bug cost me, (and will likely cost other developers in future), many hours of debugging to find.

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by tavurth** [comment]
Is there some way in Godot to track if a resource is being used in a thread which was not the creator? It would be nice to add a warning here if we start doing it accidentally

**Comment by Calinou** [comment]
@tavurth If that's not implemented already, I guess we'd have to add a "thread ID" property to Resource so we can compare it with the current thread ID in debug builds.
