### ISSUE TITLE
Improve 2D lights performance

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4151]
I use 2D lights a lot in my game, and noticed they impact FPS a lot (5 lights and more is enough), even with a tiny buffer (256).
Shadows projected by those lights don't change often, and most of them are static, so I expected a much lower FPS impact. 
Suggestions:
- Only update shadows when a change is really needed?
- Choice on the rendering technique? (is it a shader and a big quad? Or a shadow mesh like here http://www.redblobgames.com/articles/visibility/ ?)

My machine is a Window 7 64 bits, Godot 2.0.1, quad core i5, AMD radeon HD6670

**Comment by mhilbrunner** [comment]
Is this still the case with Godot 3.0?

**Comment by Zylann** [comment]
From a quick test it seems performance is ok with a handful of lights shown on screen.
But if I zoom out like this, things are getting slow (which I would expect with such a zoomed out setup):

![image](https://user-images.githubusercontent.com/1311555/32579087-faf1d2f8-c4df-11e7-9d6e-309c7d67b577.png)

I tested my old project in 2.1.4 and performance is roughly the same, though I changed my computer since...

**Comment by PJB3005** [comment]
I can't even put 4 lights next to each other on a tilemap without increasing my CPU usage by 40%, then killing my framerate. `Light2D` just seems *exceptionally* slow. I'm sure it's not an issue if you're *really* frugal on lights but it's still bad.

**Comment by akien-mga** [comment]
Would be nice to find ways to optimize it for 3.1.

**Comment by PabloNeirotti** [comment]
Really hope this issue gets taken care of on it's 2 year anniversary. It would be awesome.

I also found a huge performance drop by using several Light2D at the same time on the latest Godot. I can rely on Sprites that use Additive blending but normal maps don't react to them, naturally.

I don't know much about low level rendering, but does each light trigger another drawing call, or are all lights being merged into a single "layer" before applying it to objects and their normal maps? For instance, my lights only affect a single sprite that acts as a background, but the lights still tank the performance.

Cheers!

**Comment by PJB3005** [comment]
Lights are drawn in a forward manner, so yes, each "object" is drawn once per light + 1.

When you throw shadow casting into the mix it gets even worse, the shadow system doing 4 draw calls per occluder in range of a light.

**Comment by sicienss** [comment]
This is still an issue in Godot 3.1. I just discovered `Light2D`s are causing very volatile FPS changes in my project.

Working on Toshiba Satellite, Windows 8.

**Comment by Calinou** [comment]
> Maybe this can be fixed in 3.2, with the shift to Vulkan?

The Vulkan renderer will be implemented in 4.0, not 3.2.

Would it be possible to render 2D lights at a lower resolution and upscale the result? It won't look as good, but it could make them much faster.

**Comment by PJB3005** [comment]
I am pretty sure that would require some sort of deferred lighting approach inside the engine still, which in and of itself would already *significantly* increase performance.

Unless of course you mean "lower the resolution of the textures you assign to your `Light2D`s", which you *can* do but it won't help much.

**Comment by Chrisstar56** [comment]
When can we expect to see better performance regarding 2d lights?

**Comment by Phoenix1747** [comment]
At the moment it's set for 4.0 together with Vulkan.

**Comment by Chrisstar56** [comment]
Since I can't find an expected release date, how many months can I expect to wait?

**Comment by Phoenix1747** [comment]
Don't know, I guess it's done when it's done. Always have an eye on the milestone progress and be patient.

**Comment by mathias17** [comment]
I hope this issue is still under serious consideration. Light2D node is incredibly useful for 2D games, but my early tests are already returning worrying results.

Official word seems to be that the incoming 4.0 will save the day for Light2D node related problems.
See this post - https://github.com/godotengine/godot/issues/8685 and also notice the referenced issues at the bottom of the page.

**Comment by Calinou** [comment]
@mathias17 The 2D renderer was rewritten for 4.0. Performance should hopefully be much better there.

**Comment by mathias17** [comment]
> @mathias17 The 2D renderer was rewritten for 4.0. Performance should hopefully be much better there.

I appreciate the info! That helps.
And yes, I'm greatly anticipating the 4.0 improvements.

_Speaking of 4.0, I was about to make a new Godot github post today, but I'll ask you instead and maybe save unnecessary github management time -_ Do we yet know if the 4.0 Vulkan update will support additional texture maps for sprites/textures in 2D scenes, such as Roughness and Metallic?
Currently, we can use a diffuse/albedo map and a normal map, as seen here:
![image](https://user-images.githubusercontent.com/3425436/83331728-88dc0400-a25d-11ea-8bcb-70053352a1c6.png)

3D scenes now support the full PBR range of material textures, as seen here:
![image](https://user-images.githubusercontent.com/3425436/83331746-ac9f4a00-a25d-11ea-9311-61b28c531d3b.png)

In my opinion, adding Roughness and Metallic map support for 2D textures (I could make a case for AO as well) would be greatly beneficial for devs wanting to better control their game's aesthetics when using 2D lights.

Is there a status for adding more texture map support for 2D scenes, beyond albedo and normal?

**Comment by Calinou** [comment]
@mathias17 Light2D in 4.0 already supports specular maps, but not roughness/metallic. I don't think a PBR workflow really makes sense in a 2D context – what would consistute the environment to reflect?

**Comment by mathias17** [comment]
> @mathias17 [Light2D in 4.0 already supports specular maps](https://godotengine.org/article/vulkan-progress-report-2) (as well as adjusting the specular exponent), but not roughness/metallic maps.

_"...many users requested specularity in 2D lights, so the effect of lights moving around stage is more visible and more types of materials can be created. Because of this, it will be possible in Godot 4.0 to use specular and shininess both as parameter and as textures supplied to Sprite, AnimatedSprite, Polygon2D and other nodes."_

Aha. Thank you for the link. I was searching high and low for info about roughness maps, or something similar, in Godot's 2D scheme and overlooked this progress report post. This is all I need to know.

> I don't think a PBR workflow really makes sense in a 2D context – what would constitute the environment to reflect?

I agree - you can't 1:1 adapt a 3D PBR workflow to 2D. There comes a point when you just go full 3D. Could a 2D game really utilize an HDR skybox and still control lighting and colors as need be? I don't know; I'm an amateur when it comes to 3D. 2D scenes can use the CanvasModulate and WorldEnvironment nodes to do such things.

Calinou, thanks for being so helpful, as usual!

**Comment by lawnjelly** [comment]
As @Calinou says, Light2D is a boatload faster in 3.2.2 latest beta, for GLES2. As well as general speedup there are a lot of specific optimizations for lights. You don't mention whether this is GLES2 or 3.

I am working on GLES3, currently aiming for 3.2.3. This should do the same speedup for GLES3.

Also with the light_scissoring option in the batching, you no longer have to worry about sizes of sprites, that is handled automatically. :+1: 

Having said that, you may find you become fill rate limited once you are using batching (because of the multi pass approach to lighting). There's nothing I can easily do about that aside from the light scissoring.

**Comment by mathias17** [comment]
@lawnjelly Hey there. Thanks for chiming in! That's good news.

I have a question for you. [This dev snapshot](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-2), from May 7, states:
> ... The new 2D batching is only implemented for the GLES2 renderer, so if you use GLES3 you will not be able to benefit from it. **As the GLES3 renderer is being deprecated by Vulkan in Godot 4.0**, we currently don't plan to port the 2D batching to it. GLES2 batching is enabled by default both in-game and in the editor.

Are you saying that GLES3 may not be deprecated by the Vulkan 4.0 update?

**Comment by lawnjelly** [comment]
> Are you saying that GLES3 may not be deprecated by the Vulkan 4.0 update?

It is very up in the air at the moment, there is some more discussion here:
https://github.com/godotengine/godot-proposals/issues/877

But currently we are thinking along the lines of having vintage (GLES2, 2d only at least at first), compatibility (GLES3), and high and low end vulkan. The GLES2 and GLES3 backends though may be considerably different from the versions in 3.x, and emphasis will err on the side of compatibility rather than features (for advanced features vulkan makes more sense). As I say this is preliminary and subject to change.

**Comment by mathias17** [comment]
> ...high and low end vulkan.

Interesting. Thanks for the info. I understand these aren't firm decisions, so no worries there.

So, differing versions of the same renderer. Might this be similar to something like Blender's two rendering engines - Cycles and Eevee, which are different but partially compatible with each other? (When switching between Cycles and Eevee, some material tweaks are usually needed, etc.)

**Comment by Calinou** [comment]
@mathias17 Yes, although there will be less changes required compared to portinga project from GLES3 to GLES2.

**Comment by mathias17** [comment]
This thread has provided a good conversation regarding the Light2D node's performance and capabilities so far, but I wanted to add more one thing - Sprite Lamp style lighting effects.
I hope I'm not commandeering the thread.

---
[Sprite Lamp](http://www.snakehillgames.com/spritelamp/) is a tool that helps artists create texture maps for 2D graphics for the purpose of creating live dynamic lighting in-engine, without need for any 3D meshes or render pass baking. It goes a step further beyond just normal mapping and introduces more accurate shadow-casting/self-occlusion with a depth map (and other maps).
([Sprite DLight](http://www.2deegameart.com/p/sprite-dlight.html) is another similar tool, but I haven't tested it.)

[![Sprite Lamp demo](https://i.imgur.com/rv40Wfc.jpg)](https://youtu.be/XOgunCEN51A?list=PL_NjmXRhBbJ27yN9BW5umGnWL0CyJxCt-)
(see rest of youtube playlist if interested)

This is the depth map texture used inside Sprite Lamp for the blobby green character:
![image](https://i.imgur.com/qcH1qLm.png)

This is the depth and specularity map used for the "paincube" videos in the youtube playlist linked above:
![image](https://i.imgur.com/4sQVu9r.png)

_So I'm asking:_ Would it be advantageous for performance/optimization if Godot considered adding native support for additional maps (such as the maps used by Sprite Lamp's native shader, which you see in action in the youtube videos linked above) which then Godot's Light2D node could interact with?
Or would it be wiser to let users handle this stuff with [their own custom shaders](https://www.snakehillgames.com/using-sprite-lamp-with-engines/)?

Looks like specularity has already made the cut - it is supposed to be part of the 4.0 update. Basically the equivalent of a roughness map, in a PBR workflow.

Depth maps (in _this_ context) are different - they're specifically for 2D rendering. Comparable to a 3D height/bump map but assume an orthographic 2D camera.

---

Just putting this out there.
I'm honestly a beginner when it comes to this stuff, but wanted to expand the conversation with a few things I'm aware of, in the interest of helping Godot's 2D grow and improve.

**Comment by Calinou** [comment]
@mathias17 Feature proposals should be made on the [Godot proposals](github.com/godotengine/godot-proposals) repository, not here.

**Comment by mathias17** [comment]
> @mathias17 Feature proposals should be made on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository, not here.

Was mainly poking everyone for some feedback on the idea, but if you think it merits a proposal I may do that. I'm not sure.

**Comment by clayjohn** [comment]
For Godot 4.0 lights can be rendered in a single pass which should be enough to close this enhancement request. 

For Godot 3.2, we have introduced light scissoring to reduce the fill-rate requirements from multiple lights and batching to reduce the number of draw calls. 

Either way I would say this can be closed. If performance issues are still a concern after 4.0 has released we can revisit the topic again.
