### ISSUE TITLE
How to link bones and vertex?

### ISSUE THREAD

**Issue by Hromon** [godotengine/godot#41518]
**Godot version:**

3.2.2 mono

**OS/device including version:**

Window 10, gles2

**Issue description:**

How to link Skeleton(in 3D) bones to vertex in ArrayMesh?
I asked this question, but no one answered me. And the guys from the docks could not even name the class that is responsible for binding. Not to mention the process itself ...
![image](https://user-images.githubusercontent.com/29508584/91225884-f13b6400-e72c-11ea-8e29-ee5f5f93a12a.png)

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by Hromon** [comment]
Yes, I am asking a question here because you have not been able to answer it! And repeat it again!

> Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
> 
> (Also, [this isn't the first time you're asking support questions in repositories not designed for that](https://github.com/godotengine/godot-docs/issues/3771). This is your last warning.)
