### ISSUE TITLE
AnimationPlayer Key+1 button on Sprite node is annoying 

### ISSUE THREAD

**Issue by batmanasb** [godotengine/godot#4152]
**Operating system or device:**
Linux Mint 17.3

**Issue description** (what happened, and what was expected):
I'm making an animation using multiple sprites at once, but when I want to key a "frame" I have to press the "Key+1" button, which keys the frame number but then increments it and moves 1 step in the animation player. So I have to move 1 step back every time I key a frame so that I could continue working on that step. This process gets a very annoying when using 5 separate sprites, and wastes a lot of time. An option to remove it in the editor settings (or just remove it in general) would be appreciated greatly.

**Link to minimal example project** (optional but very welcome):
![selection_011](https://cloud.githubusercontent.com/assets/4187882/14063372/4698d074-f39c-11e5-9b21-5ef366b875b1.png)

**Comment by ondesic** [comment]
I completely agree!!!

**Comment by Krakean** [comment]
@akien-mga I suppose this should be archived since not reproducible any more
