### ISSUE TITLE
Visual Shader does not display Specular reflection from light source

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#41525]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Windows 10 v2004
Lenovo y710 Cube
Intel i7 6700
Nvidia GTX1080
16GB RAM

**Issue description:**
Visual Shader will not show a specular reflection caused by directional, omni or spotlight. A Spatial Material with identical properties (Roughness 0.2, Specular 0.5 for example) will show the specular just fine.
I have experimented with roughness maps and assigning values to Albedo/Specular/Roughness/Metalness via scalar constants and uniforms, along with checking the light, world and project settings. Nothing seems to allow specular to appear on a VisualShader material.

**Steps to reproduce:**
- Load the attached project
- Load "Main Scene"
- The "VisualShader" object DOES NOT show a specular for the directional light
- The "Spatial Material" object DOES show a specular for the directional light
- Both materials have identical settings for Specular and Roughness
- Both materials reflect the default world environment just fine

**Minimal reproduction project:**
[VisualShaderSpecular_Bug.zip](https://github.com/godotengine/godot/files/5126863/VisualShaderSpecular_Bug.zip)

**Comment by WickedInsignia** [comment]
Update:
Blinn, Phong and other specular modes appear to work. SchlickGGX does not show a specular in any diffuse modes, whereas the others will.
It's also worth taking note that the default diffuse mode for VisualShaders is Lambert, whereas the default for PBR workflows and SpatialMaterial is Burley.

**Comment by clayjohn** [comment]
It looks like when you set diffuse to burley or specular to schlick_ggx the visual shader does not insert the render mode at all. However, the shader assumes that you will have at least one specular render mode set. 

Im guessing something in the logic here is rejecting the first render_mode in the list: 

https://github.com/godotengine/godot/blob/6b5102cf907c7c1bae1e866a794bae1cc02d0fae/scene/resources/visual_shader.cpp#L1248-L1273

CC @Chaosus

**Comment by WickedInsignia** [comment]
I've no idea about shader code so I won't be much help on that front, but very happy to test things if anyone takes a shot at a fix.

**Comment by mohammedzero43** [comment]
This looks like its related to this
https://github.com/godotengine/godot/pull/12091

**Comment by Chaosus** [comment]
Ok, I take a look

**Comment by Chaosus** [comment]
@WickedInsignia 
![image](https://user-images.githubusercontent.com/3036176/91289540-27173180-e79b-11ea-8237-ecb421fef661.png)

To be honest, I don't see a difference between those two (Windows10/GTX1060), maybe a problem somewhere else?

**Comment by WickedInsignia** [comment]
@Chaosus You need to rotate the scene around so the sun is facing the camera.
The object on the right (SpatialMaterial) will show a specular for the sun. The object on the left (VisualShader) will not.
Something is not initiating the specular in Visual Shaders with GGX.
![GodotSpecularExample](https://user-images.githubusercontent.com/70243134/91290227-b7269c80-e7d6-11ea-937c-d895a69c9965.JPG)
