### ISSUE TITLE
BaseButton property "enabled_focus_mode" is redundant

### ISSUE THREAD

**Issue by FIF15** [godotengine/godot#41529]
**Godot version:**

3.2

**OS/device including version:**

no specific

**Issue description:**

#4300 added a prop to BaseButton called "enabled_focus_mode" for setting the focus mode for enabled buttons. At that time, buttons would set focus mode to FOCUS_NONE on disabling and set to "enabled_focus_mode" when enabling. However, #16152 removed above logic, but leaving the prop "enabled_focus_mode" there.

Currently, this prop is really confusing that it would not have any effect when calling "BaseButton::set_enabled_focus_mode" on a disabled button without any warning, and has the exactly same behavior as the "Control::set_focus_mode" on an enabled button.

**Comment by Calinou** [comment]
Removing a property technically breaks the API, so we can remove it in the `master` branch but not in the `3.2` branch.

**Comment by FIF15** [comment]
> Removing a property technically breaks the API, so we can remove it in the `master` branch but not in the `3.2` branch. In the `3.2` branch, we can deprecate it by making it a no-op still: #41471

Sounds good. Should I make these changes or someone would do that?

**Comment by Calinou** [comment]
@FIF15 Feel free to open a pull request to do that :slightly_smiling_face:

**Comment by akien-mga** [comment]
I agree with the proposal, #16152 did remove the only use of `enabled_focus_mode` so currently this property is a no-op. It doesn't affect anything.
