### ISSUE TITLE
Creating convex collision from a mesh results in duplicate vertices

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#41522]
**Godot version:** 3.2.3 RC4

**OS/device including version:** Windows 8.1

**Issue description:** If you go to Mesh|Create Convex Collision Sibling, there are duplicate vertexes in the convex collision shape.  For example, if you create a cube mesh, there will be 24 verts instead of 8.

**Steps to reproduce:**
- Click on a cube mesh.
- Click the mesh menu.
- Create single convex collision sibling
- Look at the collision shape and notice the array size is 24 instead of 8.

**Minimal reproduction project:**
[convex_collision_too_many_verts.zip](https://github.com/godotengine/godot/files/5126790/convex_collision_too_many_verts.zip)

**Note:** I'm working on a fix for this in 3.x, but the code is slightly different in the main branch because pool vectors were removed.  It's just a matter of ignoring verts that are in the same location, because the mesh has duplicate vertices for faces with different normals/uvs/etc.

**Comment by mortarroad** [comment]
Is there any reason against just replacing quickhull with the convex hull algorithm from Bullet?
That one might be more stable?

**Comment by Calinou** [comment]
> Is there any reason against just replacing quickhull with the convex hull algorithm from Bullet?
That one might be more stable?

Bullet may not always be compiled in Godot – in fact, it's planned to move it to a GDNative add-on in the future.

**Comment by mortarroad** [comment]
> Therefore, we'd need to manually copy Bullet's convex hull algorithm to be able to use it even when Bullet is disabled.

Is that not an option? Given that our current algorithm seems to be broken in multiple ways?

**Comment by Calinou** [comment]
> Is that not an option? Given that our current algorithm seems to be broken in multiple ways?

It is, but adapting Bullet code to use Godot's data types may not be trivial.

**Comment by mortarroad** [comment]
@Calinou It seems that Bullet's convex hull algorithm is already ported and used in the "vhacd" module, but only used for convex decomposition.
Would it make sense if I adapt it, so it can be used in place of QuickHull?

**Comment by Calinou** [comment]
> Would it make sense if I adapt it, so it can be used in place of QuickHull?

Sure :slightly_smiling_face:

**Comment by mortarroad** [comment]
Turns out this issue is unrelated to QuickHull.
The collision shape simply stores all the vertices from the source mesh; the convex hull algorithm is only run at a later point in time.

**Comment by Zireael07** [comment]
@mortarroad: This doesn't make sense - why use QuickHull at all if the collision shape just skips past it?

**Comment by mortarroad** [comment]
QuickHull is only used in the physics server:
https://github.com/godotengine/godot/blob/3d649d37f8891ff273f5630bb7e9ff842c02f855/servers/physics/shape_sw.cpp#L1152

The resource itself does not apply QuickHull.

**Comment by jitspoe** [comment]
It might make sense to run the data through quickhull before storing it so unnecessary verts aren't kept.  The fundamental quickhull algorithm is fine, but there's an issue with the way it tries to maintain edges for display purposes:
1) Unnecessary if only used for collision and the visual is unneeded.
2) Sometimes multiple triangles on the same plane bug it out and create errors: https://github.com/godotengine/godot/issues/45946

Simply replacing quickhull would mean something else would need to be used for generating the visuals to display the collision.

**Comment by mortarroad** [comment]
> Simply replacing quickhull would mean something else would need to be used for generating the visuals to display the collision.

Well, I suppose we would use whatever we replaced QuickHull with... :P 
Like in the PR I made: https://github.com/godotengine/godot/pull/47307

**Comment by jitspoe** [comment]
> 
> 
> > Simply replacing quickhull would mean something else would need to be used for generating the visuals to display the collision.
> 
> Well, I suppose we would use whatever we replaced QuickHull with... :P
> Like in the PR I made: #47307

Ah, cool.  Didn't realize that algorithm saved the edges.  I do have concerns about it possibly being imprecise, though.  Commented in the other thread, but the vhacd algorithm used by the mesh convex_decompose had issues, and I had to switch back to using QuickHull.

**Comment by jitspoe** [comment]
Just a note that https://github.com/godotengine/godot/pull/48533 superceeds the other quickhull replacement.  I imagine it would probably be faster to remove duplicates before running the quickhull algorithm, though.  I can submit a pull request for that (was hesitant to, since the data formats changed for 4.x, but it seems 3.x is still being actively updated).
