### ISSUE TITLE
Sometimes, button signals don't work with "compiled" scripts

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#41545]
**Godot version:**
Current release candidate as well as the previous release candidate
3.2.3 rc3 and rc4

**OS/device including version:**
Windows 10, all export types as far as I can tell

**Issue description:**
For some reason, when exporting https://github.com/WolfgangSenff/GWJ2YrAnniversary on my Windows 10 machine with the "compiled" option for my scripts set, for Windows or Linux (have not tested Mac export yet), the first button in this game does not work. However, if I set it to "text" scripts in the export options, it does work.

**Steps to reproduce:**

1) Download from repo below
2) Export game for Windows with embedded pck (not sure if relevant) and "compiled" scripts, which should be the default
3) Run the executable
4) You can skip the cut scene or watch it because it's cute
5) Tap the first button; it will not transition to the actual game play
6) To prove this is only on export, run the game from the editor and tap on the same button following the same steps; it works just fine.

**Minimal reproduction project:**
I have been unable to test this for a minimal project, but the below definitely seems to have the issue for me. Sorry it's lorge. If needed, I can attempt to make something that reproduces this in a much smaller project, just haven't had time.

https://github.com/WolfgangSenff/GWJ2YrAnniversary

**Comment by akien-mga** [comment]
> **Godot version:**
> Current release candidate as well as the previous release candidate
> 3.2.3 rc3 and rc4

Does it mean that it's a regression which did not happen in 3.2.2-stable, or you only tested those two versions?

**Comment by WolfgangSenff** [comment]
Sorry - only tested the two latest versions, have not tried 3.2.2.

One thing I forgot to mention also: this occurs both when connecting the signal in the editor as well as separately through code.

**Comment by Calinou** [comment]
@WolfgangSenff Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
