### ISSUE TITLE
Future of html5 in Godot? Might it completely be removed?

### ISSUE THREAD

**Issue by DanielLausch** [godotengine/godot#41544]
Hello,

i just want to get some clarification, as the following is not clear for me:

> Until the OpenGL ES 3 renderer is removed from Godot in favor of Vulkan, HTML5 export uses WebGL 2 when the GLES3 option is selected.
> 
> Warning
> 
> Using WebGL 2 is not recommended due to its expected removal from Godot without replacement.

**Source:** https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_web.html

Well, it seems clear that OpenGL ES 3 will be removed, same as WebGL 2.

But what means "in favor of Vulkan", will Web export become possible BECAUSE/USING the Vulkan API, or will Web export basically completely be removed from Godot (because of Vulkan) ?

Cheers

D

**Comment by Calinou** [comment]
The GLES2 renderer (and WebGL 1.0) are here to stay.

That said, Safari is working on adding WebGL 2.0 support (at last). See also discussion in [this proposal](https://github.com/godotengine/godot-proposals/issues/877).

**Comment by DanielLausch** [comment]
Thank you for your statement! I didn't know a better place than here to ask my question.
I will follow your request to post "question like this" on other "community channals" in the future...
