### ISSUE TITLE
get_simple_path() navigates to unconnected navmesh

### ISSUE THREAD

**Issue by hodgej** [godotengine/godot#41546]
**Godot version:**
3.2 stable

**Issue description:**
get_simple_path will navigate to a navmesh very far away, and cause the node navigating to go outside the current navmesh. I'm trying to have each node linger about it's dedicated island, but they keep navigating crazy paths. [Here's an example](https://youtu.be/WbxX-RjAQNY)

You can see one of the black dots (which are the nodes doing the navigation) navigate across navmeshes, doing a crazy long path, going outside the bounds of the navmesh, to a relatively close point inside the intended navmesh "island".
Even if I surround each island with other tiles, creating one large navmesh, it still does crazy paths: [Example of this](https://www.youtube.com/watch?v=2fpTzq3sfcw)

_A simple fix for this issue would be allowing the user to specify what navmesh the node is allowed to navigate on in the `get_simple_path()` function._

**Steps to reproduce:**
Create separate islands with a tilemap navmesh (different tiles per island), place several nodes who have a simple script creating paths and following them, but only tell the nodes to navigate to random tiles of the type they are dedicated to. In order to navigate to a tile inside their current tilemap, a path is generated to another island navmesh and back.

**Comment by Calinou** [comment]
Note that [Godot 4.0 will feature a new NavigationServer which likely solves this issue.](https://github.com/godotengine/godot/pull/34776)

**Comment by vpellen** [comment]
I believe this is caused by `Navigation2D::get_simple_path` using `Geometry::is_point_in_triangle`, which returns false for points on the edges of triangles, causing endpoints that intersect with triangle edges to be counted as "outside the mesh", causing weird snapping issues.

**Comment by hodgej** [comment]
Apologies for that, mistakenly clicked "close issue".

**Comment by smix8** [comment]
@Calinou
@akien-mga 
This weird pathfing issue was for the old 2D navigation before 3.5 and is no longer valid.

In Godot 4.0 and 3.5 the 2D navigation uses the same navigationmesh based pathfinding as 3D behind the scene. As long as the NavigationPolygon is created correctly this pathfinding issue no longer happens. In fact the 2D paths have the same path optimization as 3D now.
