### ISSUE TITLE
GDScript: resolved return type with if/else is wrong

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41540]
**Godot version:** a609b30

**OS/device including version:** windows 10

**Issue description:**
Resolved suite type for "if" block with "else" is set to the type of the first return statement, but It needs to be resolved between those "else/else if" suites.

**Steps to reproduce:** try the below code.
![Capture](https://user-images.githubusercontent.com/41085900/91301895-41fd9c00-e7c3-11ea-92ee-e2f6d9fc558a.JPG)

**Comment by ThakeeNathees** [comment]
![Capture](https://user-images.githubusercontent.com/41085900/92014192-74336e80-ed6c-11ea-94f0-aaf7f745b19c.JPG)

**Comment by lyuma** [comment]
Seems fixed on latest master (85186bc)
