### ISSUE TITLE
PopupMenu size doesn't respect usable screen size

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#41564]
**Godot version:**
master b0ca859501186b6fa088a3d3542f7dd4d72ae305

**OS/device including version:**
Linux (Ubuntu 20.04)
Also reproduced on Windows 10

**Issue description:**
PopupMenu items sometimes expand outside of the usable desktop space, either on top or behind decorations like task bars depending on the desktop system.

Example with Ubuntu/Gnome, the menu can show behind the top bar and the dock (when set at the bottom):
<img src="https://user-images.githubusercontent.com/1075032/91466657-be5db100-e88f-11ea-82dc-f99e9b08226d.png" width="200" />

**Steps to reproduce:**
Simple repro case in the editor:
- Make an export variable of type Resource
- Click the resource load button in the inspector
- Scroll up and down through resource types

**Minimal reproduction project:**
[popup-menu-size-bug.zip](https://github.com/godotengine/godot/files/5137521/popup-menu-size-bug.zip)

**Comment by EricEzaM** [comment]
The strange thing for me is that sometimes the popup does respect the bounds, and sometimes not. For example, when right-clicking in the File System Dock near the bottom, the popup will go under the taskbar (WIN10). However, if I open a popup menu in the inspector which is near the bottom of the screen, it will respect the bounds.

No good:
![image](https://user-images.githubusercontent.com/41730826/91503402-b3496600-e90d-11ea-8d3a-55b7d2cbbd86.png)

Just fine:
![image](https://user-images.githubusercontent.com/41730826/91503413-bba1a100-e90d-11ea-8218-6572796b9bb8.png)
