### ISSUE TITLE
Gradient editor displays bright magenta background instead of checker background for transparent colors

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#41561]
**Godot version:** Git https://github.com/godotengine/godot/commit/7a62b94bcae4da685144ce11aa6f1c8ad19b7c71

**OS/device including version:** Fedora 31, GeForce GTX 1080 (NVIDIA 440.100)

**Issue description:**

The Gradient editor fails to display its checker background for transparent colors and will display a bright magenta color instead.

![image](https://user-images.githubusercontent.com/180032/91448820-a7609400-e87a-11ea-9613-a76e984bdd3e.png)

This GUI component is drawn by [scene/gui/gradient_edit.cpp](https://github.com/godotengine/godot/blob/master/scene/gui/gradient_edit.cpp).

**Steps to reproduce:** Create a Gradient resource in the Inspector dock by using the New Resource button, then edit one of its points to have an alpha value lower than 1.0.

**Minimal reproduction project:** N/A

**Comment by callumW** [comment]
Hey there,

I'd like to take a crack a this no one minds?

I've got a potential fix in place but I'm not sure if it's exactly what is wanted:

![image](https://user-images.githubusercontent.com/5477252/95665190-e48c9700-0b45-11eb-9865-e943442c7835.png)


I assume it would better if it matched the color picker sample area?

![image](https://user-images.githubusercontent.com/5477252/95665214-274e6f00-0b46-11eb-84e0-2b38399b745b.png)

**Comment by Calinou** [comment]
@callumW That's a good start, but it ideally, it should display a repeating checkerboard like this:

![image](https://user-images.githubusercontent.com/180032/95666518-bc5b6300-0b5a-11eb-899b-d7177d58073c.png)


That's how it looks in 3.2.3.

**Comment by callumW** [comment]
Cool, I think that would look better too. I'll take a look 😀 

It looks like the color picker is a little broken too as it doesn't repeat like that, rather it displays stretched out as shown above.

Should that be raised as a separate issue or fixed in this one?

**Comment by Calinou** [comment]
@callumW What do you mean by the color picker being broken? Other than the "pick" icon being offset, I don't see any differences.

If you meant the checkerboard texture stretched instead of repeating, that's something you need to reimplement in your PR.
