### ISSUE TITLE
Crash after soft body point assigned to an AnimationPlayer node

### ISSUE THREAD

**Issue by lennyco** [godotengine/godot#41560]
**Issue description:**

Expected a warning

**Steps to reproduce:**
if you have an attachment point of a capsule shaped soft body and you assign an animation player to that spatial attachment path Godot will instantly crash

**Comment by Calinou** [comment]
@lennyco Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by qarmin** [comment]
Closing due no reply from OP
