### ISSUE TITLE
Client StreamPeerTCP::get_status() returns STATUS_CONNECTED even after server close

### ISSUE THREAD

**Issue by ShrewdSpirit** [godotengine/godot#4157]
**Operating system or device:**
Win10 x64
Godot commit [15d1fca](https://github.com/godotengine/godot/commit/15d1fca0614ad87fd16fa7532e4db867b342d00e) branch master

**Issue description**:
I'm checking if a client StreamPeerTCP connection is still alive in _process by checking its status but it seems that it doesn't know if server is shutdown because after I close the server, it still returns STATUS_CONNECTED. The server is netcat (Tried Hercules too) but the problem is from Godot and StreamPeerTCP::get_status()

**Link to minimal example project**:
[Client code](http://dpaste.com/2V7PYAJ)

**Comment by reduz** [comment]
in theory you have to check reading or writing for a conection to be alive. I know there are a few workarounds you can do to check if something disconnected, but haven't implemented them.
If anyone wants to add this be welcome

**Comment by reduz** [comment]
maybe some function to check this would work? or should check be done during  get_status()

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
What's the status in the current master branch?

**Comment by Fulkman** [comment]
What about this? Any hopes that this will be done pretty soon?

**issue update**

**Operating system or device:**
MacOS 10.13

**Comment by akien-mga** [comment]
CC @Faless

**Comment by Faless** [comment]
For what I know the only two ways of detecting a broken TCP connection (disconnected without completing the FIN-ACK sequence) are to either try and send data or wait for the keepalive to auto detect it.
We could expose the TCP keepalive setting, but the real solution would be in most cases to include your own keepalive messages in the application protocol.

`recv` is not a reliable way to detect disconnects unless you really expect something and receives 0 meaning a clean close was received (this is done in Godot using `get_partial_data`).
http://man7.org/linux/man-pages/man2/recv.2.html#RETURN_VALUE

**Comment by VitaZheltyakov** [comment]
https://github.com/godotengine/godot/issues/15393
