### ISSUE TITLE
Editor Menus and Text Entry Boxes Appear at Origin

### ISSUE THREAD

**Issue by duane-r** [godotengine/godot#41578]
**Godot version:**
master v4.0.dev.custom_build.1ff139cb2

**OS/device including version:**
OS: Archlinux, AMD ryzen integrated graphics, mesa driver
Window manager: Openbox (only)

**Issue description:**

All of the editor's popups appear at origin (upper left), though they tile, to make room for more. The first screenshot shows tabbing through the rectangle entries in a textrectangle. The second just shows the help menu opening in the wrong place. Submenus will open up below the menu.

![2020-08-28-051924_1920x1080_scrot](https://user-images.githubusercontent.com/14078065/91551299-8c7c3700-e8ef-11ea-989f-44862703a1d5.jpg)

![2020-08-28-052000_1920x1080_scrot](https://user-images.githubusercontent.com/14078065/91551371-a61d7e80-e8ef-11ea-8edc-8d109482a8aa.jpg)

![2020-08-28-053518_1920x1080_scrot](https://user-images.githubusercontent.com/14078065/91551794-63a87180-e8f0-11ea-9e51-cf7579e11a3b.jpg)

**Steps to reproduce:**

**Minimal reproduction project:**

Edited for form.

**Comment by Calinou** [comment]
I can't reproduce this on commit https://github.com/godotengine/godot/commit/118a7bc53f32b8303b70886eee7ea090c3d327f0 (Fedora 31 KDE, GeForce GTX 1080).

**Comment by duane-r** [comment]
Still doing it on a25818072. I'm using openbox window manager. I can try putting kde on to see if anything changes. I can't do anything about my integrated graphics though. : )

**Comment by mohammedzero43** [comment]
Are u using dwm or i3 windows manager? 
It will be funny if the wm treats every menu as a new window thus it pins it to the top

**Comment by duane-r** [comment]
> Are u using dwm or i3 windows manager?

Just openbox, but that might be the problem.

Ok, it works perfectly in kde, so presumably the bug is limited to lxde and openbox users. However, Godot 3.2 doesn't have this issue at all.

**Comment by Calinou** [comment]
> However, Godot 3.2 doesn't have this issue at all.

This is a regression from the DisplayServer refactor which allows Godot to display multiple windows.

**Comment by duane-r** [comment]
As a workaround, you can set placement/policy/UnderMouse in openbox's configuration file, which at least puts the popups close to where your mouse is.
