### ISSUE TITLE
Why does my game boot to a weird unopenable white tab on my laptop?

### ISSUE THREAD

**Issue by vader-coder** [godotengine/godot#41572]
**Godot version:** 3.2.2 stable

**OS/device including version:** Windows 10 Home, OpenGL 4.5

**Issue description:**

When I try 'Play (F5)' or 'Play scene (F6)' from inside the editor, I just get a white tab that I cannot open. When I try to click on the tab, nothing opens. The tab is titled ProjectName (DEBUG). The issue remains whether I use the mono v3.2.2 64-bit, the standard v3.2.2 64-bit, or standard v3.2.2 32-bit. Here is a [video](https://streamable.com/xd011f) of the error. Oddly enough, the same game does work when I run the project from the launch screen and select "Run."

**Steps to reproduce:**
Steps are in the [video](https://streamable.com/xd011f).

**Minimal reproduction project:**
The game only needs to include a main scene to reproduce the error. 

[Minimum.zip](https://github.com/godotengine/godot/files/5139549/Minimum.zip)

**Comment by Calinou** [comment]
If you use a NVIDIA graphics card, do you have any specific USB devices plugged on your PC? See https://github.com/godotengine/godot/issues/20566.

**Comment by vader-coder** [comment]
> If you use a NVIDIA graphics card, do you have any specific USB devices plugged on your PC? See #20566.

I have an Intel(R) UHD Graphics 620 GPU.

**Comment by knadoor** [comment]
Hi @vader-coder , what is your monitor screen resolution? 

If it's high res, such as 4K screen (like mine) try this and see if it works:

1 - Under Project Settings search for "hidpi"
2 - In Display/Window, ensure "Allow Hidpi" is checked
3 - In Gui/Theme, ensure "Use Hidpi" is checked.
4 - Reload the scene

**Comment by vader-coder** [comment]
> Hi @vader-coder , what is your monitor screen resolution?
> 
> If it's high res, such as 4K screen (like mine) try this and see if it works:
> 
> 1 - Under Project Settings search for "hidpi"
> 2 - In Display/Window, ensure "Allow Hidpi" is checked
> 3 - In Gui/Theme, ensure "Use Hidpi" is checked.
> 4 - Reload the scene

This worked! Thank you so much. :)

**Comment by knadoor** [comment]
> > Hi @vader-coder , what is your monitor screen resolution?
> > If it's high res, such as 4K screen (like mine) try this and see if it works:
> > 1 - Under Project Settings search for "hidpi"
> > 2 - In Display/Window, ensure "Allow Hidpi" is checked
> > 3 - In Gui/Theme, ensure "Use Hidpi" is checked.
> > 4 - Reload the scene
> 
> This worked! Thank you so much. :)

Happy to hear that :)

**Comment by Calinou** [comment]
Duplictate of https://github.com/godotengine/godot/issues/13017 (the underlying issue is the same).
