### ISSUE TITLE
Default mapping of Xbox One controller on Linux is incorrect

### ISSUE THREAD

**Issue by SeleDreams** [godotengine/godot#41595]
**Godot version:**
Godot 3.2.2 flatpak package

**OS/device including version:**
Pop OS 20.04

**Issue description:**
My Xbox One controller was detected, however the right axis had issues getting properly detected, the horizontal axis was making the camera rotate vertically and the vertical axis didn't have any effect

**Steps to reproduce:**
plug in the xbox one controller then test in game

I was able to fix the issue by manually adding this mapping to my project : 

`Input.add_joy_mapping("030000006f0e0000b802000001010000,XInput Controller,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,",true)
`

**Comment by akien-mga** [comment]
It seems like this mapping is not known to the SDL DB we use: https://github.com/gabomdq/SDL_GameControllerDB

Could you contribute it upstream following their instructions? https://github.com/gabomdq/SDL_GameControllerDB#create-new-mappings
Then we'll get support for it next time we sync the DB.

CC @madmiraal @27thLiz

**Comment by SeleDreams** [comment]
I see, I'll do it, thanks

**Comment by SeleDreams** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/pull/380#event-3712081919 It's been merged

**Comment by akien-mga** [comment]
Thanks! Fixed by a61cae1469 (`master`) and 9be924c454 (`3.2`).

**Comment by shackra** [comment]
A new Xbox controller was added to the db according to this PR: https://github.com/gabomdq/SDL_GameControllerDB/pull/383

It seems I can add the mapping myself per  https://github.com/godotengine/godot/issues/41595#issue-688505531 but to make that available for everyone using Godot should I present a PR or a new issue would do it?
