### ISSUE TITLE
Exporting Shape Settings to CollisionShape2D

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#416]
Hey there,
I have created a mockup for a simple ui enhancement. At the moment the shape settings are very hidden in the shape resource itself. You need to open the shaperesource to adjust the shape settings. It took me about 3 month to discover this. Before I always adjusted the shape via the nodes scale values, which resulted in very bad physics behavior.

In this screenshot I show how this can be exported to the main CollisionShape2D node. Depending on which shape is selected the appropriate shape values are shown.
I also thought if maybe removing the scale vector from that node, but I don't know if that should be done, or to just set it inactive or something like that.

![collisionshape_ui_enhancement](https://cloud.githubusercontent.com/assets/6723918/2962884/4ad1e252-dad5-11e3-839b-66231c5a22d0.png)

**Comment by akien-mga** [comment]
I like this idea, I think most of us got bitten by this funky scale parameter because we hadn't noticed that CollisionShape2Ds must be edited after opening the shape resource. @ndee85's proposal looks pretty cool, it should probably just be offset a bit to the right to show that it's dependent on the CollisionShape2D part.

**Comment by bojidar-bg** [comment]
Not sure if this is still doable or viable in 3.0, can someone check if so?

**Comment by akien-mga** [comment]
Given that #5555 implemented exactly what is proposed here and was rejected, I guess we can close this proposal. I think the UI in 3.0 is already much friendly in this regard anyway.
