### ISSUE TITLE
Renaming a non-existent file will remove existing file if it has the same name as the new one

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41623]
**Godot version:**

3.2.3 rc4

**Issue description:**

Just try this code:
```
func _ready() -> void:
	var file := File.new()
	file.open("res://test.tres", File.WRITE)

func _process(delta: float) -> void:
	var dir := Directory.new()
	dir.rename("res://test.tres", "res://test404.tres") #this makes the file disappear on second (failed) rename
```

**Comment by simpuid** [comment]
Read the docs of `Directory`. It advises to use `Directory.open` before using any operation.
And close the file after writing, maybe renaming the file while it was already opened was causing this problem.
Here the modified working code (working at least on my machine)
```
func _ready() -> void:
	var file := File.new()
	file.open("res://test.tres", File.WRITE)
	file.close()

func _process(delta: float) -> void:
	var dir := Directory.new()
	if dir.open("res://") == OK:
		dir.rename("res://test.tres", "res://test404.tres")
```

**Comment by KoBeWi** [comment]
> Here is the modified working code (working at least on my machine)

Doesn't work for me, same effect.
I'm using Windows 10.

**Comment by simpuid** [comment]
Ooops! My bad, I tried it on master.

**Comment by KoBeWi** [comment]
Same issue on master. What is your OS? Maybe it's Windows-only bug.
