### ISSUE TITLE
File.open autocompletes enum from _File

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41622]
**Godot version:**

3.2.3 rc4

**Issue description:**

![DklUxw1kSb](https://user-images.githubusercontent.com/2223172/91661175-9c0ba380-eada-11ea-99fc-6ea525e0fcba.gif)

**Comment by vnen** [comment]
Wait, this is in 3.2? @ThakeeNathees maybe this related to one of your changes to code completion?

**Comment by ThakeeNathees** [comment]
this is reproducible since 3.2.0-stable. possibly https://github.com/godotengine/godot/pull/26990 will fix this.

**Comment by vnen** [comment]
Oh, so it's older. But the namespace change won't be added to 3.2. This needs a workaround like what happens for other cases.

**Comment by me2beats** [comment]
Still in 3.4 beta. I can see many newcomers get confused when they see this in completion popup then get the error

**Comment by akien-mga** [comment]
This is fixed in 4.0 by using a proper namespace for these core singletons. But a workaround for `3.x` would still be good.

**Comment by HolonProduction** [comment]
Not reproducible in v3.6.stable.official [de2f0f147], closing this as completed.
