### ISSUE TITLE
G4.0 CSG Polygon - Path Assign is Impossible

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#41624]
**Godot version:**

Godot 4.0 calinou's nightlybuild (f10c3810b)

**OS/device including version:**

Windows 10

**Issue description:**

CSG Polygon in Path mode doesn't allow Path to be assigned to it, works in 3.2.2.

**Steps to reproduce:**
1. Create CSG Polygon
2. Set CSG Polygon to Path Mode (from Depth)
3. Create Path
4. Try to Assign Path on CSG Polygon
5. Notice Path is Grayed Out

**Minimal reproduction project:**

Not Needed, as the bug is easy to reproduce and is not some special edge case causing the bug, but rather probably the Renaming of the "Path" to "Path3D" Causing an issue with CSG Polygon looking for Path and not recognizing Path3D as Path. Other Such cases could be out there Where something is expecting a Node type that has been renamed

**Comment by Calinou** [comment]
> Not Needed, as the bug is easy to reproduce and is not some special edge case causing the bug

Please upload a minimal reproduction project even if a bug is easy to reproduce. Not everyone has ~15 minutes to spend to set up a test scene only to start trying to reproduce a bug :slightly_smiling_face:

**Comment by mrjustaguy** [comment]
Fine.. took me 2 mins to make it from scratch (as it isn't a complex scene at all), and that includes zipping it and all which took up half that time..
[MRP.zip](https://github.com/godotengine/godot/files/5147233/MRP.zip)
