### ISSUE TITLE
Using screen shader causes all other shaders to turn the screen area they cover blank if they also use screen

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#41627]
**Godot version:**
3.2.2 stable

**OS/device including version:**
GLES 3
Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768 60Hz, 1920x1080i 60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 19.2.8 

**Issue description:**
I am using a screen shader (i.e. SCREEN_UV, SCREEN_TEXTURE, etc) on multiple nodes with the same shader code and all is well, even with 'unique' turned on for the material and shader.

However, as soon as I use a different shader code that references the screen texture, all other shaders turn blank.

1. This is my screen, on the entire hand screen I am running a basic distortion on the screen covering the screen and all is well. Don't worry if you can't see it, it's a static image :)

![image](https://user-images.githubusercontent.com/12863685/91665479-cd419f00-eaed-11ea-9920-1c1351969fe8.png)

2. I can run multiple versions of this shader (even with 'unique' enabled) and there are no issues, however I have another screen shader below. As soon as I enable the shader all other shaders turn their entire area blank.

![image](https://user-images.githubusercontent.com/12863685/91665508-067a0f00-eaee-11ea-9824-3d925e3bfc71.png)

**Steps to reproduce:**
1. Create a shader than reads from the screen
2. Use the shader below
3. Use them.

In the new shader I don't even have to do anything, as soon as I create a texture from the screen it fails, even if it isn't used:

```
void fragment() {
	vec4 color=COLOR;
	vec4 color_not_even_used = texture(SCREEN_TEXTURE, SCREEN_UV, 0.0);
	//vec4 color_not_even_used = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0);

	COLOR = color;
}
```

Here is a sample shader that turns blank when the above is activated:
```
void fragment(){
    vec2 p_m=SCREEN_UV.xy;
		
    vec2 p_d = p_m;
    p_d.y -= TIME * 0.1;
		
    vec4 dst_map_val = texture(iChannel1, abs(cos(p_d)));
    vec2 dst_offset = dst_map_val.xy;
    dst_offset -= vec2(.5,.5);
    dst_offset *= level;	
    dst_offset *= 0.01;
		
    dst_offset *= (1. - p_m.y);
    vec2 dist_tex_coord = p_m.xy + dst_offset;
    COLOR = texture(SCREEN_TEXTURE, dist_tex_coord);
}
```

**Minimal reproduction project:**
If one is required I will produce it.

**Comment by chucklepie** [comment]
Sorry, it's not texturelod, but something else specific to this one shader I've left the code for. Using it turns all other shaders blank.

**Comment by chucklepie** [comment]
I've found the problem. In the first shader method, as soon as COLOR is assigned to color, it blanks all other areas, as if COLOR in this shader is affecting all others. If I remove the final line COLOR=color; then everything works fine, so it isn't the grabbing of texturelod/texture or anything else, simply the assignment.

**Comment by clayjohn** [comment]
I'm guessing you are forgetting to use backBufferCopies? The engine only takes a snapshot once for use in SCREEN_TEXTURE. It grabs the screen as it is right before the shader using SCREEN_TEXTURE is run. Here it looks like your second screen shader is overriding the first, and worse it's reading from a SCREEN_TEXTURE that doesn't contain everything. 

My guess is you just need to add a backbuffercopy before each time you use the SCREEN_TEXTURE. 

For more info please read the tutorial on screen space shaders https://docs.godotengine.org/en/stable/tutorials/shading/screen-reading_shaders.html

**Comment by chucklepie** [comment]
Hello, sorry, I read that but didn't quite understand it. I thought the
node was for using the back buffer in normal code, but for shaders it
automatically used it.

Is there any concrete examples of how I should code using this mode?

**Comment by clayjohn** [comment]
> Is there any concrete examples of how I should code using this mode?

Yes in the screen reading shaders document it shows you how to use the backbuffercopy node. https://docs.godotengine.org/en/stable/tutorials/shading/screen-reading_shaders.html

Note that the backbuffercopy is only ever accessed as SCREEN_TEXTURE from shaders.

**Comment by chucklepie** [comment]
Hello, 
Thanks. What I did was (I have a flip screen) added a BackBufferCopy as a child to my camera, set the rect to the screen size and it just magically works.

Maybe the docs need updating for clueless people like me to simply say this ;)

But thanks, you can close the case.
