### ISSUE TITLE
ERROR: can_process: Condition ' !is_inside_tree() ' is true. returned: false

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#4162]
Linux

When I run my project it works fine but in debugger window I see this

![bug3](https://cloud.githubusercontent.com/assets/7677575/14075890/b9a82eda-f4e5-11e5-8a4e-df3c8207ae8e.png)

And I don't known this is bug in my code or bug in engine..

Count of messages increment cyclically every frame
No regular repeated. Some times catch

![bug1](https://cloud.githubusercontent.com/assets/7677575/14075806/0491ecb6-f4e5-11e5-9532-4796ea14fa19.png)

![bug2](https://cloud.githubusercontent.com/assets/7677575/14075834/3cb897c0-f4e5-11e5-9be9-9c5657a8e985.png)

**Comment by bojidar-bg** [comment]
Note, the error is coming from https://github.com/godotengine/godot/blob/e46e43d2aaa6339a1675eb989f41885e745bf5c3/scene/main/node.cpp#L413

**Comment by reduz** [comment]
there really is not much information here to proceed, a sample project would be appreciated

**Comment by hilfazer** [comment]
Sample project:
https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/DebuggerSpamsIsInsideTree

Place a breakpoint at 'pass', run the project and choose the 'node' variable in Debugger so it shows in Inspector.

Message isn't untrue but it's incredibly annoying.

**Comment by akien-mga** [comment]
@hilfazer It would be better to open a new issue specific to inspector an out-of-tree node in the debugger. You get the same error as this old issue, but it's unlikely that it's the same bug (OP was not debugging, just playing the game).

There's not much info to know what to make of OP's report, so closing.
