### ISSUE TITLE
Uninitialized primitive types have nil value

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41631]
**Godot version:**

db5ea78b7

**Issue description:**

```
var test: float
print(test + 1)
```
![image](https://user-images.githubusercontent.com/2223172/91669015-dfcdcf80-eb11-11ea-905c-1290ee4001a1.png)

**Comment by Sslaxx** [comment]
So what should the default behaviour be? Should a variable declaration like this be implicitly meant to contain `0`, `0.0`, `null` etc depending on type? If there's no type defined?

**Comment by KoBeWi** [comment]
Built-in types (`float`, `int`, `Vector2`, `Array` etc.) should have a default 0/empty value. They have it in 3.2.x and any other version, so this is obviously a regression.
