### ISSUE TITLE
Object count increases quickly when pressing any keyboard input while tree is paused

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#41643]
**Godot version:**
3.2.2.stable.mono/3.2.3.rc3.mono

**OS/device including version:**
Windows 10 GLES3

**Issue description:**
When the scene tree is paused, pressing any keyboard input causes the Object count to rapidly increase. This happens whether or not any/all nodes are set to "Process". These Objects are never freed from memory.

**Steps to reproduce:**
1. Make a new gdscript or C# project.
2. Make a `_ready()` method. 
3. Call `get_tree().paused = true` in the method. 
4. Run project. 
5. Press any keyboard button.
6. Watch the Object counter go up.

**Minimal reproduction project:**
[PauseTest.zip](https://github.com/godotengine/godot/files/5148060/PauseTest.zip)

**Comment by akien-mga** [comment]
@neikeq `InputEvent`s are not GC-ed when the tree is paused?

**Comment by markdibarry** [comment]
I'm not sure about all `InputEvent`s. This only occurs when pressing any keyboard input, whether or not they're set to an action. This does not occur when pressing any joypad inputs or mouse movement.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/41543.

**Comment by markdibarry** [comment]
I just reviewed the linked issue. While it might be related, there's no way (that I can find) to manually dispose of only InputEventKey objects without overriding an `_Input()` method. Even if you do create an `_Input()` and manually dispose of the event, the objects still collect, so I'm assuming its something deeper.

**Comment by neikeq** [comment]
Just tested and I was able to reproduce on a build without the mono module enabled.

I changed the script to this for easily confirming the objects are freed after setting paused back to false:

``` GDScript
extends Node2D

func _ready():
	print("paused = true")
	get_tree().paused = true
	yield(get_tree().create_timer(10), "timeout")
	print("paused = false")
	get_tree().paused = false
```

It's not only keyboard input but mouse input too, like mouse movement and I suppose any input kind too.

**Comment by neikeq** [comment]
BTW, I tested on Windows 10. Not sure if it's reproducible on other platforms.

**Comment by markdibarry** [comment]
Just an update that this memory leak is still present in Godot 3.4.2, but oddly not in Godot 4.0 master. Further testing needed.

**Comment by IIGreed** [comment]
I was experimenting this problem but what happended was that my project.godot was missing the lines:

> [physics] 
> common/ennable_pause_aware_picking=true

I tested with the standalone version 3.4.4 and 3.5 r5 and new projects made with those versions come with the flag set by default and that seems to fix the problem so I think this issue has being solved for some time.

**Comment by markdibarry** [comment]
Haven't heard anyone else having this issue in 3.x in awhile, and with 4.0 released, I feel it's safe to close.
