### ISSUE TITLE
Vulkan: Dynamic VoxelGI is not working

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#41642]
**Godot version: 4.0 git commit f10c3810bb0abfa18b1a579ee927f460bf191b6d

OS: Archlinux latest (Nvidia GTX 1060/64 GB RAM/Intel Core i7)

Issue description: When i make a project that use a baked GI floor and dynamic cube with emissive red light dynamic GI and bake the GI the dynamic GI doesn't work.

Steps to reproduce:
- Create a new project
- Make a floor with a material (white for example)
- Make it gi baked
- Add a light
- Make a cube and add a red material and emissive color with an intensity 5.0f
- Make it GI dynamic
- Add a GIProbe
- Bake the GIProbe
- The dynamic GI Cube doesn't work (the emissive doesn't work and does not get reflected to the floor.

Minimal reproduction project: In attachments
[MyTestProject.zip](https://github.com/godotengine/godot/files/5148054/MyTestProject.zip)

**Comment by Alexia-AT-Digitecnology** [comment]
Same error persist with VoxelGI element in Godot_v4.0-dev.20210820_linux. 

Attachment in message:

[MyNewProject.zip](https://github.com/godotengine/godot/files/7038439/MyNewProject.zip)

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.dev.custom_build [52b7d5fa3] (Linux, GeForce GTX 1080). Closing.

https://user-images.githubusercontent.com/180032/143779270-4ccd925a-00ed-4e55-b72b-bb27f7790f8b.mp4
