### ISSUE TITLE
Collision between two circular KinematicBody2Ds

### ISSUE THREAD

**Issue by rohanrhu** [godotengine/godot#41655]
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
Circular KinematicBody2D vs KinematicBody2D collisions are does not behave correct.

**Steps to reproduce:**
Add two kinematic bodies and circular shapes to them.

Hi, I'm sending the problem that i see when my first try on Godot. I have got a GIF and just remember. The problem is between two kinematic bodies with circular shapes. GIF describes the problem.

I think about "We must never use two kinematic bodies together" but i thought this is a problem.

![kinematic-collision](https://user-images.githubusercontent.com/1125150/91761107-099ff880-ebdd-11ea-9af7-43589b69b58f.gif)

**Comment by Calinou** [comment]
@rohanrhu Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by pouleyKetchoupp** [comment]
Closing for now as there was no update.

Feel free to re-open if the issue can be still reproduced in 3.2.3 or a later release and you can provide a minimal project.
