### ISSUE TITLE
File Selector seems to be unresponsive in 3.2.3 RC

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#41660]
**Godot version:**
Latest (3.2.3 RC) fad1feb3a

**OS/device including version:**
Manjaro 20.1 KDE

**Issue description:**
File Manager Path shows blank, and clicking "OK" does nothing.

**Steps to reproduce:**
![2020-08-31 18-08-02 mp4](https://user-images.githubusercontent.com/14253836/91777503-9f279200-ebb5-11ea-8f74-8626906b94c3.gif)

**Minimal reproduction project:**
N/A

**Comment by avencherus** [comment]
Might be related, but cannot create a new project from the New Project button.

Keeps saying this after selecting a folder.

![image](https://user-images.githubusercontent.com/13004169/91848058-47476480-ec63-11ea-8dc1-b182f8f06bc2.png)

**Comment by akien-mga** [comment]
Confirmed on Linux. That didn't happen on 3.2.3 RC 4.

**Comment by akien-mga** [comment]
Regression from #41520 (CC @Tony-Goat @Paulb23).

**Comment by akien-mga** [comment]
Fixed with 7844775a76 (`master`) and 8a66ea7cb0 (`3.2`).
