### ISSUE TITLE
Openssl generate sha and salt

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#4166]
I am looking for a way to generate sha strings and rand_bytes (salt) to make my passwords safe.

Godot is already using openssl. Is it possible to support these functions?

**Comment by primesoftware** [comment]
You would probably have to expose that functionality on the C side of things. I started working on a simpler system using mbedTLS about a month ago. I had 2 other projects come up that made me have to put that on hold, but I should be finished with those soon. Does mbedTLS sound like it would work for you? If so, I'll see what I can do about exposing that functionality.

**Comment by AlexHolly** [comment]
Is mbedTLS going to replace Openssl in godot? It would be nice to have a long term solution.

Right now my project is no big deal, I could switch between Openssl/mbedTLS anytime.

**Comment by bojidar-bg** [comment]
@akien-mga @AlexHolly Given that sha256 is already avaiable from #5250, should this issue be close, and another one be opened for secure random?

**Comment by AlexHolly** [comment]
If #5250 works I would agree and open a seperated issue for "rand_bytes (salt)".
I had no time to test it but I see that it is already merged so if any bugs occur I will open a new bug issue.
