### ISSUE TITLE
Godot does not enable the remote debugger on HTML5 export

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#41663]
**Godot version:**

3.2.2

**OS/device including version:**

Manjaro Linux

**Issue description:**

When deploy with remote debug is enabled, after clicking on the HTML5 deploy button that uses a local server, godot does not attempt to connect to the remote instance. 

**Steps to reproduce:**
Try to debug an html5 build

**Minimal reproduction project:**

**Comment by Faless** [comment]
Debugging HTML5 exports is not supported in `3.x`.
But will be in `4.x` when it's out (see #33925 and #37099 ).
