### ISSUE TITLE
There is no way to delete an audio resource

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#41670]
**Godot version:**

3.x.x all versions

**OS/device including version:**

win10 64 home

**Issue description:**

Unable to download an audio resource loaded into any node in the "AudioStreamPlayer" family.
This means that you assign an audio file to the node and at runtime, if you want to assign a new audio file to the node, there is no way to delete the old one. There is no Stream.UnloadResource () method.

**Steps to reproduce:**
In an AudioStreamPlayer node map an audio file to the node.
At runtime delete the previously assigned audio file and assign a new file.
You will not be able to download the assigned audio file because there is no method for that.
So what happens to the old assigned resource when I assign a new audio resource?

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Unused resources are automatically freed, so if you change the assigned audio file, the old one is freed if it's not used anywhere else.

**Comment by Torguen** [comment]
Ohh, thanks!.
