### ISSUE TITLE
Tile edge issue in 2d stretch mode

### ISSUE THREAD

**Issue by qdwang** [godotengine/godot#41696]
**Godot version:**

3.2.3 rc4 mono

**OS/device including version:**

Godot Engine v3.2.3.rc4.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Intel(R) UHD Graphics 620

**Issue description:**

There will be an tile edge issue in 2d stretch mode when resizing the window. Please check the picture below.
The problem won't happen at 100% size of window.
Using `pixel snap` can fix this issue, but my goal is to create a HD 2d game not a pixel game.

![godot_tile_edge_issue](https://user-images.githubusercontent.com/403616/91926157-2f2a2080-ed09-11ea-84f8-6a7b53af15f5.png)

**Minimal reproduction project:**

[GodotIssueTest.zip](https://github.com/godotengine/godot/files/5159793/GodotIssueTest.zip)
The tile png is also in the zip file. The only 2 tiles are both 64x64 pixels with crisp edges.

**Comment by lawnjelly** [comment]
I can't check out your project this week, as I'm away from home, but from the screenshot this looks similar to the issue solved in GLES2 with #39256.

Is this using the nvidia_workaround in GLES3 by any chance? This might be more susceptible to precision bugs than the legacy method (TEXTURE_RECT).

Some other options : 
* Use GLES2 batching (with uv contract in project settings)
* add padding to your textures around each tile.

1 pixel should be enough if used only at normal magnification (no mipmaps) but 4 pixels probably better if you are using compressed textures.

**Comment by qdwang** [comment]
1. I'm not using nvidia wordaround.
2. Using GLES2 batching with uv contract won't fix this issue.
3. I believe that adding padding to the textures will solve the problem, but i hope this issue can be fixed.

**Comment by qdwang** [comment]
This textureatlas png is auto generated by godot, which should have a 4x4 offset and 7x7 separation. It looks like the tileset renderer will change the texture a little bit. And the edge become blur. 

The issue won't happen if I direct use the 64x64 texture file.

![image](https://user-images.githubusercontent.com/403616/92198232-6aae2180-eea6-11ea-8f08-2a8e1302f9a7.png)

**Comment by lawnjelly** [comment]
Am back now and have had a look at the min reproduction project.

The tile atlas is set with `filter` to on. This will give bilinear filtering but will require padding that matches the edge colours of the tiles. The alternative is to turn off filtering in the the texture.

I don't know whether there is an option in the tilemap editor to automatically create these matching edge padding for you (I'm not really familar with the tilemap editor etc), it is widely used for uv mapping and usually called `dilate` (I use it in my lightmapping module). If not it could be added as a godot proposal to autogenerate this padding.

**Comment by qdwang** [comment]
Turning off the `filter` can solve the problem, but it will cause artifacts when moving the content. 
Looks like I can create two different atlas for different use.
1. textures with filter on, and won't be used in tileset.
2. textures with filter off, and shouldn't be moving in canvas.
