### ISSUE TITLE
[4.0] Tabbing through editor inspector properties (and inspector in general) is broken

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#41691]
Bad title, I know, but hear me out... I don't know how else to describe it:

**Godot version:**
4.0 d70a17d5d37fd0

**OS/device including version:**
WIN 10

**Issue description:**
Here you can see me press 5-tab-5-tab-5-tab-5-etc continuously. 
1. My focus does not change to the next control
2. Somehow the result ends up in another editor property too??

![tabbing_broken](https://user-images.githubusercontent.com/41730826/91914001-6c3ae680-ecfa-11ea-9004-381269b24a28.gif)

However, sometimes the behaviour is completely different, here, it actually focuses the second property but stops there.
![broken_2](https://user-images.githubusercontent.com/41730826/91914179-ce93e700-ecfa-11ea-8868-0aad48432ff1.gif)

Now, if I do the tabbing slower, it kind of works, but none of the changes are _actually made_ to the editor properties until I press enter twice. Also, this is super inconsistent. Sometimes I get this behaviour, but most of the time it is what I showed in the first gif.
![broken_3](https://user-images.githubusercontent.com/41730826/91914385-43ffb780-ecfb-11ea-892e-72b6fc254c74.gif)

Finally, here I press "1" _once_, tab (once or multiple times, doesn't matter), and then press enter. Yet somehow the value goes to the first and third editor?
![broken_5](https://user-images.githubusercontent.com/41730826/91914442-6bef1b00-ecfb-11ea-9e72-87ea6432ab02.gif)

**Comment by EricEzaM** [comment]
Also, in this case I noticed that I dont even need to tab for the value duplication case. I press 1, then enter, and value is in both places.

![broken_6](https://user-images.githubusercontent.com/41730826/91914602-c9836780-ecfb-11ea-9ca0-ba83e0ea4e58.gif)

**Comment by Hassan-A** [comment]
@EricEzaM I don't think that last issue is a duplication issue. I believe the Right Anchor is changing because it cant be less than Left Anchor.

**Comment by EricEzaM** [comment]
@Hassan-A why is that the behaviour? For example, Full Rect preset uses anchors of [0 0 1 1]. Why can't I set that myself in the editor? Seems weird.
