### ISSUE TITLE
Javascript build: Cannot initialize return object of type 'Rasterizer *'

### ISSUE THREAD

**Issue by dzil123** [godotengine/godot#41695]
Error message:
```
In file included from platform/javascript/display_server_javascript.cpp:33:
./drivers/dummy/rasterizer_dummy.h:992:10: error: cannot initialize return object of type 'Rasterizer *' with an rvalue of type 'RasterizerDummy *'
                return memnew(RasterizerDummy);
                       ^~~~~~~~~~~~~~~~~~~~~~~
```

**Godot version:** 4.0 dev d70a17d5d37fd09b43882e7972f2ed93eb56b897

**OS/device including version:** Arch Linux x86_64
package versions:
> alsa-lib 1.2.3.2-1
> emscripten 2.0.1-1
> gcc 10.2.0-1
> glu 9.0.1-2
> libglvnd 1.3.2-1
> libxcursor 1.2.0-2
> libxi 1.7.10-3
> libxinerama 1.1.4-3
> libxrandr 1.5.2-3
> mesa 20.1.6-1
> nodejs 14.9.0-1
> pkgconf 1.7.3-1
> pulseaudio 13.0-3
> python 3.8.5-1
> scons 3.1.2-2
> yasm 1.3.0-4

**Enviroment**:
    Contents of ~/.emscripten:
```python
NODE_JS = "node"
EMSCRIPTEN_ROOT = "/usr/lib/emscripten"
```
No custom.py

**Issue description:**
I am trying to compile a HTML5 export template, but the build fails.
**Full build output:** https://gist.github.com/dzil123/8e27f3472b9ec9b204475076a43dc205

I have followed the documentation to set up my build enviroment:
- https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html
- https://docs.godotengine.org/en/latest/development/compiling/compiling_for_web.html

**Steps to reproduce:**
```
scons platform=javascript tools=no target=release
```

**Comment by clayjohn** [comment]
The web backend hasn't been added to the Rasterizer yet. It is still a few months away from being added. :( But be patient and we will have something for you. :)

**Comment by dzil123** [comment]
Oh, I was not aware. Is there a tracking issue for this?

**Comment by clayjohn** [comment]
I don't think so, I couldn't find one by searching.
