### ISSUE TITLE
[crash] __dynamic_cast() segfault - signal related? 

### ISSUE THREAD

**Issue by bertiebaggio** [godotengine/godot#417]
**Preamble**: I am not 100% certain what triggered this crash, although it seemed to happen after changing a Timer scene. However the crash still occurs even after not starting the Timer (and decoupling the timeout signal).

Perhaps the rather sizable set of stack frames implies I've been careless with my node heirarchy or callback referencing somewhere?

     
    Program received signal SIGSEGV, Segmentation fault.
    0xb78b4540 in __dynamic_cast () from /usr/lib/i386-linux-gnu/libstdc++.so.6
     
    (gdb) backtrace
     
    #0  0xb78b4540 in __dynamic_cast () from /usr/lib/i386-linux-gnu/libstdc++.so.6
    #1  0x0805d309 in Object::cast_to<Node> (this=0x9dc8c60) at core/object.h:476
    #2  0x08b65644 in Variant::operator Node* (this=0xbfffc2c4) at core/variant.cpp:1437
    #3  0x082c2b05 in VariantCaster<Node*>::cast (p_variant=...) at core/method_bind.h:61
    #4  0x082c236d in MethodBind1<Node*>::call (this=0x994eaf0, p_object=0x9ddf890, p_args=0xbfffc418, p_arg_count=1, r_error=...)
        at core/method_bind.inc:609
    #5  0x08b33ab0 in Object::call (this=0x9ddf890, p_method=..., p_args=0xbfffc418, p_argcount=1, r_error=...) at core/object.cpp:890
    #6  0x08b9e9d1 in Variant::call (this=0xbfffc4e4, p_method=..., p_args=0xbfffc418, p_argcount=1, r_error=...) at core/variant_call.cpp:857
    #7  0x080b3ee0 in GDFunction::call (this=0x9c5a04c, p_instance=0x9ddf2b0, p_args=0x0, p_argcount=0, r_err=...)
        at modules/gdscript/gd_script.cpp:631
    #8  0x080bb6b7 in GDInstance::_ml_call_reversed (this=0x9ddf2b0, sptr=0x9c40340, p_method=..., p_args=0x0, p_argcount=0)
        at modules/gdscript/gd_script.cpp:1978
    #9  0x080bb721 in GDInstance::call_multilevel_reversed (this=0x9ddf2b0, p_method=..., p_args=0x0, p_argcount=0)
        at modules/gdscript/gd_script.cpp:1986
    #10 0x085d0136 in Node::_notification (this=0x9ddf890, p_notification=13) at scene/main/node.cpp:106
    #12 0x080a961c in CanvasItem::_notificationv (this=0x9ddf890, p_notification=13, p_reversed=false) at ./scene/2d/canvas_item.h:44
    #13 0x0875eadc in Node2D::_notificationv (this=0x9ddf890, p_notification=13, p_reversed=false) at ./scene/2d/node_2d.h:36
    #14 0x08799bd0 in CollisionObject2D::_notificationv (this=0x9ddf890, p_notification=13, p_reversed=false) at scene/2d/collision_object_2d.h:37
    #15 0x087c97c2 in PhysicsBody2D::_notificationv (this=0x9ddf890, p_notification=13, p_reversed=false) at scene/2d/physics_body_2d.h:39
    #16 0x087caa58 in KinematicBody2D::_notificationv (this=0x9ddf890, p_notification=13, p_reversed=false) at scene/2d/physics_body_2d.h:235
    #17 0x08b33bdf in Object::notification (this=0x9ddf890, p_notification=13, p_reversed=false) at core/object.cpp:902
    #18 0x085d042d in Node::_propagate_ready (this=0x9ddf890) at scene/main/node.cpp:149
    #19 0x085d6249 in Node::_set_scene (this=0x9ddf890, p_scene=0x9b4fad0) at scene/main/node.cpp:1622
    #20 0x085d2434 in Node::_add_child_nocheck (this=0x9c9e5d0, p_child=0x9ddf890, p_name=...) at scene/main/node.cpp:635
    #21 0x085d274c in Node::add_child (this=0x9c9e5d0, p_child=0x9ddf890) at scene/main/node.cpp:662
    #22 0x082c2383 in MethodBind1<Node*>::call (this=0x994eaf0, p_object=0x9c9e5d0, p_args=0xbfffcf9c, p_arg_count=1, r_error=...)
        at core/method_bind.inc:609
    #23 0x08b33ab0 in Object::call (this=0x9c9e5d0, p_method=..., p_args=0xbfffcf9c, p_argcount=1, r_error=...) at core/object.cpp:890
    #24 0x08b9e9d1 in Variant::call (this=0xbfffcf4c, p_method=..., p_args=0xbfffcf9c, p_argcount=1, r_error=...) at core/variant_call.cpp:857
    #25 0x080b3ee0 in GDFunction::call (this=0x9c749bc, p_instance=0x9dc8ac0, p_args=0xbfffd778, p_argcount=1, r_err=...)
        at modules/gdscript/gd_script.cpp:631
    #26 0x080bb546 in GDInstance::call (this=0x9dc8ac0, p_method=..., p_args=0xbfffd778, p_argcount=1, r_error=...)
        at modules/gdscript/gd_script.cpp:1945
    #27 0x08b339b1 in Object::call (this=0x9dc8910, p_method=..., p_args=0xbfffd778, p_argcount=1, r_error=...) at core/object.cpp:869
    #28 0x08b9e9d1 in Variant::call (this=0xbfffd728, p_method=..., p_args=0xbfffd778, p_argcount=1, r_error=...) at core/variant_call.cpp:857
    #29 0x080b3ee0 in GDFunction::call (this=0x9c9a89c, p_instance=0x9dc8730, p_args=0xbfffdebc, p_argcount=1, r_err=...)
        at modules/gdscript/gd_script.cpp:631
    #30 0x080bb546 in GDInstance::call (this=0x9dc8730, p_method=..., p_args=0xbfffdebc, p_argcount=1, r_error=...)
        at modules/gdscript/gd_script.cpp:1945
    #31 0x08b339b1 in Object::call (this=0x9dc82b0, p_method=..., p_args=0xbfffdebc, p_argcount=1, r_error=...) at core/object.cpp:869
    #32 0x08b9e9d1 in Variant::call (this=0xbfffdf84, p_method=..., p_args=0xbfffdebc, p_argcount=1, r_error=...) at core/variant_call.cpp:857
    #33 0x080b3ee0 in GDFunction::call (this=0x9c99cdc, p_instance=0x9dc8730, p_args=0xbfffe5d4, p_argcount=1, r_err=...)
        at modules/gdscript/gd_script.cpp:631
    #34 0x080bb546 in GDInstance::call (this=0x9dc8730, p_method=..., p_args=0xbfffe5d4, p_argcount=1, r_error=...)
        at modules/gdscript/gd_script.cpp:1945
    #35 0x08b339b1 in Object::call (this=0x9dc82b0, p_method=..., p_args=0xbfffe5d4, p_argcount=1, r_error=...) at core/object.cpp:869
    #36 0x08b9e9d1 in Variant::call (this=0x9dc765c, p_method=..., p_args=0xbfffe5d4, p_argcount=1, r_error=...) at core/variant_call.cpp:857
    #37 0x080b3ee0 in GDFunction::call (this=0x9c564ec, p_instance=0x9dc7460, p_args=0xbfffeca4, p_argcount=0, r_err=...)
        at modules/gdscript/gd_script.cpp:631
    #38 0x080bb546 in GDInstance::call (this=0x9dc7460, p_method=..., p_args=0xbfffeca4, p_argcount=0, r_error=...)
        at modules/gdscript/gd_script.cpp:1945
    #39 0x08b339b1 in Object::call (this=0x9dc7180, p_method=..., p_args=0xbfffeca4, p_argcount=0, r_error=...) at core/object.cpp:869
    #40 0x08b3369d in Object::call (this=0x9dc7180, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:766
    #41 0x08b34aad in Object::emit_signal (this=0x9dc7a80, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
        at core/object.cpp:1142
    #42 0x085e569c in Timer::_notification (this=0x9dc7a80, p_what=17) at scene/main/timer.cpp:52
    #43 0x085e6983 in Timer::_notificationv (this=0x9dc7a80, p_notification=17, p_reversed=false) at scene/main/timer.h:36
    #44 0x08b33bdf in Object::notification (this=0x9dc7a80, p_notification=17, p_reversed=false) at core/object.cpp:902
    #45 0x085e9680 in SceneMainLoop::_notify_group_pause (this=0x9b4fad0, p_group=..., p_notification=17) at scene/main/scene_main_loop.cpp:706
    #46 0x085e8d0c in SceneMainLoop::idle (this=0x9b4fad0, p_time=0.0226579998) at scene/main/scene_main_loop.cpp:512
    #47 0x0805bc46 in Main::iteration () at main/main.cpp:1295
    #48 0x08051f77 in OS_X11::run (this=0xbffff180) at platform/x11/os_x11.cpp:1277
    #49 0x0804df2b in main (argc=3, argv=0xbffff4e4) at platform/x11/godot_x11.cpp:41

**Comment by akien-mga** [comment]
@reduz Did you finally add those checks as you mentioned?

**Comment by akien-mga** [comment]
Assuming this has been fixed since then.
