### ISSUE TITLE
GitHub login to Q&A site is broken when using www. subdomain

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#4170]
**Issue description** (what happened, and what was expected):
Can't login to http://godotengine.org/qa/ with GitHub - it shows a bland page with `You cannot access this page directly.` message.

The solution described here - http://www.question2answer.org/qa/49972/error-using-login-getting-error-cannot-access-directly-solve?show=49972#q49972 is just to reinstall open login module.

**Steps to reproduce:**
Open http://godotengine.org/qa/
Click button in top right corner
Choose GitHub

**Comment by Ace-Dragon** [comment]
https://github.com/godotengine/godot/issues/3888

I once had the same problem, see if this helps you as well.

**Comment by freemanfromgodotengine** [comment]
Can't confirm today - it works for me right now, but when the new site was published I had the issue once, then it was repaired and gone. Never had the problem again since than.

**Comment by techtonik** [comment]
Just tried and got logged in too. It seems to work with http://godotengine.org/qa/, but still fails for http://www.godotengine.org/qa/

**Comment by freemanfromgodotengine** [comment]
I can confirm that  www.godotengine.org/qa still has this problem.

**Comment by techtonik** [comment]
The solution is to strip `www.` or redirecting to `www.`. Stripping `www.` means that godotengine.org cookie will be shared between main site and qa site, which usually thought of as a weak security (prooflink needed).

**Comment by akien-mga** [comment]
@alketii @punto- It would be great to solve these ``www.godotengine.org`` vs ``godotengine.org`` issues once and for all, we also had similar problems on the previous OP website (if you were logged in on ``www.``, you were not logged in on the non-``www.``).

I guess there's something that we're doing wrong in our redirection :)

**Comment by eska014** [comment]
Maybe related to the @godotengine OAuth application (callback/homepage URL)?

**Comment by bojidar-bg** [comment]
Is this still valid actually?

**Comment by vnen** [comment]
The `www` subdomain is now redirected, so this doesn't happen anymore.
