### ISSUE TITLE
GDScript parse error on Dictionary indexing with member syntax

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#41707]
**Godot version:**
358e209fa049887fd4212c52c9faba0ca9d6e111

**OS/device including version:**
Linux, but should affect any OS.

**Issue description:**
Given this script:
```gdscript
func _ready():
        var a = {
                test: "Hello"
        }
        a.test += " World"
```
The new GDScript in the `master` branch would throw an error:
```
SCRIPT ERROR: Parse Error: Identifier "test" not declared in the current scope.
          at: GDScript::reload (res://Node2D.gd:6)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:633)
```

**Steps to reproduce:**
- Use `my_dict.my_var` syntax to index a Dictionary.

**Minimal reproduction project:**
Not necessary.

**Comment by NonADev** [comment]
Try this:
```py
func _ready():
	var a = {
			"test": "Hello"
	}
	a.test += " World"
	print(a.test)
```
The test have to be in quotation marks.

**Comment by ThakeeNathees** [comment]
@NonADev it's a missing quotations is a typo, and it still a bug
