### ISSUE TITLE
C# error on empty project: load: Parameter "assembly" is null.  

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#41712]
**Godot version:**
3.2.3.rc5.mono

**OS/device including version:**

macOS Catalina 10.15.6 / MacBookPro11,1 / Intel Iris 5100 /GLES2

**Issue description:**
I created a new empty project, ran it and got this error:
E 0:00:00.482   load: Parameter "assembly" is null.
  <C++ Source>  modules/mono/mono_gd/gd_mono_assembly.cpp:461 @ load()

![Screenshot 2020-09-02 at 20 04 24](https://user-images.githubusercontent.com/13488692/92014840-8d322480-ed58-11ea-868c-63085e28b868.png)

 
**Steps to reproduce:**
Create empty project. Run it.

**Minimal reproduction project:**
Not necessary.

**Comment by akien-mga** [comment]
Did you Build the project? (button in top right corner)

This error sounds like a project which has never been compiled, so indeed there's no assembly to load nor run.

**Comment by akien-mga** [comment]
I can reproduce the issue on Windows 10 when creating a new project and load it the first time. It indeed happens because there's no assembly to load yet, so it's not a bad error per se, it's just confusing UX wise.
