### ISSUE TITLE
Tilemap tiles don't rotate on feedback with horizontal and vertical flips

### ISSUE THREAD

**Issue by ObaniGemini** [godotengine/godot#41716]
**Godot version:** 3.3rc4, rc5

**OS/device including version:** GNU/Linux, latest Arch Linux

**Issue description:** When flipping tiles on TileMap, the tile doesn't rotate in its feedback on the scene

**Steps to reproduce:** Open a tileset with the tilemap and invert X or Y, check if the tile hovering the scene is rotated

**Minimal reproduction project:**
![2020-09-02_20:11:08](https://user-images.githubusercontent.com/11649956/92023226-c4a2d000-ed5c-11ea-9d88-4bd0b4da832a.png)

**Comment by akien-mga** [comment]
Possibly related to #41032, CC @mrushyendra (assuming it to be a regression though I haven't tested 3.2.2 or earlier to confirm).

**Comment by mrushyendra** [comment]
Can confirm, preview is flipped correctly on 3.2.2
