### ISSUE TITLE
CollisionShape.set_shape accepts pretty much any type, should only accept Shape

### ISSUE THREAD

**Issue by phryk** [godotengine/godot#41722]
**Godot version:**
3.2.1

**OS/device including version:**
Any. But tested on FreeBSD-12.1-RELEASE

**Issue description:**
CollisionShape.set_shape accepts *any* object, but should only accept Shape.
Currently it just fails silently (without any error or warning) if you pass in a non-shape object.
This *should* fail explicitly.

**Steps to reproduce:**
In GDScript:
```
var foo = CollisionShape.new()
foo.set_shape(Object())
```

**Comment by Zylann** [comment]
The same happens with other properties such as `MeshInstance.mesh`:
```gdscript
	var mi = MeshInstance.new()
	mi.mesh = mi
```
No errors printed in game.

I think there was an issue mentionning that but can't find it.
