### ISSUE TITLE
Mouse cursor set with Input.set_custom_mouse_cursor doesn't resize

### ISSUE THREAD

**Issue by macramole** [godotengine/godot#4173]
stretch_mode is set to viewport, all sprites get smaller on window resize but the cursor stays the same causing a humongous cursor in my game

**Comment by bojidar-bg** [comment]
Does this happen with `stretch_mode = 2d` too?

**Comment by macramole** [comment]
yep, same thing

**Comment by kubecz3k** [comment]
Not sure if this is bug, set_custom_cursor is probably using hardware cursor which is managed by operating system... I think if you want to stretch it, you should do this via code just before setting it.

**Comment by guilhermefelipecgs** [comment]
@akien-mga now that we have hardware cursor, this issue doesn't make sense, strech mode can't affect system's cursor.

**Comment by akien-mga** [comment]
Thanks, marking as fixed in 3.0 then.
