### ISSUE TITLE
RC5 requires all filenames be unique in project or it grabs first one it finds

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#41745]
**Godot version:**
3.2.3.rc5.mono

**OS/device including version:**
Windows 10

**Issue description:**
If a filename is not unique for the entire project, Godot will ignore the path and namespace and access the first one in the project it finds, (or caches the last one it found?)
This is not a problem in RC3 and works as expected.
Example:
If you have files `Menus/Pause/MainOptions.cs` and `Menus/Title/MainOptions.cs`, and try to access the Title file, Godot will access the Pause file.

**Steps to reproduce:**
1. Create a C# project with two trees of nodes, 2+ levels deep. 
2. Attach scripts to all files, and make folder structure mimic the hierarchy. 
3. Name the nested files the same, but keep them in separate folders with separate namespaces.
4. Run project, and view that it will only access one of the nested scripts.

**Minimal reproduction project:**
Included is a project working as expected made with RC3, and one working incorrectly made with RC5.
[ReferenceTestRC3.zip](https://github.com/godotengine/godot/files/5170454/ReferenceTestRC3.zip)
[ReferenceTestRC5.zip](https://github.com/godotengine/godot/files/5170455/ReferenceTestRC5.zip)

**Comment by Calinou** [comment]
cc @neikeq

**Comment by Zireael07** [comment]
Does that affect only Mono or GDScript too?

**Comment by markdibarry** [comment]
Just mono, I'd assume.
As pointed out by someone on the discord, [here's the offender.](https://github.com/godotengine/godot/pull/41408/commits/c3954441f360b46546e8a8deacfc42460e93987d#diff-7c0e8d64438b87f8ba8badfe02562938L57)

**Comment by Spartan322** [comment]
It seems the problem comes as a result of 
https://github.com/godotengine/godot/blob/3.2/modules/mono/editor/GodotTools/GodotTools/CsProjOperations.cs#L39-L47
and
https://github.com/godotengine/godot/blob/3.2/modules/mono/editor/GodotTools/GodotTools/Internals/ScriptClassParser.cs#L18-L20
