### ISSUE TITLE
when i changing the animation to animation (by code) it doesn't work

### ISSUE THREAD

**Issue by sihela** [godotengine/godot#41741]
**Godot version:**
 Godot_v3.2.1-stable_win64

**OS/device including version:**
Windows 10

**Issue description:**
i think this is bug if not i am sorry so i have two animationPlayer in one scene but i cannot change animation to another animation
i mean i want when a texture button (screen) pressed the want to be changed to another animation

here is my code,

`extends TextureButton 
onready var anim = get_node("AnimationPlayer")

##i connected to button node (presssed)##
func _on_TextureButton_pressed():
   anim.play("starting")`

If you don't understand sorry i am very poor at explanation.if you have a question tell me

**Steps to reproduce:**
1. Unpack the archive
2. Open the project.
**Minimal reproduction project:**
[The bob.zip](https://github.com/godotengine/godot/files/5170091/The.bob.zip)

**Comment by splite** [comment]
Cant run your project, but at first glance, you 'get_node("AnimationPlayer")' but you want `get_node("../AnimationPlayer")` (AnimationPlayer is sibling to your node with attached script, not his child) 

Please, next time, try [godotengine questions and answers](https://godotengine.org/qa/) first.
