### ISSUE TITLE
Default values given in GDScript function declarations overriding anything else.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#41766]
**Godot version:** Godot Engine v4.0.dev.custom_build. 5c4dffe7c

**Issue description:** I have a function `add_sound_to_library` in `sound_player` with two arguments, `sound_file` and `sound_name`. By default, `sound_name` reverts to `""` if nothing is supplied for it. `func add_sound_to_library (sound_file, sound_name = "") -> void`

However: `sound_player.add_sound_to_library ("res://Assets/Audio/Sound/ring_get.ogg", "ring_get")` does not work as expected. The name given here is ignored, and instead the function uses the default given. This can also be seen in the `play_sound` function.

**Minimal reproduction project:**

[41766_Demonstrator.zip](https://github.com/godotengine/godot/files/5175071/41766_Demonstrator.zip)

**Comment by akien-mga** [comment]
Please try to attach an actually **minimal** reproduction project. A full game is not that, and it takes a while to read the code, understand what it's supposed to do and then what it doesn't do right.

While a properly minimal reproduction project for the symptom is fairly short:
```gdscript
extends Node

func some_func(a = "test"):
	print(a)

func _ready():
	some_func("hello world")  # prints "test"
```
