### ISSUE TITLE
X11: Can't add effects to Audio Bus, selection impossible in popup

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#41762]
**Godot version:**
44e89cb88f7e982d7298e640f0828608bd3c5784

**OS/device including version:**
Mageia 8 x64, Plasma 5 on X11 with KWin

**Issue description:**
In the current `master` branch, I can't select audio effects to add to an audio bus in the popup menu with the mouse:
![Screenshot_20200904_133609](https://user-images.githubusercontent.com/4701338/92235209-9aaff180-eeb3-11ea-82ca-92216fd3cef5.png)
I can however select items with the arrow keys and <kbd>Return</kbd>.

Possibly a regression from #41640 (CC @EricEzaM), otherwise might be a general X11 window issue (CC @pouleyKetchoupp).

**Steps to reproduce:**
- Open project on X11
- Select Audio bottom panel
- Click "Add Effect"
- Try to select an effect

**Minimal reproduction project:**
n/a

**Comment by akien-mga** [comment]
This is fixed by #41689, so indeed a regression from #41640.

**Comment by EricEzaM** [comment]
Awesome, already solved before I get to look at the ticket :P
