### ISSUE TITLE
Can't turn off both Fill and Expand flags of Control node

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4176]
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
Can't turn off both ``Fill`` and ``Expand`` flags of Control node.
I can turn off both flags while editing and I got expected result.
But when running game, or close and reopen scene,
Size flag is reset to ``Fill``.
And I can get expected result while running with ``set_h_size_flags(0)`` script.

**Steps to reproduce:**
1. make a new Scene
2. add ``Control`` node
3. uncheck ``Fill`` size flag of Horizontal (and/or Vertical)
4. close scene
5. reopen scene
6. see the size flags is set to ``Fill`` again

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Are you using `.tscn`

**Comment by volzhs** [comment]
I'm using `.scn`

**Comment by volzhs** [comment]
I looked some codes,
I think that the flag of size doesn't have an option for *none*.
But it's really useful for some case.

![image](https://cloud.githubusercontent.com/assets/8281454/14142413/8518d5ca-f6c0-11e5-8d2a-50c12191dbda.png)

I can create vertical list with horizontal list aligned center.
But I can't not get this layout without **none** option.
This seems unsupported offically, but works fine if I did it on editor and use ``set_h_size_flags(0)`` on runtime.

**Comment by volzhs** [comment]
I tested and found with ``.tscn`` format.
Horizontal size flag is not saved when it has ``0`` (none).
So, I manually added ``size_flags/horizontal = 0`` in ``.tscn`` and opened it.
then, it looks fine.

**Comment by volzhs** [comment]
The default values of size flags are ``SIZE_FILL``.
But, default vertical size flag of ``Label`` is ``0``.
So, vertical size flag of ``Label`` is empty by default.
I think, it would be good if both size flags are saved with its value.

**Comment by volzhs** [comment]
I think this line cause problem.

https://github.com/godotengine/godot/blob/e46e43d2aaa6339a1675eb989f41885e745bf5c3/scene/resources/packed_scene.cpp#L495

Default value of size flag is actually 2(SIZE_FILL).
But, it's skipped by ``(E->get().usage & PROPERTY_USAGE_STORE_IF_NONZERO) && value.is_zero()``, I guess.
