### ISSUE TITLE
Drag & drop CS files not works to add files to the project

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#41768]
**Godot version:**

3.2.3 RC5 Mono

**OS/device including version:**

win10 64 home
nvidia GT440

**Issue description:**

Cannot add files CS (C#) to project using drag and drop method

![test gif gif gif](https://user-images.githubusercontent.com/19652075/92263464-f5117800-eedc-11ea-8f5d-b72e01f6e44d.gif)

The files should be added to the project.

**Steps to reproduce:**
In any project, try dragging and dropping a CS file to add it to your project in Godot.

**Minimal reproduction project:**

Any project, even empty

**Comment by neikeq** [comment]
Does this work with GDScript files?

**Comment by Flavelius** [comment]
dragging in .material(s) also doesn't work (nothing happens like in the entry post's video)

**Comment by Calinou** [comment]
@Flavelius Dragging arbitrary files to the FileSystem dock isn't allowed by Godot yet.

**Comment by KoBeWi** [comment]
Seems fixed in 3.2.4 rc2
![xvnGsHiSWo](https://user-images.githubusercontent.com/2223172/107891376-8ec66200-6f1e-11eb-9f1b-4cd354674344.gif)

**Comment by Torguen** [comment]
Why is this problem (which in my opinion is not very important either) is added to milestone and this problem (which I think is more important) not?
[(https://github.com/godotengine/godot/issues/45108)]

**Comment by akien-mga** [comment]
It was added to the milestone because it's fixed in that milestone (closed). Before that, it was not on the milestone because it was indeed not very important.
