### ISSUE TITLE
OS clipboard func return null/no result in android os

### ISSUE THREAD

**Issue by rixck** [godotengine/godot#4177]

**Comment by bojidar-bg** [comment]
Please, provide more information, like android version, godot version, etc.

**Comment by rixck** [comment]
Ops sorry :)

1. Godot 2.0 stable
2. Android 4.4.2
3. Device LG-D325

set/get clipboard seems no response/nothing

**Comment by reduz** [comment]
this is unimplemented on android, if anyone wants to do it feel free to do it

**Comment by Hinsbart** [comment]
I tried to implement this a few months ago but stopped halfway through as it was a lot more work than I initially expected :p 
I can try to dig out that code for anyone interested in implementing this.

**Comment by akien-mga** [comment]
Fixed by #17950 in the 2.1 branch, but that code has not been added to the master branch yet.

**Comment by reduz** [comment]
@akien-mga , @xsellier: What is the status of this?

**Comment by xsellier** [comment]
@reduz it has been fixed by the merge request.

**Comment by akien-mga** [comment]
It's not fixed in the master branch.

**Comment by reduz** [comment]
If someone wants to copy this code from the 2.1 branch to 3.1, help would be appreciated!

**Comment by akien-mga** [comment]
Fixed by #21783.
