### ISSUE TITLE
Errors in get_usable_parent_rect on editor startup

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#41779]
**Godot version:**
Master 28100d554ce9047c6c267115ae4aca0e0970fe42

**OS/device including version:**
Linux (Ubuntu 20.04.1)

**Issue description:**
A series of errors show up on editor startup.

They seem related to #41640 (calling `get_usable_parent_rect` in `_get_contents_minimum_size`).
CC @EricEzaM 

Error:
```
ERROR: Condition "!is_inside_tree()" is true. Returning: Rect2()
   at: get_usable_parent_rect (scene/main/window.cpp:1085)
```

Callstack:
```
_err_print_error(const char * p_function, const char * p_file, int p_line, const char * p_error, const char * p_message, ErrorHandlerType p_type) (/home/pouleyketchoupp/sources/godot/core/error_macros.cpp:77)
_err_print_error(const char * p_function, const char * p_file, int p_line, const char * p_error, ErrorHandlerType p_type) (/home/pouleyketchoupp/sources/godot/core/error_macros.cpp:69)
Window::get_usable_parent_rect(const Window * const this) (/home/pouleyketchoupp/sources/godot/scene/main/window.cpp:1085)
PopupMenu::_get_contents_minimum_size(const PopupMenu * const this) (/home/pouleyketchoupp/sources/godot/scene/gui/popup_menu.cpp:104)
Window::get_contents_minimum_size(const Window * const this) (/home/pouleyketchoupp/sources/godot/scene/main/window.cpp:1069)
Window::_update_window_size(Window * const this) (/home/pouleyketchoupp/sources/godot/scene/main/window.cpp:522)
Window::set_size(Window * const this, const Size2i & p_size) (/home/pouleyketchoupp/sources/godot/scene/main/window.cpp:86)
EditorNode::_update_layouts_menu(EditorNode * const this) (/home/pouleyketchoupp/sources/godot/editor/editor_node.cpp:4572)
EditorNode::EditorNode(EditorNode * const this) (/home/pouleyketchoupp/sources/godot/editor/editor_node.cpp:6436)
Main::start() (/home/pouleyketchoupp/sources/godot/main/main.cpp:2057)
main(int argc, char ** argv) (/home/pouleyketchoupp/sources/godot/platform/linuxbsd/godot_linuxbsd.cpp:57)
```

The other errors are similar ones in `CanvasItemEditor`, `Node3DEditorViewport`, `ScriptEditor`, `ScriptTextEditor`.

**Steps to reproduce:**
Launch the editor.

**Minimal reproduction project:**
n/a

**Comment by EricEzaM** [comment]
Is it a crash or just errors in the output log?

**Comment by pouleyKetchoupp** [comment]
Just errors.

**Comment by EricEzaM** [comment]
So the issue seems to be in `main.cpp`... the editor is initialised in Main::start(), but tree entry only happens on the first run of `os.run()`. So, in the constructor of `EditorNode`, the tree doesn't exist yet so calls to those methods return the error.

I think the solution to this will be putting the methods which cause these errors into `EditorNode::notification` on `NOTIFICATION_ENTER_TREE`, or `NOTIFICATION_READY`.
