### ISSUE TITLE
Mono: Godot does not generate Generated directory

### ISSUE THREAD

**Issue by TheKetrab** [godotengine/godot#41783]
While glue generating, Godot does not generate Generated directory, but generates mono_glue.gen.cpp

I am using Windows 10, 
Mono version: Mono JIT compiler version 6.10.0 (Visual Studio built mono),
Visual Studio 2019 Developer Command Prompt v16.7.0

---
I am typing the following commands:

scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
--> bin/godot.windows.tools.64.mono.exe is created

bin/godot.windows.tools.64.mono.exe is created --generate-mono-glue modules/mono/glue
--> process exits without any problems

scons p=windows tools=yes module_mono_enabled=yes mono_glue=yes
--> fails because no 'Generated' directory found

```
MSBuild path: C:\Program Files\dotnet\dotnet.exe
Microsoft (R) Build Engine 16.7.0-preview-20360-03+188921e2f dla platformy .NET
Copyright (C) Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\ketra\Downloads\godot-master\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj(70,3): error MSB4019: Not found project: "C:\Users\ketra\Downloads\godot-master\modules\mono\glue\GodotSharp\GodotSharp\Generated\GeneratedIncludes.props".
...
scons: *** [bin\GodotSharp\Api\Debug\GodotSharp.dll] RuntimeError : 'msbuild' exited with error code: 1
```

File modules/mono/glue/mono_glue.gen.cpp IS GENERATED, but rest of api (modules/mono/glue/Managed/Generated) is not.
I spent many hours trying to rebuild Godot with Mono on many different ways, but still --generate-mono-glue option doesn't produce Generated directory. I even tried to enforce define:
```
#define DEBUG_METHODS_ENABLED
#define TOOLS_ENABLED
#define MONO_GLUE_ENABLED
```
but result was the same: mono_glue.gen.cpp is generated, but rest of api is not.

---
Does anybody know what am I doing wrong?
Can anybody send me a zip with 'Generated' directory?

**Comment by Calinou** [comment]
@TheKetrab Which Godot version are you compiling? Please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it when creating issues.

**Comment by akien-mga** [comment]
> bin/godot.windows.tools.64.mono.exe is created --generate-mono-glue modules/mono/glue

If that's what you typed, the "is created" part is wrong and this would likely fail.
