### ISSUE TITLE
Unable to export only .pck from command line

### ISSUE THREAD

**Issue by slasktotten** [godotengine/godot#41786]
Godot version:
3.2.2 stable 

OS/device including version:
mac os catalina 10.15.6

Issue description:
When attempting to export only a .pck file via cmd line godot also tries to export an executable binary.
If I have an export profile named "android" `godot --export android builds/assets.pck `tries to also export a .apk
With an ios profile it also tried to export a .ipa

Everything works fine if I try to do it manually via the editor.

Steps to reproduce:
Try to export only .pck via command line.

**Comment by Calinou** [comment]
Use the `--export-pack` command-line option (added in 3.2.2) for this.
