### ISSUE TITLE
Seamless OpenSimplex noise has less contrast than non-seamless noise

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot#41787]
**Godot version:**
3.2.2-stable, Windows & Linux

**OS/device including version:**
Windows 10, Ubuntu 20.04.1 LTS

**Issue description:**
When switching between seamless and non-seamless versions of OpenSimplex noise, the contrast changes. Specifically, seamless noise never has a value of 0 or 1. I'm using the values in a shader to look up values in a gradient texture and never get the colours in the extremes to show when using a seamless noise texture.

**Steps to reproduce:**
1. Create a Sprite
2. Under Texture, add a New NoiseTexture
3. Set the Noise to New OpenSimplexNoise
4. On the Texture, turn the "seamless" checkbox on and off to see the difference. It's most apparent in the darkest colours of the texture; the seamless version just looks more washed out.

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
cc @JFonS

**Comment by Zylann** [comment]
> seamless noise never has a value of 0 or 1

That's actually extremely rare with noise, or normalized random floats in general.
In the case of OpenSimplex, the base algorithm actually happens to never go beyond `0.87` (computed this empirically with a large for loop).

However, in the case of seamless noise, loss of contrast can happen if it is implemented by mixing several layers together and averaging them, because the probability of all layers tending to the same extreme gets less likely.

**Comment by robbertzzz** [comment]
@Zylann Adding a multiplier is what I'm resorting to now, it does help make things look better. It's pretty interesting that technically the extremes should still exist, I haven't come across anything that looked like it and am using a LOT of different seeds in my current project.

A possible "solution" could be to add a flag for improving contrast, I can imagine that sometimes users wouldn't want that to happen as the maximum possible difference between two adjacent pixels changes by implementing a multiplier curve.

**Comment by Calinou** [comment]
Is this something we should attempt to fix in 4.0, or should we leave it as-is?

> A possible "solution" could be to add a flag for improving contrast

This can be done manually by the user using the Image class (or just taking it into account in their shader).

**Comment by robbertzzz** [comment]
> Is this something we should attempt to fix in 4.0, or should we leave it as-is?

Given that the problem is [broader than just image generation](https://github.com/godotengine/godot/issues/43168) I'd like to see this fixed. I'm also using the noise function in another project than the one that made me open this issue to create smooth noisy animations, not knowing the actual min and max values makes that a lot harder to control.

**Comment by Omicron666** [comment]
currently output is approximatively [-0.8;0.8]
see also reports and links here: https://github.com/godotengine/godot-docs/issues/4078

**Comment by JFonS** [comment]
The proper solution would be to add support for tileable noise directly into the OpenSImplexNoise library, or find another implementation that already supports it. 

The sampling of a 4D sphere to get 2D  tileable noise is a trick and, as @Zylann mentioned,  it results in an image with reduced contrast (I didn't foresee that, my bad). However, it should be possible to generate tileable noise directly from the generator. Here's some literature I found if someone wants to look into doing this: https://www.gamedev.net/blog/33/entry-2138456-seamless-noise/

Another option is to wait for #35144 to be merged. If I understand correctly it provides a quadrant swap and blend approach to tileable noise. I assume the blending will result in less contrast just like the current implementation does, but it would only be on the blended regions and likely less noticeable.

**Comment by Zylann** [comment]
The author of OpenSimplex2 is working on a tileable version too, I think it's probably going to be added to FastNoiseLite.

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/56718 (4.0). In 3.x, this was documented by https://github.com/godotengine/godot/pull/43279.
