### ISSUE TITLE
4.0: textureSize causes scene shader to fail compile.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#41797]
**Godot version:**
v4.0.dev.custom_build.9fc4f1728
(compiled with scons & VC 2017, git repo is clean)

**OS/device including version:**
Microsoft Windows [Version 10.0.18362.1016] Windows 10 Pro, 64-bit.
NVidia GeForce RTX 2080 Ti
Driver version: 445.87 DCH
(Vulkan)

**Issue description:**
I created a shader using `textureSize()` - this shader causes the following errors to be printed out each time it is compiled:
```
 servers\rendering\rasterizer_rd\rasterizer_scene_high_end_rd.cpp:149 - Condition "!scene_singleton->shader.scene_shader.version_is_valid(version)" is true.
 servers\rendering\rasterizer_rd\rasterizer_scene_high_end_rd.cpp:149 - Condition "!scene_singleton->shader.scene_shader.version_is_valid(version)" is true.
```

**Steps to reproduce:**
Open the attached project and open the scene. The cubes should be colored depending on the texture size (e.g. icon.png). Instead they are white and errors are printed to Console.

Here is the simpler of the two shader sources I am using:
```glsl
shader_type spatial;

uniform sampler2D testtex : hint_white;

void fragment() {
	ALBEDO = textureSize(testtex, 0).x > 8 ? vec3(1.0,0.1,0.5) : vec3(0.0,1.0,0.5);
}
```

**Minimal reproduction project:**
[TextureSizeTest.zip](https://github.com/godotengine/godot/files/5178894/TextureSizeTest.zip)

**Comment by Chaosus** [comment]
Similar issue (but for texelFetch) - https://github.com/godotengine/godot/issues/40142 I guess they are related.
