### ISSUE TITLE
Selecting a different GraphNode from code does not send a select or deselect signal

### ISSUE THREAD

**Issue by TomNCatz** [godotengine/godot#41799]
**Godot version:**
godot mono 3.2.3_RC5

**OS/device including version:**
Windows 10

**Issue description:**
Calling GraphEdit.SetSelected( node ) does not send a 'node_unselected' signal or a 'node_selected' signal

Expected behavior :
When a node is already selected and GraphEdit.SetSelected( node ) is used to select a new node, a 'node_unselected' signal should be sent

**Steps to reproduce:**
1 connect a listener to 'node_unselected'
2 Left click on an unselected node.
3 Call GraphEdit.SetSelected( node ) where node is a different node from the one selected

Notes :
This behavior might not be new in 3.2.3, but since that version added 'node_unselected' as a signal it may just now be noticeable.

**Comment by IlTrain** [comment]
Fixed
