### ISSUE TITLE
error getting the modified time of a file while running the editor

### ISSUE THREAD

**Issue by voidplayer** [godotengine/godot#418]
Not critical, but im getting this in the console

ERROR IN: res://assets/bionickid.fnt::0
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/unix/file_access_unix.cpp:233.

The resource is there:
$ stat assets/bionickid.fnt 
  File: ‘assets/bionickid.fnt’
  Size: 21365     	Blocks: 48         IO Block: 4096   regular file
Device: fe03h/65027d	Inode: 35512356    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/voidplayer)   Gid: ( 1000/voidplayer)
Context: unconfined_u:object_r:user_home_t:SystemLow
Access: 2014-05-14 23:41:49.825771331 +0200
Modify: 2014-05-11 18:15:28.028585940 +0200
Change: 2014-05-11 18:15:28.028585940 +0200
 Birth: -

**Comment by akien-mga** [comment]
Can you still reproduce the issue with a recent Godot build?

**Comment by voidplayer** [comment]
im not even sure what this was about. It was so long ago
