### ISSUE TITLE
Text input caret resets to start in some LineEdits and TextEdits

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#41809]
**Godot version:**
4.0 ceed52493696d

**OS/device including version:**
win 10

**Issue description:**
EditorInspector line edit's and text areas reset the caret to the beginning. Note: this does not happen on line edit's and text areas in-game, seems to only be the editor. The behaviour is seen both when typing and clicking in the control area, as seen below.

![textinputbug](https://user-images.githubusercontent.com/41730826/92325355-26c94100-f08d-11ea-8efc-22f2fd32b96b.gif)
![textinputbug2](https://user-images.githubusercontent.com/41730826/92325356-27fa6e00-f08d-11ea-89ef-6db08f27a40b.gif)

**Comment by rodohanna** [comment]
Successfully repro'd while trying to repro https://github.com/godotengine/godot/issues/41962. I'll start checking this out.

**Comment by Paavs-Git** [comment]
This also affects every text editable property in Project Settings and Editor Settings, including 'Application' (Config etc.), 'Layer Names', etc. As a workaround you can write somewhere outside the editor and paste things in.

**Comment by Paulb23** [comment]
This is caused by #41697, as every refresh it's calling `set_text`. Also makes editing arrays etc impossible:
![array_edit_bug](https://user-images.githubusercontent.com/6584330/93239038-24947000-f77a-11ea-805f-ef3b6637218d.gif)

**Comment by EricEzaM** [comment]
Why is `cursor_pos` set to zero on `set_text()`?
