### ISSUE TITLE
Math operation on editor

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4180]
Hi. This is a suggestion to speed up the work flow in Godot. The idea is to have the ability of type math operation on the properties that are shown on the editor, such as Pos, Rot, Scale... e.g. 70+190, 70*(2+24). I know it might sound kind of silly but most of the time with need to set a specific value that is the two time another one or when duplicate a sprite increase the Pos.x by the width or... you got the idea.

Not having to switch to the calculator will be awesome!

**Comment by akien-mga** [comment]
Hi, that's precisely what #3620 would implement when merged :)

**Comment by EdwardAngeles** [comment]
Awesome, looking forward to it!
