### ISSUE TITLE
GDScript: calling a non-static method statically from another non-static method cause a bug

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41811]
**Godot version:** both 3922883 and 3.2.*

**OS/device including version:** windows 10

**Issue description:**
Calling a non-static method statically from another non-static method should be either compile time error or not an error at all. Running the below code on current master throws a runtime error `Bug, call error: #-1728575696` and in 3.2 it just skip over the method call `Aclsas.f()` at line 9.

```gdscript
extends Node2D

class Aclass:
	func f():
		print('Aclass::f, line:5')
		
	func g():
		print('Aclass::g, line:8')
		Aclass.f();                   ## <--- this line cause the bug!
		print('Aclass::g, line:10')

func _ready():
	var a = Aclass.new();
	a.g();
	print('::_ready, line:15')

```

**Comment by lyuma** [comment]
issue is still present on godot master (85186bc)

**Comment by vnen** [comment]
Tested this in current master (db028ac7001cca42c9f61cc231e2363ae884e70a) and 3.3.1 (which is what I had handily available) and cannot reproduce in either.

In 3.3.1 it shows an error message but does not make a breakpoint in the editor when debugging, which could be improved.
