### ISSUE TITLE
C# Error message point to one line above in Visual Studio Code

### ISSUE THREAD

**Issue by vitorbalbio** [godotengine/godot#41816]
**Godot version:**
Godot 3.2.3 RC4

**OS/device including version:**
Win10

**Issue description:**
When double clicked in any error report it point to one line above in code.

![Godot_v3 2 3-rc4_mono_win64_OHUQmYBXce](https://user-images.githubusercontent.com/6172013/92330852-8ea96880-f048-11ea-888d-d20745419ae7.png)
![Code_sACDSKXxl6](https://user-images.githubusercontent.com/6172013/92330856-90732c00-f048-11ea-8e68-fb6a994104bc.png)

**Steps to reproduce:**
Write any code that broke. Click on the error report. it will point to the line above. e.g error in line 45 , it will point the line 44 in Visual Studio Code.

**Comment by raulsntos** [comment]
This issue seems to be about the Errors tab in Debugger, this was fixed by https://github.com/godotengine/godot/pull/73584. But I noticed the same issue also applies to the errors list in the MSBuild panel, this will be fixed by https://github.com/godotengine/godot/pull/79404.
