### ISSUE TITLE
Image.get_pixel() from Viewport returns nan

### ISSUE THREAD

**Issue by bmolyneaux** [godotengine/godot#41815]
**Godot version:**
3.2.3.rc5

**OS/device including version:**
Mac OSX 10.15.5
OpenGL ES 3.0

**Issue description:**
I obtain an Image from a Viewport. Getting a pixel from this Image occasionally returns nan Color. The supplied image coordinates are valid (within the width and height of the image). No errors are printed when a nan value is returned. Sometimes all color channels are nan and sometimes it's only some channels that are nan while others are zero.

This behavior is not consistently reproducible. However, it seems that switching windows makes it far more likely to happen.

```
var image = get_node("Viewport").get_texture().get_data()
image.lock()
var value = image.get_pixel(12, 14)
image.unlock()
assert(!is_nan(value.r))  # <- occasionally fails
```

**Minimal reproduction project:**
[Archive.zip](https://github.com/godotengine/godot/files/5179929/Archive.zip)

**Comment by scottmpowell** [comment]
I wasn't able to reproduce this on three versions, maybe it's an OS-specific issue.

OS: Arch Linux 5.8.5-arch1
Godot Versions: 3.2.2, 3.2.3-rc5, 4.0

**Comment by akien-mga** [comment]
I can't seem to reproduce it either on Linux with the latest `3.2` branch (5357e6a974cadf58bfdfa215250bdc12dd5fdea5).

@bmolyneaux Can you still reproduce the issue on 3.2.4 beta 3 or later?

**Comment by bmolyneaux** [comment]
I couldn't reproduce it on either 3.2.4 beta 3 or even 3.2.3.rc5 on the same machine as I originally encountered the bug.

You may as well close this issue.
