### ISSUE TITLE
GUI framework

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#4181]
How about using a gui framework like [electron,](http://electron.atom.io/) for the editor. I think most of the godot usability problems are related to the editor ui, and the editor has problems with the ui because of its implementation using a custom ui framework, the godot gui framework is well suited for a game (uis in games are very simple or should be) but not for a complex application like an editor, using html, and css would be very beneficial for future editor modifications.

**Comment by eska014** [comment]
I disagree. Godot Engine's editor being itself implemented as a Godot "game" is what makes the editor so powerful and allows simple extension though GDScript plugins, addons, `tool` scripts, ...
The Control node system, especially the Container classes, work excellently to create complex GUIs. If there's something wrong, or could work better, it can (and, as the past has shown, will) be fixed.

**Comment by Calinou** [comment]
Electron is very heavy in terms of CPU, RAM usage and loading times, that's a no-go.

**Comment by djrm** [comment]
CPU and RAM are ok, i personally use electron powered programs and they are just fine as far as im concerned, in terms of extensibility i guess eska is right, it would be kinda difficult to integrate something like tool scripts in an electron powered editor

**Comment by TheoXD** [comment]
UI with web and java script? No way! Everyone thought Planetary Annihilation would run fast enough if build on top of web technology, they were wrong! It may look nice, but it's a bloat.

**Comment by jackmakesthings** [comment]
A web-stack interface definitely doesn't make sense here, but that said, I'd love to see some time put towards improving the theme creation interface. Right now it's not very intuitive and sort of clunky to use, IMO. (Or, if not the UI, maybe the format themes are stored as could be tweaked to be easier to manipulate.)

**Comment by naive231** [comment]
> I disagree. Godot Engine's editor being itself implemented as a Godot "game" is what makes the editor so powerful and allows simple extension though GDScript plugins, addons, `tool` scripts, ...
> The Control node system, especially the Container classes, work excellently to create complex GUIs. If there's something wrong, or could work better, it can (and, as the past has shown, will) be fixed.

As you mentioned, Godot's editor should be able to deployed on Web if I want, right?
After I export the final 'game' as HTML5/WebGL platform, I should be able to use the editor by browser?

**Comment by Zireael07** [comment]
@naive231 Yes, Godot editor itself can be deployed on web, see: https://godotengine.org/online/godot.tools.html

**Comment by naive231** [comment]
> @naive231 Yes, Godot editor itself can be deployed on web, see: https://godotengine.org/online/godot.tools.html

OMG, It unexpectedly can run on the web page.
This is the first time I'd seen, the editor itself actually is the game of the engine, that's so amazing.
Thanks for your reply, mate.
