### ISSUE TITLE
String function "get_basename" does not check whether the file path is valid

### ISSUE THREAD

**Issue by PhoenixStroh** [godotengine/godot#41817]
**Godot version:**
v.3.2.2.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
Using the string function `get_basename`, it says within the documentation that "If the string is a valid file path, returns the full file path without the extension." However, no matter what string is provided, `get_basename` will return what was inputted before, and does not check if the file path is valid. The similar functions of `get_base_dir` , `get_extension` , and `get_file` all correctly check if the file path is valid. However, `get_basename` does correctly parse the string and removes the extension as documented.

**Steps to reproduce:**
using a LineEdit node var called "dirPath" to enter the string, and printing it on button press.
`print( dirPath.text.get_basename() );`

**Comment by Zylann** [comment]
In this function, the definition of `valid` is not that the file actually exist, but that the string contains *what could be a valid path*. What the function actually does is removing file extensions, and nothing else.

**Comment by PhoenixStroh** [comment]
Okay, I apologize if I mis-used Issues, I'm new to github and was hesitant if this was the correct behavior or a real issue.
