### ISSUE TITLE
Godot Runs But Windows are Black

### ISSUE THREAD

**Issue by BloodyMess** [godotengine/godot#41825]
**Godot version:**
Build the latest zip snapshot of master.

**OS/device including version:**
Hardware:
- Ryzen 3900X
- Sapphire Pulse Radeon RX 580
- 128GB RAM

Software:
- elementary OS 5.1.7 Hera (based on Ubuntu 18.04.4 LTS)
- Linux 5.4.0-45-generic
- GTK 3.22.30
- Mesa 20.1.7~kisak2~b
- gcc/bionic-updates,bionic-security,now 4:7.4.0-1ubuntu2.3 amd64 [installed,automatic]

**Issue description:**
Godot launches and runs, but the window only briefly shows the usual gray-blue background color, and then the window content turns entirely black, with only the title bar looking normal. Controls will respond to clicks, but everything is black.

**Steps to reproduce:**
1. Download and extract a zip of the latest Godot master.
2. Build Godot.
3. Launch the newly built Godot program.
4. The windows will be black.

**Minimal reproduction project:**
(not applicable)

**Comment by Calinou** [comment]
Make sure to build Godot with `target=debug` (the default), not `target=release_debug`: https://github.com/godotengine/godot/issues/40601

**Comment by BloodyMess** [comment]
> Make sure to build Godot with `target=debug` (the default), not `target=release_debug`: #40601

Thanks! That got it working. Does that make this a duplicate issue?

Now I just wish I could get Godot building with LLVM again : #40279, #41852.

**Comment by Calinou** [comment]
> Does that make this a duplicate issue?

Indeed, this issue is a duplicate of #40601 then. Closing.
