### ISSUE TITLE
Have Editor Remember Visible Collision Shapes Setting

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#4182]
The Visual Collision Shapes setting is great, especially for us programmer types. No longer do I have to come up with placeholder art, especially early on in development when I'm trying to get the core of the engine down.

But every time I re-open the editor, I invariably forget that Visible Collision Shapes always defaults to Off, so I'm always confused oh-so-briefly that nothing appears on the screen.

It'd be nice if the editor remembered the state of Visible Collision Shapes (either per-editor or per-project), as I suspect I'm not the only one who uses it as a significant source of visual information during development.

This behavior should probably also apply to the other editor/debug settings, but I haven't used them yet.

**Comment by ivodopiviz** [comment]
This issue is invalid. The editor saves debug settings as project metadata.

**Comment by Gastronok** [comment]
The originally described behavior still appears in the 2.x branch.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
