### ISSUE TITLE
Grid Container description should say it only works with Control based nodes, not with Node2D based nodes.

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#41822]
**Your Godot version:** 3.2.2, latest , stable

**Issue description:**
"Grid container used to arrange **elements** in a grid like layout."
"Grid container will arrange **its children** in a grid like structure,"
"GridContainer reorders **its children** to accommodate the new layout."

"children" or "elements" is not true, it won't work with any Node2D nodes like Sprites, KinematicBody2Ds or regular Node2Ds.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_gridcontainer.html

**Comment by NathanLovato** [comment]
It's about the class reference so transferring to this repo, where the class reference is.

I think it's fair to specify `Control children` or `child Control nodes`. It wouldn't bloat the reference to have it here and there, and it makes the docs more explicit.
