### ISSUE TITLE
Black rendering on materialed mesh.

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#41831]
**Godot version:**

Godot 3.2.3.rc4.official

**OS/device including version:**

OS: Windows 10 64-bit version 2004 build 19041.450
GPU: Intel UHD Graphics 620 driver version 27.20.100.8587
GLES3

**Issue description:**

Adding/creating material for a mesh will cause the mesh's rendering to be completely black in a certain distance, as shown in the attached file:

![Mesh-materials-rendering-issue](https://user-images.githubusercontent.com/1403194/92337091-7e5fb080-f07d-11ea-9b9d-f5e1390758d3.gif)

**Steps to reproduce:**

1. Create the MeshInstance node.
2. Add/create material for the MeshInstance.

**Minimal reproduction project:**

[reproduction_project.zip](https://github.com/godotengine/godot/files/5180436/reproduction_project.zip)

**Comment by Calinou** [comment]
Like https://github.com/godotengine/godot/issues/30330, this is likely specific to Intel HD 620 IGPs on Windows.
