### ISSUE TITLE
Build failure with Python 2 in 3.2 branch

### ISSUE THREAD

**Issue by efornara** [godotengine/godot#41858]
**Godot version:**

Godot 3.2.3-rc5

**OS/device including version:**

Raspbian 8&10 / VideoCore IV

**Issue description:**

I have been compiling godot for a long time on Raspbian 8 (i.e. debian 8 / scons2 / python2 / g++ 4.9).  That setup has been serving me well actually.

I have just compiled 3.2.3-rc5 and I have had the same problem as here: https://github.com/godotengine/godot/issues/40988

First I tried Raspbian 10 (Raspbian 8 is admittedly obsolete). Same problem. I then changed `/usr/bin/scons` to use python3. It might have worked, but I stopped the build because I have got a warning saying that `-j` wasn't supported with that version of python, making it a no go for me.

I suppose I could install scons 4 manually and carry on, but I have just checked what the change is and this seems to be the relevant commit:

https://github.com/godotengine/godot/commit/7e1312055bcb6a65f934728e29291ae00a1d1a19

Reverting that made 3.2.3-rc5 compile with scons2 / python2 / g++ 4.9.

I was wondering if it is worth bumping the scons requirements in a point release. I personally would suggest reverting that commit, at least for the 3.2 branch.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
> I suppose I could install scons 4 manually and carry on, but I have just checked what the change is and this seems to be the relevant commit:
>
> 7e13120

Well that's not a SCons version requirement bump, that's a bug...

The SCons version requirement is in `SConstruct`:
```
EnsureSConsVersion(0, 98, 1)
```

**Comment by akien-mga** [comment]
Fixed by #41860.
