### ISSUE TITLE
Reimporting a 3D scene doesn't update meshes

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#4186]
Godot 2.0.1 under GNU/Linux and Windows 8 (tried on both, same results).

If I re-export a scene from Blender using the better collada exporter, Godot shows the red exclamation mark sear the "Settings" menu. I can click it, the list of asssets to re-import displays. I click ok, the re-importing seems to progress fine. All is done, but the geometry never changes. Textures can be re-imported and they update, but meshes never update. I need to delete the scene and start over if I want to change something.

**Comment by volzhs** [comment]
in my case,
I can see updated mesh if close and re-open scene after re-importing.

**Comment by bojidar-bg** [comment]
Was this somehow fixed in 2.1/HEAD or master?

**Comment by toger5** [comment]
I have the same issue on current master.
The mesh only reloads on editor restart
The editor also detects the change when I save in blender and automatically executes a reimport... but the meshes don't updte.
In the original DAE and the inherited scene

**Comment by Calinou** [comment]
Closing in favor of #38853, which has more information about the issue at hand.
