### ISSUE TITLE
Camera with invalid zoom values: ERROR: affine_invert: Condition ' det == 0 ' is true.

### ISSUE THREAD

**Issue by colorworlds** [godotengine/godot#41873]
**Godot version:**
3.2.2

**OS/device including version:**
win7-64,GLES2

**Issue description:**
It seems that there are many situations that can cause this error:
https://github.com/godotengine/godot/issues/36642
https://github.com/godotengine/godot/issues/31090
  
I met the camera situation.

**Steps to reproduce:**
create a **Camera** node ,then set **Zoom** property to (0,0) and run the scene. 
you can see many  error as shown below:
```
ERROR: affine_invert: Condition ' det == 0 ' is true.  
ERROR: affine_invert: Condition ' det == 0 ' is true.  
ERROR: affine_invert: Condition ' det == 0 ' is true.  
```
I've tried to make negative numbers legal, like (-1,-1)
So I think the editor should prohibit setting the camera's zoom property to (0, 0),or change it to (1,1).  

  
  
**supplement:**
And I also found another problem with the camera, but I'm not sure if it's a bug. It  doesn't make any serious mistakes.
Correct situation:
If there are two camera nodes in the  **A** scene,Their **Current** properties are enabled.
**A** scene node structure:
```
--Node2D:
----Camera1   // Current is true
----Camera2    // Current is true
```

when the game runs,only one the **Current** properties of  Camera node will be enabled. 
```
--Node2D:
----Camera1   // Current is false
----Camera2    // Current is true
```
the editor can fix this to correct situation.

Feeling abnormal:
If there are two scene **A** and  **B**,each has a camera.Their **Current** properties are enabled.
And the  **A** scene has a  **B** scene instance node.
**A** scene node structure:
```
--Node2D:
----Camera1     // Current is true
----B                 // B scene instance
------Camera2   // Current is true
```

when the game runs,the two **Current** properties of  Camera node will be enabled. 
```
--Node2D:
----Camera1    // Current is true
----B                  // B scene instance
------Camera2    // Current is true
```
the editor not fix this situation.

**Minimal reproduction project:**
Both of the above issues are easy to implement

**Comment by akien-mga** [comment]
> **Godot version:**
> 3.2.3

Please be more specific, 3.2.3-stable hasn't been released yet.

**Comment by colorworlds** [comment]
> > **Godot version:**
> > 3.2.3
> 
> Please be more specific, 3.2.3-stable hasn't been released yet.

sorry,I type the wrong number.It's 3.2.2-stable.
