### ISSUE TITLE
Godot architecture diagram

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#4189]
**Issue description** (what happened, and what was expected):
I was trying to find what input library Godot uses, to look what features does it exhibit and if there are any metrics like latency etc. gathered for it. So I went to https://github.com/godotengine/godot/tree/master/drivers and couldn't understand what most of those directories contain.

Here is the list:

```
alsa               - audio
angle              - graphics
builtin_openssl2   - network
builtin_zlib       - utility/compression
chibi              - ???
convex_decomp      - ???
dds                 
etc1
gl_context
gles2             
jpegd
mpc
nedmalloc
nrex
ogg
openssl           - network
opus
png
pnm
pulseaudio
pvr
rtaudio
speex
squish
theora             - utilities/formats
unix
vorbis             - utilities/formats
webp               - utilities/formats
webpold
windows
```

Above I tried to map few logical blocks to show what information I expect to find about them. As you may see I couldn't find the module that is responsible for input (like http://gainput.johanneskuhlmann.de/). Perhaps it is managed by Godot core directly, but I have no proof and not enough hours to read the code to figure this out.

What would help is a colored diagram of components of Godot engine (even a list of blocks would find for the first approximation) - every color is a function of the component as shown above. Then a picture of how different functions are meld together, and which components are responsible for every function (color).

I could do some ugly SVG's in Inkscape that could be improved later, but it would be nice to learn something from design/art gurus and get something inspiring as a result.

**Comment by akien-mga** [comment]
See http://docs.godotengine.org/en/latest/reference/introduction_to_godot_development.html#architecture-diagram

**Comment by SuperUserNameMan** [comment]
@techtonik : "chibi" is a soundtrack music module player. You can use it through the EventPlayer Node. You can play IT, XM, S3M and MOD musics.

**Comment by reduz** [comment]
EventPlayer node is designed so you can play stuff such as midi with
soundfonts or DLS for interactive music, or other types of music/sound
generation too, but never had time or priority to work on that.

**Comment by Hinsbart** [comment]
@techtonik You're right, Godot doesn't use an input library, every platform has it's own input code.
After that, all the events are "godotified" in `main/input_default.cpp`

**Comment by techtonik** [comment]
Awesome. The diagram clarified things a lot. And brings the ground for more questions.

@reduz I guess DTS is [this](https://en.wikipedia.org/wiki/DLS_format). EventPlayer is a strange name for MusicTracker interface. Maybe it is a good name for interactive music with few events per second, but for real tracker there can be hundreds if not thousands events that are not really high level, and emitting non-filtered events for them even without handlers may add too much overhead. Just some thoughts. Need to understand use cases better.


Anyway, "chibi" was just first in the list. The role and diagram place of other directories without description is also mostly unclear. If diagram sources are hackable, it may be possible to map specific blocks to repository sources. Maybe that info can be extracted automatically somehow?

@akien-mga is there source code for that diagram? What software is required to update it? Right now I see that it may need a small shift to the right to fix outgoing arrow from "Sample, ...".

@Hinsbart aha, I see. So godot keeps joystick and keyboard state in its own classes. But where is actual platform specific code, like translating scancodes etc.? (also good candidate for devdocs).

**Comment by akien-mga** [comment]
It could be interesting to have a more complete architecture diagram showing all the libraries and how they're used, but that's probably worth discussing in a specific issue on https://github.com/godotengine/godot-docs at this stage.

It's also not a trivial task and it would need to be updated every now and then, so we would need the source for the diagram indeed (I don't have the source for the current one, maybe @reduz does...).

**Comment by techtonik** [comment]
I wonder.. can Godot autogenerate its own architecture diagram? Or dump graph of compiled components and their interconnections in JSON/YAML data structure, which can be then used to test different graph layout algorithms from game library.
