### ISSUE TITLE
Vector2 Constructor Mismatch

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#41903]
**Godot version:**

3.2 branch commit 784e854e580f8a9335c8dc738bbc8b83ea0fdd65

**OS/device including version:**
Arch Linux

**Issue description:**
Two pieces of GDScript code involving a `PoolStringArray` should be equal in functionality, however when statically typing a variable with `PoolStringArray`, the `Vector2` constructor is not matched correctly.

**Steps to reproduce:**
Consider the following GDScript:
```gdscript
#!/usr/bin/godot -s
extends SceneTree

func _init():
	var location : String = "(182, 182)"
	var coordinates = location.replace('(','').replace(')','').split(',')
	print(typeof(coordinates))
	print(Vector2(coordinates[0], coordinates[1]))
	quit()
```
There the entries of the `Vector2` constructor are both of type `String` and the code seems to work fine.

However, if you add `PoolStringArray` as the static type for the `coordinates` variable like the following:

```gdscript
#!/usr/bin/godot -s
extends SceneTree

func _init():
	var location : String = "(182, 182)"
	var coordinates : PoolStringArray = location.replace('(','').replace(')','').split(',')
	print(typeof(coordinates))
	print(Vector2(coordinates[0], coordinates[1]))
	quit()
```

you will get the following:

```
SCRIPT ERROR: GDScript::reload: Parse Error: No constructor of 'Vector2' matches the signature 'Vector2(String, String)'.
   At: res://./vector2_constructor_mismatch_bug.gd:8.
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:599.
```

**Minimal reproduction project:**
The two pieces of GDScript code are provided above.

**Comment by capnm** [comment]
Try
`var coordinates := location.replace('(','').replace(')','').split(',')`
print(Vector2("42", "42")

**Comment by Rubonnek** [comment]
@capnm Oh, I see what you mean now.

I just tried statically casting one of the variables:

```gdscript
#!/usr/bin/godot -s
extends SceneTree

func _init():
	var location : String = "(182, 182)"
	var coordinates = location.replace('(','').replace(')','').split(',')
	print(typeof(coordinates))
	var test : String = coordinates[0];
	print(Vector2(test, coordinates[1]))
	quit()
```

And the following error makes it clear:

```
SCRIPT ERROR: GDScript::reload: Parse Error: No constructor of 'Vector2' matches the signature 'Vector2(String, var)'.
   At: res://./vector2_constructor_mismatch_bug.gd:9.
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:599.
```

Looks like there's an implicit type `var` for uncasted variables that `typeof` doesn't really return the type of -- it seems to be used only by the parser to know whether a variable is allowed to be casted automatically.

Statically casting a variable to `PoolStringArray` also statically casts it's array entries as `String`.

Thanks for pointing this out.

**Comment by Calinou** [comment]
> #!/usr/bin/godot -s

That's interesting, I didn't know you could use a shebang to run Godot scripts. This should be documented in the command-line tutorial :slightly_smiling_face: 

Note that using `#!/usr/bin/env godot -s` is preferable as it will search in the user's environment variables for the Godot binary instead of hardcoding its path.

**Comment by Rubonnek** [comment]
> Note that using `#!/usr/bin/env godot -s` is preferable as it will search in the user's environment variables for the Godot binary instead of hardcoding its path.

Shebangs only accept one parameter IIRC, so that will not work. Everything after the binary path will be considered as a single string and you'll get get the following:

```
/usr/bin/env: ‘godot -s’: No such file or directory
```

Because it's trying to find the `godot -s` binary (space included). A workaround could be using a symbolic link to avoid the `-s` flag.

I remember seeing the shebang used by someone in reddit, but wow you are right, this is not documented either.

I've opened [issue #3990](https://github.com/godotengine/godot-docs/issues/3990) to document this. I'll do it sometime at the end of the week.
