### ISSUE TITLE
GDScript static methods not implicitly cast into Callable 

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41919]
**Godot version:**  0a8c5845e

**OS/device including version:** windows 10

**Issue description:**

It's possible to assign a native function to a variable as a Callable but it's not possible for GDScript static function.

```gdscript
class Aclass:
	static func static_func():
		return 'Aclass::static_func() called'

func _ready():
	var callable1 = OS.get_process_id
	print(callable1.call())  ## <-- prints the pid
	
	var callable2 = Aclass.static_func
	print(callable2.call()) ## <-- invalid get index 'static_func'
	
```

### MRP
[41919.zip](https://github.com/godotengine/godot/files/11736820/41919.zip) (for 4.x)

_Bugsquad edit: added the MRP_

**Comment by lyuma** [comment]
Still present on latest godot master (85186bc)

Can be worked around by using the syntax `Callable(Aclass,"static_func")` instead of `Aclass.static_func`

**Comment by cdemirer** [comment]
Note that the error happens while evaluating `Aclass.static_func`, not in the line with `.call()` as originally indicated.
https://github.com/godotengine/godot/blob/bc2445d0eb1b4d00de7506fbea4384212c8dfe16/modules/gdscript/gdscript_vm.cpp#L973

**Comment by scally** [comment]
This happens in Godot 4.0a7 as well. The workaround still works. Also, strangely, creating a new instance of the object and then calling the static method on that instance also works.

**Comment by dalexeev** [comment]
The bug is still reproducible in 4.0 RC 1.

**Comment by adamscott** [comment]
### MRP for 4.x
[41919.zip](https://github.com/godotengine/godot/files/11736820/41919.zip)
