### ISSUE TITLE
Allow to disable the "output overflow" limit

### ISSUE THREAD

**Issue by TheSuspiciousWombat** [godotengine/godot#4192]
Implement an option to disable the "output overflow" limit.

**Comment by Larpon** [comment]
This is quite a turn-off for programmers that are used to debug most things via console output

**Comment by vnen** [comment]
I feel that if you get to that point you're already lost in the amount of info in the console. Also, IIRC this is only shown in the editor output panel, not in the console, so you could use that.

**Comment by vnen** [comment]
I assume it's because of the debugger protocol. It runs over the network and allocate stuff in the stack, there's only so much memory available for those messages (and all other info sent by the debugger). The console print happens directly to terminal output, so it doesn't have this limitation.

**Comment by Larpon** [comment]
@vnen 
> I feel that if you get to that point you're already lost in the amount of info in the output. 

Not if you're debugging a hard to trace sequence of incidents that lead up to e.g. a crash (and a following headache when you've tried to figure it out for 2 hours - with no luck)

I need to see exactly where, what and when in the execution order things has happened - so for this I need the complete history of print statements.

I can't think of any framework or library I've ever used where logging was limited like this. If the buffer is full - flush it :) I can see the trouble when it's network related though but in terms of debugging it should be solvable. For instance Qt's debugging can be done both locally and remote without limitations as far as I have tried.

A choice to disable output via the network (using std/err out instead) on platforms that don't need remote output streaming would be nice?

Luckily I'm on Linux so I'll use the terminal output workaround as mentioned. I'd still consider this a bug or (awkward) limitation though.

**Comment by alkhimey** [comment]
Please, at least let me configure what the limit is. I am willing to sacrifice memory for this.
Godot does not have good debugger, so printing is the only option to trace bugs :disappointed:

**Comment by Kowbell** [comment]
While we don't have the option to disable the buffer yet, **you can customize the buffer size** at least as of 3.0.6. Check out `Project Settings > Limits > Debugger Stdout > Max Chars Per Second`. You can set that to an astronomical number and print to your heart's content, as long as that's <= 2,147,483,647 (and some change) characters per second. _(Note: Do not actually try to print that many characters unless you have a lot of time and memory.)_

I started poking around the source to try implementing this feature before realizing it's already there. If anyone truly wants to disable the "output overflow" limit, you can check out `ScriptDebuggerRemote::_print_handler()` in `script_debugger_remote.cpp`. There lies the overflow check. It's pretty straightforward (assuming you know C++):

```cpp
void ScriptDebuggerRemote::_print_handler(void *p_this, const String &p_string, bool p_error) {

	ScriptDebuggerRemote *sdr = (ScriptDebuggerRemote *)p_this;

	uint64_t ticks = OS::get_singleton()->get_ticks_usec() / 1000;
	sdr->msec_count += ticks - sdr->last_msec;
	sdr->last_msec = ticks;

	if (sdr->msec_count > 1000) {
		sdr->char_count = 0;
		sdr->msec_count = 0;
	}

	String s = p_string;
	int allowed_chars = MIN(MAX(sdr->max_cps - sdr->char_count, 0), s.length());
	//          Max Chars Per Second ^^^^^^^ is defined in the Project Settings

	if (allowed_chars == 0)
		return;

	if (allowed_chars < s.length()) {
		s = s.substr(0, allowed_chars);
	}

	sdr->char_count += allowed_chars;
	bool overflowed = sdr->char_count >= sdr->max_cps;

	sdr->mutex->lock();
	if (!sdr->locking && sdr->tcp_client->is_connected_to_host()) {

		if (overflowed)
			s += "[...]";

		sdr->output_strings.push_back(s);

		if (overflowed) {
			sdr->output_strings.push_back("[output overflow, print less text!]");
		}
	}
	sdr->mutex->unlock();
}
```

If you cut out the use of the `int allowed_chars` and `bool overflowed` variables you will completely ignore the buffer limit.

**Comment by mitchcurtis** [comment]
I'm sorry, but this is a flat out ridiculous default setting.

> I feel that if you get to that point you're already lost in the amount of info in the output.

So you consider 20 lines of text being "lost"? That's roughly what the default settings cut me off at.

My experience in the last 30 minutes trying to get the rest of the output where the problem actually lies (in a function dealing with pathfinding called by `_process()`) shows the exact opposite: I'm lost without the output that was omitted.

Trying to use the debugger when I haven't even narrowed down where the exact problem is is a waste of time - I would be stepping through code for the rest of the day.

> Also, IIRC this is only shown in the editor output panel, not in the console, so you could use that.

What console? I'm using the editor on macOS and I have the editor window and that's it.

> While we don't have the option to disable the buffer yet, you can customize the buffer size at least as of 3.0.6. Check out Project Settings > Limits > Debugger Stdout > Max Chars Per Second. 

Maybe it's change since then, but for me, with 3.1, the relevant settings are in Project > Project Settings > General > Network > Limits > Debugger Stdout.

2048, 10, 10 are the defaults, respectively. I'm not sure which one is the limiting factor in my case (probably `Max Messages Per Frame`, but I bumped them up considerably and now it's actually sane:

<img width="899" alt="Screen Shot 2019-04-15 at 6 44 50 PM" src="https://user-images.githubusercontent.com/6002340/56150199-9fb68d00-5fae-11e9-904b-1b87a86d310f.png">

> I started poking around the source to try implementing this feature before realizing it's already there.

Just curious... why not just bump the defaults up while you were in there?

**Comment by Calinou** [comment]
> What console? I'm using the editor on macOS and I have the editor window and that's it.

You can start Godot from a terminal by specifying the path to the binary contained in the `Godot.app` directory directly. Try running this in a terminal (replacing `/path/to/Godot.app` with the full path to the Godot application bundle):

```
/path/to/Godot.app/Contents/MacOS/Godot
```

**Comment by golddotasksquestions** [comment]
I'm on Windows and unfortunately while is has no "output overflow" the terminal only prints a small number of lines. I tried to change the settings, but it did not seem to make a difference.
The current output overflow is a default setting is making debugging absurdly hard. It will cut off printed text when you try to print more than 5 lines per physics frame at a frame rate of 60fps.

**Comment by Zireael07** [comment]
Most game engines do not have such a limit, because they do things such as grouping messages from the same source (see your browser's console for the quickest example)

**Comment by Calinou** [comment]
Would it be possible to increase the default value significantly (say, 4-10 times higher) in a compatible manner?

**Comment by Calinou** [comment]
I had a try at increasing the values similar to what @mitchcurtis did, but this causes the output to be "congested" over a few minutes of continuous printing. (I tested this by printing two numbers and pushing one error on every `_process()` frame)

The editor debugger probably needs a rewrite to handle this better, see #29533.

**Comment by Larpon** [comment]
As long as the order of output can be trusted @Calinau what you mention is better than omitting output in my opinion

**Comment by Faless** [comment]
The default limit has been greatly increased in #36751 (400 errors per seconds, 400 warnings per seconds, 32 KiB of text output per seconds).

I believe those are quite good default values, and the limits can be further increased by the user if needed.
Closing as fixed for now, we'll see if we need to raise the defaults further.

**Comment by darkconsole** [comment]
yeah well i triggered this on my 5th line in a loop. this is so annoying and makes no sense to even exist. just print what i ask man :\

![image](https://user-images.githubusercontent.com/9095897/167972358-ad8ee1ca-5066-4725-b675-c5c385d7113a.png)

**Comment by darkconsole** [comment]
for future reference if anyone else lands here like did because of frustration with the most basic of debugging method, searching for the word buffer i dont think exposes any of the settings you actually need those seem to be more networking lib related. these settings appear way more relevant.

![image](https://user-images.githubusercontent.com/9095897/168159562-65bfde54-1545-4e48-876f-9a1f16b66b94.png)

**Comment by ell1e** [comment]
The old limit option seems to have been removed. Where can this be set now, or preferably unset? While I somewhat get the default, it confuses me that this can't be easily disabled. (Or can it?) I ran into this after 5 minutes of print debugging more intensely in godot for the first time, and terminals can start lagging behind as well but devs may want infinite scrollback for that as well.

**Comment by Calinou** [comment]
The setting still exists in 4.x. It's a project setting (**not** an editor setting) called **Max Chars per Second**:

https://github.com/godotengine/godot/blob/88f3b5f9d52f740b24fabfb8bc01b8b7026ba279/core/debugger/remote_debugger.cpp#L169-L173

https://github.com/godotengine/godot/blob/88f3b5f9d52f740b24fabfb8bc01b8b7026ba279/core/debugger/remote_debugger.cpp#L661
