### ISSUE TITLE
Latest Rcedit is not compatible with Godot mono windows export

### ISSUE THREAD

**Issue by qdwang** [godotengine/godot#41938]
**Godot version:**

3.2.3 rc5 mono

**OS/device including version:**

windows 10

**Issue description:**

The rcedit won't change the icon of the exported exe file no matter whether the `embed pck` option is on or off.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Please provide more details. How do you configure rcedit in Godot? Which rcedit version do you use? How do you fill the export preset?

**Comment by Calinou** [comment]
Make sure to export the executable with a different name every time. Otherwise, Windows Explorer will take the old icon from the cache.

**Comment by qdwang** [comment]
Sorry, my mistake. No problem now.
