### ISSUE TITLE
Protect XR transforms from receiving NaN values from the hardware

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot#41943]
**Godot version:**
3.2.2.stable

**OS/device including version:**
Oculus Quest (Android)

**Issue description:**
There are occasional NaN values getting into Godot's ARVR transforms from the hardware API (specifically the Quest) and not being filtered out or detected.  This caused a bug that took me 8 hours to track down.  

The XRServer somewhere around [here in the godot_oculus_mobile code](https://github.com/GodotVR/godot_oculus_mobile/blob/a76540e390f9efde7085777864b10d3e650edf51/plugin/src/main/cpp/ovr_mobile_session.cpp#L108) is updating the positional tracker value for the ARVRCamera that is accessed somewhere around [here](https://github.com/godotengine/godot/blob/dee8f8db745e58caedbf49bbc13a2fdcc8fb1da4/servers/xr/xr_positional_tracker.cpp#L197).  (I can't find the update loop where the API is actually being called and the bogus values are getting through.)

**Steps to reproduce:**

Take the simplest Oculus Quest demo project that comes with the library, like [this one](https://github.com/GodotVR/godot_oculus_mobile/tree/1ebb548701417f55de10b478462c13b1b5217ab2/demo)

Then in your `ARVROriginWithInitAndMovement.gd` (the one derived from `ARVROrigin`), add the following few lines at the start of the `_process()` function:

```GDscript
var processTimeStamp = 0
func _process(delta_t):
	processTimeStamp += delta_t
	if is_nan($ARVRCamera.transform.basis.x.x):
		print(" Bad ARVRCamera position:", processTimeStamp, " ", $ARVRCamera.transform)
```
The result will be:
> Bad ARVRCamera position:0.122599 nan, nan, nan, nan, nan, nan, nan, nan, nan - -0, 0, -0

In my application I was reliably getting a run of bad NaN values in the VR camera orientation fields between 0.15seconds and 0.26667seconds of startup -- there were a few valid values at the start, which made this bug so difficult to identify.  

I can't rule out that there won't be glitches in the system that spit out these values minutes or hours in.  If motions are being done relative to the camera (eg to keep the player within the walls) then this issue will cause the player to suddenly spin off to infinity, and it will be impossible to find out the bug.

We would hope it's not necessary for any sanity checking to be done for these values in the Godot system (eg to ensure that you don't get numbers well outside the range), because the VR operating system should do this itself because it knows the dimensions of the kit.  (Eg if we coded in a 50 metre range limit from the VROrigin then this would unnecessarily cause a problem when someone builds a 100m range device next yet.)  

However at the very least we should be logging errors when the numbers are completely out (NaNs, infinities, values that exceed a light year) to show where there are bugs in the VR operating system like this.  This is definitely an Oculus Quest bug and it should be reported to them.  For now I am having to check for NaNs in all my VR code where the positions are given by the hardware.

**Minimal reproduction project:**
See above

**Comment by m4gr3d** [comment]
@goatchurchprime Are you seeing these issues upon starting the app, or upon putting the headset on?
If it's upon starting the app, then it may be an issue in the plugin initialization logic.
If it's upon putting on the headset, then that may be expected as the device may take some time to initially acquire tracking.

Can you open a matching bug in the Quest plugin repo as well. That'll help with tracking and resolving the issue.

**Comment by BastiaanOlij** [comment]
@m4gr3d thats what I suspect too, probably the transform isn't set to an identity matrix if there is no tracking data meaning it will just be a bunch of zeroes. Could be as simple as just making sure we call identity() on the transform.

**Comment by m4gr3d** [comment]
@goatchurchprime Any updates on this issue?

**Comment by goatchurchprime** [comment]
I haven't been monitoring it, but I thought I saw it 2 weeks ago.  I just tried starting my app with the adb running just now and I didn't get any messages from [the lines in my code](https://github.com/goatchurchprime/tunnelvr/blob/d72c6c9de273276cc9d9c23fd584f7742bb9b986/PlayerMotion.gd#L86_)

Maybe there's been an update from Oculus that fixes it.  I don't know.  Today it is not reproducing on my Quest2.  I don't know what that means we should do with this ticket, but I'm not taking that `if is_nan()`-block out of my code.  

Meanwhile I do get a lot of `**ERROR**: Condition "p_aabb.position.x > 1e15 || p_aabb.position.x < -1e15" is true.` messages near startup that probably has nothing to do with this, but which I am having to ignore.

**Comment by goatchurchprime** [comment]
Actually, I'm still getting this issue of NaN's being returned for the VR camera position for the first 0.2 seconds of running an app, even on a new Quest2, so it's definitely not gone away. 
```
 skipping bad headcam position:0.125 orientation (nan, nan, nan)
 skipping bad headcam position:0.138889 orientation (nan, nan, nan)
 skipping bad headcam position:0.152778 orientation (nan, nan, nan)
 skipping bad headcam position:0.166667 orientation (nan, nan, nan)
 skipping bad headcam position:0.180556 orientation (nan, nan, nan)
 skipping bad headcam position:0.194444 orientation (nan, nan, nan)
 skipping bad headcam position:0.208333 orientation (nan, nan, nan)
 skipping bad headcam position:0.222222 orientation (nan, nan, nan)
```

**Comment by m4gr3d** [comment]
Fixed by https://github.com/GodotVR/godot_oculus_mobile/pull/128
