### ISSUE TITLE
Already loaded script instance is affected when edit the script during runtime

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#41948]
**Godot version:**
Godot Engine v3.2.2.stable.official

**OS/device including version:**
windows 10
mac os 10.12.6

**Issue description:**
An already loaded script instance is affected when i edit an existing script.

**Steps to reproduce:**
Use the attached project
- run the scene and click on element2 ( Hello is printed on console) (don't close)
- open the script res://TestClass.gd and change "hello" to "changed" and save it
- click again on element2 and "changed" is printed on console

**Minimal reproduction project:**
[testScriptLoad.zip](https://github.com/godotengine/godot/files/5201419/testScriptLoad.zip)

**Comment by MikeSchulze** [comment]
It's not a bug, is it a feature? ;)
What's the advantage? In which case does it make sense to synchronize changes at runtime?

**Comment by TheDuriel** [comment]
Export() takes care of most uses cases.

But I've used script reloading when debugging VR games, having a playtester in VR and making changes at runtime.

**Comment by MikeSchulze** [comment]
ok i understand, but this option makes problems when using the tree inside a plugin.
Than all functions are lost and the instance is useless.

**Comment by TheDuriel** [comment]
Disable it then, its an option.

**Comment by MikeSchulze** [comment]
ok thanks for the fast answer ;)
