### ISSUE TITLE
GDScript: base class constructor is not called when constructing a derived class

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#41952]
**Godot version:**  3b25548e4

**OS/device including version:** windows 10

**Issue description:**
base class constructor is not called when constructing a derived class. in the below code the `Base` class `_init()` method will never be called.
```gdscript
class Base:
	func _init():
		print('Base::_init()')

class Derived  extends Base:
	func _init():
		print('Derived::_init()')

func _ready():
	var d = Derived.new();
```
output:
```
Derived::_init()
```
expected:
```
Base::_init()
Derived::_init()
```

**Comment by vnen** [comment]
This is not a bug. If you want to call the parent you have to use `super()` to do it explicitly.
