### ISSUE TITLE
C# inputEvent constantly increases object count.

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#41950]
**Godot version:**

Godot_v3.2.3-rc6_mono_win64.

**OS/device including version:**

Windows 10.

**Issue description:**

Singleton with inputEvent constantly increases object count in debugger monitor. I've also tested scenario where inputEvent in main node with same result.

**Steps to reproduce:**
1. Run attached project.
2. Follow Debugger -> Monitor -> Object.

**Minimal reproduction project:**

[MLeak.zip](https://github.com/godotengine/godot/files/5201897/MLeak.zip)

**Comment by akien-mga** [comment]
C# objects are not reference counted but garbage collected, so it's normal. See the duplicate issue #41543.

The object count should decrease eventually when the GC comes into action, or if you dispose the object manually yourself.
