### ISSUE TITLE
BBcode in RichtTextLabel is not ignored by wrap

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41963]
**Godot version:**

beb9ebc

**Issue description:**

![image](https://user-images.githubusercontent.com/2223172/92817107-847bc700-f3c6-11ea-9786-bfc60b88ed57.png)
The text is `test, [color=red]test[/color],`

When I change it to `test, [color=red]test,[/color]` the second test gets wrapped correctly.
![image](https://user-images.githubusercontent.com/2223172/92817277-b2610b80-f3c6-11ea-9445-b2aa6f9d9ff4.png)

The BBcode should be ignored when wrapping, right now seems like it's treated like whitespace.

**Minimal reproduction project:**
[Node2D.tscn.txt](https://github.com/godotengine/godot/files/5204958/Node2D.tscn.txt)

**Comment by theoway** [comment]
Its the same with all the tags. I'll look into it.

**Comment by KoBeWi** [comment]
Looks related/duplicate of #31089 although mine has better description IMO .-.
