### ISSUE TITLE
TextEdit autoscrolls to top when wrapped

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41962]
**Godot version:**

beb9ebc

**Issue description:**

![BqtF0UQ6gA](https://user-images.githubusercontent.com/2223172/92815300-6319db80-f3c4-11ea-957a-3a92d7103290.gif)
Interestingly it only happens on the first line that goes under non-scrolled area.

**Steps to reproduce:**
1. Create a small TextEdit
2. Enable autowrap
3. Type something long

Might be related to #38180

**Comment by rodohanna** [comment]
I'm gonna start looking at this. I'm very new to the Godot source so be patient with me. :)
