### ISSUE TITLE
editor/editor_mode_node.cpp:5273 - An EditorPlugin build callback failed.

### ISSUE THREAD

**Issue by mo-moxi** [godotengine/godot#41973]
** Error **

Editor/editor_mode_node.cpp:5273 - An EditorPlugin build callback failed.

** Godot version **

Godot_v3.2.2-stable_mono_x11.64

** Site Samples **

https://docs.godotengine.org/en/stable/getting_started/step_by_step/index.html 

Mo

**Comment by akien-mga** [comment]
Sorry but there isn't enough information in this report for us to help you, or debug what happens.

Make sure that you have mono and msbuild installed and in the `PATH`.
