### ISSUE TITLE
Sprite3D wrong rendering order

### ISSUE THREAD

**Issue by FlorianWeissensteiner** [godotengine/godot#41993]
**Godot version:** 3.2.2.stable.official
**OS:** Windows 10

**Issue description:**
Two Sprite3D nodes, placed above each other in the world (think hamburger slices), render in the wrong order under given circumstances.

I figured out when this starts happening:

Picture a camera positioned above (+y) and to the south (+z) of a plane (facing +y), so that the camera looks at a 45 degree angle down at the plane's origin. Now picture a ray shooting out of the camera, and reflecting on the plane. The initial ray and its reflection are now at a 90 degree angle to each other.
Now picture a second plane above the first. The reflected ray from the first plane, intersects with this second plane. If the second plane is south (+z) of this intersection point, everything renders fine. But as soon as it moves north of it, the first (lower) plane is rendered first.
In other words, if the second (upper) plane's origin leaves the area spanned by the ray and reflected ray, it renders incorrectly.

This always happens in a 90 degree spanned area. The ray is not actually reflected (it was the most simple example at 45 degrees).
If for example the camera looks at the origin of the first plane at a 10 degree angle (above x-z-plane), it would hit the origin and then shoot towards 100 degrees (again, spanning 90 degrees), and NOT towards 170 degrees, which would be a reflection.

Illustration of the problem:

![demonstration](https://user-images.githubusercontent.com/13268841/92957978-bbef7f80-f469-11ea-8e8e-ccdf0582a0da.png)

Working correctly:

![depth_correct](https://user-images.githubusercontent.com/13268841/92958023-cc9ff580-f469-11ea-9d7f-2fbaa71ea0ca.png)

Not working correctly (leaving the 90 degree area):

![depth_bug](https://user-images.githubusercontent.com/13268841/92958046-d9bce480-f469-11ea-8c31-1a77c5a6a7f6.png)

The size of the Sprite3D nodes (planes) does not affect this behaviour (neither scale, nor pixel-size).
This behaviour also occurs in the editor, not just when the game is started.

I also attached an example project with 4 scenes, where the camera looks at a 10, 22.5, 45, and 67.5 degree angle towards the origin of the lower sprite, to illustrate the behaviour. In each scene, the upper sprite is positioned just outside of the 90 degree area where it starts breaking. So if you increase the translate.z of the upper sprite by 0.001, it renders correctly. (see info.gd)

[sprite3d_depth_bug.zip](https://github.com/godotengine/godot/files/5210842/sprite3d_depth_bug.zip)

Sidenote:
I encountered the Sprite3D rendering problem with a static camera, where only the player sprite was moving around, and static sprites positioned above other static sprites would randomly start switching rendering order based on where the player was currently positioned in the scene.
So my original problem was that with a static camera, layered static sprites that were not even moving would switch rendering order, based on another sprite's position (the player) that was nowhere near the static sprites. I do not know if this problem even has the same cause as the one i encountered when trying to investigate the original problem.

**Comment by Calinou** [comment]
There isn't much we can do about this. Transparency sorting issues are a known [limitation](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html) of rasterization-based rendering.

As a workaround, configure the **Render Priority** property on your SpatialMaterials accordingly.

**Comment by FlorianWeissensteiner** [comment]
> Transparent objects are sorted back to front before being drawn based on the Node3D's position, not the vertex position in world space.

Yup, that explains it perfectly. Sure enough, if I untick the transparent property on the Sprite3D, it renders correctly. This also explains the issue I had with the static sprites, because the player was on the same y coordinate as the sprites.

Thanks for getting back to me so quickly!
