### ISSUE TITLE
Godot Crashes when I test my game.

### ISSUE THREAD

**Issue by BkDevDude** [godotengine/godot#41994]
Hello, Godot has been crashing whenever I run my project.

**Godot version:**
I am using the v3.2.2-stable version

**OS/device including version:**
I'm on Chrome OS Linux, version 85.0.4183.84(i'm not gonna say all the specs because i know that this isn't a device problem)

**Issue description:**
When I click the play button to test my game, Godot stops working so I  have to force close it. Now, that has happened before, many, many times. So, I thought "Oh ok, there's an error in the code" since that's usually the problem when this happens. I read over all of the code and, no error, not even a warning. This has happened on repeat about 3 times, no idea why. I'm going to try again and update if anything new happens.

**Steps to reproduce:**
Load all game files in, the press play button.

**Minimal reproduction project:**
[Dungeon-Masters-Thanggggg.zip](https://github.com/godotengine/godot/files/5210985/Dungeon-Masters-Thanggggg.zip)

**Comment by qarmin** [comment]
Try remove .import folder when Godot is closed, and then open all scenes to check if everythings import correctly.
In your minimal project you have a problem with non existing script

**Comment by Calinou** [comment]
Try running Godot from a terminal and see if it spits out any error messages or crash messages.

**Comment by BkDevDude** [comment]
> Try running Godot from a terminal and see if it prints any error messages or crash messages.

The only way I am able to run the newest version of Godot is from a terminal, actually. It only shows errors after I close it and I have to restart the terminal.

**Comment by BkDevDude** [comment]
> Try remove .import folder when Godot is closed, and then open all scenes to check if everythings import correctly.
> In your minimal project you have a problem with non existing script

I fixed it. The problem was because in the previous zip file, there was a folder called scripts where those files were held but it was gone so it didn't know where the files were. Anyways, thanks for commenting, have a good day/night!
