### ISSUE TITLE
Suggestion: Separate help pages from scripts

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#4199]
On the scripts page, in the list of scripts, please separate scripts from help pages.  I can have a LOT more of the help pages open than scripts and then it gets tedious to find the script I actually need. It would be cool to have 2 tabs at the top of this page, or the top of the list panel, Scripts and Help.  Something to help organize.

**Comment by neikeq** [comment]
Currently, there is a option for placing the help pages after the script pages:

_Editor Settings -> Text Editor -> Group Help Pages_

![screenshot](https://cloud.githubusercontent.com/assets/7718100/14226421/e7c33440-f8e1-11e5-80fc-ba7e7f1939d1.png)

**Comment by bojidar-bg** [comment]
Shouldn't this be on by default?

**Comment by captainwasabi** [comment]
Ok, that's helps alot!  I agree that it should be the default.  I forgot about the editor settings.  They should be accessible from the editors menus

**Comment by zendorf** [comment]
Agreed, this should be on by default! I didn't know about that option either.
