### ISSUE TITLE
Godot not generate module mono glue.

### ISSUE THREAD

**Issue by mrdev023** [godotengine/godot#42011]
Godot not generate module mono glue.

**Godot version:**
463879db56 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #41995 from Rubonnek/disconnect-item-rect-changed

**OS/device including version:**
Windows 10 2004 20206.1000
GPU: RTX 2080ti
GPU: Driver 452.06 Game ready 
Mono :
```
 mono --version
Mono JIT compiler version 6.10.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

**Issue description:**
```
 scons -j32 platform=windows tools=yes module_mono_enabled=yes mono_glue=yes
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
Found MSVC version 14.2, arch amd64, bits=64
RuntimeError: Mono glue sources not found. Did you forget to run '--generate-mono-glue'?:
  File "D:\PROJET\Perso\godot\SConstruct", line 659:
    SConscript("modules/SCsub")
  File "C:\Users\flori\scoop\apps\scons\4.0.1\scons-local-4.0.1\SCons\Script\SConscript.py", line 661:
    return method(*args, **kw)
  File "C:\Users\flori\scoop\apps\scons\4.0.1\scons-local-4.0.1\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\flori\scoop\apps\scons\4.0.1\scons-local-4.0.1\SCons\Script\SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "D:\PROJET\Perso\godot\modules\SCsub", line 44:
    SConscript(name + "/SCsub")  # Built-in.
  File "C:\Users\flori\scoop\apps\scons\4.0.1\scons-local-4.0.1\SCons\Script\SConscript.py", line 661:
    return method(*args, **kw)
  File "C:\Users\flori\scoop\apps\scons\4.0.1\scons-local-4.0.1\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\flori\scoop\apps\scons\4.0.1\scons-local-4.0.1\SCons\Script\SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "D:\PROJET\Perso\godot\modules\mono\SCsub", line 23:
    raise RuntimeError("Mono glue sources not found. Did you forget to run '--generate-mono-glue'?")
```

modules/mono/glue/mono_glue.gen.cpp and modules/mono/glue/Managed/Generated not generated.

When i run this command ```.\bin\godot.windows.tools.64.mono --generate-mono-glue modules\mono\glue\```
A window is open and immediatly closed with no error and 0 status code.

```
PS D:\PROJET\Perso\godot> .\bin\godot.windows.tools.64.mono -v --generate-mono-glue modules\mono\glue\
PS D:\PROJET\Perso\godot> echo $?
True
```

**Steps to reproduce:**
- Clone the project in master branch (hash 463879db56)
- ```$ scoop install gcc python scons yasm make mono```
- ```$ scons -j32 platform=windows tools=yes module_mono_enabled=yes mono_glue=no mono_prefix=C:\Users\flori\scoop\apps\mono\current```
- ```$ .\bin\godot.windows.tools.64.mono.exe --generate-mono-glue modules\mono\glue\```
- ```$ scons -j32 platform=windows tools=yes module_mono_enabled=yes mono_glue=yes mono_prefix=C:\Users\flori\scoop\apps\mono\current```

All steps run correctly

**Comment by DarkKilauea** [comment]
I ran into this issue a while ago, it seems like the build doesn't contain all the DLLs required to run the editor with mono, so the glue generation step fails.

Using `copy_mono_root=yes` forces the build system to copy the required mono DLLs from your mono installation.

My build script for mono is thus:
```
scons -j6 p=windows tools=yes module_mono_enabled=yes mono_glue=no copy_mono_root=yes
bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue
scons -j6 p=windows tools=yes module_mono_enabled=yes mono_glue=yes copy_mono_root=yes
```

Note: You are not seeing the glue generation failure because the default subsystem for windows has been changed to GUI, which hides the console output.  You can add the `windows_subsystem=console` build parameter to cause the console to appear.

**Comment by Calinou** [comment]
This was fixed by https://github.com/godotengine/godot/pull/42332 (see https://github.com/godotengine/godot/issues/42011#issuecomment-691724908), closing.
