### ISSUE TITLE
PoolStringArray.empty() returns "False" when its empty

### ISSUE THREAD

**Issue by weirdo23** [godotengine/godot#42015]
**Godot version: Godot Engine v3.2.stable.official**

**OS/device including version: Win7 OpenGL ES 3.0 Renderer: GeForce GTX 1080/PCIe/SSE2**

**Issue description: PoolStringArray.empty() returns False when its empty**

**Steps to reproduce:**

```
	var nstr = ""
	print(nstr) #will not print! why?
	var strarr = nstr.split(" ",true,0)
	print(strarr) #prints [] an empty array
	print(strarr.empty()) #prints "False", claims to have contents
```
Output:

> []
> False

So, I was working on some Text processing and some of the lines were just empty. Strangely asking the returned PoolStringArray whether it was empty retuned `False` consistently. I managed to trace it to the `String.split()` function, which under certain arguments produces an empty array that is confused about its contents.
when compiling this report, I also noticed that `print("")` prints nothing. I was convinced that `print()` always concludes with a new line. Hence there is `printraw()` which doesnt.

Greetings

**Comment by Leleat** [comment]
I tried it and it's working as expected for me on 3.2.2 stable on Fedora 32.

> print(nstr) #will not print! why?

This will print an empty line. Try to `print("nstr: ", nstr)` and you should see it.

> 	var strarr = nstr.split(" ",true,0)
> 	print(strarr) #prints [] an empty array
> 	print(strarr.empty()) #prints "False", claims to have contents

You set `allow_empty` to be true. That means that there is an empty String and that `strarr` isn't an empty PoolStringArray but an PoolStringArray with one element, which is an empty String. Use `var strarr = nstr.split(" ", **false** ,0)` and it should work as you would expect.

**Comment by akien-mga** [comment]
Indeed, it's as @Leleat describes. The confusion comes from the fact that empty strings are not visible when printed (but they still exist and are valid).
