### ISSUE TITLE
Having BoneAttachment node before a Physical Bone for the same bone throws error

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#42010]
**Godot version:** 3.2.2 stable

**OS/device including version:** Windows 10

**Issue description:**

having a bone attachment node attached to a non root bone before a physical bone for that same bone in the heirarchy as shown:
![image](https://user-images.githubusercontent.com/7292421/93003927-f0157f80-f4ff-11ea-9ddf-a1cff9312aba.png)

throws this error message:
 scene/3d/skeleton.cpp:637 - Condition "bones[p_bone].physical_bone" is true.
 ./core/list.h:158 - Condition "!p_I" is true. Returned: false
![image](https://user-images.githubusercontent.com/7292421/93003872-90b76f80-f4ff-11ea-9c99-69e666f19435.png)

and this error message when run:
E 0:00:00.501   erase: Condition "!p_I" is true. Returned: false
  <C++ Source>  ./core/list.h:158 @ erase()
everything works fine, but you get that error message for each bone on scene load 

But if you rearrange it this way it works fine with no error message:
![image](https://user-images.githubusercontent.com/7292421/93003923-e8ee7180-f4ff-11ea-8844-ec857049eed1.png)

**Minimal reproduction project:**

[boneerrormessagedemonstration.zip](https://github.com/godotengine/godot/files/5213191/boneerrormessagedemonstration.zip)
project contains two scenes: HasErrorMessage.tscn and NoErrorMessage.tscn, which show it not working correctly and it working correctly respectively

**Comment by dane-johnson** [comment]
I think attaching a BoneAttachment might actually un-parent the Physical Bones. I keep finding their collision shapes at the world origin.
![bones](https://user-images.githubusercontent.com/10768827/94345898-b8720180-ffee-11ea-94fe-a505e955bfcd.png)

**Comment by pouleyKetchoupp** [comment]
Can still reproduce in 3.2.4 beta 5.

**Comment by akien-mga** [comment]
Fixed by #67698.
