### ISSUE TITLE
Platform-specific modules (e.g. GodotPayments) not appearing in generated class reference

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot#4201]
**Operating system or device:**
debian host, compiling for android

**Issue description** (what happened, and what was expected):

**Steps to reproduce:**
```
cp doc/base/classes.xml .
# release/linux_server.64 -doctool classes.xml

./bin/godot.x11.tools.64 -doctool classes.xml
```

**Link to minimal example project** (optional but very welcome):

**Comment by Anutrix** [comment]
I barely see usage of GodotPayments except for in `Engine.xml` as a class. Maybe we should remove/replace that.

GodotPayments seems to have moved into plugin https://github.com/godotengine/godot-google-play-billing. Is there a different Platform-specific module we can try?

**Comment by akien-mga** [comment]
Yeah both Android and iOS specific modules live in their own first party repositories, so it's expected that they won't be in the class reference.
