### ISSUE TITLE
GDScript: Parent class Member vars are reset when extending script is changed

### ISSUE THREAD

**Issue by mcardellg** [godotengine/godot#42028]
**Godot version:**
v3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
When a node that extends a class has a new script loaded the values of the parent classes member vars are reset to their defaults.
I would have hoped it would retain the set values.

**Steps to reproduce:**
Run the attached project, note how the values of the member varschange to their defaults when the script is changed.

**Minimal reproduction project:**

[thelostvars.zip](https://github.com/godotengine/godot/files/5214393/thelostvars.zip)

**Comment by ThakeeNathees** [comment]
@mcardellg the [docs](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-set-script) clearly stats that `set_script()` will reset all the variables.
> If the object already had a script, the previous script instance will be freed and its variables and state will be lost. The new script's _init() method will be called.

**Comment by mcardellg** [comment]
Thanks for the swift reply.

> the previous script instance will be freed and **its** variables and state will be lost.
Okay, so it's expected behaviour. Possibly add a clarification on the order of "including any member variables inherited from a parent class".
Also - did you spot that the onready var, which has a default value in the parent class, got reset to Null? I am not sure that is covered by the doc entry.

**Comment by ThakeeNathees** [comment]
@mcardellg 
```gdscript
# var x = get_node("path"); <-- you can't set get_node() as default value as it needs the scene tree first.
onready var x = get_node("path"); # <-- this will be called after the scene tree is ready so you can get the node
```
the above code is a syntax sugar for the below code
```gdscript
var x; # <-- initially null
func _ready():
    x = get_node("path");
```
The `_ready()` function will only called when the Node enters the scene (first time the it plays or if you add that node to another node in the scene tree) and setting it another script doesn't call `_ready()`, that's why the second time the string was Null

**Comment by pouleyKetchoupp** [comment]
Given that switching between built-in node types does keep common variable values, I would have expected the same behavior with custom scripts. But I guess https://github.com/godotengine/godot-proposals would be a better fit to suggest this change.

**Comment by mcardellg** [comment]
Yes, thanks, I am aware of the reason, I just think the result feels a bit counter-intuitive.

My problem, and sudden revelation, is that in my project the scripts I am attaching at runtime all extend the same class, it only just occurred to me that, of course, they could extend any class, so there is no reason to expect them to have the same member vars. Still very much learning Godot it seems.

Thanks for all the help, closing this now.
