### ISSUE TITLE
Re-importing asset with Filter off sometimes causes crash

### ISSUE THREAD

**Issue by ZackingIt** [godotengine/godot#42020]
**Godot version:**
3.2.2

**OS/device including version:**
Windows

**Issue description:**
When we re-import an asset and change its Filter bool status, the executable will crash upon re-running.

**Steps to reproduce:**
1. Import any uncompressed or losslessly compressed PNG in a 2D scene.
2. Compile to binary and play the game.
3. Exit game, toggle "filter" from on to off
4. Recompile and re-run the game.
5. The game has about a 50% chance of getting the following error:

```
ERROR: remove: Condition "p_elem->_root != this" is true.
   At: ./core/self_list.h:84
```
-- I know this seems really insane since this bug is usually associated with `remove_child` and other node operations, but I've managed to isolate my previous issues to ***some*** kind of asset importation issue.

You ***must** do this with a fresh png that has previously been unimported.

**Comment by Calinou** [comment]
Do you get any crash backtrace when the project stops? I'm not sure what could be a good way to get a crash backtrace when running the project from the editor.

> Recompile and re-run the game.

Godot projects aren't compiled when you run them (with the exception of C# where a solution is built). They're just run as-is from the project files, since GDScript is an interpreted language.

**Comment by ZackingIt** [comment]
Sorry yes -- I just mean re-exporting to `.pck`

**Comment by ZackingIt** [comment]
By the way -- I should add that I was able to confirm that the bug is not caused by my code -- I git-bisected to find the regression, then literally physically re-copied my code to avoid layering on any commits with generated config serializations from the engine, now I have a branch that works fully and another branch that has *some* kind of asset import misconfiguration that is causing an engine crash.

**Comment by fire** [comment]
Can you provide more details? Wanted to try recreating the problem under a debugger.

**Comment by ZackingIt** [comment]
I actually should close this issue:

this is actually coming from the failure to safely use multi-threading when combining with deferred signals.
