### ISSUE TITLE
Mesh collision shape generation size and position BUG

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#42027]
**Godot version:**

3.2.3 RC6 

**OS/device including version:**

Windows 10.

**Issue description:**

I have a few meshes generated in Blender (Box, 45° ramp, 22.5° ramp). Generating collision shape siblings on MeshInstance now creates wrong Trimesh and MultipleConvex collision shapes. Trimesh doesn't respect scale and position, MultipleConvex generates slightly bigger shape on-ramps.

**Steps to reproduce:**
Create MeshInstance with changed position and scale.
Generate CollisionShape sibling.

**Minimal reproduction project:**

[MeshCollisionShape.zip](https://github.com/godotengine/godot/files/5214270/MeshCollisionShape.zip)

**Comment by Calinou** [comment]
Did this occur with any older 3.2.3 RCs or 3.2.2?

**Comment by nezvers** [comment]
@Calinou Yes, this happens with 3.2.2.

**Comment by hoontee** [comment]
Bug: "Create Trimesh Collision Sibling" has been fixed in #42038.

Non-bug: "Create Multiple Convex Collision Siblings" uses approximate convex decomposition, which is efficient but not exact. See here: https://github.com/kmammou/v-hacd/blob/master/README.md
