### ISSUE TITLE
Custom Module singletons and classes are not showing in help

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot#4202]
**Operating system or device:**
debian compiling for android

**Issue description** (what happened, and what was expected):
admob module

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
This seems more like an Admob module bug. Leaving it open though for someone to confirm.

**Comment by volzhs** [comment]
as this one, https://github.com/punto-/godot_modules/tree/master/admob
it's becuase there is no cpp for admob.

**Comment by bojidar-bg** [comment]
What's the status on this issue? (bonus, is there something to be done on it from godot's side?)

**Comment by vnen** [comment]
They don't show in help because AFAIK only the export template is built with the module, not the editor itself. If that's the case, there's nothing to do here (unless the whole help thing is redesigned).

**Comment by Calinou** [comment]
Closing, as there's nothing that can be done about it if the module isn't compiled in the editor binary. See also https://github.com/godotengine/godot-proposals/issues/993.
