### ISSUE TITLE
OpenSSL security alert on google developer console for godot apk

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot#4203]
**Operating system or device:**
debian to build for Android

**Issue description** (what happened, and what was expected):
Logged into my google developer console, click the Yellow Bang icon above the loud speaker icon for displaying alerts.

"Your app is using a version of OpenSSL containing a security vulnerability. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.
https://support.google.com/faqs/answer/6376725"

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Closing as duplicate of #2780.
