### ISSUE TITLE
ResourceImporterLayeredTexture mismatched compress options

### ISSUE THREAD

**Issue by arccoza** [godotengine/godot#42043]
**Godot version:**

3.2.2

**OS/device including version:**

N/A

**Issue description:**

In a recent update the 'Lossy (WebP)' compress option was added to the importer options for `ResourceImporterLayeredTexture`, but neither the compress enum nor the `_save_tex` function were updated to match.

The option is added in `get_import_options` on [this line](https://github.com/godotengine/godot/blob/cd62be1845b32861d05cbdae43419f6b159cf3fe/editor/import/resource_importer_layered_texture.cpp#L84).

But the [enum](https://github.com/godotengine/godot/blob/cdc9fe154fb8e81559d31fd05859642e0cf3a3bf/editor/import/resource_importer_layered_texture.h#L66) doesn't have that option.

Nor does the [_save_tex](https://github.com/godotengine/godot/blob/cd62be1845b32861d05cbdae43419f6b159cf3fe/editor/import/resource_importer_layered_texture.cpp#L94) method.

We've now got a mismatch, where choosing *Lossy WebP* in the importer UI actually generates *Video RAM* textures, choosing *Video RAM* generates *Uncompressed*, and *Uncompressed* errors.

|  UI Option                  | Actual Option               |
|-----------------------------|-----------------------------|
| Lossless \(PNG\)            | Lossless \(PNG\)            |
| Lossy \(WebP\)              | Video RAM \(S3TC/ETC/BPTC\) |
| Video RAM \(S3TC/ETC/BPTC\) | Uncompressed                |
| Uncompressed                | Errors                      |

**Steps to reproduce:**
1. Select a texture to import as a TextureArray or Texture3D
2. Choose *Video RAM* compression
3. Check the .import folder for the generated platform specific textures

**Minimal reproduction project:**

[ResourceImporterLayeredTexture mismatched compress options.zip](https://github.com/godotengine/godot/files/5215827/ResourceImporterLayeredTexture.mismatched.compress.options.zip)

**Comment by arccoza** [comment]
There are two ways to fix this: The quick and easy way is to remove the *Lossy (WebP)* option. The longer way is to actually added *lossy* compression to the enum and `_save_tex` method. Which would be preferred?

FYI the [importer in 4.0](https://github.com/godotengine/godot/blob/1ce46f2a3f81e2395767a693b773adce7758d048/editor/import/resource_importer_layered_texture.cpp#L158) is quite different, but does include *lossy* compression.
Also missing from 3.2.2 if *lossy* is wanted is an option to set the quality of the compression.

**Comment by akien-mga** [comment]
Removing the extra option should be the way to go for now.

**Comment by arccoza** [comment]
Ok, would you like a PR against 3.2? It's a very small change.

**Comment by akien-mga** [comment]
Yes, that would be great :)

**Comment by akien-mga** [comment]
Fixed by #42045.
