### ISSUE TITLE
Unable to iterate on object of type 'Nil' (type changed since first iteration?).

### ISSUE THREAD

**Issue by GregTheMadMonk** [godotengine/godot#42050]
**Godot version:**
4.0.dev.custom_build.6ee1b7862

**OS/device including version:**
Arch Linux 5.8.8-arch1-1

**Issue description:**
In a minimal reproduction project there is a file CLevel.gd that is used there similarly to the way I use it in my other project. Upon execution of `walls()` method, on line **54** (`warr.push_back({
				"start":	shape.points[shape.points.size() - 1],
				"end":		shape.points[0]
			})`), it throws an error **Unable to iterate on object of type 'Nil' (type changed since first iteration?).** for an unknown reason. When used in 3.2 the same way, everything works just fine.

Contents of **CLevel.gd**:
```gdscript
class_name CLevel

var shapes = Array()
var spawn_point = Vector2(0.0, 0.0)

var depth = 0.5;

var objects = Array()

func constructTemplate():
	shapes = [
		{
			"points": [
				Vector2(-0.5, -0.5),
				Vector2(5.5, - 0.5),
				Vector2(5.5, 5.5),
				Vector2(-0.5, 5.5)
			],
			"cclock": true
		},
		{
			"points": [
				Vector2(0.5, 0.5),
				Vector2(4.5, 0.5),
				Vector2(4.5, 4.5),
				Vector2(0.5, 4.5)
			],
			"cclock": false
		}
	]

func walls():
	var warr = Array()
	
	for shape in shapes:
		var last = null
		for point in shape.points:
			print(point)
			if last != null:
				if shape.cclock:
					warr.push_back({
						"start":	last,
						"end":		point
					})
				else:
					warr.push_back({
						"start":	point,
						"end":		last
					})
			
			last = point
		
		if shape.cclock:
			warr.push_back({
				"start":	shape.points[shape.points.size() - 1],
				"end":		shape.points[0]
			})
		else:
			warr.push_back({
				"start":	shape.points[0],
				"end":		shape.points[shape.points.size() - 1]
			})
	
	return  warr
```

**Steps to reproduce:**
1. Create a new project
2. Put CLevel.gd from minimal issue project in it
3. Create a scene, create a script for it
4. In a script, in `_ready` do:
```gdscript
var level = CLevel.new()
level.constructTemplate()
for wall in level.walls(): print(wall)
```
5. Run the scene. It should throw an error

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/5218120/project.zip)

**Comment by ThakeeNathees** [comment]
An actual minimal project:
```gdscript
func bug():
	var arr = [1, 2]
	for __ in arr:
		
		## comment the below line out and the iteration will never terminate
		var local_var
		
		## this conditional jump is required for the bug
		if false:
			pass
		else:
			## if the local_var declared above it'll throw a runtime error below
			print('blah blah..')

func _ready():
	bug()
```
the bytecode generator for the gdscript have refactored recently that might be the cause for this bug.
