### ISSUE TITLE
GLES 3 is not supported on some devices that used to run it in the past for android

### ISSUE THREAD

**Issue by d-rex-15** [godotengine/godot#42063]
The device used: ASUS zenfone 
model number: ASUS_Z00LD
Android: 6.0.1
GODOT 3.2.3 RC6

This is an issue that was present in 3.2.2 as well. I used to run my android game on Godot 3.1.2 on this device.
I recently upgraded to 3.2.2 from 3.1.2 and found this same issue.

When I try to run GLES3 the app just goes to a black screen on the older device(which used to support this when using GODOT 3.1.2) but works on a newer device

GLES2 works on the old device but Fallback to GLES2 doesn't work but gives the same black screen

**Comment by Calinou** [comment]
Can you test older versions like 3.2 and the 3.2 alphas/betas/RCs as well? See [this page](https://downloads.tuxfamily.org/godotengine/3.2/) for downloads.

**Comment by d-rex-15** [comment]
Yes the problem is present in V 3.2.0 I just tested it out

**Comment by d-rex-15** [comment]
> Can you test older versions like 3.2 (= "3.2.0") and the 3.2 alphas/betas/RCs as well? This would greatly speed up troubleshooting. See [this page](https://downloads.tuxfamily.org/godotengine/3.2/) for downloads.

Yes the problem is present in V 3.2.0 I just tested it out

**Comment by d-rex-15** [comment]
> Can you test older versions like 3.2 (= "3.2.0") and the 3.2 alphas/betas/RCs as well? This would greatly speed up troubleshooting. See [this page](https://downloads.tuxfamily.org/godotengine/3.2/) for downloads.

Tell me if you want me to test out anything else because I'm not sure if this is easy to recreate and I don't know if it is present in other old devices and how old the device has to be, as it runs GLES3 in my new device. (do note that the old phone used to run GLLES3).

**Comment by d-rex-15** [comment]
> Can you test older versions like 3.2 (= "3.2.0") and the 3.2 alphas/betas/RCs as well? This would greatly speed up troubleshooting. See [this page](https://downloads.tuxfamily.org/godotengine/3.2/) for downloads.

The problem also persists in 3.2 alpha1 and 3.2 beta1

**Comment by akien-mga** [comment]
Try to remove or change the default environment (`default_env.tres`), it got fixes in 3.2 which made it slightly more demanding on the hardware, and thus less compatibility with lower end devices (for which it would be strongly recommended to use GLES2 though).

**Comment by boruok** [comment]
also persist on Godot 3.2.4 RC 1

**Comment by Calinou** [comment]
> also persist on Godot 3.2.4 RC 1

Does it work if you remove `default_env.tres` then export the project again?

**Comment by boruok** [comment]
@Calinou no, still stucked on logo, [New Game Project.zip](https://github.com/godotengine/godot/files/5897088/New.Game.Project.zip)

**Comment by akien-mga** [comment]
This is unlikely to be changed at this stage in the `3.x` branch. This issue likely means that some new features were added (or some bugs fixed) that increased the hardware requirements and made Godot's GLES3 renderer too demanding for low-end mobile.

The focus of rendering contributors is on Godot 4.0, which should also have a GLES3 renderer which will be made more compatible with older hardware (closer to Godot 3.x's GLES2 renderer), so this might be an option for those devices in the future (at least as long as we support their older Android versions, which might change).
