### ISSUE TITLE
Crypto.generate_self_signed_certificate returns null [regression from mbedtls 2.16.8]

### ISSUE THREAD

**Issue by jarroddavis6889** [godotengine/godot#42068]
**Godot version:**

3.2.3.rc6

**OS/device including version:**

Windows 10 Pro Version 2004 (Build 19041.508)

**Issue description:**

Crypto.generate_self_signed_certificate, returns null. I checked 3.2.2.official, and it works as expected.

**Steps to reproduce:**
```python
# Create and set key and self-signed certificate.

var crypto = Crypto.new()
    
# Generate 4096 bits RSA key.
var key = crypto.generate_rsa(4096)
key.save("res://private.key")
    
# Generate self-signed certificate using the given key.
var cert = crypto.generate_self_signed_certificate(key, "CN=example.com,O=A Game Company,C=IT")
cert.save("res://ssl.crt")

#cert will be null
```

**Comment by Calinou** [comment]
Can you test this with older 3.2.3 RCs? You can download them [here](https://downloads.tuxfamily.org/godotengine/3.2.3/).

**Comment by akien-mga** [comment]
Confirmed on 3.2.3 RC 6, this is a regression in RC 6, no bug in 3.2.3 RC 5 and earlier.

Here's the error in the terminal:
```
ERROR: generate_self_signed_certificate: Generated invalid certificate: -8576
   At: modules/mbedtls/crypto_mbedtls.cpp:270.
```

Changes between RC 5 and RC 6: https://github.com/godotengine/godot/compare/d773de6d244116c3ad26f0506a10038cc11019ff...8c5ed688476da64cbea17b34f1eacc76bac1d9c7

Most likely culprit: https://github.com/godotengine/godot/commit/48de6269492a960688274405620134b2c53f9b14 (@Faless)
