### ISSUE TITLE
Flipped tiles in hexamap demo are broken

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4206]
Likely since #3204 which caused some offset for vertically flipped tiles. As I understand it #3204 fixed a previously wrong behaviour, so now we need to rethink the hexamap demo to show how to make hexagonal tilesets that can still be flipped properly.

**Comment by neikeq** [comment]
I kind of "fixed" it (not really, read next paragraph) by changing the sprites/tiles offset to the center of the tiles/sprites (which is -64, -64) and changing the TileMap origin to center.

The problem? It's only works with the tile preview, not after placing the tile in the TileMap... I opened an issue about this some time ago: #3209. I can fix that issue if someone tells me what's the correct result with origin set as center (crossing my fingers for it to be the preview), and then I would check this one again.

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-demo-projects/issues/11.

**Comment by reduz** [comment]
I seriously forgot how TileMap works, if anyone is more up to date with it, feel free to find a way to fix this

**Comment by neikeq** [comment]
@reduz It's already fixed. There is still #3209 though :)
