### ISSUE TITLE
Sprite 3D axis setting not working Godot_v3.2.3-rc6

### ISSUE THREAD

**Issue by tommiemartin** [godotengine/godot#42079]
**Godot version:**
Godot_v3.2.3-rc6

**Issue description:**
axis on Sprite 3D has no effect, working correctly on 3.2.2stable

**Steps to reproduce:**
add a sprite 3d with default texture and change 'axis'

**Comment by akien-mga** [comment]
Confirmed, here's a minimal reproduction project: [Sprite3D axis.zip](https://github.com/godotengine/godot/files/5223687/Sprite3D.axis.zip)

In 3.2.2, the `axis` property changes the orientation of the Sprite3D:

Z axis (default):
![Screenshot_20200915_105656](https://user-images.githubusercontent.com/4701338/93189228-30644000-f742-11ea-9b88-9b7d7f97801e.png)

Y axis:
![Screenshot_20200915_105734](https://user-images.githubusercontent.com/4701338/93189306-440fa680-f742-11ea-9b43-e577201d2d8a.png)

X axis:
![Screenshot_20200915_105717](https://user-images.githubusercontent.com/4701338/93189276-3a863e80-f742-11ea-89ea-131b4116301e.png)

In 3.2.3 RC 6 (likely after #39867 by @clayjohn), it now behaves differently:

Z axis (default), same as 3.2.2:
![Screenshot_20200915_105849](https://user-images.githubusercontent.com/4701338/93189448-70c3be00-f742-11ea-90ce-2bc43c22e07e.png)

Y axis, vertically flipped:
![Screenshot_20200915_105909](https://user-images.githubusercontent.com/4701338/93189490-7caf8000-f742-11ea-8234-517e9172c4c3.png)

X axis, same as Z axis:
![Screenshot_20200915_105924](https://user-images.githubusercontent.com/4701338/93189521-85a05180-f742-11ea-82dc-c192853e4378.png)

**Comment by akien-mga** [comment]
Possibly related to this removal: https://github.com/godotengine/godot/pull/39867/files#diff-4b83b22d736cbbd1839998a01382b67cL516

But I don't know what the equivalent should be with the new mesh-based approach.

**Comment by akien-mga** [comment]
Fixed by #42091.
