### ISSUE TITLE
From Signal field from Edit connection window is not updated.

### ISSUE THREAD

**Issue by AureaFUNSoft** [godotengine/godot#42074]
**Godot version:**
Godot 3.2.3 RC 6

**OS/device including version:**
Windows 10

**Issue description:**

![Annotation 2020-09-15 124742](https://user-images.githubusercontent.com/8875839/93170686-df5c4800-f751-11ea-9dbb-8ecbf4a8c848.jpg)
See that the signal name in the window title and From Signal field is not same.

**Steps to reproduce:**
Make a new scene.
Add control node.
connect the node mouse_entered signal to its own grab_focus function.
Right-click minimum_size_changed signal and select Connect...
Then close the window.
Now right-click on grab_focus connection and select Edit...
See the From Signal still minimum_size_changed

**Minimal reproduction project:**

**Comment by aterlamia** [comment]
I would like to have a go at this
