### ISSUE TITLE
Android pre-launch report Accessibility tab warnings about splashscreen

### ISSUE THREAD

**Issue by ksvslk** [godotengine/godot#42075]
When uploading APK to Google Play pre-launch report catches these issues:

![Screenshot 2020-09-15 at 09 54 48](https://user-images.githubusercontent.com/29600539/93176944-afee1100-f73a-11ea-8024-ee41f7b43d78.png)
![Screenshot 2020-09-15 at 09 55 00](https://user-images.githubusercontent.com/29600539/93176950-b1b7d480-f73a-11ea-9f05-f7d77119185c.png)
![Screenshot 2020-09-15 at 09 54 41](https://user-images.githubusercontent.com/29600539/93176952-b2506b00-f73a-11ea-9848-603f6a144d31.png)
![Screenshot 2020-09-15 at 09 55 05](https://user-images.githubusercontent.com/29600539/93176955-b2e90180-f73a-11ea-9a5d-6ea0ef44f087.png)

**Godot version:**
3.2.3 RC5

**Issue description:**
Warnings in Google Play console

**Steps to reproduce:**
Upload app to Google Play

**Comment by akien-mga** [comment]
CC @godotengine/android 

There's not much to describe for screen readers on the splash screen, but maybe there's metadata that we can set as a hint for screen readers about what is on screen?

**Comment by ksvslk** [comment]
> CC @godotengine/android
> 
> There's not much to describe for screen readers on the splash screen, but maybe there's metadata that we can set as a hint for screen readers about what is on screen?

As I went through the Developer materials I found that you can turn this off for some elements but that might not be best solution.

**Comment by m4gr3d** [comment]
Android views have fields that allow to add additional information to make the app accessible (screen reader, tts, etc). 
Unless a game is specifically designed for accessibility however, the nature of a game engine makes these fields unusable (i.e: a custom accessibility framework has to be designed to tailor to each unique game since they don't make use of standard Android ux components). 

In this instance, it's fine to ignore these warnings.

**Comment by ksvslk** [comment]
I don't think it is a good idea to ignore such warnings. I am not sure at all that this will be ignored by Google that the games are not accessible - this is what Google robots see. This is what I was afraid of when I opened this issue. Please reconsider.

**Comment by bleedweedsuz** [comment]
I am having the same issue how to add description in that control.
I have same problem in my splash screen.

did some body figure it out.. too many warning now by the google play console, also they are saying need to fix before release.

![Screenshot 2024-08-08 at 10 28 29 PM](https://github.com/user-attachments/assets/96325792-63a6-49a1-879e-8331ab00ebfe)

![Screenshot 2024-08-08 at 8 25 22 PM](https://github.com/user-attachments/assets/bc36eede-13bb-4934-9930-8b9b50053f9d)

**Comment by rabid-dev** [comment]
I'm facing the exact same issue

**Comment by bleedweedsuz** [comment]
Its just a warning , ignore it. i had those message and still does, google playstore approve it.

**Comment by rabid-dev** [comment]
Aaah okay thanks for the tip, i thought my app was getting dragged back (partly) because of this

**Comment by ksvslk** [comment]
Wow, I cannot believe I complained about such a minor issue 🥲
