### ISSUE TITLE
HTTPClient connection keep-alive duplicate Headers 

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#4208]
**Operating system or device:**
Ubuntu 14.04 64-bit

**Issue description** (what happened, and what was expected):
I get the same header on to different requests with HTTPClient.
I try to use the same connection(keep-alive), the body is different but it is cut off because the content-length is from the first request on not the second. 

Lets say the first response body has a content-length of 10 and the second 20.
The HTTPClient delivers in both requests the same header(s) content-length 10. The second body shows only 10 chars. But contains the correct second body.

When I do the same steps with postman plugin on chrome it works perfectly fine.
When I use HTTPClient, disable connection: keep-alive and create a new connection for each request it also works.

Maybe it is my Websocket implementation but I checked that it is sending the correct headers and it also works with postman...

**Steps to reproduce:**
1. connect to a server
2. send a request(connection: keep-alive) that sends a response with an body(not chunked).
3. send a request(connection: keep-alive) that sends a response with an body that is bigger than the first(not chunked).

I tried many HTTPClient setups I can't find the reason...

blocking mode true/false -> no difference

```
var http
func _ready():
	http = HTTPClient.new() # Create the Client
	
	http.set_blocking_mode( true )
	
	var err = http.connect("localhost",3561,false) 
		
	while( http.get_status()==HTTPClient.STATUS_CONNECTING or http.get_status()==HTTPClient.STATUS_RESOLVING):
		http.poll()

func _on_Button_pressed():
	print(getResponse("/kategories"))

func _on_Button1_pressed():
	print(getResponse("/find?kategory=ALL&text=ic"))

func headers():
	return {
				"User-Agent": "Pirulo/1.0 (Godot)",
				"Accept": "*/*",
				"connection": "keep-alive"
			}

func dict_to_array(dict):
	var rs = []
	
	for key in dict:
		rs.append(key + ": " + str(dict[key]))
	return rs
	
func getResponse(url):

	var err = http.request(HTTPClient.METHOD_GET, url, dict_to_array(headers()))
	
	# Keep polling until the request is going on
	while (http.get_status() == HTTPClient.STATUS_REQUESTING):
		http.poll()
	
	if (http.has_response()):
		var headers = http.get_response_headers_as_dictionary()
		
		var rb = RawArray() #array that will hold the data
		
		if (http.is_response_chunked()):
			while(http.get_status()==HTTPClient.STATUS_BODY):
				http.poll()
				var chunk = http.read_response_body_chunk()
				if (chunk.size()!=0):
					rb = rb + chunk
		else:
			while(http.get_status()==HTTPClient.STATUS_BODY):
				http.poll()
				var chunk = http.read_response_body_chunk()
				if (chunk.size()!=0):
					rb = rb + chunk
					
		print(headers)
		print(rb.get_string_from_utf8())
```

**Comment by akien-mga** [comment]
Fixed by #4463.
