### ISSUE TITLE
Camera offset does not respect camera limits

### ISSUE THREAD

**Issue by securas** [godotengine/godot#42088]
This is related to #30358

**Godot version:**
3.2.1 stable

**Issue description:**
Unlike behavior in previous Godot versions, the camera offset does not respect limits. This was changed, breaking compatibility without considering existing projects.
Working around involves a rather complex limit of the offsets imposed whereas the workaround the issue #30358 would be far simpler.

A possible solution is to add a method of setting the limit regardless of offset.

**Comment by Calinou** [comment]
As stated in a comment in https://github.com/godotengine/godot/pull/30361:

> Code looks good.
> Note that one get have the old behavior can by moving the camera itself instead of changing the offset, so this is probably fine.

**Comment by securas** [comment]
I did. Substantially more complex than simply temporarily disabling the limits for screen shaking. Also, was this added to the list of compatibility breaks at release? I might have missed it.

**Comment by Calinou** [comment]
@securas I don't see a mention of it in the [changelog](https://github.com/godotengine/godot/blob/master/CHANGELOG.md). I've probably missed the commit in the log, apologies.

**Comment by securas** [comment]
Thanks

**Comment by securas** [comment]
Please consider including the previous behavior as an option. The current implementation is suitable when the camera is the child of another node that is controlling the position. If that is not the case, it becomes exceedingly complex to track the position of the camera (on a rail for example) whist panning. It would also preserve retro compatibility.

**Comment by Calinou** [comment]
@securas Please open a [proposal](https://github.com/godotengine/godot-proposals) for this, so we can judge how much this is desired.

**Comment by securas** [comment]
Is it possible to add this to the original proposal where the desire for this change was initially discussed? Opening a new one seems redundant.

**Comment by Calinou** [comment]
@securas No, as the original issue wasn't opened on the godot-proposals repository. That's the place where all feature requests should be made now :slightly_smiling_face:

**Comment by securas** [comment]
You should consider clarifying what is a feature request and what is a bug. I see this as a bug rather than a feature request. The original, on the other hand is a feature request and should have been included in the proposals since those have been around since longer than the issue.
