### ISSUE TITLE
Editor Function: "Lock the selected object in place" makes it unselectable.

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#42080]
**Godot version:**
 v3.2.2.stable.official

**Issue description:**
If a object is locked in place this way, it's also no longer selectable, which it should be imho.
![image](https://user-images.githubusercontent.com/16130334/93193382-11b47800-f747-11ea-8b34-7764302e0a31.png)

**Comment by KoBeWi** [comment]
This is intended behavior not a bug. If you want it changed, please [fill a proposal on the proposal repository](https://github.com/godotengine/godot-proposals).

btw in 4.0 you have an option to select a locked node by doing Alt+Click. See #35704.
