### ISSUE TITLE
Clicking a 2D node when editor is unfocused might result in a movement that you can't undo

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#42097]
**Godot version:**

7f0352b

**Issue description:**

This is a variation of #23779
When you click a node in unfocused editor, it might move permanently upon click if it gets snapped to grid. You can't undo it without reverting the scene.
![HwvmWH9RRl](https://user-images.githubusercontent.com/2223172/93240232-2b27e500-f784-11ea-8244-4a94e504523c.gif)
Notice how the scene remains "unmodified".

**Steps to reproduce:**
1. Place any 2D node (including Controls)
2. Enable grid
3. Make sure that the node isn't on a snapped position
4. Unfocus editor
5. Click the node
6. The node gets snapped upon click and when you try to undo it, you will realize that you can't and you are stuck with accidentally moved node

**Comment by Calinou** [comment]
Out of curiosity, can you reproduce this if you enable Single Window Mode in the Editor Settings (or start the editor with the `--single-window` command-line argument)?

**Comment by KoBeWi** [comment]
Yes. This also happens in 3.2.3 rc6 btw.

**Comment by KoBeWi** [comment]
Doesn't seem reproducible anymore in 4.0 beta.
