### ISSUE TITLE
get_aabb() returns AABBs with incorrect position-values

### ISSUE THREAD

**Issue by okapii** [godotengine/godot#42095]
**Godot version:**
Godot v3.2.3.rc6.official

**OS/device including version:**
MacBook Pro (13", 2020)
2,3 GHz Quad-Core Intel Core i7
16 GB 3733 MHz LPDDR4X
Intel Iris Plus Graphics 1536 MB

**Issue description:**
I hope that this is not a conceptual misunderstanding on my end but it seems to me that the position property of AABBs is reporting incorrect values.

<img width="863" alt="screenshot_aabb" src="https://user-images.githubusercontent.com/4265181/93237688-bc955800-f780-11ea-876b-e9f7c74fd7b4.png">

```
extends Spatial

func _ready():
	print($box1.get_aabb())
	print($box2.get_aabb())
	print($box2.get_aabb())
```

Running this code on the scene shown above yields the following output:

* -0.5, -0.5, -0.5 - 1, 1, 1
* -0.5, -0.5, -0.5 - 1, 1, 1
* -0.5, -0.5, -0.5 - 1, 1, 1

As one can see all position values are identical despite the cubes being positioned differently.

Originally I assumed that this was by design and that one would have to offset the AABBs utilising the object's origin-coordinate to get the correct position of the AABB in the global world. But that surely can't be right as this would result in varying / wrong values depending on where the origin is positioned in relation to the actual geometry.

**Steps to reproduce:**
See above

**Minimal reproduction project:**
[200915_Godot_AABB.zip](https://github.com/godotengine/godot/files/5226386/200915_Godot_AABB.zip)

**Comment by Calinou** [comment]
Did you find a solution to this issue?

**Comment by okapii** [comment]
@Calinou : I thought I did. But by now I am even more stumped. :) Right now I am just unsure if this is a bug or an issue on my end which is why I did not reopen things.

I have come to realise that the AABBs never reflect position, rotation and scale of instances. get_aabb() always leads to the bounding box of the unrotated, unscaled object positioned at the origin resulting in false collision detection. Position can be accounted for by altering the AABBs position-property according to the instance's origin but I am fairly stumped now as to how to account for rotation and scale. Sadly I can't find too much information on the whole AABB topic in Godot in general.

**Comment by okapii** [comment]
As I still can't seem to find a solution here is an illustration of the issue. It is still the basic code form above.

**Scene in perspective**
<img width="879" alt="200915_aabb" src="https://user-images.githubusercontent.com/4265181/93264685-c67e8180-f7a7-11ea-8dee-b1f1e7253ff6.png">

**Intersection false**
![200915_aabb_false](https://user-images.githubusercontent.com/4265181/93264697-cbdbcc00-f7a7-11ea-9a68-c1f2b27ca3a2.jpg)

**Intersection true**
![200915_aabb_true](https://user-images.githubusercontent.com/4265181/93264701-cc746280-f7a7-11ea-939d-cae42c980655.jpg)

```
extends Spatial

func _ready():
	var b1 = $box1.get_aabb()
	var b2 = $box2.get_aabb()

	b1.position += $box1.translation
	b2.position += $box2.translation

	print(b1.intersects(b2))
```

As one can see what matters is not the actual position / rotation / scale (as seen on the left side of the images) but the default rotation where in the 2nd one this leads to a small intersection while in reality both versions should report "true" as the bounding boxes should intersect.

**Comment by pouleyKetchoupp** [comment]
Could you check if `get_transformed_aabb` gives you the right result? It looks like `get_aabb` is the bounding box in local space, while `get_transformed_aabb` is in world space.

**Comment by okapii** [comment]
Yeh, that was the obvious solution I was afraid of potentially just not seeing. So yeah, thanks, that worked!

I guess the method is not documented in https://docs.godotengine.org/de/stable/classes/class_aabb.html for being inherited from VisualInstance?
