### ISSUE TITLE
LineEdit behaving weird when checking for integer in text_changed signal

### ISSUE THREAD

**Issue by tanjunior** [godotengine/godot#42104]
**Godot version:**

3.2.2

**OS/device including version:**

win10-2004

**Issue description:**

Trying to make it so that LineEdit only accepts number to form a string from 0000 to 9999
[https://youtu.be/nunteynnNAA](https://youtu.be/nunteynnNAA)

**Steps to reproduce:**
Add a LineEdit node
Attach a new script
declare `var old_text = ""`
Connect LineEdit text_changed signal to the script

```
func _on_LineEdit_text_changed(new_text):
	if new_text.is_valid_integer():
		old_text = new_text
	else:
		text = old_text 
		set_cursor_position(text.length())
```

**Minimal reproduction project:**

[bug.zip](https://github.com/godotengine/godot/files/5228764/bug.zip)

**Comment by capnm** [comment]
Try `if new_text.is_valid_integer() or new_text == "":`

**Comment by tanjunior** [comment]
> Try `if new_text.is_valid_integer() or new_text == "":`

it works!

**Comment by capnm** [comment]
> it works!

So there is clearly a bug in your GDScript and you can close this issue ;-)
