### ISSUE TITLE
Input method doesn't support any styles

### ISSUE THREAD

**Issue by Dziban-dev** [godotengine/godot#42101]
**Godot version:**
3.2.2

AMDR7 7600, Deepin v20 (debian10 stable), Mesa drivers,

Godot won't start, if i start from command line i get the following:

$ ./Godot_v3.2 --verbose
Godot Engine v3.2.2.stable.official - https://godotengine.org
XInput: Refreshing devices.
XInput: Using touch device: Virtual core pointer
Input method doesn't support any styles
free(): invalid pointer
Aborted

NOTE: i already tried DRI_PRIME=0, that did not fixed it , libx11-dev is on version [ 2:1.6.7.1-1+dde amd64 ] which i believe is what debian 10 comes with.

Godot has been working just fine on this very same system for the past 6 months.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/40966.

**Comment by Dziban-dev** [comment]
> See also #40966.

well yeah i already read that post, however I'm not building/compiling godot, just trying to run the executable that one can download from the download section at godot.org, I don't know if you but i tried some the "fixes" listed in that post.

**Comment by Dziban-dev** [comment]
> See also #40966.

the guys at Deepin updated some packages including libx11-dev and issue resolved
here is the list up packages that were tackled in last update.
so im gonna close this issue.
https://ibb.co/4875Dt3
