### ISSUE TITLE
Crash when creating a project with the "Browse" button

### ISSUE THREAD

**Issue by Leleat** [godotengine/godot#42112]
**Godot version:**

Godot Engine v4.0.dev.custom_build.6f4384f20, 6f4384f

**OS/device including version:**

Fedora 32, Kernel 5.8.8

**Issue description:**

When creating a new project and and trying to change the project path with the "Browse" button, Godot will crash when you end up pressing the "Select current folder" or the "Select this folder" button.

**Steps to reproduce:**
Create a new project and try to change the project path with the "Browse" button. Godot will crash when you try to start the project with the "Select current folder" or the "Select this folder" button.

```
Godot Engine v4.0.dev.custom_build.6f4384f20 - https://godotengine.org
ERROR: Can't find layer: VK_LAYER_KHRONOS_validation
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:157)
ERROR: Can't find layer: VK_LAYER_LUNARG_standard_validation
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:157)
ERROR: Can't find layer: VK_LAYER_GOOGLE_threading
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:157)
DisplayServer::_create_window 0 want rect: 448, 300, 1024, 600 got rect 448, 300, 1024, 600
 
DisplayServer::_window_changed: 0 rect: 448, 330, 1024, 600
DisplayServer::_create_window 1 want rect: 710, 600, 714, 414 got rect 710, 600, 714, 414
DisplayServer::_window_changed: 1 rect: 710, 630, 714, 414
DisplayServer::_create_window 2 want rect: 610, 350, 700, 500 got rect 610, 350, 700, 500
DisplayServer::_window_changed: 2 rect: 610, 380, 700, 500
DisplayServer::_create_window 3 want rect: 835, 560, 250, 106 got rect 835, 560, 250, 106
DisplayServer::_window_changed: 3 rect: 835, 590, 250, 106
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3ca70) [0x7f0f62df2a70] (??:0)
[2] /lib64/libX11.so.6(XSetICFocus+0x9) [0x7f0f635457e9] (??:0)
[3] DisplayServerX11::process_events() (/home/toni/godot/platform/linuxbsd/display_server_x11.cpp:2687)
[4] OS_LinuxBSD::run() (/home/toni/godot/platform/linuxbsd/os_linuxbsd.cpp:238)
[5] ./godot.linuxbsd.tools.64(main+0x135) [0x1a0c8fb] (/home/toni/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[6] /lib64/libc.so.6(__libc_start_main+0xf2) [0x7f0f62ddd042] (??:0)
[7] ./godot.linuxbsd.tools.64(_start+0x2e) [0x1a0c70e] (??:?)
-- END OF BACKTRACE --
Aborted (core dumped)
```

**Comment by Ev1lbl0w** [comment]
AFAIK Fedora 32 uses Wayland, right? If you're using it, I don't know if Godot supports it yet...

**Comment by Calinou** [comment]
> AFAIK Fedora 32 uses Wayland, right? If you're using it, I don't know if Godot supports it yet...

Godot doesn't support Wayland yet, but it should be able to run with XWayland if I'm not mistaken.

Also, Fedora 32 will only use Wayland if you don't have a NVIDIA graphics card.

**Comment by Leleat** [comment]
No longer happening to me on c3964b6, so I am closing this.

> AFAIK Fedora 32 uses Wayland, right?

> Also, Fedora 32 will only use Wayland on new installations if you don't have a NVIDIA graphics card.

Just for the record since I didn't mention it on my original post:

- I'm not on Wayland. 
- Hardware:
   - i7-10750H
   - GTX 1650 Ti (mobile)
