### ISSUE TITLE
Casting to string makes the whole script fail in release build

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#42127]
**Godot version:**
6f4384f20

**Steps to reproduce:**
1. Add some Sprite node with a script
2. Put this code
```
func _ready() -> void:
	modulate = Color.red
	var a = 1.5
	var b = str(a)
	modulate = Color.blue
```
3. The sprite doesn't change color at all in release build

If you do `var b = a` it works fine.
Not sure about other conversions.

**Comment by DavidSichma** [comment]
Most built-in functions can not be called in release build as there is a function call validation that requires information only available from DEBUG_ENABLED.
https://github.com/godotengine/godot/blob/07112b92a85de9b2134f3208149b295f871d3642/modules/gdscript/gdscript_analyzer.cpp#L1854 `validate_call_arg` compares argument count and type, even without DEBUG_ENABLED. It gets information about the function to call from few lines above
https://github.com/godotengine/godot/blob/07112b92a85de9b2134f3208149b295f871d3642/modules/gdscript/gdscript_analyzer.cpp#L1817 however `get_info` returns no information without DEBUG_ENABLED so comparing argument counts fails.

removing validate_call_arg from release builds solves the issue, but I do not know what kind of validations are still expected to run in release builds.

**Comment by DavidSichma** [comment]
broken builtins have been reported here (https://github.com/godotengine/godot/issues/41706) but issue remained unresolved

**Comment by JestemStefan** [comment]
Can't reproduce in https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20210727/

Here is a project with exports for Windows and Linux. (I couldn't export for macOS or some reason)
I tested Windows and it works just fine. I'm looking for someone with Linux to test

https://drive.google.com/drive/folders/1fZLyHgh6b7o5hQ6VUa622w4p_SsCgRTM?usp=sharing

**Comment by akien-mga** [comment]
Confirmed, it seems to work fine in 688228030850005f84d7b51a527bc779d76b905e.
