### ISSUE TITLE
Menu button generating pushed button texture offset

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#4213]
**Operating system or device:**
Arch x86_64 and Windows 10 x86_64

**Issue description** (what happened, and what was expected):
I added a menu button to a VBox container and it acted strange when pressing it

**Steps to reproduce:**
Add a menu button to a vbox container, then click it in the game view

Screenshot:
![1459682365](https://cloud.githubusercontent.com/assets/3101690/14232156/50aca050-f99f-11e5-8148-5b26ec3814d4.png)

**Comment by reduz** [comment]
I can't reproduce

**Comment by reduz** [comment]
also the picture above seems fine, nothing seems out of place

**Comment by bojidar-bg** [comment]
Uhm, can someone reproduce on any recent version, or is this a nonissue as well?
