### ISSUE TITLE
Custom Resources cannot be assigned in the editor when using "@tool"

### ISSUE THREAD

**Issue by TwistedTwigleg** [godotengine/godot#42134]
**Godot version:**
v4.0.dev.calinou.6ac7b9009

**OS/device including version:**
Ubuntu Linux, 64-bit.

**Issue description:**

Custom resources that use `@tool` cannot be assigned to nodes in the Godot editor. An error is returned and the resource is not assigned to the slot. The error shown is the following: `editor/editor_properties.cpp:2564 - Condition "!resp" is true. Breaking.` Looking at the code at the code given in the error, it appears the casting to a Resource type fails when `@tool` is used despite the script extending a Resource type. The issue can be worked around by removing `@tool`, assigning the resource, and then adding `@tool` again.

This bug was discovered on my 2D and 3D IK pull requests, where users can make custom IK solutions by extending the SkeletonModification base class. Using `@tool` on these resources allows users to make GDScript IK solutions that run in the Godot editor, like the C++ ones, but this bug makes it difficult. The workaround can be used to avoid the issue, but it is not ideal.

Additionally, custom resources defined using `class_name` show up in the selection drop-down in the Godot editor, but when assigned to a node, the base resource name is shown rather than the Resource's `class_name`. This is a relatively minor issue though.

**Steps to reproduce:**
Create a script that extends a Resource and define it's `class_name`. If the resource does not have `@tool`, then it will allow you to set use the resource in the editor like the build-in Resources. The editor will not show the correct name for the resource in the editor, it will show the base class name rather than the given `class_name`, but the custom resource will otherwise work as expected.

If the script that extends Resource has `@tool` and a custom class name, the following error will be shown when trying to assign the resource in the Godot editor `editor/editor_properties.cpp:2564 - Condition "!resp" is true. Breaking.` and the resource will not be properly assigned. If you remove `@tool` and assign the resource, and then add `@tool`, the resource will run in tool mode as expected but new instances of that resource cannot be added in the editor without using the workaround again.

The minimum reproduction project has two scripts, one with `@tool` and one without `@tool` to show how this works. If you assign one of the Shape2D nodes to the Resource without `@tool` it works as expected, but assigning the Resource with `@tool` will result in an error.

**Minimal reproduction project:**

[Custom_Tool_Resource_Project.zip](https://github.com/godotengine/godot/files/5240402/Custom_Tool_Resource_Project.zip)

**Comment by lyuma** [comment]
Would it be possible to re-test on the latest godot master?
I believe this was fixed with either #47131 or #48253

**Comment by TwistedTwigleg** [comment]
Sorry for the late reply. I just tested the project and can confirm the issue is fixed now with the latest version of master. Thanks :+1: 
Closing this issue...
