### ISSUE TITLE
GDScript format string number placeholders work only after the dot

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#42135]
**Godot version:** 3.2.3.rc6

**OS/device including version:** Manjaro Linux

**Issue description:** Placeholder modifiers do not apply on both sides of a dot if it is specified. I expected that indents would apply based on the instructions both before **and** after the dot

**Steps to reproduce / Minimal reproduction project:** Try to fill the text in Label via GDScript as follows (clock-like format): `"%d:%02.2f" % [1, 2.3456789]`. I want `1:02.34` but get `1:2.34`.

**Comment by dalexeev** [comment]
```gdscript
tool
extends EditorScript

func _run():
    print("%d:%05.2f" % [1, 2.3456789]) # 1:02.35
    #           ^
```

You have used the wrong format (the first number indicates the total number of characters).

Not a bug.
