### ISSUE TITLE
C# can't build and open solution with Visual Studio Community: unable to find Godot.NET.Sdk

### ISSUE THREAD

**Issue by Classy11** [godotengine/godot#42138]
**Godot version:**

 v3.2.3.stable.mono.official

**OS/device including version:**

Windows 10 64 bit, Visual Studio Community 2019.

**Issue description:**

In 3.2.2 creating and building new mono projects worked, after upgrading to 3.2.3 I can't run and build newly created (and old) Godot projects anymore, building any type of C# Godot project both new and old with 3.2.3 from the Godot editor returns:

```
Project "New Proj.sln" (Restore target(s)):
	Message: Building solution configuration "Debug|Any CPU".
	Restoring packages for C:\Users\Classy\AppData\Local\Temp\NuGetScratch\6b0ff92b0b0f4e92a2848d32bbc2a496\d3933e8b4c6b472ab788feb042f8c045.proj...
	C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): error : Unable to find package Godot.NET.Sdk. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, Project Packages
	C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): error : C:\Program Files\dotnet\sdk\3.1.402\Sdks\Godot.NET.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
	Project "New Proj.csproj" (_IsProjectRestoreSupported target(s)):
	Done building project "New Proj.csproj".
	C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): warning NU1503: Skipping restore for project 'C:\Users\Classy\Desktop\newProj\New Proj.csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\Classy\Desktop\newProj\New Proj.sln]
	NuGetMessageTask: Determining projects to restore...
	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): warning : Unable to find a project to restore! [C:\Users\Classy\Desktop\newProj\New Proj.sln]
Done building project "New Proj.sln".
Project "New Proj.sln" (Build target(s)):
	Message: Building solution configuration "Debug|Any CPU".
	Restoring packages for C:\Users\Classy\AppData\Local\Temp\NuGetScratch\ca6c85bb262f44bfaf4ea2a9b11b4637\ea3b9dba342e4d669214b8001cfafe08.proj...
	C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): error : Unable to find package Godot.NET.Sdk. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, Project Packages
	C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): error : C:\Program Files\dotnet\sdk\3.1.402\Sdks\Godot.NET.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
	Project "New Proj.csproj" (default targets):
		C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): error MSB4236: The SDK 'Godot.NET.Sdk/3.2.3' specified could not be found. [C:\Users\Classy\Desktop\newProj\New Proj.csproj]
	Done building project "New Proj.csproj" -- FAILED.
Done building project "New Proj.sln" -- FAILED.
```

Also important to note is that I cannot open the C# solution for any type of 3.2.3 mono project (new and old) in Visual Studio Community either. It returns the following error: 
```
C:\Users\Classy\Desktop\newProj\New Proj.csproj : error  : The project file cannot be opened. Unable to find package Godot.NET.Sdk. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, Project Packages C:\Program Files\dotnet\sdk\3.1.402\Sdks\Godot.NET.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
```

**Steps to reproduce:**
With 3.2.3 mono create a new project, add a node, attach a C# script and hit build.

**Comment by neikeq** [comment]
Are you working offline without internet access?

**Comment by Classy11** [comment]
@neikeq No, I am working online with cable internet access.
Possible useful information is that the directory it is trying to find Godot.NET.Sdk in is indeed lacking the Godot Sdk file(s).

**Comment by rick551a** [comment]
What is your selected 'Build tool'? `Editor Settings > Mono > Builds > Build Tool.`

_Just a suggestion:_
Maybe try installing dotNetCli: [https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.401-windows-x64-installer](https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.401-windows-x64-installer)

and then then changing the build tool to dotNetCli, then create a new project + scene + .cs script + build.
If this works, then "MS Build (VS Build tools)" is the problem. DotNetCli works for me.

**Comment by Classy11** [comment]
@rick551a MSBuild (VS Build Tools) is the original setting I have tried it with.
I attempted installing the linked version of dotNetCli but it fails and tells me I already have a newer version of it installed. I acquired my dotnet sdk 3.1.402 through Visual Studio Community 2019 already. Perhaps this is the problem?
Because when building with "dotnet CLI" I get the following similar error trace:
```
Project "New Proj.sln" (Restore target(s)):
	Message: Building solution configuration "Debug|Any CPU".
	Restoring packages for C:\Users\Classy\AppData\Local\Temp\NuGetScratch\4aa8c12347d442c7882232328417b15c\51db6b26dd3c42e4b457431ca08a93aa.proj...
	C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): error : Unable to find package Godot.NET.Sdk. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, Project Packages
	Project "New Proj.csproj" (_IsProjectRestoreSupported target(s)):
	Done building project "New Proj.csproj".
	C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): warning NU1503: Skipping restore for project 'C:\Users\Classy\Desktop\newProj\New Proj.csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\Classy\Desktop\newProj\New Proj.sln]
	NuGetMessageTask: Determining projects to restore...
	C:\Program Files\dotnet\sdk\3.1.402\NuGet.targets(128,5): warning : Unable to find a project to restore! [C:\Users\Classy\Desktop\newProj\New Proj.sln]
Done building project "New Proj.sln".
Project "New Proj.sln" (Build target(s)):
	Message: Building solution configuration "Debug|Any CPU".
	Restoring packages for C:\Users\Classy\AppData\Local\Temp\NuGetScratch\4f650e6bac204f96bcaaeb44b180143a\051e3e1669844460818c58f4da3f5fdb.proj...
	C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): error : Unable to find package Godot.NET.Sdk. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, Project Packages
	Project "New Proj.csproj" (default targets):
		C:\Users\Classy\Desktop\newProj\New Proj.csproj(0,0): error MSB4236: The SDK 'Godot.NET.Sdk/3.2.3' specified could not be found. [C:\Users\Classy\Desktop\newProj\New Proj.csproj]
	Done building project "New Proj.csproj" -- FAILED.
Done building project "New Proj.sln" -- FAILED.

```

Maybe this is just the same build method of the visual studio community 2019 builder in the end so that would be why the error persists, but I am unsure about this.

**Comment by neikeq** [comment]
There may be something wrong with the NuGet config on your system. Try opening the [Developer Command Prompt for VS](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs), run `nuget sources` and copy the output here.

**Comment by rick551a** [comment]
@classy11, Your dotNetCli istallation is fine, its up to date. Now this error, I had this problem also, i tried a few things:

Maybe its nuget? Do you have a folder called`C:\Users\YOURUSERNAME\.nuget\` on your system?
Are you online when making the project first (Godot downloads its nuget stuff on first creation).

I also installed the **Microsoft .NET Framework 4.7 Developer Pack** from here: [https://www.microsoft.com/en-us/download]( https://www.microsoft.com/en-us/download)/details.aspx?id=55168

**Comment by Classy11** [comment]
@neikeq When entering that command in the dev cmd it returns the following:
```
'nuget' is not recognized as an internal or external command,
operable program or batch file.
```
Could this be the cause? No global environment variable set for nuget? I know it exists somewhere on my pc because Visual Studio Community uses it successfully for 3.2.2 projects, but my Visual Studio Community can barely even open a 3.2.3 project so when attempting to use NuGet through Visual Studio Community for a 3.2.3 project by clicking "Manage NuGet packages for Solution" it returns:
```
Operation Failed.
No project is supported by NuGet in the solution.
```

@rick551a That .nuget folder indeed exists.
I have also just tried building the Godot mono project after having installed your linked .NET Framework but nothing has changed unfortunately.

**Comment by neikeq** [comment]
Maybe there's a way to access this info from Visual Studio. Otherwise you could download `nuget.exe` here: https://www.nuget.org/downloads

**Comment by Classy11** [comment]
@neikeq I have downloaded NuGet from nuget.org. Put the executable in the new project's folder and ran `nuget sources`, this outputs:
```
Registered Sources:
  1.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  2.  Project Packages [Enabled]
      C:\Users\Classy\Documents\Godot Projects\spaceServer\nugetPackages
```

I also just did `nuget install Godot.NET.Sdk -Version 3.2.3` in the project folder which outputs:

```
Attempting to gather dependency information for package 'Godot.NET.Sdk.3.2.3' with respect to project 
'C:\Users\Classy\Documents\Godot Projects', targeting 'Any,Version=v0.0'
Package 'Godot.NET.Sdk 3.2.3' is not found in the following primary source(s):
'C:\Users\Classy\.nuget\packages\,
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\,
C:\Users\Classy\Documents\Godot Projects\spaceServer\nugetPackages'.
Please verify all your online package sources are available (OR) package id, version are specified correctly.
```

Should I add or modify a registered Source or something?

**Comment by neikeq** [comment]
You are missing the `nuget.org` source for some reason, so it can't resolve any package other than the ones you already have locally. You can edit `%APPDATA%\NuGet\NuGet.Config` with a text editor to add this source. For example, mine looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

**Comment by Classy11** [comment]
@neikeq Adding
`<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />`
has resolved my issue. Weird that mine didn't include the online source from the get-go. Thank you and all for your help!

This issue can be closed on my end.

**Comment by PixelsmithVR** [comment]
> 
> 
> What is your selected 'Build tool'? `Editor Settings > Mono > Builds > Build Tool.`
> 
> _Just a suggestion:_
> Maybe try installing dotNetCli: https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.401-windows-x64-installer
> 
> and then then changing the build tool to dotNetCli, then create a new project + scene + .cs script + build.
> If this works, then "MS Build (VS Build tools)" is the problem. DotNetCli works for me.

Strangely enough after installing dotNetCli from that link, it finally let me run, then when I switched back to JetBrains, that now works as well! Thank you for saving me a ton of time.
