### ISSUE TITLE
Godot Linux mint game window very small 

### ISSUE THREAD

**Issue by John0456** [godotengine/godot#42144]
I am using Godot 3.2.3 . I am running Godot on Linux Mint 20 Cinnamon with Cinnamon version being 4.6.7. I am using Ge-force GTX 1660 SUPER, NVIDIA 440 driver. All of my projects have a very tiny window when ran. This includes new windows.

**Comment by Calinou** [comment]
@John0456 Do you have an hiDPI display? What's the screen resolution of the PC you're using?

Linux (with X11) does not have a fallback system for applications that don't handle hiDPI support themselves. This means such applications will appear as tiny on hiDPI displays.

**Comment by John0456** [comment]
I have Acer Technologies 22 G226HQL and a dell sp2208wfp, and according to online datasheets and an online calculator, the dpi for my Acer is 333 DPi and 341 DPI for my dell monitor.

**Comment by Calinou** [comment]
@John0456 There's the culprit :slightly_smiling_face: 

You have two solutions here:

- Increase your project's **Test Width** and **Test Height** settings so the window is larger when you run the project from the editor.
- Enable **Fullscreen** in the Project Settings.

In any case, make sure to enable **Display > Window > Dpi > Allow Hidpi** to avoid issues on other platforms. Also, you need to configure your project to support [multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) for the solutions above to work correctly.

**Comment by John0456** [comment]
Test height does not change the height of the window and I would like to be able to test my game without using fullscreen

**Comment by John0456** [comment]
For some reason changing the Test Height does not affect the the window when ran. Is it possible there is another problem?

**Comment by Calinou** [comment]
@John0456 Did you disable **Resizable** in the Project Settings? It most likely won't work if it's disabled.

**Comment by John0456** [comment]
No I did not disable it. A fix that I have discovered is that I can change the monitor size to be in DPI mode. when I do this the game runs as normal but all of my system UI is strange

**Comment by John0456** [comment]
For some reason after changing the DPI settings it started working again.
