### ISSUE TITLE
Default C# script naming system can cause invalid class name

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#42149]
**Godot version: 3.2.3 mono stable**

**OS/device including version: Windows 10 x64**

**Issue description:**

**1)** Create a new scene by right clicking file dock & selecting `New Scene...`

**2)** In the popup for scene name, enter a name with spaces (e.g: "my scene")

**3)** Now create a new .cs script in this new scene. Use the defaults.

**4)** As the .cs file loads in editor observe red squiggly error lines as the class name is now 
`my scene : Node2D`
A class name cannot have a space.

_Maybe to resolve this the new script dialog should not allow script names with spaces by default?_

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Confirmed in 3.2.4 beta 3. Should be fairly easy to solve for anyone interested in Mono editor code.
