### ISSUE TITLE
ItemList does not allow "selecting" items

### ISSUE THREAD

**Issue by AnarcoCapitalCapo** [godotengine/godot#42141]
I'm trying to create an inventory from an item list node.

Using a panel as parent of the itemlist one.

After adding the items either by the UI or in code they show when i run the scene, but i cant click on any of them and get them selected, by code it does work but when I try to select by using the mouse clicks it does nothing, is there anything i have to setup in the node or project for it to handle de input event? i've seen other projects (even run one) and it does work properly in my computer.

I'm using the 3.2.2 godot stable version.

**Comment by Calinou** [comment]
@AnarcoCapitalCapo Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
