### ISSUE TITLE
Asset Library no longer works

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#42155]
**Godot version:** 3.2.2 and 3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
Clicking the Asset Library tab, waiting, searching, all fail (stays perpetually on "loading ..."). An error appears eventually.

**Steps to reproduce:**
Open the asset library.

Note: browsing the URL that appears below, shows "page not found".

![image](https://user-images.githubusercontent.com/31222662/93550471-759e9280-f939-11ea-8cfe-d199a335f291.png)

**Comment by nathanfranke** [comment]
Can't reproduce on my Manjaro (3.2.3 stable)

![image](https://user-images.githubusercontent.com/14253836/93564225-f5832780-f94e-11ea-85ca-d7a1d43a09d8.png)

I also get 404 Not Found on https://godotengine.org/asset-library/api, I think it's because there is no endpoint at that exact location.

**Comment by Calinou** [comment]
@nathanfranke The URL is https://godotengine.org/asset-library/api/asset (`/asset` is always appended).

**Comment by nightblade9** [comment]
I'm not behind a proxy or double-stack as far as I know.

I tried again right now and it seems that it's working again. Hurray.
