### ISSUE TITLE
Scripts loaded from outside of res not marked as unsaved when modifying code

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#42154]
**Godot version:**

v3.2.3.stable

**OS/device including version:**

Windows

**Issue description:**

A script that is loaded from a folder other than `res://` is not marked as unsaved when you edit it in Godot Script Editor.
Although script history (ctrl+z) works
I expect it to get unsaved mark `(*)` in the Script Editor script list

**Steps to reproduce:**
1) Open a new Godot project
2) Open Script Editor (F3)
3) Open a script that is not in `res://` (with File-Open)
4) Change the script code in the editor
5) As you can see, the script is not marked as changed (no star `(*)` symbol at the end of the script name in Script Editor script list)

**Minimal reproduction project:**

**Comment by me2beats** [comment]
maybe related to https://github.com/godotengine/godot/issues/42153

**Comment by KoBeWi** [comment]
Seems fixed in 4.1 (and probably earlier)
