### ISSUE TITLE
Execution of exported project to LinuxX11 with encrypted GDScript fails.

### ISSUE THREAD

**Issue by Pawel82S** [godotengine/godot#42162]
**Godot version:**

v3.2.3.stable.official

**OS/device including version:**

Manjaro Linux - Nvidia GTX 960M - GLES3
Linux 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64 GNU/Linux

**Issue description:**

Project with encrypted script export failed to execute but at the same time when exported without encryption executed properly.
```
ERROR: open_and_parse: The MD5 sum of the decrypted file does not match the expected value. It could be that the file is corrupt, or that the provided decryption key is invalid.
   At: core/io/file_access_encrypted.cpp:97.
ERROR: load_byte_code: Condition "err" is true. Returned: err
   At: modules/gdscript/gdscript.cpp:772.
ERROR: load: Cannot load byte code from file 'res://Node.gde'.
   At: modules/gdscript/gdscript.cpp:2282.
ERROR: _load: Failed loading resource: res://Node.gde. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:279.
ERROR: poll: res://Node.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Node.gd
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Failed to load resource 'res://Node.tscn'.
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://Node.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:279.
ERROR: start: Failed loading scene: res://Node.tscn
   At: main/main.cpp:1944.
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2135.
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477.
```

**Steps to reproduce:**
1. Create new project
2. Create one scene of type "Node"
3. Attach to scene script with default template
4. Hit F5 and set this scene as main scene
5. In Export/Script set: Encrypted (with key)
6. Enter valid key: 839bbb335a89bef0299a04be366c014f47ec283ea89ccf710c944413dd92810d
7. Try to run exported project.

**Minimal reproduction project:**

[Export encrypted bug.zip](https://github.com/godotengine/godot/files/5244915/Export.encrypted.bug.zip)

**Comment by akien-mga** [comment]
Did you compile your own export template with that encryption key? https://docs.godotengine.org/en/stable/development/compiling/compiling_with_script_encryption_key.html

**Comment by Pawel82S** [comment]
I need a sticky note or some script to remember myself of compiling export templates with encryption key every time I have to export some project. Last time I did it was in v3.1.

Sorry for bothering you. My bad.
