### ISSUE TITLE
Exported ZIP contains duplicate files

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#42163]
**Godot version:**
3.2.3.stable.mono

**OS/device including version:**
Win10

**Issue description:**
I use filters to export my resources, like this:
![export2](https://user-images.githubusercontent.com/12966814/93588305-ca93e480-f9dd-11ea-96ba-76facd723546.png)

I exported it as zip, and found it contains duplicate `.import` files:
![export1](https://user-images.githubusercontent.com/12966814/93588564-2e1e1200-f9de-11ea-9312-b68b4c66bf5f.png)

**Steps to reproduce:**
**Minimal reproduction project:**
[export_bug.zip](https://github.com/godotengine/godot/files/5245084/export_bug.zip)

Note: I know I shouldn't export resources using filters, but in my actual project I want to export 200 out of more than 600 resources. It's not possible to select resources one by one.

**Comment by Dragoncraft89** [comment]
Seems like this is fixed in master and the 3.2 branch

**Comment by Calinou** [comment]
Closing per @Dragoncraft89's comment. Please comment if you can still reproduce this issue.
