### ISSUE TITLE
The test_move() function may not be behaving properly, when rotating

### ISSUE THREAD

**Issue by vesk4000** [godotengine/godot#42175]
**Godot version:**
Godot Engine v3.2.3.stable.official

**OS/device including version:**
Windows 10 Pro, Version 2004

**Issue description:**
In this demo, I've got this T shape and it can move around in an invisible grid as well as rotate 90 degrees clockwise. It should collide with these blue walls, and when simply moving - it does. But if I try to rotate next to a wall that is to the right of the T shape (when looking from its perspective by taking into account the rotation), the T shape kinda glitches out instead of just not moving or rotating at all like it is supposed to.
![rotation_test](https://user-images.githubusercontent.com/30286047/93635790-8fa0a980-f9fb-11ea-9e3e-19db5a5a0cca.gif)

Here's the script that's attached to the T shape:
![2020-09-18 20_32_44-Godot Engine - Rotation Collision Test - Level tscn](https://user-images.githubusercontent.com/30286047/93640904-093c9580-fa04-11ea-9f4c-b10e415eeed6.png)

**Minimal reproduction project:**
[Rotation Collision Test.zip](https://github.com/godotengine/godot/files/5247912/Rotation.Collision.Test.zip)

**Comment by madmiraal** [comment]
This is also fixed with #35945 and its 3.2 version #37498.

**Comment by vesk4000** [comment]
Yup just compiled your commit (#35945) and tested it with my demo project - it works! Thanks so much for the fix! Do you have an idea when the commit might find itself in the stable version of Godot, because I think this is a very important commit and I don't feel that the current master is stable enough for me to use?

**Comment by Calinou** [comment]
> Do you have an idea when the commit might find itself in the stable version of Godot, because I think this is a very important commit and I don't feel that the current master is stable enough for me to use?

We can't make any guarantees that it will be merged as-is.

**Comment by vesk4000** [comment]
> You can always compile the `3.2` branch from source and apply your own commits on top 🙂
@Calinou Yeah that is actually a good idea. I see that @madmiraal has made a 3.2 version of the PR, so I think I'll just compile that (now that I actually know how to compile Godot, which really ended up being easier than I expected).

> We can't make any guarantees that it will be merged as-is, since reduz disagrees with the implementation.
I haven't extensively looked at the implementation and from what I read it seems that it is a bit of a workaround until/if the physics engine is reworked. But the thing is, it is a massively important workaround in my opinion, given how basic of feature that is. Like I don't know how more people aren't having problems with this, but it's quite nonsensical (for the lack of a better word) how something as simple and basic as my demo didn't work. I really hope this gets fixed in stable as soon as possible, whether it is by #35945 or something else.

**Comment by vesk4000** [comment]
@Calinou By the way, I closed the issue, because it was fixed by #35945, but since you say that it is unlikely that that PR will be merged, should I reopen it until it is fixed in an official build, or should I keep it closed?

**Comment by pouleyKetchoupp** [comment]
Fixed by #42574, closing.
