### ISSUE TITLE
Some alternative modules

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#4217]
Hi!
I have two questions:
1- Why godot don't use Box2D, Liquid Fun, Chipmunk2D, bullet, and have his own physics engine?
2- Why godot don't use Angelscript. Is there an important feature in Gdscript that angelscript lacks. (Angel script c++ binding looks easier)
I need a good and clear reason to leave box2d and angelscript modules implementation for godot.

**Comment by neikeq** [comment]
You can always make such modules yourself. I once considered doing an AngelScript module as an alternative to dynamic typing, but there is not much demand for it (most of the people who complain about GDScript seem to prefer C#...).

**Comment by alabd14313** [comment]
I haven't good memories about Microsoft technologies. C# is a good language but there are better languages than it. Also C# differ with C# script.

**Comment by ret80** [comment]
How many programmers have many opinions about what a programming language is best used in Godot. Will not please everyone. Of course it would be better if it was in Godot python rather than what we have now. But just because historically let it yet remains. In the engine there are many other important things that sledovolo be improved.

**Comment by ret80** [comment]
By the way, C # was not the best solution, until recently. Since there were difficulties with the creation of games for mobile platforms (surcharge Xamarin). But now Xamarin became free, and C # is a good alternative in the future.

**Comment by paper-pauper** [comment]
I know the answer for question 2, but what's the answer for question 1? @reduz, anyone?

(not that I have any issues with Godot's physics)

**Comment by ret80** [comment]
@paper-pauper  The answer to question 1 is the same as to question 2.
I'm more interested in whether @alabd14313  was able to implement a third-party modules or abandoned this idea?

**Comment by paper-pauper** [comment]
@ret80 the answer can't be the same, since scripting languages come with their own VMs and garbage collectors which physics engines don't.

**Comment by akien-mga** [comment]
Closing as the discussion is stale, and issues written as a suggestion to replace big parts of the engine with arbitrary libraries are usually bound to be ignored/closed, as per the FAQ: http://docs.godotengine.org/en/latest/about/faq.html
