### ISSUE TITLE
Navigation bar in android is sometimes open and sometimes not.

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot#42182]
**Godot version:**

3.2.3

**OS/device including version:**

Android 10 and Android 8 , Gles2

**Issue description:**

I've seen this issue #41388 but wanted to open an issue because it's not about the calculation of the decoration on Android but about the navigation bar which is sometimes not hiding.

**Steps to reproduce:**
launch many times the game [https://play.google.com/store/apps/details?id=ch.disd.BlueToothPoker8](url)
Sorry I can't be more specific as this occur just sometimes. But when you press on open all old app and then reclick on the game the navigation bar is hiding it self.

**Minimal reproduction project:**

[https://play.google.com/store/apps/details?id=ch.disd.BlueToothPoker8](url)

**Comment by capnm** [comment]
I had such issues with the quick launch button in the Godot editor.
Try to stop & run again the app via Android UI.

**Comment by DisDoh** [comment]
It happens in Immersive mode.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/80574, which is a more up-to-date issue about the problem at hand.
