### ISSUE TITLE
Not able to print on console using  GD.Print("abc");

### ISSUE THREAD

**Issue by itsabhiaryan** [godotengine/godot#42197]
**Godot version:**
3.2.3.rc6.mono

**OS/device including version:**
OS : Mac
Language : C#
Graphics : GLES2

**Issue description:**
I am trying to print some value for debug purpose but unable to see on output space.

**Steps to reproduce:**
Create a scene and .cs script on that scene. Write Print statement in _Ready() method.
```
public override void _Ready()
 {
     GD.Print("abc");   
 }
```

Crosschecked setting to disable output :

<img width="683" alt="Screen Shot 2020-09-19 at 8 50 33 PM" src="https://user-images.githubusercontent.com/7019724/93670542-c210dc00-fab9-11ea-9a31-ad7c1337b16b.png">

**Comment by ondesic** [comment]
Just ran into this today.  I can confirm that 3.2.3 stable release has same problem.  It is making debug very hard.

**Comment by Calinou** [comment]
As a workaround, try running Godot from a terminal and look at the output there.

**Comment by neikeq** [comment]
Is this a bug introduced in 3.2.3 or could anyone reproduce in older versions?

**Comment by akien-mga** [comment]
I can't seem to reproduce the issue on 3.2.3-stable on Linux myself.

@ondesic What OS are you running?

**Comment by itsabhiaryan** [comment]
@neikeq Not able see any log on 3.2.2 version as well. Checked on mono variant.

**Comment by itsabhiaryan** [comment]
@akien-mga I am using macOS, checked this issue on both variant(normal & mono) of 3.2.3 stable release.

**Comment by akien-mga** [comment]
> I am using macOS, checked this issue on both variant(normal & mono) of 3.2.3 stable release.

So you mean that with both 3.2.2 and 3.2.3, you don't get any output from prints even with GDScript? E.g.:
```
func _ready():
    print("Hello from mac")
```

**Comment by itsabhiaryan** [comment]
Yes correct. For 3.2.2, I only check mono variant.
 
<img width="386" alt="Screen Shot 2020-09-22 at 8 06 14 PM" src="https://user-images.githubusercontent.com/7019724/93898463-ddc1ef80-fd10-11ea-8128-1220567a4edc.png">

**Comment by bruvzg** [comment]
Checked 3.2.3 stable on macOS, both Mono/C# and GDScript `print`s work in the editor `Output` tab and in terminal.

**Comment by itsabhiaryan** [comment]
Am I missing something?? because I am also checking on 3.2.3 version.  

This is the code that I used to print 
<img width="479" alt="Screen Shot 2020-09-22 at 8 34 15 PM" src="https://user-images.githubusercontent.com/7019724/93900482-0e0a8d80-fd13-11ea-9a0d-e447f5e0d0ce.png">

Output window
<img width="513" alt="Screen Shot 2020-09-22 at 8 33 32 PM" src="https://user-images.githubusercontent.com/7019724/93900565-2aa6c580-fd13-11ea-89c1-73f632f72766.png">

I can see my print statement in godot.log file
<img width="642" alt="Screen Shot 2020-09-22 at 8 32 00 PM" src="https://user-images.githubusercontent.com/7019724/93900650-47db9400-fd13-11ea-9bfa-46ec24c661da.png">

**Comment by bruvzg** [comment]
>`Connection Taken`

Firewall might be blocking connection between editor and running project or default debugger port (`6007`) is already used, try changing port in `Editor Settings` -> `Network` -> `Debug` -> `Remote Port` and check firewall settings.

<img width="757" alt="Screenshot 2020-09-22 at 17 55 16" src="https://user-images.githubusercontent.com/7645683/93901803-94b56f80-fcff-11ea-963a-36b3f95fe214.png">

**Comment by Zireael07** [comment]
Err, from the point of view of someone who doesn't know that much of C#, one of you is doing print() and the other GD.Print() - could that be the difference?

**Comment by itsabhiaryan** [comment]
I changed debugger port to 6009 and now I am able to see log on output window. Do we need separate port for language server and debug port ?
<img width="597" alt="Screen Shot 2020-09-22 at 8 51 05 PM" src="https://user-images.githubusercontent.com/7019724/93903531-63946980-fd16-11ea-9e34-db3742637aa8.png">

**Comment by bruvzg** [comment]
> Do we need separate port for language server and debug port ?

Most likely, yes.

**Comment by itsabhiaryan** [comment]
@bruvzg Thanks for finding the issue.

**Comment by ondesic** [comment]
I am on Windows and as the OP mentioned this is with C#.  In 3.2.2 stable the GD.Print() was fine.
