### ISSUE TITLE
Several issues with mac export

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#4219]
**Operating system or device:** Linux (exporting to mac)

**Issue description**:

1- My first attempt was just to try a default export. On the mac the game immediately crash when opening. I tired disabling the 64-bit option, and that seemed to solve the problem. (is 64-bit not supposed to work?)

2 - Next, the app icon only shows correctly when looking at a bigger size. The small icon seems totally messed up
![screen shot 2016-04-03 at 15 24 21](https://cloud.githubusercontent.com/assets/1642015/14232992/787bd696-f9b3-11e5-99ba-09bad879d5e8.png)

3 - finally being able to run the game I was shocked to see all the colors messed up. In my game(3d) i'm using HDR in the world environments, but the result is totally different from my main dev machine. Some levels are too dark, and some are so bright that I only see white on the screen :( Could this be a mac problem or a linux problem?

**Comment by neikeq** [comment]
Please, open one ticket per issue. It would also be great to have a sample project which reproduced 1- and 3-.

**Comment by nunodonato** [comment]
unfortunately I dont have a mac to prepare a sample project that has this result... I  just used one from a friend and tried my game for a few minutes

**Comment by nunodonato** [comment]
Just tried on my windows install and everything was ok[1]. So I guess it is a Mac issue.

[1] - got a godot splash even though its disabled, and an error saying pulseaudio was an invalid sound system. (still got sound, though)

**Comment by akien-mga** [comment]
Was this with the 2.0.1 or 2.0 binaries? If the former, it would be nice if you can try with 2.0 too as the buildsystem changed between the two releases, and we haven't got much feedback yet on the 2.0.1 binaries (especially on the Mac and iOS ones).

**Comment by nunodonato** [comment]
was with 2.0.1... but now I dont have access to a mac to test again :(

anyway, should it matter? the build system should only change the ... *build*.. the final binaries should be the same, right?

**Comment by akien-mga** [comment]
> anyway, should it matter? the build system should only change the ... build.. the final binaries should be the same, right?

Well different compilers produce different binaries. :)

**Comment by nunodonato** [comment]
Just went to windows and produced 64-bit mac binaries using 2.0. and 2.0.1

The binary produced by 2.0.1 crashes on the mac, while 2.0 runs

**Comment by nunodonato** [comment]
@bojidar-bg closed because

- it's too old
- I can't even test it to confirm if its still a problem
- like neikeq said, this issue is not an ideal one since it mentions 2 different problems

**Comment by haxpor** [comment]
Might consider re-opening this issue, I can confirm this still happen on `2.1.4` for icon, and only 64-bit selected to be able to export issue.

![screen shot 2017-12-15 at 5 49 32 pm](https://user-images.githubusercontent.com/673757/34036670-f19514ec-e1c0-11e7-9354-8b48e3de08ed.png)

You can download sample project [here](https://bitbucket.org/haxpor/godot-study-project).

Should we create a new issue here?
