### ISSUE TITLE
Build failure with MSYS2 when using SCons from MSYS2

### ISSUE THREAD

**Issue by zeroxoneafour** [godotengine/godot#42204]
**Godot version:**
`31d0f8ad8d5cf50a310ee7e8ada4dcdb4510690b` "3.2.3-stable"

**OS/device including version:**
Windows 10 1909, x64, Intel Graphics that don't support Vulkan but that's a [different issue](github.com/godotengine/godot/issues/41158), MSYS2 with Scons and GCC/G++ installed via it

**Issue description:**
Scons could not build Godot. It had an especially weird warning before compilation (command `scons target=release_debug use_mingw=yes p=windows bits=64 -j4`)-
```
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
```
which I think is more of a Linux thing. I don't know if it mattered or not, but I got this error not very far into compilation-
```
[  2%] build_res_file(["platform/windows/godot_res.windows.opt.tools.64.o"], ["platform/windows/godot_res.rc"])
[  4%] Compiling ==> main/tests/test_ordered_hash_map.cpp
[  4%] Compiling ==> main/tests/test_physics.cpp
[  4%] scons: *** [platform/windows/godot_res.windows.opt.tools.64.o] Error 1
Compiling ==> main/tests/test_physics_2d.cpp
scons: building terminated because of errors.
```

**Steps to reproduce:**
Clone Godot with `git clone www.github.com/godotengine/godot.git`
```
cd godot
git switch --detach 3.2.3-stable
scons target=release_debug use_mingw=yes p=windows bits=64 -j4
```
on Windows with MYSY2, MinGW, and Scons as a MSYS package, NOT a pypi package.

**Minimal reproduction project:**
https://github.com/godotengine/godot/tree/3.2.3-stable

**Comment by free-vbucks** [comment]
This is an issue with the MSYS2 SCons, most likely because MSYS has not updated their SCons package to 4.0.1. I built successfully with 4.0.1 SCons. I am keeping this issue open for reference. Maybe someone will care someday.

**Comment by akien-mga** [comment]
I think MSYS2's SCons package has been updated, and they now even package Godot. Can you try again?

**Comment by akien-mga** [comment]
No answer, closing.
