### ISSUE TITLE
HTML5 exports running on Android crash with generated `default_env.tres`

### ISSUE THREAD

**Issue by Ozzadar** [godotengine/godot#42208]
**Godot version:**
Confirmed on 3.2, 3.2.1, 3.2.2, .3.2.3 stables

**OS/device including version:**
Xiaomi Redmi Note 4(MIUI 11), a couple of other devices though im not sure which they were. Newer devices seem to last longer before it crashes

**Issue description:**
All projects (including empty projects), see terrible performance or crash outright when running HTML5 builds within a browser on Android with WEBGL Context Lost errors.

Removing the generated `default_env.tres` file from the project resolves the issue.

No issues on any other OS though I haven't tested on iOS.

This issue kept me up all night :(

**Steps to reproduce:**

1 - Create an empty project
2 - Create an empty scene and save it
3 - set this scene as your project's main scene
4 - Export HTML5 build
5 - Host it somewhere
6 - Try to run it on android

**Minimal reproduction project:**
[New Game Project321.zip](https://github.com/godotengine/godot/files/5251445/New.Game.Project321.zip)

**Comment by Calinou** [comment]
It seems you're using the GLES3 renderer. We no longer support the GLES3/WebGL 2.0 renderer on HTML5 for now. Switch to the GLES2 renderer in the top-right corner of the editor (or in the Project Settings).

**Comment by Ozzadar** [comment]
thanks. 

i figured it wouldnt get fixed but having an issue archived for it can possibly save time for other people with the workaround.
