### ISSUE TITLE
ERROR: Signal 'settings_changed' is already connected to given method '_tileset_settings_changed' in that object.

### ISSUE THREAD

**Issue by skar** [godotengine/godot#42207]
**Godot version:**
3.2.3 Stable Mono

**Issue description:**
I just updated version of engine from 3.2.2 to 3.2.3, open the project, open the scene with the TileMap and see that in console:
```
ERROR: Signal 'settings_changed' is already connected to given method '_tileset_settings_changed' in that object.
   At: core/object.cpp:1515
```

**Steps to reproduce:**
1. Open scene with a TileMap
2. Check 'Output'

**Comment by Calinou** [comment]
@skar Can you reproduce this in a newly created project?

**Comment by skar** [comment]
@Calinou thank you for fast reply.

No, I can't, but I get some additional information.
I get this error only if I select TileMap and...
I have two scenes with TileMap, one is empty and one with a tiles.
If I open scene with empty TileMap first, I didn't get this error, but if I open scene with tiles I get:
```
ERROR: tile_get_tile_mode: Condition "!tile_map.has(p_id)" is true. Returned: SINGLE_TILE
   At: scene/resources/tile_set.cpp:480
ERROR: tile_get_tile_mode: Condition "!tile_map.has(p_id)" is true. Returned: SINGLE_TILE
   At: scene/resources/tile_set.cpp:480
```
Then I get error with signals on every other TileMaps.

**Comment by WolfgangSenff** [comment]
I believe this happens on the non-Mono version as well; I've definitely seen it happen in my 3.2.3.stable version, which is not Mono.

**Comment by Error7Studios** [comment]
I was able to reproduce this in 3.2.3 stable and 3.2.4 beta 2.

The error only shows when the Tilemap scene is open in a scene tab (but isn't the focused tab) and you switch to it.
If the Tilemap scene does not already have a tab open, no error will show when opening the scene by double-clicking the Tilemap's .tscn file.
However, once you switch to another tab, then switch back to it, you get the error.

```
 Signal 'settings_changed' is already connected to given method '_tileset_settings_changed' in that object.
Switch Scene Tab
```

[TilemapSignalBug - 1.zip](https://github.com/godotengine/godot/files/5578895/TilemapSignalBug.-.1.zip)

**Comment by CitrusWire** [comment]
3.2.3 - Windows 7

I'm getting this in my project too:
```
 scene/resources/tile_set.cpp:480 - Condition "!tile_map.has(p_id)" is true. Returned: SINGLE_TILE
```

Seems to be different from Error7Studios explanation.

* Open attached
* Go into Terrain and open the Background scene
* Click on One of the tilemaps.

You'll now get the error any time you switch between the tilemaps.

[SINGLE_TILEBug.zip](https://github.com/godotengine/godot/files/5758359/SINGLE_TILEBug.zip)

**Comment by Szesan** [comment]
Getting the same error today. Using v3.2.3-stable_mono_win64 on windows 10.
