### ISSUE TITLE
Reopen all scenes that were open last run

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#4220]
**Operating system or device:**

**Issue description** (what happened, and what was expected):
When opening a project it would be nice if the editor re-opened all the scenes that were open previously.  It only opens the $main_scene.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
@akien-mga This request is included in #3333, but IMO it's better as a separated issue.

**Comment by AlexHolly** [comment]
#2385

**Comment by neikeq** [comment]
Closing it then, as it's a duplicate of #2385
