### ISSUE TITLE
Closing bbcode tags with append_bbcode on RichTextLabel doesn't work

### ISSUE THREAD

**Issue by Lucas-Romao** [godotengine/godot#42216]
**Godot version:** 3.2.2.stable.mono

**OS/device including version:** Windows 10

**Issue description:** appending a closing tag by itself, after appending an opening tag doesn't recognize the closing tag, and just appends it as if it were regular text.

![code](https://user-images.githubusercontent.com/48300973/93715377-49ecf980-fb3f-11ea-890c-1224d5286087.png)
![ezgif-5-c5f8234cbda5](https://user-images.githubusercontent.com/48300973/93715329-0a261200-fb3f-11ea-9100-f8dae8d5581f.gif)

**Steps to reproduce:**
- call append_bbcode() to append a string with an opening tag
- call append_bbcode() again with a closing tag 
- the closing tag appears as text and doesn't actually closes the tag

**Minimal reproduction project:**
[RichTextLabelAppendError.zip](https://github.com/godotengine/godot/files/5252020/RichTextLabelAppendError.zip)

**Comment by Calinou** [comment]
This is a design decision in RichTextLabel to make `append_bbcode` faster. If you need this behavior (which is slower), append the `bbcode` property instead:

```gdscript
extends Node2D

onready var rich_text = $RichTextLabel

func _ready():
    rich_text.bbcode += "[shake] first append"
    rich_text.bbcode ++ " [/shake] second append"
```

**Comment by Lucas-Romao** [comment]
Okay, thank you!

> This is a design decision in RichTextLabel to make `append_bbcode()` faster. If you need this behavior (which is slower), append the `bbcode_text` property instead:
> 
> ```gdscript
> extends Node2D
> 
> onready var rich_text = $RichTextLabel
> 
> func _ready():
>     rich_text.bbcode_text += "[shake] first append"
>     rich_text.bbcode_text ++ " [/shake] second append"
> ```
> 
> I wouldn't recommend relying on this behavior for large RichTextLabels though, especially if you update them often.
