### ISSUE TITLE
c# export returns empty executable

### ISSUE THREAD

**Issue by awalone995** [godotengine/godot#42218]
found similar issues only from 2018 or earlier :^)

**Godot version:**
3.2.3 stable mono

**OS/device including version:**
win7 desktop

**Issue description:**
exporting the project returns an empty (0KB) executable, even though everything else exports fine 
turning on "embed pck" gives an error right on export, saying something's wrong with the export settings

log (ftw i'm afraid it's in russian)
[msbuild_log.txt](https://github.com/godotengine/godot/files/5252482/msbuild_log.txt)

UPD:: 
![image](https://user-images.githubusercontent.com/26692947/93720771-da552980-fb93-11ea-8aed-f22a3f35af00.png)
![image](https://user-images.githubusercontent.com/26692947/93721644-4175dc80-fb9a-11ea-89ee-b361275e6a1b.png)

**Comment by awalone995** [comment]
calinou please notice me

**Comment by Calinou** [comment]
> exporting the project returns an empty (0KB) executable, even though everything else exports fine
> turning on "embed pck" gives an error right on export, saying something's wrong with the export settings

Do you get an empty executable *only* when Embed Pck is enabled, or do you also get an empty executable when Embed Pck is disabled?

**Comment by awalone995** [comment]
> > exporting the project returns an empty (0KB) executable, even though everything else exports fine
> > turning on "embed pck" gives an error right on export, saying something's wrong with the export settings
> 
> Do you get an empty executable _only_ when Embed Pck is enabled, or do you also get an empty executable when Embed Pck is disabled?

always

**Comment by awalone995** [comment]
i beg of thee

**Comment by awalone995** [comment]
UPD:: same for 3.2.2 and even 3.2.1 on an empty project, tried all the export//mono export settings so it's probably an issue regarding mono itself

**Comment by awalone995** [comment]
reainstalled VS, completely on my side indeed : ^ (
