### ISSUE TITLE
Git merge workflow

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4221]
GitHub just introduced a new feature for PR mergers: https://github.com/blog/2141-squash-your-commits

It is now possible to squash all commits from a PR and merge them directly in master, without generating a merge commit. The other alternative is to keep doing like before, i.e. don't change the PR commits and create a merge commit.

What workflow should we use? Should we keep the old behaviour, use the new one, or both depending on the context?

**Comment by akien-mga** [comment]
I've haven't given it much thought yet, but I'd propose at least:
- keep the old behaviour (merge commit) for PRs with more than one commit, and where it's useful to keep them separate in the history
- use the new behaviour for PRs with many fixup commits for only one functional change, to avoid having to annoy PR makers every time so that they rebase their branch
- for PRs with only one commit, I don't have a strong opinion. WDYT?

**Comment by neikeq** [comment]
I agree with the two points above. For PRs with only one commit I would use the new behaviour.

**Comment by akien-mga** [comment]
> For PRs with only one commit I would use the new behaviour.

Yeah that's what I leaning towards too. Unless there's some really interesting discussion in the PR topic that would be worth keeping directly linked in the git log maybe.

**Comment by slapin** [comment]
I'd prefer old behavior even with single-commit PRs, as this makes tracking
merges easier.
Or you will have to edit comment adding what you have pulled, whch is
additional work

**Comment by akien-mga** [comment]
In the end we settled on keeping the old behaviour and not using that new feature, so closing.
