### ISSUE TITLE
NavigationServer3D

### ISSUE THREAD

**Issue by ShalokShalom** [godotengine/godot#42228]
https://github.com/reduz/godot/commit/eaae4b6408361eb34363adcb22a08046f43147f4

This commit shows that quite an effort got put into making the naming streamlined, so I am a but confused why the newly merged NavigationServer again breaks with the new standard. 

https://docs.godotengine.org/en/latest/classes/class_navigationserver.html

**Comment by akien-mga** [comment]
The class reference on https://docs.godotengine.org/en/latest/ has not been synced in months (intentionally, as it will break a lot of the documentation and it would be a waste of time to rewrite the documentation for the 4.0 API now when it's not final).

This class was also renamed with a 3D suffix. https://github.com/godotengine/godot/blob/master/servers/navigation_server_3d.h#L48

**Comment by ShalokShalom** [comment]
Ah. NavigationServer2D in the API docs is named Navigation2DServer, by the way. Is this also already fixed?

![Screenshot_2020-09-21-20-07-45-74_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/6344099/93804552-c4547100-fc46-11ea-9ee7-ee37a0d4163a.jpg)

**Comment by akien-mga** [comment]
https://github.com/godotengine/godot/blob/master/servers/navigation_server_2d.h#L43
