### ISSUE TITLE
generate_normals() and  add_to_smooth_group() not working on imported .dae mesh - smooth normals

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#42233]
**Godot version:**
3.2.1 onwards

**OS/device including version:**

GTX 1080 GLES3.0

**Issue description:**

I imported .dae files from Maya into Godot, but the normals of the mesh are not smooth.
I tried creating new vertices using SurfaceTool, but it's still the same.
I need to work with this file type from Maya, because there are animations and blendshapes that are used.
![image](https://user-images.githubusercontent.com/37254287/93826639-10e77e80-fc3e-11ea-8642-107bdd7366a0.png)

**Steps to reproduce:**
- check attached zip

**Minimal reproduction project:**
- check the .zip ""issue smooth normals.zip"
- open scene.tscn
- tool mode is active. just close and open .tscn to view updates.
[issue smooth normals.zip](https://github.com/godotengine/godot/files/5258399/issue.smooth.normals.zip)

**Comment by Calinou** [comment]
> 3.2.1 onwards

Is this a regression from 3.2.1 onwards, or did it never work in the first place?

**Comment by shafnaz** [comment]
it never worked in the first place

**Comment by Klowner** [comment]
In 4.0-beta16 the imported .dae has smooth normals as well as the generated mesh
![image](https://user-images.githubusercontent.com/9374/215799443-035a8e08-e5f8-47b5-b7ed-49a44824b8fd.png)
With a few small changes to the SurfaceTool calls:
```
	st.set_smooth_group(0)
	for face in mdt.get_face_count():
		for i in range(3):
			var vert_index = mdt.get_face_vertex(face, i)
			st.set_uv(mdt.get_vertex_uv(vert_index))
			st.add_vertex(mdt.get_vertex(vert_index))
```

Looks fixed to me!
