### ISSUE TITLE
Export should create parent directories

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#42231]
**Godot version:**

3.2.2.stable.custom_build.bc8eea3e9

**OS/device including version:**

Linux 5.8.8-arch1-1

**Issue description:**

I wanted to get a clean export of my project for all OS's, so I wiped out my build directory and re-exported.
The export failed because the target subdirectories no longer existed.
It seems pretty normal to want to wipe out a build directory and rebuild, so I think Godot should create any necessary directories during export.

**Steps to reproduce:**

1. Set up your exports to gitignore'd folders like `build/{linux,windows,mac}`
2. Run `git clean -xdf` (Note: this will wipe out all untracked/ignored files!)
3. Press "Export All" in the export dialog
4. Exports fail due to nonexistant folders

**Minimal reproduction project:**

**Comment by Calinou** [comment]
As a workaround, you can create empty folders and add an empty `.gitignore` file inside that you commit. This way, the folder will be committed to version control.
