### ISSUE TITLE
exact colour matching in shaders fails with when using floats

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#42237]
**Godot version:**
3.2.2 stable

**OS/device including version:**
linux mint

**Issue description:**
In the image you can see from a paint picker that the yellow is 255,255,0. Or 1.0,1.0,1.0 in Godot colours.

The cyan is 0,192,192. Or 0, 0.75, 0.75 in Godot colours.
![image](https://user-images.githubusercontent.com/12863685/93833064-7a33b580-fc6f-11ea-9d3f-c46953762385.png)

However, when doing a colour replacement shader, the code will match the yellow fine, however the cyan has to be a fuzzy match, as shown below. I presume this is a floating point issue, but given the values I would expect it not to fail.

Apologies if I'm misinterpreting how shader colour comparison should be working.

```
shader_type canvas_item;

void fragment() {
	COLOR = texture(TEXTURE, UV);

        //this fails if use exact 0.75 so have to do the following. The colour is exactly 0.75 though
	if(COLOR.r==1.0 && COLOR.b>0.75 && COLOR.b<0.753 && COLOR.g>0.75 && COLOR.g<0.753) {
		COLOR.r=0.75;
		COLOR.g=0.0;
		COLOR.b=0.0;
	}
   
        //this works fine as it is 1.0
	if(COLOR.r==1.0 && COLOR.g==1.0 && COLOR.b==0.0) {
		COLOR.r=d;
		COLOR.g=0.0;
		COLOR.b=0.0;
	}
}
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Your not misunderstanding shader color comparisons, you are actually misunderstanding how floating point numbers work in general. Floating point numbers don't store exact representations. So floating point comparison using ``==`` is not guaranteed to be accurate. 

You have to realize that the GPU does a lot of operations on the float when converting it into a texture and reading from the shader, so there is no guarantee that 0.75 is exactly 0.75 or 1.0 is exactly 1.0. It is pure chance that 1.0 is working for you. If you switch to another computer or update your driver's, it may no longer work. 

In shaders you should always use a fuzzy comparison.

**Comment by chucklepie** [comment]
Thanks, that's why I said is it a floating point issue :)

This seems bad, how are you supposed to do an exact perfect colour replacement? what if I want exactly this colour and not a small fractional variation and how are you supposed to know what range to have, i.e. this would be fine with values in the range 0-255, seems overly vague when using 0..1 as a range.

**Comment by akien-mga** [comment]
> This seems bad, how are you supposed to do an exact perfect colour replacement? what if I want exactly this colour and not a small fractional variation and how are you supposed to know what range to create, do you do a variance of 0.05, 0.1, will it work on another computer?, i.e. this would be fine with values in the range 0-255, seems overly vague when using 0..1 as a range.

Well you can't do this with computers :)

If you want exact comparison, use integers. Otherwise you have to use epsilons for comparison to account for precision errors. An epsilon (small value bigger than the precision errors, typically 10e-5 or 10e-4) shouldn't make a perceivable difference for Color values.

**Comment by chucklepie** [comment]
On, fair enough. In the olden days it wasn't hard to choose to use rgb as a
range of 0 to 255 😉

I'll rethink how I do it.

**Comment by anthonyjb** [comment]
I'm using this method to colour match in shaders currently:

```c
bool colorMatch(vec3 c1, vec3 c2, float maxDiff) {
    return (
        abs(c1.r - c2.r) < maxDiff
        || abs(c1.b - c2.b) < maxDiff
        || abs(c1.b - c2.b) < maxDiff
    );
}

void fragment() {
    vec3 color = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0).rgb;
    if (colorMatch(color.rgb, someColor.rgb, 0.01)) {
        COLOR = vec4(1f, 0f, 0f, 1f);
    } else {
        COLOR = vec4(0f, 0f, 0f, 0f);
    }
}
```

**Comment by jakefriend-dev** [comment]
FWIW if anyone's finding this through Google, the above code didn't work for me, but a tweak did. Changed colorMatch's 'or' to 'and' operator. Mine's no a screen shader either, for what that's worth.

```
bool colorMatch(vec4 c1, vec4 c2, float maxDiff) {
    return (
        abs(c1.r - c2.r) < maxDiff
        && abs(c1.g - c2.g) < maxDiff
        && abs(c1.b - c2.b) < maxDiff
    );
}

void fragment() {
	
	vec4 curr_color = texture(TEXTURE,UV); // Get current color of pixel
	float variance = 0.0001;
	
	if (curr_color.a == 1.0 && colorMatch(curr_color, exit_col_1, variance)) { curr_color = enter_col_1; }
	[repeat for howevermany colours you're swapping]
	
	COLOR = curr_color;
}
```
