### ISSUE TITLE
Missing texture / material on glTF (glb) import.

### ISSUE THREAD

**Issue by y0nd0** [godotengine/godot#42235]
**Godot version:**
3.2.2 Standard (GDScript) 64 bit

**OS/device including version:**
Windows 10 - GLES3

**Issue description:**
Some glb-files work great, some don't.
I tested a default glb-file from Windows 10 build-in 3D-Viewer. The bee.

**Steps to reproduce:**
Create a new project and import the glb-file. See that there is no material / texture imported. Only the mesh and animations, etc.
I expected a full support of all material features and textures like albedo, normal, emission, etc.
(No errors on console.)

**Demo / Files:**

Windows 10 3D-Viewer:
![window-10-3d-viewer](https://user-images.githubusercontent.com/68586847/93828759-4efb9700-fc6c-11ea-8d12-99070363400f.jpg)

Godot after import:
![godot](https://user-images.githubusercontent.com/68586847/93828998-d9dc9180-fc6c-11ea-9fd3-b5998ec74495.jpg)

Source model file (glb):
[Download Bee.zip](https://github.com/godotengine/godot/files/5258501/Bee.zip)

**Comment by Calinou** [comment]
cc @fire

**Comment by y0nd0** [comment]
A working example in the [glTF sample models repo](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Lantern/glTF-Binary) Or this duck: 
[Download Duck.zip](https://github.com/godotengine/godot/files/5258677/Duck.zip)

**Comment by fire** [comment]
Uses a non core gltf extension:

```
"extensions": {
        "KHR_materials_pbrSpecularGlossiness": {
          "diffuseTexture": {
            "index": 0
          },
          "specularGlossinessTexture": {
            "index": 1
          }
        }
      }
```

There's already a pr for it. https://github.com/godotengine/godot/pull/38438

I'll post a converted scene in a bit.

**Comment by fire** [comment]
Something is wrong. Not sure what it is yet.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/93833488-9c0c4880-fc2d-11ea-83e6-fb85f90c383c.png)

You can see it clearly in the blender view.

**Comment by y0nd0** [comment]
Thanks for investigating. It's looks better. This means that only "Principled BSDF (GGX, Burley)" is supported.
Your commit to Godot will convert this in the future, right? I tried to convert it in Blender. But export in Blender is a gamble. ... It seems there is an issue with wrong scales. Anyway... thanks.

**Comment by y0nd0** [comment]
I close this issue, because the glb-file material (SpecularGlossiness) is not supported in Godot which only supports MetallicRoughness. It's ok. But Godot should display a message about it and / or convert it.
