### ISSUE TITLE
Mono C# class Basis.cs has RotationQuat internal

### ISSUE THREAD

**Issue by ricardoalcantara** [godotengine/godot#42239]
**Godot version:**

Godot Engine v3.2.3.stable.mono.official

**OS/device including version:**

Windows, GLES3

**Issue description:**

On TPS Demo it's used `orientation.basis.get_rotation_quat()` and on C# the same method `RotationQuat` is defined as `internal`. shouldn't it be public?

**Steps to reproduce:**
https://github.com/godotengine/godot/blob/3.2/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs#L210

**Minimal reproduction project:**

**Comment by aaronfranke** [comment]
Yes, makes sense. This is a useful method and it's exposed in GDScript, so we may as well expose it in C# too. This is a very minor change (one line) so we could probably just solve this issue in the same PR as #42241.

**Comment by ricardoalcantara** [comment]
@aaronfranke In the end the Access Modifiers was the only issue! I will explain better on the other issue.
