### ISSUE TITLE
Error while importing Norwegian translation - Invalid locale: no

### ISSUE THREAD

**Issue by OverloadedOrama** [godotengine/godot#42236]
**Godot version:**
3.2.3.stable (happened in 3.2.2.stable too, didn't test previous versions or master)

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
While importing a Norwegian translation .po file, and using `no_NO` as the locale code, it does not work properly and the Debugger shows the error `set_locale: Invalid locale: no.`. According to this documentation page, `no_NO` is a valid locale code. https://docs.godotengine.org/en/stable/tutorials/i18n/locales.html

Using `nb_NO` as the locale code seem to be working though.

**Steps to reproduce:**
Create a valid .po file, use the `no_NO` locale code and load it into a Godot project, and then run it. The file I used in the below project contains just this:
```
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Language-Team: Norwegian\n"
"Language: no_NO\n"
```

**Minimal reproduction project:**
[Norwegian Translation.zip](https://github.com/godotengine/godot/files/5258604/Norwegian.Translation.zip)

This issue also happens in [Pixelorama](https://github.com/Orama-Interactive/Pixelorama).

**Comment by akien-mga** [comment]
I think that documentation page is wrong. Locale codes for Norwegian are `nb` (Norwegian Bokmål) and `nn` (Norwegian Nynorsk). They're two official and different languages, so `no` would not let you know if its Bokmål or Nynorsk.
