### ISSUE TITLE
Visible Collision Shape won't draw new cast_to of raycast2d

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4224]
Hi. I have a raycast2d node and enabling Visible Collision Shape draws the raycast2d as an arrow as  spectated. But if I set the cast_to property to a new one on runtime, the arrow remains the same position, even though the cast_to is different (and I'm 100% sure it is). Now, it does draw it correctly when I set the cast_to on _ready() and _fixed_update but I'm setting it on other methos that is being call in _fixed_update, weird....

**Comment by neikeq** [comment]
I can confirm this in the current master branch.

**Comment by neikeq** [comment]
This change would fix this particular issue:

``` diff
@@ -33,7 +33,7 @@
 void RayCast2D::set_cast_to(const Vector2& p_point) {
 
 	cast_to=p_point;
-	if (is_inside_tree() && get_tree()->is_editor_hint())
+	if (is_inside_tree() && (get_tree()->is_editor_hint() || get_tree()->is_debugging_collisions_hint()))
 		update();
 
 }
```

However, the same problem applies to Shape2D resources.

**Comment by neikeq** [comment]
I opened an issue for a similar bug with CollisionPolygon2D: #4260
