### ISSUE TITLE
Godot 4: Scenes Don't Run (Condition "!process_map->has(p_pid)" is true)

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#42251]
**Godot version:**

Godot Engine v4.0.dev.calinou.160ad23e5 (Originally spotted in)
Godot Engine v4.0.dev.custom_build.339b64697 (Last checked build, as of 1st december 2020)

**OS/device including version:**

Windows 10
Intel Pentium G3258 (2c/2t)@3.2GHz with 16gb@1333mhz memory
Probably not related but...
Nvidia Quadro K2000, Driver: 441.28

**Issue description:**

When I try to run a scene (F6 or the button) Godot just spikes to nearly 100% CPU Usage, no window appears and all log files created are empty, while what was expected is a Window, with a splash screen and the scene appearing when it loaded.

**Steps to reproduce:**
Run a Scene, Doesn't matter if it's 2d or 3d, full or totally empty, new or old project..

If the scene is killed it returns this error in the output
- platform/windows/os_windows.cpp:485 - Condition "!process_map->has(p_pid)" is true. Returning: FAILED

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/5262826/Test.zip)
The MRP doesn't help a lot, as it doesn't rly matter, however something i did notice is, When a Window node is created and the camera is attached to it.. the renderer works on both 3d and 2d so that isn't the issue... and also the window has no impact on CPU usage (well almost none)

**Comment by felaugmar** [comment]
I have a similar behavior when running the project:

- The CPU spikes;
- Takes a while, but the window appears;
- When quitting the application, the same message outputs: **platform\windows\os_windows.cpp:485 - Condition "!process_map->has(p_pid)" is true. Returning: FAILED**.

**Comment by Exomode** [comment]
I haven't noticed any critical points related to this error yet. It simply notifies by assert that there was an attempt to terminate an already killed process. So far, I just replaced the line `ERR_FAIL_COND_V(!process_map->has(p_pid), FAILED);` with `if (!process_map->has(p_pid)) { return OK; }` so that it doesn't hurt my eyes every time.

**Comment by mrjustaguy** [comment]
Update (8e514bb):
Window now Does appear almost instantly now (used to not show up at all, CPU still spikes and the window is Blank white (regardless of anything in the scene or not, and well, no splash screen so..))

**Comment by mrjustaguy** [comment]
Update (tested on same branch as above):
Managed to Get it to Run, by setting the main scene to run in project settings, quitting the editor and pressing run in Project Selector, Instantly Ran, just fine, no CPU spike
@felaugmar Could you please try it and see if that solves the CPU spike for you too?

**Comment by mrjustaguy** [comment]
#47076 fixed the CPU spike and now runs as expected. Error msg provided is Not related to the issue, and is a Separate issue, that doesn't seem to have any effect on performance.

**Comment by mojoyup** [comment]
Im getting this now with the Steam build of 3.4.4 exporting to android via debug. I get a black screen that hangs sometimes, but when I reload it and reinstall the debug app on my developer phone, it works half the time just fine. Should I change something that I haven't likely seen yet since this is closed already? Thanks if you can help :)

**Comment by Calinou** [comment]
> Im getting this now with the Steam build of 3.4.4 exporting to android via debug. I get a black screen that hangs sometimes, but when I reload it and reinstall the debug app on my developer phone, it works half the time just fine. Should I change something that I haven't likely seen yet since this is closed already? Thanks if you can help :)

I can see one instance of `process_map` in an Android issue here: https://github.com/godotengine/godot/issues/38278

However, this error message only means that the child process couldn't be killed by Godot. It's not related to the export specifically (and is *not* emitted by the exported project).
