### ISSUE TITLE
Support HTTPClient in HTML5

### ISSUE THREAD

**Issue by DarkDimius** [godotengine/godot#4226]
Thought It's clearly impossible to support arbitrary tcp\upd in html5 platform, it would be great to support simple HTTP requests.

**Comment by williamd1k0** [comment]
Simple HTTP requests would be very useful on the HTML5 platform :thinking:

**Comment by nhydock** [comment]
Raw TCP might not be supported, but it would be nice to expose WebSocket support for all platforms, so then HTML5 does have something.  HTTP requests could just wrap the fetch api now that most browsers support it and it's easy to work with.
