### ISSUE TITLE
Renaming scene instance changes exposed nodepath values

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#42272]
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

Windows 10 x64

**Issue description:**

As the title says, when renaming a scene instance inside another scene and that instance has a script with exposed nodepaths attached, the nodepaths are wrongly 'auto-corrected'. 
They shouldn't be touched from outside when not user-modified as override!

Related issue: https://github.com/godotengine/godot/issues/35226

**Steps to reproduce:**
Open attached project, inside Main scene rename nested and see exposed nodepath change.

**Minimal reproduction project:**
[InstanceNodePathProblem.zip](https://github.com/godotengine/godot/files/5268049/InstanceNodePathProblem.zip)

**Comment by mbrlabs** [comment]
That was fixed in #42314.
