### ISSUE TITLE
Improve code completion

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#4227]
I think it is better if you type "action", everything with "action" in it, including functions with "action" in the middle like `set_action` can be brought up.
Second, it is better if most commonly used functions can be placed at the top.
Do you guys agree with that?

See here: https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp
`if (completion_strings[i].begins_with(s)) {...`

**Comment by neikeq** [comment]
I agree. I swear there was already an issue about this, but I can't find it :(

**Comment by neikeq** [comment]
Did #5196 add this?

**Comment by buckle2000** [comment]
Yes, thanks.
