### ISSUE TITLE
MeshDataTool.create_from_surface crashes without any error information

### ISSUE THREAD

**Issue by felipefcm** [godotengine/godot#42273]
**Godot version:**
(3.2.3-stable) 31d0f8ad8d5cf50a310ee7e8ada4dcdb4510690b

**OS/device including version:**
Arch Linux, NVIDIA GTX 1080 (nvidia drivers), GLES3

**Issue description:**
When calling `create_from_surface`, the program crashes without information shown in console. The crash happens before the function returns an `Error`.

**Steps to reproduce:**

Create a `MeshInstance` node. Attach this script and the mesh will be created as expected.
```
extends MeshInstance

export (int) var sizeX = 4;
export (int) var sizeZ = 8;
export (float) var cellSize = 8;

func _ready():

	var vertices := generateGrid();
	var indices := generateIndices();

	var array = [];
	array.resize(Mesh.ARRAY_MAX);
	array[Mesh.ARRAY_VERTEX] = vertices;
	array[Mesh.ARRAY_INDEX] = indices;

	var arrayMesh = ArrayMesh.new();
	arrayMesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, array);

	mesh = arrayMesh;

func generateGrid() -> PoolVector3Array:

	var vertices := PoolVector3Array();

	for z in range(sizeZ):
		for x in range(sizeX):
			vertices.push_back(Vector3(x * cellSize, 0, -z * cellSize));

	return vertices;

func generateIndices() -> PoolIntArray:

	var indices := PoolIntArray();
	indices.resize(sizeX * sizeZ * 2 * 3);
	
	var topToBottom := true;

	for z in range(sizeZ):
		for x in range(sizeX):
			var BL = x + sizeX * z;
			var BR = BL + 1;
			var TL = BL + sizeX;
			var TR = TL + 1;

			#left triangle
			indices.push_back(BL);
			indices.push_back(TL);

			if(topToBottom):
				indices.push_back(BR);
			else:
				indices.push_back(TR);

			#right triangle
			indices.push_back(TR);
			indices.push_back(BR);

			if(topToBottom):
				indices.push_back(TL);
			else:
				indices.push_back(BL);

			topToBottom = !topToBottom;

		topToBottom = !topToBottom;

	return indices;
```

Now I need to update this mesh. So when I add this, it crashes:
```
func _process(_delta):
	var mdt = MeshDataTool.new();
	mdt.create_from_surface(mesh, 0);
```
It's not something related to it being in `_process`, apparently. As I also tested only running that part when a button is pressed and the problem still happens.

**Comment by Calinou** [comment]
I can confirm this on 3.2.3.

**Minimal reproduction project:** [mesh_data_tool_crash.zip](https://github.com/godotengine/godot/files/5268458/mesh_data_tool_crash.zip)

(Please include a ZIP file next time, so we can immediately import the project and try to reproduce the issue.)
