### ISSUE TITLE
Renaming material in dock gives invalid reference

### ISSUE THREAD

**Issue by fire** [godotengine/godot#42278]
**Godot version:**
3.2.3.stable from itchio

**OS/device including version:**
win10.
Not graphics related

**Issue description:**

Renaming material in Godot Engine dock gives invalid reference if you follow these series of steps.

**Steps to reproduce:**

1. Create a new Godot Engine project.
1. Download https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox/glTF-Binary/Fox.glb
1. Open the glb as a scene
1. Open the fox MeshInstance (Not strictly necessary, kept for historical reasons)
1. Open the ArrayMesh (Not strictly necessary, kept for historical reasons)
1. Open the Material (Not strictly necessary, kept for historical reasons)
1. Go to the dock and rename the material. The blue is the dock.
![image](https://user-images.githubusercontent.com/32321/94047240-ac840680-fd86-11ea-9311-0e92a7081721.png)

1. Save the scene.
1. Close all scenes.
1. Open the tscn saved fox.
1. There will be a dependency error.
1. Review the posted project

![image](https://user-images.githubusercontent.com/32321/94045645-95441980-fd84-11ea-8f85-dca983089bf5.png)

**Minimal reproduction project:**
Follow the steps to reproduce the error.

This is the error'd state.

[Dependency Bug Project.zip](https://github.com/godotengine/godot/files/5269762/Dependency.Bug.Project.zip)

**Comment by fire** [comment]
This may be a documentation bug related to ArrayMesh's materials versus Overwritten materials.

**Comment by fire** [comment]
Analysis seems to be:

The original flow is:
* tscn -> glb -> material.

Anything that's after the glb is incorrect.

One approach is to do:
* tscn -> material -> glb -> material

So the material is overriding the material in the glb.

Another is to use the tscn slot for materials, it has the same ref graph.

**Comment by capnm** [comment]
Currently to get rid of old material and let it regenerated from the glb file i have
to close the editor and manually remove the *material file.
Your comments sound to me like: It's already broken, let's break it completely;)

**Comment by fire** [comment]
By the time we get to the manually remove the *material file, it's already wrong. I want to avoid that.

Any suggestions?

**Comment by capnm** [comment]
> Any suggestions?

Really fix the "(un)Keep on Reimport" option, keep track on the material file name in the .import file or forbid Dock to change the material file name ... honestly, I can't read the completely uncommented source code`¯\_(-_-)_/¯`

P.S.: My issue #26775 will soon celebrate its two-year birthday :D

**Comment by fire** [comment]
Reduz mentioned the concept of a virtual folder. I don't know what this means yet.

**Comment by fire** [comment]
This issue is resolved by the new importer in 4.0 and we try not to break backwards compatibility in 3.x.
