### ISSUE TITLE
Exported NodePath reference invalid if referencing node is moved up/down the node hierarchy

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#42277]
**Godot versions:**
3.2.2, 3.2.3 and master 215fa6e85b8a22e75081190293460f720291f6a5

**OS/device including version:**
Windows 10

**Issue description:**
Basically what the title says. Exported NodePaths won't get updated if i move them up/down the node hirachy in the inspector. However if i move the referenced Node (in the example below that would be `Path1`) the path gets updated automatically.

I found some open NodePath related issues, but nothing exactly like this (#35226, #34872).
The same issue exists in the master branch, but i can't provide a MRP because of a bug where the node path gets set to null if saving the scene.

**Steps to reproduce:**
Export a NodePath via a script like so:
```
extends Node

export var my_path: NodePath

func _ready():
	print(my_path)
	print(get_node(my_path))
```
attach the script to a node (here called `Receiver`) and set the NodePath (here `Path1`) like so:
![ok](https://user-images.githubusercontent.com/8750135/94041170-28ec0900-fdca-11ea-803d-1df2056e649b.png)

Now move `Receiver` into `Container` and the NodePath will be invalid:
![broken](https://user-images.githubusercontent.com/8750135/94041417-7ff1de00-fdca-11ea-937e-2384b7cb290c.png)

**Minimal reproduction project:**
[NodePathBug.zip](https://github.com/godotengine/godot/files/5269587/NodePathBug.zip)

**Comment by HEAVYPOLY** [comment]
I think I'm running into a related issue, when using remove / add child it seems the original reference to the object is lost.
```
onready var Node = get_tree().get_root().find_node("Node")
Parent.remove_child(Node)
OtherParent.add_child(Node)```

now Node = null

**Comment by mbrlabs** [comment]
@HEAVYPOLY That's probably not related. 
This issue is about exported node paths (see my code snippet above) not beeing updated correctly when moved in the scene tree of the editor. I'm not quite sure what the problem is you are having but if you found a bug you should probably open 
 a seperate issue for that 😉
