### ISSUE TITLE
RayCast2D gives wrong collisions if properties are changed in code immediately before

### ISSUE THREAD

**Issue by cosmicgenius** [godotengine/godot#42279]
**Godot version:**
v3.2.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Changing a property of RayCast2D (e.g. cast_to) in code then immediately trying to get collisions (e.g. get_collider()) causes the ray to use the previous, unupdated value to calculate collisions.

**Steps to reproduce:**

1. Create a new 2D scene
2. Add a RayCast2D at (100, 100) and select "Enabled" and "Collide With > Areas"
3. Add two Area2D's at (150, 100) and (100, 150) and give them CollisionShape2D's with RectangleShape2D
4. Add a GDScript script to Node2D and paste in the following, 
```
extends Node2D

onready var ray_cast = $RayCast2D

func _physics_process(delta: float) -> void:
	if Input.is_action_just_pressed("ui_accept"):	
		ray_cast.cast_to = Vector2(50, 0)
		
		var hit_object = ray_cast.get_collider()
		if hit_object:
			print("hit an object at ", hit_object.position)
```
5. Select "Debug > Visible Collision Shapes"
6. Play and press enter twice.

The raycast changes direction as intended, but the output is wrong.

Expected output:
```
hit an object at (150, 100)
hit an object at (150, 100)
```

Actual output:
```
hit an object at (100, 150)
hit an object at (150, 100)
```

**Minimal reproduction project:**
Implementation of the aforementioned steps:
[RayCast2D_Minimal_Reproduction.zip](https://github.com/godotengine/godot/files/5269882/RayCast2D_Minimal_Reproduction.zip)

**Comment by Xrayez** [comment]
There's a special method for this purpose: [`force_raycast_update()`](https://docs.godotengine.org/en/3.2/classes/class_raycast2d.html#class-raycast2d-method-force-raycast-update), I think this should resolve your issue.

**Comment by cosmicgenius** [comment]
Yep adding `ray_cast.force_raycast_update()` works. Thanks!
