### ISSUE TITLE
Generic6DOFJoint 'precision' attribute error with Bullet

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#42285]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Windows 10 60-bit

**Issue description:**
if you set the 'precision' attribute to anything but 1, when you run the project the error "get: Condition "!p_rid.is_valid()" is true. Returned: __null" and "generic_6dof_joint_set_precision: Condition "!joint" is true."

**Steps to reproduce:**
Create Generic6DOFJoint node and set the "precision" attribute to be greater than 1.

**Comment by Calinou** [comment]
@addmix Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by akien-mga** [comment]
MRP: [6DOF Precision error.zip](https://github.com/godotengine/godot/files/5676043/6DOF.Precision.error.zip)

I can confirm the issue with Bullet. No error with GodotPhysics.

```
ERROR: get: Condition "!p_rid.is_valid()" is true. Returned: __null
   At: ./core/rid.h:149.
ERROR: generic_6dof_joint_set_precision: Condition "!joint" is true.
   At: modules/bullet/bullet_physics_server.cpp:1476.
```

When closing the scene, this warning is raised too:
```
WARNING: assert_no_constraints: A body with a joints is destroyed. Please check the implementation in order to destroy the joint before the body.
   At: modules/bullet/rigid_body_bullet.cpp:466.
```
