### ISSUE TITLE
Using arrows in tileset editor with collision tool selected will not cycle through all subtiles in autotiles.

### ISSUE THREAD

**Issue by kurinoku** [godotengine/godot#42290]
**Godot version:**
3.2.3

**OS/device including version:**

Windows 10 x64

**Issue description:**

When using the arrows (previous and next coordinates) in the tileset editor, if the tool selected is collision, it won't cycle through all of the subtiles of autotiles. Given the region that belongs to that autotile, it will only go subtiles up to width - 1 and height - 1.

**Steps to reproduce:**
Have a tileset, make an autotile, select the collision tool, and use the arrows in the editor.
![rB3JbMV0PP](https://user-images.githubusercontent.com/31811692/94093573-e93a1700-fdf3-11ea-8eaf-4c6174e6084e.gif)

**Minimal reproduction project:**

**Comment by kurinoku** [comment]
It's the first time I contribute ever to a project. I believe this fixes it.
#42313

**Comment by akien-mga** [comment]
Fixed by #42313.
