### ISSUE TITLE
TextureFrame insufficiency?

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#4229]
**Operating system or device:**
Windows 7

**Issue description** (what happened, and what was expected):
TextureFrame no set_vframes set_hframes set_frame and other methods such as Sprite

**Comment by akien-mga** [comment]
http://docs.godotengine.org/en/latest/classes/class_textureframe.html

> Control frame that simply draws an assigned texture. It can stretch or not. It’s a simple way to just show an image in a UI.

So it's not insufficient, it's designed to be simple. I guess you're mislead by the *Frame* part of TextureFrame. In this context it just means that it's a frame (as in painting, so a rectangular shaped thing to put stuff in it).
Is there any reason why you can't use Sprite it you want to use vframes and hframes?

**Comment by neikeq** [comment]
Was this a misunderstanding? It looks like you are looking for _Sprite_. If that's not the case, what are these methods needed for in _TextureFrame_?

**Comment by akien-mga** [comment]
Closing as it's likely a misunderstanding of what TextureFrame is meant to be used for. Feel free to further comment though if you think there is really something to change, we can reopen the issue if it's valid.
