### ISSUE TITLE
some resource files are not exported.

### ISSUE THREAD

**Issue by eaglecat** [godotengine/godot#4230]
Filesystem dock does not show *.bme files(and also other user defined format)

when exporting, 'export all files' option does not export that files

**Comment by akien-mga** [comment]
Link to more debugging info: http://godotengine.org/qa/2575/some-resource-files-are-not-exported

Could you provide such a .bme file to test?

**Comment by eaglecat** [comment]
here it is. It's text file
[a7.zip](https://github.com/godotengine/godot/files/205572/a7.zip)

**Comment by reduz** [comment]
this is a feature, not a bug. Add your non-godot extensions here:
![image](https://cloud.githubusercontent.com/assets/6265307/16321543/cff9d2ba-3973-11e6-9c5c-4e3275f71bfe.png)
