### ISSUE TITLE
GDScript: variables that begin with an underscore ("_") do not count as being used, gives UNUSED_PRIVATE_CLASS_VARIABLE warning

### ISSUE THREAD

**Issue by Paavs-Git** [godotengine/godot#42318]
**Godot version:**
4.0 master - 72aaf81518253e25f28b3a23b5d3509e1264a5ad

**Issue description:**
If a variable's name starts with an underscore it will not count towards being used (from the tests I've done) and thus produce a warning, UNUSED_PRIVATE_CLASS_VARIABLE, even if it is used.

**Steps to reproduce:**
```
var _test_var: int = 2
var another_var: int = 5

func test() -> void:
	another_var = _test_var
```

![1](https://user-images.githubusercontent.com/68266227/94195088-7a6bc500-feaa-11ea-8a5d-0ae3ea55ac8c.PNG)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/5e726d8d2025f1bc52299894230d94ef5972cea4. This doesn't occur on 3.2.3.

**Comment by mhilbrunner** [comment]
This should be fixed by https://github.com/godotengine/godot/pull/52329 :)
