### ISSUE TITLE
Nintendo Switch Pro controller not detected on Linux

### ISSUE THREAD

**Issue by clarfonthey** [godotengine/godot#42324]
**Godot version:** 3.2.2

**OS/device including version:** Arch Linux, Linux 5.8.10 with hid-nintendo module

**Issue description:** The latest version of the Linux kernel (5.8) does not have driver support for the Nintendo Switch Pro controller, but a driver has been accepted into 5.10 and should be released later this year. However, with this driver, even though the controller appears to be properly detected with other programs, it is completely invisible to Godot. This means that there are no signals being fired for the controller being connected, and events are not fired for its inputs even if using "All Devices" bindings.

**Steps to reproduce:**

1. Install the hid-nintendo kernel module using [dkms-hid-nintendo](https://github.com/nicman23/dkms-hid-nintendo) and reboot the kernel. Available on the AUR via [hid-nintendo-dkms](https://aur.archlinux.org/packages/hid-nintendo-dkms/).
2. Install and start [joycond](https://github.com/DanielOgorchock/joycond) to pair controllers. More information is available in the docs for joycond on specifically how to pair controllers, but in my case I connected a Switch Pro controller via USB and pressed both the ZL and ZR buttons.
3. The controller should work in all cases except Steam, but if you want to test with a Steam game, you will need to use firejail as mentioned on [this ArchWiki page](https://wiki.archlinux.org/index.php/Gamepad#Nintendo_Switch_Pro_Controller_and_Joy-Cons).
4. Try running the given project and moving around with the controller. It's programmed to work with any keyboard or controller movements.

**Minimal reproduction project:** [ControllerTest.zip](https://github.com/godotengine/godot/files/5280098/ControllerTest.zip)

**Comment by Calinou** [comment]
Can you test this with the [joypads demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/joypads) in Godot 3.2.3? 3.2.3 has had significant changes to controller mapping handling using the new SDL format.

**Comment by clarfonthey** [comment]
I didn't realise that there were such big changes in 3.2.3! I just tested and everything works, so, I'll close this out. :)
