### ISSUE TITLE
Sprite3D with Alpha Cut set to Discard Loses Transparency

### ISSUE THREAD

**Issue by tragicmanner** [godotengine/godot#42326]
**Godot version:** 3.2.3

**OS/device including version:** Windows 10, NVIDIA GeForce GTX 1050 Ti, GLES3

**Issue description:**
Setting Alpha Cut to Discard on a Sprite3D that has a texture with transparency causes transparency to no longer behave correctly.

**Steps to reproduce:**
1.  Create a Sprite3D
2.  Set the Sprite3D's texture to a texture that has a transparent background
3.  Set the Alpha Cut on the Sprite3D to dicard

![image](https://user-images.githubusercontent.com/5327369/94224183-f962fc80-feae-11ea-82af-5637ad0eed77.png)
![image](https://user-images.githubusercontent.com/5327369/94224217-0a137280-feaf-11ea-89c6-79da5d0808f5.png)

**Minimal reproduction project:** [sprite_3d_test.zip](https://github.com/godotengine/godot/files/5280475/sprite_3d_test.zip)

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by akien-mga** [comment]
Fixed by #42380.
