### ISSUE TITLE
Why so bad perfomance at Godot TPS demo?

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot#42331]
**Godot version:**
3.2.3

**OS/device including version:**
GPU: Radeon RX 480 8GB
CPU: Intel Xeon (unknown)
Backend: GLES3

**Issue description:**
Why i have only 10 fps when i launch godot TPS demo with medium settings?
The scene isn't that complicated...

**Comment by Calinou** [comment]
Please report issues specific to the TPS demo on [its repository](https://github.com/godotengine/tps-demo), not here. That said, keep in mind that AMD's OpenGL Windows drivers offer worse performance than all competiting hardware and OSes (especially compared to NVIDIA).

The TPS demo's level is a single mesh, which prevents any frustum culling opportunities. Once the level is split into several meshes, it should be much faster to render, especially once https://github.com/godotengine/godot/pull/41123 is merged.
