### ISSUE TITLE
Alloca.h not found with VS Code

### ISSUE THREAD

**Issue by Rdna123** [godotengine/godot#42330]
**Godot version:**

3.2.3

**OS/device including version:**

**Issue description:**
When using vs code to look through code states "alloca.h not found"

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
> OS/device including version:

> Steps to reproduce:

These are not option. There's nothing in this issue for us to work with.

**Comment by bruvzg** [comment]
For VSCode IntelliSense to get correct build flags for the file (and search for correct includes), you should build Godot for the specific platform and have `compile_commands.json` file generated and set full path to it in the `c_cpp_properties.json` VSCode config. (see: https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference).

**Comment by Rdna123** [comment]
Thank you

**Comment by yeeing** [comment]
Should replace all, `type *d=(*type)alloca(sizeof(type)*n)` go to `type d[sizeof(type)*n)` and gradually eliminate `#include<alloca.h>`

**Comment by kleonc** [comment]
Sorry, missclicked I guess. :upside_down_face:
