### ISSUE TITLE
GDScript: variable arrays are shared if initialized to same value

### ISSUE THREAD

**Issue by Paavs-Git** [godotengine/godot#42335]
**Godot version:**
4.0 master - 72aaf81518253e25f28b3a23b5d3509e1264a5ad

**Issue description:**
If initialized to the same value, arrays end up shared, unlike #20436 this is not limited to singletons or exported variables, it happens in any normal script.

**Steps to reproduce:**
```
extends Node2D
var arr1: Array = []
var arr2: Array = []

func _ready() -> void:
	print(arr1, " ", arr2)
	arr1.append(1)
	arr2.append(2)
	print(arr1, " ", arr2)
```

Output:
```
[] []
[1, 2] [1, 2]

```

The bug also happens if both are initialized to the same non-null value.
It does not happen if initialized to different values.

**Comment by ThakeeNathees** [comment]
@vnen what do you think about #41983 ?
