### ISSUE TITLE
Drag-Drop and some other Editor features

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#4233]
Here are drag-drop and some other useful features:
[https://www.youtube.com/watch?v=I0g-t0nZ-qE](https://www.youtube.com/watch?v=I0g-t0nZ-qE)
[https://www.youtube.com/watch?v=8U9Ojc8Babc](https://www.youtube.com/watch?v=8U9Ojc8Babc)
[https://www.youtube.com/watch?v=yeD8lVYwAWQ](https://www.youtube.com/watch?v=yeD8lVYwAWQ)

**Comment by akien-mga** [comment]
Yeah I've been asking for "some other Editor features" myself, but somehow nobody seems to want to implement them...

**Comment by alabd14313** [comment]
There is another feature that is very useful (Implemented in superpower game engine):
https://github.com/godotengine/godot/issues/2751

**Comment by alabd14313** [comment]
Someones request Electron UI, but in my tests in superpower and some other engines, the performance in electron is low and May be in some big scenes causes lag.

**Comment by punto-** [comment]
have we ever considered a theme for the editor that doesn't look exactly
like all other engines? I can't tell them apart :p

**Comment by toger5** [comment]
Do you want sth like that ?


![colortestforui](https://cloud.githubusercontent.com/assets/16718859/14403793/27f6d5a2-fe65-11e5-974a-b71da3111ff3.png)


I had that Idea reading your post.
But I think the themes usually are designeed to be as usable as possible. And a grey color lets you focus on your viewport. The dock size for properties is the best compromis between many options and enough space... So there is not really much you should change to make it look special.

But I stil wanted to look how a colored engine UI would look like.
And I like it but I'm not sure if I could work with it ;)

**Comment by akien-mga** [comment]
Hehe, did we get bought by Microsoft too? :D

**Comment by neikeq** [comment]
- IINW, dragging and dropping images into the canvas item editor is not yet implemented. How would it actually work? There are different nodes you may want to create from an image.
- I like the idea of dragging docks. It wouldn't really need to change the way docks are positioned right now.
- I am not sure "some other Editor features" were already implemented.
In any case this issue could/should be split in two separated issues.

**Comment by bojidar-bg** [comment]
Any status on this issue? Given that d&d was mostly done in 2.1, I guess that's closeable and splittable.

**Comment by mhilbrunner** [comment]
@akien-mga Can be closed.
