### ISSUE TITLE
Window transparency not clearing viewport

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#42344]
Godot 3.2.3 (persists in 3,2,2; 3.2.1 has other problems)
Windows 10

Using the code below in a basic [Project.zip](https://github.com/godotengine/godot/files/5284878/TEMP.zip), the transparent window does not refresh when window transparency is enabled.

```gdscript
var windowTransparent = true

func _ready():
	get_viewport().render_target_clear_mode = Viewport.CLEAR_MODE_ALWAYS
	get_viewport().render_target_update_mode = Viewport.UPDATE_ALWAYS
	get_tree().get_root().set_transparent_background(windowTransparent)

func _input(event):
	if event.is_echo(): return 
	if event is InputEventKey == false: return
	if event.pressed == false: return
	
	windowTransparent = not windowTransparent
	get_tree().get_root().set_transparent_background(windowTransparent)
```

Example image produced while rendering only a transparent white square to the screen and moving the window around.
![Capture](https://user-images.githubusercontent.com/13801432/94307311-3269a280-ff7d-11ea-862b-5e521076007b.PNG)

Issue exists in the same form in 3.2.2
3.2.1 does not have this issue, but that version does not allow enabling the window border with the transparency

**Comment by bruvzg** [comment]
Can't reproduce, moving and resizing works fine for me, Windows 10, AMD FirePro D300 GPU.

Do you have any remote access or screen recording software running or something else that can affect OS compositor work?

**Comment by rokasv** [comment]
No remote access or screen recording active at any time.

I'm on `OpenGL ES 2.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE`
Tried running it both on the dedicated and integrated cards to the same result.

I think the issue not appearing in 3.2.1 is a good indication an engine change caused this while moving into 3.2.2
Also, trying to take a screenshot using the Windows Snipping Tool successfully clears the application viewport just before the snip

**Comment by bruvzg** [comment]
3.2.1 was using different, much slower transparency method, see: #38629

**Comment by rokasv** [comment]
I have solved the problem.

The problem solution procedure is as follows:
```
Step 1: Update Windows
```
Thank you for your patience, time and diligence investigating this.
