### ISSUE TITLE
Vulkan/Godot does not start on Ubuntu 20.04 using X11 (works with Wayland)

### ISSUE THREAD

**Issue by Timothy-Pulliam** [godotengine/godot#42348]
**Godot version:**
`Godot Engine v4.0.dev.custom_build.fea72f2a7`

**OS/device including version:**

```
timothy@Orion ~> cat /etc/*release
...
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
...
timothy@Orion ~> uname -a
Linux Orion 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

GPU info
![image](https://user-images.githubusercontent.com/12704531/94326277-f3cdeb00-ff70-11ea-80f9-4257a8551266.png)

**Issue description:**
Starting Godot from a terminal I get the following error:

```
timothy@Orion:~/Desktop/Godot 4/godot/bin$ ./godot.linuxbsd.tools.64 
Godot Engine v4.0.dev.custom_build.fea72f2a7 - https://godotengine.org
INTEL-MESA: warning: Haswell Vulkan support is incomplete
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x6e00008
  Serial number of failed request:  105
  Current serial number in output stream:  111
```

**Steps to reproduce:**
1) Clone and build the latest master branch
```
git clone git@github.com:godotengine/godot.git
cd godot
scons -j4 target=linuxbsd
```
2) Install Ubuntu 20.04 Nvidia drivers
`sudo apt-get install nvidia-driver-450`

```
timothy@Orion ~> apt show nvidia-driver-450
Package: nvidia-driver-450
Version: 450.66-0ubuntu0.20.04.1
Priority: optional
Section: restricted/libs
Source: nvidia-graphics-drivers-450
Origin: Ubuntu
...
Description: NVIDIA driver metapackage
 This metapackage depends on the NVIDIA binary driver and on all of its libraries,
 to provide hardware acceleration for OpenGL/GLX/EGL/GLES/Vulkan
 applications on either X11 or on Wayland.
```
Verify using X11 and then try to start Godot.
```
timothy@Orion ~> echo $XDG_SESSION_TYPE
x11
```

**Solution**
I was able to get Vulkan/Godot to work by instead installing and using Wayland instead. 
https://askubuntu.com/a/1258280

1) Install Wayland `sudo apt install gnome-session-wayland`
2) Open `/etc/gdm3/custom.conf` and ensure `WaylandEnable=false` is commented.
3) Open `/usr/lib/udev/rules.d/61-gdm.rules` and comment all lines.
4) Execute `sudo systemctl restart gdm3` (may need to reboot entirely)
5) Click on the cogwheel and select GNOME or Ubuntu on Wayland.
6) Execute `echo $XDG_SESSION_TYPE` in order to confirm you are running Wayland (output should be `wayland`).

From what I understand, this is an issue with X11? Although I'm not really an expert.

**Comment by Calinou** [comment]
You need to force Godot to run on the dedicated GPU, as your integrated GPU doesn't fully support Vulkan.

**Comment by trommlbomml** [comment]
It would also be a great addition to detect when mandatory validation layers are not available and that they should be donwloaded, that blocked me from using vulkan some time.

**Comment by bruvzg** [comment]
> It would also be a great addition to detect when mandatory validation layers

Non of validation layers are mandatory, it will print errors (probably should be changed to warnings or even `print_verbose`), but it should work fine without any.

**Comment by chon-panic** [comment]
Sorry for my ignorance, but would you be able to give me general directions for how to force Godot to use my dedicated gpu? Is there a flag I need to pass when starting it?

**Comment by Calinou** [comment]
@chon-panic You can change the PRIME GPU in the NVIDIA Control Panel, but this requires you to log out and back in. Once you do this, the dedicated GPU will be used for *everything*, which decreases battery life significantly.

**Comment by chon-panic** [comment]
@Calinou I was just looking at PRIME settings on Arch wiki. I think that is what I will have to do. Fortunately I am on a Desktop, so battery life is not a concern. Thank you for helping me.

**Comment by Calinou** [comment]
@chon-panic If you're on a desktop system, you're not using Optimus in this case :slightly_smiling_face: 

If you have several displays and some of them are connected to the motherboard's video outputs, they will use the IGP instead of the dedicated graphics card.

**Comment by chon-panic** [comment]
@Calinou I have one monitor plugged into my GPU via HDMI, and one monitor plugged into the motherboard via VGA.

**Comment by Calinou** [comment]
@chon-panic In this case, if you start Godot while the currently focused window is on the monitor connected to the dedicated GPU, it should use the dedicated GPU. At least, in theory…

**Comment by bruvzg** [comment]
> I have one monitor plugged into my GPU via HDMI, and one monitor plugged into the motherboard via VGA.

Is there any reason for this strange setup? Using IGP on desktop doesn't make much sense.

**Comment by Calinou** [comment]
@bruvzg It can be useful if you need to use more monitors than your dedicated GPU supports. That said, any modern graphics card supports 3 monitors (if not 4) already.

**Comment by bruvzg** [comment]
> It can be useful if you need to use more monitors than your dedicated GPU supports.

Typical GTX-970 should have at least 4 ports, including DVI-I which can be converted to VGA with the passive adapter/cable.

**Comment by chon-panic** [comment]
@bruvzg I have an old hand me down monitor and not VGA to DVI converters. 

I tried unplugging my secondary VGA monitor entirely, rebooting and starting Godot that way, but I still see the same issue. Granted, my CPU is a bit older.

`Model name:                      Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz`

**Comment by chon-panic** [comment]
I have found a temporary work around. I enabled Wayland, however since Wayland doesn't work with nvidia GPUs I just plugged both of my monitors into my motherboard and use onboard graphics. I know this is dumb, but I plan on upgrading my CPU/GPU at some point anyways. I will try an AMD GPU in the future and see if that helps.

For what it's worth, my desktop is Windows 10/Ubuntu dual boot, and I did not run into these issues compiling and running Godot 4 for Windows 10 with my specs.

**Comment by trommlbomml** [comment]
> > It would also be a great addition to detect when mandatory validation layers
> 
> Non of validation layers are mandatory, it will print errors (probably should be changed to warnings or even `print_verbose`), but it should work fine without any.

It did not work, without the validation layers I had black screens. When I have installed them it worked very well. I tested even before running a vulcan game and it works properly, godot not. Only after adding the validation layers it worked.

**Comment by akien-mga** [comment]
@trommlbomml Most likely whatever process you used to install the validation layers also installed Vulkan drivers. Validation layers have no impact on whether Vulkan works or not, they're debugging tools.

**Comment by bfloch** [comment]
Sorry, I think I have the same issue with an NVIDIA optimus setup on a laptop while the integrated GPU is being used and crashes.

Despite the intuition on this thread in my case the problem is really that the current state of the vulkan implementation has a hard-coded physical device:
https://github.com/godotengine/godot/blob/master/drivers/vulkan/vulkan_context.cpp#L383

This should be selectable in the command line, or via an envvar but for the time being this PR unblocks me and might do the same for other devs:

https://github.com/godotengine/godot/pull/46070

**Comment by Snub0** [comment]
I am having a similar issue on Linux laptop, but strangely, it ONLY runs on my AMD 7 5800H, or 'AMD Renoir'. It completely refuses to run on my gtx 1650 since it's vulkan drivers are apparently not supported. I am running Pop-OS if it helps.

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
