### ISSUE TITLE
Implement sharing/saving of editor colorschemes

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#4235]
Considering the huge amount of PRs by @Paulb23 about coloring the script editor, it would be nice if it is possible to share the colorschemes as well. This would allow for people with experience in design and colors to make the work of programmers more pleasurable to the eye, and would allow the porting of well-known themes, such as "Base64 dark/light" etc.

**Comment by neikeq** [comment]
IMO the best way to do it would be to allow exporting and importing editor settings in general, but allowing to select the constants to import and export.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/1656.

**Comment by bojidar-bg** [comment]
Closing, since the issue @Calinou linked asks for the same.
