### ISSUE TITLE
Heavy Performance Degradation after updating Godot to version 3.2.3 on MacOS Catalina

### ISSUE THREAD

**Issue by SamToorchi** [godotengine/godot#42357]
**Godot version: 3.2.3**

**OS/device including version: MacOS Catalina (10.15.6)**

**Issue description:**
Heavy Performance Degradation after updating Godot to version 3.2.3.
By the same project, without any changes there is a very Heavy Performance Degradation after the update. The Editor/script editor is unusable, because it is very slow.
I use a Nvidia Graphic card with 2GB memory and 16GB RAM and i7 Processor. 

**Minimal reproduction project:**
update Godot from 3.2.2 to 3.2.3

**Comment by Calinou** [comment]
> MacOS Mojave (10.15.6)

Mojave is 10.14, Catalina is 10.15.

**Comment by WolfgangSenff** [comment]
I have had multiple projects go through the same upgrade process without running into this issue.

**Comment by SamToorchi** [comment]
I will add my project to this issue, today.

**Comment by SamToorchi** [comment]
I tried to open the same project with another laptop (Lenovo T480s with i5, without extern graphic card, 16GB RAM) and Linux ElementaryOS as operation. I hadn't any problem with Godot. I think this is only a MacOS problem. 
On Mac I can open the project in editor, but after about 30 seconds the GPU goes to run with maximum power and overloaded. The CPU and RAM continue to work under normal load (about 20%). But after overloading the GPU nothing works more on my laptop until I change the window, e.g. I start another program and change the active application. After changing the application again to the Godot, the same problem starts again.

**Comment by Calinou** [comment]
@SamToorchi Try increasing **Low Processor Mode Sleep Usec** to 33000 in the Editor Settings. Also, in 3D, you can click the **Perspective** button in the top left corner and enable **Half Resolution** to decrease the load on the GPU.

**Comment by SamToorchi** [comment]
Thank you for your solution. This setting solves my problem on macOS
