### ISSUE TITLE
Godot 3.2.3 C# project load failed in Rider

### ISSUE THREAD

**Issue by wmigor** [godotengine/godot#42350]
**Godot version:**
 3.2.3 stable

**OS/device including version:**
 Linux Mint 19.3

**Issue description:**
Rider can`t load project created with Godot 3.2.3:

`Project 'Test' load failed`
`[MSB4236] The SDK 'Microsoft.NET.Sdk' specified could not be found.`
`/home/user/.nuget/packages/godot.net.sdk/3.2.3/Sdk/Sdk.props at (31:11)`

However it works In Godot 3.2.2

**Steps to reproduce:**
- Create new Godot project
- Create C# solution (Project -> Tools -> Mono -> Create C# project)
- Open solution in Rider 2020.2

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/5286363/Test.zip)

**Comment by Duroxxigar** [comment]
Do you have .Net Core installed?

**Comment by neikeq** [comment]
Installing the .NET Core SDK could be the solution. You may need to change the MSBuild Rider uses as described here: https://stackoverflow.com/a/55573377. Mine was working well with .NET Core's MSBuild but I tried Mono's too and it had no issues, so I'm not sure what could have been wrong in your case. Could you show us what `Use MSBuild version:` was set to?

**Comment by wmigor** [comment]
![изображение](https://user-images.githubusercontent.com/28404760/95383519-f971ec00-08f3-11eb-8aec-df99c06ddb32.png)

**Comment by wmigor** [comment]
I installed mono from https://www.mono-project.com/download/stable/

**Comment by neikeq** [comment]
Do you get the same error with a normal C# project (not Godot)? Try creating an empty project from Rider targeting netstandard or netcoreapp and see if you get the same error.

**Comment by wmigor** [comment]
![изображение](https://user-images.githubusercontent.com/28404760/95673993-f4dc5a80-0bb5-11eb-8f68-700a2366c0e3.png)

.Net Core not installed (

**Comment by wmigor** [comment]
Rider got it working after installing dotnet-sdk-3.1 from https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#1804-.
But how work build in Godot without dotnet-sdk?
