### ISSUE TITLE
It's impossible to use singletons from tool script

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4236]
**Operating system or device:**
Ubuntu, Godot 2.01 

**Issue description** (what happened, and what was expected):
When you define a script that have tool keyword on the top, and you use in this script any singleton it wont compile because of  an error:  (where "Global" is my singleton)
`
SCRIPT ERROR: GDScript::reload: Compile Error: Identifier not found: Global
   At: res://Gameplay/Levels/BaseLevel.gd:151.
ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules/gdscript/gd_script.cpp:1894.
`
You won't be able to use singleton script with `get_node("/root/Signleton")` either.

**Steps to reproduce:**
1. Define a "Global" singleton scene with a script
2. Create another scene with a script in a tool mode, use "Global" singleton somewhere in the script.
3. Restart Godot (needed for tool scripts to compile )
4. Open scene with tool script
5. Observe error in console, tool mode for your script is not working.

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
@kubecz3k ~ is the singleton in `tool` mode too?

**Comment by kubecz3k** [comment]
@bojidar-bg the error is the same regardless if the singleton is in tool mode or not (tried both).

**Comment by reduz** [comment]
i don't think singletons are loaded in editor mode, this is intended since singletons can also be scenes.
maybe you can do what you are intending to do in a different way?

**Comment by bojidar-bg** [comment]
Plugins would come in handy in this case...

**Comment by kubecz3k** [comment]
@reduz Well in general I have a lot of 'helper' functions defined in singletons/globals. Those are the functions which I'm using in a daily basics and it's quite an issue for me... It would be ok for me if my singletons should be a tools as well... Maybe I should convert them to plugin as @bojidar-bg suggested but I'm not familiar with plugins api yet so I'm not sure if this is the way. In next week I will have time to explore all those fancy features that 2.1 will provide :)

**Comment by vnen** [comment]
I'm not sure if plugins can talk to each other. A way to make a set of plugins with common data would be an interesting feature.

I don't think this is a "bug" though, it simply wasn't designed this way.

**Comment by kubecz3k** [comment]
Well the idea that difference tool keyword from plugins for me, is the possibility for every scene to have some small code that runs in editor, usually linked to getters/setters methods. Currently this is impossible because those scenes simply wont compile.

**Comment by neikeq** [comment]
Example project from #5763:

> [SingletonCompileError.zip](https://github.com/godotengine/godot/files/368194/SingletonCompileError.zip)
Open this test project, the error appears in the console.

**Comment by Zylann** [comment]
If your helper functions don't modify the state of the singleton, you can make your functions static and do this in the script where the singleton is used:
```gdscript
const Groups = preload("groups.gd") # HOTFIX tool scripts cannot compile if they use singletons
```
However if the script also uses another game-related singleton, this is becoming a problem.

**Comment by reduz** [comment]
Maybe we could add a flag "tool" to singletons (besides global) to get this to work (load them if the flag is present). If anyone wants to do this, please feel free to do it.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by Geaxle** [comment]
I'm having the same issue. Hope someone manages to make the change :)

**Comment by chanon** [comment]
I was trying to use a utility function in my singleton in tool mode and ran into this issue too.

**Comment by bojidar-bg** [comment]
I guess we should inject tool-mode singletons too in `main.cpp` :smiley:

**Comment by kerskuchen** [comment]
It would definitely be useful to use singletons in tool mode to avoid cluttering a lot of scripts that are game objects as well as tools with preloads.

**Comment by Shadowblitz16** [comment]
this doesn't look like it was added in 3.1

**Comment by xsellier** [comment]
Hey,

Sorry for the necrobump, but I think sharing this workaround might help few of you.

Loading a singleton that way in a `tool` script will compile.
```
onready var MySingleton = get_node("/root/MySingleton");
```

**Comment by stickgrinder** [comment]
This is also relevant to what I mentioned before (having a proper singleton at plugin level): https://www.reddit.com/r/godot/comments/134lk0p/comment/jiggacp/?utm_source=share&utm_medium=web2x&context=3
