### ISSUE TITLE
Godot 4.0.dev memory leak

### ISSUE THREAD

**Issue by Brankec** [godotengine/godot#42370]
**Godot version:**
4.0.dev

**OS/device including version:**
Ubuntu 20.04 LTS 64 bit. Vulkan project on a GTX 1080 with NVidia proprietary driver version 450. I downloaded Godot from Unofficial Godot Engine Builds [here](https://hugo.pro/projects/godot-builds/)

**Issue description:**
Large memory leak in mere seconds after trying to import a scene that Juan Linietsky used in his latest video or after trying to open a project where I tried to import the scene I mentioned previously. I have 18 gb of Memory Swap and 16 gb of system memory, both of which got maxed out in a span of 2-3 seconds.

**Steps to reproduce:**
1. Open this [link](https://sketchfab.com/3d-models/huge-medieval-battle-scene-19b198bb18be49498db3b647abebc755) and download the scene called "Huge Medieval battle scene".
2. Click "Download 3D Model" button and select the first option "Original format (fbx)".
3. Extract the downloaded file and Drag-and-drop it into Godot
4. Wait for it to reach 80-90% when importing before closing Godot

**Minimal reproduction project:**
The scene size is 200mb and is too large for github.

**Remark:**
it doesn't create a memory leak if I try to import any other scene

**Comment by Pete-The-Penguin** [comment]
the scenes that didn't create the memory leak, are they .gltf files? Because if so, that means that the .fbx file importer in godot is broken. Currently another person is reworking the FBX importer.

**Comment by Pete-The-Penguin** [comment]
Also its best to either download from the official godot website, or build the master branch yourself.

**Comment by RevoluPowered** [comment]
OK I have fixed this in #47880 and bizarrely wasn't a 'leak' behaved a lot like one, but it was copying 32 million vertexes 192 million times, so.... it might have finished importing in a few days 🤣 

anyways, it's sorted now in that PR.
