### ISSUE TITLE
Swift/Objective-c Support for IOS project?

### ISSUE THREAD

**Issue by etamity** [godotengine/godot#4237]
on IOS export, the godot engine has been compiled into godot_opt.iphone file.
but there is not entry file for Objective-c/swfit,
For example, when you want to add push notification function,  admob, or google analytics function, if you want to use some cocoa component or code, how can you do that?

**Comment by beocat** [comment]
I think you want to write a C++ module and compile the engine with that.

**Comment by mohaalak** [comment]
look at  [this example](https://github.com/punto-/godot_modules)

**Comment by etamity** [comment]
Thank you for your reply.

Yes, I have seen this way to do, but I have to familiar with Objective C++ echo system ?
Also, I don't even know how to debug with this C++ code ?

I mean in this way, if we can compile the Godot engine into a framework or library,  just like cocos2d, then we will be able to free to write native code.
Is this possible ?

**Comment by a-lexu** [comment]
Yes, I'm too looking for this since it's the most clean and straight forward way to add code and all of the frameworks that already exist in Objective-C and Swift

**Comment by a-lexu** [comment]
Also it's important for using ARC

**Comment by punto-** [comment]
You should also be able to do this with a GDNative module (if you can link
those weird languages as a .dylib :p )

**Comment by Calinou** [comment]
I'll close this issue as it's out of scope for the main Godot repository. Also, note that Godot has ARKit support since 3.2.

If you still have a need for this, please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository.
