### ISSUE TITLE
Adding "Quick open" for scenes and scripts

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4239]
As my game project grows in size, I found myself navigating too often in files to open what I'm searching for. Tabs are okay, but at some point, I end up not using them so much.
So, just like Sublime Text, Atom or Visual Assist, why not adding a quick-open command triggered with a shortcut, to open files or scripts just by knowing a part of their path?
And if it's not a priority for the editor, how can it be added by extending it with a script?

EDIT: Oops, I found it actually exists for scripts with Ctrl+Alt+O, and for any file with Ctrl+Alt+P. But the latter doesn't opens the scene/script, it just locates it in the file system.

**Comment by neikeq** [comment]
Isn't this already implemented?:
![captura de pantalla de 2016-04-05 18-41-58](https://cloud.githubusercontent.com/assets/7718100/14290143/243118f6-fb5e-11e5-9aba-55882a5dcc41.png)

**Comment by Zylann** [comment]
Yes it is, sorry about that. The issue can be closed :)

**Comment by Mupli** [comment]
It is not that well documented. Well it is but with so much other stuff. And I've struggle to find the answer.
