### ISSUE TITLE
You can change textedit's color via: $TextEdit.add_color_override("font_color", Color8(254,171,31)) but you cannot change the font size via $TextEdit.add_font_override("font_size",100)

### ISSUE THREAD

**Issue by BracerJack** [godotengine/godot#42405]
**Godot version:**
3.2.2

**OS/device including version:**

**Issue description:**
You can change textedit's color via: $TextEdit.add_color_override("font_color", Color8(254,171,31)) but you cannot change the font size via $TextEdit.add_font_override("font_size",100) ? Why the inconsistency ?

**Steps to reproduce:**
I am using dynamic font.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
`font_size` is not a property of TextEdit, but of the Font resource. Fonts don't have any color assigned, so whatever draws the text decides the color, hence why `font_color` is a property of certain controls. This looks like inconsistency, but makes sense if you understand the difference.

See also #5557 and related discussion.

**Comment by akien-mga** [comment]
Moreover, look at the documentation for `Control.add_font_override()`: https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-add-font-override

The first parameter is the name of a font in the current `Theme`: https://docs.godotengine.org/en/stable/classes/class_theme.html#class-theme-method-get-font-list

**Comment by BracerJack** [comment]
Thank you KoBeWi, I didn't realize changing something as simple as a text component's font size via code is currently so painful in Godot.
Really miss the intuitiveness of Macromedia Flash :-(
