### ISSUE TITLE
TSCN bug when exporting path to an image

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#4240]
**Operating system or device:**
Mageia 5

**Issue description** (what happened, and what was expected):
tscn format saves the whole content of the image targetted by an exported path variable inputted to a script, into the tscn file, bloating it up. Should simply export the path instead.

**Steps to reproduce:**
1. Download this project's zip : https://github.com/StraToN/godot_pointandclickadv/releases/tag/v0.1
2. Open the project in Godot editor (scene file is /Assets/rooms/desk/desk.scn)
3. Directly save the scene as *.tscn

The output tscn is ~15 Mb. 
Godot seems to export the content of the depth.png image which path is provided as a parameter to the "bg" node, instead of the provided path.

**Link to minimal example project** (optional but very welcome):
https://github.com/StraToN/godot_pointandclickadv/releases/tag/v0.1

**Details**
The corresponding exported image is located in the Assets/terrain.gd script.

**Comment by bojidar-bg** [comment]
Just to note, this is happening with `export(Image) var …`, and not with `export(ImageTexture) var …`, right?

**Comment by StraToN** [comment]
@bojidar-bg I will test this during mid-day and will edit this message for answer.

Also a possible workaround (**not tested, just thinking**) is to use:
```export(Path) var depthFilePath
var depthFile = load(depthFilePath)
```
instead of 
```export(Image) var depthFile```

**Comment by bojidar-bg** [comment]
@StraToN ~ Is there a size difference with `.scn` between `Image` and `ImageTexture`?

**Comment by StraToN** [comment]
@bojidar-bg No, it's 5.8 Kb in both cases.

**Comment by reduz** [comment]
This is not a bug, it's a feature. Images are a built-in atomic datatype, not a resource, so exporting Image will not link it to a path, it will include it in the scene or resource.

**Comment by bojidar-bg** [comment]
@reduz But it is the same size on `.scn`, so it either saves the image in both cases, or just links to it...

**Comment by StraToN** [comment]
@bojidar-bg @reduz Indeed the behaviour is different between ``.scn`` and ``.tscn``.

**Comment by bojidar-bg** [comment]
Reopening after discussion on #8086, plus, this wasn't fixed it seems... can we have some testing on 3.0?

**Comment by akien-mga** [comment]
Well it wasn't fixed as @reduz said it's a feature. Still, I think TSCN should not allow bundling binary data like Image.

**Comment by bojidar-bg** [comment]
@akien-mga No, it wasn't fixed since `.scn` doesn't exhibit the behaviour, while `.tscn` does

**Comment by reduz** [comment]
Image is now a resource, so this bug no longer applies
