### ISSUE TITLE
Editing items in Tree control does not edit the correct item

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#42419]
**Godot version:**
4.0 dev 80165210c

**OS/device including version:**
win 10

**Issue description:**
If you edit an item and click _off_ that item and _on_ to another item to stop the editing, the item you clicked _on_ to will be edited instead. You can also observe this in the Input map editor where it is very strange and broken. Just clicking around completely breaks it.

![inputmapeditor_tree_broken](https://user-images.githubusercontent.com/41730826/94632467-faac8300-030d-11eb-84b7-096939c7d775.gif)
PS. also the tree does this really annoying thing where sometimes when you select it scrolls upwards... super annoying...

**Steps to reproduce:**
```
# script on a Tree control
func _ready():
	var root = create_item()
	hide_root = true
	columns = 1
	
	for i in range (5):
		var item = create_item(root)
		item.set_editable(0, true)
		item.set_text(0, "%s" % i)
	
	pass # Replace with function body.
```

![tree_editing_broken](https://user-images.githubusercontent.com/41730826/94632197-575b6e00-030d-11eb-9655-be9bbffdd90b.gif)

**Minimal reproduction project:**
[TreeTesting.zip](https://github.com/godotengine/godot/files/5302610/TreeTesting.zip)

**Comment by EricEzaM** [comment]
It gets even worse...
![tree_broken_2](https://user-images.githubusercontent.com/41730826/94633289-32b4c580-0310-11eb-8af9-5b21bcd97a21.gif)

```gdscript
	for i in range (5):
		var item = create_item(root)
		item.set_editable(0, true)
		item.set_text(0, "%s" % i)
		
		item.set_editable(1, true);
		item.set_cell_mode(1, TreeItem.CELL_MODE_RANGE);
		item.set_range_config(1, 0.0, 1.0, 0.01);
		item.set_range(1, 0.5 / float(i+1));
```

**Comment by alazifk** [comment]
I think the issue is with the text buffer. It only happens when you click on one cell directly after the other. It does not happen if in-between you click at a non-cell spot.

**Comment by Rindbee** [comment]
May be suppressed by #56408. More difficult to reproduce.

**Comment by EricEzaM** [comment]
Yeah I can't reproduce any more
