### ISSUE TITLE
Custom normals are not displayed correctly on backfaces

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#42411]
**Godot version:**
Godot 3.2.3

**OS/device including version:**
Windows 10 Pro v.2004 / Inspiron 7373 Core i7-8550U / Intel(R) UHD Graphics 620

**Issue description:**
When using custom normals, they display incorrectly on backfaces. This is problematic when doing things like vegetation where you would have culling disabled and use custom normals to get effects like this https://simonschreibt.de/gat/airborn-trees/
It's difficult to show off the issue, but I made the image below and you can look in the example project. Godot is using the custom normals in some way, but it is incorrect. It becomes especially clear when you have a low roughness on a material as you will be getting very incorrect specular highlights as you can see on the image of the tree further below.

![CustomNormals](https://user-images.githubusercontent.com/4955051/94572508-05610c80-0269-11eb-8c37-ae84c59e2563.png)

Example of the issue in my current project
![image](https://user-images.githubusercontent.com/4955051/94573184-c089a580-0269-11eb-9395-5429050861ed.png)

**Steps to reproduce:**
Open the attached example project to see the issue.

**Minimal reproduction project:**
[CustomNormalsBackface.zip](https://github.com/godotengine/godot/files/5299939/CustomNormalsBackface.zip)

**Comment by lolleko** [comment]
Seems like the backface normals are flipped when using the `double_sided` render mode: https://github.com/godotengine/godot/blob/3.2/drivers/gles3/shaders/scene.glsl#L1655

This was introduced to fix normal maps when using double sided rendering: https://github.com/godotengine/godot/issues/19918

I am not sure this is fixable without breaking normal maps. Maybe only flip normals if normal maps are enabled @reduz ?

You can use the following in a shader as a workaround for now:

```c
void fragment ()
{
	if (!FRONT_FACING) {
		NORMAL = -NORMAL;
	}
}
```

![Screenshot 2020-10-13 at 15 28 26](https://user-images.githubusercontent.com/4759511/95866880-bfc43980-0d68-11eb-9529-989741d742cc.png)

**Comment by Arnklit** [comment]
Does that mean using your workaround would make my normal maps incorrect on backfaces?

**Comment by Arnklit** [comment]
Just wanted to give an update on this, as I was trying this method again. While it works to invert the normals, for them to be pointed in the correct directions. It still doesn't solve the issue of low roughness causing very strange shading. I think there is something wrong with the diffuse calculation when using custom normals, but I don't know how to track it down.

Roughness 1.0:
![image](https://user-images.githubusercontent.com/4955051/115512196-9c2efe00-a279-11eb-9d6a-2c19f70dfb18.png)

Roughness 0.5:
![image](https://user-images.githubusercontent.com/4955051/115512247-ae10a100-a279-11eb-991c-87c12722fb62.png)

**Comment by Calinou** [comment]
@Arnklit Can you upload a minimal reproduction project with the tree model shown in https://github.com/godotengine/godot/issues/42411#issuecomment-823835366? I'm having trouble seeing the issue on the MRP with the Blender comparison (they look mostly identical, with the exception of the normal buffer because of a lack of sRGB conversion on display).

**Comment by Arnklit** [comment]
I'm not sure I still have that. I'll have a look tomorrow and otherwise I will make some new models to test with.

**Comment by Arnklit** [comment]
I think we are fine to close this. I found some of these original models and textures and there were some bugs that make me doubt the issues with low roughness. I'll open a new better bug if I reproduce with better assets. Closing.
