### ISSUE TITLE
Color correction gradient versus glow in GLES2

### ISSUE THREAD

**Issue by gdesecrate** [godotengine/godot#42421]
**Godot version:**
3.2.3.stable.official (Steam)

**OS/device including version:**
5.8.6-1-MANJARO
RX5500XT
GLES2

**Issue description:**
Color correction gradient gets used as glow effect texture.
![Screenshot_20200930_051938](https://user-images.githubusercontent.com/41639190/94636234-3c710580-02dd-11eb-8441-ed11844ad00a.png)

**Steps to reproduce:**
Set GLES2. 
Edit the world enviroment.
Add color correction gradient. Enable Glow. (Very noticeable on additive blend mode)  

**Minimal reproduction project:**
[colorcor.zip](https://github.com/godotengine/godot/files/5302823/colorcor.zip)

**Comment by akien-mga** [comment]
Fixed by #42446.
