### ISSUE TITLE
get_mouse_position() is offset.

### ISSUE THREAD

**Issue by gaetgu** [godotengine/godot#42425]
I have searched for this but could not find anything that matched my issue.

**Godot version:**
Godot v3.2.3.stable.mono.official

**OS/device including version:**
macOS Mojave 1.14, 2.7 GHz Intel Core i7, Intel HD Graphics 3000 512 MB

**Issue description:**
I am creating a bullet hell game along with [this](https://www.youtube.com/watch?v=NMNl9Ix6ng8&t=240s) tutorial. however, I am finding that the icon (Player) is offset from my mouse. I have switched out his `get_global_mouse_position()` with `get_viewport().get_mouse_position()`, but I get the exact same issue. A quick video can be seen below.

![ezgif-5-82c570c42905](https://user-images.githubusercontent.com/47652746/94649616-403b6280-02b2-11eb-8963-a5715546cbb7.gif)

**Steps to reproduce:**
Create a Player object with this script attached to it:

```py
extends Node2D

func _ready():
	pass 

func _process(delta):
	self.position = get_viewport().get_mouse_position()

```
Sorry if this is not the most clear, check out the video for exact steps.

**Minimal reproduction project:**
[BHTwo.zip](https://github.com/godotengine/godot/files/5303420/BHTwo.zip)

Thanks for any help!

**Comment by akien-mga** [comment]
Haven't opened the project yet (on phone), but remember that `position` is local, so any offset to the origin from parent nodes will be kept. The gif looks like Player's parent has a non-zero position itself. If so, the behaviour is correct.

**Comment by akien-mga** [comment]
This is your Player node:
![Screenshot_20200930_084955](https://user-images.githubusercontent.com/4701338/94652213-ef4f5c80-02f9-11eb-9538-4f82127b37e4.png)

The Player position is (0, 0) (red cross, selected). The Sprite and Area2D are at an offset (white cross). Your script moves the Player node, the offset for Sprite and Area2D stays the same. Move them to the same position as Player if you don't want this offset.
