### ISSUE TITLE
Tree scrolls on its own when selecting items

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#42420]
**Godot version:**
4.0 dev 8016521

**OS/device including version:**
WIN 10

**Issue description:**
Tree scrolls on it's own when selecting items.
Probable cause is that Tree scrolls when clicking and dragging mouse... I don't even know why this is a feature with the mouse - should be touch only.

**Steps to reproduce:**
Open input map settings and just select items a bit until it happens. Seems to only happen on items which are editable...?
![tree_scrolling](https://user-images.githubusercontent.com/41730826/94634122-87594000-0312-11eb-958a-a16aeebe0d39.gif)

**Comment by Riteo** [comment]
Is this related to #38665?

**Comment by EricEzaM** [comment]
Yes I think so, could be scroll container related? Or just use the same code for scrolling.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/38665.
