### ISSUE TITLE
Incrementing rotation_degrees property of a Node2D results in the value getting incresingly unprecise.

### ISSUE THREAD

**Issue by pajcek11** [godotengine/godot#42429]
**Godot version:**
3.2.3.stable.official

**Issue description:**
Even when I take all precautions and force ints, the problem of a small value being added or removed from what the value should actually be persists.
It goes: 
...
...30, 30.999998, 32... 
...60, 61.000004, 62.000004, 63.000004, 64...
...114, 115.000008, 116.000015, 117.000023, 118.000031, 119.000038, 120.000046, 121.000053, 122.000046, 123.000038, 124.000038, 125.000046, 126.000053, 127.000061... 
(with .000061 now persisting in all subsequent numbers)

...231.000061, 232.000046, 233.000046, 234.000046, 235.000031, 236.000031, 237.000031, 238.000015, 239.000015, 240...
...242, 242.999985, 243.999985, 244.999985, 245.999969, 246.999969, 247.999954, 248.999954, 249.999954, 250.999939, 251.999939, 252.999939, 253.999924, 254.999924, 255.999908 ...
(with .999908 now persisting until 360)

**Steps to reproduce:**
    self.rotation_degrees += 1

**Comment by Calinou** [comment]
This is how floating-point math works. The further away you get from 0, the less precise the value.

Try setting `rotation` directly (even using a `deg2rad()` conversion on your side) rather than setting `rotation_degrees`.

**Comment by pajcek11** [comment]
tnx. I always get surprised anew by how imprecise math can get in computing...
