### ISSUE TITLE
C# Mono release builds contain debug info (PDB)

### ISSUE THREAD

**Issue by Bleuzen** [godotengine/godot#42436]
**Godot version:**
3.2.3

**OS/device including version:**
Manjaro Linux (current stable branch)

**Issue description:**
When a mono game is exported as release build, it will still contain pdb files with some debug information. I don't think that everyone out there playing the game should know the file structure and paths of my system. PDB files should only be included in debug builds.

**Steps to reproduce:**
Make a game with Mono / C# and export it as release build. The .pck file will contain the assembly and the .pdb.

**Comment by neikeq** [comment]
We need to add a export flag for this.

**Comment by Phischermen** [comment]
Is this a security concern? Could somebody do something malicious if they have a copy of your mono game on their machine?

**Comment by Calinou** [comment]
@Phischermen No, although it can expose your real name unexpectedly if you use it as your OS username.

**Comment by raulsntos** [comment]
As a workaround, adding this to the `.csproj` should work:

```csproj
<PropertyGroup Condition=" '$(Configuration)' == 'ExportRelease' ">
  <DebugSymbols>False</DebugSymbols>
  <DebugType>None</DebugType>
</PropertyGroup>
```
