### ISSUE TITLE
GDNative resources not unloaded when no longer referenced

### ISSUE THREAD

**Issue by geekrelief** [godotengine/godot#42449]
**Godot version:**
3.2.3

**OS/device including version:** only tested on Windows

**Issue description:**
Via gdnative, loaded a gdns file referencing a dll. No references to the loaded resource are held.  Next frame, ResourceLoader.has_cache is checked for the gdns file and returns false.  But the resource is not freed. There are no references to the resource, but the gdns / dll library is still held in memory and file access to the dll is locked until the application exits. 

The reference count for the gdns resource should be 0 if ResourceLoader.has_cache returns false for the gdns resource path. And the resource should be freed, meaning godot_gdnative_terminate should be called on the dll and the dll file access should be free.

**Steps to reproduce:**
Using godot-nim or other gdnative binding.
From a host gdns dll, call ResourceLoader.load on a "component" gdns resource with sub resource to a dll. Next frame check that ResourceLoader.has_cache for the gdns resource path is false. If false, attempt to open the dll file referenced in the gdns resource.

**Minimal reproduction project:**
I can provide a minimal project for godot-nim bindings, but you'll need to install nim.

**Comment by geekrelief** [comment]
A simpler test case.  I created a Curve Resource "res://curve.tres".  Via gdnative, on _ready using ResourceLoader.load("res://curve.tres"), and I discard the results.  There shouldn't be any references to the resource at this point.  

In visual studio I set the debug configuration properties to run my app and load my test scene. 
`--path pathtomyapp res://test.scn` 

Let the debugger run to line 160 in godot_windows.cpp widechar_main so Main::setup() finishes. Put a breakpoint in core/reference.h line 279 where the memdelete(reference) occurs. Let the debugger run.  
You'll see the ResourceInteractiveLoader destroy itself after loading "res://curve.tres". But memdelete(reference) never shows Curve being deleted. 

I double checked the godot-nim bindings to make sure Reference.unreference was being called when the Curve object leaves its creation scope, and I see in unreference being called in the engine via the visual studio debugger.  Normally, when unreference is called it's through the ~Ref() destructor which calls unref() which looks like this:
`
// reference.h line 272
void unref() {
		//TODO this should be moved to mutexes, since this engine does not really
		// do a lot of referencing on references and stuff
		// mutexes will avoid more crashes?

		if (reference && reference->unreference()) {

			memdelete(reference);
		}
		reference = NULL;
	}

	void instance() {
		ref(memnew(T));
	}

	Ref() {

		reference = NULL;
	}

	~Ref() {

		unref();
	}
`
But since the gdnative bindings don't have access to unref(), a call to unreference() just decrements the count but memdelete is never called.

I'm not sure if this is an issue that's particular to the godot-nim bindings or all gdnative bindings.  But it seems like unreference is meant to be called with the expectation the engine will delete the Ref if it's refcount hits 0.

**Comment by geekrelief** [comment]
On further inspection of the godot-nim bindings it looks like it calls objectDestroy which seems to reference gdnative.cpp godot_object_destroy which calls memdelete.  https://github.com/godotengine/godot/blob/48afdfddb583c117ea3fff49d94b781b676b38e7/modules/gdnative/gdnative/gdnative.cpp#L46
So Curve should be freed. But a breakpoint on godot_object_destroy is not triggered.  I'm not sure where nim's objectDestroy is calling into the engine then.

**Comment by geekrelief** [comment]
It  looks like godot_object_destroy is being called properly, but the gdns resource is not being released properly.  I've nailed it down to NativeScriptLanguage::unregister_script.  The function https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/nativescript.cpp#L1719-L1732 checks to see if any other scripts are using script->lib_path and deletes it from library_script_users.

So I access library_gdnatives.find(script->lib_path) and terminate the GDNative object and erase it from library_gdnatives.  This frees the dll.

**Comment by geekrelief** [comment]
This is resolved with PR #44617

**Comment by akien-mga** [comment]
Fixed by #44617.
