### ISSUE TITLE
Godot compiled by scons not working

### ISSUE THREAD

**Issue by Rdna123** [godotengine/godot#42444]
**Godot version:**

Branch Main

**OS/device including version:**

Windows 10

**Issue description:**

Compiling issues

**Steps to reproduce:**

install Godot using `git clone https://github.com/godotengine/godot.git` and used scons compiled EXE no responding.
 
**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Please provide more information. What command did you use to build Godot? What gets printed out when you run the engine?

Right now you haven't given anyone enough information to help you.

**Comment by Rdna123** [comment]
This was the exit code `progress_finish(["progress_finish"], [])`

**Comment by clayjohn** [comment]
Those just mean that the code finished compiling. Is anything printed when you run the engine? 

If not try compiling with the following command:

``scons p=windows windows_subsystem=console``

**Comment by Rdna123** [comment]
Here is a TXT of the [error.txt](https://github.com/godotengine/godot/files/5309390/error.txt).

**Comment by clayjohn** [comment]
Do you have the Vulkan SDK installed? If so, are you able to run the vkcube example?

**Comment by Rdna123** [comment]
Didn't need to before, but I will go try.

**Comment by Rdna123** [comment]
I have downloaded the SDK now, but cube will not run

**Comment by Calinou** [comment]
@Rdna123 Which i7 model is it? 4th-gen (Haswell) IGPs and older aren't supported, since they don't have a *complete* Vulkan implementation. If you're using integrated graphics, you need to have a 5th-gen (Broadwell) CPU or newer.

**Comment by Rdna123** [comment]
core i7 8th intel

**Comment by clayjohn** [comment]
Have you updated your graphics drivers recently? If the vkcube doesn't run, it means your current hardware setup doesn't support Vulkan.

**Comment by Rdna123** [comment]
Graphic drives are update to most recent.
