### ISSUE TITLE
InputEventMouseMotion (and other input events) should have "speed" renamed to "velocity" as it is represented as a vector.

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#42450]
**Issue description:**
Speed is a scalar quantity, and is the magnitude of velocity. In godot, Since speed is represented as a vector, it is actually a velocity since it represents both magnitude and direction.

[Physics Classroom Link](https://www.physicsclassroom.com/class/1DKin/Lesson-1/Speed-and-Velocity)

Speed | Vector2
-- | --
Default | Vector2( 0, 0 )
Setter | set_speed(value)
Getter | get_speed()

becomes

Velocity| Vector2
-- | --
Default | Vector2( 0, 0 )
Setter | set_velocity(value)
Getter | get_velocity()

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/16863.
