### ISSUE TITLE
Can't export variable with a setter

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#42463]
**Godot version:**

c646768

**Steps to reproduce:**
1.
```
@export var test: int:
	get:
		pass
```
2. Crash

Same for both setters and getters. Removing `@export` works fine.

**Comment by KoBeWi** [comment]
No, it's a different bug. I discovered it when testing #42190, not sure if it's possible in vanilla build due to the syntax error preventing the script parsing.

**Comment by nathanfranke** [comment]
In 5525cd85c this doesn't crash anymore but saving the scene creates an invalid file- variables are put with
` = null`

**Comment by Nathan173AB** [comment]
> In [5525cd8](https://github.com/godotengine/godot/commit/5525cd85c60455b0bb9716bbef0ad2ad8111d752) this doesn't crash anymore but saving the scene creates an invalid file- variables are put with
> ` = null`

This sounds like what I'm getting. I'm using the latest master build as of today. Whenever I create a scene that has a _set_ defined in its script, loading that scene in the editor later will fail and I get this message in the output:

`Invalid scene: node Main does not specify its parent node.`

**Comment by lyuma** [comment]
seems like in latest master it works if called from gdscript.

the getters/setters don't seem to be used in the inspector. saving the scene now seems to work fine.

**Comment by KoBeWi** [comment]
There is no longer crash, so closing.
