### ISSUE TITLE
Kinematics body regression when using raycast collision shapes.

### ISSUE THREAD

**Issue by HungryProton** [godotengine/godot#42462]
**Godot version:**
3.2.git
Commit causing the regression : a9b5dc56a6a77a8392e9e313ce3462311b7bebf3

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When using Bullet, kinematics body ignores the ray collision shapes when using `move_and_slide`.
Using `move_and_collide` makes it collide at the beginning of the ray instead of the end.

**Steps to reproduce:**
- Create a kinematic body with a ray collision shape
- Move it towards another physic body with `move_and_collide`: The collision happens at the wrong end
- Move it with `move_and_slide`: The collision is ignored.

**Minimal reproduction project:**
[minimal_project.zip](https://github.com/godotengine/godot/files/5311830/minimal_project.zip)

Motion happens in the gravity.gd script.

**Comment by akien-mga** [comment]
>  Commit causing the regression : a9b5dc5

That's the cherry-pick for #41426, CC @madmiraal @AndreaCatania.

**Comment by HungryProton** [comment]
In the minimal project I sent, the collision shape is rotated. I used **the 3D gizmo** to make it point downwards and the transform matrix looks like this:
![image](https://user-images.githubusercontent.com/52043844/94858307-25dcc280-0433-11eb-9e8f-5f67c3c5b09d.png)

But! If I click the revert icon and **manually type 90°** in the x axis rotation, the transform matrix is slightly different:
![image](https://user-images.githubusercontent.com/52043844/94858631-a3a0ce00-0433-11eb-9dca-4aba46ea524a.png)

(Notice the -0 instead of 0)
I have no idea why it makes a difference but the collision happens properly in this case.

**Comment by madmiraal** [comment]
Fixed with #42500.

Interestingly, -0 should have caused it to fail (flip the RayCast) too, but Bullet didn't think that it was close enough to zero. :confused: So maybe something to look into too.
