### ISSUE TITLE
iMac Retina OS.get_screen_dpi()  incorrect in 3.2.3 release

### ISSUE THREAD

**Issue by JayHiserote** [godotengine/godot#42474]
Version 3.2.3

iMac Retina 27 inch, Late 2015 (5120x2880)
MacOs Catalina 10.15.7

My application under development in Godot 3.2.1 reports an OS.get_screen_dpi() = 217
After installing 3.2.3 my application reports an OS.get_screen_dpi() = 144

Allow Hidpi is on in the project's display settings.

I believe the dpi value reported in 3.2.1 (217) is correct.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Indeed, is seems to return `144` for all displays with `scale != 1` and `72` for `scale == 1`, I messed it up in #40084 cause `144` is correct for my display, but previous version of code seems to return completely inaccurate values as well.
