### ISSUE TITLE
setget does not update

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot#42473]
**Godot version:**

3.2.3 (actually, I've tried with 3.1 and 3.2.2 too)

**OS/device including version:**

**Issue description:**

When a setget var is updated, it doesn't call the setter.

**Steps to reproduce:**
Just make a setget function and changes it's value to see it. It's working on old scripts, I can even create more vars on old scripts and they will work, but if I make a new one, it doesn't.

**Minimal reproduction project:**

[Setget-bug-Reproduction.zip](https://github.com/godotengine/godot/files/5313848/Setget-bug-Reproduction.zip)

**Comment by Calinou** [comment]
This is intended in 3.2.x. Use `self.a = ...` to set the value and trigger the setter, not `a = ...`.

This behavior will be changed in 4.0 thanks to the [new GDScript](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged).
