### ISSUE TITLE
filepath problem

### ISSUE THREAD

**Issue by eaglecat** [godotengine/godot#4247]
in release mode, the program does not read ../ word

```
if tempfile.file_exists("res://resources/folderA/a7.bme/../a7.bme"):
	print("exists!")
else:
	print("not exists!")

```

in debug mode, this code prints exist!
in release, prints not exists!

**Comment by akien-mga** [comment]
The question is: which one is the bug? :D

I don't think ``resources/folderA/a7.bme/../a7.bme`` would be a valid path on Unix, unless ``a7.bme`` is a folder. Not sure about Windows. At any rate it's strange that it gives a different behaviour.

**Comment by eaglecat** [comment]
but I did debug on Window and also exported to window

**Comment by reduz** [comment]
no this should definitely not work, maybe in windows it works for some bizarre reason but it's not a standard and universal way to refer to files
