### ISSUE TITLE
Text input in inspector properties can be interrupted by AnimationPlayer.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#42488]
**Godot version:**

e35687a1160eb65dc5f793852d4c8352aefe602f

**OS/device including version:**

Win10 64-bit

**Issue description:**

While typing when a looping AnimationPlayer is playing, and the Animation panel is open, the text cursor in inspector values jump around while typing.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/13004169/94889931-7df0e480-0486-11eb-9171-6b5dbc28734f.gif)

**Steps to reproduce:**
Play a looping animation, and type something in a LineEdit control in the Inspector.

Using the MRP below the root node has an export var String to test with.

**Minimal reproduction project:**

[AnimationPlayer Inspector Conflict.zip](https://github.com/godotengine/godot/files/5316066/AnimationPlayer.Inspector.Conflict.zip)

**Comment by EricEzaM** [comment]
Could be related to #41809? For some reason the anim player is called `update_property()` on the properties for some reason? The symptom is exactly the same.

**Comment by akien-mga** [comment]
The animation player likely refreshes the inspector because if you're inspecting a node affected by an animation, you should see its animated properties change (e.g. frame index on a Sprite).

I'm not sure if there's any proper fix for this.
