### ISSUE TITLE
C# - Accessing values in a Godot.Collections.Dictionary seems to return copies instead of consistent references?

### ISSUE THREAD

**Issue by iamacup** [godotengine/godot#42484]
I am sorry if this has been posted before, I have searched the issues but can't find anything. This is some behaviour that I would not expect as we are accessing a value by reference, but the reference is not consistent? I would have expected it to behave the same as the C# dict? 

**Godot version:**

3.2.3.stable.monoo

**OS/device including version:**

OpenGL ES 2.0 Renderer: AMD Radeon Pro 555 OpenGL Engine
OpenGL ES 2.0 Batching: ON

**Issue description:**

```
            Godot.Collections.Dictionary<object, object> z = new Godot.Collections.Dictionary<object, object>() {
                {"someKey", new Godot.Collections.Dictionary<object, object>() {
                    {"someOtherKey", "someValue"}
                }}
            };

            GD.Print("Some values stored in a godot dict");
            GD.Print(z["someKey"].GetHashCode());
            GD.Print(z["someKey"].GetHashCode());
            GD.Print(z["someKey"].Equals(z["someKey"]));
            GD.Print(System.Object.ReferenceEquals(z["someKey"], z["someKey"]));

            System.Collections.Generic.Dictionary<object, object> t = new System.Collections.Generic.Dictionary<object, object>(){
                {"someKey", new System.Collections.Generic.Dictionary<object, object>() {
                    {"someOtherKey", "someValue"}
                }}
            };

            GD.Print("Some values stored in a c# dict");
            GD.Print(t["someKey"].GetHashCode());
            GD.Print(t["someKey"].GetHashCode());
            GD.Print(t["someKey"].Equals(t["someKey"]));
            GD.Print(System.Object.ReferenceEquals(t["someKey"], t["someKey"]));
```

outputs this

```
Some values stored in a godot dict
1179816577
-164861908
False
False
Some values stored in a c# dict
365243463
365243463
True
True
```

**Steps to reproduce:**

Code above

**Minimal reproduction project:**

**Comment by aaronfranke** [comment]
Under the hood, the array operator calls `godot_icall_Dictionary_GetValue` (or the `_Generic` version):

https://github.com/godotengine/godot/blob/5e726d8d2025f1bc52299894230d94ef5972cea4/modules/mono/glue/collections_glue.cpp#L185-L197

Since it's converting a Variant to a Mono object on every access, it's not surprising that this is the behavior. However, I'm not sure if there's a way to change this without reworking how all of this code works.

**Comment by iamacup** [comment]
OK, in the meantime i have rewritten the function that relied on this behavior in GD script and call it from C#.

I don't know what to do with this issue @neikeq - happy if you want to close it but the behavior is not intuitive and might catch people out so maybe a docs message about it or something in the future :)

**Comment by iamacup** [comment]
@GeorgeS2019 i think it is a bit of a documentation thing - i feel like the Godot.Collections.Dictionary class (and somewhat the array class) are themselves noob traps - there is no real reason to use them as far as i can see (would be happy too be corrected here) unless you need to interface with some GDScript that requires a Dict as an input or if some native thing (like the networking or whatever) returns one.

The reason they are a noob trap is - coming from C#, you see a, what you assume to be highly optimised dictionary class specifically for Godot and start using it, but actually it seems that it is just fallout from the GDScript JSON-Like language construct - Dictionary - and it behaves in strange was, in as in this issue.

**Comment by GeorgeS2019** [comment]
@iamacup  I think the keyword here is Noob Traps.   I too frequently use GDScript to validate if the C# method calls would lead to similar results as that of the GDScript. I do not have the overview, which C# methods (under what circumstances) will behave and lead to similar results as the correspondence GDScript calls.  This is Why if we have the community to support unit tests that recommend how BEST to call C# methods for the corresponding GDScript call.  We can learn from the best practice used by the more experience C# Godot developers. I hope this will lead to better c# Nood developer experience. This is just a suggestion.

**Comment by Calinou** [comment]
@GeorgeS2019 Please don't derail the discussion with off-topic comments. This issue has no relation to unit tests or lack thereof.

**Comment by neikeq** [comment]
This is expected. `Godot.Collections.Array/Dictionary` are wrappers around Godot's native `Array/Dictionary`. As such when storing a string from C#, it's converted into Godot's String type. If this is not ok for you, then I recommend using a different collection like those in `System.Collections.Generic`.

**Comment by iamacup** [comment]
@neikeq its not just strings though - its any stored value -

Dictionary d = new Dictionary();
d["one"] = 1;
GD.Print(d["one"] == d["one"]); // false

I don't really want this to drag on, there are more important things to worry about in Godot and this is clearly a bigger thing to solve for which you correctly point out are other solutions (System.Collections.Generic) - i think users should be told to avoid Godot.Collections.Dictionary at almost all costs - it causes a lot of issues that are hard to debug because of this behavior.

**Comment by Calinou** [comment]
Reopening, as we still need to document this.

**Comment by takhimi** [comment]
Just want to share my findings for anyone that may encounter Godot Dict vs C# Dict.. 

```
            Godot.Collections.Dictionary<string, object> GodotDict = new Godot.Collections.Dictionary<string, object>();
            GodotDict["one"] = 1;
            GD.Print((int)GodotDict["one"] == 1); // true
            GD.Print(GodotDict["one"] == GodotDict["one"]); // false


            System.Collections.Generic.Dictionary<string, object> CSharpDict = new System.Collections.Generic.Dictionary<string, object>();
            CSharpDict["one"] = 1;
            GD.Print((int)CSharpDict["one"] == 1); // true
            GD.Print(CSharpDict["one"] == CSharpDict["one"]); // true


             GD.Print((int)GodotDict["one"] == (int)CSharpDict["one"]); // True
             GD.Print(GodotDict["one"] == CSharpDict["one"]); // False
```

**Comment by VestedGrammar** [comment]
Ya'll are talking about this in 2020, and I'm not finding much discussion. One point to add is that there are a number of implementations that require using Godot.Collections.Dictionary, e.g. PhysicsDirectSpaceState3D.IntersectRay
