### ISSUE TITLE
False positive unsafe_property_access warning on untyped field

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#42482]
**Godot version:**

3.2.2.stable.custom_build.bc8eea3e9

**OS/device including version:**

Linux 5.8.12-arch1-1

**Issue description:**

When an object field is declared without a type (because it is a `Variant`, and I don't know that you can explicitly specify `Variant` as a type?),
trying to access that field will warn you about `unsafe_property_access`, even though it should know that property exists.

**Steps to reproduce:**

```
extends Node2D

class Obj:
	var f: float
	var v # Variant

func _ready():
	var o := Obj.new()
	print(o.f)
	print(o.v) # The property 'v' is not present on the inferred type 'Obj' (but may be present on a subtype). [UNSAFE_PROPERTY_ACCESS]

```

**Minimal reproduction project:**

**Comment by rcorre** [comment]
For context, my real life example is:

```
class Action:
	enum Kind {
		NONE, # returned when there is no action left for the current time
		GRAPPLE, # data is True (engage) or False (release)
		LOOK, # data is a Vector2(x_rotation, y_rotation) in radians
		JET, # data is a Vector3 with each coordinate in the range [0,1]
		MAX
	}

	var time: float
	var kind: int  # Kind
	var data

	func _init(t: float, k: int, d):
		time = t
		kind = k
		data = d

class Writer:
	var actions: Array  # Action[]

...snip...

	func save(path: String):
		var file := File.new()
		file.open(path, File.WRITE)
		for a in actions:
                        # arrays are untyped, so I have to do this cast
			var act: Action = a
                        # I was hoping to get warned if I typo a field in the next line
                        # unfortunately I get a false negative on .data
			file.store_line("%.4f %d %s" % [act.time, act.kind, var2str(act.data)])
		file.close()
```

**Comment by rcorre** [comment]
I'm not quite sure why, but I can't seem to get `warning-ignore` working either:

```
	match act.kind:
		InputRecord.Action.Kind.GRAPPLE:
			# warning-ignore:UNSAFE_PROPERTY_ACCESS
			emit_signal("grapple", act.data)  # still warns me
```

**Comment by gettylee** [comment]
This problem is still present in 3.2.3.stable

**Comment by gettylee** [comment]
OP's use case was with variants but (not surprisingly) this affects enums since they can't be explicitly typed. For my use case, having explicitly-typed enums would solve the problem.

**Comment by akien-mga** [comment]
I can confirm the issue in `3.x` (7244ea7e20bdb5d0aa5fde61a82f958b1bc5bbec).

It's worth noting that the `UNSAFE_PROPERTY_ACCESS` warning is not enabled by default, so to reproduce the bug using the OP's script one needs to enable it in the Project Settings.
