### ISSUE TITLE
Failed to get cached path from RPC when reconnecting to a hosted multiplayer game

### ISSUE THREAD

**Issue by ZackingIt** [godotengine/godot#42483]
For once -- we have a *perfectly replicable* minimally-reproducible bug, as it occurs in an **official example**, the Multiplayer Bomber Demo!! 

My question is, given the following "bug" (which arises from just how RPC/polling/networked instancing is done), **what is the best way to implement safe reconnection to existing games**?
Godot's engine will never be crash-free, and not being able to reconnect to a multiplayer game seems like a critical issue.
Tagging @Faless  as he has done a lot of work here. 

**Godot version:**
3.2.3 or 3.2.2

**OS/device including version:**
Windows
https://godotengine.org/asset-library/asset/139

**Issue description:**
Players attempting to re-connect to an existing game will be unable to, with the following crash:
```
ERROR: _process_get_node: Failed to get cached path from RPC: World/Players/1.
   At: core/io/multiplayer_api.cpp:272
ERROR: Invalid packet received. Requested node was not found.
   At: core/io/multiplayer_api.cpp:204
ERROR: Node not found: World/Players/1.
   At: scene/main/node.cpp:1381
```
At which point, the server will also fail catastrophically.

**Steps to reproduce:**
1). Create three instances of the bomberman game locally:  1 for server, 2 for clients.
2). Host the game, and join with 2 clients.
3). Quit or ctrl+c out of one of the two clients
4). Try to re-join the game with one of the two clients.

**Minimal reproduction project:**
https://godotengine.org/asset-library/asset/139
^ the official example!

**Comment by Calinou** [comment]
> My question is, given the following "bug" (which arises from just how RPC/polling/networked instancing is done), what is the best way to implement safe reconnection to existing games?

See https://github.com/godotengine/godot-proposals/issues/75.

**Comment by Faless** [comment]
I'm unable to reproduce, meaning:

- I see no crash.
- You are probably missing a step in your description (i,e, press "start" to start the match before reconnecting).
- After that, if I connect a new client I can reproduce the error you mention (again, no crash). But this is expected, as he demo does not handle reconnection (in fact, it should probably just disable new connection after start has been pressed).

I would consider this issue invalid, as this is not a bug, and for the feature request there is already a proposal.

**Comment by ZackingIt** [comment]
I want to add for posterity/future users confused by this issue:  you can resolve reconnection by simply always:
a). maintaining consistent node name (and path, of course) references up reconnection (aka, do not ever name nodes by their network_id or you're gonna have a bad time)

b). correctly setting the network master to the new network_id, which should be decoupled from the node name.

RPC uses the node's path to identify the corresponding node in other client instances, so if you use the wrong name, ya gonna have a bad time. <3
