### ISSUE TITLE
Enhanced 2D and 3D particle system & tooling

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#4250]
It's a wild suggestion so feel free to ignore, but having more types of particle emitters would probably be cool. (It's also weird there isn't already a ticket for that, but I guess good particle effects are generally underestimated in games.)

Like beam emitters with startpos, endpos, trails, trail-fading, beam-fading and intense and zappynes (like for lightening bolts) parameters, or mesh emitters.

For example, check out [this](https://www.youtube.com/watch?v=OXK2Xbd7D9w) video.

As for the editor, a tool/stamp to group emitters would be awesome where included emitters could auto-inherit some parameters like lifetimes from. Imagine that for explosions, where you typically have fire, sparks, smoke and debris particles.

Note that I'm not even using Godot atm; I just think it would be a really cool feature to have for a game engine and it's probably a PITA to add manually afterwards. So if you got the time and motivation, why not.

**Comment by HeartoLazor** [comment]
+1 on this, I implemented non linear beams with collision support on my game using polygons + raycast 
https://gfycat.com/DrearyMadeupBlobfish
But I would love a similar solution with particles and collision like the unreal one, also should be less resource intensive than my solution

**Comment by KoBeWi** [comment]
Proposals on this repository are being closed. This issue was already linked in the particles proposal: https://github.com/godotengine/godot-proposals/issues/815
