### ISSUE TITLE
Textures on Sprite3D nodes with animated region_rects wobble (new in 3.2.3, 3.2.2 was unaffected)

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#42509]
**Godot version:** 3.2.3-stable
Also tested on 3.2.2-stable and couldn't reproduce it.

**OS/device including version:**
Ubuntu Linux 16.04, 64-bit
GeForce GTX 970 with NVIDIA 384.130 driver
GLES3 backend

**Issue description:**
After upgrading to 3.2.3 we noticed some of the sprites in our project wobbling. I've attached an example as a reproducer. These are Sprite3D nodes with animated region_rects, but the wobbling may occur in other situations; I'm not certain.

In 3.2.2, notice the skull at the bottom of the Sprite is rock steady:

![cb-540](https://user-images.githubusercontent.com/165720/94934425-9f23f600-04c3-11eb-9d13-c060b4c2d51f.gif)

In 3.2.3 the skull appears to wobble side-to-side by fractions of a texture pixel:

![cb-541](https://user-images.githubusercontent.com/165720/94934503-bcf15b00-04c3-11eb-8920-dd901a9d2757.gif)

(Apologies for the low-quality gifs.)

**Steps to reproduce:**

1. Open the reproduction project below in the Godot editor.
2. Select the AnimationPlayer node and preview an animation--`idle` and `alt_idle` demonstrate it most clearly.

**Minimal reproduction project:**
[wobbly_sprites.zip](https://github.com/godotengine/godot/files/5318509/wobbly_sprites.zip)

**Comment by akien-mga** [comment]
Fixed by #42537.
