### ISSUE TITLE
[3.2.3 - "sTaBLe"] Godot Opens 'Project List' when you click Run

### ISSUE THREAD

**Issue by ThaddeusWilliams** [godotengine/godot#42519]
Random chance that "Run" will open the Project list but keep the Editor open. Scared that when I export my game, this will just give the player another copy of Godot instead of my game... :(

**Comment by akien-mga** [comment]
Duplicate of #28036.

**Comment by Calinou** [comment]
> Scared that when I export my game, this will just give the player another copy of Godot instead of my game... :(

This can't happen. When you export a project, you only get a PCK file that includes the resources as if they were imported by Godot.
