### ISSUE TITLE
Math results vary widely based on order of operations.

### ISSUE THREAD

**Issue by pajcek11** [godotengine/godot#42528]
**Godot version:**
v.3.2.3.stable.official

**Issue description:**
If I type a formula one way, it turns out correct, and if another, I get a useless result.

**Steps to reproduce:**
    `print(100/200*300)`
    `print(300*100/200)`

**Minimal reproduction project:**
[MathSucks.zip](https://github.com/godotengine/godot/files/5321328/MathSucks.zip)

I can't even. Who knows how many of my formulas are compromised by this. Even if there was some kind of trick, why does it work one way and not the other?

**Comment by pajcek11** [comment]
fricking ints. do I now have to make sure that my ints never become 0 at any point? why can't math be math? I'm converting it to an int at the end either way...

**Comment by akien-mga** [comment]
That's integer division, it's normal. Use float, or work with integral results.

**Comment by pajcek11** [comment]
yea, I just added .0 to one of the numbers... sigh... 
This is why javascript is superior.. just plug and play and everything works always.
