### ISSUE TITLE
Refactoring suggestion: making GDScript an own library

### ISSUE THREAD

**Issue by sauer2** [godotengine/godot#4252]
Another wild suggestion: It seems like some people are reluctant to use GDScript for the reason that they can't reuse it elsewhere.

So why not make it its own library so they actually can reuse it in their own engines or games? They'd even have game specific functionality, like built in vector types.

I guess that'd require
- [ ] moving/generalizing too Godot-specific features
- [ ] packaging it
- [ ] ???
- [ ] profit

As mentioned in the particle issue, I'm not even using Godot atm, so, yeah, I'm quite the Idea Guy™ here, sorry.

**Comment by neikeq** [comment]
I remember some months ago @reduz proposed doing this. The conclusion was that doing so is kind of pointless since we already have Python. GDScript seems easier to bind though.

**Comment by bojidar-bg** [comment]
@sauer2 ~ Note that both of your issues fall to different extend under the [first and last points of the "Great idea" question in the FAQ](http://docs.godotengine.org/en/latest/reference/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think)

**Comment by sauer2** [comment]
@neikeq That was a pretty bad conclusion that time, to be honest. Because Python

- is only remotely similar to GDScript,
- is hard to sandbox (aka "comes with batteries included"),
- you can only have one instance (Referring to CPython, but as far as I know, TinyPy is completely outdated and unmaintained, jia-mini-python is some obscure thing aimed at ObjectiveC mobile apps and MicroPython aims at embedded boards and its API is a mess, so there is no such thing as mpython, compared to mruby.) and
- the CPython developers don't seem to care for startup times and raw single threaded performance in general

@bojidar-bg That's ok. That said, the first point on this list is somewhat broadly vague and could even cover bug fixes.

**Comment by mhilbrunner** [comment]
@neikeq I'd close this. If in the future somebody steps up who sees value in doing this and wants to do it, it can be reopened. As it is, there was no discussion for ~1.5 years.

**Comment by akien-mga** [comment]
Yeah, I don't see any added value in doing this, just a lot of work.
