### ISSUE TITLE
Imported animations influence all bones in spite of empty tracks

### ISSUE THREAD

**Issue by automatrio** [godotengine/godot#42533]
Godot v3.2.3

I made a character in Blender 2.9 and rigged it with Rigify. I exported an embedded .gltf with only the deformations bones and imported it in Godot with each animation to a separate file and "enable custom tracks" checked. Some of the animations control the hips, whereas others control the upper body. I deleted all the keyframes on the corresponding unused tracks of each animation, but they still seem to influence all bones. Because of this, a lower body animation cannot be combined to an upper body animation, which is odd because a previous attempt with a custom simpler rig did work.

I'm attaching the .gltf file. It's free to use, btw, if anyone can get it to work.

Steps to reproduce:

Import the .gltf file in Godot using the necessary presets and give it a go.

[Alphred.zip](https://github.com/godotengine/godot/files/5321752/Alphred.zip)

**Comment by fire** [comment]
The animation import keys all the tracks even if they're empty, look into animation tree blending.

**Comment by automatrio** [comment]
That got it working, thanks!

I'll leave here how it's done, in case somebody else runs into the same issue:

Create an AnimationTree node within the scene that contains the AnimationPlayer you'll be adressing.

![explain001](https://user-images.githubusercontent.com/72306665/94998322-7a915200-0587-11eb-9d6c-10f9a3880213.png)

Choose the AnimationPlayer in the Properties and choose AnimationNodeBlendTree as the root. There are other options with different capabilities, and you can read about them in the documentation:
[https://docs.godotengine.org/en/stable/tutorials/animation/animation_tree.html](url)

![explain002](https://user-images.githubusercontent.com/72306665/94998332-8e3cb880-0587-11eb-938e-ff6979104182.png)

Create nodes for the animations and a Blend2 one. In the Edit Filters box, check the bones that'll be excluded from the animation you connected to the "in" slot.

![explain003](https://user-images.githubusercontent.com/72306665/94998400-ec699b80-0587-11eb-8fa1-10647fc4edcc.png)

Finally, back on the Properties panel, enable Active to start playback.

I still have to figure out how to adress the AnimationTree via script, but that shouldn't be too hard.
