### ISSUE TITLE
Calling a puppet function from server causes an error on masters

### ISSUE THREAD

**Issue by samthemagicman** [godotengine/godot#42536]
**Godot version:**
3.2.3

**Issue description:**
When you have an authoritative server where server_relay is false and then you call an RPC function from the server where the clients have it as a puppet, it causes an error like "RPC {function} is not allowed on node {node} from: 1. Mode is 3, master is 101012031", when the master has no need to call the puppet function anyway.

**Steps to reproduce:**
1. Create one Godot project with NetworkMultiplayerENet and set server_relay to false
2. Create another Godot project and create any type of puppet function. Connect this client to the server, and set this client as a master on the server and client.
3. Let the server call the puppet function

**Minimal reproduction project:**
[ServerClientPuppetError.zip](https://github.com/godotengine/godot/files/5321938/ServerClientPuppetError.zip)

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
There are errors in the user code, starting from the fact that the one called Server created the client and the one called Client creates the server. The code is indeed causing the server `1` to call a method `test_client_puppet` on the client `ID`, but that method is flagged as `puppet` and the network master is the client.
Closing.
