### ISSUE TITLE
CanvasLayer Node Missing

### ISSUE THREAD

**Issue by MSZAL** [godotengine/godot#42549]
**Godot version:**

v3.2.3.stable.official 64bit

**OS/device including version:**

Windows 10

**Issue description:**

In the "Create New Node" menu, the CanvasLayer node is missing. 

**Steps to reproduce:**

In any project, in "Create New Node" menu, it is missing the CanvasLayer node.

![image](https://user-images.githubusercontent.com/14929629/95007029-6291f080-05d0-11eb-96c5-a3f7c4682437.png)
![image](https://user-images.githubusercontent.com/14929629/95007051-9a993380-05d0-11eb-9667-d31790a22d83.png)

I was a following tutorial for showing a HUD corresponding to the camera and to use this node. I cannot find any mentions of this node being removed. Still appears in the docs as well https://docs.godotengine.org/en/stable/classes/class_canvaslayer.html#class-canvaslayer

**Minimal reproduction project:**

Any new or existing project

**Comment by volzhs** [comment]
![Screenshot_20201004_141849](https://user-images.githubusercontent.com/8281454/95007614-87c44480-064c-11eb-90a5-94450aae6149.png)
just tested with 3.2.3 stable official.

![Screenshot_20201004_142019](https://user-images.githubusercontent.com/8281454/95007644-c1954b00-064c-11eb-83f4-335976fdad97.png)
it seems `CanvasLayer` node is disabled at Editor > Manage editor features

**Comment by MSZAL** [comment]
That solved the issue. I must have accidentally disabled it when creating a profile. Thank you.
