### ISSUE TITLE
Godot 3.2 GLES2 macOS + HTML5 stuttering (some frames idle time > 60 ms)

### ISSUE THREAD

**Issue by stefanbaur-neugelb** [godotengine/godot#42555]
**Godot version:**
3.2.3.stable
**OS/device including version:**
MacOS Catalina 10.15.7 
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
CPU: 3,1 GHz Dual-Core Intel Core i5
RAM: 16 GB 2133 MHz LPDDR3
GFX: Intel Iris Plus Graphics 650 1536 MB 

Backend: GLES2

**Issue description:**
Game (even empty project) is stuttering. Getting spikes with frame times > 60 ms, whilst most frames have < 1ms when selecting GLES2 renderer. For GLES3 all frames stay < 1ms and everything runs smooth. HTML5 export seems to have the same issue.
Note that there are no scripts running / no expensive rendering going on. It is purely the engine running.

Profiling GLES2: Very slow frames!
<img width="914" alt="Bildschirmfoto 2020-10-04 um 11 09 35" src="https://user-images.githubusercontent.com/34034651/95011612-1b3c4c00-0632-11eb-857b-c4578f4c71ee.png">

For comparison GLES3:
<img width="922" alt="Bildschirmfoto 2020-10-04 um 11 17 50" src="https://user-images.githubusercontent.com/34034651/95011746-407d8a00-0633-11eb-9da1-1f6384d4f1be.png">

In order to make sure it is not vsync related, provfiling with vsync disabled
GLES2:
<img width="927" alt="Bildschirmfoto 2020-10-04 um 11 22 00" src="https://user-images.githubusercontent.com/34034651/95011824-d5808300-0633-11eb-98bb-0ac2179c9b49.png">
Note: you can clearly see the spikes > 60ms once or twice every 12-16 frames

For comparison GLES3:
<img width="929" alt="Bildschirmfoto 2020-10-04 um 11 19 43" src="https://user-images.githubusercontent.com/34034651/95011784-82a6cb80-0633-11eb-82e8-9ac14d7706cf.png">
Most frames < 1ms, only one random frame with still perfect 14ms

**Steps to reproduce:**
Seeing the same behavior already in a empty Project:
Start from a empty project, GLES2 backend. Create a empty Node2D. Start profiling.

**Minimal reproduction project:**
Plain default template with empty Node2D already shows this behavior.

**Comment by lawnjelly** [comment]
See also several issues related to performance problem on some Macs, including:
#39758
#17584

**Comment by Zireael07** [comment]
I am sure a similar issue (spikes on empty project) was already reported, but I can't find it atm.

**Comment by Faless** [comment]
The HTML5 version and the MacOS one share very little platform code. I doubt the two things are related unless it's a driver issue with some GL function which is used by both the desktop version (GLES2) and the browser (WebGL).
Also worth mentioning that you can't disable vsync in HTML5 since the rendering is done in the animation frame callback from the browser.

**Comment by lawnjelly** [comment]
See #39758 for a test build with a possible fix. (Note the test build is GLES3 but is easy to extend to GLES2).

**Comment by akien-mga** [comment]
Fixed by #42734.
