### ISSUE TITLE
Area2D mouse_entered signal not working

### ISSUE THREAD

**Issue by scyq** [godotengine/godot#42554]
**Godot version:**

v3.2.3.stable.official

**OS/device including version:**

OS: macOS Catalina 10.15.6
OpenGL ES 3.0 Renderer: AMD Radeon Pro 5500M OpenGL Engine

**Issue description:**

I created a 2D node, which contains Sprite, Area2D and CollisionShape2D under Area2D. This node is a card, I want to make an effect, once the cursor is moved up, its scale will change. I used the mouse_entered and mouse_exited signals of Area2D. But when I instantiate it in another node, it's not working.
I am sure I enabled pickable option.

**Steps to reproduce:**
1. Create a 2D node as root, there are sprite, Area2D under it.
2. Create a CollisionShape2D under Area2D.
3. Connect mouse_enterd signal and mouse_exited to GDscirpt.
4. The effect works on Scene Test but not working on the nother Scene

**Minimal reproduction project:**

[gd.zip](https://github.com/godotengine/godot/files/5322892/gd.zip)

**Comment by Zireael07** [comment]
Probably some side effect of collision shapes being shared by default?

**Comment by KoBeWi** [comment]
Background is blocking your mouse input. Set the `mouse_filter` to `Ignore`.
