### ISSUE TITLE
Euro sign can not be displayed by a Label

### ISSUE THREAD

**Issue by SirMoM** [godotengine/godot#42562]
**Godot version:**
3.2.3-stable

**OS/device including version:**
Windows 10 GPU: NVIDIA GeForce GTX 1050 Ti

**Issue description:**
The Label can't display the euro sign €.
It is not working via code nor through the editor.

**Comment by volzhs** [comment]
you need a font file for it.
![Screenshot_20201005_011015](https://user-images.githubusercontent.com/8281454/95020684-8aa05300-06a7-11eb-8287-7d9502286ccb.png)

**Comment by Calinou** [comment]
Closing per @volzhs's comment. See also https://github.com/godotengine/godot/pull/39603 which will remove the need to use a custom font to display characters not present in the default bitmap font.

**Comment by bruvzg** [comment]
For the reference, default Bitmap font include only 0x20-0x7E and 0xA0-0xFF Unicode characters.

![hidpi](https://user-images.githubusercontent.com/7645683/95021933-a5110700-067c-11eb-9174-710df9e27520.png)
