### ISSUE TITLE
[C#] Instancing a class that inherits from node crashes

### ISSUE THREAD

**Issue by ninjanomnom** [godotengine/godot#42566]
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
With execution never being halted:
https://pastebin.com/udM7Djdq

With a breakpoint on `NativeCalls.godot_icall_CanvasLayer_Ctor(this);` (IL code):
https://pastebin.com/VJaubNHc

When attempting to instance a class that inherits from ~~CanvasLayer~~ Node it immediately causes a native crash. This doesn't happen in a fresh project and I've not been able to figure out what exactly causes a project to start behaving in this way. Instancing a ~~CanvasLayer~~ Node directly doesn't have any issues.

# Update: This is caused by the main assembly getting loaded multiple times, which shouldn't be happening.

**Steps to reproduce:**
~~Take the project at the commit below and run until [Setup.cs#104](https://github.com/ninjanomnom/ScientiaMagica/blob/57cb10c0e52bcda7be2854da74097a1c99a222a3/ScientiaMagica/src/Setup/Setup.cs#L104), next step causes a native crash.~~
Run the project in the zip below, it crashes when it attempts to instance the child class

.**Minimal reproduction project:**
~~Not as minimal as it could be but isn't *too* large
https://github.com/ninjanomnom/ScientiaMagica/tree/57cb10c0e52bcda7be2854da74097a1c99a222a3~~

EDIT: Actualy minimal reproduction [MinimumCrashReproduction.zip](https://github.com/godotengine/godot/files/5329484/MinimumCrashReproduction.zip)

**Comment by ninjanomnom** [comment]
I've done some more experimenting to try and figure out what's causing the issue here and came upon some more weird behavior. In my code I have the following where `TestChild` is a child of `CanvasLayer`

```
var test = new CanvasLayer();
var testChild = new TestChild();
//other code
```

If I step into line 1 it crashes but if I let it run to line 2 it doesn't. On line 2 though, when it instances `TestChild` it crashes even if I don't step into it. Inside the `CanvasLayer` constructor if I put a breakpoint on *any* line it will run to that point then crash:

```
public CanvasLayer()
      : this(false)
    {
      if (!(this.ptr == IntPtr.Zero))
        return;
      this.ptr = NativeCalls.godot_icall_CanvasLayer_Ctor(this);
    }
```

Of the 3 lines in this constructor, a breakpoint on any line will be reached before crashing and halting all execution. Thinking this may be an issue with the debugger I ran the code without debug symbols in release mode but godot still crashes, assumingly in the same fashion. Even though it seems the code will run to the next breakpoint before crashing, in the first code example a breakpoint on `//other code` will never be reached and godot crashes before finishing instancing `TestChild`

If I let it run entirely on its own without halting execution until crash I get this stacktrace instead:
https://pastebin.com/udM7Djdq

**Comment by ninjanomnom** [comment]
In the end it turned out to be more of a C# problem, kinda. An assembly shouldn't be getting loaded multiple times but the hard crash without an exception may be an issue that should be handled at a lower level.

**Comment by akien-mga** [comment]
Did you mean to close this?

**Comment by ninjanomnom** [comment]
Yes, it isn't an issue that godot should be fixing. The proper place would be in either mono or the build tools.
