### ISSUE TITLE
Godot can't find plugin.cfg files in addons sub-sub-folders

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#42572]
**Godot version:**

3.2.3

**OS/device including version:**

Windows

**Issue description:**

I need to have my plugins in sub-sub-folders of `addons/` folder.
Say `addons/me2beats/a/a.gd`, `addons/me2beats/b/b.gd` etc

One of the reasons for this may be that I would not want a conflict of plugin names with plugins from other developers.
Another reason is that there can be a lot of plugins (say, several hundred small plugins) which I'd like to logically divide into subfolders.

The issue is Godot in this case can see `plugin.cfg` files only in `addons` and `addons/me2beats`, 
and it doesn't go deeper for some reason (maybe so Godot doesn't run recursively through all  `addons/` subfolders)

- this limitation is not specified anywhere in the documentation.

- it is possible to create plugins in `addons/` sub-sub-folder with `Create a plugin` dialog (see below).
The plugin file and cfg file are generated correctly, but the plugin cannot be found.

**Steps to reproduce:**
- Create a plugin with `Create a Plugin` (`Project` - `Project settings` - `Plugins` - `Create a Plugin`),
- in `Subfolder` field specify sub-sub-folder using `/` for example `a/b` or `sub/subsub`.
- As you will see, sub and sub-sub folders created, `plugin.cfg` and `plugin.gd` created too but godot doesn't see this plugin

![subsubfolder](https://user-images.githubusercontent.com/16458555/95076693-b107d200-072b-11eb-89a4-dafb779e7a59.JPG)

**Minimal reproduction project:**

**Comment by Xrayez** [comment]
It's likely that it's not a feature currently, but as you said, it lacks documentation, so I'd assign `documentation` label, and/or transfer this issue to the GIP repository, or create a new proposal.

I've just written a similar proposal for the `custom_modules` build option (much like `addons` but in C++): godotengine/godot-proposals#1619, so this could be similarly applied for the `addons` to add a recursive plugin search option is the editor settings, for instance.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/43734, closing.
