### ISSUE TITLE
Linking polygon2D points to bone2D goes wrong

### ISSUE THREAD

**Issue by edaojs** [godotengine/godot#42576]
**Godot version:**
Godot Engine v3.2.3.stable.official
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics
OpenGL ES 2.0 Batching: ON

**OS/device including version:**
Processor: Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 CPUs), ~2.1GHz
Memory: 4096MB RAM
Card name: Intel(R) HD Graphics
Chip type: Intel(R) HD Graphics (Core i3)
DAC type: Internal
System: Windows 7 Professional x64

**Issue description:**
When I try to link a few polygon2D points to a bone2D the sprite gets distorted. If I link all the points, the image disappears
Video: https://youtu.be/oqmed2EWGog

**Steps to reproduce:**
Open "Player.tscn, Select LegR object and click over UV. On UV editor, select Bones and select the bLegR bone. Select a few points and click "OK". 

**Minimal reproduction project:**
[GodotTest.zip](https://github.com/godotengine/godot/files/5328458/GodotTest.zip)

**Comment by Calinou** [comment]
This is a very old graphics adapter. I wouldn't expect any OpenGL 2.0+ renderer to run correctly on it.

**Comment by lawnjelly** [comment]
I don't know if this is a rendering issue or an editor issue, but just in case it is a rendering issue, try the latest build in #42119. This should deal with problems where the GPU does not support the skinning shader. I've only seen reports of this on android, but it could occur on other hardware.

The unified batching has a new software transform path for 2d skinning (you can turn it on and off in `projectsettings->rendering->quality->2d->use_software_skinning`).

If this doesn't fix it, then it may be an editor issue.

**Comment by edaojs** [comment]
> I don't know if this is a rendering issue or an editor issue, but just in case it is a rendering issue, try the latest build in #42119. This should deal with problems where the GPU does not support the skinning shader. I've only seen reports of this on android, but it could occur on other hardware.
> 
> The unified batching has a new software transform path for 2d skinning (you can turn it on and off in `projectsettings->rendering->quality->2d->use_software_skinning`).
> 
> If this doesn't fix it, then it may be an editor issue.

I visited the build in #42119 and download the GLES3 Batching version 0.15.
It solved the problem. Thank you very much!
Should I close the issue here ?

**Comment by edaojs** [comment]
> I don't know if this is a rendering issue or an editor issue, but just in case it is a rendering issue, try the latest build in #42119. This should deal with problems where the GPU does not support the skinning shader. I've only seen reports of this on android, but it could occur on other hardware.
> 
> The unified batching has a new software transform path for 2d skinning (you can turn it on and off in `projectsettings->rendering->quality->2d->use_software_skinning`).
> 
> If this doesn't fix it, then it may be an editor issue.

I visited the build in #42119 and download the GLES3 Batching version 0.15.
It solved that problem, but created another problem. The bones rotation doesn't work properly.
Maybe the problem is my GPU, but everything works fine in DragonBones.
Could you try to run my attached project? If it works well for you, then I'll need a new notebook.

**Comment by lawnjelly** [comment]
It's more likely there is a small bug in the new 2d software skinning.

There was a small area where I resorted to guesswork, I only had one test project, so it should be quite simple to fix when I have more test cases. Basically the case was where the weights didn't add up to 1.0, or when no weights were applied. I'm really waiting on testing to identify the correct way of doing this, you are the very first tester!

When I tried your project yesterday it seemed the same between the software and old path, but I didn't try bone rotation I'll have a look. :+1: 

I'm pretty sure you don't need a new notebook. :smile:

**Comment by edaojs** [comment]
@lawnjelly I appreciate your help. I really need Godot for this project, it will be impossible to make it in Love2D.
Maybe the video wasn't clear enough, but now I've put some subtitles, I think the bug is clear to see.
new video: https://youtu.be/J7u6Fkg5zwA
Just let me know if it is not enough , then I will try to make a new video or a new project.

**Comment by lawnjelly** [comment]
Yeah I think I see what is going wrong, but I need a project with the vertices weighted to the bones so I can debug it.

**Comment by edaojs** [comment]
@lawnjelly there it goes.
just open the project and click "play"
[GodotTest.zip](https://github.com/godotengine/godot/files/5335550/GodotTest.zip)

you should see something like this:
![attack](https://user-images.githubusercontent.com/61250724/95238309-b4f52c00-07df-11eb-926d-d6a0f34be7ec.gif)

**Comment by lawnjelly** [comment]
Thanks! :+1: I'm debugging it at the moment.

Getting skinning working is always a bit finicky and there are a few transforms available and with no comments in the code it's a case of trial and error to work out what each does and fit them together in the right order. I'm confident it should work fine though once I've cracked it .. it might be in a few days though, as I have to go away from home again.

Once it is working I'll do another build.

**Comment by lawnjelly** [comment]
Back home and after spending some time this morning I've finally tracked this down. It was down to an offset on the polygons used to rig the model. God only knows why it actually works in the original shader version lol. :rofl:

And actually I there is a AABB bound check somewhere else pre-existing in the CPU side code for culling that doesn't take this into account which may also be buggy I'll double check this, fix two bugs at once kind of thing.

I'll possibly do a bit of rearranging to make it more efficient, then will need to rebase the PR after Pouley's skinning, then see if I can make a new build for testing. :+1:

**Comment by edaojs** [comment]
@lawnjelly thank you for replying.
It still weird... the skins are stretching when I move the bones. 
Sadly, I tested the same code on my nephew's PC, and it was running perfectly!
I need a new notebook.  
Anyway, thanks for your help. I appreciate

**Comment by lawnjelly** [comment]
Double check you have 2d skinning switched on in build 0.16. I'll check I haven't made some mistake in the build. If you are running the test project you gave me, it should either run completely correctly or not at all.

There should be no situation with skin stretching possible using that path, unless you are using a different project (in which case there may be another bug to fix). This is very likely a mistake on my side.

It is very unlikely your computer is at fault. With software skinning the calculations are done on the CPU, and all CPUs can do this. The GPU is only showing on the screen the positions calculated on the CPU. This is very different from GPU skinning, where huge variations in hardware can lead to the process failing.

**Comment by edaojs** [comment]
@lawnjelly the option "use software skinning" was unchecked !
I checked and it works perfect now! Thank you very much!

**Comment by lawnjelly** [comment]
Yay!! :grin:

**Comment by akien-mga** [comment]
Fixed by #42119.
