### ISSUE TITLE
Favorites from a deleted project in a new one with the same name

### ISSUE THREAD

**Issue by MPWrobel** [godotengine/godot#42578]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
macOS Catalina 10.15.5

**Issue description:**
When you delete a project and create a new one with the same name in the same folder, Godot uses favorites from the deleted project. The same might be true for some of the cache files stored in " /Users/marcin/Library/Application\ Support/Godot/projects". 

**Steps to reproduce:**
1. Create a new project
2. Create a new folder
3. Create a new scene and save it in the folder
4. Add scene to favorites
5. Save the project and close Godot
6. Delete the project folder
7. Open Godot and remove the missing project
8. Create a new project with the same name in the same folder

**Comment by pycbouh** [comment]
This is because the project-specific editor data is stored for each unique project path. And it is never removed, unless you go into the editor data directory and manually delete it. This will be fixed in #42394 by moving this data in a special folder at the project root.

**Comment by MPWrobel** [comment]
> This is because the project-specific editor data is stored for each unique project path. And it is never removed, unless you go into the editor data directory and manually delete it. This will be fixed in #42394 by moving this data into a special folder at the project root.

Thank a lot for the response! I guess I can close this issue then.
