### ISSUE TITLE
CollisionPolygon2D not updating when debugging collisions

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#4260]
**Issue description** (what happened, and what was expected):
Changing a the points/segments of a _Convex/ConcavePolygonShape2D_ during the game should update the shape if _Visible Collision Shapes_ is enabled. It works fine with _CollisionShape2D_ but not with _CollisionPolygon2D_.

**Steps to reproduce:**
Enable _Visible Collision Shapes_ option and change the shape points/segments in game:

``` GDScript
var shape = body.get_shape(0)
var points = shape.get_points()
points[0] = Vector2(0, points[0].y - 10)
shape.set_points(points)
```

**Link to minimal example project** (optional but very welcome):
[SP_4260.zip](https://github.com/godotengine/godot/files/208556/SP_4260.zip)

Run the game with _Visible Collision Shapes_ enabled and click the _Change_ button:

![Screenshot](https://cloud.githubusercontent.com/assets/7718100/14354797/fc97fd14-fcde-11e5-9557-a2aad2a62b4d.png)

**Comment by neikeq** [comment]
It may be worth checking if the same issue happens in the spatial (3D) world with _CollisionPolygon_ and _CollisionShape_.

**Comment by reduz** [comment]
until we change how this works in 3.0 and break compatibility, it won't be possible to do it

**Comment by neikeq** [comment]
@reduz What's the status on this one? Has anything been done in regards to this? Should we change to a later the milestone?

**Comment by reduz** [comment]
debug is now on the polygon, and it's updated. closing.
