### ISSUE TITLE
100% Core utilisation on empty project

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#42601]
**Godot version:**
3.2.3 x64

**OS/device including version:**
Windows 7; OpenGL ES 3.0 Renderer: GeForce GTX 1050/PCIe/SSE2

**Issue description:**
A completely empty project when run uses 100% of a CPU Core. It's the compiled application that's doing it, not the editor, and it only does it when it's open; if I minimise the application the resource use goes to 0. Re-open the window (even in the background), and it's back to 100%.

It's not the debug component because I exported it into a .exe (using the defaults) and ran that, with and without DEBUG. Both exhibited the exact same behaviour.

Yet the Godot Editor itself doesn't exhibit this problem, and that being a Godot project...

This may seem minor but:
* It drains batteries faster.
* On a global scale across all installs, it may waste a fair amount of electricity and contribute to the environmental consequences thereof.

**Steps to reproduce:**
Start Godot Editor. Create a new project. Give it a "Node 2D". Save Scene. Run project (pointing to that scene as the "main" scene).

**Minimal reproduction project:**
See Repro steps

**Comment by Calinou** [comment]
> It's the compiled application that's doing it, not the editor,

This is expected. By default, the application will redraw as fast as it can, only limited by V-Sync.

**Comment by CitrusWire** [comment]
Thanks for the clarification (and explanation of Godots "compiling"); it's appreciated.

I understand what you're saying and it makes sense, but I would suggest the default should be changed for the aforementioned reasons. Then suggest to users what settings to tweak to get more smoothness on a documentation page about optimisation (one of https://docs.godotengine.org/en/stable/tutorials/optimization/ say).

I don't pretend to understand the behind-the-scenes stuff of either engine, but I have a basic Windows Unity game I created using their defaults and it uses 0.01% of my CPU when running when idling and just 1% when playing.

**Comment by clayjohn** [comment]
Do you have V-sync disabled? Either through ProjectSettings or through your graphics driver settings?

If you have V-sync enabled and you are still experiencing this issue, then it may be a bug. But we need way more information to be able to help you.

**Comment by bruvzg** [comment]
If you need behavior similar to the editor (e.g. UI app that does not need constant redraws/physics updates) you can enable low processor mode `Project Settings`→`General`→`Application`→`Run`→`Low Processor Mode` and adjust sleep interval to limit FPS (default value `6900` is about `144` FPS) `Project Settings`→`General`→`Application`→`Run`→`Low Processor Mode Sleep usec`

**Comment by CitrusWire** [comment]
The settings are Godot (Project) defaults. I've not fiddled with anything yet because I'm still new.

However, having looked, I can see that `display/window/vsync/use_vsync` is ticked.

Further testing:
Vsync disabled: GPU usage: 49%
Vsync enabled (the default it seems): GPU usage: 1.2%

CPU in both cases seems to be identical. So Vsync has nothing to do with CPU for me; GPU only.

**Comment by lawnjelly** [comment]
Sounds like the windows build needs profiling on an affected machine.

Indeed the CPU percentage should not be more than a couple percent on an empty project with vsync (when profiling linux this is the case for me, and the largest CPU draw is the audio if I remember right).

**Comment by luckyabsoluter** [comment]
Godot_v3.5-stable_win64
Laptop i3-8145U

[project setting]->[display/window/vsync/use_vsync] true (default true)
[project setting]->[display/window/vsync/vsync_via_compositor] true (default false)

It solved my problem.

By the way, empty project(without debug) has 3% cpu usage, so maybe there is another problem.

**Comment by luckyabsoluter** [comment]
In my case, `Low Processor Mode` reduce cpu usage.
However, if you go to game scene from empty scene and then go to empty scene again, cpu usage is high (30%).
It is cpu leaking.

**Comment by lawnjelly** [comment]
See #53463 .
`editor_settings/interface/editor/show_update_spinner` set to true.
Then left click on the update spinner in the top right, and choose `update_vital_changes`.

This should hopefully reduce CPU quite a bit for you. The other CPU hog is the audio. I did a PR to fix this #63458 , but it has not been progressed to merging (I think Juan wants to research this more).

You can also run with the dummy audio server in the editor with a command line option.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/39758, which is essentially the same issue.
