### ISSUE TITLE
Visual Shader Editor - Can't close code preview on low-mid res display

### ISSUE THREAD

**Issue by tvardero** [godotengine/godot#42612]
No dupes of this issue were found with search. Or i can't search things. Either of these.

**Godot version:**
v3.2.2.stable.official from godot website.
Win10 x64
Screen resolution 1366 x 768 (laptop Dell Inspiron 5558)

**Issue description:**
Can't close code preview because it overlays the button that opens/closes it.
Also there is no "X" button to close code preview.
![image](https://user-images.githubusercontent.com/45442278/95321654-0830b280-08a4-11eb-9d63-3ef2d15c6891.png)
![image](https://user-images.githubusercontent.com/45442278/95321681-11218400-08a4-11eb-92cc-dec10e6f37e4.png)

Only solution to close the code preview is to stretch inspector and sceene-manager side windows as much as possible, BUT IT WON'T HELP with much smaller screen resolutions:
![image](https://user-images.githubusercontent.com/45442278/95321865-504fd500-08a4-11eb-8529-42a20e0c9d11.png)

**Steps to reproduce:**
Open blank project, enter visual shader editor on 1366 x 768 or narrower resolution. Open code preview.

**Comment by Chaosus** [comment]
Well, I could change the place of its button to the place at the right of the mode selector, but then someone will complain about the unavailability of the value box of grid snapping...

**Comment by timothyqiu** [comment]
The minimum width of the preview box is 400, which seems arbitary. What about allowing the user to close the preview box by resizing it to a very small width? Then the order of controls won't matter.

**Comment by groud** [comment]
To be honest I believe this is a design error. The button to switch between the two panels should not be inside one of the panels. Either we attach it to the right side somewhere, but it might overlap with the other buttons, or we simply move most menu and buttons to a toolbar.
