### ISSUE TITLE
_get_alloc_size_checked behavior

### ISSUE THREAD

**Issue by punto-** [godotengine/godot#4262]
during initialization, there's a call to "_get_alloc_size_checked(6, &alloc_size)", which is returning "true", but the value stored in alloc_size is 0. This is on Vector<T>::resize() (line 277). The alloc size 0 is causing the function to return with ERR_OUT_OF_MEMORY.

Only happens on a release build (debug works), with a clang compiler.

Could this be the cause of the ios issue?

**Comment by akien-mga** [comment]
> Could this be the cause of the ios issue?

The mentioned issue being: #4190.

It sounds like a potential culprit indeed, as it seems indeed to happen only when building binaries with a certain build environment. (One user reported having good binaries when building for iOS with OS EL CAPTION 10.11.4, IOS SDK 9.3).

**Comment by punto-** [comment]
I worked around by disabling the overflow stuff and using
nearest_power_of_2() on my build (I don't know which one is broken tho)

**Comment by est31** [comment]
@punto- hmm can you try to find out with which parameters `nearest_power_of_2_templated` gets called?

And what is `sizeof(size_t)` for IOS?

**Comment by akien-mga** [comment]
Should some more work be done on this `nearest_power_of_2_templated` for 2.2, or are we happy with the current situation?

**Comment by est31** [comment]
I'm waiting for @punto- to answer the question here.

**Comment by akien-mga** [comment]
I guess we're happy with it... :)
