### ISSUE TITLE
Inconsistent use of "real" and "float"

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#42633]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 7

**Issue description:**
Godot uses the `float` type - https://docs.godotengine.org/en/stable/classes/class_float.html#class-float

Yet in a few places within Godot, this is changed to `real`.
Examples:
* PoolRealArray - https://docs.godotengine.org/en/stable/classes/class_poolrealarray.html
* Connect a Signal to a Method Dialog -> Advanced -> "Add extra call argument" type box has "real", no float.

Not everyone is going to know these are synonyms in Godot:
a) If they don't have a background in software dev/CS, the user probably won't know they're related.
b) Some languages use them as different data types (i.e. SQL) so it's not a automatic given they're synonyms.

**Steps to reproduce:**
n/a

**Minimal reproduction project:**
n/a

**Comment by Calinou** [comment]
`real` was renamed to `float` in the `master` branch, but we can't do this in 3.2.3 without breaking backwards compatibility.

**Comment by CitrusWire** [comment]
Just found this and it's in /latest/ docs too - don't know if it's an engine issue or docs issue or both:

https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html

```
match typeof(x):
    TYPE_REAL:
        print("float")
```

**Comment by akien-mga** [comment]
Docs haven't been updated yet for 4.0 on purpose, it will be done once the master branch is closer to alpha.

**Comment by CitrusWire** [comment]
Ok, thanks. I did check class_poolrealarray.html on /latest and it wasn't there so figured they'd been updated. Also, the /latest/ docs themselves do say: "This is the documentation for the development (master) branch" but I guess that's godotdocs master rather than godotengine master.
