### ISSUE TITLE
The scaling for ' set resolution ' is buggy and creates weird shadows on the character ( not sure what name . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot#42638]
**Godot version:**
Godot 3.2.3, latest version . .

**OS/device including version:**
Windows 10, nVidia 1050 GTX Ti . .

**Issue description:**
I want my game to run in 1280x720p, by default, render it in that resolution, then scale it, using the settings in project settings, under ' visuals ', stretch mode, here are . .
<img width="478" alt="Skærmbillede (495)" src="https://user-images.githubusercontent.com/61069740/95449331-e77c6180-0964-11eb-8bd9-6ae2e08cd30e.png">

However, when I do that, something weird happens, for the shadows, when the monitor is running at, 4K, ie. it scales the original render, from 1280x720, to 4K, weird shadow lines . . .
<img width="500" alt="Skærmbillede (492)" src="https://user-images.githubusercontent.com/61069740/95449343-ecd9ac00-0964-11eb-900d-367f8b74348e.png">

I'm not sure what happens, I set it to render game first, in 1920x1080, which is exactly HALF, of 4K, so I would assume the problem didn't occur, when I did that, ie. there would be no dithering, or interpolation, however the same lines occur . . I THINK there's a bug in the up-scaling method, that causes these things, it shouldn't happen when scaling from Full HD, to 4K, since it simply means, each pixel becomes 4 pixels, and should look the same, as the 1080p image . . It looks a bit weird, for my games, I was wondering if it was a bug, again not sure . . .

**Steps to reproduce:**
Make a 3D game, set resolution to 1280x720p, and play it with settings above, on a 4K monitor, same problem, for 1080p, where there is no scaling issues, ie. one simply needs to make 1 pixel, fit inside 4 pixels, for scaling to work, or so . . It looks a BIT ugly, so I hope it might be fixed, with a better scaling algorhitm <3

**Minimal reproduction project:**
Uhhmm, see images above, not sure how to upload it . .

Link, to exported example game, 30 mb . . .
https://1drv.ms/u/s!Ar-BMFbxklUbhEucwWBvon4dmi3E?e=t2rwGO

**Comment by jasperbrooks79** [comment]
Add: Tried setting my monitor to resolution, of 720p, then playing game . . The same thing happens, the shadows look weird, or dithered, instead of smooth, when I look in the game engine window, before pressing ' run scene ', even at 4K, it looks like the shadows are made of ' small dots ', instead of a smooth curve, not sure . . . .

**Comment by Calinou** [comment]
Use the `2d` stretch mode if you don't want the viewport to be scaled.

**Comment by jasperbrooks79** [comment]
Thanks . . <3
