### ISSUE TITLE
Tabs are not highlighted when selecting in RichTextLabel

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#42656]
**Godot version:**

3.2.3

**OS/device including version:**

Windows

**Issue description:**

Tabs are not highlighted when selecting text in `RichTextLabel`.

**Steps to reproduce:**
1. create a `RichTextLabel`, set `selection_enabled` to `True`
2. Fill `RichTextLabel` with text that has tabs like this (you can just copy-paste it)
```gdscript
		hello		world
```
3. Select the text in this `RichTextLabel` using mouse

As you can see tabs areas are not highlighted
(but the text is selected with tabs - you сan verify this when `Ctrl+C` and `Ctrl+V` the selected text somewhere)

This is true for `Output Log` as well since it is a `RichTextLabel` so you could just
```gdscript
func _ready():
	print("		hello		world")
```
![tabs-editor-log](https://user-images.githubusercontent.com/16458555/95519483-98731280-09de-11eb-9c9d-fe89dc5a87b0.JPG)

Expected result when selecting the text:
![expected](https://user-images.githubusercontent.com/16458555/95520115-08ce6380-09e0-11eb-8923-8fb17acc1a5c.JPG)

**Minimal reproduction project:**

**Comment by torabshaikh** [comment]
Hi @Calinou I want to contribute to the project and this looks like a good place to start from. Can you please guide me on this?

**Comment by Calinou** [comment]
@torabshaikh Thanks for your interest in contributing :slightly_smiling_face: 

The RichTextLabel node's code is at [scene/gui/rich_text_label](https://github.com/godotengine/godot/blob/master/scene/gui/rich_text_label.cpp). Search for `selection_bg` (background color) and `selection_fg` (foreground color) to find the code that draws the selection.

See [this page](https://docs.godotengine.org/en/latest/development/compiling/) for compilation instructions. Remember to open the pull request against the `master` branch . This means that to test your changes, you need a GPU that fully supports Vulkan. If your GPU doesn't support Vulkan, work from the `3.2` branch, commit your changes, switch to the `master` branch and use the `git cherry-pick` command to pick the latest commit of the `3.2`-based branch you've made.

**Comment by torabshaikh** [comment]
@Calinou Thanks for the info. I have set up the development environment and started debugging the code. I will submit a PR soon.

**Comment by bruvzg** [comment]
Fixed in `master` by #44487: 

https://user-images.githubusercontent.com/7645683/105685926-4efff200-5eff-11eb-8b4a-87194461c3a3.mov
