### ISSUE TITLE
Godot 3.2.3 Mono Breaks with Latest Nvidia Drivers on Arch-Linux

### ISSUE THREAD

**Issue by TrainDoctor** [godotengine/godot#42655]
**Godot version:**
3.2.3

**OS/device including version:**
Arch Linux, RTX 2070 Super, GLES3

**Issue description:**
After updating my Nvidia drivers (both nvidia and nvidia-utils packages) I suddenly got this error:
```console
[traindoc@archpc ~]$ godot-mono
Godot Engine v3.2.3.stable.mono.official - https://godotengine.org
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  34 ()
  Value in failed request:  0x0
  Serial number of failed request:  29
  Current serial number in output stream:  30
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  34 ()
  Value in failed request:  0x0
  Serial number of failed request:  29
  Current serial number in output stream:  30
ERROR: initialize: Condition "ctxErrorOccurred || !p->glx_context" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:190.
ERROR: initialize: Condition "!p->glx_context" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:177.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles2/rasterizer_gles2.cpp:166.
Your video card driver does not support any of the supported OpenGL versions.
Please update your drivers or if you have a very old or integrated GPU upgrade it.
```

I have never received this error before on any system using Godot ever before. I have been moving my development environment over to linux and encountered no issues doing so until this driver update. 

I am reporting this as a bug here because I know this is likely on nvidia, but I wanted to bring this to the attention of the Godot team at large.

**Steps to reproduce:**

- Arch-Linux installed with xorg, light-dm, xfce4 and nvidia drivers.
- [Package List](https://pastebin.com/zqAiD12j)

1. Have the latest nvidia drivers, or if you have old drivers, update them to versions; nvidia: 455.28-3 nividia-utils: 455.28-1
2. Install Godot Mono
3. Attempt to launch godot (from console) and observe the above error.

**Note:**
I was able to downgrade to the previous driver versions and was able to run godot perfectly fine after the rollback by running this command:
```console
yay -U /var/cache/pacman/pkg/nvidia-455.23.04-3-x86_64.pkg.tar.zst /var/cache/pacman/pkg/nvidia-utils-455.23.04-1-x86_64.pkg.tar.zst
```
(or without yay)
```console
sudo pacman -U /var/cache/pacman/pkg/nvidia-455.23.04-3-x86_64.pkg.tar.zst /var/cache/pacman/pkg/nvidia-utils-455.23.04-1-x86_64.pkg.tar.zst
```

**Comment by akien-mga** [comment]
Did you reboot after installing the drivers? Nvidia drivers have a kernel component, a reboot is necessary. After an upgrade, any OpenGL application would fail.

**Comment by TrainDoctor** [comment]
> Did you reboot after installing the drivers? Nvidia drivers have a kernel component, a reboot is necessary. After an upgrade, any OpenGL application would fail.

I did not have the chance too and had forgotten this element. I will update, reboot and edit this comment with the results. I suspect you are completely correct and in-experience with nvidia drivers in relation to arch likely is the problem.
