### ISSUE TITLE
3d pan/zoom without middle mouse button should be optional

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4265]
**Operating system or device:**
Ubuntu

**Issue description** (what happened, and what was expected):
https://github.com/godotengine/godot/pull/4241 introduced ability to pan/zoom in 3d editor without middle mouse button, by simply holding shift/ctrl keys. Unfortunately this pr changes the way how panning/zooming is working for people that do have mouse and touchpad (or stylus) in the same time.
So it seems there should be an option in settings to turn on/off this functionality. 
Edit: It looks this behaviour is common for all users, independently if there is touchpad/stylus available or not.
**Steps to reproduce:**
**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Note to self: the fix for this issue should be cherry-picked for 2.0.3.

**Comment by quantum-entangler** [comment]
Yup, can confirm as issue. I have no touchpad/trackpad connected to my pc, only a wacom stylus, mouse and keyboard. Would be nice to have it be optional.

**Comment by kubecz3k** [comment]
It looks this behaviour is common for all users, independently if there is touchpad/stylus available or not. Info from irc:
> bojidar_bg: BTW, I have no touchpad whatsoever, only my mouse 
bojidar_bg: but I can still zoom in via Ctrl+mouse move
bojidar_bg: shift+drag works too

**Comment by quantum-entangler** [comment]
ok I figured out the view nav for trackpad, if I hold down alt then I don't get the trakpad nav i.e. works as I want & if I don't hold down alt then it works as trakpad nav. Duh.

**Comment by Zylann** [comment]
It just seems that in the 3D mode, modifiers keys (Ctrl and Shift) no longer require any other input to produce panning or zooming. As a general rule, modifier keys should never do anything on their own, because they are... well, "modifiers", "dead keys" :p

**Comment by volzhs** [comment]
> It just seems that in the 3D mode, modifiers keys (Ctrl and Shift) no longer require any other input to produce panning or zooming when the mouse moves.
**Now I accidentally change the view with Ctrl+S, Ctrl+D, or the usual Shift+drag, which is annoying**.

yes. it's really annoying to me.

**Comment by volzhs** [comment]
I tested 84d706c commit.
It still doesn't act like before trackpad things added.

I can zoom with mouse wheel scroll and orbit with mouse wheel down before.
Now, wheel scroll and wheel down move did same thing - zoom in/out.
I checked Trackpad Hint is off.

**Comment by Zylann** [comment]
Which are your settings?
I tested with these and I can pan with [wheel down+shift+move] and zoom with [wheel scroll]:
![Settings screenshot](http://zylannprods.fr/images/screen/godot/editor_settings_trackpad.png)

**Comment by volzhs** [comment]
@Zylann it works after set modifiers same as your settings.

**Comment by Zylann** [comment]
Is the issue resolved?

**Comment by akien-mga** [comment]
Yes. Fixed by  	84d706c.

**Comment by raould** [comment]
personally i find it confusing that the behaviour is so different between laptop trackpad vs. desktop mouse. i want to just do shift-move not shift-middlemouse-move for panning on the desktop.

**Comment by Zylann** [comment]
The difference comes from the controller. You don't want the same behaviour if you are using a different controller. The reasons are explained above. And if you still want this, the option is here for you.

**Comment by raould** [comment]
@zylann thanks, understood... up to the point of how do i make my desktop not require the extra use of the middle mouse button to get pan and zoom with shift and ctrl respectively? (I know i am crazy for wanting them. and i know it is weird for modifiers to do things on their own.) e.g. I don't have Trackpad Hints in my settings on desktop if that is the trick?  sorry and thanks :-)
![godot-settings-snip](https://cloud.githubusercontent.com/assets/77176/18969698/0bab01dc-8643-11e6-96e0-50c58b3b6ebd.PNG)

**Comment by Zylann** [comment]
Strange you don't have the option. Is it the latest Godot?

**Comment by raould** [comment]
"latest" in what sense? :-) i have current stable from the download page on the web site.
Godot_v2.1-stable_win32.exe

**Comment by Zylann** [comment]
Aaah it has been renamed to "emulate 3 buttons mouse" by b3b1fdae85f845d92d749ec268877b87bb9bc47a.

**Comment by raould** [comment]
THANKS! woot.
