### ISSUE TITLE
Vulkan: `CanvasItem.draw_texture_rect()` tiling does not work as expected

### ISSUE THREAD

**Issue by DavidSichma** [godotengine/godot#42662]
**Godot version:**
current master
3.x unaffected

**OS/device including version:**
Debian 10
Vulkan, Mesa DRI Intel(R) UHD Graphics 630

**Issue description:**
calling `CanvasItem::draw_texture_rect` with `tile = true` does not work or only in an unintuitive way. It definitive does not work as in 3.x

In 3.x this argument, well, tiled the texture.
In 4.0 it only prevents texture scaling but instead of tiling the edges just get stretched out.

Behavior in 3.2
![image](https://user-images.githubusercontent.com/25692790/95557283-df7bfa80-0a14-11eb-9268-c750bfc8cfce.png)
left: TextureRect Stretch Mode tile, just a hidden call to draw_texture_rect really
right: manual call to draw_texture_rect from _draw()

The same setup in 4.0.dev
![image](https://user-images.githubusercontent.com/25692790/95557654-616c2380-0a15-11eb-8f60-d0be01ca0ae3.png)

To achieve the same results in 4.0 one has to
- call `draw_texture_rect` with `tile = true` to prevent scaling instead of tiling
- and specify a tiling mode (calling `set_texture_repeat` or specifying the `texture_repeat argument`)

**Related Issues**
- reason for #40011
- background checkerboard does not correctly tile in ColorPicker related Nodes with alpha < 1: (example with alpha=0)
3.2:  ![image](https://user-images.githubusercontent.com/25692790/95559248-c0329c80-0a17-11eb-9894-2aafff7c2c5f.png)
4.0:  ![image](https://user-images.githubusercontent.com/25692790/95559069-78137a00-0a17-11eb-9cd4-cf27584928b8.png)
- possible that I missed some

**Possible Solutions**
- setting texture repeat as described above. some places in the engine already do this.
- changing the api to be less confusing. Maybe rename tile to keep_src_size as this currently describes the behavior, however compat breakage might be hard to spot as the same calls work but they don't do their job properly. 

**Steps to reproduce:**
any call to draw_texture_rect with tile=true

**Minimal reproduction project:**
[draw_texture_rect-tile.zip](https://github.com/godotengine/godot/files/5353415/draw_texture_rect-tile.zip) - setup as above

**Comment by Calinou** [comment]
> background checkerboard does not correctly tile in ColorPicker related Nodes with alpha < 1: (example with alpha=0)

See also https://github.com/godotengine/godot/issues/41561.

**Comment by clayjohn** [comment]
This is most likely a result of the tiling property now being a property of the material instead of the texture. Tiling works with sprites, so someone just needs to update draw_texture_rect to use the proper tiling mode.

**Comment by aaronfranke** [comment]
This bug is still relevant in the current master, and it's immediately noticeable when porting some of the demo projects.
