### ISSUE TITLE
Material is not applied on MeshInstance when opening scene

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#42675]
**Godot version:**

3.2.4 beta 0cea2731f7

**OS/device including version:**

Radeon RX570, both GLES2 and GLES3

**Issue description:**

Assigned material is not applied on MeshInstance after reopening scene.
_(Assigning material to `material_override` works as expected)_

**Steps to reproduce:**
1. assign a material on MeshInstance
2. save it
3. close the scene
4. reopen the scene

![material](https://user-images.githubusercontent.com/8281454/95611619-05e57880-0a9d-11eb-86bf-a9320b716889.gif)

**Minimal reproduction project:**

[material bug.zip](https://github.com/godotengine/godot/files/5356438/material.bug.zip)

**Comment by volzhs** [comment]
probably @pouleyKetchoupp has a clue...

**Comment by pouleyKetchoupp** [comment]
Ah yes, probably a regression from the software skinning change.

**Comment by akien-mga** [comment]
No issue for me in 4040cd350db9be99c46fbe9376367eb2cb58b2fd, so it's likely a regression from #40313 indeed.

**Comment by dsnopek** [comment]
I'm seeing this problem as well, but it's not just affecting the scene in the editor after reload: the material also fails to load when running the game from the editor, or when exported. If I move my material from "Material" to "Material Override", then it appears in game again.

**Comment by akien-mga** [comment]
Fixed by #42846.

**Comment by AThousandShips** [comment]
Please open a new issue with an MRP
