### ISSUE TITLE
Godot should not include insecure OpenSSL code in its source tree

### ISSUE THREAD

**Issue by rofl0r** [godotengine/godot#4267]
openssl had several important security bugfixes in the last years.
embedding third-party code in a source tree is equivalent to a fork, so there need to be sufficient resources to maintain it.
in security-critical software this either means continuous updates or backported patches.
if these resources are not available, it's better to use the system supplied version.
just to make it easy to build for windows folks doesn't mean godot needs to be insecure.

removing the code would also fix the issue that github mistakenly classifies godot as a C project, while in reality it's C++.
( https://github.com/godotengine/godot/search?l=c )

**Comment by vnen** [comment]
Duplicate of #2780.

**Comment by akien-mga** [comment]
Reopening as it's more precise than #2780, the latter being "fixed" now that we bundle the latest OpenSSL release and have a good workflow to keep it up-to-date.

**Comment by vnen** [comment]
If it's possible to use Git submodules for this (and other embedded drivers) it'll make updating even more reliable.

BTW, in *nix environments Godot does use the system's OpenSSL, unless you force `openssl=builtin` when compiling.

**Comment by Noshyaar** [comment]
Fixed by #16519 I think
