### ISSUE TITLE
Changing reflection atlas size/subdivision should request an editor restart

### ISSUE THREAD

**Issue by BracerJack** [godotengine/godot#42687]
**Godot version:**
v3.2.3

**OS/device including version:**
GTX 1650, GLES3

**Issue description:**
Have to restart editor just to see the changes made in Reflection Atlas Size/Subdiv ? Now this seems like a bug.

And also how come one needs to set the Atlas Subdiv manually ?
Why can't the number of probes in the scene be auto detected and this be updated automatically ?
Example, you have only one probe and you have to go all the way to this dialog just to set atlas subdiv to 1 just to have maximum quality or else the atlas size resolution is wasted...why ? Why can't the editor detect simple things like this automatically ?

Not to mention you have to restart the editor every time just to see the change...why ?
![Untitled-1](https://user-images.githubusercontent.com/46036208/95652606-ea25b500-0b24-11eb-8c14-a50eccb2e3aa.png)

**Comment by Calinou** [comment]
> Have to restart editor just to see the changes made in Reflection Atlas Size/Subdiv ? Now this seems like a bug.

Not everything in the Godot renderer is made to work without a restart. I think the situation will be better in Godot 4.0, but Godot 3.2 just wasn't designed for that.

**Comment by akien-mga** [comment]
Fixed by #42694.
