### ISSUE TITLE
Godot gets stuck everytime quitting

### ISSUE THREAD

**Issue by Ark2000** [godotengine/godot#42693]
**Godot version:** V3.2.3.stable.official

**OS/device including version:** Windows 10，GTX1650(445.75), GLES2, GLES3

**Issue description:** When I open any projects, the project manager gets stuck, but I can use the engine editor without troubles, but when I quit the editor, the editor gets stuck too. Very similar to the issue #29107. I can't see any output from the console.

**Steps to reproduce:**
![1](https://user-images.githubusercontent.com/21126555/95657732-a0e75c80-0b48-11eb-9e70-d40204acdd79.png)
![2](https://user-images.githubusercontent.com/21126555/95657742-ae9ce200-0b48-11eb-9fe7-6916cf375e5e.png)
![3](https://user-images.githubusercontent.com/21126555/95657754-beb4c180-0b48-11eb-8f18-125b52c098ed.png)

**Minimal reproduction project:** any projects

**Comment by Calinou** [comment]
@Ark2000 Do you get anything specific in the command window/console output?

Also, which graphics card model do you have?

**Comment by Ark2000** [comment]
> @Ark2000 Do you get anything specific in the command window/console output?
> 
> Also, which graphics card model do you have?

I don't get any specific in the command window, it just gets stuck, my graphics card is GTX1650

**Comment by volzhs** [comment]
I have same issue on Kubuntu 20.04 with 3.2.4-beta 0cea2731f7
editor gets stuck at quitting.

**Comment by akien-mga** [comment]
I assume you tested and the bug was no longer reproducible in recent 4.0 betas?

**Comment by Ark2000** [comment]
> I assume you tested and the bug was no longer reproducible in recent 4.0 betas?

Have Never met this again in 4.0
