### ISSUE TITLE
Regex produces errors on the 3.2.3 linux_x11_64_release export template

### ISSUE THREAD

**Issue by L4r0x** [godotengine/godot#42699]
**Godot version: 3.2.3.stable**

**OS/device including version:**
- Linux Mint 20 Cinnamon (Kernel 5.4.0-48-generic)
- i7-8700K CPU
- GeForce GTX 1080

**Issue description:**
Regex does not seem to work on the 3.2.3 `linux_x11_64_release` export template. 
However, `linux_x11_64_debug` and the editor both work as expected.

**Steps to reproduce:**
Execute a gdscript that uses the `Regex` class with the `-s` option as show below:

```bash
./linux_x11_64_release -s TestRelease.gd
```
Produces the following output:
```
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 1080/PCIe/SSE2
OpenGL ES 2.0 Batching: ON
 
ERROR: search: Condition "!is_valid()" is true. Returned: __null
   At: modules/regex/regex.cpp:245.
```

**Minimal reproduction project:**
- [TestRelease.gd.zip](https://github.com/godotengine/godot/files/5359736/TestRelease.gd.zip)

**Comment by L4r0x** [comment]
Also `File.store_string` fails for the release export template:

```gd
extends MainLoop

func _idle(_delta: float) -> bool:
    var text := "Repudiandae enim aut rerum minima quam repellat vero."

    var file := File.new()
    assert(file.open("some_data.txt", File.WRITE) == OK)
    file.store_string(text)
    file.close()

    return true
```

Produces the following error:
```
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 1080/PCIe/SSE2
OpenGL ES 2.0 Batching: ON
 
ERROR: store_string: Condition "!f" is true.
   At: core/bind/core_bind.cpp:2195.
```
> PS: With `linux_x11_64_debug` and the editor it works as expected

**Comment by zacryol** [comment]
`assert()` calls are ignored/removed in release builds. `file.open()` isn't being called.
This can be closed.

**Comment by Calinou** [comment]
Also, you should always use the `user://` location to store user-specific data such as save and configuration files.
