### ISSUE TITLE
Misleading Color.from_hsv() description in documentation

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot#42707]
Existing method(`Color8()`) and non-existent method(`HSV()`) are shown as examples in the same Description. It is written as if the `HSV` method existed.
https://github.com/godotengine/godot/blob/bf37ab52b3ee4b14f235cfa1ea9e48c24c616bb3/doc/classes/Color.xml#L213
https://github.com/godotengine/godot/blob/bf37ab52b3ee4b14f235cfa1ea9e48c24c616bb3/doc/classes/Color.xml#L216

I think the "HSV (210, 50, 79, 0.8) or" part is unnecessary. Delete it.

**Comment by pycbouh** [comment]
It's not a method name, it's a standard notation for colors. `RGBA()` is used in the same way elsewhere in the document. Though I have to admit that mixing it in the same sentence with an actual function call in the form of `Color8` can be misleading.

**Comment by aaronfranke** [comment]
@hazarek Thanks for pointing this out. Rather than deleting this information outright, I decided to reword that information, along with fixing other confusing `RGBA` comments. Feel free to review #42710 if you want.
