### ISSUE TITLE
Rectangle Paint shortcut conflicts with a system-wide shortcut on macOS

### ISSUE THREAD

**Issue by MPWrobel** [godotengine/godot#42702]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
macOS Catalina 10.15.5

**Issue description:**
Tile Map Editor shortcut for Rectangle Paint (**Shift+Ctrl+LMB**) conflicts with system-wide macOS shortcut (**Ctrl+LMB**). On macOS **Ctrl+LMB = RMB**, thus Godot receives **Shift+RMB**/**Shift+Ctrl+RMB**, I'm not sure on this one. Unfortunetely, the Godot shortcut can't be changed in the editor settings and the system-wide shorcut can't be disabled, at least not without 3rd party software.

<img width="369" alt="obraz" src="https://user-images.githubusercontent.com/20567620/95663628-0e8f8a80-0b41-11eb-838e-c4318db36801.png">

**Comment by MPWrobel** [comment]
I just accidentally discovered that on mac the shortcut for Rectangle Paint is actually Ctrl+Command+LMB. So it's just a mistake in the tooltip.

**Comment by hazarek** [comment]
Also; 
* `Command + , ` (Editor Settings..) does not work when the script editor is open.
* `Command + M` (Minimize the front window to the Dock) doesn't work.

**Comment by akien-mga** [comment]
Fixed by #42705.
