### ISSUE TITLE
Compiling MacOS from Linux does not work

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#42714]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux minut 64bit

**Issue description:**
When I export my game to MacOS Catalina via Linux Mint 64 bit edition, upon opening I get this error, note it is not a permission error. When I export using my Windows 64 bit version with the same target and I've checked every setting is the same as below, it works fine.

![image](https://user-images.githubusercontent.com/12863685/95675815-c2306300-0bb1-11eb-8380-78db90262fad.png)

![image](https://user-images.githubusercontent.com/12863685/95675836-0459a480-0bb2-11eb-8979-a8d355f8042a.png)

**Steps to reproduce:**
1. download export files
2. build macos 64 bit
3. try to run

**Comment by akien-mga** [comment]
This was fixed in Godot 3.2.3: https://godotengine.org/article/maintenance-release-godot-3-2-3

**Comment by chucklepie** [comment]
Thanks. i didn't think he's running Arm, which is what the release notes are implying. Anyway I'll try again.

btw, not relevant to the issue but I'm wary of upgrading to 3.2.3 incase things break. I've had to put workarounds/hacks in my code to bypass faults in 3.2.2 and I suspect if those are fixed in 3.2.3 my game will break at subtle points without me realising...

**Comment by akien-mga** [comment]
It's not about ARM, it's this:

> macOS: Set correct external file attributes, and creation time (GH-39977) [regression fix].

If you can't upgrade, you can extract the exported macOS zip on Linux, make sure the binary is executable, and rezip.
