### ISSUE TITLE
Curve2D:tessellate produces a slanted curve

### ISSUE THREAD

**Issue by bugsalad** [godotengine/godot#42727]
Godot version: v3.2.3.stable.official

OS/device including version: PC, Linux Mint, kernel 4.15.0-118

Issue description:
calling Curve2D.tessellate with f.i. (20,0), (40,60), (-40,60), (140,0)
produces a curve that is not symmetric, as it should be, but instead slated towards one of the endpoints
(given that "in" and "out" in this example are mirror images, equal but with opposite sign in x).

My guess is that the issue is at
https://github.com/godotengine/godot/blob/master/scene/resources/curve.cpp, line 941,
  _bake_segment2d(midpoints.write[i], 0, 1, points[i].pos, points[i].out, points[i + 1].pos, points[i + 1].in, 0, p_max_stages, p_tolerance);
which should be
_bake_segment2d(midpoints.write[i], 0, 1, points[i].pos, points[i].out, points[i + 1].pos, points[i].in, 0, p_max_stages, p_tolerance);

(.in and .out both belong to points[i] for any given Bezier segment)

Thanks!

**Minimal reproduction project:**

**Comment by pouleyKetchoupp** [comment]
Could you please provide a minimal reproduction project that shows the resulting curve? It would help other contributors confirm the issue and review a potential fix.

**Comment by bugsalad** [comment]
[42727.zip](https://github.com/godotengine/godot/files/5367460/42727.zip)

Hi,
sorry for the incomplete post yesterday. Attached is a minimal example.

After downloading the sources in the 3.2 branch, I can confirm that the change mentioned in the first post (points[i + 1].in -> points[i].in) fixes the issue. I used the 3.2 branch because there are differences in the master branch that I didn't want to work around for the example project (in the master branch PoolArrayVector2D becomes PackedArrayVector2D, and Vector2D.linear_interpolate does not appear to exist). The relevant line in scene/resources/curve.cpp (line 941 in master, 953 in the 3.2 branch) seems to be the same, though.

Thanks again!

**Comment by pouleyKetchoupp** [comment]
It seems some control points might be inverted in your script. I'm getting the proper result by setting an out control on the first point, and in control on the second point:
```
func tessellated():
	var c = Curve2D.new()
	c.add_point(begin, Vector2.ZERO, offset_out)
	c.add_point(end, offset_in, Vector2.ZERO)
	return c.tessellate()
```
If there were 3 points, the middle point would probably get in + out controls.
Does that make sense to you?

**Comment by bugsalad** [comment]
Ah, I see! Thanks, then I believe we can close the issue.
