### ISSUE TITLE
All materials and sky material are black in viewport on godot 4

### ISSUE THREAD

**Issue by SeleDreams** [godotengine/godot#42720]
**Godot version:**
Godot 4 build bf37ab52b

**OS/device including version:**
Windows 10 64-bit
AMD Ryzen 7 3700x
NVIDIA RTX 2080
16GB RAM DDR4 3200mhz

**Issue description:**
When opening the Godot editor, the viewport doesn't have any skybox or background except the white grid, and meshes added to the scene are black themselves
The camera preview though can properly display the materials.

**Steps to reproduce:**
Building Godot from source in the godot 4 branch
Creating a VULKAN project

**Minimal reproduction project:**
[Test4.zip](https://github.com/godotengine/godot/files/5361352/Test4.zip)
![image](https://user-images.githubusercontent.com/16335601/95682947-8b297400-0be8-11eb-89a1-bb4654ef5dfb.png)

**Comment by nongvantinh** [comment]
I think you have to create Environment Resource and add it by yourself. In Godot 3.x engine created it when you create new project.

**Comment by SeleDreams** [comment]
It seems to have worked, thanks, I wonder why this change of behaviour though
