### ISSUE TITLE
4.0 ScriptEditor Gutter Drag Selection Always Acts Like You're Holding Shift

### ISSUE THREAD

**Issue by Devination** [godotengine/godot#42722]
**Godot version:**
4.0 / ca2c0b8937d287e608448a9a5ba553a8deaf46d9

**OS/device including version:**
Windows 10

**Issue description:**
When you click and drag on the line numbers gutter in the ScriptEditor in Godot 4.0, it adds to the selection from your previous cursor point instead of starting a new selection from the drag line's start.

Here is the current 4.0 behavior acting strange: 
![4 0_bad](https://user-images.githubusercontent.com/8147765/95683940-fe0ffc00-0ba2-11eb-92a5-80616c3d9b77.gif)

Here is the Godot 3.2 behavior working as expected:
![3 2_good](https://user-images.githubusercontent.com/8147765/95683955-14b65300-0ba3-11eb-863d-214b7b38f680.gif)

This is related to the refactor from #31739

**Steps to reproduce:**

1. Open the Script Editor in any 4.0 project.
2. Click in the middle of any line to place the cursor there.
3. Click and drag the line number gutter of a different line. (See gifs above)
4. Notice the selection starts from the previous cursor point instead of starting from the dragged line number.

**Comment by Calinou** [comment]
cc @Paulb23

**Comment by Devination** [comment]
I submitted a PR that works for me, though it changes TextEdit's selection from private to protected. Not sure if we're trying to avoid that or not.
