### ISSUE TITLE
Tooltip ignores parent scaling

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#4272]
Godot 2.0.1-stable Win10 64bit

Tooltip's position is invalid if Controls are scaled
(a similar problem happens if you set a custom drag control)

**Steps to reproduce:**
1. Create a new scene, add a main Control element
2. Create a Panel, change it's scale to 2,2
3. Create a Button as the Panel's child, set some text and tooltip text
4. Start the scene
5. Hover over the button

When you hover over the button the tooltip will be misplaced. You will not see the tooltip at all if the button is far from 0,0 (top left of the screen).
This may be related to Control.set_drag_previev() also messing up the position if there is a scale involved.

**Comment by akien-mga** [comment]
Probably related to #3264 and #1445.

**Comment by vnen** [comment]
I cannot reproduce this, maybe it was also fixed along with #3264.
