### ISSUE TITLE
Leak errors when starting and closing any project

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#42735]
**Godot version:**

master build https://github.com/godotengine/godot/commit/d22791c271aceeade16970bffd8e8a3a146de339

**OS/device including version:**

Windows 10 Enterprise 1909

**Issue description:**

```
ERROR: Some texture bindings were not properly freed (leaked CanvasItems?)
   at: ~RasterizerCanvasRD (servers\rendering\rasterizer_rd\rasterizer_canvas_rd.cpp:2500)
ERROR: 1 shaders of type ParticlesShaderRD were never freed
   at: ~ShaderRD (servers\rendering\rasterizer_rd\shader_rd.cpp:470)
ERROR: 1 RID allocations of type 'N19RasterizerStorageRD8MaterialE' were leaked at exit.
ERROR: 1 RID allocations of type 'N19RasterizerStorageRD6ShaderE' were leaked at exit.
ERROR: Invalid Object id '24259854738', can't call method.
   at: (.\core/callable_method_pointer.h:182)
```
This is the state of errors in current master build https://github.com/godotengine/godot/commit/d22791c271aceeade16970bffd8e8a3a146de339.

First error is in #37664. This issue is about other errors.
ParticlesShaderRD is supposed to freed at https://github.com/godotengine/godot/blob/d22791c271aceeade16970bffd8e8a3a146de339/servers/rendering/rasterizer_rd/rasterizer_storage_rd.cpp#L4322-L4327
But this destructor is never called. Looks like variable `shader_data` is never `memdelete`ed.
I don't have much info about other errors yet.

**Steps to reproduce:**
Open or close any project.

**Minimal reproduction project:**

Any project.

**Comment by opl-** [comment]
Can repro on bf37ab52b3 with some more errors.
```
ERROR: Texture (binding: 1, index 0) is not a valid texture.
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:4614)
ERROR: Some texture bindings were not properly freed (leaked CanvasItems?)
   at: ~RasterizerCanvasRD (servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp:2500)
ERROR: 1 shaders of type SortShaderRD were never freed
   at: ~ShaderRD (servers/rendering/rasterizer_rd/shader_rd.cpp:470)
ERROR: 1 shaders of type ParticlesCopyShaderRD were never freed
   at: ~ShaderRD (servers/rendering/rasterizer_rd/shader_rd.cpp:470)
ERROR: 1 shaders of type ParticlesShaderRD were never freed
   at: ~ShaderRD (servers/rendering/rasterizer_rd/shader_rd.cpp:470)
ERROR: 1 RID allocations of type 'N19RasterizerStorageRD8MaterialE' were leaked at exit.
ERROR: 1 RID allocations of type 'N19RasterizerStorageRD6ShaderE' were leaked at exit.
WARNING: 1 RIDs of type 'UniformBuffer' were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:7275)

--- during another run ---
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:6853)```

**Comment by Anutrix** [comment]
@opl- Some of those were fixed in a very recent commit https://github.com/godotengine/godot/commit/b3b5cd021c46db7c29cac65fb1a5eb4caaf7c962.
Do a `git pull` and compile again.
