### ISSUE TITLE
Inertia "leak" in zoom/pan gestures when using trackpad on Mac

### ISSUE THREAD

**Issue by vaner-org** [godotengine/godot#42747]
**Godot version: 3.2.3**
**OS/device including version: macOS 10.14.6, on MacBook Pro**

**Issue description:**

• When using the two finger scroll or pinch to zoom gestures on macOS with the trackpad, velocity for the action is retained even after releasing the modifier key. So, if I am panning with Shift + a two finger swipe, then releasing shift before the swipe's inertia has ended causes the viewport to momentarily orbit, until the velocity reaches zero. The same happens when zooming in or out with control + two finger scroll: letting go of the modifier too early will mean the view orbiting upward or downward.

• Also, pressing a specific view button doesn't negate this inertia either. So if you held down any axis-aligned orthogonal view button mid-orbiting with the two finger swipe gesture the viewport will rapidly flicker between ortho and perspective view in the direction of the swipe, because the scroll inertia will keep trying to orbit every frame.

(These two together lead to a very annoying loop where you try to pan with the swipe gesture in ortho view, release shift, which causes the view to start to orbit in perspective view, then press the front view button again, but since the velocity hasn't run out, it ejects the view into a perspective orbit once again.)

• Finally, there's the minor gripe that the "Translation inertia" setting doesn't seem to affect panning with the trackpad at all, the acceleration for which is really sluggish, maybe ten times slower than it should be (see Blender for responsive panning with the Mac trackpad). The magnitude of this panning is also really inconsistent for some reason, with minor swipes sometimes leading to big movements, sometimes small.

**Steps to reproduce:**

Can be tested in brand new project, just need a MacBook with a trackpad or a Mac desktop with a wireless trackpad.
I usually set all of Godot's inertia settings to zero because they only compound the built-in inertia already on macOS. (Maybe these settings could be isolated to mouse use?)

**Possible causes:**

Maybe this is because of Godot not recognising the built-in systemwide two finger scroll inertia applied by macOS?
These kinds of gestures work very well in Blender, where using a trackpad on Mac actually provides a smoother viewport experience than on any mouse, in my opinion. Godot more closely imitating Blender in this would be very helpful.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
I can't test it, my mac is Mac Pro and the only trackpad I have is sending Scroll events on two finger swipe, AFAIK Pan events are supported only with Magic Trackpad, Magic Mouse, some Wacom tablets, and MacBook trackpads).

If you can test it on a custom Godot build, try it with the following patch (based on Blender code):
```diff
diff --git a/platform/osx/os_osx.mm b/platform/osx/os_osx.mm
index 1f60ed59b3..3ee2f43c30 100644
--- a/platform/osx/os_osx.mm
+++ b/platform/osx/os_osx.mm
@@ -105,6 +105,7 @@ static int mouse_x = 0;
 static int mouse_y = 0;
 static int button_mask = 0;
 static bool mouse_down_control = false;
+static bool ignore_momentum_scroll = false;
 
 static Vector2 get_mouse_pos(NSPoint locationInWindow) {
 
@@ -1179,6 +1180,8 @@ static int remapKey(unsigned int key, unsigned int state) {
 
 - (void)keyDown:(NSEvent *)event {
 
+	ignore_momentum_scroll = true;
+
 	// Ignore all input if IME input is in progress
 	if (!imeInputEventInProgress) {
 		NSString *characters = [event characters];
@@ -1219,6 +1222,8 @@ static int remapKey(unsigned int key, unsigned int state) {
 
 - (void)flagsChanged:(NSEvent *)event {
 
+	ignore_momentum_scroll = true;
+
 	// Ignore all input if IME input is in progress
 	if (!imeInputEventInProgress) {
 		OS_OSX::KeyEvent ke;
@@ -1360,8 +1365,13 @@ inline void sendPanEvent(double dx, double dy, int modifierFlags) {
 	}

+ 	if ([event momentumPhase] != NSEventPhaseNone) {
+ 		if (ignore_momentum_scroll) {
+ 			return;
+ 		}
+ 	} else {
+ 		ignore_momentum_scroll = false;
+ 	}
 	if ([event phase] != NSEventPhaseNone || [event momentumPhase] != NSEventPhaseNone) {
 		sendPanEvent(deltaX, deltaY, [event modifierFlags]);
 	} else {
 		if (fabs(deltaX)) {
 			sendScrollEvent(0 > deltaX ? BUTTON_WHEEL_RIGHT : BUTTON_WHEEL_LEFT, fabs(deltaX * 0.3), [event modifierFlags]);
 		}
```

**Comment by molevision** [comment]
Getting an error when I try to apply the diff patch. Any way around it?

```$ git apply inertia.diff
inertia.diff:34: space before tab in indent.
 	if ([event momentumPhase] != NSEventPhaseNone) {
inertia.diff:35: space before tab in indent.
 		if (ignore_momentum_scroll) {
inertia.diff:36: space before tab in indent.
 			return;
inertia.diff:37: space before tab in indent.
 		}
inertia.diff:38: space before tab in indent.
 	} else {
error: corrupt patch at line 46
```

**Comment by bruvzg** [comment]
> Getting an error when I try to apply the diff patch.

Here's original `diff` file (it's for current 3.2 branch head - 0a2a93b165) and I have updated previous post, seems like I have not copied it correctly.

[patch_32_pan.diff.zip](https://github.com/godotengine/godot/files/5371581/patch_32_pan.diff.zip)

**Comment by vaner-org** [comment]
Closing since both PRs were merged.
