### ISSUE TITLE
Jagged Textures using Pixel Art Textures

### ISSUE THREAD

**Issue by OrbitalBiscuitHammer** [godotengine/godot#42751]
**Godot version:**
Godot 3.2.1

**OS/device including version:**
Tested on Dell XPS 13:
- Intel Core i5-8520U CPU
- 8 GB RAM
- 1920 x 1080 resolution

**Issue description:**
Hello. I added a 32 x 32 texture to a 3d model and the lines come out very jaggy despite
using MSAA and Anisotropic Filtering (I tested this on various settings). Have a lovely day!

Here are some images:
[![Example.png](https://i.postimg.cc/GmG4cV9W/Example.png)](https://postimg.cc/gxczsMVs)
[![Example2.png](https://i.postimg.cc/fTBvZ3S4/Example2.png)](https://postimg.cc/Czn8sx4J)

**Steps to reproduce:**
- Create a 32 x 32 texture and add it to a 3d model in Godot

**Minimal reproduction project:**
[Jagged Pixel Art Texture Recreation.zip](https://github.com/godotengine/godot/files/5366880/Jagged.Pixel.Art.Texture.Recreation.zip)

**Comment by Calinou** [comment]
This is a limitation of multi-sample antialiasing. MSAA cannot smooth out the "insides" of textures, since it only uses triangles for smoothing, not transparency.

**Comment by OrbitalBiscuitHammer** [comment]
Thank you, have a nice day!
