### ISSUE TITLE
Expected expression, found: QUESTION in Shader Editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#42756]
**Godot version:**

3.2.3

**Steps to reproduce:**
1. Create a shader with this code
```
shader_type canvas_item;

void fragment() {
	COLOR = vec4(0, 0, 0, );
}
```
2.
![image](https://user-images.githubusercontent.com/2223172/95797289-6ec42f00-0cef-11eb-8a4d-3ada1bfe7c0c.png)

On master it says COMMA instead of QUESTION.

**Comment by ZER0PSS** [comment]
Just edit vec4() to vec4(1,1,1,1)

Mini_tutorial:
vec4(1 - Red,
         1 - G,reen,
         1 - Blue,
         1 - Alpha
         )

And now we have vec4(1,1,1,1)

**Comment by Zylann** [comment]
Still happening in 4.4 dev
