### ISSUE TITLE
GridMap has no Visual layer_mask 

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#42752]
**Godot version:**

3.2-stable

**OS/device including version:**

any

**Issue description:**

layer_mask is always 1 in gridmap multimeshinstances

**Steps to reproduce:**
Create a gridmap, there's no layer property!

**Minimal reproduction project:**

[GridMapLayers.zip](https://github.com/godotengine/godot/files/5367145/GridMapLayers.zip)

**Comment by jamie-pate** [comment]
https://godotengine.org/qa/76297/is-it-possible-to-use-camera-layers-cull_mask-with-gridmap

**Comment by madmiraal** [comment]
Updated the title to be clear that this refers to the Visual layer mask and not the Collision layers and masks.

**Comment by jamie-pate** [comment]
duplicate of 
https://github.com/godotengine/godot/issues/40245 ?
