### ISSUE TITLE
Weird shader behavior when using depth texture. Overlay hidden when alpha is used.

### ISSUE THREAD

**Issue by y0nd0** [godotengine/godot#42760]
### Godot version:
`3.2.3` Win 64-bit Standard.

### OS/device including version:
`GLES3` Windows 10, RTX 2070 Super

### Issue description:
When the a (sea) shader uses `DEPTH_TEXTURE`, all overlaying objects are hidden. Or with render mode `depth_draw_alpha_prepass` on the overlaying object (tree).

### Steps to reproduce:

1. Create a plane for the sea and add the shader see below.
2. Create a tree on the sea and add the shader see below.

**Sea Shader**

```cpp
shader_type spatial;

void fragment() {
	float depth_raw = texture(DEPTH_TEXTURE, SCREEN_UV).r * 2.0 - 1.0;
}
```
It does not matter if the ALBEDO, etc. are set. This is just minimal code to demonstrate the issue. 

**Tree shader**

```cpp
shader_type spatial;
render_mode cull_disabled;

uniform sampler2D texture_albedo : hint_albedo;

void fragment() {
	vec4 tex_albedo = texture(texture_albedo, UV);
	ALBEDO = tex_albedo.rgb;
	ALPHA = tex_albedo.a;
}
```
Just a minimal shader. Add `depth_draw_alpha_prepass` to render mode to see a difference but it's also does not work great.
Toggle comment the `ALPHA` line to see the issue. If a background shader uses DEPTH_TEXTURE and a foreground shader uses ALPHA, the whole object is hidden when overlay the background shader object. It does not matter if the alpha is 0 or 1 or uses a texture for masking e.g. leaves of a tree.

### Screenshots

![demo](https://user-images.githubusercontent.com/68586847/95810062-692b1100-0d10-11eb-91d3-92a9118c6ce1.png)

**When using `depth_draw_alpha_prepass`** (Little bit better, but nope... It looks cropped.)
![with_depth_draw_alpha_prepass](https://user-images.githubusercontent.com/68586847/95810067-6af4d480-0d10-11eb-952f-a0ce6b0af02a.png)

### Minimal reproduction project:
[Demo_Shader_Issue.zip](https://github.com/godotengine/godot/files/5368673/Demo_Shader_Issue.zip)

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by y0nd0** [comment]
Some more infos about this issue: 

I found out, that the y-angle affects to this bug. See the attached gif (sorry for the bad quality. It's hard to create a good gif with a small size. Since webm videos are not embeddable.)

![y-angle](https://user-images.githubusercontent.com/68586847/95936113-241ce280-0dd5-11eb-9dea-83233ee22e7f.gif)

This is recorded in the viewport. Rotated with the flying camera by hand (sure you can guess it. ^^)

In the next image you can see that the gizmos are also hidden on this shader which is using "DEPTH_TEXTURE". 

![image](https://user-images.githubusercontent.com/68586847/95936285-7cec7b00-0dd5-11eb-89a9-8e7dd5031999.png)

**Comment by y0nd0** [comment]
Good Morning ☕ *sip* ... Any guesses?

**Comment by Calinou** [comment]
@y0nd0 Try playing with the tree material's Render Priority property.

**Comment by y0nd0** [comment]
@Calinou Thanks for the hint. I changed the render priority of the tree leaves to `1`. This fixes the issue of hidden leaves. But with higher priority, the leaves are always drawn above any other material like the sea. For example: Placing the tree under the sea will not cover the leaves. In my case, it's ok. Because this trees under the water can't breathe. ;) But seriously: I'll run into this issue when adding seaweed, corals, etc. ...
I wonder why does this "bug" appear when just getting the "DEPTH_TEXTURE" without setting anything.
For me it's a workaround. However, if you think this is not a bug then you can close this problem. I'm not sure if this is a correct behavior.

**Comment by y0nd0** [comment]
Ok, I close this because of "[Godot does not support it](Some rendering engines feature order-independent transparency techniques to alleviate this)" (quote: "other engines may support it, on costs of GPU performance", ... if this is the issue). Maybe a good feature proposal?

**Comment by Calinou** [comment]
> (What's about Godot 4 and Vulkan? Some changes here?)

Order-independent transparency is still expensive in Vulkan, so I wouldn't hold my breath for it in 4.0.
