### ISSUE TITLE
3.2: Software Skinning being used despite hardware capability

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#42768]
**Godot version:**
0a2a93b

**OS/device including version:**
Windows 10 [10.0.18362.1082]
NVIDIA GeForce RTX 2080 Ti
Driver 452.06

**Issue description:**
With the new PR that landed, Godot appears to be using software skinning (as evidenced by a new rendering bug) both in a case where I created a new project and in a case where I open an older existing project.

The expected behavior is to whitelist the specific low-end hardware which needs to use software skinning, so as to not degrade performance on high-end systems.

**Steps to reproduce:**
1. Make a new project
2. Import a GLB with blend shapes.
3. Switching tabs to a model with blend shapes is perceptibly slower (I think about 0.2 seconds, compared with instantaneous) with a new release build compared to 3.2.3.stable. See here for the test project with this model https://github.com/godotengine/godot/issues/42767

**Minimal reproduction project:**
https://github.com/godotengine/godot/files/5371719/GLTFBug.zip

**Comment by akien-mga** [comment]
Regression fixed by #42846. (#37854 is still valid.)
