### ISSUE TITLE
Errant script editor UI elements appear when visual shader editor is opened

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4277]
**Operating system or device:**
Windows 10 64bit; 24 gigs RAM; ATI 7xxx GPU; third-gen i7 CPU.

**Issue description** (what happened, and what was expected):
When opening the visual shader editor, errant graphics that are supposed to only be for the script editor show up in the viewport (with errant text left of the viewport).

**Steps to reproduce:**
Get a brand new build of Master (April 8) and create a new shader via the visual node editor

**Link to minimal example project** (optional but very welcome):
I don't have a project, but I do have an image (see the red circles).
![godot_bug2](https://cloud.githubusercontent.com/assets/10081256/14415122/413411c2-ff61-11e5-8ec0-8551e232b897.jpg)

**Comment by vnen** [comment]
The shader code editor is the thing being shown, maybe with the generated code from the visual editor.

**Comment by MarianoGnu** [comment]
Fixed in #5308
