### ISSUE TITLE
Exported Godot software did not realize the supposed library file (for GDNativeLibrary) even had been exported with & sitting next to it

### ISSUE THREAD

**Issue by JOELwindows7** [godotengine/godot#42777]
**Godot version:**

Godot 3.2.3 Stable Standard x64

**OS/device including version:**

Tested:
- Windows 10 Pro

untested:
- Linux
- Android

**Issue description:**

Similar Issue at #11441 , which seems had fixed the crash when the library missing, but still happened for this case.

I have test rendered / exported a software that I was developing which involves a GDNative, such as FLMusicLib, the asset https://godotengine.org/asset-library/asset/407 here.
The GDNativeLibrary works in project edit, **but not when I executed the rendered version**, as it spits errors like `Invalid call. Nonexistent function 'play_music' in base 'Nil'`. It happened in Windows Desktop export, but I will confirm for other platform later.

bellow is the debug console output of exported application which is FLMusicLib demo.
```
Godot Engine v3.2.3.stable.official - https://godotengine.org
Using GLES2 video driver
OpenGL ES 2.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL ES 2.0 Batching: ON
        OPTIONS
        max_join_item_commands 16
        colored_vertex_format_threshold 0.25
        batch_buffer_size 16384
        light_scissor_area_threshold 1
        item_reordering_lookahead 4
        light_max_join_items 32
        single_rect_fallback False
        debug_flash False
        diagnose_frame False
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 8
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 1536000
WASAPI: nBlockAlign = 32
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 8 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms

Loading resource: res://FLMusicLib/FLMusicLib.gdnlib
ERROR: Can't open dynamic library: FLMusicLib/Windows/x86/FLMusicLib.dll, error: Error 126: The specified module could not be found.
.
   At: platform/windows/os_windows.cpp:2395
CORE API HASH: 17947557007960061372
EDITOR API HASH: 3270892295
Loading resource: res://default_env.tres
Loading resource: res://global.gdc
Loading resource: res://FLMusicLib/FLMusic.gdns
Loading resource: res://FLMusicLib/FLMusicLib.gdnlib
ERROR: Can't open dynamic library: FLMusicLib/Windows/x86/FLMusicLib.dll, error: Error 126: The specified module could not be found.
.
   At: platform/windows/os_windows.cpp:2395
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:501
ERROR: init_library: No nativescript_init in "res://FLMusicLib/Windows/x86/FLMusicLib.dll" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506
SCRIPT ERROR: _init: Attempt to call function 'new' in base 'NativeScript' on a null instance.
          At: res://global.gdc:8
Loaded builtin certs
Loading resource: res://MyScene.tscn
Loading resource: res://MyScene.gdc
Loading resource: res://TrackList.gdc
ERROR: add_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1174
SCRIPT ERROR: _ready: Invalid call. Nonexistent function 'set_gme_buffer_size' in base 'Nil'.
          At: res://global.gdc:12
SCRIPT ERROR: _ready: Invalid call. Nonexistent function 'connect' in base 'Nil'.
          At: res://MyScene.gdc:23
SCRIPT ERROR: _play_music: Invalid call. Nonexistent function 'play_music' in base 'Nil'.
          At: res://MyScene.gdc:30
SCRIPT ERROR: _play_music: Invalid call. Nonexistent function 'play_music' in base 'Nil'.
          At: res://MyScene.gdc:30
SCRIPT ERROR: _play_music: Invalid call. Nonexistent function 'play_music' in base 'Nil'.
          At: res://MyScene.gdc:30
```

to even clarify, I also implemented the FLMusicLib into my own project, made the implementation to use that when the music file is the format for the GMEPlayer, and it resulted the same. `Invalid call. Nonexistent function 'play_music' in base 'Nil'`
```
...
res://GameDVDCardtridge/TemplateHexagonEngine/LevelCardtridge/MusicEnjoy/MusicRoom3D.tscn
Queueing Scene res://GameDVDCardtridge/TemplateHexagonEngine/LevelCardtridge/MusicEnjoy/MusicRoom3D.tscn
Queueing Scene res://GameDVDCardtridge/TemplateHexagonEngine/LevelCardtridge/MusicEnjoy/MusicRoom2D.tscn
Set Statuso Flag
Set Statuso Flag
Queue is ready res://GameDVDCardtridge/TemplateHexagonEngine/LevelCardtridge/MusicEnjoy/MusicRoom3D.tscn
Connect Signal 3D
Queue is ready res://GameDVDCardtridge/TemplateHexagonEngine/LevelCardtridge/MusicEnjoy/MusicRoom2D.tscn
Testoid Location= C:/Users/joelr/AppData/Roaming/Perkedel Technologies/Hexagon Engine/TestoidDummy.txt
SCRIPT ERROR: _ready: Invalid call. Nonexistent function 'connect' in base 'Nil'.
          At: res://GameDVDCardtridge/TemplateHexagonEngine/LevelCardtridge/MusicEnjoy/MusicRoom2D.gdc:59
Connect Signal 2D
Show UI Gameplay


(NOTICE)PLEASE DON'T LOSE THE CRACKLES!!! LEFT 15 PCS!!! (NOTICE)


Body Out of Bound = TestoidDrop
openFile = D:/PRIVATE FOLDER/FILE JOEL ROBERT/MP3/Tobu/Tobu - Calling.mp3
Use GME = D:/PRIVATE FOLDER/FILE JOEL ROBERT/MP3/Tobu/Tobu - Calling.mp3
SCRIPT ERROR: PlaySong: Invalid call. Nonexistent function 'play_music' in base 'Nil'.
          At: res://GameDVDCardtridge/TemplateHexagonEngine/LevelCardtridge/MusicEnjoy/MusicRoom2D.gdc:127
```

I haven't tried other GDNativeLibraries yet, so I am not sure whether if the problem was specific to this FLMusicLib or every GDNativeLibs.

I even had added filter non_resource to include which are `.dll`, `.so`, `.dylib`, to no avail.

Is this a bug, or did I do something wrong?

**Steps to reproduce:**

*For FLMusicLib Demo*
- clone https://github.com/MightyPrinny/godot-FLMusicLib/ to make sure you get the latest commit as of now.
- Choose branch `demo`
- this `demo` branch has `project.godot` file in the root here hence, this branch is a Godot project you can load now.
- `▶ Play` the Project
- Choose any of the sample music file from the list on the right `ItemList`
- click `Load` beneath of the list. The Music should play like normal
- Close the test play, 
- now Export this project. Assign the export target for each platform to wherever you like. can be at `../../render/FLMusicLib/` directory with its respective filename or something. Make sure the other export setting for each platform remains unchanged.
- **Important** export all of the binaries with **Debug!!!**
- Open the executable, rendered from the project. Mine has Windows 10, so that will be `.exe`. Maybe will try linux binary later.
- Choose any of the sample music file from the list on right `ItemList`
- click `Load` beneath of the list. **The Music did not play and spits error in the console output like above what happened at section `Issue Description`**.

*For Hexagon Engine* **Warning! over 1 GB in repo size!**
- clone https://github.com/Perkedel/HexagonEngine . Branch is `Master`
- `project.godot` is in the root of this Branch
- `▶ Play` the project
- 2x click `Template Hexagon Engine`.
- wait for *Made with U-word splash screen* to finish
- click `▶ Play` (Start Repeat ⚜)
- Scroll to right so you can see `Music Enjoy` Level Card.
- click `Enjoy The music now!` to play that Enjoy Music Room
- according to this script right here  https://github.com/Perkedel/HexagonEngine/blob/master/GameDVDCardtridge/TemplateHexagonEngine/LevelCardtridge/MusicEnjoy/MusicRoom2D.gd , The FLMusicLib will be used if the file loaded is `.mp3`, `.xm`, `.it`, etc. that is not supported by `AudioStreamPlayer`. so,
- click `Load` on right side
- choose File Access mode. I'll choose `File System (/)`
- choose files that the system would use FLMusicLib, like your favourite MP3. (end repeat 🛑)
- Turn on `Play` button. The MP3 or whatever music you loaded plays. 
- Exit the test play by either go back to editor and press `Stop` top right corner or
- `⏸ Pause`
- Hover `more` button
- `Leave Level`
- `Yes`
- `Exit`
- `Yes`.
- Export to executable to some empty folder.
- open the executable you just rendered (the `.exe` file for Windows), 
- Repeat process from `(Start Repeat ⚜)` to `(end repeat 🛑)`
- Turn on `Play` button. **The MP3 or whatever music you loaded did not play!!! it spits error to console `SCRIPT ERROR: _ready: Invalid call. Nonexistent function 'connect' in base 'Nil'.` like above at section `Issue Description`.**

**Minimal reproduction project:**

Unfortunately, I haven't had time to create minimal reproduction project for now. 
However, the reproduction should be simple by just implementing the asset lib into your experiment project and try to replicate the event, both when editing project & exported.
I would however, make the minimal reproduction project if requested.

**Comment by bruvzg** [comment]
https://github.com/MightyPrinny/godot-FLMusicLib/blob/demo/FLMusicLib/FLMusicLib.gdnlib#L16

Dependencies are missing from the library config and are not exported, see https://github.com/MightyPrinny/godot-FLMusicLib/tree/demo/FLMusicLib/Windows/x86, there are multiple `.dll`s.

**Comment by bruvzg** [comment]
> I even had added filter non_resource to include which are .dll, .so, .dylib, to no avail.

This won't help, GDNative libraries can't be packed to `pck`/`zip` and are placed as separate files alongside executable instead, export process is controlled by `gdnlib` file.
