### ISSUE TITLE
Nondeterministic .tscn data from AnimationBlendTreeNode

### ISSUE THREAD

**Issue by Zoomulator** [godotengine/godot#42788]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10, 1904.508

**Issue description:**
The order of the triplets in the "node_connections" array is nondeterministic, making it annoying to version control files with animaton blend trees as they may change without any actual alterations to the scene.

In my specific case, the diff often looks like this:
![image](https://user-images.githubusercontent.com/1069303/95968665-00c25980-0e0e-11eb-8299-5a9fce657dd2.png)
The array contains the same triplets but in different order.

**Steps to reproduce:**
* Create a scene with a larger animation tree (mine has 9 nodes with 8 connections) and save it.
* Commit the file to version control (GIT).
* Restart Godot, open and save the same file.
* Check the version control diff.
* Retry a few times from step 3 if no diff occurs.

However, it was easy to find the likely cause of the bug in the C++ code:
https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/scene/animation/animation_blend_tree.cpp#L1122-L1138
https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/scene/animation/animation_blend_tree.cpp#L1028-L1041

The .tscn array is created by iterating the elements of a Map, which order is undefined (unless I'm mistaken about the specifics of Godot's Map class). At the very least, the order of the Map elements are somewhat dependent on the insertion order, which may in turn be nondeterministic. Relying on the element order of the map here seems in any case suboptimal for consistent .tscn data.

**Suggested fix:**
The element order needs to be sorted in some way. Alphabetical sorting by each NodeConnection field in turn seems as good as any.

```C++
// I'm not very familiar with Godot's own primitives, but something like this:
int comp_nc(const NodeConnection &a, const NodeConnection &b) const {
  return a.input_node.compare(b.input_node) < 0 || a.input_index < b.input_index || a.output_node.compare(b.output_node) < 0;
}
// ...
bool AnimationNodeBlendTree::_get(const StringName &p_name, Variant &r_ret) const {
  //...
  List<NodeConnection> nc;
  get_node_connections(&nc);
  std::sort(nc.begin(), nc.end(), &comp_nc);
  //...
}
```

**Comment by Calinou** [comment]
Note that we don't use `std::sort` in the engine.

**Comment by 1029chris** [comment]
We've been encountering this bug as well, it's not too big a deal to just discard the changes before pushing, but it's still annoying.
