### ISSUE TITLE
Custom Android Plugin (Godot 3.1) cannot execute method from .so file

### ISSUE THREAD

**Issue by SilvanaP** [godotengine/godot#42796]
**Godot version:**
3.1.2

**OS/device including version:**
Android 8.0, Huawei P20lite

**Issue description:**
I am working on a quite experimental project where I need various functionalities from Android, so I started to develop my own Android Modules for Godot which works good so far. (I was able to get scan/connect to Bluetooth Peripherals with the the native BTManager and so on. )

I would now need to access some C/C++ Code from an .so file but this is where I am stuck. I am able to load the library via System.loadLibrary("mySOLib"), but when running my app I end up with the error _"No implementation found for java.lang.String org.godotengine.godot.GodotNdk.stringFromJNI()"_. I am very sure that the implementation exists but cannot be found for some reason. So I wanted to ask: Is this a bug in Godot? Is it even possible to call methods from .so files in a custom module?

**Comment by Calinou** [comment]
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by SilvanaP** [comment]
Of course, here is the project as zipfile: https://fromsmash.com/soTemplates

When I run this, the app crashes but I get the following message in logcat:
`10-15 15:15:20.101 21175 21207 I godot   : 1.) NDK MODULE FOUND
10-15 15:15:20.102 21175 21207 E zygote64: No implementation found for java.lang.String org.godotengine.godot.GodotNdk.stringFromJNI() (tried Java_org_godotengine_godot_GodotNdk_stringFromJNI and Java_org_godotengine_godot_GodotNdk_stringFromJNI__)
` 

The .so-file I use is the one from Android's [JNI sample:](https://developer.android.com/ndk/samples/sample_hellojni) and it should return a string when calling `stringFromJNI()`. (As I just wanted to test if addressing .so files generally works before digging deeper into writing my own c/c++ code.)

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
@SilvanaP I'd recommend to update to the latest stable version Godot version and use the [updated Android plugin system](https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html) as it's a lot more modular (doesn't require engine modification) and allow usage of C/C++ code/libraries.

**Comment by SilvanaP** [comment]
@m4gr3d My problem is that I also need an iOS module, and from v 3.2+ on, there is only a doc for Android plugins. So I assumed that iOS plugins are not possible for the newest versions? I would love to use the new system, it seems so much more convenient and I am also not happy with compiling the engine every time I make a change in my modukes... >_<

**Comment by m4gr3d** [comment]
@SilvanaP 3.2 should have the same capabilities as 3.1, so iOS module are still possible. They just haven't been updated in a similar manner as Android plugin and may still require engine recompilation.

However @naithar is working on improving the state of iOS plugins, so it may be getting better soon.

**Comment by naithar** [comment]
@SilvanaP iOS plugins are ready and waiting for merge for both `master` and `3.2`. But since `3.2.4` is mostly bugfixes and it already has a lot of changes for iOS, I don't think it'll make into stable branch. Also Godot will require additional changes to remove modules from Godot to remake them into plugins, just like Android did.
But plugins are usable and working, so it can be used in your own Godot fork.

**Comment by m4gr3d** [comment]
@naithar I think `3.2.3` was the bugfix release. Unless there are several issues that needs addressing for iOS, you may be able to include your changes for `3.2.4`.
cc @akien-mga

**Comment by SilvanaP** [comment]
@naithar @m4gr3d Thanks for the info, I thought iOS plugins simply vanished in 3.2. I will talk with my team colleagues about how we will proceed, maybe we will switch to the newer system then.
