### ISSUE TITLE
Don't hardcode res://addons/ path

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#4279]
**Problem:**

Currently, addons path is hardcoded to point to `res://addons/*` [as evidenced by code](https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/tools/editor/editor_plugin_settings.cpp#L22).

Before addons were introduced, the only hardcoded paths were `res://engine.cfg`, `res://export.cfg` and `res://override.cfg`, all of which are `.cfg` files (I might be missing some of them though, that is based on a quick code search). In other words, even though we configure all paths in `engine.cfg` and `export.cfg`, addons are all folders in a hardcoded folder, without `.cfg` files for listing them, and/or allowing them to go in other directories (E.g. "What if I want them to go in `res://vendor/plugins/`?").

**Proposed solutions:**

1. Allow the `res://addons/` path to be changed in `engine.cfg`.
  * **Pros:** Would allow for a bit more freedom when choosing a project structure. (E.g., I can move all addons under the `sahder/addons` folder instead.)
  * **Cons:** The auto-installer/addon lib just got a bit more complex...
2. Add a `[addons]` section to `engine.cfg`, where addons are listed as paths to their respective `plugin.cfg` or folder.
  * **Pros:** Would allow some addons to be enabled and others disabled, without moving the folders around.
  * **Cons:** Harder to manually add an addon, maybe an installer GUI would be necessary.
3. Add a `addons.cfg` file, which contains that section instead of `engine.cfg`
  * **Pros:** Better division of concern, `engine.cfg` is less bloated.
  * **Cons:** One more hardcoded path, `engine.cfg` isn't that big yet.

Note that if 2 or 3 is chosen, it might be nice to include the link/git repo from which the addon was downloaded, so we would be able to distribute the project without the addons inside. (Or.... git submodules to the rescue `;)`)

**Comment by vnen** [comment]
The current [plugins demos](https://github.com/godotengine/godot-demo-projects/tree/aae4e30162897252f05185b4d3d5e477c1f800af/plugins) all use hardcoded the `res://addons` path. So it'd nice for the plugins to have a way to retrieve their current path. Though most of the time relative paths can be used, there may be cases where an absolute path is needed.

**Comment by akien-mga** [comment]
We should probably decide upon this one before publishing 2.1-stable, as if we change things later on it will break compatibility.

**Comment by bojidar-bg** [comment]
Ok, thinking about it, it would be better if it is left hardcoded, because:

* Having to check engine.cfg before manual unzip installation of plugins is terrifying
* The asset library already depends on this
* Telling users "put this zip into the addons folder, except if you have changed the path or..." is not a very good experience in general
* It isn't that hardcoded as it sounds. Also, you would not usually use the `res://addons/` path for anything game-specific anyway.

I still think that there should be a way to update and/or store links to installed assets though.
