### ISSUE TITLE
SpriteFrames not working with TextureAtlas!?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#42806]
**Godot version:**
3.2.3

**OS/device including version:**
Ubuntu 20

**Issue description:**
I have a couple files like this that I am using to create a SpriteFrames for an AnimatedSprite.

![Arrow](https://user-images.githubusercontent.com/962340/96061711-e9ad5700-0e61-11eb-8a12-03ca6916a3e7.png)

It works fine until I change import settings to combine some into a TextureAtlas? Then It changes and I cannot select the right tiles?

**Steps to reproduce:**

1. animation is fine
2. combine with other files into atlas
2. animation broke?

![Peek-2020-10-12-15-58](https://user-images.githubusercontent.com/962340/96061758-021d7180-0e62-11eb-815d-5efb6d94ab39.gif)

I have seen some related issues like this: https://github.com/godotengine/godot/issues/9340 but none really the same I think.

**Minimal reproduction project:**
https://github.com/rakkarage/TestAtlasAtlas

Thanks.

**Comment by Calinou** [comment]
Support for AtlasTexture was added to SpriteFrames in https://github.com/godotengine/godot/pull/37939.

**Comment by Calinou** [comment]
@rakkarage You should be able to work around this by following the steps described here: https://github.com/godotengine/godot/pull/51030#issuecomment-899390081
