### ISSUE TITLE
Anrdoid: Xbox wireless controller triggers reversed

### ISSUE THREAD

**Issue by ndarilek** [godotengine/godot#42801]
My game currently exports for Linux, Windows, UWP, MacOS, and the web. On these platforms, my Xbox wireless controller's left and right triggers are correct. Under Android, though, they are reversed. They behave well otherwise--they're just opposite to every other platform.

**Comment by Zireael07** [comment]
@ndarilek: Did your screen reader not read the issue template to you, maybe?

**Comment by ndarilek** [comment]
I'm sorry, it didn't. I'll close this and open a new one.

How do you actually use the issue templates? I kind of hit <repo>/issues/new on autopilot, and there's no obvious way to use a template that way--at least, not to me.

Thanks, and apologies for getting it wrong.

**Comment by ndarilek** [comment]
OK, figured it out, I need to use the actual button, which takes me to issues/choose. Sorry, hitting the URLs is generally faster than tabbing/arrowing through controls, so I do that from muscle memory. I'll use the templates going forward.
