### ISSUE TITLE
Vulkan: Environment "Fixed" fog is displayed on top of volumetric fog if there's no solid surface behind

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#42820]
**Godot version:** Git https://github.com/godotengine/godot/commit/a22c7eff0

**OS/device including version:** Fedora 32, GeForce GTX 1080 (NVIDIA 450.66)

**Issue description:**

When "fixed" (non-volumetric) fog is enabled, it displays on top of volumetric fog if there's no solid surface behind it (i.e. the sky is the background). It works fine if there's a solid material behind the fogged surface.

This is probably not intended; the volumetric fog should always display on top, like it does when only volumetric fog is enabled.

## No fog (OK)

![No fog](https://user-images.githubusercontent.com/180032/96122887-6b4cc580-0ef2-11eb-8657-04be292e232f.png)

## Only "fixed" fog enabled (OK)

![Only "fixed" fog enabled](https://user-images.githubusercontent.com/180032/96122922-71db3d00-0ef2-11eb-8d71-407f8653bd85.png)

## Only volumetric fog enabled (OK)

![Only volumetric fog enabled](https://user-images.githubusercontent.com/180032/96122120-51f74980-0ef1-11eb-9b97-5e9c359a5ef5.png)

## Both "Fixed" and volumetric fog enabled (broken)

![Both "Fixed" and volumetric fog enabled](https://user-images.githubusercontent.com/180032/96122343-a1d61080-0ef1-11eb-8ad8-addd9eefcab7.png)

**Steps to reproduce:**

Toggle fog on and off by editing `default_env.tres` in the minimal reproduction project.

**Minimal reproduction project:** [test_gpu_particles.zip](https://github.com/godotengine/godot/files/5384773/test_gpu_particles.zip)

**Comment by clayjohn** [comment]
I wonder if it is enough to just switch the order that fog is applied in the sky and scene shaders 

https://github.com/godotengine/godot/blob/5971a97a0c5e535014ff940d8cf6a474b4860857/servers/rendering/rasterizer_rd/shaders/sky.glsl#L226-L234

https://github.com/godotengine/godot/blob/5971a97a0c5e535014ff940d8cf6a474b4860857/servers/rendering/rasterizer_rd/shaders/scene_high_end.glsl#L2729-L2739

https://github.com/godotengine/godot/blob/5971a97a0c5e535014ff940d8cf6a474b4860857/servers/rendering/rasterizer_rd/shaders/scene_high_end.glsl#L2750-L2758
