### ISSUE TITLE
Parser Error: Cannot find property "rotated" on base "Basis"

### ISSUE THREAD

**Issue by farahats9** [godotengine/godot#42834]
**Godot version:**
v4.0.dev.custom_build.ea21b8ff8

**OS/device including version:**
Windows 10 version 2004

**Issue description:**
I am trying a code that works on v3.2.3 to use gyroscope to rotate an object
```
func rotate_by_gyro(p_gyro, p_basis, p_delta):
	var b = Basis()
	
	b = b.rotated(p_basis.x, -p_gyro.x * p_delta)
	b = b.rotated(p_basis.z, -p_gyro.z * p_delta)
	
	return b * p_basis
```

but I get an error `Parser Error: Cannot find property "rotated" on base "Basis".` this used to work on previous builds of godot v4.0
also when I check the help for Basis I get this:
![image](https://user-images.githubusercontent.com/463359/96174713-fc8b5e80-0f29-11eb-9faa-6aeb088545db.png)

**Steps to reproduce:**
use the following code to reproduce
```
func rotate_by_gyro(p_gyro, p_basis, p_delta):
	var b = Basis()
	
	b = b.rotated(p_basis.x, -p_gyro.x * p_delta)
	b = b.rotated(p_basis.z, -p_gyro.z * p_delta)
	
	return b * p_basis

func _physics_process(delta):
	var gyro = Input.get_gyroscope()
	var new_basis = rotate_by_gyro(gyro, $Area3D.transform.basis, delta).orthonormalized()
	print(new_basis)
```

**Comment by Calinou** [comment]
This is likely a regression from https://github.com/godotengine/godot/pull/42826.

**Comment by qarmin** [comment]
String class have 3 missing functions:
-  begins_with
- find
- replace

**Comment by qarmin** [comment]
In code they look different than others: 
https://github.com/godotengine/godot/blob/c8716734ebad5fd34ead55bd0106b0f6cba16d9d/core/variant_call.cpp#L1365-L1369
