### ISSUE TITLE
OS move_to_trash() on Linux is not compliant with the Freedesktop specification

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#42840]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux mint

**Issue description:**
In Godot modifying files externally is generally a bad idea as things may break inside Godot, so the approach is to use the IDE.

Unlike almost most IDEs, when you select DELETE on an item in the FileSystem dock they are removed permanently (yes, I know there is a message saying this), they are not removed to the current operating system Trash.

This is quite a dangerous thing and all other editors simply send the files to the Trash. I know this because I decided to tidy up some files before committing and accidentally deleted all the files I had created and worked on in the past few hours as I'd selected a couple by mistake.

**Steps to reproduce:**
1. create a file
2. Use Godot to delete it
3. No getting it back

**Comment by Calinou** [comment]
>  they are not removed to the current operating system Trash.

This is supposed to happen, but it's not working for some reason: https://github.com/godotengine/godot/pull/41263

**Comment by chucklepie** [comment]
I'm on Linux Mint Mate and it definitely wipes all the files. It's just Godot, all other editors send them to the Trash.

I can try 3.2.3?

**Comment by chucklepie** [comment]
Right, time to apologise ;)

Looks like what has happened is I didn't find the files because for some reason when I delete from Godot the Trash items do not have a timestamp and I was looking by recent date. Is this a coincidence? because deleting from file manager adds date/time but inside Godot the stamp is left out.

![image](https://user-images.githubusercontent.com/12863685/96186558-825fd780-0f33-11eb-9e4e-2eacbd1e23a6.png)

**Comment by Anutrix** [comment]
I suggest you rename the issue title.

**Comment by akien-mga** [comment]
As seen in #41263, the problem is that our implementation of `OS::move_to_trash()` for Linux/*BSD (in `platform/linuxbsd/os_linuxbsd.cpp`) does not generate `.trashinfo` files that describe the trashed files and can be used to restore them.

The implementation should be reviewed to ensure that it follows the [Freedesktop Trash specification](https://specifications.freedesktop.org/trash-spec/trashspec-latest.html).

Here's our relevant code:
https://github.com/godotengine/godot/blob/7a2d721536688d0e8afefbe31cb9f4a35ed718ba/platform/linuxbsd/os_linuxbsd.cpp#L305

**Comment by nalinwadhwa02** [comment]
If this issue has not been picked by anyone, can I pick it up?

**Comment by dalexeev** [comment]
The issue is still not fixed in `3.2.4.beta6.official`.

**Comment by Calinou** [comment]
@dalexeev https://github.com/godotengine/godot/pull/44021 needs to be remade for the `3.2` branch to fix it there.
