### ISSUE TITLE
Vulkan: SSS Does not seem to work

### ISSUE THREAD

**Issue by NHodgesVFX** [godotengine/godot#42869]
**Godot version:**

Godot v4.0.dev.calinou.94e5f66cb

**OS/device including version:**

Vulkan, RTX2080 Driver: 456.71 Windows 10 64Bit

**Issue description:**

when enabling subsurface scattering the mesh becomes transparent.

![SSS_Issue](https://user-images.githubusercontent.com/11403345/96336155-9139ad80-104b-11eb-936f-37927b8ea0ac.JPG)

**Steps to reproduce:**
Create a mesh, assign a material, enable subsurface scattering 

**Minimal reproduction project:**

[SSS.zip](https://github.com/godotengine/godot/files/5395558/SSS.zip)

**Comment by seadra** [comment]
Same here, CLI is filled with the following error:

> ERROR: Source and Destination textures must be the same format.
>   at: texture_resolve_multisample (drivers/vulkan/rendering_device_vulkan.cpp:2783)

**Comment by akien-mga** [comment]
Fixed by #50186.
