### ISSUE TITLE
Make Sub-Resources Unique shortcut clears itself randomly

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#42862]
**Godot version:**

3.2.3

**Issue description:**
This is a weird one, but I created a shortcut for the Make Sub-Resources Unique action and my problem is that it's cleared randomly. I mean some time after creating it I find out that it's gone, so I have to bind it again, but it keeps happening. I have other custom shortcuts and this doesn't happen. No idea what could be the cause.

**Steps to reproduce:**
1. In Editor Settings bind a shortcut for Make Sub-Resources (in my case I use `Ctrl + Shift + D`
2. Close and reopen Godot few times?
3. Wait few days???
4. Notice that eventually the shortcut is gone

**Comment by gvaneyck** [comment]
I was able to reproduce this.  This can affect all shortcuts not defined during the initial Godot startup.

*Steps to reproduce*
1. Start Godot
1. Add a Node2D or select an existing one (this loads/defines the shortcut for `property_editor/make_subresources_unique`)
1. Open Editor Settings
1. Set the shortcut for Property Editor > Make Sub-Resources Unique
1. Close Editor Settings
  OBSERVE: Godot's settings file (e.g. `C:\Users\<User>\AppData\Roaming\Godot\editor_settings-3.tres`) has a shortcut defined for `property_editor/make_subresources_unique`
1. Close Godot
1. Start Godot
  OBSERVE: Godot's settings file is updated during startup and no longer has a shortcut for `property_editor/make_subresources_unique`
  EXPECTED: Godot saves all shortcut whether or not they have been initialized with `ED_SHORTCUT`

If you select a Node2D, then open/close the Editor Settings dialog, the shortcut is restored from memory and re-saved to the settings file.  However, if you close Godot before doing that, it is gone from the file forever.

**Comment by maniacalipsis** [comment]
Have the same issue with Upper/Lower case shortcuts in text editor. In my case these shortcuts are reset at the second editor launch after that one when shortcuts was set.
And that's I found: 
First I set these shortcuts to e.g. Ctrl+U and Ctrl+L correspondently.
Then I opened the <homefolder>/.config/godot/editor_settings-3.tres and found that subresource IDs of these shortcuts aren't in the order: they had IDs 43 and 44 and was placed between subresources 12 and 13. And the last subresource in list was 42.
The same order was in the array named shortcuts.
And when I closed and reopened the editor, it has modified config at startup and deleted these irregulari placed 43 and 44 subresources and script_text_editor/convert_to_...case ele,ents that had refers to them. But in the editor these shortcuts remained available. And I found that if open and just close the editor settings at this moment  these shortcuts will be restored into the config file and thus they will live one session longer. But if don't do so, they will be forgotten.

Unfortunately I have no enough time to search problem in the source code, but think that it is somewhere arount this irregular sequence of IDs or in the processing of it. Hope this will be helpful.

**Comment by KoBeWi** [comment]
I can no longer reproduce it in 3.5 or 4.0 with the steps described above. Although I didn't use this shortcut for a while, so I didn't pay enough attention to tell if this is really fixed.

**Comment by maniacalipsis** [comment]
I hadn't tested this issue since that time, because I had manually edited the config file (as I remember) and then just made it readonly by changing permissions.
However in the 4.0a3 all hotkeys changes I was made, including an additional hotkeys, are works fine. P.S. and I like that way how it's made in 4.0.

**Comment by KoBeWi** [comment]
I will just close this for now.
