### ISSUE TITLE
Label Limited to 1 Character Wide with Autowrap Inside ScrollContainer

### ISSUE THREAD

**Issue by Zarraya** [godotengine/godot#42887]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
When placing a label inside of a scroll container node with the autowrap property set to true, the label text is limited to one character wide. Turning autowrap off will fix this issue, but text may now exceed the desired width of the control, especially if the text is set via a script. Note that the scroll container can have horizontal scrolling enabled or disabled, the result is the same.

**Minimal reproduction project:**
[ScrollContainerBug.zip](https://github.com/godotengine/godot/files/5397982/ScrollContainerBug.zip)

**Comment by Calinou** [comment]
Try setting the Label's Min Size to the desired width.

**Comment by KoBeWi** [comment]
This is not a bug, you need to enable Expand in horizontal size flags.
