### ISSUE TITLE
Wrong parse error line number (GDScript)

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#42884]
**Godot version:**

3.2.3

**OS/device including version:**

Windows

**Issue description:**

![wrong error lineno](https://user-images.githubusercontent.com/16458555/96365807-a3efd780-115c-11eb-97a9-e7f6496d3e90.JPG)
Got parse error at line 3
`Parse Error: Variable "x" already defined in the scope (at line 1).`
Expected line **2**, not line **3**

**Steps to reproduce:**
Create a script (I named it `new_script.gd`) with this code:
```gdscript
func a(x):
	var x
	print(1)
```

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Also valid in 6a8dfdb

**Comment by akien-mga** [comment]
Fixed for `3.2` branch with #43019, but it has yet to be fixed in `master`.

**Comment by bati22** [comment]
I have reproduced the bug and also found some new cases. I attach screenshots.
![10](https://user-images.githubusercontent.com/40314986/105410607-7b331e80-5c32-11eb-83be-528b5554a5aa.png)
![11](https://user-images.githubusercontent.com/40314986/105410608-7bcbb500-5c32-11eb-9e6f-dd884e1e2338.png)
![13](https://user-images.githubusercontent.com/40314986/105410610-7c644b80-5c32-11eb-8b4c-d2fff19abc89.png)

Godot version:
Godot 3.2.3.stable

OS/device including version:
Ubuntu 20.04.1 LTS

**Comment by lyuma** [comment]
Still occurs in master (85186bc)

**Comment by dalexeev** [comment]
Fixed.

![](https://user-images.githubusercontent.com/47700418/218118375-b0f28910-ee00-49d2-ab44-5d5fb6e7f8ee.png)
