### ISSUE TITLE
Scene not instancing in _ready() when called from a child node

### ISSUE THREAD

**Issue by Skyvastern** [godotengine/godot#42897]
**Godot version:**
Godot 3.2.2 and 3.2.3

**OS/device including version:**
Windows 10 Professional 64-bit

**Issue description:**
When trying to instance a scene ( PackedScene ) from _ready() / _enter_tree() function, then if the node from which we are calling it is a child, then the PackedScene does not get added to the tree. Whereas, in the _process() the scene gets added normally.

This only happens with a child node, and with child I mean any child of our main scene at the topmost level ( root -> main ).

**Steps to reproduce:**
• Add a script to any child object
• Then, instance a PackedScene from _ready() or _enter_tree()

```
export(PackedScene) var scene

func _ready():
	var clone = scene.instance()
	get_tree().root.get_child(get_tree().root.get_child_count()-1).add_child(clone)
```

**Minimal reproduction project:**
[InstancingDebug.zip](https://github.com/godotengine/godot/files/5401799/InstancingDebug.zip)

**Comment by timothyqiu** [comment]
I think the error output in the debugger shows the reason and the proper way to add child in `_ready`:

> add_child: Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.

**Comment by Skyvastern** [comment]
> I think the error output in the debugger shows the reason and the proper way to add child in `_ready`:
> 
> > add_child: Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.

Ahh yes. I totally forgot to check the error output. As the scene continued running without any pause, I must have ignored that error output. I was scratching my head for hours as I didn't found any result on Google about this. Will remember to double check the error window from now on. Thank You! :)
