### ISSUE TITLE
Default value of Sprite3D Alpha Cut is null

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4290]
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
Default value of Sprite3D Alpha Cut is null.
Debugger panel shows an error if this remain null.

**Steps to reproduce:**
1. Add Sprite3D to scene
2. Run

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by bojidar-bg** [comment]
This seems to have been fixed by #/14784, though it is not backported to 2.x yet.

**Comment by akien-mga** [comment]
Thanks, fixed in 3.0 then by #14784. I've backported the fix to 2.1 as 1d0b8219c.
