### ISSUE TITLE
Wrong definition and formula for Color.contrasted()

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot#42922]
Doc description;
> Color.contrasted()
> Returns the most contrasting color.

Opposite color(complementary color) do not mean that the contrast is high. The contrast of the two hue is measured by relative luminance.

I don't know what this formula calculates (it looks like complementary colors) but it's certainly not contrast.
https://github.com/godotengine/godot/blob/27763b67bb63139319bf611590c40e48663e72d6/core/color.cpp#L220
```
void Color::contrast() {
	r = Math::fmod(r + 0.5, 1.0);
	g = Math::fmod(g + 0.5, 1.0);
	b = Math::fmod(b + 0.5, 1.0);
}
```

A Python library for computing contrast ratios, as required by WCAG 2.0.
https://github.com/gsnedders/wcag-contrast-ratio

I found this so maybe it would be useful.
https://gamedev.stackexchange.com/questions/38536/given-a-rgb-color-x-how-to-find-the-most-contrasting-color-y

**Comment by Ev1lbl0w** [comment]
I made a visualization of the color changes from those methods and the formula from the linked Stackexchange post, to aid with discussion:

![image](https://user-images.githubusercontent.com/6501975/96611284-658d2080-12f4-11eb-9f93-7fde29d712ac.png)

From what I can see, `.contrasted()` does not make complementary colors; `.inverted()` does.

**Comment by Ev1lbl0w** [comment]
Godot already has the `inverted` method which effectively swaps the color to it's complementary. And I agree: I'm not seeing the usefulness of the `contrast` method. From what I've seen the code hasn't been changed since the _dawn of Godot_ *(the first commit)*, so it might indeed be something laying around and long forgotten :stuck_out_tongue:

**Comment by hazarek** [comment]
> Godot already has the `inverted` method which effectively swaps the color to it's complementary.

I have not noticed, sorry. Formulas and descriptions need to be approached more scientifically. I reviewed Godot's color methods now. Godot's descriptions do not give confidence.

**Comment by clayjohn** [comment]
@hazarek some of the descriptions indeed need work. The focus in the past was on getting _something_ in the class reference for each method. However, many methods lack clarity or depth. 

If you understand how the method descriptions can be improved, please make suggestions here or, preferably, in a PR

**Comment by Calinou** [comment]
PS: Replacing or removing the `constrated()` method should be debated in a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by hazarek** [comment]
> PS: Replacing or removing the `constrated()` method should be debated in a [proposal](https://github.com/godotengine/godot-proposals).

The discussion has already been done here and it's over.

**Comment by Calinou** [comment]
@hazarek The only thing we can do without breaking backwards compatibility is improving the existing documentation. If you want the method's behavior to change, you need to open a proposal for that.
