### ISSUE TITLE
godot should un-lock mouse in case of being stopped due to error

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4292]
**Operating system or device:**
Any (Linux)

**Issue description** (what happened, and what was expected):
The damn cursor stays locked and unusable if execution is stopped because of errors,
which is really damn annoying

**Steps to reproduce:**
Use mouse locking in your code, do some bad code (to be executed later than that),
have fun.

**Comment by akien-mga** [comment]
Duplicate of #2232. The latter hints that it might be X11-specific, that might be interesting to check.
