### ISSUE TITLE
Scan thread aborted warning

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#42923]
**Godot version:**

3.2 branch at commit 4a92d2111b40e9bf80be382c52b95addff82beeb

**OS/device including version:**

Arch Linux

**Issue description:**

Opening and closing the editor started yielding a scan thread aborted warning when a project of mine and turns out the issue is some SVG files for some reason. I think this started happening recently, perhaps within the last week or so.

**Steps to reproduce:**
1. Create empty project
2. Copy all the Godot [SVG icons](https://github.com/godotengine/godot/tree/master/editor/icons) to the project folder
3. Once Godot is finished importing the resources, close Godot. You'll get a scan thread aborted warning.

Further opening and closing the same project will yield the same warning.

```
WARNING: _notification: Scan thread aborted...
   At: editor/editor_file_system.cpp:1130.
```

**Minimal reproduction project:**

[scan_thread_aborted.zip](https://github.com/godotengine/godot/files/5405830/scan_thread_aborted.zip)

**Comment by Rubonnek** [comment]
Can't reproduce this issue with v3.2.3.rc6

**Comment by akien-mga** [comment]
I can't seem to reproduce this reliably myself on 9de391e9a7aa53e14320aca1ea8c17c4edd6021a. I've tried reimporting the assets 10 times (clearing `.import/`) and after each reimport close the editor, then reopen it and close it again, and out of all these I only got the "Scan thread aborted..." warning once.

I think this warning can happen if you open the editor and close it right away while it's still scanning to see if there are files to import/reimport.

As I can't reproduce it systematically, it's hard to see if it's really a regression.

**Comment by Rubonnek** [comment]
Mmm... I'm able to reproduce constantly on my end and I even waited 30 seconds or so without touching the editor. I can also reproduce it without having to reimport.

I'll dig deeper. I wonder if it's a GCC 10.2 bug of some sort.

Thanks for the feedback!

**Comment by akien-mga** [comment]
I'm also building with GCC 10.2. But it might well be caused by a system component, or possibly it's project-specific and happens because of your Godot cache or project metadata.

**Comment by Rubonnek** [comment]
I cleaned my cache and config:

```
rm -rf /home/wilson/.config/godot
rm -rf /home/wilson/.cache/godot
rm -rf /home/wilson/.local/share/godot
```

and my system is not under any load and I can still reproduce it even after waiting 30 seconds or so without reimporting the SVGs. I also run a very minimal Linux environment.

I started blaming the kernel. I switched it to 5.9.1 and now it's harder to reproduce this issue with it.

I'm still going to grab a few backtraces of this scan thread, and maybe even make a flame graph. I'm not familiar with that scan thread code, but I'd like to be. I'll close this issue if I don't find anything of substance in a week or so.

**Comment by Rubonnek** [comment]
Welp, there's definitely a regression performance-wise at the very least. There's something eating CPU cycles badly between v3.2.3 stable and 4a92d21.

I have another project where I'm seeing this scan thread warning, and that project starts in less than a second with v3.2.3 (this includes the Editor and running the project itself), but with 4a92d21 the Editor takes around 5 seconds to start and running the project about 3 to 4.

I'll keep digging.

**Comment by Rubonnek** [comment]
Welp, I did some more testing today and I'm chalking this up to external changes. I don't know what the cause was, but I've been using Godot with all optimizations disabled (-O0) for months and I never saw that scan thread warning pop until recently.

I did a full system update recently too, and right after that I recompiled Godot which is when I think the scan thread warning started to popup. At this point it seems like whatever caused this issue is unrelated to Godot.

**Comment by akien-mga** [comment]
Indeed, I also wondered for a second at some big difference in import speed, but I was testing with 3.2.3-stable (optimized official build) and a custom build from `3.2` (debug, unoptimized, thus slower).

**Comment by germanbv** [comment]
did you manage to solve this issue? I'm on Windows 10 using v4.1 and this issue started to trigger every single time I work on my project... this started to happen after installing a plugin.. but now it doesn't matter what I do... I've tried disabling that plugin, removing it, removing files, and deleting the .godot folder... nothing seems to work... the weird thing is that this issue doesn't trigger on other projects... even after installing the plugin that caused it...
