### ISSUE TITLE
Importing assets loading bar always on top (DisplayServer regression)

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot#42934]
**Godot version:** master on 5ddfc657a

**OS/device including version:**
Arch Linux, GNOME 3.38 on Wayland

**Issue description:**
The Importing Assets loading bar stays always on top, even when the editor window is minimized.
![Screenshot from 2020-10-20 15-28-52](https://user-images.githubusercontent.com/36982494/96580219-007ffd80-12e9-11eb-999d-95e4c21f4462.png)
It even ignores changing workspaces in GNOME and doesn't move.

**Steps to reproduce:**
1. Load a project, preferrably with many unimported assets
2. Minimize the editor window
3. Loading bar always on top

**Comment by Calinou** [comment]
I can confirm this on `master` 52b7d5fa3. This logically does not occur if single-window mode is enabled.

**Comment by KoBeWi** [comment]
Does it still happen in newest alpha?

**Comment by Zireael07** [comment]
Yep! I can confirm on alpha... 6 I think,or 7 (haven't gotten the newest one yet), and Linux Manjaro KDE.

**Comment by Tooniis** [comment]
Yes. Can reproduce in alpha 9

**Comment by coppolaemilio** [comment]
@Tooniis Is this still a thing in the latest beta?

**Comment by clayjohn** [comment]
Yep, I'm still seeing it as of Beta 17 on PopOS 22.04 X11

**Comment by akien-mga** [comment]
Are you sure you're testing Beta 17? We literally fixed this yesterday.

**Comment by akien-mga** [comment]
Fixed by #72439.
