### ISSUE TITLE
Sprite/ColorRect: using "onready var" reference won't visually update the rect_size/scale during runtime

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#42933]
**Godot version:** 3.2.3 stable

**OS/device including version:** Win64

**Issue description:**
I have a node 2D with a ColorRect as child and want to change the rect_size in code:

##### this works #####
```
extends Node2D

func _process(delta):
	if Input.is_action_just_pressed("ui_accept"):
		$ColorRect.rect_size.x += 10
		print($ColorRect.rect_size.x)
```

##### this does not work #####
```
extends Node2D

onready var color_rect_x = $ColorRect.rect_size.x

func _process(delta):
	if Input.is_action_just_pressed("ui_accept"):
		color_rect_x += 10
		print(color_rect_x)
```
**Both will print the rect_size changes correctly in the output panel**, but in the `onready var` example, the visual representation of the ColorRect does not change. As expected, assigning the ColorRect to the variable in `_ready()` has the same effect as `onready var`.

Same applies to Sprite:

##### works #####
```
extends Node2D

func _process(delta):
	if Input.is_action_just_pressed("ui_accept"):
		$Sprite.scale.x += 0.1
		print($Sprite.scale.x)
```

##### does not work #####
```
extends Node2D

onready var sprite_scale_x = $Sprite.scale.x

func _process(delta):
	if Input.is_action_just_pressed("ui_accept"):
		sprite_scale_x += 0.1
		print(sprite_scale_x)
```

**Comment by Zylann** [comment]
Unless I misunderstand something, your code examples are not equivalent at all.
In your `work` examples, you increment the scale on the node directly, so yeah it updates the node.
In your `does not work` examples, you put the scale in a member var, *and increment the member var*. This will obviously not  update the node. Integer variables are not references, so that's expected.

**Comment by Calinou** [comment]
Closing per @Zylann's comment.

**Comment by golddotasksquestions** [comment]
Thank you for the thorough explanation, @Zylann , that totally makes sense!
