### ISSUE TITLE
Viewport.CLEAR_MODE_ONLY_NEXT_FRAME does not work as expected

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#42937]
**Godot version:**

3.2 branch at commit 4a92d2111b40e9bf80be382c52b95addff82beeb

**OS/device including version:**

Arch Linux

**Issue description:**

Took a screenshot using GDScript in one of my projects and then I noticed the Viewport was not rendering my targets correctly -- the sprite I was moving around the screen started to leave a trail which it shouldn't in that project.

This issue should be reproducible in any project, as long as the following executes:

```gdscript
get_viewport().set_clear_mode(Viewport.CLEAR_MODE_ONLY_NEXT_FRAME)
```
And if you keep keep a look at the Viewport clear mode with `get_viewport().get_clear_mode()`, you can see its value gets stuck at `Viewport.CLEAR_MODE_ONLY_NEXT_FRAME` instead of switching back to `Viewport.CLEAR_MODE_NEVER` after one frame as stated in the documentation.

**Steps to reproduce:**
1. Run the attached project.
2. Press W to change the viewport clear mode to `Viewport.CLEAR_MODE_ONLY_NEXT_FRAME`
3. Use the arrow keys to move the sprite around, it will leave a trail when it shouldn't.
4. Press W to change the viewport clear mode to it's default value

**Minimal reproduction project:**

[viewport_clear_mode_bug.zip](https://github.com/godotengine/godot/files/5408792/viewport_clear_mode_bug.zip)

**Comment by Rubonnek** [comment]
I was able to reproduce on builds all the way back to 3.1, but I remember not encountering this issue sometime around August 16, 2020.

Maybe it was fixed, and then regressed?

**Comment by clayjohn** [comment]
The second part about the viewport enum not changing is tracked here https://github.com/godotengine/godot/issues/33351

**Comment by Rubonnek** [comment]
Then this is a duplicate of #33351.

I need to get in the habit of checking previous issues before I open one. I keep forgetting every now and then.

Thanks!
