### ISSUE TITLE
Mesh class needs to be un-crippled

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4293]
For a long time the Godot supports accessing  mesh internals only using GLES calls,
and it is basically disabled in many configurations. While geometry is there, Godot can't access it.
which is really not justifiable. So Mesh surfaces access method should be implemented
without using GLES where this path is not supported.
Access to geometry data is really useful for various mesh processing and preparing
internal assets, like collision helpers.

**Comment by akien-mga** [comment]
Is this still relevant in the current stable branch? (i.e. does the Mesh API still need to be extended for more geometry data access?)

**Comment by Calinou** [comment]
@slapin Bump :slightly_smiling_face:

Is this still relevant in the current `master` branch?

**Comment by slapin** [comment]
Thanks for asking.
No. Now ArrayMesh is good enough. There are ways to improve it, like block
operations to overcome gdscript slowness with loops,
but as it comes to this particular issue, I think it can be closed.

**Comment by Calinou** [comment]
@slapin Thanks for replying :slightly_frowning_face: I'll close this then.
