### ISSUE TITLE
Button node does not work with focus_neighbour_* properties

### ISSUE THREAD

**Issue by Salvakiya** [godotengine/godot#42956]
[buttongrid.zip](https://github.com/godotengine/godot/files/5413361/buttongrid.zip)

**Godot version:**
3.2.3 stable

**OS/device including version:**
Windows 10 GLES 3

**Issue description:**
Button node does not have set_focus_neighbour function yet Control node does?

additionally you cannot set the focus_neighbour_* properties (or if you can they seemingly have no effect)

**Steps to reproduce:**
in my use case I had a gridcontainer with more than 1 column and more than 1 row. I was trying to get the right keyboard to cycle to the next row if you are at the end. 

minimal project included

**Comment by groud** [comment]
Sorry, having a look to you project you likely did not understand how set_focus_neighbour works. Button inherits Control so the function is indeed available for buttons too.

You are using the `set_focus_neighbour` function like that: `child.set_focus_neighbour(focus_neighbour_right, NodePath(get_child(child.get_index()+1).get_path()))`, while you are supposed to use something like `child.set_focus_neighbour(MARGIN_RIGHT, get_child(child.get_index()+1).get_path()))`. Or simply set the `focus_neighbour_right` on the node's property.

In any case, this is likely not a bug with the engine but with your project, so please ask for help on the other community channels first.

**Comment by Salvakiya** [comment]
Interesting... Although I should mention it still does not work by setting focus_neighbour_* properties. or even by using MARGIN_LEFT or MARGIN_RIGHT

**Comment by groud** [comment]
I mean, if you can provide a sample project, with the focus_neighbour_* set on only one node, where it does not work, instead of a complex script iterating over a node's children, I'm ok to reopen. But for now it looks more like a problem in your script than in the engine.

**Comment by Salvakiya** [comment]
You dont have to look further than Button node does not have `set_focus_neighbor` function I would think?

**Comment by groud** [comment]
>  Button node does not have set_focus_neighbor function

It does have a set_focus_neighbor function, it inherits from Control. Thus it has this function.
