### ISSUE TITLE
[Android] eof_reached() causes infinite while-loop

### ISSUE THREAD

**Issue by SilvanaP** [godotengine/godot#42959]
**Godot version:**
3.1

**OS/device including version:**
Android

**Issue description:**
I am trying to open an existing file and count the lines in there. Works like a charm on Windows, but crashes on Android because the code is stuck in the while-loop. It's a *.txt logfile that I try to open. I already did set the exporting-options so that my *.txt files should make it into the apk, but its still stuck in the loop. Also restarting Godot did not help.

Here's my code:
```
#savefile is a file I open in another method...
func calculateTotalLinecount():
	var totalcount = 0
	while !savefile.eof_reached():
		# iterate through all lines until the end of file is reached
		var line = savefile.get_line()
		totalcount += 1
	linenumber = totalcount
```

Here what the console says:
![godotcrash](https://user-images.githubusercontent.com/15194903/96716769-c294df00-13a5-11eb-999f-63b252199bd7.PNG)

**Comment by Calinou** [comment]
@SilvanaP Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by SilvanaP** [comment]
Argh...I found the problem. I had no read/write Permissions  set >_< 
Improvement suggestion: making more descriptive errors for such cases?
