### ISSUE TITLE
`Directory.copy` returns error code 12 on Android

### ISSUE THREAD

**Issue by ndarilek** [godotengine/godot#42964]
**Godot version:** 3.2.3

**OS/device including version:** Android 7.0

**Issue description:**

I have this code:

```
	elif OS.get_name() == "Android":
		var dest = OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS) + "/onslaught.html"
		var dir = Directory.new()
		print_debug("findme")
		var result = dir.copy("res://README.html", dest)
		print(result)
		uri = "file://" + dest
		print_debug(uri)
```

Trying to copy a file from my PCK so it can be viewed in the local browser. But I get this in my logs:

10-21 10:50:26.939 25437 25458 E godot   : **ERROR**: Failed to open /storage/emulated/0/Download/onslaught.html
10-21 10:50:26.939 25437 25458 E godot   :    At: core/os/dir_access.cpp:307:copy() - Failed to open /storage/emulated/0/Download/onslaught.html
10-21 10:50:26.939 25437 25458 I godot   : 12

Looking up that error code gives me:

ERR_FILE_CANT_OPEN = 12 --- File: Can't open error.

The docs for `Directory.copy` seem to indicate that the file doesn't need to exist, so I'm not sure of the nature of this error. I've also confirmed from decompiling the manifest in the app that `WRITE_EXTERNAL_STORAGE` is set. The directory also exists, and for good measure I created an empty file at the location. I'm wondering if this error code means something different on Android?

**Steps to reproduce:**

1. Create a project with a script including the above code in its `_ready` method, and run it as a global.
2. Export it for Android.
3. Launch.

**Minimal reproduction project:**

I can provide one if this can't be duplicated, but for me a "minimal" project needs to pull in the accessibility plugin, so they end up being pretty large.

**Comment by bruvzg** [comment]
> manifest in the app that WRITE_EXTERNAL_STORAGE is set

You have to call `OS.request_permissions()` to actually get external storage access, and other stuff in the manifest.

**Comment by ndarilek** [comment]
So sorry, did not realize.

That works. Now I get another error, but that looks to be in Android itself and I can debug that.

Thanks, and sorry for the noise.
