### ISSUE TITLE
Godot Mono iOS export can't be compiled with Xcode 12 or later: "Cannot load assembly (refonly): 'Xamarin.iOS'"

### ISSUE THREAD

**Issue by fadexmusic** [godotengine/godot#42960]
**Godot version:**
v3.2.3.stable.mono.official

**OS/device including version:**
MacOS Catalina 10.15.7, Macbook Pro 15" 2017,
.NET core SDK 2.1.809,  Xamarin iOS 14.0.0.0

**Issue description:**
When I try to export for iOS, I get these errors:
```
Cannot load assembly (refonly): 'Xamarin.iOS'.
Cannot load one of the dependencies for the assembly: 'System.Net.Http'.
Cannot load one of the dependencies for the assembly: 'netstandard'.
Cannot load one of the dependencies for the assembly: 'GodotSharp'.
```
The Xcode project gets created, but I cannot build it to test on either the simulators or my iOS device.
I didn't have this problem yesterday, before updating to Xcode 12.

**Steps to reproduce:**
1. Create a mono project
2. Export to iOS

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/5416352/test.zip)

**Comment by fadexmusic** [comment]
Any ideas? @neikeq

**Comment by neikeq** [comment]
Unfortunately I lost access to the mac I was borrowing so I'm not being able to work on the iOS port right now. I plan to buy one of the new arm macbooks once they come out and get back to this.

**Comment by mars3142** [comment]
@neikeq You've set the milestone to 4.0. Is there a visible roadmap for v4.0? Because right now no deployment of Godot mono is possible with the latest stable build in Xcode 12.

**Comment by neikeq** [comment]
Adding it to the 4.0 milestone doesn't mean it won't be fixed in a future 3.2.x release. I will talk about my roadmap in the next devlog. I've bough one of the new arm macbooks so I will be able to get back to iOS issues in December.

**Comment by sonenko** [comment]
reproduced same issue

**Comment by ksvslk** [comment]
Have the same issue. Is this planned for 3.2.4 ?

**Comment by Calinou** [comment]
@ksvslk This isn't on the roadmap for 3.2.4, so there's no guarantee it will be fixed by the time 3.2.4 is released.

**Comment by ksvslk** [comment]
> > Have the same issue. Is this planned for 3.2.4 or it is impossible to build for iOS for now?
> 
> This issue isn't on the roadmap for 3.2.4, so there's no guarantee it will be fixed by the time 3.2.4 is released.

Ok. Any workaround, using earlier Xcode?

**Comment by Calinou** [comment]
> Ok. Any workaround, using earlier Xcode?

Probably.

**Comment by ksvslk** [comment]
> > Ok. Any workaround, using earlier Xcode?
> 
> Yes, that can probably work.

Tried with Xcode 11.7 - same thing. Do I need to create new Xcode export templates?
