### ISSUE TITLE
Scons incorrectly asserts python version is 2.7 while it is 3.6

### ISSUE THREAD

**Issue by Dantali0n** [godotengine/godot#42963]
**Godot version:**
918f03529f42b3fdebbc6f236012e61288db0c3a

**OS/device including version:**
Ubuntu 18.04
AMD Radeon RX 470 Graphics (POLARIS10, DRM 3.40.0, 5.4.0-48-generic, LLVM 10.0.0)

**Issue description:**
Scons incorrectly asserts python version is 2.7 while it is 3.6.

```shell
$ scons platform=linuxbsd use_lto=yes
scons: Reading SConscript files ...
Python 3.5 or greater required, but you have Python 2.7.17
$ python --version
Python 3.6.9
$ which python
/home/xxx/usr/bin/python
$ echo $PATH
/home/xxx/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ ls -lah /usr/bin/ | grep "python "
lrwxrwxrwx  1 root   root          9 apr 16  2018 python -> python2.7
```

**Steps to reproduce:**
Have a path to python > 3.5 in `$PATH` **first** but have /usr/bin/python still point to python 2.7

**Minimal reproduction project:**
 
I really think this is not applicable in the current context as it involves the compiling from source.

**Comment by Calinou** [comment]
We recommend installing SCons via pip3 rather than your ditribution's package manager:

```
python3 -m pip install --user scons
```

Then make sure `$HOME/.local/bin` is in your `$PATH`.

**Comment by Dantali0n** [comment]
> To benefit from the latest Python 3-enabled SCons version, we recommend installing SCons via pip3 rather than your ditribution's package manager:
> 
> ```
> python3 -m pip install --user scons
> ```
> 
> Then make sure `$HOME/.local/bin` is in your `$PATH`.

Seeing how Scons is a relatively small and lightweight package with little to no dependencies I consider this a very reasonable solution. Currently compiling godot and it seems to be going fine now. Thanks for the quick replies.
