### ISSUE TITLE
Unexpected focus neighbor behavior with buttons in a GridContainer when the vseparation and hseparation are set to 0

### ISSUE THREAD

**Issue by uheartbeast** [godotengine/godot#42965]
**Godot version:**
Godot 3.2.3.stable

**OS/device including version:**
Windows 10

**Issue description:**
When I attempt to navigate the buttons in a GridContainer with the vseparation and hseparation set to 0, I get unexpected behavior. For example, pressing the left arrow key when focused on a button in the right column won't focus on the button to the left, it will focus on the button up and to the left.

When I set the vseparation and hseparation of the GridContainer to at least 1, I get the expected behavior.

**Steps to reproduce:**
Run the project and try to navigate the buttons in the grid container using the arrow keys.

**Minimal reproduction project:**
[ButtonGrid.zip](https://github.com/godotengine/godot/files/5417341/ButtonGrid.zip)

**Comment by Calinou** [comment]
Does it work if you specify the Focus Prev and Focus Next neighbors explicitly?

**Comment by uheartbeast** [comment]
Yes, you can manually set the focus neighbors on each button as a workaround. However, it becomes much less practical as a workaround if you are adding buttons to the GridContainer dynamically.

**Comment by swimmer248** [comment]
This is still very much a thing, and is annoying if you want to stylize something.

**Comment by tetrapod00** [comment]
Reproducible in 4.3. MRP: [mrp-gridcontainer-focus.zip](https://github.com/user-attachments/files/16603305/mrp-gridcontainer-focus.zip)

I also dug in a little more, and it's a general problem with finding neighbor controls, not just with GridContainer. It occurs whenever Controls are laid out in a grid pattern, flush with no separation between. I tested with a GridContainer, with an HBoxContainer containing VBoxContainers, and with controls laid out manually. In all cases, as long as there is no separation, the wrong focus behavior occurs.

![Godot_v4 3-rc1_mono_win64_QZI3Io5m09](https://github.com/user-attachments/assets/2066a978-d8ce-42b7-87e8-97ee681cee8e)

In this video, I am inputting "ui_right" by pressing the right arrow key.

https://github.com/user-attachments/assets/0d1dd973-f764-4592-8826-a20154a98412

Maybe an edge case with the neighbor selection algorithm in control.cpp? https://github.com/godotengine/godot/blob/06fbc8395b3c0ec6fa38588caea2ee94837f7b97/scene/gui/control.cpp#L2263 https://github.com/godotengine/godot/blob/06fbc8395b3c0ec6fa38588caea2ee94837f7b97/scene/gui/control.cpp#L2344?
