### ISSUE TITLE
Replacing root node loses Editable Children data

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4297]
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
Replacing the tree root node loses **Editable Children** data.

**Steps to reproduce:**
![replace_node](https://cloud.githubusercontent.com/assets/8281454/14466248/efbdb2b0-0110-11e6-9de4-52e977d0bb4f.gif)

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
I can confirm this issue. It only happens when replacing the tree root node, which is the one that stores this information.
