### ISSUE TITLE
Default color for ruler text with light theme to dark

### ISSUE THREAD

**Issue by Hojoe42** [godotengine/godot#42988]
**Godot version:**
v3.2.3.stable

**OS/device including version:**
Windows 10

**Issue description:**
The text for the ruler position with light theme is nearly invisible. It needs an other default color.

**Steps to reproduce:**
Switch to light theme, open a new empty scene, move the ruler and  look at the ruler text. 
![Zwischenablage01](https://user-images.githubusercontent.com/9704038/96834123-bc544080-1441-11eb-936a-bece51f67d95.png)

related to #33523?

**Comment by Ev1lbl0w** [comment]
Shoud be fixed by #36530

**Comment by Hojoe42** [comment]
Oh, thank you

**Comment by erictuvesson** [comment]
It wont be fixed in there unless they do other changes there too, which I don't expect.

#36530 is about the rules while this is about the `zoom_reset` Button, from what I understand.

**Comment by Ev1lbl0w** [comment]
@erictuvesson you're right, but since @Hojoe42 also opened a issue specific to the zoom problem (#42986), I assumed this screenshot was just an error.

**Comment by Hojoe42** [comment]
For the Zoom I have opened #42986. I marked the ruler text:
![Zwischenablage01](https://user-images.githubusercontent.com/9704038/96845900-80c17280-1451-11eb-8085-424e3b071c86.png)
