### ISSUE TITLE
Members panel style is broken in new visual scripts

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#42984]
**Godot version:**
3.2.4beta1

**OS/device including version:**
Windows 10

**Issue description:**
When you create a new visual script the Members panel is unstyled, black fonts and no icons so you can't really tell what you are supposed to do to create new variables. Once you click the invisible buttons it shows up properly.

**Steps to reproduce:**
Create a node, create and add a new visual script

**Minimal reproduction project:**
Link to video demonstrating the issue: https://www.youtube.com/watch?v=RK72M61oUDA

**Comment by Chaosus** [comment]
Sometimes it happens on master too.

**Comment by akien-mga** [comment]
I've seen that in master today indeed. It used to be fine, so I guess it's a regression?

**Comment by Chaosus** [comment]
Well, yeah I think its regression from somewhere between 3.2 and 3.2.3

**Comment by coppolaemilio** [comment]
Still happening in 3.2.4.beta3
