### ISSUE TITLE
Zoom Level with light theme nearly invisible

### ISSUE THREAD

**Issue by Hojoe42** [godotengine/godot#42986]
Windows 10, Godot Engine v3.2.3.stable

Switch to light theme, open a new empty scene and look at the zoom level. The zoom level is only a little bit darker as the background. 
![Zwischenablage01](https://user-images.githubusercontent.com/9704038/96832546-3800be00-143f-11eb-9ef1-650b90ee4de6.png)

**Comment by Calinou** [comment]
Reopening, as this is fixed in `master` but not `3.x` since the cherry-pick of https://github.com/godotengine/godot/pull/42995 was undone.

**Comment by akien-mga** [comment]
Fixed for 3.4 too by #49274.
