### ISSUE TITLE
SurfaceTool needs add_quad method

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4298]
It is simple enough to implement, but I have no time so
To improve speed of generation algorithms (and reduce script sizes), the quad
method should be added to SurfaceTool.
GDScript implementation:

```gdscript
class mysf extends SurfaceTool:
    func add_tri(uvs, pts):
            if uvs.size() != pts.size():
                    return
            for k in range(uvs.size()):
                    add_uv(uvs[k])
                    add_vertex(pts[k])
    func add_quad(pts, uvs):
            var pts1 = [pts[0], pts[1], pts[3]]
            var pts2 = [pts[1], pts[2], pts[3]]
            var uvs1 = [uvs[0], uvs[1], uvs[3]]
            var uvs2 = [uvs[1], uvs[2], uvs[3]]
            add_tri(uvs1, pts1)
            add_tri(uvs2, pts2)
```

**Comment by bojidar-bg** [comment]
Copy from IRC:

\<**bojidar_bg**\> surfacetool has alot of functions, like add_color, add_uv2, add_bones, etc. which relate to the next vertex added with add_vertex
\<**bojidar_bg**\> ...which add_tri and add_quad (as proposed) don't allow in any way to be changed
\<**bojidar_bg**\> so, I wonder how should this be actually implemented... by adding a lot of optional parameters for uv, uv2, etc. or some other way

**Comment by slapin** [comment]
Adding arrays of parameters should be fine.

**Comment by slapin** [comment]
Well, it seems we have hard times discussing this :)

I've got another idea. We have a Geometry class, which is singleton and contains a set of useful,
but undocumented routines. I think we can use this one to generate our needed arrays,
Then we could provide our add_tri function with such arrays.
So we add function make_quad(p1, p2, p3, p4, uv1, uv2, uv3, uv4) to Geometry, then use normal SurfaceTool
methods to cope with it?
@reduz are you here already? Would you add some bit? The idea is to make basic geometric shapes generation faster. I basically need cubes, which could be made out of quads.
I think we can separate forms and methods, so we generate all shapes out of triangles and the we could generate collisions and forms themselves (with uv-maps and all), so my algorithm runs
in seconds instead of minutes?

**Comment by bojidar-bg** [comment]
@slapin ~ Well, wouldn't it be better if we do (sorry if I have mistaken any of the types):
````
add_poly(Vector3Array points, ColorArray colors = [], Vector2Array uvs = [], Vector2Array uv2s = [], Vector3Array normals = [], Vector3Array tangents = [])
````

For points.size < 3 it would do nothing, for size = 3 it would make a triangle, and for size > 3 it would do a triangular fan based on points[0].

**Comment by slapin** [comment]
Basically this looks good., except for points and uvs should go first and not be optional.
or uvs can be optional, but go just after points.

**Comment by bojidar-bg** [comment]
Ok, after a bit more discussion on IRC, we decided that:

1. The method will be just one, called `add_triangle_fan`.
2. The method will do nothing to ensure the data is a planar, convex polygon. (as of now, feel free to open another issue about it when it is implemented, or comment on this one)

**Comment by slapin** [comment]
The answer to question on IRC:
15:51 < bojidar_bg> slapin: are you still there?
15:51 < bojidar_bg> how does SurfaceTool handle multi-material meshes?

You create separate surface for each material, then commit to the same mesh.

**Comment by slapin** [comment]
Good work, thanks a lot to you guys!
