### ISSUE TITLE
Godot doesn't show paths for scripts with identical names anymore

### ISSUE THREAD

**Issue by ktostam0** [godotengine/godot#42996]
**Godot version:**
Godot 3.2.4 beta 1

**OS/device including version:**
Linux X11 x64

**Issue description:**
In Godot 3.2.3 when two scripts with identical file names were opened, editor showed their path making user able to recognize them. This behaviour is no longer present in 3.2.4 beta 1. I tried to use the setting making paths visible for all scripts, however it resulted in some very long names making the dock with scripts needlessly large.

**Steps to reproduce:**
Create two scripts with exactly same file names and open them in the editor.

**Minimal reproduction project:**
See above.

Note: this is my first issue and I'm not really sure if this is the right way/place to do it.

**Comment by akien-mga** [comment]
The only change to the script editor plugin since 3.2.3-stable seems to be #40461, CC @pouleyKetchoupp.
Might have been lost in rebase as this disambiguation was a new feature in 3.2.3-stable.

**Comment by ktostam0** [comment]
Sorry, I just realised that I also had some older Godot version present on my computer and I've accidentally run it. I'm really sorry for the misinformation. I will double-check it next time.
