### ISSUE TITLE
FXAA mess brightness when using World Environment Tone mapping

### ISSUE THREAD

**Issue by vitorbalbio** [godotengine/godot#43005]
**Godot version:**
3.2.4 Beta 1

**OS/device including version:**
Windows 10

**Issue description:**
FXAA mess your scene brightness when using World Environment Tonemap other than default settings. 
![dVO4ake86T](https://user-images.githubusercontent.com/6172013/96881113-50c79e80-1454-11eb-9233-8d4658ab208c.gif)

**Steps to reproduce:**
See above

**Minimal reproduction project:**
[TesteFXAA.zip](https://github.com/godotengine/godot/files/5423220/TesteFXAA.zip)

**Comment by clayjohn** [comment]
Are you using GLES2 or GLES3?

**Comment by volzhs** [comment]
looks GLES3 according to driver name on top right corner of gif.

**Comment by vitorbalbio** [comment]
> Are you using GLES2 or GLES3?

GLES3

**Comment by clayjohn** [comment]
Same bug is in master and 3.2. I think I know what the issue is.
