### ISSUE TITLE
Distance fade Bug. material fade by proximity and not by distance

### ISSUE THREAD

**Issue by CHIESOFTWARE** [godotengine/godot#43003]
**Godot version:**
3.2.3

**OS/device including version:**
Linux Ubuntu Studio 20.04, backend GLES3

**Issue description:**
I check the distance fade option in material and the object get transparent if camera is close 

**Steps to reproduce:**
Just add an spatial material to a mesh instance and check the option of distance fade

**Comment by Calinou** [comment]
> I check the distance fade option in material and the object get transparent if camera is close

This is intended. The fade will direction invert if the minimum distance is greater than the maximum distance.

**Comment by CHIESOFTWARE** [comment]
oh , sorry .. thanks for a nice answer
