### ISSUE TITLE
Exporting Android APK doesn't work using a custom Godot build without tools and 3d

### ISSUE THREAD

**Issue by eddex** [godotengine/godot#43006]
**Godot version:** Custom build @ `tags/3.2.3-stable`

**OS/device including version:** Windows 10

**Issue description:**

I'm trying to build an Android app that only uses `2D` and `Control` nodes. Therefore I want to use a custom build of Godot to make the APK size smaller. I followed the instructions on the [introduction to the build system](https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html) page and was able to compile Godot without any errors.

When I build Godot with `tools` and `3d` enabled I can successfully export my Android app:
Build Godot: `scons p=windows target=debug -j 8`
Export app: `godot.windows.tools.64.exe --verbose --path .\project.godot --export "Android" app.apk`

This opens the Godot Engine UI and runs the export task as if I would do it with the UI myself. The app is built as expected.

When I build Godot without `tools` and `3d`, the export for Android fails:
Build Godot: `scons p=windows target=debug tools=no disable_3d=yes -j 8`
Export app: `godot.windows.debug.64.exe --verbose --path .\project.godot --export "Android" app.apk`

Instead of building the APK, the export command just runs the Godot project on my PC.

**Steps to reproduce:**
- Build Godot without `tools` and `3d`
- Try to export an Android project

**Remarks:**
As I am new to building Godot and optimizing APK sizes, it is possible that what I do is not correct because I don't understand all the concepts yet. So here are a few questions I have:
- Is it even possible to build an Android app using a build of Godot without the `tools` build option?
- If not, do I always need to include the `3d` stuff in my Android app, even if I don't need it?
- Or does Godot automatically exclude nodes that are not used by the game from the APK when I export it?
- Does creating a custom build of Godot even affect the APK size of my Android app?

**Comment by Calinou** [comment]
You don't use the compiled export template to export a project. You use the editor and specify the newly compiled *Android* export template (not Windows!).

**Comment by eddex** [comment]
Hi @Calinou 

First of all, thanks a lot! I have never received such a quick and detailed answer, this really made my day!

So if I understand this correctly (and for anyone else who might stumble upon this issue), to optimize my APK size, I should do the following:
- Create a custom Godot build, using `tools` and `3d` but disabling everything else that I don't need in the `custom.py` options as described on [optimizing for size](https://docs.godotengine.org/en/stable/development/compiling/optimizing_for_size.html). This will decrease the size of the APK.
- Then build and install the Android export templates as described on [compiling for android](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html) (build for `armv7` and `arm64v8` with `target=release`).
- To further decrease the size of the APK, export 2 APKs, one for ARMv7 and one for ARMv8 as described on [compiling for android](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html)

**Comment by Calinou** [comment]
> So if I understand this correctly (and for anyone else who might stumble upon this issue), to optimize my APK size, I should do the following:

    Create a custom Godot build, using tools and 3d but disabling everything else that I don't need in the custom.py options as described on optimizing for size. This will decrease the size of the APK.
    Then build and install the Android export templates as described on compiling for android (build for armv7 and arm64v8 with target=release).
    To further decrease the size of the APK, export 2 APKs, one for ARMv7 and one for ARMv8 as described on exporting for android


As I said, you don't need to recompile the editor. Only recompile the Android export template, export one APK per architecture and upload them to Google Play using its [multiple APK support](https://developer.android.com/google/play/publishing/multiple-apks).

Also, Godot 3.2.4 will support Android App Bundles, making it possible to export a single `.aab` file that contains all architectures. Google Play will then take this file and split it into individual APKs for each architecture, so you don't have to do this yourself.

**Comment by eddex** [comment]
In your first answer you said this:

> > Does creating a custom build of Godot even affect the APK size of my Android app?

> Yes, it helps significantly as long as your game's assets aren't too large. As your game's assets become larger, they'll take a larger portion of the APK size, making binary size optimizations less interesting (but still useful nonetheless).

And now you say it's not needed?

> As I said, you don't need to recompile the editor since you're only _removing_ functionality in the export template, not adding new functionality. (Also, the editor can't function without 3D support anyway.)

Also [compiling for android](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html) doesn't really describe how to _remove_ any functionality from the export template. Sorry but I'm really confused right now..


> Also, Godot 3.2.4 will support Android App Bundles, making it possible to export a single `.aab` file that contains all architectures. Google Play will then take this file and split it into individual APKs for each architecture, so you don't have to do this yourself.

Great to hear this :)

**Comment by eddex** [comment]
Ah wait, I think I got it.. I use the command `scons platform=android target=release android_arch=armv7` to build Godot for _Android_. This will make use of the `custom.py` scons options and therefore make the custom export templates smaller. Is this right?

**Comment by Calinou** [comment]
> Ah wait, I think I got it.. I use the command `scons platform=android target=release android_arch=armv7` to build Godot for _Android_. This will make use of the `custom.py` scons options and therefore make the custom export templates smaller. Is this right?

Yes.

**Comment by eddex** [comment]
Great, thanks a lot for your help!

**Comment by eddex** [comment]
What I noticed is that, while the export templates are significantly reduced in size when building them from source, the exported APKs are exactly the same size as with the default export templates. So to me it seems like it's not really necessary to build a custom export template.

**Comment by akien-mga** [comment]
If it's the exact same size, most likely it's the exact same template (i.e. the original one).

Did you do this?

> Once you've compiled an Android export template, specify it as a custom export template in your Android export preset. You can do so in the editor's Export dialog.

Here's where you should set the path to your release and/or debug template, depending on what you built and want to export:
![Screenshot_20201022_181425](https://user-images.githubusercontent.com/4701338/96900470-6eb3f400-1492-11eb-9043-7399b7073842.png)

**Comment by eddex** [comment]
@akien-mga yes, I did this. Version 0.0.3 was made with the default export template. Version 0.0.4 with the custom build template.
![image](https://user-images.githubusercontent.com/5302085/96901025-087ba100-1493-11eb-9e2d-35f01b5074f1.png)

The default `android_debug.apk` was ~60MB and the `android_release.apk` was ~50mb for version 0.0.3.
Now my newly built export templates are ~19MB and ~13MB. But the built app is exactly the same size as you can see in the image.
