### ISSUE TITLE
Porting for Android 4.2-2.2 (3.2.3.stable)

### ISSUE THREAD

**Issue by Summersay415** [godotengine/godot#43001]
**Godot version:**
3.2.3.stable

**OS/device including version:**
Android 4.2, GLES1/2

**Issue description:**
I am trying port Godot3.2.3.stable to Android 4.2 and earlier, but then I run project even with GLES2 I get the error(libGLESv3 not found). I try remove /drivers/gles3 folder, changing ndk_platform to 17 and fix some errors, but these errors I can't fix(`scene/libscene.android.opt.debug.armv7.neon.a(voxel_light_baker.android.opt.debug.armv7.neon.o):voxel_light_baker.cpp:function` VoxelLightBaker::_lightmap_bake_point(unsigned int, VoxelLightBaker::LightMap*): error: undefined reference to 'log2f'
servers/libservers.android.opt.debug.armv7.neon.a(visual_server_scene.android.opt.debug.armv7.neon.o):visual_server_scene.cpp:function VisualServerScene::instance_set_blend_shape_weight(RID, int, float): error: undefined reference to 'log2f'
servers/libservers.android.opt.debug.armv7.neon.a(visual_server_scene.android.opt.debug.armv7.neon.o):visual_server_scene.cpp:function VisualServerScene::update_dirty_instances(): error: undefined reference to 'log2f'`)

**Steps to reproduce:**
Download [this](https://drive.google.com/file/d/1qGALbDbgEETDHEFwmxx4jKkAk4eWeQjb/view?usp=sharing) source code and try to compile for Android.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
We don't support building Godot 3.2.3 for these old Android releases, and all the code assumes the availability of recent APIs.

If you really want to make games for Android 2.2, you should use an earlier Godot version, such as Godot 2.0: https://github.com/godotengine/godot/releases/tag/2.0.4.1-stable
It supports min API level 10, which is Android 2.3.3: https://github.com/godotengine/godot/blob/2.0/platform/android/AndroidManifest.xml.template#L203
