### ISSUE TITLE
KinematicBody2D hugs corners when using move_and_slide()

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#43012]
**Godot version:** 3.2.3.stable

**OS/device including version:** Ubuntu 20.04

**Issue description:**
When a `KinematicBody2D` using `move_and_slide()` glances the corner of a `StaticBody2D`, it hugs the corner and slides along the opposite surface:
![KinematicBody-Hugging-Corner2](https://user-images.githubusercontent.com/9253928/96910357-4b3f7800-1497-11eb-864a-caf76dd84844.gif)
Related to #25967, but that was with a one-way collision surface that is fixed with #42574.

**Steps to reproduce:**
Create `KinematicBody2D` and aim it so it just glances the corner of a `StaticBody2D`.

**Minimal reproduction project:**
[KinemacticHuggingCorner.zip](https://github.com/godotengine/godot/files/5424650/KinemacticHuggingCorner.zip)

**Comment by pouleyKetchoupp** [comment]
Fixed by #42574, closing.
