### ISSUE TITLE
opcode #38 in 3.2.4.beta1 (regression from 3.2.3.stable)

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#43023]
**Godot version:**
3.2.4.beta1

**OS/device including version:**
Windows 10

**Issue description:**
`opcode 38 (report please)`

```
<C++ Source> modules/gdscript
E 0:00:00.998   call: Condition ' !base_type ' is true. Breaking..:
  <C++ Source>  modules/gdscript/gdscript_function.cpp:837 @ call()
```

**Steps to reproduce:**
Could not reproduce in a new project.

**Minimal reproduction project:**
A huge project of spaghetti code.
Tried to reduce it down to a minimal project, but everything breaks when I try, so this is all I can provide, sorry.
[opcode 38 Bug - 1.zip](https://github.com/godotengine/godot/files/5426556/opcode.38.Bug.-.1.zip)

**Comment by Rubonnek** [comment]
I'm unable to reproduce in Linux. Perhaps this is specific to Windows.

**Comment by Rubonnek** [comment]
Welp, I was able to reproduce. For some reason executing the project through the Editor does not generate the warning. Interesting.

```
SCRIPT ERROR: PlayerInventoryNamesMenu.create_inventory_object_counts_menu: Internal Script Error! - opcode #38 (report please).
   At: res://Scenes/PlayerInventoryNamesMenu/PlayerInventoryNamesMenu.gd:24.
```

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/43042n which has more information about the issue at hand.

**Comment by Error7Studios** [comment]
Was able to reproduce by following the steps provided in #43042.
Closing, since I've added a screenshot to that issue that adds more information.
