### ISSUE TITLE
Text_Changed not triggered when changing text through ".Text"

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#43024]
3.2.3 Stable Mono version

Create a TextEdit and a button, connect the button press to add text to a TextEdit node by using the TextEdit.Text code.
Finally, connect the "_text_changed" to code and create a break point in the code.
Run the program and push the button.  The text will change to "Hello There!", BUT the _text_changed code will not be triggered.  However, if you actually type in the TextEdit the _text_changed function will fire.

Here is an example:
[TextChange.zip](https://github.com/godotengine/godot/files/5426759/TextChange.zip)

**Comment by Rubonnek** [comment]
Could you reupload the example project? It seems to be empty.

**Comment by ondesic** [comment]
There we go

**Comment by Zylann** [comment]
I think "changed" signals usually don't fire when you change the value of a control from code. We should check the consistency of such behavior before we can label this as a bug.

**Comment by ondesic** [comment]
My project analyzes the text in a TextEdit any time it changes.  The user can manually enter text or select text from a database.  The signal is named "text_changed", not "on_typing".  In this particular case I would expect the signal to trigger when the text changes regardless of how it changes.

**Comment by DaividFrank** [comment]
It's pretty understandable why godot won't emit the signal when you replace a node's property, and IMO adding a hook on that property would be a proper solution.
I looked at TextEdit's functions and it seems it doesn't have a function to replace all current text, but for now you can use select_all and then insert_text_at_cursor to replace all current text, hope this helps =]

**Comment by Paulb23** [comment]
Related #19372

**Comment by Paulb23** [comment]
Can be considered fixed by #50372 which added a `text_set` signal.
