### ISSUE TITLE
GDScript: 'match' does not work correctly with enums and constants

### ISSUE THREAD

**Issue by Paavs-Git** [godotengine/godot#43035]
**Godot version:**
4.0 32be9299ba177781d22bffa8e7e848fcca33b860

**Issue description:**
'match' behaves incorrectly when the cases are enums or constants, it also oddly changes behaviour if used after a 'match' with literal values.

This bug doesn't occur on 3.2.3.stable (it works correctly).

**Steps to reproduce:**
```
enum {ENUM_0, ENUM_1, ENUM_2}
const CONST_0: int = 0
const CONST_1: int = 1
const C_STRING_a: String = "a"
const C_STRING_b: String = "b"

func _ready() -> void:
	var int_var: int = 1
	var string_var: String = "b"
	
	match string_var:
		C_STRING_a:
			print("C_STRING_a")
		C_STRING_b:
			print("C_STRING_b")
		_:
			print("C_STRING default")
	
	match int_var:
		ENUM_0:
			print("ENUM_0")
		ENUM_1:
			print("ENUM_1")
		_:
			print("Enum default")
	
	match int_var:
		CONST_0:
			print("CONST_0")
		CONST_1:
			print("CONST_1")
		_:
			print("CONST default")
	
	# Works  correctly with literals
	match int_var:
		0:
			print("literal 0")
		1:
			print("literal 1")
		_:
			print("literal default")
	
	match string_var:
		"a":
			print("literal a")
		"b":
			print("literal b")
		_:
			print("literal default")
	
	# Now repeat the initial match cases, behaviour has changed, still incorrect
	match string_var:
		C_STRING_a:
			print("C_STRING_a")
		C_STRING_b:
			print("C_STRING_b")
		_:
			print("C_STRING default")
	
	match int_var:
		ENUM_0:
			print("ENUM_0")
		ENUM_1:
			print("ENUM_1")
		_:
			print("Enum default")
	
	match int_var:
		CONST_0:
			print("CONST_0")
		CONST_1:
			print("CONST_1")
		_:
			print("CONST default")
```

This outputs:
```
C_STRING default  # Wrong
Enum default        # Wrong
CONST default      # Wrong
literal 1
literal b
C_STRING_a   # Wrong - behaviour changed
ENUM_0        # Wrong - behaviour changed
CONST_0       # Wrong - behaviour changed
```

**Comment by bloodsign** [comment]
Just to add, 
I can confirm that there are times where it doesn't work on 3.2.3.stable build. 
I would write the code and run it a few times where it will work, but then, it would stop matching suddenly 
Despite me printing the values in a 1 to 1 comparison and confirming that the values are the same. I would even cast both values 
to int(val) before matching to make sure. 
The match returns false, which baffles me. In my case, the values I'm passing was retrieve from a config file and matched to a Global Enum list of Types. The real odd thing is, the very same lines of code would work on other parts of my code, while on others it just doesn't seem to like the match statement... I would have to use an if statement for it to work.
