### ISSUE TITLE
Broken class image

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#4303]
Broken class image
Image generated texture is completely black, here's an example of my script ...

```
extends Quad
export (int) var Xpix = 128
export (int) var Ypix = 128

func _ready():
	_update_texture()
	pass


func _update_texture():
	
	var IMEGE = Image( Xpix, Ypix, false, 4)
	print(str(IMEGE.get_height())+"_size_"+str(IMEGE.get_width()))
	
	for i in range(Xpix):
		for j in range(Ypix):
			IMEGE.put_pixel( i, j, Color(i*j*64*128),0)
	IMEGE.save_png("res://SAVED_DATA/test_PNG_pix.png")
	
	
	var IMEGE_TEXTURE = ImageTexture.new()
	
	IMEGE_TEXTURE.set_data(IMEGE)
#	IMEGE_TEXTURE.create_from_image(IMEGE,7 )
	
	
	var MAT = FixedMaterial.new()
	MAT.set_name("MAT")
	
	MAT.set_texture(0,IMEGE_TEXTURE)
	
#	MAT.set_fixed_flag(0,true)#FLAG_USE_ALPHA = 0
	
	set_material_override(MAT)
```

**Comment by reduz** [comment]
what is this supposed to be?

`IMEGE.put_pixel( i, j, Color(i*j*64*128),0)`

**Comment by OlexiyKravchuk** [comment]
is an attempt to create each time a different color, passing as an argument to Int, I had to make such a perversion because the function Color 8 () did not work, but this is corrected, probably it is worth to indicate clearly the type INT, and use the sum channel values ​​multiplied by the degree of the first bit in the channel in order to obtain the desired effect like this ...
IMEGE.put_pixel (i, j, Color (int (i * 16777216 + j * 64 * 65536 + 256 + 128), 0) I probably should close the issue because obviously the problem lies in the fact that I was not properly calculated the formula but still I wonder why everything was black and had no difference in pixels?

**Comment by OlexiyKravchuk** [comment]
Oh, I found where there was a mistake, it should have been so ...
# IMEGE_TEXTURE.set_data (IMEGE)
IMEGE_TEXTURE.create_from_image (IMEGE, 7)

I'm sorry, I close issue
