### ISSUE TITLE
[3.2.4 beta1]Turn off Use Batching in Editor make Editor looks strange

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#43039]
**Godot version:**

3.2.4 beta1

**OS/device including version:**

2013 late MacBookPro 13' MacOS 10.14.6 intel GPU

**Issue description:**

![屏幕快照 2020-10-23 19 42 45](https://user-images.githubusercontent.com/64188282/97013380-9468f800-157b-11eb-876d-d70777bf5f51.png)

**Steps to reproduce:**
go to Project Settings, switch to Rendering -> Batching, turn off use batching in Editor

**Minimal reproduction project:**

**Comment by EIREXE** [comment]
I'm looking at similar issues in game if I disable batching.

**Comment by EIREXE** [comment]
![imagen](https://user-images.githubusercontent.com/3101690/97013896-ebee7000-1549-11eb-811f-68f2f328b29c.png)

Example of the issue, using an Vega 56 on Linux with the free drivers.

**Comment by Calinou** [comment]
Note that this was already reported here: https://github.com/godotengine/godot/issues/42899#issuecomment-713963134

**Comment by akien-mga** [comment]
This was fixed by #42990 (will be in 3.2.4 beta 2). Until then you should not disable batching :P

**Comment by snougo** [comment]
> Note that this was already reported here: [#42899 (comment)](https://github.com/godotengine/godot/issues/42899#issuecomment-713963134)

ok, got it
