### ISSUE TITLE
Packed{Byte,Int{32,64},Float{32,64}}Array.resize() fills new elements with garbage

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#43033]
**Godot version:**
4.0.dev.calinou.32be9299b
3.2.3.stable.official

**OS/device including version:**
Linux

**Issue description:**
Run the script and most likely you will see something like:
```
26000000050000000900000000000006000000042600000006000000150000000100000000000006
00000000010000040100000526000000070000001600000000000000000000060100000001000005
170000003f0000000100000001000005010000052600000008000000260000000900000026000000
0a000000260000000b000000260000000c000000260000000d000000260000000e00000026000000
0f000000260000001000000026000000110000002600000012000000270000006400000069000000
6f00000053000000740000007200000065000000610000006d000000500000006c00000061000000
79000000650000007200000033000000
```

The array is filled with random data from memory.

New array elements are expected to be filled with zeros.

**Steps to reproduce:**
```
@tool
extends EditorScript

func _run():
    var buf = PackedByteArray()
    buf.resize(256)
    print(buf.hex_encode())
```

Also, I noticed that the offset depends on the size of the buffer.

**Minimal reproduction project:**
–

**Comment by Ev1lbl0w** [comment]
I believe this is "expected", in the sense that this is what happens with C/C++ code; initializing new memory arrays with "default" values is generally a waste of resources, since the programmer is likely to fill in their data afterward.

**Comment by dalexeev** [comment]
@Ev1lbl0w Godot and especially GDScript are high-level systems that are often used by newbies who don't know C/C++. We need to either document this or add an optional parameter to the `resize()` function. Also, this behavior is inconsistent with other types of arrays:

```gdscript
tool
extends EditorScript

func test(name, array, default):
    array.resize(1024)
    var result = true
    for i in array:
        if i != default:
            result = false
            break
    print(name, ": ", result)

func _run():
    test("Array", [], null)
    test("PoolByteArray", PoolByteArray(), 0)
    test("PoolColorArray", PoolColorArray(), Color())
    test("PoolIntArray", PoolIntArray(), 0)
    test("PoolRealArray", PoolRealArray(), 0.0)
    test("PoolStringArray", PoolStringArray(), "")
    test("PoolVector2Array", PoolVector2Array(), Vector2())
    test("PoolVector3Array", PoolVector3Array(), Vector3())
```

```
Array: True
PoolByteArray: False
PoolColorArray: True
PoolIntArray: False
PoolRealArray: False
PoolStringArray: True
PoolVector2Array: True
PoolVector3Array: True
```

(I tested on 3.2, because it is more convenient for me, but it seems that the behavior is not different on 4.0.)

**Comment by dalexeev** [comment]
Alternatively, we can add the `fill()` method:

```gdscript
var buf = PackedByteArray()
buf.resize(256)
buf.fill(0)
```

**Comment by Xrayez** [comment]
> Also, this behavior is inconsistent with other types of arrays:

I think this is because types such as `Color`, `String`, `Vector2` etc. are `Variant` types, so they have a constructor, unlike primitive types.

Relevant code (3.2): https://github.com/godotengine/godot/blob/93172515de86147ca31783fbe600f17526b462d0/core/cowdata.h#L293-L301

**Comment by dalexeev** [comment]
I think whether we add `fill()` method or not, we should add optional parameter to the `resize()` function, because `fill()` fills all elements of the array, and `resize()` with `zero_new_elements = true` fills only new elements.

**Comment by Shatur95** [comment]
> I believe this is "expected", in the sense that this is what happens with C/C++ code; initializing new memory arrays with "default" values is generally a waste of resources, since the programmer is likely to fill in their data afterward.

In C ++, `std :: vector` will be filled with zeros when using the [resize](https://en.cppreference.com/w/cpp/container/vector/resize) function.

**Comment by noidexe** [comment]
I came across this behavior yesterday when resizing a PoolIntArray in 3.4.beta1
It'd be nice to have void resize(idx: int, fill:bool = true) so that by default it works as expected of a high level language but you still have the current behavior available for when the performance impact is noticeable.

**Comment by Xrayez** [comment]
It's possible to fill an array with `fill()` method now, see #46476, but it wasn't backported to 3.x. Also note that Godot implicitly follows single-responsibility principle.
