### ISSUE TITLE
Incorrect "Unreachable code" warning in a for loop

### ISSUE THREAD

**Issue by pomalley** [godotengine/godot#43037]
[I searched "unreachable code" in open issues and didn't find anything related.]

**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
The gdscript analyzer reports an "unreachable code" warning when a for loop has a return statement after a continue. (See code example below.)

**Steps to reproduce:**
This code produces an unreachable code warning for line 10 (the one after the for loop):

```gdscript
extends Control

func _ready():
	var numbers = [1, 2, 3]
	for i in numbers:
		if i > 0:
			continue
		$Label.text = "in the loop"
		return
	$Label.text = "escaped the loop"
```
![image](https://user-images.githubusercontent.com/1106276/97010809-e7a76000-1513-11eb-8c92-7c72389daea9.png)

**Minimal reproduction project:**

[bug.zip](https://github.com/godotengine/godot/files/5429787/bug.zip)

**Comment by Paavs-Git** [comment]
This no longer happens in 3.2.2.stable onwards. That is to say it seems to have been fixed already. I suggest you upgrade to the most recent stable version, 3.2.3.stable.

**Comment by pomalley** [comment]
Ha, that's what I get for not checking for upgrades. Sorry for the churn.
