### ISSUE TITLE
Godot keeps xdg-open zombie processes

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#43048]
**Godot version:**
3.2.3.stable.official
4.0 - I haven't tested

**OS/device including version:**
KDE Plasma Version: 5.20.0
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.8.15-1-default

**Issue description:**
![](https://user-images.githubusercontent.com/47700418/97080494-6d0a3d80-1604-11eb-8fbe-bfbdd47cf4ce.png)
Closing Godot removes the zombie processes.
_I don't know, maybe the bug is not in Godot, but in KDE, because I noticed the `kde-open5` process opening briefly._

**Steps to reproduce:**
Project > Open Project Data Folder
![](https://user-images.githubusercontent.com/47700418/97080913-8b256d00-1607-11eb-9042-6c70fc1320bd.png)

**Minimal reproduction project:**
—

**Comment by Calinou** [comment]
The issue is likely in the X11 implementation of `OS::shell_open()`.

**Comment by Ev1lbl0w** [comment]
From what I've tested, `xdg-open` and `kde-open` don't block when they're done launching the file browser, so I believe it's safe for Godot to wait for these processes to finish *(also `gnome-open` is deprecated for nearly a [decade now](https://askubuntu.com/questions/101965/what-is-the-replacement-for-gnome-open-in-gnome), so it would be best to switch to new alternatives)*
