### ISSUE TITLE
yield AudioStreamPlayer finished signal on html export not working

### ISSUE THREAD

**Issue by dpensky** [godotengine/godot#43040]
I have this code:

`$background.stop()`

`yield($background, "finished")`

`emit_signal("game_load_requested", game_name)`

that works perfectly on the engine and the signal is emitted after the sound stops.

however when I export to html, the signal is emitted immediately, before the sound stops.

is this an engine problem or what am i doing wrong?

$background is a AudioStreamPlayer with a ogg file playing on loop

tanks in advance

**Comment by Chlipouni** [comment]
I have the same problem in my project.
In desktop mode, the sound is played once and the "finished" signal is emitted at the end.
In hmtl5 export, the sound is played indefinitely (in loop mode) and the "finished" signal is not emitted (may be the correct behaviour in this case).
To obtain the same behaviour in both cases, it is necessary to set the "loop" property to "false" explicitly (for the "AudioStreamOGGVorbis" instance).
It seems that the default value of the "loop" property is not the same in Html5 exports.
