### ISSUE TITLE
Godot Editor crash, shader parser/compiler bug in long shader

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#43055]
**Godot version:**
**OS/device including version:**
3.2.2-stable and 3.2.3-stable, Windows and Linux act same, GLES2 and GLES3 does not matter
I did not test on other version
GPU Nvidia

**This can be Nvidia only Bug**. I tested it on AMD, did not happen on AMD.

**Issue description:**
Godot crash without even log to console, it just silently crash.

**Steps to reproduce:**
(I do not have time to make smallest shader code, this my original shader where I found this bug)
**Bug happened on compile!**
Download my example project(open Spatial.tscn in Godot) or copy **[this my shader](https://github.com/danilw/godot-utils-and-other/blob/gh-pages/BUG_shader_parsing/Spatial.shader)** to your Godot as MeshInstance material.

Edit line 263 in shader
```
// EDIT NEXT LINE
    if (i == 3) {
```
Change `3` to `4` to `3` and to `4` back, **every time after editing wait when shader compiled**(few sec), in one of this compiles Godot crash.
Shader is valid, there no inf loop of anything.

**Minimal reproduction project:**
[shader_compile_bug.zip](https://danilw.github.io/godot-utils-and-other/BUG_shader_parsing/shader_compile_bug.zip)

**Comment by danilw** [comment]
Will be nice if someone confirm this, because **it can be only my system bug**(RAM or CPU or GPU broken somehow), I tested it on two PC, it happens only on PC with Nvidia.

**Comment by smix8** [comment]
The test Shader crashes reliably after 5th or 6th edit/compile for me on 3.2.3-stable.official, Win10, GTX980.

Sidenode, test project already has all ProjectSettings memory limits and messagequeuesize increased (x10 due to skeleton crashes in 3.x).

**Comment by Calinou** [comment]
@smix8 If you can compile a debug build, can you give us a backtrace here?

**Comment by smix8** [comment]
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] DrvPresentBuffers
[1] DrvPresentBuffers
[2] DrvPresentBuffers
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] BaseThreadInitThunk
-- END OF BACKTRACE --

I tried now with both GTX980 ( older driver) and RTX2080 (most recent NVIDIA driver) with the same crash result. I noticed that the editor freezes with each edit/compile for a longer time (up to ~ 2sec until crash, 1rst shader edit/compile is instant for me).

I also tested the same shader with the recent Godot 4.x Vulkan build. After 50+ edits/compiles without freeze or hiccups I would say it doesn't crash on the Vulkan branch.

**Comment by danilw** [comment]
@smix8 thank you for tests
as I say already, I tested it on AMD, and there no crash
from what I saw this is a very weird bug, and I was not sure if it Godot or Nvidia bug, or maybe my CPU/RAM broken...

on Linux this bug-crash do not have any "output" I even tried launch it with GDB, silent crash
on WIndows it crashes same way

**Comment by Chaosus** [comment]
Hmm... this complex shader leads to shader compiler crash on master (even without any action):

```
 494 | /* clang-format off */
 495 | layout(set = 5, binding = 11) uniform texture2D m_light_data;
 496 | layout(set = 5, binding = 6) uniform texture2D m_panorama_bg;
 497 | layout(set = 5, binding = 5) uniform texture2D m_texture_5;
 498 | layout(set = 5, binding = 9) uniform texture2D m_pallte;
 499 | layout(set = 5, binding = 8) uniform texture2D m_floor_tile;
 500 | layout(set = 5, binding = 2) uniform texture2D m_texture_2;
 501 | layout(set = 5, binding = 4) uniform texture2D m_texture_4;
 502 | layout(set = 5, binding = 7) uniform texture2D m_floor_texture;
 503 | layout(set = 5, binding = 10) uniform texture2D m_chbtex;
 504 | layout(s   at: ShaderRD::_compile_variant (servers\rendering\rasterizer_rd\shader_rd.cpp:338)
ERROR: Error compiling Vertex shader, variant #4 (
#define MODE_RENDER_DEPTH
#define MODE_RENDER_MATERIAL
).
   at: ShaderRD::_compile_variant (servers\rendering\rasterizer_rd\shader_rd.cpp:334)
ERROR: Failed parse:
ERROR: 0:508: 'location' : overlapping use of location 11
ERROR: 1 compilation errors.  No code generated.

```

**Comment by danilw** [comment]
@Calinou after rebooting it does not crash from "first try"
for me it depends on the boot, sometimes it crashes on the first try just open my shader, sometimes after editing... 

if I have time today/tomorrow il try to get full shader code and make bugreport to Nvidia

**Comment by danilw** [comment]
after debugging today I found source of bug
**This is Nviida compiler bug, so this bugreport has nothing to do with Godot.**

Minimal Godot shader to crash Nvidia compiler:
```
shader_type spatial;
render_mode blend_mix, depth_draw_opaque, cull_back, diffuse_burley,
    specular_schlick_ggx, unshaded;

// minimal shader for bug https://github.com/godotengine/godot/issues/43055

uniform float time; // >0

varying vec2 fc[4];

void vertex(){
  fc[0]=vec2(0.);
  fc[1]=vec2(0.);
  fc[2]=vec2(0.);
  fc[3]=vec2(0.);
}

void fragment ()
{
  float tval=0.;
  //tval=min(time,0.); // fix - uncomment this also fix, this tval is 0 always
  
  vec2 m_uv1[4];
  m_uv1[0]=fc[0]+tval;
  m_uv1[1]=fc[1]+tval;
  m_uv1[2]=fc[2]+tval;
  m_uv1[3]=fc[3]+tval;
  
  float d=0.0;
  ALBEDO = vec3(0.);
  
  for (int i = 0; i < 8; i++) {
    int tx=int(min(time,0.)); // fix - moving this out of loop fix crash
    if ((tx==0)&&(i<4)) {
      d = m_uv1[uint(i)].x;
      return;
    } else {
      d = m_uv1[uint(i - 4)].x; // crash
      // d = m_uv1[uint(max((i - 4),0))].x; // fix
    }
  }
  ALBEDO = vec3(d);
}

```

[Nvidia forum bugreport  link](https://forums.developer.nvidia.com/t/nvidia-opengl-glsl-compiler-crash-on-this-shader-when-index-of-array-expected-by-compiler-to-be-out-or-range/158267)

Reason obvious - Nvidia compiler "expect" that index in this operation `m_uv1[uint(i - 4)]` make out of range(when it does not in logic), and when `m_uv1` defined as `in` compiler can not address this array and crash. I list obvious "fixes" every one of them works.

**Comment by danilw** [comment]
I think it can be closed because the latest Nvidia driver bring even more "GLSL" bugs than this...
