### ISSUE TITLE
Timer Feature Request

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#4305]
For more flexibility with timers in loops, you should make the timer.start() work once(not talking about oneshot) so the timer does not reset when timer.start() is called over and over, but allow a second function or a condition to be called that allows for this. Ex: timer.reset_and_start(), or timer.start(Bool reset)

**Comment by HeartoLazor** [comment]
I'm fine how it's now, sometimes abuse that exact behaviour from start on my game for reset cooldowns. If you really want to start don't reset the timer put this check before the call:
```
if(_timer.get_time_left() <= 0.0):
	_timer.start()
```

**Comment by suptoasty** [comment]
I'll try that then. Thanks lazor.
