### ISSUE TITLE
Mono iOS export error "Mono AOT compiler exited with code: 134".

### ISSUE THREAD

**Issue by fadexmusic** [godotengine/godot#43065]
**Godot version:**
v3.2.4.beta1.mono.official

**OS/device including version:**
MacOS Catalina 10.15.7, Macbook Pro 15" 2017

**Issue description:**
Exporting to iOS leads to the error "Mono AOT compiler exited with code: 134", resulting in the project not exporting.

**Steps to reproduce:**
1. Create a project
2. Add a C# script
3. Export to iOS

**Minimal reproduction project:**
[monoerror.zip](https://github.com/godotengine/godot/files/5433836/monoerror.zip)

**Comment by akien-mga** [comment]
@neikeq I guess that might be because the AOT compiler I used is the one you built for me back when we were using Mono 6.6.0.166, but 3.2.4 beta 1 uses 6.12.0.102. So https://github.com/godotengine/godot-mono-builds's CI should be updated to track the same release, so I can use the resulting AOT compiler.

**Comment by fadexmusic** [comment]
Guess I can’t resolve this without recompiling the engine ?

**Comment by fadexmusic** [comment]
please? :D

**Comment by akien-mga** [comment]
You can use 3.2.3 stable until we get to fixing this.

**Comment by fadexmusic** [comment]
I know, but 3.2.3 has the input delay bug. My game doesn't work with that.

**Comment by akien-mga** [comment]
@fadexmusic Could you try 3.2.4 beta 5? I updated the cross-compiler version in 3.2.4 beta 2, so this should be fixed now.

**Comment by akien-mga** [comment]
I asked others to test with 3.2.4 RC 4 and it seems fixed, so closing.
