### ISSUE TITLE
angle_to_point() is reversed

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#43063]
**Godot version:**

3.2.3

**Issue description:**
Title.
`Vector2.RIGHT.angle()` equals to 0.
Now, `(Vector2(200, 0) - Vector2(0, 0)).angle()`, which supposed to be a direction from (0, 0) to (200, 0), equals to 0, consistently with the above.
HOWEVER `Vector2(0, 0).angle_to_point(Vector2(200, 0)` equals to π, which is in the opposite direction, inconsistently with the `angle()` method.

These two should yield equal results.

**Comment by timothyqiu** [comment]
I think this is a duplicate of #16307
