### ISSUE TITLE
Adding to properties no longer works

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#43064]
**Godot version:**

8718107

**Steps to reproduce:**
1. Have any scene with a Sprite2D child
2. Use this code
```
func _process(delta: float) -> void:
	$Sprite2D.position.x += delta
```
3. The sprite doesn't move

`$Sprite2D.position.x = 200` seems to be fine.

**Comment by Anutrix** [comment]
It works for me on Windows 10 in 3f7f4fb6f  at least. The movement is very slow though. I will test on latest master build https://github.com/godotengine/godot/commit/6c173e2f7ffdb972ec3754b3d78fe51bfbfb4f22 soon.

**Comment by KoBeWi** [comment]
Ok it was probably mistake on my side, I can't reproduce it anymore.
