### ISSUE TITLE
OpenGL 3.0 - Error

### ISSUE THREAD

**Issue by MiccoXW** [godotengine/godot#43062]
Hello, I have an old video card and when I try to run a project in OpenGL 3.0 the card just stops working (the video), when I'm starting it also shows some errors:
`ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5120`

My video card is ATI Radeon 3100 Graphics (VERY old, but it supports OpenGL 3.0 as far as I know), I still can't buy a new video card, is there any way to fix this or is it a "bug" in my board?

**Comment by Calinou** [comment]
> My video card is ATI Radeon 3100 Graphics (VERY old, but it supports OpenGL 3.0 as far as I know), 

Godot's GLES3 requires full OpenGL 3.3 support, not just 3.0.
