### ISSUE TITLE
Audio doesn't work on iPhone in silent mode.

### ISSUE THREAD

**Issue by fadexmusic** [godotengine/godot#43071]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
MacOS Catalina 10.15.7, Macbook Pro 15" 2017,  iOS 14, iPhone 8

**Issue description:**
The audio doesn't work on an iOS device in silent mode. All the other games/apps do play audio in silent mode, because  the silent mode is there just to prevent the iPhone from playing unexpected sounds (call, notification, etc.). It would make more sense to allow audio to go through in silent mode.

**Steps to reproduce:**
1. Export to iOS
2. Put iPhone in silent mode
3. Run game

**Minimal reproduction project:**
[iosaudio.zip](https://github.com/godotengine/godot/files/5434355/iosaudio.zip)

**Comment by fadexmusic** [comment]
Actually, this is intended behaviour as per apple guidelines: https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/audio/

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/50638.
