### ISSUE TITLE
Image thumbnails too large in Filesystem dock list view on hiDPI display

### ISSUE THREAD

**Issue by Alterae** [godotengine/godot#43074]
**Godot version:**

v3.2.3.stable.official

**OS/device including version:**

Windows 10 Home version 2004 running on an HP Spectre x360 Convertible 15-ch0xx

GPU: Nvidia Geforce MX150

Display resolution: 3840x2160

**Issue description:**

_Expected behavior:_ In the filesystem dock, when set to list view, icons/thumbnails for image files should be the same size as icons for other files.

_Actual behavior:_ In the filesystem dock, when set to list view, icons/thumbnails for image files are approximately twice the size of other icons.

_Screenshot:_
![image](https://user-images.githubusercontent.com/27498421/97110132-10a72c80-169d-11eb-94a7-de76eed78613.png)
As shown, image icons are substantially larger than icons for scripts or scene files, which is distracting and makes scanning the filesystem visually more difficult.

**Steps to reproduce:**

1. In the Godot editor, open any Godot project containing at least one image file and at least one folder or non-image file.
1. In the filesystem dock, either toggle split mode **off**, or with split mode on set the bottom pane to "View items as a list".
1. Icons for image files will be larger than icons for normal files.

**Minimal reproduction project:**
This appears to be a bug with the editor, as it happens with every project on my machine regardless of project settings.

Regardless, attached is a .zip file of a fresh Godot project in which the issue manifests.
[FileIcons.zip](https://github.com/godotengine/godot/files/5434926/FileIcons.zip)

**Comment by timothyqiu** [comment]
I think this has been resolved by #42426

BTW: Big thumbnails generated before this fix may still appear large due to caching.

**Comment by akien-mga** [comment]
Fixed by #42426 (you can try 3.2.4 beta 1 to confirm).
