### ISSUE TITLE
1.7 does not equal to 1.7

### ISSUE THREAD

**Issue by kcl101** [godotengine/godot#43077]
**Godot version:**

v3.2.1.stable.mono.official

**OS/device including version:**

Windows 10 (not really related)

**Issue description:**

GDscript does not return print(1.7 == 1.6+0.1) as true, while all other numbers I entered are behaving correctly.

**Steps to reproduce:**
1. Create a script
2. Type print(1.7 == 1.6+0.1) and run
3. It will return false

**Minimal reproduction project:**

**Comment by qarmin** [comment]
In programming `0.9` isn't equal to `0.1 + 0.8` due not being able to reproduce these numbers accurately in a binary system.

https://en.wikipedia.org/wiki/Floating-point_arithmetic

**Comment by mrjustaguy** [comment]
Use is_equal_approx(1.7,1.6+0.1) and it'll return true
so the line would be:
print(is_equal_approx(1.7,1.6+0.1))
output would be:
True
