### ISSUE TITLE
Godot not opening imported projects

### ISSUE THREAD

**Issue by IonAir1** [godotengine/godot#43087]
**Godot version:**
Godot 3.0.6 stable

**OS/device including version:**
Crostini/Chrome OS 86 |Lenovo chromebook s340 14-touch

**Issue description:**
Whenever I scan a folder or import a project it detects it however when I cant open the projects, only the projects made in the laptop I was able to open.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Ev1lbl0w** [comment]
Can you send the project that's causing you trouble?

Also Godot 3.0.6 is very old, can you confirm this happens with the latest stable version too *(3.2.3)*?

**Comment by Calinou** [comment]
@IonAir1 Bump :slightly_smiling_face: See Ev1lbl0w's comment above.

**Comment by nathanfranke** [comment]
Issue is very outdated and likely invalid. @Calinou
