### ISSUE TITLE
Issue with Blender armatures and Godot Engine

### ISSUE THREAD

**Issue by Polecat-Punter** [godotengine/godot#43085]
I don't know why but when I import rigged characters into Godot the armature and all the bones from blender turn into spatial nodes. Sometimes the meshes related to the bones are deformed in an undesired way but no bones. I tried all the file formats available.GLB .GLTF .GLTF+BIN .FBX .OBJ

The only thing that kind of resembled bones was .DAE but it only created 5 skeletons and no bones and no meshes. I had more than 5 bones In the rig

if there is a way to create 3D bones in Godot that I could work around it  or is there an addon that I need

I am using Godot 3.2.3 and blender 2.80

**Comment by smix8** [comment]
You can try ESCN from the Godot Blender Exporter Addon.
https://github.com/godotengine/godot-blender-exporter

**Comment by fire** [comment]
Can you post a minimal reproduction project?  --  A small Godot project which reproduces the issue.

**Comment by fire** [comment]
I don't have a reproduction case. Closing. Feel free to add a minimal reproduction project.
