### ISSUE TITLE
Vulkan: Per-vertex shading not working

### ISSUE THREAD

**Issue by AlzoPalzo** [godotengine/godot#43093]
**Godot version:**
v4.0.dev.calinou.e16729a8c

**OS/device including version:**
Windows 10, GTX 1070, Vulkan

**Issue description:**
In Godot 3.2 I used Tree models with their normals edited in blender in tandem with per vertex shading to create smoothly shaded trees. In Godot 4.0, with vulkan backend switching the shading between per vertex and per pixel has no effect on the tree models

Examples of the expected result are shown below where the trees on the left are shaded per pixel and the trees on the right are shaded per vertex.
![treeShadingExample2](https://user-images.githubusercontent.com/36478304/97184947-619b4b80-1797-11eb-9559-4c99a011a9c1.png)

![treeShadingExample](https://user-images.githubusercontent.com/36478304/97184923-5a743d80-1797-11eb-9546-b99ab2e00ed0.png)

**Steps to reproduce:**
Add a directional Light or other lights to the models and in the material turn on the per vertex shading flag(3.2) or switch shading to per vertex(4.0)

**Minimal reproduction project:**

[LowPolyTrees.zip](https://github.com/godotengine/godot/files/5439432/LowPolyTrees.zip)

**Comment by r0-che** [comment]
vertex shading still does not work in 4.0

![3](https://user-images.githubusercontent.com/60857418/195976570-63fe28d9-b759-4f8d-9e41-646f0b951370.png)
godot 3.5, vertex shading on the left
![4](https://user-images.githubusercontent.com/60857418/195976572-ab002196-85dc-41d7-87f0-33b88877c4d4.png)
godot 4.0 beta, vertex shading on the left aswell

**Comment by AestheticalZ** [comment]
It seems it's also happening in the gl_compatibility and mobile renderers. I tried using the shaders from godot-psx on all 3 renderers and none of them have vertex lighting, only pixel lighting.

**Comment by zCubed3** [comment]
I've noticed 2 things regarding vertex lighting in 4.X, I hope it can be of help to someone more talented with graphics programming.

1. Looking at 3.X, I can see that `scene.glsl` contains the `USE_VERTEX_LIGHTING` flag. While in the master branch, `scene.glsl` (and its equivalents) are completely missing the flag.
2. It also appears that from the C++ side of things that `USE_VERTEX_LIGHTING` is never set anymore. The flag doesn't exist anymore in `material.h` either?

**Comment by clayjohn** [comment]
> I've noticed 2 things regarding vertex lighting in 4.X, I hope it can be of help to someone more talented with graphics programming. (I'll note these are just my observations, I know nothing about how Godot's rendering pipeline works)
> 
> 1. Looking at 3.X, I can see that `scene.glsl` contains the `USE_VERTEX_LIGHTING` flag. While in the master branch, `scene.glsl` (and its equivalents) are completely missing the flag.
> 2. It also appears that from the C++ side of things that `USE_VERTEX_LIGHTING` is never set anymore. The flag doesn't exist anymore in `material.h` either?

Vertex lighting hasn't been re implemented yet in 4.x

**Comment by zCubed3** [comment]
👍 Thanks, good to know.

**Comment by pozitiffcat** [comment]
When it will be implemented? 20 fps on mobile devices with only one direct light is no good ((

**Comment by Calinou** [comment]
> When it will be implemented? 20 fps on mobile devices with only one direct light is no good ((

This won't be done for 4.0 due to time constraints.

**Comment by TerraDev64** [comment]
I hope it will be fixed soonish after the 4.0 release. It's to be honest a very important feature to have for many.

**Comment by GithubPrankster** [comment]
Could this issue be looked into now that 4.0 is out and 4.1 is nearing? It reduces the feasibility of retro 3D work in the current iteration of the engine. I personally would be happier with a proper solution to #39513 but I'll take anything at this point.

**Comment by Calinou** [comment]
There's no ETA for implementing this feature, and nobody has looked into it yet to my knowledge. Feature freeze for 4.1 is approaching, so this won't be merged before 4.2 at the earliest.

**Comment by MicrotonalMatt** [comment]
Any update on ETA? I just tried with 4.2-dev4 and still not working. This and [#4619](https://github.com/godotengine/godot-proposals/issues/4619) are deal breakers for moving my project from 3 to 4 unfortunately.

**Comment by Calinou** [comment]
> Any update on ETA?

[Same as before](https://github.com/godotengine/godot/issues/43093#issuecomment-1565636336), as rendering contributors are busy with other tasks currently.

**Comment by golddotasksquestions** [comment]
I just want to state that I think this needs to be given much higher priority. 

One of Godots most prominent usecases is 3D retro games. PS1 style games. 3D games that rely on classic vertex lighting. The internet is filled with free and paid tutorials and complete courses which teach how to create Godot games in that style. People come to Godot knowing it's not a AAA engine, but they expect to be able to do 3D retro games with per-vertex lighting.

**Comment by AThousandShips** [comment]
Anyone willing and able to fix this is welcome to, we can't order people to just fix one specific thing, and this was worked on but the contributor is busy, so it isn't like this is just ignored

**Comment by golddotasksquestions** [comment]
>  we can't order people to just fix one specific thing

a) Everyone knows people who contribute for free on their own time out of their own ambition can't be ordered or forced to work on anything specific. Insinuating anyone would assume otherwise is honestly pretty offending.

b) Also everyone knows the Godot core devs and maintainers are able promote specific issues, bring attention to them and ask for help or if anyone would like to take this on, and offer support. This has been done countless times before (for example on various social media channels of core devs and maintainers). Often very successfully.

c) Also everyone knows the Godot Foundation is able to hire people **_to work on on specific issues_**. This has also been done before countless times. Also everyone knows Godot Foundation has received a massive uptick in donations recently due to the Unity debacle.

**Comment by AThousandShips** [comment]
I'm sorry if pointing that out is offensive, I meant no offense, but I see no other way of "prioritising" it if no one is willing or able to work on it

I don't see this as not being promoted or prioritised, seeing the attention it has and is getting

**Comment by golddotasksquestions** [comment]
> I don't see this as not being promoted or prioritised, seeing the attention it has and is getting

I don't see any of the core devs with a large following promoting this issue on their socials, or the foundation taking some of the money in their hands and offer to hire someone to fix it. Such a promotion could be shared on the [official Godot twitter](https://twitter.com/godotengine) with ~100K followers, and by Remi and Juan. There could also be a separate tab on https://godot.foundation/ next to "Donations" saying "For hire", where prioritized Github issues are linked. They could also post and promote on the Godot subreddit with 142K subscribers and the Godot Discord server.

So I think there is still a lot of room to prioritize & promote this issue.

**Comment by ywmaa** [comment]
@golddotasksquestions well I need this feature too, so I am going to try to do it, though I am new to rendering.

**Comment by ywmaa** [comment]
I looked at the material.cpp and material.h, I saw vertex shading parameters, so I guess I need to only do the rendering backend, right ?

**Comment by AnalogFeelings** [comment]
> I looked at the material.cpp and material.h, I saw vertex shading parameters, so I guess I need to only do the rendering backend, right ?

I am pretty sure the entire framework for it is already done, but the shaders lack the code required to handle vertex lighting.

**Comment by ywmaa** [comment]
> > I looked at the material.cpp and material.h, I saw vertex shading parameters, so I guess I need to only do the rendering backend, right ?
> 
> I am pretty sure the entire framework for it is already done, but the shaders lack the code required to handle vertex lighting.

Yeah that's true, atleast for GLES3 

I looked at the scene.glsl and it looks like it only needs to add the Vertex Shading pass and we are good to go (Working on it).

Does vulkan use this shader too ?

**Comment by Calinou** [comment]
> Does vulkan use this shader too ?

Forward+ uses `scene_forward_clustered.glsl`, Mobile uses `scene_forward_mobile.glsl`. Both include `scene_forward_lights_inc.glsl`.

**Comment by ywmaa** [comment]
My draft PR
https://github.com/godotengine/godot/pull/83360

**Comment by SamBWarren** [comment]
What is the status of this PR? Could it be implemented in 4.3?

**Comment by Calinou** [comment]
I made MRPs to test shading mode performance in 3.x and 4.x:

- [test_shading_modes_3.x.zip](https://github.com/godotengine/godot/files/15324121/test_shading_modes_3.x.zip)
- [test_shading_modes_4.x.zip](https://github.com/godotengine/godot/files/15324122/test_shading_modes_4.x.zip)

This is a situation where per-vertex shading gives you nearly identical visuals, but can greatly improve performance in situations where you have lit particles close to the camera.
In games, there are two common situations where this occurs:

- In a racing game, you race on a wet track with rain/water particles from other cars in front of you. This gets particuarly noticeable in interior cameras. An example of this is the F1 series, to the point where the most popular benchmark scenario is a rainy track with 20 cars and the player being last.
- In a FPS, you walk through a corridor filled with smoke. An example of this is in Doom 2016 (the game uses per-vertex shading on subdivided quads for shading particles, with automatic subdivision depending on distance).

Many people use vertex shading for stylistic reasons, but personally I want it for performance reasons first and foremost. This is doubly true on mobile and integrated graphics – I only tested a top-end dedicated GPU here and the difference is already pretty noticeable. You can imagine it only gets that much more important on low-end GPUs :slightly_smiling_face: 

Results with the MRPs on a RTX 4090 in 4K for reference:

### 3.5.2 GLES3

[Imgsli](https://imgsli.com/MjY0MTgy/0/1)

Per-pixel | Per-vertex | Unshaded
-|-
1449 FPS (0.69 mspf) | 1842 FPS (0.54 mspf) 1936 FPS (0.52 mspf)

### 4.3.dev5 Forward+

[Imgsli](https://imgsli.com/MjY0MTkw)

Per-pixel | Unshaded
-|-
856 FPS (1.17 mspf) | 1875 FPS (0.53 mspf)

### 4.3.dev5 Compatibility

[Imgsli](https://imgsli.com/MjY0MTkw/2/3)

Per-pixel | Unshaded
-|-
2105 FPS (0.48 mspf) | 3259 FPS (0.31 mspf)

If done well, a 4.x implementation of per-vertex shading should offer performance between per-pixel shading and unshaded (but it should be closer to unshaded than per-pixel), like in 3.x.

**Comment by akien-mga** [comment]
Fixed by #83360.
