### ISSUE TITLE
error: use of undeclared identifier 'strcpy_instead_use_StringCbCopyA_or_StringCchCopyA'

### ISSUE THREAD

**Issue by fire** [godotengine/godot#43094]
**Godot version:**
825ab3b

**OS/device including version:**
CentOS Linux 8.2.2004 Core

**Issue description:**
Mingw can't compile Godot version.

**Steps to reproduce:**

PATH=/opt/llvm-mingw/bin:$PATH scons werror=no platform=windows use_llvm=yes use_lld=yes target=release_debug -j4 use_lto=no deprecated=no

https://github.com/mstorsjo/llvm-mingw

My guess is that Godot Engine needs to use `STRSAFE_NO_DEPRECATE`.

Source: https://social.msdn.microsoft.com/Forums/vstudio/en-US/b06cd738-f3e8-4f2b-8268-69a2a6d3de11/help-error-c2065?forum=vcgeneral

**Minimal reproduction project:**
Git clone https://github.com/godotengine/godot @ 825ab3b

[compile-log.txt](https://github.com/godotengine/godot/files/5439502/compile-log.txt)

**Comment by bruvzg** [comment]
Might be related to #42817, but probably not, `strcpy(ext_list->list[idx].entrypoints[i], entrys[i]);` line seems to be the same as before.

**Comment by akien-mga** [comment]
> Might be related to #42817, but probably not

@fire Is this a regression from today or is this the first time you try this toolchain?

**Comment by fire** [comment]
Here's a log:
![image](https://user-images.githubusercontent.com/32321/97193070-d2c20b00-1765-11eb-8919-976155aa3524.png)

**Comment by fire** [comment]
I added `"STRSAFE_NO_DEPRECATE"` to drivers/vulkan/SCsub and it passed.

```c++
    if env["platform"] == "windows":
        loader_sources.append("dirent_on_windows.c")
        env_thirdparty.AppendUnique(
            CPPDEFINES=[
                "VK_USE_PLATFORM_WIN32_KHR",
                "VULKAN_NON_CMAKE_BUILD",
                "WIN32_LEAN_AND_MEAN",
                "STRSAFE_NO_DEPRECATE",
                'API_NAME=\\"%s\\"' % "Vulkan",
            ]
        )
        if not env.msvc:  # Windows 7+, missing in mingw headers
            env_thirdparty.AppendUnique(
                CPPDEFINES=["CM_GETIDLIST_FILTER_CLASS=0x00000200", "CM_GETIDLIST_FILTER_PRESENT=0x00000100"]
            )
```
