### ISSUE TITLE
Making a very thin ProgressBar

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4310]
It is currently not possible to make a very thin ProgressBar (in height, not width).

I'd like to have such progress bars for health bars above enemies, but I can't make them less high, even if they don't contain any text and use flat styling.

**Comment by akien-mga** [comment]
Even in master which contains #4191?

**Comment by Calinou** [comment]
> Even in master which contains #4191?

You are right, it is possible now to make very thin ProgressBars, closing.
