### ISSUE TITLE
Unify get_pos() / get_translation()

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4311]
I gave a try to 3D in Godot and I got confused by the naming convention.
In 2D, you use get_pos() and get_rot(), but in 3D it's get_translation() and get_rotation().
This got me to write errors in my code everytime because of the different names.
I think the names of these functions should be unified for clarity, because they do the same thing in space.

**Comment by slapin** [comment]
Well, in 3D it is better to use Transform class. The concepts are too different in use to make them look similar.

**Comment by Zylann** [comment]
I know transforms are better in 3D, but it's more about the naming, for transforms or shortcuts.

**Comment by reduz** [comment]
this was done already, closing
