### ISSUE TITLE
rand_range() doesn't return random numbers

### ISSUE THREAD

**Issue by sphere-a** [godotengine/godot#43128]
**Godot version:**
Godot 3.2.3

**OS/device including version:**
windows 10

**Issue description:**
every time I run a program with rand_range() it returns the same numbers.

**Steps to reproduce:**
open a script type:
func _ready():
  for i in range(10):
    print(rand_range(0, 10)

run this program two times and compare the numbers you got

**Comment by mrjustaguy** [comment]
use Randomize when initializing

**Comment by DanielJamesCollier** [comment]
You need to seed the random number generator

**Comment by Chaosus** [comment]
Yes, it's not a bug just a misuse. Closed.

**Comment by sphere-a** [comment]
thx
