### ISSUE TITLE
Android build crashes when using C# threads

### ISSUE THREAD

**Issue by hedi-sel** [godotengine/godot#43122]
**Godot version:** Godot Engine v3.2.3.stable.mono.official
**OS/device including version:** Linux Mint 19.3
**C# version:** .NET Core 3.1
**Issue description:** Any scene crashes if it contains a C# script that uses the `Threads` library.
**Steps to reproduce:** 
Make a script that contains an at least `await` and an `async` function
Export for Android
Run the .apk on any debugging platform
It crashes immediatly (even before the `await` or the `async` are reached)

You can find [here](https://we.tl/t-ZH6NUxdkSZ) a minimal Godot project

**Comment by akien-mga** [comment]
Can you still reproduce this in 3.5.2 and 3.6-beta2 or later?

If so, could you provide a new reproduction project? The previous link expired. You can upload a zip directly to GitHub with a drag and drop.

**Comment by AThousandShips** [comment]
Closing due to lack of response if you provide the requested MRP and details this can be reopened
