### ISSUE TITLE
Using external Sublime text editor on mac opens a new copy every time.

### ISSUE THREAD

**Issue by 01271** [godotengine/godot#43120]
**Godot version:**
3.2.3.stable.official

**OS/device including version:**
OSX 10.14

**Issue description:**
Any time that I want to open a script it will open another copy of sublime text 3. This can get annoying if I wanted to edit multiple files.

**Steps to reproduce:**
My editor settings are:
Use External Editor: True.
Exec Path /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
Exec flags: {project}

I also did use the recommended exec flags from the site: {file}:{line}.

Is it just that I selected the wrong file for the editor?

**Comment by Calinou** [comment]
> Is it just that I selected the wrong file for the editor?

The path seems to be correct. Out of curiosity, can you reproduce this issue with any other external editor such as Visual Studio Code or Atom?

**Comment by 01271** [comment]
I have found the cause of the issue. The issue was caused by my providing the path to the application rather than the path to the sublime text internal file (made for the command line). The correct file path should be:
`/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl`
