### ISSUE TITLE
Beta regression with inspector mask properties.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#43137]
**Godot version:**

Godot_v3.2.4-beta1_win64

**OS/device including version:**

Win10 64-bit

**Issue description:**

The first mask bit in inspector masks don't respond to clicking.  The others work fine, and the expanded menu still works.

![Godot_v3 2 4-beta1_win64_lzQbRyCzmt](https://user-images.githubusercontent.com/13004169/97323319-5a4c6e80-1879-11eb-9ed6-5527b9315e5f.png)

**Steps to reproduce:**
Open any project, and locate a node with a bitmask property.  Try turning the first layer off via clicking.

**Minimal reproduction project:**
Any project will work.

**Comment by akien-mga** [comment]
Fixed by #43084.
