### ISSUE TITLE
Skybox does not seem to work in-game (GLES2)

### ISSUE THREAD

**Issue by gabentoons** [godotengine/godot#43135]
Godot version: 3.2.3 Stable

OS/device including version: Windows 10, Intel HD Graphics 4000, GLES2

Issue description: Skybox does not seem to appear in-game, and I haven't found any indication I did something wrong.

Steps to reproduce

1. Create Node
2. Create WorldEnvironment node as a Child of the first node
3. Create a "New Environment" within WorldEnvironment
4. Right Click the "New Environment" and select Edit
5. Go to Background and set it to Sky
6. Go to the Sky menu that appears after setting the background mode to Sky and select PanoramaSky
7.  (Right Click and Edit)
8. Click the Panorama menu and select Load 
9. Select icon.png
10. Save Scene and Play Project

Minimal reproduction project:
[ripe.zip](https://github.com/godotengine/godot/files/5446028/ripe.zip)

**Comment by clayjohn** [comment]
Do you have a camera in the scene?

**Comment by gabentoons** [comment]
Yes.

**Comment by gabentoons** [comment]
Whoops, turns out I did do something wrong. Apparently, whenever I go to the camera in the "true" project. You can set the environment from there. Not sure why it didn't work in the attached project however.

**Comment by Calinou** [comment]
Closing per @gabentoons' comment.

PS: You can also edit `default_env.tres` since it's marked as the default environment in the Project Settings. To do so, double-click it in the FileSystem dock.
