### ISSUE TITLE
[LSP] Diagnostics are not cleared out when a file is deleted.

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#43133]
**Godot version:**
3.2.3

**OS/device including version:**
Linux 5.4.0 (Linux Mint)

**Issue description:**
The LSP implementation doesn't seem to detect file deletion and thus doesn't clear out the diagnostics of that file.

Linked to https://github.com/godotengine/godot-vscode-plugin/issues/243.
The LSP specification specifies that the creator of the diagnostics is responsible for their deletion (see https://github.com/microsoft/language-server-protocol/issues/463).

**Steps to reproduce:**
Create a new file, write anything invalid in it then save (not saving the file then closing clears out the diagnostics).
Delete the file, notice the diagnostics are still here.

**Minimal reproduction project:**
-

**Comment by akien-mga** [comment]
Fixed in 3.3 by #47553, but not fixed in `master` yet.
