### ISSUE TITLE
UndoRedo.add_do_method fails when arguments are null

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#43141]
**Godot version:**
3.2.4

**Issue description:**
`UndoRedo.add_do_method` throws an error:
*add_do_method: Condition "action_level <= 0" is true.
  <C++ Source>  core/undo_redo.cpp:112 @ add_do_method()*
if any parameter is null:

```gdscript
func create_action():
	call("multiple_parameters") # fails, not enough arguments
	call("multiple_parameters", null, null) # works

	undo_redo.add_do_method(self, "multiple_parameters") # fails, as expected
	undo_redo.add_do_method(self, "multiple_parameters", null, null) # also fails
	undo_redo.add_do_method(self, "multiple_parameters", null, "some value") # also fails

func multiple_parameters(arg1, arg2):
	pass
```

**Steps to reproduce:**
Call `UndoRedo.add_do_method` with null as one parameter.

**Comment by Zylann** [comment]
Similar to https://github.com/godotengine/godot/issues/36895 ?

**Comment by Jummit** [comment]
> Similar to #36895 ?

Yep :D
