### ISSUE TITLE
Different visual shader outputs between two GPUS

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#4316]
**Updated with new info**
**Operating system or device:**
PC1 (notebook)
http://i.imgur.com/gMPJ4gu.png
PC2 (Desktop)
http://i.imgur.com/ZUI6s9S.png
PC3
Intel® Core™ i5-3320M CPU
64Bit Zorin OS 10 (Linux)
4gb DDR3 Ram
Intel-4000 Graphics 

Godot >= 2.0.1

**Issue description** (what happened, and what was expected):
I developed a method for old school color swap with shaders using color palettes and a grey mask, which should be fast and has a low memory overhead.

Shader accept two textures:
A Greyscale texture which is the Grey Mask
A Palette texture where each pixel is a color of the palette (Nx1 size)
Grey Mask has correlative colors where his RGB value represent the index of a pixel color on the palette.
An image which explain better the theory:
![Image of explanation](http://i.imgur.com/IDz2Lp9.png)

So on computers with **AMD Graphics** the result is as **EXPECTED**:
https://gfycat.com/ImmensePoshElectriceel
And on computers with **Intel Graphics** the result is **WRONG**:
https://gfycat.com/ImmediateInformalEmu
Nvidia untested

Note: a visually reference of which palette gets applied to megaman on each button press is on right side, on the intel video for some reason the shader uses the wrong color for the second color of palette.

The shader code:

```
uniform texture palette;
uniform float palette_size;
uniform texture mask;
vec4 mask_color = tex(mask,UV);
vec4 output = tex(TEXTURE,UV);
if(mask_color.r != 1.0)
{
    output = tex(palette,vec2((mask_color.r*255.0)/(palette_size),0.0));
}
COLOR.rgba = output;

```

The culprit is the `palette_size` var, this is an uniform float which represents the width of the palette texture, is updated at gdscript with an int value when is required:
output = tex(palette,vec2((mask_color.r*255.0)/`palette_size`,0.0));

The `palette_size` is different between Intel vs Amd/Nvidia for some reason, could be something about float precision on the GPU or int to float casting. I managed to find a work around about this issue, but is a patch, a bad one I think because a formula written on paper, should behave the same on code always. The work around is to subtract 0.001 to `palette_size`:
output = tex(palette,vec2((mask_color.r*255.0)/(`palette_size-0.001`),0.0));
This behaves the same on all desktop GPUS.

Much more detailed info about the implementation and algorithm used here:
http://www.godotengine.org/qa/2935/best-colour-palettes-asking-again-cause-last-time-didnt-help?show=2979#a2979

**Steps to reproduce:**
- Download the project with the implementation on a computer with an Intel Graphics GPU (Updated with my last finds):
  https://dl.dropboxusercontent.com/s/4axz8j3k359m5a1/pallete_swap_bug.zip?dl=0
- Open it with godot >= 2.0.1 using the intel graphics, if you have a notebook with a dedicated+integrated graphic card, on amd control panel set the godot editor to Power Saving mode. Here a illustrative video how to do that:
  https://gfycat.com/NauticalVillainousAustraliankestrel
  For Nvidia I don't know, I don't have a computer with Nvidia at hand.
  Also don't tested on mobile devices.
- Press the buttons to change megaman from different palettes, look if megaman uses the 0,1,2 color of each palette (visual references from palettes on the right side of buttons)

Shader is on megaman sprite, the script on megaman is for texture and hud management

**Comment by quantum-entangler** [comment]
OK, I have tested on a gtx 680(on windows 7 64bit) and it _seems_ to be working correctly on nvidia graphics cards as well(driver version 347.88), as such I am going to propose that the issue _might_ lye with the intel drivers(they tend to have omitted feature support for versions up to at least openGL 4.3).

Linux side is better in the sense that intel drivers on linux side are open source and intel's been pretty good(at least for the most part) at accepting fixes and whatnot but Windows drivers are still closed source, and thus not contributable to - likely a problem. You claim to be running linux on the system specified however, so I propose you report the bug with _intel's driver team **too**_ if possible and report back if any news.

**Comment by HeartoLazor** [comment]
Hey I managed to "patch" my shader and isolate the bug, but the inconsistencies between Intel Amd/Nvidia are still present.
I will update the main post with my finds.
First pngs saved with photoshop for some reason tends to alter the color RGB on all modes (indexed color, save for web, save as), so the color RGB 2,2,2 gets saved always as 3,3,3 with photoshop. To fix this I used ASEPRITE, with this program the color are saved always with the correct color mapping.
Now for the inconsistencies the problem relies on **uniform float vars**, specifically this var value
`uniform float palette_size;` is inconsistent between intel and amd/nvidia on this line:
`output = tex(palette,vec2((mask_color.r*255.0)/(palette_size),0.0));//this doesn't produce the same result on all gpus`
Take a note `palette_size` is a float on shader but receives INT values from gd script code (the texture width)
I managed to patch this inconsistency with subtract 0.001 to `palette_size`, now the code behaves equal on all desktop gpus, but this doesn't fix the underling problem of inconsistent uniform float values between gpus
`output = tex(palette,vec2((mask_color.r*255.0)/(palette_size-0.001),0.0));//this produce the same result on all gpus`

**Comment by techtonik** [comment]
Looks like something for https://people.freedesktop.org/~nh/piglit/

**Comment by bojidar-bg** [comment]
Well, shouldn't the issue be closed if the origin of the problem is in GPU cards and the way images are compressed?

**Comment by techtonik** [comment]
@bojidar-bg need solid proof about GPU behaviour, so I'd implement practice to close such tickets when (or after) this is covered by appropriate test suite, such as piglit. Why? Because if test is there, the situation still can be improved by 3rd party video driver, maybe even made specifically for Godot by Intel 4000 users (I am in close situation as my main GPU burned out).

**Comment by HeartoLazor** [comment]
@bojidar-bg As I said on my last reply, I found and fixed an issue with compression on my images with ASEPRITE, but that doesn't change the main issue which is **inconsistencies between GPU brands on the same shader**.
@techtonik Hey I couldn't find a binary on the piglit page, Should I compile it, run it and copy the results here?

**Comment by techtonik** [comment]
@HeartoLazor yes, `piglit` is run in rather oldschool ways, so you need to work with sources, especially if your test is missing.

**Comment by trollworkout** [comment]
is this still an issue or has been fixed?

**Comment by HeartoLazor** [comment]
@trollworkout 
Tested in Godot 3.0 apha 1.0 and 2.1.4. Still happening in bot versions.
Because the graphics backend changed in 3.0, and the error is still there, this should be an Intel HW/Drivers issue with float precision, but that doesn't mean we couldn't look a way to patch this.
As @techtonik this should be tested by another specialized tool in future and someday I could implement this exact demo in another opensource engine and look how they fixed it in case of success.

**Comment by techtonik** [comment]
@HeartoLazor more frequently updated site for `piglit` - https://people.freedesktop.org/~nh/piglit/ - and here is how to run it - https://cgit.freedesktop.org/piglit/tree/README

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by HeartoLazor** [comment]
Same behavior in 3.0.2.stable and 2.1.5 rc1.
Here is the updated 3.0 project.
[pallete_swap_bug_3.0.zip](https://github.com/godotengine/godot/files/1890497/pallete_swap_bug_3.0.zip)

**Comment by swarnimarun** [comment]
Seems to be working fine on my Windows, Intel HD 530 latest drivers.

**Comment by randomness128** [comment]
I don't think the uniform is the problem. You're sampling the texture right on the edge between two pixels. Some GPUs are rounding up, some are rounding down. Try this:
`output = tex(palette,vec2((mask_color.r*255.0+0.5)/(palette_size),0.0));`
![image](https://user-images.githubusercontent.com/8137601/41742640-9fe07eda-756c-11e8-80b3-4f75534f7b20.png)

**Comment by HeartoLazor** [comment]
@randomness128 that fixes it, at least in my intel 4000 vs amd m8800 so it's more a rounding issue instead of precision one.
As this is a **GPU** problem, this issue could be closed.
This code is from almost two years ago, we used luts instead of this approach in our game for full palette replacement.
If somebody  want to use this approach I created a repository with the fixed/cleaned/explained code, feel free to use it and improve it.
https://github.com/HeartoLazor/godot_palette_swap

**Comment by techtonik** [comment]
This thread will be useful if research and discovery done here is submitted upstream as piglit tests. I am unable to do this, because of lack of time and expertise, but if you've got everything set up, I'd highly appreciate taking some time to get in touch with guys from pyglit or Igalia - https://blogs.igalia.com/siglesias/2014/11/11/piglit-an-open-source-test-suite-for-opengl-implementations/

**Comment by swarnimarun** [comment]
@HeartoLazor I tried both codes on my old laptop with Core2Duo seems to be working with the new one. 
It should be closed now.
