### ISSUE TITLE
it instance 1st scene but not 2nd bug

### ISSUE THREAD

**Issue by Echua36** [godotengine/godot#43172]
Godot version:
Godot_v3.2.3-stable_win64

OS/device including version:
i5-9300h, intel uhd 630, GLES2

Issue description:
it instance first but not second, and sometime the func _ready():print on this script not working untill i restart the godot

Steps to reproduce:
[Bug report.zip](https://github.com/godotengine/godot/files/5455476/Bug.report.zip)
just run scene and see remote the 2nd batch of tree not showing up
![Godot_v3 2 3-stable_win64_001Umpz8Fn](https://user-images.githubusercontent.com/45130922/97511530-3e081900-19c2-11eb-8fed-15ecce780357.png)

code:
extends Spatial

var load_pointer=0

func _ready():
	print('map')
	print(load_pointer)
	force_load()

func force_load():
	if load_pointer==0:
		add_child(load("res://1kBills Tree_16_1.tscn").instance())
		load_pointer=1
	if load_pointer==1:
		add_child(load("res://1kBills Tree_16_2.tscn").instance())
		load_pointer=2
	if load_pointer==2:
		add_child(load("res://1kBills Tree_16_3.tscn").instance())
		load_pointer=3
	if load_pointer==4:
		add_child(load("res://1kBills Tree_16_4.tscn").instance())
		load_pointer=4
	print('finished loading')

**Comment by pycbouh** [comment]
You've got the names for your scenes wrong. Your files are named with an apostrophe, e.g. `1kBill's` not `1kBills`. All of them, except for the first one, so the code is only correct for the first one.

In future, please use one of our [community channels](https://godotengine.org/community) for support. This repository is reserved for engine issues only.
