### ISSUE TITLE
CanvasGroup is missing a proper icon

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#43189]
**Godot version:**
5bb7c7c

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/97623421-eac7b200-1a25-11eb-8ad1-bc983f748db0.png)

**Comment by Calinou** [comment]
If anyone is willing to contribute an icon, see [Editor icons](https://docs.godotengine.org/en/latest/development/editor/creating_icons.html) in the documentation.

The icon must be SVG, designed with a size of 16×16 (with 1 pixel of padding on each side) and should try to keep its lines on integer coordinates as much as possible.

**Comment by nathanfranke** [comment]
Fixed by https://github.com/godotengine/godot/pull/43220
