### ISSUE TITLE
Incorrect global_transform inside process()

### ISSUE THREAD

**Issue by BenjaminNavarro** [godotengine/godot#43205]
**Godot version:**
3.2.3

**OS/device including version:**
Desktop : Archlinux

**Issue description:**
Accessing a `Spatial`'s `global_transform` from inside a `_process` function can lead to an incorrect value. The same access from a `_physics_process` function produces the right value.

This is problematic when duplicating and reparenting an object since it can end up at a different position that the original one.

In my game with results in the following:
![position_error](https://preview.redd.it/z0wqav7spzv51.png?width=1920&format=png&auto=webp&s=0a537c3a7f590bdb6c95c69acb0d34a7855857b0)
where the arrow on the left is a duplicate of the one on the right. The original arrow wiggles a bit due to the player idle motion (hidden here for visibility) but never goes to where the duplicate ends up being, so it's not a timing issue.

**Steps to reproduce:**
I can't share my whole game project and I'm having a hard time reproducing it in a new one.

In the meantime, here is the hierarchy I have in my game:
![Screenshot from 2020-10-30 08-28-31](https://user-images.githubusercontent.com/14923636/97673208-ae2ea180-1a8b-11eb-8ac7-b1434e509815.png)
and the highlighted `Arrow` node is the one I'm reading the `global_transform` of.
My intuition goes to an issue with the skeleton animation and/or bone attachment parts since otherwise the problem would have been noticed a long time ago I guess.

**Minimal reproduction project:**
WIP

**Comment by Calinou** [comment]
@BenjaminNavarro Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by BenjaminNavarro** [comment]
Sorry, I couldn't find the time to make a minimal reproduction project yet but the problem showed up in a different part of my game.

This means that it's not related to the skeleton part as I initially guessed and that it should be easier for me to reproduce it. I'll try to upload a test project as soon as possible

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
