### ISSUE TITLE
BoneAttachment is gone with editable children and tscn format

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4320]
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
``BoneAttachment`` node is gone when using ``Editable children`` and ``tscn`` format.
When reopen ``tscn`` file, console says,
``
WARNING: SceneState::instance: Parent path 'Skeleton/Spatial' for node 'BoneAttachment' has vanished when instancing: 'res://test/test_bone_attach.tscn'.
``

It's fine with ``scn`` format.

**Steps to reproduce:**
![tscn_boneattachment](https://cloud.githubusercontent.com/assets/8281454/14535079/1f11aa0c-02a7-11e6-94f1-71b6e49cbdba.gif)

**Link to minimal example project** (optional but very welcome):

**Comment by slapin** [comment]
Don't use .tscn scenes with 3D, they do not work, which is pity. Try .scn format.

**Comment by akien-mga** [comment]
Well, they *should* work. If they don't it's a bug and has to be fixed.

**Comment by slapin** [comment]
@reduz said .tscn doesn't work for 3D, so I tend do believe him
regarding something not working.

**Comment by akien-mga** [comment]
That does not make it a feature. Either it's supported and should work, or it's not supported and should not be allowed when saving 3D scenes.

**Comment by slapin** [comment]
@akien-mga you're right of course, but currently the usage of .tscn for 3D is not recommended.

**Comment by volzhs** [comment]
similar issue is reported at http://www.godotengine.org/qa/3584/strange-warning-in-godot-console
I'm not quite sure but it seems like losing edit data when using tscn with 3d scene and editable children.

**Comment by reduz** [comment]
@slapin 

> @reduz said .tscn doesn't work for 3D

it's not that it doesn't work, it's mostly that saving geometryin .tscn will be huge and take a long time to load, but it should work

**Comment by slapin** [comment]
On Mon, Jun 20, 2016 at 10:28 PM, Juan Linietsky <notifications@github.com>
wrote:

> @slapin <https://github.com/slapin>
>
> @reduz <https://github.com/reduz> said .tscn doesn't work for 3D
>
> it's not that it doesn't work, it's mostly that saving geometryin .tscn
> will be huge and take a long time to load, but it should work
>
That is good to hear.

**Comment by TheoXD** [comment]
Good thing it's fixed, just stumbled across this issue and couldn't come around it xD
