### ISSUE TITLE
TileSet Navigation offset does not apply for Atlas tiles.

### ISSUE THREAD

**Issue by ejfudd** [godotengine/godot#43214]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10 19041.508

**Issue description:**
When Atlas tiles are specified in a TileSet, the navigation offset property is not being applied to the navigation polygon.  
For single tiles, the navigation offset is being applied to the navigation polygon.

**Steps to reproduce:**
Create a TileSet with tiles that have a non-zero texture offset.
Create Atlas tiles and add navigation polygons to those Atlas tiles.  
Match the Navigation Offset to the Texture Offset.
Create a Tilemap using the tiles in the tilset and run the project with show navigation enabled.
You will see that the navigation polygon does not align with the textures.

**Minimal reproduction project:**
[NavPolyOffset.zip](https://github.com/godotengine/godot/files/5466275/NavPolyOffset.zip)

Edit:
After digging a little bit further.  Starting at line 584 in tile_map.cpp:
```
			if (navigation) {
				Ref<NavigationPolygon> navpoly;
				Vector2 npoly_ofs;
				if (tile_set->tile_get_tile_mode(c.id) == TileSet::AUTO_TILE || tile_set->tile_get_tile_mode(c.id) == TileSet::ATLAS_TILE) {
					navpoly = tile_set->autotile_get_navigation_polygon(c.id, Vector2(c.autotile_coord_x, c.autotile_coord_y));
					npoly_ofs = Vector2();
				} else {
					navpoly = tile_set->tile_get_navigation_polygon(c.id);
					npoly_ofs = tile_set->tile_get_navigation_polygon_offset(c.id);
				}

				if (navpoly.is_valid()) {
					Transform2D xform;
					xform.set_origin(offset.floor() + q.pos);
					_fix_cell_transform(xform, c, npoly_ofs, s);
```

The variable npoly_ofs never gets set for Autotiles or Atlas tiles.

**Comment by akien-mga** [comment]
Fixed by #61822.
