### ISSUE TITLE
TileSet: It does not support all features Sprite (Bug)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#4321]
**Operating system or device:**
all

**Issue description** (what happened, and what was expected):
Property "Vframes", "Hframes", "Frame" not supported in the TileSet.
Instead, they must use the "region". But it is not always convenient.

It is desirable that the tiles can be created from any 2D objects. Let the solution of the tile that will be left for the developers. It would be more correct.

**Comment by eska014** [comment]
Very similar to #3637, let's use that issue
