### ISSUE TITLE
Array operator on nodes broken in some situations

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#43221]
**Godot version:** master @ 41f66761fd8e41760dbffce9b9a4a4d8ceb7af0b

**OS/device including version:** Ubuntu 20.04

**Issue description:**

The array operator for accessing node properties seems to be broken in some situations.

**Steps to reproduce:**

This code works in 3.2:

```gdscript
extends Node

func _ready():
	print(self["name"])
	self["name"] = "Changed"
	print(self["name"])
```

The same code is broken in master, here's some test code with comments:

```gdscript
extends Node

func _ready():
	#print(self["name"]) # This doesn't work, yet works in 3.2.
	print(self.get("name")) # But this works in its place.
	
	#self["name"] = "Changed" # This doesn't work, yet works in 3.2.
	self.set("name", "Changed") # But this works in its place.
	
	#print(self["name"]) # This doesn't work, yet works in 3.2.
	print(self.get("name")) # But this works in its place.
	
	#var n = self # This makes the below lines fail.
	var n: Node = self # But this works in its place.
	print(n["name"])
	n["name"] = "Changed2"
	print(n["name"])
```

Additionally, I've run into situations where the array operator works for setting but not getting (works in 3.2):

```gdscript
@onready var animation_tree = $AnimationTree

# lots of code...

#var blend_pos = animation_tree["parameters/aim/blend_position"] # Causes the += 5 line to fail.
var blend_pos = animation_tree.get("parameters/aim/blend_position") # But this works in its place.
blend_pos.x += 5 # Would fail with 'Invalid get index "x" on base Nil'
animation_tree["parameters/aim/blend_position"] = blend_pos # Works fine.
```

**Minimal reproduction project:**

This ZIP contains two projects, for 3.2 and 4.0: [ArrayOperatorTests.zip](https://github.com/godotengine/godot/files/5467439/ArrayOperatorTests.zip)

**Comment by lyuma** [comment]
Bug is still present on latest master build (85186bc)

If I uncomment the lines in Test.gd, I get this error for each one:
```
  modules\gdscript\gdscript.cpp:840 - Method/function failed. Returning: ERR_PARSE_ERROR
```
