### ISSUE TITLE
Tilemap collisions not updated during _fixed_process

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4322]
Tested on Godot 2.0.2, Windows 7 64 bits:

I have a tilemap where tiles have collision shapes. I use them to perform raycasts and intersections.

To develop a new feature, I need to modify the tilemap during the _fixed_process() callback.
But when I cast rays to new tiles, they pass through as if there were no tiles Oo

Then I realized the tiles become "collisionnable" ONE frame AFTER.
This is a big problem in my game, because working around that means I have to introduce a special case for every collision query I make... and this is going to produce a lot of potential bugs with all the logic I already have working.

Is this known to be a design constraint, or is it a bug?

**Comment by eska014** [comment]
Raycasts and intersection tests query the "space state", which is calculated just before `_fixed_process`. You'll have to change collision bodies/shapes before `_fixed_process`

**Comment by Zylann** [comment]
Problem is... I already need to query the space state to know if I should modify the tiles.

**Comment by akien-mga** [comment]
I think that's normal behaviour, the physics state is immutable during a given frame, and will be updated for the next frame. So if you modify and query in the same frame, you'll still query the data from the past frame.

I asked @reduz about it, he said "we could add a function to update the modified tileset, worst case, but current approach is best because it's more efficient (everything changed is updated at once later)"

So I guess it's a wontfix, unless you really really need this feature and then there could be a TileSet.force_update() method or something.

**Comment by Zylann** [comment]
I have a working workaround (so far) for now, but I still wonder why it's a problem because:

1) I'm doing this in `_fixed_process` so physics is in sync
2) It's a collision/intersection check, there is no physics or timed dynamics involved. In fact, my game doesn't use physics at all apart from raycasts and intersections^^

I would understand such a delay in a multithread scenario, but my game is far from using it.

**Comment by akien-mga** [comment]
Well as @eska014 pointed out, the space state is calculated just before `_fixed_process`, so:
- Frame 1:
  - SpaceState 1:
  - _fixed_process
    - modifies TileMap (thus modifying what the physics server used to calculate the SpaceState)
    - queries the space state: gets values from SpaceState 1
- Frame 2:
  - SpaceState 2 (takes into account modifications of past frame, calculates physics)
  - _fixed_process
    - ...
    - queries the space state: gets values from SpaceState 2, thus matching changes in Frame 1

**Comment by akien-mga** [comment]
Or actually the physics step seems to happen just *after* `_fixed_process`, but that doesn't change much; the `Physics2DDirectSpaceState` used in `_fixed_process` still represents an "old" state after you've changed physics-related things in `_fixed_process`.

**Comment by Zylann** [comment]
> as @eska014 pointed out, the space state is calculated just before _fixed_process
> the physics step seems to happen just after _fixed_process

That's my point^^
In my game, physics has nothing to step (no rigidbody, no kinematic).

**Comment by akien-mga** [comment]
I think in the end it's a design constraint and we have to live with it :)

As @reduz mentioned it could be possible to add a function to update the modified tileset/recompute the physics state, but it's probably best to come up with design that work with the fact that modifying collision shapes is basically queuing them for modification in the next physics step.

**Comment by akien-mga** [comment]
I propose to close the issue because Huge Backlog™, but if you still strong feel that something should be done to improve the situation here we can reopen it :)
