### ISSUE TITLE
When cleared, Variant destroys the Reference it had assigned if it was the only ref. count incrementer

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#43225]
**Godot version:**
3.2.4-beta, 4.0

**OS/device including version:**
N/A

**Issue description:**
The `Variant(Object *)` constructor checks whether the passed object is a `Reference` to manage its reference count.

The problem comes when the `Reference` has not yet gotten its reference count initialized and so its the `Variant` it's assigned to the one doing that, because that will cause the object to be freed when the `Variant` is cleared/destroyed/reassigned.

One example of this happening is the `self` variable in `GDScriptFunction::call()` when called during the duplication of a resource. The moment the `script` property is copied and such script is called on a still-unreferenced `Reference` which is the duplicate `Resource` you get a crash.

Probably there are other cases across the whole codebase.

**Steps to reproduce:**
Consider this sequence:
1. Some `Resource`-derived class is instantiated: `SomeResource *res = memnew(res)`.
2. A `Variant` is initialized with it: `Variant v(res);`. `res`'s ref. count becomes 1.
3. The `Variant` is cleared: `v.clear()` . `res`'s ref. count becomes 0 then it's released.

**Minimal reproduction project:**
Not needed.

***Possible approaches to fixing:***
I can think of some ways to fix this:

1. Find and fix every case of a `Reference` whose ref. count is not yet initialized being assigned to a `Variant`, by managing the life cycle of the former explicitly via `Ref<>`. 
2. Modify `Variant` so it doesn't deal with the reference count of a `Reference` if it's not already initialized when it's assigned.
3. Modify `Variant` so it doesn't deal with the reference count of a `Reference` it's assigned via the `Object *` constructor. (Adding this here for the sake of the brainstorm, but that would only be possible in 3.2, where there is the `Variant(RefPtr &)` constructor that could have the alternative ref. counting semantics.)

**Comment by reduz** [comment]
This is intended and the correct behavior (at least in 4.0 unless I am missing something) it requires no change.

**Comment by reduz** [comment]
Checked and it should be the same in 3.2. This is fully intended, it's not a bug or a problem.

**Comment by reduz** [comment]
The crash you get in 3.x I think is related to something else, because in Godot 3.x, scripts reference themselves. In 4.0 you should not get this crash because this behavior has been fixed.

**Comment by RandomShaper** [comment]
I backported vnen's change so scripts now provide the self reference the same way as in 4.0.

The crash was discovered in 3.2. I tried the MRP on 4.0 and it crashed too. Try the MRP provided at https://github.com/godotengine/godot/pull/43049#issuecomment-717559858.

If `Variant` is designed to work that way, then I guess we should apply solution 1).

**Comment by RandomShaper** [comment]
Here's my suggestion:

- For 3.2, make `Variant` not do any kind of ref.-counting on `References` passed as `Object *`. That will fix the existing cases where a `Reference` is not put in a `Ref` before assigning it to a `Variant` by avoiding the early destruct problem. This won't affect GDScript, only the C++ side. I have thought of a way to implement it without having to make `Variant` bigger.
- For 4.0 it may be better to just try to find and fix all the cases where the illegal-by-design way is used. We already have spotted a couple of cases, and the rest may very well be found during the pre-alpha and alpha stages as people start to try to do stuff with the engine.

**Comment by RandomShaper** [comment]
It seems we have indeed chosen the option to fix the individual cases where `Variant` is wrongly used, rather than patching it, even in 3.2.

So this is no longer an issue by iself.

See #43610 for further info.
