### ISSUE TITLE
The editor is constantly redrawing in the 3D tab, even in an empty project

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#43228]
Godot 3.2.4 beta1
Windows 10 64 bits

I noticed Godot keeps rendering every frame when the 3D tab is selected, even in an empty project. You can notice it with the CPU/GPU usage and the update spinner rotating constantly.
This did not happen in Godot 3.2.3.

**Comment by Calinou** [comment]
I can confirm this with 3.2.4beta1 on Linux.

**Comment by lawnjelly** [comment]
Yes I am looking at this in the debugger now. Every NOTIFICATION_PROCESS the spatial_editor_plugin.cpp is calling set_use_fxaa which is causing a redraw_request().

The same appears to be happening with viewport_set_use_debanding, and a few other things, although they may not be the cause.

**Comment by akien-mga** [comment]
Fixed by #43272.
