### ISSUE TITLE
Vulkan crash on startup on Debian Buster (too old Mesa drivers)

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot#43231]
**Godot version:** master, after #38410 closed
**OS/device including version:** Debian Buster amd64, Radeon RX550 with radeon driver (and MATE)

**Issue description:**
Editor does not launch, crashes instead:
```
Godot Engine v4.0.dev.custom_build.67f64ef4f - https://godotengine.org
ERROR: Can't find layer: VK_LAYER_KHRONOS_validation
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:157)
ERROR: Can't find layer: VK_LAYER_LUNARG_standard_validation
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:157)
ERROR: Can't find layer: VK_LAYER_GOOGLE_threading
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:157)
DisplayServer::_create_window 0 want rect: 448, 300, 1024, 600 got rect 448, 300, 1024, 600
DisplayServer::_window_changed: 0 rect: 452, 326, 1024, 600
 
DisplayServer::_create_window 1 want rect: 709, 551, 501, 97 got rect 709, 551, 501, 97
LLVM ERROR: Cannot select: 0x93e16e8: i16,ch = load<(load 1 from %ir.50 + 1, addrspace 6), anyext from i8> 0x86884e8, 0x93e7ed0, undef:i32
  0x93e7ed0: i32 = add 0x93e13a8, Constant:i32<25>
    0x93e13a8: i32,ch = CopyFromReg 0x86884e8, Register:i32 %3
      0x93e1340: i32 = Register %3
    0x93e7e68: i32 = Constant<25>
  0x93e14e0: i32 = undef
In function: main
```

**Steps to reproduce:**
- Build on Debian Buster with: scons -j3 platform=linuxbsd target=release_debug use_llvm=yes use_lld=yes
- Launch on Debian Buster

Now that #38410 is closed, we can be certain that this is a different problem.

This same build works fine on Kubuntu Bionic and Kubuntu Focal with radeon and amdgpu drivers (on an R9 290), so the problem is most likely not with building, but with running.

**Comment by dark-penguin** [comment]
Since it's Debian, it's probably about something being too old. Upgrading libvulkan to backports did not help, so maybe old Xorg? Running it in an Ubuntu container on a Debian host did not work, and in this case, the only part from Debian was Xorg (if my understanding is correct).

If that's the case, would it be worth the trouble to support an old Xorg?

**Comment by Calinou** [comment]
> so maybe old Xorg? 

The last stable Xorg release is quite old, so I think most distributions are running the same version by now, no?

**Comment by dark-penguin** [comment]
Debian Buster Xorg version: 1:7.7+19
Ubuntu Focal Xorg version: 1:7.7+19ubuntu14
Hmmmmm, yes, seems like the last Xorg update was in Debian Stretch - and it was very memorable to me, because it caused the fglrx driver to no longer work, and made all my pre-GCN Radeons nearly useless. Unless they've fixed something on the Ubuntu side, it shouldn't be Xorg then. Or even if it is, I guess supporting the upstream version is important.

**Comment by akien-mga** [comment]
What Mesa version do you have, and is there a newer one in backports?

**Comment by dark-penguin** [comment]
mesa is version 18.3.6-2+deb10u1, and there is no backports version.

**Comment by akien-mga** [comment]
Yeah that's fairly old, those were early days for Vulkan still. Mesa drivers were likely quite buggy at that time. Not sure we'll be able to support Debian Buster with Godot 4, at least until OpenGL support is reimplemented.

Ubuntu works as it's based off Debian Sid and thus has much newer packages.

**Comment by Grant1219** [comment]
I am having the exact same problem running Debian buster, i3wm, Radeon RX580:
```> ./bin/godot.linuxbsd.tools.64.llvm -v -w -e
Godot Engine v4.0.dev.custom_build.ad0f1c667 - https://godotengine.org
Using ICU / HarfBuzz / Graphite text server...
XInput: Refreshing devices.
XInput: No touch devices found.
DisplayServer::_create_window 0 want rect: 768, 420, 1024, 600 got rect 768, 420, 1024, 600
XcursorGetTheme could not get cursor theme
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
 
CORE API HASH: 6887144409508696913
EDITOR API HASH: 5764121762446788548
EditorSettings: Load OK!
Loaded builtin certs
EditorSettings: Save OK!
DisplayServer::_create_window 1 want rect: 1030, 670, 500, 100 got rect 1030, 670, 500, 100
DisplayServer::_window_changed: 0 rect: 1243, 685, 75, 50
LLVM ERROR: Cannot select: 0xd2d5c98: i16,ch = load<(load 1 from %ir.50 + 1, addrspace 6), anyext from i8> 0xcef8118, 0xd2dc480, undef:i32
  0xd2dc480: i32 = add 0xd2d5958, Constant:i32<25>
    0xd2d5958: i32,ch = CopyFromReg 0xcef8118, Register:i32 %3
      0xd2d58f0: i32 = Register %3
    0xd2dc418: i32 = Constant<25>
  0xd2d5a90: i32 = undef
In function: main
```

I was planning on upgrading my Debian install to `bullseye` soon, so I can report back if that solves the issue.

**Comment by Grant1219** [comment]
I confirmed that upgrading from `buster` to `bullseye` fixes the problem... unfortunately considering the age of the `buster` it might just be old Vulkan drivers? Is this worth pursuing now that `bullseye` is reaching the soft/hard freeze period?

**Comment by akien-mga** [comment]
> I confirmed that upgrading from `buster` to `bullseye` fixes the problem... unfortunately considering the age of the `buster` it might just be old Vulkan drivers? Is this worth pursuing now that `bullseye` is reaching the soft/hard freeze period?

Yeah Mesa drivers on Buster are fairly old, and Vulkan was still a fast moving target back then: https://packages.debian.org/buster/mesa-vulkan-drivers

I don't think we'll be able to fix this, but we can keep the issue open for now as others are likely to run into it. Eventually we might need to clarify what driver versions are required to use Vulkan (and ideally blacklist the ones we know don't work to avoid crashing but falling back to GLES3 - once implemented).

**Comment by dark-penguin** [comment]
I agree that is does not make sense to support Buster. So we can close this.

If anyone still wants to get it working, I've managed to do that. You have to upgrade mesa and most likely xserver-xorg-video-amdgpu (for Radeon). Backporting the current version from Bullseye is not easy, so I've installed packages from this repository, and it helped:
http://download.opensuse.org/repositories/home:/stevenpusser:/new-hardware-support-buster/Debian_10/

**Comment by Calinou** [comment]
Closing per the above comment.
