### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by motaj01** [godotengine/godot#43263]
No open issues with this error

**Godot version:**

3.2.2stable

**OS/device including version:**

Android Huawei P30 Lite New Edition

**Issue description:**

When a node queue_free(), it should continue the game but crash. Tested in other mobile devices and didn't crash.

**Steps to reproduce:**
While playing during a node "died" queue_free() the app crash. I attached the log of fatal crash it starts in line 153:

11-01 13:30:34.136  2733  2820 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6769642e6d6f93 in tid 2820 (GLThread 40516), pid 2733 (.earthtothemoon)

**Minimal reproduction project:**

[logcat.txt](https://github.com/godotengine/godot/files/5470941/logcat.txt)

**Comment by Calinou** [comment]
@motaj01 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

We can't do anything with *just* the crash message, I'm afraid.

**Comment by motaj01** [comment]
[example.gd.txt](https://github.com/godotengine/godot/files/5471250/example.gd.txt)


Hi, attached the complete of the node in gd where I think the crash happens. It happens when I call function dead() bellow, the no desapear and then crash but only on Huawei on other device like samsung / lenovo it works.. If need more code please let me know.
func _on_shootBirdsTimer_timeout():
	if angryLevel == 1:
		_getRedBird(-15,10)
		_getYellowBird(15,10)
	if angryLevel == 2:
		_getPinguin(-10,10)
		_getPinguin(10,10)
	if angryLevel >= 3:
		_getRedBird(-15,10)
		_getPinguin(0,10)
		_getYellowBird(15,10)
		_getRedBird(-30,150)
		_getPinguin(0,30)
		_getYellowBird(30,150)
		dead()

**Comment by Calinou** [comment]
Try using `remove_child()` instead of `queue_free()` and see what happens. Also try `free()` instead of `queue_free()`.

**Comment by motaj01** [comment]
Hi, when I try to use free() instead queue_free give an error:

func dead():
	shootBirdsTimer.stop()
	#queue_free()
	free()

E 0:00:12.579   call: Object is locked and can't be freed.
  <C++ Error>   Method failed. Returning: Variant()
  <C++ Source>  core/object.cpp:888 @ call()
  <Stack Trace> duck.gd:131 @ dead()
                duck.gd:111 @ _on_shootBirdsTimer_timeout()

But I check again all places where I have validations about this and I realize that I have a condition inside a timer that checks if the instance of that node is null -> if  **mynode != null** do something else stop timer

This works for samsung and lenovo but huawei crash. I try and put an extra condition as bool

if  **mynode != null** and **!enemyNodeIsDead** do something else stop timer. With this it solved the problem but really strange because the bug was only on Huawei device.
