### ISSUE TITLE
[Bug: 3.2.3] Navigation2D on TileMap doesn't work with Half Offset (test scene included).

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#43274]
**Godot version:**
3.2.3.stable.mono.official

**OS/device including version:**
Win 10

**Issue description:**
Navigation2D with a TileMap - half offset X (either positive or negative) - visually (debug Visible Navigation) everything looks ok, in code nav polygon seems to be placed correctly as well (inside TileSet).
If you try to move (with mouse left click) the sprite around through GetSimplePath the path is obtained only for tiles which are in the same lane (understand horizontally = X axis) but nothing happens when you try to move the sprite to other lanes vertically - Y axis (tiles in lanes above or below).

If you turn off Half Offset everything works smoothly so I assume the navigation polygons are set properly and the tile map as well.

(The same happens for Half Offset Y but this time no navigation happens for movement in X direction)

**Expected result**
Would be a sprite moving all across the TileMap.

*(I tested this in previous stable version - not mono - and the problem was the same)*
*(I tried to get other opinions but so far everyone seems to be puzzled why it doesn't work)*
*(TileSet is set with Single Tile but the same happens with Autotile and Atlas)*

**Steps to reproduce:**
1. Create Navigaion2D node
2. Add TileMap as Navitaion2D node's child
3. Use GetSimplePath in movement code (test scene includes all this)
4. Set base tile (for example icon.png) in TileMap in a new TileSet (single tile for example)
5. Check movement and result from Path above (step 3) with and without Half Offset X (or Y).

*(Test scene includes everything already prepared so the lines below apply only to the test scene)*

*(In the test scene there are 2 Navigation2D nodes (Navigation2D and Navigation2D2).
Navigation2D has half offset disabled.
Navigation2D2 has half offset X enabled.)*

1. Turn on visibility of Navigation2D and turn off visibility of Navigation2D2, play the scene, try to move the sprite around with left mouse click (pressing). Sprite moves around without problems.

2. Turn off visibility of Navigation2D and turn on visibility of Navigation2D2, play the scene, try to move the sprite around with left mouse click (pressing). Sprite moves only in the lane it already is in and only horizontally.

**Minimal reproduction project:**
https://drive.google.com/file/d/14AynEyse6UUcA-rDBTqL4DNN56vstGQK/view?usp=sharing
(I'm using mono version so zip file is larger than github's minimum limit so I uploaded a simple test scene to my google drive and left it there)

**Notes:**
There seem to be other people having problems which seem to be similar in nature if not the same:
https://github.com/godotengine/godot/issues/43214
https://godotengine.org/qa/81320/tilemap-navigation2d-not-working-in-half-offset?show=81320#q81320

Sorry I don't think I can add proper labels to this issue (bug, navigation2D, ...?).

**Comment by viksl** [comment]
Tested a second scene now, though I'm not really sure how much related it is so I'll leave it as a separate comment not to make the original report to bloated.

If you create tiles in a separate file:
Sprite + Navigation polygon instance
Then go through menu - Convert To - TileSet (save as tres).

Then use this new tileset in the tilemap and as long as you don't make any changes through tileset editor you can set half offset and make the navigation work.
(navigation polygons inside tileset editor through this method is displayed completely off basically in top left corner but I don't know if the editor should work with this or not and I don't know what exactly Convert to - TIleset those I'm not that kind of programmer unfortunately to figure it out from godot's side :?)

Unfortunately you lose options such as Autotile and Atlas from the tileset editor. I want to investigate the options a bit further with some simple code built test scenes and see if that works or not (I already tried one and it did not work but I want to give it a bit more).

I'll try to post another test scene at some point. Probably just with already prepared tileset.

**Comment by Zireael07** [comment]
> EDIT: I'm closing this issue as it turns out it's probably not a bug. Turns out I and no one else I discussed this with knew that navigation polygons have to have a point in the polygon for every point it's neighbouring with. Basically for no offset with square tile you need 4 points square navigation polygon, for offset in one axis with square tile you need a 6 point navigation polygon square, for offset in both axes for square tiles you need 8 points for navigation polygon square. I haven't seen this in docs so far either but I'll need too go through docs more thoroughly. With this it doesn't seem to be a bug, maybe just an entry in docs if there's not one somewhere already.

Yep, not a bug per se, rather a fairly annoying limitation.
