### ISSUE TITLE
Parser Error: The function 'change_scene()' returns a value, but this value is never used. (warning treated as error)

### ISSUE THREAD

**Issue by mhona** [godotengine/godot#43287]
extends Control

func _ready():
	$"menu/centerrow/buttons/new game button".grab_focus()
	for button in $menu/centerrow/buttons.get_children():
		button.connect("pressed", self, "_on_Button_pressed", [button.scene_to_load])

func _on_Button_pressed(scene_to_load):
	get_tree().change_scene(scene_to_load)

**Comment by mhona** [comment]
it kkept saying Parser Error: The function 'change_scene()' returns a value, but this value is never used. (warning treated as error)

**Comment by qarmin** [comment]
This means that `change_scene` returns Ok if scene changes properly and Error if there was an error(e.g. invalid scene name).
You can disable warning in project settings.

Next time please fill all required fields(version of Godot etc.).
This is engine issue tracker, for help you should check this sites - https://godotengine.org/community
