### ISSUE TITLE
Build error with bad solution when switching between master and 3.2 branch

### ISSUE THREAD

**Issue by gvekan** [godotengine/godot#43299]
**Godot version:**

Builds from source: 4.0 (`master`) https://github.com/godotengine/godot/pull/39635 and 3.2 (`3.2`) https://github.com/godotengine/godot/pull/43293

**OS/device including version:**

Windows 10

**Issue description:**

When working on multiple issues, some specific to the `3.2` version and some to the `master`, I have to deal with this issue every time: https://github.com/godotengine/godot/issues/38773 and https://github.com/godotengine/godot/issues/39789. To clean the folders is not an option because of compile time. The solution right now is to remove `default_controller_mappings.gen.cpp `every time I switch from `3.2` to `master`. 
I would like a better solution. Maybe some change with: https://github.com/godotengine/godot/blob/afef8e30eaaf99af866b21cd54c946ab45532cd4/main/SCsub#L11
that would not include the file. 
I can see this issue being more relevant in the future if more generated `.cpp`-files are removed or added. I'm compiling the `3.2` branch with `extra_suffix` flag so that the versions don't interfere with each other. It is just the manual labor of deleting the file every time that makes this situation tedious.

**Steps to reproduce:**
Compile Godot on the 3.2 branch with `scons ... extra_suffix=3.2`, switch to master branch and compile Godot again without `extra_suffix`. The compilation fails and you have to fix it as described in the **Issue description**. Repeat this until you also find it tedious.

**Comment by akien-mga** [comment]
Most of us use separation got clones for 3.2 and master, that's more reliable and convenient than using `extra_suffix` and dealing with differences in generated files.

**Comment by gvekan** [comment]
@akien-mga Okay, then I know what everyone else is doing. I've also used that approach but for some reason I wanted to try to avoid multiple clones. But if most other use it, it's fine by me.
