### ISSUE TITLE
Stay safe Reduz

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4330]
Okay, I know this isn't standard fare for Godot's issue tracker, but a comment from Reduz late last month indicated that he is currently in Japan (the country which just saw two powerful earthquakes hit in the past couple of days).
http://www.cnn.com/2016/04/15/asia/japan-earthquake/index.html

I sure hope he's okay (either he felt the shaking and is unharmed or he was not in the region at that time). The Godot project will always need his skill, insight, and direction.

Stay safe.

**Comment by neikeq** [comment]
Last time I seen him on IRC he was already in Los Angeles.

**Comment by slapin** [comment]
That is good
@rediz how are you?

**Comment by neikeq** [comment]
He is already back:
```
[23:25:37] <reduz> Finally back home!
[01:13:07] <reduz> super tired from the plane trip, and will most likely rest this weekend so I adjust the jet lack, will begin doing Godot stuff again on Monday
```
