### ISSUE TITLE
Launcher text fields stuck on previous character

### ISSUE THREAD

**Issue by Go-Duck** [godotengine/godot#43304]
Godot version:
v3.2.3.stable.mono.official

OS/device including version:
Windows 10.0.18363

Issue description:
I tried to make a new project, but when I tried naming it, it was one character behind. I was a little confused, I restarted Godot, I also restarted my computer, but nothing worked, even on a new installation of Godot. (Only in the launcher.)

Steps to reproduce:
Open the launcher, then try typing on any of the text fields.

Minimal reproduction project:
*see description

**Comment by Go-Duck** [comment]
This is a common bug on their troubleshooting page. I'm closing the issue now.

**Comment by Calinou** [comment]
For reference, this is a duplicate of https://github.com/godotengine/godot/issues/23069.
