### ISSUE TITLE
Godot needs 6 ico sizes for windows export to not include the godot icon

### ISSUE THREAD

**Issue by viindicater** [godotengine/godot#43300]
**Godot version: 3.2.1 (But I assume persists in 3.2.3, according to release notes, has not been addressed yet)**

**OS/device including version: Windows 64-Bit**

**Issue description:**
When less than 6 image sizes in the ico file, godot will include (6 - number of sizes) godot icons in the ico file 

**Steps to reproduce:**
1. Export an exe with less than 6 sizes in the ico file.
2. Export an exe with 6 or more sizes in the ico file.
3. Compare and observe the godot icon is included in the first one, and appears in some cases in explorer (such as small icons view in explorer)

**(For 3 sizes, the first 3 are the icon it's supposed to be, and the last 3 are godot icons.)**
![image](https://user-images.githubusercontent.com/60835390/98041608-37c5d280-1df0-11eb-8c26-067b7e735123.png)

**Example of its effects**
![image](https://user-images.githubusercontent.com/60835390/98041775-79567d80-1df0-11eb-9c57-ede8b7dbba43.png)

**Things to note:**
- Windows does not require 6 ico sizes, I've seen other exe files with less than 6
- Godot includes godot icons of sizes that may already be in the ico file you have, such as 16x16 

**Minimal reproduction project: http://www.mediafire.com/file/rukl6ua303q7fdl/BubbleShootericoSizesTest.zip/file [Due to size limit here, had to upload it elsewhere]**

**Comment by pycbouh** [comment]
> and appears in some cases in explorer (such as small icons view in explorer)

Which is why [it is recommended](https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html) to provide all 6 of them.

**Comment by viindicater** [comment]
> > and appears in some cases in explorer (such as small icons view in explorer)
> 
> Which is why [it is recommended](https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html) to provide all 6 of them.

Ok but you're ignoring the facts I noted: 1) 6 sizes are not a requirement in exe files 2) It's the godot icon that shows in such cases.

**Comment by pycbouh** [comment]
I'm not ignoring, I'm saying there are cases for those sizes so you better use them anyway. And yes, Godot icon is embedded in the export templates.

**Comment by viindicater** [comment]
> I'm not ignoring, I'm saying there are cases for those sizes so you better use them anyway. And yes, Godot icon is embedded in the export templates.

This is getting off-topic, the issue remains and what you've said so far doesn't change anything or go into the issue in hand. I don't need to hear suggestions or related but irrelevant info.

Windows can deal with those cases automatically, and there's no reason godot icon should be included, even if there was only one size in the ico.

**Comment by pycbouh** [comment]
> I don't need to hear suggestions or related but irrelevant info.

This is not irrelevant. This behavior is by design and is documented. The export templates are generated with the default icon. You can build your own templates without it for that matter. For the best user experience it is advised to support all 6 possible resolutions. It doesn't matter if Windows can approximate the icon for you.

**Comment by viindicater** [comment]
> > I don't need to hear suggestions or related but irrelevant info.
> 
> This is not irrelevant. What you report is not a bug. This behavior is by design and is documented. The export templates are generated with the default icon. You can build your own templates without it for that matter. For the best user experience it is advised to support all 6 possible resolutions. It doesn't matter if Windows can approximate the icon for you.

This behaviour is neither document (if you persist to claim this, then show me where in the docs it says it'll add in icons if you put less than 6 sizes), or intuitive/expected. Godot includes ALREADY INCLUDED sizes of the godot icon in the ico. So it's not as if it fills the missing sizes for 'best user experience'. Even if it's "advised" , it shouldn't have this unexpected behaviour if not done. 6 sizes are just not a requirement for exe files.

Furthermore, of course it matters if windows can approximate it for you, this further solidifies the point that it is not a requirement and should behave as expected when less than 6 sizes (i.e. no godot icons included).

**Comment by pycbouh** [comment]
> Godot can include ALREADY INCLUDED sizes of the godot icon in the ico.

Godot doesn't do anything by itself. That's what `rcedit` does, if you follow that path. As per the article, you are expected to provide all 6 sizes so that `rcedit` can replace all 6 sizes of the default icon. If you don't some sizes may remain. Default icon is there so that users don't have to make an icon immediately. I'm sure you understand why this is important.

If the way `rcedit` works doesn't satisfy you, you can already fix it by compiling the export templates with your own icon included in whatever sizes you want. Or generate all 6 images in your icon for the `rcedit` to work correctly, it's extremely easy.

**Comment by viindicater** [comment]
Godot doesn't do anything by itself. That's what `rcedit` does, if you follow that path. As per the article, you are expected to provide all 6 sizes so that `rcedit` can replace all 6 sizes of the default icon. If you don't some sizes may remain. Default icon is there so that users don't have to make an icon immediately. I'm sure you understand why this is important.

rcedit is just a tool that can work however it's commanded, and should be able to just replace the icon, is what it seems
![image](https://user-images.githubusercontent.com/60835390/98051379-c000a380-1e01-11eb-9bd3-ce7590a4f9a6.png)
so I suspect the issue here is still tied to godot and not rcedit itself (unless someone else can confirm).

**Comment by pycbouh** [comment]
For the record, this exact argument is in fact used:

https://github.com/godotengine/godot/blob/afef8e30eaaf99af866b21cd54c946ab45532cd4/platform/windows/export/export.cpp#L137-L140

**Comment by viindicater** [comment]
> For the record, this exact argument is in fact used:
> 
> https://github.com/godotengine/godot/blob/afef8e30eaaf99af866b21cd54c946ab45532cd4/platform/windows/export/export.cpp#L137-L140

You are correct, I've also tested using rcedit manually and same results, thanks.
