### ISSUE TITLE
using gltf2.0 export from blender, lights are converted to spatial nodes (not exporting as lights)

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot#43313]
Latest Godot 3.2.3

macOS High Sierra 10.13.6

**Issue description:**

when exporting gltf2.0 files from Blender, no lights are exported to Godot. The objects do appear however as Spatial nodes.
The godot manual implies lights are supposed to be imported suggesting this is a bug:

"Deleting nodes that are not used in the game engine (like specific lights used for modelling)."
https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_scenes.html

EDIT: 
Confirmed that gltf2.0 does support lights by 2018:
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual

checked this model viewer online:
https://gltf-viewer.donmccurdy.com/
could not see my lights either

**Comment by Calinou** [comment]
@RichardEllicott Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by RichardEllicott** [comment]
okay the blend file that i export in Blender 2.83.7 the resulting gltf2.0 file

[light_export_issue.blend.zip](https://github.com/godotengine/godot/files/5490538/light_export_issue.blend.zip)

[light_export_issue.NORMALSETTINGS.glb.zip](https://github.com/godotengine/godot/files/5490541/light_export_issue.NORMALSETTINGS.glb.zip)

**Comment by RichardEllicott** [comment]
okay sorry, i must close this issue!

i was setting the options wrong, but they are slightly confusing. You have to check "punctual lights" when you export with gltf2.0

thanks for your attention, i'm glad this works!
