### ISSUE TITLE
The `--doctool` command generates random default property values in classes such as `RandomNumberGenerator`

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#43317]
**Godot version:**
3.2.4 beta

**OS/device including version:**
Windows 10

**Issue description:**
I've stumbled upon an issue with `--doctool` if `RandomNumberGenerator.randomize()` is called automatically in derived classes, as seen in goostengine/goost#35. This also means that derived classes will display parent class properties as "overridden"...

![goost_property_random](https://user-images.githubusercontent.com/17108460/98169602-3d591080-1ef5-11eb-8547-fbd418c5cc1e.png)

I haven't found a way to prevent this, and running `--doctool` would create unnecessary diffs in VCS. Perhaps adding some kind of property usage hint to prevent the `--doctool` generating "random default" values for those properties like `seed` would be enough to configure this per-property, like `PROPERTY_USAGE_NON_DETERMINISTIC`.

See also godotengine/godot-proposals#1774. The proposal is about randomizing the global instance so no properties are exposed in GDScript like that and this currently only applies to `RandomNumberGenerator`, but it's still an issue for module developers.

The issue is similar to #30038.

**Steps to reproduce:**
1. Compile goostengine/goost#35.
2. Run `--doctool`, this will change those `*.xml` files every time.

**Comment by akien-mga** [comment]
You can use `ADD_PROPERTY_DEFAULT` to force a fixed default value for documentation purposes.

**Comment by akien-mga** [comment]
Ah it was not clear from the report but I see that `RandomNumberGenerator` does have a `seed` property which can change value if `randomize()` was called (it isn't currently, so it doesn't change value). I'll hide it.

**Comment by Xrayez** [comment]
Thanks, this works!

Another issue still persists as described godotengine/godot-proposals#1777, but that's more like a feature request now.

> Is there a specific reason why you're using properties to get randomized values, instead of `get_` methods? That seems pretty non-intuitive from a API user point of view.

- Not as verbose as corresponding `get_` methods.
- Intuitive if you do write it in code: `Random.number`, `Random.color`, `Random2D.direction` etc. It's no different than a getter without a setter (read-only). The only thing which makes it unintuitive is the fact that the documentation shows the default values for those kind of properties in the first place.
- This is what Unity [Random](https://docs.unity3d.com/ScriptReference/Random.html) API does for some properties.
