### ISSUE TITLE
Vertical line when maximize

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#43315]
**Godot version:**

3.2.4 beta 1 mono 64

**OS/device including version:**

GTX 660
Win10 home 64

**Issue description:**

A vertical line appears when maximizing the window.

**Steps to reproduce:**
Maximize the window of the example included

**Minimal reproduction project:**
[tests.zip](https://github.com/godotengine/godot/files/5490222/tests.zip)
![Captura4](https://user-images.githubusercontent.com/19652075/98161789-9cf8f100-1ee0-11eb-8471-9f0b278aab10.PNG)

Video
https://youtu.be/4yQiVQYtIc0

**Comment by Lyx52** [comment]
For me its bit different
![Capture](https://user-images.githubusercontent.com/55701905/98164760-71303800-1eed-11eb-8712-e3f61e1485cc.PNG)

**Comment by Calinou** [comment]
@Torguen @Lyx52 Can you reproduce this when using the GLES2 renderer? Also, can you reproduce this in 3.2.3?

**Comment by Lyx52** [comment]
Im already using Godot 3.2.3 stable
![image](https://user-images.githubusercontent.com/55701905/98165672-f8ca7680-1eee-11eb-85a7-0ef8417fd2f8.png)
And in GLES2 it displays the same issue
![gles2_3_2_3](https://user-images.githubusercontent.com/55701905/98165729-0d0e7380-1eef-11eb-9630-6a4e64e1db2f.PNG)

**Comment by Torguen** [comment]
Yes with 3.2.4 with opengl 2
And yes with 3.2.3 stable with openGL 2 and 3

**Comment by Torguen** [comment]
In my case it was solved by activating pixel snap in the project options.
But maybe it shouldn't happen even if pixel snap is disabled

**Comment by Calinou** [comment]
You should generally always enable pixel snap when working on a game with a pixel art aesthetic. I'm not sure if we can fix this when filtering is disabled.

**Comment by akien-mga** [comment]
That's expected and it's exactly what the pixel snap option is used for. So enabling pixel snap is indeed the right fix for scaled pixel art.
