### ISSUE TITLE
Implement --no-window option for macOS and Linux

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#43325]
**Godot version:**
Godot Engine v3.2.3.stable.mono.official 

**OS/device including version:**
macOS Sierra Version 10.12.6

**Issue description:**
When i try to run a script via OS.execute() with option *--no-window* the window pops up.
Under Windows 10 it works as expected but under MacOs the window is not hidden

**Steps to reproduce:**
```
class_name GdUnitRunnerClient
extends SceneTree

func _initialize():
  pass
...
```
execution from a EditorPlugin context
```
var arguments := Array()
arguments.append("--no-window")
arguments.append("-d")
arguments.append("-s")
arguments.append("res://addons/gdUnit/src/core/GdUnitRunnerClient.gd")

var output = []
_current_runner_process_id = OS.execute(OS.get_executable_path(), arguments, false, output, true);
```

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
On Linux and macOS `--no-window` is not implemented, here's PR for it #42276.

**Comment by akien-mga** [comment]
```
$ godot --help | grep no-window
  --no-window                      Disable window creation (Windows only). Useful together with --script.
```

**Comment by MikeSchulze** [comment]
ok thanks for this feedback

**Comment by akien-mga** [comment]
Let's repurpose this as a feature request to implement `--no-window` for macOS and Linux I guess, which #42276 can close.

**Comment by Riteo** [comment]
Now that the resolving PR has been merged, can this issue be closed?
