### ISSUE TITLE
Script editor is very slow to select text

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4333]
**Operating system or device:** Windows 10 64-bit

**Issue description** (what happened, and what was expected):

When selecting text in the script editor, regardless of the script's length, selecting will be slow and stuttering. This occurs even if the editor is set to **Update Always**, rather than **Update Changes**. This behavior is mostly noticeable when selecting several lines of text.

This was tested on a self-compiled 32-bit build, as well as a 64-bit build from [fixnum.org](http://fixnum.org/godot/).

**Steps to reproduce:**

Select several lines of text in the script editor.

**Comment by Ace-Dragon** [comment]
Perhaps it could be due to compiler settings?

I use the daily builds from this site.
http://www.purpleorangegames.com/godot/

And selecting text for me is instant (I'm also on Windows10 64 bit).

**Comment by neikeq** [comment]
I only notice this when building with `DEBUG_ENABLED`, which is expected I guess.

**Comment by akien-mga** [comment]
I always build the editor is debug mode and never experienced this on Linux, 64-bit with GCC 5.3.1.

**Comment by vnen** [comment]
This seems to only happen in debug mode indeed, so it sounds like a non-issue to me (and it's not that slow, it just hangs for a second). Maybe it's worse with MinGW-compiled binaries?

**Comment by reduz** [comment]
i never experienced thism, neither on debug mode, and never on windows or
linux

**Comment by Calinou** [comment]
I can't experience this anymore, closing for now.
