### ISSUE TITLE
Tile atlas miscalculate spaced subtiles when using priority.

### ISSUE THREAD

**Issue by Zoomulator** [godotengine/godot#43331]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
Using the Tile Atlas subtile spacing value together with tile priority causes out of bound subtiles to be used when placing the tile.
![tile_atlas_bug](https://user-images.githubusercontent.com/1069303/98229498-45976700-1f5a-11eb-8edd-ec8d5af9efd1.gif)
![tile_settings](https://user-images.githubusercontent.com/1069303/98229505-47612a80-1f5a-11eb-8dcb-b42a426dbc33.PNG)

**Steps to reproduce:**
* Create a tileset with an Atlas using spacing between subtiles and put the Region over the entire area you'd expect to be used (see above image).
* Add the tileset to a TileMap.
* Paint with the tile using "Enable Priority".

**Workaround**
You can get around the issue by only covering part of the rightmost and bottom-most subtiles in the tile editor. This is pretty annoying when you've set up the preferred grid snapping though.

**Minimal reproduction project:**
[AtlasSubtileSpacingPrio.zip](https://github.com/godotengine/godot/files/5493628/AtlasSubtileSpacingPrio.zip)

**Comment by Salvakiya** [comment]
Just ran into this issue myself... is it related to this loop here? https://github.com/godotengine/godot/blob/2abe996414b8b551e69e29461de3ff1bcaf5a28f/scene/resources/tile_set.cpp#L654

**Comment by akien-mga** [comment]
Fixed by #50886.
