### ISSUE TITLE
Parse Error: Could not find base class "Light2D".

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43336]
**Godot version:**
4.0.dev.custom_build. 494bf38c7

**Issue description:**
When I type at the top of script `extends Light2D`, then error `Parse Error: Could not find base class "Light2D".` is shown.
It worked fine ~12 days ago.
Clicking at this text with Control button pressed, properly move to correct doc page with Light2D.

**Comment by akien-mga** [comment]
It seems `Light2D` is virtual now:
```
        ClassDB::register_virtual_class<Light2D>();
        ClassDB::register_class<PointLight2D>();
        ClassDB::register_class<DirectionalLight2D>()
```

**Comment by Xrayez** [comment]
Similar issue #42830, it means that virtual classes cannot be extended via script, only in C++...

Things like `VisualShaderNodeCustom` can be extended via script because they're not registered as virtual:
```c++
ClassDB::register_class<VisualShaderNodeCustom>();
```

But `VisualShaderNodeCustom` does register virtual methods with `BIND_VMETHOD`.

**Comment by qarmin** [comment]
Looks that Light2D become PointLight2D, so this is not a bug.
This should be added to docs/changelog as breaking change
