### ISSUE TITLE
Freeze to Hard Shutdown

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#4334]
**Operating system or device:**
Linux, Ubuntu MATE, this was Godot 2.1

**Issue description** (what happened, and what was expected):
I was replaying my scene which just generated a random number and printed it out. On one of the replays it froze my system except the mouse, but no GUI would respond to clicks in the OS or in Godot. Magic SysRq key didn't work and I was forced to do a hard shutdown. I should mention that I'm using dual monitors (laptop and TV) and that I had Godot load the game window on the TV (the second screen of course). The one thing that was notable is that on the time where it froze the game window opened in the first screen (the laptop).

**Steps to reproduce:**
Perhaps replay a scene (or the attached scene) a few times in a dual monitor set up where the game window opens on the second screen.

**Link to minimal example project** (optional but very welcome):
[Music Test.zip](https://github.com/godotengine/godot/files/221857/Music.Test.zip)

BTW, the scene in question is "new_scene2.scn" not "new_scene.scn".

**Comment by suptoasty** [comment]
If you spawn and que_free () on objects like bullets the engine does this at a random number of bullets spawned and deleted as well; On the same platform.

**Comment by OvermindDL1** [comment]
A user-level application like Godot really should be incapable of that.  What that sounds like is a bad driver.  Bad GPU drivers are the most common but not the only possible cause, however based on your description of the mouse working but the screen not responding is most commonly a GPU driver bug crashing your windowing system.

I downloaded and tested your zip file and have dual-output display however I was unable to replicate the issue.

**Comment by OvermindDL1** [comment]
Sent too soon, sorry.  ^.^

What is your hardware, driver versions of GPU, etc...?

**Comment by toliaferrode** [comment]
Hi, I was using the Intel mode of my GPU. Which doesn't seem to run even older games well. However I've been experience freezes with Nvidia mode but it's more of a general problem and has not occurred with Godot (as of yet). I think it has to do with heavy network traffic while the Nvidia mode is active, but that's another story. Ubuntu MATE is a rather young distro as well.

Anyway I've since switched back to Nvidia mode to do more testing. I've got an Intel Core i5-5200U here with an Nvidia GeForce 840M GPU. Nvidia driver version 352.63.

**Comment by toliaferrode** [comment]
Update. Since I've switched back to the Nvidia driver (and stopped doing heavy network stuff on it) it hasn't crashed in 3 days. Also, I tested my Godot project again and it hasn't crashed yet. I just keep reloading the scene over and over again. I'll be testing for a few more days, but I just wanted to send an update on the issue. Looks like you guys were right, it seems to be a driver issue.

**Comment by akien-mga** [comment]
Let's close then, if was a driver-specific issue it will not be possible to fix it anyway.
