### ISSUE TITLE
Duplicating a resource having a script attached to it crashes Godot

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#43341]
Godot 3.2.4 as of d3ffff3ad8552b4f75c96f4ff43451b8f60fec5e
Windows 10 64 bits

If you have said script:
```gdscript
extends Resource

export var channel:int = 0

func _get_used_channels_mask () -> int:
	return 1<<channel
 ```

And try to duplicate it like so:
```gdscript
const CustomResource = preload("./custom_resource.gd")

func _ready():
	var r = CustomResource.new()
	print("A")
	r.duplicate()
	print("B")
```

Godot crashes without any errors, having printed only `A` and not `B`.

Stack trace from original repro from my voxel module:
![image](https://user-images.githubusercontent.com/1311555/98304141-4d392900-1fb7-11eb-99bb-7bca179eefda.png)

Simple reproduction project, run the main scene:
[GDScriptDuplicate.zip](https://github.com/godotengine/godot/files/5497821/GDScriptDuplicate.zip)

It did not happen in the build I had from october 27th, and was happening on my CI build which included commits up to november 5th.

**Comment by akien-mga** [comment]
I can reproduce with commits from early November, but it doesn't happen with 3.2.4 beta 1 (before the regression) nor in 3.2.4 beta 2, so it was probably fixed (likely by @RandomShaper).
