### ISSUE TITLE
draw_string ignores \n break line

### ISSUE THREAD

**Issue by elbroandrew** [godotengine/godot#43345]
Hi,
I just want do draw a text at the line end, but the break line \n seems to be not working.
```
var label = Label.new()
var font = label.get_font("")
var player_x = 100
var player_y = 100
var ray_len = 50
var ray_end_x = 0
var ray_end_y = 0

func _draw():
	draw_line(Vector2(player_x, player_y), 
		 Vector2(ray_end_x, ray_end_y), 
		 Color(255, 255, 255), 2)
	draw_string(font, 
                   Vector2(player_x, player_y),
                  "player_x: " + str(10) + "\nplayer_y: " + str(20))
```

**Comment by Calinou** [comment]
@OBannon When reporting bugs, please follow the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it.

**Comment by CitrusWire** [comment]
Yep, I just hit the same bug. There's no documentation that /n doesn't work as you'd expect.

**Comment by Calinou** [comment]
@CitrusWire We had a [similar issue](https://github.com/godotengine/godot/issues/2967) with a `junior job` label applied, but it turns out it's not that much of a junior job. The situation is likely similar here.

**Comment by KoBeWi** [comment]
In 4.0 there is a `draw_multiline_string()` method that handles line breaks, language quirks etc. It won't be backported, because it depends on CTL changes.

For 3.x we could just document that it doesn't work.
