### ISSUE TITLE
AnimationPlayer Tracks Don't Work on Objects They Create

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#4335]
**Operating system or device:**
Windows 7 x64 using Godot 2.0.1 Stable (x64)

**Issue description**
As part of an animation track I call a function which adds a child to the object being animated. A pre-existing animation track that has the name of the object to be created cannot modify this object, even though it exists at that path by the time any functions are called by this track.

(In my game I have attacking animations spawn a weapon deterministically. I don't know which scene file the weapon will be in advance but it will always be called "Weapon" and it will always have the same path in the parent node. I want one of these attack animations to call that weapon's "shoot" function, but I can't seem to call this function from the animation player.)

**Steps to reproduce:**
Create an animation for an object. Add a track which calls a function which creates a child object. Have a function track in the animation editor which has the path to that child object, even though it does not exist in the editor (it'll have a line through it). Add a function call on the child object track at some point in the animation player's timeline that is after the child object was created. It won't work.

**Link to minimal example project**
[Example.zip](https://github.com/godotengine/godot/files/221973/Example.zip)

**Comment by reduz** [comment]
not a bug, you can't do this. Every time an animation starts, it generates a cache of all the nodes it's affecting, if the node was not found by then, it's not going to be found if you create it later.

To get what you are trying to do to work, you must call AnimationPlayer.clear_caches() after you added the node.
