### ISSUE TITLE
Godot disconnects all usb's in system

### ISSUE THREAD

**Issue by Kandif** [godotengine/godot#43359]
Godot version: any

OS/device including version: Ubuntu 18.04

I have problem with Godot and USB's in Ubuntu 18.04. When I run Godot after random period of time it disconnects every usb devices, (usb-hub + mouse which is connected on another usb.). Here is systems logs with part which include errors about that. https://pastebin.com/EBP6sPjw

**Comment by Calinou** [comment]
> Godot version: any

Which Godot version are you using?

Can you reproduce this if you [compile Godot](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html) with `udev=yes`?

**Comment by Kandif** [comment]
I am using 3.2.3.
I didnt compiled. I just downloaded and run file :P. I prefer to skip way with compiling on my self.

**Comment by Calinou** [comment]
> I prefer to skip way with compiling on my self.

Unfortunately, if you're the only user who can reproduce this, you'll most likely have to compile Godot yourself to further troubleshoot this issue.

**Comment by akien-mga** [comment]
Official binaries are built with `udev=yes` already.

**Comment by Kandif** [comment]
I upgraded my Ubuntu to 20.04 and still have the same issue.

**Comment by Kandif** [comment]
THe problem disapear when i unplug usb hub and plug every devices directly to USB. So there are two possibilities:
My usb hub have problem with Godot or Godot do sth bad with my Usb hub.

**Comment by Faless** [comment]
Is the HUB externally powered? If not, this could simply be the motherboard outputting less current to the USB-connected hub (standard is USB2 500mA USB3, 1A IIRC, but most motherboards can serve more if requested) due to heavy-load/GPU usage.

**Comment by Calinou** [comment]
@kandif Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
