### ISSUE TITLE
"Select Control Points" option is missing for Path node

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#43355]
**Godot version:**
3.2.3.Stable

**OS/device including version:**
Intel(R) Core(TM) i7-5820K, GTX 970, Windows 10 Pro

**Issue description:**
"Select Control Points" option is missing for Path node. The tool is available for Path2D and it works to use the tooltip from Path2D of holding down shift and dragging on the control point, so why is the tool not there for the 3D Path? There is no way of knowing how to make the path smooth if you don't know it already or go compare with Path2D like I did.

Tool missing:
![image](https://user-images.githubusercontent.com/4955051/98364215-4991ba80-2028-11eb-9f8c-08f44007e0c6.png)

Tool present:
![image](https://user-images.githubusercontent.com/4955051/98364293-704ff100-2028-11eb-9b35-d7f3ac57744d.png)

**Steps to reproduce:**
Create a new Path node and observe the issue.

**Minimal reproduction project:**
NA

**Comment by Xrayez** [comment]
> There is no way of knowing how to make the path smooth if you don't know it already or go compare with Path2D like I did.

This is probably not exactly related and asks for proposal, but stumbling upon this issue, it makes me think that perhaps those nodes could benefit from Catmull-Rom interpolation by default (the idea is that you don't necessarily need or want to configure control points manually), like in goostengine/goost#77. But perhaps this is already the case for `Path(3D)` nodes?

If that makes sense, I could create a proposal for this, but I'm not proficient in 3D to be able to elaborate on this topic, nor have a real-life use case to justify making a proposal.

**Comment by Arnklit** [comment]
This is resolved in Godot 4.2 (probably earlier, but saw it there). Closing.
