### ISSUE TITLE
UPnP doesn't delete the mapped port in Android

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot#43362]
**Godot version:**

3.2.3

**OS/device including version:**

Android 10

**Issue description:**

Mapped port isn't deleted with :
	upnp.delete_port_mapping(port)

**Steps to reproduce:**
var upnp := UPNP.new()
upnp.discover()
upnp.add_port_mapping(port)
upnp.delete_port_mapping(port)

**Minimal reproduction project:**

[upnp.bug.repro.zip](https://github.com/godotengine/godot/files/5502567/upnp.bug.repro.zip)

**Comment by Calinou** [comment]
@DisDoh Does the same code delete the mapped port on other platforms?

**Comment by DisDoh** [comment]
on Mac Os and windows and linux yes

**Comment by DisDoh** [comment]
On godot 3.3-rc6 it's closing the upnp port on Android.
So i think this ticket can be closed.
