### ISSUE TITLE
Cannot connect to websocket using an IPv6 address

### ISSUE THREAD

**Issue by jacopofar** [godotengine/godot#43365]
Probably related with https://github.com/godotengine/godot/issues/39331 but on the client side

**Godot version:**
3.2.3 stable

**OS/device including version:**
macOS 10.15

**Issue description:**
When connecting to a server exposing a websocket, the connection does not work if I specify `ws://[:.1]:4000` and run the game as a native app. If I export to HTML5 and run in the browser, the connection is established without issues.

If I use `127.0.0.1` the connection can be created both in HTML5 and in the native app, while with `localhost` only the HTML5 version works.

**Steps to reproduce:**

You can use the demo for Godot Phoenix channels [here](https://github.com/alfredbaudisch/GodotPhoenixChannels), accidentally it already implements this behavior and allows to try different hostnames from its UI

**Comment by jonbonazza** [comment]
@jacopofar what is localhost aliased to on your machine?

**Comment by jacopofar** [comment]
`ifconfig` says
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
```
pinging and nslookup report `127.0.0.1`
