### ISSUE TITLE
bug sprite3d

### ISSUE THREAD

**Issue by drcucaracha** [godotengine/godot#43367]
**Godot version:**
3.2.3

**OS/device including version:**
windows 7 64 bits 

**Issue description:**
sprites3d overlap each other

**Steps to reproduce:**
create two sprite3d nodes one as ground the other as character by advancing the character the ground is superimposed on the character

**Minimal reproduction project:**
[testsprite.zip](https://github.com/godotengine/godot/files/5503726/testsprite.zip)

**Comment by Calinou** [comment]
You may have to set the **Render Priority** property on one of the Sprite3Ds to ensure it overlaps the other one. See [Transparency sorting](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting) for more information.

**Comment by akien-mga** [comment]
Closing as there's no real bug report here to act upon, it's more a support question. The test project is just `icon.png` imported as a TextureArray (which doesn't work in GLES2).
