### ISSUE TITLE
Add an exposed getter method for the private property named connection in HTTPClient class.

### ISSUE THREAD

**Issue by mownier** [godotengine/godot#4336]
It seems that there's no way to get the `connection` property in HTTPClient class. Maybe we can expose a method called `get_connection` that returns the current connection of the client.

**Comment by AlexHolly** [comment]
I think there is also a status update missing

https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/core/io/http_client.cpp#80

status=STATUS_CONNECTED;

**Comment by akien-mga** [comment]
Fixed by 0ca7e19.
