### ISSUE TITLE
Debugging errors are being cleared half a second after occuring

### ISSUE THREAD

**Issue by Gnomeknows** [godotengine/godot#43374]
**Godot version:**
3.2.3 stable and 3.2.4 beta for linux and also the steam 3.2.3 version

**OS/device including version:**
ubuntu latest stable

**Issue description:**
an error occurs during f5 testing, it crashes and I look down to see what the error is, but it shows up as the red text at the top of the debugger tab for barely half a second, then the red error text clear and it snaps closed the debugger tab altogether and opens the script and the line where the issue is.  Reopening the debugger tab only shows the stack trace but not the error message.

only happens on the errors that close the test game window

**Steps to reproduce:**
start included project, click on little grey character that camera centers on, then at the top  of the right side panel it displays what's inside that 'tile', click on the 'squig' character, it brings up a popup, it crashes and wipes the error info.

**Minimal reproduction project:**
[godot_error_video.zip](https://github.com/godotengine/godot/files/5504687/godot_error_video.zip)
[godot_project.zip](https://github.com/godotengine/godot/files/5504759/godot_project.zip)

**Comment by Calinou** [comment]
Out of curiosity, are you printing text every frame?

Can you record a video of the editor when this occurs?

**Comment by Gnomeknows** [comment]
I just tried it without printing, but no I wasn't, I keep those to a minimum, I also tried it without warning messages but same result, trying to make a video now.

**Comment by Gnomeknows** [comment]
Video added

**Comment by Calinou** [comment]
@Gnomeknows Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

**Comment by Gnomeknows** [comment]
I tried and failed to reproduce it in 3.5.1 with the same project.

**Comment by Calinou** [comment]
Alright, closing for now.
