### ISSUE TITLE
Godot 3.2.4 Beta 1 - Choosing Collision Layer Bug

### ISSUE THREAD

**Issue by ashfidable** [godotengine/godot#43370]
**Godot version:**
Godot 3.2.4 Beta 1

**OS/device including version:**
Windows 10 and GLES2

**Issue description:**
Just upgraded my project from 3.2.3 to 3.2.4. Massive performance gain on tilemap side but there are few broken issues. I can't seem to deselect the first collision layer or mask. I can do for every other layer and mask. Just not the first one.

**Steps to reproduce:**
1. Add KinematicBody2D or TileMap or Area2D
2. Click the first layer mask in collision section
3. Try to deselect it.

**Minimal reproduction project:**

**Comment by qarmin** [comment]
Duplicate of #43137 fixed by #43084 
Fix will be available in beta 2
