### ISSUE TITLE
Invalid operand of type "Vector2" for unary operator "- (negation)"

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43389]
**Godot version:**
4.0.dev.custom_build. 30b6db99a
Regression from #43323 - but this can be GDScript issue like reduz said and this commit just exposed bug

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When using this code,
```
var ss : float = 2.0
-ss
```
or this
```
var use_Object : bool = false
	if ! use_Object:
		return

```
then this error are shown
```
Parse Error: Invalid operand of type Vector2 for unary operator "-(negation)"
Parse Error: Invalid operand of type "bool" for unary operator "not".
```

**Comment by AndreaCatania** [comment]
I encountered it for `float`, `int`, `Vector3` too. So I guess that something is broken with the unary check.

**Comment by AndreaCatania** [comment]
Just checked with the last commit, this issue seems fixed.

**Comment by qarmin** [comment]
I can still reproduce with 4.0.dev.custom_build. f73374629

**Comment by aaronfranke** [comment]
This happens for me too. Temporary workaround: replace `-` with `-1 * ` and it should work.

**Comment by AndreaCatania** [comment]
You right, though this issue is less severe now and it's allowed in some lines.
