### ISSUE TITLE
Missing icons in editor for Joint2D, CanvasGroup, DirectionalLight2D, PointLight2D

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43388]
**Godot version:**
4.0.dev.custom_build. 30b6db99a

![Zrzut ekranu z 2020-11-08 07-36-40](https://user-images.githubusercontent.com/41945903/98458853-289aa800-2195-11eb-82f9-398f2e9681c3.png)

**Comment by pycbouh** [comment]
Lights: https://github.com/godotengine/godot/pull/43380
CanvasGroup: https://github.com/godotengine/godot/pull/43220 or https://github.com/godotengine/godot/pull/43291

**Comment by KoBeWi** [comment]
Closing in favor of #46056
