### ISSUE TITLE
need hotkey for 'continue'

### ISSUE THREAD

**Issue by eaglecat** [godotengine/godot#4338]
I really need hotkey for  'continue' when debugging

**Comment by neikeq** [comment]
I completely agree. What could be the hotkey?

**Comment by eaglecat** [comment]
f8 would be good

**Comment by neikeq** [comment]
F8 is already used to _"Stop the scene"_. Perhaps something like _Ctrl+F5_.

**Comment by eaglecat** [comment]
how about f4 or f12

**Comment by reduz** [comment]
and then they were victims of a terrible fate as, two months later, no one has heard of them again

**Comment by reduz** [comment]
I like ctrl-f5, will add that

**Comment by reduz** [comment]
no, wait a second, pause button actually works as resume.. so this is not needed anymore, just use F7.
