### ISSUE TITLE
Hovered and Pressed button themes are duplicated

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#43386]
**Godot version:**
3.2.3

**OS/device including version:**
Zorin OS Core 15.3

**Issue description:**
There seems to be duplicate entries in button styles
![image](https://user-images.githubusercontent.com/2453707/98454606-39a6d300-211b-11eb-883c-0dcfe3e86a0a.png)

**Steps to reproduce:**
- Change theme to light
- Create a theme from editor themes
- Open button styles

**Minimal reproduction project:**
[Godot.zip](https://github.com/godotengine/godot/files/5505723/Godot.zip)

**Comment by pycbouh** [comment]
Screenshot shows colors, not styles. I don’t see a duplication. There are two colors for fonts and two for icons.

**Comment by Shadowblitz16** [comment]
your right my bad
