### ISSUE TITLE
Unexpected results from min() and max() on 2D arrays

### ISSUE THREAD

**Issue by IIGreed** [godotengine/godot#43395]
**Godot version:**
3.2.3

**OS/device including version:**
Windows10 64bits

**Issue description:**
comparing arrays inside of an array using min() and max() result in different results than in a 1d array
and min seems to copy the result of max most of the times.

```
var D = ["abc","zxy","ABC","ZXY"]          -> max: zxy    min: ABC
var DD = [["abc"],["zxy"],["ABC"],["ZXY"]] -> max: [zxy]  min: [zxy]  
```

Expected result:
```
DD.min() = [ABC]
DD.max() = [zxy]
```

Numbers are also affect by 2d Arrays:

```
var D = [0,7,8]         -> max: 8     min: 0
var DD = [[0],[7],[8]]  -> max: [8]   min: [8]
```

Expected result:
```
DD.min() = [0]
DD.max() = [8]
```

Weirdly enough the "-" symbol is taken in consideration but only when the nested array has 2 values.

Both of these arrays will take the array with the -5 as min value:
```
[["a",7],["a",8],["a",-5]] -> max: [a,8]   min: [a,-5]
[[1,7],[1,8],[1,-5]]       -> max: [1,8]   min: [1,-5]
```

This one won't
`var DD = [[7],[8],[-5]] -> max: [8]   min: [8]`

Expected result:
```
DD.min() = [-5]
DD.max() = [8]
```

Also it would be nice if the documentation explained how it is concluded what is the value of a strings or a nested arrays.

**Comment by DavidSichma** [comment]
caused by #39299

fixed on recent master by #43323 that introduced working array comparisons.

3.2 array comparisons remain broken.

**Comment by akien-mga** [comment]
> caused by #39299

This doesn't seem to be a PR that caused this, but another duplicate bug report for that same issue. Did you mean to link a PR?

**Comment by DavidSichma** [comment]
> Did you mean to link a PR?

No, I just wanted to link an issue explicitly about the comparison operators being broken, which is the underlying bug. I made my wording clearer.

**Comment by IIGreed** [comment]
I tried to replicate this issue in Godot 4.1 and it's fixed, the [documentation](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-max) states: 

> If the elements can't be compared, null is returned.

As a noob I would expect numbers and letters to be elements that can't be compared, unless what its actually being compared is the addition of their Unicode's value.

I'm closing this this issue since it is already resolved.
