### ISSUE TITLE
Modulate property is not affecting Control nodes with StyleBoxFlat style

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot#43394]
**Godot version:**
master @ 1abe52e611b7681084c47e6a05d088b307b60fe0

**OS/device including version:**
Windows 10
Intel Core i7-6700HQ with HD Graphics 530
NVIDIA GeForce GTX 960M

**Issue description:**
Controls with a StyleBoxFlat style cannot be affected by the modulate property, neither to adjust hue nor to change the opacity via the alpha channel. It works as expected in 3.2.3 stable, but not on master at the specified commit. Setting the modulate alpha to 0, however, hides the control, so there is at least that.

3.2.3-stable
![godot windows opt tools 64_2020-11-08_20-28-57](https://user-images.githubusercontent.com/11782833/98472251-ef991c80-2202-11eb-86f6-79b388145203.png)

master
![godot windows tools 64_2020-11-08_20-33-15](https://user-images.githubusercontent.com/11782833/98472260-ffb0fc00-2202-11eb-9b3f-5e6da8c5ef4d.png)

At the same time StyleBoxTexture is modulated correctly.

**Steps to reproduce:**
Make a UI scene, add a control node that has styleboxes and set the default one to be a new StyleBoxFlat. Then adjust the modulate property of said control node to change hue or alpha. Everything except alpha being set to 0 has no affect on the color of the stylebox.

**Minimal reproduction project:**
[bug-4.0-flatsb-modulate.zip](https://github.com/godotengine/godot/files/5506853/bug-4.0-flatsb-modulate.zip)

**Comment by Calinou** [comment]
Can you reproduce this when using the GLES2 renderer, or when disabling batching in GLES3?

**Comment by pycbouh** [comment]
Seems to be working fine in 3.2.3-stable with GLES2. Same for GLES3 but with [these](https://user-images.githubusercontent.com/11782833/98482155-828c8380-2210-11eb-8005-17c7c11b79e8.png) off. Do you have some other version in mind? So far I'm only seeing this with Vulkan.

**Comment by nathanfranke** [comment]
I have the same issue with Control+Shader

**Comment by pycbouh** [comment]
Fixed by #49863.

![image](https://user-images.githubusercontent.com/11782833/123141287-e80c4800-d460-11eb-99f7-0ec96b0d12da.png)
