### ISSUE TITLE
Can't minimize the editor window when selected in 3d view 

### ISSUE THREAD

**Issue by happydpc** [godotengine/godot#43392]
Godot version:
4-71907cb6d

**OS/device including version:**
GTX 2070 Vulkan windows 10

**Issue description:**
When selected an item in 3d editor view, can't operate on the minimize button on the main window.

**Comment by Calinou** [comment]
Can you record a video of your desktop when you're trying to minimize the window? I don't know why it wouldn't work.

There were known issues with the minimize button not working if the editor window is maximized, but I think that one was fixed a long time ago.

**Comment by happydpc** [comment]
> Related to #15833.
> 
> Does this occur if you make the editor window non-maximized first?

No, just select something in view, then the main window not responded.

**Comment by Calinou** [comment]
@happydpc Can you (or anyone else) still reproduce this bug in Godot 4.0 or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
