### ISSUE TITLE
Node anchoring

### ISSUE THREAD

**Issue by arcanis** [godotengine/godot#4339]
**Issue description:**
It would we nice to have a way to specify the base anchoring of elements, in each axis. In the linked minimal project, eight sprites should be positioned on each eight directions of another one. However, it's currently impossible to position them automatically in such way that even if we change the assets, the positioning will still be correct (ie you always have to hardcode the position according to the assets dimensions).

What I have:

![image](https://cloud.githubusercontent.com/assets/1037931/14581839/2deaa4c4-03f7-11e6-9951-31218652ec64.png)

What I'd like to have (of course, the assets here are very simple, in my actual project each direction has a different texture):

![image](https://cloud.githubusercontent.com/assets/1037931/14581828/f1a21f74-03f6-11e6-8a6a-84f94567bbf6.png)

**Steps to reproduce:**
Here's what I tried:
- A TextureFrame inside a Container doesn't work, because there's no way to set one of the two related margins to `auto` like it would be possible in css. In css, if you the left margin to `auto` and the right margin to `0`, the engine will understand that the element should be anchored to the right side of its referential, and take as much size as it needs, but no more.
- Using Sprites set up with a 90° rotation followed by a negative scale work for the corners, but not for the North-North / East-East / South-South and West-West directions, because this technics require the sprite to tick off the "Centered" property for one of the axis to work - and unfortunately, the other axis requires this property to be ticked on to work.

**Link to minimal example project:**
[DEMO.zip](https://github.com/godotengine/godot/files/222263/DEMO.zip)

**Comment by toger5** [comment]
There is actually a anchoring system in godot.
And I think it is powerful enough. If you already know it and it doesn't fixeds your issue, than I didn't understand your problem. If not I can tell you how I would deal with it.
You have four anchor settings, One for each side. And accordingly four margin settings. The anchor settings can be set to Begin,End,Center,Ratio. They describe how the four sides are placed. So if you set the left anchor to End menas that the position of the left edge of the object is placed relative to the End (right side) of the parent object. If you set it to Begin that the left side is placed relative to the Beginning (Left side) of the parent object.
Right than describes how the right side is placed and top and bottom for the last two sides. With the margin settings you than can setup the values (how far from which side it is placed).

So this is how I would solve your issue:
For the box on the right center:
Anchor:
    Left: End
    Right: End
    top: center
    Bottom: Center
Than place the sprite int the viewport as you need it to..
The values than will look like that if you have a 20*20 px image
Margin:
    Left 20
    Right: 0
    Top 10
    Bottom 10

Just to make this post complete I shortly describe the other anchor systems
Center: Margin describes the distance to the center point of the parent object
Ratio: margin is a value from 0 to 1 and describes the relative position. (0.5 menas exactly at the center, 0.7 mens slightly on the right....)
Hope this solves your issue ... But nontheless this is a great and very powerful feature which should solve every problem with anchoring and positioning (especially in combination with simple scripts ;) )

**Comment by arcanis** [comment]
Thanks for the explanation, it's quite helpful :)

However, it doesn't solve the main issue I have with anchoring: as you said, the values "will look like that *if you have a 20x20px image*". But what if my image is 50x50? Or if I decide that actually, I like rectangles better and switch to 20x50? Or if I want a texture switch on mouse over (so at runtime), and that this texture has a totally different size than the normal one? In all of these cases, the margins will not work as expected, and the user will have to compute new ones.

In css (the pseudo-language used to describe how should a web page be rendered), there's a very similar feature, that also works with margins. The key difference is that the engine allows a special value on top of a numerical one: `auto`. When `auto` is selected, the engine is let to decide the actual size of the margin, based on the parent container, the child size, and the opposite margin value. So for example, in my case, the North-East and East-East element would have the following properties:

```
// North-East
left: auto;
right: 0;
top: 0;
bottom: auto;

// East-East
left: auto;
right: 0;
top: auto;
bottom: auto;
```

The whole css feature is actually much more complex, and not needed here. But the `auto` property seems like something that could prove a useful addition to the anchoring mechanisms already there.

**Comment by bojidar-bg** [comment]
Probably containers would do the trick here.

**Comment by Gfurst** [comment]
no, this is the same issue as described #2965 
I think arcanis was bit confusing in explaining it, but the real issue is that nodes always grow to the right and bottom, regardless of anchoring, (and always shrink the opposite of that). Always torwards the origin point, where as it would be expected for them to grow relatively to the anchoring point.

The images above describe it really well, if you have a node position and anchored at the bottom-right corner, if for whatever reason the node changes size (either texture change, or resizing of its children), its expands always to the bottom and right, opposed to what its expect, that is, for it to remain anchored in relation to the bottom-right corner.
issue #5775 is yet another user who seems to want same thing.

**Comment by reduz** [comment]
This was finally implemented by allowing controls to specify grow directions, so closing this.

**Comment by adadgio** [comment]
> This was finally implemented by allowing controls to specify grow directions, so closing this.

Where was this implemented ? Which setting is this ? Are you sure ?
