### ISSUE TITLE
Incorrect Character Animation

### ISSUE THREAD

**Issue by norrath-hero** [godotengine/godot#43406]
**Godot version:**

Godot_v3.2.3-stable_win64
Godot_v3.2.4-beta1_win64

**OS/device including version:**

Nvidia GTX 960, Windows 10 Both GLES2 and GLES3 renderer, Both fbx and glb format

**Issue description:**

Incorrect character animation, maybe cause by some bugs of skinning calculations?

Cocos Creator 3D can correctly animate the rigged model

Cocos Creator 3D FBX:
![cocos_fbx](https://user-images.githubusercontent.com/73905273/98533477-02245c00-22be-11eb-9dba-8ccecd0c2d6c.gif)
Cocos Creator 3D GLB:
![cocos_glb](https://user-images.githubusercontent.com/73905273/98533501-08b2d380-22be-11eb-9b68-985a5226504c.gif)

Godot FBX:
![godot_fbx](https://user-images.githubusercontent.com/73905273/98533523-0e101e00-22be-11eb-861b-f30b538c7710.gif)
Godot GLB:
![godot_glb](https://user-images.githubusercontent.com/73905273/98533532-10727800-22be-11eb-90aa-0a791f407493.gif)

**Steps to reproduce:**
1. Open the model fbx or glb
2. choice "New Inherited"
3. select "AnimationPlayer"
4. switch viewport to "Right Orthogonal[auto]"
5. click play in Animation Editor

**Minimal reproduction project:**

[demo3d.zip](https://github.com/godotengine/godot/files/5509972/demo3d.zip)

**Comment by Calinou** [comment]
FBX import is known to be broken for animated scenes right now. 3.2.4beta2 will feature a [brand new FBX importer](https://github.com/godotengine/godot/pull/42941).

**Comment by norrath-hero** [comment]
> 
> 
> FBX import is known to be broken for animated scenes right now. 3.2.4beta2 will feature a [brand new FBX importer](https://godotengine.org/article/fbx-importer-rewritten-for-godot-3-2-4).

I think this is not relevant to importing, because both fbx and glb formats works incorrectly, it possibly some core skinning calculations bugs

**Comment by norrath-hero** [comment]
I don't want to post negative things here, because I known people in the community are nice and working very hard. but after all these long years we still missing basic stable assets workflow, are we really going to wait Godot forever?

**Comment by Calinou** [comment]
@norrath-hero Godot is developed on a best-effort basis. As per its [license](https://godotengine.org/license), there's no warranty provided for anything.

**Comment by norrath-hero** [comment]
Close it because following the links seems use collada can avoid this issue
