### ISSUE TITLE
Flatpak Installation on Lenovo Duet Chromebook; Error on Launch

### ISSUE THREAD

**Issue by sly-roccoon** [godotengine/godot#43401]
**Godot version:**
3.2.3

**OS/device including version:**
Chrome OS 86.0.4240.183 (32-Bit) / Lenovo Duet Chromebook

**Issue description:**
When trying to launch Godot (installed as a flatpak) I am met with the following error:
```
Godot Engine v3.2.3.stable.flathub - https://godotengine.org
OpenGL ES 3.0 Renderer: llvmpipe (LLVM 9.0.1, 128 bits)
Unable to find target for this triple (no targets are registered)
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/arm-linux-gnueabihf/libc.so.6(+0x275d0) [0xf6ff15d0] ()
-- END OF BACKTRACE --
/app/bin/godot: line 3:     4 Aborted                 (core dumped) /app/bin/godot-bin "$@"
```

**Comment by akien-mga** [comment]
I'm not sure if this is a Godot issue or if it belongs to https://github.com/flathub/org.godotengine.Godot/issues

@Calinou Does the FlatHub distribution include an armv7 build? I see you're excluding aarch64 on https://github.com/flathub/org.godotengine.Godot/blob/master/flathub.json, but I don't know which platforms are then still included by default.
For the reference, I build Godot successfully on armv7 and aarch64 on Mageia Linux (though I admit I never actually tried the binaries to see if they're functional).

@sly-roccoon Do you have Linux support enabled for your Chrome OS? See https://www.computerworld.com/article/3314739/linux-apps-on-chrome-os-an-easy-to-follow-guide.html (might not be the best resource around this, I just picked one of the first links).

**Comment by Calinou** [comment]
>  Does the FlatHub distribution include an armv7 build?

I think it does, otherwise you'd get an "Exec format error" on startup (or `flatpak` would refuse installing the Flatpak altogether).

**Comment by sly-roccoon** [comment]
Working now, thanks!
