### ISSUE TITLE
Godot closes directly after launching

### ISSUE THREAD

**Issue by benutzerjannes** [godotengine/godot#43411]
Hello Ppl,

Suddenly my Godot has got an Issue with launching. 

When i start it, the console (cmd) opens and 3 seconds later the console and godot closes down. 
The main Godot Exe wont even open - only the console windows opens up. 

Graphics driver is updated, it worked before, and it is the Godot Version 3.2.3 for 64 Bit. 

Thanks for your help!!!

**Comment by groud** [comment]
Hi, there is an issue template. Please edit your issue and provide the required information. I will reopen when this is done.

Also, without information on the message, a video, or a reproduction project, there's no way we can solve the issue.
