### ISSUE TITLE
Crash when "Updating Scene"

### ISSUE THREAD

**Issue by UltimaN3rd** [godotengine/godot#4341]
**Operating system or device:** Ubuntu 14.04 LTS x64

**Issue description** (what happened, and what was expected): Edited a node in a scene and saved with ctrl+s. Switched to another scene which had instances of this scene in it. Godot editor crashed with box saying "Updating Scene" and a progress bar at exactly 50%. This happened twice - once I edited the Z depth of a Sprite node and the other time (in another scene) I changed a Node to a Control.

**Steps to reproduce:** Have a scene instanced within another scene. Edit the instanced scene file in some way. Save (ctrl+s) then click to the tab containing the scene instances.

**Comment by neikeq** [comment]
I could not reproduce this under Ubuntu 15.10 x64 in the current muster branch. A sample project would be helpful.

**Comment by UltimaN3rd** [comment]
The project it's happening in has stuff I don't really want to share at the moment. . . This bug might just be an anomaly as it doesn't happen every time. It has only happened when I've been extremely quick pressing ctrl+s then switching to another scene tab.

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by UltimaN3rd** [comment]
This bug seems fixed in Godot 3.0.2

When following the steps I detailed in the original bug report Godot froze for a couple of seconds with the "Updating Scene" box and a progress bar at exactly 50% but then continued to function normally.
