### ISSUE TITLE
Build failures with Visual Studio 2010

### ISSUE THREAD

**Issue by SteelyGlint** [godotengine/godot#4342]
Godot versions 2.0.2, 2.0.1, and 2.0 do not build with Visual Studio 2010 on Windows 7. I followed the steps described on the [Compiling for Windows](http://docs.godotengine.org/en/latest/reference/compiling_for_windows.html) page.

The initial problem I saw was with the INFINITY macro used in Godot 2.0.2, [as described in this post](http://www.godotengine.org/qa/3085/godot-2-0-2-build-fails-on-win7-vs2010). The INFINITY macro was [committed on March 8](https://github.com/godotengine/godot/commit/0635a639e92577948ce61011ee31abedb35c05f6), so I tried version 2.0.1 (from March 6) and 2.0 to see if they would build.

Godot 2.0.1 and 2.0 also suffer from build failures with Visual Studio 2010, but it's a linker error rather than the INFINITY macro: `LINK : fatal error LNK1181: cannot open input file 'dxguid.lib'`

The Compiling for Windows page currently erroneously states that VS2010 is supported.

**Comment by vnen** [comment]
IMO it's easier to simply drop support for VS2010. It's quite hard to even download it, which makes it harder to test and maintain. I don't see any reason to keep the support, since anyone can get the 2013 or 2015 easily and for free.

@SteelyGlint do you have any particular reason to keep using VS2010?

**Comment by SteelyGlint** [comment]
No particular reason for me to want to use VS2010 beyond the standard: I already had it installed, I'm used to the workflow/interface, I have it configured the way I like it, change is always risky, etc.

I've always been a bit skeptical about whether VS2013 Community would be the right solution for me (TANSTAAFL), but some research suggests that it will probably do what I need. I installed VS2013 Community and built Godot 2.0.2 on the first try. 

If VS2010 isn't supported, it should be removed from the documentation so people like me don't waste 5 hours trying to get it working. You could even include a link straight to a MS page for downloading VS2013/VS2015.

**Comment by kubecz3k** [comment]
@godotengine/documentation it might be good idea to mention in docs that VS2010 is no longer supported

**Comment by akien-mga** [comment]
I'm on it.
