### ISSUE TITLE
Attempted to free invalid ID error when opening and closing project manager

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43430]
**Godot version:**
4.0.dev.custom_build.efc4d217d

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
This error comes from line 
https://github.com/godotengine/godot/blob/90edd839d5f67d4252923a720feeef6ad0d76107/servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp#L2571

The easiest fix is to comment/delete this line, because it doesn't introduce leak

**Comment by akien-mga** [comment]
```
13:59 <Akien> reduz: see #43430 about that RenderingDevice invalid ID free that I mentioned yesterday. qarmin found which line causes it, but needs confirmation if it can be removed or if more work is needed.
14:00 <reduz> Akien: ah its an uniform set, yeah good to remove since it gets autoremoved when then contents of the uniform set are removed
```
