### ISSUE TITLE
[3.x] `AnimatedSprite` normal maps are displayed with differences from project until editor restart

### ISSUE THREAD

**Issue by squimmy** [godotengine/godot#43435]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**

Godot_v3.2.3-stable_win64

**OS/device including version:**

Windows 10, OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2

**Issue description:**

When adding a normal map to an AnimatedSprite, the normal map does not always take effect as expected. It seems to work in the editor, but not when the scene is run. Issue https://github.com/godotengine/godot/issues/38509 includes a comment saying this feature "doesn't work", but I don't know if the issue was subsequently resolved, since the documentation was updated to suggest that it should be working.

**Steps to reproduce:**
Add an Animation to the SpriteFrames for an Animated sprite, and add another Animation with a normal map using the same name with `_normal` appended. The expected behaviour (the normal map affects lighting) can be seen in the editor, but is not seen when the scene is run. Opening an existing project with normal maps already added also exhibits the same problem.

**Minimal reproduction project:**

[2D Lighting.zip](https://github.com/godotengine/godot/files/5517235/2D.Lighting.zip)

The normal map animation (`spin_normal`) doesn't take effect in the editor unless the `spin` animation is either removed and re-added or renamed to something else and the renamed back to `spin`. the normal map also doesn't take effect when the scene is run.

**Comment by valpet** [comment]
I have also encountered this issue.

**Comment by Calinou** [comment]
As a workaround, I suppose you can use the Sprite + AnimationPlayer workflow instead of AnimatedSprite. It requires more work to setup, but it's technically a more powerful approach.

**Comment by valpet** [comment]
I began doing that but my sprite sheets have sizes that's a power of two (like 512x512, 1024x1024 etc) and there's blank space padded at the bottom or spacing between rows of sprites. The slicing algorithm does not seem to handle that afaik, which is topic for another issue. I was hoping to use the simpler and easier to use AnimatedSprite for static (but animated) objects like trees, torches etc as it seems perfect for that.

**Comment by pietrodito** [comment]
In my project it is working like a charm. Maybe the issue can be closed now?

**Comment by aykut4** [comment]
@pietrodito can you please provide some insight how it is working like a charm for you?

**Comment by pietrodito** [comment]
+ [Here](https://github.com/pietrodito/Godot_zipped_projects/blob/master/2D.Lighting.fixed.zip) the initial project of the OP with normal map fixed.
+ [Here](https://github.com/pietrodito/Godot_zipped_projects/blob/master/normal.gif) a .gif that shows it works on my v3.3.1
+ [Here](https://gamedev.stackexchange.com/questions/192441/how-to-use-a-normal-map-for-light-effects-with-an-animatedsrpite/192442#192442) a StackExchange question for details

**Comment by squimmy** [comment]
The "fixed" project includes a custom shader.
This seems like a good workaround, but I don't think I'd consider the issue fixed unless the intended behaviour is for normal maps to do nothing by default.

**Comment by r0ber70** [comment]
Yes, still a problem.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 4.x builds?

**Comment by dalexeev** [comment]
> Add an Animation to the SpriteFrames for an Animated sprite, and add another Animation with a normal map using the same name with `_normal` appended.

In 4.0, support for normal and specular maps in `AnimatedSprite2D` (via `_normal` and `_specular`) has been removed in #43052 in favor of `CanvasTexture`.

But I don't know if this issue remained in one form or another in 4.0 and in 3.x.

**Comment by CamBrown00** [comment]
so there's no way to use normal/specular maps with an animated sprite at all anymore then?

**Comment by CamBrown00** [comment]
Ah ok I see, so you just add the frames from a CanvasTexture resource in the SpriteFrames editor

**Comment by akien-mga** [comment]
Fixed by #80406.
