### ISSUE TITLE
Rename Tween.stop() to pause()

### ISSUE THREAD

**Issue by opl-** [godotengine/godot#43442]
The `Tween.stop()` and `Tween.stop_all()` methods are named in a way that suggests that they stop the playback and reset the tween progress to `0`, while in reality it only stops playback.

Related:
- #31168 - Similar issue for `AnimationPlayer`
- [`AnimatonPlayer.stop()`](https://docs.godotengine.org/en/3.2/classes/class_animationplayer.html#class-animationplayer-method-stop), mentioned in https://github.com/godotengine/godot/issues/31168#issuecomment-519136003
- Fixed by #41794

**Comment by Calinou** [comment]
It would be better to leave a comment in https://github.com/godotengine/godot/issues/16863#issuecomment-612792875 for renaming requests.

That said, keep in mind [Tween is being rewritten for 4.0](https://github.com/godotengine/godot/pull/41794).

**Comment by opl-** [comment]
Yeah, I'm writing a comment in that thread as we speak. Honestly the issue of "stop" vs "pause" is already being discussed in several places, so I decided to open a separate issue to track `Tween` naming specifically. Feel free to close it in favor of the tracker thread or making #31168 more general.

**Comment by KoBeWi** [comment]
The rewrite was merged, so this issue is resolved.
