### ISSUE TITLE
Godot won't start

### ISSUE THREAD

**Issue by AdhamDahle** [godotengine/godot#43447]
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1070 Ti/PCIe/SSE2

**Issue description:**
Godot won't start I get this message
" Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1070 Ti/PCIe/SSE2"
But It won't start

**Comment by aaronfranke** [comment]
What is your OS and hardware? Does this happen on any other computers?

**Comment by AdhamDahle** [comment]
Windows i7 graphic card gtx 1070ti

I counter this problem several times while programming the solution is to
resart the pc once a while but its frustrating to do that in middle of the
code

**Comment by Calinou** [comment]
With the given information, there's absolutely nothing we can do about this issue report.

Can you start Godot from a command prompt with the `--verbose` command line argument and paste the output here?

**Comment by Allov** [comment]
I also have this problem. Restarting the PC seems to resolve the issue.

Here's a dump running the `--verbose` option:

```
C:\Apps\Godot_v3.2.3-stable_mono_win64>Godot_v3.2.3-stable_mono_win64.exe --verbose
Godot Engine v3.2.3.stable.mono.official - https://godotengine.org
Using GLES3 video driver
OpenGL ES 3.0 Renderer: GeForce GTX 1070/PCIe/SSE2
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms

Mono: Initializing module...
Mono JIT compiler version 6.6.0 ((no/d9001b5a)
Mono: Log file is: 'C:\Users\...\AppData\Roaming/Godot/mono/mono_logs/2021_03_23 12.31.19 (23332).txt'
Mono: Runtime initialized
Mono: Loading assembly mscorlib...
Mono: Assembly mscorlib loaded from path: C:\Apps\Godot_v3.2.3-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll
Mono: Loading scripts domain...
Mono: Creating domain 'GodotEngine.Domain.Scripts'...
Mono: INITIALIZED
Mono: Loading assembly GodotSharp...
Mono: Assembly GodotSharp loaded from path: C:\Apps\Godot_v3.2.3-stable_mono_win64/GodotSharp/Api/Debug/GodotSharp.dll
Mono: Loading assembly GodotSharpEditor...
Mono: Assembly GodotSharpEditor loaded from path: C:\Apps\Godot_v3.2.3-stable_mono_win64/GodotSharp/Api/Debug/GodotSharpEditor.dll
Mono: Loading assembly GodotTools...
Mono: Assembly GodotTools loaded from path: C:\Apps\Godot_v3.2.3-stable_mono_win64/GodotSharp/Tools/GodotTools.dll
Mono: Loading assembly GodotTools.ProjectEditor...
Mono: Assembly GodotTools.ProjectEditor loaded from path: C:\Apps\Godot_v3.2.3-stable_mono_win64/GodotSharp/Tools/GodotTools.ProjectEditor.dll
CORE API HASH: 13116283933631344335
EDITOR API HASH: 6348957170305068143
Loading resource: C:\Users/.../AppData/Roaming/Godot/editor_settings-3.tres
EditorSettings: Load OK!
EditorSettings: Save OK!
Loaded builtin certs
```
Logs look like this before selecting a project:

![image](https://user-images.githubusercontent.com/1179492/112183082-4a407d00-8bd4-11eb-9fd1-8c5a05665202.png)

```
Editing project: C:/dev/CYBERTRON/code (C:::dev::CYBERTRON::code)
EditorSettings: Save OK!
Godot Engine v3.2.3.stable.mono.official - https://godotengine.org
Mono: Finalizing scripts domain...
Mono: Unloading scripts domain...
Mono: Runtime cleanup...
Mono: Finalized
```
Then, choosing a project gives me these.

**Comment by Allov** [comment]
Log file in mono_logs:

[2021_03_23 12.35.32 (2940).txt](https://github.com/godotengine/godot/files/6191326/2021_03_23.12.35.32.2940.txt)

**Comment by Calinou** [comment]
Closing due to lack of response.

@AdhamDahle Please reply if you're still running into this issue.
