### ISSUE TITLE
Resources created from a script get their type int variables set to 0 once opened in the inspector

### ISSUE THREAD

**Issue by IIGreed** [godotengine/godot#43455]
Godot version:
3.2.3

OS/device including version:
Windows10 64bits

Issue description:
I created a script to save every key and its data in a resource "tres" file. The resources are created and I can open then in the inspector all the variables have their values properly set, but when I click on another resource and go back to the first inspected resource its integer variables are set to 0. After some testing I found out this only happens when I parse the dictionary from the json and save it as type int **saving it as a float will work as intended** and If I copy and paste the exact same dictionary into a variable in the script there won't be any problems either.  

Its worth mentioning I've been using this same json extensible and I've never had any problems until I tried to assign the values to these script-created resources.

I would also like to mention that Godot lets me assign the wrong type of variable into the resources, I can set an **export (int) max_stack** to be an empty array and it won't cry about it although in the inspector the value is 0 opening the tres fill will display in fact an empty array.

**Steps to reproduce:**
Parse json dictionary > Create the resources > Set resources variables to their homonymous in the parsed dictionary

**Project code**:

Item.gd:
```gdscript
extends Resource
class_name Item

export (String) var name 
export (String) var category
export (int)    var max_stack
```

Import&Export.gd:
```gdscript
extends Node

onready var items_data

func _ready():
  items_data = Parse_json()
  #items_data = {"Apple":[15,"Fruit"],"Wood":[30,"Material"],"Axe":[1,"Tool"],"WaterCan":[1,"Tool"]}

func Parse_json():
  var data_read = File.new()
  data_read.open("res://Data.json",File.READ)
  var data = parse_json(data_read.get_as_text())
  data_read.close()
  return data

func _input(event):
  if event.is_action_pressed("ui_right"):
    create_resources()

func create_resources():
	
  for key in items_data:

    var new_resource = Item.new()

    new_resource.name        = key
    new_resource.category    = items_data[key][1]
    new_resource.max_stack   = items_data[key][0]
		
    #Shouldn't this be an error since max_stack is an integer type?
    #new_resource.max_stack   = [] 
		
    print("\n",key)
    print("Resource: ",new_resource.category,"  DBase: ",items_data[key][1])
    print("Resource: ",new_resource.max_stack,"  DBase: ",items_data[key][0])
		
    ResourceSaver.save("res://Resource/"+key+".tres",new_resource)
```

**Minimal reproduction project:**

[Bug Resource v0.2.zip](https://github.com/godotengine/godot/files/5524917/Bug.Resource.v0.2.zip)

**Comment by Calinou** [comment]
Keep in mind JSON only has a number type (which is stored as `float` in Godot), not distinct integer and float types.

**Comment by IIGreed** [comment]
> 
> 
> Keep in mind JSON only has a number type (which is stored as `float` in Godot), not distinct integer and float types.

I didn't know that. But what about resources not enforcing their assigned types, why can I set an integer or an array if their on a variable with another type specified?

**Comment by IIGreed** [comment]
This is an old issue Gdscript 2.0 typehints work much better I haven't had this issue since Godot 4.0.
