### ISSUE TITLE
Custom loaders are broken after 3.2.4 fix to variants

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#43460]
Godot 3.2.4 1e9a774ac24ecbbec9b0aa4b903f3f1525f4d525
Windows 10 64 bits

After getting this report https://github.com/Zylann/godot_heightmap_plugin/issues/216, I checked in a simple project, and I saw custom loaders no longer work after this fix: 1e9a774ac24ecbbec9b0aa4b903f3f1525f4d525
This makes my plugin unusable, and to my knowledge there is no workaround.

MRP:
[CustomLoaders.zip](https://github.com/godotengine/godot/files/5526147/CustomLoaders.zip)
Open the project in the editor, observe the following errors:
```
ERROR: ResourceLoader::add_resource_format_loader: Condition "p_format_loader.is_null()" is true.
   At: core\io\resource_loader.cpp:539
Loading resource: res://alpaca_saver.gd
Loading resource: res://alpaca.gd
ERROR: It's not a reference to a valid ResourceFormatSaver object.
   At: core\io\resource_saver.cpp:161
Loading resource: res://alpaca_loader.gd
Loading resource: res://alpaca.gd
ERROR: ResourceLoader::add_resource_format_loader: Condition "p_format_loader.is_null()" is true.
   At: core\io\resource_loader.cpp:539
Loading resource: res://alpaca_saver.gd
Loading resource: res://alpaca.gd
ERROR: It's not a reference to a valid ResourceFormatSaver object.
   At: core\io\resource_saver.cpp:161
```

**Comment by RandomShaper** [comment]
Probably due to #43225. I'l look deeper into it anyway.
