### ISSUE TITLE
Dropping obsolete platforms

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4347]
We currently have an important number of platforms in ``platform/``, but some of those have hardly been supported over the last two year, probably don't work and refer to somewhat obsolete technologies. Those would be:

- flash: @punto- hinted on IRC that this probably never really worked, it contains [nonfree files](https://github.com/godotengine/godot/blob/master/platform/flash/Console.as), and well, Flash should die and I'd be for not even suggesting that we might be working on it. So: **drop**.
- nacl: I don't know if anyone even tried to build it since the opensourcing. NACL itself is still being somewhat developed, but should we spend time on it or just ditch it [Waiting for WebAssembly™](https://hacks.mozilla.org/2016/03/a-webassembly-milestone/)? I'd propose to **drop**, but if others would like to keep it, why not.

Then we have:
- bb10: The personal favourite of @punto- AFAIK ;) I never tried to build it myself, but it seems BB10 is not 100% dead yet, so I guess we can keep it around until @punto- ditches his BB10 phone :p
- winrt: It might be somewhat broken nowadays because it hasn't been much worked on recently, but it should not be dropped, we need to add proper support for UWP.

WDYT? If there's no objection, I'd drop ``platform/flash`` and ``platform/nacl``.

**Comment by punto-** [comment]
winrt *is* UWP, so it might become a standard platform if it actually
succeeds in replacing win32. And it'll probably benefit from the angle
patch if we ever fix the gles2/webgl bugs

**Comment by akien-mga** [comment]
> winrt *is* UWP

That's why I said "should not be dropped, we need to add proper support for UWP" - inferring that the support we have currently is not complete, but we still do have something to work with :)

**Comment by vnen** [comment]
I agree in all points.

I tried to build for NaCl once, but failed. And since it's pretty much Google Chrome only, there's no much to gain if we keep it.

**Comment by slapin** [comment]
I'd drop anything which will not be supported or made work any time soon.
One can always resurrect the code from the repo, if needed.
Code not touched for several months is usually so rotten, that it is easier
to rewrite it if needed.
Cleaning the code is very important thing, less code - less bugs.
And less unfulfilled promises, which is good too.
