### ISSUE TITLE
"Narrowing conversion" warning is trigerred when it shouldn't

### ISSUE THREAD

**Issue by ktostam0** [godotengine/godot#43472]
**Godot version:**

3.2.3/3.2.4 beta v1

**OS/device including version:**

Linux x11

**Issue description:**

In GDScript when variable type hint is set to integer, and you assign it value using round(*some float*) the "Narrowing conversion" warning is triggered, while it is intended conversion.

**Steps to reproduce:**
See above.

**Minimal reproduction project:**
var a : int = round(0.25)

**Comment by akien-mga** [comment]
The warning is correct, `round()` returns a float (here `0.0`), so a narrowing conversion happens from float to int.

**Comment by ktostam0** [comment]
Then there isn't an issue, I just didn't expect it to actually return float. Sorry for the time taken.

**Comment by akien-mga** [comment]
See #19262, it's still on the table to maybe change it to return `int`, or add a `roundi` variant that does the conversion.

To silence the warning, you can cast to int explicitly: `int(round(0.25))`.
