### ISSUE TITLE
Texture errors provide no information

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#43475]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux

**Issue description:**
I am getting the following error. I have tried using '-v' at the command line, but there is nothing extra shown. There are errors loading a texture, but I have no idea what and Godot won't tell me. This happens on a new load of a project and I have. If it failed to load, surely it should be telling us what file it failed on given it failed trying to load a specific file?

Similarly, load every scene in the editor works just fine, it is only at runtime.

How do we get the information from debug that is required to trace this fault?

neil@MintNeil:~$ ERROR: _load_data: Condition "!f" is true. Returned: ERR_CANT_OPEN
   At: scene/resources/texture.cpp:502.

**Comment by Zylann** [comment]
Usually if I can debug this with a C++ debugger, I put a breakpoint in `_err_print_error` inside `error_macros.cpp`, or directly in the file shown in your error. I see the path should be available on the line above.

**Comment by chucklepie** [comment]
Thanks for the information.

Maybe this is a feature request then? But I and most people don't have the
debug/source version. Given you've said its available, can it be marked to
be included in the next release if somebody is good enough to update the
code?

I have about 150 scenes, 500 textures and about 75 animated sprites and
other resources that use textures so figuring it out is pretty hard unless
I bisect all my code and try to figure it all out 😉

**Comment by nazgum** [comment]
Ya I've just run into this, I did a fresh OS install and then pulled a copy of my game back from github, and now when I run it I get 3 error messages:

ERROR: Condition "!f" is true. Returned: ERR_CANT_OPEN
   at: _load_data (scene/resources/texture.cpp:466)

But I have literally thousands of image files that get loaded now, I have no idea where this is coming from, so really hard to try and figure out which images suddenly are failing to load

**Comment by akien-mga** [comment]
@nazgum I just cherry-picked #43490 for the `3.x` and `3.4` branches, so it should be included in 3.5 and 3.4.3.

**Comment by nazgum** [comment]
awesome thanks @akien-mga!! =)
