### ISSUE TITLE
Tileset Editor Toolbar not shown unless tile clicked/selected

### ISSUE THREAD

**Issue by monk-e-boy** [godotengine/godot#43489]
3.2.2

Win

Create a tileset. Then attempt to edit the tileset. The GUI/UX is very odd. Selecting a picture shows the associated tile, but none of the edit tools or toolbar:

![image](https://user-images.githubusercontent.com/17924807/99009708-5cccea80-2540-11eb-93a2-6f4db95d78ff.png)

Selecting the tile starts an edit, but also displays the associated edit toolbar:

![image](https://user-images.githubusercontent.com/17924807/99009726-68b8ac80-2540-11eb-9351-80edcb0150dd.png)

I think selecting the image, which causes the tile to display, should ALSO display the GUI

**Comment by Calinou** [comment]
Note that the TileMap and TileSet editors are being rewritten: https://github.com/godotengine/godot-proposals/issues/1769

**Comment by groud** [comment]
Closing as this enhancement is no more needed in master.
