### ISSUE TITLE
Docstring for Vector class is very confusing.

### ISSUE THREAD

**Issue by MadMcCrow** [godotengine/godot#43488]
**Godot version:**
master branch 

**OS/device including version:**
Not related

**Issue description:**
in `core/vector.h` , `PoolVector` has been replaced by `Vector` leading to this weird docstring :  
```
/**
 * @class Vector
 * @author Juan Linietsky
 * Vector container. Regular Vector Container. Use with care and for smaller arrays when possible. Use Vector for large arrays.
*/
```

**Steps to reproduce:**
Check `core/vector.h` 

**Minimal reproduction project:**
Godot Engine sources

**Fix step proposal** 
Confirm what class to use and either specify Vector are OK for large sizes or tell us to `Use PackedVector for large arrays`

**Comment by tetrapod00** [comment]
Fixed by https://github.com/godotengine/godot/pull/100147.
