### ISSUE TITLE
Adding a CollisionShape2D on an instanced Area2D in the editor does not work

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#4348]
**Operating system or device:**

Windows 10

**Issue description** (what happened, and what was expected):

In TestArea.tscn I have
```
TestArea (Area2D)
```

With script TestArea.gd:
```
extends Area2D

func _input_event(viewport, event, shape_idx):
	print(self.get_name())
```

If I add that to another scene main.tscn and add a CollisionShape2D to it:

```
Node2D
     -> TestArea (from TestArea.tscn)
               -> CollisionShape2D (added in main.tscn with rectangle shape) 
```

The CollisionShape2D doesn't seem to work and nothing is logged out.

I have attached an example project. To the left is an Area2D that was created in main.tscn. On the right is a TestArea loaded from TestArea.tscn
[collision_shape.zip](https://github.com/godotengine/godot/files/222613/collision_shape.zip)

**Comment by eska014** [comment]
The issue is the same as #2314, so let's use that one
