### ISSUE TITLE
Unexpected bone names because GLTF importer renames bones

### ISSUE THREAD

**Issue by geneishouko** [godotengine/godot#43482]
**Godot version:**
3.2.3

**OS/device including version:**
Debian unstable

**Issue description:**
The GLTF importer renames bones on import in a process called "sanitization". It works by converting the bone name to some snake_case pattern that also muddles numbers. It probably solves a corner case but I don't think it should be applied every time. The problem is that I have to access the skeleton bones programmatically and the importer gets in the way by altering the data (bone names) I know. 

I think an import option should be added to opt in to the bone name sanitization process.

**Steps to reproduce:**
* Run the reproduction project and move the slider. It will fail because the expected bone name in the script isn't the actual imported bone name.

**Minimal reproduction project:**
[GltfImporterRenamesBonese.zip](https://github.com/godotengine/godot/files/5533083/GltfImporterRenamesBonese.zip)

**Comment by fire** [comment]
This doesn't look that hard to do. How important is this for you?

**Comment by geneishouko** [comment]
It is very important because we rely a lot on bone manipulation with code not only animations. The current naming sanitization isn't guaranteed to remain constant and adapting our art library is very cumbersome. This is how we have [patched it](https://github.com/geneishouko/godot/commit/cf36cfb0e0451f146e4f1a9bc23c6b1154039738).

**Comment by fire** [comment]
Can you write a proposal and I'll discuss with others?

I'll argue for verbatium names by default, but wanted to hear other opinions. @marstaik

**Comment by marstaik** [comment]
There are some sanitizations that are required as they are not allowed to be in node names, IIRC.

The rest were to make injected fake bones consistent in the hierarchy, but I guess in practice it does not matter. We just have to enforce that the injected bone names are unique and make sense.

**Comment by fire** [comment]
Can you check this? 

https://github.com/godotengine/godot/pull/47074
