### ISSUE TITLE
cursor_set_line is not work

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#4349]
**Operating system or device:**
Arch Linux

**Issue description** (what happened, and what was expected):
I use TextEdit with ```set_readonly(true)``` and ```set_focus_mode(Control.FOCUS_NONE)```
After that cursor_set_line isn't work.

**Steps to reproduce:**
Create a scene, add TextEdit and write script... 
please see example project
I program with press key 0, 1, 2 or 3 for change cursor line.

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/s/qcwoxux8w2i4j48/testTextEdit.zip?dl=0

**Comment by neikeq** [comment]
Not a bug, TextEdit is just not redrawing. You must call `update()` after changing the cursor line:

``` GDScript

extends Node

onready var textEdit = get_node("TextEdit")

func _input(event):
	if(event.type == InputEvent.KEY):
		if(event.pressed):
			if(event.scancode == KEY_2):
				cursor_set_line(2)

func cursor_set_line(line):
	textEdit.cursor_set_line(line)
	textEdit.update()
```
