### ISSUE TITLE
GLES2/3 shadows does not work when Scene in viewport

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#43508]
look similar to other GLES2 shadow Issues
maybe this bug is known already, or this is not a bug and I missing something

**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux

**Issue description:**
![1](https://user-images.githubusercontent.com/24825887/99109046-4767c700-25f9-11eb-9993-44402daf9e41.png)
On top scene in Godot, other is the same scene in viewport(no shadows)

**Edit - look like it valid for GLES3 also.**

**Steps to reproduce:**
Add 3d scene to viewport.

**Minimal reproduction project:**
[GLES2_shadow_viewport.zip](https://github.com/godotengine/godot/files/5538758/GLES2_shadow_viewport.zip)

**Comment by Calinou** [comment]
Increase the directional shadow atlas size above 0.
