### ISSUE TITLE
Trying to close the editor settings' window while editing a big Visual Script file will cause the engine to crash

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#43521]
**Godot version:**

Godot v3.2.3-stable

**OS/device including version:**

- Windows 10 (64-bit) version (build) 2009 (10.0.19042).
- Intel® UHD Graphics 620 driver version 27.20.100.8935.
- GLES3

**Issue description:**

The engine will crash if I try to close the editor settings' window while editing a _big_ Visual Script file. And in the separated logging window, it shows "**Object was deleted while awaiting a callback**" messages indefinitely.

I can't reproduce this issue when trying to close the editor settings' window while editing a small Visual Script file or GDScript file.

[Here ](https://photos.app.goo.gl/dgWFFXTUyWmTH2it7)is my screen recording regarding this issue.

**Steps to reproduce:**

1. Open the big Visual Script file (Look.vs).
2. Open the editor settings' window.
3. Close the editor settings' window. And the engine will crash.

**Minimal reproduction project:**

[3D Targeting System.zip](https://github.com/godotengine/godot/files/5540140/3D.Targeting.System.zip)

**Comment by Calinou** [comment]
This is likely related to https://github.com/godotengine/godot/issues/35653 in one way or another. Try increasing the message queue size in the Project Settings. It will be larger by default in 3.2.4 thanks to https://github.com/godotengine/godot/pull/42296.

**Comment by kreaninw** [comment]
> This is likely related to #35653 in one way or another. Try increasing the message queue size in the Project Settings. It will be larger by default in 3.2.4 thanks to #42296.

Yes, I tested it. Changing the max message queue size to 4096 KB does fix this issue.

**Comment by kreaninw** [comment]
The default max message queue size has been changed to 4096 KB, as tested on 3.2.4 beta 3. The engine won't crash as described in this issue anymore.

I will close this issue as it is fixed.
