### ISSUE TITLE
C# AnimationPlayer.Play() uses a default parameter value of empty string for the animation name.

### ISSUE THREAD

**Issue by cjpdev** [godotengine/godot#43548]
**Godot version:**

2.3.2.stable

**OS/device including version:**

Windows 10

**Issue description:**

The play animation method is defined as:
``Play(string name="", float customBlend = -1, float customSpeed = 1, bool frontEnd  = false)``

But the `name` parameter is not optional, so if you forget to give a name : `Play()`, the compiler syntax checker and the mono IntelliSense will alow this to pass. Thus only when exectuted will the errors be raised.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by cjpdev** [comment]
Also: 
PlayBackwards(string name = "", float customBlend = -1f)

**Comment by object71** [comment]
The underlying C++ methods will use the playback.assigned for the name if no name is provided for the "name" parameter. You can use the SetAssignedAnimation to set the animation beforehand and then call Play with empty string.

This is not a bug.
