### ISSUE TITLE
GDScript 2.0 exported resource are cleaned out on save.

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#43542]
**Godot version:**
dd5485142f2d2d84b98483ea41bc36e03c4a16b7

**OS/device including version:**
Fedora 32

**Issue description:**
When you assign a resource, from the editor, to an exported variable: On save it's cleaned out.

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/8342599/99153264-b4399a80-26a7-11eb-8dc1-a2d8387fa1ae.gif)

This is how the exported variable is created:
```gdscript
extends Node

@export var variable: Resource
```

**Minimal reproduction project:**
[TestResource.zip](https://github.com/godotengine/godot/files/5541185/TestResource.zip)

**Comment by lyuma** [comment]
Tested on latest master 85186bc and it seems to save resources assigned to `Node` without issue when I save Node.tscn, so I'm going to close this.
@AndreaCatania  if you still encounter trouble, feel free to re-open this issue.
