### ISSUE TITLE
Misplaced highlight for completion option match

### ISSUE THREAD

**Issue by gvekan** [godotengine/godot#43551]
**Godot version:**

v4.0.dev.custom_build.9e7348f78

**OS/device including version:**

Windows

**Issue description:**

The highlight on what is matching between completion options and the written word is always placed at the beginning with the same length as the written word, thus only correct for options that begins with the word and not for other substrings or subsequences that also is shown in the list.
![completion](https://user-images.githubusercontent.com/25207137/99180364-e12c9280-2725-11eb-9928-f4c4203fc3e4.PNG)
Only the highlight for `load` is correct here.

**Steps to reproduce:**
For example, write `load` and look at the completion options list.

**Minimal reproduction project:**

Any.

**Comment by gvekan** [comment]
@YeldhamDev I'm curious about the labels, what makes this an `enhancement` and not a `bug`?
In _v3.2.3.stable.official_:
![Skärmklipp](https://user-images.githubusercontent.com/25207137/99223656-38de0300-27e5-11eb-8a36-0d18f3bf52fe.PNG)
I would say that the issue is a `bug` because of an merged `enhancement` in _v4.0_ that makes it show subsequences as options. This would probably also make it an `regression`.
But if I write something that nothing begins with in _v3.2.3_:
![Skärmklipp2](https://user-images.githubusercontent.com/25207137/99224017-d20d1980-27e5-11eb-9f3c-0f838f49ed4e.PNG)
The issue is the same for _v3.2.3_. If the highlight is supposed to only show the length of the written word I would say that it's an `enhancement` but if it's not, I'm guessing there's no label for a partially misused component? :)

**Comment by YeldhamDev** [comment]
That original code that handles the highlighting seems to be working as intended, even if the implementation was very short sighted. It was more of a poorly implemented enhancement rather than a bug/regression.
