### ISSUE TITLE
StreamPlayer Loop Restart Time not a float but int in inspector

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#4355]
**Operating system or device:**
Windows 10 Pro, Godot 2.0.2 stable

**Issue description** (what happened, and what was expected):
The StreamPlayer class provides the float property "Loop Restart Time" and corresponding functions to get and set the value. The value specifies the time in seconds at which a looping stream is rewound to. The inspector erroneously displays it as an Integer property, and thus makes it very inexact / useless. A script which uses set_loop_restart_time(float) to properly set a float value for it is the only workaround.

**Steps to reproduce:**
Create a StreamPlayer. Try to set a float value for "Loop Restart Time" in the inspector. Since the field is an Integer there, it will be rounded to the next Integer, setting the loop time exactly is impossible without a script.

**Comment by Alex-doc** [comment]
Looks like [it happens here](https://github.com/godotengine/godot/blob/d454e64f429affb89de036eed6daa5c6e5278492/scene/audio/stream_player.cpp#L391)

I think setting it to `Variant::REAL` should work though...

**Comment by RayKoopa** [comment]
Yep! The property works flawless other than the inspector display fault.
I'd fix it, but I'm not feeling safe enough on GitHub yet and better let the pro's do that ;)

**Comment by Alex-doc** [comment]
Now going to test!
