### ISSUE TITLE
Godot 3.2.3 GLES3 handles transparency wrong

### ISSUE THREAD

**Issue by nerdnils** [godotengine/godot#43559]
I have a viewport inside of a Viewportcontainer or I can use the texture of this viewport in a TextureRect it does not matter.
Parallaxbackground having a sprite used as background for everything. So this Viewport has transparency set on. Everything where transparency should be is 100% pure black. When adding a CanvasItemMaterial I can see this only happens on Blend Mode Mix. Add and Sub handle the transparency right. But that way the colors are off. When switching to GLES2, the transparency is handled right, no black.

Second issue I found: when using the texture as texture for TextureRect, VFlip is upside down/works the other way around.

**Godot version:** 3.2.3

Archlinux 5.4.77-1-lts

NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]

**Comment by Calinou** [comment]
@nerdnils Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
@nerdnils Can you (or anyone else) still reproduce this bug in [Godot 3.5](https://godotengine.org/article/godot-3-5-cant-stop-wont-stop) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
