### ISSUE TITLE
Tween.seek() fails to set the interpolation time

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#43568]
**Godot version:**
v3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
The seek function is supposed to "Sets the interpolation to the given time in seconds.", it does not seem to work and instead pu the Tween in an unpredictable behavior.

**Steps to reproduce:**
Create a Tween, add some interpolation, try to seek.

**Minimal reproduction project:**
[TweenSeekTest.zip](https://github.com/godotengine/godot/files/5542705/TweenSeekTest.zip)

**Comment by KoBeWi** [comment]
`seek()` no longer exists after Tween rework. Also given the way interpolaters work, such method is not easy to implement, so the fact that it was bugged is no surprise.

**Comment by avnerh1** [comment]
> `seek()` no longer exists after Tween rework. Also given the way interpolaters work, such method is not easy to implement, so the fact that it was bugged is no surprise.

seek() needs to be removed from documentation.

**Comment by KoBeWi** [comment]
`seek()` still exists in Godot 3. It was removed in 4.0.

**Comment by avnerh1** [comment]
> `seek()` still exists in Godot 3. It was removed in 4.0.

But according to this bug, it doesn't work in Godot 3.

**Comment by KoBeWi** [comment]
That's not a reason to remove it from documentation.
And we can't remove it at all either, because that would break compatibility. At most, the documentation could be updated to state that the method might not work as expected.
