### ISSUE TITLE
Viewport appears to work only if is a child of Control Node

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#4356]
It appears viewport only works if you add it as a child to a Control Node (thanks for hetdegon for figuring this out). So if I place viewport under any other node nothing happens just a black screen. Also the control needs to be set to width and height of the viewport. 

This deff seems like a hack and a bug and hardly appears intentional. 

edit: seems it may be intentional?? This was not documented anywhere.  

And even if you do that  to get the viewport working you will still get the issue described in #1840  Seems the viewport doesn't know how to zoom in and out with the rest of the editor and will just flood the entire editor screen instead.

**Comment by eska014** [comment]
You can use viewports as a render target texture to use them outside Control nodes. Check the docs: http://docs.godotengine.org/en/latest/tutorials/engine/viewports.html

**Comment by trollworkout** [comment]
@eska014  seems the control feature is intentional and seems to be in the docs . i should have read them better. sorry i was just confused how it works.
