### ISSUE TITLE
Setting RayCast cast_to value in _physics or _physics_process causes lag spike.

### ISSUE THREAD

**Issue by Andy-Hamm** [godotengine/godot#43571]
**Godot version: 3.2.3**

**OS/device including version: Microsoft Windows 10 Pro Version: 10.0.18363 Build 18363**

OS Name: Microsoft Windows 10 Pro
Version: 10.0.18363 Build 18363
System Type: x64-based PC
Processor: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz, 3501 Mhz, 4 Core(s), 4 Logical Processor(s)
GPU: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Version: 27.21.14.5730

**Issue description: Setting RayCast cast_to value in _physics or _physics_process causes lag spike.**

When I update a RayCast cast_to value it causes a lag spike.
![RayCast Lag Test Result 2](https://user-images.githubusercontent.com/74505545/99192443-e3e8b100-2740-11eb-9879-f8dd8cc8e994.png)

**Steps to reproduce:**
Created Spatial node.
Add RayCast node as child.
Add this script to Spatial node:

```gdscript
extends Spatial
func _physics_process(_delta):
	var start = OS.get_ticks_usec()
	if Input.is_action_just_pressed("ui_accept"):
		print("Start Test")
	if Input.is_action_pressed("ui_accept"):
		get_node("RayCast").cast_to = Vector3(0, 0, 1.5)
	var end = OS.get_ticks_usec()
	var time = (end-start)/1000000.0
	print(time)
```

I tested on GLES3

**Minimal reproduction project:**

[RayCast Lag Test.zip](https://github.com/godotengine/godot/files/5542839/RayCast.Lag.Test.zip)

**Comment by pouleyKetchoupp** [comment]
For info, the lag only occurs when collision debug shapes are enabled, because it updates the raycast render debug when `cast_to` is changed.
