### ISSUE TITLE
Animation Transitions are not interruptable

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#43570]
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

Win10

**Issue description:**

AnimationTrees allow for blending animations which is important for good looking motion. Sometimes longer transitions need to be used to allow a variety of animations to match up with each other well.
The problem is that transitions (the blending) cannot be interrupted and currently play until done, which makes certain animation types look wrong, for example falling to moving, where small height differences usually start the falling animation, but the immediate switch to grounded typically cancels it and resumes grounded animation. But currently the falling transition takes over and animates the character until the falling pose, even if the initial state is traveled to immediately again.

Edit: It looks like it's the same with manually calling the AnimationPlayer and blend duration as parameter.

See this video with exaggerated transition time:
https://streamable.com/a1vsjp

**Comment by Flavelius** [comment]
It looks like it's the same with manually calling the AnimationPlayer and blend duration as parameter.
The expected outcome would be using the blend duration of the last Play call which equates to the AnimationTree's xfade time of the transition to the target node.

**Comment by TokageItLab** [comment]
@Flavelius If there are more than two state transitions, i.e. no return to the start state, are the transitions working correctly?

**Comment by Flavelius** [comment]
@TokageItLab Unfortunately it's the same:
![colcClpjqc](https://user-images.githubusercontent.com/8841352/106253691-18d0b400-6218-11eb-8097-e82ac6d537cd.gif)

**Comment by TokageItLab** [comment]
@Flavelius Is it mean you want to use PlayMode Immediately from Script easily?

**Comment by Flavelius** [comment]
Sorry, i don't understand that question.
The problem here is, when animations are forced to complete their blending, they cannot be interrupted. 
Imagine a transition from jumping to falling where the ground beneath the character is actually just a very small hole, so the character immediately is grounded again. 
Currently with this bug, the character completes his falling animation transition forcibly until he plays the grounded animation again, which looks silly and wrong.
There's the possibility that i just misunderstand the 'Immediate' mode of transitions, and that this option is unrelated to 'actually immediately blending' and is just a way to not wait until the end of the animation clip length.
If that's the case then transitions definitely need an option to make them interruptable (like in unity), to be able to produce intended transition visuals.

**Comment by TokageItLab** [comment]
The immediate mode is to run the next Transition at the end of the Xfade of the previous Transition, and the AtEnd mode is to run the next Transition at the end of the animation. In other words, the problem is that it is not possible to abort a Transition and start a new Transition, which is a lack of functionality and not a bug.

**Comment by Flavelius** [comment]
Ok, i began expecting that this is the case. That's unfortunate. I'll create an improvement proposal

**Comment by TokageItLab** [comment]
Yes, I agree with the implementation of that feature. I'll keep this in mind as I'm one of the contributors trying to improve the animation feature.

**Comment by Flavelius** [comment]
https://github.com/godotengine/godot-proposals/issues/2200
