### ISSUE TITLE
Project settings window; do not expose settings that likely lead to bugs or other issues.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4357]
The reason I opened this issue is because I just found one setting that can be a potential troublemaker when it comes to being able to debug and monitor a project.
![godot_donottouch](https://cloud.githubusercontent.com/assets/10081256/14589644/e96a5374-04ac-11e6-8f44-b51d6101cd25.png)

The setting highlighted in the image is exposed to the user for whatever reason, but if you set it to a different value, you can potentially cause the debugger and info windows to stop working after saving the project and closing/reopening (changing it back likewise makes everything work again). Good thing too since working on my project was slow without error reporting and prints.

My suggestion is that the developers work to remove the exposure of various technical functions that are likely to cause bugs and development trouble if they are changed at all. For instance, I would at least keep the _message queue-size_ parameter in the **core** category because an increase in that value is needed if you are to have large scenes, but there's others that appear to be so technical that only a C++ coder might actually know what they are and what they do (and if a user who only knows GDscript messes with them, who knows what issues will crop up).

Thoughts?

**Comment by Gastronok** [comment]
I would very much prefer that the options were left exposed.

If I don't know what something does, I probably won't mess with it, or at least I won't be surprised when I don't anticipate its results. But later I may find out what it does and that I have a use for it.

On the other hand, nothing is more frustrating than when I know exactly what is wrong but don't have the ability to do anything about it. It's why a lot of people prefer UNIX over Windows. Sure you have the ability to royally mess things up, but without that level of power you'd also be limited in how clever and inventive you could be.

The argument also generalizes poorly. The current implementation of atan2 will likely lead to bugs or other issues. I suspect many developers would be upset if atan2 were removed; we rely on it for geometric calculations.

**Comment by Ace-Dragon** [comment]
As far as I know, the atan2 function is a GDscript function and is not part of what I'm talking about.

What I'm talking about is the parameters you can set in the project settings window and how changing some of them may not readily do anything other than create issues (that one might have a lot of trouble figuring out as to its cause).

Sure, we can say we don't mess with something if we don't know what it is, but that logic can also be used to advocate the idea that we should expose _everything_ in the Godot source on the off chance someone "might" want to change it (sure, it will only add a lot of unneeded clutter to the window and make it difficult to find what we need, but we don't need to mess with it).

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.

**Comment by akien-mga** [comment]
For the reference this is mostly address by #21795 / #22779.
