### ISSUE TITLE
Android build succeeds even if the keystore credentials are wrong 

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#43580]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
I created an Android keystore using Android Studio and configured it to be used by my Godot project via the Export Settings. I noticed that if you use wrong keystore credentials (either `user` or `password`) the export still suceedes (both release and debug). It even creates an APK file. There are **no** error messages or warnings.

If i try to install the generated APK using `adb` i get this error message:
```
adb: failed to install D:\Test.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates 
from /data/app/vmdl544102076.tmp/base.apk: Attempt to get length of null array]
```

If i use the quick build+install button on the top right corner of the editor the the build succeeds but the install silently fails.

**Steps to reproduce:**
1. Create a keystore in Android Studio and configure a Godot project to use that keystore using wrong credentials
2. Export an APK -> successfully creates an APK
3. Quick install with connected device -> silently fails

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/18222 (which is a similar issue, even if the underlying cause is different).

**Comment by mbrlabs** [comment]
Alright, the signing process here goes wrong:
https://github.com/godotengine/godot/blob/d191ffe647b5074bd939f6289957f1610159a31d/platform/android/export/export.cpp#L2235-L2240

The command should return a `value != 0` in case the signing failed but `retval` is 0 here (signing still failed based on the verbose output of the command). However if i execute the exact same command in the Windows Powershell and print the last error code using `echo $LASTEXITCODE` i get 1. 
So i think somehow the retrieval of the error code of the OS call to the `jarsinger` executable is buggy.

I don't have access to my Linux machine now, but it would be intersting to check if this also happens on Linux.

**Comment by mbrlabs** [comment]
Yes! I'm now certain that this is an issue in the Windows implementation of `OS:execute()`.

If you call it like this with a pipe parameter the return code will be returned correctly:
```
 int retval; 
 String pipe;
 OS::get_singleton()->execute(jarsigner, args, true, NULL, &pipe, &retval); 
```

As you can see when using a pipe for the output the implementation takes a completly different code path:
https://github.com/godotengine/godot/blob/e5dfb9b25e128d88a4628f82d22fddf3046de75a/platform/windows/os_windows.cpp#L414-L484
