### ISSUE TITLE
Imported model with skeleton doesn't have bones

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#43585]
**Godot version:**
3.2.3

**OS/device including version:**
Nvidia GTX 650
GLES3

**Issue description:**
When importing a rigged mesh bones are not there making it impossible to animate 3d meshes in Godot
![image](https://user-images.githubusercontent.com/2453707/99215001-8c6d3400-2786-11eb-9fdc-339688f061ab.png)

**Steps to reproduce:**
- Download this https://drive.google.com/file/d/1XkMuPJgxxr_0qq4OxpaE56BBpUyKOQAD/view?usp=sharing
- Import it in godot
- Make new inherited scene
- See that bones are not there

**Minimal reproduction project:**
[Bug-ModelBones.zip](https://github.com/godotengine/godot/files/5544253/Bug-ModelBones.zip)

**Comment by smix8** [comment]
The Bones are found in the Skeleton Node and not in your "Armature" Spatial Node. Click on the Skeleton Node and you see all the Bone values in the Inspector Window.

The "Armature" named Spatial Node is just a relict from the import process. In fact all 6 Bones of your 3d model are included in the Skeleton Node. Your imported Animation track for the Leg.L Bone is playing and the models leg is moving.

It wouldn't make a difference here but if you encounter other issues with 3d exports better not use the ancient Collada .dae file format. Use glTF2.0 or the Godot Blender Exporter Addon for your 3D exports from Blender.

**Comment by fire** [comment]
The skeleton node contains the bones.

I'll close the issue in a few moments.

**Comment by Shadowblitz16** [comment]
@fire but they are not visible or draggable making animation impossible

**Comment by Calinou** [comment]
@Shadowblitz16 There's an open proposal for that: https://github.com/godotengine/godot-proposals/issues/584
