### ISSUE TITLE
Deleting indentations reduces the size of the exported projects but only sometimes?

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#43584]
**Godot version:**
3.2.2

**OS/device including version:**
MX Linux always updated
i5-2520M

**Issue description:**
I'm not 100% sure if this is a bug but it's kind of odd.
I noticed that the filesize of my exported project decreases sometimes when I delete indentations or whole lines that had only indentations in them but not every time and I was wondering: Why are indentations making the exported projects bigger, shouldn't they not adding to the file size when the game is exported? And why isn't it always the case? It's only a couple of bytes but in a big project this could add up a bit. I exported only for Linux, maybe this is specific for Linux. Working with GDScript. Exported without Debug.

**Steps to reproduce:**

Delete unnecessary indentations in a project or add some and test it multiple times.

**Minimal reproduction project:**
[Indentations.zip](https://github.com/godotengine/godot/files/5543599/Indentations.zip)

**Comment by Calinou** [comment]
In general, I'd always recommend trimming trailing whitespace from your scripts. It will also give you better diffs in version control. You can enable **Trim Trailing Whitespace** in the editor settings to do that automatically.

**Comment by Daniel-da-Silva** [comment]
Thanks, didn't knew that - but it's still pretty weird that it is so inconsistently?

**Comment by Calinou** [comment]
Scripts are included as text files, which is why trailing whitespace will impact your game's exported PCK size.

**Comment by Daniel-da-Silva** [comment]
Thanks 👍

**Comment by Calinou** [comment]
Indeed, files are stored as *blocks* on the filesystem. This block size is often 4 KB with today's partition sizes, which means a file will always use up space in increments of 4 KB, even if the file in question is smaller.

This is why Windows exposes two file size metrics in a file's Properties dialog: "Size" and "Size on disk". The former is the actual file size, whereas the latter is the "physical" file size that takes the block size into account.

**Comment by Daniel-da-Silva** [comment]
For me it shows it down to a couple of bytes on MX Linux. But I don't know the exact increments there. But it's less than 4kb
