### ISSUE TITLE
on_body_entered detecting body which is not on its mask layer, also print(body.collision_layer) returns 2147483649 

### ISSUE THREAD

**Issue by Scriptering** [godotengine/godot#43594]
**Godot version:**V3.2.3.stable.official

V3.2.3.stable.official

**OS/device including version:**

Windows 10
64 bit

**Issue description:**

Setup an Area2D to detect when the player entered into range of an enemy "bat", set the Area2D mask to the player layer, but it would also detect the bat, which was on a different layer. After getting it to print(body.collision_layer) it returned 2147483649, which seems to be 2^31, but infact the bat was on Layer 1.

**Steps to reproduce:**
[_body_entered bug.zip](https://github.com/godotengine/godot/files/5548371/_body_entered.bug.zip)
I am not sure how you would reproduce this from scratch, but just from running the bat scene you can see the problem.

**Minimal reproduction project:**

[_body_entered bug.zip](https://github.com/godotengine/godot/files/5548371/_body_entered.bug.zip)

**Comment by qarmin** [comment]
This should be fixed by https://github.com/godotengine/godot/pull/42733, which you can try with Godot 3.2.4 beta.
This value, you need manually reset to correct value(or 0) inside this `tscn` file
