### ISSUE TITLE
Multiple same scene instances in different viewport causing duplicated objects

### ISSUE THREAD

**Issue by edreal** [godotengine/godot#43596]
**Godot version:**
3.2.3

**Issue description:**
In the example project there is multiple viewports so I can have multiple instances of the same scene.
The scenes _ready function will create scene instance which has kinematic body with collider, adds it to scene and starts moving it. I used randf to create the velocity vector, I am not sure exactly why it makes them appear apart but if I remove that line, the box will start moving left really fast for some reason (I assume its something to do with collisions since it didn't happen when I moved object by changing its transform.origin)

When I have both of the viewports it looks like the box is duplicated in each scene instead of one box per scene.
![bug](https://user-images.githubusercontent.com/35248192/99294324-96596a80-284c-11eb-9241-083ade79c9fa.png)

Here is what I see when I removed the second viewport which is as expected.
![nobug](https://user-images.githubusercontent.com/35248192/99294359-a2ddc300-284c-11eb-8436-f06753a7379a.png)

Am I doing something wrong or is this a bug?

**Comment by smix8** [comment]
You are using a shared 3D World Resource. You may have different Views on this World but all your TestScene Instances are placed in the same space. What you can do is to use different "World" Resources on the Viewport's and toggle on "own_world" or you can use different visuallayers for your objects and cull_masks for the cameras so one viewport doesn't capture the content from the other viewport.

**Comment by edreal** [comment]
@smix8 Thanks! That indeed solved the issue. I guess this isn't a bug after all then.
