### ISSUE TITLE
Can't create Callables with Callable(object, method) constructor

### ISSUE THREAD

**Issue by OragonEfreet** [godotengine/godot#43604]
**Godot version:**
fbe0386c653615a373e45af1ebe027c83b924d33

**OS/device including version:**
OS: Ubuntu 20.04.1 LTS x86_64
GPU: Intel Iris Plus Graphics G7
Built Godot with -j8 platform=x11 target=release_debug

**Issue description:**
Upon running the following script, the programs stops with the error 
```
SCRIPT ERROR: Bug, call error: #681396112
          at: SomeNode._ready (res://Node.gd:6)
```

```gdscript
class_name SomeNode # Will crash may I have this line or not
extends Node


func _ready():
	var f = Callable(self, "my_function") # Crashes here
	
func my_function():
	print("nothing")
```

**Steps to reproduce:**
- Create a new Project
- Add a Node2D or any node inheriting from it
- Attach a new script
- On any running code, create a callable to a local function
- Run the project

_I tried with a `Node` instead of `Node2D` and it does not crash (though I did not test the Callable worked in itself)_

**Minimal reproduction project:**
[CallableError.zip](https://github.com/godotengine/godot/files/5550034/CallableError.zip)

**Comment by OragonEfreet** [comment]
I got this error as I wanted to make a signal/slot connection:
```
class_name InteractionArea
extends Area2D

var _on_interacted_slot

func _ready():
	_on_interacted_slot = Callable(self, "_on_interacted") ## BOOM!

func _on_InteractionArea_area_entered(area):
	area.connect("interacted", _on_interacted_slot)


func _on_InteractionArea_area_exited(area):
	pass

func _on_interacted():
	pass
```
If an alternative is available for an equivalent result, i'd be glad to know that :smile_cat:

**Comment by KoBeWi** [comment]
> If an alternative is available for an equivalent result, i'd be glad to know that 😸

Just use `_on_interacted` instead of `Callable(self, "_on_interacted")`

**Comment by Calinou** [comment]
Related to #36444.

**Comment by hungrymonkey** [comment]
```
Registered camera FaceTime HD Camera (Built-in) with id 1 position 0 at index 0
SCRIPT ERROR: Parse Error: Expected ',' or ')'
          at: GDScript::reload (built-in:19)
ERROR: Method/Function Failed, returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:560)
SCRIPT ERROR: Parse Error: No constructor of 'Callable' matches the signature 'Callable(self, String)'.
          at: GDScript::reload (built-in:18)
```
<img width="1792" alt="Screen Shot 2021-02-22 at 6 14 42 AM" src="https://user-images.githubusercontent.com/771339/108721721-302d5500-74d7-11eb-9e61-72fa10266645.png">

**Comment by akien-mga** [comment]
@hungrymonkey You don't have to create a callable manually here, `compare` *is* a Callable.

**Comment by hungrymonkey** [comment]
<img width="1792" alt="Screen Shot 2021-02-22 at 6 37 46 AM" src="https://user-images.githubusercontent.com/771339/108722911-80f17d80-74d8-11eb-8de1-3150f6def46a.png">

Oh, I already tried that.

**Comment by akien-mga** [comment]
Works here:
![Screenshot_20210222_153928](https://user-images.githubusercontent.com/4701338/108723112-31d13a00-7524-11eb-9645-ce68c17af2ea.png)

Your `master` branch build is likely outdated.

**Comment by hungrymonkey** [comment]
I will recompile it. My master branch was created like a week ago.

**Comment by KoBeWi** [comment]
Works fine in b283447
