### ISSUE TITLE
How to set font for Hint/Tooltip?

### ISSUE THREAD

**Issue by hunar1997** [godotengine/godot#43609]
**Godot version:**
Latest release: 3.2.3 stable official

**OS/device including version:**
Windows10/Windows7/Linux Manjaro

**Issue description:**
I set the font for a specific button, and the text on it uses that font without problems, but the hint(Tooltip) isn't using it, i tried changing the editor font but it didn't affect it. I said button but i also tired textedit, I think its general

Normally this isn't a problem but I was experimenting with using Kurdish-Sorani characters and they don't appear at all without font

**By the way**
How is the progress on BiDi/RTL support?

**Another question please**
I tried fixing the flipped&disjoined Kurdish (or Arabic /Persian/etc...) characters by writing a script that converts them on the fly, Like this:

* writing سڵاو in the editor results in و‌ا‌ڵ‌‌س
* So when printing, my script first flips it س‌ڵ‌ا‌و
* Then based on context replace the standalone characters with their respective joined versions ﺎوﺳ here is the problem, that ڤ (It isn't he only one) character version which my browser cant render is Private use (according to windows Character Map), it should look like
![Capture](https://user-images.githubusercontent.com/14861276/99361943-e6274880-28c3-11eb-8ca0-b08698c8946b.PNG)

No problem though since I just need to use the correct font
**BUT My Actual Problem** is that godot does not accept this character at all, i try putting it in the code editor and it throws (Parser Error: Parse error: Unknown character)

[That character](https://www.fileformat.info/info/unicode/char/e009/index.htm) is a 3 byte utf-8, is there a fundamental problem here? Godot doesn't accept the full Unicode characters?

Thanks

**Comment by akien-mga** [comment]
See https://godotengine.org/article/complex-text-layouts-progress-report-1 and https://godotengine.org/article/complex-text-layouts-progress-report-2.

This work is being done for Godot 4.0 and can't be backported to the 3.2 branch.

You can try @bruvzg's [libgdtl](https://github.com/bruvzg/godot_tl) for the 3.2 branch, which supports and subset of what's being implemented for Godot 4.0, and can be used as a C++ module (if you build the engine yourself) or GDNative plugin (check the "Releases" page).

**Comment by akien-mga** [comment]
Regarding the question on setting the font for tooltips, you have two options:

- Change the `font` theme item for `TooltipLabel` in your Theme resource. See the recently written documentation about this (not online yet): https://github.com/godotengine/godot/blob/d0a5ef9c7a79e24ec04643ee629f952b4077e6fe/doc/classes/Control.xml#L848-L859 (see `Label` documentation for a list of its theme properties, which are the same for `TooltipLabel`).
- Make your own custom tooltip with `_make_custom_tooltip`:
https://github.com/godotengine/godot/blob/d0a5ef9c7a79e24ec04643ee629f952b4077e6fe/doc/classes/Control.xml#L60-L85

That being said, this is an issue tracker for *bug reports*, and not for user support. Such questions would be best asked and answered on the [Godot Q&A](https://godotengine.org/qa/).
