### ISSUE TITLE
GDScript 2.0 Custom class scripts cant access properties of super class

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#43600]
**Godot version:**
Godot Engine v4.0.dev.calinou.e16729a8c 

**OS/device including version:**
Windows 10

**Issue description:**
Godot crashes when trying to access e.g. global_transform, when creating a script from a custom class that extends Node3D.
Also, creating custom variables in the custom class, they print out as "null" when extending the class. When trying to use "super.global_transform", it expects a function call, so it does not work either.

![image](https://user-images.githubusercontent.com/15088582/99299246-3e6e3400-284b-11eb-84bd-afe1fedaaea7.png)

![image](https://user-images.githubusercontent.com/15088582/99299285-50e86d80-284b-11eb-8429-88527f30bdfb.png)

**Steps to reproduce:**
Create a custom class "Node4D", that extends Node3D. Create a new script that extends Node4D, and try to print global_transform.

**Minimal reproduction project:**
[Gdscript super property.zip](https://github.com/godotengine/godot/files/5549240/Gdscript.super.property.zip)

**Comment by lyuma** [comment]
Seems fixed on latest godot master 85186bc
```
4
5
[X: (1, 0, 0), Y: (0, 1, 0), Z: (0, 0, 1), O: (0, 0, 0)]
4
[X: (1, 0, 0), Y: (0, 1, 0), Z: (0, 0, 1), O: (0, 0, 0)]
```
Closing the issue
