### ISSUE TITLE
ERROR: Condition "rb == nullptr" is true, when using 3D nodes

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43624]
**Godot version:**
4.0.dev.custom_build. dd5485142

**Issue description:**
When I use 3D nodes then sometimes this error is shown
```
ERROR: Condition "rb == nullptr" is true.
   at: _setup_giprobes (servers/rendering/rasterizer_rd/rasterizer_scene_rd.cpp:1404)
```

**Steps to reproduce:**
1. Run scene https://github.com/qarmin/RegressionTestProject/blob/master/MainScenes/Spatial.tscn from reproduction project

**Minimal reproduction project:**
https://github.com/qarmin/RegressionTestProject/

**Comment by clayjohn** [comment]
I remember this being a common error, but it seems to have gone away over the last two years. The render buffer implementation has changed substantially in the meantime, so this issue is no longer relevant anyway.
