### ISSUE TITLE
Attempted to free invalid ID: 0 Error when opening 3D scene

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43628]
**Godot version:**
4.0.dev.custom_build. dd5485142

**Issue description:**
When opening editor this error is shown:
```
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:6949)
```
This error comes from 
![Zrzut ekranu z 2020-11-17 22-52-04](https://user-images.githubusercontent.com/41945903/99455177-c6297080-2927-11eb-870c-4a73ce06f589.png)

**Steps to reproduce:**
1. Open scene `ALL.tscn` from minimal file

**Minimal reproduction project:**
https://github.com/qarmin/RegressionTestProject/archive/master.zip

**Comment by akien-mga** [comment]
I guess it just needs a check to validate if `rb->gi_uniform_set` is valid before freeing it? Most likely `giprobes_changed` is true when changing from "no setup" to "initial setup" which has this line fail.

**Comment by clayjohn** [comment]
Ya that's right. It should be done the same as the lines just below.
