### ISSUE TITLE
Polygon2D UV results are unusual for convex polygons in the editor.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#43637]
**Godot version:**

04103db

**OS/device including version:**

Win10 64-bit GeForce GTX 1660 SUPER/PCIe/SSE2

**Issue description:**

The shader UV of a convex Polygon2D has strange results in the editor.  Both in GLES2 / GLES3.  Appears to be applying to all the sub-polygons.

When selecting the polygon and scrolling the inspector the UV results will also change rather wildly.  This seems to be only when not using a texture, and editor side only.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/13004169/99511091-7d59d200-2990-11eb-9c19-9c9d42cec875.gif)

Appears fine when running:
![godot windows tools 64_D87ugTdMsD](https://user-images.githubusercontent.com/13004169/99511128-88acfd80-2990-11eb-9950-444d2beb51e2.png)

Noticed old versions and the master don't have anything like this for Polygon2D, it's just black.

![godot_N84d9U76jP](https://user-images.githubusercontent.com/13004169/99511814-69fb3680-2991-11eb-9a05-42dfb6ee4876.png)

@lawnjelly A minor issue, and recent, but not sure where to categorize this one.  Probably doesn't go in any of the batching threads.

**Steps to reproduce:**

1. Use the shader code below on a convex Polygon2D.
2. Initial results should be on internal polygons.
3. Selecting the Polygon2D and scrolling the inspector can case the values to flutter.

```
shader_type canvas_item;

void fragment() {
	
	COLOR = vec4(UV.x, 0.0, 0.0, 1.0);
}
```

**Minimal reproduction project:**

[Polygon2D Shader Issue.zip](https://github.com/godotengine/godot/files/5559065/Polygon2D.Shader.Issue.zip)

**Comment by lawnjelly** [comment]
Yes I think this will be because a polygon with no texture is not setting the UVs (as they are assumed to be unused), so they are just whatever is left in the buffers. I'll take a look.

**Comment by akien-mga** [comment]
Fixed by #43642.

Will be included in 3.2.4 beta **3**.

**Comment by avencherus** [comment]
@lawnjelly Oh these don't have UVs unless a texture is assigned the Polygon2D?  Seems a bit weird, but I guess to just draw colors the work around is to put some dummy texture on it.

![image](https://user-images.githubusercontent.com/13004169/99540543-4eefed00-29b8-11eb-810e-17f38d8662f3.png)

**Comment by lawnjelly** [comment]
Yeah, each poly command has a list of uvs, and it seems with no texture the number of UVs is less than the number of indices (presumably zero UVs, I didn't check this).

I already had a 'last ditch' check for reading a UV outside the bounds of the UV list to prevent crashing in such a scenario, not realising that it might be standard to not include UVs with no texture.
