### ISSUE TITLE
Tooltips for variables retain value after ending Debug session

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#4363]
When setting a breakpoint to see some variable values in tooltips that appear when you hover the mouse over them, they work as intended. But it is weird that they still show the same values after ending (stopping) debugging when hovering the mouse over them.

It is kind of misleading since I though I changed their values somewhere in script. Which I didn't.
It is a minor issue though, tooltips need to be reset to their original values after ending debug session.

This happens even on the latest dev build as of writing this.

**Comment by reduz** [comment]
This was added because users complained that debug state was lost after a crash or disconnection, so it's a feature, not a bug.

**Comment by reduz** [comment]
I guess if enough users complain to remove it, we can remove it.. I don't know :P
