### ISSUE TITLE
Regression in GLTF import, unsupported images fails the import

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#43638]
**Godot version:**
3.2.4
commit 61c8efecffd52953da621566df2033ecce0710d5

**OS/device including version:**
Any

**Issue description:**
The GLTF files in the openvr repo found here: https://github.com/GodotVR/godot_openvr/tree/master/demo/addons/godot-openvr/meshes are no longer importing. They contain a couple of images in GIF format that are not supported. Previous versions would give a warning but the new version is erroring out:
```
ERROR: EditorSceneImporterGLTF::_parse_images: glTF: Got image data with an unknown URI data type: data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=
   At: editor\import\editor_scene_importer_gltf.cpp:1313
WARNING: PNGDriverCommon::check_error: Not a PNG file
```

As a result the GLTF file has become unusable:
![image](https://user-images.githubusercontent.com/1945449/99515155-b457d400-29e0-11eb-99db-c9b9ff60a5d9.png)

As many assets will be obtained from 3rd parties having small issues like these are not uncommon. They are easily dealt with by updating the materials within Godot. In the above case we're using these "slim" low resolution versions of the GLTF file because the version that does include the proper textures is 36Mb per hand, while we only need the textures once. The correct textures are thus stored alongside the model and the material resource is edited accordingly.

**Steps to reproduce:**
Create a project and try and use the GLB files included in teh link before

**Minimal reproduction project:**
See godot_openvr repo mentioned above.

**Comment by akien-mga** [comment]
It's not a bug, these files are broken. You should tell Valve to remove the embedded GIF, and remove it from the versions used in the OpenVR module.

Still, I'll add a hack but users will complain about the (correct) warning and non-working image, so that's just that - a hack.
