### ISSUE TITLE
Polygon2D toolbar becomes inaccessible when a shader is attached.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#43635]
**Godot version:**

04103db6bd5694b81ab0a1717fc5fdde6cb5dd4f 
bfed10185a55004b258eaad7fbb3e6049448edf9 (Slightly different behavior.  Works initially.)

**OS/device including version:**

Win 10 64bit

**Issue description:**

When attaching a material and then a shader to a Polygon2D the toolbar to edit the points will disappear.

![godot windows tools 64_QSbit9iC8y](https://user-images.githubusercontent.com/13004169/99510068-4636f100-298f-11eb-828b-340b6a8556af.png)
![godot windows tools 64_CWXapGmKIV](https://user-images.githubusercontent.com/13004169/99510160-64045600-298f-11eb-8b23-e2c6dd8fcc23.png)

**Steps to reproduce:**
It appears to be the result of the shader text editor opening.  In 3.2 this is forced every time the Polygon2D is selected.

In the Master it seems to be fine on first selection, but after opening the shader resource and having the editor to appear, the toolbars then vanishes from then on.

1. Create a Polygon2D
2. Attach a Material and a Shader.
3. Open the Shader resource into its text editor.

**Minimal reproduction project:**

[Poly Tools Missing.zip](https://github.com/godotengine/godot/files/5559007/Poly.Tools.Missing.zip)

**Comment by Swanderrr** [comment]
I'm not sure if this should be considered a bug? After some testing it looks like it is a default Godot response after selecting an editable resource from the currently inspected object. Similar result could be observed in Polygon2D if you would try to open its texture. I even tested it with Sprite2D and, as expected, it hid its type-specific toolbar panel as well.
