### ISSUE TITLE
SVG rendering incorrectly after nanosvg update (regression)

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#43641]
**Godot version:**
4.0 master f697e7879b0c1b37b94b890b3f2a9910e5d822a2

**OS/device including version:**
WIN 10

**Issue description:**
Many (but not all, it seems) SVG icons are rendering incorrectly after f697e7879b0c1b37b94b890b3f2a9910e5d822a2
![image](https://user-images.githubusercontent.com/41730826/99520041-5a560f00-29de-11eb-9577-016eaa0af5a9.png)

**Comment by akien-mga** [comment]
I'll bisect the upstream changes.

**Comment by akien-mga** [comment]
Upstream bug report: https://github.com/memononen/nanosvg/issues/188

**Comment by akien-mga** [comment]
Reverted for now until the upstream issue is fixed.
