### ISSUE TITLE
get_tree().quit() on IOS doesn't close the game

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot#43655]
**Godot version:**

3.2.3-stable

**OS/device including version:**

IOS Iphone 6

**Issue description:**

get_tree().quit()  on IOS doesn't close the game

**Steps to reproduce:**
try to call get_tree().quit() on IOS

**Minimal reproduction project:**

**Comment by Calinou** [comment]
See also #24049. This is likely a design decision on iOS.

**Comment by Calinou** [comment]
Reopening, as this still needs to be better documented.
