### ISSUE TITLE
Crash when serialising PackedScene with a custom resource

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#43652]
**Godot version:**
68973cadf71f66f8e6fab270e441f24a1ff213b4

**OS/device including version:**
Windows 10

**Issue description:**
When serialising a scene with a custom resource type, the editor will crash. The engine will also crash if attempting to load the scene ingame. A bisect seems to indicate that the issue occured after this commit 1e9a774ac24ecbbec9b0aa4b903f3f1525f4d525

**Steps to reproduce:**
Simply load alicia.scn in the example project and attempt to save it again.

**Minimal reproduction project:**
[godot_crash_test.zip](https://github.com/godotengine/godot/files/5562305/godot_crash_test.zip)

**Comment by RandomShaper** [comment]
Fixed. Alice can now be saved. 😄
