### ISSUE TITLE
Artifacts on Android GLES2 with PanoramaSky

### ISSUE THREAD

**Issue by Filippopotamus** [godotengine/godot#43667]
**Godot version:**
3.2.3

**OS/device including version:**
Android, Pixel 2, GLES2

**Issue description:**
On Editor:
![image](https://user-images.githubusercontent.com/4430051/99612888-65ec0a80-29cb-11eb-8df7-7e03f4f91181.png)

On Android:
![screen](https://user-images.githubusercontent.com/4430051/99612833-3f2dd400-29cb-11eb-99d9-2e140f5bcb53.png)

Artifacts on objects when WorldEnvironment has a PanoramaSky. If WorldEnvironment is set to color only, this does not happen. There is a ticket related to this (https://github.com/godotengine/godot/issues/33633) which says it is fixed by enabling High Precision Float in GLES2 for Android, however it does not seem to fix it. This issues is not present on Desktop or iOS (or any other platform I am aware of)

**Steps to reproduce:**
1) Create scene and add a sphere and camera
2) Add SpatialMaterial to sphere
3) Add WorldEnvironment to scene and add Environment
4) Select Background->Mode = Sky
5) Add new ProceduralSky or add a PanoramaSky
6) Run project on Android device

**Minimal reproduction project:**
[Repro Project (Includes .apk)](https://github.com/godotengine/godot/files/5563905/GodotBug.zip)
[Repro Project (No .apk)](https://github.com/godotengine/godot/files/5563976/GodotBug-NoAPK.zip)

**Comment by volzhs** [comment]
probably related to #37673

**Comment by Filippopotamus** [comment]
As @NeoSpark314 mentioned on https://github.com/godotengine/godot/issues/33633, the Level 1 of the Sky cubemap is black.

Level 0:
![Level0](https://user-images.githubusercontent.com/4430051/99713828-a4300b00-2a59-11eb-915a-7f34d6108df6.png)

Level 1:
![image](https://user-images.githubusercontent.com/4430051/99713865-b27e2700-2a59-11eb-8b69-a740beab3fe0.png)

**Comment by Filippopotamus** [comment]
Any news on this?

**Comment by Calinou** [comment]
> Any news on this?

As far as I know, nobody has found a fix to this issue yet.

**Comment by akien-mga** [comment]
Fixed by #44489.
