### ISSUE TITLE
Add more small utility effects like modulate

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#4367]
Hello,
On my game I developed some utility shaders because enemies flash white when they take damage or some sprites need inverted colors and I couldn't achieve those effects with modulate, this escalates so bad with multiple sprites because they need a shader with the UNIQUE flag for each one, this gets even worse if some enemies needs another shader behaviour.

For that reason I propose a change on modulate section from Sprite and Animated Sprite.
The idea is to support more lightweight utility effects of common use and let's the user cycle between them, only one effect is active at time for each sprite and could be cycled by animations or scripts included his properties.

Proposed changes to godot GUI to support this:
![Image NewGui](http://i.imgur.com/UJyWSWU.png)
- Move the Modulate to a new section called Effects
- Here you could select the current effect from a dropbox, default one is modulate with white
- Display controls related for each effect when one is selected

And here is video from a prototype of how this section could behave:
https://dl.dropboxusercontent.com/s/xc06512cg9rdswm/2016-04-18_16-13-22.mp4?dl=0

Examples of posible new effects:
Additive Blending: make enemies flash white or another light recolor
Silhouette: change sprite to a solid color, could be used to make enemies flash white too
Desaturate: convert sprites to shades of grey
Inverse: invert colors of a sprite

So what do you think about this idea?

**Comment by trollworkout** [comment]
or you can simply create an effects section where you can actually add effects 

you pull the drop down and you click a button called add and it adds the effect below then you can use all effects at the same time if you wish. all with script handles like get_effects_list as an array maybe then you can get 1 2 3 etc

**Comment by HeartoLazor** [comment]
Hey trollworkout, don't forget about the shader access, with the current system exist an attribute called SRC_COLOR on shader code, this attribute is the MODULATE color, on my proposal I thought about this and my solution should be add a new shader var for manage the float effects like desaturate.
so on shader attributes should be now:
SRC_COLOR <--- shader vec4 for all effects with color (this already exist for modulate)
SRC_RANGE <--- shader float for all effects with a range
SRC_CURRENT_EFFECT <--- shader float which represents current effect active, I don't know if this last one should be a good idea, because leads to multiple cases on shaders
As a  rule all the simple effects only takes 1 parameter, a color or a float.
This is the reason because my proposal only suggest 1 effect active at time on the same "slot" as modulate.

Now how you manage this part with your suggestion of multiple effect list?

**Comment by trollworkout** [comment]
@HeartoLazor  Im guessing there is an array that holds each "effect" object and the visual server will place first effect on the image then produce a new image then place second effect and produce a new image and so forth then finally present it to the screen. So obvs too many effects will become slower. Also the order matters.

**Comment by HeartoLazor** [comment]
@trollworkout But how you expose the vars to user on shader language if they already has a shader on the sprite/animated sprite?, What I described on top with SRC_COLOR

**Comment by trollworkout** [comment]
@HeartoLazor  same thing except one extra step of getting the effects list array

var effects = sprite.get_effects_array()

effects[0].get_type
effects[0].get_src_color
effects[0].set_src_color = new Color(5, 5, 5)
effects[0].set_range
effects[0].get_range
...

so you can change anything in a link of effects

**Comment by HeartoLazor** [comment]
@trollworkout I think you couldn't access to arrays on shader code at least. Could you make a demo on a branch, where you expose the effect array somehow to the shader code? Remember when you add a shader, the effect of modulate doesn't get automatically applied, you need to read the SRC_COLOR var exposed and apply the modulate effect yourself (color*SRC_COLOR). For this is important the var exposed somehow on godot shader language.
Now a solution for your method I think could be scrap the SRC_COLOR behaviour and add an enum for automatically apply the effect when a shader is present behind the scenes,(for each effect, generate glsl code to apply it), but with this, you should take consideration if it's generated after or before the user shader.

**Comment by HeartoLazor** [comment]
I found the SRC_COLOR parameter on shader language is always **UNIQUE** for each instance.
SRC_COLOR.rgb is the Modulate parameter from sprites or textures exposed to Shader language and SRC_COLOR.a is the Modulate alpha * Opacity * Local Opacity
So if you want the modulate property behave as additive you should use SRC_COLOR, with this implementation each instance of sprite has ALWAYS different parameters without the uniform requirement of **"Make Shader Unique"** 
An example of this:
```
vec4 col = tex(TEXTURE,UV);
vec4 modulate = SRC_COLOR;
COLOR.r = min(modulate.r+col.r,1.0);
COLOR.g = min(modulate.g+col.g,1.0);
COLOR.b = min(modulate.b+col.b,1.0);
COLOR.a = col.a * modulate.a;
```

I hope this could help somebody looking for a nice way to do this and not _Make every instance as Unique_ approach for different parameters on simple effects.


Still a nice feature request could be a new shader variable like **SRC_COLOR**, which is always unique for each INSTANCE, but with only a float value, something like **SRC_FLOAT**, this could be closed if you think so, and I will open a new one for the SRC_FLOAT request

**Comment by KoBeWi** [comment]
That's rather easy to achieve with a plugin or even a simple custom node inheriting from Sprite. I'm not really convinced that we need this in the core.

**Comment by akien-mga** [comment]
I also don't think this is necessary, and any "effect" would likely be quite project-specific. As there was not much support for the proposal over the years, closing.
