### ISSUE TITLE
[3.2.4 beta2] When opening Godot Editor, The Editor Window will automatically minimized.

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#43675]
**Godot version:**

3.2.4 beta2

**OS/device including version:**

![屏幕快照 2020-11-19 17 06 53](https://user-images.githubusercontent.com/64188282/99645028-a6aa5900-2a89-11eb-9203-f1c490d72df8.png)

**Issue description:**

when I opened Godot Editor on first time after installing, the Editor Window was automatically minimized. when I opened Godot Editor on second time, the Editor Window just flicked a second then opened as usual, but when I opened Project, the Editor Window was automatically minimized again

I test it on a Windows PC, seems it only appeae on MacOS

**Steps to reproduce:**
see the video I record
[open godot bug.mp4.zip](https://github.com/godotengine/godot/files/5565747/open.godot.bug.mp4.zip)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Is this a regression in 3.2.4 beta 2, or is this the first version you try?

If it's a recent regression, it might be related to #42276 (but I checked and `_no_window` seems properly initialized to `false` in `core/os/os.cpp`).

**Comment by snougo** [comment]
> Is this a regression in 3.2.4 beta 2, or is this the first version you try?
> 
> If it's a recent regression, it might be related to #42276 (but I checked and `_no_window` seems properly initialized to `false` in `core/os/os.cpp`).

I don't have this problem with beta1

**Comment by akien-mga** [comment]
Fixed by #43678.
