### ISSUE TITLE
[3.2.4 beta2] View Grid Turn on/off bug

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#43672]
**Godot version:**

3.24 beta2

**OS/device including version:**

![屏幕快照 2020-11-19 16 40 04](https://user-images.githubusercontent.com/64188282/99641987-f0914000-2a85-11eb-8b42-7c79e02a8d7c.png)

**Issue description:**

turn on or off View Grid will not Immediately show Grid or hide Grid, also when turn off View Grid and turn on some Post-Processing like SSR, dragging viewport feels lagging, see the video I record
[grid view bug.mp4.zip](https://github.com/godotengine/godot/files/5565464/grid.view.bug.mp4.zip)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Might be related to #43206 (@Calinou).

**Comment by akien-mga** [comment]
#43681 will fix the issue of the View Grid not working immediately.

For the viewport lagging, it might be worth opening a new issue so that we can look into it after this is closed by #43681.
