### ISSUE TITLE
Incorrect mouse position in Node2Ds under CanvasLayer

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4368]
Tested on Godot 2.0.2, Windows 7 64 bits.

In my game, I put the HUD inside a CanvasLayer, but mouse position returned by get_global_mouse_pos() is incorrect when nodes go deeper in hierarchy.
If node A is child of a CanvasLayer, reported position is fine, relative to the layer and not the level's camera.
However, if B is child of A, mouse position is incorrect and is reported as if B was a sibling of CanvasLayer, so the camera of the level ends up being used as reference.

Because of this, I can't create clickable custom controls because get_global_mouse_pos() doesn't works as expected.

Sample project: http://zylannprods.fr/dl/godot/GlobalMousePosLayer.zip
Start new_scene.tscn, then click the sprite on the top-left. Two positions are printed, one for node A, one for node B. Both should be equal, but B is incorrect.

Might be related (or maybe not): https://github.com/godotengine/godot/pull/2306

**Comment by bojidar-bg** [comment]
Close?

**Comment by akien-mga** [comment]
Fixed by 2b9cab2.
