### ISSUE TITLE
set_process_internal starts timers

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#43689]
**Godot version:**
3.2.2

**OS/device including version:**
Linux

**Issue description:**
I have a simple kinematic body with a one shot timer. I start the timer manually in code, nowhere else starts it.

However, I am now calling:

```
propagate_call("set_process_internal",[true])
```

instead of
```
set_process(true)
```

On the node, and as soon as I do, the timer automatically starts and then it's timeout is subsequently called.

When I remove the call or if I simply call set_process(true), nothing happens as you would expect.

I've just rewritten all my code to use this as advised in a ticket detailing automatically disabling nodes and now there are probably a dozen nodes that will now probably be broken. So I'll have to revert back with now no obvious means of disabling a node in Godot...

**Steps to reproduce:**
1. Create a node
2. Create a one-shot timer
3. instance node and call propagate_call("set_process_internal",[true])
4. kaboom, the timer starts and your timeout is raised

**Minimal reproduction project:**
I don't think this is needed for such a simple case.

**Comment by akien-mga** [comment]
That seems correct. Why do you need to use `set_process_internal()` over `set_process()`? The internal version is meant for... internal use.

**Comment by chucklepie** [comment]
Because on a ticket (can't remember which) regarding how to completely
disable a node. I mentioned the pain of having to stop each and every
timer, collision, etc.

The response was to use propagate and process internal.

Regardless, why would calling set process internal start a timer that was
stopped, that makes no sense?

**Comment by Zireael07** [comment]
The ticket @chucklepie refers to is https://github.com/godotengine/godot-proposals/issues/1835

**Comment by chucklepie** [comment]
@akien-mga Why would calling start_process_internal() tell every timer in a node to actually start? It kind of goes against all logic. Also, as I mentioned in the issue 1835, there is no documentation for this that states what it does so I took from what I was told as it enables/disables all other nodes such as timers/collision boxes, etc.

**Comment by akien-mga** [comment]
> Why would calling start_process_internal() tell every timer in a node to actually start? It kind of goes against all logic.

Why would it go against all logic? You're enabling internal processing, and processing is what's used to process stuff. Timers are nodes that process time, so when internal processing is enabled, their time passes.

Starting a timer starts internal processing. Stopping a timer stops internal processing. Process *is* by essence a timer, it iterates over time and gives you the delta of the last iteration.

**Comment by KoBeWi** [comment]
This is rather meh workaround, but you could try
```
propagate_call("set_process_internal",[true])
propagate_call("stop")
```
to prevent timers from starting. But it would affect e.g. AnimationPlayers too…

We could introduce a variable that controls Timers independently, but it's not really worth it (performance-wise mostly).

> The ticket chucklepie refers to is godotengine/godot-proposals#1835

Actually it's https://github.com/godotengine/godot-proposals/issues/1847

**Comment by chucklepie** [comment]
@akien-mga Ok, you wrote the library so you know best, it's just when you use set_process you're simply allowing the _process method to be called essentially, i.e. you're making the process enabled/disabled, not stop/start.

When told/read set_process_internal does the same for 'deeper' nodes I assumed it would do the same and actually call the start() method on them when they are already stopped. As I said, if the documentation gave more detail it would be fine. As it stands I'll just wait for the other proposal - you can see it's pretty painful to disable a node and all its children at the minute?

**Comment by akien-mga** [comment]
I added a warning to the docs: #43713.
