### ISSUE TITLE
[3.2.4 beta 2] Strange Shader behaviour with Batching (GLES3) enabled.

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#43685]
**Godot version:**
3.2.4 beta 2 - official build (Win 64)

**OS/device including version:**
Windows 10 Pro - 10.0.19042
Nvidia RTX 2080

**Issue description:**
On the example shader, provided in the Minimal reproduction project, the shader only works correctly with:
a) batching disabled
b) making each Shader Material unique

Without batching (or in 3.2.3) it works without this extra step.

**Without batching:**
![3 2 4_shader_batching_disabled](https://user-images.githubusercontent.com/9423774/99670818-6b9c2b80-2a71-11eb-9d35-c5e78257c50d.gif)

**With batching:**
![3 2 4_shader_batching_enabled](https://user-images.githubusercontent.com/9423774/99670806-67700e00-2a71-11eb-9660-20e1b3fe8199.gif)

**Minimal reproduction project:**
[3.2.4b2_shader_batching.zip](https://github.com/godotengine/godot/files/5566922/3.2.4b2_shader_batching.zip)

**Comment by akien-mga** [comment]
Confirmed with 3a8e1f324f56f8a8a08e1bf034467bbc3886b06f.

**Comment by lawnjelly** [comment]
You can also seem to cure it by setting `max_join_item_commands` to zero, which disables item batching.

I suspect it is something in the shader which we should be picking up in the shader and disabling joining those items, possibly WORLD_MATRIX. Some of those builtins are rarely used, so don't get a lot of testing.

**Comment by akien-mga** [comment]
Fixed by #43690.
