### ISSUE TITLE
When opening a project in the IDE, randomly sometimes the logos appear in the bottom left instead of centre

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#43680]
**Godot version:**
3.2.3 .. possibly earlier
3.2.4 beta 2

**OS/device including version:**
Linux Mint 20
Intel HD graphics 630

**Issue description:**
Logos appeared in bottom left of the IDE splash screen, expected in centre.
Seemed random, happened on some starts, not on others.

![logos_left](https://user-images.githubusercontent.com/21999379/99655176-48fb1a00-2a53-11eb-8fdf-600f66c81f16.jpg)

**Steps to reproduce:**
Start the IDE and load a project.

**Minimal reproduction project:**
N/A

This may well be a batching bug, but I'm not absolutely sure at this stage, I'll have a look.

**Comment by akien-mga** [comment]
To clarify, do you mean that their position in the Godot window is wrong?

Because otherwise the fact that the Godot window itself can pop in the middle or in a corner is a X11 quirk that would be hard to circumvent, it just decides by itself where to place the window depending on the other active windows.

**Comment by lawnjelly** [comment]
I managed to grab a screenshot. It could actually be the X11 changes, it could be centred on a window that is bigger than my display?

**Comment by akien-mga** [comment]
The window decoration does shown that the window is fullscreen on your display but not bigger (at least in width), so that doesn't explain the centering being off.

**Comment by lawnjelly** [comment]
It is occurring in 3.2.3 too for me, which never had this problem before the upgrade. So I'm inclined to put it down to an OS issue, unless there are any more reports, we can reopen this.
