### ISSUE TITLE
No padding between error/warning indicators and tab title (3.2.4 beta2)

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#43684]
**Godot version:**
3.2.4 beta2

**OS/device including version:**
Windows 10

**Issue description:**
The padding between the error/warning indicators and the tab title is gone since `beta2`:

3.2.4 beta1:
![Capture](https://user-images.githubusercontent.com/8750135/99668274-cb90d300-2a6d-11eb-8722-d66a412a9a4e.PNG)

3.2.4 beta2:
![Capture2](https://user-images.githubusercontent.com/8750135/99668293-d2b7e100-2a6d-11eb-8c7c-a9672524ed57.PNG)

**Comment by akien-mga** [comment]
Probably a regression from #42766, @volzhs.

**Comment by akien-mga** [comment]
Fixed by #43972.
