### ISSUE TITLE
Vertex shader breaks colors when batching is enabled

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#43696]
**Godot version:**

3.2.4 beta2

**OS/device including version:**

Windows 10 x64 GTX 1060

**Issue description:**

```
shader_type canvas_item;

void vertex()
{
	VERTEX=VERTEX+vec2(sin((UV.y + (TIME)+VERTEX.y*8888.0 )),0.0) * 35.0*(1.0-UV.y);
}
```
Pure vertex shader. In 3.2.4 beta2 it turns sprites black. 3.2.3 was ok.
![image](https://user-images.githubusercontent.com/2223172/99695223-9dbb8680-2a8d-11eb-8581-25ddbb07cf5c.png)
Happens both with GLES2 and GLES3.

Also the sprite changes colors on various actions, e.g. opening a popup menu
![BzkHM7cWz3](https://user-images.githubusercontent.com/2223172/99695367-c80d4400-2a8d-11eb-9b1c-0aa428ad72ab.gif)

Happens in the editor and in-game (exported too). Disabling batching fixes the issue.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/5568292/ReproductionProject.zip)

**Comment by lawnjelly** [comment]
Likely duplicate of #43673. I'll double check though.

We might actually keep the original issue open otherwise we'll get loads of duplicates.

**Comment by KoBeWi** [comment]
Fixed in beta3
