### ISSUE TITLE
Edit menu items duplication in Script Editor

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [godotengine/godot#43707]
**Godot version:**

3.2.4 beta 2

**OS/device including version:**

Windows 10 Home version 2004

**Issue description:**

![image](https://user-images.githubusercontent.com/36826319/99751174-ac1a9a00-2aaf-11eb-88a1-3410d21c9fab.png)

**Steps to reproduce:**

**Minimal reproduction project:**

Simply use the latest beta release and open Edit menu in Script Editor

**Comment by akien-mga** [comment]
Fixed by #43739.
