### ISSUE TITLE
Active Control node receive _GuiInput and prevent _UnhandledInput get called Node3d derived.

### ISSUE THREAD

**Issue by nongvantinh** [godotengine/godot#43708]
**Godot version:**
 
v3.2.3.stable.mono.official

**OS/device including version:**

Windows 10

**Issue description:**

When we design GUI we usually make a root node type **MarginContainer** with Layout -> Full Rect  Then create a child node _PanelContainer_, **VBoxContainer**, **HBoxContainer** and more.
These containers always instance  with **mouse_filter** property set to **stop**. This prevents virtual function _UnhandledInput in 3d derived node get called.

To solve this we need to set **mouse_filter** to **ignore** because they're containers, but with tree design manually set it is a pain. 
These containers shouldn't receive _GuiInput by default.
**Steps to reproduce:**
![Screenshot (25)](https://user-images.githubusercontent.com/53887662/99753752-6f838880-2b19-11eb-87ae-18e0aaec16f2.png)
![Screenshot (27)](https://user-images.githubusercontent.com/53887662/99754801-cf7b2e80-2b1b-11eb-9a8a-7c750e9cb2fa.png)

**Minimal reproduction project:**
[Containers.zip](https://github.com/godotengine/godot/files/5571028/Containers.zip)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/788.
