### ISSUE TITLE
Too many warnings! Ignoring warnings for up to 1 second.

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#43710]
**Godot version:**

Godot 3.2.3.stable (84e17881cd)

**OS/device including version:**

MacOSX 10.15.7 (19H2)
Android 8.1

**Issue description:**

When I start the game on my android device it constantly generates warnings:
```
W 0:01:33.656   Too many warnings! Ignoring warnings for up to 1 second.
  <Ошибка C++>  TOO_MANY_WARNINGS
  <Исходный код C++>:0
```

![Снимок экрана 2020-11-20 в 09 25 25](https://user-images.githubusercontent.com/1177068/99766566-64792a00-2b12-11eb-8c9d-96ac43af9c3c.png)

**Steps to reproduce:**

Run the game on android. 
I don't know if this issue depends on something. I will try to conduct additional investigation. 

**Minimal reproduction project:**

**Comment by qarmin** [comment]
Did you tried to increase warnings/errors limit in settings?
![Zrzut ekranu z 2020-11-20 09-24-56](https://user-images.githubusercontent.com/41945903/99777300-617e3980-2b12-11eb-95b2-3aa99ce66884.png)

**Comment by DrMoriarty** [comment]
@qarmin No, I didn't.
The problem was in too many automatically generated warnings about too many warnings. Really there were no any other warnings except the "Too many warnings!"
And it really don't ignore any warning as it generated them many times per second.

**Comment by DrMoriarty** [comment]
I'm trying to repeat the problem, but now I can not some-why.

**Comment by DrMoriarty** [comment]
@Calinou No, I don't see it in 3.3-stable

**Comment by mbrlabs** [comment]
I have this issue randomly in 3.3.3.stable on Windows 10. I can't reproduce it. Please reopen it, i'm looking into a solution.

**Comment by Calinou** [comment]
> I have this issue randomly in 3.3.3.stable on Windows 10. I can't reproduce it. @Calinou Please reopen it, i'm looking into a solution.

What were you trying to do when you encountered this?

**Comment by mbrlabs** [comment]
I just started https://github.com/mbrlabs/Lorien in the editor. I had to relaunch it many times until i could reproduce it. I think i already have a solution by looking at the code in `script_debugger_remote.cpp`, need to test it. It's probably just a 3.x issue.

**Comment by mbrlabs** [comment]
This can be closed now. Not sure why it didn't close automatically because i linked it in the PR.

**Comment by Dante3085** [comment]
I have just encountered this problem in `3.4.4.stable`:
![too_many_warnings](https://user-images.githubusercontent.com/26558776/179419054-a4b89971-c348-4b8b-8e46-2782dcd91dd1.gif)

Before this occured I have changed some code and had about 80 normal warrnings. Unlike op, I am running my game on Windows 11.

**Comment by mbrlabs** [comment]
@Dante3085 what does the error say? can you expand it and post the complete error message?

**Comment by mbrlabs** [comment]
@Dante3085 can you check if this also happens in `3.3.4`?

**Comment by Dante3085** [comment]
@mbrlabs Will do!

**Comment by Dante3085** [comment]
@mbrlabs I have created #63139 as you hopefully can see in this issue. The problem exists in all three versions on my end.
