### ISSUE TITLE
GDscript Enhancement: Reflection

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#4372]
What if I want to make a game which allows players to write their own code and then executes the code?
I found that I can create a GDScript and then use `get_method_list()`, but there is no more hint.
What I know is only this method returns an array.
I think it is good to have a function like `vars` in python or `Object.has_property`.
Also, add a function which can `execute` code embedded is better.
But be careful, a history told from python tells us it is very important to **isolate** the code in a new namespace.

**Comment by Zylann** [comment]
Well, what if players want to write:
```
while true:
    print("rabbit")
```
You would need to sandbox it in a thread with only access to an API you choose, otherwise they could mess up the game. Threads are supported in Godot, but I'm not sure about deliberate API restriction.

**Comment by buckle2000** [comment]
Well, denial of service is an exception, since it is considered harmless (but not) in most code inspections.

**Comment by buckle2000** [comment]
Also, what is the proper usage of `get_method_list()`?

**Comment by buckle2000** [comment]
May I ask that does GDScript have GIL or such stuff?
If yes, denial of service is no more critical.

**Comment by slapin** [comment]
I think you better do some your game-specific language, maybe json based,
or something. Allowing users access to GDScript is bad idea.
Or you can just release source to your game and allow to play around it.
Or something.

**Comment by buckle2000** [comment]
@slapin @akien-mga I opened this issue because I think GDscript can have a complete reflection system like C# or Java or Python. Making a game like this is just a very specific usage.

**Comment by slapin** [comment]
What is reflection? I thinkk when posting such requests, if you want any
reaction than WTF, you'd better spend a few minutes on writing proper
request on what you want and what benefits it gives.

**Comment by buckle2000** [comment]
@slapin Explanation of *reflection*, see [here](https://en.wikipedia.org/wiki/Reflection_%28computer_programming%29).
Reflection is very useful, but is not necessary in most situation.
If you want to make a simple application, it is not useful.
But reflection is often used in library to automate class, function creation and such stuff.
It is hard to explain all.

**Comment by TeddyDD** [comment]
> You would need to sandbox it in a thread with only access to an API you choose

That's a feature I'd really love to see in GDScript but I suppose its quiet niche thing. It would be useful for creating modding API without exposing all game code. I wonder how hard it would be to do.

**Comment by vnen** [comment]
Both sandboxing and reflection add an execution overhead. You need extra memory for keeping symbols and extra processing time for checking the sandbox boundaries. I can't find a usage (for a **game** logic) that *needs* either of these and that can't be worked around.

Modding API is quite a complex thing IMO and has to be very carefully designed if you don't want people modding too much. It is almost possible with PCK files, but there's a lack of control when loading it which makes it problematic. It would be a similar thing to DLCs.

**Comment by Calinou** [comment]
Is this solved by #31021?

**Comment by willnationsdev** [comment]
@Calinou Yeah, I think this is basically solved with #31021. There's something to be said for documenting how `get_property_list()`, `get_method_list()`, etc. work since most people don't understand the notion of PropertyInfo/MethodInfo structs/dictionaries, but that would be something for godot-docs. The technical blockers of this issue are already resolved by exposing the built-in reflection methods (*which already exist btw*) to the scripting API.

**Comment by Calinou** [comment]
@willnationsdev Thanks for replying :slightly_smiling_face: I'll close this then.
