### ISSUE TITLE
Codesigning silently fails on Mac Mono exports

### ISSUE THREAD

**Issue by sjml** [godotengine/godot#43732]
**Godot version:**
3.2.3 Mono

**OS/device including version:**
macOS 10.15.7

**Issue description:**
Exporting a Mac app with the Mono build of Godot and a valid codesigning identity, the codesigning step fails with the following error: 

```
codesign (/Users/shane/Library/Caches/Godot/MonoTest.app/Contents/MacOS/MonoTest): /Users/shane/Library/Caches/Godot/MonoTest.app/Contents/MacOS/MonoTest: code object is not signed at all
In subcomponent: /Users/shane/Library/Caches/Godot/MonoTest.app/Contents/MacOS/data_MonoTest/Mono/etc/mono/config
```

The [Apple documentation on codesigning](https://developer.apple.com/library/archive/technotes/tn2206/_index.html) has a section on "nested code" that seems like the problem we're running into. Since a good chunk of the Mono distribution gets packaged up into the app, the `codesign` process doesn't happily operate. When I tried manually running codesign with the `--deep` flag, it raised a problem with the version directories, which that same Apple page says is problematic because they get interpreted as bundles. 

I don't know if there's an easy fix for this, other than re-arranging the layout of where the Mac build expects to find the mono distribution. In the meanwhile, though, the export should probably not fail silently as it currently does. (Took me a while to figure out what was wrong with this Godot project but not others.)

I'm looking at different solutions -- apparently Unity runs into similar issues with their exports, but people have had success individually signing each executable. That didn't work on my first effort, but still investigating. Wanted to log the issue though if anyone else runs into it.

**Steps to reproduce:**
1. Load the attached project on a Mac. 
2. Change the export configuration to have a valid codesigning identity. (One that works with a non-Mono Godot project, for instance.)
3. Run the export. 
4. Note the message that appears in the output (reproduced above). Running `codesign -vvvv ./MonoTest.app` on the resulting app confirms that it was not codesigned. 

**Minimal reproduction project:**
[MonoTest.zip](https://github.com/godotengine/godot/files/5576490/MonoTest.zip)

**Comment by Calinou** [comment]
cc @bruvzg @neikeq

**Comment by bruvzg** [comment]
> MonoTest.app/Contents/MacOS/data_MonoTest/Mono/etc/mono/config

Something wrong with the export template.

Nothing except executables and dylibs can go to the `MacOS` folder, nothing except frameworks and dylibs can go to `Frameworks` folder. 

`etc`, mono `dll`s and other custom files should be in `Resources`.

**Comment by sjml** [comment]
If someone else who knows the Mono integration well is already on it, please let me know. Otherwise I'm putting together a patch to fix the .app layout in the export template, but want to know -- should it be based on the master branch or the 3.2?

**Comment by bruvzg** [comment]
I guess none have tried to sign Mono exports before.

I have checked what's in the Mono export template:
- There are `dylibs` in the `MacOS/name/Mono/lib`, these preferably should go to the `Frameworks` or stay in `MacOS`, or they won't be correctly signed.
- The rest of stuff (`etc` configs) should be in the `Resources`.

Note: `Mono/etc` and `dylibs` are correctly placed in the `Resources` and `Freameworks` folders in editor build, but there's a mess of other in the `Frameworks`:
- `dll`s, `exe`s, `pdb`s and `xml`s should be in `Resources`.
- `aot-compiler` executable should go to `MacOS`.

Probably mono module code responsible for loading it, should be changed to reflect correct locations as well.

> should it be based on the master branch or the 3.2?

All new PRs should be done against master and then cherry-picked to 3.2, unless it's 3.2 specific issue (it this case it's probably relevant for both).

**Comment by sjml** [comment]
I'll reorganize to best practices as best I can; that's the easy part. 

> Probably mono module code responsible for loading it, should be changed to reflect correct locations as well.

This is the tricky part -- I'm currently getting the latest build up and running so I can investigate, but I'm living in Lebanon and have very flaky internet at the moment, so it's a little slow going. From [perusing the codebase on GitHub it looks like](https://github.com/godotengine/godot/blob/279f4fbb5f83c2df6e8499799a2aa0c14f85aa2d/modules/mono/godotsharp_dirs.cpp#L181) there are efforts to load from the right places, but something isn't working if the files are there. Once I have a build up I can take a better look. 

> All new PRs should be done against master and then cherry-picked to 3.2, unless it's 3.2 specific issue (it this case it's probably relevant for both).

Will do!

**Comment by sjml** [comment]
Quick question: is there a build script somewhere that generates the downloadable template? The [Compiling for macOS](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_osx.html) page doesn't have the same section as the other platforms for building the templates, just some instructions on how to manually make an editor build if needed. 

I assume it's a similar process for making the template, but I can't identify where in the code that's happening.

**Comment by bruvzg** [comment]
> is there a build script somewhere that generates the downloadable template?

https://github.com/godotengine/godot-build-scripts

**Comment by sjml** [comment]
OK, I've got some small changes to the export code and a new template that seem to resolve the problem. I'm going back and cleaning it up for a PR right now, but wanted to ask what the status is of pulling `libMoltenVK.dylib` into the build. Since right now running Godot 4 on a Mac at all requires manually adding it to the app bundle, I'm guessing it's ok for exports to not include it for now, but if there's a preferred way of including it I'm happy to add that to the template or build script.

**Comment by sjml** [comment]
Maybe I spoke too soon -- I had been pleasantly surprised at how robust the engine was at finding the Mono runtime, no matter where it was placed in the `.app` tree. But then I realized [the official build script](https://github.com/godotengine/godot-build-scripts/blob/463b9577161347038e40c389b85b04a6933d6ff6/build-macosx/build.sh#L10) (which I'd hacked to produce my local version) has `mono_static=yes` as one of its flags. 

This conflicts with [the documentation on building with Mono](https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html), which says that it should be set to `no` on all platforms other than iOS or WASM. 

Anybody know which one is wrong? And does this maybe mean we've been unnecessarily shipping the dynamic libraries for Mono in the editor .app? 

Running some more experiments but my build process is quite slow, so wanted to raise the question while the script runs...
