### ISSUE TITLE
Node.get_groups() returns hidden/unused Engine Groupnames added at Runtime

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#43738]
**Godot version:**
3.2.3.stable
3.2.4.beta2
4.0.dev.custom_build.71f53a5ba

**OS/device including version:**
Win 10 64x

**Issue description:**
Node.`get_groups()` returns also internal used groupnames for e.g. process and input. They seem to be added by `NOTIFICATION_ENTER_TREE `events and the `set_process_xyz` functions like `set_physics_process(true)`.

"_vp_input" + viewport instance id
"_vp_unhandled_input" + viewport instance id
"_vp_unhandled_key_input" + viewport instance id
"idle_process_internal"
"idle_process"
"physics_process"
... also camera groups and more

After a small Godot history lesson and trial and error I noticed that ...

- this groupnames should no longer be necessary for internal processing as NOTIFCATION_XYZ  is used now
- and they should be removed or at least not mixed with user groups after old issue discussions like #7673
- but nearly all NOTIFICATION_ENTER_TREE notifications and set_process_xyz functions inside engine still add groupnames
- internal functions that use these groupnames have no check if the groupname is available on the node so if it gets removed Engine spams the log repeatedly with "remove_from_group()" errors.
- there is currently no way for users to see this hidden gems in the groupname (remote) inspector #41073.

So what is the intention of this groups that seem to be no longer in use? Are they kept for compatibility or is this a regression?

Adding hidden groupnames creates problems like messing with user expected index numbers with get_groups(). The returned Array from get_groups() also seem to be sorted messing up the expected index positions further. I accidentally removed the internal groups while deleting my own groupnames from nodes with a loop function on the get_groups() Array. The Engine started spaming error reports about missing groupnames with "remove_from_group()".

**Steps to reproduce:**
Use Node.get_groups() after e.g. set_physics_process(true)

**Comment by Nekuromu** [comment]
![image](https://user-images.githubusercontent.com/30809120/171687806-88f85ebe-6397-4fce-8401-d4482389f072.png)
![image](https://user-images.githubusercontent.com/30809120/171687863-025b78b6-30cc-4093-887c-8f91e10c921e.png)

I ran into this problem today, I use groups to tell what function on item should do. Such as pickup, toss, or chat. "idle_process" has started popping up out of nowhere, along with the expected results from get_groups().

I am now having to account for it being there in my index by erasing it.

**Comment by winston-yallow** [comment]
Another internal group: `process`
This just popped up for me out of nowhere. Not sure if these groups are needed at all, but if they are needed then they should at least start with `_` as described in [the docs](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-get-groups).
