### ISSUE TITLE
Custom dock with minimal size appears bigger than necessary

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#43749]
**Godot version:**

3.2.4 beta2

**Issue description:**

![uyBuazcFLC](https://user-images.githubusercontent.com/2223172/99879941-8953c700-2c10-11eb-857a-edf7c4207612.gif)
The dock has minimum horizontal size. It looks like the panel is resized to this size, but it's also added to the final size, so the left panel is wider than necessary. But when you manually shrink the width to minimal, when the dock is switched out the additional size is still subtracted resulting in tiny panel.

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/5577793/ReproductionProject.zip)

**Comment by KoBeWi** [comment]
Ugh I just checked on master and it doesn't happen there.
Not sure if it's worth keeping this open. It affects my plugin, but it's not very critical bug.

**Comment by KoBeWi** [comment]
Seems like it happens to the import dock too:
![KWXQy0chYK](https://user-images.githubusercontent.com/2223172/145994717-ac7f5baa-e7f4-4ca3-9f07-2e87474a946a.gif)

**Comment by KoBeWi** [comment]
Seems to be still valid on master, see #64273

**Comment by akien-mga** [comment]
Reopening as #64800 was reverted due to regressions.
