### ISSUE TITLE
Editor memory leak and crash on editing blendtree

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#43740]
**Godot version:**
3.2.2 stable

**OS/device including version:**
linux Godot editor

**Issue description:** **Steps to reproduce:**
select nodes like on screenshot 
![1](https://user-images.githubusercontent.com/24825887/99868018-d499b580-2bcf-11eb-8297-68a35007a6a4.png)
and press delete
Godot will freeze and eats all memory, till you kill Godot editor process

**Minimal reproduction project:**
[BUG_blendtree_mem.zip](https://danilw.github.io/godot-utils-and-other/BUG_blendtree_mem.zip)

**Comment by smix8** [comment]
Does not happen for me on Win10 64x with 3.2.4.beta2.

I tried every possible combination of selecting and deleting the AnimationTree nodes. Even if I select all AnimationTree Nodes at ones and clear the entire AnimationTree nothing bugs or freezes.

**Comment by danilw** [comment]
I tried 3.2.4.beta2 
it does not hapens there, so it only 3.2.2.stable bug, can be closed
