### ISSUE TITLE
Theme not finding an image makes FileSystem view stuck forever

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#4374]
**Operating system or device:**
Windows 10 Pro x64

**Issue description** (what happened, and what was expected):
I created a Theme referencing a texture for use in a Button class. After renaming the texture, the FileSystem view gets stuck at "Scanning files" forever, and reopening the project doesn't help.
Additionally, in a bigger game project, I cannot close the editor anymore as it freezes upon attempting to do so, and I have to kill its process. (I could not reproduce that in the sample project linked below).

**Steps to reproduce:**
Open the project I linked below. The FileSystem view is stuck at "Scanning Files".
The Button.png texture file was renamed to Button_renamed.png before.

**Link to minimal example project**:
[DickTheme.zip](https://github.com/godotengine/godot/files/228076/DickTheme.zip)

**Comment by reduz** [comment]
Sorry, but the .thm file is corrupted, which is why you see this. Could you specify the steps you did that resulted in this corrupted file?

**Comment by RayKoopa** [comment]
I'm afraid it's too long ago. I could indeed only fix it by recreating the theme. The only steps I remember it was that I simply renamed a texture referenced in there, and then my FileSystem stopped working.

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
