### ISSUE TITLE
Vertex Light: Improperly lit with multiple directional lights (GLES3)

### ISSUE THREAD

**Issue by Enoh32** [godotengine/godot#43760]
**Godot version:**
3.2.4 beta & 3.2.3 stable (Tested both)

**OS/device including version:**
Windows 7 64-bit, using GLES3

**Issue description:**
When using more than one directional light on a vertex-lit material, the material will be lit without any texture/color information, besides the light's color, for any directional light that is not the first one lighting the object. This has existed since 3.0 I believe. This does not happen with GLES2. This only happens with Directional Lights.

**Steps to reproduce:**
-Make a new scene 
-Make a sphere mesh and give it a red material that uses vertex lights
-Use two directional lights on opposing sides and enjoy the improper lighting

**Screenshot:**
![vertex_light_directional](https://user-images.githubusercontent.com/17599329/99889991-aeecca80-2c28-11eb-948e-33a2a0608d4d.png)

**Comment by Calinou** [comment]
I can confirm this on 3.2.4beta2 (Linux, GeForce GTX 1080).

Minimal reproduction project: [test_vertex_lighting.zip](https://github.com/godotengine/godot/files/5578707/test_vertex_lighting.zip)

**Comment by clayjohn** [comment]
This bug is amazing! Godot 3.2 only supports 1 DirectionalLight at a time. The shader literally doesn't have any way of passing more than 1! So I have no idea how this is happening, but it shouldnt happen at all. 

If the bug isn't easy to fix in the VisualServer/Rasterizer, then I suggest we just add a warning at node level.

**Comment by Calinou** [comment]
> This bug is amazing! Godot 3.2 only supports 1 DirectionalLight at a time. The shader literally doesn't have any way of passing more than 1! So I have no idea how this is happening, but it shouldnt happen at all.

**Comment by akien-mga** [comment]
Fixed by #46205.
