### ISSUE TITLE
ExportDebug to Android giving Duplicate Error

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#43765]
3.2.4 beta2

I finally got my Godot 3.2.2 project working on windows in 3.2.4 beta2.  However, when I try to export to Android, I get a Build Error:
`.mono\temp\obj\ExportDebug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs(4,12): Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute`

After this the project  won't even run in windows.

When I go to VS Code and look at the file tree,  here is what it looks like:
![extra](https://user-images.githubusercontent.com/26915986/99896912-3995ef80-2c52-11eb-8e19-5aaf6414288f.png)

If I delete the red file, I can run it in windows again UNTIL I try to export it again.

Any thoughts?

**Comment by ondesic** [comment]
If I delete the temp/obj/Debug folder I can export it to the Android device.  Then If I try to run it on the Desktop, I get the error above.
If I delete the temp/obj/ExportDebug folder, I can run it on the desktop, but when I try to export to android I get the error above.

There must be a setting that allows both to exist at the same time, but is missing from the settings.

**Comment by ondesic** [comment]
@Calinou The bug seems to occur on any platform.  It just depends on which platform you export second.  The first runs/exports fine, when you try to export to a second platform the duplicate error is occuring.

**Comment by nobuyukinyuu** [comment]
This may be a potential issue with the `.csproj` file includes.  If you included a wildcard that contains the `.mono` directory then this error can occur when building.

**Comment by neikeq** [comment]
I would need an example project to reproduce.

**Comment by van800** [comment]
I think this is obsolete after switching to new csproj format. Godot 3.4 and maybe even earlier.

**Comment by akien-mga** [comment]
Closing as non reproducible.
