### ISSUE TITLE
Vulkan: Panorama sky not rotating correctly

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#43767]
**Godot version:**
current 4.0 master

**OS/device including version:**
Win10 960M

**Issue description:**
When using the Panorama sky rotation control, it is not rotating correctly, as it does in 3.2.

**Steps to reproduce:**
Add a panorama sky to the world environment node and load in a hdri image. Change the rotation y axis to anything other than 0.

**Minimal reproduction project:**
[sky_rotation_issue.zip](https://github.com/godotengine/godot/files/5579174/sky_rotation_issue.zip)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/69630, which contains more information about the issue at hand.
