### ISSUE TITLE
Errors when adding mesh instance primitives

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#43766]
**Godot version:**
current 4.0 master

**OS/device including version:**
Win10 960M

**Issue description:**
When adding mesh instance primtives the console is spammed with errors

**Steps to reproduce:**

Add a mesh instance node and change it to a quad or plane and the console continually prints the error:
core/math/basis.cpp:65 - Condition "det == 0" is true.

If the other primitive types are added, then there are multiple reports of:
./servers/rendering/rasterizer.h:221 - Condition "!F" is true. Continuing.

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.rc2. Even setting a PlaneMesh's size to `(0, 0)` doesn't cause any errors to be printed:

![image](https://user-images.githubusercontent.com/180032/220205109-c1e731f6-ad51-41c8-808e-27287f364ca3.png)
