### ISSUE TITLE
Instanced scene is not automatically opened in the inspector

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#43761]
**Godot version:**

3.2.4 beta2 / 48049b8

**Issue description:**

When you instance a scene with "Instance Child Scene" button, the scene doesn't get opened in the inspector automatically. It wasn't like this in 3.2.3

**Steps to reproduce:**
1. Use "Instance Child Scene"
2. Notice that the inspector remains unchanged, despite the new instance is selected (compare with "Add Child Node")

**Comment by KoBeWi** [comment]
This can be fixed by adding `editor->push_item(instances[instances.size() - 1]);` at the end of `_perform_instance_scenes()` in `scene_tree_dock.cpp`, but this hides the real issue. The new node is selected but somehow doesn't end up in the inspector. Hard to tell where it broke.

**Comment by akien-mga** [comment]
Probable culprit (didn't test, but it happened between `3.2.3-stable` and beta 1 (2e073ecbeaf5b502c2b8c3c0510e4a22a56db58f)): 5abc42c27e36d49dba6a238094035f5eae722e1f, i.e. #32908.
