### ISSUE TITLE
HTML5 export does not export certificate .crt file

### ISSUE THREAD

**Issue by ripperdave** [godotengine/godot#43771]
Dear Colleagues,

I wanted to test the new crypto class with websocket. Thanks for your work @Faless.

**Godot version:**
Godot 3.2.4 beta 2

**OS/device including version:**
Ubuntu 20.04.1 LTS 64 bit, Brave browser

**Issue description:**
Usecase:
[html5CertificateIssue.zip](https://github.com/godotengine/godot/files/5579567/html5CertificateIssue.zip)

Websocket client need to use wss from https itch.io site. I wanted to export a html5 client only. Certificate cannot be loaded in in html5 exported version.
HTML5 export does not export .crt file.
Filter to export has *.crt settings.
Client works in linux standalone export. It also works in the editor.
It is interesting that .crt file has no resource file in .import folder.

**Steps to reproduce:**
Export html5 version or run in 1 click deploy/run html5 icon. See errors in browser inspector tool F12.

**Minimal reproduction project:**

Logs from browser:
Godot Engine v3.2.4.beta2.official - https://godotengine.org
tmp_js_export.js:9 OpenGL ES 3.0 Renderer: WebKit WebGL
tmp_js_export.js:9 OpenGL ES Batching: ON
tmp_js_export.js:9  
**t**mp_js_export.js:9 **ERROR**: Failed loading resource: res://public.crt. Make sure resources have been imported by opening the project in the editor at least once.****
put_char @ tmp_js_export.js:9
write @ tmp_js_export.js:9
write @ tmp_js_export.js:9
doWritev @ tmp_js_export.js:9
_fd_write @ tmp_js_export.js:9
__stdio_write @ 04f1990e:0x6c8560
__vfprintf_internal @ 04f1990e:0x183317
vfprintf @ 04f1990e:0x11f382
StdLogger::logv(char const*, void*, bool) @ 04f1990e:0x807199
Logger::logf_error(char const*, ...) @ 04f1990e:0x152bef
Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xb87dca
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xc7587f
_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType) @ 04f1990e:0x2ca46
_err_print_error(char const*, char const*, int, char const*, String const&, ErrorHandlerType) @ 04f1990e:0x2e0d7
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0700
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
ResourceInteractiveLoaderText::poll() @ 04f1990e:0x897ead
ResourceFormatLoader::load(String const&, String const&, Error*) @ 04f1990e:0x8a3e46
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0639
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
Main::start() @ 04f1990e:0xb81444
main @ 04f1990e:0x600ac8
Module._main @ tmp_js_export.js:9
callMain @ tmp_js_export.js:9
(anonymous) @ tmp_js_export.js:362
(anonymous) @ tmp_js_export.js:357
Promise.then (async)
Engine.start @ tmp_js_export.js:302
(anonymous) @ tmp_js_export.js:380
Promise.then (async)
Engine.startGame @ tmp_js_export.js:376
(anonymous) @ tmp_js_export.html:270
(anonymous) @ tmp_js_export.html:275
tmp_js_export.js:9    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char @ tmp_js_export.js:9
write @ tmp_js_export.js:9
write @ tmp_js_export.js:9
doWritev @ tmp_js_export.js:9
_fd_write @ tmp_js_export.js:9
__stdio_write @ 04f1990e:0x6c8560
__vfprintf_internal @ 04f1990e:0x183317
vfprintf @ 04f1990e:0x11f382
StdLogger::logv(char const*, void*, bool) @ 04f1990e:0x807199
Logger::logf_error(char const*, ...) @ 04f1990e:0x152bef
Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xb87df2
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xc7587f
_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType) @ 04f1990e:0x2ca46
_err_print_error(char const*, char const*, int, char const*, String const&, ErrorHandlerType) @ 04f1990e:0x2e0d7
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0700
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
ResourceInteractiveLoaderText::poll() @ 04f1990e:0x897ead
ResourceFormatLoader::load(String const&, String const&, Error*) @ 04f1990e:0x8a3e46
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0639
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
Main::start() @ 04f1990e:0xb81444
main @ 04f1990e:0x600ac8
Module._main @ tmp_js_export.js:9
callMain @ tmp_js_export.js:9
(anonymous) @ tmp_js_export.js:362
(anonymous) @ tmp_js_export.js:357
Promise.then (async)
Engine.start @ tmp_js_export.js:302
(anonymous) @ tmp_js_export.js:380
Promise.then (async)
Engine.startGame @ tmp_js_export.js:376
(anonymous) @ tmp_js_export.html:270
(anonymous) @ tmp_js_export.html:275
tmp_js_export.js:9 **ERROR**: Failed loading resource: res://public.crt. Make sure resources have been imported by opening the project in the editor at least once.
put_char @ tmp_js_export.js:9
write @ tmp_js_export.js:9
write @ tmp_js_export.js:9
doWritev @ tmp_js_export.js:9
_fd_write @ tmp_js_export.js:9
__stdio_write @ 04f1990e:0x6c8560
__vfprintf_internal @ 04f1990e:0x183317
vfprintf @ 04f1990e:0x11f382
StdLogger::logv(char const*, void*, bool) @ 04f1990e:0x807199
Logger::logf_error(char const*, ...) @ 04f1990e:0x152bef
Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xb87dca
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xc7587f
_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType) @ 04f1990e:0x2ca46
_err_print_error(char const*, char const*, int, char const*, String const&, ErrorHandlerType) @ 04f1990e:0x2e0d7
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0700
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
ResourceInteractiveLoaderText::_parse_ext_resource(VariantParser::Stream*, Ref<Resource>&, int&, String&) @ 04f1990e:0x89adf6
ResourceInteractiveLoaderText::_parse_ext_resources(void*, VariantParser::Stream*, Ref<Resource>&, int&, String&) @ 04f1990e:0x89ac5b
VariantParser::parse_value(VariantParser::Token&, Variant&, VariantParser::Stream*, int&, String&, VariantParser::ResourceParser*) @ 04f1990e:0xc329b
VariantParser::parse_tag_assign_eof(VariantParser::Stream*, int&, String&, VariantParser::Tag&, String&, Variant&, VariantParser::ResourceParser*, bool) @ 04f1990e:0xc4a7c
ResourceInteractiveLoaderText::_parse_node_tag(VariantParser::ResourceParser&) @ 04f1990e:0x89aa13
ResourceInteractiveLoaderText::poll() @ 04f1990e:0x899064
ResourceFormatLoader::load(String const&, String const&, Error*) @ 04f1990e:0x8a3e46
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0639
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
Main::start() @ 04f1990e:0xb81444
main @ 04f1990e:0x600ac8
Module._main @ tmp_js_export.js:9
callMain @ tmp_js_export.js:9
(anonymous) @ tmp_js_export.js:362
(anonymous) @ tmp_js_export.js:357
Promise.then (async)
Engine.start @ tmp_js_export.js:302
(anonymous) @ tmp_js_export.js:380
Promise.then (async)
Engine.startGame @ tmp_js_export.js:376
(anonymous) @ tmp_js_export.html:270
(anonymous) @ tmp_js_export.html:275
tmp_js_export.js:9    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char @ tmp_js_export.js:9
write @ tmp_js_export.js:9
write @ tmp_js_export.js:9
doWritev @ tmp_js_export.js:9
_fd_write @ tmp_js_export.js:9
__stdio_write @ 04f1990e:0x6c8560
__vfprintf_internal @ 04f1990e:0x183317
vfprintf @ 04f1990e:0x11f382
StdLogger::logv(char const*, void*, bool) @ 04f1990e:0x807199
Logger::logf_error(char const*, ...) @ 04f1990e:0x152bef
Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xb87df2
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xc7587f
_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType) @ 04f1990e:0x2ca46
_err_print_error(char const*, char const*, int, char const*, String const&, ErrorHandlerType) @ 04f1990e:0x2e0d7
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0700
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
ResourceInteractiveLoaderText::_parse_ext_resource(VariantParser::Stream*, Ref<Resource>&, int&, String&) @ 04f1990e:0x89adf6
ResourceInteractiveLoaderText::_parse_ext_resources(void*, VariantParser::Stream*, Ref<Resource>&, int&, String&) @ 04f1990e:0x89ac5b
VariantParser::parse_value(VariantParser::Token&, Variant&, VariantParser::Stream*, int&, String&, VariantParser::ResourceParser*) @ 04f1990e:0xc329b
VariantParser::parse_tag_assign_eof(VariantParser::Stream*, int&, String&, VariantParser::Tag&, String&, Variant&, VariantParser::ResourceParser*, bool) @ 04f1990e:0xc4a7c
ResourceInteractiveLoaderText::_parse_node_tag(VariantParser::ResourceParser&) @ 04f1990e:0x89aa13
ResourceInteractiveLoaderText::poll() @ 04f1990e:0x899064
ResourceFormatLoader::load(String const&, String const&, Error*) @ 04f1990e:0x8a3e46
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0639
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
Main::start() @ 04f1990e:0xb81444
main @ 04f1990e:0x600ac8
Module._main @ tmp_js_export.js:9
callMain @ tmp_js_export.js:9
(anonymous) @ tmp_js_export.js:362
(anonymous) @ tmp_js_export.js:357
Promise.then (async)
Engine.start @ tmp_js_export.js:302
(anonymous) @ tmp_js_export.js:380
Promise.then (async)
Engine.startGame @ tmp_js_export.js:376
(anonymous) @ tmp_js_export.html:270
(anonymous) @ tmp_js_export.html:275
tmp_js_export.js:9 **WARNING**: Couldn't load external resource: res://public.crt
put_char @ tmp_js_export.js:9
write @ tmp_js_export.js:9
write @ tmp_js_export.js:9
doWritev @ tmp_js_export.js:9
_fd_write @ tmp_js_export.js:9
__stdio_write @ 04f1990e:0x6c8560
__vfprintf_internal @ 04f1990e:0x183317
vfprintf @ 04f1990e:0x11f382
StdLogger::logv(char const*, void*, bool) @ 04f1990e:0x807199
Logger::logf_error(char const*, ...) @ 04f1990e:0x152bef
Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xb87dca
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xc7587f
_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType) @ 04f1990e:0x2ca46
_err_print_error(char const*, char const*, int, char const*, ErrorHandlerType) @ 04f1990e:0x29c34
ResourceInteractiveLoaderText::_parse_ext_resource(VariantParser::Stream*, Ref<Resource>&, int&, String&) @ 04f1990e:0x89ae48
ResourceInteractiveLoaderText::_parse_ext_resources(void*, VariantParser::Stream*, Ref<Resource>&, int&, String&) @ 04f1990e:0x89ac5b
VariantParser::parse_value(VariantParser::Token&, Variant&, VariantParser::Stream*, int&, String&, VariantParser::ResourceParser*) @ 04f1990e:0xc329b
VariantParser::parse_tag_assign_eof(VariantParser::Stream*, int&, String&, VariantParser::Tag&, String&, Variant&, VariantParser::ResourceParser*, bool) @ 04f1990e:0xc4a7c
ResourceInteractiveLoaderText::_parse_node_tag(VariantParser::ResourceParser&) @ 04f1990e:0x89aa13
ResourceInteractiveLoaderText::poll() @ 04f1990e:0x899064
ResourceFormatLoader::load(String const&, String const&, Error*) @ 04f1990e:0x8a3e46
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0639
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
Main::start() @ 04f1990e:0xb81444
main @ 04f1990e:0x600ac8
Module._main @ tmp_js_export.js:9
callMain @ tmp_js_export.js:9
(anonymous) @ tmp_js_export.js:362
(anonymous) @ tmp_js_export.js:357
Promise.then (async)
Engine.start @ tmp_js_export.js:302
(anonymous) @ tmp_js_export.js:380
Promise.then (async)
Engine.startGame @ tmp_js_export.js:376
(anonymous) @ tmp_js_export.html:270
(anonymous) @ tmp_js_export.html:275
tmp_js_export.js:9    At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://public.crt
put_char @ tmp_js_export.js:9
write @ tmp_js_export.js:9
write @ tmp_js_export.js:9
doWritev @ tmp_js_export.js:9
_fd_write @ tmp_js_export.js:9
__stdio_write @ 04f1990e:0x6c8560
__vfprintf_internal @ 04f1990e:0x183317
vfprintf @ 04f1990e:0x11f382
StdLogger::logv(char const*, void*, bool) @ 04f1990e:0x807199
Logger::logf_error(char const*, ...) @ 04f1990e:0x152bef
Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xb87df2
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xc7587f
_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType) @ 04f1990e:0x2ca46
_err_print_error(char const*, char const*, int, char const*, ErrorHandlerType) @ 04f1990e:0x29c34
ResourceInteractiveLoaderText::_parse_ext_resource(VariantParser::Stream*, Ref<Resource>&, int&, String&) @ 04f1990e:0x89ae48
ResourceInteractiveLoaderText::_parse_ext_resources(void*, VariantParser::Stream*, Ref<Resource>&, int&, String&) @ 04f1990e:0x89ac5b
VariantParser::parse_value(VariantParser::Token&, Variant&, VariantParser::Stream*, int&, String&, VariantParser::ResourceParser*) @ 04f1990e:0xc329b
VariantParser::parse_tag_assign_eof(VariantParser::Stream*, int&, String&, VariantParser::Tag&, String&, Variant&, VariantParser::ResourceParser*, bool) @ 04f1990e:0xc4a7c
ResourceInteractiveLoaderText::_parse_node_tag(VariantParser::ResourceParser&) @ 04f1990e:0x89aa13
ResourceInteractiveLoaderText::poll() @ 04f1990e:0x899064
ResourceFormatLoader::load(String const&, String const&, Error*) @ 04f1990e:0x8a3e46
ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) @ 04f1990e:0x2c0639
ResourceLoader::load(String const&, String const&, bool, Error*) @ 04f1990e:0x454a0
Main::start() @ 04f1990e:0xb81444
main @ 04f1990e:0x600ac8
Module._main @ tmp_js_export.js:9
callMain @ tmp_js_export.js:9
(anonymous) @ tmp_js_export.js:362
(anonymous) @ tmp_js_export.js:357
Promise.then (async)
Engine.start @ tmp_js_export.js:302
(anonymous) @ tmp_js_export.js:380
Promise.then (async)
Engine.startGame @ tmp_js_export.js:376
(anonymous) @ tmp_js_export.html:270
(anonymous) @ tmp_js_export.html:275
tmp_js_export.js:9 **SCRIPT ERROR**: Assertion failed.
put_char @ tmp_js_export.js:9
write @ tmp_js_export.js:9
write @ tmp_js_export.js:9
doWritev @ tmp_js_export.js:9
_fd_write @ tmp_js_export.js:9
__stdio_write @ 04f1990e:0x6c8560
__vfprintf_internal @ 04f1990e:0x183317
vfprintf @ 04f1990e:0x11f382
StdLogger::logv(char const*, void*, bool) @ 04f1990e:0x807199
Logger::logf_error(char const*, ...) @ 04f1990e:0x152bef
Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xb87dca
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType) @ 04f1990e:0xc7587f
_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType) @ 04f1990e:0x2ca46
_err_print_error(char const*, char const*, int, char const*, ErrorHandlerType) @ 04f1990e:0x29c34
GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) @ 04f1990e:0x9b95e
GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) @ 04f1990e:0x35952f
GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) @ 04f1990e:0xc0bf11
Node::_notification(int) @ 04f1990e:0x2f1072
Node::_notificationv(int, bool) @ 04f1990e:0x5bcbd
CanvasItem::_notificationv(int, bool) @ 04f1990e:0x160dc4
Control::_notificationv(int, bool) @ 04f1990e:0x512ad
RichTextLabel::_notificationv(int, bool) @ 04f1990e:0x89070e
Object::notification(int, bool) @ 04f1990e:0x40e59
Node::_propagate_ready() @ 04f1990e:0x2f05db
Node::_propagate_ready() @ 04f1990e:0x2f0592
Node::_set_tree(SceneTree*) @ 04f1990e:0x110fe5
SceneTree::init() @ 04f1990e:0x8781fb
main @ 04f1990e:0x600aec
Module._main @ tmp_js_export.js:9
callMain @ tmp_js_export.js:9
(anonymous) @ tmp_js_export.js:362
(anonymous) @ tmp_js_export.js:357
Promise.then (async)
Engine.start @ tmp_js_export.js:302
(anonymous) @ tmp_js_export.js:380
Promise.then (async)
Engine.startGame @ tmp_js_export.js:376
(anonymous) @ tmp_js_export.html:270
(anonymous) @ tmp_js_export.html:275
Show 2 more frames
tmp_js_export.js:9    At: res://client.gdc:16:_ready() - Assertion failed.

**Comment by Faless** [comment]
You can't use custom certificates in HTML5 exports:
https://docs.godotengine.org/en/stable/classes/class_crypto.html
https://docs.godotengine.org/en/stable/classes/class_websocketclient.html#property-descriptions

**Comment by Calinou** [comment]
Closing per @Faless' comment.

**Comment by ripperdave** [comment]
Thank you. Any recommendation, workaround?
Usecase: I would have a dedicated server and HTML5 cliens joins from itch.io to the server.

**Comment by Faless** [comment]
> Any recommendation, workaround?

Obtain a browser-trusted certificate for your domain (e.g. via https://letsencrypt.org/).
