### ISSUE TITLE
[3.2.4 beta2]Shadow doesn't work under GLES2 on Mac

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#43779]
**Godot version:**

3.2.4 beta2

**OS/device including version:**

![屏幕快照 2020-11-19 17 06 53](https://user-images.githubusercontent.com/64188282/99910453-1722d580-2d29-11eb-840b-e946164a5c44.png)

**Issue description:**

shadow donesn't work under GLES2 on Mac

I have tested this problem on a Windows PC and everything is ok, also I have tested this problem on 3.2.4 beta1 and everything is ok, so this problem only apperas when using 3.2.4 beta2 on Mac

3.2.4 beta2
![屏幕快照 2020-11-23 01 05 51](https://user-images.githubusercontent.com/64188282/99910788-f6f41600-2d2a-11eb-85de-74054377c187.png)

3.2.4 beta1
![屏幕快照 2020-11-23 01 08 29](https://user-images.githubusercontent.com/64188282/99910794-03786e80-2d2b-11eb-95e2-8d068664a849.png)

**Comment by Calinou** [comment]
@snougo Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by lawnjelly** [comment]
Note bisecting might be easier because there are now artifacts built for the commits, so in many cases no need to build.

https://github.com/godotengine/godot/commits/3.2

* Click on the green tick.
* Mac OS builds - details.
* Artifacts (download artifacts, macOS editor)

**Comment by snougo** [comment]
this bug has be fixed in 3.2.4 beta3

**Comment by snougo** [comment]
I tested this issue again and in some case this problem still appear

if your scene's mesh is imported from DCC tool like blender and if you switch from GLES2 to GLES3 then switch back GLES2 again, shadow won't be rendered until you resart Godot Editor

@Calinou can you reopen this issue again? sorry about that

**Comment by akien-mga** [comment]
That sounds like an unrelated issue, please open a new issue for it.
