### ISSUE TITLE
Add a way to add categories to the script variables section from GDScript

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#4378]
(Inspired by [a question on QA](http://godotengine.org/qa/3196/how-add-subcategories-inspector-script-variables-section))

When doing scripts with a lot of configurable variables, it is nice to be able to group them in the inspector. 

So, instead of having:

```
> Script Variables
| - Not totally unrelated var = false
| - Unrotate children = true
| - Rotate speed = 60
| - Rotate timeout = 100
| - ...
```

We can have

```
> Script Variables
| - Not totally unrelated var = false
| > Rotate
| | - Unrotate children = true
| | - Rotate speed = 60
| | - Rotate timeout = 100
| - ...
```

---

With @kubecz3k we discussed on IRC about how might we do the syntax, and we ended up with the following:
- (1) A new keyword that starts a category
  - Pros: Allows for this issue to be closed
  - Cons: Impossible to end a category, no nesting

``` gd
category rotate
export var unrotate_children = false
```
- (2) An addition to export hints
  - Pros: Not much additional code to be written
  - Cons: You have to retype the name of the category for each variable

``` gd
export("rotate") var unrotate_children = false
export("rotate", float) var rotate_speed = 60
```
- (3) Allow variables with non-identifier names
  - Pros: Stuff like CJK support comes naturally
  - Cons: You have to retype the name of the category for each variable, doesn't look good at all

``` gd
export var "rotate/unrotate_children" = false
```
- (4) Add a keyword that starts a "category block"
  - Pros: Which variable is where is evident from afar, nesting of categories is supported
  - Cons: Raises suspicion on how to get that variable... should it be via `category_name.variable_name`, or just `variable_name`

``` gd
category rotate:
    export var unrotate_children = false
```

@reduz ~ Which one of the four proposals above do you like the most?

**Comment by Zylann** [comment]
Could this be a subset of a more generalist inspector system like Unity?
You could write a whole custom inspector as a class so you can have controls, layout and name the elements the way you like.
Then, export(), annotations etc would just be a shortcut for most of the cases.

**Comment by kubecz3k** [comment]
@Zylann I believe in Unity it's like it's because they cant modify C# directly, while we have the power to adapt our language to the editor. The things you want to do are possible with more complex plugin api.

**Comment by kubecz3k** [comment]
I personally like the 1 option the most, it's the most straightforward and simple to me, the second for me would be 4.

**Comment by Zylann** [comment]
@kubecz3k they use annotations most of the time. But using a custom class also allows to present an inspector that doesn't looks 1:1 as the script, because sometimes a script is too complex to be just presented as its key/value properties. Sometimes you even have popups and contextual buttons, which in Godot are located in the toolbar when you select a node. You need a way to specify that too, and annotations become limited at this :)

**Comment by bojidar-bg** [comment]
@Zylann ~ That's the idea behind editor plugins/addons.

**Comment by akien-mga** [comment]
I'd be for the hint solution, i.e. (2):
```
export("rotate", float) var rotate_speed = 60.0
```
That's the most intuitive syntax IMO, and having to respecify the category for each variable is IMO better than having a new keyword that would needlessly complexify the parser (we'd have to add a ``is_category`` boolean and check against it everywhere in the parser so that we can turn it off at the first occurence of a non ``export`` line).

**Comment by RayKoopa** [comment]
@kubecz3k Unity has its own C# interpreter, it's not Microsoft's, they just try to be as compatible as possible to the "official" C# (but fail at that here and there). They could still be C#-compatible and use attributes for that, so that's probably not the reason they don't do it like that. I guess they wanted a rather "complete" solution for even more specific inspectors.

Anyway, I'd be against the category "block", and would prefer the hint solution (2). Introducing a whole new block feels rather messy than python-esque.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by Barina** [comment]
I would vote for '4. category block' I think it will make the code looks good also

**Comment by SuperUserNameMan** [comment]
As a workaround, and as the inspector respects the orders of my exported variables, to categorize them, i use pseudo-exported vars :

````
export var __R_O_T_A_T_E__ = "----------";
export var unrotate_children = false;
export var rotate_speed = 60.0;
export var __C_A_T_E_G_O_R_Y__2____ = "----------";
export var blablbla = Vector2(5,5);
````

**Comment by hubbyist** [comment]
I have a fifth option by adding an "into" word:

	category rotate
	category foo

	export into rotate var unrotate_children = false
	export into foo var bar = false
	export into rotate var baz = false

also nesting can be possible:

	category rotate
	category foo into rotate

I am not sure about the implementation pros and cons.

**Comment by RayKoopa** [comment]
Everything but not more keywords please. It is of good design to not introduce needless keywords. export(category="blablabla") or anything, just in the context of export, would be more useful.

**Comment by hubbyist** [comment]
What about mixing (2) and (3). Need for retyping category names may be little discouraging

	export ("rotate", float) var rotate_speed = 60
	export ("rotate/limits") var unrotate_children = false
	export ("rotate/limits/axis/z") var max = pi 
	export ("rotate/limits/axis/z") var min = 0
	export ("rotate") var rotate_inside_tree = false

but sort of nested tree as in (4) may eleminate retyping need. 

	export ("rotate"):
		var unrotate_children = false
		export ("limits"):
			var unrotate_children = false
			export ("axis"):
				export ("x"):
					var max = pi
					var min = 0
		var rotate_inside_tree = false

For clarity "export" may be changed with a "category" keyword which implies exporting as well. 

	category ("rotate"):
		var unrotate_children = false
		category ("limits"):
			var unrotate_children = false
			category ("axis"):
				category ("x"):
					var max = pi
					var min = 0
		var rotate_inside_tree = false

But I fear that this solution may be like torturing export hinting mechanism and coders as well. :)

**Comment by bojidar-bg** [comment]
I think retyping the category name is not a really big deal...

**Comment by Zylann** [comment]
I don't like this kind of nesting. It takes metadata to code structure, which can be confusing.
Also, typing again categories is not a big deal, because I will otherwise 1) make a specialized view if needed with an editor plugin, or 2) put variables in a class/resource if they are really many (however it's a bit more tedious currently).

Again, in other languages what I would do is something as simple as an attribute like [Category("This Category")], which is usually a standalone feature that doesn't dictates how different properties should be written.
So in GDScript I would expect something as simple as that, which is currently covered by `export()`, somehow.

btw, what about translation? Maybe sounds crazy, It just went into mind for a second :p

**Comment by hubbyist** [comment]
So in the end something like
	export ("category" type) var name = value
will be simple and sufficient without nesting, and with nesting
	export ("category_path/category" type) var name = value
will do the trick. Am I right?

**Comment by akien-mga** [comment]
@hubbyist Yes, but with a comma separator. There's no existing precedent for a `"category" type` syntax in Godot, I'd expect a parsing error.

So `export("category", type) var name = value`, i.e. (2). That's the most natural in GDScript, and the most flexible IMO. And Godot itself already works around having categorized stuff as "category/subcategory/parameter", so it makes perfect sense.

**Comment by henriquelalves** [comment]
I'm assuming creating the "category" for export like `export("category", type)` will break some compatibility; is someone already working on it for 3.0? This would be a great feature for more complex plugin nodes.

**Comment by Sslaxx** [comment]
Maybe if people are exporting multiple variables to a category, a with type statement/block could make that easier?

```
export with ("category", type):
        var foo
        var baz
```

**Comment by bojidar-bg** [comment]
@henriquelalves I would break _no_ compatibility -- since we would make the category optional.

I have some unpushed local changes concerning it, but the biggest issue with it is not the export syntax -- it is making GDScript code concerning set/get aware of categories.

**Comment by akien-mga** [comment]
I guess it should be made similar to the new property grouping in the inspector for 3.0+.

**Comment by Zylann** [comment]
@nhold while it would make sense, this is not always the best solution. Sometimes you just need to group many variables in categories but still have them in the same class, as well as their getter/setters and associated code.

**Comment by nhold** [comment]
@Zylann Great point, then yeah I would personally prefer both options available as well as sub-classes showing under their own categories.

**Comment by FrederickDesimpel** [comment]
Is this still considered ?

While looking into this, would it also be possible to optionally add limits and other possible properties relevant to the type?

something like:

`export("rotate", float, min: 0, max: 90) var rotate_speed = 60.0`

and maybe even `mid: 45`

would be nice if the system for this is extensible.

**Comment by FrederickDesimpel** [comment]
could be interesting to brainstorm a list of possible 'export arguments'.

like the former, there could be a ui-min and hard-min, to suggest a min value but still possible to override until hard-min.

Not sure if user types are supported too, possibly to restrict what you can set as a nodepath for example ? That one would be a hard one , ie a specific sub type allowed, or a lits of allowed / disallowed types.

**Comment by bojidar-bg** [comment]
@FrederickDesimpel Reading through the [GDScript export docs](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_exports.html) might be helpful -- `min`/`max` hints for floats are already supported (and ui-min/max would be through something like #32935).

**Comment by ChronoDK** [comment]
> As a workaround, and as the inspector respects the orders of my exported variables, to categorize them, i use pseudo-exported vars as separators :
> 
> ```
> export var __R_O_T_A_T_E__ = "----------";
> export var unrotate_children = false;
> export var rotate_speed = 60.0;
> export var __C_A_T_E_G_O_R_Y__2____ = "----------";
> export var blablbla = Vector2(5,5);
> ```

Sadly this is actually the only easy/practical way to group export vars.

**Comment by LightningAA** [comment]
This should be closed in favor of https://github.com/godotengine/godot-proposals/issues/1255
