### ISSUE TITLE
Godot crashes on start

### ISSUE THREAD

**Issue by dakennedyd** [godotengine/godot#43787]
Godot version: 4.0.dev.custom_build.6bd4074f7
commit hash:6bd4074f769b9fd1eb4c4e06bf83a414f9d4ecc7

OS/device: Ubuntu 16.04
GPU: NVIDIA 750ti.(proprietary driver)
NVIDIA binary driver version 384.130

Issue description: It crashes on start giving this ouput.
> Godot Engine v4.0.dev.custom_build.6bd4074f7 - https://godotengine.org
DisplayServer::_create_window 0 want rect: 208, 150, 1024, 600 got rect 208, 150, 1024, 600
Segmentation fault (core dumped)

Steps to reproduce: Just run the executable godot.linuxbsd.tools.64

**Comment by akien-mga** [comment]
It's very likely that NVIDIA drivers 384.130 are too old to support Vulkan.

I would suggest upgrading to a more recent Ubuntu version if you can. We likely won't be able to support Ubuntu 16.04 in 4.0 until OpenGL support is reimplemented (Vulkan 1.0 was released in 2016, and Ubuntu is not typically cutting edge.)

**Comment by akien-mga** [comment]
Also to clarify, the crash itself is still a bug, but I think we already have another report tracking it. Eventually we'll implement a proper check for Vulkan support to show an error dialog if it's not suitable, instead of crashing.
