### ISSUE TITLE
class_name doesn't show icon when using png

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#43805]
**Godot version:**

3.2.3

**OS/device including version:**

Zorin OS 15.3 Nvidia GTX 650, GLES3

**Issue description:**

class_name doesn't show icons

**Steps to reproduce:**
- Create a script with the following.. `class_name Test, "res://test.png" extends Node`
- Try to add it through the scene explorer
- See that the icon is invisible 

**Minimal reproduction project:**

[IconBug.zip](https://github.com/godotengine/godot/files/5585797/IconBug.zip)

**Comment by Calinou** [comment]
I can see it here:

![image](https://user-images.githubusercontent.com/180032/100025312-cffc1980-2de8-11eb-840e-0fed95c20d0b.png)

Maybe it only appears after restarting the editor?

Also, the "proper" way to define a named class with regard to the GDScript style guide is:

```gdscript
extends Node
class_name Test, "res://test.png"
```

**Comment by Shadowblitz16** [comment]
@Calinou thats looks so ugly though!
Also even that doesn't work..
![image](https://user-images.githubusercontent.com/2453707/100025481-bc779100-2d9d-11eb-88ec-e6651b3690e3.png)

**Comment by Reneator** [comment]
Works for me as well with 3.2.3:

![image](https://user-images.githubusercontent.com/24807557/100067222-496e2900-2e36-11eb-9065-00cb01fe6567.png)

**Comment by akien-mga** [comment]
Works here too. Maybe you have a caching issue? Check permissions on and contents of `~/.cache/godot/`. The icon should have a matching `resthumb-<hash>.png` and `resthumb-<hash>_small.png` matching your `network.png`.

**Comment by Shadowblitz16** [comment]
I seem to have multiple of them at least 4 and I've only used it in 2 projects

**Comment by Shadowblitz16** [comment]
![image](https://user-images.githubusercontent.com/2453707/100144702-0323c480-2e4c-11eb-98f0-498d0ed34d50.png)
![image](https://user-images.githubusercontent.com/2453707/100144722-0ae36900-2e4c-11eb-916a-bd00b5185876.png)
![image](https://user-images.githubusercontent.com/2453707/100144749-16cf2b00-2e4c-11eb-9c1b-d71aa6c73f16.png)
![image](https://user-images.githubusercontent.com/2453707/100144779-22225680-2e4c-11eb-8dca-fc406cee9d85.png)
![image](https://user-images.githubusercontent.com/2453707/100144820-323a3600-2e4c-11eb-8378-71765e734589.png)

**Comment by akien-mga** [comment]
File permissions seem OK, not sure why it wouldn't work for you.

It works fine here, but note that there's a bug which makes script class icons not work right after you declare them, you need to restart the editor to have them properly loaded (that's #35896).

**Comment by Shadowblitz16** [comment]
I am closing this because I switch back to windows 10. if I ever return I will reopen
