### ISSUE TITLE
Control Nodes prevent CollisionObject2D from detecting Mouse

### ISSUE THREAD

**Issue by Schweini07** [godotengine/godot#43814]
**Godot version:**
3.2.3-stable

**OS/device including version:**
Manjaro 20.2

**Issue description:**
I have a HUD which prevents a StaticBody2D from detecting if the mouse entered or exits the 

![2020-11-24 12-19-56](https://user-images.githubusercontent.com/47503977/100087955-bcd06480-2e4f-11eb-8491-a6b2eddd1f72.gif)
(Pardon me for the bad GIF quality)

**Steps to reproduce:**
1. Create a Control node whose layout is on `Full Rect`
2. Create a body that inherits from CollisionObject2D and add a CollisionShape2D
3. Create the `mouse_entered` signal from the body
4. Start the project, the signal will not be fired

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Did you set the mouse filter to `PASS`?

**Comment by Schweini07** [comment]
I set it to all 3 different modes, it never worked.

**Comment by akien-mga** [comment]
It works for me with Mouse Filter "Ignore" and setting "Input Pickable" on the CollisionObject2D as described in the documentation for this signal: https://docs.godotengine.org/en/stable/classes/class_collisionobject2d.html#signals

See https://docs.godotengine.org/en/stable/classes/class_control.html#enum-control-mousefilter for Mouse Filter documentation.

**Comment by Schweini07** [comment]
[Test.zip](https://github.com/godotengine/godot/files/5589599/Test.zip)

Could you try this project still?
I set everything so it should work, but it doesn't.

**Comment by Schweini07** [comment]
The test project I created for this works suddenly now, I guess I'll have to try to do the same thing in my personal project, thanks!

**Comment by Schweini07** [comment]
I set everything to "Ignore" and it works now, thank you!
