### ISSUE TITLE
Android Export : 'Use Custom Build' option DOES NOT USE 'Custom Template' setttings, for android_debug.apk and android_release.apk

### ISSUE THREAD

**Issue by ginobean** [godotengine/godot#43817]
**Godot version:**

3.2.3.stable

**OS/device including version:**

Linux, Android, GLES2.

**Issue description:**

I enabled the Android export option: 'Use Custom Build'. I also specified custom templates, for both the debug and release versions, as I wanted to use script encryption.

When I built and deployed the resulting app, on my Android device, it was UNABLE to read the encrypted scripts. 

As a check, I unset the 'Use Custom Build' option only, and then was able to run my app fine, which indicates that the custom templates I had built, to use scrip encryption, were working fine.

Looking into this matter, it looks like the custom build option, instead of using the custom build templates (<custom_location>/android_debug.apk and <custom_location>/android_release.apk), were actually using .aar files from 
the project's local 
        android/build/libs/debug/godot-lib.debug.aar 
and android/build/libs/release/godot-lib.release.aar

As a further test and workaround, I copied my custom built godot engine's .aar files (which incorporated the script encryption) to the aforementioned locations, and was able to get my app to run successfully..

Ideally, the 'Use Custom Build' option should be able to pick up the custom templates and use them, if they are specified.

As it is now, the combo of 'Use Combo Build' and custom templates, for Android export, doesn't really work as one would expect..

**Comment by Calinou** [comment]
When you use a custom build, you won't be using pre-built APK files as they will be built during the export process (using Gradle). Therefore, the Custom Template section simply can't be made to work in this case.

**Comment by ginobean** [comment]
I'm not all that familiar with AAR files, but couldn't you dynamically generate suitable AAR files from the custom apk templates? 
Then, it would effectively work as users would expect it to work..

**Comment by m4gr3d** [comment]
> I'm not all that familiar with AAR files, but couldn't you dynamically generate suitable AAR files from the custom apk templates?

@ginobean At build time, the `aar` files are unpacked within the `apk`, so once you have the final `apk`, it's not possible to retrieve the `aar` from it.

**Comment by kristijandraca** [comment]
Documentation should be more clear about this. There is no mention that you can't mix android build templates with custom apks

**Comment by Calinou** [comment]
@kristijandraca Feel free to open a pull request to update the [documentation](https://github.com/godotengine/godot-docs/blob/master/tutorials/export/exporting_for_android.rst) :slightly_smiling_face:

**Comment by serogbp** [comment]
Hi, I have a Godot Android project (Godot 3.3.2.stable) with [NativeLib](https://github.com/DrMoriarty/nativelib) and some plugins.
I wanted to use script encryption but I can't get it to work (with custom export templates and the encryption key).

I was about to open a new issue.

If I understand correctly, does this issue mean that you can't use script encryption and plugins together? 

Thanks in advance

**Comment by kristijandraca** [comment]
@serogbp try to build a custom export template for debug and release, and instead of using them, just replace android/build/libs aar files with ones that you generated with custom export.

**Comment by serogbp** [comment]
Thank you so much @kristijandraca, it worked!

**Comment by blurrred** [comment]
Thank you so much @kristijandraca. I have been struggling with this for weeks and it was the only thing keeping me from releasing my app. Thank you, thank you, thank you.

**Comment by randazzle** [comment]
I believe the mentioned issue exists in 3.4 stable as well, since I've been trying to get it to work as well.

Also thank you @kristijandraca . Your solution worked for me as well!

**Comment by Calinou** [comment]
@randazzle Feel free to open a pull request to update the [documentation](https://github.com/godotengine/godot-docs/blob/master/tutorials/export/exporting_for_android.rst) :slightly_smiling_face:

**Comment by WoodShack** [comment]
> @serogbp try to build a custom export template for debug and release, and instead of using them, just replace android/build/libs aar files with ones that you generated with custom export.

THANK YOU!!!

**Comment by m4gr3d** [comment]
`Custom Build` has been renamed to `Gradle Build` in Godot 4.x, which should resolve the confusion about assuming it's related to `Custom templates`.
