### ISSUE TITLE
[FBX] Bones in an FBX Skeleton are in random or arbitrary order

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#43825]
**Godot version:**
3.2.4 beta2

**OS/device including version:**
Windows 10.0.19041.630
NVidia GeForce RTX 2080 Ti 452.06

**Issue description:**
In beta2, imported files show bones added in an arbitrary order, seemingly randomly. My expectation is that parent bones in a skeleton are added before their children, in some sort of traversal order.

Sure, it can be argued that this is not a bug: that the order of bones in a skeleton is unspecified.

I'm filing this bug because this change could break compatibility with code that iterates through a skeleton, assuming parent bones were already processed before hitting child bones.

Another reason this matters to me is because the good skeleton inspector was not yet backported to 3.2, and the old skeleton inspector requires that you guess which bone you're looking at, and having them in order helps significantly.

![image](https://user-images.githubusercontent.com/39946030/100116929-2426ee00-2e29-11eb-859d-103af9551865.png)

**Steps to reproduce:**
1. Open the attached project.
2. Click Bunny_Farmer.fbx and click Reimport in the import panel.
3. Open the imported scene.
4. Select the Rabbit_Skeleton object.
5. Select bones in order. Notice that the order does not start with Body, and "Leg" is between "Pinky" and "Index", for example.

**Minimal reproduction project:**
[fbx_issues.zip](https://github.com/godotengine/godot/files/5590831/fbx_issues.zip)

**Comment by RevoluPowered** [comment]
Ordering is based on the FBX ID and the node order on export.

What exporter/package are you using: blender, maya, 3ds max?

**Comment by RevoluPowered** [comment]
I need a bit more info about how the file was made to know what to test this in; can you please let me know the above info?

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
