### ISSUE TITLE
ClassDB::add_property does not support setters with optional secondary arguments

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#43821]
**Godot version:**

Latest on both branches
3.2.3 279f4fbb5f83c2df6e8499799a2aa0c14f85aa2d
4.0 32b31a5

**OS/device including version:**

N/A

**Issue description:**

I'm creating a C++ module that adds new nodes with properties.

One of my setters has a signature with an optional second parameter, e.g.
```cpp
void set_somevalue(int p_value, bool p_force_update = true);
```
However, `ClassDB::add_property` (with `DEBUG_METHODS_ENABLED` defined) enters a fail condition and spits out "Invalid function for setter ..." because the expected number of arguments is one (or two for indexed setters).

Optional second parameters in GDScript are supported, but not in core. If possible, core should allow this.

**Steps to reproduce:**
In a custom module, create/register a new Node derived class. In `_bind_methods`, add a property:
```cpp
ClassDB::bind_method(D_METHOD("set_somevalue", "somevalue", "force_update"), &MyNode::set_somevalue, DEFVAL(true));
ClassDB::bind_method(D_METHOD("get_somevalue"), &MyNode::get_somevalue);
ADD_PROPERTY(PropertyInfo(Variant::somevariant, "somevalue"), "set_somevalue", "get_somevalue");
```

**Minimal reproduction project:**

N/A

**Comment by Xrayez** [comment]
I can at least confirm that I've stumbled upon this limitation before in C++.

Also, I didn't know that it's possible to bind a setter with default argument in GDScript. So, unless it doesn't break other language bindings, I don't see a reason why this cannot be allowed, in fact this should be made possible according to mostly trivial changes in #43831. 🙂

But if I were you, I'd separate the responsibility of those methods from:
```c++
void set_somevalue(int p_value, bool p_force_update = true);
```
to:
```c++
void set_somevalue(int p_value);
void force_update_value(int p_value);
```

**Comment by reduz** [comment]
As I mentioned in the PR, this is by design to make language binding simpler, so it should be closed (and likely explained in a comment in the source code).
