### ISSUE TITLE
[FBX] Duplicate Spatial nodes created for every Skeleton bone.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#43822]
**Godot version:**
3.2.4 beta2

**OS/device including version:**
Windows 10.0.19041.630
NVidia GeForce RTX 2080 Ti 452.06

**Issue description:**
Unused Spatial nodes added for every node in the skeleton, even if they are also created as bones.
![image](https://user-images.githubusercontent.com/39946030/100112590-40745c00-2e24-11eb-8f10-4670314b1e64.png)

The biggest issue with this is that the duplicate nodes cause a name conflict with the bones, and lead all bones to have _1 in their names (see issue #43820 ). These spatial nodes should not exist. If they must exist for some reason, they should be created as BoneAttachment, not ordinary Spatial nodes.

The expected behavior is that no spatial nodes are created if no spatials are needed.

**In the specific case that an FBX had leaf bones / end bones**, the old behavior was also incorrect: it added all end bones as children of each other in a non-sensical way. However, if the leaf bones were unused, they could have been safely ignored or deleted.

The old behavior wasn't good, but the new behavior is far worse, and affects files without leaf bones, too. Regardless of which bones are decided to be included, it is never appropriate to expose bones as plain Spatial nodes. Any nodes added as children of a skeleton should be BoneAttachment objects in Godot.

**Steps to reproduce:**
1. Open the attached project.
2. Click Bunny_Farmer.fbx and click Reimport in the import panel.
3. Open the imported scene.
4. Notice that the hierarchy includes duplicate copies of bones, as plain Spatial nodes.

**Minimal reproduction project:**
[fbx_issues.zip](https://github.com/godotengine/godot/files/5590831/fbx_issues.zip)

**Comment by RevoluPowered** [comment]
We can remove this but it's missing bone attachment creation for constraints they're kept for compatibility with node animations mixed with bone animations from Maya. Some constraint creations would fail without this even with bone attachments.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
