### ISSUE TITLE
[FBX] All bones have _1 at the end of their names.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#43820]
**Godot version:**
3.2.4 beta2

**OS/device including version:**
Windows 10.0.19041.630
NVidia GeForce RTX 2080 Ti 452.06

**Issue description:**
Bones in skeleton have _1 added to the end of their names.

This is a bug because it breaks compatibility with existing projects: any existing animation targeting a FBX bone is no longer valid after upgrade to 3.2.4beta2 and must target bonename_1 instead.

Even if the compatibility breakage is not considered an issue, it seems undesirable to necessarily have extra text appended to all bone names just because it was imported from FBX.

![image](https://user-images.githubusercontent.com/39946030/100114201-06a45500-2e26-11eb-8f4d-271ba9fa2e25.png)

**Steps to reproduce:**
1. Open the attached project.
2. Click Bunny_Farmer.fbx and click Reimport in the import panel.
3. Open the imported scene.
4. Select the Rabbit_Skeleton object.
5. Select any bone. Notice that the names of all bones have _1 when running 3.2.4beta2.

**Minimal reproduction project:**
[fbx_issues.zip](https://github.com/godotengine/godot/files/5590831/fbx_issues.zip)

**Comment by RevoluPowered** [comment]
So the safest bet would be if we had UUID for this, it's to prevent breakage, I'll see if we can remove it or improve the uniqueness check.

**Comment by akien-mga** [comment]
Fixed by #46576 and #47458.
