### ISSUE TITLE
_gui_input(event) didn't realize finger release with multi-touch

### ISSUE THREAD

**Issue by nongvantinh** [godotengine/godot#43829]
**Godot version:**

v3.2.3.stable.mono.official 

**OS/device including version:**

Windows 10 Pro

**Issue description:**

_gui_input(event) didn't recognize input release with multi touch.

**Steps to reproduce:**
1) touch in TextureRect 0 -> touch in TextureRect 1  -> touch in TextureRect 2.
2) the `_gui_input event.pressed = true `as normal.
3) release finger 2 ->release finger 1 ->release finger 0
4) only sprite 0 `_gui_input  event.pressed = false `get called.
5) the order of finger release does not matter.
![Screenshot (29)](https://user-images.githubusercontent.com/53887662/100128322-b9ba9000-2eb2-11eb-818c-81789f65e02e.png)

**Minimal reproduction project:**

[GuiInputBug.zip](https://github.com/godotengine/godot/files/5591545/GuiInputBug.zip)

**Comment by nongvantinh** [comment]
Is there any guide on this?

**Comment by Sauermann** [comment]
This could be a duplicate of #29525

**Comment by nongvantinh** [comment]
Could not reproduce in 4.2. This error has been fixed.
