### ISSUE TITLE
"get_material()" function for EditorSpatialGizmoPlugin expects two arguments even though the documentation says the second should be optional

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#43832]
**Godot version:**
3.2.3.Stable

**OS/device including version:**
NA

**Issue description:**
"get_material()" function for EditorSpatialGizmoPlugin expects two arguments even though the documentation says the second should be optional
![image](https://user-images.githubusercontent.com/4955051/100145998-1dcc5c80-2e91-11eb-9ed0-926954b60792.png)
![image](https://user-images.githubusercontent.com/4955051/100146046-3177c300-2e91-11eb-84eb-9cf16acc98b5.png)
https://docs.godotengine.org/en/3.2/classes/class_editorspatialgizmoplugin.html#class-editorspatialgizmoplugin-method-get-material

**Steps to reproduce:**
Attempt the function call.

**Minimal reproduction project:**
NA

**Comment by Calinou** [comment]
The documentation is written in an ambiguous way, but the second argument *is* required. That said, you should be able to provide `null` as a value for the second argument.

**Comment by akien-mga** [comment]
The code was written with the intent to give it a default value: https://github.com/godotengine/godot/blob/3.2/editor/plugins/spatial_editor_plugin.cpp#L6851

But for some reason it's always been commented out. CC @JFonS.

**Comment by JFonS** [comment]
I wrote this code so long ago I don't even remember why it was commented. I did some testing and everything seems to work fine when uncommented, so I opened #43861.
