### ISSUE TITLE
Bezier tracks can't fade in/out animations with AnimationTree

### ISSUE THREAD

**Issue by mmonart** [godotengine/godot#43848]
**Godot version:**
3,2,2

**OS/device including version:**
Windows 10 , RTX 2080 Super GLS2

**Issue description:**
OneShot node can't fade in/out animations where one animation from animationPlayer is made "normal" and second have animation based on Bezier key's 

**Steps to reproduce:**
repro in zip file

**Minimal reproduction project:**
[oneShot_issue.zip](https://github.com/godotengine/godot/files/5595277/oneShot_issue.zip)

select AnimationTree and test OneShot nodes

**Comment by sketchyfun** [comment]
It doesn't seem to be related to OneShot, but bezier tracks in general, as I've just stumbled over this bug myself while trying to use the xfade on an animationtree with a state machine. Fading between two normal tracks worked fine, but as soon as I tried to fade from a bezier version of the animation to a regular one,  no fading happens at all.
