### ISSUE TITLE
_input_event(event) is called after _input(event)

### ISSUE THREAD

**Issue by UltyX** [godotengine/godot#4384]
Linux x64

According to the documentation the call order for input events is  _input_event(event) then _input(event) as described here:
http://docs.godotengine.org/en/latest/tutorials/engine/inputevent.html
But _input(event) is always called before _input_event(event)

![bug](https://cloud.githubusercontent.com/assets/12592569/14685934/f77d510a-0736-11e6-8c21-fe7455c37996.png)

tested in 1.1 stable 2.0 stable 2.0.2 stable and compiled from source 19.4.2016 under Linux x64

minimal example 
[input_eve.zip](https://github.com/godotengine/godot/files/228586/input_eve.zip)

**Comment by Biliogadafr** [comment]
The same problem in 2.0.3. 
This makes hard to have mouse interactions in game and some UI at the same time. For example: if some UI button is pressed, game will handle _input() of other nodes and do their logic(for example spawn monster at mouse position), and after this engine will invoke _input_event() of the button, call signals of the button and so on, so monster will be spawned under button, and it is too late to call accept_event() or set_input_as_handled()

**Comment by reduz** [comment]
right, this is a bug resulting in the recent rewrite of the gui for 2.0

**Comment by reduz** [comment]
Sorry, I misunderstood this. This is not a bug and was reverted. The documentation will have to be updated..

**Comment by reduz** [comment]
For reference, it is allright that _input() is called before _input_event()

The correct order is _input() -> _input_event() -> _unhandled_input()

For implementing game code that uses fullscreen, but that needs to stop working if GUI is active, replace your _input() by _unhandled_input()

**Comment by reduz** [comment]
Doc has been updated
