### ISSUE TITLE
[3.2.4 Beta 2] Layout does not work on HTML5 export unless the browser is resized

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#43845]
Godot version:
3.2.4 Beta 2

OS/device including version:
HTML5 export with GLES2 on Firefox/Chromium Edge

Issue description:
When I export my web game on 3.2.4, the layout configuration does not work as it does in 3.2.3. However, if I resize the browser size a bit, it does work perfectly again.

Steps to reproduce:
Create a Control node, then add a Grid node with some Buttons as its children. Select Full Rect among Layout options for the Control and Grid nodes, and set Size Flag for the Buttons to Fill and Expand. Export the project to HTML5, then you will see unexpected UI layout. But if you resize the browser, the layout becomes normal again.

Minimal reproduction project:
[test.zip](https://github.com/godotengine/godot/files/5595187/test.zip)

**Comment by Faless** [comment]
I'm unable to reproduce, can you provide a screenshot of what you see?
What OS are you on? What GPU?

**Comment by Faless** [comment]
Cannot reproduce on Window 10 with FF 83 and Edge 87 either.
GPU: NVidia GTX 980

**Comment by floppyhammer** [comment]
I tested both on Windows 10 20H2 and on Ubuntu 20.04 (a different machine). The issue only exists on Windows for both Firefox and New Edge but not on Ubuntu for Firefox. More importantly, when I access the HTML page on my mobile with Android 10 (via both Firefox and Edge), I still got the issue no matter which OS I use to export and host the game.

OS/device including version:
Windows 10 20H2 (NVIDIA GeForce MX250)/Ubuntu 20.04 (NVIDIA GeForce GTX 750)

Screenshots:
Firefox before resizing the browser
<img width="1080" alt="Firefox_before_resizing" src="https://user-images.githubusercontent.com/28705694/100295381-6d5f7500-2fc4-11eb-99c8-d86f57037289.png">

Firefox after resizing the browser
<img width="1080" alt="Firefox_after_resizing" src="https://user-images.githubusercontent.com/28705694/100295392-77817380-2fc4-11eb-9c22-32d39f1bd599.png">

Edge before resizing the browser
<img width="1080" alt="Edge_before_resizing" src="https://user-images.githubusercontent.com/28705694/100295749-52413500-2fc5-11eb-9ec0-db3e7d936e4d.png">

Edge after resizing the browser
<img width="1080" alt="Edge_after_resizing" src="https://user-images.githubusercontent.com/28705694/100295408-836d3580-2fc4-11eb-9551-eead1cae59b1.png">

Android Firefox before rotating the screen (as resizing is not possible on mobile)
![Android_Firefox_before_rotating_screen](https://user-images.githubusercontent.com/28705694/100295774-70a73080-2fc5-11eb-80b9-547a1879e45d.jpg)

Android Firefox after rotating the screen
![Android_Firefox_before_rotating_screen](https://user-images.githubusercontent.com/28705694/100295782-79980200-2fc5-11eb-8f0c-b63e348a2a7b.jpg)

**Comment by gianmichelemariani** [comment]
Confirming this happens on OSX 10.15.7 (catalina) on a macbook pro (intel iris 640 gpu) as well. 
On first launch (both with the runnable project and by exporting debug/release builds) the created screen is huge (4 times the size of the window). Once you start resizing the window it then conforms properly.

<img width="1910" alt="Screenshot 2020-11-27 at 14 58 25" src="https://user-images.githubusercontent.com/46694168/100461912-5783aa00-30c1-11eb-85ba-e73952fc281a.png">

**Comment by Faless** [comment]
I can reproduce on Android, I'll investigate. I'm pretty sure this is about devicePixelRatio detection.

**Comment by gianmichelemariani** [comment]
Yeah I figured. Forgot to mention that I've tried with both the hidpi option on and off

**Comment by floppyhammer** [comment]
In addition, this issue causes "OS.window_size" to be larger than your actual window size no matter Hidpi in Project Settings is enabled or not. But it can be temporarily solved by using "OS.set_window_maximized(true)", provided that you disable Hidpi. And when Hidpi is enabled, this solution renders it ineffective unless the window is resized.

**Comment by Faless** [comment]
When I say HiDPI, I mean HiDPI monitor, not the setting.
