### ISSUE TITLE
Game window appears behind window where game was opened (including IDE)

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#43840]
I was unable to find any other bugs quite like this.

**Godot version:**
3.2.4.beta2 (this does *not* occur in beta1, implying a possible regression of some kind to me)

**OS/device including version:**
macOS Catalina v10.15.5, running a GLES3 app.

**Issue description:**
If I run my game from the editor, the game window itself now appears behind the editor itself - I have to go find it and click on the game icon at the bottom in the program bar to get it to come to the front.

In addition to this, if I'm for instance running my exported game from a folder on my computer, the game appears behind the folder from which I launched it.

I turned off batching to see if that was related, but it is not. I tried several things related to graphics, got nothing, so suspect this is somewhere in the windowing code.

**Steps to reproduce:**
1: Own a mac (and be sad about it)
2: Start a new project
3: Create a scene, make it the main scene on startup
4: Run the game - game will appear behind Godot

**Minimal reproduction project:**
This happens with all projects I'm building currently as well as a dummy project that literally just had a single scene with nothing in it, so I suspect it doesn't require a repro project itself. Happy to provide it though if absolutely necessary.

**Comment by WolfgangSenff** [comment]
Actually, just noticed this was merged: https://github.com/godotengine/godot/pull/43678 Any relation? Seems like it could be a focus-stealing artifact.

I have discovered a work-around: turn on Always on Top. It's not my favorite setting to use for obvious reasons, but it does work to fix the exact issue mentioned.

**Comment by akien-mga** [comment]
#43678 fixed this, this issue is the same as #43675.
