### ISSUE TITLE
[FBX] Weird graphical artifacts in rigged mesh instance imported from Maya 2016 exported FBX file.

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#43846]
**Godot version:**
Tried with both Godot 3.2.3-stable and 3.2.4-beta2

**OS/device including version:**

Windows 10 Pro, NVIDIA RTX 3080, GLES3

**Issue description:**
When importing an FBX file with 2 meshes and a rig created in Maya 2016, the import succeeds with the following hierarchy:
<img width="382" alt="hierarchy" src="https://user-images.githubusercontent.com/1424843/100199106-93482500-2eb1-11eb-80c6-35cb3202f7e9.PNG">

In both the editor and game viewports, however, The following rendering issue of the mesh is observed:
<img width="469" alt="weird_cull" src="https://user-images.githubusercontent.com/1424843/100199159-aa871280-2eb1-11eb-866c-17da9bd230f8.PNG">

I've ensured back-face culling is enabled on the material.
I've also observed the following:

1. If I clear the skin from the body MeshInstance, the issue persists
2. If I unassigned the skeleton from the body MeshInstance (regardless of whether skin resource is still assigned or not) the issue goes away.
3. If I import the FBX file into blender it seems fine. Same for Paint3D on Windows.
4. If I export the FBX file as a glTF from Blender and import into Godot, it works fine.
5. If I export the FBX file as another FBX file from Blender and import _that_ into Godot, the rig is entirely fubar, but I believe this is an entirely separate issue.

From all of these observations, I can conclude that there is something very peculiar happening when importing an FBX file created in Maya 2016 specifically (and possibly other versions of Maya as well--I don't have any other versions on hand to test).

Here is a log file of the verbose (-v) output when importing. No errors--everything seems to have imported fine:
[import.log](https://github.com/godotengine/godot/files/5595298/import.log)

**Steps to reproduce:**
I'm not sure if it's something unique to this mesh or not and I am unable to share the FBX file in question publicly. I can provide it privately to a Godot dev if needed for testing, however.

All I did was import said FBX file into Godot and view it in the editor viewport (though it also occurs when running a game).

**Minimal reproduction project:**
See above. Can't share FBX file publicly, but can provide privately if needed.

**Comment by jonbonazza** [comment]
I guess it should also be noted that I just tried it in master (godot 4.0) using the Vulkan renderer and in this case, the rig is entirely fubar, so it doesn't work at all. Likely unrelated.

**Comment by RevoluPowered** [comment]
Thank's I'll look into this next week :)

**Comment by RevoluPowered** [comment]
Took longer than I thought to even look into this, I'll check it now.

**Comment by RevoluPowered** [comment]
#43921 This is resolved in this PR

**Comment by RevoluPowered** [comment]
![image](https://user-images.githubusercontent.com/748770/101820098-0a222680-3b1e-11eb-93bb-5c249f96de3d.png)

**Comment by akien-mga** [comment]
Fixed by #43921.
