### ISSUE TITLE
Invalid call, even though the method exists (in plugin)

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#43853]
**Godot version:**

3.2.4 beta2

**Issue description:**

So I have a typical editor plugin for specific nodes. When I try to call a method on the handled node, it says `Invalid call. Nonexistent function`, even though the method exists. I stripped down everything as much as I could and the error persists. The worst thing is this:
```
print("Trying to call the test method")
print("Is it correct class? ", map_importer_handle is MapConverter)
print("Does the method exist? ", map_importer_handle.has_method("test_func"))
map_importer_handle.test_func()
```
And the output is:
```
Trying to call the test method
Is it correct class? True
Does the method exist? True
 res://addons/MapImporterPlugin/MapImporterPlugin.gd:60 - Invalid call. Nonexistent function 'test_func' in base 'Node2D (map_lut_conveter.gd)'.
```
So Godot literally tells me that the method exists, but it can't call it. Even with `call`. I literally have no idea what is happening here.

**Minimal reproduction project:**

[godot_project.zip](https://github.com/godotengine/godot/files/5596799/godot_project.zip)
Click the plus icon on the right and click on the image. The error will appear.

**Comment by akien-mga** [comment]
The script which defines `test_func` should be a `tool` script if you want it to run in the editor. If not, the method effectively doesn't exist.

The fact that `has_method` returns true might be the bug.

**Comment by KoBeWi** [comment]
Ah, right.

> The fact that has_method returns true might be the bug.

This can be useful actually. If the method exists but call fails, the error could tell that you are probably missing `tool`.

**Comment by lyuma** [comment]
Still reproducible on Godot master 85186bc, though as noted, adding `@tool` to map_lut_converter.gd allows the function to be called.
Anyway here's the 4.0 test project: [godot_project_4.0.zip](https://github.com/godotengine/godot/files/6943187/godot_project_4.0.zip)

Not sure this is a major issue given that using `@tool` is the correct thing to do

**Comment by KoBeWi** [comment]
> Not sure this is a major issue given that using tool is the correct thing to do

This is not a major issue. We could just improve the error message.

**Comment by KoBeWi** [comment]
This is actually duplicate of #36592
