### ISSUE TITLE
Godot show error when opening project first time

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43859]
**Godot version:**
4.0.dev.custom_build. 6dfcc4aa8

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When opening first time project, Godot shows that scene is corrupted and cannot be opened.
When opening same scene manually from file system dock, then everything works fine.

**Steps to reproduce:**
1. Open editor - error should be shown
2. Open scene manually - no error
3. Open editor second time - no error

To see error once again just clear godot cache
```
#!/bin/bash
path="/home/rafal/"
rm -rf $path".godot"
rm -rf $path".cache/godot"
rm -rf $path".config/godot/projects"
rm -rf $path".local/share/godot"
```

**Minimal reproduction project:**
[MainScenes.zip](https://github.com/godotengine/godot/files/5598214/MainScenes.zip)

**Comment by akien-mga** [comment]
To clarify, the scene is invalid as it references a non-existing NodePath.

But indeed after a first error it then opens OK (and just spams the console with errors at each refresh).

That might be related to the generation of the scene preview for the filesystem dock or the generation of some project metadata indeed.

**Comment by qarmin** [comment]
Looks that non existent Nodepath is not an issue, because when I delete remove it, then errors doesn't disappear - [MainScenes.zip](https://github.com/godotengine/godot/files/5598518/MainScenes.zip)

Problem is probably with invalid sequence of items to load, because looks that Godot try to open 3DALL.tscn scene before opening 3DALL.gd file
```
ERROR: res://MainScenes/3DALL.tscn:6 - Parse Error: [ext_resource] referenced non-loaded resource at: res://MainScenes/3DALL.gd
   at: _parse_node_tag (scene/resources/resource_format_text.cpp:282)
ERROR: Failed loading resource: res://MainScenes/3DALL.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:198)
```

**Comment by akien-mga** [comment]
As I said, your GDScript doesn't compile, so it can't be loaded as Resource and thus the `.tscn` that references it fails loading.

`if ! some_bool:` doesn't compile in `master` (that's a bug). Change it to `if some_bool == false` (or remove the script).

**Comment by KoBeWi** [comment]
Still valid in c77bbde
Although the editor now properly shows the missing dependencies dialog. When you Open Anyway, everything works fine.

**Comment by bitbrain** [comment]
This also seems to happen when checking out a project for the first time that has been setup with Godot 4 on a different machine:
```
ERROR: Unable to open file: res://.godot/imported/icon.png-ab93c23a059afd5b316ae16028606cb0.ctex.
   at: (scene\resources\texture.cpp:824)
ERROR: Failed loading resource: res://.godot/imported/icon.png-ab93c23a059afd5b316ae16028606cb0.ctex. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core\io\resource_loader.cpp:222)
ERROR: Failed loading resource: res://addons/godot-event-bus/icon.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core\io\resource_loader.cpp:222)
SCRIPT ERROR: Parse Error: Could not preload resource file "res://addons/godot-event-bus/icon.png".
```
The only way for me to fix this at the moment is to let Godot crash around 9-10 times and eventually it "just works"

**Comment by KoBeWi** [comment]
The error does not seem to appear anymore in the attached project on master (19c9fd6)
@qarmin Can you confirm?

**Comment by KoBeWi** [comment]
Well, comment if you can still reproduce.
