### ISSUE TITLE
3D Collision Shape Crash

### ISSUE THREAD

**Issue by TesserWreck** [godotengine/godot#4385]
**Operating system or device:**
Windows 8
Lenovo Z580 ideapad

**Issue description** (what happened, and what was expected):
Changing the the shape on a CollisionShape node causes Godot to crash.

**Steps to reproduce:**
Create a new project.
Add a root node.
Add a CollisionShape node.
Change the shape of the node.
Crash.

**Comment by nunodonato** [comment]
can't reproduce. what version are you one?

**Comment by TesserWreck** [comment]
Turns out after taking an update most of my programs don't work properly.
I resorted a backup and re-downloaded the update and Godot.
Everything now works correctly.
Thanks Microsoft.
