### ISSUE TITLE
Mac OS X hotkeys don't work right for the Dvorak - QWERTY ⌘ layout

### ISSUE THREAD

**Issue by all-iver** [godotengine/godot#4386]
This is on Mac OS X 10.11.4.  I use a keyboard layout called "Dvorak - QWERTY ⌘".  What that does is let me type in Dvorak most of the time, but whenever I press the ⌘ (command) key, Mac switches back to QWERTY for as long as I hold the key down.  That lets me use hotkeys like a normal QWERTY user, e.g. ⌘-Z to undo is the same keypress as QWERTY and makes a lot of apps easier to use.

Unfortunately Godot must be detecting keys at a lower level and doesn't respect the switch back to QWERTY.  That means that to undo I have to press ⌘-/ (since in Dvorak, z is mapped to the / key).

What's worse is that the hotkey for redo (Shift-⌘-Z) doesn't work at all even if I use the / key.  I know it's weird to use a Dvorak keyboard but it's crippling not to be able to use hotkeys like a normal user.  It does work when I switch to the plain Dvorak layout (though that makes hotkeys awkward everywhere).

I'm set up to build Godot from source so if anybody could point me to the appropriate way to fix this problem, I could give it a shot?  Being able to remap hotkeys in the editor is probably the ideal solution but for now I'd settle for an under-the-hood fix.

**Comment by bojidar-bg** [comment]
Retagging as porting, since it doesn't look related to the editor.

Note that you can now remap editor shortcuts, so this issue is much less of a nuisance :smiley:

I'm no OSX user nor expert, so I can't say for sure, but maybe it is worth investigating if there is a FOSS application which doesn't exhibit this behaviour, and checking how they did it? (Qt-based applications probably don't count..)

**Comment by icnikerazah** [comment]
https://stackoverflow.com/questions/21597804/determine-os-x-keyboard-layout-input-source-in-the-terminal-a-script
<img width="768" alt="ekran resmi 2018-01-22 16 12 26" src="https://user-images.githubusercontent.com/33985414/35222616-94bda080-ff8f-11e7-99ff-ca6ab67a9ab5.png">

**Comment by icnikerazah** [comment]
nevermind

**Comment by martin-damien** [comment]
I have the same problem with BÉPO layout. Godot use the AZERTY layout instead when using the command key.

**Comment by Calinou** [comment]
@martin-damien Note that as of Godot 3.0, it is now possible to change key bindings in the Editor Settings. Eventually, this issue should still be fixed, but changing the keys is a possible workaround for now.
