### ISSUE TITLE
Import PCK/ZIP?

### ISSUE THREAD

**Issue by Chadt54** [godotengine/godot#43883]
I'm wondering if there's a way to import a pack like with Unity's .unitypackage importer feature?

I've been able to export a .pck and .zip but haven't found a way to import it (besides instructions for importing at runtime), but I am trying to import while in the editor for custom game assets built in Godot for Godot. (Like for selling on an asset market)

Am I misunderstanding .pck/.zip files? Or, is there some other way I'm expected to do this that I'm missing?

**Comment by Calinou** [comment]
> Am I misunderstanding .pck/.zip files? Or, is there some other way I'm expected to do this that I'm missing?

Indeed, PCK/ZIP files are not meant to be used for reusable game assets.

**Comment by akien-mga** [comment]
Note that we discussed adding a way to export and import one or more scenes with their dependencies across projects for this kind of use case (marketplace). For now that's just a rough idea in the back of our minds, we'll eventually write it down in a formal proposal on https://github.com/godotengine/godot-proposals.

**Comment by Chadt54** [comment]
Oops, sorry, ok I'll check out the community channels. Thanks for your response!
