### ISSUE TITLE
Cannot compile for platform WinRT

### ISSUE THREAD

**Issue by set-killer** [godotengine/godot#4389]
Hello folks, I decided to try Godot for WinRT platform but i couldn't compile it. I know that WinRT is not officially supported, but anyway...

The first problem that i encountered what something related to Windows Store  and the fix was to comment [this line here](https://github.com/godotengine/godot/blob/master/platform/winrt/detect.py#L51). 

After that it starts to compile the [gl_context_egl.h](https://github.com/godotengine/godot/blob/master/platform/winrt/gl_context_egl.h) files. Here i got an error that it cannot find the namespace `Windows::UI::Core` but that was fixed with a single line like:
```#include <windows.ui.core.h>```

Then it starts to build the core components. This is where i reached the deadend. The [Error enum](https://github.com/godotengine/godot/blob/master/core/error_list.h) conflicts with some system class that is named `Error`. 

As a result i got [this huge error list](http://www.pasteall.org/68336).

I am using Windows 10 x64, Visual Studio 2015 Community edition. I was using the ARM Developer Command prompt, as [described in the wiki](http://docs.godotengine.org/en/latest/reference/compiling_for_universal_windows_apps.html).

However there were no problems to build Godot for Windows platform.

Update:
This could be helpful for the future researches: 
[Supported Win32 APIs for Windows Phone 8](https://msdn.microsoft.com/en-us/library/windows/apps/jj662956%28v=vs.105%29.aspx)

**Comment by set-killer** [comment]
Since the latest commits this issue is not relevant.

**Comment by akien-mga** [comment]
Indeed, fixed by #6363.
