### ISSUE TITLE
Cant export AAB on Godot 3.2.4 Beta1 of previous project from Godot3.2.3 Stable

### ISSUE THREAD

**Issue by titangamingglt** [godotengine/godot#43892]
**Godot version:** 3.2.4 Beta 1

**OS/device including version:** Windows 7 64bit

**Issue description:** When i tried to export a project from Godot version 3.2.3 in Godot 3.2.4 as an AAB it throws an error. Here is the log of the error.
**FAILURE: Build failed with an exception.

* What went wrong:
Task 'copyAndRenameDebugAab' not found in root project 'build'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Exit Code: 1**

**Steps to reproduce:** Open an already excisting project of 3.2.3 which u in past export to android using custom build. Then try to export that project AAB in Godot3.2.4 Beta1

**Minimal reproduction project:** NA

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by akien-mga** [comment]
Did you install the Android source template for 3.2.4 Beta 1? (i.e. replacing the content of `res://android`).

**Comment by m4gr3d** [comment]
@titangamingglt as mentioned by @akien-mga , the issue is caused because the Android source template was not updated.
Try deleting the `res://android/build` directory, and reinstall the Android source template.

**Comment by titangamingglt** [comment]
thank you.The problem solved. but is there any way to make it simple like in my project i have lots of custom plug ins and have to edit and put many thing in the build.gradle and others. So after deleting the android build folder i have to search again to see where to edit and all. Can it be possible to make it simplify when someone transit from one version of godot to another?

**Comment by m4gr3d** [comment]
At the moment, it's not possible and the transfer has to be manual but we're brainstorming ways to improve the process.
Can you share what you original `build.gradle` file looks like? That'll help us with identifying the type of migration to support.

**Comment by titangamingglt** [comment]
[build.zip](https://github.com/godotengine/godot/files/5623647/build.zip)
