### ISSUE TITLE
Scripted resources unable to serialize/deserialize aka save/load data successfully.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#43904]
**Godot version:**
master (ed2f847)

**OS/device including version:**
Windows 10 Home Edition

**Issue description:**
Scripted resource's properties don't save. You can create and edit them, but if you attempt to actually save the file, the properties will reset to default values. This does not appear to happen with built-in properties (tested with a GradientTexture resource and it worked fine).

**Steps to reproduce:**

1. Create a `data.gd` Resource-extending script.

```gdscript
# data.gd
extends Resource
@export var count: int
@export var ratio: float
```

2. Create a new basic Resource in the Inspector using the new file icon.
3. Drag and Drop `data.gd` onto the resource's `script` property.
4. Set the `count` value to `42` and the `ratio` value to `3.14`.
5. Perform any save operation. The data will reset to `0` / `0.0` respectively.

**Comment by willnationsdev** [comment]
Also note that there are still a huge variety of export types that simply don't work properly yet (not generating the proper Inspector editor for the property). But that's a separate batch of issues.

**Comment by mbrlabs** [comment]
The same issue applies for non-resource scripts. See #41690.

**Comment by willnationsdev** [comment]
@mbrlabs Oh, then this is probably a duplicate then. Should probably be closed. Thanks!
