### ISSUE TITLE
Change Popup's popup_exclusive after shown

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#43901]
**Godot version:** Godot Engine v3.2.3.stable.official

**OS/device including version:** Windows 10

**Issue description:** Setting `popup_exclusive` for Popups has no effect after opening, but it should become an exclusive popup when changed, even when opened.

**Steps to reproduce:** 
- Create a `Popup`, set `popup_exclusive` to false and open it with popup's display methods (`popup`, `popup_centered`, etc);
- After opened, change the `popup_exclusive` to true, it will still close when clicked outside or with ESC.

**Minimal reproduction project:** 
[popup_exclusive_43901.zip](https://github.com/godotengine/godot/files/5605275/popup_exclusive_43901.zip)

**Comment by Calinou** [comment]
@felaugmar Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by felaugmar** [comment]
Uploaded a Minimal reproduction project.

**Comment by allkhor** [comment]
Still valid on Godot 3.4.4.stable

**Comment by akien-mga** [comment]
Fixed by #61483.
