### ISSUE TITLE
Method to assess the extents of a tilemap (level size)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4390]
There is, AFAIK, no easy way to determine the extents of a tilemap right now, i.e. the size of the Rect2 from the top-left tile to the bottom-right tile that would cover the whole non-null level area.

This would be quite useful for games that need e.g. to define margins for a Camera2D on levels with different sizes, without having to hardcode the size in each level script.

The output of the method could be:
- a Vector2 with number of tiles horizontally and vertically, e.g. `Vector2(12,18)`
- a Rect2 with the position of the topmost tile, and then the size as defined above, e.g. `Rect2(Vector2(-4,0),Vector2(12,18))`

Example:
![godot-tilemap-size](https://cloud.githubusercontent.com/assets/4701338/14703117/6fdca796-07ae-11e6-8080-baca58d14e29.png)

**Comment by bojidar-bg** [comment]
Better to do it with a Rect2 output, since otherwise you won't know where it starts.

**Comment by rnoriega31** [comment]
Uh, are we ever going to get this?

**Comment by bojidar-bg** [comment]
Would be cool, and it _should_n't be hard to do...
