### ISSUE TITLE
PacketPeerUDP.listen reuses port without error on Linux

### ISSUE THREAD

**Issue by mudbile** [godotengine/godot#43912]
**Godot version:**
Godot 3.2.2.

**OS/device including version:**

Tested on an Ubuntu 20.04 virtual machine inside VirtualBox. 

**Issue description:**
Calling listen with the same port number sequentially on two PacketPeerUDP instances should fail with error code 2. This happens on Windows, but on Linux it succeeds. You can even see there's two identical entries here:

![Screenshot_1](https://user-images.githubusercontent.com/29006839/100448832-a7349680-30fe-11eb-91fa-32ad6f7c2f5d.png)

**Steps to reproduce:**
Create two PacketPeerUDP  instances and call listen on the same port. Can someone see if they can duplicate this issue? I'm not 100% confident posting an issue based on results on a virtual machine. It's using a bridged networking adapter, for what that's worth.

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/5607776/New.Game.Project.zip)

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
The problem is that we enable `SO_REUSEADDR` which behaves differently between windows and linux (and is thus disabled there).
I guess this is a bug, and `SO_REUSEADDR` should NOT be used for UDP.
I'll make a PR.
