### ISSUE TITLE
It's impossible to select multiple lines of text from Help window

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4391]
**Operating system or device:**
Ubuntu 15.10 (added in edit)

**Issue description** (what happened, and what was expected):
Since some time it's impossible to select couple lines of text in help window (so it's impossible to copy them as well). While I usually like when software allows me to drag window content with mouse (like on touch devices where there is no sliders), but not in exchange for more basic functionality.  
![cantselectlines](https://cloud.githubusercontent.com/assets/6129594/14706245/d3bff43e-07bd-11e6-85bc-a85a781ccb0f.gif)
I saw this for first time in 2.0.2, compiled current main c0ec7e933ac6b6419e564b276b49c8d9a6d03f30 and it's still there.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by sketchyfun** [comment]
This might be OS related? I just tried it on Ubuntu using 2.0.2 and it selects fine without scrolling

**Comment by kubecz3k** [comment]
@sketchyfun I'm on Ubuntu as well.. It's interesting, maybe I have some editor option selected?

**Comment by bojidar-bg** [comment]
@kubecz3k can you reproduce this on an empty project?

**Comment by kubecz3k** [comment]
@bojidar-bg Indeed I'm unable to reproduce this in empty project. I have looked closely at all my settings and it turns out, that if you in project settings enable `Display->emulate_touchscreen`, not only your project will work in this mode but editor also... Will open new issue about this.

**Comment by kubecz3k** [comment]
new issue: https://github.com/godotengine/godot/issues/4392
