### ISSUE TITLE
Glitched audio on Raspberry Pi 3 when using ALSA driver

### ISSUE THREAD

**Issue by charasyn** [godotengine/godot#43927]
**Godot version:**

3.2.3

**OS/device including version:**

`Linux raspberrypi-fgts 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux`
Debian 10.6 on Raspberry Pi 3
Audio driver: snd_bcm2835

**Issue description:**

Audio playback is garbled and swaps back and forth between sound channels (ex. sounds playing on only Left/Right channel can be heard on both speakers)

**Steps to reproduce:**
Run the given project on Raspberry Pi 3 and observe bad audio quality.

**Minimal reproduction project:**

[testaudiopi.zip](https://github.com/godotengine/godot/files/5609389/testaudiopi.zip)

I have debugged this and have determined that there is a bug in the ALSA driver, please see https://github.com/efornara/frt/issues/14#issuecomment-734964644

**Comment by hiulit** [comment]
I can confirm this issue.
In my case, I'm using a Raspberry Pi 4.
I've tested Godot 3.1.2 and 3.2.3.

Here you can listen the same audio played on VLC and then in Godot https://twitter.com/hiulit/status/1330873256904110081?s=20
