### ISSUE TITLE
GDScript member class changes type.

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#43933]
**Godot version:**
3b4fad435c2856398f87b6f010013ce1a114b31b

**OS/device including version:**
Fedora 33

**Issue description:**
The member type `test_object` changes its type from `Node` to `bool` when this statement is executed `if test_object and true:`.

```GDScript
extends Node


var test_object: Node = null


func _ready():
	test_function(null)

	# This changes `test_object` type to bool.
	if test_object and true:
		print("At this point the variable type is changed from `Node` to `bool`.")

	# This will cause an error because you can't compare bool with a `Nil`
	test_function(null)


func test_function(obj):
	if test_object == obj:
		return
	test_object = obj

```

**Steps to reproduce:**
- Put the above code into a script
- Play the scene
- The GDScript VM will complaing the second time `test_function` is executed.

**Minimal reproduction project:**
[TestOperatorIssue.zip](https://github.com/godotengine/godot/files/5610736/TestOperatorIssue.zip)

**Comment by lyuma** [comment]
Not reproducible on master (85186bc).
