### ISSUE TITLE
CollisionShape2D trigger doesn't behave as expected

### ISSUE THREAD

**Issue by genete** [godotengine/godot#4393]
**Operating system or device:**
OSX  10.10.3
Godot 2.0.2 stable official

**Issue description** (what happened, and what was expected):
One moving KinematicBody2D with a shape set as trigger doesn't collide with other KinematicBody2D. 
According to the documentation:

> A trigger shape detects collisions, but is otherwise unaffected by physics (i.e. will not block movement of colliding objects).

I expect to detect the collision in the script but the body wouldn't stop its movement. What happens is that  the is_colliding() doesn't return true when the two bodies overlaps and no collision is detected

**Steps to reproduce:**
See minimal example

**Link to minimal example project** (optional but very welcome):
https://github.com/genete/triggerbug

**Comment by neikeq** [comment]
`KinematicBody2D.is_colliding()` must return true only when a collision is detected (therefore stopping the body movement), this way you can fix the movement to avoid getting stuck. Check: http://docs.godotengine.org/en/latest/tutorials/2d/kinematic_character_2d.html#problem

Is there a reason not to use an `Area2D` inside your kinematic body? The only reason I find to use a trigger shape with a `KinematicBody2D` (supposing the shape must have a different size than the collidable shape) is to make `Area2D` trigger _body_enter_ and _body_exit_, or to temporally disable that shape.

**Comment by genete** [comment]
Hi nelkeq, thanks for comment.
Please let me quote you:
> `KinematicBody2D.is_colliding()` must return true only when a collision is detected (therefore stopping the body movement), this way you can fix the movement to avoid getting stuck.

and quote again what documentation says:

> A trigger shape detects collisions, but is otherwise unaffected by physics (i.e. will not block movement of colliding objects).

I conclude: 

> If a Kinematic body's collision shape is a trigger the body must detect collision ("A trigger shape detects collision") and therefore as it is not affected by physics it wouldn't stop its movement. 

The second part happens (it is not affected by physics) but the first part doesn't (it doesn't detect a collision). So it is a bug or documentation must be updated.

Moreover, **can anyone show me an example of trigger with a PhisicsBody2D?**

> Is there a reason not to use an Area2D inside your kinematic body? 

There isn't. I'm using it for other purposes. 

> The only reason I find to use a trigger shape with a KinematicBody2D (supposing the shape must have a different size than the collidable shape) is to make Area2D trigger body_enter and body_exit, or to temporally disable that shape.

In both cases trigger just disables the shape. Why not call it just `set_disabled()`?

**Comment by neikeq** [comment]
The documentation can always be changed to make it clearer.

> A trigger shape detects collisions

This means it will emit the signals `body_enter` and `body_exit` (in case of Area2D and RigidBody2D). 

> but is otherwise unaffected by physics (i.e. will not block movement of colliding objects)

`Kinematic.is_colliding()` must return true only if the movement was blocked, because it's used to slide the remaining motion with the collision normal to avoid the body getting stuck.
KinematicBody2D does not have the signals `body_enter` and `body_exit` so as I said, you may only want to have trigger shapes on it is when these shapes are different from the colliding shapes and you don't want it to collide with other bodies but you still want other `Area2D` to trigger `body_enter` when collided.
Maybe what you are looking for are these signals in KinematicBody2D, but you can already achieve what you are looking for by using Area2D.

BTW, triggers are better explained here: http://docs.godotengine.org/en/latest/tutorials/2d/physics_introduction.html#triggers

**Comment by genete** [comment]
> BTW, triggers are better explained here: http://docs.godotengine.org/en/latest/tutorials/2d/physics_introduction.html#triggers

> A CollisionShape2D or CollisionPolygon2D can be set as a trigger. When used in a RigidBody2D or KinematicBody2D...

Precisely another documentation mistake (or code bug)

**Comment by genete** [comment]
Thanks again for reply again. 
My conclusion is that trigger use is:

1) Temporarily disable collisions (physics behavior) for that shape.
2) Allow Area2D trigger body_enter(), etc. for its shape, without being stopped by other surrounding colliding shapes.

One triggered shape won't send physics behavior to its PhysicsBody holder neither would send any collision information to it. A triggered shape is like disabled for the physics body it is inside, but it  is visible for Area2D from the point of view of its signals body enter, etc.

**Comment by KoBeWi** [comment]
This is no longer relevant since 3.0, as the `trigger` property was apparently removed.
