### ISSUE TITLE
Windows File Path Too Long Infinite Importing and Erroring

### ISSUE THREAD

**Issue by Chadt54** [godotengine/godot#43944]
Godot infinitely tries (and fails) to import an asset (in my case a .png) when the new ".import" file exceeds the windows file path character limit. The error it gives is actually unrelated to the path length, so it took me a while to figure out why the import was failing (and why Godot keeps trying the import the file over and over again).

Perhaps it would be good for there be a path length check on windows in order to give users a more relevant error message.

**Godot version:**
3.2.3

**OS/device including version:**
Windows

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/24395.
