### ISSUE TITLE
Text Editor discards unsaved changes when Godot gets focus again

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#4394]
**Operating system or device:**
Windows 10 Pro x64

**Issue description** (what happened, and what was expected):
A script has been modified in the editor, but not saved yet. I switch to another app and then back to Godot. The script gets reverted to the last saved version, and all my changes are lost!

**Steps to reproduce:**
I'm not sure how to trigger it. When working with Godot for a while, this starts to happen. Only one editor file seems to be affected. Closing the file and re-opening it fixes it. If I know more, I edit the issue. I simply focus another app, either by mouse or by keyboard (Alt+Tab), and when I go back to Godot, I shortly see the unsaved recent contents, and then them being immediately replaced by the last saved version.

**Comment by akien-mga** [comment]
I guess it's the same issue as #3764. Closing it as duplicate, feel free to add some more details over there. :)

**Comment by RayKoopa** [comment]
Yeah, it's the same. Sorry, didn't find it!
