### ISSUE TITLE
Tooltips for some 3D editor functions contain an additional newline.

### ISSUE THREAD

**Issue by AnilBK** [godotengine/godot#43940]
**Godot version:**
3.2.4 beta 3, 3.2.4 beta 2

**OS/device including version:**

Win10, GLES3

**Issue description:**

Tool-tips for some options in the 3D editor contain a extra newline.The 5 options as shown below only seem to have this issue.
None of the options in 2D editor have this issue.
This issue doesn't occur in 3.2.3 stable.

**Steps to reproduce:**
![bug](https://user-images.githubusercontent.com/17506575/100523049-6ce9f880-31d5-11eb-900e-4d22d3498cf6.png)

Easily reproducible.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
I bisected the regression to #43280. My fault :)
