### ISSUE TITLE
Modifying Node2D.position in the inspector does not send NOTIFICATION_TRANSFORM_CHANGED

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#43945]
**Godot version:**

3.2

**OS/device including version:**

N/A

**Issue description:**

My custom module node (extending Node2D) calls `set_notify_transform(true)` and `set_notify_local_transform(true)` in the constructor.
I have the following code in `_notification`:
```cpp
...
case NOTIFICATION_TRANSFORM_CHANGED: {
	print_line("local xform changed");
} break;
case NOTIFICATION_TRANSFORM_CHANGED: {
	print_line("xform changed");
} break;
```

When in the editor, *dragging* the node prints:

> local xform changed
> local xform changed
> xform changed

for every pixel moved. However, when editing the Node2D position directly in the inspector, my node prints only "local xform changed".

---

Just to note, this was not an issue when modifying Node2D.position from a script during runtime like so:
```gdscript
[if KEY_J pressed]: # <- pseudo code
    print("BEFORE")
    position += Vector2(1, 0)
    print("AFTER")
```
which prints:

> BEFORE
> local xform changed
> AFTER
> xform changed

**Steps to reproduce:**
See above.

**Minimal reproduction project:**

Request if needed.

**Comment by Calinou** [comment]
@briansemrau Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

(If in doubt, *always* upload a MRP!)

**Comment by briansemrau** [comment]
I thought just this once I could be lazy and not worry about a minimal reproduction, but I've only been reminded the importance.

The reason that `NOTIFICATION_TRANSFORM_CHANGED` wasn't being transmitted was because I was resetting the position in the `NOTIFICATION_INTERNAL_PHYSICS_PROCESS` notification. Oops! While the call to `set_position` from the inspector was immediately propagating `NOTIFICATION_LOCAL_TRANSFORM_CHANGED`, the global transform was net unchanged after the process loop. Hence, no notification. 

The most important understanding I've gotten from this is that `NOTIFICATION_TRANSFORM_CHANGED` doesn't happen exactly when I expect it to. `NOTIFICATION_LOCAL_TRANSFORM_CHANGED` is immediate, while `NOTIFICATION_TRANSFORM_CHANGED` seems to be deferred.
