### ISSUE TITLE
Display problem on macos(vmware)

### ISSUE THREAD

**Issue by blackbeaf** [godotengine/godot#43950]
**Godot version:**

Godot_v3.2.3-stable_mono_osx.64

**OS/device including version:**

Vmware player 16

**Issue description:**

Display error and don't respond any operation. I am curious about exporting IOS so I use vmware to have a try but failed. I'm not sure it's caused by Vmware or Godot.

**Steps to reproduce:**
Install macos on vmware, download godot from official website, open the official demo project.
![vm](https://user-images.githubusercontent.com/25684578/100537641-11674b80-3265-11eb-893d-b0249407cae1.jpg)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Running Godot using a virtual machine's 3D acceleration isn't officially supported. It would be better to use a more reliable OpenGL fallback instead.

**Comment by blackbeaf** [comment]
Thanks for reply.Please delete this issue.
