### ISSUE TITLE
Wrong color in Shader Material

### ISSUE THREAD

**Issue by okay300** [godotengine/godot#43961]
**Godot version:** 3.2.3 stable.official 

**OS/device including version:** Windows 7   GeForce 1660/PCIe/SSE2

**Issue description:** 
Through SpatialMaterial the assigned color is displayed correctly (model 1), and when I do through ShaderMaterial the color is wrong (Model 2).
![Pic1](https://user-images.githubusercontent.com/75214342/100549370-71291b00-3294-11eb-9d14-4378067f32af.jpg)

Here's an example of creating new material in a new scene. 
![yYYl8b7](https://user-images.githubusercontent.com/75214342/100549381-7dad7380-3294-11eb-989f-04af529f252e.gif)

**Steps to reproduce:**

**Minimal reproduction project:**

[Bild3d_0.2.zip](https://github.com/godotengine/godot/files/5612569/Bild3d_0.2.zip)

The color difference in one scene. SpatialMaterial is created in a simple way. **Bild3d_0.2**
![Pic_material_1](https://user-images.githubusercontent.com/75214342/100549374-78e8bf80-3294-11eb-808f-ea91c9a5fa61.jpg)

**Comment by clayjohn** [comment]
In ShaderMaterials you need to specify that albedo is a color with ``hint_color`` this is what Spatial material does 

https://github.com/godotengine/godot/blob/803f6d2388f64d069810554ab1b0a57d6a5a8087/scene/resources/material.cpp#L486

I don't know how to specify hints with Visual shaders. But that's what you need to do.

**Comment by okay300** [comment]
In the examples below I used Emission.
Did you open the project? Is there a difference in color like in the picture?
Maybe I'm the only one with this problem.

**Comment by Chaosus** [comment]
I guess using `hint_color` which is used by emission in SpatialMaterial provides conversion from linear color space to SRGB. The Color (ColorConstant) node is not uniform but a local vector and so it does not use this conversion.

**Comment by Calinou** [comment]
Closing poer @Chaosus's comment.
