### ISSUE TITLE
List of obsolete methods to deprecate

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4398]
We have quite a few obsolete and/or empty methods that should be deprecated, as they can be quite misleading for the users (see e.g. [this question about `OS.get_fullscreen_mode_list()`](http://godotengine.org/qa/3150/full-screen-list-generation)). Especially `OS` seems to have a good share of obsolete methods, that when asked about @reduz says "Don't use it, it's obsolete, use <foo> instead".

So this issue is meant to list and discuss such methods, to see which ones we should deprecate (and which ones should _not_ be deprecated but maybe improved/fixed). Once #4397 is solved, we should have a simple way to efficiently deprecate methods.

**Comment by akien-mga** [comment]
## To deprecate for 2.1

- ``OS.get_fullscreen_mode_list``
- ``OS.set_video_mode``

## Already deprecated for 2.1

**Comment by hurikhan** [comment]
Just stumbled over it.

- OS.get_borderless_window()
- OS.set_borderless_window()

Looks like it is only implementated in OS.initialize() for windows.
Is it also deprecated?

**Comment by akien-mga** [comment]
> OS.get_borderless_window()
OS.set_borderless_window()

Nope, those were added recently, but indeed only for Windows. If those would be relevant for other platforms, we should probably open an issue about it to keep track of their implementation.

**Comment by akien-mga** [comment]
Superseded by #5696.
