### ISSUE TITLE
CSG geometry glitch on overlapping faces

### ISSUE THREAD

**Issue by Axeltherabbit** [godotengine/godot#43989]
**Godot version:**
Godot Engine v3.2.stable.custom_build
OpenGL ES 3.0 Renderer: GeForce GTX 1650/PCIe/SSE2

**OS/device including version:**
`Linux pop-os 5.8.0-7630-generic #32~1605108853~20.04~8bcf10e-Ubuntu`

**Issue description:**
here some screenshot of the "glitch" https://imgur.com/a/WV9pgZt

**Steps to reproduce:**
The scene is in the zip file.
The top combiner is the cube divided in pieces, I had to scale it to 0.99 because perfectly overlapping geometries don't subtract.
the bottom combiner is the subtractor, when the nodes are visible they remove parts from the top geometry (I tried with just a cube on top but I have the same result)

I also tried the tweak the snap option but I don't see any difference, I'm not sure how it works

I checked the geometry and normals in blender, I'm not an expert but they seem fine to me.
 
**Minimal reproduction project:**
https://anonfiles.com/b2356cuap9/Destruction_zip

**Comment by Calinou** [comment]
> Godot Engine v3.2.stable.custom_build

There have been many CSG fixes since the release of 3.2. Try 3.2.3 or 3.2.4beta3.

**Comment by Axeltherabbit** [comment]
I can confirm it was fixed in the `v3.2.3-stable`, sorry if I have wasted some of your time, thank you!
