### ISSUE TITLE
gdscript compiler codegen incorrect instructions

### ISSUE THREAD

**Issue by jordo** [godotengine/godot#43997]
for @vnen  again.

Sorry george!  Still some issues in gdscript in current master

Below is my simple gdscript test function.  This print statement executes even when test_num is 1

![Screen Shot 2020-11-30 at 2 52 08 PM](https://user-images.githubusercontent.com/323868/100663444-e55ad180-331b-11eb-9deb-7ba82ffd6ca4.png)

However, if I uncomment the commented out line, `is_equal_num` (which is totally unused), the function executes properly.

Below is the dissasembly for when the function behaves incorrectly (as posted in the screenshot):
```
@"Disassembling test()\r\n"
@" 0: line 7: \tvar test_num = get_state().get_tick_number()\r\n"
@" 2: call-ptrcall (return OBJECT) stack(2) = self.get_state()\r\n"
@" 7: call-ptrcall (return INT) stack(1) = stack(2).get_tick_number()\r\n"
@" 12: assign stack(0) = stack(1)\r\n"
@" 15: line 9: \tif( self.type == NetworkGame.SERVER && test_num == 300):\t\r\n"
@" 17: get_named stack(3) = self[\"type\"]\r\n"
@" 21: validated operator stack(2) = stack(3) <operator function> const(0)\r\n"
@" 26: jump-if-not stack(2) to 41\r\n"
@" 29: operator stack(3) = stack(0) == const(300)\r\n"
@" 34: jump-if-not stack(3) to 41\r\n"
@" 37: assign stack(1) = true\r\n"
@" 39: jump 43\r\n"
@" 41: assign stack(1) = false\r\n"
@" 43: jump-if-not stack(1) to 53\r\n"
@" 46: line 10: \t\tprint(\"is 300\")\t\r\n"
@" 48: call-built-in stack(1) = print(const(\"is 300\"))\r\n"
@" 53: == END ==\r\n"
```

And here is the function executing correctly when I uncomment out that line:

```
@"Disassembling test()\r\n"
@" 0: line 7: \tvar test_num = get_state().get_tick_number()\r\n"
@" 2: call-ptrcall (return OBJECT) stack(3) = self.get_state()\r\n"
@" 7: call-ptrcall (return INT) stack(2) = stack(3).get_tick_number()\r\n"
@" 12: assign stack(0) = stack(2)\r\n"
@" 15: line 8: \tvar is_equal_num = (test_num == 300)\r\n"
@" 17: operator stack(2) = stack(0) == const(300)\r\n"
@" 22: assign stack(1) = stack(2)\r\n"
@" 25: line 9: \tif( self.type == NetworkGame.SERVER && test_num == 300):\t\r\n"
@" 27: get_named stack(4) = self[\"type\"]\r\n"
@" 31: validated operator stack(3) = stack(4) <operator function> const(0)\r\n"
@" 36: jump-if-not stack(3) to 51\r\n"
@" 39: operator stack(4) = stack(0) == const(300)\r\n"
@" 44: jump-if-not stack(4) to 51\r\n"
@" 47: assign stack(2) = true\r\n"
@" 49: jump 53\r\n"
@" 51: assign stack(2) = false\r\n"
@" 53: jump-if-not stack(2) to 63\r\n"
@" 56: line 10: \t\tprint(\"is 300\")\t\r\n"
@" 58: call-built-in stack(2) = print(const(\"is 300\"))\r\n"
@" 63: == END ==\r\n"
```

I think the stack comparators are not executing correctly in the first example.   And for whatever reason, adding in the unused variable causes the function to compile properly.  Maybe @vnen  can see something obvious there in the dissasembly.

**Comment by jordo** [comment]
So @vnen, after taking a more in-depth look at the dissassembly I can't see any error in the compiler.   Both jumps in the if statement look correct.  

Wrong execution disassembly looks valid:
```
@" 15: line 9: \tif( self.type == NetworkGame.SERVER && test_num == 300):\t\r\n"
@" 17: get_named stack(3) = self[\"type\"]\r\n"
@" 21: validated operator stack(2) = stack(3) <operator function> const(0)\r\n"
@" 26: jump-if-not stack(2) to 41\r\n"
@" 29: operator stack(3) = stack(0) == const(300)\r\n"
@" 34: jump-if-not stack(3) to 41\r\n"
```
And the correct execution disassembly looks valid:
```
@" 25: line 9: \tif( self.type == NetworkGame.SERVER && test_num == 300):\t\r\n"
@" 27: get_named stack(4) = self[\"type\"]\r\n"
@" 31: validated operator stack(3) = stack(4) <operator function> const(0)\r\n"
@" 36: jump-if-not stack(3) to 51\r\n"
@" 39: operator stack(4) = stack(0) == const(300)\r\n"
@" 44: jump-if-not stack(4) to 51\r\n"
``` 

 I guess this must be an issue in the vm.

**Comment by zachreizner** [comment]
I had a similar issue with the vm. In my case this works:

```
if Input.is_action_just_pressed("move_jump"):
	if is_on_floor():
		snap = Vector2.ZERO
		velocity.y = -jump
```

But this triggers constantly, even when both predicates are False according to print_debug:

```
if Input.is_action_just_pressed("move_jump") and is_on_floor():
	snap = Vector2.ZERO
	velocity.y = -jump
```

I managed to git bisect it to c707d6fe717c43fecafa0aca53182f214268ec16. The change prior to that works as expected with both version of the above code, but c707d6fe717c43fecafa0aca53182f214268ec16 is broken only for the second code snippet. I examined the commit itself, but being a newcomer to godot, I wasn't able to discern any immediate problems except that lots of things changed with GDScript codegen and VM.

**Comment by briansemrau** [comment]
I've been able to reproduce this on 4.0.dev 94b15bfb89.

This is the code I used:
```gdscript
var num = 2 # static typing does not matter

# Adding this line breaks the following if statement
num == 2
# But after adding this one it behaves as expected (in this case)
#num == 1

if false and num == 2: # operand order does not matter
    print("If you can see this, `if` is not working.")
```

**Comment by jordo** [comment]
@briansemrau try adding an else statement after the if, and let me know if it works when adding an empty else 

```
else:
	pass
```

**Comment by jordo** [comment]
Also the one thing common to all of our test code is `&&` / `and` operator in the if statement.  Maybe I'll take a look at the dissasembly one more time, perhaps I missed something obvious

**Comment by briansemrau** [comment]
> 
> 
> @briansemrau try adding an else statement after the if, and let me know if it works when adding an empty else


This did not make the if statement behave as expected. It's still printing the statement.

**Comment by jordo** [comment]
@vnen Here is the bytecode from @briansemrau (good function with the superfluous `num == 1`).
```
_brian_test_good()
2: assign stack(0) = const(2)\r\n"
7: operator stack(1) = stack(0) == const(2)\r\n"
14: operator stack(1) = stack(0) == const(1)\r\n"
21: jump-if-not const(False) to 36\r\n"
24: operator stack(2) = stack(0) == const(2)\r\n"
29: jump-if-not stack(2) to 36\r\n"
32: assign stack(1) = true\r\n"
34: jump 38\r\n"
36: assign stack(1) = false\r\n"
38: jump-if-not stack(1) to 48\r\n"
43: call-built-in stack(1) = print(const(\"If you can see this, `if` is not working.\"))\r\n"
48: == END ==\r\n"


_brian_test_bad()
2: assign stack(0) = const(2)\r\n"
7: operator stack(1) = stack(0) == const(2)\r\n"
14: jump-if-not const(False) to 29\r\n"
17: operator stack(2) = stack(0) == const(2)\r\n"
22: jump-if-not stack(2) to 29\r\n"
25: assign stack(1) = true\r\n"
27: jump 31\r\n"
29: assign stack(1) = false\r\n"
31: jump-if-not stack(1) to 41\r\n"
36: call-built-in stack(1) = print(const(\"If you can see this, `if` is not working.\"))\r\n"
41: == END ==\r\n" 
```

Both SHOULD execute `jump-if-not const(False)` bypassing the print, but in the `_brian_test_bad` function the print function call executes.

**Comment by vnen** [comment]
> I managed to git bisect it to [c707d6f](https://github.com/godotengine/godot/commit/c707d6fe717c43fecafa0aca53182f214268ec16). The change prior to that works as expected with both version of the above code, but [c707d6f](https://github.com/godotengine/godot/commit/c707d6fe717c43fecafa0aca53182f214268ec16) is broken only for the second code snippet. I examined the commit itself, but being a newcomer to godot, I wasn't able to discern any immediate problems except that lots of things changed with GDScript codegen and VM.

This might mean I made a mistake in the arguments of some instruction (maybe the conditional jumps?). So it's probably a problem in the VM itself, since the code seems to be compiled correctly.
