### ISSUE TITLE
Raycasts inside Tilemaps only collide at the edge.

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#44003]
**Godot version:**
3.2.3 stable

**OS/device including version:**
GLES3
Windows 10 Pro - 10.0.19042
Nvidia RTX 2080

**Issue description:**
When using a Raycast (of any kind, as a RayCast2D node or as a direct_space_state intersect_ray) to detect collision on a Tilemap, the collision is only detected at the edge of the Tilemap.

On other bodies, eg. a StaticBody, the Raycast is immediately stopped when it is inside the body. Not so on a Tilemap.
When casted inside a Tilemap, the Raycast will have no collision result unless it hits a wall edge.

![image](https://user-images.githubusercontent.com/9423774/100718825-112d9400-33bc-11eb-96b8-5ecc0b73d58e.png)

**Steps to reproduce:**
- Create a TileMap node with a Tileset that has collision
- Create a RayCast2D node and place it inside the TileMap
- Setup the collision masks accordingly

**Minimal reproduction project:**
[tilemap_collision_raycast_bug.zip](https://github.com/godotengine/godot/files/5621464/tilemap_collision_raycast_bug.zip)

**Comment by creikey** [comment]
This is an issue with `ConvexPolygonShape2DSW::intersect_segment` in `shape_2d_sw.cpp`:

```C++
if (!Geometry::segment_intersects_segment_2d(p_begin, p_end, points[i].pos, points[(i + 1) % point_count].pos, &res))
			continue;
```

This is in a loop where it's iterating over all the points in the polygon it seems. To fix this maybe an initial check to see if the starting point is inside the convex polygon?
