### ISSUE TITLE
Weird code suggestions behaviour when scrolling with scrollbar

### ISSUE THREAD

**Issue by ktostam0** [godotengine/godot#44000]
**Godot version:**

Godot 3.2.3/3.2.4 beta

**OS/device including version:**

Linux X11 x64

**Issue description:**

Suggestion window in code editor places itself in weird location when you scroll with scrollbar.

**Steps to reproduce:**
1. Start typing so that code suggestion window appears.
2. Scroll using the scroll bar (not using the mouse scroll wheel and not using the "minimap") until the suggestions should be no longer visible.
Suggestion window should position itself in a weird spot near the top-left corner of the code editor.

**Minimal reproduction project:**

See above.

I'd be really glad if someone approved that this problem isn't related to my PC only.

**Comment by ktostam0** [comment]
![bug](https://user-images.githubusercontent.com/70446098/100715343-57ccbf80-33b7-11eb-865e-392d6d2223a0.gif)

**Comment by Calinou** [comment]
I can confirm this on the `3.2` branch (803f6d238).

![Peek 2020-12-01 16-27](https://user-images.githubusercontent.com/180032/100760510-1e657580-33f2-11eb-870e-e033155fc62c.png)
