### ISSUE TITLE
"Your video card does not support any of the supported OpenGL versions" on Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by dude920228** [godotengine/godot#44034]
## Issue description
I have Godot 3.2.3-stable downloaded to my computer. After download, I could successfully create projects and fiddle with it for some time, but after I restarted my computer, an error message appeared which said: 

> Your video card does not support any of the supported OpenGL versions. Please  update your drivers or if you have a very old integrated GPU upgrade it.

 I have my nvidia drivers up to date and `glxinfo | grep version` outputs the following:
```
GLX version: 1.4
OpenGL core profile version string: 4.5.0 NVIDIA 384.130
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL version string: 4.5.0 NVIDIA 384.130
OpenGL shading language version string: 4.50 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 384.130
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```
 I tried to run it from terminal to see the debug info and I got the following output:
 ```
Godot Engine v3.2.3.stable.official - https://godotengine.org
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: initialize: Condition "!fbc" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:158.
ERROR: initialize: Condition "!fbc" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:158.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles2/rasterizer_gles2.cpp:166.
```
The problem is that I don't exactly know how to reproduce it.

**Comment by akien-mga** [comment]
Can you run any OpenGL application?

**Comment by dude920228** [comment]
I can run glxgears just fine, but glmark gives me a Segmentation fault. I have tried to reinstall drivers, but it didn't help.

**Comment by aaronfranke** [comment]
@dude920228 This doesn't sound like a problem with Godot. Try running a game from Steam and see if that works. You may also wish to try upgrading Ubuntu to a newer version.

**Comment by dude920228** [comment]
I could solve the isssue. I think there was some fault in the driver. Reinstalling the driver did not solve the issue, but downgrading it, then removing the driver, then reinstalling the latest worked.
