### ISSUE TITLE
Can't input double quotes (< " > character) on Mac OS X with US International keyboard layout

### ISSUE THREAD

**Issue by emanuelcds** [godotengine/godot#4403]
**Operating system or device:**
MacOS X Mavericks

**Issue description** (what happened, and what was expected):
Can't use simple or double quotes inside the godot script editor using US-International keyboard layout.

**Steps to reproduce:**
- Open any godot version since 2.0 stable
- Attach a Panel to you Scene
- Create a Script attached to the given panel
- Try to use quotes and double-quotes 

**Link to minimal example project** (optional but very welcome):
You can use my project as example:
https://github.com/emanuelcds/SlotMockRuntime

(I need to edit the gdscript files on VIM to edit the game logic and resync it on the engine).

**Comment by eduardonunesp** [comment]
OSX 10.11.6

Godot_v2.0.4.1_stable_osx

Unfortunately, the issue still here, any update about ? @akien-mga

**Comment by akien-mga** [comment]
No idea, we'd need someone who can reproduce it to debug the issue and try to fix it. AFAIK, it only affects certain users, as we have many OSX users who never complained about it.

I guess the common denominator is that you're all using the "US international" keyboard layout?

**Comment by eduardonunesp** [comment]
Yeah, definitely the common denominator is the "US international", I bet that is the main symptom

**Comment by eduardonunesp** [comment]
Confirmed, the quotes and double quotes works correctly when the OSX is using "US" keyboard, but fail if the user set "US International" keyboard

**Comment by reduz** [comment]
if you press double quote and then space, does it work?

**Comment by eduardonunesp** [comment]
@reduz, doesn't work either, my keyboard is a "US International" due the PT-br idiom. When I press the double quote and then space nothing happens, it just considers as a simple space and ignores the  double quote as if haven't pressed

**Comment by vnen** [comment]
I think this is the same as #1490, a general problem with dead keys.

**Comment by MacgyverMartins** [comment]
Same error here!
I can't write something like this: `is_action_pressed("left")`

**Comment by akien-mga** [comment]
This needs an OSX developer to dive into the input code.

**Comment by lucasmazzetto** [comment]
I'm having this same problem here: When i use "US International" mode on my keyboard i can't type quotes neither other characters in the Godot Editor - but when i change the keyboard mode all seems to be working fine.

**Comment by andreScutieri** [comment]
The problem doesn't only affects the double quote, but any character that "waits" (a.k.a. dead keys) for the next input in the International Keyboard. For example, when I press the `"` key and follow it by a vowel like `a`, it produces `ä` instead of `"a`. Likewise, the characters ``` `~` `^` `'` also "wait" for the next input key so they can determine which character will be inputted, be the regular character, be a modified character like `ç`, or `ê` or `ñ`. 

My system settings:

   ProductName:	Mac OS X
   ProductVersion:	10.12.4
   BuildVersion:	16E195

```
$ printenv

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
LANG=pt_BR.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
```
 As you can see, I'm using the UTF-8 version of the pt_BR locale, with the Brazilian Keyboard Pro. 

![Keyboard Layout](http://imgur.com/a/jfauB)

The bug can be avoided temporarily by selecting the US keyboard on the System Preferences -> Keyboard -> Layout

**Comment by reduz** [comment]
@BastiaanOlij want to give this one a try?

**Comment by akien-mga** [comment]
CC also @bruvzg and @marcelofg55 :)

**Comment by EmKeyy** [comment]
I'm searching this 'quetos' isse about last 4 hours. Thanks to "eduardonunesp" i handled it. Changing 'US Internatiol' Keyboard to 'US' Keyboard worked for me.

**Comment by vinaypoddar1** [comment]
I changed to keyboard "US" from "US International" and it works

**Comment by lordbertus** [comment]
It seems this is not solved? I'm having the same problem with Godot 4.2.1 on Pop!_OS. 
I am also using US - International keyboard layout.

**Comment by joaodanilo123** [comment]
I'm also getting this bug, when using dead keys on US-International Layout on Fedora 40, I can't type quotes, double quotes or other types of dead-keys characters.

Changing to another layout fixes some characters, but then I can't type the new layout dead keys

Desktop: Gnome with Xorg on Fedora Workstation 40
Godot Version: v4.2.2.stable.official [15073afe3]
