### ISSUE TITLE
Godot loses Input events on Android

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#44032]
**Godot version:**
3.2.4-beta3

**OS/device including version:**
Xiaomi - Redmi Note 9
Android 10

**Issue description:**
Wen pressing a touch button fast, other control nodes loses input. Is expected that the digital analog doesn't loses input.
This bug has been introduced on 3.2.4-beta2, previous versions work OK (beta1 and stable).
In beta-2 happens sometimes (I thought I was doing something wrong), but in beta-3 is really noticeable.

**Steps to reproduce:**
Export project to Android.
Drag the digital analog on the blue zone and spam fast one of the other buttons, the analog will lose control as if you stooped touching the screen, doesn't matter if you drag the finger across the screen.

**Minimal reproduction project:**
[VirtualAnalog.zip](https://github.com/godotengine/godot/files/5627545/VirtualAnalog.zip)

**Comment by Janders1800** [comment]
Related? https://github.com/godotengine/godot/pull/43907

**Comment by akien-mga** [comment]
> Related? #43907
