### ISSUE TITLE
Can't restore RNG state properly

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#44031]
**Godot version:** 3.2.3 & current master (ba51af7)

**OS/device including version:** not graphics-related.

**Issue description:**

RNG state is not restored after calling `RandomNumberGenerator.set_seed` with a seed saved from `RandomNumberGenerator.get_seed`.

The issue is caused by `get_seed` returning the current RNG state, while `set_seed` takes a seed, not state.

PR #35764 tries to resolve this problem by making the interface more intuitive, but seems inactive.

PR #27171 introduced this behavior.

A workaround is, maybe, [reseeding manually after generating a number](https://twitter.com/miziziziz/status/1333949897612079104), sacrificing randomness.

**Steps to reproduce:**

Run the following script with Godot.

```gdscript
extends SceneTree


func _init():
	var rng = RandomNumberGenerator.new()

	# let the seed change
	rng.randomize()
	rng.randi()
	rng.randi()

	var saved = rng.seed
	print('Current seed: ', saved)

	print('This seed produces:')
	print(rng.randf())
	print(rng.randf())

	rng.seed = saved
	print('Resetting the seed produces:')
	print(rng.randf())
	print(rng.randf())
```

Actual output:

```
Current seed: 8670679328791200068
This seed produces:
0.823806
0.514134
Resetting the seed produces:
0.028601
0.02974
```

Expected output:

```
Current seed: 8670679328791200068
This seed produces:
0.823806
0.514134
Resetting the seed produces:
0.823806
0.514134
```

**Minimal reproduction project:** N/A

**Comment by avencherus** [comment]
> PR #27171 introduced this behavior.

I thought that was reverted.  b5d9099626c4c180403baf0b75bd286a6b65c981

**Comment by timothyqiu** [comment]
It's only reverted on the 3.1 branch. 😂

**Comment by avencherus** [comment]
Oh right, it was left in the master, and 3.2 was the master back then.  Yeah, reverting it solves the issue.
