### ISSUE TITLE
Editor terminate when choose atlas texture (.atex)

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#4404]
**Operating system or device:**
Arch Linux 64bit.

**Issue description** (what happened, and what was expected):
I made 2D Atlas Texture, When choose it, Godot editor is terminate.

**Steps to reproduce:**
- Import->2D Atlas Texture.
- Select textures for import (2 files or more).
- **Texture Format: Compress (VRAM).**
- Add Sprite node.
- Inspector->Sprite->Texture->Load
- When enter a path to file atlas so Godot editor is terminate.

**Link to minimal example project** (optional but very welcome):
None.

**Comment by Hinsbart** [comment]
I can't reproduce this on master (also using 64bit Arch). I used some of the assets included with the demos and the VRAM Compress option.
Any chance you could provide the images which are causing that problem?

**Comment by Mavhod** [comment]
I made example project here:
https://www.dropbox.com/s/5vptbdp254zuxpc/testAtlas.zip?dl=0

And when I open test.tscn, Godot editor is terminate in a few sec after opened scene.
test.tscn is just include Sprite node (default settings).
