### ISSUE TITLE
Pixel snap interferes with Sprite offset rounding on Y axis

### ISSUE THREAD

**Issue by grotar00** [godotengine/godot#44048]
**Godot version:** 3.2.3.stable.official

**OS/device including version:** Windows 10 x64

**Issue description:**
Changing uncentered *Sprite* offset with *2d/use_pixel_snap* project flag checked results in visual vertical displacement of the image while editor frame is displayed correctly. Entering original offset doesn't revert this glitch but everything looks right after project is reloaded.

![demo](https://user-images.githubusercontent.com/8709735/100924330-877fe280-34f1-11eb-8a29-f793ddf3f0e9.gif)

**Steps to reproduce:** Create project with pixel snap enabled, create *Sprite* node with *centered* parameter unchecked, assign any offset value.

**Minimal reproduction project:**
[Sprite Offset Test.zip](https://github.com/godotengine/godot/files/5631731/Sprite.Offset.Test.zip)

**Comment by Calinou** [comment]
This may be fixed in 3.2.4beta3 by https://github.com/godotengine/godot/pull/43554, please test with that version if you can.

**Comment by grotar00** [comment]
Can confirm it's solved on [3.2.4beta3](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-3).
However, new option *2d/use_transform_snap* inherits this behavior while both image and frame appear shifted. Happens regardless of *2d/use_pixel_snap* being enabled.

![demo2](https://user-images.githubusercontent.com/8709735/100935073-adf94a00-3500-11eb-8a24-a9a002205366.gif)

**Comment by Calinou** [comment]
cc @lawnjelly

**Comment by lawnjelly** [comment]
No idea why off the top of my head. Float rounding issues perhaps on a whole number boundary? Or something else entirely. It does look like something is being retained on the original 'client' position, or perhaps the position in the visual server. I won't have time to investigate this at the moment.

Perhaps some of the snapping enthusiasts can investigate this, I'm really snowed under at the moment. Really my PR was just a backport / sorting the project settings for @m6502's idea so it could be merged and investigated - I'm slightly regretting it now :smile: . It doesn't imply that I champion the approach, or am the 'go to' guy for snapping, it is outside my (self-imposed) remit. There will be lots of consequences of this kind of change - snapping is a deep rabbit hole.

**Comment by m6502** [comment]
@lawnjelly I'll try to put some hours into this, thanks for your efforts :-)

**Comment by lawnjelly** [comment]
This seems fixed by using round #43813. I'll leave this open until that is merged.

**Comment by akien-mga** [comment]
Fixed by #43813.
