### ISSUE TITLE
The computer restarts without an error when I start it with Open GL 3.0

### ISSUE THREAD

**Issue by onurdumangoz** [godotengine/godot#44040]
**Godot version:**
3.2.4-beta3

**OS/device including version:**
Windows 10 (19042.630)
Lenovo ThinkPad T61
CPU: Intel Core 2 Duo T9300
GPU: Quadro NVS 140M

![Image of OpenGL](https://i.imgur.com/1g3IHfZ.png)

**Issue description:**
I know my system is old. But according to the above result, it supports OpenGL 3.0.
When I start a project with OpenGL ES 3.0, the laptop waits for a while (about 5 minutes) on a black screen and restarts.
No error or warning.
Even if Open GL 3.0 is not supported, it should at least be giving an error.

**Steps to reproduce:**
Start new project with OpenGL ES 3.0
And black screen
Restarting after 5 minutes

**Comment by clayjohn** [comment]
It should give you an error. 

Please note. Godot requires OpenGL 3.3 to run in GLES3. You should be able to run the engine by opening it from the command line with ``--video-driver GLES2``

**Comment by onurdumangoz** [comment]
Open GL 3.3 already supported and I can create projects with Open GL 2.0. I want to find out if this is related to my system or Godot and if possible, create a project with Open GL 3.0.

**Comment by akien-mga** [comment]
The drivers claim support for OpenGL 3.3, but if the system restarts it means that the drivers crashed, so they're buggy.

You can try to see if there's a newer version of Nvidia drivers for your GPU (yours is from 2016).

Ideally Godot should default to GLES2 for your hardware, but since the drivers claim OpenGL 3.3 support, it uses that.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/1609.

**Comment by akien-mga** [comment]
@onurdumangoz Does the project manager work for you? I.e. it only crashes when you start editing a GLES3 project in the editor?

**Comment by onurdumangoz** [comment]
@akien-mga Project manager working. It's only crashes when start GLES3 project.

**Comment by aaronfranke** [comment]
@onurdumangoz Try updating your drivers. Nvidia's website says that the latest supported drivers for your Quadro NVS 140M GPU are R384 U2 (385.12) from 2017.7.31 https://www.nvidia.com/Download/driverResults.aspx/121781/en-us

**Comment by onurdumangoz** [comment]
@aaronfranke Could not find compatible graphics hardware error.

**Comment by onurdumangoz** [comment]
I tried it from 378 to 384. The latest driver installed is 342.01.

![NVS 140m Drivers](https://i.imgur.com/iV20bY5.png)

**Comment by Calinou** [comment]
Closing per [this comment](https://github.com/godotengine/godot/issues/44040#issuecomment-737334070). Unfortunately, s
uch old graphics cards will most likely never support the GLES3 renderer well.
