### ISSUE TITLE
Saving a resource to file doesn't mark the scene as modified

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44053]
**Godot version:**

3.2.4 beta3

**Steps to reproduce:**
1. Create a node (e.g. Node2D)
2. Add any resource to it (e.g. built-in script or material)
3. Save the scene
4. Right-click the resource and choose Save
5. Save it to file
6. The resource is saved to file and reference gets modified
7. But the scene is not marked modified. If you close it, you will lose the reference to the file

**Comment by FeralBytes** [comment]
@KoBeWi just a question, I only seem to encounter this behavior if a "tool" script is involved, is that your case too? If I remove the tool scripts then it seems that the scene knows it should save, and does so properly.

**Comment by KoBeWi** [comment]
It happens without any tool scripts.
