### ISSUE TITLE
Getting "ERROR: hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1" on every project

### ISSUE THREAD

**Issue by Threepwoodd** [godotengine/godot#44056]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
Windows 10 19041.630
OpenGL ES 3.0 Renderer: GeForce GTX 1080 Ti/PCIe/SSE2

**Issue description:**
Im getting this error when opening godot aswell as when i open a project and when i run a game.

Error from the engine console/terminal:
`ERROR: hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1`
`Unrecognised output string: hint`
`   At: main/input_default.cpp:1141`

Here is a picture showing the errors, first opening godot engine, then opening a project and finally a project
![5xspdwr](https://user-images.githubusercontent.com/36038081/100955489-ec016880-3516-11eb-9886-8523f451baab.png)

Here is what shows up in the debugger when running a game
![9N4yjm4](https://user-images.githubusercontent.com/36038081/100955490-ec99ff00-3516-11eb-9d3a-b22115db1a13.png)

I am not sure when it started, wether it was when i updated to this build, or when i updated my nvidia graphics drivers etc...
I've had different controllers connected to my pc before but the error comes up even with no controllers connected.
I've tried uninstalling all my controllers to no avail, the error still shows up.

**Steps to reproduce:**
I am not sure how to reproduce this error, i am getting it even when reinstalling godot through steam.

I do **not** get this error when running the same non-steam version from the official website which could mean that something in my steam install has left something over that produces this error?

**Minimal reproduction project:**
I am not sure wether this is project related, just opening the godot engine will produce this error.
Any project will do, even a blank one.

**Comment by Threepwoodd** [comment]
An update on this, the error does not show up when opening godot through the exe in the steam directory (godot.windows.opt.tools.64.exe), instead of launching godot through steam (steam desktop shortcut or through the steam app)!

**Comment by akien-mga** [comment]
I suspect Steam initializes special mappings (maybe for the new PS5 controller) which Godot picks up but fails to parse.

**Comment by Threepwoodd** [comment]
> I suspect Steam initializes special mappings (maybe for the new PS5 controller) which Godot picks up but fails to parse.

Sounds likely, although i have no clue how steam work when launching an application

**Comment by madmiraal** [comment]
The simply solution is to just ignore the hint entries, but I'll have a look to see whether or not there may be any useful hints.
