### ISSUE TITLE
GDScript generated ConeTwistJoints do not link RigidBody objects together

### ISSUE THREAD

**Issue by starryaja** [godotengine/godot#44057]
**Godot version:**
v3.2

**OS/device including version:**
Windows 10

**Issue description:**
Trying to link two Rigid Body objects together using a ConeTwistJoint in GDScript. In the script, I instance the rigid bodies, add them to the tree, create a new joint, set the node_a and node_b properties to the two initialized RigidBody node paths, and add the joint to the scene, but the ConeTwistJoint is not connecting the two objects as it should. Project attached shows that the two spheres are not connected.

**Steps to reproduce:**
Either download and play the reproduction project below or follow these steps.

1. Create a camera/ floor mesh to contextualize the bug.
2. Create a scene that will act as a chain link. (Rigid Body with CollisionShape and CGSMesh as children)
3. Create a scene that will generate the chain and attach a script to that scene.
4. In the script of the chain generator: preload your chain link scene. 
5. in _ready(), create two instances of your chain link and a new ConeTwistJoint.
6. self.add_child() the two new chain links into the scene.
7. Find the paths to each of the two links in the scene with get_path_to() and add those paths to the ConeTwistJoint with joint.set_node_a and joint.set_node_b()
8. Add the joint to the scene with self.add_joint(joint)
9. Add the chain generator to your main scene.
10. Observe that the ConeTwistJoint does not connect the two RigidBodies.

**Minimal reproduction project:**
https://github.com/starryaja/godot_joint_gen_bug

**Comment by madmiraal** [comment]
[`get_path_to()`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-get-path-to) returns the relative path to the current node. Since these nodes are not children of the `Joint` it can't find them. Instead you need to use [`get_path()`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-get-path) to get their absolute path. Changing these lines in `Spatial.gd` fixes the problem:
```
	# Get nodepaths to each link
	var path1 = get_path_to(node1)
	var path2 = get_path_to(node2)
```
to:
```
	# Get nodepaths to each link
	var path1 = node1.get_path()
	var path2 = node2.get_path()
```
