### ISSUE TITLE
Godot custom source compile much larger than Linux executable

### ISSUE THREAD

**Issue by TetraGenius** [godotengine/godot#44058]
**Godot version:**
4.0.0 with one-line change

**OS/device including version:**
Fedora 33 and scons 3.1.2 (conda version) at https://anaconda.org/anaconda/scons

**Issue description:**
Compiled source to executable 499.6 MB and downloaded executable is about 75MB. Advice to reduce size will be welcome?

Cannot add Nodes to the project. (Create New Node window stays empty)

**Comment by TetraGenius** [comment]
I found this explaining the settings:
https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#cross-compiling-for-windows-from-other-operating-systems
There is a Note:

If you are compiling Godot for production use, then you can **make the final executable smaller** and faster by adding the SCons option **target=release_debug**.

**If you are compiling Godot with MinGW,** you can make the binary even smaller and faster by adding the SCons option use_lto=yes. As link-time optimization is a memory-intensive process, this will require about 3 GB of available RAM while compiling.
I'm trying this to see the result...

**Comment by qarmin** [comment]
https://github.com/godotengine/godot-build-scripts/blob/master/build-linux/build.sh

There is also used `debug_symbols=no` to not generate debug symbols

**Comment by akien-mga** [comment]
See https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html#compiling

![Screenshot_20201203_092140](https://user-images.githubusercontent.com/4701338/100982951-f5a3c400-3548-11eb-973d-c6624f27f055.png)

**Comment by Calinou** [comment]
Remember to also run `strip` on the binary to strip it from debugging symbols. However, after doing this, you won't get accurate stack traces when getting a crash anymore.

**Comment by TetraGenius** [comment]
I managed to fix  this: I was trying to compile the 4.0.0 and could not get this done.
Went back to stable 3.2 and compiles to 72.3MB and works just fine....
