### ISSUE TITLE
Editor continuously updating with Camera2D in scene

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#4406]
**Operating system or device:**
Ubuntu 15.10 x64

**Issue description** (what happened, and what was expected):
The editor is continuously being updated/redrawn if the scene contains a Camera2D. I am not sure, but this issue may be a regression from #4373

**Steps to reproduce:**
- Add Camera2D to a scene
- Close the scene and reopen it
- The editor will be updating/redrawing continuously (check the progress wheel in the top right corner) like when _Update Always_ is enabled

**Comment by neikeq** [comment]
Ping @bojidar-bg :)

**Comment by bojidar-bg** [comment]
Umm... yes? :smile: 

(I'll check asap)
