### ISSUE TITLE
adding the path to adb.exe generates error logs on the console

### ISSUE THREAD

**Issue by rafaelsescato** [godotengine/godot#44072]
**Godot version:**

**OS/device including version:**

**Issue description:**

please, can someone help me with this error, adding the path to adb.exe generates error logs on the console:

ERROR: execute: Condition "!f" is true. Returned: ERR_CANT_OPEN
   At: platform/windows/os_windows.cpp:2856

------
environment is windows!
happens when it points to the ADB executable
test with:
- godot 3.2.3
- godot 3.2.2
-----
ADB is what comes in sdkmanger tested with:
- platforms-tools v30 (from 2020)
- platforms-tools v29.0.5
----------

**Steps to reproduce:**
adding the path to adb.exe generates error logs on the console

**Minimal reproduction project:**

The problem happens in any project, even blank projects

**Comment by Calinou** [comment]
Can you paste the full, absolute path to adb.exe you've tried to add in the editor settings?

**Comment by rafaelsescato** [comment]
Friend @Calinou , I believe the problem was with my machine. As dark as it may seem, I did everything to even track the error in the godot code and solved the problem by reinstalling windows from scratch. And some members of the godot community with the same settings didn't have that error log.
