### ISSUE TITLE
Loading audio/image/mesh/materials paths in ready() not working for exported game

### ISSUE THREAD

**Issue by RockyMadio** [godotengine/godot#44075]
https://github.com/godotengine/godot/issues/18158 (similar)

**Godot version:**
Godot Engine v3.2.3.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Loading any file in ready() doesnt work for exported project, only in editor

I prevent sudden lags on changing asset/ resources during runtime by loading all of them inside ready() of a singleton. These are either .png or .wav files. As our game randomizes speeches and textures on characters, this should be the best solution.

However, the exported game is not able to do this. Is there anything I am missing?

**Steps to reproduce:**
0. make a simple scene, assign a script into a node
1. load( ) an image or an audio into a **var** or multiple ones into an **array**,  inside ready(). 
2. print( ) the result
3. Then export the game.

**Comment by Calinou** [comment]
Loading sound files at run-time isn't supported yet, see https://github.com/godotengine/godot-proposals/issues/732 and https://github.com/godotengine/godot-proposals/issues/1632.

**Comment by RockyMadio** [comment]
not just for sounds,
meshes/ png/ res/ tscn and any other files wont work with load( ) inside ready( )

**Comment by Calinou** [comment]
@RockyMadio My comment about run-time resource loading using `load()` not being supported yet still applies.

**Comment by RockyMadio** [comment]
> @RockyMadio My comment about `load()` not working in an exported project still applies 🙂
> 
> It's not designed to work in an exported project in the first place. Right now, if it works, it's more of an incindental thing than anything else.

so we wait until the fixes are made? ö.ö

**Comment by Calinou** [comment]
> so we wait until the fixes are made? ö.ö

There are no fixes to be made, since the feature in question needs to be implemented.

**Comment by Zylann** [comment]
> @RockyMadio My comment about load() not working in an exported project still applies 🙂

`load` (aka `ResourceLoader.load()`) is supposed to work at runtime for files of the project. If it didnt, scenes (or even scripts using `load(res://other.gd)`) would not even work. I too have a game that loads `tscn` at runtime, and it works fine exported. Godot remaps to `.scn` after export, and it does too for other resources AFAIK.

Maybe there is a problem with paths?

**Comment by RockyMadio** [comment]
It was my mistake, i had a double "/" inside my preload addresses. For some reason the editor doesnt notify me anything about this. 

Thank you  @Zylann for the great help!
