### ISSUE TITLE
logs directory appears in new project when running

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44083]
**Godot version:**

3.2.4 beta3

**OS/device including version:**

Windows 10

**Steps to reproduce:**
1. Create a new project
2. Add any scene
3. Run project
4.
![image](https://user-images.githubusercontent.com/2223172/101158925-ded69d80-362c-11eb-9006-76f1fd513118.png)

**Comment by akien-mga** [comment]
Déjà vu...

**Comment by Calinou** [comment]
Logs are configured to appear in `user://logs`. If logs appear in the project directory, this means the editor failed to get the path to `user://` and is falling back to the project directory.

How did you start the editor (command line, Start Menu option)? If using the command line, what was your CWD when you started the editor? Are you using self-contained mode?

**Comment by KoBeWi** [comment]
I used command line, I use only `-e` and `--path` args.

**Comment by KoBeWi** [comment]
Ok so I create an empty directory, create `project.godot`, double click it to open the project and the logs directory appears when run (also the Open Data Folder option in menu opens project folder). But it doesn't happen with previously existing projects.

I wonder if recent Windows update maybe broke something.

**Comment by akien-mga** [comment]
Likely the same underlying issue as #41435.

**Comment by KoBeWi** [comment]
So I just discovered that this happens when the project has empty name.
