### ISSUE TITLE
Imported BMFont not visible in HTML5 export

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#4408]
**Operating system or device:**
Windows 10 x64 Pro / Google Chrome

**Issue description** (what happened, and what was expected):
I imported a BMFont bitmap font file as a Godot font. It is visible in Windows builds, but in a HTML5 export, the font is totally invisible.
The console displays the following error for every character:

```
[1;31mERROR: draw_char: [0m[1mCondition ' c->texture_idx<-1 || c->texture_idx>=textures.size() ' is true. returned: 0
[0;31m   At: scene/resources/font.cpp:492.[0m
```

**Steps to reproduce:**
Import a BMFont file. Create a new scene and label using that font. Export as HTML5, run in Browser. The label text is invisible.

**Link to minimal example project** (optional but very welcome):
Test in browser: http://ray.syroot.com/fonttest
Source: http://ray.syroot.com/fonttest/source.zip

**Comment by eska014** [comment]
Unable to reproduce this, is it still occurring for you? If so, please upload the font causing issues (original links are down)

**Comment by RayKoopa** [comment]
Yeah, still not working. I update the links now.

**Comment by eska014** [comment]
Thanks, seems to be caused by (or at least related to) #7309

**Comment by RayKoopa** [comment]
Yeah, that's how it felt to me too. I'd bet my girlfriend on that it's caused by the bug you linked... if i had one.
