### ISSUE TITLE
Collision order in 2D solver (and maybe 3D) appears to be random

### ISSUE THREAD

**Issue by jordo** [godotengine/godot#44099]
cc'd @pouleyKetchoupp as per IRC discussion.

**Godot version:**
4.0 master

**OS/device including version:**
Not os or device specific

**Issue description:**
The solver when processing multiple collisions in the same step appears to generate a random response.  I'm speculating this is most likely due to something random in processing order in the solver.  As per IRC discussion speculation is that collision pairs are solved in random order by a hash of their pointer.  

See linked youtube video here:  https://www.youtube.com/watch?v=b5tBEl9TGWU&feature=youtu.be

Expected results is the same trajectory for each of the 3 simulations.  Instead, on the second simulation one collision bounce goes up, and creates a different outcome.  

**Steps to reproduce:**
See linked youtube video

**Comment by jordo** [comment]
So I guess we propose to change this in body_2d_sw ?  As well as perhaps the 3d as well?

```
Map<Constraint2DSW *, int> constraint_map;
```

There should be a more deterministic data structure for this correct?

**Comment by akien-mga** [comment]
Fixed by #44112.
