### ISSUE TITLE
Play the project is only saving the current selected tab

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#4410]
Play the project is only saving the current selected tab.

**Steps to reproduce:**
1. Create two scenes(tabs)
2.Edit both to that the tabs show *
3.Press "Play the project" -> BUG: Now only the selected tab is beeing saved, the other tab still shows * and the game is not showing the changes of the second(not saved) tab.

**Comment by mefihl** [comment]
Confirmed (Windows 10 64 bit)

**Comment by akien-mga** [comment]
From #4669: this happens when "Auto save before running" is checked.

**Comment by MarianoGnu** [comment]
I'm a llitle worried about consistency on tab titles, didn't get any problem myself, but please test it :sweat_smile:
