### ISSUE TITLE
Error when calling a coroutine with await in _ready

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#44101]
**Godot version:**
Master 2a0de6d88cfdc7cbd42e448fd44f1fbc438b320c

**OS/device including version:**
Windows 10

**Issue description:**
Calling a coroutine in `_ready()` using await fails with error `Trying to call an async function without "await".`

Example script:
```
extends Node

func _ready():
	await get_tree().create_timer(1.0).timeout # works
	await _async_func_test() # fails

func _async_func_test():
	await get_tree().create_timer(1.0).timeout
```

**Steps to reproduce:**
1. Add the script above to a node
2. Start game
3. Observe debugger break and error

**Minimal reproduction project:**
[script-await-ready.zip](https://github.com/godotengine/godot/files/5645934/script-await-ready.zip)

**Comment by pouleyKetchoupp** [comment]
Fixed in #43890, closing.

**Comment by pouleyKetchoupp** [comment]
I thought it was fixed, but I can actually still reproduce it in 68117f5e75944cfd6f8ad1534a15c334e7ed5e91.

**Comment by epth** [comment]
same error,
`extends Button

func _ready():
	await wait_confirmation()

func wait_confirmation() -> void:
	print("Prompting user")
	await self.button_up # Waits for the button_up signal from Button node.
	print("User confirmed")`

**Comment by SelfReflection31** [comment]
this returned in 4.4.1.stable
