### ISSUE TITLE
Array property is reset when saving scene

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#44103]
**Godot version:**
Master 2a0de6d88cfdc7cbd42e448fd44f1fbc438b320c

**OS/device including version:**
Windows 10

**Issue description:**
A property of type array added to a script with `@export var array_prop: Array` can't get its values saved, the property is reset each time the scene is saved.

**Steps to reproduce:**
1. Add an array property to a script with `@export var array_prop: Array`
2. Select a node that uses this script
3. Set array size to any value
4. Save scene
5. Observe array property reset to (Nil)

**Minimal reproduction project:**
Trivial enough to reproduce in any project.

**Comment by mbrlabs** [comment]
Duplicate of: #41690

**Comment by pouleyKetchoupp** [comment]
Closing as duplicate of #41690.
