### ISSUE TITLE
Button style - focus overrides pressed (pressed is not displayed)

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#44113]
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

win10

**Issue description:**

A Button's pressed style is not applied if focus is also used, the focus style seems to take precedence or is drawn on top.
Only if enabled_focus_mode is set to none for an element instance does the pressed style get drawn.
This goes in hand with the confusing and wrong behaviour of editing a theme where even disabled buttons are drawn with the focus style when clicked.
Expected would be that hover, pressed and disabled are displayed normally and focus is only drawn while those are not actively processed.

![OyBwAL7QB8](https://user-images.githubusercontent.com/8841352/101237774-ae017180-36db-11eb-8d16-3913590118da.gif)

**Steps to reproduce:**
Create a new theme, add a button item, change the pressed style to something noticeable, change the focus style, click some of the buttons in the preview panel, notice the focus style applying to everyone of them, but pressed style only to the toggle button (also only when it's not focused).

**Comment by Calinou** [comment]
> A Button's pressed style is not applied if focus is also used, the focus style seems to take precedence or is drawn on top.

You should use a focus style that's transparent and lets the underlying pressed style be visible. This is similar to `:focus` in HTML/CSS.

**Comment by Flavelius** [comment]
Then it's confusing the way it's presented (having all options available but at the same time having to chose a specific one to make it work a specific way), but okay.
