### ISSUE TITLE
Cannot find property "linear_interpolate" on base vector3

### ISSUE THREAD

**Issue by CozmoGames** [godotengine/godot#44127]
Godot version:
4.0

OS/device including version:
Not os or device specific

**Issue description:**
Cannot find property "linear_interpolate" on base vector3

**Steps to reproduce:**
this is the project i was working on

**Minimal reproduction project:**
[vulkan test.zip](https://github.com/godotengine/godot/files/5647706/vulkan.test.zip)

**Comment by Calinou** [comment]
`Vector3.linear_interpolate` was renamed to `Vector3.lerp()` to make the API more consistent.

**Comment by CozmoGames** [comment]
ok thank you
