### ISSUE TITLE
Make a better panel for the tilemap editor (zoom, columns alignment)

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#4412]
Currrently, when the tilemap editor's tiles panel is resized it looks quite strange.... (all columns are displaced)
![image](https://cloud.githubusercontent.com/assets/5276727/14762895/9dc1dbfe-098e-11e6-9820-7f77da56df23.png)

And here is how it looks with very smallish tiles: (Good luck finding and clicking the right one!)
![image](https://cloud.githubusercontent.com/assets/5276727/14762930/69346f90-098f-11e6-9bf1-46f1ce760425.png)

The problems:

* Columns are misaligned
* Small tiles are basically invisible

---

We discussed with @akien-mga on IRC (in an non-godotengine channel), a few fixes for those two scenarios:

1. Make everything properly aligned in nice columns somehow. (Will PR soon)
2. Add a zoom option. ( Done in #4800 )
3. Add an option to hide the names of tiles, since they are useless (take too much space) in some cases (like in the first pic).

---

To future responders: Note that this issue is not a place to dump your latest tilemap editor idea -- you should preferably open a new issue for that. This issue is specifically for discussing the above two examples (along with similar examples), and solutions for the problems presented.

**Comment by akien-mga** [comment]
Another striking example from @olsonjeffery:

![screen shot 2016-05-13 at 6 30 34 am](https://cloud.githubusercontent.com/assets/10408/15246656/3b705264-18d4-11e6-8d94-d25349e5f71d.png)

**Comment by bojidar-bg** [comment]
@akien-mga I think we solved that one, what's left?

**Comment by akien-mga** [comment]
I guess there's still this which might be relevant:
> Add an option to hide the names of tiles, since they are useless (take too much space) in some cases (like in the first pic).

Also the vscrollbar size is not taken into account in the Control, so the tiles are displayed under it when too small. But those are for other more specific issues IMO.
