### ISSUE TITLE
No code completion when inheriting a custom class that inherits a builtin class

### ISSUE THREAD

**Issue by zatherz** [godotengine/godot#4413]
**Operating system or device:**
Arch Linux (Godot version 2.0.1)

**Issue description** (what happened, and what was expected):
If you create a GDScript file, then inherit a builtin class, upon inheriting the file you will not get code completion for the builtin class.

**Steps to reproduce:**
* Create a file called `myclass.gd`
* Put only `extends Sprite` in the file
* Create another file called `test.gd`
* Put `extends "res://myclass.gd"` in the file
* In both files, write some function definition (e.g. `func test():`)
* In an indented block on the next line, try to write letters that some of the functions in `Sprite` start with, like `get` or `set`
* You will not see completion for them in `test.gd`, but you will in `myclass.gd`

**Link to minimal example project** (optional but very welcome):
[Download](https://ptpb.pw/vwHs.zip)

**Comment by vnen** [comment]
I think this is the same as #1039 and #3168.

**Comment by akien-mga** [comment]
Indeed, closing as duplicate.
