### ISSUE TITLE
Can't scroll with mouse wheel in Script Editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44137]
**Godot version:**

93b107a

**Steps to reproduce:**
1. Open Script Editor
2. Try using mouse wheel

**Comment by name-here** [comment]
Scrolling with a trackpad (in macOS)seems to work on a fresh build of `master`, or as well as it works in `3.2.3`, anyways.  However, like `3.2`, it scrolls in steps despite having smooth scrolling enabled, and doesn't do anything if I scroll too slowly.

On a side note, why is there a scroll speed limit by default, and why does setting it to 0 or -1 not disable it?  I can understand some people wanting it, but it makes the editor feel sluggish if you don't know about the option.

**Comment by Chaosus** [comment]
@name-here Please open a new issue for this, since it targets the mouse wheel and not the trackpad.
