### ISSUE TITLE
Mono's get_mesh() equivelent GetMesh() doesn't exist

### ISSUE THREAD

**Issue by dukevin** [godotengine/godot#44139]
**Godot version:** 3.2.3.stable.mono.official
**OS/device including version:** Windows 10

**Issue description:**
Cannot GetMesh on a node. In GDScript this works fine:
`$"../World/Ocean".get_mesh().size = Vector2(w, h)`
In C#/Mono this does not work:
`GetNode("../World/Ocean").GetMesh() //Doesn't exist`

"error CS1061: 'Node' does not contain a definition for 'GetMesh'"

[Documentation shows](https://godotsharp.net/api/3.0.3/Godot.MeshInstance/) that GetMesh exists however

**Comment by name-here** [comment]
Why is the path `"../World/Ocean"` in GDScript, but just `"World/Ocean"` in C#?

**Comment by dukevin** [comment]
> Why is the path `"../World/Ocean"` in GDScript, but just `"World/Ocean"` in C#?
Typo, but doesn't really matter

**Comment by name-here** [comment]
Just wanted to make sure it was a typo here and not in your actual code.

**Comment by akien-mga** [comment]
You should cast the result of GetNode to the actual Node type that implements this method. See examples in the Godot docs' C# snippets.

**Comment by dukevin** [comment]
Thanks for your answer but I'm having trouble still.

    (MeshInstance)GetNode("../World/Ocean").Mesh 

Says 'Node' does not contain a definition for 'Mesh' even though I am casting it. How do you do this?
