### ISSUE TITLE
godot attempt to call function rotate_x in base previously freed on a null instance

### ISSUE THREAD

**Issue by CozmoGames** [godotengine/godot#44133]
**Godot version:**
4.0

**OS/device including version:**
not os or device specific

**Issue description:**
godot attempt to call function rotate_x in base previously freed on a null instance

**Steps to reproduce:**
use the project

**Minimal reproduction project:**
[vulkan test.zip](https://github.com/godotengine/godot/files/5647943/vulkan.test.zip)

**Comment by Ev1lbl0w** [comment]
Your reproduction project doesn't run; it has scripting errors and is missing game objects. Could you please update it?

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
