### ISSUE TITLE
`const` values are not accepted as array dimension in shaders

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#44145]
Godot 3.2.3
Godot 3.2.4 beta 3
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

The following shader fails to compile at the line where the array is defined with the constant:
```glsl
shader_type spatial;

const int COUNT = 16;

void fragment() {
	float test1[16];
	float test2[COUNT]; // <-- fails here
}
```
With error
```
SCRIPT ERROR: (null): Expected integer constant > 0 or ']'
          At: :7
```
It should be possible to use constants here.

**Comment by Calinou** [comment]
cc @Chaosus
