### ISSUE TITLE
Color Picker popup behind the button when...

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#4415]
When a `ColorPickerButton` is child of a `Node2D` with **z>0**:
![scene](https://cloud.githubusercontent.com/assets/10850402/14764439/fe7fd418-09e9-11e6-8c7f-304d76506623.PNG)
![preview](https://cloud.githubusercontent.com/assets/10850402/14764443/4371a204-09ea-11e6-89d4-9f1da9293fef.png)
Am I supposed to do this however?

**Comment by reduz** [comment]
yes, this is intended, the ColorPicker contains a dialog and dialogs don't keep their parent Zs. (GUI components don't use Z). This is a really strange use case though, so if you want to set a custom Z to the color pciker, I am adding a function get_picker() to the button, so you can do:

VS.canvas_item_set_z( button.get_picker().get_canvas_item(), <your_z_here> );
