### ISSUE TITLE
Mono crash on Android version 4.4.4 (KitKat)

### ISSUE THREAD

**Issue by elix22** [godotengine/godot#44159]
**Godot version:**

v3.2.4-beta3_mono
Godot_v3.2.4-beta3_mono_export_templates.tpz

**OS/device including version:**

GLES2
Android 4.4.4 (KitKat)
armeabi-v7a
 

**Issue description:**

"Dodge the Creeps!" , the  sample game is crashing on an Android device running version 4.4.4 (KitKat)

**Relevant logcat :**
12-07 10:00:58.384  5965  5965 E dalvikvm: dlopen("/data/app-lib/org.godotengine.dodgethecreepswithc-2/libgodot_android.so") failed: dlopen failed: could not load library "libmonosgen-2.0.so" needed by "libgodot_android.so"; caused by cannot locate symbol "sigemptyset" referenced by "libmonosgen-2.0.so"...: org.godotengine.dodgethecreepswithc
12-07 10:00:58.394  5965  5965 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libmonosgen-2.0.so" needed by "libgodot_android.so"; caused by cannot locate symbol "sigemptyset" referenced by "libmonosgen-2.0.so"...: org.godotengine.dodgethecreepswithc
12-07 10:00:58.404   591  1413 I am_crash: [5965,0,org.godotengine.dodgethecreepswithc,8928838,java.lang.UnsatisfiedLinkError,dlopen failed: could not load library "libmonosgen-2.0.so" needed by "libgodot_android.so"; caused by cannot locate symbol "sigemptyset" referenced by "libmonosgen-2.0.so"...,Runtime.java,364]: system_server

**Steps to reproduce:**
install "Dodge the Creeps!"   on an Android device running version 4.4.4 (KitKat) and try to run it .

**Minimal reproduction project:**

[https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html](https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html)

**Comment by akien-mga** [comment]
@neikeq Checking e.g. https://github.com/eclipsesource/J2V8/issues/466, this error seems to mean that we're compiling `libmonosgen-2.0.so` under a too recent API level for armv7.

In `platform/android/detect.py` we use `android-18` for `armv7` (Android 4.3.x) which should still be compatible with Android 4.4.4 (`android-19`). So my guess is that https://github.com/godotengine/godot-mono-builds might be incorrectly using a newer API level for `armv7`.

**Comment by akien-mga** [comment]
Yep here's the bug: https://github.com/godotengine/godot-mono-builds/blob/master/android.py#L525

The default is set to `21`, but it should be `18` to match `platform/android/detect.py`. It's then bumped to `21` automatically for `arm64v8` and `x86_64` which require it.

**Comment by elix22** [comment]
Thanks for the quick reply and fix .
It will take me some time to setup **godot-mono-builds** and compile my own *.so
If you have a precompiled **libmonosgen-2.0.so** (armeabi-v7a)  with the fix , I will be able to verify it

**Comment by akien-mga** [comment]
I'm making a full build of the Android templates for 3.2.4-beta3 using the fixed container, should be ready soon.

**Comment by akien-mga** [comment]
@elix22 Here's a test build with that fix: https://downloads.tuxfamily.org/godotengine/testing/android-mono-3.2.4-beta3.zip

To use it, you should go to your installation folder for 3.2.4-beta3 templates (on Windows `%APPDATA%/Godot/templates/3.2.4.beta3/`, on Linux `~/.local/share/godot/templates/3.2.4.beta3/`) and replace the following files or folders with the contents of that zip:

```
android_debug.apk
android_release.apk
android_source.zip
bcl/godot_android_ext/
bcl/monodroid/
bcl/monodroid_tools/
godot-lib.release.aar
```

Note that the `bcl/` folder contains other Mono stuff for other platforms, so you should only replace the three subfolders which match the ZIP's content.

**Comment by akien-mga** [comment]
Wait a few minutes, I posted too fast and the upload isn't completed yet :)

**Comment by akien-mga** [comment]
It's now ready to download.

**Comment by elix22** [comment]
Yep 
It works !!
Thanks for the quick fix

**Comment by akien-mga** [comment]
The templates for 3.2.4 beta 4 and future versions should be good from the start :)
