### ISSUE TITLE
Cannot rename Path node

### ISSUE THREAD

**Issue by Shulito** [godotengine/godot#44163]
**Godot version:**
3.2.3.stable

**OS/device including version:**
Windows 10.0.19042.630

**Issue description:**
I added a Path node and a PathFollow node as a child. When I try to rename the Path node, I can edit the name but after I hit enter it reverts to the name "Path". This only seems to happen on a particular scene that I have, I've tried with other scenes and it seems to work fine.

**Steps to reproduce:**
1. Open the project.
2. Open the scene "Main".
3. Click on the node "Path" to rename it,
4. Rename it.
5. Hit enter.

**Minimal reproduction project:**
[squash_the_creeps_start_1.1.0.zip](https://github.com/godotengine/godot/files/5652814/squash_the_creeps_start_1.1.0.zip)

**Comment by Shulito** [comment]
Here's a recording of the issue:
[2020-12-07 10-15-51.zip](https://github.com/godotengine/godot/files/5652843/2020-12-07.10-15-51.zip)

**Comment by TWolfdev** [comment]
I'm able to reproduce that renaming is generally somewhat glitchy, in the sense that I occasionally need to rename a node twice for it to work. Same thing in your provided minimal reproduction project, however ultimately I'm always able to rename a node.

**Comment by gongpha** [comment]
Still occur in [`41e9028`](https://github.com/godotengine/godot/commit/41e9028868e49669de83c82ba20fd9dcef0d1b8b).
