### ISSUE TITLE
Incorrect control receive event in _gui_input() after set gui_disable_input

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#44173]
**Godot version:**
Godot 3.2.3 Stable, Godot_v3.2.4-beta3

**OS/device including version:**
Ubuntu 16.04.7 LTS, Android

**Issue description:**
Incorrect control receive event in _gui_input() after gui_disable_input = true

**Steps to reproduce:**
1) Open MRP.
2) Run scene and click on ColorRect1.
3) Await printing Input Gui Enabled!
4) Click on other ColorRects
5) Try several times while not reproduce bug.

As workaround uncomment:
```
#		self.visible = false
#		self.visible = true
```
![gui_bug](https://user-images.githubusercontent.com/1049442/101395848-b4b70100-38f4-11eb-9b28-d7881a85151b.gif)

**Minimal reproduction project:**
[gui_input.zip](https://github.com/godotengine/godot/files/5654772/gui_input.zip)

**Comment by allkhor** [comment]
Still here, tested on Godot 3.4.3 Stable.

**Comment by Sauermann** [comment]
This happens when the MouseButton is released during `gui_disable_input = true`. If you keep the MouseButton pressed longer in the MRP, you can reset the Control, that receives the input.

**Comment by RandomShaper** [comment]
I believe this is a side effect of allowing the engine to enter an "unstable" situation, which #59099 will prevent.
