### ISSUE TITLE
Xbox controller trigger input is wrong.

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#44178]
**Godot version:**
4.0 master
3.2.3 stable

**OS/device including version:**
WIN 10, using Wired Xbox 360 controller.

**Issue description:**
Godot treats trigger input incorrectly.
The for the Right trigger, first half of the trigger pull is "Joystick 2 Up", and the second half if "Joystick 2 Down", but you can only set one of these axes as the input value. This means that the first half of the trigger pull is ignored, and you essentially always have a deadzone of 50%...

Here is an example with a utility that reads what the actual input is. As you can see, Godot thinks the input starts at 50%. Note I have the deadzone set to 0% here (does deadzone even work anway??).
![controller_input_trigger_wrong](https://user-images.githubusercontent.com/41730826/101422556-a2fc4a80-3942-11eb-8531-5d0465190537.gif)

**Steps to reproduce:**
Make an input action with a joystick input event.
Print or set a label text to `Input.get_action_strength("my_action")`
Play the scene and press the right trigger.
The label will only go above 0 when the trigger is half pressed.

**Minimal reproduction project:**
For 3.2
[XboxTriggersWrong.zip](https://github.com/godotengine/godot/files/5656084/XboxTriggersWrong.zip)

**Comment by EricEzaM** [comment]
https://github.com/godotengine/godot/blob/706c38ab2a69fa36aff6ff7d0ba2ca4517c5dcd6/core/input/input.cpp#L897

Here is where the value gets reversed. The controller does input a value 0 to 255, which then goes through a bunch of different conversions. 

I don't know why it was done like this... Why were triggers split into 2 axes where you can only use half of them?

**Comment by Calinou** [comment]
> I don't know why it was done like this... Why were triggers split into 2 axes where you can only use half of them?

See https://github.com/godotengine/godot/pull/42799.

**Comment by madmiraal** [comment]
> Why were triggers split into 2 axes where you can only use half of them?

Originally, Microsoft used a single axis for the two triggers. The -ve and +ve were split into the two triggers. To get around the problem of only being able to use one trigger at a time, they were split into two axes, but the range wasn't changed. Actually, the complexity goes back further, because originally triggers were buttons not even axes; so having a axis with a range was an enahancement.

**Comment by EricEzaM** [comment]
@madmiraal Ok, so can this be fixed?

This is like having a deadzone of 50% all the time. This is not how it works in other engines.

**Comment by madmiraal** [comment]
> The for the Right trigger, first half of the trigger pull is "Joystick 2 Up", and the second half if "Joystick 2 Down"

The left trigger should map to the positive half of axis 4 (Joystick 2 Right) and the right trigger should map to the positive half of axis 5 (Joystick 2 Down).

I don't have an XBox controller so I can't test it and confirm that this is a bug, but the values are provided by Windows [XInput](https://docs.microsoft.com/en-us/windows/win32/api/xinput/ns-xinput-xinput_gamepad). In the case of triggers these are bytes. The byte values are converted to a positive value between 0 and 1 here:
https://github.com/godotengine/godot/blob/d94bf9f7b66c7e5ec4c7438025fbcc59110cb4e7/platform/windows/joypad_windows.cpp#L457-L462
There should never by negative values provided by triggers.

**Comment by golddotasksquestions** [comment]
I have an Xbox One controller (Win 64). When I map the trigger buttons (L2,R2 - not the shoulder buttons) to left_trigger and right_trigger and
```
func _physics_process(_delta):
	print("right: ",Input.get_action_strength("right_trigger"))
	print("left: ",Input.get_action_strength("left_trigger"))
```
it will print

> left: 0
> right: 0
> left: 0
> right: 0
> left: 0
> right: 1
> left: 1
> right: 1
> left: 1
> right: 1

This is strange, for one because deadzone was set to 0 yet the button press was only registered after it has already been pressed halve way through, and second, because I seem to remember successfully using strength on this very Xbox One controller some time back without problems. I get strength from my analog sticks on the same controller just fine.

**Comment by EricEzaM** [comment]
Yeah from memory testing this problem deadzone doesn't do anything it seems. 

It is quite counterintuitive due to the way it is set up with the 2 different axes representing the 2 halves of the trigger pressed level. Currently you can only bind to one of these axes, so you get either the first half or the second half of the trigger movement.

**Comment by madmiraal** [comment]
@EricEzaM Is this still an issue for you? @golddotasksquestions, in his edited comment, says _"On the joy axis the triggers work fine, deadzone included."_ with a Xbox One Controller. I have now tested this on Windows with a PS3 controller and it (including the dead zone) works fine for me too.

The only thing I can think of is the Action Deadzone, which despite you saying _"I have the deadzone set to 0% here"_, in your MRP it is set to the default 50%; so the behaviour you're seeing would be expected.

BTW See https://github.com/godotengine/godot-proposals/issues/3709 for a proposal on making the axes dead zone configurable and changing the default to a more reasonable value of 5%.

**Comment by EricEzaM** [comment]
I will try and test, thanks @madmiraal

Might be in the new year tho

**Comment by madmiraal** [comment]
@EricEzaM I've just tested this on master and I can confirm that it is a problem on master for all controllers. On 3.x it works as expected.

**Comment by golddotasksquestions** [comment]
@madmiraal I don't have access to a controller right now, but will test this again as soon as I can.
