### ISSUE TITLE
When AnimationPlayer is seeked, certain values aren't set correctly.

### ISSUE THREAD

**Issue by kirilledelman** [godotengine/godot#4417]
This happens on tracks whose interpolation type is set to discrete. **Setting AnimationPlayer's time by clicking on timeline, or programmatically using `seek` between two keys, doesn't update the value to that of the previous key.** But this works correctly if the track is continuous, and values are interpolated.

Example:
* track `sprite:frame` is set to discrete and has a key at time `0.0s` with value `10`, it has another key at time `5.0s` with value `11`.
* My sprite's current frame is set to some other value, say, `20`, and player's time is at `10.0s`
* Clicking on timeline at `2.5s` should set sprite's frame to last / previous key, namely one at `0.0s` - frame `10`, but nothing happens. Other, continuous tracks all get set correctly, resulting in chaotic / incorrect display of the animation.
* The only way to see animation correctly is to manually drag / rewind animation to `0.0s`, and then drag the time slider over to `2.5s`. This is a huge time killer, and makes editing very cumbersome.

In my case, character body parts are separate, and have different frames for "straight", "bent at elbow", "holding a gun" etc., so sprite frame number, and sprite offset are set to discrete. I've wasting a ton of time needlessly scrubbing the animation back to last frame, just so I can see it displayed correctly.

My game also saves character state, along with current animation name, and current animation time. When game is restored, the animation is often somewhere in progress, and what I see is mangled / incorrectly positioned body parts at wrong frames.
![screen-shot-2016-04-23-at-7 33 12-pm](https://cloud.githubusercontent.com/assets/6539713/14764781/b430dd1c-098a-11e6-9947-3815e35fe013.jpg)

**Comment by reduz** [comment]
This should now work properly. 
Regarding save/restore state, Godot works like blender and other animation software, so there is no "default" state.

The easiest way to do this is just create an animation of length 0 that sets the default state of the rig, so you can either use it to save, or call play/seek on animationplayer on that animation at the begining to reset all states.
