### ISSUE TITLE
[3.2] Rotation gizmo outline wrong due to missing inverse function in GLES2

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#44171]
**Godot version:**
3.2.4 beta3

**OS/device including version:**
Windows 10

**Issue description:**
I backported the improved rotation gizmo from @JFonS in #43016, but i just noticed that the circular gray outline around the gizmo is rotated wrongly when using the GLES2 backend. It should always face the camera, but that is not working in GLES2 because it lacks the built-in [inverse ](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/inverse.xhtml) shader function (this should be noted in the [docs](https://docs.godotengine.org/en/stable/tutorials/misc/gles2_gles3_differences.html#shading-language)).

This is relevant part of the shader code: https://github.com/godotengine/godot/blob/364d019fee656ee822a3ac502e89362dd31d0640/editor/plugins/spatial_editor_plugin.cpp#L5410

GLES3:
![gles3](https://user-images.githubusercontent.com/8750135/101379510-a2b56e00-38b4-11eb-9549-f11acb326493.PNG)

GLES2:
![gles2](https://user-images.githubusercontent.com/8750135/101379525-a6e18b80-38b4-11eb-8c5b-f154cc9792a9.PNG)

**Solution**
I used a custom `inverse` function based on [this implementation](https://stackoverflow.com/questions/22643604/glsl-es-2-0-inverse-matrix) to fix it in this particular case. A more general approach would be to add a polyfill `inverse` function on the engine level, so it works with all shaders. This is a bit more involved though, because it requires to write versions for `mat2`, `mat3` and `mat4` (probably not worth it). 

If the custom `inverse` function idea sounds good, i can open a PR :)

**Comment by Calinou** [comment]
@lawnjelly What's your opinion on this? Is a custom `inverse` method the way to go, or should we polyfill `inverse` in GLES2?

**Comment by clayjohn** [comment]
We already provide an implementation of ``inverse``. So I guess the bug is that this isn't being applied properly. 

https://github.com/godotengine/godot/blob/2beb36fbadf157c7ac73fb7472b9a4847bc960b9/drivers/gles2/shaders/stdlib.glsl#L302-L373

**Comment by mbrlabs** [comment]
@clayjohn Oh, nice! Could it maybe be because it's definied for `highp` floats and `MODELVIEW_MATRIX` uses a lower precision?

**Comment by clayjohn** [comment]
@mbrlabs are you getting an error when you use ``inverse`` in GLES2? 

If so, I am guessing that something is missing in our shader compiler and it isn't setting the #define properly.

**Comment by mbrlabs** [comment]
No errors (i also checked with the verbose flag). 
The shader compiles fine btw, otherwise the outline would probably not draw at all.

**Comment by clayjohn** [comment]
@mrcdk then maybe the math in the inverse function is wrong. Maybe compare it to your custom function and see what is different.

**Comment by mbrlabs** [comment]
@clayjohn I guess that's it. I'll have a look!

**Comment by clayjohn** [comment]
@mbrlabs thanks! Please open a PR if you can figure it out. :)

**Comment by mbrlabs** [comment]
I'm closing this since it's fixed with #44174
