### ISSUE TITLE
AnimationPlayer / AnimatedSprite frame and offset key aren't set when scrubbing timeline 

### ISSUE THREAD

**Issue by kirilledelman** [godotengine/godot#4418]
When I'm working on an animation using `AnimatedSprite`, I often have to change sprite's `frame` during animation, as well as its `offset` ( which is the rotation pivot ). These tracks are set to discrete ( not continuous ), and my expectation is that when I'm scrubbing the timeline, to preview the animation, the `frame` and `offset` keys would take effect immediately when time hits them. Instead, the sprite is updated when the timeline is dragged past them, on the next frame/step.

This makes animating extra cumbersome, because of the discrepancy between what I see on the scene, and the keys I see at current time in the timeline.

Additionally, clicking on the timeline between two keys on a track set to discrete doesn't apply current track value, so it's a total mess on the screen.

**Comment by xa8et67** [comment]
每天盯着邮件,为什么这个BUG没人修?

**Comment by kirilledelman** [comment]
I switched to Unity after waiting for this to be fixed.

**Comment by reduz** [comment]
Good for you, though this was fixed a while ago

**Comment by reduz** [comment]
Confirming that this is fixed, so closing it. We will always be waiting for you to come back with hugs.
