### ISSUE TITLE
mention collision layers and masks in Documentation

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#4419]
Collision Layers & Masks are not even mentioned in Godot Docs. Any many people ask about them or ask about problem, which could be solved with those.

examples from today, from Godot's FB group:
https://www.facebook.com/groups/godotengine/permalink/765588073577789/
https://www.facebook.com/groups/godotengine/permalink/765659656903964/

**Comment by Marqin** [comment]
I was told about this feature on IRC, when I had similar problem to those guys. And only description of those layers/mask I've found is here:
http://godotengine.org/qa/3020/collision-masks-and-its-propper-uses

**Comment by akien-mga** [comment]
Moved to godot-docs repo.
