### ISSUE TITLE
Color picker eye dropper preview does not work, and exits out of color picker when you click

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#44192]
**Godot version:**
4.0 master

**OS/device including version:**
Win 10

**Issue description:**
Color picker does not change color as you drag your cursor across the screen when in eyedropper more.
When you click, the color is indeed selected but the window closes immediately.

**Steps to reproduce:**
Use any color picker button in the editor, e.g. modulate.

**Comment by mrushyendra** [comment]
It appears to arise between commits 77b70aa and b3080bc (a.k.a the DisplayServer changes)

**Comment by EricEzaM** [comment]
Yes from experience it is due to fact Popups are now Windows.

**Comment by KoBeWi** [comment]
Closing in favor of #46334, which has more activity.
