### ISSUE TITLE
CanvasItem `draw_primitive()` does not work with textures

### ISSUE THREAD

**Issue by groud** [godotengine/godot#44196]
**Godot version:** master

**OS/device including version:**
Linux, Intel Corporation UHD Graphics 620 (rev 07), Vulkan

**Issue description:**
The draw primitive function does not display textures as it should. Only the color is taken into account instead. See this sample code:
```gdscript
func _draw():
	var points = [Vector2(0, 0), Vector2(64, 0), Vector2(64, 64), Vector2(0, 64)]
	var uvs = [Vector2(0, 0), Vector2(1, 0), Vector2(1, 1), Vector2(0, 1)]
	var colors = [];
	# Same behavior with this or any other color: var colors = [Color(1.0, 1.0, 1.0, 0.5)];
	var texture = preload("icon.png")
	draw_primitive(points, colors, uvs, texture)
	
	draw_texture(texture, Vector2(0, 200))
``` 
This leads to:
![2020-12-08-171254_349x308_scrot](https://user-images.githubusercontent.com/6093119/101509063-a6aac400-3978-11eb-9b68-2b711a6b7f08.png)

**Steps to reproduce:**
Simply try to use the draw_primitive function of CanvasItem with a texture.

**Minimal reproduction project:**

[draw_primitive.zip](https://github.com/godotengine/godot/files/5660411/draw_primitive.zip)

**Comment by LeonardoCBoar** [comment]
I have tested this on 3.3.3 and it appears to be solved

**Comment by Calinou** [comment]
> I have tested this on 3.3.3 and it appears to be solved

This issue likely only affects the `master` branch, not `3.x`. Can you test this on a [recent build of the `master` branch](https://hugo.pro/projects/godot-builds/) as well?

**Comment by MrBlockers** [comment]
Just reproduced this issue on master, commit [39534a7ae] with a new Mobile project with 'gl_compatibility' rendering method set. Tested using a 64x64 .png as substitute for logo.png (rest in lo-fi peace). 

It seems like draw_primitive is also having a vertex order issue of some sort.. probably a separate issue for the 4.0 GLES3 renderer specifically?

```gdscript
func _draw():
	var points = [Vector2(0, 0), Vector2(64, 0), Vector2(64, 64), Vector2(0, 64)]
	var uvs = [Vector2(0, 0), Vector2(1, 0), Vector2(1, 1), Vector2(0, 1)]
	var colors = [];
	# Same behavior with this or any other color: var colors = [Color(1.0, 1.0, 1.0, 0.5)];
	var texture = preload("sample.png")
	draw_primitive(points, colors, uvs, texture)
	
	draw_texture(texture, Vector2(0, 200))
```
![image](https://user-images.githubusercontent.com/1747505/195943111-e12ddba6-3b3d-4370-b4aa-1f0e99ce8a21.png)
