### ISSUE TITLE
Scenes that extend a base class and use a new script file cannot delete or create signals, or call existing signals

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#44204]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Linux Mint

**Issue description:**
Quick description: Load the sample and see that in double bullet all signals are broken and cannot be fixed.

I have a base class/scene called StraightProjectile.tscn, StraightProjectile.gd

I have a scene called SingleBullet that extends StraightProjectile as the node type and the script opens StraightProjectile.gd

In SingleBullet I have a signal at the root node, a signal on a node from the StraightProjectile and a signal on an inherited scene of StraightProjectile. They all work fine.

I then duplicated this SingleBullet to a new one called DoubleBullet, then disconnected the 'SingleProjectile' script and added a new script which extends StraightProjectile (does not matter whether you select Load or 'extend').

Now, when I open up DoubleBullet, Godot thinks all the signals are there, but double clicking leads to nowhere, when you disconnect the signal it disappears but when you close then re-open the scene the signals are there again, but again you cannot do anything with them. If you disconnect the signal, create a new one it generates the code. But when you then try to double click on the Node signal again, it fails to find the code again. The signal code is never reached at runtime either. So it thinks the signal is connected to the base class but it never runs and never opens the code and you cannot disconnect or create your own signal.

You can, however, click on a new signal, e.g. draw() in Sprite, generate the code and all is well because the code goes into doublebullet.gd.

HOWEVER, one exception is in the scene from StraightProjectile you can disconnect one signal which was created in an inherited scene.

Even if there is some logical explanation for this (inheritance rules, etc) you would expect Godot to either let you disconnect the signal or even inform you something is wrong.

Looking at the tscn file it appears that it is loading the base class and new script fine, has attached the inherited scene fine because that is where the connection is made, but all the other signals are in 'straightprojectile' base class and they are never properly associated with the superclass.

**Steps to reproduce:**
1. Open the attached project
2. Open Single bullet and see all 3 signals work
3. Open Double bullet and see all signals are broken
4. Try to disconnect double bullet and see on re-opening they reappear and you cannot create a new signal
5. Try to disconnect double bullet VisibilityNotifier2D signal, then create a new one successfully then go back to the 2D view and try to double click, it fails
6. Find a node, e.g. Sprite, find a new signal, e.g. draw() and create. This is fine. It is added to the correct .gd file.
6. Note that 'take_hit' in hurtbox attached scene can still be detached properly, because it is an inherited scene

**Minimal reproduction project:**

[test1.zip](https://github.com/godotengine/godot/files/5662097/test1.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/12373 (possible duplicate?).

**Comment by Calinou** [comment]
@chucklepie Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release? Also test this in 4.0.beta4 if you can.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
