### ISSUE TITLE
Gdscript bug when calculating the length of a Vector2 and checking for a mouse click

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#44210]
**Godot version:**
current 4.0 master

**OS/device including version:**
Win10

**Issue description:**
I am getting some very bizarre gdscript results when calculating the length of a vec2 followed by an if statement with an AND operator in it that tests for a mouse click. I was getting strange results in my game (which works fine in 3.2.4 and earlier 4.0 builds), so this took me a while to track down. It seems to occur with a very specific order of code so I am not quite sure what is causing this.

**Steps to reproduce:**

Try this code on a node2d:

```
func _process(delta):
	var start = Vector2(0, 0)
	var end = Vector2(10, 0)
	#var dist = (end + start).length()	
	var test = "one"	
	
	if Input.is_mouse_button_pressed(1) and test == "one":
		print("pressed")	
```
This works as expected and  will print "pressed" when the left mouse button is clicked. However if you uncomment out line 4, the if statement will evaluate as true continuously even though no mouse button is clicked.
Additionally, if you move the `var dist = (end + start).length()` line to after the if statement, everything works as expected. Even just using var `dist = (end + start)` will cause this strange behaviour, so it doesn't necessarily have to be calculating the length of the vector.

Also, if you try nesting the if statements and leaving in the vector calculation it all works as expected.

```
func _process(delta):
	var start = Vector2(0, 0)
	var end = Vector2(10, 0)
	var dist = (end + start).length()	
	var test = "one"

	if Input.is_mouse_button_pressed(1):
		if test == "one":
			print("pressed")
```
This buggy behaviour does not occur in 3.2.4.beta2 or 4.0 master builds from about 6 weeks ago. 

**Minimal reproduction project:**
[input_issue.zip](https://github.com/godotengine/godot/files/5663461/input_issue.zip)

**Comment by lyuma** [comment]
I am no longer able to reproduce this bug on the latest master ( 85186bc )

@fracteed can you confirm if you still see this problem?

**Comment by fracteed** [comment]
Ah yes, you can close this now. It was something to do with the "and" conditional that was resolved a while back!
