### ISSUE TITLE
View Grid render bug in both GLES2 and GLES3

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#44216]
**Godot version:**

3.2.4 beta3

**OS/device including version:**

![屏幕快照 2020-12-09 18 26 36](https://user-images.githubusercontent.com/64188282/101617837-19d13a80-3a4c-11eb-9f7a-a0592edcb29b.png)

**Issue description:**

when add a new scene from a scene that View Grid is turned off, the new scene's Grid won't be rendered in viewport unitl you switch to the previous scene then switch back
![屏幕快照 2020-12-09 18 23 28](https://user-images.githubusercontent.com/64188282/101619979-ee9c1a80-3a4e-11eb-8194-87dc611f6181.png)

**Steps to reproduce:**
open Godot Editor
make sure turn off empty scene's view grid option
click add new scene button
you will see the bug

**Minimal reproduction project:**

[bug report.zip](https://github.com/godotengine/godot/files/5665296/bug.report.zip)

**Comment by Calinou** [comment]
This should be fixed in 3.2.4beta4 (or later) thanks to https://github.com/godotengine/godot/pull/44218.
