### ISSUE TITLE
TouchScreenButton generate error "Child Process Connected"

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#4421]
**Operating system or device:**
Godot 2.0.2, Windows 8.1

**Issue description** (what happened, and what was expected):
After click TouchScreenButton which causes a change scene, debugger show error "Child Process Connected".
TextureButton not show this error.

**Steps to reproduce:**
1) Set in project options "emulate_touchscreen" to "on"
2) Create "TouchScreenButton"
3) Connect button with function when "pressed"

`func _on_StartGame_pressed():`
`get_tree().change_scene("res://scenes/game.tscn")`

4) After change scene debugger show error "Child Process Connected"

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
this is just the debugger that shows that the process has connected, it's unrelated to anything else so don't worry, it's not a bug
