### ISSUE TITLE
"WARNING: ObjectDB instances leaked at exit" on initiating Node2d object with c# 

### ISSUE THREAD

**Issue by Szesan** [godotengine/godot#44226]
**Godot version:** 3.2.3 - stable_mono_win64

**OS/device including version:** Windows 10 Home PC

**Issue description:**

 - Tried instantiating a Node2d object from code:

`var newNode = new Node2D(); `

The above command triggers the following error:

WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2135)

**Steps to reproduce:**

1. - Create new project
2. - Create main scene
3. - Insert the above command `var newNode = new Node2D(); ` in the _Ready() method

**Minimal reproduction project:**

[TestLeak.zip](https://github.com/godotengine/godot/files/5666978/TestLeak.zip)

**Comment by Szesan** [comment]
I've figured out that if I connect the instance to the SceneTree by 
	`AddChild(newNode);` for example, the leak is gone. But I think there should be a garbage collection that picks up unparrented nodes on exit.

**Comment by pouleyKetchoupp** [comment]
This warning makes sense, it's not a bug.

Nodes are not automatically freed on exit, unless they are added to the scene, for example by using `add_child(newNode);` in your case.

On the other hand, Resources or any class that inherits from `Reference` use a ref counting system and are freed automatically when not used.

Documentation:
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html?#memory-management

*Note for contributors:*
Maybe the documentation could be clearer on this aspect? It doesn't say anything about Nodes **not** being managed automatically unless added to the scene.

**Comment by Szesan** [comment]
> Documentation:
> https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html?#memory-management
> 
Thanks, good to know. Coming from a .net background I assumed that there is garbage collection.

**Comment by akien-mga** [comment]
Indeed that's expected behavior. `AddChild(newNode);` solves the issue by making the new Node part of the scene tree and thus freed together with the scene tree when you close the game.

>  Maybe the documentation could be clearer on this aspect? It doesn't say anything about Nodes not being managed automatically unless added to the scene.

I opened an issue for this:
https://github.com/godotengine/godot-docs/issues/4877

**Comment by Karmavil** [comment]
This was very helpful. Thanks!
