### ISSUE TITLE
Key added to the wrong action in Input Map

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#44227]
**Godot version:**
Master 44a88244dee7e8996824aa29507e917b22ffccca

**OS/device including version:**
Windows 10

**Issue description:**
When adding keys to multiple actions in a row in Input Map, the next key can be added to the same action as the previous one instead of the action that was selected.

Seems related to #44155 but I'm adding a separate issue since the repro is a bit different, to make sure this case gets fixed as well.

**Steps to reproduce:**
1. Open Project Settings in a new project
2. Go to Input Map tab
3. Click the + icon on `ui_left` action
4. Select Key
5. Press A
6. Click OK
7. Immediately press the + icon on `ui_right` action
8. Select Key
9. Press D
10. Click OK
11. Observe D key added to `ui_left` instead of `ui_right`

**Minimal reproduction project:**
n/a

**Comment by KoBeWi** [comment]
Seems no longer valid in 758bccf
@pouleyKetchoupp Can you confirm?

**Comment by pouleyKetchoupp** [comment]
Yes, I can confirm this is fixed with #44181, closing.
