### ISSUE TITLE
DisplayServer: Some dropdowns are not persistent

### ISSUE THREAD

**Issue by KaruroChori** [godotengine/godot#44230]
**Godot version:**

Godot 4.0 bc30df8

**OS/device including version:**

Linux 80x86 64bit, GTX 1660 super and RTX 2060 (main one). Drivers 450.80

**Issue description:**

Some dropdown elements in the GUI are not persistent. Releasing the mouse click will let them disappear. This has only been tested in single window mode.

**Steps to reproduce:**
Open any project and try to export. The dropdown to select the architectures is one of the few being affected.

**Minimal reproduction project:**
No need for a specific project.

**Comment by Calinou** [comment]
This happens with pretty much all OptionButtons in Linux

**Comment by MagdielM** [comment]
Can confirm, I'm also having this issue on Windows 10.

**Comment by nathanfranke** [comment]
Duplicate https://github.com/godotengine/godot/issues/40227?
