### ISSUE TITLE
Deleting new script file from FileSystem view before saving script crashes the editor

### ISSUE THREAD

**Issue by pigigi** [godotengine/godot#44237]
3.2.1 stable

Windows 10 x64

See title for description. File entry gets stuck in FileSystem view, must edit project file to remove.

Steps for repro:
- Create new ptoject.
- Add script to root node.
- Delete file that appeared in FileSystem view.
- Crash!
- Reopen project.
- File is still in FileSystem view. Attempting to delete it crashes 100%.

**Comment by pigigi** [comment]
Ok great, enter in title submits issue. Fanfu**ingtastic. And no deletion.

**Comment by Calinou** [comment]
I can't reproduce this on 3.2.3 and `3.2` Git 666e8ca38 (Fedora 33), regardless if I save the scene before moving the script to the trash using the FileSystem dock or not. (Saving the scene will automatically save the script.)

Are you using GDScript or C#?

**Comment by pigigi** [comment]
GDScript. I do not save the scene either actually, so the file doesn't exist at all, as seen in Explorer. Perhaps I should've added this verification step, sorry.

**Comment by Calinou** [comment]
> GDScript. I do not save the scene either actually, so the file doesn't exist at all, as seen in Explorer. Perhaps I should've added this verification step, sorry.

Thanks for the clarification :slightly_smiling_face: 

Unfortunately, I still can't reproduce this bug with the steps you've given.

**Comment by EricEzaM** [comment]
Can you post a Gif of you showing it happening? You can user shareX on Windows which is FOSS.

**Comment by pigigi** [comment]
Sure thing.

[A few blunders later](https://i.imgur.com/sxifbgh.gif)

**Comment by EricEzaM** [comment]
Any reason in particular you are using 3.2.1 and not a newer stable release?

**Comment by pigigi** [comment]
I started my main projects on 3.2.1 quite some time ago, and upgrading to 3.2.3 brought a slew of issues that I wasn't in the mood for. I guess I should also try reproing the crash on 3.2.3. I'll do that and report back. Maybe not tonight tho!

**Comment by pigigi** [comment]
Hey all that said and done, it really is a dumb edge case that might not be worth busting too many balls on.

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.beta 282e50ac8 (Linux). Please comment if you can still reproduce this issue on (https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release.
