### ISSUE TITLE
Hidden Tilemaps affects Shadows

### ISSUE THREAD

**Issue by diegomachado** [godotengine/godot#44235]
**Godot version:**

3.2.3 Stable Official

**OS/device including version:**

Windows 10, RTX 2070, for both GLES2 and GLES3

**Issue description:**

Hidden tilemaps affects Light Occlusion. Don't know if this is the intended behaviour, but the only way to hide and disable shadows on tilemaps is by tweaking Tilemap's Occluder's Light Mask.

**Steps to reproduce:**
- Create two tilemaps
- Use the same tileset on both
- Add Occluder to tiles
- Hide one of the Tilemaps
- Create a Light2D and turn on it's shadows

**Minimal reproduction project:**

[hidden_tilemap_light_occlusion.zip](https://github.com/godotengine/godot/files/5667812/hidden_tilemap_light_occlusion.zip)

**Comment by Calinou** [comment]
@groud What's your opinion on this?

**Comment by groud** [comment]
> @groud What's your opinion on this?

Looks lit a bug yes. A hidden tilemap should not have visible occluders I suppose.

**Comment by akien-mga** [comment]
Fixed by #54435.
