### ISSUE TITLE
PVS-Studio report 2020-12-09

### ISSUE THREAD

**Issue by fire** [godotengine/godot#44240]
**Godot version:**
https://github.com/godotengine/godot/commit/d8825fb253dbdf8b149f678b35a45fb3763a0d97

**OS/device including version:**
Linux Fedora 33

**Issue description:**
Expected zero errors. But saw many errors.

@bruvzg 

**Steps to reproduce:**

```
cd godot
pvs-studio-analyzer credentials NAME XXXX-XXXX-XXXX-XXXX
scons p=x11 -j16
pvs-studio-analyzer analyze -f compile_commands.json  -j16 -r`pwd` -ethirdparty/
plog-converter -a GA:1,2 -t fullhtml -o html PVS-Studio.log -dV752,V1058 -r `pwd`
```

[html.zip](https://github.com/godotengine/godot/files/5668675/html.zip)

**Minimal reproduction project:**
Clone the Godot Engine source at commit.

**Kudos**

Kudos to bruvzg for fixing the bugs.

**Comment by aaronfranke** [comment]
For the first five high severity ones, see [this discussion](https://github.com/godotengine/godot/pull/43903#discussion_r531782704).

**Comment by fire** [comment]
I'll use the other issue.
