### ISSUE TITLE
Shader script editor appears out of nowhere when backing out of the shader nodes

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4424]
**Operating system or device:**
Win10 64 bit; 24 gigs RAM; third gen i7 CPU; ATI HD 7xxx GPU

**Issue description** **(what happened, and what was expected):**
In the original version 2 release for Godot, going into the shader node setup, then clicking the back arrow just closes the nodes window without opening something else. Newer builds (done in the last week) now show the shader script editor (regardless of whether I want to do any editing or not).

Then, returning to the shader does not close the script window, so now you have two additional windows instead of just one. I can see the use of having the raw code made available, but whether or not the script window is visible should be a user option rather than something done automatically by Godot (unless of course you're in the regular custom shader options and you explicitly use the script field in the _reference_ area).

**Steps to reproduce:**
Open the file, select the mesh instance, go to the material editing buttons via the material override menu, go to the shader tree editing via the shader menu, then back out of the tree editing with the back button.

**Edit:: Example file to try it with**
[Bugs.zip](https://github.com/godotengine/godot/files/233844/Bugs.zip)

**Comment by Griefchief** [comment]
I can confirm this happened to me as well, the code editor appears undocked from the GUI itself in front of the visual shader editor.

**Comment by MarianoGnu** [comment]
Fixed in #5308
