### ISSUE TITLE
Long paths conceal GDScript warnings

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#44247]
**Godot version:**

3.2 branch at commit 0b5a9bf7167e393e0b42a18383cccddd8b008d1f

**OS/device including version:**

Arch Linux

**Issue description:**

On a template I'm working on, I moved a deep folder hierarchy to the root of the project to make it easier to access. All of a sudden I'm now seeing warnings never shown previously.

**Steps to reproduce:**
1. Open the attached project with the Editor
2. Run the project (F5) and stop it (F8). Look at the Debugger -- no warnings.
3. Using the File System tab, move the `autoload` folder at `res://addons/pragmatic-godot/autoload` to `res://`
4. Run the project (F5) and stop it (F8). Look at the Debugger -- 27 warnings.

**Minimal reproduction project:**

[concealed_warnings_bug.zip](https://github.com/godotengine/godot/files/5669534/concealed_warnings_bug.zip)

**Comment by Calinou** [comment]
Scripts under `addons/` have warnings excluded by default. You can disable this behavior in the Project Settings.

**Comment by Rubonnek** [comment]
I see. Thanks.
