### ISSUE TITLE
Godot Engine's SVG logo contrast is too low on Github's beta dark mode

### ISSUE THREAD

**Issue by Riteo** [godotengine/godot#44244]
Since Github finally added a (beta) dark mode, The words "Godot game engine" don't contrast enough with the dark background, making reading them a little too hard.
![immagine](https://user-images.githubusercontent.com/31065808/101703165-9bdc5600-3a82-11eb-8529-df08d0ea006a.png)

Maybe there should be an outline of sorts?

**Comment by Calinou** [comment]
Is there much we can do about it? I'm not sure if adding an outline is a good idea, considering this is a general-purpose logo where you don't always want to use an outline for the text.

**Comment by Riteo** [comment]
Well, it could be at least added here, since there's the option of having a dark background.

**Comment by Calinou** [comment]
What I mean is that the README references `logo.svg`, which is meant to be used by third parties as well.

If we want to solve this issue for the README only, we'd have to commit a separate SVG file.

**Comment by Riteo** [comment]
Well, the option of committing a separate version of the logo doesn't sound too bad. A generic `logo_outline.svg` file to pair the clean one would be nice IMO, since this would allow for it to be reused in other places where the background color may cause issues. What do you think?

**Comment by Calinou** [comment]
@Riteo Feel free to open a pull request for that, although I can't guarantee it'll be merged.

**Comment by Riteo** [comment]
The idea of a press kit is a really nice one, and I think that it should be proposed in the appropiate repo. Do you want to propose it yourself, or should I do it? In the meanwhile I think that it would still make sense to make a PR with the outlined version, so I'll do it ASAP

**Comment by Calinou** [comment]
> The idea of a press kit is a really nice one, and I think that it should be proposed in the appropiate repo. Do you want to propose it yourself, or should I do it?

It's already been proposed on the website repository: https://github.com/godotengine/godot-website/issues/44

**Comment by Riteo** [comment]
> It's already been proposed on the website repository: [godotengine/godot-website#44](https://github.com/godotengine/godot-website/issues/44)

Oh, nice. I think later I'll update that thread with this use case as another reason to have a centralized place where to put community-approved variations of the logo.
