### ISSUE TITLE
The 3D scene view does not do a full refresh after re-importing with edits to the .dae file.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4425]
**Operating system or device:**
Win10 64 bit; 24 gigs RAM; third gen i7 CPU; ATI HD 7xxx GPU

**Issue description** **(what happened, and what was expected):**
Editing the scene in a 3D program (in this case Blender), exporting the .dae file, and doing the re-import step does not do a full refresh of either the original scene itself or the scenes containing the edited data as an instance (instead you have to close the scene and re-open it). The only area where the refresh works as it should is when a scene file is being created for the first time.

What's expected is that a full view refresh would happen so the edited data immediately becomes visible. This was the case in Godot 1.x, but this has generally been a nuisance in Godot 2.x and hurts usability (even though it's not a showstopper with the quick workaround mentioned).

**Steps to reproduce:**
Create a 3D scene file, import it to Godot, then edit the 3D scene file and use the re-import dialogue in Godot. Notice how there's no immediate change.

Now close the scene and re-open it, the edits should be there as it should be.

**Comment by slapin** [comment]
This issue is long standing story. The only workaround is to close and open all scenes which depend on imported scene.
Also an issue is not very logical approach re-import, as the only reasonable way to be safe is to always
rewrite scene, keeping your stuff in parent or separate scenes, if you plan to re-import often.
Editing the imported scene can turn into tedious task.

**Comment by Ace-Dragon** [comment]
One of the points being made here is that this did work in Godot 1.x just fine without breaking the scene.

If all you're doing is editing existing objects (without changing their names) or adding objects, then the re-import function can and should be a safe option to use. Things get a little dicier when deleting objects in the 3D program, but that could probably be handled as well. The only thing that can get out of whack is the collision meshes for static geometry, but it shouldn't be a problem if you can tell Godot to use the _-col_ flag as a sign to do a complete rebuild of the collision mesh on re-import.

**Comment by reduz** [comment]
Some questions to understand the issue better: 
1) How is this working with the auto reimport option? 
2) If the scene being imported is closed, do others refresh properly when it changes?

**Comment by Ace-Dragon** [comment]
With the auto re-import it does refresh as it should, but now all of the Godot-assigned materials disappear on re-import (I did read in the logs that the merge options for re-import have vanished for now, but I don't see why the option for keeping the materials intact would vanish as well if that is the case, because there were no issues with that in version 2.

**Comment by reduz** [comment]
Ah yeah, this needs to be done, will work on it asap./
