### ISSUE TITLE
Missing ghost resource dependency after removing script from node and deleting

### ISSUE THREAD

**Issue by pigigi** [godotengine/godot#44250]
**Godot version:**
3.2.1 stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
Removed a script from a node using button in Tree view. Script was open for editing and currently displayed. Closed scene. Did I save? Not sure. Closed script, whose name had (correctly so) vanished from script editor sidebar, while content was still displayed. Deleted script file from FileSystem view. Ran game, crash on launch with error

E 0:00:02.165   ResourceFormatLoaderGDScript::load: Cannot load source code from file 'res://mnbmbnm.gd'.
  <C++ Error>   Condition "err != OK" is true. Returned: RES()
  <C++ Source>  modules\gdscript\gdscript.cpp:2244 @ ResourceFormatLoaderGDScript::load()

Removed dependency manually from .tres, everything fine again.

And yes indeed, that is the best script name ever thank you very much.

**Steps to reproduce:**
Working on it, but similar to above I reckon. Order of events and details are hazy.

**Minimal reproduction project:**
All in due time, young padawan.

**Comment by Calinou** [comment]
@pigigi Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
