### ISSUE TITLE
HttpRequest.timeout property has the wrong type

### ISSUE THREAD

**Issue by Schroedi** [godotengine/godot#44258]
**Godot version:**
3.24b3 and master

**Issue description:**
If I understand the code correctly, the `HttpRequest` uses the timeout to start a `Timer`:
https://github.com/godotengine/godot/pull/30315

The Timer expects seconds: float as parameter. Therefore, `HttpRequest.timeout` should be a `float` as well but is of type `int` currently.

**Suggested fix**
Change HttpRequest.timeout to float and document it. 

Doc draft
> timeout
> Maximum time in seconds for the whole request. The maximum time to connect to the server is additionally limited by the project settings: network/limits/tcp/connect_timeout_seconds.

> RESULT_TIMEOUT = 12 -- Request didn't complete in time, see timeout.

**PR**
I could make the proposed changes and open a PR if desired.

**Comment by Faless** [comment]
Well, to be honest, I don't see how useful the float precision would be for HTTPRequest timeout.

**Comment by Schroedi** [comment]
Fair point; I stumbled upon it when I debugged some other errors and didn't know the unit. So documentation might be enough. 
On the other hand, I don't see why it should be limited to seconds when it already supports smaller increments.
