### ISSUE TITLE
GDScript 2.0: Profiling does not seems to be working

### ISSUE THREAD

**Issue by KaruroChori** [godotengine/godot#44252]
**Godot version:**
Godot 4.0 bc30df8

**OS/device including version:**

Linux 80x86 64bit, GTX 1660 super and RTX 2060 (main one). Drivers 450.80

**Issue description:**
I am working in single window mode.
When I try to profile my scene the number of objects is extremely high even with an empty one (I guess this is justr the rest of the editor showing up) an draw calls are set to zero no matter how many objects with different materials I add.

**Steps to reproduce:**
Open any project. Run the scene and open the profiler. Add some meshes and material. Run the scene and open the profiler. Compare the results.

**Minimal reproduction project:**
No need for a specific project.

**Comment by Calinou** [comment]
@KaruroChori  Can you (or anyone else) still reproduce this bug in the latest `master` branch? You can download a nightly build [here](hugo.pro/projects/godot-builds/).

Also, are you referring to the GDScript profiler or the visual profiler (new in 4.0)?

**Comment by KaruroChori** [comment]
Hi, it would be hard for me to test this. In the last few months I changed graphic cards as well as drivers, so I would not be able to reproduce the exact circumstances.
Your link is not working, could you provide an updated one?
If I recall correctly it should be the one shown here: https://docs.godotengine.org/en/latest/tutorials/scripting/debug/the_profiler.html

**Comment by Calinou** [comment]
@KaruroChori I fixed the link in my comment.

**Comment by KaruroChori** [comment]
[Well, I guess it is worse than last time, now I cannot even open it :(.
https://github.com/godotengine/godot/issues/54962

**Comment by Zireael07** [comment]
Note: as of alpha 1, graphics profiling seems to be working, script profiling is NOT.

**Comment by tavurth** [comment]
<img width="1552" alt="Screenshot 2022-03-26 at 04 07 13" src="https://user-images.githubusercontent.com/100964/160218620-7f9ee36a-d67c-441f-804c-fc7034ec5f8f.png">

Actually seems to be working if you open the debug panel before the game starts.

Seems like the `start` button is getting greyed out incorrectly

**Comment by Zireael07** [comment]
@tavurth What alpha version/master hash is that?

**Comment by tavurth** [comment]
That's on Alpha 4

**Comment by tavurth** [comment]
After digging some more, it appears that when entering the `pause` state, the proflier buttons `Start` and `Stop` become greyed out, and do not properly reset their state when the game is restarted or resumed.
