### ISSUE TITLE
TextureRect not keeping rotation inside tabs

### ISSUE THREAD

**Issue by game-dev-matt** [godotengine/godot#44264]
**Godot version:**
Godot v3.2.3.stable.official

**OS/device including version:**
Windows 10, Version: 10.0.19042 Build 19042, 
CPU: i7-920
GPU: GTX 760
Issue occurs on both: GLSE3 and 2

**Issue description:**
TextureRect does not keep it's rotation inside tab containers when switching tabs. This could possibly affect more than just TextureRects though.

**Steps to reproduce:**
Rotate node in GDScript using either rect_rotation or set_rotation(), then switch tabs, then switch back. The rotation will be reset.

**Minimal reproduction project:**
[RotateTest.zip](https://github.com/godotengine/godot/files/5672578/RotateTest.zip)

**Comment by Calinou** [comment]
This is likely the same issue as scale not being retained for Controls placed within Containers.

**Comment by K750i** [comment]
Encounter the rotation and scale issues today in v3.4 and it's quite baffling why this is yet to be fixed.

**Comment by KoBeWi** [comment]
See #59306
TabContainer is a container and changing tabs will cause layout reset.
