### ISSUE TITLE
Label / RichTextLabel \n not parsed when text is set via Text/Bbcode fields in inspector

### ISSUE THREAD

**Issue by spookdogg** [godotengine/godot#4426]
**Operating system or device:**
Windows 7

**Issue description** (what happened, and what was expected):
Whenever I add \n to Labels/RichTextLabels (the standard text line break) via the Text/Bbcode fields in the inspector, it is never parsed... I can only get it to parse the linebreak if I set/add the text via code
This is especially confusing for newer users, as after trying to add it in using these fields when experimenting and it not working, I believed there was no linebreak character support for Labels/RichTextLabels

**Steps to reproduce:**
Attempt to add a linebreak (\n) to a Label/RichTextLabel via the Text/Bbcode fields in the inspector

**Comment by salalex** [comment]
Perhaps I'm wrong, but I don't think this is a bug: you can add newlines by simply pressing the 'enter' key on the keyboard, while entering the Text/Bbcode in the inspector editor, which you can open by clicking on the "text" icon on right side of the field.
![edit](https://cloud.githubusercontent.com/assets/7436475/14779222/64bb2bcc-0ad7-11e6-88ae-53d0fa74970b.jpg)
The '\n' is a GDScript language-level escape sequence for strings constants.

**Comment by spookdogg** [comment]
I can understand the enter key argument but as I've said previously, it makes it confusing for newer users, especially with RitchTextLabel as other such codes are parsed (technically \n is not bbcode but you could see how it could be confusing)

**Comment by reduz** [comment]
This is not a bug, I honestly wouldn't add this functionality as I think it's not worth it, and we didn't have anyone else complaining about this so far.

**Comment by bojidar-bg** [comment]
I'd vote for closing this as inactive and probably a wontfix, WDYT @godotengine/bugsquad?

**Comment by salalex** [comment]
I agree.

**Comment by kubecz3k** [comment]
@bojidar-bg totally agree
