### ISSUE TITLE
Texture import streamed option should be bool

### ISSUE THREAD

**Issue by Hurakano** [godotengine/godot#44277]
**Godot version:**
master (5b3e2dcaba2b9f3)

**OS/device including version:**
all, code related

**Issue description:**
In https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_texture.cpp#L204 the "streamed" option is created as int:
`r_options->push_back(ImportOption(PropertyInfo(Variant::INT, "compress/streamed"), false));`

and because of that in editor it's displayed as number input and I can input there any intiger value.
![Zrzut ekranu z 2020-12-10 22-20-15](https://user-images.githubusercontent.com/37509321/101831531-54170680-3b36-11eb-9940-28888f3ebb60.png)

But it's default value is 'false' which suggests bool type.
Also, it's later considered as bool anyway:
https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_texture.cpp#L392
`bool stream = p_options["compress/streamed"];`

In my opinion this value should be just bool and displayed as checkbox in editor in this case, but maybe it's intended for some reason, I just stated using godot so I'm not an expert.
I checked that changing type in line 204 to `Variant::BOOL` is enough for it to be displayed properly. I can make this fix, if it's necessary, and make pull request.

**Steps to reproduce:**
try to import texture in editor

**Minimal reproduction project:**
new project is enough

**Comment by Calinou** [comment]
> I checked that changing type in line 204 to Variant::BOOL is enough for it to be displayed properly. I can make this fix, if it's necessary, and make pull request.

Sure, feel free to open a pull request for this :slightly_smiling_face: 

For bug fixes, you don't need to ask before opening a pull request.
