### ISSUE TITLE
Keyboard Input Cancelling out other Keyboard Input

### ISSUE THREAD

**Issue by CalebJep** [godotengine/godot#44278]
So, I'm running Godot 3.2 on a Lenovo ThinkPad Edge with Kubuntu 18.04, KDE Plasma 5.12.9.

I was working on a 3d platformer project, and I noticed I couldn't jump when holding down the up and left arrow keys. I was using space as the jump key. I did some debugging with print statements and such and discovered that when those keys are down, pressing space doesn't call the "_input()" event. I added WASD movement, and when I'm using W + A instead of UP + LEFT, there's no problem. Similarly, when I changed the jump key to "Z", there was no problem, even when using the arrow keys for movement. It seems for some reason, those two keys cancel out the "Space" key.

Steps to reproduce:
1. create a new project
2. Write a script in which "_input()" or "_unhandled_input()" is called
3. Check if the event is the space key (doesn't matter if space is mapped to something like "Jump" or just the default "ui_select") and if so, do something visible
4. Run the scene. Press space while holding down the up and left arrow keys. Even if nothing else in the project uses the arrow keys, this should prevent "_input()" from being called.
5. Tell me if this does what I'm saying it does so I know if it's really a Godot issue or something with my computer.

Example Project:
[Input Bug.zip](https://github.com/godotengine/godot/files/5676025/Input.Bug.zip)

**Comment by KoBeWi** [comment]
No problem here:
![nUamgjACnG](https://user-images.githubusercontent.com/2223172/101839153-2768ec00-3b42-11eb-8405-99725adf7c85.gif)

Your issue is keyboard ghosting. Some keyboards (usually older ones) can't handle certain key combinations. You can workaround it by using a different key (letters should work fine).

Closing, this is not a problem with Godot.
