### ISSUE TITLE
A couple problems with the Splash Screen on Desktop targets

### ISSUE THREAD

**Issue by alexandervrs** [godotengine/godot#4427]
Tested on Windows. Mac & Linux possibly have this issue as well.

**The splash screen has the following issues:**
1. You can't disable it completely in the Project Settings, there should be an option for it (the dev might not want to show it or the game loads very fast so there is no need for it)
2. Appears non-centered, window should be centered (if you center the game window manually, the splash screen flickers to the left top and it looks bad)
3. The splash screen window shows the Godot icon (the little icon top-left), it needs to show the game icon
4. Add more customization in Project Settings? Like, no border for the splash screen window?, Fullscreen splashscreen? Delay in ms? etc.?

_Using Godot 2.0.2_

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by char0xff** [comment]
Points 1 and 4 are still relevant right now in master.
Point 1 because loading a black image is a hack, there should simply be an option to disable the boot splash entirely.
Point 4 because a minimal time duration for the boot splash is useful for a starting scene that loads fast.

**Comment by vnen** [comment]
This can be closed. There are already other issues tracking the relevant points. Also, in Godot the splash screen is not the same as in other software where it's a completely different window, so you can't make it borderless without making the game itself borderless. This issue also conflates the splash image option with the splash screen demo (which is actually a scene, not related to the option).
