### ISSUE TITLE
Custom Multiplayer RPC ignores the name of base root node

### ISSUE THREAD

**Issue by udit** [godotengine/godot#44287]
**Godot version:** 3.2.3

**OS/device including version:** Windows 10

**Issue description:** Custom Multiplayer RPC ignores the name of base root node. Not sure if this is as per design or a bug so opening a issue.

**Steps to reproduce:**
I was playing with custom multiplayer using [this example project](https://github.com/LudiDorici/gd-custom-multiplayer).

Tree structure in minimal reproduction project:
Main
   |--Server  (<---instance of---  Server.tscn  <---inherited from---  CustomMultiplayer.tscn)
   |               |--Connection.tscn
   |
   |--Client   (<---instance of---  Client.tscn  <---inherited from---  CustomMultiplayer.tscn)
   |               |--Connection.tscn            

Here, Connection node of Client is able to call Connection node of Server even though relative node paths of each is "Server/Connection" and "Client/Connection". Server and Client are set as the base root nodes for rpc.

**Minimal reproduction project:**
[Learn.zip](https://github.com/godotengine/godot/files/5677629/Learn.zip)

**Comment by Faless** [comment]
Seems to work as expected. Closing.

**Comment by udit** [comment]
So the path should be considered as "/root/...." irrespective of the name of the root node?

**Comment by Faless** [comment]
> So the path should be considered as "/root/...." irrespective of the name of the base root node?

No, the sent path is relative to the the multiplayer `root_node` setting.
So the client send the path: `./Connection`.
And when the server receives it, it applies the relative path to its root_node:
`/root/Server + ./Connection` = `/root/Server/Connection`
