### ISSUE TITLE
video memory .png file sprite -- Convert to xxxx2D error

### ISSUE THREAD

**Issue by denghe** [godotengine/godot#44291]
**Godot version:**
3.2.4 beta3

**OS/device including version:**
win10/rx5700

**Issue description:**
![image](https://user-images.githubusercontent.com/3364637/101884464-b1ad6080-3bd3-11eb-8bf7-9500414fb471.png)

when i choose Sprite -- click Sprite menu -- Create xxxxxx2D -- , the following error occur:

![image](https://user-images.githubusercontent.com/3364637/101884576-e6211c80-3bd3-11eb-9c53-5ad608830e20.png)
![image](https://user-images.githubusercontent.com/3364637/101884644-0224be00-3bd4-11eb-8957-9a787a23531f.png)
![image](https://user-images.githubusercontent.com/3364637/101884910-57f96600-3bd4-11eb-97cf-da6ac37c7f98.png)

**Steps to reproduce:**
when i set .png -- Import -- Compress -- Lossless, everything is ok, but Video RAM not.

**Comment by Calinou** [comment]
@denghe Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
