### ISSUE TITLE
Version Information in Project Settings for Windows applications

### ISSUE THREAD

**Issue by alexandervrs** [godotengine/godot#4429]
Application executables on Windows supports additional metadata called **Version Information**. The info is available in detail to the user by right clicking and choosing Properties > Details, it also shows the info under the .exe name in the Explorer and Taskbar entry and used for some System dialogs.

I can't seem to find a way to add this via the Project Settings so I am requesting it.
We need fields like:
- Description
- Version
- Product
- Company
- Copyright

_Using Godot 2.0.2_

**Comment by bojidar-bg** [comment]
Related to #1211

**Comment by akien-mga** [comment]
This is now fixed in 3.0 with the integration of `rcedit` in the export dialog (note that you still need to download rcedit yourself and tell Godot where it is).
![screenshot_20180317_092447](https://user-images.githubusercontent.com/4701338/37553265-0cffcc4e-29c5-11e8-8a4f-b92c724a02f3.png)
