### ISSUE TITLE
TileMap Editor is not working correctly

### ISSUE THREAD

**Issue by rohanrhu** [godotengine/godot#44308]
Hi, In Godot `v3.2.3`, TileMap editor is not working correctly. I can't draw collision shapes. It was working in previous versions.

**Comment by Calinou** [comment]
@rohanrhu Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, can you record a video of the editor when trying to draw collision shapes?

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
