### ISSUE TITLE
PhysicalBone 6DOF set/get doesn't check if a property starts with joint_constraints

### ISSUE THREAD

**Issue by Demindiro** [godotengine/godot#44320]
**Godot version:**
```
3.2.3.stable.custom_build.662455ee8
```

**OS/device including version:**
```
$ uname -a
Linux pc 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
```

**Issue description:**
`PhysicalBone` doesn't check whether the first part of a property is `"joint_constraints"` in `set` and `get` if `joint_type == JOINT_TYPE_6DOF`

https://github.com/godotengine/godot/blob/0762484473c1330c5d524d5cc3644d5e2b2e557c/scene/3d/physics_body_3d.cpp#L1712-L1866

https://github.com/godotengine/godot/blob/0762484473c1330c5d524d5cc3644d5e2b2e557c/scene/3d/physics_body_3d.cpp#L1868-L1938

**Steps to reproduce:**
Change `PhysicalBone` to `PhysicalBone3D` for Godot 4.0

```gdscript
extends SceneTree


var bone = PhysicalBone.new()
var t = 0


func _init():
	bone.joint_type = bone.JOINT_TYPE_6DOF
	root.add_child(bone)


func _idle(_delta):
	var x = bone.get("blahblah/x/angular_limit_upper")
	print(x)
	t += 1
	bone.set("foo/x/angular_limit_upper", t)
```

**Minimal reproduction project:**
See above

**Comment by Favkis** [comment]
I don't get what's exactly wrong with .set code though?I really need to fix it but I don't see anything wrong with .set or .get code

**Comment by Favkis** [comment]
I edited file, recompiled it. It broke all my ragdolls, now all joints have 0 degree angular rotations. 

I ctrl+z all changes, recompiled. Same problem. In editor all my joints have correct rotations but in game - it's all 0.

I started project in steam godot, same shit. Why? How? Do I have to fix my save now somehow? It broke godot's ability to change bullet physics constraints?

**Comment by Demindiro** [comment]
@Favkis have you seen #44535?

**Comment by pouleyKetchoupp** [comment]
Junior job info:
`SixDOFJointData::_get` and `SixDOFJointData::_set` needs to be updated so `bone.get("blahblah/x/angular_limit_upper")` would fail and only `bone.get("joint_constraints/x/angular_limit_upper")` would work (same with set).

The current code uses `const String axis_s = path.get_slicec('/', 1);` to get to the axis part and `String var_name = path.get_slicec('/', 2);` to get to the property name part, by splitting the string based on separators. Instead, it should start with validating that the path starts with `joint_constraints` and then process the remaining part of the path.

**Comment by madmiraal** [comment]
See #44876.

**Comment by pouleyKetchoupp** [comment]
@madmiraal This issue doesn't have to wait for #44876.

This issue is still open for junior job.
