### ISSUE TITLE
Make export GUI debug toggle more obvious

### ISSUE THREAD

**Issue by alexandervrs** [godotengine/godot#4432]
I can't seem to find a way/option to **hide the console/commandline window** when running the game in Release mode. I personally saw this on Windows but also on HTML5.

It is extremely important not to have that window visible when publishing a game as the end-user does not need to see this, or have any access to it.

_Using Godot 2.0.2_

**Comment by eska014** [comment]
Can't reproduce this on either Windows or HTML5, are you sure you turned off "Enable Debugging" in export options? Or are you not exporting per GUI?

**Comment by alexandervrs** [comment]
Ah, I just saw the toggle button, it's not very apparent in that dialog, I was expecting it to be in the previous screen per target.

**Comment by eska014** [comment]
This comes up a lot, we should move the toggle to the main export dialog
