### ISSUE TITLE
Turning VSync off doesn't work on the runned projects

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#44329]
**Godot version:**
8c045fc9ff8101a3581045ed4baa02565850aebd

**OS/device including version:**
Win10

**Issue description:**
Turning VSync off in the project settings works in the Editor but the FPS still locked to 60 (monitor hz) in the game.

**Steps to reproduce:**
Create an empty project - Turn VSync off - check FPS by calling `Engine.get_frames_per_second`

**Minimal reproduction project:**
[TestFPS.zip](https://github.com/godotengine/godot/files/5683662/TestFPS.zip)

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/36862.

**Comment by Chaosus** [comment]
Ah, ty, it is a duplicate of https://github.com/godotengine/godot/issues/36467
