### ISSUE TITLE
Tabs' label look incorrect when dragging for rearranging (Also valid on the editor)

### ISSUE THREAD

**Issue by gongpha** [godotengine/godot#44321]
**Godot version:**

Master Branch [`8c045fc`](https://github.com/godotengine/godot/commit/8c045fc9ff8101a3581045ed4baa02565850aebd)

**OS/device including version:**

Windows 10 64-bit ( Vulkan )

**Issue description:**

TabContainer with "Drag to Rearrange Enabled" allows the user to drag its tabs by mouse to rearrange.

**Steps to reproduce:**
In the game :
1. Create `TabContainer` node with `drag_to_rearrange_enabled` is enabled
2. Create 2 tabs. Name it differently.
3. Put any `Control` nodes to tabs.
3. Put tabs inside `TabContainer`.
4. Run a game. And try to drag any tab to any position.
5. Problem arrived. Tab boxes and their contents changed. But their labels aren't.

In the editor :
1. Drag any tab in the editor to any position.
2. Problem arrived the same as the game.

![game](https://user-images.githubusercontent.com/13400398/101987382-6031ce00-3cc6-11eb-8a82-407f14b31160.gif)
![editor](https://user-images.githubusercontent.com/13400398/101987383-60ca6480-3cc6-11eb-97d8-6c05f3bdd40d.gif)

( Sorry for the editor's language, which made you confused. I'm in a hurry )

**Minimal reproduction project:**

[TabContainer.zip](https://github.com/godotengine/godot/files/5683274/TabContainer.zip)

**Comment by akien-mga** [comment]
CC @volzhs in case this is related to recent TabContainer fixes.

**Comment by gongpha** [comment]
Still valid in [`0167bfa`](https://github.com/godotengine/godot/commit/0167bfa530bb4c19ff237d2f12927c60ac452ad7). Before his last commit on `tab_container.cpp`.
