### ISSUE TITLE
Depth/parallax does not work on Spatial Material with Triplanar UVs active

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#44322]
**Godot version:**
3.2.3.Stable

**OS/device including version:**
GLES3, Intel(R) Core(TM) i7-5820K, GTX 970, Windows 10 Pro

**Issue description:**
Depth does not work on Spatial Material with Triplanar UVs active
![Bx5NpD7KbA](https://user-images.githubusercontent.com/4955051/101988159-d9fa9500-3c8f-11eb-977b-aa7737f7380a.gif)
Maybe this is on purpose. Looking at the generated shader code, I can see that the depth texture doesn't get used at all when Triplanar is active, but if that's the case it should warn you about that limitation and it should be mentioned in the documentation.

**Steps to reproduce:**
Open the attached project and observe the materials

**Minimal reproduction project:**
[depth_triplanar_bug.zip](https://github.com/godotengine/godot/files/5683320/depth_triplanar_bug.zip)

**Comment by Calinou** [comment]
I can confirm this on `7195f6b97`'s Vulkan renderer as well (Fedora 33, GeForce GTX 1080).

**Comment by Calinou** [comment]
This was documented by https://github.com/godotengine/godot/pull/44323, closing.

**Comment by sammonius** [comment]
Couldn't this be fixed somehow though?

**Comment by Calinou** [comment]
> Couldn't this be fixed somehow though?

It's technically possible to support, but it's expensive on the GPU. Some people have figured out ways to optimize this (such as using [biplanar mapping](https://iquilezles.org/articles/biplanar/) to reduce the number of texture reads required)), but at this point it's [proposal](https://github.com/godotengine/godot-proposals) territory :slightly_smiling_face:

**Comment by Radivarig** [comment]
There is also 1 sampler triplanar https://www.youtube.com/watch?v=dFApswlwsRc
