### ISSUE TITLE
CanvasItem.draw_polyline does not draw 1px lines when width<=1.0

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#44332]
**Godot version:**

4.0 7195f6b973

**OS/device including version:**

Vulkan

**Issue description:**

Following changes in https://github.com/godotengine/godot/commit/3ec972fc95f3d9fb308af0fded69fc7e53940f78, support for drawing thin lines with draw_polyline seems to have been removed. I believe this is in error.

Using the code:
```gdscript
func _draw():
	draw_arc(Vector2(0, 0), 50, 0, PI * 0.75, 25, Color.white)
```

when zoomed in, the line should be 1px wide, but it looks like this:
![image](https://user-images.githubusercontent.com/6376721/101999849-f78b2700-3cae-11eb-958f-d3a42b1eef7c.png)

**Steps to reproduce:**
See above

**Minimal reproduction project:**

**Comment by briansemrau** [comment]
@Chaosus

**Comment by Calinou** [comment]
This may actually be intended, see https://github.com/godotengine/godot-proposals/issues/1363.

We should support both use cases but we probably have to find another way to do that. I think scaling 1-pixel lines by default *is* a better idea, but there should still be a way to draw "hairline" width lines.

**Comment by briansemrau** [comment]
I do agree that width=1 shouldn't create pixel-thin lines and I generally prefer the behavior demonstrated in this issue. Hairline width should be supported with width=0, not 1. However, right now this function is inconsistent with other line drawing functions and behaves unexpectedly.

**Comment by Chaosus** [comment]
I think adding the `add_thin_polyline` method family is not a bad idea. So instead of `draw_arc`, you would write `draw_thin_arc`.
