### ISSUE TITLE
Visual Script's dictionary variable in the members' window shows its keys in the A to Z format regardless of their index

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#44335]
**Godot version:**

- Godot 3.2.4 beta4

**OS/device including version:**

![Screenshot 2020-12-13 041011](https://user-images.githubusercontent.com/1403194/102005661-5f665f80-3cf9-11eb-89d0-5e6b96b48060.jpg)
![Screenshot 2020-12-13 041144](https://user-images.githubusercontent.com/1403194/102005665-62f9e680-3cf9-11eb-83a7-869ea4bd2e22.jpg)

**Issue description:**

Visual Script's dictionary variable in the members' window shows its keys in the A to Z format regardless of their index, as shown in the screenshot below:
![image20](https://user-images.githubusercontent.com/1403194/102005786-79ed0880-3cfa-11eb-8f65-9abb1847948a.png)

This is very confusing especially when trying to get the keys by their index, as shown in the screenshot below:
![Screenshot 2020-12-13 035909](https://user-images.githubusercontent.com/1403194/102005843-db14dc00-3cfa-11eb-9964-f9adc87692fb.jpg)

I tested this in GDScript also which confirmed that the dictionary's keys are not related to their alphabet order, as shown in the screenshot below:
![Screenshot 2020-12-13 040713](https://user-images.githubusercontent.com/1403194/102005884-39da5580-3cfb-11eb-96c7-b19244c85207.jpg)

I expected the dictionary variable to show its keys based on their index in the members' windows. 

**Steps to reproduce:**

1. Create a dictionary variable in Visual Script.
2. Add some keys.
3. See the value in the members' window.
4. Try to print and get the keys' index.

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/5684304/test.zip)

**Comment by kreaninw** [comment]
This issue still presents as of Godot v3.4.3.rc2.official [0ea54d07f], as shown in the screenshot below:

![Screenshot 2022-02-18 222527](https://user-images.githubusercontent.com/1403194/154780585-90b95173-9c55-42c9-b07e-8075318430ac.jpg)

However, **this issue is fixed** in Godot 4 as of v4.0.alpha2.official [79077e6c1], as shown in the screenshot below:

![Screenshot 2022-02-18 222108](https://user-images.githubusercontent.com/1403194/154780644-0cfdd6b9-78b5-4974-a952-11c2246780f5.jpg)

Note: the variable type icon in the members' window incorrectly shows as the array type due to [issue #58117](https://github.com/godotengine/godot/issues/58117).

I also upload a reproduction project for Godot 4 below:

[G4Test.zip](https://github.com/godotengine/godot/files/8101193/G4Test.zip)

I don't know whether I should close this issue since it's already fixed in Godot 4 but not Godot 3.

**Comment by akien-mga** [comment]
I think we can close it as fixed in 4.0. But anyone is welcome to PR a fix for `3.x` too if wanted.
