### ISSUE TITLE
Shader Graph - Deleting a node in the node editor auto-selects and auto-moves another node.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4433]
**Operating system or device:**
Win10 64 bit; 24 gigs RAM; third-gen i7 CPU; ATI HD 7xxx GPU

**Issue description** **(what happened, and what was expected):**
When deleting a node in the visual node editor, the editor will often auto-grab another node and move it with the cursor. This is not desired and noticeably impacts usability.

**Steps to reproduce:**
Open the example file, open the node tree for the material, select a node, delete the node. Notice how another one automatically sticks to your cursor for no apparent reason.

**Link to minimal example project** **(optional but very welcome):**
[Bugs.zip](https://github.com/godotengine/godot/files/233840/Bugs.zip)

**Comment by hetdegon** [comment]
You mean the visual shader editor? I've gotten this issue before as well, but I wasn't able to replicate consistently. I can now, though.

**Comment by mattiascibien** [comment]
I actually replicated this using lastest master. When clicking on the x the second time you delete a node you get the node attached to the left in dragging mode.

**Comment by vnen** [comment]
I cannot reproduce this issue.

**Comment by djrm** [comment]
i am also unable to reproduce this one maybe it was fixed with #5308

**Comment by akien-mga** [comment]
Closing then.

**Comment by rgrams** [comment]
@akien-mga This bug is alive and well in 2.1 RC2

![shadergraph delete node issue](https://cloud.githubusercontent.com/assets/11370192/17413698/4c705894-5a50-11e6-94d1-e074d2fd33b4.gif)

**Comment by neikeq** [comment]
I can reproduce this too. It doesn't always happens, you must try it multiple times. At least in my case. It also happens after adding new nodes.

**Comment by vnen** [comment]
I also noticed this when playing with the visual scripting.

**Comment by hetdegon** [comment]
I noticed it almost immediately when trying out the visual scripting thingy as well.

**Comment by bojidar-bg** [comment]
Confirmed in the same circumstances.

**Comment by akien-mga** [comment]
Can't check now, but I'm pretty sure we've got one or two recent duplicates of this issue.

**Comment by neikeq** [comment]
@akien-mga I found #3568

**Comment by bojidar-bg** [comment]
I found https://github.com/godotengine/godot/issues/4869

**Comment by quantum-entangler** [comment]
This issue has existed for me since shadergraph was first introduced. I don't think theres been 1 build I've used where this wasn't an issue.

**Comment by akien-mga** [comment]
I can't seem to reproduce anymore in the master branch, it might have been fixed while work was being done on the visual script editor. Can anyone confirm?

**Comment by volzhs** [comment]
I can reproduce in current master head.
A random node is selected when adding, deleting nodes in Shader graph editor.
And also, strange random selection happens when changing `b` value with `Scalar+Vector Operator`
