### ISSUE TITLE
Moving text caret by "word breaks" moves caret incorrectly 

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#44346]
CC @bruvzg 

**Godot version:**
4.0 master 2020-12-14

**OS/device including version:**
WIN 10

**Issue description:**
In text/line edit moving by ctrl+left/right arrow keys skips by words, but does so incorrectly.

In below clips I hold ctrl and press left/right arrow keys until I get to the end of the line.
Godot: Skips symbols (braces, parenthesis, periods, etc)
![3jzJOkm2RD](https://user-images.githubusercontent.com/41730826/102014996-8463dc80-3da4-11eb-8a03-d408e7308fef.gif)

Visual Studio: expected behaviour, stops are parenthesis, periods, etc
![aGsNqsHlWL](https://user-images.githubusercontent.com/41730826/102014988-79a94780-3da4-11eb-8dc9-46fd3e0f6e5b.gif)

**Comment by Calinou** [comment]
Is this a regression from 3.2.3, or was it always like that?

**Comment by EricEzaM** [comment]
Regression after text server.
