### ISSUE TITLE
AnimationTreePlayer API

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4435]
It is not possible from know which node is connected to which from code.
I.e. you can't know which animation is played by this particular blend2 node, for example.
This way if you want to do soma automation, like clean-up animations which are attached to
blending nodes saving animators work and frees yourself from editing messy filters,
you have to guess, which is not good.
You can do the following:

``` gdscript
var anim_filters = {}
func _ready():
    var nodes = Array(get_node_list())
    for m in nodes:
        print(m)
        var t = node_get_type(m)
        if t == NODE_ANIMATION:
            var anm = animation_node_get_animation(m)
            if anm == null:
                var pl = get_master_player()
                var pln = get_node(pl)
                var anim = animation_node_get_master_animation(m)
                anm = pln.get_animation(anim)
            anim_filters[anm.get_name()] = []
            for l in range(anm.get_track_count()):
                var track_type = anm.track_get_type(l)
                if anm.track_get_key_count(l) == 2:
                    anim_filters[anm.get_name()].append(anm.track_get_path(l))
    for m in nodes:
        var t = node_get_type(m)
        if t == NODE_ONESHOT:
            for np in anim_filters[m]:
                oneshot_node_set_filter_path(m, np, true)
```

... etc.
for simple cases which will fill filters for each animation,
then use that filter for matching nodes (named the same as animation)
but this is ugly and stupid.
You should be able to know at _ready time whet is your ATP node setup,
which allows to do small tricks like this without ugly hacks.

**Comment by slapin** [comment]
@JoshuaGrams are you around?

**Comment by bojidar-bg** [comment]
Pretty bump, just in case.

**Comment by vnen** [comment]
I believe @reduz has some plans for AnimationTreePlayer in 3.0.

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
