### ISSUE TITLE
Cannot rename id of canvas when exporting a web version

### ISSUE THREAD

**Issue by codec-abc** [godotengine/godot#44368]
**Godot version:**
3.2.3 64 bits version using mono

**OS/device including version:**
Windows 10

**Issue description:**
I wanted to experiment with the ability of Godot to integrate into a web page and support multiple viewport into the same page. As such, I created 2 html canvas with differents Id. The problem is even with one it doesn't work as long as the html id of the canvas isn't ``canvas``. 

**Steps to reproduce:**
Create a project with Godot 3.2.3 with C# scripting.
Export it to HTML5.
Serve it. At this point it should work as expected.
Now in the generated ``index.html`` change

````html
<canvas id='canvas'>
    HTML5 canvas appears to be unsupported in the current browser.<br />
    Please try updating or use a different browser.
</canvas>
````

to

````html
<canvas id='canvas1'>
    HTML5 canvas appears to be unsupported in the current browser.<br />
    Please try updating or use a different browser.
</canvas>
````

(ie ``canvas`` become ``canvas1``)

and

````js
const EXECUTABLE_NAME = 'godot';
const MAIN_PACK = 'godot.pck';
const INDETERMINATE_STATUS_STEP_MS = 100;

var canvas = document.getElementById('canvas');
````

to

````js
const EXECUTABLE_NAME = 'godot';
const MAIN_PACK = 'godot.pck';
const INDETERMINATE_STATUS_STEP_MS = 100;

var canvas = document.getElementById('canvas1');
`````

ie, ``document.getElementById('canvas');`` become ``document.getElementById('canvas1');``

Serve the page. It doesn't work anymore.

Here the stack trace showing up in Firefox: 
![image](https://user-images.githubusercontent.com/1208646/102094508-b61b8880-3e22-11eb-9109-c98b973768ac.png)

**Comment by codec-abc** [comment]
I made some progress. There is a function in ``godot.js`` that try to retrieve the HTML element from a target argument. The problem is that the argument is a string that contains a leading ``#`` and there is a special case when the string is ``#canvas``.

![image](https://user-images.githubusercontent.com/1208646/102101224-a142f300-3e2a-11eb-965d-15cbadd7bcf9.png)

By patching this I am able to get a canvas whose ``id`` isn't ``canvas`` to run Godot properly. I think this code come from emscripten but I didn't dig more.

Unfortunately, with this patch Godot refuse to run 2 canvas independently even if the 2 viewports have their own engine.

**Comment by Zireael07** [comment]
Unfortunately what you want is not possible - in WebGL, the context is shared even if you have two canvases, so you'll just get two views that are mirrors of each other...

**Comment by codec-abc** [comment]
I don't think so because I think I just suceed in doing that and already did with Unity.

Right now, I have 2 canvas that open the same scene (which is just a moving cube) and then ask their canvas Id through Javascript.Eval function. Then the cube color change differently depending on the ID. The trick, beside patching the godot.js file so it does find the viewport is to only load a engine for a canvas after it is done loading another one. There is probably a global variable which mess up with this but I am quite sure having multiples indepent godot canvas that don't interfere with each other isn't far away.

The good thing with this is that I can build complex 3d web GUI with only C# because I use it on the 3D through Godot and Mono, on the frontend with Blazor and on thr backend with ASP.NET.

**Comment by Faless** [comment]
@codec-abc is this happening with 3.2.4 beta4 too?

**Comment by codec-abc** [comment]
It seems fixed! On the other hand having multiple viewport with independant godot instance still doesn't work. Is it worth opening an issue for it?

**Comment by Faless** [comment]
> having multiple viewport with independant godot instance still doesn't work

Not sure what you mean by "multiple viewport with independant godot instance".
If you mean running 2 instances of Godot on 2 different canvases that should work (the web editor does that).
If you mean having only one instance of Godot that renders in multiple canvases, that's not possible, and we don't really have plans for it.
It might be possible in 4.0 to implement Window to render on its own canvas (right now it does not support multiple windows), but will likely require a lot of work.
