### ISSUE TITLE
Function yield(obj, signal) does not block execution

### ISSUE THREAD

**Issue by tvardero** [godotengine/godot#44364]
Searching and reading existing issues does not help me with solving my problem (#17280 , #3235).

**Godot version:**
v3.2.3 mono
Win10 x64

**Issue description:**
Code is similar to this one:
```gdscript
onready var client: StreamPeerTCP = StreamPeerTCP.new()
onready var wrapper: PacketPeerStream = PacketPeerStream,new()
enum CustomErrors {...}
signal response_recieved # "response_recieved" are always sent with integer argument of error in enum CustomErrors
...
func _ready() -> void:
    client.connect_to_host("127.0.0.1", 504)
    wrapper.stream_peer = client
...
func requester(code: int, args: Array = []) -> int:
    # Posting data to server
    var assemble: Array = [code, args]
    var bytes: PoolByteArray = var2str(assemble).to_utf8()
    var packets: Array # bytes are sliced in packets by 128
    for packet in packets:
        wrapper.put_packet(packet)
    
    # THIS IS WERE PROBLEM BEGINS
    # Waiting for server response using _process function
    set_process(true)
    print_debug("BEFORE YIELD")
    var response = yield(self, "response_recieved") 
    print_debug("AFTER YIELD")
    if not response is int:
        print("RESPONSE IS NOT INT")
        print(response)
        return 1
    return response

func _process
    print("PROCESS CALLED")
    if client.get_status() == 2 and wrapper.get_available_packet_count(): # If connected to server AND has packets received
        set_process(false) # This DOES NOT terminates current execution of _process
        while wrapper.get_available_packet_count():
            var bytes: PoolByteArray = wrapper.get_packet()
            var response: int = bytes.get_string_from_utf8().to_int()
            print("SIGNAL EMITTED") 
            emit_signal("response_recieved", response) # This is THE ONLY source of "response_recieved" signal
        
```

**What was expected:**
yield function stops function requester(), then function _process() is called by the engine and yield continues.

**What was in fact happened:**
Console log:
```
BEFORE YIELD
AFTER YIELD
RESPONSE IS NOT INT
Null    <--- that what response variable holds
```
Note that neither "PROCESS CALLED" nor "SIGNAL EMITTED" were printed. 

**Project**
This is client side of my project to control SolidWorks application using SolidWorks API. Server side is console app on C#.
Reason why I don't use C# inside Godot to control SolidWorks: SolidWorks API bugs, crashes, and null returns. Might be COM related problems, but I've just started programming in general, can't tell surely.
Project is uploaded to my GDrive and will be there for at least 6 month.
https://drive.google.com/file/d/1w9Djy_m07aj2Z4PdxmlzheIJiqm6bDJl/view?usp=sharing

Run server first, I use Visual Studio 2019 for it.
To run into the problem, run Godot project (Main.tscn), first press "Сброс" button (which is Reset, it will load predefined values into all the fields) and then press "Перестроить" ("Rebuild").

**Comment by Demindiro** [comment]
```gdscript
	match cmd_num:
		0:
			rtn = request(cmd_num, asm_path)
		1, 3:
			rtn = request(cmd_num, prms)
		2, 4, 6:
			rtn = request(cmd_num)
		5: 
			rtn = request(cmd_num)
			open_csv()
	if rtn is GDScriptFunctionState:
		err = rtn.resume()
```
You are calling [`GDScriptFunctionState.resume()`][1]. Of course it doesn't stop then.

[1]: https://docs.godotengine.org/en/stable/classes/class_gdscriptfunctionstate.html?#class-gdscriptfunctionstate-method-resume

**Comment by tvardero** [comment]
Oh...

Well... [picnic](https://en.wikipedia.org/wiki/User_error)
Sorry

**Comment by tvardero** [comment]
I've just now come up with an idea to add warning "yield state unhandled"  or  "yielded function return value ignored" to improve usability of yield function for newbies.
Do I need open a new issue with this proposal in Godot proposal tracker?
@Chaosus
