### ISSUE TITLE
Movable collision object for collision avoidance

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4437]
We all seen that Godot lacks collision bodies which could be controlled by bones.
So it should have feature of static body (not movable on its own), but
still collide and prevent collisions from occurring (collision avoidance).

While we can sorta implement this for triggering (i.e. hit boxes ,etc.)
using Area but that will not solve a problem of collision avoidance.

Also we can manipulate positions of collision bodies within RigidBody from code.

This is more actual when  using bones, as other cases can be handled by adding many collision shapes. But you might want to switch them on and off depending the animation you run.

But for character animation this is different, as overall game experience depends on collision quality.

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
