### ISSUE TITLE
NodePath set in editor breaks if any parent is reparented

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#44380]
**Godot version:** 3.2.3 stable

**OS/device including version:** Windows 10

**Issue description:**

Assigning a NodePath in the editor to point to a node, and then moving a parent not in the path changes the path to no longer be relative to the original node with the script that has the NodePath.

**Steps to reproduce:**
have this node hierarchy
![image](https://user-images.githubusercontent.com/7292421/102137213-b2cecf80-3e17-11eb-9c82-30c71998a0ec.png)

put this script on Spatial4:
```
extends Spatial


export(NodePath) var test_path

func _ready():
	get_node(test_path)
```
In editor assign the nodepath to point to Spatial5, it will show up as "../Spatial5"
![image](https://user-images.githubusercontent.com/7292421/102138055-0261cb00-3e19-11eb-9270-bbc733fd683d.png)

Move Spatial3 to be a child of Spatial6.
![image](https://user-images.githubusercontent.com/7292421/102138118-19082200-3e19-11eb-8b55-bfc67e9db8cc.png)
the NodePath in editor on Spatial4 changes to "../../../Spatial6/Spatial3/Spatial5/"
![image](https://user-images.githubusercontent.com/7292421/102138171-2d4c1f00-3e19-11eb-8d17-77ca86705b6f.png)

it will work if you run the scene but the path shouldn't be changed.

If you reparent Spatial2 to Spatial6 it will completely break the path and throw an error when the scene is run
![image](https://user-images.githubusercontent.com/7292421/102138197-389f4a80-3e19-11eb-87d2-d325ba9b4e67.png)
![image](https://user-images.githubusercontent.com/7292421/102138211-405eef00-3e19-11eb-8dc9-4fd14f3ffd51.png)

Sometimes this would happen to me if saving a parent as a scene, but haven't been able to reproduce it here.

**expected behaviour:** the Nodepath should stay as "../Spatial5" 

**Minimal reproduction project:**

[NodePathBug.zip](https://github.com/godotengine/godot/files/5691674/NodePathBug.zip)

**Comment by mbrlabs** [comment]
That was fixed in #42314. Can you try this with `3.2.4 beta4`?
