### ISSUE TITLE
Shader makes text unreadable

### ISSUE THREAD

**Issue by Jattmackson** [godotengine/godot#44395]
**Godot version:**
3.2.1.stable.official

**OS/device including version:**

Windows 10 64bit Nvidia 1060 6GB
GLES3

**Issue description:**

Attaching a basic fragment shader to a control node which includes text replaces the text with rectangles

**Steps to reproduce:**
-Create a label node or a button node (likely true with other text but tested with these)
-Add a new shader material and shader:

shader_type canvas_item;
void fragment(){
	COLOR=COLOR;
}

**Minimal reproduction project:**
[Shader Text Bug.zip](https://github.com/godotengine/godot/files/5696447/Shader.Text.Bug.zip)

**Comment by Calinou** [comment]
Can you test this on [3.2.4beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-4)? It features revised 2D rendering code GLES3 and GLES2 batching support. (Make a backup of your project before upgrading!)

**Comment by lawnjelly** [comment]
It's the same in 3.2.4. It's not really a bug, just a confusing aspect of how shaders work...

The shader should really be:
```
void fragment(){
	COLOR=texture(TEXTURE, UV);
}
```
COLOR as an output isn't the same as COLOR as an input, I think COLOR input is the vertex color, not the COLOR after a texture is applied. If you use COLOR you have to apply the texture yourself. At least that is my understanding.

**Comment by Jattmackson** [comment]
> It's the same in 3.2.4. It's not really a bug, just a confusing aspect of how shaders work...
> 
> The shader should really be:
> 
> ```
> void fragment(){
> 	COLOR=texture(TEXTURE, UV);
> }
> ```
> 
> COLOR as an output isn't the same as COLOR as an input, I think COLOR input is the vertex color, not the COLOR after a texture is applied. If you use COLOR you have to apply the texture yourself. At least that is my understanding.

Just tried this and that works =) Many thanks for explaining this.
