### ISSUE TITLE
Valid drop locations are not highlighted when inspector is made floating.

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#44390]
**Godot version:**
4.0 master 2020-12-15

**OS/device including version:**
Win 10

**Issue description:**
No highlighting on valid drop locations in inspector after it has been made floating.
![floating_inspector_no_highlight](https://user-images.githubusercontent.com/41730826/102187217-6c54a000-3eff-11eb-8971-020f7bb1ca47.gif)

**Steps to reproduce:**
Make inspector floating, try to drag and drop.

**Comment by EricEzaM** [comment]
Tested & works fine on latest mater

**Comment by KoBeWi** [comment]
Still valid in 4.0 alpha 7.
