### ISSUE TITLE
Wrong behavior of ScrollContainer in EditorPlugin

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#44397]
**Godot version:**

Godot 3.2.3.stable

**OS/device including version:**

MacOSX 10.15.7 (19H2)

**Issue description:**

I'm trying to make editor plugin. I've made some ScrollContainer with some test data. In editor UI this scroll container have very little height, less then one item in it's VBoxContainer. And I have no ideas what is wrong with it.

The UI in editor.
![Снимок экрана 2020-12-15 в 18 57 58](https://user-images.githubusercontent.com/1177068/102239183-a45fe100-3f07-11eb-978e-82581e97c812.png)

Scroll container.
![Снимок экрана 2020-12-15 в 18 58 39](https://user-images.githubusercontent.com/1177068/102239232-b2adfd00-3f07-11eb-8a14-0286b17a7669.png)

Resulting editor plugin interface.
![Снимок экрана 2020-12-15 в 18 57 43](https://user-images.githubusercontent.com/1177068/102239303-c48fa000-3f07-11eb-8f0e-de30c6f091c8.png)

**Steps to reproduce:**

**Minimal reproduction project:**

It's not the whole project, just zipped folder with editor plugin.
[addons.zip](https://github.com/godotengine/godot/files/5697052/addons.zip)

**Comment by pycbouh** [comment]
I think it's the `Panel` node that breaks things. There needs to be a container, try switching it for `PanelContainer`.

**Comment by Zylann** [comment]
I think main screen UIs like you are making are added under a container. So unlike viewing in the edited scene, you need to tell that container to expand your root control. Otherwise, it will shrink to its minimum size.
Try setting the vertical size flag of your root control to `expand`.

**Comment by pycbouh** [comment]
Ah yes, agree with Zylann. My root node is also `size_flags_vertical = 3`, so it must be required.

**Comment by Zylann** [comment]
I think the container of main screen controls could simply be one that expands its child. No need to introduce extra types for such a specific case

**Comment by DrMoriarty** [comment]
Thanks @pycbouh and @Zylann !
I changed MainUI's Size Flags to Fill + Expand and it works as expected!
