### ISSUE TITLE
A rigidbody without a collisionobject 2d does not react to torque

### ISSUE THREAD

**Issue by CombustibleLemonade** [godotengine/godot#4439]
**Operating system or device:**
Tested on Ubuntu 16.04

**Issue description** (what happened, and what was expected):
A 2D rigid-body was added, and an off-center impulse was applied. A polygon was added as a child of the rigidbody to see rotation. When run, the rigidbody remained unrotated. Then I added a collisionshape, and the torque suddenly did affect the rigidbody.

**Steps to reproduce:**
Paste attached scene and script into empty godot project. Run the scene. Obsereve rotation. Delete CollisionShape2D. Run scene again. Observe no rotation.

**Link to minimal example project** (optional but very welcome):
[RigidBodyIssue.zip](https://github.com/godotengine/godot/files/234613/RigidBodyIssue.zip)

**Comment by JoshuaGrams** [comment]
Yes, this is annoying. To apply torque, you need to know the moment of inertia of the rigid body (which is **not** the same as mass; it depends on how the mass is distributed.  Most physics engines allow you to set the moment of inertia directly, but Godot only auto-computes it from the mass and the shapes. So you need a shape.

**Comment by akien-mga** [comment]
Maybe there could be a RigidBody{,2D} option to let users specify if the inertia should be derived from the mass + shape, or defined as a fixed value by the user?

**Comment by akien-mga** [comment]
Fixed by #4387.

**Comment by JarLowrey** [comment]
So how can we set the moment of inertia now without adding the shape node?

**Comment by JoshuaGrams** [comment]
I gave up on Godot most of a year ago, but I *believe* `set_inertia` should work...

http://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#class-rigidbody2d-set-inertia
