### ISSUE TITLE
Vector2i multiplied by float gives wrong results

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44408]
**Godot version:**

cb42bf1
3.2.x (C++)

**Issue description:**

```
print(Vector2i(256, 256) * 0.9)
```
This prints `Vector2i(0, 0)` while it should be `Vector2i(230, 230)`

**Comment by aaronfranke** [comment]
Should it give `Vector2i(230, 230)`, or should it give `Vector2(230.4, 230.4)`? Since an int multiplied by a float (ex: `256 * 0.9`) results in a float (`230.4`), I guess an integer vector multiplied by a float should too.

**Comment by KoBeWi** [comment]
> Should it give Vector2i(230, 230), or should it give Vector2(230.4, 230.4)?

I think the it should be `Vector2i(230, 230)`. Vectors aren't primitives. Or maybe it could be converted if the variable is untyped.

**Comment by EricEzaM** [comment]
I agree, to me it should be returning a Vector2i

**Comment by dalexeev** [comment]
I think meaning should prevail over form. We need to be very careful with similar but slightly different types. Especially in terms of consistency of behavior. Now in Godot there are many paired types:

`int` — `float`
`String` — `StringName`
`Vector2` — `Vector2i`
`Vector3` — `Vector3i`
`Rect2` — `Rect3i`

In GDScript, you cannot compare values of different types, this causes a parsing or runtime error (in many other languages, this simply returns false). However, an exception is made for the `int` — `float` pair. You can compare them without any problem. `int` values are accepted wherever a `float` value is expected.

```gdscript
print(2 == 2.0) # True
```

This and a couple of other things (see [comment](https://github.com/godotengine/godot/pull/43959#issue-529122081)) might give the user the impression that `int` and `float` are just numbers that can be safely handled regardless of their exact type ([but this is not the case](https://github.com/godotengine/godot-proposals/issues/1866)).

New types, differing only in that they are based on `int` / `float`, should behave like `int` / `float`. For example, where `Vector2` is expected, it should be possible to pass `Vector2i`, etc. I checked, now we cannot compare `TYPE` and `TYPEi`:

```gdscript
print(Vector2() == Vector2i()) # Error
print(Vector3() == Vector3i()) # Error
print(Rect2() == Rect2i()) # Error
```

Also, as far as I remember, there are questions with implicit conversions of `String` <-> `StringName`. This attitude towards the type system can lead to inconvenience and strange bugs. Remember that GDScript is a dynamically typed language. And even when type hints are used, they can be omitted, unlike in C:

```c
int a = f();
float b = g();
```

```gdscript
var a := f()
var b := g()
```

We need to discuss this. I am sure that these problems exist and they are serious enough, but I cannot formulate them well enough and say how we can fix these problems.

**Comment by aaronfranke** [comment]
I looked into solving this issue and it's very non-trivial.

* If I add an overload for multiplication/division with `real_t` or similar, then it becomes ambiguous for all integer types which operator it should use. Many parts of the code use `int` or `int32_t` or `uint32_t` or `int64_t` and more, so the compiler doesn't know whether to convert these to the integer type or to `real_t`.

  * If we removed the integer operator and *only* had an operator for multiplying/dividing by `real_t`, then that would be slower for the more common use case of integer division.
  
  * If we had an operator for every integer type, that would be a lot of code.
  
  * If we wanted to only have two operators, we would need a lot of explicit casting all over the codebase.

I think the best and easiest solution is to require users to be explicit about what they want, so I opened #44441 for this.

**Comment by JFonS** [comment]
> If we had an operator for every integer type, that would be a lot of code.


Not sure about what the best solution is, but this specific problem could be solved by defining a macro and applying it to whatever types we want to support.

**Comment by mhilbrunner** [comment]
We discussed this in a PR meeting, needs a look/fix by @vnen or @reduz

**Comment by reduz** [comment]
I have been thinking about it, and I believe it is wrong to assume it should return integer. Integer by float should always be float, no matter whether scalar or vector.

**Comment by KoBeWi** [comment]
Well it could be `Vector2` too, as long as the result is correct.

**Comment by reduz** [comment]
The only limitation I see is that doing

vec2i *= float
vec3i *= float

should not work in GDScript if the variable is typed. @vnen can you make sure this can be the case?
