### ISSUE TITLE
GDScript No constructor of "int" matches the signature "int(String)"

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#44407]
**Godot version:**

4.0.dev a511a26ad8

**OS/device including version:**

Windows 10

**Issue description:**

```gdscript
var text: String = "12345"
var number: int = int(text)
```
This gives an error "Parser Error: No constructor of "int" matches the signature "int(String)".
Per the [documentation](https://docs.godotengine.org/en/latest/classes/class_int.html#class-int-method-int), this constructor should exist. I know of no other way in GDScript to parse a string without writing the implementation myself, so I'm not sure how to work around this.

**Steps to reproduce:**
See above

**Minimal reproduction project:**

**Comment by Zylann** [comment]
Checking the doc: try `to_int()` https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-to-int

**Comment by briansemrau** [comment]
Thank you, that works. I'm not sure if this is a missing implementation issue or a documentation issue.

**Comment by Zylann** [comment]
It worked in Godot 3.2, but changes occurred in Godot 4.0 so it might be intented, or not.

**Comment by vnen** [comment]
I believe this was removed in #43403 but I'm not sure if it was intentional.

**Comment by KoBeWi** [comment]
I gave a try at restoring the constructor, but my code is sus and doesn't work for floats:
https://github.com/KoBeWi/godot/commit/fd8b1b5eceb40978536d1504f93d1c74a5caf0c9
Int constructor works though (in GDScript at least)

**Comment by akien-mga** [comment]
See #55284 for more examples of related issues with String to int casting.

**Comment by cdemirer** [comment]
> I gave a try at restoring the constructor, but my code is sus and doesn't work for floats: [KoBeWi@fd8b1b5](https://github.com/KoBeWi/godot/commit/fd8b1b5eceb40978536d1504f93d1c74a5caf0c9) Int constructor works though (in GDScript at least)

I don't know why only int worked, but I commented a bugfix (for both int and float)
