### ISSUE TITLE
Android export broken on Windows with 3.2.4 beta4

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#44409]
**Godot version:**
3.2.4 beta4

**OS/device including version:**
Windows 10

**Issue description:**
When exporting to Android (APK) with custom templates i get this error.
This only happens when i export directly into the root of a drive `(eg. D:\)`. When i export to `D:\foo\` it works. 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':copyAndRenameDebugApk'.
> java.io.IOException: The filename, directory name, or volume label syntax is incorrect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Steps to reproduce:**
Create a new project, install export templates and export.

**Comment by Calinou** [comment]
@mbrlabs Did it work on 3.2.4beta3 and prior when exporting to `D:\`?

**Comment by mbrlabs** [comment]
The same issue exists in `3.2.4 beta1`. The problem for me is that `export_path.is_rel_path()` in line 2811 is true for `D:\`, which results in something like `C:\Users\mbr\Documents\Projects\Godot\Foo\D:`. That code has been added when adding support for AAB in commit 3de720c11dbd828be310b6732e9d8940f674cd99 (#43526)

https://github.com/godotengine/godot/blob/574ca8a8cd91354e4de97be3f5805c2bd1332ffd/platform/android/export/export.cpp#L2809-L2823
