### ISSUE TITLE
I can't do a custom build for android

### ISSUE THREAD

**Issue by CHIESOFTWARE** [godotengine/godot#44405]
**Godot version:**
godot 3.2.4 beta

**OS/device including version:**
Linux ubuntu studio 20.04

**Issue description:**
Export the project as I always do from godot 3.2.3 but the console freezes at startup. It doesn't even start the build

**Steps to reproduce:**
Do a custom build for android and that's it, it will not advance beyond the console.
![Captura de pantalla_2020-12-15_15-29-46](https://user-images.githubusercontent.com/29322316/102263313-82a43100-3eea-11eb-8242-6e9a7ec7c1e2.png)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
>  godot 3.2.4 beta

Which beta?

Did you reinstall the Android source template in your project folder to match the beta version you're using? (`res://android`)

**Comment by CHIESOFTWARE** [comment]
yes i did reinstall the source template, beta 3.2.4 beta 4 x11-64

**Comment by mbrlabs** [comment]
That's probably normal. The Gradle Daemon can take forever to startup. How long have you waited?

**Comment by CHIESOFTWARE** [comment]
I wait like 10 min and i check mi task manager and it wasn't consuming ram or anything seemed idle.
In order to use the engine again, I was forced to kill the task after I had waited long enough. With godot 3.2.3 it works without problems and this procedure I have already done before since godot 3.2

**Comment by m4gr3d** [comment]
@CHIESOFTWARE Are you still running into this issue?

**Comment by CHIESOFTWARE** [comment]
@m4gr3d yes , you find a wallkarround ?

**Comment by CHIESOFTWARE** [comment]
@m4gr3d ok i will check that

**Comment by CHIESOFTWARE** [comment]
@m4gr3d After waiting about 6 minutes the console began to print more messages and approximately 8 minutes later this message appeared:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripReleaseDebugSymbols'.
> NDK at /home/manuel/Android/Sdk/ndk-bundle did not have a source.properties file

Exit code 1

**Comment by CHIESOFTWARE** [comment]
@m4gr3d i fix it by adding my on source.properties file, now i running fast no more long waiting

**Comment by m4gr3d** [comment]
@CHIESOFTWARE Sounds like the ndk was not properly setup for you. Not sure why that caused an issue on your setup but installing the ndk from the [sdkmanager](https://developer.android.com/studio/command-line/sdkmanager) should also resolve the issue.

Glad you were able to resolve it!
