### ISSUE TITLE
Shapes generated by CollisionShape helper node are not named properly

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4440]
The CollisionShape helper node doesn't call set_name() on on shape it makes,
which lead to problems identifying them.

**Comment by eska014** [comment]
CollisionShape doesn't create Nodes, you can name the CollisionShape node itself

Shapes themselves don't have names, just an ID to refer to within a CollisionObject node, e.g. in `get_shape()`

**Comment by slapin** [comment]
Shapes do have name as any Resource. These are set by set_name(). Not
setting the name is a bug.

**Comment by bojidar-bg** [comment]
@slapin Given that you can set the name of the resource on your own (by editing the shape resource the helper node adds), I'm not sure if I get the problem.

**Comment by slapin** [comment]
Yes, thanks, it makes this sloved, but, I think it would be nicer if CollisionShape helper node
would aid there (usability +100) and this should be easy to do.

**Comment by Calinou** [comment]
Is this issue still relevant in the current `master` branch?

**Comment by slapin** [comment]
Currently this is irrelevvant because there are ways to achieve the
intended thing but still some way to go from shape id to actuall
shape or CollisionShape object would be nice. Currently Godot allows shape
sweeping through API so it is much less relevant now.
So I'm fine if this is closed unless somebody have better idea.

**Comment by Calinou** [comment]
Alright, I'll close this then. Thanks for replying :slightly_smiling_face:
