### ISSUE TITLE
Godot 3.2.4 beta 4 not supported by your gpu drivers message (it runs anyway)

### ISSUE THREAD

**Issue by crapaam** [godotengine/godot#44415]
Godot version: 3.2.4 beta 4 standard

OS/device including version: Linux Pop Os 20.10 and windows 10
Notebook lenovo x240 (linux) and AMD ryzen 3400g with integrated vega 11 (win)

Issue description:
When creating a new project in the project manager, under the OpenGL ES 3.0 option, appear the "not supported by your gpu drivers" message.
Anyway, it let me create the project and run it with GLES 3 renderer.

Steps to reproduce: Open Godot 3.2.4 beta 4 and create a new project. The message appear under OpenGL 3.0

The project seems to run well, it's only the message.
It doesn´t happen in 3.2.4 beta 3 and previous versions.
thanks

**Comment by akien-mga** [comment]
This is fixed with #44302.
