### ISSUE TITLE
disassembler crash in OPCODE_ASSIGN_TYPED_NATIVE

### ISSUE THREAD

**Issue by jordo** [godotengine/godot#44417]
Latest master:

I can not disassemble functions using OPCODE_ASSIGN_TYPED_NATIVE due to a crash in OPCODE parsing OPCODE_ASSIGN_TYPED_NATIVE:

<img width="1351" alt="Screen Shot 2020-12-15 at 8 48 55 PM" src="https://user-images.githubusercontent.com/323868/102298668-24da0e00-3f17-11eb-9fc6-f2a82b5cb142.png">

**Comment by jordo** [comment]
The crash is unrelated to the issues listed above, but fixed with the correct dissasembly in #44419

**Comment by akien-mga** [comment]
Fixed by #44419.
