### ISSUE TITLE
Backspace doesn't work properly in TextEdit on Android

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#44416]
**Godot version:**
Master 92d4deedaa542e9458845fdf2b2a44fedd19fde8

**OS/device including version:**
Android 11 (Pixel 3)

**Issue description:**
After leaving and entering again a `TextEdit` control on Android, erasing the previously entered text doesn't work.

There's an error in the log when the virtual keyboard is triggered:
```
ERROR: TextEdit::_base_get_text: Index p_to_column = 5 is out of bounds (text[p_to_line].length() + 1 = 5).
   At: scene\gui\text_edit.cpp:4018
```

On this line in the new code:
```
String text = _base_get_text(0, 0, selection.selecting_line, selection.selecting_column);
```

I can confirm `selection.selecting_column` is 5 and not 4 in this scenario by debugging step by step on Windows (and forcing the virtual keyboard path).

This issue seems to be due to #43561 (CC @naithar)

**Steps to reproduce:**
1. Launch MRP (or create a scene with `TextEdit` and `LineEdit`)
2. Select the `TextEdit` control
3. Type `abcd`
4. Select the `LineEdit` control
5.Select the `TextEdit` control again (after `abcd`)
6. Press backspace on the virtual keyboard
7. Observe backspace is not working

**Minimal reproduction project:**
[android-ui-4.0.zip](https://github.com/godotengine/godot/files/5699827/android-ui-4.0.zip)

**Comment by naithar** [comment]
https://github.com/naithar/godot/commit/10eeeca18dc01ef9411f84dd2343d3fe82e44b3d - I've ported latest commit from #43560 PR. 
It should fix this issue. I'll try to test it tomorrow and make a PR for `master`.
