### ISSUE TITLE
Remove default commit message in VCS commit dock

### ISSUE THREAD

**Issue by Omicron666** [godotengine/godot#44413]
Current commit message should be a placeholder (instead of default message).

![image](https://user-images.githubusercontent.com/23405122/102286976-b0649680-3f39-11eb-929c-416c6216e13d.png)

like 
![image](https://user-images.githubusercontent.com/23405122/102287037-ddb14480-3f39-11eb-8639-ffa3d042f3bd.png)
![image](https://user-images.githubusercontent.com/23405122/102287127-09ccc580-3f3a-11eb-9185-d863f199d9f0.png)

Also without a placeholder, after a commit, the text box of commit message is emptied and unhinted about its use.

Suggested solution:  TextEdit implements placeholder functionnality

**Comment by EricEzaM** [comment]
Shouldn't this title be changed to "add placeholder functionality to textedit"?

**Comment by Calinou** [comment]
Closing in favor of a proposal: https://github.com/godotengine/godot-proposals/issues/1995

**Comment by akien-mga** [comment]
Well I still think that if this can't be a placeholder, it shouldn't be pre-filled. Pre-filling a bad commit message leads to bad Git commits. It should be empty, and the commit button should be disabled while there is no content.
