### ISSUE TITLE
Node Multi-Edit can't attach script to multiple nodes

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#4442]
**Issue description** (what happened, and what was expected):
I've tried to add same script to multiple nodes using multi-edit feature and properties editor. It didn't worked had to add them manually to each node :)

**Steps to reproduce:**
Create many nodes.
Select them.
Turn ON multi-edit/
Go to properties and try to attach script to them.

**Comment by kirilledelman** [comment]
Honestly, having to click an extra button to enter "node multi edit" mode when multiple nodes are selected is silly.

There's never a situation when you have multiple nodes selected, and you would only desire to edit properties of one of them in the inspector. You always want to edit them all.

It should enter multi-node mode automatically. Or at the very least be configurable to be automatic.

**Comment by neikeq** [comment]
As of f9d615e multi-node edit is automatic. Can you confirm if the issue is still valid in the current master branch?

**Comment by reduz** [comment]
@kirilledelman multi node edit is now automatic
