### ISSUE TITLE
Vulkan renders the colors of unshaded 3D meshes differently than in 2D

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#44425]
**Godot version:**
92d4deedaa542e9458845fdf2b2a44fedd19fde8 master

**OS/device including version:**
Windows 10, GeForce RTX 2060/PCIe/SSE2

**Issue description:**
If you have an unshaded MeshInstance3D and a ColorRect overlap each other i would expect the ColorRect to not be visible when both have the same color (the albedo color of the BaseMaterial3D is the same as the ColorRect color). In `3.2.x` that was the case for GLES2 and GLES3, but on master the ColorRect appears darker:

![Capture](https://user-images.githubusercontent.com/8750135/102355933-d6774e80-3fac-11eb-90c0-bd6ebcf9fc5e.PNG)

**Minimal reproduction project:**
[ColorBug.zip](https://github.com/godotengine/godot/files/5703055/ColorBug.zip)

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/66683
