### ISSUE TITLE
The editor does not update when adding frames to an AnimatedSprite using SpriteFrames editor

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#44438]
**Godot version:**

3.2.4 beta 4 mono

**OS/device including version:**

win10 64

**Issue description:**

In an animated sprite node with the "Playing" property activated, it works correctly with two frames, the "Frame" property indicates each frame correctly, however, if you add one more frame (it would be number 2), then the "Frame" property does not show this frame and keep oscillating between frame number 0 and frame number 1.

In the gif, notice that when I add frame number 2, the "Frame" property doesn't show it and you can only see 0 and 1.
![gif](https://user-images.githubusercontent.com/19652075/102388547-37fde400-3fd2-11eb-8206-217ba403d6f6.gif)

**Steps to reproduce:**
Add an "AnimatedSprite" node
Add two frames
activate the "Playing" property
notice the "Frame" property
Add a third frame
Note that the "Frame" property does not display frame number 2 even though the animation looks correct.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Fixed in 3.3.2

**Comment by akien-mga** [comment]
Fixed by #49495.
