### ISSUE TITLE
simple gltf import causes inspector viewport graphics issue

### ISSUE THREAD

**Issue by xenopulse** [godotengine/godot#44432]
**Godot version:**

3.2.3

**OS/device including version:**

GLES 3 on Win10, i5-9600K, 32GB RAM, GTX 1080 Ti (drivers 457.30), monitor at 144Hz

**Issue description:**

Opening up one of my Blender gltf2.0 exports (a simple model of a flat 5x5x0.5 floor with a square hole in the middle with cylinders for grate bars, no materials assigned), the viewport in the inspector does not clear each frame that it draws anew (everything smears across the screen, including the xyz coordinate lines). See video here: https://youtu.be/8PKvicCqxvQ

**Steps to reproduce:**
[floor_grate.glb.zip](https://github.com/godotengine/godot/files/5703334/floor_grate.glb.zip)

**Minimal reproduction project:**

See attached gltf file.

**Comment by akien-mga** [comment]
I tried on Linux with 3.2.3 and latest `3.2`, but I can't reproduce the issue (neither with Intel HD 630 and AMD Radeon RX Vega M).

**Comment by xenopulse** [comment]
Upon further testing, it now happens in this project when opening any scene based on gltf. And I can open this fine in any other project. So it must be something wrong with the particular project. Sorry for the confusion, I'll try removing some parts to create an uploadable project.

**Comment by xenopulse** [comment]
[Receiver MIRU.zip](https://github.com/godotengine/godot/files/5703853/Receiver.MIRU.zip)

**Comment by fire** [comment]
Testing old issues. The gltf2 files don't have any problems. Can you revisit or close?

Today's godot engine commit is https://github.com/godotengine/godot/commit/90a1e5193366e57069951cf2703616248e5f515d
