### ISSUE TITLE
Shader node materials don't show updated normal-map data (in the viewport) when saved

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4443]
**Operating system or device:**
Win10 64 bit; 24 Gigs RAM; third-gen i7 CPU; ATI HD 7xxx GPU.

**Issue description** (what happened, and what was expected):
When changing the normal map data in a shader material (using the visual node editor). The edited data will initially show like it should in the viewport. However, when you save the material, the visuals you get in the viewport will revert back to how it looked when the editing was started (but the new data _is_ saved). The only way to really update it for good is to then exit to the projects window and reload the project in question.

**Steps to reproduce:**
Download the project file, go to its shader node setup, play around with the normal map data a little, then save the material. Instant revert in the viewport (visually at least). Exit to the projects window and re-open the project to see it updated like it should be.

**Link to minimal example project** **(optional but very welcome):**
http://www.mediafire.com/download/3mucchbbonshdbz/Terrain%282%29.zip

**Comment by MarianoGnu** [comment]
@akien-mga i belive this issue can be closed. CanvasItemMaterial have not DIFUSE builtin variable, instead COLOR should be used.

**Comment by akien-mga** [comment]
Seems to be properly updated in 2.1.5.
