### ISSUE TITLE
Trying to modify const Dictionary results in confusing error

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44443]
**Godot version:**

fb2465b

**Issue description:**

```
const a = {}

func _ready() -> void:
	a["test"] = 1
```
This results in `Cannot get index "test" from "{}".` (parse error)

If I'm not supposed to modify const Dictionary, the error should clearly say so.

**Comment by ThakeeNathees** [comment]
there was already an issue for this: #44241

**Comment by KoBeWi** [comment]
It's not the same issue. In my case it works when I do `var a = {}`

**Comment by YuriSizov** [comment]
This should be clear after https://github.com/godotengine/godot/pull/71051.
