### ISSUE TITLE
Windows build fails: cannot open include file 'netinet/in.h'

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#44448]
**Godot version:**
master b07a3f503b75831414f92d2cc6886d045eeb96fb

**OS/device including version:**
Windows 10

**Issue description:**
Windows build fails, even with clean build. Worked before #44433 was merged. cc @akien-mga 

```
C:\Users\mbr\Documents\Projects\godot\thirdparty\wslay\wslay_net.h(38): fatal error C1083: Cannot open include file: 'netinet/in.h': No such file or directory
C:\Users\mbr\Documents\Projects\godot\thirdparty\wslay\wslay_net.h(38): fatal error C1083: Cannot open include file: 'netinet/in.h': No such file or directory
scons: *** [thirdparty\wslay\wslay_net.windows.opt.tools.64.obj] Error 2
scons: *** [thirdparty\wslay\wslay_event.windows.opt.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
I can reproduce the issue with MSVC too, I think my changes made it so that the modules build now use an incomplete environment, without the relevant config to target Windows 7+ APIs, which means that these headers are not available.

I'll fix it.
