### ISSUE TITLE
Tabs in TextEdit do not get highlighted when selected

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#44450]
**Godot version:**
4.0 master 2020/12/17

**OS/device including version:**
WIN 10

**Issue description:**
Tabs do not get highlighted.
![tabs_no_highlight](https://user-images.githubusercontent.com/41730826/102477903-b1680600-40a8-11eb-96f5-ffbab5f0cf40.gif)

**Steps to reproduce:**
Try highlight tabs

**Comment by akien-mga** [comment]
Duplicate of #42656, might be fixed by #42975 if you want to test/review.

**Comment by EricEzaM** [comment]
@akien-mga No, that is RichTextLabel. This is a TextEdit.
