### ISSUE TITLE
Hard to select objects in 3D view when zoomed out

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#4445]
**Issue description** (what happened, and what was expected):
When zoomed out it's impossible to select some smaller objects. I'm not talking about 5px objects of course, they are reasonably big on screen to be selectable by user.

**Comment by reduz** [comment]
this will be rewritten in 3.0, so let's check it again by then

**Comment by reduz** [comment]
kicked to 3.1

**Comment by reduz** [comment]
I think this may have been fixed already by @JFonS 
Can anyone confirm?

**Comment by reduz** [comment]
Most likely fixed, please reopen if still reoccurs
