### ISSUE TITLE
Android ~ Adreno 506, Adreno 505 and Adreno 330

### ISSUE THREAD

**Issue by MadDogMayCry0** [godotengine/godot#44465]
UPDATE
I trye'd 3.2.4 Beta 4 and semms to this bugs has been fixed on it.

Xiaomi redmi 7
Adreno 506:
230 mesches @ 60fps
250 mesches @ 53fps

Samsung Galaxy TAB S 10.5 (T805)
Adreno 330:
41 mesches @ 60fps
50 mesches @ 49fps

Last stable release 3.2.3

Xiaomi redmi 7
Snapdragon 632 (Adreno 506)
When you use Skeletal2D and some mesch with UV
>Become bad perfomance (2 times) versus good perfomance on Adreno 330 (Adreno 506 has more power).
>Wrong texture gamma in GLSE3 mode.

Xiaomi redmi 4x
Snapdragon 439 (Adreno 505)
When you use Skeletal2D and some mesch with UV
>Become bad perfomance (2 times) versus good perfomance on Adreno 330 (Adreno 505 has more power).
>Wrong texture gamma in GLSE3 mode.

Samsung Galaxy TAB S 10.5 (T805)
Snapdragon 800 (Adreno 330)
When you use Skeletal2D and some mesch with UV
>Become wrong polygon figure (distortion) or no figure at all on GLSE2, and normal figure on GLSE3
>Hass better perfomance on GLSE3 than 506 and 505 on GLSE3 and GLSE2.

Project files
Touch/click and hold on screen to deploy the object.
[Polygon_adreno_gpu_perfomance.zip](https://github.com/godotengine/godot/files/5714779/Polygon_adreno_gpu_perfomance.zip)

**Comment by Calinou** [comment]
> When you use Skeletal2D and some Polygon with UV
> > become wrong polygon figure (distortion) on GLSE2, and normal figure on GLSE3

Skeleton2Ds should be fixed in GLES2 starting from 3.2.4beta3. Give [3.2.4beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-4) a try after making a backup of your project :slightly_smiling_face:

**Comment by MadDogMayCry0** [comment]
@Calinou 
I'll attach project files later!

**Comment by lawnjelly** [comment]
> UPDATE
> I trye'd 3.2.4 Beta 4 and semms to this bugs has been fixed on it.

Closing as the software skinning should solve.
