### ISSUE TITLE
Improve form validation in the editor plugin creation dialog

### ISSUE THREAD

**Issue by t-karcher** [godotengine/godot#44462]
**Godot version:**
v3.2.4.beta4.official

**OS/device including version:**
Windows 10 64-Bit

**Issue description:**
I followed [the official doc](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html) in a newly created project to create a plugin. After clicking "Create" in the "Create a Plugin" dialog, only the addons folder was created, but no subfolder and no files. In the debug window, there was the following error message:

    ERROR: make_dir_recursive: Method failed. Returning: err
       At: core/os/dir_access.cpp:185

**Steps to reproduce:**
1) Create a new project with default settings.
2) In Project -> Project settings -> Plugins tab -> Click "Create"
3) Fill in the required fields and confirm with "Create"

**Minimal reproduction project:**
* Any newly created, blank project.

**Comment by Calinou** [comment]
What did you fill the fields with when getting an error message? (Take a screenshot and upload it here.)

**Comment by t-karcher** [comment]
Ok, this is embarrassing. :-( I read the hint `"my_plugin" --> res://addons/my_plugin` the wrong way round and entered this:

![image](https://user-images.githubusercontent.com/22897030/102523735-3d256680-4098-11eb-8f3a-f19cfaacd39b.png)

Only after rereading the docs I noticed that just entering `my_plugin` and `my_plugin.gd` would have been enough. And with those values it works.

So yes, creation works, but validation of user input could be improved.

**Comment by Calinou** [comment]
> So yes, creation works, but validation of user input could be improved.

I opened a pull request for that: https://github.com/godotengine/godot/pull/36677

**Comment by KoBeWi** [comment]
Resolved by #41788
