### ISSUE TITLE
Can't set escape as a key in InputMap

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#44461]
**Godot version:**
Master 68117f5e75944cfd6f8ad1534a15c334e7ed5e91

**OS/device including version:**
Windows 10

**Issue description:**
It's not possible to set `escape` as a key binding in `InputMap`, as pressing it immediately closes the prompt.

There's no workaround, except for setting the keycode by hand in the project file.

**Steps to reproduce:**
1. Open any project
2. Open Project Settings
3. Go to Input Map tab
4. Edit an existing key mapping using the pencil icon
5. Press `escape`
6. Observe the popup closes without setting the key

**Minimal reproduction project:**
n/a

**Comment by EricEzaM** [comment]
Fixed by #44181 if it gets merged
