### ISSUE TITLE
Lock object for 3D

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#4447]
**Issue description** (what happened, and what was expected):
In 2D there is an option to Lock objects from selection, something like that would be useful for 3D as well.

**Comment by akien-mga** [comment]
There was an old pull request for that, but it had merge conflicts and no answer from the OP nor any interested contributor, so I archived it: #2251

You could try to rebase it on top of the current master branch and see how it goes :)

**Comment by ZX-WT** [comment]
when will we have this?

**Comment by n-pigeon** [comment]
@akien-mga @ZX-WT 
I will look into it then :) But first I will try to finish Scale Gizmo PR.
I'm noob C++ user and coder overall so bare with my speed :D I can't promise any ETA.

**Comment by n-pigeon** [comment]
PR Implementing this: #12359

**Comment by Calinou** [comment]
Since the pull request implementing the requested feature was merged, this issue can now be closed.
