### ISSUE TITLE
StreamPeerBuffer.get_utf8_string() doesn't handle null characters (\u0000) correctly

### ISSUE THREAD

**Issue by Demindiro** [godotengine/godot#44478]
Related: #44477

**Godot version:**
`4.0.dev.custom_build.5332d212f`

**OS/device including version:**
`Linux pc 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`

**Issue description:**
[`StreamPeerBuffer.get_utf8_string()`][1] doesn't include any characters after the null character (`\u0000`).

**Steps to reproduce:**
```gdscript
extends MainLoop


func _idle(_delta):
	var string := "aaaa\u0000bbbb"
	print("%d: '%s'" % [len(string), string])
	var buffer := StreamPeerBuffer.new()
	buffer.put_utf8_string(string)
	# Expecting 13 because 32 bit integer + 9 characters
	print("%d: %s" % [len(buffer.data_array), var2str(buffer.data_array)])
	buffer.seek(0)
	string = buffer.get_utf8_string()
	print("%d: '%s'" % [len(string), string])
	return true
```

Output:
```
9: 'aaaa
13: PackedByteArray( 9, 0, 0, 0, 97, 97, 97, 97, 0, 98, 98, 98, 98 )
4: 'aaaa'
```

**Minimal reproduction project:**
See above.

[1]: https://docs.godotengine.org/en/stable/classes/class_streampeer.html#class-streampeer-method-get-utf8-string

**Comment by akien-mga** [comment]
Fixed by #62735.

Output from the MRP:
```
  Unicode parsing error, some characters were replaced with spaces: NUL character
8: 'aaaabbbb'
12: PackedByteArray(8, 0, 0, 0, 97, 97, 97, 97, 98, 98, 98, 98)
8: 'aaaabbbb'
```
