### ISSUE TITLE
Autocompletion is missing signals

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44479]
**Godot version:**

5332d21

**Issue description:**

Given that signals are first-class members now, they should appear in the autocompletion. They don't right now:
![J1Ntmeslwi](https://user-images.githubusercontent.com/2223172/102559976-6f06ef00-40d1-11eb-837b-66598a4edf58.gif)

EDIT:
Not sure if it always was like that, but in b0e9371 the autocompletion includes custom signals. It doesn't suggest the built-in one though (i.e. from base class).

**Comment by akien-mga** [comment]
Still valid in current `master` branch.

**Comment by Chaosus** [comment]
Probably related to https://github.com/godotengine/godot/issues/54589
