### ISSUE TITLE
Attempted to use the same texture in framebuffer attachment error

### ISSUE THREAD

**Issue by UltraWelfare** [godotengine/godot#44473]
**Godot version:**
v4.0.dev.custom_build.2c0d1c3b9

**OS/device including version:**
OS: EndeavourOS (5.9.13-zen1-1-zen)
GPU: Intel UHD 620 (with integrated: Radeon 530)
Backend: X11 / Vulkan

**Issue description:**
Upon opening any new project (either creating one or loading one), the Output tab (and the terminal, if launching godot from there) continuously shows this message:
`ERROR: Attempted to use the same texture in framebuffer attachment and a uniform set, this is not allowed.`

The terminal outputs an extra line:
`at: draw_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:6176)`

**Steps to reproduce:**
1. Create a new project.
2. Look at the output tab (or the terminal)

**Minimal reproduction project:**
Not needed as it happens with the creation of any new project.

**Comment by clayjohn** [comment]
I spent some time tracking this down tonight, but haven't gotten anywhere yet. I'm recording notes below to help myself later or someone else.

The issue stems from binding the depth and normal textures for reading during any of the three main passes (prepass, opaque, alpha).

All three passes share the same uniform set which is declared here

https://github.com/godotengine/godot/blob/5332d212f9bc0932544156d1fa1f568bf4ae24a8/servers/rendering/renderer_rd/renderer_scene_render_forward.cpp#L1841

Specifically it comes from binding the ``depth`` and ``normal_roughness`` textures in ``_setup_render_pass_uniform_set``:

https://github.com/godotengine/godot/blob/5332d212f9bc0932544156d1fa1f568bf4ae24a8/servers/rendering/renderer_rd/renderer_scene_render_forward.cpp#L2426

https://github.com/godotengine/godot/blob/5332d212f9bc0932544156d1fa1f568bf4ae24a8/servers/rendering/renderer_rd/renderer_scene_render_forward.cpp#L2503-L2510

https://github.com/godotengine/godot/blob/5332d212f9bc0932544156d1fa1f568bf4ae24a8/servers/rendering/renderer_rd/renderer_scene_render_forward.cpp#L2521-L2528

The depth prepass binds the ``depth`` and the ``normal_roughness`` textures as framebuffers, so the issue makes sense. But the error occurs on the opaque and alpha pass as well. It is on this point that I need to investigate further.

**Comment by jure** [comment]
Just a data point over here: the error, still spammed, now says "ERROR: Attempted to use the same texture in framebuffer attachment and a uniform (set: 1, binding: 6), this is not allowed."

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/44523.

**Comment by reduz** [comment]
@Calinou #44523 seems completely unrelated, so feel free to keep this closed

**Comment by akien-mga** [comment]
@reduz Read again, there's still very closely related error spam: https://github.com/godotengine/godot/issues/44473#issuecomment-748490674

**Comment by Drachenbauer** [comment]
when i apply the texture, that a SubViewport outputs as the texture of a Sprite2d, it spams an error in the debugger:
draw_list_bind_uniform_set: Attempted to use the same texture in framebuffer attachment and a uniform (set: 3, binding: 0), this is not allowed.

**Comment by clayjohn** [comment]
> when i apply the texture, that a SubViewport outputs as the texture of a Sprite2d, it spams an error in the debugger: draw_list_bind_uniform_set: Attempted to use the same texture in framebuffer attachment and a uniform (set: 3, binding: 0), this is not allowed.

Yes, that isn't allowed. You can't read from the texture that you are writing to
