### ISSUE TITLE
Context-based autocompletion no longer works

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44480]
**Godot version:**

5332d21

**Issue description:**

Title. This includes e.g. animation names for `play` or method list for `connect` and probably other things.

EDIT:
Also, not sure if it's the same bug, but when you do e.g. `$AnimationPlayer` (pointing to a valid node), it doesn't check the type correctly and suggests only Node members.

**Comment by KoBeWi** [comment]
Seems like animation names are working, but connect still doesn't suggest method names (both from `Signal` and from `Object`).

The issue mentioned in EDIT is handled by some other issue AFAIK.

**Comment by KoBeWi** [comment]
Ok so the `$AnimationPlayer` issue is fixed and all seems to be in order. Only missing are the method names I mentioned above, but it's caused by Callable changes. I think the issue has less priority now.

**Comment by dalexeev** [comment]
CC @HolonProduction @ajreckof
