### ISSUE TITLE
Better bounding box select in 3D

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#4448]
**Issue description** (what happened, and what was expected):
Awesome feature of Select Mode (Q) is that it can do bounding box selection, helps with selecting multiple or small objects, but it doesn't work if there are other objects behind object we want to select.
It then selects that "behind object" and because current nature of this tool automatically transforms it to the movement of the mouse, so there is no way to use bounding box selection in most scenes.

I would suggest to separate selection from multi transform tool and make it more like ON/OFF mode for transform gizmos. It would also help if user wants, for example, only translate objects that he selects, or only select object without seeing any transform widgets on the screen that can stand in the way sometimes.
I can elaborate that idea (visual help what I have in mind?) if that's not enough.

**Comment by akien-mga** [comment]
There have been many improvements to the 3D selection in the master branch (especially by @JFonS), so I think this might be addressed somehow.

If not, I'd suggest to open a new issue to discuss how to improve the current system, as it would have better visibility.
