### ISSUE TITLE
Collision shapes which are changed or created at run time are not shown by debugging system

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4449]
**Operating system or device:**
Any

**Issue description** (what happened, and what was expected):
Collision shapes which are changed or created at run time are not
shown by collision debugging system (visible collisions).
This is annoying as they are needed to be debugged too.

**Steps to reproduce:**
Whatever way create some bodies, collisions, modify them in script, enable
collision debugging and see

**Comment by reduz** [comment]
need to break compatibility to fix this, so it will happen in 3.0

**Comment by reduz** [comment]
happened in 3.0, closing
