### ISSUE TITLE
Strange and confusing check tile in position

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#44491]
**Godot version:**

3.2.4 beta 4 mono

**OS/device including version:**

win10 64

**Issue description:**

To consult the index of a tile in a position, use "GetCell (X, Y)" from the tilemap node.
But if your tiles belong to an atlas then you should use "GetCellAutotileCoord (X, Y)".
That's confusing, in any case a method should be called or exist with a name like "GetAtlasCell (X, Y)".

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This should probably be discussed in a [proposal](https://github.com/godotengine/godot-proposals) rather than a bug report.

**Comment by groud** [comment]
Closing as this enhancement request is not more needed on master.
