### ISSUE TITLE
Loading an animation on AnimationPlayer on 3d model doesn't work

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#44508]
**Godot version:** 3.2.3

**OS/device including version:** Windows 10

**Issue description:**

new animations loaded on AnimationPlayer nodes on 3d models do not play

**Steps to reproduce:**
Video attached

import a 3d model
import another one with the same skeleton and a new animation
go to the animation player on the new model
save the new animation to the project with either .anim or .tres file extension
go to the first 3d model's AnimationPlayer node
load the new animation
it will not play

**Minimal reproduction project:**

[AnimationLoadNotWorking.zip](https://github.com/godotengine/godot/files/5718556/AnimationLoadNotWorking.zip)

https://user-images.githubusercontent.com/7292421/102673198-60abe800-4150-11eb-9052-11ae6053dd0e.mp4

**Comment by nonunknown** [comment]
related to #44550

**Comment by Calinou** [comment]
@Miziziziz Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

**Comment by efraim301** [comment]
I am having this exact issue in Godot 3.5.1.
