### ISSUE TITLE
Building engine with mono enabled cannot find MSBuild.exe

### ISSUE THREAD

**Issue by Avantir-Chaosfire** [godotengine/godot#44504]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
Attempting to build the engine from source with mono. Generated the mono glue, now attempting to rebuild the engine with the generated mono glue. Getting the error: "MsBuild.exe does not exist at 'C:\Program Files\Mono\lib\mono\msbuild\15.0\bin'."

It is correct that MsBuild.exe does not exist there. There is an MsBuild.dll at that location, and many other things besides, but no MsBuild.exe. From other posts I've found, I think it should be looking in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin, where there IS an MSBuild.exe. I'm not sure why it's insisting on looking in the mono directory instead. Is this a bug? Is there a way for me to fix this?

Full log attached.
[message.txt](https://github.com/godotengine/godot/files/5717654/message.txt)

**Comment by Calinou** [comment]
@Avantir-Chaosfire Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

**Comment by Avantir-Chaosfire** [comment]
Cannot reproduce
