### ISSUE TITLE
AnimationPlayer method call bug

### ISSUE THREAD

**Issue by DanesZalor** [godotengine/godot#44513]
So this is the Node with the scripts i made
![image](https://user-images.githubusercontent.com/48168267/102686833-34ae6680-4225-11eb-8029-2c68073fdcf7.png)

And these are the only methods that can be called via animation player
![image](https://user-images.githubusercontent.com/48168267/102686843-4859cd00-4225-11eb-9aaa-a62f46648980.png)

Is this a bug? or am I just missing something like a format?

**Comment by akien-mga** [comment]
We have an issue template for a reason, there's nothing we can do to answer this or help you with so little details.

**Comment by DanesZalor** [comment]
nvm. i fixed the issue by restarting the engine.
