### ISSUE TITLE
Export variables in C# don't work

### ISSUE THREAD

**Issue by suleyth** [godotengine/godot#44516]
I've tried looking through all of the issues related to this and even asked for help in the discord but those issues didn't seem to fit with my case. So I'm making a new one. It's not a duplicate, the situation is a little different...

**Godot version:**
3.2.3 Mono

**OS/device including version:**
Windows 10 

**Issue description:**
C# works properly, it builds with no issue and the script *is* attached to the node, since `GD.Print` does print correctly. However, simple `[Export]` variables just plain old do not show in the editor. It's not related to building the project or resetting the engine, I've done that a hundred times with both the build button, using `dotnet build` specifically and even `msbuild` on the project solution myself. Restarting the project after and before building again doesn't work either. I've confirmed I have downloaded the proper framework, and the project builds correctly, there *is* a DLL on `.mono\temp\bin\Debug`

Since no one else seems to be having this specifically, I'm not very sure if this is an issue with Godot, C#, my computer... But reinstalling Godot and .NET didn't fix the issue. So I'm not really sure what's wrong now.

**Steps to reproduce:**
1. Create a new project
2. Attach a C# script to anything
3. Put any `[Export]` variable there
4. It will not show up no matter what

**Minimal reproduction project:**
Something as basic as this project doesn't work for me. Is there maybe something wrong with it? Thank you.

[TestyThing.zip](https://github.com/godotengine/godot/files/5719371/TestyThing.zip)

**Comment by MrZak-dev** [comment]
![image](https://user-images.githubusercontent.com/27586088/102692144-7093fc80-4222-11eb-884a-4ee94e2511a7.png)

in my case it is working !

![image](https://user-images.githubusercontent.com/27586088/102692179-d1bbd000-4222-11eb-87b6-0d07ce381e3b.png)

it works in your reproduction project also.

**Comment by suleyth** [comment]
Yeah, figured it wasn't really a Godot problem, but I can't for the life of me figure out what could be wrong with my setup... I'll keep this issue open for a bit in case anyone may have any clues or pointers

**Comment by MrZak-dev** [comment]
@Calinou , Please change labels

**Comment by suleyth** [comment]
More things I've tried:
1. Completely reinstall Godot removing all configs
2. Reinstall .NET Framework and the VS Build Tools

No results. I've seen in the Mono logs that it has some isssues loading assemblies, but I don't think it has a correlation.
[2020_12_23 16.42.14 (17324).txt](https://github.com/godotengine/godot/files/5735994/2020_12_23.16.42.14.17324.txt)

**Comment by MrZak-dev** [comment]
Try to use a different Mono version , and change the Build tool from `Editor > Mono > Builds`

**Comment by suleyth** [comment]
*sigh* I installed the Mono SDK, yet building with Mono throws this:
```
Project "Testy Thing.sln" (Restore target(s)):
	Message: Building solution configuration "Debug|Any CPU".
	Project "Testy Thing.csproj" (Restore target(s)):
		D:\Dev\Code\Godot\TestyThing\Testy Thing.csproj(0,0): error MSB4237: The SDK resolver type "DotNetMSBuildSdkResolver" failed to load. The type initializer for 'Microsoft.DotNet.MSBuildSdkResolver.VSSettings' threw an exception. [D:\Dev\Code\Godot\TestyThing\Testy Thing.csproj]
	Done building project "Testy Thing.csproj" -- FAILED.
Done building project "Testy Thing.sln" -- FAILED.
```
Building with VS Build Tools works, but export variables still don't appear.

Building with JetBrains Rider only shows "The build method threw an exception." even if I have JetBrains Rider properly installed. The log is:
```
Project "Testy Thing.sln" (Restore target(s)):
	Message: Building solution configuration "Debug|Any CPU".
	Project "Testy Thing.csproj" (_IsProjectRestoreSupported target(s)):
	Done building project "Testy Thing.csproj".
	NuGetMessageTask: Determining projects to restore...
	Project "Testy Thing.csproj" (_GenerateRestoreProjectPathWalk target(s)):
	Done building project "Testy Thing.csproj".
	Project "Testy Thing.csproj" (_IsProjectRestoreSupported target(s)):
	Done building project "Testy Thing.csproj".
	Project "Testy Thing.csproj" (_GenerateRestoreGraphProjectEntry target(s)):
	Done building project "Testy Thing.csproj".
	Project "Testy Thing.csproj" (_GenerateProjectRestoreGraph target(s)):
	Done building project "Testy Thing.csproj".
	RestoreTask: Committing restore...
	RestoreTask: Assets file has not changed. Skipping assets file writing. Path: D:\Dev\Code\Godot\TestyThing\.mono\temp\obj\project.assets.json
	RestoreTask: Restored D:\Dev\Code\Godot\TestyThing\Testy Thing.csproj (in 56 ms).
	RestoreTask: 
	RestoreTask: NuGet Config files used:
	RestoreTask:     C:\Users\Suleyth\AppData\Roaming\NuGet\NuGet.Config
	RestoreTask: 
	RestoreTask: Feeds used:
	RestoreTask:     https://api.nuget.org/v3/index.json
	RestoreTask: All projects are up-to-date for restore.
Done building project "Testy Thing.sln".
Project "Testy Thing.sln" (Build target(s)):
	Message: Building solution configuration "Debug|Any CPU".
	Project "Testy Thing.csproj" (default targets):
		Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
		Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
		Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
		Message: Testy Thing -> D:\Dev\Code\Godot\TestyThing\.mono\temp\bin\Debug\Testy Thing.dll
	Done building project "Testy Thing.csproj".
Done building project "Testy Thing.sln".
```
After some hassle, I managed to get the test project to build with dotnet CLI without errors - Still no export variables.

Given that they didn't show up with two different methods, I'm willing to say the error is probably not there...
