### ISSUE TITLE
Strange rendering issues in an HTML5 exported game. Can someone please help me figure out how to debug/fix them?

### ISSUE THREAD

**Issue by lumenwrites** [godotengine/godot#44520]
**Godot version:**
3.2.3

**OS/device including version:**
Mac OS Catalina, GLES3, HTML5 exported game.

**Issue description:**
Hey guys, can you please help me to debug an issue?
I'm trying to export my game for HTML5.

Here's how it looks like when I'm running it in Godot, or when I'm running it in Chrome on Linux:
https://i.imgur.com/dxSt9mQ.png

Here's how it looks like when I'm opening the same HTML5 page in Chrome on Mac:
https://i.imgur.com/tKmaide.png

Here's the HTML5 exported game:
http://lets-roll.netlify.com/

Here's this game on GOTM:
https://gotm.io/godotacademy/lets-roll

Here are the project files:
https://github.com/lumenwrites/lets-roll

When I'm trying to export my other game, it works just fine:
https://gotm.io/godotacademy/tavern

So the issue is specific to the Let's Roll game, and it appears specifically on Macs.
Can someone more experienced please help to figure out what I can try to resolve the issue?

**Comment by Calinou** [comment]
Are you using the GLES2 or GLESS3 renderer? Make sure to use GLES2 when targeting HTML5 as it's more compatible.

**Comment by akien-mga** [comment]
Safari doesn't support WebGL 2 yet in the stable version AFAIK, so it might be that your game falls back to GLES2 / WebGL 1 which can look different for some features.

**Comment by Calinou** [comment]
@akien-mga OP is using Chrome on macOS, not Safari.

**Comment by Calinou** [comment]
Closing per akien-mga's comment. Please comment if you can still reproduce this after switching to the GLES2/WebGL 1.0 renderer.
