### ISSUE TITLE
Export ios with undefined symbol errors

### ISSUE THREAD

**Issue by blackbeaf** [godotengine/godot#44522]
**Godot version:**

3.2.3 mono official 

**OS/device including version:**

Macos 

**Issue description:**

The project works fine and exporting windows + android are ok but report 100 errors when exporting ios. See picture below.

output log:
Godot Engine v3.2.3.stable.mono.official (c) 2007-2020 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started ---
Switch Scene Tab
Static library: libgodot.iphone.debug.fat.a
Unzipping...
READ: data.pck
READ: godot_ios/
READ: godot_ios/godot_ios-Info.plist
ADDING: test/test-Info.plist size: 1937
READ: godot_ios/export_options.plist
ADDING: test/export_options.plist size: 458
READ: godot_ios/dummy.cpp
ADDING: test/dummy.cpp size: 2381
READ: godot_ios/en.lproj/
READ: godot_ios/en.lproj/InfoPlist.strings
ADDING: test/en.lproj/InfoPlist.strings size: 45
Creating /Users/mac/Desktop/isometric/ios/test/en.lproj
READ: godot_ios/godot_ios.entitlements
ADDING: test/test.entitlements size: 190
READ: godot_ios/Launch Screen.storyboard
ADDING: test/Launch Screen.storyboard size: 2987
READ: godot_ios/Images.xcassets/
READ: godot_ios/Images.xcassets/SplashImage.imageset/
READ: godot_ios/Images.xcassets/SplashImage.imageset/Contents.json
ADDING: test/Images.xcassets/SplashImage.imageset/Contents.json size: 343
Creating /Users/mac/Desktop/isometric/ios/test/Images.xcassets/SplashImage.imageset
READ: godot_ios/Images.xcassets/SplashImage.imageset/splash@2x.png
ADDING: test/Images.xcassets/SplashImage.imageset/splash@2x.png size: 21443
READ: godot_ios/Images.xcassets/SplashImage.imageset/splash@3x.png
ADDING: test/Images.xcassets/SplashImage.imageset/splash@3x.png size: 21443
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-480h@2x.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-480h@2x.png size: 347
Creating /Users/mac/Desktop/isometric/ios/test/Images.xcassets/LaunchImage.launchimage
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-568h@2x.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-568h@2x.png size: 395
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-667h@2x.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-667h@2x.png size: 514
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Landscape-736h@3x.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-Landscape-736h@3x.png size: 1506
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Landscape-X.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-Landscape-X.png size: 1403
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Contents.json
ADDING: test/Images.xcassets/LaunchImage.launchimage/Contents.json size: 2567
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Landscape.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-Landscape.png size: 466
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Landscape@2x.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-Landscape@2x.png size: 1746
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Portrait-736h@3x.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-Portrait-736h@3x.png size: 1429
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Portrait-X.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-Portrait-X.png size: 1426
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Portrait.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-Portrait.png size: 421
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Portrait@2x.png
ADDING: test/Images.xcassets/LaunchImage.launchimage/Default-Portrait@2x.png size: 1615
READ: godot_ios/dylibs/
READ: godot_ios/dylibs/empty
ADDING: test/dylibs/empty size: 42
Creating /Users/mac/Desktop/isometric/ios/test/dylibs
READ: godot_ios.xcodeproj/
READ: godot_ios.xcodeproj/project.pbxproj
ADDING: test.xcodeproj/project.pbxproj size: 14667
Creating /Users/mac/Desktop/isometric/ios/test.xcodeproj
READ: godot_ios.xcodeproj/project.xcworkspace/
READ: godot_ios.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ADDING: test.xcodeproj/project.xcworkspace/contents.xcworkspacedata size: 150
Creating /Users/mac/Desktop/isometric/ios/test.xcodeproj/project.xcworkspace
READ: godot_ios.xcodeproj/xcshareddata/
READ: godot_ios.xcodeproj/xcshareddata/xcschemes/
READ: godot_ios.xcodeproj/xcshareddata/xcschemes/godot_ios.xcscheme
ADDING: test.xcodeproj/xcshareddata/xcschemes/test.xcscheme size: 3386
Creating /Users/mac/Desktop/isometric/ios/test.xcodeproj/xcshareddata/xcschemes
READ: libgodot_arkit_module.iphone.debug.fat.a
READ: libgodot_arkit_module.iphone.release.fat.a
READ: libgodot_camera_module.iphone.debug.fat.a
READ: libgodot_camera_module.iphone.release.fat.a
READ: libgodot.iphone.debug.fat.a
ADDING: test.a size: 139179920
READ: libgodot.iphone.release.fat.a
Using Launch Images
Exporting additional assets

**Steps to reproduce:**
I tried to create new empty project on Macos, also the same errors.

**Minimal reproduction project:**

![err](https://user-images.githubusercontent.com/25684578/102692769-85878480-4250-11eb-82ca-e12c5c062ee2.jpg)

**Comment by naithar** [comment]
@blackbeaf is it still an issue? Adding any `C#` script should fix missing symbols.

**Comment by blackbeaf** [comment]
@naithar   Hi, I tried(add a empty c# script) but got another error. I'm not familiar with ios development. Do I have to config something manually?

--- Debugging process started ---
Godot Engine v3.2.3.stable.mono.official - https://godotengine.org
OpenGL ES 2.0 Renderer: Apple Software Renderer
OpenGL ES 2.0 Batching: ON
 
--- Debugging process stopped ---
 Cannot load assembly (refonly): 'Xamarin.iOS'.
 Cannot load one of the dependencies for the assembly: 'System.Net.Http'.
 Cannot load one of the dependencies for the assembly: 'netstandard'.
 Cannot load one of the dependencies for the assembly: 'GodotSharp'.
Static library: libgodot.iphone.debug.fat.a
Unzipping...
READ: data.pck
READ: godot_ios/
READ: godot_ios/godot_ios-Info.plist
ADDING: test/test-Info.plist size: 1937

**Comment by naithar** [comment]
@blackbeaf no, I think you shouldn’t.

This error happens when you export Godot project?  
But have you tried running an exported Xcode project after this - adding C# script should have fixed missing symbols and you should be able to compile and run it in Xcode.

**Comment by blackbeaf** [comment]
@naithar  Thank you!!!!! I succeed. I stopped building ios since I saw those error lines last time.  Those errors seem to have no effect.
