### ISSUE TITLE
After Fixing Error Spam on wrong Attachment, I Got this Error For Creating Mesh Instance Node, Setting Mesh, etc

### ISSUE THREAD

**Issue by DivijManik** [godotengine/godot#44523]
**Godot version:**

  Godot Engine v4.0.dev.custom_build

**OS/device including version:**

  Mac OS Big Sur,
  Version 11.0.1
  
   Intel core i7,
   Intel UHD

**Issue description:**

I followed #44517 for fixing  "Attempted to use the same texture in framebuffer attachment error" Error

  Now I'm getting these Errors in my Output When I create a MeshInstance3D as a Child Node to our Root and Set its Mesh-->
  
  Set mesh
    platform/osx/display_server_osx.mm:2506 - Condition "!windows.has(p_window)" is true. Returning: -1
  Set mesh
    ./servers/rendering/renderer_storage.h:74 - Condition "!F" is true. Continuing.
  
  I get the first error for most of the things related to the components of the MeshInstance3D such as Rotation, Setting Mesh, Set Material.
  
  -- 
  
  ***Materials and Skybox is still not rendering in My 3D Scene
  Everything is just Black in my Scene.***

**ERROR Files:**
   platform/osx/display_server_osx.mm:2506 
  ./servers/rendering/renderer_storage.h:74

**Steps to reproduce:**
1) Starting a new project
2) New Scene Root
3) Now if I make anything (New MeshInstance3D Node, Setting Mesh, Set Material, Rotating Node, etc) Will give the Error.

**Comment by RevoluPowered** [comment]
Getting this in FBX and GLTF2 on reimporting a mesh :) without opening the scene

**Comment by RevoluPowered** [comment]
locally changed this to a continue without the message, I think possibly this could be expected since the resource wasn't loaded but this is entirely a guess.

**Comment by RevoluPowered** [comment]
The reason this happens at the re-import time and spams is because when you re-import a file it hasn't actually opened the scene. 

this happens with FBX/GLTF and probably Collada too.

To reproduce:
- re-import fbx file don't open it

in my local branch changing to continue is perfectly safe to do

**Comment by Calinou** [comment]
@DivijManik Can you (or anyone else) still reproduce this bug in [Godot 4.0alpha1](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
