### ISSUE TITLE
revert button does not consistently show up in instanced children properties if root is Node (and not Node2D)

### ISSUE THREAD

**Issue by snaar** [godotengine/godot#44537]
**Godot version:** v3.2.3.stable.official

**Issue description:**
Consider scene that consists of a root node that has single child that is an instance of another scene. With "editable children" enabled, there is single child - Sprite. Here is how it looks:
![image](https://user-images.githubusercontent.com/602439/102702842-6c250f00-4235-11eb-985e-f7f46a65526f.png)

If you change properties of that Sprite, you expect revert button to appear once you change a property. "Position" has revert button here:
![image](https://user-images.githubusercontent.com/602439/102702878-a8f10600-4235-11eb-874d-a9ba0458e3d3.png)

You also expect that if you change Rotation Degree or Scale they also will get revert buttons. However, this does _not_ happen if "main" scene has type Node, i.e. `[node name="main" type="Node"]` - this is how it is in attached project.

If you change the type to Node2D, i.e. `[node name="main" type="Node2D"]`, and reload the project, then the buttons apprear as expected:
![image](https://user-images.githubusercontent.com/602439/102702913-0d13ca00-4236-11eb-8d57-8009ec4b0326.png)

I'm surprised that presense of revert button is affected by what type the root node is.

**Minimal reproduction project:**
[revert.zip](https://github.com/godotengine/godot/files/5720359/revert.zip)

**Comment by KoBeWi** [comment]
Does it still happen in [3.2.4 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-4)? There was a similar issue that got fixed.

**Comment by snaar** [comment]
Confirming fixed in v3.2.4-beta4. Thank you!
