### ISSUE TITLE
Vulkan: Screen Space Reflection not working

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#44539]
**Godot version:**
Godot 4.0 Build bd0dc4d4d

**OS/device including version:**
MX Linux (Debian Based)
Nvidia GT 1030

**Issue description:**
SS reflection not working  properly

**Steps to reproduce:**
Create a simple scene with some meshes
Add world environment
Add sky
Add SS reflection.

Weird glitch appear

![ssreflection](https://user-images.githubusercontent.com/1168582/102703485-29bbfc00-424e-11eb-9052-942eb9831891.gif)

**Comment by Calinou** [comment]
SSR in Vulkan has been broken a for a few months now (since the introduction of SDFGI or so).

**Comment by WattanaGaming** [comment]
SSR and VL fog straight up does nothing but kill my FPS at least with the unofficial builds

**Comment by Calinou** [comment]
I bisected this to commit 201d606b3d348c3287f3d57d25e6eced298c2df5. This confirms my initial guess: https://github.com/godotengine/godot/issues/44539#issuecomment-748614218

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/50144. (See also https://github.com/godotengine/godot/issues/50151.)
