### ISSUE TITLE
Launching godot 4.0 (master) with mono breaks later godot+mono build attempts

### ISSUE THREAD

**Issue by eddsanity** [godotengine/godot#44532]
**Godot version:**
4.0/master

**OS/device including version:**
Windows 10 x64

**Issue description:**
Following the build instructions to build Godot with mono [from the godot documentation](https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html), I ran into a problem where building the engine for the first time and rebuilding the project without having ever ran the godot-mono binary worked fine. Running `godot.windows.tools.64.mono.exe` causes all attempts to build godot-mono to fail, and it is failing specifically **because of NuGet**.

**Steps to reproduce:**
1- run `scons -j12 platform=windows tools=yes module_mono_enabled=yes mono_glue=no`
2- run `./godot.windows.tools.64.mono.exe --generate-mono-glue modules/mono/glue`
3- run `scons -j12 platform=windows tools=yes module_mono_enabled=yes mono_glue=yes`
4- run `godot/bin/godot.windows.tools.64.mono.exe`
5- make or select a project (going past the project selection pop-up is important)
6- try to rebuild project by running `scons -j12 platform=windows tools=yes module_mono_enabled=yes mono_glue=yes`

Up until step 5, everything is fine.

Now, when trying to rebuild, scons fails saying

> scons: *** [bin\GodotSharp\Tools\nupkgs\Godot.NET.Sdk.4.0.0-dev3.nupkg] RuntimeError : 'msbuild' exited with error code: 1

and msbuild fails because

> C:\forks\godot\modules\mono\editor\Godot.NET.Sdk\Godot.NET.Sdk\Godot.NET.Sdk.csproj : error MSB4236: The SDK 'Microsoft.Build.NoTargets/2.0.1' specified could not be found.

And a couple dozen other errors that are probably a result of this one, which could be found [in this pastebin](https://pastebin.com/pZEjx5yT).

**Possible cause:**
I kept trying to fix this locally, and eventually, I found the issue to be that the godot-mono executable modifies `AppData/roaming/NuGet/nuget.config` and this modification is breaking the build. Whenever it adds it, I manually remove it and the build is successful. My guess is that it is trying to make NuGet use some offline fallback folder, but upon searching for the referenced folder, I found nothing.

My `nuget.config` file before/after building godot with mono and before **ever** running godot with mono (builds successfully):
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

My `nuget.config` file after launching `godot/bin/godot.windows.tools.64.mono.exe` (build fails)
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <fallbackPackageFolders>
    <add key="Godot Offline Packages" value="C:\Users\Eyad\AppData\Roaming/Godot/mono\GodotNuGetFallbackFolder" />
  </fallbackPackageFolders>
</configuration>
```
I looked for the `GodotNuGetFallbackFolder` and I couldn't find it anywhere on my computer. It is never generated, even though it gets added in the `nuget.config` file every time I run `godot/bin/godot.windows.tools.64.mono.exe`.
I am not very familiar with nuget (I don't use it at all) so I don't entirely understand what's happening as this `fallbackPackageFolders` clause is added, **but I am certain its addition is what's breaking my build as manually removing it (with a text editor) allows scons to build successfully again.**

**Comment by eddsanity** [comment]
Update:
I managed to narrow down the failure to this command: `dotnet.exe msbuild .\modules\mono\editor\Godot.NET.Sdk\Godot.NET.Sdk.sln /restore /t:Build /p:Configuration=Release /p:GodotPlatform=windows`.
The command fails when `AppData/Roaming/Godot/mono/GodotNuGetFallbackFolder` doesn't exist, succeeds otherwise.
The problem is that the folder `GodotNuGetFallbackFolder` isn't created automatically, for some reason. What could be blocking the creation of this directory?

**Comment by neikeq** [comment]
I think what is happening is that Godot adds the directory to `nuget,config` when launched, but doesn't actually create the directory until a game build is triggered. Can you confirm if that's the case?

**Comment by eddsanity** [comment]
> 
> 
> I think what is happening is that Godot adds the directory to `nuget.config` when launched, but doesn't actually create the directory until a game build is triggered. Can you confirm if that's the case?

Yes, actually. I can confirm that Godot adds the directory to `nuget.config` when launched and I can confirm that the directory is not created until a game build is triggered. I just tried it out with a clean reproduction of the issue using the `InterpolatedCamera3D Demo` template project for the mono build.

**Comment by castroclucas** [comment]
I got the same issue on Linux. Simple workaround was `mkdir /home/user/.local/share/godot/mono/GodotNuGetFallbackFolder`.

Somehow, Godot isn't creating this Fallback folder when compiling for the first time.

**Comment by eddsanity** [comment]
Any updates on this?

**Comment by 31** [comment]
> This issue is present in the _3.x_ branch as well.

Godot 4.0 modifies the *user/global* NuGet.config, so if you try to use Godot 4.0 and then e.g. switch back to Godot 3.3 and delete `%appdata%\Godot` to try to get a fresh start, you actually hit this issue instead. (Even when you build a Godot 3.3 project. But, 3.3 doesn't know how to create this directory, so your build is broken forever!)

I think Godot should instead put a NuGet.config into the project directory to specify the fallback folder. At the very least, it would make it a little more obvious what's going wrong and avoid breaking `dotnet build` across the whole machine.

**Comment by 31** [comment]
> I think Godot should instead put a NuGet.config into the project directory to specify the fallback folder.

After a few minutes of reflection... I suppose the problem with this is that NuGet.config files are typically checked into Git repositories, but this path is specific to a certain machine/user because it goes into e.g. `appdata`, so it shouldn't be checked in. Is that why the global NuGet.config is being used (despite the danger)?

**Comment by Bian-Sh** [comment]
run Godot_v4.0-alpha16_mono_win64.exe  once，this issue make me confused  a long time , i can not even compile my program。
create folder named mono 、GodotNuGetFallbackFolder manually solve my problem.
