### ISSUE TITLE
Vulkan: Godot crash on startup

### ISSUE THREAD

**Issue by theoniko** [godotengine/godot#44548]
**Godot version:**
Godot Engine v4.0.dev.custom_build.e9d12f9e4

**OS/device including version:**
Windows 10
NVIDIA GeForce 940MX

**Issue description:**
Godot starts but after some seconds crashes. Terminal reports the following

> Unicode parsing error: invalid skip at 1. Is the string valid UTF-8?
> Unicode parsing error: invalid skip at 0. Is the string valid UTF-8?
> Unicode parsing error: invalid skip at 2. Is the string valid UTF-8?
> Unicode parsing error: invalid skip at 0. Is the string valid UTF-8?
> early out of data
> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] vk_optimusGetInstanceProcAddr
> [1] vk_optimusGetInstanceProcAddr
> [2] VulkanContext::prepare_buffers (c:\godot\drivers\vulkan\vulkan_context.cpp:1221)
> [3] RenderingDeviceVulkan::prepare_screen_for_drawing (c:\godot\drivers\vulkan\rendering_device_vulkan.cpp:7182)
> [4] RendererCompositorRD::prepare_for_blitting_render_targets (c:\godot\servers\rendering\renderer_rd\renderer_compositor_rd.cpp:37)
> [5] RendererViewport::draw_viewports (c:\godot\servers\rendering\renderer_viewport.cpp:606)
> [6] RenderingServerDefault::draw (c:\godot\servers\rendering\rendering_server_default.cpp:110)
> [7] RenderingServerWrapMT::draw (c:\godot\servers\rendering\rendering_server_wrap_mt.cpp:93)
> [8] Main::iteration (c:\godot\main\main.cpp:2515)
> [9] ProgressDialog::task_step (c:\godot\editor\progress_dialog.cpp:211)
> [10] EditorNode::progress_task_step (c:\godot\editor\editor_node.cpp:3868)
> [11] EditorProgress::step (c:\godot\editor\editor_node.h:874)
> [12] EditorFileSystem::reimport_files (c:\godot\editor\editor_file_system.cpp:1952)
> [13] EditorFileSystem::_update_scan_actions (c:\godot\editor\editor_file_system.cpp:578)
> [14] EditorFileSystem::_notification (c:\godot\editor\editor_file_system.cpp:1150)
> [15] EditorFileSystem::_notificationv (c:\godot\editor\editor_file_system.h:107)
> [16] Object::notification (c:\godot\core\object\object.cpp:795)
> [17] SceneTree::_notify_group_pause (c:\godot\scene\main\scene_tree.cpp:820)
> [18] SceneTree::idle (c:\godot\scene\main\scene_tree.cpp:447)
> [19] Main::iteration (c:\godot\main\main.cpp:2503)
> [20] OS_Windows::run (c:\godot\platform\windows\os_windows.cpp:621)
> [21] widechar_main (c:\godot\platform\windows\godot_windows.cpp:163)
> [22] _main (c:\godot\platform\windows\godot_windows.cpp:185)
> [23] main (c:\godot\platform\windows\godot_windows.cpp:199)
> [24] __scrt_common_main_seh (d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
> [25] BaseThreadInitThunk
> -- END OF BACKTRACE --

**Steps to reproduce:**
1. scons platform=windows  -j 6 target=debug
2. Run godot.windows.tools.64.exe

**Comment by Calinou** [comment]
@theoniko Which graphics card model do you have?

**Comment by theoniko** [comment]
@Calinou: I edited my previous comment with the graphics card version

**Comment by Calinou** [comment]
@theoniko If you use a laptop with hybrid graphics, are you sure that the dedicated GPU is used? Godot should do this by default, but we never know.

**Comment by theoniko** [comment]
I right clicked godot.windows.tools.64.exe and in selected run with graphics processor i choosed High-performance NVIDIA processor but again it crashed after 1minute.

**Comment by Calinou** [comment]
@theoniko I don't know what could be causing this, but make sure your NVIDIA graphics driver is up-to-date.

**Comment by theoniko** [comment]
I tried again with updated graphics cards drivers but godot crashed again after some time. One point to note is that before the crash in the terminal reports several time the following

**Comment by theoniko** [comment]
Is there any other workaround to avoid the crash?

**Comment by Calinou** [comment]
> Is there any other workaround to avoid the crash?

Not that I know of. The Vulkan renderer isn't production-ready yet anyway.

**Comment by theoniko** [comment]
@Calinou: I have not tried to reproduce the issue recently. I will maybe give it a try this weekend. Was there any change/fix in the meantime that i am not aware of?

**Comment by clayjohn** [comment]
To me this looks like there are 2 potential causes:
1. this could be a driver error. The optimus drivers are notoriously buggy. If this is the case, then hopefully a future driver update will fix the issue.
2. We may need to have special logic for optimus drivers. The odd thing about optimus is that it uses your dedicated GPU for rendering, but uses the integrated GPU for presenting to screen. Its possible that Godot needs extra logic to adapt to that arrangement

**Comment by theoniko** [comment]
Hello @Calinou, @clayjohn,
I did a clean build with the latest master today and there is no crash anymore.
I would say we can close this issue. Thank a lot for your answers and help.

**Comment by clayjohn** [comment]
Great! Thank you for checking again!
