### ISSUE TITLE
RigidBody physics for TileMaps (CollisionShape passing to parent)

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#4454]
_feature proposal_
I was thinking about a kind of game, where you sort of build a ship - rooms, corridors, wings etc. The best way to do this would be with TileMaps. But there is an obvious problem.

To fly this ship you would have to treat it as a RigidBody, and there is no option like that. There is an option "Use Kinematic", but it's really confusing. Can I move() the TileMap ? How can I detect collisions with it?

The workaround right now would be to contain the TileMap in a RigidBody and for each cell create a collision shape suitable for a tile in that cell. The fact that it's doable this way, and not via a "TileMap" option is not a good thing in my opinion.

The whole idea of collisions within TileMaps seems a little flawed to me. My proposition:
1. Change "Use Kinematic" to "Use Static Body" selected by default
2. TileSets can contain collision shapes, but don't have to contain Static Body anymore
3. If the user deselects Use Static Body the TileMap will now have to be a child of a PhysicsBody2D (Rigid,Kinematic or Static) which will use the collision shapes

Since the tilemap can be very big I can understand why this was never a feature in the first place, but since an aformentioned workaround is possible... This would also make TileSet creation a little less of a pain (no need to use static bodies).
What do you think? Is this feature a good idea? Would it be hard to implement?

**Comment by khairul169** [comment]
And also, area2d is needed to detect some part like ladder, spike, trap, etc.. It would be useful without adding several area2d node to the scene..

**Comment by WalasPrime** [comment]
That's a good idea. In a hierarchy like this:
> [Node2D] Player
> [StaticBody2D] TheMap
>> [TileMap] Tiles here

> [Area2D]
>> [TileMap] TrapsHere

It would be easy to connect to signals. The only issue would be how to tell which cell sent the signal?
One solution comes to mind: since we wish to extend TileMap's functionality we could create these new classes (no StaticBodyTileMap, since that would be the backwards-compatible one):
> KinematicBodyTileMap - would expose KinematicBody2D's move, move_to, etc.

> RigidBodyTileMap - would expose RigidBody2D's methods, and also modified signals that would pass cell's x,y of collisions

> Area2DTileMap - I think Area2D's would have to be instanced per-cell, so expose a get_cell_area2d, and then you could connect to signals, set some properties etc.

**Comment by khairul169** [comment]
Projecting the player position to the tilemap?
TileMap node have a map_to_world & world_to_map function... if the cells is known by using world_to_map(player_pos)..
And then, we can detect if the player is colliding with the ladder or spike by the cells name..
TileMap.get_tileset().tile_get_name(cell_id);

**Comment by WalasPrime** [comment]
You can do that too. But there is no workaround like that for physics-based application.

**Comment by WalasPrime** [comment]
Implemented this workaround today. Requires a structure like this:

> [RigidBody2D]
>> [TileMap] - script attached here
>>> [CollisionShape2D] TemplateCollision - for example a 32x32 rectangle

````
## Rigid TileMap
## by WalasPrime
#
## Overrides set_cellv, requires a TemplateCollision
#

extends TileMap

onready var _colTpl = get_node("TemplateCollision")
var POS_COLLIDER_MAP = {}

func remove_map_entry(pos):
	# 1. Find the index
	if POS_COLLIDER_MAP.has(str(pos)):
		var oidx = POS_COLLIDER_MAP[str(pos)]
		# 2. Decrease all indexes > oidx
		for k in POS_COLLIDER_MAP:
			if POS_COLLIDER_MAP[k] > oidx:
				POS_COLLIDER_MAP[k] -= 1
		# 3. Remove the entry
		POS_COLLIDER_MAP.erase(str(pos))
		# 4. Return the oidx
		return oidx
	else:
		return null

# POS is a TileMap coordinate (like in regular set_cellv)
# TODO: Check if there is something already at POS
func set_cellv(pos, id):
	if id != -1:
		# Sets the cell - Get the Shape2D
		var shape = _colTpl.get_shape()
		var pos_g = map_to_world(pos)
		get_parent().add_shape(shape, Matrix32(0,pos_g))
		POS_COLLIDER_MAP[str(pos)] = get_parent().get_shape_count()-1
	else:
		var idx = remove_map_entry(pos)
		if idx != null:
			get_parent().remove_shape(idx)

	.set_cellv(pos,id)

````
Probably far from optimal (you can move the str() functions into one place). Will work with Area2D too. The POS_COLLIDER_MAP is required to remember what collision index corresponds to what. You could also iterate over collision shapes and check their transform.

**Comment by Footurist** [comment]
Just wanted to ask if this is still on the table? This feature would be very awesome indeed!
