### ISSUE TITLE
Automatic Reimport settings have no effect

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#44545]
**Godot version:** 3.2.3 stable, 3.2.4 beta4

**OS/device including version:** Win64

**Issue description:**
Both the **"Ask Save Before Reimport"** and the **"Automatic Reimport On Sources Changed"** in the Editor Settings seem to have no effect.
There is no popup asking me if I want to save before reimport and the textures still get reimported and immediately updated when "Automatic Reimport On Sources Changed" is disabled. 
Files are always automatically reimported and updated.

**Steps to reproduce:**

1. Make a new project and drag an image file into the scene to create a Sprite with a texture.
2. Enable "Ask Save Before Reimport" and disable "Automatic Reimport On Sources Changed"
3. Change the image in an external image editor, and save it.
4. Switch back to Godot to see Godot reimporting and updating.

This also happens if you save your project or even close Godot all together and reopen everything after making the changes in the Editor settings.

**Comment by Calinou** [comment]
These settings don't exist in the current `3.2` branch nor `master`. Are you sure they weren't from an older version and then removed? See https://github.com/godotengine/godot/issues/22099.

**Comment by golddotasksquestions** [comment]
@Calinou 

![image](https://user-images.githubusercontent.com/47016402/102723120-43b91580-4306-11eb-9ee8-e18e6d4251c4.png)


![image](https://user-images.githubusercontent.com/47016402/102723138-63e8d480-4306-11eb-9126-778234e3a2f9.png)

**Comment by Calinou** [comment]
@golddotasksquestions This is what I have here:

![image](https://user-images.githubusercontent.com/180032/102723621-7d3f5000-4309-11eb-8f67-272b1a8be8f3.png)

**Comment by golddotasksquestions** [comment]
That's very creepy lol

**Comment by Calinou** [comment]
Anyway, this is a d
uplicate of #22099.
