### ISSUE TITLE
Physics regression with Bullet 3.07 

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot#44547]
**Godot version:**
Godot master after https://github.com/godotengine/godot/commit/3cbf8bde8455f98f9b447237ebfe578aca397574

**OS/device including version:**
Fedora

**Issue description:**
I have a project where I place vegetation. I use raycasting with `PhysicsDirectSpaceState3D::intersect_ray` in a local space to not interfere with certain collisions.
I've bisected the commit and https://github.com/godotengine/godot/commit/3cbf8bde8455f98f9b447237ebfe578aca397574 seems to be the cause. I though It would be the multimeshes not rendering the vegetation mesh after the autoLOD commit but it's the physics always returning false from `PhysicsDirectSpaceState3D::intersect_ray`

**Steps to reproduce:**
**Minimal reproduction project:**
I've described all the info I have in the previous section, It might take a while to isolate the cause in my code and create a minimal rep project but I could try if the cause of this doesn't seem evident for a physics versed contributor.

**Comment by AndreaCatania** [comment]
@lupoDharkael Interesting, can you please provide a sample project? Otherwise is really difficult spot it.

**Comment by lupoDharkael** [comment]
I'll try to create one later today or tomorrow.

**Comment by lupoDharkael** [comment]
I think it's easier for me to bisect Bullet because in my case I have a procedural generator, it produces terrain at runtime and generates the colliders, after that I reparent all the colliders in a local space and do the raycasts to find where each plant should be placed. It's part of a big C++ module so creating a minimal reproduction project might be time cosuming. I hope the bisection points to a small commit so it's easy to identify the cause.

**Comment by AndreaCatania** [comment]
Ok, that's fine.
I don't know if this information is useful or not; though, if your Body or Shape have a negative scale some query (ray cast, shape cast, motion test) fail.

**Comment by lupoDharkael** [comment]
It's not happening in master anymore. I'm closing the issue.
