### ISSUE TITLE
AnimationPlayer playing animation on both instances of packedscene

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#44550]
**Godot version:**
3.2.4 beta 4

**OS/device including version:**
Windows 10 x64

**Issue description:**
I've created all player animations via scripting, then saved them into AnimationPlayer. On another scene I instantiated
this "Character" node, with animation, 2 times. When player 1 walks nothing happens, but when player2 walks both plays animation

**Steps to reproduce:**
* Create animations via script
* save them into animation player
* in another scene
* instantiate it 2 times
* call $AnimationPlayer.play("animationname")

**Minimal reproduction project:**

[MK - Copia.zip](https://github.com/godotengine/godot/files/5721207/MK.-.Copia.zip)

**Comment by akien-mga** [comment]
That's not a minimal reproduction project, and you can't expect us to debug a full project with a dozen scenes and scripts.

You're using a complex state machine setup where the methods that trigger the walk animation are called through a dynamically generated FuncRef.

While there *might be* an engine issue (e.g. shared FuncRef between instances), there might also be a bug in your own code, and a bug report on the engine tracker is not the place to debug it.

**Comment by nonunknown** [comment]
I just couldnt make a MRP due to complexity, and the problem is only on Character.gd and Fight.tscn
