### ISSUE TITLE
 Zoom on automatic LODs cause error.

### ISSUE THREAD

**Issue by fire** [godotengine/godot#44551]
**Godot version:**
d3ff3dc6ce96ef1d9d513917ff61abe62e266c19

**OS/device including version:**
WIN10, VULKAN, Nivida

**Issue description:**

Zoom on LODs cause error.

![image](https://user-images.githubusercontent.com/32321/102719232-bfcd4200-42a1-11eb-8ebe-c60ad9ee9f64.png)

See also https://github.com/zeux/meshoptimizer/issues/206.

**Steps to reproduce:**

Open project and scene.

Zoom out.

**Minimal reproduction project:**
Add https://sketchfab.com/3d-models/subd-minitutorial-8ee637a4afa44d95836749c994270dd3#download to your project.

[subd_minitutorial.zip](https://github.com/godotengine/godot/files/5721215/subd_minitutorial.zip)

[Subdiv Project.zip](https://github.com/godotengine/godot/files/5721219/Subdiv.Project.zip)

**Comment by alexfreyre** [comment]
I don't know if this is what I have experimented too, but I had similar artifacts on a rounded complex mesh, I can't determine visually if is this same issue or if is the mesh not completely closed, with open faces or holes

**Comment by alexfreyre** [comment]
LOD bias 1.0
![image](https://user-images.githubusercontent.com/42384785/103094734-74df6180-45f6-11eb-8055-3da8ee955594.png)

LOD bias 0.5
![image](https://user-images.githubusercontent.com/42384785/103094852-9f311f00-45f6-11eb-91f6-34df1ebc1a93.png)

**Comment by fire** [comment]
@alexfreyre The normals should flip but it should not artifact like that anymore in master

**Comment by alexfreyre** [comment]
Happy new year! @fire I have compiled with this commit uploaded and I am doing a project which has a character separated in parts, the previous image was of the head and with this PR it was solved, but in the hands remains the issue. I deleted the .godot folder and the whole scene was exported from blender as a gltf, I wish I am wrong, but all the project reimported in Godot the hands remains with holes. On the other hand, the triangles flipped are a little noticeable, so little but visible

**Comment by fire** [comment]
Can you post an example so we can determine why it's broken

**Comment by alexfreyre** [comment]
if helps, this happen in archlinux x64, intel i7-6600U with Skylake GT2 [HD Graphics 520] (rev 07) and with nvidia 940m too.

I can confirm I have re-compiled Godot again, re-deleted the .godot folder within the project folder and there still holes.


![Screenshot_20210101_000808](https://user-images.githubusercontent.com/42384785/103433909-a60cf280-4bf1-11eb-8366-a38c7af6610f.png)
![Screenshot_20210101_000839](https://user-images.githubusercontent.com/42384785/103433910-a7d6b600-4bf1-11eb-9963-6310151150ca.png)
![Screenshot_20210101_000907](https://user-images.githubusercontent.com/42384785/103433911-a907e300-4bf1-11eb-8ffb-47b9b008e939.png)
![Screenshot_20210101_001018](https://user-images.githubusercontent.com/42384785/103433912-a9a07980-4bf1-11eb-99bb-9dc8b275c620.png)
![Screenshot_20210101_001034](https://user-images.githubusercontent.com/42384785/103433913-aad1a680-4bf1-11eb-9bff-f9b3ba5ea219.png)
![Screenshot_20210101_001147](https://user-images.githubusercontent.com/42384785/103433915-ab6a3d00-4bf1-11eb-9855-1a6104d6faae.png)
![Screenshot_20210101_001227](https://user-images.githubusercontent.com/42384785/103433916-ac02d380-4bf1-11eb-993d-7ba0b31d6149.png)

**Comment by fire** [comment]
Can you test https://github.com/godotengine/godot/pull/45038?

**Comment by alexfreyre** [comment]
@fire I can confirm that it works now perfectly!

I've test your "meshopt-scale" godot fork.
I've exported/imported from blender to godot a character to test, the break points were the hands and the head, so I have exported each one bigger than before, each one with 1.5 millions of poligons.
As a result for each object, several lod meshes were created and none of them have triangles flipped/hole nor nothing else strange!

you did it! :1st_place_medal:

**Comment by fire** [comment]
Thats great! Please double check the distances where the lod transition and they actually do, I’ve written the procedure in the pr. Make a video. Wanted to see the transitions and know that it didn’t stay lod0.

**Comment by alexfreyre** [comment]
https://user-images.githubusercontent.com/42384785/104104792-2abad900-52a2-11eb-950f-23ff69242240.mp4

**Comment by fire** [comment]
Resolved. The shadow mesh changes will be done in a future revision.
