### ISSUE TITLE
Light-only mode in CanvasItemMaterial makes both sprite and light disappear

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44559]
**Godot version:**

bccbd4b

**Issue description:**

![2TU6IRUzXA](https://user-images.githubusercontent.com/2223172/102729064-5eec4b00-432f-11eb-9b57-3453a2e9aa2f.gif)

**Steps to reproduce:**
1. Create Sprite2D
2. Create Light2D
3. Assign icon.png to both
4. Add CanvasItemMaterial to Sprite2D node
5. Set the light mode in the material to light only

**Comment by chrom007** [comment]
I have same problem... A lot of developers use this feature. How to fix it? Or how soon it will be fixed

**Comment by Calinou** [comment]
> I have same problem... A lot of developers use this feature. How to fix it? Or how soon it will be fixed

For 2D masking in 4.0, you should use CanvasItem's Clip Children property instead.

**Comment by KoBeWi** [comment]
The problem with Clip Children is that, as name suggests, it only clips children. Light Only mode was very useful because it could "clip" any node and supported light masks.

In my project I managed to replace Light Only mode with a shader and a global uniform.

**Comment by Calinou** [comment]
> In my project I managed to replace Light Only mode with a shader and a global uniform.

Could it be added to [Godot Shaders](https://godotshaders.com/)? :slightly_smiling_face:

**Comment by KoBeWi** [comment]
idk it boils down to a single line
```GLSL
COLOR.a = min(COLOR.a, 1.0 - distance(item_detector_pos, global_pos + (UV - vec2(0.5, 0.5)) * 30.0) / item_detector_range);
```
It makes the object visible when within a certain range from an "observer", where `item_detector_pos` (global uniform) is the position of the observer and `global_pos` (regular uniform) is the position of the object. Unlike Light Only solution it has a limit of 1 observer and it was written specifically for my project, so not sure if it's useful.

**Comment by chrom007** [comment]
> To my knowledge, nobody knows how to resolve this yet. That said, for 2D masking in 4.0, you should use CanvasItem's Clip Children property instead of using Light2D for masking.

I used this technique in the past to make a "fog of war" or "field of view".

How it worked in Godot 3:
![image](https://user-images.githubusercontent.com/12010456/226110250-c43ef9a3-ccd0-4616-b470-74908f63fc19.png)

But in Godot 4.0 its not work... sprite is full invisible 😢

**Comment by chrom007** [comment]
Finally someone solved this problem! 😺

**Comment by Datoh** [comment]
Still not working for me, the sample is still broken: https://github.com/godotengine/godot-demo-projects/tree/master/2d/light2d_as_mask

**Comment by orolyn** [comment]
Do we have a workaround in the mean time?

**Comment by Janonas** [comment]
This issue is straight up kneecapping my project, hope it gets resolved.

**Comment by chrom007** [comment]
After this fixes: https://github.com/godotengine/godot/pull/75181
In my case everything (FOW) works good in Godot 4! 😃👍🏻 

![image](https://github.com/godotengine/godot/assets/12010456/4a8d492f-5f4c-4204-af9a-6062c225a16f)
