### ISSUE TITLE
Reopening a script doesn't updates it from disk

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4456]
Tested on Windows 7 64 bits, Godot 2.0.2

For convenience, I had to switch to Sublime Text for editing a script to benefit from rectangular selection. I saved, then reopened the script in Godot, but the changes where not there.
I opened from another editor, my changes were applied. Godot didn't actually reloaded the file.

If I keep the script open, it will update as soon as I unfocus/refocus Godot. This issue happens when the script has been closed.

Steps to reproduce:
1) Create a script and attach it to a node
2) Open the script in the script editor, then close it (Ctrl+W)
3) Modify the script in an external editor and save it
4) Reopen the script in Godot: notice nothing has changed

From 4), the only way to get an update is to unfocus and refocus Godot by clicking somewhere else (desktop on another app).

**Comment by kubecz3k** [comment]
Was able to confirm in 2.0.2 build

**Comment by reduz** [comment]
i guess when the script is opened in the editor, it should check if the file changed and reload it?

**Comment by Zylann** [comment]
If the file has not been closed, yes.

But if the file has been closed with Ctrl+W, then it shouldn't be "hidden", but really closed, that's the point. This way, when you open it again, you load the file as it is on disk.
