### ISSUE TITLE
3.2.3-stable_win64 Won't start

### ISSUE THREAD

**Issue by bigtunacan** [godotengine/godot#44564]
**3.2.3-stable_win64:**

**OS/device including version:**
Windows 10, version 20H2
OpenGL ES 3.0 Renderer: GeForce GTX 1080 Ti/PCIe/SSE2

**Issue description:**
Godot starts to open with the terminal window that outputs the Godot version and renderer information.  It never gets past that to the phase where Godot would normally actually start-up.

**Steps to reproduce:**
Try to start Godot

**Minimal reproduction project:**
No project needed for this.

**Comment by clayjohn** [comment]
Can you provide more information about your setup?

Right now there is nothing we can do with that amount of information. 

Consider adding more information about your hardware, also have you updated drivers recently or anything? 

Is there anything unique about your setup? 

Have any other Godot versions worked for you?

**Comment by bigtunacan** [comment]
@clayjohn I'm closing this out.  It appears this is related to the Windows 20H2 update.  It had recently installed, but not rebooted following the install.  I tried running 3.2.2 (which I knew was working) and that was no longer working either.  I rebooted to complete the windows update and now everything is working correctly.

**Comment by clayjohn** [comment]
Thanks for following up! 

Have fun!
