### ISSUE TITLE
Godot texture are all black

### ISSUE THREAD

**Issue by AaryanGamez** [godotengine/godot#44572]
Hello, I'm trying to create a 3d fps game in Godot but no matter what I do the textures are always black. I tried millions of stuff but nothing seems to work.

My PC specs: 4gb of ram, 1.6 GHz extendable to 2.6, intel hd 4000 and dual core processor
Please help I'm just a newbie.

**Godot version:3.2.2 stable release**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
1) You need to place a light in your scene.
2) I see it's an Intel HD 4000, if they remain black after placing a light it's a driver bug.

**Comment by akien-mga** [comment]
Please share a project that triggers the issue, and post screenshots. There's nothing we can do with so little information.

**Comment by AaryanGamez** [comment]
@Zireael07  thanks for your reply friend I hope it works out

**Comment by AaryanGamez** [comment]
@Zireael07  Thanks a lot, it did work. now i can create my game (tyran) you can ask me for help if you ever need

**Comment by Zireael07** [comment]
Didn't we have an issue about having a default light in? I can't find it but quite a lot of first-time users forget to add a light in...

**Comment by Calinou** [comment]
> Didn't we have an issue about having a default light in? I can't find it but quite a lot of first-time users forget to add a light in...

The default environment provides natural light, but maybe it's not working for OP here.
