### ISSUE TITLE
Can't access preloaded script member from static function with single line call

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4457]
Tested in Windows 7 64 bits, Godot 2.0.2

It is not possible to access a constant from another script under **certain conditions**.
It makes me unable to separate inner classes from a giant script in my project, unless I pass the constant as argument everywhere.

**Steps to reproduce**
scene1
1) Create a script A on a node
2) Create a script B with a constant in it
3) In script A, use the constant from B. The code editor will complain.
4) Run the scene: it works anyways.

scene2
1) Create a script A on a node
2) Add a constant in A
3) Create a script B with a static function using the constant of A
4) Call the function of B from A. The editor will complain.
5) Run the scene: it won't run, the same eror will happen.

**Example project**: http://zylannprods.fr/dl/godot/ConstError.zip
As attachment: [ConstError.zip](https://github.com/godotengine/godot/files/238879/ConstError.zip)

In the linked project, there are two scenes.
In scene1, the code editor raises an error while the script is being written, but the scene runs without problems. Only one preload() is evaluated.

In scene 2, the scene doesn't runs and raises the same error.
Here, there are two preload() to evaluate successively.

**Theory**
I didn't see the C++ code, but I think that when GDScript sees preload(), it will try to compile the referenced script, but if that script has itself a reference to the other script, it will fail because the other script has not finished to compile.
It's interesting to note that on the other hand, static function calls will work because they might be looked up at runtime instead of compile-time.

Maybe related: issue #1411

**Comment by kubecz3k** [comment]
Can you attach sample project as an attachment? I'm unable to download it from provided link.

**Comment by bojidar-bg** [comment]
@Zylann ~ With the sample project I wasn't able to reproduce the first (scene1) problem at all on current master.
The second problem was missing a `SCENE2_CONSTANT` definition in `scene2.gd`, but even when adding it, execution can't get past the recursive `preload()`-ing. Changing `preload` to `load` in `scene2.gd` fixes it though.

**Comment by kubecz3k** [comment]
@Zylann tested this as well, also was able to reproduce only scene2 bug. @bojidar-bg I dont think it's about recursive preloads since I changed `scene2.gd` script to:

> func _ready():
> 	var twoScript = preload("two.gd");
> 	twoScript.test();
and this still behaves like this

**Comment by Zylann** [comment]
Sorry, I forgot to add this in scene2.gd:
```gdscript
const SCENE2_CONSTANT = 222
```
I updated the archive.
But as bojidar-bj said, it still doesn't works.

Also, scene1 is actually supposed to run correctly, I just wanted to point out that when you write scene1.gd from scratch, you'll get an error in the code editor only.

**Comment by reduz** [comment]
this is not a bug, this is (at least to me) clearly a recursive scene preload between scene2.gd and two.gd
```

static func test():
	#preload("scene2.gd").func_test()
	
	var v = preload("scene2.gd").SCENE2_CONSTANT
	print(str(v))


```

scene2.gd:
```

extends Node

const SCENE2_CONSTANT = 222


func _ready():
	preload("two.gd").test()


```
bug one is fixed since a few days ago (when you save scripts, they are updated and re-parsed)
