### ISSUE TITLE
3.2.4beta: Auto Exposure not working with FXAA enabled

### ISSUE THREAD

**Issue by Avogine** [godotengine/godot#44576]
**Godot version:**
v3.2.4.beta4.official

**OS/device including version:**
Nvidia Rtx 2070 Super (driver version 460.89)
GLES 3

**Issue description:**
Auto exposure isn't working when enabling fxaa.

This seems to only be present in 3.2 beta1-4, in 4.0 it's working as expected.
Glow is still affected by auto exposure when enabling fxaa.

https://user-images.githubusercontent.com/55308941/102821152-e04ae880-43d6-11eb-8e78-74ecfa286dee.mp4

**Steps to reproduce:**
Create a scene in which auto exposure is visible (high contrast in brightness).
Enable auto exposure.
Enable Fxaa, auto exposure has no effect anymore.

**Minimal reproduction project:**
[fxaa_bug.zip](https://github.com/godotengine/godot/files/5726501/fxaa_bug.zip)

**Comment by Calinou** [comment]
I ported over the FXAA code from `master` to `3.2`, but I don't know why this is happening.

**Comment by akien-mga** [comment]
Fixed by #44711.
