### ISSUE TITLE
EmeraldSquare FBX

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#44579]
Working on the new FBX importer port for 4.0.

**Godot version:**
2c3bf66157c2c99d9fb2379d9bbfebd49fde668d

The PR I'm working on https://github.com/godotengine/godot/pull/44499

**OS/device including version:**
Linux, Manjaro 

**Issue description:**
- I can't determine the correct settings for alpha on the trees something seems broken in the renderer, flickering is present on the tree's, this is being discussed in IRC. We tried looking at it via IRC but it's not clear what is broken or what is being done wrong.
- We need a standard set of transparency options that importers can use safely.
- Tried MSAA and various workaround suggested in IRC.
- Would really like some assistance with this as it's not something I do normally.

**Steps to reproduce:**
1. Download https://developer.nvidia.com/orca/nvidia-emerald-square
2. Extract into your local test project
3. Build my PR https://github.com/godotengine/godot/pull/44499 as target=release_debug (otherwise import will take 30+ minutes)
4. Open any of the provided FBX files and you can see the tree's have no alpha, this is correct as I've disabled these flags temporarily.
5. Add directional light, environment (sky)
6. Tweak materials on tree's to enable the alpha/alpha scissoring. (this will be fixed in importer after we know the correct settings for 4.0)
7. no matter what you set you should see flickering, depth issues or scissoring not quite working as expected.

**Minimal reproduction project:**
Please see the link provided above.

**Comment by RevoluPowered** [comment]
The scene
![image](https://user-images.githubusercontent.com/748770/102833467-198c5400-43e9-11eb-8f0f-f1bc9c71ee4c.png)
Alpha Scissor with tweaks (little better but still flickering)
![image (2)](https://user-images.githubusercontent.com/748770/102833514-3b85d680-43e9-11eb-8bac-65deb976d3ee.png)
![image (3)](https://user-images.githubusercontent.com/748770/102833536-480a2f00-43e9-11eb-93d6-516def82c980.png)

Alpha flickering intensely when you move camera
![image (5)](https://user-images.githubusercontent.com/748770/102833561-59ebd200-43e9-11eb-966c-8ae6ebba23d7.png)
note I only moved the camera 5-10 degrees and flickering is captured
![image (4)](https://user-images.githubusercontent.com/748770/102833564-5b1cff00-43e9-11eb-835c-de23b15e42dc.png)

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
