### ISSUE TITLE
Normal mapping offsets refraction rather than just distorting them

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#44571]
**Godot version:**
3.2.3.Stable

**OS/device including version:**
NA

**Issue description:**
Normal mapping offsets refraction rather than just distorting them. This appears to be because the normals are not unpacked before being used for the distortion.
![e019cp75Dz](https://user-images.githubusercontent.com/4955051/102781830-37799a80-4390-11eb-852c-bc09e9ff55a7.gif)

**Current**
```
NORMALMAP = texture(texture_normal,base_uv).rgb;
NORMALMAP_DEPTH = normal_scale;
vec3 ref_normal = normalize( mix(NORMAL,TANGENT * NORMALMAP.x + BINORMAL * NORMALMAP.y + NORMAL * NORMALMAP.z, NORMALMAP_DEPTH) );
```

**Suggested**
```
NORMALMAP = texture(texture_normal,base_uv).rgb;
NORMALMAP_DEPTH = normal_scale;
vec3 normal_unpacked = NORMALMAP * 2.0 - 1.0;
vec3 ref_normal = normalize( mix(NORMAL,TANGENT * normal_unpacked.x + BINORMAL * normal_unpacked.y + NORMAL * normal_unpacked.z, NORMALMAP_DEPTH) );
```

**Steps to reproduce:**
Open attached project to see the issue.

**Minimal reproduction project:**

[refraction_bug.zip](https://github.com/godotengine/godot/files/5724504/refraction_bug.zip)

**Comment by Arnklit** [comment]
One additional thing I've found. When I use an actual normal map texture for this, rather than the generated simplex noise one I used in the example it seems to cause issues to multiply by the z channel of the normal map.

So I have to change this:
```vec3 ref_normal = normalize( mix(NORMAL,TANGENT * normal_unpacked.x + BINORMAL * normal_unpacked.y + NORMAL * normal_unpacked.z, NORMALMAP_DEPTH) );```

to this:
```vec3 ref_normal = normalize( mix(NORMAL,TANGENT * normal_unpacked.x + BINORMAL * normal_unpacked.y + NORMAL, NORMALMAP_DEPTH) );```

I assume that's because we don't have z vectors in normal maps in Godot?

**Comment by Calinou** [comment]
> I assume that's because we don't have z vectors in normal maps in Godot?

Indeed, normal maps are compressed using RGTC (red-green texture compression) because that's more efficient.

**Comment by Arnklit** [comment]
My normal maps don't have Z either, since all I'm working in at the moment is Godot, so I just removed the multiplication with z. But I don't know if z then should be calculated from x and y and plugged in there in there in this case, so it get's taken into account in the distortion, but I'm guessing the visual difference will be negligible.

**Comment by clayjohn** [comment]
Looks like we need to unpack normal map manually for use with refraction here https://github.com/godotengine/godot/blob/e6e1f6212d08342f48bac79f723631d8bde4574e/scene/resources/material.cpp#L859

the above line should be altered to look like it does in the scene shader:
https://github.com/godotengine/godot/blob/e6e1f6212d08342f48bac79f723631d8bde4574e/drivers/gles3/shaders/scene.glsl#L1819-L1826
