### ISSUE TITLE
@export_enum Weird Behavior

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#44570]
**Godot version:**
master (0923494c78130d69ff6d53737c53e5b6cfc163a2)

**OS/device including version:**
Windows 10 64 Bit

**Issue description:**
```
enum Element {FIRE, WATER, WIND, EARTH}

@export_enum(Element) var element_enum: Element = {}


func _ready():
    element_enum["Entry"] = "Value"
    print(element_enum)
```
I'm not sure what the expected behavior here is, as @export_enum() expects a list of strings, rather than an enum.
but for some reason passing in an enum works, but in the Inspector it shows up as Dictionary
![image](https://user-images.githubusercontent.com/24433899/102775133-90dfca80-438c-11eb-8a8f-afa87437c6cd.png)

enums in general seem to be not very usable at this point in time.
I don't see any way to export an enum as of now, but that's a separate issue.

**Comment by EricEzaM** [comment]
Ah I think I have noticed this before, but not just for enums. I think for any non primitive type? Not at a computer Rn so I can't check but I will try to remember to do so.

**Comment by vnen** [comment]
> `@export_enum(Element) var element_enum: Element = {}`

This is invalid, you're assigning a dictionary (`{}`) as the default value. The only problem is not showing an error, but I'm fixing that now.
