### ISSUE TITLE
Export AAB can not run on Android device when using one-click deploy from the editor

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#44588]
**Godot version:**

3.2.4 beta 4

**OS/device including version:**

**Issue description:**

When export format set to Export AAB, then click the Android icon to run from the editor, it shows:

Invalid filename! Android App Bundle requires the *.aab extension.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Does this occur *only* when using one-click deploy from the editor, or also when manually exporting and installing the AAB on the device?

**Comment by alexzheng** [comment]
@Calinou only when using one-click deploy from the editor

**Comment by alexzheng** [comment]
That's caused by when using one-click deploy from the editor, it just run with the file tmpexport.apk, so the check for .aab will not valid, it can be just ignored.

**Comment by m4gr3d** [comment]
Fixed by PR https://github.com/godotengine/godot/pull/44639
