### ISSUE TITLE
CONNECT_REFERENCE_COUNTED requires two disconnects for a single connect

### ISSUE THREAD

**Issue by chess123mate** [godotengine/godot#44584]
https://github.com/godotengine/godot/blob/2cbc0b641a0d58a88592d52d86634ca2d40da9e4/core/object/object.cpp#L1368

The simple fix is to change `slot->reference_count >= 0` to `slot->reference_count > 0`, except then if the first connection does not use `CONNECT_REFERENCE_COUNTED` and then a second connection does (this does not currently error), then you would need only a single disconnect despite `connect` having been called two times.

**Comment by Calinou** [comment]
@chess123mate Which Godot version did you experience this bug with?

Also, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by chess123mate** [comment]
Version: Godot Engine v3.2.3.stable.official

The project I was experimenting with when I discovered this bug (it is fairly minimal): [Connect.zip](https://github.com/godotengine/godot/files/5761605/Connect.zip)

**Comment by Shatur95** [comment]
Can reproduce on 3.2.3 too:

```gdscript
extends Node2D


onready var _timer = $Timer


func _ready() -> void:
	_timer.connect("timeout", self, "_on_timeout", [], CONNECT_REFERENCE_COUNTED)
	_timer.connect("timeout", self, "_on_timeout", [], CONNECT_REFERENCE_COUNTED)
	_timer.connect("timeout", self, "_on_timeout", [], CONNECT_REFERENCE_COUNTED)
	_timer.disconnect("timeout", self, "_on_timeout")
	_timer.disconnect("timeout", self, "_on_timeout")
	_timer.disconnect("timeout", self, "_on_timeout")
#	_timer.disconnect("timeout", self, "_on_timeout") # Uncomment to prevent calling _on_timeout


func _on_timeout() -> void:
	print("Called!")
```
