### ISSUE TITLE
APK can not upload to google play when set target SDK to 30

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#44587]
**Godot version:**

3.2.3 

**OS/device including version:**

**Issue description:**

You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
So this should already be resolved for custom build on Godot 3.2.4. @alexzheng Can you check with the latest beta for Godot 3.2.4 after enabling custom build and check that the generated apk is properly signed?

The issue remains however for users that wants to use the prebuilt apk without relying on `custom builds`. 
For that scenario, it should be feasible to resolve the issue by replacing `jarsigner` in the Android export logic with `apksigner`. That change will also affect how signing is done for the prebuilt apk.

**Comment by alexzheng** [comment]
However, in 3.2.4 beta, after enable custom build and install the android build template, set the export format to Export APK,  all of my projects just crash when run on Android devices,  the logcat message shows:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-23 17:00:07.988 11928 11928 F DEBUG   : Build fingerprint: 'Xiaomi/chiron/chiron:9/PKQ1.190118.001/V12.0.1.0.PDEMIXM:user/release-keys'
12-23 17:00:07.988 11928 11928 F DEBUG   : Revision: '0'
12-23 17:00:07.988 11928 11928 F DEBUG   : ABI: 'arm64'
12-23 17:00:07.988 11928 11928 F DEBUG   : pid: 11841, tid: 11897, name: GLThread 60525  >>> com.xunyougame.puzzlesgame <<<
12-23 17:00:07.988 11928 11928 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-23 17:00:07.988 11928 11928 F DEBUG   : Abort message: 'java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: can't call java.lang.ClassLoader android.content.ContextWrapper.getClassLoader() on instance of org.godotengine.godot.Godot'

**Comment by m4gr3d** [comment]
@alexzheng That's expected behavior. The `Godot` class no longer extends the `Activity` class, and so you need to check your code for usage of `getClassLoader()` and make sure they're being called from an activity reference instead of a `Godot` reference.

**Comment by alexzheng** [comment]
I did not call getClassLoader in my code, I only used the admob module :
https://github.com/kloder-games/godot-admob

**Comment by m4gr3d** [comment]
@alexzheng Looking at the code, it's an actual bug resulting from forgetting to migrate the old java modules logic when the update to the `Godot` class was done.
I'll provide a PR to fix the `getClassLoader()` issue.

**Comment by alexzheng** [comment]
I can confirm the getClassLoader issue have fixed by this PR.

Since there are other issues in 3.2.4 beta, I have not uploaded an APK file build by 3.2.4 yet, I can not confirm this issue.
