### ISSUE TITLE
Antialiasing in draw() doesn't work with Intel Graphics on Linux

### ISSUE THREAD

**Issue by Nolkaloid** [godotengine/godot#44597]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Tested on Arch Linux with Intel HD Graphics 520
Tested on Ubuntu 18.04 with Intel HD Graphics 4600
Tested on Manjaro with an NVIDIA GTX 1050

Both GLES2 & GLES3 were tested.

**Issue description:**
Using the anti-aliasing option in draw methods (draw_arc, draw_line etc.) doesn't do anything with Intel Graphics on Linux.
Lines and arcs appeared smooth when using the NVIDIA setup.
![image](https://user-images.githubusercontent.com/30960698/102929968-dfc85580-449b-11eb-8d6a-a5d7e04e1fec.png)
Make sure to open the original image as your browser may anti-alias the preview :)

**Repro project**
[intel_alias_bug.tar.gz](https://github.com/godotengine/godot/files/5732349/intel_alias_bug.tar.gz)

**Comment by Calinou** [comment]
Disable HDR in the Project Settings.

**Comment by Nolkaloid** [comment]
Hey! HDR was already disabled. I spent my whole afternoon trying to figure out what was happening, but without success...
[intel_alias_bug.tar.gz](https://github.com/godotengine/godot/files/5732349/intel_alias_bug.tar.gz)
May be related to #38872 and #43618

**Comment by lawnjelly** [comment]
Whether anti-aliasing works or not is down to your GPU and drivers, the feature is a OpenGL hint not mandatory. As such it is not really a bug, more a feature, this behaviour is expected.

Explained in #43618.

**Comment by Nolkaloid** [comment]
That's quite unfortunate... Thanks for the explanation.
I'm wondering if it works on Windows, I guess that the Intel drivers for Linux are pretty meh.
