### ISSUE TITLE
everything goes wrong sequence

### ISSUE THREAD

**Issue by WolfGames** [godotengine/godot#44595]
when i exported my project this sequence happend:
1.Scene was unable to change in exported project
2.On project restart every scene was playing at same time 
3.Editor was always displaying scene Game.tscn 
4. drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054 on project run

This broke my whole project! Please help or fix this!

**Comment by Calinou** [comment]
@WolfGames Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.

**Comment by WolfGames** [comment]
Sorry I was inactive for some time but this issue is outdated.
My project works fine in new versions.
Nevermind
