### ISSUE TITLE
Error pressing the up, left and space keys simultaneously

### ISSUE THREAD

**Issue by dsncreation** [godotengine/godot#44615]
**Godot version:** 3.2.3

**OS/device including version:**
Windows 10, OpenGL ES 3.0 Renderer: AMD Radeon(TM) Vega 8 Graphics

**Issue description:**
Good morning to everyone in the community!
When pressing the up, left and space keys simultaneously, a false value is being returned, the same does not happen when you press the up, right and space keys and that is exactly what I need, a true return to fire in a spaceship game.

**Comment by EIREXE** [comment]
Have you tried using another keyboard? It may be the keyboard's motherboard acting up.

Also, what method are you using for checking the input?

**Comment by juse4pro** [comment]
This is usually what happend if you use a matrix style keyboard. This effect is called ghosting.
You can test if it is a keyboard issue here: [MultiKeyDisplay](https://drakeirving.github.io/MultiKeyDisplay/)

**Comment by dsncreation** [comment]
yes, I tested it, but the same thing happens. I tested with MultiKeyDisplay
and when pressing the up, left and space keys, the first two light up, the
space is already off.

Fábio Venâncio
1398836-2146


Em qua., 23 de dez. de 2020 às 10:40, Álex Román Núñez <
notifications@github.com> escreveu:

**Comment by dsncreation** [comment]
thanks for the support, it was very fast. I'm also sorry for my English,
it's not the language I speak, I'm from Brazil and I'm using the Google
translator to help me.
Fábio Venâncio
1398836-2146


Em qua., 23 de dez. de 2020 às 11:38, juse4pro <notifications@github.com>
escreveu:

**Comment by Zireael07** [comment]
Unfortunately there is nothing you can do to fix keyboard ghosting except changing the hardware. Not a Godot issue, in other words.

**Comment by akien-mga** [comment]
Closing as this is not a Godot issue.

**Comment by dsncreation** [comment]
Thanks for the clarification, it helped me understand how to work better
with godot and, of course, admire even more the work of the community that
supports this incredible engine.

[image: image.png]


Fábio Venâncio
1398836-2146


Em qua., 23 de dez. de 2020 às 13:07, Zireael07 <notifications@github.com>
escreveu:
