### ISSUE TITLE
PhysicsShapeQueryParameters2D collision_layer property is actually collision_mask

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#44622]
**Godot version:**

3.2, 4.0.dev

**Issue description:**

While looking at the code for `PhysicsShapeQueryParameters2D`, I noticed the property name `collision_layer` was different than the name in the implementation (`collision_mask`). This also occurs in the parameter names for various `intersect_...` functions in `PhysicsDirectSpaceState2D`. The implementation behaves as collision_mask, as it should.

This mismatch is also apparent in the documentation, for example [here](https://docs.godotengine.org/en/latest/classes/class_physics2ddirectspacestate.html#class-physics2ddirectspacestate-method-intersect-point). The parameter name is listed as "collision_layer", but the description only talks about a collision_mask. This can only serve to confuse users even more, given the already confusing nature of the two properties.

PhysicsShapeQueryParameters2D:
```cpp
// physics_server_2d.cpp
ClassDB::bind_method(D_METHOD("set_collision_layer", "collision_layer"), &PhysicsShapeQueryParameters2D::set_collision_mask);
ClassDB::bind_method(D_METHOD("get_collision_layer"), &PhysicsShapeQueryParameters2D::get_collision_mask);
...
ADD_PROPERTY(PropertyInfo(Variant::INT, "collision_layer", PROPERTY_HINT_LAYERS_2D_PHYSICS), "set_collision_layer", "get_collision_layer");
```

PhysicsDirectSpaceState2D:
```cpp
// physics_server_2d.cpp
ClassDB::bind_method(D_METHOD("intersect_point", "point", "max_results", "exclude", "collision_layer", "collide_with_bodies", "collide_with_areas"), &PhysicsDirectSpaceState2D::_intersect_point, DEFVAL(32), DEFVAL(Array()), DEFVAL(0x7FFFFFFF), DEFVAL(true), DEFVAL(false));
```
Note the parameter name "collision_layer". This bound function passes through to eventually arrive at this, with parameter "p_collision_mask":
```cpp
// space_2d_sw.h
virtual int intersect_point(const Vector2 &p_point, ShapeResult *r_results, int p_result_max, const Set<RID> &p_exclude = Set<RID>(), uint32_t p_collision_mask = 0xFFFFFFFF, bool p_collide_with_bodies = true, bool p_collide_with_areas = false, bool p_pick_point = false) override;
```

**Comment by rburing** [comment]
Fixed a few years ago by https://github.com/godotengine/godot/pull/51532.
