### ISSUE TITLE
regression in Area2D monitoring which results in callbacks missing

### ISSUE THREAD

**Issue by snaar** [godotengine/godot#44632]
**Godot version:** appears since 3.2.3 and still exists in head of 3.2 branch; 3.2.2 does **not** have this issue; I've done git bisect and it points at this commit, which does looks relevant: https://github.com/godotengine/godot/commit/ccdfaf24912c3c73a514e9ad8cba38c8b6a0a9b3

**Issue description:**
I noticed unexpected missing area_entered callbacks when playing around with Godot book example code from https://github.com/vnen/Godot-24-Hours/tree/master/Godot-Hour5/finished-project-with-exercises

I've narrowed down the issue to the attached repro project that doesn't need any human input to observe the issue.

There is whole bunch of stuff happening to the scene tree and the monitored areas in the project, which results in that sometimes the _on_player_area_entered callback is not called when asteroid's area enters player's area.

The scene is setup that player (i.e. ship) periodically spawns the shots that immediately queue_free() themselves - key here seems to be that they are spawned overlapping the ship's area. If shots do not overlap then there is no issue. Then asteroids are periodically spawned and move towards the ship. They are expected to trigger _on_player_area_entered, which then will draw an explosion around the ship. Before commit ccdfaf24912c3c73a514e9ad8cba38c8b6a0a9b3 it happens consistently for every asteroid. After commit ccdfaf24912c3c73a514e9ad8cba38c8b6a0a9b3 it does NOT happed for every asteroid.

**Steps to reproduce:**
Open attached project in 3.2.3 and hit play button. Observe that sometimes there is no explosion around the ship as asteroid hits it. For comparison, open it in 3.2.2 and observe that there is consistently an explosion around the ship as asteroids hit it.

**Minimal reproduction project:**
[repro-20201223.zip](https://github.com/godotengine/godot/files/5737195/repro-20201223.zip)

**Comment by Calinou** [comment]
cc @madmiraal

**Comment by madmiraal** [comment]
Fixed with #44695 and its 3.2 version #44696.
