### ISSUE TITLE
Overlapping BBcode sections not being parsed correctly in RichTextLabel

### ISSUE THREAD

**Issue by Tercus** [godotengine/godot#44634]
**Godot version:**
3.2.3-stable

**OS/device including version:**
Distro: KDE neon 20.04 5.20
Kernel: 5.9.0-14.1-liquorix-amd64 x86_64
Desktop: KDE Plasma 5.20.4
CPU: AMD Ryzen 7 3800X
GPU: Radeon RX 5500 (driver: amdgpu)
Backend: GLES3

**Issue description:**
If you have overlapping BBcode, one of the entangled BBcode-tags is being ignored. `[i]This [b]is[/i] a test[b]` will result in something like this:
_This **is[/i] a test**_

**Steps to reproduce:**
* Create a new RichTextLabel
* edit the BBcode.text field to contain `[color=maroon][u]This is[/color] a[/u] test`
* run the scene

**Comment by Calinou** [comment]
I'm not sure if this is a bug or intended behavior (i.e. it's considered too much of an edge case to be worth supporting).

**Comment by dalexeev** [comment]
BBcodes are similar to HTML, in which such overlaps are not allowed.

```html
<b>aaa<i>bbb</b>ccc</i>
```

Use instead

```html
<b>aaa<i>bbb</i></b><i>ccc</i>
```

**Comment by Tercus** [comment]
I just tested this and that is correct. Browsers usually transform such documents internally. The HTML specification even [has a section](https://html.spec.whatwg.org/multipage/parsing.html#adoption-agency-algorithm) for dealing with such problems and also refers [to another site discussing that problem](https://ln.hixie.ch/?start=1037910467&count=1). Great read and very informative. As such I would close this ticket as this is working as intended.
There might be a point in automatically converting invalid tags, but that was not what this ticket was for.
