### ISSUE TITLE
Creating directories broke!

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#4464]
Creating directories broke!
I discovered that someone had broken a very good thing that worked perfectly before.

Earlier I commonly when saving new files, simply specify a desired path, and if it did not exist, then all the required directory created automatically to any depth and saves the file with the specified name. like this... in 1.1 stable
```
func seve_file():
	FILE_PATH = "res://SAVED_DATA/new_NONEXISTENT_directory/test/test.txt"
	FILE = File.new()
	
	if (FILE.file_exists(FILE_PATH) == false && VOX_FILE.is_open() == false):
		FILE.open(FILE_PATH, File.WRITE)
		FILE.store_string("string_12345678")
		FILE.close()
```

but now when I tried to save a file in a directory that previously did not exist, I was suddenly was refused and I had to rewrite the old code which previously worked fine using a single string, and create a whole monster which added all a bunch of blocks in which it was necessary to rewrite each directory selected call options to create the directory manually, and this shit for automation ...
in 2.0.1 stable
```
func seve_file():
	var dir = Directory.new()
	dir.make_dir("res://SAVED_DATA/new_NONEXISTENT_directory")
	dir.make_dir("res://SAVED_DATA/new_NONEXISTENT_directory/test")
	
	FILE_PATH = "res://SAVED_DATA/new_NONEXISTENT_directory/test/test.txt"
	FILE = File.new()
	
	if (FILE.file_exists(FILE_PATH) == false && VOX_FILE.is_open() == false):
		FILE.open(FILE_PATH, File.WRITE)
		FILE.store_string("string_12345678")
		FILE.close()
```

simply return how it worked before, it was perfect!!!

**Comment by OlexiyKravchuk** [comment]
I'm sorry, I was a stupid asshole, because of this possibility and did not exist before, I spent a further investigation in my old project where the code worked, and it turned out that I was there only created the illusion that it is working as it is written, but it is actually a directory just created a different way, and I fooled myself .. I apologize for the confusion, and that perhaps brought someone misleading or hurt, I close this issue ...
But still very much I want it to work so, without crutches, and the invention of wheels ...

**Comment by akien-mga** [comment]
Don't worry, I don't think anyone was hurt :)

About the bug itself, I think the behaviour in 2.0.x is what it should be. Creating files and creating directories are different operations, so it's normal that you need to create the directories manually when they're missing, trying to opening a non-existing file should not create all the directories that would lead to it, it should just throw an error.

**Comment by OlexiyKravchuk** [comment]
I meant that the directories created only in the moment when a file already written to disk, but not at the time of verifying the existence or opening for operations, ie, directories are created at the last moment before putting there the finished to record the file after editing it, if for this operation is have enough free space ...
