### ISSUE TITLE
VisibilityEnabler2D disables parent's process after queue_free

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#44647]
**Godot version:** 3.2.3 & 3.2.4.beta4 & master(8ad0ff8ae5)

**OS/device including version:** not graphics-related.

**Issue description:**
`queue_free`ing a `VisibilityEnabler2D` node disables the parent's `process()` and `physics_process()`.

I think it's related to this code block in `NOTIFICATION_ENTER_TREE`:

https://github.com/godotengine/godot/blob/3fdf4bfe71311000bf706c16d79b475308a200ac/scene/2d/visibility_notifier_2d.cpp#L243-L250

* The `set_process(false)` won't be cancelled.
* There is no `set_process(true)` in `NOTIFICATION_EXIT_TREE`.

**Steps to reproduce:**
Try the MRP.

The sprites' `process()` rotates themselves. The middle one calls `queue_free` in the `viewport_entered` signal. The right one calls `queue_free` after one second.

**Minimal reproduction project:**
[Enabler.zip](https://github.com/godotengine/godot/files/5738609/Enabler.zip) (3.2 project)

**Comment by KoBeWi** [comment]
Fixed in 4.1 or earlier.
