### ISSUE TITLE
GDscript min and max are inverted

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#44659]
**Godot version:**
ecda989

**Issue description:**
The GDScript functions `min` and `max` are inverted:
- `min()` returns the maximum value
- `max()` returns the minimum value 

**Steps to reproduce:**

```gdscript
extends Node

func _ready():
	print("Min(20, 30): ", min(20, 30)) # Returns 30
	print("Max(20, 30): ", max(20, 30)) # Returns 20

```

**Minimal reproduction project:**
[MinMaxIssue.zip](https://github.com/godotengine/godot/files/5740168/MinMaxIssue.zip)

**Comment by RevoluPowered** [comment]
we should add C++ test for this if possible too

**Comment by amoriqbal** [comment]
I can confirm this on Linux Mint 20.04.

**Comment by AndreaCatania** [comment]
@amoriqbal Please check this if you can: https://github.com/godotengine/godot/pull/44661

**Comment by amoriqbal** [comment]
The issue started from this commit abfc528439f334eaea91377a46121089aa5be229. The bug was introduced via #43890 .
The previous commit (f26a765637acea98b4745d4b17d1e82961b267c1) does not have this issue.
