### ISSUE TITLE
SSAO buffer corrupted on NVidia GPUs

### ISSUE THREAD

**Issue by AlfonsoGrimaldo** [godotengine/godot#44666]
**Godot version:**

v4.0.dev

**OS/device including version:**

Windows 10 Pro, v20H2, compilation 19042.685, AMD FX-6300, GTX 960 2gb

**Issue description:**

Apparently when ssao is active there doesn't seem to be much difference between on and off. Sometimes a diffuse, dark texture appears on the screen that stains the screen (this texture can change its appearance when the screen changes in size or the quality changes).

==================================Output========================================
 Attempted to use the same texture in framebuffer attachment and a uniform (set: 1, binding: 6), this is not allowed.

================================Windows Console====================================
ERROR: Attempted to use the same texture in framebuffer attachment and a uniform (set: 1, binding: 6), this is not allowed.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6194)

ASSAO OFF
![ASSAO OFF](https://user-images.githubusercontent.com/48926464/103105210-f1237600-45f1-11eb-82b3-36fa70f7c308.jpg)
ASSAO ON
![ASSAO ON](https://user-images.githubusercontent.com/48926464/103105217-f84a8400-45f1-11eb-88e9-71f233b9d143.jpg)

This video better shows what i'm talking about.

https://user-images.githubusercontent.com/48926464/103105530-09949000-45f4-11eb-9994-4f7990ed2760.mp4

**Steps to reproduce:**
Just turn on the ssao and test debug mode or light mode.

**Minimal reproduction project:**

[NOTE THE PROJECT DON'T HAVE SPONZA SCENE BECAUSE IT'S VERY BIG BUT IT CONTAINS THE MODEL sibnek.fbx TO TRY]
[Project_test.zip](https://github.com/godotengine/godot/files/5740437/Project_test.zip)

**Comment by Calinou** [comment]
If your materials use an ambient occlusion map, make sure to set **Ao Channel Affect** to 1.

**Comment by Calinou** [comment]
> Sometimes a diffuse, dark texture appears on the screen that stains the screen (this texture can change its appearance when the screen changes in size or the quality changes).

I can reproduce this when no DirectionalLight is present in the scene.

**Godot version:** Git https://github.com/godotengine/godot/commit/545c89461464ee14b2b806dd2dd2c0eef110e181
**OS:** Fedora 33
**GPU:** GeForce GTX 1080 (NVIDIA 455.45.01)

**Comment by clayjohn** [comment]
Uh oh. Does this happen on all scenes?

Can you also send a screen shot of the "normal_roughness buffer" it's another one of the debug modes. 

I had issues in the sibenik model I have because the normals were completely corrupted.

**Comment by Unknownn1024** [comment]
**Godot version:** 
v4.0 dbd00d932e27088f6f8a8fc88e5dd75796719ada

**OS/device including version:**
OpenSUSE / RX 5500 XT (Mesa 20.2.4)

new ASSAO works fine but there are output errors
![image](https://user-images.githubusercontent.com/17591539/103107396-e2b77780-464e-11eb-97ee-09a2dde7cea5.png)

![image](https://user-images.githubusercontent.com/17591539/103107433-48a3ff00-464f-11eb-878e-3ec110f1ceb3.png)

**Comment by clayjohn** [comment]
@Unknownn1024 Thanks for confirming. It looks like this is an NVidia specific issue. 

The error is unrelated to SSAO and there is already a PR submitted to fix it :) https://github.com/godotengine/godot/pull/44530

**Comment by AlfonsoGrimaldo** [comment]
This fixes #44530 the nvidia problem?

**Comment by AlfonsoGrimaldo** [comment]
I have tried the demo of Intel ASSAO and AMD CACAO and they work fine. In all the projects that I have it works badly, I even created a new one and it is the same.

**Comment by clayjohn** [comment]
> This fixes #44530 the nvidia problem?

No, it fixes the framebuffer attachment error.

**Comment by AlfonsoGrimaldo** [comment]
In the two apis

**Comment by AlfonsoGrimaldo** [comment]
Here I leave you some images with the normal buffer.

![Clare ao buffer](https://user-images.githubusercontent.com/48926464/103107854-04d9d700-4608-11eb-9766-80a8d2b0974f.jpg)
![Clare normal buffer](https://user-images.githubusercontent.com/48926464/103107855-05726d80-4608-11eb-9918-d648cce13c5a.jpg)
![Sibnek normal buffer](https://user-images.githubusercontent.com/48926464/103107856-05726d80-4608-11eb-9025-a1032e450f54.jpg)

The sponza model has problems in the geometry, I think it is a bug from the collada importer.
![Sponza normal buffer](https://user-images.githubusercontent.com/48926464/103107857-060b0400-4608-11eb-854b-2d3922598af1.jpg)

**Comment by clayjohn** [comment]
@AlfonsoGrimaldo Would you be willing to run a scene in RenderDoc or Nvidia Nsight to show me further details?

I don't think I can debug this without access to NVidia hardware

**Comment by AlfonsoGrimaldo** [comment]
If you explain me how to do it. I will do it

**Comment by clayjohn** [comment]
@Calinou and I have been debugging this a little. So far we have figured out that the issue is coming from the blur pass. I am not sure what the root cause is. But this means their are 2 workarounds for now:
1. Set ``blur_passes`` in the ProjectSettings to 0, so no blur is performed; or
2. Set quality to "Very Low"
