### ISSUE TITLE
Unrecognizable font character adds unwanted space when outline size is not zero.

### ISSUE THREAD

**Issue by AureaFUNSoft** [godotengine/godot#44674]
**Godot version:**

Godot 3.2.3.stable
Godot 3.2.4.beta4

**OS/device including version:**

Windows 10 64-bit

**Issue description:**

When I add unrecognizable character for some font without outline that character will be ignored and not drawn, which is the correct behavior. But when I set outline size other than zero it will add some space in that character place. I also notice that it will push the next character drawn outside the label rect. Here is the screenshot:
![Annotation 2020-12-24 212335](https://user-images.githubusercontent.com/8875839/103127266-aa05b580-46c3-11eb-9e23-5d7d0c1375b7.jpg)

**Steps to reproduce:**
Open the project below. I include 2 fonts for example.
Open FontSpaceBug.tscn

**Minimal reproduction project:**

[FontSpaceBug.zip](https://github.com/godotengine/godot/files/5741499/FontSpaceBug.zip)

**Comment by AureaFUNSoft** [comment]
Maybe related to this issue #37901
But they said that this doesn't happen to Label. But I used Label in this issue.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by akien-mga** [comment]
Fixed by #44679.
