### ISSUE TITLE
Fullscreen mode uses the resolution of the first screen when using multiple screens not the primary one

### ISSUE THREAD

**Issue by aleksandrbazhin** [godotengine/godot#44673]
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10, Nvidia 940GT, GLES2 and GLES3

**Issue description:**

I have a notebook with 1920x1080 resolution and 150% hipdi scaling (1280x720 scaled resolution) and another 1920x1080 monitor with no scaling set as a primary one. When launching the project set to be fullscreen it is only launched in the 1280x720 window. There is a number of similar issues in the tracker, like https://github.com/godotengine/godot/issues/44028, but I did not find the exact description.

**Steps to reproduce:**
- set the second monitor as a primary one
- in a project settings set Window->Fulscreen to On
The launched project window will be displayed on the second screen, but will have the size of the first one.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/21674.
