### ISSUE TITLE
Draggin a node on graph does not appears visually until mouse has been released

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#44677]
**Godot version:**
c4c211c3b7608f79457f16bb42ad8839a9cdcf5a

**OS/device including version:**
Win10

**Issue description:**
Graph nodes do not visually follow the mouse while dragging. A regression from c4c211c3b7608f79457f16bb42ad8839a9cdcf5a.

**Steps to reproduce:**
Run a graph (visual shader or visual script), add a node, and try dragging:

![graph_bug](https://user-images.githubusercontent.com/3036176/103132225-e41b8b00-46b4-11eb-8f8b-ce217c388598.gif)

**Minimal reproduction project:**
No need, very simple to reproduce.

**Comment by akien-mga** [comment]
Probably some signal callbacks or UndoRedo which haven't been updated if passed by string.
