### ISSUE TITLE
When exporting for iOS, simulator options doesnt appear to run the app

### ISSUE THREAD

**Issue by gustavottc** [godotengine/godot#44681]
**Godot version:**
3.2.3-stable

**OS/device including version:**
iMac 27"
XCode: Version 12.3 (12C33)
OS: Catalina 10.15.7 (19H15)

**Issue description:**
If i export a project in Godot for iOS, the XCode doesn't let me test on Simulator, but when i make a new project in XCode it appears letting me thinking its a issue of Godot
![img](https://cdn.discordapp.com/attachments/760935236762206219/791871514790199296/Captura_de_Tela_2020-12-25_as_00.34.17.png)

**Steps to reproduce:**
Export the Game normally

**Minimal reproduction project:**
Can be in any project

**Comment by Calinou** [comment]
I don't remember if official iOS export templates contain simulator binaries.

**Comment by akien-mga** [comment]
> I don't remember if official iOS export templates contain simulator binaries (which are x86 instead of ARM).

They do: https://github.com/godotengine/godot-build-scripts/blob/master/build-ios/build.sh

**Comment by gustavottc** [comment]
hey @akien-mga , how can i use this script?
it's needed to run this script always when i export a new project? 

i think the older versions of Godot you doesn't need to run this script

**Comment by gustavottc** [comment]
Like this video, he was able to run the game on simulator: https://www.youtube.com/watch?v=_huwSZu3XSs&ab_channel=KemoJallow

**Comment by naithar** [comment]
Strange. Just tested on new Macbook with fresh installed Godot and everything works fine.
<img width="300" alt="Снимок экрана 2020-12-26 в 20 26 29" src="https://user-images.githubusercontent.com/3750083/103156335-c0416d80-47b8-11eb-969f-29971bd0369e.png">

Xcode does filter out simulators that might not be supported by application, so maybe that's the actual source of the problem. Can you try downloading additional simulator runtimes, like iOS 13-14 and add them to the simulator list to check if that's the problem?

**Comment by gustavottc** [comment]
Hey @naithar , i already did that, but didn't make any difference, PS: This is a new project that i tested the export, and have the same problem

![image](https://user-images.githubusercontent.com/20030153/103156502-e569b800-4787-11eb-918a-78400f7ba5ae.png)
![image](https://user-images.githubusercontent.com/20030153/103156490-cb2fda00-4787-11eb-93df-a3177418c3e0.png)
![image](https://user-images.githubusercontent.com/20030153/103156496-d84cc900-4787-11eb-8b43-4fe2b35b3be0.png)

**Comment by gustavottc** [comment]
And this is a clean XCode project, as you can see theres options to run on a simulator

![Captura de Tela 2020-12-26 às 14 39 13](https://user-images.githubusercontent.com/20030153/103156536-22ce4580-4788-11eb-9dc9-262ea517f2d9.png)

**Comment by naithar** [comment]
I see... well, I can't really tell what's the problem then. 

Can you provide the project that you are trying to export? Maybe there is something wrong with project itself that is causing Xcode to exclude simulator runtimes?

Other than that I really have no idea what could be the cause - as you can see new clean Godot project exports perfectly fine.

**Comment by gustavottc** [comment]
Here is the project: https://www.mediafire.com/file/shumkwsp41ve0yy/admob.zip/file
This project it's on 3.2.4.beta4 version, but i can easily change for 3.2.3 if you want to

I will try to export a clean project and download the simulators on 13.0 version to see how if works,

**Comment by naithar** [comment]
I have simulators available in the list.
<img width="300" alt="Снимок экрана 2020-12-26 в 20 54 08" src="https://user-images.githubusercontent.com/3750083/103156704-95f1af00-47bc-11eb-9eb8-aca116f8bbc8.png">

Well, it actually might be a Xcode caching something that doesn't allow this project on your end to list simulators. 
You can try creating new Scheme, if it fixes the issue then it's something in Xcode cache. 
You can also try clearing `Derived Data` folder and restarting Xcode (not sure if restarting Mac is necessary) to clear all cached data.

**Comment by gustavottc** [comment]
Same thing on a clean project 
![Captura de Tela 2020-12-26 às 14 57 11](https://user-images.githubusercontent.com/20030153/103156750-cc163b00-478a-11eb-8f93-8cb2b657f79e.png)


Probably it's something about the version of simulator XCode

**Comment by naithar** [comment]
Let me know if clearing cache works, but it seems like a problem that people face with entirely different project according to stackoverflow.

**Comment by gustavottc** [comment]
Didn't work, i including restart the XCode and the Computer, but it's with the same problem, currently i'm trying to download the Simulator 13.0, do you know what version of Simulator do you have installed?

**Comment by naithar** [comment]
Both 14.0 and 14.3 simulator runtimes is working fine on my end.

**Comment by gustavottc** [comment]
Well, i fixed, but i think this is still a issue of Godot with newest versions of XCode because it shouldn't do that

To fix i changed these three datas:

Excluded Architectures -> Debug -> Add: i386
![Captura de Tela 2020-12-26 às 18 11 01](https://user-images.githubusercontent.com/20030153/103159245-da258500-47a5-11eb-8c75-745ad392ac07.png)
Build Active Architecture only -> Yes
![Captura de Tela 2020-12-26 às 18 10 33](https://user-images.githubusercontent.com/20030153/103159247-dd207580-47a5-11eb-8a81-12b120df90e0.png)
Architectures -> Stantard Architectures
![Captura de Tela 2020-12-26 às 18 10 12](https://user-images.githubusercontent.com/20030153/103159248-de51a280-47a5-11eb-97c5-9700998167b6.png)


@naithar can you please how are the these configurations of your XCode?

**Comment by naithar** [comment]
Well, I have default settings:
<img width="675" alt="Снимок экрана 2020-12-27 в 00 23 46" src="https://user-images.githubusercontent.com/3750083/103159377-d7448780-47d9-11eb-9103-8f9207a15c78.png">

Also `arm7v` arch requires your own Godot build as default uses only `arm64`. And you shouldn't use `Build Active Architecture` for anything but `Debug` mode.

**Comment by gustavottc** [comment]
True, i deactivate the ```Build Active Architecture``` and works, as i'm developing AdMob for iOS i also needed to [add one more Arch to Exclude: arm64](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios), due: 
![Captura de Tela 2020-12-26 às 18 51 32](https://user-images.githubusercontent.com/20030153/103159719-769e5600-47ab-11eb-8f21-5b24e626c5df.png)

Now everything is working.
![Captura de Tela 2020-12-26 às 18 40 11](https://user-images.githubusercontent.com/20030153/103159631-7c476c00-47aa-11eb-8f66-48deb0263ff2.png)

I still don't know why it only appeared to select the Simulator when I changed these settings and basically my computer configuration is the same as yours, I hope that the Godot team will investigate and adjust this.

As I have solved the problem temporarily i will close the issue. Thank you, all of you.

**Comment by MikeFrom** [comment]
I've the same problem on an **Intel Mac Mini** with **Godot 3.4.stable**. The iOS Simulators don't show up. I can add manualy i386 arm64 to Excluded Architectures, then the iOS Simulators show up, but the build crashes on the Simulator.

Any news/fixes about this Intel iOS Simulator problem? Thanks.

**Comment by Calinou** [comment]
> I've the same problem on an **Intel Mac Mini** with **Godot 3.4.stable**. The iOS Simulators don't show up. I can add manualy **i386 arm64** to **Excluded Architectures**, then the iOS Simulators show up, and I can compile, but the build crashes on the Simulator.
> 
> Any news/fixes about this Intel iOS Simulator problem? Thanks.

Please continue the discussion here: https://github.com/godotengine/godot/issues/55902
