### ISSUE TITLE
Tilemap C# clearing cells with for loop.

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#44685]
**Godot version:**

3.2.3-stable_mono_win64

**OS/device including version:**

Windows 10.

**Issue description:**

I've tried to clear all used cells in tilemap with code below, but tilemap erases not every cells, (looks like it clears every 2nd cell). 
```csharp
for (int i = 0; i < GetUsedCells().Count; i++)
{
    var cell = (Vector2)GetUsedCells()[i];
    SetCellv(cell, -1);
}
```
however if you use foreach, it works fine:
```csharp
foreach (var item in GetUsedCells())
{
    var cell = (Vector2)item;
    SetCellv(cell, -1);
}
```

it also works if you use dublicate **GetUsedCells().Duplicate()** into variable and loop over it.

**Steps to reproduce:**
1. Open attached file.
2. Run.

**Minimal reproduction project:**

here -> [Example.zip](https://github.com/godotengine/godot/files/5742120/Example.zip)

**Comment by Calinou** [comment]
In the first code sample, you're getting the currently used cells on *every* iteration. Not only this is slower, but this also means you're iterating over an array while iterating over it. Hence the "unstable" behavior.


You need to use foreach in your case.
