### ISSUE TITLE
Add scroll in Web editor Loader page

### ISSUE THREAD

**Issue by Summersay415** [godotengine/godot#44692]
**Godot version:**
3.2.4 beta 4(Web Editor)

**OS/device including version:**

Ubuntu 20.10, Mozilla Firefox
Screen 1366x768

**Issue description:**
Couldn't scroll in Loader page in Web Editor

**Steps to reproduce:**
Open Web Editor and try scroll

**Comment by Calinou** [comment]
I'm working on the HTML5 editor page and downsized the logo so that scrolling shouldn't be necessary anymore, even on 1366×768 or mobile displays.
