### ISSUE TITLE
Mouse Pointer does not respect editor's Display Scale setting

### ISSUE THREAD

**Issue by tylerecouture** [godotengine/godot#44693]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
The mouse cursor/pointer does not get larger when I change the display scale of my my editor (

**Steps to reproduce:**
Editor > Editor Settings > General > Interface > Editor > Display Scale: 125%

Everything scales except the mouse pointer is still small

**Comment by Calinou** [comment]
The mouse cursor is drawn by your operating system. You have to change its size in your OS' mouse settings.
