### ISSUE TITLE
temporary aligned apk showing up way too much

### ISSUE THREAD

**Issue by DanesZalor** [godotengine/godot#44694]
**Godot version:**
Godot 3.2.3 Mono

**OS/device including version:**
Windows 10 (not graphics related)

**Issue description:**
Whenever I export an apk, the temporary unaligned apk shows up way too much, when I was working with the Godot GDScript version, it shows up way less than when I'm working with the mono version. Too much that every after 2 or 3 exports it shows up. 

**Steps to reproduce:**
This can be fixed by deleting the temporary aligned apk from C:\Users\name\AppData\Local\Temp\Godot\ but the problem is it occurs way too much that it could slow down testing a lot.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
What do you mean by "temporary aligned APK shows up too much"?

**Comment by DanesZalor** [comment]
there's an issue when exporting an apk, theres an error that says smth like "temporary unaligned apk" and wont export the game. it can be fixed by deleting a certain file in a certain directory that produces files whenever godot exports. but it happens way too often in the mono version

**Comment by neikeq** [comment]
Not sure if this is an issue with the android exporter that just affects C# projects more, or if it's something the C# exporter is doing wrong.

@godotengine/android Anyone knows what the `temporary unaligned apk` error is about and why it could happen?

**Comment by m4gr3d** [comment]
@neikeq @DanesZalor Are you seeing the `"Could not unzip temporary unaligned APK."` error?
Can you switch to `custom build` and see if that resolves the issue.

**Comment by m4gr3d** [comment]
@DanesZalor ping on this issue.

**Comment by DanesZalor** [comment]
oh yeah it's "Could not unzip temporary unaligned APK." it doesn't occur very often in the previous version though. I installed the latest version
