### ISSUE TITLE
Area2D can not override space at all.

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#4469]
v2.0.2 stable
win 10 x64

As it said here:
http://docs.godotengine.org/en/latest/classes/class_area2d.html#class-area2d
Area2D can override space parameters.

But:
![picture](https://cloud.githubusercontent.com/assets/10850402/14886575/02654e26-0d84-11e6-8bfb-4341afc39a29.PNG)
![picture2](https://cloud.githubusercontent.com/assets/10850402/14886576/02990c0c-0d84-11e6-8cea-ba3376384e3e.PNG)
Whatever I change `Gravity Vector` and `Gravity` to, nothing changes, the acceleration is the same.

**Comment by eska014** [comment]
You need to give your Area2D (and other CollisionObjects) shapes with which it collides. Easiest way is to use CollisionShape2D nodes for this: http://docs.godotengine.org/en/latest/tutorials/2d/physics_introduction.html#collisionshape2d

**Comment by buckle2000** [comment]
@eska014 Thank you, solved. But is there a way to set the default gravity?

**Comment by eska014** [comment]
You can change it in `Scene`→`Projects Settings` in the category `Physics 2d`.
