### ISSUE TITLE
Mouse pointer does not respect OS pointer size

### ISSUE THREAD

**Issue by tylerecouture** [godotengine/godot#44707]
Ref #44693

**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When I change the pointer size in my OS, the cursor reverts to its default size when my mouse pointer moves into the Godot editor

**Steps to reproduce:**
In Ubuntu 20.04:
Settings > Universal Access > Cursor Size > Large

Example:
![Godot Cursor](https://user-images.githubusercontent.com/10604391/103158464-fbb94900-4772-11eb-8866-87c8521c8db4.gif)

**Comment by Calinou** [comment]
What's your screen DPI/scaling factor? I can't reproduce this on Fedora 33 KDE (32×32 DMZ cursor theme, loDPI).

Also, it would have been better if you commented on the previous issue to clarify instead of opening a new issue.

**Comment by EveerDrof** [comment]
I can reproduce this bug. My OS is kubuntu 20.10. Editor is running when I change the cursor. In my case the cursor size and color are unchanged in the godot window. Even if I restart godot the cursor is the same. But it changes properly when I logout and start godot again. Should I try to fix this bug, or it is normal ?

**Comment by Calinou** [comment]
> Should I try to fix this bug, or it is normal ?

It's probably difficult to fix. Most applications I know of don't seem to bother with it.

**Comment by tylerecouture** [comment]
When I restarted Godot it picked up the new curser size.
