### ISSUE TITLE
"Cannot get CSGBrush" and other errors when creating a CSGMesh

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#44713]
**Godot version:**
Godot 3.2.4 dev 279f4fbb5f83c2df6e8499799a2aa0c14f85aa2d
Might happen too in Godot 4.0

**OS/device including version:**

**Issue description:**
An error occurred when I created a `CSGMesh`. I had a C++ debugger attached with a breakpoint in the error callback to catch my own stuff initially, but I got several unexpected errors like this one.
```
RROR: Cannot get CSGBrush.
   At: modules\csg\csg_shape.cpp:280
ERROR: VisualServer::mesh_add_surface_from_arrays: Condition "array_len == 0" is true.
   At: servers\visual_server.cpp:965
ERROR: ArrayMesh::add_surface_from_arrays: Condition "len == 0" is true.
   At: scene\resources\mesh.cpp:849
```
More of this happens when deleting the node.

**Steps to reproduce:**
I created a new scene, created a Node root node, then a MeshInstance with a PlaneMesh inside, then a CSGMesh. Then my C++ debugger I had attached broke into the error callback (originally to catch my own stuff):
![image](https://user-images.githubusercontent.com/1311555/103161189-f7724780-47d5-11eb-9654-977f57756f44.png)

It is then followed by this:
![image](https://user-images.githubusercontent.com/1311555/103161229-8a12e680-47d6-11eb-88ab-98fdd0eb93dc.png)

**Minimal reproduction project:**
None, sorry

**Comment by hoontee** [comment]
Adding a fix for this in #40814 / #43322.
