### ISSUE TITLE
Vulkan still does not work on multiple graphics cards

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot#44722]
**Issue description:**
Godot looks like this on all of my systems (details below):

![Screenshot](https://user-images.githubusercontent.com/16963337/103168476-95046000-4844-11eb-8a0b-b66b398627f6.png)

**Godot version:**
build fb16b1e39

**OS/device including version:**
Radeon R9 290 - Ubuntu 18.04 with amdgpu-pro/amdgpu
Radeon R9 290 - Ubuntu 20.04 with radeon/amdgpu with oibaf drivers
Radeon R9 290 - Ubuntu 20.10 LiveCD (radeon/amdgpu)
Radeon R9 290 - Windows 7 x64
Radeon RX 550 - Ubuntu 20.10 LiveCD (radeon/amdgpu)
GeForce GTX 670 - Windows 7 x64

**Steps to reproduce:**
- Boot the Ubuntu LiveCD (20.10, 20.04, any...)
- Download Godot from Calinou's builds
- Launch Godot, create an empty project and open it

**Minimal reproduction project:**
Just create a new empty project

I've never once seen Godot 4 working, so I assumed it's just this early in development. I've tried every few months, but it was always the same. But apparently it does work for some people?.. Just what kind of hardware or software do you have?! :) Am I doing something wrong?..

I've tried building if with GCC and Clang, with various options, debug and release_debug - it's all the same. Sometimes there are no errors in the console, and sometimes it says something about validation layers, but this appears to be not connected because that's not always the case. (Is it?)

There was #38410 , which seems to solve it for some people, but not for me. (There is also a mention of Godot not working on Debian Buster, but that's not surprising - #43231 .) I don't think R9 290 and especially RX 550 are so old they don't support Vulkan properly?..

**Comment by akien-mga** [comment]
It seems to work just fine. You have to add a light source if you want to see colors :)

**Comment by dark-penguin** [comment]
O_O So it's just that by default there is no sky light?..

OK, added light, now I can see things. It was just very unexpected to see this instead of what we usually saw. :)

**Comment by akien-mga** [comment]
There is sky light but there is no default sky, you have to add an environment.

This will likely change before the stable release though, see https://github.com/godotengine/godot-proposals/issues/1599.
