### ISSUE TITLE
Rect2 has_point() does not include points on the right and bottom border

### ISSUE THREAD

**Issue by lucassardois** [godotengine/godot#44723]
**Godot version:**

Godot version 3.2.3 stable from Steam.

**OS/device including version:**

Linux mint 19.

**Issue description:**

Rect2 has_point should return true when a point is inside a Rect2.

**Steps to reproduce:**
```
var array = [
Vector2(-3, 2),
Vector2(0, 0),
Vector2(1, 1),
Vector2(2, 1),
Vector2(1, 5),
]

var rect = Rect2(array.front(), Vector2.ZERO)
for pos in array:
rect = rect.expand(pos)

for pos in array:
  print(rect.has_point(pos))
```

This print:
```
True
True
True
False
False
```

While it should always print true since the Rect2 is created to contains all positions...

**Minimal reproduction project:**

See steps to reproduce.

**Comment by akien-mga** [comment]
That's a misunderstanding, `expand()` doesn't take a position but an offset. It doesn't expand the rect to contain the absolute coordinate you passed, it expands it by the given offset (so `Vector2(-3, 2)` will shrink it by 3 px on x for example.

**Comment by lucassardois** [comment]
Oh I see thanks for the precision. Maybe this could be added to the documentation?

**Comment by akien-mga** [comment]
Actually I'm wrong, the documentation for `expand` does say:
```
Returns this [Rect2] expanded to include a given point.
```

And that seems to be what the code does (or at least attempts to do).

**Comment by akien-mga** [comment]
`expand()` works fine, the problem is that `has_point()` does not include points on the right and bottom borders:
https://github.com/godotengine/godot/blob/d55e335026e4848d4d2ec21db8f334a9429c8cc8/core/math/rect2.h#L161-L177

I'm not sure if it's a design decision or a bug, but the 3D equivalent AABB does include borders:
https://github.com/godotengine/godot/blob/d55e335026e4848d4d2ec21db8f334a9429c8cc8/core/math/aabb.h#L286-L307

**Comment by Calinou** [comment]
PS: Make sure to add tests for this use case when opening a pull request :slightly_smiling_face:

**Comment by akien-mga** [comment]
As discussed in #44727, it's a design decision that the bottom and right borders are not included, so this is not a bug.
