### ISSUE TITLE
Controller d-pad up direction registering as pressed when it isn't - macOS

### ISSUE THREAD

**Issue by rob-patchett** [godotengine/godot#44721]
**Godot version:**
3.2.3 (also tested against latest `3.2` and `master` branches)

**OS/device including version:**
macOS 11.1 (Big Sur) - x86
Xbox Wireless Controller (030000005e040000fd02000003090000 in the [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) project) connected over Bluetooth

**Issue description:**
The up arrow on the d-pad of a controller registers as pressed when it isn't and pressing any direction activates the next arrow clockwise of it.

The up arrow should not present as pressed when it is not being pressed.

**Steps to reproduce:**
1. Connect a Xbox Wireless Controller (030000005e040000fd02000003090000) via Bluetooth to a x86 Mac running Big Sur
2. Download and run [Joypads demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/joypads)  inside the latest Godot release (3.2.3)

You will see the following image if pressing nothing on the controller:
<img width="655" alt="Screen Shot 2020-12-27 at 10 52 16" src="https://user-images.githubusercontent.com/5439648/103168225-adb74a80-4831-11eb-93ff-08cebfb3f495.png">

If you try different arrows on the d-pad, you will see the next arrow clockwise also being marked as pressed.

**Minimal reproduction project:**
See [Joypads demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/joypads)

**Comment by rob-patchett** [comment]
I have narrowed the problem to this function: https://github.com/godotengine/godot/blob/74512fd8765782ba6e12c3816966e2313833a81f/platform/osx/joypad_osx.cpp#L402

My proposed resolution for this is to increment each case in the function's switch statement by one, as it seems clear that `HAT_MASK_CENTER` should be 0, not `HAT_MASK_UP` as it is now. So the new code would look like this:

```
    switch (value) {
		case 1:
			hat_value = InputDefault::HAT_MASK_UP;
			break;
		case 2:
			hat_value = InputDefault::HAT_MASK_UP | InputDefault::HAT_MASK_RIGHT;
			break;
		case 3:
			hat_value = InputDefault::HAT_MASK_RIGHT;
			break;
		case 4:
			hat_value = InputDefault::HAT_MASK_DOWN | InputDefault::HAT_MASK_RIGHT;
			break;
		case 5:
			hat_value = InputDefault::HAT_MASK_DOWN;
			break;
		case 6:
			hat_value = InputDefault::HAT_MASK_DOWN | InputDefault::HAT_MASK_LEFT;
			break;
		case 7:
			hat_value = InputDefault::HAT_MASK_LEFT;
			break;
		case 8:
			hat_value = InputDefault::HAT_MASK_UP | InputDefault::HAT_MASK_LEFT;
			break;
		default:
			hat_value = InputDefault::HAT_MASK_CENTER;
			break;
	}
```

If this change looks acceptable, I will happily submit a PR for the change.

I'm surprised though that this code has been like this for so long. I am concerned this change might break support for older controllers that I don't have access to. Any suggestions on how to proceed would be welcome.

**Comment by rob-patchett** [comment]
Although I couldn't find a pre-existing issue for this, it appears to be the same as the issue mentioned here: https://github.com/godotengine/godot/issues/41065#issuecomment-702927922.

Since you were in that conversation @madmiraal, perhaps you'd be interested to comment on this issue.

**Comment by rob-patchett** [comment]
Also of note. I tested my controller against both https://gamepad-tester.com and https://www.generalarcade.com/gamepadtool/ (which uses the same controller mapping data as Godot: https://github.com/gabomdq/SDL_GameControllerDB) - both of which showed my controller working as expected.

**Comment by madmiraal** [comment]
@rob-patchett The Godot implementation matches the current SDL2 implementation:
https://github.com/spurious/SDL-mirror/blob/dd227ffbdabe2a9690410c64202ba8766a6a1397/src/joystick/darwin/SDL_iokitjoystick.c#L1020-L1051
So I suspect the problem lies somewhere else.

**Comment by rob-patchett** [comment]
Thanks for pointing this out @madmiraal - seems this might be trickier than I first expected. I played around with the SDL library on the same machine and with the same controller as I experienced this issue with in Godot. What I found is that this code you link to isn't being used for my controller. Instead, the sample tool I wrote hits this code in the SDL library: https://github.com/spurious/SDL-mirror/blob/dd227ffbdabe2a9690410c64202ba8766a6a1397/src/joystick/hidapi/SDL_hidapi_xboxone.c#L736-L767. 

Essentially, SDL recognizes it as an HID class device (https://www.usb.org/hid, https://hg.libsdl.org/SDL/rev/399cc39583cc) and based on that spec, the HAT value for dpad up is 1. However, other controllers such as the Switch Pro or PS4 controllers, dpad up is 0 (https://github.com/spurious/SDL-mirror/blob/dd227ffbdabe2a9690410c64202ba8766a6a1397/src/joystick/hidapi/SDL_hidapi_ps4.c#L695-L726). So the HAT values are controller-dependent.

I couldn't really tell if Godot uses the HID spec or not (perhaps it is being used on macOS but not Windows or Linux), but it seems this could explain the issue. It looks like SDL prefers the HID spec in general, though I haven't tested on Windows or Linux: https://github.com/spurious/SDL-mirror/blob/dd227ffbdabe2a9690410c64202ba8766a6a1397/src/joystick/SDL_joystick.c#L52-L92.

Any suggestions on where to take this next? Implementing something like the HID spec to the extent SDL does, looks pretty in-depth. Another option could be to check the device type in https://github.com/godotengine/godot/blob/74512fd8765782ba6e12c3816966e2313833a81f/platform/osx/joypad_osx.cpp#L402 and manipulate the `value` accordingly - could get messy though.

**Comment by dsrw** [comment]
I have a fix in my branch that sorts out the dpad issue and gets the triggers working. I've tested with rev1 and rev2 XBox One S controllers, and verified that PS4 controllers still work after the change. The new Series X controller works after updating [gamecontrollerdb.txt](https://github.com/godotengine/godot/blob/3.2/main/gamecontrollerdb.txt) to the latest version. I assume it will also work with the Elite 2, but I don't have one to test with.

https://github.com/dsrw/godot/commit/40efc29bf843a1af383c75327d491e97ec21fb33

I'm not much of a C++ programmer, but if this seems like a reasonable way to fix things, I can create a PR.

**Comment by snougo** [comment]
Xbox one S controller Bluetooth connition
macOS 14.10.6
well I got same issue, the Dpad up button is always pressed even it's not, but when running project in browser, there is no this issue
this is a very old issue I remember, is there any chance we can fix it in 3.2.4?

**Comment by Calinou** [comment]
> this is a very old issue I remember, is there any chance we can fix it in 3.2.4?

Since 3.2.4 is nearing release, I doubt it can be fixed in time.

**Comment by apertureless** [comment]
Is there any update on this?

I have the same issue. Even tho with a different controller. (8Bitdo Sn30 Pro+)
I checked out the Joypads demo. And the result was:

UP is always active.

If I press right: Right and bottom are active
If I press up: Up and right are active
If I press left: Left and up are active (event tho up is all the time active)
If I press down: Down and left are active

However if I check out the controlls in other apps like [Controlly](https://apps.apple.com/de/app/controlly/id1548544614?mt=12) or https://gamepad-tester.com/ it works fine.

Godot 3.3.2
MacOS 11.4

**Comment by Calinou** [comment]
> Is there any update on this?

As far as I know, nobody knows how to resolve this issue.
