### ISSUE TITLE
Editor settings search showing result groups that are empty

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#44728]
3.2.3 - Windows.

Open Editor Settings.

In the search box at the top, type:
`deb`

1) The left column will have many of the fields disappear, however most of the ones that remain are empty if you click on them!

2) Of the ones that are not empty, some I can't fathom how they have "deb" in them:
`Interface > Editors > Derive Script Globals By Name` for example, along with the `3D Gizmos` entry

**Comment by VedatGunel** [comment]
Tested in 3.2.4 beta 4, seems to be fixed. See #41702.

**Comment by Calinou** [comment]
Closing per @VedatGunel's comment.
