### ISSUE TITLE
Unable to initialize video driver

### ISSUE THREAD

**Issue by AaryanGamez** [godotengine/godot#44742]
Hello there, I needed some help. I am currently working on a fps game and whenever I play my game the engine gives me the error saying "Unable to Initialize Video Driver".

Godot version: 3.2.3 stable release

I don't know why it happens even though my opengl version supports both goes 3 and goes yet I get these errors, please help if you can.

**Comment by allkhor** [comment]
Please fill the issue template with the relevant information.  Without this information developers can't help you.

**Comment by AaryanGamez** [comment]
Umm...... Somehow the game started running so I am closing this
