### ISSUE TITLE
glTF importer fails to apply "normalized" accessor parameter

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#44744]
**Godot version:**

v3.2.3.stable.official
v3.2.4.beta.custom_build.74512fd8765782ba6e12c3816966e2313833a81f
v4.0.dev (783ec77dbfbd3d94a79b14dadbfd6caa37e65334)

**OS/device including version:**

Ubuntu 18.04, GLES3 (v3.2.3.stable.official)
Windows 10, GLES3/Vulkan (for v3.2.3.stable.official and the others)

**Issue description:**

Since (at least) Blender 2.91, the export glTF plugin exports vertex colors using the "normalized" accessor parameter. This parameter, if true, serves to announce that the data needs to be normalized before using it. [(link to the definition)](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#accessornormalized)

For my project using PS1-style shaders, I intend to use vertex colors instead of textures for a lot of models, and as a custom shader must be applied, I cannot use standard materials. Therefore, I want to rely on the vertex colors set in Blender.

For this example, I will use my simple test model. It uses only vertex colors, no material is present in the file. The .glb and .gltf files of this example are present in the uploaded Godot minimal examples (in assets/models/).

Here is what my simple test model in glTF viewers:
![normal-import](https://user-images.githubusercontent.com/270928/103198756-257b8880-48b7-11eb-98e8-b1bbcacdc071.png)

Here is what the model looks like in Godot 3.2 (it looks the same on 4.0; one sphere is the .glb, the other is the .gltf file; and I set the shading to unshaded for the demonstration):
![glitched-import](https://user-images.githubusercontent.com/270928/103198833-5065dc80-48b7-11eb-89d4-fb7ea6275357.png)

When I print the vextex color data for each vertex, the data that shows up match the displayed sphere in Godot, not the gltf (or glb) file.

**Steps to reproduce:**
- Import a .gltf or .glb file with one of their accessors having the parameter "normalized" set to true.

**Minimal reproduction project:**

[issue-import-accessor-normalized-parameter-4.0.zip](https://github.com/godotengine/godot/files/5746289/issue-import-accessor-normalized-parameter-4.0.zip)
[issue-import-accessor-normalized-parameter-3.2.zip](https://github.com/godotengine/godot/files/5746290/issue-import-accessor-normalized-parameter-3.2.zip)

**Comment by akien-mga** [comment]
Fixed by #44745.
