### ISSUE TITLE
Type save function returned Type missmatch, 

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#44749]
**Godot version:**
Godot Engine v3.2.3.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 980/PCIe/SSE2

**OS/device including version:**
Windows 10 x86

**Issue description:**
The returned type does not match the function signature.
If a function defines a return type, e.g. `func foo () -> int` then I expect the returned type to be an  `int` or at least an error should be generated.

**Steps to reproduce:**
```
func value() -> int:
	var value = 2.1234
	return value


func test_return_type():
	var type = typeof(value())
	prints(value(), type == TYPE_INT, type == TYPE_REAL)
```
the output:
```
2.1234 False True
```
But i would expect
```
2 True False
```

The returned value is still an float, the function signature return type is ignored.

I am aware that not all types of autocast can be used. But it would be nice if at least basic build-in types supported auto cast.

**Minimal reproduction project:**
see steps to reproduce

**Workaround**
It needs to cast the value manually
```
func value() -> int:
	var value = 2.1234
	return value as int
```

**Comment by KoBeWi** [comment]
Fixed in 4.0
