### ISSUE TITLE
Online/Web Editor Default Project Directory is bad

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#44754]
**Godot version:**

Godot Web Editor 3.2.4 beta 4 https://godotengine.org/editor/latest/godot.tools.html (Currently b5e8b48bb)

**OS/device including version:**

Windows 10 1909, Google Chrome

**Issue description:**

the Default Path When Creating a new Project is "/home/web_user" however creating a new project at "/home/web_user/New Game Project" results in the new going bye bye the moment it is created.

Default Path Should be "/home/web_user/projects" instead of "/home/web_user" as "/home/web_user/projects" keeps the projects and doesn't instantly discard them.

**Steps to reproduce:**
1. Load the Web Editor, Make a New project with the default path
2. Wait like a second, after that the New project will be missing

**Minimal reproduction project:**

Cannot make MRP

**Comment by Faless** [comment]
Yeah, I can  confirm this. It was originally done to avoid storing the cache in the IndexedDB to save space, but in the end I opted to include it too (so opening projects is faster).
I'll try to come up with a better solution for the next version. I wonder if we can add boundaries to the project manager too (so it won't allow creating a project in `/home/MyProject` either).
