### ISSUE TITLE
Online/Web Editor Navigation breaks mouse cursor

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#44755]
**Godot version:**

Godot Web Editor 3.2.4 beta 4 https://godotengine.org/editor/latest/godot.tools.html (Currently b5e8b48)

**OS/device including version:**

Windows 10 1909, Google Chrome

**Issue description:**

When Holding Mouse Button to Look around the scene, like in the offline editor, once the button is no longer held, The Cursor doesn't come back, forcing the user to use esc to free the Cursor, which is an annoyance

**Steps to reproduce:**
1. Make/Load a project
2. Try looking around with the cursor
3. Stop holding the mouse button
4. Notice how the Cursor doesn't come back
5. Press Esc to Get the Cursor back

**Minimal reproduction project:**

Cannot make MRP

**Comment by Calinou** [comment]
> 2. Try looking around with the cursor

By "looking around with the cursor", you mean using 3D freelook?

**Comment by Faless** [comment]
Confirmed on Firefox 84.0 / Ubuntu 20.04 looking around a 3D scene with the mouse.

**Comment by mrjustaguy** [comment]
Yea, it's the Right Mouse Button, for rotating The camera, not the middle mouse button that's Blender like rotation.
