### ISSUE TITLE
InputMapEditor control is not updated when adding actions in tool mode

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#44776]
**Godot version:**

3.2.3

**OS/device including version:**

Windows

**Issue description:**

```gdscript
tool
extends Control

func _ready():
    InputMap.add_action("test")
    print (InputMap.has_action("test"))
```
After running this, I can see
```
True
```
In Output
But  I don't see new action in `InputMap` list (`Project`-`ProjectSetting`-`InputMap`).

And when I reopen the project, the input data (new test action) is lost.

**Steps to reproduce:**
1. Create a project
2. Create a node (in this example I use `Control`) and attach the script above.
3. Save the script and reopen the scene (for triggering the Control `_ready()`)
now `True` should be printed in Output
4. Select `Project` - `ProjectSettings` - `InputMap` to open InputMap window.
As you can see, new `test` action is not added.

**Minimal reproduction project:**

**Comment by AnidemDex** [comment]
Still happens in Godot 3.4.2

**Comment by AnidemDex** [comment]
Additional note: You can add actions from plugins, but they're only visible when you restart the editor

**Comment by alazifk** [comment]
Same thing happens in Godot 4.0. `InputMap.add_action()` appears to be broken.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/25865.
