### ISSUE TITLE
Issues with the new 3d navigation gizmo selection box

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#44779]
**Godot version:**
3.2.4.beta4 and 4.0 master

**OS/device including version:**
Win10 960m and 1060

**Issue description:**
I am finding several problems with the new 3d gizmo bounding/selection box. 

I think that it is quite distracting when editing materials on a mesh, since as far as I can tell it can't be disabled. The old selection bounding box was quite subtle and did not tend to cross over a selected mesh. I have been creating a lot of semi transparent shaders and having the prominent box all around your model means you can see the box lines through the mesh, which is very distracting. I tend to turn off all gizmos and grids when doing transparent materials, but the transform gizmo is the one thing that can't be turned off.

To add to that, there is weirdness in the way that box lines in front of a semi transparent mesh actually look like they are behind the mesh as can be seen here (material alpha is set at 235):

![transparent](https://user-images.githubusercontent.com/7741669/103255948-6969ad00-49df-11eb-8339-5b71b200d43e.gif)

The new selection box is also scaling up and down when adjusting the range control on an omni light which is an unnecessary visual distraction. The old subtle box used to stay put. Not sure why we even need a bounding box on lights, cameras and spatials, etc? The new vs old light range adjustment can be seen here:

![omni_new](https://user-images.githubusercontent.com/7741669/103256105-13493980-49e0-11eb-814f-76bb96160dc7.gif)

![omni_old](https://user-images.githubusercontent.com/7741669/103256150-3ecc2400-49e0-11eb-9d4a-971c3a7c6648.gif)

Additionally, when grouping many nodes under a spatial node, upon selecting the parent there is now a very prominent bounding box which seems visually distracting...to me at least. Especially if the child nodes are not meshes, such as lights, spatials or cameras. The old vs new can be seen in this image.

![spatial_selection](https://user-images.githubusercontent.com/7741669/103256224-80f56580-49e0-11eb-9ca2-4dfea8dea64d.jpg)

I can understand that this new bounding box style can be useful in some situations, such as selection of an object within a dense scene, where it will stand out better. However there should be a way of either toggling it on/off or some way of adjusting the color and opacity of it in the editor settings.

Maybe I am missing something, but as far as I can tell, in the editor settings>gizmo colors panel, there is no setting for transform gizmo selection box? Likewise Editors>3d>manipulator gizmo opacity does not seem to do anything.

Also in the 3d viewport menu View>Gizmos there is an option to hide every other gizmo type other than the transform gizmo ,which seems like an oversight. In every 3d package I have ever used there is a hotkey or way to toggle on and off the transform gizmo, as it can be a visual distraction when texturing or rigging/animating.

**Comment by Calinou** [comment]
> Not sure why we even need a bounding box on lights, cameras and spatials, etc? 

If Spatials didn't have a bounding box when selected, then you wouldn't be aware of their position when selected.

**Comment by fracteed** [comment]
@Calinou damn you are fast...thanks for that new commit! I assume the alpha of the color for this will effect the box opacity in the viewport?

What do you think about the need for a way to toggle on/off the whole transform gizmo, as can be done with the other gizmos?

**Comment by Calinou** [comment]
> I assume the alpha of the color for this will effect the box opacity in the viewport?

Yes, that's why I left the color's alpha property editable.

> What do you think about the need for a way to toggle on/off the whole transform gizmo, as can be done with the other gizmos?

To be fair, when **Show Gizmos** is disabled in the Perspective menu, the selection box should probably be hidden as well.

**Comment by fracteed** [comment]
Agreed. And it should also hide the central part of the gizmo with the axis arrows or rotation rings. This is especially important when previewing/creating materials. There should also be the ability to disable the entire gizmo (arrows and box) in the view>gizmos menu.
