### ISSUE TITLE
[3.2.4 Beta 4]  When I use a AnimatedTexture in the NinePatchRect, it gives the error.

### ISSUE THREAD

**Issue by oknpk** [godotengine/godot#44770]
**Godot version:** 3.2.4 Beta 4 Mono

**OS/device including version:** Windows 10 / Gtx 960 / GLES2,GLES3

**Issue description:**

When I use a **AnimatedTexture** in the **NinePatchRect**, it gives the error in the screenshot. AnimatedTexture isn't visible.
**(It works fine in version 3.2.3.)**

![image](https://user-images.githubusercontent.com/64914195/103239384-637fb780-495e-11eb-8088-fb3ebec3a02d.png)
![image](https://user-images.githubusercontent.com/64914195/103239397-6bd7f280-495e-11eb-80ad-dfbc234ef841.png)

**Steps to reproduce:**

1. Open any project or create a new one
2. Create a User Interface
3. Add NinePatchRect
4. Assign a new AnimatedTexture 
![image](https://user-images.githubusercontent.com/64914195/103239816-b9a12a80-495f-11eb-9fdc-0c5f7c83eaae.png)
5. Assign any image 
![image](https://user-images.githubusercontent.com/64914195/103239907-f79e4e80-495f-11eb-9435-dc747b931a3e.png)

**Minimal reproduction project:**

[ucikidort.zip](https://github.com/godotengine/godot/files/5748620/ucikidort.zip)

**Comment by Calinou** [comment]
@oknpk Can you reproduce this after disabling batching in the Project Settings? Make sure to restart the editor after disabling batching.

cc @lawnjelly

**Comment by mrjustaguy** [comment]
I Reproduced it on the Web Editor, Turning Off Batching helped.

**Comment by oknpk** [comment]
> @oknpk Can you reproduce this after disabling batching in the Project Settings? Make sure to restart the editor after disabling batching.
> 
> cc @lawnjelly

I turned off the batching. It worked

**Comment by lawnjelly** [comment]
K will take a look tomorrow! :+1:

**Comment by akien-mga** [comment]
Fixed by #44790.
