### ISSUE TITLE
godot_is_instance_valid prevents GDNative module from loading

### ISSUE THREAD

**Issue by blocktaster** [godotengine/godot#44774]
**Godot version:**

3.2.3-stable

**OS/device including version:**

Intel i5-7400
Ubuntu 20.04.1 LTS

**Issue description:**

When I use a the function godot_is_instance_valid(...) anywhere in my GDNative module, Godot will refuse to load the module and returns a bunch of failure messages.

**Steps to reproduce:**
make a C++ GDNative module
add this line, godot_is_instance_valid(nullptr); , in some custom class in some function (for ex., _init(), although it appears to break no matter where it's placed)
compile
link compiled binary as a GDNative module to Godot

**Comment by Calinou** [comment]
@blocktaster Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by blocktaster** [comment]
found solution. It needs to be called like this:
godot::core_1_1_api->is_instance_valid(...)
