### ISSUE TITLE
FBX version of file is unsupported.

### ISSUE THREAD

**Issue by ricardoalcantara** [godotengine/godot#44780]
**Godot version:**

Godot Engine v3.2.4.beta4.mono.official

**OS/device including version:**

Windows 10 Home
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL ES Batching: ON

**Issue description:**

Cannot import https://syntystore.com Character models, the problem is only with the character.

Cannot import file: res://Test/SK_Chr_Soldier_Female_01.fbx version of file is unsupported, please re-export in your modelling package file version is: 7200
Cannot import file: res://Test/SK_Chr_Soldier_Male_01.fbx version of file is unsupported, please re-export in your modelling package file version is: 7200

However if I convert it using the AutoDesk Tool https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives It imports.

Maybe not a real bug, better you guys judge it.

**Steps to reproduce:**
It's required to have a syntstore character assets.

**Minimal reproduction project:**

Cannot public provide one.

**Comment by akien-mga** [comment]
As the message says, this FBX format is unsupported, so converting it to a newer format *is* the proper solution. You could notify Syntystore about it so that they can consider re-exporting it in a newer format.

Version 7200 is 7.2, from 2012. That's an 8 year old FBX format.
