### ISSUE TITLE
Godot FTBFS: No such file or directory: 'platform/flash/logo.png'

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4479]
scons: Reading SConscript files ...
IOError: [Errno 2] No such file or directory: 'platform/flash/logo.png':
  File "/home/slapin/godot/SConstruct", line 54:
    methods.save_active_platforms(active_platforms,active_platform_ids)
  File "/home/slapin/godot/methods.py", line 1363:
    pngf=open(pth,"rb");

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/4441#issuecomment-214977951

You need to delete the folders ``platform/flash`` and ``platform/nacl`` that are leftovers in your local clone (but are no longer in git).

**Comment by slapin** [comment]
Thanks!
I think some script cleanup is required for this to not happen in future though.

**Comment by akien-mga** [comment]
I guess we should just change the code that parses all folders in ``platform`` to determine the list of platforms, so that it ignores folders without a ``SCsub`` file (like it does for modules).
