### ISSUE TITLE
PacketPeer.put_packet returns invalid non-zero Error

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#44804]
**Godot version:**
4.0 edccc0bbdffe3175e41358e4d85bcd50b6f04d8e

**OS/device including version:**
Microsoft Windows [Version 10.0.19041.685]

**Issue description:**
put_packet returns an Error value whose lower 32 bits are 0, but higher 32 bits seem arbitrary.

Generally, Error codes should be between 0 and 100 or so, based on enum values, so this behavior seems wrong

**Steps to reproduce:**
1. Run a copy of the project.
2. Click Host
3. Run another copy of the project
4. Click Connect
5. The status bar at the bottom will display two numbers.

What I want: The status bar should show 0 / 0 (indicating Error.OK)

What I see instead: Due to this bug, it shows numbers which are not 0. This is disruptive to code which attempts to check == Error.OK

The higher 32 bits seem to disappear and become 0 depending on which operations are applied to the Error result in GDScript.
<img width="1541" alt="error_code_invalid" src="https://user-images.githubusercontent.com/39946030/103330078-c2076d00-4a14-11eb-9d13-5bde05704d62.png">

**Minimal reproduction project:**
[SimpleNetworkTest.zip](https://github.com/godotengine/godot/files/5753037/SimpleNetworkTest.zip)

**Comment by lyuma** [comment]
diagnosing this further, I suspect this to be a GDScript bug actually so I'm going to ping @vnen 

Of note, the fact that both numbers are displayed are not the same... when this "corrupted" Error code is combined in n expression or stored in a variable, its value mysteriously changes to 0.

Also, while reading the networking code implementing put_packet and send_peer, I can't see how it returns anything other than Error.OK (0) in most cases...

**Comment by SaracenOne** [comment]
ConfigFile.load also seems to have this issue

**Comment by Calinou** [comment]
> ConfigFile.load also seems to have this issue

Can you reproduce this in `master` only or in 3.3.2 as well?

**Comment by lyuma** [comment]
To be clear, we have only seen this issue on master. @SaracenOne was using master, too.

**Comment by lyuma** [comment]
ran into the problem again today, this time with PackedScene.pack():

```gd
	var packed_scene: PackedScene = PackedScene.new()
	err = packed_scene.pack(scene_root)
	if err == OK:
		...
```
err is 1795296329728 which is 0x1a200000000

I'm on godot master 953de68

**Comment by Calinou** [comment]
I also ran into this problem with `Image.save_png` yesterday.

**Comment by Faless** [comment]
> Looks like this applies to any use of the Error type?

Yeah, I've see that in general when getting an Error value, and I think I'm also experiencing this with other enum types (`MultiplayerPeer.ConnectionStatus` in my case).

**Comment by timothyqiu** [comment]
#50435 might be suffering the same cause. A `false` variant becomes a `true` bool after going through the `ptrcall` / `PtrToArg` process in a build with  sanitizers.
