### ISSUE TITLE
KEY_KP_PERIOD not selectable in project settings

### ISSUE THREAD

**Issue by egore** [godotengine/godot#44801]
**Godot version:**
v3.2.3.stable.flathub

**OS/device including version:**
Arch Linux on Gnome desktop using de_DE nodeadkeys

**Issue description:**
When trying to assign numpad period to any action in the project settings it is not registered. Manually adding the keycode in project.godot to (manually calculated) 16777348 causes the project file to no longer being able to load.

**Steps to reproduce:**
- Open project settings
- Switch to input tab
- Try to assign keypad period to any action

**Minimal reproduction project:**
It works on any project.

**Comment by Calinou** [comment]
Can you reproduce this when using an `en_US` keyboard layout?

**Comment by egore** [comment]
@Calinou Unfortunately I'm no longer able to reproduce the issue at all. I've switched back and forth between en_US and de_DE layouts trying to reproduce it, but it no longer happens.
