### ISSUE TITLE
Need some way to identify collision shapes created using CollisionShape node

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4480]
When using complex 3D setups you basically need to know what part of collision your shape represents. For example, your character can walk, lay on sofa, sit on chair. All these poses (and transitions!) require different collision setups to avoid unwanted behavior. Another example is multi-character animations, where we want to selectively disable collision bodies. Or, entering a car.

To select a body to disable or move you need to identify it. You can loop through bodies in collision object, but you can't identify which is which. Ref<Shape> do not know about names.
one can set names for shapes in GDScript, but not in C++ for some reason. Or do I do something wrong? This is serious issue, basically a show stopper.

**Comment by slapin** [comment]
Godot seriously changed since this bug was submitted. Now there is multiple ways to identify collision shape which triggered (with addition of runtime CollisionShape node). There is a lot of improvement possible in this area (store shape id in CollisionShape node?) but is is definitely no longer show stopper. So expressed like this, this issue can be closed, if you want to.

**Comment by akien-mga** [comment]
Thanks, closing then, as further improvement discussions would likely get better visibility in a new issue.
