### ISSUE TITLE
Screenshot in master only takes one screenshot

### ISSUE THREAD

**Issue by fire** [godotengine/godot#44811]
**Godot version:**
https://github.com/godotengine/godot/commit/b24f9f2d8f060533f2dff16c73bf93c94f23fbdf

**OS/device including version:**
win10, vulkan, nvidia

**Issue description:**
Wanted to take a screenshot of the editor. The second screenshot fails.

**Steps to reproduce:**
1. Take the second screenshot
2. The result is the same as the first screenshot

**Minimal reproduction project:**
Any project.

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/b24f9f2d8f060533f2dff16c73bf93c94f23fbdf (Linux, NVIDIA).

**Comment by pycbouh** [comment]
Take note that this only happens in the editor. The same exact approach works correctly with user projects. Code samples and test projects available in #45898.

**Comment by fire** [comment]
Fixed by https://github.com/godotengine/godot/pull/54427
