### ISSUE TITLE
GDScript static typing (release mode): Could not infer the type because the initial value is "null"

### ISSUE THREAD

**Issue by Demindiro** [godotengine/godot#44829]
**Godot version:**
`4.0.dev.custom_build.41e902886` 41e902886

**OS/device including version:**
`Linux pc 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`

**Issue description:**
When trying to assign `OS.get_ticks_msec()` to a variable with `:=`, the parser throws `Could not infer the type of the variable "msec" because the initial value is "null".`. This maybe also happening with other methods but I haven't checked yet. This only happens in release builds.

```
...
ERROR: Condition "register_funcs.has(p_name)" is true.
   at: add_register_func (modules/visual_script/visual_script.cpp:2711)
ERROR: Condition "register_funcs.has(p_name)" is true.
   at: add_register_func (modules/visual_script/visual_script.cpp:2711)
SCRIPT ERROR: Parse Error: Could not infer the type of the variable "msec" because the initial value is "null".
          at: GDScript::reload (res://main.gd:5)
SCRIPT ERROR: Parse Error: Invalid operands "null" and "null" for "-" operator.
          at: GDScript::reload (res://main.gd:6)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:832)
```

**Steps to reproduce:**
```gdscript
extends Node

func _ready():
	var msec := OS.get_ticks_msec()
	print(OS.get_ticks_msec() - msec)
```
**Minimal reproduction project:**
[get_ticks_msec_null.zip](https://github.com/godotengine/godot/files/5756132/get_ticks_msec_null.zip)

**Comment by Demindiro** [comment]
I suspect it's related to #44411

**Comment by Demindiro** [comment]
I also get `SCRIPT ERROR: Parse Error: Invalid get index "quit" on base Nil` when trying to use `get_tree().quit()`. I guess it's related?

**Comment by qarmin** [comment]
Error doesn't show with 4.0.dev.custom_build. 759b876b8
