### ISSUE TITLE
TileSet's _forward_subtile_selection expects returning either Vector2 or null, which is incompatible with statically-typed languages like C#

### ISSUE THREAD

**Issue by FalseLobster** [godotengine/godot#44823]
**OS:** Windows 10
**Godot Version:** I'm on 3.2.2, but I think this repros on the master branch as well.

**Issue Description**
I've been working on a more nuanced autotiler script for my TileSet and I primarily use C# with Godot.  I was looking at other uses of _forward_subtile_selection since it isn't well documented, but it is awkward to use in C# compared to gdscript.  Because of C#'s static typing and the way this function is projected, there's no way to "opt out" of overriding the behavior once you've added a script with the function.

Here's how it's used in the engine code:

```cpp
Vector2 TileSet::autotile_get_subtile_for_bitmask(int p_id, uint16_t p_bitmask, const Node *p_tilemap_node, const Vector2 &p_tile_location) {
	ERR_FAIL_COND_V(!tile_map.has(p_id), Vector2());
	//First try to forward selection to script
	if (p_tilemap_node->get_class_name() == "TileMap") {
		if (get_script_instance() != nullptr) {
			if (get_script_instance()->has_method("_forward_subtile_selection")) {
				Variant ret = get_script_instance()->call("_forward_subtile_selection", p_id, p_bitmask, p_tilemap_node, p_tile_location);
				if (ret.get_type() == Variant::VECTOR2) {
					return ret;
				}
			}
		}
	}
	
	// default behavior follows here
```

If you look at how others have used this function in gdscript, you might run into [this example](https://www.reddit.com/r/godot/comments/gl2t00/wrote_a_script_to_extend_autotile_functionality/)

which mentions:

```py
func _forward_subtile_selection(autotile_id, bitmask, tilemap, tile_location):
	# This func is called on each tile after the bitmask has been determined,
	# to get the coord of the subtile texture to be used
	# (if no return, fall back to default behaviour)
```

As mentioned here a "no return" falls back to the default behavior, and you can see in the engine code above, one must return a *non-Vector2* type to fall back to default behavior.  This is hard to accomplish with how this function is projected in C#:

```cs
[GodotMethodAttribute("_forward_subtile_selection")]
public virtual Vector2 _ForwardSubtileSelection(int autotileId, int bitmask, Object tilemap, Vector2 tileLocation);
```

because C# won't let you return nothing like gdscript, one has to find some other way to work around the C# type checking and marshal a non-Vector2 type to the native code.  This *might* be possible using C#'s `unsafe` and creating another Godot type and "reinterpret_cast"-ing it to a Vector2 somehow.  Barring that, you'd have to reimplement the entire `autotile_get_subtile_for_bitmask` C++ function in C#, assuming that's possible, if you don't want your script to override the behavior for a specific autotile.

**Comment by FalseLobster** [comment]
I don't know much about how Godot marshal's C#'s representation of the Godot types into the C++ Variant type, but making the return type nullable (`Vector2?`) would make sense to me or using some "Invalid subtile coordinate constant" like (-1, -1).

**Comment by KoBeWi** [comment]
"No return" in GDScript defaults to Variant::Nil. This is not really a problem with C# but with the implementation of  `_forward_subtile_selection`. It should never expect *any Variant* type, to be compatible with other, potentially statically-typed, languages. Vector2(-1, -1) sounds like a good idea for the opt out value.
CC @groud because he is rewriting TileSets currently.

btw what happens when you change the method declaration? Does C# have generic Variant type?

**Comment by FalseLobster** [comment]
You can't change the method declaration-- the function is projected as returning a Vector2 and if you want to override it you must match the way it's declared in the metadata found in the GodotSharp.dll binary.  Here's what ildasm says about it, note the valuetype Godot.Vector2 return.

```
.method public hidebysig newslot virtual 
        instance valuetype Godot.Vector2 
        _ForwardSubtileSelection(int32 autotileId,
                                 int32 bitmask,
                                 class Godot.Object tilemap,
                                 valuetype Godot.Vector2 tileLocation) cil managed
{
  .custom instance void Godot.GodotMethodAttribute::.ctor(string) = ( 01 00 1A 5F 66 6F 72 77 61 72 64 5F 73 75 62 74   // ..._forward_subt
                                                                      69 6C 65 5F 73 65 6C 65 63 74 69 6F 6E 00 00 )    // ile_selection..
  // Code size       15 (0xf)
  .maxstack  1
  .locals init (valuetype Godot.Vector2 V_0,
           valuetype Godot.Vector2 V_1)
  IL_0000:  nop
  IL_0001:  ldloca.s   V_0
  IL_0003:  initobj    Godot.Vector2
  IL_0009:  ldloc.0
  IL_000a:  stloc.1
  IL_000b:  br.s       IL_000d
  IL_000d:  ldloc.1
  IL_000e:  ret
} // end of method TileSet::_ForwardSubtileSelection
```

**Comment by FalseLobster** [comment]
Essentially the function is non-functional in C# because you have deep understanding of how Godot.Object / primitive types get marshalled to the native Variant and subvert C#'s static typing, assuming that's even possible.

I worked around it by writing my override in gdscript

**Comment by akien-mga** [comment]
That's a weird API and might be worth refactoring, but otherwise the return type should be `Variant` if it expects either a `Vector2` or `Nil` (both of which are Variants).

**Comment by FalseLobster** [comment]
Since C# doesn't use Variant that would mean boxing the value like `System.Object(null)` or `System.Object(new Vector2(x, y))` right?

**Comment by Scripptor** [comment]
API is worth refactoring! 
Simply overriding like so breaks the functionality:
```csharp
    public override Vector2 _ForwardSubtileSelection(int autotileId, int bitmask, Godot.Object tilemap, Vector2 tileLocation)
    {
        return base._ForwardSubtileSelection(autotileId, bitmask, tilemap, tileLocation);
    }
}
```
Someone please fix, I prefer programming in C#!

**Comment by neikeq** [comment]
The easiest solution is to modify the virtual method bind to correctly specify it expects Variant, which would be generated as System.Object in C#. Problem with that is returning a Vector2 would result in boxing. A better option would be for the scripting API to support nullable types, but that's more complicated.

**Comment by FalseLobster** [comment]
I'd consider submitting a PR if I knew where this happens:

> modify the virtual method bind to correctly specify it expects Variant

**Comment by FalseLobster** [comment]
Alternatively I could update the engine to check for (-1, -1) in a backward compatible way, too, if that feels more canonical.  Do the folks more active in maintaining this have a stylistic preference here?

**Comment by neikeq** [comment]
> I'd consider submitting a PR if I knew where this happens:
> 
> > modify the virtual method bind to correctly specify it expects Variant

Here: https://github.com/godotengine/godot/blob/49122588391b5159fada6d33f136d169b5a01ae5/scene/resources/tile_set.cpp#L1156

To make it return Variant you need to set the first parameter of `BIND_VMETHOD` to `Variant::NIL` and set `PROPERTY_USAGE_NIL_IS_VARIANT`. Here's an example of how to do the latter: https://github.com/godotengine/godot/blob/e1e52b3736c34ba48cbcb3c62c967c035f5a2818/editor/plugins/node_3d_editor_plugin.cpp#L7470-L7472

**Comment by FalseLobster** [comment]
@neikeq I made the change you suggested and have been following along with the compiling with mono instructions.  After generating the glue I do see that

```
// godot\modules\mono\glue\GodotSharp\GodotSharp\Generated\GodotObjects\TileSet.cs

[GodotMethod("_forward_subtile_selection")]
public virtual object _ForwardSubtileSelection(int autotileId, int bitmask, Object tilemap, Vector2 tileLocation)
{
    return default(object);
}
```

Since the return type is `object` that looks like progress, but after building the final mono-enabled binary, I can't build a simple test project because the final binary still thinks the return type is Vector2.  I'm assuming I'm missing something obvious here but I'm not sure what.  Here's the steps I'm running:

```
scons -j8 platform=windows tools=yes module_mono_enabled=yes mono_glue=no
bin\godot.windows.tools.64.mono.exe --generate-mono-glue modules\mono\glue
scons -j8 platform=windows tools=yes module_mono_enabled=yes mono_glue=yes
start bin\godot.windows.tools.64.mono.exe
```

I'm not sure if this is really worth pursuing for one of the 3.x stable branches since gdscript works fine and it looks like @groud has completely replaced autotiles on master so I'm going to close this issue, but I'd love to know if you have any thoughts on what I did wrong so that I might learn more about how to build & test godot w/ mono.
