### ISSUE TITLE
Maximum negative integer value can't be set

### ISSUE THREAD

**Issue by podpathos** [godotengine/godot#44826]
**Godot version:**
3.2.4-beta4

**OS/device including version:**
Windows 10

**Issue description:**
Documentation says that int is in range [-9223372036854775808, 9223372036854775807] in decimal, or in hex [8000 0000 0000 0000, 7fff ffff ffff ffff), but when I set int value to maximum negative value in decimal (-9223372036854775808) GDScript sets it to **one less** than maximum negative value: -922337203685477580**7** or 8000 0000 0000 0001, and if I set int value to maximum negative in hex (8000 0000 0000 0000) GDScript sets it to maximum **positive** int value 7fff ffff ffff ffff or 9223372036854775807. In either case maximum negative int value cant be set.

**Steps to reproduce:**
```gdscript
func _ready():
	print(-9223372036854775808)
	print(0x8000000000000000)
```

**Comment by mrushyendra** [comment]
I'm guessing this might be due to the same reason outlined in #42289

**Comment by akien-mga** [comment]
Indeed, same issue as #42289.
