### ISSUE TITLE
Apk installation failed with the INSTALL_FAILED_NO_MATCHING_ABIS code

### ISSUE THREAD

**Issue by ICatRegister** [godotengine/godot#44835]
**Godot version:**
3.2.3-stable

**OS/device including version:**
Android 5 - 10

**Issue description:**
If the apk contains a single native image with the arm64-v8a architecture, then installation on many modern devices will fail with the INSTALL_FAILED_NO_MATCHING_ABIS error. In fact, the android decides that the armeabi-v7a image is required. Perhaps a dependency on some library in gradle build is forcing android to load a 32 bit image instead of a 64 bit one? If you load 2 apk, armeabi-v7a and arm64-v8a, into the Google console, you can see that many users have installed the 32-bit version for no reason, even on devices with android 10. For example, here are the devices on which the 32-bit image is guaranteed to be loaded:

Samsung SM-A105F Galaxy A10
Samsung SM-J260M Galaxy J2 Core
Huawei Y3 2017
Huawei Y9 2019
Samsung SM-J500H Galaxy J5

Anyone have any idea what's going on?

**Steps to reproduce:**
Export any empty project with the only arm64-v8a architecture, no plugins or custom build. Try to install and get "App not intalled". On which device it will work, alas, it is not known

**Minimal reproduction project:**
The project doesn't matter, maybe an empty scene

**Comment by akien-mga** [comment]
Are you sure that those phones have both an arm64 CPU *and* a matching arm64 version of Android? I assume some devices might have 64-bit capabilities but run a 32-bit OS, like is possible on desktop.

**Comment by ICatRegister** [comment]
Indeed, these devices still use a 32 bit OS despite the processor architecture. I apologize for the false alarm

**Comment by akien-mga** [comment]
The error is expected then, those devices need an armv7 build.

If distributed in the Play Store, they should normally be flagged as not compatible with the user device.
