### ISSUE TITLE
doctool: Homogenise indentation scheme in the XML

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4483]
The various XML tags in the classes.xml template produced by doctool don't have the same expectations regarding the need for indentation.

For example `<description>` expects no additional indentation level:
```
<description>
Return the label used for built-in text.
</description>
```

While ``<constant>`` expects an indentation:
```
<constant name="NO_INDEX_ARRAY" value="-1">
	Default value used for index_array_len when no indices are present.
</constant>
<constant name="ARRAY_WEIGHTS_SIZE" value="4">
	Amount of weights/bone indices per vertex (always 4).
</constant>
```

Most IDEs seem to increment the indentation level after ``<description>``, or at least 90% of the documentation writers add one, which always gets reverted when running doctool again, producing needlessly verbose diffs.

We need to settle on one convention, implement it in doctool and enforce it.

**Comment by StraToN** [comment]
OK. Which convention do we choose? 
```
<description>
Return the label used for built-in text.
</description>```
or
```
<description>
    Return the label used for built-in text.
</description>
```

**Comment by akien-mga** [comment]
I guess we'd have to use the second convention if we don't want to fight all IDEs that auto-indent after an opening XML tag. Alternatively, if we choose the first convention we'd have to add in the docs that documenters *should* rerun doctool before committing, to ensure they use the proper formatting.

**Comment by StraToN** [comment]
This should be too hard to do. Here's a hint : https://github.com/godotengine/godot/blob/master/tools/doc/doc_data.cpp#L917

**Comment by bojidar-bg** [comment]
Ok, with consideration to https://github.com/godotengine/godot-docs/issues/133, I think it would be nice to actually indent `<description>`, since we will have many other tags that would need text inside as well, e.g. `<long_description>`, `<argument>`, `<returns>`, etc.

But, even in this case, I think it would be better if we apply the change at the same time as introducing long descriptions.
