### ISSUE TITLE
Singleton's cannot be used as const in a module

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#44837]
**Godot version:**
3.2.3

**OS/device including version:**
Linux

**Issue description:**
I know enums don't work very well with singletons/exports but I have the following in an autoload:

```
const COLOURS = { 
	"black" 		: [0.0,0.0,0.0],
	"blue" 			: [0.0,0.0,192.0/256.0]
}
```

If I try to create a constant using it:
```
var y = Globals.COLOURS.blue     #works fine as var
const z = Globals.COLOURS.blue
```

I get error invalid index COLOURS in constant expression.

Maybe this is more a 'feature request', but you would expect autoload variables to be loaded first or at least a script able to know of the autoload's existence as it parses the code...

![image](https://user-images.githubusercontent.com/12863685/103409986-2e8f8280-4b61-11eb-88ef-347c970126b1.png)

**Comment by Calinou** [comment]
A singleton reference is not constant because the first part (`Globals`) is a result of `get_node()`, which itself is not a constant expression.

**Comment by chucklepie** [comment]
I get what you're saying, but constants are "known at compile-time" according to the docs, which implies it is regardless where it is defined, it is simply known at compile time?

So an autoload having a constant means the value is known at compile time. So that implies that a const based off a const is also perfectly valid because that is done at compile time?

**Comment by Omicron666** [comment]
why use globals, when you can do MyClass.MY_CONST

**Comment by KoBeWi** [comment]
Autoloads are just references to a node. They can be modified, removed or replaced, so they can't be const.

However your code will work just fine when you add `class_name`.
