### ISSUE TITLE
Godot debug windows freezes on Windows 10 

### ISSUE THREAD

**Issue by mawoka-myblock** [godotengine/godot#44855]
**Godot version: 3.2.3**

**OS/device including version: Windows 10**

**Issue description:**
If I want to run my project in debug mode the windows freezes but the editor is still working. I tried to start a HTML 5 Server and it says ` Unable to start HTTP server.`. 

**Steps to reproduce:**
Open the project, click on run and enjoy :)

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/5759186/Test.zip)

**Comment by floppyhammer** [comment]
Of course your game freezes when you put an endless while loop in _ready().
