### ISSUE TITLE
GDScript 2.0: Button signal "pressed" cannot be connected because it is seen as bool property `pressed` (name conflict)

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#44877]
**Godot version:**
v4.0.dev.custom_build.41e902886
hash:41e9028868e49669de83c82ba20fd9dcef0d1b8b

**OS/device including version:**
Windows 10

**Issue description:**
When I try to connect a Button's "pressed" signal, it gives an error.
Example:
$Button.pressed.connect(b_pressed)
Error:
"Invalid call. Nonexistent function 'connect' in base 'bool'"

I am fairly certain this is because buttons have signal "pressed" and also a bool "pressed"
The way connect works may have to be tweaked a bit so it doesn't look at bools/variables, but only signals.

**Steps to reproduce**
Load up 4.0, create root node, add a button, add a script with this:
```gdscript
func _ready():
    $Button.pressed.connect(b_pressed)

func b_pressed():
    print("Hello")
```

**Comment by Calinou** [comment]
I can confirm this on commit f1cb475d9.

**Minimal reproduction project:** [gdscript_connect_button.zip](https://github.com/godotengine/godot/files/5760812/gdscript_connect_button.zip)

**Comment by Xrayez** [comment]
Related to #38937.

**Comment by KoBeWi** [comment]
#38937 mentions this issue already and it should be solved by renaming either the property or signal, so this can be closed probably.
