### ISSUE TITLE
Vulkan: Normal maps in 3D don't work

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#44872]
**Godot version:**
[7a16efc](https://github.com/godotengine/godot/commit/7a16efc88596caa5e794d1eb52c599d706b2457c)

**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan

**Issue description:**
Enabling "Normal Maps" on materials doesn't work and leads to render problems, and [spams console with errors](https://gist.github.com/Xartorx/de8bc8ab16c4e0a067f6329006243ceb)

**Steps to reproduce:**

1. Load project
2. Enable "Normal Map" on new_standardmaterial3d.tres material
3. Look at the console

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/5760496/Test.zip)

**Comment by clayjohn** [comment]
Introduced by: https://github.com/godotengine/godot/pull/44614

This line renames ``NORMAL_MAP_DEPTH`` to ``normal_map_depth``
https://github.com/godotengine/godot/blob/ec99c8159ddfd15acccf1ce704593309daa38396/servers/rendering/renderer_rd/renderer_scene_render_forward.cpp#L2871

While the shader expects a variable named ``normal_depth``
https://github.com/godotengine/godot/blob/ec99c8159ddfd15acccf1ce704593309daa38396/servers/rendering/renderer_rd/shaders/scene_forward.glsl#L1858

The solution is to rename the variable in the shader to ``normal_map_depth`` here:
https://github.com/godotengine/godot/blob/ec99c8159ddfd15acccf1ce704593309daa38396/servers/rendering/renderer_rd/shaders/scene_forward.glsl#L1858
and here:
https://github.com/godotengine/godot/blob/ec99c8159ddfd15acccf1ce704593309daa38396/servers/rendering/renderer_rd/shaders/scene_forward.glsl#L1934
