### ISSUE TITLE
viewport unusable in 2d

### ISSUE THREAD

**Issue by awalone995** [godotengine/godot#44881]
**Godot version:**
3.2.4 beta4 mono

**OS/device including version:**
win7 desktop

**Issue description:**
![image](https://user-images.githubusercontent.com/26692947/103467073-28b1c100-4d5c-11eb-8eaf-8bfad63ab05a.png)

container clearly shows as the viewport returns bg color

![image](https://user-images.githubusercontent.com/26692947/103467066-1899e180-4d5c-11eb-831c-8f3849fce907.png)

works in 3d though

![image](https://user-images.githubusercontent.com/26692947/103467013-9ad5d600-4d5b-11eb-9b9d-3a5dce0a76ca.png)

**Minimal reproduction project:**
[view.zip](https://github.com/godotengine/godot/files/5760905/view.zip)

**Comment by Xrayez** [comment]
I find it difficult to understand the problem, what's the expected behavior?

`Camera2D` shifts the view within the viewport itself, but perhaps the behavior is slightly different in 3D.

That said, the `Viewport` in 2D won't display nodes outside of the hierarchy (nodes have to be added directly to `Viewport` for them to be displayed).

**Comment by awalone995** [comment]
>viewport should contain the nodes
not documented anywhere then, also seems like a recent change because not a single forum post mentions that
also you can't do much with such a restriction

**Comment by clayjohn** [comment]
It seems like you benefit from reading the [viewport documentation](https://docs.godotengine.org/en/stable/tutorials/viewports/viewports.html) which explains how viewports work. There is also a whole section in the [Godot-Demos](https://github.com/godotengine/godot-demo-projects/tree/master/viewport) on viewports. Looking through the examples may be helpful for you, you can access them in the asset library from within the godot editor. 

The reason I point to these resources is that, based on Xrayez' comment and your response, you appear to be misunderstanding how Viewports work. If you go through the resources and there still appears to be something wrong, please let us know and we will try to do what we can to fix it.

**Comment by awalone995** [comment]
`misconception` tag please
