### ISSUE TITLE
C#: add generic version of Node.FindNode()

### ISSUE THREAD

**Issue by felixscheffer** [godotengine/godot#44891]
Right now, there is only:

`Node FindNode(string mask, bool recursive = true, bool owned = true);`

Ideally, there would also be a generic version like there is for GetChild() and GetNode().
`T FindNode<T>(string mask, bool recursive = true, bool owned = true) where T : class;`

**Godot version:**
3.2

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the Godot proposals repository. This repository is now used for bug reports only.
