### ISSUE TITLE
C++11 support for linux build - needed to compile creature2d module

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#4490]
I've been trying to build godot with support for creature2d. The author of creature 2d has kindly made a module for godot.

it however needs C++11 support. How do I get godot to compile with c++11 support?
https://github.com/kestrelm/Creature_Godot/issues/1

So far I learned that I need to edit the sconstruct file. This however is much too complicated for me. Help much appreciated!

**Comment by Zylann** [comment]
I'm creating a module to integrate a library that uses C++11 features, and I'd like to know as well how to properly ensure it compiles correctly on all platforms.

**Comment by punto-** [comment]
You don't need to enable it for the whole build, just for your module on
the SCsub, something like this:

module_sources=['file1.cpp', 'file2.cpp']

env_mymodule = env.Clone()
env_mymodule.Append(CXXFLAGS=['--enable-c++11', '-D_SOME_MODULE_DEFINE'])

env_mymodule.add_source_files(env.modules_sources, module_sources)

That will add the compiler flags only to your sources and not to the rest
of the build. Keep in mind that not all compilers use the same flags
obviously (maybe there's a scons option to enable c++11 that is more
portable), the point is whatever you do to that environment won't affect
the rest of the build (which means if you enable or disable the module it
won't trigger a recompile of all the sources, only the ones specifically
affected by your module)

**Comment by blurymind** [comment]
@punto- 
this is the SCsub file:

> # SCsub
> Import('env')
> 
> env.Append(CPPDEFINES=['_USE_MATH_DEFINES'])
> env.Append(CPPPATH='#modules/creaturegodot/glm')
> env.Append(CPPPATH='#modules/creaturegodot/gason')
> env.add_source_files(env.modules_sources,"*.cpp") # just add all cpp files to the build

How do I alter it exactly? I dont have much experience with scons

**Comment by punto-** [comment]
All of those calls can go in a new env (along with the parameter to enable
c++11), since they don't affect the rest of the build

**Comment by blurymind** [comment]
@punto- I can't get it to compile at all. Could you post how you would change his build script so it builds at least?

Getting it to work is more important to me

**Comment by punto-** [comment]
env_module = env.Clone()

then do to "env_module" everything you do to "env", like in my first
example.

**Comment by blurymind** [comment]
@punto- 
Here is the file so far:

> 
> # SCsub
> Import('env')
> 
> env_module = env.Clone()
> env_module.Append(CPPDEFINES=['_USE_MATH_DEFINES'])
> env_module.Append(CPPPATH='#modules/creaturegodot/glm')
> env_module.Append(CPPPATH='#modules/creaturegodot/gason')
> env_module.Append(CXXFLAGS=['--enable-c++11', '-D_SOME_MODULE_DEFINE'])
> env_module.add_source_files(env.modules_sources,"*.cpp") # just add all cpp files to the build

it fails to build with this error:

> scons: Building targets ...
> g++ -o modules/creaturegodot/register_types.x11.tools.64.o -c --enable-c++11 -D_SOME_MODULE_DEFINE -g2 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -DOC_X86_ASM -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DOPENGL_ENABLED -DGLEW_ENABLED -DALSA_ENABLED -DJOYDEV_ENABLED -DPULSEAUDIO_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DGLES_OVER_GL -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DPNG_ARM_NEON_OPT=0 -D_REENTRANT -D_USE_MATH_DEFINES -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/x11 -I/usr/include/freetype2 -Imodules/creaturegodot/vorbis -Imodules/creaturegodot/glm -Imodules/creaturegodot/gason modules/creaturegodot/register_types.cpp
> cc1plus: error: unknown pass c++11 specified in -fenable
> scons: *** [modules/creaturegodot/register_types.x11.tools.64.o] Error 1
> scons: building terminated because of errors.
> 
>

**Comment by blurymind** [comment]
I am using this version of g++ btw:

g++ --version
g++ (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413

**Comment by blurymind** [comment]
@punto- 
Using this line:
env_module.Append(CXXFLAGS=['--std=c++11'])

still fails to compile the module.

**Comment by punto-** [comment]
yeah, --enable-c++11 is just an example I made up, you have to find the
right option..

**Comment by blurymind** [comment]
I tried numerous different options and nothing seems to do it :(

**Comment by akien-mga** [comment]
What's the error with ``--std=c++11``? It's the proper tag for gcc, so there error should be different than the one with ``--enable-c++11`` where it parsed it as a gcc ``--enable-stuff`` standard option.

**Comment by Kazuo256** [comment]
The tag for C++11 in gcc is actually `-std=c++11`, with only a single `-`.

I have managed to compile a module in C++11 for Godot before, but it was not easy since some of Godot's headers are not C++11 compatible. I had to make a C++99 wrapper of my module.

**Comment by akien-mga** [comment]
> The tag for C++11 in gcc is actually ``-std=c++11``, with only a single ``-``.

Oh you're right! So @blurymind, try:
```
 env_module.Append(CXXFLAGS=['-std=c++11'])
```

**Comment by punto-** [comment]
If you keep the c++11 flag only to your module, you shouldn't have a
problem with the rest of the headers of the engine..

**Comment by Zylann** [comment]
If the compiler is different, what is the good practice? Is there an if to write with two different flags?

**Comment by blurymind** [comment]
@punto- , @akien-mga  Thank you for the help so far. It still fails to compile unfortunately.

this is the SCsub file of the creature module so far:

> # SCsub
> Import('env')
> 
> env_module = env.Clone()
> env_module.Append(CPPDEFINES=['_USE_MATH_DEFINES'])
> env_module.Append(CPPPATH='#modules/creaturegodot/glm')
> env_module.Append(CPPPATH='#modules/creaturegodot/gason')
> env_module.Append(CXXFLAGS=['-std=c++11'])
> env_module.add_source_files(env.modules_sources,"*.cpp") # just add all cpp files to the build

and this is the compile error message (the last few lines - as it is long):

> .....
> In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
>                  from modules/creaturegodot/glm/detail/setup.hpp:616,
>                  from modules/creaturegodot/glm/detail/type_int.hpp:32,
>                  from modules/creaturegodot/glm/fwd.hpp:32,
>                  from modules/creaturegodot/glm/glm.hpp:88,
>                  from modules/creaturegodot/MeshBone.h:44,
>                  from modules/creaturegodot/CreatureModule.h:41,
>                  from modules/creaturegodot/creaturegodot.h:7,
>                  from modules/creaturegodot/register_types.cpp:5:
> modules/creaturegodot/glm/./gtx/simd_vec4.inl: In member function 'glm::detail::fvec4SIMD& glm::detail::fvec4SIMD::swizzle()':
> modules/creaturegodot/glm/./gtx/simd_vec4.inl:178:3: error: function template-id 'mask<((((W << 6) | (Z << 4)) | (Y << 2)) | (X << 0))>' in nested-name-specifier
>    mask<(W << 6) | (Z << 4) | (Y << 2) | (X << 0)>::value);
>    ^
> In file included from /usr/include/glm/detail/func_integer.hpp:232:0,
>                  from /usr/include/glm/integer.hpp:35,
>                  from /usr/include/glm/glm.hpp:117,
>                  from modules/creaturegodot/glm/./gtx/../detail/intrinsic_integer.hpp:32,
>                  from modules/creaturegodot/glm/./gtx/simd_vec4.hpp:49,
>                  from modules/creaturegodot/glm/ext.hpp:134,
>                  from modules/creaturegodot/MeshBone.h:49,
>                  from modules/creaturegodot/CreatureModule.h:41,
>                  from modules/creaturegodot/creaturegodot.h:7,
>                  from modules/creaturegodot/register_types.cpp:5:
> /usr/include/glm/detail/func_integer.inl:50:23: note: 'template<class T> T glm::detail::mask(T)' declared here
>   GLM_FUNC_QUALIFIER T mask(T Bits)
>                        ^
> scons: *** [modules/creaturegodot/register_types.x11.tools.64.o] Error 1
> scons: building terminated because of errors.
> 

Of course everyone is free to go and check out the module's code and try to compile it themselves here:
https://github.com/kestrelm/Creature_Godot

**Comment by blurymind** [comment]
its perhaps worth noting that the module depends on glm and gason - but they are included in it's build folder

**Comment by akien-mga** [comment]
It looks like issues with the module itself, you should probably take it to the upstream developer directly.

**Comment by vnen** [comment]
Ok, I build it successfully but had to add a line to SCsub from @blurymind's version because some header file wasn't being found:

```Python
# SCsub
Import('env')

env_module = env.Clone()
env_module.Append(CPPDEFINES=['_USE_MATH_DEFINES'])
env_module.Append(CPPPATH='#modules/creaturegodot') # Added to find headers
env_module.Append(CPPPATH='#modules/creaturegodot/glm')
env_module.Append(CPPPATH='#modules/creaturegodot/gason')
env_module.Append(CXXFLAGS=['-std=c++11'])
env_module.add_source_files(env.modules_sources,"*.cpp") # just add all cpp files to the build
```

I tested with the sample provided and it's working fine.

**Comment by blurymind** [comment]
@vnen  Awesome stuff. It's compiling now and looks promising.
I forwarded this solution to creature2d's dev and will be testing out his addon later today.

For anyone curious, there are a number of example files you can try to load into godot:
http://www.kestrelmoon.com/creaturedocs/Animation_Samples_And_Examples/Samples_And_Videos.html

**Comment by Kazuo256** [comment]
> If you keep the c++11 flag only to your module, you shouldn't have a
problem with the rest of the headers of the engine..

There was something to the effect of:

```c++
puts(__FILE__":"__LINE__);
```

In a Godot header. It could not compile since the syntax is ambiguous with C++11's user-defined literals. When my module included a header from Godot (one of those to register types) it failed to compile due to lines like this.

It might not be there anymore, but just pointing out that it is possible to have compile errors even if only your module is using C++11.

**Comment by blurymind** [comment]
He committed the changes to master. Thanks everyone :D

**Comment by punto-** [comment]
Oh right, we've seen this, you just have to add spaces to the macro, like
this:

puts(__FILE__ ":" __LINE__);

**Comment by blurymind** [comment]
Btw there was a nasty crash with the creature node where if you put a wrong directory, it crashes godot entirely. It is fixed now.

The plugin is really damn nice. It's so good to see smooth sprite deformation 2d animation in godot. 
Can only hope to see godot's native animation editor catching up to that soon. Visually it is a huge improvement to have that

**Comment by vnen** [comment]
Is there something that needs to be fixed in Godot? The original issue was proven to not be related to the engine but @Kazuo256 is making a point here. WDYT @punto-?

**Comment by punto-** [comment]
I don't think so.. there may be some instances of that macro error where
you need to add spaces (I remember a patch for that a while ago tho), and
maybe the module docs could include this method of adding compile options
only for the module, other than that probably not..

**Comment by vnen** [comment]
I just compiled Godot with `CCFLAGS='-std=c++11'`. Got a lot of warnings because of the macro (among other things) but it finished without errors. So I consider there's no issue anymore.
