### ISSUE TITLE
Pressing "no" to "This scene has never been saved. Save before running?" causes it to not run. 

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#44917]
**Godot version:**

3.2.3 stable official

**OS/device including version:**

Windows 10

**Issue description:**

I had an unsaved scene that I had made just to test how my pixel art game looked when I resized the window, so I hit Play Scene, and it asked me if I wanted to save, and I hit no, and then nothing happened. **I think either hitting "no" should cause it to run without saving (as the dialogue box implies), or the dialogue box text should be changed to say something like "Please save your scene before running it"**.

**Steps to reproduce:**
Create new scene
Hit play scene before saving the scene

**Minimal reproduction project:**

not relevant

**Comment by Calinou** [comment]
> I think either hitting "no" should cause it to run without saving (as the dialogue box implies)

This isn't possible because the editor starts a child process to run the project. If the scene is not present on disk, there's no way to run it.

We can edit the button text so that it says something like "No (cancel)" instead.

**Comment by LightningAA** [comment]
> We can edit the "No" button text so that it says something like "No (cancel)" instead.

Well **the reason it's confusing is because "Save before running?" makes it sound like saving the scene before running it is optional**. Perhaps change it say something like "Please save your scene before running it" and make the buttons say "Save" and "Cancel" (or just make it an Accept Dialog instead of a ConfirmationDialog)
