### ISSUE TITLE
Asset Library host not found

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#44919]
**Godot version:**
3.2.3 Mono x64 Custom Build

**OS/device including version:**
Windows 10 x64

**Issue description:**
![image](https://i.imgur.com/a94RngR.png)
(The writing is "Unable to define/recognize host name")

![image](https://i.imgur.com/1mdhfmA.png)

**Steps to reproduce:**
1. Open AssetLib in Godot.
2. Catch the bug.

**Comment by Calinou** [comment]
Are you using an HTTP/HTTPS proxy? These aren't supported yet: https://github.com/godotengine/godot/issues/6100

Are you using a dual-stack IPv4/IPv6? See https://github.com/godotengine/godot/issues/36418.

**Comment by Calinou** [comment]
@Teashrock Bump :slightly_smiling_face: See my questions above.

**Comment by Teashrock** [comment]
@Calinou 
No, all I'm using is my home local network, no proxies in the router.
No, I don't need IPv6 at the moment.

**Comment by Calinou** [comment]
@Teashrock Can you (or anyone else) still reproduce this bug in [Godot 3.4.2](https://godotengine.org/article/maintenance-release-godot-3-4-2) or any later release?

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
