### ISSUE TITLE
Scaled up CollisionShapes using BoxShapes will flail wildly when colliding.

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#4491]
When using the ability to dynamically scale CollisionShapes on RigidBodies, when attempting to scale up a BoxShape, it will intersect and flail wildly with other colliders.

To reproduce this issue, create a RigidBody with a standard box CollisionShape child. Scale the CollisionShape a significant amount (10.0+ should be sufficent) and then place the RigidBody high above a static body to act as the ground. When the RigidBody collides with the ground, it will flail wildy and never stop. This issue only seems to occur with BoxShape colliders; things like SphereShapes and CapsuleShapes do not seem to suffer from the same issue when scaled up.

**Comment by reduz** [comment]
yeah.. this kind of sucks, I tried to make the physics engine too flexible
and then started having precission issues.. will eventually have to
introduce a few hacks to avoid these situations

**Comment by SaracenOne** [comment]
Yeah, one reliable way to solve this would probably be to extract the scaling information and feed it directly into the shape's extants. I've actually been working on some improvements to the frontend of the physics engine which will allow, amongst other things, people to create 'proper' ragdolls, and one such improvement is that you'll be able to make ragdolls which adapt to any size, and it pretty much is functional bar this one bug I ran into. I'd fix this myself, but I'm having a lot of trouble figuring out how the internals of the physics engines.

**Comment by reduz** [comment]
yes, indeed.. actual physics engines just feed this stuff into shape
geometry, should have done this. There are more open source physics engines
nowadays with permissive licenses than when I wrote the current one, which
use saner approaches than Bullet.. should give a check to that for either
replacing it or adapting it

**Comment by SaracenOne** [comment]
Feeding it into the shape geometry does seem like the right thing to do. Even if it results in some inconsistencies with complex multi-tiered scaling, it would be overall more reliable (and may even have some performance gains). I can't say what the best choice for a long-term replacement physics engine might be though, but I'd be curious to know what it was about Bullet's design which you felt made it unsuitable. I honestly don't know enough about the deep math behind them to be able to sufficently compare.

**Comment by reduz** [comment]
Bullet is good, but you have to be constantly hacking "margins" into shapes
for it to work due to the collision algorithm it uses (GJK+EPA) , if you
make a margin too big or too thin you get inconsistent results, which in
general requires more work for the user compared to other physics engines
that just work.

**Comment by SaracenOne** [comment]
Ah, I understand. Well, either way, the design of the physics engine is very self-contained so it shouldn't be too much trouble to allow the usage of alternatives regardless.

**Comment by reduz** [comment]
yeah, collision detection is a single file, it shouldn't be too troublesome
to replace the collision functions

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
