### ISSUE TITLE
Implement additional stretch_aspect - crop

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#4492]
Please implement an additional stretch aspect mode. Let's call it crop.
If you are familiar with flash, you know what I am talking about - the NO_BORDER scaling mode.

What this will do is scale the content up/down until there are no black borders are appeared. This is like the reverse of what the 'keep' mode is doing in Godot now.
If keep = min(screen_width/game_width,screen_height/game_height),
then crop will be
max(screen_width/game_width,screen_height/game_height)

This will be a best sure way to know that your game won't have any empty areas or black borders on any device without having to test on the device. 

I think that a portrait game should select 'keep_width' and landscape game should select 'keep_height'. I am not sure if this will work perfectly on all devices.

I don't know if there is a way to get the desired appearance without camera zoom. The camera zoom method is a hacky way so that you have to multiply the zoom scale with other elements like canvas layer to get this correct.

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
