### ISSUE TITLE
SkeletonIK bug cause strange model deform on runtime

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#44937]
**Godot version:**

3.2.4 beta4

**OS/device including version:**

![屏幕快照 2021-01-05 22 50 28](https://user-images.githubusercontent.com/64188282/103660340-702c8d00-4fa8-11eb-9b83-e95d1333b68d.png)

**Issue description:**

without target on runtime
https://user-images.githubusercontent.com/64188282/103660419-876b7a80-4fa8-11eb-95df-399a5dbe8bc6.mov

with target on runtime
https://user-images.githubusercontent.com/64188282/103660570-b550bf00-4fa8-11eb-9857-245e53e2cc08.mov

**Steps to reproduce:**
get a model with animtion
add skeletonIK node as a child node of skeleton node
add gdscript to skeletonIK node and wirte code to play IK when game start
run it

**Minimal reproduction project:**

[IKbug.zip](https://github.com/godotengine/godot/files/5770894/IKbug.zip)

**Comment by snougo** [comment]
also I got error message everytime when I run it
![屏幕快照 2021-01-05 23 01 12](https://user-images.githubusercontent.com/64188282/103661975-52f8be00-4faa-11eb-8738-23a518f835dc.png)

**Comment by Zireael07** [comment]
It's related to where in your tree the SkeletonIK node is related to the bones it wants to animate. This kind of thing should really have a yellow warning in editor for cases where the SkeletonIK can't/won't be able to find the bone...

I fixed it with trial and error in my projects. Usually I place SkeletonIK as sibling of armature/skeleton, not child.

**Comment by snougo** [comment]
> It's related to where in your tree the SkeletonIK node is related to the bones it wants to animate. This kind of thing should really have a yellow warning in editor for cases where the SkeletonIK can't/won't be able to find the bone...
> 
> I fixed it with trial and error in my projects. Usually I place SkeletonIK as sibling of armature/skeleton, not child.

if skeletonIK not a child node of skeleton node, it won't automatically get the bones list of skeleton
![屏幕快照 2021-01-05 23 51 22](https://user-images.githubusercontent.com/64188282/103667481-f5b43b00-4fb0-11eb-929a-503ae712532c.png)
![屏幕快照 2021-01-05 23 51 32](https://user-images.githubusercontent.com/64188282/103667490-f8169500-4fb0-11eb-99e7-81c4a71e71cc.png)

**Comment by snougo** [comment]
this is a documentation issue not a code bug, sorry

**Comment by Zireael07** [comment]
Please tell us how you fixed this (as I was running into a similar problem), and which docs should be updated?

**Comment by snougo** [comment]
> Please tell us how you fixed this (as I was running into a similar problem), and which docs should be updated?

I have opened another issue report about skeletonIK is_running() method, you can download the minimal project to see the code, hopefully it will help you

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/45590.
