### ISSUE TITLE
Reffering to MeshInstance in GDNative doesn't work

### ISSUE THREAD

**Issue by federico-leuze** [godotengine/godot#44930]
Hi, I'm trying to use MeshInstance in a GDNative script, but I receive this error, this happen directly if I write:

**Godot version:**
Godot 3.2.3

**OS/device including version:**
Linux OpenSuse-Tumbleweed

**Issue description:**
Scons is not able to compile Ref<MeshInstance>, returning 
`error: 'class godot::MeshInstance' has no member named 'unreference'`

**Steps to reproduce:**
try Reference a MeshInstance in a GDNative Class
`Ref<MeshInstance> mesh;`

**Minimal reproduction project:**

[Example.zip](https://github.com/godotengine/godot/files/5769972/Example.zip)

**Comment by akien-mga** [comment]
Please fill the issue template.

**Comment by Zylann** [comment]
This is the wrong repo. This is about the C++ bindings https://github.com/godotengine/godot-cpp
Also you cant use `Ref` on a class that does not inherit `Reference`, so the error is expected.
