### ISSUE TITLE
glTF2 updates: attenuation was changed

### ISSUE THREAD

**Issue by fire** [godotengine/godot#44945]
**Godot version:**
https://github.com/godotengine/godot/commit/a390e1e8a2efd1de810e0c1f2e0929ba2918e8a9

**OS/device including version:**
It's graphics, but this was in result to a render engine change. It applies to all.

**Issue description:**

The engine formulas don't match with the glTF2 formulas. Attenuation was changed in https://github.com/godotengine/godot/pull/44941.

https://github.com/godotengine/godot/blob/6e23ab4fa20f766ef9e1ec64be88675db6c708af/modules/gltf/gltf_document.cpp#L4936

https://github.com/godotengine/godot/blob/6e23ab4fa20f766ef9e1ec64be88675db6c708af/modules/gltf/gltf_document.cpp#L5027

See original test cases from gltf assets in #39450

**Steps to reproduce:**
Load the test project in #39450.

**Minimal reproduction project:**
I don't have a project ready, but see #39450. I think it has a gltf2 asset.

**Comment by fire** [comment]
Fixed by https://github.com/godotengine/godot/issues/44945.

**Comment by akien-mga** [comment]
> Fixed by #44945.

You referenced this issue and not a PR.

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/53109 Mistake.
