### ISSUE TITLE
Android mobile screen expanding till front camera region in portrait mode

### ISSUE THREAD

**Issue by abhiagnihotri01** [godotengine/godot#44946]
**Godot version:**
3.2.4 beta

**OS/device including version:** 
Product: Redmi Note 7 Pro
Version: Android 10
CPU: arm64
Backend: GLES3

**Issue description:**
When i run game with Mode=2D and Aspect=Ignore, the game is getting extended till front camera. Due to this, the game contents at top middle part are getting hidden behind the front camera. I want the game to expand till just below the front camera.

**Steps to reproduce:**
Run any game with a background in android device having front camera coming in front of mobile screen. In my case i am using the Redmi Note 7 Pro mobile.

**Minimal reproduction project:**
<img width="204" alt="Mobile_Screen" src="https://user-images.githubusercontent.com/40638746/103691713-a116bd00-4fbc-11eb-9dbe-0144b2ada3d5.png">

**Comment by mbrlabs** [comment]
I could reproduce this on my Galaxy S10 starting with `beta2`, but it seems it's a feature added in #43104. You can get the safe area for your UI with `OS.get_window_safe_area()` though. cc @Klowner

**Comment by Calinou** [comment]
> When i run game with Mode=2D and Aspect=Ignore, the game is getting extended till front camera. 

Reminder: Do *not* use the `ignore` aspect in production games, as this will cause visible distortion on any aspect ratio not matching your "design" aspect ratios. Now that phones exist in many aspect ratios (16:9, 18:9, 19:9, 19.5:9, 21:9, …), you really need to support multiple aspect ratios properly to give everyone a good experience.

**Comment by abhiagnihotri01** [comment]
Thanks for the reply @mbrlabs. The function OS.get_window_safe_area()  solved my problem.
