### ISSUE TITLE
Godot Editor memory leak and freeze on editing Editor theme color

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#44943]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux editor

**Issue description:**
Editor freeze and use all the ram (16+Gb)

**Steps to reproduce:**
1. Create an empty project
2. add Control as main node
3. click in the inspector (of Control) Theme - New Theme - select created Theme - in Theme editor - Create from current editor theme, like on screenshot 
![1](https://user-images.githubusercontent.com/24825887/103674425-cf31d800-4f8f-11eb-926e-9ac05af50f14.png)

4. menu Editor - Editor settings - Theme - Accent Color 
5. click Color to edit and click just once on any other color is enough to see Editor freeze and memeory leak

**Comment by Calinou** [comment]
> 3.2.2 stable

Please upgrade to 3.2.3 or 3.2.4beta4 when reporting issues.

**Comment by danilw** [comment]
> Please test issues in 3.2.3 or 3.2.4beta4 

I tested on 3.2.4beta4 and bug does not happen there, so closed
