### ISSUE TITLE
PopupPanel doesn't resize properly

### ISSUE THREAD

**Issue by NoFr1ends** [godotengine/godot#44942]
**Godot version:**
3.2.4.beta4

**Issue description:**
When having a label with autowrap inside of a PopupPanel and changing the content of the label the PopupPanel doesn't resize accordingly.
Creating a new label in the script and adding it as a child node resizes the PopupPanel as expected.

For example:
![Peek 2021-01-05 17-00](https://user-images.githubusercontent.com/6075580/103672083-11511e80-4f7c-11eb-845a-0cc9f837975b.gif)
The PanelContainer on the top left has the same content as the PopupPanel which is created by the custom tooltip for the button in the middle.

**Steps to reproduce:**
1. Create a PopupPanel
2. Create a VBoxContainer
3. Add a label inside the vbox, enable autowrap
4. Create a script to change the text of the label in the ready function 

**Minimal reproduction project:**
[testpopuppanel.zip](https://github.com/godotengine/godot/files/5771414/testpopuppanel.zip)

**Comment by andy-noisyduck** [comment]
Probably the same issue, but if the text contracts the size will also be incorrect. The popup will remain with the inflated size from the original label box.

**Comment by Calinou** [comment]
> Probably the same issue, but if the text contracts the size will also be incorrect. The popup will remain with the inflated size from the original label box.

As far as I know, none of Godot's dialogs currently downsize if child elements are also downsized or hidden.
