### ISSUE TITLE
Autcomplete not working for multiline strings in Editor

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#44959]
**Godot version:**
3.2.3

**OS/device including version:**
Win 7

**Issue description:**
Multiline scripts don't autocomplete properly in the editor.

**Steps to reproduce:**
(With the | representing where the cursor is.)

Should be able to type:
```"""```
and have it automatically create:
```"""|"""```

Currently you have to type all six and you get back:
```
""""""|
```

**Minimal reproduction project:**

**Comment by Paulb23** [comment]
Should be fixed by #45393
