### ISSUE TITLE
Popup menus do not close when other is opened (DisplayServer regression)

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#44953]
**Godot version:**
4.0 master cdfcf68

**OS/device including version:**
Win 10

**Issue description:**
Popup menus do not close when other is opened.
![popup_menu_bug_1](https://user-images.githubusercontent.com/41730826/103719668-3a71bd80-5015-11eb-861a-4528adfcc2a3.gif)
![popup_menu_bug_2](https://user-images.githubusercontent.com/41730826/103719640-2b8b0b00-5015-11eb-9ec0-dc8cfe1c1cb2.gif)

This seems to affect all popup menus (not just those created by MenuButtons) since you can have multiple context menus open as well.
![image](https://user-images.githubusercontent.com/41730826/103719785-83c20d00-5015-11eb-8329-da056b3ad9e4.png)

However I also get this weird issue where if I right click in FileStystem and then right clicking in the Scene Tree, the filesystem context menu goes blank:
![image](https://user-images.githubusercontent.com/41730826/103719820-9b999100-5015-11eb-9254-ac72e01564e2.png)

**Steps to reproduce:**
Open menus

**Comment by EricEzaM** [comment]
I can't see any code changed in PopupMenu, Popup or Window which would affect this. Is it something in display server(s)?

**Comment by Chaosus** [comment]
Fixed by https://github.com/godotengine/godot/pull/44948
