### ISSUE TITLE
3D Particle stream disappears when camera is perpendicular to emitter direction

### ISSUE THREAD

**Issue by cwaldren** [godotengine/godot#44955]
OS: Windows 10, 64-bit
Godot: v3.2.3 stable
Processor: AMD Ryzen 7 3700X
Graphics: GeForce RTX 2060S, Nvidia driver v460.89

**Issue description:**

All 3D particles disappear when camera is rotated perpendicular to the particle stream. Particles appear again when camera is rotated back.

**Expected result:**

3D particles do not disappear.

**Steps to reproduce:**

Open the minimal reproduction scene. Hold the 'D' key until the particle stream disappears. Camera can be rotated using 'A' and 'D'; camera transform is displayed on a label in the top left corner of the screen. 

I've noticed the camera has to be pretty close to the stream - if I move it further away, the particles no longer disappear when rotating. I suspect this has something to with some kind of bounding box..

**Minimal reproduction project:**
[MinimalParticleRepro.zip](https://github.com/godotengine/godot/files/5773822/MinimalParticleRepro.zip)

**Comment by Calinou** [comment]
> I suspect this has something to with some kind of bounding box..

You can probably increase the particle visibility AABB size to avoid this issue.

If you check the top of the editor viewport while having a Particles node selected, you should see a **Particles** menu that lets you generate a visibility AABB automatically.
