### ISSUE TITLE
Mouse mode always 0 (MOUSE_MODE_VISIBLE) in HTML5

### ISSUE THREAD

**Issue by fractilegames** [godotengine/godot#44957]
**Godot version:**
3.2.4 beta4

**OS/device including version:**
Xubuntu 20.04 x86_64, Firefox 84.0.1 / Chromium 87.0.4280.88

**Issue description:**
Input.get_mouse_mode() keeps returning 0 even after mouse is clearly captured by the browser/game and the cursor disappears. Same code works just fine in native Linux/X11 export and when exporting to HTML5 from Godot 3.2.3 stable. No difference between Regular and Threads export type.

**Comment by Faless** [comment]
Likely related to #44755 .

**Comment by fractilegames** [comment]
Will this be fixed in 3.2.4? I'm waiting for the stable version before releasing an update to my game and this would be a problem for me. I don't see any way to work around this..

**Comment by akien-mga** [comment]
I put some debug prints here to see what happens:

https://github.com/godotengine/godot/blob/06895e0c9e312ac02b8fa8a0058dcc306b9a8018/platform/javascript/os_javascript.cpp#L585-L593

It looks like when I set `MOUSE_MODE_CAPTURED`, `ev.id` is `canvas` and `canvas_id` is `#canvas`, so the comparison fails. I'm not familiar enough with that code to say how that should be solved though (apart from hacking a `#` prefix to `ev.id` in the comparison to make it work, but that's hiding the issue).

**Comment by Faless** [comment]
> and `canvas_id` is `#canvas`

Wow, thanks a lot for spotting that. I wonder how the rest of the functions using `canvas_id` worked :(. Probably emscripten doing some checks and removing the extra `#`. I'll make a PR to fix that.
