### ISSUE TITLE
Editor can't draw tabs and spaces at the same time

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot#44958]
This PR https://github.com/godotengine/godot/pull/44802 introduced regression that hampered previous feature of editor, that could draw both spaces and tabs at the same time. It comes handy when one uses tabs for indent and likes to see spaces too to have better control over code formatting. Not to mention it introduces hidden coupling between drawTabs and drawSpaces settings where having drawTabs on makes drawSpaces not working and it is not indicated anywhere in editor. 

Above PR solved issue where both tab and space icon was drawn at the same time but this is workaround and not real solution. The real problem in this code fragment in textEdit

```
if (draw_tabs && ((glyphs[j].flags & TextServer::GRAPHEME_IS_TAB) == TextServer::GRAPHEME_IS_TAB)) {
	int yofs = (text_height - cache.tab_icon->get_height()) / 2 - ldata->get_line_ascent(line_wrap_index);
	cache.tab_icon->draw(ci, Point2(char_ofs + char_margin + ofs_x, ofs_y + yofs), current_color);
}
else if (draw_spaces && ((glyphs[j].flags & TextServer::GRAPHEME_IS_SPACE) == TextServer::GRAPHEME_IS_SPACE)) {
	int yofs = (text_height - cache.space_icon->get_height()) / 2 - ldata->get_line_ascent(line_wrap_index);
	int xofs = (glyphs[j].advance * glyphs[j].repeat - cache.space_icon->get_width()) / 2;
	cache.space_icon->draw(ci, Point2(char_ofs + char_margin + ofs_x + xofs, ofs_y + yofs), current_color);
}
```

that both `glyphs[j].flags & TextServer::GRAPHEME_IS_SPACE` and  `glyphs[j].flags & TextServer::GRAPHEME_IS_TAB` evaluate to true for tab character which should be fixed somehow.

**Comment by bruvzg** [comment]
> This PR #44802 introduced regression that hampered previous feature of editor, that could draw both spaces and tabs at the same time.

Tabs and spaces are working at the same time.
<img width="305" alt="Screenshot 2021-01-06 at 12 39 44" src="https://user-images.githubusercontent.com/7645683/103759454-6e041600-501c-11eb-861c-a46694910c81.png">

Not sure I get what's wrong, please provide screenshots (what's rendered and what's expected).

**Comment by iwek7** [comment]
So sorry, I messed up my editor config file :(. Closing
