### ISSUE TITLE
Godot Editor math not as expected; float results becoming ints

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#44961]
**Godot version:**
3.2.3

**OS/device including version:**
Win 7

**Issue description:**
Editor math (i.e. type 1*2 in transform position) is awesome. But if a number contains only integers you get the wrong result if it should be a float; it always rounds it to a integer.

**Steps to reproduce:**
`1/2.0` == 0.5
`1/2` == 0 (Wrong)

But conversely, if the input has a float in, you get back an integer.
`2*0.5` == 1
`1/0.5` == 2

Rounding float results to integers if the two inputs are integers is rarely going to be the desired outcome. While it can be worked around, it's non-obvious what's going on (I only recognised it quickly because I've seen it before.)

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
If you type only integers, you get integers back (there are no "float results" involved). This is working as expected imho.

**Comment by CitrusWire** [comment]
> If you type only integers, you get integers back (there are no "float results" involved). This is working as expected imho.

What do you type into a calculator when you want to halve something?
```
x / 2
x * 0.5
x / 2.0
```
99% of people will type the first.
This is a calculator, it is not working as most people would expect a calculator to work.

**Comment by KoBeWi** [comment]
This is intended, inspector fields follow the same math logic as scripts. See https://github.com/godotengine/godot-proposals/issues/1866

**Comment by CitrusWire** [comment]
@KoBeWi  - It may be as intended but I maintain it's still a bug, albeit one of design not implementation. This interface is a tool, not a (over-strictly-typed) programming language, see my calculator example above.
