### ISSUE TITLE
Resizable text

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#4496]
I saw somewhere that this wasn't possible because it's bitmap or something like this. But in Unity, for example, you can resize your text from the text component itself, and don't need to import a new font size each time. 
Maybe if you could adjust it in the label node (or other node that displays text) and then it create the .fnt when compiling. That way you could prototype quickly and it would just import it when necessary (when you actually run the game).

**Comment by Ace-Dragon** [comment]
Godot does not have support for the dynamic resizing of text yet, but it is in the works for the 2.x version series (a recent commit takes a step towards that).

For now, you can scale text by parenting it to a generic 2D node and then scaling the parent (but you will be limited by the general resolution of the text itself).

**Comment by toger5** [comment]
just import a huge font resolution and than scale down.
