### ISSUE TITLE
Text section being updated when entering BB Code text in bb text section

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#44965]
**Godot version:**
3.2.3

**OS/device including version:**
Linux

**Issue description:**
When you enable BB Code in a label and type in there, at certain points in time the 'text' properly updates itself to match. This is confusing and leads to lost data. Sometimes you inadvertently type into the 'text' box by mistake, then run your code and you lose your changes because BB Code has refreshed the data in the text label.

This unsynchronised and one way update makes no sense. If you have bb text enabled, then text property should either be disabled, or both should synchronise in both directions.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
`text` and `bbcode_text` are going to be unified. See #39148 and linked issues.

**Comment by chucklepie** [comment]
Thanks. I do search for these things, but I think my phrases are bad or the
github search engine isn't very good.

I raised this because I don't know how many times I've lost my changes 😁
