### ISSUE TITLE
ClassDB.class_get_method_list("class") returns a method Array of a Dictionary with only the name key

### ISSUE THREAD

**Issue by CodeDarigan** [godotengine/godot#44968]
**Godot version:**
Godot 3.2.3 Stable

**Issue description:**
Calling ClassDB.class_get_method_list("Node") in a Windows Release Exe will return an Array of dictionaries that
only contain the name key. All other keys that you can see in the editor don't seem to appear here.

**Steps to reproduce:**
```gdscript
func _on_Button_pressed():
	var method_list = ClassDB.class_get_method_list("Node")
	for m in method_list:
		# Adding method list
		var l = Label.new()
		l.text = m as String
		$ScrollContainer/VBoxContainer.add_child(l)
```

In Editor Builds

![EditorBuilds](https://user-images.githubusercontent.com/47497501/103798200-470c0b00-5041-11eb-94f3-b06446a911ae.png)

In Release Builds

![ReleaseBuilds](https://user-images.githubusercontent.com/47497501/103798225-4d9a8280-5041-11eb-9b7c-26aff1852360.png)

**Minimal reproduction project:**

[DBTest.zip](https://github.com/godotengine/godot/files/5777105/DBTest.zip)

**Comment by KoBeWi** [comment]
Seems to be done on purpose:
https://github.com/godotengine/godot/blob/8158d17edf18e3d6ec847d2cb710012361e7b12e/core/core_bind.cpp#L2163-L2169
Should be documented probably.
