### ISSUE TITLE
Sprite node not animating

### ISSUE THREAD

**Issue by Ezenki** [godotengine/godot#44975]
[game.zip](https://github.com/godotengine/godot/files/5783540/game.zip)

**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**
add sprite node, animation player, and animation tree, (I'm not very sure If the animtree node impacts this), then create a couple of animations and then click around on the editor, then try to create an animation or add a new keyframe with the frame property on the sprite.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Please attach a minimal project that reproduces the issue.

**Comment by KoBeWi** [comment]
Uncheck `active` in AnimationTree when editing animations, otherwise it will overwrite your current frame. Does it solve the issue?
(btw you could've commented after attaching the project; we don't get notifications for edits)

**Comment by Ezenki** [comment]
thanks that helped

**Comment by Chaosus** [comment]
Alright, closed then.
