### ISSUE TITLE
Z-fighting with a high value for the far plane

### ISSUE THREAD

**Issue by Dimev** [godotengine/godot#44988]
**Godot version:**
3.2.3.stable

**OS/device including version:**
Windows 10 Home (10.1.1941)
CPU: Intel i5-9600KF
GPU: NVIDIA GTX 1660, driver version 460.89, GLES3 backend

**Issue description:**
When setting the camera far plane to a high value (100 000 or higher), some z-fighting on distant objects can occur when moving the camera. This likely has to do with the precision of the depth buffer.
The reason I'm reporting this is that unreal engine 4 doesn't seem to have this issue, and it can prevent the creation of large open world scenes.

I did find a [source](https://www.gamasutra.com/blogs/BranoKemen/20090812/85207/Logarithmic_Depth_Buffer.php), saying that changing the way the z-buffer is used can help solve these issues, but I'm not experienced enough with openGL/Vulkan to implement this.

**Steps to reproduce:**
Make a new scene, add 2 meshinstances with cube meshes, set the size to 1000, 1000, 1000 and 10000 2, 10000 respectively
fly far away with the editor camera, and when moving, some flickering can be seen where the 2 meshes intersect.

**Minimal reproduction project:**
[Minimal reprod.zip](https://github.com/godotengine/godot/files/5781529/Minimal.reprod.zip)

**Comment by Calinou** [comment]
I doubt we can use a logarithmic depth buffer in GLES3 (or worse, GLES2).

**Comment by lawnjelly** [comment]
I'm not an expert in this. It did get discussed before, if you manage to search the issues. I have vague memory that tweaking the z buffer (reversed etc) may be more limited in GLES. Although maybe that's GLES2 rather than GLES3, no idea.

http://www.reedbeta.com/blog/depth-precision-visualized/

> Fortunately, in desktop OpenGL you can fix this with the widely-supported ARB_clip_control extension (now also core in OpenGL 4.5 as glClipControl). Unfortunately, in GL ES you’re out of luck.

**Comment by Dimev** [comment]
What about doing this in the vulkan branch?
then it would still be possible to have a view distance beyond 4km, and using something like the origin shifter plugin it would be possible to avoid some of the physics issues.

WhatI'm trying to create is a space game. If the render distance is limited to only 4km then that's not really gonna be useful. in ue4 this wouldn't be a problem, as long as world origin shifting is used.
My though around this issue would be to use multiple cameras with different near/far planes, and combine them via a ViewportContainer, but I'm not sure how well that would work, and then use something similar to world origin shifting to solve physics issues.

**Comment by aaronfranke** [comment]
> What I'm trying to create is a space game. If the render distance is limited to only 4km then that's not really gonna be useful. in ue4 this wouldn't be a problem, as long as world origin shifting is used.

Right now Godot isn't very suitable for space games (and most other engines also aren't). At the moment the only option to have large-scale space games is to use a custom engine or customize and existing one (ex: Star Citizen uses modified Lumberyard). Unreal 5 is planned to get support for double precision, which would allow extremely large scales. Godot doesn't have an ETA on this. I highly recommend reading more in [proposal 892](https://github.com/godotengine/godot-proposals/issues/892) if you're interested in making a space game.

**Comment by Dimev** [comment]
Ah thanks. I was planning on making a workaround for single float precision, but the thing I don't know how to work around yet is the limited far plane, besides the trick I described above.

**Comment by Calinou** [comment]
> Ah thanks. I was planning on making a workaround for single float precision, but the thing I don't know how to work around yet is the limited far plane, besides the trick I described above.

You can increase the value of the Near plane distance to decrease visible Z-fighting significantly.

You can change this value dynamically at run-time depending on viewing conditions/camera mode. This way, you can make the best out of the precision you can get.

**Comment by lawnjelly** [comment]
You can also simply render far away stuff to a separate texture (probably viewport in Godot, I'm not familiar with this technique in Godot), use a separate camera, separate scene.

Then in the main scene just draw this texture as a background with no Z writes, and render everything close up on top of this.

You can also potentially use a lower resolution for the far away stuff and blur it for depth of field, for better performance.

This is how a lot of old games would do things. If you look at some game levels from return to castle wolfenstein (2001) for instance, you can see mini sized scenes at the side of the map that were used explicitly for rendering the background skyboxes etc before rendering the foreground.

**Comment by Dimev** [comment]
Thanks for the suggestions for some workarounds. 
As the issue is still open, I'll add this as a resource, as it discusses some ways to organize the depth buffer: https://zero-radiance.github.io/post/z-buffer/

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/58516, as no further steps will be taken in 3.x towards double precision support.
