### ISSUE TITLE
Creating a VisualScript node emit warning to the output

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#44994]
**Godot version:**
efdca23f8798b03330e25d2d615c57adaab237af

**OS/device including version:**
Win10

**Issue description:**
Attempting to creating a node emit a warning in the editor.

**Steps to reproduce:**
![vs_bug](https://user-images.githubusercontent.com/3036176/103919660-5b273980-5121-11eb-89d4-f47f46f63dab.gif)

**Minimal reproduction project:**

**Comment by Chaosus** [comment]
cc @swarnimarun

**Comment by swarnimarun** [comment]
Aah, I forgot to throw in the fix for that in Refactor PR it seems.
Will make separate PR for this stuff before I wrap up my rebasing and fixing on submodule branch.

**Comment by Gallilus** [comment]
seems fixed in 4.0.alfa
