### ISSUE TITLE
Space  will lead to abnormal line breaks in Languages with non Latin alphabets in RichTextLabel

### ISSUE THREAD

**Issue by colorworlds** [godotengine/godot#44993]
**Godot version:**

v3.2.3.stable

**OS/device including version:**

win7

**Issue description:**

Some languages do not use spaces to separate words, so `one word` such as `中` in these languages will be treated as `a letter` in English, while `two words` such as `中文   `  will be treated as `one English word` because of spaces.
Eventually, this will result in a newline exception.

The following is the specific effect, I tested Chinese and Japanese.
Label (Text above) is right, but RichTextLabel (Text below)  is wrong!
The second and fourth lines are treated as `one English word` in RichTextLabel.

![截图未命名0107220511](https://user-images.githubusercontent.com/59448002/103901370-05a85800-5134-11eb-9c0e-37643bc3588e.png)

**Steps to reproduce:**
Copy the following sentence to Label Node and RichTextLabel:
`中文 中文 中文中文中文中文中文 日本語 日本語 日本語日本語日本語`

**Minimal reproduction project:**

This is the project file. I'm sorry, I missed the font before
[LabelTest.zip](https://github.com/godotengine/godot/files/5824165/LabelTest.zip)

**Comment by Calinou** [comment]
I suppose proper line breaks for non-Latin languages were only added in the TextServer implementation, which is in `master` but not 3.2.x. Due to the large amount of backward-incompatible changes it contains, it can't be backported to 3.2.x.

cc @bruvzg

**Comment by KoBeWi** [comment]
I tested in 3.2.4 beta5 and master and I don't see difference.

> the issue is easy to reappearance

The project would still be useful, because you need custom font to display non-latin letters.

**Comment by colorworlds** [comment]
@KoBeWi   Maybe 3.2.4 has been fixed? And I have upload the project,I'm sorry I forgot about the problem of language font

**Comment by bruvzg** [comment]
> Maybe 3.2.4 has been fixed?

It's not.

### In `3.2`:

In 3.2 `Label` (top on the screen recordings) is always breaking single characters and `RichTextLabel` will try to break "words" (anything separated with space or punctuation) first.

https://user-images.githubusercontent.com/7645683/104809911-91d41280-57f9-11eb-8dd7-c2a5acfe5772.mov

### In `master`:

In  the `master` both use ICU word breaker (language specific rule + dictionary based).

https://user-images.githubusercontent.com/7645683/104809916-98fb2080-57f9-11eb-95e8-051169f70303.mov
