### ISSUE TITLE
Calling popup menu in fullscreen mode make flickering on the screen (DisplayServer regression)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#44997]
**Godot version:**
f1832a6027529332b91fe1786ba58e8e9af43fd7

**OS/device including version:**
Win10/GTX1060

**Issue description:**
Clicking(especially frequent) on these buttons which called popup menus 
![image](https://user-images.githubusercontent.com/3036176/103932642-3045e100-5133-11eb-87bb-0bc01306c09d.png) will cause the whole screen flickering with dark flash.

**Steps to reproduce:**
Simply run the empty project, toggle fullscreen (Shift+F11), and try to use the buttons showed above.

`Single Window Mode` should be disabled (of course).

**Minimal reproduction project:**
It's not recordable with ScreenToGIF unfortunately.

**Comment by Calinou** [comment]
> It's not recordable with ScreenToGIF unfortunately.

You could record your screen using your phone :stuck_out_tongue:

**Comment by Chaosus** [comment]
It's unprofessionally :) but ok - https://drive.google.com/file/d/1RyWLsCaUC53o7dFY3Kt784x45E54iiyB/view?usp=sharing

**Comment by EricEzaM** [comment]
Pretty sure you can attach videos directly to github posts now.

**Comment by Chaosus** [comment]
https://user-images.githubusercontent.com/3036176/103982053-d0cbed80-5193-11eb-9fd3-7d99f0c73969.mp4

**Comment by akien-mga** [comment]
Is that a recent regression?

**Comment by Chaosus** [comment]
At 41e9028868e49669de83c82ba20fd9dcef0d1b8b the pressing these buttons in fullscreen leads to editor window become invisible (which is fixed by 8a2bc6bf58e305a55ae7b54b8eeafa435575c744) so I guess its exist at the point where Juan separated display server (10 months ago). But need to test for sure.

**Comment by Chaosus** [comment]
Also found an interesting article about possible fixing it: https://github.com/glfw/glfw/issues/527

**Comment by Chaosus** [comment]
After some experimenting I found 2 ways to solve this problem:
1) Append 1 pixel to the height of the window which enters fullscreen mode. The downside of this - the client rect will be changed and this may alter the content.
2) Change WS_POPUP to WS_CHILD for borderless windows. The downside of this is child windows behaved differently than WS_POPUP for example their positions and event processing needs to be modified. They don't close automatically if the users changed window focus.

**Comment by Chaosus** [comment]
+ It's not only the editor problem - games will be affected too (if the `Embed subwindows` is disabled in the project settings)

**Comment by Chaosus** [comment]
This issue seems fixed at fe7559f751e81b21da2eb8252123f384b8a8622d. This may be caused by either engine or Windows upgrade.

**Comment by Chaosus** [comment]
This issue seems fixed by https://github.com/godotengine/godot/pull/54645
