### ISSUE TITLE
Texture get_size gets wrong size for Region textures

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#44996]
**Godot version:**
3.2.3

**OS/device including version:**
Win 7

**Issue description:**
(Similar to: https://github.com/godotengine/godot/issues/33366 )

The size returned by `get_size()` for a texture is the full texture size, even if a region rectangle is declared.

Given `Texture` has no documented methods/properties for getting the rectangle size this means it's impossible to get the correct texture size when using a spritesheet with a region.

https://godot-es-docs.readthedocs.io/en/latest/classes/class_texture.html#class-texture-get-size

**Steps to reproduce:**
`get_node("Sprite").get_texture.get_size()` on a Texture using a region.

I expect this should be an easy fix:
```
If region enabled:
return Vector2(rect.w, rect.h)
```
[bad size.zip](https://github.com/godotengine/godot/files/5783301/bad.size.zip)

**Comment by Calinou** [comment]
@CitrusWire Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by CitrusWire** [comment]
Done

**Comment by KoBeWi** [comment]
This is not a bug. `region_rect` is a property of Sprite. It doesn't modify texture, it just displays part of it. Texture doesn't know if it's used by regioned Sprite.

Your options are either using `get_rect().size` or using an AtlasTexture, which has its own region property.
