### ISSUE TITLE
Can't use arrays in boolean operations

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44990]
**Godot version:**

c7b4514

**Issue description:**

This is pretty exotic code, but works fine in 3.2:
```
func _ready() -> void:
	var a: Array
	if true and a:
		print("ok")
```
Now it says `invalid operand bool and Array for and operator`.

**Comment by ThakeeNathees** [comment]
There is already an issue here  #44688

**Comment by KoBeWi** [comment]
Duplicate of #44688
