### ISSUE TITLE
Billboards not working on planes

### ISSUE THREAD

**Issue by NHodgesVFX** [godotengine/godot#45000]
**Godot version:**

Godot 3.2.3, 3.2.4 Beta 5

**OS/device including version:**

RTX2080S GLES3

**Issue description:**

Y billboard breaks planes from external software I would expect it to make the x axis always face the camera as described in the docs.

Billboard off
![1](https://user-images.githubusercontent.com/11403345/103941916-8ef06800-50fd-11eb-9415-dff82e83ce2e.PNG)

y billboard on
![2](https://user-images.githubusercontent.com/11403345/103941924-9152c200-50fd-11eb-9206-295451545902.PNG)

The example shows y billboard but it seems the issue effects all billboard modes.

**Steps to reproduce:**
1. import a plane from blender
2. add it to mesh instance add assign a material
3.  change material to y billboard.

**Minimal reproduction project:**

[BillBoardError.zip](https://github.com/godotengine/godot/files/5783851/BillBoardError.zip)

**Comment by Calinou** [comment]
This is because the billboard expects a different rotation for the plane.

Consider using a MeshInstance with a QuadMesh instead.

**Comment by NHodgesVFX** [comment]
Tried rotating the plane that doesn't work. 
![3](https://user-images.githubusercontent.com/11403345/103943333-e8f22d00-50ff-11eb-98d3-cf7bc1b59624.PNG)

Quad mesh does work but I need the pivot to be at the top like in the first screen shot I showed.

**Comment by NHodgesVFX** [comment]
Ok for the pivot you can add a spatial then add you mesh as a child that allows you to get the same effect as setting the pivot. Im going to close this as it seems this is intended. Perhaps this should be added to the docs though.
