### ISSUE TITLE
[Editor only] ViewportTexture transparent by a frame after resizing its Viewport

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#45001]
**Godot version:** Godot Engine v3.2.3.stable.official

**OS/device including version:** Windows 10, GPU AMD RX 470

**Issue description:**

The [ViewportTexture](https://docs.godotengine.org/en/stable/classes/class_viewporttexture.html) from [Viewport::get_texture](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-method-get-texture) is transparent by a frame after changing the [size](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-property-size) of the Viewport when running in the editor, the expected is what happens when running the game (no transparent frames).

**Steps to reproduce:** 
- Create a Viewport and assign its ViewportTexture to a Control to display on the screen;
- Modify the size of the Viewport and note a transparent texture by a frame before showing the content in the new size.

**Minimal reproduction project:**

[viewport_resize_transparent_frame.zip](https://github.com/godotengine/godot/files/5784093/viewport_resize_transparent_frame.zip)

The minimal reproduction project randomizes the size, wait for a `VisualServer::frame_post_draw` and [update](https://docs.godotengine.org/en/stable/classes/class_canvasitem.html#class-canvasitem-method-update) the [Sprite](https://docs.godotengine.org/en/stable/classes/class_sprite.html) with the ViewportTexture assigned.

! This happens in the editor only, running the project generates the correct behavior.

**Comment by LoipesMas** [comment]
Can reproduce on Linux with both 3.2.3 and 3.2.4.beta.custom_build.292bbb870 (NVIDIA GPU).

**Comment by felaugmar** [comment]
A workaround for this editor behavior is welcome if known :)

**Comment by Xrayez** [comment]
If this happens only in editor, perhaps the difference is that the editor itself uses another `Viewport` (displayed within `ViewportContainer`?) to display edited canvas/world, and this may somehow introduce update delays?

Similar issue at #44866.

**Comment by Xrayez** [comment]
I've tried `VisualServer.force_draw()` just after resizing, and this produced interesting behavior... The texture is only updated whenever editor is updated too now (just move the mouse around to trigger mouse hover notifications in the editor).

```gdscript
tool
extends Node2D


func _ready() -> void:
	$sprite.texture = $viewport.get_texture()
	while true:
		$viewport.size = Vector2(rand_range(64, 256), rand_range(64, 256))
		VisualServer.force_draw() # This.
		yield(VisualServer, 'frame_post_draw')
		$sprite.update()
		yield(get_tree().create_timer(0.5), 'timeout')

```

[viewport_resize_transparent_frame.zip](https://github.com/godotengine/godot/files/5788296/viewport_resize_transparent_frame.zip)

**Comment by LoipesMas** [comment]
> I've tried VisualServer.force_draw() just after resizing, and this produced interesting behavior... The texture is only updated whenever editor is updated too now (just move the mouse around to trigger mouse hover notifications in the editor).
> 
> tool
> extends Node2D
> 
> 
> func _ready() -> void:
> 	$sprite.texture = $viewport.get_texture()
> 	while true:
> 		$viewport.size = Vector2(rand_range(64, 256), rand_range(64, 256))
> 		VisualServer.force_draw() # This.
> 		yield(VisualServer, 'frame_post_draw')
> 		$sprite.update()
> 		yield(get_tree().create_timer(0.5), 'timeout')
> 
> Works fine while running the project as well, so again editor issue.
> 
> viewport_resize_transparent_frame.zip

In this project, selecting the Sprite node in the editor produces the (I think) desired result. It seems that then the editor updates often enough (every frame?). Not sure how helpful that is.

**Comment by felaugmar** [comment]
I can reproduce this: https://github.com/godotengine/godot/issues/45001#issuecomment-756874180

And even found a possible workaround for the issue, calling [VisualServer.force_draw(false)](https://docs.godotengine.org/en/stable/classes/class_visualserver.html?#class-visualserver-method-force-draw) and not yielding for a `VisualServer::frame_post_draw` gives the desired behavior without transparent frames.

```gdscript
$sprite.texture = $viewport.get_texture()
  
while true:
  $viewport.size = Vector2(rand_range(64, 256), rand_range(64, 256))
  VisualServer.force_draw(false)
  # yield(VisualServer, 'frame_post_draw')
  $sprite.update()
  yield(get_tree().create_timer(0.5), 'timeout')
```

**Comment by djrain** [comment]
I had reported a similar issue regarding nodes using the ViewportTexture, and also commented there with gifs of what seems like this same issue: #43762
