### ISSUE TITLE
KinematicBody2D slides with move_and_collide

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#45004]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Windows 10

**Issue description:**
Created from https://github.com/godotengine/godot/issues/18433#issuecomment-396372868 to have a separate issue for 2D.

`KinematicBody2D` slides down the slope when using `move_and_collide`. It can be reduced to a minimum setting to almost zero the safe margin in the kinematic body. But it's sliding anyway, only slower.

**Steps to reproduce:**
1. Create KinematicBody2D with a CollisionShape2D
2. Add a script to the KinematicBody2D:
```
extends KinematicBody2D

func _physics_process(delta):
	move_and_collide(Vector2(0, 98 * delta))
```
3. Create a slope using StaticBody2D with a CollisionShape2D

**Minimal reproduction project:**
https://github.com/xphere/godot-testing/tree/slides-down-the-slope
(needs `Debug/Visible Collision Shapes` to be enabled)

**Comment by piratesephiroth** [comment]
Nice one!
I was about to post this exact issue.
Here's another simple project showcasing it:
[move_and_collide-slide.zip](https://github.com/godotengine/godot/files/5784581/move_and_collide-slide.zip)

Uploading output.mp4…

**Comment by Bhu1-V** [comment]
hello @pouleyKetchoupp, I want to work on this can u help me where to start

**Comment by pouleyKetchoupp** [comment]
@Bhu1-V For sure! Your contribution would be welcome. At this point it's hard to tell how difficult it will be to solve, but it's not a problem for now. You can start with investigating the cause, share what you find and we'll find a good solution together if you need help.

Here are a some starters:

- I would suggest to work on latest from the 3.2 branch first (it will be easier to run any test project from the community) but in the end the PR will be opened on master (the code should be mostly compatible).

- You can start with checking `KinematicBody2D::move_and_collide` (of course) and also `Space2DSW::test_body_motion` where most of the logic for this motion is (collision tests are all calls to `CollisionSolver2DSW::solve` with different parameters).

- `test_body_motion` goes through 3 phases:
1. Free body if stuck by using collision test with extra margins
2. Try to move the body without using the extra margins
3. If it collides during the motion, check for rest information using extra margins

- My guess would be that the sliding in `move_and_collide` occurs during phase 1, because it might push the body from the slope if it overlaps, in a direction that is not the direction of the motion  (and then phase 2 moves it vertically and so on, which makes it slide along the slope). The first thing you can do is to run a simple case and debug it to confirm this is what happens.

- If it's confirmed, I'm thinking about a potential way to fix it within `KinematicBody2D::move_and_collide` which can be simple, but I'm not sure it will work. You can check what `move_and_slide` does when `stop_on_slope` is used, and possibly use something similar to revert the sliding effect:
```
if (p_stop_on_slope) {
	if ((body_velocity_normal + up_direction).length() < 0.01 && collision.travel.length() < 1) {
		Transform2D gt = get_global_transform();
		gt.elements[2] -= collision.travel.slide(up_direction);
		set_global_transform(gt);
		return Vector2();
	}
}
```
Note: It would have to be adapted to `move_and_collide`, not done when `move_and_collide` is called from `move_and_slide` and applied along the body motion instead of `up_direction`.

If that doesn't work or the problem comes from something else we'll figure something out :)

**Comment by piratesephiroth** [comment]
One curious detail is that it makes the KinematicBody slide again when detaching from the colliding obstacle.
I updated my sample project above to display the body's positions.

**Comment by piratesephiroth** [comment]
I'm not sure when it happened but a few things changed in v3.3
1. the undesired sliding on collision is more pronounced now.
2. the "sliding on detach" I mentioned in the previous comment seems to be completely absent.

**Comment by piratesephiroth** [comment]
After observing it more carefully, I see that the problem comes from the way the kinematic body recovers from being stuck.

![image](https://user-images.githubusercontent.com/10672233/122137555-4448e980-ce1b-11eb-89d4-4ec0114df9d9.png)

You see that every time the kinematic body moves right and enters the slope, it's always ejected out pretty much following the slope's normal.
If the process is repeated multiple times, the body will appear to slowly slide up along the slope.

So maybe the solution to make the body always move, collide and then stop is to make it always recover toward the position it was at before the collision?
