### ISSUE TITLE
Tilemap Feature Request

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#4501]
I think a tile-map that handles tiles with scripts and different physics settings would make level design a lot easier.

**Comment by akien-mga** [comment]
http://docs.godotengine.org/en/latest/reference/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think

**Comment by suptoasty** [comment]
Ok, think about it this way, I have 50 enemy nodes or 100 moving platforms my scene tree would be cluttered. It would be easier to have a tile-map instance enemys and enter-active objects like it does tiles instead of forcing developers to duplicate and move these things into place, when they should just be able to click and poof object is where it needs to be. Thus improving godot's ability to develop game scenes for everyone. This next release is about the editor and usability. This feature would be perfect.

**Comment by mateusak** [comment]
I agree. The ideal would be just a copy and paste of your tilemap.scn when you put the tile, with all the things exactly like they are. Even simple things like levers can't be done right now.

**Comment by reduz** [comment]
I don't think adding such things into the tilemap would be possible, as
they are rendered and processed in batch for performance reasons.
But if you mean a helper in the tile editor to instance scenes into cells,
that could be pretty easy.. not sure what the level of integration would be
though

**Comment by mateusak** [comment]
Maybe a individual toggle for tiles ("Is special = true / false") that would do that? So we can use all the functionality of the tile-map for these special tiles. Like set_cell().

**Comment by AlexHolly** [comment]
Maybe something like this https://github.com/AlexHolly/HelloGodot/blob/master/scripts/tilemap.gd
I think this is not my recent version I will check later.

**Comment by suptoasty** [comment]
Andreas Esau's' [asset dropper](https://www.youtube.com/watch?v=ovaSj38j5Vw&feature=youtu.be) plug-in for godot, is a great alternative to what I was trying to propose. Closing Issue
