### ISSUE TITLE
New scripts and resources are not sorted in the file system browser

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#45027]
**Godot version:**
3.2.3

**OS/device including version:**
* macOS 10.15.7
* Windows 10

**Issue description:**
When adding a new script or resource to a folder using right click in the file system browser, the items aren't sorted until Godot is restarted (or the file system browser is refreshed because of some event)

**Steps to reproduce:**
Add an item "c.tres" using right click. After that, add an item "a.tres". It will be put after "c.tres" instead of before it.

**Comment by dploeger** [comment]
Ah, this is a duplicate of #19360 and that was already fixed. Nevermind.

**Comment by dploeger** [comment]
Oh. It was seemingly fixed in an older version because the last comment is two years old. So this problem seems to be still there.

**Comment by fmazan** [comment]
Confirmed in master, I'll take care of this. It seems to be caused by a bug in EditorFileSystem::update_file.
