### ISSUE TITLE
Add child node shortcut (CTRL + A) is not working while the scene dock has been clicked or selected

### ISSUE THREAD

**Issue by mrsir8433** [godotengine/godot#45033]
**Godot version:** 4.0

**OS/device including version:** Windows/ HP Omen 15

**Issue description:** Add child node shortcut (CTRL + A) is pressed while the scene dock has been selected, the add child node button i.e. the '+' button is holding the pressed state and not being released, so it can generate the 'add child node' window.  

**Steps to reproduce:** 1. Click anywhere in the scene dock. Then press (CTRL+A) 

**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @EricEzaM

**Comment by EricEzaM** [comment]
Cannot reproduce Win 10, 4.0 master 98ccaa1

![ctrl_a_works](https://user-images.githubusercontent.com/41730826/104079924-04c91080-5271-11eb-83b1-262cf2c41e17.gif)

**Comment by Mrsir8433** [comment]
https://user-images.githubusercontent.com/65132884/104086674-e3235580-527f-11eb-9949-cfc1f6d62f7c.mov

Here is the issue what's happening. I don't know if this is machine-specific.

**Comment by EricEzaM** [comment]
Wow I think i figured it out... really weird.

Try Pressing Ctrl + A, an **releasing in these orders**, and please confirm results:
* Release **A first** = works, dialog opens.
* Release **Ctrl first** = does not work, button stays in pressed state.

**Comment by jmb462** [comment]
I can confirm that the release order matters.
Need to release A first to work.

**Comment by Mickeon** [comment]
I cannot reproduce this on master, v4.0.alpha.custom_build [00fa4e23e], Windows 10.

**Comment by mrsir8433** [comment]
I interpreted the issue wrong. Actually the issue is the release order of the keys. I should change the issue subject.

**Comment by KoBeWi** [comment]
I don't get this issue. Ctrl is a modifier key. Only A will trigger the shortcut.
If it's only about the release order then its not related to Add Child Node and it's not even a bug.

**Comment by rcorre** [comment]
The issue is that the sequence:
1. Press control
2. Press A
3. Release control
4. Release A

Would open Add Child on 3.5 but will not open Add Child on 4.x.

I tend to hit those keys in a "rolling" stroke that often leads to releasing ctrl before A, to the point where I initially thought the shortcut wasn't working at all in Godot 4. I have to slow down and press my keys very deliberately for it to work in Godot 4, which is not true of Godot 3 or any other program I can think of.

There's a very noticeable impact on user experience for me, so if it's not a bug, it's at least a usability request.

**Comment by KoBeWi** [comment]
So as I said

> Would open Add Child on 3.5 but will not open Add Child on 4.x.

it only works because the shortcut actually triggers at "Press A". You don't need to release it.

**Comment by rcorre** [comment]
> it only works because the shortcut actually triggers at "Press A". You don't need to release it.

That's true in Godot3 but not in Godot4. Is it reasonable to request that shortcuts also trigger on press in Godot4?
It seems that the "on release" behavior leads to a lot of mis-inputs, based on all the people who have found this issue.

I double-checked a number of other programs I use frequently (`st`, `dwm`, `qutebrowser`, `blender`, `vim`) and all seem to interpret shortcuts on press, not release, so it seems reasonable to expect Godot to behave this way.
