### ISSUE TITLE
Text in editor popup menus is cut off

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#45037]
**Godot version:**
4.0 98ccaa1

**OS/device including version:**
Win 10

**Issue description:**
Text in editor popup menus gets cut off. See how the bottom of the O is cut off, as well as all the other text?
![image](https://user-images.githubusercontent.com/41730826/104079948-3215be80-5271-11eb-8d53-35a5400f4009.png)

This was a common issue around the editor but I think there was a PR to fix it? is it back now?

**Comment by mbrlabs** [comment]
It also happens pretty frequently when you scroll some kind of list (e.g. in #44431 if you look closely)

**Comment by bruvzg** [comment]
Menu cut of is regression from #44905 (adds non integer item offset on lowDPI screens), but it's probably better to round coordinates in the font itself to avoid it in the future.
