### ISSUE TITLE
"Can't connect to host" in templates tab

### ISSUE THREAD

**Issue by georgetye** [godotengine/godot#45041]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/15068475/104091328-b1dc6280-524a-11eb-8c07-672c1540910a.png">

**Comment by georgetye** [comment]
Because of this I can't search for anything

**Comment by Calinou** [comment]
@georgetye re you using an HTTP/HTTPS proxy? Are you using a dual-stack IPv4/IPv6 network?

**Comment by KoBeWi** [comment]
Closing due to lack of reply. Please answer the questions in the above comment if you are still experiencing this problem.
