### ISSUE TITLE
Overlapping navigation tiles do not pathfind with Navigation2D

### ISSUE THREAD

**Issue by CyberFoxar** [godotengine/godot#45045]
**Godot version:** 3.2.3

**OS/device including version:** Windows 10 Version 10.0.19042 Build 19042
Not really graphic related, I'll add if needed.

**Issue description:** 

When configuring a Navigation2D Node using a TileMap node, `get_simple_path` does not pathfind between tiles that have overlapping navigation polygons.

This is an issue especially with hexagonal or isometric tilemap.
A workaround is to have pixel-perfect navigation polygons, but this quite bothersome when lots of different tiles are involved.

**Steps to reproduce:**
Create a Navigation2D node and add a TileMap as a child.
Configure the tilemap through the TileMap editor, set the navigation polygon (or grid) to overlap between nearby tiles.
Debug with a Line2D the path generated by Navigation2D

**Minimal reproduction project:**

[MinimalBroken.zip](https://github.com/godotengine/godot/files/5791626/MinimalBroken.zip)

The project is setup with an hexagonal grid. Each tile has a rectangular navigation polygon that overlap between the top and bottom rows. The line2D shows the plotted path. You can see that it can pathfind easily in the row (because navigation polygons do not overlap) but not between rows.
You can see the polygon by ticking debug>"View Navigation".

**Sidenote:**
Related to #43079, which was closed by its owner without reasons.

**Comment by KoBeWi** [comment]
This is most likely fixed in 4.0 with the new navigation changes, but it's still an issue in 3.x (it was recently brought up by a user here https://godotforums.org/discussion/25471/how-to-visually-debug-tilemap-navigation)

**Comment by Zireael07** [comment]
... and it's also an issue in the 3d version in 3.x, too.

**Comment by smix8** [comment]
This is no longer a problem for 2D and 3D in Godot 4.0 and 3.5 with the new NavigationServer when navmesh points / vertex overlap exactly or borders / edges are within `edge_connection_margin` and align so the NavigationServer considers them as connected for pathfinding.

There is still a specific issue with TileSets stored NavigationPolygon resources cause the TileSet Editor stores the NavigationPolygon wrong while normal NavigationPolygon resources created outside the TileSet work just fine.
