### ISSUE TITLE
`String.lstrip` does not strip characters starting with "res"

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#45048]
**Godot version:**
3.2.4 beta 3032b38b5
Keywords: lstrip
Maybe due to a change in #24823.

**OS/device including version:**
Windows 10.

**Issue description:**
The following snippet prints `"cript.gd"`, expected `"script.gd"`
```gdscript
print("res://script.gd".lstrip("res://"))
```

**Steps to reproduce:**
See minimal project. I've found other cases where this also produces error like `"usscript.gd".lstrip("us")`, I haven't pin-pointed more cases to identify what might be the problem yet...

**Minimal reproduction project:**
[string_lstrip_res_45048.zip](https://github.com/godotengine/godot/files/5791677/string_lstrip_res_45048.zip)

**Comment by VedatGunel** [comment]
Related https://github.com/godotengine/godot/issues/43513#issuecomment-727052513?

**Comment by Xrayez** [comment]
Likely, the documentation is quite misleading. Lets not close this issue until this behavior is documented at least, then. 🙂

See Python's [rstrip()](https://docs.python.org/3/library/stdtypes.html?highlight=rstrip#str.rstrip) description in comparison.

I have to be honest that GDScript was my first duck-typed language before I started using Python for real. 😄

**Comment by VedatGunel** [comment]
There is an open issue about it in the docs repo: https://github.com/godotengine/godot-docs/issues/4365

Looks like [trim_prefix](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-trim-prefix) is the more suitable function for your purpose.
