### ISSUE TITLE
Prompt for unsaved scene changes checks incorrect scene

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#4504]
**Operating system or device:**
Windows 10 Pro x64

**Issue description** (what happened, and what was expected):
The check to ask for closing the scene in case of unsaved changes checks the currently displayed scene, not the scene which tab is about to be closed.

This creates two issues:
- The current scene has unsaved changes; closing tabs of saved scenes creates a misleading prompt: "Please Confirm...: Close scene? (Unsaved changes will be lost)"
- Even worse: The current scene is saved; closing tabs with unsaved changes does not create a prompt at all and immediately discards the scene and changes.

**Steps to reproduce:**
Open multiple scenes, change something in one, try closing the unchanged scenes (or the other way round); you'll get a misleading prompt or none where should be one.

**Comment by vnen** [comment]
I can confirm on Arch Linux.
