### ISSUE TITLE
Icons in Project Manager are Shown Half-Size on a High-DPI Screen (macOS)

### ISSUE THREAD

**Issue by name-here** [godotengine/godot#45044]
**Godot version:**
`master` (98ccaa1)

**OS/device including version:**
MacBook Pro 13" 2020 running macOS Catalina

**Issue description:**
Icons are displayed at half the size they should be, with empty space around them (see picture).  As a side note, launching with `--low-dpi` does not, in fact, seem to start the project manager in low-DPI mode, though running with `-e` and an invalid path does for some reason.  Also, I noticed when overlaying the images that almost everything in the UI is a slightly different size and position between High-DPI and Low-DPI.
<img width="1015" alt="High-DPI" src="https://user-images.githubusercontent.com/26884090/104105348-60989700-527b-11eb-85df-a0d65b9f8af5.png">
<img width="1015" alt="Low-DPI" src="https://user-images.githubusercontent.com/26884090/104105351-64c4b480-527b-11eb-8be8-f43abe8eefb0.png">
<img width="1015" alt="Overlay" src="https://user-images.githubusercontent.com/26884090/104105354-67270e80-527b-11eb-8e94-21c8d96658b5.png">

**Steps to reproduce:**
Open Godot, have at least one project in the Project Manager

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
This is a regression from https://github.com/godotengine/godot/pull/41430.

**Comment by name-here** [comment]
It's kind of ironic how `--low-dpi` doesn't activate low-DPI, but other options (when given invalid arguments) do.  `-e`, if not pointed to a `project.godot` file, `--doctool` with no arguments—even giving invalid options (`--this-is-not-a-valid-option`) triggers low-DPI mode, but `--low-dpi` doesn't.
