### ISSUE TITLE
Strange shading with imported fbx models

### ISSUE THREAD

**Issue by abgenullt** [godotengine/godot#45057]
**Godot version:** 3.2.4beta5

Hi everyone,

I want to import the polygon city fbx models (https://syntystore.com/products/polygon-city-pack) I bought.
But the shading looks very strange. It seems, that godot is not using the normals from the fbx file. I also imported the model into blender, to show the difference:

![image](https://user-images.githubusercontent.com/34768615/104108563-0a047a80-52c6-11eb-9578-e44ce2c0cdc3.png)

![image](https://user-images.githubusercontent.com/34768615/104108593-5059d980-52c6-11eb-8173-04d1b1834e5c.png)

So, I've created a little test sphere in blender and try to import that. But with the same result.
[TestSphere.zip](https://github.com/godotengine/godot/files/5791828/TestSphere.zip)

![image](https://user-images.githubusercontent.com/34768615/104108736-52706800-52c7-11eb-8d4f-55dd4201b238.png)

![image](https://user-images.githubusercontent.com/34768615/104108743-6320de00-52c7-11eb-8069-959e0fb41ebc.png)

Is there something, I'm doing wrong or is this a bug?

Regards
abgenullt

**Comment by Calinou** [comment]
cc @RevoluPowered

**Comment by lyuma** [comment]
i tried with a smooth shaded sphere from blender and it looked broken the same way as flat shading as in the OP.

Also, can reproduce on godot 4.0.dev ( b24c24f ) as well, but differently: mostly smooth (even if exported with shade flat) but a weird bias causing a seam.
![image](https://user-images.githubusercontent.com/39946030/107230314-c63f8680-69d3-11eb-83f1-4439307e27fe.png)
 if I remove uv seams (e.g. by scaling uv to 0 along the x axis in blender), the normal seam disappears and normals become smooth, even if exported with flat shading
So, on godot 4, it seems almost like it's recalculating normals on import (but incorrectly, taking uv seams into account), which I do not want.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
