### ISSUE TITLE
False positive message when intentionally round floats: "Narrowing conversion (float is converted to int and loses precision)."

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#45052]
**Godot version:**

3.2.3

**OS/device including version:**

Win7

**Issue description:**

False positive message when intentionally round floats.

**Steps to reproduce:**
```
	var a: int = floor(3.0)
	print(a)

```
outputs:
> Narrowing conversion (float is converted to int and loses precision).

**Minimal reproduction project:**

**Comment by pycbouh** [comment]
`floor` still returns a `float`. You might want to do `int(floor(3.0))` instead to cast it to int. Or just `int(3.0)` for that matter.

**Comment by CitrusWire** [comment]
> `floor` still returns a `float`. 

:-o

How does that make an semblance of sense? You know what, I don't want to know.

**Comment by KoBeWi** [comment]
It's not a bug. `floor()` indeed returns `float`, so the warning technically makes sense. Use `int(3.0)` if you want to avoid it, it has the same effect. Also see #19262

btw in 4.0 I think there are plans for `floori()` and similar methods.

**Comment by CitrusWire** [comment]
> It's not a bug. `floor()` indeed returns `float`, so the warning technically makes sense. 

It's "technically" correct, but from the user's perspective it's still a false positive. Ah well, 4.0. Thanks.
