### ISSUE TITLE
Allow fonts to be previewed from editor.

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#45053]
**Godot version: All versions**

**OS/device including version: All**

**Issue description:**

Many projects have multiple fonts, previewing these is currently cumbersome.
When I want to see what e.g. 'Droid.ttf' looks like from the godot editor, double clicking does nothing.
I have to right click and 'show in file manager' and then double click to see the font preview.

Maybe Godot could possibly open up the font in the OS Font previewer, or a user defined font viewer.

**Steps to reproduce:**
Double clicking a font, nada happens.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-propopsals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal.
