### ISSUE TITLE
[GodotPhysics] KinematicBody3D with move_and_slide() move bumpy/jittering on flat surface

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#45060]
**Godot version:**

- Godot 3.2.4 beta 5

**OS/device including version:**

- Windows 10 Home 64-bit, Version 20H2, OS build 19042.685
- Intel® UHD Graphics 620, Version 27.20.100.9126

**Issue description:**

I move a KinematicBody3D with velocity input to the move_and_slide() using the GodotPhysics engine. It has a bumpy ride on a completely flat floor(StaticBody), as shown in my screen recording below:

https://user-images.githubusercontent.com/1403194/104109926-7628b380-52b1-11eb-91a2-6e683d878c7f.mp4

**Steps to reproduce:**

1. Open the reproduction project.
2. Choose the appropriate Vector 3 Print in the Player's script available at the inspector tab.
3. Run the project, the Player will move bumpy/jittering on a flat surface.

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/5791931/test.zip)

**Comment by nonunknown** [comment]
While the bug isnt solved in general, I could solve this problem in my project, so I recommend this to you:

Option 1:
* Scale the child-most nodes until when you change cordinates and its almost integer only i.e: before if you move the cube in the editor from 0.01 to 0.05 now if you move it (due to huge scale) from 1 to 5, this is "easier" for physics engine to calculate

Option 2:
* Use a plugin called smoothing-addon and since it will make things smoother you can also change physics Fps to something like 15-30 fps this will save a lot of resources 👍

**Comment by kreaninw** [comment]
> While the bug isnt solved in general, I could solve this problem in my project, so I recommend this to you:
> 
> Option 1:
> 
> * Scale the child-most nodes until when you change cordinates and its almost integer only i.e: before if you move the cube in the editor from 0.01 to 0.05 now if you move it (due to huge scale) from 1 to 5, this is "easier" for physics engine to calculate
> 
> Option 2:
> 
> * Use a plugin called smoothing-addon and since it will make things smoother you can also change physics Fps to something like 15-30 fps this will save a lot of resources 👍

Thanks for your suggestions ❤

Option 1: I think it's too complicated as a solution. Therefore I put a condition before applying the gravity instead. Since GodotPhysics does a reliable job to detect the floor with _is_on_floor()_, unlike the current Bullet engine which is known to have this kind of issue, i.e. #33833 or #45058. Moreover, testing whether the body is on the floor _before_ applying gravity makes the falling of the body be more simple to implement and more natural, as the gravity value will be interpolated by the physics instead of being at the maximum value all the time.

Option 2: I tried the smoothing-addon but it didn't help at all. I believe this issue is not relating to the jittering from the un-alignment of the PhysicsRep and VisualRep, which the addon is trying to solve. If you watch the issue closely, you will see that the _y translation_ of the cube changes its position while being moved on a flat surface. It can only mean that there's a problem with how the physics work somehow.
