### ISSUE TITLE
Vulkan: 3D viewport no longer uses nearest-neighbor filtering when Half Resolution is enabled, resulting in a loss of sharpness

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#45081]
**Godot version:** Git https://github.com/godotengine/godot/commit/c3b23f02031dbdc96afa09e40fe51ffe345038ef, but applies all the way back to the initial Vulkan renderer

**OS/device including version:** Fedora 33, GeForce GTX 1080

**Issue description:** Unlike Godot 3.x's GLES3 and GLES2 renderers, the Vulkan renderer uses linear filtering when **Half Resolution** is enabled in the 3D viewport's **Perspective** menu. However, with a resolution scale of 50%, you can use nearest-neighbor filtering to benefit from a sharper image with no performance cost – in fact, nearest-neighbor filtering can be minutely faster.

We should revert to the `3.x` behavior, at least when an integer scaling factor is used (1/2, 1/3, 1/4, …).

I think that by default, the engine should use nearest-neighbor filtering when using an integer scale factor and linear filtering with fractional scale factors (or scale factors above 100%). A Viewport property could be added to toggle between "Automatic", "Always Linear" and "Always Nearest" filtering modes.

See https://tanalin.com/en/articles/integer-scaling/ for more information.

**Steps to reproduce:** In a 4.0 development build, enable **Half Resolution** in the 3D viewport's **Perspective** menu.

**Minimal reproduction project:** N/A

**Comment by KoBeWi** [comment]
I added this line:
```C++
subviewport_container->set_texture_filter(shrink ? TEXTURE_FILTER_NEAREST : TEXTURE_FILTER_PARENT_NODE);
```
here:
https://github.com/godotengine/godot/blob/ecde7ce8345a54becf65c166e1c9efc640e37837/editor/plugins/node_3d_editor_plugin.cpp#L414-L417

Before this change:
![godot windows tools 64_mnmgbadwZC](https://user-images.githubusercontent.com/2223172/172017365-979226a6-5757-4a37-8291-64b0a44d4862.gif)
After this change:
![godot windows tools 64_l9ykAvzgcP](https://user-images.githubusercontent.com/2223172/172017352-f7e4a1fe-8850-4f8b-9aff-500d4016d94a.gif)

Does this solve the issue? 🤔

**Comment by Calinou** [comment]
> I added this line:
> 
> ```c++
> subviewport_container->set_texture_filter(shrink ? TEXTURE_FILTER_NEAREST : TEXTURE_FILTER_PARENT_NODE);
> ```
> 
> here:
> 
> https://github.com/godotengine/godot/blob/ecde7ce8345a54becf65c166e1c9efc640e37837/editor/plugins/node_3d_editor_plugin.cpp#L414-L417
> 
> Before this change: ![godot windows tools 64_mnmgbadwZC](https://user-images.githubusercontent.com/2223172/172017365-979226a6-5757-4a37-8291-64b0a44d4862.gif) [ ](https://user-images.githubusercontent.com/2223172/172017365-979226a6-5757-4a37-8291-64b0a44d4862.gif) ![godot windows tools 64_mnmgbadwZC](https://user-images.githubusercontent.com/2223172/172017365-979226a6-5757-4a37-8291-64b0a44d4862.gif) [ ](https://user-images.githubusercontent.com/2223172/172017365-979226a6-5757-4a37-8291-64b0a44d4862.gif) After this change: ![godot windows tools 64_l9ykAvzgcP](https://user-images.githubusercontent.com/2223172/172017352-f7e4a1fe-8850-4f8b-9aff-500d4016d94a.gif) [ ](https://user-images.githubusercontent.com/2223172/172017352-f7e4a1fe-8850-4f8b-9aff-500d4016d94a.gif) ![godot windows tools 64_l9ykAvzgcP](https://user-images.githubusercontent.com/2223172/172017352-f7e4a1fe-8850-4f8b-9aff-500d4016d94a.gif) [ ](https://user-images.githubusercontent.com/2223172/172017352-f7e4a1fe-8850-4f8b-9aff-500d4016d94a.gif)
> 
> Does this solve the issue? 🤔

Looks like that fixes it 🙂 

That said, it may be better to rework Half Resolution to set the Viewport's `scaling_3d_scale` instead of shrinking the viewport. This doesn't support nearest-neighbor filtering yet, but this should be straightforward to add.

**Comment by KoBeWi** [comment]
> That said, it may be better to rework Half Resolution to set the Viewport's scaling_3d_scale instead of shrinking the viewport.

Open a new issue for this.
