### ISSUE TITLE
Dumb Question: Does Queue_free's end of the frame deletion refer to the game's rendering frame, or physics' frame

### ISSUE THREAD

**Issue by GhbSmwc** [godotengine/godot#45082]
Some instructions such as queue_free and other things rely on the _frame_ (in this case, at the end of the frame) to do certain things (such as deleting node/scene)

However, reading some of the info, such as this: https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-queue-free it never mentions what type of frame (rendering frames? Physics frames?). Is it referring to the main game's loop that the user made the code intended to run constantly (akin to minecraft's “ticks”)?

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
