### ISSUE TITLE
Black 3D models when using GLES2 [Intel HD 3000, Windows 10]

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45099]
**Godot version:**
3.2.4 beta 5 mono

**OS/device including version:**
Windows 10 x64
Intel HD 3000

**Issue description:**
When opening a scene and importing models they're all black, Also cant change render mode to "Unshaded"
![image](https://user-images.githubusercontent.com/58845030/104166752-05c98180-53da-11eb-986d-b09397d1bc3b.png)

**Steps to reproduce:**
Import 3D model using gles2

**Minimal reproduction project:**
[MonoGame.zip](https://github.com/godotengine/godot/files/5794989/MonoGame.zip)

**Comment by Zireael07** [comment]
Do you have a light somewhere in your scene?

Also what is your GPU card?

**Comment by nonunknown** [comment]
lights solve the problem dude, but "base" scenes , in this case the car will be used in antoher scene, doesnt make sense to put light just to see models.

Also GPU is described in "OS/device including version"

**Comment by akien-mga** [comment]
Works fine here on Linux with Intel HD 630:

![Screenshot_20210111_115340](https://user-images.githubusercontent.com/4701338/104171911-aed8a200-5403-11eb-83eb-12f7bbb54ada.png)

Make sure that your `default_env.tres` is properly configured, that's what provides default lighting if you don't define a `WorldEnvironment` in your scene.

>  When opening a scene and importing models they're all black, Also cant change render mode to "Unshaded"

That's expected, those features are not supported on GLES2.

**Comment by nonunknown** [comment]
Makes sense, with linux I could Use Gles3 too, bad Idea going back to windows LOL

**Comment by akien-mga** [comment]
I'll close as I'm fairly sure this is the issue, and it's a driver problem that we can't fix:

> It might be the ProceduralSky of the default environment which doesn't work on your hardware. You can use PanoramaSky with a skybox instead which should be less heavy on the IGP.
