### ISSUE TITLE
New CPU lightmapper does not recognize UV2 coordinates generated by Godot

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#45098]
**Godot version:**
3.2.4.beta5+lightmapper from https://github.com/godotengine/godot/pull/44628#issuecomment-757508966

**OS/device including version:**
Windows 10, GeForce GTX 660/PCIe/SSE2, i7-3820 @3.6GHz

**Issue description:**
Import a model into Godot (i created one in Blender and it does not have a secondary uv map) and select "Generate Lightmaps" in the import settings. Setup the lightmapper and bake the scene. This error shows up:

![Capture](https://user-images.githubusercontent.com/8750135/104163782-408de280-53f7-11eb-86d4-1e3b5b41932a.PNG)

If you exit Godot and reopen the project again it works. cc @JFonS

**Minimal reproduction project:**
[LightmapperTester2.zip](https://github.com/godotengine/godot/files/5794849/LightmapperTester2.zip)

**Comment by JFonS** [comment]
Did you re-import the scene after selecting the "Generate Lightmaps" import option? Also, assuming you did re-import, did you close and re-open the scene in the editor? 

Given the way Godot handles resources, unloading and loading the scene is sometimes needed, otherwise the data is not updated properly.

**Comment by mbrlabs** [comment]
Yes i reimported the scene after enabling the import option. Closing and reopening the scene with the `BakedLightmap`  in it works as well. So you don't have to close the whole editor.

**Comment by JFonS** [comment]
Then this can be reproduced as well in the old lightmapper. It's not really related to the lightmapper itself, but the way the editor handles resources.

Closing this issue as we already have #14338 to track any changes on the re-import/re-load usability problems.

**Comment by mbrlabs** [comment]
Yeah, i didn't test this with the old lightmapper so closing this in favor of the other issue is fine.
