### ISSUE TITLE
New CPU Lightmapper doesn't work on MacOS with IntelGPU

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#45091]
**Godot version:**

Godot Engine v3.2.4.beta5 lightmapper bulid

**OS/device including version:**

![屏幕快照 2021-01-11 13 58 21](https://user-images.githubusercontent.com/64188282/104150544-16e3b400-5415-11eb-8144-49059be3c273.png)

**Issue description:**

after baking, I can't see anything but a piece of gray model

also I got error message when use GLES2
![屏幕快照 2021-01-11 13 41 23](https://user-images.githubusercontent.com/64188282/104150646-83f74980-5415-11eb-9d28-dc1c1f2072a5.png)

got error message when use GLES3
![屏幕快照 2021-01-11 13 53 59](https://user-images.githubusercontent.com/64188282/104150677-9a9da080-5415-11eb-8bf2-73193f9aa3b5.png)
![屏幕快照 2021-01-11 14 31 39](https://user-images.githubusercontent.com/64188282/104152182-c6bb2080-5419-11eb-8a4f-19fe4dbb62f0.png)

before baking
![屏幕快照 2021-01-11 13 54 36](https://user-images.githubusercontent.com/64188282/104150695-ac7f4380-5415-11eb-96ef-ff1012bce7da.png)

after baking
![屏幕快照 2021-01-11 13 54 23](https://user-images.githubusercontent.com/64188282/104150711-b9039c00-5415-11eb-8999-4f54d5c41e33.png)

**Steps to reproduce:**
find some model to test
imported the model to engine
unwarp lightmap for each mesh
enabled "Use In Baked Light"
add a directional light and turn on shadow
add BakedLightmap node to the scene tree
click bake button and wait for finsihing

**Minimal reproduction project:**

https://drive.google.com/file/d/1GwlClcFxspsK7swA2SqnSnsIZWlupanF/view?usp=sharing

**Comment by snougo** [comment]
here is the Baked Atlas Texture after baking, but it looks like this texture can't apply to the model
![屏幕快照 2021-01-11 14 35 12](https://user-images.githubusercontent.com/64188282/104152343-3a5d2d80-541a-11eb-94ab-7f51f2a0fedf.png)

**Comment by JFonS** [comment]
Looks like I made some mistakes on the GLSL code, I will take a look.

**Comment by snougo** [comment]
has be fixed in beta6

**Comment by JFonS** [comment]
Thanks for testing!
