### ISSUE TITLE
UV offset of material with a normal map doesn't work . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot#45094]
**Godot version:**
3.2.3 official, Mono . .

**OS/device including version:**
nVidia 1050 Ti GTX 4 GB, Windows 10 . .

**Issue description:**
When I try and animate the UV's, of a texture, to make it ' move ' across a surface, the ALBEDO correctly moves, but the normal map doesn't move . .

Note, before offset the UV, the normal map ' shadows ', on surface, are as expected . . .
<img width="960" alt="Skærmbillede (845)" src="https://user-images.githubusercontent.com/61069740/104153681-3b269d00-53e3-11eb-8ddc-290198fba067.png">

But, as UV offset is moved, towards 1, the normal map isn't ' duplicated ', like the ALBEDO . .
<img width="960" alt="Skærmbillede (846)" src="https://user-images.githubusercontent.com/61069740/104153706-4ed20380-53e3-11eb-8ba9-96f04b6eadd6.png">

So, for some reason, when animating the UV's, the normal isn't moving, as it should . .

<img width="960" alt="Skærmbillede (847)" src="https://user-images.githubusercontent.com/61069740/104153726-5c878900-53e3-11eb-8833-95b1f183171b.png">

This could mean problems, for animating stuff, like rivers or, the ocean, if the normal map doesn't move correctly . .

**Steps to reproduce:**

Make a material, add an albedo AND, a normal map, and try moving the UV offset, the albedo moves as one would think, but the normal map, is only projected, on the first tile, ( 0 - 1 x, or y off-set ), after that, it disappears . . :( . .

**Minimal reproduction project:**
It's very easy to replicate, not sure if it's something I did, made a new material, and tried making it work, it didn't, for some reason . . . .

**Comment by clayjohn** [comment]
It sounds like the normal map is not repeating as the UV becomes greater than 1. If that's the case then the solution is to set the "repeat" flag on the normal map texture when you import it.

**Comment by Calinou** [comment]
Closing per @clayjohn's comment.

**Comment by jasperbrooks79** [comment]
Thank you :OO <3 . .
