### ISSUE TITLE
Vulkan: what MacOSes are supported?

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#45092]
**Godot version:**

Godot 4.0.dev (a594243eee07b1237572cfae3291e3694e8395a3)

**OS/device including version:**

MacOSX 10.15.7 (19H2)
Radeon RX 580 8 Gb
Metal support: macOS GPUFamily2 version 1

**Issue description:**

When I start godot I get error message:
```
Godot Engine v4.0.dev.custom_build.a594243ee - https://godotengine.org
Using ICU / HarfBuzz / Graphite text server...
ERROR: No surface extension found, is a driver installed?
   at: _initialize_extensions (drivers/vulkan/vulkan_context.cpp:267)
ERROR: Could not initialize Vulkan
   at: DisplayServerOSX (platform/osx/display_server_osx.mm:3850)
```
![Снимок экрана 2021-01-11 в 09 21 55](https://user-images.githubusercontent.com/1177068/104151579-7da1a700-53ee-11eb-86ff-ca053c097552.png)

**Steps to reproduce:**
Run godot4 on MacOSX.

**Minimal reproduction project:**

No project.

**Comment by bruvzg** [comment]
Is [Vulkan SDK](https://vulkan.lunarg.com/sdk/home#mac) installed? There's no Vulkan runtime on macOS by default.

If it's installed using system paths (`sudo ./install_vulkan.py`) it should work as is, if not `MoltenVK.dylib` should be added to the Godot app bundle. Or, if Godot is not bundled, `VK_ICD_FILENAMES` environment should be set to the path of SDK driver config file (e.g. `export VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json`). See https://vulkan.lunarg.com/doc/sdk/1.2.162.0/mac/getting_started.html for more details.

**Comment by DrMoriarty** [comment]
@bruvzg Thank you very much!
