### ISSUE TITLE
Vulkan: 3D grid and origin gizmos cast shadows from directional lights

### ISSUE THREAD

**Issue by MagdielM** [godotengine/godot#45109]
**Godot version:**
Commit hash: 98ccaa1bad97bdb83b2afd6a4df6f7a392745592

**OS/device including version:**
OS: Windows 10
GPU: AMD Radeon RX 480M
Driver version: 20.20.33.02-201105a-360732E-RadeonSoftwareAdrenalin2020
Backend: Vulkan renderer

**Issue description:**
The grid and origin gizmos cast shadows from a `DirectionalLight3D` in a 3D scene. Omni lights and spot lights are not affected.
![image](https://user-images.githubusercontent.com/56076033/104231297-223edb80-5425-11eb-96d9-ec39ce47ab38.png)

The shadows appear to originate at an offset from the on-screen position of the grid (in the XZ plane, at least). In the following image, the rightmost capsule is halfway through the grid and remains unaffected. The leftmost capsule, further below the grid, shows the grid shadows being partially cast onto it.
![image](https://user-images.githubusercontent.com/56076033/104231441-5adeb500-5425-11eb-901f-52333a6e1491.png)

The issue also affects origin guide gizmos by themselves, although it seems to only affect lines nearly perpendicular to the light's direction.
![directional-light-3d-shadow-bug-origin-gizmo](https://user-images.githubusercontent.com/56076033/104231945-05ef6e80-5426-11eb-8c77-99425573fe76.gif)

**Steps to reproduce:**
In an empty 3D scene:
1. Ensure both the 3D grid and origin gizmos are shown  in the scene view.
2. Place a `DirectionalLight3D` in the scene. For visualization purposes, ensure that the light's rotation does not coincide with any of the grid planes.
3. Place any number of `MeshInstance3D`s in the scene.
4. Move each mesh a small distance in the direction facing away from the light relative to the grid plane. For instance, for a directional light rotated -45&deg; on the X and Y axes, move the mesh towards -Y for the XZ grid, towards +X for the YZ grid, and towards -Z for the XY grid.

**Minimal reproduction project:**
[GridShadowTest.zip](https://github.com/godotengine/godot/files/5798117/GridShadowTest.zip)

**Comment by lawnjelly** [comment]
Maybe masks not working / implemented? Yeah there's no masks in the `dynamic_bvh.h` culling functions, and I'm guessing maybe the IDE uses masks to prevent shadows on the grid etc.

**Comment by KoBeWi** [comment]
Doesn't happen in alpha 8

**Comment by Calinou** [comment]
There's a variant of this bug still occurring to my knowledge: https://github.com/godotengine/godot/issues/55390
