### ISSUE TITLE
set_rot() is in degree in editor but in radian in script

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#4511]
**Operating system or device:**
Windows 10 Pro

**Issue description** (what happened, and what was expected):
When setting rot from script you must use deg2rad, but in editor it's in degree. It was supposed to be either everything in radians or in degrees. At the very least something in the docs saying that it was in radian.

**Steps to reproduce:**
Attach a new script to a sprite and write set_rot(80). It's going to be completely erroneous. Now put set_rot(deg2rad(80)). It works just fine.

**Comment by rgrams** [comment]
+1. This inconsistency has annoyed me quite a bit. Everything should be the same, presumably in degrees.

**Comment by mattiascibien** [comment]
I guess this is the offending piece of code:
```c++
void Node2D::set_rot(float p_angle) {
	if (_xform_dirty)
		((Node2D*)this)->_update_xform_values();
	angle=p_angle; //Should this be with a deg2rad function call?
	_update_transform();
	_change_notify("transform/rot");
}
```
Found [here](https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/scene/2d/node_2d.cpp#L151-L158) 

If needed I can fix it pretty easily i think but I want to ask the devs first.

**Comment by akien-mga** [comment]
> I guess this is the offending piece of code:

The issue is not here, ``set_rot`` is defined to use radians in the whole code base, which is pretty normal when doing mathematic operations. In Node2D, you have ``_set_rotd`` for degrees.

The problem is here: https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/scene/2d/node_2d.cpp#L403
The ``transform/rot`` parameter uses the ``_set_rotd`` method, so expects degrees. But when switching to GDScript, people use ``set_rot`` which expects radians.

Not sure how to fix that without breaking all existing Godot games :)

**Comment by mattiascibien** [comment]
I guess I read the issue all wrong. Sorry.

> Not sure how to fix that without breaking all existing Godot games

exactly what I was thinking.

**Comment by reduz** [comment]
This behavior is intended, Godot works with radians internally, but will
show degrees when presented to the user via the UI.

**Comment by akien-mga** [comment]
As I mentioned on Facebook:

> We could maybe expose ``set_rotd`` to GDScript, and rename the arguments to "radians" and "degrees" respectively so that the autocompletion makes it obvious.

Will implement that.

**Comment by blurymind** [comment]
@akien-mga thank you. Sorry for the inconvenience.

**Comment by akien-mga** [comment]
No problem, I do agree that this apparent inconsistency is confusing, even if it has a good justification as @reduz mentioned.

**Comment by blurymind** [comment]
Thank you !
