### ISSUE TITLE
Infinite error spam when shader has Sampler2D uniform

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#45114]
**Godot version:**

8e514bb

**Steps to reproduce:**
1. Create a 2D node
2. Add this shader to it
```
shader_type canvas_item;

uniform sampler2D test;
```
3:
![image](https://user-images.githubusercontent.com/2223172/104245949-7073cf00-5465-11eb-9afc-1d5dda7ef13b.png)
forever.

Loading a texture to the material doesn't fix it.

**Comment by Chaosus** [comment]
@KoBeWi This issue has not been reproduced anymore at least for me - maybe it's fixed?

**Comment by KoBeWi** [comment]
Yeah seems fixed.
