### ISSUE TITLE
Engine crashes during reparenting caused by collision signal

### ISSUE THREAD

**Issue by jvetulani** [godotengine/godot#45112]
**Godot version:**
Godot_v3.2.4-beta5_mono
Project using c#

**OS/device including version:**
OS: Ubuntu 20.04 on Kernel 5.10.4-051004
GPU: NVIDIA GTX 1080
CPU: Intel i7-8700K

**Issue description:**
KinematicBody enters an area, which sends a signal to a script that changes the KinematicBody's parent node.
Engine either crashes completely generating a crash report json, or in the case of the minimal repro project just hangs.

**Steps to reproduce:**
Press Play, engine crashes the moment the left capsule (one in a Characters group) touches the area.

**Minimal reproduction project:**
[CollisionSignalReparentingCrash.zip](https://github.com/godotengine/godot/files/5798281/CollisionSignalReparentingCrash.zip)

**Comment by Calinou** [comment]
@jvetulani Can you include a minimal reproduction project written in GDScript? We recommend always doing this unless an issue can only be reproduced in C#. This makes it easier for contributors to run the project locally, as not everyone has a Mono setup available.

**Comment by jvetulani** [comment]
> @jvetulani Can you include a minimal reproduction project written in GDScript? We recommend always doing this unless an issue can only be reproduced in C#. This makes it easier for contributors to run the project locally, as not everyone has a Mono setup available.
> 
> Additionally, this will rule out whether this issue is C#-specific or not.

I have no experience with GDScript, it may take me a while.

**Comment by KoBeWi** [comment]
When you change parent, the body is entering area again, which triggers the signal again. Your script just enters into an infinite loop of callbacks.

You can avoid this by adding a variable that makes the body entered callback ignored when true.

**Comment by jvetulani** [comment]
> When you change parent, the body is entering area again, which triggers the signal again. Your script just enters into an infinite loop of callbacks.
> 
> You can avoid this e.g. by adding a variable that makes the body entered callback ignored when true.

True, this is not a bug as such then you're absolutely right, but I do consider it as potentially broken or incomplete behaviour as I cannot find a satisfactory, easy and user friendly solution to the problems it poses.

For instance if you plan to parent a player object to a platform when entering an area, and then add the player back to it's original parent when leaving the area you're stuck in a loop no matter how you set your parameters as area always considers it as a new object and starts bouncing it back and forth without an option to reliably set a condition to false - that the player has left the area. You can use a second area but they cannot be close enough to each other that the player will be in two at the same time, regardless it's still a hacky way of handling it...

If a reliable solution to this exists it would be great to have it documented.
