### ISSUE TITLE
TabContainer should use Tabs instead of reimplementing them

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4512]
As discussed today on IRC [0], TabContainer `scene/gui/tab_container.cpp` should be modified to rely on Tabs `scene/gui/tabs.cpp` instead of reimplementing tabs itself.

The Tabs class has grown to be feature-rich (though it could still use some cleanup even after #4506), so it should stay as the sole implementation.

[0] http://godot.eska.me/irc-logs/devel/2016-05-01.log

**Comment by StraToN** [comment]
Tabs is the class describing only the tab buttons on top of the TabContainer. There is no Container in the Tabs class, simply each tab sends a signal when an action happens on it: ```tab_changed(int tab_clicked)```, ```tab_close(int tab_clicked)``` and ```right_button_pressed(int tab_clicked)```.

Thus, since Tabs buttons should only be used as such (ie. as "simple Button"s), Tabs class may itself have the container. I can take that one.

**Comment by akien-mga** [comment]
Well I think the idea would be to keep TabContainer, but replace its own tab "buttons" by an instance of Tabs.

**Comment by StraToN** [comment]
Alright. I'm in ;)

**Comment by Anutrix** [comment]
Any updates?

**Comment by pycbouh** [comment]
From the recent discussions it's not clear if we want to keep both, delete one, or make them work together. There is a proposal for removal: https://github.com/godotengine/godot-proposals/issues/2129 There are also several proposals for features in `TabContainer` that could be solved by a more unified solution.

At any rate, there needs to be a proper proposal now for any change like that. So, closing.

**Comment by akien-mga** [comment]
In the end, this was implemented for 4.0 :)

Fixed by #58687.
