### ISSUE TITLE
Textures not loading up

### ISSUE THREAD

**Issue by AaryanGamez** [godotengine/godot#45130]
Hello there, I have this issue which is→
When I try to load a texture, the thing just doesn't work. It doesn't even load the thing.

Godot version: 3.2.3 stable release

My pc: 16 gb ram with i7 processors
AMD Radeon RX 6800 graphics card

Bye the way it is a jpg file
This worked properly some days ago but dienst now
Plus i didnt update godot

**Comment by Calinou** [comment]
@AaryanGamez Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
