### ISSUE TITLE
Unit Offset displayed as integer

### ISSUE THREAD

**Issue by henkz1** [godotengine/godot#4513]
**Operating system or device:**
Ubuntu 16.04

**Issue description** (what happened, and what was expected):
Entering 0.5 in "Unit offset" for PathFollow/PathFollow2D is displayed as 0, it is still set to 0.5 but the box only shows 0 or 1, it displays correct value while editing. I think this bug is for all properties with "PROPERTY_HINT_RANGE" where step is 0.0001

**Steps to reproduce:**
Drag the slider or enter decimal value for Unit Offset on PathFollow node

**Comment by akien-mga** [comment]
Could you check if 1555608 fixed this issue?

**Comment by henkz1** [comment]
Yes fixed in https://github.com/godotengine/godot/commit/1555608276abda42bd2ced9f949e1afb5bc0a6dd
