### ISSUE TITLE
GDScript 2.0: Using Vector2.INF or Vector3.INF causes parse error

### ISSUE THREAD

**Issue by lahouaridc** [godotengine/godot#45139]
**Godot version:** latest master, custom build based on commit:8e514bbf6ab3d2cff4daeb64e842bd8846c07046
platform = "linuxbsd"
bits = 64
target = "release_debug"
tools = "yes"
module_mono_enabled = "no"

**OS/device including version:** Gentoo linux

**Issue description:**
using Vector3.INF causes parse errors in editor:
```
 Parser bug (please report): Trying to check compatibility of unset value type
- Parse Error: Expected identifier after "." for attribute access.
modules/gdscript/gdscript.cpp:816 - Method/function failed. Returning: ERR_PARSE_ERROR
```
**reproduction:**
in any gdscript that extends Node try using Vector3.INF constant.

**Comment by Maran23** [comment]
Just got this error as well.
So I can still confirm this in 0160fea.

Just create a script and paste in: `var target_position: Vector2 = Vector2.INF`

**Comment by TokisanGames** [comment]
Use `Vector2(INF, INF)` until #61744 is merged.
