### ISSUE TITLE
Building temporary binary for Mono glue crashes.

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#45146]
**Godot version:**
 [d214869](https://github.com/godotengine/godot/commit/d2148692bc5433a5d866bf59138b718c0fa6cae5)

**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan
[Compiler used](https://github.com/mstorsjo/llvm-mingw)

**Issue description:**
Compilation of Mono glue crashes. [Possibly related commit](https://github.com/godotengine/godot/commit/1218441b16bd0d5bdbcf93c11e77f1e999f0183c)
In fact, after checking out [commit before](https://github.com/godotengine/godot/commit/3bce846e0cdc172b8cb17370c5354dc61890bf91) lets me build temporary binary.

<details>
    <summary>Error:</summary>

>=====
b"modules\\mono\\utils\\mono_reg_utils.cpp:176:59: error: cannot initialize a parameter of type 'String *' with an rvalue of type 'bool'\r\n        OS::get_singleton()->execute(vswhere_path, vswhere_args, true, nullptr, &output, &exit_code);\r\n                                                                 ^~~~\r\n.\\core/os/os.h:132:87: note: passing argument to parameter 'r_pipe' here\r\n        virtual Error execute(const String &p_path, const List<String> &p_arguments, String *r_pipe = nullptr, int *r_exitcode = nullptr, bool read_stderr = false, Mutex *p_pipe_mutex = nullptr) = 0;\r\n                                                                                             ^\r\n1 error generated.\r\n"
=====
scons: *** [modules\mono\utils\mono_reg_utils.windows.tools.64.o] Error 1
scons: building terminated because of errors.

</details>

**Steps to reproduce:**
Compile the source with following parameters:
`scons use_mingw=yes use_llvm=yes tools=yes module_mono_enabled=yes mono_glue=no`

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
I don't have a crash here on Linux, building with `mono_glue=no` and generating the glue works, then building with the generated glue does fail with:
```
Export/XcodeHelper.cs(30,94): error CS1739: The best overload for 'Execute' does not have a parameter named 'blocking' [/home/akien/Projects/godot/godot.git/modules/mono/editor/GodotTools/GodotTools/GodotTools.csproj]
Build/MsBuildFinder.cs(184,17): error CS1739: The best overload for 'Execute' does not have a parameter named 'blocking' [/home/akien/Projects/godot/godot.git/modules/mono/editor/GodotTools/GodotTools/GodotTools.csproj]
```
