### ISSUE TITLE
Profiler Time only show two decimals

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#45140]
**Godot version:**
Godot 3.2.3 stable

**Issue description:**
There was a regresión in profile time information, in older godot versions show five decimals in time column, now show two, which isn't useful considering a frame at 60 fps is 0.016 ms, worse in 144 fps setups (0.00694 ms), so most of the frame times are below the two decimal range and the editor shows 0.00 for everything.
![x5yYIYq](https://user-images.githubusercontent.com/12376042/104365903-5d114400-54f7-11eb-8c47-57e6c823fcd5.png)
Looking at source code, the culprit is this line: 
https://github.com/godotengine/godot/blob/3.2.3-stable/editor/script_editor_debugger.cpp#L877
label = rtos(value * 1000).pad_decimals(2) + " ms";
Where someone hardcoded the decimal number. My proposal to fix this issue is expose the decimal number in editor settings using 5 as default value.

**Steps to reproduce:**
Open profiler and profile a scene, then look at the time values.

**Comment by Calinou** [comment]
Time is now shown in milliseconds rather than seconds. Therefore, you now see nearly as much information as before, as time was previously shown in *seconds*.

**Comment by HeartoLazor** [comment]
Oh understood, still as you see in my screenshot for example shows 0.15 ms for all scripts and the methods 0.00, So I can't evaluate the performance weight of each method. I'm assuming they are in the 0.00x range. A third decimal can be useful in this case, so the point about a configuration variable for decimals still is valid, maybe with default value of 2 instead of 5.

**Comment by Calinou** [comment]
> I'm assuming they are in the 0.00x range. A third decimal can be useful in this case, so the point about a configuration variable for decimals still is valid, maybe with default value of 2 instead of 5.

It's more likely that the profiler simply isn't able to trace at this level of precision. I doubt the GDScript profiler was designed for high levels of accuracy, since that would impact performance too much.

**Comment by HeartoLazor** [comment]
Update:
I increased the limit of profiled methods to 512 (as is dangerously hardcoded limit to this value) and now the profiler show more coherent values:
![image](https://user-images.githubusercontent.com/12376042/104376517-e2025a80-5503-11eb-92d1-8045a4d74036.png)
So this means the methods between the method limit aren't ordered by frame time, so the algorithm can cut methods causing bottlenecks using the default values. Worse the script function total time seems to be using only the frame time between the method limit.
@Calinou Should I create a new issue for this problem? Idk what should be the best solution, maybe default to a higher value the limit?
