### ISSUE TITLE
OpenGL

### ISSUE THREAD

**Issue by XVUser** [godotengine/godot#45151]
**Godot version:**
v3.2.3 Stable Offical

**OS/device including version:**
Windows 7 Ultimate SP 1

**Issue description:**
Cmd shows error about OpenGL Not compatible  When switching to OpenGL 2.0 the cmd does not appear

**Steps to reproduce:**

Open only the program

**Minimal reproduction project:**
[Player.zip](https://github.com/godotengine/godot/files/5806314/Player.zip)

Img:
![screenshot](https://user-images.githubusercontent.com/77373035/104405196-20ffd280-553b-11eb-907e-1714018ab849.png) 
![screenshot2](https://user-images.githubusercontent.com/77373035/104405209-278e4a00-553b-11eb-998f-cdc81f713652.png)

ATI Radeon HD 4200 Support OpenGL 3.3  Direct 10_1  OpenCL  1.0

**Comment by clayjohn** [comment]
I don't think the ATI Radeon HD 4200 fully supports opengl 3.3 on windows 7. I think you need better drivers to actually run opengl 3.3. 

The reason we have the GLES2 backend is so that such old hardware can still be supported by Godot.

**Comment by XVUser** [comment]
There is no way to force it? with programs that analyze the hardware say it has opengl 3.3

**Comment by Calinou** [comment]
> There is no way to force it? with programs that analyze the hardware say it has opengl 3.3

It might claim to have OpenGL 3.3 support, but that doesn't mean it's reliable enough to be used in production.

The same thing happens with GeForce 8/9 GPUs.
