### ISSUE TITLE
Errors "Attempt to connect nonexistent signal 'about_to_popup'"  when clicking at nodes

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#45177]
**Godot version:**
3.2.4.beta.custom_build. f93c2ddc9

Regression probably from  https://github.com/godotengine/godot/pull/45042
CC @KoBeWi 

**Issue description:**
Godot output window is spammed by errors - `ERROR: connect: In Object of type 'PopupPanel': Attempt to connect nonexistent signal 'about_to_popup' to method 'EditorPropertyColor._picker_opening'.
   At: core/object.cpp:1500.
`

![Zrzut ekranu z 2021-01-14 08-39-06](https://user-images.githubusercontent.com/41945903/104558974-fbaabb80-5643-11eb-9ab5-13c39dea0207.png)

**Steps to reproduce:**
1. Open Editor with minimal project
2. Click at different nodes in scene tab

**Minimal reproduction project:**
[wrp.zip](https://github.com/godotengine/godot/files/5812974/wrp.zip)

**Comment by akien-mga** [comment]
I might have missed something in the cherry-pick when converting to method binds: 3873a1331b38949d8e6e454c14eb88ecfe92db0d.

**Comment by akien-mga** [comment]
There's no `about_to_popup` signal in `3.2`.

**Comment by akien-mga** [comment]
Fixed by #45185.
