### ISSUE TITLE
Can't build for iOS arm64 (builtin OpenSSL error)

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#4517]
Trying to build for iPhone arm64 (on a Linux environment) gives error in the built-in OpenSSL. It does compile if I revert the last update (#4329). Somehow it compiles fine for iPhone armv7 architecture.

```
scons -j 1 p=iphone tools=no target=release_debug IPHONEPATH=/home/george/iostoolchain IPHONESDK=/home/george/iostoolchain/iPhoneOS9.2.sdk/ ios_triple=arm-apple-darwin11- bits=64
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/home/george/iostoolchain/usr/bin/arm-apple-darwin11-clang -o drivers/builtin_openssl2/ssl/s3_cbc.iphone.opt.debug.64.o -c -DOPUS_ARM64_OPT -fno-objc-arc -arch arm64 -fmessage-length=0 -fno-strict-aliasing -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -Wno-trigraphs -fpascal-strings -Wmissing-prototypes -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -fvisibility=hidden -Wno-sign-conversion -MMD -MT dependencies -miphoneos-version-min=5.1.1 -isysroot /home/george/iostoolchain/iPhoneOS9.2.sdk/ -Os -DNS_BLOCK_ASSERTIONS=1 -Wall -DDEBUG_ENABLED -DNEED_LONG_INT -DLIBYUV_DISABLE_NEON -fblocks -DGAME_CENTER_ENABLED -DSTOREKIT_ENABLED -DICLOUD_ENABLED -DDEBUG_MEMORY_ENABLED -DIPHONE_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DMPC_FIXED_POINT -fexceptions -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DPNG_ARM_NEON_OPT=0 -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/iphone -Iplatform/iphone/include -I/home/george/iostoolchain/iPhoneOS9.2.sdk/usr/include -I/home/george/iostoolchain/iPhoneOS9.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers -I/home/george/iostoolchain/iPhoneOS9.2.sdk/System/Library/Frameworks/AudioUnit.framework/Headers -Idrivers/builtin_openssl2 -Idrivers/builtin_zlib/zlib -Idrivers/vorbis -Idrivers/builtin_openssl2/crypto -Idrivers/builtin_openssl2/openssl -Idrivers/builtin_openssl2/crypto/evp -Idrivers/builtin_openssl2/crypto/asn1 -Idrivers/builtin_openssl2/crypto/modes drivers/builtin_openssl2/ssl/s3_cbc.c
drivers/builtin_openssl2/ssl/s3_cbc.c:459:13: error: implicit declaration of function 'private_MD5_Init' is invalid in C99 [-Werror,-Wimplicit-function-declaration,2]
         if (MD5_Init((MD5_CTX *)md_state.c) <= 0)
             ^
drivers/builtin_openssl2/openssl/md5.h:115:18: note: expanded from macro 'MD5_Init'
 #define MD5_Init private_MD5_Init
                  ^
1 error generated.
scons: *** [drivers/builtin_openssl2/ssl/s3_cbc.iphone.opt.debug.64.o] Error 1
scons: building terminated because of errors.
```

Maybe with the next update will fix this, but will keep open as a reminder.

**Comment by akien-mga** [comment]
It seems blocking only when building with ``-Werror`` no? I see the same issue in Travis-CI logs but as a warning. IMO we shouldn't try to build external libraries with ``-Werror``, we can't really fix their issues ourselves :)

**Comment by vnen** [comment]
Yes, you're right. However, it seems `-Werror` is default, as it's not in command line (also, it is not defined in any other platform, only for iOS arm64). Tried to add `-Wno-error` but it seems to not work in general, only if I specify a warning to no convert to error, such as `-Wno-error=implicit-function-declaration`.

**Comment by akien-mga** [comment]
I can't find any match for ``-Werror`` in the source code, that's weird. How did you see that it was defined only for iOS arm64? I don't see in the ``detect.py`` what would behave differently for armv7 and arm64 in this regard.

**Comment by vnen** [comment]
Well, it's a guess, as it is not defined for any platform, but for some reason is applied by default to iOS arm64, while not to armv7.

Also, if I revert the last OpenSSL update, it gives no error even though there's no relevant change in the erroring file. So I'm clueless.

**Comment by vnen** [comment]
I'm still clueless about what's going on here. Since the build still gives warnings, then `-Werror` is not defined, at least no for all warnings. From what I can infer, `-Werror=implicit-function-declaration` is enable by default, but only for arm64 and not for armv7 (since the latter only gives the warning while the former makes it an error).

I guess if we add `-Wno-error=implicit-function-declaration` to `CFLAGS` in `platform/iphone/detect.py` we can avoid this specific problem and hope there's no other hidden flag.

My Google-fu didn't help on this, I could not find any mention for default implicit flags like that.

**Comment by akien-mga** [comment]
I can confirm that it doesn't build on Travis either: https://travis-ci.org/GodotBuilder/godot-builds/jobs/128051707

**Comment by akien-mga** [comment]
Javascript seems to fail too with the same error, most likely because it's also built using clang: https://travis-ci.org/GodotBuilder/godot-builds/jobs/128253926

I guess the proper solution would be to add ``-Wno-error=implicit-function-declaration`` to the ``CFLAGS``,  not platform-dependent but directly in the ``SCsub`` of the builtin openssl driver. If we can somewhat make it with a local environment to avoid defining it for the rest of Godot's source, that would be best :)

**Comment by vnen** [comment]
>  If we can somewhat make it with a local environment to avoid defining it for the rest of Godot's source

This may be possible with `env.Clone` but I couldn't do it when I tried with Opus. I might try a little harder and see if it works.

**Comment by punto-** [comment]
is the OPENSSL_ENABLED macro used anywhere outside the stuff that's in the
driver? that'd be a great candidate to compile with a cloned environment
since it's pretty common to recompile without ssl, and it triggers a
recompile of the whole engine

**Comment by vnen** [comment]
It seems that all the drivers definitions are made in the main `SConstruct` file. The only file outside the actual driver that uses that is `drivers/register_drivers_types.cpp` to select what to register.

I think this calls for a refactor, though we can start with OpenSSL.

**Comment by punto-** [comment]
Ok I made a commit that clones the env in drivers/SCsub, then exports it,
so openssl and builtin_openssl2 can use it, what is the option that has to
be added? The environment should be able to know if the compiler is clang
(and if it's 64 bits)

**Comment by vnen** [comment]
@punto- the option to add is `-Wno-error=implicit-function-declaration` to `CFLAGS`.
