### ISSUE TITLE
GDScript assigning static typed Vector2's components with ints assigns 0 or NAN

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#45172]
**Godot version:**

4.0.dev 8e514bbf6a

**OS/device including version:**

Windows 10

**Issue description:**

Statically typed Vector2 member assignments behave unexpectedly with non-float assignees. See examples below.

**Steps to reproduce:**
```gdscript
# this behaves properly
func _ready():
    var vec = Vector2()

    vec.x = 50
    print(vec) # prints (50, 0)
    vec.x = -50
    print(vec) # prints (-50, 0)
    vec.x = 50.0
    print(vec) # prints (50, 0)
```

```gdscript
# this doesn't work as expected
func _ready():
    var vec := Vector2() 

    vec.x = 50
    print(vec) # prints (0, 0)
    vec.x = -50
    print(vec) # prints (nan, 0)
    vec.x = 50.0
    print(vec) # prints (50, 0)
```
The only difference between scripts is that `vec` is statically typed in the second one.

**Minimal reproduction project:**

[vectorNANrepro.zip](https://github.com/godotengine/godot/files/5812027/vectorNANrepro.zip)

**Comment by Shatur95** [comment]
Also want to add that `+=` and similar works:

```gdscript
    vec.x += 50
```
