### ISSUE TITLE
Anisotropic filter doesn't work

### ISSUE THREAD

**Issue by dakennedyd** [godotengine/godot#45178]
Godot version:3.2.stable

OS/device including version:Ubuntu 20.04
GPU:Nvidia Geforce GTX 750Ti
Driver:nvidia-driver-460
GLES3

Issue description:Anisotropic texture filtering doesn't seem to work no matter the level used

Steps to reproduce: 
Go to project settings, rendering quality, filters and change the settings.
Changing the filter level doesn't have any effect on the textures
![Screenshot from 2021-01-14 06-09-56](https://user-images.githubusercontent.com/44821219/104570082-3dca0200-5630-11eb-9c20-6bf395e64d00.png)
![Screenshot from 2021-01-14 06-08-03](https://user-images.githubusercontent.com/44821219/104570189-5fc38480-5630-11eb-9083-8e17ef7fe2fe.png)

Minimal reproduction project:
It seems to happen on all projects

**Comment by dakennedyd** [comment]
I figured out that apparently you have to enable anisotropy when importing the textures otherwise it doesn't work. Closing the issue

**Comment by Calinou** [comment]
This will be resolved by https://github.com/godotengine/godot/pull/37847 if it's merged.
