### ISSUE TITLE
set_as_toplevel behavior of kinematic body 2D in Godot 3.2.4

### ISSUE THREAD

**Issue by Reapetitive** [godotengine/godot#45188]
Godot version:
3.2.4 betas

PC, API:
Windows 10 64bit, ryzen 1700x OC, nvidia geforce rtx 3070, gles3

Issue description:
Two KinematicBody2Ds, one is a child of another, child follows parent with move and slide, parent moves around with move and collide.

Set child as top level, so it can move ignoring parent.

3.2.3 behavior - normal. For example - head of a worm moves first, its tail drags after it.

3.2.4 behavior - nodes fly through space and time, glitch through worlds and disappear.

**Comment by Calinou** [comment]
@Reapetitive Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Reapetitive** [comment]
Ok, this one goes on me. I guess you guys fixed some bugs, which were allowing me to do wrong stuff. :) I figured it out for me.
