### ISSUE TITLE
Dynamic fonts: Should force redraw when there size is modified

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4519]
Awesome work on the dynamic font support! It seems to work fairly well already.

One small glitch. If I have:
![spectacle yj4492](https://cloud.githubusercontent.com/assets/4701338/14947918/cb6f23ce-103a-11e6-953b-6f71520bd2c4.png)

And change the font size, I get:
![spectacle hc4492](https://cloud.githubusercontent.com/assets/4701338/14947930/e4c23032-103a-11e6-9826-d089726b54a2.png)

I need to move the label around to get it refreshed:
![spectacle vr4492](https://cloud.githubusercontent.com/assets/4701338/14947936/fadc80b6-103a-11e6-9482-57a056c9aa68.png)

**Comment by reduz** [comment]
this was implemented, closing
