### ISSUE TITLE
Remote scene tree: Dock "Inspector" update problem

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#45205]
**Godot version:**

3.2.4 beta 5 mono

**OS/device including version:**

win10 64

**Issue description:**

The inspector section does not update when "Remote" mode is automatically activated when executing a scene.
For the "Inspector" section to be updated, the user must select another node (this will minimize the execution window) and then select the initially selected node, this updates the "Inspector" dock, now the user must maximize the execution window again ... a good waste of time.
The "Inspector" dock could automatically update to show the selected node when the scene is run.
In this GIF you can see everything.

![gif](https://user-images.githubusercontent.com/19652075/104710885-e8b9e900-5720-11eb-94fc-2f281828e97c.gif)

**Steps to reproduce:**
Enable "Remote" mode execution by default when executing a scene.
Select a node before running the scene.
Run the scene.
The "Inspector" dock appears empty or shows a node that is out of remote mode although you can see that a node is selected.

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Not limited to Windows nor beta. I am on 3.2.3 on Linux Manjaro and seeing the same behavior.

**Comment by Torguen** [comment]
Could the execution window be implemented in the editor?
This way it will never be minimized because it belongs to the publisher itself.

**Comment by Zireael07** [comment]
@Torguen: Been suggested already, requires an extensive rework of editor.

**Comment by Torguen** [comment]
> @Torguen: Been suggested already, requires an extensive rework of editor.

Can you tell me the thread in which the suggestion was made?

**Comment by Zireael07** [comment]
https://github.com/godotengine/godot-proposals/issues/1864 (thread title is a bit different, but if you read through it, it'll point you to a PR which attempted the rework, and from there, you can probably find the original proposal from years back)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1864, as feature proposals are now tracked on the Godot proposals repository.
