### ISSUE TITLE
Crash upon doing ctrl+z, that is after unchecking the set DynamicFont of a label.

### ISSUE THREAD

**Issue by mownier** [godotengine/godot#4520]
**Operating system or device:**
OS: Ubuntu 15.10, 64-bit
branch: master
HEAD: commit 5bb7cef

**Issue description** (what happened, and what was expected):
I tried DynamicFont on a label. I decided to edit it. Under the Font variable, I chose New DynamicFontData. Then, I clicked the label again in the Scene tab. I unchecked the Font variable under Custom Fonts category. I did `ctrl+z` 4 times and boom, the program quit. See gdb info below.

```bash
ERROR: _get_dynamic_font_at_size: Condition ' !valid ' is true. returned: Ref<DynamicFontAtSize>()
   At: scene/resources/dynamic_font.cpp:62.
```
I got this error also but I can't reproduce. I think this is just related to the error above.
```bash
ERROR: add_font_override: Condition ' p_font.is_null() ' is true.
   At: scene/gui/control.cpp:1476.
```

**Steps to reproduce:**
1. Create a scene.
2. Add a node `Label` as root and save it.
3. Click the label and choose DynamicFont.
4. Edit it and choose DynamicFontData on the `Font` variable.
5. Click the label again in the Scene tab.
6. Uncheck the `Font` variable under the `Custom Fonts` category.
7. `ctrl+z` 4 times. _(expectation: the program quits)_

**Comment by reduz** [comment]
This is fixed already, closing
