### ISSUE TITLE
Postprocessing/tonemapping does not work with Viewport + Transparent Bg

### ISSUE THREAD

**Issue by vitorbalbio** [godotengine/godot#45208]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
Stable 3.2.3 Mono

**OS/device including version:**
Windows 10

**Issue description:**
World's post process do not work with Viewports when Transparent BG is enabled. That included Tone mapping and color correction not only FX

![Godot_v3 2 3-stable_mono_win64_gcO4YSVZ5R](https://user-images.githubusercontent.com/6172013/104726884-2d3e8800-5713-11eb-8f81-ac8faf294829.png)
![Godot_v3 2 3-stable_mono_win64_n0NnmC0Wqx](https://user-images.githubusercontent.com/6172013/104726887-2e6fb500-5713-11eb-89ba-d731ffe23c6b.png)

**Steps to reproduce:**
Bellow

**Minimal reproduction project:**
Run the project. Check option with and Without Transparent Bg
[PostBug.zip](https://github.com/godotengine/godot/files/5820414/PostBug.zip)

**Comment by Calinou** [comment]
I think this is a design decision. I doubt post-processing effects can be made to work with a transparent viewport.

**Comment by vitorbalbio** [comment]
> I think this is a design decision. I doubt post-processing effects can be made to work with a transparent viewport.

I think it's more like a feature lost in the way when it was implemented since i can get a Viewport Texture with alpha channel and apply a custom shader to it with Color Correction per example. Beside that it have too much limitations to be a solution since i can't do a simple Glow because i can't access the mipmap levels of the Viewport Texture (Even when those are correctly created) but this is another problem https://github.com/godotengine/godot/issues/23417

**Comment by farfalk** [comment]
This feels a lot like a bug, at least from an usability standpoint. I'm using different viewports with different cameras and the same world, mixed together using overlapped TextureRects, and I'm using this structure to replicate this effect: https://youtu.be/LAopDQDCwak

In practice, I render everything but some objects in a viewport via cull masks, and those objects in the other one with transparent_bg enabled. I'd love to put some effects in both of them, but I just.. can't, and it feels wrong.

I'm currently trying some chromakey to achieve transparency without transparent_bg, but it's cumbersome

**Comment by djmaesen** [comment]
same problem in 3.4.2 in my fps project

**Comment by Calinou** [comment]
> same problem in 3.4.2 in my fps project. enabling transparent background disables post processing and fxaa and msaa

Could you test https://github.com/godotengine/godot/pull/54585 by building its branch from source (https://github.com/Kinwailo/godot/tree/fix_viewport_transparent_bg)? See compiling instructions here: https://docs.godotengine.org/en/stable/development/compiling/index.html

**Comment by djmaesen** [comment]
> > same problem in 3.4.2 in my fps project. enabling transparent background disables post processing and fxaa and msaa
> 
> Could you test #54585 by building its branch from source (https://github.com/Kinwailo/godot/tree/fix_viewport_transparent_bg)? See compiling instructions here: https://docs.godotengine.org/en/stable/development/compiling/index.html

sorry man , im not a coder i have no idea to implement that in my project

**Comment by djmaesen** [comment]
godot4 alpha fixes the environment effects on second camera
however, transparent background doesnt work anymore when using viewports

**Comment by Calinou** [comment]
> godot4 alpha fixes the environment effects on second camera however, transparent background doesnt work anymore when using viewports

This is already being tracked in https://github.com/godotengine/godot/issues/40651.

**Comment by akien-mga** [comment]
Fixed by #54585.
