### ISSUE TITLE
Cannot properly instance multiple child scenes at once

### ISSUE THREAD

**Issue by fstiewitz** [godotengine/godot#45204]
**Godot version:**
- `master` at 8a3310708
- `3.2` at d2989495134
- `3.2.3.stable` unaffected

**Issue description:**

`Instance child scenes` in context menu and selecting multiple scenes creates unintended tree.

![instance_3 2 4 beta mkv](https://user-images.githubusercontent.com/7817714/104707141-ef8e2f00-5713-11eb-878f-65b7f703520e.gif)

What should happen:

![instance_3 2 3 stable mkv](https://user-images.githubusercontent.com/7817714/104707198-03399580-5714-11eb-93a8-1fc9ddb129d3.gif)

**Comment by Riteo** [comment]
Currently bisecting this, will update you soon.

**Comment by Riteo** [comment]
Ok, so it seems that the first bad commit is c588ba0b6af9f82a6db95e5c06c155fcd53121b3 and it's... one line of code.

**Comment by Zireael07** [comment]
cc @KoBeWi
