### ISSUE TITLE
Popups may appear with huge offset when right-clicking unfocused editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#45200]
**Godot version:**

011d201

**OS/device including version:**

Windows 10

**Issue description:**

![jahrT7ZhRo](https://user-images.githubusercontent.com/2223172/104659739-7b2c9f00-56c5-11eb-933d-0de964c7d869.gif)
This happens when right-clicking while editor is unfocused. Right-clicks on focused editor makes the popup appear at cursor correctly.

**Comment by albinaask** [comment]
I have found the same issue, to add to that the popup may appear partially off screen.

**Comment by KoBeWi** [comment]
Was fixed (likely) along with #45740
