### ISSUE TITLE
Dynamic fonts: can't delete TTF file while editor is opened

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4522]
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
can't delete TTF file while editor is opened.
OS says file is still in use, so can't delete it.

**Steps to reproduce:**
1. Add ``Label``
2. Make Dynamic font and load TTF file
3. Delete ``Label``
4. try to delete TTF file on file system

**Comment by reduz** [comment]
does this still hapen?

**Comment by volzhs** [comment]
@reduz yes, still happen.

**Comment by reduz** [comment]
Oh, this is not a bug. This is how Windows works, let me explain:

1) TTF/OTF support for Dynamic Fonts is provided by Freetype
2) While you are using the font, freetype is loaded and working, it generates characters into textures on demand. For this, it accesses the .ttf file and keeps it open.
3) Even if you remove it from the label, it's likely still loaded in the undo/redo history
4) Windows (unlike linux and osx) does not allow removing or modifying a file that is in use

So, this is not a "bug", it's a Windows feature and it can't be changed
