### ISSUE TITLE
After deleting folder in project, Godot will try to import into deleted folder path if dragging a file into Godot

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#45229]
**Godot version:**
3.2.3.Stable

**OS/device including version:**
Windows 10 Pro v2004 OS Build 19041.746

**Issue description:**
After deleting folder in project, Godot will try to import into deleted folder path if dragging a file into Godot
![8uPRqpwQkw](https://user-images.githubusercontent.com/4955051/104808868-e8812280-57e0-11eb-90c9-a86c1e994f1f.gif)

**Steps to reproduce:**
1. Create a folder in Godot.
2. Delete the folder.
3. Drag file to be imported into Godot.

**Minimal reproduction project:**
NA

**Comment by YeldhamDev** [comment]
The bug is also present on master. It seems that the selected path is still the deleted folder even after the fact, should be a simple fix.

**Comment by Anshul7sp1** [comment]
So it should pass the focus back to project root once an active (selected) folder is deleted right?
