### ISSUE TITLE
Sprite disappears when closing inventory

### ISSUE THREAD

**Issue by cheomanigua** [godotengine/godot#45238]
**Godot version:**

3.2.3 stable official

**OS/device including version:**

Ubuntu 18.04
kernel: 4.15.0-128-generic x86_64
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
GLES3

**Issue description:**

When picking an item from the Loot slot of the inventory, place it again in any Loot slot and closing the inventory, the item sprite disappears from the ground.
It is expected for the sprite to be shown in the ground when closing the inventory.

**Steps to reproduce:**
1. Move player nearby an item (get_overlapping_bodies) 
2. Open inventory
3. Inventory **Loot** section is populated automatically with nearby items 
3. Click on item to take from **Loot** slot 
4. Click on an empty **Loot** slot to drop the item
5. Close inventory
6. Item is dropped in the ground, but item sprite disappears (debugging HUD shows that item is still present as overlapped body)
7. Opening the inventory again will make the item visible in the ground
8. Closing the inventory again will make the item invisible in the ground
9. Debugging printing will show that item visibility is True despite item not been shown.

**Minimal reproduction project:**

[inventory-issue.zip](https://github.com/godotengine/godot/files/5824860/inventory-issue.zip)

**Comment by KoBeWi** [comment]
Your items are children of inventory, so they will disappear with the inventory. Make them child of map if you want them to stay.

btw the whole issue doesn't sound like Godot bug. If you have problems with your game, try [other community channels](https://godotengine.org/community) first and only fill a bug report if you are certain it's an engine bug.
