### ISSUE TITLE
RESULT_CANT_CONNECT when using HTTPRequest on localhost

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#45249]
**Godot version:**
`Godot_v3.2.2-stable_x11.64`

**OS/device including version:**
Linux 64bits (Pop!_OS 20.10)

**Issue description:**

It seem `localhost` pseudo-domain is not correctly resolved by `HTTPRequest` node, ending up in a `RESULT_CANT_CONNECT` error. Using `127.0.0.1` instead works fine.

**Steps to reproduce:**

Considering a http server is running on localhost:8000 (typically using `python3 -m http.server`)

```gdscript
static func download(url: String):
	var root = Engine.get_main_loop().root
	var http_request = HTTPRequest.new()
	root.add_child(http_request)

	var error = http_request.request(url)
	if error != OK:
		return "Cannot initiate HTTP request %s (error %s)" % [
			url,
			error
		]

	var vars = yield(http_request, "request_completed")
	var http_result = vars[0]
	var status_code = vars[1]
	var body = vars[3]

	if http_result == HTTPRequest.RESULT_CANT_CONNECT:
		return "Cannot reach %s (error RESULT_CANT_CONNECT)" % url
	elif http_result == HTTPRequest.RESULT_CANT_RESOLVE:
		return "Cannot reach %s (error RESULT_CANT_RESOLVE)" % url
	elif http_result != OK:
		return "Bad response from %s (error %s)" % [url, http_result]
	elif status_code != 200:
		return "Bad response from %s (status code: %s)\n%s" % [
			url,
			error,
			body.get_string_from_utf8()
		]
	return "Request succeeded !"

static func main_test():
	# var res = yield(download("http://127.0.0.1:8000"), "completed")  # Works as expected
	var res = yield(download("http://localhost:8000"), "completed")  # Ends up with RESULT_CANT_RESOLVE error :-(
	print("Result: ", res)
```

**Comment by Faless** [comment]
@touilleMan your OS is configured to prefer an IPv6 address when resolving `localhost`, so Godot connects to `[::1]:PORT`, instead of `127.0.0.1:PORT`. By default though, python only listen to `0.0.0.0` (IPv4).
Run `python3 -m http.server --bind ::` to bind to the IPv6 address.

**Comment by Faless** [comment]
The solution, would be [Happy eyeballs](https://tools.ietf.org/html/rfc8305), see https://github.com/godotengine/godot/issues/36418#issuecomment-589963787

**Comment by touilleMan** [comment]
@Faless thanks for the quick answer ;-)
