### ISSUE TITLE
Reflection probes don't blend with BVH rendering

### ISSUE THREAD

**Issue by waveeeee** [godotengine/godot#45247]
**Godot version:**
3.2.4 beta 6

**OS/device including version:**
Intel UHD 620 graphics, GLES3

**Issue description:**
When an object moves from one reflection probe area to another, instead of blending between reflections the probes stop affecting the object all together and it will instead show the skybox reflection. It stays that way even if the player object moves back into the area of the reflection probe it originally spawned in. This only happens in the BVH renderer, setting it back to octree fixes this bug.

**Steps to reproduce:**
Move an object with a reflective material from one reflection probes' confines to another with the BVH renderer enabled.

**Minimal reproduction project:**
[3D Platformer Demo.zip](https://github.com/godotengine/godot/files/5825652/3D.Platformer.Demo.zip)

**Comment by lawnjelly** [comment]
Seems like a bug in the pairing, there may be a situation I'm not dealing with properly, hopefully not too bad to fix. I'll take a look. :+1:

**Comment by waveeeee** [comment]
Oh sorry! I was using that demo to test some things but that makes sense. Either way #45251 has fixed this and reflections work as they should.
