### ISSUE TITLE
Incorrect normal mapping with imported glTF scenes

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#45240]
**Godot version:**
[3099f6f](https://github.com/godotengine/godot/commit/3099f6fae4da58f6c55d7bf4a060e21b5968a0bf)

**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan

**Issue description:**
Normal maps are weirdly warped, which leads to incorrect shading.
[Cutout of the model in editor.](https://i.imgur.com/eCJEYTz.png) vs [Full model in GLTF Viewer](https://i.imgur.com/mM7or87.png)

**Steps to reproduce:**
Open the project > Open `untitled.glb` > Select `Perspective > Display Advanced... > Normal Buffer`

**Minimal reproduction project:**
[Here](https://drive.google.com/file/d/1jnXUw-kp4Ya3ey5r7cL5H1qqLol7SD9H/view?usp=sharing)

**Comment by fire** [comment]
There is one missing feature of the Godot Master autolod. So I think this is a autolod bug and not rendering in Vulkan. Please check if it's related by disabling lod.

**Comment by Xartorx** [comment]
> Please check if it's related by disabling lod.

If LOD is in "Import" tab, then i tried it (re-imported and relaunched editor) and [it's still buggy](https://i.imgur.com/j0FNS6W.png).

**Comment by Xartorx** [comment]
Another example, now with [model from Sketchfab](https://sketchfab.com/3d-models/modular-p90-tactical-080897fc0366455884b1a916684313fe).
[Normal mapping as viewed on Sketchfab](https://i.imgur.com/qRolA0X.png) vs [bugged normals in editor](https://i.imgur.com/AigJPz0.png).
Found out that when scene with model was open, editor were spamming error in console:
`ERROR: Condition "!uniform_set" is true.
   at: draw_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:6187)`
After closing scene tab this error occured:
`ERROR: Condition "!material" is true.
   at: material_set_shader (servers\rendering\renderer_rd\renderer_storage_rd.cpp:1545)`
And image of scene was still present, although no tabs were open. [Image.](https://i.imgur.com/aJ7DLhn.png)

Also, this looks like a material shader problem for me - if i disable normal maps in material it looks ok.
[Bugged](https://i.imgur.com/54xMAMt.png) vs [Normal](https://i.imgur.com/dSeBMg7.png)

**Comment by decepticlown** [comment]
+1 @Xartorx I have same problem with incorrect shading and it goes away when I use Triplanar in Shader.

**Comment by Calinou** [comment]
@Xartorx @decepticlown Can you reproduce this when using a primitive mesh in a MeshInstance (such as a BoxMesh)?

**Comment by decepticlown** [comment]
@Calinou I can confirm that it only happens with gltf import. I imported same mesh through obj and it works fine without any issues. Could it be gltf importer problem?

**Comment by Xartorx** [comment]
@Calinou looks like it's an importing issue - using model straight from Sketchfab (and looks like model was made in 3DS Max) produces errors in normal mapping, but importing model into Blender and exporting it as OBJ fixes it:
<details>
<summary>
Top - OBJ from blender, bottom - FBX from Sketchfab
</summary>

![Screenshot 2021-02-11 132956](https://user-images.githubusercontent.com/2698825/107625767-e12d2780-6c6d-11eb-91a1-07cf127f49b8.png)

</details> 

<details> 

<summary>
Exporting as GLTF from Blender produces different problem - part of normal map just doesn't mapped:
</summary>

![Screenshot 2021-02-11 134345](https://user-images.githubusercontent.com/2698825/107626671-3453aa00-6c6f-11eb-9474-7d966d02c895.png)

</details> 

<details>
<summary>
And in normal buffer view this part just straight up missing:
</summary>

![Screenshot 2021-02-11 134332](https://user-images.githubusercontent.com/2698825/107626789-5b11e080-6c6f-11eb-9c34-ca0f7446c7c2.png)

</details>

**Comment by decepticlown** [comment]
Another problem.
Obj model from blender but flat shaded:
<a href="https://imgur.com/HRr7iOP"><img src="https://i.imgur.com/HRr7iOP.png?1" title="source: imgur.com" /></a>

Obj Model but smooth shaded:
<a href="https://imgur.com/sgF8amS"><img src="https://i.imgur.com/sgF8amS.png?1" title="source: imgur.com" /></a>

**Comment by Calinou** [comment]
cc @fire

**Comment by decepticlown** [comment]
Maybe I should mention that I'm using Godot compiled from master branch?

**Comment by Calinou** [comment]
> Can I comment in another version if master branch has same problem?

I'd suggest opening a separate issue if you're encountering this issue in `master`. Note that `master` will currently display some materials as white after you set a texture in them; this can be solved by saving the scene then using **Scene > Reload Saved Scene**.

**Comment by Xartorx** [comment]
Looks like issue is resolved with latest PR ([#49522](https://github.com/godotengine/godot/pull/49522)).

![image](https://user-images.githubusercontent.com/2698825/121757155-48c48800-cb25-11eb-98cd-4bdfaa8baa99.png)

**Comment by clayjohn** [comment]
Closed by #49522
