### ISSUE TITLE
The clear button of LineEdit can not delete the text on iOS devices.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#45245]
**Godot version:**
3.2.x

**OS/device including version:**

**Issue description:**

after clear the text of LineEdit by click the clear button, the text disappeared, however, when continue to input characters, the original text still displayed and the new input characters is append to it.

**Steps to reproduce:**
1. add a LineEdit 
2. enable clear button in the property of LineEdit
3. input some text
4. click clear button to clear the text
5. continue to input
6. the cleared text plus the new text displayed in the LineEdit.

The above behavior only happened on iOS devices.

And the following behavior happened on iOS and Android devices.
After clicking the clear button, the suggestion words on the soft keyboard  is not cleared, which will be cleared on the UITextField.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
> Godot version:
3.2.x

Please be more specific, there are bug fixes in every single Godot version.

**Comment by alexzheng** [comment]
all including 3.2.4 beta 6

**Comment by naithar** [comment]
Maybe someone from Android team can help? I don't entirely understand how android is handling keyboard input and LineEdit doesn't seem to be sending anything to platform code so we can actually catch it and clear the backing text view.

**Comment by naithar** [comment]
@alexzheng can you try out this branch and check if it works for you? https://github.com/naithar/godot/commit/e3677a312bcb3bb47fdba6164e69c97bc8557754

**Comment by alexzheng** [comment]
@naithar  it works, thanks.
