### ISSUE TITLE
Cannot enable visibility if the lights is off by default (visibility=off)

### ISSUE THREAD

**Issue by takhimi** [godotengine/godot#45246]
**Godot version:**
3.2.4 Beta 6 Official

**OS/device including version:**
GTX970, Ryzen 3700x, Windows 10 64bit

**Issue description:**
I cannot enable visibility for lights if they are disabled by default. It is running as expected in ver 3.2.3.
If it is enabled by default when loaded, I can turn the light on or off. Happens for Spotlight and Omnilight but not directional light.

**Steps to reproduce:**
1. Create new project, add camera
2. Add lights Omni or spot lights
3. Disable the lights visibility in the editor (visibility=off)
4. Create script and add a toggle function to test when a button is clicked, example 	
5. if Input.is_action_just_pressed("ui_accept"):  $SpotLight.visible=!$SpotLight.visible
6. The lights wont turn on if it is off by default(will always off). If I turn it on in the editor and run it, the light will toggle on and off
7. This bug does not occur in official stable version 3.2.3 

**Minimal reproduction project:**
[Godot Light Bug.zip](https://github.com/godotengine/godot/files/5825491/Godot.Light.Bug.zip)

**Comment by lawnjelly** [comment]
Can confirm this is a BVH bug, switching off BVH in `project_settings->rendering->quality->spatial_partitioning->use_bvh` cures it.

Is possibly the same bug as #45247, but can't confirm yet.

**Comment by lawnjelly** [comment]
Yes .. it was when using the `set_pairable` command, I wasn't updating the changed items and doing a collision check, that was only occurring during regular commands (such as a move). If the item had the pairable changed and was not moved it did not register.

I'll make a PR once I've double checked it. Also want to see if it is the same problem as the other issue, could well be. Annoying to not have fixed before the build, but that's what the beta builds are for I guess!

**Comment by akien-mga** [comment]
Fixed by #45251.
