### ISSUE TITLE
Mono version complains about missing .NET 4.7 targeting packs

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45257]
**Godot version:**
Godot 3.2.4 beta 6 Mono

**OS/device including version:**
Ubuntu 20.10

**Issue description:**
When the user installs mono (all features), he also needs to install .Net 5.0 (or else he gets errors when compiling)

**Workaround**
change **targetframework** to `net5.0` 
![image](https://user-images.githubusercontent.com/58845030/104850647-0331c500-58cf-11eb-97d7-efbc47484340.png)

**Steps to reproduce:**
* Get a Fresh Ubuntu 20.10
* Install godot version mentioned above
* install mono with all features
* Create a new godot project
* Create a new script `.cs`
* Press F6 an run

At this moment your project will  run without any errors, but if you look at `MSBuild` tab notice he will complain about missing 4.7

Workaround:
* Install .Net 5.0
* in the ".csproj" file change `targetFramework` to `net5.0`
* Compile again and now project works well    

**Minimal reproduction project:**
A Empty project already satisfies

**Comment by aaronfranke** [comment]
Changed the title to reflect the actual bug. .NET 5 is not supported right now. You can, however, use the build tools from .NET Core or .NET 5 (as of 3.2.4, see also #43717) to build Mono. Targeting `net472` is the default and recommended option right now.

**Comment by nonunknown** [comment]
Well, we have a problem then, because installing mono only (without .NET 5.0) will not meet godot requirements, because it will complain about the 4.7 and how to install 4.7 on linux?

**Comment by aaronfranke** [comment]
@nonunknown I can't reproduce the issue. An empty project builds and runs just fine without any errors or warnings anywhere.

![Screenshot from 2021-01-17 13-40-19](https://user-images.githubusercontent.com/1646875/104852556-b5668e00-58c9-11eb-9322-8ee534ab5afa.png)

I'm on Ubuntu 20.04 with Mono 6.12.0.107 and .NET Core 3.1.405. It works with either build tool selected:

![Screenshot from 2021-01-17 13-43-19](https://user-images.githubusercontent.com/1646875/104852662-3c1b6b00-58ca-11eb-91b4-6b3648e705a3.png)

```csproj
<Project Sdk="Godot.NET.Sdk/3.2.4">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Empty</RootNamespace>
  </PropertyGroup>
</Project>
```

[45257.zip](https://github.com/godotengine/godot/files/5826594/45257.zip)

Please provide more information (Mono and .NET versions), please test if the above project and if the [official demo projects](https://github.com/godotengine/godot-demo-projects/tree/master/mono) work on your system, and please [make sure you have everything in this article set up](https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_basics.html).

**Comment by nonunknown** [comment]
I think this topic can be closed, for future users:

* Uninstall mono and .net5.0 (in case you have)
* install .netcore3.1 with the following command:
```
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list 
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install aspnetcore-runtime-3.1.4
sudo apt-get install dotnet-sdk-3.1
```

* Restart your pc, and try a new godot mono project

**Comment by Moon422** [comment]
> I'm on Ubuntu 20.04 with Mono 6.12.0.107 and .NET Core 3.1.405. It works with either build tool selected:

That means I don't need to have Mono installed on my pc. I am using Linux mint. I am facing an issue with VSCode's C# extension when I use Mono build, as the recent C# extension need a higher msbuild version than what Mono's msbuild offers. Therefore, I switched to `dotnet cli` (I have dotnet 5 installed) and building of games without a problem and the also the C# extension for VSCode do not complain and the features are working. So, I want to ask if I stick dotnet cli for my future projects, am I going to face any issues?

**Comment by aaronfranke** [comment]
@Moon422 No, you will not run into issues. The recommended option right now is to have .NET Core 3.1 SDK installed and optionally Mono, and use dotnet CLI as the build tool.
