### ISSUE TITLE
[Ubuntu 20.10] Icon not showing

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45256]
**Godot version:**
3.2.4 beta 6 MONO

**OS/device including version:**
Ubuntu 20.10

**Issue description:**
The icon is invisible in the tray, and its the OS default icon for executables in desktop.

![image](https://user-images.githubusercontent.com/58845030/104850474-1f813200-58ce-11eb-834d-18620423e910.png)

**Steps to reproduce:**
Just Download the mentioned version above

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
This is a limitation on Linux/*BSD in general. There is no way for *binaries* on Linux to embed an icon. Only `.desktop` files can have an icon associated to them.
