### ISSUE TITLE
Can't use editor while using tileset autotile, tileset editor goes off screen

### ISSUE THREAD

**Issue by tvardero** [godotengine/godot#45253]
**Godot version:** 3.2.3.stable.mono.official, russian translation
**OS/device including version:** Win10 x64, screen resolution 1366x768

**Issue description:**
Can't use inspector tab on the right, because tileset editor goes off screen when you select new region with selection tool.
Screen capture on GDrive: https://drive.google.com/file/d/1cpOEOLbv7FvIT21pPcqMzYKcQ705K-en/view?usp=sharing

![image](https://user-images.githubusercontent.com/45442278/104843831-4ee76d00-58d5-11eb-8cdb-985abc4a10c0.png)

There are lots of temporal solutions for this issue, like moving inspector to left tab.

**Comment by Calinou** [comment]
As a workaround, switch to English language in the Editor Settings to make button text shorter.
