### ISSUE TITLE
[New CPU Lightmapper] Lightmapper frequently hangs or crashes

### ISSUE THREAD

**Issue by DarkKilauea** [godotengine/godot#45260]
**Godot version:**

v3.2.4.beta6.official

**OS/device including version:**

Windows 10 (10.0.19042 Build 19042)
AMD Ryzen 7 3800XT
NVIDIA GeForce RTX 2080 (running GLES3)

**Issue description:**

While testing the new light mapper, when I went to bake the lightmaps, the process frequently hung at "Preparing data structures".   During that time, Godot maxes out my CPU, with most of that time occurring in the kernel.  I have waited up to 30 minutes for the process to recover, but it never has.

I have tried reducing the settings to Low for both Quality and Capture Quality and bounces to 0.  When bounces are 0, this appears to happen less often, but still happens the majority of the time.

When the process does crash, I get the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  you have to wait for spawned subtasks
```

Progress state:
![lightmapper_stalled_progress](https://user-images.githubusercontent.com/1929107/104856029-fdcf7d00-58c4-11eb-876a-26458235758f.png)

Godot in Task Manager:
![lightmapper_stalled_task_manager](https://user-images.githubusercontent.com/1929107/104856074-38391a00-58c5-11eb-919d-e700d102e2e9.png)

Task Manager CPU graph:
![lightmapper_stalled_task_manager_cpu](https://user-images.githubusercontent.com/1929107/104856079-40915500-58c5-11eb-8d1e-2305190d6cbe.png)

**Steps to reproduce:**
1. Attempt to bake a scene using the new light mapper.  See attached scene for an example.

**Minimal reproduction project:**

[TestGridmapLightmap.zip](https://github.com/godotengine/godot/files/5826849/TestGridmapLightmap.zip)

**Comment by mbrlabs** [comment]
That's a duplicate of #45097, but it's good to know that this also happens with AMD processors.

**Comment by jcostello** [comment]
Had the same issue

**Comment by DarkKilauea** [comment]
I compiled 3.2 myself from e25984a745cc5bbe292e41b5c9d441d59414051b using MSVC 14.2 and I don't see the hangs anymore.  As indicated by #45097, this may be an issue with how the official builds are constructed.

I'm going to close this ticket as #45097 was first.  Feel free to re-open if you think that is worthwhile.
