### ISSUE TITLE
[New CPU Lightmapper] Dynamic objects lose lighting when leaving and re-entering BakedLightmap extents

### ISSUE THREAD

**Issue by DarkKilauea** [godotengine/godot#45261]
**Godot version:**

v3.2.4.beta6.official

**OS/device including version:**

Windows 10 (10.0.19042 Build 19042)
AMD Ryzen 7 3800XT
NVIDIA GeForce RTX 2080 (running GLES3)

**Issue description:**

In beta 5, if a dynamic (not baked) mesh instance leaves the bounds of the BakedLightmap node it loses lighting information while out of the bounds and regains that lighting as soon as it re-enters.

https://user-images.githubusercontent.com/1929107/104855681-f313e880-58c2-11eb-9678-23f420b0d617.mp4

However, on beta 6 with the new lightmapper, the mesh instance does not regain lighting until the scene is reloaded in the editor.

*I'm still trying to capture a video of this, I will update the ticket when I successfully get a lightmap to bake*

**Steps to reproduce:**
1. Create a scene and bake a lightmap.
2. Add a MeshInstance and assign the default sphere mesh to it.
3. Find an area in the scene that does not get direct light and move the mesh there.  It should still show lighting due to bounced light.
4. Drag the mesh out of the lightmap's bounds.  It should turn black.
5. Move the mesh back into the lightmap's bounds.  Note that it doesn't regain its bounced lighting.

**Minimal reproduction project:**

[TestGridmapLightmap.zip](https://github.com/godotengine/godot/files/5826862/TestGridmapLightmap.zip)

**Comment by clayjohn** [comment]
This may actually be a result of the BVH/pairing changes. If so, it is likely already fixed by https://github.com/godotengine/godot/pull/45251

**Comment by DarkKilauea** [comment]
694e51d210b1a376418c9d067aa9d763689b5770 does indeed appear to fix the issue.  Closing this ticket since it has been fixed in the 3.2 branch, but feel free to re-open if you'd like.
