### ISSUE TITLE
InputEventKey not working for all scancodes

### ISSUE THREAD

**Issue by pederbacher** [godotengine/godot#45266]
**Godot version:**

3.2.3

**OS/device including version:**

Linux

**Issue description:**

Running the following code it should be expected that this generated an input event as if the 'A' key was pressed on the keyboard, e.g. an 'A' would be input to a TextEdit object in focus:
```
var ev = InputEventKey.new()
ev.scancode = KEY_A
ev.pressed = true
Input.parse_input_event(ev)
```
However nothing happens. If the scancode is:
```
ev.scancode = KEY_ENTER
```
then the cursor in a TextEdit reacts as if the ENTER key was pressed on the keyboard.

**Steps to reproduce:**
See code above

**Minimal reproduction project:**

[test_input_event.zip](https://github.com/godotengine/godot/files/5827027/test_input_event.zip)

**Comment by Xrayez** [comment]
Setting `unicode` property seems to work:

```gdscript
var ev = InputEventKey.new()
ev.scancode = KEY_B
ev.pressed = true
ev.unicode = 0x61 # "a"
Input.parse_input_event(ev)
```

Unfortunately I don't know whether scan codes are expected to work.

**Comment by EricEzaM** [comment]
TextEdit only looks at the unicode value when typing a character. When you type with your keyboard it sends both a scancode and a unicode value afaik.

As far as I am concerned, this is expected and not a bug.

https://github.com/godotengine/godot/blob/e25984a745cc5bbe292e41b5c9d441d59414051b/scene/gui/text_edit.cpp#L3769-L3774

**Comment by pederbacher** [comment]
Thanks a lot. Yes, well, it's probably not a bug, just difficult to figure out why it's like that. I don't know, I will just close the issue now, hoping others will find this information is they need it. Thanks.
