### ISSUE TITLE
Match statement maps to 2 when operations are used in head

### ISSUE THREAD

**Issue by ctkerns** [godotengine/godot#45293]
Godot version: 4.0 custom build 7fc9d4c79b3b790ff75c32317c25410f58ed1f68

OS: Windows 10.0.19042 Build 19042

Using integer operations in the head of a match statement will map to a 2 case if it is provided. One operand must be a variable.

Attach a new script and write in _ready as follows:  
```
func _ready():
	var bar = 1000
	
	match(bar + 0):
		2:
			print(2)
		1000:
			print(1000)
```

The output is 2 when it should obviously be 1000. It is consistently 2 even when using other operations and numbers.

[Match Issue.zip](https://github.com/godotengine/godot/files/5832083/Match.Issue.zip)

**Comment by Calinou** [comment]
Running the code snippet in 3.2.3 gives me `1000`, so this is a regression in `master`.

**Comment by HaSa1002** [comment]
it matches the type there:
```gdscript
match bar:
	var x:
		printt(x, typeof(x)) # will print 2	2
```
