### ISSUE TITLE
PoolRealArray inaccuracy

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot#45308]
**Godot version:**
3.2.3-stable

**OS/device including version:**
Windows 10

**Issue description:**
PoolRealArray seems to mess with the digits of a number, past 8 or more digits.

**Steps to reproduce:**
var real := PoolRealArray([1611054567])
-Prints: [1611054592]

var real2 := PoolRealArray([1661054567.5)]
-Prints: ([1661054592])

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
PoolRealArray is 32-bit floats, and that's about the accuracy that 32-bit floats provide.

If you need more accuracy, you should use a normal Array of floats (the GDScript `float` type is 64-bit).

**Comment by LoneDespair** [comment]
> PoolRealArray is 32-bit floats, and that's about the accuracy that 32-bit floats provide.
> 
> If you need more accuracy, you should use a normal Array of floats (the GDScript `float` type is 64-bit).

I see, although, why does godot allow me to print even higher values but just messes with the last digits?

**Comment by akien-mga** [comment]
That's how floating point numbers work. It doesn't mess with the last digits, it's the closest representation of what you tried to save as a 32-bit float. Cutting the last digits that cannot be represented precisely would not be a good option as it introduce an error of not some small percentage but several orders of magnitude.

**Comment by LoneDespair** [comment]
> That's how floating point numbers work. It doesn't mess with the last digits, it's the closest representation of what you tried to save as a 32-bit float. Cutting the last digits that cannot be represented precisely would not be a good option as it introduce an error of not some small percentage but several orders of magnitude.

Ohhh, I see, thank you so much

**Comment by akien-mga** [comment]
For info, see this C++ example:
```
#include <cstdio>

int main () {
    float numf = 2611054567;
    printf("%f\n", numf);
    double numd = 2611054567;
    printf("%f\n", numd);
    return 0;
}
```
Prints;
```
2611054592.000000
2611054567.000000
```

The same happens with Godot's `PoolRealArray` which uses C++ `float`.

Note that in 4.0 you'll have both `PackedFloat32Array` and `PackedFloat64Array`, the latter using C++ `double` (64-bit).
