### ISSUE TITLE
Sprite3D is not visible

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#45304]
**Godot version:**
7fc9d4c79b3b790ff75c32317c25410f58ed1f68

**OS/device including version:**
Win10/GTX1060

**Issue description:**
![image](https://user-images.githubusercontent.com/3036176/104999296-ac96c900-5a3d-11eb-8033-386e27a9e4f1.png)

**Steps to reproduce:**
Create a Sprite3D, assign a texture, and observe the result

**Minimal reproduction project:**
[TestBug.zip](https://github.com/godotengine/godot/files/5834183/TestBug.zip)

**Comment by Chaosus** [comment]
Ah, and I remember the @reduz said that `ImmediateGeometry` is not implemented (and hard to be implemented on Vulkan) and `Sprite3D` uses it.

**Comment by Calinou** [comment]
In `3.2`, Sprite3D no longer uses ImmediateGeometry for performance reasons but this change wasn't ported to `master` yet.

**Comment by akien-mga** [comment]
Fixed by #50014.
