### ISSUE TITLE
Color arithmetic operator inconsistencies in core

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#45307]
**Godot version:** master

**Issue description:**

https://github.com/godotengine/godot/blob/master/core/math/color.cpp#L592

There are a few inconsistencies with Color's operators[.](https://github.com/godotengine/godot/pull/34452)

* The `/= real_t` code has a check for if the value is zero, but not for `/ real_t` (no `=`). This inconsistency should be fixed eventually, but which behavior should be kept?

* All of the operators should also be changed from `real_t` to `float` because `Color` never has a need for more precision than `float` (using `double` is useless for `Color`).

* The parameter name `p_rvalue` could be changed. The vectors use `p_scalar`.

I think all of these can be fixed at the same time, but the first point requires discussion.

**Comment by akien-mga** [comment]
>     * The `/= real_t` code has a check for if the value is zero, but not for `/ real_t` (no `=`). This inconsistency should be fixed eventually, but which behavior should be kept?

Generally speaking it should be fine that `/ (real_t)0` has no special handling and gives NaN, however here for `Color` this might have been done for the renderer's sake? So I'm not sure which behavior should be kept, probably needs input from @reduz.

**Comment by reduz** [comment]
The rule is float /=0 should not check, int /=0 should check and throw error. I guess this needs to be changed.
