### ISSUE TITLE
Infinite recursion in project selector when directory fails to open

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#45302]
**Godot version:**
4.0.dev 8ba67b7

**OS/device including version:**
Windows [Version 10.0.19041.746]
NVidia 452.06 RTX 2080 Ti

**Issue description:**
Godot hangs when loading the project list, after deleting or moving the folder specified under `filesystem/directories/autoscan_project_path`

The main issue is that in project_manager.cpp, `void ProjectManager::_scan_dir(const String &path, List<String> *r_projects)` no error checking is performed after the `change_dir` call or the `list_dir_begin` call.

It seems that if change_dir fails, the DirAccess is left at the current working directory, which is my user home directory by default ("C:/Users/MYUSER").

Here is what I gathered by inspecting stack frames manually after the failure.
_scan_begin("C:/Projects/old_autoscan_directory")
_scan_dir("C:/Projects/old_autoscan_directory") -> change_dir fails and iterates through the original working directory, finding "AppData"
_scan_dir("C:/Users/MYUSER/AppData") -> "Local"
_scan_dir("C:/Users/MYUSER/AppData/Local") -> "ElevatedDiagnostics"
_scan_dir("C:/Users/MYUSER/AppData/Local/ElevatedDiagnostics") -> change_dir fails and iterates through the original working directory, finding "AppData"
_scan_dir("C:/Users/MYUSER/AppData") -> "Local"
_scan_dir("C:/Users/MYUSER/AppData/Local") -> "ElevatedDiagnostics"
...and so on

This actually uncovered two problems: one is if the autoscan project path does not exist; and the other is if any directory within the project path is not readable (due to permissions or otherwise), for example the above "ElevatedDiagnostics" directory:
![permission dialog showing no permissions other than Administrators and SYSTEM](https://user-images.githubusercontent.com/39946030/104983829-651f2700-59c2-11eb-80ed-55db7d955a32.png)

Here is the full stack trace:

```
ntdll.dll!NtOpenFile()
ntdll.dll!RtlpCreateNewDirectoryReference()
ntdll.dll!RtlSetCurrentDirectory_U()
KernelBase.dll!SetCurrentDirectoryW()
godot.windows.tools.64.exe!DirAccessWindows::change_dir(String p_dir) Line 132
	at S:\repo\godot4\drivers\windows\dir_access_windows.cpp(132)
godot.windows.tools.64.exe!DirAccessWindows::DirAccessWindows() Line 386
	at S:\repo\godot4\drivers\windows\dir_access_windows.cpp(386)
godot.windows.tools.64.exe!DirAccess::_create_builtin<DirAccessWindows>() Line 63
	at S:\repo\godot4\core\os\dir_access.h(63)
godot.windows.tools.64.exe!DirAccess::create(DirAccess::AccessType p_access) Line 246
	at S:\repo\godot4\core\os\dir_access.cpp(246)
godot.windows.tools.64.exe!ProjectManager::_scan_dir(const String & path, List<String,DefaultAllocator> * r_projects) Line 2169
	at S:\repo\godot4\editor\project_manager.cpp(2169)
godot.windows.tools.64.exe!ProjectManager::_scan_dir(const String & path, List<String,DefaultAllocator> * r_projects) Line 2175
	at S:\repo\godot4\editor\project_manager.cpp(2175)
......
godot.windows.tools.64.exe!ProjectManager::_scan_dir(const String & path, List<String,DefaultAllocator> * r_projects) Line 2175
	at S:\repo\godot4\editor\project_manager.cpp(2175)
godot.windows.tools.64.exe!ProjectManager::_scan_dir(const String & path, List<String,DefaultAllocator> * r_projects) Line 2175
	at S:\repo\godot4\editor\project_manager.cpp(2175)
godot.windows.tools.64.exe!ProjectManager::_scan_begin(const String & p_base) Line 2189
	at S:\repo\godot4\editor\project_manager.cpp(2189)
godot.windows.tools.64.exe!ProjectManager::ProjectManager() Line 2695
	at S:\repo\godot4\editor\project_manager.cpp(2695)
godot.windows.tools.64.exe!Main::start() Line 2368
	at S:\repo\godot4\main\main.cpp(2368)
godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 161
	at S:\repo\godot4\platform\windows\godot_windows.cpp(161)
godot.windows.tools.64.exe!_main() Line 185
	at S:\repo\godot4\platform\windows\godot_windows.cpp(185)
godot.windows.tools.64.exe!main(int argc, char * * argv) Line 199
	at S:\repo\godot4\platform\windows\godot_windows.cpp(199)
[Inline Frame] godot.windows.tools.64.exe!invoke_main() Line 78
	at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(78)
godot.windows.tools.64.exe!__scrt_common_main_seh() Line 288
	at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288)
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()
```

**Steps to reproduce:**
1. Set a folder for your autoscan path.
2. Open Godot's project selector
2. Open a project in that folder.
3. Close godot editor
4. Move the folder you selected as autoscan.
5. Open Godot's project selector **with its working directory set as your user home directory**

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
> This actually uncovered two problems: one is if the autoscan project path does not exist

We should make it so the autoscan project folder and default project folder are created automatically on project manager startup if they don't exist.
