### ISSUE TITLE
GLES2 Lights randomly stop working

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#45318]
**Godot version:**

3.2.4-beta6

**OS/device including version:**

Zorin OS 15

**Issue description:**

Lights stop lighting for no apparent reason, I tested with different bake modes and with and without BakedLightmap node, but I don't know what causes it.
![LightBug2](https://user-images.githubusercontent.com/27329423/105078804-cdd3d580-5a8e-11eb-8b76-6d3773858b34.gif)

**Steps to reproduce:**
No idea, it just happens.

**Minimal reproduction project:**

This is where I test this kind of stuff.
[LightMaps.zip](https://github.com/godotengine/godot/files/5837962/LightMaps.zip)

**Comment by Janders1800** [comment]
OK I fond out why.
https://twitter.com/lawnjelly/status/1351150452449169410
Fix:
https://www.reddit.com/r/godot/comments/kyl0eg/dev_snapshot_godot_324_beta_6_cpu_lightmapper/gjprkn2?utm_source=share&utm_medium=web2x&context=3

Well... I can probably close this, but as now, is still a bug. Feel free to close.

**Comment by lawnjelly** [comment]
It's ok we can leave open for now so anyone else can see who has lighting issues. The latest build with several fixes is available from #45311.

Or you can simply turn off `rendering->quality->spatial_partitioning->use_bvh` in the render settings as in my reddit post.

Also see #45292 which is similar.

**Comment by akien-mga** [comment]
Fixed by #45311 if I understand correctly.
