### ISSUE TITLE
Disconection betwen Gizmo and inspector values on BakedLightmap

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#45317]
**Godot version:**

3.2.4-beta6

**OS/device including version:**

Zorin OS 15

**Issue description:**

If you change Extents in the Gizmo it does not reflects on the inspector.
![GizmoBug](https://user-images.githubusercontent.com/27329423/105073975-18058880-5a88-11eb-8d2d-6bfccd8e1d56.gif)
@JFonS related: https://github.com/godotengine/godot/pull/44628

**Steps to reproduce:**
Add a BackedLightmap node and change its extents with the gizmo.

**Minimal reproduction project:**

No need.

**Comment by Calinou** [comment]
A `change_notify()` call was likely missed in the gizmo code.

**Comment by Bhu1-V** [comment]
I actually tried to fix this, but I didn't see the bounding box to extend neither in the viewport nor those values available in the inspector.

**Comment by Calinou** [comment]
@Bhu1-V The `master` branch has a different GPU-based lightmapper which doesn't have a notion of extents. You need to test this with the `3.2` branch.

**Comment by TamplierS1** [comment]
Hi, I fixed this by adding `_change_notify("extents")` to `_update_gizmo()` method in `Spatial` class. Do I create a pull request to 3.2 branch or master branch?

**Comment by Calinou** [comment]
> Hi, I fixed this by adding _change_notify("extents") to _update_gizmo() method in Spatial class. Do I create a pull request to 3.2 branch or master branch?

It seems too general to add this to the Spatial class. [Solutions must be local](https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local), so the fix should be applied to the BakedLightmap class.

**Comment by TamplierS1** [comment]
Okay, I moved `_change_notify("extents")` to `set_extents()` in `BakedLightmap` and opened a PR on 3.2 #45510

**Comment by akien-mga** [comment]
Fixed by #45510.
