### ISSUE TITLE
DisplayServer: UI Freeze on Windows after opening Popup

### ISSUE THREAD

**Issue by marstaik** [godotengine/godot#45325]
**Godot version:**
8a6d4dd

**OS/device including version:**
Windows/Vulkan

**Issue description:**
Sometimes when a pop is created on windows the UI is locked up, and then becomes unresponsive.

**Steps to reproduce:**
* Not reproducible on demand.
* Open some popup windows through godot and the UI will lockup.

example: https://f.staik.net/f/2ki.mp4

Relevant:
![image](https://user-images.githubusercontent.com/5601015/105129156-535c8300-5a99-11eb-9103-8bc76a67b486.png)

*Bugsquad edit: Linux counterpart of this issue: https://github.com/godotengine/godot/issues/41614*

**Comment by Xartorx** [comment]
> Not reproducible on demand.

Just do a right click on any folder in a FileSystem > Open in File Manager, for me it always locks the UI.
