### ISSUE TITLE
Incorrect mouse pointer position in hiDPI-corrected resolutions on web

### ISSUE THREAD

**Issue by Guang1234567** [godotengine/godot#45323]
Hello @akien-mga 

> Fix pointer position in hidpi-corrected resolutions on web #29786

> @akien-mga akien-mga added this to the 3.2 milestone on 16 Jun 2019

still not working on `godot v3.2.3`, thanks.

Below screen recording shows the problem:

https://user-images.githubusercontent.com/8240718/105017454-bee52700-5a7e-11eb-99ad-ff9c3e292c33.mp4

_Originally posted by @Guang1234567 in https://github.com/godotengine/godot/issues/29661#issuecomment-762729284_

**Comment by Guang1234567** [comment]
- macOS  10.15.7

- chrome browser for macOS (version 87.0.4280.141) ,  newest at this moment.

- export template


![1611050174827](https://user-images.githubusercontent.com/8240718/105019094-ae35b080-5a80-11eb-9ae6-72683c25a560.jpg)

[bug_godot_hidpi_html5_chrome_macOS.zip](https://github.com/Guang1234567/Godot_MyFirstGame.git)

**Comment by Faless** [comment]
Does this also happens with 3.2.4rc1 ? https://downloads.tuxfamily.org/godotengine/3.2.4/rc1/ . I believe HiDPI is still kinda broken there, but the input positioning issue should be fixed. I'm reworking that part a bit though (to make it a bit more like native), so I'll be having a look anyway.

**Comment by Guang1234567** [comment]
> Does this also happens with 3.2.4rc1 ? https://downloads.tuxfamily.org/godotengine/3.2.4/rc1/ . I believe HiDPI is still kinda broken there, but the input positioning issue should be fixed. I'm reworking that part a bit though (to make it a bit more like native), so I'll be having a look anyway.


2021-02-09
-------------------
Just test on `3.2.4rc1` right now ,  but still works as video says:

https://user-images.githubusercontent.com/8240718/105017454-bee52700-5a7e-11eb-99ad-ff9c3e292c33.mp4

**Comment by Guang1234567** [comment]
@Faless 

> but the input positioning issue should be fixed

You are right !

My problem is caused by `GetViewport().Size;`,  this api return the wrong result in `Hidpi` mode.

Because i dont want to hard code in `Hidpi` mode. Could you give me some suggestion?
 
https://github.com/Guang1234567/Godot_MyFirstGame/blob/f7589ac4518a65c3bad477b73d25c44a98c655a5/Player.cs#L19-L21

**Comment by Faless** [comment]
Closing as per user comment, the "size" issue is fixed via #45920
