### ISSUE TITLE
TextureAtlas generates empty file

### ISSUE THREAD

**Issue by devvoid** [godotengine/godot#45324]
**Godot version:**
v3.2.3 Stable

**OS/device including version:**
Ubuntu 20.04.1 LTS

**Issue description:**
Trying to generate a texture atlas with the provided assets produces a blank image.

The problem doesn't seem to be the really large resolution of the provided files - other files in my project which are of similar size import into atlases just fine.

Sometimes when importing, I get this error message:
`scene/resources/bit_map.cpp:37 - Condition "p_size.width < 1" is true.`

**Steps to reproduce:**
* Download the reproduction project
* Try to import the files as a TextureAtlas

**Minimal reproduction project:**
[packertest.zip](https://github.com/godotengine/godot/files/5840117/packertest.zip)

**Comment by boruok** [comment]
still valid in 3.3.3.stable.
Looks like godot can't handle transparent pixels in corners.
.

**Comment by kleonc** [comment]
Seems already fixed in `3.4.1.stable`.

**Comment by Calinou** [comment]
Likely fixed by https://github.com/godotengine/godot/pull/55094 and/or https://github.com/godotengine/godot/pull/55235.
