### ISSUE TITLE
screen_texture/ImageTexture of Viewport shader bug

### ISSUE THREAD

**Issue by Reapetitive** [godotengine/godot#45327]
A new thing i discovered yesterday - screen_texture/ImageTexture of Viewport based shaders seem to behave really wierd too. I am using a shader to add reflections of the world to glass etc. Sometimes i use Polygon2Ds to apply the shader to, sometimes Sprites. Polygon2Ds seem to display the shader result pretty well, while Sprites flicker around and display objects sporadically. Increasing the Z_Index of the sprite helps, but doesnt resolve the issue. I ve been having an issue with screen_texture not displaying everything on screen properly anyway, even while using Backbuffer Copy. So i assigned ImageTexture of Viewport to a shader variable through script. But this workaround seems to be half broken now too.

_Originally posted by @Reapetitive in https://github.com/godotengine/godot/issues/41513#issuecomment-762651752_

**Comment by Calinou** [comment]
@Reapetitive Did you find a solution to this? If so, please post it here :slightly_smiling_face:

**Comment by akien-mga** [comment]
Thsi was a wrongly opened issue which was meant as comment on #41513.
