### ISSUE TITLE
Godot 4.0 UV2 not working

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#45330]
**Godot version:**
Godot 4.0. Build 8a6d4dd5e

**OS/device including version:**
MX Linux (Debian based)
Nvidia GT1030

**Issue description:**
Unwrapping/Showing UV2 is not working

**Steps to reproduce:**
Grab any 3D model (Sponza for example). Try to unwrap uv2 (or use and exported uv2). The UV is not shown correcly. When trying to bake the light its not using it correctly.

**Minimal reproduction project:**

[Godot 4.0 UV.zip](https://github.com/godotengine/godot/files/5843388/Godot.4.0.UV.zip)

**Comment by Calinou** [comment]
@jcostello Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by jcostello** [comment]
@Calinou Done. I uploaded a minimal reproduction project :muscle:

**Comment by jcostello** [comment]
Fixed in master
