### ISSUE TITLE
Android export broken; apksigner error #127

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#45341]
**Godot version:**

3.2.4-beta5 & 3.2.4-beta6

**OS/device including version:**

Zorin OS 15
Redmi note 9

**Issue description:**

Since 3.2.4-beta5 exporting to android doesn't work.
I set up the new required sdk path on editor settings.

but wen I export to android I get this error
![Screenshot from 2021-01-21 02-54-07](https://user-images.githubusercontent.com/27329423/105272650-19bf7100-5b9a-11eb-8209-b7de2888b506.png)
Godot complains about the sdk sometimes, seems to be random.

This is my editor setting config.
![Screenshot from 2021-01-21 03-40-49](https://user-images.githubusercontent.com/27329423/105272874-820e5280-5b9a-11eb-93bc-ac1bfdadca1c.png)

I tried with jdk 8 and 11 and the one in android studio with no avail.
In 3.2.4-beta4 exports perfectly fine.

**Steps to reproduce:**
Try to export to android

**Minimal reproduction project:**

[Virtual Analog.zip](https://github.com/godotengine/godot/files/5846506/Virtual.Analog.zip)

**Comment by volzhs** [comment]
it was changed in beta 5.
this document will help.
https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html

after beta 5, actually, there is no need about `adb` and `jarsigner`
![image](https://user-images.githubusercontent.com/8281454/105274328-501fdf00-5be0-11eb-868a-a3451f9ca96b.png)

if you want to keep using beta 5 or later, try to delete `export/android/...` in `editor_settings-3.tres` which can be found at Editor => Open Editor Settings Folder

**Comment by Janders1800** [comment]
Still the same. I'll try to reinstall Android Studio (since I have a somewhat old version).

**Comment by Janders1800** [comment]
OK, I'm retarded, forgot to generate a new keystore (the old one will not work). Feel free to close.

**Comment by volzhs** [comment]
good to hear that.

**Comment by akien-mga** [comment]
Maybe we should document that if apksigner adds new requirements on the debug keystone @m4gr3d.

The error about needing a valid Android SDK path when there's one is also weird.

**Comment by Janders1800** [comment]
No need, the Android SDK error was a mistaken on my part. Since the log screen doesn't get cleared wen you make a new export, that was the old error wen I didn't had it configured.

Everything seems to work OK. Tho it would be nice to tell in the docs that old keystores will not work, and you need to generate a new one.

**Comment by cjmxp** [comment]
‘apksigner’ returned with error #1
‘apksigner’ returned with error #1
‘apksigner’ returned with error #1
‘apksigner’ returned with error #1

**Comment by cjmxp** [comment]
Godot version:

3.2.4-beta6

OS/device including version:
win10

Issue description:

I don't know why I tried almost everything, but I couldn't solve this problem. I also regenerated the keystore

**Comment by akien-mga** [comment]
@cjmxp The error is `Exception in thread "main" java.lang.OutOfMemoryError`, it sounds like you are running out of RAM. How much RAM do you have on that system? Can you monitor its usage while exporting the APK to see if it reaches 100% and eventually fails?

**Comment by cjmxp** [comment]
3.2.4-beta 4 can be exported. My memory is 16g to use 30%

**Comment by akien-mga** [comment]
Could you open a new issue for this `OutOfMemoryError`? It's also related to the switch to `apksigner` but it's unrelated to @Janders1800's issue, so we should treat it separately.

**Comment by cjmxp** [comment]
The apksigner parameter should modify the memory size of the JVM

**Comment by tqm-dev** [comment]
@akien-mga 

Is it possible to reopen it ? because, I still have same issue on godot 3.3 RC8. (https://downloads.tuxfamily.org/godotengine/3.3/rc8/). 
When I try to export for android, getting the error message below:
 'apksigner' returned with error #127

but in 3.2.3 stable release, exports perfectly fine.  

OS              : Ubuntu 18.04 
Build target : oculus quest 2 (Android)

**Comment by akien-mga** [comment]
@tqm-dev Which versions do you have for the Java JDK and Android build tools?
The documentation mentions that one should use Android build tools 30.0.x: https://docs.godotengine.org/en/3.3/getting_started/workflow/export/exporting_for_android.html

But it might be that you actually need 29.0.x for OpenJDK 8: https://github.com/godotengine/godot-docs/issues/4796

**Comment by tqm-dev** [comment]
@akien-mga 

> @tqm-dev Which versions do you have for the Java JDK and Android build tools?
> The documentation mentions that one should use Android build tools 30.0.x: https://docs.godotengine.org/en/3.3/getting_started/workflow/export/exporting_for_android.html

I am currently using OpenJDK 8 , and android build tool 30.0.1.
so I followed the doc :
https://docs.godotengine.org/en/3.3/getting_started/workflow/export/exporting_for_android.html
 
> But it might be that you actually need 29.0.x for OpenJDK 8: [godotengine/godot-docs#4796](https://github.com/godotengine/godot-docs/issues/4796)

Okay, I am going to try it.

Thank you.

**Comment by tqm-dev** [comment]
@akien-mga 
>> But it might be that you actually need 29.0.x for OpenJDK 8: godotengine/godot-docs#4796

I tried uninstall 30.0.1 and reinstall 29.0.3 
but still same problem here.

**Comment by akien-mga** [comment]
Did you try to generate a new debug keystore using the instructions from https://docs.godotengine.org/en/3.3/getting_started/workflow/export/exporting_for_android.html#create-a-debug-keystore ?

The original issue here (error `#127`) was due to this and fixed this way.

**Comment by tqm-dev** [comment]
> Did you try to generate a new debug keystore using the instructions from https://docs.godotengine.org/en/3.3/getting_started/workflow/export/exporting_for_android.html#create-a-debug-keystore ?

Yes ,  I tried a lot.
placed to .android dir then set the path in Editor Settings->Export->Android->Debug keystore.
But I could not solve it.

**Comment by m4gr3d** [comment]
@tqm-dev Can you enable `verbose stdout` in your project settings. That should provide more information about why the signing step is failing.
Also, can you try building your apk after enabling `custom build` and let us know if that succeeds.

**Comment by tqm-dev** [comment]
@m4gr3d 
I have got some messages on log window:

Starting signing of the APK binary using /home/tqm-dev/Android/sdk/build-tools/30.0.1/apksigner
Signing debug binary using: 
/home/tqm-dev/Android/sdk/build-tools/30.0.1/apksigner sign --verbose --ks /home/tqm-dev/.android/debug.keystore --ks-pass pass:android --ks-key-alias androiddebugkey /home/tqm-dev/.cache/godot/tmpexport.apk

but I could not get additional error messages.
I think that Oculus quest need v2 scheme for signing but it is not v2 explicitly.

**Comment by m4gr3d** [comment]
@tqm-dev Could you try to run the last command in a terminal window and see what happens (you may need to check that the `tmpexport.apk` file is still there first):

`/home/tqm-dev/Android/sdk/build-tools/30.0.1/apksigner sign --verbose --ks /home/tqm-dev/.android/debug.keystore --ks-pass pass:android --ks-key-alias androiddebugkey /home/tqm-dev/.cache/godot/tmpexport.apk`

**Comment by m4gr3d** [comment]
@tqm-dev In addition can you enable `custom build` in your Android export settings and try building and signing your apk again.

**Comment by tqm-dev** [comment]
> @tqm-dev Could you try to run the last command in a terminal window and see what happens (you may need to check that the `tmpexport.apk` file is still there first):
> 
> `/home/tqm-dev/Android/sdk/build-tools/30.0.1/apksigner sign --verbose --ks /home/tqm-dev/.android/debug.keystore --ks-pass pass:android --ks-key-alias androiddebugkey /home/tqm-dev/.cache/godot/tmpexport.apk`

I got the error message below:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/android/apksigner/ApkSignerTool, offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:774)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```
I seems that java would not be found but
 $ java -version
works fine for me.

**Comment by tqm-dev** [comment]
> @tqm-dev In addition can you enable `custom build` in your Android export settings and try building and signing your apk again.

I am going to try but still struggling to set it up for custom build yet .

**Comment by tqm-dev** [comment]
Once I switched  java runtime OpenJ9  to HotSpot (both are OpenJDK 8) 
is giving me the error:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Then I installed OpenJDK 11 HotSpot and tried again, the result is different than before:

```
Exception in thread "main" java.io.FileNotFoundException: /home/takuma/.cache/godot/tmpexport.apk (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:183)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:344)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:84)
```

**Comment by tqm-dev** [comment]
@m4gr3d

I tried signing my `godot_quest_example.apk` file with apksigner(OpenJDK 11 HotSpot) was succeeded  by manually.
And installed apk by adb command, then launched my app using SideQuest or adb shell.
I think the reason why I failed signing is related for signing the `tmpexport.apk`, not  `godot_quest_example.apk`.

**Comment by akien-mga** [comment]
@tqm-dev Does it work if you delete `~/.cache/godot/tmpexport*`?

**Comment by tqm-dev** [comment]
@akien-mga 
> @tqm-dev Does it work if you delete `~/.cache/godot/tmpexport*`?

It does not exist when I try to delete it.
`tmpexport.apk` only appeared at one click deploy, then immediately removed.

**Comment by tqm-dev** [comment]
@akien-mga
I solved .

The way that solved the issue for me is that launch godot from command line with using OpenJDK 11.
also using OpenGL ES3 is fine for me.

I do not know the problem is only for my environment. 
If it is not, the documentation should be maintained with more details for exporting to Oculus Quest 2. 

Thank you.

**Comment by AlexSleepy** [comment]
I had the same problem with error #127 and no matter what I did it was still there.
Fixed it by downloading Godot from official website. The one that I had before was from Elementary OS App Center (I guess it is a flatpack) and reinstalling it did not help, but the version from the website works just fine

**Comment by Calinou** [comment]
> The one that I had before was from Elementary OS App Center (I guess it is a flatpack) and reinstalling it did not help, but the version from the website works just fine

Exporting to Android isn't supported in Snap/Flatpaks because of sandboxing limitations.

**Comment by AlexSleepy** [comment]
Ok, makes sense. But it's pretty hard to understand it from the error message

**Comment by Calinou** [comment]
> Ok, makes sense. But it's pretty hard to understand it from the error message

To improve this, we can prevent exporting to Android from the Flatpak/Snap versions, either by patching those versions or detecting the presence of a `/.flatpak-info` file and triggering an error in the case.

**Comment by kowsen** [comment]
I just ran into this and want to throw my solution onto this in case anyone else ends up here with the same problem as me.

My problem was that I never added openjdk's bin folder to my PATH. This wasn't an issue in earlier versions since we told godot where to find jarsigner, but the new version assumes it (or some other openjdk component) is in your PATH.

You can fix it by adding this line to your ~/.profile file:

```
PATH="WHEREVER_YOU_PUT_OPENJDK/openjdk8/bin:$PATH"
```

**Comment by naturally-intelligent** [comment]
Also encountering this problem on Linux (Ubuntu 20.04 MATE), and seem to have a solution:

Oddly, if I launch godot manually from a terminal, the apksigner error doesn't appear, and it exports normally. 

If I launch godot from a desktop shortcut, then the apksigner error occurs.

**Comment by kowsen** [comment]
Have you tried the solution I posted above? It sounds like you might be
adding something to your PATH variable in either your terminal or .bashrc
file when you need to set it in .profile if you want stuff launched outside
the terminal to see it.

**Comment by RishiNiranjan** [comment]
> OK, I'm retarded, forgot to generate a new keystore (the old one will not work). Feel free to close.

For me this solution didnt work. I unticked the  'signed' box under package section and export was successful

**Comment by rafaelsescato** [comment]
> Acabei de me deparar com isso e quero lançar minha solução nessa discussão, caso mais alguém acabe aqui com o mesmo problema que eu.
> 
> Meu problema foi que eu nunca adicionei a pasta bin do openjdk ao meu PATH. Isso não era um problema nas versões anteriores, pois dissemos ao godot onde encontrar o jarsigner, mas a nova versão assume que (ou algum outro componente do openjdk) está no seu PATH.
> 
> Se você estiver na mesma situação que eu, você pode corrigi-lo adicionando esta linha ao seu arquivo ~/.profile e reiniciando:
> 
> ```
> PATH="WHEREVER_YOU_PUT_OPENJDK/openjdk8/bin:$PATH"
> ```



> I just ran into this and want to throw my solution onto this discussion in case anyone else ends up here with the same problem as me.
> 
> My problem was that I never added openjdk's bin folder to my PATH. This wasn't an issue in earlier versions since we told godot where to find jarsigner, but the new version assumes it (or some other openjdk component) is in your PATH.
> 
> If you're in the same situation I was, you can fix it by adding this line to your ~/.profile file and then rebooting:
> 
> ```
> PATH="WHEREVER_YOU_PUT_OPENJDK/openjdk8/bin:$PATH"
> ```

Thank you very much the solution also worked pramin. But for some reason I had already added it to ~/.bashrc and ~/.zshrc, and just to export to android I got the signature error (#127). To be able to avoid this error I had to open it through the terminal.

OS: POP_OS 21.10
GODOT: v3.4.4.stable.official [419e713a2] (download from official site)

**Comment by Calinou** [comment]
> But for some reason I had already added it to ~/.bashrc and ~/.zshrc, and just to export to android I got the signature error (https://github.com/godotengine/godot/pull/127). To be able to avoid this error I had to open it through the terminal.

`.bashrc` and `.zshrc` are *not* read by your desktop environment when you log in. To have environment variables that work with your basic GUI session (when not starting applications from a terminal), you need to add them to the system-wide `/etc/environment`. This file needs to be edited as root, and it *cannot* expand environment variables. Therefore, paths must be written in their full, absolute form, instead of using variables such as `$HOME`.

**Comment by f33h** [comment]
Check $PATH and $JAVA_HOME, it solved the issue for me.

**Comment by richardvanderdys** [comment]
After having the same `apksigner` errors, I also was able to install my app to the Meta Quest 2 device after opening Godot via the terminal. I imagine it has something to do with me using `.zshrc` for my PATH changes.

My problem though is that the app/game never loads.... I only see the 3 loading dots forever.

Has any one else seen this issue?

**Comment by dijs** [comment]
I was seeing the same issues as I also use `.zshrc`. Once I opened Godot through the terminal, it shows the little android icon in the top right and I can "install" it.

The problem for me is that the app never actually loads. It just shows the 3 dots forever.

Any ideas why that might be happening?

**Comment by naturally-intelligent** [comment]
> I was seeing the same issues as I also use `.zshrc`. Once I opened Godot through the terminal, it shows the little android icon in the top right and I can "install" it.
> 
> The problem for me is that the app never actually loads. It just shows the 3 dots forever.
> 
> Any ideas why that might be happening?

You could run "adb" in another terminal to try and see what's happening. There might be a better way tho
