### ISSUE TITLE
GDscript does not properly assign variables

### ISSUE THREAD

**Issue by engineer0x47** [godotengine/godot#45343]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
Windows, not graphics related

**Issue description:**
Variable assignment is not performed by GDscript

**Steps to reproduce:**
Calling the below function, such as:
    MakeActiveWindowButton(1)
Godot exits with error.  Doesn't matter where called, another function, end of _ready(), after yield(get_tree().root.get_child(get_tree().root.get_child_count()-1), "ready").  Based on the "Print" statements the variable is clearly not NULL, so the assignemnt is never made.

    Invalid call. Nonexistent function 'add_stylebox_override' in base 'Nil'.

The "print" statements print the following:

    1
    [Button:####]
    Null

**Minimal reproduction project:**

    func MakeActiveWindowButton(selectedScreenmode) -> void:
	    var buttonActive = null

	    var new_stylebox_normal = buttonSettings.get_stylebox("normal").duplicate()
	    new_stylebox_normal.border_color = Color(0, 0.5, 1)
	    new_stylebox_normal.bg_color = Color(0, 0.5, 1.0, 0.3)

	    print(selectedScreenmode)
	    print(buttonBorderless)

	    match selectedScreenmode:
		0:
		    buttonActive = buttonWindowed
		1:
		    buttonActive = buttonBorderless
		2:
		    buttonActive = buttonFullscreen

	    print(buttonActive)

	    buttonActive.add_stylebox_override("normal", new_stylebox_normal)

**Comment by engineer0x47** [comment]
There iss other code for the buttons, I left it out for clarity, but here is  the full thing.  tabs/spaces are consistent in the eidtor, but GitHub's editor is lacking so I had to change it so it showed up properly here:


[bug_sample.gd.txt](https://github.com/godotengine/godot/files/5847182/bug_sample.gd.txt)

**Comment by aaronfranke** [comment]
You are missing `extends` in your script, so none of the methods from Node or its ancestors are available.

**Comment by engineer0x47** [comment]
This is not the entire script.  The script extends Control.

**Comment by engineer0x47** [comment]
OK, the shorter codebase does not duplicate it, but calling the assignment multiple times in a row resolves it.  It is a race condition in the Godot interpreter.

... [more code here] ...

buttonActive = buttonVsyncOff
buttonActive = buttonVsyncOff
buttonActive = buttonVsyncOff
buttonActive = buttonVsyncOff
buttonActive = buttonVsyncOff

... [more code here] ...

**Comment by engineer0x47** [comment]
[_gdscript_assignment_bug.zip](https://github.com/godotengine/godot/files/5851209/_gdscript_assignment_bug.zip)

**Comment by aaronfranke** [comment]
@engineer0x47 The problem is unclear from this project. What is the current output? What is the expected output? Where are you putting `buttonActive = buttonVsyncOff`? For me, the print statement on line 126 does have a node reference.

**Comment by engineer0x47** [comment]
It's real weird, like the match statement is being skipped. In the "output" section below there should be a "godot 1" but there isn't.  And those "while" loops are never called.  I had it working until I implemented a settings loading function and am calling this function after "_ready" so it will update the button highlights to match the selections.  Based on the print statements in the output "selectedVsyncmode" is clearly "1".


![Capture](https://user-images.githubusercontent.com/836411/105395703-0689c100-5bed-11eb-81e2-964498a309b7.PNG)

**Comment by engineer0x47** [comment]
I thought I did the "match" statement wrong so I retyped it.  The assignment works if it is not in the "match" statement, but the GUI behaviour is not as desired (it's always set to the same button, not the correct one to the player).

![Capture3](https://user-images.githubusercontent.com/836411/105397331-ea871f00-5bee-11eb-9acc-6c934a770d22.PNG)

**Comment by engineer0x47** [comment]
I cloned the Godot repo and ported the code to Godot 4 (mostly by commenting out things like calls to the "os" class and "export" for arrays).  Many function calls do not work because "get_stylebox()" is not implemented.  The match statements function in the Godot 4 gdscript interpreter (tag a9b151c66).  Text is weird but thee entire game largely works in Godot 4.

![Capture4](https://user-images.githubusercontent.com/836411/105430274-24711900-5c21-11eb-8419-38696cd83aea.PNG)

**Comment by Calinou** [comment]
> Many function calls do not work because "get_stylebox()" is not implemented. The match statements function in the Godot 4 gdscript interpreter (tag a9b151c).

`get_stylebox()` is now `get_theme_stylebox()` in 4.0.
