### ISSUE TITLE
Baked lightmap doesn't respect bounding box (3.2.4.beta6)

### ISSUE THREAD

**Issue by rena-souza** [godotengine/godot#45358]
**Godot version:** 3.2.4.beta6

**OS/device including version:** Ubuntu 18.04.5 LTS
**GPU:** GeForce RTX 2060
**Backend:** GLES3

**Issue description:**

When using baked lightmapping, the light of objects outside of the bounding box are being baked

https://user-images.githubusercontent.com/8316202/105441874-3914d780-5c48-11eb-92eb-55b98007b213.mp4

**Steps to reproduce:**
Add two meshes in a scene, add a light, and a baked lightmap with a bounding box that covers only one of the meshes. When the light is baked, both meshes are affected

**Minimal reproduction project:**

[test-light-3.2.4.zip](https://github.com/godotengine/godot/files/5853410/test-light-3.2.4.zip)

**Comment by Calinou** [comment]
Are the meshes *unique* scenes? If they're shared instances, I think it's expected that the lighting will show up on both of them the same way.

**Comment by rena-souza** [comment]
The meshes are a single scene instaced twice. 
On version 3.2.3 the baked lightmap respect the bounding box. To me this looks like a regression. 
In my case I had a scene that was taking 10 minutes to bake when testing the new 3.2.4, and tried to reduce the bounding box to be able to experiment with light faster, but even reducing the bound box, it did not reduced the time to bake, and the baked light was being applied in the whole scene


**Same project in 3.2.3**

https://user-images.githubusercontent.com/8316202/105512509-f1c23180-5caf-11eb-816f-cf92aa6cb1af.mp4

**Comment by JFonS** [comment]
It is a regression indeed. I ported some code over from master, where lightmaps don't have bounding boxes, and I forgot to add the  bounding boc check. My bad :)

I will fix this along with other issues in my next PR.

**Comment by akien-mga** [comment]
Fixed by #45752.
