### ISSUE TITLE
VsplitContainer and HsplitContainer wont work with more than two children

### ISSUE THREAD

**Issue by astrale-sharp** [godotengine/godot#45352]
I've searched for similar issues but i didnt find any (that being said, my english vocabulary is not that large : i may have failed)
-->

**Godot version: 3.2.3.stable.official**

**OS/device including version:**
```
❯ screenfetch
                                       astrale@Sharp
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Linuxmint 20.1 ulyssa
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 5.4.0-62-generic
 MMd      /++                -sNMd:    Uptime: 8h 45m
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages: 3707
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: fish 3.1.0
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution: 1920x1080
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 4.8.6
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Muffin
     NMm  dMM  .mmd  `mmm   yMM. dMM   WM Theme: Mint-Y-Dark-Blue (Mint-Y)
     NMm  dMM`  ..`   ...   ydm. dMM   GTK Theme: Mint-Y-Dark-Red [GTK2/3]
     hMM- +MMd/-------...-:sdds  dMM   Icon Theme: breeze-dark
     -NMm- :hNMNNNmdddddddddy/`  dMM   Font: Ubuntu Condensed, 24
      -dMNs-``-::::-------.``    dMM   Disk: 688G / 1,1T (71%)
       `/dMNmy+/:-------------:/yMMM   CPU: Intel Core i3-2330M @ 4x 2.2GHz [66.0°C]
          ./ydNMMMMMMMMMMMMMMMMMMMMM   GPU: GeForce GT 630M
             \.MMMMMMMMMMMMMMMMMMM     RAM: 1914MiB / 3844MiB
                                      

```

GLES3

**Issue description:**

i made a tree with a VsplitContainer which had three button children, the first two buttons are positioned one on top of the other (which is what you would expect from a VsplitContainer which had two button children) the third one is not sized well and disposed at the same place as the first button which is really weird.
I expected the three buttons to be evenly spaced in the y axes.

I colored the third button in red :
![godot_issue](https://user-images.githubusercontent.com/53686698/105389759-82e5c980-5c18-11eb-915b-15bfb089fff0.png)

![godot_issue2](https://user-images.githubusercontent.com/53686698/105389792-9133e580-5c18-11eb-83f8-d928a12964c8.png)

**Steps to reproduce:**

in a new scene with a VsplitContainer as root, had three buttons

**Minimal reproduction project:**

[issue.zip](https://github.com/godotengine/godot/files/5851147/issue.zip)

**Comment by pycbouh** [comment]
This is not a bug. `SplitContainer`s only deal with 2 children. This is their only function. If you want multiple evenly spaced items, you need to use `BoxContainer`s.

**Comment by astrale-sharp** [comment]
Okay thanks, the documentation should probably be changed then !

**Comment by pycbouh** [comment]
Which part of the documentation misled you?

**Comment by astrale-sharp** [comment]
Oh, you're right ! I just misread V**box**Container and V**split**Container twice!
thanks again!
