### ISSUE TITLE
_unhandled_event is not called for mouse button events on Controls

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#45363]
**Godot version:**
* 3.2.3

**OS/device including version:**
* macOS 10.15.7

**Issue description:**
A Button handles mouse clicks even if button_mask is set to ignore the mouse button and mouse_filter is set to pass. _unhandled_event is not called.

**Steps to reproduce:**
* Create a Button (e.g. TextureButton)
* Leave button_mask to the default (only left button)
* Set mouse_filter to pass
* Connect the pressed signal to a function (any function body works)
* Create a _unhandled_event function
* Click on the button *with the right mouse button*
* => Neither the pressed-signal function nor the unhandled_event function will be called

**Minimal reproduction project:**
[unhandledinput.zip](https://github.com/godotengine/godot/files/5857019/unhandledinput.zip)

**Comment by KoBeWi** [comment]
This is not a bug. You need to use `MOUSE_FILTER_IGNORE`, otherwise the input will be handled automatically if it hits any control (even if that control doesn't handle it).

This is even stated in the docs:
> If this control does not handle the event, the parent control (if any) will be considered, and so on until there is no more parent control to potentially handle it. This also allows signals to fire in other controls. Even if no control handled it at all, the event will still be handled automatically, so unhandled input will not be fired.

**Comment by dploeger** [comment]
But will the pressed event on the texture button for the left button be carried out?

The docs seem to state (to me at least) that even that wouldn't be handled, because all mouse events will be ignored.

**Comment by KoBeWi** [comment]
Any mouse input event on a control is handled, unless the control is set to ignore it. Even if the control doesn't "use" this event, as long as it received it, it will be handled. Mouse filter STOP/PASS only determines whether this event will be propagated further.

**Comment by dploeger** [comment]
Sorry, I still don't get it. 

Didn't you suggest to ignore it (by setting MOUSE_FILTER_IGNORE) in your first message or did I understand you wrong there?

I will try to set that and see whether the left mouse click on the texture button will still be handled by the pressed function.

**Comment by dploeger** [comment]
Yes, the left mouse click is not handled by the pressed function anymore.

Maybe we're misunderstanding each other:

I want the left mouse click to be handled by the pressed function and the right mouse click by the _unhandled_event function.

**Comment by KoBeWi** [comment]
> I want the left mouse click to be handled by the pressed function and the right mouse click by the _unhandled_event function.

This is not possible. You need to intercept the event yourself and pass it via script to the object you want.

This is how Control nodes work. If you see some missing functionality, [you can open a proposal](https://github.com/godotengine/godot-proposals) if there isn't any.
You might be interested in this https://github.com/godotengine/godot-proposals/issues/1959 or this https://github.com/godotengine/godot-proposals/issues/1775

**Comment by dploeger** [comment]
Thanks for the clarification

**Comment by dploeger** [comment]
Those both don't really handle this problem. Created a new one.
