### ISSUE TITLE
Wrong input mapping for Dual Shock 3 over bluetooth

### ISSUE THREAD

**Issue by pcmxms** [godotengine/godot#4537]
Operating system or device: Gnome Ubuntu Linux 16.04

Issue description (what happened, and what was expected): By trying to configure DS3 in my game I realised that the suggestion given by the editor for the buttons is completely wrong (ex: button 0 --> PS = X, Nintenda = A, etc...). Turns out, for instance, that select button is the godot X
Emoticon. How can I get the button mapping so to not going for a "trial and error" approach?

Steps to reproduce: Project settings --> input map: Map the buttons and test it.

**Comment by akien-mga** [comment]
According to @Hondres, it would be related to https://github.com/gabomdq/SDL_GameControllerDB/issues/66

**Comment by Hinsbart** [comment]
I'll look into it. I remember that my ds3 was working over bluetooth, but there may be multiple revisions or something.

Btw, I should get rid of that @Hondres account... causes confusion or even wrongly attributed commits :/

**Comment by akien-mga** [comment]
> Btw, I should get rid of that @Hondres account... causes confusion or even wrongly attributed commits :/

Hehe, estimate yourself lucky, some guy grabben the "akien" account 5 years ago and never did anything with it :p You could ask the GitHub guys to merge your two accounts into one.

**Comment by Hinsbart** [comment]
Alright, turns out my system also needs the new mapping with bus type 5.
However a quick google search for "ps3 bus type 006" revealed that a lot of people are indeed running this thing on bus 6, so I also kept the old one.
I guess it was fixed in a (more or less) recent driver/kernel.
