### ISSUE TITLE
Assigning joint_i_to_name to self in gltf_skin.cpp

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#45371]
**Godot version:**
4.0.dev.custom_build .d39f6386c

**Issue description:**
https://github.com/godotengine/godot/blob/d39f6386ce3a7916dbb94fef5ff65e7599e060f0/modules/gltf/gltf_skin.cpp#L145

**Comment by fire** [comment]
Shouldn't this be:

```c++
void GLTFSkin::set_joint_i_to_name(Dictionary p_joint_i_to_name) {
	Array keys = p_joint_i_to_name.keys();
	for (int i = 0; i < keys.size(); i++) {
		joint_i_to_name[keys[i]] = p_joint_i_to_name[keys[i]];
	}
}
```

**Comment by angad-k** [comment]
I'd like to work on this.

**Comment by angad-k** [comment]
Can I work on this? If yes, then could you tell me when is this function called so that I can test it.

**Comment by fire** [comment]
Do you have vscode setup? GLTFSkin is the class and set_joint_i_to_name is the function name. If you want, you can join rocketchat and the onboarding channel.

**Comment by angad-k** [comment]
Yeah cool. What I was asking is when exactly is this function called when using godot so that I can test whether it's working correctly after making the changes.

**Comment by fire** [comment]
1. Create a new gd script in tools mode.
1. Create a PackedSceneGLTF.
1. Call import_gltf_scene.
1. Get GLTFState
2. Call get_skins
3. Get one skin from the array of Skins returned
4. Call set_joint_i_to_name

**Comment by angad-k** [comment]
okay thanks! I'll try this and get back to you

**Comment by angad-k** [comment]
I have opened the PR with the change but haven't been able to test it. I tried it on a gltf model I quickly made and exported in blender but since it didn't have any skins couldn't test it. Would be great if you gave a model to test it on. 
The gdscript code (can't call set_joints_i_to_name since y.get_skins returns an empty array) : 
```var x = PackedSceneGLTF.new()
var y = GLTFState.new()
var z = x.import_gltf_scene("res://ball.gltf", 0, 1000.0, y)
print("skins" + str(y.get_skins()))```

**Comment by fire** [comment]
See if any from here satisfy that. https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0

**Comment by angad-k** [comment]
https://github.com/godotengine/godot/pull/45955#issuecomment-778806561
