### ISSUE TITLE
KinematicBody2D (Player) gets stuck between two blocks (they acts like the ground) if another KinematicBody2D stands on that Body

### ISSUE THREAD

**Issue by Sv1nnet** [godotengine/godot#45374]
Didn't find any similar issue, so

**Godot version:**
v3.2.3.stable.mono.official
v3.2.3.stable.official

**OS/device including version:**
Windows 10 Pro

**Issue description:**
I move a player (KinematicBody2D with rectangle shape) via MoveAndSlide. Gravity is always applied (like in real life).
And what I consider as a bug:
1) when I move a player horizontally on the ground his Y position slitghly changes. When the player moves from one ground block to another his Y position changes even more.
2) this leads to critical bug for gameplay - if Player_2 stands on Player_1 then Player_1 can't move if he stands (or stopped moving) between two blocks. It works the same way if blocks overlap each other or just placed side by side. Looks like it's something with processing collisions.
Demostration https://youtu.be/mzaVSvEHuVk

Discussion on forum
https://godotforums.org/discussion/25234/moveandslide-moves-the-body-with-redundant-vertical-bias/p1

**Steps to reproduce:**
1. You have to have v3.2.3 (with C# support if you download C# project archive (I use v3.2.3.stable.mono.official));
2. Open the project from archive
3. Launch Main.tscn
4. Use keys: A, W, D to controll Player_1, and arrows LEFT, RIGHT, UP to controll Player_2
5. Move Player_1 between block
6. Jump by Player_2 onto Player_1
7. Try to move Player_1

You can see positions and velocities of the player on the screen. Velocity with is passed into MoveAndSlide, position which is before invoke MoveAndSlide.
Player.cs controlls the players.

**Minimal reproduction project:**
[C# Movement_bug_reproduction.zip](https://github.com/godotengine/godot/files/5858936/Movement_bug_reproduction.zip)
[GDScript Movement_bug_reproduction_GDS.zip](https://github.com/godotengine/godot/files/5860130/Movement_bug_reproduction_GDS.zip)

Upd: in GDScript situation even worse - the bottom player can't move at all if he steps on second ground block;

**Comment by Calinou** [comment]
@Sv1nnet Could you create a minimal reproduction project written in GDScript? I don't think this bug is Mono-specific.

**Comment by Sv1nnet** [comment]
> @Sv1nnet Could you create a minimal reproduction project written in GDScript, please? I don't think this bug is Mono-specific.

I don't think so either but I don't know GDScript so it will take some time

**Comment by Sv1nnet** [comment]
Update: added archive with GDScript project

**Comment by madmiraal** [comment]
Fixed in 3.2.4-beta6.
