### ISSUE TITLE
GDNative C++ bindings build failed.

### ISSUE THREAD

**Issue by RevolNoom** [godotengine/godot#45392]
**Godot version:** 4.0.dev.custom_build.8d4698db3

**OS/device including version:** Ubuntu 20.04 LTS, Dell Inspiron 3580

**Issue description:**
Building with `scons platform=linux generate_bindings=yes use_custom_api_file=yes custom_api_file=../api.json -j4` results in these errors: 
[custom_api.txt](https://github.com/godotengine/godot/files/5860433/custom_api.txt)
Deleting the equal signs does not work. They are automatically re-inserted to the same place when scons is called again.

Building with `scons platform=linux generate_bindings=yes` like in the docs say generates this different error:
[no_custom_api.txt](https://github.com/godotengine/godot/files/5860436/no_custom_api.txt)

**Steps to reproduce:**
Following the steps in the doc: 
https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-cpp-example.html

**Minimal reproduction project:**
[gdnative_cpp_example.zip](https://github.com/godotengine/godot/files/5860445/gdnative_cpp_example.zip)

**Comment by RevolNoom** [comment]
I'm sorry. I think I opened an issue on the wrong repository. I'm heading to godot-cpp right now.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-cpp/issues/494.
