### ISSUE TITLE
ScrollContainer doesn't follow the carret in a LineEdit

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#45397]
**Godot version:**
3.2.3

**OS/device including version:**
Linux Mint (5.4.0-60-generic), GLES3

**Issue description:**
The carret of a `LineEdit` within a `ScrollContainer` (as a direct or indirect child) isn't followed when the scroll container's `follow_focus` is set to true.

**Steps to reproduce:**
Create a `ScrollContainer`, add a `LineEdit` in it with `expand_to_text_length` to true (or change the `rect_min_size`) then launch the scene and fill the `LineEdit` until it goes out of the screen, the `ScrollContainer` doesn't follow.

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/5860977/bug.zip)

**Comment by KoBeWi** [comment]
This is somewhat expected. Caret is an internal thing of LineEdit, it doesn't affect focus. You could workaround this by setting the scroll in a script, based on caret position.

**Comment by linkpy** [comment]
Bumping this up. So this issue is the intended behaviour? If it is feel free to close this issue.

**Comment by KoBeWi** [comment]
Yeah there is no way to fix it reasonably without adding class-specific hacks. What could (maybe) make sense is adding a scroll bar to LineEdit. But LineEdit already has some scrolling capabilities, so it's probably not worth it (and there should be a proposal first).

Closing.
