### ISSUE TITLE
Can't change values of variables in scenes with setters

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#45404]
**Godot version:**

v3.2.3.stable.official

**OS/device including version:**

Windows 10

**Issue description:**
I expected $"Holder".setvar.somevar to be set to 3 but instead it calls the setvar setter making changing somevar to 3 impossible
If this is intentional behavior idk how to do the action I'm trying to do here

**Steps to reproduce:**
put a breakpoint on Node2D.gd on line 4 and step through

**Minimal reproduction project:**
[setter  bug.zip](https://github.com/godotengine/godot/files/5861468/setter.bug.zip)

**Comment by Norrox** [comment]
Can't you do something like this, i think you complicate it to much?  :D
![Skärmbild 2021-01-24 062235](https://user-images.githubusercontent.com/13393087/105621891-9f4a5780-5e0c-11eb-9d1c-1036d6d81961.png)
![Skärmbild 2021-01-24 062000](https://user-images.githubusercontent.com/13393087/105621899-aa9d8300-5e0c-11eb-93e3-3d2f1423df78.png)

**Comment by lukostello** [comment]
thats not remotely similar to what I'm doing. The setvar is what needs the setter and doing so disables me from changing any properties of setvar. You can meet me on the discord if you want to see what it is I am doing in my game and how this translates

**Comment by aaronfranke** [comment]
This is a GDScript-specific issue, and it occurs on both 3.2 and the master branch. Master test project: [setterbug4.zip](https://github.com/godotengine/godot/files/5870044/setterbug4.zip)

The same code does work properly in C# even though it's broken in GDScript. Here is a 3.2 C# project: [setterbug-godot-cs.zip](https://github.com/godotengine/godot/files/5870110/setterbug-godot-cs.zip)


Also, to make the problem clearer, here's a pure C# test made in .NET Core: [45404-dotnet.zip](https://github.com/godotengine/godot/files/5870051/45404-dotnet.zip)

**Comment by lukostello** [comment]
@vnen I'm supposed to tag you and ask if this is taken care of for 4.0

**Comment by lukostello** [comment]
Just tested this in 3.3 and it works so I'm fairly certain you can close this

**Comment by lukostello** [comment]
although it does seem weird to me that the setter for setvar is called for when you change the value of somevar, its not really relevant for the issue I was having. There could be a case where you would want to change the value of somevar without calling the setter of setvar. But I'm under the impression that that is somehow impossible from the way things work under the hood.
