### ISSUE TITLE
shader_type particles missing i visualshader editor 4.0

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#45408]
**Godot version:**
d39f6386ce3a7916dbb94fef5ff65e7599e060f0

**OS/device including version:**
windows 10

**Issue description:**
shader_type particles missing i visualshader editor
maybe just not implemented there yet :)

![Skärmbild 2021-01-24 101112](https://user-images.githubusercontent.com/13393087/105625930-f829e800-5e2c-11eb-85a2-950992deb359.png)

**Comment by Chaosus** [comment]
Shader type is named shader mode for visual shaders. You can change it in the inspector:
![image](https://user-images.githubusercontent.com/3036176/105627638-169ddc80-5e49-11eb-9167-d27d29559893.png)
