### ISSUE TITLE
There is no possibility to get reference to object by it's instance id in GDNative c++

### ISSUE THREAD

**Issue by NicholasShatokhin** [godotengine/godot#45417]
In gdscript you can get instance by it's unique id. But there is not the same method at GDNative C++

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-propopsals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal.
