### ISSUE TITLE
import no longer splits .glb animations for rigged characters

### ISSUE THREAD

**Issue by AaronOldenburg** [godotengine/godot#45418]
I've created a glTF animation in Blender that can be split into multiple parts. I split it up in the import settings, as shown in the attached images. However, on reimport, there is still only the main animation. It no longer gives me the new split up animations as before.

I tried with FBX, and splitting up the animation worked fine, but the mesh is kind of a mess (jagged parts sticking out everywhere). I know FBX import is still in beta until 3.2.4, so I'd like to get glTF import working. I had no problem with the first animated model I imported.

Collada also splits animations nicely, but the mesh is a complete mess.

Versions: 
Godot 3.2.3, Linux
Blender 2.91

![import_settings01](https://user-images.githubusercontent.com/10565963/105641394-a8114c80-5e51-11eb-828b-4d5622f2668c.png)
![import_settings02](https://user-images.githubusercontent.com/10565963/105641395-a8114c80-5e51-11eb-9104-2c4579ff606c.png)

**Comment by fire** [comment]
Can you post your sample project or some project that causes the issues? (MRP)

**Comment by AaronOldenburg** [comment]
Sure, here it is, thanks: https://drive.google.com/file/d/1MNAjm8cmf81aIAYPR3F0fZYdj-eKys2m/view?usp=sharing
The main scene is of the imported model. I've changed the import settings to where it should show new, separate clips.

**Comment by fire** [comment]
I think as of 9a64d6b it is still broken. Wanted to check the current state, but in the middle of something.

**Comment by AaronOldenburg** [comment]
I'm currently using a workaround: I'm separating everything out in Actions in Blender so they're already in separate animation clips on import without messing with Godot's import settings.

**Comment by djmaesen** [comment]
same issue 
splitting clips doesnt work in 3.4.2 
animations shouldnt be called "default" in order for splitting to work imo

**Comment by Calinou** [comment]
> Sure, here it is, thanks: [drive.google.com/file/d/1MNAjm8cmf81aIAYPR3F0fZYdj-eKys2m/view?usp=sharing](https://drive.google.com/file/d/1MNAjm8cmf81aIAYPR3F0fZYdj-eKys2m/view?usp=sharing) The main scene is of the imported model. I've changed the import settings to where it should show new, separate clips.

@AaronOldenburg The Google Drive link no longer works, could you upload the project again?

**Comment by lyuma** [comment]
Godot 4.0 now allows assigning splits to any imported animation, so this is no longer an issue for Godot 4.

I'll keep this assigned to the 3.x milestone in case a contributor comes along to fix it, but we don't have any active development resources to dedicate to the 3.x import pipeline

**Comment by lawnjelly** [comment]
Do let us know if #65711 has fixed this, if so we can close this issue (the PR is a little vague as to whether this is a fix). :+1:

**Comment by aaronfranke** [comment]
Given the lack of response from @AaronOldenburg and the fact that a PR has been made to likely fix this issue, I'm closing this issue as assumed fixed.

If this is still a problem, please upload a minimal reproduction project. The Google Drive link from before no longer works.

**Comment by AaronOldenburg** [comment]
I'm sorry for the lack of response. I've been importing files created in Blender with multiple animations just fine since 4.0, so your fix must have worked.
