### ISSUE TITLE
erroneous timer Timeout error on new project

### ISSUE THREAD

**Issue by samtsejerome** [godotengine/godot#45415]
I created a deliberately simple project intended to test exporting to ios, but found a different problem this time!

when I tried to run the simplistic project the output pane fills with errors saying "Error calling method from signal 'timeout': node:timerTimeout" (screenshot attached)

however there are no timer nodes in the project at all!!?
I'm running godot 3.2.3  Official download  on macos  catalina 10.15.6
I'm going to attach the simple project in question ( in case you can reproduce it)

![image](https://user-images.githubusercontent.com/68197715/105638287-c420e800-5e69-11eb-9e91-f17082f9b25e.png)

[csharpexport2.zip](https://github.com/godotengine/godot/files/5862792/csharpexport2.zip)

**Comment by Calinou** [comment]
@samtsejerome Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
