### ISSUE TITLE
3.2.4 beta 6 FBX UV Texture Issue

### ISSUE THREAD

**Issue by xMakerx** [godotengine/godot#45423]
# Rewritten FBX Albedo Texture Bug Report
**Godot version:** 3.2.4.beta6.mono
**OS/device including version:** Windows 10 Pro 64-bit
NVIDIA GeForce RTX 2060 SUPER version: 27.21.14.5671. Driver model: WDDM 2.7
Issue is reproduceable in GLES3 and GLES2.

**Issue description:** Exporting FBX files from Maya 2020 using the 2020 FBX exporter sometimes results in stretched/choppy albedo texture issues in 3.2.4.beta6. This issue doesn't exist in 3.2.3 stable, and must relate to the FBX rewrite.
![texturecomparison](https://user-images.githubusercontent.com/8694578/105642284-e2c9b380-5e56-11eb-999b-3894d763c344.png)

**NOTE:** Ignore the differing hand textures. Focus on the circled area.

## Steps to reproduce

**DOWNLOAD THE PROVIDED ZIP FILE TO REPRODUCE LOCALLY!*

### *Prepare the Model in **Maya 2020** for Exporting*
1. Open a New Scene in Maya 2020 and drag and drop the Maya Binary file into the editor.
2. Select all 3 *transform* nodes in the Outliner. *The nodes that begin with the suitA_zero* prefix.
3. Go to Windows > General Editors > Namespace Editor. Select "suitA_zero" and hit Delete. Hit "Merge with Parent" and close the dialog. This removes the "suitA_zero" prefix.
4. Go to Edit > Delete All By Type > Non-Deformer History.

### *Export the Model*
1. With all 3 *transform* nodes selected, go to File > Export Selection. 
2. Select "FBX export" as the type. If that option isn't provided, make sure the *fbxmaya.mll* plugin is loaded inside of the plug-in manager.
3. Use the following settings:
![mayasettings](https://user-images.githubusercontent.com/8694578/105642592-97b0a000-5e58-11eb-9703-33aee163c1f7.png)

### *Import the Model into Godot*
1. Open and/or create a new project.
2. Drop in the exported fbx model and its materials.
3. Double-click and hit "Open Anyway"
4. View the model's albedo texture issues.

## Reproduction Demo/ZIP
[FBX Demo.zip](https://github.com/godotengine/godot/files/5863117/FBX.Demo.zip)

**Comment by Calinou** [comment]
cc @RevoluPowered

**Comment by xMakerx** [comment]
I'd also like to make a note that this bug doesn't only occur with models that use skeletons and have skins. Regular meshes with an albedo texture show this issue as well. Messing around with texture import settings doesn't alleviate the problem either. Clearing the skin on the individual meshes on the model just ruins the meshes entirely, so that isn't a workaround. I can't go back to the last stable release either because there are bugs with FBX animations in that version.

**Comment by likeich** [comment]
I think I'm having a similar issue with assets from Synty Studios. They also use Maya.

Character without texture:
![image](https://user-images.githubusercontent.com/57882701/106165826-7f42cd00-6159-11eb-8bd8-25b52a1e76b2.png)

Character with broken texture:
![image](https://user-images.githubusercontent.com/57882701/106165922-9d103200-6159-11eb-96fa-26ba60b51940.png)

What it should look like:
![People_01_1024x1024@2x](https://user-images.githubusercontent.com/57882701/106166038-c03ae180-6159-11eb-9079-7acbe5f9bc96.png)

**Comment by RevoluPowered** [comment]
I'll take a look into this when I can.

**Comment by RevoluPowered** [comment]
> I think I'm having a similar issue with assets from Synty Studios. They also use Maya.
> 
> Character without texture:
> ![image](https://user-images.githubusercontent.com/57882701/106165826-7f42cd00-6159-11eb-8bd8-25b52a1e76b2.png)
> 
> Character with broken texture:
> ![image](https://user-images.githubusercontent.com/57882701/106165922-9d103200-6159-11eb-96fa-26ba60b51940.png)
> 
> What it should look like:
> ![People_01_1024x1024@2x](https://user-images.githubusercontent.com/57882701/106166038-c03ae180-6159-11eb-9079-7acbe5f9bc96.png)
> 
> I can't share the asset for testing because it's a paid-for item.

Hi, thanks for saying you're having the problem too but I will need to actually be certain that the issue is identical.

Since you can't share the paid for asset I would highly recommend sending me the log output of your project with verbose debugging enabled. Once you have verbose debugging enabled, reimport the file and send me the log from the output window of Godot, if you want your comment also to be looked into but ideally please put them in a separate ticket.

You can do this by running:
1. godot with the ./godot --path ./yourprojecpath --verbose
2. then go to the output window, click on clear.
3. reimport the file which is broken.

For the asset which is provided above in the original issue no such log needs provided since I can open the source asset.

**Comment by RevoluPowered** [comment]
A third option is to send me the rig privately to gordon@gordonite.tech. I won't share the asset it will just be used to check compatibility and for the actual problem and won't be shared with any third parties.

**Comment by xMakerx** [comment]
@RevoluPowered Would you like me to send you more Maya models with this issue or do you get the gist?

**Comment by RevoluPowered** [comment]
@xMakerx this should be okay, but if you have a simpler model that has the same problem the time to debug the issue and fix it tends to be lower.

**Comment by ricardoalcantara** [comment]
@RevoluPowered I have this same issue with Synty Store and I e-mailed you with the model and texture for testing purpose.

**Comment by xMakerx** [comment]
@RevoluPowered Any updates on how a fix is progressing? Some models look dear awful because of the texture issue.

**Comment by RevoluPowered** [comment]
I have bisected the problem it's caused by commit #8ffad0d8bda78acc24e63b8a80811399a017b9b2

I will submit a patch today :)

**Comment by RevoluPowered** [comment]
File in issue is fixed
![image](https://user-images.githubusercontent.com/748770/107403349-e9198a00-6afc-11eb-8066-c9894c81e660.png)

**Comment by RevoluPowered** [comment]
It was a bug introduced when I was adding color indexing, but it's now fixed.

**Comment by RevoluPowered** [comment]
other file is fixed too
![image](https://user-images.githubusercontent.com/748770/107404195-ee2b0900-6afd-11eb-94be-e810945302bb.png)

**Comment by xMakerx** [comment]
Awesome! Thank you so much!

**Comment by RevoluPowered** [comment]
added UV to title so other people can see the UV's have been fixed again.

**Comment by xMakerx** [comment]
With the merged PR into the 3.2 branch that resolves this bug, I'm closing this. If someone else should have another texture issue relating to the rewrite in the future, it'll be up to them to open up a new issue with their own demonstrations and context.

_**NOTE: I advise anyone using Godot 3.2.4 RC 1 and below to use the glTF/glB format for their models to get intended behavior unless they know how to build from the source.**_

## Alternatives for users of 3.2.4 RC 1 and below
At the time of this writing Blender 2.9.12 can import FBX and export glTF. You can also export glTF directly from Maya using the [Maya2glTF](https://github.com/iimachines/Maya2glTF) plug-in.
