### ISSUE TITLE
iOS export is confusing around handling of orientation (configurable both in project settings and export preset)

### ISSUE THREAD

**Issue by samtsejerome** [godotengine/godot#45422]
**Godot version:**
3.2.3 Mono official build.

**OS/device including version:**
macbook Pro running catalina 10.15,6

**Issue description:**
have tried with several simple projects and the .ipa isn'tcreated (see issue 45421)
but when running the xcode project produced the graphics in the start scene are displayed sideways

see screenshots:
project in editor:
<img width="400" alt="editor-sshot" src="https://user-images.githubusercontent.com/68197715/105642085-71522b00-5e7f-11eb-8f94-454726724cd8.png">

same project in iphone simulator:
<img width="379" alt="orientation-sshot" src="https://user-images.githubusercontent.com/68197715/105642100-8d55cc80-5e7f-11eb-81a1-faff1c9eaf6a.png">

steps to reproduce: 
1. create a simple project  with a viewport that should  fit any modern  iphone display.
2. select export... from the project menu.
3. select the ios(Runnable) preset
4. enter a valid team id, and bundle id
5. select the  export path to a location outside of the project.
6. select all the required icons, and screens as per the documentation.
7. click the export Project button, enter an ipa filename and click save.
8. open the project in xcode.

expected results:
images displayed in the viewport should  look as they do when running in godot

actual results:
ithe entire viewport  isrotated  ro

tated 90 degrees

**Minimal reproduction project:**

[csharptest_project3.zip](https://github.com/godotengine/godot/files/5863087/csharptest_project3.zip)

**Comment by Calinou** [comment]
You need to set the orientation to **Portrait** in the Project Settings, as landscape orientation is used by default.

**Comment by samtsejerome** [comment]
its probably worth mentioning that here:
https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_ios.html

?

**Comment by samtsejerome** [comment]
i did a quick retry setting the orientation to portrait, but then got an error! (screenshot attached)

<img width="821" alt="exporterror-sshot" src="https://user-images.githubusercontent.com/68197715/105642882-6bab1400-5e84-11eb-8b1b-d09f16364e2e.png">

**Comment by naithar** [comment]
MRP project export is fixed by adding icons and LauchScreen images as described in https://github.com/godotengine/godot/issues/45421#issuecomment-769919492

Incorrect orientation is fixed by selecting correct orientation in `Project Settings->Display->Window->Handheld->Orientation` right now you have `landscape` value, so that's what iOS project is using.
It can also be fixed by selecting required orientations on export screen, but the one selected in `Project Settings` has more priority and should be also selected correctly.

**Comment by neikeq** [comment]
I don't think this is specific to Mono/C# projects. Can any one confirm?

**Comment by naithar** [comment]
> 
> 
> I don't think this is specific to Mono/C# projects. Can any one confirm?

It's not. The reason for this issue is the incorrect orientation in project and export settings.

**Comment by akien-mga** [comment]
Should we remove the parameters from the export preset, and improve documentation? I think something similar was done for Android.

**Comment by naithar** [comment]
If we can get access to `ProjectSettings::get_singleton()->get("display/window/handheld/orientation")` inside export preset code, it should be pretty simple. As far as I can tell that's exactly what Android does.

**Comment by Calinou** [comment]
The screen orientation has been defined as a string for all this time. For 4.0, I think it's time to move to an enum :slightly_smiling_face: 

We'll need a different PR to fix this in the `3.x` branch, as we need to keep the string there to preserve compatibility with existing projects. (Nothing major needs to be changed by the users, but people may still be surprised to see their project revert to the default orientation after upgrading.)
