### ISSUE TITLE
FileDialog translation

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot#45429]
**Godot version:**  3.2.3 stable

**OS/device including version:**  windows 8.1 64bit

**Issue description:**

I have Godot in german  and added an FileDialog to the scene. If it is visible it shows a picture with german text but if you let it popup run the game it is in english. It happens also if I set the TranslationServer local to german.

**Steps to reproduce:**
Set language to german and add a FileDialog.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Godot doesn't bundle translations for built-in nodes in running projects. You need to supply translations for the English strings in your own translation files.

**Comment by Gamemap** [comment]
Can you tell me which keywords these are?

**Comment by Gamemap** [comment]
I found this: https://github.com/godotengine/godot/blob/master/editor/translations/de.po
I can translate words like "Path:" but how do I add for example  "Create Folder"? (with space)
It isn't working for me if I have:

```
keys, de
Create Folder, Ordner erstellen
```

Maybe you can tell me.

Thank you
Gamemap
