### ISSUE TITLE
BakedLightmap crash on bake 3.2.4 beta 6

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot#45431]
**Godot version:**
3.2.4 beta 6

**OS/device including version:**
Win 64 GLES3

**Issue description:**
Trying to bake a scene using the new light mapper, and it crashes with the following error in terminal:
```
Embree error: you have to wait for spawned subtasks
terminate called after throwing an instance of 'std::runtime_error'
  what():  you have to wait for spawned subtasks
```

**Steps to reproduce:**
Open my scene that used the old light mapper, Select the node, hit "Bake Lightmap"

Godot either hangs forever, or outright crashes.

**Minimal reproduction project:**
I'm working on it. My project is fairly large:
https://github.com/FugitiveTheGame/Fugitive3D

I'm trying to see if I can repro with something smaller.

**Comment by akien-mga** [comment]
Likely a duplicate of #45097, Embree doesn't like MinGW-GCC :|

**Comment by akien-mga** [comment]
Can you test either build from https://github.com/godotengine/godot/issues/45097#issuecomment-767102593 to see if it solves the issue? If so that would confirm it as a duplicate of #45097, and that that issue finally got fixed :tada:

**Comment by Wavesonics** [comment]
Yup! The build you linked to doesn't crash, and the light maps bake correctly, and look great!
