### ISSUE TITLE
3.2.4.beta6 graph minimap reacts to clicks even when disabled

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#45439]
**Godot version:**

3.2.4.beta6.mono.official

**OS/device including version:**

Win10

**Issue description:**

The new minimap in graph editors (animation blendtree in my example) still reacts to clicks even when it's disabled (the clickable area seems to stay):

![jumkNKF2I3](https://user-images.githubusercontent.com/8841352/105670923-26b5ca80-5ee2-11eb-9b40-75bd5d9d6cd2.gif)

Also, i'd like to request a small outline around it, so it doesn't blend into the background when using the light editor theme

**Comment by Flavelius** [comment]
There's still an issue with clicking renamable fields or dragging node connections behind the hidden minimap
![jkd5I9UPoj](https://user-images.githubusercontent.com/8841352/109471431-080e9a80-7a71-11eb-8ab1-df364e5e85f9.gif)

**Comment by pycbouh** [comment]
@Flavelius Are you sure it's minimap related? Connection dots on `GraphNode`s are finicky and sometimes miss events.

**Comment by Flavelius** [comment]
Yes, that's why in the gif you can see it working okay when dragged to the left (outside that area) and as mentioned, even the textfield doesn't react to clicks. I'll open a new one.
