### ISSUE TITLE
AnimationNodeTransition does not visually update upon changing input count or input names

### ISSUE THREAD

**Issue by PistolRcks** [godotengine/godot#45437]
**Godot version:**

v3.2.3-stable

**OS/device including version:**

Manjaro Linux, running kernel `5.9.1-1-rt19-MANJARO` (64-bit), using KDE with Plasma version `5.20.4` in X11.

Using an Nvidia GeForce GTX 1060 6GB with driver version 455.45.01.

Performed in 2D mode, using GLES3.

**Issue description:**

Upon updating an Transition node's "Input Count" property or any input of the Transition node's "Name" property within an AnimationNodeBlendTree will not visually update the number of inputs or the names of the inputs until another node is added to the AnimationNodeBlendTree. 

Closing the editor (that is, quitting to the project list or closing the program entirely) and reopening the project also visually updates the Transition node. Closing the scene and reopening it does not update the Transition node.

Deleting the node and then undoing the action will also update the Transition node.

Deleting the parent AnimationTree and then undoing the action does not update the Transition node.

**Steps to reproduce:**
1. Within an AnimationNodeBlendTree, place a Transition node.
2. Update the "Input Count" parameter and/or the "Name" parameter of any input of the Transition node.
3. Place any other node within the AnimationNodeBlendTree to update the Transition node, OR close and reopen the project in its entirety, OR delete the Transition node and undo the action.

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/5864192/example.zip)

**Comment by Calinou** [comment]
This is probably due to a missed `change_notify()` call in one of the setters or inspector tools.

**Comment by Cartogy** [comment]
I would like to try and implement the fix.

**Comment by Calinou** [comment]
@Cartogy Sure, go ahead :slightly_smiling_face: 

Look for instances of `change_notify(` in the codebase. This will help you understand how it should be used.

**Comment by Cartogy** [comment]
This issue is not only for AnimationNodeTransition but for others such as AnimationNodeAnimation, as I tried using: *_change_notify("input_count")* in **AnimationNodeTransition::set_enabled_inputs(...)** .

In **AnimationNodeAnimation::set_animation** there is a *_change_notify("animation")* called but the field is not updated until you add another node. Just like what happens with the AnimationNodeTransition.

I've been trying to see how the tree gets updated once adding a new node, but so far I don't know how the tree actually updates the nodes inside the blend tree. I looked into **AnimationNodeBlendTree::add_node** and commented out: *emit_changed()* and *emit_signal("tree_changed")* to see if this would stop updating the nodes in the editor, but it somehow still updates the nodes.

I also tried commenting out *_change_notify()* in **AnimationTree::_update_properties**, but still the nodes in the editor change once adding a new node.

I may be missing something and need some help in figuring out how the blend nodes get updated when adding a new node.

**Comment by Cahlien** [comment]
Hey, Cartogy.  

It looks to me like AnimationNodeBlendTreeEditor::_update_graph() is the function that is being used to redraw the AnimationNodeBlendTree graph and update the data of the items displayed there.  

Typing text in the inspector fields triggers EditorInspector::_property_changed(), but doesn't trigger AnimationNodeBlendTreeEditor::_update_graph().

**Comment by Cartogy** [comment]
Thanks for helping, Cahlien!

After looking in toe AnimationNodeBlendTreeEditor::_update_graph, I'm starting to think the main issue is that the function _change_notify() for some reason is not registered when called in the AnimationNodeBlendTree.

**Comment by Cartogy** [comment]
After debugging at bit more, I discovered that the _update_graph() does not update the blend tree editor. The blend tree editor shows the changes when the function **OS_X11::run()** is called. Specifically after  **3607: Main::iteration()** is called.

**Comment by Calinou** [comment]
> The blend tree editor shows the changes when the function OS_X11::run() is called. Specifically after 3607: Main::iteration() is called.

These are the two first steps of the backtrace, which don't help us isolate the source of this bug.

**Comment by Cartogy** [comment]
Just realized that when dragging the node, the node in the blend tree does not update when **_update_graph()** is called. Only when adding a node.

**Comment by Cartogy** [comment]
I was wrong. The **AnimationNodeBlendTreeEditor::_update_graph** does update the nodes and shows its states.
The loop responsible is this specific one: https://github.com/godotengine/godot/blob/d7aea6ff6c54466dba51b75de5942154fbffe75d/editor/plugins/animation_blend_tree_editor_plugin.cpp#L149

**Comment by Cartogy** [comment]
I added **_change_notify("input_count")** based on the propertie's name: https://github.com/godotengine/godot/blob/28e36dc7b99afe4adb8edfbd2a052ae5de303109/scene/animation/animation_blend_tree.cpp#L831 after *_update_inputs* in :https://github.com/godotengine/godot/blob/28e36dc7b99afe4adb8edfbd2a052ae5de303109/scene/animation/animation_blend_tree.cpp#L691 
and it does not update the blend tree. I noticed that **change_notify("animation")** for NodeAnimation  https://github.com/godotengine/godot/blob/28e36dc7b99afe4adb8edfbd2a052ae5de303109/scene/animation/animation_blend_tree.cpp#L37 
also does not update the field in the blend tree.

**Comment by snougo** [comment]
recently I got this issue too when I using transition node, a bit of annoying, specially when you have a lot of this kind node, hope can be fixed
