### ISSUE TITLE
BakedLightmap not working with CSG nodes 3.2.4 beta 6

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot#45433]
**Godot version:**
3.2.4 beta 6

**OS/device including version:**
win64 gles3

**Issue description:**
I'm trying to create a minimal reproduction project for another issue, but have possibly run into a different bug. Or I might not be understanding how this is supposed to work.

I want to use the new BakedLightmap node with CSG geometry. So I create a few CSG nodes, and on those nodes I enabled `Use in baked lightmap` and `Generate lightmaps`.

Then I insert some lights, and a `BakedLightmap` node that contains the CSG nodes in it's extents.

When I hit bake I get the following error:
```No meshes to bake. Make sure they contain an UV2 channel and that the 'Bake Light' flag is on.```

**Steps to reproduce:**
Try to bake a lightmap with only CSG nodes for geometry.

**Minimal reproduction project:**
[lmtest.zip](https://github.com/godotengine/godot/files/5863579/lmtest.zip)

**Comment by Calinou** [comment]
I don't think BakedLightmap ever worked with CSG nodes. The issue is that CSG nodes have no way to bake UV2 in the first place…

**Comment by Wavesonics** [comment]
oh got ya, ok then, we can just close this. Thanks for clearing that up!
