### ISSUE TITLE
get_fetched_method_unknown_params: Condition "!methods_fetched" is true. Returned: __null

### ISSUE THREAD

**Issue by MagiusCHE** [godotengine/godot#45441]
**Godot version:**
3.2.3.stable.mono

**OS/device including version:**
Linux Manjaro - OpenGL ES 3.0 Renderer: GeForce GTX 980/PCIe/SSE2

**Issue description:**
After 8 days of research in forum/community and here i couldnt figure out how to go out of this problem. I just need to know what this exception means.

Calling `AddChild(xxx.Instance())` cause this assert exception if the combination of "container" is in a "certain" status (after _ready). 

**Steps to reproduce:**
```
public bool AddChild_Now = false;
public override void _Process(float delta)
{
    if (AddChild_Now) // if this varibale is setted to true AFTER _ready of this node the error happends.
    {
        AddChild_Now = false;
        var instance = ((PackedScene)ResourceLoader.Load("res://assets/ACErr.tscn")).Instance();
        AddChild(instance); // <----------------- EXCEPTION
        Log("AddChield TEST");
    }
}
```
```
E 0:00:01.988   get_fetched_method_unknown_params: Condition "!methods_fetched" is true. Returned: __null
  <Sorgente C++>modules/mono/mono_gd/gd_mono_class.cpp:264 @ get_fetched_method_unknown_params()
  <Analisi dello stack>:0 @ void Godot.NativeCalls.godot_icall_2_420(IntPtr , IntPtr , IntPtr , Boolean )()
                Node.cs:525 @ void Godot.Node.AddChild(Godot.Node , Boolean )()
                LocalWorldWrapper.cs:31 @ void LocalWorldWrapper._Process(Single )()
```

**Minimal reproduction project:**
I cant reproduce it on other clean project but it happends only on my complex one.
If you really need it i can share my entire project.

The question is: what means this error?

Thx in advance, and sorry for my poor english.

**Comment by MagiusCHE** [comment]
Hi again. After 2 days i found how to move forward. I tried to detail my progress below. 

The C# class attached to the **child** was:
```
public class IGChunkWrapper : SpatialWrapper
{
...
]
```
where `SpatialWrapper` is another class of mine like that:
```
public class SpatialWrapper : Spatial
{
...
}
```
With these 2 classes the exception appears no matter what.
But... if i change the class name from `IGChunkWrapper` to `IGChunkWrapperFAKE` (and file from `IGChunkWrapper.cs` to `IGChunkWrapperFAKE.cs`) strangely **all** starts to work correctly!!!!

Just to clarify: if i revert back the name from `IGChunkWrapperFAKE` to `IGChunkWrapper` the exception appears again.

I have no clue about this behaviour.

**Comment by Calinou** [comment]
@MagiusCHE Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
