### ISSUE TITLE
`Color.from_hsv()` is no longer available in `master` due to core binding changes

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#45450]
**Godot version:** Git https://github.com/godotengine/godot/commit/161c4be9d21f4368e7c8c99b3ea2175c02963ee0

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 460.32.03)

**Issue description:**

```
SCRIPT ERROR: Parse Error: Cannot find property "from_hsv" on base "Color".
          at: GDScript::reload (res://Node2D.gd:6)
SCRIPT ERROR: Parse Error: Function "from_hsv()" not found in base Color.
          at: GDScript::reload (res://Node2D.gd:6)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:832)
```

In `3.2`, running the code results in:

```
1,0,0,1
0.45,0.5,0.25,1
```

The `Color.from_hsv()` method isn't exposed anymore in `master`: https://github.com/godotengine/godot/blob/161c4be9d21f4368e7c8c99b3ea2175c02963ee0/core/variant/variant_call.cpp#L1149-L1150

**Steps to reproduce:**

```gdscript
extends Node2D

func _ready():
	print(Color(1, 0, 0))
	var color := Color()
	print(color.from_hsv(0.2, 0.5, 0.5))  # Error.
```

**Minimal reproduction project:** [test_color_from_hsv.zip](https://github.com/godotengine/godot/files/5867667/test_color_from_hsv.zip)

**Comment by Bhu1-V** [comment]
hello @Calinou Can u please explain me what `bind_method()` does In 
[godot/core/variant/variant_call.cpp](https://github.com/godotengine/godot/blob/161c4be9d21f4368e7c8c99b3ea2175c02963ee0/core/variant/variant_call.cpp#L1149-L1150) 
and also I can't Understand why Color is Immutable.

**Comment by Calinou** [comment]
@Bhu1-V Sorry, I don't understand the cause of the regression either.

**Comment by Bhu1-V** [comment]
I'm trying to make a constructor of type Color(r,g,b,a, bool is_hsv 
[anything other than zero takes hsv value. but this value defaults to zero so always takes as **rgb values** but when the last argument is true acts as **hsv values**]
 ). is this useful 🤔

**Comment by Bhu1-V** [comment]
@Calinou Is it a good idea to make a temporary fix or find what caused this regression in the first place and fix it..??🤔

**Comment by Calinou** [comment]
> Is it a good idea to make a temporary fix or find what caused this regression in the first place and fix it..??thinking

The regression is caused by a Variant core refactoring that was done in the `master` branch by reduz a few months ago. Since he's working on the renderer right now, I'd prefer if we didn't bother him about this just yet :slightly_smiling_face:

**Comment by akien-mga** [comment]
Note that's not a very easy issue to solve for a new contributor as it requires some design decision on how we want to expose such functionality going further. We can't have static methods yet, so this one is a bit tricky and probably requires a good amount of experience to find a good solution.

I don't want to discourage you from working on this but it's worth noting :)
There are simpler issues with the `junior job` label which you can maybe work on: https://github.com/godotengine/godot/labels/junior%20job

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/43311.
