### ISSUE TITLE
GDscript overwriting does not works

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4545]
**Operating system or device:**
Godot 2.0.2 win64 official release

**Issue description** (what happened, and what was expected):
When you click on the "Edit/create the Node Script" button into Scene panel, there is a "Create Script for Node" dialog box which appears.
When you click the ".." path button, an other dialog box appears.
When you select a script that already exists, a confirmation box ask you if you want to overwrite it.
If you reply "OK", the previous "Create Script for Node" dialog box refuses to overwrite it.

**Steps to reproduce:**
![bug_0_0](https://cloud.githubusercontent.com/assets/9801802/15012984/07ab588a-11fd-11e6-821d-a04e5afcb1d8.png)
![bug_0_1](https://cloud.githubusercontent.com/assets/9801802/15012988/0aee4ebc-11fd-11e6-95e0-8967621be6a6.png)
![bug_0_2](https://cloud.githubusercontent.com/assets/9801802/15012989/0d95bde4-11fd-11e6-8aa4-6ad0252d2e65.png)
![bug_0_3](https://cloud.githubusercontent.com/assets/9801802/15012992/101b89ae-11fd-11e6-8dcd-e3f0231ec2f6.png)
![bug_0_4](https://cloud.githubusercontent.com/assets/9801802/15012995/12bc4edc-11fd-11e6-9721-af24774b2023.png)

**Link to minimal example project** (optional but very welcome):

**Comment by slapin** [comment]
Well, this is quite dangerous path, to many people will destroy their scripts if that is allowed.
And also knowledge about setting existing script to node is not properly shared,
which will make this situation even more dangerous. And no, people will never read dialogue messages. Maybe they will learn after a few deleted files, but before that they will come here and rant
at you.

**Comment by akien-mga** [comment]
We're not babysitters, overwriting should overwrite, and that's it. We don't have to cripple features in case users are silly and overwrite files they need to keep. Any file manager allows overwriting files after confirming a dialog.

**Comment by neikeq** [comment]
Although I agree with @akien-mga, I think in this case it's not supposed to allow overwriting scripts. Otherwise the _File Exists_ error wouldn't exist.

**Comment by SuperUserNameMan** [comment]
@neikeq : it asked me wether i wanted to overwrite a script that i selected on purpose. I replied yes. So, it should overwrite it.
Else, what's the purpose of asking me if i wanted to overwrite it ?

**Comment by neikeq** [comment]
That's probably a problem with _FileDialog_. I think currently there is no way to tell it not to show that message in save mode.

**Comment by vnen** [comment]
The fix was reverted. Quoting @reduz from https://github.com/godotengine/godot/commit/17fbf473fdd12f0a9a351521256d5c34880cb427#commitcomment-17926196:

> I suppose what is needed in this specific case is an option in
EditorFileDialog to directly not allow the user from picking an existing
file
