### ISSUE TITLE
Duplicating AnimatedSprite2D shows error: There is no animation with name 'default'

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#45459]
**Godot version:**
3.2.4.beta.custom_build. 2d904127d

**Issue description:**
This code:
```
func _ready() -> void:
	var a = AnimatedSprite.new()
	a.duplicate(0)
```
shows error
```
ERROR: set_animation: There is no animation with name 'default'.
   At: scene/2d/animated_sprite.cpp:651.
```

![Zrzut ekranu z 2021-01-25 21-42-14](https://user-images.githubusercontent.com/41945903/105763565-3969e700-5f56-11eb-809d-8864fbcae758.png)

**Comment by Szesan** [comment]
If anyone else runs into this issue:

I got the error after deleting an animation, and although I didn't use that specific animation anywhere in the code, that was the last item selected in the GUI. So to make the error disappear, just go into the scene, select animated sprite then select another existing animation. 

Btw It's still a bug and it is still present in 3.3.2.

**Comment by L4Vo5** [comment]
As of #64155, this happens on AnimatedSprite3D as well

**Comment by KoBeWi** [comment]
Does not happen in 4.0.
