### ISSUE TITLE
Godot 3.2.3 mono crashes as on launch (SIGILL)

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#45468]
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10 Pro 64 bit

**Issue description:**

Godot doesn't run at all
```
Microsoft Windows [Version 10.0.19042.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Shadowblitz16>cd desktop

C:\Users\Shadowblitz16\Desktop>"Godot 3.2.3".lnk
Godot Engine v3.2.3.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 650/PCIe/SSE2

Mono: Log file is: 'C:\Users\Shadowblitz16\AppData\Roaming/Godot/mono/mono_logs/2021_01_25 18.36.28 (3336).txt'
ERROR: Failed to load one of the prebuilt API assemblies.
   At: modules/mono/mono_gd/gd_mono.cpp:930

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGILL while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Managed Stacktrace:
=================================================================
=================================================================

C:\Users\Shadowblitz16\Desktop>
```

**Steps to reproduce:**
1. Download godot mono 3.2.3 64 bit
2. Download and install mono 64 bit
3. Run Godot.

**Minimal reproduction project:**

I can't even get to the project screen.

**Comment by akien-mga** [comment]
Did you move/remove the data folder with the Mono assemblies that comes with the download? Or maybe your `.lnk` doesn't have the working directory properly set to find them.

**Comment by MagiusCHE** [comment]
Try share content of your `"Godot 3.2.3".lnk`.

**Comment by Shadowblitz16** [comment]
this is the what my godot executable folder looks like..
![image](https://user-images.githubusercontent.com/2453707/105944910-17856880-6019-11eb-80a1-2fa3f4c72a31.png)
![image](https://user-images.githubusercontent.com/2453707/105944932-1ce2b300-6019-11eb-974e-511f3108eec3.png)
The shortcut is to the mono exectuable

**Comment by akien-mga** [comment]
That folder was named `GodotSharp` when you unzipped the Mono build. Renaming it makes it impossible for the Godot binary to locate the `GodotSharp` assemblies.
