### ISSUE TITLE
Image.save_png("user://image_name.png") does not save image in reachable location in Android export

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#45467]
**Godot version:**

3.2.3

**OS/device including version:**

Pixel 2, Android 9

**Issue description:**

Tried saving an image in the user directory with Image.save_png(). It didn't work. I enabled read/write to external storage perms and asked the user to grant them (the popup appeared). I printed the error code and it was 0. I went into my files but I don't see anything that looks like the image I saved.

Edit: Found the file with adb, but I'm not sure how to get to it by using my phone. I want the images to be saved in a place that the user can easily access them.

**Steps to reproduce:**
Get the data of the texture of the default icon and save it with Image.save_png().

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/5870977/Test.zip)

**Comment by dalexeev** [comment]
Use the `OS.get_system_dir()` method ([docs](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-system-dir)). `user://` paths don't fit here. On Android, the root user-accessible directory is usually `/storage/emulated/0`.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/39414.

**Comment by ShatReal** [comment]
Okay, so here's how I'm trying to save the image:

### 1 - Save to "user://".

**Result:**
Image is saved to "/data/data/org.godotengine.nameofproject/files/image.png".

**How to access from phone:**
No clue.

### 2 - Save to OS.get_system_dir(OS.SYSTEM_DIR_PICTURES).

**Result:**
```
E 0:00:31.060   save_image: Can't save PNG at path: '/storage/emulated/0/Pictures'.
  <C++ Error>   Condition "err" is true. Returned: err
  <C++ Source>  drivers/png/resource_saver_png.cpp:58 @ save_image()
  <Stack Trace> Global.gd:181 @ save_file()
```

**How to access from phone:**
Pretty sure this isn't an actual path but a representation.

**Comment by ShatReal** [comment]
I have managed to save the image in a reachable location, finally. I eventually ended up creating a new directory recursively at "/sdcard/Android/data/org.godotengine.nameofproject/files/" and saved the image there. It seems to also be deleted automatically when I uninstall the app as well.

**Comment by Calinou** [comment]
Should we make `Image.save_png()` and `Image.save_exr()` create directories recursively if they don't exist?

**Comment by volzhs** [comment]
we have already `Directory.make_dir_recursive(path)`.
I think this issue is about documentation for **"How to save a visible custom file to other apps on Android?"**

**Comment by ShatReal** [comment]
Yeah, that was my issue. I couldn't find an answer to that in the docs.
