### ISSUE TITLE
Editor crashes at opening the project

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#45477]
**Godot version:**
[268f32bad](https://github.com/godotengine/godot/commit/268f32badaa0b8a6843f6f36c1284a41b4d7831d)

**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan

**Issue description:**
Editor crashes after opening any project, even empty one.
<details>
<summary>Error:</summary>

>ERROR: Condition "p_ptr == nullptr" is true.
   at: free_static (core\os\memory.cpp:149)
</details>

Crash appeared somewhere after commit [ad0f1c6](https://github.com/godotengine/godot/commit/ad0f1c66707429b35f368eabb1d581013a1d243d).

**Steps to reproduce:**
Compile the editor with [MinGW](https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.0-11.0.0-8.0.0-r6) and open any project.
Compile parameters: `scons -j24 platform=windows bits=64 use_mingw=yes debug_symbols=no use_lto=yes tools=yes target=release_debug`

**Minimal reproduction project:**
N/A, crashes even on empty project.

**Comment by Torguen** [comment]
This also happens to me in mono occasionally. To solve it I must delete the folder ".mono".
Although perhaps his version is not mono.

**Comment by Xartorx** [comment]
@Torguen no, this is classic version, mono version even fails to compile on MinGW for me.
Also, tried these three ([1](https://github.com/zero9178/GNU-Toolchain-for-Windows/tree/GCC-11), [2](https://github.com/zero9178/GNU-Toolchain-for-Windows/tree/GCC-10), [3](https://github.com/zero9178/GNU-Toolchain-for-Windows/tree/GCC-9)) versions, got the same result.

**Comment by qarmin** [comment]
Can you check if still happens?
I'm almost sure that https://github.com/godotengine/godot/pull/45646 fixes it.

**Comment by Xartorx** [comment]
> Can you check if still happens?
I'm almost sure that #45646 fixes it.

Currently i can't even compile the engine with GCC ([crashes at linking stage](https://gist.github.com/Xartorx/c0293102d23821bf81a4ac499af419c7)) at all, so i'm using LLVM-MinGW instead, which compiles and runs everything OK.

**Comment by KoBeWi** [comment]
Does it still happen in 4.0 alpha7?

**Comment by Xartorx** [comment]
Kinda, can compile with MinGW from MSYS2 with parameters from first post, but editor closes instantly without any error, [here's link](https://www.dropbox.com/s/144g1ss6nyfabs5/godot.zip?dl=0) with compiled (commit d38d05c) editor.

**Comment by KoBeWi** [comment]
And what about official alpha?
Did you try using a debugger?

**Comment by Xartorx** [comment]
Latest official alpha works fine.
And no, i didn't tried to use a debugger.

**Comment by KoBeWi** [comment]
If the official alpha works then it's some build-specific issue.

**Comment by Anutrix** [comment]
Tried making a build with almost same parameters but with [llvm-mingw](https://github.com/mstorsjo/llvm-mingw).
Failed with an error:
```
> scons platform=windows bits=64 use_mingw=yes debug_symbols=no use_lto=yes tools=yes target=release_debug
scons: Reading SConscript files ...
Auto-detected 24 CPU cores available for build parallelism. Using 23 cores by default. You can override it with the -j argument.
Using MinGW, arch x86_64
Building for platform "windows", architecture "x86_64", editor, target "release_debug".
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 96%] Linking Program bin\godot.windows.opt.tools.x86_64.exe ...
[ 98%] =====
[ 98%] clang-14: error: unsupported argument '23' to option 'flto='

=====
[100%] progress_finish(["progress_finish"], [])
[100%] scons: *** [bin\godot.windows.opt.tools.x86_64.exe] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:14.757]
```
The above might be unrelated bug.

So after checking code, I tried replacing `use_mingw=yes` with `use_llvm=yes`.
Failed with another error:
```
> scons platform=windows bits=64 use_llvm=yes debug_symbols=no use_lto=yes tools=yes target=release_debug
scons: Reading SConscript files ...
Auto-detected 24 CPU cores available for build parallelism. Using 23 cores by default. You can override it with the -j argument.
Using MinGW, arch x86_64
Building for platform "windows", architecture "x86_64", editor, target "release_debug".
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 96%] Linking Program bin\godot.windows.opt.tools.x86_64.llvm.exe ...
[100%] progress_finish(["progress_finish"], [])
[100%] =====
ld.lld: error: undefined symbol: thread-local initialization routine for Thread::caller_id
>>> referenced by servers\rendering\rendering_server_default.cpp
>>>               libservers.windows.opt.tools.x86_64.llvm.a(rendering_server_default.windows.opt.tools.x86_64.llvm.o)
>>> referenced by core\io\resource_loader.cpp
>>>               libcore.windows.opt.tools.x86_64.llvm.a(resource_loader.windows.opt.tools.x86_64.llvm.o)
>>> referenced by core\debugger\remote_debugger.cpp
>>>               libcore.windows.opt.tools.x86_64.llvm.a(remote_debugger.windows.opt.tools.x86_64.llvm.o)
>>> referenced 10 more times
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)

=====
scons: *** [bin\godot.windows.opt.tools.x86_64.llvm.exe] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:14.716]
```

Works perfectly without `use_lto=yes`.

**Comment by reduz** [comment]
If possible, please submit at a backtrace of the crash so we can take a look.

**Comment by akien-mga** [comment]
@Anutrix For your build issue, you did need `use_llvm=yes` so that the right LTO config is passed. Then the second build likely fails due to pre-existing build objects being invalid. A build from scratch might work.

Official builds do use LTO, albeit from GCC.

**Comment by Anutrix** [comment]
I tried it on Windows 11 with llvm-mingw with same command as in issue description: `scons -j24 platform=windows bits=64 use_mingw=yes debug_symbols=no use_lto=yes tools=yes target=editor` on `master` build. Only target changed and it compiled fine.
I started and ran a project and it worked too.

Is this still valid in master?

**Comment by akien-mga** [comment]
This issue is a bit too old and broad to be actionable nowadays, it's quite likely that the problem has been fixed long ago.
