### ISSUE TITLE
Mouse focuses away when clicking debugger buttons (step over, step into)

### ISSUE THREAD

**Issue by gxhamster** [godotengine/godot#45473]
**Godot version:**

3.2.2 stable 

**OS/device including version:**

Windows 10

**Issue description:**

When clicking the step over button in the debugger the mouse focuses away from the button after clicking

**Steps to reproduce:**
Any project would do

![godot_debugger_issue 1](https://user-images.githubusercontent.com/49613528/105847923-1dbb1b00-6000-11eb-99f6-da9ad3897778.gif)

**Comment by Zireael07** [comment]
Likely not. Also, Godot is already at 3.2.**3** stable - check if it exhibits the same problem.

**Comment by Torguen** [comment]
I don't understand what you mean exactly, I don't see which buttons you mean in the debugger but that doesn't happen to me, I use version 3.2.4 beta 6 mono on Windows.

**Comment by akien-mga** [comment]
Please fill the issue template completely, we cannot work with so little information.

**Comment by Calinou** [comment]
@gxhamster Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Torguen** [comment]
I couldn't reproduce the problem in v3.5.1.rc1.official [293c3844b].

When I press that button everything happens normally.

**Comment by Calinou** [comment]
On second read, I understand what's going on now. The project is using captured mouse mode (or is warping the mouse cursor somehow), and the old cursor position isn't reverted to when the debugger breaks. I'm not sure if this is actually a bug. It *might* be possible to make the button warp to the button when the debugger breaks, but it would be difficult to get it to work correctly. Also, doing so may be undesired in some cases.

In general, I recommend using keyboard shortcuts if you intend to step repeatedly like this.
