### ISSUE TITLE
issue received when upload app to App Store 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#45478]
**Godot version:**
3.2.4 beta6

**OS/device including version:**

**Issue description:**

after submit to App Store, an email about an issue is received:

ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

That's caused by the methods for push notifications added in beta6 such as:
didReceiveRemoteNotification

My app Do not use push notifications and the push notifications is not checked when export the project.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @naithar

**Comment by naithar** [comment]
@alexzheng this message should be simply a warning so it shouldn't block you from sending an app to review. Do you get this message while uploading the application or when you send an app to the actual review process? I didn't have an issue with updating a project with this feature.

If that's a critical issue for you - enabling `Push Notifications` entitlements in `Capabilities` section should be enough to pass the app store check. It wouldn't force you to do anything related to APNS.

I'll look into a ways to silence this warnings.

**Comment by alexzheng** [comment]
Yes, this is just a warning to info you fix this issue on your next submit.
It happens when uploading the application.

Also there is a waning in Xcode:
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.

I can fix this issue simply by remove these methods add in beta6 for my situation since I do not need push.
But it would be better it can be removed when the Push Notifications is not checked when export.

**Comment by naithar** [comment]
> Yes, this is just a warning to info you fix this issue on your next submit.

Not really, it's just an automatically generated message that comes from source analyzers. But I do understand that it's bothering you. :) 

> 
> I can fix this issue simply by remove these methods add in beta6 for my situation since I do not need push.
> 
> But it would be better it can be removed when the Push Notifications is not checked when export.

Yeah, but the intention for adding a Pluggable App Delegates was to make integration of custom `AppDelegate` code easier, so it wouldn't require you to edit the source code.

I'll look into a ways to conditionally enable the method, hopefully there is a way for it without recompiling the source.

**Comment by alexzheng** [comment]
> I'll look into a ways to conditionally enable the method, hopefully there is a way for it without recompiling the source.

yeah, that's great.

**Comment by alexzheng** [comment]
@naithar
Define these methods in a macro still can not stop the waining email.

**Comment by alexzheng** [comment]
It seems any strings match these methods would trigger that waining.
