### ISSUE TITLE
Godot opening a new instance instead of restarting game

### ISSUE THREAD

**Issue by Warionator** [godotengine/godot#45493]
When I am testing my game and want to restart it, randomly (and quite frequently) instead of reloading the game, it will open a new instance of Godot with the project selection. I was lucky enough to get it on video. It even happened when the game wasn't open so idk

https://user-images.githubusercontent.com/30875003/105942658-a8663f00-602d-11eb-9101-8a1a2e5767ce.mp4

**Comment by volzhs** [comment]
duplicate of #28036

**Comment by KoBeWi** [comment]
Closing as duplicate.
