### ISSUE TITLE
WebXR AR re-localisation fails

### ISSUE THREAD

**Issue by michaelvogt** [godotengine/godot#45504]
**Godot version:**
Godot_v3.2.4-beta6_win64, HTML5 export, custom exporter provided by dsnopek

**OS/device including version:**
Pixel 4, Android 11, Chrome 89 Beta

**Issue description:**
When starting an WebXR immersive-ar session, the initial localisations works. When localisation is lost (by putting a hand in front of the camera or moving the device quickly), relocalisation fails with an exception.

  | blitTexture | @ | index.js:formatted:11516
-- | -- | -- | --
  | _godot_webxr_commit_for_eye | @ | index.js:formatted:11562
  | WebXRInterfaceJS::commit_for_eye(ARVRInterface::Eyes, RID, Rect2 const&) | @ | 04e48562:0x7009d6
  | VisualServerViewport::draw_viewports() | @ | 04e48562:0x72df6b
  | VisualServerRaster::draw(bool, double) | @ | 04e48562:0x738217
  | Main::iteration() | @ | 04e48562:0xb515c2
  | OS_JavaScript::main_loop_iterate() | @ | 04e48562:0x9575b7
  | main_loop_callback() | @ | 04e48562:0x223338
  | runIter | @ | index.js:formatted:4931
  | Browser_mainLoop_runner | @ | index.js:formatted:4861
  | onFrame | @ | index.js:formatted:11431
  | XRRequestFrame (async) |  

Code around exception in index.js
`                gl.enableVertexAttribArray(GodotWebXR.programInfo.attribLocations.vertexPosition);
                gl.activeTexture(gl.TEXTURE0);
                gl.bindTexture(gl.TEXTURE_2D, texture);
                gl.uniform1i(GodotWebXR.programInfo.uniformLocations.uSampler, 0);
                gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);`

**Steps to reproduce:**
Setup a minimal WebXR app with immersive-ar mode (like [here](https://www.snopekgames.com/blog/2020/how-make-vr-game-webxr-godot), setting immersive-ar in place of immersive-vr) and start it in an AR capable browser. 

When starting the AR session shows the camera view correctly. Move the device around a bit, to make sure the AR session can localize correctly. 

Covering the camera with a hand for a view seconds

When uncovering the camera again, camera image is shown for a short while. When relocalisation was established, the screen goes white

**Minimal reproduction project:**

**Comment by dsnopek** [comment]
Thanks for the report! I'm able to reproduce this one.

Here's a little more information I was able to get out of the Chrome console:

```
WebGL: INVALID_OPERATION: bindTexture: attempt to use a deleted object

blitTexture @ index.js:9
_godot_webxr_commit_for_eye @ index.js:9
WebXRInterfaceJS::commit_for_eye(ARVRInterface::Eyes, RID, Rect2 const&)
[...]
```

I think that narrows it down to specifically [this line](https://github.com/godotengine/godot/blob/3.2/modules/webxr/native/library_godot_webxr.js#L175):

```
gl.bindTexture(gl.TEXTURE_2D, texture);
```

So, somehow the texture is getting deleted... That's a pretty good lead to start tracking this down!

**Comment by dsnopek** [comment]
I think I've gotten to the bottom of this!

PR #45514 has a fix, and here's a version of my demo that includes it for testing:

https://bit.ly/godot-webxr-07

**Comment by michaelvogt** [comment]
I get the same error with this version as before, unfortunately.

**Comment by michaelvogt** [comment]
As this fix doesn't fix the problem (for me at least), can this issue be reopened or do I need to create a new issue?

**Comment by akien-mga** [comment]
My bad, I missed this comment before merging.

**Comment by michaelvogt** [comment]
No problem.

**Comment by dsnopek** [comment]
@akien-mga @michaelvogt Sorry, I uploaded the wrong build to my server! I thought I retested that version after I uploaded it, but I guess I didn't. :-( Same fix, but new link:

http://bit.ly/godot-webxr-08

**Comment by michaelvogt** [comment]
Yes, I can confirm that this version works for me 👍
