### ISSUE TITLE
C# tools menu size bug after using "Create C# solution"

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#45526]
**Godot version:**
3.2.4 RC 1

**OS/device including version:**
Linux

**Issue description:**
When creating a new project, you can use Project > Tools > C# > Create C# solution to generate the solution:
![Screenshot_20210128_143406](https://user-images.githubusercontent.com/4701338/106145530-f1c1a600-6175-11eb-9a55-9cade0e93969.png)

After that, if you access the same menu, the "Create C# solution" entry is removed (as it should) but there's a blank space in instead:
![Screenshot_20210128_143058](https://user-images.githubusercontent.com/4701338/106145412-ce96f680-6175-11eb-9a9c-4bad96c2407b.png)

Restarting the editor fixes it so it's really a super low priority nitpick.

**Steps to reproduce:**
See above.

**Minimal reproduction project:**
n/a

**Comment by Bhu1-V** [comment]
I want to work on it..🙂

**Comment by Calinou** [comment]
@Bhu1-V Sure, go ahead :slightly_smiling_face: 

I think PopupMenu was reworked in the `master` branch, so you'll have to open a pull request against the `3.2` branch for this one.

**Comment by Bhu1-V** [comment]
how to get a mono build of 3.2 branch?

**Comment by akien-mga** [comment]
The error says that you built with `mono_glue=no`. Once you've done that, you should generate the Mono glue, and then rebuild with `mono_glue=yes` (or without `mono_glue=no`, which is the same).

See https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html#generate-the-glue

**Comment by Bhu1-V** [comment]
thanks I just didn't have a dev .NET sdk. Installing that fixed...

**Comment by Bhu1-V** [comment]
I am Trying some fix but how to get a mono-build after making changes. Building as shown in Docs is time-consuming.

**Comment by akien-mga** [comment]
If you're not changing the core API of Godot, it should be fine to just rebuild with `mono_glue=yes` and without re-generating the glue.

**Comment by Bhu1-V** [comment]
Hello, actually after a lot of tweaking I found that `Contol::Data.size_cache` is something responsible for the size of the `Popup_Menu`
* `Popup_Menu::remove_item( )` function will only remove item from `Items [Vector]` and mark it as an `data.minimum_size_valid = false;`
* but when it's time to show pop_up there is no where in code where it checks whether  **minumum_size.height < size_cached.height**
* So it doesn't update when we try it next time.
* So I tried to set the size_cached after removing the item to new one, but `Control::set_size( new_size , bool );` function really isn't setting the size_cache it but changing some margin and anchors....
https://github.com/godotengine/godot/blob/eda5f4ea31f36aa8d551007a61faf71521667c12/scene/gui/control.cpp#L1727-L1747

* so I created a new function called `set_size_cached (Size2 new_size)` just sets size and it works fine... when called after removing an item.


#### This would also doesn't alter any previously working code ####

**Comment by Bhu1-V** [comment]
> Hello, actually after a lot of tweaking I found that `Contol::Data.size_cache` is something responsible for the size of the `Popup_Menu`
> 
> * `Popup_Menu::remove_item( )` function will only remove item from `Items [Vector]` and mark it as an `data.minimum_size_valid = false;`
> * but when it's time to show pop_up there is no where in code where it checks whether  **minumum_size.height < size_cached.height**
> * So it doesn't update when we try it next time.
> * So I tried to set the size_cached after removing the item to new one, but `Control::set_size( new_size , bool );` function really isn't setting the size_cache it but changing some margin and anchors....
>   https://github.com/godotengine/godot/blob/eda5f4ea31f36aa8d551007a61faf71521667c12/scene/gui/control.cpp#L1727-L1747
> * so I created a new function called `set_size_cached (Size2 new_size)` just sets size and it works fine... when called after removing an item.
> 
> #### This would also doesn't alter any previously working code

I came to this Solution after I tried calling some different functions and also tried to add the `min_size.height < new_size_cache.height` in `_size_changed( )` but it just altering so many things that were working before...

if I just missed something I'm happy to learn...

**Comment by akien-mga** [comment]
I think you're on the right track! But it might be possible to fix it without adding a new function, did you try to call `minimum_size_changed()` in `PopupMenu` when the item is removed? It should force an update, and update the cached size too.

**Comment by akien-mga** [comment]
BTW, this behavior doesn't seem to be specific to the C# tools menu, it can happen in any PopupMenu. Here's a minimal reproduction project:
[TestPopupMenuRemove.zip](https://github.com/godotengine/godot/files/5898822/TestPopupMenuRemove.zip)

(Press Space to remove items, the popup menu won't be resized.)

That's normal behavior for Controls as they don't shrink to fit their contents in general, but we should decide if that's also the expected behavior for PopupMenu, and if so if there's a convenient way to force an update when we do want it to shrink upon content removal, like here.

**Comment by YeldhamDev** [comment]
@akien-mga Generally, when popups need be shrunk, the size is just set to (1, 1). That happens quite a few times around the code base.

**Comment by akien-mga** [comment]
>  Generally, when popups need be shrunk, the size is just set to (1, 1). That happens quite a few times around the code base.

I see. It's a hack but that makes sense, it would indeed make the `minimum_size_changed()` call properly calculate a new minimum size higher than current size, and thus force updating the current and cached size.

So there are two options:
- Change `PopupMenu::remove_item()` to have it call `set_size(Size(1, 1))` before `minimum_size_changed()` to force recalculating the size when removing items. That *might* be a good change but I'm not sure yet, needs more discussion.
- Add the `set_size(Size(1, 1))` call directly in the Mono editor code which removes the item. That's safer and follows our ["Solutions must be local"](https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local) best practice, so I'd recommend going with that.

We can still discuss in a second step if we want a more systematic fix that removes the need for the `set_size` hack, and we could then remove this hack in the editor code that currently uses it. But that's something that warrants further discussion.

**Comment by KoBeWi** [comment]
IMO adding the `set_size()` "hack" to PopupMenus is fine. You'd always expect that there are no blanks on the list and this perfectly fixes the issue (btw the call should be at the end of `remove_item()` method).

**Comment by Bhu1-V** [comment]
* I should call `minimum_size_changed()` before `set_size( Size2 (1,1) )` otherwise it's just taking  `minimum_cache_size` which doesn't change anything. but `minimum_size_changed ()` forces to calculate min_size again.

* I think calling `set_size((1,1))` is not a hack because even if I calculate the `get_minimum_size( )` and pass it inside the `set_size` internally it will again call `get_minimum_size( )` which is kinda redundant and passing something like (1,1) is best option.
* also Tweaking a bit in https://github.com/godotengine/godot/blob/f351cf1b8d19a6dbdfbe2f15e03709e921fd3c20/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs#L126-L131 I found that I couldn't call set_size( ). so we should try something else for local solution.

**Comment by Bhu1-V** [comment]
@akien-mga what do you say shall i PR with `set_size() ` or there is still room for discussion...

**Comment by akien-mga** [comment]
> I found that I couldn't call set_size( ). so we should try something else for local solution.

In C#, the syntax would be `SetSize()`, or setting the `Size` property directly.

**Comment by Bhu1-V** [comment]
> > I found that I couldn't call set_size( ). so we should try something else for local solution.
> 
> In C#, the syntax would be `SetSize()`, or setting the `Size` property directly.

Yes it's Working with `SetSize(new Vector2(1,1));`

**Comment by Bhu1-V** [comment]
Hello @akien-mga in ur MRP while playing when i change the focus of the game window the popup_menu disappears for me, can u reproduce it...?

**Comment by jonhermansen** [comment]
This issue can no longer be reproduced (tested with master branch, commit 6588a4a29af1621086feac0117d5d4d37af957fd)

The `Project -> Tools -> C#` menu only exposes 1 menu option -- "Create C# solution" and no popup menu items get removed later. Even after generating the C# solution file, the popup menu does not exhibit the issue.

I also tried to replicate the problem documented above by modifying GodotSharpEditor.cs file to create 2 popup menu items, and then to remove the 2nd item after C# solution generation. After the 2nd menu item is removed, the popup menu still looks OK to me:

![Screenshot from 2023-07-22 20-48-44](https://github.com/godotengine/godot/assets/660911/996e6cab-6a04-4e89-a646-f86877a0b468)

I think this issue can be closed.
