### ISSUE TITLE
 How to get the error information of engine crash on Android？

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#45527]
**Godot version:**
2.3.4

**OS/device including version:**
GLES2

**Issue description:**
 How to get the error information of engine crash on Android？ win10 platform runs well and crashes on Android platform

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
