### ISSUE TITLE
No input events for L and R analog triggers in MacOS with Xbox One controller

### ISSUE THREAD

**Issue by avilches** [godotengine/godot#45535]
**Godot version:**
v.3.2.3.stabe.mono.official

**OS/device including version:**
macOS Catalina 10.15.7 (MacBook Pro 2017)

**Issue description:**
I'm trying to detect and print all the input events received from my Xbox One controller (bluetooh). All of them are received ok except the L/R analog triggers.

I'm using this snippet in a PlayerController.cs class. Pretty straightforward (just print the input, no matter what)

```csharp
using Godot;
using System;

public class PlayerController : Node {

public override void _Input(InputEvent @event) {
    if (@event is InputEventJoypadMotion joypadMotion)
    {
        GD.Print("Axis " + joypadMotion.Device + "[" + joypadMotion.Axis + "]:" + joypadMotion.AxisValue+ " "+joypadMotion.IsActionType());

    } else if (@event is InputEventJoypadButton joypadButton)
    {
        GD.Print("Button "+joypadButton.Device + "[" + joypadButton.ButtonIndex + "]:" + joypadButton.Pressed + " " +
                 joypadButton.Pressure);

    }
    else
    {
        GD.Print(@event.Device + "[" + @event.AsText() + "] pressed:" + @event.IsPressed() + " type:" +
                 @event.IsActionType());
    }
}
}
```

**Steps to reproduce:**

Just connect a Xbox One controller and run a scene with a node with the PlayerController attached and press all the buttons

**Results**

I've attached a video with my tests. I've tested the analog L & R triggers almost at the end, just to show that the rest of the buttons works properly in Godot and in gamepad-tester.com site.
![bug-triggers](https://user-images.githubusercontent.com/194074/106168051-25102f00-618e-11eb-865f-cbd1bfe54b46.gif)

EDIT: I've tried the https://github.com/godotengine/godot-demo-projects/tree/master/misc/joypads demo, same result: L/R analog are ignored.

**Comment by snougo** [comment]
I have the same issue when connecting a bluetooh xbox one controller

**Comment by masonkieth** [comment]
Has there been any update to this issue or any potential workarounds found? I've noticed that it affects my iOS builds as well. Only appears to be Xbox controllers, DualShock worked fine.

**Comment by Calinou** [comment]
> Has there been any update to this issue or any potential workarounds found? I've noticed that it affects my iOS builds as well. Only appears to be Xbox controllers, DualShock worked fine.

As far as I know, nobody has founda  solution for this yet.

**Comment by masonkieth** [comment]
> > Has there been any update to this issue or any potential workarounds found? I've noticed that it affects my iOS builds as well. Only appears to be Xbox controllers, DualShock worked fine.
> 
> Which Godot version are you using? As far as I know, nobody has founda solution for this yet.

3.2.3-Stable. Just updated to 3.3 and the issue is still there. I'm developing in GDScript. I'm running on an x86_64 2020 MacPro. I've used Bluetooth and wired connections for the controller and the behavior is the same.

I don't know much about making Native Plugins. I was going to look into that next and see if a plugin could be written to solve this. 

An interesting thing i noticed, the controllers triggers work with several Steam games but the triggers would not register any input with the Gamepad Tester that avilches used. I was using Gamepad Tester in Firefox. I wonder if Mozilla and Godot use the same library for Input and maybe this stems from that?

**Comment by Calinou** [comment]
> I wonder if Mozilla and Godot use the same library for Input and maybe this stems from that?

While Godot uses the crowdsourced [SDL game controller database](https://github.com/gabomdq/SDL_GameControllerDB), Godot uses its own input handling code – it doesn't use SDL.

**Comment by masonkieth** [comment]
Alright. I'll find some time to dig into this. I'm pretty curious and it's kind of important that I get this working too. I'll post if I find anything else.

**Comment by masonkieth** [comment]
I confirmed that the controller I'm having issues with is in the SDL controller database and i verified that the strings are correct per gamepad-tool. 

The following tests are done in a branch of 3.x: 
I think I can confirm that input_default.cpp is not registering events for the triggers. I added the following print_line statements to check. 
```
void InputDefault::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_emulated) {
	
        Ref<InputEvent> a = p_event;
		print_line(vformat("InputEvent as text: %s", a->as_text())); //Nothing printed when cycling the L/R trigger actions
	

       Ref<InputEventJoypadMotion> jm = p_event;
	if (jm.is_valid()) {
		set_joy_axis(jm->get_device(), jm->get_axis(), jm->get_axis_value());
		print_line(vformat("axis: %d, axis value: %f", jm->get_axis(), jm->get_axis_value())); 
        //Nothing printed when cycling the L/R trigger actions

```
I went to joypad_osx.cpp next and this is where I think I'm getting lost. If I print the axis_elements size `joy.axis_elements.size()` I get a size of 4: 0,1 for left joystick and 2,3 for right joystick. If i understand correctly there should be 6 axis elements. 1 additional element for each trigger? 

I'm struggling to understand how the various elements are add to their array/structs.

**Comment by madmiraal** [comment]
> If i understand correctly there should be 6 axis elements. 1 additional element for each trigger?

Depending on the controller, triggers are often buttons. Godot converts these to fake axis events:
https://github.com/godotengine/godot/blob/0b136a8066e10ab8b07188c09b882c275d1c2101/main/input_default.cpp#L723-L728

The controller mapping can confirm whether an axis or a button is mapped to `lefttrigger` and `righttrigger`. For example `lefttrigger:a2` for an axis or `lefttrigger:b6` for a button.

Then, as you suggest, you can confirm that the number of `a`, `b` and `h` elements in the mapping match the `joy.axis_elements.size()`, `joy.button_elements.size()` and `joy.hat_elements.size()` respectively.

**Comment by markmehere** [comment]
Yep I tried Godot 3.3 and 3.3.3rc1 and both have the same issue. I was even going to try a nightly but couldn't get the one I downloaded to run.

My technique was a little different in my tutorial I placed:

```
func _input(event):
	print(event.as_text())
```

This registers all button pushes and axis motion. Press the left or right triggers - you get bupkis (nothing registered at all). The left or right bumpers and pretty much anything else register fine.

Check https://support.xbox.com/en-US/help/hardware-network/controller/xbox-one-wireless-controller for controller button definitions (the bottom and back of the controller).

macOS 10.15.7
XBox One S controller
over Bluetooth

**Comment by Calinou** [comment]
@markmehere https://github.com/godotengine/godot/pull/51117 wasn't cherry-picked to `3.3` yet, but you can try compiling the `3.x` branch from source which includes the pull request I linked.

**Comment by bram-dingelstad** [comment]
OMG! I'm super happy to announce that the nightly version you sent works for my setup/controller!

https://user-images.githubusercontent.com/3514405/130086613-2938c1b4-5f85-4b89-b91f-bc2caec58964.mov

**Comment by Calinou** [comment]
[3.3.3 was released][https://godotengine.org/article/maintenance-release-godot-3-3-3)
 with https://github.com/godotengine/godot/pull/51117 included, so I guess this can be closed :slightly_smiling_face:
