### ISSUE TITLE
GLES2 fullscreen on OSX behaving differently with hiDPI on

### ISSUE THREAD

**Issue by gianmichelemariani** [godotengine/godot#45537]
**Godot version:**
3.2.4rc1

**OS/device including version:**
Macbook Pro 13
GPU: Intel Iris 640
GLES2 

**Issue description:**
When using GLES2 with HiDPI off, the window button to go full screen simply maximises the window without going into full screen.

With HiDPI on the same button produces real full screen (no window decorations or any of the os visible).

NOTE: this happens only with GLES2. With GLES3 the behaviour is the same with both hiDPI on or off (full screen is correct).

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/42085 (same cause).

**Comment by gianmichelemariani** [comment]
Read that one before posting and this is definitely not the same issue. 
I understand how and why HiDpi behaves for screen size, but this is a difference in behaviour of the window button that enables full screen on OSX. Again it happens only in GLES2.

I've recorded a video showing the difference.


https://user-images.githubusercontent.com/46694168/106188052-601a5e80-619e-11eb-9908-2e73fc8b87cb.mov

**Comment by gianmichelemariani** [comment]
Catalina 10.15.7

**Comment by bruvzg** [comment]
Might be fixed by #48527. Try using the editor artifact from PR - https://github.com/godotengine/godot/suites/2675083515/artifacts/58954846

**Comment by gianmichelemariani** [comment]
Awesome! Will let you know as soon as I can test it

**Comment by Calinou** [comment]
@gianmichelemariani Did you find some time to test https://github.com/godotengine/godot/pull/48527? Note that the CI artifacts expired, so you'll have to build the editor from source to test it. See [Testing pull requests](https://docs.godotengine.org/en/stable/community/contributing/testing_pull_requests.html) in the documentation for more information.

**Comment by gianmichelemariani** [comment]
I have tested this on 3.5 beta 1 and it works as expected
