### ISSUE TITLE
In 3D view, holding down Right Click and scrolling the mouse, shows the zoom indicator changing

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#45538]
**Godot version:**
3.2.4.rc1

**OS/device including version:**
Windows 10 64bit

**Issue description:**
In 3D view, holding down Right Click and scrolling the mouse, shows the zoom indicator changing. The zoom indicator should not show up when in that Right Click navigation mode as it is not applicable.
![NVzzgDAzDj](https://user-images.githubusercontent.com/4955051/106185799-3d3a7b00-619b-11eb-91ac-45f48c6513db.gif)

**Steps to reproduce:**
In a 3D project hold down right mouse button and scroll the wheel.

**Minimal reproduction project:**
NA - You can reproduce this in an empty project

**Comment by Calinou** [comment]
It's not the zoom indicator, it's the freelook speed indicator. Notice the different "running person" icon.

**Comment by Arnklit** [comment]
Ah my bad, sorry about that.
