### ISSUE TITLE
Change sorting of tiles in the TileMap palette to be based on ID instead of atlas name

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#45531]
**Godot version:**

3.2.4 beta 6 mono

**OS/device including version:**

win10 64

**Issue description:**

As the title indicates, the alphabetical order in the tile IDs is broken.

![3](https://user-images.githubusercontent.com/19652075/106150907-19b40800-617c-11eb-9d4a-0b6053d0b47b.PNG)

**Steps to reproduce:**
Add some textures to a tilemap node, delete some texture again, add another.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
As I wrote on Discord:

> It's not a bug, alphabetical comparison is done character by character, and `2` comes before `.`. The order would be correct if I renamed `icon.png` to `icon1.png` :)

![Screenshot_20210128_154948](https://user-images.githubusercontent.com/4701338/106154993-7a454400-6180-11eb-9ace-ca52792d36c2.png)

Now, the sorting is done based on the file name, and maybe it would be preferred to have it based on the tile ID. In the above screenshot I created first a tile in `icon1.png` (0), then in `icon2.png` (1), and finally another one in `icon1.png` (2).

**Comment by Torguen** [comment]
Wouldn't it be more appropriate for Godot to sort them by ID number?

**Comment by akien-mga** [comment]
Yes that's an option if that's preferred by most users. I never used TileMap with multiple atlases so it wasn't an issue for me, would be good to hear from other users. It might also be fixed in 4.0 already by @groud's refactor, but we could still change the ordering in `3.2` if there's a consensus.

**Comment by Torguen** [comment]
Well I think it would be the most appropriate because normally the name of the image is something like "cityTileset.png" or "dungeonTileset.png" and the order would be something strange.

**Comment by KoBeWi** [comment]
This is no longer a problem in the new TileMap.

**Comment by groud** [comment]
Closing as this enhancement is not applicable anymore in master.
