### ISSUE TITLE
glTF import process strips most non-alphanumeric characters when generating Nodes

### ISSUE THREAD

**Issue by abaire** [godotengine/godot#45544]
**Godot version:**
3.2.3 (but still exists in master as of today)

**OS/device including version:**
Verified with Windows/x64, macOS/x64

**Issue description:**
Importing a glTF file with node names containing characters other than `a-zA-Z0-9_ -` results in Nodes with those characters removed.

It is expected that any characters that are valid in a Godot Node name should also be valid here. The error message within the editor in 3.2.3 indicates that only `. : @ / " ` are disallowed, though in looking at the importer code in 3.2.3 it looks like `$` could be problematic as it is used as a suffix delimiter and by inspection `#` was found to prevent import hints from being processed as well. 

This is particularly useful for `EditorScenePostImport` processing (my specific usecase is adding `key=value` pairs as hints to facilitate BoneAttachment generation)

**Steps to reproduce:**
Create a glb or gltf file with a node whose name contains interesting characters (e.g., `Test!%^&*`), import into Godot and note 
that the imported node in the scene omits those characters.

This project contains a glb file with a default cube named `Cube!%^&*()=[]WithInterestingCharacters` which is renamed `CubeWithInterestingCharacters` by Godot.

[MinimalReproProject.zip](https://github.com/godotengine/godot/files/5890030/MinimalReproProject.zip)

Not clear if this would be obviated by https://github.com/godotengine/godot-proposals/issues/1823
This is also similar to #43482 which covers the impact bone name sanitization has on users.

**Comment by Shatur95** [comment]
This cause by the following function:
https://github.com/godotengine/godot/blob/dc1ae065578baee102d461353c757ebf2cc5cf8c/editor/import/resource_importer_scene.cpp#L266
Godot preprocesses nodes as some editors add extra characters when exporting. But probably it would be nice to keep names as is.

**Comment by Calinou** [comment]
@Shatur95 This should be addressed by https://github.com/godotengine/godot/pull/45545.

**Comment by akien-mga** [comment]
Fixed by #45545 (not sure why it didn't get closed on merge).
