### ISSUE TITLE
SpotLight doesn't affect programatically spawned objects

### ISSUE THREAD

**Issue by skemps** [godotengine/godot#45543]
**Godot version:**
3.2.4 beta 6

**OS/device including version:**
Linux (64bit), GLES3, Nvidia drivers

**Issue description:**
SpotLight affects objects created in editor but not the ones spawned in code

**Steps to reproduce:**
New project, add camera, spotlight, and a MeshInstance. On button press create new MeshInstance

**Minimal reproduction project:**
https://github.com/skemps/Godot_3.2.4_beta_6_SpotLight.git

**Comment by clayjohn** [comment]
Can you test with BVH disabled in the rendering project settings? 

``project_settings->rendering->quality->spatial_partitioning->use_bvh``

Also, please try with [RC1](https://godotengine.org/article/release-candidate-godot-3-2-4-rc-1) as this may already be fixed by https://github.com/godotengine/godot/pull/45251

**Comment by skemps** [comment]
If I disable BVH then it work correctly.

Also with bvh on if I increase range in editor while running the app it starts working.

**Comment by skemps** [comment]
With RC1 it also works great. Thank you

**Comment by aaronfranke** [comment]
@skemps Can you confirm, with RC1 does it work with BVH enabled, or only when it's disabled?

If the former, you can click the close button on this issue.

**Comment by skemps** [comment]
It works with BHV enabled and disabled. Closing ...

**Comment by skemps** [comment]
I'm reopening the issue. I'm testing using **RC1** version now.

I found the case where when using **BVH** something goes wrong with SpotLights. With BVH disabled everything works OK.

I updated **Minimal reproduction project**:
https://github.com/skemps/Godot_3.2.4_beta_6_SpotLight.git

**Comment by lawnjelly** [comment]
Fixed by #45530.
