### ISSUE TITLE
Size() function on named enum is broken in gdscript 2.0

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#45558]
**Godot version:**
4.0 nightly from calinou website

**OS/device including version:**
windows 10

**Issue description:**
I got the error message:

> "Cannot find value "size in "ENUM_NAME (enum)".

Expected the `ENUM_NAME.size()` method to work like in godot 3.2

**Steps to reproduce:**
Make an enum and try to call .size() method on it

**Minimal reproduction project:**

```
enum ENUM_NAME {
	VALUE_1,
	VALUE_2,
}

func _ready():
        print(ENUM_NAME.size())
```

**Comment by Xrayez** [comment]
This may be due to the way how enums are implemented currently, previously it was just a syntax sugar for `Dictionary`.

**Comment by fossegutten** [comment]
I find it hard to test Godot 4 because of too many issues with GDscript 2.0 at the moment. Is there any documentation for all the Gdscript changes?

**Comment by Calinou** [comment]
> I find it hard to test Godot 4 because of too many issues with GDscript 2.0 at the moment. Is there any documentation for all the Gdscript changes?

See [New GDScript is now merged](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged) and the [GDScript reference](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html) documentation in the docs' `master` branch.

**Comment by flomar** [comment]
On the latest master branch (4.0), stuff like the following is no longer possible either:

```
enum State {
  Foo,
  Bar
}

func check_state(_state):
  if not _state in State.values():
    return
  # Do something...
```

The source of the problem most likely is the fact that enums are no longer dictionaries. And while I could work around most GDScript-related changes without any documentation when porting my projects from 3.x to 4.0, I have no solution for the snippet above: How do I check whether an int (enum) is valid, as in part of the declared enum?

**Comment by vnen** [comment]
Enums are still dictionaries (there's not much way around that without hacking Variant). The only issue here is the type-checker don't see them as dictionaries. An exception needs to be added for those cases.

**Comment by MarianoGnu** [comment]
I have a potential fix for this, i want to check if it is possible to fix more issues with enums toguether before opening a PR:
https://github.com/MarianoGnu/godot/commit/c002136f2e8a1f12324141be8eb95c582d99412d

Also, despite this commit is a "good enough" fix, it could be better, because unlike usual dictionaries, enums are constant/read-only so we could foretell the return types and error when an unknown identifier is used
