### ISSUE TITLE
godot 4.0 and godot 3.2 gdscript performance comparison

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot#45556]
**Godot version:**

godot 4.0: jan 28 build from https://hugo.pro/projects/godot-builds/

godot 3.2: 3.2.4 rc1

**OS/device including version:**

OS: solus
GPU: rx480
backend: GLES3, Vulkan

**Issue description:**

i wrote a simple test for both godot 3.2 and godot 4.0 to see how much faster the new typed gdscript was in godot 4.0, to my suprise godot 4.0 was 5 times slower.

i tried different versions of the code below, in 1 version i used the new packedarrays in godot 4.0, it didnt make any diffrence.
seems to be a bug in gdscript.

here is the code i used:

extends Control

const AMOUNT: int = 100
var counter: float = 0.0
var array_one: Array = []
var array_two: Array = []
var array_three: Array = []

func _ready() -> void:
	set_process(true)

func _process(delta: float) -> void:
	counter += delta
	if counter > 1.0:
		counter = 0.0
		print(test_2())

func test() -> int:
	for i in range(AMOUNT):
		array_one.push_back(randi())
		array_two.push_back(randi())
	var start: int = OS.get_ticks_msec()
	for i in range(AMOUNT):
		array_three.push_back(array_one[i] * array_two[i])
	var stop: int = OS.get_ticks_msec()
	return stop - start

func test_2() -> int:
	var my_array: Array = Array()
	var start: int = OS.get_ticks_msec()
	for i in range(AMOUNT):
		for j in range(AMOUNT):
			my_array.push_front(i * j)
	var stop: int = OS.get_ticks_msec()
	return stop - start

**Steps to reproduce:**

use the code above

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Those builds can't be compared as they're not built with the same options. @Calinou's builds use `target=debug`, and are thus completely un-optimized (because `target=release_debug` is broken in GDScript currently).
Official builds for 3.2.4 RC 1 use different toolchains and are fully optimized: `target=release_debug use_lto=yes`.

To make a meaningful comparison, you'd have to compare two builds made in the exact same conditions (same toolchains, same build options).

**Comment by barbaros83** [comment]
@akien-mga thnx for the info, didnt know this, so a 5 times slower performance is expected in this case ?

**Comment by akien-mga** [comment]
In a debug build versus a release build yes, 5 times performance drop is quite normal.
