### ISSUE TITLE
Export fails when trying to create Temp/Godot/packtmp on windows due to missing path

### ISSUE THREAD

**Issue by Magodra** [godotengine/godot#45560]
**Godot version:**

v3.2.3.stable.official

**OS/device including version:**

Windows

**Issue description:**

**Steps to reproduce:**
Export project fails.
 Cannot create file 'C:\Users\USER\AppData\Local\Temp/Godot/packtmp'.
 editor/project_export.cpp:984 - Failed to export the project for platform 'Windows Desktop'.

Creating the C:\Users\USER\AppData\Local\Temp/Godot/ manually and export again working.

**Minimal reproduction project:**

**Comment by yunylz** [comment]
this still happens on 4.3 macos
