### ISSUE TITLE
A Windows build of my game was identified as a virus

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#45563]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
Game was created and built on Manjaro Linux, problem detected on Windows 10.

**Issue description:**

A friend of mine tried to run my game on Windows, and this is how his OS reacted to his attempt at downloading the game build from Github:

![image](https://user-images.githubusercontent.com/491704/106337721-35113700-6292-11eb-977a-a1473e65220a.png)

`Threat detected: Trojan:Script/Wacatac.B!ml`

**Steps to reproduce:**

1. Download this build of my game: https://github.com/unfa/Sho/releases/download/v0.1.0/Sho_Windows.zip
2. Attempt to run it on Windows

**Minimal reproduction project:**

I have no idea, but the entire source code for the project is available if that's gonna be helpful:
https://github.com/unfa/Sho

**Comment by akien-mga** [comment]
That's a drawback of the "Embed PCK" feature, the data bytes added to the .exe sometimes seem to match footprints of some virus (at least that's my hypothesis), at least until the antivirus provider can review a claim of false positive.

Should work fine if you don't use that feature.

**Comment by unfa** [comment]
I'll try that, thank you.

**Comment by Calinou** [comment]
If you want to be certain that your binary isn't considered a virus, you have to purchase a code signing certificate and use it to sign every Windows release you make. To make matters worse, if you want your binary to be trusted immediately (rather than having a few dozen people bypass a warning), you need to buy a more expensive extended validation certificate (~€500/year).

**Comment by BimDav** [comment]
I just had this problem in 3.5.1, whether I embed the pck or not

**Comment by Calinou** [comment]
> I just had this problem in 3.5.1, whether I embed the pck or not

See my above comment. There is nothing we can do about it – it's something you need to handle on your end using the methods I desribed above. You can try reporting your game as a false positive to antivirus developers (and have your players do that too), but it's usually a uphill battle.

**Comment by Anixias** [comment]
I have this problem using an IV certificate. Windows defender constantly deletes my game on other peoples' computers. Do I have to purchase an extended validation certificate to fix this, or can it be reported to Microsoft as a false positive?

**Comment by Calinou** [comment]
> I have this problem using an IV certificate. Windows defender constantly deletes my game on other peoples' computers. Do I have to purchase an extended validation certificate to fix this, or can it be reported to Microsoft as a false positive?

You need an EV certificate to be considered instantly trusted. You can try reporting your executable as a false positive (and encourage your players to do so), and it may eventually cause your program to no longer be flagged as malicious. You will need to repeat this every time the executable is updated though.

**Comment by dewald-els** [comment]
I just built a game on Windows 11 using Godot 3.5.2 and one of my friends still experienced this issue :(

**Comment by Calinou** [comment]
This is not an issue Godot can resolve, so I'll lock this. See [this comment](https://github.com/godotengine/godot/issues/45563#issuecomment-1439149294) for guidance on what you can do.
