### ISSUE TITLE
CSharp Hash throws index-out-of-bounds exception

### ISSUE THREAD

**Issue by cgbeutler** [godotengine/godot#45567]
**Godot version:**
3.2.3 (though it looks like the code hasn't changed.)

**OS/device including version:**
N/A

**Issue description:**
The current `Hash()` extension method for strings can throw an index out of bounds exception. C# strings are different than C++, as they are not null terminated and can even contain nulls in the middle of them. ( [See official docs](https://docs.microsoft.com/en-us/dotnet/api/system.string?view=net-5.0#strings-and-embedded-null-characters) )  The current hash method seems to scan till it hits null. Maybe it was copied or converted from C++ or something?

https://github.com/godotengine/godot/blob/46de553473b4bea49176fb4316176a5662931160/modules/mono/glue/GodotSharp/GodotSharp/Core/StringExtensions.cs#L467-L477

I don't know how string conversions and things work, so I'm not sure if removing the null scan could break things. At the very least, it seems we may need a length check or something for non-null terminated strings.

**Steps to reproduce:**
Create a string and call the hash extension on it like so:
```coffeescript
"Hello World".Hash();
```
Run the project.
Look in the errors tab in godot to see the exception.

**Minimal reproduction project:**
[StringHashException.zip](https://github.com/godotengine/godot/files/5897272/StringHashException.zip)

**Comment by zaevi** [comment]
When fixing, I found the hash result is different from engine.
Variable and the return value should use UInt32 type to keep consistent.
https://github.com/godotengine/godot/blob/f351cf1b8d19a6dbdfbe2f15e03709e921fd3c20/core/string/ustring.cpp#L2651-L2663
