### ISSUE TITLE
glTF import with wrong orientation

### ISSUE THREAD

**Issue by abgenullt** [godotengine/godot#45578]
**Godot version:**
3.2.4.beta6

**Issue description:**
After you import a .gld or .gltf file, the mesh itself is not oriented correctly but the MeshInstance node is rotated.
So, this is a problem, if you want to use the mesh separately..
It also seems, that this is the only format, this happens.

![image](https://user-images.githubusercontent.com/34768615/106356044-c61cf800-62fc-11eb-9bc0-b5a134d99a72.png)

If the mesh will be imported with the desired orientation, so there is no need to rotate the mesh instance or the scene and you can use them without limitations.

Regards
abgenullt

**Comment by fire** [comment]
Please post this as project we can use to recreate the bug. Or any other thing that can recreate the bug.

My steps would be to compare against https://gltf-viewer.donmccurdy.com/ and the latest blender gltf2 import.

**Comment by abgenullt** [comment]
I'm sorry, I need to test a bit more.
I actually cannot reproduce this with a test mesh, I made myself for this example.
Maybe there is something wrong with my project or the model. I will let you know, if I found it out.
Btw thanks for the link.

**Comment by abgenullt** [comment]
Ok, this was my fault. The model has a rotation and I didn't apply the transform in blender. 
Sometimes it takes so long to find such a simple thing..
