### ISSUE TITLE
Machine-specific shader loop bug

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#45588]
**Godot version:**
3.2.3 stable

**OS/device including version:**
MacBook Pro (Retina, 15-inch, Mid 2015)
macOS Mojave 10.14.5
2.2 GHz Intel Core i7
16 GB 1600 MHz DDR3
Intel Iris Pro 1536 M

**Issue description:**
I'm having an odd issue with shaders where adding to a variable inside a loop doesn't always work as expected. Evidently the issue is specific to my machine, since on discord several others tested the same code and they all got the correct result. I have tested this on 3.2.2, 3.2.3, and now 3.2.4 RC and none of them work. Also no apparent difference between GLES2 and 3.

For example, take this simple shader, which I put on a new sprite in a new scene:

```
shader_type canvas_item;

void fragment() {
    
    float a = 0.0;
    while (a < 1.0) {
        a = a + 0.1; 
    }
	
    COLOR = vec4(a, a, a, 1);
}
```

This should result in a white square, but I get grey:

![Screen Shot 2021-01-29 at 6 11 48 PM](https://user-images.githubusercontent.com/33777501/106346067-37ab6680-6269-11eb-9c86-265c867c6cbc.png)

I noticed that replacing the 0.1 inside the loop with a uniform set to 0.1 gives white as expected:

![Screen Shot 2021-01-29 at 6 13 24 PM](https://user-images.githubusercontent.com/33777501/106346072-43972880-6269-11eb-9129-d9ae10b66bdb.png)

But a const float set to 0.1 gives gray again.

![Screen Shot 2021-01-29 at 6 14 21 PM](https://user-images.githubusercontent.com/33777501/106346077-4b56cd00-6269-11eb-829b-29482c4bc3b7.png)

Just adding an int i and a loop condition for this variable fixes it, even though that shouldn't change anything:

![Screen Shot 2021-01-30 at 8 49 20 AM](https://user-images.githubusercontent.com/33777501/106362596-92c87200-62d8-11eb-8455-0688193b9c6f.png)

Regarding for loops, this works:

![Screen Shot 2021-01-30 at 8 59 15 AM](https://user-images.githubusercontent.com/33777501/106362845-e5eef480-62d9-11eb-948b-ce642a903e05.png)

But this doesn't (condition on a instead of i):

![Screen Shot 2021-01-30 at 8 58 09 AM](https://user-images.githubusercontent.com/33777501/106362847-eb4c3f00-62d9-11eb-9f63-6e93b91ee3f4.png)

The issue seems limited to additions - the other basic operations work fine as far as I've tested.

Is this some sort of driver problem? Is there anything I can do? I realize I'm not running the latest macOS, which might help, but I'm hesitant to update because of issues with other software.

**Steps to reproduce:**
It's machine specific, but to test it just apply the first shader posted above to something.

**Minimal reproduction project:**
[ShaderLoopIssue.zip](https://github.com/godotengine/godot/files/5898397/ShaderLoopIssue.zip)

**Comment by clayjohn** [comment]
Definitely a driver issue if it's not reproducible on other hardware. 

Nothing that Godot does with your shaders could cause that kind of issue. It is almost certainly an issue with the shader compiler in your driver. 

Unfortunately that means you'll just have to find and use workarounds. :/

**Comment by djrain** [comment]
I see :( In that case I suppose I'll update my OS and hope that it works itself out.

Theoretically, if I were to export my game on this machine with such code, would it still run correctly for the end user?

**Comment by clayjohn** [comment]
In theory yes. As long as their machine doesn't have the same driver bug. 

Shaders are compiled when an object is first drawn in a scene. And shader compilers are driver/hardware dependant.

**Comment by djrain** [comment]
Good to know, thank you. I'll close this for now then.
