### ISSUE TITLE
Inconsistent window resize behavior

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#4558]
**Operating system or device:**
Fedora linux (Gnome 3.20)

**Issue description** (what happened, and what was expected):
It is supposed that setting window to non resizable should not let you resize the window, but when using this code weird things happen, sometimes the window resizes and sometimes it doesn't

**Steps to reproduce:**
    OS.set_window_size(Vector2(100, 100))
    OS.set_window_fullscreen(false)
    OS.set_window_resizable(false)
    OS.set_window_fullscreen(true)
    OS.set_window_fullscreen(false)
    OS.set_window_resizable(false)
    OS.set_window_size(Vector2(100, 100))

[window_problems.zip](https://github.com/godotengine/godot/files/250808/window_problems.zip)

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
