### ISSUE TITLE
Assembly info is not applied to Windows binaries on export.

### ISSUE THREAD

**Issue by Topaz-Reality** [godotengine/godot#45599]
**Godot version:**
v3.2.3.stable.mono.official

**OS/device including version:**
Windows 10 Pro - Latest

**Issue description:**
The application information is filled at Export Options for a Windows export, they do not persist. The information gets reset to be the same as the Godot Engine executable. This issue does not happen on an Android export.

**Steps to reproduce:**
- Make a Project.
- On "Windows Desktop" export template, fill out the "Application" section with some info.
- Export for Windows.
- Right Click -> Properties on the EXE.

**Screenshots:**
![image](https://user-images.githubusercontent.com/28973970/106376843-e787ed80-63a9-11eb-8171-fd1a5deb148f.png)
![image](https://user-images.githubusercontent.com/28973970/106376852-f79fcd00-63a9-11eb-9531-f6babe24fca2.png)

**Minimal reproduction project:**
[SomeGame.zip](https://github.com/godotengine/godot/files/5899302/SomeGame.zip)

**Comment by akien-mga** [comment]
You need to configure rcedit as documented here: https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html#changing-the-file-icon

**Comment by Topaz-Reality** [comment]
RCEdit only talks about the icon. Does it also work for this?
It was not required before, what's the reason for this requirement?
Why was not it documented in an easier to read place? Why wasn't it mentioned in the export settings like ADB was?
These are important key questions.

**Comment by Topaz-Reality** [comment]
Tried this, a few issues:

- Everything applied, except for the icon (Yes, it is a .ico file)
- The exe cannot launch. Not in x86 nor in x86_64 when Embedding PCK.
- Yes, I need PCK embedded.

**Comment by Topaz-Reality** [comment]
Update: Icon is now included. However, still cannot execute. This is most likely related to #33466.
Closing this issue.

**Comment by akien-mga** [comment]
RCEdit is needed to modify any of the PE data, this should be clarified in the docs.
And yeah, it doesn't work with embedded PCK. You'll have to modify the export template with RCEdit manually if you want to use Embedded PCK.
