### ISSUE TITLE
Scene is marked dirty/modified when unrelated resources are modified

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#45601]
**Godot version:**

3.2.4.beta6.mono.official

**OS/device including version:**

Win10

**Issue description:**

Whenever a resource is modified while a scene is open, no matter whether the resource is used in the scene or not, the scene get's marked as modified too.

**Steps to reproduce:**
Create and open a scene, modify some unrelated resource, notice the asterisk appear in the scene tab.

**Comment by Calinou** [comment]
Since the editor can't be marked dirty, I believe this is done so that you get an "unsaved changes" warning when exiting the editor. Now that https://github.com/godotengine/godot/pull/32321 was merged, we need to be especially careful about avoiding false negatives.

**Comment by Flavelius** [comment]
If the editor has to keep track of the dirty resources it has to have knowledge of the dirty state; i see no reason why it couldn't include the asterisk in the application title for it like most other software does. Maybe it's more complicated internally, but as communication to the user it would make it clearer than pretending the scene has been changed when it actually hasn't, just as a workaround. And it could still warn about unsaved changes before exiting unrelated to that.
