### ISSUE TITLE
[3.2.4 rc1] Custom Android builds are not signed correctly

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#45606]
**Godot version:**
3.2.4 rc1

**OS/device including version:**
Windows 10
Android build tools: 30.0.1
Gradle: 6.5

**Issue description:**
I tried custom builds with the new `rc1` and when installing the APK with adb i get this error:

```
adb: failed to install D:\Test.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from
/data/app/vmdl623359582.tmp/base.apk: Attempt to get length of null array]
```

The error is the same as in #43580 which i fixed and in this case i used the standard debug keystore, so it's not that. I checked the relevant code in https://github.com/godotengine/godot/blob/3.2/platform/android/export/export.cpp and the signing process there changed quite a bit from last time i looked at it, so i suspect there might be a bug in the new signing process. @m4gr3d 

**Steps to reproduce:**
- Create a new project with `rc1` and setup custom Android builds
- Export a debug or release APK
- Install with `adb install Test.apk`

**Comment by akien-mga** [comment]
You might need to re-generate your debug keystore, see #45341.

**Comment by mbrlabs** [comment]
I created a brand new keystore using Android Studio, but that didn't fix it.

**Comment by m4gr3d** [comment]
@mbrlabs Thanks for reporting the issue. I'll try to reproduce it.
For additional debug info, are you able to use the same keystore within Android Studio?

**Comment by mbrlabs** [comment]
@m4gr3d do you mean if i can use the same keystore to build, sign and install a standard Android App in Android Studio? If so, yes that works without problems.

**Comment by mbrlabs** [comment]
@m4gr3d I'm sorry, false alarm. I made a mistake while updating the gradle scripts (i coulding just copy and paste the files since i customized some of them), so i'm closing this.

**Comment by m4gr3d** [comment]
@mbrlabs Thanks for the update!
We're looking for ways to improve the upgrade process especially for customized gradle build files. I'll ping you for input once we have a proposal ready.
