### ISSUE TITLE
macOS sound stuttering/hiccups on ARM

### ISSUE THREAD

**Issue by naithar** [godotengine/godot#45614]
**Godot version:**
Tested with 3.2.3, 3.2.4 betas and RC1

**OS/device including version:**
M1 MacBook Pro, macOS Big Sur.

**Issue description:**
While using Godot with any sound source (music from web browser, Apple Music etc.), sound sometimes stutter on actions performed inside Godot.
When performing actions that takes some time, like exporting a project or launching a game scene stutter/hiccups are more noticeable and repeats until action is finished.

Launching Godot with `--audio-driver Dummy` helps in fixing this issue.

Could be related to #38154

**Steps to reproduce:**
Launching a game from the editor or exporting a game should be enough. 
Launching editor or selecting a project from project browser sometimes also causes this issue.

**Minimal reproduction project:**
Any project will do, even an empty one.

**Comment by bruvzg** [comment]
Are there any extra filters or virtual audio devices like `BackgroundMusic` installed? I'm always getting heavy audio hiccups with `BackgroundMusic` enabled and any kind of debugger running (but not with Godot editor/projects).

**Comment by naithar** [comment]
No, nothing that I'm aware of - mac is new so, there are basically nothing installed on it. Pretty much the clean install with Xcode, Godot and some command line stuff.

**Comment by Calinou** [comment]
Can you reproduce this with old Godot versions (3.1.2, 3.0.6, 2.1.6)?

**Comment by naithar** [comment]
`2.1.6`, `3.0.0`, `3.1.0` - has the same issue on project being opened, but on running or exporting there is no such problem (or at least it's not that noticeable).
Also for `3.2.4` if project actually plays any audio the hiccup is much less noticeable, but maybe it's just me.

**Comment by naithar** [comment]
Cannot reproduce it on macOS Catalina with Intel based mac.

**Comment by naithar** [comment]
The issue described in #38154 also happens for both Unity and Unreal Engine - `coreaudiod` process CPU usage doesn't drop below 3-4% if any of game engine is running even without any sound source.

But cracking sound/sound stutter issue does not appear to happen for Unity or UE. 
I'll try investigating more, but I think the issue might actually be in M1 mac itself, since Intel based macs work fine.

**Comment by naithar** [comment]
After 2 macOS system updates, this problem seems to be fixed for `arm64` builds.
Build emulated through Rosetta (`x86_64`) still cause stutter, but that too might be driver/system issue.
