### ISSUE TITLE
Ctrl+S does not save resources in *[unsaved] scenes

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#45611]
**Godot version:**
4.0.dev c9413b513fd2fb95e9b71d886e01a04e379bb969

**OS/device including version:**
Windows 10.0.19041.746
Nvidia RTX 2080 Ti driver 452.06

**Issue description:**
Ctrl+S saves resources but only if the current scene can be saved, so either [empty] or a valid scene. (not [unsaved], and not opened .glb files or such things)

 Ctrl+Alt+S (Save All Scenes) always saves resources but does not notify the user of this fact.

Similar to issue 9069, but this problem deals with *all resources* (such as Environment), not just scripts.

**Steps to reproduce:**
1. Create a new project or open existing
2. Double click default_env.tres
3. Expand Sky. Then, in the Sky fleld, click Sky to expand the sky object.
4. In the Sky Material box, create a new PhysicalSky
5. Press Ctrl-S
6. Quit to Project List and reopen.
7. The default_sky.tres was not saved.

**Minimal reproduction project:**
Happens in a new project

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/45601.

**Comment by KoBeWi** [comment]
Can't reproduce in alpha7.
When scene is [empty], the resource is saved correctly.
When scene is [unsaved], you are prompted to save the scene. The resource is saved if you do so and not saved when you cancel.

So I guess the issue is resolved?

**Comment by YuriSizov** [comment]
Closing due to no response. Let me know if it's still reproduceable so I can reopen it.
