### ISSUE TITLE
Quit does not ask to save resources and causes data loss.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#45612]
**Godot version:**
4.0.dev c9413b513fd2fb95e9b71d886e01a04e379bb969

**OS/device including version:**
Windows 10.0.19041.746
Nvidia RTX 2080 Ti driver 452.06

**Issue description:**
When exiting the editor (such as Quit; or Quit to Project List; or the X button on the godot editor), no attempt is made to notify the user of unsaved resources, and in the case that no unsaved scenes are open, no attempt is made to give the user a chance to save their work.

Note that when the current *scene* is unsaved, the editor may pop up a confirmation dialog. However, this dialog has a few problems.
1. When no scenes have unsaved changes, the dialog does not even appear, and the editor is closed instantly.
2. It does not notify the user of the fact that there are unsaved resources in addition to the scene.
3. If the user clicks "Dont Save" in order not to save the scene, the resource changes are discarded.

![image](https://user-images.githubusercontent.com/39946030/106395949-d941cd80-63b9-11eb-978f-c21bc270b22b.png)

Related to issues #45611 and #9069, but this problem is about the lack of confirmation at the moment when data is about to be lost.

One solution would be to notify the user of unsaved resources.
Another solution would be to automatically save them (given that other unrelated actions can sometimes automatically save all resources without notification or confirmation)

**Steps to reproduce:**
1. Create a new project or open existing
2. Double click default_env.tres
3. Expand Sky. Then, in the Sky fleld, click Sky to expand the sky object.
4. In the Sky Material box, create a new PanoramaSky
5. The 3d scene should turn light blue.
6. Quit to Project List and reopen.
7. The default_sky.tres was not saved. The scene is black again.

**Minimal reproduction project:**
Happens in a new project

**Comment by Calinou** [comment]
We could partially fix this by reverting https://github.com/godotengine/godot/pull/32321, but I'd prefer fixing the actual issue. Even if you revert https://github.com/godotengine/godot/pull/32321, the message will still be misleading when exiting the editor.

**Comment by Krish2882005** [comment]
Hi :)
Looking Into It
