### ISSUE TITLE
PhysicalSky is NaN or uninitialized when no directional light in scene

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#45610]
**Godot version:**
4.0.dev c9413b513fd2fb95e9b71d886e01a04e379bb969

**OS/device including version:**
Windows 10.0.19041.746
Nvidia RTX 2080 Ti driver 452.06

**Issue description:**
When I create a physical sky, I expect something sky-like.

Instead, creating a PhysicalSky causes the scene to become pitch black and even transparent objects like the gizmo fail to render. This is because the sky is actually NaN, not black.
![image](https://user-images.githubusercontent.com/39946030/106394940-55d1ad80-63b4-11eb-92c8-34770eac038b.png)

It also seems to be sharing information from other scenes until the editor is restarted, which makes the issue more confusing to diagnose.

**Steps to reproduce:**
1. Create a new project or open existing
2. Double click default_env.tres
3. Expand Sky. Then, in the Sky fleld, click Sky to expand the sky object.
4. In the Sky Material box, create a new PhysicalSky
5. Tada! NaN everywhere.

Sharing data from other scenes:
1. Open another scene.
2. Create a directional light there. Rotate it for fun
3. Go back to the first unnamed scene. Suddenly it's not NaN any more.

**Minimal reproduction project:**
Happens in any project.

**Comment by clayjohn** [comment]
Are you sure it is NaNs? The physical sky is just black unless you add a light. Much like our own sky, the color comes from the sun.

**Comment by lyuma** [comment]
It's NaN if I've never opened another scene. You can tell because the gizmo doesn't blend over the blackness properly:

If I open another scene with a directional light and move back, the skybox shows color in it, despite having no light.

I'd be fine if it is "just black until you add a light" but this should be defined behavior, not random depending on the last scene you had open.

I'll change the bug title to say "uninitialized" instead of NaN because that's the real issue

**Comment by clayjohn** [comment]
I thought I had already added logic to detect if there is a sun or not. But it appears I haven't.

I guess an appropriate fix would be to just wrap the entire fragment function in an ``if`` statement like:

```
if (LIGHT0_ENABLED) {
//everything that is currently in fragment
} else {
COLOR = texture(night_sky, SKY_COORDS).xyz;
}
```

I'll be away from my computer until late tonight, so do you mind trying this fix locally? You can just "convert to shader material" and then copy this into the resulting shader.

**Comment by clayjohn** [comment]
I have tested out on current master and I can't reproduce the issue.

Here is what it looks like for me:
![Screenshot (98)](https://user-images.githubusercontent.com/16521339/106552339-fcf53880-64cb-11eb-97cc-f3d071e2a5c5.png)

So please try out the shader change I suggested above and let me know if it works for you!

**Comment by lyuma** [comment]
Yes, can confirm that fixes the issue. Thanks!

I did notice that if two directional lights are present in the scene, PhysicalSky seems to receive a random directional light, and doesn't support multiple directional lights...

I suspect because of how the inputs are exposed, that properly supporting multiple directional lights in the sky shader would be messy with lots of duplicate code, and that's why not even the built-in sky shaders support multiple directional lights.

In my opinion, It would be more straightforward if lights were an array (or accessor function)... then you'd simply start out with the night sky texture and add the contribution from each light on top. Then, instead of using an if statement around LIGHT0_ENABLED and copying and pasting duplicate code for each directional light, it would be a simple matter of looping through each light and adding its influence...

**Comment by clayjohn** [comment]
> I did notice that if two directional lights are present in the scene, PhysicalSky seems to receive a random directional light, and doesn't support multiple directional lights. 

Please open another bug report with an MRP. 

> I suspect because of how the inputs are exposed, that properly supporting multiple directional lights in the sky shader would be messy with lots of duplicate code, and that's why not even the built-in sky shaders support multiple directional lights.

Supporting multiple lights is easy. Just look at the ProceduralSkyShader which supports up to 4. The reason the PhysicalSkyShader only supports one sun is because earth only has one sun, not because of a technical limitation.

**Comment by elvisish** [comment]
What’s the correct steps for getting PhysicalSky to show anything but black? I’ve tried add a DirectionalLight3D and it’s still black, does it need to be positioned correctly?

**Comment by clayjohn** [comment]
@elvisish It should have an energy above 0 and it should be pointing somewhat downwards

**Comment by elvisish** [comment]
> @elvisish It should have an energy above 0 and it should be pointing somewhat downwards

Thanks, I found it started working as soon as I added a texture2d node to night sky, but I didn't even specify a texture, just added the resource lol
