### ISSUE TITLE
3.2.4 RC1 BVH Light Bug

### ISSUE THREAD

**Issue by NHodgesVFX** [godotengine/godot#45623]
**Godot version:**
3.2.4 RC1

**OS/device including version:**

RTX 2080s, GLES3

**Issue description:**

Spawning lights then freeing them breaks bvh. Once broken lights no longer show. With BVH off everything works as expected. You can spawn and free lights and they will not disappear. 

https://user-images.githubusercontent.com/11403345/106418425-468a4880-6424-11eb-80cc-07d6875eb505.mp4

**Steps to reproduce:**
continuously spawn a bunch of lights then free them after a bit, notice the bvh breaks.

**Minimal reproduction project:**

[BVH_Light_Bug.zip](https://github.com/godotengine/godot/files/5902038/BVH_Light_Bug.zip)

**Comment by clayjohn** [comment]
May already be fixed by https://github.com/godotengine/godot/pull/45530

**Comment by NHodgesVFX** [comment]
fixed by #45530
