### ISSUE TITLE
Cannot document a module without forking Godot

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4562]
I'm writing a module for Godot, but I can't find a way to document it without modifying the global classes.xml or adding icons in tools/editor/icons.
This is impractical because it means I have to fork Godot.
It would be better to allow modules to be self-contained, have their own classes.xml file, icons etc. This way, modules could be versionned truly independently.

**Comment by neikeq** [comment]
I agree. Modules need their own `classes.xml`.

**Comment by akien-mga** [comment]
Fixed by #7310.

**Comment by Zylann** [comment]
Does it also fixes the same issue with the icons?

**Comment by akien-mga** [comment]
What icon?

**Comment by Zylann** [comment]
If the module adds new nodes, resources or whatever that needs new images/icons, for example.

**Comment by akien-mga** [comment]
Yeah that makes sense. Could you open a new issue about that? The above mentioned PR only relates to documentation.

**Comment by Zylann** [comment]
> modifying the global classes.xml or adding icons in tools/editor/icons. ^^
I'll make a more specific one

**Comment by Zylann** [comment]
There is still something strange: when you use `doctool .` as explained in the doc to contribute core documentation, it still includes all classes from my module inside the global `classes.xml`. What happens to those I would have in my module then?
