### ISSUE TITLE
Better defaults for VehicleBody and VehicleWheel nodes

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#45640]
**Godot version:**

v3.2.3.stable.official

**OS/device including version:**

Windows 10

**Issue description:**

Several of the default values for the VehicleBody and VehicleWheel don't make a lot of sense and aren't in agreement with the documentation.

**VehicleBody**:
- `mass`'s default is `40`kg, even though most cars are 1500+ kg

**VehicleWheel**:
- `wheel_friction_slip`'s default is `10.5`; documentation says "It's best to set this to 1.0 when starting out."
- `suspension_travel`'s default is `5.0`; documentation says "try a value between 0.1 and 0.3 depending on the type of car"
- `suspension_stiffness`'s default is `5.88`; documentation says "use a value lower than 50 for an off-road car, a value between 50 and 100 for a race car and try something around 200 for something like a Formula 1 car."

Are these values very off because of the low mass of the car? Either way, I think either the documentation or the defaults should be modified because this really doesn't make much sense.

[VehicleBody Documentation](https://docs.godotengine.org/en/stable/classes/class_vehiclebody.html)
[VehicleWheel Documentation](https://docs.godotengine.org/en/stable/classes/class_vehiclewheel.html)

**Steps to reproduce:**
Create a new VehicleBody or VehicleWheel node

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Changing the defaults should be discussed in a [feature proposal](https://github.com/godotengine/godot-proposals) instead of this repository.

**Comment by LightningAA** [comment]
> Changing the defaults should be discussed in a [feature proposal](https://github.com/godotengine/godot-proposals) instead of this repository, as this repository is now meant to be used for bug reports only.

I wasn't sure because this is an issue but you're right that it's not exactly a bug either. I'll close this open and reopen it on the godot proposals repository.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/2217.
