### ISSUE TITLE
ImageTexture flag "Repeat" has no effect if "Mipmaps" is disabled.

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#4565]
**Operating system or device:**
Windows 10 Pro x64

**Issue description** (what happened, and what was expected):
Choosing only the flag `Repeat` does not make an ImageTexture repeat. Additionally, `Mipmaps` must be checked to make `Repeat` work.

Not sure if that combination makes sense, I don't remember needing to generate mipmaps for getting texture repeat to work in my old engine.

![untitled 1](https://cloud.githubusercontent.com/assets/9631152/15058171/13934b52-131b-11e6-88e5-94e1ccb3c32f.png)
![untitled 3](https://cloud.githubusercontent.com/assets/9631152/15058172/139404d4-131b-11e6-8840-a3642769c215.png)

**Comment by reduz** [comment]
This is not a bug, this is an OPENGL ES 2.0 limitation, as Godot uses this API, this limit is enforced.
