### ISSUE TITLE
Custom User Input in Exported .EXE game doesn't work on Steam or Steam Big Picture Mode

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#4566]
**Operating system or device:**
Windows 10 64-bit

**Issue description** (what happened, and what was expected):
What happened is that I was test running an executable game on the Big Picture Mode in Steam and unfortunately, the joystick controls were not functioning in the game within the Steam Big Picture Mode, hopefully there may be a resolution to make the Godot Engine Executable to be more friendly for steam.

And just for heads up, I was using the Input maps for the Action pressed functions such as UI_Cancel and etc for both buttons and the joystick... However, I was using custom user interface inputs for a local multiplayer Idea.

Also, and additional note which strange enough is that the keyboard still works normally rather than the gamepad support, both the Steam Controller and the Xinput controllers does not work at all... Plus the controls, minus the steam controller works fine outside Big Picture Mode...

**Steps to reproduce:**
Make custom user input mapping that uses the joystick on the gamepad, Export your game to EXE or whatever works, open up Steam and bring in your game as a shortcut using "Add Non-Steam Game to library, Open up Big Picture Mode, go to where you've installed the game and see if you can get the joystick to work...

**Comment by nunodonato** [comment]
tried it in Linux, couldn't reproduce, gamepad still worked fine

**Comment by Hinsbart** [comment]
I couldn't reproduce on windows 10 either. Both, my Steam controller and a wireless 360 pad work flawlessly in Big Picture mode. Tried it with tools and release builds, no difference. InputMap actions also work. Mhh

**Comment by Corruptinator** [comment]
Weird, I guess I am the only one who notices this problem. Meanwhile, I've tried out a different method involving using the get_joy_axis() function, this worked out better for me, but to a warning to all users if you are using custom User Interface mapping for action_pressed()/action_released(), be prepared for a hard realization that it doesn't work within the Steam application but outside instead.

**Comment by Hinsbart** [comment]
Ahh, so you only tried it with joystick axes, not buttons (Buttons should work)? If so, AND you're using the official godot binary( or a build older than 2 weeks), you likely have the bug fixed by #4409.

So, the next release should include this fix :)

**Comment by Corruptinator** [comment]
Sounds good to me. I have been using official builds rather than compiling the source code because it is less of a mess for me to deal with, albeit having to tackle with bugs in the long run...

**Comment by kubecz3k** [comment]
@Corruptinator you don't need to compile Godot to check this, there are unofficial night builds available... Would you mind downloading build from here http://fixnum.org/godot/ and checking if the bug still occurs?

**Comment by Corruptinator** [comment]
Sorry for the non response, but I did find an alternative. for now the gamepad works on the Steam Big Picture mode by using the "Input.Get_Axis()" value input. This way It will be easier to not endure any issues when exporting the Steam Big Picture.
