### ISSUE TITLE
Viewport front/rear view swapped

### ISSUE THREAD

**Issue by MrMinimal** [godotengine/godot#45668]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
Front/rear view in the viewport is swapped.

In this scene
![grafik](https://user-images.githubusercontent.com/8739690/106646772-62116280-658e-11eb-8f74-179360618488.png)
selecting
![grafik](https://user-images.githubusercontent.com/8739690/106646842-7190ab80-658e-11eb-99ff-c22c50f528b9.png)
leads to
![grafik](https://user-images.githubusercontent.com/8739690/106646893-810ff480-658e-11eb-8566-07dafdafac70.png)

**Steps to reproduce:**
1. open the provided demo
2. open the Demo.tscn
3. click on "Perspective"
4. click on "Front View"
5. observe the blue marker disappear
6. click on "Rear View"
7. observe the blue marker appear

**Minimal reproduction project:**
[WrongCamera.zip](https://github.com/godotengine/godot/files/5913674/WrongCamera.zip)

**Comment by MrMinimal** [comment]
Fixed here, opening PR right now:
https://github.com/MrMinimal/godot/commit/f995d6cd17e227492dee14627e9262292c58d6a4

**Comment by Calinou** [comment]
This may be intended. In Godot, the "forward" direction is Z-, not Z+.

**Comment by MrMinimal** [comment]
@Calinou Thanks but then the right and left view don't make too much sense. It's one or the other.

**Comment by ulvido** [comment]
maybe mathematicaly you are right but humanly this is confusing and front/back should be reverted.

**Comment by ulvido** [comment]
> @Calinou Thanks but then the right and left view don't make too much sense. It's one or the other.
maybe mathematicaly you are right but humanly this is confusing and front/back should be reverted.
