### ISSUE TITLE
Theme's property "LineEdit/colors/read_only" doesn't work

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#45673]
**Godot version:** 3.2.3.stable

**OS/device including version:** Windows 10

### Issue description: 

`Theme`'s `LineEdit/colors/read_only` doesn't work, even though it's been generated as default property when using _Create Empty Editor Template_ button.

**Steps to Reproduce:**

add a LineEdit node -> navigate to theme property - right click -> click _New Theme button_ -> click _Edit Theme_ button - click _Create Empty Editor Template_ button -> LineEdit - Colors - Read Only - change this to [Color (1, 0, 0, 1)]

Expected: font color of uneditable LineEdit becomes red.

Result: font color stays the same, some translucent milky color.

or:

`line_edit.theme.set("LineEdit/colors/read_only", Color.red)`, should work and doesn't work.
____
**ALSO:**

`line_edit.set("custom_colors/font_color_uneditable", Color(1,1,0))` should work and works.
`text_edit.set("custom_colors/font_color_readonly", Color(1,1,0))` should work and works.

`line_edit.theme.set("LineEdit/colors/font_color_uneditable", Color.red)` **undocumented and works**.
`text_edit.theme.set("TextEdit/colors/font_color_uneditable", Color.red)` undocumented and does not work.
`text_edit.theme.set("TextEdit/colors/font_color_readonly", Color.red)` undocumented and does not work.

**Proposal that I was too lazy to add to godot-proposal:**

Make `ControlX`'s `custom_*/property_x` work in `Theme` as well. For examples, we have "custom_colors/font_color_readonly" in TextEdit, then Theme's "TextEdit/colors/font_color_readonly" should work too.

In this way we're able to style the whole GUI by changing the theme of one super-parent Control node.

**Comment by pycbouh** [comment]
The proper way to set theme properties is `theme.set_*(name, node_type, value)`. So in case of colors it would be `theme.set_color("read_only", "LineEdit", Color.red)`.

Out of curiosity, what are you trying to achieve? The `read_only` color on `LineEdit` is only defined in the Editor Theme, it doesn't exist in the `LineEdit` control by default and it's not even used in the editor in any way.

**Comment by rambda** [comment]
> The proper way to set theme properties is `theme.set_*(name, node_type, value)`. So in case of colors it would be `theme.set_color("font_color_uneditable", "LineEdit", Color.red)`.
> 
> Out of curiosity, what are you trying to achieve? The `read_only` color on `LineEdit` is only defined in the Editor Theme, it doesn't exist in the `LineEdit` control by default and it's not even used in the editor in any way. It should just be removed, and you need to use `font_color_uneditable` to change the color of an uneditable `LineEdit`.
> 
> > Make ControlX's custom_*/property_x work in Theme as well. For examples, we have "custom_colors/font_color_readonly" in TextEdit, then Theme's "TextEdit/colors/font_color_readonly" should work too.
> > In this way we're able to style the whole GUI by changing the theme of one super-parent Control node.
> 
> That is exactly how it works, though. Properties can be defined on the theme, `theme.set_color("font_color_uneditable", "LineEdit", Color.red)`, or they can be overridden for each individual node, `line_edit.add_color_override("font_color_uneditable", Color.red)`.

I think` theme.set_*(name, node_type, value)` works the same as `theme.set("node_type/colors/name")`, because they're just essentially setting properties in a theme resource.

If we do 
```
theme = Theme.new()
theme.set_color("font_color_readonly", "TextEdit", Color.red)
ResourceSaver.save("res://a.tres", theme)
```
The content of a.tres will be
```
[gd_resource type="Theme" format=2]

[resource]
TextEdit/colors/font_color_readonly = Color( 1, 0, 0, 1 )

```
which is the same as the result of 
```
theme = Theme.new()
theme.set("TextEdit/colors/font_color_readonly", Color.red)
ResourceSaver.save("res://b.tres", theme)
```
___
I double checked the docs, you're right. `LineEdit's font_color_readonly` is not even in the docs and should be removed, and this issue should be close.
___

**But it does have a behaviour that I think is a bug about <ins>TextEdit </ins>(not LineEdit):**

Although `theme.set_color("font_color_uneditable", "LineEdit", Color.red)` works.

`theme.set_color("font_color_readonly", "TextEdit", Color.red)` should work according to the [docs](https://docs.godotengine.org/en/stable/classes/class_textedit.html), but it doesn't work.
