### ISSUE TITLE
GDNative: Issues with nested custom Resources.

### ISSUE THREAD

**Issue by LennyPhoenix** [godotengine/godot#45675]
**Godot version:**
Godot 3.2.3-stable (`godot.windows.opt.tools.64.exe`)

**OS/device including version:**
Microsoft Windows 10 Home (64-bit)
10.0.19041 Build 19041

**Issue description:**
Somewhat related to #45645.
Nested custom GDNative resources (woohoo, these again) are completely broken:
When setting a property for a custom GDNative resource (from the editor, must be a saved resource) to another custom GDNative resource will cause one of two things to happen when loading the resource and attempting to access the property:
- The game will crash, with no error. (Seems to be the more common case)
- The resource will appear as `[Deleted Object]` and attempting to access attributes will result in a crash like above.

**Steps to reproduce:**
- Define two GDNative classes inheriting from `Resource`.
- Add a property to one class with the type `object`.
- Create two resources in the editor, one for each class, ResourceA will have the property, ResourceB will not.
- Assign the property of ResourceA to ResourceB.
- In GDScript:
  - Load ResourceA.
  - Attempt to print the resource's property.

**Minimal reproduction project:**
[Reproduction Project.zip](https://github.com/godotengine/godot/files/5914930/Reproduction.Project.zip)
*Like my last bug report, you will have to compile this yourself, and it comes with a SConstruct file.*

**Comment by sheepandshepherd** [comment]
Resources are reference-counted. In C, you need to call `reference()` whenever you store a pointer to one, and `unreference()` when the pointer is changed. (C++ and the other language bindings do this automatically with their `Ref<Resource>` type.)

Your child resource was getting deleted early because its ref-count drops to 0 when `second_set_child` stores it without calling `reference()`. Adding it fixes the `[Deleted Object]`:

```c
void godot_reference(godot_object *object, Library *p_lib)
{
    static godot_method_bind *bind = NULL;
    if(bind == NULL) bind = p_lib->api->godot_method_bind_get_method("Reference", "reference");
    godot_bool ret;
    p_lib->api->godot_method_bind_ptrcall(bind, object, NULL, &ret);
}

void godot_unreference(godot_object *object, Library *p_lib)
{
    static godot_method_bind *bind = NULL;
    if(bind == NULL) bind = p_lib->api->godot_method_bind_get_method("Reference", "unreference");
    godot_bool ret;
    p_lib->api->godot_method_bind_ptrcall(bind, object, NULL, &ret); // this returns `true` if the reference count is now at zero...
    if(ret) p_lib->api->godot_object_destroy(object); // ...in which case, delete the object
}

GDCALLINGCONV void second_set_child(godot_object *p_instance, Library *p_lib,
                                    Second *p_large,
                                    godot_variant *p_second)
{
    if(p_large->child != NULL) godot_unreference(p_large->child, p_lib);
    p_large->child = p_lib->api->godot_variant_as_object(p_second);
    if(p_large->child != NULL) godot_reference(p_large->child, p_lib);
}
```

`second_constructor` also needs to call `reference()` when it sets `child`.

Note that a Resource placed inside a `godot_variant` already gets its ref-count managed by `godot_variant_new_object`/etc, so you don't need to call `reference()`/`unreference()` when storing in a `godot_variant`. Only `godot_object *` pointers require this.

**Comment by LennyPhoenix** [comment]
Thanks for checking this out and explaining!
I was under the impression that `godot_alloc` tracked memory for `godot_object` pointers for some reason, I'm a little confused how I managed to get this far without encountering any other major issues haha.
I'll try this out when I get back to my PC, and I'll close this issue if it works.
Cheers!

**Comment by LennyPhoenix** [comment]
Works great, thanks again!
