### ISSUE TITLE
WebSocketClient fails to connect, but no error message is shown

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot#45681]
### **Godot version:**
3.2.3 and 3.2.4 RC1

### **OS/device including version:**
Linux 64 bit, both client and server

### Issue description:

**Observed**: Trying to connect to server with `WebSocketClient` using SSL. The connection fails and `_connection_error()` is called on the client. There is **no error message on the console**, both on the server and on the client. As far as I know, it's not possible to get any error message or error code from withing `_connection_error()` programmatically.

In my example code, I keep retrying, and the client tends to connect, sometimes only after 20+ tries. The server uses a certificate from letsencrypt.org.

**Expected**: **An error message indicating what's going wrong.**

### **Steps to reproduce:**
Run the code below in a new project.

### **Minimal reproduction project:**

```
# Attach this script the only node in a new project.
# Tried with Godot 3.2.3 and 3.2.4 RC1.

extends Node

var client := WebSocketClient.new()

func _ready():
    client.connect("connection_established", self, "_connection_established")
    client.connect("connection_error", self, "_connection_error")

    init_network()

func init_network():
    # This server uses certificates from letsencrypt.org.
    # setting client.trusted_ssl_certificate doesn't make any difference
    var url = "wss://vm31500.vps2day.com:5000"
    var err = client.connect_to_url(url)
    print("Connecting to %s (returned error %d)" % [url, err])

func _process(_delta):
    client.poll()

# fails a lot of times... retrying
func _connection_error():
    # what caused the error?
    # no error message or error code available at this point?
    print("connection failed.")
    init_network()

# after several tries (sometimes >20) it eventually connects
func _connection_established(_protocol):
    print("connected.")
    get_tree().quit()

```

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/42210 (possible duplicate?).

**Comment by mrimvo** [comment]
With this issue I wanted to bring to attention that the `connection_failed` signal does not provide any error message, making it impossible to troubleshoot the actual problem I have. Maybe it's a timeout, or a SSL handshake error, or something else. I have no idea, because there is no error message.

I got this connection problem only if connecting to the server which got the letsencrypt.org certificates. Using no secured connection works without any problems, also connecting to servers secured with certificates other than letsencrypt.org

Again, my main intention is to in some way have an error message or even an error code provided with the connection_failed signal.

**Comment by mrimvo** [comment]
I quote @Faless from the linked ticket (#45681)
>  You are getting a disconnect because the client takes too long to do the handshake (timeout is 1 sec during websocket handshake to limit DOS attacks).

This might actually be the very case for my issue. Is there any way to increase that time out to 2 seconds? Because it looks like this handshake taking place between europe and the US actually _does_ take longer than 1s, especially in rush hours.

**Comment by mrimvo** [comment]
I really need this to work for my current project and it's a blocker for me. People essentially can not connect to my server because of the time out during ssl handshake. If they finally succeed, the game is running very well. But the handshake fails constantly.

For Godot 3.2.4, can we have an attribute `ssl_timeout = 1000` on `WebSocketServer`? So I could increase the time out a little bit? It would really help me out.

Thank you for considering.

**Comment by mrimvo** [comment]
In the godot source code, I changed
```
wsl_server.h
#define WSL_SERVER_TIMEOUT 1000 // set to 5000 or something!
```
I went through the pain of recompiling the game engine for my server. After spending a day on this I succeeded and all connectivity problems are gone, peers now always connect!

I had severe and long term problems to connect from EU to US and vice versa, rendering WebSocketServer useless for production use. The chosen Timeout is simply too short. I suggest making `ssl_timeout` a property on `WebSocketServer`.

**Comment by avnerh1** [comment]
Do we have a workaround for this, until it is fixed?
Many of my users fail to connect to the server. This leads to poor user experience, bad reviews, losing users, and so on. It is urgent to find a solution.
Compiling as was suggested above helps but does not solve it fully, and further debugging is not possible due to absence of error code.

**Comment by Calinou** [comment]
> Do we have a workaround for this, until it is fixed?

If increasing the timeout doesn't solve the issue, then we don't know how to fix this.

**Comment by mrimvo** [comment]
For me, increasing the timeout does solve the issue. No connectivity problems anymore since several months. I set the timeout to `10 000` and recompiled the engine.

I agree with @avnerh1 that an error message would be of tremendous help, besides changing the timeout or making it a property of `WebSocketServer`.

**Comment by Calinou** [comment]
I'm working on making WebSocketServer print error messages on its own and adding a `handshake_timeout` property, stay tuned :slightly_smiling_face:

**Comment by Faless** [comment]
Closing via #49964 and  #49966
