### ISSUE TITLE
Tween calculates fraction passed for duration to 0 in `interpolate` method

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#45683]
**Godot version:**

3.2.3.stable

**OS/device including version:**

Windows 10 Home 1909

**Issue description:**

When I passed a fraction as the argument for duration in an `interpolate_property()` function, no tween was executed but instead the value changed immediately, so duration was calculated to 0.

**Steps to reproduce:**
Create a Sprite or so and give it a Tween. In a Script, do an interpolation and pass any fraction as the duration argument.

**Minimal reproduction project:**

[Bug_REPRODUCTION.zip](https://github.com/godotengine/godot/files/5919049/Bug_REPRODUCTION.zip)

**Comment by akien-mga** [comment]
`1/2` is an integer division, and will truncate the result to give an integer -> 0.

If you want a floating point as a result, you should use floating point division, i.e. `1.0 / 2.0`.

**Comment by MaaaxiKing** [comment]
Oh, sorry. Thank you.
