### ISSUE TITLE
[Bullet] collide_shape returns unintuitive/wrong values

### ISSUE THREAD

**Issue by janmagtoast** [godotengine/godot#45680]
![Anmerkung 2021-02-03 113453](https://user-images.githubusercontent.com/63017641/106734948-ebb74380-6613-11eb-9f63-28e3ff14958b.jpg)

**Godot version:**
3.2.3 stable/3.2.4 (tested on multiple versions)

**PhysicsEngine:**
tested in both Godot Physics and Bullet Physics
(This project is in Bullet, bc it's using cyliner-shape)

**Issue description:**
As the title implies, I don't understand what collide_shape returns. Either it's bugged or just really unintuitive.

**Steps to reproduce:**
Use collide_shape and print the returned values.

**Minimal reproduction project:**
[MinimalisticProject.zip](https://github.com/godotengine/godot/files/5917708/MinimalisticProject.zip)

**Comment by pouleyKetchoupp** [comment]
I can confirm returned values are wrong with Bullet. Returned points should be in world space, but Bullet is probably returning them with a different transformation, maybe in the shape's local space.

In Godot Physics they are correct:
<img width=300 src="https://user-images.githubusercontent.com/1075032/108551478-3fc95580-72ad-11eb-884b-17384935f067.png" />
(cylinder is implemented now, and you can get similar results with other shapes)

Documentation could be improved though. Returned points are a list of pairs of contact points. For each pair the first one is in the shape passed in `PhysicsShapeQueryParameters`, second one is in the collided shape from the physics space.

**Comment by theraot** [comment]
I just ran into this. It appears that the first point is in the local space of the body whose shape is passed in PhysicsShapeQueryParameters, and the second point is in the local space of the other body.

**Comment by Funinja** [comment]
Hello! I'm new to the community and would like to try fixing this for my first commit. Can I be assigned this?

**Comment by akien-mga** [comment]
Fixed by #59470.
