### ISSUE TITLE
Unexpected behaviour of CircleShape2D falling onto a LineShape2D

### ISSUE THREAD

**Issue by runapp** [godotengine/godot#45692]
**Godot version:**
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce RTX 3070/PCIe/SSE2

**Issue description:**
Create a floor as StaticBody2D, with LineShape2D as its collisionshape. Add code to instance a RigidBody2D with CircleShape2D as it's collisionshape on the scene, whenever a mouse click occurs. Click randomly several times, and see the balls fall through the floor.
![2021-02-04_00-02-50](https://user-images.githubusercontent.com/6805108/106780663-2e643480-6683-11eb-812e-9f6a6f28fbe6.gif)

**Minimal reproduction project:**
[lineshape2d-test.zip](https://github.com/godotengine/godot/files/5920094/lineshape2d-test.zip)

**Comment by Calinou** [comment]
While this is a bug, remember that LineShape2D represents an infinitely long collision (like PlaneShape in 3D).

**Comment by Xrayez** [comment]
I cannot reproduce in **3.2.4 RC**, fixed by #42532.

![image](https://user-images.githubusercontent.com/17108460/106781750-10321080-6652-11eb-8229-5b8eaacb6d6c.png)

**Comment by runapp** [comment]
@Xrayez I've tested and the results are (obviously) the same. Thank you.

@Calinou Thank you for the reminder. I think LineShape2D is just good for a floor, except it's performance problem?

**Comment by Calinou** [comment]
> Thank you for the reminder. I think LineShape2D is just good for a floor, except it's performance problem?

You can use a wide RectangleShape instead. Don't make it too thin to avoid tunnelling issues – in general, it's best to make your collision shapes as thick as you reasonably can.

**Comment by runapp** [comment]
> 
> 
> > Thank you for the reminder. I think LineShape2D is just good for a floor, except it's performance problem?
> 
> You can use a wide RectangleShape instead. Don't make it too thin to avoid tunnelling issues – in general, it's best to make your collision shapes as thick as you reasonably can.

I see. Now I'm using a thick CollisionPolygon2D to replace multiple LineShape2D(s).
