### ISSUE TITLE
More FileSystem view (improvement) ideas

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#4570]
I feel a bit uncomfortable using the FileSystem view, mostly because it doesn't allow the following:
- Make the tree view also display files inside the folders.

Then I got some more ideas:
- Make only one button to toggle between the new tree and the thumbnail view of the most recently selected folder / folder of the most recently selected file.
- Remove the "Open" button or give it an icon with an arrow; it currently tricks me into believing it's a "Create Folder" button. I bet most people open files with double click anyway.
- Add a "Create Folder" button, which adds a child folder in the currently selected one.
- Add a "Create New Resource" button, which opens the New Resource dialog currently invokable from the Inspector (saving the resource to the current folder after creation?).
- Move the favorite "Up" and "Down" arrows beside the favorite list entries to clean up the toolbar. Maybe even add a remove icon, similar to the AutoLoad list in the project settings.
- Move the "Add / Remove Favorite" button to the right of the address bar; since the thumbnail button got merged with the tree button.
- Make it possible to favor files?

Here's a mock up of the ideas (the previous "Open" button would be a "Create Folder" button...):
![filesystem](https://cloud.githubusercontent.com/assets/9631152/15085138/b881752c-13d8-11e6-99df-8236cc4e0aa7.png)

**Comment by reduz** [comment]
there will be some changes to this soon, which should make it a little
easier.

**Comment by Geequlim** [comment]
How about add a button to open the selected folder in system file explorer?

**Comment by RayKoopa** [comment]
@Geequlim Good idea, was missing that too several times. Since we can't have a context menu yet (I think), it would probably take the last free space of the top toolbar =D

**Comment by reduz** [comment]
Curretly working on that, but a button or option to open current dir on
native explorer sounds pretty good

**Comment by neikeq** [comment]
I would also like the option to open a directory with the file manager, but I think it would be better to wait for context menus.

**Comment by Geequlim** [comment]
@reduz  I think you are working on that now. I have tested the 8b47e26f59ddca57f95dfae5ce807d382957a97e commit and it is really cool!

I also tested `OS.shell_open(str("file://", dirPath)))` on Linux, OSX and Windows, it can open the directory `dirPath` in native explorers. So I think it's the time to add this feature.

By the way, maybe add an option to create new folder should be more convinient.

**Comment by akien-mga** [comment]
See also #2517.

**Comment by reduz** [comment]
you can now view folders and files separatedly if you use full height filesystem dock, more detail on the folders will not be added, so closing this one
