### ISSUE TITLE
The online editor not support high DPI Screen

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#45714]
**Godot version:**
Latest version

**OS/device including version:**
MacOS 10.15.7

**Issue description:**
The editor not support HDPI screens. (I don't had this issue before I think)

<img width="571" alt="Capture d’écran 2021-02-04 à 20 07 47" src="https://user-images.githubusercontent.com/6397893/106952423-6629b580-6731-11eb-87cd-24df5437ebfb.png">

**Steps to reproduce:**
Just start the editor.

**Comment by Calinou** [comment]
This was already reported on the Godot Contributors Chat. Can you test with this URL? https://no-war.fales.me/editor/godot.tools.html

**Comment by fabriceci** [comment]
There is not the issue in the version you linked.

**Comment by Calinou** [comment]
cc @Faless

**Comment by fabriceci** [comment]
seems fixed in the latest build probably by #45921
