### ISSUE TITLE
TextureRegion editor pushes the inspector outside screen

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#45710]
**Godot version:**

2ba66c1

**Issue description:**

Basically horizontal version of #26835 
![ZdIEIKaUYf](https://user-images.githubusercontent.com/2223172/106935029-2952c400-671b-11eb-946e-201d6488d961.gif)

**Steps to reproduce:**
1. Add Sprite2D
2. Click TextureRegion at the bottom

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/45253.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/31133.

**Comment by KoBeWi** [comment]
TextureRegion editor is now a popup, so this is fixed.
