### ISSUE TITLE
Area2d's Monitoring not exposed in Physics2DServer

### ISSUE THREAD

**Issue by CherryPetrichor** [godotengine/godot#45717]
There is no Area_Set_Monitoring() in Physics2DServer, despite there being area_set_monitorable().

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
