### ISSUE TITLE
Convex decomposing failed with CollisionPolygon2D PackedVector2Array size < 3

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#45724]
**Godot version:**
1f7f27e86

**OS/device including version:**
Windows 10 64bits
Nvidia GTX 1060 (driver 461.40)

**Issue description:**
While using CollisionPolygon2D with PackedVector2Array size < 3, editor show an error (not only the warning icon)
>ERROR: Convex decomposing failed!
>   at: decompose_polygon_in_convex (core/math/geometry_2d.cpp:53)

**Steps to reproduce:**
Just add node CollisionPolygon2D

**Minimal reproduction project:**
[bugreport.zip](https://github.com/godotengine/godot/files/5930859/bugreport.zip)

**Comment by TotCac** [comment]
I post a similar issue while ago
https://github.com/godotengine/godot/issues/19558

**Comment by jjmontes** [comment]
With Godot version 3.2.4 RC 3 over Ubuntu 18.04.5 LTS  it also happens

In the attached project you can test. You just have to open the Node2D.tscn scene, select the CollisionShape2D node, and in the node properties, change Shape to ConcavePolygonShape2D or ConvexPolygonShape2D and the editor closes. 

[CollisionBug.zip](https://github.com/godotengine/godot/files/6083918/CollisionBug.zip)

**Comment by pouleyKetchoupp** [comment]
@jjmontes I've fixed `ConvexPolygonShape2D` but I can't reproduce a crash with `ConcavePolygonShape2D`. Could you please confirm this issue affects convex shapes only or let me know the exact repro for concave shapes?

**Comment by Sslaxx** [comment]
Finding this error is occurring in 3.3.3.

**Comment by pouleyKetchoupp** [comment]
@Sslaxx Could you share your setup in a minimal project? It would help finding what case I missed with the last fix.

**Comment by Sslaxx** [comment]
Minimal, afraid not - not my work and I'm unsure of how to separate it. https://github.com/coderman64/flow-engine/tree/working - @coderman64

**Comment by pouleyKetchoupp** [comment]
That helps, thanks! What are the repro steps?

**Comment by Sslaxx** [comment]
For me, the errors happened when attempting to resize the window.

**Comment by pouleyKetchoupp** [comment]
@Sslaxx Given the project assets, it seems these errors could be related to tilemaps, but I wasn't able to reproduce anything. Please open a separate issue with more details if you see it again or can give a bit more details about the context.

**Comment by golddotasksquestions** [comment]
@pouleyKetchoupp 

I cannot confirm this is related to TileMaps. I'm having the same issue and it's very easy for me to replicate it without TileMap:

```
extends Node2D

onready var line = $Line2D
onready var collision_poly = $Area2D/CollisionPolygon2D

func _process(delta):
	if Input.is_action_pressed("LMB"):
		line.add_point(get_global_mouse_position())
	if Input.is_action_just_released("LMB"):
		collision_poly.polygon = line.points
```
![image](https://user-images.githubusercontent.com/47016402/140460274-2ffd0b9c-f192-41ed-b106-12a33aa61bd1.png)

Minimal Reproduction Project:
[convex_polygon_decomposition_bug.zip](https://github.com/godotengine/godot/files/7480678/convex_polygon_decomposition_bug.zip)

**Comment by kleonc** [comment]
@golddotasksquestions Seems like the reason of the convex decomposing failing in your example is the repetition of the same point (which happens when you didn't move mouse between consecutive `_process()` calls while holding LMB).

So even with your code I could draw a concave shape which was decomposed successfully (just have to be fast and precise enough):
![firefox_6I7YzJPBjG](https://user-images.githubusercontent.com/9283098/140515593-7d65033d-0cf5-4c7f-ab78-36dc22201f0a.png)

Disallowing such points should help for now:
```
func _process(delta):
	if Input.is_action_pressed("LMB"):
		var p = get_global_mouse_position()
		if line.get_point_count() == 0 or line.get_point_position(line.get_point_count() - 1) != p:
			line.add_point(p)
	if Input.is_action_just_released("LMB"):
		collision_poly.polygon = line.point
```
It's easy to draw complex shape after such change:
![Godot_v3 4-rc3_win64_n3raoZfoJK](https://user-images.githubusercontent.com/9283098/140518579-52eb2576-9756-45e0-8c46-043a5b7608d9.png)

A proof showing duplicates are the cause (after a delay after releasing LMB removing duplicated points and reassigning them to the `CollisionPolygon2D.polygon` makes convex decomposing not fail):
```
func _process(delta):
	if Input.is_action_pressed("LMB"):
		var p = get_global_mouse_position()
		line.add_point(p)
	if Input.is_action_just_released("LMB"):
		var points = line.points
		line.points = []

		collision_poly.polygon = points

		yield(get_tree().create_timer(0.5), "timeout")

		var i = 0
		for j in range(1, points.size()):
			if points[j - 1] != points[j]:
				points[i] = points[j]
				i += 1
		points.resize(i)
		collision_poly.polygon = points
```
![HdgZX2qq04](https://user-images.githubusercontent.com/9283098/140521670-9a40c421-b08b-49f5-9397-e13a6e2eef5a.gif)

**Comment by golddotasksquestions** [comment]
@kleonc 
Oh wow! What a great find! I would not have figured this out.
Still I think this should be more robust. If they are needed, I think these checks should happen under the hood.

**Comment by SteveSmith16384** [comment]
I'm getting this error when I call opaque_to_polygons() on a bitmap created from a specific png image I have.  I'm using 3.4.2.  It's a polygon with 85 points (i.e. more than 3), and I've checked for duplicate points, but it still happens.

**Comment by Calinou** [comment]
> I'm getting this error when I call opaque_to_polygons() on a bitmap created from a specific png image I have. I'm using 3.4.2. It's a polygon with 85 points (i.e. more than 3), and I've checked for duplicate points, but it still happens.

Please open a new issue with a minimal reproduction project attached.

**Comment by dimkauzh** [comment]
> @pouleyKetchoupp
> 
> I cannot confirm this is related to TileMaps. I'm having the same issue and it's very easy for me to replicate it without TileMap:
> 
> ```
> extends Node2D
> 
> onready var line = $Line2D
> onready var collision_poly = $Area2D/CollisionPolygon2D
> 
> func _process(delta):
> 	if Input.is_action_pressed("LMB"):
> 		line.add_point(get_global_mouse_position())
> 	if Input.is_action_just_released("LMB"):
> 		collision_poly.polygon = line.points
> ```
> 
> ![image](https://user-images.githubusercontent.com/47016402/140460274-2ffd0b9c-f192-41ed-b106-12a33aa61bd1.png)
> 
> Minimal Reproduction Project: [convex_polygon_decomposition_bug.zip](https://github.com/godotengine/godot/files/7480678/convex_polygon_decomposition_bug.zip)

for me too
