### ISSUE TITLE
Vulkan: Registry lookup failed to get layer manifest files on nvidia 1060 gtx

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#45725]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
1f7f27e86

**OS/device including version:**
Windows 10 64bits
Nvidia GTX 1060 (driver 461.40)

**Issue description:**
While starting editor, a warning appear
>Godot Engine v4.0.dev.custom_build.1f7f27e86 - https://godotengine.org
>Using ICU / HarfBuzz / Graphite text server...
>WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
>        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
>        Objects - 1
>                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 191611232
>     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:152)
>Using Vulkan Device #0: NVIDIA - GeForce GTX 1060 6GB

**Steps to reproduce:**
Just start godot editor

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
A quick search led me to this: https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/1010/cant-play-any-game-that-uses-vulkan-on-w7/

**Comment by TotCac** [comment]
I just want to add that I build Godot nearly every days, and this warning just appears some days ago. Don't know if it's a recent commit or Nvidia driver recent update.

**Comment by clayjohn** [comment]
Which version of the Vulkan SDK do you have installed?

**Comment by TotCac** [comment]
Ouch maybe it just has something to do with nvidia....

> PS E:\> vulkaninfo.exe --summary
> WARNING: [Loader Message] Code 0 : ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
> ==========
> VULKANINFO
> ==========
> 
> Vulkan Instance Version: 1.2.162
> 
> 
> Instance Extensions: count = 15
> -------------------------------
> VK_EXT_debug_report                    : extension revision 9
> VK_EXT_debug_utils                     : extension revision 2
> VK_EXT_swapchain_colorspace            : extension revision 4
> VK_KHR_device_group_creation           : extension revision 1
> VK_KHR_display                         : extension revision 23
> VK_KHR_external_fence_capabilities     : extension revision 1
> VK_KHR_external_memory_capabilities    : extension revision 1
> VK_KHR_external_semaphore_capabilities : extension revision 1
> VK_KHR_get_display_properties2         : extension revision 1
> VK_KHR_get_physical_device_properties2 : extension revision 2
> VK_KHR_get_surface_capabilities2       : extension revision 1
> VK_KHR_surface                         : extension revision 25
> VK_KHR_surface_protected_capabilities  : extension revision 1
> VK_KHR_win32_surface                   : extension revision 6
> VK_NV_external_memory_capabilities     : extension revision 1
> 
> Instance Layers: count = 9
> --------------------------
> GalaxyOverlayVkLayer           Galaxy Overlay Vulkan Layer                   1.1.73   version 1
> GalaxyOverlayVkLayer_DEBUG     Galaxy Overlay Vulkan Layer                   1.1.73   version 1
> GalaxyOverlayVkLayer_VERBOSE   Galaxy Overlay Vulkan Layer                   1.1.73   version 1
> VK_LAYER_EOS_Overlay           Vulkan overlay layer for Epic Online Services 1.2.136  version 1
> VK_LAYER_EOS_Overlay           Vulkan overlay layer for Epic Online Services 1.2.136  version 1
> VK_LAYER_NV_optimus            NVIDIA Optimus layer                          1.2.155  version 1
> VK_LAYER_OW_OVERLAY            Overwolf Overlay Layer                        1.1.131  version 1
> VK_LAYER_VALVE_steam_fossilize Steam Pipeline Caching Layer                  1.2.136  version 1
> VK_LAYER_VALVE_steam_overlay   Steam Overlay Layer                           1.2.136  version 1
> 
> Devices:
> ========
> GPU0:
>         apiVersion         = 4202651 (1.2.155)
>         driverVersion      = 1934229504 (0x734a0000)
>         vendorID           = 0x10de
>         deviceID           = 0x1c03
>         deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
>         deviceName         = GeForce GTX 1060 6GB
>         driverID           = DRIVER_ID_NVIDIA_PROPRIETARY
>         driverName         = NVIDIA
>         driverInfo         = 461.40
>         conformanceVersion = 1.2.4.0

**Comment by mahdisml** [comment]
same problem in windows (with nvidia 940m and intelHD)

**Comment by Calinou** [comment]
> same problem in windows (with nvidia 940m and intelHD)

Which NVIDIA driver version do you have installed?

**Comment by mahdisml** [comment]
> 
> 
> > same problem in windows (with nvidia 940m and intelHD)
> 
> Which NVIDIA driver version do you have installed?

461.09
but i got same error with Intel HD 520

**Comment by Wolfe2x7** [comment]
This error prevents me from taking look at 4.0 on my old laptop (on a whim).

Windows 7 Pro 64-bit
i5-6200U with an Intel HD 520, just like **mahdisml**
8GB RAM
VulkanRT 1.2.182 (just installed)
[Intel driver: 15.45.5174](https://www.intel.com/content/www/us/en/download/18799/intel-graphics-driver-for-windows-15-45.html) (just installed)

I found [this Nvidia forum thread](https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/1010/cant-play-any-game-that-uses-vulkan-on-w7/) that might offer a clue. The user **Sora** there offers advice on what Vulkan's entries in the Windows registry should look like. However, the registry on this PC looks correct, as far as I can tell.

Unlike another user in that thread, I think my laptop has a valid Vulkan assignment; before crashing, Godot says: `Using Vulkan Device #0: INTEL - Intel(R) HD Graphics 520`

**Comment by akien-mga** [comment]
@Wolfe2x7 This is just a warning about validation layers, it should not cause any issue. If it crashes for you, that's a different bug (most likely that the Intel drivers for legacy hardware don't support Vulkan well).

**Comment by Chaosus** [comment]
Yeah, it's just annoying warning spam, nothing more - hope it will be fixed after the latest Vulkan loader will be merged.

**Comment by Chaosus** [comment]
Seems like this issue will be fixed when Vulkan runtime has been installed (not SDK). For example: https://sdk.lunarg.com/sdk/download/1.2.182.0/windows/VulkanRT-1.2.182.0-Installer.exe

**Comment by gamergamesz** [comment]
```
Godot Engine v4.0.dev.custom_build.49e7e049a - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1558820022592
     at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:154)
Vulkan API 1.2.170 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 SUPER

17
   At: res://new_script.gd:12:_ready()
ERROR: Attempted to free invalid ID: 0
   at: RenderingDeviceVulkan::_free_internal (drivers\vulkan\rendering_device_vulkan.cpp:8436)
ERROR: Attempted to free invalid ID: 0
   at: RenderingDeviceVulkan::_free_internal (drivers\vulkan\rendering_device_vulkan.cpp:8436)
ERROR: Attempted to free invalid ID: 0
   at: RenderingDeviceVulkan::_free_internal (drivers\vulkan\rendering_device_vulkan.cpp:8436)
ERROR: Attempted to free invalid ID: 0
   at: RenderingDeviceVulkan::_free_internal (drivers\vulkan\rendering_dev
```

**Comment by InfuriatedBrute** [comment]
Did not fix it for me. Nvidia RTX 3050.

**Comment by akien-mga** [comment]
I think the problem is that the Vulkan SDK (used to?) write some stuff to the Windows registry and didn't update it as the SDK changed. So your Windows registry must have some Vulkan SDK entries pointing at non-existing objects. They probably need to be deleted manually, or maybe a reinstall of the SDK would do it.

**Comment by obedabit** [comment]
I am also facing the same problem here:
`
Godot Engine v4.0.dev.20211117.official.175690957 - https://godotengine.org
USER ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 127437616
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:154) - GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 127437616
Vulkan API 1.2.182 - Using Vulkan Device #0: NVIDIA - GeForce 930M
USER ERROR: vkCreateComputePipelines failed with error -1000012000.
   at: compute_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6629) - Condition "err" is true. Returning: RID()
USER ERROR: vkCreateComputePipelines failed with error -1000012000.
   at: compute_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6629) - Condition "err" is true. Returning: RID()
`
my laptop specs:
Windows 10 pro 21H1 64-bit
CPU i7-6500U 
GPU Nvidia GeForce 930M
8GB RAM
VulkanRT 1.2.182
Nvidia driver version 388.57

**Comment by TotCac** [comment]
Updating nvidia driver to 511.23 has updated Vulkan to API 1.2.189.

No more warning now.

**Comment by Calinou** [comment]
Closing per @TotCac's comment.

Please comment if you can still reproduce this issue, **only if using driver version 511.23 or newer**.

**Comment by FyiurAmron** [comment]
for further generations: Vulkan Runtime `1.3.204.1` (01-Mar-2022) is the last version that supports Windows 7 x64 (or at least is seems so based on my trials and errors). Upgrading to it fixed this issue. Going higher [e.g. `1.3.211.0` (18-Apr-2022)] made Vulkan (i.e. in this case Godot, but also other Vulkan applications) just crash instead of running. YMMV

**Comment by lazuee** [comment]
![image](https://user-images.githubusercontent.com/91590512/193241510-79d98daf-66e4-4023-b6b3-aa8654963e58.png)

**Comment by Calinou** [comment]
@lazuee See the above comments for a resolution to this issue. This is caused by outdated graphics drivers.

**Comment by valkyrienyanko** [comment]
I am getting this warning on an AMD graphics card (RX 6600) on Adrenalin Edition Version 25.8.1 using Godot 4.4.1 stable mono and Windows 11 on Forward+ renderer. These are the latest released drivers from AMD's auto driver update tool released on 2025-07-24.

**Comment by clayjohn** [comment]
@valkyrienyanko You should roll back your drivers. There is a known issue with them that AMD is working on fixing https://github.com/godotengine/godot/issues/109378

**Comment by valkyrienyanko** [comment]
If it means anything, I still get the warning after downgrading to 25.6.1. Thank you for telling me about the issue with AMD, I had no idea this was a thing. I'll be staying on the downgraded version for now. 👍
