### ISSUE TITLE
Using multiple enums in a dictionary cause wrong return values

### ISSUE THREAD

**Issue by 4561235** [godotengine/godot#45720]
**Godot version:**

Godot Engine v3.2.3.rc.custom_build

**OS/device including version:**

POP OS 20.10

**Issue description:**

I made two enums and a dictionary. I put enums values as keys in the dictionary. I tried to access values from my dictionary using my enums and the returned value wasn't correct. The correct order should be: 3,2,5,1 but in the output is: 3,5,5,4. See the code and the output at the screen below.

![enumsBug](https://user-images.githubusercontent.com/38690495/106969795-dcd3ac80-674b-11eb-8e69-de096314b475.png)

**Steps to reproduce:**

Copy and paste this code on a Node:
```
extends Node

enum Ingots {
	GOLD,
	IRON,
	COPPER
}

enum Days {
	MONDAY,
	TUESDAY,
	WEDNESDAY
}

var dict = {
	Ingots.GOLD : 0,
	Ingots.IRON : 1,
	Ingots.COPPER : 2,
	Days.MONDAY : 3,
	Days.TUESDAY : 4,
	Days.WEDNESDAY : 5
}

func _ready():
	print(dict[Days.MONDAY]) #Return value should be: 3
	print(dict[Ingots.COPPER]) #Return value should be: 2
	print(dict[Days.WEDNESDAY]) #Return value should be: 5
	print(dict[Ingots.IRON]) #Return value should be: 1
	pass
```

**Minimal reproduction project:**

Copy and paste the code in "Steps to reproduce".

**Comment by Calinou** [comment]
This is because the Ingots and Days enums will share the same values. If you don't want that to happen, you have to give them different initial values:

```gdscript
enum Ingots {
	GOLD = 0,
	IRON,
	COPPER
}

# Let's assume that there can only be 256 Ingot values at most.
enum Days {
	MONDAY = 256,
	TUESDAY,
	WEDNESDAY
}
```

**Comment by 4561235** [comment]
> This is because the Ingots and Days enums will share the same values. If you don't want that to happen, you have to give them different initial values:
> 
> ```gdscript
> # Specify 0 to be more explicit (this is the default starting value).
> enum Ingots {
> 	GOLD = 0,
> 	IRON,  # 1
> 	COPPER  # 2
> }
> 
> # Let's assume that there can only be 256 Ingot values at most.
> enum Days {
> 	MONDAY = 256,
> 	TUESDAY,  # 257
> 	WEDNESDAY  # 258
> }
> ```

Calinou's answer solved the problem. Thank you very much! :)
Maybe we should update the documentation to inform others about this?

![enumBugSolved](https://user-images.githubusercontent.com/38690495/106971536-6a64cb80-674f-11eb-8ea7-3cb11e4e89a5.png)

**Comment by Calinou** [comment]
> Maybe we should update the documentation to inform others about this?

This is expected when using enums in any programming language. They're not designed to be used as dictionary *keys*.
