### ISSUE TITLE
Calling `set` within class triggers setter

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#45729]
**Godot version:**

**OS/device including version:**

**Issue description:**

Calling `set` triggers the setter for a property. This causes a stackoverflow if `set` is called within the setter.

**Steps to reproduce:**

This is a slightly-less-minimal example to demonstrate _why_ you might do this:

```
extends Node

const STAT_MAX := 20

var strength: int setget set_strength
var agility: int setget set_agility
var intellect: int setget set_intellect

func _set_bounded(prop: String, val: int, min_val: int, max_val: int):
	assert(val >= min_val and val <= max_val)
	set(prop, clamp(val, min_val, max_val))
	print_debug("Set %s to %d", prop, get(prop))

func set_strength(val: int):
	_set_bounded("strength", val, 0, STAT_MAX)

func set_agility(val: int):
	_set_bounded("agility", val, 0, STAT_MAX)

func set_intellect(val: int):
	_set_bounded("intellect", val, 0, STAT_MAX)
```

From another node, call `character.strength = 5`. The stack will overflow, as `set` invokes the setter. This is surprising given [the docs](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html) say:

> Whenever the value of variable is modified by an external source (i.e. not from local usage in the class), the setter function (setterfunc above) will be called

> As said, local access will not trigger the setter and getter.

I'm happy to add a gotcha to the docs and close this, but I wanted to check if it was intentional first.

**Minimal reproduction project:**

**Comment by pycbouh** [comment]
I'm not sure calling a public method like `set` constitutes "local access", even if you call it from inside of the class itself.

**Comment by rcorre** [comment]
I'm not sure either, so I think we either need explicit documentation or a change in behavior. I don't feel strongly about which.

**Comment by Xrayez** [comment]
I think "local access" relates to GDScript. Everything which calls `set()` explicitly will call corresponding setter, because that's `Object`'s internal functionality which is agnostic to language used.

What you probably need is overriding `_set()`, `_get()`, and `_get_property_list()` callbacks. See example in [this answer](https://godotengine.org/qa/3196/how-add-subcategories-inspector-script-variables-section?show=3252#a3252), for instance.

**Comment by rcorre** [comment]
Here's another surprising one: does accessing a superclass property within a subclass count as local access? Looks like yes:

```
extends AudioStreamSample
class_name SineSample

func _init():
	data.resize(22050)  # data is actually get_data(), which returns a copy
	for i in range(22050):
		data[i] = int(127 * sin(0.01 * TAU * i))  # crash! index out of bounds
```

You actually need:

```
extends AudioStreamSample
class_name SineSample

func _init():
        var data := PoolByteArray()
	data.resize(22050)
	for i in range(22050):
		data[i] = int(127 * sin(0.01 * TAU * i))
        self.data = data
```

This isn't necessarily _wrong_, just confusing. If you asked me before I tried this whether accessing a superclass value from a subclass counts as "local access" or not, I'd probably flip a coin.

**Comment by pycbouh** [comment]
I think it's just the nature of dealing with PoolArrays, which are copied and not passed by reference.

**Comment by rcorre** [comment]
It is, but my point is that it isn't clear whether `data` is "local" or not, which determines whether you get a copy or not.

**Comment by rcorre** [comment]
Aha! https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#properties

> Unlike setget in previous Godot versions, the properties setter and getter are always called, even when accessed inside the same class (with or without prefixing with self.). This makes the behavior consistent.

4.0 won't have this confusion. :tada:
