### ISSUE TITLE
Webassembly preview

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#4572]
Hello!
Can we have a preview for wasm through [binaryen](https://github.com/WebAssembly/binaryen)?
Firefox nightly and chrome canary have a demo: [Demo](https://webassembly.github.io/demo/)
Another demo: [demo-bananabread](https://github.com/WebAssembly/demo-bananabread)
Toggle javascript.options.wasm in (about:config).
Here is fire fox nightly: [https://nightly.mozilla.org/](https://nightly.mozilla.org/)

**Comment by kubecz3k** [comment]
I'm not sure Godot at current moment is using Webassembly as it's html5 backend.  However core developers are having high hopes for this technology for the future, you can read more here: http://godotengine.org/article/webassembly-godot-web

**Comment by vnen** [comment]
Is there any timetable for WebAssembly? I'm sure the core devs want to use it but it's hard to do anything while the API is in flux and there's no prediction when it'll become stable. Also, they plan to make it easy conversion from Emscripten, which we use already.

**Comment by eska014** [comment]
Currently Emscripten still goes the extra mile over `asm.js` (C++ → LLVM bitcode → asm.js → wasm).
This is not going to change before LLVM has a proper `wasm` backend. I don't think it's worth it to look into changing the build system before then, unless someone is curious enough to do it themselves.

Until then, web export still has more than enough issues (that will persist with or without WebAssembly)

**Comment by techtonik** [comment]
https://webassembly.github.io/demo/ looks cool.

**Comment by eska014** [comment]
We've had WebAssembly export for more than a year now, so closing this.

> not going to change before LLVM has a proper wasm backend

@eska014 from almost 2 years ago: You're gonna be waiting for a long time, LLVM's WebAssembly backend is still experimental
