### ISSUE TITLE
[Gamepad API] Ipega PG-9118 analog sticks are reporting a little offset value in Godot

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#45738]
**Godot version:**

- I use the [Joypads (DEBUG)](https://no-war.fales.me/joy/) as suggested [here](https://godotengine.org/article/godot-web-progress-report-5) to test.

**OS/device including version:**

- Windows 10 Home 64-bit, Version 20H2, OS build 19042.746
- Intel® UHD Graphics 620, Version 27.20.100.9168
- Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)
- Firefox 85.0 (64-bit)

**Issue description:**

The analog sticks values are not reset to zero when idle (no input). 

However, this issue is not unified across the browsers. For instance, Firefox doesn't have this issue when using wired connection (the gamepad will be detected as an Xbox controller by default when connecting to Windows PC) or bluetooth connection with Xbox 360 Controller Emulator (x360ce). The browser's interactions with the gamepad (Ipega PG-9118 as tested) are shown below:

**Google Chrome**

_wired connection / bluetooth connection with Xbox 360 Controller Emulator (x360ce)_

https://user-images.githubusercontent.com/1403194/107086206-6d57ce80-67d8-11eb-9cff-94e464b6900e.mp4

_bluetooth connection **without** Xbox 360 Controller Emulator (x360ce)_ 

https://user-images.githubusercontent.com/1403194/107087068-a9d7fa00-67d9-11eb-90d2-b16eb4c49634.mp4

**Firefox**

_wired connection / bluetooth connection with Xbox 360 Controller Emulator (x360ce)_

https://user-images.githubusercontent.com/1403194/107086659-156d9780-67d9-11eb-9dda-30d8142c9217.mp4

_bluetooth connection **without** Xbox 360 Controller Emulator (x360ce)_ 

https://user-images.githubusercontent.com/1403194/107086703-23bbb380-67d9-11eb-9636-a96a675d0e62.mp4

Currently, only Firefox with _wired connection / bluetooth connection with Xbox 360 Controller Emulator (x360ce)_ work correctly with the gamepad. I expect the analog value to be zero when idle in all browsers and all gamepad connection modes.

**Steps to reproduce:**

1. Connect the Ipega PG-9118 gamepad via the bluetooth or wired connection.
2. Go to the [Joypads (DEBUG)](https://no-war.fales.me/joy/) website.
3. Remap the button as needed.
4. Test both of your analog sticks.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
I have the same issue with Chrome and the newest XBox gamepad. Looks more like hardware issue though.

**Comment by Faless** [comment]
> I expect the analog value to be zero when idle in all browsers and all gamepad connection modes.

This is almost never the case with gamepads, especially after some time of usage. Analog sticks simply gets damaged/dirty. Different browser might apply different form of deadzone or 0-ing epsilon.
x360ce will remap, and apply deadzone and rounding of values, so it's expected to give different results when in use (the browser too will apply different mapping as `x360ce` will fake it to be an Xbox controller).

I'm closing this, since it's not really a Godot issue.

**Comment by Calinou** [comment]
PS: There's now a [documentation page about controllers in Godot](https://docs.godotengine.org/en/latest/tutorials/inputs/controllers_gamepads_joysticks.html) :slightly_smiling_face:
