### ISSUE TITLE
NetworkedMultiplayerENet doesn't return an error when joining a non-existant server

### ISSUE THREAD

**Issue by ragerin** [godotengine/godot#45744]
**Godot version:**
`3.2.3.stable.official`

**OS/device including version:**
OS: `Manjaro Linux x86_64`
Kernel: `5.10.7-3-MANJARO`

**Issue description:**
When calling `.create_client(address, port)` on an instance of `NetworkedMultiplayerENet`, I expect it to return a non-zero error if there is no server to respond.

This is not the case as the method returns a 0 and emits no other signals, even though no server is present on the specified address and port.

I have not tested on other machines/OS, as I have none available.

**Steps to reproduce:**
1. Create a Node and attach a script to it.
2. In the `_ready` method, insert the code below.
3. Run the scene and observe the Output pane where a `0` is printed.
```
    var peer = NetworkedMultiplayerENet.new()
    var err = peer.create_client('127.0.0.1', 1234)
    assert(err == OK)
    print(err)
```

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/5935605/test.zip)

**Comment by Calinou** [comment]
cc @Faless

**Comment by ragerin** [comment]
While not a fix, I solved the issue temporarily with the following code on for my "Join game" scene:

```
var timeout_counter = 0.0
var timeout = 5.0
var connection_state
```
In a `physics_process` or `process`:
```
if get_tree().network_peer:
    connection_state = get_tree().network_peer.get_connection_status()
    if connection_state == 1:
        timeout_counter += delta

        # Timeout
        if timeout_counter >= timeout:
            # Handle timeout here
            timeout_counter = 0.0
            get_tree().network_peer = null
        elif connection_state == 2:
            # Handle success here
            pass
```

I don't see any problem with handling the connection state like this, but reading the documentation for `.connect_client` I'd expect that method to block and handle this behind the scenes.

**Comment by Faless** [comment]
There is no way we can know if the server is not available, so there is no way to return an error.
The method should absolutely not block, but should also emit a signal after the connection reaches a timeout.

**Comment by Faless** [comment]
And it does timeout emitting `connection_failed` after 30 seconds:

```gdscript
extends Spatial

var peer = null

func _ready():
	peer = NetworkedMultiplayerENet.new()
	peer.connect("connection_failed", self, "_failed")
	var err = peer.create_client('127.0.0.1', 1234)

func _process(delta):
	peer.poll()

func _failed():
	print("Failed")
```

**Comment by ragerin** [comment]
@Faless thanks for pointing that out. It does work with the signal as you noted, and I agree with this issue being closed.

I don't think it's very clear from the documentation regarding the `create_client` method, but acknowledge that it is stated elsewhere in the documentation regarding the Multiplayer API. Maybe it's just me getting confused by the method returning an error-code, with which I'd expect to be able to handle connection issues as well.

**Comment by wayjack** [comment]
> @Faless thanks for pointing that out. It does work with the signal as you noted, and I agree with this issue being closed.
> 
> I don't think it's very clear from the documentation regarding the `create_client` method, but acknowledge that it is stated elsewhere in the documentation regarding the Multiplayer API. Maybe it's just me getting confused by the method returning an error-code, with which I'd expect to be able to handle connection issues as well.

I agree, I just stumbled across this issue as well today. Did not realize connection_failed would eventually be emitted. Is the 30 sec timeout hard-coded into ENetMultiplayerPeer? I think it should be exposed and configurable by the user at least.

**Comment by hak33m16** [comment]
Any chance this will ever become configurable? Not very user friendly at the moment

**Comment by Faless** [comment]
@hak33m16 this is a very old 3.2 issue, timeout configuration has been available for a while via `NetworkedMultiplayerENet.set_peer_timeout` in 3.x , and `ENetPacketPeer.set_timeout` in 4.x .
