### ISSUE TITLE
Vulkan: Setting a PanoramaSky makes console spam error

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45746]
**Godot version:**
Godot Engine v4.0.dev.calinou.779dc7613

**OS/device including version:**
Windows 10 x64
Using Vulkan Device #0: AMD - AMD Radeon R7 200 Series

**Issue description:**
Console spams  INFINITELY the following message:
```
ERROR: Condition "!uniform_set" is true.
   at: draw_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:6452)
ERROR: Uniforms were never supplied for set (1) at the time of drawing, which are required by the pipeline
   at: (drivers/vulkan/rendering_device_vulkan.cpp:6607)
```
This happens when you set the sky to .HDR file and also the sky goes black:
![image](https://user-images.githubusercontent.com/58845030/107096566-d09e2c80-67e9-11eb-93d1-52bbd8aa469d.png)

**Steps to reproduce:**
* Create a new WordEnvironment node
* use the following config:
![image](https://user-images.githubusercontent.com/58845030/107096648-fdeada80-67e9-11eb-959a-c8dbe9d2e0ac.png)

**Minimal reproduction project:**

[WorldBug.zip](https://github.com/godotengine/godot/files/5935703/WorldBug.zip)

PS: When you click worldenvironment node, mode will be clearcolor, change it to Sky
![image](https://user-images.githubusercontent.com/58845030/107097122-02fc5980-67eb-11eb-8b05-080629677718.png)

**Update**

Closing godot and opening the project again, things works nice
edit: Just closing the scene and opening it works as well.

![image](https://user-images.githubusercontent.com/58845030/107098023-07c20d00-67ed-11eb-85a0-7bd75eaa785a.png)

**Comment by akien-mga** [comment]
Thanks for the detailed bug report.

I tested in a recent `master` build and I can't reproduce the issue, it must have been fixed recently (before #54489 as the build I'm testing didn't include this PR yet).

I also couldn't reproduce it in `v4.0.dev.20210811.official` (7188cb601). You might want to double check yourself as maybe this was system specific or needs slightly different steps to reproduce.
