### ISSUE TITLE
Reset zoom shortcut doesn't work

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#45747]
**Godot version:**

b70836c

**Issue description:**

In 2D editor, the Reset Zoom (Ctrl+0 by default) shortcut does nothing. Might apply to other shortcuts, but not all (e.g. tools work properly).

**Comment by KoBeWi** [comment]
Seems fixed in 758bccf

**Comment by AeioMuch** [comment]
It does not work with CTRL + numpad 0, but work with CTRL + non numpad 0 (Godot 4.0.alpha13.official [59dcddc45])

**Comment by Calinou** [comment]
> It does not work with CTRL + numpad 0, but work with CTRL + non numpad 0 (Godot 4.0.alpha13.official [59dcddc45])

Which keyboard layout are you using? Non-QWERTY layouts can often struggle with this. Also, double-check that numlock is enabled :slightly_smiling_face:

**Comment by KoBeWi** [comment]
That's because numpad 0 is a separate key.

**Comment by AeioMuch** [comment]
Azerty indeed (belgian), and yes numlock is enabled. I mean, as long as you can reset it it’s ok. I did reply just in case someone wanted to know 😉
Thank you for your answer

De : Hugo ***@***.***>
Envoyé le :mercredi 10 août 2022 14:58
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [godotengine/godot] Reset zoom shortcut doesn't work (#45747)


It does not work with CTRL + numpad 0, but work with CTRL + non numpad 0 (Godot 4.0.alpha13.official [59dcddc45])

Which keyboard layout are you using? Non-QWERTY layouts can often struggle with this. Also, double-check that numlock is enabled 🙂
