### ISSUE TITLE
[Godot 4] Importing 3D models (glb only?) shows console message

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45743]
**Godot version:**
Godot Engine v4.0.dev.calinou.779dc7613

**OS/device including version:**
Windows 10 x64
Using Vulkan Device #0: AMD - AMD Radeon R7 200 Series

**Issue description:**

When importing glb (~240mb) file from blender, godot emits the following message:

![image](https://user-images.githubusercontent.com/58845030/107091840-28846580-67e1-11eb-93f3-fca4e4fad72f.png)

But at the moment, i can see it (this is the expected way ?):
![image](https://user-images.githubusercontent.com/58845030/107092067-a0529000-67e1-11eb-9a97-5d88b89d0265.png)

**Steps to reproduce:**
* Import 3D File (.glb)

**Files**

https://drive.google.com/file/d/1dGIhibVa2iDMvLamOretgbToiAdWVOKq/view?usp=sharing

**Comment by Calinou** [comment]
Can you link to the glb file you imported?

**Comment by nonunknown** [comment]
> @nonunknown Can you link to the glb file you imported?

well , the file is ~250mb, I can send you a piece of it which is 50mb, its okay?
