### ISSUE TITLE
Godot is too slow

### ISSUE THREAD

**Issue by dakennedyd** [godotengine/godot#45753]
Godot version: 4.0
commit: b70836c8edd504e2f3e331ae30cd8d3c3c4b931c

OS/device including version:
Ubuntu 20.04 
Nvidia driver: 460.32.03

Issue description:
It is slow to start, after a while it becomes unresponsive.

Steps to reproduce:
1. Go to project settings/localization/text server data or Project settings/Shader Globals
2. After a few seconds the program becomes unresponsive.
Also, if you add a GI node to the scene it becomes unresponsive.

Minimal reproduction project:
It happens on all projects.

**Comment by clayjohn** [comment]
Hi, sorry to hear that Godot isn't working well for you. 

Please remember that Godot 4.0 hasn't been released and is heavily in development. It is very likely that something about your system is causing issues. 

At any rate, you haven't provided us with any actionable information, so we can't really help you. Please try again in a few months and hopefully you will have a better experience!
