### ISSUE TITLE
Fedora 33 Build Error stdc++ missing

### ISSUE THREAD

**Issue by pejorativefox** [godotengine/godot#45751]
**Godot version:**

Building master @ b70836c8edd504e2f3e331ae30cd8d3c3c4b931c

**OS/device including version:**

Linux Fedora 33 unmodified in any way

**Issue description:**

When building I get a missing library -lstdc++ when the proper packages ARE installed

```
$ sudo dnf install libstdc++-devel
Last metadata expiration check: 1:36:47 ago on Sat 06 Feb 2021 09:07:16 AM CST.
Package libstdc++-devel-10.2.1-9.fc33.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

$ scons -j8 platform=linuxbsd
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Enabling udev support
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 78%] Linking Static Library ==> core/libcore.linuxbsd.tools.64.a
[ 86%] Ranlib Library         ==> core/libcore.linuxbsd.tools.64.a
[ 91%] Linking Program        ==> bin/godot.linuxbsd.tools.64
[100%] progress_finish(["progress_finish"], [])
[100%] Building compilation database compile_commands.json
[100%] /bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.linuxbsd.tools.64] Error 1
scons: building terminated because of errors.
```
Verification:
```
$ gcc hello.cpp -lstdc++
$ ldd a.out 
	linux-vdso.so.1 (0x00007ffc87bac000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fcb9c946000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fcb9c77b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fcb9c635000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcb9cb4f000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fcb9c61a000
```

**Steps to reproduce:**
* Checkout master @ commit hash above
* Install needed packages from the build documentation
* run "scons -j8 platform=linuxbsd" as per the build documentation

**Minimal reproduction project:**

**Comment by pejorativefox** [comment]
Also I see nothing in the official Fedora build of 3.x that corrects for this so I assume its a regression?
Here is a build of the 3.2.3-stable tarball from releases:
```
[Initial build] Building compilation database compile_commands.json
[Initial build] progress_finish(["progress_finish"], [])
[Initial build] Linking Static Library ==> core/libcore.x11.tools.64.a
Ranlib Library         ==> core/libcore.x11.tools.64.a
[Initial build] Linking Program        ==> bin/godot.x11.tools.64
[Initial build] scons: done building targets.
```

**Comment by akien-mga** [comment]
You need to install the static version of libstdc++, it's likely `libstdc++-static`.

**Comment by pejorativefox** [comment]
@akien-mga Cool so my confusion was this is not in the documentation, and that the 3.x versions build without it. So I could just make a PR to the docs repo to add this, but I am just worried about the confusion. Is the standard practice here that the master docs -> master engine. Just wanna be sure.

**Comment by akien-mga** [comment]
Yes sorry for not linking it earlier, I was on phone. I already opened this issue about it a few days ago, it's a new requirement in 3.2.4: https://github.com/godotengine/godot-docs/issues/4617

**Comment by pejorativefox** [comment]
And I didnt search the docs repo I assumed it was a build issue... My bad. I'm gonna close this with this comment. Thanks @akien-mga !
