### ISSUE TITLE
Godot Compiling for web fails to compile

### ISSUE THREAD

**Issue by XanthosWare** [godotengine/godot#45754]
**Godot version: 3.2.3 win64**

**OS/device including version: Windows 10**

**Issue description:**

When following ["Compiling for the Web"](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_web.html) tutorial, on "instructing SCons to build the Javascript platform", the building was terminated because of errors. I expected no errors to occur and for the build to successfully execute.

> C:\godot>scons platform=javascript tools=no target=release
scons: Reading SConscript files ...
Couldn't parse CXX environment variable to infer compiler version.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] ←[94mCompiling ←[95m==> ←[93mplatform\javascript\display_server_javascript.cpp←[0m
In file included from platform\javascript\display_server_javascript.cpp:33:
.\drivers/dummy/rasterizer_dummy.h:83:185: error: only virtual member functions can be marked 'override'
  ...&p_directional_lights, const RID *p_positional_light_instances, uint32_t p_positional_light_count) override {}
                                                                                                        ^~~~~~~~~
.\drivers/dummy/rasterizer_dummy.h:180:537: error: non-virtual member function marked 'override' hides virtual member
      function
  ...p_reflection_atlas, RID p_reflection_probe, int p_reflection_probe_pass, float p_screen_lod_threshold) override {}
                                                                                                            ^
.\servers/rendering/renderer_scene_render.h:219:15: note: hidden overloaded virtual function
      'RendererSceneRender::render_scene' declared here: different number of parameters (22 vs 17)
        virtual void render_scene(RID p_render_buffers, const Transform &p_cam_transform, const CameraMatrix &p_...
                     ^
In file included from platform\javascript\display_server_javascript.cpp:33:
.\drivers/dummy/rasterizer_dummy.h:181:229: error: only virtual member functions can be marked 'override'
  ...&p_camera_plane = Plane(), float p_lod_distance_multiplier = 0, float p_screen_lod_threshold = 0.0) override {}
                                                                                                         ^~~~~~~~~
.\drivers/dummy/rasterizer_dummy.h:183:107: error: only virtual member functions can be marked 'override'
  ...render_sdfgi(RID p_render_buffers, int p_region, const PagedArray<GeometryInstance *> &p_instances) override {}
                                                                                                         ^~~~~~~~~
.\drivers/dummy/rasterizer_dummy.h:184:161: error: only virtual member functions can be marked 'override'
  ...p_cascade_count, const uint32_t *p_cascade_indices, const PagedArray<RID> *p_positional_lights) override {}
                                                                                                     ^~~~~~~~~
.\drivers/dummy/rasterizer_dummy.h:1029:23: error: field type 'RasterizerSceneDummy' is an abstract class
        RasterizerSceneDummy scene;
                             ^
.\servers/rendering/renderer_scene_render.h:219:15: note: unimplemented pure virtual method 'render_scene' in
      'RasterizerSceneDummy'
        virtual void render_scene(RID p_render_buffers, const Transform &p_cam_transform, const CameraMatrix &p_...
                     ^
In file included from platform\javascript\display_server_javascript.cpp:33:
.\drivers/dummy/rasterizer_dummy.h:1056:10: error: cannot initialize return object of type 'RendererCompositor *' with
      an rvalue of type 'RasterizerDummy *'
                return memnew(RasterizerDummy);
                       ^~~~~~~~~~~~~~~~~~~~~~~
.\core/os/memory.h:93:25: note: expanded from macro 'memnew'
#define memnew(m_class) _post_initialize(new ("") m_class)

**Steps to reproduce:**
1. Install Godot Source code in C:\godot using git clone
2. Install the emscripten in C:\emsdk using git clone
3. Open x86_x64 Cross Tools Command Prompt for VS 2019
4. Navigate to C:\emsdk
5. Type command **emsdk install latest**
6. Type command **emsdk activate latest --permanent**
7. Type command **emsdk_env.bat**
8. Navigate to  C:\godot
9. Type command **scons platform=javascript tools=no target=release**
10. The command prompt would return errors and terminate the building.

**Comment by akien-mga** [comment]
You're trying to compile the master branch, not 3.2.3. You should checkout `3.2.3-stable` for this.

Also note that emscripten 2.0.9+ broke compatibility for the code of 3.2.3-stable, so you should use an earlier version (2.0.8 should work).

**Comment by XanthosWare** [comment]
> 3.2.3-stable



> You're trying to compile the master branch, not 3.2.3. You should checkout `3.2.3-stable` for this.
> 
> Also note that emscripten 2.0.9+ broke compatibility for the code of 3.2.3-stable, so you should use an earlier version (2.0.8 should work).

Thank you, akien-mga! It works. I feel that the information about broken compatibility should be mentioned in the Compiling for Web tutorial. Thanks again!
