### ISSUE TITLE
Button pressed style never appears

### ISSUE THREAD

**Issue by viktorias** [godotengine/godot#4575]
Operating system or device - Godot version: Xubuntu 14.04.4 - Godot 2.0.2
Issue description (what happened, and what was expected):
I have a project where I want to use Buttons with custom images. If I set up  different properties in the Custom Styles section of the button and I run the project the pressed style never appears. All of the other styles are working except for the pressed style, (No matter if I use StyleBoxFlat or StyleboxTexture!)
And it's quite interesting because if I specify Custom Colors for the button the Font Color Pressed seems working!
I was expecting the pressed image appear too when the button is pressed, not just the font color change.
I was looking around the godot source I have noticed that in button.cpp in void Button::_notification(int p_what) function, first the pressed style is drawn in the switch( get_draw_mode() ) section, but then:

``` cpp
if (has_focus()) {

    Ref<StyleBox> style = get_stylebox("focus");
    style->draw(ci,Rect2(Point2(),size));
}
```

overwrites the button appearance. An unfortunately the button has the focus after being clicked and therefore the focused style is drawn "overwriting" the pressed style. IMHO the focused style only should be drawn for a button if it's not pressed, but has the focus. (For example the user navigating with the tab key and the button has the focus then the focused style should be active, but when he hits the space, and therefore presses the button, the pressed style should appear.)

Link to minimal example project (optional but very welcome):
I have attached a minimal project. You can see from the output the button has the focus when it is pressed.
[buttontest.zip](https://github.com/godotengine/godot/files/253486/buttontest.zip)

**Comment by bojidar-bg** [comment]
@viktorias ~ Two points,
1. Pressed is used for toggle-mode buttons, and
2. If focus is semi-transparent, the pressed style should appear from below :smile: 

Still, I guess it would be useful to be able to use opaque focus images...

**Comment by viktorias** [comment]
@bojidar-bg 
I see your point, I was using opaque image for the focus property not a transparent one. That's why the behaviour was so confusing. And in this case yes I agree 

> it would be useful to be able to use opaque focus images...

Thank you for your help.

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by viktorias** [comment]
I have tested with 3.0.2 and the behaviour is the same.

**Comment by naturally-intelligent** [comment]
I'm having this problem as well in 3.0.3.  Pressed button textures are not visible when focus textures are set, but they are visible when focus textures are turned off (but then you get the unwanted blue outline).

Button -> Custom Styles - > Pressed
Button -> Custom Styles - > Focus 

This IMO is definitely a 3.0.4 candidate bug, if 3.0.4 is a thing.  This breaks default expected behavior in many apps!

**Comment by jamie-pate** [comment]
[example behavior when not using transparent focus style](https://streamable.com/gw87j)

**Comment by akien-mga** [comment]
As per #23098, it seems like this is now fixed in the master branch.
