### ISSUE TITLE
Audio doesn't restart in animation after pausing it with .stop(false) then play

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [godotengine/godot#45759]
**Godot version:**

3.2.3 stable

**OS/device including version:**

Win 7 Pro Machine i7 though it happens both in IDE and in built IOS version so it's a design issue.

**Issue description:**

When I have an animation that I pause using AnimationPlayer.stop(false); then resume using AnimationPlayer.play(), while the visual elements resume correctly, any audio that was in the middle of playing does not resume.

**Steps to reproduce:**

Create an animation of 20 seconds.
Add an audio track and an audio keyframe at 1.0 seconds with the audio playing for say 8 seconds.

Play the animation and at 5.0 seconds pause it with AnimationPlayer.stop(false);
Now Resume it with Animation.Player.play()
Interrupted audio does not resume.

I have found a work-around though:

Before playing it again, if I store the current animation position, seek to zero and then advance back to the position it was just at and THEN do play() it works.

var stored_anim_position = ActivePageContents.myPagePlayer.current_animation_position;
ActivePageContents.myPagePlayer.seek(0.0);
ActivePageContents.myPagePlayer.advance(stored_anim_position);
ActivePageContents.myPagePlayer.play();

**Minimal reproduction project:**

**Comment by revilo** [comment]
I can confirm the issue for master branch, too. Here is a minimal reproduction project (for v4.00):
[v4_audioplayer.zip](https://github.com/godotengine/godot/files/5938914/v4_audioplayer.zip)

**Comment by akien-mga** [comment]
This is working as intended in 4.0 RC 3.

Note that for pausing and stopping animations, you now use `pause()` and `stop()`. Updated MRP:
[v4_audioplayer.zip](https://github.com/godotengine/godot/files/10804693/v4_audioplayer.zip)
