### ISSUE TITLE
Request to add a new feature in godot 4.0

### ISSUE THREAD

**Issue by ScintillationGamesOfficial** [godotengine/godot#45763]
**Godot version:**
Godot 4.0

**OS/device including version:**

**Issue description:**
 This is technically not an issue but I went on the godot website and got the news about 2d tilemap. So I was wondering that if the godot 4.0 devs can implement tilemap 3d like instead of image texture we have to give a .dae or .gltf mesh and do the tilemapping or someone able to make a addon of that type, it will make 3d modelling easier

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
That's already implemented with GridMap.

But this is not the place for feature requests, this should go to https://github.com/godotengine/godot-proposals, and should be somewhat more detailed to be useful for further discussion / implementation of features.
