### ISSUE TITLE
Tileset creation for 16x16 tiles is broken

### ISSUE THREAD

**Issue by ciw1973** [godotengine/godot#45767]
**Godot version:**
v3.2.3.stable

**OS/device including version:**
Windows 10 Home.

**Issue description:**
Trying to create a tileset from an image which is 16 pixels high is horrbily broken. See steps below.

**Steps to reproduce:**
- New Project, then 2D Scene, then Add Child Node, then TileMap
- Set Cell Size to 16 x 16
- TileSet, then New TileSet, then Click to open Tileset Editor
- Add/drag image (below) into panel to create Tileset.

![outer-border](https://user-images.githubusercontent.com/2350088/107123220-4232b500-6894-11eb-8578-0fe8917ee2eb.png)

- This looks odd to begin with:

![image](https://user-images.githubusercontent.com/2350088/107123186-144d7080-6894-11eb-8811-61a13e93dbdb.png)

- New Single Tile
- Enable Snapping, then click first tile, and it's highlighted using a 32 x 32 grid:

![image](https://user-images.githubusercontent.com/2350088/107123246-62fb0a80-6894-11eb-9d4b-6a8d73db0527.png)

- Continue selecting more tiles, then click the TileMap. Tiles in righthand list are 32 x 32, with the last row of the image repeated to fill the bottom 16 rows:

![image](https://user-images.githubusercontent.com/2350088/107123308-be2cfd00-6894-11eb-90b2-62f199ebb9c1.png)

- Whilst TileMap grid is 16 x 16, the tiles placed are 32 x 32, as they appear in the tile list:

![image](https://user-images.githubusercontent.com/2350088/107123335-e4529d00-6894-11eb-9716-2ddf07e2ca9d.png)

**Minimal reproduction project:**
See steps to reproduce.

**Comment by Calinou** [comment]
@ciw1973 Can you link to the tileset texture you've used on the screenshots?

**Comment by ciw1973** [comment]
Hi there,

I've literally included the image in the bug report.

Regards,


Chris

**Comment by Calinou** [comment]
@ciw1973 Apologies, I didn't notice it in the issue.

**Comment by Calinou** [comment]
This is not a bug. After opening the TileSet editor, you need to expand the Snap Options in the inspector and set the snap size to 16×16:

![image](https://user-images.githubusercontent.com/180032/107126762-fee73f00-68b1-11eb-8984-a7f73a39897f.png)

Once this is done, the grid size will be correct:

![image](https://user-images.githubusercontent.com/180032/107126768-145c6900-68b2-11eb-927a-73ac43080f49.png)

Remember that sometimes, you may want to use different TileMap cell sizes and TileSet tile sizes
.

**Comment by ciw1973** [comment]
Is there a reason the Snap options are not visible all the time whilst in the TileSet editor?

Having to choose "New Single Tile" and select a tile you don't want, just to see options which will almost certainly apply to the entire TileSet, is convoluted, and counterintuitive.

**Comment by Calinou** [comment]
> Is there a reason the Snap options are not visible all the time whilst in the TileSet editor?

Probably not, but fixing this is most likely not trivial either. The tilemap editor is being rewritten for 4.0: https://godotengine.org/article/tiles-editor-progress-report-2

**Comment by ciw1973** [comment]
OK, cool. Thanks.
