### ISSUE TITLE
set_read_only() in EditorProperties doesn't work correctly

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#45769]
**Godot version:**
4.0

**OS/device including version:**
All

**Issue description:**
There are extended class of EditorProperty such as `EditorPropertyVectorXXX` that has multiple `SpinBoxes` for `Vector2`, `Vector3`, etc.
As you can see in editor_propaties.cpp, `set_read_only()` does not make sense because `set_read_only()` does not propagate to all properties that the EditorProperties class has.

**Comment by Calinou** [comment]
I think it was never implemented for those properties in the first place.
