### ISSUE TITLE
Software crash when merging one Kinematicbody into another scene

### ISSUE THREAD

**Issue by Ohri1234** [godotengine/godot#45777]
**Godot version:**
stable 3.2.3

**OS/device including version:**
Windows 10 Professional
Device name DESKTOP-T3MH083
Prozessor AMD Ryzen 5 2600 Six-Core Processor 3.40 GHz
Installed RAM 16.0 GB
Device ID CE860F4C-F151-429D-B0F8-52E69AF2E314
Product ID 00330-50000-00000-AAOEM
System type 64-bit operating system, x64-based processor
Pen and touch input No pen or touch input is available for this display.

**Issue description:**
When I wanted to add a 3D Kinematicbody with some subnodes to another scene via the "merge from scene" function, Godot suddenly crashed. This has happened many times lately.

**Comment by Calinou** [comment]
@Ohri1234 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, can you try reproducing this bug in a [debug build](https://github.com/Calinou/godot-debug-builds) to get a backtrace?

**Comment by Calinou** [comment]
Note: "Merge from Scene" has been removed in favor of copy-pasting nodes using <kbd>Ctrl + C</kbd> and <kbd>Ctrl + V</kbd>, which likely fixes this issue.
