### ISSUE TITLE
Placing caret in editor scrolls the text causing issues finding the caret and text

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#45770]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Linux

**Issue description:**
When you place the caret in a text line after scrolling to a position you want to start editing, the line is scrolled a massive amount to the left or right of the causing complete confusion as to where you are and where the caret is on screen. When you click the cursor inside the editor it should not subsequently adjust the line, it should stay where it is.

Example:
![caratmove](https://user-images.githubusercontent.com/12863685/107124328-33033580-689b-11eb-81ae-2f28f4303726.gif)

This is the same, but done in any other editor, as you can see, nothing scrolls and you know exactly where you are:
![caratmove2](https://user-images.githubusercontent.com/12863685/107124498-35b25a80-689c-11eb-8ef4-f0792ff05711.gif)

**Comment by Calinou** [comment]
As a workaround, I recommend enabling soft wrapping in the Editor Settings.

**Comment by chucklepie** [comment]
Ok, I'll give it a try.

**Comment by chucklepie** [comment]
Wow. That was quick!
