### ISSUE TITLE
Godot hangup when using "tool" annotation

### ISSUE THREAD

**Issue by p-r-o-m-e-t-h-e-u-s** [godotengine/godot#45789]
**Godot version:**

3.2.3 (also newer like 3.2.4 rc1)

**OS/device including version:**

MacOS version / GLES3

**Issue description:**

Hanging UI, expect to open the scene

Workaround: Removing the "tool" annotation in Cloud.gd script.

**Steps to reproduce:**
Try to open just the demo scene in the editor, which contains  another scene with Path2D.
The combination with the Cloud.gd results in this hanging behavior. 

**Minimal reproduction project:**

[CrashDemo.zip](https://github.com/godotengine/godot/files/5938730/CrashDemo.zip)

**Comment by lawnjelly** [comment]
When I paused it from a debugger during a hang, the call stack looks like this:

```
1   _int_malloc                                                          malloc.c   4116 0x7ffff77428bc 
2   __GI___libc_malloc                                                   malloc.c   3066 0x7ffff7744419 
3   Memory::alloc_static                                                 memory.cpp 82   0x5ecd84c      
4   DefaultAllocator::alloc                                              memory.h   65   0x2c2ed37      
5   operator new                                                         memory.cpp 47   0x5ecd9ba      
6   Map<float, Vector2, Comparator<float>, DefaultAllocator>::_insert    map.h      347  0x55551b0      
7   Map<float, Vector2, Comparator<float>, DefaultAllocator>::insert     map.h      564  0x5554f10      
8   Map<float, Vector2, Comparator<float>, DefaultAllocator>::operator[] map.h      607  0x554c1d9      
9   Curve2D::_bake_segment2d                                             curve.cpp  658  0x553f170      
10  Curve2D::_bake_segment2d                                             curve.cpp  663  0x553f212      
11  Curve2D::_bake_segment2d                                             curve.cpp  662  0x553f1d1      
12  Curve2D::_bake_segment2d                                             curve.cpp  663  0x553f212      
13  Curve2D::_bake_segment2d                                             curve.cpp  663  0x553f212      
14  Curve2D::_bake_segment2d                                             curve.cpp  663  0x553f212      
15  Curve2D::_bake_segment2d                                             curve.cpp  663  0x553f212      
16  Curve2D::_bake_segment2d                                             curve.cpp  662  0x553f1d1      
17  Curve2D::_bake_segment2d                                             curve.cpp  663  0x553f212      
18  Curve2D::_bake_segment2d                                             curve.cpp  663  0x553f212      
19  Curve2D::_bake_segment2d                                             curve.cpp  663  0x553f212      
20  Curve2D::_bake_segment2d                                             curve.cpp  662  0x553f1d1      
... <More>                                                                                              
```
No idea about this part of Godot, but it might help another contributor.

**Comment by lawnjelly** [comment]
Ah, the 25 is coming from your `cloud.gd` script:
```
	draw_polygon(path.curve.tessellate(25), colors)
```
When I set it to 2, it finished fine.

**Comment by lawnjelly** [comment]
Yeah the docs say:
> max_stages controls how many subdivisions a curve segment may face before it is considered approximate enough. Each subdivision splits the segment in half, so the default 5 stages may mean up to 32 subdivisions per curve segment. Increase with care!

So it sounds like the number of subdivisions is going up with the square of this max_stages, or some such relationship. So I'm not sure it is a bug, and it is mentioned in the docs, so I don't know if there's anything actionable.

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
Thats it! Reducing to 5 works much better... for any reason I thought its a linearly scaling. My assumption was wrong.

I don't know if this is a "bug" or not. At the end, the editor hangs up and the "user" doesn't get feedback. Either detecting a high load with interruption or defining a maximum value could improve the usability. Just my thoughts.
Thx.

**Comment by Calinou** [comment]
> I don't know if this is a "bug" or not. At the end, the editor hangs up and the "user" doesn't get feedback. Either detecting a high load with interruption or defining a maximum value could improve the usability. Just my thoughts.

This is already being requested in https://github.com/godotengine/godot-proposals/issues/701, closing.
