### ISSUE TITLE
Sprite3D regression with custom SpatialMaterial

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#45782]
**Godot version:**
3.2.4 RC 1, seems to be a regression in 3.2.3-stable (likely from porting Sprite3D to a MeshInstance).

**OS/device including version:**
Mageia 8 Linux, Intel HD 630 and AMD Radeon RX Vega M

**Issue description:**
In 3.2.2 or earlier, you can assign a SpatialMaterial to this Sprite3D with Unshaded flag and Add blend mode to get this output:
![Screenshot_20210206_233956](https://user-images.githubusercontent.com/4701338/107131191-a07f8800-68d4-11eb-90e1-eab8558859ea.png)

In 3.2.3 and latest `3.2`, it becomes:
![Screenshot_20210206_234030](https://user-images.githubusercontent.com/4701338/107131202-b4c38500-68d4-11eb-8fb6-c328fde4e4fe.png)

**Steps to reproduce:**
- Add a transparent PNG to a Sprite3D
- Add a SpatialMaterial, e.g. with flag Unshaded and blend mode Add

**Minimal reproduction project:**
[Sprite3D-Material.zip](https://github.com/godotengine/godot/files/5937807/Sprite3D-Material.zip)

**Comment by clayjohn** [comment]
This is a change in behaviour resulting from the change to using meshes internally. You need to also set the texture in your SpatialMaterial because override_material now actually overrides the material. The same way it does on other Spatial objects.

**Comment by akien-mga** [comment]
Thanks, setting the texture as Albedo texture does work indeed. And there's a hint to that in the documentation for Sprite3D.texture so all good I think.

Though there's still something fishy which might need clarification in the docs: since the SpatialMaterial would override the texture, I removed the Sprite3D.texture, but then nothing gets rendered. It seems the Sprite3D.texture still needs to be set even though it gets overridden. I assume that Sprite3D uses it to calculate the size?

**Comment by Xrayez** [comment]
Wasn't it possible to propagate texture changes regardless of whether you're using a `SpatialMaterial`? I think `Sprite3D.texture` should be treated as the base for everything else.

**Comment by clayjohn** [comment]
> It seems the Sprite3D.texture still needs to be set even though it gets overridden. I assume that Sprite3D uses it to calculate the size?

Yes. That's exactly right. 

> I think Sprite3D.texture should be treated as the base for everything else, even if you use different albedo texture in the material.

This is how things work now. But before the Sprite3D.texture would override albedo regardless of whether you set an albedo texture or not.

**Comment by akien-mga** [comment]
> > I think Sprite3D.texture should be treated as the base for everything else, even if you use different albedo texture in the material.
> 
> This is how things work now. But before the Sprite3D.texture would override albedo regardless of whether you set an albedo texture or not.

I'm not sure to understand what `Sprite3D.texture` affects at all aside from the size, when any SpatialMaterial is assigned. It seems to me that as soon as a SpatialMaterial is added, the `Sprite3D.texture` is relegated to a simple size definition placeholder, I don't see a way to configure the SpatialMaterial to make it actually used for the albedo.

We should likely document this in more details as the current docs from #41088 are a bit terse.

**Comment by clayjohn** [comment]
> I'm not sure to understand what Sprite3D.texture affects at all aside from the size, when any SpatialMaterial is assigned. It seems to me that as soon as a SpatialMaterial is added, the Sprite3D.texture is relegated to a simple size definition placeholder, I don't see a way to configure the SpatialMaterial to make it actually used for the albedo.

That's right. If you override the material then the Sprite3d.texture is only used for size. When you use a material override it overrides the current material, including the albedo texture.

**Comment by TedSpikes** [comment]
Should this be closed? The documentation changes were merged.

**Comment by akien-mga** [comment]
Yes, thanks. Fixed by #64135.
