### ISSUE TITLE
Moving a node with Editable Children enabled will disable it.

### ISSUE THREAD

**Issue by Gamespleasure** [godotengine/godot#45788]
**Godot version:**

3.2.3.stable

**Issue description:**

Moving a scene node with Editable Children enabled will disable it instead of being still enabled, and the edited properties will be kept unchanged in the editor, but will be changed to the default value when playing the game.

**Steps to reproduce:**
1. Create a Control node inside of a Control node
2. Instance a scene on it
3. Move it outside of the parent node

**Comment by Zireael07** [comment]
It was already reported, and fixed with the editable children rework.

**Comment by KoBeWi** [comment]
This is fixed in 3.2.4 rc1.
