### ISSUE TITLE
bug in tscn format

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#4579]
**Operating system or device - Godot version:**
godot 2.0.2

**Issue description** (what happened, and what was expected):
1 to create a scene "A"
2 create a scene "B" and add the scene of "A"
3 included in the stage of "B" at the scene "A" mode "redoktirovanie children"
4 In this mode, the scene of "A" to edit some sort of option (but not root node) (I used a string)
5 values of changed parameters at startup will not change

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/s/5wz2coi8367v3zi/tscn_error.zip?dl=0

**Comment by neikeq** [comment]
This is how I understood the steps:

1. Create scene "A"
2. Create scene "B" and instance the scene "A" on it
3. Enable the option "Editable Children" for the instanced scene "A" in scene "B"
4. Edit some property of some children of the instanced scene "A" (not the "A" root node)
5. The values of these properties are not applied when running the game

I could not reproduce it, assuming that's the issue. In my test, the scene "A" was a _Control_ as node with a _Button_ as child. The property I changed was the button's text.

What version are you using? If you have problems explaining how to reproduce it, you can provide an example project.

**Comment by volzhs** [comment]
maybe it's about 3d? #4320

**Comment by ret80** [comment]
https://www.dropbox.com/s/5wz2coi8367v3zi/tscn_error.zip?dl=0

There's only one who writes the script "error" or "ok". It is also worth attention bridle error message from the engine.

**Comment by neikeq** [comment]
I get the following warning:

`Parent path 'fsm/enemy/world' for node 'hunt' has vanished when instancing 'res://scene/game.tscn'`

There is an issue about that warning which seems to be a _tscn_ bug: #4580. It may be the cause of this bug.

**Comment by ret80** [comment]
Perhaps only in my case, the variable "way" nothing found. The inspector can see that I have a way to script it is not.

![tsn_error](https://cloud.githubusercontent.com/assets/233268/15097690/490e0c78-152c-11e6-8e65-d98784745434.jpg)

**Comment by ret80** [comment]
Moreover, all present in the scene file, but does not work at start

![tscn_error_2](https://cloud.githubusercontent.com/assets/233268/15097720/8ccaa790-152d-11e6-8124-bd68b40a17c9.jpg)
