### ISSUE TITLE
TextureProgress's nine_patch_stretch property does not stretch textures for radial and bilinear fill_mode

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#45791]
Godot version:
3.2.4 rc1

OS/device including version:
Windows 10

Issue description:
When using TextureProgress node, the nine_patch_stretch property does not stretch texture_under and texture_over, while it does stretch texture_progress. In addition, for bilinear fill_mode, it has no effect at all.
![screen-record](https://user-images.githubusercontent.com/28705694/107144852-e3933700-6978-11eb-814e-625da3927a02.gif)

Steps to reproduce:
Add a TextureProgress node, add texture_under, texture_over and texture_progress. Enable the nine_patch_stretch. Scale the node down or up. Change the fill_mode.

Minimal reproduction project:
[test.zip](https://github.com/godotengine/godot/files/5940574/test.zip)

**Comment by lawnjelly** [comment]
> Any project will do.

A minimum reproduction project will help this get looked at.

**Comment by floppyhammer** [comment]
I'm making a fix to this, and hopefully making the nine_patch_stretch property behaves more consistently for different fill modes.

**Comment by akien-mga** [comment]
Fixe by #45815.
