### ISSUE TITLE
Editor Asset Library UI returns less result than Web UI

### ISSUE THREAD

**Issue by YRTV** [godotengine/godot#45795]
I did search by "Asset Library".  I don't think any issues was related.

**Godot version:**
3.2.3.stable.official

**OS/device including version:**
OS Windows10 20H2 (19042.746)
GPU ASUS NVIDIA GTX 760
CPU Intel Core i7-4790

**Issue description:**
Current behavior: Editor Asset Library UI returns less result than Web UI at https://godotengine.org/asset-library/asset
Expected behavior: Be able to see all results in editor.

**Steps to reproduce:**

Search for word "analog" using web UI and Editor UI (Screenshots attached)
![godot_2021-02-07_18-45-20](https://user-images.githubusercontent.com/18060413/107151672-d2482b80-6974-11eb-94ff-8c22f7be2766.png)
![firefox_2021-02-07_18-47-48](https://user-images.githubusercontent.com/18060413/107151715-06235100-6975-11eb-88a7-ffafd1a20961.png)

**Minimal reproduction project:**
Not a project issue.

**Comment by Calinou** [comment]
This is because the editor only displays results compatible with your Godot editor version.

**Comment by bruvzg** [comment]
> This is because the editor only displays results compatible with your Godot editor version.

In this case, the only asset shown in the editor is for 3.1, and the other two should be compatible as well (web UI have 3.2 filter set).

Editor displays only `Templates`, `Demos` and `Projects` categories, rest of the shown assets on the web UI are for `Tools`/`2D Tools` categories.
