### ISSUE TITLE
Hand tracking permission string for Quest

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#45809]
**Godot version:**
3.2.4

**OS/device including version:**
Android (Quest)

**Issue description:**
After discussing on Github we think this permission is wrong:
https://github.com/godotengine/godot/blob/master/platform/android/export/export.cpp#L770

Oculus reports: `Unable to identify permission com.oculus.permission.HAND_TRACKING`
We think it should be `oculus.permission.HAND_TRACKING`

**Steps to reproduce:**
Run Neosparks toolkit demo with handtracking enabled.

**Comment by BastiaanOlij** [comment]
Need to confirm with @m4gr3d and @NeoSpark314 if we got the right permission, if so just need to change it and test it.

**Comment by m4gr3d** [comment]
This is the correct permission string; it was updated in v15 of the SDK: https://developer.oculus.com/blog/oculus-developer-release-notes-v15/.

I'll follow up with Oculus to update the documentation accordingly.
