### ISSUE TITLE
C# Mathf.Smoothstep returns infinitesimal result

### ISSUE THREAD

**Issue by MrGreaterThan** [godotengine/godot#45804]
**Godot version:**

fe38afca89c453fe01591fedc0dc81a459a6927ea39b16d0d60cc2b2f583d0d74cfdbe6b83a9a4394250a237da3dc4079b31f828033fd1bec77c4547b9021ece  Godot_v3.2.4-rc1_win64.exe.zip

**OS/device including version:**

Windows 10 Pro 10.0.19041, GTX1080TI, Ryzen 2700x, GLES3, C#

**Issue description:**

The Mathf.SmoothStep function gives unexpected result. I'm expecting similar results to Mathf.Lerp(), but I am getting very small numbers back instead. The function seems to be  returning a number that correlates to its intended value, but it's scaled very small.

**Steps to reproduce:**
Use Mathf.SmoothStep to interpolate between a minimum and Maximum number.

**Minimal reproduction project:**

I've make a visual representation of the problem in this project.
[Smoothstep.zip](https://github.com/godotengine/godot/files/5939862/Smoothstep.zip)
![image](https://user-images.githubusercontent.com/26847380/107158269-b29e0c80-694e-11eb-9b10-20ada58fa636.png)

**Comment by Calinou** [comment]
cc @aaronfranke

**Comment by lawnjelly** [comment]
Smoothstep does this:
https://en.wikipedia.org/wiki/Smoothstep

Looks like the function is correct, but the docs are wrong / misleading (at least in 3.2), wrongly suggesting that it is like lerp.

The output of smoothstep is a value between 0 and 1.

```
float smoothstep(float edge0, float edge1, float x) {
  // Scale, bias and saturate x to 0..1 range
  x = clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0); 
  // Evaluate polynomial
  return x * x * (3 - 2 * x);
}
```

**Comment by MrGreaterThan** [comment]
@lawnjelly crushing 0.47 on a scale of 0 to 100 down to a scale of 0 to 1 doesn't give a number anywhere near as small as what I'm getting.
0.47 / 100 = 0.0047

I have no idea what your smoothstep function is supposed to be for, but I did notice that [Godot's docs](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-smoothstep) almost exactly match the verbiage of [Unity's Docs.](https://docs.unity3d.com/ScriptReference/Mathf.SmoothStep.html)

The only difference is that Unity's smoothstep function returns the value I am looking for. (I created a test project in unity just now to test it.) I believe that OpenGL has a smoothstep which is probably used for a different purpose, so perhaps that has something to do with the confusion?

Given the syntax is the same as lerp() and the documents say it should behave similar to lerp() and Unity's smoothstep() has almost the exact same verbiage and my expected behavior, I believe that it is the code that needs to change. Not the documentation.

**Comment by kleonc** [comment]
Check out [this related comment](https://github.com/godotengine/godot/pull/27231#discussion_r415647993) (yeah, I should've probably created a new issue instead of commenting there).

**Comment by lawnjelly** [comment]
I'm not an expert on the function (never having used it) but without more info I would tend towards the more widely accepted meaning of the function as with the original PR, rather than the unity version, unless there were convincing argument to change it. Plus changing it now would break backward compatibility.

Although you would have to alter code samples taken from unity, if the other definition was used you would have to alter code samples taken from glsl etc. In fact, given that smoothstep is already available in the godot shader language (which mirrors glsl) it would be confusing to have two different definitions of the function in the same engine.

@MrGreaterThan to get the unity type value you are after, I think this would work:
```
var f = smoothstep(0, 1, t);
var value = lerp(your_min, your_max, f);
```

**Comment by MrGreaterThan** [comment]
@lawnjelly Your arguments are better than mine, so I agree it should stay and the docs must change.

Perhaps it would be a good idea to add a small note on the docs to warm Unity converts about the difference.

**Comment by angad-k** [comment]
Is this issue open? I'd like to work on it.

**Comment by akien-mga** [comment]
Go ahead :) As suggested by @lawnjelly, the documentation needs to be improved to clarify the behavior of smoothstep.
It's in `doc/classes/@GlobalScope.xml`, see https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html and https://docs.godotengine.org/en/latest/community/contributing/class_reference_writing_guidelines.html for relevant documentation on editing the class reference.

**Comment by angad-k** [comment]
I guess this is already fixed in the master branch. This is what the documentations says : 
```
Returns the result of smoothly interpolating the value of [code]x[/code] between [code]0[/code] and [code]1[/code], based on the where [code]x[/code] lies with respect to the edges [code]from[/code] and [code]to[/code].
				The return value is [code]0[/code] if [code]x &lt;= from[/code], and [code]1[/code] if [code]x &gt;= to[/code]. If [code]x[/code] lies between [code]from[/code] and [code]to[/code], the returned value follows an S-shaped curve that maps [code]x[/code] between [code]0[/code] and [code]1[/code].
				This S-shaped curve is the cubic Hermite interpolator, given by [code]f(x) = 3*x^2 - 2*x^3[/code].
```
which I guess is correctly telling what the function does save for the last line since x isn't directly fed into ```3*x^2 - 2*x^3``` but first scaled according to the edges. I'll make a PR with a change to the last commit.

**Comment by lawnjelly** [comment]
More pressing is the need to make a PR to update the 3.2 docs, you should be able to just copy the docs from 4.0 (when you are happy with the PR for 4.0).

**Comment by kleonc** [comment]
Currently master and 3.2 docs are almost the same, https://github.com/godotengine/godot/pull/39898 was just cherry-picked (https://github.com/godotengine/godot/pull/45892/commits/347a9df0a146d9c765227eaca5105e5148d747eb).
