### ISSUE TITLE
DisplayServerWindows: Invalid window id in input event.

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#45808]
**Godot version:**

57e2822

**OS/device including version:**

Windows 10

**Issue description:**

When opening/closing windows (popup menus, project settings, color pickers etc), randomly this error will appear in the console:
![image](https://user-images.githubusercontent.com/2223172/107160760-86a77900-6998-11eb-8b2e-a6ef2246ef33.png)

It comes from here:
https://github.com/godotengine/godot/blob/57e2822a05c29db3980ad243c37a34acf6c4d14b/platform/windows/display_server_windows.cpp#L1787-L1790

This used to freeze the editor (see #45325), but was patched. The original cause of this error should still be fixed though.

**Comment by mhilbrunner** [comment]
This just crashed my Godot engine (recent master https://github.com/godotengine/godot/commit/c89ad92c96a9b99d8550acda47e71948dffec1cd) build on Windows 10 - happened when I was editing a very simple GDScript and used backspace/deleted invalid code, seemingly during autocomplete/parsing when it tried to open the suggestion dropdown/popup:

```
ERR_PARSE_ERROR
at GDScript::reload @ modules\gdscript\gdscript.cpp:840
DisplayServerWindows: Invalid window id in input event
platform\windows\display_server_windows:1796
x2
FATAL: Index p_index = -1 is out of bounds (size() = 3)
at CowData<char32_t>::get (C:\...templates/cowdata.h:157)
```

![godot-crash](https://user-images.githubusercontent.com/1654763/129235606-a1ed98fd-f3a3-47b9-9ca3-331679f6acd5.PNG)
