### ISSUE TITLE
Incorrect debug symbols on windows platform

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#45816]
**Godot version:**
Master

**OS/device including version:**
Windows

**Issue description:**
Trying to use vscode as a debugger for Windows found a few interesting issues.

`env("debug_symbols")` returns a boolean thanks to its definition but it's compared to a "yes" string:
```
if env["debug_symbols"] == "yes":
```
That actually fails for me and should become `if env["debug_symbols"]`

Obviously this is only important for `target=release_debug`, `target=debug` will include debug flags through a different if. 
Also I think that `target=release` will till keep debug_symbols as true, which I don't think is correct.

Finally it adds in `env.AppendUnique(CCFLAGS=["/Z7"])`, `/Z7` being version 7.0 compatible debug symbols. That may be needed for some environments I don't know but for vscode it doesn't like this option. Using `/Zi` (include all debug symbols allowed me to debug my code).
I also needed to add the `/FS` flag to enable multiple threads writing to the pdb file.  

**Steps to reproduce:**
Setup VSCode for debugging and try to debug :)

**Comment by akien-mga** [comment]
> `env("debug_symbols")` returns a boolean thanks to its definition but it's compared to a "yes" string:

That was a recent bug, fixed in #45818.

**Comment by BastiaanOlij** [comment]
Ok so all thats left is the question on whether to change /Z7 into /Zi and add the /FS flag.

**Comment by akien-mga** [comment]
I'd say that if you can confirm that debugging then works for MSVC-compiled binaries with both VS and VS Code, that's a good change to make.

**Comment by BastiaanOlij** [comment]
Only confirmed it for vs code, I've steered clear of VS itself. If I am not mistaken it requires a visual studio project file to be created. Not sure if the switches in scons translate to that properly or whether MS just overrides it with the settings it needs to do its thing.

**Comment by cridenour** [comment]
As of today, master uses `env.Append(CCFLAGS=["/Zi", "/FS"])` so this can be closed.

**Comment by akien-mga** [comment]
This was fixed a long time ago by #45825.
