### ISSUE TITLE
 About Godot running poorly on my computer

### ISSUE THREAD

**Issue by shuhai2008** [godotengine/godot#45817]
When I downloaded godot from steam, it didn't work properly, and it didn't respond after displaying a section of error text (see Figures 1 and 2). This might have something to do with the computer, which I put in Figures 3 and 4. My operating system running godot is Windows 7
I'm from China, so the pictures I provided are in Chinese. Please forgive me.

![$3% Y AZNGV93M$I5SBN`T](https://user-images.githubusercontent.com/57448027/107180736-4b4a9000-6a14-11eb-8740-99e557e0ff20.png)
![NCANUGSW34RRLVN755R}53C](https://user-images.githubusercontent.com/57448027/107180761-57cee880-6a14-11eb-84a1-935b2fec07b2.png)
![E4J(8X_C7M}(S5R4M{5YH5P](https://user-images.githubusercontent.com/57448027/107180769-5d2c3300-6a14-11eb-9fdf-7f79e9e8f625.png)
![P3RW3P1BE47HIE5}8HXE34K](https://user-images.githubusercontent.com/57448027/107180771-5ef5f680-6a14-11eb-8480-afe2c69ddccb.png)

**Comment by Calinou** [comment]
Sorry, but your computer is too old to run Godot (even with the GLES2 renderer).

**Comment by shuhai2008** [comment]
> 抱歉，您的计算机太旧了，无法运行Godot（即使使用GLES2渲染器）。您需要更新的图形卡才能运行Godot。

BEST  COMPUTER ON WORLD
