### ISSUE TITLE
[3.2.4.rc1] Android custom build export failed on icons merge

### ISSUE THREAD

**Issue by PoqXert** [godotengine/godot#45821]
**Godot version:**
3.2.4.rc1.official

**OS/device including version:**
Windows 10

**Issue description:**
Export using custom build template failed:

Debug:

```
* What went wrong:
Execution failed for task ':processDebugResources'.
> Could not resolve all files for configuration ':debugRuntimeClasspath'.
   > Failed to transform godot-lib.debug.aar to match attributes {artifactType=android-compiled-dependencies-resources}.
      > Execution failed for AarResourcesCompilerTransform: C:\Users\poqxe\.gradle\caches\transforms-2\files-2.1\292c13cebff2ac459e69cf36eef145a8\jetified-godot-lib.debug.
         > AAPT2 aapt2-4.1.0-6503028-windows Daemon #0: Unexpected error during compile 'C:\Users\poqxe\.gradle\caches\transforms-2\files-2.1\292c13cebff2ac459e69cf36eef145a8\jetified-godot-lib.debug\res\mipmap\icon.png', attempting to stop daemon.
```

Release:

 ```
> Task :stripReleaseDebugSymbols
 Unable to strip the following libraries, packaging them as they are: libc++_shared.so, libgodot_android.so.
 
 > Task :mergeReleaseResources
 > Task :mergeReleaseResources FAILED
 
 FAILURE: Build failed with an exception.
 
 * What went wrong:
 Execution failed for task ':mergeReleaseResources'.
 > Multiple task action failures occurred:
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > AAPT2 aapt2-4.1.0-6503028-windows Daemon #0: Unexpected error during compile 'D:\Projects\Test324\android\build\res\drawable\splash_bg_color.png', attempting to stop daemon.
         This should not happen under normal circumstances, please file an issue if it does.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > AAPT2 aapt2-4.1.0-6503028-windows Daemon #3: Unexpected error during compile 'D:\Projects\Test324\android\build\res\mipmap-xxxhdpi-v4\icon.png', attempting to stop daemon.
         This should not happen under normal circumstances, please file an issue if it does.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > AAPT2 aapt2-4.1.0-6503028-windows Daemon #1: Unexpected error during compile 'D:\Projects\Test324\android\build\res\mipmap-xhdpi-v4\icon_foreground.png', attempting to stop daemon.
         This should not happen under normal circumstances, please file an issue if it does.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > AAPT2 aapt2-4.1.0-6503028-windows Daemon #2: Unexpected error during compile 'D:\Projects\Test324\android\build\res\mipmap-xxhdpi-v4\icon_foreground.png', attempting to stop daemon.
         This should not happen under normal circumstances, please file an issue if it does.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > AAPT2 aapt2-4.1.0-6503028-windows Daemon #4: Unexpected error during compile 'D:\Projects\Test324\android\build\res\mipmap\icon_foreground.png', attempting to stop daemon.
         This should not happen under normal circumstances, please file an issue if it does.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > AAPT2 aapt2-4.1.0-6503028-windows Daemon #5: Unexpected error during compile 'D:\Projects\Test324\android\build\res\mipmap-xxhdpi-v4\icon.png', attempting to stop daemon.
         This should not happen under normal circumstances, please file an issue if it does.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > AAPT2 aapt2-4.1.0-6503028-windows Daemon #6: Unexpected error during compile 'D:\Projects\Test324\android\build\res\drawable\splash.png', attempting to stop daemon.
         This should not happen under normal circumstances, please file an issue if it does.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > AAPT2 aapt2-4.1.0-6503028-windows Daemon #7: Unexpected error during compile 'D:\Projects\Test324\android\build\res\mipmap-hdpi-v4\icon_foreground.png', attempting to stop daemon.
         This should not happen under normal circumstances, please file an issue if it does.

```
**Steps to reproduce:**
1. Create project.
2. Install Android Build Template
3. Add Android export and set "Custom Build"
4. Setup keystore.
5. Export project and get failed

**Minimal reproduction project:**
Default project

**Comment by m4gr3d** [comment]
@PoqXert I'm unable to reproduce the issue you described. I've used a copy of the Godot 3.2.4.rc1 build on a Windows 10 with a brand new Android project, and I was able to export the apk successfully in each attempts.

Can you provide additional information about your machine setup.

Thanks.

**Comment by PoqXert** [comment]
I created project in Linux and got the same error, but it works in macOS .

Android SDK:
```
Platform: Android 10.0 (29) and Android 11.0 (30)
Build Tools: 30.0.3
```
JDK:
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```
HW (Win/Linux):
```
CPU: AMD Phenom(tm) II X4 925 Processor 2.80 GHz
RAM: 8 GB
```
HW (macOS):
```
CPU: Dual-Core Intel Core i5
RAM: 8 GB
```

**Comment by m4gr3d** [comment]
@PoqXert Can you provide a copy of the the `godot-lib.debug.aar` and `godot-lib.release.aar` in your `android/build` directory since the error seems to originate when trying to process them.

Also can you confirm you are able to reproduce the issue using a new empty project with the official Android build template?

**Comment by m4gr3d** [comment]
@PoqXert Can you navigate to the `android/build/build/outputs/logs` directory, grab and provide the `manifest-merger*report` files. As well as the `lint-results-*` files in the `android/build/build/reports` directory.

Where is your `.gradle` directory located?

**Comment by PoqXert** [comment]
> 
> Also can you confirm you are able to reproduce the issue using a new empty project with the official Android build template?

Yes. New empty project, no plugins, no files changes.  

> Can you provide a copy of the the `godot-lib.debug.aar` and `godot-lib.release.aar` in your `android/build` directory since the error seems to originate when trying to process them.

[Libs](https://drive.google.com/file/d/1g6e4X4JvCYZi3Ee0rWXvo7Gd2Ro4Qrtt/view?usp=sharing)

**Comment by PoqXert** [comment]
> Can you navigate to the `android/build/build/outputs/logs` directory, grab and provide the `manifest-merger*report` files.

[manifest-merger-release-report.txt](https://github.com/godotengine/godot/files/5949611/manifest-merger-release-report.txt)
[manifest-merger-debug-report.txt](https://github.com/godotengine/godot/files/5949618/manifest-merger-debug-report.txt)

> As well as the `lint-results-*` files in the `android/build/build/reports` directory.

I haven't `reports` directory.


> Where is your `.gradle` directory located?

With cache? `C:\Users\poqxe`

**Comment by m4gr3d** [comment]
Both log files look normal. Looking at the debug error log in the issue description, it looks like the Godot engine was unable to convert `<USER_PATH>` into the corresponding filepath on your machine.

Is that error still occurring, and any idea why the path conversion would fail?
Are you also seeing the same debug error on the linux machine?

**Comment by PoqXert** [comment]
> Both log files look normal. Looking at the debug error log in the issue description, it looks like the Godot engine was unable to convert `<USER_PATH>` into the corresponding filepath on your machine.

Sorry, it's incorrect copy-paste. Path in log is corrent `C:\Users\poqxe\.gradle\.....`

```
> Task :preBuild UP-TO-DATE
> Task :preDebugBuild UP-TO-DATE
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript NO-SOURCE
> Task :generateDebugBuildConfig UP-TO-DATE
> Task :javaPreCompileDebug UP-TO-DATE
> Task :checkDebugAarMetadata UP-TO-DATE
> Task :generateDebugResValues UP-TO-DATE
> Task :generateDebugResources UP-TO-DATE
> Task :mergeDebugResources UP-TO-DATE
> Task :createDebugCompatibleScreenManifests UP-TO-DATE
> Task :extractDeepLinksDebug UP-TO-DATE
> Task :processDebugMainManifest UP-TO-DATE
> Task :processDebugManifest UP-TO-DATE
> Task :processDebugManifestForPackage UP-TO-DATE
> Task :processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Could not resolve all files for configuration ':debugRuntimeClasspath'.
   > Failed to transform godot-lib.debug.aar to match attributes {artifactType=android-compiled-dependencies-resources}.
      > Execution failed for AarResourcesCompilerTransform: C:\Users\poqxe\.gradle\caches\transforms-2\files-2.1\292c13cebff2ac459e69cf36eef145a8\jetified-godot-lib.debug.
         > AAPT2 aapt2-4.1.0-6503028-windows Daemon #0: Unexpected error during compile 'C:\Users\poqxe\.gradle\caches\transforms-2\files-2.1\292c13cebff2ac459e69cf36eef145a8\jetified-godot-lib.debug\res\mipmap\icon.png', attempting to stop daemon.
           This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
11 actionable tasks: 1 executed, 10 up-to-date

Exit Code: 1
```

**Comment by m4gr3d** [comment]
According to this [blog post](https://cazimirroman.medium.com/how-to-solve-the-execution-failed-for-aarresourcescompilertransform-issue-in-android-studio-90b7819facaa), the issue may be a elevation issue. Can you try following the steps in the blog post and see if that resolves the issue.

**Comment by m4gr3d** [comment]
In this case though, try to apply the steps to the Godot editor instead of Android Studio.

**Comment by m4gr3d** [comment]
@PoqXert Did previous versions of the Godot editor (e.g: 3.2.3) work as expected on your machine?

**Comment by PoqXert** [comment]
> @PoqXert Did previous versions of the Godot editor (e.g: 3.2.3) work as expected on your machine?

Yes.

**Comment by PoqXert** [comment]
> According to this [blog post](https://cazimirroman.medium.com/how-to-solve-the-execution-failed-for-aarresourcescompilertransform-issue-in-android-studio-90b7819facaa), the issue may be a elevation issue. Can you try following the steps in the blog post and see if that resolves the issue.

This didn't resolve the issue.

**Comment by PoqXert** [comment]
I changed `androidGradlePlugin` version in `config.gradle` to `3.5.3` (as in Godot 3.2.3) and the project built without errors. (but there are warnings about deprecated code)

**Comment by m4gr3d** [comment]
@PoqXert Looks like this is a bug with AGP v4.1.+ on older machines:  

- https://issuetracker.google.com/issues/171235570
- https://stackoverflow.com/questions/64947285/why-is-android-studio-failing-to-build-with-an-aapt2-error-on-images

I'll revert to AGP v4.0.x for the time being in order to resolve the issue.
Thanks for reporting!

**Comment by m4gr3d** [comment]
@PoqXert On your machine, can you test if changing the `androidGradlePlugin` value to `4.0.1` resolves the issue.

**Comment by PoqXert** [comment]
> changing the `androidGradlePlugin` value to `4.0.1` resolves the issue.

Yes. It resolve the issue.
