### ISSUE TITLE
Visual Shader, doesn't cast bools to float when trying to add or multiply them together

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#45826]
**Godot version:**
3.2.4.rc1

**OS/device including version:**
NA

**Issue description:**
Visual Shader, doesn't cast bools to float when trying to add or multiply them together.
It appears to work fine as long as only one of the values is a bool, but not with both.
![image](https://user-images.githubusercontent.com/4955051/107227438-489b6b00-6a13-11eb-8d27-d000c8861df2.png)

**Steps to reproduce:**
Open the example.tres in the attached project.

**Minimal reproduction project:**

[visual_shader_boolean.zip](https://github.com/godotengine/godot/files/5943988/visual_shader_boolean.zip)

**Comment by Chaosus** [comment]
Fixed in master, need to be backported to 3.2

**Comment by akien-mga** [comment]
Fixed by #45831.
