### ISSUE TITLE
DisplayServer: An open window sometimes interferes with UndoRedo

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#45820]
**Godot version:**
4.0-dev

**OS/device including version:**
Kubuntu 20.10

**Issue description:**
In some cases, an open window prevents the editor's global UndoRedo. When the window is closed, <kbd>Ctrl+Z</kbd> and <kbd>Ctrl+Shift+Z</kbd> work fine.

**Steps to reproduce:**
1. Open Project Settings Editor.
2. Add a custom setting and delete it.
3. Press <kbd>Ctrl+Z</kbd>: the setting won't back (in 3.2 it works).
4. Close Project Settings Editor.
5. Press <kbd>Ctrl+Z</kbd> ("Undo: Delete Item" will appear in the output log).
6. Open Project Settings Editor and make sure the setting is back now.

**Minimal reproduction project:**
—

**Comment by dalexeev** [comment]
Still reproduced in 4f298237b.

**Comment by KoBeWi** [comment]
Can't reproduce in alpha 8
@dalexeev Can you test again?

**Comment by dalexeev** [comment]
Can't reproduce.
