### ISSUE TITLE
Ability to easily extend gd scripts

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4584]
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):
Currently when I want to extend some script that is attached to a scene I need to make a lot of quite tiring (in the long term) steps. 
1. Create new text file.
2. Find path to the file I want to extend
3. Write proper 'extend' line in new scipt
4. Remove 'base' script from a node that should use extended script.
5. Attach 'extended' script to a node 
6. Reset all exported variables of the script.

It would be so incredibly easier if Godot editor could do all this for me (button like 'new Extended script'/'Extend'). We don't even need new button, when I want to create new script for a node I'm clicking:
![newscript](https://cloud.githubusercontent.com/assets/6129594/15098020/0e869242-1530-11e6-88cd-a4748e7caad9.png)
And then popup with question about file location cames out. 
It would make perfect sense for me if the same could happen when I'm clicking this button on a node that already have a script, just this time 'extends path/2/parent/script.gd' line would be filled automatically.
**Related issue:** https://github.com/godotengine/godot/issues/4585

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by kubecz3k** [comment]
I think this issue is related to plugin system since currently extending a custom plugin is executed in exactly the same painful way. That's why I'm  thinking it should be considered before releasing 2.1

**Comment by kubecz3k** [comment]
I think this issue is related to plugin system since currently extending a custom plugin is executed in exactly the same painful way. That's why I'm  thinking it should be considered before releasing 2.1.

**Comment by LeonardMeagher2** [comment]
It would be nice if the "inherits:" section when creating a script just accepted a path as well as a class name, and had a little file browser button next to it, but it still defaulted to the Node type of the current node.

**Comment by bojidar-bg** [comment]
@LeonardMeagher2 Well, I don't think there is another way to do this :smile: 

Actually, we might have two buttons, one for selecting a class and one for script file, or we might have a new dialog that merges both of those ideas.

**Comment by MarianoGnu** [comment]
Copypaste from #4584 since same proposal fixes both issues:

I belive an option on contextual menu is enought for this
If no script:
-create script
If has script
-edit script
-extend script

This should not only work for scene instance, but for every node with a script assigned

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by kubecz3k** [comment]
In general I wrote external plugin which can be eventually used to solve this issue, it's available in asset store but it's implementation is not perfect since I dont have ability to add an entry under right click button (https://github.com/godotengine/godot/issues/6128).

**Comment by vnen** [comment]
I think this is now solved by #20233.
