### ISSUE TITLE
Deleting or moving a file causes the FileSystem browser to jump to the res:// directory

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#45842]
**Godot version:**
3.2.4 RC 1

**OS/device including version:**
Windows 10

**Issue description:**
Deleting or moving a file causes the `FileSystem` browser to jump to the `res://` directory.
This is a regression from 3.2.4 Beta 6.
The `FileSystem` should stay in the same folder when something is deleted or moved.

**Steps to reproduce:**
1. Create some nested sub-folders.
2. Delete or move the most deeply-nested folder.
3. Watch the `FileSystem` jump to the `res://` directory.

**Minimal reproduction project:**
[Deletion Bug.zip](https://github.com/godotengine/godot/files/5948995/Deletion.Bug.zip)

**Comment by gongpha** [comment]
This issue was caused by #45233. to fixes #45229 that when removed a folder. The above file path still points to the deleted folder. And when trying to import a new resource to a deleted directory. The error occurred.

**Comment by YeldhamDev** [comment]
It's not really bug. You can delete multiple items from different places at once, and since there's no way to tell when this happens, defaulting to the root directory seemed like a decent choice. But I can change it to place the path where the last selected item was, if this is desirable.

**Comment by Error7Studios** [comment]
> I can change it to place the path where the last selected item was, if this is desirable.

Yes, please change it to stay in the current folder path.
The current behavior is extremely annoying.

**Comment by Zireael07** [comment]
@Error7Studios: What if you deleted stuff from several directories at once? What would "current folder path" be?

**Comment by Error7Studios** [comment]
> What if you deleted stuff from several directories at once? What would "current folder path" be?

As Yeldham suggested, the folder containing the last selected item in that case.

**Comment by YeldhamDev** [comment]
Small correction: It will be the first selected item's path, as the path doesn't change once multiple items are being selected.

**Comment by Error7Studios** [comment]
Ah. That's still good.
