### ISSUE TITLE
Mouse press delay 

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#45840]
**Godot version:**
3.2.4 rc 16c7a3b1b

**OS/device including version:**
Mac OSX MacBook Pro 2015 

**Issue description:**
InputEventMouseButton has small delay before event.pressed is registered
Compared to InputEventKey .pressed which is correct/instant

**Minimal reproduction project:**
Try drawing a quick stroke using mouse press, then an identical stroke using key press.  the beginning of the stroke has a delay/less points recorded on mouse press 

[mouse_delay.zip](https://github.com/godotengine/godot/files/5947543/mouse_delay.zip)

Small video of the issue
https://user-images.githubusercontent.com/24432677/107295275-ea2ab880-6a23-11eb-8ccc-fd980b33242a.mov

Delay becomes more obvious with a lower framerate limit:
https://user-images.githubusercontent.com/24432677/107301277-0d5b6500-6a30-11eb-8e1a-32d2191b70f4.mov

**Comment by bruvzg** [comment]
I can't see any difference. Are you using external mouse or trackpad? Also, what's mouse polling rate is set to? AFAIK there's no built-in way to set/get it on macOS, but software from the mouse manufacturer should be able to change it. macOS usually handle "gaming" mice with high polling rate really poorly, if you are using one of these try setting polling rate to 500 HZ or lower.

**Comment by HEAVYPOLY** [comment]
@bruvzg I'm using a wacom intuos tablet.  The strange thing is that replacing InputEventMouseButton.press with InputEventKey.press fixes the delay.

**Comment by Calinou** [comment]
@HEAVYPOLY Try calling `Input.set_use_accumulated_input(false)` in any script's `_ready()` function.

**Comment by HEAVYPOLY** [comment]
Getting the same result with Input.set_use_accumulated_input(false). Still perplexed why BUTTON_RIGHT and KEY pressed as expected but BUTTON_LEFT doesn't

**Comment by Calinou** [comment]
**OS:** Linux
**Display:** 144 Hz (V-Sync enabled)
**Mouse:** Logitech G901 Lightspeed in wireless mouse with 1000 Hz polling rate

I can't reproduce this on 3.2 Git ecf432abc.

First row has strokes drawn using the mouse's left button, second raw has strokes drawn using the space bar:

![image](https://user-images.githubusercontent.com/180032/107404516-a8bf0980-6b06-11eb-800a-d733a84869d5.png)

**Comment by HEAVYPOLY** [comment]
@Calinou I've found that lower framerate makes it more pronounced, can you try with project settings > debug > force FPS set to 10fps?

**Comment by Calinou** [comment]
@HEAVYPOLY This is with FPS forced to 10 and V-Sync disabled:

![image](https://user-images.githubusercontent.com/180032/107410177-3aca1080-6b0d-11eb-8f67-60db6cdc2859.png)

Mouse strokes on the top row, keyboard strokes on the bottom row.

**Comment by HEAVYPOLY** [comment]
This is what I get with 20FPS forced.

My input polling is linked to FPS...looks like yours is independent for some reason..
<img width="943" alt="image" src="https://user-images.githubusercontent.com/24432677/107410695-7c819980-6ac2-11eb-9f95-dac290e52b95.png">

**Comment by HEAVYPOLY** [comment]
and with 144forced fps, not too noticeable:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/24432677/107410977-d5e9c880-6ac2-11eb-875f-6b0f671ed955.png">

**Comment by Calinou** [comment]
This issue is likely macOS-specific, but I don't have macOS hardware to test it.

**Comment by HEAVYPOLY** [comment]
It's happening on windows, android and ios too...input frequency is linked to FPS

on linux polling rate is independant?

**Comment by HEAVYPOLY** [comment]
err is it possible to try with a lower polling rate on your logitech mouse?

**Comment by bruvzg** [comment]
I have disconnected points in the similar manner, polling rate is probably the same. But still no lag with mouse. Sometimes it happens with the keyboard input (on the screenshot tho only missing stroke part is marked with blue).

![Screenshot 2021-02-09 at 20 43 29](https://user-images.githubusercontent.com/7645683/107412127-fe4fe200-6b17-11eb-92c3-506862ff9dfa.png)

**Comment by Calinou** [comment]
> err is it possible to try with a lower polling rate on your logitech mouse?

I can't find a way to decrease the mouse polling rate on Fedora, sorry.

**Comment by HEAVYPOLY** [comment]
ok found another interesting thing.  I plugged in a mouse and the first point is registered while trackpad misses the first point.

On top of that, mouse right seems to be more responsive than mouse left

**Comment by HEAVYPOLY** [comment]
https://user-images.githubusercontent.com/24432677/107414721-3f6bd600-6ac7-11eb-88d3-84ad0412137a.mov

**Comment by HEAVYPOLY** [comment]
This video has sound and prints to show and hear the click delay left vs right
https://user-images.githubusercontent.com/24432677/107422599-14d24b00-6ad0-11eb-8baa-2ce8c49bcc71.mov

**Comment by HEAVYPOLY** [comment]
Arghh... it was a window snapping app stealing left mouse input on Mac.  I remember noticing it on windows also, maybe something similar.  I will do some more testing on windows and report back.  Sorry for the non Godot bug

**Comment by HEAVYPOLY** [comment]
Tested on windows and no delay.  Sorry for the incorrect bug and thanks for helping me test.  Closing now.

**Comment by matthew-dean** [comment]
Was the mouse click delay cause ever discovered? New to Godot and I've been banging my head against the wall why Godot can't seem to capture / log any mouse events without nearly a half-second delay, whereas key presses are instant. I've tried adding / removing from input map, checking unhandled and handled events... it's like Godot just doesn't know about the mouse until much later.

**Comment by matthew-dean** [comment]
Ohhh thank goodness, I think I finally found [the culprit](https://github.com/godotengine/godot/pull/104644). I think the way that this code holds onto mouse events and then regenerates them is the source of mouse left-button input delays on macOS. I downgraded Godot Engine from 4.5.1 to 4.4.1 and mouse clicks are instantly registered now! Hopefully I'll be able to submit a proper bug report, but I just wanted to record this in case someone else is trying to understand why mouse clicks just have a massive input delay no matter what you do on macOS starting in Godot 4.5. If you're using the mouse for clicking on a GUI you'd probably never notice it; but if you're using it as, say, a fire button then it's painfully obvious.

**Comment by bruvzg** [comment]
> I think I finally found https://github.com/godotengine/godot/pull/104644.

This code is only called when a native popup menu is directly opened (e.g, right click menus), which is never used in the editor (all such menus use custom menu, only main menu is native). So it can't have any effect on this issue.

**Comment by Calinou** [comment]
The issue is being tracked in https://github.com/godotengine/godot/issues/109264.
