### ISSUE TITLE
get_node_data returns a string with XML entities for e.g. &#039;

### ISSUE THREAD

**Issue by skinkie** [godotengine/godot#45841]
**Godot version:**
Godot Engine v3.2.3.stable.custom_build

**OS/device including version:**
Linux, GLES3

**Issue description:**
When using get_node_data() on an XMLParser.NODE_TEXT the "string" contents is returned, I would expect the UTF-8 contents here. Hence XML-entities such as &#039; or &quot; should have been resolved to UTF-8.

**Steps to reproduce:**
Open any XML document with special characters.

It seems in the current repo there is already a function XMLParser::_replace_special_characters, which does not seem to do what I would expect.

https://github.com/godotengine/godot/blob/3.2/core/io/xml_parser.cpp#L113

**Comment by akien-mga** [comment]
Could you clarify why you expect `'` and `"` to be converted to XML entities?

**Comment by skinkie** [comment]
@akien-mga actually the opposite. &quot; gets converted to ", but &#039; does not get converted to '.

**Comment by akien-mga** [comment]
It's simply not included in https://github.com/godotengine/godot/blob/3.2/core/io/xml_parser.cpp#L549-L553

**Comment by skinkie** [comment]
I don't think it can be included as fixed list. The ```&# number ;``` pattern should be recognized and replaced.

**Comment by akien-mga** [comment]
Then it should be done after this:
https://github.com/godotengine/godot/blob/398a625a9f37fe6e45a5da075f8796d26378004d/core/io/xml_parser.cpp#L63-L71

**Comment by skinkie** [comment]
It is not entirely trivial. For inspiration: https://github.com/leethomason/tinyxml2/blob/master/tinyxml2.cpp#L417

**Comment by akien-mga** [comment]
I wouldn't bother with full UTF-32 support, simply supporting the ASCII table should already be sufficient for your use case, and that should be easy to implement in a few lines.

**Comment by skinkie** [comment]
For ascii it something like below in the in case specialChar == -1.

```cpp
const char *p = &origstr[pos + 1];
if (p[0] == '#') {
        newstr += (origstr.substr(oldPos, pos - oldPos));
        int endPos = origstr.find(";", pos) + 1;
        if (p[0] == '#') {
                string value;
                int valueInt = 0;
                if (p[1] == 'x') {
                        /* hex entities */
                        value = origstr.substr(pos + 3, (endPos - pos) - 3);
                        valueInt = std::stoi (value, nullptr, 16);
                } else {
                        /* decimal entities */
                        string value = origstr.substr(pos + 2, (endPos - pos) - 2);
                        valueInt = std::stoi (value, nullptr, 10); 
                }       
                if (valueInt > 10 && valueInt < 255) {
                        newstr += (char) valueInt;
                }       
        }       
                        
        pos = endPos; 
} else {
        newstr += (origstr.substr(oldPos, pos - oldPos + 1));
        pos += 1;
}       
```

**Comment by HenryWConklin** [comment]
Looks like there's a method in ustring to do this, but it also doesn't handle the `&#num;` entities. Would it be best to fix it in ustring and change XMLParser to use that?
https://github.com/godotengine/godot/blob/master/core/string/ustring.cpp#L3883

**Comment by skinkie** [comment]
@HenryWConklin I would then take the UTF32 approach, implement everything not just the ascii stuff.

**Comment by akien-mga** [comment]
> Looks like there's a method in ustring to do this, but it also doesn't handle the `&#num;` entities. Would it be best to fix it in ustring and change XMLParser to use that?

It does handle them in the ASCII range:
https://github.com/godotengine/godot/blob/master/core/string/ustring.cpp#L3889-L3912

**Comment by HenryWConklin** [comment]
I started working on this, and it looks like we'd need to add a check to restrict it to ASCII anyway so I'm just going to leave it open to the full `char32_t` range
