### ISSUE TITLE
Calling Self not working properly?

### ISSUE THREAD

**Issue by TheKnittedAcorn** [godotengine/godot#45866]
**Godot version:**

Godot Engine v4.0.dev.calinou.06ae14dd8

**OS/device including version:**

Win10 Home x64 desktop PC

**Issue description:**

New to GDS. Set up to do a tutorial or two with 4.0.

One line of code giving me resounding issues, in which a Timer needs to call on **self.**

As you can see from the screenshot, I did a setup in the stable build of Godot 3.2.3 of the same tutorial with the exact same code, and it worked perfectly fine.

![errorsgalore](https://user-images.githubusercontent.com/78849449/107493932-06714700-6b43-11eb-8d99-bb17251a6055.jpg)

As you can see, the 4.0 version is bugging out pretty badly. For some reason I'm not even seeing a list of methods and Node2D.tscn isn't properly indicated in the FileSystem? Am I missing something? Am I crazy? Is there some new-fangled thing I'm not finding?

**Steps to reproduce:**
- Make Node2D
- Child Sprite2D and Button to Node2D
- Child Timer to Sprite 2D
- Add Signal "pressed()" to Button and connect to Sprite 2D
- Add script as written to Sprite 2D:

extends Sprite2D

var speed = 400
var angular_speed = PI

func _process(delta: float) -> void:
	rotation += angular_speed * delta
	var velocity = Vector2.UP.rotated(rotation) * speed
	position += velocity * delta
	
func _on_Button_pressed():
	set_process(not is_processing())
	
func _ready():
	var timer = get_node("Timer")
	timer.connect("timeout", self, "_on_Timer_timeout")
	
func _on_Timer_timeout():
	visible = not visible

**Minimal reproduction project:**

[Godot Project 01.zip](https://github.com/godotengine/godot/files/5957295/Godot.Project.01.zip)

**Comment by pycbouh** [comment]
In 4.0 there is a new version of GDScript and signals are no longer connected with strings. Functions are also first class citizens now and can be passed by reference as a Callable object.

Read more in the old PR https://github.com/godotengine/godot/pull/39093
