### ISSUE TITLE
Same code and godot versions threw different errors and crashes on different PCs

### ISSUE THREAD

**Issue by JezSonic** [godotengine/godot#45867]
**Godot version:**
3.2.3.stable

**OS/device including version:**
1. Windows 10, 64bits, GLES2, i3
2. Windows 10, 64bits, GLES2, AMD Ryzen
3. GithubActions (ubuntu 18.04)

**Issue description:**
For each PC and Github Actions we have used the same version of game code and we think it's issue with the engine
On PC nr. 1 game works everything works well except one thing. Game wants to load txt file with exists, but there's no code that's used to load that file
On PC nr. 2 godot loads not-existing plugin and throws errors in gdnative code (https://github.com/LennyPhoenix/GodotDiscordSDK/tree/activities) then it tries to load some csharp scripts (in standard godot version) and finally editor crashes while loading the project.
On github actions we use headless version of godot and exported game (workflow file is here https://github.com/NewDEV-github/Foxy-Adventure/blob/develop/.github/workflows/godot-build.yml) just crashes after calling `_init()` function in game singleton and before calling `_ready()` function in the same singleton. There's no code error, cause when i export game from pc nr. 1 it works, exports from other PCs - doesn't work

Also there are output logs from [pc nr. 2](https://github.com/NewDEV-github/Foxy-Adventure/issues/37) and [GithubActions export](https://github.com/NewDEV-github/Foxy-Adventure/issues/36)

Github Actions builds are downloadable for pc platforms by artifacts from action runs

**Steps to reproduce:**
I don't know, for 1 and 2 PC there have happened different errors with the same engine version and the same game code version

**Minimal reproduction project:**
Run our game from [develop branch](https://github.com/NewDEV-github/Foxy-Adventure/tree/develop)

**Comment by JezSonic** [comment]
ok, so github actions error was by my fault, but still there are 2 different errors on the same godot and code version and by those errors game can't be programmed by my friend on his pc cause it crashes just after running the game, even main scene can't be runned because of this

**Comment by menip** [comment]
Could you produce a smallest possible project that has the same error?

**Comment by JezSonic** [comment]
I'll try to make one but I won't promise

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
