### ISSUE TITLE
Autocompletion grabs focus somewhere but it is hidden.

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#45860]
**Godot version:**

3.2.4 rc 5cf55fe905

**OS/device including version:**

Kubuntu 20.10

**Issue description:**

Autocompletion grabs focus somewhere but it is hidden.
so arrow up/down looks not responding.
but <kbd>Enter</kbd> works like autocompletion working.

**Steps to reproduce:**
1. type `get_t` and see if autocompletion works
2. type `yield(` and then type `get_t`

![autocomplete](https://user-images.githubusercontent.com/8281454/107450641-01cf8180-6b89-11eb-8012-81a0cbfd7abb.gif)

**Minimal reproduction project:**

**Comment by volzhs** [comment]
probably regression from #45169? cc @fmazan

**Comment by fmazan** [comment]
In current 3.2 I have reproduced the bug and I am pushing a fix in a moment.

In master, although yield has been replaced by await and the syntax has changed, another kind of autocompletion bug is happening where it does not even offer any hints inside function calls. This might be related to the gdscript overhaul.

**Comment by akien-mga** [comment]
Fixed by #45878.
