### ISSUE TITLE
is_colliding() not working properly

### ISSUE THREAD

**Issue by mg979** [godotengine/godot#45865]
**Godot version:**
3.2.3-mono

**OS/device including version:**
Windows 10, laptop with NVIDIA GeForce GTX 1050, Intel Core i5-8300H

**Issue description:**
RayCast `is_colliding()` isn't working properly

**Steps to reproduce:**

I was following [this tutorial](https://godottutorials.pro/rpg-godot-tutorial-part-2/) and got to the part where I have to make a chest and have it interact with the player. Instead of using an `Area2D` node I'm using a `StaticBody2D`.

So I have a chest (StaticBody2D) with a CollisionShape2D and a sprite. The chest has this script:

```gdscript
extends StaticBody2D

var gold = 5

func on_interact(player):
	print('interacted with chest')
	player.give_gold(gold)
	queue_free()
```

The player has this (partial):

```gdscript
func _process(delta):
	if Input.is_action_just_pressed("interact"):
		try_interact()
		try_interact()


func try_interact():
	rayCast.force_raycast_update()
	rayCast.cast_to = facingDir * interactDist
	print("try interact: " + str(rayCast.cast_to.x) + " " + str(rayCast.cast_to.y) + " " + str(interactDist))

	if rayCast.is_colliding():
		print("rayCast colliding")
		if rayCast.get_collider() is KinematicBody2D:
			rayCast.get_collider().take_damage(damage)
		elif rayCast.get_collider().has_method("on_interact"):
			rayCast.get_collider().on_interact(self)
```

You can see that I call `try_interact` two times, because the first time it just doesn't work, and the second time it does.

![godot1](https://user-images.githubusercontent.com/26169924/107476132-8dd7ae00-6b75-11eb-8f94-26d16220fb32.gif)

---

But if I approach the chest from the upper side, it works, and `try_interact` is called two times:

![godot2](https://user-images.githubusercontent.com/26169924/107476373-fe7eca80-6b75-11eb-9263-8142249e78d6.gif)

and I don't even think it should, because the second time the object should be destroyed already.

---

If I remove `rayCast.force_raycast_update()` it fails also at the second call:

![godot](https://user-images.githubusercontent.com/26169924/107477789-b1502800-6b78-11eb-8555-7da9020605cb.png)

but it will succeed at the second call if I call `try_interact` once:

![godot](https://user-images.githubusercontent.com/26169924/107478154-4bb06b80-6b79-11eb-8831-119a3ad4b168.png)

**Minimal reproduction project:**
[tutorial-2d-rpg.zip](https://github.com/godotengine/godot/files/5956387/tutorial-2d-rpg.zip)

**Comment by Xrayez** [comment]
Have you tried calling `try_interact()` in `_physics_process()` over `_process()`? Any physics interactions should be done in `_physics_process()` (also previously called `_fixed_process()`) to make those operations safe. `_process()` is called as fast as possible (every frame), so it's not recommended to use in a physics context.

**Comment by mg979** [comment]
Yes I tried too, the only difference is that `rayCast.force_raycast_update()` is not needed. But I still need to press the activation key 2 times from any direction that isn't the upper one (north).

**Comment by KoBeWi** [comment]
Use `force_raycast_update()` AFTER changing `cast_to`.

**Comment by mg979** [comment]
> Use `force_raycast_update()` AFTER changing `cast_to`.

Ok that worked thanks. I still think that there's a bug somewhere because it defies every logic thar RayCast2D fails for some directions and not for others. In this situation basically you're forced to do `force_raycast_update` and I don't think it can be considered normal.

**Comment by KoBeWi** [comment]
You can enable visibility of collision shapes in Debug menu to see the raycasts. I didn't check the project, but I guess the initial position of your RayCast just accidentally aligned for colliding or it's due to some offset or something.

btw for this specific case it would be more suited directly query the physics space:
```
get_world_2d().direct_space_state.intersect_ray(from, to, [], 1)
```
RayCasts aren't really intended to be changed dynamically, especially if you want to check the collision right after change.

**Comment by mg979** [comment]
> just accidentally aligned for colliding 

I set the raycast to `enabled` and it is pointing down. If I disable it, it becomes gray but it's still pointing down. Since the only direction that worked was from the upper side, maybe it's not a coincidence. Anyway I don't understand much of these things and I don't feel like investigating what to me is still a very strange behaviour.

**Comment by mg979** [comment]
Btw, by enabling visibility of colliders, I can see what happened. The raycast was active and pointing down, when I interact the first time the facing changes, but apparently the `is_colliding` function ignores the change unless you force update. From the upper side, this has no effect because the raycast was already colliding.

**Comment by KoBeWi** [comment]
> apparently the is_colliding function ignores the change unless you force update.

The collision is updated on the next physics frame, changing the raycast doesn't do it automatically. `force_raycast_update` just provides an option to update the collision if you really need it.

**Comment by mg979** [comment]
Thanks for the help.

Eventually I moved `rayCast.cast_to` in the `_input()` function and I don't need `force_raycast_update`.
