### ISSUE TITLE
Arrays can not be resetted in the inspector, will not work if you create them with 'export' in gdscript, but not assign them manually in the inspector

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#4586]
wow, do i have the honor of being the 1000th issue? 

I just noticed that Array type variables can not be resetted, like other types of variables in godot:
![arrayss](https://cloud.githubusercontent.com/assets/6495061/15098428/9146f456-1535-11e6-972c-63955a44dcba.png)

Whats worse is that if you make an array in gdscript like this:

```
export var myArray = [1,2,8,4]
for test in myArray:print('whyy',test)

```

and forget to give it any values in the inspector, the array will simply be empty. The for loop will not print at all!

In essence array type variables have no default value that they can be resetted to. They do not work at all if you have not assigned anything to them in the inspector, while they have the export tagged in gdscript.

This is inconsistent with strings, ints, floats and what have you. :) 

So this is a problem with them in both gdscript and the inspector.

**Comment by reduz** [comment]
This is not a bug, arrays and dictionaries are shared, while other datatypes are not.
Maybe what should be added is a popup menu on an array property so you can:
a) make a new, empty array
b) make the array unique? (do a copy)

otherwise I'm not sure if anything else can be done

**Comment by AWKgamedev** [comment]
I'm having trouble with exported arrays too, right now they aren't useful at all since they aren't unique.
I think they should be unique by default or at least have a "make unique" button since the only reason why I would want an exported array is to have different values per instance.

**Comment by Jummit** [comment]
I think this is behaving as op wants now. Arrays can now be reset.

**Comment by akien-mga** [comment]
Indeed, this works fine in 3.2 at least.
