### ISSUE TITLE
Android export

### ISSUE THREAD

**Issue by Doniyor-GTU** [godotengine/godot#45869]
**Godot version:**
Godot 3.2.4 beta 6 

**Issue description:**
I exported my project as apk and trying to install it but I am getting a parsing error on my mobile device.
On versions 3.2.3 and 3.2.2 there is no problem with the same project.
Also I tried to make a new simple project and export to android, again the same problem.

**Comment by volzhs** [comment]
check this #45606 to see if it's the same issue

**Comment by Doniyor-GTU** [comment]
@volzhs I think the issue is not same. When I try to install with adb i get this message:
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

**Comment by Calinou** [comment]
@Doniyor-GTU What does the path of your project look like? Make sure it doesn't contain accented characters: https://github.com/godotengine/godot/issues/18222

**Comment by Doniyor-GTU** [comment]
@Calinou I am sure that it doesn't contain any accented characters, because I developed my project on Godot 3.2.2 and there was no problem with exporting and running on my device, everthing worked well. Then I needed an app bundle in order to publish on Play Store and downloaded Godot 3.2.4 beta 6. Because of changing the version a few errors occured and I fixed them. Also, I've installed relative versions of export template and android build. 
    While doing theese steps I didn't chancge the names or path of anything. So there should be no problem with characters. 
    When I change the version from 3.2.4 beta 6 to 3.2.2 it works again well.

**Comment by Calinou** [comment]
@Doniyor-GTU The Android export process has changed in 3.2.4 betas, see the new documentation: https://github.com/m4gr3d/godot-docs/blob/957279271079197575a615c2637f3785da242307/getting_started/workflow/export/exporting_for_android.rst

**Comment by m4gr3d** [comment]
@Doniyor-GTU Which machine (Linux, mac, or Windows) are you trying to export from.

> Also I tried to make a new simple project and export to android, again the same problem.

Can you provide the sample project you used to replicate the issue as well as its `export_presets.cfg` file.

**Comment by akien-mga** [comment]
No answer, so closing.
