### ISSUE TITLE
Joint movement is not equivalent.

### ISSUE THREAD

**Issue by YooPita** [godotengine/godot#45875]
**Godot version:** 3.2.3

**Issue description:**
I'm trying to throw a ball connected to the player by rope (I use joints). In general, the idea works, there is only a problem that I can't set the length of the rope initially (the distance between the joints). I expected that the ball throw would be equivalent in any direction and the joints would behave unambiguously. And this is really so if we make a throw exactly along the axis. But if we deviate a little, the ball starts flying to the side.
Here's how it works on video: https://imgur.com/tzjcoIe
Here is a video demonstration where I multiplied the push force by 5, 10 and 20: https://imgur.com/a/fi0v0V9

I made a test scene where I placed the prefabs with different turns symmetrically:
![image](https://user-images.githubusercontent.com/34219009/107541881-a3ca8a80-6bd8-11eb-9b30-8b32259c4cdb.png)

**Steps to reproduce:**
Create objects and link sequentially. (As shown in the screenshot)
![8twgto2wcwga](https://user-images.githubusercontent.com/34219009/107541352-18e99000-6bd8-11eb-8281-c6376cfd16e6.png)
Then apply force: ball.apply_central_impulse((ball.get_global_transform().origin - get_global_transform().origin) * 5)

**Minimal reproduction project:**
[balltest.zip](https://github.com/godotengine/godot/files/5959830/balltest.zip)

**Comment by YooPita** [comment]
I wanted to find alternative physics engines and found that Godot has more than one physics engine. I'll clarify that I used the default one.
If we change GodotPhysics, then the result will be like this:
![image](https://user-images.githubusercontent.com/34219009/107544150-fa38c880-6bda-11eb-8548-fec784382e94.png)

This result is already similar to the truth. It turns out that the Bullet works worse? Which one is better to use?

**Comment by Calinou** [comment]
> Which one is better to use?

There is no "better" choice, it depends on your situation and the bugs you're running into.

**Comment by YooPita** [comment]
I tried GodotPhysics and it only added persistent errors to the console stating that the physics engine is busy + checking that the KinematicBody is on the ground stopped working correctly.
Maybe somewhere the features of working with GodotPhysics are described... Bullet was the best option, but the problem with physics didn't allow me to realize my idea :(

**Comment by pouleyKetchoupp** [comment]
When you setup a chain of joints like this, in order to get more stability you need to make sure each subsequent object has equal or lower mass compared the previous one.

In your test project, the cones have a very low mass and it seems to cause the stability problems. I've tried to set them to 1 and it behaves much better with both physics engines. You can try different combinations depending on what you need to achieve, but try to keep their mass at least equal to the ball's mass for the best results.

Let me know if that solves your issue!

**Comment by YooPita** [comment]
@pouleyKetchoupp Hey! This is a good explanation of how joint physics works. But as you can imagine, the chain that holds the ball cannot weigh more than the ball itself. In my chain, the last object definitely weighs more than the very first one sometimes. In general, the bug doesn't fix it and doesn't solve my problem either. But still, thank you very much for your answer!

**Comment by pouleyKetchoupp** [comment]
@YooPita Do you have a specific reason why you need the ball to weigh more than the chain elements? I know it looks like it should, but in my experience, when setting up a chain like that the behavior is fine even if weights are not very realistic and you don't really see a difference visually. So in practice what really matters is to set them in a way that makes things more stable.

**Comment by YooPita** [comment]
@pouleyKetchoupp I want the player to watch him when I throw the ball. That is, the ball is pulling for the hero. Visually, this will have a different effect if the player is heavier. But I'll try to see. This behavior may be unrealistic, but may be better for gameplay.

**Comment by pouleyKetchoupp** [comment]
@YooPita If what you mean is you want the player to be pulled while throwing the ball in some cases, it seems to work well with these settings:
Ball mass: 0.61 (didn't change)
Segment 1: 1 (increased for stability)
Segment 2: 1 (increased for stability)

Then depending on the player's mass, they get dragged while throwing the ball. With a force of 20, a player with mass 10 will not move, while a player with mass 5 will be pulled pretty hard.

Can you try in your project and let me know what problems you encounter in case it doesn't work for you?

**Comment by YooPita** [comment]
@pouleyKetchoupp Of course, thanks. Thanks for your attention, I didn't expect to receive such feedback.

**Comment by pouleyKetchoupp** [comment]
You're welcome! I'm closing this issue for now. Feel free to re-open if you encounter specific problems with the setup I suggested.
