### ISSUE TITLE
HTTPClient request_raw METHOD_GET not working.

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#45877]
**Godot version:**
3.2

**OS/device including version:**
Windows 10, Google Chrome

**Issue description:**
You see I'm currently helping working on a [Firebase API for Godot](https://github.com/GodotNuts/GodotFirebase). The work is going smoothly except for one thing... In HTML builds, it's impossible to `METHOD_GET` any sort of data with `HTTPClient`. When an attempt is made to `request_raw`, the following prints in the console.
```
Failed to send data per XHR: null pointer
```

**Steps to reproduce:**
1. Create an HTTPClient.
2. Connect to a host.
3. After successfully connecting, request data from a url.
4. `ERROR`
_Note: This only seems to happen in HTML builds._

**Minimal reproduction project:**
[HTML Issue.zip](https://github.com/godotengine/godot/files/5961528/HTML.Issue.zip)
Just run the project in HTML and pay attention to the console output. Numbers are the `HTTPClient`'s status.

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
Thanks for reporting this issue, this was indeed a bug in how Godot handled requests with empty body. It should be fixed now (and in upcoming `3.2.4 RC2`)
