### ISSUE TITLE
Anchor value other than Begin crashes game when run

### ISSUE THREAD

**Issue by her001** [godotengine/godot#4588]
**Operating system or device - Godot version:**
Arch Linux 64 bit - Godot master branch (8a45936)
git bisect reveals that the issue should effect everything after (and including) 0e8a8d2, which is only in the master branch (was added in #3997, is not in 2.0/Steam).

**Issue description**:
When changing any Control to have an Anchor on anything other than "Begin," the game crashes when run.

I expect the game to run with the Anchor in the new position.

**Steps to reproduce:**
With a Control in the scene tree, change any Anchor from "Begin" to any other value and attempt to run the game.

Alternately, attempt to run a game which uses anchors other than "Begin," which should crash, but should run after changing those values to "Begin."

**Link to minimal example project**:
The official [drag and drop demo](https://github.com/godotengine/godot/tree/master/demos/gui/drag_and_drop) has the root Control node with Anchors set to "End," so it will not run, but will after changing them to "Begin."

**Comment by bojidar-bg** [comment]
Uh, maybe I broke it? I'll look into it soon :smile:

**Comment by bojidar-bg** [comment]
@her001 ~ Unfortunately, I'm unable to reproduce on master (as of today)... I'll try a bit more though

**Comment by her001** [comment]
@bojidar-bg It wasn't happening for me until I built from a clean source tree. It also, if I remember correctly, happened with either the normal build or a debug build.

**Comment by bojidar-bg** [comment]
@her001 BTW, can you try reverting the changes in that commit and the following, and testing again, since I'm still not sure that the problem is in my code..?

**Comment by vnen** [comment]
I get a segfault with current head. Then I tried with a debug build to get a backtrace but then it doesn't crash.

Here's what I have from the release_debug build:

```gdb
(gdb) bt
#0  __cxxabiv1::__dynamic_cast (src_ptr=0x0, src_type=0x17817f8 <typeinfo for Object>,
    dst_type=0x1683c60 <typeinfo for SceneTree>, src2dst=0)
    at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/dyncast.cc:50
#1  0x0000000000c42395 in Control::_set_anchor(Margin, Control::AnchorType) ()
#2  0x0000000000c54c73 in MethodBind2<Margin, Control::AnchorType>::call(Object*, Variant const**, int, Variant::CallError&) ()
#3  0x00000000013bc84e in ObjectTypeDB::set_property(Object*, StringName const&, Variant const&, bool*) ()
#4  0x00000000013f9361 in Object::set(StringName const&, Variant const&, bool*) ()
#5  0x0000000000fb991b in SceneState::instance(bool) const ()
#6  0x0000000000fbad5e in PackedScene::instance(bool) const ()
#7  0x000000000042978e in Main::start() ()
#8  0x000000000040c57d in main ()
```

So maybe it's from the cast introduced in #4007?

**Comment by her001** [comment]
@bojidar-bg If I revert those 2 commits (0e8a8d2 and bac875b, which rely on each other), the bug is not present.

**Comment by bojidar-bg** [comment]
@vnen ~ I get slightly different crash, but if it is indeed from the cast it would be nice :smile: 
@vnen Can you test with this patch?
````
@@ -1287,14 +1287,13 @@ void Control::set_anchor(Margin p_margin,AnchorType p_anchor, bool p_keep_margin
 
 void Control::_set_anchor(Margin p_margin,AnchorType p_anchor) {
        #ifdef TOOLS_ENABLED
-       SceneTree *st=OS::get_singleton()->get_main_loop()->cast_to<SceneTree>();
-       if (st && st->is_editor_hint()) {
+       if (is_inside_tree() && get_tree()->is_editor_hint()) {
                set_anchor(p_margin, p_anchor, EDITOR_DEF("2d_editor/keep_margins_when_changing_anchors", false));
        } else {
-               set_anchor(p_margin, p_anchor);
+               set_anchor(p_margin, p_anchor, false);
        }
        #else
-       set_anchor(p_margin, p_anchor);
+       set_anchor(p_margin, p_anchor, false);
        #endif
 }
````

**Comment by vnen** [comment]
@bojidar-bg no crash with your patch 😃

**Comment by bojidar-bg** [comment]
Ok, PR incoming (soon&trade;)!
