### ISSUE TITLE
Vulkan: ReflectionProbes don't show up and cause clustering artifacts instead

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#45895]
**Godot version:** `master` Git 89a43d9c2
This bug has been around at least since December 2020.

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 460.39)

**Issue description:**

Reflection probes don't display correctly and will exhibit clustering artifacts:

![ReflectionProbe clustering artifacts](https://user-images.githubusercontent.com/180032/107658407-64f30e00-6c86-11eb-9224-0d24ae7d11f4.png)

**Steps to reproduce:**

- Add a ReflectionProbe to a scene.

**Minimal reproduction project:** [test_reflection_probe.zip](https://github.com/godotengine/godot/files/5966428/test_reflection_probe.zip)

**Comment by barbaros83** [comment]
i get similar artifacts from the environment ss reflection option, its as if some faces become transparent, en some behave like bilboards

**Comment by Calinou** [comment]
@barbaros83 The SSR issue is already reported in https://github.com/godotengine/godot/issues/44539.
