### ISSUE TITLE
StreamPeerTCP - is_connected()

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#4590]
Is it possible to add some kind of keep alive signal to see when a connection has disconnected?

Right now "is_connected()" only recognize a disconnect when data is send.

Ubuntu 14.04 64bit ( Tested with "socat TCP:localhost:3560 -" )

**Comment by reduz** [comment]
Does not TCP have some kind of timeout for this?

**Comment by AlexHolly** [comment]
I testen my use case again and it looks like "is_connected()" now shows false on an disconnect maybe it was fixed with #4675.

**Comment by OvermindDL1** [comment]
@reduz: It does, but the timeout is 30 minutes on RFC spec as I recall (TCP is not designed for something like the Internet...), hence why near every TCP library for purposes like this have their own heartbeat (usually once a second to once a minute depending on the need for real-time or not where hearbeats are only sent if no data has been sent within the hearbeat timeframe and the connection is marked as 'dropped' if missing two heartbeats in order).  Just the act of sending a heartbeat when no data has been sent recently causes the TCP stack to test, but it may not returned dropped quickly (up to thirty minutes depending on how the OS is configured among other factors, hence why checking for two missed concurrent heartbeats, though if using 1second heartbeats then maybe 8 missed ones or even more).
