### ISSUE TITLE
The godot "editor" is too laggy

### ISSUE THREAD

**Issue by ScintillationGamesOfficial** [godotengine/godot#45917]
**Godot version:**
Godot 3.2.3 stable.mono

**OS/device including version:**
Windows 10/AMD Ryzen

**Issue description:**
I have put many nodes in the scene now (especially csg nodes) and now the godot is very laggy, other engines i have first worked didn't have this problem but due to some reasons I come on godot and I like godot now but it is very laggy

**Steps to reproduce:**
I have 2k textures for materials.
It only happened in this scene of project because there are many nodes ( i guess)
I putted a video .mkv in the zip file the fps in  the console is showing for my game's fps
[godot_lag.zip](https://github.com/godotengine/godot/files/5970390/godot_lag.zip)

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Many CSG nodes will lead to performance problems due to the dynamic nature of the CSG. Convert CSG output to static meshes to improve the situation.

**Comment by ScintillationGamesOfficial** [comment]
okay zireal07 thank you for your advice but how to do that?

**Comment by Zireael07** [comment]
https://github.com/godotengine/godot/issues/19232#issuecomment-476459435

**Comment by ScintillationGamesOfficial** [comment]
thank you zirael07 the mesh conversion works, i am closing this issue for now, i haven't tested it fixes lag or not

**Comment by ScintillationGamesOfficial** [comment]
Umm. It literally worked!! One last question, can I put unlimited mesh instances and godot engine will not lag?

**Comment by Calinou** [comment]
> One last question, can I put unlimited mesh instances and godot engine will not lag?

No, as each MeshInstance will result in a draw call (which takes up CPU time). If you want to render lots of static objects and save on draw calls, look into [using MultiMeshes](https://docs.godotengine.org/en/stable/tutorials/optimization/using_multimesh.html).

**Comment by ScintillationGamesOfficial** [comment]
I am making a city and there are different buildings still a lots of buildings are left. I am worried that my godot "editor" will lag again

**Comment by Calinou** [comment]
This issue tracker is meant to be used for bug reports only, not support questions. Please use other [community channels](https://godotengine.org/community) to ask support questions :slightly_smiling_face:
