### ISSUE TITLE
Vulkan: Enabling SDFGI slows down editor (+ crashes launching scene in Mono build)

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#45911]
**Godot version:**
[e5bb89c](https://github.com/godotengine/godot/commit/e5bb89cdd5e92fa6fdeff78aad08bf0cbfbcc692) (Mono build)

**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan

**Issue description:**
Enabling SDFGI in Enviroment causes slowdown of editor when turning camera around. Also lots of errors.

<details>
<summary>Errors:</summary>

>ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6586)
ERROR: Attempted to use an unused shader variant (shader is null),
   at: (.\servers/rendering/renderer_rd/pipeline_cache_rd.h:71)
ERROR: Condition "!pipeline" is true.
   at: draw_list_bind_render_pipeline (drivers\vulkan\rendering_device_vulkan.cpp:6379)

</details>

<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/2698825/107718951-18d8b580-6ce8-11eb-905e-2f9c0cec1417.mp4

</details>

Also, on Mono version launching with SDFGI causes launched scene to crash.
<details>
<summary>Errors:</summary>

>ERROR: Storage buffer supplied (binding: 1) is invalid.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:5152)
ERROR: Condition "!uniform_set" is true.
   at: draw_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:6454)
ERROR: Mono: FATAL ERROR '* Assertion at ..\mono\mini\debugger-agent.c:4175, condition `!tls' not met
 (in domain , error)', ABORTING! Logfile: 'C:\Users\George\AppData\Roaming/Godot/mono/mono_logs/2021-02-12_04.16.43_19360.log'.
   at: mono_log_callback (modules\mono\mono_gd\gd_mono_log.cpp:92)

</details>

[Error at opening the project](https://gist.github.com/Xartorx/72f6da1085341b40293b07e427b8fc10), but it doesn't happen very often.

**Steps to reproduce:**
Open project and enable SDFGI in Main scene.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/5969214/Test.zip)

**Comment by kimamb** [comment]
I get the same issues on a non-mono build.

**Comment by Calinou** [comment]
> Enabling SDFGI in Enviroment causes slowdown of editor when turning camera around.

This is currently expected since the SDF has to be generated when the camera is moving or rotating. We need to figure out a way to remove this stuttering, but it might not be easy.

**Comment by kimamb** [comment]
> > Enabling SDFGI in Enviroment causes slowdown of editor when turning camera around.
> 
> This is currently expected since the SDF has to be generated when the camera is moving or rotating. This is especially noticeable when the camera is moving at high speeds. We need to figure out a way to remove this stuttering (e.g. by capping the speed at which the SDF can be regenerated), but it might not be easy.

Yes, but it spews out errors which makes the output unreadable.

**Comment by Calinou** [comment]
Looking at the video, the slowdown isn't due to the SDF updating but due to the error spam in the console.

**Comment by kimamb** [comment]
> Looking at the video, the slowdown actually doesn't seem to be caused by the SDF updating rather by the error spam in the console. Minimizing the console might help a bit in this case, but probably not much.

Yes it does, at least for me.

Browsing the remote node tree is nearly impossible as well.

Curiously the errors don't appear if SDFGI is turned off when starting the game, and later is turned on. They only appear if the game is started with it on.

**Comment by Calinou** [comment]
@kimabjorkede Can you still reproduce this bug in the latest `master` branch or nightly builds?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
