### ISSUE TITLE
User imported 3D Collision Shapes only interact with primitives and not each other

### ISSUE THREAD

**Issue by thirite** [godotengine/godot#4591]
**Operating system or device - Godot version:**
Ver 2 Stable

**Issue description** (what happened, and what was expected):
3D collision shapes do not interact/collide unless at least one is an engine defined primitive. The same happens with kinematic bodies or rigid bodies. A custom shape can interact with collision shapes using primitives but not with any other user imported collision shapes.

**Steps to reproduce:**
Create a rigid body and give it a custom, imported collision shape. Instance a bunch at the same location. Notice they don't interact with each other.  

**Link to minimal example project** (optional but very welcome):

**Comment by Ace-Dragon** [comment]
Last I checked, the import window expects different keywords in order to create rigid-bodies as opposed to static-bodies.

What does your node tree look like?

**Comment by bojidar-bg** [comment]
I think there was a problem with tri-mesh (i.e `ConcaveCollsionShape`) vs tri-mesh collisions, but I can't find an issue about it.

**Comment by thirite** [comment]
@Ace_Dragon
Importing issues shouldn't be the problem, as the only thing I'm using from my imported .dae is the geometry for the collision shape/mesh. Everything else I made in Godot.

@bojidar_bg
I think that might be exactly it. I'll try to upload an example project showing the problem when I get a chance.

**Comment by slapin** [comment]
Well, there is no way to generate convex collision from mesh during import;
But you can create these in editor, probably that will work to some extent...

Checking collision code this type of collision should work.

**Comment by thirite** [comment]
> You can create these in editor
Would it be something as simple as copying the mesh data from what I imported (a convex shape, but imported as concave) to a new convex shape resource?

**Comment by reduz** [comment]
need to implement convex decomposition for triangle geometry, that will help a lot. Will be done for 3.0 though

**Comment by DimitriyPS** [comment]
Like everyone I am very much waiting for version 3.0 Godot. Most of all I hope to fix this bug (and then: https://github.com/godotengine/godot/issues/4831). And therefore I was most afraid that it is not fix. The request of the developers to comment on the situation.

**Comment by ghostfreeman** [comment]
Does this issue also affect the ability for custom meshes such as imported models from interacting with other imported meshes?

**Comment by thirite** [comment]
That's exactly what the bug is. Imported collision meshes (ie: meshes that are not primitives) only collide with primitives, and not other custom imported collision meshes.

**Comment by reduz** [comment]
duplicate
