### ISSUE TITLE
Ctrl + V shortcut isn't working on the visual script editor

### ISSUE THREAD

**Issue by Henrykado** [godotengine/godot#45916]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10 / Radeon Vega 3

**Issue description:**
I tried copying and pasting some nodes on the visual script editor to another place, but when 
i tried to paste it (ctrl + v), it didn't work, i even tried restarting Godot but the problem was still there, the only "copy and paste" shortcuts that work is "Ctrl + X" and "Ctrl + D"

**Steps to reproduce:**
Click a Node, Function, etc on the Visual Script editor.
Press Ctrl + X
Press Ctrl + V
or
Press Ctrl + C
Press Ctrl + V

**Minimal reproduction project:**
[Project.zip](https://github.com/godotengine/godot/files/5969586/Project.zip)

**Comment by jmb462** [comment]
Seems to be the same issue as #39039

PR has been proposed : #42143

**Comment by Gallilus** [comment]
#42143 is merged issue closed !?

**Comment by Chaosus** [comment]
This issue is about 3.x version where this bug still presents.

**Comment by akien-mga** [comment]
Fixed by #54629.
