### ISSUE TITLE
godot 4.0 bug in inspector not allowing to change properties and setting them at random

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot#45925]
**Godot version:**

downloaded from artifacts: 
https://github.com/godotengine/godot/pull/45922/checks?check_run_id=1887388674

**OS/device including version:**

OS: Solus
GPU: RX480
backend: Vulkan

At default light value of 1.0 its way too bright.
![Screenshot from 2021-02-12 16-02-57](https://user-images.githubusercontent.com/59711483/107785602-10669600-6d4d-11eb-856b-c37d1f6cdc14.png)

mesh isnt lighted properly, seems like something is casting a shadow on top of the sphere while nothing is above it
![Screenshot from 2021-02-12 16-03-38](https://user-images.githubusercontent.com/59711483/107785709-35f39f80-6d4d-11eb-82a0-7bbf4ad2e51d.png)

![Screenshot from 2021-02-12 16-04-02](https://user-images.githubusercontent.com/59711483/107785969-8cf97480-6d4d-11eb-8278-cd8f87487965.png)

the light gizmo is casting a shadow
![Screenshot from 2021-02-12 16-05-59](https://user-images.githubusercontent.com/59711483/107785991-9387ec00-6d4d-11eb-9ffa-eaaa84b68583.png)

the shadow of the sphere is transparent for some reason, the grid underneath the box the shadow is cast on is visible.
![Screenshot from 2021-02-12 16-06-19](https://user-images.githubusercontent.com/59711483/107786327-0db87080-6d4e-11eb-8178-2bf1302635c2.png)

**Comment by barbaros83** [comment]
forgot to upload minimal reproducable project
[Godot 4.0 test.zip](https://github.com/godotengine/godot/files/5972716/Godot.4.0.test.zip)

**Comment by reduz** [comment]
Seems unrelated to the PR linked, I suggest doing proper bisection to figure out what's going on

**Comment by barbaros83** [comment]
i download from the lastest artifacts from time to time, and couple of days ago these problems where not there, im not sure wich commit this issue is related to, but today when i downloaded it, i had these issues

**Comment by Calinou** [comment]
> the light gizmo is casting a shadow

This was already reported in https://github.com/godotengine/godot/issues/45109.

**Comment by barbaros83** [comment]
couldn't figure out which commit causes these issues, but i encountered something strange, when i select sphere on a meshinstance, and apply a material on it, it does really weird things, and for some reason emmision is set to on, and i cant deselect it.

**Comment by barbaros83** [comment]
at #45861 this commit everything still works as it was before, no weird glitches

**Comment by barbaros83** [comment]
#45879 this is the one that causes the problems, in the inspector, it forces some options on the material that i cant change, thats why it behaves weird @reduz
