### ISSUE TITLE
Test game closes on using ssl-enabled host.

### ISSUE THREAD

**Issue by mownier** [godotengine/godot#4593]
**Operating system or device - Godot version:**
Ubuntu 15.10 64-bit
branch: master
head: 8a45936

**Issue description** (what happened, and what was expected):
I have built the godot source using `$ scons platform=x11 openssl=builtin`. A test game closes upon connecting to an ssl-enabled host. Unfortunately, there's no error message info displaying on gdb. On `HTTPRequest` node, you can test this url `https://godot-ssl-test.firebaseio.com/.json`. Upon completion, it is expected that you should receive a response:
```json
{"test":{"message":"ok"}}
```
On the other hand, no problem upon requesting valid url with `http` as the scheme.

**Steps to reproduce:**
1. Create new project.
2. Add scene.
3. Add HTTPRequest node as root.
4. Connect "request_completed" signal.
5. Perform request using `https://godot-ssl-test.firebaseio.com/.json`.
6. Run current scene. _(expectation: the game closes.)_
7. If expectation at `step 6` fails, you should receive a response mentioned above and the game does not close.

**Comment by akien-mga** [comment]
Thanks for the report, it might be that even though it all compiles fine, we still need to take into account API changes in OpenSSL 1.0.2h. If you could confirm by trying the official binaries for Godot 2.0.1 (which used OpenSSL 1.0.1h), it would be great :)

**Comment by mownier** [comment]
@akien-mga I can confirm that v2.0.1 does well regarding with openssl. Yep, you are right, openssl changes are needed to take into account. However, maybe next time if there is an update on critical dependencies, such as openssl, a separate branch should be created. That is just a suggestion on the dev workflow. You can just omit it. haha

**Comment by akien-mga** [comment]
Well to be honest if it had been merged in a separate branch, we would never have known that there was an issue. The OpenSSL update has been done one month ago already, and you're the first to report an issue with it (apart from a couple compilation-related issues that are being handled currently).

Also, the previous version was critically vulnerable to dozens of security vulnerabilities, so a quick update was necessary :)

**Comment by mownier** [comment]
Okay, I see. Thanks.

**Comment by akien-mga** [comment]
Actually I've noticed that HTTPRequest does not exist in 2.0.x, so it could very well be that this is an HTTPRequest bug, and not a regression due to the OpenSSL upgrade. Other SSL features seem to work fine in the master branch with builtin OpenSSL, such as talking to the GitHub API, etc.

**Comment by mownier** [comment]
A speculation I would say that, there's a problem in StreamPeerSSL class, which is used in HTTPClient, upon connecting to the host. While calling `poll` method in HTTPClient, it stuck on status `HTTPClient.STATUS_CONNECTING` and the status will never be `HTTPClient.STATUS_CONNECTED`. Afterwards, the test game will close.

**Comment by ealataur** [comment]
I have the same bug in master branch but all work fine in 2.0.1

**Comment by reduz** [comment]
what's the state of this?

**Comment by reduz** [comment]
also, an example project would be appreciated

**Comment by mownier** [comment]
i just tested this. this is already fixed.
