### ISSUE TITLE
AnimatedSprite3d frame changed never fires

### ISSUE THREAD

**Issue by chriscamacho** [godotengine/godot#45947]
as per title please see example project

[animatedsprite3d-noframe-signal.zip](https://github.com/godotengine/godot/files/5975154/animatedsprite3d-noframe-signal.zip)

expected result: on frame changed should call the connected function each time a new frame is shown

**Comment by Calinou** [comment]
Related to #40301. This will be fixed by https://github.com/godotengine/godot/pull/40316.

PS: In the future, please fill in the issue template instead of replacing it when reporting bugs.

**Comment by chriscamacho** [comment]
sorry completely missed the template, glad you could fix it anyhow!
