### ISSUE TITLE
Godot online editor: 3D view not working in Chrome on intel mac 

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#45954]
**Godot version:**
All the version available on editor.godotengine.org

**OS/device including version:**
Tested on 2 macs on Catalina 10.15.7:

- One with Radeon Pro 560x **(no bug with this mac)**
- One with Intel Iris 1536 (**here the bug occurs**).

**Issue description:**

The 3D view  is not rendered in Chrome , but works fine on Firefox. I tried to run webgl game/demos to see if the issue is generalised. However I was able to run all the game/demo flawlessly, so it seems to be related to the Godot editor.

<img width="1178" alt="Capture d’écran 2021-02-12 à 23 12 51" src="https://user-images.githubusercontent.com/6397893/107850623-0bb0e900-6e04-11eb-9a09-6a861ea20199.png">

**Steps to reproduce:**
Open the editor

**Comment by Calinou** [comment]
Can you open the DevTools in Chrome, reload the editor and paste the error messages you get here?

**Comment by fabriceci** [comment]
@Calinou there is no error, however there is no webGL warning too:

<img width="1279" alt="Capture d’écran 2021-02-13 à 09 07 52" src="https://user-images.githubusercontent.com/6397893/107852861-4a9a6b00-6e13-11eb-8854-7d0e1c18bfe5.png">

**Comment by Faless** [comment]
Maybe related to: #40842

**Comment by fabriceci** [comment]
Works now
