### ISSUE TITLE
Input.is_key_pressed() method not working properly for some keys

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot#4595]
Using : Godot_v2.0.2_stable_x11.64 on linuxmint 17.2

InputEvent.scancode is returning wrong values for some keys and these keys also don't work with
Input.is_key_pressed() method. For example KEY_BACKSPACE is working but KEY_ENTER is not working with Input.is_key_pressed() method. InputEvent.scancode value is a 8 digit integer for both of KEY_BACKSPACE and KEY_ENTER. Besides KEY_SPACE seems to be working as expected.

Press "enter", "space" and "backspace" to replicate

Sample code : 

	extends Node2D

	func _ready():	
		set_process_input(true)

	func _input(event):
		if event.type == InputEvent.KEY && event.pressed:
			print("\n\n \n ----- ----- ----- ----- ----- ----- -----")
			var scancode = event.scancode
			print('scancode ' + str(scancode))
			var unicode = event.unicode
			print('unicode ' + str(unicode))

			print("\n ----- ----- ----- ----- ----- ----- -----")
			print('CHECKING KEY_ENTER')
			var reported_scancode_for_enter = 16777221
			print ('scancode when "enter" pressed is : ' + str(reported_scancode_for_enter))
			print('value of constant for KEY_ENTER is : ' + str(KEY_ENTER))
			if(scancode == reported_scancode_for_enter):
				print('ENTER IS PRESSED')
			if(Input.is_key_pressed(KEY_ENTER)):
				print('is_key_pressed for KEY_ENTER is working')

			print("\n ----- ----- ----- ----- ----- ----- -----")
			print('CHECKING KEY_BACKSPACE')
			var reported_scancode_for_backspace = 16777220
			print ('scancode when "backspace" pressed is : ' + str(reported_scancode_for_backspace))
			print('value of constant for KEY_BACKSPACE is : ' + str(KEY_BACKSPACE))
			if(scancode == reported_scancode_for_backspace):
				print('BACKSPACE IS PRESSED')
			if(Input.is_key_pressed(KEY_BACKSPACE)):
				print('is_key_pressed for KEY_BACKSPACE is working')

			print("\n ----- ----- ----- ----- ----- ----- -----")
			print('CHECKING KEY_SPACE')
			var reported_scancode_for_space = 32
			print ('scancode when "space" pressed is : ' + str(reported_scancode_for_space))
			print('value of constant for KEY_SPACE is : ' + str(KEY_SPACE))
			if(scancode == reported_scancode_for_space):
				print('SPACE IS PRESSED')
			if(Input.is_key_pressed(KEY_SPACE)):
				print('is_key_pressed for KEY_SPACE is working')

**Comment by reduz** [comment]
This is not a bug, the actual key is KEY_RETURN, not KEY_ENTER. 
I think this was somehow taken from X11, I don't remember

**Comment by akien-mga** [comment]
Indeed, `KEY_RETURN` is the key which is typically above the arrow keys. `KEY_ENTER` is the key which is at the right of the numpad, when there is one.
