### ISSUE TITLE
Locked nodes don't have a lock icon in the scene tree

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#45964]
**Godot version:**
3.2.4 rc2 and latest master 041cccc28773fe2d832a90888416df106f2a6d79

**OS/device including version:**
Windows 10

**Issue description:**
In the editor you can lock certain nodes, so that they can't be moved by accident (lock icon). Currently when you do this, the lock icon won't show up next to the node in the scene tree unless you save the scene and reopen it. Same goes for the "Make child nodes not selectable" feature. It's a purley visual bug (missing icon in scene tree). The nodes will actually be locked.

This is not happening in RC1.

![Capture](https://user-images.githubusercontent.com/8750135/107854896-61df5580-6e1f-11eb-83a0-19722b45d39a.PNG)

**Steps to reproduce:**
- Add a Sprite2D to the scene
- Lock it by clicking on the lock icon in the editor
- It's locked, but there is no icon next to it in the scene tree
- Save the scene and reload it -> now it shows the icon

**Comment by Calinou** [comment]
Can you reproduce this in 3.2.3?

**Comment by mbrlabs** [comment]
No, 3.2.3 is fine. It's also not reproducable in RC1, so this must have been introduced recently.

**Comment by akien-mga** [comment]
Might be related to #45813, CC @RandomShaper (who did warn me of possible regressions :P).
