### ISSUE TITLE
In 3D scenes, right mouse button causes random jump in editor viewport camera direction (macOS only)

### ISSUE THREAD

**Issue by hmans** [godotengine/godot#45966]
**Godot version:**
3.2.4 RC2 for Mac.

**OS/device including version:**
macOS Big Sur 11.2, i5, 16 GB RAM, Intel Iris Plus 655

**Issue description:**
In a 3D scene, when trying to rotate the editor camera using the right mouse button, once the button is pressed, the camera rotates into a seemingly random direction once the button is clicked.

Tweet with video:
https://twitter.com/hmans/status/1360610656064593923

Confirmed to happen with the editor running in both GLES2 and 3. Also confirmed that this does not happen in the Windows version of the editor (same version.)

**Steps to reproduce:**
Create a new project with a 3D scene. It doesn't need to have any additional nodes in it.

*Bugsquad edit (keywords for easier searching): freelook*

**Comment by Calinou** [comment]
This is probably due to how the mouse position is set when the mouse mode is set to `Input.MOUSE_MODE_CAPTURED` on macOS.

**Comment by akien-mga** [comment]
CC @godotengine/macos.

**Comment by bruvzg** [comment]
I can confirm both this and #46030, bugs are present in 3.2.4 beta 1, but not in 3.2.3 stable.
