### ISSUE TITLE
Warning about changed project file while having the project open multiple times

### ISSUE THREAD

**Issue by NoFr1ends** [godotengine/godot#45965]
**Godot version:**
3.2.4.rc2

**OS/device including version:**
Linux

**Issue description:**
When having the same project open multiple times (e.g. to be able to easily start the game multiple times while developing network games) whenever you switch the editor you will get a warning about a changed "project.godot" file. This behaviour is new with 3.2.4.rc2 and got introduced by #31747
It is also possible to launch the project via cli but I know many people who having the editor open twice and aren't really used to use the command line.

**Steps to reproduce:**
1. Create a new project
2. Open it twice
3. Switch focus between the editors

**Comment by Calinou** [comment]
cc @KoBeWi 

We could look at calculating MD5 checksums of `project.godot` instead of relying on the file modification date.

**Comment by KoBeWi** [comment]
As I mentioned in chat, fixing #45243 would resolve this issue.
