### ISSUE TITLE
Can't Compile GDNative C++ game for Windows under Linux (Zorin OS and Ubuntu).

### ISSUE THREAD

**Issue by Karim-Fadi** [godotengine/godot#45974]
**Godot version:**

3.23 stable (Standard)

**OS/device including version:**

Linux Zorin OS and Ubuntu (Not Graphics related)

**Issue description:**

What happened was that i was making a GDNative C++ game and i can compile for Linux just fine but when i tried for Windows (I installed mingw and the environment variables are set correctly) it failed giving an error that the compiler options or command line options are not found. The Same thing happened under Zorin OS and Ubuntu. Is there anything i must change in the Sconstruct file or this is a bug?

The Project :
[C++ Testing.zip](https://github.com/godotengine/godot/files/5976469/C%2B%2B.Testing.zip)

  I was expecting it to compile without problems.

**Steps to reproduce:**
You can try to compile your own GDNative C++ Example for Windows under Linux (Ubuntu or Zorin OS) and see if it works.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This repository is only used to track core engine bugs. 
Please report issues related to the C++ binding on [godot-cpp](https://github.com/godotengine/godot-cpp/issues) **after searching for duplicates**.
