### ISSUE TITLE
java.lang.VerifyError crash on Android app startup when using Android plugin in 3.2.4-rc2

### ISSUE THREAD

**Issue by msoechting** [godotengine/godot#45983]
**Godot version:**
3.2.4-rc2

**OS/device including version:**
GLES 3, Samsung SM-G965F

**Issue description:**
When building an Android project with a plugin (either GameAnalytics or Admob), the game crashes on startup on the phone.

**Steps to reproduce:**
1. Build sample project with GameAnalytics plugin or [Admob plugin](https://godotengine.org/qa/91861/android-app-crashing-due-to-admob)
2. When launching the app on the Android phone, it crashes with this error:
```
02-13 23:07:07.393  4669  4669 E AndroidRuntime: FATAL EXCEPTION: main
02-13 23:07:07.393  4669  4669 E AndroidRuntime: Process: com.gameanalytics.godottest, PID: 4669
02-13 23:07:07.393  4669  4669 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class com.gameanalytics.godotgameanalytics.GodotGameAnalytics: void com.gameanalytics.godotgameanalytics.GodotGameAnalytics.init(java.lang.String, java.lang.String) failed to verify: void com.gameanalytics.godotgameanalytics.GodotGameAnalytics.init(java.lang.String, java.lang.String): [0x7] register v0 has type Reference: org.godotengine.godot.Godot but expected Reference: android.app.Activity (declaration of 'com.gameanalytics.godotgameanalytics.GodotGameAnalytics' appears in /data/app/com.gameanalytics.godottest-mtZ_tK2kr4ox-nPt89PH7A==/base.apk)
```

**Minimal reproduction project:**
[GameAnalytics example.zip](https://github.com/godotengine/godot/files/5976615/example.zip)

**Comment by akien-mga** [comment]
The Admob plugin doesn't seem update for 3.2.4 yet: https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/98
The latest release is for 3.2.3.stable.

Probably the same for the GameAnalytics plugin?

**Comment by msoechting** [comment]
I assume that is the same case for GameAnalytics, I'll bring it up with their plugin maintainers then. Thanks!

**Comment by m4gr3d** [comment]
@msoechting Thanks for reporting the issue! Feel free to loop us in the plugin maintainers' issue if more information is needed.
