### ISSUE TITLE
Nodes added via EditorPlugin don't refresh the Scene Dock automatically

### ISSUE THREAD

**Issue by DarkKilauea** [godotengine/godot#45988]
**Godot version:**
Godot Engine v3.2.4.rc2.official

**OS/device including version:**
Windows 10

**Issue description:**
When adding nodes to the currently edited scene via a tool script, nodes are not automatically shown in the Scene Dock.  If you click on another node in the Scene Dock, then the added nodes will appear.

Nodes do appear automatically with Godot Engine v3.2.4.rc1.official, so I believe this is a recent regression.

Behavior in RC1:

https://user-images.githubusercontent.com/1929107/107864626-fc856780-6e12-11eb-8ea4-2618ff0895fa.mp4

Behavior in RC2:

https://user-images.githubusercontent.com/1929107/107864630-04450c00-6e13-11eb-9ecd-961cbc7a154c.mp4

Code used to add nodes:
``` gdscript
var node := scene.instance(PackedScene.GEN_EDIT_STATE_INSTANCE if Engine.editor_hint else PackedScene.GEN_EDIT_STATE_DISABLED);
node.name = palette.get_item_name(item_id);

var spatial := node as Spatial;
if spatial:
        spatial.translation = get_global_cell_position(coordinate);

self.add_child(node, true);

# Climb the nodes above us, looking for an owner to attach to.
var parent: Node = self;
while parent:
        if parent.owner:
	        node.owner = parent.owner;
	        break;
        parent = parent.get_parent();
```

**Steps to reproduce:**
1. Download the reproduction project linked below and open it in RC2.
2. Select the "SceneMap" control.
3. Select "Floor" in the right hand dock.
4. Left click in the scene to paint tiles.

**Minimal reproduction project:**
https://github.com/DarkKilauea/godot-scene-map/tree/361d3ef90c067c1102a477a8362a49f15c9c7a75

**Comment by akien-mga** [comment]
CC @RandomShaper @KoBeWi

**Comment by KoBeWi** [comment]
This is not related to plugins, works with any tool script and I've seen it happen with nodes added not via script too. Here's a truly minimal reproduction:
```
@tool
extends Node2D

var timer: float

func _physics_process(delta: float) -> void:
	timer += delta
	if timer > 1:
		timer = 0
		var node = Node.new()
		add_child(node)
		node.owner = self
```
Put it into root node of a scene (remove `@` if you are not on master).

**Comment by Calinou** [comment]
Confirmed by lawnjelly on the Godot contributors chat.

**Comment by KoBeWi** [comment]
This is a regression from #45813
