### ISSUE TITLE
CacheMode and Side missing from mono build

### ISSUE THREAD

**Issue by DigitalJokerMan** [godotengine/godot#45985]
**Godot version:**

2b95372

**OS/device including version:**

Microsoft Windows 10 Version 1909

**Issue description:**

I tried compiling with mono, and I encountered this error.

```
Core\Extensions\ResourceLoaderExtensions.cs(5,70): error CS0246: The type or namespace name 'CacheMode' could not be found (are you missing a using directive or an assembly reference?) [F:\Git\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
Core\Extensions\ResourceLoaderExtensions.cs(5,90): error CS0103: The name 'CacheMode' does not exist in the current context [F:\Git\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
Core\Rect2.cs(202,31): error CS0246: The type or namespace name 'Side' could not be found (are you missing a using directive or an assembly reference?) [F:\Git\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
Core\Rect2i.cs(197,32): error CS0246: The type or namespace name 'Side' could not be found (are you missing a using directive or an assembly reference?) [F:\Git\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
```

**Steps to reproduce:**
Generate the mono glue, and then try to compile Godot with mono.

**Minimal reproduction project:**

N/A

**Comment by Xartorx** [comment]
May be regression from my commit (#45959), try to change `CacheMode` to `ResourceLoader.CacheMode` in `modules\mono\glue\GodotSharp\GodotSharp\Core\Extensions\ResourceLoaderExtensions.cs` and see if it's compiles.
IDK why it's doesn't compiles for you, even OmniSharp suggests to simplify name.

**Comment by aaronfranke** [comment]
@DigitalJokerMan I can't reproduce. Try doing a clean build: `git clean -fd && git clean -fdX`, then build again.

**Comment by DigitalJokerMan** [comment]
> @DigitalJokerMan I can't reproduce. Try doing a clean build: `git clean -fd && git clean -fdX`, then build again.

Yeah, that worked. I guess it was my fault. Thanks guys!
