### ISSUE TITLE
DVector - invert()

### ISSUE THREAD

**Issue by kjohnson0451** [godotengine/godot#4601]
Would it be appropriate to add an invert() method to core/dvector.h? I've come to a point where I need to invert a Vector3Array.

If this were to be added to dvector.h, it would give the functionality to all of the Array types (IntArray, StringArray, etc.)

Note - Inverting an array is equivalent to reversing its contents (bringing the back elements to the front, putting the front elements in the back).

**Comment by kjohnson0451** [comment]
If this is indeed appropriate, I'd be up for implementing it.

**Comment by djrm** [comment]
fixed by #4693
