### ISSUE TITLE
Dragging to adjust variable values in inspector is broken

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#46030]
**Godot version:**
3.2.4 RC2

**OS/device including version:**
macOS Catalina
Macbook Pro

**Issue description:**
Seems to be a regression since 3.2.3. It's an issue in both RC1 and RC2, I am not sure about beta builds.

When dragging over an exported variable to adjust the value, it does not work as expected. The issue is not limited to any particular variable type as far as I can tell. Dragging only a tiny bit causes the value to jump to an extreme, and even if you drag to the right it jumps to below what it already was:

https://user-images.githubusercontent.com/33777501/107888291-39f3fe80-6ec0-11eb-8592-0c4e77e88a78.mov

Dragging on a variable with a slider also does not work smoothly as it used to, though the slider itself works fine:

https://user-images.githubusercontent.com/33777501/107888316-5d1eae00-6ec0-11eb-9efc-87500e0cd8b1.mov

**Steps to reproduce:**
Make a new scene, add a node such as Node2D, and try to adjust some variable in inspector (like position) by dragging over it.

**Minimal reproduction project:**
Not needed I think

**Comment by KoBeWi** [comment]
I can't reproduce it, for me the behavior is the same as in 3.2.3.

**Comment by akien-mga** [comment]
Might be a macOS specific input issue, there's also https://github.com/godotengine/godot/issues/45966 which was reported as a regression on macOS.
