### ISSUE TITLE
Light2D Additive not always rendered in correct order (Only GLES2)

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#46049]
Godot 3.2.3 Stable, Windows 10.

When having two light2Ds on top of eachother the renderorder is switched randomly. Light 1 is set to additive and live 2 is set to mix. In the image you can also see that when the scene is played godot randomly sets the order of the lights each time. If I duplicate the light theres a 50 percent chance that the render order is wrong.

GLES3 is working as intended.

![image](https://user-images.githubusercontent.com/24936603/107942843-1bf3d000-6f8c-11eb-9ed5-109484d0f8a7.png)

Make two light2D's set one to mix and the other to add, if you dupliacete them or play the scene they should randomly switch render order.

**Comment by lawnjelly** [comment]
Needs minimum reproduction project.

**Comment by TonyMorgan-BurbleGames** [comment]
I have found this problem too but in GLES 3.  Using v3.5.1... Any fixes or work arounds?

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/34673.

@jesperkondrup @TonyMorgan-BurbleGames Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
