### ISSUE TITLE
Full-Screen Screen flickering

### ISSUE THREAD

**Issue by Rukiri** [godotengine/godot#4605]
Hello, I have a pretty basic issue with Godot which is full-screen.
Every time I enter full screen the screen will flicker, but is just fine in Window mode.

OS: Windows 10 PRO X64
GPU: Nvidia Titan-X
Drivers: 365.10

Just turn on fullscreen in the project settings, this may be a driver issue but I've tried several and get the same.  I did NOT have these issues in 1x!

**Comment by reduz** [comment]
seems it's not vsyncing on Windows for some reason, will have to check

**Comment by akien-mga** [comment]
@reduz BTW, there is still strong interest in the community for a way to force vsync on (#2621). You mentioned there that it's hardly relevant as it's always forced on by compositors, but it seems not to always be the case.

**Comment by bojidar-bg** [comment]
@akien-mga ~ Considering that fullscreen is usually not managed by the composer, it might be it :smile:

**Comment by Calinou** [comment]
> @akien-mga ~ Considering that fullscreen is usually not managed by the composer, it might be it :smile:

Also, V-Sync is not forced on Windows by default, except by Intel graphics drivers.

**Comment by reduz** [comment]
Yeah, it seems on fullscren, vsync is not forced on by default.. I thought
it was. Will have to work on this.

**Comment by Rukiri** [comment]
Enabling V-Sync in the Nvidia control panel doesn't solve the problem though...

**Comment by Alex-doc** [comment]
@reduz I've added Vsync a while ago but never did a PR because I'm not sure it's the neatest way to implement it. [it is in this commit here](https://github.com/Alex-doc/godot/commit/1e5b5f4da7911b090a429d8ea50f0f15b424fd41)

**Comment by Rukiri** [comment]
Switched resolutions, have a 4K display but go back down to 1080p for normal desktop use, go back to 1440p or 4K for gaming and forgot to switch back the resolution and noticed the massive flickering is gone...  I have noticed major screen tearing in games like dolphin island 2 and a few others and forcing v-sync probably isn't as effective as forcing it in engine.

**Comment by akien-mga** [comment]
@Rukiri Could you try again in the current master branch, which has vsync support?@Rukiri Could you try again in the current master branch, which has vsync support?

**Comment by reduz** [comment]
this is most likely fixed now

**Comment by akien-mga** [comment]
Closing then, please reopen if you still experience this issue once we release 2.1 alpha (or when you build the master branch from source).

**Comment by rogeriodec** [comment]
Project: [path.zip](https://github.com/godotengine/godot/files/2968968/path.zip)

I do not know if it's the case of opening a new issue, but I'm using official Godot 3.1 with Windows 10 x64 and an NVIDIA GeForce GTX 1060 6GB video card.

In the project (above) where I did a simple test with PathFollow, I noticed two problems:
1) I have 3 monitors. When the game screen is running on monitor 1 (LG M2380A), the animation displays **flickers** (after the third loop of the mesh). By dragging the screen to monitor 2 (AOC 2269W) or to monitor 3 (Samsung SyncMaster), no flickers occur. Maybe it's something with the clock in Monitor 1 (although I only saw this problem with Godot).
2) Another strange situation: turning off VSync, the animation is simply crazy, the mesh keeps jumping from side to side, following the path.

What could be done?

**Comment by PragmaticBeaver** [comment]
I have the same Problem as @rogeriodec .
I am using a 144hz Screen and a 60hz Screen. The flickering occurse on my 144hz Screen but not on my 60hz screen.
Godot Version: 3.2.1.stable.official
using OpenGL 3.0
My graphics card is a Nvidia GeForce RTX 2080.

**Comment by Calinou** [comment]
@PragmaticBeaver Can you make a video recording of the flickering and upload it here, if it's visible on a video?

**Comment by clayjohn** [comment]
@PragmaticBeaver Please open a dedicated issue. What you describe is very different from this issue. 

Before doing that however, have you tried setting Vsync to use the windows compositor? There was a setting added recently to use the Windows compositor for VSync, and that may help with your issue. See https://docs.godotengine.org/en/3.2/classes/class_projectsettings.html#class-projectsettings-property-display-window-vsync-vsync-via-compositor

**Comment by Anutrix** [comment]
Maybe 2.1 Milestone can be removed or changed as 3.x seems to be affected too.

**Comment by akien-mga** [comment]
This is a 2016 bug report about Godot 2.0, I would suggest opening new issues for similar-sounding issues that happen in 3.2+.
