### ISSUE TITLE
Project export for iOS takes a very long time (10+ min) due to LTO enabled in 3.2.4 RC 2 

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#46064]
**Godot version:**

3.2.4 rc2

**OS/device including version:**

iOS Catalina

**Issue description:**

iOS project export freezes (repeatedly) on Making .xcarchive at 60%. Tried the standard demo Dodge The Creeps - same issue with 3.2.4 rc2, freeze at 60%.

Same projects, same export has no problem with 3.2.4 rc1 and previous versions.

**Steps to reproduce:**
Export project for iOS with 3.2.4. rc2

**Minimal reproduction project:**

No clue where to look at but willing to help debugging it.

![IOS_export_freeze](https://user-images.githubusercontent.com/40200623/107982891-23839b00-6fc5-11eb-9f32-60d3507bc04c.png)

**Comment by akien-mga** [comment]
CC @godotengine/ios

**Comment by naithar** [comment]
Seeing same issue with 3.2.4rc2 on my project.
Trying to compile directly with Xcode seems to have no effect. Xcode is stuck on `Link Godot`. 
@akien-mga was iOS templates built with LTO support? The last time I got same results was exactly because of this.

**Comment by naithar** [comment]
Yeah, `use_lto` (`-flto`) makes iOS projects noncompileable. But `https://github.com/godotengine/godot-build-scripts/blob/6bee8dec2e3bbb64d784cfbd1885239a64c05804/build-ios/build.sh` doesn't seem to have anything using this flags. `production=yes` also isn't used.

I've built `lto` and non-`lto` binaries myself and non`lto` work fine.

**Comment by akien-mga** [comment]
Yeah I have a local commit that enabled `production=yes`, I forgot to push it. So I'll disable it again for iOS (and I guess we should maybe disable LTO support in the `detect.py` if it doesn't work?).

**Comment by naithar** [comment]
I'm not sure exact reason for it to be there, so I didn't touch when I was doing refactoring it just in case. But since it's not working and just breaking stuff, I guess it should be removed.

**Comment by ViktorEvil** [comment]
same, takes up to 10 minutes to do the initial build in Xcode, stays on "Constructiing differed tasks" for ages

using M1 MacBook Pro with 16GB

**Comment by naithar** [comment]
@oeleo1 @ViktorEvil 
You can download iOS binaries from here: https://s3.eu-central-1.wasabisys.com/naithar/godot/godot_templates/ios/3.2.4.b7695f1/list.html

You can simply replace `<project_name>.a` file in project folder with the file from archive and it should be possible to compile through Xcode without linker taking a lot of time.
In case you want to use `.xcframework` you will need to manually link it to the Xcode project, but don't forget to set it to `Do not embed`

**Comment by ViktorEvil** [comment]
@naithar thanks, I noticed you have tvOS builds on there as well, is that a possible export feature in Godot 4?

**Comment by naithar** [comment]
I've made a PRs to add it to `master` and `3.2` (https://github.com/godotengine/godot/pull/45829).
You can try using macOS editor build from the link - it has tvOS export built-in.

**Comment by paulo-coutinho** [comment]
Mine is freezing sometimes when export and when run on Xcode on my device:

![image](https://user-images.githubusercontent.com/395096/108926310-e77fb400-761c-11eb-8777-46da4196942b.png)

**Comment by naithar** [comment]
@akien-mga seems like `production=yes use_lto=yes` doesn't rewrite `use_lto` flag that gets set with `production` flag - RC3 binaries still use `-flto`

**Comment by naithar** [comment]
> Mine is freezing sometimes when export and when run on Xcode on my device:

It's not freezing, it's linking Godot's static library. It takes longer due to the enabled `link time optimization` flag that was used to build the binary.

**Comment by paulo-coutinho** [comment]
Yes, but im with a macbook corei7 6-core and it never compile? I think the flag is `-eternal`.

**Comment by naithar** [comment]
It doesn’t matter what flags you are using for Xcode in this case. Godot binary was built using lto.

**Comment by ViktorEvil** [comment]
> It doesn’t matter what flags you are using for Xcode in this case. Godot binary was built using lto.
> 
> **Edit:**
> I've finished uploading rc3 non-lto binaries in case you need them: [link](https://s3.eu-central-1.wasabisys.com/naithar/godot/godot_templates/ios/list.html)

thanks

**Comment by MarcusDobler** [comment]
> **Godot version:**
> 
> 3.2.4 rc2
> 
> **OS/device including version:**
> 
> iOS Catalina
> 
> **Issue description:**
> 
> iOS project export freezes (repeatedly) on Making .xcarchive at 60%. Tried the standard demo Dodge The Creeps - same issue with 3.2.4 rc2, freeze at 60%.
> 
> Same projects, same export has no problem with 3.2.4 rc1 and previous versions.
> 
> **Steps to reproduce:**
> Export project for iOS with 3.2.4. rc2
> 
> **Minimal reproduction project:**
> 
> No clue where to look at but willing to help debugging it.
> 
> ![IOS_export_freeze](https://user-images.githubusercontent.com/40200623/107982891-23839b00-6fc5-11eb-9f32-60d3507bc04c.png)

I've the same issue with RC3 - Export stuck at 60% - Godot (does not react) for around 10 minutes 

<img width="566" alt="Bildschirmfoto 2021-03-05 um 07 06 24" src="https://user-images.githubusercontent.com/16276195/110076989-b5d9bc00-7d85-11eb-80fd-7ceae557aa12.png">

**Comment by naithar** [comment]
@MarcusDobler as I previously mentioned here and in your issue, RC2 and RC3 iOS templates was built with `lto` enabled. This results in longer compilation times everywhere - in editor and in Xcode project.
`lto` will probably be disabled for iOS in RC4. 
For now you can use my iOS templates - they was built on macOS and with disabled `lto`.

**Comment by oeleo1** [comment]
All right! 3.2.4.rc4 fixes it. Thanks!
