### ISSUE TITLE
Networking RPC Error

### ISSUE THREAD

**Issue by Almondbubby** [godotengine/godot#46068]
I'm tagging @Faless  and @Calinou since they have helped a lot of other people in things like this.

**Godot version:**

Godot Version 3.2

**OS/device including version:**

**Issue description:**

I was trying to start a game using an RPC. Instead, I got an error: 
`ERROR: Node not found: Host.
   At: scene/main/node.cpp:1381
ERROR: _process_get_node: Failed to get path from RPC: Host.
   At: core/io/multiplayer_api.cpp:256
ERROR: Invalid packet received. Requested node was not found.
   At: core/io/multiplayer_api.cpp:204`

**Steps to reproduce:**
I made a menu with a join and host button. Hosting would bring you to a scene where you would be given a port number, and joining would show you a spin box where you would enter in the port. Everything is connected, but when the host starts the game, I got the error.

**Minimal reproduction project:**

[GitHelp.zip](https://github.com/godotengine/godot/files/5983995/GitHelp.zip)

Thanks for any help!

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by Almondbubby** [comment]
Thanks, sorry, I'll ask on the godot forum or something next time.
