### ISSUE TITLE
Android build crashes on start when using font

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4606]
Any font type (bitmap, field, dynamic) makes the game on android crash on godot engine splash screen and it also flashes (Samsung Galaxy S4). On desktop work just fine.

Although, if the fonts were imported using other godot version (2.1) work just fine.

**Comment by akien-mga** [comment]
@reduz Would there be some Android code still referencing ``Font`` instead of ``BitmapFont`` or ``DynamicFont``?

**Comment by henkz1** [comment]
@EdwardAngeles ofc this could be a bug with fonts, but exact same thing can happen if you use export templates from an older godot version. Maybe you'r using templates from 2.1?

**Comment by reduz** [comment]
most likely export templates outdated

**Comment by akien-mga** [comment]
Also note that 2.1 is not released yet, but you probably meant 2.0.1. As others mentioned, if you are using the git master branch, you need to build Android export templates from the same branch. The templates of Godot 2.0.1 or 2.0.2 especially don't know about BitmapFont and DynamicFont, so it won't work.

**Comment by EdwardAngeles** [comment]
Yip, that was the problem I was using the templates from 2.0.1. I built a template from source and it's working well, thanks!
