### ISSUE TITLE
"Could not find base class" when trying to extend abstract class

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#46073]
**Godot version:**

f14008b

**Issue description:**

When you try to extend class that is abstract (e.g. CanvasItem or Texture) the editor complains that it can't find the class. In 3.2 there is no error, but then you can't instantiate the script.

The error should clearly say that the class is abstract and you can't extend it.

**Comment by Xrayez** [comment]
> The error should clearly say that the class is abstract and you can't extend it.

But isn't it the point behind having abstract classes, so they can be extended? Unless you just want to make the message for user-friendly.

In any case, that's a feature which should be supported given the existing ability to extend base classes in C++.

If there's no intention to fix this, then I'd keep #42830 open regardless (at least for 4.0), otherwise have to create a feature proposal (for something which should be supported already, IMO). 🙂

**Comment by KoBeWi** [comment]
Well I agree that this should be supported (I guess there are some limitations that disallowed it so far), but until it happens the error should be fixed.

**Comment by BastiaanOlij** [comment]
Running into this as a problem as well extending `PhysicsBody3D`, the use case here is that the script I'm converting from Godot 4 can be assigned to any subclass of `PhysicsBody3D`. I don't want to create identical copies of the scripts just so I can use it both with a static body and rigid body.

**Comment by JoanPotatoes2021** [comment]
Having the same problem atm just like Bastiaan, writing a interface visual effects script I cannot extend from `CanvasItem` to allow applying the same script to `Node2D` and `Control` nodes, using v4.0.alpha9.official [fc18891db].

**Comment by Fran6nd** [comment]
Well, this is still open and I am facing, I believe the same issue with the latest Godot 4 alpha:
```
class my_item extends TreeItem:
	var id
	pass
```

And I get:

```Invalid set index 'fullpath' (on base: 'TreeItem') with value of type 'String'.```

This is very annoying as it makes the use of built-in component really painful.

**Comment by eh-jogos** [comment]
Having this issue on Godot 4, I have a script that should work both with Controls and Node2D so making it extend CanvasItem seemed like the obvious solution, but just doesn't work.

**Comment by DaGamingWolf** [comment]
sadness. i'm trying to make a class that has a bunch of predefined shape functions specialized for my game in addition to the ones defined in canvas item. i guess i can do it another way but this felt like the best way to go about it.
