### ISSUE TITLE
Double clicking in the File System panel won't work

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4607]
I'm using a build from source version. Linux / Ubuntu Gnome.

I can't navigate through the file system panel by double clicking and the resources won't open either, I can select them by simple click and open the folders/resources by pressing enter, though.

**Comment by mefihl** [comment]
I can confirm the bug on Windows platform.

**Comment by RayKoopa** [comment]
That's interesting, I don't seem to have that bug on Win10 Pro x64.

**Comment by jackmakesthings** [comment]
I'm also seeing this on Mac OS X (El Capitan, the latest version) with godot built from source. Double-click doesn't work, single click and enter does. This seems to have started within the past few weeks.

**Comment by akien-mga** [comment]
Apparently it's caused by f909634, and I cherry-picked it for the 2.0 branch, so 2.0.3 is affected too :(
