### ISSUE TITLE
Ability to modify Spinbox editor widgets with mouse drag suddenly stopped working.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#4608]
**Operating system or device - Godot version:**
Ubuntu Linux 16.04 64bit, Godot built from git bc31be9812b165c677584a2be81a5a9bd71d8ecf

**Issue description** (what happened, and what was expected):
It was possible to alter the value of a Spinbox in the editor by holding mouse and dragging up and down, which was pretty handy to alter small values without having to reach for the keyboard. It suddenly stopped working after last update, and doesn't seem intentional judging from the changelogs.
Furthermore, the (rather imprecise, IMHO)"slider" widget will always pop out when the mouse is released after trying this, even if the cursor is far from the Spinbox widget when released.

**Steps to reproduce:**
Click over Spinbox and drag up/down, the value won't change. When the mouse button is released, the slider widget will pop out.

**Comment by neikeq** [comment]
I can reproduce this on the current master branch too. It looks like a regression from a735573 (I had no time to check but it's the only commit that modified `Tree` in the last weeks).

**Comment by hetdegon** [comment]
This fixed it, and in fact it even seems to work better than before. Thanks a lot!
