### ISSUE TITLE
C# Inherited Tool script variables lose data on build within opened scenes!

### ISSUE THREAD

**Issue by Scripptor** [godotengine/godot#46080]
**Godot version:** 
v3.2.3.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
SceneB inherits from SceneA. SceneA has a script file, and SceneB has it's own. They're both declared as [Tool]. Scene A's script declares exported variables. The main scene has SceneA and SceneB in it. The Main scene is open in the editor, either as the active tab or a background tab. Altered script variables on any instance of SceneB will be lost if source files are modified and the project is built.  This can be restored by closing Main.tscn and reopening it. 

**Steps to reproduce:**
1. Make SceneA and attach a script. Declare it as a tool. Export a variable.
2. Make an inherited scene from SceneA, let's call it SceneB. Attach a script. Make that script inherit SceneA "SceneB : SceneA" Declare SceneB's script as a tool.
3. Add SceneB into your main scene.
4. Set the script variables of SceneB.
5. Keep main.tscn open. Modify code, simply by adding a comment in //
6. Build. And check the script variables of SceneB. They're lost!

**Minimal reproduction project:**
[ToolInheritenceBug.zip](https://github.com/godotengine/godot/files/5985934/ToolInheritenceBug.zip)

**Comment by Phischermen** [comment]
Might you have encountered issue #37812?

**Comment by Scripptor** [comment]
Oh! I didn't see that, I struggled to word a search to hit this exact issue, I will close mine as it's a duplication.
I will report on your issue what I've learnt about it.
