### ISSUE TITLE
Add support for documenting member variables

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4609]
Current doctool will discard any information given for member variables as e.g. in #4563. We need to:
- tweak doctool to have it parse and merge the contents of ``<member>`` tags properly (likely easy)
- tweak the editor to have it display this information in the offline help
- tweak the `makerst.py` script to have it display this information in the online help

By comparing with the code for ``<constant>``, it should not be too hard to implement I think.

**Comment by akien-mga** [comment]
@bojidar-bg Could you handle tweaking ``makerst.py`` too?

**Comment by bojidar-bg** [comment]
@akien-mga ~ I think this works too, based on https://github.com/godotengine/godot/blob/master/doc/tools/makerst.py#L455
