### ISSUE TITLE
[OS gdscript] set_window_mouse_passthrough does not exist despit being documented

### ISSUE THREAD

**Issue by RexTheWho** [godotengine/godot#46109]
Was unable to find other reports on this issue.

**Godot version:**
Godot_v3.2.3-stable_win64

**OS/device including version:**
OS: Windows 10

**Issue description:**
Missing OS function `set_window_mouse_passthrough`
This function seems to be documented in the Godot docs but seems to be missing in the latest release.
Document: https://docs.godotengine.org/en/3.2/classes/class_os.html#class-os-method-set-window-mouse-passthrough

QA discussion I found relating to this issue.
https://godotengine.org/qa/93703/nonexistent-function-set_window_mouse_passthrough

**Steps to reproduce:**
- add a script to any basic node
- on _ready() for example use OS.set_window_mouse_passthrough([])
- get a non-existent function error

**Minimal reproduction project:**
[set_window_mouse_passthrough report.zip](https://github.com/godotengine/godot/files/5993107/set_window_mouse_passthrough.report.zip)

**Comment by bruvzg** [comment]
> Godot_v3.2.3-stable_win64

It's a new addition in 3.2.4.

**Comment by RexTheWho** [comment]
> 
> 
> > Godot_v3.2.3-stable_win64
> 
> It's a new addition in 3.2.4.

I see, excuse the confusion then. The docs dont seem to mention the version its in so I assume it was in the 3.2 release.

**Comment by Zarasan** [comment]
@bruvzg I am using 3.3.rc8 and when I add

- add a script to any basic node
- on _ready() for example use OS.set_window_mouse_passthrough($Polygon2D.polygon)

whole exe gets hidden
Before Clicking:
![Screenshot 2021-04-17 011340](https://user-images.githubusercontent.com/43384612/115093517-e1ba9680-9f1a-11eb-86b1-2c4a30bcb571.png)

After Clicking:
![Screenshot 2021-04-17 011838](https://user-images.githubusercontent.com/43384612/115093524-e7b07780-9f1a-11eb-943b-6e9838d4466a.png)
