### ISSUE TITLE
Requested features preset properties.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#4610]
Requested features preset properties. Similarly, as is done in a Blender Game Engine.
![2016-05-10 20-20-31](https://cloud.githubusercontent.com/assets/11325733/15147899/8a6ec598-16f5-11e6-8707-37c334373168.png)

**Comment by akien-mga** [comment]
You mean http://docs.godotengine.org/en/latest/reference/gdscript.html#exports ?

**Comment by DimaKiva** [comment]
Thanks!
