### ISSUE TITLE
Doubleclick is not correctly set for InputEventMouseButton events on mobile touch screens

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#46100]
**Godot version:**
3.2.3

**OS/device including version:**
Desktop test was Win 10.
Mobile test Android 11 on Galaxy S10e

**Issue description:**
The `doubleclick` property for an `InputEventMouseButton` event is not correctly set on mobile devices when the source is a Control.

**Steps to reproduce:**
With default project settings (i.e. "Emulate Touch As Mouse" is true):
1. Override `_gui_input` for a `Control` node with mouse flags correctly set.
2. Print the input events, including the doubleclick parameter.

On Desktop the output is for a double click is (4 events generated, press and release for each touch in the double click):
<pre>
Event doubleclick = False, pressed = True
Event doubleclick = False, pressed = False
Event doubleclick = True, pressed = True
Event doubleclick = False, pressed = False
</pre>
The same test on mobile gives the following output:
<pre>
Event doubleclick = False, pressed = True
Event doubleclick = False, pressed = False
Event <b>doubleclick = False</b>, pressed = True
Event doubleclick = False, pressed = False
</pre>
Notice the second press does not trigger a double click.

**Minimal reproduction project:**
[Testing-DoubleClickControl.zip](https://github.com/godotengine/godot/files/5991094/Testing-DoubleClickControl.zip)

**Comment by Calinou** [comment]
I was able to reproduce this in a project of mine, although I've gotten doubleclick to work on mobile if the touch position was *exactly* the same between the two presses. This is very difficult to do on such hiDPI displays and fingers :slightly_smiling_face:

**Comment by m4gr3d** [comment]
cc @thebestnom
