### ISSUE TITLE
Bug material. The transparent property disables the depth test

### ISSUE THREAD

**Issue by oktopusgames** [godotengine/godot#46102]
**Godot version:**
version 3.2.3 stable, 3.2.3 mono stable, 3.2.4

**Steps to reproduce:**
Watch the gif: https://psv4.userapi.com/c536236/u102209357/docs/d38/2feb355e0d33/gX0SvzrosL.gif?extra=LGSgBWBVbk090OkU8-ACZcuIO0rB33XZAR9v0oQwL1cO2ZTqs2A6UsG8Z_tXdhb91gAbdTQHqfcR4sDp2IaAEt_aOJMIJ70D8-N-ttabVHs051TJnZjQqOb556o6nUmpaZh8AAooP95lIK9tGUEHsGwu

**Comment by pycbouh** [comment]
Please follow the issue template and provide additional information about your issue.

(You can also now post videos directly to GitHub).

**Comment by Hromon** [comment]
> Please follow the issue template and provide additional information about your issue.
> 
> (You can also now post videos directly to GitHub).

You can't read title?

**Comment by Hromon** [comment]
I have exactly the same bug.

**Comment by clayjohn** [comment]
Please see the documentation for SpatialMaterial depth draw mode. transparent objects are not written to the depth buffer. https://docs.godotengine.org/en/stable/classes/class_spatialmaterial.html#enum-spatialmaterial-depthdrawmode

Also. In the future, all bug reports need to follow the template. Posting a statement in the title is not sufficient.

**Comment by oktopusgames** [comment]
> Please see the documentation for SpatialMaterial depth draw mode. transparent objects are not written to the depth buffer. https://docs.godotengine.org/en/stable/classes/class_spatialmaterial.html#enum-spatialmaterial-depthdrawmode
> 
> Also. In the future, all bug reports need to follow the template. Posting a statement in the title is not sufficient.

In this case, how to enable the alpha channel for textures, avoiding such a problem

**Comment by pycbouh** [comment]
This is not a support forum, this is an issue tracker. If you need help with setting up your project, please join one of our [communities](https://godotengine.org/community).
