### ISSUE TITLE
Editor Freeze when dragging a LineShape2D

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#4611]
**Operating system or device - Godot version:**
Win 10
Godot 2.0.2.stable.official

**Issue description**
The whole godot engine freezes for a while.
It should not be like that.

**Steps to reproduce:**
Add a `RigidBody2D`
Add a `CollisionShape2D` as its child
Change the `Shape` parameter of `CollisionShape2D` from `null` to `LineShape2D` in the inspector
Try dragging, resizing the line shown in 2d editor

**Comment by eska014** [comment]
Confirmed on Win7, modifying the LineShape drags down the framerate

**Comment by Ovnuniarchos** [comment]
Confirmed it happens when the LineShape is a direct child of a CollisionObject.
Creating a CollisionObject, then a Node2D inside, then a LineShape inside the Node2D, does not affect the framerate.

**Comment by Ovnuniarchos** [comment]
I (more or less) found the culprit, but not a way to solve it.
Line2D, when changing, informs its parent that it has an AABB of 20000x20000 units. With the default cache size (128), that means ±30000 insertions in the cache!
The AABB could be reduced, but it would also reduce the Line2D size, as it is not *really* infinite.

**Comment by reduz** [comment]
the source of the freeze has been fixed, so closing this

**Comment by reduz** [comment]
this has been fixed a few weeks ago, so closing the issue
