### ISSUE TITLE
Using Thread objects in GDScript doesn't work on HTML5 exports (but works on desktop)

### ISSUE THREAD

**Issue by Semphriss** [godotengine/godot#46128]
**Godot version:**
3.2.3 vanilla (without Mono)

**OS/device including version:**
Ubuntu 20.04 LTS
CPU: AMD Ryzen 5 3600
GPU: AMD XT 5700 XT
Browser: Firefox 85.0.1

**Issue description:**
Using `Thread()` objects in GDScript will work fine on desktop, but will not launch properly on HTML5 exports. No error message is given.

**Steps to reproduce:**
Paste this code somewhere:
```gdscript
var thread = null

func _test(val):
	print(val)

func _ready():
	print("A")
	thread = Thread.new()
	thread.start(self, "_test", "B")
```

Running on desktop will print both "A" and "B"; running on an HTML5 export will only print "A".
<sub>I believe this issue also happens on Android devices, but I don't have my phone with me at the moment.</sub>

--------------------------

**Minimal reproduction project:**
[test-threads.zip](https://github.com/godotengine/godot/files/5997229/test-threads.zip)

**Comment by Calinou** [comment]
Threads in HTML5 are only supported in 3.2.4rc1 and later and *only if you use an HTML5 builds with threads enabled* (which requires browser support).
