### ISSUE TITLE
Reparenting crashes editor in release_debug build (GCC 6)

### ISSUE THREAD

**Issue by her001** [godotengine/godot#4614]
**Operating system or device - Godot version:**
Arch Linux 64 bit - Godot master branch (98bff2f) **only** with target=release_debug
git bisect reveals that the issue should effect everything after (and including) 84f96eb

**Issue description**:
Clicking the reparent button in the scene tree pane always crashes the editor, with every node type I have tried.

I tested with target=release_debug and target=debug. Not sure what other options there are that include the editor, but the plain debug build did not have the issue.

**Comment by Calinou** [comment]
I can confirm this with Godot Git being installed through AUR. Reparenting a node will always cause an editor crash.

**Comment by bojidar-bg** [comment]
@her001 @Calinou ~ BTW, is there any chance this is related to GCC 6 as well?

**Comment by Calinou** [comment]
> BTW, is there any chance this is related to GCC 6 as well?

I'm using GCC 6.1, so it may be related.

**Comment by slapin** [comment]
Look at that bug for a workaround

**Comment by Hinsbart** [comment]
Can confirm it's not crashing for release_debug build with clang (3.7) .

**Comment by neikeq** [comment]
No crash here with GCC 4.9.3

**Comment by zaps166** [comment]
Crashes on `__cxxabiv1::__dynamic_cast` (`NULL` pointer), so this bug report is the same as #4673 - the same patch fixes this crash.

**Comment by akien-mga** [comment]
Closing as duplicate of #4673 then.
