### ISSUE TITLE
Can't Build the C# runtime environment

### ISSUE THREAD

**Issue by MixDino** [godotengine/godot#46157]
**Godot version:**

3.2.3.stable.official mono version

**OS/device including version:**

Windows 10 professional
Using GLES2 with GTX 760 2GB

**Issue description:**

I want to use C# in Godot,but after I followed the document to prepare the mono environment.
I can't run every project with C# script.I'm sure that I follow the document to do.
If I made mistakes,please help me solve it. Thanks.
Here are some screenshots.
![{MGLOZ)G@8(C(W8$D%{JI7V](https://user-images.githubusercontent.com/68007705/108318264-7a25ea80-71fa-11eb-8a79-104cc58a170f.png)
![3%IRKQ 14}LW2( 8TRMAT7B](https://user-images.githubusercontent.com/68007705/108318276-814cf880-71fa-11eb-84a7-c1c0cf586711.png)
![TLW}C6AM EPKI%`Y{OPU1P](https://user-images.githubusercontent.com/68007705/108318281-83af5280-71fa-11eb-83e4-6bc1f8acc80e.png)

**Steps to reproduce:**
Install the Visual Code 2019 and the .NET Framework 4.5/4.6/4.7 and others.
Open the godot.
Create a node.
Create a script with C#.
Then run it.
It won't run successfully.
**Minimal reproduction project:**

Every Project was the same in my computer.

**Comment by Torguen** [comment]
Have you configured the editor (Godot) to use an external code editor (VS Code)?

**Comment by MixDino** [comment]
> I'm not sure if this has anything to do with it but Have you configured the editor (Godot) to use an external code editor (VS Code)?

Yes，but I already can use C# now.Thank you.
