### ISSUE TITLE
Virtual function Control::can_drop_data seems ignored by the API

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4616]
The ``drag_and_drop`` demo redefines the virtual function ``Control::can_drop_data(pos, data)``: https://github.com/godotengine/godot/blob/master/demos/gui/drag_and_drop/drag_drop_script.gd#L15-L16
Apparently making the function always return false has no incidence on the drag and drop behaviour.

By looking at the source code, it seems indeed that this method is mostly useless/ignored. The only three occurences of ``can_drop_data`` are:
- Its definition in Control: https://github.com/godotengine/godot/blob/bc31be9812b165c677584a2be81a5a9bd71d8ecf/scene/gui/control.cpp#L686-L727 (see how ``drop_data`` just redoes the same checks as ``can_drop_data`` without referring to it)
- Its override in LineEdit: https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/scene/gui/line_edit.cpp#L387-L409 (same issue as above)
- A bogus call in Viewport: https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/scene/main/viewport.cpp#L1899 (IIUC it just translates to a ``true`` or ``false`` statement, so it would do nothing)

@reduz Was ``can_drop_data`` intended to be used in ``drop_data``? If not, what is it supposed to be used for?

**Comment by akien-mga** [comment]
BTW, the mentioned demo really needs some comments to be made easier to understand, and the relevant virtual methods should be documented in the classref. But it all depends on the resolution of the above issue, as right now the demo overrides a method that doesn't seem to be meaningful.

**Comment by reduz** [comment]
no.. i just didn't notice this

**Comment by akien-mga** [comment]
Nevermind, it has been removed/changed already in master :)
