### ISSUE TITLE
Directory::get_space_left() does not return consistent "failure" values

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4617]
Looking at the API for the documentation, I noticed that ``Directory::get_space_left()``:
- is only implemented on Unix
- returns ``0`` for some platforms, ``-1`` in others

For the first point, this is likely a platform limitation and just has to be properly documented. For the second point, it would be nice to streamline this by making all implementations return either 0 or -1, but not a mix of both.

- [ ] Android: Always returns ``0`` https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/platform/android/dir_access_android.cpp#L173-L176 and https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/platform/android/dir_access_jandroid.cpp#L224-L227
- [x] *Fixed by #5059.* Unix driver and OSX platform: If statvfs is enabled, returns the size on success and ``-1`` on failure. If not, returns ``0`` https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/drivers/unix/dir_access_unix.cpp#L311-L325
- [x] *Fixed by #5059.* Windows: Always returns ``-1`` https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/drivers/windows/dir_access_windows.cpp#L360-L363
- [ ] FileAccessPack: Always returns ``0`` https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/core/io/file_access_pack.cpp#L493-L496

I guess it would be best to make all error outputs be ``-1``, to make it clear that the function errored and not that the disk space available is 0 bytes?

**Comment by mattiascibien** [comment]
I will see if I can give this a go.. Would it be cool to implement it correctly also on the other platforms?

**Comment by akien-mga** [comment]
It would be great if it could be actually implemented yeah :)

**Comment by mattiascibien** [comment]
I will have a try. I am still new to thw Win32 world.
