### ISSUE TITLE
Negative delay freeze Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#46190]
**Godot version:**
Godot 3.2.4 rc 2

**OS**
Ubuntu 20.04 - Ubuntu 3.36 X11

**Issue description:**
Executing
```
OS.delay_usec(-1)
```
or 
```
OS.delay_msec(-1)
```
freeze entire Godot

**Comment by Calinou** [comment]
This is probably because the value overflows, resulting in a very long delay.

**Comment by akien-mga** [comment]
Yeah it can likely be considered working as intended... but I guess we can `ERR_FAIL` if the parameter is negative to prevent this, we don't have to support unsigned int wrapping as a feature here.

**Comment by Calinou** [comment]
The parameter is an `uint32_t`, so how can we detect whether it was actually passed as a negative value?

**Comment by akien-mga** [comment]
Maybe bind the scripting method to a proxy `_delay_usec(int p_delay)` that does the check and calls the original method, so it's still available for C++ with proper type checks.
