### ISSUE TITLE
Stutter on android 9 with 90hz updated screen

### ISSUE THREAD

**Issue by ilyapaliy** [godotengine/godot#46193]
**Godot version:** 3.2.3

**OS/device including version:**
BV9500 plus
Android 9
Screen: 1080*2160 90hz
![image](https://user-images.githubusercontent.com/34491834/108425779-001e5180-724c-11eb-9ac9-88ae7578248e.png)

**Issue description:**
Everything is cool on win 10 but, when I try run my project on android-phone, I face with stutters.

**Steps to reproduce:**
In my project I created meteor generator. It creates instances of RigitBody2D with Rigid mode. In ready method meteors gets random offset, position, rotation, liner_velocity, angular_velocity, and new scale for their Sprite and CollisionShape2D. There is no place in my game where is meteors are moved by forces, code or even collide. Their _process and _physics_process are empty, but they stuttering on the screen like some other objects before I remove some of their _physics_process code elements to the _process function. It's small jerks at perhaps regular intervals less than a second. There is nothing to lag here so I suppose this is a godot project issue. 

**Minimal reproduction project:**
My first godot project. Small enough.

**Comment by Calinou** [comment]
This is because Godot doesn't interpolate physics by default. To solve this, install, enable and configure lawnjelly's [smoothing-addon](https://github.com/lawnjelly/smoothing-addon) to benefit from physics interpolation.

**Comment by ilyapaliy** [comment]
Thanks! This addon really work, but due I generate instances of RigitBody2D in my code and there is no collision events it's easier way to me create not RigitBody2D but KenematicBody2D.
