### ISSUE TITLE
Joint name in .dae

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#462]
I'm write a tool for create .dae file format.
in ```<library_controllers>``` node at joint name section I'm do it look like this:

```XML
<Name_array id="Armature_xxxxx-skin-joints-array" count="4">
	bone00
	bone01
	bone02
	bone03
</Name_array>
```

But it can't import to Godot, to resolve this I must make it like this:

```XML
<Name_array id="Armature_xxxxx-skin-joints-array" count="4">bone00 bone01 bone02 bone03</Name_array>
```

I must prevent \t\n for resolve it

**Comment by akien-mga** [comment]
It's not really clear what is actually asked here, and since the issue is one and a half years old, I guess a workaround has been found already.
