### ISSUE TITLE
Cannot compile with MSVC with latest master

### ISSUE THREAD

**Issue by mattiascibien** [godotengine/godot#4620]
**Operating system or device - Godot version:**
Windows 10 x64 - master https://github.com/godotengine/godot/commit/b5e0729fcd21a63fc71fe2f37804a02c1d446e40

**Issue description** (what happened, and what was expected):
When compiling with Visual C++ 2015 x86 i get an error about the argument **/Wno-error=implicit-function-declaration** not being valid. It seems that a GCC switch is appended to the linker even in msvc.

**Steps to reproduce:**
Open Native Vs Command Prompt 2015 x86 and do `scons platform=windows'

**Comment by akien-mga** [comment]
Indeed, it's a regression from 2e44e255.

**Comment by mattiascibien** [comment]
Great. Thanks.
