### ISSUE TITLE
Tilemap editor "Enable Priority" affects all tilemaps in the scene

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#46209]
**Godot version:**

3.2.4.rc2.official

**OS/device including version:**

Windows 10

**Issue description:**

Enabling one tilemap priority affects on all tilemaps priority in tree.

**Steps to reproduce:**
1. select one tilemap and try to enabling priority.
2. notice that all of them changed their priority.

**Minimal reproduction project:**

here -> [New Game Project.zip](https://github.com/godotengine/godot/files/6008451/New.Game.Project.zip)

**Comment by akien-mga** [comment]
That doesn't strike me as a bug, it's a feature of the TileMap editor, not a property of the TileMap node. So it's not linked to a specific TileMap node, it's a configuration for any TileMap that uses this editor. Similarly, enabling Grid Snap in the CanvasItem editor (main 2D viewport) will affect all 2D nodes.

BTW, that option is really badly named, I couldn't figure out what it means without reading the docs: https://docs.godotengine.org/en/stable/tutorials/2d/using_tilemaps.html?highlight=priority%20tilemap#random-tile-priorities

CC @groud, I don't know if/how you're addressing this in the new TileMap editor.

**Comment by groud** [comment]
I removed this feature from the new TileMap editor. 
I think that, if you define priorities on your TileSet, then it likely means you want to use it when painting random tiles. You can still disable the "random tile painting mode" though.

But yeah, reagading the initial issue, this is indeed not linked to a specific TileMap, it's an editor feature.

**Comment by boruok** [comment]
that make sense, closing issue.
