### ISSUE TITLE
Multiple calls to create functions in visual server when multithreaded render mode set.

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#46215]
**Godot version:**

3.2.4 RC2 (but probably occurred much earlier)

**OS/device including version:**

Linux Mint 20
Intel i5 7500T

**Issue description:**

While developing Rooms & Portals PR, I found that it was failing the CI due to automated tests which ran Qarmin's test project, and reported memory leak. I managed to get his project running locally and replicating the leak.

After extensive testing I tracked it down to the line in gdscript:
```
	var object : Object = ClassDB.instance("Portal")
```
The problem is occurring because in the constructor for the Portal node, I am calling a visual server function to create a RID for a VisualServer::Portal. Although the calling site calls this one time, the call being received 10 or so times in the visual server.

I first suspected an error on my part, but it turns out, the same problem occurred with the existing Camera node, which follows the same pattern (allocates a RID from visual server in the constructor):
```
Camera::Camera() {
// where camera is a RID
camera = VisualServer::get_singleton()->camera_create();
```

Curiously when I ran the same line of gdscript in a different fresh project, the problem did not occur. It seemed there was something in the qarmin project triggering these errors. As it was likely to do with threading, I noticed that qarmin's project was set to multithreaded rendering in project settings. It turns out that setting this to single threaded cures the bug.

**Steps to reproduce:**
I was also able to replicate the exact same thing in my simple test gdscript. Create a camera, and place a breakpoint in the visual server scene camera creation code, or add a print statement. Run it in single threaded, the camera is created once. Run in multithreaded, it is created multiple times.

**Minimal reproduction project:**

[test_portal_leak.zip](https://github.com/godotengine/godot/files/6009620/test_portal_leak.zip)

**How can we address this**
There are a couple of options depending on where @reduz @RandomShaper etc think the problem lies:
1) Change Camera etc to allocate from visual server outside of constructor
2) Fix the multithread code to work correctly in this situation

Given that qarmin's project is now breaking CI, if (2) is the long term solution we could temporarily switch the CI to use single threaded.

**Comment by qarmin** [comment]
This patch fixes memory leak
```
diff --git a/servers/visual/visual_server_wrap_mt.cpp b/servers/visual/visual_server_wrap_mt.cpp
index 3a85454ae3..d5a57fac48 100644
--- a/servers/visual/visual_server_wrap_mt.cpp
+++ b/servers/visual/visual_server_wrap_mt.cpp
@@ -160,6 +160,8 @@ void VisualServerWrapMT::finish() {
        canvas_item_free_cached_ids();
        canvas_light_occluder_free_cached_ids();
        canvas_occluder_polygon_free_cached_ids();
+       room_free_cached_ids();
+       portal_free_cached_ids();
 }
 
 void VisualServerWrapMT::set_use_vsync_callback(bool p_enable) {

```

**Comment by lawnjelly** [comment]
> This patch fixes memory leak
> 

Ah excellent, well spotted qarmin. I'm not that familiar with the RID lifetimes of objects in visual server as it is really reduz area, and have just been copying pasting techniques, so was conscious I might be missing something.

I'm not sure this will solve the multiple calls problem though, will let you know! :grin:

**Comment by qarmin** [comment]
Creating multiple RID in multithreading is caused by option `Rid Pool Prealloc` (look at `memory/limist/multithreaded_server/rid_pool_prealloc`)
This looks like feature, not a bug

**Comment by lawnjelly** [comment]
Ah! That does make sense! :+1: 
In my case though it would be nice to turn it off. Although I could work around it...
