### ISSUE TITLE
Improve wording for "Invalid get index" error

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#46214]
**Godot version:**
3.2, but the same wording is used in `master`.

**Issue description:**
I lurk in the [Godot subreddit](https://www.reddit.com/r/godot/), and one of the (if not _the_) errors that beginners encounter most frequently is of the form "Invalid get index 'X' (on base 'Y')". Now, I'm an experienced programmer with many languages, but without any context this message would make little sense to me either! I think everyone would be helped if we could make this error clearer.

**First improvement:**

Simply rephrase the error as `Value of type 'Y' does not have attribute 'X'`. This is similar to Python. It also puts the arguments in the same order as they appear in the code.

If the GDScript interpreter can tell whether it's a property access or method call, it could be specified as `Value of type 'Y' does not have (property|method) 'X'`.

**Second improvement:**

Add a dedicated message for the common case of `Y == null`, such as `Tried to access attribute 'X' on a value that is null`.

Again, if we know the type of access, say `access property` or `call method` instead.

**Third improvement:** (moonshot)

This would be icing on the cake, but might be taking it too far. One of the most frequent causes of X being null is that a particular node was not found. So if X is either `$node` or a `get_node` call with a literal path, the error could be reported as `Node 'N' not found relative to 'P'`, where `N` is the NodePath of the node that doesn't exist, and `P` is the NodePath of `self`.

I'd be happy to write PRs for this if the Godot devs agree. Particularly interested in input from GDScript guru @vnen of course!

**Comment by Calinou** [comment]
> This would be icing on the cake, but might be taking it too far. One of the most frequent causes of X being null is that a particular node was not found. So if X is either $node or a get_node call with a literal path, the error could be reported as Node 'N' not found relative to 'P', where N is the NodePath of the node that doesn't exist, and P is the NodePath of self.

This is definitely a good idea as per the advice of https://github.com/godotengine/godot/issues/42719 :slightly_smiling_face:

**Comment by ttencate** [comment]
Wow, you just went ahead and did something even better. Many thanks, LGTM! :grinning:
