### ISSUE TITLE
Error calling method from signal 'timeout': SceneTreeEditor::_update_tree': Method expected 1 arguments but called with zero

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [godotengine/godot#46211]
**Godot official release version 3.2.3 release and 3.24.rc2 beta:**

**OS/device including version:**

Win 7 IDE GLES3

**Issue description:**

If you have a control node and set its MOUSE_FIILTER in gd_script then you get a series of the messages listed as the subject.

You also get them simply by changing the filter in the IDE

**Steps to reproduce:**

Open the sample project and load SettingMouseFilter.tscn then look at the output and you'll see the error.
[Emit_signal_error.zip](https://github.com/godotengine/godot/files/6008828/Emit_signal_error.zip)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
> Godot official release version 3.2.3 release and 3.24.rc2 beta:

Are you sure that you saw this in 3.2.3-stable?

This is a bug which was specific to 3.2.4 RC 2 and has been fixed since by #46031.

**Comment by TheOriginalBytePlayer** [comment]
Weird.  I am fairly sure I saw it in 3.2.3 stable because I then went and downloaded the 3.24rc2 beta to see if it had been fixed.  Though It’s conceivable I’m mixing up the issues, as I’m getting quite a number of erroneous errors, and of course, I can’t reproduce that specific issue now so you’re probably right.  

 

Sorry to bug you; I’ll reopen it if I can reproduce it again.
