### ISSUE TITLE
Subprocess can't acces files. 

### ISSUE THREAD

**Issue by WolfGames** [godotengine/godot#46213]
**Godot version:**

3.2.3 Official stable

**OS/device including version:**

NVIDIA GeForce GTX 1650
Open GL 3.0
Acer Nitro 5
Windows 10

**Issue description:**

Sub-process programs can't acces files.

Also I found: godot not responding when you use OS.execute() on console apps like CMD
I don't know it's a bug or  it's something with OS <b>[OUTDATED]</b> but file acces for sub-processes are very needed for my project to make DiscordRPC so I submit issue

**Steps to reproduce:**
1.Unpack ZIP
2.Run exe file
But if you want to check this in editor copy "GithubIssueSuff" folder to godot directory

**Minimal reproduction project:**
(Open GL 2.0)

[GithubIssue.zip](https://github.com/godotengine/godot/files/6009244/GithubIssue.zip)

**Comment by Calinou** [comment]
> I don't know it's a bug or it's something with OS but file acces for sub-processes are very needed for my project to make DiscordRPC so I submit issue

Did you look into https://github.com/Drachenfrucht1/godotcord ?

**Comment by WolfGames** [comment]
> > I don't know it's a bug or it's something with OS but file acces for sub-processes are very needed for my project to make DiscordRPC so I submit issue
> 
> Did you look into using https://github.com/Drachenfrucht1/godotcord?

No. What's this?

**Comment by WolfGames** [comment]
well I don't need godotcord.
I made VBS script instead of BAT that runs EasyRP and now console is hidden.
yay

**Comment by Calinou** [comment]
Closing, as this seems to be resolved.
