### ISSUE TITLE
Editor properties in the configuration panel should also be translatable in weblate

### ISSUE THREAD

**Issue by AndyBarcia** [godotengine/godot#46228]
I have always found it annoying that when changing the editor language the configuration panel remained in English, even though all the properties are perfectly translatable.

I don't have much experience with the engine yet. But I think that this could be fixed rather easily:

1. Change the extract.py file to also search for calls to the function _initial_set on editor_settings.cpp, and add the templates accordingly. So for example, when we find '_initial_set("interface/editor/custom_display_scale", 1.0f);' we should add "Interface", "Editor", and "Custom display scale" to the template file.
2. Change the configuration panel to use the translated strings.
3. I think that the search function also needs to be modified.

Maybe I could try to add all of this, but I may take a while, and I can only do this for version 3.2, because my computer doesn't support vulkan :p

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.

**Comment by AndyBarcia** [comment]
I don't exactly think that this is a proposal. I was planning to post it as a proposal, but I think it more as a bug.
But as you wish

**Comment by Calinou** [comment]
>  but I think it more as a bug.

A missing feature (especially one that isn't desired by everyone) isn't a bug :slightly_smiling_face:

**Comment by AndyBarcia** [comment]
But this is a problem in general when using a translated version of the engine. When I set the language to Spanish there are times that I get errors in Spanish, and I have to translate them to English to search for info in google. 
I think that the problem is not the property names, but just that using the engine in a language that is not English is a bit awkward sometimes.
