### ISSUE TITLE
Incorrect GridMap behavior with baked shadows

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#46231]
**Godot version:**
3.2.4 RC 2

**OS/device including version:**
Develop in Windows, Run in Android

**Issue description:**
GridMap objects react to both lighting and baked shadows, creating image imbalance and difficulty adjusting shadows.
Feels like they are baked and dynamically receive shade at the same time.

**Steps to reproduce:**
1. Create a Project
2. Import 3D models (or create MeshInstances)
3. Create MeshLib from pack of models
4. Create a scene with GridMap and regular objects
5. Add DirectionalLight (or another)
6. Add BackedLightmap node
7. Backed Shadows
8. Try to adjust the shadows for dynamic objects

My simple project

Full Scene
![Image 001](https://user-images.githubusercontent.com/13809475/108544060-f7cf2080-72f6-11eb-8db3-f947d5271e94.jpg)

Settings for MeshLib objects
![Image 002](https://user-images.githubusercontent.com/13809475/108544104-07e70000-72f7-11eb-9da7-0a637c667923.jpg)

Settings for regular objects
![Image 003](https://user-images.githubusercontent.com/13809475/108544134-17fedf80-72f7-11eb-8e92-9e7351f85446.jpg)

My GridMap node
![Image 004](https://user-images.githubusercontent.com/13809475/108544191-2ea53680-72f7-11eb-8060-ab71c37c2925.jpg)

Settings DirectionalLight
![Image 005](https://user-images.githubusercontent.com/13809475/108544220-3a90f880-72f7-11eb-90c0-21f3c89f1530.jpg)

Settings for BackedLightmap
![Image 006](https://user-images.githubusercontent.com/13809475/108544260-47ade780-72f7-11eb-8164-c56b1b587e53.jpg)

GridMap behavior when setting lighting AFTER baking
![2021-02-19-21-15-53](https://user-images.githubusercontent.com/13809475/108544974-3dd8b400-72f8-11eb-8c74-70ca11f86f1e.gif)

**Minimal reproduction project:**
[shadows_test.zip](https://github.com/godotengine/godot/files/6012088/shadows_test.zip)

**Comment by Calinou** [comment]
It looks like https://github.com/godotengine/godot/pull/41629 isn't applying to GridMaps?

cc @JFonS

**Comment by SkanerSoft** [comment]
Also, I noticed that when turning off Shadows to Directional Light, the GridMap objects start to flicker on my device.
No errors or warnings, just flickering.
When the shadows are turned on, the flickering disappears, but the GridMap objects become too dark where the shadow falls on them, as they receive it.

https://user-images.githubusercontent.com/13809475/108548058-5c40ae80-72fc-11eb-9d01-cef0190e370f.mp4

**Comment by Calinou** [comment]
Also, when you're using the All bake mode, you're kind of giving up on using shadows for dynamic objects.

If you want to keep shadows for dynamic objects, a good compromise is to use the Indirect bake mode for your DirectionalLight and the All bake mode for everything else. This is similar to what games like CS:GO do.

**Comment by SkanerSoft** [comment]
> Also, when you're using the All bake mode for a given light, you're kind of giving up on using shadows for dynamic objects

Sorry, I meant shading objects, not just shadows)

**Comment by NHodgesVFX** [comment]
> Also, when you're using the All bake mode for a given light, you're kind of giving up on using shadows for dynamic objects. This is a difficult-to-solve problem that should be discussed in a [proposal](https://github.com/godotengine/godot-proposals).
> 


Isnt shadowmasking and distance shadowmasking the exact solution to this problem

**Comment by Calinou** [comment]
> Isnt shadowmasking and distance shadowmasking the exact solution to this problem, granted it would need to be added to godot, So i guess that would make a good proposal.

[It is](https://docs.unity3d.com/Manual/LightMode-Mixed-Shadowmask.html), but I doubt it'll be implemented in Godot anytime soon given the added complexity.

**Comment by SkanerSoft** [comment]
Still wrong in RC 3.

**Comment by akien-mga** [comment]
Fixed by #46590.
