### ISSUE TITLE
Android device not vibrating

### ISSUE THREAD

**Issue by kjav** [godotengine/godot#46232]
**Godot version:**
Godot 3.2.2 (stable)

**OS/device including version:**
Google Pixel 4 XL

**Issue description:**
I ran the command `Input.vibrate_handheld()`, with vibrate permissions turned on in the Android export settings. The android device does not vibrate.

**Comment by kjav** [comment]
Sorry, please close this - I have discovered that there is a setting to turn off all vibration (not just for notifications). This was my issue, not a problem with Godot. I have now confirmed that it works.

**Comment by rafrafek** [comment]
For future visitors, remember to add the Vibrate permission when exporting to Android:

![image](https://github.com/godotengine/godot/assets/23004737/3257b9db-010c-40e7-82ea-f0a8dd75fe30)
