### ISSUE TITLE
SpinBox cannot be styled

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#46248]
**Godot version:**
3.2.3.official

**OS/device including version:**
Windows 10

**Issue description:**
On every other input node, the background can be set to a StyleBox. However, the appearance of a SpinBox cannot be changed from its Android 4 style default StyleBox.

**Steps to reproduce:**
1. Create a SpinBox.
2. Attempt to style it.

**Minimal reproduction project:**
Since this topic is at the Node level, I don't think a minimal reproduction project is necessary.

**Comment by Calinou** [comment]
I'm pretty sure you can theme SpinBoxes, but you have to do so indirectly by theming LineEdit (which SpinBox uses behind the scenes).

**Comment by KoBeWi** [comment]
Yep, you can't override styles for SpinBox, you need to assign a Theme and set values for LineEdit.
![W172H59GuP](https://user-images.githubusercontent.com/2223172/108612793-2da20100-73ec-11eb-8c1b-f5e316f1b561.gif)

**Comment by KoBeWi** [comment]
Well maybe this could be documented.
