### ISSUE TITLE
PoolStringArray is not updated while stored in an array or dictionary

### ISSUE THREAD

**Issue by Beuc** [godotengine/godot#46251]
**Godot version:**
3.2.3,3.2.4rc2

**OS/device including version:**
GNU/Linux

**Issue description:**
Changes to a PoolStringArray that is stored in an array or dictionary are apparently ignored.
This works when it's stored in a variable so I'd expect it works in a structure as well.

**Steps to reproduce:**
```
func _ready():
	var psa = PoolStringArray(['test'])
	psa.append('test2')
	print(psa)

	var d = {'psa':null}
	d['psa'] = PoolStringArray(['test'])
	d['psa'].append('test2')
	print(d['psa'])

	var arr = [null]
	arr[0] = PoolStringArray(['test'])
	arr[0].append('test2')
	print(arr[0])
```
```
[test, test2]
[test]
[test]
```

**Comment by pycbouh** [comment]
`Pool*Array`s are not referenced, they are copied on access. When you do `d['psa']`, you get an exact copy of a value stored at the key `psa` in `d`. You then modify that copy, but the original value remains unchanged. What you need to do is 

```gdscript
var temp = d['psa']
temp.append('test2')
d['psa'] = temp
```

This is not a bug, but intended behavior.

**Comment by Beuc** [comment]
I believe my usage warrants a solid warning at execution time, to the least, because this is introduces a major bug in the user code.

TBH even after belatedly finding "This type is passed by value and not by reference", I didn't expect that I couldn't do ```d['psa'].xxx()```, and there's no documented justification for such an error-prone behavior.

I also believe this behavior is pretty poor by any programming language standard.

Please reopen accordingly.

**Comment by pycbouh** [comment]
It's a gotcha, but it's a predictable gotcha when you know it's a value type, not a reference type. If you want some syntactic magic in GDScript for such situations, please consider making a proposal or consulting with language developers on our chat platform. I would even suggest consulting first anyway, because a proposal here would need to have a thought-out implementation.

Though, I personally would be against any changes here, because that would make it behave differently than other value types, and I've run into this problem enough times to be bothered myself.

**Comment by Beuc** [comment]
> If you want some syntactic magic in GDScript for such situations...

No no no, don't get me wrong.

"Silently passing _objects_ as values" reminds me of my darkest C++ debugging hours.
There's a reason we don't find it in any dynamic language. This goes against the [base documentation](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_advanced.html#pointers-referencing).

We need to get rid of this ASAP.

**Comment by akien-mga** [comment]
That's a duplicate of #15265.

**Comment by Beuc** [comment]
OK so this _is_ a bug.

**Comment by pycbouh** [comment]
Well, no, it's not a bug, but it's a problem 🙂 To quote the first comment by reduz:

> This is not really a bug, the problem is that PoolArrays are immutable
