### ISSUE TITLE
Double/triple click in LineEdit not working as expected

### ISSUE THREAD

**Issue by asmaloney** [godotengine/godot#46259]
**Godot version:**

3.2 branch (f15f5b45781eb3de8e5811400f654e3e49580149)

**OS/device including version:**

macOS 10.14.6

**Issue description:**

When double-clicking in a LineEdit, I would expect it to select by word. Instead it selects the entire contents of the LineEdit. I would expect triple click to select the entire contents. (This is the way applications on macOS generally work as well.)

TextEdit and the script editor work properly - line edits are not consistent with them which is confusing (and frustrating).

**Steps to reproduce:**

1. Select any node with an exported var that shows up as a line edit in the inspector.
2. Change the contents to "Foo bar blat".
3. Double-click on "bar" == the entire contents are selected instead of just "bar".

**Comment by Calinou** [comment]
I can confirm this on commit ecf432abc.
