### ISSUE TITLE
Scene invalid/corrupt after saving

### ISSUE THREAD

**Issue by Blackiris** [godotengine/godot#46260]
**Godot version:**
Godot 4.0
(commit ed8333f6bc7d0f6b721a5ddf610f1e76793cb78e)

After git bisecting, [f8d03b98e7eeeb726af4f653f1fde8b063cbad14](https://github.com/godotengine/godot/commit/f8d03b98e7eeeb726af4f653f1fde8b063cbad14) was the first commit to have this issue

**OS/device including version:**
ArchLinux

**Issue description:**
Saving scene make the scene file corrupted.

Sorry I am not good enough with Godot codebase to understand what's happening.

**Steps to reproduce:**
In the reproduction project:

1. Open res://Scenery/Infrastructure/Sliding_doors.tscn
2. Save it, close it (just the scene tab)
3. Open the scene again

You should then see "Scene file 'Sliding_doors.tscn' appears to be invalid/corrupt"

**Minimal reproduction project:**
[CorrupAfterSaveBis.zip](https://github.com/godotengine/godot/files/6015949/CorrupAfterSaveBis.zip)

**Comment by KoBeWi** [comment]
I've encountered this too. For some reason instanced scenes are stored as PackedScene sub-resources.

**Comment by hilfazer** [comment]
I didn't have this problem if my scene contained only instanced scenes, the problem appeared when those instances scenes were also inherited.
And it looks like GlassDoor.tscn is an inherited scene.

**Comment by kimamb** [comment]
I'm also getting this issue, I had to compile commit fbb1ef759c and use that.
