### ISSUE TITLE
tscn's ext_resource path is not case sensitive when launching game from the editor, but it is in builds

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#46267]
**Godot version:**

3.2.3 stable

**OS/device including version:**

Windows 10

**Issue description:**

*The backstory:*
I was making a new game and I accidentally named a folder "Prefabs" instead of "prefabs", so later I went to rename it but the editor wouldn't let me (which I assume is a separate issue), so I opened it in file explorer and renamed the folder there and everything seemed to work fine so I forgot about it, until a few days later when I tried building the game and the builds wouldn't run (cannot load file "res://Prefabs/Player.tscn")

Thankfully I tracked down the issue relatively quickly, in `World.tscn` it was referencing the player's scene like `[ext_resource path="res://Prefabs/Player.tscn" ...]` instead of `[ext_resource path="res://prefabs/Player.tscn" ...]`, which is where the player's scene was actually stored. It seems strange to me that it worked fine in the editor but not in the builds.

**Steps to reproduce:**
Open the minimal reproduction project. For me, it'll launch fine if you run it from the editor but if you try building it the build won't run.

**Minimal reproduction project:**

[CaseSensitiveIssue.zip](https://github.com/godotengine/godot/files/6016850/CaseSensitiveIssue.zip)

**Comment by KoBeWi** [comment]
This is not really a bug. Windows is case-insensitive with files by default while exported project uses custom filesystem inside .pck files, which is case-sensitive (as things should be).

The real bug is that we had a warning about this (or at least I remember seeing it), but it doesn't seem appear anymore. Weird.

**Comment by tavurth** [comment]
This issue occurs a lot for me on Mac as well, I would rather I get some error about this in the editor, even if it takes me a bit more time to fix. Having to export the project multiple times to track down these import errors from the terminal is frustrating.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/24107, which has more information about the issue at hand.
