### ISSUE TITLE
CollisionShape 'Node warning' doesn't update wen adding or removing a shape resource

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#46265]
**Godot version:**
3.2.4.rc2

**OS/device including version:**
Zorin OS 15

**Issue description:**
When adding or removing a shape resource to a CollisionShape node the 'Node configuration warning' (yellow triangle) doesn't update until you change scene tab or change something in the Scene graph

**Steps to reproduce:**
- Add a CollisionShape node
- Create a new shape resource for it.

**Minimal reproduction project:**
No need.

**Comment by KoBeWi** [comment]
This is already fixed for RC3, see #45988
