### ISSUE TITLE
Pivot point shows in Inspector for TextureProgress control when assigned a Progress Texture

### ISSUE THREAD

**Issue by remorse107** [godotengine/godot#46266]
Godot: Version 3.2.3-Stable

OS: Windows 10
GPU: Nvidia 1660 Super

Custom edit control for plugin (created as a scene file) displays a pivot point for a TextureProgress control when given a Progress Texture.  Doesn't appear to put a pivot in place for any other texture assingment.

![image](https://user-images.githubusercontent.com/7462993/108609305-aeccaa00-7392-11eb-841a-fd976cf5c23b.png)

Does not appear to do this during Run Time, but does do it while being used in the Editor under the Inspector section.

**Comment by Calinou** [comment]
@remorse107 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by remorse107** [comment]
[MinimalProject.zip](https://github.com/godotengine/godot/files/6016813/MinimalProject.zip)

**How to Reproduce the Problem**

![HowToReproduce](https://user-images.githubusercontent.com/7462993/108610434-1b4ba700-739b-11eb-8000-343d3e4d2e74.png)
