### ISSUE TITLE
Poor editor performance and high memory usage on macOS compared to 3.2.2

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#46262]
**Godot version:**
3.2.3, 3.2.4

**OS/device including version:**
MacBook Pro (Retina, 15-inch, Mid 2015)
macOS Catalina
2.2 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3
Intel Iris Pro 1536 MB

**Issue description:**
I have noticed significantly degraded editor performance and higher memory usage on recent versions of Godot compared to 3.2.2 stable. Basically 3.2.2 is great, while 3.2.3 and 3.2.4 are far less responsive in general and use way more memory. 3.2.4 RC2 seems even worse than 3.2.3, though I'm not sure if stable builds are more optimized which might account for that.

The issue does not seem project specific, and here I made a new project containing only a simple scene with a sprite animated using vertex shader. I am not running the game but just in the 2D scene preview.

Memory usage on 3.2.2:

<img width="808" alt="3 2 2 memory" src="https://user-images.githubusercontent.com/33777501/108605344-6bf5dc80-7368-11eb-8046-573793cba3e3.png">

Same scene in 3.2.3 stable:

<img width="852" alt="3 2 3 memory" src="https://user-images.githubusercontent.com/33777501/108606221-ab72f780-736d-11eb-9ad6-44e987651c65.png">

And 3.2.4 RC2:

<img width="808" alt="3 2 4 memory" src="https://user-images.githubusercontent.com/33777501/108605433-e32b7080-7368-11eb-82c2-de9778553d0f.png">

As you can see 3.2.3 and 3.2.4 are using 2 to 2.5 times as much memory compared to 3.2.2. Interestingly, I have not noticed any significant difference in CPU usage or energy.

**Comment by Calinou** [comment]
@djrain Can you try reproducing this with all the released 3.2.3 betas and RCs? You can download them [here](https://downloads.tuxfamily.org/godotengine/3.2.3/).

**Comment by djrain** [comment]
The issue is present in 3.2.3 beta 1. It's using around twice as much memory as 3.2.2 stable and editor runs noticeably slower.

**Comment by akien-mga** [comment]
Does it use less memory if you turn off 2D batching in the project settings?

**Comment by djrain** [comment]
> Does it use less memory if you turn off 2D batching in the project settings?

Nope, no difference.

**Comment by akien-mga** [comment]
Any clue on how to debug this @godotengine/macos?

**Comment by djrain** [comment]
For some reason, I am no longer able to reproduce this as before. Maybe my computer had been acting up, though it is odd considering I was experiencing the issue for some time... In any case, now the editor is snappy across versions, and I don't see any alarming differences in memory usage. So unless anyone else is having the issue, I think we can go ahead and close this for now.
