### ISSUE TITLE
Can't run any games from developers or run the engine at all [Windows] 

### ISSUE THREAD

**Issue by Beelzeguese** [godotengine/godot#46269]
**Godot version:**
3.2.3

**Issue description:**
Trying to open Godot, or run any game made with Godot, results in an empty command window opening and then closing with no background processes.

This is run on Windows. I can post specifications but I seriously have no idea why this is happening.

**Comment by Xrayez** [comment]
Please provide more information about your system as much as possible. The questions you've omitted in the template are all important to fill for issues like this. Otherwise there's nothing concrete to act upon. See also [Filing an issue on GitHub](https://docs.godotengine.org/en/stable/community/contributing/ways_to_contribute.html?highlight=bug%20report#filing-an-issue-on-github).

This may be due to incompatible/faulty GPU, drivers, and even USB peripherals that you have installed.

**Comment by Beelzeguese** [comment]
> 
> 
> Please provide more information about your system as much as possible. The questions you've omitted in the template are all important to fill for issues like this. Otherwise there's nothing concrete to act upon. See also [Filing an issue on GitHub](https://docs.godotengine.org/en/stable/community/contributing/ways_to_contribute.html?highlight=bug%20report#filing-an-issue-on-github).
> 
> This may be due to incompatible/faulty GPU, drivers, and even USB peripherals that you have installed.

I'm not going to lie to you, I'm technologically illiterate. I'm pretty sure it's due to my drivers because now after supposedly updating it says "Your video card driver does not support any of the supported OpenGL versions. Please update your drivers or if you have a very old of integrated GPU upgrade it.

Where do I find the device information I need to post to be of more help?

"

**Comment by Calinou** [comment]
> Where do I find the device information I need to post to be of more help?

- Press <kbd>Windows + R</kbd>, enter `dxdiag` in the Run dialog and press <kbd>Enter</kbd>.
- In the window that appears, answer <kbd>Yes</kbd> to the signature check (it's not important here).
- Wait a few seconds for the diagnostic to be generated.
- Click the **Save all information** button at the bottom of the window. Specify a file name (and remember it so you can open it later).
- Open the generated file and paste the contents here.

**Comment by Beelzeguese** [comment]
wait this file is huge do you need all of it ?

**Comment by Beelzeguese** [comment]
ok wait

gpu is Intel(R) UHD Graphics 630 or NVIDIA GeForce RTX 2070 SUPER?

 driver is... vulkan?

**Comment by Calinou** [comment]
@Beelzeguese Try right-clicking the Godot executable then choose **Run with graphics processor > Integrated graphics**. This could help work around https://github.com/godotengine/godot/issues/20566.

**Comment by Beelzeguese** [comment]
> **Run with graphics processor > Integrated graphics**.

i dont see this option?

**Comment by Calinou** [comment]
@Beelzeguese Are you on a laptop?

**Comment by Beelzeguese** [comment]
I am not, but the problem was simple, I used the solution from here (https://tencomputer.com/you-are-not-currently-using-a-display-attached-to-an-nvidia-gpu/) and just double clicking the program opened it normally. I apologize for my lack of computer knowledge.
