### ISSUE TITLE
TranslationServer doesn't work in tool mode

### ISSUE THREAD

**Issue by AnidemDex** [godotengine/godot#46271]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
I tried to use the [`tr` method](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-tr) to translate a label text inside the editor. 

I created a test csv file to try the translation and added the generated `.translation` files to the editor translations inside the project settings. Then I created a GDScript and added the `tool` line in the first line to test the translation inside the editor.

That didn't worked. So, I used the [`TranslationServer`](https://docs.godotengine.org/en/stable/classes/class_translationserver.html#class-translationserver) with `translate` method directly instead. That didn't work.

Finally, I tried creating [`Translation`](https://docs.godotengine.org/en/stable/classes/class_translation.html) objects directly and adding them to `TranslationServer` with `add_translation` method. And guess what, that didn't worked too.

I don't know if I'm missing something related to the translations steps, or if this is intended. I just want to translate text inside the editor to make a plugin with multiple languages using the translation feature that comes with Godot

**Steps to reproduce:**
1. Create a new project
2. Create a new scene with any kind of node as scene root, then add a label as child
3. Add some translations. You can use the one that i'll leave attached
4. Try to translate with `tr` method with a `tool` script attached inside the new scene

**Minimal reproduction project:**
[translation_test.zip](https://github.com/godotengine/godot/files/6017190/translation_test.zip)

**Comment by Calinou** [comment]
This is probably because the editor instance doesn't load your project's translation files.

**Comment by AnidemDex** [comment]
I understand, thank you for your answer. I'll close this issue and start to make my own localization system

**Comment by AnidemDex** [comment]
Just if someone in the future need something similar and there's no implementation for the editor plugin, you could try this https://github.com/AnidemDex/Godot-TranslationService 

Cheers (☞ﾟヮﾟ)☞

**Comment by TinyTakinTeller** [comment]
> Just if someone in the future need something similar and there's no implementation for the editor plugin, you could try this https://github.com/AnidemDex/Godot-TranslationService
> 
> Cheers (☞ﾟヮﾟ)☞

You can use now 
```
func translate(text: String) -> String:
	var localized_text: String
	if Engine.is_editor_hint():
		var translation: Translation = TranslationServer.get_translation_object(DEFAULT_LOCALE)
		localized_text = translation.get_message(text)
	else:
		localized_text = tr(text)

	if localized_text == "":
		return text
	return localized_text
```
