### ISSUE TITLE
Bug with warnings about non-existent project settings

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#46289]
**Godot version:**
4.0.dev.calinou.d4d753552

**OS/device including version:**
Kubuntu 20.10

**Issue description:**
When switching between categories in the Project Settings, warnings appear randomly:
```
core/config/project_settings.cpp:240 - Property not found: application/run/name
core/config/project_settings.cpp:240 - Property not found: application/run/name
core/config/project_settings.cpp:240 - Property not found: application/run/name
core/config/project_settings.cpp:240 - Property not found: application/run/description
core/config/project_settings.cpp:240 - Property not found: application/run/description
core/config/project_settings.cpp:240 - Property not found: application/run/description
core/config/project_settings.cpp:240 - Property not found: application/run/icon
core/config/project_settings.cpp:240 - Property not found: application/run/icon
core/config/project_settings.cpp:240 - Property not found: application/run/icon
...
```

It looks like the name of one category is mixed with the properties of another category.
Apparently the bug appeared after #46127 or #45956. Perhaps this is due to a change in `SectionedInspector`.

**Steps to reproduce:**
1. Open the Project Settings Editor.
2. Switch categories on the left side of the window for a while until warnings appear in the output log.
3. No patterns have been identified in this bug; when switching to a specific category, warnings may or may not appear.

**Minimal reproduction project:**
—

**Comment by dalexeev** [comment]
Same problem with editor settings.

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.alpha 174c14762fd38f8a8f0a04f69a5fdf3f81fc1b75 (Linux) on an empty project.

**Comment by dalexeev** [comment]
On alpha 6, the bug is reproduced, although it has become quite rare:

![](https://user-images.githubusercontent.com/47700418/166863345-a9771f55-98cd-4526-870e-fd1d50125999.png)

I can't reproduce the bug on alpha 7. Either it has been fixed or it has become more rare.

**Comment by KoBeWi** [comment]
Also can't reproduce anymore.
