### ISSUE TITLE
bug with drag&drop in the Scene tab

### ISSUE THREAD

**Issue by DimOkGamer** [godotengine/godot#4628]
Latest commit c7292b1

1. start dragging an unselected nodes which leads to scrolling list
2. the fall of the node, scrolling continues until the mouse click.

![2016-05-11_21-59-25](https://cloud.githubusercontent.com/assets/7782218/15192886/ea794b60-17c3-11e6-9eca-ce4e2bf79584.gif)

that's going to happen if drag selected node in a large list:

![2016-05-11_22-47-02](https://cloud.githubusercontent.com/assets/7782218/15194319/0ef7acdc-17cb-11e6-90c7-cba9fc1b1b25.gif)

**Comment by trollworkout** [comment]
OP here is a new bug to add to the list 

- If you try to place a node right after  another node with children it will become a child to that node instead of going after it. 

![rec1](https://cloud.githubusercontent.com/assets/6987027/15219243/06b74f30-1831-11e6-8e2a-f5db6e3542c4.gif)

**Comment by reduz** [comment]
ah.. i thought I added code to prevent this, but it seems it didn't work,
thanks for the report

**Comment by mefihl** [comment]
Compiled from source (2016.05.16) - Move node down with long list not work good, problem with scrollbar and mouse wheel still exists.
