### ISSUE TITLE
TCP_Server only get data one time

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#46293]
**Godot version:**
Godot 3.2.4 custom build

**OS/device including version:**
GLES3 - Windows 10

**Issue description:**
Client try to send many int data to the server but the TCP_Server only get data one time, because there are not available any signal, i'm put the func into _process

**Steps to reproduce:**
Server:
![2021-02-22_001849](https://user-images.githubusercontent.com/34160378/108632885-be87e380-74a3-11eb-8af2-b89a9f27fbb4.png)
![2021-02-22_001857](https://user-images.githubusercontent.com/34160378/108632893-c8a9e200-74a3-11eb-8bcf-4cb6413eef1d.png)
Client:
![2021-02-22_001939](https://user-images.githubusercontent.com/34160378/108632905-d6f7fe00-74a3-11eb-9c08-573ce33576f9.png)
![2021-02-22_001945](https://user-images.githubusercontent.com/34160378/108632907-d95a5800-74a3-11eb-9838-b93f5f18b71c.png)

More suggest:
Also, I'm not saw any API of StreamPeerTCP/StreamPeer contain signal when TCP_Server send back data to client like ENet
Please also improve UDP_Server of source code, get_packet() of PacketPeer in GDScript return PoolByteArray, but in source code module, it is return Error type
![2021-02-20_003144](https://user-images.githubusercontent.com/34160378/108633066-cac07080-74a4-11eb-872a-1f6d18c53ee7.png)
![2021-02-22_002813](https://user-images.githubusercontent.com/34160378/108633076-e0ce3100-74a4-11eb-9b88-91ea04b27a6d.png)

**Comment by zaksnet** [comment]
You will have to create a packet peer stream for your connection and check that peer stream for new packets inside your _process loop. Here is a basic example:

```GDScript
var server = TCP_Server.new()
var connections: Dictionary = {
	"connectionObject": {
		"packetPeerObject": ""
	}
}

func _process(delta):
	checkForConnections()
	checkForMessages()

func checkForMessages():
	for connection in connections:
		var peer = connection["packetPeer"] as PacketPeerStream
		if peer.get_available_packet_count() > 0:
			# Do something with the message/packet
			pass
	
func checkForConnections():
	if server.is_connection_available():
		var conn = server.take_connection()
		var packetStream = PacketPeerStream.new()
		packetStream.stream_peer = conn
		connections[conn]["packetPeer"] = packetStream
```

**Comment by rieniter** [comment]
> You will have to create a packet peer stream for your connection and check that peer stream for new packets inside your `_process` loop. Here is a basic example:
> 
> ```gdscript
> var server = TCP_Server.new()
> var connections: Dictionary = {
> 	"connectionObject": {
> 		"packetPeerObject": ""
> 	}
> }
> 
> func _process(delta):
> 	checkForConnections()
> 	checkForMessages()
> 
> func checkForMessages():
> 	for connection in connections:
> 		var peer = connection["packetPeer"] as PacketPeerStream
> 		if peer.get_available_packet_count() > 0:
> 			# Do something with the message/packet
> 			pass
> 	
> func checkForConnections():
> 	if server.is_connection_available():
> 		var conn = server.take_connection()
> 		var packetStream = PacketPeerStream.new()
> 		packetStream.stream_peer = conn
> 		connections[conn]["packetPeer"] = packetStream
> ```

Sorry, but this way more buggy and not effectively because checkForMessages() always running in _process, I have tried your code but get a lot of bug, because Dictionary store key-value , not the whole object, so i must refactor it, but still even not get any data from client rather than get only one

**Comment by zaksnet** [comment]
My fault, Dictionary might not work with objects as a primary key. But i',m afraid you can not avoid running the checks in the main loop. Godot is a game engine and almost everything depends on the game loop (_process or _process_physics). 
Here is a better example https://github.com/Kermer/Godot/blob/master/Tutorials/tut_tcp_connection.md

**Comment by rieniter** [comment]
> My fault, Dictionary might not work with objects as a primary key. But i',m afraid you can not avoid running the checks in the main loop because Godot is a game engine and almost everything depends on the game loop (_process or _process_physics).
> Here is a better example https://github.com/Kermer/Godot/blob/master/Tutorials/tut_tcp_connection.md

Thank you, but i have tried to follow that tutorial, but no luck, it has some problem (append is not belong to, but the main problem is the function is_connection_available() never be true after the first time received first stream packet

Updated: I also checked the source and found out that TCP_Server has private poll method, may be this is the problem? Because in UDP Server, it almost  is the same code as TCP server but it has poll() function, so UDP Server work perfectly

**Comment by Faless** [comment]
`TCP_Server` supports multiple connections.
There are various implementation that uses `TCP_Server` (e.g. the debugger) and support multiple connections.

This is likely a logical error in the code, and the issue does not even include a minimal reproduction project that actually shows a bug.
I suggest seeking help via the [community channels](https://godotengine.org/community) as this is not a support forum.
