### ISSUE TITLE
enet.h compile path error when in networked_multiplayer_enet.h

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#46300]
**Godot version:**
3.2.4 Custom Build

**OS/device including version:**
Windows 10 LTSC

**Issue description:**

![2021-02-22_044738](https://user-images.githubusercontent.com/34160378/108639821-1b49c500-74c9-11eb-9b32-3f45691b15ee.png)

![2021-02-22_044507](https://user-images.githubusercontent.com/34160378/108639811-0a994f00-74c9-11eb-98e4-581ed0544795.png)

**Steps to reproduce:**
Include networked_multiplayer_enet.h to custom module then compile and get this (Without included, it won't give any compile error)

Updated: After fix to thirdparty/enet/enet/enet.h, it give more path error:
![2021-02-22_050028](https://user-images.githubusercontent.com/34160378/108640218-00785000-74cb-11eb-8be8-355c41c1db03.png)

**Comment by Calinou** [comment]
Can you link to your module somewhere? Without access to your module's source code, there's nothing we can do to help.

**Comment by rieniter** [comment]
> @rieniter Is your module available somewhere? Without access to your module's source code, there's not much we can do to help.
> 
> Also, it's likely a better idea to ask module development questions on other [community channels](https://godotengine.org/community) like Discord.

No, i just created fresh module to test, as i was describe, it only get this error when include that file into an module (if not include that file into an module, it compiled OK without any problem).

I have checked github source code, it also #include "enet/godot.h", while compiled in Windows 10, it doesn't know what path, after change above path to "thirdparty/enet/enet/enet.h" and some other the file in this enet folder too, it will worked fine again. So i think the source code should be change this path correctly

**Comment by akien-mga** [comment]
You should set the include path like the module does itself: https://github.com/godotengine/godot/blob/master/modules/enet/SCsub#L26

**Comment by rieniter** [comment]
> You should set the include path like the module does itself: https://github.com/godotengine/godot/blob/master/modules/enet/SCsub#L26

Thank you, i don't know this way existence
