### ISSUE TITLE
ssl certificates property does not present

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#4630]
certificates property described in:
http://docs.godotengine.org/en/latest/tutorials/ssl_certificates.html
it is not present

**Comment by akien-mga** [comment]
I think the SSL certificate was made editor-wide, as it's needed for the assets lib, but will have to check.

**Comment by hubbyist** [comment]
There is a setting in the application group but it does not have a file dialog icon.

![projectsettings_certificates](https://cloud.githubusercontent.com/assets/5895328/15855151/97f38664-2cb6-11e6-8fb9-a15de939ff1a.png)

**Comment by J08nY** [comment]
This is fixed in current `git master`
![screenshot from 2016-06-07 13-09-43](https://cloud.githubusercontent.com/assets/1296726/15855695/2f0a388c-2cb1-11e6-8434-bef8a2230de1.png)

**Comment by vnen** [comment]
@J08nY indeed, thanks for noticing.
