### ISSUE TITLE
Godot in app purshaces first party license problem

### ISSUE THREAD

**Issue by mani144** [godotengine/godot#46318]
**Godot version:**
3.2.3

**OS/device including version:**

Android

**Issue description:**

Greetings

I have been trying to develop a game and use iap ( first-party plugin)

However, there was a problem with the purchases licenses
I could not find anywhere to place a Google license into Godot project neither the doc ( or the example) is talking about this.
I uploaded my game into Google play and I tried to use this plugin without a Google license but I could not use it

I tried every possible issue and topics and could not find any resource

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
cc @timoschwarzer 

@mani144 there's a dedicated repo for the iap plugin, can you open a ticket there instead
https://github.com/godotengine/godot-google-play-billing

**Comment by mani144** [comment]
@akien-mga i opened the ticket because noone replayed in the first party plugin issue page. 

https://github.com/godotengine/godot-google-play-billing/issues/23
