### ISSUE TITLE
Pack file unloads itself?

### ISSUE THREAD

**Issue by ChronoDK** [godotengine/godot#46311]
**Godot version:**
3.4.2.rc2

**OS/device including version:**
Windows, Chrome, HTML5 build

**Issue description:**
I'm downloading a pack file and loading it using ProjectSettings.load_resource_pack, which seems to work just fine. But after the game has been running for an hour or so, it freezes and prints this error:

![image](https://user-images.githubusercontent.com/626662/108700235-98dff600-7506-11eb-8105-55be115381ef.png)

To me it looks like the pack file unloads itself?

**Steps to reproduce:**
Download a pack file using a httprequest, then load it using this code:

```gdscript
func _on_HTTPRequest_request_completed(_result, response_code, _headers, body):
    var file = File.new()
    file.open("user://pack.zip", File.WRITE)
    file.store_buffer(body)
    file.close()
    ProjectSettings.load_resource_pack("user://pack.zip")
```

**Comment by Calinou** [comment]
@ChronoDK Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by ChronoDK** [comment]
I'm not exceeding the IndexedDB storage limit, but could this happen because the files in IndexedDB are wiped out randomly by the browser? Or does load_resource_pack just load the resources to memory, and then not care about the original file anymore (as I hoped it would)? 

The resources seem fine too when not loaded from this extra pack, and just included in the original build instead. Crashes only occur when resources are loaded from a pack. It's just impossible to pinpoint the reason cause crash times seem so random. 

Maybe some wasm signature is destroyed when a resource pack is loaded?

**Comment by Calinou** [comment]
@ChronoDK Bump :slightly_smiling_face: There is still no reproduction project available, which means nobody can look into fixing this.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
