### ISSUE TITLE
Godot 3.2.4rc2 - Capabilities - Game Center missing

### ISSUE THREAD

**Issue by MarcusDobler** [godotengine/godot#46337]
**Godot version:**

3.2.4 rc2 (official)

**OS/device including version:**

Mac OS 11.2.1 - Mac Book Pro 13" - Apple M1

**Issue description:**

In the iOS export template capabilities missing. I can't use Game Center

**Steps to reproduce:**

Just try to export, you will see capabilities are missing!

**Minimal reproduction project:**

<img width="648" alt="Bildschirmfoto 2021-02-23 um 05 36 17" src="https://user-images.githubusercontent.com/16276195/108802606-15231980-7599-11eb-8fd9-8571d06ef13a.png">

**Comment by bruvzg** [comment]
GameCenter support was moved to from the core engine to standalone plugin: https://github.com/godotengine/godot-ios-plugins.

**Comment by Calinou** [comment]
Closing per @bruvzg's comment.
