### ISSUE TITLE
ColorPicker eyedrop doesn't work

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#46334]
**Godot version:**

c5a88e6

**OS/device including version:**

Windows 10

**Issue description:**

Nothing happens when you click it
![image](https://user-images.githubusercontent.com/2223172/108791504-86ee6980-757f-11eb-8af4-a1ea39bf2e39.png)

**Comment by Calinou** [comment]
This is likely a regression from the DisplayServer changes.

**Comment by KoBeWi** [comment]
I checked the code. The picker will create a screen-sized control and listen for its input. The problem is that the control is on main window and it won't get any input, because picker popup is focused. There's also this comment
https://github.com/godotengine/godot/blob/d9d920ed6cd54d641a7c998d3656adf7e12a13c8/scene/gui/color_picker.cpp#L1009-L1014

**Comment by DleanJeans** [comment]
Coming across this bug, sometimes I can get a color preview but most times I don't. Clicking will select the node instead of saving the selected color.
