### ISSUE TITLE
Change drag preview property cause crash when exported in release mode only

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#46335]
**Godot version:**
3.2.3 official(steam version)

**OS/device including version:**
windows 10 professional

**Issue description:**
Change drag preview property will cause crash on build version( no crash on debug export or in game engine)

**Steps to reproduce:**
1. Add a itemlist and give it a preview
2. Change preview text in gui_input(check whether the preview is exist)
3. Run in godot or export debug version, run well
4. Export non-debug version. crash when drag

Use call_deferred cannot fix the crash
Maybe some relation with[#36724](https://github.com/godotengine/godot/issues/36724)

**Minimal reproduction project:**
[PreviewCrash.zip](https://github.com/godotengine/godot/files/6026612/PreviewCrash.zip)

**Comment by firecloud888** [comment]
Set preview to null when drop data can fix the crash
func drop_data(position, data):
  preview = null
  return
Maybe drop data break the gui_input process and free the preview node just before "if preview != null"

**Comment by nmrkr** [comment]
The engine takes ownership of whatever control you throw at `set_drag_preview`. Once the drag is completed, the control is deleted by the engine itself. Your var `preview` then becomes invalid. So it makes sense that clearing the var mitigates the crash.

**Comment by KoBeWi** [comment]
Upgrade to 3.2.4 and change your check to `if preview` or `if preview != null`, you will get error in debug build. To avoid it properly you should do `if is_instance_valid(preview)`.

Here's a similar recent issue: #46359
Tagging as documentation, #46360 will resolve this.

**Comment by firecloud888** [comment]
> Upgrade to 3.2.4 and change your check to `if preview` or `if preview != null`, you will get error in debug build. To avoid it properly you should do `if is_instance_valid(preview)`.
> 
> Here's a similar recent issue: #46359
> Tagging as documentation, #46360 will resolve this.

That will fix the crash, thanks!
