### ISSUE TITLE
HTML5 Export broken in 3.2.4RC3

### ISSUE THREAD

**Issue by gianmichelemariani** [godotengine/godot#46352]
**Godot version:**
3.2.4RC3

**OS/device including version:**
Macbook Pro 13" Intel
OSX 10.15.7

**Issue description:**
When using the Run in Browser export, an error is produced.

I've attached a couple of screenshots from both Chrome and Safari.

Note that the previous RC was working as expected.

<img width="991" alt="safari" src="https://user-images.githubusercontent.com/46694168/108880325-18022680-75fa-11eb-98f6-c5da5fed289d.png">
<img width="659" alt="chrome" src="https://user-images.githubusercontent.com/46694168/108880326-19335380-75fa-11eb-8819-82917081b737.png">

**Steps to reproduce:**
Try to run any project on the web.

**Comment by daveTheOldCoder** [comment]
I can confirm this issue.

A project that successfully works with HTML5 / Run in Browser in Godot 3.2.3 fails with 3.2.4RC3.
In my case, the browser window is blank, except for a small white dialog box that contains nothing but an "OK" button. If I click the button, the message "indirect call to null" is displayed.

**Comment by Faless** [comment]
After some debugging and a bisect session, I found out only the threaded build is working.

Seems like `NO_THREADS` builds are broken after #46197 , @hpvb @RandomShaper any idea? Sadly the wasm binary doesn't give you much info, the only thing I know is that I'm getting a `null` pointer exception during startup (I think in `Main::setup`, but I'm not really sure). I'll keep digging and try to see if I can make a native build with NO_THREADS so I can get a better debug output from `gdb`.

**Comment by daveTheOldCoder** [comment]
Can you explain the difference between threaded builds and NO_THREADS builds? Does that refer to multi-threading support?
The file I downloaded was Godot_v3.2.4-rc3_x11.64.zip.

**Comment by Faless** [comment]
> Can you explain the difference between threaded builds and NO_THREADS builds? Does that refer to multi-threading support?

It was meant as in internal reference to the people I tagged.

But in this context it means build without thread support, yes.
See export options: https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#export-options

**Comment by daveTheOldCoder** [comment]
Thanks for the explanation. I thought it might refer to a difference among the RC3 downloads. I just verified that the HTML5 export of my project works if I select Export Type as Threads, rather than Regular. Which, of course, you already know.

**Comment by chucklepie** [comment]
Hello, which release candidate will this be in? I'm asking because rc4 fixes quite a lot of bugs and issues I'm experiencing but also want to release a html as well as binary version and don't want to mix Godot versions...

btw, if this helps with anything (probably not), if you enable Threads in the HTML build then it works under Chromium (but not Firefox).

Thanks.

**Comment by Calinou** [comment]
@chucklepie Please don't bump other people's issues to ask for support.
