### ISSUE TITLE
`ProjectSettings.save()` does nothing

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#46358]
**Godot version:**

3.2.3.stable

**OS/device including version:**

Windows 10 Home 1909

**Issue description:**

I wanted to save the ProjectSettings which I configured earlier with `ProjectSettings.set_setting("application/run/main_scene", "res://title_screen/title_screen.tscn")`, which works because when I do `print(ProjectSettings.get_setting("application/run/main_scene")`, I get "res://title_screen/title_screen.tscn" printed, with `ProjectSettings.save()`. I even disabled safe save in EditorSettings and my antivirus. For days I ask myself where the problem is.

**Steps to reproduce:**
in script: change any ProjectSetting and then save it.

**Minimal reproduction project:**

[Bug_REPRODUCTION.zip](https://github.com/godotengine/godot/files/6031879/Bug_REPRODUCTION.zip)

**Comment by KoBeWi** [comment]
Seems like you can't modify ProjectSettings from within running project. It works when you add `tool` to your script. Probably should be documented.

**Comment by MaaaxiKing** [comment]
But why does the method exist then? To me it seems like a bug.

**Comment by MaaaxiKing** [comment]
After disconnecting from my Android phone I got
```
E 0:10:43.140   _save_settings_text: Couldn't save project.godot - project.godot.
  <C++ Error>   Condition "err != OK" is true. Returned: err
  <C++ Source>  core/project_settings.cpp:755 @ _save_settings_text()
  <Stack Trace> tutorial.gd:36 @ next()
                tutorial.gd:29 @ _input()
```
. I don't know if this helps.

**Comment by MaaaxiKing** [comment]
For me, it does not work with `tool`.

**Comment by Ev1lbl0w** [comment]
This was fixed by #45880

**Comment by KoBeWi** [comment]
> For me, it does not work with tool.

You need to call it from the editor. It won't work in the running project.

> This was fixed by #45880

It's unrelated.

**Comment by Ev1lbl0w** [comment]
Sorry, I forgot to show my findings. :sweat_smile:

It looks like `ProjectSettings.save()` works; the issue is that, as soon as the editor is re-focused, it saves the project settings, thus overriding any modifications done externally
![clip](https://user-images.githubusercontent.com/6501975/109006137-a92cd800-76a2-11eb-8a3f-5dfcc4447e1f.gif)

**Comment by KoBeWi** [comment]
Ah you are right, although the PR that fixed this is #45968 
I wonder if it works in exported project though.

**Comment by MaaaxiKing** [comment]
That should be documented!

**Comment by Zireael07** [comment]
No need to document something that's already fixed @MaaaxiKing

**Comment by KoBeWi** [comment]
Ok so it works in exported project too, but the modified settings can't be loaded. This might be worth mentioning in the doc.

**Comment by MikeSchulze** [comment]
This bug needs to be merged into v3.x aswell.
My inital plugin setting are not saved ;)
