### ISSUE TITLE
Project Manager dosen't update last modified project [3.2.4.rc3]

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#46356]
**Godot version:**
Godot_v3.2.4-rc3_mono_win64

**OS/device including version:**
Win10 1650 Nvidia

**Issue description:**
I opened a project and edited it. The closed Godot.
Then I relaunched Godot, and saw the last edited project was not at the top of the project manager (which is sorted by 'Last Modified').

The last modified project should be sorted to the top of the project manager if sorted by 'last Modified' date, like in 3.2.3 stable.

**Steps to reproduce:**
Open Godot, edit a project, close. Repopen the project manager and see.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is probably a side effect of https://github.com/godotengine/godot/pull/45968. We can rename the Last Edited option to Last Modified again.

**Comment by KoBeWi** [comment]
We could "fix" this by saving the project once immediately after loading.

**Comment by aaronfranke** [comment]
@KoBeWi This would be a good idea. With #45968, currently it doesn't save the `project.godot` file at all until after something is modified about it (like the project name or description). This causes other problems, such as if `config_version` is incremented [like in this PR](https://github.com/godotengine/godot/pull/31171), currently the incremented `config_version` is not saved automatically.

**Comment by OlexiyKravchuk** [comment]
Why is the issue closed?
I have the same problem in stable version 3.3.

**Comment by Calinou** [comment]
> Why is the issue closed?
> I have the same problem in stable version 3.3.

This was reopened as a proposal in https://github.com/godotengine/godot-proposals/issues/2669.

**Comment by OlexiyKravchuk** [comment]
> This was reopened as a proposal in godotengine/godot-proposals#2669.

As far as I understand, they offer based on views, and this is different, but I need to order it according to the last changed and saved project and this does not work as before.

**Comment by KoBeWi** [comment]
Seems like the fix was only cherry-picked to 3.4, 3.3 still has this issue.

**Comment by OlexiyKravchuk** [comment]
OH! I was hoping to get this in the next hot fix, 3.3.1, within a week.

**Comment by Sslaxx** [comment]
It is, see https://github.com/godotengine/godot/issues/48507
