### ISSUE TITLE
macOS errors with new builtin ui_* input actions

### ISSUE THREAD

**Issue by gitcatrat** [godotengine/godot#46369]
**Godot version:** master

**OS/device including version:** macOS Catalina 10.15.7, Radeon Pro 555, Vulkan

**Issue description:**

These errors show up in terminal every time I start Godot from terminal, e.g `./bin/godot.osx.tools.64.mono`.

![err2](https://user-images.githubusercontent.com/58787197/108991233-826da200-76a0-11eb-8a21-2c6fe360152c.png)

`ui_pageup` and `ui_pagedown` errors fire (always in a pair) every time output is focused and I press any key.

![err](https://user-images.githubusercontent.com/58787197/108990972-2efb5400-76a0-11eb-869d-64751ecae6cb.png)

**Steps to reproduce:**
No steps really, just boot up a compiled master binary, open a project and check the terminal errors. As always, if you need anything else like my compiled binary or more information, just ask and I'll gladly provide.

**Minimal reproduction project:**

[issue.zip](https://github.com/godotengine/godot/files/6035413/issue.zip)

**Comment by akien-mga** [comment]
The two types of errors are not related to each other so I'd suggest opening another issue for the `!windows.has(p_window)` one (if not reported already), so we can focus on the `ui_*` actions errors here.

CC @EricEzaM, likely regression from #43663.

**Comment by gitcatrat** [comment]
Opened https://github.com/godotengine/godot/issues/46370, will edit this.

**Comment by EricEzaM** [comment]
Hello, please see attached pull request. I cannot test on Mac, so I would really appreciate it if you could test it.

1. Check that errors are gone
2. Ensure that "ui_text_backspace_all_to_left" in editor shortcuts is still assigned to `Command + Backspace`

**Comment by gitcatrat** [comment]
@EricEzaM 

1. ✅ 
2. ✅ 

Great job, thanks!
