### ISSUE TITLE
Crashes when using arrow keys in Quick Open Scene or Instance Child Scene

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#46361]
**Godot version:**
3.2.4.rc2.official

**OS/device including version:**
win 10 64

**Issue description:**
At the "Quick Open Scene.." menu or the "Instace Child Scene.." menu, using the arrow keys to select a scene crashes the engine. No error is shown using --verbose with the official builds. 

**Steps to reproduce:**
- In any project with at least one scene, open the "Quick Open Scene" menu
- Press down or up a few times
Expected: 
 - Pressing down should select the next scene in the list, and pressing up the previous one.
 Actual:
 - Sometimes pressing up selects the next scene, sometimes pressing up or down crashes the engine.

**Minimal reproduction project:**
I could reproduce it with any project with at least one scene.

**Comment by KoBeWi** [comment]
This is fixed in rc3.
