### ISSUE TITLE
Cannot Update position of a KinematicBody2D

### ISSUE THREAD

**Issue by cub525** [godotengine/godot#46362]
**Godot version:** Godot Engine v3.2.3.stable.official

**OS/device including version:**
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)         
System Manufacturer: Microsoft Corporation
System Model: Surface Laptop 3
BIOS: 9.102.140 (type: UEFI)
Processor: Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 CPUs), ~1.5GHz
Memory: 8192MB RAM
DirectX Version: DirectX 12
User DPI Setting: 144 DPI (150 percent)
System DPI Setting: 144 DPI (150 percent)
DWM DPI Scaling: UnKnown
Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
DirectX Database Version: 1.0.8
DxDiag Version: 10.00.19041.0546 64bit Unicode

**Issue description:**
Assigned the position of a KinematicBody2D in the _ready funtion, failed to assign
![image](https://user-images.githubusercontent.com/49500036/108922394-4e3ca780-75f4-11eb-92eb-b06b0d6b81af.png)
The output shows the issue (in the output)

**Minimal reproduction project:**
Project Files res://Character.gd, the _ready method
[Issue.zip](https://github.com/godotengine/godot/files/6032335/Issue.zip)

**Comment by nisovin** [comment]
You have the "Sync to Physics" option enabled on your KinematicBody2D. This delays the update of your position until the physics tick.

**Comment by cub525** [comment]
I toggled Sync to Physics and that seems to have solved the problem (it was off before).

**Comment by pouleyKetchoupp** [comment]
I'm closing the issue since the explanation from @nisovin clarifies what's going on with the prints and the issue seems to be solved.

@cub525 Feel free to re-open in case you need more help.

**Comment by cub525** [comment]
I think it was just user error, and I got everything working.
