### ISSUE TITLE
Edge and face artifacts with SSAO and 2x MSAA

### ISSUE THREAD

**Issue by gitcatrat** [godotengine/godot#46368]
**Godot version:** master

**OS/device including version:** macOS Catalina 10.15.7, Radeon Pro 555, Vulkan

**Issue description:**

Issue looks like this, take a closer look at black edges and patterned face artifacts. Artifacts are not static, i.e if you move camera around, they disappear and appear in different locations or doesn't appear at all in some angles.

<img width="333" alt="normal" src="https://user-images.githubusercontent.com/58787197/108989979-e727fd00-769e-11eb-8236-8e805b63e681.png">
SSAO texture looks fine although this issue only shows up if both 2x MSAA and SSAO are enabled.

<img width="360" alt="ssao" src="https://user-images.githubusercontent.com/58787197/108989986-e8f1c080-769e-11eb-8609-b28cb29d4c8f.png">

**Steps to reproduce:**
* Make a new project
* Add few meshes
* Enable SSAO
* Enable AA and choose 2x MSAA

**Minimal reproduction project:**

[issue.zip](https://github.com/godotengine/godot/files/6035357/issue.zip)

**Comment by gitcatrat** [comment]
Arifacts DO NOT appear if SSAO or AA is disabled or another MSAA multiplier is used.

**Comment by Calinou** [comment]
I can't reproduce this on Fedora 33 with a GeForce GTX 1080.

<details>
<summary>Screenshots</summary>

### No MSAA, no FXAA
![msaa_0_fxaa_0](https://user-images.githubusercontent.com/180032/109009657-16466a80-76af-11eb-8d45-acae559a1b05.png)

### No MSAA, FXAA enabled

![msaa_0_fxaa_1](https://user-images.githubusercontent.com/180032/109009662-16df0100-76af-11eb-89ed-22b4b54f9870.png)

### 2× MSAA, no FXAA

![msaa_2_fxaa_0](https://user-images.githubusercontent.com/180032/109009663-17779780-76af-11eb-8714-46acebf8d4ce.png)

### 2× MSAA, FXAA enabled

![msaa_2_fxaa_1](https://user-images.githubusercontent.com/180032/109009665-17779780-76af-11eb-95f9-dd249adcf5bd.png)

### 4× MSAA, no FXAA

![msaa_4_fxaa_0](https://user-images.githubusercontent.com/180032/109009667-18102e00-76af-11eb-802b-cb20f31bdd88.png)

### 4× MSAA, FXAA enabled

![msaa_4_fxaa_1](https://user-images.githubusercontent.com/180032/109009668-18102e00-76af-11eb-8cee-ed6f5915f3ef.png)
</details>

**Comment by Flavelius** [comment]
I'm experiencing similar artifacts, even with msaa disabled, although they are more pronounced with it enabled:
![grafik](https://user-images.githubusercontent.com/8841352/110245637-62719480-7f64-11eb-9e13-2583d70d9184.png)
Win10, gtx1060
i suspect this has something to do with the depthbuffer itself as i get similar low precision artifacts with custom depth projecting /decal shaders

**Comment by Calinou** [comment]
@Flavelius The SSAO algorithm used in 3.2.x is entirely different from ASSAO which is used in the `master` branch. To combat these artifacts, you need to *increase* the camera's Near property as much as you can and decrease the Far property as much as you can.

**Comment by Flavelius** [comment]
That doesn't seem to help. I reduced the clipping planes to 80-180, so most of the world is already clipped away, and it's still the same:
![grafik](https://user-images.githubusercontent.com/8841352/110245916-9a2d0c00-7f65-11eb-908a-5a4edbf97143.png)

**Comment by Calinou** [comment]
@Flavelius Please open a separate issue about this – it's an unrelated problem. Also, make sure to include a minimum reproduction project and a screenshot *at the same location* with SSAO disabled.

**Comment by Calinou** [comment]
@gitcatrat  Can you (or anyone else) still reproduce this bug in [Godot 4.0alpha3](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-3) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
