### ISSUE TITLE
Impossible to resize collision shape for tile when vertex outside of tilesheet

### ISSUE THREAD

**Issue by dszhblx** [godotengine/godot#46367]
**Godot version:**

Godot_v3.2.4-rc3_win64

**OS/device including version:**

Win10

**Issue description:**

Impossible to resize collision shape for tile when vertex outside of tilesheet
same as https://github.com/godotengine/godot/issues/34970

**Steps to reproduce:**
same as https://github.com/godotengine/godot/issues/34970

**Minimal reproduction project:**

same as https://github.com/godotengine/godot/issues/34970

**Comment by akien-mga** [comment]
If it's all exactly the same as #34970, let's just reopen #34970 instead of having another issue without additional information.
