### ISSUE TITLE
Spatial shader triplanar mapping binormals are flipped on the y axis.

### ISSUE THREAD

**Issue by victfv** [godotengine/godot#46363]
Godot version: 3.2.4 RC3

Windows 10.0.18363

GTX 650 Ti 2GB, Driver version 461.40, GLES3

**Issue description:**
After activating the triplanar checkbox in a spatial material, the normals seem to be flipped in some directions.
After converting to a shader material and looking at the vertex function, it seems the binormals are flipped.
In the shader they are as such:
```
BINORMAL = vec3(0.0,-1.0,0.0) * abs(NORMAL.x);
BINORMAL+= vec3(0.0,0.0,1.0) * abs(NORMAL.y);
BINORMAL+= vec3(0.0,-1.0,0.0) * abs(NORMAL.z);
```
While changing them to:
```
BINORMAL = vec3(0.0,1.0,0.0) * abs(NORMAL.x);
BINORMAL+= vec3(0.0,0.0,-1.0) * abs(NORMAL.y);
BINORMAL+= vec3(0.0,1.0,0.0) * abs(NORMAL.z);
```
Seemed to fix the problem.

**Steps to reproduce:**
1. Create a new project.
2. Add a mesh instance and assign any mesh.
3. Create a spatial material and assign it to the mesh.
4. Assign a normal map to the spatial material.
5. Click the triplanar checkbox in the UV 1 dropdown.
6. Add a light to the scene and observe the behavior of the material when the light is moved.
[Triplanarbug.zip](https://github.com/godotengine/godot/files/6032960/Triplanarbug.zip)

**Minimal reproduction project:**

[Triplanarbug.zip](https://github.com/godotengine/godot/files/6032973/Triplanarbug.zip)

**Comment by Zylann** [comment]
![TestNormal_normal](https://user-images.githubusercontent.com/1311555/108987998-da4dde00-768b-11eb-95ea-dfeb04f3092f.png)
This doesn't look like a proper normal map. Tangent space normal maps are supposed to be blue-ish in flat regions.

**Comment by victfv** [comment]
This normal map is generated in Material Maker and I assumed Godot doesn't use the blue channel. It works well on UV mapped surfaces, I added a blue channel to it and the problem still persists. If I flip the green channel if fixes the triplanar material, but breaks the UV mapped material. The UV mapped materials seem to use X+ Y+ Z+ normal maps and the triplanar seems to use X+ Y- Z+ normal maps.
With this one, it looks fine if I use UVs, but broken if I use triplanar mapping.
![Normal+++](https://user-images.githubusercontent.com/25274301/109006317-b7bac580-7689-11eb-970d-4d0580532fde.png)
This one looks fine with triplanar mapping, but broken with UVs.
![Normal+-+](https://user-images.githubusercontent.com/25274301/109006465-dde06580-7689-11eb-966d-18142c7195ad.png)
All I did was switch the green channel.

**Comment by Calinou** [comment]
@Zylann Godot performs RGTC compression of normal maps.

**Comment by victfv** [comment]
@Calinou That's strange, because the first normal map from my previous comment is working as intended, while the second is not. I even tested in 3.2.3 and the same thing happens. But the issue is that UV mapping and triplanar mapping expect different Y directions.

**Comment by Zylann** [comment]
> @Zylann Godot performs RGTC compression of normal maps. The blue channel is discarded as it can be reconstructed in the shader from the two other channels.

This is why I precised in parenthesis that this is the PNG as is, not the imported result. I know Godot does this. You mean it can also accept pre-compressed normalmaps?

**Comment by Calinou** [comment]
> You mean it can also accept pre-compressed normalmaps?

It should accept normal maps already in RGTC format.

**Comment by Arnklit** [comment]
Just wanted to confirm as well. I've just been running into this issue

https://user-images.githubusercontent.com/4955051/123541507-e2528300-d73c-11eb-926e-304e2eed068a.mp4

Left: Standard UV. Middle: Standard triplanar UV. Right: Custom triplanar shader with binormals inverted.

I had found the the same solution as victfv of inverting the three binormals.

**Comment by Calinou** [comment]
I can confirm this issue on `master` Git 659178e85:

![image](https://user-images.githubusercontent.com/180032/123547884-d5488a80-d762-11eb-83b7-9195b51df709.png)
