### ISSUE TITLE
replaying an edited scene after a bug does not replay the former edited scene by default

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4637]
**Operating system or device - Godot version:**
official 2.0.2stable win64

**Issue description** (what happened, and what was expected):

Lets say I have two scene opened into the editor. Scene A and B.

When I work on Scene A and press the "Play the edited scene" (F6) and that a bug occurs into one of its scripts, the debugger appears and the "Play the edited scene" button is changed into a "Replay" button.

If I edit Scene B and press the "replay" button, this is Scene B that is played instead of Scene A that should be replayed.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
I don't think this is a bug. The button is meant to play the **current** scene. It works as a replay to save the trouble of stopping and playing again. This is more of a wording issue, but an option to actually replay the scene might be added.

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
