### ISSUE TITLE
Game Crashes in Release Mode giving logs from previous versions

### ISSUE THREAD

**Issue by wenderRondonia** [godotengine/godot#46377]
Godot 3.2.3 (tried on all release versions until 3.1 reimporting etc)

GLES2 Windows 10

The game runs fine in debug mode but crashes  in release mode after few interactions giving strange log that I written long time ago,
what could be happening and how can I avoid this?

**Comment by wenderRondonia** [comment]
It seems related to queue_free, I used all possible checks and now it works with 'is_instance_valid' and 'is_queued_for_deletion'
I think it is strange that it worked on debug mode and not release mode.

**Comment by akien-mga** [comment]
That's a bug in 3.2.3, if you use 3.2.4 RC 3 the debug mode should raise errors about those.
