### ISSUE TITLE
HTML5 export, OS.window_size has wrong value

### ISSUE THREAD

**Issue by isokissa** [godotengine/godot#46372]
**Godot version:** 3.2.3

**OS/device including version:** running godot on Linux (Lubuntu/Ubuntu)

**Issue description:** When export to HTML5 and run in (firefox) browser, the game kind of runs but no red ball is shown. When I run the game in Godot or when I generate executable for Linux, it works correctly, the red ball is shown:
![image](https://user-images.githubusercontent.com/2178475/109003557-42162000-76b0-11eb-86f2-2ae73f34ecd5.png)

**Steps to reproduce:** clone the https://gitlab.com/isokissa/games/zivac, export game to HTML5, start the local server and goto localhost:<port>, or go to https://isokissa.gitlab.io/games/zivac/ to see the game which does not show the red ball. When you run within Godot, or exported to Linux executable, there is a red ball 

**Minimal reproduction project:** https://gitlab.com/isokissa/games/zivac (it is just a beginning of the project: look at the arena/arena scene, where Ball scene is instantiated. That Ball scene from Arena is not shown when run in HTML5 export)

**Comment by Calinou** [comment]
I can confirm this on Chromium 87 and Firefox 86 (Linux).

**Comment by isokissa** [comment]
@Calinou using sprite did not help. It is again visible when running as application, but not in browser.

**Comment by isokissa** [comment]
@Calinou apparently it depends on the shape of the browser screen. If it's wide so that black areas are shown on the side, then the ball does not show. If the windows is narrow, so that black areas are on top and bottom, then the ball is shown, but at wrong place (I guess also in wide case it is in wrong place, but out of screen, so that's the reason why it is not shown) 

![image](https://user-images.githubusercontent.com/2178475/109296123-8502ff80-7838-11eb-9e80-c6efa845401a.png)


This means, the problem is that HTML5 export, this code 

```
func ball_spawn(): 
	var middle: Vector2 = OS.window_size / 2
	get_node("Ball").position = middle
```

does not put Ball in the middle of the window as when ran standalone  (Ball's position (0,0) is in the origin)

**Comment by Kitsee** [comment]
This is not a bug, you're using the wrong variable, OS.window_size gives you the size of the container the game exists within not the size of the game's viewport or in other words the size including the black bars. the correct variable you wanted would be get_tree().get_root().get_size(), this give you want the game's main viewport size after stretch mode has been applied / after the black bars have been applied.
