### ISSUE TITLE
Build error with Clang due to libatomic static linking

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#46375]
**Godot version:** Git `master` https://github.com/godotengine/godot/commit/f3864ec89f337ad1454a7112ba47896f2524ba9b (also occurs on the latest `3.2` branch)

**OS/device including version:** Fedora 33

```
❯ clang --version
clang version 11.0.0 (Fedora 11.0.0-2.fc33)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

❯ ld.lld --version
LLD 11.0.0 (compatible with GNU linkers)
```

**Issue description:** Build fails when using Clang, with LLD:

```
Linking Program        ==> bin/godot.linuxbsd.tools.64.llvm
ld.lld: error: unable to find library -l:libatomic.a
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.linuxbsd.tools.64.llvm] Error 1
scons: building terminated because of errors.
The terminal process "/bin/zsh '-c', 'scons -j10 use_llvm=yes use_lld=yes werror=no tests=yes'" terminated with exit code: 2.
```

And with GNU ld:

```
Linking Program        ==> bin/godot.linuxbsd.tools.64.llvm
progress_finish(["progress_finish"], [])
Building compilation database compile_commands.json
/bin/ld: cannot find -l:libatomic.a
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.linuxbsd.tools.64.llvm] Error 1
scons: building terminated because of errors.
The terminal process "/bin/zsh '-c', 'scons -j10 use_llvm=yes use_lld=no werror=no tests=yes'" terminated with exit code: 2.
```

The build also fails when using GNU ld.

This is a regression from https://github.com/godotengine/godot/pull/46347 (cc @hpvb).

**Steps to reproduce:** Build Godot with `scons platform=linuxbsd use_llvm=yes use_lld=yes`.

**Minimal reproduction project:** N/A

**Comment by Calinou** [comment]
Resolved by installing `libatomic-static` from the Fedora repositories.

**Comment by Xrayez** [comment]
I've recently compiled Godot on a fresh install of Fedora 33 Workstation on my laptop, had to install `libstdc++-static` as well (GCC).

**Comment by Calinou** [comment]
@Xrayez This is because `use_static_cpp` is now enabled by default.

**Comment by akien-mga** [comment]
> Resolved by installing `libatomic-static` from the Fedora repositories. Should we add this dependency to the various oneliners in the Linux compiling documentation? As far as I know, this is only needed when compiling with Clang, not GCC.

It should be added to the docs, but indeed it's only relevant when using Clang, so it's a bit tricky. Could still be added to the oneliners because it doesn't hurt to have it even when using GCC I guess. Otherwise as a `.. note::` after the table, but then we wouldn't be able to provide the name of the relevant package for each distro.

See also https://github.com/godotengine/godot-docs/issues/4617.

**Comment by rosshadden** [comment]
I'm not sure what needs installed on Arch Linux. Does anyone here that got it working know which packages are required? I have both `libatomic_ops` and `gcc-libs` installed already, both of which provide libatomic.

**Comment by akien-mga** [comment]
> I'm not sure what needs installed on Arch Linux. Does anyone here that got it working know which packages are required? I have both `libatomic_ops` and `gcc-libs` installed already, both of which provide libatomic.

`libatomic_ops` is unrelated, but `gcc-libs` does provide `libatomic.so`. What is needed for static linking is `libatomic.a`, and somehow it seems Arch decided not to provide that one..? So for now you'll have to build with `use_static_cpp=no` (not linking libstdc++, libgcc and libatomic statically, worse for portability but fine for your local builds) or use GCC.

**Comment by Waridley** [comment]
Since the benefits of Clang and LLD are mostly for development anyway, perhaps the workarounds should just be mentioned under the "Using Clang and LLD for faster development" section of the docs, and it could suggest using GCC for release builds for better portability.

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/5376.

**Comment by fire** [comment]
On centos8 adding `LINKFLAGS=-L/opt/rh/gcc-toolset-9/root/usr/lib/gcc/x86_64-redhat-linux/9/` to scons helped.

**Comment by dathide** [comment]
For Arch users who don't want to disable static cpp:

- Copy the text from https://github.com/archlinux/svntogit-packages/blob/packages/libatomic_ops/trunk/PKGBUILD
- Place it in a text file called PKGBUILD in an empty directory
- Remove `--disable-static --enable-shared` from the ./configure line
- Before the `install -Dm644 ...` line, add this line: `cp -f "$pkgdir/usr/lib/libatomic_ops.a" "$pkgdir/usr/lib/libatomic.a"`
- In the directory, run `makepkg -si`
