### ISSUE TITLE
Ctrl + Backspace and Ctrl + Left/Right arrows skip underscores for subword navigation in the script editor/TextEdit

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#46380]
**Godot version:** 4.0 e1e52b373

**OS/device including version:** Windows 10

**Issue description:**

Ctrl + backspace and ctrl + left/right arrow only consume alphabats and digits but skips underscores.

![ctrl_back](https://user-images.githubusercontent.com/41085900/109013412-25daa900-76d9-11eb-8b38-7d9b6fbf464b.gif)

**Steps to reproduce:**
**Minimal reproduction project:**
N/A

**Comment by Chaosus** [comment]
cc @bruvzg

**Comment by Chaosus** [comment]
Ah, nevermind there is PR opened to fix that, I missed it, sorry

**Comment by akien-mga** [comment]
Fixed by #47604.
