### ISSUE TITLE
No parser error for `get_node` used in "not-onready" variable

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#46382]
**Godot version:** 4.0 e1e52b373

**OS/device including version:** Windows 10

**Issue description:**
No parser error for get_node used in "not-onready" variable.

```gdscript
extends Node2D

var node1 = get_node('Sprite2D')
var node2 = $Sprite2D
```

**Steps to reproduce:**
**Minimal reproduction project:**
N/A

**Comment by KoBeWi** [comment]
Can't reproduce in 757c151
![image](https://user-images.githubusercontent.com/2223172/109080172-66015200-7700-11eb-9a7b-e204b4180c7e.png)

**Comment by Xrayez** [comment]
The regression can be confirmed by looking at #46233 reported in 3.2.

**Comment by angad-k** [comment]
I'd like to work on this. Any pointers on which files to investigate to start with?

**Comment by KoBeWi** [comment]
@angad-k This is the code from 3.2 branch:
https://github.com/godotengine/godot/blob/9047e760d11f0f606db0e40488e5a84f5d42227f/modules/gdscript/gdscript_parser.cpp#L4971-L4983

**Comment by akien-mga** [comment]
Reopening for now as #72487 was reverted.
