### ISSUE TITLE
Inaccurate HSV to RGB conversions

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#46393]
**Godot version:**
3.2, 4.0-dev

**OS/device including version:**
Kubuntu 20.10

**Issue description:**
In some cases, slightly inaccurate RGB to HSV conversions occur.

**Steps to reproduce:**
```gdscript
tool
extends EditorScript

func _run():
    var c1 = Color.from_hsv(0, 0.75, 0.4)
    print(c1.to_html(false)) # 661919
    print(c1.r) # 0.4
    print(c1.g) # 0.1
    print(c1.b) # 0.1
    
    var c2 = Color(0.4, 0.1, 0.1)
    print(c2.to_html(false)) # 661a1a
    print(c2.r) # 0.4
    print(c2.g) # 0.1
    print(c2.b) # 0.1
```

![](https://user-images.githubusercontent.com/47700418/109047713-414cb080-76e7-11eb-995f-921433403cf3.png)

**Minimal reproduction project:**
—

**Comment by Ev1lbl0w** [comment]
Printing more digits shows precision errors:

```gdscript
print("%.16f" % c1.r)
...
```

```
661919
0.4000000059604645
0.0999999940395355
0.0999999940395355
661a1a
0.4000000059604645
0.1000000014901161
0.1000000014901161
```
When you multiply the green or blue values by 255, it becomes clear:
- `0.0999999940395355 * 255` = `25.49999848` -> rounds to `25`
- `0.1000000014901161 * 255` = `25.50000038` -> rounds to `26`

I doubt there's much it can be done to combat these scenarios...

**Comment by dalexeev** [comment]
Yes, I understand. But the fact is that the values calculated using the formula from Wikipedia give accurate results... 

```gdscript
tool
extends EditorScript

func _run() -> void:
    var c1 := Color.from_hsv(0, 0.75, 0.4)
    print(c1.to_html(false)) # 661919
    print('%.16f' % c1.r) # 0.4000000059604645
    print('%.16f' % c1.g) # 0.0999999940395355
    print('%.16f' % c1.b) # 0.0999999940395355

    
    var c2 := Color(0.4, 0.1, 0.1)
    print(c2.to_html(false)) # 661a1a
    print('%.16f' % c2.r) # 0.4000000059604645
    print('%.16f' % c2.g) # 0.1000000014901161
    print('%.16f' % c2.b) # 0.1000000014901161
    
    var c3 := hsv2rgb(0, 75, 40)
    print('%.16f' % c3[0]) # 40.0000000000000000
    print('%.16f' % c3[1]) # 10.0000000000000000
    print('%.16f' % c3[2]) # 10.0000000000000000

func hsv2rgb(h: int, s: int, v: int) -> Array:
    var h_i := (h / 60) % 6
    var v_min := (100 - s) * v / 100.0
    var a := (v - v_min) * (h % 60) / 60.0
    var v_inc := v_min + a
    var v_dec := v - a
    
    var t := []
    match h_i:
        0: t = [v,     v_inc, v_min]
        1: t = [v_dec, v,     v_min]
        2: t = [v_min, v,     v_inc]
        3: t = [v_min, v_dec, v    ]
        4: t = [v_inc, v_min, v    ]
        5: t = [v,     v_min, v_dec]
    return t
```

**Comment by Ev1lbl0w** [comment]
Can you post the link from the Wikipedia where you got that formula? I can't find it anywhere, and I'm curious now :sweat_smile:

But your algorithm is not only more correct, it's even faster than the current one. I've tested the values and they are equal _(`is_equal_approx(...)`)_ to the current implementation, so do open up a PR to improve this!

**Comment by dalexeev** [comment]
I used an algorithm from Russian Wikipedia. English Wikipedia has two options, one of them is very similar to this algorithm, but slightly different. I do not presume to judge how correct each of these algorithms is. [ru-wiki](https://ru.wikipedia.org/wiki/HSV_(%D1%86%D0%B2%D0%B5%D1%82%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C)) [en-wiki](https://en.wikipedia.org/wiki/HSL_and_HSV#HSV_to_RGB)

**Comment by dalexeev** [comment]
I'm not sure, but it seems to me that the problem is not only in the algorithm, it's in how the `float` values are stored and processed in the `Color` class. Perhaps they are being rounded several times and/or at the wrong time. The precision of the numbers may not be considered. I don't know. Anyway, I hate `float`s because no one understands how to work with them properly. Including me.
