### ISSUE TITLE
Missing inherited methods in the "Select Method" window for animation call method tracks for C# scripts.

### ISSUE THREAD

**Issue by Gawehold** [godotengine/godot#46408]
**Godot version:**

3.2.3.stable.mono and 3.2.4.rc3.mono

**OS/device including version:**

OS: Windows 10 64bit 
Backend: GLES3
GPU: GTX 1060 6GB

**Issue description:**

When adding a new method call key to a "call method track", there is a popup window listing all methods of the node.
However, the "Script Methods" section only includes the methods in the script file, not those inherited from its parent class.
This issue is similar to https://github.com/godotengine/godot/issues/23384, which seems to be fixed, but the scripts I use are C# scripts instead of GDScripts.

**Steps to reproduce:**
1. Create a class A with a public/protected method X in a C# script `A.cs`
2. Create a class B that inherit class A in another C# script `B.cs`
3. Attach `B.cs` to arbitrary node in a arbitrary scene.
4. Create an AnimationPlayer node in the same scene.
5. Create an animation and a "call method track" of the node with `B.cs` attached.
6. Insert a new key in the track
7. Method X is not listed in the popup window

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Related to #39156 and #37803.

**Comment by akien-mga** [comment]
Fixed by #52607.
