### ISSUE TITLE
3.2.4rc3 - Immense lag occurs with >1000 colliding tiles and "visual collision shapes" enabled

### ISSUE THREAD

**Issue by etables** [godotengine/godot#46410]
**Godot version:**

3.2.4rc3

**OS/device including version:**

Arch Linux kernel 5.10.15-arch1-1
OpenGL ES 2.0 Renderer: GeForce RTX 2070 Super/PCIe/SSE2
OpenGL ES 2.0 Batching: ON

**Issue description:**

Immense lag occurs when enabling "visual collision shapes" under Debug, with over 1000 tiles with collision. This only occurs in 3.2.4rc3, not 3.2.4rc2.
I assume this has something to do with https://github.com/godotengine/godot/pull/46291
I suggest giving developers the option to disable outlines on debug collision shapes in Project settings; I did not expect such a performance hit with this. Obviously "visual collision shapes" won't be used in any production environment but it becomes close to impossible to debug something when FPS < optimal.

**Steps to reproduce:**
1. Create a tileset using any sprite/spritesheet.
2. Create a tile, and add a collision box to it.
3. Add the tileset to a tilemap node.
4. Create around 1000 tiles in the tilemap node.
5. Enable Debug -> Visual Collision Shapes
6. Enable "Print FPS" in settings
7. FPS should be below 60 FPS depending on hardware used
8. Test the project in 3.2.4 rc2 and 3.2.4 rc3. The latter will show lower frame rates than the former.

**Minimal reproduction project:**

https://github.com/etables/tilemap-lag-with-debug-collision-shapes

**Comment by pouleyKetchoupp** [comment]
Yeah an option to disable outlines in project settings would make sense. I'm going to add that, unless @Calinou has another idea in mind. I've also tried with just disabling antialisasing on the lines for test, and it doesn't make a lot of difference.
