### ISSUE TITLE
Mouse in Input Map not handled in _unhandled_input

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#46419]
**Godot version:**
3.2.3

**OS/device including version:**
Linux mint

**Issue description:**
In _input() all keyboard, joypad and mouse buttons are handled, however have no _input() and instead use _unhandled_input() then keyboard and joypad buttons are handled, but mouse buttons are ignored.

E.g. create Input Map 'fire' and add a key, a joypad button and a mouse click and on an empty scene or a scene with a sprite or something:

```
func _input(event: InputEvent) -> void:
	if Input.is_action_just_pressed("fire"):
		pass  #entered for keyboard, joypad and mouse
```

However, if you do not have _input and instead _unhandled_input then it is not called. However it works perfectly fine for all other controls (keyboard, joypad), just not mouse

```
func _unhandled_input(event: InputEvent) -> void:
	if Input.is_action_just_pressed("fire"):
		pass  #entered for keyboard and joypad only, not mouse
```

Documentation has nothing to state mouse is an exception in the calling chain
![image](https://user-images.githubusercontent.com/12863685/109169305-91735380-7777-11eb-8cad-a5b2c54cfec5.png)

**Steps to reproduce:**

**Minimal reproduction project:**
Add mouse left click to Input Map, put a breakpoint on 'pass'. In _input it reaches it. Now remove _input and repeat - unhandled input is not called. Code as above.

**Comment by nisovin** [comment]
This issue is likely caused by a Control node that is consuming your input. Check the mouse filter settings for any controls that fill the space where you are clicking.

**Comment by chucklepie** [comment]
I thought I stated, this is on a blank scene. So it's not a control node.

Just try it with the code I pasted. Or I can zip up a scene with this code
if your prefer.

**Comment by nisovin** [comment]
Yes, you should post a zip. I tried your reproduction steps and it seemed to work fine for me.

**Comment by copygirl** [comment]
I just noticed my nodes did not receive a `_unhandled_input` mouse event because I had a background image (`TextureRect`) covering the screen with mouse filter set to `Pass` (as is default). Changing it to `Ignore` fixes this issue. This seems like an error. (Godot Mono v3.3)

**Comment by madmiraal** [comment]
As @nisovin has pointed out, this works fine when there is no `Control` node intercepting the mouse see attached project:
[46419.zip](https://github.com/godotengine/godot/files/6530795/46419.zip)

@copygirl This is exactly how control nodes work. See the last sentence in the [documentation](https://docs.godotengine.org/en/stable/classes/class_control.html#enum-control-mousefilter):
> MOUSE_FILTER_PASS = 1The control will receive mouse button input events through _gui_input() if clicked on. And the control will receive the mouse_entered and mouse_exited signals. If this control does not handle the event, the parent control (if any) will be considered, and so on until there is no more parent control to potentially handle it. This also allows signals to fire in other controls. **Even if no control handled it at all, the event will still be handled automatically, so unhandled input will not be fired**.

**Comment by copygirl** [comment]
> Even if no control handled it at all, the event will still be handled automatically, so unhandled input will not be fired.

It would be nice to have an explanation as to what the reasoning for this behavior is.

**Comment by MacJuicer** [comment]
> I just noticed my nodes did not receive a `_unhandled_input` mouse event because I had a background image (`TextureRect`) covering the screen with mouse filter set to `Pass` (as is default). Changing it to `Ignore` fixes this issue. This seems like an error. (Godot Mono v3.3)

I had the same issue, the ViewportContainer node was the problem (changing it to ígnore fixed too). thx [copygirl](https://github.com/copygirl) you saved my day

**Comment by EramarkMedia** [comment]
I'm with ya on having the same issue too.
Started to get grey hair why i did not receive any events from Mouse.

This was a good one. :)
Thank you.
