### ISSUE TITLE
Can't grab outputs from visual shader node's when the visual shader editor is zoomed out a little

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#46425]
**Godot version:**

3.2.3 stable

**OS/device including version:**

Windows 10, with a 3200x1800 display at 250% scaling if that's relevant

**Issue description:**

https://user-images.githubusercontent.com/50304111/109214998-c67ba800-776f-11eb-8d65-724ed8947837.mp4

**Steps to reproduce:**
Try what I tried in the video

**Minimal reproduction project:**

**Comment by LightningAA** [comment]
I found some more weird and probably related behaviour:

https://user-images.githubusercontent.com/50304111/109228739-87555300-777f-11eb-8a9d-fef814bc1974.mp4

**Comment by Chaosus** [comment]
It's a GraphEdit bug, affected both VisualScripts/VisualShaders and perhaps custom GraphEdit's of the users.
