### ISSUE TITLE
LineEdit and TextEdit text selection stops working if the mouse moves out of the game window

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#46428]
**Godot version:**

3.2.3

**OS/device including version:**

Linux

**Issue description:**

happened:

https://user-images.githubusercontent.com/16458555/109227295-eb106800-77e1-11eb-99c4-6fbdb8abadb3.mp4

expected:

https://user-images.githubusercontent.com/16458555/109227312-f19edf80-77e1-11eb-9257-08b3d6556a35.mp4

**Steps to reproduce:**
1. Create a new scene
2. Add `LineEdit` as the scene root
3. Run the scene
3. Add some text, select and move mouse outside the game window
As you can see, the selection doesn't work when dragging untill you release the mouse and select again.

The same for `TextEdit`

**Minimal reproduction project:**

**Comment by mhilbrunner** [comment]
At least on Windows, this seems to have been fixed in Godot 4. Please ping for a reopen if anyone can still reproduce it with Godot 4.
