### ISSUE TITLE
Ability to use a plain color as splash screen rather than an image

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4642]
Since many games would rather have their own animated splash screen, it would be nice to be able to set a color to the splash that would be applied to the whole window during loading (and instead have a pure black color during engine loading, for example).

Currently, you have to use a pure black image as splash, it's kind of a hack (since you need an image editor to change the color).

**Comment by neikeq** [comment]
There is already `boot_bg_color`. The problem is that if you don't specify a custom splash screen, the default one will be used instead of none.

**Comment by Calinou** [comment]
**Update:** This issue is still relevant as of https://github.com/godotengine/godot/commit/a1f835df771464e9db6909fd104751ccbbc1b91a.

**Comment by char0xff** [comment]
I agree that there is the need for an option to simply disable the boot splash, since loading a black image is a hack.

**Comment by KoBeWi** [comment]
What would be the best way to handle it? Adding another project setting is probably out of question, so maybe this could depend on image name? The default would be changed to "Godot" or "default" and it would mean to use the Godot logo. Setting the path to non-existing file (especially empty string) should just display the clear color, instead of being full-white.

**Comment by Calinou** [comment]
@KoBeWi A new project setting sounds fine to me, especially as you may want to specify a boot splash color *in addition* to an image. The boot splash color would be used to fill the areas outside the image.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1445, as feature proposals are now tracked on the Godot proposals repository.
