### ISSUE TITLE
Dropping an empty folder on HTML5 causes a Javascript error

### ISSUE THREAD

**Issue by Nukiloco** [godotengine/godot#46437]
**Godot version:**

v3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

When dropping an empty folder onto your game, on desktop this will normally return a file path from the files_dropped signal in the SceneTree. However when doing this on HTML5, you will be given a blank array and a javascript error with the error being "<generic error, no stack>" and the error number is 44.

**Steps to reproduce:**
1. Connect a function to the files_dropped signal in the SceneTree.
2. Run it on desktop, drop the project folder onto it, then drop an empty folder onto it. It will return the folder path on both of them.
3. Run it on HTML5, drop the project folder onto it, then drop an empty folder onto it. It will return the folder path when it has files in it but when it has no files in it, it returns an empty array and a javascript error.

**Minimal reproduction project:**

[FileDropHTML5Issue.zip](https://github.com/godotengine/godot/files/6047221/FileDropHTML5Issue.zip)

**Comment by akien-mga** [comment]
I don't think file drag and drop is supported in 3.2.3, but it should be in 3.2.4 RC 3.

**Comment by Flairieve** [comment]
Drag and drop works on HTML5 on 3.2.3 for any file and folders as long as the folder isn't empty.

**Comment by akien-mga** [comment]
Can you test 3.2.4 RC 3? There has been many changes for this platform.

**Comment by Flairieve** [comment]
HTML5 Debugging is broken in 3.2.4 RC 3.
It shows a blank dialog box with the button ok then it shows this error message.
![image](https://user-images.githubusercontent.com/16618467/109362598-3194af80-7840-11eb-9a5d-468d521df0c7.png)
This is definitely not related to this issue.

**Comment by Faless** [comment]
This seems fixed in current `3.x` (likely by #55594).
Closing, feel free to drop a comment is you still experience it.
