### ISSUE TITLE
Hovering over a button then moving the cursor out of the window causes the button to stay highlighted

### ISSUE THREAD

**Issue by Nukiloco** [godotengine/godot#46438]
**Godot version:**

v3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

When hovering over a button with your cursor then moving your cursor out of the window causes the button to stay highlighted. This seems to happen on all platforms including HTML5.

**Steps to reproduce:**
1. Make a button right next to the window border.
2. Run the project.
3. Move your cursor over the button.
4. Then move your cursor out of the window.
5. The button stays highlighted.

**Minimal reproduction project:**

[ButtonIssue.zip](https://github.com/godotengine/godot/files/6047240/ButtonIssue.zip)

**Comment by Anshul7sp1** [comment]
Hi!,
I tried to fix this by changing the conditions that set the hover state to false to this [(here)](https://github.com/godotengine/godot/blob/888051889ed0b63a6b88d3a7e0c2bfbbacde7b4b/scene/gui/base_button.cpp#L87)
`if (p_what == NOTIFICATION_MOUSE_EXIT || p_what == NOTIFICATION_WM_MOUSE_EXIT)`

**the updated behavior:**

https://user-images.githubusercontent.com/52310272/111586025-39fc5c80-87e6-11eb-9a21-7377c80b3254.mp4

**But then this problem:** 
If we enter into the game window from the common side (the right side in the video, where the button is clipped) then the notification `NOTIFICATION_MOUSE_ENTER` is received by the button object only if the last time the mouse pointer left the game window was through a side OTHER than the common edge.
If mouse pointer is moved out of the window through the common edge and moved back in again, no `NOTIFICATION_MOUSE_ENTER` reaches the object.

Thanks to @Faless for pointing out that  the problem might be [here](https://github.com/godotengine/godot/blob/9ca0d66a3b51084eb528a85e133d9037b21bdd09/scene/main/viewport.cpp#L562) in `viewport.cpp` (although I couldn't make much out of it 😅)

Maybe someone who worked on it earlier can take up this issue ✌
