### ISSUE TITLE
Project settings that require a restart won't get saved

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#46444]
**Godot version:**
3.2.4 rc3 (but not in rc2)

**OS/device including version:**
Windows 10

**Issue description:**
I wanted to disable `vsync` in the project settings, which requires a restart of the editor. Afterwards vsync was still enabled. Probably related to #45968. cc @KoBeWi

**Comment by Calinou** [comment]
I could reproduce this while working on the Truck Town demo last week.

**Comment by KoBeWi** [comment]
This is weird, I can reproduce in 3.2, but not on master. Fix is easy though.
