### ISSUE TITLE
Regression with Contextual Help lookup

### ISSUE THREAD

**Issue by asmaloney** [godotengine/godot#46456]
**Godot version:**

4.0 master (75d03f1fbd94efb5f8756e405de03cf271435336)

**OS/device including version:**

macOS 10.14.6

**Issue description:**

When the script editor cursor is on a word with a `_`, the lookup does not used the entire word.

**Steps to reproduce:**

Open the attached project, open *Main.gd*, place the cursor on the `node` part of `find_node` (without selecting anything), then bring up the contextual help.

The docs will be on `node` when it should be on `find_node`.

This works properly in 3.2.4rc. `TextEdit::get_word_under_cursor()` has been re-implemented on master which breaks this behaviour.

**Minimal reproduction project:**

[ContextHelpBug.zip](https://github.com/godotengine/godot/files/6052186/ContextHelpBug.zip)

**Comment by akien-mga** [comment]
Fixed by #47604.
