### ISSUE TITLE
[3.2.3] Godot grid container margin option not working properly (values are not getting saved)

### ISSUE THREAD

**Issue by soyrandom1** [godotengine/godot#46461]
**Godot version:**
3.2.3

**Issue description:**
When i change the values in the inspector i do see the changes on the scene, but when i run the project it doesn't. If i refresh the inspector window or if i close and open again that scene, the value is back to 0. 

**Steps to reproduce:**
Using the following node structure 
![image](https://user-images.githubusercontent.com/12002910/109366756-037c9300-7873-11eb-8b13-2e0229d00135.png)
Change the value of any grid container margin, save the scene, close it, open it again, check the margin, it will be at 0
![image](https://user-images.githubusercontent.com/12002910/109366809-21e28e80-7873-11eb-9490-bd06b52cca23.png)
![image](https://user-images.githubusercontent.com/12002910/109366824-29099c80-7873-11eb-8d4b-09b3f1fe60ca.png)

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/6053229/bug.zip)

**Comment by pycbouh** [comment]
That's not a bug. Your `GridContainer` is inside of another container. Containers control positional properties of their children, and override them. Ideally these properties should be uneditable in the Inspector, but this has not been implemented yet.

**Comment by soyrandom1** [comment]
@pycbouh Thanks for the quick response, you are right, i feel dumb now! I completly forgot about that. Thanks for answering!
