### ISSUE TITLE
Polygon2D Antialiasing doesn't antialias.

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot#46465]
**Godot version:**

3.2.4.rc3

**OS/device including version:**

Windows 10 PC with RTX 2060, using the most recent NVidia Game Ready drivers and the GLES3 backend.

**Issue description:**

When I enable the "Antialias" property on a Polygon2D node, it does no antialiasing. I expect that option to enable antialiasing on that polygon.

**Steps to reproduce:**
Add a Polygon2D in your scene and enable Antialiasing. Presumably MSAA needs to be enabled in the project settings, which it is on my project.

**Minimal reproduction project:**

[Polygon2DAntialiasing.zip](https://github.com/godotengine/godot/files/6053611/Polygon2DAntialiasing.zip)

**Comment by lawnjelly** [comment]
Turning anti-aliasing on in the polygon doesn't actually turn anti-aliasing on, this is correct, this should probably be changed in the class reference.

Turning anti-aliasing on draws lines around the poly using `GL_HINT_SMOOTH` (but only on `GLES_OVER_GL` devices, such as desktop). However this is only a hint, so this setting is basically a vague request for anti-aliasing, it doesn't guarantee anti-aliasing.

It doesn't use MSAA or anything full screen.

**Comment by Calinou** [comment]
Try disabling HDR in the Project Settings.

**Comment by Syntaxxor** [comment]
@Calinou Disabling HDR doesn't seem to change anything. After further testing today, it seems that some behaviors have changed since last night. Antialiasing happens in-game for all non-skinned polygons with antialiasing enabled, whether or not HDR and Batching are enabled. However, there is no in-editor antialiasing. Also, for whatever reason, my AnimationTree Add2 is now acting like a Blend2.

**Comment by hazarek** [comment]
not only polygon2d. all 2d lines and polygons

**Comment by Calinou** [comment]
This is now documented by https://github.com/godotengine/godot-docs/pull/5746, closing.

**Comment by FeldrinH** [comment]
> This is now documented by [godotengine/godot-docs#5746](https://github.com/godotengine/godot-docs/pull/5746) (including workarounds with an [add-on](https://github.com/godot-extended-libraries/godot-antialiased-line2d)), closing.

I don't know about others here, but I was really hoping this could be fixed in the core engine, instead of using some third party addon as a workaround. Also, the documentation change doesn't really address the Polygon2D node, which has an antialiasing option that seems to do nothing.

**Comment by Syntaxxor** [comment]
> > This is now documented by [godotengine/godot-docs#5746](https://github.com/godotengine/godot-docs/pull/5746) (including workarounds with an [add-on](https://github.com/godot-extended-libraries/godot-antialiased-line2d)), closing.
> 
> I don't know about others here, but I was really hoping this could be fixed in the core engine, instead of using some third party addon as a workaround. Also, the documentation change doesn't really address the Polygon2D node, which has an antialiasing option that seems to do nothing.

While the documentation not making any mention of the continued inaction of Polygon2D anti-aliasing is definitely a problem (and I can reproduce it), that would be best addressed by a separate issue in the [godotengine/godot-docs](https://github.com/godotengine/godot-docs) repository. With regards to actually getting Polygon2D objects to have visual anti-aliasing, I've found that the project setting "MSAA 2D" smooths out the edges very nicely and works perfectly fine on Polygon2D objects. Perhaps that could help you if you're on Godot 4 at this point.

As for having it actually fixed in the engine, I don't know if there would be a good way that works with what's currently in place, especially since the add-on is sufficient for most purposes. That could be its own issue as well, but bemoaning it on a closed issue doesn't seem to be the right course of action to me. If anything, I get the feeling that the best course of action is to remove the property that does nothing, since it can make it actually _harder_ to find workarounds because it looks like it should work. But again, such things should be in separate proposals and issues, not here. I do wish you luck, though.

**Comment by AThousandShips** [comment]
For implementing some feature like that please open a [feature proposal](https://github.com/godotengine/godot-proposals) if there isn't one already

**Comment by FeldrinH** [comment]
> As for having it actually fixed in the engine, I don't know if there would be a good way that works with what's currently in place, especially since the add-on is sufficient for most purposes. That could be its own issue as well, but bemoaning it on a closed issue doesn't seem to be the right course of action to me. If anything, I get the feeling that the best course of action is to remove the property that does nothing, since it can make it actually _harder_ to find workarounds because it looks like it should work. But again, such things should be in separate proposals and issues, not here. I do wish you luck, though.

Fair enough, I created https://github.com/godotengine/godot/issues/112626.
