### ISSUE TITLE
Perfomance issues on OSX with a tilemap and 2d lights

### ISSUE THREAD

**Issue by marcelofg55** [godotengine/godot#4646]
**Operating system or device - Godot version:**
Mac OSX, godot 2.0.2 and latest github.
[tilemap_lights.zip](https://github.com/godotengine/godot/files/262476/tilemap_lights.zip)

**Issue description** (what happened, and what was expected):
Running a scene with a tilemap and 2d lights shows a big performance drop (to aprox. 35fps) on OSX, the same project runs with a steady 60fps on windows (on the exact same machine).

**Steps to reproduce:**
Run the attached project on OSX.

**Link to minimal example project** (optional but very welcome):
https://dl.dropboxusercontent.com/u/29008381/tilemap_lights.zip

**Comment by reduz** [comment]
It is possible that the Apple drivers suck,  but also GLES2 does a lot of setup calls. For 3.0 we'll be rewritting many of these things, so we'll be able to tell better what is the case

**Comment by marcelofg55** [comment]
Cool, I'll wait for 3.0 to keep testing this, thanks for the info!

**Comment by marcelofg55** [comment]
It seems that this bug is related to nvidia cards, I've tested the same on a mac with an intel card and the project with lights works just fine. The problem might reside in the nvidia opengl, while searching for info I've found this article: http://www.tonymacx86.com/threads/os-x-opengl-4-1-broken-on-nvidia-for-almost-2-years.157082/

**Comment by reduz** [comment]
all this code has been completely rewritten, so please test again and re-report if it still happens
