### ISSUE TITLE
import godot with Clion failed 

### ISSUE THREAD

**Issue by wangjianpeng** [godotengine/godot#46460]
**Godot version:**

master project

**OS/device including version:**

windows 10 

**Issue description:**

Failed to open godot by Clion ,has the following error.
Build file 'D:\Projects\GitProjects\godot\platform\android\java\lib\build.gradle' line: 98

A problem occurred evaluating root project 'Godot'.
> A problem occurred configuring project ':lib'.
   > org.gradle.api.GradleException: Unable to find executable path for the 'scons' command.

**Steps to reproduce:**
I follow the link [Clion IDE for godot ](https://docs.godotengine.org/en/stable/development/cpp/configuring_an_ide/clion.html),When I open <Godot root directory>/platform/android/java/lib ,there is no CMakeLists.txt located ,then failed to import.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @RevoluPowered @m4gr3d

**Comment by likeich** [comment]
I'm using CLion and I've been using the CMakeLists.txt found in godot\platform\android\java\nativeSrcsConfigs. I think it was moved there and the docs just weren't updated.

**Comment by likeich** [comment]
Nevermind, the latest docs have it set correctly: https://docs.godotengine.org/en/latest/development/cpp/configuring_an_ide/clion.html

**Comment by Calinou** [comment]
I cherry-picked the commits in the `master` branch to the `3.2` branch.
