### ISSUE TITLE
Calling AudioPlayer stop() then change scene induces music stuttering that lasts a few seconds

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#46472]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Linux

**Issue description:**
I don't know if this bug is fixed by  #43210 or not as it's a different issue.

Basically, on Linux Chromium (I haven't tried Windows Chrome, I don't have it) when I stop music then change scenes the last element of the music repeat and stutters for 2 to 3 few seconds until the scene is loaded and sounds truly awful.

I have tried before changing scene:
1. Calling stop() - still stutters
2. setting pause - still stutters
2. setting volume to -80 - still stutters
3. Attaching to the audio player music finished signal then starting scene - still stutters

The only thing that has worked, and it's a pretty crap solution, is I attach a timer and wait 2 seconds after I call stop() on the music player.

Firefox Linux is ok.

**Steps to reproduce:**
Happy to show it working on my web server...

**Minimal reproduction project:**
Any combination of the below with the change scene...
```
		$AudioStreamPlayer.volume_db=-80
		$AudioStreamPlayer.pause_mode=true
		$AudioStreamPlayer.stop()
                get_tree().change_scene("res://scenes/Game.tscn")
```

**Comment by chucklepie** [comment]
btw, sorry to digress. I presume this is a browser bug and not Godot and not related to the above, but it might be. In Chromium you get no audio when a game starts, e.g. your startup logo/intro, until you click the mouse. On all other browsers it is fine. It means if you start your menu/splash with music it fails to start on Chromium. It means you have to introduce a silly 'click me' scene at the start of a Godot game.bypass this first scene.

**Comment by Calinou** [comment]
I'd try using 3.2.4rc3 and exporting with threads enabled in the export preset to see if this is caused by the lacl of threads in HTML5. Enabling threads will also decrease sound latency.

**Comment by chucklepie** [comment]
But it's fine on Firefox?

I will try, but if not it's either suggest to players on Linux they have awful sound on Chrome or 10fps on Firefox ;-)

**Comment by Calinou** [comment]
> But it's fine on Firefox? Did you get time to read my comment above adding to the issue as I typed it late?

Yes 🙂

**Comment by chucklepie** [comment]
> > But it's fine on Firefox? Did you get time to read my comment above adding to the issue as I typed it late?
> 
> Yes slightly_smiling_face

and? is this a bug or Chrome feature?

**Comment by Calinou** [comment]
@chucklepie Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by chucklepie** [comment]
@Calinou No, I have tried it and it is even worse. See #46733

**Comment by dpensky** [comment]
I also have this problem in the current stable version, not only in chrome but in safari as well.
The path to reproduce this erros in my case is more or less like this:
user clicks button, button plays a click audiostream wav file sound, I wait for the 'finished' signal, load another scene, sound is playing stuttering until the end of loading the new scene

**Comment by pwnorbitals** [comment]
@chucklepie I agree that a minimal reproduction project would help in helping troubleshoot the issue

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
