### ISSUE TITLE
Errors when commenting or uncommenting code

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#46477]
**Godot version:**
3.2.4.rc.custom_build. 8385a0d8a

**Issue description:**
When I uncomment/comment code, then pressing with Shift on selected area, shows this errors
```
ERROR: _base_get_text: Condition "p_to_line < p_from_line" is true. Returned: String()
   At: scene/gui/text_edit.cpp:4059.
```

**Steps to reproduce:**
1. Select code from bottom to top
2. Comment selected code
3. With SHIFT pressed, click with left mouse button at place inside selection

On video is shown first, that selecting code from top to bottom doesn't show any error

https://user-images.githubusercontent.com/41945903/109395354-2b7bfd00-792c-11eb-9485-e8cd9bf934da.mp4

**Comment by jmb462** [comment]
This issue applies to the 4.0 master branch too.
It's happening also if text is indented instead of commented.
I've summited a PR that fixes it. ( #46572 )
