### ISSUE TITLE
C#, memory leak from _GuiInput method

### ISSUE THREAD

**Issue by Nefistofeles** [godotengine/godot#46497]
**Godot version:**
3.2.3 Stable

**OS/device including version:**
GLES3 and GLES2
Graphics card : Nvidia GTX 1650
OS : Windows 10

**Issue description:**
I was writing drag and drop system for panel node but when i clicked and moved panel, objects number was continuously increase and they weren't delete from debug panel. I'm thinking reason is _GuiInput method.
I expect objects number don't increase or delete after few seconds.

![leak](https://user-images.githubusercontent.com/43671468/109403436-bda4f500-796e-11eb-9da6-49c6a157d225.PNG)

    public override void _GuiInput(InputEvent @event)
    {
        if (@event is InputEventMouseButton button)
        {
            if (button.IsActionPressed("right_click"))
            {
                drag = true;
                offset = GetGlobalMousePosition() - RectGlobalPosition;
            }
            if (button.IsActionReleased("right_click"))
            {
                drag = false;
                offset = Vector2.Zero;
            }
        }
        if (@event is InputEventMouseMotion motion && drag)
        {
            RectGlobalPosition = GetGlobalMousePosition() - offset;
        }
    }

**Steps to reproduce:**
1. Create Panel node
2. Add above method
3. Click to panel and fastly move (then objects increase and do not delete)

**Minimal reproduction project:**
[MemoryLeak.zip](https://github.com/godotengine/godot/files/6055918/MemoryLeak.zip)

**Comment by kleonc** [comment]
Not a leak, that's [how Garbage Collector works](https://docs.microsoft.com/en-gb/dotnet/standard/garbage-collection/fundamentals). If you'd drag long enough the garbage collection would finally happen. :wink:
To see it better in action you can add a button and connect such method to the pressed signal:
```
void OnButtonPressed()
{
	for (int i = 0; i < 1000; i++)
	{
		new Godot.Reference();
	}
}
```
Keep clicking the button and observe number of objects.

To prevent this pseudo leak from happening you can call `Dispose` method when you're "done" with the given object ([Godot.Object implements IDisposable](https://github.com/godotengine/godot/blob/3.2.3-stable/modules/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs)), like this:
```
public override void _GuiInput(InputEvent @event)
{
    if (@event is InputEventMouseButton button)
    {
        if (button.IsActionPressed("right_click"))
        {
            drag = true;
            offset = GetGlobalMousePosition() - RectGlobalPosition;
        }
        if (button.IsActionReleased("right_click"))
        {
            drag = false;
            offset = Vector2.Zero;
        }
    }
    if (@event is InputEventMouseMotion motion && drag)
    {
        RectGlobalPosition = GetGlobalMousePosition() - offset;
    }
    @event.Dispose();
}
```

**Comment by Calinou** [comment]
Closing per @kleonc's comment.
