### ISSUE TITLE
Clip Content property in Controls has 1px error

### ISSUE THREAD

**Issue by asheraryam** [godotengine/godot#46493]
**Godot version:**

Godot 3.2.3 stable. 

**OS/device including version:**

Both GLES3 and GLES2. Windows 10. Nividia 930M.

**Issue description:**

Clip Content does not always respect its own rect size, and children will bleed by 1-2 pixels. This happens when zooming in the editor, or when running the game with the stretch mode set to anything other than None.

I expect the Clip Content property to always clip the child contents regardless of screen resolution or zoom.

In this below picture you can see the edges of the TextureRect that is supposed to be completely clipped.

Note that toggling "snap_controls_to_pixels" in project settings also did not help.

![image](https://user-images.githubusercontent.com/43449832/109402362-63a03180-7966-11eb-889b-c1259a38dfaa.png)

**Steps to reproduce:**

- Create Control node with size A
- Set Clip Content true
- Add child Control node with size B bigger than A
- Add sibling ColorRect set to Full Rect layout/size A (to help visualize the error) 
- Scroll in/out in the editor (or launch the game and resize the screen)

**Minimal reproduction project:**
[clip_content_flicker.zip](https://github.com/godotengine/godot/files/6055733/clip_content_flicker.zip)

**Comment by Calinou** [comment]
This is likely a rounding issue somewhere in the GUI code.

**Comment by lawnjelly** [comment]
I will try and have a look later but I'm not familiar with the clips, for a quick answer it would be better to get @reduz to look at as he will know how it is intended to work etc.

**Comment by asheraryam** [comment]
@lawnjelly To be clear I already made a PR yesterday and I tested it on a big project and found no regressions. https://github.com/godotengine/godot/pull/46495

**Comment by lawnjelly** [comment]
Yup sorry I should have been clearer - I saw the PR, it looks good. :+1: It will need reviewing though - that's what I'm referring to.
