### ISSUE TITLE
Extended class does not inherit _init method

### ISSUE THREAD

**Issue by ofiala-a51** [godotengine/godot#46491]
**Godot version:** 3.2.3

**OS/device including version:** Linux Mint 20.1

**Issue description:**

I created a new class that extends another one. The original class has modified _init that requires one parameter (instead of default zero). The extended class does not properly inherit this, and passing the parameter to the extended class' constructor triggers error: `Parser Error: Too many arguments for "_init()" call. Expected at most 0.`. Copying the exact _init from the original class into the extended class fixes this issue, but this obviously shouldn't be necessary (minimizing code duplication is the whole point of inheritance).

**Steps to reproduce:** See above.

**Minimal reproduction project:**

GitHub won't let me upload the files here, so I uploaded the project to my GitLab: https://gitlab.com/ofiala/godot-repro

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/26106.

**Comment by ofiala-a51** [comment]
Huh. That's counterintuitive as hell, but in that case I gotta close this as NOTABUG.
