### ISSUE TITLE
Duplicate Folder with Scene and Scripts Issue

### ISSUE THREAD

**Issue by gonzo191** [godotengine/godot#46498]
**Godot version:**
v.3.2 stable.official

**OS/device including version:**
Windows 10 x64

**Issue description:**
Duplicating a folder with scenes and scripts inside do not update the paths used in the copy but uses the paths from the original. My assumption was that the paths of the duplicate item would update. Not sure if this is the intended behaviour but it seems like a bug.

**Example Project**
- Original
  - Original.tscn (**Attached**: Original.gd)
  - Original.gd

- Duplicate (_Duplicated from 'Original' using Godot FileSystem_)
  - Duplicate.tscn (**Attached**: _Original_ / Original.gd - instead of Duplicate.gd)
  - Duplicate.gd

**Steps to reproduce:**
1. Create a folder with a scene and attach a script
2. From the FileSystem in Godot, right click and duplicate a folder 
3. Rename duplicated folder scene and script
3. Open duplicated folder/scene
4. Hover over the script icon in editor of the original and duplicate to view their paths are the same

**Minimal reproduction project:**

[DuplicateIssueShowcase.zip](https://github.com/godotengine/godot/files/6055999/DuplicateIssueShowcase.zip)

**Comment by Calinou** [comment]
I don't think this is a bug, just behavior that was never implemented in the first place.

**Comment by gonzo191** [comment]
Ok, got it. I figured I'd highlight it just in case as it could trip users up if they chose to update the 'duplicate' code and unknowingly updating the original. 
Should I close it since it's not a bug but an unimplemented feature?

**Comment by KoBeWi** [comment]
Someone actually opened a similar proposal already: https://github.com/godotengine/godot-proposals/issues/2375
You could add a comment about folders.
