### ISSUE TITLE
Cannot use lowercase (e,f) in hexadecimal number with in Shader

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#46507]
**Godot version:**

3.2.4 rc3

**OS/device including version:**

Windows 10 x64

**Issue description:**

```glsl
shader_type canvas_item;
const int x = 0xe; // or 0xf
```
Expected: No errors
Happened: Invalid numeric constant error

**Steps to reproduce:**
1. new Shader
2. copy paste the above script

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/6056751/project.zip)

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by Chaosus** [comment]
As a workaround you can write `const int x = 0xE; // or 0xF` (uppercase) and it will work.
