### ISSUE TITLE
Simulated mouse button clicks are ignored by UI elements

### ISSUE THREAD

**Issue by Reapetitive** [godotengine/godot#46503]
Godot 3.2.4 RC3

func mouse_left_press():
	var a = InputEventMouseButton.new()
	a.global_position = get_viewport().get_mouse_position()
	a.set_button_index(1)
	a.set_pressed(true)	
	Input.parse_input_event(a)

func mouse_left_release():
	var a = InputEventMouseButton.new()
	a.global_position = get_viewport().get_mouse_position()        
	a.set_button_index(1)
	a.set_pressed(false)	
	Input.parse_input_event(a)	

This two methods are called deferred on action_just_pressed/action_just_released in _physics_process, and it seems to do the click, but UI elements don't react to it.

**Comment by Calinou** [comment]
Are you 100% sure that the mouse coordinates match the UI button's coordinates? Try making the button span the whole viewport to make sure.

**Comment by Reapetitive** [comment]
@Calinou well, i am able to click the buttons with the actual mouse, but when i simulate a click with a method, at the exact same positions, they ignore it. There is an old issue somewhere, about exactly this problem in Godot 2. i think. It wasn't resolved, just closed because it was old. Input got reworked since then, but the issue seems to be present.

**Comment by Calinou** [comment]
> My actual problem is, i implemented the controlls with a joystick, including the mouse movement in menus, but i can't click the ui buttons with it.

That's strange. Godot is definitely able to create menus with full controller support ([here's an example](https://github.com/Calinou/escape-space)).

**Comment by Reapetitive** [comment]
@Calinou sorry, my explanation was misleading. What you described is already implemented. It is possible to do almost everything in the UI with keyboard/controller. What i mean is the mouse clicking. For example, you use the right stick of the controller to move the mouse in menus. Then you want to click the button hovered by mouse by pressing a controller button, which leads you to calling a mouse button pressed event on controller button pressed. This doesn't work. The events work, but the UI doesn't react to them. You can literally see your mouse clicking, and you can even set the position of the event in script, so you know exactly where the click happens, the mouse warps there automatically, but for usual situation, you just set it to event.global_position = get_viewport().get_mouse_position(), so it clicks where your mouse is right now. The button under the mouse loses focus, when the click happens instead of receiving the click event.

**Comment by Sauermann** [comment]
This issue is based on a misconception: You only set `a.global_position`, but do not set `a.position`.

The code, that evaluates, if an event is over an UI element, depends on `a.position`:
https://github.com/godotengine/godot/blob/cec7fc4ffeba4de992436ed9c7f8fe428c22a6b1/scene/main/viewport.cpp#L1864

In order to make your code work, as far as I can tell, you would need to also set `a.position`.

**Comment by Reapetitive** [comment]
It still doesn't seem to work. I tried setting the position, position and global position, applying make_input_local and so on. Nothing works for me so far. I am trying to change the value of a horizontal slider by simulating a mouse click from controller input.
