### ISSUE TITLE
Difference in input to output for Quat(from euler) -> Euler -> Quat

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#46506]
**Godot version:**

3.2.4.rc3.mono.official

**OS/device including version:**

Win10

**Issue description:**

[c#/mono]
When trying to handle rotations using custom data structures i noticed strange behaviour.
Using unit tests i discovered that converting a quat constructed from euler angles to euler angles and back does not produce the same quat (even visually, when applied to a spatial).
In my case i'm basing everything on euler angles and only convert to quat when doing interpolation or assignments.
This is my test:
```
[Test]
public void QuatConversionIsConsistent()
{
    var eulerAnglesIn = new Vector3(0, 180f, 0);
    var rotated = new Quat(eulerAnglesIn);
    var eulerAnglesOut = rotated.GetEuler(); // (0, -2.212374, 0) = unexpected
    var reconverted = new Quat(eulerAnglesOut);
    Assert.IsTrue(reconverted.IsEqualApprox(rotated));
}
```

**Steps to reproduce:**
Execute the test (i used jetbrains rider with godot plugin + runner from github) or just print the values.

**Comment by Zireael07** [comment]
Most likely you're running into gimbal locking or floating point accuracy issues. What is the reconverted printing?

**Comment by Flavelius** [comment]
Gimbal lock is only relevant for delta-rotations, for rotation states this shouldn't matter.
Reconverted is: (0, -0,8939967, 0, 0,4480736)

**Comment by kleonc** [comment]
It works properly... in radians:
180 ≈ 29 * 2 * PI - 2.212374

**Comment by Flavelius** [comment]
> 
> 
> It works properly... in radians:
> 180 ≈ 29 * 2 * PI - 2.212374

Right, i tested it treating the euler angles coming from godot as radians and that does it. Thanks.
I didn't expect them them to be in radians, now i know better.

**Comment by Flavelius** [comment]
Hm, that only fixes the problems in my code though.
The results are still inverted.
If i do
`eulerAnglesIn = new Vector3(0, Mathf.Deg2Rad(180f), 0)`
the test still fails
