### ISSUE TITLE
Vulkan Memory Allocator

### ISSUE THREAD

**Issue by ThePreviousOne** [godotengine/godot#46500]
I stumbled across this a few days ago and wondered if it was or should be of interest to the Godot Project.

https://gpuopen.com/vulkan-memory-allocator/
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator

I wont pretend to know enough about this to argue the benifits of integrating it, I'll even admit I don't really know what it is, but it sounded useful.

**Comment by clayjohn** [comment]
Thanks for the interest! We already use this in the 4.0 branch. :)

In the future please don't ask questions like this on the Bug tracker, this place is for bug reports only. To discuss development join us at chat.godotengine.org

**Comment by ThePreviousOne** [comment]
cool. and thanks for the link
