### ISSUE TITLE
Gltf vertex color is not imported correctly.

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#46512]
**Godot version:**
3.2.3 stable

**Issue description:**
I am using Blender 2.92 to export a simple cube with vertex color.

**Steps to reproduce:**
1. Make a cube with vertex color
2. Export it to glb
3. Import it to Godot
4. make a saptial material with vertex color as albedo
5. the color is not matched in blender

The first one is from Blender.
![001](https://user-images.githubusercontent.com/24987226/109421645-29409e00-7a13-11eb-92a7-c5f16554b4c6.png)

The second one is from Godot.
![002](https://user-images.githubusercontent.com/24987226/109421640-280f7100-7a13-11eb-8ce0-fefdb16d4a7e.png)

**Minimal reproduction project:**
[test-vertex-color.zip](https://github.com/godotengine/godot/files/6056919/test-vertex-color.zip)

I made a simple project. It contains the blender file and a godot project

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
I believe this is fixed in the 3.2 release candidates. Can you test?

**Comment by nagasawamaki** [comment]
> 
> 
> I believe this is fixed in the 3.2 release candidates. Can you test?
> 
> ![image](https://user-images.githubusercontent.com/32321/109426532-01195680-79a3-11eb-91d8-e1cfcf859abc.png)

oh yeah. It is fixed. Thanks
