### ISSUE TITLE
typing 'continue' in a non-loop in a shader causes freezing, occasional crash

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#46521]
**Godot version:** 3.2.3 stable

**OS/device including version:** Windows 10

**Issue description:**

Accidentally put continue outside of a loop, Godot crashed. Attempted to reproduce I was only able to get temporary freezes.
Expected behaviour: shader should just throw an error and not render like other errors do.

**Steps to reproduce:**
write this shader:
```
shader_type spatial;

void fragment(){
	continue;
}
```

**Minimal reproduction project:**

[ShaderCrashTest.zip](https://github.com/godotengine/godot/files/6057573/ShaderCrashTest.zip)

**Comment by qarmin** [comment]
In Godot 3.2.4 rc 3 this error is shown me:
```
ERROR: get_current_version: SceneShaderGLES3: Fragment Program Compilation Failed:
0(1230) : error C1119: "continue" not in loop
```

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by Ev1lbl0w** [comment]
Seems there are some instances where the code isn't returning after an error:
https://github.com/godotengine/godot/blob/e3dd38c9f0064a8fa81d934fc5323d5816e710e4/servers/rendering/shader_language.cpp#L5918-L5921
https://github.com/godotengine/godot/blob/e3dd38c9f0064a8fa81d934fc5323d5816e710e4/servers/rendering/shader_language.cpp#L5960-L5964
