### ISSUE TITLE
Godot versioning

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#4653]
http://godotengine.org/article/maintenance-release-godot-2-0-3 have something like:

"Ability to shrink all images x2 on load"
isn't that a feature? Why then it's 2.0.3 and not 2.1? Why there was bump to 2.0? There should be some info on how Godot versions itself...

Or just use http://semver.org/ 😛

**Comment by reduz** [comment]
We made an exception because some users needed it for production games and
it's a relatively simple addition

**Comment by slapin** [comment]
I think adding small features in patch releases can't be currently avoided due to state of affairs.
We can leave feature releases for major features.
Nobody promised there's no new bugs in patch releases,
so nothing stops from adding features.

**Comment by akien-mga** [comment]
Yeah don't overdo it, we never promised LTS and 100% stable API. We only promise that patch releases are production ready.

**Comment by Marqin** [comment]
>production ready

That definion varies...
![AC glitch](http://s3.amazonaws.com/digitaltrends-uploads-prod/2014/11/AC-unity-glitch.jpg)

**Comment by akien-mga** [comment]
What am I supposed to make of that? If you think that 2.0.3 is less stable than 2.0, please open bug reports.

**Comment by Marqin** [comment]
First you say

>never promised LTS and 100% stable API

but then you say

>production ready

So maybe your "production ready" is somehow different. You should define it. Some SLA or something from ISO/IEC 9126.

**Comment by akien-mga** [comment]
Ok this is pointless.

**Comment by akien-mga** [comment]
Feel free to maintain your own branch if you have a problem with mine, I don't plan to change what I backport or how I version maintenance releases.

**Comment by Marqin** [comment]
@akien-mga what's your problem with standarisation of versioning and why you have closed this issue? Professionals shouldn't pour out their frustrations into work.

**Comment by Marqin** [comment]
>I don't plan to change what I backport or how I version maintenance releases.

Which part of

>There should be some info 

means

>change

?

**Comment by Marqin** [comment]
@reduz @punto- @vnen Why do you accept such rudeness in this community?

**Comment by SuperUserNameMan** [comment]
( @Marqin : which AAA game this screenshot comes from already ? )

**Comment by vnen** [comment]
@Marqin Akien is a bit too harsh sometimes. The issue itself is of simple solution as you stated in the OP: a proper informational page about how Godot changes version number. Godot doesn't need to take semver to the letter.

IMO Godot has been very obscure in terms of development path and people who don't follow closely the community on IRC likely has little clue of what's going on. The versioning system is one bullet in this topic.

**Comment by reduz** [comment]
Easy guys, this was an exception, not the rule

**Comment by punto-** [comment]
This build is labeled "stable", and this feature didn't make the build
unstable, so the build is consistent with the way it's labeled. I don't
know what information is out there about our versioning procedure, maybe we
need more (I wouldn't be surprised if that were the case, there are many
efforts underway to document everything better), but that doesn't mean a
stable build can't have features. As Akien says, it's production ready. You
don't have to shrink your textures, it's off by default :p
