### ISSUE TITLE
Duplicated resource are shown as empty in inspector at runtime

### ISSUE THREAD

**Issue by yoskeleton** [godotengine/godot#46537]
**Godot version:**

v3.2.4.rc3.official

**Issue description:**

A duplicated resource appear as EMPTY in the inspector at runtime. We cant edit / inspect values. 
I was expecting to be able to watch and modify values at runtime.

![duplicated_empty](https://user-images.githubusercontent.com/8815330/109445095-1a6fe080-7a3f-11eb-8ede-dc75238ee081.png)

**Minimal reproduction project:**
[duplicated_resource_empty.zip](https://github.com/godotengine/godot/files/6058802/duplicated_resource_empty.zip)

**Comment by Calinou** [comment]
Related to #39847.

**Comment by raulsntos** [comment]
If I understood the issue I think it's unrelated to #39847.

Can anyone still reproduce this issue in Godot 3.5 or any later release? I was unable to reproduce in v3.5.stable.mono.official [991bb6ac7]:

![image](https://user-images.githubusercontent.com/3903059/187923602-e12e0af0-57b8-4132-b4e1-f4d45c0d6769.png)

The `duplicated_resource` property does not show as `[empty]` and if clicked it can be edited/inspected.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
