### ISSUE TITLE
PopupMenu has incorrect height limit

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#46545]
Godot version:
4.0.dev.165d77a49

OS/device including version:
Windows 10

Issue description:
PopupMenu of OptionButton and MenuButton has incorrect height limit, resulting in it goes above and covers the button. Instant selection of menu item by mistake upon mouse release in this case is very frequent.
![popup_menu_2](https://user-images.githubusercontent.com/28705694/109471109-42952900-7aab-11eb-98ee-9d7e11683872.gif)

This affects the project manager.
![popup_menu_1](https://user-images.githubusercontent.com/28705694/109471106-4163fc00-7aab-11eb-965e-a84e8797a05e.gif)

Steps to reproduce:
Open the project manager and click on the language button.

Minimal reproduction project:
No need.

**Comment by floppyhammer** [comment]
The issue stems from the following code in `popup_menu.cpp`:
```gdscript
if (is_inside_tree()) {
    int height_limit = get_usable_parent_rect().size.height;
    if (minsize.height > height_limit) {
        minsize.height = height_limit;
    }
}
```
`get_usable_parent_rect()` doesn't return the correct height.

**Comment by floppyhammer** [comment]
I suppose this can be closed now since the menu item selection issue has been fixed.

**Comment by KoBeWi** [comment]
The input bug was fixed, but menus appearing over their source button still look bad, idk 🤔Though the issue has lower priority now.

**Comment by floppyhammer** [comment]
@KoBeWi Potential solutions are plenty. Some typical ones from other apps:

Inkscape (pretty close to what we have now)
<img width="694" alt="inkscape" src="https://user-images.githubusercontent.com/28705694/159627166-9087e4eb-a7f9-462c-ab39-ea68aff0533e.png">

GIMP
<img width="575" alt="gimp" src="https://user-images.githubusercontent.com/28705694/159627231-7ad4c07c-09dc-439d-ac57-906416070a33.png">

Code
<img width="700" alt="code" src="https://user-images.githubusercontent.com/28705694/159627242-0854a9e8-7b65-480b-8ec9-e4620f86355c.png">

We might need more discussions on this.

**Comment by KoBeWi** [comment]
I think the best solution would be GIMP + Inkscape. If popup is too big to fit at the bottom, show it at the top. If it's too big for the entire screen, show it *next to* the button and add scrolls.

**Comment by floppyhammer** [comment]
None of these shows the menu next to the button though. The Inkscape screenshot might be a bit confusing. A gif shows it more clear.

![inkscape2](https://user-images.githubusercontent.com/28705694/159696490-8fbfc1cf-6bc2-4db3-8431-7a33fb3ed191.gif)

**Comment by KoBeWi** [comment]
Ah right. I've seen popups next to menu in Audacity though. It's a nice solution.
