### ISSUE TITLE
Use of MODULATE in shader does not suppress automatic modulation (3.2.4 regression)

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#46546]
**Godot version:**
3.2.4.rc3.official, using GLES2.

**OS/device including version:**
Arch Linux, NVIDIA GeForce 9600 GTX.

**Issue description:**
The [documentation for CanvasItem shaders](https://github.com/godotengine/godot-docs/blob/317c229472171c63fca65012d7bd8d78934cfc78/tutorials/shading/shading_reference/canvas_item_shader.rst) in the 3.2 branch says:

> in vec4 **MODULATE** | Final modulate color. If used, **COLOR** will not be multiplied by modulate automatically after the fragment function.

This is a useful feature, because it lets us override any modulation inherited by parent nodes. It works as advertised in 3.2.3.stable.official, but not in 3.2.4.rc3.official. It seems that no matter whether I mention `MODULATE` in the fragment shader or not, the final fragment is automatically post-modulated anyway.

As a workaround, we can divide by `MODULATE` in the shader, but this is not ideal due to division by zero.

**Expected behaviour (3.2.3):**

The icons all have `modulate` set to `#808080`.

![2021-03-01T09:26:08_731x470](https://user-images.githubusercontent.com/90930/109470914-51aab580-7a70-11eb-9925-0864893bfc32.png)

**Actual behaviour (3.2.4-rc3):**

![2021-03-01T09:27:55_736x477](https://user-images.githubusercontent.com/90930/109470994-6b4bfd00-7a70-11eb-905b-602c0d6603e7.png)

**Minimal reproduction project:**

[modulate_issue.zip](https://github.com/godotengine/godot/files/6060102/modulate_issue.zip)

**Comment by lawnjelly** [comment]
It's something in batching I'm just looking. Interesting if it works in 3.2.3 with batching, maybe a fix for something else caused a regression.

**Comment by lawnjelly** [comment]
Am finally getting to have a look at this. I think you are absolutely right it is to do with it being a special case, where MODULATE is used in the custom shader it doesn't apply final_modulate in the canvas shader. So it may mean that the solution is simply to prevent these materials from batching, and pass them through the legacy path.

**Comment by akien-mga** [comment]
Fixed by #46676.
