### ISSUE TITLE
2.0.3 demos - demos in demos

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#4655]
**Operating system or device - Godot version:**
2.0.3

**Issue description** (what happened, and what was expected):
There is a demos folder in the demos zip file that looks to contain the same files over again.  

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Thanks, I'll have a look.

**Comment by akien-mga** [comment]
It should be fixed now on both mirrors, can you confirm?

**Comment by punto-** [comment]
Is this on Steam too?

**Comment by captainwasabi** [comment]
Confirmed fixed.  Leaving open for Steam issue

**Comment by akien-mga** [comment]
I don't think Steam is affected, the duplicate comes from when I repacked the demos with my script, but for Steam I did it manually.

**Comment by akien-mga** [comment]
Don't have access to Steam now, but I check the prepared folder over SSH and it's fine.
