### ISSUE TITLE
[3.2.4-rc3] GLES2 shader version errors

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot#46567]
**Godot version:**
3.2.4.rc3.official

**OS/device including version:**
Ubuntu 20.04 with GLES2, GeForce 1660 Super

**Issue description:**
Occasionally, when a ShaderMaterial is initialised in GLES2, the following errors appear in the 'debugger' panel (but not the console):

```
E 0:00:31.072   get_current_version: Condition "!cc" is true. Returned: __null
  <C++ Source>  drivers/gles2/shader_gles2.cpp:221 @ get_current_version()
E 0:00:31.072   bind: Condition "!version" is true. Returned: false
  <C++ Source>  drivers/gles2/shader_gles2.cpp:89 @ bind()
E 0:00:31.072   _get_uniform: Condition "!version" is true. Returned: -1
  <C++ Source>  drivers/gles2/shader_gles2.h:267 @ _get_uniform()
E 0:00:31.072   _get_uniform: Condition "!version" is true. Returned: -1
  <C++ Source>  drivers/gles2/shader_gles2.h:267 @ _get_uniform()
E 0:00:31.072   _get_uniform: Condition "!version" is true. Returned: -1
  <C++ Source>  drivers/gles2/shader_gles2.h:267 @ _get_uniform()
E 0:00:31.072   _get_uniform: Condition "!version" is true. Returned: -1
  <C++ Source>  drivers/gles2/shader_gles2.h:267 @ _get_uniform()
E 0:00:31.072   _get_uniform: Condition "!version" is true. Returned: -1
  <C++ Source>  drivers/gles2/shader_gles2.h:267 @ _get_uniform()
E 0:00:31.072   _get_uniform: Condition "!version" is true. Returned: -1
  <C++ Source>  drivers/gles2/shader_gles2.h:267 @ _get_uniform()
```

I can't seem to isolate this with any precision other than that it seems to happen intermittently in rc3 when a ShaderMaterial is initialised; this didn't happen in rc2.

Apologies for the lack of accuracy here; I'll keep looking at this and add anything I find.

**Steps to reproduce:**
Initialise a ShaderMaterial in GLES2. (more TBD)

**Minimal reproduction project:**
Will upload one if I can isolate this further.

**Comment by akien-mga** [comment]
Do you still get the issue after a reboot? Nvidia drivers are typically broken on Linux after an update, until rebooted with the new drivers built against your kernel.

Also can you confirm if the issue happens only with 3.2.4 RC 3 (i.e. re-test RC 2)? This could also help check if it's a driver update regression instead of a Godot bug.

**Comment by snoopdouglas** [comment]
Ah, funnily enough: I've had a few reboots since, have just retested it and can't reproduce it. That might've been it, and though I don't recall updating the drivers myself just before these errors appeared, I guess it might've been a queued upgrade.

**Comment by akien-mga** [comment]
Thanks for testing, closing then.
