### ISSUE TITLE
weird offset in tilemap

### ISSUE THREAD

**Issue by havlenapetr** [godotengine/godot#46575]
**Godot version: v3.2.3**

**OS/device including version: macOS 10.15.7**

**Issue description: when used tileset with right grid settings & place same tile next to other, small gap will be created between these same tiles. When I place same tiles in Krita editor, tiles are aligned correctly. Check screenshot here: https://drive.google.com/file/d/1Mtl1mCEjAKOqkUc2P-_yoQmpCAGgwiXb/view?usp=sharing upper row are 2 tiles placed from godot editor & below are tiles placed in Krita & exported like single image into godot**

**Steps to reproduce:**
tileset here image: https://drive.google.com/file/d/1nFBjNDGGIVXu2OGDgYexZM2GKZwwz7AA/view?usp=sharing

**Comment by groud** [comment]
That looks like an expected behavior.  It seems like you are using a texture with the "filter" flag on, which causes such problems on the sides of the tileset. The pixels at the side of the tiles get interpolated with an empty area on, the TileSet, which causes such problems.

**Comment by havlenapetr** [comment]
> That looks like an expected behavior. It seems like you are using a texture with the "filter" flag on, which causes such problems on the sides of the tileset. The pixels at the side of the tiles get interpolated with an empty area on, the TileSet, which causes such problems.

could you please give me url for this issue? don't know what 'texture with the "filter" flag on' means, where is this flag?

**Comment by groud** [comment]
https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_images.html

Click on the texture in the filesystem dock, then click on the import dock.

**Comment by havlenapetr** [comment]
> https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_images.html
> 
> Click on the texture in the filesystem dock, then click on the import dock.

thanks very much, it was my problem. don't why this checkbox is checked by default. closing this issue
