### ISSUE TITLE
[3.2.4 RC3] Texture Rect doesn't Render on iOS

### ISSUE THREAD

**Issue by Tekuzo** [godotengine/godot#46577]
**Godot version:**

Godot 3.2.4 RC3

**OS/device including version:**

iPhone SE running iPhone OS 14.4
iPad 5th Generation Running iPad OS 14.4

**Issue description:**

I have a texture rect in a control node that I use as my health bar for the player.
The texture rect stretch mode is set to tile and I control the rect_size through code to dynamically show the player's HP.

Doing it this way works normally on Windows, Mac and Android. When I try to play the game on my iPhone or iPad after exporting to iPhone, opening xcode and running the project on my phone, the texture rect only shows as a black box the size of the texture rect.

When I switch the stretch mode from tile to scale it will render properly.

**Steps to reproduce:**
Canvas Layer -> Control -> Texture Rect -> Stretch Mode: Scale

**Minimal reproduction project:**

My setup to reproduce this glitch is a scene with a Canvas Layer -> Control -> Texture Rect

I have the texture rect stretch mode to Tile and it will render like the screen shot
![IMG_0103](https://user-images.githubusercontent.com/6944363/109580934-7121fc80-7ac9-11eb-83f9-dff9c91ae2fa.PNG)

**Comment by Calinou** [comment]
@Tekuzo Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, which renderer are you using (GLES3 or GLES2)?

**Comment by Tekuzo** [comment]
GLES2
I will build a sample project quickly

**Comment by naithar** [comment]
Do older versions (rc2, 3.2.3) has same issue or it's 3.2.4rc3 only?

**Comment by Tekuzo** [comment]
3.2.3 did have the same issue and I didn't think anything of it then because 3.2.3 [had this issue](https://github.com/godotengine/godot/issues/42164) which is why I tried out  3.2.4 RC3

**Comment by naithar** [comment]
Does switching to GLES3 for iOS help?

**Comment by Tekuzo** [comment]
> Does switching to GLES3 for iOS help?
Unsure I didn't switch it to GLES3 as I have been unable to re-produce the bug outside of my project.

I have tried to create a minimal project to upload that features the glitch, and it renders every time, so it must be something else that is causing it to not render.
