### ISSUE TITLE
Unable to create multiple Occlusion Polygons in the same tile in AutoTile editor.

### ISSUE THREAD

**Issue by CrowSR** [godotengine/godot#46580]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
Likely not relevant.

**Issue description:**
Attempted to use multiple Occlusion Polygons per tile as with Collision, but the second polygon overwrites the first.
What should happen is that the second polygon does not overwrite the first.

Youtube video demonstrationo: https://youtu.be/mDK4H6Z9fkI

**Steps to reproduce:**
1. Create Tilemap node.
2. Create Tileset.
3. Go into the Occlusion tab.
4. Create one polygon inside a tile, then create another polygon inside the same tile.

**Minimal reproduction project:**
[Occlusion Polygon Bug.zip](https://github.com/godotengine/godot/files/6065449/Occlusion.Polygon.Bug.zip)

**Comment by Calinou** [comment]
I don't think having multiple occlusion polygons was ever supported in TileMap in the first place.

**Comment by CrowSR** [comment]
![strange](https://user-images.githubusercontent.com/32560328/109829539-6330c080-7c1c-11eb-8030-62e55ad95efa.png)
Yes, I believe it does work with collision polygons on the AutoTile editor.
As shown in the image attached, I have two polygons on the same tile. I have not done extensive testing but so far, when playing the game both the collision polygons seem to work properly.
Though, I thought this was intended, but in retrospect, the inability to select the first polygon created in the same tile while in the editor is quite strange.

**Comment by groud** [comment]
Closing as multiple collision shapes/occlusion polygons is implemented on master.

**Comment by ka0s420** [comment]
"Closing as multiple collision shapes/occlusion polygons is implemented on master."

While collision polygons work this way (and did in 3x) I'm using v4 beta 2 and you still can't add more than one occlusion polygon per tile.
