### ISSUE TITLE
project settings and import settings missing

### ISSUE THREAD

**Issue by DevYoshi** [godotengine/godot#46582]
everything was normal but almost all of the project settings are gone and a lot of the texture import settings are gone, how would I fix it? I used this to compile it https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html

**Comment by EricEzaM** [comment]
This is not enough information for anyone to help. Please amend your post to match the template format - it is there for a reason.

**Comment by DevYoshi** [comment]
> This is not enough information for anyone to help. Please amend your post and title to match the template format - it is there for a reason.

I'm sorry but, I don't know how to give any more info, I said what I have used to compile and I have said what is wrong and I have never used git hub before unless to download stuff so I don't know how specific you have to be compared to how much you have to be on reddit.

**Comment by floppyhammer** [comment]
@DevYoshi Refer to the template on the reporting bug page. Or you could check out the issues submitted by others.

**Comment by Firepal** [comment]
Stating the way you compiled Godot isn't really helping as much as you think it does. 

What exactly do you mean by "the project settings and texture import settings are missing"? Did many settings in a project reset?

**Comment by Calinou** [comment]
If you've compiled the `master` branch, you need to toggle **Advanced Settings** in the Project Settings to see all the project settings as it was before.

**Comment by DevYoshi** [comment]
> Stating the way you compiled Godot isn't really helping as much as you think it does.
> 
> What exactly do you mean by "the project settings and texture import settings are missing"? Did many settings in a project reset?

no, most of the settings on the side are just gone

**Comment by EricEzaM** [comment]
Can you please post a screenshot

**Comment by DevYoshi** [comment]
> Can you please post a screenshot

i have one but calinou's method worked but for some reason, all the pop-ups when you click on buttons are gone

**Comment by DevYoshi** [comment]
and the texture import settings are different and dont have filter option or detect 3d

**Comment by EricEzaM** [comment]
The import dock was changed recently and there may be some bugs. I don't recall who made the changes. I know reduz added a "default import settings" feature in the Project Settings, but that shouldn't affect this.

**Comment by Calinou** [comment]
> i have one but calinou's method worked but for some reason, all the pop-ups when you click on buttons are in the wrong place

This is a regression from DisplayServer and it's already been reported.

> and the texture import settings are different and dont have filter option or detect 3d

Texture filter/mipmap settings have been removed since these are now defined in the location where you *use* the texture instead (such as CanvasTexture for 2D and StandardMaterial3D for 3D).
