### ISSUE TITLE
CPU lightmapper capture doesn't make use of the environment lighting

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#46591]
*See also https://github.com/godotengine/godot/issues/46332.*

**Godot version:** `3.2` Git 4f891b706

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 460.39)

**Issue description:**

The new CPU lightmapper's dynamic object capture doesn't make use of the environment lighting. This occurs in GLES3 at least, but I remember it happening in GLES2 as well.

While peeking around in `scene.glsl`, I noticed there's code for environment lighting in the lightmap capture shader but I can't seem to find a way to enable it.

### BakedLightmap visible

*Environment lighting is not used, only probe lighting is. This is fine in theory, but since the capture probes don't have environment lighting baked in, it looks bad.*

![2021-03-02_15 25 16](https://user-images.githubusercontent.com/180032/109662620-8c454880-7b6b-11eb-88a0-dce4e66fd41c.png)

### BakedLightmap hidden

*Environment lighting is used as the lightmap capture isn't used when the BakedLightmap node is hidden. Note that the lightmaps still affect the baked mesh though – whether this is a bug or not is a separate issue.*

![2021-03-02_15 25 33](https://user-images.githubusercontent.com/180032/109662624-8d767580-7b6b-11eb-9520-20cc3836053e.png)

**Steps to reproduce:**

Add a BakedLightmap node, add two MeshInstances (one baked, one not baked), bake and move the non-baked mesh around.

Note that the DirectionalLight is hidden in the MRP to work around https://github.com/godotengine/godot/issues/46332.

**Minimal reproduction project:** [test_lightmap_shadow.zip](https://github.com/godotengine/godot/files/6069322/test_lightmap_shadow.zip)

**Comment by antocorr** [comment]
Hi, I'm sure it captures it with GLES2.
OLD Lightmapper
![photo_2021-03-02 18 34 07](https://user-images.githubusercontent.com/1094862/109689745-e81ccb00-7b85-11eb-8936-0eb1931d3f57.jpeg)

New CPU lightmapper on GLES2

![photo_2021-03-02 18 34 03](https://user-images.githubusercontent.com/1094862/109689781-f1a63300-7b85-11eb-8c9d-37a75566d7d2.jpeg)

**Comment by SkanerSoft** [comment]
You are literally a couple of hours ahead of me! I wanted to create a proposal for adding a lighting environment. Because hiding the CPULighmapper adds ambient light, but the shading of the probes is lost. I'm waiting for a solution!

**Comment by SkanerSoft** [comment]
@JFonS 
I also don’t know, can I write here or create a new issue?
When baking lighting, the GridMap cannot be hidden, it is always shown
Also, I cannot disable it from baking. It is forcibly baked.

GridMap before bake
![1](https://user-images.githubusercontent.com/13809475/109810804-0c86af00-7c3b-11eb-929d-04d1317a7c5b.gif)

GridMap after bake
![2](https://user-images.githubusercontent.com/13809475/109810905-38099980-7c3b-11eb-8b19-b2a4c31508b1.gif)

**Comment by SkanerSoft** [comment]
Godot 3.2.4 RC 4.
Environment settings are still ignored.
In particular, it is not possible to set any lighting if DirectionalLight is hidden. Objects become black and unnatural.

https://user-images.githubusercontent.com/13809475/110492867-8e774c00-8103-11eb-86e2-d83b3de6ddc2.mp4

**Comment by JFonS** [comment]
Yes, I'm working on adding an option to enable environment lighting on dynamic capture options, but it didn't make it to the RC4 release.

**Comment by Calinou** [comment]
> Objects become black and unnatural.

In your case, this happens because the object is partially stuck in solid baked geometry.

**Comment by SkanerSoft** [comment]
Maybe the solution could be made easier?
If technically, of course, it's not more difficult to implement.
Just turn off the use of recorded light and use only the environment. I don't know how it works internally, but I think it should help.
![Image 001](https://user-images.githubusercontent.com/13809475/110502668-7526cd80-810c-11eb-9334-118cc40a48aa.jpg)

**Comment by Calinou** [comment]
> Just turn off the use of recorded light and use only the environment. I don't know how it works internally, but I think it should help.

The issue with using only environment lighting is that the object will look out of place since it won't take any indirect lighting and won't be shaded if it's not in direct sunlight.

**Comment by JFonS** [comment]
I'm adding a property in `BakedLightmapData` that enables environment lighting for all the objects that use its "captured" lighting. From what I tested so far it looks ok and should fix your issues. But if that's not enough for your use case we can explore other options later.

**Comment by Calinou** [comment]
> I'm adding a property in `BakedLightmapData` that enables environment lighting for all the objects that use its "captured" lighting. From what I tested so far it looks ok and should fix your issues. But if that's not enough for your use case we can explore other options later.

Sounds good to me :slightly_smiling_face: Personally, I'd enable it by default as you'll probably want to always enable it unless your level is 100% indoors.

**Comment by SkanerSoft** [comment]
It is perfectly! I completely trust your solutions, with the next update I will definitely try and report everything!
Finally, I would like to ask the last question.
Is it possible to somehow limit the darkness? This means not turning the shadow completely black.

That is, in the same way, you can specify the color of the shadow from a light source, which can be not only black.

![Image 002](https://user-images.githubusercontent.com/13809475/110505346-1c0c6900-810f-11eb-9766-7a680eeb1568.jpg)

**Comment by Calinou** [comment]
> Is it possible to somehow limit the darkness? This means not turning the shadow completely black.

You should be able to define ambient lighting in the Environment resource to achieve this. If it's not taken into account by the lightmapper, I'd consider this to be a bug – although we may want to apply this ambient lighting in real-time rather than baking it into the lightmap. This way, the ambient lighting can be changed without having to bake the lightmaps again. This can be useful for special effects like thunder.

That said, increasing ambient lighting too much will create a dull appearance. Instead, you can add subtle, shadow-less OmniLights or even SpotLights to prevent specific areas from being too dark.

**Comment by Calinou** [comment]
> I tried solving this through adding OmniLight and it works. But their presence reduces the FPS, since the game is planned for Android.

If you set the OmniLight's bake mode to All, it shouldn't affect performance in any meaningful way (other than making bake times longer).

**Comment by JFonS** [comment]
> Sounds good to me slightly_smiling_face
Personally, I'd enable it by default as you'll probably want to always enable it unless your level is 100% indoors.

@Calinou Yeah, I added the `interior` property, and it's disabled by default. I'm just trying to find a good way to update all the objects whenever the property is changed, since we currently don't have any relation to which objects are affected by each lightmap capture.

@SkanerSoft You should be able to set a custom environment for the bake. It's under the "Environment" section of the `BakedLightmap` node properties. Normally you can set a custom color, and it will lighten up the whole scene, but I think there's a bug in RC4 which I will fix in the next release. 

If you want to test right now how it will look, you can set a "Cutsom Sky", and assign a `PanoramaSky` with a solid color image. This is the same as setting a custom color, so after the fixes it will be easier to use.

**Comment by SkanerSoft** [comment]
Ok, I tried all the options, and this is the result:

When using "Custom Color" - shadows are completely black
When using "Custom Sky" - shadows are completely black
When using "Scene" - shadows are completely black

I've tried changing the intensity and it only works on the lighter areas. They become super light.

And in those places where the shadow falls - everything is still black. This creates a very strong contrast.

The option with additional OmniLoght works, however, so that the FPS does not sag, you need to make them hidden or delete them after baking.
![Image 007](https://user-images.githubusercontent.com/13809475/110587038-26b51580-8184-11eb-8f94-8a06b6df4ec2.jpg)

However, this behavior is also quite normal.

**Comment by akien-mga** [comment]
Fixed by #46932.

**Comment by JFonS** [comment]
@SkanerSoft The latest PR that was merged (will be available in the RC5 realease) adds the new property "Environment -> Min Light" in `BakedLighmap`. That should give you some control over the darkest areas in the lightmap :)
