### ISSUE TITLE
Exporting from Linux command line does not work

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#46597]
**Godot version:**
3.2.3

**OS/device including version:**
Linux Mint

**Issue description:**
Following the documentation I issued the following command:

/opt/Godot/Godot  --path ~/Godot/games/rex/game --export "Linux/X11"  ~/Godot/games/rex/game/build/test02_binaries/linux/rex.x86_64

Godot started up (I thought it was meant to be headless), then quit with an error.

I may be doing something wrong, but I'm just following the documentation, which states to do:

godot --path path_to_your_project --export my_export_preset_name game.exe

**Comment by chucklepie** [comment]
I think I found the problem. You cannot put a path to your executable, e.g.

/opt/Godot/Godot  --path ~/Godot/games/rex/game --export "Linux/X11"  ~/Godot/games/rex/game/build/test02_binaries/linux/rex.x86_64

instead it puts the binary in the current directory, which is a bit silly because it means if you want to make 8 different builds you need to create a build script that does a 'cd' before every build...

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/28646#issuecomment-490377033.
