### ISSUE TITLE
2dpathfinder freezes the game

### ISSUE THREAD

**Issue by voidplayer** [godotengine/godot#466]
If points are in direct sight of each other, it works, but if it has to make a turn, it freezes the game

I made a small scene where it happens:
http://speedy.sh/Dyr3u/pathfinder.tar.bz2

forum reference:
http://www.godotengine.org/forum/viewtopic.php?f=11&t=625&start=10#p2788

**Comment by akien-mga** [comment]
The link to the test scene is dead so I can't use it to try to reproduce, but as the 2D pathfinding demo works just fine, I guess this issue has been fixed.

**Comment by Luraktinus** [comment]
We found the bug again, it happens on some Android devices
here our code
https://github.com/Luraktinus/EN_/tree/Test
