### ISSUE TITLE
Nintendo Switch Joy-Con Controller: Analog Stick Inputs Override Existing Buttons

### ISSUE THREAD

**Issue by mbforbes** [godotengine/godot#46612]
**Godot version:** v3.2.3.stable.mono.official
**OS/device including version:** macOS 10.15.7 (w/ Intel)

**Issue description:**
When I connect a Nintendo Switch Joy-Con controller (issue is with both R and L, but will show only R for simplicity), the analog stick inputs are indistinguishable from two of the other buttons:

![godot-joypads](https://user-images.githubusercontent.com/1170062/109763467-f8916d80-7ba6-11eb-8a81-b5f1e048ca55.gif)

(I'm wiggling the analog stick at the end.) Just to be clear, the issue isn't that the axis becomes buttons (#21918), though it would be great if it didn't. The issue is that it becomes _the same buttons_ as other ones you actually press. (Also, it seems to map 4 directions onto only 2 buttons?)

The [SDL2 Gamepad Tool](https://www.generalarcade.com/gamepadtool/) is able to correctly identify the analog stick inputs:

![gamepad-tool](https://user-images.githubusercontent.com/1170062/109763544-12cb4b80-7ba7-11eb-99c2-f8ca67ccbb57.gif)
(the analog stick inputs have shown up as the arrows)

I saw from this [reddit thread](https://www.reddit.com/r/godot/comments/ej6tpq/i_did_some_research_on_gamepad_behaviour_that_id/) and [corresponding sheet](https://docs.google.com/spreadsheets/d/14_phchmecgCCmOdZ-bkDN_-TvAcrUNarw2sRFwODfPU/edit#gid=0) that the analog stick might be mapped to buttons instead of axis. Of course, this wouldn't be ideal—[Gamepad Tester](https://gamepad-tester.com/) is able to read the analog stick axis values of this same controller—but it would be workable as long as I was able to distinguish the buttons it maps the analog stick to, from the actual buttons! :sweat_smile:

From looking at related issues (e.g., #21918), it looks like I can redefine an environment variable (`SDL_GAMECONTROLLERCONFIG`) to provide a custom mapping. But there are a few issues here:
- When I do this, I don't observe any change.
- I'm not sure how to tell whether Godot is reading this environment variable correctly.
- (I'm also not sure how this works with GUI applications on macOS—if I export a new variable on my `.bash_profile`, and start the Godot app with Finder, will it see these variables?)
- I'm also worried that doing this wouldn't be portable. Would my local environment variable make it into a built game?

**Steps to reproduce:**
- Attach Nintendo Switch Joy-Con (R) via Bluetooth to a Mac
- Open the "Joypads Demo / Tool" project (linked below)
- Try using the analog stick

**Minimal reproduction project:**
https://godotengine.org/asset-library/asset/140

**Parting words:** I just briefly wanted to thank you all for working on such a massive, wonderful project and fielding endless problems from newbs like me.

**Comment by akien-mga** [comment]
Can you try 3.2.4 RC 3? Mappings have been updated since 3.2.3 and might have fixed this issue.

**Comment by mbforbes** [comment]
I downloaded 3.2.4 RC 3 and am attempting to run the Joypads Demo / Tool project, but as luck would have it, it might be broken with that version? I'm freshly getting an error at:

https://github.com/godotengine/godot-demo-projects/blob/master/misc/joypads/joypads.gd#L60

```
E 0:00:01.676   get_node: (Node not found: "16" (relative to "/root/joypads/Buttons/ButtonGrid").)
  <C++ Error>   Condition "!node" is true. Returned: __null
  <C++ Source>  scene/main/node.cpp:1386 @ get_node()
  <Stack Trace> joypads.gd:60 @ _process()
```

Will debug that when possible, apologies for any delay.

**Comment by KoBeWi** [comment]
Duplicate of #21918, I just tested that it's indeed fixed.

Here's fixed demo:
[joypads.zip](https://github.com/godotengine/godot/files/6078747/joypads.zip)
`JOY_BUTTON_MAX` is now 22 for some reason, which caused the bug.

**Comment by mbforbes** [comment]
Tested out — works, thank you! I appreciate you attaching the fixed project! Will close this issue.

There are three separate issues now I may consider opening issues for. Please let me know whether I'm just getting greedy.

1. The vibrate function (in that demo project) does not work (though it does on the [GamepadTester](https://gamepad-tester.com/))

2. The axis value is only ever at 0 or 1 (or -1). There's no fine-grained values possible. (The [GamepadTester](https://gamepad-tester.com/) does detect fine-grained values.)

3. For me, after a few minutes and tests, the Joy-Con (R) seems to change some kind of new state, where the home button permanently lights up blue, and both the SDL2 Gamepad tool and Godot stop being able to detect _any_ inputs. (Somehow, yet again, the [GamepadTester](https://gamepad-tester.com/) is still able to continue to read all values without trouble after this happens.)
