### ISSUE TITLE
Unable to Select GLES3.0 Renderer When Starting A New Project (Hardware is Fine)

### ISSUE THREAD

**Issue by ACB-prgm** [godotengine/godot#46626]
**Godot version:**
3.2.4 beta4 official

**OS/device including version:**
MacOS 10.15.7 Catalina
MacBook Pro (15-inch, 2018)
Processor: 2.2 GHz 6-Core Intel Core i7
Memory: 16 GB 2400 MHz DDR4
Graphics: Radeon Pro 555X 4 GB

Also occurring on my 2020 iMac:
MacOS 10.15.7 Catalina
Graphics: Radeon Pro 5300 GPU (4GB GDDR6)

**Issue description:**
When creating a new project, the option to select the GLES 3.0 renderer is disabled/greyed out, and "Not supported by your GPU drivers" is displayed.  This was not the case in Godot 3.2.3.  I can however switch to GLES3.0 in the editor once the project is created.

**Steps to reproduce:**
Idk if this is happening on all operating systems, but on macOS:
1. Open Godot Project Manager
2. click "New Project"
3. OpenGL ES 3.0 will be disabled

**Minimal reproduction project:**
NA

**Comment by bruvzg** [comment]
Fixed in beta5 and newer.
