### ISSUE TITLE
Unable to build C# after new install on Windows 10

### ISSUE THREAD

**Issue by Volts-s** [godotengine/godot#46628]
**Godot version:**
v3.2.3.stable.mono.official

**OS/device including version:**
Windows Version 10.0.19042.804, 
Alienware Aurora R11, Intel i7-19799 CPU
GeForce RTX 2080 Super

**Issue description:**
All builds of C# projects fail.

**Steps to reproduce:**
Install Godot and .NET SDK 3.1.406.  Then create new project using the Pong with C# example and attempt to build it.

**Minimal reproduction project:**
It fails with the Pong with C# example.  I also included the build log file
[TestSharp.zip](https://github.com/godotengine/godot/files/6078196/TestSharp.zip)
[msbuild_log.txt](https://github.com/godotengine/godot/files/6078204/msbuild_log.txt)

**Comment by Calinou** [comment]
You need to install the .NET Framework 4.5 targeting pack as described in https://github.com/godotengine/godot-docs/issues/4672.

**Comment by Volts-s** [comment]
Thanks for the quick response. This corrected the problem.
