### ISSUE TITLE
KinematicBody2D is_on_floor() and is_on_wall() are refusing to return true on the same frame when using small vector values

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#46634]
**Godot version:** v3.2.4.rc3
**OS/device including version:** Windows 8.1
**Issue description:**

![Untitled](https://user-images.githubusercontent.com/15337628/109876796-4cdf3f00-7cc6-11eb-89e4-07d75e0ec950.png)

```
extends KinematicBody2D
var motion = Vector2()

func _physics_process(delta):
	motion += Vector2(1,1)
	motion = move_and_slide(motion, Vector2.UP)
	
	for i in get_slide_count():
		print(get_slide_collision(i).collider.name)
	print('WALL COLLISION: ' + str(is_on_wall()))
	print('FLOOR COLLISION: ' + str(is_on_floor()))
	print('----------------------------------')
```
The Godot icon moves into the two walls, then prints this, flipping back and forth:
```
South Wall
WALL COLLISION: False
FLOOR COLLISION: True
----------------------------------
East Wall
WALL COLLISION: True
FLOOR COLLISION: False
----------------------------------
```

If you replace the line ``motion += Vector2(1,1)`` with ``motion += Vector2(5,5)`` they will now return true on the same frame. No idea what's going on.

Here's the minimal reproduction project:
[physics_on_wall_on_floor_bug.zip](https://github.com/godotengine/godot/files/6075655/physics_on_wall_on_floor_bug.zip)

**Comment by pouleyKetchoupp** [comment]
Thanks! I can confirm on both 3.2.3 and 3.2.4.rc3.

**Comment by Calinou** [comment]
See [Shfty's character movement manifesto](https://markdownpastebin.com/?id=d9d61e67f9d64db2bd215f165b931449) for a workaround:

> - Unstable floor results make my 'is grounded' flag jitter
>   - This seems to be down to the collision margin system
>   - Use a rolling window (2-3 frames should be sufficient) that folds down to a single bool using OR to de-noise the floor check
