### ISSUE TITLE
Problem with node selection and "Inspector" dock

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#46633]
**Godot version:**

3.2.4 rc3

**OS/device including version:**

win10 64

**Issue description:**

The "inspector" dock is confusing when selecting different areas.
In the gif you can see that the information of the animationTree node is displayed correctly, then a Blend2 node is selected and the "inspector" dock shows the information of the Blend2 node but when selecting the animationTree node again, the "inspector" dock no longer displays its information, then you need to select another node and reselect the animationTree node.

The animationTree node information should be displayed in the "inspector" dock when selected, even if it is already selected.

![GIF](https://user-images.githubusercontent.com/19652075/109872262-7b303080-7c6c-11eb-8c30-7cfad9d77c5f.gif)

**Steps to reproduce:**
Necesary?

**Minimal reproduction project:**

[testSlider.zip](https://github.com/godotengine/godot/files/6079302/testSlider.zip)

**Comment by Calinou** [comment]
> Necesary?

Yes, we'd prefer not having to set up an AnimationTree setup to be able to reproduce this as it takes a bit of time to do :slightly_smiling_face:

**Comment by Torguen** [comment]
Ok added.

**Comment by Torguen** [comment]
This also happens with nodes like "Tilemap".
You select the "Tile set", the tilesets window opens and the "Inspector" dock shows the tileset information but now the information of the "Tilemap" node has disappeared from the "Inspector" dock, so even though the "Tilemap" node is selected, its information is not displayed and even if you select it again, the information will not be displayed.
Solution:
Select another node and select the "Tilemap" node again, now the information for the "Tilemap" node appears in the "Inspector" dock.

**Comment by Torguen** [comment]
This continues to happen in 3.3 rc8 mono.
This time it happens when executing.
The animation is shown, after you run, the animation is hidden, you select the animationPlayer node but the animation is not shown.
![behavior1](https://user-images.githubusercontent.com/19652075/114323916-bc4b1880-9b27-11eb-9478-c14282c49b0e.gif)

**Comment by akien-mga** [comment]
It doesn't seem the be the same issue, even if it might be related. Please open a dedicated issue for this one.
