### ISSUE TITLE
HTML5 Builds Do Not Run On Linux Mozilla Firefox Internet Browser

### ISSUE THREAD

**Issue by FallenAngelSoftware** [godotengine/godot#46647]
Hi,

HTML5 builds on Linux Mozilla Firefox Internet browser do not work?
WebGL is broken on Linux Mozilla Firefox Internet browsers.
We need an HTML5 Canvas fallback to support above Linux Internet browser.

Jesse

**Comment by akien-mga** [comment]
This is not the place to ask general questions or vague feature proposals.

Godot is an OpenGL engine and what you're asking for simply cannot be implemented. I would suggest using a JavaScript engine if you want better support for Firefox on Linux, or make your concern known to Mozilla about the bad performance on this configuration (for which there already is an upstream bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1010527
