### ISSUE TITLE
exported var of type Image are not auto-updated

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4664]
**Operating system or device - Godot version:**
official 2.0.3stable win64

**Issue description** (what happened, and what was expected):

Can't say wether it is a bug or a feature request.

When, into a script, you export a variable of type Image(), you can use the inspector to load an image.

If you modify this image file outside of the editor, the editor does not automatically update it like are usually auto-updated other external ressources like textures etc.

And if you press the little "refresh" button at the left of the script variable into the inspector, it clears the image isntead of reloading it.

Then you have to reload the image manually.

**Steps to reproduce:**
- create a script with an `export var image = Image()` (see example below)
- attach an white image to the script variable using the inspector
- edit the image using an external image editor, change the color of the pixel(0,0) and save your modification to the same file
- go back to the editor and run again (the result is be the same)
- click the little "refresh" button at the right of the script variable into the inspector (the image is cleared instead of reloaded)
- reload manually the picture and run again the script.

**Link to minimal example project** (optional but very welcome):
````
extends Node

export var my_image = Image()

func _ready():
    print( my_image.get_pixel(0,0) )
````

**Comment by kubecz3k** [comment]
This button is not for refreshing, it's for setting 'default value' (when you are declaring export variable you can assign default value for this variable)

**Comment by SuperUserNameMan** [comment]
@kubecz3k : ah ok. thanks for the info

**Comment by reduz** [comment]
Ok after many times reading this issue, I finally understand what this is about.

Images are an atomic datatype, there is simply no way to have them update if the version on disk changes because no such reference exists.  

Try using a Texture instead, or export a path to a file instead of an image. 

You can make a setter that loads the image when the path changes.
