### ISSUE TITLE
Can't close all scripts if some are unsaved

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#46649]
**Godot version:**

3.2.4 rc3 / dd1881a

**Issue description:**

When there is an unsaved script on your script list, using Close All or Close Others will stop on that script. The unsaved dialog will interrupt closing scripts, so you have to use it again.

This is especially problematic with built-in scripts, which tend to ask you to save changes even if they are unmodified.

**Steps to reproduce:**
1. Open few scripts
2. Modify 1 of them (or 2 for best effect)
3. Right click script list and Close All
4. Not all scripts are closed, because of the dialog

**Comment by Pop0p** [comment]
Hello,
This seems to be the desired behavior: 

```cpp	
for (int i = child_count - 1; i >= 0; i--) {
  ...	
  // Maybe there are unsaved changes
  if (se->is_unsaved()) {
    _ask_close_current_unsaved_tab(se);
    continue;
  }
  ...
}
```

But maybe opening popup before closing the scripts in which the unsaved files are listed with the possibility to : 
- save all
- save nothing
- cancel the action
- 
Would be a better alternative ? Like what Visual Studio does ?

**Comment by KoBeWi** [comment]
When you close all scene tabs, editor switches to each unsaved tab and separately asks what to do. Also VS Code does the same. So this is what I would expect. Right not Script Editor stops closing tabs on first popup.
