### ISSUE TITLE
Inconsistent result using draw_line() ?

### ISSUE THREAD

**Issue by brachna** [godotengine/godot#4665]
**Operating system or device - Godot version:**
Windows 8.1 x64, Godot 2.0.3

**Issue description** (what happened, and what was expected):
I was trying to make a square border selection effect using draw_line method.
I get mostly correct result, except lower-left corner doesn't get painted for some reason:
![godot_draw_line_bug_x4](https://cloud.githubusercontent.com/assets/5756107/15276805/3b130de2-1afb-11e6-9217-dfebf233bd5b.png)

**Steps to reproduce:**
1. start project, add root node, create new script.
2. add following commands to a _draw() call of the script:
draw_line( Vector2( 10, 10 ), Vector2( 20, 10 ), Color( 1.0, 0.0, 0.0 ) )
draw_line( Vector2( 10, 20 ), Vector2( 20, 20 ), Color( 1.0, 0.0, 0.0 ) )
draw_line( Vector2( 10, 10 ), Vector2( 10, 20 ), Color( 1.0, 0.0, 0.0 ) )
draw_line( Vector2( 20, 10 ), Vector2( 20, 20 ), Color( 1.0, 0.0, 0.0 ) )

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
I can confirm the bug on Mageia 6 x86_64, with the current master branch.

![spectacle q22971](https://cloud.githubusercontent.com/assets/4701338/15629607/c8af8168-251d-11e6-8c84-22f9bc5d2c42.png)

Here's a minimal example that reproduces the bug:
[bug_draw_line.zip](https://github.com/godotengine/godot/files/287980/bug_draw_line.zip)

**Comment by akien-mga** [comment]
It's also buggy when defining a line width != 1:
![spectacle h25928](https://cloud.githubusercontent.com/assets/4701338/15629772/20201620-2522-11e6-9446-79a8f80d8938.png)
But that might be a somewhat different issue.

**Comment by reduz** [comment]
No idea what to do about this, this is 100% OpenGL side, so I can't really think of much being done.
there was a reason this worked this way (I don't remember how it's called), and had to do with drawing sucecssive lines. If anyone wants to give it a check if there is an opengl option to change this behavior be welcome.

Otherwise I think this should be closed, as it can't be changed.

**Comment by reduz** [comment]
For this kind of things, using rectangles instead of lines is always the way to go

**Comment by brachna** [comment]
I use draw_line to draw more elaborate borders. draw_rect just won't do for that.
Would be a shame to resort to texture and leave scripting flexibility.

**Comment by brachna** [comment]
I've been doing more testing. One of the corners not being painted actually makes sense.
Example of 2 horizontal lines:
draw_line(Vector2( 0.0, 0.0 ), Vector2( 20.0, 0.0 ), color)
draw_line(Vector2( 0.0, 20.0 ), Vector2( 20.0, 20.0 ), color)
![godot_horizontal_lines_ok](https://cloud.githubusercontent.com/assets/5756107/16492555/ddf73f8e-3eea-11e6-8ee9-eee8dea61ebf.png)
First line starts at row 0, column 0 and it's size is 20.
Second line starts at row 20, column 0 and it's size is 20.
So it's consistent. No bugs.

The problem starts with second example of 2 vertical lines:
draw_line(Vector2( 0.0, 0.0 ), Vector2( 0.0, 20.0 ), color)
draw_line(Vector2( 20.0, 0.0 ), Vector2( 20.0, 20.0 ), color)
![godot_vertical_lines_not_ok](https://cloud.githubusercontent.com/assets/5756107/16493211/57ab6eac-3eed-11e6-9881-838ec84a19a4.png)
First line is invisible because it actually starts at row 0, column -1, size 20.
Second line starts at row 0, column 19, size 20.
One would expect them to start at column 0 and column 20 respectfully.
It makes for scripting nightmare.

**Comment by akien-mga** [comment]
Sounds similar to #3909 to some extents.

**Comment by brachna** [comment]
This draw_line thing drives me insane %)

So I've been doing a lot of tests and cooking my own draw_line alternative using draw_polygon.
You definitely got something there about rounding errors.

Horizontal tests.
![test_horizontal1](https://cloud.githubusercontent.com/assets/5756107/16547645/7b6de5ee-417d-11e6-8d9a-6f4f266c9944.gif)

Vertical tests. Especially weird is draw_line(Vector2(0.5, 0.0), Vector2(0.5, 20.0) ) which creates position 0.0, -1.0.
![test_vertical1](https://cloud.githubusercontent.com/assets/5756107/16547651/83394322-417d-11e6-8843-2cc0422d8899.gif)

Changes direction of where to apply thickness based on small position change:
![test_thickness](https://cloud.githubusercontent.com/assets/5756107/16547658/8e0bf088-417d-11e6-909b-e0820f5c48a0.gif)

This one's not about inconsistency, rather just about looking bad. The closer the line angle gets to 45 degree the more it deforms. At thickness=1 it's invisible, but at big values it's showing.
Green one is draw_line().
![test_angle_deform](https://cloud.githubusercontent.com/assets/5756107/16547659/95873f16-417d-11e6-8481-5d457e29104c.gif)

i can't even find actual code for draw_line in source. Is it "godot/drivers/gles2/rasterizer_gles2.cpp" RasterizerGLES2::_draw_primitive? Then the only solution seems to be rounding values.

**Comment by SuperUserNameMan** [comment]
I personally don't see any Godot bug here. As @reduz explained, it is 100% OpenGL side.


I think it is important to keep in mind that OpenGL lines are not meant for rendering. They are more some sort of "helper tool".

The only way to slightly "improve" their rendering would be to activate their antialiasing using a glEnable( GL_LINE_SMOOTH ): somewhere.

Even so, the Opengl lines will not be be drawn like CSS or Gimp would.
Opengl lines have no rounded or squared tips for instance.

**Comment by brachna** [comment]
The bug is incosistency.
In horizontal test:
draw_line(Vector2(0.0, 0.0), Vector2(0.0, 20.0)) produces position 0.0, -1.0
draw_line(Vector2(0.0, 1.0), Vector2(20.0, 1.0)) produces position 0.0, 1.0
And so on and so on.

As for the rest all it tells me is that OpenGL lines are terrible.

**Comment by SuperUserNameMan** [comment]
> In horizontal test:
> draw_line(Vector2(0.0, 0.0), Vector2(20.0, 0.0)) produces position 0.0, -1.0
> draw_line(Vector2(0.0, 1.0), Vector2(20.0, 1.0)) produces position 0.0, 1.0

Yeah, you're right here. Unexpectedly, the origin is (0,1) instead of (0,0)

**Comment by brachna** [comment]
-0.5 being rounded to 0.0 and 0.5 to 1.0 makes more sense here.

**Comment by SuperUserNameMan** [comment]
Actually, POINTS and LINES that are drawn using the underlying ``RasterizerGLES2::_draw_primitive()`` appears to have a wrong origin.

On the other hand, drawing a TRI and a QUAD using the same ``_draw_primitive()`` does not show this issue.

I see nothing into ``[RasterizerGLES2::_draw_primitive()](https://github.com/godotengine/godot/blob/be830d10c25e0699d516cbb0a4e8124754e5ff51/drivers/gles2/rasterizer_gles2.cpp#L164)`` that could explain this behavior.

It must thus come from OpenGL side.

However, if this behavior is standard on every implementation of OpenGL, a simple workaround could be applied to lines and points.





````
# point <--- origin at (0,-1)
	var vertices = Vector2Array();	var colors = ColorArray();
	
	vertices.push_back(Vector2( 0.0,0.0)) ; colors.push_back(Color(1,1,1));

	draw_primitive( vertices, colors, Vector2Array(), null, 1.0 );
````

````
# line <--- origin at (0,-1)
	var vertices = Vector2Array();	var colors = ColorArray();
	
	vertices.push_back(Vector2( 0.0,0.0)) ; colors.push_back(Color(1,1,1));
	vertices.push_back(Vector2(20.0,0.0)) ; colors.push_back(Color(1,1,1));
	
	draw_primitive( vertices, colors, Vector2Array(), null, 1.0 );
````

````
# triangle <--- origin at (0,0)
	var vertices = Vector2Array();	var colors = ColorArray();
	
	vertices.push_back(Vector2( 0.0,0.0)) ; colors.push_back(Color(1,1,1));
	vertices.push_back(Vector2(20.0,0.0)) ; colors.push_back(Color(1,1,1));
	vertices.push_back(Vector2(20.0,100.0)) ; colors.push_back(Color(1,1,1));
	draw_primitive( vertices, colors, Vector2Array(), null, 1.0 );
````

````
# quad <--- origin at (0,0)
	var vertices = Vector2Array();	var colors = ColorArray();
	
	vertices.push_back(Vector2( 0.0,0.0)) ; colors.push_back(Color(1,1,1));
	vertices.push_back(Vector2(20.0,0.0)) ; colors.push_back(Color(1,1,1));
	vertices.push_back(Vector2(20.0,100.0)) ; colors.push_back(Color(1,1,1));
	draw_primitive( vertices, colors, Vector2Array(), null, 1.0 );
````

**Comment by SuperUserNameMan** [comment]
Also, on my system, the minimal offset that can be added is : y = 0.000229;

``draw_line( Vector2( 0.0, 0.000228 ), Vector2( 20.0, 0.000228 ), Color(1,1,1) );`` <--- wrong origin

``draw_line( Vector2( 0.0, 0.000229 ), Vector2( 20.0, 0.000229 ), Color(1,1,1) );`` <--- correct origin

It corrects the LINE and POINT origins, and seems to have no effect on QUAD and TRI.

If this offset works on everyone's system, this could be the workaround.

**Comment by brachna** [comment]
Did tests and offset +0.002 seems to do the trick. +0.001 was not enough in every case.
So it seems to be a rounding issue.

I'm not sure about it being the case for only LINE. That means that draw_polygon() should be free of such issues? Because I made a replacement using draw_polygon and it's old algo would produce same issues.
ie draw_poly_line(Vector(0.0, 0.0), Vector(20.0, 0.0), color, 1.0)
would make a polygon [p1(0.0, -0.5), p2(20.0, -0.5), p3(20.0, 0.5), p4(0.0, 0.5)]
and it would disappear in same cases as draw_line would.

**Comment by SuperUserNameMan** [comment]
Offset +0.002 seems okay on my system too.

``draw_polygon()`` seems not affected at all here.

**Comment by reduz** [comment]
all this code has been entirely rewritten, please test it again and report if is still happens
