### ISSUE TITLE
[3.2.4 Rc3] When I load the scene with WeakRef and InteractiveLoader, the textures are loaded in black.

### ISSUE THREAD

**Issue by oknpk** [godotengine/godot#46659]
**Godot version:** 3.2.4 Rc3 Mono

**OS/device including version:** Windows 10 / Gtx 960 / GLES2,GLES3

**Issue description:**
I also use c# thread for the loading process. (It works fine in version 3.2.4 Rc2)
![image](https://user-images.githubusercontent.com/64914195/109982722-39a69080-7d13-11eb-8cfe-3a6825547b87.png)
![image](https://user-images.githubusercontent.com/64914195/109982817-4fb45100-7d13-11eb-8ef6-89d44612ab79.png)

**Steps to reproduce:**
Press the button in the sample project.
For Weakref object - SceneLoader.cs Line: 41

**Minimal reproduction project:**
[ThreadorInteractiveLoader.zip](https://github.com/godotengine/godot/files/6084560/ThreadorInteractiveLoader.zip)

**Comment by akien-mga** [comment]
Thanks for the report and the MRP, I can confirm the regression in 3.2.4 RC 3 (works fine in 3.2.4 RC 2) on Linux.

**Comment by akien-mga** [comment]
Tested locally, I've confirmed that it's a regression from #45618, CC @RandomShaper @hpvb.

**Comment by akien-mga** [comment]
Fixed in fd5966af6490b9466fa5b2baab41afb0bbffb759, probably by #46742. (Fix will be in 3.2.4 RC 4.)
