### ISSUE TITLE
Collision detection between moving kinematic and rigid bodies is broken

### ISSUE THREAD

**Issue by e344fde6bf** [godotengine/godot#46653]
**Godot version:**
3.2.3.stable

**OS/device including version:**
N/A

**Issue description:**

Collision detection between a moving rigid body and a kinematic body that uses `move_and_collide()` will fail to detect a collision if they both move towards the same position on the same frame.  See also https://github.com/godotengine/godot/issues/46601 for collision detection between two moving kinematic bodies.

**Steps to reproduce:**

* Create a rigid body that will move towards the origin at 1 unit per a frame (vel=60 at 60Hz physics loop). Position it at `x=-60` so at the end of physics frame 60 it will be positioned at the origin.
* Create a kinematic body that is positioned next to the origin. On frame 60 use `move_and_collide()` such that it will overlap the rigid body at the origin.
* Notice that no collision is detected by the kinematic body, and the rigid body does not react to the kinematic body and ends up overlapping it.

![rigid-kinematic-collision](https://user-images.githubusercontent.com/79001820/109964646-a9c80d00-7d39-11eb-90cb-3820638a0045.png)

**Minimal reproduction project:**

[test-rigid-kinematic-collision.zip](https://github.com/godotengine/godot/files/6083647/test-rigid-kinematic-collision.zip)

**Comment by Calinou** [comment]
I can confirm this on `3.2` 08898e97a with both Bullet (MRP default) and GodotPhysics.

### Bullet

![image](https://user-images.githubusercontent.com/180032/109989707-0bbc4e80-7d09-11eb-9301-a2ee1adb9edf.png)

### GodotPhysics

![image](https://user-images.githubusercontent.com/180032/109989780-1bd42e00-7d09-11eb-93ae-e40d950d92d6.png)

**Comment by madmiraal** [comment]
Related to #30481 which is the same problem with two KinematicBodies.

**Comment by e344fde6bf** [comment]
I don't think this is a bug after all, instead it's a result of the update order of rigid bodies.

1. Rigid body positions updated
2. _physics_process() called for nodes

So rigid bodies `_physics_process()` essential operates on a 1-frame delay. So in the example provided, the kinematic body moves on frame `n` and sees no collision (because the rigid body is not there yet). The rigid body is stopped on frame `n+1` and since its position gets updated at the start of the frame before `_physics_process()` is called, that's why it ends up being stopped on the kinematic body without the kinematic body seeing a collision.

**Comment by Calinou** [comment]
@e344fde6bf If this could be better documented, feel free to point out places in the manual or class reference where this could be done :slightly_smiling_face:
