### ISSUE TITLE
Find node in project browser

### ISSUE THREAD

**Issue by vjrossi** [godotengine/godot#4668]
I'd love to have a feature where you could locate a given node from the 2D view, in the project/node tree. Sometimes a node is buried down several levels, or is otherwise time consuming to locate.

Currently a selected node is highlighted in the browser if it's already in view (in the tree) but not if it isn't. So the idea is to expand whichever nodes are necessary in the tree, and scroll the selected node into view.

Normally this would be implemented as a right-click in the 2D view, bringing up a context menu "Find in Project Window" or similar, so I'm not sure where this could fit into the current schedule.

(I haven't done any 3D stuff but I guess it would apply there as well)

**Comment by bojidar-bg** [comment]
Is this still valid on master? (just asking)

**Comment by Calinou** [comment]
This seems to be implemented as of https://github.com/godotengine/godot/commit/2e065d8ad07bb20fede0d0c0b2d33d6628033024. Selecting a node in the 2D/3D viewport will scroll to the selected node in the scene tree dock.
