### ISSUE TITLE
RayCast2D arrowhead disappears on length smaller than the arrowhead

### ISSUE THREAD

**Issue by drcucaracha** [godotengine/godot#46680]
aesthetic bug in the new raycast2d, possible solution make the tip scalable

**Godot version:**
godot 4.0 custom bd9799e9f

**OS/device including version:**
windows 7 64bits

**Issue description:**
the arrowhead of the raycast2d disappears if it is set to 5 leaving only a rectangle and if the value is increased with the mouse it appears at 6

**Steps to reproduce:**
create a 2d raycast and put a value of 5 on the Y axis

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Can you please include a screenshot of the issue?

**Comment by drcucaracha** [comment]
![02](https://user-images.githubusercontent.com/49615968/110052906-22799a00-7d37-11eb-94b6-fea89fc3ae9b.png)
![01](https://user-images.githubusercontent.com/49615968/110052908-23aac700-7d37-11eb-94cf-66f5e9de1763.png)

**Comment by Calinou** [comment]
cc @fabriceci

**Comment by fabriceci** [comment]
@Calinou @drcucaracha This is the intended behavior. The shape is composed by a line + an arrow drawn. Now that the shape has the true size of the ray, it can arrive that there is no space for the arrow. So if the ray is lower than the size of the arrow (6), it only draws the line.
