### ISSUE TITLE
Doc for Physics2DServer.area_create() should mention that the area have to be added to world

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#46696]
**Godot version:**

4de0768 / 3.2.4 rc

**Issue description:**

I was using Physics2DSever to optimise my collisions by creating areas directly from the server and encountered an issue where my areas didn't detect anything. As it turns out, you need to add the area to a physics space to have it work.

The Physics2DServer documentation is generally lacking, but the `area_create()` method description should mention that you have to call `area_set_space()` on that area to make it work properly, so that people using it won't waste time figuring out why it's broken (like me for the last hour ;_;).

**Comment by Bhu1-V** [comment]
hello, how should I update the doc either in the docs Folder of this repo or in the [@godot-docs](https://github.com/godotengine/godot-docs) repo.

**Comment by KoBeWi** [comment]
@Bhu1-V  You have to modify the XML files on this repo. See https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by Bhu1-V** [comment]
> The Physics2DServer documentation is generally lacking, but the `area_create()` method description should mention that you have to call `area_set_space()` on that area to make it work properly,

So I need to make it clear that after, Creating an Area they should assign a Space with that by `area_set_space()` to use the created area.
