### ISSUE TITLE
shadow 3d godot 3.2.4 custom

### ISSUE THREAD

**Issue by drcucaracha** [godotengine/godot#46695]
shadow 3d

**Godot version:**
godot 3.2.4 rc custom_build  8a020a657 (.8a020a657)

**OS/device including version:**
windows 7 64bit

**Issue description:**
hello in 3.2.3 the shadows are badly positioned and I thought it had been fixed for 3.2.4 but no, I don't know if it is already reported but just in case I upload the cap and test project

**Steps to reproduce:**

**Minimal reproduction project:**
[Nueva carpeta.zip](https://github.com/godotengine/godot/files/6091299/Nueva.carpeta.zip)
![01](https://user-images.githubusercontent.com/49615968/110132955-7a9db400-7daa-11eb-98eb-f0d45ae3cd30.png)

**Comment by Calinou** [comment]
Shadow biasing hasn't been improved in 3.2.4 because [implementing shadow pancaking will break backwards compatibility](https://github.com/godotengine/godot/pull/43207)
. It can be done for a future 3.2.x release, but not 3.2.4.
