### ISSUE TITLE
Auto-save does not save all edited scenes

### ISSUE THREAD

**Issue by vjrossi** [godotengine/godot#4669]
I was going to submit this as a feature request but it seems to me this behaviour is not as desired. Currently when I run my project with F5/run button, and I have "Auto save before running" checked, only the current scene is saved. Others that are currently 'dirty' remain that way. This is doubly annoying as there is currently no way to 'save all scenes' (unless I'm missing something).

**Comment by AlexHolly** [comment]
duplicate #4410?

**Comment by bojidar-bg** [comment]
@AlexHolly ~ Indeed

**Comment by vjrossi** [comment]
argh.. sorry, I did a search

**Comment by bojidar-bg** [comment]
@vjrossi ~ Don't worry, it happens once in a while anyway.
