### ISSUE TITLE
Negative Video RAM usage in debugger [3.2.4-rc3]

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#46692]
**Godot version:**

Godot 3.2.4-rc3

**OS/device including version:**

MacOSX 10.15.7 (19H2)

**Issue description:**

I use a lot of big atlases in my project. When they was in Lossless mode debugger showed me Video RAM usage about 1GB. Now I changed all atlases to Video RAM compressed mode and Video RAM usage became negative.

![Снимок экрана 2021-03-05 в 16 51 07](https://user-images.githubusercontent.com/1177068/110124442-24913680-7dd3-11eb-819c-5438c56c4129.png)

![Снимок экрана 2021-03-05 в 16 51 28](https://user-images.githubusercontent.com/1177068/110124474-2d820800-7dd3-11eb-82b5-a458c10ada4a.png)

On the graphics Video Mem and Texture Mem went to negative area.
 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Probably some overflow.
Relevant files to debug:
https://github.com/godotengine/godot/blob/f2ad10f957f7765d9733145112f5df6583b53adf/editor/script_editor_debugger.cpp#L715-L739
https://github.com/godotengine/godot/blob/f2ad10f957f7765d9733145112f5df6583b53adf/scene/debugger/script_debugger_remote.cpp#L45-L63
https://github.com/godotengine/godot/blob/f2ad10f957f7765d9733145112f5df6583b53adf/servers/register_server_types.cpp#L69-L88
and further down that rabbit hole until GLES2 and GLES3 renderers:

```
drivers/gles2/rasterizer_storage_gles2.h
372:    virtual void texture_debug_usage(List<VS::TextureInfo> *r_info);

drivers/gles3/rasterizer_storage_gles3.h
381:    virtual void texture_debug_usage(List<VS::TextureInfo> *r_info);
```

But might be good to check first if the issue can be reproduced on `master`.
