### ISSUE TITLE
Bad mouse position when releasing EditorSpinSlider

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#46708]
**Godot version:**
4.0 Master branch

**OS/device including version:**
Windows 10

**Issue description:**
When the mouse cursor reappears after dragging an EditorSpinSlider grabber, the position of the cursor is wrong.
It reappears at the exact location it was hidden despite the fact that the slider has moved.

![before](https://user-images.githubusercontent.com/3649998/110176832-38a15c00-7e04-11eb-9e91-3cc3de979fe5.gif)

**Steps to reproduce:**
Move any slider in a EditorSpinSlider (with the mouse set the rotation_degrees property of a node2d for instance)
Look at the location where the cursor reappears.

**Comment by Calinou** [comment]
Does this also occur on 3.2.3 or 3.2.4rc3?

**Comment by jmb462** [comment]
@Calinou It's a regression because in 3.2.3 and 3.2.4rc3, the mouse is not set in captured mode while dragging.

The problem happens when the mode is set back to normal mode : the cursor reapears by default at the center of the screen and the old code put it back at the previous location.

I assumed that the choice of captured mode is due to the fact that some slider as add a factor between the move relative input and the value modification. So I will be weird to keep the mouse visible while she doesn't follow the grabber.

**Comment by jmb462** [comment]
Grabber TextureRect is set at top_level.
Seems to related to #44334 as the slider acts like we never use the grabber and just drag into the text area.
