### ISSUE TITLE
Editor is not updating properly when it's not maximized

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4670]
Ubuntu Gnome / Linux ~ Godot 2.0.1 / 2.0.2 / 2.0.3 and build from source (I have tested it on all).

When the editor is not maximized changes made in the editor while running the project won't be display after a while, which is very inconvenient when using the output (for printing stuff), pressing a tab to switch to another scene won't happen after a few seconds (even with the option "update always"). There is not problem when the project it's not running.

EDIT:
Processor: Intel® Core™2 Duo CPU P8400 @ 2.26GHz × 2 
Graphics: Mobile Intel® GM45 Express Chipset
Memory: 3.8 GiB
Base Sytem: Ubuntu 15.10 64-bit

**Comment by bojidar-bg** [comment]
@EdwardAngeles ~ please include GPU and driver information as well :smile:

**Comment by akien-mga** [comment]
I'm not a GPU expert, but I guess (based on http://feedback.wildfiregames.com/report/opengl/device/Mobile%20Intel%C2%AE%20GM45%20Express%20Chipset) that your GPU has no native support of OpenGL 2.1+, but only via software rendering thanks to Mesa, which could explain why you get bad performance.

**Comment by EdwardAngeles** [comment]
Well, it seems like it only happens on my laptop, because of the drivers. So I guess I'll close this issue.
