### ISSUE TITLE
(kinda)[SOLVED] Crashes instantly on linux

### ISSUE THREAD

**Issue by Zwiebelsaft** [godotengine/godot#46700]
When I try to start godot 3.2.3 on my pc wich is running Pop OS 20.10 it instantly sends me back to the login screen and kills all applications. My hard drive should be fine and the system shouldnt be damaged. I tried launching it directly from popü shop, but I also downloaded it from the internet with no change in results.

my specs: r7 240 2gb ddr3, i3 2100, 4x2gb ddr3 1333 mhz

The pc crashed back to the login screen instantly after opening the application. Thermals of my pc are fine and non of my system components should be damaged. My pc works fine even under max load.

I will update this after further testing.

update 1: I threw a windows drive into that same pc. The 3.2.3 version of godot works for windows on that same pc

update 2: Everything just got a lot wierder. I open godot 3.2.3 from the official website and from the Pop Shop on a different mashine running the same os with any issues. On my main pc I started godot succesfully on windows. But then I also tried to start Godot via steam. (also 3.2.3 I checked) and it worked fine. So I only get this issue where my pc crashes back to the login screen when I start godot on my current installation of Pop Os 20.10 on my main pc and if it is the version from the pop shop or the official website. It doesnt have trouble launching via steam even though its the exact same version of godot

**Comment by Calinou** [comment]
Do you get a crash when running other 3D applications like Blender, 3D games and so on? This is likely a bug in the AMD graphics driver. You could try finding an updated graphics driver, but doing so on a non-LTS Ubuntu-based distribution might not be easy.

**Comment by Zwiebelsaft** [comment]
No I dont have any issues running any other application. I started minecraft just to make sure. Also this accurs directly after starting godot not after loading the project. I never saw the project selection screen in godot. I have used godot a lot on that same installation on that same computer and the same driver. The only thing that changed is the version of godot.

**Comment by akien-mga** [comment]
> The only thing that changed is the version of godot as far is I know.

What was the previous working version you had?

Is this a Godot package provided by PopOS? Can you try the official download instead? https://godotengine.org/download/

**Comment by Zwiebelsaft** [comment]
I have tried the official download already with the same result. I havent used godot in a while so the last working version is 3.2.1

**Comment by akien-mga** [comment]
Did you retry 3.2.1 on your current system? I'd like to make sure if there's a regression in Godot or something broke in your system.

**Comment by Zwiebelsaft** [comment]
i tried 3.2.1 on my system. I got exactly the same crash as with 3.2.3 even though I know 3.2.1 should work. On my windows drive I didnt have any problems and on the other ciomputer also running Pop OS 20.10 I didnt have any issues. The only common denominator is my linux install. I might have a slightly damaged hard drive. I will use the "repair filesystem" feature of my disks application and then try to repair my linux install or reinstall linux competely. I will then try to start godot.

**Comment by Zwiebelsaft** [comment]
My hard drive and my install of linux are fine. When I tried to start godot on the live usb I got the same crash back to login screen. I dont know anymore but starting it via steam seems to work so Im just gonna dot that

**Comment by akien-mga** [comment]
> I dont know anymore but starting it via steam seems to work so Im just gonna dot that

That means there's something in your local config which triggers a crash, either in `~/.local/share/godot`, `~/.config/godot` or `~/.cache/godot`.

Deleting them to force recreating your config should fix the issue. However it would be useful to try to narrow down what file actually triggers the issue so that we can fix it, so you could rename them one after the other, testing Godot in between, to see which folder is problematic. If it's `~/.config/godot/`, it might be related to something in your `editor_settings-3.tres` for example.

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
