### ISSUE TITLE
forum registration : waiting for admin approval after 2 captcha is slightly too much

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4671]
**Operating system or device - Godot version:**
http://godotdevelopers.org

**Issue description** (what happened, and what was expected):

Since identifiers from the ancient forum have not been migrated to this new one, I had to register again.

I understand that bots and spammers are plaguing the net, but i find that having to wait for admin approval after filling 2 captcha is slightly too much :-/

I only wanted to post some screenshots and share my enthusiasm. And now i'm all frustrated :-(((( 

**Steps to reproduce:**
- goto godotdevelopers.org and click on register
- dig your brain to find a username that please you
- invent a password that is both hard to guess and easy to remember
- select which of your email address you want to expose
- fill a first captch to prove you're not a bot
- once you proved you're not a bot, fill a second captcha to prove you're still not a bot
- validate
- goto your email-box and wait for the confirmation mail
- discover the confirmation mail is not a "click to confirm" mail but just a notification that you'll have to wait for admin approval
- go back to the forum and login
- discover you can't login till it is approved by admin
- goto IRC and complain about how frustrated you are
- goto bed and sleep
- come back to the forum the next afternoon
- discover you are still waiting for admin approval
- discover your enthusiasm is changed into frustration 

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
See that with the admins of godotdevelopers.org directly, it's managed independently.

**Comment by SuperUserNameMan** [comment]
damn, many things have changed since last year :-/
i guess i'll have to wait a little bit more, 'cause i found no contact link or form into their forum.

**Comment by kubecz3k** [comment]
I'm archiving this issue since it's related to community effort forum which is not maintained by us.

**Comment by akien-mga** [comment]
I reported it on GodotDevelopers in the private moderation board, proposing to disable the manual account validation for now, and see how it goes spam-wise. We enabled it after a huge spam attack, but at that time the captchas were also weaker IIRC.
