### ISSUE TITLE
HTML5 HTTPClient.request() sends always the "OPTIONS" Method

### ISSUE THREAD

**Issue by db0** [godotengine/godot#46716]
**Godot version:**

3.2.3 Stable official

**OS/device including version:**

Windows 10

**Issue description:**

When exporting to HTML5, `HTTPClient.request()` always sends an "OPTIONS" request instead of GET, POST, PUT etc.

**Minimal reproduction project:**

[method_options_html5.zip](https://github.com/godotengine/godot/files/6095342/method_options_html5.zip)

*EDIT: I've adjusted the project to print some info as well.*

It's not possible to test this in isolation as you need a web server to accept the request. I have created one small such server which can be used in combination with this minimal project

https://github.com/db0/CGF-Stats

simply clone it and run it with `python cgf-stats.py "Test"`

When runnig the project from the editor, you will see normal POST requests after pressing the button. Exporting to HTML however will always return OPTIONS

```
$ python cgf-stats.py "Test"
 * Serving Flask app "cgf-stats" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 303-146-213
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Mar/2021 05:08:28] "POST /newgame/ HTTP/1.1" 201 -
127.0.0.1 - - [06/Mar/2021 05:11:23] "POST /newgame/ HTTP/1.1" 201 -
127.0.0.1 - - [06/Mar/2021 05:12:06] "OPTIONS /newgame/ HTTP/1.1" 405 -
```

**Comment by db0** [comment]
BTW, The backend is already sending `Access-Control-Allow-Origin: *` to handle CORS.

```
TP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Allow: POST, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Max-Age: 21600
Content-Length: 0
Server: Werkzeug/1.0.1 Python/3.8.6
Date: Sat, 06 Mar 2021 12:43:43 GMT
```

**Comment by Faless** [comment]
The `OPTIONS` request is automatically done by the browser, as a [CORS pre-flight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request).
We have no control over it. It's something that servers need to take care of.
