### ISSUE TITLE
starting to learn godot cant edit sprite animation... can anybody help me

### ISSUE THREAD

**Issue by mechheiser** [godotengine/godot#46718]
![image](https://user-images.githubusercontent.com/80150120/110201007-e14eca80-7e9b-11eb-9e0d-c306e820dfe8.png)

begginer problem dont know how to use github properly

**Comment by Zireael07** [comment]
This is not a place to request help with Godot. You have the Discord or the forums for that.

**Comment by mechheiser** [comment]
what discord

**Comment by clayjohn** [comment]
If you need help working with the engine please ask your question on one of the Community Channels (reddit, discord, or the Q&A are likely the best places to ask)

Links here https://docs.godotengine.org/en/stable/community/channels.html

**Comment by Calinou** [comment]
As for the issue of menus sliding off-screen, this is a known bug: https://github.com/godotengine/godot/issues/31133
