### ISSUE TITLE
Make it possible to inspect and preview the whole scene while the game is running

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#4672]
As discussed briefly on IRC by @reduz, @eska014 and me:

**\<bojidar_bg\>** reduz: also, another question, are there plans to allow developers to see the full scene tree and preview of a running (though maybe paused) game through the editor?
**\<eska\>** bojidar_bg, you can already see the scene tree in debuffer-\>info
**\<eska\>** debugger I mean
**\<bojidar_bg\>** it is terrifying to go through the debugger
**\<eska\>** bojidar_bg, it's just a tab, click the reload button once and you get the whole tree
**\<bojidar_bg\>** eska: does it allow for property value observance?
**\<eska\>** no
**\<bojidar_bg\>** well, that's one thing, the other is running editor plugins on it
**\<bojidar_bg\>** and looking outside the reaches of the camera..
**\<reduz\>** bojidar_bg, it should allow that
**\<reduz\>** never made it, but i guess it should be done
**\<bojidar_bg\>** reduz: would you like an issue about it?
**\<reduz\>** sure
**\<reduz\>** I was thinking of moving that to the backtrace debug screen, so besides properties you can see the tree and properties of nodes/resources
**\<bojidar_bg\>** reduz: I think that putting it into the debugger will make it harder to see, and I would personally prefer to run it fullscreen as a tab
**\<reduz\>** fullscreen?
**\<bojidar_bg\>** reduz: as if it was another scene

**Comment by kubecz3k** [comment]
@bojidar-bg I have feeling that this is in general implemented in in current build,  or is it lacking some feature?

**Comment by bojidar-bg** [comment]
Well, the only part left is drawing the scene in the editor (maybe without custom `_draw` scripts, unless they are `tool`)

**Comment by vinod8990** [comment]
Is the question similar to the one called "Frame debugger" in Unity?

**Comment by reduz** [comment]
this was implemented already. Drawing the running game in the editor is impossible, given the game is a separate process, so closing

**Comment by neikeq** [comment]
I was expecting that answer. My idea is to do it in the game itself. I first proposed modularizing some editors like CanvasItemEditor so they can work without the editor, but as you mentioned it would be really hard. Maybe this could be done with the plugin API.

**Comment by reduz** [comment]
You mean making some sort of mini editor where the game runs?

**Comment by neikeq** [comment]
No, I mean making mini editors (like the scene tree editor and the canvas item editor) that run in the game :P
