### ISSUE TITLE
A node instanced as a child of a foreign node doesn't get saved after Editable Children is unchecked.

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#46726]
**Godot version:**

f477d3ca9851953ded5f0560081d726f5de9b534, master (8faecd6a470aeef41084a32d74f4a131a5ef42b6)

**OS/device including version:**

Windows 7 SP1

**Issue description:**

After unchecking "Editable Children" i expected a node added as a child of a foreign node to either
- survive saving and reopening a scene
- be removed when "Editable Children" becomes unchecked.

Since users really don't like loosing their work it's probably better to go with the first option.

**Steps to reproduce:**
1. Disable Editable Children of "Node2D"

2. Click on Godot logo

3. "Sprite" will get selected and will be editable in the inspector while not visible in Scene dock

4. Save the scene and reopen it. "Sprite" node will be gone.

**Minimal reproduction project:**

https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/EngineIssues/ChildrenOfForeignNodes_godot32
https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/EngineIssues/ChildrenOfForeignNodes_godot40
and open SelectSprite.tscn

**Comment by KoBeWi** [comment]
Sounds related to #45915
