### ISSUE TITLE
Custom boot splash image scaling wrong on Android

### ISSUE THREAD

**Issue by fractilegames** [godotengine/godot#46723]
**Godot version:**
3.2.4rc3

**OS/device including version:**
Samsung Galaxy S8, Android 9

**Issue description:**
With window size in project settings set to 1280x720 and using a custom boot splash image of the same size, only the middle 1/4 of the image is shown on Android:

![Screenshot_20210306-120953_Polychoron](https://user-images.githubusercontent.com/2310335/110203334-47c0f200-7e76-11eb-9a35-92deaf8b08d1.jpg)

Changing Boot splash / full size -project setting does not change anything.

**Comment by Calinou** [comment]
This is likely due to DPI scaling. Does this occur if you resize the splash image to 640×360?

**Comment by fractilegames** [comment]
You're right. After resizing the image to 640x360 it shows up in correct size and position:
![Screenshot_20210306-171309_Polychoron](https://user-images.githubusercontent.com/2310335/110211538-9fc01e80-7e9f-11eb-82b6-b531d695c679.jpg)

**Comment by AlexHCC** [comment]
I do have the same scaling issue with a high resolution image in a 720p phone screen. It is inconsistent with how it works on other platforms, and how it worked in previous versions (3.2.3). 
Another maybe related inconsistency Is that the screen fades to black before starting the main scene. It is more apparent if you set the Bg Color to white. Again this does not happen in other platforms neither did it in previous versions (3.2.3), on the same device.

**Comment by Calinou** [comment]
> Another maybe related inconsistency Is that the screen fades to black before starting the main scene. It is more apparent if you set the Bg Color to white. Again this does not happen in other platforms neither did it in previous versions (3.2.3), on the same device.

This is probably related to the Android porting rework that happened between 3.2.3 and 3.2.4. Can you test this in [all 3.2.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.2.4/)?

**Comment by fractilegames** [comment]
The problem is present in both 3.2.4rc1 and 3.2.4beta1.

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by AlexHCC** [comment]
I have tested the versions and recorded my results. I have used a 1000x1000 custom godot logo on a 720p phone screen (android). [Here](https://github.com/godotengine/godot/files/6136607/project.zip) is the project I used.
In beta1-rc2 there is a scaled up version of the image before the correct one is shown. In rc3-rc5 the scaled up version remains but the correct one is replaced by a fade to a black screen.


https://user-images.githubusercontent.com/28542484/111067083-19bd5c80-84cb-11eb-82ad-9bbdfaa67e22.mp4

https://user-images.githubusercontent.com/28542484/111067084-1aee8980-84cb-11eb-81a9-afe0a5fb880d.mp4

https://user-images.githubusercontent.com/28542484/111067085-1c1fb680-84cb-11eb-8194-a5dfb9a37d51.mp4

**Comment by akien-mga** [comment]
CC @godotengine/android

**Comment by m4gr3d** [comment]
@fractilegames @AlexHCC The changes you are observing are intended and were done in PR #46168  in order to address issue #43726.

As mentioned in PR #46168, the use of the Android theme api introduces a couple of limitations, proper scaling being one of them.

Let me know if you have further questions on the current implementation.

**Comment by fractilegames** [comment]
That PR says "One limitation of the Android api being used is that the splash screen aspect ratio is not maintained when it's scaled up". This isn't just about aspect ratio, the image is scaled 2x too big on Android.

**Comment by m4gr3d** [comment]
@fractilegames Thanks for the update, I'll take a look.

**Comment by hani09876** [comment]
> @fractilegames Thanks for the update, I'll take a look.

The boot splash still has the same problem on godot 3.4.4... my splash image is scaling down. I am using a image same as my window size... Will it be fixe in feature?

**Comment by Calinou** [comment]
> The boot splash still has the same problem on godot 3.4.4... my splash image is scaling down. I am using a image same as my window size... Will it be fixe in feature?

This is already being tracked in https://github.com/godotengine/godot/issues/49816.
