### ISSUE TITLE
Path2D Bug (Editor bug)

### ISSUE THREAD

**Issue by CyberMole-Dev** [godotengine/godot#46734]
Hi, I' working with Godot 3.2.3 Stable on my Windows PC (Windows 10).

I noticed that when I create a Path2D, with a PathFollow2D and a RemoteTransform2D, my editor becomes bigger than the actual window and it goes out of the borders, so I cant click some buttons on the right of the screen.

It also says this error: "Cannot get ratio when minimum and maximum value are equal."

I'm following this tutorial and every time is always the same story, thanks in advance.

https://youtu.be/2ykdYUA40Ds

**Comment by Calinou** [comment]
> I noticed that when I create a Path2D, with a PathFollow2D and a RemoteTransform2D, my editor becomes bigger than the actual window and it goes out of the borders, so I cant click some buttons on the right of the screen.

This is a known bug: https://github.com/godotengine/godot/issues/31133

> It also says this error: "Cannot get ratio when minimum and maximum value are equal."

This was fixed in 3.2.4rc2 and later by https://github.com/godotengine/godot/pull/45220.

**Comment by CyberMole-Dev** [comment]
I tried to follow the workarounds and I also installed the 3.2.4rc-3
version of Godot but the bug still appears. What should I do in this case?

Il sab 6 mar 2021, 21:44 Hugo Locurcio <notifications@github.com> ha
scritto:

**Comment by Calinou** [comment]
> I tried to follow the workarounds and I also installed the 3.2.4rc-3
version of Godot but the bug still appears.

Which bug are you referring to? The editor docks going off-screen or the ratio error message?
If you're using a 1366×768 display, you really need to set the editor scale to 75% to be able to use Godot in any productive manner. Otherwise, there's just not enough screen real estate to work with. This should be done automatically in 3.2.4rc now, but maybe it's not working on your end.

**Comment by CyberMole-Dev** [comment]
Well, I'm working on 1366x767 ratio, the only solution it's to set 75%
display size.
Anyway that's not a big problem so it's ok.
Thanks for all.

Il dom 7 mar 2021, 13:32 Hugo Locurcio <notifications@github.com> ha
scritto:
