### ISSUE TITLE
SceneTree tab does not immediately reflect undo action

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#46747]
**Godot version:**
3.2.4 RC2, RC3

**OS/device including version:**
macOS Big Sur
M1 Mac Mini

**Issue description:**
After some undo actions, such as undoing moving or deleting nodes, the SceneTree tab does not visually reflect the undo until the user clicks somewhere inside the tree tab. Other actions, such as undoing an "add new node" or renaming a node, still work normally.

Bug is present in 3.2.4 RC2 and RC3, but _not_ present in RC1. So RC2 introduced the regression.

**Steps to reproduce:**
Add some nodes into the scene, move or delete them, then undo the action.

**Comment by snougo** [comment]
can't reproduce the issue on a non-M1 MBP with MacOS 10.14.6

**Comment by djrain** [comment]
My mistake, I got RC2 and 3 mixed up in my testing - it's been fixed somehow in RC3. Closing this then :)
