### ISSUE TITLE
Opening/Closing scenes with Animated Sprite causes the SpriteFrames editor panel to display wrong Animations and Animation Frames

### ISSUE THREAD

**Issue by aaronsham** [godotengine/godot#46741]
**Godot version:**

3.2.3 stable (mono)

**OS/device including version:**

Windows 7 x64

**Issue description:**

Viewing an Animated Sprite's SpriteFrames, closing a scene and re-opening another scene with an Animated Sprite shows the incorrect scene's animations in the SpriteFrames' Animation and Animation Frames panel, and causes loss of functionality until corrected.

**Steps to reproduce:**
**Prep:**
1. Create a Node2D Scene, attach an AnimatedSprite as child. Create SpriteFrames, and add a new animation, call it something distinguishable, ie. "ANIMATION_A". _Optional, but helps to demo: add any random graphic to this animation._ Save this scene as "abc123". Make sure the AnimatedSprite node is selected.
2. Repeat the above step, but use "ANIMATION_B" instead of "ANIMATION_A", and add a different graphic (or use none). Save this scene as "def234". Make sure the AnimatedSprite node is selected.
3. Your scene tabs should be as follows: [abc123, def234 (current)], both with their AnimatedSprite node selected to make the SpriteFrame Animation/Animation Frames panel in the editor visible.

**Reproduction**
Close def234, then close abc123. Re-open def234, then select the AnimatedSprite node. The displayed animation in the Animation and AnimationFrames panel will be of abc123, not def234. Also, all buttons in the Animation and Animation Frame panels do not respond, except for "New Animation" and "Add Frames from a Sprite Sheet" respectively.

**Current workarounds**
There are two ways I've found to "correct" this behavior in the editor. One such way is to open abc123 again, select its AnimatedSprite node, then switching back to def234. Another is to use the aforementioned buttons and either create a new animation, or the spritesheet button and add a frame to the animation (no frame is actually added?). The editor then correctly displays the correct animations.

https://user-images.githubusercontent.com/67756278/110222308-22d47b00-7e86-11eb-99a6-1f7875e950b1.mp4

**Comment by KoBeWi** [comment]
Fixed in 56d7126
But valid in 3.3.2

**Comment by akien-mga** [comment]
Fixed by #49495.
