### ISSUE TITLE
Field to search for nodes in scene tree is case sensitive

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#4674]
**Operating system or device - Godot version:**
Windows 10 64bit, Godot from github

**Issue description** (what happened, and what was expected):
In new "Contextualized Scene Tree menu" field to search for nods use only case sensitive.

**Steps to reproduce:**
In my tree have node with name "AS".
1. In field "search for nods use" type "as".
2. Not find anything.
3. Type "AS".
4. Node is find.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Should be easy to fix, we just need to ensure to compare lowercased Strings for both the input string and the node names.
