### ISSUE TITLE
Godot don't work with non-English layout of keyboard on Linux

### ISSUE THREAD

**Issue by FallenNephalem** [godotengine/godot#46750]
**Godot version: 3.2.3 stable release**

**OS/device including version: Linux Mint 18.3**

**Issue description: I have 2 layout on my laptop (English and Russian for me) and when i change it to non-English layout happends:
1) Hotkey is not working
2) When i run the project and trying to catch action by _if Input.is_action_pressed("ui_right")_ it doesn't work
3) When i try see scancode of character, i see 0 for all keys, if it not a special key (like "shift", "control", "tab" and etc.)**

**Steps to reproduce: For reproduce this bug you can try to catch any action or InputEventKey and see it (of course, you need to do it on linux)**

**Minimal reproduction project:*[game.zip](https://github.com/godotengine/godot/files/6096826/game.zip)*

**Comment by JapanYoshi** [comment]
Your minimal reproduction project doesn't have a Godot project file, but I can confirm that this issue does NOT occur on Windows.

This is the result of pressing the "Й" key on the ЙЦУКЕН Russian keyboard layout (which is where the "Q" is on QWERTY):
![image](https://user-images.githubusercontent.com/8707990/110236234-0153bc00-7f78-11eb-8d92-f199c92c6a66.png)

Here is the minimal reproduction project I used for this:
[Test.zip](https://github.com/godotengine/godot/files/6096913/Test.zip)

**Comment by bruvzg** [comment]
In the `master`, it should be fixed by #18020 (by falling back to the physical code if remapping failed). I had encountered a similar issue while testing it on different Linux VMs (not sure what exactly is causing it, on most distros non-Latin scan codes work fine).

**Comment by madmiraal** [comment]
Fixed on master with #18020 and on 3.x with #46764.
