### ISSUE TITLE
8bitdo dpad problem.

### ISSUE THREAD

**Issue by blastermaster77** [godotengine/godot#46766]
**Godot version:**
3.2.3

**OS/device including version:**

Manjaro Linux, gtx 1060, 460.39 

**Issue description:**

Problem with dpad with 8bitdo SN30+ controller, it gets left and right stuck when pressing fast.

**Steps to reproduce:**
press left and right on dpad really fast and it inputs both at the same time, this does not happens with my xboxone controller.

Also this does not happens with retroarch and other games. 

https://user-images.githubusercontent.com/9307070/110248264-93db6780-7f46-11eb-9cbd-88553f2a5c8b.mov

**Comment by Calinou** [comment]
Can you test this on [3.2.4rc3](https://godotengine.org/article/release-candidate-godot-3-2-4-rc-3)?

**Comment by blastermaster77** [comment]
> @blastermaster77 Can you test this on [3.2.4rc3](https://godotengine.org/article/release-candidate-godot-3-2-4-rc-3)?

yes! tested it works now with the rc3 thanks to all for the hard work! 

https://user-images.githubusercontent.com/9307070/110254734-bc735980-7f66-11eb-9fa7-2e43fff1b78a.mov

**Comment by akien-mga** [comment]
Great, closing as fixed then :)
