### ISSUE TITLE
ScrollBar page can be higher than max_value, which results in oversized grabber

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#46778]
**Godot version:**

3.2.4 rc3 / 7739db3

**Steps to reproduce:**
1. Add H/VScrollBar node
2. Set `page` to value greater than `max_value`
3. 
![image](https://user-images.githubusercontent.com/2223172/110259796-d5e9c500-7fa9-11eb-927e-acf85159aac5.png)

Setting `page` or `max_value` should validate to make sure `page` is no bigger than `max_value`.

**Comment by Hassan-A** [comment]
So if we change the `page` to a number higher than `max_value`, should the `max_value` be adjusted to match the `page` or should the `page` value be adjusted to match `max_value`. The latter is what happens to `value` when you try to change it above `max_value`.

**Comment by likeich** [comment]
Adjusting the max value automatically would be unexpected behavior to most users I'd think. It's probably be best to use max value instead and perhaps throw a warning as well.

**Comment by Bhu1-V** [comment]
https://github.com/godotengine/godot/blob/d52974ba953ff01b3f8199977fbc582f5bcc843e/scene/gui/range.cpp#L103-L117

And also see we can update min-value to be greater than max-value 

if we are solving the main issue we should also try to check this also and some questions.

1. Anybody have any idea on `shared` in the above code.
2. while setting min and max it called `set_value()` but it only updates while setting minimum...??

**Comment by jmb462** [comment]
As it affects the Range class, is there no case that we want to be able to overpass the max_value ?
It seems that SpinBox needs to be able to due that (allow_greater property)

So modification maybe should be done in HSlider & VSlider derived class.

**Comment by likeich** [comment]
If you look at the header file for range you can see that "shared" is a struct that holds all the data for the range.

![Screenshot from 2021-03-08 07-37-06](https://user-images.githubusercontent.com/57882701/110322458-26c8e000-7fe1-11eb-94c7-4855664cde04.png)

I think it's best that if you try to set the min greater than the max or the max less than the min that Godot should throw a warning and say that it set itself back to whatever the other number is. 

For example: max = 100 and we try to set min to 101, godot sets the min to 100 and says in the debug console something like "The ScrollBar minimum value cannot be larger than the max value, setting the minimum to 100."

A very similar warning would be thrown if the page is set to larger than the max value.

**Comment by KoBeWi** [comment]
I think the warnings are not necessary.

**Comment by Bhu1-V** [comment]
> 2\. while setting min and max it called `set_value()` but it only updates while setting minimum...??

Yep warnings are overkill but what about my 2nd question...

**Comment by likeich** [comment]
The only warning is a min_value warning:
![Screenshot from 2021-03-08 08-30-37](https://user-images.githubusercontent.com/57882701/110327918-9c847a00-7fe8-11eb-9226-6fe20db18fe0.png)

I've fixed the page issue on my own branch by clamping the page value to the min and max values. For the set_min/max issue should I just limit each value to the other? I.e. max can't be less than min and min can't be less than max.

Leaving the warnings out.

**Comment by Hassan-A** [comment]
@Bhu1-V What values are you using because `value `will only update say if you change the `max_value `lower than the `value`.

**Comment by likeich** [comment]
@Hassan-A Allow_greater/lesser only deals with the value, not the page. All I've done is prevent the max/min values from overlapping each other and preventing page from being outside the range of min-max.

**Comment by Bhu1-V** [comment]
@likeich  can I see your code for setting min and max values..?

**Comment by Bhu1-V** [comment]
so I made some changes and found that page can have maximum value of `shared->max-shared->min` to not get outside of the boundaries.
```
void Range::set_min(double p_min) {
	if (p_min < shared->max) {
		shared->min = p_min;
	}
	set_value(shared->val);

	shared->emit_changed("min");

	update_configuration_warning();
}

void Range::set_max(double p_max) {
	if (p_max > shared->min) {
		shared->max = p_max;
	}
	set_value(shared->val);

	shared->emit_changed("max");
}

void Range::set_page(double p_page) {
	if ( p_page <= (shared->max - shared->min)) { 
		shared->page = p_page;
	} else {
		shared->page = (shared->max - shared->min); 
	}
	set_value(shared->val);

	shared->emit_changed("page");
}

```

and also turning on `allow_greater` only gives small amount of control area at max value....
![ScrollBar](https://user-images.githubusercontent.com/70578657/110344368-69c39b80-8053-11eb-8d67-e5a8c1be27c3.gif)
