### ISSUE TITLE
Some PopupMenus have incorrect size on first opening

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#46779]
**Godot version:**
7739db3

**Issue description:**
Some popups don't start with their correct size on first opening, this can be seen when right-clicking the search lines on the project manager:
![Screenshot_20210307_232626](https://user-images.githubusercontent.com/30739239/110266574-fc156200-7fb5-11eb-83e4-8865cb47df4e.png)

I trying reverting some recent changes done in the `PopupMenu` (both mine and Eric's) to see if they introduced the regression, but found nothing.

CC @EricEzaM

**Comment by HaSa1002** [comment]
I saw this behaviour while trying to fix the focus. I implemented something and the error disappeared...

**Comment by YeldhamDev** [comment]
I've noticed that this only happens if the editor font's size is smaller than the default one. Which probably means that the popups aren't getting an updated font size on their first opening.
