### ISSUE TITLE
Parent does not reflect changes in children

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#4677]
**Godot Version:** 
![](https://i.imgur.com/BNC2WNQ.png)

Currently when you make changes to the children of Panel Container (**NB**: This also applies to other nodes that make changes to children, but for sake of this post I will use PanelContainer as an example) the parent does not adjust unless I make any changes inside it after making changes in a child.

**Scene Tree:**
![](https://i.imgur.com/3d7p2Vs.png)

**Before making changes to child**
![](https://i.imgur.com/CkmrTOa.png)

**After making changes to child**
![](https://i.imgur.com/brhkRZV.png)

As you can see, the parent do not wrap the children as it is set to do.
![](https://i.imgur.com/KirLrNa.png)

However if I just click inside one of the parents' margin, and press enter;
![](https://i.imgur.com/15dJq8x.png)

It changes to the way it _should_ have been after making these changes to child.
![](https://i.imgur.com/wqfZiur.png)

While this is not anything "serious", it would be nice to have it looked at - and adjusted so that It do as expected :)

**Comment by reduz** [comment]
This was actually a bug in GridContainer not letting the parent know that it's minumum size may have changed when the cells property changed.

**Comment by Tybobobo** [comment]
Neat, glad to see this is fixed :) :+1:
