### ISSUE TITLE
Uniforms in shaderGraph shader doesn't show until editor is restarted.

### ISSUE THREAD

**Issue by henkz1** [godotengine/godot#4678]
**Operating system or device - Godot version:**
Ubuntu 16.04, master https://github.com/godotengine/godot/commit/a0dd7ec171001f9b9a14bafc0c9ed12623908984

**Issue description** (what happened, and what was expected):
Adding a uniform to shaderGraph it won't show in the inspector until editor is restarted.

**Steps to reproduce:**
* create a shaderGraph shader
* add a texture uniform(or any uniform)
* navigate back to the material, you won't find any param for the uniform until you restart godot

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
@MarianoGnu
