### ISSUE TITLE
Android build on Windows gives cryptographic error

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#46790]
**Godot version:**
Current 3.2 branch (6b48fce2b54af26cc8e640129d8b93823f53226f) and master branch (26d1b30d35d0897e18e4bc9521c1833eb1bdcf0c)

**OS/device including version:**
Windows 10 but compiling for Android
Latest Windows patches installed
Android Studio 4.1.2 fully updated
Visual Studio 2019 fully updated (if even applicable here)

**Issue description:**
Compiling fails with the following error:
```
scons: Reading SConscript files ...
Checking for Android NDK...
Building for Android, platform android-24 (arm64v8)
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[  1%] Compiling shared ==> platform\android\os_android.cpp
=====
b'LLVM ERROR: Could not acquire a cryptographic context: Provider DLL failed to initialize correctly.  (0x8009001D)\r\nStack dump:\r\n0.\tProgram arguments: C:\\Development\\Android\\Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -o platform\\android\\os_android.os -c -std=gnu++17 -frtti -O2 -fomit-frame-pointer -ftree-vectorize -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -fvisibility=hidden -fno-strict-aliasing -mfix-cortex-a53-835769 -target aarch64-none-linux-android -fno-integrated-as -gcc-toolchain C:\\Development\\Android\\Sdk/ndk/21.4.7075529/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 -Wall -Werror=return-type -isystem C:\\Development\\Android\\Sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include -isystem C:\\Development\\Android\\Sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++abi/include --sysroot=C:\\Development\\Android\\Sdk/ndk/21.4.7075529/sysroot -isystem C:\\Development\\Android\\Sdk/ndk/21.4.7075529/sysroot/usr/include/aarch64-linux-android -isystem C:\\Development\\Android\\Sdk/ndk/21.4.7075529/sources/android/support/include -DNDEBUG -D__ANDROID_API__=24 -DNO_STATVFS -DGLES_ENABLED -D__ARM_ARCH_8A__ -DANDROID_ENABLED -DUNIX_ENABLED -DVULKAN_ENABLED -DNO_FCNTL -DNDEBUG -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -Ithirdparty\\freetype\\include -Ithirdparty\\libpng -IC:\\Development\\Android\\Sdk\\ndk\\21.4.7075529\\sources\\third_party\\vulkan\\src -IC:\\Development\\Android\\Sdk\\ndk\\21.4.7075529\\sources\\third_party\\vulkan\\src\\include -IC:\\Development\\Android\\Sdk\\ndk\\21.4.7075529\\sources\\third_party\\vulkan\\src\\layers -IC:\\Development\\Android\\Sdk\\ndk\\21.4.7075529\\sources\\third_party\\vulkan\\src\\layers\\generated -Ithirdparty\\zstd -Ithirdparty\\zlib -Iplatform\\android -I. platform\\android\\os_android.cpp \r\n1.\tCompilation construction\r\n2.\tBuilding compilation jobs\r\n3.\tBuilding compilation jobs\r\n4.\tBuilding compilation jobs\r\n5.\tComputing output path\r\n'
=====
scons: *** [platform\android\os_android.os] Error 1
scons: building terminated because of errors.
```
(log from master, but same error happens on 3.2)

**Steps to reproduce:**
Compile for Android using Windows.

**Minimal reproduction project:**
n/a

**Comment by BastiaanOlij** [comment]
@m4gr3d any ideas what might be happening here? This looks like a recent change, I was able to compile master before I pulled the latest changes (If I read reflog correctly I think commit bd9799e9f0a9a9c7d0dd22d5f3f520f450520caf)

**Comment by akien-mga** [comment]
> This looks like a recent change, I was able to compile master before I pulled the latest changes (If I read reflog correctly I think commit bd9799e)

Hm that's pretty recent indeed, more recent than the latest Android buildsystem changes. That would be weird but worth checking if 5d217a94414117438d92b094956baead8ec942fb did not cause the issue (merged yesterday).

**Comment by BastiaanOlij** [comment]
@akien-mga I'm sorry to be the bearer of bad news but yes, that commit broke it. I don't get it though, it looks like a fine change. Unless if it breaks if TERM does not exists. In the old one it checks for that, in the new one it sets the whole structure regardless.

**Comment by BastiaanOlij** [comment]
@akien-mga I'm guessing that AppendEnvPath appends the path to what is already there, while the new solution overwrites what is already there breaking things?
