### ISSUE TITLE
ShaderGraph shader turns black after save

### ISSUE THREAD

**Issue by henkz1** [godotengine/godot#4679]
**Operating system or device - Godot version:**
Ubuntu 16.04, master https://github.com/godotengine/godot/commit/a0dd7ec171001f9b9a14bafc0c9ed12623908984

**Issue description** (what happened, and what was expected):
ShaderGraph shader display as expected until you save the scene, then they go black.

**Steps to reproduce:**
* add a quad
* create a new shader material for material override
* create a new shaderGraph shader
* add a texture uniform, connect uv and connect rgb to diffuse, you should see your texture
* save the scene, now the quad turns black

**Link to minimal example project** (optional but very welcome):

**Comment by MarianoGnu** [comment]
I realized this too...

**Comment by EdwardAngeles** [comment]
It happens to me too, although if I run the game the shader has effect in the game, to see it in the editor I have to reopen the editor :(

**Comment by MarianoGnu** [comment]
Fixed in #5308
