### ISSUE TITLE
Godot Shell...

### ISSUE THREAD

**Issue by gerardogc2378** [godotengine/godot#4680]
Hi, is there a godot shell to execute gdscripts and see behaviours or outputs? A example for this could be working with math part, vectors, random, strings, arrays or any others.

**Comment by reduz** [comment]
there is no line by line interpreter, but you can try running scripts with
godot -s
as long as the scripts inherit from SceneTree it should all be good

like:

extends SceneTree


void _initialize():

     print("hello")
     quit()

**Comment by gerardogc2378** [comment]
Ok thanks now I'll try this
