### ISSUE TITLE
Node types don't update when scene(.tscn) file is updated

### ISSUE THREAD

**Issue by BrandonCardoso** [godotengine/godot#46803]
**Godot version:**
v3.2.3.stable.official

**Issue description:**
When updating a scene file (ex. switching branches on git) where the type of a node is changed, the editor does not refresh the scene node tree, so the type is incorrectly set until the project is closed and reopened. The scripts files are automatically reloaded, so you reach a state where the type the node extends in the script does not match the type of the node in the scene tree.

**Steps to reproduce:**
I experienced the issue when switching between branches where I refactored a node from KinematicBody to RigidBody.

You can also reproduce just by editing a scene file in an external editor (notepad) and changing the type of a node.

**Comment by KoBeWi** [comment]
This is fixed in 3.2.4.
