### ISSUE TITLE
Unchecked malloc return NULL vulnerability 

### ISSUE THREAD

**Issue by vulnerabilitydetectionlearning** [godotengine/godot#46807]
**Issue description:**
Found two Unchecked malloc return NULL vulnerabilities in Godot repository.

The two vulnerabilities are in these files:
https://github.com/godotengine/godot/blob/b9aa2d0dfb5ec6e93e1dc3604fba92606c1a2398/modules/xatlas_unwrap/register_types.cpp#L163-L175
https://github.com/godotengine/godot/blob/5525cd85c60455b0bb9716bbef0ad2ad8111d752/modules/mono/mono_gd/support/android_support.cpp#L637-L641

Both vulnerabilities can potential occur when malloc cannot successfully allocate memory, it would instead return a null pointer which has unexpected behaviors when operated on. See this for more detail about this type of vulnerability https://cwe.mitre.org/data/definitions/690.html

**Comment by vulnerabilitydetectionlearning** [comment]
@Ev1lbl0w Hi! Thanks for taking a look at this and fixing it. This vulnerability was detected by our deep learning based vulnerability detection model. Along with the detection, our model also localizes the vulnerability by producing a version of the function with code that contributed to the vulnerability highlighted. We provide the localization output of the vulnerable function identified in this Issue. The intensity of the highlight correspond to how important the code snippet was for vulnerability detection in this function. 
<p align="center">
<img src="https://user-images.githubusercontent.com/79933146/111919657-77205300-8a61-11eb-88d1-07cffc6b653f.png">
</p>
<p align = "center"> android_support.cpp </p>

<p align="center">
<img src="https://user-images.githubusercontent.com/79933146/111919697-b189f000-8a61-11eb-9111-841ed46524f8.png">
</p>
<p align = "center"> register_types.cpp </p>

As part of our university research project we would like to evaluate the usefulness of the model’s localization outputs. You can help us out by clicking one of the options below:

- This vulnerability is a **real** vulnerability and the localization output is **useful**. <a href="https://www.eecg.utoronto.ca/~xiachunq/vulnerability_survey.php?project_issue=godot46807&choice=real_useful" target="_blank">check</a> 
- This vulnerability is a **real** vulnerability but the localization output is **not useful**. <a href="https://www.eecg.utoronto.ca/~xiachunq/vulnerability_survey.php?project_issue=godot46807&choice=real_not_useful" target="_blank">check</a> 
- This vulnerability is **not a real** vulnerability. <a href="https://www.eecg.utoronto.ca/~xiachunq/vulnerability_survey.php?project_issue=godot46807&choice=not_real" target="_blank">check</a>

**Comment by vnen** [comment]
@vulnerabilitydetectionlearning do note that Godot has a [policy for reporting security vulnerabilities](https://github.com/godotengine/godot/security/policy). If you want to use this tool on Godot or any other project, you should make sure to review and follow the project's reporting procedures.

**Comment by vulnerabilitydetectionlearning** [comment]
@vnen Hi When we reported this vulnerability we did check the security policy listed and emailed the Godot contact email, however we did not recieve any response. We waited more than two weeks later to open this issue.
