### ISSUE TITLE
Document's fonts are too small

### ISSUE THREAD

**Issue by KnIfER** [godotengine/godot#46820]
**Godot version:**
```
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 1050/PCIe/SSE2
OpenGL ES 2.0 Batching: ON

```

**Steps to reproduce:**
1. In the scripts editor, one can navigate to the embedded godot documents using control + mouse click. 
2. The font size is too small and not ajustable.

![Screenshot (1004)](https://user-images.githubusercontent.com/11593903/110472341-97c2e180-8120-11eb-97e4-6260926546ea.jpg)

![Screenshot (1005)](https://user-images.githubusercontent.com/11593903/110471950-1bc89980-8120-11eb-8080-5b66ca75386c.jpg)

**Comment by akien-mga** [comment]
You can change the Help fonts size in the Editor Settings:
![Screenshot_20210309_135529](https://user-images.githubusercontent.com/4701338/110473730-257ddd00-80df-11eb-8c74-d4348b394b7b.png)
