### ISSUE TITLE
Adding / Removing nodes to EditorSelection does not refresh Inspector (after 3.2.4 rc3)

### ISSUE THREAD

**Issue by takaturre** [godotengine/godot#46821]
**Godot version:**
Godot 3.2.4 rc3 and rc4

**OS/device including version:**
Windows 10

**Issue description:**
When adding nodes to selection (or removing them) via `EditorSelection`, the Inspector panel no longer gets refreshed - however the SceneTree is refreshed properly. It now only gets refreshed when the user selects / removes nodes as opposed to selecting from within a tool script. (Could not find a way to manually refresh the Inspector.)

**Steps to reproduce:**
Follow the minimal reproduction project. Below are general steps:
1. First get the `EditorSelection` instance from `EditorInterface` instance (from an `EditorPlugin` instance). Eg. `EditorPlugin.new().get_editor_interface().get_selection()`
2. Then call `.add_node(my_node)` or `.clear()` to do the changes to the selection.
3. Observe the result: SceneTree is updated, but Inspector is not. (Does not help to emit `selection_changed` from `EditorSelection` instance.)

**Minimal reproduction project:**
[LazyInspector.zip](https://github.com/godotengine/godot/files/6109082/LazyInspector.zip)

**Comment by KoBeWi** [comment]
Might be another consequence of #32908

**Comment by akien-mga** [comment]
> Might be another consequence of #32908

CC @Nehluxhes

**Comment by KoBeWi** [comment]
After looking into it, I think this is not a bug. Before ##32908, any selection change would cause a cascade of calls that would edit every selected node. Now nodes need to be edited (i.e. opened in the inspector) explicitly.

EditorNode has a method called `push_item`, but it's not exposed. Not sure if there is a way to push something to edit in the inspector. We should add/expose such method and properly document that users have to manually edit the nodes.

**Comment by nonfinity** [comment]
@KoBeWi I am able to push things to the editor with this inspect_object() call. Is that what you are talking about?

https://docs.godotengine.org/en/stable/classes/class_editorinterface.html#class-editorinterface-method-inspect-object

**Comment by takaturre** [comment]
Thanks! I had only used `inspect_object` for resources and selection for nodes, didn't realize inspecting works for nodes, and this is (now) intended behaviour - not a bug. So, for anyone with similar tool helpers, the solution is to add `EditorInterface.inspect_object(node)` after calling `EditorSelection.add_node(node)`.

**Comment by takaturre** [comment]
Btw. Any idea how to refresh the inspector to view multiple (selected) nodes ?

**Comment by solodeveloping** [comment]
If someone find this issue, now it should be:
EditorInterface.inspect_object => EditorInterface.edit_node
