### ISSUE TITLE
Spatial Shader with no render_mode set appears to default to "specular_disabled" rather than "specular_schlick_ggx"

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#46838]
**Godot version:**

3.2.4.rc4

**OS/device including version:**

NA

**Issue description:**

When no specular rendermode is specified, Spatial Shaders appear to default to specular_disabled. The manual says that specular_schlick_ggx is supposed to be the default. specular_schlick_ggx also is set both when converting a Spatial Material to a shader and making a visual shader, so it appears it should be the default everywhere?
https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/spatial_shader.html#render-modes
![image](https://user-images.githubusercontent.com/4955051/110518252-cda59d00-8103-11eb-9ebe-9e3572dcbe0f.png)

**Steps to reproduce:**
See screebshot above

**Minimal reproduction project:**

See screebshot above

**Comment by clayjohn** [comment]
The documentation needs to be updated to say that specular_disabled is the default

**Comment by AnaDenisa** [comment]
I would like to work on this issue. Could you assign me here, please?

**Comment by Calinou** [comment]
@AnaDenisa No need to be assigned – you can start working on it directly :slightly_smiling_face:

**Comment by Calinou** [comment]
@JonatasOrsini The general rule is to open pull requests against the `master` branch. However, some pull requests need to be done separately for the `3.2` branch (such as this one), so you should open it against the `3.2` branch instead of `master`.

**Comment by akien-mga** [comment]
> I guess we need to clean up this behaviour and make it consistent. And the best way to do that is probably to change the if/elif branch to make GGX default e.g. change the final "elif" to an "else"

I'm not sure about this, looking at the shader there are several locations where `#if defined(SPECULAR_SCHLICK_GGX)` is checked, and changing only one of those to `#else` would likely only solve part of the problem.

But more importantly, `SPECULAR_SCHLICK_GGX` is the default value for `Material::specular_mode`, so I don't understand why the define doesn't end up in the final shader. The proper fix IMO would be to make sure that the generated shader includes the defines that match default values. Reading `material.cpp::_update_shader()` that's what it seems to do, but I guess I'm missing something? I put a breakpoint there and modifying the shader script in the editor doesn't seem to trigger an `_update_shader()` call.

**Comment by JonatasOrsini** [comment]
Please diregard my entry.
