### ISSUE TITLE
The SpriteFrames editor default zoom is too low on hiDPI displays

### ISSUE THREAD

**Issue by luislodosm** [godotengine/godot#46836]
**Godot version:**
3.2.3

**OS/device including version:**

macOS 11.2.2, iMac 5K retina, Radeon Pro 570X 4GB, GLES3.

**Issue description:**
When I select the frames of a sprite sheet for an `AnimatedSprite` the image appears very small, as if it doesn't take into account the HDPI screen.

<img width="2672" alt="Captura de pantalla 2021-03-09 a las 17 18 01" src="https://user-images.githubusercontent.com/63356898/110510799-78fe2400-80fb-11eb-8ec5-33066fe426d3.png">

I think a zoom could be implemented in this window.

**Steps to reproduce:**
- I create an AnimatedSprite.
- I create a SpriteFrames.
- I select "add frames from spritesheet".

**Minimal reproduction project:**
[animated-sprite-bug.zip](https://github.com/godotengine/godot/files/6110291/animated-sprite-bug.zip)

**Comment by Calinou** [comment]
We can solve this by defaulting the zoom level to `EDSCALE`.

**Comment by LightningAA** [comment]
Would it literally be as simple as changing `sheet_zoom = 1.0f;` to `sheet_zoom = MAX(1, EDSCALE);` (line 1236)

**Comment by thorion21** [comment]
I can work on this, can I be assigned?

**Comment by Calinou** [comment]
@thorion21 Thanks for your interest in contributing! No need to be assigned – you can start working on it directly :slightly_smiling_face:
