### ISSUE TITLE
Bug. set_pos not called in body_enter

### ISSUE THREAD

**Issue by eXponenta** [godotengine/godot#4683]
Windows 10. GoDot 2.0.3 stability

Bug. Why `set_pos()` for current node don't work on `body_enter()` signal. Other methods are called from that signal.

Ex:
`func body_enter(body):`
    `self.set_pos(Vector2(100,100)) # doesn't work`
    `body.set_pos(Vector2(100,100)) # normal`

**Comment by akien-mga** [comment]
The issue is probably that your ``self`` node is not what you think it is? Please make a minimal example that reproduces the issue, or give more details on your current implementation.

**Comment by eXponenta** [comment]
[Test.zip](https://github.com/godotengine/godot/files/267875/Test.zip)
Test project.

Getting ALL `get_` in body_enter work normaly. But ALL `set_` cann't calls.

**Comment by carlosmarti** [comment]
I have this bug at the moment and i would like to add that you can call a method with a `set_pos()` inside it and have it work with another nodes `body_enter()` signal calling it.

**Comment by reduz** [comment]
if you use call_deferred("set_pos",position) does it work?

**Comment by carlosmarti** [comment]
Yes the call_deferred() works to change its own position.
