### ISSUE TITLE
Anchors on Control nodes aren't working properly in Godot Mono

### ISSUE THREAD

**Issue by hidemat** [godotengine/godot#46849]
Os: WIndows 10 Home -version 10.0.19042
Godot Engine v3.2.3.stable.mono.official
GLES2 Renderer: GeForce GTX 1050/PCIe/SSE2

**Issue description:**
When setting the layout options on a freshly created Control node:
![Screenshot 2021-03-09 211650](https://user-images.githubusercontent.com/6559151/110571595-60066a80-811d-11eb-94bf-102598923e83.png)

Nothing seems to happen and the bounding box for the control node disappears:
![Screenshot 2021-03-09 211709](https://user-images.githubusercontent.com/6559151/110571659-7f9d9300-811d-11eb-8b82-64116de24138.png)

**Minimal reproduction project:**

[ControlIssue.zip](https://github.com/godotengine/godot/files/6112946/ControlIssue.zip)

**Comment by groud** [comment]
This is an expected behavior, as there is a mistake in your example. You made the Control of a Node2D, which has position but no size. Setting a Layout (which is about setting the control's size according to its parent) will consequently move the control to the Node2D's position, but with no size.

So basically, this is expected. Closing.

**Comment by Calinou** [comment]
@groud What do you think about my Layout suggestion? Or should we print a warning message in this case at the very least? I think there's an usability issue to solve here.

**Comment by hidemat** [comment]
Oh I understand. Thanks for the clarification. Changing the parent node to type Node worked.

**Comment by groud** [comment]
> Maybe we should ensure ourselves that controls resized using Layout options should always have a minimum size (something like 16 pixels in each dimension). This would ensure that their corners can always be grabbed relatively easily.

Sorry for the late response. I don't think that would make sense, forcing a minimum size on a node to be able to edit it does not make a lot of sense. Maybe an idea would be to disable the layout menu if the parent has a size of zero, or simply display a warning (as you may still want to set the layout when the parent could be resized at runtime).
