### ISSUE TITLE
[3.2.4 rc4] HTML5 window/viewport size is incorrect during startup

### ISSUE THREAD

**Issue by db0** [godotengine/godot#46843]
**Godot version:**

3.2.4 RC4 win64

**OS/device including version:**

Windows 10 x64

**Issue description:**

This is what my game's main menu looks like in RC4 HTML5 export

![image](https://user-images.githubusercontent.com/296513/110539331-66004980-8125-11eb-844c-c266113abd38.png)

The game itself also hangs if you load the demo deck and try to play.  (just after pressing "Start Competition")

No errors that I saw in the browser console.

It is working fine when run via Godot.

It is working fine in 3.2.3 HTML5 export. I cannot test in RC3 because it was broken due to #46352

You can see and play it in 3.2.3 export here: http://fragmentforge.dbzer0.com/

Source code: https://github.com/db0/Fragment-Forge

**Comment by akien-mga** [comment]
I can reproduce the issue with RC3 (enabling threads) and RC4.

But could you clarify what the problem is exactly? I understand that the GUI looks all scrambled together but it actually seems to be designed this way in the project, is the issue that the shader animation meant to hide all this is not working? Or is there also an issue with the UI elements additionally to the missing shader effect?

**Comment by db0** [comment]
The GUI elements are pushed out of the way (one screen away) during the _ready(). Then slid into view when a button is pressed.Try out the 3.2.3 version or the non-html5 export.

```
func _ready() -> void:
        ...
	settings_menu.rect_position.x = get_viewport().size.x
	new_game_menu.rect_position.x = get_viewport().size.x
	deck_builder.rect_position.x = -get_viewport().size.x
        ...
```
In RC4, it seems to be messing up the placement of the elements during the _ready() process

Also, it's not just that. Try to start a game using the demo deck included, then press on the "Start Competition" button. The game will hang.This is not happening in 3.2.3

**Comment by akien-mga** [comment]
Tested previous releases, it seems fine on 3.2.4 RC 1 and RC 2, broken on RC 3 and RC 4.
