### ISSUE TITLE
Scenetree Nodes drag and drop visual representation

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#4684]
Currently when selecting many nodes in the scene tree and dragging them creates a list with all selected items which can result in a very long list that is displayed at the cursor position which is imho not needed. You probably read not more than the first 5 items, if even. Why not display the first few items and then fade them out.
Here is a mockup of how it could look like. 
![dnd](https://cloud.githubusercontent.com/assets/6723918/15317672/c7a19710-1c22-11e6-883b-594f185fe1af.jpg)

**Comment by reduz** [comment]
that looks pretty, not sure how much work it is (probably not that much)
and definitely looks nicer than the approach i used for files. I'll give it
a try

**Comment by akien-mga** [comment]
@reduz It's done already, see #4690 ;)

**Comment by ndee85** [comment]
oh wow.. that was a quick one! :)
Great work guys!
