### ISSUE TITLE
Setting `OS.window_maximized = false` on Linux does not change the window size back to its previous size

### ISSUE THREAD

**Issue by ISVios** [godotengine/godot#46840]
#### Godot versions:

3.2.3 - 3.3.1rc

####  OS/device including version:
Linux 5.9.16-1-MANJARO, GeForce GTX 960M 

### Issue description:
When I use ```OS.window_maximized  = true``` - window set maximized (it's ok), but when I try return to normal windows size ``` OS.window_maximized  = false```  - nothing happens.
Ps: ```OS.window_maximized``` never changes on Linux. It eq false, but on Windows all work.  
PsPs: Sorry about my English.

[test_bug.zip](https://github.com/godotengine/godot/files/6112130/test_bug.zip)

**Comment by Calinou** [comment]
@ISVios Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by ISVios** [comment]
[test_bug.zip](https://github.com/godotengine/godot/files/6112119/test_bug.zip)
Sure.

**Comment by boruok** [comment]
confirm **PopOS 21.04**
```gdscript
# doesn't toggles back to normal size
OS.window_maximized = !OS.window_maximized
```
