### ISSUE TITLE
Godot monetization plugin development

### ISSUE THREAD

**Issue by flynetstudios** [godotengine/godot#46847]
We are developing a free plugin for monetization. 
Is a wrapper ,but we cant integreate without recompile Godot.

Is there any way to do this without recompile ? Can anyone guide to us ?

**Comment by clayjohn** [comment]
Hi! 

This space is for bug reports only. 

This question is probably better suited for one of the [community channels](https://docs.godotengine.org/en/stable/community/channels.html)
