### ISSUE TITLE
Godot build cannot find -lstdc++

### ISSUE THREAD

**Issue by ktostam0** [godotengine/godot#46858]
**Godot version:**

master/3.2 branch

**OS/device including version:**

Fedora 33, 64 bit

**Issue description:**

Whenever I try to build Godot everything goes fine until it shows:
```
[100%] Linking Program        ==> bin/godot.x11.tools.64
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```
It used to build just fine some time ago. I have all necessary dependencies (https://docs.godotengine.org/en/3.0/development/compiling/compiling_for_x11.html) installed.
I'm have very little experience with compiling so please excuse me if this issue is related to the OS not the engine.

Also I don't know if it has anything to do with this, but `lstdc++` library in Fedora seems to be named `libstdc++`.

**Steps to reproduce:**
Compile Godot on Fedora (I suppose it's the problem) and watch it fail at the very end.

**Minimal reproduction project:**

None

**Comment by akien-mga** [comment]
> I have all necessary dependencies (https://docs.godotengine.org/en/3.0/development/compiling/compiling_for_x11.html) installed.

Note that this is documentation for Godot 3.0, not 3.2/master.

You need to install `libstdc++-static`, see https://github.com/godotengine/godot-docs/issues/4617.
