### ISSUE TITLE
Godot 3.2.4 RC4 FBX Imported models really hard to select in godot viewport compare to other imported formats

### ISSUE THREAD

**Issue by takhimi** [godotengine/godot#46852]
**Godot version:**
Godot 3.2.4 RC4

**OS/device including version:**
GTX970, 461.81, GLES3
Windows10 64Bit
Blender 2.92 (Steam version)

**Issue description:**
I imported my models in godot and I notices that it is really hard to select with my mouse or pick the models in the editor viewport. It does not have this problem with other formats like gltf,obj,dae

**Steps to reproduce:**
1)From blender just export the models as fbx format. 
2)Import the model into godot and try to select the model in the viewport (not from the scene tree)
3)It is really hard to pick the model from the viewport. However it is really consistently simple or easy  to click or select other models that is not from fbx formats (gltf,obj,dae)

**Minimal reproduction project:**
[GodotImportTest1.zip](https://github.com/godotengine/godot/files/6113128/GodotImportTest1.zip)

[GodotBlendFile.zip](https://github.com/godotengine/godot/files/6113129/GodotBlendFile.zip)

**Comment by takhimi** [comment]
Ok after further testing. I found out that you need to check the "apply transform" when exporting to fbx from blender. This is not the same as Ctrl+ A and apply scale and rotation feature in blender(it is already at scale 1 and rotation=0 in blender).

We need to tick "apply transform" in the blender fbx export menu. You will get problem to select the fbx imported model because the mesh is scaled up to 100 and rotated in x -90 when imported to godot if you didnt tick the "apply transform"

Not sure if this is by design or a bug.

**Comment by takhimi** [comment]
@Calinou Maybe the documentation for fbx importing needs to be updated but it does not  solve the really hard to select the object in the viewport problem. I just tested the same fbx module in Unity and even though the object is scaled up to 100 and rotated x=-90 when imported to Unity (same as Godot without tick the "apply transform" checkbox), I can still select the object without problem in Unity viewport.

![FBX Model in unity](https://user-images.githubusercontent.com/4146156/110719977-c50aaf00-8248-11eb-8798-4a97f8423401.jpg)


I still think this is a bug and should be fix ? Reason is I dont think all user know how to use blender and I think this is going to be more problematic if the user have bought alot of assets and he or she have problem with it when trying to select it in Godot  viewport. Imagine the user is from Unity and trying to use godot, the assets is not a problem in Unity but really hard to select in Godot. Please fix this. Thanks

**Comment by Calinou** [comment]
> I still think this is a bug and should be fix ?

The 3D object picking logic is due for a complete rewrite in 4.0, but I doubt this can be fixed in 3.2 since we have few contributors knowledgeable with the 3D editor.
