### ISSUE TITLE
[FBX] Imported models does not have or supported shade smooth compare to other formats

### ISSUE THREAD

**Issue by takhimi** [godotengine/godot#46851]
**Godot version:**
Godot 3.2.4 RC4

**OS/device including version:**
GTX970, 461.81, GLES3
Windows10 64Bit
Blender 2.92 (Steam version)

**Issue description:**
I'm trying to import some of my models and I notices that the "shade smooth" does not work on Godot when importing fbx models, I've tested importing GLTF, OBJ, and Better collada and the models work as expected (with shade smooth).
This is probably a bug to godot fbx import module since the same fbx file is open correctly in Substance Painter(with smooth shaded). 

**Steps to reproduce:**
1)In blender try to model some cylinder or something and right click "shade smooth", on the object property check the autosmooth
2)Export as fbx and import to godot. I did export other format also(gltf,obj,dae) as a control group.
3)Object imported from fbx format does not have shade smooth but other formats will have the shade smooth) worked as expected.)

**Minimal reproduction project:**

[GodotImportTest1.zip](https://github.com/godotengine/godot/files/6113065/GodotImportTest1.zip)
[GodotBlendFile.zip](https://github.com/godotengine/godot/files/6113072/GodotBlendFile.zip)

![Godot bug](https://user-images.githubusercontent.com/4146156/110574554-46eecf80-8198-11eb-92e9-3c1060cd2a92.jpg)

**Comment by Enixoid** [comment]
Godot 3.2.3 or 3.2.4? I have this problem in godot 3.2.4 rc4

**Comment by takhimi** [comment]
Ops.. Sorry for the typo.

**Comment by takhimi** [comment]
@Calinou 

Just tested and the shade smooth works with 3.2.3(Steam version). My guess is that the new fbx importer module need some tweaking.

![Godot 3 2 3 FBX ShadeSmooth](https://user-images.githubusercontent.com/4146156/110718823-ab686800-8246-11eb-82da-8a1a2583e866.jpg)

**Comment by takhimi** [comment]
Just reporting that it still happens for 3.2.4 RC5.

**Comment by felixscheffer** [comment]
The issue still exists in 3.4 beta 2

**Comment by takhimi** [comment]
Still happens for 3.4 beta 3

**Comment by huhund** [comment]
Ou noes :(, does anybody know a work around for this? I see it 3.4.1 as well.

**Comment by felixscheffer** [comment]
> Ou noes :(, does anybody know a work around for this? I see it 3.4.1 as well.

I am using obj and glb as file format instead.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
