### ISSUE TITLE
[3.2.4 rc4] [HTML5] Infinite loop while using `HTTPClient.get_status()` while-loop

### ISSUE THREAD

**Issue by db0** [godotengine/godot#46857]
**Godot version:**

3.2.4 RC4 win64
**OS/device including version:**

Windows 10 x64
**Issue description:**

My project HTML5 export was breaking in RC4 when performing an http client interaction and I was investigating why. 

I am using [a modified http_client tutorial code](https://docs.godotengine.org/en/stable/tutorials/networking/http_client_class.html#doc-http-client-class)

I have discovered that when you reach this part in an HTML5 export, it goes into an infinite loop:
```
        while http.get_status() == HTTPClient.STATUS_BODY:
            # While there is body left to be read
            http.poll()
            var chunk = http.read_response_body_chunk() # Get a chunk.
            if chunk.size() == 0:
                # Got nothing, wait for buffers to fill a bit.
                OS.delay_usec(1000)
            else:
                rb = rb + chunk # Append to read buffer.
```

This is working fine in non-HTML5, and it's also working in 3.2.3 HTML5

**Steps to reproduce:**

In my minimal demo, press the button while in an HTML5 export. The game will get stick in a loop and you'll see my `print_debug()` continue infinitely.

You can also see it [in my game directly](https://github.com/db0/Fragment-Forge)

**Minimal reproduction project:**

I have created this little reproduction project, based on my own game's web code to show this issue. It's connecting to my own web server for this demo purposes.

[http_poll_loop.zip](https://github.com/godotengine/godot/files/6114900/http_poll_loop.zip)

**Comment by Faless** [comment]
You can't poll while busy waiting in HTML5. That has always been the case (and printed error in debug mode when detected).
The only reason it worked in your specific case previously is that the `STATUS_BODY` used to be set only when the request was fully received because it didn't support chunking.
In fact, I would say that the main issue here is that the warning about polling multiple time is only shown during request, and not during BODY also.

**Comment by db0** [comment]
In that case the [official example](https://docs.godotengine.org/en/stable/tutorials/networking/http_client_class.html#doc-http-client-class) also has to be tweaked.

How should I be doing it instead?

**Comment by db0** [comment]
OK Converting the while-loop to the following fixes it for me

```
			while http.get_status() == HTTPClient.STATUS_BODY:
				# While there is body left to be read
				# Get a chunk.
				var chunk = http.read_response_body_chunk()
				if chunk.size() == 0:
					if not OS.has_feature("web"):
						http.poll()
						# Got nothing, wait for buffers to fill a bit.
						OS.delay_usec(1000)
					else:
						# Synchronous HTTP requests are not supported on the web,
						# so wait for the next main loop iteration.
						yield(Engine.get_main_loop(), "idle_frame")
				else:
					# Append to read buffer.
					rb = rb + chunk
```

I think this can be closed but the documentation needs to be updated imho.

**Comment by db0** [comment]
[I use threading myself](https://github.com/db0/godot-card-game-framework/blob/main/src/core/GameStats.gd) but this of course doesn't work in HTML. I think a workaround would be to store the HTTPClient object as a global var, then process the http.poll() in _process() as Faless suggested earlier and continue the execution from there. 

```
if http.get_status() == HTTPClient.STATUS_BODY and body_processed == false:
   body_processed = true
   process_body()
```

**Comment by Calinou** [comment]
> I can probably craft this myself, but I don't know how to update the documentation :D

The process is documented here: https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html

Make sure to open the pull request against the `master` branch of this repository, not godot-docs.

**Comment by db0** [comment]
OK I'll give it a try

**Comment by db0** [comment]
So, @Calinou [the page I need to update](https://docs.godotengine.org/en/stable/tutorials/networking/http_client_class.html) is under the tutorials. I think this is indeed in the godot-docs repo. https://github.com/godotengine/godot-docs/blob/master/tutorials/networking/http_client_class.rst no?

**Comment by db0** [comment]
Given the format of that tutorial describing a simple script, I decided to not fragmentize it into multiple functions using `_process` as that would require to rewrite it as a class. 

I think if someone needs something that complex, they can use the [HTTPRequest node](https://docs.godotengine.org/en/stable/classes/class_httprequest.html), no?
