### ISSUE TITLE
In 2d setting more than one collision masks works like setting collision layer

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#4685]
**Operating system or device - Godot version:**
Ubuntu 14.04 Godot 2.03

**Issue description** (what happened, and what was expected):
Putting in layer mask more than one layers it works like it was setted to the collisions layer.
The object is going to be detected from other objects.

**Steps to reproduce:**
Just put one more layer in the layer mask.

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
@kakoeimon ~ Please include an example project, or screenshots of the different objects' masks, since on this matter it is rather easy to mess things up :smile:

**Comment by kakoeimon** [comment]
@bojidar-bg . You are right! I tried to recreate this and I can't. Sorry for that.
Can I delete the issue?

**Comment by bojidar-bg** [comment]
@kakoeimon No, but I'll close it for you :)
