### ISSUE TITLE
Godot Doesn't screen clear in Both 3D and 2D Editor

### ISSUE THREAD

**Issue by SchimmelSpreu83** [godotengine/godot#46867]
**Godot version:**

Godot Engine v3.2.3.stable.official

**OS/device including version:**

GPU: 
AMD Radeon Vega 8

CPU:
AMD Ryzen 3 2200G with Radeon Vega Graphics

Project is in the build-in D: drive (not ssd, 1 TB)

Renderer:
GLES3 -(maybe GLES2 too)

**Issue description:**

it doesn't screen clear after about 2 min. It's only in the editor in 2D as well in 3D. I don't know how to replicate it, but it happens randomly. Here is a video i made from the Bug in 2D: https://youtu.be/VGer9-4jjFA

**Steps to reproduce:**
I have no idea

**Minimal reproduction project:**

I think it happend only my machine. I couldn't find any help in the internet

**Comment by KoBeWi** [comment]
Maybe something is changing the clear mode of your Viewport? Like editor plugin or something. It's possible to break the editor via tool scripts.

**Comment by SchimmelSpreu83** [comment]
It's happening in other projects too. I fixed it by using the version: 3.2.4.rc4

**Comment by KoBeWi** [comment]
Well if it doesn't happen in 3.2.4 then this can be closed.
