### ISSUE TITLE
Problem with the menu "Manage export templates"

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#46862]
**Godot version:**

3.2.4 rc4 mono

**OS/device including version:**

win10 64

**Issue description:**

The menu is poorly displayed

![Captura2](https://user-images.githubusercontent.com/19652075/110618336-ee6b0280-8196-11eb-8f27-11d86d119a31.PNG)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Duplicate of #35695
Fixed in 4.0
