### ISSUE TITLE
Baked Lightmap Regression

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#46861]
**Godot version:**

3.2.4 (from new cpu lightmapper introduction to rc4, worked fine in 3.2.3 stable)

**OS/device including version:**

Both backends (vulkan isn't 3.2), Nvidia Quadro K2000, 452.06

**Issue description:**

Result of Bake is the same as non baked, aside from the lack of shadowing there is no indirect light.

**Steps to reproduce:**
Make a few meshes with Uv2 ready for lightmap usage, enable baking of the light and the meshes, bake.
If shadows are used, the result will look like just the light with shadows off.

**Minimal reproduction project:**

[Bug.zip](https://github.com/godotengine/godot/files/6115157/Bug.zip)

Note: Indirect light and shadows are applied to dynamic objects correctly, so only the Baked meshes have issues with not getting the indirect light and shadows

**Comment by Calinou** [comment]
@mrjustaguy Can you reproduce this in 3.2.4rc3?

**Comment by mrjustaguy** [comment]
Yes I get the exact same result, all the way from 3.2.4 beta 6 to now. It takes a while to bake, and only dynamic objects get anything from the bake, however to baked objects it's like there's just a light with no shadows or anything else. 3.2.4 beta 5 is the last one that gives Some result on baked objects, which is before the new cpu lightmapper..

On that note: running an Intel Pentium G3258 which is quite an old CPU (like 7 years or so)

**Comment by JFonS** [comment]
I tried the reproduction project and I can reproduce the issue locally, so I will investigate what's going on. I double-checked on other projects and the baking still works, so there must be something specific to this project. 

Thanks for testing, and I will keep you posted :)

**Comment by akien-mga** [comment]
Fixed by #46932.
