### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#4686]
**Operating system or device - Godot version:**
Win7/Godot 2.0.3

**Issue description** (what happened, and what was expected):
Tooltips on buttons blink on some machines.  When tested with another app (MS word) tooltips that app's tooltips did not blink.

**Steps to reproduce:**
Create a button with a tooltip
run
mouse over the button
tooltip regularly blinks on and off 

**Link to minimal example project** (optional but very welcome):

--------------------

Not sure if this is button related or all tooltips. However playing around with this on Win10 I see that the tooltip cuts off if the mouse gets any movement at all, even if it stays over the button. IMO the tool tip should only go off if the mouse moves off the button.

**Comment by bojidar-bg** [comment]
Dupe of #3835?

**Comment by captainwasabi** [comment]
probably.

**Comment by bojidar-bg** [comment]
@captainwasabi ~ For the record, did you reproduce it in the editor or in the running game?

**Comment by captainwasabi** [comment]
These were users systems so they were running the app.  However on my Win10 dev system I do reproduce that if the mouse moves the tooltip blinks even though it stays over the item with the tooltip.  I tested a bunch of other apps and none of them exhibit that behavior.  I surmise that in godot any mouse message resets the "hover timer" rather than the mouse position exiting the item.

**Comment by captainwasabi** [comment]
Yeah, this seems to have worked.  How do I build a 64 bit exe on windows? It says the bits argument is not supported.
