### ISSUE TITLE
Master build no longer supports empty or nested namespaces (C#)

### ISSUE THREAD

**Issue by Cat-Lips** [godotengine/godot#46879]
**Godot version:**
-Godot Engine v4.0.dev.mono.custom_build.afd0df792

**OS/device including version:**
-Windows 10/C#

**Issue description:**
-No namespace => Compile time error: `...\.Node_ScriptPath_Generated.cs(2,10): Identifier expected`
-Nested namespace => Run time error: `Cannot instance script because the class 'X' could not be found`

**Steps to reproduce:**
-Create new project, add new node, add C# script
-Build with default template gives compile error
-Add namespace, builds & runs ok
-Add nested namespace, builds, but fails to find script at runtime

**Minimal reproduction project:**
-Minimal working version: https://github.com/Cat-Lips/GodotSharp.BuildingBlocks
--Remove or add nested namespace to reproduce

**Comment by neikeq** [comment]
Is the error reproducible with the example project as is or are some modifications needed? I don't know what `Remove or add nested namespace to reproduce` means exactly.

**Comment by Cat-Lips** [comment]
Apologies for the brevity, yes.
If you remove the namespace from around Bootstrap.cs, you get the compilation error.
If you change `namespace MyGame` to (eg) `namespace MyGame.Scenes` you get the runtime error.
I've attached minimal examples to illustrate (as I should have in the original ticket!)

[NoNamespace.zip](https://github.com/godotengine/godot/files/6127386/NoNamespace.zip)
[NestedNamespace.zip](https://github.com/godotengine/godot/files/6127384/NestedNamespace.zip)

**Comment by Cat-Lips** [comment]
Great work, all!

I have run the attachments against the new build and both are working as expected :)

Thanks for the timely turnaround :)
