### ISSUE TITLE
Android plugins fail to load in RC4

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#46875]
**Godot version:**
3.2.4rc4

**OS/device including version:**
Windows 10, Android 10

**Issue description:**
I tried out the Android plugin system with the latest rc4 (updated from rc1 which did not have this issue) and all my updated plugins failed to load. 

This is what i found in Logcat: 
```
2021-03-10 18:00:18.288 2900-2900/? W/GodotPluginRegistry: Plugin xyz is listed in the dependencies but is not enabled.
```
When looking at `git diff` i found that Godot also removed a meta tag in `android/build/src/release/AndroidManifest.xml` which listed the plugins. This might be fine and not related to this issue but i thought i'd mention it since it seems suspicious.

Probably a regression from #46454. @m4gr3d

**Comment by m4gr3d** [comment]
@mbrlabs it sounds like you didn't regenerate your `res://android/build` directory :)

The error is occurring because the previous logic (which is probably still in your `res://android/build` directory) requires the `meta-data` tag you referred to, while the new logic is more flexible and do away with it.

**Comment by mbrlabs** [comment]
Ah yes, thanks for explaining ;) Looking at #46454 more closley i can see why that happend. The problem is that i can't just regenerate the `android` folder. It would override my modifications, so i have to do it manually. Anyway, i'm going to close this issue once i got it working.

**Comment by m4gr3d** [comment]
You should be able to get it working by replacing the `godot-lib*.aar` binaries in the `res://android/build/libs` subdirectories with the latest ones from the RC4 template, and removing the `meta-data` tag in `res://android/build/AndroidManifest.xml` file.

**Comment by mbrlabs** [comment]
@m4gr3d I already updated the *.aar binaries. Yes i just removed the meta tag and updated `res://android/build/config.gradle` which also changed. Now it's working.

@akien-mga in the final release notes for 3.2.4 you should probably mention that some files (besides the `*.aar` libs) for the custom Android build process changed and that they need to be updated.

**Comment by akien-mga** [comment]
The general guideline is normally that users should redo the whole `res://android/build` install every time they change Godot version... which I agree is quite difficult when having a heavily modified custom build, we've been discussed options to improve this workflow but it's not implemented yet.

@m4gr3d Do you think we can have some kind of upgrade guide that tells users how to update their custom build template without losing custom changes? Or is this too use-case specific and hard to give general guidelines?

**Comment by mbrlabs** [comment]
I don't know if it's documented already that you have to regenerate the the build directory for every update, but IMO that's enough. Maybe add one sentence that custom modifications need to be redone afterwards.

Anyway, i'm closing this now since it's not actually a bug :)
