### ISSUE TITLE
canvas_item shader setting alpha greater than one, caps alpha at 1 on GLES2

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#46885]
**Godot version:** 3.2.3

**OS/device including version:**
- OS: Windows 10 (Home edition?)
- Godot reports my GPU as OpenGL ES 3.0 Renderer: GeForce GTX 1650 Ti/PCIe/SSE2

**Issue description:**
One of my shaders makes sprites "highlight" by setting the alpha to a value between 1x and 3x the original (1-3). In GLES3, it looks correct (see below); in GLES2, there is no visible change (I think it's capping the alpha at 1.0).

![image](https://user-images.githubusercontent.com/31222662/110724172-47f91e80-81e3-11eb-83a2-5073c12db678.png)

**Steps to reproduce:**
Here's an approximation of my shader:

```
shader_type canvas_item;

uniform float highlight_amount : hint_range(1, 3) = 1.0;

void fragment() {
	vec4 final_colour = texture(TEXTURE, UV);
	float alpha = texture(TEXTURE, UV).a;
	COLOR = vec4(final_colour.r, final_colour.g, final_colour.b, alpha * highlight_amount);
}
```

Please advise. I was told that this is something I should open a bug-report about.

For what it's worth, this renders the same in Godot 3.1.2. In 3.0.6, which only supports GLES3, this renders correctly (with the glow).

**Comment by clayjohn** [comment]
GLES2 doesn't support high dynamic range (HDR) rendering. Which means all color values are limited to the range 0-1 

See here for more info. https://docs.godotengine.org/en/stable/tutorials/misc/gles2_gles3_differences.html#hdr

**Comment by Calinou** [comment]
Try multiplying the RGB colors instead of increasing alpha above 1.0.

**Comment by nightblade9** [comment]
`Color(3, 3, 3)` doesn't look the same, but I get your point: it's not going to work in GLES2. I'm not good with shaders, I don't know how to reproduce the effect, so I'll try and come up with something else that achieves the same goal.

Thanks for clarifying.
