### ISSUE TITLE
Missing sprites, suspected GPU driver issue with GLES3

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#46886]
**Godot version:** 3.2.3

**OS/device including version:**
- Windows 10 home edition
- Godot reports my GPU as OpenGL ES 3.0 Renderer: GeForce GTX 1650 Ti/PCIe/SSE2

**Issue description:**

In one particular scene of my game, monster sprites don't appear, except for very brief appearances (one frame or so) when I show/hide or use shaders. The issue used to be unpredictable (coming and going at random), with no logical cause or fix (restarting Godot several times sometimes fixes it, restarting my PC used to fix it, now it's stuck.) 

Here's how it looks, with GLES2, then GLES3:

![image](https://user-images.githubusercontent.com/31222662/110725697-0453e400-81e6-11eb-92b6-76ca7c0e85a4.png)

![image](https://user-images.githubusercontent.com/31222662/110725675-f7cf8b80-81e5-11eb-9e12-200fb41f08b3.png)

Strange things seem to trigger the disappearance of the monster sprites:

- Adding nodes on the other side of the scene with the same Y-value or that would overlap if they were placed on top of monster sprites
- Zooming in sufficiently in the editor and/or in game
- ???

You can see a video of a previous variation of the issue here: https://twitter.com/nightblade99/status/1365450489534504962

At present, my game simply never shows monster sprites, or text, in this scene, in GLES3. Switching to GLES2 solves the issue.

I don't have steps to reproduce or an MVP project, because this is so unpredictable. (Moving nodes, removing nodes, adding nodes, etc. cause this issue to appear/disappear; sometimes zooming in fixes/breaks it.)

**Comment by clayjohn** [comment]
Can you try with the release candidate of version 3.2.4?

https://downloads.tuxfamily.org/godotengine/3.2.4/rc4/

There have been some changes to 2D rendering in GLES3 that may help.

**Comment by nightblade9** [comment]
> Can you try with the release candidate of version 3.2.4?

Frustratingly, this bug isn't reproducing on this machine today. I've downloaded 3.2.4, and I'll keep an eye on it. As soon as it comes back, I'll switch to 3.2.4 and report back.

**Comment by nightblade9** [comment]
Saw this issue reproduce today. TL;DR 3.2.4 RC5 seems to work fine.

I'll monitor further and report back if this recurs, but I'm pretty sure it's solved. What I tried:

- Open RC5 and 3.2.3 at the same time
- Run 3.2.3, see the bug
- Run RC5, see everything's fine
- Run 3.2.3, see the bug
- Run RC5, see everything's fine

Also tried variations with closing/opening both versions, making sure 3.2.3 still breaks, and that RC5 is still good. I think it's good. Will close now and reopen if it comes back.

Thanks for the suggestion @clayjohn
