### ISSUE TITLE
min() and max() don't return the right value

### ISSUE THREAD

**Issue by EuclidianMonkey** [godotengine/godot#46894]
**Godot version:**
Godot 3.2.3 stable official release

**OS/device including version:**
Windows 10

**Issue description:**
Strange cases where min(a, b) doesn't actually return either a or b

**Steps to reproduce:**
(Reproduction project included below) This seems to be linked with the OS.get_system_time_msecs() function call, as well as the min(), max(), or clamp() function calls. 
When writing a condition to pick which value to store (if t > now : t = now), the bug does not appear.
When switching from OS.get_system_time_msecs() to OS.get_ticks_msec(), the bug does not appear. However, in the context of the project in which the bug was spotted, the issue is still present while using OS.get_ticks_msec() instead of OS.get_system_time_msecs().
When switching from OS.get_system_time_msecs() to a hard-coded value (1615465414656 for example), the bug does not appear.

**Minimal reproduction project:**

```gdscript
extends Node


func _ready():
	var t = INF
	var now = OS.get_system_time_msecs()
	t = min(t, now)
	print(t, " == ",  now, " : ", t == now)
```

Output : 
```
1615465414656 == 1615465427994 : False
```

**Comment by KoBeWi** [comment]
Could it be because `OS.get_system_time_msecs()` returns int, but min returns float?

**Comment by EuclidianMonkey** [comment]
> Could it be because `OS.get_system_time_msecs()` returns int, but `min` returns float? Like precision problem or something.

Interesting : apparently, casting OS.get_system_time_msecs() as a float (  float(OS.get_system_time_msecs())  ) seems to make the issue disappear. However, casting this result as an int again (  int(float(OS.get_system_time_msecs()))  ) doesn't make the issue reappear. My first intuition would be some kind of delayed execution of OS.get_system_time_msecs() is causing the issue, and the cast forces it to execute at the right moment, but other methods of trying a force cast (by comparing this value to a number) doesn't have the same effect of making the issue disappear again.

**Comment by KoBeWi** [comment]
`float`s lose precision with big numbers, so when you do `int(float(big_number))`, you get an integer that can be correctly represented by a float, but it's not the same as the original `big_number`.

**Comment by EuclidianMonkey** [comment]
> `float`s lose precision with big numbers, so when you do `int(float(big_number))`, you get an integer that can be correctly represented by a float, but it's not the same as the original `big_number`.

This seems to be the cause of the issue : min() takes floats as parameters, so there is likely a cast of those big integers to floats, which mean the result of min() is a float precision away from the big integer input. Some small tests seem to confirm this is what's happening.

Should this issue be closed then? This is arguably not really related to min() or OS.get_system_time_msecs() implementation, although maybe this could lead to a more robust version of min() for these special cases.

**Comment by KoBeWi** [comment]
Well, there is `mini()` method in 4.0 that uses and returns ints, so it's no longer relevant there and in 3.2 we can only "fix" this with documentation. But not sure where would it fit.

Should be fine to close the issue.
