### ISSUE TITLE
Wireframe View in editor does not clear

### ISSUE THREAD

**Issue by unpause** [godotengine/godot#4689]
**Operating system or device - Godot version:**
Windows 7 64 bit - Godot 2.0.3 64 bit and 32 bit

**Issue description** (what happened, and what was expected):
I switched the editor to the wireframe mode (3D -> View -> Display Wireframe) and i moved the camera around, but the editor didn't clear the view properly and this happens: 
![godot_wireframe_view_noclear](https://cloud.githubusercontent.com/assets/9016634/15325490/d97af6fc-1c4a-11e6-81bd-f71f3455d276.PNG)

**Steps to reproduce:**
1. Open project
2. Switch to wireframe rendering mode
3. Move the camera around
4. TADA you see it

**Link to minimal example project** (optional but very welcome):
Every example project thats 3D should work

**Comment by akien-mga** [comment]
Congrats, that's a good runner for the most artistic bug report of the month :-P

**Comment by unpause** [comment]
Possible Duplicate of #2489, Sorry

**Comment by akien-mga** [comment]
Right, let's keep only the old bug report then.
