### ISSUE TITLE
Node can not be selected after clicking it's script icon in Godot Editor

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#46935]
**Godot version:**

3.2.4 rc4

**OS/device including version:**

Mac OS

**Issue description:**

Node and it's script file can not be switched by click the node icon and the script icon.

**Steps to reproduce:**
1.add a node 
2.attach a script file to the node 
3.click the script icon of the node to open the script, the Inspector change to property of the script file
4.click the node again to select it again, the Inspector still show the property of the script, not the property of the node.

The node can not be selected again. In 3.2.3 it can be select again.

It can only become selected by clicking on another node and click the node again.

**Minimal reproduction project:**

**Comment by snougo** [comment]
yeah I found this issue too, it's a bit of annoying

https://user-images.githubusercontent.com/64188282/110950232-8d9e1e80-837e-11eb-94d2-ae241e4b5dfa.mov

**Comment by Torguen** [comment]
It is practically the same as https://github.com/godotengine/godot/issues/46633
