### ISSUE TITLE
Godot's integreted explorer doesn't strip spaces at the end of a folder name, and it causes problems with windows

### ISSUE THREAD

**Issue by leElvyn** [godotengine/godot#46944]
**Godot version:**

3.2.3 steam build

**OS/device including version:**

windows 10 pro 20H2

**Issue description:**

### What should happen : 
when creating a folder via the integrated explorer, every spaces at the end should be removed.
### What happened :
the space is left, and this confuses windows / windows explorer / windows file system 

**Steps to reproduce:**
- Open Godot 
- click "new project"
- click "browse" 
- click "create folder"
- on the prompt, type a name and add a space at the end
- click "ok"

**Minimal reproduction project:**

None

## Notes : 

you can't easily remove the folder, as windows explorer returns an error
powershell doesn't work either for the same reason

To remove it, the only way i found is using Windows Subsystem for linux, and use `rm - rf 'folder '`

**Comment by Calinou** [comment]
This has been a recurring issue throughout the editor, which needs to be fixed locally in every case where it happens.

**Comment by akien-mga** [comment]
Fixed by #46969.
