### ISSUE TITLE
[3.2.4 RC4] Engine.has_singleton("GameCenter") fails on iOS Works in 3.2.3 Stable

### ISSUE THREAD

**Issue by Tekuzo** [godotengine/godot#46948]
**Godot version:**

3.2.4 RC4

**OS/device including version:**

iPhone SE running iOS 14.4

**Issue description:**

When I attempt to Authenticate to Game Center, the if statement fails because the Game Center singleton is not detected.

**Steps to reproduce:**
if (Engine.has_singleton("GameCenter")):

this if statement will validate as false, and if the singleton doesn't exist I can't authenticate to iOS services.

**Minimal reproduction project:**

[Test Project.zip](https://github.com/godotengine/godot/files/6132468/Test.Project.zip)
I have removed my identifier and team ID from this project, one will need to be added before it can be exported

**Comment by Zireael07** [comment]
IIRC game center support was moved to an addon?

**Comment by Tekuzo** [comment]
Ah, missed that in the patch notes. Thank you
