### ISSUE TITLE
Per Pixel Transparency is broken when using borderless windows and fullscreen in godot 3.2.3

### ISSUE THREAD

**Issue by bubu-code** [godotengine/godot#46958]
**Operating System:**
Windows 7 Pro SP1.

**Godot Version:**
Godot 3.2.3 stable.

**Issue:**
Per Pixel Transparency replaces transparency with black when using Borderless windows and Maximized Mode (or Fullscreen).
On Godot 3.2.2 stable the window works fine **only when exporting**.
However, on Godot 3.2.3 stable the window replaces transparency with black.
When running the project from the Godot Editor the window is always broken.

**Steps to reproduce:**
Go to Project Settings and set the window to be borderless and enable Per Pixel Transparency.
Make a new scene and attach a script to it.
Add in the ready function:
get_tree().get_root().set_transparent_background(true)
OS.window_maximized = true
(Change it to false to see the normal condition)
Export the project in Godot 3.2.3 stable and Godot 3.2.2 stable.

**Minimal Project:**
[window_transparency_bug.zip](https://github.com/godotengine/godot/files/6134074/window_transparency_bug.zip)

**Exported project (Godot 3.2.2 stable) with the expected behavior:**
[window_transparency_bug_godot_3.2.2.zip](https://github.com/godotengine/godot/files/6134067/window_transparency_bug_godot_3.2.2.zip)

**Comment by Purgeme** [comment]
Godo-3.2.3 had this issue with windows 10 as well.
Building from master branch doesn't seem to have the same problem so I think it might be fixed.

**Comment by bruvzg** [comment]
This is expected, in the full screen or borderless full screen (borderless + maximized) mode per-pixel transparency may or may not work depending on GPU driver and OS. When the full screen window is detected, OS can stop rendering other windows.

As a workaround, you can set the window size to be a few pixels smaller than a screen size.

> Building from master branch doesn't seem to have the same problem so I think it might be fixed.

Currently, there's no per-pixel transparency support in `master` at all.

**Comment by Bubutotti** [comment]
Is this problem already fixed in Godot 3.2.4?

**Comment by Bubutotti** [comment]
My GPU is a GeForce GTX 1050 Ti and my driver is currently version 456.38.

**Comment by Calinou** [comment]
> Is there a way to make a borderless window maximized without being in Fullscreen mode (eg. Showing the taskbar like a normal window would)?

Enablr borderless window in the Project Settings, disable fullscreen and set `OS.window_maximized = true` in a script.

Note that we don't recommend implementing client-side decorations in Godot as there is no way to implement custom draggable areas yet. Moving the window yourself when the user drags the title bar *will* lead to desyncs and issues on multi-monitor setups (on top of not being able to benefit from window managers' tiling features).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/60665, as this is the same underlying cause.
