### ISSUE TITLE
capitalize properties deactivated not work with shader variables names

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#46961]
**Godot version:**

3.2.4 rc4 mono

**OS/device including version:**

win10 64

**Issue description:**

I am creating a bool variable to activate my visuashader effect, I want to name the variable with the name "ImpactEffect" or "impactEffect" but the editor decides that it is better "Impact Effect" which creates confusion for me.

![Captura2](https://user-images.githubusercontent.com/19652075/111027348-025d7100-83f0-11eb-8936-1bb25db24be6.PNG)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by jmb462** [comment]
I think it's more a feature than a bug.
It increases editor readability and may be the expected behavior.

![spacee](https://user-images.githubusercontent.com/3649998/111027978-e1971a80-83f3-11eb-94d0-46ce71527417.png)

**Comment by Torguen** [comment]
In my opinion I would prefer that the variables appear as I name them.
If later I don't remember the name of a variable and need to check it in the editor, it will show a name that is not the real one.

**Comment by jmb462** [comment]
Real name is in the tooltip.

**Comment by Torguen** [comment]
> Real name is in the tooltip.

Could you tell me where I can find that?

**Comment by jmb462** [comment]
![tootip](https://user-images.githubusercontent.com/3649998/111028159-32f3d980-83f5-11eb-8e6f-0ad0bb6128e2.png)

Just put the mouse cursor over the name in the editor. It will popup.

**Comment by Torguen** [comment]
Oh, okay.
Thank you, although I still think the same.

**Comment by VedatGunel** [comment]
You can get rid of that behavior by turning off  `Capitalize Properties` in `Editor Settings > Interface > Inspector`.

**Comment by Torguen** [comment]
> You can get rid of that behavior by turning off `Capitalize Properties` in `Editor Settings > Interface > Inspector`.

Oh, are you sure?
I did and restarted the editor but it didn't change the name.
![Captura2](https://user-images.githubusercontent.com/19652075/111029233-e233af00-83fb-11eb-8537-5af9cef78607.PNG)
![Captura3](https://user-images.githubusercontent.com/19652075/111029234-e2cc4580-83fb-11eb-8dea-a719b8288b5f.PNG)

**Comment by VedatGunel** [comment]
It works with all the other properties, but not shaders for some reason.

**Comment by akien-mga** [comment]
Confirming that this capitalization is a feature, but indeed the `Editor Settings > Interface > Inspector > Capitalize Properties` option is supposed to turn it off for users who prefer to see the names unchanged. So what needs to be fixed here it that it doesn't seem to be respected for Shader Params.

**Comment by jmb462** [comment]
@akien-mga The problem concerns all subinspectors properties. Capitalization is always set to true regardless of editor settings.

Wiil be fixed by this PR : #46967
