### ISSUE TITLE
Shader_param not work with "Set( "...", true );"

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#46963]
**Godot version:**

3.2.4 rc4 mono

**OS/device including version:**

win10 64

**Issue description:**

The Set method doesn't work when I try to set a value to a shader parameter.

![Captura4](https://user-images.githubusercontent.com/19652075/111028161-37b88d80-83f5-11eb-9fb5-9f5028ecc46a.PNG)
![Captura3](https://user-images.githubusercontent.com/19652075/111028163-39825100-83f5-11eb-968f-7e8fc65f479a.PNG)
![Captura2](https://user-images.githubusercontent.com/19652075/111028168-44d57c80-83f5-11eb-9b5d-fe48224625a6.PNG)

**Steps to reproduce:**

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/6134675/test.zip)

[testGDScript.zip](https://github.com/godotengine/godot/files/6134684/testGDScript.zip) -> RC3

**Comment by jmb462** [comment]
`using Godot;
using System;

public class Sprite : Godot.Sprite
{
	public override void _Ready()
	{
		
		Material.Set("shader_param/impactEffect", true);
		GD.Print(Material.Get("shader_param/impactEffect"));
	}
}`

**Comment by Torguen** [comment]
Ok it works, the error was in my code.
Thanks.
