### ISSUE TITLE
Changing Editor Settings Asset library URLS doesn't update editor

### ISSUE THREAD

**Issue by menip** [godotengine/godot#46977]
**Godot version:**
3.2.4-rc5

**OS/device including version:**
N/A

**Issue description:**

I change asset library urls in editor settings, but the editor dropdown is not updated. This is because of missing functionality in  #45202. Restarting the editor updates with new settings, but this should not require a restart.

**Steps to reproduce:**
Initial:
![image](https://user-images.githubusercontent.com/22862244/111042148-bfe86400-83f0-11eb-9f6b-eb1d070bece1.png)
![image](https://user-images.githubusercontent.com/22862244/111042198-08078680-83f1-11eb-8b4c-5f25087edd9e.png)

Update settings, for example add new entry or modify current entries:
![image](https://user-images.githubusercontent.com/22862244/111042241-41d88d00-83f1-11eb-9ac9-7bbcc194f2ea.png)

Editor doesn't update with new ones:
![image](https://user-images.githubusercontent.com/22862244/111042262-66cd0000-83f1-11eb-9b03-765e0adc5c43.png)

After editor restart, we see our changes:
![image](https://user-images.githubusercontent.com/22862244/111042300-9a0f8f00-83f1-11eb-9968-3baaee99b7ce.png)

**Minimal reproduction project:**
New/empty project is all you need.

**Comment by Calinou** [comment]
`NOTIFICATION_EDITOR_SETTINGS_CHANGED` can be used in `_notification()` for this purpose. Here's an example: https://github.com/godotengine/godot/blob/942f5f0cb282cbc2b3fb766e3c7614e82b98dd9b/editor/editor_help_search.cpp#L112-L114
