### ISSUE TITLE
3.2.4 RC 5 issue with dragging control nodes - seems to translate double of what I am dragging.

### ISSUE THREAD

**Issue by norlowski** [godotengine/godot#46979]
I did not see any similar reports for RC5. This was not an issue in RC4

**Godot version:**

3.2.4 RC 5
**OS/device including version:**

Windows 10 GTX1080 - in-editor

**Issue description:**

When dragging a control node from its anchor, the translation seems to be double of what my mouse drags. I can reset the anchor to, say, "center", but if I drag the node away from the center, the translation of the control node is at least 2x faster than what my mouse is moving. It moves in the same direction.

**Steps to reproduce:**
New project
Add color rect (or any control)
set anchor to center (or any anchor)
drag control
[testdrag.zip](https://github.com/godotengine/godot/files/6135449/testdrag.zip)

Gif of behavior
https://gph.is/g/4M6yy6V

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
That's my fault, I forgot to change `offsets` back to `margins` when cherrypicking this: f8ee8b1b7344db274d6830b25a9760e02de0a0a6.

That means RC 5 is pretty much broken, will have to make a new build.

**Comment by akien-mga** [comment]
Fixed by #46980.
