### ISSUE TITLE
Screen being drawn in the middle of handling an event

### ISSUE THREAD

**Issue by beamer159** [godotengine/godot#4697]
Windows 10 - Godot 2.0.3

(This issue seems to be specific to Windows operating systems. It did not show up on iOS or on Android.)

**Situation**

I have a project with 3 nodes:

1. Sprite
2. Node2D
3. Area2D (with a child shape, etc.)

Both Node2D and Area2D have a script that moves the Sprite to a different position when the mouse is clicked. Node2D does this with _input(ev) and Area2D does this with _input_event(...).

**What I expected**

If I click somewhere not on Area2D's shape, the Sprite will move directly to the position specified by Node2D. If I click on Area2D's shape, the Sprite will move directly to the position specified by Area2D. This is because events are handled by _input(ev) before _input_event(...). So the Sprite would first go Node2D's specified position, and then go to Area2D's specified position, and then finally be drawn to the screen.

**What happened**

When I click on Area2D's shape, sometimes the Sprite is drawn at Node2D's specified position for a few frames, and then moves to Area2D's specified position. This seems like an error because the mouse click event is clearly being handled by Node2D, then a screen draw occurs before the event is handled by Area2D. I thought that an event should propagate through all nodes before a screen draw happens.

**Steps to reproduce:**

In a project, add 2 nodes, one of them a CollisionObject2D. Give one an _input(ev) function and the other an _input_event(...) function. Have them both alter a sprite in a similar way, like changing its location. To really see the issue clearly, add a time-intensive loop right before the CollisionObject2D node modifies the sprite, such as an unnecessary nested for loop.

Example project demonstrating this issue: [Godot Demo.zip](https://github.com/godotengine/godot/files/270561/Godot.Demo.zip)

**Comment by reduz** [comment]
This is not a bug, this is by design. 

Physics does not run synchronized to the game loop, in fact it can run in a separate thread, including all collisions and raycasting.

As it is part of the physics engine, the _input_event function in Area2D is done during physics-main thread synchronization, so it may happen a frame after the original _input().
