### ISSUE TITLE
Viewport's "Handle Input Locally" inside ViewportContainer gets set to false after scene reload 

### ISSUE THREAD

**Issue by kuhnchris** [godotengine/godot#46982]
**Godot version:**
Godot Engine v3.2.4.rc.custom_build.ba174332a - https://godotengine.org

**OS/device including version:**
Linux (Arch), AMD, GLES3 (not relevant)

**Issue description:**
The flag on "handle_input_locally" on a Viewport within a ViewportContainer keeps getting reset to false whenever the scene is getting reloaded, despite "true" being the default option.

**Steps to reproduce:**
1. Create new project
2. Create new scene
3. Create ViewportContainer
4. Create Viewport within ViewportContainer
5. Set size so Godot is satisfied
6. Save Scene
7. Close Scene
8. Open Scene again
9. Check Viewport's handle_input_locally property

**Minimal reproduction project:**
[MinimalDemoViewportIssue.zip](https://github.com/godotengine/godot/files/6135629/MinimalDemoViewportIssue.zip)

**Comment by kuhnchris** [comment]
Could this be the potential issue?
https://github.com/godotengine/godot/blob/1d0929a992cb9b0df404ba9049fe278b6390bfae/scene/gui/viewport_container.cpp#L125
If yes, is there any reasoning for this?
Maybe I'm just not understanding ViewportContainers properly.

Thanks!

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/56502, which is more detailed.
