### ISSUE TITLE
Control Node Exponentially Large Scaling 3.2.4 RC5

### ISSUE THREAD

**Issue by DeadlyEssence01** [godotengine/godot#46981]
**Godot version:**
3.2.4 RC5 

**OS/device including version:**
N/A

**Issue description:**
Trying to scale a, control node (only tested in 2D) exponentially scales the rect. Getting to a ridiculous size quickly with a relatively short mouse movement (Less than 200 pixels right, creates a 4,000 size rect). Plus, the rect does not size back down going the opposite direction once it has hit a certain length.

**Steps to reproduce:**
Create a control node, grab the circles at the edges of the rect to resize and move mouse right, the node will scale very large quite quickly. Also, try moving the mouse left after it begins scaling exponentially, and the node will continue to scale larger. 

**Minimal reproduction project:**
[GUIBug.zip](https://github.com/godotengine/godot/files/6135595/GUIBug.zip)

**Comment by akien-mga** [comment]
Thanks for the report! It's the same issue as #46979 which I fixed already with #46980 (will be in 3.2.4 RC6).
