### ISSUE TITLE
Color tag in RichTextLabel doesn't color the first character if not at the beginning of a line.

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#46989]
**Godot version:**
4.0 master branch https://github.com/godotengine/godot/commit/dc038bd7c30e50a94f844a485e7f89f0bab0d4cf

**OS/device including version:**
Windows 10

**Issue description:**
Color tag in RichTextLabel doesn't color the first character unless if the word is is at the beginning of a new line.

![bbcode](https://user-images.githubusercontent.com/3649998/111063917-80ce1780-84b1-11eb-9080-a4dc11a1d7b5.png)

As you can see, Y is the only first character which is well colored in 4.0.
It's a regression cause everything is OK in 3.2.4 RC5
If we add a carriage return before color tags, the first word of each line is well colored.

**Steps to reproduce:**

- Setup a RichtextLabel with bbcode enable and set text as : 
- `[color=yellow]Yellow[/color][color=red]Red[/color][color=green]Green[/color][color=blue]Blue[/color]`

**Minimal reproduction project:**
[bbcode_color.zip](https://github.com/godotengine/godot/files/6136390/bbcode_color.zip)

**Comment by Calinou** [comment]
This can be seen in the editor help too.

**Comment by jmb462** [comment]
Yes, RichTextLabel is used in the HelpBit tooltip. That's the way I found this bug.

**Comment by bruvzg** [comment]
Regression from #45899, `if (offset > p_position)` ⇒ `if (offset >= p_position)` change.
