### ISSUE TITLE
Label rect_size in x only show when using rect_position

### ISSUE THREAD

**Issue by mliitfall** [godotengine/godot#46988]
Hi, when I try to print rect_size of label, it only show y size and x size is always 0, and 
when I add damageLabel.rect_position -= Vector2(0,0) it showing rect_size x and y normally.
I want to get rect_size without using rect_position.
Is it bug?
Can you guys explain this?

```
var damageLabel = Label.new()
add_child(damageLabel)
#damageLabel.rect_size = Vector2(0,0)
damageLabel.text = '3'
damageLabel.theme = Global.theme
#damage label position in y
damageLabel.rect_position -= Vector2(0, 0)
print("rect size :", damageLabel.rect_size)
```

**Comment by gongpha** [comment]
AFAIK, This is a limitation of control nodes. the `rect_size` wasn't calculated until the next frame (or maybe signal `resized` was emitted, from `damageLabel.rect_position -= Vector2(0,0)`). And well, This is not a bug. This is how Control nodes work.

Also, you can use `yield(get_tree(), "idle_frame")` to waiting for the next frame too.

**Comment by akien-mga** [comment]
Note that this is an issue tracker for bug reports, not support questions. Please use one of the other community platforms for user user support: https://godotengine.org/community
