### ISSUE TITLE
Problem with extending singleton-declared classes in Godot 3.2.4 rc5 (unless running --verbose)

### ISSUE THREAD

**Issue by takaturre** [godotengine/godot#46995]
**Godot version:**
Godot 3.2.4 rc5. This problem came with rc5, was fine in rc4 and before.

**OS/device including version:**
Windows 10.

**Issue description:**
A script can no longer extend a class declared inside a class inside a singleton. For example: `extends MySingleton.MyClasses.MyClass` now throws error, even though `MyClasses` and `MyClass` are constant declarations. However, `extends MySingleton.MyClass` would not throw error. Also if you run Godot with `--verbose`, there is no problem at all - which leads me to conclude that it's a bug. 

![image](https://user-images.githubusercontent.com/16601926/111068686-7d975380-84d2-11eb-91b8-c6e243249105.png)

**Workarounds:**
- One workaround solution is to move all the classes from `MySingleton.MyClasses` under `MySingleton`. (So you'll have to add more singletons to get over this technicality.)
- Another workaround is to reference the classes by filepath. (But then related reorganizations in the file structure will be painful.)

**Steps to reproduce:**
Follow the minimal reproduction project.
1. Basically you add a singleton (`MySingleton`).
2. Inside the singleton script, write a constant reference to a class (`MyClasses`).
  * ![image](https://user-images.githubusercontent.com/16601926/111068589-12e61800-84d2-11eb-81ee-067e8086892d.png)
3. This class in turn simply contains a collection of classes that you'd like to extend (`MyClass`). 
  * ![image](https://user-images.githubusercontent.com/16601926/111068576-02ce3880-84d2-11eb-8b15-0b8632e2e775.png)
4. Finally, extend the class from some script: `extends MySingleton.MyClasses.MyClass`. You'll get a `Parser Error: Couldn't find the subclass: MySingleton.MyClasses.MyClass`. And when you open up the project, it will open up with `Parser Error`s - unless you open Godot with `--verbose`, in which case all works fine.

**Minimal reproduction project:**
[ClassProblem.zip](https://github.com/godotengine/godot/files/6136694/ClassProblem.zip)

**Comment by akien-mga** [comment]
I tested on Linux and I can't reproduce the issue with either 3.2.4 RC 5 or a build from the current `3.2` branch.
That seems like a surprising regression as I don't recall any change between RC 4 and RC 5 that could affect this.

**Comment by KoBeWi** [comment]
I can't reproduce either on Windows. Usually editor restart helps with similar problems.

**Comment by takaturre** [comment]
Well, this is weird. I still do get the error every time and with `--verbose` not. My only uneducated guesses are:
- This could have something to do with timing. And so running -verbose somehow delays that part which initially checks whether those classes exist - without it, they are checked "too early". (Though, weird that the problem remains after starting up.)  <-- Reminding of an older "_some_singleton not declared in the current scope" bug when running the game.
- Very unlikely, but you don't happen to have some editor settings or such that could affect this ? (Or me?)

**Comment by takaturre** [comment]
Aah.. I'm terribly sorry. This is an old bug (or not yet implemented feature) of `3.2 beta5`. Messed up with shortcuts (so that's why `--verbose` worked, d'oh)..!  :O My bad, really sorry, closed the issue.
