### ISSUE TITLE
BBCode Tables overlap with bottom text

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#47012]
**Godot version:**

3.2.4-rc4

**OS/device including version:**

Windows 10

**Issue description:**

RichTextLabel using BBCode tag "[table]" doesn't push the text after the table down far enough so it overlaps with table.
![image](https://user-images.githubusercontent.com/69117768/111086971-5ba2ce80-84dc-11eb-95ae-ae3c69ccc432.png)
Sorry if this is a duplicate issue, I tried to find if this had been submitted before.

**Steps to reproduce:**
Paste this into a RichTextLabel:
```
Top text
[table=3]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[/table]
Bottom Text
```

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/6137769/test.zip)

**Comment by Anshul7sp1** [comment]
It seems to glitch only when the number of cells between the `table`  tag isn't a multiple of number of columns specified in `table=`

I would like to try and give a PR for this!

**Comment by ShatReal** [comment]
Good luck!
