### ISSUE TITLE
OSX 10.11 SDK support

### ISSUE THREAD

**Issue by nepitard** [godotengine/godot#4702]
**System info:**
Linux(compiling for OSX) - Godot 2.0.3

**Issue**:
Godot won't compile with darwin15 SDK, only with darwin14.

**Steps to reproduce:**
Try to compile with OSX 10.11 SDK.

**Comment by akien-mga** [comment]
Thanks, but it's hard to fix an issue just based on the fact that it reportedly doesn't work :)

Could you post build logs that show what the issues are?

**Comment by nepitard** [comment]
Logs:

`[user@user godot-2.0.3-stable]$ scons platform=osx bits=64
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/home/user/osxcross/target/bin/x86_64-apple-darwin14-c++ -o platform/osx/os_osx.osx.opt.debug.64.o -c -O2 -DDEBUG_ENABLED -DFREETYPE_ENABLED -DOC_X86_ASM -DAPPLE_STYLE_KEYS -DUNIX_ENABLED -DGLES2_ENABLED -DGLEW_ENABLED -DOSX_ENABLED -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DPNG_ARM_NEON_OPT=0 -Icore -Icore/math -Itools -Idrivers -I. -I/home/user/.boost_1_48_0 -Iplatform/osx -Itools/freetype -Itools/freetype/freetype/include -Imodules/godotsteam/sdk/public -Iplatform/osx/vorbis platform/osx/os_osx.mm
sh: /home/user/osxcross/target/bin/x86_64-apple-darwin14-c++: No such file or directory`

**Comment by akien-mga** [comment]
Does it build with the ``osxcross_sdk=15`` argument?

**Comment by nepitard** [comment]
It actually worked, but with `osxcross_sdk=darwin15` argument.

**Comment by akien-mga** [comment]
Thanks. We should make sure it's properly documented, and maybe default to ``darwin15`` instead of ``darwin14`` if it's the current SDK.
