### ISSUE TITLE
Can't import Game Sound into my project

### ISSUE THREAD

**Issue by GameDevAl3x** [godotengine/godot#47025]
**Godot version:**

- Godot Engine v3.2.3.stable.official

**OS/device including version:**

- GLES2

**Issue description:**

- can't import my Game Sound into my Project (.wav File)
- Error: 
      -  Failed loading resource: res://Sounds/Game Sound.wav. Make sure resources have been imported by opening the project in the editor at least once.
      -  editor/import/resource_importer_wav.cpp:110 - Method failed. Returning: ERR_FILE_UNRECOGNIZED
      -  editor/editor_node.cpp:854 - Condition "!res.is_valid()" is true. Returned: ERR_CANT_OPEN
      

**I already searched for a solution, but didn't found anything to fix this issue**

![ErrorGodot](https://user-images.githubusercontent.com/80691297/111158841-cd405280-8598-11eb-8f6d-5e3d4cd4ec27.png)

**Comment by akien-mga** [comment]
Can you share that file? Otherwise we can't debug.

**Comment by GameDevAl3x** [comment]
Guys I fixed this problem. The Problem was that my Sound File was Stereo not Mono. I changed it to Mono and it worked!
