### ISSUE TITLE
asin (sin-1) incorrect calculation , look_at on Spatial/InstanceMesh not working too

### ISSUE THREAD

**Issue by sunnydrake** [godotengine/godot#47023]
**Godot 3.2.3 official from steam**
**Win10 x64 NVIDIA RTX 2070 GLES2:**
**asin(1.571) calculation provide result 1.#QO expected 177.95 :*

run code
		var center=Vector2(0,0)
		var dd=Vector2(0,5) 
		var dp=Vector2(-0.313,-8.746)
		var disdd=center.distance_to(dd) #5
		var disdp=center.distance_to(dp) #8.751
		var disdddpdiff=dd.distance_to(dp) #13.749
		var div=disdddpdiff/disdp #1.571
		var angle=asin(div) .#QO expected 177.95
		print(angle)

Screenshots attached 
![image](https://user-images.githubusercontent.com/15017432/111156610-9ec57600-859e-11eb-8d35-5132009663cf.png)
![image](https://user-images.githubusercontent.com/15017432/111156631-a5ec8400-859e-11eb-9db6-15154d8ae3be.png)

**Comment by jmb462** [comment]
asin() parameter must be between -1 and 1 and the return value is in radian (between -PI/2 ans PI/2)
