### ISSUE TITLE
High CPU usage in editor and project when running the game

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#47026]
**Godot version:**
Godot 4.0-dev (6eef187a81)

**OS/device including version:**
Arch Linux - Ryzen 7 2700X - Radeon RX 480

**Issue description:**
When playing the game from the editor, both the editor and the played game consumes a high amount of CPU time (over 100% of a core each). Doesn't happen in the editor when idle nor running the project directly without the editor.

The editor is using about 60% already when idle, then goes up to 160% when running the game.

**Steps to reproduce:**
- Create a new empty project with an empty main scene.
- Run the project from the editor.

**Minimal reproduction project:**
Not needed, reproducible with an empty project.

**Comment by Faless** [comment]
Seems related to the debugger network threads that are quire wasteful in terms of resources. I'll work on some optimization that should greatly improve the performances (still won't be the same though :) )

**Comment by mrjustaguy** [comment]
Similar to, and possibly related to #42251

**Comment by Faless** [comment]
> Similar to, and possibly related to #42251

Very unlikely, that seem just a windows bug on assigning/keeping process ids

**Comment by mrjustaguy** [comment]
It could be that the error msg from the issue isn't related to the issue and just being falsely connected to the underlying problems which are mostly as described here:

Running Project in Editor -> Massive CPU usage & horrible performance (and on a weak system taking several minutes just for the game window to appear)

Running Project outside the Editor -> Expected CPU usage & performance
