### ISSUE TITLE
Custom editor themes are reset to standard theme after closing editor settings.

### ISSUE THREAD

**Issue by DmitriySalnikov** [godotengine/godot#47035]
**Godot version:**
starting from c655fc7cd89d17eb858b3c99e82402de61571bb0

**OS/device including version:**
Any

**Issue description:**
![Very good gif to show issue. I cant write normal description](https://user-images.githubusercontent.com/7782218/111194922-bd426600-85cc-11eb-99ac-513d8dc8f4ed.gif)

**Steps to reproduce:**
1. Change custom editor theme
2. Reopen editor
3. Open editor settings
4. Close editor settings

**Minimal reproduction project:**
[Editor Theme.zip](https://github.com/godotengine/godot/files/6143147/Editor.Theme.zip)

The problem is introduced here:

https://github.com/godotengine/godot/commit/c655fc7cd89d17eb858b3c99e82402de61571bb0#diff-b88f0bde58b731e8dd353707c8011fb7a1e452f0db2c9f15f4b7905d60e5e52eL287-R286

https://github.com/godotengine/godot/blob/3.2/editor/editor_node.cpp#L543
Here must be `create_custom_theme` instead of `create_editor_theme`

**Comment by a3p169** [comment]
This is happening in 3.3 stable. Should I open another issue? There's also bunch of other problems with theme related to fonts.

**Comment by a3p169** [comment]
Here's the theme file.
[material.zip](https://github.com/godotengine/godot/files/6426198/material.zip)

**Comment by DmitriySalnikov** [comment]
fixed by #48667 5 month ago...
