### ISSUE TITLE
Cut+Paste in TileMap editor causes random tiles to disappear

### ISSUE THREAD

**Issue by nebs** [godotengine/godot#47039]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**

Windows 10 PC. NVidia GTX1660. Using GLES3.

**Issue description:**
In the Godot editor, when editing a TileMap, sometimes when you cut + paste a selection of tiles it causes other random unreleated tiles to disappear.

Expected: Cutting and pasting tiles should not cause other unrelated/unselected tiles to be modified in any way.

![tilebug](https://user-images.githubusercontent.com/2637098/111219649-ab51ca80-85ae-11eb-847f-cc2276a45a56.gif)

**Steps to reproduce:**
1) Open the attached demo project (you don't have to run the project, the bug can be reproduced in the editor)
2) In the Main scene, select the TileMap node
3) Press "M" to enter tile selection mode
4) Draw a region around the tile rectangle on the right. Make sure to select a bit more than the tiles (see gif)
5) Press "Ctrl + X" to cut the tile selection
6) Click in random places around to paste the selection multiple times
7) Notice how some random tiles from the center set of tiles start to disappear (see gif).

It's not clear exactly where you need to paste, so try cutting + pasting multiple times in different spots until you notice tiles disappearing from the center. 

**Minimal reproduction project:**
[TileMapBugDemo.zip](https://github.com/godotengine/godot/files/6144371/TileMapBugDemo.zip)

**Comment by AndyBarcia** [comment]
Can confirm, and in 3.2.4 too. And the same thing happens when copying.
Also, the tiles that dissapear aren't actually random. When you paste the selection in two neighboring tiles, two neighboring tiles will disappear.

Maybe something wrong with TileMapEditor::_update_copydata?

```
TileData tcd;

tcd.cell = node->get_cell(j, i);
if (tcd.cell != TileMap::INVALID_CELL) {
  tcd.pos = Point2i(j, i);
  tcd.flip_h = node->is_cell_x_flipped(j, i);
  tcd.flip_v = node->is_cell_y_flipped(j, i);
  tcd.transpose = node->is_cell_transposed(j, i);
  tcd.autotile_coord = node->get_cell_autotile_coord(j, i);
}

copydata.push_back(tcd);
```

I don't know if the fact that the tile is added to copydata even if it's invalid have something to do with it. But I can't test it right now.

**Comment by AndyBarcia** [comment]
Seems about right.
By the way, I was planning of fixing this, maybe tomorrow or so, as it seems easy enough. 

Although I find it curious that non one had reported or fixed this before, as it seems quite a big problem with the copy and paste system.

**Comment by Bogunovich** [comment]
Here are two possible solutions for testing, depending on the desired functionality.

Solution 1: allow the user to copy blank (invalid) cells.
Shown below by removing the if statement on line 963

![solution1](https://user-images.githubusercontent.com/53198139/111549247-d9b7dd00-8749-11eb-8d3d-45304604ba00.png)
![solution1example](https://user-images.githubusercontent.com/53198139/111551216-b727c300-874d-11eb-986e-274383474c63.png)

Solution 2: only call _set_cell( ) for those cells which are not invalid.
Shown below by introducing a new if statement on line 1138

![solution2](https://user-images.githubusercontent.com/53198139/111549721-b0e41780-874a-11eb-9e10-0ac2fd9d7140.png)
![solution2example](https://user-images.githubusercontent.com/53198139/111551223-ba22b380-874d-11eb-90b1-4e5ca44597c6.png)

**Comment by AndyBarcia** [comment]
I have checked it, and programs like gimp also don't copy blank tiles. And given that that's also the way that it (kind of) worked in godot. I say that we should go with solution2.
But I think that a more efficient solution would be to only move to copydata valid cells:

```
 TileData tcd;

tcd.cell = node->get_cell(j, i);
if (tcd.cell != TileMap::INVALID_CELL) {
  tcd.pos = Point2i(j, i);
  tcd.flip_h = node->is_cell_x_flipped(j, i);
  tcd.flip_v = node->is_cell_y_flipped(j, i);
  tcd.transpose = node->is_cell_transposed(j, i);
  tcd.autotile_coord = node->get_cell_autotile_coord(j, i);
  
  copydata.push_back(tcd);
}
```
