### ISSUE TITLE
SceneTree's tree_changed signal causing problem with the Script editor's member list

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#47030]
**Godot version:**
6eef187

**Issue description:**
Opening, switching, and closing scripts/docs generally causes the member list to not be updated:
![Screenshot](https://user-images.githubusercontent.com/30739239/111173712-c6b4d980-859e-11eb-93c5-992b74aaf4c9.png)

This issue is caused by the SceneTree's `tree_changed` signal firing on `master` in situations that it didn't back in the `3.*` branch, causing [`ScriptEditor::_tree_changed()`](https://github.com/godotengine/godot/blob/6eef187a81cbdd3cd314776de372e753f79f9831/editor/plugins/script_editor_plugin.cpp#L2522) to be called and setting `waiting_update_names` to `true`, stopping [this update here](https://github.com/godotengine/godot/blob/6eef187a81cbdd3cd314776de372e753f79f9831/editor/plugins/script_editor_plugin.cpp#L2058).

**Comment by KoBeWi** [comment]
Is this still happening? Never seen this issue.

**Comment by YeldhamDev** [comment]
I currently don't have much time to test this specifically, sorry.

**Comment by KoBeWi** [comment]
So let's say it's resolved.

**Comment by YeldhamDev** [comment]
Alright, I encountered the bug again. Having the first thing selected in the script editor being a doc page when first opening the project doesn't show the categories in the list.
