### ISSUE TITLE
Scaling a HeightMapShape CollisionShape (3D) results in incorrect collision calculations

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#47034]
**Godot version:**
Godot 3.2.3

**OS/device including version:**

Arch Linux

**Issue description:**
When you scale the transform of a CollisionShape, that has a HeightMapShape assigned as the shape, the scaling doesn't seem to make any difference in physics, only rendering.
![godot-scaling-bug](https://user-images.githubusercontent.com/25486263/111194916-59b43a80-85c4-11eb-9171-315bbba13b8a.gif)

**Minimal reproduction project:**
[scaling-bug.zip](https://github.com/godotengine/godot/files/6143281/scaling-bug.zip)

**Comment by Calinou** [comment]
Collision shapes aren't meant to be scaled. This isn't exclusive to HeightMapShape.

**Comment by PonasKovas** [comment]
I thought about that but it seems to work with BoxShape

**Comment by PonasKovas** [comment]
Either way, I don't know about the technical side but if they're not meant to be scaled that seems kind of counter-intuitive and can be troublesome for new users, in my opinion.

**Comment by Calinou** [comment]
> Either way, I don't know about the technical side but if they're not meant to be scaled that seems kind of counter-intuitive and can be troublesome for new users, in my opinion.

See https://github.com/godotengine/godot/issues/32975.
