### ISSUE TITLE
servers/visual/visual_server_scene errors on scene changes in 3.2.4.RC5

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#47051]
**Godot version:**

3.2.4.RC5

**OS/device including version:**

Windows 10, GTX970, Happens both on GLES2 and GLES3

**Issue description:**

When changing back and forth between scenes and sometimes just selecting nodes with my Shell Fur tool open I'm getting various visual server errors and sometimes MeshInstances are no longer getting rendered until I reopen a scene. None of these errors occur in 3.2.3.Stable, but happen consistently in 3.2.4.RC5.

 ./core/rid.h:150 - Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
 servers/visual/visual_server_scene.cpp:629 - Condition "!instance" is true.
 ./core/rid.h:150 - Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
 servers/visual/visual_server_scene.cpp:713 - Condition "!instance" is true.
 ./core/rid.h:150 - Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
 servers/visual/visual_server_scene.cpp:780 - Condition "!instance" is true.
 ./core/rid.h:150 - Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
 servers/visual/visual_server_scene.cpp:913 - Condition "!instance" is true.

![image](https://user-images.githubusercontent.com/4955051/111286908-9a4e9b00-863a-11eb-9c92-781a7f0759d0.png)

**Steps to reproduce:**
Clone https://github.com/Arnklit/ShellFurGodot and open test_assets/sample_scene.tscn and test_assets/test_suite.tscn and go back and forth between the scenes selecting objects.

**Minimal reproduction project:**
Sorry I have been unable to create a simple repro project. I'll update the bug if I figure out how to.

**Comment by akien-mga** [comment]
I can't seem to reproduce those errors in 3.2.4 RC 5 here on Linux with AMD Vega M discrete GPU.

I do get this error when switching quickly between the two scenes, but that's probably a bug in the Shell Fur code since it updates each time the scene is shown (and switching quickly can mean switching before it finished updating):
```
ERROR: get_global_transform: Condition "!is_inside_tree()" is true. Returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition "!is_inside_tree()" is true. Returned: Transform()
   At: scene/3d/spatial.cpp:265.
```

**Comment by Arnklit** [comment]
Hmmm that is really strange. Thanks so much for testing. I'm not sure what is causing it then. I'll try and check it on my Win10 machine with Intel 630 graphics.

I'll update with more info soon.

**Comment by Arnklit** [comment]
I am unable to reproduce on my second windows machine on 3.2.4.RC5 which has an Intel 620 integrated GPU. 

I'll try and do a driver rollback on my desktop, I belive I recently updated to latest NVidia driver. Not sure what else to try.

**Comment by Arnklit** [comment]
OK, maybe this was all just a bad dream i had. Turned out there was a newer driver actually for my GTX970. I updated, ran the project and can no longer repro. Closing, very sorry for the trouble!

**Comment by mbrlabs** [comment]
I'm having the same issue (both errors) with my project but i can't reproduce it reliably yet. It only happens sometimes inside the editor when switching or opening scenes. The earliest version with that issue appears to be 3.2.4 beta3.

I'm trying to create a MRP.

**Comment by mbrlabs** [comment]
Yeah, i had no luck either. Yesterday i spent waaay too long trying to make an MRP but to no avail. I suspected it had something to do with materials specifically ShaderMaterials, but i'm not sure anymore..
