### ISSUE TITLE
Line2D.points.append( Vector2 ) not work correctly

### ISSUE THREAD

**Issue by HerrCai0907** [godotengine/godot#47060]
**Godot version:**

v3.2.3.stable.official

**OS/device including version:**

GLES2

**Issue description:**

Line2D.points cannot use append()
when I use points.append(A), nothing happened. (in the comment part of following code)

```
	extends Line2D
	const WIDTH = 2
	#const star_line_texture := preload("res://image/star.png")
	func _init(A:Vector2,B:Vector2):
		width = WIDTH
# correctly set Line2D.points
		var point :PoolVector2Array= []
		point.append(A)
		point.append(B)
		points = point

# nothing happened for Line2D.points
#		points = []
#		points.append(A)
#		points.append(B)
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Try doing this in `func _ready()` instead of `func _init()`.

**Comment by HerrCai0907** [comment]
> Try adding points in `func _ready()` instead of `func _init()`. `_init()` is called _before_ the node is fully ready, and this may cause problems in specific cases.

I have tried again but useless.

example
```
extends Line2D
func _ready():
	self.points = []
	self.points.append(Vector2(0,0))
	self.points.append(Vector2(100,100))
	print("1: ",self.points)
	
	var tmp:PoolVector2Array = []
	tmp.append(Vector2(0,0))
	tmp.append(Vector2(100,100))
	self.points = tmp
	print("2: ",self.points)
```
output
```
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 1650/PCIe/SSE2
OpenGL ES 2.0 Batching: ON
 
1: []
2: [(0, 0), (100, 100)]
```

**Comment by Xrayez** [comment]
This is expected, because `PoolVector2Array` is passed by value rather than reference in 3.2. It's not the case in 4.0 anymore. But not sure whether this would work in 4.0 in all cases, since setting a property may do something else as well as assigning the value, like calling `update()` callback, in which case you'd need to call it yourself in 4.0. (?)

So I suggest always making a copy (the second case in your snippet):

```gdscript
var tmp:PoolVector2Array = []
tmp.append(Vector2(0,0))
tmp.append(Vector2(100,100))
self.points = tmp
```

See also #17896.

**Comment by Calinou** [comment]
For reference, caveats of Pool*Array being passed by value are now documented in https://github.com/godotengine/godot/pull/59637.
