### ISSUE TITLE
3.2.4 breaks onMainRequestPermissionsResult callback for Android Plugins

### ISSUE THREAD

**Issue by minosvasilias** [godotengine/godot#47073]
**Godot version:**
3.2.4-rc5 (also tested 3.2.4-rc3)

**OS/device including version:**
Android 7, LG-H850

**Issue description:**
Moving from 3.2.3-stable to 3.2.4 the `onMainRequestPermissionsResult` function in my Android plugins has stopped being called. 

The relevant plugin code looks like this:

```javascript
public class PluginName extends GodotPlugin {

    private Activity activity;
    private permissionName = Manifest.permission.READ_EXTERNAL_STORAGE; //Which permission is being requested makes no difference
    private requestCode = 107;

    
    public PluginName(Godot godot) {
        super(godot);
        activity = getActivity();
    }
    
    public void onMainRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        //This never gets called
    }
    
    public void askForPermission(String permissionName, int requestCode) {
        ActivityCompat.requestPermissions(activity, new String[] {permissionName}, requestCode);
    }
}
```

This works perfectly when running 3.2.3-stable. 
In 3.2.4, the permission still gets requested, the dialog pops up when testing, and confirming the dialog does indeed grant the permission successfully. It's just the `onMainRequestPermissionsResult` callback that never comes through, meaning the Plugin never finds out if the request was successful, which is quite important for the flow of a bunch of my plugins.

Both for 3.2.3-stable and 3.2.4 i use their respective unmodified Android Build Templates.

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
@minosvasilias You should be able to use `getGodot().requestPermissions(....)` for both 3.2.3 and 3.2.4 and it should work as expected.

**Comment by minosvasilias** [comment]
@m4gr3d Thanks, that does work, but it appears to require upping the minSdk version in the build template to at least 23 (Marshmallow) from the default 18.

**Comment by m4gr3d** [comment]
@minosvasilias I'll also add a fix to support your original code. We want to maintain backward compatibility as they may be plugins that don't get updated in time which would cause a loss of functionality for users.

**Comment by m4gr3d** [comment]
@minosvasilias The fix should be in the latest RC. Can you double-check that your original code works as expected.

**Comment by minosvasilias** [comment]
@m4gr3d Everything working as expected now. Thank you!
I had since encountered a related issue where `onMainActivityResult` wasn't being called either (while implementing the Facebook SDK), but i can see you fixed that in the same commit as well. Working perfectly with the latest RC.

**Comment by minosvasilias** [comment]
Coming back to this again since it looks like i need to correct myself.

While the original code using `ActivityCompat.requestPermissions` and `ActivityCompat.startActivityForResult` now indeed does successfully result in `onMainRequestPermissionsResult` and `onMainActivityResult` being called, the `getGodot().requestPermissions` and `getGodot().startActivityForResult` calls @m4gr3d suggested are **not** working anymore when running rc7 (while they do work in rc5). So it seems we now have a reversal of the original rc5 issue.

**Comment by akien-mga** [comment]
Note that there's a bug until 3.3 RC 8 which could cause a crash when asking for permissions (see #46832), I don't know if that's related to your issue (doesn't sound like you're having a crash, just API issues).

**Comment by minosvasilias** [comment]
@akien-mga Thanks, but it seems that is unrelated to my issue.

I've had some time to properly test this and have attached a minimal reproduction project below. I've included an Android plugin project as well. (same structure as the [godot-google-play-billing](https://github.com/godotengine/godot-google-play-billing) plugin, copy godot-lib.***.release.aar into the libs folder to build). Prebuilt plugin .aar is already included in the godot project.

The issue with `getGodot().requestPermissions` and `getGodot().startActivityForResult` from rc6 onwards is not that `onMainRequestPermissionsResult` and `onMainActivityResult` aren't being called, they are, but the returned **requestCode** parameter does not correspond to the one that was passed to the `getGodot().requestPermissions`, `getGodot().startActivityForResult` calls, meaning some of my plugins were ignoring those callbacks. The returned requestCode appears to be changing on every call.

To make it absolutely clear what the behavior of each RC when running the minimal reproduction project is:

| Release        | ActivityCompat Behavior           | getGodot() Behavior  |
| ------------- |:-------------:| -----:|
| rc5      | onMainRequestPermissionsResult **not** called | onMainRequestPermissionsResult called, **correct** requestCode |
| rc6, rc7, rc8      | onMainRequestPermissionsResult called, **correct** requestCode      |  onMainRequestPermissionsResult called, **wrong** requestCode |

**Project:**
[godot_issue_mrp.zip](https://github.com/godotengine/godot/files/6278008/godot_issue_mrp.zip)

**Comment by m4gr3d** [comment]
Thanks for the detailed update @minosvasilias! I'll take a look at the issue.

**Comment by m4gr3d** [comment]
@minosvasilias So looking at the implementation, it turns out the Android system makes both the `ActivityCompat` and the `getGodot()` implementations go through the same pipeline but in the case of the `getGodot()` implementation, the `requestCode` is modified with information to classify where it comes from.

As such when the response is received, the result needs to go through a similar pipeline in order to get the callback with the correct `requestCode`. In my current implementation, I am short-circuiting  that pipeline leading to the callback with the invalid `requestCode`.

The fix will follow two approaches:
- For the `3.x` branch, since we're keeping backward compatibility, my original changes will be maintained but modified so as to no longer short-circuit the other pipeline: 
  - This will maintain the behavior of forwarding the callback when invoking with `ActivityCompat`.
  - When invoking with `getGodot()`, this will cause two callbacks to be received, but only one of them will have the correct `requestCode`.
- For the `master` branch, since we're not worried about backward compatibility, support for `ActivityCompat` will be removed, and so using `getGodot()` instead for requesting permissions will be required.

**Comment by minosvasilias** [comment]
@m4gr3d Thanks for getting to the bottom of this! :)

The only thing i'd maybe note in regard to only supporting `getGodot()` calls for the `master` branch is that these functions may be called by third party APIs when building a plugin. As an example, the [Facebook SDK](https://github.com/facebook/facebook-android-sdk) is calling `startActivityForResult` in a whole bunch of places and expecting devs to return the `onActivityResult` values back to the SDK as per their [documentation](https://developers.facebook.com/docs/facebook-login/android/v2.2#9--register-a-callback). I believe something similar may be true for the Google Sign In API as well. 
Removing `ActivityCompat` support might result in future problems concerning implementations of things like that.

**Comment by m4gr3d** [comment]
@minosvasilias That's a very good point, thanks for the feedback!
In that case it seems we may need to replicate the same behavior in `master` as we do in the `3.x` branch.
Do you see any issues with that approach?

**Comment by minosvasilias** [comment]
@m4gr3d I don't, that sounds like the way to go! 👍 
The double callback i do not think should be cause for any problems since checking for a matching `requestCode` i expect would be standard practice anyway.
