### ISSUE TITLE
Error while reading .scn file

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#47071]
**Godot version:**

3.2.4 rc 94a0fc47f7

**OS/device including version:**

Kubuntu 20.10

**Issue description:**

below error occurred every `.scn` file
```
ERROR: get_buffer: Condition "!p_dst" is true. Returned: -1
   At: core/io/file_access_compressed.cpp:305.
```

**Steps to reproduce:**
1. create a scene
2. save it with `.scn` extension
3. run it or reopening it

**Minimal reproduction project:**

[Test Empty Project.zip](https://github.com/godotengine/godot/files/6151564/Test.Empty.Project.zip)

**Comment by volzhs** [comment]
looks regression from 5a882a659a 
cc @akien-mga

**Comment by akien-mga** [comment]
CC @W4RH4WK.

I had a look and the code that parses Variants from binary files expects a null ptr and length 0 to be a valid input to `get_buffer()`:
https://github.com/godotengine/godot/blob/master/core/io/resource_format_binary.cpp#L431-L449

We could add checks everywhere to prevent calling `get_buffer()` with a length of 0, but I think it's simpler to improve the checks added in #46810 instead. Maybe replacing `!p_dst` by `!p_dst && p_length > 0`?
