### ISSUE TITLE
albedo_textures that are LargeTextures can't be applied to Meshes

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot#47075]
**Godot version:**

3.2.3.stable.official

**OS/device including version:**

OS: Arch Linux (I don't know how to give a version for this)
CPU: x86_64 AMD Ryzen 5 3600
GPU: ASRock Radeon RX 580
Backend: GLES2 and GLES3

**Issue description:**

Setting a SpatialMaterial's albedo_texture to a LargeTexture doesn't cause the Texture to appear on a Mesh. Instead, Godot acts like the albedo_texture is completely transparent.

**Steps to reproduce:**
1. Create a MeshInstance.
1. Set the MeshInstance's mesh to any Mesh.
1. Set the MeshInstance's material_override to a new SpatialMaterial.
1. Set the SpatialMaterial's albedo_texture to a LargeTexture.

**Minimal reproduction project:**

[large_albedo_texture.zip](https://github.com/godotengine/godot/files/6151769/large_albedo_texture.zip)

**Comment by Calinou** [comment]
I'm not sure which state LargeTexture is in. It may not be supported in 3D at all.
