### ISSUE TITLE
Godot 4 - Condition "!process_map->has(p_pid)" is true

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#47087]
Noticed in #42251 however wasn't what was causing the major issue that was noted there, and the error (in that and now this issue) are separate, as such opted to open a Dedicated Issue for this error, as most of the data from the old issue isn't related and was actually #47026 which is now fixed.

**Godot version:**

First Observed in Godot Engine v4.0.dev.calinou.160ad23e5
Still present in newest builds at the time of writing.

**OS/device including version:**

Windows 10, Vulkan, Quadro k2000 452.06

**Issue description:**

Dropped an error when Scene was terminated in the editor, aside from that there have been no indications of anything going wrong and everything worked as expected.

**Steps to reproduce:**
1. Create a scene of any kind
2. Run Scene
3. Kill Scene
4. Read debugger -> platform/windows/os_windows.cpp:485 - Condition "!process_map->has(p_pid)" is true. Returning: FAILED

**Minimal reproduction project:**

Not Project Specific

**Comment by sairam4123** [comment]
I can confirm this bug, it's still doesn't seemed to be fixed.

**Comment by mhilbrunner** [comment]
Can confirm this still occurs with master as of b1eee24e2673b4a980a6f661511ff0f18c2fff8a on Windows 10.
