### ISSUE TITLE
2d skinning errors when reading VERTEX in custom shader

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#47103]
**Godot version:**

3.x 5d8ae492ba50071de3b7b4cc8fce8f6fc220f019 (17 March 2021)

**OS/device including version:**

Any

**Issue description:**

Using 2d skinning with batching resulted in deviations from the non-batching renderer, both using software and hardware skinnings.

![arm_wrong_place](https://user-images.githubusercontent.com/21999379/111499648-0fa19500-873b-11eb-88fe-646d7dda3355.png)

**Steps to reproduce:**
Make skinned poly. Apply vertex shader such as:
```
VERTEX = VERTEX;
```

**Minimal reproduction project:**

[edaojs_skinning_moving.zip](https://github.com/godotengine/godot/files/6157822/edaojs_skinning_moving.zip)

**Comment by akien-mga** [comment]
Fixed by #47102.
