### ISSUE TITLE
"Move to Trash" does not move files to Recycle Bin on Windows under specific configuration

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#47106]
**Godot version:**
3.2.4 rc

**OS/device including version:**
Windows 10

**Issue description:**
Godot does not move files to Recycle Bin when a file is deleted from the filesystem dock with the "Move to Trash" menu option, and when the Recycle Bin is configured so that files are not placed inside Recycle Bin (via "Properties").

Originally showcased by @aaronfranke in https://github.com/godotengine/godot-proposals/issues/2460#issuecomment-800822287.

**Steps to reproduce:**

*Make sure you're configuring the drive where Godot project is located.*

## Move to Recycle bin (expected)

![image](https://user-images.githubusercontent.com/17108460/111503865-d1fb3700-874f-11eb-942d-f266971aebca.png)

![image](https://user-images.githubusercontent.com/17108460/111504092-ffe07b80-874f-11eb-957a-91aaf06b709a.png)

![image](https://user-images.githubusercontent.com/17108460/111504636-8ac17600-8750-11eb-9ac7-ce5de747ed4e.png)

![image](https://user-images.githubusercontent.com/17108460/111504702-9745ce80-8750-11eb-9ba5-cd9462ae55c2.png)

## Do not move to Recycle bin (not expected)

![image](https://user-images.githubusercontent.com/17108460/111503915-daec0880-874f-11eb-9afd-c2640bdaa8f3.png)

![image](https://user-images.githubusercontent.com/17108460/111504092-ffe07b80-874f-11eb-957a-91aaf06b709a.png)

![image](https://user-images.githubusercontent.com/17108460/111504636-8ac17600-8750-11eb-9ac7-ce5de747ed4e.png)

![image](https://user-images.githubusercontent.com/17108460/111504778-a6c51780-8750-11eb-86ec-0d216724a9ed.png)

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
The message can just be edited to clarify that this depends on having the system trash actually enabled...

**Comment by Xrayez** [comment]
Yes, I see two possible solutions to this:
1. Make `OS.move_to_trash` work on Windows in a way that detects this kind of configuration, and rename the action to either "Delete" or "Move to Trash" depending on Recycle Bin configuration.
2. Just rename "Move to Trash" back to "Delete" on Windows for all cases, because that's the default name for this action in Windows' context menu. See godotengine/godot-proposals#2463.

**Comment by akien-mga** [comment]
>     Just rename "Move to Trash" back to "Delete" on Windows for all cases, because that's the default name for this action in Windows' context menu. See godotengine/godot-proposals#2463 (that's the easiest solution).

Nice try, but that doesn't solve the issue, since there's a ln explicit mention to what the option does in the confirmation dialog shown in your screenshot.

**Comment by Xrayez** [comment]
I'm not excluding additional usability enhancements which can be done after the bug fix, I'm saying that it would be enough to revert to previous state on Windows (having "Delete" instead of "Move to Trash"), because current behavior is buggy, and is an actual bug from the user standpoint.

The proper fix to this would entail all proposed enhancements, of course.

**Comment by Anshul7sp1** [comment]
I think a change like this would be intuitive enough for an average user....no?
![image](https://user-images.githubusercontent.com/52310272/111598856-a6cb2300-87f5-11eb-9a00-ba32c34d0799.png)


Then again, for a "Windows only" user, the term "recycle bin" would be far more familiar and hence he/she would be clearer of what will be the result.

**Comment by Vignesh1-art** [comment]
> I see two possible solutions to this:
> 
> 1. Make `OS.move_to_trash` work on Windows in a way that detects this kind of configuration, and rename the action to either "Delete" or "Move to Trash" depending on Recycle Bin configuration.
> 2. Just rename "Move to Trash" back to "Delete" on Windows for all cases, because that's the default name for this action in Windows' context menu. See [Rename "Move to Trash/Recycle Bin" back to "Delete" on Windows godot-proposals#2463](https://github.com/godotengine/godot-proposals/issues/2463) (that's the easiest solution).

Can you tell how? `OS.move_to_trash` is called after popup is already displayed right?

**Comment by Vignesh1-art** [comment]
I searched a bit ,  there is no any clean way to check for recycle bin configuration in windows. I think this issue need to be closed with updated message , nothing much can be done.

**Comment by Xrayez** [comment]
I don't know how to be honest, but it would be quite surprising to figure out that Windows API does not have a way to check this programmatically. The way I see it, Godot could have `OS.can_move_to_trash()` method. By default, it would return `true` for all platforms.

**Comment by akien-mga** [comment]
I think that implementing OS specific APIs just for the sake of updating a message that doesn't even need to mention what will happen to the file would really be overkill.

I'll just change the message.
