### ISSUE TITLE
File.store_string ignore " when saving

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#47117]
**Godot version:**
4.0.dev.custom_build. e57f6e2cc
This works in 3.2 branch

**Issue description:**
```
	var file : File = File.new()
	file.open("res://txt.txt", File.WRITE)
	file.store_string("""
	Save a little things 123!@#456$%^7890&*()
	"{}|:<>?\'
	""")
```
doesn't save `"` to file
Things inside file after saving
```
	Save a little things 123!@#456$%^7890&*()
	{}|:<>?'
```
As workaround `\"` can be used

**Comment by dalexeev** [comment]
> As workaround `\"` can be used

Is this a bug in GDScript 2.0 and not in the `File` class? (I can't check this right now.)
