### ISSUE TITLE
Unable to start Godot after building on MacOS (mscorlib.dll.dylib is unusable)

### ISSUE THREAD

**Issue by KuroiRoy** [godotengine/godot#47118]
**Godot version:**
I tried compiling the following versions and running into the problem every time.
Godot 3.x - 7f2107ebfd4cf470e9b4c5fc28a32b6f22a1b7df
Godot 3.2 - 94a0fc47f7b4e90f8973f9adbfd3312579ed2825
Godot master - 6eef187a81cbdd3cd314776de372e753f79f9831

**OS/device including version:**
macOS Catalina

**Issue description:**
I'm trying to compile Godot to try using a c++ library. The Godot application compiles fine. But when I run it the program crashes with this in the terminal:
`ERROR: _load_api_assemblies: Failed to load one of the prebuilt API assemblies.
   At: modules/mono/mono_gd/gd_mono.cpp:930.` 

And this in the mono_logs:
`Config attempting to parse: '/Library/Frameworks/Mono.framework/Versions/Current/etc/mono/config'. (in domain Mono, info)
Config attempting to parse: '/Users/[user]/.mono/config'. (in domain Mono, info)
Image addref mscorlib[0x7fdfc3cd2e80] (asmctx DEFAULT) -> /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/mscorlib.dll[0x7fdfc5b75000]: 2 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/mscorlib.dll) (in domain Mono, info)
AOT: module /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/mscorlib.dll.dylib is unusable: compiled against runtime version '6.12.0.114 (2020-02/5e9cb6d1c1d Thu Dec 10 04:55:48 EST 2020)' while this runtime has version '6.12.0.114 (2020-02/5e9cb6d1c1d)'. (in domain Mono, info)
Assembly mscorlib[0x7fdfc3cd2e80] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Assembly mscorlib[0x7fdfc3cd2e80] added to domain GodotEngine.Domain.Scripts, ref_count=2 (in domain Mono, info)
`

**Steps to reproduce:**
Thats hard to say. I have tried multiple Mono versions and multiple Godot versions but nothing seems to help.

**Comment by Calinou** [comment]
@KuroiRoy Are you on an x86 or ARM-based Mac? Are you building the Godot editor or an export template?

**Comment by KuroiRoy** [comment]
@Calinou I'm on a x86 Mac. I'm building the Godot editor.
Currently I have Mono 6.12.0.114 installed from https://github.com/godotengine/godot-mono-builds 
I've also tried building Mono using https://github.com/godotengine/godot-mono-builds which also successfully compiled the editor but was unable to run with the same issue.

**Comment by KuroiRoy** [comment]
Okay, so apparently I missed something about the folder structure of the resulting .app. I read [here](https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html#editor) that one of the Mono folders has to go in Resources instead of Frameworks. However simply moving it didn't work. 

Then I tried copying the whole GodotSharp folder from Frameworks to Resources and that worked. The editor is running now, I just don't know what it was or why it produced this specific error message

**Comment by akien-mga** [comment]
Right, this documentation needs to be updated, the packaging changed recently with #43768.

**Comment by akien-mga** [comment]
I opened an issue on the docs repo: https://github.com/godotengine/godot-docs/issues/4776

So I guess this issue can be closed. Thanks for the report!
