### ISSUE TITLE
Measurements are difficult with new infinite grid

### ISSUE THREAD

**Issue by likeich** [godotengine/godot#47110]
**Godot version:**
3.2.4 RC 5

**OS/device including version:**
Linux

**Issue description:**
Scale is almost impossible to judge with the new infinite grid. Before, I could use the grid to judge 1x1 meter distances so I could build maps based on that scale. Now that the grid gets infinitely smaller it's almost impossible to judge that scale because it's constantly shifting. The only workaround I've found is to create a 1x1 csg mesh that I leave floating, but having the grid stop shrinking at 1x1 meter squares would be better.

| New Grid | Old Grid |
| --------- | ---------- |
| ![Screenshot from 2021-03-17 13-54-16](https://user-images.githubusercontent.com/57882701/111514630-4de18900-8728-11eb-801f-c753c9fc0678.png) | ![Screenshot from 2021-03-17 13-58-09](https://user-images.githubusercontent.com/57882701/111515292-ff80ba00-8728-11eb-8b9d-848b32c1078f.png) |
| Zooming in without this 1x1 block will make users lose track of the scale. | The old grid stops at 1x1 so it can be used for scale. |

Making maps to realize that they are 1/10th the size I need is frustrating. The new grid is great besides for this issue.

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
> but having the grid stop shrinking at 1x1 meter squares would be better.

The downside is that we lose the ability to make precise adjustments when we're zoomed in. Maybe a compromise would be to change the grid color depending on the zoom level.

**Comment by JotaFaD** [comment]
Major lines (every meter) and minor lines could use different colors. I don't think having different colors for each zoom level is necessary.

**Comment by likeich** [comment]
> The downside of doing this is that we lose the ability to make precise adjustments when we're zoomed in. Maybe a compromise would be to change the grid color depending on the zoom level, so that you keep the precise grid while still being able to determine the grid subdivision level you're currently at.

That's understandable. I think colors for the major lines could be a decent solution as Jota said. As long as there's some easy way to distinguish 1x1 meter lines then I'm happy.

**Comment by JFonS** [comment]
You could also tweak the "Grid Division Level Min" and "Grid Division Level Max" settings under "Editor Settings -> Editor -> 3D" to only show the grid in a specific division level. 

For example setting them both to 0 will set the minor lines every meter and the major lines every 8 meters (by default, depends on the primary grid steps setting).

**Comment by likeich** [comment]
That division level setting works, I think the idea to color the 1-meter lines would be good too. 

I'm not sure the factors that went into the default setting for the grid division level but 0 for both would be better in my opinion; going lower than that is probably more niche.
