### ISSUE TITLE
Blend shapes are glTF2 exported duplicated

### ISSUE THREAD

**Issue by fire** [godotengine/godot#47121]
**Godot version:**
https://github.com/godotengine/godot/commit/e57f6e2cca90d4c9e956fe1a7ddb3ca086521b42

**OS/device including version:**
NVidia 3000 series and win10

**Issue description:**
Blend shapes should not be duplicated

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/32321/111545906-137de900-8734-11eb-8103-9733a465055b.png)

When the glb is imported blend shapes are duplicated as many times there are surfaces.

See instructions from test project from https://github.com/godotengine/godot/issues/47120.

**Minimal reproduction project:**
See test project from https://github.com/godotengine/godot/issues/47120.

**Comment by fire** [comment]
I am working on this and blend shape animations.

**Comment by lukostello** [comment]
I recently imported a mesh with shapekeys using gltf 2 and I noticed that my original shapekey name of "In2" was changed to "In 2" could be related

**Comment by fire** [comment]
Export is fixed by https://github.com/godotengine/godot/pull/53114. 

Validation errors in https://github.com/godotengine/godot/issues/47120 is still valid.
