### ISSUE TITLE
Drag and Drop reparenting bug

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#4712]
Testing the current drag and drop behavior gives me a bug on moving nodes.
It can happen that by changing the node order all nodes can get unparented.

Here is a small gif showcasing the bug.

![drag_and_drop_bug](https://cloud.githubusercontent.com/assets/6723918/15383146/12f41e12-1d91-11e6-8b6d-11e0c56b5293.gif)

**Comment by n-pigeon** [comment]
I have problem with behavior when you take two nodes on the bottom and drag them between two on the beginning. Then they are parented to top node, when I expect it to be moved between them...
