### ISSUE TITLE
Please allow file.open("res://config_game.dat", File.READ) on HTML5

### ISSUE THREAD

**Issue by linux-man** [godotengine/godot#47132]
Otherwise, a lot of code (and plugins) that uses customized files (csv, json) will never be portable.

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by linux-man** [comment]
I'm sorry to be out-of-place, but to my knowledge, Godot don't open files at "res://" on HTML5 export, only at "usr://". This would be a "feature proposal".

Sorry again. :(

**Comment by Zireael07** [comment]
Not opening files at res:// is a feature of all exports, not just html5.

**Comment by akien-mga** [comment]
You can open file in `res://`, but you can't modify them (it's read-only, often a `.pck` archive).

Here you do need to specify an export filter to have the `.dat` file (not a standard resource) exported with the game.
