### ISSUE TITLE
Cannot compile Godot with ECMAScript module

### ISSUE THREAD

**Issue by SamirL** [godotengine/godot#47134]
**Godot version:**
3.2.3

**OS/device including version:**
MacOS Big Sur 11.2.3

**Issue description:**
Hello
I cannot compile Godot with the ECMAScript module 

> In file included from modules/ECMAScript/quickjs/quickjs_binder.cpp:1:
> In file included from modules/ECMAScript/quickjs/quickjs_binder.h:4:
> In file included from modules/ECMAScript/quickjs/../ecmascript_binder.h:5:
> In file included from modules/ECMAScript/ecmascript_gc_handler.h:4:
> In file included from ./core/object.h:38:
> ./core/os/rw_lock.h:41:15: error: no type named 'shared_timed_mutex' in
> namespace 'std'
> mutable std::shared_timed_mutex mutex;
> In file included from modules/ECMAScript/quickjs/quickjs_binder.cpp:4:
> modules/ECMAScript/quickjs/../ecmascript_language.h:74:27: warning:
> 'ECMAScriptLanguage::complete_code' hides overloaded virtual function
> [-Woverloaded-virtual]
> /* TODO */ virtual Error complete_code(const String &p_code, con...
> ^
> ./core/script_language.h:285:16: note: hidden overloaded virtual function
> 'ScriptLanguage::complete_code' declared here: type mismatch at 4th
> parameter ('List *' vs 'List *')
> virtual Error complete_code(const String &p_code, const String &...
> ^
> modules/ECMAScript/quickjs/quickjs_binder.cpp:190:32: warning: format string is
> not a string literal (potentially insecure) [-Wformat-security]
> ret = JS_ThrowTypeError(ctx, err_message.utf8().get_data());
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> modules/ECMAScript/quickjs/quickjs_binder.cpp:190:32: note: treat the string as
> an argument to avoid this
> ret = JS_ThrowTypeError(ctx, err_message.utf8().get_data());
> ^
> "%s",
> modules/ECMAScript/quickjs/quickjs_binder.cpp:340:17: warning: unused variable
> 'binder' [-Wunused-variable]
> QuickJSBinder *binder = get_context_binder(ctx);
> ^
> modules/ECMAScript/quickjs/quickjs_binder.cpp:807:31: warning: result of
> comparison against a string literal is unspecified (use an explicit string
> comparison function instead) [-Wstring-compare]
> if (data.jsclass.class_name == "") {
> ^ ~~
> modules/ECMAScript/quickjs/quickjs_binder.cpp:2217:26: warning: format string is
> not a string literal (potentially insecure) [-Wformat-security]
> JS_ThrowTypeError(ctx, err.utf8().get_data());
> ^~~~~~~~~~~~~~~~~~~~~
> modules/ECMAScript/quickjs/quickjs_binder.cpp:2217:26: note: treat the string as
> an argument to avoid this
> JS_ThrowTypeError(ctx, err.utf8().get_data());
> ^
> "%s",
> modules/ECMAScript/quickjs/quickjs_binder.cpp:2323:8: error: use of undeclared
> identifier 'atomic_increment'
> id = atomic_increment(&global_transfer_id);
> ^
> modules/ECMAScript/quickjs/quickjs_binder.cpp:2344:10: warning: unused variable
> 'obj' [-Wunused-variable]
> Object *obj = value;
> ^
> In file included from modules/ECMAScript/quickjs/quickjs_binder.cpp:1:
> In file included from modules/ECMAScript/quickjs/quickjs_binder.h:4:
> In file included from modules/ECMAScript/ecmascript_binder.h:5:
> In file included from modules/ECMAScript/ecmascript_gc_handler.h:4:
> In file included from ./core/object.h:38:
> ./core/os/rw_lock.h:41:34: warning: private field 'mutex' is not used
> [-Wunused-private-field]
> mutable std::shared_timed_mutex mutex;
> ^
> 7 warnings and 2 errors generated.
> scons: *** [modules/ECMAScript/quickjs/quickjs_binder.osx.tools.64.o] Error 1
> scons: building terminated because of errors.
> 

**Steps to reproduce:**
clone https://github.com/godotengine/godot/tree/3.2
compile it using scons platform=osx arch=x86_64 --jobs=$(sysctl -n hw.logicalcpu)

Thank you for the help!

**Comment by akien-mga** [comment]
Please report this on the EMCAScript repository, that's not something that Godot developers can fix.

You should likely checkout the `3.2.3-stable` tag though if you want to build against that module, it's probably not compatible with Godot 3.2.4 / 3.3's slightly modified threading API.
