### ISSUE TITLE
Windows 64-bit release template not working (2.0.3 official, MSVC 14.0)

### ISSUE THREAD

**Issue by yslo** [godotengine/godot#4714]
**Operating system or device - Godot version:**
Windows 7 - Godot 2.0.3 / Godot_v2.0.3_stable_export_templates.tpz

**Issue description** (what happened, and what was expected):
On Windows 7 exported executable not working (templates/windows_64_release.exe).
The executable works with debug ((templates/windows_64_debug.exe)

**Steps to reproduce:**
Export > Windows > without debug

It works with  Godot 2.0.2 / Godot_v2.0.2_stable_export_templates.tpz

**Comment by Marqin** [comment]
>not working

Could you give us screenshot of that error? Also run application from command line and see if there are any errors ( and show us ).

**Comment by Marqin** [comment]
Also, you are using template from website or from Steam?

**Comment by vnen** [comment]
Somebody else can reproduce this issue?

**Comment by vnen** [comment]
I cannot reproduce this on 2.0.4.1, so I'll assume it's fixed. If I'm wrong then please comment with more details about the issue.
