### ISSUE TITLE
Asserts take only constant strings

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#47157]
**Godot version:**
47cf998

**Issue description:**
So I have code like this
```GDScript
if "element" in resource:
    var id := get_element_id(resource.element)
    assert(id != -1, "Nonexistent element: " + resource.element)
    resource.element = id
```
Works perfectly in 3.2.x, but 4.0 isn't happy about the assert message:
![image](https://user-images.githubusercontent.com/2223172/111716209-d4e04f80-8855-11eb-8812-a8c1c0067e64.png)

**Comment by Xrayez** [comment]
Perhaps this is done to minimize debug vs release differences? `assert` previously allowed to have side effects on the game logic which may cause crashes, since assertion op codes are removed once exported, AFAIK.

**Comment by aaronfranke** [comment]
@Xrayez Was this fixed by #47701?

**Comment by cdemirer** [comment]
What should be the desired behavior here?

The underlying assert operation can print anything just fine (not necessarily strings), which can be seen by removing the check (see #47165) that produces this error. If there is a goal of not allowing side-effects, whether the expression has a side effect or not can't be detected just by observing the result type. The result type also cannot be known when dynamic typing is involved, which prevents properly checking for String in most cases. The only way to guarantee the lack of side effects is to require the expression to be a constant.

(Maybe it might be possible to propagate a "has_side_effect" flag for expression nodes, given that everything involved in the expression is statically typed and with only certain functions being whitelisted. But I think that's too much work for not much gain.)

What about an unconditional warning for every use of assert, which states the debug/export difference? It can be easily suppressed with a #warning-ignore anyways. Or rename assert to something like debug_assert, so it's behavior is slightly more obvious.

**Comment by KoBeWi** [comment]
Warning sounds fine. It could show when the string is not constant, instead of error like now.

**Comment by cdemirer** [comment]
In that case, constant non-strings would also be fine, right? And the warning message would now be about the risk of side effects that wouldn't be included in the export, rather than being about strings.

**Comment by KoBeWi** [comment]
Non-strings for message don't really make sense.

**Comment by DleanJeans** [comment]
This should work like in Godot 3:
```gdscript
func assert_equal(a, b):
    assert(a == b, 'NotEqual: %s != %s' % [a, b])
```

**Comment by duchainer** [comment]
For those using https://github.com/comby-tools/comby#install-pre-built-binaries,
I'm using this as part as my WIP comby config file for converting from Godot3 to Godot4
```
[assert-without-non-const-message]
match=":[tab~[\\t ]*]assert(:[expr~[^\\n,)]+], :[expr2~[^\\n,\")]+])"
rewrite="""
:[tab]# Errors out : Expected constant string for assert error message.
:[tab]# Track https://github.com/godotengine/godot/issues/47157 for fix in Godot source
:[tab]var assert_value = :[expr]
:[tab]if not (assert_value):
:[tab]\tassert(assert_value)
:[tab]\tpush_error(:[expr2]):[eol]
"""

```

See[ this playground for an example:](https://comby.live/index.html#{%22source%22:%22func%20foo()%20-%3E%20void:\n%20%20assert(bob,%20bob_msg)\n%20%20other_func()\n%20%20return%22,%22match%22:%22:[tab~[\\\\t%20]*]assert(:[expr~[^\\\\n,)]%2B],%20:[expr2~[^\\\\n,\\\%22)]%2B])%22,%22rule%22:%22where%20true%22,%22rewrite%22:%22:[tab]%23%20Errors%20out%20:%20Expected%20constant%20string%20for%20assert%20error%20message.\n:[tab]%23%20Track%20https://github.com/godotengine/godot/issues/47157%20for%20fix%20in%20Godot%20source\n:[tab]var%20assert_value%20=%20:[expr]\n:[tab]if%20not%20(assert_value):\n:[tab]\\tassert(assert_value)\n:[tab]\\tpush_error(:[expr2]):[eol]%22,%22language%22:%22.generic%22,%22substitution_kind%22:%22in_place%22,%22id%22:0})

**Comment by KoBeWi** [comment]
I realized it just recently but

> Perhaps this is done to minimize debug vs release differences? assert previously allowed to have side effects on the game logic (rather than just debugging stuff) which may cause crashes, since assertion op codes are removed once exported, AFAIK.

This is irrelevant to the issue. The issue is about the right side of the assert, i.e. the message. While left side, i.e. the actual expression can still be non-constant. It doesn't make sense to enforce const on the message.

**Comment by akien-mga** [comment]
Just referencing the now closed (because unfinished) PR that aimed at solving this, can be used as reference for another PR: #47165.

**Comment by cdemirer** [comment]
> While left side, i.e. the actual expression can still be non-constant.

That's right! Until GDScript has const function support, I guess there is no reason to consider side effects here at all. In regards to the message parameter, why would we want warning/error for non-strings anyway? Sometimes printing an Array etc. can also be useful (and it already works when you compile with this check removed).
