### ISSUE TITLE
MultiMesh `set_as_bulk_array()` not available anymore in 4.0

### ISSUE THREAD

**Issue by puchik** [godotengine/godot#47159]
**Godot version:**

4.0.47cf9985e

**OS/device including version:**

Windows 10 64bit, Ryzen 3600, RTX 2070s, Vulkan

**Issue description:**

`set_as_bulk_array` does not exist in 4.0 as it does in 3.x

**Steps to reproduce:**

Try to use the function.

**Minimal reproduction project:**

Not necessary? Function is missing.

**Comment by clayjohn** [comment]
It has just been renamed to ``multimesh_set_buffer``

https://github.com/godotengine/godot/blob/edbc8488a5c1e090a5a98958ac3d368f13ba1492/servers/rendering/renderer_rd/renderer_storage_rd.cpp#L3725-L3756

Also note, the multimesh API is necessarily different in 4.0 with the overhaul of the rendering architecture, so not every concept from 3.x will map 1 to 1 in 4.0. However, in this case it does, it is just a rename and a slight change in internal behaviour.
