### ISSUE TITLE
print() function doesn't generate any output on (either) Project Output Console or System Terminal

### ISSUE THREAD

**Issue by Justin-Byrne** [godotengine/godot#47153]
**Godot version:** 

    v3.2.3.stable.official
    v3.1.2.stable.official

**OS/device including version:** macOS Big Sur v11.2.3

**Issue description:**

Running the following GDScript doesn't generate any output via the Output console or terminal !?

    extends Node2D

    func _ready() -> void:
	   print("Hello!")

**Original Files:** [Hello Word.zip](https://github.com/godotengine/godot/files/6167773/Hello.Word.zip)

**Similar Issues:**

https://github.com/godotengine/godot/issues/42197
https://github.com/godotengine/godot/issues/22723

**System/Project Details:**

**Local Machine**

    OS: macOS Big Sur v11.2.3
    Local Antivirus Active: false
    Local Firewall: false

**Project Settings**

    Disable Stdout: false

**General/Debug**

    Remote Host: 127.0.0.1
    Remote Port: 6007

**Output From Initialization**

GLES2

    --- Debugging process started ---
    Godot Engine v3.2.3.stable.official - https://godotengine.org
    OpenGL ES 2.0 Renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
    OpenGL ES 2.0 Batching: ON
 
    Registered camera FaceTime HD Camera (Built-in) with id 1 position 0 at index 0
    --- Debugging process stopped ---

GLES3

    --- Debugging process started ---
    Godot Engine v3.2.3.stable.official - https://godotengine.org
    OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
 
    Registered camera FaceTime HD Camera (Built-in) with id 1 position 0 at index 0
    --- Debugging process stopped ---

Terminal

    (base) ➜  godot -d Hello.tscn 
    arguments
    0: /Users/username/Programs/Godot/Godot.app/Contents/MacOS/Godot
    1: -d
    2: Hello.tscn
    Current path: /Users/username/Programs/Godot/Hello World/
    Godot Engine v3.2.3.stable.official - https://godotengine.org
    OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
 
    Registered camera FaceTime HD Camera (Built-in) with id 1 position 0 at index 0

**Networking Testing While Project is Initialized**

$ sudo lsof -i:6007

    Godot   4158 username   56u  IPv6 0xb9d8c182e0cc45b3      0t0  TCP *:6007 (LISTEN)
    Godot   4158 username   57u  IPv6 0xb9d8c182df54cc13      0t0  TCP localhost:6007->localhost:50149 (ESTABLISHED)
    Godot   4445 username    5u  IPv4 0xb9d8c182e8a802db      0t0  TCP localhost:50149->localhost:6007 (ESTABLISHED)

$ sudo lsof -i -n -P | grep TCP

    Godot     4158     username   55u  IPv4 0xb9d8c182e8a7e493      0t0    TCP 127.0.0.1:6008 (LISTEN)
    Godot     4158     username   56u  IPv6 0xb9d8c182e0cc45b3      0t0    TCP *:6007 (LISTEN)
    Godot     4158     username   57u  IPv6 0xb9d8c182df54cc13      0t0    TCP 127.0.0.1:6007->127.0.0.1:50149 (ESTABLISHED)
    Godot     4445     username    5u  IPv4 0xb9d8c182e8a802db      0t0    TCP 127.0.0.1:50149->127.0.0.1:6007 (ESTABLISHED)

**Wireshark Analysis**

[Godot Local Port 6007 Test.json.zip](https://github.com/godotengine/godot/files/6168120/Godot.Local.Port.6007.Test.json.zip)

**Comment by snougo** [comment]
can't reproduce the issue on x86 intel MacOS 10.14.6 on Editor Output and System Terminal just print some init info then the process completed

![Screen Shot 2021-03-19 at 11 11 28](https://user-images.githubusercontent.com/64188282/111726796-8e661180-88a4-11eb-9404-40f8de32b4ae.png)

**Comment by Justin-Byrne** [comment]
Do sincerely appreciate the prompt reply, however, I'm not running the latest release candidate, instead I've tested this out on  `v3.2.3.stable.official` and `v3.1.2.stable.official`. In addition, I'm running `x86_64` version of Godot, not `x86_32` since Apple's latest OS updates (post `Mohave 10.14.6`) don't allow for `x86_32`!? Could you confirm which version you're testing on!? 

I'm unaware whether this is an OS related problem, a build issue, or both!?

I fired up Wireshark, and it doesn't even appear as though it is capturing any TCP packets affiliated with the print() function!?

**Here's some more system info:**

System Software Overview:

    System Version:			macOS 11.2.3 (20D91)
    Kernel Version:			Darwin 20.3.0
    Boot Mode:			Normal
    Computer Name:			MacBook Pro
    Secure Virtual Memory:		Enabled
    System Integrity Protection:	Enabled

Hardware Overview:

    Model Name:			MacBook Pro
    Processor Name:			Quad-Core Intel Core i5
    Processor Speed:		2 GHz
    Hyper-Threading Technology:	Enabled
    Memory:				16 GB
    System Firmware Version:	1554.80.3.0.0 (iBridge: 18.16.14347.0.0,0)

Firewall Settings:

    Mode:			Allow all incoming connections
    Firewall Logging:	Yes
    Stealth Mode:		No

**Test Execution**

![Screen Shot 2021-03-19 at 7 55 40 AM](https://user-images.githubusercontent.com/5762336/111803136-fe1bd280-888b-11eb-9d3c-8002abd05799.png)

**General Settings**

![Screen Shot 2021-03-19 at 7 15 51 AM](https://user-images.githubusercontent.com/5762336/111803266-1ee42800-888c-11eb-895b-e7d4bfccfe72.png)

**Wireshark Capture**

<img width="1436" alt="Screen Shot 2021-03-19 at 7 38 20 AM" src="https://user-images.githubusercontent.com/5762336/111803383-3c18f680-888c-11eb-8618-bfe54759201c.png">

<img width="1440" alt="Screen Shot 2021-03-19 at 7 38 41 AM" src="https://user-images.githubusercontent.com/5762336/111803423-420ed780-888c-11eb-9a1a-5363a7b823ec.png">

**Godot Version**

![Screen Shot 2021-03-19 at 7 46 03 AM](https://user-images.githubusercontent.com/5762336/111803547-6074d300-888c-11eb-8650-1d8bfd935903.png)

Any feedback, comments, or advice is always appreciated! Gotta go to the vet for my puppy; sort of an emergency. Will definitely check back here later, and continue trying to identify why this behavior persists! Many thanks in advance! 

- Cheers

**Comment by Justin-Byrne** [comment]
Scene wasn't properly attached to the internal GD Script... internal idiocy aside, problem solved!
