### ISSUE TITLE
RichTextLabel's append_bbcode() respects opening tags but not closing tags(v3.2.3.stable.official)

### ISSUE THREAD

**Issue by Bropocalypse** [godotengine/godot#47178]
If using append_bbcode() to add any tag, only the opening tags are parsed- closing tags(IE [/center] or [/rainbow]) are added as literal text and do not affect the formatting. 
The expected behavior is that both opening and closing tags would be treated identically- append_bbcode should not simply add the ending tag as text; it should result in the associated opening tag being closed and the closing tag not being visible.

Steps to reproduce: attach a script to a RichTextLabel node with the following code:
````
    func _ready():
        append_bbcode("[center] text")
        append_bbcode("[/center]")
````
result: text is centered, reads " text[/center]"
This occurs with all markers as far as I can tell.

There is a workaround which behaves as expected:
````
    bbcode_text = "[center] text"
    bbcode_text = bbcode_text + "[/center]"
````
result: text reads " text", is centered(no closing tag visible; tag closed as expected).

**Comment by Calinou** [comment]
>  it should result in the associated opening tag being closed and the closing tag not being visible.

This isn't possible for performance reasons.
