### ISSUE TITLE
Quaternion not normalized during fbx import

### ISSUE THREAD

**Issue by IllusiveS** [godotengine/godot#47174]
**Godot version:**
ec3f220098f4bf5a10809e6682a9a24ff93d85cb

**OS/device including version:**
nvidia GTX 970

**Issue description:**
While importing fbx generated in akeytsu log is filled with error messages informing me of quaternion not being normalized, editor_scene_importer_assimp.cpp:236

**Steps to reproduce:**
try to import models in archive

**Minimal reproduction project:**
[modele.zip](https://github.com/godotengine/godot/files/6174121/modele.zip)

**Comment by W4RH4WK** [comment]
Assuming it's fine to always normalize rotation quaternions in the FBX import, here you go.
