### ISSUE TITLE
Missing file system dock preview thumbnail for 3D scenes

### ISSUE THREAD

**Issue by CaptainProton42** [godotengine/godot#47171]
**Godot version:**
Current 3.x (f50c806) and current master (ec3f220) branches

**OS/device including version:**
Windows 10

**Issue description:**
No file system dock preview thumbnail is generated for 3D scenes unless a editor feature profile is set that explicitly enables the 3D editor.

**Steps to reproduce:**

Save any 3D scene in the editor; no preview thumbnail will be generated in the file system dock unless a editor feature profile is set first.

**Minimal reproduction project:**
Just create and empty project, add an empty 3D scene and save it.

**Comment by pycbouh** [comment]
> No file system dock preview thumbnail is generated for 3D scenes unless a editor feature profile is set that explicitly enables the 3D editor.

What do you mean *explicitly*? 3D is enabled by default.
