### ISSUE TITLE
Editor crashes when you want to create a Mesh Outline for an empty mesh.

### ISSUE THREAD

**Issue by unpause** [godotengine/godot#4718]
**Operating system or device - Godot version:**
Windows 7 64 Bit - Godot 2.0.3

**Issue description** (what happened, and what was expected):
When you click on [Create Outline Mesh...] at the Menu when you have selected a MeshInstance and the Mesh in the MeshInstance Node is empty the Editor crashes with an error in the console.
I expected it to display an error dialog instead of crashing.

EDIT:
Error Message: 
```
ERROR: Vector<class Variant>::operator []: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: c:\projects\godot-builds\godot\core\vector.h:132
```

**Steps to reproduce:**
- Create a MeshInstance Node
- Add a new Mesh Resource to the MeshInstance which needs to be empty
- Click on Mesh->Create Outline Mesh... at the top bar
- Click Create
- Editor will crash

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Might be related to #1990.

**Comment by reduz** [comment]
something simple must be going on the process that starts here

https://github.com/godotengine/godot/blob/master/tools/editor/plugins/mesh_instance_editor_plugin.cpp#L177

**Comment by MarianoGnu** [comment]
Mesh::_make_outline() intends to use an empty array when the mesh has no surfaces. I belive the best aproach is forbid to use the option when the mesh is empty:
