### ISSUE TITLE
Physical Bone joint are not visible

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#47188]
**Godot version:**
3.2.4 rc4 and later

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Physica bones joint are no longer visible in 3d viewport. Look the images as reference, in version 3.2.3 stable they are visible, after version 3.2.4 rc5 they are no longer visible

**Minimal reproduction project:**
![GodotJoint 3 2 3](https://user-images.githubusercontent.com/16955149/111867230-fdaa3700-8972-11eb-9884-8861a503a30b.PNG)
![GodotJoint 3 2 4 rc5](https://user-images.githubusercontent.com/16955149/111867232-fedb6400-8972-11eb-92dc-2cd56133f980.PNG)

**Comment by Calinou** [comment]
> after version 3.2.4 rc5 they are no longer visible

To clarify, are they no longer visible in 3.2.4rc5 and later, or 3.2.4rc6 and later?

**Comment by grevius5** [comment]
@Calinou I tested all rc version again, they are no longer visible in version 3.2.4rc4 and later. (I have updated the issue description)
