### ISSUE TITLE
GraphEdit's minimap can be resized to be wider than the view.

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#47189]
**Godot version:** master (62e134a) and 3.x (f50c806)

**OS/device including version:** not graphics-related

**Issue description:** The minimap of `GraphEdit` can be resized to be wider than the view, and could not be resized back because the resize handle on the top left corner of the minimap is outside the view.

**Steps to reproduce:**
1. Create a VisualScript or create an `AnimationTree` node and create an `AnimationNodeBlendTree` as root.
2. Drag the handle on minimap to the very top left corner of the screen.

**Minimal reproduction project:** Not project specific, create an empty VisualScript is faster.

**Comment by floppyhammer** [comment]
Reproducible:

![anim_tree](https://user-images.githubusercontent.com/28705694/111869391-2d306200-89ba-11eb-8acf-3b1eeaa283e2.gif)

**Comment by jmb462** [comment]
I'm investigated on this issue.

I think we should also resize the minimap when setting the graphEdit is resized to a smaller size than minimap.

**Comment by pycbouh** [comment]
Yes, I was aware of this when I implemented it. However, logic here is that user has to do this on purpose, and at a reasonable size this does not happen and cause discomfort. And if you resize the editor itself to be smaller than the minimap, you can likely extend it back to a normal size and make minimap smaller beforehand.

In other words, I don't see a reasonable limit that we can implement, and it's up to the user.

**Comment by jmb462** [comment]
OK, resizing the minimap when GraphEdit resized is not so important. And could even be annoying when we just resizing the editor inspector or tree panel for a short time (we need to re-enlarge the minimap after that...)

On the other hand, I think that preventing resizing the minimap larger than the graphedit need a fix.
In some case, there isn't any way to drag the grabber to resize minimap (when all other tabs are allready at mininum size).

**Comment by pycbouh** [comment]
Sure, we can prevent it a bit. But even if you stop the size at the GraphEdit size user can still resize the GraphEdit after that to be smaller than the minimap, producing the same state. Which is why I deemed this unimportant initially. But I guess you can prevent weird accidents this way at least.

**Comment by jmb462** [comment]
As you said, if the user set a smaller graphEdit manually, he can still set it back larger by hand. (You convince me that my proposal was useless).
That's not always the case after changing minimap size. User can be stuck because he can't enlarge the graphedit enough.
