### ISSUE TITLE
Reference of Android plugins have changed in 3.3.rc6

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot#47198]
**Godot version:**

3.3.rc6

**OS/device including version:**

MacOs Macbook air 2017

**Issue description:**

org.godotengine.godot.Godot): [0x6] register v2 has type Reference: org.godotengine.godot.Godot but expected Reference: android.app.Activity 

**Steps to reproduce:**
use a plugin from 3.2.3 and copy it to 3.3.rc6

**Minimal reproduction project:**

https://github.com/DisDoh/GodotVibrate
I've used my plugin which is working on 3.2.3 but not on 3.3.rc6

**Comment by m4gr3d** [comment]
@DisDoh that's expected behavior. Even for 3.2.3 you were using the `godot` instance incorrectly; you're supposed to use `getActivity()` instead. 
Once you make the switch the plugin should work for both 3.2.3 and 3.3.

**Comment by DisDoh** [comment]
Thank you
