### ISSUE TITLE
3.3RC6 sometimes crashes on open [macOS]

### ISSUE THREAD

**Issue by mangecoeur** [godotengine/godot#47190]
Godot 3.3RC6 
macOS Big Sur 11.2.3
CPU: intel i7
GPU: Radeon Pro 560 4GB
GLES3

Opened Godot from my download folder. Editor briefly appeared then crashed. However, doesn't happen every time, since I don't have the chance to interact with the editor there's not much I can do to systematically reproduce the error. I've attached the crash log generated by the OS.

[Godot_2021-03-20-131918.txt](https://github.com/godotengine/godot/files/6175534/Godot_2021-03-20-131918.txt)

**Comment by Calinou** [comment]
Can you reproduce this with a binary [compiled from source](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_osx.html) from the `3.x` branch?

**Comment by mangecoeur** [comment]
ok i'll see. waiting for it to compile 
![Waiting-Skeleton](https://user-images.githubusercontent.com/743508/111875952-a1f4a380-899c-11eb-9e48-dace542ba3a0.jpg)

**Comment by mangecoeur** [comment]
So yes it crashed. Not sure if it could be an issue with the project i'm opening:


```
./godot.osx.tools.x86_64
arguments
0: ./godot.osx.tools.x86_64
Current path: /Users/xxx/Code/godot/bin
Godot Engine v3.3.rc.custom_build.f50c8062d - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon Pro 560 OpenGL Engine
OpenGL ES Batching: ON
 
Registered camera FaceTime HD Camera (Built-in) with id 1 position 0 at index 0
Editing project: /Users/xxx/Code/stargrazer/stargrazer_source (::Users::xxx::Code::stargrazer::stargrazer_source)
arguments
0: /Users/xxx/Code/godot/bin/godot.osx.tools.x86_64
1: --path
2: /Users/xxx/Code/stargrazer/stargrazer_source
3: --editor
Current path: /Users/xxx/Code/godot/bin
Godot Engine v3.3.rc.custom_build.f50c8062d - https://godotengine.org
(base) xxx@xxxs-MBP-2 bin % OpenGL ES 3.0 Renderer: AMD Radeon Pro 560 OpenGL Engine
OpenGL ES Batching: ON
 
Registered camera FaceTime HD Camera (Built-in) with id 1 position 0 at index 0
ERROR: _load: Resource file not found: res://assets/animations/pulse-anim-frames/frame_02_delay-0.03s.png.
   At: core/io/resource_loader.cpp:283.
ERROR: _load: Resource file not found: res://assets/animations/pulse-anim-frames/frame_01_delay-0.03s.png.
   At: core/io/resource_loader.cpp:283.
ERROR: _load: Resource file not found: res://assets/animations/pulse-anim-frames/frame_00_delay-0.03s.png.
   At: core/io/resource_loader.cpp:283.
ERROR: _load: Resource file not found: res://assets/animations/pulse-anim-frames/frame_03_delay-0.03s.png.
   At: core/io/resource_loader.cpp:283.
ERROR: _load: Resource file not found: res://assets/animations/pulse-anim-frames/frame_00_delay-0.03s.png.
   At: core/io/resource_loader.cpp:283.
WARNING: _parse_ext_resource: Couldn't load external resource: res://assets/animations/pulse-anim-frames/frame_00_delay-0.03s.png
   At: scene/resources/resource_format_text.cpp:175.
ERROR: _load: Resource file not found: res://assets/animations/pulse-anim-frames/frame_01_delay-0.03s.png.
   At: core/io/resource_loader.cpp:283.
WARNING: _parse_ext_resource: Couldn't load external resource: res://assets/animations/pulse-anim-frames/frame_01_delay-0.03s.png
   At: scene/resources/resource_format_text.cpp:175.
ERROR: _load: Resource file not found: res://assets/animations/pulse-anim-frames/frame_02_delay-0.03s.png.
   At: core/io/resource_loader.cpp:283.
WARNING: _parse_ext_resource: Couldn't load external resource: res://assets/animations/pulse-anim-frames/frame_02_delay-0.03s.png
   At: scene/resources/resource_format_text.cpp:175.
ERROR: _load: Resource file not found: res://assets/animations/pulse-anim-frames/frame_03_delay-0.03s.png.
   At: core/io/resource_loader.cpp:283.
WARNING: _parse_ext_resource: Couldn't load external resource: res://assets/animations/pulse-anim-frames/frame_03_delay-0.03s.png
   At: scene/resources/resource_format_text.cpp:175.
ERROR: get: Condition "!p_rid.is_valid()" is true. Returned: __null
   At: ./core/rid.h:149.
ERROR: texture_allocate: Condition "!texture" is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:653.
ERROR: get: Condition "!p_rid.is_valid()" is true. Returned: __null
   At: ./core/rid.h:149.
ERROR: texture_set_data: Condition "!texture" is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:781.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff20512d7d _sigtramp + 29
(base) xxx@xxxs-MBP-2 bin % [2] Vector<int>::Vector() (in godot.osx.tools.x86_64) (vector.h:119)
[3] HashMap<StringName, Object::Signal, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::getptr(StringName const&) (in godot.osx.tools.x86_64) (hash_map.h:318)
[4] Object::emit_signal(StringName const&, Variant const**, int) (in godot.osx.tools.x86_64) (object.cpp:1187)
[5] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (in godot.osx.tools.x86_64) (object.cpp:1303)
[6] Resource::emit_changed() (in godot.osx.tools.x86_64) (resource.cpp:44)
[7] NoiseTexture::_set_texture_data(Ref<Image> const&) (in godot.osx.tools.x86_64) (noise_texture.cpp:104)
[8] NoiseTexture::_update_texture() (in godot.osx.tools.x86_64) (noise_texture.cpp:174)
[9] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (in godot.osx.tools.x86_64) (method_bind.gen.inc:59)
[10] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (in godot.osx.tools.x86_64) (object.cpp:919)
[11] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (in godot.osx.tools.x86_64) (message_queue.cpp:250)
[12] MessageQueue::flush() (in godot.osx.tools.x86_64) (message_queue.cpp:299)
[13] SceneTree::idle(float) (in godot.osx.tools.x86_64) (scene_tree.cpp:524)
[14] Main::iteration() (in godot.osx.tools.x86_64) (main.cpp:2123)
[15] OS_OSX::run() (in godot.osx.tools.x86_64) (os_osx.mm:3272)
[16] main (in godot.osx.tools.x86_64) (godot_main_osx.mm:71)
[17] 17  libdyld.dylib                       0x00007fff204e9621 start + 1
-- END OF BACKTRACE --
```

**Comment by mangecoeur** [comment]
When I open it a second time, it's fine, but i still see this error on the console:

```
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150.
ERROR: texture_allocate: Condition "!texture" is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:653.
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150.
ERROR: texture_set_data: Condition "!texture" is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:781.
```

**Comment by Calinou** [comment]
@mangecoeur Thanks :slightly_smiling_face: 

We'd need access to the project to be able to further diagnose this. Ideally, you should publish it here (feel free to strip elements not relevant to the reproduction if thus bug).

**Comment by mangecoeur** [comment]
@Calinou since it's a project i eventually want to publish i can't make the whole thing public. Plus since I have no idea what part of the project might be causing the issue if i remove bits it might not show up the problem. 
I can share a temporary link to the project source (be warned: it's a mess), let me know when you downloaded a copy and i will delete it: https://drive.switch.ch/index.php/s/la0LIVK2N180iqM

I tried opening a couple of demo projects and didn't have any crashes. I'm going to mess about with my project and see if I can find anything - I have a hunch it might have to do with level serialization code.

**Comment by Calinou** [comment]
> I can share a temporary link to the project source (be warned: it's a mess), let me know when you downloaded a copy and i will delete it

Done. I can't promise I'll have time to take a look though.

**Comment by mangecoeur** [comment]
@Calinou ok, i cleared the link. If it seems something specific to my project then good, no need to waste your time going though my project ;) If I figure out what caused the crash in my project i will post it here.

**Comment by nathanfranke** [comment]
> @Calinou ok, i cleared the link. If it seems something specific to my project then good, no need to waste your time going though my project ;) If I figure out what caused the crash in my project i will post it here.

This might be an important bug to fix before 3.3 is released. I understand you don't want to publish your current project. I would recommend backing up the entire project (ideally through a cloud service) and start deleting parts slowly until the bug isn't reproducible. Ideally you can find a very minimal reproduction project that still has the bug.

**Comment by mangecoeur** [comment]
I've been testing a bit more including deleting some parts of the project that I thought were the obvious offenders but I'm still having the same issue. It's very non-deterministic, just now I opened the editor 3 times and it crashed on project load each time, on the 4th time it loaded fine and is stable thereafter. I can only imagine it's something like a race condition that works only if some things happen to get loaded in the right order - my next step is to investigate classes that have global behaviour, perhaps there is something like a cyclic/diamond reference pattern that gets processed on load and only resolves correctly if the classes happen to get parsed in a particular order.

**Comment by mangecoeur** [comment]
I never managed to figure out the cause of this crash but it seems to have disappeared since at least RC8 and in the final 3.3, though maybe something about my project changed as well. Closing for now and thanks for the great 3.3 release :)
