### ISSUE TITLE
Bad translation key for last modified projet manager filtering list

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#47196]
**Godot version:**
Master branch 4.0 c655ed7926c051116cf0cb33a29e6a506298a820

**OS/device including version:**
Not OS related

**Issue description:**

The "Last Edited" item of the Project Manager filtering list is not translated with non english languages.

Spanish example :
![esp](https://user-images.githubusercontent.com/3649998/111880930-7975a500-89ae-11eb-8147-4c2cb9f4923a.png)
French example :
![french](https://user-images.githubusercontent.com/3649998/111880932-7aa6d200-89ae-11eb-9ba4-ed611832bc57.png)

**Steps to reproduce:**
Change the language settings to anything else english.
Open the project manager.
"Last Edited" item is still in english.

**Minimal reproduction project:**
No project needed.

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/47197#issuecomment-803461444, the fact that this is not in the translation catalog is on purpose for now, it's synced with `3.x`.
