### ISSUE TITLE
YIELD bug?

### ISSUE THREAD

**Issue by MadDogMayCry0** [godotengine/godot#47203]
Godot 3.2.4

It seems that the process of initiating the connection of an object with a yeld has no feedback with lastone. The object has time to call its method before the yould receives a link to it

Signal _ready will not be executed
```gdscript
class Class:
    extends Node
    signal _ready
    
    func do()->Object:
        emit_signal("_ready")
        return self

var bla = Class.new()
add_child(bla)
yield(bla.do(),"_ready")
print("bla")
```
Will be!
```gdscript
class Class:
    extends Node
    signal _ready
    
    func _ready():
        set_process(false)
        name = "bla"
    
    func _process(delta)->void:
        emit_signal("_ready")
        set_process(false)
            
    func do()->Object:
        set_process(true)
        return self

var bla = Class.new()
add_child(bla)
yield(bla.do(),"_ready")
print("bla")
```

**Comment by mrjustaguy** [comment]
https://github.com/godotengine/godot/issues/47057 - 3.2.4 is now 3.3, also, which version (like beta number, RC number)?

**Comment by KoBeWi** [comment]
This is not a bug.

In the first example this is what happens:
>bla is added
>do() is called
>emit_signal is called
>do() returns self
>yield will wait for _ready signal from the returned object

As you can see, the signal was emitted before the yield happens.

**Comment by MadDogMayCry0** [comment]
@KoBeWi 
You are in a hurry with the deletion!
Of course, I understand what is happening in my code, and why the yeld will never wait for a signal.
And maybe this is not a bug, but this is a logical collision that needs to be fixed at the engine level. The so-called - unexpected behavior!

Okay, I'll create a new Issue with a different name, but that doesn't change the point. Next time I ask you to be slower, and think a few times before doing any action.
