### ISSUE TITLE
Font height doesn't affect on drawing

### ISSUE THREAD

**Issue by rinart73** [godotengine/godot#4720]
**Operating system or device - Godot version:** Windows 8.1 x64 - 2.0.3

**Issue description** (what happened, and what was expected):

**Steps to reproduce:**
 - Add some font in the TextEdit properties in the IDE

 - And then connect this script to it:
```
extends TextEdit

func _ready():
    get_font("YourFontName", "").set_height(6)
```
It results in scaling down the cursor in the TextEdit while text remains default size.

---
Also please take a look at font file: https://github.com/godotengine/godot/blob/0fa588a8301b50cff5975f6c9fe8dd7969f59f16/scene/resources/font.cpp#L525
As I see we draw one char but `height` property doesn't affect it.

Maybe I'm wrong with the understanding of the code but font height changing doesn't work.

**Comment by rinart73** [comment]
I tried to make some changes in Font files and CanvasItem. It makes possible to change font size and to use one font with different sizes for several widgets simultaneously
https://github.com/rinart73/godot/tree/2.0u

**Comment by reduz** [comment]
yeah this is intended by design. Having a system where everything is
notified that the font changed height would be extremely complex at no
practical gain

**Comment by bojidar-bg** [comment]
@reduz Maybe some system to `update()` all nodes on screen might do it?

**Comment by reduz** [comment]
in other words, the function to change the font height is only intended
when building a font yourself, not for in-game use.

**Comment by reduz** [comment]
not against adding something like that, you would have to call in every
node that:
-theme changed
-minimum size for control potentially changed
-update

there are probably alternate ways around doing what OP wants, like changing
line spacing in the desired controls.

**Comment by rinart73** [comment]
No, I have another system. No fire events on font size change!
NOTIFICATION_PREDRAW fires for CanvasItem before start of the drawing. And we can use it to change size of font.
![Code](https://pp.vk.me/c604426/v604426014/a733/QMAk78rcYHE.jpg)

**Comment by reduz** [comment]
This is not a bug, in fact, it has been made that if a font size is changed, all controls that use the font will be forced to redraw, thus trying to do this will be futile. I suggest using separate fonts for this, or the new DynamicFont.
