### ISSUE TITLE
64 bit build not possible with msys2 mingw64 and ASLR enabled

### ISSUE THREAD

**Issue by MrRevington** [godotengine/godot#47219]
**Godot version:**

3.x 5e434841ec358ae3fefa2356b122c9d62df94179

**OS/device including version:**
Windows 10, msys2

**GCC:**
 gcc -v
Using built-in specs.
COLLECT_GCC=K:\dev\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=K:/dev/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev9, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Rev9, Built by MSYS2 project)

**Issue description:**
It is not possible to build a 64-bit version with ASLR enabled by default.
see: https://www.msys2.org/news/

**errors:**
<pre>
modules/libmodules2.windows.opt.tools.64.a(gdscript.windows.opt.tools.64.o):gdscript.cpp:(.text$_ZN16GDScriptLanguage28debug_get_current_stack_infoEv[_ZN16GDScriptLanguage28debug_get_current_stack_infoEv]+0x20): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript.windows.opt.tools.64.o):gdscript.cpp:(.text$_ZN16GDScriptLanguage28debug_get_current_stack_infoEv[_ZN16GDScriptLanguage28debug_get_current_stack_infoEv]+0x30): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_editor.windows.opt.tools.64.o):gdscript_editor.cpp:(.text+0x4ae7): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_editor.windows.opt.tools.64.o):gdscript_editor.cpp:(.text+0x4af1): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_editor.windows.opt.tools.64.o):gdscript_editor.cpp:(.text+0x5b6a): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_editor.windows.opt.tools.64.o):gdscript_editor.cpp:(.text+0x5b74): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_function.windows.opt.tools.64.o):gdscript_function.cpp:(.text+0x1785): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_function.windows.opt.tools.64.o):gdscript_function.cpp:(.text+0x178f): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_function.windows.opt.tools.64.o):gdscript_function.cpp:(.text+0xea04): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_function.windows.opt.tools.64.o):gdscript_function.cpp:(.text+0xea0e): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodules2.windows.opt.tools.64.a(gdscript_function.windows.opt.tools.64.o):gdscript_function.cpp:(.text+0x2de18): additional relocation overflows omitted from the output
collect2.exe: error: ld returned 1 exit status\n"
=====
scons: [bin/godot.windows.opt.tools.64.exe] Error 1
scons: building terminated because of errors.
</pre>

**Steps to reproduce:**
mingw64 shell:
scons -j24 verbose=no use_mingw=yes bits=64 platform=windows target=release_debug debug_symbols=no module_bullet_enabled=no module_fbx_enabled=no module_gdnative_enabled=no tests=no

the same build params work fine with msvc without using msys2.

the only workaround I know is
LINKFLAGS=-Wl,--disable-dynamicbase,--default-image-base-low which unfortunately disables ASLR.

building only with LINKFLAGS=-Wl,--default-image-base-low builds too but the exe crashes at start with exception: 0xc0000005
error offset: 0x0000000000920000 

$ ./godot.windows.opt.tools.64.exe --verbose
WinTab context creation failed.
Godot Engine v3.3.rc.custom_build.5e434841e - https://godotengine.org
WinTab context creation failed.
Segmentation fault

PS
the prepackaged version from msys2 has ASLR disabled too according to procexp.

**Comment by akien-mga** [comment]
See "Known issues" in the blog post you linked:

> In case you are seeing errors such as relocation truncated to fit: `IMAGE_REL_AMD64_REL32` against undefined symbol try building with `-Wl,--default-image-base-low`. Here is the upstream bug report: https://sourceware.org/bugzilla/show_bug.cgi?id=26659

So that's an upstream bug, I'm not sure there's anything we can/should do.

**Comment by MrRevington** [comment]
yeah, but now we have an issue for it in case anyone wonders.

Btw as I checked just now, the official builds from https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_win64.exe.zip don't have ASLR enabled either - I think they use mingw too?

**Comment by hpvb** [comment]
Yes official builds use Mingw due to missing features in MSVC making it unsuitable for production deployments due to performance issues. However if ASLR is more important to your use case than GDScript performance MSVC could work.

**Comment by MrRevington** [comment]
Thanks for clarifying! It doesn't really matter for me at the moment but I found out that if you replace thread_local with __thread it compiles just fine with mingw64 and ALSR enabled and seems to work too(tested 2 demos)! 

As far as I can tell functionally this should be equivalent but it's of course gcc specific.

**Comment by hpvb** [comment]
Yeah, I did suspect that, I was already talking with Pedro to ask why this was implemented in this way!

**Comment by akien-mga** [comment]
Fixed by #47368.
