### ISSUE TITLE
get all local variables as dictionary using a function like in python

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#4721]
i'm now reading the tutorial about saving games and i'm curious why variables aren't stored in dictionaries like python does.

it would be much easier to get all local variables with 'locals()' and may be even assign loaded from json dictionary to the locals dictionary.

it will give the ability to fully serialize a class (node) with single line of code

**Comment by reduz** [comment]
Performance

**Comment by vnen** [comment]
Note that there's already [`dict2inst()` and `inst2dict()`](http://docs.godotengine.org/en/latest/classes/class_@gdscript.html?#class-gdscript-inst2dict) functions to translate between an object instance and a dictionary.

**Comment by bojidar-bg** [comment]
Bump, is this still something needed, or is it not useful enough to get in gdscript?

**Comment by mhilbrunner** [comment]
@bojidar-bg I think this can be closed.

**Comment by Overvault-64** [comment]
mmhh bump? I'm working on something that would greatly benefit from getting a list of the function locals.
Example:

```
func my_func() -> void:
   var a = "some"
   var b = "thing"
   print(my_func.get_locals()) #prints {"a" : "some", "b" : "thing"}
```

Any other viable route?

**Comment by AThousandShips** [comment]
Proposals are handled [here](https://github.com/godotengine/godot-proposals), this is for bug reporting, please take it there or to the other [community channels](https://godotengine.org/community)
