### ISSUE TITLE
Godot Web Editor Mouse Mode Bug

### ISSUE THREAD

**Issue by KesaiArts01** [godotengine/godot#47227]
**Godot version:**
3.3.rc6 (Web Editor)

**OS/device including version:**

Intel Core i5-3475S - Intel HD Graphics 4000 - DirectX 12

**Issue description:**
Well, on the standard Godot Engine the command `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)` worked correctly. But in the Web Editor is not capturing the cursor and escaping the game.

**Steps to reproduce:**
Just create a script (or an existing script) and add the mentioned command (`Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)`) to `func _ready()` and run the project.

**Minimal reproduction project:**

**Comment by Faless** [comment]
Console reports: `**ERROR**: MOUSE_MODE_CAPTURED can only be entered from within an appropriate input callback.`

See [documentation](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_web.html#full-screen-and-mouse-capture)

**Comment by Firepal** [comment]
This is a security measure Javascript has in place to prevent capturing the mouse without user consent.
You **must** use `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)` in a `_input` or `_unhandled_input` function.
Example:
```gdscript
func _input(e):
	if e is InputEventMouseButton:
		Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
```
This is probably best implemented by having an overlay with text asking the user to click and removing it once they have.
