### ISSUE TITLE
Embedded subwindows (single window mode) dialogs draw in the incorrect position

### ISSUE THREAD

**Issue by pcvonz** [godotengine/godot#47244]
**Godot version: 47cf9985ebf2799d9718fa1a2ca96f2f70c6d212**

**OS/device including version:Linux**

**Issue description:**

When in single window mode, floating windows (popup, floating docks, etc.) get re-positioned to the last moved window.

**Steps to reproduce:**
1. Enable single window mode
2. Make two docks floating (scene tree, inspector, filesystem, etc.)
3. Move one dock
4. Move another dock

https://user-images.githubusercontent.com/6378569/111925817-8efad580-8a67-11eb-9d3e-ba13fcbb0c75.mp4

**Minimal reproduction project: N/A**

**Comment by Calinou** [comment]
Should we even allow detaching docks while in single-window mode in the first place? I can't see much use cases for them if you can't move them outside the editor window.

**Comment by pcvonz** [comment]
Disabling floating docks might be a good idea, but we shouldn't disable that feature in single window mode just to fix this bug. There are other ways to replicate this bug, for example, viewing the generated shader code in the visual shader editor suffers from the same issue. 

https://user-images.githubusercontent.com/6378569/111932437-a7282000-8a7a-11eb-9bb9-d78b5660cfd4.mp4

**Comment by TechnoPorg** [comment]
I think this is the same as #50949 and #51445, both of which were fixed by #53419. Are you still having this issue on the current `master` @pcvonz?

**Comment by akien-mga** [comment]
Assuming fixed, please comment if you can still reproduce it in 4.0 alpha 1.
