### ISSUE TITLE
Native Windows icon set in the Project settings is ignored

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#47240]
**Godot version:**
`3.3 RC6` and `master`

**OS/device including version:**
Debian GNU/Linux 10

**Issue description:**
When exporting the project into a Windows executable, it will not contain the ICO icon specified in the Project settings, only taking into account the path given in the Export dialog itself. The ICNS icon however, seems to work fine either way.

**Minimal reproduction project:**
[windows_icon_bug.zip](https://github.com/godotengine/godot/files/6178119/windows_icon_bug.zip)

**Comment by akien-mga** [comment]
Did you configure rcedit in editor settings?

**Comment by YeldhamDev** [comment]
@akien-mga Yes, otherwise neither setting the icon path in the Export dialog would've worked.

**Comment by YeldhamDev** [comment]
This was fixed by #77821.
