### ISSUE TITLE
The has() method not working with parsed JSON

### ISSUE THREAD

**Issue by komdog** [godotengine/godot#47247]
**Godot version:** 31d0f8ad8d5cf50a310ee7e8ada4dcdb4510690b

**OS/device including version:** Windows 10 Pro Version 1903

**Issue description:** 

When a dictionary is defined in GDScript directly, the `has()` method correctly outputs `true` when a value in the given array is present. However, when parsing a dictionary object from a string using `parse_json()`, the `has()` method fails to output true.

**Steps to reproduce:**
```gdscript
# A dictionary define in Godot 
var dictobj = {"value": [6, 10, 12]}
# Outputs "True"
print(dictobj)
print(dictobj.value.has(6))

# A Dictionary created from string and parsed
var dict1 = "{\"value\": [6, 10, 12]}"
var dictobj1 = parse_json(dict1)
# Outputs False
print(dictobj1)
print(dictobj1.value.has(6))
```
![image](https://user-images.githubusercontent.com/42328288/111947260-77493e80-8ab3-11eb-963d-e26c8cea9058.png)

**Minimal reproduction project:**

**Comment by komdog** [comment]
After looking at the source code in [json.cpp](https://github.com/godotengine/godot/blob/2abe996414b8b551e69e29461de3ff1bcaf5a28f/core/io/json.cpp), and running a few tests, I found out that `has(6)` did not return `true` because it was looking for an `int` when the `parse_json()` method returned a `float` value.

so:
```gdscript
print(dictobj1.value.has(6))
```
Does not work, but
```gdscript
print(dictobj1.value.has(6.0))
```
does. :D

**Comment by timothyqiu** [comment]
This is expected behavior as described in doc [JSONParseResult.result](https://docs.godotengine.org/en/stable/classes/class_jsonparseresult.html#class-jsonparseresult-property-result):
> Note: The JSON specification does not define integer or float types, but only a number type. Therefore, parsing a JSON text will convert all numerical values to float types.

**Comment by Calinou** [comment]
Closing per @timothyqiu's comment.

PS: Consider using the ConfigFile class when you don't require interoperability with third-party software or APIs. It can store actual integers, which avoids surprises during conversion.
