### ISSUE TITLE
[HTML5] "response.body is undefined" with 3.3 RC6 in Waterfox Classic

### ISSUE THREAD

**Issue by juanitogan** [godotengine/godot#47272]
**Godot version:**

3.3.rc6

**OS/device including version:**

Windows 10

**Issue description:**

"response.body is undefined" message appears before loading bar completes.

This is only in Waterfox Classic v2021.02 64-bit (which is the classic version of regular Waterfox -- a Firefox fork).  Firefox, Chrome, and Edge work fine.  Did not test regular Waterfox but I expect it works like Firefox does.

The same export from Godot 3.2.3 works in Waterfox Classic.  My hunch is this is related to the excellent switch to Fetch but can't say I know (or even why a Fetch is being made).

I don't know if Godot wants to continue supporting browsers such as Waterfox Classic, but I would like to if the fix to this is easy.  It is still my primary browser due to vertical tab support (and a few other reasons).

**Steps to reproduce:**

Export the demo game, Dodge the Creeps, to HTML5.

Run in Waterfox Classic (with or without an http server).

**Minimal reproduction project:**

https://github.com/godotengine/godot-demo-projects/tree/master/2d/dodge_the_creeps

**Comment by Faless** [comment]
Seems that Waterfox doesn't support the fetch Response [`body` property](https://developer.mozilla.org/en-US/docs/Web/API/Body/body). Should be reported upstream.

**Comment by Faless** [comment]
Not sure what version of Firefox they forked, but `body` should be there since FF65.
You can try setting the flag `javascript.options.streams` to `true` in `about:config` but it probably still won't work.

Not much we can do, they simply don't support fetch well enough for it to work.

**Comment by juanitogan** [comment]
Waterfox should work but Waterfox Classic is forked from FF 56 for continued support of NPAPI plugins.  So, yeah, it doesn't support Body.body.  It does, however, support most of the older parts of the Fetch API.

I mostly just wanted to report it in case there was an easy workaround.  I don't know the use case here so I don't know if streaming through body is required versus arrayBuffer() and the like.  Assuming body is required, however, perhaps there is a solution through a polyfill such as https://www.npmjs.com/package/@stardazed/streams-polyfill .  There are too many polyfills to look at so I can't guess which one might be the thinnest for the use cases here -- and without going too crazy with trying to support too many browsers.  And are they worth the extra weight?  Maybe...maybe not.  I don't suppose an option to include the polyfills is possible?

Anyhow, again, I can't guess what's right for Godot and older and/or "classic" browsers.  I suppose it's all about who's willing to put in what time for maybe 2% of browsers.  Thank you for looking at this.

**Comment by Faless** [comment]
@juanitogan you can try including the polyfill in the `html head include` field in the export.

![head_include](https://user-images.githubusercontent.com/1687918/112245870-08eeb280-8c52-11eb-83e6-8b77ec02d810.png)

**Comment by juanitogan** [comment]
Ooh, interesting, thanks.  I might try it.  I'm only about 50 hours into Godot so there are still a lot of little things like this I have yet to learn.  I've been shaking Godot down to see if it's a fit for project I've been prototyping in another engine.

**Comment by juanitogan** [comment]
Just tried it... and it totally works.  Thank you!  I'm so used to complicated web builds that I didn't think about the obvious.

So, yeah, just put this in Head Include:
<script src="https://unpkg.com/@stardazed/streams-polyfill/dist/sd-streams-polyfill.min.js"></script>

...and that's it.  Voila!
