### ISSUE TITLE
Batching: CPUParticles with custom shader broken in 3.3-rc6

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#47285]
**Godot version:**

3.3-rc6

**OS/device including version:**

Windows, iOS

**Issue description:**

With Godot 3.3-rc6 CPUParticles with a custom vertex shader are broken with batching: coordinates and color/alpha is messed up. The same setup works fine in 3.2.4-rc4.

Without batching (good):
![cpup_good](https://user-images.githubusercontent.com/40200623/112087035-90262280-8b8d-11eb-97f7-86774e586018.png)

With batching (bad):
![cpup_bad](https://user-images.githubusercontent.com/40200623/112087060-9916f400-8b8d-11eb-9ba8-c95b6f741aee.png)

**Steps to reproduce:**
Please use the MRP.

**Minimal reproduction project:**

[CPUParticles_Batching.zip](https://github.com/godotengine/godot/files/6186652/CPUParticles_Batching.zip)

**Comment by lawnjelly** [comment]
Already fixed by #47102 (according to my test just now), but not merged yet.

**Comment by akien-mga** [comment]
Fixed by #47102.
