### ISSUE TITLE
Visual Shader - sometimes can't click preview when not zoomed at 100%

### ISSUE THREAD

**Issue by mangecoeur** [godotengine/godot#47288]
**Godot version:**
3.3RC6

**OS/device including version:**
macOS 11.2.3, intel macbook pro 15 (2017)

**Issue description:**
When working on a visual shader, if I try to click the preview icon when I am zoomed out (i.e. not at 100%), it instead tries to create a new node (see screen recording)

**Steps to reproduce:**
Create a visual shader node, zoom out, then try to click the shader preview icon.

https://user-images.githubusercontent.com/743508/112123494-9afaaa80-8bc1-11eb-8142-245a2d820e4b.mp4

**Comment by akien-mga** [comment]
This might be fixed in `master` already and if so would likely be fixed by #47173 - it's a bit late in the 3.3 development cycle to merge it now though, but it will probably make its way to 3.3.1. (Still needs confirmation that it's indeed the same issue.)

**Comment by Chaosus** [comment]
I noticed that https://github.com/godotengine/godot/pull/46441 fixes only port connections but not a preview button, I wanna try to fix this too.
