### ISSUE TITLE
GDNative unable to store custom class in Variant

### ISSUE THREAD

**Issue by valentinAlkan** [godotengine/godot#47299]
**Godot version:**
3.2.3-stable

**OS/device including version:**
Windows 10

**Issue description:**
Casting GDNative custom class to Variant results in read-access violation. Refs to custom objects also fail - basically anything that ends up being stored as a pointer results in a read access violation.

**Steps to reproduce:**
Store a pointer to any custom object as a variant and project will compile but engine will crash with a read access violation 
```
Unhandled exception at 0x0000000002EC97AA in godot.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

Example code:

```
#ifndef
GDEXAMPLE_H
#define GDEXAMPLE_H

#include <Godot.hpp>

namespace godot {

    class CustomClass : public Object {
        GODOT_CLASS(CustomClass, Object)
    public:
        static void _register_methods(){
            register_property<CustomClass, String>("name", &CustomClass::name, "Undefined");
        }
        CustomClass(){
            name = "MyName";
        }
        ~CustomClass(){}
        void _init(){}
    private:
        String name;
    };



    class GDExample : public Object {
        GODOT_CLASS(GDExample, Object)
    public:
        static void _register_methods(){
            register_method("get_example", &GDExample::getCustomClasses);
        };
        GDExample(){};
        ~GDExample(){};
        void _init(){};
        CustomClass* getCustomClasses(){
            return &myclass;
        }
    private:
        CustomClass myclass;
    };

}

#endif
```

I've tried every conceivable syntax.

```
Variant(new CustomClass());
-----
CustomClass* class = new CustomClass(); 
Variant v(class);
-----
CustomClass class;
Variant v(&class)
-----
return new CustomClass(); (implicit cast to Variant)
etc
```

Even changing CustomClass to inherit from Reference produces the same error
```
Ref<CustomClass> getCustomClasses(){
    return Ref<CustomClass>(&myclass);
}
```

I'm at a loss. I've tried everything I know and I'm totally stuck. I assume it has to be a bug. I had old GDNative projects from years past that used to work like this. Every reference I've found online says this should work. Variant has a constructor from an object pointer and should be able to hold it. It compiles and then fails at runtime. Something is not right. Everything works totally fine until the moment I try to make it into a Variant. I should be able to cast a godot::Object derived pointer to and from Variant with no issues.

If it never gets cast to variant it even works in the engine. 

```
extends Control
var CustomClass = preload("res://bin/customclass.gdns")

func _ready():
	var cclass = CustomClass.new()
	print(cclass.name)
```
Produces the output:
`MyName`

**Minimal reproduction project:**
[NativeTestSimpleExport.zip](https://github.com/godotengine/godot/files/6190305/NativeTestSimpleExport.zip)
need to pull in godot-cpp

**Comment by Zylann** [comment]
> CustomClass* class = new CustomClass(); 

Don't use `new`. Use `CustomClass::_new()`. Sadly this doesnt seem to be in the doc, but it's shown in the readme: https://github.com/godotengine/godot-cpp#using-godot-classes-in-c

**Comment by valentinAlkan** [comment]
Oh wow. That's a pretty important piece of information that the guide glosses over.

Anyway, that solved my issue, thanks!
