### ISSUE TITLE
Jump to reference doesn't center around the line

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#47305]
**Godot version:**

3.3 rc6

**Issue description:**

This is basically another case of #5269 and similar issues.

**Steps to reproduce:**
1. Have a script long enough to have scrolling
2. Do something like
```
func _ready():
    my_function()

... lots of lines

func my_function():
   pass
```
3. Ctrl + Click on `my_function()` on the top
4. Editor will jump to `my_function()` definition, but it will appear at the bottom instead of being centered.

**Comment by jmb462** [comment]
In 4.0 branch, it appears at the first line at the top. Should it be centered ?

**Comment by KoBeWi** [comment]
Yeah, everything should be centered for consistency.
