### ISSUE TITLE
Custom BBCode tags do not seem to work

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#47304]
**Godot version:**

v3.2.3.stable.mono.official

**OS/device including version:**

Windows 10 20H2
1030 GT, drivers from some time in December 2020
GLES3 backend

**Issue description:**

Issue:
When attempting to write a RichTextEffect extension/custom BBCode tag, it is not recognised by RichTextLabels.
I am unsure if this is due to my use of the bbcode variable, which at present is `public string bbcode = "vcenter"`, or if there's some kind of bug in the way Godot picks up BBCode stuff. I do have [Tool] in the class definition, if that makes a difference. I've also tried various capitalisations of the bbcode variable.

The documents do not feature a C# equivalent of the GDScript, which makes this a bit of a guessing game.

EDIT: I have tried to replicate the issue with GDScript, and successfully have.
I have also tried to use the "ghost" example from the docs, which was not successful either.

Expected: 
The tag is picked up by the RichTextLabel and does not display as part of its text.

**Steps to reproduce:**
- Create a C#/GDScript class that extends RichTextEffect, and make a variable like this: `public string bbcode = "mytag"`
- Add the [mytag] tag to a RichTextLabel which has BBCode enabled
- The tag will display as part of the text

**Minimal reproduction project:**

[BBCode Test Harness.zip](https://github.com/godotengine/godot/files/6191449/BBCode.Test.Harness.zip)

**Comment by Calinou** [comment]
This is not a bug. You need to load the `class_name` classes (not a new RichTextEffect) into the RichTextLabel's Custom Effects property:

![image](https://user-images.githubusercontent.com/180032/184609127-4c3d7f93-aa30-45c8-b5f1-33885f51c302.png)

This involves scrolling through a long list of Resources, but you'll find VAlignBBCode and RichTextGhost in that list eventually (in the MRP) :slightly_smiling_face:
