### ISSUE TITLE
FileSystem editor tab doesn't load any scene.

### ISSUE THREAD

**Issue by Nanox19435** [godotengine/godot#47303]
**Godot version:**

I'm using a custom build with the following commit hash: cd05653e308c2263e23debd45211c48af134040d

**OS/device including version:**
I've confirmed this bug in both Linux and Windows

**Issue description:**

When trying to open a scene from the FileSystem tab in the editor the editor displays a warning pop up that states that there was an error loading the scene. The output displays the following message: 
ERROR: Condition "!importer.is_valid()" is true. Returning: nullptr
   at: pre_import (editor/import/resource_importer_scene.cpp:1303)

**Steps to reproduce:**
Try to open any scene from the FileSystem tab, this will happen.

**Minimal reproduction project:**

[Example.zip](https://github.com/godotengine/godot/files/6190487/Example.zip)

**Comment by akien-mga** [comment]
I can reproduce it too, and it seems like a recent regression (a few days at most). If anyone wants to do a [`git bisect`](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html), that'd be welcome :)

**Comment by Nanox19435** [comment]
Okay, I did the bisect and I think that this is the commit that caused it: 97a3a662205d598dad195fa72d2dcb2f19c21088 I hope this proves useful

**Comment by Bogunovich** [comment]
same result 97a3a662205d598dad195fa72d2dcb2f19c21088

**Comment by akien-mga** [comment]
Thanks, now I can blame @reduz :P

**Comment by RevoluPowered** [comment]
fixed #47311
