### ISSUE TITLE
Documentation:Custom Drawing 2d: Dynamic custom drawing error

### ISSUE THREAD

**Issue by mrbw85** [godotengine/godot#4730]
**Operating system or device - Godot version:**
Ubuntu 16.04 ~ godot 2.0.2

**Issue description** (what happened, and what was expected):
`func wrap(value, minVal, maxVal):`
>>`return (((value - minVal) % (maxVal - minVal)) + minVal)`

does not want to take the float that delta represents in:
`func _process(delta):`
>>`angleFrom += rotAngle * delta`
>>`angleTo += rotAngle * delta`
>>`angleFrom = wrap(angleFrom, 0, 360)`
>>`angleTo = wrap(angleTo, 0, 360)`
>>`update()` 

gives error: Invalid operands 'float' and 'int' in operator '%'.
what syntax does
`func wrap(value, minVal, maxVal):`
>>`return (((value - minVal) % (maxVal - minVal)) + minVal)`

need to be in order to accept delta value?

**Steps to reproduce:**
Running code as described in docs

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-docs/issues/151
