### ISSUE TITLE
Issues with lights not working using the new BVH option

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#47316]
**Godot version:**
3.3 rc6

**OS/device including version:**
Win10, 960m

**Issue description:**

@lawnjelly this is the issue that we discussed on twitter.

Quite often in my topdown game, the 2 main player lights don't illuminate all mesh surfaces. These 2 lights both have shadows, one being an omni and the other being a spotlight. I don't have this issue if I turn the bvh off for rendering.

As can be seen in the start of this video of my game, when the player enters an area that should be lit by the omni and spolight, there is no illumination and then it suddenly turns back on. Towards the end of the video, shows the same thing happening, but this time the spotlight is working. When the player fires a bullet (which has an attached light), suddenly the walls and floor are illuminated by the player omni light.

https://user-images.githubusercontent.com/7741669/112289057-0f2c6f80-8ce2-11eb-9506-93301544bfb6.mp4

**Comment by lawnjelly** [comment]
Thanks for the report. :+1: 

It does sound like a simple case in the pairing that I'm missing, and will probably have to wait until we get someone by chance with a simpler reproduction case, but it's useful to know there is still a bug. I'll try and have another look through if I get chance, but these things are unfortunately much easier to fix once we have a simple case.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/53374 (fixed by https://github.com/godotengine/godot/pull/54650).

@fracteed This may be fixed in the `3.4` branch, can you compile it from source and test it?

**Comment by fracteed** [comment]
@Calinou just tried it, but alas it does not resolve the issue for me. In my case, the geometry is there, it is just not being rendered, and is completely black. Interestingly, as soon as I fire a bullet into one of these black regions or walls, everything in the area starts being rendered correctly. I am guessing that doing this is forcing the bvh to update?

**Comment by lawnjelly** [comment]
It could be a number of things, but without a minimum reproduction project, there's really little we can do except hope it might get fixed by another issue.

Note that there is currently a known deficiency with areas / statics, which should be fixed soon, see description in #55640 and #17238. This is historically the result of unclear specification regarding the collision behaviour of pairable / non-pairable objects.

There's also #55813 lighting bug, which was recently fixed (it should have be present if you built the current 3.x, rather than downloaded the artifact from #54650).

**Comment by fracteed** [comment]
Thanks @lawnjelly I found it too hard to reproduce in a simple scene. It might be the complexity of the scene tree that is causing the issue as there are lots of nested spatial nodes, since the levels are procedurally strung together from lots of instanced scenes.

I did try it with a fresh build from today, so that lighting bug you mentioned didn't help. As long as the bvh remains an option and can be turned off, that is fine for me. If I do get to the bottom of this I will close down this issue. The game itself if mostly on hold for moment, as I want to finish my other game first. Tentatively I will then move this game onto a more stable 4.0 next year and the joys of trying to get it to work in 4.0 :)

**Comment by lawnjelly** [comment]
> As long as the bvh remains an option and can be turned off, that is fine for me.

Note that this isn't guaranteed longterm as a good solution, the BVH may soon offer more advanced / better behaviour compared to the old octree in 3.x. Also in Godot 4 the octree is not available (there is currently another BVH for rendering in 4.x, but it may well be replaced by the 3.x BVH soon, it is already used for physics in 4.x). So it is important we pin down such bugs.

Another option by the way if you are compiling from source is to compile with the `rids=tracked_handles` option in Scons, this provides extra error checking for RIDs. I don't *think* it is the problem in your case (am still suspecting pairing) but it's good practice to use this build as RIDs have occasionally caused problems with objects not showing up.

**Comment by lawnjelly** [comment]
Update: This looks fixed by #55640 (@fracteed sent me closed source version to try).

**Comment by lawnjelly** [comment]
Fixed by #55640 .
