### ISSUE TITLE
Snap Transform project setting is Missing

### ISSUE THREAD

**Issue by LeandroLibanio28H** [godotengine/godot#47328]
**Godot version:**

Godot Engine 3.3 RC6

**OS/device including version:**

Windows 10 Pro x64

**Issue description:**

Project Settings rendering/2d/snapping/use_transform_snap is missing.

![image](https://user-images.githubusercontent.com/68310301/112342416-f64f9a00-8ca0-11eb-85bf-015307cb7df9.png)

**Comment by Calinou** [comment]
The settings were removed in 3.3rc6 because they weren't deemed mature enough. In the future, they'll be experimented again as add-ons.

**Comment by Zireael07** [comment]
It is missing because the feature was removed - too many arcane corner cases kept breaking. It will be revisited post 3.3.

**Comment by LeandroLibanio28H** [comment]
Thanks! The feature is still mentioned on the news blog, maybe should be removed to avoid confusion.
https://godotengine.org/article/release-candidate-godot-3-3-rc-6

Sorry for my bad English.

**Comment by akien-mga** [comment]
Ah indeed, thanks. I removed it now.
