### ISSUE TITLE
getPluginMethods marked as deprecated?

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot#47327]
**Godot version:**

3.3-rc6

**OS/device including version:**

MacOs MacBookAir 2017

**Issue description:**

The getPluginMethods function is marked as deprecated in android studio.
Which function is there for replacement?

**Steps to reproduce:**
using Android Studio to build a .aar plugin for android and godot 3.3-rc6

**Minimal reproduction project:**

![Bildschirmfoto 2021-03-24 um 16 43 24](https://user-images.githubusercontent.com/10052295/112339640-2490a200-8cc0-11eb-9fa2-bb8c33471607.png)

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
@DisDoh You can now use the [`@UsedByGodot`](https://github.com/godotengine/godot/blob/ed1f5c29be6aecc62072f20d925812dd24a27f34/platform/android/java/lib/src/org/godotengine/godot/plugin/UsedByGodot.java#L45) annotation to indicate methods that should be exposed to gdscript.

Here's an [updated plugin for reference](https://github.com/m4gr3d/GAST/compare/update_to_godot_lib_3_2_4#diff-9906fd4353a5919871cd25cae411f519f4c107f80056a19ec6190f21dfb648c2).

**Comment by DisDoh** [comment]
Thank you for answering
