### ISSUE TITLE
Pause mode enabled stops body/area signals being raised on a scene that has pause mode set as Process

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#47326]
**Godot version:**
3.2.3

**OS/device including version:**
Linux mint

**Issue description:**
I have the following global code to toggle pausing so my main game pauses but a node (a mini-game popup in a gui) runs:

```
func _input(event: InputEvent) -> void:
	if Input.is_action_just_pressed(INTERFACE_OPENCLOSE_ACTION):
		visible=!visible
		if visible:
			get_tree().paused=true
		else:
			get_tree().paused=false

```

I have set pause mode as PROCESS for this 'popup' node. When the game runs, the scene is shown, the mini-game plays ok, i.e. pause mode is being ignored for this whole scene correctly. However none of the body or area entered signals within the scene are raised and no collisions occur, they are completely ignored, but the rest of the scene runs fine.

Please see below the little character going straight through the blocks. I have enabled collision visibility to show these are being generated ok

https://user-images.githubusercontent.com/12863685/112331419-cd370580-8cb0-11eb-88bd-6159b9c208d7.mp4

Now, if I change the autoload to not pause the game, then everything works fine. So game_pause is stopping signals from being raised.

```
    func _input(event: InputEvent) -> void:
	if Input.is_action_just_pressed(INTERFACE_OPENCLOSE_ACTION):
		visible=!visible
		#if visible:
		#	get_tree().paused=true
		#else:
		#	get_tree().paused=false
```

https://user-images.githubusercontent.com/12863685/112331444-d1fbb980-8cb0-11eb-9b88-6f484cc15165.mp4

**Minimal reproduction project:**
See below comments

**Comment by chucklepie** [comment]
I have a simple reproducible sample project which I will upload later. The problem is as soon as 

get_tree().paused=true

is called, even if it is unpaused, collision signals on area2d are not called. I have even went as far as resetting the collision layers, masks, monitoring and disabled states.

**Comment by chucklepie** [comment]
@Calinou 
Find attached a simple as possible case as I could do

1. Run the program use the cursors and watch it either collide with the tilemap or the kinematic (kinematic to show it's not tilemap at fault)
2. Press the ui_accept key to pause the game and hide display, then press immediately again to unpause the game
3. Repeat 1 and watch it not collide with anything

[collision_test.zip](https://github.com/godotengine/godot/files/6206282/collision_test.zip)

**Comment by pouleyKetchoupp** [comment]
It seems there's a typo in your pause/unpause script, this version works as expected:
```
if Input.is_action_just_pressed("ui_accept"):
	visible=!visible
	if !visible: # here, should be set to pause if visible was just set to false
		get_tree().paused=true
	else:
		get_tree().paused=false
```
In your current version, triggering the ui leaves the game unpaused, then hiding the ui actually pauses the game.

With this fixed, the signals work as expected.
While the game is paused, signals stop being received because the physics world is not processed.
When the game is unpaused, signals are received again.
Does that work for you?

**Comment by chucklepie** [comment]
no, the scene has pause set to Process so whether pause is on or off should not affect this scene. If pause were on then the scene would not run, but it does run, just collisions stop working.

The purpose is to pause the entire game but let this scene. I only use visible as a means of showing pause is on and off in this sample code.

**Comment by pouleyKetchoupp** [comment]
Right now, in your test project, pressing the key twice doesn't revert the state to normal, it's setting pause to true, that's why the signals keep not being received.

But beside that, I understand better what you're trying to do.

By default, yes I can confirm the whole physics is paused when the tree is paused. It causes rigid bodies to stop colliding and getting forces applied, and no collision signal is sent. On the other hand, `_process` and `_physics_process` are still called on objects with pause mode set to "process", that's why you can still move the character.

You can work around that by forcing physics to still be processed while paused, using `Physics2DServer.set_active(true)` just after pausing the game. In this case, the physics world will be still processed while paused, which means rigid bodies will be still moving and signals will be sent on all objects. Objects with pause mode set to "stop" won't receive calls to `_process` or `_physics_process` but they will receive signals.

**Comment by chucklepie** [comment]
My test case was me trying to refactor everything :)

Yes, the purpose is this is a mini-game within a 'pip boy' that pauses the whole game but not this.

If what you say is correct, I'll try it out. Why does process and physics process get called but signals on area/kinematic stop? This doesn't quite make sense to me, but either way it would be nice if it were mentioned in the docs the limitations of the pause mode.

But thanks for your time and effort, I'll check it out.

**Comment by Zireael07** [comment]
Physics not being processed AT ALL when the game is paused is a BIG catch that absolutely needs to be called out in documentation...

**Comment by pouleyKetchoupp** [comment]
The reason behind this limitation is that the physics world can only be processed or paused as a whole, which includes checking for collision and sending signals.

In Godot 4.0, the plan is to allow physics objects to be removed from the simulation or set to static when the game is paused, which will help with this limitation.

But yeah, I agree the documentation in 3.2 could be clearer on this aspect. It only mentions that physics 2D/3D will be stopped when you pause the tree, without giving details about what it means.
https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-property-paused

And the pause modes could have more details about this too:
https://docs.godotengine.org/en/stable/classes/class_node.html#enum-node-pausemode

**Comment by chucklepie** [comment]
So if I don't any rigid bodies and I call 

Physics2DServer.set_active(true) 

then pause my game leaving my mini-game running, will there be any side effects on my main game?

Also, is it worth going to the documentation section and raising a 'request' for documentation update from somebody knowledgable enough to put something useful in the 
https://docs.godotengine.org/en/stable/tutorials/misc/pausing_games.html

section?

**Comment by pouleyKetchoupp** [comment]
> So if I don't have any rigid bodies and I call Physics2DServer.set_active(true)
then pause my game leaving my mini-game running, will there be any side effects on my main game that is paused?

If your main game also uses 2D Physics, physics will keep running as a side effect. If it's a problem for you, the easiest way I can think about to work around this would be to disable physics in all your physics objects manually when you pause (probably by removing the nodes from the tree).

For the long term, the best way to handle this case would be to have a new node type to allow creating separate physics worlds, so you could use it for your minigame and if needed, pause the physics for your main game only. I'll add it to the list of useful things to add in the future, I think it would be relatively easy to do.

> Also, is it worth going to the documentation section and raising a 'request' for documentation update from somebody knowledgable enough to put something useful in the
https://docs.godotengine.org/en/stable/tutorials/misc/pausing_games.html
section?

Yes, it's a good idea! You can open a ticket in https://github.com/godotengine/godot-docs/issues and link to this issue.

**Comment by chucklepie** [comment]
@pouleyKetchoupp 
It works great, thanks. One thing I've just noticed and oddly I raised an issue about this ages ago but never saw the link, is when you have animated resources (e.g. animated tres for a tile) they continue to function with game_pause on. These changes you mention coming to 4, would they fix this issue to? At the minute I go through every animated tile and set it's speed to 0.

**Comment by pouleyKetchoupp** [comment]
Great to hear this workaround works for you!

The pause changes for 4.0 I was referring to are specific to physics nodes, animated textures are not part of it and need a separate discussion.

**Comment by chucklepie** [comment]
@pouleyKetchoupp 

I've found another issue, can you clarify to save wasting another issue, or if you think it's a bug or separate issue I can raise a ticket.

If I call:
get_tree().paused=true
get_tree().paused=false

Tooltips for all gui controls stop working.

**Comment by Zireael07** [comment]
IIRC there's an issue for tooltips not showing when paused and it's a bug @chucklepie

**Comment by Calinou** [comment]
Tooltips not being shown while paused was already reported in https://github.com/godotengine/godot/issues/29362.

**Comment by chucklepie** [comment]
@Calinou thanks, like I always say I did search just github never seems to be very accomodating with matching.

That bug seems to be not active and classed as requiring a documentation update only, so I've added some comments to it if you don't mind.

I guess this case can be closed as the original bug was down to a known limitation of world physics.
