### ISSUE TITLE
NavigationAgent3D signal "target_reached" fires very unreliable with continues movement

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#47334]
**Godot version:**
Godot v4.0.dev.custom_build
commit 4a1f2dcb746af43dcebeb241276adfb5d99c1020

**OS/device including version:**
Win 10 64x

**Issue description:**
NavigationAgent3D signal "target_reached" fires very unreliable with continues movement breaking behaviour that depends on this signal.

If the NavigationAgent3D doesn't stop and instead immediately proceeds with movement and follows a new path as soon as the path end is reached and "navigation_finished" signal is fired it constantly fails to fire the "target_reached" signal as well.

With very slow movement speed (something unpractical for most games like 2-4) and a way to large margin for realistic scaled characters (1.0+) it fails 8 out of 10 attempts to fire "target_reached" with human sized characters. It even fails if the agent moves directly over the target point while "navigation_finished" fires every single time.

**Steps to reproduce:**
Move a NavigationAgent3D constantly between multiple points. Change to an new navpath immediatly when path is finished / "navigation_finished" is fired. See that "target_reached" signal barely gets fired in this case even with generous margin values.

I think the issue is that the "target_reached" signal function only checks once on the slow physics_tick rate while "navigation_finished" signal function checks on every single path and next_location query from scripts.

This is actually easy to test by moving a script from _physics_process() to _process(). With _process(), high framerate and high movement speed "target_reached" stops firing completely while "navigation_finished" runs fine. This makes the issue worse with scripts that run in _process() to e.g. update a movement location or path marker UI each frame to prevent visual lag.

I suggest to add another "target_reached" signal check inside the "navigation_finished" check so both signals can fire reliably at the same time if the distance to the target is small enough.

**Minimal reproduction project:**
[NavigationAgent3DIssue.zip](https://github.com/godotengine/godot/files/6293312/NavigationAgent3DIssue.zip)

**Comment by Calinou** [comment]
cc @AndreaCatania
