### ISSUE TITLE
NavigationAgent3D set_velocity() doesn't trigger "velocity_computed" signal callback

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#47337]
**Godot version:**
Godot v4.0.dev.custom_build
commit 4a1f2dcb746af43dcebeb241276adfb5d99c1020

**OS/device including version:**
Win 10 64x

**Issue description:**
After telling the NavigationAgent3D the movement velocity with set_velocity() function the "velocity_computed" signal never gets emitted with Callback from the NavigationServer3D after the calculation is supposed to be done. Tested with both Editor signal connection and GDScript 2.0 Callable connection.

Movement of NavigationAgent3D on Navmesh works so NavigationServer3D and NavigationAgent3D generally communicate just fine with each other and only the "save_velocity" calculation for avoidance is butchered.

Setup and script is the same as in official NavigationServer blogpost.
https://godotengine.org/article/navigation-server-godot-4-0

**Steps to reproduce:**
Create NavigationRegion3D with navmesh.
Add NavigationAgent3D and some NavigationObstacle3D.
Connect "velocity_computed" signal on NavigationAgent3D.
Set agent velocity vector3 on NavigationAgent3D.set_velocity()
"velocity_computed" signal never receives a callback from the NavigationServer / RVO

**Minimal reproduction project:**
[NavigationAgent3DIssue.zip](https://github.com/godotengine/godot/files/6293311/NavigationAgent3DIssue.zip)

**Comment by Calinou** [comment]
cc @AndreaCatania

**Comment by smix8** [comment]
Updated with MRP for commit 4a1f2dcb746af43dcebeb241276adfb5d99c1020

**Comment by smix8** [comment]
After eating distasteful spaghetti for hours I learned that required properties like agent or map RID are never set correctly and broken functions would silently eat away the brains of all `NavigationAgent3D` with collision avoidance (no wonder they all acted so dumb in testing). I will prepare a PR as soon as I find the best place to insert a fix.
