### ISSUE TITLE
Continuous updates with 3D scene open even if it's not visible

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#47335]
## Godot version

3.2 (ee8661158c545bac2d98c34708518146cb5b60e4)

## OS/device including version

Linux/Thinkpad

## Issue description

The update spinner is spinning continously and Godot is consuming a lot of CPU with a 3D scene open, even if the script editor is open.

## Steps to reproduce

Create a 3D scene and open the script editor.

Watch the update spinner spin.

**Comment by Calinou** [comment]
> 3.2

Which *exact* Godot version are you using? Is this a regression that occurred recently?

**Comment by Jummit** [comment]
I'm on ee8661158c545bac2d98c34708518146cb5b60e4

**Comment by KoBeWi** [comment]
Doesn't seem to happen in rc6 and ee86611 looks older than that.

(Also probably related: #46743)

**Comment by ceLoFaN** [comment]
I can confirm this on 3.2.3.  My main 3D scene will use up GPU, even if I toggle it's visibility, while I work on a script / switch to the 2D viewmode. If I work on the same scripts from inside any secondary scene, then the GPU usage goes away, unless I'm viewing the scenes from the editor's 3D viewport of course.
