### ISSUE TITLE
NavigationAgent3D substracts "agent_height_offset" automatically from paths but NavigationMesh Bake averages Map height to strong

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#47342]
**Godot version:**
Godot v4.0.dev.custom_build
#47314

**OS/device including version:**
Win 10 64x

**Issue description:**

NavigationMesh Bake averages height differences very strong over larger distances (2+ units) between merged Static/MeshInstances even on best cell settings and highest quality settings possible.

While this was always the unfortunate case in Godot 3.x what changed in Godot 4.x is that NavigationAgent3D substract their "agent_height_offset" property automatically from the returned NavigationServer paths. 

This creates situations where the returned pathpoints on areas with smaller up and down slopes end up largely underground (up to 1.5 units) if "agent_height_offset" is set to properly match the agent height with a flat surface to prevent hovering. The result is that NavigationAgent3D following the paths get Collision stuck all the time on uneven terrain instead of a little "hovering" in the air fixed by gravity like in Godot 3.x.

Both situations are bad and require expensive raycasts to really ground pathfollowing characters. I think the way "agent_height_offset" works is a good idea but currently no improvement over Godot 3.x. It just flipped the core problem with lack of navmeshes baking details. To fix this Navmesh Bake needs better editor options for more granularity to create more detailed navmeshes with better height information from the baked environment.

**Steps to reproduce:**
Bake NavigationMesh Resources on NavigationRegion3D while source geometry is not flat. Even with best bake quality settings and smallest sizes uneven surfaces get nearly compelty flat over larger distances (2+ units). If you set "agent_height_offset" on NavigationAgent3D to match a flat surfaces pathpoints on small slopes end up largely underground.

**Minimal reproduction project:**
[NavigationAgent3DIssue.zip](https://github.com/godotengine/godot/files/6293308/NavigationAgent3DIssue.zip)

**Comment by Calinou** [comment]
cc @AndreaCatania
