### ISSUE TITLE
Assets are not copied to the android project when install android build template.

### ISSUE THREAD

**Issue by wangmir** [godotengine/godot#47353]
**Godot version:**
Godot v3.2.4 beta6

**OS/device including version:**
Android / Galaxy S21+

**Issue description:**
I'm using the Android build template to use subview, but the build template has some problems.
First of all, it does not copy the configuration of signing, so it it required (minor).
And, after that, assets are not copied (or not linked), so when I build with android build template, it shows,
```
2021-03-25 19:41:55.452 27967-28005/com.godot.game E/godot: **ERROR**: Couldn't load file 'res://project.binary', error code 19.
2021-03-25 19:41:55.452 27967-28005/com.godot.game E/godot:    At: core/project_settings.cpp:621:_load_settings_text_or_binary() - Couldn't load file 'res://project.binary', error code 19.
```

So, I just check the apk file built with godot editor, and I found assets/ directory, so I copied that directory to the project.
After that, it works fine.

**Steps to reproduce:**
1. fork project https://github.com/uheartbeast/youtube-tutorials
2. load project
3. install android build template
4. load android project (generated by build template)
5. build / run

**Minimal reproduction project:**

**Comment by m4gr3d** [comment]
The Android build template is only supposed to be used by the Godot editor.
A separate set of instructions will be provided when Godot 3.3 is stable for how to create a Android project that uses Godot subview.
