### ISSUE TITLE
File selection dialog missing for adb and jarsigner in Editor Settings.

### ISSUE THREAD

**Issue by benkaranja** [godotengine/godot#47367]
https://github.com/godotengine/godot/issues/45869

**Godot version:**

Godot_v3.3-rc6_win64

**OS/device including version:**

Windows 10  #64bit

**Issue description:**

In my attempts to troubleshoot my android export errors also [45869](https://github.com/godotengine/godot/issues/45869) I also noticed the file dialog selection for adb and jarsigner has been missing in the editor settings, android section.

**Steps to reproduce:**
Open Editor settings, scroll to Android section.

**Minimal reproduction project:**

**Comment by benkaranja** [comment]
![godot 3 3 missing file selection](https://user-images.githubusercontent.com/9350718/112533414-26fa0700-8d67-11eb-8f7c-39dbeb958515.png) Godot v3.3-rc6

![godot missing selection](https://user-images.githubusercontent.com/9350718/112533461-3416f600-8d67-11eb-8813-132ebddd0950.png) Godot v3.2.4

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
@benkaranja This is expected behavior. `adb` and `apksigner` are now deduced automatically based on the given `Android sdk path`.

**Comment by akien-mga** [comment]
To clarify, the settings that you see without file dialog are remnants of your previous config, but they're no longer used.

**Comment by benkaranja** [comment]
Noted. Thanks for heads up.
