### ISSUE TITLE
Binary to TSCN/TRES converter

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4736]
I've converted a few projects from XML or binary formats to the new TSCN/TRES formats of Godot 2.0. It's a very tiresome process, as you need to save every resource in the new format, and then fix all the broken dependencies manually.

It would be awesome to have an editor tool to convert binary SCN/RES ~~and XML~~ to TSCN/TRES (and maybe the other way around, though it wouldn't be a priority for me - but maybe not too hard as the exporter converts to SCN already on the fly).

**Comment by unpause** [comment]
As we want to remove the support for XML in 3.0 I think this is a necessary thing.

**Comment by akien-mga** [comment]
Such XML to TSCN conversion happens in the Godot 2 to Godot 3 exporter in 2.1.3+, but a refactoring tool for existing projects to convert SCN <> TSCN and RES <> TRES would still be nice to have in 3.0.

**Comment by KoBeWi** [comment]
Is it still necessary 2 years later? Anyone who needed to convert probably did it manually already.

**Comment by unpause** [comment]
Yeah you might be right. And because `.tres` is the standard format now anyways most projects are using `.tres` already anyway.

**Comment by akien-mga** [comment]
It could still be nice to have, but I agree that it's not so necessary nowadays since the text-based format is well established.

It would be a good use case for a plugin though to convert resources on the fly from one format to another (but some editor features might need to be better exposed to the plugin API, I don't know e.g. if the resource dependency fixing logic is available in plugins).
