### ISSUE TITLE
_gen_shape_list and other functions need to check mesh for null

### ISSUE THREAD

**Issue by fire** [godotengine/godot#47372]
**Godot version:**
https://github.com/godotengine/godot/commit/0d2da276b8066490d7af7036f5ee71e1a4703876

**OS/device including version:**
Win10 and Nvidia

**Issue description:**
`static void _gen_shape_list(const Ref<Mesh> &mesh, List<Ref<Shape3D>> &r_shape_list, bool p_convex) {`

and others don't check their mesh variable for null and crashes.

`ERR_FAIL_NULL(mesh);`

**Steps to reproduce:**
Launch https://github.com/godotengine/tps-demo in editor.

**Minimal reproduction project:**
TPS is not a small demo, but.. :D

**Comment by akien-mga** [comment]
Fixed by #47375.
