### ISSUE TITLE
EditorHelpBit doesn't resize to fit the whole description (Complex Text Layouts/DisplayServer regression)

### ISSUE THREAD

**Issue by csstej** [godotengine/godot#47377]
**Godot version:**  4.0 .dev.custom_build.5953f4d76

**OS/device including version:** Win10 [10.0.19041 Build 19041]

**Issue description:**
<ins>Bug:</ins>
![Screenshot 2021-03-26 125259](https://user-images.githubusercontent.com/21338088/112597302-f67f9f00-8e32-11eb-95af-295cf796a0d9.png)

<ins>Expected</ins>: A bigger Annotation box to fit the whole text.

**Steps to reproduce:**
Just add a ```DirectionalLight3D``` node and hover over the ```Use In Sky Only``` option.

**Minimal reproduction project:** 
As listed above.

**Comment by Calinou** [comment]
cc @bruvzg
