### ISSUE TITLE
get_item_rect() needs improvements!!

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#4738]
**[PROLOGUE] - ranting, sorry!**
Due to the unpredictable behavior of KinematicBody2D #1472 which I am trying to create pixel-perfect game. I am forced to use Area2D instead. I managed to make Area2D as a "solid" object with "slide" effect, following this article about [swept AABB](http://www.gamedev.net/page/resources/_/technical/game-programming/swept-aabb-collision-detection-and-response-r3084). Which regrettably, makes me forfeit the use of collision detection of Godot and implement my own, including **"snap to grid smooth movement"** which Godot Engine **doesn't have**, but most other engines (Unity, GameMaker..etc) have it supported, but that is for another issue. (it is solvable using script, but it is better to have it supported in the engine for grid games).

All of that worked fine since I worked with 64x64 pixels images in my testing project. But when I tried to work with other sizes, issues began.

**[ISSUE]**
When I call `get_item_rect()` function, I expected to get a `Rect2` that has the position of the item and the **`size` of all of its children enclosed and expanded in the Rect2 structure (fit all children)**. But I only get the size of 64x64. Also, using `get_item_rect()` for a rectangular with extents of 64x64 `CollisionShape2D` (for a 128x128 sprite) I get a 134x134 for its size **:/**

Maybe the following picture can get my idea better (excuse my 30 seconds scribble using mspaint)
![untitled](https://cloud.githubusercontent.com/assets/1888186/15448294/0f1b853a-1f23-11e6-8e26-cb18c513e5a1.png)

**[EPILOGUE]**
I think Godot can easily implement this, since it already has "expand() or grow()" in Rect2 class. Besides, it will make it easier to be noticed in the editor to see the expanded rectangle with all its children.

**Comment by bojidar-bg** [comment]
IMO, this should be a separate function, in order not to break current behaviour.

**Comment by RebelliousX** [comment]
@bojidar-bg Of course, I can't argue with that, as long as there is a fix for this issue.
But I don't really think it will break anything. If anything, it will make the usage of the editor more intuitive IMO.

**Comment by reduz** [comment]
function will not be changed, but how about a function like:

get_item_and_children_rect() or something like that..

**Comment by RebelliousX** [comment]
Would be perfect! thanks reduz :+1:

**Comment by RebelliousX** [comment]
Thanks again reduz, really helpful.
