### ISSUE TITLE
Writing node paths leading with a digit in their name results in an error.

### ISSUE THREAD

**Issue by InfiniteNex** [godotengine/godot#47383]
**Godot version:**
Godot Engine v3.2.3.stable.official

**OS/device including version:**
Windows10

**Issue description:**
When writing the node path in the editor, for example 
> $Node/1/Button.disabled = true

if a node within the path, is leading with a digit, the following error occurs.

> Expected string constant or identifier after "$" or "/".

Renaming the node culprit to lead with a letter instead, fixes the issue, but is hard to intuitively know that at a glance.
At a bare minimum, the error message should include that nodes leading with a digit should be renamed.

**Minimal reproduction project:**
[errorPJ.zip](https://github.com/godotengine/godot/files/6211218/errorPJ.zip)

**Comment by hilfazer** [comment]
You can also quote the string, no need to rename your node:

`$"Node/1/Button"`

**Comment by Calinou** [comment]
Literals starting with a digit are not valid identifiers (`var 2pi = TAU` won't work). Therefore, the current error message is correct.
