### ISSUE TITLE
`NOTIFICATION_WM_FOCUS` not dispatched in HTML5 (regression in 3.2.4 beta 2)

### ISSUE THREAD

**Issue by davcri** [godotengine/godot#47417]
**Godot version:** Godot 3.3rc6

**OS/device including version:**
Tried both GLES2/GLES3 renderers.

<details>
<summary>HW/SW info: </summary>
<pre>
System:
  Kernel: 5.11.6-1-MANJARO x86_64 bits: 64 Desktop: Cinnamon 4.8.6 
  Distro: Manjaro Linux 
Machine:
  Type: Desktop System
  Mobo: ASUSTeK model: ROG STRIX B550-F GAMING (WI-FI) v: Rev X.0x 
CPU:
  Info: 8-Core model: AMD Ryzen 7 3700X bits: 64 type
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1650 SUPER] driver: nvidia v: 460.56 
  Display: x11 server: X.Org 1.20.10 driver: loaded: nvidia resolution: 
  1: 1920x1080~60Hz 2: 1600x900~60Hz 
  OpenGL: renderer: GeForce GTX 1650 SUPER/PCIe/SSE2 v: 4.6.0 NVIDIA 460.56 
</pre>
</details>

**Issue description:**

`_notification(what: int)` doesn't receive `NOTIFICATION_WM_FOCUS_*` events on HTML5 export, eg: when changing tab. 

Focus events are correctly dispatched with Godot 3.2.3 stable.

**Steps to reproduce:**
With the reproduction project:

1. Run the HTML5 export
2. Click on the game to gain focus
2. Switch to another tab
3. Switch again to focus the game tab
4. `_notification(what: int)` didn't receive any `NOTIFICATION_WM_FOCUS_IN`/`NOTIFICATION_WM_FOCUS_OUT`

**Minimal reproduction project:**
[html5-focus-notifications.zip](https://github.com/godotengine/godot/files/6216155/html5-focus-notifications.zip)

**Comment by Calinou** [comment]
@davcri Which browser(s) did you test this with?

**Comment by davcri** [comment]
Chrome 89.0.4389.90, Firefox 87.0. Sorry I forgot to mention it in the first message!

**Comment by akien-mga** [comment]
Confirmed on Linux with Firefox Nightly.

I tested intermediate dev snapshots, the regression happened between 3.2.4 beta 1 (`good`) and beta 2 (`bad`).
Changes between 3.2.4 beta 1 and beta 2: https://github.com/godotengine/godot/compare/2e073ecbeaf5b502c2b8c3c0510e4a22a56db58f...04103db6bd5694b81ab0a1717fc5fdde6cb5dd4f

**Comment by Faless** [comment]
I can confirm that `WM*` events are broken in 3.3 (e.g. `NOTIFICATION_WM_FOCUS_*`), but to my testing `NOTIFICATION_WM_FOCUS_*` events where not fired in `3.2.3-stable` either when switching tabs.

Can someone else confirm that switching tabs in `3.2.3` triggered `NOTIFICATION_WM_FOCUS_EXIT`/`NOTIFICATION_WM_FOCUS_ENTER`?

**Comment by akien-mga** [comment]
Yes, here's how the MRP looks like for me on Firefox Nightly with `3.2.3`, after switching tabs a couple of times: 
![Screenshot_20210329_200235](https://user-images.githubusercontent.com/4701338/112879693-c7368f80-90c9-11eb-8a2f-79f0351ee68a.png)

Remember to click in the canvas to activate it before switching tabs the first time.

**Comment by Faless** [comment]
> Remember to click in the canvas to activate it before switching tabs the first time.

Now I see my mistakes :sweat:
