### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by nicolascanova** [godotengine/godot#47423]
Godot version: 3.2.3

The layout is bugged, i can't move anything and i can't see the scripts
 

Steps to reproduce: I just clicked in my project and cliked to edit

![Godot_bug](https://user-images.githubusercontent.com/81490588/112734710-35dae800-8f26-11eb-9765-d60ed9631a8d.png)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/43235. Can you try deleting your editor cache folder as described in that issue?

**Comment by nicolascanova** [comment]
i did it, in my secondary project the editor is working normally, but in my 
main project it got worse

**Comment by Calinou** [comment]
@nicolascanova Does it get better if you un-maximize and resize the editor windwo?

**Comment by nicolascanova** [comment]
no
![image](https://user-images.githubusercontent.com/81490588/112735358-1219a100-8f2a-11eb-838f-53014f81f7d8.png)

**Comment by nicolascanova** [comment]
uninstalled and reinstalled the editor and still this error continues

**Comment by nicolascanova** [comment]
every time i try to edit the editor i get this crash
![image](https://user-images.githubusercontent.com/81490588/112735808-e350fa00-8f2c-11eb-8243-76a2946fe595.png)

**Comment by nicolascanova** [comment]
In my secondary project, i didn't get this error, it's working normally
![image](https://user-images.githubusercontent.com/81490588/112735884-5ce8e800-8f2d-11eb-9ce7-3596839d06b1.png)

**Comment by nicolascanova** [comment]
OK, NO PROBLEMS, NO WORRIES, I UNINSTALLED GODOT FROM STEAM AND FROM THE DIRECTORY AND THE PROBLEM WAS RESOLVED :)
