### ISSUE TITLE
GDScript Texture Import Causes Crashing in Godot v4.0

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot#47425]
**Godot version:**
v4.0.dev.calinou.5953f4d76

**OS/device including version:**
Macbook Pro 16" (2019), MacOS Big Sur v11.2.2, AMD Radeon Pro 5500M (Vulkan) if graphics-related. -->

**Issue description:**
- set up a button to import texture to 3D model
- works the first time
- on the second time clicking the button and importing a texture the test crashes and outputs this in the debug:
![image](https://user-images.githubusercontent.com/27105009/112736251-66ae3200-8fa5-11eb-99ce-37b28e2b04f3.png)

...and an aside...not sure if this is linked or not... but in my main scene I keep getting this error if I'm in the 2D window:

![image](https://user-images.githubusercontent.com/27105009/112738695-6c157780-8fb9-11eb-8d69-ebd97f96182b.png)
This 2nd error seems to happen because I haven't set my Control2D nodes to be larger than 0,0 initially, which i do later with code. This error didn't happen in Godot 3.3

**Steps to reproduce:**
I've attached a file that reproduces the main error (not the aside). 
This error does not occur in Godot v3.3 with the same setup.

**Minimal reproduction project:**
[11_TextureTest.zip](https://github.com/godotengine/godot/files/6216505/11_TextureTest.zip)

**Comment by Calinou** [comment]
> ...and an aside...not sure if this is linked or not... but in my main scene I keep getting this error if I'm in the 2D window:

This error spam is a known issue (which needs to be fixed on our end), see https://github.com/godotengine/godot/issues/45911 and https://github.com/godotengine/godot/issues/45746.

**Comment by KoBeWi** [comment]
Seems fixed in alpha 8, can someone confirm? Not sure how to test it.
