### ISSUE TITLE
Godot 4.x Quat(ernion) multiplication not working correctly

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#47439]
**Godot version:**
Godot v4.0.dev.custom_build
#47428

**OS/device including version:**
Win 10 64x

**Issue description:**
I am currenctly in the process of converting my working Godot 3.3 animation retargeting module to Godot 4.x and encountered a roadblock with Quat multiplications in Godot 4.x. I need to calculate differences between Quat rotations and also apply them back and forth for different stages in the animation retargeting process. 

There are **no errors from the engine** but Quat rotations are all wrong after Quat * Quat multiplication operations that work fine in Godot 3.3. Maybe I am just not aware of some Quat/Syntax changes in Godot 4.x and someone can point me to the missing puzzle piece.

In Godot 3.3 Quat(ernion) multiplication works fine in both GDScript and in Core C++.
e.g. for calculating differences between Quat rotations and reversing them, it always yields the same Quat values, except for maybe a sign switch with near zero values.

```
# Godot 3.3
var quat_one : Quat = Quat(0.05, 0, 0, 0.98).normalized()
var quat_two : Quat = Quat(0.02, 0, 0.02, 0.97).normalized()
var quat_rotation_difference : Quat = quat_one * quat_two.inverse()
var quat_three = quat_rotation_difference * quat_two
print(quat_one) #-> prints (0.050954, 0, 0, 0.998701)
print(quat_three) #-> prints (0.050954, -0, 0, 0.998701)
print(quat_one.is_equal_approx(quat_three)) # returns True
```
Apart from Quat to Quat also converting Basis to Quat and to euler values works fine at any step in Godot 3.3.

In Godot 4.x doing the same in both GDScript and in Core C++ does not work at all. New or returned Quat is always wrong.

```
# Godot 4.x
var quat_one : Quat = Quat(0.05, 0, 0, 0.98).normalized()
var quat_two : Quat = Quat(0.02, 0, 0.02, 0.97).normalized()
var quat_rotation_difference : Quat = quat_one * quat_two.inverse()
var quat_three = quat_rotation_difference * quat_two
print(quat_one) #-> prints (0.050954, 0, 0, 0.998701)
print(quat_three) #-> prints (0.050928, -0.000848, 0.000035, 0.997004)
print(quat_one.is_equal_approx(quat_three)) # returns False
```

I first though this could be an issue with GDScript 2.0 so I converted everything to Core C++ and rebuild Godot, same issue.

Converting a Skeleton3D bone rest Transform Basis to Quat to euler in Godot 4.x is even more wrong by large values and not just very small precision errors. I don't expect a unique euler but all vector3 radians values are completely wrong and make no sense at all compared to the real skeleton rest bone rotation.

**Steps to reproduce:**
see code examples

**Minimal reproduction project:**
see code examples

**Comment by fire** [comment]
@rafallus looked into this for me. However, I haven't tested it yet.

[e04fe559a3299fd3a9993671853dd976846c5a5e.txt](https://github.com/godotengine/godot/files/6222325/e04fe559a3299fd3a9993671853dd976846c5a5e.txt)

**Comment by rafallus** [comment]
@smix8 I tested your code and now the result is the same as in version 3.3

**Comment by smix8** [comment]
@fire @rafallus 
I applied the changes and can confirm that Quat multiplications are fixed now.
