### ISSUE TITLE
Skeleton3D inspector fails to display/update Bone Rest Transforms without AnimationPlayer

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#47430]
**Godot version:**
Godot v4.0.dev.custom_build
#47314

**OS/device including version:**
Win 10 64x

**Issue description:**
Skeleton3D inspector fails to display/update Bone **Rest** Transforms without an AnimationPlayer Node or an AnimationPlayer running.

I can understand that Bone **Pose** Transforms are not on display without animation data or further updated without a running animation. Bone **Rest** Transforms should always be viewable on the skeleton node inspector.

This makes it cumbersome to inspect bone values on single skeletons saved without an AnimationPlayers. I regular need to check them for import or runtime errors as well as animation retargeting debug.

Other odd behaviour of Skeleton3D inspector:
- Without an AnimationPlayer the inspector loads all bone controls (bonetree, matrix and transform display) but all bone transform values are zero/empty as long as the "Pose Enabled" checkbox is off even the Bone Rest Transforms.
- If the AnimationPlayer is paused or no animation file is inside the AnimationPlayer Skeleton3D inspector fails to update bone transform values as well.
- If the Skeleton3D Inspector is open and updating and the AnimationPlayer gets paused and restarted the Skeleton3D Inspector stops to update Bone values. It is required to click another node and reclick the Skeleton3D node to fix this.

**Steps to reproduce:**
Click on skeleton3D and open inspector without an AnimationPlayer or animatios inside the player, all transform values are empty, not even bone rest transforms show up with values.
Start animation for a skeleton3D, open skeleton3D inspector, stop animation, inspector values stop to update, restart animation, inspector values still stop to update without reclicking other nodes before returning to Skeleton3D.

**Minimal reproduction project:**
scene save broken for me in 4.x, constant "Error opening scene" after editor restart. see steps

**Comment by fire** [comment]
Confirmed.

**Comment by smix8** [comment]
In `editor\plugins\skeleton_3d_editor_plugin.cpp` inside `Skeleton3DEditor::_joint_tree_selection_changed()` adding another `_update_properties()` around line 500 before making the containers visible again fixes the issue partially for transforms not updating with changing bone selection. Does not fix the AnimationPlayer start/stop quirks.

```
void Skeleton3DEditor::_joint_tree_selection_changed() {
    rest_editor->set_target(bone_path + "rest");
    custom_pose_editor->set_target(bone_path + "custom_pose");

    _update_properties();

    pose_editor->set_visible(true);
    rest_editor->set_visible(true);
    custom_pose_editor->set_visible(true);
```

**Comment by lyuma** [comment]
I've been running into this bug a lot in master (my version is 4.0.dev 9ca0d66a )

The workaround suggested by smix8 seems to work around the problem for me, so I think it's good.
