### ISSUE TITLE
Error using set_edited_scene_root from EditorPlugin

### ISSUE THREAD

**Issue by DenisComtesse** [godotengine/godot#4744]
**Issue description**:
I'm writing an editor plugin and I was trying to create a new root node from the script. So I created a simple node and tried this:
`get_tree().set_edited_scene_root(node)
`
A few days ago, this caused the editor to crash. With a more recent build (compiled from master), it doesn't crash anymore. The node doesn't seem to appear at first, but as soon as the screen gets updated (e.g. by clicking on the "add node" button and going back), the root node does appear, but the editor ignores it and behaves as if there was no root node.  The Console shows this error:
> ERROR: get_path: Condition ' !is_inside_tree() ' is true. returned: NodePath()

Is this actually a bug, or am I using this function completely wrong? There seems to be no documentation about it.

Here's a minimal example project. A plugin that adds a single button to the  bottom panel which creates a new node and calls this function:
[https://dl.dropboxusercontent.com/u/1891681/Test_set_edited_scene_root.zip](url)

**Comment by jjay** [comment]
I am not really sure what the set_edited_scene_root do. Code below works for me. You can inspect [editor_node.cpp](https://github.com/godotengine/godot/blob/master/tools/editor/editor_node.cpp#L5004) for more details.
```
	var editor = get_node("/root/EditorNode")
	editor.set_edited_scene(node)
```

**Comment by DenisComtesse** [comment]
Thank you, that works well! I didn't even know that EditorNode and set_edited_scene existed, is this undocumented?
It would still be nice to know what set_edited_scene_root does and if this is actually a bug or not. But my problem has been solved, so thank you!

**Comment by neikeq** [comment]
Closing as solved. Feel free to document [_SceneTree.set_edited_scene_root( Object scene )_](http://docs.godotengine.org/en/latest/classes/class_scenetree.html?highlight=scenetree#class-scenetree-set-edited-scene-root) if anyone knows what it does.
