### ISSUE TITLE
ClassDB.class_get_method_list() the provided meta data is incomplete, missing vararg in the 'args' 

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#47449]
**Godot version:**
Godot Engine v3.2.4.beta4.official

**OS/device including version:**
Windows 10, MacOs

**Issue description:**
I want to extract function signature to double a class for my GdUnit3 plugin.
For Engine classes i use ClassDB.class_get_method_list() to get the full list of supported functions to parse out the function signature.
I found a problem of functions where using varargs
For example function `emit_signal`
```
{
   "args":[
      {
         "class_name":,
         "hint":0,
         "hint_string":,
         "name":"signal",
         "type":4,
         "usage":7
      }
   ],
   "default_args":[
      
   ],
   "flags":129,
   "id":20,
   "name":"emit_signal",
   "return":{
      "class_name":,
      "hint":0,
      "hint_string":,
      "name":,
      "type":0,
      "usage":7
   }
}

```
The `args` only contain the argument 'signal'  but the function signature is `void emit_signal(signal: String, ...) vararg`
I would expect to find the second argument as vararg in the `args` section like this:
```
{
   "args":[
      {
         "class_name":,
         "hint":0,
         "hint_string":,
         "name":"signal",
         "type":4,
         "usage":7
      },
      {
         "class_name": "vararg",
         "hint":0,
         "hint_string":,
         "name":"",
         "type":19,
         "usage":7
      }
   ],

...
````

After deeper investigation I found out the `flags` is containing a bit 128 for vararg functions but im not sure is this the correct marker for an vararg func.
The enum  `MethodFlags` has no definition for bit 128 is this still undocumented?

**Steps to reproduce:**
```
	var metas := ClassDB.class_get_method_list("Node")
	for class_meta in metas:
		if class_meta["name"] == "emit_signal":
			prints(class_meta)
````

**Comment by qarmin** [comment]
https://github.com/godotengine/godot/blob/5238f1399d48397cd1c69053f8fd9bac0f1dfe0a/core/core_constants.cpp#L560-L568

https://github.com/godotengine/godot/blob/92b27e49440be1c3592a26bacc3f44e4f09e2756/core/global_constants.cpp#L598-L605

https://github.com/godotengine/godot/blob/224f5cab992e10fa1d197785942e60032b269577/core/object/method_bind.h#L36-L47

Both 4.0 and 3.x branch needs to have bind this constant
