### ISSUE TITLE
C# class not found after playing project

### ISSUE THREAD

**Issue by KuroiRoy** [godotengine/godot#47459]
**Godot version:**
I've built Godot myself and I'm currently on master branch bc29f4bca158bbf3a24030cd616f162706e1646c

**OS/device including version:**
I'm on a Macbook x86 running Catalina and using Mono 6.12.0.114.

**Issue description:**
The Godot application is unable to find the class defined in my script. 

I've been debugging the issue using CLion and I think my assembly is missing the AssemblyHasScripts attribute. I think that my class should be loaded in this function `CSharpLanguage::lookup_scripts_in_assembly() (csharp_script.cpp line 1198)`. but it doesn't get through the if statement there. I've tried setting the attribute on my assembly myself by adding this to my csproj `<AssemblyAttribute Include="Godot.AssemblyHasScripts" />` but that doesn't work.

After that it can't load my script in `CSharpScript::reload()` because the script was never added to the `dotnet_script_lookup_map`.

**Steps to reproduce:**
Create a new C# script in the Godot editor and write in some print statement.
Press Play current scene. 
The error is visible in the Debugger. "Cannot instance script because the class 'NewScript' could not be found. Script: 'res://NewScript.cs'"

**Minimal reproduction project:**
My testing project: [Master1.zip](https://github.com/godotengine/godot/files/6222714/Master1.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.2.3?

**Comment by akien-mga** [comment]
I tested your project in 3.3 RC 6, it seems to fail building with these errors:
```
.mono/temp/obj/Debug/Master1.AssemblyInfo.cs(13,18): The type or namespace name 'AssemblyHasScriptsAttribute' does not exist in the namespace 'Godot' (are you missing an assembly reference?)
.mono/temp/obj/Debug/Master1.AssemblyInfo.cs(13,18): The type or namespace name 'AssemblyHasScripts' does not exist in the namespace 'Godot' (are you missing an assembly reference?)
```

This comes from this attribute in `Master1.csproj`:
```
    <AssemblyAttribute Include="Godot.AssemblyHasScripts" />
```

I guess it might be something used in the `master` branch and not `3.x`, so it's probably something that can be debugged only with a `master` build.

**Comment by KuroiRoy** [comment]
I'm sorry! I just found the issue where this is mentioned https://github.com/godotengine/godot/pull/46713
After adding this above my class it works `[ScriptPathAttribute("res://NewScript.cs")]`

Thank you @akien-mga for checking out the issue and @Calinou for your quick responses

**Comment by neikeq** [comment]
Not fixed. You shouldn't add those attributes manually. They should be auto-generated.
I'll have a look to see what's happening.

**Comment by 31** [comment]
I don't see which version of the .NET SDK being used--is it possible this happened with .NET Core SDK 3.1, because `master` requires .NET SDK 5.0+ now that it depends on a source generator?

C# source generators just kinda don't do anything if you have them set up in the csproj and run them with an old SDK.

Maybe the source generator should add some kind of sentinel class to ensure it ran, then the Godot tooling can detect it and tell the user (and add some info that'll make it easier to diagnose these issues)?

**Comment by 31** [comment]
You can open a terminal in the project folder and run `dotnet --info` for info about what you have installed and what's being used in that particular folder. (In case you have a [`global.json`](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json).)

But, `16.6.0+5ff7b0c9e for .NET Core` indicates you're using .NET Core, not .NET Framework. That particular version probably means 3.1.302 based on the table at https://dotnet.microsoft.com/download/dotnet/3.1. (That's also an old version even as far as 3.1 versions go, need to update!) You can get .NET SDK 5.0 from https://dotnet.microsoft.com/download.

Posting your logs would help reduce the guesswork, if you can.

Also feel free to wait for @neikeq, I'm not completely sure I'm right about needing a 5.0 version. 😅

**Comment by KuroiRoy** [comment]
Alright that solves it. Thank you!
I'm on .NET 5 now with MSBuild 16.9.0
