### ISSUE TITLE
Typing into Find text box in Find/Replace loses selection and searches file for the text instead

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#47450]
**Godot version:**
3.2.3

**OS/device including version:**
Linux

**Issue description:**
Typing into the find part of the Find/Replace option loses your selection and searches entire file for the text.

When you are only searching for text then highlighting the first occurrence is fine, but when you want to search/replace and Selection Only is highlighted this behaviour is wrong.

**Steps to reproduce:**
1. Select some lines of text
2. Press CTRL-R (selection only should be ticked)
3. Type something into the top 'find' box
4. Your selection is gone and the IDE jumps to the first occurrence

What you have to do is a sequence that isn't 'normal' by remembering to bring up the search bar, entering the find text then selecting the text.

I expect this is because the 'find' and 'find/replace' use the same code.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
cc @Paulb23

**Comment by Paulb23** [comment]
Probably need to skip [this](https://github.com/godotengine/godot/blob/master/editor/code_editor.cpp#L143-L149) if `selection only` is ticked.
