### ISSUE TITLE
TextEdit color settings don't work

### ISSUE THREAD

**Issue by rinart73** [godotengine/godot#4746]
**Operating system or device - Godot version:** Windows 8.1 x64 - 2.0.3

**Issue description** (what happened, and what was expected):
- I tried to change colors in TextEdit properties but nothing of them work.
- Also I tried to apply a Theme in IDE to TextEdit. All color settiings of Theme don't apply.

**Comment by neikeq** [comment]
This is weird. I cannot reproduce this bug on Ubuntu 15.10 x64. It may be a bug on windows builds. Can any windows (or not) user confirm this?

**Comment by akien-mga** [comment]
It has been fixed already in the master branch, will be backported for Godot 2.0.4: #4798
