### ISSUE TITLE
Error when selecting Sprite2D

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#47477]
**Godot version:**

db31445

**Steps to reproduce:**
1. Add Sprite2D
2. Select it
3. 
```
In Object of type 'Sprite2D': Attempt to connect nonexistent signal 'changed' to callable 'TextureRegionEditor::_texture_changed'. Disconnecting nonexistent signal 'changed' in [Sprite2D:5173288191127].
```

**Comment by nonunknown** [comment]
Still can confirm the issue 
![image](https://user-images.githubusercontent.com/58845030/117331674-612dec80-ae6d-11eb-9975-f663b8a69561.png)

godot version: v4.0.dev.custom_build.7b8a86421 date 06/05/21

**Comment by Logharaa** [comment]
Issue still relevant as of 21/05/21 (d5f9f58b6)
