### ISSUE TITLE
Game randomly crashes if extends GDscript file

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4748]
**Operating system or device - Godot version:**
Windows 10, compiled with 81fd4598c1e436c9dfe7951b1f829ff68045103b

**Issue description** (what happened, and what was expected):
Game runs fine or randomly gets error one of following cases when run, if using ``extends "some.gd"`` ~~and ``some.gd`` has ``func _init()``~~

- Runs fine
- Invalid call to function '_init'. Expected 6 (or random number like 528, 720896) arguments.
- Bug, call error: #1576692939
- Game Crashes without debug info

**Steps to reproduce:**
- Node2D (A.gd)

### A.gd ###
```gdscript
extends "B.gd"
```

### B.gd ###
```gdscript
extends Node2D
```

And run several times.

**Link to minimal example project** (optional but very welcome):
https://drive.google.com/open?id=0ByuhCIzeus36TURzY3RBMnVULUk

**Comment by volzhs** [comment]
@reduz I guess it's related with profiler recently added.

**Comment by bojidar-bg** [comment]
@volzhs ~ Well, you should try running it in 2.0.3 to confirm that.

**Comment by volzhs** [comment]
@bojidar-bg I tested with 4c4d79e3c98182faf348f41f98d1cc3e5d843e69 commit which is just before profiler commit.
And it didn't happen.

**Comment by volzhs** [comment]
@bojidar-bg @reduz I found that it happens just when using ``extends "script.gd"``.
I deleted ``func _init()`` in ``B.gd``, so ``B.gd`` has only ``extends Node2D``.
And It happens same error as describe.

**Comment by henkz1** [comment]
I can confirm this, using inheritance doesn't work at all. Debugger also shows what appears to be random errors like "Illegal opcode 71723344 at address 0" or "Invalid call to function '_init'. Expected 10 arguments."

**Comment by aaschmitz** [comment]
I can confirm this, using a version before the commit who added the "profiler", the game runs fine. The error is "Bug, call error: #60507152" (running on Ubuntu 16.04 64b).

**Comment by akien-mga** [comment]
@reduz Can you have a look? It's a regression from this weekend's developments.

**Comment by marcosbitetti** [comment]
Sad onfirmed in b2a4908e9cc802a838a67f92dd66a17d3894c619
And it not random, game crashes all time that run, with message: Invalid call to function 'apply_json'. Expected 0 arguments
or nothing (crashes debuger)!
I make a clean clone of repo!
Affected classes:
ator.gd

    extends Reference
    
    func apply_json(ob):
       ...

personagem.dg
   extends './ator.gd'
   
    func apply_json(ob):
       ...
       .apply_json(ob) # <- raises the error

**Comment by iap-mutant** [comment]
Quick PR to fix this, base function call was left unchanged after converting member_functions from GDFunction to GDFunction*
