### ISSUE TITLE
AddChild() does not add child to scene

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#47495]
**Godot version:**

v3.2.3.stable.mono.official

**OS/device including version:**

Windows 10 20H2
1030 GT, not sure on the drivers
Backend is GLES3

**Issue description:**

I am not sure what is causing this, or if it is a visual bug in the Remote Tree, but when I add children to a Node via code, after a PackedScene is loaded, they do not appear in the Remote Tree at all. If I do GetChildren() and print out the names of the Nodes, they are correct.
No Nodes are shown on screen, or in the Remote Tree, though.

**Expected Behaviour:**
The Remote Tree is updated with the new nodes, or the Nodes are actually added to the scene.

**Steps to reproduce:**
Open and run the project attached in the Godot editor.
When it's finished doing its little Loading thing, click "New Game".
In the console, it will print out the names of the children of each node. They should be "background" and "border".
In the Remote Tree, there are no "background" or "border" nodes to be found, and they do not display on screen.

**Minimal reproduction project:**

[JoyGodot - Trimmed.zip](https://github.com/godotengine/godot/files/6229575/JoyGodot.-.Trimmed.zip)

**Comment by wupingli2021** [comment]
I hope you have not misunderstood your question.

You mean "UI"/ LoadingScreen.tscn "Add to scene without loading background?

This is just a matter of code logic, not a bug.

When "UI"/ LoadingScreen.tscn ”When the loading is completed, it will jump to the next state immediately. Packedscene loading time is very short, and loadingscreen will skip directly, so the node cannot be seen, and the printed content is correct.

My suggestion is to add a minimum retention time to "loading screen", or use breakpoint debugging to find out more easily that something is wrong.
![1111](https://user-images.githubusercontent.com/80683955/113295594-fb5cbb00-932a-11eb-8e66-a91d7512149d.png)

![222](https://user-images.githubusercontent.com/80683955/113295671-14fe0280-932b-11eb-8b98-e939645d4ec8.png)

**Comment by Nosrick** [comment]
Ah, no, it should get past the "loading screen" and into a menu.
It should look something like this:
![image](https://user-images.githubusercontent.com/1487089/113331212-8f248c00-9317-11eb-8708-1043ee968724.png)
(Colours may vary!)

Then, when you click the "New Game" button, it'll load to a mostly blank scene.
There should be a background, and Textures on the UI elements in this scene.
It looks like this:
![image](https://user-images.githubusercontent.com/1487089/113331298-af544b00-9317-11eb-8be7-de2b5aed3ee9.png)

If you check the console-
![image](https://user-images.githubusercontent.com/1487089/113331404-db6fcc00-9317-11eb-8b89-9d7509e6ffc1.png)
It will have printed out the supposed children's names, but checking the Remote Tree does not yield the same.
![image](https://user-images.githubusercontent.com/1487089/113331365-c98e2900-9317-11eb-94f0-c60b16013f45.png)

**Comment by wupingli2021** [comment]
CharacterCreationState.cs
![111111](https://user-images.githubusercontent.com/80683955/113399994-b345a300-93d3-11eb-9e16-17fe3fc8b016.png)
The position of the red wire frame instantiates two scenes.

" this.Node "Not added to the scene by GUIManager。

modify
![22222](https://user-images.githubusercontent.com/80683955/113400611-a70e1580-93d4-11eb-9457-02de23c7ff07.png)

![333](https://user-images.githubusercontent.com/80683955/113401108-74185180-93d5-11eb-96f3-4234deec5950.png)

**Comment by Nosrick** [comment]
Huh, can replicate this. Thank you!
Closing this issue, now.
