### ISSUE TITLE
Add breakpoint icon at script line number

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#4750]
it would be good to add breakpoint icon at script line number like in Delphi IDE or other game engine script editor and option to change color breakpoint line. Example: http://postimg.org/image/m99xzltip/

**Comment by bojidar-bg** [comment]
@Paulb23 ~ Ping :smiley_cat:

**Comment by Dillybob92** [comment]
+1 for me, and a hotkey to cycle through em, like Notepad ++. This is a great idea, especially for large gdscripts

**Comment by Paulb23** [comment]
Started playing around with this today, and came up with 3 rough designs, marker on the left, marker on the right, and marker on the right with a line. They can be seen in this image.

![breakpoint_marker](https://cloud.githubusercontent.com/assets/6584330/15552113/f67c3df8-22b0-11e6-983c-04b0760b14fe.png)

 Let me know what you think. I personally like the marker either the left, or on the right with a line.

**Comment by bojidar-bg** [comment]
I think the left-of-number variation is the most common, so I would rather go with it :smile:.

**Comment by mefihl** [comment]
For me "marker on the right with a line" options is the best. Thx Paulb23.
