### ISSUE TITLE
SCREEN_TEXTURE is not updated after rendering a node with a shader

### ISSUE THREAD

**Issue by OkaeriStudio** [godotengine/godot#47504]
**Godot version:**

v3.3.rc7.mono.official

**OS/device including version:**

Ubuntu 20.10
GeForce RTX 2060
GLES2

**Issue description:**

The var "SCREEN_TEXTURE" from shaders doesn't contain the previous node changes

**Steps to reproduce:**

Create a TextureRect with a shader and change the colour using "SCREEN_TEXTURE", then create a second TextureRect with another shader, when using "SCREEN_TEXTURE" it will replace the first shader effect, not taking into consideration that the screen texture already changed

If you enable a BackBufferCopy between the TextureRects, it works

![image](https://user-images.githubusercontent.com/76102447/113041483-ebf63a00-9191-11eb-83b9-54474b76ed75.png)
![image](https://user-images.githubusercontent.com/76102447/113041538-fca6b000-9191-11eb-9366-0eecf12e7db7.png)
![image](https://user-images.githubusercontent.com/76102447/113041563-04665480-9192-11eb-81f8-7d925edd7c1f.png)

**Minimal reproduction project**
[BugReport.zip](https://github.com/godotengine/godot/files/6231550/BugReport.zip)

**Comment by lawnjelly** [comment]
I'm in agreement with @clayjohn .

It seems to have been a batching bug that was introduced in 3.2.2 and no one noticed. In 3.2.2 (and 3.2.3) if you run GLES2 without batching you get blue, and if you run GLES3 (which has no batching) you get blue, but you get magenta with GLES2 batching. So blue does seem to be the correct result.

I think this can be closed unless we get further info.
