### ISSUE TITLE
Terrible performance in editor if using lots of tiles with collisions

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#47509]
**Godot version:**
3.3rc7

**OS/device including version:**
Windows 10
gtx 1050 ti
gles3

**Issue description:**
I opened a project I made in 3.2.3 in 3.3rc7, and noticed terrible performance inside of the editor. I've found that the problem happens when you use a lot of tiles with collisions. This was not a problem in 3.2.3.

**Steps to reproduce:**
Create a new gles3 project. Create a node2d, and add a tilemap node as a child. Create a new tileset resource using the dropdown in the inspector for tilemap, Import an image into the tileset creator, and crate a new single tile. Create a collision for that tile. As you start adding that tile to the tilemap, it will progressively get slower and slower.

**Minimal reproduction project:**
[SlowTilemap.zip](https://github.com/godotengine/godot/files/6232151/SlowTilemap.zip)

**Comment by Calinou** [comment]
Disable the visibility of collision shapes in the TileMap node by unchecking the **Show Collision** property.

**Comment by JamesC01** [comment]
I feel like that should be disabled by default, since it doesn't take _that_ many tiles to start slowing down.

**Comment by akien-mga** [comment]
They should be disabled by default in 3.3 RC 7 already.

**Comment by akien-mga** [comment]
Ah no my PR isn't merged yet: #47382.

Well #47382 fixes it.
