### ISSUE TITLE
Error 'Condition "!is_visible_in_tree()" is true' when moving cursor in window with hidden TouchScreenButton

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#47501]
**Godot version:**

3.3-rc7

**OS/device including version:**

Windows

**Issue description:**

With rc7 I get lots of errors about _input: Condition "!is_visible_in_tree()" is true for touch screen buttons, which weren't showing before. Is this normal ?

![image](https://user-images.githubusercontent.com/40200623/113015427-d4ad5180-917d-11eb-81f4-43619c66d68a.png)

**Steps to reproduce:**
With the minimal reproduction project, when the visibility of the touch screen button is turned on in the editor, it's ok. When the visibility is turned off, running the project and moving the mouse inside the window generates an error for every mouse event.

**Minimal reproduction project:**

[TouchScreenButton.zip](https://github.com/godotengine/godot/files/6232152/TouchScreenButton.zip)

**Comment by oeleo1** [comment]
My bad. I had a get_global_position() in the TouchScreenButton which fails when the button is hidden.

**Comment by oeleo1** [comment]
Still have them and these errors are new compared to previous versions.

**Comment by akien-mga** [comment]
Can you clarify which versions are "previous versions"?

**Comment by akien-mga** [comment]
A minimum reproduction project, or more detailed steps to reproduce, would be greatly appreciated. I tried to add a TouchScreenButton and hide/show it, doesn't raise any errors here in 3.3 RC 7.

**Comment by oeleo1** [comment]
The ones I've tested are 3.3-rc6, 3.2.rc4 and before. I also tried to isolate a quick MRP from the existing code base but didn't succeed so far. I'll dig it up and come back with details.

**Comment by akien-mga** [comment]
That's interesting, there hasn't been much change from 3.3 RC 6 to RC 7, and none that should affect TouchScreenButton: https://github.com/godotengine/godot/compare/15ff752737c53a1727cbc011068afa15683509be...cca2637b9b9dcb16070eb50a69c601a5f076c683

**Comment by oeleo1** [comment]
I nailed it down. Try the MRP

**Comment by akien-mga** [comment]
Thanks. To clarify, it's moving the mouse around in the window with visibility off *when running the game* (not in the editor).

I have the same issue in 3.3 RC 7, 3.3 RC 6, 3.2.3-stable, and all the way down to 3.1-stable (didn't test earlier releases) so it doesn't seem to be a regression.

**Comment by oeleo1** [comment]
Strange indeed that I noticed this for the first time. It's nasty enough as well, as there doesn't seem to be a workaround with code. The simple presence of the _input() function generates the error for mouse (any?) events.

**Comment by AgentSmith0** [comment]
I tried the reproduction project and I can confirm this issue is still present in Godot 3.4-stable.
