### ISSUE TITLE
Changing the name of a node breaks NodePaths

### ISSUE THREAD

**Issue by BimDav** [godotengine/godot#47523]
**Godot version:**
v3.2.3-stable

**OS/device including version:**
Windows 10

**Issue description:**
When there is a Node hierarchy as such:
NodeToBeRenamed
   -- NodeWithPathToOtherNode
   -- OtherNode

and NodeWithPathToOtherNode has a script with `export(NodePath) var path_to_other_node` and we set a path to OtherNode, the path is logically set to "../OtherNode".

Now if we rename NodeToBeRenamed to NodeRenamed, the path becomes "../../NodeRenamed/OtherNode", but it should not change.

This is problematic if we later have a scene where there are several instances of NodeRenamed, where one will be named NodeRenamed and the second NodeRenamed2. The path in NodeRenamed2 will refer to the OtherNode in NodeRenamed.

Another bug follows if we rename once again NodeRenamed to NodeRenamedAgain. The path stays at "../../NodeRenamed/OtherNode".

**Steps to reproduce:**
Use the project below, and change the name of the root Node.

**Minimal reproduction project:**
[Path_bug.zip](https://github.com/godotengine/godot/files/6236595/Path_bug.zip)

**Comment by mbrlabs** [comment]
That is already fixed and will be available in the next 3.3 release. See #42314

**Comment by Calinou** [comment]
Closing per @mbrlabs' comment.
