### ISSUE TITLE
Race condition regarding something about CanvasItem

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#47521]
**Godot version:**

v3.2.3.stable.mono.official

**OS/device including version:**

Windows 20H2
1030 GT, not sure on drivers
GLES3

**Issue description:**

This error appears when LoadingText.cs runs its _Process() function the first few times. This may or may not appear if the project is debugged, and stepped through.
![image](https://user-images.githubusercontent.com/1487089/113151672-3bd60f00-922d-11eb-89df-53c3b4d18d37.png)

Another set of errors that appear are these ones:
![21-03-31-12 24](https://user-images.githubusercontent.com/1487089/113160414-63c97080-9235-11eb-9b2d-1ba7de9442a6.png)

These ones only appear for me if I do not step through the code.

I believe this may be a race condition of some kind?

Everything in the project can basically be ignored apart from LoadingText.cs; the rest is simply there to take up time, now.
It appears to be _after_ the _Process() has finished being executed that these error messages appear.

I'm struggling to recreate this in a very minimal test project, but I'm going to keep trying.

**Steps to reproduce:**
- Run the sample project
- Observe errors in the console (I can't get this to be consistent)

**Another method:**
- Put a breakpoint on LoadingText._Process()
- Step through the code one step at a time
- Watch the console for either the texture errors, or the CanvasItem ones (again, this is not consistent)

**Minimal reproduction project:**

[JoyGodot - Trimmed.zip](https://github.com/godotengine/godot/files/6236226/JoyGodot.-.Trimmed.zip)

**Comment by akien-mga** [comment]
I don't get those errors on 3.2.3-stable or 3.3 RC 7, but I get this instead:
```
E 0:00:03.089   texture_set_data: Condition "!texture->active" is true.
  <C++ Source>  drivers/gles3/rasterizer_storage_gles3.cpp:782 @ texture_set_data()
```

But your project is too big for a bug report, without debugging your whole code it's difficult to say if it's an engine bug, or if it's a misuse of an engine feature in the project (or both).

**Comment by Nosrick** [comment]
Ah, I didn't notice these errors before!
Let me see if I can trim it down a bit.

**Comment by Nosrick** [comment]
Closing this issue because I can't make the project smaller and replicate the issue.
