### ISSUE TITLE
Normal is wrong with scaled mesh (SpatialMaterial Ensure Correct Normals not implemented in GLES2)

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#47536]
**Godot version:**

3.3.rc b38a36923a

**OS/device including version:**

Kubuntu 20.10 / AMD RX570 / both GLES2 & GLES3

**Issue description:**

Normal goes wrong with scaled mesh.
Left - no scale, Center - 0.2 scaled on Y, Right - 5.0 scaled on Y
![Screenshot_20210401_113341](https://user-images.githubusercontent.com/8281454/113235582-51efd800-92de-11eb-98c7-d318f4640548.png)
it looks Normal of the center and the right one is swapped.
same result on both gles2 and 3.

**Steps to reproduce:**
[scale normal.zip](https://github.com/godotengine/godot/files/6240583/scale.normal.zip)

**Minimal reproduction project:**

**Comment by volzhs** [comment]
@lawnjelly @clayjohn would you take a look?
it seems to be easy to fix but I have no idea with glsl :cry:

**Comment by clayjohn** [comment]
How does it look in Blender (or whatever modelling program it is made in)? Is there any chance your mesh has malformed normals?

**Comment by volzhs** [comment]
@clayjohn 
this is how it looks in blender
![Screenshot_20210401_123658](https://user-images.githubusercontent.com/8281454/113240231-48b73900-92e7-11eb-8797-e8e608a443a2.png)

and `ensure correct normal ` does not make any changes.
![normal](https://user-images.githubusercontent.com/8281454/113240294-684e6180-92e7-11eb-86e0-7a64aabbb22a.gif)

for me, right one looks correct normal for the center one (even without `ensure_correct_normal`). isn't it?

**Comment by clayjohn** [comment]
Without ``ensure_correct_normals``:
![Screenshot (8)](https://user-images.githubusercontent.com/16521339/113240797-3e069080-9262-11eb-928d-fc5ce53ce270.png)


With ``ensure_correct_normals``:
![Screenshot (9)](https://user-images.githubusercontent.com/16521339/113240802-41018100-9262-11eb-8a9b-82101bcc37f6.png)

**Comment by volzhs** [comment]
yes, I found it works on gles3 but not on gles2.
maybe it's a bug on gles2?

**Comment by clayjohn** [comment]
Ah yeah, looks like it was never implemented in GLES2.

**Comment by akien-mga** [comment]
Fixed by #47540.
