### ISSUE TITLE
Nodes from a parent Control that are  children of a sprite don't inherit that Controls Theme

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4754]
Hard to explain, but look at my hierarchy for example:

![image](https://cloud.githubusercontent.com/assets/10387670/15453997/edbbd60c-1fdf-11e6-9760-6afe604215ea.png)

On this image, the `Button` and `Checkbox` nodes inherit the main theme. (Which is normal) --

**But**, when you have children of a sprite, for example the `Life` and `Mana` labels, **they don't inherit the main controls theme**. Is that intended? If so, I apologize for this, I just thought all nodes under would inherit the main theme.

**Comment by Dillybob92** [comment]
Ohh @akien-mga assigned it a bug!  Yay! :) This will save so much time by not having to re-set the main theme for every other label, haha.

**Comment by akien-mga** [comment]
Well it looks like a bug *a priori*, but I'm not an expert. It could be that it's by design, but until we know, it's a probable bug :)

**Comment by bojidar-bg** [comment]
To me it looks like a non-bug, but it would be nice to fix anyway.
