### ISSUE TITLE
Regression: GDScript but not C# is able to set Blend Shapes values via code

### ISSUE THREAD

**Issue by GeorgeS2019** [godotengine/godot#47543]
[GDScript but not C# is able to set Blend Shapes values via code](https://github.com/godotengine/godot/issues/36243)

Godot version: 3.3 RC 7
OS/device including version: Windows 10

Minimal reproduction project:
[BlendShapeCsharp.zip]
(https://github.com/godotengine/godot/files/4208427/BlendShapeCsharp.zip)

https://github.com/godotengine/godot/issues/36243#issuecomment-590350428
`._Set` for c# does not work any more

**Comment by Calinou** [comment]
@GeorgeS2019 Which Godot version did it last work in?

**Comment by GeorgeS2019** [comment]
@Calinou 
Godot version: 3.2 (stable) mono
OS/device including version: Windows 10 19014
https://github.com/godotengine/godot/issues/36243

**Comment by Calinou** [comment]
@GeorgeS2019 I've seen the issue you've linked, but it's pretty old by now. Can you test this in [3.2.3](https://downloads.tuxfamily.org/godotengine/3.2.3/) and [older 3.2.4 RCs](https://downloads.tuxfamily.org/godotengine/3.2.4/) to determine when this stopped working? (3.2.4 was renamed to 3.3 during the development process, but they are fundamentally the same branch.)

**Comment by GeorgeS2019** [comment]
@Calinou Tested 3.2.3  => failed, so I would not proceed to 3.2.4 RCs

Very strange, I could not be the only one in c# needing BlendShape.

**Comment by Calinou** [comment]
@GeorgeS2019 Can you test [3.2.1](https://archive.hugo.pro/godot-tuxfamily/3.2.1/) and [3.2.2](https://downloads.tuxfamily.org/godotengine/3.2.2/) as well? (Note that you'll have to create new projects for each version since they're not fully backwards/forwards compatible.)

**Comment by GeorgeS2019** [comment]
@Calinou Can you please help me where to look the c++ code.. I think it is more relevant to avoid this problem in future myself.

**Comment by GeorgeS2019** [comment]
@neikeq  Do you have idea how to prevent this regression?

**Comment by 31** [comment]
Changing `.Set` instead of `._Set` as recommended/accepted in #36243 works for me in 3.3 rc7:

![image](https://user-images.githubusercontent.com/331300/113305879-1860a200-92c9-11eb-9429-e81c13cf1e88.png)

(Changed the code a bit to make the equivalence more obvious: used `0.5f` instead of `randf()`, and used an orthogonal camera.)

@GeorgeS2019 Why are you using `._Set` instead of `.Set`? When did that work?

**Comment by GeorgeS2019** [comment]
@31 

Was recommended to use ._Set in c#

![image](https://user-images.githubusercontent.com/49812372/113311856-02270600-930a-11eb-83fa-3feddf8e7637.png)

**Comment by GeorgeS2019** [comment]
@31 can u attach a working c# mono 3.3 rc7 so I can test. Thank you.

**Comment by 31** [comment]
> Was recommended to [use ._Set in c# => and it worked before for c#!](https://github.com/godotengine/godot/issues/36243#issuecomment-590350428)
> 
> > From a quick look, you're calling `set` in GDScript but `_Set` in C# instead of `Set`. Could that be the cause?

I actually get the opposite impression from that comment. 😄 To me, it's saying the problem with your code is that you're using `_Set`. It's different from the GDScript, where you use `set`. (The equivalent to GDScript's `set` in C# is `Set`.)

> can u attach a working c# mono 3.3 rc7 so I can test. Thank you.

I downloaded the zip, (deleted `.mono` and `.import` to make sure I get a fresh build), then made this change in `Sphere.cs`:

```diff
-        this._Set("blend_shapes/Morphed Sphere", 0.25);
+        this.Set("blend_shapes/Morphed Sphere", 0.25);
```

then it worked for me in 3.3 rc7.

**Comment by GeorgeS2019** [comment]
@31  no luck :-(   => it is unfortunate, ._Set and .Set is even a question for c# developer and making Blendshape c# works is like climbing Everest, full of time wasting paths.

**Comment by 31** [comment]
@GeorgeS2019 Huh... can you upload a new copy of your project after the change + rebuild + run? I wonder if our .NET assemblies are ending up different.

**Comment by GeorgeS2019** [comment]
@31 so far, I do not have other problems with godot 3.3rc7 except this particular function.  Godot should not be so complicated to get BlendShape works. Thank you for your help. No more effort.
