### ISSUE TITLE
Cannot Tween Gradient Properties

### ISSUE THREAD

**Issue by TheNewGrant** [godotengine/godot#47558]
**Godot version:**
Godot 3.2.1 (Stable)

**OS/device including version:**
Windows 10

**Issue description:**

Cannot tween either the offsets or colors properties of a gradient using either interpolate_property() or interpolate_method() 

I got the error:
_calc_delta_val: Invalid parameter type. Supported types are: bool, int, float, Vector2, Rect2, Vector3, Transform2D, Quat, AABB, Basis, Transform, Color.
with both initial_val and final_val
 
After some digging, I noticed that this case is very similar to Issue #34575 where the Rect2 Variant type was not supported.

**Steps to reproduce:**
Create Sprite and Tween node
Attach gradient resource to texture property of sprite node
Add following script to root node:
```
var gradient_Offset_Start = PoolRealArray([0, 1])
var gradient_Offset_End = PoolRealArray([1, 1])

func _ready():
	$Tween.interpolate_property($Sprite, "texture:gradient:offsets", gradient_Offset_Start, gradient_Offset_End, 1, Tween.TRANS_BACK, Tween.EASE_IN_OUT)
```
**Minimal reproduction project:**

[Tweening Gradient.zip](https://github.com/godotengine/godot/files/6247242/Tweening.Gradient.zip)

**Comment by ShatReal** [comment]
I think #41794 may solve this issue.

**Comment by KoBeWi** [comment]
Not really, #41794 doesn't change interpolation.

**Comment by ShatReal** [comment]
Well, we can use the set_offset method with interpolate_method and pass more than one argument

**Comment by KoBeWi** [comment]
Yeah the new Tweens just got merged, so you can solve this with method interpolation (3.x also has this available, but slightly less convenient)
