### ISSUE TITLE
Godot's Modulo doesn't work with negative numbers

### ISSUE THREAD

**Issue by MyNameIsntBob** [godotengine/godot#47554]
**Godot version:**
Godot Engine v3.2.3

**OS/device including version:**
GeForce GTX 1060 6GB/PCIe/SSE2
Ryzan 5 3600XT
Windows 10
OpenGL ES 3.0

**Issue description:**
Trying to get a mod of any negative number appears to just give -1. 
If you try to do this in python it'll return what you want it to return. 
Godot:
  -1%3  -> -1
Python:
  -1%3  -> 2

**Steps to reproduce:**
put this in your ready function. Than run
print(-1%3)

**Minimal reproduction project:**
Not required

**Comment by Chaosus** [comment]
GDScript modulo is internally using the C/C++ implementation of modulo. The `wrapi`/`wrapf` functions are originally designed to avoid this problem. If you really sure that need to be changed (I pretty sure the Python approach using more complicated logic and slower than C++) you need to create a proposal in https://github.com/godotengine/godot-proposals

**Comment by bruvzg** [comment]
> Trying to get a mod of any negative number appears to just give -1.

There is no standard mathematical definition for modulo with negative numbers, different programming languages implement it in different ways. Godot C implementation, which is "When integers are divided, the result of the / operator is the algebraic quotient with any fractional part discarded. If the quotient `a/b` is   representable, the expression `(a/b)*b + a%b` shall equal `a`."

**Comment by bruvzg** [comment]
> I pretty sure the Python approach using more complicated logic and slower than C++

It is. On x86 / x86-64 it's a single instruction for both `/` and `%`.

**Comment by bruvzg** [comment]
There's `fposmod` built-in function that should behave exactly like Python modulo: `print( fposmod( -1, 3 ) ) ⇾ 2`.

**Comment by MyNameIsntBob** [comment]
Ok, that makes sense. I'll use the fposmod, thanks :D
