### ISSUE TITLE
Export to android - godot 3.3 rc7

### ISSUE THREAD

**Issue by sesenta** [godotengine/godot#47560]
**Godot version** : 3.3 rc7

**OS/device including version:** Pop_Os 20.10

**Issue description:** Can't export to android, i'm using the same paths in editor/settings/export/android than godot 3.2.3 stable, in the export android tab shows : " _invalid android sdk path_", "_unable to find android sdk_" and related errors.

**I can export normaly with the same paths with godot 3.2.3**, i already download export templates for godot 3.3 rc7 from internet and from godot editor, reassign paths and redownload android components with same results

**Steps to reproduce:** export to android with godot 3.3 rc7

**Comment by akien-mga** [comment]
You need to configure the path to your Android SDK as mentioned in the error message.

See the updated documentation for 3.3: https://docs.godotengine.org/en/3.3/getting_started/workflow/export/exporting_for_android.html
