### ISSUE TITLE
Engine crashes on startup

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#47566]
Godot version:
8610867

OS/device including version:
Windows 10, NVIDIA - GeForce MX250

Issue description:
Engine crashes on startup.
> PS C:\Users\chenhy\Desktop\GameDev\Godot\godot\bin> ./godot.windows.tools.64.exe --verbose
> Godot Engine v4.0.dev.custom_build.86108679b - https://godotengine.org
> Using "ICU / HarfBuzz / Graphite" text server...
> Vulkan API 1.2.162
> Using Vulkan Device #0: NVIDIA - GeForce MX250
> - Vulkan subgroup size 32
> - Vulkan subgroup stages STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE
> - Vulkan subgroup supported ops FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
> - Vulkan subgroup quad operations in all stages
> Using "winink" pen tablet driver...
> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] <couldn't map PC to fn name>
> [1] <couldn't map PC to fn name>
> [2] <couldn't map PC to fn name>
> [3] <couldn't map PC to fn name>
> [4] <couldn't map PC to fn name>
> [5] <couldn't map PC to fn name>
> [6] <couldn't map PC to fn name>
> [7] <couldn't map PC to fn name>
> [8] vk_optimusGetInstanceProcAddr
> [9] vkGetInstanceProcAddr
> [10] vk_optimusGetInstanceProcAddr
> [11] vk_optimusGetInstanceProcAddr
> [12] vkGetInstanceProcAddr
> [13] vkGetInstanceProcAddr
> [14] vkGetInstanceProcAddr
> [15] vkGetInstanceProcAddr
> [16] vkCreateComputePipelines (C:\Users\chenhy\Desktop\GameDev\Godot\godot\thirdparty\vulkan\loader\trampoline.c:1313)
> [17] RenderingDeviceVulkan::compute_pipeline_create (C:\Users\chenhy\Desktop\GameDev\Godot\godot\drivers\vulkan\rendering_device_vulkan.cpp:5769)
> [18] RendererSceneGIRD::init (C:\Users\chenhy\Desktop\GameDev\Godot\godot\servers\rendering\renderer_rd\renderer_scene_gi_rd.cpp:2882)
> [19] RendererSceneRenderRD::RendererSceneRenderRD (C:\Users\chenhy\Desktop\GameDev\Godot\godot\servers\rendering\renderer_rd\renderer_scene_render_rd.cpp:4111)
> [20] RendererSceneRenderForwardClustered::RendererSceneRenderForwardClustered (C:\Users\chenhy\Desktop\GameDev\Godot\godot\servers\rendering\renderer_rd\renderer_scene_render_forward_clustered.cpp:3328)
> [21] RendererCompositorRD::RendererCompositorRD (C:\Users\chenhy\Desktop\GameDev\Godot\godot\servers\rendering\renderer_rd\renderer_compositor_rd.cpp:178)
> [22] RendererCompositorRD::_create_current (C:\Users\chenhy\Desktop\GameDev\Godot\godot\servers\rendering\renderer_rd\renderer_compositor_rd.h:84)
> [23] RendererCompositor::create (C:\Users\chenhy\Desktop\GameDev\Godot\godot\servers\rendering\renderer_compositor.cpp:40)
> [24] RenderingServerDefault::RenderingServerDefault (C:\Users\chenhy\Desktop\GameDev\Godot\godot\servers\rendering\rendering_server_default.cpp:403)
> [25] Main::setup2 (C:\Users\chenhy\Desktop\GameDev\Godot\godot\main\main.cpp:1580)
> [26] Main::setup (C:\Users\chenhy\Desktop\GameDev\Godot\godot\main\main.cpp:1387)
> [27] widechar_main (C:\Users\chenhy\Desktop\GameDev\Godot\godot\platform\windows\godot_windows.cpp:151)
> [28] _main (C:\Users\chenhy\Desktop\GameDev\Godot\godot\platform\windows\godot_windows.cpp:185)
> [29] main (C:\Users\chenhy\Desktop\GameDev\Godot\godot\platform\windows\godot_windows.cpp:199)
> [30] __scrt_common_main_seh (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
> [31] BaseThreadInitThunk
> -- END OF BACKTRACE --

Steps to reproduce:
Not applicable.

Minimal reproduction project:
Not applicable.

**Comment by Calinou** [comment]
Can you compile an editor binary with debug symbols included? This way, you can get an accurate backtrace.

**Comment by floppyhammer** [comment]
@Calinou I checked out the page but couldn't figure out what I exactly need to do. I tried to build the editor with `target=debug` but nothing got generated. Could you elaborate a bit?

**Comment by qarmin** [comment]
Have you installed the latest Nvidia drivers?
Looks that 457.67 or 458.06 may fix crash with vkCreateComputePipelines

**Comment by floppyhammer** [comment]
@qarmin I upgraded my driver and it worked. However, with the old driver, the compiled editor had worked fine until a few days ago. I wonder if some core rendering stuff changed recently.

**Comment by Zireael07** [comment]
@floppyhammer: Yes, there were some changes to Vulkan renderer.

**Comment by KoBeWi** [comment]
If it no longer crashes after driver update then the issue is effectively resolved. Just keep your drivers up-to-date always.
