### ISSUE TITLE
Home button on Xbox-like controllers is not recognized

### ISSUE THREAD

**Issue by Saitodepaula** [godotengine/godot#47579]
**Godot version:**
3.2.4 rc3 official

**OS/device including version:**
Windows 10, 64 bit

**Issue description:**
The HOME button on a Xbox like controller (XInput, like the Logitech F310) is not in the [JoystickList](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-joysticklist).

Also, when pressing the HOME button on a Xbox like controller, it returns the scancode 33554431 (Unknown key).

I think this is a fault of the engine, because platforms like Steam expect a game to have an answer to the HOME button, like pausing the game. It can be done with Steam API integration, but why not recognize the button?

Users also expect this, because even if it's not on a specific store/launch hub, on Windows, XInput controllers will open the Xbox Game Bar with the HOME button, and it is good practice to pause the game when that happens.

**Steps to reproduce:**
Just add a script to any project with the code below, and press the HOME button in a Xbox like controller.

```
func _unhandled_input(event):
	if event is InputEventKey:
		print(event.scancode)
```

**Minimal reproduction project:**
See above.

**Comment by Calinou** [comment]
Is that button even visible to third-party input mapping programs? If it's like the Xbox button on official Xbox controllers, there's no way to access it.

**Comment by Saitodepaula** [comment]
> Is that button even visible to third-party input mapping programs? If it's like the Xbox button on official Xbox controllers, there's probably no way to access it from userspace.

Hum, didn't know that this could be the problem...

**Comment by madmiraal** [comment]
This was fixed in 4.0 with #38151 and will be fixed in 3.x with #48934.

**Comment by MrEliptik** [comment]
Should I create a new issue or reopen this one? I still have the problem in Godot 3.5.2. The action is not triggered and printing `event.scancode` in the `_input()` function returns **33554431**, which is unknown. 

I've tested and it works fine in Godot 4.1.

**Comment by AThousandShips** [comment]
Please open a new one, issues that have been marked as solved are not reopened
