### ISSUE TITLE
Error when overriding a function with a parameter type set to an inner class with a function

### ISSUE THREAD

**Issue by osmiumforge** [godotengine/godot#47570]
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

When a class has a method with a parameter that is statically typed to another class's inner class, overriding the function in a child class will cause an error.
This will not happen if the inner class has no functions.

**Steps to reproduce:**

Base.gd:
```gdscript
extends Node
class_name Base
func _error(v: Other.Inner) -> void:
	print(v.data)
```

Inherit.gd:
```gdscript
extends Base
class_name Inherit
func _error(v: Other.Inner) -> void:
	print(v.data)
```

Other.gd:
```gdscript
extends Object
class_name Other
class Inner:
	var data: String
	func _new(dat: String = "Data"):
		data = dat
```

**Minimal reproduction project:**

[inner_error.zip](https://github.com/godotengine/godot/files/6249779/inner_error.zip)

**Comment by Calinou** [comment]
@osmiumforge Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
