### ISSUE TITLE
Values initalized to -0 on conversion/export to TRES format

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4758]
**Operating system or device - Godot version:**

Any OS, Godot 2.0.3 and master.

**Issue description**

When exporting a tileset to the TRES format, some values (typically default ``Vector2`` assignements) are saved with a value of -0, i.e. ``Vector2( -0, -0 )``. When resaving the resource from the inspector, this bug is fixed and the values are changed to ``Vector2( 0, 0 )``.

Excerpt from the related diff:
```
 0/texture = ExtResource( 1 )
 0/tex_offset = Vector2( 0, 0 )
 0/region = Rect2( 0, 0, 64, 128 )
-0/occluder_offset = Vector2( -0, -0 )
-0/navigation_offset = Vector2( -0, -0 )
-0/shape_offset = Vector2( -0, -0 )
+0/occluder_offset = Vector2( 0, 0 )
+0/navigation_offset = Vector2( 0, 0 )
+0/shape_offset = Vector2( 0, 0 )
 0/shapes = [ SubResource( 1 ) ]
 1/name = "Floor2"
```

**Link to minimal example project**

See this example project that reproduces the bug: [bug_zeros.zip](https://github.com/godotengine/godot/files/276497/bug_zeros.zip)

**Comment by unpause** [comment]
i can confirm this
