### ISSUE TITLE
The slider handle is drawn in an imprecise position

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#47588]
**Godot version:**

3.2.3

**OS/device including version:**

Linux

**Issue description:**

The slider handle is drawn in an imprecise position.
![hslider](https://user-images.githubusercontent.com/16458555/113471631-13415580-9477-11eb-8ede-16dbfc4b5139.png)
![hslider max val](https://user-images.githubusercontent.com/16458555/113471636-176d7300-9477-11eb-95d6-b72c9f72ff39.png)

Compounding the problem is that changing the value of the slider sets the `edge` of the handle. It is more correct to set the `center` of the handle texture:

https://material-ui.com/ru/components/slider/
https://codepen.io/qkevinto/full/KzxMdj
https://codepen.io/simeydotme/pen/mJLPPq

The problem is especially noticeable when you create a slider with a transparent handle (custom theme):
![slider](https://user-images.githubusercontent.com/16458555/113472277-89e05200-947b-11eb-9163-e0d5833e7323.png)

it looks confusing, making you think the value is greater than 0.

**Steps to reproduce:**
Add an `HSlider`, zoom in
As you can see there is a gap between slider start and slider handle 

**Minimal reproduction project:**

**Comment by duianto** [comment]
This might have been solved by: Add center_grabber theme property to Slider #69053

**Comment by akien-mga** [comment]
Looks like it indeed.

Fixed by #69053.
