### ISSUE TITLE
Inherited scenes: float variables always seen as custom, can't be reset

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4759]
**Operating system or device - Godot version:**
All OSs, Godot 2.0.3 and master.

**Issue description** (what happened, and what was expected):
In inherited scenes (at least using the TSCN format), float variables appear to always be seen as custom (thus with a button to reset them), and resetting them has no effect:
![spectacle b13401](https://cloud.githubusercontent.com/assets/4701338/15455662/5171eb5c-205b-11e6-85e7-2b0173493ab3.png)

**Steps to reproduce:**
1. Load provided minimal project
2. Check the KinematicBody2D in the inspector: the Margin is shown as modified, even though it has the exact same value as in the base scene.

**Link to minimal example project**:
[bug_inheritance_reinit.zip](https://github.com/godotengine/godot/files/276506/bug_inheritance_reinit.zip)

**Comment by kubecz3k** [comment]
Different but similar issue with inherited exported booleans not working: https://github.com/godotengine/godot/issues/3904

**Comment by bojidar-bg** [comment]
Probably something to do with testing for `float == float` instead of `abs(float - float) < EPS`?

**Comment by akien-mga** [comment]
Most likely. Just need to find the code which tests that :)

**Comment by reduz** [comment]
indeed, just checked and this is due to numerical error,  makes sense due to text scene format

**Comment by reduz** [comment]
closed via push (forgot to write the #)

**Comment by vnen** [comment]
For reference, the commit is f0abda999e179faf1577026d0369062349cb4897.
