### ISSUE TITLE
Editor Settings > Shortcuts Database View is glitchy.

### ISSUE THREAD

**Issue by Bhu1-V** [godotengine/godot#47594]
**Godot version:**

Godot ed2f51b

**OS/device including version:**

Windows 10 

**Issue description:**

The Shortcut Undo, delete, add button is not working as expected in the latest commit.

https://user-images.githubusercontent.com/70578657/113476901-fa976680-949b-11eb-9fc5-8436f625a46c.mp4

**Steps to reproduce:**

In the latest commit build use Editor_settings > shortcuts and try to edit, undo, delete shortcuts.

**Comment by Bhu1-V** [comment]
Most of the bugs were not found when I restarted the editor except for one bug.

* when I press the delete button of a shortcut and then immediately click, delete button of a different shortcut it is showing the previous shortcut keys...
* selecting the given option deletes the input event of the previous shortcut. 

This is demonstrated in the above Video.

**Comment by EricEzaM** [comment]
> * when I press the delete button of a shortcut and then immediately click, delete button of a different shortcut it is showing the previous shortcut keys...
> * selecting the given option deletes the input event of the previous shortcut.

This is a bug with the Tree, not specific to the Editor Shortcuts tree. There is an issue where when a button is clicked, the _previous_ button index/id is the one that is actually sent out in the signal. Not sure if there is already an Issue open for this.

You don't list the bugs in the OP. When you say "most of the bugs were not found when i restarted the editor", what are "most of the bugs", apart from the two that you listed?

**Comment by EricEzaM** [comment]
I did find one issue (PR attached) which may have been causing you some grief. Like I said, the others are common issues with the Tree node (which is a bit of a mess and hard to fix bugs in - I don't know a lot about how it was set up.)

**Comment by Bhu1-V** [comment]
> although it would be nice if you listed them out in text rather than just provided the video 😄.

😁 Sure, there was a lot going on when I was testing. I will update all the bugs I found in the text format.

**Comment by Bhu1-V** [comment]
> You don't list the bugs in the OP. When you say "most of the bugs were not found when i restarted the editor", what are "most of the bugs", apart from the two that you listed?

So as I said earlier it was way glitchy in my 1st test-run where buttons didn't work when I was pressing them. but this problem was solved after restarting the editor.

* The above bug is only seen in `Common` section of the shortcuts.
* In every other section there is no option for adding more than one Input event for a shortcut. (IDK, maybe this is intentional behavior for other sections.)
* In every other section there is a noticeable lag after clicking a button(this needs confirmation from other users.).
* When pressing the `edit` or `erase` button in the `Common` Section the view is scrolling automatically. (this might be because of the pop-up menus that are coming after clicking them.)

**Comment by Bhu1-V** [comment]
After some research, I found why this [bug](https://github.com/godotengine/godot/issues/47594#issuecomment-812852415) is happening:

1. This line connects `button pressed` signal https://github.com/godotengine/godot/blob/ed2f51b15fee22a35d2a975fd77a70fc291bd8de/editor/settings_config_dialog.cpp#L626
2. the emit signal part in tree.cpp is like this
https://github.com/godotengine/godot/blob/ed2f51b15fee22a35d2a975fd77a70fc291bd8de/scene/gui/tree.cpp#L2774-L2778
In which we get the treeItem from the `cache.click_pos` value.

3. `cache.click_pos` is only updated in `tree::propagate_mouse_event()` at https://github.com/godotengine/godot/blob/ed2f51b15fee22a35d2a975fd77a70fc291bd8de/scene/gui/tree.cpp#L1955
but `get_global_mouse_position()` value is derived from `viewport::get_mouse_position()` so when a pop-up is created to add or remove Input Event from shortcut the Viewport is limited to that pop-up so it doesn't update when I click on another ShortCut button which eventually thinks that the TreeItem is at the non-updated position and we unintentionally edit other shortcuts. (I came to this conclusion after printing the `viewport::gui.last_mos_pos` every frame and I saw that when the pop-up is open it didn't print the `mouse_pos` values when I'm not on the pop-up.)

**Comment by EricEzaM** [comment]
@Bhu1-V Thanks again for your help with this, should be fixed now! 🎉

**Comment by Bhu1-V** [comment]
😁
