### ISSUE TITLE
creating shortcuts with same Input Event doesn't raise a warning or error.

### ISSUE THREAD

**Issue by Bhu1-V** [godotengine/godot#47593]
**Godot version:**

godot ed2f51b

**OS/device including version:**

Windows 10

**Issue description:**

When I add the same input event for different shortcuts. The engine doesn't warn me. 
* I know we can have the same shortcut events for different contexts like `Control + C` Copy for editor and scene and `Control + A` for Select All (Script Editor) and Create new node(Scene). 

* but there should be a warning or some-other solution when the same input event is used for different shortcuts of the same context (i.e Editor, Scene Tree, Script Text editor,....).
     - and when I use the shortcut the one which is handled first is being executed. So this is an unintended behavior for users. 

**Steps to reproduce:**
Go to the Editor Settings and in the shortcuts tab try to add the same input event for different shortcuts.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/49527, which has more information about the issue at hand.
