### ISSUE TITLE
Transparent Sprite3D occludes 3D gizmo icon that should always be drawn on top

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#47606]
**Godot version:**
3.3 RC 6, 3.2.2 official

**OS/device including version:**
windows 10

**Issue description:**
Sprite3d with transparent flag on always keep front on the screen, and it will hide the gizmo icon
This image shows the issue, the sprite3d actually behind the light
![image](https://user-images.githubusercontent.com/9168814/113492171-54ce1100-9508-11eb-9549-e37f4faa1186.png)
Left is the transparent, right is without transparent
![image](https://user-images.githubusercontent.com/9168814/113496798-c8cfdf80-952f-11eb-84b4-bdb049bb7a85.png)

Minimal Reproduce
[GizmoBug.zip](https://github.com/godotengine/godot/files/6253913/GizmoBug.zip)

**Comment by Calinou** [comment]
@firecloud888 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by firecloud888** [comment]
> @firecloud888 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

I upload the file, the snapshot describe the issue of the project

**Comment by firecloud888** [comment]
And I found that if you change the editor camera fov to a smaller value(15 degrees), the gizmo icon will become incredible size
![image](https://user-images.githubusercontent.com/9168814/113509793-0b260a80-958a-11eb-92eb-45a53ffe2abb.png)

**Comment by firecloud888** [comment]
Seems like turn alpha-cut to discard will fix this, but that will cause the image outline jagged and looks bad

**Comment by Calinou** [comment]
> Seems like turn alpha-cut to discard will fix this, but that will cause the image outline jagged and looks bad

This is because using alpha testing instead of alpha blending avoids issues related to [transparency sorting](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting). The downside is that hard edges can't be smoothed out by MSAA (but they can still be smoothed out by screen-space antialiasing algorithms like FXAA, which will be available in 3.3).

**Comment by firecloud888** [comment]
> > And I found that if you change the editor camera fov to a smaller value(15 degrees), the gizmo icon will become incredible size
> 
> This is expected, since you are further zoomed in yet the gizmo remains of a fixed size. We need to find a solution that doesn't involve adding too many settings that people must constantly tweak. I suppose adjusting gizmo size to be smaller when using a lower FOV could work, but this won't solve the other 3D gizmo visibility issues we currently have.
> 
> > Seems like turn alpha-cut to discard will fix this, but that will cause the image outline jagged and looks bad
> 
> This is because using alpha testing instead of alpha blending avoids issues related to [transparency sorting](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting). The downside is that its hard edges can't be smoothed out by MSAA (but they can still be smoothed out by screen-space antialiasing algorithms like FXAA, which will be available in 3.3).

You're right, I change the sprite3D to Mesh and set the render priority to -128, it fix, though the 3d axis and grid show always above. Seems the gizmo has different render priority
![image](https://user-images.githubusercontent.com/9168814/113539279-099f2580-9610-11eb-9bb2-f1d68195f295.png)

**Comment by KoBeWi** [comment]
Looks related to #24069

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/24069, as this is due to the same cause.
