### ISSUE TITLE
[GDScript 2.0] var i and var j in nested loops are sharing the same address

### ISSUE THREAD

**Issue by Blackiris** [godotengine/godot#47603]
**Godot version:**
4.0 
ed2f51b15fee22a35d2a975fd77a70fc291bd8de

**OS/device including version:**
Archlinux

**Issue description:**
I have the following function:
```
func _auto_link_nodes():

	var nodes = editorSelection.get_selected_nodes()
	if len(nodes) == 1 and nodes[0] is Graph:
		var graph = nodes[0]
		graph.removeAllLinks()
		var graphNodes = graph.get_children()
		var length = graphNodes.size()

		var obstacles = []
		for graphNode in graphNodes:
			if graphNode.obstacleNodePath:
				var obstacle = graphNode.get_node(graphNode.obstacleNodePath)
				obstacles = appendCollisionObjects(obstacles, obstacle)
				obstacles.append(graphNode.get_node(graphNode.obstacleNodePath))

		print("obstacles: "+str(obstacles))
		print("nbNodes: "+str(length))
		
		var i = 0
		while i < length:
			var j = 0
			while j < length:
				print("Link " + str(i) + "/" + str(j))
				if i != j:
					
					# Some stuff that are currently not executed because of the bug
				jNode += 1
			iNode += 1
```

Please notice the last part of the code starting `while i < length:`, using i and j, with i going from 0 to length in the first loop, then j from 0 to length in the second loop for every each step of i.

**Expected result:**
If length = 2, I should see in the console:
```
Link 0/0
Link 0/1
Link 1/0
Link 1/1
```

**Current result**
If length=2, I see in the console
```
Link 0/0
Link 1/1
```
It means: **i and j are sharing the same variable address!!**

After some debugging, I notice the variable address is assigned in GDScriptByteCodeGenerator::add_local, and I see both i and j are assigned to address 6!!
This value is given by `current_stack_size`, and I notice that its value gets reset in `void pop_stack_identifiers()`  gdscript_byte_codegen.h l.138,
`current_stack_size = current_locals;`
triggered because the previous block being processed first:
```
for graphNode in graphNodes:
	if graphNode.obstacleNodePath:
		var obstacle = graphNode.get_node(graphNode.obstacleNodePath)
		obstacles = appendCollisionObjects(obstacles, obstacle)
		obstacles.append(graphNode.get_node(graphNode.obstacleNodePath))
```

Commenting out l.138 fixes the issue for me. This line was introduced in commit https://github.com/godotengine/godot/commit/2e528ef3829

**Steps to reproduce:**
Start the reproduction project and check the console logs

**Minimal reproduction project:**
[LoopBug.zip](https://github.com/godotengine/godot/files/6253682/LoopBug.zip)

**Comment by Blackiris** [comment]
I was able to create a very small project to reproduce the bug.

```
extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready():
	var nodes = get_children()
	if nodes[0] is Node2D:

		if true:
			var q = 0
		
		var i = 0
		while i < 5:
			var j = 0
			while j < 5:
				print("Link " + str(i) + "/" + str(j))
				
				j += 1
			i += 1
```

The condition `if nodes[0] is Node2D:` seems to be the key.
If I change it to `if true:` or `if 1 == 1:`, the bug disappears.

And as I previously said, the code
```
if true:
	var q = 0
```
Is also needed to trigger the pop_stack_identifiers() method.
I have added the reproduction project in the first post.

**Comment by Blackiris** [comment]
My guess on the problem is in gdscript_compiler.cpp, in GDScriptCompiler::_parse_expression

In `case GDScriptParser::Node::BINARY_OPERATOR:` > `case GDScriptParser::BinaryOpNode::OP_TYPE_TEST:`, the address `GDScriptCodeGenerator::Address operand` (l. 765) **don't have any matching pop_temporary**, such as 

```
if (operand.mode == GDScriptCodeGenerator::Address::TEMPORARY) {
    gen->pop_temporary();
}
```

Indeed, in others case blocks, EVERY GDScriptCodeGenerator::Address xxxx = _parse_expression... gets a matching :
```
if (xxxx.mode == GDScriptCodeGenerator::Address::TEMPORARY) {
    gen->pop_temporary();
}
```


Adding these 3 lines at the end of the `case` fixes the bug. It looks like it is just a forgotten code, but I cannot confirm.

**Comment by vnen** [comment]
@Blackiris yeah, that looks like an oversight. Feel free to open a Pull Request with this fix.

**Comment by Blackiris** [comment]
Hello @vnen, thanks a lot for your feedback! :) The PR should be ready very soon!
