### ISSUE TITLE
Implement rename function in the language server

### ISSUE THREAD

**Issue by astrale-sharp** [godotengine/godot#47609]
**Godot version:**

3.2.3.stable.official

**OS/device including version:**

```
                                       astrale@Sharp
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Linuxmint 20.1 ulyssa
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 5.4.0-70-generic
 MMd      /++                -sNMd:    Uptime: 14h 35m
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages: 4224
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: fish 3.1.0
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution: 1920x1080
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 4.8.6
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Metacity
     NMm  dMM  .mmd  `mmm   yMM. dMM   GTK Theme: Mint-Y-Dark-Red [GTK2/3]
     NMm  dMM`  ..`   ...   ydm. dMM   Icon Theme: Mint-Y-Dark-Red
     hMM- +MMd/-------...-:sdds  dMM   Font: Ubuntu Condensed, 24
     -NMm- :hNMNNNmdddddddddy/`  dMM   Disk: 867G / 1,1T (89%)
      -dMNs-``-::::-------.``    dMM   CPU: Intel Core i3-2330M @ 4x 2.2GHz [63.0°C]
       `/dMNmy+/:-------------:/yMMM   GPU: GeForce GT 630M
          ./ydNMMMMMMMMMMMMMMMMMMMMM   RAM: 3339MiB / 3844MiB
             \.MMMMMMMMMMMMMMMMMMM    
```

**Issue description:**

When editing gdscript code from VScode, with godot connected, i tried using the very handy "rename" feature: (its not a simple find&replace, it renames a variable (or a function) everywhere it is used.) and there was an error message in the console.

**Steps to reproduce:**
open any gdscript file in VScode with godot-tools extension, select the name of a variable, right click -> rename

**Minimal reproduction project:**

Any project after setting up VSCode

*Bugsquad edit (keywords for easier searching): LSP*

**Comment by astrale-sharp** [comment]
I'd be happy to try to implement it,
I believe other function are implemented in modules/gdscript/language_server/lsp.hpp,
I've also read :
modules/gdscript/language_server/gdscript_language_protocol.cpp
modules/gdscript/language_server/gdscript_language_server.cpp

but i'm honestly having trouble understanding how it all works...

I have not much experience in C++ (I understand what the code does, i can successfuly build godot but that's all)
i have some experience coding (mostly python, rust, gdscript :p). I know it may be a little ambitious to start with this issue but I'd like to try!
I also have some experience building games in godot, so classes I see in the C++ code are familiar to me.

**Comment by ray90514** [comment]
You should read : 
modules / gdscript / language_server / gdscript_text_document.cpp
modules / gdscript / language_server / gdscript_workspace.cpp 
modules / gdscript / language_server / gdscript_extend_parser.cpp
There are specific implementation.

**Comment by Razoric480** [comment]
The client will send a `textDocument/rename` request. It sends the position of the text cursor, and the symbol's new name. See https://microsoft.github.io/language-server-protocol/specification#textDocument_rename

This should then be sent to the Workspace class to rename the symbol and re-parse the script. The server is when expected to send a `WorkspaceEdit` object, which includes an array of `TextDocumentEdit` objects where the symbol we want renamed is renamed everywhere it's referenced.

This presents a complication, however, as we can't just do a search and replace. We have to know, for sure, that the symbol being replaced _is_ the variable that was renamed. And there isn't really a fool proof way of knowing that unless everything is strictly type checked and tested and `get_node()` calls are tested.

**Comment by astrale-sharp** [comment]
My idea was the following :
Given we're in a class,
we could (theorically ofc, as im still reading/trying to understand the files and i feel out of my depths :/) rename all occurences where we know we have a instance of the class via typechecking
And it would be ideal to also display an optional replace UI for the parts of the code where it might be that we have a class instance but we're not sure (duck typing).

**Comment by Razoric480** [comment]
I've gone ahead and pushed #48615 and #48616 to implement this.
