### ISSUE TITLE
Constants at function scope are not defined as constants for autocompletion

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#47620]
**Godot version:**
ed2f51b15fee22a35d2a975fd77a70fc291bd8de

**OS/device including version:**
Win10

**Issue description:**

![image](https://user-images.githubusercontent.com/3036176/113510313-ef5b3e00-9562-11eb-9faf-7bdd29da73ea.png)

This shows that `test` is not defined as a constant (however it is a constant), while `test2` is defined correctly in that menu.

**Steps to reproduce:**
^^

**Minimal reproduction project:**
(Too easy to reproduce)

**Comment by Calinou** [comment]
(PS: "IntelliSense" is a Microsoft trademark that should only be used to refer to Visual Studio's autocompletion. Other IDEs/editors do *not* have IntelliSense.)

**Comment by Chaosus** [comment]
Ah.. yeah sorry, I just take the first name from my mind, autocompletion of course..
