### ISSUE TITLE
WebRTC seems to be broken in C# for no visible reason

### ISSUE THREAD

**Issue by Vatyx** [godotengine/godot#47626]
Similar to this issue in that stuff that should work in C# just doesn't - https://github.com/godotengine/godot/issues/42399

**Godot version:**
3.2.3

**OS/device including version:**
* Windows
* HTML/Web

**Issue description:**
For the past two days, I have been battling with getting WebRTC working in a C# godot project. And ran into a few issues with no discernable reason as to why they occur
1. When requesting an offer, the `session_description_created` callback never fired unless I ticked the connection - which other example projects don't have. I created the `WebRTCPeerConnect`, added it to the `WebRTCMultiplayer` object with `AddPeer` and then called `CreateOffer`. The callback never happened unless I ticked.
2. After connecting, no packets were sent over the web. I tried manually sending packets and nothing would happen. Other callbacks on the tree seem to be broken as well, such as peers successfully connecting.
3. I could send packets on Windows but I had MASSIVE packet loss. I would send 100 packets and receive two. I'm not sure why

After porting my implementation to gdscript, everything worked. I'm not sure what's happening here but it seems to be a deep issue. I would go as far to say it might be worth suggesting in the documentation to not use C# for WebRTCMultiplayer stuff to save other people time.

**Minimal reproduction project:**
Unfortunately, I don't have the time to create a clean minimal reproduction project at the moment.

**Comment by steelywing** [comment]
Any update on this issue? Godot 3.4.2 still not working

Here is a reproduction project ([WebRTC GDNative](https://github.com/godotengine/webrtc-native/releases) not included)

[Godot WebRTC.zip](https://github.com/godotengine/godot/files/8129625/Godot.WebRTC.zip)

**Comment by Calinou** [comment]
@Vatyx Can you (or anyone else) still reproduce this bug in [Godot 3.4.2](https://godotengine.org/article/maintenance-release-godot-3-4-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
