### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [godotengine/godot#47658]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays   
    My question is how to build this on linux ubuntu

thank you  
best regards to you  
William

**Comment by akien-mga** [comment]
This is an issue tracker for **bug reports**, not user support.

Please consult the documentation to find how to compile Godot: https://docs.godotengine.org/en/stable/development/compiling/index.html
And use other community platforms for support if you run into issues: https://godotengine.org/community/
