### ISSUE TITLE
Issue with 3D particle properties

### ISSUE THREAD

**Issue by Dente222** [godotengine/godot#47681]
**Godot version:**
3.2.3

**OS/device including version:**
OS: Win 10
GPU: GTX 1660
CPU: Ryzen 5 2600
GLES3

**Issue description:**
Sometimes settings for particles are different in a project from the ones that appear in-game, sometimes they even change properties at random, I managed to record the issue and made a gif out of them.

This is How particles were behaving in the editor and how they should behave in-game
https://i.imgur.com/CM0M9J5.gifv

And here is the actual in-game behaviour
https://i.imgur.com/OI3i3qK.gifv

As you can see, the speed was way off, but this also applies for size and position and probably to other properties too :L

**Steps to reproduce:**
Happens randomly so I can't reproduce it in any way :L

**Comment by Calinou** [comment]
> Happens randomly so I can't reproduce it in any way :L

Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Dente222** [comment]
I wish I could upload something that can reproduce that but the last time this happened was today and before a couple of months ago, in the main time it was working fine :L

**Comment by Dente222** [comment]
> 

This happend at random to me, however, I didn't see this happening ever again, could be a one time thing when godot was updated

**Comment by Calinou** [comment]
Closing for now. Please comment with a minimal reproduction project attached if you can still reproduce this on the latest Godot version.
