### ISSUE TITLE
[Input] Doesnt support some especific key-combinations

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#47685]
**Godot version:**
3.3 rc6

**OS/device including version:**
Windows 10 x64

**Issue description:**
using some key combinations doesnt work with:

`Input.is_action_just_pressed()` & `Input.is_action_pressed()`

So, lets supose you can move your player using WASD , run with SHIFT, and dash with SPACE
If the gamer is using a keyboard he cant simply use some key combinations, i mean pressing 4-5 keys at same time, neither 3 in some cases, for example:

_ps: Ive made this app to show keyboard pressed keys_

**Godot allows:**
SD + SPACE = down-right dash
![image](https://user-images.githubusercontent.com/58845030/113781860-b4ded600-9707-11eb-92c0-3bd718834e17.png)

**But Godot doesnt allows:**
WA + SPACE = up-left dash

![image](https://user-images.githubusercontent.com/58845030/113782002-e48dde00-9707-11eb-8c94-0079ae9c47c6.png)

**Test Results: **

Not allowed combinations:
W+D+SHIFT+SPACE
W+S+SHIFT+SPACE

Allowed Combinations:
S+D+SHIFT+SPACE
A+S+SHIFT+SPACE
A+S+D+SHIFT+SPACE

OBS: if you look, all W related key combinations doesnt work.

**Minimal reproduction project:**
[KeyboardTest.zip](https://github.com/godotengine/godot/files/6267712/KeyboardTest.zip)

**Comment by Zireael07** [comment]
This is likely keyboard ghosting, i.e. a mechanical problem with many keyboards.
