### ISSUE TITLE
resize signals not recognised on html5 localhost

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#47680]
**Godot version:**
3.2.3 stable

**OS/device including version:**
gles 3, linux manjaro

**Issue description:**
Using any node resize() signal or even 
get_tree().get_root().connect("size_changed", self, "_on_resized")

the signal gets called when playtesting on desktop, but gets completely ignored when doing it on html5

**Steps to reproduce:**
you can call some print statements or cause some sprite to disappear
```
func _ready():
        get_tree().get_root().connect("size_changed", self, "_on_resized")
```

playtest in a web browser.

In your web browser, open the debugger and resize it to make the area where godot's canvas is resize.
You will see that its width does update in the dom inspector, but godot is completely unaware of this.

Now do the same with desktop playtest - see it works there.

This is particularly bad if you want to develop a pwa godot app that has a mobile friendly interface as its hard to test how the interface would adapt as the screen gets narrower

**Comment by Calinou** [comment]
@blurymind Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Which stretch mode are you using in the project?

**Comment by blurymind** [comment]
Hmm strange, when the signal is on the root scene, it works fine. I am trying to create a simple reproduce project that pinpoints it.
I suspect it breaks when you have nested scenes
