### ISSUE TITLE
_init arg count errors inheritance error

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#4768]
OS Windows, latest commit

Seems to be an issue most-likely introduced by the new script profiling tools since it only appears to be introduced fairly recently. Certain instantiated GDScript objects with inherited '_init' statements (func _init(args).(parent_args)) will fail with the error message: 'Invalid call to function '_init'. Expected 0 arguments.' Subsequent, attempts to rerun the game project will result in the '0' gradually increasingly randomly, 'Invalid call to function '_init'. Expected 78 arguments.', 'Invalid call to function '_init'. Expected 32758 arguments.', ect., until it finally 'presumably' overflows and gives the error 'Bug, call error: #699553309'. I'm not sure if any of the example projects contain code to reproduce such an error, but for an example, try running the similarly complex Tanks of Freedom project (https://github.com/w84death/Tanks-of-Freedom) to see it reproduced.

**Comment by volzhs** [comment]
duplicated issue #4748

**Comment by SaracenOne** [comment]
Ah, I didn't see that. Might as well close this then.
