### ISSUE TITLE
Nodes such as RichTextLabel with animating BBCode continues using GPU even when hidden, or when BBCode is disabled. 

### ISSUE THREAD

**Issue by rossunger** [godotengine/godot#47687]
Godot version: 3.2.3 and 3.3 rc7

**OS/device including version:**
Alienware m15r3 (2017) gtx1070 / intel GPU,  Windows 10, 1909

**Issue description:**
RichTextLabel with animating BBCode continues using GPU even when hidden, or when BBCode is disabled. 

**Steps to reproduce:**
1) Create blank project. 
2) Add a RichTextLabel. and enable BBcode. Add a BBcode such as: [wave amp=20 freq=4]Some Animating Text[/wave]. 
GPU spikes to 5% usage (in task manager). 
3) Disable BB code. GPU stays at 5%. 
4) Change the BBCode text to something simple, without animations such as "Some normal text". GPU still at 5%
5) Enable BBCode. GPU drops to 0%.

**Expected Behavior**
If you hide the RichTextLabel, or disable the BBcode, it should stop affecting the GPU usage. 

**Other notes**
I have a similar issue with Particles2D, where the gpu usage continues even if the particles are disabled or hidden.

**Comment by Calinou** [comment]
This is related to RichTextEffect; cc @Eoin-ONeill-Yokai.

**Comment by Eoin-ONeill-Yokai** [comment]
@Calinou I'll check this out tomorrow when I get some time. :)
