### ISSUE TITLE
Ctrl+clicking `Vector2.move_toward()` member method points to GDScript builtin `move_toward()`'s documentation

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#47692]
**Godot version:** Godot 3.2.3stable, Godot 3.3 rc7

**OS/device including version:**Win64

**Issue description:**

The Vector2.move_toward() method seems to be misconfigured, appearing as move_toward(from,to,delta).
See https://github.com/godotengine/godot-docs/issues/4820

**Steps to reproduce:**
paste this code into your script and notice "move_toward" is marked in red, indicating a keyword. Ctrl-leftclick on "move_toward to get to the [@GDScript move_toward API documentation](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-move-toward) instead of the[ Vector2 API docs](https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-move-toward).
```
var test_vec = Vector2(100,100)

func _process(delta):
	test_vec = test_vec.move_toward(Vector2.ZERO, 5)
	print(test_vec)
```

**Comment by akien-mga** [comment]
To clarify, it's not the method being misconfigured, it's the symbol resolution logic of the editor which finds the wrong match. The code should likely not look up builtin methods when trying to resolve symbols for `some_var.method`, as those would always be either member methods or properties.

**Comment by VedatGunel** [comment]
Seems to be fixed in `master`.
![test](https://user-images.githubusercontent.com/56537502/115070337-7d3d0e80-9efd-11eb-8e52-eb38856f6857.gif)
