### ISSUE TITLE
A tool script with SVG icon makes the editor lag when adding or removing child nodes

### ISSUE THREAD

**Issue by Hoimar** [godotengine/godot#47698]
**Godot version:**

3.3.rc8 (but also 3.2.x)

**OS/device including version:**

(X)Ubuntu 20.04

**Issue description:**

A bit of a weird issue, so here goes: In a scene with a `Node` that has a tool script attached to it which has an SVG icon, the editor lags as soon as you add or remove child nodes in the script.
The same does not happen when you run the scene **or** when you use an image as icon instead, so it seems to be the way Godot handles a vector graphics icon when the scene tree is refreshed?
While narrowing it down I ran `strace -p <PID of Godot>` and found that in the editor, the icon file (be it png or svg) is opened every frame:
```
[...]
stat("/path/to/icon.svg", {st_mode=S_IFREG|0664, st_size=2841, ...}) = 0
openat(AT_FDCWD, "/path/to/icon.svg", O_RDONLY) = 15
[...]
```
But I guess that's normal.

**Steps to reproduce:**
- create a scene with one `Node`
- attach a tool script (content below) to it which has a `class_name` and an SVG icon
- save everything, then tick the "Run In Editor" box in the inspector
- the editor slows down, taking 160ms for a single frame cycle

Tool script content:
```
tool
class_name ToolScript, "res://icon.svg"
extends Node

export var run_in_editor: bool = false
var time_prev = OS.get_ticks_msec()

func _process(delta):
	if Engine.editor_hint and not run_in_editor:
		return
	var n = Node.new()
	add_child(n)
	print("Adding %s after %dms." % [n, OS.get_ticks_msec() - time_prev])
	time_prev = OS.get_ticks_msec()
```

**Minimal reproduction project:**

[MCVE Project.zip](https://github.com/godotengine/godot/files/6271170/MCVE.Project.zip)
Open the project, everything should run smoothly. Tick the "Run In Editor" box and it will lag (output: >160ms). Run the scene and it will be smooth (output: ~16ms).

**Comment by Hoimar** [comment]
Is this perhaps related to #42096?

**Comment by Calinou** [comment]
> so it seems to be the way Godot handles a vector graphics icon when the scene tree is refreshed?

Godot is rasterizing the SVG every time is loaded, since the icon isn't being cached.
