### ISSUE TITLE
Crash On Making Convex Collision Mesh Out of Terrain

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#477]
Hey, there. I've found a crash on attempting to create a convex physics collision mesh out of a hilly terrain object. I thought it was because the terrain is not convex, but the crash doesn't seem to occur on a (what I think was) simpler concave mesh.

In any case, to reproduce, download and open the attached scene file, click on the Plane (terrain) mesh, and select "Create Convex Collision" from the Inspector's "gear" options menu. Godot will then crash. Here's the link:

https://copy.com/7ooRIxKja7wY

If this is a matter of it being an "intended bug" because I'm using it incorrectly, then a check to find concave polygons and abort before a crash would probably be a good idea. Or perhaps it could be automatic, and go with a trimesh collision mesh if there are concave lines, and a convex mesh otherwise (though, informing the developer might be a good idea).

I have:

AMD Athlon II X2 250 3.0 GHZ Processor
Windows 7 64-bit
4GB RAM
AMD Radeon HD 7750
Godot Win 32-bit 1.0 Development version from the homepage, 5/29/14

Anyway, thanks a lot for reading!

**Comment by akien-mga** [comment]
I've tried to reproduce using the test scene provided above, but got no crash, so I'll assume this has been fixed.
