### ISSUE TITLE
HTML5 Mono Build - Signals can't call methods on parent classes

### ISSUE THREAD

**Issue by animanmaster** [godotengine/godot#47707]
**Godot version:**

3.3-rc8

**OS/device including version:**

Windows 10 Home OS Build 19041.867

**Issue description:**

I have a NetworkService class extending Node that has a virtual MakeRequest method, and a virtual OnRequestComplete method, and in its _Ready method I add an HTTPRequest object as a child and connect the HTTPRequest instance's "request_completed" signal to "OnRequestCompleted." I also have an AssetService class that is derived from this NetworkService base class.

In the editor/desktop build (and even in a web build in 3.2.3-stable), this works fine, but in the HTML5 build, when the AssetService makes an HTTP request, I get a message in the DevTools console that says something to the effect of  "Cannot find method on Node(AssetService.cs):OnRequestCompleted". If I add an `OnRequestCompleted` method to AssetService that just calls `base.OnRequestCompleted`, I no longer get that error in the console.

**Steps to reproduce:**

* Connect a signal from a node to a class where the method to call for that signal is only defined in the parent class.
* Trigger that signal in an HTML5 build of the project and see the error message in the console.

**Minimal reproduction project:**

I can try to whip up a minimal project a little later, but here's the NetworkService I mentioned above:

```csharp
using Godot;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace Duel
{
    public class NetworkService : Node {
        protected HTTPRequest request;
        protected string lastResponse;

        // Called when the node enters the scene tree for the first time.
        public override void _Ready()
        {
            // Create Network client
            request = new HTTPRequest();
            AddChild(request);
            request.Connect("request_completed", this, "OnRequestComplete");
        }

        // Credit to https://www.reddit.com/r/godot/comments/9blz7b/parsing_json_from_httprequest_in_c/ for this.
        protected virtual void OnRequestComplete(int result, int response_code, string[] headers, byte[] body) {
            GD.Print($"Request completed: {result}, {response_code}, {headers}, {body}");
            lastResponse = Encoding.UTF8.GetString(body);
        }

        protected virtual async Task<T> MakeRequest<T>(string url, HTTPClient.Method method = HTTPClient.Method.Get, string body = "") {
            T result = default(T);
            var token = AuthenticationService.Token;
            List<string> headers = new List<string>();
            if(token != null) { headers.Add($"Authorization: {AuthenticationService.Token}"); }
            if(body != "") { headers.Add($"Content-Length: {body.Length}"); }
            var error = request.Request(
                url: url,
                customHeaders: headers.ToArray(),
                method: method,
                requestData: body
            );
            if (error == Error.Ok) {
                GD.Print($"Awaiting request {url}");
                await ToSignal(request, "request_completed");
                GD.Print("Deserializing...");
                result = JsonConvert.DeserializeObject<T>(lastResponse);
                GD.Print("Deserialized");
            }
            return result;
        }
    }
}
```

If you add a class that extends that and then call `MakeRequest` on that subclass instance, you should run into the same issue.

This and a regression on https://github.com/godotengine/godot/issues/44631 are preventing an HTML5 build of my game from working in 3.3-rc8 so far.

**Comment by animanmaster** [comment]
Tried my project out on 3.3-rc9 too, getting the same error as in rc8:

![image](https://user-images.githubusercontent.com/764580/115493963-b1346e80-a232-11eb-94f1-c6f75a9de00e.png)

**Comment by animanmaster** [comment]
Update on this... I changed NetworkService to no longer be async and instead use signals and SignalAwaiters, and I no longer hit this in 3.3-stable. Without that change, this error pops up on 3.3-stable too.

**Comment by akien-mga** [comment]
No answer, closing. Please comment if you can still reproduce it in latest releases.
