### ISSUE TITLE
GDScript 2.0: Breakpoints not hit in nested classes

### ISSUE THREAD

**Issue by BMagnu** [godotengine/godot#47706]
**Godot version:** 4.0.dev.custom_build. 55faf1c874fae5b67928395d3a35889bbb4e458b
Works fine on 3.3 RC8

**OS/device including version:** Win10 64bit

**Issue description:**
Breakpoints on code in functions of a nested class will not be hit

**Steps to reproduce:**
1. Add a node to a scene with a custom script
2. Create a nested class with a function in that script and set a breakpoint at any point in the function
3. Create an object of the nested class and call that function during _ready() of the node
4. Run the scene, the breakpoint will not be hit

**Minimal reproduction project:**
[NestedClassBreakpoint.zip](https://github.com/godotengine/godot/files/6273935/NestedClassBreakpoint.zip)
Remember to actually add a breakpoint on line 10 or 11 of the script file to reproduce the bug with this reproduction project.

**Comment by lyuma** [comment]
Still confirmed on latest master 85186bc

**Comment by vnen** [comment]
I cannot reproduce on current master, probably was fixed along the way.
