### ISSUE TITLE
Mouse pointer add vertical offset when using 2th monitor

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#47719]
**Godot version:**

3.3-rc8 mono

**OS/device including version:**

Debian 10

**Issue description:**

when I move the editor in 2th monitor The mouse pointer have one row of vertical offset. Example: To be able to click a certain folder I have to move the mouse cursor in the line below. 
Or
The entire editor is moved one-ish row toward top
![DeepinScreenshot_20210408111927](https://user-images.githubusercontent.com/13235119/114001652-6abb3900-985c-11eb-94e8-a837c608d59d.png)

ps: you can adjust the title if you think it will be more correct ;)

**Steps to reproduce:**
See before

**Minimal reproduction project:**

NA

**Comment by akien-mga** [comment]
Is it specific to 3.3 or do you have the same issue with 3.2.3?

**Comment by Calinou** [comment]
I've been able to reproduce this in the script editor since 3.1 or so, but I've never figured out consistent reproduction steps for this.

**Comment by git2013vb** [comment]
> Is it specific to 3.3 or do you have the same issue with 3.2.3?

Just in the 3.3. The 3.2.3 work fine.
I think its enough to have a 2th monitor in linux .  Its not related to any projects I think.

**Comment by akien-mga** [comment]
I can't reproduce it on Mageia 9 running KDE Plasma 5.21.3 with KWin display manager.

What DE are you using on Debian 10? And is it X11 or Wayland?

**Comment by git2013vb** [comment]
> I can't reproduce it on Mageia 9 running KDE Plasma 5.21.3 with KWin display manager.
> 
> What DE are you using on Debian 10? And is it X11 or Wayland?

ExecStart=/usr/sbin/lightdm

(base) vale@debianace:~$ systemctl status display-manager
● lightdm.service - Light Display Manager
   Loaded: loaded (/lib/systemd/system/lightdm.service; indirect; vendor preset: enabled)
   Active: active (running) since Thu 2021-04-08 00:28:17 CEST; 12h ago
     Docs: man:lightdm(1)
  Process: 788 ExecStartPre=/bin/sh -c [ "$(cat /etc/X11/default-display-manager 2>/dev/null)" = "/usr/sbin/lightdm" ] (code=exited, status=0/S
 Main PID: 800 (lightdm)
    Tasks: 7 (limit: 4915)
   Memory: 273.7M
   CGroup: /system.slice/lightdm.service
           ├─800 /usr/sbin/lightdm
           └─834 /usr/lib/xorg/Xorg :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch

**Comment by akien-mga** [comment]
Sorry I used wrong terminology, I meant what is your desktop environment? GNOME, Plasma, Mate, Cinnamon, Openbox, etc.

And are you using Wayland or X11?

**Comment by git2013vb** [comment]
![image](https://user-images.githubusercontent.com/13235119/114015967-a3620f00-986a-11eb-8a90-ca0de44844bc.png)

No problem :)

**Comment by akien-mga** [comment]
It seems to be specific to Optimus and related to #48091, let's consolidate both issues there as they likely have the same root cause (Bumblebee bug).
