### ISSUE TITLE
GDScript 2.0: StringName Literals and Constants don't work as dictionary keys

### ISSUE THREAD

**Issue by BMagnu** [godotengine/godot#47721]
**Godot version:** 4.0.dev.custom_build. 55faf1c874fae5b67928395d3a35889bbb4e458b

**OS/device including version:** Win10 64bit

**Issue description:**
Using a StringName literal to access a dictionary fails.

**Steps to reproduce:**
1. Create a dictionary that contains a StringName key.
2. Access this key's value by using a StringName literal or a const StringName variable
```
var dict : Dictionary = { StringName("Test") : 1 }
var test1 : StringName = StringName("Test")
const test2 : StringName = StringName("Test")
dict[test1] #Works
dict[test2] #Fails
dict[StringName("Test")] #Fails as well
```

**Minimal reproduction project:**
[StringNameLiterals.zip](https://github.com/godotengine/godot/files/6277741/StringNameLiterals.zip)

**Comment by Blackiris** [comment]
I have tried with the following script (yours + print to see):

```
extends Node

func _ready():

	var dict : Dictionary = { StringName("Test") : 1 }
	var test1 : StringName = StringName("Test")
	const test3 : StringName = StringName("Test")
	print(dict[test1]) #Works
	print(dict[test3]) #Fails
	print(dict[StringName("Test")]) #Fails as well
	print(dict["Test"]) 
```

The output is
```
1
1
1
1
```

It looks like the bug is fixed in the latest build.

**Comment by Calinou** [comment]
This was likely addressed by https://github.com/godotengine/godot/pull/50057, closing.
