### ISSUE TITLE
GDScript 2.0: Iterator over typed arrays is not typed

### ISSUE THREAD

**Issue by BMagnu** [godotengine/godot#47722]
**Godot version:** 4.0.dev.custom_build. 55faf1c874fae5b67928395d3a35889bbb4e458b

**OS/device including version:** Win10 64bit

**Issue description:**
When iterating over a typed array with ``for i in array:``, the iterator i is not typed in respect to the typed array.
Neither are there editor code completion suggestions, nor errors when the variable is incorrectly cast to a different type.
It should be typed to the type of the array

**Steps to reproduce:**
1. Create a typed array.
2. Iterate over the array with a for in loop
3. No auto-completion suggestions are shown, illegal casts are not detected
```
var array : Array[Vector3] = [Vector3()]
for i in array:
	i.length() # Not automatically suggested, but should be
	(i as Vector3).length() # Correct, but cast should not be necessary
	(i as StringName) == "" # Incorrect, should throw an incompatible cast error
```

**Minimal reproduction project:**
[TypedArrayFor.zip](https://github.com/godotengine/godot/files/6277770/TypedArrayFor.zip)

**Comment by KoBeWi** [comment]
It's probably because typed `for` loops aren't supported yet.

**Comment by BMagnu** [comment]
Yeah, they are probably just "not yet implemented".
Still, the existence of typed arrays now imply that it should be implemented, as not being able to have the iterator typed defeats the purpose of typed arrays for a lot of use cases (pretty much everywhere I'd use a typed array, I'd need to also iterate over the array, removing the typing again).
I agree, that might make it more an enhancement than a bug. 
In any case, not typing a for loop when iterating over a typed array exists seems almost more like an oversight than an intentionally left-out feature to me.

**Comment by KoBeWi** [comment]
Seems fixed.
