### ISSUE TITLE
Remote Inspector: ability to inspect memeber variables as well

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4773]
**Operating system or device - Godot version:**
2.1 alpha
**Issue description** (what happened, and what was expected):
Remote inspector would be even more handy if it would allow not only to inspect exported variables, but 'normal' ones as well.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
What's the status on this issue in both the master branch and 2.1/HEAD with the improved debugger?

**Comment by Zireael07** [comment]
Remote inspector in 2.1.4 beta (the August build) doesn't seem to show local variables.

**Comment by kubecz3k** [comment]
In current master db7f49183357c282e267c0743411505eb61f1c6f it's still showing only exported variables

**Comment by Calinou** [comment]
This seems to have been implemented a while ago, closing. Here's a screenshot in https://github.com/godotengine/godot/commit/d711c57d767734887fbf0955a7b9902c54498a0d:

![image](https://user-images.githubusercontent.com/180032/71406839-9f8c8800-2639-11ea-8a0f-6626243c6d15.png)
