### ISSUE TITLE
can't zoom out more than 250 units

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#47736]
**Godot version:** 3.3 RC8

**OS/device including version:** Windows 10

**Issue description:** scrolling wheel stops zoom out at 250 units away no matter what I'm focused on. Was expecting same behaviour as 3.2, where you can zoom out much farther

**Steps to reproduce:**
Make new project, zoom out with scroll wheel

**Comment by Calinou** [comment]
This is an intentional change to prevent zooming out from hiding the zoom origin due to the far clip plane.

To change this, increase the far clip plane distance in the 3D viewport's **View** menu.
