### ISSUE TITLE
Custom Signal fired twice 

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#47731]
**Godot version:**

3.2.3 mono

**OS/device including version:**

Debian 10

**Issue description:**

When I remove a _Ready() Method from an Inherited scene a custom signal will be fired twice. I'm not sure if it is related to issue #28857

**Steps to reproduce:**
See project attached

**Minimal reproduction project:**

[TestInheritedScene.zip](https://github.com/godotengine/godot/files/6280563/TestInheritedScene.zip)

**Comment by git2013vb** [comment]
Ah. Ok. There is some kind of documentation that explain in details how it work? Because its yet not clear to me how it is supposed to work.

Thank you.

**Comment by kleonc** [comment]
Not sure which part you don't understand. How signals work and when `_Ready` is called is for sure explained in the Godot docs (somewhere in the basics). How `virtual` methods (like `_Ready`) work and what `override` keyword does is a C# stuff and you can find it in its docs.

Maybe changing your `Control.cs` to:
```
using Godot;
using System;

namespace Test
{
	public class Control : Godot.Control
	{
		public override void _Ready()
		{
			Node signalOwner = GetTree().Root.GetNode("Global");
			string signalName = nameof(Global.MainLoaded);
			Node methodOwner = this;
			string methodName = nameof(TestSignal);

			GD.Print($"Connecting {methodName} method of {Info(methodOwner)} to {signalName} signal of {Info(signalOwner)}");
			signalOwner.Connect(signalName, methodOwner, methodName);
		}

		public void TestSignal()
		{
			GD.Print($"Signal fired, handled by {Info(this)}");
		}

		private string Info(Node node) => $"{node}@{node.GetPath()}";
	}
}
```
will help you understand what's happening.
Also an advice: to avoid confusion don't name your classes the same as the Godot built-in classes (like you've done with the `Control` here).

**Comment by git2013vb** [comment]
Thank you for the explanation. I've already understood roughly the two scenes+c# scripts relation. What is missing, I think, is exactly such behaviour when we use signals that is not explained in docs ( I didn't see it so far but please link me a location if I'm wrong) for this case specific. It is confusing to me because we talk about scenes and scripts in godot engine and sometime it is not clear how they behave in some particular configuration. I cant be more specific here but I used c# in godot for a while now - and before that gdscipt - and often I find doc not particular clear. Maybe its me that is used to read technical stuff from other sources for other things that are made in different way ( can I say with a more standard approach?). Anyway it is a not easy discussion and this is not , I guess , the right place to do that.
Thank you for your explanation again. If wasn't you I will never guessed such code behaviour about Signals.

**Comment by kleonc** [comment]
After revisiting this, I don't see anything to improve here. As explained above there's no bug in here, things work correctly, there's just some misunderstanding. And as I previously said:

>How signals work and when `_Ready` is called is for sure explained in the Godot docs (somewhere in the basics). How `virtual` methods (like `_Ready`) work and what `override` keyword does is a C# stuff and you can find it in its docs.

Hence I'll close this issue.

If some "how signals work" docs need to be improved then it should be addressed/reported in https://github.com/godotengine/godot-docs.
