### ISSUE TITLE
Error when compiling godot

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [godotengine/godot#47739]
Godot version:
trying to compile Godot 3.3 RC 8(the most recent at the time of this writing)

Device:
Raspberry pi 4

Issue description:
Im trying to compile godot 3.3 RC 8 on my rpi4 and it was working for a while then it ran into an error. I would be very thankful for any help. Let me know if you need any more information.
![2021-04-08-165133_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/114109748-c0a6d580-988a-11eb-8b61-5bcd11dfe731.png)

**Comment by Calinou** [comment]
You need to disable the WebM module when compiling for ARM on Linux. Append `module_webm_enabled=no`

**Comment by The-Sapphire-Starship** [comment]
I did that and it worked for a while, it did a lot more compiling, then it came up with another error:
![2021-04-08-180101_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/114113891-8b9f8080-9894-11eb-9668-ed4229ed40c4.png)
