### ISSUE TITLE
Bizarre, inaccurate force or acceleration applied to 2D rigid body with collision polygon.

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#47745]
**Godot version:** 3.2.3

**OS/device including version:** Windows 10, GLES2

**Issue description:** Really bizarre "force"/acceleration applies to 2D rigid body with a collision polygon after collision, forcing it to the left.  I was trying to recreate another physics bug, but this behavior was so bizarre, I felt it needed to be reported.  Not sure how to even properly describe this, so here's a gif:

![EswGbm3hqP](https://user-images.githubusercontent.com/7751182/114161200-cdacde80-98f5-11eb-8b85-e187e0cb2d69.gif)

**Steps to reproduce:**  Create a RigidBody2D with CollisionPolyon2D collision  -- something vaguely ring-like in shape.  Let it drop onto a static body that's also a RigidBody2D. (Note: This is pretty much exactly what I did with Goop Loop, and that ring did not have nearly this strange of a behavior, so maybe there's something specific with what I did in this example project):

**Minimal reproduction project:**
[test_wonky_left_movement_on_rigid_body.zip](https://github.com/godotengine/godot/files/6284744/test_wonky_left_movement_on_rigid_body.zip)

Edit: Tried creating a new project from scratch and it had the exact same behavior, even though the shape was different.  Strange.

Edit2: Realized the reason for this problem.  My collision is off-center from the rigid body origin.  Not sure what the expected behavior is here, but maybe this isn't a bug.

**Comment by akien-mga** [comment]
> Edit2: Realized the reason for this problem. My collision is off-center from the rigid body origin. Not sure what the expected behavior is here, but maybe this isn't a bug.

I guess this might be expected behavior then since the calculated moment of inertia will likely induce an acceleration if the body is not in a stable state. CC @godotengine/physics to review.

**Comment by madmiraal** [comment]
Yes, it's behaving as expected. I've put our Godot logo at the centre of mass and zoomed out to show you what is happening, and you can see that it's behaving as expected:

![47745](https://user-images.githubusercontent.com/9253928/114198365-23f83c80-994b-11eb-8a77-e62ee346c373.gif)

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/945.

**Comment by akien-mga** [comment]
It might be interesting to add a debug visualization of the center of mass in the editor (though that's material for a proposal :)).
