### ISSUE TITLE
Can't revert editor shortcuts

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#47743]
**Godot version:**

e8f3fa6

**Issue description:**

In the editor settings shortcut section, you can't revert the shortcut nor remove it. Pressing any button will open the Event Configuration dialog, as if the pencil button was pressed:
![image](https://user-images.githubusercontent.com/2223172/114157845-5b072780-9924-11eb-8950-d7f9a232745c.png)

**Comment by EricEzaM** [comment]
Fixed in #47596
