### ISSUE TITLE
Zoom in 2D editor doesn't stay centered on the mouse

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#47756]
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

(I'm not moving my cursor while I'm zooming)

https://user-images.githubusercontent.com/50304111/114213609-6c4e3500-9920-11eb-9ddd-8b16305d8585.mp4

**Steps to reproduce:**
Try hovering your mouse over an object and zoom in and out

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This occurs because the editor view is constrained. See https://github.com/godotengine/godot/pull/47628.

**Comment by Macksaur** [comment]
I fixed this in https://github.com/godotengine/godot/pull/73223 but constraining might be being entirely removed.
