### ISSUE TITLE
Drag&Drop Ability to reorder scripts in script view 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4775]
**Operating system or device - Godot version:**
2.1 alpha

**Issue description** (what happened, and what was expected):
There is no way to reorder scripts on a script list dock currently:
![script_doc](https://cloud.githubusercontent.com/assets/6129594/15469309/c6928c50-20e9-11e6-8d92-9b5cf40e85fb.png)
**Link to minimal example project** (optional but very welcome):

**Comment by Dillybob92** [comment]
The scripts are alphabetically listed too, which is nice. So maybe after we drag them around, we can sort them back:
![image](https://cloud.githubusercontent.com/assets/10387670/15469716/fc019410-20a0-11e6-9dcd-0956bfb19a3e.png)

**Comment by trollworkout** [comment]
@Dillybob92  You can move them around or go back to default sorting.  Very nice both ideas I support.

**Comment by reduz** [comment]
I haven't seen any IDE that lets you sort the list of open files, it's
generally alphabetical..

**Comment by bojidar-bg** [comment]
@reduz ~ Even if we don't allow it, it would be nice to be able to list open files in a tree-like fashion, especially when there are scripts with the same name in different folders.

Allowing for drag and drop reordering would mean less trouble for users that want it another way.

**Comment by trollworkout** [comment]
I was thinking you could probably remove the side bar altogether and use the tabs up top instead which could also be freely re-organized

**Comment by vnen** [comment]
I personally like the way [Visual Studio Code](https://github.com/Microsoft/vscode) handles this. It shows a list of working files in order of opening (those can be dragged and reordered) and also a tree of files below.

![code_2016-05-25_16-04-47](https://cloud.githubusercontent.com/assets/5599796/15552871/dc8636ba-2292-11e6-968d-498a61f5fa3d.png)

**Comment by kubecz3k** [comment]
@reduz About that editor sorting opened files list: I would request code tabs reordering (which every code editor have), but we don't have tabs so I'm requesting ability to reorder the thing that we have...

**Comment by kubecz3k** [comment]
@reduz But in the end I'm able to understand the reason why we might not have this functionality and I would love to just hide this panel and depend on `Open dominant script on scene change` option but unfortunately it's not working very well and it's hard to use it without script panel (which for me is almost always bloated by very high amount of opened scripts).

**Comment by reduz** [comment]
there used to be tabs, but the horizontal space would be cluttered really
quickly

regarding high amount of scripts, i'm not sure if having them ordered by
date opened would be a good idea, it's really easy to add this back,
including drag&drop rearranging, but would it really be an improvement?

If it helps, you can always use alt-ctrl-o and type the name of the script,
this generally works best when you have that many..

**Comment by reduz** [comment]
regarding opening the dominant script, if you find a bug, please let me
know.. would not be nice if this fails

**Comment by kubecz3k** [comment]
@reduz I'm also not so sure if reordering by opening time is the best option, in general I would like to describe my user case because there are reasons why script panel is not usable for me (why I'm ending with so many scripts opened):
* first: I'm using `Open dominant script on scene change` (not blaming the option just explaining use case, the current main problem of this option is described here: https://github.com/godotengine/godot/issues/3638)
* second: I don't remember how my scripts are named :) There are couple hundred of scripts in project like Steam Quest, and usually I'm navigating to them by opening some main scene in which I have smaller ones and so on until I find the scene in which there is script that is interesting for me.

**Comment by kubecz3k** [comment]
So opening each of those scenes in the process is giving me new script in script tabs.

**Comment by Biliogadafr** [comment]
I thought that this list of opened files is actually vertical tabs :). Even in browsers I use options to display tabs vertically(because in this case I can handle more tabs). If this list doesn't display all tree, this is tabs, right? :) And I also missing a feature to arrange this vertical tabs like I want. Especially if opened scripts is messed with opened class docs. Actually it would be nice to have it like in Visual Studio Code or QTCreator(usually configured in the same way). They have filesystem tree and vertical tabs in one vertical panel.

**Comment by reduz** [comment]
I left the code open to implement rearranging of scripts, we can try it
easily, but I seriously doubt it's going to help organization if you have a
lot of open ones..
Aren't better ways to do this?

kubecz3k: How about using a tree? could add an option so files are shown
together with a Tree of the filesystem..

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by bojidar-bg** [comment]
I think we might do it better if we allow assigning categories to scripts, and then sorting them by said categories.
That would be useful for me since sometimes, when I do a big refactor, I have two groups of open scripts, new and old. Also, it would be pretty useful to be able to divide them into "objects", "skills", etc., without having to prefix them for a nicer alphabetical sort.

**Comment by Dillybob92** [comment]
I really like @bojidar-bg's idea of the categorical approach.

Real world example:
![sug1](https://cloud.githubusercontent.com/assets/10387670/19033140/c9ba419e-8911-11e6-949d-cf93d5b8a22e.png)

**Comment by bojidar-bg** [comment]
@Dillybob92 I disagree a bit though, using the parent folder of a script is not the best idea in some cases. Example (real-world):
```
res://
- creatures
  creature.gd
  - heroes
    - <name>
      <name>.gd
      <name>_skill1.gd # Or whatever
- ...
```

In this case it would categorise all heroes under their respective name, which won't be better than before, and would be certainly worse than a simple tree of folders with scripts...

**Comment by Dillybob92** [comment]
Yah, maybe a checkmark for recursive directory? I was just thinking of something like this:

![image](https://cloud.githubusercontent.com/assets/10387670/19034186/002688dc-8917-11e6-8486-4fcedca3af0e.png)

But yeah, you're right. it will most likely be messy
