### ISSUE TITLE
Custom Type which hides mouse cursor on its script, hides mouse cursor in editor too.

### ISSUE THREAD

**Issue by immccc** [godotengine/godot#47768]
**Godot version:**
v3.2.3.stable

**OS/device including version:**
Windows 10

**Issue description:**
I am trying to create a custom type within a plugin which is a cursor with extended capabilities, such as animations, signals, etc.
Point is, as hardware cursor does not accept animations, it needs to be hidden, so the custom type script includes

`Input.setMouseMode(MouseMode.MOUSE_MODE_HIDDEN )` 

Problem is, this is hiding the cursor in Godot editor as well, whereas I'd expect that it's hidden only on the scene it belongs to its tree while running/debugging.

 I think this behavior is correct in case of controls added by the plugin. But certainly not for custom types added by the plugin.

**Steps to reproduce:**
1. Create a Godot plugin.
2. Register in the plugin one custom type with its own script.`
    - Bear in mind that script should have `tool` keyword on the very beginning of it. 
3. In the custom type script, place `Input.setMouseMode(MouseMode.MOUSE_MODE_HIDDEN` in either `_enter_tree()` or `_ready()`.
4. Enable plugin and verify custom type is reachable when a new node is requested to be created from editor. 
5. Create a testing scene.
6. In the scene tree, add the created custom type. 
7. Check that mouse cursor dissapears within the editor.

**Comment by Calinou** [comment]
@immccc Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by immccc** [comment]
> @immccc Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> Also, to guard specific code from running in the editor in `tool` scripts, use `if Engine.editor_hint`. This evaluates to `true` only when the script is running in the editor, and evaluates to `false` otherwise.

No need to. Just check Engine.editor_hint and that made the trick, thanks!
