### ISSUE TITLE
EditorPlugin.get_editor_interface().set_main_screen_editor() doesn't change main screen

### ISSUE THREAD

**Issue by nonfinity** [godotengine/godot#47763]
Godot version: v3.2.3.stable.official

OS/device including version: Windows 10

Issue description:
Currently building a main screen plugin with a GridEdit as the primary view for the main screen plugin. When a GraphNode is selected, I catch the signal and use inspect_object(object) to load that specific GraphNode in the Inspector. 

Expected behavior: the selected graph node details appear in the inspector
Observed behavior: the selected graph node details appear in the inspector and the main screen is switched to the 2D view

Attempted work around: after calling inspect_object(object), I try to manually set the main screen back to the plugin screen with set_main_screen_editor(plugin_screen), but it doesn't work. I also attempted to directly reset the visibilty of the 2D and the Plugin screens, but this did not work either

Steps to reproduce in attached project:
1. Open project
2. Click "Plugin01" in main screen editors list
3. Click on the GraphNode that says "Click Me"

[plugin_test_01.zip](https://github.com/godotengine/godot/files/6289169/plugin_test_01.zip)

**Comment by rainlizard** [comment]
This appears to already be fixed, try a more recent version of Godot.

**Comment by Calinou** [comment]
> Expected behavior: the selected graph node details appear in the inspector
> Observed behavior: the selected graph node details appear in the inspector and the main screen is switched to the 2D view

I can't reproduce this in 3.3rc8. Also, isn't this issue's title saying the opposite of the observed behavior?

**Comment by nonfinity** [comment]
Confirmed. This has been fixed in 3.3rc8.

Thanks very much!
