### ISSUE TITLE
Can't compile on Windows due to `gdscript_vm.cpp` taking a long time to build

### ISSUE THREAD

**Issue by sboron** [godotengine/godot#47762]
**Godot version:**
4

**OS/device including version:**
Windows

**Issue description:**
Cant compile under windows with mono.

Hangs on gdscript_vm.cpp

Related to that commit 
https://github.com/godotengine/godot/commit/cf4079cb5f51a40c8370a84f5131f944c398f4b8

**Steps to reproduce:**
Compile under windows with mono

**Minimal reproduction project:**
Not necessary

**Comment by Calinou** [comment]
Are you using MSVC or MinGW to compile Godot? If you're using MinGW, try using [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) instead.

**Comment by sboron** [comment]
MSVC

**Comment by sboron** [comment]
Btw its just by building under the target release_debug.

**Comment by sboron** [comment]
![image](https://user-images.githubusercontent.com/76991284/115310058-76b4ce00-a16d-11eb-8a27-0c4c4843bc60.png)

Here the compiler is hanging

**Comment by sboron** [comment]
And thats my build settings for vscode:

`  {
            "label": "mono-build-binary-release",
            "type": "shell",
            "command": "scons",
            "group": "build",
            "args": [
                "platform=windows", // Change to your current platform
                "target=release_debug",
                "tools=yes",
                "module_mono_enabled=yes",
                "-j20"
            ],
            "problemMatcher": "$msCompile",
            "dependsOrder": "sequence",
            "dependsOn": [
                "mono-build-release-temp",
                "mono-build-glue-release"
            ]
        },`
        
        `     {
            "label": "mono-build-release-temp",
            "type": "shell",
            "command": "scons",
            "group": "build",
            "args": [
                "platform=windows", // Change to your current platform
                "tools=yes",
                "target=release_debug",
                "module_mono_enabled=yes",
                "mono_glue=no",
                "-j20"
            ],
            "problemMatcher": "$msCompile"
        },`

`      {
            "label": "mono-build-glue-release",
            "type": "shell",
            "command": "bin\\godot.windows.tools.64.mono.exe",
            "group": "build",
            "args": [
                "--generate-mono-glue",
                "modules/mono/glue"
            ],
            "problemMatcher": "$msCompile"
        },`

**Comment by Calinou** [comment]
How much time did you wait during the linking process? It can take a very long time on the `master` branch (up to an hour).

**Comment by sboron** [comment]
Issue is gone since the laster rebase from the master branch. Ticket can be closed.

**Comment by RandomShaper** [comment]
With a CL that identifies itself as _Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32532 for x64_, from Visual C++ 17.6.0, identified by SCons as MSVC 14.3, it happens to me, with this command line:
`cl /Fomodules\gdscript\gdscript_vm.windows.editor.x86_64.obj /c modules\gdscript\gdscript_vm.cpp /TP /std:c++17 /nologo /MT /Gd /GR /utf-8 /bigobj /Zi /FS /O2 /W4 /wd4100 /wd4127 /wd4201 /wd4244 /wd4245 /wd4267 /wd4305 /wd4514 /wd4714 /wd4820 /EHsc /WX /DTOOLS_ENABLED /DDEBUG_ENABLED /DNDEBUG /DNO_EDITOR_SPLASH /DWINDOWS_SUBSYSTEM_CONSOLE /DWINDOWS_ENABLED /DWASAPI_ENABLED /DWINMIDI_ENABLED /DTYPED_METHOD_BIND /DWIN32 /DMSVC /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /DNOMINMAX /D_WIN64 /DVULKAN_ENABLED /DGLES3_ENABLED /DMINIZIP_ENABLED /DBROTLI_ENABLED /DZSTD_STATIC_LINKING_ONLY /DUSE_VOLK /DVK_USE_PLATFORM_WIN32_KHR /DGLAD_ENABLED /DGLES_OVER_GL /Ithirdparty\libpng /Ithirdparty\glad /Ithirdparty\volk /Ithirdparty\vulkan /Ithirdparty\vulkan\include /Ithirdparty\zstd /Ithirdparty\zlib /Ithirdparty\brotli\include /Iplatform\windows /I.`

It's taken around 10 minutes, but has completed.

**Comment by Calinou** [comment]
@RandomShaper Can you reproduce this after removing the `bin/` folder? See https://github.com/godotengine/godot/issues/77968.

**Comment by RandomShaper** [comment]
I can't try again shortly since I've already changed the build types, etc. However, I can confidently say that the issue is not related to link time. (I have issues with never-ending linking that I fix by Ctrl-C, deleting the .ilk file and linking again, but that's aside.) This problem with compilation happens even if I run the pasted command manually, outside the build system.
