### ISSUE TITLE
RayCast2D hits every tile collision in my Tilemap in the first frame of the game

### ISSUE THREAD

**Issue by gnevesdev** [godotengine/godot#47771]
Godot version: 3.2.3-stable-official-linux
Using GL ES 3 back-end

Did this code
```GDScript
if my_RayCast2D.is_colliding():
		my_RayCast2D.get_collider().queue_free()
```
in the `_process` function, and all my Tilemap tiles disappear when the game starts, not only the ones that were hit.

**Comment by Calinou** [comment]
@gnevesdev Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by gnevesdev** [comment]
No bugs here. The RayCast2D started hiting one of the tiles and destroyed the whole Tilemap node. I was setting the target for the RayCast2D only _after_ it hits the Tilemap.
