### ISSUE TITLE
GDScript: ERROR: Index address = 20 is out of bounds (_stack_size = 10) when calling method on class

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#47777]
**Godot version:**
Godot 4.x
commit c1b4755aa12c03d192e6269a60ce1f53f605a6e4

**OS/device including version:**
Win 10 64x

**Issue description:**
Creating a new `World3D` for a `SubViewport` with GDScript2.0 results in a permanent error log spam when accessing world property on SubViewport.

```
var new_3d_world = World3D.new()
...........
subviewport_node.set_world_3d(new_3d_world)
..........
ERROR: Index address = 20 is out of bounds (_stack_size = 10)
at: GDScriptFunction::_get_variant (modules\gdscript\gdscript_vm.cpp:44)
```

**Steps to reproduce:**
see issue desc

**Minimal reproduction project:**
see issue desc

**Comment by akien-mga** [comment]
The error message is weird and a bug, but the issue here is that you're calling a method on a class, not an instance of a class. That can't work.

**Comment by Blackiris** [comment]
I've tried to recreate a reproduction project, and when calling from the SubViewport class, I get another error:
`Invalid call. Nonexistent function 'set_world_3d' in base 'GDScriptNativeClass'`
which is normal as akien-mga said, it should be called on an instance instead.

And when calling the method on an instance, I get no error as expected.

So, indeed the current code should not work, but I am just wondering how to get the same error message. Maybe you should try to fix your script first and then we will see if it worth checking the issue further.

**Comment by smix8** [comment]
@akien-mga 
@Blackiris 
My bad (example), I used lowercase class name for variable name and copy&pasting my example back and forth it ended up being capitalized and I didn't notice.

I went back and found that the actual reason that triggered the error was not the world resource but a following "if x is y" on the physicsspace RID that was silent without a world resource. I am migrating copy&pasting code junks from a working Godot 3.x project to Godot 4.x at the moment.

```
Godot 3.x
var new_world : Resource = World.new()
viewport_node.set_world(new_world)
print(viewport_node.get_world()) # prints World[1284]
print(viewport_node.get_world().get_space()) # prints [RID]
if (viewport_node.get_world().get_space() is RID):
    # returned a physics space rid, do stuff, works
else:
   return
```

```
Godot 4.x
var new_world : Resource = World3D.new()
subviewport_node.set_world(new_world)
print(subviewport_node.get_world()) # prints [World3D:-9223372008585165723]
print(subviewport_node.get_world().get_space()) # prints RID(4200478015489)
if (subviewport_node.get_world().get_space() is RID):
    #  error msg ERROR: Index address = 20 is out of bounds (_stack_size = 10)
else:
   return
```

**Comment by Blackiris** [comment]
Thank you @smix8, I was able  to reproduce the same error.

From, what I understand, when reading the arguments in GDScriptFunction::call at l.517:

```
int instr_arg_count = ((_code_ptr[ip]) & INSTR_ARGS_MASK) >> INSTR_BITS;
for (int i = 0; i < instr_arg_count; i++) {
	GET_VARIANT_PTR(v, i + 1);
	instruction_args[i] = v;
}
```
the code expects to have variants adresses, but the 3rd argument is not an a Variant adress, but directly the type Variant::RID(20). 20 is then wrongly treated as an adress, thus creating an "out of bounds" bug.

This value, Variant::RID(20), is set in gdscript_byte_codegen.cpp (p_type = 20):

```
void GDScriptByteCodeGenerator::write_type_test_builtin(const Address &p_target, const Address &p_source, Variant::Type p_type) {
	append(GDScriptFunction::OPCODE_IS_BUILTIN, 3);
	append(p_source);
	append(p_target);
	append(p_type);
}
```

However, I don't know how to change `append(p_type);` to make it works yet

**Comment by Blackiris** [comment]
Well, it was easier than I thought. Changing this
`append(GDScriptFunction::OPCODE_IS_BUILTIN, 3);`
to
`append(GDScriptFunction::OPCODE_IS_BUILTIN, 2);`

makes the third argument (type) not treated as a variant address. This this type is already treated at gdscript_vm.cpp l.656):
`Variant::Type var_type = (Variant::Type)_code_ptr[ip + 3];`

I will prepare a PR and a reproduction project

**Comment by Blackiris** [comment]
Here is the project used for testing

[Test_IsBuiltIn.zip](https://github.com/godotengine/godot/files/6292530/Test_IsBuiltIn.zip)

```
extends Node

@onready var subviewport_node = $SubViewport

func _ready():
	var new_world : Resource = World3D.new()
	var a = new_world.get_space()
	var b = "Hello"
	print("a Is RID? " + str(a is RID))
	print("a Is String? " + str(a is String))
	print("a Is Node? " + str(a is Node))
	
	print("b Is RID? " + str(b is RID))
	print("b Is String? " + str(b is String))
	print("b Is Node? " + str(b is Node))

```
