### ISSUE TITLE
Support for Android N beta

### ISSUE THREAD

**Issue by vjrossi** [godotengine/godot#4777]
**Windows 10, Godot 2.0.3**

I'm seeing inconsistent results when deploying to Android N Beta. I realise this wouldn't be 'supported' but I thought I'd report anyway. For example when deploying the Genetic Programming Godot demo I get this:

```
Installing into device (please wait..): Google Nexus 6P
running cmdline: "H:/Android/sdk/platform-tools/adb.exe" "-s" "CVH7N15B30002131" "install" "-r" "C:\
Users\UserName\AppData\Roaming/Godot/tmp/tmpexport.apk"
13510 KB/s (6824426 bytes in 0.493s)
Success
running cmdline: "H:/Android/sdk/platform-tools/adb.exe" "-s" "CVH7N15B30002131" "shell" "am" "start
" "-a" "android.intent.action.MAIN" "-n" "org.godotengine.geneticprogrammingsimulation/org.godotengine.godot.Godot"
Starting: Intent { act=android.intent.action.MAIN cmp=org.godotengine.geneticprogrammingsimulation/org.godotengine.godot.Godot }
Error type 3
Error: Activity class {org.godotengine.geneticprogrammingsimulation/org.godotengine.godot.Godot} does not exist.

```

**Steps to reproduce:**

- Install Android N Beta on a device
- Import the Genetic Programming Godot demo to Godot
- Perform a one-click deploy to the device (I have project defaults set)
- Observe the above error

I've also tried the Drag/Drop GUI demo and that deploys and runs ok.
Another project installed but when I ran it the screen was flashing/strobing badly on the splash screen.
My own project gets a similar error to the above.

Should I assume Android N support will come later and wait, or can something be done to make it work?

**Comment by volzhs** [comment]
the error looks like same as http://www.godotengine.org/qa/4268/android-export-error-type-3-activity-class-does-not-exist

**Comment by reduz** [comment]
maybe the name of the generated application is too long, try setting up a
shorter name in the android project settings

**Comment by bojidar-bg** [comment]
I get a similar error on a 4.4 android device with `master` branch version + 2.0.3 export templates. Maybe something is wrong with them?

**Comment by akien-mga** [comment]
> I get a similar error on a 4.4 android device with master branch version + 2.0.3 export templates. Maybe something is wrong with them?

Well 2.0.3 templates are not compatible with 2.1-dev.

**Comment by bojidar-bg** [comment]
@akien-mga Well, it doesn't work with 2.0.3 linux x64 + 2.0.3 templates, and results in error:
````sh
#...omited apk building and jarsigner output...
Warning: 
This jar contains entries whose certificate chain is not validated.
This jar contains signatures that does not include a timestamp. Without a timestamp, users may not be able to validate this jar after the signer certificate\'s expiration date (2043-10-06) or after any future revocation date.
#...omited a bit here...
Failure [INSTALL_FAILED_INVALID_APK]
returned: 10886, waiting for: 10886 # Unrelated?
Starting: Intent { act=android.intent.action.MAIN cmp=io.github.kobuge-games.minilens/org.godotengine.godot.Godot }
Error type 3
Error: Activity class {io.github.kobuge-games.minilens/org.godotengine.godot.Godot} does not exist.
````

**Comment by volzhs** [comment]
does device already have an app with same package name?

**Comment by bojidar-bg** [comment]
@volzhs No, it doesn't.

**Comment by vjrossi** [comment]
@volzhs no, I have never even tried to install that app on the device before. Still, based on above posts perhaps the Android N thing is a red herring and there is another cause. I agree that error can be raised in other circumstances as well. I'll experiment some more and if I find out more I'll update.

**Comment by vjrossi** [comment]
Ok, I've just created a new project with just a label, with Godot & templates 2.0.3 and it deployed fine with one-click..

**Comment by volzhs** [comment]
I got same problem with Android 7.0 (as knwon as N, Nougat) official release, not beta.
I tried both way.
* one click deploy
* exporting release apk and install with `adb install`

`Failed to install C:\Users\volzh\AppData\Roaming/Godot/tmp/tmpexport.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl242509773.tmp/base.apk: Corrupt XML binary file]`

No problem with Android 4.4 device.

**Comment by volzhs** [comment]
I tested with official 2.1 stable and seems no problem.
I should investigate what is wrong.

**Comment by volzhs** [comment]
Changing version code also makes error.

**Comment by volzhs** [comment]
It seems that problem is in replacing `String` value in `AndroidManifest.xml` while exporting.

https://github.com/godotengine/godot/blob/fc61eb37ce004ecfa0656a46c68d111c68bb5c19/platform/android/export/export.cpp#L641

but fixing it is beyond me.
@RandomShaper would you take a look for this?

**Comment by RandomShaper** [comment]
I'm interested in checking this, but please let me add it to my backlog
until I got enough time. I'm pretty busy developing my game (with Godot, of
course).

So the same APK fails (intermitenty or not) on Android N, but gets
installed OK anytime on former releases. Is that the case?

**Comment by volzhs** [comment]
@RandomShaper correct.

**Comment by volzhs** [comment]
I found so~ weird thing.
It works if compiled tool with `scons platform=windows target=debug`
And problem with `scons platform=windows target=release_debug`
What's wrong with `release_debug`?

**Comment by RandomShaper** [comment]
If you could extract the manifest from both resulting APKs we would be able
to tell if it's the offending piece.

**Comment by volzhs** [comment]
Tool | Generated manifest by tool with debug | Generated manifest by tool with release_debug
-----|-----|------
Size | 33,040 bytes | 33,040 bytes
Compressed size in APK | 6,773 bytes | 6,777 bytes

Found diff with VBinDiff, only one difference.

![image](https://cloud.githubusercontent.com/assets/8281454/18700570/ec63033c-8012-11e6-8e30-f3a76c9fdb6f.png)

**Comment by volzhs** [comment]
I found that is last `savint string` (not sure this is typo or not)
```
...
savint string :com.google.android.gms.auth.api.signin.RevocationBoundService
savint string :com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION
file size: 33040
ADDING: AndroidManifest.xml
ADDING: META-INF/MANIFEST.MF
...
```

**Comment by volzhs** [comment]
So... is this issue fixed now?
I don't have problem after #6574 merged.
