### ISSUE TITLE
Typing in preload("res://con will freeze the editor

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot#47775]
**Godot version:**

v3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

When typing in preload("res://con into the script editor, a warning will appear in the godot console saying this:
```
WARNING: _open: Case mismatch opening requested file 'Con.remap', stored as 'Con' in the filesystem. This file will not open when exported to other case-sensitive platforms.
     At: drivers/windows/file_access_windows.cpp:105
```
But it will also freeze the entire editor making you lose any progress you had.

**Steps to reproduce:**
1. Make a new script
2. Type in preload("res://con
3. You will get a warning but the entire editor will also freeze

**Comment by Flairieve** [comment]
Someone already posted this issue at https://github.com/godotengine/godot/issues/20110

**Comment by Zylann** [comment]
This still happens in Godot 3.4 if you write `preload("./con"`
