### ISSUE TITLE
TileMap YSort inconsistency for tiles with negative y-coordinate

### ISSUE THREAD

**Issue by Calamander** [godotengine/godot#47781]
**Godot version:**

Godot 3.3 RC 8 (same in 3.2.3 and many earlier versions including 3.1)

**OS/device including version:**

Windows 10, GLES 2/3.

**Issue description:**

I have two (or more) TileMaps, both are children of YSort. One TileMap for floor tiles with cell_y_sort property disabled, since floor should always be behind everything. Other TileMap(s) for objects etc. with cell_y_sort enabled. Non-floor tiles with negative y-coordinate placed over the floor get rendered behind floor tiles, while same tiles with positive y-coordinate are sorted on top of it. Cell size and tilemaps hierarchy doesn't matter as long as they are part of the same active YSort tree.
Expected non-floor tilemap(s) with enabled cell_y_sort to be always on top of floor tilemap with disabled cell_y_sort, no matter what coordinate tile has or at the very least all floor tiles to be consistently on top of non-floor tiles, not 50/50.
Floor:
![изображение](https://user-images.githubusercontent.com/8860283/114284854-13cb8480-9a53-11eb-8e41-52747f3cdcb0.png)
Objects:
![изображение](https://user-images.githubusercontent.com/8860283/114284871-3493da00-9a53-11eb-856c-35b0891d0ea9.png)
Together:
![изображение](https://user-images.githubusercontent.com/8860283/114284864-25ad2780-9a53-11eb-9fcc-02d52133c4d4.png)

**Steps to reproduce:**
1. Create YSort (or TileMap with enabled cell_y_sort property)
2. Add 2 TileMaps as children, define tilesets
3. Enable cell_y_sort for one TileMap
4. Place cells on both tilemaps on top of each other, some with positive y and some with negative.
5. Observe different behavior.

**Minimal reproduction project:**

[TileMapYSortNegativeTilesIssue.zip](https://github.com/godotengine/godot/files/6290784/TileMapYSortNegativeTilesIssue.zip)

**Comment by codecustard** [comment]
What happens when you change your hierarchy to the following? 
YSort:
- YSort -> Floors
- YSort -> Objects

**Comment by Calamander** [comment]
@codecustard you mean if i do it like this?
![изображение](https://user-images.githubusercontent.com/8860283/114298371-596d6900-9ab6-11eb-991c-1fbf4ba635b7.png)
Nothing really changes, as you can see... Since they are in the same YSort hierarchy.

**Comment by kleonc** [comment]
I'd say that's expected/correct behavior. Since your `floor` tilemap has `cell_y_sort` disabled the parent `YSort` treats that `floor` tilemap as a single element (and `floor`'s position is `Vector2(0, 0)`, thus the result).


> One TileMap for floor tiles with cell_y_sort property disabled, since floor should always be behind everything.

If it should be behind everything then why would you put it as a child of `YSort`? If you move `floor` before the `YSort` in the scene tree it works exactly as you want (`floor` is being rendered before `YSort`):
![BN1BaTHeGv](https://user-images.githubusercontent.com/9283098/114302318-d4d81600-9ac8-11eb-8ef6-8b9eed6ddbfe.png)

**Comment by Calamander** [comment]
@kleonc 
> I'd say that's expected/correct behavior. Since your floor tilemap has cell_y_sort disabled the parent YSort treats that floor tilemap as a single element (and floor's position is Vector2(0, 0), thus the result).

Ah, i get it. I was under wrong impression that toggling cell_y_sort makes tilemap and all of its cells either participate in all ysort operations or don't, but in reality it only affects sorting of cells.

> If it should be behind everything then why would you put it as a child of YSort?

The reason is because I want everything in one place. I'm making an isometric game. It consists of few self-contained sections (separate scenes) each having floor, walls, objects, characters, etc - except for floor everything is ysorted. Characters can move between different sections and sections should be sorted against each other too (their walls, objects, etc). So all sections have to be part of the same YSort hierarchy.

I fixed my problem by changing floor tilemap z-index to negative.

Thanks and sorry for cluttering tracker with my turns-out-not-a-bug issue. I guess my problem is rare enough use-case and doesn't require further discussion.
