### ISSUE TITLE
Shader material and modulation with batching enabled can result in wrong color

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#47783]
Godot 3.3-rc8
Arch Linux
Intel UHD 10th gen / Nvidia GTX1080
GLES3

Color of canvas item changes when a shader material and modulation are applied. Disabling batching results in correct color.

[shader-modulation-batching-bug-reproduction.zip](https://github.com/godotengine/godot/files/6290827/shader-modulation-batching-bug-reproduction.zip)

Color in attached file should be constant, but isn't.

**Comment by Calinou** [comment]
cc @lawnjelly

**Comment by akien-mga** [comment]
Fixed by #47788.
