### ISSUE TITLE
Keyboard is less responsible on a project

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#47793]
**Godot version:**
Godot 3.3 rc 8

**OS/device including version:**
OS Win 10 64  AMD GPU

**Issue description:**
When pressing the keyboard is less responsible, and the animation looks like it stutters.
I tested the TP-Minimal-Controller with Godot 3.3 rc 8 and it gives keyboard issue.
In Godot 3.2.3 stable works fine. I found that from Godot_v3.2.4-beta2, the issue started to show.

**Steps to reproduce:**
Just press the keys to move the char.

**Minimal reproduction project:**
link: https://github.com/Naurk/TP-Minimal-Controller

**Comment by KoBeWi** [comment]
I don't see any difference between these versions.

**Comment by Akira1San** [comment]
> I don't see any difference between these versions.

Thx for the response. Its very interesting, but when i press the W key there is a hold before the char moves.

**Comment by Akira1San** [comment]
Found the issue. It was the plugged joystick - closing.
