### ISSUE TITLE
Duplicated node does not duplicate editable children

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#47790]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Linux

**Issue description:**
Observe the image below:

1. BasicDebris is an inherited node, inside Hitbox/Hurtbox is an empty area2d with no collision shape set
2. BasicDebris has Hitbox/Hurtbox set as 'editable children' and their collision shape created
3. BasicDebris is duplicated to BasicDebris3

On duplicating the Hitbox/Hurtbox are empty (the editable status is gone) and the collision shape has not copied down. You would expect duplicate to do this, otherwise creating multiple items is not possible... Please let me know if this is as designed, otherwise I can create a sample if you want, but the basic gist is editable children are not duplicated.

![image](https://user-images.githubusercontent.com/12863685/114300458-51162d80-9ab8-11eb-82f5-1e6e7d5d7ca8.png)

**Comment by hilfazer** [comment]
It's not intended. There's a PR that deals with that but it hasn't been merged into 3.x branch yet:
https://github.com/godotengine/godot/pull/46292

It's been merged into 4.0 though, so if you can compile it you can try recreating your problem on the master branch.

**Comment by akien-mga** [comment]
> Godot version:
3.3 stable

I'd like to know where you downloaded 3.3 stable from when I haven't released it yet...

**Comment by chucklepie** [comment]
> > Godot version:
> > 3.3 stable
> 
> I'd like to know where you downloaded 3.3 stable from when I haven't released it yet...

Sorry, 3.2.3.

**Comment by KoBeWi** [comment]
This can be fixed by adding `node->data.editable_instance = data.editable_instance;` here:
https://github.com/godotengine/godot/blob/595a74ca79578ca882e3f9f71fbcc6bd3c5c1818/scene/main/node.cpp#L2005-L2007

It was done by #45937 , so the fix is only relevant for 3.x

**Comment by akien-mga** [comment]
Fixed by #46292.
