### ISSUE TITLE
Vulkan: GIProbe very slow on AMD RX480 and Linux

### ISSUE THREAD

**Issue by pihdastudios** [godotengine/godot#47794]
**Godot version:**

43f89e7c2

**OS/device including version:**

Linux Mint 20.1
Kernel `5.8.0-48-generic #54~20.04.1-Ubuntu`

AMDVLK 2021.Q2.1 and radv 20.2.6

AMD RX 480 8Gb
AMD Ryzen 7 3700X

Build Command
`scons p=linuxbsd target=debug module_mono_enabled=no -j16 CXX=g++-10 CC=gcc-10`

**Issue description:**

GIProbes on any mesh with or without light would create a performance issue.

Also selecting the mesh after setting it to disabled baking and baking GIProbe also creates a performance issue

**Steps to reproduce:**

1. Create a scene
2. Add mesh (Cube)
3. Set to baked Dynamic
4. Add GIProbe
5. Bake

And

1. Create a scene
2. Add mesh (Cube)
3. Add GIProbe
4. Bake (Everything is still fine by now)
5. Select Mesh

**Minimal reproduction project:**
[giprobe-test.zip](https://github.com/godotengine/godot/files/6291731/giprobe-test.zip)

**Comment by Calinou** [comment]
@pihdastudios Can you define "very slow"?

**Comment by pihdastudios** [comment]
> @pihdastudios Can you define "very slow"? Is the slowless persistent or does it occur only when moving a node?

Near freezing, it slows down my entire desktop.
Godot still can receive inputs (clicking buttons, moving nodes) but you'd have to wait around 2 seconds.

It would dissapear if you cleared the GIProbe data

**Comment by pihdastudios** [comment]
This also happens on Windows 10 with AMD Adrenalin 21.3.2. So its probably a hardware thing.

**Comment by novemberist** [comment]
I can confirm this. I'm also on Linux and with an AMD GPU (RX 580). This issue has been present for me for at least a year now. I think this started around the time the DisplayServer changes/multiple windows support was introduced.

**Comment by Calinou** [comment]
GIProbe in `master` is currently broken in my experience (it often makes everything black), *unless* you combine it with SDFGI at the same time.

**Comment by novemberist** [comment]
So, as of commit  https://github.com/godotengine/godot/pull/49547 by @reduz the blackness is gone and VoxelGI seems to somewhat work again. However, this is only the case if you set "Global Illumination" for your MeshInstance to "baked". If you select "dynamic" here, once you bake the GIData, Godot slows down permanently (almost freezes). If I understand the current GI implementations correctly, the gi_mode "baked" should only be relevant for LightmapGI (and thus have no effect for VoxelGI) whereas "dynamic" is the correct one to enable if you want the Mesh to contribute to VoxelGI? I think something is still broken here (or it is really a driver issue)

**Comment by Calinou** [comment]
> If I understand the current GI implementations correctly, the gi_mode "baked" should only be relevant for LightmapGI (and thus have no effect for VoxelGI) 

AFAIK, Baked and Dynamic are treated differently in VoxelGI, and both are meant to work.

**Comment by William-Godwin** [comment]
> However, this is only the case if you set "Global Illumination" for your MeshInstance to "baked". If you select "dynamic" here, once you bake the GIData, Godot slows down permanently (almost freezes).

It's still happening for me on Win and linux with GTX 1080 on Hugo's builds. =(

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/55359, which describes the issue at hand in more detail. The unexpectedly low performance only occurs with meshes in Dynamic bake mode, not the Baked bake mode.
