### ISSUE TITLE
`Tabs tab_close` signal is emitted when close button is hidden

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#47795]
**Godot version:**

3.2.3

**OS/device including version:**

Linux

**Issue description:**

https://user-images.githubusercontent.com/16458555/114306621-c522f680-9af5-11eb-946f-c34848263032.mp4

When pressing the tab on "close button" area, `tab_close` signal is emitted even  when `Tabs close display policy` is set to `active only`.

**Steps to reproduce:**
see video above

**Minimal reproduction project:**

**Comment by Calinou** [comment]
I can reproduce this on 3.2.3. It's the reason I opened https://github.com/RodZill4/material-maker/pull/325.

**Comment by kitbdev** [comment]
fixed by #55454
