### ISSUE TITLE
AnimationPlayer: Adding consecutive keys "eats" the first key when the track does not already exist

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#47808]
**Godot version:** Godot 3.2.3, Godot 3.3 rc8

**OS/device including version:** Win64

**Issue description:**

Clicking on the key symbol next to a property is very convenient as it keeps adding keys on the timeline according to the snap setting.

![adding_keys_bug](https://user-images.githubusercontent.com/47016402/114323445-85740300-9b25-11eb-9937-1cef7b993d1d.gif)

https://user-images.githubusercontent.com/47016402/114317396-2d7ad380-9b08-11eb-8613-2335dce7118d.mp4

However if this is done on a property without an existing track, the first key is written twice, resulting in more manual labor, since either this auto key functionality or the auto track adding functionality can't be used properly.

https://user-images.githubusercontent.com/47016402/114317464-7fbbf480-9b08-11eb-9f70-b07f2baa308a.mp4

**Steps to reproduce:**
Drag and drop this texture into your project:
![numbers_spritesheet](https://user-images.githubusercontent.com/47016402/114317735-ce1dc300-9b09-11eb-936c-6092531338e5.png)
Add a Sprite node with above Texture, set the `hframe `to 4, `vframe `to 2. Make sure `frame `is set to 0
Add an AnimationPlayer and add Animation
Click on the Sprite node to bring up the Sprite properties and the key symbol next to it, 
Click the "frame" key symbol a bunch of times (first time Godot will ask if you want to create a track, click "create")

_**Witness the brutal devouring of the first keyframe by the second keyframe.**_

To see how it should work, select all keyframes and delete them, then click the Sprite again reset the `frame` property to 0 and hit the key symbol of the `frame` property a bunch of times.

**Comment by timothyqiu** [comment]
This has been a long existing issue: #33681

The playhead does not advance if the confirmation dialog appears.

**Comment by Calinou** [comment]
Duplicte of https://github.com/godotengine/godot/issues/33681.
