### ISSUE TITLE
Inspector for exported string variables is broken

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#47809]
**Godot version:**

3.3 rc8

**Issue description:**

~~I have an exported string variable. When I edit it, I can't undo the first batch of entered characters. It's like the modified undo history gets merged with original string.~~ EDIT: This is LineEdit issue: #47562 

Another thing is that my cursor will randomly move to the beginning. Seems like it only happens reliably when you reload the scene.

This wasn't happening in 3.2.3 as far as I remember, it appeared recently.

**Steps to reproduce:**
1. `export var test = "Test"
2. Save and reload the scene
3. Edit the variable
4. 
![LineEdit bug](https://user-images.githubusercontent.com/2223172/114320829-1d6af000-9b18-11eb-8b57-84e2a5ee6802.gif)

**Comment by akien-mga** [comment]
> Another thing is that my cursor will randomly move to the beginning. Seems like it only happens reliably when you reload the scene.

How do you reload the scene exactly?

For me the cursor jumps to the beginning when I save the scene (Ctrl+S), both in 3.2.3 and 3.3 RC 8.

The only difference I noticed is that in 3.3 RC 8 I can somehow end in a state where saving the scene (Ctrl+S) will lose focus in the LineEdit.

**Comment by KoBeWi** [comment]
> How do you reload the scene exactly?

Using the Reload Saved Scene option.

**Comment by KoBeWi** [comment]
Seems like this also happens after switching scene tabs (makes sense, otherwise I wouldn't really notice it). It affects all LineEdits, so numeric variables also have this problem.

**Comment by Calinou** [comment]
@KoBeWi Can you (or anyone else) still reproduce this bug in 3.4rc3?

**Comment by KoBeWi** [comment]
Doesn't seem to be happening anymore.
