### ISSUE TITLE
VisualShaderNodeCustom set_input_port_default_value() issue (bug?)

### ISSUE THREAD

**Issue by Valinakova** [godotengine/godot#47805]
Godot version: 3.2.3

GPU: RTX 550 series.
Using GLESE 3

Hi! When using VisualShaderNodeCustom, there appears to be an issue with values being entered into the Visual Shaders being reset to the default values when I close the engine and reopen the project. This happens even if I hit save before closing the project.  Duplicating the material by right click-duplicate also leads to the same result.

Here is my folder set up below:
![image](https://user-images.githubusercontent.com/81381626/114315409-bf0c2600-9ab3-11eb-980a-26354aac62b0.png)

My custom values I set:
![image](https://user-images.githubusercontent.com/81381626/114315553-53768880-9ab4-11eb-850f-23856a23f32e.png)

Below is what would happen if you were to were to save, then close the program, and reopen the project. The custom values I set disappear and go back to their default settings. 
![image](https://user-images.githubusercontent.com/81381626/114315565-6b4e0c80-9ab4-11eb-9c95-2d1089fb6152.png)

I uploaded a test into 3.3 version via online: https://editor.godotengine.org/releases/3.3.rc8/godot.tools.html
I right clicked, and duplicated and renamed the modified texture. The settings on the duplicate go back to their default values just like in 3.2.3

Minimal Reproduction Project:
Below you will find a test game with the addons folder in it with all the custom nodes. In The test material inside it has two nodes, a regular noise node which is part of the Godot core, and one custom node called DistortUV. Change the values, save, close, and reopen and you will see the values reset to their defaults.
[Bug_testing.zip](https://github.com/godotengine/godot/files/6292517/Bug_testing.zip)

**Comment by arkology** [comment]
cc @Chaosus
