### ISSUE TITLE
Running tool/EditorScript code to send UDP packets freezes the whole system irrevokably

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot#47806]
**Godot version:**
3.3.rc8

**OS/device including version:**
linux64 GLES3

**Issue description:**
I was experimenting with sending UDP packets by executing an immediate function to make it easier to develop and hit this unfortunate situation.  Window close doesn't even work.

**Steps to reproduce:**
Open the project and the udp_immediate.gd file, and hit Cntrl-Shift-X to run the code immediate.  Everything stops and you have to kill the process.

**Minimal reproduction project:**
[udpsendingtest.zip](https://github.com/godotengine/godot/files/6292523/udpsendingtest.zip)

**Comment by Calinou** [comment]
Can you reproduce this in 3.2.3?

**Comment by qarmin** [comment]
You execute 1000 times OS.delay_msec(2000), so for me this is expected behavior

**Comment by goatchurchprime** [comment]
Dang, you might be right.  The whole UDP business is a red herring.  

I've just tested `OS. delay_msec(20000)` in a different `tool; EditorScript` file (where I normally check out small GDscript snippets), and the whole interface hangs.  

I'd normally use `yield(get_tree().create_timer(1.0), "timeout")` for this, but when you are running an EditorScript file there is no tree, so I looked for the next best thing.  

Maybe all I really needed was a health warning on the function.
 https://docs.godotengine.org/en/stable/classes/class_os.html?highlight=delay_msec#class-os-method-delay-msec

**Comment by LikeLakers2** [comment]
> but when you are running an EditorScript file there is no tree

Actually there is, it's just not *directly* accessible. If you use `EditorScript.get_editor_interface()`, you'll get back a `EditorInterface` node, which you can then call `get_tree()` on. So in your case, you'd be using `yield(get_editor_interface().get_tree().create_timer(1.0), "timeout")`.
