### ISSUE TITLE
ShaderGraph Editor moving bug

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#4782]
**Operating system or device - Godot version:**
win10-2.0.3

**Issue description** (what happened, and what was expected):
![default](https://cloud.githubusercontent.com/assets/10054853/15475934/0cec4a1a-213f-11e6-9142-58ec7d069533.png)
Zoom Out the graph using '-',then move the block, and the block don't follow the mouse.

**Steps to reproduce:**
Zoom Out the graph using '-',then move the block, and the block don't follow the mouse.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Was fixed by c907a32.
