### ISSUE TITLE
Can't use signal declared in abstract generic class

### ISSUE THREAD

**Issue by PhilG** [godotengine/godot#47830]
**Godot version:** 3.2.3.stable.mono

**OS/device including version:** Windows 19042.870, GTX1060 (Driver 461.09)

**Issue description:**

Working on a system I noticed I could give myself a nicer API by making the abstract base class generic over what entity or node it will be dealing with. There was one signal declared in the abstract base class which I was able to connect from concrete implementations of the base class before making the base class generic. With the generic type argument in use neither connecting nor emitting the signal works.

```
E 0:00:00.686   connect: In Object of type 'Node': Attempt to connect nonexistent signal 'MySignal' to method 'Node2D.MySignalCallback'.
  <C++ Error>   Condition "!signal_is_valid" is true. Returned: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1503 @ connect()
  <Stack Trace> :0 @ Int32 Godot.NativeCalls.godot_icall_5_593(IntPtr , IntPtr , System.String , IntPtr , System.String , IntPtr , UInt32 )()
                Object.cs:512 @ Godot.Error Godot.Object.Connect(System.String , Godot.Object , System.String , Godot.Collections.Array , UInt32 )()
                Manager.cs:13 @ void Manager._Ready()()

```

```
E 0:00:00.689   emit_signal: Can't emit non-existing signal "MySignal".
  <C++ Error>   Condition "!signal_is_valid && !script.is_null() && !Ref<Script>(script)->has_script_signal(p_name)" is true. Returned: ERR_UNAVAILABLE
  <C++ Source>  core/object.cpp:1195 @ emit_signal()
  <Stack Trace> :0 @ void Godot.NativeCalls.godot_icall_2_591(IntPtr , IntPtr , System.String , System.Object[] )()
                Object.cs:359 @ void Godot.Object.EmitSignal(System.String , System.Object[] )()
                ConcreteThing.cs:8 @ void ConcreteThing.MyMethod()()
                Manager.cs:14 @ void Manager._Ready()()
```

**Steps to reproduce:**
To verify this change in behaviour in the minimal reproduction project simply remove/add the generic type argument to the `GenericThing` class and `ConcreteThing` inheriting from it, then run the project.

**Minimal reproduction project:**

[Generics Example.zip](https://github.com/godotengine/godot/files/6298014/Generics.Example.zip)

**Comment by PhilG** [comment]
@neikeq Sorry to ping, but if you happen to have the time to check whether this is an expected limitation I'd be much obliged.

**Comment by serramatutu** [comment]
Same is happening to me. I solved it temporarily by using native C# events instead of godot signals.

**Comment by serramatutu** [comment]
![image](https://user-images.githubusercontent.com/18057473/127749231-cde9bea0-8f4c-45c3-9fc3-84319a9e20d1.png)
![image](https://user-images.githubusercontent.com/18057473/127749244-654262ed-a6c3-42cc-8b28-9c146b143622.png)

This seems to work quite well, even though I'd much prefer to use Godot's native signals to adhere to the conventions

**Comment by serramatutu** [comment]
In my case, `ResourceLoader<T>` is the abstract class and `TileLoader` inherits from `ResourceLoader<Tile>`.

**Comment by PhilG** [comment]
That is a good idea I didn't have! I just took half an hour to try it out in my case and after reading up on a couple things about C# events sans Godot it works just like expected. The only thing I had figure out was to write a method which raises the event in the base class, since all subclasses need to be able to do that and C# doesn't allow this directly for events declared in the base class.

**Comment by cgbeutler** [comment]
This happens with any generic class. Abstract has nothing to do with it.
Signal `MySignal` below will show up as missing
```csharp
public class TypedSignaler<T> : Object
{
  [Signal] public delegate void MySignal();
}
```
If you were to move the signal out into a type-less base class, then it works!
```csharp
public class TypedSignaler : Object
{
  [Signal] public delegate void MySignal();
}
public class TypedSignaler<T> : TypedSignaler { }
```
Sadly, that is not an option in many cases, so a fix is certainly needed.

This may even be a bigger issue. I could mean the `CSharpScript` or something is not fetched right for generic types. Keep an eye out for other bugs that could signal that that is the case.

**Comment by raulsntos** [comment]
It seems the `GDMonoClass::get_all_delegates` method does not retrieve delegates defined in a generic type. The problem seems to be the method `mono_class_get_nested_types` does not return anything in this case:

https://github.com/godotengine/godot/blob/4b4e92b3d4dfa850ed7d14202c3ec5e6b9646bc0/modules/mono/mono_gd/gd_mono_class.cpp#L446

The documentation for this method says:

> This routine is an iterator routine for retrieving the nested types of a class. **This works only if klass is non-generic, or a generic type definition**.

So I think the way to fix this would be to check if the type is generic and in that case use the generic type definition instead of the generic type as the `klass` parameter. But I don't know how to get the generic type definition from the `MonoClass *`.

**Comment by neikeq** [comment]
For `GetGenericTypeDefinition` we have to rely on C# helper methods. See how we do it here:

https://github.com/godotengine/godot/blob/3.x/modules/mono/glue/GodotSharp/GodotSharp/Core/MarshalUtils.cs

It seems `mono_class_get_properties` has the same comment about not working with generic types. We should check whether the listing of properties, methods and fields is also failing with generic types or not.

**Comment by raulsntos** [comment]
I'm only seeing that comment in the `mono_class_get_nested_types` method in the documentation I linked.
I tested again with a79e4d0ae5707f954f6422672cc9279f8165d91b (3.x) to check listing and it works everywhere (_properties_, _fields_ and _methods_) except for _delegates_.

**Comment by cgbeutler** [comment]
Delegates are, I'm pretty sure, closer to a static definition. That makes them more like enums and member classes than fields.

**Comment by neikeq** [comment]
I must have misread the documentation for `mono_class_get_properties`. It's next to `mono_class_get_nested_types` so I probably read the latter's description by mistake.
