### ISSUE TITLE
Batching - incorrect modulate with joined sprites

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#47834]
**Godot version:**

Godot 3.3 RC 8

**OS/device including version:**

All

**Issue description:**

This is a stub issue, I have already fixed the bug, see below.

Create a project with 2 similar sprites that will be joined together by batching. Set the modulate of the 1st to white, and the second to red.

Apply this shader to both:
```
shader_type canvas_item;

void fragment() {
	COLOR = vec4(0.7, 0.7, 0.7, 1) * MODULATE;
}
```
Incorrect (batching)
![Screenshot from 2021-04-12 17-52-57](https://user-images.githubusercontent.com/21999379/114431941-febc3600-9bb7-11eb-9e7f-7cf23c4b803a.png)
Correct (no batching)
![Screenshot from 2021-04-12 17-53-13](https://user-images.githubusercontent.com/21999379/114431943-01b72680-9bb8-11eb-982a-0946b0d520c3.png)

**Steps to reproduce:**
Run minimum reproduction project. It has flash batching switched on, should show the regression.

**Minimal reproduction project:**

[UnitTests.zip](https://github.com/godotengine/godot/files/6298431/UnitTests.zip)

**Bug**
The bug occurs because the first sprite has a white modulate, it bypasses the decision to use a FVF with modulate. The second joined sprite should force MODULATE_FVF, but this does not work because only the first joined item is considered.

**Comment by akien-mga** [comment]
Fixed by #47788.
