### ISSUE TITLE
Unable to change mouse cursor over RichTextLabel

### ISSUE THREAD

**Issue by 3p0ch-NG** [godotengine/godot#47847]
**Godot version: 3.2.3.stable.mono.official**

**OS/device including version: Windows 10**

**Issue description:**
With RichTextLabels, changing "Mouse": "Default cursor shape" from the editor or .mouse_default_cursor_shape from code has no effect on the mouse cursor. This is true even though I made the RichTextLabel clickable and have code executing functions when the label is clicked, so I know it's not an issue with the underlying rect size or anything.

There is a maybe related issue #42249, but it looks like they only had problems with the mouse cursor if they have the RichTextLabel's meta_underlined property set to false, whereas I'm not able to get the cursor to change even if meta_underlined is set to true.

Unless this is a sign that there's a more fundamental underlying issue, this is probably a low priority to fix because the following workaround worked for me (in case anyone is running into this issue and finds this in a web search):
1) Add a MarginContainer as a child to the RichTextLabel
2) Set the MarginContainer Anchors to be 0 for Left and Top, and 1 for Right and Bottom
3) Set the MarginContainer Margins to all be 0
4) Set the MarginContainer Mouse settings to Filter: Pass and Default Cursor Shape: Pointing Hand

**Steps to reproduce:**
Add a RichTextLabel and attempt to change the mouse default cursor shape.

**Minimal reproduction project:**
[rich_text_label_mouse_cursor_minimal_project.zip](https://github.com/godotengine/godot/files/6300923/rich_text_label_mouse_cursor_minimal_project.zip)

**Comment by timothyqiu** [comment]
Seems fixed by #52067.
