### ISSUE TITLE
Godot sometimes switches to the 2D editor on play

### ISSUE THREAD

**Issue by johnnygossdev** [godotengine/godot#47861]
**Godot version:**
3.3.rc8

**OS/device including version:**
Windows 10

**Issue description:**
Sometimes when certain nodes in the 2D editor are selected, the script editor swaps to the 2D editor when the project runs.

In some scenes over multiple projects:

* When the root Node2D is selected, the script editor switches to the 2D editor on play
* When a CanvasLayer is selected, the script editor **does not** switch to the 2D editor on play
* Trying to replicate this scene with a simpler one fails to reproduce the bug

This video shows me talking through the issue and I also discovered switching to the 2D editor stopped in one project possibly because another project was already running.

https://user-images.githubusercontent.com/3285214/114578885-3d63f600-9c75-11eb-8227-307aaa5593e4.mp4

**Steps to reproduce:**
Unsure how to.

**Minimal reproduction project:**
I couldn't replicate it with a clean project with a smaller scene.

**Comment by KoBeWi** [comment]
Sounds like #33409
