### ISSUE TITLE
directionalLight

### ISSUE THREAD

**Issue by Mbeah123** [godotengine/godot#47860]
**Godot version:**
 version 3.3

**OS/device including version:**

**Issue description:**

the DirectionalLight is not working in the version 3.3. It can't throw light on the screen 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
Please fill out the entire template. As it is, you haven't provided enough information for someone to help you.

**Comment by clayjohn** [comment]
No answer so closing. There is nothing actionable for us here.
