### ISSUE TITLE
Upon opening Godot, it runs the last project instead of opening project list or even the editor.

### ISSUE THREAD

**Issue by burzum85** [godotengine/godot#4787]
**OS:**
Windows 10 Home edition

Can reproduce on these Godot versions:
2.0.2 and 2.0.3 win64
2.0.3 win32

**Issue:**
Upon opening Godot, it runs the last project instead of going to project list, or even going to editor.
Only way I can go back to project list or editor is editing engine.cfg and removing main_scene line.
I have to re-open the scene and assign it on project settings as main scene again.
If I close Godot and re-open it, same thing happens again.

**Steps to reproduce:**
Start new project from scratch.
Set main_scene in project settings.
Run project.
Save it.
Quit.
Open Godot......issue.

**Project upload:**
I'm sorry but I cannot upload the project, it is VERY SMALL though, nothing weird, just a few nodes with AnimatedSprite and AnimationPlayer.

**Comment by Ace-Dragon** [comment]
I've been using Godot 2.0.3 on Windows 10 and I don't have the issue you're describing.

Could it be you accidentally changed some obscure setting or something?

**Comment by bojidar-bg** [comment]
Probably you saved the project in the same folder as the godot executable?

**Comment by burzum85** [comment]
@bojidar-bg that was it, thank you so much bojidar!
