### ISSUE TITLE
[MacOS] GD v4.0 Crash on startup 

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot#47877]
**Godot version:**
v4.0

**OS/device including version:**
MacOs Big Sur

**Issue description:**
Over the last few weeks when trying nightly builds from https://hugo.pro/projects/godot-builds/, they continually crash on start up. I'm still able to test things using a build from a month ago but all builds in the last few weeks for MacOS won't start.

**Steps to reproduce:**
Here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/27105009/114649257-7f4b7580-9d23-11eb-84cb-e812d736118a.png)

I've then gone and compiled from source myself and received this error:
![image](https://user-images.githubusercontent.com/27105009/114655273-3c8f9a80-9d2f-11eb-8eaf-a658ee50f4c4.png)

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
It's crashing due to old version in the ICD .json. Fix - https://github.com/godotengine/godot/pull/47881, you can change version in the nighty build bundle without rebuilding it.
