### ISSUE TITLE
GDScript editor: Spurious warnings "declared but never used in the script"

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#47888]
**Godot version:**
4.0.dev 6b39980e

**OS/device including version:**
Windows 10

**Issue description:**

I'm seeing warnings of the form
```
[Ignore] Line 52 (UNUSED_PRIVATE_CLASS_VARIABLE): The class variable '_cache_uniq_key' is declared but never used in the script.
```
for private variables and properties I declare which do get used within the same class.

**Steps to reproduce:**
1. Edit the attached project (do not run it)
2. In the script editor, open crashy.gd
3. Check the Warnings panel at the bottom. You will see the above unused variable warnings:
* `_cache_uniq_key` is used by `uniq_key` property getter which is used by `_to_string` which is used by str() on line 101.
* `_type_dictionary` is used directly by the instantiate function

**Minimal reproduction project:**
[ExtendsCrash.zip](https://github.com/godotengine/godot/files/6310726/ExtendsCrash.zip)

**Comment by smix8** [comment]
Not only class variables, compared to Godot 3.x the parser seem to complain about any variable that does not use the same indentation level, e.g. in an if or match block. If you create a variable inside a function and immediatly below create an if block and assign values in all available branches the Godot 4.x parser still complains that the variable is never used. I just moved the main code from a Godot 3.x project to Godot 4.x and I have 8 pages of false "is declared but never used" warnings to dig through.

**Comment by lyuma** [comment]
confirmed still on 85186bc - note you have to edit `crashy.gd` and replace both instances of Reference with RefCounted

**Comment by lyuma** [comment]
Seems similar to issue #42318

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot/pull/52329 in 4.0 master
