### ISSUE TITLE
Godot 4.0 Unable to initalize Video Driver

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#47906]
**Godot version:**
Not sure it won't launch for me to check. but its from here https://hugo.pro/projects/godot-builds/

**OS/device including version:**
OS: Kubuntu 20.10
GPU: Geforce GTX 650

**Issue description:**

![image](https://user-images.githubusercontent.com/2453707/114811223-8e9de380-9d62-11eb-96b0-7f0704706d47.png)

**Steps to reproduce:**
- Run the editor

**Minimal reproduction project:**

NA

**Comment by clayjohn** [comment]
What version of Vulkan do your driver's advertise support for?

You likely need to install different drivers from what you have. But I'll let someone with more kubuntu knowledge explain how you do that.

**Comment by Shadowblitz16** [comment]
Idk I can try to check drivers aren't that easy to find out and install

**Comment by qarmin** [comment]
Post here output of command `glxinfo | grep OpenGL`
From Nvidia site I see that Vulkan 1.2 is supported on GTX 650

I think that you may use Nouveau instead propertiary nvidia drivers.

**Comment by Shadowblitz16** [comment]
```
OpenGL vendor string: nouveau
OpenGL renderer string: NVE7
OpenGL core profile version string: 4.3 (Core Profile) Mesa 20.2.6
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.3 (Compatibility Profile) Mesa 20.2.6
OpenGL shading language version string: 4.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by qarmin** [comment]
You are using builtin(free and open source) drivers which doesn't work always well with Nvidia cards(this is Nvidia fault).
Probably you can install proprietary drivers with this command(I didn't tested this command since ~1,5 year, so it may not work correctly)
```
sudo apt install ubuntu-drivers-common
sudo ubuntu-drivers autoinstall
```

**Comment by Calinou** [comment]
Nouveau doesn't have *any* Vulkan support yet, so this is expected. Closing.

**Comment by Shadowblitz16** [comment]
@qarmin I tries those commands and it still won't run

**Comment by akien-mga** [comment]
![Screenshot_20210416_085619](https://user-images.githubusercontent.com/4701338/114984056-9d36e880-9e91-11eb-90de-8d09110e6b18.png)

**Comment by Shadowblitz16** [comment]
wow sorry I have my dad's sense of vision I swear
