### ISSUE TITLE
Mesh.PRIMITIVE_LINES not being drawn in GD4.0

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot#47901]
**Godot version:**
v4.0

**OS/device including version:**
MacOS Big Sur, Macbook Pro 2019

**Issue description:**
ImmediateGeometry lines aren't being drawn. Tested same code in v3.3rc7 and worked fine.
Tried PRIMATIVE_LINES & PRIMATIVE_LINE_STRIP, neither work

**Steps to reproduce:**
Copy the code from the reproduction project into v4.0 and 3.3 to test

**Minimal reproduction project:**
[15_LineTest_GDv4.0.zip](https://github.com/godotengine/godot/files/6314493/15_LineTest_GDv4.0.zip)

**Comment by clayjohn** [comment]
While I have labelled this as a bug, it technically isn't. ImmediateGeometry just hasn't been implemented in the Vulkan backend yet.

**Comment by MrJoshBowman** [comment]
Ah, that would be it then 😁

**Comment by akien-mga** [comment]
Fixed by #50014.
