### ISSUE TITLE
Vulkan: transparency sorting is broken

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot#47907]
**Godot version:**
v4.0

**OS/device including version:**
MacOS, Macbook Pro 2019

**Issue description:**
Alpha transparency doesn't properly draw at all and will cause textures behind to disappear, as well as sit over the top of things like the camera and the translate/rotate/scale widget
![image](https://user-images.githubusercontent.com/27105009/114811783-17b02b80-9df2-11eb-8630-32104bc09b06.png)

**Steps to reproduce:**
Made two planes with a texture and used the logo to test
- set the transparency of the StandardMaterial3D to Alpha (or anything other than 'disabled')
- set depth draw mode to 'always'
- Watch the camera and the transform widget disappear behind the meshes
- Also happens when running the build

**Minimal reproduction project:**

[16_Z_Sorting_GDv4.0.zip](https://github.com/godotengine/godot/files/6315071/16_Z_Sorting_GDv4.0.zip)

**Comment by Calinou** [comment]
This might be fixed by https://github.com/godotengine/godot/pull/43507. Note that transparency sorting was never that good in Godot in the first place…

**Comment by MrJoshBowman** [comment]
I can only hope that it can somehow be improved as it seems like quite a fundamental necessity for a game engine to have it working correctly. I do understand that there are a lot of other moving parts that need to be considered though, but for my purposes, the entire app I'm building relies on alpha sorting.

**Comment by Calinou** [comment]
@MrJoshBowman You could try rebasing QbieShay's work from that pull request against the latest `master` branch and see if it works correctly.

**Comment by MrJoshBowman** [comment]
Took your advice and tried to implement the code changes into the latest master, but it looks like the `renderer_scene_cull.cpp` file has changed so much that the changes made in the above fix aren't directly compatible as far as I can see. I couldn't search or find the code either side of the changed line.
