### ISSUE TITLE
File->New Scene opens a empty scene instead of creating a new scene

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#47905]
**Godot version:**
3.2.3

**OS/device including version:**
Kubuntu 20.10

**Issue description:**
File->New Scene opens a empty scene instead of creating a new scene
this maybe be confusing for new users because other options like `new folder`, `new script` and `new resource` create items in the file menu, where `new scene` just opens a new scene tab

**Steps to reproduce:**
- Create project
- Add new scene from file menu
- See it opens a new scene instead of creating one

**Minimal reproduction project:**

Not needed

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.

**Comment by KoBeWi** [comment]
See also #34524
