### ISSUE TITLE
"response.body is undefined" HTML5 not playing  at Itch.io

### ISSUE THREAD

**Issue by diegoferraribruno** [godotengine/godot#47908]
"response.body is undefined" is what i get after uploading the exported my game to itch.io.
I have also made a new test project with just godette and some text but it also have the same error.

**Comment by diegoferraribruno** [comment]
Godot 3.3 RC9

**Comment by akien-mga** [comment]
Please fill the issue template, there's not enough information to help you here.

What project are you testing with? How do you set things up on itch? Did it work in earlier versions?

**Comment by diegoferraribruno** [comment]
**Godot version:3.3 RC9**
**Notebook Acer intel core i3 OS Linux Mint 19 cinnamon.**
**Issue description:**
Exporting HTML5 in godo 3.3 RC9 uploading it to itch.io presentes the error: "response.body is undefined"
While, the same project re-exported in godot 3.2.3 works perfectly!
**Steps to reproduce:**
Create a simple game scene, export in html5 in menu Export (check the exec opt). Zip the exported files and upload it to  an itch.io account  and play it. 

**Minimal reproduction project:**

This is my game working fine re-exported in Godot 3.2.3 https://diegoferraribruno.itch.io/gato-mia-2 You can download the RC9 tests there. :P

**Comment by diegoferraribruno** [comment]
I also tryed all the export type options: Regular, GDNative and Threads... none worked

**Comment by diegoferraribruno** [comment]
ne more thing: In godot 3.3 RC9, just clicking the HTML5> Play in browser works fine!

**Comment by diegoferraribruno** [comment]
OPS FLASH NEWS: it seems that only in firefox 61.0.1 that is not working! It seems to works on my tablet and on Google Chrome.

**Comment by akien-mga** [comment]
Firefox 61 is 3 years old, that's definitely not supported (and a huge security risk).

**Comment by diegoferraribruno** [comment]
I have just found issue #47272 (from RC6) waterfox browser seems to have same issue as my old firefox that was not working with 3.3 exporta. Now after the firefox update everything works. Thanks so much for your attention.
