### ISSUE TITLE
ERROR: (draw_rect: Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal.) while accessing a child from _draw()

### ISSUE THREAD

**Issue by independentCog** [godotengine/godot#4790]
**Operating system or device - Godot version:**
Ubuntu 16.04
Godot 2.0.2 stable
**Issue description** (what happened, and what was expected):
get_child() in _draw function returns 
ERROR: draw_rect: Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal.
   At: scene/2d/canvas_item.cpp:695.

**Steps to reproduce:**
parent Node2D with child 300x300 Sprite
simplest script I could come up with to replicate attached to Node2d:
```
extends Node2D

func _ready():
	var curPos = Vector2(get_viewport().get_rect().size.width/2, get_viewport().get_rect().size.height/2)
	self.set_pos(curPos)
	
func _draw():
	get_child(0).draw_rect(get_child(0).get_item_rect(),Color(1,0,0,0.1))
```
attaching script to child and replacing get_child with self works fine.
when I run:
```
print(get_child(0).get_item_rect())
```
is returning -150,-150,300,300
so its seen it as it should be. Is this a bug?(error message is somewhat strange considering its inside _draw)Does something have to be overridden that I'm not aware of or is this simply not the way to go about this? Thank you in advance.

**Link to minimal example project** (optional but very welcome):

**Comment by Ovnuniarchos** [comment]
You are invoking a draw _on the child_ ( child(0).draw_rect() ). You can use the draw methods of _this_ object, but not those of its descendants.

**Comment by independentCog** [comment]
Is this ever going to be a feature to be included? It would be nice to be able to manipulate multiple sprites/gui with draw from a single script in either a node2d or control parent as opposed to having separate scripts on each reacting to a global trigger.

**Comment by Ovnuniarchos** [comment]
Why would you need to? You can do `draw_rect(get_child(0).get_item_rect(),Color(1,0,0,0.1))` to do what you can't do now, with your problem solved by making the _parent object_ do all the draws, instead of delegating that task to the descendants (which you can't do, because they're not the ones receiving the NOTIFICATION_DRAW).

**Comment by independentCog** [comment]
I see. So i could still use the for loop idea to set draws to the positions of children instead of the actual children. I got my head wrapped around how to do this now. I just had to set on the child sprite behind parent to on in order for it to actually show without having to deform the child with opacity. Thank you for your patience, I am still very much a noob to the ways of this engine. =)
