### ISSUE TITLE
Not able to set material override

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#47913]
**Godot version:**
master : c7a4e2196ee08d7ec5190873bd243fbf2727c18f

**OS/device including version:**
Windows Nvidea 3070 

**Issue description:**
You can no longer set the material override:
![image](https://user-images.githubusercontent.com/1945449/114855325-2f56d680-9e29-11eb-9ba4-48a264a58f5d.png)

**Steps to reproduce:**
1. Create a new meshinstance
2. Add a mesh 
3. Attempt to create a new material for the material override slot

**Comment by akien-mga** [comment]
Possible regression from #47878?
