### ISSUE TITLE
Inspector ranges

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#4791]
Some of the inspector ranges are exagerated, for example why node2D rotation goes from -1440 to 1440, instead of -360 to 360, or light2D energy from -some_big_number to some_big_number, even though energy set to negative does not have effect, and also going above 100 does not seem to have effect either.

**Comment by reduz** [comment]
exagerating the rotation range was done in order to better animate some
node rotations (this was requested by artists), light2D energy should
really be clamped..

**Comment by djrm** [comment]
good to know, im going to work on some of the ranges, but as you mentioned people have different needs, but i think that changing values with the slider must be visible, if the changes are too big to be visible probably the range should be changed

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by mhilbrunner** [comment]
Closing, we got a new inspector - ranges were supported anyway, they just need to be defined. IMO, this issue is outdated, if a specific property needs a range defined or changed, we should have a specific issue or just create a PR to do it.
