### ISSUE TITLE
Vulkan: Selecting MeshInstance causes sun in the sky background to change position

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#47912]
**Godot version:**
master c7a4e2196ee08d7ec5190873bd243fbf2727c18f

**OS/device including version:**
Windows Nvidia 3070

**Issue description:**
When not selected this object renders correctly (black in background is another issue):
![image](https://user-images.githubusercontent.com/1945449/114854882-a2138200-9e28-11eb-8698-de3518961203.png)

But when you select the object:
![image](https://user-images.githubusercontent.com/1945449/114854971-ba839c80-9e28-11eb-9c1e-8f7ff3fd2fe1.png)
Notice how we now have two "suns". 

**Steps to reproduce:**
- Create a new scene
- Add a WorldEnvironment with the sky set to PhysicalSkymaterial
- Add a directional light, make sure its angles down so you get a sun
- Add a MeshInstance with a sphere mesh and add a material that has roughness set to 0 and material set to 1

Select/deselect the object and see the sun position change in the sky..

*edit* found out its the entire sky that changes, it gets a different sun position, and the sky is then reflected.

**Comment by BastiaanOlij** [comment]
Ok, looks like the entire sky is rotated when a meshinstance is selected.

So here the sun is on the right:
![image](https://user-images.githubusercontent.com/1945449/114867052-aa26ee00-9e37-11eb-8e2b-2b749de6e532.png)

And when an object is selected:
![image](https://user-images.githubusercontent.com/1945449/114867114-be6aeb00-9e37-11eb-9a1f-c8c969057dae.png)

**Comment by clayjohn** [comment]
It has to do with the little material preview in the inspector. I have noticed that it overwrites the environment settings for the main scene for some reason.

**Comment by BastiaanOlij** [comment]
I'm going to find some time next week to do an experiment I wanted to do with using RenderState more effectively and as an encapsulation for the data with which the current render pass is being processed. That may help with this too, long shot but.. :)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/f2d55f3c0fabcd4ba4c14d56a6abd4627ebafc4a.
