### ISSUE TITLE
Access editor font and other styles.

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#4793]
**Operating system or device - Godot version:**

Any-Godot 2.1alpha

**Issue description** (what happened, and what was expected):

If we can access the font style and other styles of the editor(May be changed by user to non-default) we can keep the GUI of plugin with same look with editor.

The defaulit  font is too small on my reina laptop screen and it doesn't support Chinese characters. So I changed the font of editor and it works fine. I hope plugins can access and follow the font of editor's to keep same style and display with editor. If it is possible the developers of plugin will no have to add an extra font like this guy [TeddyDD/gtern](https://github.com/TeddyDD/gtern)

**Comment by neikeq** [comment]
I am not sure if I understand the issue. Are you trying to do something like `editor_plugin.get_editor_settings().get("global/font")`?

**Comment by Geequlim** [comment]
@neikeq I don't find the method `get(String)` in class `EditorSettings`.

**Comment by neikeq** [comment]
@Geequlim `EditorSettings` is a derived class of `Object` which has the method `get(String)`. You need the `EditorSettings` instance that is used by the editor, which can be obtained by calling `get_editor_settings()` from an `EditorPlugin` object.

**Comment by Geequlim** [comment]
@neikeq  Thank you! I get the font file path by this function call.
