### ISSUE TITLE
index a property to a singleton in tool mode

### ISSUE THREAD

**Issue by MasTho0128** [godotengine/godot#47946]
**Godot version:**
3.2.2

**OS/device including version:**

**Issue description:**
Godot Engine v3.2.2.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics 4600
OpenGL ES 2.0 Batching: ON

**Steps to reproduce:**

Create a script
I add tool and I get this error

  <built-in>: 73 - Invalid get index 'difficulty' (on base: 'Node (Save_game.gd)').

the property if I call it but it is after "if! Engine.editor_hint:" which should not be executed from the editor. I already tried to remove the property momentarily and even so it continues to appear

Save_game is a singleton

If I remove tool from the script the error no longer runs. But this object I need it with tool for customization

**Comment by akien-mga** [comment]
Please ask such questions on other community platforms better suited to user support, such as Discord, Reddit, the forum or the Q&A: https://godotengine.org/community/

This platform is for bug reports only, and nothing indicates that there is a bug in the current report. The error is most likely in your code.
