### ISSUE TITLE
Android custom build export fails to build with Android NDK 22.0.7026061 installed

### ISSUE THREAD

**Issue by bluebarnacles** [godotengine/godot#47949]
**Godot version:**

v3.3.rc8.official

**OS/device including version:**

Windows 10

**Issue description:**

Attempting to export my Android project with custom build enabled (or run it) fail, with this error message:

    Execution failed for task ':stripReleaseDebugSymbols'.
    > No version of NDK matched the requested version 21.4.7075529. Versions available locally: 21.1.6352462, 21.3.6528147, 22.0.7026061

If I edit `android/build/config.gradle` in my project directory to change ndkVersion from 21.4.7075529 to 22.0.7026061, I am able to export.

This might be fixed by updating `ndkVersion` in `platform/android/detect.py` and `get_project_ndk_version()` in `platform/android/java/app/config.gradle`.

**Steps to reproduce:**

1. Update the Android SDK
2. Uninstall Android NDK 21.4.7075529, if present
3. Create a new project, with an Android build (or use the attached)
4. Check Custom Build, in export dialog
2. Install the v3.3.rc8.official Android build template
3. Export the Android build

**Minimal reproduction project:**

[android_custom_build_failure.zip](https://github.com/godotengine/godot/files/6323311/android_custom_build_failure.zip)

**Comment by akien-mga** [comment]
That's not a bug, you should use NDK 21.4.7075529.

That's what is required to build Godot (NDK 22.0 is not supported #44055), and so we can't assume that custom builds would work with NDK 22.0. It's safe to use the version which is tried and tested.

**Comment by bluebarnacles** [comment]
Thanks for the reminder! I installed that specific version of NDK and it worked.
