### ISSUE TITLE
WARNING: 1 RIDs of type 'UniformBuffer' were leaked.

### ISSUE THREAD

**Issue by JohnCWakley** [godotengine/godot#47941]
First, I have found several similar issues here, but all have been closed with one stating to open a new issue if the issue arises again. I apologize ahead of time in case this is not needed, my intention is merely to inform the team.

If any additional information is needed, please let me know.

**Godot version:**
4.0.dev.custom_build.0c8ec7237

**OS/device including version:**
OS: Solus 4.2
CPU: AMD RYZEN 5 3400G 4-Core 3.7 GHz
GPU: Radeon RX Vega 11 Graphics
Driver: Advanced Micro Devices, Inc. [AMD/ATI] Picasso (rev c8)
API: Vulkan

**Issue description:**
```
Godot Engine v4.0.dev.custom_build.0c8ec7237 - https://godotengine.org
Vulkan API 1.2.162
Using Vulkan Device #0: AMD - AMD RADV RAVEN (ACO)
- Vulkan subgroup size 64
- Vulkan subgroup stages STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE
- Vulkan subgroup supported ops FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD
- Vulkan subgroup quad operations in all stages
DisplayServer::_create_window 0 want rect: 448, 240, 1024, 600 got rect 448, 240, 1024, 600
 
ERROR: Condition "!d.has("cell_size")" is true.
   at: set_data (servers/physics_3d/shape_3d_sw.cpp:1702)
DisplayServer::_window_changed: 0 rect: 0, 39, 1024, 600
DisplayServer::_window_changed: 0 rect: 0, 39, 1920, 1002
ERROR: Attempting to use an uninitialized RID
   at: getornull (./core/templates/rid_owner.h:197)
ERROR: Condition "!material" is true.
   at: material_set_shader (servers/rendering/renderer_rd/renderer_storage_rd.cpp:1556)
WARNING: 1 RIDs of type 'UniformBuffer' were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:7989)
```

**Steps to reproduce:**
Open TestProject (supplied below) from command line `$ godot -e .`
After the project has loaded, simply close Godot.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/6321737/TestProject.zip)

This project has one scene with only one Node3D in it.

**Comment by Mo8it** [comment]
ERROR: Attempting to use an uninitialized RID
   at: get_or_null (./core/templates/rid_owner.h:199)
ERROR: 1 RID allocations of type 'N10RendererRD7TextureE' were leaked at exit.
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9435)

I get something similar. Also on AMD

**Comment by Calinou** [comment]
@Mo8it Which Godot version and operating system are you using?

**Comment by Mo8it** [comment]
On the Godot 4 nightly build of yesterday (03.04.2022) but also on alpha5.

Specs are here: https://codeberg.org/unfa/Liblast/issues/169#issuecomment-384614

New problem with my editor every few days :(

But I know that it is alpha software. Thanks for your effort!

**Comment by clayjohn** [comment]
These errors no longer come up regularly and much has changed since this issue has been updated. There are no errors printed when running the MRP either. Closing as fixed
