### ISSUE TITLE
Game windows focus/unfocus signal or properties

### ISSUE THREAD

**Issue by eXponenta** [godotengine/godot#4795]
How i can identify focus/defocus on Game window on PC|Mac platform? 

I use both keyboard and window draging as character control, but if key was been pressed and then window has been defocused or draged, keyboard action `Input.is_action_pressed ` got stuck on `true` and resets only after focusing on window and pressing on another key.

**Comment by Calinou** [comment]
You can use this:

```gdscript
func _notification(what):
	if what == MainLoop.NOTIFICATION_WM_FOCUS_IN:
		print("Focused!")
	elif what == MainLoop.NOTIFICATION_WM_FOCUS_OUT:
		print("Unfocused!")
```
