### ISSUE TITLE
godot script: clone sub class (improvement)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#4796]
I wrote here such script:
fuzzy.gd

```
extends Node
# sub class
class FzSet:
   var st
   func _init(v):
      st = v.st
   func clone():
      return FzSet.new(self)
```

eventually I found that this does not work. should be replaced

```
return FzSet.new(self)
```

 to

```
extends Node
# sub class
class FzSet:
   var st
   func _init(v):
      st = v.st
   func clone():
      return load("res:/fuzzy.gd").FzSet.new(self)
```

But it looks like that scary.

PS.
Perhaps there is another way, and I just do not know about it.

**Comment by reduz** [comment]
return get_class().new()

**Comment by ret80** [comment]
Invalid call. Nonexistent function 'get_class' in base 'Reference ()'.

> return get_class().new()

**Comment by eska014** [comment]
`return get_script().new()`

**Comment by eska014** [comment]
You can't reference `FzSet` within `FzSet`, so you call `get_script()` to retrieve the class instead.
So you would change your original `clone()` function like this:

    func clone():
        return get_script().new(self)

**Comment by ret80** [comment]
Yes, that's it ``` return get_script().new() ``` works. But it is not pretty. Probably still worth making improvement.

**Comment by vnen** [comment]
Apparently `get_script().new()` does not work in the main class of the file. I'm gonna try to remember to test this tomorrow, but it also fits this proposal, I think.

**Comment by bojidar-bg** [comment]
Is this by any chance a duplicate of #944?

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/391, closing.
