### ISSUE TITLE
Setting font on labels will crush the app on Android

### ISSUE THREAD

**Issue by azurvii** [godotengine/godot#4797]
**Operating system or device - Godot version:**
Nexus 7, Android 6.0.1, Godot compiled @commit b777b3.

**Issue description** (what happened, and what was expected):
If I specify a font in a GUI node, e.g. Label, and deploy the app to Android, the app won't start, and stays in a loop showing Godot splash screen, crashing, and again.
This happens to both bitmap or dynamic fonts on this build. If a bitmap font is used, the same project works just fine running on Godot 2.0.3.

**Comment by akien-mga** [comment]
Did you compile templates for b777b32, or are you using templates for 2.0.3? If so, they are not compatible, you should always use templates that match your editor version.

**Comment by akien-mga** [comment]
Same error as #4606, so likely same resolution :)

**Comment by azurvii** [comment]
Thanks @akien-mga, tried compiling and the new templates seemed to work fine.
The template compiling process needs quite a lot manual intervention, and is not as convenient as Godot compiling.

**Comment by akien-mga** [comment]
Yeah building templates is a lot of work. We'll soon make an official 2.1 alpha release with editor + templates, so that should help for people who want to play with the development branch :)
