### ISSUE TITLE
When vsync is off, Godot got higner frame rate but looks like in lower frame rate

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#47972]
**Godot version:**

all 3.3 (include preview 3.2.4) and 3.2.3 stable

**OS/device including version:**

![Screen Shot 2021-04-17 at 18 46 11](https://user-images.githubusercontent.com/64188282/115110295-33136600-9fad-11eb-8d18-676d7f47eea6.png)

**Issue description:**

when I set vsync to off, and printed FPS to output, I saw I got higher frame rate, but the game actually looks like in lower frame rate

**Steps to reproduce:**

https://user-images.githubusercontent.com/64188282/115110402-d2d0f400-9fad-11eb-9d6d-8fd394fe84ba.mov

https://user-images.githubusercontent.com/64188282/115110458-1f1c3400-9fae-11eb-9f2c-abfe065d4a69.mov

**Minimal reproduction project:**

[RenderingTest.zip](https://github.com/godotengine/godot/files/6329095/RenderingTest.zip)

**Comment by snougo** [comment]
also see the last comment from me here https://github.com/godotengine/godot/issues/43038

**Comment by lawnjelly** [comment]
Some possibles are some kind of throttling issue on your system (is the GPU overheating?), or it is running out of resources and garbage collecting or something (we could even be e.g. rendering 10 frames ahead, it runs out of memory and stalls until it catches up etc). The running out of resources (especially vertex buffers) could have been influenced by the flags in 3.3, but if they don't seem to help I'm running out of ideas.

Artificially limiting the frame rate via sleep may be helping with either of these possibilities (and using vsync which I assumed you had tried). There are also countless other possibilities of course. Unfortunately it's mostly guesswork unless you accidentally hit on something that triggers it, given that we can't reproduce this our side.

**Comment by snougo** [comment]
@lawnjelly  yeah, I agreed, these issues are very likely only appeared on specific device or system and hard to find what's going on, anyway thank you for your patient response!  at least I find the solution how to fix them in my device 🕶️

**Comment by Calinou** [comment]
Video captures do not accurately display the effective framerate you can reach, unless you use a capture card. This is especially true when not using V-Sync and having an uncapped framerate, as the CPU and/or GPU will be saturated.

**Comment by snougo** [comment]
https://github.com/godotengine/godot/pull/48555 this PR has sloved this issue @lawnjelly thanks a lot!
