### ISSUE TITLE
GooglePlayBilling  _on_purchase_consumed  function does not always work

### ISSUE THREAD

**Issue by abhiagnihotri01** [godotengine/godot#47970]
**Godot version:**
3.2.2

**OS/device including version:** Android
**GodotGooglePlay Billing Version:** 1.0.1

**Issue description:**
When i buy something using GooglePlayBilling, the function  "_on_purchase_consumed" sometimes get called even after successfull payment. And sometimes the payment get failed but still the function "_on_purchase_consumed" get called.
Can you please resolve this or if its there a workaround to resolve this problem.

**Steps to reproduce:**
Insert debugs in the function "_on_purchase_consumed" to get whether its getting called or not after successfull and un-successfull payment.

**Comment by Xrayez** [comment]
I think this issue can be transferred to https://github.com/godotengine/godot-google-play-billing repository.

**Comment by abhiagnihotri01** [comment]
Do i need to create this issue inside the link shared above or this issue will get automatically transferred to it ?

**Comment by RAINBOW-Men** [comment]
think this issue should be transferred to https://github.com/godotengine/godot-google-play-billing repository.

**Comment by Anutrix** [comment]
Can we close or move this ticket?
