### ISSUE TITLE
Particle positions are not continuous when the Particles node is moved at a high speed (missing interpolation)

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#47973]
Godot version:
3.3rc9, 4.0

OS/device including version:
Windows 10

Issue description:
Particle positions are frame rate dependent, which causes discontinuous distribution of the particles when the particle node moves fast.

Particle2D:
![particle2d](https://user-images.githubusercontent.com/28705694/115111125-5213f700-9fb1-11eb-999e-7199cbe15e2d.gif)

Particle3D:
![image](https://user-images.githubusercontent.com/28705694/115111121-4f190680-9fb1-11eb-920b-89618f0aea2d.png)

Steps to reproduce:
Create a 2D or 3D particle node, set a high emission amount, animate the node itself to move fast, observe the particle clusters.

Minimal reproduction project:
No need.

**Comment by Calinou** [comment]
I don't see a way to solve this, aside of unlocking the framerate by disabling V-Sync.

**Comment by mortarroad** [comment]
When emitting, you can simply interpolate between the old and the new transform of the emitter.
This comes with the issue that "teleporting" the emitter doesn't work anymore by just setting the position. (It will cause a thin trail of particles from the old to the new position, because it is considered a very fast movement.)
This could be solved by having a dedicated "teleport" function for that.
And this can also be made into a flag to turn this behavior on and off.

**Comment by Calinou** [comment]
> This could be solved by having a dedicated "teleport" function for that.
And this can also be made into a flag to turn this behavior on and off.

See also https://github.com/godotengine/godot-proposals/issues/671 and https://github.com/godotengine/godot-proposals/issues/1936.

**Comment by Calinou** [comment]
@floppyhammer In the meantime, you may be able to hide this by making particles emitted over a box area rather than a single emission point. You can do this by changing the emission point property in the particles material. This is available in both Particles and CPUParticles, in both 3D and 2D.

**Comment by floppyhammer** [comment]
@Calinou Hadn't thought of this workaround. Thanks!

**Comment by reduz** [comment]
There is a fixed FPS for particles, you can put it to 60 to fix this.

**Comment by floppyhammer** [comment]
@reduz Setting `fixed_fps` to 60 has no effect when the game already runs at 60 FPS.

**Comment by Calinou** [comment]
@floppyhammer Do higher `fixed_fps` values such as 120 look smoother?

**Comment by floppyhammer** [comment]
@Calinou No, it makes no difference when going beyond 60.

![Peek 2021-04-26 11-17](https://user-images.githubusercontent.com/28705694/116024682-4eebcb80-a681-11eb-8706-86f7d0956f47.gif)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/8088, as feature proposals are now tracked on the Godot proposals repository.
