### ISSUE TITLE
negative scales on double sided sprite 3ds break shadows

### ISSUE THREAD

**Issue by thepromaper** [godotengine/godot#47984]
**Godot version:**
3.2.3  stable

**OS/device including version:**
Windows, i dont think it matters but im using vega 8 graphics on ryzen 2200G

**Issue description:**
negative scales on double sided sprite 3ds break shadows, or perhaps it shows the other side`s shadows instead.

**Steps to reproduce:**
this is the scene i got the issue on:

![image](https://user-images.githubusercontent.com/72669769/115122531-fc722700-9f7d-11eb-988e-641fc1a0a2a4.png)

the light needs to be facing negative z, in this case im using directional light, you need something to cast a shadow, and turn on shadows on the light, then you need the afected sprite 3d, mark it with opaque prepass, shaded, and double sided, then play with negative scales, its gonna screw up.

**Minimal reproduction project:**

[testforgit.zip](https://github.com/godotengine/godot/files/6329791/testforgit.zip)

**Comment by Calinou** [comment]
Try enabling **Ensure Correct Normals** on the SpatialMaterial used on the Sprite3D. You can do this by adding a material override to the Material Override property in the Sprite3D's GeometryInstance section.

Note that enabling this property has a cost, so you should only do it when absolutely needed.

**Comment by clayjohn** [comment]
I can't reproduce.

The shadow looks fine no matter what the scale of the sprite is.

The only related thing I noticed is that the normals are reversed when you reverse the scale. This, however is expected behaviour. When you set a negative scale, the values will be negative.

**Comment by thepromaper** [comment]
ok so calinou said i should enable spatial material override and enable ensure correct normals, this makes the sprite dissapear when cull mode is in the default, setting it to disabled fixes it as expected, however the problem persists.

by the way i tried with z and y scalking too, the problem still appears, shadows dissapearing.

tested on android, can reproduce.
updated project with the material stuff:

[testforgit.zip](https://github.com/godotengine/godot/files/6330194/testforgit.zip)

**Comment by thepromaper** [comment]
now that i see it, shadows dont dissapear, but appear on the other side instead.

**Comment by clayjohn** [comment]
Can you please post pictures of what you are seeing and what you expect to see?

As I said above, when I tested your MRP the shadow looked correct no matter what scale I used.

**Comment by thepromaper** [comment]
thats weird im attaching some video since you cant reproduce, but i cat imagine why, it works in my phone too.



https://user-images.githubusercontent.com/72669769/115146361-cdaa8e00-a01b-11eb-801c-b2806b3fc8e4.mp4

is this expected? i would expect the sprite to flip its texture and children rather than flip with his shadow

**Comment by thepromaper** [comment]
[https://youtu.be/GtMp562PtN8](url)

i had to sent a link, github upload didnt work.

i personally expect the same effect as flip, but affecting children`s position, and not flippng with his shadow to the other side

**Comment by clayjohn** [comment]
Thanks for the video. 

What you show in the video is not a shadow issue. Your shadow looks totally fine throughout.

When you scale an object its attributes are scaled as well. For example, when you double the X scale of an object the vertex normals are scaled accordingly. This is necessary so that lights affect the surface appropriately. When you use a negative scale, the normals are correctly multiplied by scale resulting in reversed normals. With a regular mesh this would look obvious because the mesh would be reversed totally. However, since you are using a double-sided sprite the only difference you notice is the fact that the normal is reversed. 

A flip and a negative scale are two very different operations.
