### ISSUE TITLE
Visual error with broken shader and batching

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#47995]
**Godot version:**
3.3 RC9

**OS/device including version:**
All

**Issue description:**
A shader that has an error in it can sometimes produce unexpected results.
This occurs when batching is on, when batching is off, it seems to reuse the last valid state of the shader.

Broken:
![broken_error](https://user-images.githubusercontent.com/21999379/115138277-fbdf9c00-a022-11eb-942d-fbab1fe572d6.png)
Correct:
![broken_correct](https://user-images.githubusercontent.com/21999379/115138282-039f4080-a023-11eb-95ac-544e3a49e899.png)

**Steps to reproduce:**
Load the minimum reproduction project in Godot IDE. Open the shader, first fix the error by adding semi colon, the shader will display correctly. Then break the shader by removing the semi colon, there will be white squares that appear.

Remove / add the semi colon after MODULATE to break the shader:
![broken_shader](https://user-images.githubusercontent.com/21999379/115138455-35fd6d80-a024-11eb-8d35-ce51f53009f9.png)

It is important that when you first load the project with the broken shader it will look fine, you need to fix it (create a valid shader) then break it (creating a half valid shader) for the error to occur.

**Minimal reproduction project:**
[broken_shader_bug.zip](https://github.com/godotengine/godot/files/6330704/broken_shader_bug.zip)

**Comment by akien-mga** [comment]
Fixed by #47994.
