### ISSUE TITLE
Overriding the Resource virtual method _setup_local_to_scene doesn't seem to work

### ISSUE THREAD

**Issue by wupingli2021** [godotengine/godot#48017]
Godot version:
v3.3 rc9

OS/device including version:
Windows 10

Issue description:
Rewrite method "_ setup_ local_ to_ Scene "was not called
![1111](https://user-images.githubusercontent.com/80683955/115229386-90dab600-a145-11eb-85df-b68dc386761d.png)

Steps to reproduce:
1.play scene
2.The console did not print a message

Minimal reproduction project:
[Resource_Demo.zip](https://github.com/godotengine/godot/files/6335621/Resource_Demo.zip)

**Comment by akien-mga** [comment]
I tested the project, it works but you forgot to enable Local To Scene in the Resource:

![Screenshot_20210419_133951](https://user-images.githubusercontent.com/4701338/115230518-c4511c80-a114-11eb-82d5-d7fafc2e368d.png)

See https://docs.godotengine.org/en/3.3/classes/class_resource.html#id1
