### ISSUE TITLE
Weird rigid body behaviour

### ISSUE THREAD

**Issue by pcmxms** [godotengine/godot#4801]
What version are you on? 2.0.3 - Linux Mint 17.3

Whenever a rigid body stays with its center of mass away from an edge, it should starts rotating. The expected behaviour happens only if the collision shape is in one (maybe more) particular rotation state:

https://media.giphy.com/media/3oAt28ng9R3avLQVry/giphy.gif

**Comment by vnen** [comment]
That is likely related to rotation of collision shapes (those don't like to be scaled or rotated). Still, I guess it's natural to rotate a capsule shape to fit your needs.

If you can provide a test project as an attachment to this issue (in a zip file), please do, so it helps debugging.

**Comment by bojidar-bg** [comment]
@vnen ~ AFAIK, rotation of collision shapes is not a problem, only scaling them (or their respective bodies) is...

**Comment by akien-mga** [comment]
BTW this collision shapes scaling issue should really be fixed somehow (but that's a matter for another issue).

**Comment by slapin** [comment]
This one is to be fixed for both 2D and 3D, too.

**Comment by pcmxms** [comment]
There. (Sorry for not responding it earlier). If you get only the collision shape of the rigid body and rotate it 180 degrees, everything goes fine. Note that all the scales (except for the sprite scale) are equal to 1, so it is not a problem of scaling. The original rotation for the collision shape is 0, so my guess is .... don't have no idea. :/

Thanks! 

[bug.zip](https://github.com/godotengine/godot/files/282237/bug.zip)
