### ISSUE TITLE
Autogenerated collision shapes with script wont export as tileset collision shapes

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#4802]
**Operating system or device - Godot version:**
Windows

**Issue description** (what happened, and what was expected):
I used an script to autogenerate an scene to export as a tileset, this script created a CollisionRectangle2D and assigned it to the CollisionShape nodes, however when i exported the scene as a tileset, all collision was null, but if i created a new collision rectangle from editor and assigned to a colision shape, that, and only that tile will have a collision...

**Steps to reproduce:**
Use this script to create an exportable scene with some collisions (scene should have a root node before runing it with Ctrl+Shift + R)
http://pastebin.com/1W9WB2Tg
(this script will use individual textures as tiles, you might need to change the path variables to use the right directories)

**Comment by MarianoGnu** [comment]
didn't try out, but maybe this can be extended to navpoly and occlusion

**Comment by neikeq** [comment]
It seems to look for the shapes in the StaticBody2D. Try adding the shapes directly to the StaticBody2D.

**Comment by reduz** [comment]
the way CollisionShape works is pretty hacky, and needs to be changed. So far this didn't happen to avoid breaking compatibility but we will do it for version 3.0

**Comment by reduz** [comment]
wow, again closing the same bug for the 13th time or so..

**Comment by MarianoGnu** [comment]
in my defense, this bug had one and a half year old :P
