### ISSUE TITLE
Panorama skybox causes freckles

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#48032]
**Godot version:**
4.0.dev f817e7fb

**OS/device including version:**
Windows 10

**Issue description:**
In master branch, importing an HDR skybox with a bright sun seems to produce strange filtering artifacts on the ambient light of all meshes with Roughness about equal to 1. It's extremely noticeable and affects almost all meshes,

As roughness is decreased, artifacts at more detailed reflection LODs also exist but are far less pronounced... roughness=0 looks perfectly fine.

![roughness_freckles](https://user-images.githubusercontent.com/39946030/115325715-f9736400-a140-11eb-8097-e165988fbe78.png)

The freckles seem to be caused by an extremely bright sun (intensity 5-10 or so) in the skybox texture. This issue is not present in Godot 3.x: it seems unique to master branch (It's not a new problem in master: This issue has existed since mid-to-late 2020 at least... but I don't think a bug was filed about it yet)
The texture I am using was literally a reflection probe texture copied from Unity. But I could see the same issue happening in a photographic HDRi skybox containing a bright sun.

**Steps to reproduce:**
1. Open the attached project. Observe the objects in Node3D.tscn. The first capsule is maximally rough, but exhibits a strange freckling.
2. Other smooth objects show minimal or no artifacts.
3. Select the WorldEnvironment, and modify the panorama to have the compatible_skybox_nosun.exr texture. 
4. The freckle dots disappear.

**Minimal reproduction project:**
Godot project: [FrecklesTest.zip](https://github.com/godotengine/godot/files/6340079/FrecklesTest.zip)
Equivalent Godot 3.x project: [FrecklesTest_3.zip](https://github.com/godotengine/godot/files/6340080/FrecklesTest_3.zip)

**Comment by fire** [comment]
Switch to openexr. I spent a notable amount of time debugging firefly `.hdr` artifacts.

**Comment by fire** [comment]
See https://github.com/godotengine/godot/issues/32125

**Comment by lyuma** [comment]
Actually looks to be a duplicate of #43763, so I'll close this one.
