### ISSUE TITLE
project settings type does not match what is added

### ISSUE THREAD

**Issue by indubitablement2** [godotengine/godot#48045]
**Godot version:**
Godot_v3.3-rc9_win64

Tested on Godot_v3.2.3-stable_win64 without issue.

**Issue description:**
When adding new project setting, type name does not always match what is added. For example, adding an array will add a dictionary.

**Steps to reproduce:**
![lsVzVQigCa](https://user-images.githubusercontent.com/62550921/115401659-a1784400-a1b8-11eb-899b-0a166d62918b.gif)

**Comment by akien-mga** [comment]
That's very likely a regression from #42616, which removes two entries from the list but doesn't handle the code which then actually creates those Variant types (most likely by assuming that their `OptionButton` index matches their `Variant` index).

**Comment by Xrayez** [comment]
I think there are many such assumptions throughout Godot editor. A warning in the project settings should suffice I think.
