### ISSUE TITLE
variable/reference to object that got queue_freed is not null anymore. Accessing throws null exception

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#48040]
Might be duplicating: https://github.com/godotengine/godot/issues/45639

Still posting to make sure/clarify

**Godot version:**
v3.3-rc9

**OS/device including version:**
Windows 10

**Issue description:**
in 3.2.3 if an object gets freed, every reference to it then counts as null. That way checks for "if not object:" will work.
But in r8 and r9 this seems to have been changed, so that checking if a reference/variable with the object "if not object" will return false, but then trying to access a method/variable on the object will give me a null-pointer.

Either it works the way it works for 3.2.3 or it gives a proper Error-message like "cant access X on freed object Y"

**Steps to reproduce:**
Start the reproduction project and press play.
In 3.2.3 it should work and print without complaint
In 3.3-rc8/rc9 it should throw null error on "child.is_alive()"

**Minimal reproduction project:**
[Queue-free-null-reproduction.zip](https://github.com/godotengine/godot/files/6342200/Queue-free-null-reproduction.zip)

**Comment by akien-mga** [comment]
That's intentional as documented in #45639 indeed.

You *will* get a null exception when trying to access a freed variable in a release build, so it's preferred to also get them in a debug build so that you can fix your code. Otherwise you game will work in debug and crash in release.

**Comment by akien-mga** [comment]
> But in r8 and r9 this seems to have been changed, so that checking if a reference/variable with the object "if not object" will return false, but then trying to access a method/variable on the object will give me a null-pointer.

Do you mean that you're not getting an error in the editor?

With the provided project on Linux I properly get an error as expected:

![Screenshot_20210420_111209](https://user-images.githubusercontent.com/4701338/115370417-56b2f800-a1c9-11eb-8e8c-e67f5f7bf92c.png)

**Comment by Reneator** [comment]
"Do you mean that you're not getting an error in the editor?"

Im getting the null-point exactly as you have in your image!

Thanks a lot for the clarification and your extended answer in your referenced issue!

Have a great day!
