### ISSUE TITLE
Weird texture corruption

### ISSUE THREAD

**Issue by MattArtzthedev** [godotengine/godot#48044]
**Godot version:**

Godot 3.3 RC 4 = RC 9

**OS/device including version:**

Windows 10, Intel UHD 620, GLES2

**Issue description:**

so i was adding the icon.png as a texture for my floor, but suddenly the textures became this.. its like corrupted.
![Screenshot (126)](https://user-images.githubusercontent.com/79185162/115400551-fdc07f80-a21b-11eb-83f4-b4f0b1e4ec85.png)

**Steps to reproduce:**
i don't know if this is only for me but:
add a cube then add any texture to it.

**Minimal reproduction project:**

i cant post it because the issue fixes itself after restarting, but this is very annoying.

**Comment by akien-mga** [comment]
I can't reproduce the issue with the given steps to reproduce on Linux with Intel HD Graphics 630.

**Comment by MattArtzthedev** [comment]
i don't really know if this problem is only for me, but yeah.
i would post the project files but the issue will fix itself after restarting

**Comment by lawnjelly** [comment]
The project files may still give a clue as to what / why this is happening.

**Comment by MattArtzthedev** [comment]
i can't post the project files due to the issue fixing itself after restarting.

**Comment by MattArtzthedev** [comment]
story is i put the icon.png as a test texture for the cube. suddenly that thing happened

**Comment by MattArtzthedev** [comment]
https://streamable.com/vd964s
here's the video how this happened.

**Comment by MattArtzthedev** [comment]
not only a corruption, but if the texture is not triplanar, its just a black color, it feels like you're staring at the void

**Comment by lawnjelly** [comment]
I can't seem to reproduce it here by following the same method (which isn't uncommon for graphics issues). I must admit I'm a bit stumped.

In your video it strangely appears to work while dragging the texture in, then stop working once the texture is released. I'm not sure what happens between these two points in terms of the code / GL states.

The fact it shows in the preview and works after restart suggests your GPU *does* work with the shader. So at a guess it might be some GL state is getting set which is preventing drawing properly on yours (but not on other GPUs). But it could be a lot of things.

It could also be something specific to the CSG, I'm not that familiar with the CSG nodes. Especially if the same does not occur in e.g. a MeshInstance box. It could be it is not generating / updating the vertex buffer with the correct UV data or something in that particular case.

**Comment by Calinou** [comment]
@MattArtzthedev Can you (or anyone else) still reproduce this bug in [Godot 3.5](https://godotengine.org/article/godot-3-5-cant-stop-wont-stop) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
