### ISSUE TITLE
Vulkan: SpotLight3D angles above 90 degrees cause clustering artifacts (even with shadows disabled)

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#48054]
**Godot version:**
4.0.dev f817e7fb

**OS/device including version:**
Windows 10.0.19041.928
Nvidia RTX 2080 Ti
Driver version 466.22 

**Issue description:**
SpotLight angles seem doubled from what makes intuitive sense to me. For example, an angle of 120 degrees covers roughly 240 degrees of the sphere. 179 degrees covers effectively the whole sphere, same as an omni light.

However, when the Spotlight angle exceeds a Hemisphere (90 degrees in Godot), the spotlight continues to expand, but the clusters collapse to (180-angle) degrees, causing the square clustering artifacts.

![image](https://user-images.githubusercontent.com/39946030/115455719-2a05dd00-a1d7-11eb-90c9-bf95411ce635.png)

My opinion is spotlights which are greater than a hemisphere are kind of a strange concept, but if they are intended to be supported, perhaps this could be worked around by having the clustering algorithm treat them like omni lights.

**Steps to reproduce:**
1. Open the attached project
2. Zoom the camera as in the above screenshot, so that the camera is facing the spotlight and the capsule is off to the side.
3. Play with the spot angle and note how as the angle increases, the cluster squares diminish.
4. For spot angles < 90, everything renders perfectly fine.

**Minimal reproduction project:**
[SpotLightClusterTest.zip](https://github.com/godotengine/godot/files/6346350/SpotLightClusterTest.zip)

**Comment by Calinou** [comment]
> My opinion is spotlights which are greater than a hemisphere are kind of a strange concept, but if they are intended to be supported, perhaps this could be worked around by having the clustering algorithm treat them like omni lights.

They are intended to be supported, but only when shadows are disabled. Otherwise, a node configuration warning is emitted.

**Comment by Calinou** [comment]
I can confirm this on commit 52e3f986a (Linux + NVIDIA).

**Comment by ngreve** [comment]
I have encountered something similar with the "Junk Shop" scene. Is this the same issue in another form, or should I create another issue for that? 

https://user-images.githubusercontent.com/18660100/132385625-f01de16c-51bc-4f45-a0ca-f3ef459e29df.mp4

**Comment by Calinou** [comment]
We don't seem to have access to the spot angle in the cluster data, so we can't treat ultrawide SpotLights as OmniLights. The only reference to SpotLights in the cluster builder is here:

https://github.com/godotengine/godot/blob/a6a2e0feb9a64a624e01789b7a3fb126e9acefc0/servers/rendering/renderer_rd/cluster_builder_rd.cpp#L449-L451

**Comment by rustwork** [comment]
This is also an issue with narrow spotlight angles less than about 40 degrees. It's easy to reproduce by setting a spotlight's angle to about 11, turning up the energy and range and putting a spotlight close to some geometry.

![image](https://user-images.githubusercontent.com/2095704/181877366-a4377eb5-0bf0-4caf-a828-3a1b5ced683e.png)


Seen in 4.0 alpha 10, 11, 12 and 13 on windows 10, Nvidia Geforce 3060 Ti

**Comment by Calinou** [comment]
@rustwork This isn't exactly the same issue, although it may have a similar cause. See https://github.com/godotengine/godot/issues/59262.
