### ISSUE TITLE
Problem reading certain axes on the right analog stick of gamepad

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#48067]
**Godot version:**

3.3 rc9 mono

**OS/device including version:**

win10 64

**Issue description:**

The right analog stick is not well read by Godot.
Some angles appear dead and the values do not change.
I have two different joys and the same thing happens in both.

Watch the video, I never stop turning the analog stick and the angle shows that the values update in a strange way.

![Captura](https://user-images.githubusercontent.com/19652075/115617074-3f6f2a00-a2f1-11eb-8fa1-99346a98e60f.PNG)

https://youtu.be/YPNAUwTr4BM

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
> I have two different joys and the same thing happens in both.

Which gamepad models did you try?

**Comment by Torguen** [comment]
http://rumble-re.blogspot.com/2014/11/game-list-ipega-game-pad.html

https://www.amazon.com/Trust-GXT-540-Wired-Gamepad/dp/B0151GJSSM

this two

**Comment by Torguen** [comment]
Can anyone try this with a different controller?

**Comment by madmiraal** [comment]
Godot doesn't read the controller. It responds to events sent by the controller. So, it's more likely to be a limitation of the controller. From the looks of it, the right stick may be mapped via the DPad i.e. only returning -1, 0 or 1.
To help confirm my theory, please provide the outputs of `Input.get_joy_axis(0, JOY_ANALOG_RX)` and `Input.get_joy_axis(0, JOY_ANALOG_RY)`; instead of just the calculated angle between them. Also, please provide the GUIDs for the joysticks using [`Input.get_joy_guid(0)`](https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-get-joy-guid); so we can confirm the mappings.

**Comment by Torguen** [comment]
Is it enough if I record a video as before?

**Comment by madmiraal** [comment]
A video helps understand the relationship between what you're physically doing with the joystick and the values `Input.get_joy_axis()` returns. I'm curious to know what the range of values is. Is it limited to -1, 0 and 1? Does it return everything in between? Or, is it some limited subset of values?

**Comment by Rubonnek** [comment]
I'm guessing the SDL Game Controller configuration mapping is not correctly configured for your controller.

Have you attempted to [map the keys](https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html#my-controller-has-incorrectly-mapped-buttons-or-axes/) for your controller?

I personally use the [SDL2 GamePad tool](https://www.generalarcade.com/gamepadtool/).

You can install the joypad configuration string the tool provides at runtime in an [Autoload](https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html).

```gdscript
extends Node
func _ready():
    var joypad_configuration_string : String = "gamepadtool, or controllermap configuration string goes here"
    var overwrite_existing_entry : bool = true
    Input.add_joy_mapping(joypad_configuration_string, overwrite_existing_entry)
```

**Comment by Torguen** [comment]
It is a problem of the control, in the configuration of the control in windows, it behaves in the same way. It is not related to Godot.
