### ISSUE TITLE
Incorrect UI scale in editor

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#48069]
**Godot version:** 3.3.stable

**OS/device including version:** Manjaro Linux

**Issue description:**

The GUI in the editor is way too small. The scale is correct in 3.2 and older

![image](https://user-images.githubusercontent.com/16022203/115628630-24cf8d80-a2be-11eb-9aae-12613ae544ba.png)

**Steps to reproduce:**
N/A

**Minimal reproduction project:**

N/A

**Comment by clayjohn** [comment]
What is your display resolution?

Maybe it is a result of this PR https://github.com/godotengine/godot/pull/43611

**Comment by andersmmg** [comment]
My main display is 1366x768, and I have another 1920x1080. If I open it with the larger display connected as well, it's the right scale, so that pull request is probably the reason. Is there a way to stop the scale from changing?

**Comment by clayjohn** [comment]
I'm not sure, but it looks like you can override the automatic display scale using ``interface/editor/custom_display_scale`` in the editor settings!

Give that a try and let me know how it goes.

**Comment by andersmmg** [comment]
Yeah, that works! Cool, since the borders work on small scales now I might switch back sometimes but this did what I want for now. Thanks :)

**Comment by Calinou** [comment]
What's surprising though is that your screenshot is 814 pixels tall, yet the 0.75 scale factor is being applied even though it's supposed to apply only to displays less than 800 pixels tall.

**Comment by andersmmg** [comment]
Looking at it, I think the screenshot was taken on my external monitor to be able to see both windows easily. I plugged it in after launching both just to take the screenshot, so the engine just didn't know about the new display size.
