### ISSUE TITLE
GIProbe bake result looks different/darker than 3.2

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#48077]
**Godot version:**
Godot_v3.3-stable_mono_win64

**OS/device including version:**
windows 10, nvidia1050ti   drivers v.451

**Issue description:**
Just testing the new stable release with the demo https://github.com/Calinou/godot-sponza

Pressed 'Bake GiProbe', was surprised to see darker scene resulted than 3.2.

See before & after:
https://postimg.cc/hXPrtbJL

Expected to see similar to 3.2, did not..

**Steps to reproduce:**
Open sponza demo, press Bake for the GIProbe node.

**Minimal reproduction project:**
https://github.com/Calinou/godot-sponza

**Comment by rick551a** [comment]
Previous version (3.2.3) also same result.
Seems I never pressed 'Bake' on this demo before.
I cannot recreate the 'before' look from the using the settings available.

**Comment by UnknownS1024** [comment]
all the same darker/light need to set up GIProbe everything is fine -> https://docs.godotengine.org/en/stable/tutorials/3d/gi_probes.html

![2021-04-22_10-07](https://user-images.githubusercontent.com/17591539/115670886-95c08500-a352-11eb-88cf-ac6470a57599.png)

**Comment by Calinou** [comment]
> Pressed 'Bake GiProbe', was surprised to see darker scene resulted than 3.2.

The GIProbe bake in godot-sponza is very old – it was made back in the 3.0 days. It's likely that something has changed since then.

**Comment by rick551a** [comment]
Got it!, it seems GIProbe is not at fault, but the Directional Light needs much more 'indirect energy' than previous versions to appear the same.
Thanks for your patience.
