### ISSUE TITLE
Hold Ctrl to turn all objects/functions into links to their help files

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#4807]
I was trying to find something similar already submitted but I haven't found anything.  

So yeah

Hold Ctrl (or any other modifier key) to turn all the recognized objects or functions in the current script to links to their respective help classes. Also optionally   it should even autoscroll the help file to where the entry is located.

Additionally when hovering over recognized objects/functions it should show the help file description as a tooltip. 

Some IDEs have the ability to do this and I always found it quite useful. 

Alternatively simply tries to turn only the keyword the mouse is over rather than ALL keywords. Might be easier to implement and equally useful.

**Comment by vnen** [comment]
In IDEs I expect <kbd>Ctrl</kbd>+<kbd>LMB</kbd> to take me to the identifier's *definition*, not to its help page, so this might be a bit misleading.

Currently <kbd>Shift</kbd>+<kbd>F1</kbd> does this to an extent, as it shows the help search window.

**Comment by neikeq** [comment]
@vnen Considering a _"Go to definition"_ option is ever implemented, I don't think there would be any problem. If the class is native or the function is from a native class (and is not overridden) there will be no definition to go to, so going to the help view is fine IMO.

**Comment by trollworkout** [comment]
I can't use Shift+F1 on OSX for some reason

**Comment by trollworkout** [comment]
After I posted I realize I like the second idea I had much better than the first one. Simply press and hold Ctrl while hovering a keyword and if is a native class it goes to it's respective help file.  Seems much more elegant than turning everything into links.

**Comment by vnen** [comment]
@neikeq yeah, I see your point. It might be a good thing indeed.

**Comment by vnen** [comment]
This was implemented in 37f1e86.
