### ISSUE TITLE
The editor stops responding when opening any tab

### ISSUE THREAD

**Issue by noearaujo** [godotengine/godot#48071]
**Godot version:**
3.3 64-bit and 32-bit

**OS/device including version:**
Windows 10 64-bit, AMD Radeon 8210. GLES 2 and GLES 3

**Issue description:**
I created a clean project and in the opening of any editor's tab, the godot stops responding for all eternity and nothing else is shown in the terminal.

I also left only the Godot open on my machine and I have already cleared the RAM memory, but it is impossible to work (because with each opening of the tab or opening of any ui of the editor, the godot stops responding).

**Steps to reproduce:**
I just created a clean project. In this case, the previous version was much lighter on my machine (using GLES 2).

**Minimal reproduction project:**
pass

in editor (print)
![image](https://user-images.githubusercontent.com/37861515/115634372-e0ed8000-a2df-11eb-934b-49aaf851b9f9.png)

in terminal (print)
![image](https://user-images.githubusercontent.com/37861515/115634383-e945bb00-a2df-11eb-8896-b950e6fbeef5.png)

**Comment by noearaujo** [comment]
I had the same problem in version 3.2.3 when I removed the Display Scale from the Auto editor.

I realized that this new editor has a new scaling system that is locking on my machine.
![image](https://user-images.githubusercontent.com/37861515/115639984-4fd0d600-a2ec-11eb-85c8-bd1db0515012.png)

**Comment by akien-mga** [comment]
That's weird and probably a Windows/drivers bug, but you should be able to solve it in 3.3 by choosing the same Display Scale that "Auto" would be for your screen resolution on 3.2.3 (try 100% maybe?).

**Comment by noearaujo** [comment]
![image](https://user-images.githubusercontent.com/37861515/116005681-78075000-a5de-11eb-9658-e93175225496.png)

You are right, it was the way the video driver worked with the scaling of the display.
To solve this problem, I had to update the driver and configure it like this:
![image](https://user-images.githubusercontent.com/37861515/116005694-87869900-a5de-11eb-8e12-b5635b61ec98.png)

Thank you very much for your help ... if other people go through the same problem, this advice will help.
The editor is running lisinho lol.

**Comment by noearaujo** [comment]
An update to the driver resolves this issue. 
@akien-mga  - Thank you very much and stay with God.

**Comment by Calinou** [comment]
> You are right, it was the way the video driver worked with the scaling of the display.
To solve this problem, I had to update the driver and configure it like this:

It's very strange that changing this setting solves the issue, because this scaling setting is only used when scaling an exclusive fullscreen game run at a non-native resolution. Godot doesn't use exclusive fullscreen and it will never change your screen resolution.

**Comment by noearaujo** [comment]
@Calinou 
I don't have much experience and I went to do the tests. True, the pure driver update already solves the problem by itself.
Thank you very much for the teaching.

And changing the scale of the display no longer locks the editor. 

"Muito obrigado amigo, de hoje em diante serei um programador mais experiente. "
Deus te abençoe
