### ISSUE TITLE
Lightmapper decreasing bias 0.00051 prints an error message, despite the lowest value in code being 0.00001

### ISSUE THREAD

**Issue by UnknownS1024** [godotengine/godot#48084]
**Godot version:**
3.3 stable

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**
decreasing only to 0.00051 gives an error

 ![image](https://user-images.githubusercontent.com/17591539/115694618-b3e5af80-a369-11eb-8b63-f76c74675d19.png)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Fixed by #48324.
