### ISSUE TITLE
2.5D Demo with GDScript ERROR

### ISSUE THREAD

**Issue by StWooow** [godotengine/godot#48083]
**Godot version:**

3.3

**OS/device including version:**

Win10, PC, GLES2, Nvidia Geforce RTX2070

**Issue description:**

I just started the project and didn't do anything
![ERROR](https://user-images.githubusercontent.com/9404211/115692761-d986af00-a391-11eb-9639-cab5ce7f6214.png)

**Steps to reproduce:**
restart and reproduce

**Minimal reproduction project:**

Steam downloads Godot, the first project

**Comment by akien-mga** [comment]
This is a bug in that demo and should be reported on https://github.com/godotengine/godot-demo-projects.

But it was already fixed yesterday with https://github.com/godotengine/godot-demo-projects/pull/558.

**Comment by StWooow** [comment]
ok,the demo project from steam is old version.
there is no problem with the project downloaded from github

**Comment by akien-mga** [comment]
Yeah I just updated the demos on Steam 10 minutes ago, you should get the update soon.
