### ISSUE TITLE
An attempt to move a Container children causes `canvas_item_editor_plugin.cpp:514 - Condition "p_list.empty()" is true`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#48093]
**Godot version:**

3.3 stable

**OS/device including version:**

Linux

**Issue description:**

When I (accidentally) try to move a Container child for example Button of a HBoxContainer I get multiple
```
editor/plugins/canvas_item_editor_plugin.cpp:514 -
Condition "p_list.empty()" is true. Returned: Rect2()
```

This clutters the Output.

**Steps to reproduce:**
1. Create a scene with a container, for example `HBoxContainer`
2. Add a child to it (for example Button)
3. Try to move it in Editor (using mouse)
You will get the error (see above)

**Minimal reproduction project:**

**Comment by hilfazer** [comment]
Also in 3.2.3 stable. Windows.
