### ISSUE TITLE
Debug exports using Android custom build don't have the same certificate fingerprints as the ones in the specified debug keystore. 

### ISSUE THREAD

**Issue by oneseedfruit** [godotengine/godot#48096]
**Godot version:** 3.3

**OS/device including version:** Manjaro 21.0.2  Linux 5.10.30-1-MANJARO

**Issue description:**

When exporting to Android, if it uses custom build and it is a debug apk, it doesn't seem to get signed with the same debug keystore as specified in the editor settings as the resulting apk doesn't  have the same certificate fingerprints as the ones in the debug keystore. Setting the debug keystore in the export settings under "Keystore" doesn't change anything either. 

However, if it is a release apk and with the release keystore set in the export settings, it works fine as expected. 
If it is a debug apk but it doesn't use custom build, it works as expected too.

**Steps to reproduce:**
1. In a new project that is all set up to run a scene, go to "Project" -> "Install Android Build Template" then click "Install".
2. Go to "Editor" -> "Editor Settings", scroll all the way down to "Export" then go to "Android".
3. Specify the "Debug Keystore", "Debug Keystore User", and "Debug Keystore Pass". Then close the "Editor Settings".
3. Go to "Project" -> "Export" then add "Android". 
4. In "Export" under "Android", under "Custom Template", check "Use Custom Build".
5. Click "Export Project", then check "Export With Debug", then choose a place to save the export.
6. Use `keytool -keystore debug.keystore -list -v` and `keytool -printcert -jarfile exported_file.apk` to compare the certificate fingerprints.

**Minimal reproduction project:**

[keystore.zip](https://github.com/godotengine/godot/files/6359327/keystore.zip)

**Comment by m4gr3d** [comment]
@oneseedfruit seems you have two debug keystores in your environment, and the custom build is automatically selecting the default. This was done to simplify deployment for debug builds.

The quick fix would be to identify the other keystore and either replace it with yours or use it within Godot.

**Comment by salalex** [comment]
I have the same issue and I tried to replace `~/.android/debug.keystore` with my debug keystore, as @m4gr3d suggested, but now the custom build fails with this error
> \> com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "C:\Users\alex\\.android\debug.keystore": Keystore was tampered with, or password was incorrect

because, quite obviously, the username and password for my keystore are different from the default.

**Comment by salalex** [comment]
As a quick-and-dirty workaround, add this code to `<project_dir>/android/build/build.gradle` inside `signingConfigs {}`:

```gradle
debug {
    File keystoreFile = new File("YOUR_DEBUG_KEYSTORE_FILE_PATH")
    if (keystoreFile.isFile()) {
    storeFile keystoreFile
    storePassword "YOUR_DEBUG_KEYSTORE_PASSWORD"
    keyAlias "YOUR_DEBUG_KEYSTORE_USERNAME"
    keyPassword "YOUR_DEBUG_KEYSTORE_PASSWORD"
    }
}

```

**Comment by m4gr3d** [comment]
@salalex That's correct, the export logic is currently configured to expect the default username and password for the debug keystore.

@salalex @oneseedfruit Just so I understand the issue better, what are the usecases for setting and using a manually generated `debug.keystore` file, since you could instead use the one automatically generated by the system.

**Comment by oneseedfruit** [comment]
@m4gr3d 

When exporting a debug apk with Google Play Games integration, I won't be able sign in to Google Play Games even as a tester unless that apk has the same SHA-1 fingerprint as the OAuth 2.0 client ID I have previously added to the "Credentials" page in its Google Cloud Platform project.

Besides, why wouldn't it use the debug.keystore file manually specified in the Editor Settings, if the option of manually specifying it is right there?

**Comment by salalex** [comment]
@m4gr3d I totally agree with @oneseedfruit and I will add: why does a non-custom build use the debug keystore configured in the editor setting, while a custom build does not? 
Godot 3.2 didn't have this inconsistency.

**Comment by m4gr3d** [comment]
@salalex @oneseedfruit Thanks for the feedback! We'll resolve the issue in the next bugfix release for version 3.3.

**Comment by oneseedfruit** [comment]
@m4gr3d Awesome! Thank you for your hard work!!

**Comment by salalex** [comment]
@m4gr3d good, waiting for... Godot!
