### ISSUE TITLE
Dropdown arrow no longer uses the "open" variation when an inspector section is unfolded

### ISSUE THREAD

**Issue by TCROC** [godotengine/godot#48104]
![image](https://user-images.githubusercontent.com/24307049/115761847-c9aaa300-a370-11eb-8142-ded17b6ee4ef.png)

The > arrow should rotate to v when the component is open.

Just a small visual improvement suggestion. :)

This was originally reported here: https://github.com/GodotECS/godex/issues/146

But ported over here since it was found to be related to the Godot Editor and not Godex.

**Comment by Calinou** [comment]
@TCROC Which Godot version are you using? I remember seeing this too, but I think it's a regression from the `master` branch specifically.

**Comment by TCROC** [comment]
@Calinou I just heard back from @AndreaCatania.  Godex is based on the Godot hash: 81fc9fa1dc9162cb50e77ab5f7d7085eb3c4bc9e

**Comment by AndreaCatania** [comment]
I think this is fixed now. cc @Calinou
