### ISSUE TITLE
Failed determining lightmap size. Maximum lightmap size too small?

### ISSUE THREAD

**Issue by KoxaKoxama** [godotengine/godot#48112]
**Godot version:** 3.3 stable

**Issue description:**
Since 3.3 lightmaps are finally can be batched in atlases, this is defiantly a more efficient way to store and render them, however, why all lightmaps are combined in a **single** atlas and not into **multiply atlases** with specified resolution? How is this even possible to use it when baking an interior scene with ~20-40 static meshes in it? Combined lightmap atlas would be over 32k in resolution... and sometimes even more. Is this how it should be used? 
Currently there is no way to use it properly as Godot will almost always give an error "Failed determining lightmap size. Maximum lightmap size too small?"
Maybe I don't understand something, but how exactly should I handle baking lightmaps in atlases with a relatively large interior scene? Or I should completely avoid generating atlas and stick to ginormous amount of small lightmap maps?

**Comment by Calinou** [comment]
@KoxaKoxama Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by JFonS** [comment]
By default, the BakedLighmap node sets the maximum atlas size to 4096, that means it will try to arrange all the meshes in 4096x4096 pages and then combine those into a single texture array. If any of the meshes in the scene doesn't fit in a single page it will report the "Maximum size too small" error. 

Do you have a large mesh in your scene? If that's the case you can try increasing the `Atlas > Max Size` property in the `BakedLightmap` node or splitting any large mesh into a couple of smaller ones. You can also take  alook at the 

Baking into multiple atlasses is interesting, but it would make the internal systems more complex, so it needs to be evaluated.

**Comment by twocountriestrus** [comment]
Gracias 


Enviado desde Yahoo Mail para iPhone


El viernes, abril 23, 2021, 10:39 a. m., KoxaKoxama ***@***.***> escribió:




Closed #48112.

**Comment by twocountriestrus** [comment]
Gracias 


Enviado desde Yahoo Mail para iPhone


El viernes, abril 23, 2021, 10:43 a. m., Dairon Padron ***@***.***> escribió:

Gracias 


Enviado desde Yahoo Mail para iPhone


El viernes, abril 23, 2021, 10:39 a. m., KoxaKoxama ***@***.***> escribió:




Closed #48112.

**Comment by twocountriestrus** [comment]
Gracias 


Enviado desde Yahoo Mail para iPhone


El viernes, abril 23, 2021, 10:44 a. m., Dairon Padron ***@***.***> escribió:

Gracias 


Enviado desde Yahoo Mail para iPhone


El viernes, abril 23, 2021, 10:43 a. m., Dairon Padron ***@***.***> escribió:

Gracias 


Enviado desde Yahoo Mail para iPhone


El viernes, abril 23, 2021, 10:39 a. m., KoxaKoxama ***@***.***> escribió:




Closed #48112.

**Comment by KoxaKoxama** [comment]
Unfortunately there is no solution because this is not an issue. It appears that this is how it was designed and the only way around it is to increase atlas max size to insane value or split mesh into smaller pieces before bake.

**Comment by NHodgesVFX** [comment]
Thiers a proposal for it https://github.com/godotengine/godot-proposals/issues/2147
