### ISSUE TITLE
Display user friendly error when running an HTML5 Threads export without SharedArrayBuffers

### ISSUE THREAD

**Issue by cloewen8** [godotengine/godot#48110]
**Godot version:**

3.3

**OS/device including version:**

Windows 10 20h2 (build 19042.928)
Firefox 88

**Issue description:**

When launching a game using the HTML5 template with the Threads export type in an environment without SharedArrayBuffers, an uncaught error occurs and loading halts.

I tracked the error to this statement in index.js: `if(!(wasmMemory.buffer instanceof SharedArrayBuffer)){err("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag");`

I am aware I can't use threads without SharedArrayBuffers. At a bare minimum, Godot shouldn't load and display a proper error message in the console. Optimally, the game should still run without threads. I'd love to contribute a fix, I'm just not sure where this line is or how it is generated (if anyone knows, please tell me).

**Steps to reproduce:**
This should occur with any HTML5 export using the Threads export type in a browser that does not provide the SharedArrayBuffer.

1. Create any web-compatible game (a game with a single scene).
2. Start a static web server (I used `python -m http.server`).
3. Start in Firefox (Firefox supports SharedArrayBuffers, but requires additional cross-origin isolation headers).

Additionally, this should be reproducible with:

- IE
- Chrome 91+ (without additional headers)
- Safari

**Minimal reproduction project:**

[HTML5ThreadsBug.zip](https://github.com/godotengine/godot/files/6360935/HTML5ThreadsBug.zip)

**Comment by Faless** [comment]
> Optimally, the game should still run without threads. I'd love to contribute a fix, I'm just not sure where this line is or how it is generated (if anyone knows, please tell me).

This would require shipping 2 different versions of Godot (and potentially of your pck too): one with threads, one without.
We could add SAB check and display a warning like for WebGL.

**Comment by Calinou** [comment]
I have a PR that aims to address a similar issue, but it should be redone to use feature detection instead: https://github.com/godotengine/godot/pull/47925
