### ISSUE TITLE
Bug when using clear() function on Arrays

### ISSUE THREAD

**Issue by martinpelli** [godotengine/godot#48117]
**Godot version:**
Godot 3.3

**Issue description:**
Clear function makes parameters pass by reference???

**Steps to reproduce:**
make a singleton called global

Anywhere (not in singleton) just copy and paste this script:
```
var my_local_var = [1,2,3]
global.my_global_var = my_local_var
my_local_var = []
print(global.my_global_var)
```
this will print([1,2,3]) which is OK.
but if you do:

```
var my_local_var = [1,2,3]
global.my_global_var = my_local_var
my_local_var.clear()
print(global.my_global_var)
```
this will print([]) which should print [1,2,3]

also If you add this single line:

```
var my_local_var = [1,2,3]
global.my_global_var = my_local_var
my_local_var.clear()
my_local_var = [1,2,3,4,5]
print(global.my_global_var)
```
this will print([1,2,3,4,5]) which should print [1,2,3]
**Minimal reproduction project:**
not needed, just copy the code avobe, and add a singleton called global whit a variable.

**Comment by volzhs** [comment]
```gdscript
var my_local_var = [1,2,3]

# global and local variable point same array by reference
global.my_global_var = my_local_var 

# it's same with my_local_var = Array()
# so this will create a new array for local variable so that global and local variable point different array
my_local_var = []

# this will clear the array which is pointed by global and local
my_local_var.clear() 
```

and testing below code prints `[]` not `[1,2,3,4,5]`
```gdscript
var my_local_var = [1,2,3]
global.my_global_var = my_local_var
my_local_var.clear()
my_local_var = [1,2,3,4,5]
print(global.my_global_var)
```

**Comment by martinpelli** [comment]
@volzhs oh, so It´s okay that clear function changes the global value?

**Comment by volzhs** [comment]
it's just simple.
if you want to keep the reference of array, use `clear()` instead of creating a new one.

**Comment by timothyqiu** [comment]
> how do you know that a clear() works by reference?

It's not `clear()` that works by reference, "Arrays are always passed by reference" ([doc](https://docs.godotengine.org/en/stable/classes/class_array.html#description)).

It might be easier to think variables and objects separately:

* `global.my_global_var = my_local_var` makes the two variables to reference the same array object
* `my_local_var.clear()` makes the array object empty
* `my_local_var = []` makes the variable to reference a new empty array object

**Comment by akien-mga** [comment]
Closing as this is already covered in the documentation. (Though suggestions welcome if it could be made clearer.)
