### ISSUE TITLE
Android export not finding apksigner

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [godotengine/godot#48111]
**Godot version:**
3.3 (custom built for the rpi4)

**OS/device:**
raspberry pi os on a raspberry pi 4

**Issue description:**
Im trying to export an android apk, but for some reason godot 3.3 will not find the apksigner, all the settings are the same in godot 3.2.3 and it works fine there, here are a few pitures to show how i have things set up.

This is the error in the export window:
![2021-04-22-133949_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/115783217-6ff6a880-a371-11eb-9886-5dce55a8f0b7.png)

This is the android export editro setting and the files manager showing the files and paths that they point to(note the apksigner.jar file that godot will for some reason not find):
![2021-04-22-134119_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/115783261-800e8800-a371-11eb-9e73-5ad3af5e8841.png)

**Comment by Calinou** [comment]
The Adb and Jarsigner settings are not used anymore, only the **Android Sdk Path** setting is.

**Comment by The-Sapphire-Starship** [comment]
> The **Adb** and **Jarsigner** settings are not used anymore, only the **Android Sdk Path** setting is. If you upgraded from 3.2.3, the old settings will still be listed because of #22099.

okay, but if i remove those paths it still cannot find the jarsigner for some reason
![2021-04-22-141630_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/115786426-a7675400-a375-11eb-898a-3df265f945e6.png)
![2021-04-22-141833_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/115786428-a7ffea80-a375-11eb-9f70-31fd2c0fdf67.png)

**Comment by akien-mga** [comment]
How did you install the Android SDK?

Distro provided Android SDKs are outdated and not supported, as documented here: https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html

![Screenshot_20210423_111236](https://user-images.githubusercontent.com/4701338/115849092-d688ce80-a424-11eb-9b8d-50b86caf054d.png)

**Comment by The-Sapphire-Starship** [comment]
> How did you install the Android SDK?
> 
> Distro provided Android SDKs are outdated and not supported, as documented here: https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html
> 
> ![Screenshot_20210423_111236](https://user-images.githubusercontent.com/4701338/115849092-d688ce80-a424-11eb-9b8d-50b86caf054d.png)
> 
> You should have Android build-tools 30.0.1, but you have 27.0.1 (that's from 2017).

Do you know how i can get the newer version on my rpi?

**Comment by akien-mga** [comment]
I'm not sure that's possible easily as the upstream Android SDK is only distributed for x86_64 Linux.

You could try to add Debian Sid repos to your Raspberry Pi OS though to get build-tools 29.0.3, that might be recent enough: https://packages.debian.org/sid/android-sdk-build-tools
