### ISSUE TITLE
Control+Click on `Array` `min()`/`max()` opens `@GDScript` `min()`/`max()` docs

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#48113]
**Godot version:**

3.3 stable

**OS/device including version:**

Linux

**Issue description:**

https://user-images.githubusercontent.com/16458555/115786164-e202d800-a3d9-11eb-8589-b020b6500f04.mp4

**Steps to reproduce:**
1. Create a script in Godot script editor, with code like:
```gdscript
func _ready():
	[0,1].max()
```
2. Hover the mouse on `max()` then press `Control+Mouse Click`
As you can see, wrong docs are opened: `@Gdscript max()`  instead of `Array.max()`; same for `min()`

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
This is the same as #47692
Already fixed on master.
