### ISSUE TITLE
Rigidbody2D jitters on FPS drops

### ISSUE THREAD

**Issue by ural89** [godotengine/godot#48128]
Godot version: 3.3

Platforms: MacOS, Android

Issue description:
Hello there. I'm making a racing game. Player car and other cars are Rigidbody2D type objects. Gameplay is very smooth at 60 FPS. But sometimes even a little drop in FPS(50-55) causes rigidbodies to jitter. How do I fix that (except keep fps at 60. Because it will be a mobile game and maybe not everyone able to play it on 60 FPS). I tried both versiyon 3.2.3 and 3.3
Physics jitter fix: 0.5
Code looks something like this (I can send more detailed if needed):

```
func _physics_process(delta):
    if speed>speed_limit:           
            thrust = Vector2(0, 0)
    else:
            thrust = Vector2(engine_power, 0)
    set_applied_force(thrust.rotated(rotation))


```
Steps to reproduce:
Set your project FPS limit to 50. Set physics FPS to 60. Apply force to a Rigidbody2D. You will see object jitters.

*Bugsquad edit: For reference, this was cross-posted on Godot forums: https://godotforums.org/discussion/26109/rigidbody2d-jitters-on-fps-drops*

**Comment by Zireael07** [comment]
See https://docs.godotengine.org/en/stable/tutorials/misc/jitter_stutter.html and this addon: https://github.com/lawnjelly/smoothing-addon

**Comment by ural89** [comment]
> See https://docs.godotengine.org/en/stable/tutorials/misc/jitter_stutter.html and this addon: https://github.com/lawnjelly/smoothing-addon
it only works if physics FPS is lower than screen FPS.

**Comment by Calinou** [comment]
> it only works if physics FPS is lower than screen FPS.

The smoothing add-on can still do its job even if the physics FPS is equal to rendering FPS.

**Comment by ural89** [comment]
> > it only works if physics FPS is lower than screen FPS.
> 
> The smoothing add-on can still do its job even if the physics FPS is equal to rendering FPS.
> 
> Out of curiosity, are you using a Camera2D node with smoothing enabled? Try changing its update mode to **Process** instead of **Idle**.
Yes I have camera2D node smoothing on. It follows player car. I disabled it and changed mode to process. This time both camera and rigidbody jitters together (road jitters relatively).

**Comment by Calinou** [comment]
This should be resolved with the addition of [fixed timestep interpolation](https://github.com/godotengine/godot/pull/52846). It's currently only available in 3D, but it'll be ported to 2D eventually (after 3.5 is released).

**Comment by Calinou** [comment]
Closing per the above comment.
