### ISSUE TITLE
Batch-exporting projects from the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4813]
It would be very nice to have something that lets you export for several platforms and architectures at once; this could speed up the project release process considerably, without relying on platform-specific command lines. It could be part of the Export dialog (with an additional "Batch Export" tab) and look like a list of checkboxes like this:

---
- [ ] Windows
  - [ ] Windows 64-bit
  - [ ] Windows 32-bit
- [ ] Linux
  - [ ] Linux 64-bit
  - [ ] Linux 32-bit
- …

---

Ticking the checkbox next to the operating system would enable it for all architectures at once, but the user could also choose to export for one architecture only.

There would probably be a global CheckButton for toggling debugging on all the exports. The naming scheme would probably follow the default SCons one, ideally it would be customizable as well.

**Comment by reduz** [comment]
You can already do this by using the commandline, it's not very well
documented though. Ask punto how it works

**Comment by vnen** [comment]
:+1: I was thinking of this very thing today.

@reduz (or @punto-) can we do actual batch export from command line or it just enable us to make a script with every export command?

**Comment by bojidar-bg** [comment]
There is a new exporter, was this done for it?

**Comment by Calinou** [comment]
> There is a new exporter, was this done for it?

The new exporter has improved CLI functionality which allows for easy batch exporting using export presets defined in the project. Batch exporting isn't possible using *only* the GUI currently, but I think CLI batch exporting is enough for now.

Feel free to open another issue if you have a proposal for a GUI batch exporting option. :smiley:
