### ISSUE TITLE
Error in the output when moving a control node (German translation bug)

### ISSUE THREAD

**Issue by Ohri1234** [godotengine/godot#48134]
To see the error in the output, all you have to do is change the position of the control node using the mouse. Then an error is thrown in the output.

My OS:
Windows 10 Professionell, version 20H2
System type: 64Bit
Processor: AMD Ryzen 5 2600 Six-Core Processor  3.40 GHz
16 GB installed RAM
SSD (528GB)
HDD (1TB)
GPU: GeForce GTX 1650 Super

Screenshot:
![2021-04-23 18_39_52-Xbox Console Companion](https://user-images.githubusercontent.com/78663912/115902994-5897e800-a463-11eb-98ba-34e5daecc749.png)

Godot version:
3.3 stable

Issue description:
It happened in other projects too. It gaves me the error: "unsupported format character" when I moved the Control-Node.

Steps to reproduce:
1. Create a new Scene.
2. Select 2D Scene as Root-Node.
3. Add a Control-Node or a Control-based Node to the Scene.
4. Drag the Node. In the output appears the error.

Project the reproduce:
[project.zip](https://github.com/godotengine/godot/files/6366750/project.zip)

**Comment by LightningAA** [comment]
It gave me no errors

**Comment by Calinou** [comment]
This is likely because the 2D undo/redo log translation messages haven't been updated to use the new percent-formatted strings.

**Comment by RedMser** [comment]
Randomly found this issue and try to repro in 3.5 and 4.3. It appears to be fixed in both versions.

**Comment by Calinou** [comment]
Closing per the above comment.
