### ISSUE TITLE
Null Check on a Deleted Object No Longer Works

### ISSUE THREAD

**Issue by BHSDuncan** [godotengine/godot#48147]
**Godot version:**

3.3

**OS/device including version:**

Windows 10.0.19042

**Issue description:**

A null check on a deleted object doesn't work, e.g. `if the_variable == null:` and `the_variable` is a deleted object, the block contained within that `if` statement will not execute.

The same incorrect behaviour happens with a statement in the form of, `if not the_variable:`

I expect that check to succeed and I have verified that it does succeed in Godot 3.2.3.

I notice that, in the debugger, it says something along the lines of:

`Invalid get index 'method_name_here' (on base: 'null instance').`

But printing out the object, in the output area I get `[Deleted Object]`

I have noticed that the following code does work (with respect to a null object as opposed to a deleted object):

```
var the_variable = null

if not the_variable:  # if the_variable == null: also works
  print("NOT NULL")
```

...and "NOT NULL" will be successfully printed out.

If this is no longer the correct way to check for deleted objects, I'd like to know what the proper way now is.

**Steps to reproduce:**
I'm unsure of how exactly to do this outside of a current project of mine, as I can at least reproduce it at will there.

However, the bug happens in a method that is called by a function that's called as part of a `_physics_process(delta)` call.

**Minimal reproduction project:**

Unsure of how to create such a project as `queue_free()` would only queue an object/node for deletion and the object in question is already deleted.

If I can provide any additional information, please let me know and I'll do my best.

**Comment by felaugmar** [comment]
This is intended, you can use `is_instance_valid` for null checks.

**Comment by BHSDuncan** [comment]
Got it. Confirmed it for myself that it works as you said.

Also did a bit more digging into the changelog and release notes for 3.3 and found the related parts.

Thanks for the prompt reply! Loving the 3.3 experience!
