### ISSUE TITLE
CSGPolygon added at runtime will not render if set to Path mode.

### ISSUE THREAD

**Issue by Armadon7** [godotengine/godot#48140]
**Godot version:**

3.3

**OS/device including version:**

Mint 19.3 Cinnamon OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2

**Issue description:**

I’m adding a CSGPolygon to a scene via script. It looks to render correctly if set to depth or spin. It will not render though if it’s set to path and set_path_node() is pointed to a path node that’s already in the scene tree. set_path_node() works as expected on a CSGPolygon already in the scene tree with no issues.  

If the same scene is run in Godot 3.2.3 it'll throw the error _update_shape: Cannot get CSGBrush 

**Steps to reproduce:**
Add a CSGPolygon to a scene via script, set to path, and set its path node.

**Minimal reproduction project:**

[CSGPolygon not showing.zip](https://github.com/godotengine/godot/files/6367658/CSGPolygon.not.showing.zip)

**Comment by Calinou** [comment]
cc @madmiraal

**Comment by madmiraal** [comment]
This is not a bug. In the example provided, the path used in `set_path_node()` doesn't point to the `Path` object. The `CSGPolygon` object created in the script is added as a child of the `Spatial` object. Therefore, the `Path` needs to be set to `"../../OldPath"` not `"../OldPath"`.
