### ISSUE TITLE
Error upon de-indent

### ISSUE THREAD

**Issue by dranorter** [godotengine/godot#48163]
**Godot version:**
Experienced on 3.3, as well as 3.3.rc9.

**OS/device including version:**
Windows 10

**Issue description:**
I experience the following error when de-indenting specific areas of text via `shift + tab`:
```
ERROR: _base_get_text: Index p_from_column = 33 is out of bounds (text[p_from_line].length() + 1 = 33).
   At: scene/gui/text_edit.cpp:4056
ERROR: _base_get_text: Index p_from_column = 33 is out of bounds (text[p_from_line].length() + 1 = 33).
   At: scene/gui/text_edit.cpp:4056
ERROR: _base_get_text: Index p_from_column = 33 is out of bounds (text[p_from_line].length() + 1 = 33).
   At: scene/gui/text_edit.cpp:4056
ERROR: _base_get_text: Index p_from_column = 33 is out of bounds (text[p_from_line].length() + 1 = 33).
   At: scene/gui/text_edit.cpp:4056
ERROR: _base_get_text: Index p_from_column = 33 is out of bounds (text[p_from_line].length() + 1 = 33).
   At: scene/gui/text_edit.cpp:4056
ERROR: _base_get_text: Index p_from_column = 33 is out of bounds (text[p_from_line].length() + 1 = 33).
   At: scene/gui/text_edit.cpp:4056
```

Once I have de-indented, the error is printed about once per second, possibly when the text cursor itself blinks. I can cause it to print more frequently by scrolling up and down the page with my mouse's scroll wheel. The message stops printing when I deselect the text or undo the de-indentation with `ctrl+z`.

While experimenting with this, one project froze up entirely; however, I have not been able to reproduce that aspect of the error, as I lost the exact code and project state I was working with.

**Steps to reproduce:**

Start with some error-free code. Select several lines of text to de-indent. For the error to occur:

- The selection must start at the end of a line.
- The starting line must be indented.
- The final line selected must be a comment.
- The commented line must begin with "#", with no whitespace before.
- The comment must contain whitespace immediately after the "#". Either a space or a tab will suffice.

Then simply press `shift + tab`.

In order to reproduce the error, it does not matter whether the cursor lies at the beginning of the selection or the end when you press `shift + tab`. It also doesn't matter where the selection ends within the final, commented line. It also doesn't matter whether the de-indentation produces valid code, or triggers a syntax error.

I experience this issue with both GDScript, and using godot-python. I have not tested other languages.

**Minimal reproduction project:**
The GDScript template itself suffices:
```
extends Spatial


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Selection should start at end of this line >


# Selection should end anywhere in this line. Then press shift + tab
#func _process(delta):
#	pass
```

**Comment by KoalasinTraffic** [comment]
I believe this is due to start_line selection not being updated. It should be fixed by adding the same updates as done with end_line.

I'm new, so double check for me.
