### ISSUE TITLE
Imported materials are not colour corrected

### ISSUE THREAD

**Issue by thirite** [godotengine/godot#4816]
**Operating system or device - Godot version:**
Godot 2.0.3 Stable

**Issue description** (what happened, and what was expected):
When you import a 3D scene containing a mesh with a material applied to it, the saturation of that material will not be right on import (seemingly always waaay too saturated)

**Steps to reproduce:**
Import a 3D scene with a material with low saturation, observe the result.

**Link to minimal example project**
You can simply export this blend file and import it into Godot. In blender you'll notice the side using textures is almost perfectly identical to the side using solid materials, but upon importing into Godot, the solid material side is far more saturated than the texture coloured side. 

https://drive.google.com/file/d/0BxAUmolQ9DxLM0dsREwxUTg4V0k/view?usp=drivesdk

**Comment by thirite** [comment]
After some more testing, I notice that the RGB values for the material seem to stay the same between Blender and Godot but the hex values are different. And if you set the hex value in Godot to what it is in blender, it looks fine.

Not sure what it means but hopefully it will help.

**Comment by bojidar-bg** [comment]
Maybe something to do with sRGB conversion?

**Comment by Ovnuniarchos** [comment]
Could be Blender's color correction. If you set Scene->Color Management->Display Device to None, is this how it looks in Godot?

**Comment by thirite** [comment]
@Ovnuniarchos
Yeah, when I do that it looks just like it does it Godot.

**Comment by Ovnuniarchos** [comment]
Then it's a matter of Blender doing color correction while Godot does not. I think it's better to set the CC in Blender to None while modeling for Godot.

**Comment by reduz** [comment]
whole 3D engine changed, and it now always renders in linear space, so this can be closed.
