### ISSUE TITLE
Cannot make headless build on macOS unless passing `use_static_cpp=no` to the SCons command line

### ISSUE THREAD

**Issue by huskeee** [godotengine/godot#48161]
**Godot version:** 3.3

**OS/device including version:** macOS 10.15.7 running on OSX-KVM

**Issue description:**

I've been trying to make a headless build on macOS. Downloaded the 3.3 source code archive and ran `scons platform=server tools=yes target=release_debug --jobs=8`. It compiles most of the files successfully but when it starts linking, the build fails with the error `unsupported option '-static-libgcc'`.

**Steps to reproduce:**
1. Download latest stable source code (v3.3)
2. Try to make a headless build

**Comment by Calinou** [comment]
As a workaround, pass `use_static_cpp=no` to the SCons command line.

**Comment by akien-mga** [comment]
It's better to fix the bug than to document it :)

**Comment by akien-mga** [comment]
Fixed by #57593.
