### ISSUE TITLE
WebXR problem. Browser.pauseAsyncCallbacks is not a function

### ISSUE THREAD

**Issue by MikhailMartianov** [godotengine/godot#48178]
**Godot version:**
Godot_v3.3-stable_win64

**OS/device including version:**
HTML5, GLES2, Chrome and firefox (Tested only in them (it seems to me this error will be in any browser)
I am the owner of quest 2, so only that was used in the test.

**Issue description:**
When running the VR example, the developer console in the browser shows the error "Browser.pauseAsyncCallbacks is not a function". This happens when you press the "switch to VR mode". If you build through v3.2.4.beta.custom_build.dca9f0938, then there is no such error.
I tested via oculus link and in browser inside quest 2.

I examined the js source code that is generated when exporting to html5 and saw that the call to Browser.pauseAsyncCallbacks appeared only from version 3.3, it was not there before, so there was no error. Manually removing the call to this nonexistent function helped and everything started working as it should, but this trick is very insecure.

**Steps to reproduce:**
Repeat the code from the example in your project and try to run.
https://docs.godotengine.org/en/3.3/classes/class_webxrinterface.html

**Minimal reproduction project:**
Made an example where this error occurs
[example.zip](https://github.com/godotengine/godot/files/6371800/example.zip)

**Comment by dsnopek** [comment]
I'm able to reproduce this issue. :-(

`Browser.pauseAsyncCallbacks()` is an emscripten function. Perhaps there was an update to the emscripten version used to build the HTML5 export templates that removed it? Unfortunately, I hadn't tested the last few RC's, so I'm not sure exactly when this would have broken... But I'll look into it!

**Comment by dsnopek** [comment]
@Faless @akien-mga What version of Emscripten was used to build the HTML5 export templates for Godot 3.3? It looks like `Browser.pauseAsyncCallbacks()` was removed in 2.0.13. Anyway, I'd like to test locally using the same version as was/will be used for the official builds.

**Comment by akien-mga** [comment]
Official builds use 2.0.15 currently:
https://github.com/godotengine/build-containers/blob/945940756f90c967bd482e0b9ffc3db74bfada40/Dockerfile.javascript#L6-L7

This was updated from 2.0.11 on March 23: https://github.com/godotengine/build-containers/commit/f8aed4f23a64cd9a31080fcb45d47068c0f2cbb3

**Comment by dsnopek** [comment]
Ok, thanks!

> This was updated from 2.0.11 on March 27: godotengine/build-containers@f8aed4f

Gah, I really should have tested those last few RCs! I was just really busy with getting that Steam release out. Sorry!

**Comment by Faless** [comment]
> Gah, I really should have tested those last few RCs!

It's alright, emscripten is just a mess, breaking compatibility every other version, without even mentioning it in the changelog.
I really hope we can ditch it at some point.

**Comment by dsnopek** [comment]
I created a PR that fixes this in my testing: #48268

@akien-mga Is it possible to update the HTML5 export templates for Godot 3.3 without making a new release? It's just unfortunate that WebXR support was added in 3.3, but actually doesn't work because of this issue. This issue probably also means that WebXR doesn't work in the 3.3 version of the web editor (it did in earlier RCs), but other than the novelty of it, I don't know that anyone would actually use that for a real WebXR project.

**Comment by akien-mga** [comment]
>  Is it possible to update the HTML5 export templates for Godot 3.3 without making a new release?

It's possible but it creates a messy situation as we can't force update templates for people who have installed them already. I prefer making a 3.3.1-stable release soon with the initial batch of fixes to 3.3 (Linux 32-bit templates are also broken in 3.3 for example when using an old distro).

**Comment by dsnopek** [comment]
Ok, sounds good!

**Comment by dsnopek** [comment]
Just tested with 3.3.1-rc2 - all still seems to work! :-)
