### ISSUE TITLE
Loading theme is very slow

### ISSUE THREAD

**Issue by kakatoto-collab** [godotengine/godot#48171]
**Godot version:**
3.3

**OS/device including version:**
Windows, GLES2

**Issue description:**
I experience some severe lags when accessing to the theme pannel in Godot 3.3. It takes something like 8 seconds with Godot 3.3 here... When I switch back to Godot 3.23, it is fine...

**Steps to reproduce:**
Load theme pannel.

**Minimal reproduction project:**
I was not able to produce a minimal Godot project that reproduces the issue.

**Comment by Dovava** [comment]
I'm afraid that due to the lack of a reproduction project and that I tried opening the theme panel with no problems your problem cannot be fixed.

**Comment by pycbouh** [comment]
As mentioned, this is the case where we would need an example of what you are trying to load. Otherwise we cannot test your specific issue, even if we attempt to resolve it like that.

**Comment by lawnjelly** [comment]
Do you mean you encounter lag when interacting with the panel, or just when it first loads? And as the others say, is there anything special you are loading in the theme panel (font maybe?), or is this a fresh project?

**Comment by kakatoto-collab** [comment]
Any load is very slow. I mean the first is slow, then if I close the theme pannel and open it again it is very slow again. There is custom font indeed and some styleboxes also. It is not a fresh project. AS I said I dont experience this bug on this project when I open it with Godot 3.2.3. It appears only with Gododt 3.3.

**Comment by pycbouh** [comment]
Well, if you take your theme resource and open it in a new project, does the editor still lag? Can you share your theme resource?

**Comment by kakatoto-collab** [comment]
When I Open my theme ressource in a new projet the lag is not there anymore. I dont know how to share the theme ressource with its dependancies ? (font, images...)

**Comment by Xrayez** [comment]
You can go the other approach: make a new project and start replicating the theme resource as in your main project, until you get to reproduce the lag.

**Comment by kakatoto-collab** [comment]
Yes but it will not lag (see my previous post).

**Comment by Xrayez** [comment]
You said that you don't know how to share the theme resource with dependencies such as images. If you already replicated the resource with all dependencies as in your main project, then it means it's not actually the issue with theme resource. Do you have plugins installed in your main project?

**Comment by kakatoto-collab** [comment]
Yes it is probably not due to the theme resources. No I dont have plugin in this project.

**Comment by kakatoto-collab** [comment]
Hi again,

Removing project folder from Roaming\Godot\projects fixed the problem for me.

**Comment by Whimfoome** [comment]
Today I experienced the same issue with cli build for Godot 4.0.

To produce it, in the theme editor click Create Theme->From Current Editor Theme, and now every time I access a node that expands the Theme Editor menu, my editor freezes for ~10s.

**Comment by pycbouh** [comment]
> Today I experienced the same issue with cli build for Godot 4.0.
> 
> To produce it, in the theme editor click Create Theme->From Current Editor Theme, and now every time I access a node that expands the Theme Editor menu, my editor freezes for ~10s.

That's not new. That theme is huge, and contains all the images used by the editor.

**Comment by greatmomo** [comment]
Does that mean this is a non-issue? Or can something be done to reduce the size of that theme?

**Comment by pycbouh** [comment]
> Does that mean this is a non-issue? Or can something be done to reduce the size of that theme?

With the editor theme, or even a full copy of the default theme, there is not much that can be done. It may be possible to help the load time a bit if the images for icons and other elements weren't bundled and were stored in their own files instead. But at some point it's just a matter of opening, loading and parsing a lot of data at the same time.

Note that in master specifically the time to open a theme is very very slow for unrelated reasons.

**Comment by Calinou** [comment]
@kakatoto-collab Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
