### ISSUE TITLE
PRIMITIVE_ constants should be removed from Mesh (they are in VisualServer already)

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#4817]
PRIMITIVE_ constants should be removed from Mesh since they seem to already exist in VisualServer which has all the opengl constants

**Comment by bojidar-bg** [comment]
:-1: I would prefer to write:
```gdscript
Mesh.add_surface(Mesh.PRIMITIVE_TRIANGLE_STRIP, Mesh.ARRAY_FORMAT_VERTEX)
```
Instead of:
```gdscript
Mesh.add_surface(VisualServer.PRIMITIVE_TRIANGLE_STRIP, VisualServer.ARRAY_FORMAT_VERTEX)
```

**Comment by trollworkout** [comment]
@bojidar-bg  

```
var surface = SurfaceTool.new()
surface.begin(Mesh.PRIMITIVE_TRIANGLE_STRIP)
```

Is kinda random that Mesh has them defined but SurfaceTool does not.

So you mean to say your main reason is that Mesh is 8 characters shorter than VirtualServer? :D

**Comment by slapin** [comment]
Yeah, VisualServer is too long for lazy person like me and Godot doesn't support python-style namespace imports...

**Comment by slapin** [comment]
But braking compatibility in 3D is OK, as we're supposed to pretend it doesn't exist now, as "everything will be rewritten", so breaking scripts is unavoidable anyway.

**Comment by reduz** [comment]
no, most users don't even need to know that VisualServer exists, so having this replicated makes it easier.
