### ISSUE TITLE
All 256 animation clips are always imported, even if empty (`.import`) (gltf)

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#48189]
**Godot version:**
3.3

**OS/device including version:**
Windows 10 (19042.928), GLES 3

**Issue description:**
Godot always adds 256 animation tracks to `.import` file (gltf), even if they are all empty. (File was exported with animations enabled from Blender). Each of those entries look like this:
```
animation/clip_x/name=""
animation/clip_x/start_frame=0
animation/clip_x/end_frame=0
```
It bloats the import file in this specific case with 768 lines and adds 30601 Bytes of unneeded data. You can remove those 768 lines and nothing bad happens.

**Steps to reproduce:**
1. Reimport `cube.glb` (or don't because it is imported)
2. Open `cube.glb.import` (or take a look at the required disk space)

**Minimal reproduction project:**

[Animation Import.zip](https://github.com/godotengine/godot/files/6372249/Animation.Import.zip)

**Comment by aaronfranke** [comment]
This does not occur in Godot 4.0 and later, only 3.x. As for fixing this in 3.x, it's a minor issue, and it's better to not change the behavior in 3.x which is supposed to be stable. Closing as fixed.
