### ISSUE TITLE
Some collisions are not working on 3.3

### ISSUE THREAD

**Issue by titangamingglt** [godotengine/godot#48184]
**Godot version:**
3.3

**OS/device including version:**

**Issue description:**

After updating Godot to 3.3 some collisions are not working which is working on 3.2.2. The collision that is not working is between two kinematics nodes. it effects both collision and disabling collision layer. (A Player and a Platform. It suppose to land and also pass through by disabling the collision layer)

**Steps to reproduce:**
It is for one of my project

**Minimal reproduction project:**
The file is too large to share

**Comment by akien-mga** [comment]
We can't do anything without steps to reproduce or test project.

**Comment by titangamingglt** [comment]
`if is_on_floor():
		jump_count=0
		if velocity.y>0:
			velocity.y=5
		if Input.is_action_just_pressed("ui_down") :
			$jump_through.play()
			set_collision_mask_bit(DROP_THRGH,false)
			set_collision_layer_bit(DROP_THRGH,false)
		animaton.play("running")
	elif not is_on_floor():
		set_collision_mask_bit(DROP_THRGH,true)
		set_collision_layer_bit(DROP_THRGH,true)
		animaton.play("Jumping") #Normal Jump action`
this is a small portion that helps the player to jump below/ meaning come down from a upper platform to a lower one. It is working fine in 3.2.2 but in 3.3 its not working

**Comment by Xrayez** [comment]
@titangamingglt I formatted your code to be easier to read.

Does it also work in 3.2.3? Maybe related to changes such as #39400.

**Comment by titangamingglt** [comment]
> 
> 
> @titangamingglt I formatted your code to be easier to read.
> 
> Does it also work in 3.2.3? Maybe related to changes such as #39400.

yes it also works on 3.2.3

**Comment by pouleyKetchoupp** [comment]
@titangamingglt Is it in 2D or 3D? It's going to be difficult to investigate without more information about your setup. The ideal would be to provide a minimum scene extracted from your project with just bodies and collision shapes.

**Comment by pouleyKetchoupp** [comment]
Closing for now, feel free to re-open when you can provide a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project).
