### ISSUE TITLE
Inconsistent timeout unit in `NetSocketPosix::poll`

### ISSUE THREAD

**Issue by MmAaXx500** [godotengine/godot#48195]
**Godot version:** Any

**OS/device including version:** Windows and Linux

**Issue description:**

Timeout unit is inconsistent in [`NetSocketPosix::poll`](https://github.com/godotengine/godot/blob/15a85fe9713668f8ba6143352fd27d419a96ba83/drivers/unix/net_socket_posix.cpp#L437).

For example if we input `1000` in `p_timeout` parameter.
On Windows we place this value in a [`timeval`](https://docs.microsoft.com/en-us/windows/win32/api/winsock/ns-winsock-timeval) struct in this way:
https://github.com/godotengine/godot/blob/15a85fe9713668f8ba6143352fd27d419a96ba83/drivers/unix/net_socket_posix.cpp#L449 witch means `1000` `seconds` and `0` `microseconds`.

On Linux we put the parameter directly into [`poll`](https://man7.org/linux/man-pages/man2/poll.2.html) which takes the timeout in `milliseconds`: 
https://github.com/godotengine/godot/blob/15a85fe9713668f8ba6143352fd27d419a96ba83/drivers/unix/net_socket_posix.cpp#L510

At the end we waited `1000` `milliseconds` on Linux and `1000` `seconds` on Windows which obviously not equal.

p.s.: I'm happily submitting a pr if we decided on the desired unit

**Steps to reproduce:** n/a

**Minimal reproduction project:** n/a

**Comment by Calinou** [comment]
cc @Faless 

I think microseconds would be better here as they are more granular. Just make sure the documentation is up-to-date on this.
