### ISSUE TITLE
`BaseButton's Enabled Focus Mode` warning during duplicate() call

### ISSUE THREAD

**Issue by AlexTheRegent** [godotengine/godot#48199]
**Godot version:**

Godot_v3.3-stable_win64

**Issue description:**

When duplicating Button or any Node that have Button as child in GDScript editor throws next warning:
`BaseButton's Enabled Focus Mode property has been deprecated due to redundancy and will be removed in Godot 4.0. Please use Control.set_focus_mode instead.`
This warning is thrown regardless of `focus_mode` value. If button has modified 'enabled_focus_mode`, then this warning will be thrown once during launch (this is expected behavior). So basically right now there is no way to duplicate Button-containing node without this warning.

**Steps to reproduce:**
1. Add Button to scene.
2. Duplicate this button (or any node that has Button as direct or nested child) using `button_or_node_to_duplicate.duplicate()`.

**Minimal reproduction project:**

[basebutton_focus_warning.zip](https://github.com/godotengine/godot/files/6373228/basebutton_focus_warning.zip)

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/48160.

**Comment by YeldhamDev** [comment]
Closed by #51993
