### ISSUE TITLE
Ability to maximize cetain panels 

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#4819]
Proposing the following:
- A new icon on the right side of certain panels will enable  2D, 3D, Script, FileSystem browser panels to be  maximized (to occupy the entire window) or minimize (return them to default normal behaviour). Perhaps starting Godot via terminal with the switch`-editor`should open Godot in Script mode with the Script editor panel maximized.

**Comment by neikeq** [comment]
I like the idea of maximizing the main view (2D, 3D or Script).

**Comment by bojidar-bg** [comment]
Note that the `-e` switch is already taken for the whole editor, so maybe `-e -script`, `-e -2d` and `-e -3d` can do it?

**Comment by akien-mga** [comment]
> I like the idea of maximizing the main view (2D, 3D or Script). Not so much the command line option :P

+1 to both statements.

**Comment by trollworkout** [comment]
:P The command line I thought maybe could be used to start up Godot as a script editor only

**Comment by mefihl** [comment]
Mayby also maximized bottom panels "Debugger" or "Output"?

**Comment by reduz** [comment]
This should be easy to do..

**Comment by neikeq** [comment]
Would it be enough to hide all the docks? or should the menus and toolbars at the top also be hidden?

**Comment by trollworkout** [comment]
This one is already implemented no? I think it can be closed.
