### ISSUE TITLE
Wrong inspector values under mono by using exported variables with get and set method

### ISSUE THREAD

**Issue by sboron** [godotengine/godot#48197]
**Godot version:**
4.0

**OS/device including version:**
Vulkan

**Issue description:**
Wrong inspector values under mono by using exported variables with get and set method.

**Steps to reproduce:**
1.) Create a partial class of a resource
2.) Add a new value with the attribute [export] with an get an set method
`float _test = 0.5f;`
`public float test { get { return _test; } set { _test = value; } }`
3.) Attach the resource as an exported variable to a test class
3.) Enjoy the issue
![image](https://user-images.githubusercontent.com/76991284/116006617-47d6a600-a60c-11eb-8a80-317d16d43d31.png)

**Minimal reproduction project:**
not requried

**Comment by sboron** [comment]
I working on pr . Must be taken into account:

https://github.com/godotengine/godot/pull/44879
https://github.com/godotengine/godot/issues/47465

**Comment by sboron** [comment]
Please review https://github.com/godotengine/godot/pull/48143 at first and merged. It will make the thinks easier to make a pr for solving my issue.

**Comment by sboron** [comment]
Related to: https://github.com/godotengine/godot/issues/37812

**Comment by aaronfranke** [comment]
@sboron Are you still working on a PR?

**Comment by raulsntos** [comment]
This might've been fixed by #53975, can you check if it still happens?

**Comment by raulsntos** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
