### ISSUE TITLE
Shader does not handle constant single expressions

### ISSUE THREAD

**Issue by jusw85** [godotengine/godot#48204]
**Godot version:**
3.3

**OS/device including version:**
Arch Linux

**Issue description:**

Error:

    const float arg = log(0.1);

    error: Expected constant expression after '='

Workaround:

    const float arg = log(0.1) / 1.0;

This applies to all of `sin`, `exp`, etc.

**Comment by clayjohn** [comment]
Cc @Chaosus

**Comment by Chaosus** [comment]
I need to get well after a spring flue, then I will return to programming...
