### ISSUE TITLE
Android export color is different than pc run.

### ISSUE THREAD

**Issue by a3p169** [godotengine/godot#48218]
**Godot version:**
3.3.stable

**OS/device including version:**
Android 5.1 and Android 9 (And possibly more)

**Issue description:**
Android build has different color temperature than PC/Laptop build. Color should look same regardless of platform.

**Steps to reproduce:**
Create simple scene with MeshInstance, Environment, Light and Camera. Then run it on both PC and Android. 

**Minimal reproduction project:**
[androidColorBug.zip](https://github.com/godotengine/godot/files/6379499/androidColorBug.zip)

**Comment by a3p169** [comment]
I'm using linux with wayland. I'm not sure how this is related but just in case.

**Comment by Calinou** [comment]
< Android build has different color temperature than PC/Laptop build. Color should look same regardless of platform.

You can't assume that every display will be calibrated the same way :slightly_smiling_face: 

Android devices often come with oversaturated colors out of the box. On some devices, you can fix this by setting the device's screen color mode to **sRGB** or **Basic** in the device's settings. Unfortunately, this isn't something you can force on your players' devices.

Can you take a *photo* of your PC and your Android device running the same project, then a photo of the same devices showing the same picture?

**Comment by a3p169** [comment]
Totally forgot to post that. ![image](https://user-images.githubusercontent.com/50569653/116139612-d4a85f00-a6f3-11eb-850c-9e61d59e9f61.jpeg)

**Comment by volzhs** [comment]
![Screenshot_20210427_042739](https://user-images.githubusercontent.com/8281454/116139404-f19f5b00-a710-11eb-9d8d-ee7b02204db5.png)
I think it's rendered by vertex shading on mobile devices by default.
if you turn off this `Force Vertex Shading.mobile` or turn on `Force Vertex Shading`, it will be the same look.

**Comment by lawnjelly** [comment]
Another thing to try is running in the Android emulator on the same desktop, and comparing the colors (e.g. with a screenshot). That will establish whether it is a software or hardware thing.

**Comment by a3p169** [comment]
@Calinou it is exactly as you said. I took screenshot from laptop run and opened in phone gallery and it looks more yellowish. I'm stumped

**Comment by a3p169** [comment]
Man I just did a simple test on YouTube with same video. (I wonder why I didn't think of this before) and it is more saturated.

**Comment by Calinou** [comment]
> Man I just did a simple test on YouTube with same video. (I wonder why I didn't think of this before) and it is more saturated.

Specific applications can cause the device to switch its display mode for a more saturated one. I've noticed this on my OnePlus 6.

**Comment by a3p169** [comment]
I wonder if Godot Can change those settings with OS shell commands?
