### ISSUE TITLE
Error calling method from signal 'timeout': 'Node::TimerTimeout': Method not found..

### ISSUE THREAD

**Issue by cyxl** [godotengine/godot#48223]
**Godot version:**
v3.2.3

**OS/device including version:**
GLES3 1660 super

**Issue description:**
I open my project and it starts printing 
'Error calling method from signal 'timeout': 'Node::TimerTimeout': Method not found..' 

**Steps to reproduce:**
Rename whole project including everything in the .sln  
## This is what I am assuming happened cause it started after I did this. 

**Picture**
![image](https://user-images.githubusercontent.com/59654683/116177532-2b507180-a6d1-11eb-908c-ed4716a896f7.png)

**Comment by Calinou** [comment]
@cyxl Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by akien-mga** [comment]
Closing as OP never answered. For the record, this typically happens if the method you try to connect to doesn't exist, or exists but has the wrong signature (number and type of arguments).
