### ISSUE TITLE
'apksigner' returned with error # 1 when exporting to android?

### ISSUE THREAD

**Issue by komputerboy** [godotengine/godot#48220]
**Godot version:**

Godot 3.3

**OS/device including version:**

Nvdia GT630M, Laptop ASUS K43s, GLES3, Windows 7 64 Bit

**Issue description:**

Hello, recently i updated godot to version 3.3, and i am having a problem when i try to export to android.
the following message appears:

`'apksigner' returned with error # 1`

This problem did not happen in previous versions, can someone help me please?

**Steps to reproduce:**
1. Install required component:
`sdkmanager --sdk_root=<android_sdk_path> "platform-tools" "build-tools;30.0.1" "platforms;android-29" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"`

2. Try to export it with: 
`Project -> Export -> Android`

3. My setting in Editor:
![test](https://user-images.githubusercontent.com/42455711/116161183-86a85100-a71d-11eb-919f-e9de25b06c4c.png)

**Comment by Calinou** [comment]
The Adb and Jarsigner project settings are no longer used in Godot 3.3, but they'll still appear in the Editor Settings if you've upgraded from 3.2 due to https://github.com/godotengine/godot/issues/22099.

Instead, you need to set the Android Sdk Path only.

**Comment by blacknoize404** [comment]
I have 'apksigner' returned with error # 2.

**Comment by komputerboy** [comment]
> The **Adb** and **Jarsigner** editor settings are no longer used in Godot 3.3, but they'll still appear in the Editor Settings if you've upgraded from 3.2 due to #22099.
> 
> Instead, you need to set the **Android Sdk Path** only.

okay, i've already reset my editor settings, now it looks like this:
![tes](https://user-images.githubusercontent.com/42455711/116180051-82425f00-a742-11eb-9455-dce6260823db.png)

but, it still error: `'apksigner' returned with error # 1`

**Comment by allkhor** [comment]
Maybe related https://github.com/godotengine/godot-docs/issues/4796, try to update build-tools to 30.0.3 version. To find more explicit error message run godot in verbose mode godot -v

**Comment by HaywardMorihara** [comment]
@komputerboy I came across this error and found the problem was that I needed to provide the `debug.keystore` username & password in the _Export_ options (Export -> Options -> Keystore) as well when I went to export the project for Android.

I made a [pull request to update the tutorial documentation](https://github.com/godotengine/godot-docs/pull/4918) to reminder developers to do this, but I'm wondering if this is a bug where the `Editor Settings` _should_ be propagating to as defaults to the `Export` options?
