### ISSUE TITLE
Resources are treating all variables as @export

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#48224]
**Godot version:**
4.0.dev d1dc28e

The issue occurred sometime between 9ca0d66 and b4b7c97

**OS/device including version:**
Windows 10.0.19041.928

**Issue description:**
It is often desired for resources to have temporary state which is not exported (neither visible in the inspector, nor saved to a file) In GDScript, this is controlled by using or not using @export .

Recently, however, a change was made that seems to cause all variables to act as if exported.

This is a big problem for me, as I have some data structures which are inter-connected so as to form a cycle. I have replicated a simple version of how I use resources in the attached project. Due to this bug, ResourceSaver.save() recurses infinitely (which is I think a bug in its own right, but let's fix one thing at a time)

I added a print statement in _find_resources to illustrate infinite recursion, and specifically the fact that it is recursing through the `toplevel` field which is not marked export.

```
...
ERROR: text: Local path: 'res://saved_resource.tres' checking key resource_local_to_scene
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key resource_name
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key script
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key sub_resources
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key resource_local_to_scene
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key resource_name
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key script
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key sub_value
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key toplevel
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
ERROR: text: Local path: 'res://saved_resource.tres' checking key resource_local_to_scene
   at: ResourceFormatSaverTextInstance::_find_resources (scene\resources\resource_format_text.cpp:1448)
...
```

**Steps to reproduce:**
1. Open the attached project
2. Select Project -> Tools -> Run Resource Test...
3. Ideally, a resource will be written to the root of the project. However, instead it crashes.

**Minimal reproduction project:**
[RecursiveResources.zip](https://github.com/godotengine/godot/files/6382166/RecursiveResources.zip)

**Comment by lyuma** [comment]
Related issue:
References declared as `var some_ref_obj: Reference = null` are also being serialized!

But the way Reference types are serialized makes no sense... since they aren't supposed to be serialized. This leads the generated resource files to be corrupt!

Here is an example of a garbage resource entry generated by serialization of a non-export Reference object.
```
[sub_resource type="Resource" id=10]
resource_name = "test_resource"
script = ExtResource( 2 )
some_ref_obj = Object(Reference,"script":null,"parent_resource":SubResource( 10 ),"keys":{
},"_cache_uniq_key":"","adapter":Object(Reference,"script":Resource( "res://addons/gdacid/gdacid_object_adapter.gd" ),"_type_dictionary":{
"TextureImporter": null,
"Transform": null
}),"is_test":false,"key":"0000","name":"NO_NAME","toplevel":true,"source_object":[ null, 0, "", 0 ],"instance":[ null, 0, "", 0 ],"main_id":0)

internal_data = {
}
```

**Comment by lyuma** [comment]
This issue is a blocker for me writing any GDScript tooling, so I ran a bisect, and localized it to this commit by @vnen (corresponding PR: #47131 )

160c26049566a8f392420d459d8a738e8e3b753d is the first bad commit
commit 160c26049566a8f392420d459d8a738e8e3b753d
Date:   Wed Mar 17 14:58:05 2021 -0300

    GDScript: Allow export of enum variables

    Also fix the enum type in variables to be integer.

 modules/gdscript/gdscript_compiler.cpp |  9 ++-------
 modules/gdscript/gdscript_parser.cpp   | 21 +++++++++++++++++++--
 modules/gdscript/gdscript_parser.h     |  2 +-
 3 files changed, 22 insertions(+), 10 deletions(-)

**Comment by lyuma** [comment]
The following patch fixes this issue. I have opened PR #48253 
```
diff --git a/modules/gdscript/gdscript_compiler.cpp b/modules/gdscript/gdscript_compiler.cpp
index 9b718db7cf..59a5add63b 100644
--- a/modules/gdscript/gdscript_compiler.cpp
+++ b/modules/gdscript/gdscript_compiler.cpp
@@ -2223,8 +2223,9 @@ Error GDScriptCompiler::_parse_class_level(GDScript *p_script, const GDScriptPar
                                        prop_info.hint = export_info.hint;
                                        prop_info.hint_string = export_info.hint_string;
                                        prop_info.usage = export_info.usage;
+                               } else {
+                                       prop_info.usage = PROPERTY_USAGE_SCRIPT_VARIABLE;
                                }
-                               prop_info.usage |= PROPERTY_USAGE_SCRIPT_VARIABLE;
 #ifdef TOOLS_ENABLED
                                p_script->doc_variables[name] = variable->doc_description;
 #endif
```

This does revert a part of the change to fix export of enum types, so I assume this could break some enum types.

My question is: why is this usage flag needed to get enums exporting?

**Comment by Blackiris** [comment]
By **default**, as we can see it in object.h
```
PropertyInfo usage
= PROPERTY_USAGE_DEFAULT
= PROPERTY_USAGE_STORAGE | PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_NETWORK.
```
On some examples from my own project (for instance `var dict = {}`), I also get PROPERTY_USAGE_NIL_IS_VARIANT added, if the variable has no type because of gdscript_function.h, l. 172.

By testing, I noticed the followings flag meanings:
- PROPERTY_USAGE_EDITOR: flag used to display it in the inspector.
- PROPERTY_USAGE_STORAGE: flag to know if it should be saved in the scene file
- PROPERTY_USAGE_NETWORK: from the code "Deprecated usage flag, unused."
- PROPERTY_USAGE_NIL_IS_VARIANT: flag for ????

In your PR, in the reverted code (if not an exported variable)
```gdscript
prop_info.usage = PROPERTY_USAGE_SCRIPT_VARIABLE;
```
the usage will get erased of the PROPERTY_USAGE_EDITOR and PROPERTY_USAGE_STORAGE flags and thus fix your issue.

However, I don't know what is the impact of removing the PROPERTY_USAGE_NIL_IS_VARIANT flag.
A less risky proposal is to remove only the PROPERTY_USAGE_EDITOR and PROPERTY_USAGE_STORAGE flags using:

```gdscript
prop_info.usage &= ~(PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_STORAGE);
```
Maybe we need a confirmation of someone who knows...
