### ISSUE TITLE
GIProbe will still take into consideration material emission when disabled

### ISSUE THREAD

**Issue by PanTrakX** [godotengine/godot#48230]
**Godot version:**
3.3.stable

**OS/device including version:**
I can provide if needed.

**Issue description:**
When baking GI Probe, it will bake the emission from materials even if its turned off but has a emission color set other than black.

**Steps to reproduce:**
1. Add a MeshInstance with a CubeMesh to the scene.
2. Add a material to the MeshInstance
3. Turn on emission and set a (bright) color like a cyan.
4. Turn off emission 
5. Add a GI Probe
6. Bake GI Probe

**Minimal reproduction project:**
[giprobe_bug.zip](https://github.com/godotengine/godot/files/6383833/giprobe_bug.zip)

**Comment by akien-mga** [comment]
Fixed by #48798.
