### ISSUE TITLE
Godot engine on Kickstarter?

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#4825]
Perhaps in order to accelerate the development of godot engine should support him on Kickstarter like as Krita(https://www.kickstarter.com/projects/krita/krita-2016-lets-make-text-and-vector-art-awesome).

**Comment by reduz** [comment]
We are planning to do a crowdfunding campaign when 2.1 comes out

**Comment by neikeq** [comment]
@reduz Nice. Improving the renderer sounds like a good objective for a crowdfunding campaign.

Is there a reason to leave this issue open? It's not related to the repository.

**Comment by akien-mga** [comment]
I think we can close the issue yes, we probably won't be using it to actually prepare the campaign.
