### ISSUE TITLE
In Godot 3.3.2, scripts cannot use rename() to change folder names

### ISSUE THREAD

**Issue by yxl1779556215** [godotengine/godot#48254]
**Godot version:**

3.3.2

**OS/device including version:**

windows10

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

Godot 3.3中无法使用rename对文件夹进行重命名，但是对文件可以。对文件夹进行重命名时，系统报错为：file_exists()所选文件不存在。本人推测是将文件夹作为文件进行判断，我对Godot进行卸载重装，依然是这样。在3.2.3版本中没有出现这个错误

**Comment by Megalomaniak** [comment]
Translation via google translate:
"In Godot 3.3, rename cannot be used to rename folders, but files can be renamed. When renaming the folder, the system reports an error: The file selected by file_exists() does not exist. I guessed that the folder was judged as a file. I uninstalled and reinstalled Godot, and it was still the same. This error did not appear in version 3.2.3"

**Comment by akien-mga** [comment]
I can't reproduce the issue, renaming folders works fine here on Linux:

https://user-images.githubusercontent.com/4701338/116368898-170f9000-a809-11eb-9d36-4900b4e45327.mp4

Please give more details. What OS are you using? What are you doing exactly?

**Comment by floppyhammer** [comment]
能提供一个可以复现这个问题的Godot工程（打成压缩包再拖进评论框就行）吗？还有，最好提供一些其它的信息，比如你的操作系统之类的（按照模板来填，查查你的问题上面那几个小标题什么意思）。另外，这个社区一般用英语交流，你可以先自己用谷歌翻译转成英语，这样也省得麻烦别人特地去转。

Can you provide a minimal reproduction project? And it's better to give more details about the issue, e.g. the OS you're using. In addition, English is mostly used for communication in this community. I suggest you translate your words into English by Google Translate first, saving some trouble for others.

**Comment by Megalomaniak** [comment]
Can't reproduce on windows 7 64 bit either. Godot 3.3 64bit(didn't try the mono version).

**Comment by Calinou** [comment]
@yxl1779556215 Can you still reproduce this bug? You can also test this in [Godot 3.3.1rc2](https://godotengine.org/article/release-candidate-godot-3-3-1-rc-2) and see if you can reproduce the bug there.

**Comment by yxl1779556215** [comment]
> @yxl1779556215你还能重现这个虫子吗？您也可以在[Godot 3.3.1rc2](https://godotengine.org/article/release-candidate-godot-3-3-1-rc-2)中测试此，看看是否可以在那里重现该 bug。

Sorry, I don't know much about GitHub. I am using windows10 and godot version 3.3.2. This error still exists, please help me, thank you.
![屏幕截图 2021-08-17 141810](https://user-images.githubusercontent.com/83115486/129675261-5a667751-2d92-4a67-a7be-a23a39a1a2dc.png)
![屏幕截图 2021-08-17 142040](https://user-images.githubusercontent.com/83115486/129675269-691498c9-4067-4c60-bf1c-90f095491eac.png)

**Comment by floppyhammer** [comment]
What the docs say about this method:

> Error rename ( String from, String to )
> 
> Renames (move) the from file to the to destination. Both arguments should be paths to files, either relative or absolute. If the destination file exists and is not access-protected, it will be overwritten.
> 
> Returns one of the Error code constants (OK on success).

It can only be used to change files' name, so what you're experiencing is intended.

**Comment by yxl1779556215** [comment]
> 文档对此方法的看法：
> 
> > 错误重命名 （字符串从， 字符串到 ）
> > 将文件重命名为到目的地。这两种参数都应是通往文件的路径，无论是相对的还是绝对的。如果目的地文件存在且未受访问保护，则将被覆盖。
> > 返回错误代码常数之一（成功时确定）。
> 
> 它只能用于更改文件的名称，因此您正在体验的内容是有意的。

Thank you for your answer, but in my version 3.2.3, this behavior is feasible.

**Comment by floppyhammer** [comment]
@yxl1779556215 Just did some testing. Can confirm.

**Comment by yxl1779556215** [comment]
> @yxl1779556215 Just did some testing. Can confirm that `Directory.rename()` in 3.3 and 3.4 can't rename folders while it can in 3.2.3. We should change the issue title.

Thank you very much for your reply. I don't know how the title got there. I don't know much about it. Is there a way to rename folders using scripts in Version 3.3.2?

**Comment by floppyhammer** [comment]
@yxl1779556215 Sorry I couldn't think of a straightforward way to do it. If this change is not intended, I'll try to look into the issue.

**Comment by floppyhammer** [comment]
The behaviour change of `rename()` was introduced by 11cbe99cccc2a493e14dfce674a70ad0190e2f61 to avoid renaming a non-existing file. Since a path is not a valid file, `ERR_DOES_NOT_EXIST` gets returned.

**Comment by yxl1779556215** [comment]
> [ 11cbe99](https://github.com/godotengine/godot/commit/11cbe99cccc2a493e14dfce674a70ad0190e2f61)引入了行为更改，以避免重命名不存在的文件。由于路径不是有效的文件，将返回。`rename()``ERR_DOES_NOT_EXIST`

HMM... I don't understand it, but it looks like that's where the problem is. So, what do I need to learn if I want to get involved in developing Godot?

**Comment by floppyhammer** [comment]
@yxl1779556215 You could check out this page first https://docs.godotengine.org/en/stable/community/contributing/ways_to_contribute.html. And this specific issue will be handled by @KoBeWi.

**Comment by yxl1779556215** [comment]
> @yxl1779556215 You could check out this page first https://docs.godotengine.org/en/stable/community/contributing/ways_to_contribute.html. And this specific issue will be handled by @KoBeWi.

Thank you very much!

**Comment by KoBeWi** [comment]
> And this specific issue will be handled by @KoBeWi.

Even if an issue has someone assigned, you are free to make a PR, because there is no guarantee that it will be handled anytime soon.
Although in this case the fix was easy, so I could make a quick PR.
