### ISSUE TITLE
Wrong mipmaps for VRAM compressed textures.

### ISSUE THREAD

**Issue by JFonS** [godotengine/godot#48261]
**Godot version:**

Latest master 7bca907

**OS/device including version:**

Linux

**Issue description:**

Looks like textures that are imported a "VRAM compressed" have incorrect mip map data, so they show artifacts when used in 3D meshes. Using any other compression mode seems to fix the issue, so it's most likely related.

![Screenshot_20210428_103045](https://user-images.githubusercontent.com/4402304/116374291-71f7b600-a80e-11eb-934a-8ec58ea992fc.png)
Same file, VRAM compressed on the left, lossless compression mode on the right.

**Steps to reproduce:**

* Import any texture as "VRAM compressed"
* Use it on a 3D mesh.
* Notice artifacts from mip maps.

**Minimal reproduction project:**

[vram-compressed-bug.tar.gz](https://github.com/godotengine/godot/files/6390381/vram-compressed-bug.tar.gz)

**Comment by akien-mga** [comment]
Likely a regression from #47370, though it could also be me who broke it when refactoring in #47917.

Especially I was a bit confused by the `p_mipmap - 1` used in this static `Image` method I'm using (as advised by @reduz): https://github.com/godotengine/godot/blob/master/core/io/image.cpp#L2339-L2347

**Comment by floppyhammer** [comment]
Is it correct for `Image::get_image_mipmap_offset_and_dimensions()` to set `mip_w` and `mip_h` as the original image size when `i == 1`? For example, the original size is (1024, 1024). The loop goes like this: i == 0, mip_w = 1024, mip_h = 1024 (the original image); i == 1, mip_w = 1024, mip_h = 1024 (the first mipmap); i == 2, mip_w = 512, mip_h = 512; etc. I tried to add an additional `>> 1` to the mipmap size when `i >= i`. The mipmaps did look better but were still not completely correct.

**Comment by floppyhammer** [comment]
I just checked how vram compressed textures look like in 3.x. The result is quite similar to my fixed result. So maybe this is the right fix to the regression.
![image](https://user-images.githubusercontent.com/28705694/121184465-b0fe3a00-c897-11eb-81cf-17033ff77f07.png)
