### ISSUE TITLE
HTML5 export can't use windows IME

### ISSUE THREAD

**Issue by enemy-of-mankind** [godotengine/godot#48260]
**Godot version:**
v3.3.stable.official

**OS/device including version:**
Windows 10 19042.928
Browser: Chrome, Edge

**Issue description:**
Can't use IME in HTML5 export, but can use the IME in desktop export. Hope to use IME in HTML5.

**Steps to reproduce:**
1.New project
2.add a LineEdit or TextEdit
3.add HTML5 export
4.Run in browser
5.Use windows IME to input content in LineEdit or TextEdit

For example, this is Chinese IME:
![GIF 2021-4-28 16-26-11](https://user-images.githubusercontent.com/67264008/116373414-e565eb80-a83f-11eb-8c3c-991c0f123a20.gif)

**Minimal reproduction project:**
New project, add a LineEdit or TextEdit, add font.

**Comment by akien-mga** [comment]
CC @Faless @bruvzg

**Comment by Faless** [comment]
Same issue as #45904 .
IME support in browsers is limited to `input` and `textarea`. Does not apply to `canvas` element.

**Comment by akien-mga** [comment]
Closing as duplicate of #45904 then (I edited the title to reflect that it also includes IMEs).

**Comment by enemy-of-mankind** [comment]
Thanks
