### ISSUE TITLE
Loading 3.2.3 project in 3.3 results in no MSBuild tab in the editor

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#48264]
**Godot version:**

3.3 mono stable

**OS/device including version:**

Debian 10 
Godot Engine v3.3.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL ES Batching: ON
/lib/x86_64-linux-gnu/libpulse.so.0: undefined symbol: pa_threaded_mainloop_once_unlocked
/lib/x86_64-linux-gnu/libpulse.so.0: undefined symbol: pa_thread_make_realtime

**Issue description:**

If I load an old project the editor don't have MSBuild tab

**Steps to reproduce:**
Load 3.2.3 mono project

**Minimal reproduction project:**

NA
ps If you need  one I can make it from scratch.

**Comment by Calinou** [comment]
> ps If you need one I can make it from scratch.

Please do, and upload it here :slightly_smiling_face:

**Comment by git2013vb** [comment]
Duplicate of #27030
