### ISSUE TITLE
Vulkan: Broken normal maps in 3D (RenderingServer bug)

### ISSUE THREAD

**Issue by sboron** [godotengine/godot#48279]
**Godot version:**
4.0

**OS/device including version:**
Windows 10

**Issue description:**

Broken normal maps inside StandartMaterial and ShaderMaterial

With using hint_albedo its broken
![image](https://user-images.githubusercontent.com/76991284/116481141-e9672d00-a882-11eb-8628-0f3d8a80ce31.png)
![image](https://user-images.githubusercontent.com/76991284/116480792-47dfdb80-a882-11eb-8a6a-102938175311.png)

With using hint_normal its broken 2 but looks different
![image](https://user-images.githubusercontent.com/76991284/116481095-cfc5e580-a882-11eb-8886-ee90afff5ad6.png)
![image](https://user-images.githubusercontent.com/76991284/116481133-e53b0f80-a882-11eb-9e5b-625950b99867.png)

**Steps to reproduce:**
Create a simple mesh
Create a shader and set a normalmap inside the shader.
Debug the normals -> tada

**Minimal reproduction project:**
Not required

**Comment by Calinou** [comment]
Can you reproduce this with primitive meshes such as a MeshInstance + BoxMesh setup?

**Comment by sboron** [comment]
The normals of the mesh are looking right. Its just by using a normal map texture.

I have it also on my terrain system which is using a simple PlaneMesh.

without normalmap texture:

![image](https://user-images.githubusercontent.com/76991284/116481534-a3f72f80-a883-11eb-93a5-d6c97d02b341.png)

**Comment by sboron** [comment]
When i deactivating the lod by importing the mesh i got the same issue.
Also on my terrain system i got the same issue with a PlaneMesh.

Its just by using normal maps.

Issue is still there since round about 2 weeks.

**Comment by sboron** [comment]
Its the same what i have with a simple Plane Mesh.

It looks like the wrong uv coordinates are being used.

![image](https://user-images.githubusercontent.com/76991284/116482602-c4c08480-a885-11eb-89f7-446d20e6e78f.png)

**Comment by sboron** [comment]
Okai i was try to replace the binormals and tangents inside the shader and it works. 
So the issue comes from wrong binromals and tangents (mby from the import of the mesh)

`  void vertex()
{
	
	vec3 c1 = cross(NORMAL, vec3(0.0, 0.0, 1.0));
	vec3 c2 = cross(NORMAL, vec3(0.0, 1.0, 0.0));
	vec3 tangent;
	vec3 binormal;
	if (length(c1)>length(c2))
	{
	    tangent = c1;
	}
	else
	{
	    tangent = c2;
	}
	TANGENT = normalize(tangent);
	binormal = cross(NORMAL, tangent);
	BINORMAL = normalize(binormal);

}`

**Comment by sboron** [comment]
Was regenerating the mesh with generate_tangents() and still same issue. so i blv it comes not from the importer. looks more like an shader error

**Comment by sboron** [comment]
@Calinou Wrong topic name. This issue comes not from importing meshes. Its a vulkan rendering server issue.

**Comment by sboron** [comment]
somebody have an idea how i can fix this?

**Comment by akien-mga** [comment]
Why did you close it? Is it fixed?

**Comment by sboron** [comment]
But the tangents are already broken.  See here: 
https://github.com/godotengine/godot/issues/48594
