### ISSUE TITLE
regen_normal_maps error is not in the engine console log

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#48275]
Version 3.2, 3.3, 4.0?
OS: Windows 10

When I don't have normals supplied to a surface in a mesh, when calling [ArrayMesh].regen_normal_maps() upon that mesh it throws the error in the windows terminal, and not in the engine console even though I call the method from GDScript, not sure if this is technically a bug with capital B, but it feels like an inconsistency since all the other bugs I get is neatly put into the issue tracker or in the engine log. BTW the method name is according to me misleading since the method has nothing to do with generating normal maps as in regenerating the textures, but rather to create the tangents for given normal&UV data.
I submit an example of the code generating the issue.

```gdscript
extends MeshInstance


func _ready():
	var cubeMesh = CubeMesh.new()
	var cubeArrays = cubeMesh.get_mesh_arrays()
	var array = [null, null, null, null, null, null, null, null, null]
	array[Mesh.ARRAY_VERTEX] = cubeArrays[Mesh.ARRAY_VERTEX]
	#if the line below is not commented out things work correctly
	#array[Mesh.ARRAY_NORMAL] = cubeArrays[Mesh.ARRAY_NORMAL]
	array[Mesh.ARRAY_TEX_UV] = cubeArrays[Mesh.ARRAY_TEX_UV]
	array[Mesh.ARRAY_INDEX] = cubeArrays[Mesh.ARRAY_INDEX]
	mesh = ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, array)
	mesh.regen_normalmaps()
```

**Comment by Calinou** [comment]
I can't reproduce this on Godot 3.3. The error appears in the Errors panel:

![image](https://user-images.githubusercontent.com/180032/118371888-deb0d580-b5ae-11eb-8843-09293edc0a0d.png)

**Comment by albinaask** [comment]
I tested it now on both 3.2 stable in GDScript and 3.3 Mono with both GDScript & C# and fail to reproduce my results from earlier, So I probably did lose connection somehow, I however did punish the engine rather extensively during that code session with MANY errors and undefined behaviours such as accessing the scenetree asynchronously from c# and a bunch of other edge cases. So that something breaks at that point is not surprising to me, so ignore my Bug report for now, it seem to work fine under normal use conditions ;)
