### ISSUE TITLE
XMapWindow happens before XSetClassHint

### ISSUE THREAD

**Issue by Nohac** [godotengine/godot#4827]
**Operating system or device - Godot version:**
Arch Linux using the bsp window manager.

**Issue description** (what happened, and what was expected):
For most window managers/desktop environments to be able to execute or apply rules to specific programs, they need to have access to the window class/name when the program is mapped, this is not happening as the class hints are set after the mapping.

**Steps to reproduce:**
Install bspwm and try to apply this rule:
`bspc rule -a "Godot:*" state=floating`
Then start godot. The rule is not being applied.

**Link to minimal example project** (optional but very welcome):
Referring to the issue I opened on bspwm baskerville/bspwm#493

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Web-eWorks** [comment]
Current Godot master has https://github.com/godotengine/godot/blob/23b4b7d53a8dabf822cf07074c3b72de43cf649c/platform/x11/context_gl_x11.cpp#L187, which solves this issue. It raises a different issue in that `OS_X11::set_context` has no effect, but this can be discussed in a separate issue.

If there are no confirmations of this issue (and I can confirm it is fixed on i3wm), I recommend it be closed.

**Comment by Nohac** [comment]
Can confirm that this is working as intended now with i3wm.
I'm using these rules to achieve what I want:
```
for_window [instance="Godot_ProjectList"] floating enable
for_window [instance="Godot_Engine"] floating enable
for_window [instance="Godot_Editor"] floating disable
```
Also, happy 2 years anniversary to this issue...
