### ISSUE TITLE
Add panel in script editor to show list of function and varibles in open script

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#4828]
It would be nice to add panel in script editor to show list of function and varibles in open script like in:
NetBeans IDE (https://scontent-waw1-1.xx.fbcdn.net/v/t1.0-9/13062316_10205479518262207_6508038878611220150_n.jpg?oh=1178d2830c82c5d4004eb989fd0b91f4&oe=57DECFE6) 
or Delphi IDE (http://postimg.org/image/vxfb5rpnv).

**Comment by Paulb23** [comment]
Nice mockup in #2732 also duplicate? / related to #3238

**Comment by mefihl** [comment]
I'm sorry I did not notice.

**Comment by bojidar-bg** [comment]
Closing as duplicate of one of #2732 or #3238
