### ISSUE TITLE
Silent crash with to_json(dictionary) if dictionary has point to itself

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#48289]
**Godot version:**

3.4.beta e554ecd691

**OS/device including version:**

Kubuntu 20.10

**Issue description:**

Silent crash with to_json(dictionary) if dictionary has point to itself without any error on console.

**Steps to reproduce:**
```gdscript
func _ready() -> void:
	var dic:Dictionary = {}
	dic.test = dic
	printt(to_json(dic))
```

**Minimal reproduction project:**

[Dictionary crash.zip](https://github.com/godotengine/godot/files/6397255/Dictionary.crash.zip)

**Comment by madmiraal** [comment]
It's caused by running out of memory following recursive calls to `_print_var()` as it tries to print itself within itself within itself within itself...
https://github.com/godotengine/godot/blob/418fe155f90bcb7f5451de1a5e7cb8cec64a15f6/core/io/json.cpp#L113

**Comment by arrowinaknee** [comment]
I imagine this could be avoided by pushing the value passed to `_print_var` to some stack, then checking if the value is already on stack (so it is already being printed) and if so push an error. The stack can be passed as an optional argument to `_print_var`, so it would be created and freed inside the function for internal use.
Is this a legitimate way to fix the issue? I think I can implement it that way

**Comment by arrowinaknee** [comment]
I can reproduce this on `4.0` (0ad03ba052dd3b7bea558a3a76c7ff5c46bf681a) with the following code:
```GDScript
func _ready() -> void:
	var dic:Dictionary = {}
	dic["test"] = dic
	printt(JSON.print(dic))
```
The code snippet also works the same on `3.3` and leads to the same line of code.
