### ISSUE TITLE
Imported models doesn't display when add to a scene

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#48290]
**Godot version:**
commit c11502711ec6f918a4352d8650e46b34a295081e

**OS/device including version:**
Fedora 34

**Issue description:**
Adding an imported model to a scene is not displayed

https://user-images.githubusercontent.com/8342599/116530702-9e7b0300-a8de-11eb-90de-a4b5b45e1bcb.mp4

The issue is not the file name, indeed I get the same error if I use a name without spaces:
```
core/io/resource_format_binary.cpp:318 - Couldn't load resource (no cache): res://big_entrance.fbx::460
```
The issue seems related to the cache, that somehow is not valid. Close and reopen the scene fix the issue.

**Steps to reproduce:**
1. Import a new model
2. Drag and drop inside the scene
3. Sometimes it shows just fine, in this case remove the node and add it back: now the mesh is not shown and you have the above error.

**Comment by RevoluPowered** [comment]
Happens in GLTF and FBX too

Can be tested with this GLB
[SimpleSkin.zip](https://github.com/godotengine/godot/files/6416154/SimpleSkin.zip)

**Comment by RicardRC** [comment]
I've got this problem with any fbx mesh that is instanced multiple times from a c++ module, but it works ok if I instance from gdscript (wich I can't do, unfortunately, for my game, I only checked when investigating this bug).
This happens 100% of the time: The first instance of the mesh shows up, but any consecutive instancing of the same scene has the mesh set to null, the materials set to null, and the warning that @AndreaCatania mentions.

![InkedCaptura de pantalla 2021-04-17 210958_LI](https://user-images.githubusercontent.com/35220750/117565237-75156080-b0b0-11eb-85d9-14f2a35812ef.jpg)

![imagen](https://user-images.githubusercontent.com/35220750/117565256-8e1e1180-b0b0-11eb-8f12-55a0560d829d.png)
This is the output on any second instance of a mesh.

Unfortunately, this render me unable to advance on many aspects of my game development :(

**Comment by MarvinFF** [comment]
always use internal cache for loading internal resources,but internal_index_cache is not always add @reduz 
https://github.com/godotengine/godot/blob/364ea7f280a3f074795e542b16b1d0ec76cf6ce2/core/io/resource_format_binary.cpp#L316-L322
resource is not always add to internal_index_cache
1. last resource is not add 
https://github.com/godotengine/godot/blob/364ea7f280a3f074795e542b16b1d0ec76cf6ce2/core/io/resource_format_binary.cpp#L764-L770
2.when call continue maybe is not add to internal_index_cache by my test 
https://github.com/godotengine/godot/blob/364ea7f280a3f074795e542b16b1d0ec76cf6ce2/core/io/resource_format_binary.cpp#L673-L680

**Comment by RicardRC** [comment]
This issue is still present at master 0a6a719.
Now, it only misses cache hits larger than one, though:
![imagen](https://user-images.githubusercontent.com/35220750/122647677-b2e0bc80-d125-11eb-8e80-2e628a329e3b.png)

**Comment by RicardRC** [comment]
I've been looking at all this, and through I didn't get anything clear, I don't understand why are we returning "OK" at "Error ResourceLoaderBinary::parse_variant(Variant &r_v)" when we "WARN_PRINT(String("Couldn't load resource (no cache): " + path).utf8().get_data());".
It's clear that the assumption that the internal caché is always filled previously to the first "parse_variant" does not hold true. Maybe we should return a proper error code and rebuild the internal cache somehow. Maybe here:
![imagen](https://user-images.githubusercontent.com/35220750/122651157-335be900-d137-11eb-8bd1-0093ec3db05d.png)
As we are currently returning OK, even through the load completely failed, we don't treat it in any form.
I've already invested a whole day on this, I wish I could help more, but couldn't figure out the logic behind the whole internal cache thing.

**Comment by Blackiris** [comment]
@MarvinFF  Good finding, it is cause by the `continue`, triggered before the resource is added to the internal cache. Be changing the code to add it to the cache, it now works for me. Here is the diff, but I won't submit it as PR since I am not sure about the potential risks...

```diff
From a803f604769ec241bf1af0db814a9d7d034beb00 Mon Sep 17 00:00:00 2001
From: Julien Nguyen <julien.nguyen3@gmail.com>
Date: Sat, 17 Jul 2021 23:04:46 +0200
Subject: Fix load resource not found in cache


diff --git a/core/io/resource_format_binary.cpp b/core/io/resource_format_binary.cpp
index 0e9815245f..ef83914f64 100644
--- a/core/io/resource_format_binary.cpp
+++ b/core/io/resource_format_binary.cpp
@@ -660,6 +660,7 @@ Error ResourceLoaderBinary::load() {
 		//maybe it is loaded already
 		String path;
 		int subindex = 0;
+		RES res;
 
 		if (!main) {
 			path = internal_resources[i].path;
@@ -675,7 +676,8 @@ Error ResourceLoaderBinary::load() {
 					//already loaded, don't do anything
 					stage++;
 					error = OK;
-					continue;
+					Resource *r = ResourceCache::get(path);
+					res = Ref<Resource>(r);
 				}
 			}
 		} else {
@@ -690,7 +692,7 @@ Error ResourceLoaderBinary::load() {
 
 		String t = get_unicode_string();
 
-		RES res;
+
 
 		if (cache_mode == ResourceFormatLoader::CACHE_MODE_REPLACE && ResourceCache::has(path)) {
 			//use the existing one
```

**Comment by MHillier98** [comment]
Can confirm this is still happening in `v4.0.dev.official`.

**Comment by Calinou** [comment]
@Blackiris Feel free to open a pull request with this change :slightly_smiling_face:
