### ISSUE TITLE
Godot can't find wine (Flatpak)

### ISSUE THREAD

**Issue by bastil0** [godotengine/godot#48293]
**Godot version:**
3.3 (Flatpak version)

**OS/device including version:**
Ubuntu 21.04

**Issue description:**
Godot can't find wine for the rcedit command (Windows export). I tried to leave the wine option in the editor settings blank, I tried "wine", "/usr/bin/wine", ... When I click on browse I can't find it either, but it works if I run it in the terminal. It works in the normal download version of Godot but not in the Flatpak version so I think this is a permission thing.

**Steps to reproduce:**
- Install Godot via Flatpak
- Install wine
- Try to find and use it in an export

**Comment by akien-mga** [comment]
That's a normal limitation of flatpaks, they're sandboxed so they don't give you access to other system binaries.

**Comment by bastil0** [comment]
Ok, I understand. Would be helpful if the whole command would be printed in the output console to run the command by hand in the terminal as a solution.

**Comment by Calinou** [comment]
It should be possible to implement support for rcedit with the Flatpak *as long as WINE is installed on the host*: https://github.com/flathub/org.godotengine.Godot/pull/38

**Comment by Pobega** [comment]
You shouldn't have to use host wine anymore, Godot should be able to use [org.winehq.Wine](https://github.com/flathub/org.winehq.Wine).

Unfortunately the way it's currently distributed is as a base app, but Godot can choose to distribute its own Wine as an extension (similar to how I did in the Fightcade Flatpak: [com.fightcade.Fightcade.Wine](https://github.com/flathub/com.fightcade.Fightcade.Wine)
