### ISSUE TITLE
Friction in PhysicsMaterial is too low even at 1.0 (the max)

### ISSUE THREAD

**Issue by DanielKinsman** [godotengine/godot#48298]
**Godot version:**
3.3 stable

**OS/device including version:**
linux

**Issue description:**
At the maximum value for friction (1.0) things are still very slippy. It was clamped to 0-1 in #42202. Experimenting by forcing a value of > 1.0 by manually editing the tscn with `friction = 100.0` provides the grippyness I am after. Is it possible that the docs are wrong and it is actually a percentage rather than normalised? Or am I just abusing undefined behaviour in the physics engine? Values >100 seem to behave the same as 100 but I haven't done extensive testing.

**Steps to reproduce:**
Run the minimal reproduction project. One of the objects has a friction of 1.0, the other has a friction of 50.0 (both set with roughness). The one with 50.0 friction behaves with much more grip.

**Minimal reproduction project:**

[frictiontest.zip](https://github.com/godotengine/godot/files/6398552/frictiontest.zip)

**Comment by akien-mga** [comment]
CC @rcorre @godotengine/physics

**Comment by madmiraal** [comment]
Despite what the documentation suggested, there is a case for both [bounce](https://github.com/godotengine/godot/pull/42203#issuecomment-737253504) and friction to be greater than 1; so I think 
#42202 and it's cherry-pick, should be reverted.

Note: Although, as pointed out [here](https://github.com/godotengine/godot/pull/42203#discussion_r493611311), combined bounce is clamped by the physics server to be between 0 and 1, the same is not true for friction:
https://github.com/godotengine/godot/blob/d578d82e578edf18d6e3421fbb575e1879a827f1/servers/physics_2d/body_pair_2d_sw.cpp#L214-L220

**Comment by rcorre** [comment]
I wonder if it is different between 2D and 3D? I tried putting cubes on sloped planes with friction values of 50, 1, and 0.1 (both the plane and the corresponding cube). 0.1 slides down the slope, 1 sticks to the slope, and 50 jitters erratically.
[example.zip](https://github.com/godotengine/godot/files/6410121/example.zip)
