### ISSUE TITLE
getting stuck in walls in my  fps game getting stuck in  a wall like ranomly walking then that happens so i think we need a change in physics

### ISSUE THREAD

**Issue by angelodpzc** [godotengine/godot#48306]
**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by pouleyKetchoupp** [comment]
Closing as there's not enough information. Feel free to re-open once you update with reproduction steps or a minimal reproduction project.
