### ISSUE TITLE
C# EditorPlugin doesn't work

### ISSUE THREAD

**Issue by OsaPL** [godotengine/godot#48304]
**Godot version:**
3.3

**OS/device including version:**
Win10 v1903, 64bit

**Issue description:**
Can't get a .cs EditorPlugin to load.

 
**Steps to reproduce:**

1. Create plugin.cfg:
```
[plugin]

name="Test"
description=""
author="Osa"
version="1.0"
script="plugin.cs"
```
2. Create plugin.cs (as per docs):
```
#if TOOLS
using Godot;
using System;
using Object = Godot.Object;

[Tool]
public class TestPlugin : EditorPlugin
{

}
#endif
```

3. It doesnt want to be enabled, throws:
```
Unable to load addon script from path: 'res://addons/Test/plugin.cs' There seems to be an error in the code, please check the syntax.
```

Rebuilding doesnt help.

**Minimal reproduction project:**
[PluginTest.zip](https://github.com/godotengine/godot/files/6400616/PluginTest.zip)

**Comment by Calinou** [comment]
> **OS/device including version:**
> *I dont think it matter, will provide if needed*

Please always provide this information, even if you don't think it matters :slightly_smiling_face:

**Comment by OsaPL** [comment]
Added windows ver

**Comment by GeorgeS2019** [comment]
@Calinou  @OsaPL  consider a test demo project for Addon c# to be checked each version release. Often, in my experience, is some typo etc.

**Comment by GeorgeS2019** [comment]
[PluginTest.zip](https://github.com/godotengine/godot/files/6405716/PluginTest.zip)

**Comment by GeorgeS2019** [comment]
The provided project has typo error. Nothing wrong with Godot 3.3

**Comment by GeorgeS2019** [comment]
@Calinou  close this issue.  Lack of simple demo project in c# re-create this kind of issues -- again and again

**Comment by OsaPL** [comment]
What are you talking about? 
What typo, could you elaborate?
`Lack of simple demo project in c# re-create this kind of issues ` I did supply the _Minimal reproduction project_.

I genuinely don't know what I did wrong, I did everything the docs said to do, adn it doesn't work.

**Comment by GeorgeS2019** [comment]
@OsaPL  public class **TestPlugin** => should be public class **plugin**  => pls try that :-)

**Comment by OsaPL** [comment]
@GeorgeS2019 Oh, yeah, now it works, thanks!

Went through docs, and yeah, `it must be a tool script, or else it will not load properly in the editor, and it must inherit from EditorPlugin.`
No mention of it actually having to be named the same name as the script file, maybe it should be mentioned?

**Comment by GeorgeS2019** [comment]
@OsaPL  why having a very simple demo project, when prevent another one from repeating this mistake.

**Comment by OsaPL** [comment]
Im just saying its counterintuitive, especially since its not a thing for normal scripts. From my experience you can name classes however you want there.
Well this or maybe fix up the generated one to be correct, saw a bug for that somewhere here, but cant find it now.

**Comment by GeorgeS2019** [comment]
@OsaPL  Keep feedback and write Godot Proposals, especially Mono c#.  The documentation for mono c# is often less complete than the GDScript

**Comment by OsaPL** [comment]
I was just proposing a single line mentioning this, even in the code snippet as a comment... 
From what I've already read online trying to fix this, Im not the only guy that had problems with just starting c# editor plugins.
Eh, okay, nevermind, whenever I'll find some time, I'll contribute myself.

I'll just refer #28799, cause it will mitigate such problems.
Closed.

**Comment by akien-mga** [comment]
What documentation page are you referring to here?
