### ISSUE TITLE
Virtual Keyboard crashes on iOS after calling show_virtual_keyboard

### ISSUE THREAD

**Issue by joshsegall** [godotengine/godot#48313]
**Godot version:**
3.3

**OS/device including version:**
iPhone 8, iOS 14.4.2

**Issue description:**
After calling OS.show_virtual_keyboard(), typing anything into the virtual keyboard on iOS causes the app to crash.

**Steps to reproduce:**
1. In a gdscript, call OS.show_virtual_keyboard
2. Export to iOS (note if you use my repro project you'll have to set a valid Apple Team ID)
3. In Xcode, build and deploy to an iOS device (iPhone 8 in my case)
4. When the keyboards show, press any button

**Minimal reproduction project:**
[KbdCrashTest.zip](https://github.com/godotengine/godot/files/6402187/KbdCrashTest.zip)

I have traced this to https://github.com/godotengine/godot/blob/3.3/platform/iphone/keyboard_input_view.mm#L96, where if start and end are both -1 then it sets the range to (-1, 0), which later causes the crash. Possible fix is to set the range to (0,0) if start < 0.

https://github.com/godotengine/godot/blob/3.3/core/bind/core_bind.cpp#L1091 calls this function without the start/end arguments, leaving them to be -1.

**Comment by Calinou** [comment]
cc @naithar

**Comment by joshsegall** [comment]
Here's the error in the logs:

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFConstantString substringToIndex:]: Index 18446744073709551615 out of bounds; string length 0'
terminating with uncaught exception of type NSException
