### ISSUE TITLE
There may be an error in file_access_network

### ISSUE THREAD

**Issue by vmjcv** [godotengine/godot#48326]
**Godot version:**

master

**OS/device including version:**

**Issue description:**

When I read the code, I found that the code may have some problems because last_id, and the exact object cannot be deleted during the construction and destruction FileAccessNetwork.

the code is in core\io\file_access_network.cpp line 479-497

      FileAccessNetwork::FileAccessNetwork() {
	      FileAccessNetworkClient *nc = FileAccessNetworkClient::singleton;
	      nc->lock_mutex();
	      id = nc->last_id++;
	      nc->accesses[id] = this;
	      nc->unlock_mutex();
	      page_size = GLOBAL_GET("network/remote_fs/page_size");
	      read_ahead = GLOBAL_GET("network/remote_fs/page_read_ahead");
      }
      
      FileAccessNetwork::~FileAccessNetwork() {
	      close();
	      FileAccessNetworkClient *nc = FileAccessNetworkClient::singleton;
	      nc->lock_mutex();
	      id = nc->last_id++;
	      nc->accesses.erase(id);
	      nc->unlock_mutex();
      }

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Please specify the Godot version so that we know which code you are looking at exactly. I suppose it's the current `master` branch (a91effc7915543f5cf2df7ffd6b33c61d4fc2218) but this should be explicit in the issue.

**Comment by Faless** [comment]
I'm not familiar with the `FileAccessNetwork` code but if you think you've found a bug, please make a pull request and we'll review it.

**Comment by vmjcv** [comment]
I read your modification, I think it should be changed
id = --nc-> last_id; instead of deleting him, 
if you delete him, last_id will continue to increase. 
This variable should mean the last available id

**Comment by Faless** [comment]
> if you delete him, last_id will continue to increase.

I think that's fine, it's unlikely we'll roll over, and `id`s should be unique. Additionally, I'm not sure that when `ID` is deleted `ID-1` has already been deleted.
`last_id` in this context seems to mean: "last used ID".

**Comment by vmjcv** [comment]
ok, there is something wrong with my thinking, you are right
