### ISSUE TITLE
Unit tests fails if executed from a different directory than the main one

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#48328]
**Godot version:**
66f696c2c16af1d88a016cc725fd10cac79bb838

**OS/device including version:**
Fedora 34

**Issue description:**
The unit tests fails if executed in a directory different from the project root:
```
Could not load project settings.
ERROR: Could not open specified test directory.
   at: make_tests (modules/gdscript/tests/gdscript_test_runner.cpp:258)
13:17:12: Debugging has finished
```

**Steps to reproduce:**
Just execute the unit tests from a different dir than the main directory:
- `./godot.linuxbsd.tools.64 --test`
- `.godot/bin/godot.linuxbsd.tools.64 --test`

**Comment by Xrayez** [comment]
Duplicate of #45475? See my proposed solution in https://github.com/godotengine/godot/issues/45475#issuecomment-767603251.

**Comment by AndreaCatania** [comment]
I'm closing this in favor of #45475, so we can keep the focus there.
