### ISSUE TITLE
Phone vibration support

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4833]
I need a better feedback in my game for mobile version, but I didn't found a way to make the phone vibrate using vanilla Godot.
There is currently a module for Android: https://github.com/literaldumb/GodotVibrate
I think something that simple should be included in the engine.

**Comment by SuperUserNameMan** [comment]
it could be insteresting to support it on PC too since some gamepad have a rumble motor too.

**Comment by Hinsbart** [comment]
@SuperUserNameMan thanks for reminding me.
I have experimental gamepad rumble code sitting on my harddisk for several months now... need(ed) some motivation to finish it ^^

**Comment by Zylann** [comment]
I found a post about a vibration API, apparently it doesn't work on PS4 controllers https://godotengine.org/qa/15898/ps4-controller-vibration-not-working (does it mean vibration was implemented at some point?)

**Comment by Hinsbart** [comment]
Yeah, vibration for gamepads was added but not for phones

**Comment by zero2000** [comment]
Hi, I've seen that in version 3.0 has not included part of the vibration in both desktop, platform and mobile games. I do not know why since other engines do have them and apart it does not allow to generate the kinesthetic in the games and that can ruin a correct immersion of the player

**Comment by VitaZheltyakov** [comment]
Vibration is an important part of modern games. All game engines and frameworks have the ability to control vibration. So why can not this Godot?

**Comment by akien-mga** [comment]
> Vibration is an important part of modern games. All game engines and frameworks have the ability to control vibration. So why can not this Godot?

Because no contributor implemented it so far :)

**Comment by OvermindDL1** [comment]
Sounds like @VitaZheltyakov volunteered to implement it.  ^.^

_/me would like this functionality as well_

**Comment by unfa** [comment]
+1 for making it work! It'd be great for mobile games!

**Comment by VitaZheltyakov** [comment]
@OvermindDL1 , I can not implement this functionality, because I do not know Java.

**Comment by OvermindDL1** [comment]
@VitaZheltyakov Good thing Java is one of the most well documented languages of any language out (it needed it...).  ^.^

Honestly though, I'd do this (I'd do a lot) if I had the time, but I do not...  :-(

**Comment by Shin-NiL** [comment]
I think I can do that for mobile (Android at least). My question is, is it supposed to be called using the function start_joy_vibration as stated in #21870 or we need to expose a new function just for mobile?

**Comment by VitaZheltyakov** [comment]
Unity support phone vibration.
UE support phone vibration.
Construct support phone vibration.
Phaser support phone vibration.
Cocos2d support phone vibration.
Game Maker support phone vibration.
Corona support phone vibration.
Behold support phone vibration.
**Godot not support phone vibration.**
Maybe it's time to add this feature to the engine?

**Comment by groud** [comment]
@VitaZheltyakov we are waiting for your PR then ;)

**Comment by SmithJohnFirst** [comment]
@VitaZheltyakov is right. The only Godot that does not have phone vibration support

**Comment by Michael-Jalloh** [comment]
Godot is an open-source project. So I think if any of us really need it, we can implement it and then make a PR

**Comment by Michael-Jalloh** [comment]
I create a vibration module for android for godot 3.1. Want to know if its a still needed feature

**Comment by Calinou** [comment]
@Michael-Jalloh So far, it seems to be a desired feature. It'd make sense to have this in core, without requiring a third-party module. Feel free to link to your module here still :slightly_smiling_face:

**Comment by Michael-Jalloh** [comment]
Will clean it up and try and create a readme for it. The upload it to github

**Comment by Michael-Jalloh** [comment]
Android vibrate module for godot 3.1, any bugs lemme know
https://github.com/Michael-Jalloh/Vibrate

**Comment by VitaZheltyakov** [comment]
You must add this module to the main assembly as a module Google IAP

**Comment by Michael-Jalloh** [comment]
Will try and make a PR this week or next

**Comment by volzhs** [comment]
it's about time to close this pretty long waited issue. :smile: 
hang on till merged.
