### ISSUE TITLE
`export` type hint declaration is overridden by the inferred type when using `:=`

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#48349]
**Godot version:**
3.2.3

**Issue description:**
This isn't exactly a big issue (though took me 5 minutes to realise) and obviously user error, but you'd expect some kind of useful in-IDE editor warning about declaring mixed types. Maybe the inferred type is done at run-time, but you'd expect a declared type to not allow inferring.

`
export(float) var start_freeze_time:=0
`

This turns the variable into an integer.

**Comment by Calinou** [comment]
Note that this will be fixed in 4.0 since the new `@export` syntax no longer requires declaring types separately. (The 3.x `export` syntax predates static typing in GDScript, hence the duplicated type information.)
