### ISSUE TITLE
Godot 3.3 Wrong rotation pivot for bone in Skeleton2D

### ISSUE THREAD

**Issue by kyoz** [godotengine/godot#48348]
**Godot version:**
3.3 Stable

**OS/device including version:**
- MBP 2015 15"
- Artix with Runit
- Both GLES2 & GLES3

**Issue description:**
When update to Godot 3.3, all of my animation work incorrectly. It's seem bone in Skeleton2D got the wrong pivot rotation in Godot 3.3

**Steps to reproduce:**
![untitled](https://user-images.githubusercontent.com/29815830/116779859-0d08be00-aaa3-11eb-9219-60175e184200.GIF)

**Minimal reproduction project:**
[godot3.3_rotation_issue.zip](https://github.com/godotengine/godot/files/6409373/godot3.3_rotation_issue.zip)

@lawnjelly This is what i'v talk about

**Comment by lawnjelly** [comment]
Ok I'll take a look. :+1:

**Comment by lawnjelly** [comment]
I've figured out what seems to be causing the problem. If you look in the Node2D that the polys are hanging off of, it has a translate on it. The software skinning doesn't seem to like this. If you set the translate of the Node2D to 0, 0, reassign the polys to the bones, and move the polys in the editor to match up to the bone positions, then it works.

This is probably a transform I'm not taking account of as it wasn't in the test projects I had. I'll see if I can fix it.

**Comment by kyoz** [comment]
Yay, Thank you so much, @lawnjelly , now i can continue working on my project :+1:

**Comment by lawnjelly** [comment]
It is a bug, but once you know what causes it, it is workaround-able. You didn't need to rebind the bones, I just tested it, just change the translate of the Node2D and the polys.

**Comment by kyoz** [comment]
Thank @lawnjelly , Btw, i do have a small question, when creating a Scene that i need to create other instance and reuse it. Such as Mob scene for random enemy spawing. What is good position to place the Mob in the character. I do see some one put in center the scene, some put it just center to horizontal & vertical lines.

Thank you very much

**Comment by lawnjelly** [comment]
Are you meaning where to use as the origin for your character, I didn't quite follow, you mean Mob as in mob of bad guys?

I don't think it matters as far as the engine is concerned (possible it could affect culling I guess?), so I would use what works for you. For the origin of 3d characters I usually use the centre of where their feet are, I've never used 2d skinning in a game. :slightly_smiling_face:

**Comment by kyoz** [comment]
I mean
Is placing the character center the x and y axis or center of the game screen is a good practice?

Like [this guy doing](https://www.youtube.com/watch?v=BitdxlvPTy4&t=491s), i'v alway doing this way, that's why i move the Node2D, haha

**Comment by lawnjelly** [comment]
Yeah I think that is fine, I think a lot of people use the centre, especially with using a RigidBody (a lot of deciding depends on how you do physics). Whatever works in your game, there are no strict rules. :slightly_smiling_face:

**Comment by lawnjelly** [comment]
I've worked out a fix for this, just need to tweak the PR a tiny bit to work with several skeletons batched together. :+1:

**Comment by akien-mga** [comment]
Fixed by #48402.
