### ISSUE TITLE
When making a node add itself to a group via script, self is required before add_to group()

### ISSUE THREAD

**Issue by spookdogg** [godotengine/godot#4834]
**Operating system or device - Godot version:**
Windows - 2.0.3

**Issue description** (what happened, and what was expected):
when making a node add itself to a group, you need to specify self.add_to group("whatever") instead of just add_to group("whatever"), this can be confusing as usually self is implied if there is no target (or whatever you call the thing you are calling the function on) before the function

**Steps to reproduce:**
attempt to make a node add itself to a group via script, using only add_to group("whatever") instead of self.add_to group("whatever")
test node for group membership

**Comment by vnen** [comment]
I cannot reproduce this. Just `add_to_group("group")` seems to work fine (it responds `true` for `is_in_group()` and get called with `get_tree().call_group()`).

Could you provide a minimal project as a zip attachment to this issue.where this bug happens?

**Comment by spookdogg** [comment]
huh, seems to be working on my end now, was probably a human error, thanks for getting this cleared up!
