### ISSUE TITLE
ParallaxBackground offset + zoom moves layers around

### ISSUE THREAD

**Issue by tishoe** [godotengine/godot#48342]
**Godot version:**

3.3

**Issue description:**

Parallax backgrounds don't work as expected with an offset and a camera zoom level not (1,1)
Parallax Layers with scale (1,1) are positioned differently in the editor and in game:
![Screenshot_20210430_231810](https://user-images.githubusercontent.com/59572972/116769776-c49ec100-aa0c-11eb-8204-6c0ed5598726.png)
here zoom = (0.5,0.5) (expected behaviour is to be lined up with the line as in the above picture ^)
![Screenshot_20210430_231829](https://user-images.githubusercontent.com/59572972/116769782-c799b180-aa0c-11eb-89c5-dcb663bb98bb.png)

Layers move when the zoom is adjusted:
white scale = (1,1)
blue scale = (1.5,1)
orange scale = (2,1)
![WithOffset](https://user-images.githubusercontent.com/59572972/116770131-6c1cf300-aa0f-11eb-9957-efe1f6e43e1d.gif)

Expected behavior (nothing should move):
Here I removed the offset on the ParallaxBackground
![WithoutOffset](https://user-images.githubusercontent.com/59572972/116770229-e77ea480-aa0f-11eb-91b2-589b3949d4d7.gif)

This movement happens when either scroll_base_offset or the transform offset is set to a non-zero value and the zoom is adjusted.

**Minimal reproduction project:**

[ZoomWithParallax.zip](https://github.com/godotengine/godot/files/6408829/ZoomWithParallax.zip)

I managed to get the behaviour I wanted with a script overriding the _camera_moved function on ParallaxBackgrounds, but I feel like this is the behaviour most people would expect and should be the default

**Comment by tishoe** [comment]
Closing as I think this is more of a feature proposal

**Comment by rpahut** [comment]
Looks like overriding _camera_moved wouldn't be a good practice, nor it is something every user could be expected to do in the first place. There also isn't a feature proposal that I can find.
There _is_ a slim chance that there is a right way to use ParallaxBackground as it is that I simply don't understand - but otherwise I'd say this here is an unfixed bug, that is present in 3.5 and likely in later versions.
