### ISSUE TITLE
When I click play scene on Godot Mono it says "Failed to throw exception" or "Failed to build project solution"

### ISSUE THREAD

**Issue by GaminglikiwitherYT** [godotengine/godot#48356]
Hi so when ever I try and run my game it says "Failed to throw expiation" or "Failed to build project solution", let me know if you have this issue, thanks
OS:
Windows 10
Godot Version:
3.3 Stable

**Comment by Calinou** [comment]
@GaminglikiwitherYT Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by GaminglikiwitherYT** [comment]
ok thanks, so What I have to say, I have mono downloaded, and MS Build tools and .NET framework, so when I run it says "Failed to build project solution"

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
