### ISSUE TITLE
my character's clothing disappears?

### ISSUE THREAD

**Issue by mrParabol** [godotengine/godot#48357]
**Godot version:**
3.3

**OS/device including version:**
Manjaro

**Issue description:**
I have exported characters from blender in gltf format to godot. my character's clothing disappears as he gets closer and farther away from my character. What can I do?

![a1ben](https://user-images.githubusercontent.com/28789841/116794251-49a0dd80-aad4-11eb-945a-3db0cfe57bf2.png)

<details>
<summary>Caution: Nudity</summary>

![a2ben](https://user-images.githubusercontent.com/28789841/116794256-50c7eb80-aad4-11eb-940f-d2f92a809088.png)
</details>

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@mrParabol Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by mrParabol** [comment]
@Calinou  The dansci01.glb file is in the zip file:

https://disk.yandex.com.tr/d/MueVWriNZVIJEQ

thank you, very much

**Comment by mrParabol** [comment]
@Calinou  my godot project file link:

https://disk.yandex.com.tr/d/0PDhCV7yLHOwBw

**Comment by mrParabol** [comment]
The solution to the problem is in the link below.
https://github.com/KhronosGroup/glTF/issues/1976
