### ISSUE TITLE
No Code Completion For Instanced Nodes

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#4835]
**Operating system or device - Godot version:**
Linux, Godot 2.0.3

**Issue description** (what happened, and what was expected):
I just learned to instance nodes from saved scenes and I expected code completion for it but there was none.

**Steps to reproduce:**
Instance a scene and create a node from it.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
This is the same issue as #1039, so I'll close as duplicate.

**Comment by smedelyan** [comment]
It still does not work for me
**Godot version: 3.0.6**

Example project below. There's no code completion in script Main.gd
<details>
<summary>screencast gif</summary>

![screencast](https://user-images.githubusercontent.com/47334605/52360587-7b3db200-2a4d-11e9-814a-255fe1696947.gif)

</details>

[CodeCompletion.zip](https://github.com/godotengine/godot/files/2837428/CodeCompletion.zip)

**Comment by vnen** [comment]
@smedelyan this is a duplicate of an issues that's already solved, there's no point reopening this. Since your new issue is about 3.0.x, we can keep the new one open.
