### ISSUE TITLE
Make Enter Default Accept Key For"Ok", "Choose", "Create", Etc For All UI Dialogs In Editor

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#4836]
**Operating system or device - Godot version:**
Linux, Godot 2.0.2

**Issue description** (what happened, and what was expected):
It's a bit unfluid to have some UI dialogs acceptable (Ok button, Create, or Choose button) by hitting the enter key and not others. The only alternative is to tab until the button is highlighted and then hit enter.

**Steps to reproduce:**
Hit enter on some dialogs and they do nothing.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
It'd be great if you specified which dialogs don't offer this behavior (and also some that does, for comparison).

**Comment by toliaferrode** [comment]
I'll get on it, thanks!

**Comment by reduz** [comment]
for when you have the list ready, Godot has this function:

AcceptDialog::register_text_enter

just register the dialog LineEdits using this function, and the dialog will be accepted when enter is pressed. If dialogs are missing this, we must add it.

**Comment by toliaferrode** [comment]
Hey, I'll get started on the list tomorrow. Not sure how to use that
function, though. I'm not that good with C++ and have never compiled Godot.

**Comment by vnen** [comment]
@toliaferrode it's already helpful if you just make the list. Someone else can tackle the C++.

**Comment by toliaferrode** [comment]
Sorry this took me so long. Here is my preliminary list:

1. Project Manager > New Project > Browse > Open a Directory > Open button - It would be nice if after I've created a new directory and enter it I can just press enter and be done with the dialogue.

2. Project Manager > New Project > Create button - After creating your directory it would be really quick to just hit enter again here

3 Create Script for Node > .. button > Save a File > Save button - After typing your file name it would great to just hit enter and have it done

4. Create Script for Node > Create button - Again really quick to just hit enter here and be done

5. Edit Connections > Connect.. button

6. Edit Connections > Connect.. button > Please Confirm > Connect

As an aside, I think it would also be useful to show when something has a connection, much like there's an icon to show when something has a script attached to it.

7. I feel like all the Import options and their dialogues could use this enter key treatment.

I'll continue using the editor to find more. I haven't used it in awhile, just getting back into Godot, so I'm a bit rusty on the things I noticed before.

**Comment by vnen** [comment]
Thanks for taking your time looking at this.

**Comment by toliaferrode** [comment]
You're welcome, I really believe in Godot and will continue to help out. I took out my aside BTW because it has been addressed in the 2.1 beta. Thank you for making a great software.

**Comment by mhilbrunner** [comment]
All of those now seem to work in 3.0. The ones in the project manager's "Create project" dialog don't, but I'd say even from a UX standpoint those should maybe be left out anyway... you only do this once for each project and the UX should lead you to pay close attention (instead of accidentally creating the project somewhere where you didn't want it).

The shortcuts were way more important in the other cases where they now *do* work, as those are used frequently.

Maybe close this, @vnen?

**Comment by akien-mga** [comment]
As per the above comment, this seems fixed in 3.0.
