### ISSUE TITLE
Use contrasting canvas text colors when changing to a light Interface theme to make it much easier to read

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot#48373]
### Describe the project you are working on
This relates to the editor so applies for any project across Godot v3.3 / v4

### Describe the problem or limitation you are having in your project
When changing the Interface Theme to either of the following:
Light
Solarized (Light(

The magnification text on the 2D canvas shows black font color on a dark canvas making it very hard to see on the light themes.
![image](https://user-images.githubusercontent.com/8476589/116800364-c4551180-ab43-11eb-8e24-826c660dc02e.png)
![image](https://user-images.githubusercontent.com/8476589/116800368-d1720080-ab43-11eb-8dea-89849db44a83.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Make the magnification text white colour, and, preferablly provide the option to change just the canvas text color on the Interface Theme page (for v3.x branch and v4). Such as the below option highlighted in red below:
![image](https://user-images.githubusercontent.com/8476589/116800536-5f022000-ab45-11eb-9ef0-ebed9874d984.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
After changing the canvas font colour to white (as shown in mockup above), the font colour change will look like below:
![image](https://user-images.githubusercontent.com/8476589/116800500-03379700-ab45-11eb-88e3-4700e48317df.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
This should be core because it is part of the main editor.

**Comment by Calinou** [comment]
This is actually a bug, so I transferred it to the main Godot repository.

This is fixed by https://github.com/godotengine/godot/pull/42995 in `master`, but its `3.x` cherrypick was undone because it caused a crash.

**Comment by knadoor** [comment]
Okay sure, but is this expected to be fixed in v4?

**Comment by Calinou** [comment]
> Okay sure, but is this expected to be fixed in v4?

Yes, as `master` represents the current development state of Godot 4.0.

**Comment by knadoor** [comment]
> > Okay sure, but is this expected to be fixed in v4?
> 
> Yes, as `master` represents the current development state of Godot 4.0.

Sounds good :)
