### ISSUE TITLE
Android one-click deploy should ignore "Signed" export setting

### ISSUE THREAD

**Issue by vjrossi** [godotengine/godot#4837]
**Operating system or device - Godot version:**
Windows 10, Godot nightly build (but applies to 2.0.3 and earlier)

**Issue description** (what happened, and what was expected):
It's possible to attempt a one-click deploy of an unsigned APK. This doesn't ever make sense. I'd expect the "Package/Signed" option to be ignore for one-click deployment. Not a HUGE issue but consider my use case where I need to export a release unsigned APK and so I have to check/uncheck this option when going between 1-click and export.
(edit: it's true I can 're-sign' an already signed APK and I will probably take advantage of that, but I think it's still something to consider.)

**Steps to reproduce:**
Set up Godot for Android 1-click deployment
Verify that a one-click deploy with "Signed" turned ON works ok
Un-check the "Signed" setting
Perform an Android one-click deploy
Note the deploy fails (silently; the command window shows that the install failed due to no certificate):

```
Installing into device (please wait..): Google Nexus 7
running cmdline: "H:/Android/sdk/platform-tools/adb.exe" "-s" "00ea7f8d" "install" "-r" "C:\Users\med\AppData\Roaming/Godot/tmp/tmpexport.apk"
3338 KB/s (7730287 bytes in 2.261s)
        pkg: /data/local/tmp/tmpexport.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

```

**Link to minimal example project** (optional but very welcome):
Any project that can deploy to Android.

**Comment by volzhs** [comment]
I think it's because of different signing.
It' can be solved if you check ``Clear Previous Install``.
The ``Signed`` is not should be ignored I think.
But it's better show error message and guide when it happens.

**Comment by vjrossi** [comment]
I don't believe this is the case.

**Comment by reduz** [comment]
Android _needs_ a signed APK to install, be it debug or release. You must be missing a debug certificate.

**Comment by akien-mga** [comment]
As per the above comment, it seems to be a configuration issue, so closing.
