### ISSUE TITLE
Setting dtls_verify=false makes client accept any certificate

### ISSUE THREAD

**Issue by Wafflily** [godotengine/godot#48381]
**Godot version:**
3.3 stable official

**OS/device including version:**
Windows 7

**Issue description:**
I'm trying to setup dtls with NetworkedMultiplayerENet.
I'm using a self-signed certificate on the server side.
On the client side:
- if I set dtls_verify=true, the self-signed certificate is refused as invalid (error code 42), even if the client has the same certificate
- if I set dtls_verify=false, then the client doesn't even need to have a certificate on its side to accept the server. It accepts anything from the server.

**Steps to reproduce:**
Server-wise:
```gdscript
extends Node

var crypto = Crypto.new()
var server = NetworkedMultiplayerENet.new()
var cert = X509Certificate.new()
var key = CryptoKey.new()

func gen_crypto():
    key = crypto.generate_rsa(4096)
    cert = crypto.generate_self_signed_certificate(key, "CN=mydomain.com,O=Test test,C=IT")
    
func create_server() :
    get_tree().connect("network_peer_connected", self, "on_clientConnected")
    server.use_dtls = true
    server.set_dtls_key(key)
    server.set_dtls_certificate(cert)
    server.create_server(8080)
    get_tree().set_network_peer(server)
    print("Server created")

func _ready() :
    gen_crypto()
    create_server()

func on_clientConnected(id) :
    print("Client with id %d connected" %id)
```

Client-wise:

```gdscript
extends Node2D

var client

func create_client() :
    get_tree().connect("connected_to_server", self, "on_ConnectedToServer")
    client = NetworkedMultiplayerENet.new()
    client.use_dtls = true
    client.dtls_verify = false   # when set to false it accepts any certificate, when set to true it refuses self-signed certificates
    client.create_client("127.0.0.1", 8080)
    get_tree().set_network_peer(client)
    print("Client created")

func _ready():
    create_client()

func on_ConnectedToServer() :
    print("Connected to server")
```

**Minimal reproduction project:**
[Dummy Server.zip](https://github.com/godotengine/godot/files/6411192/Dummy.Server.zip)
[Dummy client.zip](https://github.com/godotengine/godot/files/6411194/Dummy.client.zip)

**Comment by Faless** [comment]
That is exactly what `dtls_verify = false` is supposed to do.
If the problem is hostname verification see godotengine/godot-proposals#1993
