### ISSUE TITLE
Console error when using TileMap bucket fill tool in editor

### ISSUE THREAD

**Issue by nebs** [godotengine/godot#48388]
**Godot version:**

v3.3.stable.official

**OS/device including version:**

Windows 10 / Desktop PC.

**Issue description:**

When using the TileMap editor bucket fill tool it prints this error in the console: 
```
Bucket Fill
 scene/gui/item_list.cpp:257 - Index p_idx = -1 is out of bounds (items.size() = 0).
```

I would expect no errors to be shown since nothing appears to be wrong visually. This error also gets printed when you move your mouse around with the bucket fill tool selected.

This "bug" doesn't affect the actual tilemap behavior but I'm reporting it because the console error might be a symptom of a deeper issue. Also I don't recall this error being printed before v3.3 so it might be a regression.

I reported another v3.3 tilemap related issue earlier: #48092. I don't know if it's related but it seems like maybe there were some tilemap related changes in 3.3 that are worth taking a look at.

**Steps to reproduce:**
1) Open the attached project
2) Make sure the "output" console tab is open/visible.
3) Select the "TileMap" node
4) Press "B" to activate bucket fill tool
5) Click in the middle of the yellow tilemap box to fill it.
6) Notice the error printed in the console.

**Minimal reproduction project:**

[TileMapBugDemo.zip](https://github.com/godotengine/godot/files/6411587/TileMapBugDemo.zip)

**Comment by kleonc** [comment]
Caused by #42979.
