### ISSUE TITLE
AudioStreamPlayer3D still playing audio while parent node is disabled in scene

### ISSUE THREAD

**Issue by chandujr** [godotengine/godot#48387]
**Godot version:**
v3.3.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
I added an AudioStreamPlayer3D node as a child to a spatial node and assigned an audio file to it. I disabled the parent node from the Scene panel, but on play the audio attached to the disabled node is still playing, which is not the expected behavior.

**Steps to reproduce:**
1. Create an empty project.
2. Attach an AudioStreamPlayer3D node to any Spatial node.
3. Disable the parent Spatial node and run the project.
4. Observe that the audio is still getting played while the object is disabled.

**Minimal reproduction project:**
[AudioPlayingOnDisabledObj.zip](https://github.com/godotengine/godot/files/6411577/AudioPlayingOnDisabledObj.zip)

**Comment by Calinou** [comment]
Hiding a node does not disable its behavior (such as collision).

**Comment by chandujr** [comment]
Yes the behavior is same for AudioStreamPlayer2D as well. I guess it makes sense, the "eye" icon clearly mentions "Toggle Visibility" but since I'm coming from a Unity background I expected the node and it's children to pause everything they do. I checked the link you mentioned and from what I understand, the feature will be there in 4.0?

**Comment by Calinou** [comment]
> I checked the link you mentioned and from what I understand, the feature will be there in 4.0?

Yes. It can't be backported to 3.x as it would break compatibility with existing projects.
