### ISSUE TITLE
Vulkan: RootMotionView's grid is not displayed

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#48389]
**Godot version:**
4.0.dev

**OS/device including version:**
MacOS 10, Win 10 with Vulkan

**Issue description:**
`RootMotionView`'s grid is not displayed in 4.0.
<img width="1211" alt="2021-05-03 0 17 13" src="https://user-images.githubusercontent.com/61938263/116818172-eb8ffb00-aba4-11eb-8826-20169a949941.png">
But it's working fine in 3.2, so is this a regression?

**Steps to reproduce:**
Add `RootMotionView` to the scene

**Minimal reproduction project:**
[reverse_root_motion.zip](https://github.com/godotengine/godot/files/6411705/reverse_root_motion.zip)

**Comment by akien-mga** [comment]
Fixed by #50014.
