### ISSUE TITLE
macOS large resource file segfault when loading lots of DynamicFonts

### ISSUE THREAD

**Issue by maksloboda** [godotengine/godot#48393]
**Godot version:** 3.2.2 6a9fbafcbbd7954761fb17554ed08fb62e3554dd (cross compiled from linux)

**OS/device including version:** macOS 11.2 (20D64) on MacBookPro11 Dual-Core Intel Core i5, 2,6 GHz, 8 GB

**Issue description:**

Loading a resource containing a Dynamic font with lots of fallbacks causes a sigsegv on Mac OS (tested on exported version).
Using a loop in gdscript to load and add fallbacks at run time has no issues.

**Steps to reproduce:**
- Create a font with a lot of unique fallbacks and save it to the file
- Make it load it in game
- Export the game and run

**Minimal reproduction project:**

[LargeFont.zip](https://github.com/godotengine/godot/files/6412078/LargeFont.zip)

**Crash log:**
[crash.log](https://github.com/godotengine/godot/files/6412085/crash.log)

Crashes also occured at FileAccessPack::seek(unsigned long) + 22
Note: crash log is from a full project as unfotunately i dont have a way to retest right now
Also crash log says stack is 12 mb but `ulimit -s` on the machine is only 8192

**Comment by Calinou** [comment]
This may be fixed on 3.3 thanks to https://github.com/godotengine/godot/pull/44160. Please test there.

**Comment by bruvzg** [comment]
With 3.3 it seems to load and run fine.
