### ISSUE TITLE
Freezing on Linux

### ISSUE THREAD

**Issue by PaytonTheMartian** [godotengine/godot#48391]
**Godot version:**
3.3

**OS/device including version:**
Arch Linux, Intel Pentium IGPU, Mesa Drivers, GLES3

**Issue description:**
When I run Godot (Project Manager, Editor, or Game), sometimes (About 50/50 chance it seems) Godot will completely freeze Xorg, and it looks like Godot is closing and opening quite fast. After a while, my screen starts to flicker, then it turns completely black with only my mouse showing. The only solution seems to be going to another TTY and using `pkill awesome` to kill AwesomeWM so I can use it again.

I think that it may be a memory leak, but I'm not sure, it's quite hard to find the source, even when I run Godot in a terminal, no errors show up, that or it just freezes Xorg before it can update to show the problem.

**Steps to reproduce:**
Open Godot a few times, eventually you (should) encounter the problem. It seems to not happen to some people,

**Minimal reproduction project:**
(This happens across all my projects)

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/27669 (possible duplicate?).

> Minimal reproduction project:
> (This happens across all my projects)

So far, the only reports about this on 3.3 are on very specific projects with complex material setups.

**Comment by DeBeast591** [comment]
`lspci | grey VGA` returns:
`00:02.0 VGA compatible controller: Intel Corporation UHF Graphics 605 (rev 03)`

> So far, the only reports about the editor freezing X11 on 3.3 are on very specific projects with complex material setups.

This bug has happened to me on 3.2 and 3.3, I didn’t use Godot on Linux for any past versions that I know of.

**Comment by p-kolacz** [comment]
I have similar problem on Intel GPU. When I switch to nVidia it works fine. It's very hard to debug, for example one of my commits "hangs" X11 on opening project (reimporting I think), but in another commit editor works (but with high CPU usage) and launching project "hangs" X11. My current suspects are EXR file and/or some textures import settings like compression. Removing EXR from WorldEnvironment->Sky solves problem when running project.

**Comment by akien-mga** [comment]
Is this still reproducible in 3.5 or 4.0?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug (with full system information listed).

**Comment by BadWolf1st** [comment]
> Is this still reproducible in 3.5 or 4.0?

Version 4.2.2
Freezes are more likely to occur when using screen capture in Discord. But at the same time, changes are visible in the screen share, as if nothing was hanging. I also noticed that (at least for me) freezes periodically occur when debugging the project.
