### ISSUE TITLE
Parent/child rendering order

### ISSUE THREAD

**Issue by SasoriOlkof** [godotengine/godot#484]
Hi, I have seen that creating a object and then his son, the son renders me over the father.
example:
	var button = Sprite.new()
	button.set_texture(load("res://button.png"))
	button.set_pos(pos)
	add_child(button)
	var deco = Sprite.new()
	deco.set_texture(load("res://deco.png"))
	deco.set_pos(Vector2(0,0))
	button.add_child(deco)

In this example, "deco" is drawn over the button, and as a son, I have no way to change it.
But if this same amount from the editor button is rendered over the deco

**Comment by bojidar-bg** [comment]
Shouldn't this issue be closed? If there is a need for rendering order... maybe open another one with better info?

**Comment by akien-mga** [comment]
Yes, according to @reduz's comment there is already a feature for the initial question (i.e. how to draw a child before its parent), and there are other issues regarding other rendering order topics (z ordering, etc.)

**Comment by SasoriOlkof** [comment]
if is for me, yes, you can close :)
