### ISSUE TITLE
Lineedit control not reporting get_combined_minimum_size() correctly

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot#4840]
**Operating system or device - Godot version:**
Using : Godot_v2.0.3_stable_x11.64 on linuxmint 17.3

**Issue description** (what happened, and what was expected):
When building __Lineedit__ control nodes from script, **get_combined_minimum_size()** mothod is not reporting correct size. For comparison __Label__ control nodes are reporting meaningfull **combined_minimum_size** value. This makes resizing **Lineedit** to encapsulate its own content as same as **Label** impossible. 

This causes problem when these items are used inside GridContainer to form columns with different widths.

**Steps to reproduce:**
Create a scene. Add a **VBoxContainer** as root node. And add script below to this VBoxContainer node.

NOTE : **Lineedit** stretches because of **VBoxContainer**, not because of its own size value in this scene. Output of last two lines show this situation.

	extends VBoxContainer

	func _ready():
		var text = 'long text to test get_combined_minimum_size() function'

		# Add a label and resize to show all content
		var label = Label.new()
		label.set_text(text)
		label.set_name('Label')
		label.set('custom_colors/font_color', Color(0,0,0,1))
		print('label size : ' + str(label.get_size()))
		print('label combined_minimum_size : ' + str(label.get_combined_minimum_size()))
		label.set_size(label.get_combined_minimum_size())
		self.add_child(label)
	
		# Add a lineedit and resize to show all content
		var lineedit = LineEdit.new()
		lineedit.set_text(text)
		lineedit.set_name('Lineedit')
		print('lineedit size : ' + str(lineedit.get_size()))
		print('lineedit combined_minimum_size : ' + str(lineedit.get_combined_minimum_size()))
		lineedit.set_size(lineedit.get_combined_minimum_size())
		self.add_child(lineedit)
	
		print('label size after add_child : ' + str(label.get_size()))
		print('lineedit size after add_child : ' + str(lineedit.get_size()))

Console Output:

	** Debug Process Started **
	label size : 0,0
	label combined_minimum_size : 324,13
	lineedit size : 0,0
	lineedit combined_minimum_size : 46,23
	label size after add_child : 324,13
	lineedit size after add_child : 46,23

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
@hubbyist ~ Does it work correctly with `get_minimum_size`?

**Comment by hubbyist** [comment]
@bojidar-bg No it is giving the same result.

	label      (gs) : 0,0
	label     (gms) : 324,13
	label    (gcms) : 324,13


	lineedit   (gs) : 0,0
	lineedit  (gms) : 46,23
	lineedit (gcms) : 46,23


	label last size : 324,13
	lineedit last size : 46,23

**Comment by reduz** [comment]
This was a result of a PR that was reverted recently, it's not happening any longer, so closing.
