### ISSUE TITLE
SamplePlayer cuts off the first sound if played twice or consecutively 

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4841]
**Operating system or device - Godot version:**
Godot_v2.0.3_stable_win64.exe

**Steps to reproduce:**
 - Create SamplePlayer Node (not 2d)
 - Add a sample library
 - Import sound effect

**Issue description** (what happened, and what was expected):

When you use `play()` twice in a row (or before the first sound is finished) -- it cuts off that sound file that was **played first**, and **starts the latest one again**.  Thus, you don't hear the entire sound of the first sound file being played... This shouldn't happen for sound effects. Each time `play` is called, the entire audio file should be played in its entirely, and consecutively (if it gets re-played again).

I submitted an issue (https://github.com/godotengine/godot/issues/4764), but it's not really similar because that was for the `StreamPlayer` class, and is doing something different then what I'm describing here. (Delay in playing, as compared to blatantly cutting off the sound file in this issue) (Although, they could be correlated)

**Comment by bojidar-bg** [comment]
@Dillybob92 ~ Have you tried increasing the `voices` or `polyphony` setting (don't remember which one exactly) of the SamplePlayer?

**Comment by Dillybob92** [comment]
@bojidar-bg Oh, yeah that fixed it. It turned up the sound by a lot though, weird.  I'll close.. sorry about this :)
