### ISSUE TITLE
No longer able to use Enter to accept autocompletion

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#48411]
**Godot version:**

eb57dcd

**Issue description:**

![ipX2mcIlW8](https://user-images.githubusercontent.com/2223172/116894191-14aa9d00-ac32-11eb-9148-10950b2c0724.gif)
Only Tab works. It's extremely confusing to type code :/

**Comment by Calinou** [comment]
This is because the autocompletion shortcut changed to be unified between the editor and running project in the `master` branch. I've seen a similar issue reported recently, but I can't find it right now.

**Comment by JulienVanelian** [comment]
![image](https://user-images.githubusercontent.com/8573006/116905788-bf758800-ac3f-11eb-95e7-de65f0c153ce.png)

Adding another key binding is still possible to have Tab and Enter work (or something else). So I guess this may not be a problem? (correct me if I'm wrong)

**Comment by Calinou** [comment]
> Adding another key binding is still possible to have Tab and Enter work (or something else). So I guess this may not be a problem? (correct me if I'm wrong)

The default should remain <kbd>Tab; Enter</kbd> as it is in Godot 3.x, because that's what most people are used to from other editors.

**Comment by BastiaanOlij** [comment]
This was annoying me to no end, never thought of checking the key bindings :)
