### ISSUE TITLE
CSG node selection in editor not working reliably

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#48419]
**Godot version:**
Godot_v3.3-stable_mono_win64

**OS/device including version:**
Win10, Nvidia 1650

**Issue description:**
Was selecting CSG Cubes in 3D editor, very hard to select them at times.

**Steps to reproduce:**
(In example project)
Left is Mesh, Right is CSG Cube.
1)In editor, click randomly to select the left (mesh) and the right(CSG). Click top, left right centre etc...
Note that CSG mesh is unselectable at times, not as responsive as the left mesh.

**Minimal reproduction project:**
http://www.filedropper.com/testcsgselect33

**Comment by Calinou** [comment]
This is an issue with 3D selection in general. The code in question needs to be rewritten from scratch for 4.0 anyway.
