### ISSUE TITLE
rid/raster errors on first run of project in 3.3

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#48433]
**Godot version:**
3.3

**OS/device including version:**
Linux mint 64

**Issue description:**
I'm sure this is benign, but on running my project for the first time on opening Godot I always get these errors and only in 3.3. On subsequent runs from within Godot it does not appear. Close Godot and reopen project and it appears again on the first run, etc.

![image](https://user-images.githubusercontent.com/12863685/116940613-1beb9e00-ac66-11eb-980c-16370b9d7a8d.png)

I have swapped back to 3.2.3 and everything is fine, there are no errors, I go back to 3.3 and it appears again on first run.

Is this ok or a sign of something wrong with 3.3 that needs more data from me?

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/48118, https://github.com/godotengine/godot/issues/38229 and https://github.com/godotengine/godot/issues/47356.

**Comment by chucklepie** [comment]
> See also #48118, #38229 and #47356. We need a minimal reproduction project here.

Can I have some pointers as to where this error might be coming from? I have a large project and it's impossible to know in code when an error statement is written as there's no means of breaking on errors...

Given it's happening elsewhere, I know it doesn't help, but it points to some issue that would help to be investigated

**Comment by tinmanjuggernaut** [comment]
You can read about it in #53374 and the fix is coming in PR #54650.

**Comment by akien-mga** [comment]
Fixed by #54650.
