### ISSUE TITLE
Number of occurrences of message doesn't update immediately in Editor Log

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#48443]
**Godot version:**

56316b2

**Issue description:**

Not sure if it only applies to properties or to everything, but
![pnmTU2P4RM](https://user-images.githubusercontent.com/2223172/116995441-5bec6880-acda-11eb-97c6-5daaa6053c25.gif)

CC @EricEzaM

**Comment by EricEzaM** [comment]
Oh this was merged 🤣 

Will look into it
