### ISSUE TITLE
Infinite error message when plugin has error in code

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#48441]
**Godot version:**

b5e4d63 (and possibly 3.3)

**Issue description:**

When you have an addon with error in code, you get this message on startup
![image](https://user-images.githubusercontent.com/2223172/116991604-137e7c00-acd5-11eb-8873-0c6c80273339.png)
The only way to get rid of this message is either fixing the error or manually deleting the plugin from `project.godot` (or somehow triggering project save). If you ignore the message, it will appear again on next startup. You can't toggle the plugin in Project Settings dialog, because it's disabled and you will get the same error when trying to enable it.

Project Settings are saved just after checking plugins (since #47385) so we should just make sure that any errored plugin gets disabled in the settings.

**Minimal reproduction project:**
[Repro.zip](https://github.com/godotengine/godot/files/6420465/Repro.zip)

**Comment by Zami77** [comment]
Made a crack at fixing this with [PR #48584](https://github.com/godotengine/godot/pull/48584). Would appreciate any feedback on it! The solution involves removing the plugin that caused the error from enabled plugins. The error message doesn't appear once it's removed from that list.
