### ISSUE TITLE
EditorLog should remember pressed buttons

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#48445]
**Godot version:**

56316b2

**Steps to reproduce:**
None of these buttons have their state remembered between sessions:
![image](https://user-images.githubusercontent.com/2223172/117002017-521b3300-ace3-11eb-9163-d0982ed1dd58.png)
We could save this as part of project's editor state. Not sure if there is a good place to store it globally.

**Comment by EricEzaM** [comment]
Ah yeah I remember this being talked about in the main PR thread but I forgot to look into it. Thanks for bringing it up
