### ISSUE TITLE
Light2D rendering inconsistent with multiple objects in GLES3 in Godot 3.3

### ISSUE THREAD

**Issue by HeroicNate** [godotengine/godot#48440]
I did not see this issue specifically listed elsewhere.

**Godot version:**
3.3

**OS/device including version:**
Windows 10, GLES3, NVIDIA GEFORCE GTX 1660 ti, driver 442.3

**Issue description:**
When using GLES3 rendering, objects interacting with light2d start to behave differently when multiple objects on screen are also interacting with the light. When you add objects, others get dim. Moving the objects around can sometimes change what dims. Overlapping objects will cause some dim ones to light up. 

This does not appear to happen in GLES2.

**Steps to reproduce:**
1. Create a 2D scene with GLES3
2. Add light2d
3. Add a sprite with normal map
4. Duplicate the sprite node several times
5. Move the objects around, overlapping them at times, and watch how the light changes on the objects. 

**Minimal reproduction project:**
[2D_Light_Problem.zip](https://github.com/godotengine/godot/files/6419280/2D_Light_Problem.zip)

https://user-images.githubusercontent.com/229208/116967145-aab8e480-ac7f-11eb-90c9-c174683bfdc3.mp4

**Comment by lawnjelly** [comment]
This appears already fixed since 3.3 stable. It occurs in 3.3 stable for me but not in the latest build. Not sure which PR fixed it.

We could leave this open for reference possibly.

**Comment by akien-mga** [comment]
> Not sure which PR fixed it.

@lawnjelly Probably #48151?

**Comment by lawnjelly** [comment]
Yup could be, I made 2 or 3 fixes since stable, no need to spend time tracking it down as long as it is fixed I think. :+1:

**Comment by akien-mga** [comment]
3.3.1 RC 1 is published and includes a fix for this issue, so closing.
