### ISSUE TITLE
Single and Multiple Collision Siblings issues

### ISSUE THREAD

**Issue by Mercadud** [godotengine/godot#48468]
possible duplicate : #41522

**Godot version:**
Godot 3.3 stable

**OS/device including version:**
rx5700 xt
Kernel Version: 5.12.0-1-MANJARO
GLES3

**Issue description:**
When Meshes create single convex collision siblings, Godot adds a TON of points to the collision shape, when it shouldn't
But clicking 'create multiple convex collision siblings' reduces the amount of points tremendously even though it still only creates 1 collision shape anyways.

side note: both of them show errors in the output

**Steps to reproduce:**
Import model (should have at least a couple vertices)
create either the single or multiple convex collision sibling

**Minimal reproduction project:**
[MeshThing Issue.zip](https://github.com/godotengine/godot/files/6424879/MeshThing.Issue.zip)

edit: It may be because the object has a lot of vertices

**Comment by Calinou** [comment]
> edit: It may be because the object has a lot of vertices

I would recommend using a simplified version of the original mesh for convex shape generation.

**Comment by Mercadud** [comment]
Yes, I noticed that it's fine using simpler meshes with less vertices.

Quick question: if you create a collision shape with both the single and multiple version and they both end up making a single shape, are they supposed to act the same way?

**Comment by Calinou** [comment]
> Quick question: if you create a collision shape with both the single and multiple version and they both end up making a single shape, are they supposed to act the same way?

No, as they use different generators (Quickhull for a single shape, VHACD for multiple shapes).

**Comment by pouleyKetchoupp** [comment]
#48907 would help with this case by removing duplicate vertices, although it would still create a convex hull with several hundreds of vertices.

The multi-convex algorithm which uses VHACD works better for simplifying meshes, so in the single convex case, I wonder if we could:
-First do a pass with VHACD
-If several convex hulls are generated, gather all vertices together and do a second pass with QuickHull (replaced with Bullet's convex hull generator in 3.4)
