### ISSUE TITLE
Proper one way collision for slopes

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#4846]
This is a small reminder:
One way collisions work fine as long as the platform has no slope. As soon as the platform has a slope and you want to run up, you fall through. Here is a small video demonstrating the problem.

@reduz we discussed about making the one way vector relative to surface normal I think.

https://www.dropbox.com/s/m8qwwc5jhhcepx5/one_way_collision_bug.avi?dl=0

**Comment by reduz** [comment]
I'm not sure how to fix this without severely breaking compatibility. If you can wait a little after 2.1, I think what I will do is just remove this feature and re-add it in shapes instead of bodies. This should also allow to have tilemaps with one-way collision tiles

**Comment by ndee85** [comment]
@reduz 
So this would mean we will have a complete separate collision shape for oneway collisions? Sounds good to me :+1:

**Comment by reduz** [comment]
this was done for 3.0, finally, sorry for the long wait!
closing

**Comment by Razzlegames** [comment]
Hehe.  I just made a raycast that would set a collision exception on "OneWayStaticBodies" and some bottom ray casts that auto re-enabled. I'll have to check out 3.0 soon :)

**Comment by nmearl** [comment]
This still doesn't seem to be fixed. Adding a platform with a `StaticBody2D`, a `CollisionShape2D` with a `RectangleShape2D` and one-way enabled still has my `KinematicBody2D` falling through.

https://www.dropbox.com/s/cndawsl8pcrj2qv/Screencast%20from%202018-05-08%2017.34.42.webm?dl=0
