### ISSUE TITLE
Editor Froze

### ISSUE THREAD

**Issue by newtothiscommunity** [godotengine/godot#48470]
**Godot version:**
3.3

**Issue description:**
So, I'm working on a project and I have a scene in which I have other scenes of my map parts. This is pretty dumb of me and I wouldn't do it now, but anyway I put my second world map into this scene so I could try and test my transitions. I didn't actually need to put it in to test it, but I wanted to see what bugs would form from having two-player characters in one scene. Long story short, I started the game ended up on the wrong character. I closed the game, and my editor stopped working. I could move it around, close it, minimize it, do normal stuff on my computer, but I can't interact with the actual editor. I've tried closing Godot and reopening it, restarting my computer, nothing works. Any ideas for how to fix this?

Edit: Just tried uninstalling Godot and redownloading it. As expected, it did nothing. Also, found some new information. I can interact with it. Since World.tscn in the main scene, it automatically loads. I get an error message since I deleted the scene file of the second world scene I put into it. (was testing something, bad idea.) I can click ok, but can't click anything else. If I click the delete key it creates a prompt to delete the main node for that scene. If I press okay it's gone, it updates, but I still can't click anything. I can press ctrl-z to undo that, that works, but I can't interact with anything else. Very strange.

**Comment by akien-mga** [comment]
> Godot version:
2

Please be more specific. This number spans more than 4 years of development.

Also, any reason why you're using Godot 2 instead of latest Godot 3.3? We're unlikely to be able to fix issues in such old versions of Godot.

**Comment by newtothiscommunity** [comment]
> Also, any reason why you're using Godot 2 instead of latest Godot 3.3? We're unlikely to be able to fix issues in such old versions of Godot.
> Finally, it sounds like you're just having an error in the debugger, which pauses the game execution?



My bad, I am using 3.3. That was a major typo. Also, I don't think it's just in the debugger, because I can't access anything. The game is closed, everything is closed but the actual editor and I can't click anything. I can't even see the debugger.

**Comment by Zireael07** [comment]
Your OS, your video driver? (I seem to remember e.g. Intel cards updating one or two frames late, so not seeming to do anything)

Also you could try locating your project/editor settings and nuking them in case they got corrupted (I remember someone getting an empty Godot window due to corrupt/wrong settings)

**Comment by newtothiscommunity** [comment]
> Also you could try locating your project/editor settings and nuking them in case they got corrupted (I remember someone getting an empty Godot window due to corrupt/wrong settings)

how would I nuke them?

**Comment by newtothiscommunity** [comment]
Decided to record a video showing my issue. Please ignore my inability to talk to someone who isn't there.


https://user-images.githubusercontent.com/83686116/117192592-278eb000-ad9f-11eb-9a37-4400f6edc5a1.mp4

**Comment by Calinou** [comment]
@newtothiscommunity Can you still reproduce this issue on Godot 3.4 (or 3.4.1RC1)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
