### ISSUE TITLE
Importing multiple animation tracks not working for GLB files

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot#48493]
**Godot version:**

Godot_v3.2.3-stable_win64 and Godot_v3.3-stable_win64

**OS/device including version:**

Windows 10, Intel i7-10700KF CPU, RTX3060 GPU, 32GB RAM

**Issue description:**

When importing a GLB file, adding multiple animation clips during import isn't working. Tested with multiple files, all coming from Blender. I can increase the number of clips, name them and set the frames, but when clicking reimport Godot keeps only one single animation containing all keyframes. Switching between built in animations or separate files doesn't make a difference.

**Steps to reproduce:**
Download the attached project, and open the GLB file inside the editor. Notice how there is only one animation, even though in the import settings I've clearly defined two separate clips.

**Minimal reproduction project:**

[Animation Import Bug.zip](https://github.com/godotengine/godot/files/6430529/Animation.Import.Bug.zip)

*Bugsquad edit (keywords for easier searching): glTF*

**Comment by Calinou** [comment]
Possible duplicate of https://github.com/godotengine/godot/issues/45418?

**Comment by robbertzzz** [comment]
@Calinou Oh yeah I think it is. Didn't come across that one when searching if it was reported yet. I'll close this one.

**Comment by djmaesen** [comment]
still doesnt work in godot3.4.2

**Comment by Calinou** [comment]
> still doesnt work in godot3.4.2

This is already being tracked in https://github.com/godotengine/godot/issues/45418. Please continue the discussion there :slightly_smiling_face:
