### ISSUE TITLE
Particles2D & CPUParticles2D Color messed

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#48506]
**Godot version:**

3.3 stable

**OS/device including version:**

windows 10 x64
AMD R7 200 series

**Issue description:**

When the user changes a color from the particles, and later change to Gradient texture, things messes up!

https://imgur.com/zaBTRa1

**Steps to reproduce:**
* Create a particle2d or CpuParticle
* Change color to another (Red for example)
* Now create a GradientColor
* change the colors, and it will still remain with the old one (Red)

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
It seems the **Color** property disappears in the inspector once you switch nodes? Maybe something is hiding this property when it shouldn't.

**Comment by nonunknown** [comment]
Yeah, the solution can be 2 things:

* Doesn't hide color property
* When user create a gradient texture, set the Color property back to white (or ignore it)

**Comment by Calinou** [comment]
> When user create a gradient texture, set the Color property back to white (or ignore it)

The color ramp is *multiplied* by the base color – that's intended behavior. I wouldn't ignore the base color when a color ramp is set.

**Comment by nonunknown** [comment]
hmm, so just not hide it then.

**Comment by nonunknown** [comment]
There is a regression for this one in 4.0! 

version: v4.0.dev.custom_build [bf322bacd]

steps: 

https://user-images.githubusercontent.com/58845030/137516257-5105953c-6db3-47ca-9ee6-ab78a2d9231f.mp4

**Comment by Calinou** [comment]
@nonunknown Try saving the scene then reloading it. There's a known issue with textures not being read immediately after being set in `master` (it's already reported).
