### ISSUE TITLE
Can't input mandarin characters on linux

### ISSUE THREAD

**Issue by likeich** [godotengine/godot#48516]
**Godot version:**

3.3

**OS/device including version:**

Pop OS 20.10 -Debian Linux

**Issue description:**

I'm unable to type Chinese (Mandarin) characters into Godot (labels, scripts, etc.). This is definitely an input issue because copying and pasting the same characters works. I've tested on Windows as well under wine and input works fine there. Godot 4.0 on Linux works as expected as well. These all work under default conditions in an empty project. I have also tested with different project and editor fonts that support Mandarin, no settings work. Exported projects on Linux do not work as well, but they do on my Android phone.

**Steps to reproduce:**
Open a new script in a new project in Godot 3.3 on Linux. Type in Chinese using the Linux Chinese (Intelligent Pinyin) setting. Watch nothing happen at all when the text is entered.

**Minimal reproduction project:**
N/A

If someone could point me in the right direction I could potentially fix this issue myself but I don't know where to look for the input code right now.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Try using artifacts from the #46764 PR (this is the backport of the big input change between 3.3 and 4.0).

**Comment by likeich** [comment]
@bruvzg Yup! That fixes it.

**Comment by akien-mga** [comment]
Fixed by #46764.
