### ISSUE TITLE
OS.get_window_size().height appears to be longer than actual window height

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#4851]
For a window height of 600 OS.get_window_size().height returns 622

To me it seems like the height component of the Vector2 window  size adds the border height again. Because on OSX the window height includes the 22 pixels for the border.

Maybe I'm thinking could be that Godot wanted to allocate 622 pixels for the window to be 1024 x 600 as defined in the settings ? Because right now on OSX a window height of 600 has only 578 height since border occupies the other 22 pixels. But then again the window 0,0 begins just above the border so my guess is the height is calculated wrongly. 

Might be an OSX specific issue.

![screen shot 2016-05-27 at 8 08 41 pm](https://cloud.githubusercontent.com/assets/6987027/15623802/3a47c3e4-2447-11e6-8ded-355126d58c04.png)

**Comment by RebelliousX** [comment]
I used to have this issue when programming win32 apps in C++. I solve them by using ClientToScreen() and ScreenToClient() functions for windows.

Maybe OS.get_window_size() should return the client rect area to be safe.

**Comment by reduz** [comment]
yeah, the border should not be added though, I remember checking this.. will give it another look

**Comment by AfterRebelion** [comment]
This works correctly on Windows, and I don't have a Mac for testing.
Seems to have been fixed by 38de4d2 on the Godot 3 branch, and backported to 2.1 on fd6f62f , but someone needs to confirm.

**Comment by akien-mga** [comment]
I think we can safely assume that it's fixed by the mentioned commits, since no other Mac user reported a similar issue since then.
