### ISSUE TITLE
Moving Documentation Crash

### ISSUE THREAD

**Issue by Animezingamer** [godotengine/godot#48519]
In Godot, you can drag and drop/reorganize many features in the engine. When I tried to do this to organize my "Open Documents" section (the tabs of info that explain what the nodes are and their function), the whole engine crashed. I did this many times after to test it, and the results were the same every time. I loss about 2 minutes worth of tinkering on an idea because nothing was saved, so no be loss on my end, but I thought it should be pointed out before it happens to somebody else.

**Comment by pycbouh** [comment]
Please use the issue template so that we can actually help you. The information outlined there is required for every reported problem. And don’t forget to provide a reproduction project, if applicable.

This issue will be reopened when you update your message.
