### ISSUE TITLE
Upgrade from file format 1.1 to 2.0 causes load error for BitMap ext_resources

### ISSUE THREAD

**Issue by DaddySmash** [godotengine/godot#4853]
**Operating system or device - Godot version:**
OpenSUSE Tumbleweed Steam BuildID 1126922
Windows 7 Pro 64bit Steam BuildID 1126922
Godot Version 2.0.3

**Issue description** (what happened, and what was expected):
When upgrading our game from Godot 1.1 to Godot 2.0.3, the game launches, but gameplay fails.  The only file that was changed to perform the fix was app/scene/zombiesGoTomb.xscn.

**Steps to reproduce:**
Download the game from https://github.com/DaddySmash/GraphicsGame, and revert to right before the commit "fixed godot upgrade glitch with only 2 .png files", then run the game from Godot 2.0.3 Steam BuildID 1126922.  Then click one of the tombstones with a head on it to start a level.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
When reverting to the commit before your fix (5e5cecc), I get:
```
ERROR: load: No loader found for resource: res://visual/clickArea.png
   At: core/io/resource_loader.cpp:218.
ERROR: poll: res://scene/zombiesGoTomb.xscn:15: <ext_resource> referenced nonexistent resource at: res://visual/clickArea.png
   At: core/io/resource_format_xml.cpp:1448.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://scene/zombiesGoTomb.xscn
   At: core/io/resource_loader.cpp:218.
```

With this diff, the game works fine:
```
$ git diff
diff --git a/app/scene/zombiesGoTomb.xscn b/app/scene/zombiesGoTomb.xscn
index 022ca43..8c6b258 100644
--- a/app/scene/zombiesGoTomb.xscn
+++ b/app/scene/zombiesGoTomb.xscn
@@ -12,8 +12,8 @@
        <ext_resource path="res://visual/zombieHat.png" type="Texture"></ext_resource>
        <ext_resource path="res://visual/zombieHatHead.png" type="Texture"></ext_resource>
        <ext_resource path="res://visual/zombieHatBody.png" type="Texture"></ext_resource>
-       <ext_resource path="res://visual/clickArea.png" type="BitMap"></ext_resource>
-       <ext_resource path="res://visual/clickAreaTomb.png" type="BitMap"></ext_resource>
+       <ext_resource path="res://visual/clickArea.png" type="Texture"></ext_resource>
+       <ext_resource path="res://visual/clickAreaTomb.png" type="Texture"></ext_resource>
        <ext_resource path="res://visual/frontHole.png" type="Texture"></ext_resource>
        <ext_resource path="res://visual/rubbleHole.png" type="Texture"></ext_resource>
        <ext_resource path="res://code/hatHeadThrown.gd" type="Script"></ext_resource>
```

@reduz Any idea why external resources from 1.1 of BitMap type can't be loaded properly in 2.0+?

**Comment by reduz** [comment]
sorry, there is no fix for this, both sharing the png extension was causing a lot of trouble. If you are using XML, an easy fix is to convert all the png files to pbm, then replace the files for their pbm counterparts.

**Comment by reduz** [comment]
oh keep in mind that pbm is black and white, you need to convert the png files to use black or white, and this will be the mask
