### ISSUE TITLE
VisualServer mesh rendering broken in C#

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#48554]
**Godot version:**
3.3 Mono as well as 4.0 Master (as of today)

**OS/device including version:**
Windows 10

**Issue description:**
Rendering meshes with VisualServer (and RenderingServer in 4.0) directly just doesn't seem to be working.

**Steps to reproduce:**
This works in 3.3 Mono
```swift
extends Spatial

var mesh = CubeMesh.new()

func _ready() -> void:
	print("mesh created")

	var instance = VisualServer.instance_create()
	var scenario = get_world().scenario

	VisualServer.instance_set_scenario(instance, scenario)
	VisualServer.instance_set_base(instance, mesh.get_rid())

	var xform = Transform(Basis(), Vector3(0, 0, 0))
	
	VisualServer.instance_set_transform(instance, xform)

```
While this does not work.
```csharp
public class Spatial : Godot.Spatial
{
    CubeMesh mesh = new CubeMesh();

    public override void _Ready()
    {
        GD.Print("Mesh Created!");

        var instance = VisualServer.InstanceCreate();
        var scenario = GetWorld().Scenario;
        
        VisualServer.InstanceSetScenario(instance, scenario);
        VisualServer.InstanceSetBase(instance, mesh.GetRid());

        Transform xform = new Transform(new Basis(), new Vector3(0f, 0f, 0f));

        VisualServer.InstanceSetTransform(instance, xform);
    }
}
```
it is exactly the same, logic-wise.
There is no error being printed or anything, the mesh just doesn't show up.

**Comment by Byteron** [comment]
tagging @neikeq since you are our C# expert.

**Comment by Byteron** [comment]
I have more info on this. It seems to have to do with C# Transforms.
This works, the mesh shows up at 0, 0, 0
```csharp
private void RunMesh()
{   
    GD.Print("Mesh Created!");

    RID instance = RenderingServer.InstanceCreate();
    RID scenario = _parent.GetWorld3d().Scenario;

    RenderingServer.InstanceSetScenario(instance, scenario);
    RenderingServer.InstanceSetBase(instance, mesh.GetRid());
    // RenderingServer.InstanceSetTransform(instance, new Transform(new Basis(), new Vector3(0f, 0f, 0f)));
}
```
however as soon as I uncomment the InstanceSetTransform line, the mesh disappears.

I also tried to wrap the call into a gdscript.
this works
```csharp
renderScript.Call("instance_set_transform", instance, new Vector3(0f, 10f, 0f));
```
```swift
func instance_set_transform(instance, origin):
	print("instance_set_transform")
	RenderingServer.instance_set_transform(instance, Transform(Basis(), origin))
```
while this does not work
```csharp
renderScript.Call("instance_set_transform", instance, new Transform(new Basis(), new Vector3(0f, 10f, 0f)));
```
```swift
func instance_set_transform(instance, transform):
	print("instance_set_transform")
	RenderingServer.instance_set_transform(instance, transform)
```

**Comment by kleonc** [comment]
No bug in here. What causes your issue is you're using `new Basis()` instead of `Basis.Identity`. [In C# struct's default constructor can't be overriden and it initializes each member with the deafult value](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#limitations-with-the-design-of-a-structure-type). So the problem is that basis vectors are initialized to (0, 0, 0) and thus nothing can be seen.

https://github.com/godotengine/godot/blob/871d067aa9f988e69b860887cceebd243011da06/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs#L676-L682

**Comment by neikeq** [comment]
I can't confirm from my phone if this is the reason, but you could try replacing `new Basis()` with `Basis.Identity`. In GDScript the parameterless constructor initializes the values to Identity, but C# doesn't allow to change the parameterless constructor of a struct so the default values are zero.

**Comment by Byteron** [comment]
Huh. With `Basis.Identity`, it works indeed. Thanks a lot!
I guess that means I can close this issue again.

**Comment by neikeq** [comment]
I didn't notice @kleonc had already commented the same thing before me 😅
