### ISSUE TITLE
Tab doesn't have border in new editor theme when using non default theme border size

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#48552]
**Godot version:**
4.0.dev.custom_build. ee44982c4

CC @Calinou 

Ubuntu 20.04

**Issue description:**
Tabs in new editor theme doesn't have left border
Full size
![1](https://user-images.githubusercontent.com/41945903/117531658-e2a78b00-afe3-11eb-9407-0efc3135c289.png)
Zoom
![2](https://user-images.githubusercontent.com/41945903/117531668-eb985c80-afe3-11eb-8a2e-15ee1134ec53.png)

**Comment by Calinou** [comment]
I'm not sure if this can be fixed. StyleBoxFlat does not allow for per-border *colors* (only per-border widths). The only way to fix this would be to remove the top highlight would have when the border width is greater than 0, and that's a great loss.

**Comment by KoBeWi** [comment]
I don't see this issue in bb73daf
![image](https://user-images.githubusercontent.com/2223172/167229704-eb052551-842d-4a5a-8a6a-d4169bd39430.png)
Does it depend on resolution/scale?

**Comment by qarmin** [comment]
I rarely use non default editor settings, but looks that I accidentally(or when testing something) changed some, so this is not default behavior.

To reproduce issue only setting theme border is required(line from editor-settings-4.tres)
```
interface/theme/border_size = 2
```

**Comment by Calinou** [comment]
I can still reproduce the original issue as of 4.0.alpha 1839cae8a:

![image](https://user-images.githubusercontent.com/180032/182505370-24b6f61f-5200-4727-a54a-d42d516966e3.png)
