### ISSUE TITLE
Warnings when upload to google play (Java/Kotlin code obfuscated and not uploaded debug symbols) 

### ISSUE THREAD

**Issue by komputerboy** [godotengine/godot#48553]
**Godot version:**

Version 3.3

**OS/device including version:**

OS Windows, Export Android Custom Build, GLES3

**Issue description:**

Hi,
I upload my game in google play console, but there are 2 warnings, which is:

```
Warning
This App Bundle contains Java/Kotlin code, which might be obfuscated. We recommend you upload a deobfuscation file to make your crashes and ANRs easier to analyze and debug

Warning
This App Bundle contains native code, and you've not uploaded debug symbols. We recommend you upload a symbol file to make your crashes and ANRs easier to analyze and debug
How to fix these? Thank you
```
but no error only warning, and google play upload successfully.

**Comment by Calinou** [comment]
This is expected. Google tells you that you should upload the deobfuscation tables to get useful crash stack traces from users. Otherwise, stack traces will mean nothing when you read them back.

**Comment by m-melis** [comment]
Looking forward to Godot implementing this.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1342, as this depends on official builds with debug symbols being provided first.
