### ISSUE TITLE
BoneAttachment does not follow bone transform exactly

### ISSUE THREAD

**Issue by mrzapp** [godotengine/godot#48556]
**Godot version:**
3.3.stable

**OS/device including version:**
Fedora 33

**Issue description:**
When assigning a BoneAttachment to a bone, the transform of the BoneAttachment does not match the transform of the bone as it appears in the animation editor, it is scaled, rotated and translated slightly.

This makes it unusable for characters holding items and aiming weapons, for which it should be perfect on paper.

A temporary fix is to just mimic the intended behaviour, with some fixes:

```gdscript
var index : int = $Skeleton.find_bone("equipment")
var transform : Transform = $Skeleton.get_bone_global_pose(index)

$Skeleton/EquipmentSlot.set_transform(transform)

$Skeleton/EquipmentSlot.scale = Vector3.ONE
$Skeleton/EquipmentSlot.rotation = Vector3.ZERO
```

**Steps to reproduce:**
1. Import an animation
2. Create a BoneAttachment
3. Play the animation once
4. Compare the transform of the BoneAttachment to the keyframe of the target bone. There will be a slight difference.

**Screenshots**

The scale of the keyframe is `1,1,1`, but the BoneAttachment is not

![image](https://user-images.githubusercontent.com/2747428/117543168-f7077a00-b01b-11eb-922a-9d769f8107d6.png)

![image](https://user-images.githubusercontent.com/2747428/117543214-228a6480-b01c-11eb-8ae8-af48c20240b9.png)

**Comment by pouleyKetchoupp** [comment]
Could you please add a reproduction project? It would make this issue much easier to investigate. It doesn't have to have your character model, but at least the skeleton would help.

**Comment by josefkaragoli** [comment]
BoneAttatchment is getting refactored and rehauled in 4.0 as part of TwistedTwigleg's GSOC 2020 program. See https://github.com/godotengine/godot/pull/39353

**Comment by mrzapp** [comment]
Alright, I'll close this, then :) Not a dealbreaker anyway, since there is a workaround.
