### ISSUE TITLE
Popupmenu cannot be click when in popup and under other control node

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#48569]
**Godot version:**
3.3

**OS/device including version:**
windows 10 professional

**Issue description:**
When in a popup node tree, Popupmenu cannot be click if there is another control node above it

**Steps to reproduce:**
Add a popup then add 2 optionbutton under it,  let the second one below in the tree

**Minimal reproduction project:**
[PopupMenuBug.zip](https://github.com/godotengine/godot/files/6446845/PopupMenuBug.zip)

**Comment by kleonc** [comment]
Duplicate of #46325.

**Comment by Calinou** [comment]
Closing per @kleonc's comment.
