### ISSUE TITLE
MenuButton receives hotkeys expected by other MenuButtons

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#4856]
**Godot version:**
2.0.3

**Issue description** (what happened, and what was expected):
`MenuButton` is receiving hotkeys (via `_unhandled_input`) that should be received by other `MenuButton`s.

**Steps to reproduce:**
The best way to reproduce the problem is by testing #4848. This PR makes `MenuButton` accept the events when used. This way a event won't be used more than once by `MenuButton`.
Open the shader editor and focus the 2D editor (with the shader editor still visible). Pressing <kbd>CTRL+F</kbd> will result in a search dialog for the shader editor instead of the expected _Frame Selection_ in the 2D editor (since the later is focused).
Without #4848, that hotkey would result in both _Frame Selection_ in the 2D editor and a search dialog in the shader editor.

**Comment by reduz** [comment]
problem is that some menus show the binding but actually don't do anything becaue shorcut is implemented manually in a more "global" way, ideally you should make sure to not put the same thing more than once

**Comment by reduz** [comment]
This was fixed recently via ba5bc57816999804e3c392e9d1f94b528baa8c18

**Comment by neikeq** [comment]
The above commit fixes #5174 not this issue not #4848

**Comment by neikeq** [comment]
> ideally you should make sure to not put the same thing more than once
> @reduz

I think it's a fair solution. What do we do with `Search` and `Frame Selection` which use the same shortcut?

**Comment by reduz** [comment]
the case for Ctrl-F I think should be avoided by simply changing the hotkey. I think stopping propagation in MenuButtons is pointless, as you might never really know the order and priorities of them

**Comment by reduz** [comment]
we can use shift-f for frame selection
