### ISSUE TITLE
Vulkan: Lines have more washed out colors in the 3D editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#48573]
**Godot version:** 3.3, `master` Git 7050e4d3077c278bda35d21ed60d7068cc4bc9e9

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 465.27)

**Issue description:**

Lines have more washed out colors in the 3D editor, regardless of tonemapping settings.

The axis colors themselves are identical. Notice how the rotation gizmo in the top-right corner has the same colors on both 3.3 and `master`.

I'm not sure what's the cause of this – maybe sRGB conversions in the line drawing or rendering code?

Both screenshots below use linear tonemapping, yet lines in Vulkan are brighter:

![2021-05-09_10 56 06](https://user-images.githubusercontent.com/180032/117566232-b5c3a880-b0b5-11eb-9e9e-272c087830ea.png)

**Steps to reproduce:**

- In `3.x`, open the 3D editor, click the **View** in the top-left corner of the viewport then uncheck **View Environment**.
- In `master`, open the 3D editor and click the WorldEnvironment icon at the top of the 3D editor to disable the environment preview;

**Minimal reproduction project:** N/A

**Comment by mbrlabs** [comment]
Probably related to this: https://github.com/godotengine/godot/issues/44425
