### ISSUE TITLE
UI elements sometimes go over panels' focus highlight outlines

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#48575]
**Godot version:**

Godot 4.0 master

**OS/device including version:**
Windows 10, Vulkan.

**Issue description:**

A few examples of this behaviour:
![immagine](https://user-images.githubusercontent.com/19392104/117567230-92036100-b0bb-11eb-9f14-01581d95deff.png)
![immagine](https://user-images.githubusercontent.com/19392104/117567355-456c5580-b0bc-11eb-997a-ba067c538528.png)

Category labels and entries' text overlap the highlight outlines.

**Steps to reproduce:**
Open Project Settings or Editor Settings, click on an entry in the Tree on the left and scroll a bit.

**Comment by Calinou** [comment]
This is not a problem with the new theme, it's been around for a while. It's just that the new thicker focus outlines make it more obvious :slightly_smiling_face:

**Comment by samdze** [comment]
Alright, leaving another example, resource previews in the inspector:
![immagine](https://user-images.githubusercontent.com/19392104/117567679-697c6680-b0bd-11eb-9acd-59eb644c08f4.png)
