### ISSUE TITLE
Can't open encrypted files with get_unique_id as key

### ISSUE THREAD

**Issue by ICatRegister** [godotengine/godot#48576]
**Godot version:**
3.2.3, 3.3

**OS/device including version:**
Windows 10 20H2

**Issue description:**
The file created six months ago with open_encrypted_with_pass with get_unique_id as the key can no longer be decrypted.

**ERROR**: The MD5 sum of the decrypted file does not match the expected value. It could be that the file is corrupt, or that the provided decryption key is invalid.
   At: core/io/file_access_encrypted.cpp:97:open_and_parse() - Condition "String::md5(hash) != String::md5(md5d)" is true. Returned: ERR_FILE_CORRUPT
**ERROR**: File must be opened before use.

The hardware on the laptop hasn't changed since then, but there has been a major system upgrade to version 20H2. 
Perhaps [this ](https://www.pcreview.co.uk/threads/what-hardware-affects-getcurrenthwprofile.3155742/)can clarify what is happening.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is always an issue when relying on hardware/OS-reported IDs for encryption. There may not even be a way to recover the data if you can't get the old ID…

**Comment by ICatRegister** [comment]
Then what is the point of using such an unpredictable API? Even a software update can break it

**Comment by Calinou** [comment]
> Then what is the point of using such an unpredictable API? Even a software update can break it

Hardware IDs can be useful for analytics purposes, but I would not rely on them for anything that needs to remain in working state in the long term.

Also, do you really want to break users' save games when they upgrade their hardware, reinstall their OS or switch to another OS? :slightly_smiling_face:

**Comment by akien-mga** [comment]
I think we do advertise using `OS.get_unique_id()` as encryption key, so we should update documentation to warn against the fact that while this will be a unique key, it can change with hardware or OS upgrades.

**Comment by Calinou** [comment]
> I think we do advertise using `OS.get_unique_id()` as encryption key, so we should update documentation to warn against the fact that while this will be a unique key, it can change with hardware or OS upgrades.

I don't see such a recommendation in the class reference: https://github.com/godotengine/godot/blob/7050e4d3077c278bda35d21ed60d7068cc4bc9e9/doc/classes/OS.xml#L346-L353

This was indeed a recommendation in the now-removed Encrypting save games documentation page. That page needs a complete rewrite before it can be readded anyway.
