### ISSUE TITLE
"Auto" display scale on portrait vs landscape monitors is too large

### ISSUE THREAD

**Issue by lewiji** [godotengine/godot#48585]
Possibly related: #48226, godotengine/godot-proposals#2661

**Godot version:**
3.3 stable

**OS/device including version:**
Arch Linux, 5.11 kernel, KDE Plasma (global scaling off/100%). Nvidia proprietary drivers. I have 2 "2K" 2560x1440 monitors, the secondary of which is rotated 90 degrees to portrait orientation (I prefer editing code this way, more vertical space).

**Issue description:**
With `interface/editor/display_scale` set to "Auto" in the editor settings, if the Godot editor launches on my primary, landscape monitor, it correctly sets the display scale to 100%.

However, if it launches on my secondary (which can often happen by "accident" with various KDE settings and tiling window managers for example), it instead sets the UI scale to 150%, and this also causes the Godot window to stretch beyond the boundaries of my second monitor and "leak" into the first monitor.

It's a little tricky to see with screenshots alone, but here's the comparison (warning high res images and an eye-bleeding psychedelic wallpaper):

This is the editor, launched on the primary, landscape 2560x1440 monitor, then moved to secondary monitor for comparison, with the correctly applied 100% UI scale:

[godot-100-on-portrait](https://user-images.githubusercontent.com/233380/117575174-8f633480-b0d8-11eb-9a51-5485aa4269ae.png)

And here is Godot launched on secondary portrait monitor, 1440x2560, incorrect 150% auto scale detected. In addition, the left edge of window cuts into the primary monitor (you can see the taskbar on the primary monitor floating above the Godot window for example - the taskbar ends at the right edge of the left screen. This is much clearer to see on the monitors themselves, so let me know if a photo would be helpful). Additionally, the Godot window width can't be shrunk any further and won't fit on the portrait screen at this scale.

[godot-150-portrait](https://user-images.githubusercontent.com/233380/117575196-b28de400-b0d8-11eb-897a-680460ea02ea.png)

Actually the scaling doesn't look all that bad in the screenshot, but on the monitor itself (27") it's way too space consuming, and the edge "leaking" makes it unworkable.

Of course, this can entirely be fixed by manually setting the display scale to 100%, which is what I've done for a while now, but I just saw it happen again on a build with self contained config and thought to report it after searching the issues for relevant keywords :)

I haven't checked the editor code yet, but I suspect that it's looking to see if the monitor resolution height dimension is greater than a particular breakpoint to apply the relevant scaling. If that's the case, it should be checking the breakpoint against the smaller of the 2 dimensions (the smaller of either width *or* height) to get an accurate read.

**Comment by Calinou** [comment]
We can probably fix this by picking the smallest screen dimension instead of only relying on the screen height.
