### ISSUE TITLE
Set source file pathes in translation template to relative of tools.pot

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#4858]
**Operating system or device - Godot version:**

Any system - Godot 2.1alpha

That would be more friendly to translators for checking source files within translate software?

**Comment by akien-mga** [comment]
That would make the paths quite cumbersome as they would all start with `../../`. Isn't there a way to define a reference root path in translation software?

**Comment by Geequlim** [comment]
@akien-mga No translation softwares doesn't support that. 

I find the way to solve that.
Put the `.po` translation file under root path of godot when translating and move it back when finish :)

**Comment by vnen** [comment]
Poedit actually has this option. Though the feature of checking code itself does not work for me and only gives errors even if I correct the paths in .po using `../../`.

**Comment by Geequlim** [comment]
Poedit eating all of my CPU so I switch to use gtranslator instead.

**Comment by akien-mga** [comment]
For the reference, the issue was valid, but I personally think the loss of functionality for translators is better than having `../../`` in front of all paths, so it's a wontfix as far as I'm concerned. If enough users would like it to be otherwise though, I'm ready to change my mind ;)

**Comment by Geequlim** [comment]
@akien-mga Yes you are right :)
