### ISSUE TITLE
TGA files with RLE compression no longer work

### ISSUE THREAD

**Issue by metinc** [godotengine/godot#48592]
**Godot version:**

3.3

**OS/device including version:**

Ubuntu 21.04

**Issue description:**

I can no longer use my TGA textures if they are saved with RLE compression. This worked before I upgraded to 3.3. When I drag the texture onto my material nothing happens. I expected the texture to be set to the material. Changing import settings made no difference.
Of course I can use png but I found tga support useful for downloaded assets.

**Steps to reproduce:**
Open attached project and try to assign the tga file to a material. Or open GIMP, export any Image as TGA and keep the default export settings (RLE compression enabled). Then try to use it in Godot.

**Minimal reproduction project:**

[tga_rle_bug.zip](https://github.com/godotengine/godot/files/6448070/tga_rle_bug.zip)

**Comment by Calinou** [comment]
cc @Xrayez

**Comment by Xrayez** [comment]
I haven't tested but I think this is caused by #45702, because this seems to be the only change between 3.2.3 and 3.3.

**Comment by stilobique** [comment]
Discovered this issue with my project, on a Windows 10.

**Comment by bruvzg** [comment]
https://github.com/godotengine/godot/blob/12e0f10c74e9619262f1edcfdc1840432ada0565/modules/tga/image_loader_tga.cpp#L59-L61

This check (introduced in #45702) looks like a typo, it's always `true` and RLE encode function always fail. Probably should be:
```c++
	if (output_pos + count * p_pixel_size > p_output_size) {
		return ERR_PARSE_ERROR; 
	}
```

**Comment by stilobique** [comment]
Hi @bruvzg, i don't try your patch (not yet :) ), but it's only for the 4.0 ?

**Comment by bruvzg** [comment]
Version for 3.x - #49603

**Comment by stilobique** [comment]
> 
> 
> Version for 3.x - #49603

Perfect, i'm test it and great ! Everythings work perfectly. Test with an TGA 24bits from Adobe Photoshop, compressed and uncompressed.
