### ISSUE TITLE
Variable fields can't be changed because popups/menus keep closing on their own

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#48593]
**Godot version:**

3.3

**OS/device including version:**

Windows 64, RTX 2070, GLES3

**Issue description:**

Sometimes after editing a script, trying to change a variable in the Inspector, all popups/menus opened by trying to edit the field keep closing, until editor restart. Happens with all kinds var types. 

**Steps to reproduce:**
I have no idea how to diagnose or reproduce this bug, since it's a pretty common operation it seems to be correlated to specific pc/project setup? At least one other user has the same problem though.

**Comment by SkanerSoft** [comment]
Windows x64, Gles 2, Godot 3.3 (and 3.2.x)
There are strange behavior of string variables. When you open a large text input window, it closes spontaneously. Sometimes several times in a row.
There are no errors in the console.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/23626.

**Comment by PLyczkowski** [comment]
Got it again and it doesn't seem to be related to exported variables after all. Seems more to be related to editing built-in scripts? This time I added a built-in script to a Control, ran the scene a couple of times, then tried to edit rect.position on that control and got the bug.

**Comment by PLyczkowski** [comment]
Here it is also happening in the inspector on nodes accessed from the Remote scene tree view.

https://user-images.githubusercontent.com/7307968/121920212-1e96e400-cd38-11eb-9f98-dfa36fe36541.mp4

**Comment by PLyczkowski** [comment]
No longer appearing
