### ISSUE TITLE
Can't render cheese in Godot 4 (material tester demo project)

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#48600]
**Godot version:**
Commit: 6e3f47983cabb5f162eaec075d810f717985beda

**OS/device including version:**
Windows 10, Vulkan, Nvidia 3070

**Issue description:**
Making our material tester demo work on Godot 4 there are two materials that result in the entire scene not rendering properly:

![image](https://user-images.githubusercontent.com/1945449/117606759-e8e16700-b19d-11eb-88fd-883dc0f37450.png)

This happens with the Cheese and Marble materials, it looks like that it is subsurface scattering that is causing this.

**Steps to reproduce:**
Turn on subsurface scaterring on a material

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/pull/616

**Comment by josefkaragoli** [comment]
What's happening with the depth draw? Looks like its not using the depth buffer and/or it's not functioning correctly

**Comment by akien-mga** [comment]
Fixed by #50186.
