### ISSUE TITLE
Viewport - Wrong "initialization" on certain Mac OSX machines.

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#48604]
**Godot version:**
3.3 - stable

**OS/device including version:**
Mac OSX (was reported mostly on MacBooks with AMD Radeon Pro 560 or similar Graphic Adapters )

**Issue description:**
When using a Viewport node that has "render_target_clear_mode" set to "never" and transparent background, it initializes buggy on those systems.

On other Systems it does what it should do: display a transparent viewport.
On the Systems that experience the bug, the viewport displays a green color.
![image](https://user-images.githubusercontent.com/9423774/117631192-45cc2580-b17c-11eb-926e-b1ca34133a98.png)

**Steps to reproduce:**
- Create a ViewportContainer and Viewport inside
- Check "transparent" checkbox (I'm not sure if you also have to check "own world" - I don't own a Mac, so I can't fully confirm)
- Set "Clear Mode" to "never"
- I can't confirm if this only happens if the project is exported or also in the editor.

**Minimal reproduction project:**
[MacOSX-Macbook-Viewport-Never-Update.zip](https://github.com/godotengine/godot/files/6450740/MacOSX-Macbook-Viewport-Never-Update.zip)

**Comment by lawnjelly** [comment]
If the render target is never cleared, and there is a transparent background, then that may be the correct result. The data in the render target is undefined. Most hardware may be initializing it to zero, and Mac is putting a green color to let you know it is undefined.

We should probably put in a single glClear for this surface on creation even if the clear mode is set to never, just for consistency. But in some senses it is user error.

Incidentally, be careful never clearing a render target if it is being used on every frame. Long ago it used to be faster not to do a clear. These days it is pretty much always faster to clear, especially on tile based renderers. I'm presuming never clear is intended to draw something and reuse it over multiple frames.

**Comment by lawnjelly** [comment]
It sounds like the render target is uninitialized because clear is set to never. Most hardware may be initializing it to zero, and Mac maybe setting to green to let you know you haven't initialized it.

If you set something to never clear, you may need to draw something in it to have something valid in the surface.

**Comment by RPicster** [comment]
I instantly looked in the documentation if there is a clear() method, but there is none - so **that would be eventually useful to expose**.

By the way, I think viewports are usually cleared with 0,0,0,0 (just a guess) which leads to the "black edge on alpha" problem which I personally now fix with a shader - but is super annoying.
https://github.com/godotengine/godot/issues/45387
https://github.com/godotengine/godot/issues/17574

I really don't want to clear the viewport by the way - I use it as a "decal layer" in my game ( FRANZ FURY ).
I guess it's a really rare case.

My solution now is to set the viewport to always clear and set it to never after the first "decal" is spawned.

**Comment by lawnjelly** [comment]
So what happened when you tried CLEAR_MODE_ONLY_NEXT_FRAME?
https://docs.godotengine.org/en/3.3/classes/class_viewport.html#enum-viewport-clearmode

From the docs:
> CLEAR_MODE_ONLY_NEXT_FRAME = 2 --- Clear the render target next frame, then switch to CLEAR_MODE_NEVER.

I'm hoping this would do a single clear when the viewport is created, which is what you want (to clear the uninitialized data).

If you can set CLEAR_MODE_ONLY_NEXT_FRAME from script, then this is kind of similar to having a clear() method (except it takes place on the next frame).

**Comment by RPicster** [comment]
> So what happened when you tried CLEAR_MODE_ONLY_NEXT_FRAME?
> https://docs.godotengine.org/en/3.3/classes/class_viewport.html#enum-viewport-clearmode
> 
> From the docs:
> 
> > CLEAR_MODE_ONLY_NEXT_FRAME = 2 --- Clear the render target next frame, then switch to CLEAR_MODE_NEVER.
> 
> I'm hoping this would do a single clear when the viewport is created, which is what you want (to clear the uninitialized data).
> 
> If you can set CLEAR_MODE_ONLY_NEXT_FRAME from script, then this is kind of similar to having a clear() method (except it takes place on the next frame).

Ah sorry, I didn't read the documentation and thought that It would always clear on the next frame.

I'll changed it and report what my Mac testers tell me.
Unfortunately I can't test it myself.

If some Mac user that can reproduce the problem in the minimal reproduction project, test this - it would be fantastic!
