### ISSUE TITLE
Drop down menus appear on the middle of the canvas in Godot 4

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot#48613]
**Godot version:**
Godot 4 non-mono build as at 11/05/2021.

**OS/device including version:**
Windows 10.
Using a high resolution 4K screen, 15.6inch display.

**Issue description:**
Clicking on any of the menu items opens the drop down dialog in the middle of the canvas.
![image](https://user-images.githubusercontent.com/8476589/117672270-0853b080-b1ed-11eb-9bea-dd39e69ce6a1.png)
![image](https://user-images.githubusercontent.com/8476589/117672341-1acdea00-b1ed-11eb-811f-041e123e2f22.png)

**Steps to reproduce:**
Open Godot 4 and click on any of the drop down menu items.

However, if Godot 4 is minimized and maximized again, the drop down menu items appear correctly. As below:
![image](https://user-images.githubusercontent.com/8476589/117672474-39cc7c00-b1ed-11eb-9b66-4498be7923f0.png)

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
- Can you reproduce this after enabling **Single Window Mode** and restarting the editor?
- Can you reproduce this if you set **Interface > Editor > Display Scale** to 100% in the Editor Settings?
