### ISSUE TITLE
Camera2D Bug

### ISSUE THREAD

**Issue by ProgramadorSegundo** [godotengine/godot#48628]
Godot version: 3.3

OS/device including version: Windows10, Intel Core I3, GLES3

Issue description:
when I use the 2D camera the character stops moving, and nodes without scripts move

Steps to reproduce: add a 2D camera to the character

Video: https://youtu.be/dGInZD6XUrY

Minimal reproduction project: 
[game.zip](https://github.com/godotengine/godot/files/6455288/game.zip)

**Comment by Xrayez** [comment]
Looking at the video, I see nothing wrong with the camera behavior. It may *seem* like characters are moving around except for the one in the center, but that's the point of `Camera2D` node, it tracks the node. It's a point of view problem.

**Comment by ProgramadorSegundo** [comment]
you're right, sorry
