### ISSUE TITLE
Nested whiles doesn't work as expected

### ISSUE THREAD

**Issue by Shin-NiL** [godotengine/godot#4862]
**Operating system or device - Godot version:**
Windows 10 Pro 64 bit - Godot 2.0.3.

**Issue description** (what happened, and what was expected):
Nested whiles seems to be running only the deepest loop.

This code:
```
	var i = 0
	var j = 0
	
	while i < 5:
		while j < 5:
			print (str(i) + " " + str(j))
			j += 1
		i += 1
```
is printing:
```
0 0
0 1
0 2
0 3
0 4
```

**Steps to reproduce:**
Use the code above.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Hehe, what about:
```
    var i = 0
    while i < 5:
        var j = 0
        while j < 5:
            print (str(i) + " " + str(j))
            j += 1
        i += 1
```
? ;)

**Comment by neikeq** [comment]
@akien-mga I was breaking my head trying to understand why I couldn't reproduce it. I can't believe I missed that line :smile:

**Comment by Shin-NiL** [comment]
Oh, man...  my bad. Thanks so much!

**Comment by akien-mga** [comment]
I'll admit I had to try it in a test project to find the mistake ;) I just debugged as usual by adding a ``print(i)`` at the end of the first loop, and saw that it got incremented five times... so something had to wrong somewhere :)
