### ISSUE TITLE
variable update bug

### ISSUE THREAD

**Issue by JDMDK** [godotengine/godot#48633]
**Godot version:** 3.3.stable

**Issue description:** num in text does not update unless updated manually.
I don't know if I'm just stupid but shouldn't a variable get recalculated if called

**Steps to reproduce:**
#updates 
func _save_characters():
	
	var file = File.new()
	var num = 1
	var text = str("res://user/characters/characters", num, ".json")
	
	
	while file.file_exists(text):
		
		num += 1
		text = str("res://user/characters/characters", num, ".json")
	
#doesn't update 
func _save_characters_2():
	
	var file = File.new()
	var num = 1
	var text = str("res://user/characters/characters", num, ".json")
	
	
	while file.file_exists(text):
		
		num += 1

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
`str("res://user/characters/characters", num, ".json")` is a static String, it's just more convenient way to write `"res://user/characters/characters" + str(num) + ".json"`. You need to assign `text` again to have it updated.
