### ISSUE TITLE
Window unfocus doesn't stop tooltips from appearing

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#48634]
**Godot version:**

3.3

**Issue description:**

When you unfocus Godot window, the tooltip may still appear if the mouse was over tooltipable node when unfocusing.
![MdyKKJkw9N](https://user-images.githubusercontent.com/2223172/117804763-74b7c980-b258-11eb-94ac-4a4a4724df92.gif)

**Steps to reproduce:**
1. Move cursor over some editor button that has a tooltip
2. Before tooltip appears, Alt+Tab to another window
3. The tooltip will still appear even though the button is technically not hovered anymore

You can increase tooltip appear time to make it easier to observe.

Could be easily fixed by stopping the tooltip timer on notification unfocused. Also unfocusing should probably kill existing tooltips.

**Comment by KoBeWi** [comment]
Looks related to #46737

**Comment by felaugmar** [comment]
This is still an issue in v4.0.3.stable.official [5222a99f5]
