### ISSUE TITLE
Can't run Godot Editor nor Project Manager - getting a neverending stream of Vulkan related errors

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#48649]
**Godot version:**

7050e4d3077c278bda35d21ed60d7068cc4bc9e9

**OS/device including version:**

Windows 7 SP1

**Issue description:**

This video demonstrated what happened:
https://www.dropbox.com/s/1iug6bdq353n1oy/GodotVulkanFlood.mp4?dl=0

https://user-images.githubusercontent.com/8281454/118016664-9fa53900-b390-11eb-9a17-70a0c9f1c096.mp4

I don't know when exactly it started to happen. Last build i tried that didn't have that issue was f8442b97bf7f2b445b0aca9c02629277c11064d6.

**Steps to reproduce:**
Run the Project Manager or Godot Editor.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@hilfazer What graphics card model and driver version do you have?

**Comment by hilfazer** [comment]
Updating drivers did help, thanks!

I'm not getting errors anymore, just warnings:
![GodotVulkanWarnings](https://user-images.githubusercontent.com/29497869/118014626-b4171080-b353-11eb-9092-b0574fe34776.png)

One warning when project manager and one for Godot editor. I tried with a freshly created project and with a preexisting one.
Anyway, the problem appears to be solved.

**Comment by akien-mga** [comment]
Yes that warning is expected if you don't have the Vulkan validation layers from the Vulkan SDK. They're only useful for renderer developers, so you can ignore it (we'll likely silence this warning at some point).
