### ISSUE TITLE
Using onready keyword in a non-Node derived script doesn't produce a warning

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#48643]
**Godot version:**
3.3.stable

**Issue description:**
AFAIK, using `onready` keyword in a non-`Node` derived script makes no sense, it makes initialization never happen. Such usage of `onready` keyword should at least show a warning.

**Steps to reproduce:**
Create a script extending non-`Node` derived class:
```
extends Reference

onready var test = "This will never be assigned to that variable."
```
there will be no warning or something like that.

**Comment by Calinou** [comment]
cc @vnen
