### ISSUE TITLE
Changing Window Size In Project Settings Changes Project Manager Size On Ctrl + Shift + Q

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#4865]
**Operating system or device - Godot version:**
Linux, Godot 2.0.3

**Issue description** (what happened, and what was expected):
On changing the window size via the Project Settings, on a quit to Project Manager (Ctrl + Shift + Q) changes the Project Manager window size. Doing fullscreen in Project Settings also makes the Project Manager fullscreen on quit to Project Manger as well.

**Steps to reproduce:**
Change the window size in Project Manager, or fullscreen it, then quit to the Project Manager via Ctrl + Shift + Q.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
This has been fixed already, it'll be on the next release if you're not compiling from master. See #4045.
