### ISSUE TITLE
Emit a warning when modifying a primitive return value from a getter function in GDScript

### ISSUE THREAD

**Issue by Shatur95** [godotengine/godot#48673]
**Godot version:** 3.3 and 4.4 (a50a81b703)

**OS/device including version:** Linux

**Issue description:**

Getter functions allow assignments that do nothing. For example, the following code will not change mesh origin:

```gdscript
var mesh: MeshInstance = $MeshInstance
print(mesh.global_transform.origin) # Prints (0,0,0)

mesh.get_global_transform().origin = Vector3(100, 100, 100)

print(mesh.global_transform.origin) # Prints (0,0,0)
```

But the following code works:

```gdscript
var mesh: MeshInstance = $MeshInstance
print(mesh.global_transform.origin) # Prints (0,0,0)

mesh.global_transform.origin = Vector3(100, 100, 100)

print(mesh.global_transform.origin) # Prints (100,100,100)
```

I would expect to get an error in the first case, or a working assignment. But the code just silently does nothing.

**Minimal reproduction project:**

[TestBug.zip](https://github.com/godotengine/godot/files/6468372/TestBug.zip)

**Comment by Calinou** [comment]
> mesh.get_global_transform().origin = Vector3(100, 100, 100)

This should probably return some kind of "standalone expression" warning, since you are getting a new Transform, modifying it, then doing nothing with it.

**Comment by Shatur95** [comment]
@Calinou, If the behavior is as expected, should we move this issue to proposals?

**Comment by Calinou** [comment]
> @Calinou, If the behavior is as expected, should we move this issue to proposals?

Feel free to open a proposal for this :slightly_smiling_face:

**Comment by AndreaCatania** [comment]
This used to work in 3.3; but however, in my tests if the mesh start from position `10,10,10`, after the incriminated function is executed the origin is set to `0,0,0`. 

So, there is something going on there that worth to investigate anyway. At least it should not reset the origin to `0,0,0`. 

```
var mesh: MeshInstance = $MeshInstance
print(mesh.global_transform.origin) # Prints (10,10,10)

mesh.get_global_transform().origin = Vector3(100, 100, 100)

print(mesh.global_transform.origin) # Prints (0,0,0)
```

**Comment by AndreaCatania** [comment]
After few tests in 4.0, the above case --^ seems not reproducible. So, maybe it was just an issue I had the other day.

**Comment by Shatur95** [comment]
> This used to work in 3.2;

Tested on 3.2, works as in 3.3. Probably this was something different.

Opened a proposal: https://github.com/godotengine/godot-proposals/issues/2718
