### ISSUE TITLE
Variables are not being updated in tool scripts after they were edited

### ISSUE THREAD

**Issue by cmd410** [godotengine/godot#48689]
**Godot version:** Godot Engine v4.0.dev de3747fc3

**OS/device including version:** Windows 10 64-bit

**Issue description:**

Scripts marked with `@tool` remember the state of variables and refuse to update them when script was edited.

![изображение](https://user-images.githubusercontent.com/48290258/118118699-f133df00-b3f5-11eb-8978-b47da892fc1f.png)

Restarting editor doesn't help. What helps: 

- removing `@tool` and adding it back
- marking variables with `@onready`

Also tested on stable v3.3, couldn't reproduce the bug there

**UPD**: Its seems that Godot writes variables of tool scripts into `.tscn` file, even though there is no `@export`

```[gd_scene load_steps=2 format=2]

[ext_resource path="res://Main.gd" type="Script" id=1]

[node name="Node" type="Node"]
script = ExtResource( 1 )
I = 42
D = {
"key4": [ 1, 2, 3 ],
"key5": [ 1, 2, 3 ]
}
```

**Steps to reproduce:**

1. Create a script
1. Declare and initialize some variables, print their values
1. Run scene with this script 
1. Mark script with `@tool`
1. Change variables value
1. Run script once more
1. Observe that values haven't changed

OR

1. Open Minimal reproduction project
1. Try changing variable values in `Main.gd` and run the project

**Minimal reproduction project:** [ToolUpdateBug.zip](https://github.com/godotengine/godot/files/6472118/ToolUpdateBug.zip)

**Comment by Calinou** [comment]
> UPD: Its seems that Godot writes variables of tool scripts into `.tscn` file, even though there is no `@export`

This is a known issue, see https://github.com/godotengine/godot/issues/48224.

**Comment by vnen** [comment]
This is likely the same as #48224

**Comment by Calinou** [comment]
Closing per @TechnoPorg's comment.
