### ISSUE TITLE
Godot app does not close files when loading resources from zip container, so it crashes.

### ISSUE THREAD

**Issue by jhusak** [godotengine/godot#48697]
I have not found similar issues.

**Godot version:**
All versions 3.x

**OS/device including version:**
Linux, OsX, probably all versions

**Issue description:**
When running exported game to data.zip container, game runs till all descriptors are busy and opened, then cannot load resources, so it freezes. 
Minimal project attached, after several seconds it freezes with error.

**Minimal reproduction project:**
[LoopTest.tar.gz](https://github.com/godotengine/godot/files/6474737/LoopTest.tar.gz)

**Comment by akien-mga** [comment]
That sounds related to the issue described in this PR, which might fix it: #40303.

**Comment by akien-mga** [comment]
I tested and confirmed that #42337 fixes it.
