### ISSUE TITLE
Node descriptions don't appear in VisualScript editor's "Add Nodes"/Search window

### ISSUE THREAD

**Issue by idchlife** [godotengine/godot#48699]
**Godot version:**

3.3

**OS/device including version:**

macOS

**Issue description:**

When you extend another node, e.g. array variable - there you can see nodes descriptions, for example 
<img width="787" alt="изображение" src="https://user-images.githubusercontent.com/4563032/118180216-f6694c00-b43e-11eb-8115-1a221cd61808.png">

When you try to add node via search or "add nodes", you see this:
<img width="783" alt="изображение" src="https://user-images.githubusercontent.com/4563032/118180299-0aad4900-b43f-11eb-8a74-066d5aa35dea.png">

**Steps to reproduce:**
^^^
In description

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Relevant code to investigate is in `modules/visual_script/visual_script_property_selector.cpp`.

The description field is the `help_bit` member variable.

**Comment by sent44** [comment]
https://github.com/godotengine/godot/blob/9b637faf654d9e9c715f669e1101b40c9d1479a7/modules/visual_script/visual_script_property_selector.cpp#L472
This line will output elements of `class_type`.

But `class_type` fetch from this:
https://github.com/godotengine/godot/blob/9b637faf654d9e9c715f669e1101b40c9d1479a7/modules/visual_script/visual_script_property_selector.cpp#L433-L439
When drag from dot of exist node, `type` is set to the same type of dot thing. So when drag from array dot, `type` will set to `Array`
But when click `Add Nodes...` or right click on canvas, `type` is not set. So it will fallback to `base_type`, which is the class script is inherits by. And when `T` is loop, function is not found.

Off topic: I think these loops should break when whey are already found what they want.

**Comment by theoway** [comment]
> https://github.com/godotengine/godot/blob/9b637faf654d9e9c715f669e1101b40c9d1479a7/modules/visual_script/visual_script_property_selector.cpp#L472
> 
> 
> This line will output elements of `class_type`.
> But `class_type` fetch from this:
> https://github.com/godotengine/godot/blob/9b637faf654d9e9c715f669e1101b40c9d1479a7/modules/visual_script/visual_script_property_selector.cpp#L433-L439
> 
> 
> When drag from dot of exist node, `type` is set to the same type of dot thing. So when drag from array dot, `type` will set to `Array`
> But when click `Add Nodes...` or right click on canvas, `type` is not set. So it will fallback to `base_type`, which is the class script is inherits by. And when `T` is loop, function is not found.
> Off topic: I think these loops should break when whey are already found what they want.

Are you currently working on this? If not, I'd be happy to investigate it further & fix it.

**Comment by sent44** [comment]
@theoway No, you can do it.

**Comment by theoway** [comment]
Reproducible on master branch. Will make a PR on master branch soon, so that it can be cherry picked for 3.3
