### ISSUE TITLE
I want know how to create Visual Studo project and Xcode project

### ISSUE THREAD

**Issue by cmzx3444** [godotengine/godot#487]
I have complied success of the engine ,but it does'n generate the project file.
I want know how to create Visual Studo project and Xcode project, Thanks

**Comment by akien-mga** [comment]
This was more of a support question than an issue, closing.

**Comment by vnen** [comment]
For future reference, you can use `vsproj=yes` flag to scons command line to generate a Visual Studio project, as added in #1800.
