### ISSUE TITLE
Ragdoll simulation is broken if parent was removed from and then and readded to scene

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#48705]
**Godot version:** 3.3 stable and 3.3.1 rc1

**OS/device including version:** Windows 10

**Issue description:**

Video shows regular ragdoll and then ragdolling after removing and then readding to scene.

https://user-images.githubusercontent.com/7292421/118194915-30732780-b418-11eb-8a4f-368d7e7f7fa3.mov

**Steps to reproduce:**

run this code on the parent (or parent of parent, etc.) of a skeleton
```
func _ready():
	remove_child(character)
	add_child(character)
	skeleton.physical_bones_start_simulation()
```

**Minimal reproduction project:**

[ragdolltest.zip](https://github.com/godotengine/godot/files/6475366/ragdolltest.zip)
in the World.tscn you can toggle the exported var remove_from_scene_first to choose if node is removed and readded from scene before simulating ragdoll

**Comment by josefkaragoli** [comment]
Can also reproduce this in 3.2.4 in my own project

**Comment by akien-mga** [comment]
> Can also reproduce this in 3.2.4 in my own project

Please be more specific, 3.2.4 never had a stable release (it was renamed to 3.3).

**Comment by akien-mga** [comment]
> Video shows regular ragdoll and then ragdolling after removing and then readding to scene.
> [user-images.githubusercontent.com/7292421/118194915-30732780-b418-11eb-8a4f-368d7e7f7fa3.mov](https://user-images.githubusercontent.com/7292421/118194915-30732780-b418-11eb-8a4f-368d7e7f7fa3.mov)

Looks like a feature to me, just rename that exported variable to `break_dance` :P

I can reproduce the issue, it seems to happen in 3.2.x too, as early as 3.2.1. 3.2 is broken and triggers endless spam of:
```
ERROR: _notification: Condition "bone_index >= (uint32_t)len" is true. Continuing.
   At: scene/3d/skeleton.cpp:328.
```

3.1.x isn't compatible with the project as it didn't have the `Skin` resource.

**Comment by josefkaragoli** [comment]
> > Can also reproduce this in 3.2.4 in my own project
> 
> Please be more specific, 3.2.4 never had a stable release (it was renamed to 3.3).

Sorry!!!! I meant 3.2.3 (the version before 3.3)

**Comment by Miziziziz** [comment]
If you move the model away from position 0,0,0 one of the limbs becomes detached when the ragdoll simulation is run after removing and adding to the scene again, as shown:

https://user-images.githubusercontent.com/7292421/120054709-7ecf1b80-bfff-11eb-8dc2-c081ca9a6690.mov

**Comment by timothyqiu** [comment]
A quick fix is always reloading the joint at the end of enter tree. But I'll investigate further to see if there is a better solution.
