### ISSUE TITLE
3.3.1 rc 1 - godot server and godot headless empty folders

### ISSUE THREAD

**Issue by sesenta** [godotengine/godot#48703]
**Godot version:**
3.3.1 rc 1  

**Issue description:**
I downloaded godot 3.3.1 rc 1 and works perfectly, but when i download **headless** and **server** for test the folders are empty, i dont know if is normal so sorry in advance

**Comment by Calinou** [comment]
The 3.3.1rc1 headless/server downloads available are definitely not empty: https://downloads.tuxfamily.org/godotengine/3.3.1/rc1/

**Comment by sesenta** [comment]
i just check it and all folder are empty, the normal versions on web page too, only the c# version is normal, i'm on linux

**Comment by akien-mga** [comment]
Please test the `sha512sum`s of the downloaded ZIPs, and compare with https://downloads.tuxfamily.org/godotengine/3.3.1/rc1/SHA512-SUMS.txt

If they differ, it means your downloads are corrupted.

**Comment by sesenta** [comment]
i restarted my system and now can unzip correctly the versions and not just the c# version, sorry and thanks
