### ISSUE TITLE
Translation on X scales instead of moving in the 3D editor

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#4872]
Godot v. 2.03 stable, Win x64

While moving a node along the X axis in the 3D editor with the move tool, if the middle mouse button is clicked to change the constrain mode, that first switch makes scaling be applied instead. Doesn't happen on other axes nor under other constrain modes.

Steps to reproduce:
1. Select and object.
2. Pick the move tool.
3. Start dragging over the X axis arrow.
4. While still holding the LMB, click the MMB.
5. Note that now moving the mouse will produce (proportional) scaling instead of translation.

**Comment by RandomShaper** [comment]
Being this my first bug report and due to the fact that both reports of mine are the only which have not got tagged by the devs, I wonder if I made something wrong or missed some rule for posting.

Can anyone confirm?

**Comment by akien-mga** [comment]
It just means that we're busy :)

**Comment by RandomShaper** [comment]
Thanks for the feedback. This is a great project and I am really interested in contributing

**Comment by nunodonato** [comment]
Linux here, I can't reproduce this bug. The only wrong behavior I see is that the message shows a wrong "view transform". that is I'm moving along the y-axis and it shows "x-axis transform", and when I'm moving on the Z it shows "y-axis transform"

**Comment by RandomShaper** [comment]
I've tested on master and now I can't reproduce it either. Guess it already got solved. So I'm closing this report.

The issue about the out-of-phase message is reported on #4870.

**Comment by nunodonato** [comment]
but could you see the wrong messages too?

**Comment by RandomShaper** [comment]
Yeah, that still happens.
