### ISSUE TITLE
Drag forwarding methods not available in autocompletion and documentation

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#48726]
**Godot version:** master(6054feb) / 3.x(7417467) / 3.3

**OS/device including version:** not graphics-related

**Issue description:**

When `set_drag_forwarding` is set on a `Control` node, the forward owner's `get_drag_data_fw`, `can_drop_data_fw`, and `drop_data_fw` are used instead of the control's non-postfixed ones.

* Searching the built-in documentation shows no such methods on `Control`. They are only mentioned in the documentation of `set_drag_forwarding`.
* There is no autocompletion for these methods. When writing these functions in GDScript, one have to autocomplete the non-postfixed version, and then add the `_fw` postfix and extra argument. This becomes quite a lot of work when type hints are used.

**Steps to reproduce:**

* Create a control node, add a script, and try to type `get_drag_data_fw`.
* Search `get_drag_data_fw` in help.

**Minimal reproduction project:** N/A

**Comment by timothyqiu** [comment]
To anyone interested in solving this: `set_drag_forwarding()` takes any Object. But binding these forwarding methods to Object seems an overkill. See discussion in #60558.

**Comment by HolonProduction** [comment]
Can we close this? `set_drag_forwarding` does take callables now, so while we still do not provide completion, we just can't since there is no fixed name.
