### ISSUE TITLE
Skeleton IK 'twisting' bug introduced in 3.3

### ISSUE THREAD

**Issue by kjav** [godotengine/godot#48722]
**Godot version:** 3.3

**Issue description:** 

I've noticed that a strange twisting has been introduced into the IK skeleton in Godot version 3.3. Running the same project in 3.2.3 and 3.3 reveals the issue (screenshots below).
Thanks for the help.

> Working in 3.2.3
> <img width="1296" alt="3.2.3" src="https://user-images.githubusercontent.com/9029686/118324252-b1562000-b4f9-11eb-8d88-709cc4b91a92.PNG">
> Broken in 3.3
> <img width="1218" alt="3.3" src="https://user-images.githubusercontent.com/9029686/118324257-b3b87a00-b4f9-11eb-92bd-8875f49ce8a7.PNG">
> And here's my scene
> <img width="126" alt="Scene setup" src="https://user-images.githubusercontent.com/9029686/118324266-b61ad400-b4f9-11eb-947e-853fb7933cce.PNG">

**Comment by akien-mga** [comment]
This is likely fix in 3.3.1 RC 1, could you test? https://godotengine.org/article/release-candidate-godot-3-3-1-rc-1

**Comment by kjav** [comment]
> 
> 
> This is likely fix in 3.3.1 RC 1, could you test? https://godotengine.org/article/release-candidate-godot-3-3-1-rc-1

Confirmed - thanks for the help! I guess I'll wait for that release.
