### ISSUE TITLE
Android export settings in Editor Settings don't match documentation

### ISSUE THREAD

**Issue by this-is-bennyk** [godotengine/godot#48728]
**Godot version:**

3.3

**OS/device including version:**

Windows 10 Pro 20H2 (I don't think this matters)

**Issue description:**

While I was configuring my Android export settings again to deploy a custom APK build, I noticed that the parameters for the Android export settings in the editor settings were the same as in 3.2. Looking at the 3.3 documentation, most of these parameters are removed. This was incredibly confusing at first, and it took me a second to realize that the documentation was right about setting up the export settings for 3.3; it's just that the parameters are in different places than expected. I'm not sure if this was intended, and I'm also not sure whether this is a bug or a documentation issue; but seeing as the missing parameters are not required, I'm inclined to call it a bug, or at least an oversight. I apologize if this is supposed to be the case or this isn't the right place to put this issue.
![image](https://user-images.githubusercontent.com/65842636/118350574-685b9700-b50c-11eb-8de7-720080927061.png)

**Steps to reproduce:**
Download Godot 3.3, open/make a project, go to Editor -> Editor Settings... and go to Android under the Export category.

**Minimal reproduction project:**

None needed.

**Comment by Calinou** [comment]
This is because you can see obsolete settings when upgrading from an older Godot version. You can safely ignore those or click on the Revert button to remove them.
