### ISSUE TITLE
Cannot add Animation to AnimationNodeStateMachine in Godot 3.3 and 3.3.1 RC2

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot#48732]
**Godot version:**
Godot 3.3 and and 3.3.1 RC2 (non-mono)

**OS/device including version:**
Windows 10

**Issue description:**
After adding the AnimationNodeStateMachine to the tree root in an AnimationTree, right-clicking on the state machine pane to "Add Animation" does not show any options.
![image](https://user-images.githubusercontent.com/8476589/118364324-572d8b80-b5db-11eb-8248-0f68436dce9e.png)

**Steps to reproduce:**
Same as above.

**Minimal reproduction project:**
[Action_RPG.zip](https://github.com/godotengine/godot/files/6487554/Action_RPG.zip)

**Comment by knadoor** [comment]
Nevermind :)

**Comment by Sslaxx** [comment]
> Nevermind :)

Why, what was actually the problem?

**Comment by knadoor** [comment]
> > Nevermind :)
> 
> Why, what was actually the problem?

There was no problem, I forgot to add the AnimationPlayer node and was wondering why the AnimationTree's graph wasn't showing the animation values.
