### ISSUE TITLE
Importing a glTF model: texture scaling is ignored

### ISSUE THREAD

**Issue by ReturnMinusOne** [godotengine/godot#48737]
**Godot version:**

3.3.stable.mono.official

**OS/device including version:**

**OS:** Windows 10 (64-bit)
**GPU:** AMD (Gigabyte) Radeon RX 590
**GPU driver:** 20.10.27.05-201027a-360165C-RadeonProEnterprise
**Godot renderer backend:** GLES3

**Issue description:**
Importing a glTF 2.0 model file into Godot does not take into account the scaling factor of materials. A texture that is normally tiled will simply be stretched when imported.

Viewing the model in another program, such as Blender 2.9 or the Windows 3D Viewer, will show the proper tiling.

**Left:** Windows 3D Viewer | **Right:** Godot 3.3
![GLTF-Win3dViewer-vs-Godot](https://user-images.githubusercontent.com/35435781/118370209-b310f980-b574-11eb-899b-e52b46c0303d.jpg)

**Steps to reproduce:**
Import a .gltf or .glb file with some texture tiling into Godot.

**Minimal reproduction project:**

[GLTF Import.zip](https://github.com/godotengine/godot/files/6487695/GLTF.Import.zip)

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
I and a peer are working on a Godot Engine gltf2 backport for 3.x. I believe this issue is resolved on master.

https://github.com/godotengine/godot/pull/34193

https://github.com/godotengine/godot/pull/46783

**Comment by ReturnMinusOne** [comment]
That's reassuring; I look forward to the next stable release.
