### ISSUE TITLE
[REQUEST] allow closing bracket straight away in script

### ISSUE THREAD

**Issue by lewislepton** [godotengine/godot#4873]
just a simple request, but when typing out the code, it does allow the opening bracket `(`, but no closing one. it would be good if both came up and your caret was inbetween to continue coding

thanks

**Comment by Paulb23** [comment]
You have to enable it in the settings: `Settings -> Editor Settings -> Text Editor -> Auto Brace Complete`

**Comment by lewislepton** [comment]
aaah cool spot 

thanks ;)
