### ISSUE TITLE
Total system freeze when importing normal maps in 3.3

### ISSUE THREAD

**Issue by ardemd** [godotengine/godot#48733]
Godot 3.3 is completely freezing my pc every time there is a normal map being dragged into the proper slot, or a scene is being opened and assets are being reimported automatically.  Once the pop up window shows that the item being imported is a normal map, a get a total lockup and have to reboot.
That does not happen on 2.3.2 or older versions.

godot 3.3 default GLES3

linux mint 20 cinnamon
AMD Phenom II X6 1100T Processor × 6 
GeForce GTX 1060 6GB
drivers 450.119.03

**Comment by Calinou** [comment]
@ardemd Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
