### ISSUE TITLE
ShortcutCheatSheet.png for Godot Editor + Document Shortcuts?

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#4875]
I don't know of all the shortcuts and the information doesn't seem to be easily available. Perhaps an image showing Godot Editor UI + all the shortcuts listed and placed in docs somewhere would help out.

What do you think?

**Comment by trollworkout** [comment]
I did egrep on all the source files and manually went trough all output and produced this list. It may be wrong and also some shortcuts repeat  because each component set has it's own list.  

```
line edit:
Cut = CMD + X
Copy = CMD + C
Paste = CMD + V
Select All = CMD + A
Undo = CMD + Z

text edit:
Cut =  CMD + X
Copy = CMD + C
Paste = CMD + V
Select All = CMD + A
Undo = CMD + Z

animation_editor:
Goto Next Step = CMD + Right
Goto Prev Step = CMD + Left



Open Scene = CMD + O
Save Scene = CMD + S
Save Scene As.. = Shift + CMD + S
Close Scene = Ctrl + W
Close Goto Prev. Scene = Shift + CMD + P
Quick Open Scene = Shift + CMD + O
Quick Open Script.. = ALT + CMD + O
Quick Search File.. = Alt + CMD + P
Undo = CMD + Z
Redo = CMD + Shift + Z
Run Script = Shift + CMD + R
Quit to Project List = Shift + Alt + Q
Quit to Poject List = Shift + Ctrl + Q
Quit = CMD + Q

Play custom scene = Shift + F5

Select Mode = Q
Move = Alt+Drag
Change Pivot = V
Drag Pivot = Shift + V
Depth List = Alt + Right Click

Expand to Parent = CMD + P
Make Bones = Shift + B
Center Selection = F
Frame Selection = CMD + F
Insert Key = Insert
Insert Key (Existing Tracks) = CMD + Insert
Clear Pose = Shift + K

Select Control Points = Shift + Drag
Add Point = CMD + Left Click
Delete Point = CMD + Right Click

Save = CMD + S
Save All = CMD + Shift + S
History Pev = Ctrl + Alt + Left
History Next = Ctrl + Alt + Right
Close = CMD + W
Undo = CMD = Z
Redo = CMD + Y
Cut = CMD + X
Copy = CMD + C
Paste = CMD + V
Select All = CMD + A
Move Up = Alt + Up
Move Down = Alt + Down
Indent Left = Alt + Left
Indent Right = Alt + Right
Toggle Comment =  CMD + K
Clone Down = CMD + B
Complete Symbol = Ctrl + Space
Complete Symbol = CMD + Space
Trimp Training Whitespace = Ctrl + Alt + T
Auto Indent = CMD + I
Find.. = CMD + F
Find Next.. = F3
Replace.. = CMD + R
Goto Function.. = Shift + CMD + F
Goto Line = CMD + L
Find.. = F
Find Next = F3
Toggle BReakpoint = F9
Step Over = F10
Step Into = F11
Close = CMD + W
Move Left = CMD + Left
Contextual = Shift + F1
Undo = CMD + Z
Redo = CMD + Shift + Z
Cut = CMD + X
Copy = CMD + C
Paste = CMD + V
Select All = A
Find.. = F
Find Next = F3
Replce = R
Goto Line = G
Pick Tile = CTRL
Select = CMD + B
Duplicate Selection = CMD + D
Erase Selection = Delete
New Scene Root = A
Add Child Node = A
Move Up = Up
Move Down = Down
Duplicate = D
Delete Node(s) = Delete
Add/Create a New Node = CMD + A
```

**Comment by vnen** [comment]
I opened a issue about this some time ago: godotengine/godot-docs#75

**Comment by trollworkout** [comment]
@vnen  I decided to organize the shortcuts  by UI component

Here is a cheat cheat I made quickly . May have issues.
[Untitleddocument.pdf](https://github.com/godotengine/godot/files/288501/Untitleddocument.pdf)

**Comment by trollworkout** [comment]
hey guys since i made some tentative shortcut documentation myself i will close this

**Comment by plucian** [comment]
seems ALT+Left/Right don't work anymore on the 29.09.2016 build for Indent.

**Comment by vnen** [comment]
Use <kbd>TAB</kbd> and <kbd>SHIFT</kbd>+<kbd>TAB</kbd> for indent/dedent. <kbd>Alt</kbd>+<kbd>←</kbd> and <kbd>Alt</kbd>+<kbd>→</kbd> are now the back/forward commands.

**Comment by trollworkout** [comment]
you can see all shortcuts now in the editor preferences . There's no need for a cheat sheet

**Comment by Nodragem** [comment]
Really? because, not knowing that I made all my way up to here to find out that information. That should be in the documentation page I think.

**Comment by shmlalex** [comment]
what does meta mean?

**Comment by takecare** [comment]
@nandbolt `META` = system key, depending on the system. for e.g. on windows it's the windows key, on macos it's the command key, on some linux distros it's known as the "super" key

**Comment by Calinou** [comment]
For the record, default key mappings are now documented here: https://docs.godotengine.org/en/latest/tutorials/editor/default_key_mapping.html
