### ISSUE TITLE
TileMap `set_cell()` doesn't work properly (4.0.dev)

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#48750]
**Godot version:**

4.0

**OS/device including version:**

Window 10

**Issue description:**

TileMap set_cell by code not work properly

**Steps to reproduce:**
1. Create a TileMap and edit it in the Scene Editor (Set cell(0,0) to something), Run scene, it work properly.
2. Attach script and edit code like this:
```
var cord = Vector2i(0,0)
var id = $TileMap.get_cell_source_id(cord)
var k = $TileMap.get_cell_atlas_coords(cord)
$TileMap.set_cell(cord,id,k)
```
3. Run the Scene, the TileMap cell at (0,0) disappeared
**Minimal reproduction project:**

**Comment by Calinou** [comment]
@CsloudX Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by CsloudX** [comment]
minimal reproduction project:
[TileMapTest.zip](https://github.com/godotengine/godot/files/6489068/TileMapTest.zip)

**Comment by CsloudX** [comment]
Sorry, it's my fault! I doesn't set the alternative_tile.
