### ISSUE TITLE
Godot doesn't show components that exist in the .tscn file and deletes them when I save the scene

### ISSUE THREAD

**Issue by johnfn** [godotengine/godot#48754]
**Godot version:** 3.3

**OS/device including version:**
MacOS Catalina

**Issue description:**

My .tscn file appears (by checking it with a text editor) to have a couple components that don't show up in Godot when I open it in Godot.

When I save the scene in Godot, those components are deleted. 

**Steps to reproduce:**

Save a scene

**Minimal reproduction project:**

You can check out my project https://github.com/johnfn/ld48/commit/b0f8e6263e403efe69efe7633d5e3413951e6311 - specifically at the hash provided 

Then just open it in Godot 3.3 and save RoundTree.tscn

**Comment by Calinou** [comment]
Unfortunately, it's very difficult to figure out what's going on exactly without a proper minimal reproduction project.

**Comment by johnfn** [comment]
Nevermind - this was my own issue. Had a tool script and didn't realize it was deleting stuff!
