### ISSUE TITLE
CPUParticles billboard not working.

### ISSUE THREAD

**Issue by samdaiya** [godotengine/godot#48762]
**Godot version:** 3.3.stable.official

**OS/device including version:** Windows 10 ( OpenGL ES 2.0 Renderer: AMD Radeon HD 7310 Graphics )

**Issue description:** I have added CPU Particles with Quad Mesh billboard enabled (Also tried particles billboard). Billboard effect not working at all. It was working with 3.2

**Steps to reproduce:** Add CPUParticles and then add QuadMesh with Godot icon Texture and then try to enable billboard and check if it works properly as it should.

**Minimal reproduction project:** [BillboardTest.zip](https://github.com/godotengine/godot/files/6489204/BillboardTest.zip)

**Comment by samdaiya** [comment]
Any update on this?

**Comment by Chaosus** [comment]
This seems worked correctly on my PC:

![billboard](https://user-images.githubusercontent.com/3036176/123532857-96daad80-d719-11eb-8062-3fc7990a6618.gif)

> 3.3.stable.official

Try to use the last stable version (3.3.2)

**Comment by samdaiya** [comment]
Tested it. It's working now.
