### ISSUE TITLE
Setter function fails silently if called with incorrect type, assignment ignored without warning

### ISSUE THREAD

**Issue by MFikretY** [godotengine/godot#48765]
**Godot version:**
 3.3 stable

**OS/device including version:**
Windows 10

**Issue description:**
If the input type is defined for a setter function, it fails silently if given another type . No error is thrown, no warning given, and the assignment is completely ignored. Note that this only occurs if the setter is called implicitly, see steps below. 

**Steps to reproduce:**

Upon defining a class like so:
```
class_name ObjectTest

var test_var : int = 10 setget test_set, test_get

func test_set(input_string : int):
	print("Set invoked")
	test_var = input_string
	
func test_get():
	print("Get invoked")
	return test_var
```
And calling from another script like so:
```
func _ready():
 	var obj = ObjectTest.new()
 	obj.test_var = "Hello"  # IGNORED
	print(obj.test_var)
```
The output is:
```
Get invoked
10
```
Note that "Set invoked" is not shown, so the setter has not run at all. 

Project zip:
[setter_bug.zip](https://github.com/godotengine/godot/files/6489324/setter_bug.zip)

**Comment by akien-mga** [comment]
Fixed by #54117.
