### ISSUE TITLE
Editor crashes when clearing DynamicFontData resource

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4877]
**Operating system or device - Godot version:**

Arch Linux, Godot 2.1 Git (https://github.com/godotengine/godot/commit/3e8eb396d7cfec8a96efb78719c0556f1beccf68)

Compiler: `gcc (GCC) 6.1.1 20160501`

**Issue description** (what happened, and what was expected):

- Create a Label
- Set a custom DynamicFont for it
- Try creating a new DynamicFontData resource (not loading an existing one)
- Clear it, because you realize you probably wanted to load one instead
- Editor crashes

**Comment by reduz** [comment]
I think this is already fixed, does it still happen?

**Comment by volzhs** [comment]
it still happen with current head. 1785f69
