### ISSUE TITLE
`Timer` and `AnimatedSprite` affected by Vsync (probably other nodes, too)

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#48786]
**Godot version:**

3.3 / 3.3.1 rc2

**OS/device including version:**

Windows 10, GLES2/3

```
Graphics
		Monitor
			Name	BenQ GL2760 on NVIDIA GeForce GTX 1050 Ti
			Current Resolution	1920x1080 pixels
			Work Resolution	1920x1080 pixels
			State	Enabled, Primary
			Monitor Width	1920
			Monitor Height	1080
			Monitor BPP	32 bits per pixel
			Monitor Frequency	60 Hz
			Device	\\.\DISPLAY1\Monitor0
		Intel HD Graphics 630
			Manufacturer	Intel
			Model	HD Graphics 630
			Device ID	8086-5912
			Revision	5
			Subvendor	Lenovo (17AA)
			Current Performance Level	Level 0
			Current GPU Clock	0 MHz
			Voltage	1.050 V
			Driver version	26.20.100.7986
				Count of performance levels : 1
						Level 1 - "Perf Level 0"
							GPU Clock	450 MHz
		NVIDIA GeForce GTX 1050 Ti
			Manufacturer	NVIDIA
			Model	GeForce GTX 1050 Ti
			Device ID	10DE-1C82
			Revision	A2
			Subvendor	EVGA (3842)
			Current Performance Level	Level 0
			Current GPU Clock	1809 MHz
			Current Memory Clock	3504 MHz
			Current Shader Clock	3504 MHz
			Voltage	1.050 V
			Technology	14 nm
			Bus Interface	PCI Express x16
			Temperature	39 °C
			Driver version	27.21.14.6611
			BIOS Version	86.07.39.00.52
			Memory	4095 MB
				Count of performance levels : 1
						Level 1 - "Perf Level 0"
							GPU Clock	1012 MHz
							Shader Clock	3504 MHz
```

**Issue description:**

`Timer` node's `wait_time` is overridden by Vsync. Also overridden by `Force FPS` setting in `Project Settings`.
`AnimatedSprite` got more `frames` than expected with Vsync on.

**Steps to reproduce:**
(For NVIDIA GPU)
1. Enable Vsync in NVIDIA Control Panel.
2. Run test project, wait for game window to close, then read output.
3. Disable Vsync in NVIDIA Control Panel.
4. (Repeat step 2)
5. Set `Force FPS` to something like 40
6. (Repeat step 2)

**Minimal reproduction project:**

[Timer Vsync - 1.zip](https://github.com/godotengine/godot/files/6493561/Timer.Vsync.-.1.zip)

**Test Results**:
Godot 3.3.1
Results were inconsistent.
For example `AnimatedSprite` counter would range between 1000 and ~1024 (seemingly random)

Vsync off (NVIDIA Control Panel)

```
timer_counter: 1000
animated_sprite_counter: 1000
```

Vsync on (NVIDIA Control Panel)

```
timer_counter: 61
animated_sprite_counter: 1016
```

Vsync on (NVIDIA Control Panel) --- `Force FPS` set to 40

```
timer_counter: 41
animated_sprite_counter: 1024
```

In my case, toggling `Use Vsync` in `Project Settings` made no difference.

**Comment by Calinou** [comment]
I think this is expected. Timer runs on every process ("idle") step, that is, every *rendered* frame.

**Comment by Error7Studios** [comment]
> I think this is expected. Timer runs on every process ("idle") step, that is, every rendered frame.

From a user standpoint, I didn't expect that. `Timer` node allows you to set `wait_time` all the way down to 0.001 in the inspector with no warning or anything, so I expected it to actually go that fast.

> set the timer to run on Physics Process instead

But that would require setting `Physics FPS`  in `Project Settings` really high.
Then you'd be losing performance due to all the additional collision checks, etc. happening in `_physics_process()`

___

Maybe a new `Timer` node called `Micro Timer`  / `FPS Timer` / `Animation Timer` or something could be added.

It could basically work by actually being an `AnimatedSprite`, that just functions as a `Timer`.
You could just connect to its `frame_changed` signal, just renamed to `timeout`.

Or strip the code out of `AnimatedSprite` and make it into a real `Micro Timer` node.

Should I open a proposal for that?

**Comment by Calinou** [comment]
> From a user standpoint, I didn't expect that. Timer node allows you to set wait_time all the way down to 0.001 in the inspector with no warning or anything, so I expected it to actually go that fast.

Maybe we can add a node configuration warning when it's set below 0.016 and the process mode is Idle, or below `1/(physics fps)` when the process mode is set to Physics.

**Comment by Error7Studios** [comment]
Since not actually a bug, opened as proposal [#2734](https://github.com/godotengine/godot-proposals/issues/2734) instead.
