### ISSUE TITLE
Exporting Android Project Missing Default Debug Keystore Values from Editor Settings

### ISSUE THREAD

**Issue by HaywardMorihara** [godotengine/godot#48787]
**Godot version:** 3.3

**OS/device including version:** Windows 10 Version 20H2, Dell XPS 13 9310

**Issue description:**
I am following the ["Exporting for Android"](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot) tutorial to export my project for Android. I set the `Debug Keystore`, `Debug Keystore User`, and `Debug Keystore Pass` in the `Editor Settings` in accordance with the tutorial (https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot). 

When I go to export the project (Project -> Export -> Add -> Android) I see that under Options -> Keystore, the `Debug`, `Debug User`, and `Debug Password` fields are all empty. 

I would expect those values to be defaulted to match the values set in the `Editor Settings`.

I had opened a pull request to add documentation to remind the developer to set these values in the Export preset, but learned that this is a bug: https://github.com/godotengine/godot-docs/pull/4918

Noting that https://github.com/godotengine/godot/issues/48096 & https://github.com/godotengine/godot/issues/48220 look similar (could be related?), but not the same.

**Steps to reproduce:**
1. Set `Debug Keystore`, `Debug Keystore User`, and `Debug Keystore Pass` in the `Editor Settings` (following https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot).
2. Add a new Android Export preset (Project -> Export -> Add -> Android).
3. Observe that no defaults have been provided for the Options -> Keystore `Debug`, `Debug User`, or `Debug Password` fields.

**Minimal reproduction project:**
[DemoDebugKeystoreIssue.zip](https://github.com/godotengine/godot/files/6493744/DemoDebugKeystoreIssue.zip)
^ This is just a blank project.

**Comment by Calinou** [comment]
> Observe that no defaults have been provided for the Options -> Keystore Debug, Debug User, or Debug Password fields.

The fields in the export preset shouldn't be prefilled (we don't want them to be stored to `export_presets.cfg`), but the editor settings should be used as a fallback.

**Comment by HaywardMorihara** [comment]
Ahh, understood, that makes sense. The reason this came to my attention was I was getting error `'apksigner' returned with error # 1` when attempting to export my project, and I resolved it by filling out `Debug`, `Debug User`, and `Debug Password` in the Export preset. I observe now though that if I ensure all 3 of those fields are empty, then Godot appears to fallback to the Editor Settings. My guess is I was seeing this issue because I had unintentionally filled out the `Debug` field in the Export preset, and left the `Debug User` and `Debug Password` blank.

So it seems like a user error on my part - would it be most helpful for me to close this issue? Or maybe adding LineEdit placeholders or error messaging could be helpful in case another user comes across a similar issue.

**Comment by Calinou** [comment]
The debug keystore properties are defined here: https://github.com/Calinou/godot/blob/b5b78e8ce7fd76d677011c9476b16e2b99312a29/platform/android/export/export.cpp#L1655-L1657

The issue is that we can't have a field that is *both* a file path field *and* has a placeholder when empty.

**Comment by HaywardMorihara** [comment]
Makes sense.

I'd be interested in contributing and adding this enhancement - is there a suggested approach you'd recommend I look into?

If not, I can just leave this open to be revisited when appropriate.

**Comment by Calinou** [comment]
> I'd be interested in contributing and adding this enhancement - is there a suggested approach you'd recommend I look into?

The line here demonstrates how to set placeholder text: https://github.com/godotengine/godot/blob/c6bef537274e65620b40b9f5f1937d2332a249df/platform/android/export/export.cpp#L1666

The goal is to set the placeholder text dynamically based on the value of the editor setting. You can get the editor setting's value using `EDITOR_GET("path/to/editor_setting")`.

**Comment by akien-mga** [comment]
Note that if you add placeholders filled with values from editor settings, you should still make it clear when those placeholders are actually not going to be used - i.e. the original issue @HaywardMorihara ran into, which is that if you set `keystore/debug`, it will *not* use the editor settings but it will expect `keystore/debug_user` and `keystore/debug_password` to be filled.

So there should likely be a warning when `keystore/debug` is filled but not the other ones (similarly with `keystore/release`).

**Comment by Calinou** [comment]
> which is that if you set keystore/debug, it will not use the editor settings but it will expect keystore/debug_user and keystore/debug_password to be filled.

Shouldn't we use the editor setting fallbacks for each setting individually? I think it has higher chances of working out of the box, compared to not using any username/password. (Can an Android debug keystore even be created without a pssword?)

**Comment by HaywardMorihara** [comment]
So it sounds like there are two possible approaches here. 

In both cases, we have initial placeholder values in the Export preset that reflect values from the `Editor Settings`. Once the user fills in `keystore/debug`, `keystore/debug_user`, or `keystore/debug_password`, either:

a) Clear out the remaining `keystore/debug*` placeholder values and supply a "warning" that reminds the users to fill in the other two values.

OR

b) Continue showing the placeholder values for the remaining two `keystore/debug*` values and modify Godot so that it falls back to using the `Editor Settings` for those values.

^ Is that correct?

**Comment by akien-mga** [comment]
Yeah that's correct :+1: 

Both options would be fine, but I think a) is the most explicit. It's unlikely that one would specify a custom `keystore/debug` (that would likely differ from the one in Editor Settings) and expect it to get the user and password that match a different keystore.

**Comment by HaywardMorihara** [comment]
I'm working on a pull request right now (attempting solution (a) where we have placeholders upfront, then clear the placeholders and provide warnings when only one of the three `keystore/debug*` options are filled in). 

One open question remains: _How do we supply a placeholder for `keystore/debug`_ (as @Calinou pointed out [earlier](https://github.com/godotengine/godot/issues/48787#issuecomment-842310074)).

I'm browsing through the code and the editor trying to find examples of the behavior we want (placeholder with a `PROPERTY_HINT_GLOBAL_FILE` export option) but I'm not finding anything. I'm not sure if it exists?

If not, then it I can think of two solutions:
1. Modify the `ExportOption` or `PropertyInfo` struct and how they're consumed so that we can supply an additional placeholder value alongside the `PROPERTY_HINT_GLOBAL_FILE` value (I'm not familiar with these structs or how they're consumed, so I'm uncertain if this is a good idea or what exactly it would look like).
2. Leave `keystore/debug` without a placeholder. I think this might be reasonable, if we at least have the warning when only 1 or 2 of the `keystore/debug*` options are filled out. However, it would be inconsistent to have placeholders for `keystore/debug_user` and `keystore/debug_password`, but not `keystore_debug`. Maybe we forgo placeholders for all 3 and _just_ have a warning?

**Comment by Calinou** [comment]
> I'm browsing through the code and the editor trying to find examples of the behavior we want (placeholder with a PROPERTY_HINT_GLOBAL_FILE export option) but I'm not finding anything. I'm not sure if it exists?

This doesn't exist; you would have to implement a hint that combines both `PROPERTY_HINT_GLOBAL_FILE` and `PROPERTY_HINT_PLACEHOLDER_TEXT` somehow. The issue is that you can only supply one hint string, not two…

**Comment by akien-mga** [comment]
> Maybe we forgo placeholders for all 3 and just have a warning?

I'd go with that. It's not worth the trouble to add support for having placeholders on fields which already use another hint.
