### ISSUE TITLE
Project manager does not use the editor font settings

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#4879]
**Operating system or device - Godot version:**

Arch Linux 64bit - Godot 2.1alpha compiled with 0a046e6232cd6dc094423436da8bc1842a8e2645
**Issue description** (what happened, and what was expected):

Project manager window and script editor can't display Chinese characters

**Steps to reproduce:**

1. Clean custom fonts of editor and script editor in editor settings.
2. Set editor language to zh_CN.
3. Restart editor.

**Comment by akien-mga** [comment]
Yeah the project manager does not use the editor font settings currently, assigning to @reduz.

**Comment by reduz** [comment]
I think this is already fixed, does it still happen?

**Comment by Geequlim** [comment]
@reduz Yes, it was fixed. I'm closing this issue.
