### ISSUE TITLE
Possible bug with setget and shorthand assignment

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#48802]
**Godot version:**
Godot master, commit: cdb3726fe6c9d41701dc89e572c6b2631d14cf6f

**OS/device including version:**
Linux, Fedora 34

**Issue description:**
I think there might be a bug in the new setget implementation. It is best explained by considering following sample code:

```
var test : int = 0:
	get:
		return test
	set(value):
		test = value % 7
```

**Case 1 - Assignment without shorthand notation:**

```
func _ready():
	for i in 7:
		test = test + 1
		print(test)
```
--> this correctly prints 1 2 3 4 5 6 0

**Case 2 - Assignment with shorthand notation:**

```
func _ready():
	for i in 7:
		test += 1
		print(test)
```

--> this prints 0 0 0 0 0 0 0

I would expect both cases to return the same values, unless I'm misunderstanding something.

**Comment by novemberist** [comment]
Actually, the second case doesn't always print 0 0 0 0 0 but any apparently random number between 0 and 6 (but always the same number on every iteration)

**Comment by novemberist** [comment]
After some more testing, I have a little addendum: The behaviour described above is not reproducible if the assignment happens in an external script.

**Comment by Soupstraw** [comment]
I tested with the following script:
```
var x : int:
	get:
		print("get: ", x)
		return x
	set(value):
		print("set: ", value)
		x = value % 7

# Called when the node enters the scene tree for the first time.
func _ready():
	x += 1
	print("val: ", x)
```

Output:
```
set: 45789104
get: 4
val: 4
```
