### ISSUE TITLE
Damaged zip file for OS X export (built on Linux)

### ISSUE THREAD

**Issue by RKelln** [godotengine/godot#48803]
**Godot version:**

3.3
3.3.1rc2

**OS/device including version:**

Linux 64

**Issue description:**

Exporting project for OS X from Linux creates a zip file that opns on Linux but OS X sees as "damaged". Using 3.2.2 the zip file is OK.

**Steps to reproduce:**
Export project for OS X from Linux.

**Comment by bruvzg** [comment]
See #48076, is this same error?
If it is, this is the result of M1 support, and there's not much we can do about it.

macOS has some security measures we have to deal with:
- M1 can't run unsigned binaries at all, export template binary is "linker signed" for this reason.
- macOS Gatekeeper will report unsigned app with signed binary as "damaged".

This means, the export template can be either fully unsigned and completely unusable on M1 macs, or partially signed and rejected by the Gatekeeper on any mac if it has "quarantine flag" (e.g. downloaded from unknown location).

When exporting from macOS, the exported app is automatically signed (with ad-hoc signature, if none was provided by the user). But, unfortunately there's no Linux tool for signing macOS apps (signature format is quite complex and not fully documented).

To mitigate it you can either sign the exported project on macOS (or export it form the macOS, using GH actions or other CI if you do not have access to the mac), or the "quarantine flag" should be removed on the user side, after downloading the app (see aforementioned issue the commands and tools to do so).

Also, distribution platforms like Steam and some download tools like `wget` won't set "quarantine flag", and have this issue.

**Comment by RKelln** [comment]
Ah yes, I think it is the same, sorry only searched open issues. Thanks for following up.

**Comment by Calinou** [comment]
> Edit: It may make sense for now to disable exporting to OS X when not on OS X and put a link in to some docs for why this is the case and some workarounds. It is certainly unexpected behaviour.

There are still many Macs that can run unsigned applications out there, so I think this would be too drastic.

What we need to do instead is to display a warning on the export dialog (but it should not prevent exporting altogether).
