### ISSUE TITLE
Vsync enabled has no effect on godot 3.3 running on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by EduardoLemos567** [godotengine/godot#48801]
**Godot version:** v3.3.stable.official

**OS/device including version:**
Ubuntu 20.04.2 LTS x64
Gnome version: 3.36.8
Windowing system: X11
Godot running on GPU: GeForce GT 740M/PCIe/SSE2, OpenGL ES 3.0 Renderer
NVidia driver: 418.197.02
Monitor refresh rate: 60Hz

**Issue description:**
Engine with V-Sync on is running above 600 FPS, expected to run at monitor rate: 60Hz

**Steps to reproduce:**
(check if V-sync is checked)
Start any project, add camera and cube, press F6

**Comment by Calinou** [comment]
This is likely a third-party issue, as V-Sync is working here on Linux + NVIDIA.

**Comment by EduardoLemos567** [comment]
Yeah, my synchronization is off on the composer, it shows on the "nvidia x server settings", under "PRIME Display", do you think its related ? 
Also glxgears run without synchronization, even when it states its synchronized.
Maybe that's a driver related thing, my GPU is not supported by nvidia anymore, the 418 was the last driver version (from 2019).

**Comment by clayjohn** [comment]
As this is an issue either with a driver or with GPU settings, there is nothing actionable for us so I am closing this issue.
