### ISSUE TITLE
GDScript Parser skips reporting previous errors when reporting some types of errors.

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#48809]
**Godot version:**
master as of 18/5/2021

**OS/device including version:**
WIN 10

**Issue description:**
While working on #48804, I noticed that some errors stopped getting reported by the GDScript parser when an additional error was added. It appears the type of error is what causes it.

Note the below screenshots are using the multi-error reporting UI from the above PR. The UI code from the PR is not the culprit - I put a breakpoint at the below line where the parser is run, and it was only returning 1 result (expected 4).

https://github.com/godotengine/godot/blob/20765800803e7864fa6cd0b641c129c349429e6e/modules/gdscript/gdscript_editor.cpp#L134-L138

![image](https://user-images.githubusercontent.com/41730826/118646133-23dd3d80-b823-11eb-8cd1-0ded53a3485c.png)

And if I add the colon at the end of the line:

![image](https://user-images.githubusercontent.com/41730826/118646169-2fc8ff80-b823-11eb-8ab5-df40dbe22343.png)

cc @vnen

**Comment by YeldhamDev** [comment]
CC @vnen

**Comment by vnen** [comment]
There are two passes in the parser, the missing colon is caught by the first one while the missing identifier is caught by the second one. The second pass doesn't run if the first fails. Though I guess now there is enough checks on the second pass to handle inconsistencies on the first, so it might be possible to handle both when validating.

**Comment by EricEzaM** [comment]
Personally not convinced this is worth the effort.
