### ISSUE TITLE
Code minimap

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#4881]
Some text editors and IDEs have a code preview (minimap) next to the editor. It's very helpful, when you work with huge script. But it also clutters the view, so it should be optional feature. Minimap could also highlight selected word, that would be neat. But even a simple minimap would be just fine.

This is a separate issue from the big list #2982

![Atom editor](https://ugotsta.files.wordpress.com/2015/07/atom-minimap-highlight.png)

**Comment by Anutrix** [comment]
Anyone planning to do this?
