### ISSUE TITLE
Clarify or fix Node._ready description's implication of needing to enter the SceneTree.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#48810]
I think the [`_ready` documentation in the Node class](https://github.com/godotengine/godot/blob/master/doc/classes/Node.xml#L90) might be a bit misleading, if I understand things correctly.

> Called when the node is "ready", i.e. when both the node and its children have entered the scene tree.

If you instantiate a loaded `PackedScene` resource, I'm pretty sure the ready callbacks fire on the child nodes even *before* the node tree has been added to the SceneTree. So, there should either be an added note to mention standalone PackedScene instantiation cases and how they are different, or it shouldn't explicitly say that the trigger is "[entering] the scene tree", especially when there is an actual `_enter_tree` callback specifically dedicated for that.

**Comment by akien-mga** [comment]
> If you instantiate a loaded `PackedScene` resource, I'm pretty sure the ready callbacks fire on the child nodes even _before_ the node tree has been added to the SceneTree.

I don't think that's accurate, aren't you confusing with `_init`?

Test:
```gdscript
# Main.gd
extends Node2D

func _ready():
	print("Main: preload")
	var scn = preload("res://Child.tscn")
	print("Main: instantiate")
	var inst = scn.instance()
	print("Main: add_child")
	add_child(inst)
```
```gdscript
# Child.gd
extends Node2D

func _init():
	print("Child: init")

func _enter_tree():
	print("Child: enters tree")

func _ready():
	print("Child: ready!")
```

Output:
```
Main: preload
Main: instantiate
Child: init
Main: add_child
Child: enters tree
Child: ready!
```

**Comment by willnationsdev** [comment]
Oh, well, color me surprised. That's good to know. It strikes me as odd then that isolated scene instances don't have a way of knowing when their children have been created and then doing post-creation initialization *prior* to them ever being added to the SceneTree.

**Comment by akien-mga** [comment]
For the reference, with a `Subchild` node under `Child` in my above example:
```
Main: preload
Main: instantiate
Child: init
Subchild: init
Subchild: notification 18  # NOTIFICATION_PARENTED
Child: notification 20     # NOTIFICATION_INSTANCED
Main: add_child
Child: notification 18     # NOTIFICATION_PARENTED
Child: notification 32     # NOTIFICATION_ENTER_CANVAS
Child: notification 10     # NOTIFICATION_ENTER_TREE
Child: enters tree
Subchild: notification 32  # NOTIFICATION_ENTER_CANVAS
Subchild: notification 10  # NOTIFICATION_ENTER_TREE
Subchild: enters tree
Subchild: notification 27  # NOTIFICATION_POST_ENTER_TREE
Subchild: ready!
Subchild: notification 13  # NOTIFICATION_READY
Child: notification 27     # NOTIFICATION_POST_ENTER_TREE
Child: ready!
Child: notification 13     # NOTIFICATION_READY
```

So if you need to sync stuff with child nodes before entering the scene tree, you can likely do so by listening to `NOTIFICATION_INSTANCED`, which seems to be emitted once the node has been fully instanced (and thus all its child nodes have been initialized and parented).

**Comment by willnationsdev** [comment]
Honestly, this exact code and output example combination should be added to the docs and linked to from every one of these methods, lol.

**Comment by Calinou** [comment]
> Honestly, this exact code and output example combination should be added to the docs and linked to from every one of these methods, lol.

Feel free to open a pull request for that :slightly_smiling_face:

**Comment by akien-mga** [comment]
I think that's too rough an example to include in the class reference. I'd prefer a dedicated page in the online docs about the Node lifecycle that explains all this in detail.
