### ISSUE TITLE
AtlasTexture on Sprite3D displays inverted margin height

### ISSUE THREAD

**Issue by TheUltimateAbsol** [godotengine/godot#48816]
**Godot version:** 3.3.0

**OS/device including version:**

GLES2, Windows 10,  Intel (R) Graphics 630

**Issue description:**

When rendering an AtlasTexture in 3D through a Sprite3D or AnimatedSprite3D, the margin height is calculated in reverse of that from 2D, pushing the image downwards instead of upwards

This will cause any animations (such as those using an AnimatedSprite3D) to constantly shift positions up and down with unexpected behaviour, making sprite animations in 3D impossible with AtlasTextures

**Steps to reproduce:**
1. Create a Sprite3D
2. Give it an Atlas Texture
3. Change the AtlasTexture's margin "h" value and watch the sprite go down instead of up

Results: 
3D (goes downwards below the plane)
![image](https://user-images.githubusercontent.com/28760461/118693308-f1a6ee00-b7d8-11eb-8be9-8a5d7bb5cb13.png)

2D (goes upwards above the plane)
![image](https://user-images.githubusercontent.com/28760461/118693449-0aaf9f00-b7d9-11eb-958a-b11bc29c7047.png)

Workarounds:
1. Render to a separate viewport and then use that viewport as a viewport texture. This works, but requires a lot of overhead and will cause significant slowdown on mobile
2. Bite the bullet and readjust manually the position of every Sprite3D to match your desired margin
2. ???????
3. Recompile godot and fix the issue yourself before someone tells you that AtlasTextures are getting an overhaul in 4.0

**Minimal reproduction project:**

[AtlasTextureTest.zip](https://github.com/godotengine/godot/files/6503043/AtlasTextureTest.zip)

**Comment by Calinou** [comment]
Atlas textures are not supported in 3D.
