### ISSUE TITLE
Cross Compilation Fails on GCC 10 + MingW

### ISSUE THREAD

**Issue by swapshivam3** [godotengine/godot#48815]
**Godot version:**
Master Branch as on 18/5/2021

**OS/device including version:**
1. WSL2 Ubuntu 21.04 

**Issue description:**
Trying to cross compile for windows in WSL2 using scons fails saying GCC version is older than 7.  Using the POSIX configuration for mingw. "x86_64-w64-mingw32-gcc --version" returns "x86_64-w64-mingw32-gcc (GCC) 10-posix 20210408". I believe the issue is that the 'get_compiler_version' in 'methods.py' returns wrong value as the version fails the regex written in the code(as there is no decimal in this exact version of mingw being used) , which assigns -1 to the version and throws the error.

Bypassed the compiler version check and engine compiles fine.

```
user@LAPTOP-9SHAV8KV:/mnt/d/godot/godot$ scons -j8 platform=windows bits=64
scons: Reading SConscript files ...
Package xcursor was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcursor.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xcursor' found
xcursor not found.. x11 disabled.
Configuring for Windows: target=debug, bits=64
Using MinGW
x86_64-w64-mingw32-g++ (GCC) 10-posix 20210408                       //output of print( subprocess.check_output([env.subst(env["CXX"]), "--version"]).strip().decode("utf-8"))
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
None                                                                  //output of print(re.search("[0-9]+\.[0-9.]+", version))
Detected GCC version older than 7, which does not fully support C++17. Supported versions are GCC 7, 9 and later. Use a newer GCC version, or Clang 6 or later by passing "use_llvm=yes" to the SCons command line.
 ```

**Comment by MmAaXx500** [comment]
Hi! I have a fix for that here: mmaaxx500@1ef0980a23b44c329c7b195fe0f966bae266b7b2
I have changed the regex pattern and with that we can extract a total of 6 fields to use in version checking. You can take a look at the pattern [here](https://regex101.com/r/M5c88N/1).
Should I open a pr with that?

**Comment by akien-mga** [comment]
@MmAaXx500 This regex would work for the above mingw distribution, but not necessarily for many others, or for non mingw compilers. We can't make such assumptions on the string that will be passed by any compiler distribution as this can be configured arbitrarily by the compiler vendors or distributors.

**Comment by MmAaXx500** [comment]
@akien-mga I've tried as many compilers as I can from Debian, Ubuntu, Arch, Fedora and Msys. Please look at the tests at the last link of my previous comment.

> Instead, the code should handle such cases gracefully when it can't retrieve an accurate compiler version, and proceed to compiling the code with no guarantees given that it won't fail.

So if the value of the field value is the default just ignore it.
`cc_version_major < 7` become `-1 < cc_version_major < 7` Am I right?

**Comment by akien-mga** [comment]
> I've tried as many compilers as I can from Debian, Ubuntu, Arch, Fedora and Msys. Please look at the tests at the last link of my previous comment.

I see, that looks good. That could be a good fix then. I maybe wouldn't initialize variables in `SConstruct` for things which we don't care about though (patch, date, metadata2).

>  `cc_version_major < 7` become `-1 < cc_version_major < 7` Am I right?

Yeah, or:
```
if cc_version_major == -1:
    print("Couldn't detect compiler version, skipping version checks. Build may fail if the compiler doesn't support C++17 fully.")
elif cc_version_major < 7:
    ...
```

**Comment by MmAaXx500** [comment]
I have done these changes and updated the branch: https://github.com/MmAaXx500/godot/commit/48da5498b95d4465dc92a9cbb8c37e53301a89f8

**Comment by akien-mga** [comment]
Looks good, feel free to make a PR with the commits squashed.
