### ISSUE TITLE
Popup Export Template Manager can't manage different fonts

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#48826]
**Godot version:**

3.3.1 mono stable

**OS/device including version:**

Debian 10

**Issue description:**

After download export template:
![DeepinScreenshot_select-area_20210519080434](https://user-images.githubusercontent.com/13235119/118764488-e3f57500-b879-11eb-9fbb-c1b68aa4b95b.png)

**Steps to reproduce:**
Install Terminus (TTF)  fonts in godot then install export templates in godot

**Minimal reproduction project:**

Not related to any project

**Comment by akien-mga** [comment]
Fixed by #49245.
