### ISSUE TITLE
ViewportRotationControl focuses on opposite view when clicking the Z axis (front instead of rear and vice versa)

### ISSUE THREAD

**Issue by DrRevert** [godotengine/godot#48832]
**Godot version:**

3.3.1

**OS/device including version:**

Windows 10

**Issue description:**

The compass visible in 3D, called ViewportRotationControl in source, has an incorrect behavior when the Z axis is clicked to focus on front/rear view. After single press it focuses the view in opposite direction, (front instead of rear and vice versa). Second click on Z axis does nothing. X and Y axes are working correctly.

**Steps to reproduce:**
1. Open any scene in 3D in which front, rear, left, right directions can be easily distinguish.
2. Position the camera to face front
3. Press Z axis on the compass, notice it focused on rear instead
4. Press Z axis again, notice nothing happened
5. Press X axis and compare the behavior.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This may be intended behavior. In Godot, the "forward" direction is Z-, not Z+.

cc @aaronfranke

**Comment by Calinou** [comment]
This is likely a copy editing error because in Godot, "forward" is Z- instead of Z+.
