### ISSUE TITLE
Profiler should display method name in the tooltip

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#48835]
**Godot version:**

3.3

**Issue description:**

I profiled my game and found this:
![image](https://user-images.githubusercontent.com/2223172/118804908-93940c80-b8a5-11eb-842a-3a7808675bc6.png)
The method names are cut off. Can be easily solved by expanding the list horizontally, but it would be more practical if the tooltip included the method name. Right now it only includes path:
![image](https://user-images.githubusercontent.com/2223172/118805062-c6d69b80-b8a5-11eb-83f8-3eee7f373322.png)

The tooltip could be something like
```
method name
source
```

**Comment by muchachordo** [comment]
Hi, I would like to tackle this as my first contribution

**Comment by Calinou** [comment]
@muchachordo It looks like someone made a *commit* for this in their fork, but they never opened a pull request for it: https://github.com/CrispyPin/godot/commit/4a288e4cc23c508246475aa8fdfad2acdca583f4

**Comment by CrispyPin** [comment]
Oh yeah, I never forgot to open it before
