### ISSUE TITLE
Can't extract binary file from an archive

### ISSUE THREAD

**Issue by gravit22** [godotengine/godot#48838]
**Godot version:**
3.3.1

**OS/device including version:**
Ubuntu 21.04

**Issue description:**
When I try to exctract binary file from downloaded Godot_v3.3.1-stable_x11.64.zip archive, I get a folder instead of a file. I do it with "file-roller", "Archive Manager" 3.38.1. 

**Steps to reproduce:**
Click on the archive with right mouse button and choose "Extract here".

**Minimal reproduction project:**
My OS with my version of archive manager.

**Comment by Zireael07** [comment]
Weird, Ark on Manjaro extracted the binary file with zero problems.

**Comment by gravit22** [comment]
Yeah, That is probably something with "Archive Manager" of that version. I just tried to compress binary file I extracted with different archive manager, and then extract it with "file-roller" and it brings the same issue. Very weird, never had that before.

**Comment by gravit22** [comment]
Ok that is weird. I tried it after renaming the archive to something else, and it solved the issue. 
It is probably something wrong with archive manager.

**Comment by akien-mga** [comment]
We had a misunderstanding on Facebook, I meant that you should report the bug to Ubuntu's bug tracker, not Godot's. It's a `file-roller` bug, and Ubuntu developers should see if that's fixed upstream and they can backport a fix, or update the package.

**Comment by gravit22** [comment]
Oh. Ok. Sorry.
