### ISSUE TITLE
Recent regression in TPS demo

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#48840]
**Godot version:**
Latest 3.x 365ab88
Worked in 3.3 stable
Works in 3.3.1 (so maybe not cherry picked)
Bisected to @lyuma commits on May 14th 2021.

**OS/device including version:**
Linux Mint 20, Intel HD Graphics 630

**Issue description:**

Open scene red_robot.tscn from TPS demo. Laser was showing when it should be hidden.

Broken (shows laser)
![Screenshot from 2021-05-19 13-52-00](https://user-images.githubusercontent.com/21999379/118816370-02736480-b8aa-11eb-809b-8a2641cdcbb0.png)
Working (laser not showing)
![Screenshot from 2021-05-19 13-51-30](https://user-images.githubusercontent.com/21999379/118816383-056e5500-b8aa-11eb-948a-0c15e0e1848b.png)

Just bisecting now, I thought it was due to BVH, but it seems to work after @pouleyKetchoupp 's May 4th PR so I'm not yet sure what is causing it.

**Comment by lawnjelly** [comment]
Looks like it is the @Chaosus / Iyuma commits on May 14th. I can't pin it down more than that easily as I'm using the artifacts.

**Comment by Chaosus** [comment]
It's because `z_local_coordinates` is used only in vertex but not in fragment - but the new default behavior is to use it if it's assigned in the vertex function.

**Comment by lawnjelly** [comment]
Ah fantastic, so a bit of a wild goose chase, down to exposing an error in the shader. But is good to have it fixed in the demo. :smile: :+1:

**Comment by lyuma** [comment]
This does seem like a regression in 3.x, caused by that unnecessary check added in the fragment-to-light varying code.

My opinion is that the "`Varying must only be used in two different stages`" check could be removed and it will act like it used to in this regard.

**Comment by Chaosus** [comment]
This check is originally suggested by @reduz so I've implemented it, but for 3.x this could be disabled to preserve the compatibility, I agreed.
