### ISSUE TITLE
Math::round icorrectly rounds big values

### ISSUE THREAD

**Issue by Shatur95** [godotengine/godot#48841]
**Godot version:**
6dad72db69453bc0395b90e6f931b56dc687fdb1

**OS/device including version:**
Any

**Issue description:**

`Math::round` returns `inf` for `DBL_MAX` because it adds `0.5` to the passed value that causes overflow for maximum value:

https://github.com/godotengine/godot/blob/365ab8889496b779690d97e25fdc4707641a5d61/core/math/math_funcs.h#L278

**Steps to reproduce:**

```cpp
double value = Math::round(DBL_MAX); // value will be inf
```

**Minimal reproduction project:**

Just add the following check:

```cpp
CHECK(Math::is_equal_approx(Math::round(DBL_MAX), DBL_MAX));
```

to `round/floor/ceil` test case in this PR: https://github.com/godotengine/godot/pull/48721

**Comment by lawnjelly** [comment]
I suspect there is a problem in your test. When I tried debugging:
```
	double d = Math::round(DBL_MAX);
	double d2 = Math::round(-DBL_MAX);

	float f = Math::round(FLT_MAX);
	float f2 = Math::round(-FLT_MAX);
```
In the code, the results after the round are the same, i.e. DBL_MAX is the same rounded.
I found the same in plain c++, adding 0.5 to DBL_MAX gives the same value (due to lack of precision), same with -DBL_MAX, same with floats.

What could cause an INF is if double is being truncated to float somewhere in the test.

The other possibility is different behaviour of your CPU (maybe using SSE), but a problem with the test seems more likely.

**Comment by lawnjelly** [comment]
And this correctly returns true on my machine:
```
bool equal = Math::is_equal_approx(Math::round(DBL_MAX), DBL_MAX);
```

**Comment by Shatur95** [comment]
Oh, sorry, I a little overlooked. You are right `Math::is_equal_approx(Math::round(DBL_MAX), DBL_MAX)` works correctly. I just had an issue with `Math::is_equal_approx` and `real_t` that you already mentioned in #48876.

But `Math::round` not works correctly too. Let's consider the following example:

```cpp
const double value = 9007199254740991;

const double round1 = std::round(value) << std::endl; // 9007199254740991.0
const double round2 = Math::round(value) << std::endl; // 9007199254740992.0
```

The fix suggested by @Yozzaxia1311 solves the problem:

```cpp
return (p_val >= 0) ? Math::ceil(p_val - 0.5) : Math::floor(p_val + 0.5);
```

**Comment by aaronfranke** [comment]
There is another problem caused by the implementation of `round` doing this: When double drops to only integer precision, adding `0.5` will round it to the nearest sum of powers of two (in this case, the nearest even number).

```gdscript
	var x = 4503599627370497.0
	print(x)
	print(round(x))
	print(floor(x))
```

Output:

```
4503599627370497
4503599627370498
4503599627370497
```

**Comment by Shatur95** [comment]
@aaronfranke, I was ahead of you by a couple of seconds :D
Yes, this is what I talking about.

**Comment by aaronfranke** [comment]
@Shatur95 Can you test if #48887 fixes this bug for you?

**Comment by Shatur95** [comment]
@aaronfranke, yes, thank you!
