### ISSUE TITLE
Black screen when running a project

### ISSUE THREAD

**Issue by Soupstraw** [godotengine/godot#48846]
**Godot version:**
Commit d0aaf4a

**OS/device including version:**
OS: Arch Linux x86_64
WM: bspwm
GPU: Nvidia GTX 1070
Vulkan backend

**Issue description:**
When I start the game with F5, I get a black screen. Editor 3D view works fine.
I am running with `--single-window -e --path ~/Documents/gd4project`.

**Steps to reproduce:**
Run the project from editor.

**Minimal reproduction project:**
Does not really depend on the project. I created a scene with a MeshInstance and a camera pointing at it.

**Comment by Calinou** [comment]
There is no default environment anymore, so you need to add a light to your scene to be able to see anything. (If you're placing an OmniLight or SpotLight, make sure it's not placed inside the mesh.)
