### ISSUE TITLE
Multiline text cursor in script editor

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#4884]
Cursor in script editor is able to point to more lines. When you write something, it is written on those lines simultaneously. Good reference could be this [Atom package](https://atom.io/packages/multi-cursor). As pigments #4882, this is especially usefull in web development so I'm not sure, how usefull this feature would be for game developers. Thus further discussion is welcome.

This is a separate issue from the big list #2982

**Comment by blurymind** [comment]
That would be quite cool in many cases 
![multiple_cursors](https://user-images.githubusercontent.com/6495061/36080337-74263fa6-0f86-11e8-8e17-f2fd6a80435a.gif)
:D

**Comment by Calinou** [comment]
@blurymind Please do not bump issues without significant new information, use the :+1: reaction button instead.

**Comment by justgage** [comment]
I still want this, but I found modifying the files in VSCode quite a nice experiance

**Comment by Calinou** [comment]
Closing, as this feature request is now tracked on the Godot proposals repository: https://github.com/godotengine/godot-proposals/issues/245
