### ISSUE TITLE
Highlight unused variables

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#4885]
NetBeans IDE is able to track down unused variables and highlight them. They are underlined and the tooltip is shown after a while on cursor hover. This feature should be very subtle.

This is a separate issue from the big list #2982
![unused](https://cloud.githubusercontent.com/assets/3484686/15635214/b799765c-25d8-11e6-898d-9722cb6dfb54.jpg)

**Comment by vnen** [comment]
This is hard to do with GDScript, at least for now. I don't think the editor have access to the parser to know if a variable is used or not.

**Comment by akien-mga** [comment]
Indeed, fixed by #19993.
