### ISSUE TITLE
Vulkan: Use Parent Material doesn't work

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#48861]
**Godot version:**

1450a72

**Steps to reproduce:**
1. Create a 2D scene with a Sprite2D child
2. Assign any material to the root, e.g. this invert shader
```
shader_type canvas_item;

void fragment() {
	COLOR.rgb = vec3(1) - texture(TEXTURE, UV).rgb;
}
```
3. Enable "Use Parent Material" in the sprite
4. Expect that the sprite will use the above-attached shader
5. You will get disappointed

**Comment by Calinou** [comment]
Can you reproduce this on `3.x`?
