### ISSUE TITLE
Cannot use UNIX domain sockets despite StreamPeer docs

### ISSUE THREAD

**Issue by RangerMauve** [godotengine/godot#48862]
**Godot version:** 3.3.1

**OS/device including version:**

Linux, Pop OS 21 (applies to all linux variants)

**Issue description:**

The docs for the [StreamPeer](https://docs.godotengine.org/en/stable/classes/class_streampeer.html) API mention that it supports UNIX sockets, however looking at the docs and the source it seems that only IP addresses are accepted by the [connect_to_host](https://github.com/godotengine/godot/blob/master/drivers/unix/net_socket_posix.h#L82) and [bind](https://github.com/godotengine/godot/blob/master/drivers/unix/net_socket_posix.h#L80) methods.

The interfaces can only take an [IPAddress](https://github.com/godotengine/godot/blob/master/core/io/ip_address.h) instance, and sadly that only supports `*` and IPv4/Ipv6 addresses. For some reason it looks like the HTTP Client [allows a trailing `/` in the URL which could be interpreted as a unix domain](https://github.com/godotengine/godot/blob/master/core/io/http_client.cpp#L132)

A potential fix would be to allow strings in he IPAddress class, and to detect that it's a unix domain socket in the net_socket_posix code.

It would also be useful to enable [Windows named pipes](https://docs.microsoft.com/en-us/windows/win32/ipc/named-pipes) in the windows networking code, but I haven't been able to find where that is yet. 😅

Is this a documentation issue, or are UNIX sockets supposed to be supported?

**Steps to reproduce:**

Attempt to connect to a UNIX socket using TCP, the connection fails because the format isn't an IP address.

**Minimal reproduction project:**

n/a

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
Unix socket are not supported. There are no plans to adding support for it.
Should probably open a proposal in case, but it's a bit too domain specific IMO.

**Comment by akien-mga** [comment]
Maybe the docs should be amended to avoid giving that impression?

> StreamPeer is an abstraction and base class for stream-based protocols (such as TCP or UNIX sockets). It provides an API for sending and receiving data through streams as raw data or strings.

What's inferred is that StreamPeer can likely be used as base class for implementing a StreamPeerUNIXSocket, but not that the latter is supported as is.

**Comment by Faless** [comment]
Yes, we can remove referencing UNIX sockets. I'll make a PR.

**Comment by RangerMauve** [comment]
Thank you for the quick response and clarification! 😁
