### ISSUE TITLE
Translated string not showed in Project manager

### ISSUE THREAD

**Issue by xevinbox** [godotengine/godot#4887]
**Operating system or device - Godot version:**
Ubuntu 16.04 (64bit) - Godot v2.1.alpha.custom_build

**Issue description**
I add russian translation. In Project manager text strings are empty.
In Editor all fine.
Project manager and editor use various fonts?

**Steps to reproduce:**
* [get ru_RU.po from my branch](https://github.com/xevinbox/godot/blob/ru_translation/tools/translations/ru_RU.po)
* build
* run
* see buttons without text in Project Manager

**Comment by akien-mga** [comment]
Thanks for the report. It appears to be the same issue as #4879, so closing it as duplicate.
