### ISSUE TITLE
Window `borderless` property doesn't work properly (DisplayServer regression)

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#48875]
**Godot version:**

4.0

**OS/device including version:**

Windows10

**Issue description:**

Execute code like this:
```
var window = get_viewport()
window.borderless = true
```
Game window become white and can't click(click pass through)
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by SPOICAT** [comment]
You could try `OS.set_borderless_window(value)`
It works for me.

**Comment by Calinou** [comment]
> You could try `OS.set_borderless_window(value)`
> It works for me.

In the `master` branch, the borderless window property was moved to be settable on a per-window basis. See the [Core refactoring progress report #2](https://godotengine.org/article/core-refactoring-progress-report-2) for more information.

**Comment by CsloudX** [comment]
It look like work fine in current beta2, can I close this issue?
