### ISSUE TITLE
bug in the Meshinstance 

### ISSUE THREAD

**Issue by sriyeshsai** [godotengine/godot#48877]
godot version
3.3
issue:

![Godot Engine - test project - the ball tscn 20-05-2021 14_06_26](https://user-images.githubusercontent.com/84183693/118947091-a1649300-b974-11eb-98f8-f899cb2d49fd.png)
![test project (DEBUG) 20-05-2021 14_07_22](https://user-images.githubusercontent.com/84183693/118947196-bb05da80-b974-11eb-8f50-80a1c162b53b.png)

the game interface crashes when i use a color for the meshinstance to the player this stops the work i'm doing now pls help me in this 
Steps to reproduce the problem :
1) select a kinematic body 
2) add a collision shape
3) provide meshinstance 
4) input the kinematic body with basic script
5)add color to the mesh instance 
     material->>New spatial material->>albedo->>color
6)run the scene
summary:
same problem is happening when i import a 3D body from blender to Godot 
pls find me a solution as soon as possible

**Comment by sriyeshsai** [comment]
@https://github.com/Calinou

**Comment by Zireael07** [comment]
You didn't fill out the template. Since it's happening without the exporter, and since no one else has reported something like this, I suspect this is a driver bug. What is your graphics card and OS?

**Comment by Calinou** [comment]
@sriyeshsai Try switching to the GLES2 renderer in the Project Settings (**Rendering > Quality > Driver > Driver Name**) then restart the editor.

**Comment by akien-mga** [comment]
Please attach a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) so that we can test in the same conditions that you do. Otherwise the steps you give to reproduce the bug are not explicit enough to properly replicate it.

**Comment by sriyeshsai** [comment]
> You didn't fill out the template. Since it's happening without the exporter, and since no one else has reported something like this, I suspect this is a driver bug. What is your graphics card and OS?

Os: windows 10 home 64bit
Graphic card : intel 630 UHD 2gb inbuilt graphic card

**Comment by sriyeshsai** [comment]
> Please attach a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) so that we can test in the same conditions that you do. Otherwise the steps you give to reproduce the bug are not explicit enough to properly replicate it.

Pls sir provide me your personal mail so I can send the full details of the minimal reproduction project

**Comment by sriyeshsai** [comment]
> @sriyeshsai Try switching to the GLES2 renderer in the Project Settings (**Rendering > Quality > Driver > Driver Name**) then restart the editor.

I will check that out and reply within 48 hours sir

**Comment by sriyeshsai** [comment]
> > @sriyeshsai Try switching to the GLES2 renderer in the Project Settings (**Rendering > Quality > Driver > Driver Name**) then restart the editor.
> 
> I will check that out and reply within 48 hours sir

Sorry for late reply sir

**Comment by sriyeshsai** [comment]
> > @sriyeshsai Try switching to the GLES2 renderer in the Project Settings (**Rendering > Quality > Driver > Driver Name**) then restart the editor.
> 
> I will check that out and reply within 48 hours sir

Sorry for late reply sir

**Comment by sriyeshsai** [comment]
> > Please attach a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) so that we can test in the same conditions that you do. Otherwise the steps you give to reproduce the bug are not explicit enough to properly replicate it.
> 
> Pls sir provide me your personal mail so I can send the full details of the minimal reproduction project

Sorry for late reply sir

**Comment by sriyeshsai** [comment]
> > You didn't fill out the template. Since it's happening without the exporter, and since no one else has reported something like this, I suspect this is a driver bug. What is your graphics card and OS?
> 
> Os: windows 10 home 64bit
> Graphic card : intel 630 UHD 2gb inbuilt graphic card

Sorry for late reply sir
