### ISSUE TITLE
Windows icon is not correct Godot v3.3.1

### ISSUE THREAD

**Issue by Can202** [godotengine/godot#48898]
Godot Mono 3.3.1 (Rcedit v1.1.1)

Windows 

When I export my project, the icon is not seen

https://user-images.githubusercontent.com/67566612/119021199-2350be00-b96d-11eb-85c9-518146d5f30c.mp4

**Comment by Can202** [comment]
is this bad?

![ssss](https://user-images.githubusercontent.com/67566612/119028697-c1e11d00-b975-11eb-9d5a-b0f43071197e.PNG)

**Comment by Calinou** [comment]
> is this bad?

Those version numbers should be written as `0.4.0.0` to be considered valid.

**Comment by Gamemap** [comment]
@Can202 I think you need to have an .ico file with multible picture layers. (16x16, 32x32, 64x64 ...)

**Comment by Can202** [comment]
maybe but I didn't need it on Godot v3.2.3, well, i will see how to do it

**Comment by Can202** [comment]
> 
> 
> > is this bad?
> 
> Those version numbers should be written as `0.4.0.0` to be considered valid by rcedit (and Windows).

it doesn't work

**Comment by Deozaan** [comment]
> Those version numbers should be written as `0.4.0.0` to be considered valid by rcedit (and Windows).

I just tested this in 3.3.1-stable and I found that it automatically adds any missing numbers to make it fit what Windows expects.

See this image for reference:

![Godot Exports](https://user-images.githubusercontent.com/227734/119208589-21b3f280-ba60-11eb-8e52-81e7d069cb19.png)

In the one labeled 0.0.0.0 I didn't enter anything in the version field. (I also forgot to specify the custom icon file... 🤦)
In the one labeled 2.0.0.0 I entered "2" in the version field.
In the one labeled 2.13913.0.0 I entered "2.210521.0" in the version field. It seems 210521 is too large of a number for that field (16-bit integer) and it wrapped back down to zero (210,521 mod 65,536).
In the one labeled 2.2105.21.0 I entered "2.2105.21.0" in the version field.

All three of the ones I specified the custom icon for appear to be working as expected for all sizes of thumbnails.

@Can202 I suspect that @Gamemap has made the correct assessment, and that your icon needs to include multiple resolutions.

Try editing/opening your icon in something such as IcoFX or Greenfish Icon Editor and make sure it has all the relevant sizes similar to what's shown here:

![Greenfish Icon Editor Pro](https://user-images.githubusercontent.com/227734/119208744-bf0f2680-ba60-11eb-95e3-1ed0cf518d3d.png)

You can get Greenfish Icon Editor Pro (open source, and has a portable version) here:  
http://greenfishsoftware.org/gfie.php

You can get IcoFX (portable) here:  
https://portableapps.com/apps/graphics_pictures/icofx_portable

**Comment by Can202** [comment]
gracias voy a ver

**Comment by Can202** [comment]
Thanks, I will see it

**Comment by Can202** [comment]
now it works 
Thanks to Deozaan for the program

**Comment by Can202** [comment]
now it is necessary to do that apparently
