### ISSUE TITLE
get_viewport().content_scale_size bug

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#48890]
**Godot version:**

4.0

**OS/device including version:**

windows10

**Issue description:**

If execute code like this:
```
get_viewport().content_scale_size = Vector2i(500,400) 
```
I can't recv any _unhandled_input.
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@CsloudX Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by CsloudX** [comment]
It's likes fixed...
