### ISSUE TITLE
[Linux] Godot only finds apksigner.jar if the filename doesn't end in .jar

### ISSUE THREAD

**Issue by sosasees** [godotengine/godot#48897]
**Godot version:** 3.3.stable.official

**OS/devices including version:**
My computer I use the Godot Editor on, runs Linux.
My phone I export my game to, runs Android 11.

**Issue description:**

I expected that if the Android SDK directory is specified, Godot would just find the Apksigner.
Instead, Godot only found the _apksigner.jar_ program once I created a Symbolic Link of it in its original directory, being named just _apksigner_, without the _.jar_ ending.

**Steps to reproduce:**
1. Install the Android SDK with the _Command Line Tools_ method in [this guide](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html). My Android SDK directory is `/lib/android-sdk`.
2. Download the reproduction project (Or create a new Godot project with Android Export Settings).
3. Specify the usual prerequisites of exporting a Godot Project to Android,
including the newly-installed Android SDK directory, under
_Editor Settings → Export → Android_.
4. Attempt to Export the Project for Android. Note the 2 error messages blocking the Android export (The images are approximated with "Text Art" so you can copy-paste the text inside):
```
┌─────────────────────────────────────────────────────────────────────────┐    
│                               Load Errors                             X │
├─────────────────────────────────────────────────────────────────────────┤    
│ 🔴 Unable to find Android SDK build-tools' apksigner command.            │ 
│ Please check in the Android SDK directory specified in Editor settings. │ 
│                                                                         │
│                                                                         │
│                                                                         │
│                                                                         │
│                                                                         │
│                                                                         │
│                                                                         │
├─────────────────────────────────────────────────────────────────────────┤
│                                 > OK <                                  │
└─────────────────────────────────────────────────────────────────────────┘ 

┌──────────────────────────────────────┐
│               Warning!             X │
├──────────────────────────────────────┤
│ Unable to find the 'apksigner' tool. │ 
├──────────────────────────────────────┤
│        > OK <   > Copy Text <        │
└──────────────────────────────────────┘
```
5. Use the Terminal to make the working `jarsigner` file:
5.1 Navigate to the Android SDK Build Tools directory using the command `cd /lib/android-sdk/build-tools/*/` (Replace _/lib/android-sdk_ with the Android SDK directory you specified, if it's different)(Replace _*_ with the actual name of the directory that you find on your computer. For me, this directory is named _debian_.).
5.2. Create the symlink using `sudo ln -s jarsigner.jar jarsigner`. Or rename the original file using the move operation `sudo mv jarsigner.jar jarsigner`.
6. Try again to export the project to Android. Note how it now works (unless Apksigner throws error #2, in which case you need to remove the Debug Keystore references from your project's Android Export Settings and leave it only in the Godot Editor Settings).

**Minimal reproduction project:**  [Empty Godot Project but with Android Export Settings](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#download-the-android-sdk)

**Comment by akien-mga** [comment]
> Install the Android SDK with the _Command Line Tools_ method in [this guide](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html). My Android SDK directory is `/lib/android-sdk`.

>  5.1 Navigate to the Android SDK Build Tools directory using the command `cd /lib/android-sdk/build-tools/*/` (Replace _/lib/android-sdk_ with the Android SDK directory you specified, if it's different)(Replace _*_ with the actual name of the directory that you find on your computer. For me, this directory is named _debian_.).

This sound to me like you're mixing a manual installation of the Android SDK with a pre-existing installation of the Debian packaged Android SDK, which is not recent enough for Godot. The folder in `build-tools` should be `30.0.3`, not `debian`.

When manually installing an SDK on your system, it's usually better to install it e.g. in `$HOME` or in `/opt`, without trying to replicate typical distro-packaged paths, as you then do not know if you're using a Debian package or the SDK you installed from Google repositories.

**Comment by Sosasees** [comment]
Oh Boy! How could I still have parts of the Debian-packaged Android SDK installed?
I ran `sudo apt purge android-sdk` before reinstalling the Android SDK from the Godot Documentation's guide.

**Comment by Sosasees** [comment]
oops: i did not mean to mention this issue in #62559. i accidentally pasted the wrong number, but now it's corrected.
