### ISSUE TITLE
Allow for Editor/Viewport Input Control Profiles with Hotkeys to Change

### ISSUE THREAD

**Issue by PaulMoffat** [godotengine/godot#489]
Using Blender 2.7 as an example, it has been released with a FPS style navigation control system to allow in blender game levels to be navigated as if in game - perfect for virtual level previewing & analysis.

Seeing such a feature in Godot would definitely be a bonus but in my mind I can see a much more practical implementation to allow for input control profiles which can be quickly changed on the fly by customizable hot-keys to allow the user to switch between different control methods as they find necessary within the editor/view-port and other elements of Godots GUI interface.

ie. one for geometry editing, a second for general navigation and level previewing

**Comment by akien-mga** [comment]
Related to #2745.

**Comment by akien-mga** [comment]
This would likely be easier to implement now that #2745 is fixed.

**Comment by akien-mga** [comment]
This is kind of what the new freelook feature implements in the upcoming 3.0 version, so I guess it's fixed.
