### ISSUE TITLE
Cannot export to x86_64 and Apple Silicon for iOS project (to run in simulator)

### ISSUE THREAD

**Issue by atonamy** [godotengine/godot#48919]
**Godot version:**
3.3

**OS/device including version:**
Iphone 11 pro (simulator)

**Issue description:**
When I export  iOS project with GdNative I'm unable to select x86_64 and Apple Silicon target to run it in simulator. And final project exported as MyProjectName.a (and it's only arm architecture support)
<img width="500" alt="Screenshot 2021-05-21 at 4 24 58 PM" src="https://user-images.githubusercontent.com/5222190/119106654-20c79480-ba51-11eb-88b6-c9e2e15a72bf.png">

**Steps to reproduce:**
Add gdnative libs for x86_64 and arm64 for iOS then click Project menu then export you will see no x86_64 or   Apple Silicon (simulator) option architecture export.

**Minimal reproduction project:**
Use this example to replicate the issue https://github.com/godot-rust/godot-rust/tree/master/examples/spinning_cube

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
Should be fixed by #49248

**Comment by atonamy** [comment]
@bruvzg so I have to compile Godot from source of https://github.com/godotengine/godot/tree/3.x branch to test the fix?
