### ISSUE TITLE
Wrong error when emitting a signal with arguments

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4893]
On Godot 2.0.3, Windows 10, 64 bits:

I connected a signal emitted with arguments to a function that has no parameters.
It resulted in this error message:
```
ERROR: Object::emit_signal: Error calling method from signal 'custom_pressed': 'Node(test.gd)::on_press_1': Expected 0 arguments.
   At: core\object.cpp:1210
```
It should print this instead:
```
[...] Expected 3 arguments [...]
```
This made me loose time not understanding the error in a large project.
Here is a reproduction project: http://zylannprods.fr/dl/godot/SignalError.zip

I have two suggestions:
- Fix the wrong error message
- Allow signal handlers to have a different number of parameters?

**Comment by jackmakesthings** [comment]
I think the error message you got is correct - it's not the signal that "expects" arguments in this case, it's the function you're trying to connect to it. That function expects 0 arguments, and it's throwing the error because the signal tried to call it with several.

**Comment by Zylann** [comment]
You're right. So, actually it should be better if we could see both? How many argument sent, how many expected?
