### ISSUE TITLE
rect_scale not updated live in inspector

### ISSUE THREAD

**Issue by johnfn** [godotengine/godot#48936]
**Godot version:**
3.3

**OS/device including version:**
MacOS Catalina

**Issue description:**
Control > Rect > Scale does not update when I scale a control.

**Steps to reproduce:**
1. Create a control node (I used Label)
2. Scale the control node with the scale tool
3. Look at Control> Rect > Scale in the inspector. It still says x: 1, y: 1

If you save and reopen the scene, the scale is updated properly. 

**Minimal reproduction project:**

This reproduces in an empty project.

**Comment by Calinou** [comment]
This is likely an issue with `change_notify()` or `update()` not being called in the scale tool gizmo in `editor/canvas_item_editor_plugin`. Note that Node2D and Control scaling go through different code paths.

**Comment by phil-shenk** [comment]
_change_notify("rect_scale") seems to be missing in Control::set_scale in control.cpp (in 3.3 at least). PR incoming

**Comment by akien-mga** [comment]
Fixed by #48957.
