### ISSUE TITLE
Tweening a `rect_position` changes `rect_size`

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#48935]
**Godot version:**

3.3 / 3.3.1

**OS/device including version:**

Windows 10

**Issue description:**

Tweening a `rect_position` changes `rect_size`.
Either that, or it's causing `rect_size` to no longer be rounded properly.

After the tween, my output is:
```
rect_size: (16.000031, 22.000006)
rect_min_size: (16, 22)
```
The `rect_size` value changes slightly every time I run the game.
Before the tween, they were the same. 

**Steps to reproduce:**
1. Run the example project.
2. Press `Enter` and wait for the `breakpoint`. (For me, the `breakpoint` is reached every time)

**Minimal reproduction project:**

[Tween Resize Bug.zip](https://github.com/godotengine/godot/files/6524364/Tween.Resize.Bug.zip)

**Comment by Calinou** [comment]
@Error7Studios Can you reproduce this in Godot 3.2.3?

**Comment by Error7Studios** [comment]
Yes. But 3.2.3 doesn't switch to the debugger on `breakpoint`, so replace `breakpoint` with `get_tree().quit()` for testing.

**Comment by Xrayez** [comment]
I think this is floating point error accumulation issue. Perhaps changing `rect_global_position` (or just `rect_position`) forces recalculations of margins every frame when done via tween, but this is just a wild guess.

For instance, changing `$DEBUG CARG`'s node position closer to target no longer triggers the breakpoint: try setting `rect_position` to `Vector2(250, 10)` to see for yourself.

**Comment by Error7Studios** [comment]
> For instance, changing $DEBUG CARD' node's initial position closer to target no longer triggers the breakpoint: try setting rect_position to Vector2(250, 10) to see for yourself.

Can confirm.

> Setting rect_global_position = __to_global_pos after the tween has finished also resolves the problem

Yeah, as a workaround, I'm just manually setting the `rect_size` and `rect_min_size` after the tween just to be certain.
Might as well set the `rect_global_position`, too.

> (but even is_equal_approx() does not work in this case...)

`is_equal_approx()` works for me, even when `DEBUG CARD` starts far offscreen. Did you forget the `!` symbol?

Just weird that a `rect_position` tween affects the `rect_size`. They should have nothing to do with each other.

**Comment by Xrayez** [comment]
> Did you forget the `!` symbol?

Yeah... It's also possible to use `not` operator.

> Just weird that a `rect_position` tween affects the `rect_size`. They should have nothing to do with each other.

It depends. `Control` properties are not always changed via inspector. If you use one of the `Container` nodes, then a lot of the properties such as margins are going to be overridden at run-time.

If `rect_position` depends on other properties such as margins, then it's certainly possible that it could affect `rect_size` in some way, but I'm not an expert in GUI system in Godot.

**Comment by KoBeWi** [comment]
I think this is a problem of how rect position is handled internally. When you modify it, you modify the Control's transform matrix, which might also affect size. I tried tweening `rect_position` and `rect_global_position` and it yielded different results. So this is just floating point issue, hence why `is_equal_approx()` helps.
