### ISSUE TITLE
Vector2 doesn't do int -> float casting

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#48932]
Engine built from 8c2beeea9

Take a Vector2 and assign an int value to it, it doesn't get casted to a float I believe:

```
var test: Vector2 = Vector2(1.0, 1.0)

func _ready():
    test.x = -1
    print(test)
```

Results in:
`(nan, 1)`

However, setting it to a float directly does work:

```
var test: Vector2 = Vector2(1.0, 1.0)

func _ready():
    test.x = -1.0
    print(test)
```

Results in:
`(-1, 1)`

**Comment by amoriqbal** [comment]
I have verified this on Linux Mint.
using `var test = Vector2(1.0, 1.0)` instead of `var test: Vector2 = Vector2(1.0, 1.0)` works fine too.

**Comment by briansemrau** [comment]
This is the same issue as #45172

**Comment by EIREXE** [comment]
> 
> 
> This is the same issue as #45172

Correct, closing.

**Comment by Chaosus** [comment]
Duplicates should be closed
