### ISSUE TITLE
Regular editor freezes

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4894]
Windows 10, Godot 2.0.3, 64 bits

I am regularly getting freezes with the editor.
Unfortunately I've not been able to find a reproduction yet, and I cannot attach the C++ debugger because it says "only external code is executing" (Visual Studio).
There are no errors in the console.

So far, here is what I was doing for a few occurences of the freeze:
- Saving a scene, Godot froze at the loading popup
- Writing code
- Writing code
- Saving script after writing code
- Clicking into the code editor

I used the editor for 30 minutes, and now it freezes every 2 minutes and I have to kill and restart it. Then after about 4 freezes, it continues to work normally. That's a bit random. There is not much difference in my usage between those periods, I'm writing code for animated GUI elements.

**Comment by volzhs** [comment]
I had this experience once. no error on console and just freeze.
I think it happens when click script editor.

**Comment by reduz** [comment]
Unfortunately there is not much that can be done if you can't specify or try to isolate exact steps to reproduce or or an example project where this happens

**Comment by Zylann** [comment]
If it can help, I found that holding Ctrl+Z to make it spam undo is likely to cause an editor crash. But maybe that's not the only symptom.

**Comment by reduz** [comment]
I think this might have been fixed, please give it a check

**Comment by reduz** [comment]
the undo/redo crashes/freezes were fixed long ago, so I think this can be closed, if it happens again please let me know

**Comment by Altair1234** [comment]
Can someone reopen this issue? Hasn't been fixed as of 3.1

**Comment by Calinou** [comment]
@Altair1234 This issue is very old, you should create a new issue instead. Please include your hardware/software configuration as well as any steps that may cause the editor to freeze.
