### ISSUE TITLE
New 3D import: GLTF importer creates no collision for -col objects

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#48945]
Here's a source .blend file:
[Village.zip](https://github.com/godotengine/godot/files/6525359/Village.zip)
![image](https://user-images.githubusercontent.com/491704/119204906-06b0a500-ba97-11eb-85e8-597c72924427.png)
Note the texture mapping and the fact that meshes do have `-col` attribute in their names.

This is how Godot 3.3.1 imports a resulting GLTF file:

![image](https://user-images.githubusercontent.com/491704/119205787-8fc8db80-ba99-11eb-80ae-01f6fb1a0693.png)

Godot 4 does not create any collision nodes:

![image](https://user-images.githubusercontent.com/491704/119205857-c0107a00-ba99-11eb-8968-6e621ea3e2c1.png)

**Comment by Calinou** [comment]
As far as I know, this is intentional because the new 3D import system does not rely on import hints anymore: https://github.com/godotengine/godot-proposals/issues/1823

**Comment by unfa** [comment]
It seems that's the case.
the problem is - the current state of the advanced import dialog. does not allow to enable collision for more than one object at time -  for large scenes with many objects this is really bad.

**Comment by lyuma** [comment]
Seems to no longer be an issue in 4.0 release candidates.
![image](https://user-images.githubusercontent.com/39946030/220891610-33e526b0-dcf7-401f-b6c1-82c1437ef225.png)
