### ISSUE TITLE
GDNative lib ignores arm64 macos architecture

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#48959]
**Godot version:**

Godot 3.3.1-stable

**OS/device including version:**

MacOSX 10.15.7 (19H2)

**Issue description:**

I have this gdnlib file:
```
[general]

singleton=true
load_once=true
symbol_prefix="gamecenter_"
reloadable=false

[entry]

OSX.64="res://addons/gamecenter-osx/libgamecenter_universal.dylib"
OSX.arm64="res://addons/gamecenter-osx/libgamecenter_universal.dylib"

[dependencies]

OSX.64=[  ]
OSX.arm64=[  ]
```

When I open this file in Godot I see:
![Снимок экрана 2021-05-22 в 13 37 33](https://user-images.githubusercontent.com/1177068/119223577-efa79c80-bb02-11eb-8e43-195eb208773d.png)

I can add `arm64` manually (then arm64 lib appeared in editor):
![Снимок экрана 2021-05-22 в 13 38 44](https://user-images.githubusercontent.com/1177068/119223612-1665d300-bb03-11eb-85f0-c2440f48b7d7.png)

When I exit from Godot and open this project again the arm64 library again disappears.

**Steps to reproduce:**
Just try to use GDNative library on MacOS with arm64 architecture.

**Minimal reproduction project:**

**Comment by Xrayez** [comment]
I think it's a feature which is currently not implemented yet in GDNative (see also #39943).

**Comment by DrMoriarty** [comment]
@naithar @bruvzg Hi! Do you know if anybody is working on this feature? I want to implement it but it may be faster to collaborate with someone.

**Comment by bruvzg** [comment]
Single `OSX.64` entry with the universal library should work on both Intel and M1 macs.

And adding separate `arm64` and `x86-64` to the editor UI, should be as easy as changing these lines https://github.com/godotengine/godot/blob/3b3a55ca04331e85cc24ac315b60e7ad4aeb17df/modules/gdnative/gdnative_library_editor_plugin.cpp#L282-L283 `32` can be removed, and `64` probably can be renamed to `universal`.

**Comment by bruvzg** [comment]
> And adding separate <code>arm64</code> and <code>x86-64</code> to the editor UI, should be as easy as 
<code>32</code> can be removed, and <code>64</code> probably can be renamed to <code>universal</code>.

I have these changes as part of #46866 / #46860 PR, which also add support for GDNative framework.

**Comment by naithar** [comment]
> @naithar @bruvzg Hi! Do you know if anybody is working on this feature? I want to implement it but it may be faster to collaborate with someone.

Using a single universal `.dylib` file in any configuration should probably be enough for most cases, since macOS doesn't use same architecture for different targets, unlike iOS, where both device and simulator use `arm64`.

**Comment by DrMoriarty** [comment]
Thank you! Using OSX.64 was enough to build fat binary with arm64.

**Comment by akien-mga** [comment]
This was fixed a long time ago.
