### ISSUE TITLE
Editor settings window doesn't display last letter of entry headers

### ISSUE THREAD

**Issue by Nosliwnayr** [godotengine/godot#48951]
**Godot version:**
Commit 3b3a55ca04331e85cc24ac315b60e7ad4aeb17df

**OS/device including version:**
Fedora 34 Workstation, Vega 64

**Issue description:**
Built the editor with LLVM/LLD following the instructions [here](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html#using-clang-and-lld-for-faster-development) and when I opened a new empty project and went to the editor settings I noticed that the settings headers are all missing the last letter of their entries.
See "Editor Languag", "Display Scal", etc. :
![image](https://user-images.githubusercontent.com/1634364/119209343-f24eb700-ba5a-11eb-879f-7aa9e41db0b7.png)

**Steps to reproduce:**

1. Open the editor
2. Open the "Editor Settings" window

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/3b3a55ca04331e85cc24ac315b60e7ad4aeb17df.

This will be fixed by https://github.com/godotengine/godot/issues/48951 once it's merged.

**Comment by Byteron** [comment]
same is true for inspector.
![image](https://user-images.githubusercontent.com/24433899/119217349-ef46db80-bad9-11eb-83c4-238b9da4c524.png)
