### ISSUE TITLE
Black Screen When Exporting As HTML5

### ISSUE THREAD

**Issue by ngreve** [godotengine/godot#48960]
**Godot version:**
Godot version: 4.0
Commit: 3b3a55ca04331e85cc24ac315b60e7ad4aeb17df

**OS/device including version:**
OS: Arch Linux
GPU: RX 6900XT
Backend: Vulkan
Browser: Chromium/Firefox

**Issue description:**
Scene works natively on the system (hitting F5 in the editor).

Scene does not work when using HTML5 export; screen stays black.
It does not matter if I export the project and run it with a local PHP server like `php -S localhost:3000` or if I use the editors build in web server (hitting the HTML5 Button in the editor).
 
Furthermore the tab does not respond to any input it seems, because I can not open the developer tools, after the loading bar has done its thing.

The demo project has a simple cube in it. With that cube, the console shows the following error:
![image](https://user-images.githubusercontent.com/18660100/119224018-c6840d80-bafc-11eb-94ed-8981440e654c.png)
 
Deleting the cube gets rid of that error, but the screen still stays black.

**Steps to reproduce:**
How I've build everything:
```
# Building the templates
scons platform=javascript tools=no target=release -j 12
scons platform=javascript tools=no target=debug -j 12
mv bin/godot.javascript.debug.zip bin/webassembly_debug.zip
mv bin/godot.javascript.opt.zip bin/webassembly.zip

# Building the editor for development
scons -j 12
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json ./bin/godot.linuxbsd.tools.64
```
(These building steps do work for Godot 3.x.)

**Minimal reproduction project:**
[html_gd4.zip](https://github.com/godotengine/godot/files/6526283/html_gd4.zip)

**Comment by akien-mga** [comment]
There's no renderer for HTML5 in the `master` branch yet, so this is expected. It will work once either WebGL or WebGPU support is implemented.
