### ISSUE TITLE
TabContainer tab name width problem using Localization

### ISSUE THREAD

**Issue by Po46n2** [godotengine/godot#48979]
**Godot version:**
v3.2.3

**Issue description:**
The width of the name of every tab is fixed to the tab's (node's) original name and it doesn't adjust when the text gets replaced to the one stored in the language file. So there is either extra space after the tab's name or not all of it is visible.

**Minimal reproduction project:**
[TabControlLocalization.zip](https://github.com/godotengine/godot/files/6526999/TabControlLocalization.zip)

**Comment by akien-mga** [comment]
This is fixed since version 3.3. Please try the latest stable release when reporting bugs.
