### ISSUE TITLE
Using mouse click + drag to change values in inspector numeric properties teleports mouse to top left of screen

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#48971]
**Godot version:**
master 78861fd

**OS/device including version:**
WIN 10

**Issue description:**
As title

**Steps to reproduce:**
Click and drag on a number property in the inspector - your mouse disappears. When you let go, your mouse appears in the top left corner of the Godot window (position 0,0)

Note if you do the same thing on a property which has a slider bar (e.g. the rotation in the below gif) the mouse is not teleported, but still disappears.

https://user-images.githubusercontent.com/41730826/119229766-c3206e80-bb5c-11eb-9013-f3f721004f3d.mp4

**Comment by EricEzaM** [comment]
When the mouse is released, the mouse position is warped to `grabbing_spinner_mouse_pos`, but this value is only updated when the spinner is visible, as shown below:

https://github.com/godotengine/godot/blob/4828667759bca621570862d05e95316235bb05e4/editor/editor_spin_slider.cpp#L271-L285

The value also needs to be updated when the slider **is** hidden.

**Comment by EricEzaM** [comment]
Marking as Junior Job, as I think it might be a reasonably simple fix. If you want to try solve this but have questions hit me up.

**Comment by KoBeWi** [comment]
This might be regression from #48444
I moved the variable update, but maybe it should update in both places...
