### ISSUE TITLE
Type compatibility error in loop

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#48988]
**Godot version:**
45d3b965bb55f3111478306070034ed18e8fa5e4

**OS/device including version:**
Windows 10

**Issue description:**
The error 'Parser bug (please report): Trying to check compatibility of unset value type' is printed when passing an i variable of a loop into the float function.

**Steps to reproduce:**
Launch attached project

**Minimal reproduction project:**
[type_compatibility.zip](https://github.com/godotengine/godot/files/6527774/type_compatibility.zip)

**Comment by nonunknown** [comment]
All these are related to this one: #45139 & #44375

I can confirm it when typing this on my script:

```
func project_ray() -> void:
	var cam:Camera3D = $Gizmo/Camera3D
	var from = cam.project_ray_origin(mouse_pos)
	var to = from + cam.project_ray_normal(mouse_pos) * 1000
	var result = get_world_3d().direct_space_state.intersect_ray(from
	,to, [self])
```

**Comment by Blackiris** [comment]
In the reproduction project, the p_source (= i) is not set, which means its kind variable is still unresolved when using it in the call.
The i variable type should in fact be guessed from the `for i in rang(0,1):` expression but it is currently not.
In GDScriptAnalyzer::resolve_for, there is even a TODO comment about this:
```
	// TODO: If list is a typed array, the variable should be an element.
	// Also applicable for constant range() (so variable is int or float).
```

**Comment by cdemirer** [comment]
Can't reproduce on current master.
