### ISSUE TITLE
Writing bool values to PoolByteArray works in debug but not release exports

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#48999]
**Godot version:**
3.3.1

**OS/device including version:**
Windows 10, 19042.928

**Issue description:**
You can't write to PoolVectorArrays in release exports.
Debug (Editor/Export):
```
======= BOOL =======
Start:		00000
Expected:	00100
Got:		00100
```
Release Export:
```
======= BOOL =======
Start:		00000
Expected:	00100
Got:		00000
```
with code:
```
print("======= BOOL =======")
print("Start:\t\t", pba_str(byte_data))
byte_data[2] = true
print("Expected:\t00100\nGot:\t\t", pba_str(byte_data))
```

**Steps to reproduce:**
1. Open MRP
2. Run in Editor
3. Export
4. Uncheck "Export with Debug"
5. Run exported build

**Minimal reproduction project:**
[PoolVector.zip](https://github.com/godotengine/godot/files/6528476/PoolVector.zip)
The project includes test for all PoolVector types.

**Comment by Calinou** [comment]
In Godot 3.x, Pool*Arrays are passed by value instead of reference. Maybe that explains it?

**Comment by HaSa1002** [comment]
More context than in the snippet above:
```swift
extends Node
var byte_data := PoolByteArray([false, false, false, false, false])

func _ready():
	print("======= BOOL =======")
	print("Start:\t\t", pba_str(byte_data))
	byte_data[2] = true
	print("Expected:\t00100\nGot:\t\t", pba_str(byte_data))
```
I access the Vector by value there.

**Comment by akien-mga** [comment]
That's a weird bug, but it seems to be related to your use of boolean values. It works fine with ints:
```gdscript
var byte_data := PoolByteArray([0, 1, 2, 3, 4])

func _ready():
        print("before")
        for b in byte_data: print(b)
        byte_data[2] = 6
        print("after")
        for b in byte_data: print(b)
```
```
before
0
1
2
3
4
after
0
1
6
3
4
```

**Comment by HaSa1002** [comment]
Okay. Good to know. That seems to be an GDScript bug?
I can workaround my `Input.is_action_pressed` with `int(...)` then.

**Comment by Xrayez** [comment]
> That seems to be an GDScript bug?

Yeah, looks like GDScript issue to me, there were many debug vs. release differences in GDScript implementation in the past.
