### ISSUE TITLE
AAB export fails

### ISSUE THREAD

**Issue by Andrea-Miele** [godotengine/godot#48996]
**Godot version:**
3.3.stable

**OS/device including version:**
Linux 64 bit (GitHub actions )

**Issue description:**
Export with AAB and custom export template fails with error `Thread exit status: 126`

**Steps to reproduce:**
Open the editor
Download android custom build
Activate AAB and custom build
Export the project

**Reproduction project:**
[Crystal Bit Godot Game Template](https://github.com/crystal-bit/godot-game-template) (before exporting for android follow the steps to reproduce)

**Comment by madmiraal** [comment]
I've tested this with both 3.3.stable and 3.3.2.stable, and I'm unable to reproduce the reported error. It builds a perfectly good `.aab` file.

The exit code 126 suggests that you don't have execute permissions on the `gradlew` file in the `android/build` directory. Check the execute permissions or simply delete the `android` folder and reinstall the Android Build Template.

**Comment by m4gr3d** [comment]
Closing due to inability to reproduce the issue and lack of responses. @Andrea-Miele Feel free to re-open if this is still an issue.
