### ISSUE TITLE
Godot fails to execute expression with class name inside

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#49008]
**Godot version:**
3.4.beta.custom_build. 74174676b

**OS**
Ubuntu 21.04 - Ubuntu, Gnome shell 3.38 X11

**Issue description:**
When executing first line, everything works fine, 
```
{}.get(Particles.new())

var expr = Expression.new()
if expr.parse("{}.get(Particles.new())") != OK:
	print(expr.get_error_text())
	assert(false)
expr.execute([],self)
assert(!expr.has_execute_failed())
```
but when running same code inside expression class, then I got this errors:
```
ERROR: execute: Invalid named index 'Particles' for base type Object
   At: core/math/expression.cpp:2204.
```

**Comment by timothyqiu** [comment]
I think there is something wrong with the test code.

As mentioned in the [doc](https://docs.godotengine.org/en/stable/classes/class_expression.html#description), only "arithmetic operation, built-in math function call, method call of a passed instance, or built-in type construction call" are supported by `Expression`.

`Particles` is not a built-in type, so one have to pass it in:

```gdscript
var expr = Expression.new()
var bindings = {'Particles': Particles}
if expr.parse('{}.get(Particles.new())', bindings.keys()) != OK:
    print("Parse Failed: ", expr.get_error_text())
else:
    expr.execute(bindings.values())
    print("Execute Success? ", not expr.has_execute_failed())
```
