### ISSUE TITLE
Expression fails to parse valid GDScript code

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#49007]
**Godot version:**
4.0.dev.custom_build.  92c04fa72

**OS**
Ubuntu 21.04 - Ubuntu, Gnome shell 3.38 X11

**Issue description:**
When executing
```
Vector2(1,1).posmod(1)
assert(expr.parse("Vector2(1,1).posmod(1)") == OK) 
```
Second line fails to execute and shows error
```
Expected identifier after '.'
```

This error is probably shown, because in GDScript in GlobalScope, same function exists.

**Comment by Zylann** [comment]
I'd note that `Expression` actually does not litterally executes GDScript, it has its own implementation and so there might be some things it cannot run

**Comment by timothyqiu** [comment]
I think this is `Expression` misinterpreting `posmod` as the global `posmod` function it supports when parsing.

https://github.com/godotengine/godot/blob/2d3c0d311c3f55fcee64bccbe4476e70134a763e/core/math/expression.cpp#L1135-L1143

So `Vector2(1,1).length()` works while `Vector2(1,1).posmod(1)` doesn't.
