### ISSUE TITLE
Anchor in inspector does not reset when set via Layout menu

### ISSUE THREAD

**Issue by johnfn** [godotengine/godot#49004]
**Godot version:**
3.3.0

**OS/device including version:**
MacOS Catalina

**Issue description:**
When I set layout via the layout menu, then hit cmd-z to undo, the old anchor values still display in the inspector.

**Steps to reproduce:**
1. Make an HBoxContainer
2. Click Layout > Full Rect
3. Press Cmd-Z
4. Notice that the inspector still reads Anchor>Right 1 and Anchor>Bottom 1, even though they aren't 1 any more. 

**Minimal reproduction project:**
This reproduces in an empty project.

**Comment by Calinou** [comment]
This is likely because `change_notify()` or `update()` aren't being called where they should be in `scene/gui/control.cpp` or `editor/canvas_item_editor_plugin.cpp`.

**Comment by amoriqbal** [comment]
This issue does not exist in master. The code of `control.cpp` in `master` is quite different from that of `3.3`. So I have made a pull request to branch `3.3`.

**Comment by akien-mga** [comment]
Fixed by #49167.
