### ISSUE TITLE
Animations for bones with non-uniform-scale rest pose have artifacts

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#49010]
**Godot version:**
4.0.dev 45d3b965bb55f3111478306070034ed18e8fa5e4

**OS/device including version:**
Windows 10.0.19041.985

**Issue description:**
Animations have visual artifacts when rotating non-uniformly scaled bones

Here is the animation within Godot:
![When played in Godot](https://user-images.githubusercontent.com/39946030/119274018-a74fb380-bbc2-11eb-8f2d-7608ee6cb509.png)
The artifacts are the result of a desperate attempt to counteract the non-uniform scale: it requires stretching hundreds of units locally just to move a little bit.

Same animation when played in https://gltf-viewer.donmccurdy.com/
![Played in Don McCurty's glTF viewer](https://user-images.githubusercontent.com/39946030/119274114-3230ae00-bbc3-11eb-8966-e32711c90474.png)

One possible fix is to deconstruct the non-uniform-scale component and perhaps multiply it into the child nodes. However, this could affect the hierarchy of existing glTF files so could be compatibility breaking for 3.x

**Steps to reproduce:**
1. Load the attached project.
2. It should play the animation automatically. if not, enable editable children on the GLB file and play the animation.

**Minimal reproduction project:**
[gltf_non_uniform_bone_animation.zip](https://github.com/godotengine/godot/files/6528787/gltf_non_uniform_bone_animation.zip)

**Comment by fire** [comment]
Deconstruct the non-uniform-scale component and multiply it into the child nodes.

https://github.com/iimachines/Maya2glTF/blob/master/LICENSE

https://github.com/iimachines/Maya2glTF/blob/3d7ba8eaf03ea15afe0720129db88deba7f8749a/src/PolarDecomposition.c#L621-L637

From lox

> \<Lox> Polar decomposition turns a 3x3 real matrix M into `M = R * S` with R being a rotation matrix and S being a scale matrix (not necessary uniform or diagonal, i.e. the scale axes can be different to XYZ). This decomposition is unique.

> Equivalent you can always turn a 3x3 matrix M into `M = R1 * D * R2` with R1,R2 being rotation matrices and D being a diagonal matrix (i.e. S part in TRS). This decomposition isn't unique.

**Comment by TechnoPorg** [comment]
On current `master`, the animation looks the same for me as it does in the online glTF viewer. This was probably fixed by #53765, which improved support for non-uniform scaling,

**Comment by lyuma** [comment]
Thanks for testing and confirming this is fixed!
