### ISSUE TITLE
Place of error is missing

### ISSUE THREAD

**Issue by iRumba** [godotengine/godot#49014]
I deleted file from visual studio and after it i see errors in godot editor

![image](https://user-images.githubusercontent.com/12796309/119306388-45f81500-bc94-11eb-97d9-e5c2c22eefef.png)

but i don't know where this file referenced.

expanding of error say about external structures 
![image](https://user-images.githubusercontent.com/12796309/119306499-72ac2c80-bc94-11eb-874b-5ca68a10b9fb.png)

**Comment by groud** [comment]
Please fill in the issue template instead of removing it.

But in any case, I think that's an expected behavior. You deleted a file thus Godot tells you it cannot find it.
Try removing the C# script from the node using it.
