### ISSUE TITLE
Segmentation fault when exiting from running a ZIP file.

### ISSUE THREAD

**Issue by efornara** [godotengine/godot#49012]
**Godot version:** 3.3.1-stable

**OS/device including version:** Linux debian/buster, 64 bits

**Issue description:** Segmentation fault when exiting a game exported as a ZIP.

**Steps to reproduce:**

Run the official x11 export template (or the editor) with a ZIP pack:

    linux_x11_64_debug --main-pack 32_2d_platformer.zip

Exit the game. You should get a segmentation fault.

I didn't get any useful backtrace from the official build:

```handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x37840) [0x7f0ccdaf9840] (??:0)
[2] Godot_v3.3.1-stable_x11.64() [0xccac27] (??:0)
[3] Godot_v3.3.1-stable_x11.64() [0xccb752] (??:0)
[4] Godot_v3.3.1-stable_x11.64() [0x310d14f] (??:?)
[5] Godot_v3.3.1-stable_x11.64() [0x98e3e1] (??:0)
[6] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f0ccdae609b] (??:0)
[7] Godot_v3.3.1-stable_x11.64() [0x99cb9e] (??:0)
-- END OF BACKTRACE --
Aborted
```
but my build of the official source (x11 platform) points to ZipArchive::~ZipArchive.

**Minimal reproduction project:** I tried 32_2d_platformer.zip from (the standard 2D platformer ported to GLES2)  from here: https://sourceforge.net/projects/frt/files/demos/ but I suspect that any project exported as a ZIP would do.

**Comment by akien-mga** [comment]
Probably related to #42337, cc @zaevi.

**Comment by zaevi** [comment]
https://github.com/godotengine/godot/blob/635d0c9b449e34267b52a237f7ce21838d90b6ce/core/io/file_access_zip.cpp#L227-L235
Yes, after #42337 was fixed, the implementation here seems close file twice, which throws the fault.
