### ISSUE TITLE
Changing the language directly in the project manager

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4901]
Because we can, and since we spawn a new process for the editor anyway, it would be the right time to select another language.

In a more practical context, it would also make it very easy to find if we want to encourage people to make screenshots in English for bug reports, and not in their own locale.

**Comment by neikeq** [comment]
IMO It is related to #2771

**Comment by akien-mga** [comment]
> IMO It is related to #2771

True, though here I was even thinking of having a drop down list of available locales directly in the project manager (i.e. without having to open the full editor settings before if they get exposed in the PM after #2771).

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by sheepandshepherd** [comment]
Is the bottom area next to "Exit" a good spot for these?
<img width="528" alt="godot project manager language button" src="https://user-images.githubusercontent.com/11854330/31976339-981f555e-b8fc-11e7-832e-7aa25c224e63.PNG">

I'll make a PR adding just the language dropdown first.

**Comment by Noshyaar** [comment]
That's a weird location IMO. I think it should be at the top-right corner next to the version text.

**Comment by akien-mga** [comment]
I agree with @Noshyaar. Maybe the Project List and Templates tab can be moved to the left, and the Editor Settings and language drop down list can be on the same line to the right. For the language settings, just having the language code should be enough (without "Editor Language:") and save a lot of space.

**Comment by Noshyaar** [comment]
Maybe we could use icon_environment.svg instead of "Editor Language:".

**Comment by sheepandshepherd** [comment]
Agreed, those suggestions make it look nicer.  
The button is in line with the tabs now. They won't overlap even at minimum window size, but I could still move the tabs left if that's better. Changing language restarts the project manager.
<img width="653" alt="lang button" src="https://user-images.githubusercontent.com/11854330/32026009-f01b29e4-b9a7-11e7-9ec9-33a73e9f342f.PNG">
