### ISSUE TITLE
Printed messages don't get grouped

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#49030]
**Godot version:**

d9d920ed6

**Issue description:**

```
func _process(delta):
	print("test") # same with printerr(), but red
```
![LrnXy8x6Xh](https://user-images.githubusercontent.com/2223172/119368926-e1e54900-bcb3-11eb-95e5-20dd44a6af33.gif)

I also seen a case where messages were correct when using `print_line()` from C++, but then an error was printed and grouping broke.

CC @EricEzaM ;)

**Comment by EricEzaM** [comment]
Duuuuude what is going on with this stuff.

It is 100% to do with the fact that when grouping messages the steps are 1) remove the last line on the RichTextLabel; and 2) add the text back with the count incremented. The first step is where the issue lies... RTLs don't like that step...

**Comment by EricEzaM** [comment]
I blame it on RichTextLabel... from my testing it seems pretty broken and the internals are very convoluted so I have no idea how to fix.

Put this script on a RichTextLabel node in a new scene...

```gdscript
extends RichTextLabel

func _ready():
	$RichTextLabel.text = "test1\ntest2\ntest3\ntest4\ntest5\ntest6"

func _input(event):
	if event is InputEventKey:
		if event.keycode == KEY_SPACE and not event.echo and event.pressed:
			print("---------")
			print("before count: " + str($RichTextLabel.get_line_count()))
			$RichTextLabel.remove_line($RichTextLabel.get_line_count() - 1)
			print("after count: " + str($RichTextLabel.get_line_count()))
```

Press space a bunch of times. **Expectation:** one line is removed at a time until none are left. **Reality:** No lines are removed until you press it 5 times, at which point the last 3 lines are removed at once. However, in the console, note that internally it thinks it has removed lines, but then after the 5th press it goes to reporting the number of lines before and after the `remove_line` is 3...

Perhaps I was doomed from the start if RichTextLabel is not working properly.

**Comment by EricEzaM** [comment]
For now maybe "collapsing" should be removed. It seems to be having a lot of troubles.
