### ISSUE TITLE
Un-instance a scene

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4903]
Sorry for the strange title but I have no better one in mind right now:

Sometimes I create a new scene and instance it in a first scene, but I later realize it is better not to have it as an external scene, but as part of the first scene. But there is currently no way of asking Godot to take a scene instance and make it so it's not an instance anymore.

In other software you would usually copy the root node, then paste it where you want it to be in the main scene, then delete the duplicate instance. But in Godot you cannot do that. You only have Ctrl+D, which only works within the current scene, not across two.

If there is a way to do that please tell me (Godot is full of hidden features :p), otherwise it should be made easier.

**Comment by akien-mga** [comment]
You can do "Import > Nodes from Scene" to import the nodes of this other scene directly, without instancing. (in the git master HEAD it was replaced by "Right click > Merge Nodes from Scene").

But I guess a contextual action on instanced scenes could be added to make this more obvious.

**Comment by thirite** [comment]
I was always wondering how to do this. It would be great if there was an option to convert an existing instanced scene to a "unique" non instanced one.
