### ISSUE TITLE
Singleton Reference Null under Certain (Circular) Circumstances

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#49049]
* OS: Windows 10
* Godot Version: v4.0.dev.calinou.3b3a55ca0

If you have a Singleton which references a named class variable that is typed according to its class_name, and that class tries to reference the Singleton, the direct method (SigletonName) will return null even though accessing it indirectly (`get_node("/root/SingletonName")`) will succeed.

[Bug.zip](https://github.com/godotengine/godot/files/6535667/Bug.zip)

The attached example makes it clear. Scene.gd provides a working reference and a failed reference. Singleton.gd can be made to work if the variable typed as `Scene` is changed to `Node`.

Given how inconsistent this behavior is (one form of reference succeeds while another to the same object fails) and the fact that it only happens in circular situations (this doesn't appear to happen if the named class is some third class), I suspect it's a bug resolving sorta-circular situations.

**Comment by summertimejordi** [comment]
Any progress on fixing this? It makes certain workflows less viable if I have to use get_node to access the singleton.

**Comment by Calinou** [comment]
> Any progress on fixing this? It makes certain workflows less viable if I have to use get_node to access the singleton.

As far as I know, nobody has looked into fixing this yet.

**Comment by vnen** [comment]
This is probably a duplicate of #50471 actually.
