### ISSUE TITLE
Changing enabled classes resets folding in manage editor features

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#49040]
**Godot version:**
3.3.1.stable

**OS/device including version:**
Windows 10

**Issue description:**
Changing enabled classes inside of manage editor features resets folding, making it hard to use

**Steps to reproduce:**
Fold something inside of the enabled classes in manage editor features, then check/uncheck something, it'll unfold the thing you folded

https://user-images.githubusercontent.com/12120644/119308363-f20d1200-bc3a-11eb-98b9-927c85d8fb5c.mp4

**Comment by pycbouh** [comment]
Makes sense, it’s likely fully redrawn on every change, specifically because sub-items of unchecked items are removed. We would need to keep the track of the folded state between redraws.

**Comment by EricEzaM** [comment]
I think this could be a good one for the "junior job" tag.

Check out `EditorFeatureProfileManager::_update_selected_profile()`
Also perhaps check out the editor Shortcuts dialog which has similar/same logic , see first few lines of `EditorSettingsDialog::_update_shortcuts()`

**Comment by aemreaydin** [comment]
I would like to work on this.
This will be my first issue but looking at the code I think I wouldn't have any troubles fixing it.

**Comment by kodiwills** [comment]
@aemreaydin I took a look at this problem today as well. If you wanna collaborate for a fix I would be down. I have a pretty decent idea on how to do it. It will also be my first contribution.
