### ISSUE TITLE
Editor can't show Korean language well

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4904]
**Operating system or device - Godot version:**
Windows 10, current head

**Issue description** (what happened, and what was expected):
Can't show Korean language well like "한글이 제대로 나오지 않아요"

**Steps to reproduce:**
Paste "한글이 제대로 나오지 않아요" in inspector or script editor.

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment]
Because of this, I can't see labels with korean translation (I'm doing)

![image](https://cloud.githubusercontent.com/assets/8281454/15649795/1e987674-26af-11e6-90cf-e6eb340b7e0c.png)

**Comment by reduz** [comment]
Hmm seems the font did not have a korean version, but there must be one
somewhere around

**Comment by reduz** [comment]
there is supposedly a DroidSansFallback that supports Korean somewhere
around, I think Android 4.1.2 is supposed to have it, so help is
appreciated looking for it

**Comment by volzhs** [comment]
How can I properly set ``DroidSansFallback.ttf`` with editor?
I tried to set it on Settings > Global > Font field.
When I restart editor, console says infinitely,
```
ERROR: EditorFileSystemDirectory::get_source_file: Index p_source out of size (files[p_idx]->meta.sources.size()).
   At: tools\editor\editor_file_system.cpp:169
ERROR: EditorFileSystemDirectory::is_source_file_missing: Index p_source out of size (files[p_idx]->meta.sources.size()).
   At: tools\editor\editor_file_system.cpp:179
```

**Comment by volzhs** [comment]
I checked what Korean(Hangul) characters in ``tools/editor_fonts/droid_sans.ttf``.

![image](https://cloud.githubusercontent.com/assets/8281454/15651372/131a5136-26ba-11e6-8300-becd6256e03a.png)

droid_sans.ttf has few of korean letters.
I can see those letters in editor.

**Comment by volzhs** [comment]
TTF must contains over 10,000 characters for Korean(Hangul) to show Korean properly.
So, I guess this ``droid_sans.ttf`` 6MB file is too small to cover it.

**Comment by volzhs** [comment]
I made a game about a year ago, which supports 11 languages - English, German, Russian, Spanish, Japanese, Chinese, Portuguese, Polish, French, Hindi and Korean.
What I found was I could not cover all languages with only one font even if using Google Noto CJK font.
I needed to use 3 fonts to cover these 11 languages.
One for Hindi, one for Chinese, Japanese and Korean, and last one for all other Latin languages.

**Comment by reduz** [comment]
please try again, added Korean

Also for situations like yours where you need more than 64k characters, I
just added optional fallbacks to DynamicFont

**Comment by volzhs** [comment]
@reduz It works fine except script editor.
Can script editor have fallbacks too?

**Comment by reduz** [comment]
Ah I don't see why not.. not sure how compatible are the font sizes.

You could try editing editor_fonts.cpp and adding the same fallbacks to
souce code pro, let me know if it works.. if so feel free to submit a PR.
I'm not sure if the sizes are compatible though
