### ISSUE TITLE
Fbx dont work in new version

### ISSUE THREAD

**Issue by taha5564** [godotengine/godot#49054]
Parts or organs of the body are scattered everywhere and animation player do not work and strange movements appear
But when i use old version of godot it work well

**Godot version:**
3.3.2
Windows

**Comment by Chaosus** [comment]
Please fill a topic according to a template and attach the test project, otherwise, it's hard to help you by devs.

**Comment by Chaosus** [comment]
Sorry, but since you've didn't fixed the issue template and don't provide the required information - I close this issue.
