### ISSUE TITLE
Use a web-based tool to internationalize Godot engine UI

### ISSUE THREAD

**Issue by genete** [godotengine/godot#4906]
*Bugsquad edit:* Hijacked the OP as we won't use Transifex but the libre Weblate.

----------

[Transifex](https://www.transifex.com/) is a great tool for collaborative translation of applications (as well as websites, etc.).

It is possible to create a free account and with it create one organization to handle different projects on it. If the organization create and translate only open source projects the monthly cost is 0$.

See one example of open source organization that is using transifex [here](https://www.transifex.com/morevnaproject/public/)

And no, this is not spam :-)

**Comment by akien-mga** [comment]
Transifex is a great service, but it's proprietary, so it wouldn't be my first choice (even though I use it for various projects, such as the full Mageia project - the choice to use it was made while Transifex was still open source...).

Weblate is a better alternative for open source communities. I already made a request on https://hosted.weblate.org/ to get a free hosted project for Godot.

**Comment by allysonsouza** [comment]
Maybe we can use a WordPress install with GlotPress plugin: https://br.wordpress.org/plugins/glotpress/

**Comment by trollworkout** [comment]
i think Transifex is free for opensource free software

**Comment by Calinou** [comment]
> I also found this one which is opensource
> https://translations.launchpad.net/

I find its UI way worse than Weblate, even if it supports more file formats (which we don't need anyway).

**Comment by trollworkout** [comment]
@Calinou  weblate does  seem better actually

**Comment by akien-mga** [comment]
To all translators: we now have a translation project on [hosted.weblate.org](https://hosted.weblate.org/projects/godot-engine/godot/), a libre translation frontend with tons of nice features for translation and team work.

We'll have to see how to best use it in our workflow, but I would already encourage you to work in Weblate directly and not by pull requests in this repo, as we don't want the state of translations on git and on Weblate to diverge.

Changes made on git can however be easily synced to Weblate, so it wouldn't be a drama either, but more work. I won't enable automatic commits from Weblate to GitHub for now, as I don't want it to clutter our git history. So in a first time I'll probably be the one to commit translations from Weblate to GitHub. We'll adjust the workflow as time goes :)

Link if you missed it: https://hosted.weblate.org/projects/godot-engine/godot

Mass ping of all current translators: @Calinou @est31 @volzhs @vnen @Geequlim @ZX-WT  @derderder77 @noidexe @hyperglow @paviro @ajacobsen @JohnnyLeone @Bonfi96 @DimOkGamer @toby3d :)

**Comment by djrm** [comment]
closable

**Comment by vnen** [comment]
True, now we have it :tada: https://hosted.weblate.org/projects/godot-engine/godot
