### ISSUE TITLE
Unable to center TextureRect in scene

### ISSUE THREAD

**Issue by Klaider** [godotengine/godot#49065]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**

Unable to center TextureRect to its pivot point after scaling down the TextureRect.

**Steps to reproduce:**

- 1. Create a Node2D scene.
- 2. Add a CanvasLayer node to the scene.
- 3. Add a TextureRect to the CanvasLayer.
- 4. Use the tool _Layout > Center_. (Works!)
- 5. Scale the TextureRect and use the tool _Layout > Center_ again. It'll wrongly put the TextureRect at the left-top position of the scene.

**Minimal reproduction project:**

Not needed.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/19068 (same cause).
