### ISSUE TITLE
`breakpoint` can't be added as a `Dictionary` key in Lua-syntax, or accessed using dot-syntax

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#49066]
**Godot version:**
3.3 / 3.3.2

**OS/device including version:**
Windows 10

**Issue description:**
`breakpoint` can't be added as a `Dictionary` key in Lua-syntax, or accessed using dot-syntax

**Steps to reproduce:**
```
const KEYWORD := {
	yield = "yield", # OK,
#	breakpoint = "breakpoint", # Error parsing expression, misplaced: breakpoint
	"breakpoint": "breakpoint", # Error when using KEYWORD.breakpoint
}

func test() -> void:
	print(KEYWORD.yield)
#	print(KEYWORD.breakpoint) # Expected identifier as member
```

**Minimal reproduction project:**
N/A

**Note:**
This is a silly issue. Feel free to close this if it takes more than 5 seconds to fix.
(Nobody would probably ever do this except me. Using in workaround for [#2762](https://github.com/godotengine/godot-proposals/issues/2762))

**Comment by Calinou** [comment]
`ÿield` is a built-in function that expects one parameter, but `breakpoint` doesn't expect any parameters. Due to this, I'm not sure if this can be fixed.
