### ISSUE TITLE
AnimatedTexture has unexpected timing when changing frame

### ISSUE THREAD

**Issue by ANamelessGhoul** [godotengine/godot#49078]
**Godot version:**
3.3.2

**OS/device including version:**
Windows 64-bit

**Issue description:**
When setting current_frame in the AnimatedTexture from code during run time, it is expected that the newly set frame is shown for the standard duration set by FPS. However, the new frame only stays for 1 / fps minus the duration the previous frame was shown because the internal timer does not reset when calling set_current_frame.

Checking the source code you can see that setting the current frame does not affect the timer. The frame still changes as if it was never set.

**Steps to reproduce:**
- Create an AnimatedTexture in a TexturedRect.
- Write a small script to set current frame to 0 on a key press.
- Repeatedly set frame to 0 at random intervals and observe frame times.

**Minimal reproduction project:**
[AnimatedTextureBug.zip](https://github.com/godotengine/godot/files/6542164/AnimatedTextureBug.zip)

**Comment by akien-mga** [comment]
Confirmed that this behavior is still reproducible in 4.0 RC 1 with the above MRP (just needs resetting the "Expand Mode" of the TextureRect in 4.0 to see anything).

The proposed change sounds sensible a priori.

**Comment by akien-mga** [comment]
Thanks!
