### ISSUE TITLE
Misaligned FileDialog Items

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#4907]
**Issue description**:
Items in a FileDialog can be misaligned, maybe a regression from ab97718d (ping @bojidar-bg )
Also, the item selection is a bit messed up (see gif)

**How to reproduce**:
I'm not exactly sure, but it might be triggered by differently sized images:
![filediag](https://cloud.githubusercontent.com/assets/8281916/15649489/3c1ef840-2672-11e6-80e2-4054e333e40a.gif)

**Godot version:**
Git Master

**Comment by bojidar-bg** [comment]
I think the click-outside bug has been there for a long time, but the misalignment is new one probably... I won't be able to fix it right now since I have other work to do, sorry @Hinsbart
