### ISSUE TITLE
Cannot Undo within bottom panel when script view is active

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#49084]
**Godot version:** 3.3.2
This is not a new bug, I've definitely noticed this before.

**OS/device including version:** Win 64

**Issue description:**
Pressing Ctrl+Z to undo something in one of the bottom panels works when 2D and 3D viewports are active, but does not work when the script view is active. Even though the focus clearly is in the bottom panel when pressing Ctrl+Z, the Ctrl+Z event is captured by the script panel and suddenly the last action on the script panel is undone.

This is very unexpected behaviour and can easily go by unnoticed until you want to run your game and something is broken.

For the longest time I just thought the bottom panel had no "undo". I have tested this with the TextureRegion, Animation, Audio, SpriteFrames bottom panel. It's the same behaviour with all of them: Undo works in 3D, 2D but not with script view.

**Steps to reproduce:**

1. Make sure 2D or 3D view is active,
2. Add AnimationPlayer + New Animation + Track + Key, move the key around and press Ctrl+Z (works)
3. Switch to script view and type something,
4. then back to the Animation Panel and move the key around again. Hit Ctrl+Z and witness your script reverting even though the focus was on the Animation Panel.

**Comment by KoBeWi** [comment]
This is already fixed in 4.0, but can't be backported.
