### ISSUE TITLE
New Tree relationship lines disappear when the selected node is significantly out of view

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#49080]
**Godot version:** `master` Git https://github.com/godotengine/godot/commit/b6f381475fed44be21b8dd66cdb86e1a3b3af9cf

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 465.27)

**Issue description:**

The [new Tree relationship lines](https://github.com/godotengine/godot/pull/48546) disappear when the selected node is significantly out of view.

cc @pycbouh 

## Before scrolling up

![image](https://user-images.githubusercontent.com/180032/119564742-6d8cd180-bda9-11eb-9b09-10a17d35713f.png)

## After scrolling up

![image](https://user-images.githubusercontent.com/180032/119564775-7382b280-bda9-11eb-870c-6995955f4719.png)

**Steps to reproduce:**

- Create a scene with dozens of nodes.
- Select a node at the bottom.
- Scroll up.

**Minimal reproduction project:** N/A

**Comment by pycbouh** [comment]
Well that's unfortunate. This is because the whole line is drawn from the selected item. Though maybe not a big deal, as I already do the necessary checks to draw each segment, I think.
