### ISSUE TITLE
Members assignment for Vector2 / Vector3 behaves wrong

### ISSUE THREAD

**Issue by Shatur95** [godotengine/godot#49081]
**Godot version:**
b6f381475fed44be21b8dd66cdb86e1a3b3af9cf

**OS/device including version:**
Linux, GCC

**Issue description:**

Assignments for Vector2 / Vector3 members (for example, `x` / `[0]`, etc.) with a positive number will result in `0`, with a negative number will result in `nan`.

**Steps to reproduce:**

Try the following code:

```gdscript
var vector3 := Vector3.ONE
vector3.x = 10 # Will set to zero
print(vector3)
vector3[0] = 10 # Will set to zero
print(vector3)
vector3.x += 10 # Works
print(vector3)

# Same for Vector2
var vector2 := Vector2.ONE
vector2.x = -10 # Will set to nan
print(vector2)
vector2[0] = 10 # Will set to zero back
print(vector2)
vector2.x += 10 # Works
print(vector2)`
```

It will print the following:

```
(0, 1, 1)
(0, 1, 1)
(10, 1, 1)
(nan, 1)
(0, 1)
(10, 1)
```

**Minimal reproduction project:**

[Vector.zip](https://github.com/godotengine/godot/files/6542251/Vector.zip)

**Comment by Shatur95** [comment]
I dug a little deeper, the behavior is even stranger than I originally thought. Updated the issue message.

**Comment by kleonc** [comment]
I'm blindly guessing it might be behaving wrong just for ints / literal ints, probably worth checking it out to potentially narrow down the issue.

**Comment by briansemrau** [comment]
This is a duplicate of #45172

**Comment by Shatur95** [comment]
@briansemrau, you are right, sorry, missed it.
