### ISSUE TITLE
Using connection dialog with build-in script opens save file dialog

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#49086]
**Godot version:**

4.0 7ea3a45 / 3.x 94b5a82

**Issue description:**

![LSLQqqZPW1](https://user-images.githubusercontent.com/2223172/119577672-6078de00-bdbb-11eb-835d-619b7d084984.gif)

**Steps to reproduce:**
1. Create a build-in script
2. Try connecting any signal to it

**Comment by kleonc** [comment]
Caused by #42416.
https://github.com/godotengine/godot/blob/5ec8920cde0cf5aafda59dfda335772acf3fcd15/editor/plugins/script_editor_plugin.cpp#L2453-L2454
https://github.com/godotengine/godot/blob/5ec8920cde0cf5aafda59dfda335772acf3fcd15/editor/plugins/script_editor_plugin.cpp#L2327
