### ISSUE TITLE
Error `Index current_edited_scene = -1 is out of bounds` spammed into a console at editor startup

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49096]
**Godot version:**
5d83b67b573546104aa2710344c392afaa225254

**OS/device including version:**
Windows 10

**Issue description:**
Every time I start a new project or open an existing one the following errors are spammed into the console:

![image](https://user-images.githubusercontent.com/3036176/119623405-ce032980-be10-11eb-914c-1d410927c93b.png)

**Steps to reproduce:**
Just create a new project or open an existing one and you will see it.

**Minimal reproduction project:**
Too easy to reproduce

**Comment by akien-mga** [comment]
I see this too on Linux, I think it was introduced recently (past 2-3 weeks I'd say).
