### ISSUE TITLE
can setget like 3.x?

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#49093]
**Godot version:**

4.0

**OS/device including version:**

**Issue description:**

### Describe the project you are working on

I want implement a Date class like this:
```
class_name Date

var year = 0 :
    set(value):
        year = value
        update_dulian_day()

var month = 0 :
    set(value):
        month = value
        update_dulian_day()
var day = 0 :
    set(value):
        day = value
        update_dulian_day()

var julian_day = 0:
    set(value):
        dulian_day = value
        update_date()

func update_dulian_day():
    julian_day = calc_julian_day()

func udpate_date():
    year = calc_year(julian_day)
    month = calc_month(julian_day)
    day = calc_day(julian_day)
```
If setget behavior like 3.x, All work well. But in 4.0, 
in update_date() will called update_julian_day() 
and
in update_julian_day() will called update_date(),
deadlock!
How to do?
Or can I use self keyword say I want set value directly?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by pycbouh** [comment]
See https://github.com/godotengine/godot-proposals/issues/2777#issuecomment-848522343
