### ISSUE TITLE
Editor drop down menu not in proper place

### ISSUE THREAD

**Issue by Vignesh1-art** [godotengine/godot#49091]
517f1d7

Windows 10

When I click on Scene, Project ,etc their drop down menu don't appear below them .

![Screenshot (44)](https://user-images.githubusercontent.com/52810607/119600568-ee2ceb80-be04-11eb-8731-05d591e7e132.png)

Create a dummy project and then click on Scene ,Project  etc options that are in top.

**Comment by EricEzaM** [comment]
Cannot reproduce, also on Windows 10 7ea3a45.

Have you pulled the latest commits?

**Comment by Chaosus** [comment]
> master branch

Please, specify a hash of the commit, instead.

**Comment by foxydevloper** [comment]
Seems related to https://github.com/godotengine/godot/issues/45740

**Comment by Vignesh1-art** [comment]
> > master branch
> 
> Please, specify a hash of the commit, instead.

👍

**Comment by Vignesh1-art** [comment]
> Cannot reproduce, also on Windows 10 [7ea3a45](https://github.com/godotengine/godot/commit/7ea3a45da1f8b2cf8460a08a5bb00a5a0265a997).
> 
> Have you pulled the latest commits?

Yup. Now I  have mentioned hash check that out.
