### ISSUE TITLE
Mono project immediatly crashes at startup

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#49100]
**Godot version:**
Godot Engine v3.3.2.stable.mono.official

**OS/device including version:**
Windows 10 20H2
Multi-threaded rendering
GLES3

**Issue description:**

When I'm trying to run my game, it will open the window, pause briefly, then close without any debug information, or console output. This happens about 50% of the time, but not always.
When put into --verbose mode, it will simply output "Socket error: 10054" with no other information about the problem before closing the player.

If I can provide any logs, or do anything else to give more information on this mysterious bug, please do tell me and I'll provide it.

**Steps to reproduce:**
I have no idea. It only happens in my large game project, and I cannot reproduce it every time. It's about 50% of the time this happens.

**Minimal reproduction project:**
Cannot reproduce in a minimal reproduction project.

**Comment by Zireael07** [comment]
Socket error 10054 means connection was reset, in other words your project crashed before connection could be established.
Likely causes are misspellings in your code or references to null objects (although the latter *should* show error info in editor debugger)

**Comment by Nosrick** [comment]
I thought this too, but I'm using an external code editor (Rider) and C#, so any misspellings would be picked up.
I'm guessing there's some null object somewhere, and it's just not being reported on, but that's an issue in itself that should be addressed.

**Comment by Nosrick** [comment]
Forgot to specify that this only happens about 50% of the time, so edited that into my opening post.

**Comment by Chaosus** [comment]
> I have no idea. It only happens in my large game project, and I cannot reproduce it every time. It's about 50% of the time this happens.
> 
> Cannot reproduce in a minimal reproduction project.

Even so, try to bisect it, and provide a project, otherwise, devs are unlikely may help you and this issue should be closed.

**Comment by Zireael07** [comment]
As I said, if you're running from editor, you should be getting errors in editor debugger, especially if there's a crash. That said, I have had instances of a crash w/o info in editor debugger and a physics freeze that similarly resulted in no debugger info.

If you're running from Rider, maybe you could attach their C# debugger to figure out what's going on?

**Comment by Nosrick** [comment]
> If you're running from Rider, maybe you could attach their C# debugger to figure out what's going on?

I managed to get it to crash while the debugger was attached. And I got this:
`System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at Mono.Debugger.Soft.TcpConnection.TransportReceive(Byte[] buf, Int32 buf_offset, Int32 len)
   at Mono.Debugger.Soft.Connection.Receive(Byte[] buf, Int32 buf_offset, Int32 len)
   at Mono.Debugger.Soft.Connection.ReadPacket()
   at Mono.Debugger.Soft.Connection.ReceivePacket()
   at Mono.Debugger.Soft.Connection.receiver_thread_main()`
`terminated with exit code -1073741819`
Hopefully that's of some use to someone.

**Comment by Nosrick** [comment]
After doing some digging on this error code, I came across issue #24702, and it looks like it could be an NVIDIA driver problem. There's not much I can do about that, unfortunately.

**Comment by Chaosus** [comment]
Well, at least it's something. Note: if you use Mono/C# always use the debugger via VSCode or Rider otherwise - silent crashes will be so frequent, so this is nearly impossible to be used. Now we need to understand - there is a bug inside that function or you just incorrectly using it (call it in the incorrect place and time for example).

**Comment by Nosrick** [comment]
> Now we need to understand - there is a bug inside that function or you just incorrectly using it (call it in the incorrect place and time for example).

I'm not calling that function at all. I don't do _any_ networking stuff.

**Comment by Chaosus** [comment]
Ah right, it's MonoDebugger after all, then yeah it's something that broke the connection. Did it happen in an empty Mono project (with a single C# file) for example? If not - Try to disable the function calls gradually (via commenting) from start and check if this happens or not.

**Comment by Nosrick** [comment]
> Ah right, it's MonoDebugger after all, then yeah it's something that broke the connection. Did it happen in an empty Mono project (with a single C# file) for example? If not - Try to disable the function calls gradually (via commenting) from start and check if this happens or not.

Yes, it does! It tends to happen 2-3 times in quick succession (< 5 seconds between a run, crash, and run again cycle), then will be fine for a while. I've tried disabling my anti-virus (Panda) but that hasn't helped.

**Comment by Chaosus** [comment]
Which version of Mono did you install? I suppose there is an issue with this problem on the tracker but this needs to be found.

**Comment by Nosrick** [comment]
> Which version of Mono Runtime did you install? I suppose this issue is already exist on the tracker but this needs to be found.

...I apparently don't have a Mono Runtime, which is a bit concerning. I must have one bundled with something, somewhere, because I can run Mono projects without a problem through both Godot and Rider.

I'll go explicitly install one and see if that helps.

**Comment by Chaosus** [comment]
If you don't have installed Mono, I think (I'm not sure by 100%), you need to install it from https://www.mono-project.com/download/stable/ cuz Godot uses it. I really don't remember much about this problem, maybe @neikeq can help you if this not helps.

**Comment by Nosrick** [comment]
Right, I installed the Mono Runtime, but it hasn't altered the situation at all. It's still happening with the same frequency.

**Comment by Chaosus** [comment]
Did you reboot after it?

**Comment by Nosrick** [comment]
I did, yeah. Set up Rider with the new Mono runtime, as well.

**Comment by Chaosus** [comment]
cc @neikeq

**Comment by Nosrick** [comment]
I really appreciate the help, so far!

**Comment by Zireael07** [comment]
> An existing connection was forcibly closed by the remote host at ...

It's exactly the same as the originally reported issue, just a socket being closed unexpectedly (Because the app being debugged crashed silently)

Not a c# expert by any definition of the word, so I think you'll likely need to wait for neikeq for any insight on how to figure out what is making your app crash completely silently (silently other than the socket error). A driver error or a hdd/memory corruption are my guesses.

**Comment by Nosrick** [comment]
> a hdd/memory corruption

Please not this. Anything but this. I don't want to have to put my PC into the shop. 😓

**Comment by neikeq** [comment]
I don't think the socket error is related. That's probably just because the connection was lost when the game crashed.
Can you show us the Mono log? The path to the Mono log file is printed to the terminal at startup (make sure it's the game one, not the editor's).

**Comment by Nosrick** [comment]
Hey, sorry for the slow reply, it actually behaved for a while!

Hopefully, this is the right log.

[2021-05-27_07.57.13_8588.log](https://github.com/godotengine/godot/files/6551797/2021-05-27_07.57.13_8588.log)

**Comment by Nosrick** [comment]
Looks like this is an incompatibility with a library I'm using.
Specifically, CodingSeb's ExpressionEvaluator.
Closing this issue!
