### ISSUE TITLE
Large part of `Variant` documentation is missing from in-editor docs

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49101]
**Godot version:**
517f1d7e677c3f3f28c6b9908a6b9f3f2982c13f

**OS/device including version:**
Windows 10

**Issue description:**
![image](https://user-images.githubusercontent.com/3036176/119641035-e6c80b00-be21-11eb-8f18-a101f5070ab7.png)

So its missing properties, methods, etc. ^

**Steps to reproduce:**
Run docs and search for `Variant`.

**Minimal reproduction project:**
No need.

**Comment by Chaosus** [comment]
Ah, or maybe I'm wrong, it is intended and that class is not having a direct presence in Godot for the user.

**Comment by akien-mga** [comment]
Yeah Variant doesn't have own properties and methods in 3.x either, it's expected.
