### ISSUE TITLE
Add instructions about editor font generation

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4911]
The editor fonts that we are using in https://github.com/godotengine/godot/tree/master/tools/editor_fonts were custom-made using fontforge  to merge various glyphs for all supported languages.

We should document (likely in a ``tools/editor_fonts/README.md``) how those fonts were designed (source fonts, steps to merge them together in fontforge with the proper glyphs) + their respective licences.

**Comment by akien-mga** [comment]
Ping @reduz, would be nice to do this while it's still fresh in your mind :)

**Comment by vnen** [comment]
I thought these custom fonts were dropped when the multiple fallback was implemented.

**Comment by akien-mga** [comment]
As @vnen mentioned, and as @reduz confirmed in https://github.com/godotengine/godot/issues/5647#issuecomment-234084190, this issue is not longer relevant as we don't edit the TTF files (so far).
