### ISSUE TITLE
SkeletonIKs description isn't available in "create node"

### ISSUE THREAD

**Issue by gazi-safin** [godotengine/godot#49129]
**Godot version: 3.3.stable**

**OS/device including version: Windows 10 latest, 64bit **

**Issue description: When adding SkeletonIK, the short description isn't available below.**

**Steps to reproduce: Click to add node2d. Find skeletonIK. Select it but don't add it. The quick description isn't below.**

**Minimal reproduction project: Not based on project**

**Comment by Calinou** [comment]
This is because the SkeletonIK class doesn't have any documentation.
