### ISSUE TITLE
`Dim editor on dialog popup` editor option does not work

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49126]
**Godot version:**
364ea7f280a3f074795e542b16b1d0ec76cf6ce2

**OS/device including version:**
Windows 10

**Issue description:**
Seems like that editor option does not work:
![image](https://user-images.githubusercontent.com/3036176/119773590-88eefe00-bec9-11eb-8b90-80994f2dc8ac.png)

The background should be dimmed like in 3.x version if that option is enabled:
![image](https://user-images.githubusercontent.com/3036176/119774491-e9cb0600-beca-11eb-89f5-80b49cd1e68c.png)

**Steps to reproduce:**
^^

**Minimal reproduction project:**
No need

**Comment by Calinou** [comment]
The option doesn't really make sense anymore with the multi-window paradigm, so it should be removed.

**Comment by name-here** [comment]
I can see some people still wanting this, even with the new multi-window support.  I think dimming the background window when you can't interact with it because of a popup is a good design feature (avoids "why won't clicking do anything?!").  Also, we kind of still need the option for single-window mode if we want to keep that functionality.

**Comment by Calinou** [comment]
> I can see some people still wanting this, even with the new multi-window support. I think dimming the background window when you can't interact with it because of a popup is a good design feature (avoids "why won't clicking do anything?!"). Also, we kind of still need the option for single-window mode if we want to keep that functionality.

Another issue with dimming is that it messes up with ColorPicker's "pick color from window" feature, because the color returned will be incorrect if you pick over a dimmed area.
