### ISSUE TITLE
Copying node to another scene creates copies of resources belonging to instanced scenes

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#49133]
**Godot version:**

3.4.beta e9909b763a

**OS/device including version:**

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-17-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 570 Series

**Issue description:**

Get a copy of `MeshInstance` node which is an instanced scene from another scene makes file size huge via `Merge from scene` or `Copy & Paste` feature.
It generates `mesh` sub-resource and copy its `ArrayMesh` data.
But drag it to a scene directly, it has just external resource reference which expected.

when intanced directly from FileSystem panel, `.tscn` file looks like below.
```
[gd_scene load_steps=2 format=2]

[ext_resource path="res://monkey.tscn" type="PackedScene" id=1]

[node name="main" type="Spatial"]

[node name="monkey" parent="." instance=ExtResource( 1 )]

[node name="monkey2" parent="." instance=ExtResource( 1 )]
```

but getting a copy of it from another scene via `Merge from scene` or `Copy & Paste`
```
[gd_scene load_steps=4 format=2]

[ext_resource path="res://monkey.tscn" type="PackedScene" id=1]

[sub_resource type="SpatialMaterial" id=1]
vertex_color_use_as_albedo = true

[sub_resource type="ArrayMesh" id=2]
surfaces/0 = {
"aabb": AABB( -1.36719, -0.984375, -0.851562, 2.73438, 1.96875, 1.70312 ),
"array_data": PoolByteArray( 0, 0, 224, 62, 0, 0, .... HUGE NUMBERS ... ),
"blend_shape_data": [  ],
"format": 97559,
"index_count": 2904,
"material": SubResource( 1 ),
"primitive": 4,
"skeleton_aabb": [  ],
"vertex_count": 1966
}

[node name="main" type="Spatial"]

[node name="monkey" parent="." instance=ExtResource( 1 )]

[node name="monkey2" parent="." instance=ExtResource( 1 )]
mesh = SubResource( 2 )
```

removing `[sub_resource type="ArrayMesh" id=2]` part and `mesh = SubResource( 2 )`,
it just fine.

to workaround this, I need to find every scene file in FileSystem panel and instance it directly to the current scene.

**Steps to reproduce:**
from attached project...
1. open `main.tscn` and `second.tscn`
2. copy `monkey` node from `second` scene
3. paste it to `main` scene
4. save it
5. open `main.tscn` in text editor

**Minimal reproduction project:**

[copy_mesh_instance.zip](https://github.com/godotengine/godot/files/6552323/copy_mesh_instance.zip)

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
When pasting to another scene, all built-in resources get duplicated. Seems like it includes resources of instanced scenes, which become unique in the process. Might be not easy to resolve, because it's possible to e.g. assign a new material to an instanced scene, in which case it should be copied over.

**Comment by volzhs** [comment]
I hope it will be solved someday.
I need to reorganize and recreate everything related to `MeshInstance` scene to avoid huge `.tscn`. :cry:
