### ISSUE TITLE
glTF fails to import `!s.has("nodes")`

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#49138]
**Godot version:**
3.3.1, 3.3.2

**OS/device including version:**
Windows 10, 19042.928

**Issue description:**
The file fails to import. It can be previewed by the built-in windows tool.
```
 editor/import/editor_scene_importer_gltf.cpp:303 - Condition "!s.has("nodes")" is true. Returned: ERR_UNAVAILABLE
 core/os/file_access.cpp:671 - Condition "!f" is true. Continuing.
 Cannot open file 'res://.import/statue_lina4_lod1.glb-53e1acb02a1a0a28fb0ad8b79f8c2e1f.scn'.
```

**Steps to reproduce:**
1. Reimport `statue_lina4_lod1.glb` (.import folder is excluded)

**Minimal reproduction project:**
[gltf Import Bug.zip](https://github.com/godotengine/godot/files/6553174/gltf.Import.Bug.zip)

**Comment by fire** [comment]
I can verify that that exact glb fails.

However when I extract and export again in Blender 2.92.0, I can load it.

Will dig into it.

[statue_lina4_lod1.zip](https://github.com/godotengine/godot/files/6556485/statue_lina4_lod1.zip)

**Comment by fire** [comment]
Opening your original glb in https://gltf-viewer.donmccurdy.com/ gives an empty scene. This empty scene is the same parsing as Godot Engine.

**Comment by HaSa1002** [comment]
Ok the error message is just bad then. I am kind of surprised that the windows tool (3D Viewer) could load the file. However this seems to be an export bug, so this issue is a non-issue then.
Thanks for the investigation. You have to decide whether or not to close the issue

**Comment by fire** [comment]
Thanks for the report.
