### ISSUE TITLE
In ScrollContainner, Item's size.y become bigger

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#49134]
**Godot version:**

4.0; 3.2.2

**OS/device including version:**

Win10

**Issue description:**

Create a ScrollContainer, add a VBoxContainer as a child.
Create a ControlScene, set min_size.y=20
Add some ControlScene.instance() to the ScrollContainer's VBoxContainer.
```
func _on_Button_pressed():
	var item = Item.instance()
	$ScrollContainer/VBoxContainer.add_child(item)
	prints(item.rect_size) 
```
Print the instance's size.y, will bigger, bigger, bigger.
outputs:
```
(382, 20)
(382, 20)
(382, 44)
(382, 68)
(382, 92)
(382, 116)
(382, 140)
(382, 164)
```
![捕获](https://user-images.githubusercontent.com/35988767/119794014-b3f94200-bf09-11eb-85e6-2be79af1cee7.PNG)

**Steps to reproduce:**

**Minimal reproduction project:**

[ScrollTest.zip](https://github.com/godotengine/godot/files/6552398/ScrollTest.zip)

Note: In my Complex Project, the ui become bigger too, but in the reproduction project, the value become bigger but ui not.

**Comment by Calinou** [comment]
Can you reproduce this in Godot 3.3?

**Comment by CsloudX** [comment]
@Calinou
I just tested it in 3.3.2, have the same issue.

**Comment by CsloudX** [comment]
Add I found I can change the item bigger after add_child(), but I can't change it smaller.

**Comment by floppyhammer** [comment]
I sort of understand the logic behind this behavior. As you set the layout mode of the Control scene as Full Rect, when you make it the VBoxContainer's child, it will try to fit into the expanded container as Full Rect mode requires. As a result, printing its `rect_size ` immediately after adding it gives you the expanded value (it's actually equal to the `rect_size` of the container). If you set another layout mode for the Control scene, you will find the printed size depends on the said mode (e.g. the Control size won't change in Center mode). You can get the correct size as long as you delay a bit to get it.

**Comment by CsloudX** [comment]
@floppyhammer Yes, I tested this by code:
```
func _on_Button_pressed():
	var item = Item.instance()
	$ScrollContainer/VBoxContainer.add_child(item)
        await get_tree().process_frame
	prints(item.rect_size) 
```
It works right. Thanks
