### ISSUE TITLE
Multiple skeleton animations at once

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#4913]
It would be very nice I think to be able to reprouce multiple weighted animations at once for one skeleton. This way you could blend more than two animations and the blending could be perfromed depending on other parameters than time.

For instance let say I've got animations A, B and C I should be able to play animation 0.3*A + 0.4*B + 0.3*C. This would be useful for instance when playing walking animations where you must blend between multiple walking stiles (slow, medium, fast) depending on the velocity you are moving.

It would also be nice to have animations to only affect some bones, so that different animations can affect different bones when combined ("Walking" and "Shooting" for instance)

**Comment by bojidar-bg** [comment]
Doesn't AnimationTreePlayer do exactly this?

**Comment by m4nu3lf** [comment]
I've got no idea, I'll try to achieve this with the AnimationTreePlayer and I will let you know. Thanks

**Comment by m4nu3lf** [comment]
Ok, it does! Sorry about that, I didn't know. Now the question is, how do I import animations from blender into the AnimationTreePlayer with the minimum effort? I mean right now I have to save each animation manually to a file and load it into the AnimationTreePlayer. Is there any other way?
But maybe I should ask this in the forum.

Thanks so much!

**Comment by mcanders** [comment]
You can use blender's [Actions](https://www.blender.org/manual/animation/actions.html#working-with-actions).  Export the scene using the Better Collada exporter (and make sure you export the armature, the mesh, and all actions) and import the resulting .dae in godot.  The actions should be available in the AnimationTreePlayer.

**Comment by slapin** [comment]
Also you might take time and fix AnimationTreePlayer to really do its job
in all cases (look for bugs on issue tracker).
Look at my and @JoshuaGrams comments.

**Comment by mcanders** [comment]
@slapin : While AnimationTreePlayer does have some issues, your comment does not pertain to THIS issue.  I'm not a member of the Godot organization, but I assume they would want you to observe proper Github issue etiquette.

**Comment by slapin** [comment]
I just need to warn newbies that AnimationTreePlayer is rough on edges and
might not be good
solution for their particular tasks. I don't think trolling will help you
here.

For the requester:
If your AnimationTreePlayer node setup did not work for you, please ping
me on IRC or submit another issue.

**Comment by mcanders** [comment]
@slapin : I was not trying to troll.  You left a comment on an issue asking someone else to fix your tangentially related problems (which are already tracked in their own issues).  Again, I cannot speak for the Godot organization, but this is generally frowned upon.

**Comment by slapin** [comment]
Well, the AnimationTreePlayer problems are not mine as I currently not
using it.
The issue is in Godot.
The AnimationTreePlayer was recommended as solution.
AnimationTreePlayer does have its issues which were mentioned to warn user.
I can't really see where you found off-topic here.
Going this far you end-up with counter-productive policy. I think policing
messages are really off-topic.
I will completely ignore policing messages from now on unless they are sent
via IRC or email
and are constructive enough, as this is true offtopic and pollutes the mail
of many people.
