### ISSUE TITLE
Android adaptive icons is cropped

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#49141]
**Godot version:**
3.3.2

**OS/device including version:**
Android 10 / Honor 9x

**Issue description:**
I tried various ways of getting the launcher icon to display right, but nothing seems to be working.
This is the icon I want to set:

![icon_192](https://user-images.githubusercontent.com/25849067/119821219-97054480-bef2-11eb-9a59-1fdea90d49e8.png)

I configured the icon and separated foreground background into own pngs and configured it in the export options.
But no matter what I do, the icon always looks like this in my launcher:

![Screenshot_20210527_132308](https://user-images.githubusercontent.com/25849067/119819033-38d76200-bef0-11eb-9ba9-111226d4c25b.jpg)

The workaround described here (https://godotengine.org/qa/60477/godot-3-2-android-exported-icon-is-cropped) by JordanMotta is also not working for me, as it produces the following error during export:

> 
> Execution failed for task ':processReleaseManifest'.
> > Manifest merger failed : Attribute application@icon value=(@mipmap/icon) from AndroidManifest.xml:31:210-244
>   	is also present at AndroidManifest.xml:31:210-244 value=(@mipmap/icon_launch).
>   	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:16:5-25:19 to override.

Adding `tools:replace="android:icon` didn't do the trick sadly, same error
It was working for me using another app in Godot 3.2

**Steps to reproduce:**
- Configure an Icon for android export

**Comment by volzhs** [comment]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
https://medium.com/google-design/designing-adaptive-icons-515af294c783
you need to make the penguin image much smaller.

here are several templates.
https://developer.android.com/google-play/resources/icon-design-specifications#download_design_templates_resources

**Comment by Calinou** [comment]
Closing per @volzhs's comment.
