### ISSUE TITLE
windows/mingw build error on latest sync

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#4914]
**Operating system or device - Godot version:**
windows (7) building via scons/mingw

**Issue description** (what happened, and what was expected):

build of current sources fails:
`In file included from platform\windows\os_windows.cpp:54:0:`
`platform\windows\joystick.h:36:96 fatal error: xinput.h: No such file or directory`
 `#include <xinput.h> // on unix the file is called "xinput.h", on windows I'm sure it won't mind`

(an identical failure occurs in joystick.cpp:30:0 since it includes joystick.h also)

Except that it *does* mind and halts the build!

**Steps to reproduce:**
`scons platform=windows -j8`

**Link to minimal example project** (optional but very welcome):
this is just the latest sync of the current github sources

**Comment by akien-mga** [comment]
You say "latest sync", but when was your previous sync? This header has been included since Dec 2015: https://github.com/godotengine/godot/commit/af633c794179d29a4bf0c01983c8b08d14553596#diff-646f2a2d7eab534e3e3df5a7b1057631R36

Ping @Hinsbart.

**Comment by gau-veldt** [comment]
quite a while ago

**Comment by gau-veldt** [comment]
[complete build transcript](http://pastebin.com/wYiWq6zP)

**Comment by Hinsbart** [comment]
@gau-veldt looks like you're using msys, I couldn't get that to compile godot either.
IIRC, it will produce other errors(in the drivers I think) after you put the correct headers in it's include search path...
So please try with another mingw distribution.

**Comment by gau-veldt** [comment]
actually it is the mingw that comes with code::blocks

**Comment by gau-veldt** [comment]
gcc (tdm-2) 4.8.1

**Comment by gau-veldt** [comment]
I'll try the build again after moving from C::B 13.12 to C::B 16.1

**Comment by gau-veldt** [comment]
still get the error on latest C::B (which uses gcc (tdm-1) 4.9.2)
**I don't use msys shell** just have sources still homed there - *I compile from the windows command prompt directly*

**Comment by vnen** [comment]
I also was never able to compile with MinGW in Windows, not even with TDM-GCC (which has a licensing hassle for using winpthreads). As Hinsbart said, even if you add the include paths it starts to give some other errors.

There's close to no one using this AFAIK, which makes supporting it quite a burden unless someone in the community decides to maintain it.

**Comment by gau-veldt** [comment]
I wouldn't know of the winpthreads issue since I use boost's (or even C++11's) threading which has no license problems.  However building in mingw worked at least up until last July.

_**So I take it is no longer possible to compile Godot on windows using free software.**_

**Comment by vnen** [comment]
> So I take it is no longer possible to compile Godot on windows using free software (Visual Studio is not free software).

Unfortunately I can't deny this. It is a sad truth. But unless someone step up to work on this it'll not be a priority.

**Comment by Hinsbart** [comment]
> So I take it is no longer possible to compile Godot on windows using free software.

It is, with the right compiler.
There seem to be different versions of mingw out there.. As I said, the one msys gave me horribly failed and it's probably similar to yours.
Then I think I tried one or two other mingw distributions until I downloaded [WinBuilds](http://win-builds.org/doku.php).
That finally provided a compiler with the capability to compile godot ;)
It's been compiling the master branch for a few months now without problems

**Comment by gau-veldt** [comment]
The right compiler == visual studio == NOT free software

**Comment by Marqin** [comment]
>So I take it is no longer possible to compile Godot on windows using free software

It was never possible, because windows is not free software :) If you really want to use mingw build, you can crossbuild it from Linux - [it works](https://travis-ci.org/godotengine/godot/jobs/133972062).

**Comment by Hinsbart** [comment]
Where did I mention msvc?

**Comment by Marqin** [comment]
Ok, this may be problem. `xinput.h` belongs to directx-sdk which, according it its readme in mingw source tree is "optional":
https://sourceforge.net/p/mingw-w64/code/HEAD/tree/trunk/mingw-w64-headers/direct-x/

So maybe your mingw build don't have it?

**Comment by Marqin** [comment]
Check if your env has `MINGW_HAS_DDRAW_H` defined.

**Comment by gau-veldt** [comment]
where do I look for that flag?

**Comment by Marqin** [comment]
add to `joystick.h`, after including dinput.h:

```C++
#ifndef MINGW_HAS_DDRAW_H
#error MINGW_HAS_DDRAW_H not defined!
#endif
```

**Comment by gau-veldt** [comment]
Ugh.  They're not there.  So much for CodeBlocks 16.1 'everything' installer actually having, well, everything.

**Comment by Marqin** [comment]
Try installing official `mingw-w64` and not the one included in Code::Blocks.

**Comment by gau-veldt** [comment]
I see why everyone is jumping ship and going to MSVC community edition...

**Comment by Marqin** [comment]
Personally I just use MSYS2 to build my projects on windows via make+gcc if I had to build on Windows and it's working ok for me. If I got some spar time I'll check how to build godot on MSYS2 (I have too slow PC to build godot in normal time...)

**Comment by reduz** [comment]
Sorry, Mingw32 is a very old and outdated compiler. Please use mingw-w64 to build instead which is up to date. There is no intention to fix build for Mingw32
