### ISSUE TITLE
`yield(get_tree().create_timer(10.0), "timeout")` cannot be parsed by GDScript compiler

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49147]
**Godot version:**
364ea7f280a3f074795e542b16b1d0ec76cf6ce2

**OS/device including version:**
No matter I guess

**Issue description:**
![image](https://user-images.githubusercontent.com/3036176/119852696-325ce080-bf18-11eb-84dc-9f788778ca14.png)

**Steps to reproduce:**
^^

**Minimal reproduction project:**
Too easy to reproduce.

**Comment by HaSa1002** [comment]
We are `await`ing now :)

**Comment by HaSa1002** [comment]
Just a guess:
```swift
func _ready():
	await get_tree().create_timer(1.0).timeout
```

**Comment by KoBeWi** [comment]
Yep. Although the error is weird, if anything, it should mention non-existent function or unexpected yield (see #41865).

**Comment by HaSa1002** [comment]
Ok the error message is just bad then. I am kind of surprised that the windows tool (3D Viewer) could load the file. However this seems to be an export bug, so this issue is a non-issue then.
Thanks for the investigation.

**Comment by Chaosus** [comment]
Ah, yeah, I forgot about await...

**Comment by chriisduran** [comment]
I´m stuck, the scene is not being loaded, theres no echo print, just works if i remove the timer
How i can delay the execution of the scene and print? @Chaosus @HaSa1002 

extends Node

func _ready():
	await get_tree().create_timer(1.0).timeout
	get_tree().change_scene_to_file("res://scenes/menu_screen.tscn")
	print("echo")
