### ISSUE TITLE
Vulkan: adding a texture causes a consoler spam.

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#49150]
**Godot version:**
Godot night build

**OS/device including version:**
Win 10 64, AMD RX 480

**Issue description:**
adding a texture causes a consoler spam.
See vid: https://drive.google.com/file/d/1xEgbyLanm8EPrLhSzuOT4K4YvbvLsVYC/view?usp=sharing

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/48886 (same cause).
