### ISSUE TITLE
Color.r8 treated as float by binary And operator

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4915]
**Operating system or device - Godot version:**
Official 2.0.3stable Win64
Windows 8.1

**Issue description** (what happened, and what was expected):
According to the documentation, Color.r8 .g8 and .b8 are int.
It should be thus possible to make binary operations with them, but the debugger says that :
`invalid operands 'float' and 'int' in operator '&'`

**Steps to reproduce:**
Run the code below.

**Link to minimal example project** (optional but very welcome):

````
var c = Color(250,150,100)
var x = c.r8 & 0xF0
````

**Comment by gau-veldt** [comment]
as a workaround try:
`var c = Color(250,150,100)`
`var x = int(c.r8) & 0xF0`

**Comment by Hinsbart** [comment]
By the way, sadly you can't actually use that constructor.
`Color(r,g,b)` takes float parameters, so:
```gdscript
var c = Color(100, 0, 0)
print(c.r8)
```
Prints `25500`, which is all wrong.

I guess the constructor should either throw some errors or automatically switch ro rgb8 mode when it recieves value greater than 1. But that's a topic for another issue.

**Comment by akien-mga** [comment]
There's ``Color8`` for that.

**Comment by bojidar-bg** [comment]
@akien-mga It should, since some people want to make "glowing" colors that exceed white.
