### ISSUE TITLE
Code editor shortcuts are still active in background behind File Explorer popup - prevents alt+up to go to parent

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#49151]
**Godot version:**

3.2

**OS/device including version:**

Linux Ubuntu 18.04 on Unity desktop

**Issue description:**

Code editor shortcuts are still active while the File Explorer popup is shown on top of it.
The code editor must be open in the (darkened) background for this to work.

**Steps to reproduce:**
1. Open the minimal repro project (but any will do). Make sure you're using default shortcuts for Move Line Up/Down and Clone Down in the code editor.
2. Open Scenes/SampleScene.tres
3. Open Scripts/Test.gd
4. Select the Sprite object in the scene. This should focus the scene. Press F3 to go back to the scripts. (You can also select the Sprite first, and make sure to open Test.gd via File > Open to avoid showing script info in the inspector. It is important you still see the Sprite object info in the inspector panel.)
5. Place your caret on some filled line like `func _ready():`
6. In the inspector panel, you should still see the Sprite object. Click on Sprite > Texture > [empty] > Load
7. In the File Explorer, double-click to enter any folder
8. I recommend shrinking the File Explorer popup to see what's going on behind, in particular the highlighted line, where you placed your caret last.
9. Now press Alt+Up, trying to go to parent folder. Instead, the highlighted line is moved up.
10. Try again pressing Alt+Up, Alt+Down, Ctrl+D and you will see the corresponding effects played in the code editor in the background

**Minimal reproduction project:**

[v3.2 - Code Editor shortcuts are active in background behind File Explorer.zip](https://github.com/godotengine/godot/files/6556813/v3.2.-.Code.Editor.shortcuts.are.active.in.background.behind.File.Explorer.zip)

![Godot 3 2 - File browser Alt-Up and Down move line + ctrl+d Clone Down in text editor in background preventing going to parent folder (Peek 2021-05-27)](https://user-images.githubusercontent.com/1067772/119897009-ba9eae00-bf37-11eb-84be-78c33f240cff.gif)

**Comment by Calinou** [comment]
This is fixed in the `master` branch, but it can't be fixed in `3.x` completely due to how editor shortcuts are handled there.

**Comment by akien-mga** [comment]
Closing as fixed in 4.0.
