### ISSUE TITLE
[Godot 4 ] building latest commit throws error 

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#49152]
When compiling with scons:

` scons -j4 target=release_debug platform=windows --max-drift=1 --implicit-deps-unchanged`

Commit hash:

364ea7f280a3f074795e542b16b1d0ec76cf6ce2

Error:
```
C:\Users\nonunknown\Desktop\godot\servers/rendering/renderer_rd/renderer_compositor_rd.h(41): fatal error C1083: Its not possible to open file include: 'servers/rendering/renderer_rd/shaders/blit.glsl.gen.h': No such file or directory
scons: *** [platform\windows\os_windows.windows.opt.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Please explain what the issue was for other users who might have the same. There's nothing worse than googling an error message to find a [closed thread with no answer](https://xkcd.com/979/)...

**Comment by nonunknown** [comment]
oh sorry, I solved this by changing

from:
`scons -j4 target=release_debug platform=windows --max-drift=1 --implicit-deps-unchanged`
to:
`scons -j4 target=release_debug platform=windows`
