### ISSUE TITLE
Executing EditorScript _run method doesn't have garbage collection

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#49168]
**Godot version:**

3.3.2stable.official

**OS/device including version:**

Windows 10

**Issue description:**

Tried to make some tests with EditorScript _run() method and "assert" to my statemachine and kept crashing and catching error: **"modules/gdscript/gdscript.cpp:560 - Condition "!p_keep_state && has_instances" is true. Returned: ERR_ALREADY_IN_USE"**
which, i guess. means that references are keep counting after script being executed and GC doesn't do his work.
So, i've tried to make another test with instancing dummy node wich do nothing and noticed that godot takes more and more memory from RAM.

**Steps to reproduce:**
1. Copy paste following script
```gdscript
tool
extends EditorScript


func _run():
	for i in range(10000):
		var node := Node.new()
```
2. Open task manager and see how many memory godot takes.
3. Run several times.
4. Open task manager and see how many memory godot takes now.

**Minimal reproduction project:**

**Comment by Xrayez** [comment]
The snippet you provided instantiates `Node`s which are not reference-counted, and must be freed with `queue_free()`. In case of `EditorPlugin`s, the nodes you instantiate must be added as children so that they can be freed automatically upon plugin's deactivation.

Do you say that when you instantiate `Reference`-derived classes inside `_run()`, they are not freed upon completion of the callback? In that case, yes I think it would be a bug.

**Comment by boruok** [comment]
here all scripts...
```gdscript
# test.gd
tool
extends EditorScript


func _run():
	for i in range(100000):
		var sm := StateMachine.new({
			"states" : {
				"idle" : load("idle.gd"),
		}})
```

```gdscript
# sm.gd
class_name StateMachine extends Reference


var _config := {
	"states" : {},
}


func _init(config: Dictionary):
	for i in config.states:
		_config.states[i] = config.states[i].new()
		_config.states[i].state_machine = self


class State extends Reference:
	var state_machine : StateMachine
```

```gdscript
# idle.gd
extends StateMachine.State
```

memory leak happens when you assigning reference to **var state_machine variable in State**

[Example.zip](https://github.com/godotengine/godot/files/6561585/Example.zip)

**Comment by Xrayez** [comment]
Yeah cyclic referencing may be an issue here. Godot has [`WeakRef`](https://docs.godotengine.org/en/stable/classes/class_weakref.html) class which can help this, but I haven't used it myself extensively.

**Comment by boruok** [comment]
@Xrayez yup, changed reference with **weakref** and now GC works. Thanks! 
```gdscript
# sm.gd
_config.states[i].state_machine = weakref(self)
```
