### ISSUE TITLE
Project Manager crashes if you launch Godot through a taskbar toolbar on Windows 10 (regression due to incorrect CWD)

### ISSUE THREAD

**Issue by Kemeros** [godotengine/godot#49179]
**Godot version:**
v4.0.dev.custom_build.364ea7f28
This bug has been there for months or maybe forever, i do not know. It's not new from this build

**OS/device including version:**
Windows 10 Home
Vulkan
GTX 1080 TI
No additional AV or Anti-Malware installed. Only what's included with Windows 10 Home.

**Issue description:**
Godot often crashes if you open Godot from a taskbar toolbar:

![image](https://user-images.githubusercontent.com/15658976/120052447-66590400-bff3-11eb-874b-3767e69e35f4.png)
(Sorry, can't copy the text since it's not reproducible by opening Godot from CMD or PowerShell)
It can happen repeatedly many times or once and stop for a few minutes. It's a weird one.

**Steps to reproduce:**
1- Create a taskbar toolbar that points to a Godot folder (C:\Godot):
![image](https://user-images.githubusercontent.com/15658976/120052491-96a0a280-bff3-11eb-8a5d-9c0d05977ecd.png)
2- Create a folder called 4.0 inside the C:\Godot folder
3- Put a Godot artifact build from the master branch in the 4.0 folder
4- Launch it from the Godot toolbar you created:
(Should look like this)
![image](https://user-images.githubusercontent.com/15658976/120052625-247c8d80-bff4-11eb-9107-336e99799692.png)

**Minimal reproduction project:**
Will crash before reaching any project

**Comment by Kemeros** [comment]
So i had a bit of time tonight and ran Sysinternals Process Monitor to understand what's happening behind the scenes(heh). The answer came quickly:

Running from Explorer or command line:
Parent PID: 11316, Command line: "C:\Godot\4.0\godot.windows.opt.tools.64.exe" , Current directory: C:\Godot\4.0\,

Running from the toolbar:
Parent PID: 11316, Command line: "C:\Godot\4.0\godot.windows.opt.tools.64.exe" , Current directory: C:\Windows\System32\,

Running it from the toolbar somehow changes the current working directory. Which later causes this:

9:31:38.2093146 PM	godot.windows.opt.tools.64.exe	14428	CreateFile	C:\Windows\System32\.godot	ACCESS DENIED

Godot is trying to create .godot in the system32 folder because the CWD is wrong. Woops.

This could be an incorrect behavior from Windows or a Godot bug, at this time, i do not know which. I will try to look for more details and also at the code. I got an intermediate skill level with PowerShell and am a Python noob... How hard can debugging C++ be right? *starts sweating pointers and references*

Let's see what a T3 tech can do with barely any dev skills.

**Comment by Kemeros** [comment]
Ok so i can reproduce by changing manually the CWD in launch.json in vscode.

"cwd": "C:\\Windows\\System32"

Same error. Will have to follow the breadcrumbs later because, sadly, my vscode lldb extension crashes right after Godot crashes so i can't debug. Will try to switch to GCC and GDB tomorrow.

**Comment by bruvzg** [comment]
See #47882 for a fix, it's probably the same issue.
