### ISSUE TITLE
VisualServer.free() conflicts with Object.free()

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#4917]
godot 2.0.3 _bugsquad edit -- it was 2.3.0_

when trying to call VisualServer.free(RID) engine just takes Object.free() function and throws exception that free function on base VisualServer takes 0 arguments

call and funcref doesn't help too

but editor suggests right function footprint tooltip after opening a brace

P.S. may be there is some workaround right now?

**Comment by akien-mga** [comment]
> godot 2.3.0

From the future? :P

**Comment by curly-brace** [comment]
not from the future, but may be i can force compiler to take VisualServer's function instead of Object's one?

**Comment by bojidar-bg** [comment]
Can confirm
