### ISSUE TITLE
Godot Physics - Bodies with only rayshapes colliders causes NaN when calculating inertia

### ISSUE THREAD

**Issue by DrRevert** [godotengine/godot#49176]
**Godot version:**

3.3.2

**OS/device including version:**

Windows

**Issue description:**

There's an oversight when GodotPhysics is calculating inertia. If the body has no colliders the inertia tensor matrix is set to identity, however there's no similar check in case of bodies with colliders with no areas (for example body with only raycast shape). This causes the inertia to be calculated as NaNs which propagates to other variables causing physics to become unstable and spamming the console with messages like 
`set_axis_angle: The axis Vector3 must be normalized.`
`instance_set_transform: Condition "Math::is_nan(v.x)" is true.`

**Steps to reproduce:**
1. Set project to use GodotPhysics
2. Setup a scene with RigidBody with Rayshape as it's only collider
3. Run the project and notice the issues.

**Minimal reproduction project:**

[GodotInertiaError.zip](https://github.com/godotengine/godot/files/6563076/GodotInertiaError.zip)

**Comment by Calinou** [comment]
cc @pouleyKetchoupp

**Comment by DrRevert** [comment]
It seems to be an easy fix in `void BodySW::update_inertias()` function in servers/physics/body_sw.cpp the `bool inertia_set` flag should be set only after making sure that shape has non-zero area.
I can't currently prepare a proper PR, I can try tomorrow, unless someone else fix it before me.

**Comment by pouleyKetchoupp** [comment]
@DrRevert You can definitely make a PR tomorrow. What you describe sounds like a good fix.

**Comment by DrRevert** [comment]
I prepared a PR for 4.0 as the issue also occurs there. I had to change the fix as there's another division by zero when calculating total_area. When testing I notcied that the mass of disabled colliders is counted towards mass of entire object, I'm not sure if that behavior is intended or not.
