### ISSUE TITLE
Label/RichTextLabel doesn't respond to visible_characters/percent_visible

### ISSUE THREAD

**Issue by Scarm2** [godotengine/godot#49189]
**Godot version:**
364ea7f280a3f074795e542b16b1d0ec76cf6ce2
Godot Engine v4.0.dev.custom_build.364ea7f28

**OS/device including version:**
Windows 10 Pro 10.0.19042
Vulkan API 1.2.162
Using Vulkan Device #0: NVIDIA - GeForce RTX 2060 SUPER

**Issue description:**
![image](https://user-images.githubusercontent.com/82760388/120074986-2011ac80-c0a8-11eb-88c9-61d1c079e681.png)
Displayed text won't respond to visible_characters and barely responds to percent_visible. Gif demonstrating it:
![pls fix](https://user-images.githubusercontent.com/82760388/120075130-bcd44a00-c0a8-11eb-8fa8-94fff1ef9b7c.gif)
This happens no matter the text length and/or font.

**Steps to reproduce:**
1. Add a RichTextLabel to your scene
2. Enable BBCode and write some text in the BBCode section.
3. Toy with visible_characters/percent_visible

**Minimal reproduction project:**
Can be done in the editor.

**Comment by akien-mga** [comment]
I can confirm the issue (this animates percent visible from 0 to 1 for both RTLs):
![](https://user-images.githubusercontent.com/4701338/133890750-9a9047a8-5925-4f79-83ff-e1440b55c84e.mp4)
