### ISSUE TITLE
GDScript does not show the functionality of InputEventKey in the InputEvent

### ISSUE THREAD

**Issue by Zennos** [godotengine/godot#49199]
**Godot version:**
3.3.1

**Issue description:**
I was using the _input function and I noticed that the InputEvent does not show property and methods from InputEventKey, such as **get_scancode()**, **scancode**, **pressed**, etc.
But running the script works fine.

![Screenshot_1](https://user-images.githubusercontent.com/42870577/120087006-9fa87700-c0ba-11eb-97b5-47b6ac7fdd15.png)

**Comment by Calinou** [comment]
This is because GDScript cannot assume that you'll be using `event` as an InputEventKey, only as an InputEvent. If you use `(event as InputEventKey).`, you'll see autocompletion for InputEventKey. If you plan to use this casting multiple times in the same scope, assign it to a variable:

```gdscript
var key := event as InputEventKey

key.something
```
