### ISSUE TITLE
Multi-Level Yield on Parent's Ready Resumes in Incorrect Order

### ISSUE THREAD

**Issue by matthewpaul-us** [godotengine/godot#49207]
I am trying to have a portion of the node tree wait until their parents are ready before executing code. My goal is to have a hierarchy of nodes that wait until their parent (or owner) is ready before grabbing a reference to them. It is for a Finite State Machine in the style of [GDQuest's FSM Tutorial](https://www.gdquest.com/tutorial/godot/design-patterns/finite-state-machine/). I am extending it, however, to allow arbitrarily nested FSMs, in order to create more complex AI.

I know that yield is undergoing a major rewrite in 4.0, so if this isn't going to be fixed before then, I would like some ideas on how to work-around the issue.

**Godot version:**
v3.3.2.stable.mono.official

**OS/device including version:**
Windows 10 Pro x64 v 1909 build 18363.1500

**Issue description:**
Yielding on parent's ready signal works for one level, but if there are more than one level of nodes that yield on parent's ready signal, the children stop waiting before the parent has finished waiting on their parent.

I expect that the parents would finish waiting on their parents before the children return from yielding on parent's ready. 

![image](https://user-images.githubusercontent.com/1484070/120107246-48dc8500-c12e-11eb-86b9-b034e1fc3c62.png)
Add this script to each child node.
```gdscript
  func _ready() -> void:
	print("%s waiting on parent %s" % [name, get_parent().name])
	yield(get_parent(), "ready")
	print("%s finished waiting on parent %s" % [name, get_parent().name]) 
```

When run, the scene should produce the following in the output window.
```
A1 Waiting on parent A
A2 Waiting on parent A
A Waiting on parent MVP
B1 Waiting on parent B
B2 Waiting on parent B
B Waiting on parent MVP
MVP Ready
A Finished Waiting on parent MVP
A1 Finished Waiting on parent A    # A1/A2 waits until after A is finished its ready function
A2 Finished Waiting on parent A
B Finished Waiting on parent MVP
B1 Finished Waiting on parent B    # B1/B2 waits until after B is finished its ready function
B2 Finished Waiting on parent B
```
Instead, it produces the following:
```
A1 Waiting on parent A
A2 Waiting on parent A
A Waiting on parent MVP
A1 Finished Waiting on parent A     # A1/A2 resume prematurely, as A has just started waiting for MVP
A2 Finished Waiting on parent A
B1 Waiting on parent B
B2 Waiting on parent B
B Waiting on parent MVP
B1 Finished Waiting on parent B     # B1/B2 resume prematurely, as B has just started waiting for MVP
B2 Finished Waiting on parent B
MVP Ready
A Finished Waiting on parent MVP
B Finished Waiting on parent MVP
```

As can be seen, the nodes A1 and A2 return from yielding on A's ready as soon as A yields on MVP's ready.

**Steps to reproduce:**

1. Create a node structure where you have a base node and children node. 
2. To each child created, add another child node.
3. Attach a script to all children that yields on their parents ready
4. run the game

**Minimal reproduction project:**
[godot-parent_ready_mvp.zip](https://github.com/godotengine/godot/files/6566294/godot-parent_ready_mvp.zip)

**Comment by KoBeWi** [comment]
This is not a problem with yield, `ready` signal is emitted independently from the `_ready()` method. If you want to wait until `_ready()` method finishes, use a custom signal.

**Comment by matthewpaul-us** [comment]
I don't really find it obvious at all. Is there some reading somewhere that could make it more intuitive to me? The timings of the engine notifications, signals, and callback functions are a little fuzzy for me about creating nodes, adding/removing them from the tree, and such.

Looking at the documentation for the [signal](https://docs.godotengine.org/en/stable/classes/class_node.html?highlight=ready%20node#signals), it states `Emitted when the node is ready`. Looking at the _ready method, it again states that it is called when the node is ready. When does the signal fire in relation to the _ready callback?

Inside the _ready() documentation, it mentions that the parent node will receive the ready notification after the children's _ready callbacks get triggered. Does that mean that the ready notification for the parent is triggered before the child _ready function finishes? Is that way it normally happens but yielding in the _ready function causes the parent to receive the notification?

If we cannot rely on the specific order of the ready signal being fired, I'm struggling to see the use cases for this signal.

**Comment by KoBeWi** [comment]
Well, here's the relevant code:
https://github.com/godotengine/godot/blob/da12086ceb21454aa505847ce4c3c1478c5a4ea6/scene/main/node.cpp#L186-L190
`NOTIFICATION_READY` will also cause `_ready()` method to be called. Nowhere inside `_ready()` method you emit the `ready` signal, so it should lead to assumption that they are independent. (the signal is emitted from C++ and a script method can't possibly affect it)

**Comment by matthewpaul-us** [comment]
Does the _ready function operate in the same thread as the signal? I know that yielding technically causes another thread to spin up, so that probably complicates things.

I'm still confused about how the ready signal seems to be fired after the _ready function is called on the parent consistently when there is only one level. Adding additional levels causes it to lose it's consistency. Unless yielding causes it to begin executing in another thread, in which case it's anybody's guess as to when things will fire in relation to each other.

(Thanks for popping the relevant code!)

**Comment by KoBeWi** [comment]
`yield` is a GDScript-only construct. GDScript functions are executed in a completely different way than C++ functions. C++ functions are called natively, i.e. as machine code. GDScript has a higher level of abstraction, it's more similar to Java bytecode and its execution is independent and more flexible (this is also why debugging GDScript is so easy). What `yield` does is pause a function mid-way and return a function state. The object/signal arguments are optional btw (not in 4.0 tho); if you use them, the signal is connected behind the scenes to resume the function from that state.

So yielding doesn't need any new thread, it just pauses GDScript call, but the main program continues normally.

**Comment by matthewpaul-us** [comment]
I appreciate the explanation. I don't think it will help me hammer down the timings of this situation specifically, but it does help me better appreciate just how decoupled GDScript and the C++ for the engine are.

Thanks so much for taking the time to help me understand! If you don't have anything else, I will close the issue.
