### ISSUE TITLE
Screen space reflections behaving strangely on orthographic Camera

### ISSUE THREAD

**Issue by Kinwailo** [godotengine/godot#49204]
**Godot version:**
3.3.2 stable

**OS/device including version:**
Win7

**Issue description:**
The old issue: #11841 stated it fixed and closed, but I found it still happen in 3.3.2

**Comment by Calinou** [comment]
@Kinwailo Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, which graphics card model and rendering backend are you using?

**Comment by Kinwailo** [comment]
Graphics card model and rendering backend: GTX660 GLES3
Minimal reproduction project: [ssr.zip](https://github.com/godotengine/godot/files/6566355/ssr.zip)

**Comment by Calinou** [comment]
I can confirm this on 3.3.2 on Linux + NVIDIA, but only in the running project. In the editor, the SSR perspective is correct when using an orthographic camera:

![image](https://user-images.githubusercontent.com/180032/120110658-aa244880-c16e-11eb-8e0c-9a87c7e5a961.png)

**Comment by Geometror** [comment]
I did some investigation and it seems like there is something wrong with the depth related calculations in the screen space reflection shader, although I couldn't figure out how to fix it yet. However, a temporary fix would be setting the cameras origin(translation) further away to something like x=200, y=200, z=200 (which is actually the case with the editor's viewport camera; this is why it looks correct in the editor) and setting the "Far" property to something around 500. You might need to adjust the rotation of the camera (to around -35 for example in your test project). This also applies to SSAO (issue #19747).

![grafik](https://user-images.githubusercontent.com/50084500/120648841-5ff7db80-c47c-11eb-8a24-f8727aa98397.png)

**Comment by lawnjelly** [comment]
Fixed by #94281 .
