### ISSUE TITLE
Document that SVG clips/masks are not supported

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#49205]
**Godot version:** v3.3.2.stable.official

**OS/device including version:** Windows 10 x64

**Issue description:** Imported svg renders without clip. In case of masks, it just renders a solid color piece.
![issue](https://user-images.githubusercontent.com/80572855/120100916-844a7400-c16d-11eb-94d1-34c5cedfe2a8.png)

**Steps to reproduce:** Import svg with clip.

**Minimal reproduction project:** 
[SvgBugReproduce.zip](https://github.com/godotengine/godot/files/6566071/SvgBugReproduce.zip)

**Comment by Calinou** [comment]
Godot uses the nanosvg library to import SVG files, and that library is no longer maintained. This means the only thing we can do is document this limitation.
