### ISSUE TITLE
Godot 4 freeze when creating Window

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#49210]
**Godot version:**
4.0.dev.custom_build. da12086ce

**OS/device including version:**
Ubuntu 21.04 Nvidia GTX 970

https://github.com/godotengine/godot/issues/41614 may be related, but this issue happens in project, not editor

**Issue description:**
When I run minimal project, then entire project freeze and when closing Godot, entire OS hang for a while.
I think that it may be Linux + Nvidia + Godot Vulkan problem

Perf shows that most of time, Godot spends inside `swap_buffers` function

![Screenshot from 2021-05-30 19-01-59](https://user-images.githubusercontent.com/41945903/120113289-0e003e80-c17a-11eb-811f-b50842db074b.png)

**Minimal reproduction project:**
```
extends Node

var TIME_TO_DELETE: float = 1.0
var time_to_delete: float = TIME_TO_DELETE

func populate() -> void:
	add_child(ClassDB.instance("Window"))

func _ready() -> void:
	populate()

func _process(delta: float) -> void:
	time_to_delete -= delta
	if time_to_delete < 0:
		time_to_delete += TIME_TO_DELETE

		for i in get_children():
			i.queue_free()
		populate()
```

**Comment by insomniacUNDERSCORElemon** [comment]
Considering the engine is made with the engine (and thus an exported project really isn't that different) this is probably the same issue as 41614. See the comments there particularly the comments by @Riteo relating to performance/synchronization. 

> Well, we already know that it's a synchronization issue of some sort, since the UI gets stuck on some Vulkan function binded to some related semaphore(see [41574 (comment)](https://github.com/godotengine/godot/issues/41574#issuecomment-683549656)).

>It's interesting though that by having a slower framerate it doesn't freeze, and I can confirm that by putting a big enough delay right before all drawing code indeed avoids all the freezes. AFAICT since the editor doesn't do any frame limiting, it uses the GPU's frame synchronization fully, and for whatever reason(never used Vulkan, but to me it feels like the fence is never actually updated, and the X server eventually times out or something) the end of a frame draw is never signaled.

Also as I've noted in 41614, for me at least compiling (with no target, which defaults to target=debug) using Clang makes freezing hard to notice except for in a few spots with multi-window enabled. In a situation like that, I could see how a much more barebones project might perform faster and thus would be more prone to crashing than your editor.

**Comment by qarmin** [comment]
Looks that in #41574 there is really good explanation why it happens(I only read 41614 content)
