### ISSUE TITLE
String formatting %03d not correct with fmod

### ISSUE THREAD

**Issue by tmape** [godotengine/godot#49216]
**Godot version:**

v3.2.2.stable.official

**OS/device including version:**

macOS Mojave Version 10.14.6

**Issue description:**

String formatting %03d not display correct when the value is fmod(1.005,1)*1000, the result should be 005 not 004

**Steps to reproduce:**
Run the following script:

var v = 1.005
var t = fmod(value,1)*1000
print(t) # result is 5
print("%03d" % [t]) # result is 004

#the result is 004, not 005

**Minimal reproduction project:**

**Comment by timothyqiu** [comment]
The result of `fmod` is a `float`.

`"%d"` prints an integer, float values will be floored according to the [doc](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_format_string.html#placeholder-types). (The result is 4 because of float precision.)

```gdscript
var v = 1.005
var t = fmod(v, 1) * 1000  # float
print(t)  # 5
print("%03d" % t)  # 004
print("%03.0f" % t)  # 005
```

**Comment by tmape** [comment]
Thanks @timothyqiu 

from `var t = fmod(v, 1) * 1000`, the result should be in `4.9999999`, but it's hard to debug when `print(t)` is not showing a float value, have any way to print it in float value?

**Comment by timothyqiu** [comment]
@tmape The default precision when printing float values is about 6 decimal digits. If a larger precision is needed, I think you have to format the value manually. It's at least 13 in this case:

```gdscript
print("%.12f", v)  # 5.000000000000
print("%.13f", v)  # 4.9999999999999
print("%.14f", v)  # 4.99999999999989
```

I think the result of `fmod` should still be considered 5 even it's actually 4.9999999999998934... It's the nature of float point values to be approximate.

```gdscript
is_equal_approx(v, 5)  # True
```

**Comment by Calinou** [comment]
Closing per @timothyqiu's comment.
