### ISSUE TITLE
set_shader_param is not working as expected.

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot#49217]
**Godot version:** 3.3.2

**OS/device including version:** Solu OS

**Issue description:**
In the official 2D in 3D demo, I converted `spatialMatrial` to `shaderMaterial` and updated the code to use set_shader_param to set texture. But instead of rendering the Ping-Pong game, it renders a white surface. 

Both plans are identical but the white plane is using converted `shaderMaterial`.
![Screenshot from 2021-05-31 13-48-28](https://user-images.githubusercontent.com/29702428/120163561-42760800-c217-11eb-9262-191c85d54d21.png)

**Steps to reproduce:**
1. Download [demo.zip](https://github.com/godotengine/godot/files/6568822/demo.zip) and play.

**Comment by kleonc** [comment]
Your uniform is called `texture_albedo` but you're getting/setting `albedo_texture` shader param instead. Thus it's not working.

**Comment by Janglee123** [comment]
Oh my bad, Should have checked the shader code once. Thank you so much for correcting it.
