### ISSUE TITLE
Inspector is not showing VisualScriptNode properties

### ISSUE THREAD

**Issue by DavidCambre** [godotengine/godot#49229]
**Godot version:**

master

**OS/device including version:**

win10 GLES3

**Issue description:**
The inspector changes its category tabs but does not display node properties witch are crucial for VisualScript operation

![inspector error master](https://user-images.githubusercontent.com/20573784/120227403-5aff1600-c249-11eb-8a4b-211747669996.gif)
![inspector error 3 3 2stable](https://user-images.githubusercontent.com/20573784/120227406-5d617000-c249-11eb-956b-5037eab7cd5f.gif)

**Steps to reproduce:**
use .VS in master branch

**Minimal reproduction project:**

**Comment by Geometror** [comment]
I can't reproduce this issue on the current master branch(f0b17bcddb) as well as the latest unofficial master build from https://hugo.pro/projects/godot-builds/.
![grafik](https://user-images.githubusercontent.com/50084500/120792765-49ae5600-c536-11eb-86df-be8772511b42.png)
Could you test it again with the latest version?

**Comment by DavidCambre** [comment]
@Geometror,
Just tried using https://hugo.pro/projects/godot-builds/. create new project new .vs
And got the same old result.

Do you use Mac Linux or Windows?

**Comment by Geometror** [comment]
I am using Windows 10(21H1). 
To which node exactly did you attach the VisualScript or did you just create a resource file in the project folder?
Could you provide a minimal reproduction project, just that we have the same starting point for sure?

**Comment by DavidCambre** [comment]
[44.zip](https://github.com/godotengine/godot/files/6599638/44.zip)

I just create new scene and attach a new .vs to the root

**Comment by Geometror** [comment]
Still can't reproduce :(
Are there any errors printed in the console?
You could do the following and then try again:
- Delete `%APPDATA%\Godot` after you created a backup of that folder! (Otherwise your editor settings for all Godot versions will be lost!)
- Delete `%TEMP%\Godot`

**Comment by DavidCambre** [comment]
That worked! ...
And all this time I taught  master/VisualScript was broken.
Thanks man

**Comment by DavidCambre** [comment]
@Geometror, Do you know what was the cause?

**Comment by Geometror** [comment]
Not exactly, that is hard to find out, probably the configuration file (or cache) got corrupted, because Godot 4 is under heavy development and still in pre-alpha phase, so a lot of things change. You could trace back the exact file which caused this to stop working by readding all folders and files one by one from your backup and test again every time, but I don't think that's worth it :)

**Comment by DavidCambre** [comment]
OK then I'll close this issue.

Thanks man
