### ISSUE TITLE
Mispositioned diacritic marks

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#49224]
**Godot version:**
3.3.2 Stable Mono Custom build

**OS/device including version:**
Windows 10 x64 1809

**Issue description:**
I used RichTextLabel with the custom font named Alegreya Regular for my project and at some moment I decided to change the custom font of it to more fine-looking. The issue is when I changed it, the diacritic marks of words was shifted to the right. So, even if the diacritic mark is above the last letter, it will be literally dangling in the air.
Here's the example word:
![image](https://i.imgur.com/Hr8oXHv.png)
This is how it looked before changes (the font is Alegreya Regular):
![image](https://i.imgur.com/n3NbDO7.png)
This is how it looks after the font change (the font is Lora Regular):
![image](https://i.imgur.com/eRihndl.png)
One should have in mind that I tried to type the same word with the same font in LibreOffice. It looks like this:
![image](https://i.imgur.com/vA6zwD3.png)
So it's definitely not a font bug. It's a bug of something that renders it.

For comparision: I tried to really move the diacritic mark in the word. Results is below.
The text:
![image](https://i.imgur.com/kSHDHlD.png)
Same text in LibreOffice:
![image](https://i.imgur.com/kel8Udq.png)
Same text in Godot's RichTextLabel:
![image](https://i.imgur.com/Csf1aQA.png)
As you can see on the last screenshot, the diacritic mark is not on it's place.

**Steps to reproduce:**
1. Add RichTextLabel.
2. Set Lora Regular as the custom font of it.
3. Type some text with diacritics in the "Text" field.
4. See the bug.

WARNING: for the bug to be reproduced, **the diacritic marks should be separate from letters**. If you would type a text where each diacritic mark is an inseparable part of the letter, the bug won't show up.
Example:
![image](https://i.imgur.com/0Pl7Hq8.png)
![image](https://i.imgur.com/uIaDYKl.png)
![image](https://i.imgur.com/DIqb8fR.png)

**Minimal reproduction project:**
[Diacritic Bug Test.zip](https://github.com/godotengine/godot/files/6570446/Diacritic.Bug.Test.zip)

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by Calinou** [comment]
I can confirm this on 3.3.2 on Linux:

![image](https://user-images.githubusercontent.com/180032/120199340-6b9c9580-c223-11eb-953b-75f9a59656b8.png)

Therefore, the bug isn't Windows-specific like https://github.com/godotengine/godot/issues/23093 is on 3.x.

**Comment by Teashrock** [comment]
Update: It's the same in a simple Label.
![image](https://i.imgur.com/Aut3Vb6.png)

It's not a bug in RichTextLabel.

**Comment by bruvzg** [comment]
It's a Godot font handling limitation, fixed in 4.x by the complex shaping. With the 3.x font implementation, which is drawing each glyph individually it's highly unlikely this can be fixed.

4.x:

<img width="530" alt="Screenshot 2021-05-31 at 16 29 22" src="https://user-images.githubusercontent.com/7645683/120201086-b58a7900-c22d-11eb-89da-9c1ea0e3b0fc.png">

**Comment by Teashrock** [comment]
@bruvzg 
Can we backport the complex shaping to 3.x?

**Comment by bruvzg** [comment]
> Can we backport the complex shaping to 3.x?

It's part of the huge set of changes, which involves breaking API and binary compatibility with GDNative plugins. Backporting is possible (I have an incomplete and a bit outdated backport here - https://github.com/bruvzg/godot/tree/ts_32), but it won't happen for the official 3.x releases.

**Comment by Calinou** [comment]
Closing, as this is fixed in `master` and can't be fixed in `3.x` without breaking compatibility with existing projects.
