### ISSUE TITLE
Unable to export custom enum

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#49220]
**Godot version:** v3.3.2.stable.official

**Issue description:** It is not possible to use exports variables with a **custom enum without a name** in custom resource types.

**Steps to reproduce:**
![изображение](https://user-images.githubusercontent.com/5412322/120172723-c4b4fb00-c21c-11eb-85e2-b99ab81da7cb.png)
![изображение](https://user-images.githubusercontent.com/5412322/120172792-d6969e00-c21c-11eb-93de-75cf07f8fdd1.png)

**Minimal reproduction project:** [project.zip](https://github.com/godotengine/godot/files/6569327/project.zip)

**Comment by kleonc** [comment]
> It is not possible to use exports variables with a custom enum without a name in custom resource types.

Generally, it is not possible to use export variables with an enum without a name and that's expected. I don't see an issue here.

**Comment by akien-mga** [comment]
`export(Category)` doesn't make sense, `Category` is a class in your example, not an enum. So it can't be an integer type.

**Comment by toby3d** [comment]
> `export(Category)` doesn't make sense, `Category` is a class in your example, not an enum. So it can't be an integer type.

Okay, but then how do you refer to such an enum list in a class?

**Comment by akien-mga** [comment]
You can't refer to it if it's anonymous, so you need to give it a name.
```gdscript
class_name Category
extends Reference

enum Fruit {
	APPLE,
	ORANGE,
	BANANA,
}
```
```gdscript
class_name Fruit
extends Resource

export(Category.Fruit) var category: int = Category.Fruit.BANANA
```

**Comment by fulezi** [comment]
> ```gdscript
> extends Reference
> ```

This code worked for me except I had to inverse (using godot 3.4) the `class_name` and `extends` pragma:

> extends Reference
> class_name Category
