### ISSUE TITLE
Crashes when calling C# code from a gdscript thread

### ISSUE THREAD

**Issue by muevoid** [godotengine/godot#49230]
**Godot version:**
7610409b8a14b8499763efa76578795c755a846d

**OS/device including version:**
Mobile gtx 1660ti, latest nvidia drivers, gles2
Windows 10 - Insider edition

**Issue description:**
When calling C# from a gdscript in a thread it crashes on startup. The expected result is for it to not crash.

**Steps to reproduce:**
Create a simple scene with a node with a gdscript that opens a thread and calls c# code on that thread. Launch scene and it crashes with the following error:
```
Mono: Log file is: 'C:\Users\muevo\AppData\Roaming/Godot/mono/mono_logs/2021-05-31_17.08.21_3516.log'                   ERROR: GDMonoLog::mono_log_callback: Mono: FATAL ERROR '* Assertion at ..\mono\mini\debugger-agent.c:4175, condition `!tls' not met                                                                                                              (in domain , error)', ABORTING! Logfile: 'C:\Users\muevo\AppData\Roaming/Godot/mono/mono_logs/2021-05-31_17.08.21_3516.log'.                                                                                                                      At: modules\mono\mono_gd\gd_mono_log.cpp:93      
```

**Minimal reproduction project:**
[CSharpCrash.zip](https://github.com/godotengine/godot/files/6572381/CSharpCrash.zip)

**Comment by muevoid** [comment]
Here's the relevant line in mono: https://github.com/mono/mono/blob/6e079842a6575052adabfd16f35d3362a2f5cf78/mono/mini/debugger-agent.c#L4138

I don't have much experience with cpp or godot's internal workings in general but looking through the mono source code and godot's I personally can't find where this function is being called from(obviously it is) so this is definitely something I don't think I can solve on my own

**Comment by muevoid** [comment]
Update: The problem still persist but if I export in release it runs fine. So this is a problem with debugging and is still an issue in editor and debug builds. At least for now I have an annoying way to test

**Comment by RandomShaper** [comment]
Couldn't reproduce either on 3.2.3-stable nor 3.3.2-stable.

**Comment by muevoid** [comment]
> Couldn't reproduce either on 3.2.3-stable or 3.3.2-stable.

Hmmm strange I am using godot_voxel as well but I don't see why that would cause it even when not using those functions or nodes. Perhaps I did something wrong in compiling godot. I will try compiling from scratch

**Comment by muevoid** [comment]
Still happening for me :/ when trying again I tried both 3.3.2 and 3.3.3.rc

**Comment by muevoid** [comment]
Same error on 3.2

**Comment by muevoid** [comment]
If it helps at all here is the mono log in appdata:
[2021-06-01_05.26.47_17196.log](https://github.com/godotengine/godot/files/6575504/2021-06-01_05.26.47_17196.log)

**Comment by RandomShaper** [comment]
Just rechecked. I was silly enough to assume it was running fine since I got no crash, but it seems I had something wrong in my setup, because the C# function was not being called at all (with an error in the console window).

Now, if it happens on 3.2 as well, I'd say it's more related to Mono integration than core threading, so I think it's out of the scope I could deal with properly.

**Comment by neikeq** [comment]
Looking at the error in the log file:

```
* Assertion at ..\mono\mini\debugger-agent.c:4175, condition `!tls' not met
```

This should not happen if this patch for Mono is applied: https://github.com/godotengine/godot-mono-builds/blob/aa9e050543986ebbd8c307f6eee9cc0806d98da9/files/patches/mono-dbg-agent-clear-tls-instead-of-abort.diff

Are you experiencing this on a custom build? This is expected to happen with official Mono builds unless you build Mono itself with that patch. Fortunately you can grab our custom Mono builds instead: https://github.com/godotengine/godot-mono-builds/releases

**Comment by neikeq** [comment]
Regarding Godot 3.2, AFAIK we're already applying this patch in our official builds but I don't remember if this was after that version or not. @akien-mga Is the patch including only in releases after 3.2? If so this can be closed as fixed in new releases.

**Comment by muevoid** [comment]
Ok so it got past 100% but now I get this error:
```
b"C:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmini_la-driver.o):(.bss+0x0): multiple definition of `_dowildcard'\r\nC:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/../lib\\libmingw32.a(lib64_libmingw32_a-wildcard.o):wildcard.c:(.data+0x0): first defined here\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmini_la-mini-amd64.o):(.text+0x144): undefined reference to `__imp__wassert'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmini_la-mini-amd64.o):(.text+0x267): undefined reference to `__imp__wassert'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmini_la-mini-amd64.o):(.text+0x316): undefined reference to `__imp__wassert'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmini_la-mini-amd64.o):(.text+0x3d6): undefined reference to `__imp__wassert'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmini_la-mini-amd64.o):(.text+0x46f): undefined reference to `__imp__wassert'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmini_la-mini-amd64.o):(.text+0x53d): more undefined references to `__imp__wassert' follow\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x2ae): undefined reference to `GetFileVersionInfoSizeW'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x303): undefined reference to `GetFileVersionInfoW'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x348): undefined reference to `VerQueryValueW'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x399): undefined reference to `VerQueryValueW'\r\nC:\\Users\\muevo\\mono-installs\\desktop-windows-x86_64-release\\lib\\libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x4ab): undefined reference to `VerQueryValueW'\r\ncollect2.exe: error: ld returned 1 exit status\n"
=====
scons: *** [bin\godot.windows.opt.tools.64.mono.exe] Error 1
scons: building terminated because of errors.
```

**Comment by muevoid** [comment]
I got mono built with visual studio with the patches but have no idea what to do from here

**Comment by muevoid** [comment]
Ok I got somewhat further intial binary compiles but now I get:

```
Mono: Log file is: 'C:\Users\muevo\AppData\Roaming/Godot/mono/mono_logs/2021-06-02_00.00.48_22788.log'
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `C:/Users/muevo/Documents/Projects/Code/godot/bin/GodotSharp/Mono/lib\mono\4.5\mscorlib.dll' directory.
```

when launching it to generate glue

**Comment by neikeq** [comment]
You need to Mono BCL (Base Class Library). It has to be for the same version of Mono you built, otherwise you'll get out of sync errors. If you built Mono [6.12.0.144](https://github.com/mono/mono/tree/mono-6.12.0.144) then you can use [our builds](https://github.com/godotengine/godot-mono-builds/releases/tag/release-aa9e050) (`bcl-desktop-win32.zip`).
Once you have the BCL you must pass the following options to SCons: `mono_bcl=path/to/bcl/ copy_mono_root=yes`. That will tell SCons to copy it to the output directory for Godot to use (`bin/GodotSharp/Mono/lib\mono\4.5`).

**Comment by muevoid** [comment]
That works! Thank you so incredibly much! I personally don't mind building mono with visual studio for msvc but it would be nice if one of the following could happen to make it easier for others to use patched mono builds.

1) Provide msvc versions of mono
2) Fix mingw linking error with prebuilt windows mono
3) Better support windows with the native mono build scripts

I think this issue can be closed now

**Comment by akien-mga** [comment]
Maybe the existing documentation on build Godot with Mono support needs to be improved? Especially if users *must* use our patched Mono builds and not upstream Mono distributions.

**Comment by muevoid** [comment]
That would also help a lot I saw no mention of the parameter mono_bcl in the docs(I probably could've gotten it myself if so). It would also be nice to walk the user through how to use msvc if needed(it wasn't difficult at all).

**Comment by neikeq** [comment]
The docs must be updated indeed, I've added it to my list this month.
But further improvements to the build system in this regard are unlikely though, as with the expected switch to .NET 6 in Godot 4.1 we won't be building Mono ourselves anymore (and the patches won't be necessary either with the switch to AssemblyLoadContext), so I prefer not to waste much time there other than fixing the docs.
