### ISSUE TITLE
Visual Script Rich Text Label Value Box opens to Create New Object

### ISSUE THREAD

**Issue by Anaxan** [godotengine/godot#49231]
**Godot version:**

3.3.2

**OS/device including version:**

Ubuntu 20.10/Atermiter dual Xeon motherboard, gtx 970 nvidia package 460

**Issue description:**

Attempted to put text in a value box;  opened to create new object screen. I expected to  type text in box.

**Steps to reproduce:**
Add a rich text label to scene, drag in a set text( label or BBCode), click on value box. Similar to issue #44336. 

![rich_text_label_bug](https://user-images.githubusercontent.com/81984273/120248723-571dc480-c246-11eb-8ec2-99910d7d9752.gif)

**Minimal reproduction project:**

Will create if requested.

**Comment by Gallilus** [comment]
This seems fixed in the master branch!
