### ISSUE TITLE
OS.window_fullscreen with old value when toggling fullscreen in html5 exported version

### ISSUE THREAD

**Issue by dpensky** [godotengine/godot#49242]
**Godot version:**
 v3.3.stable.official

**OS/device including version:**
Linux Ubuntu Chrome

**Issue description:**
The variable that controls the full screen does not update its value immediately, even though it is manually set

**Steps to reproduce:**

```
print('state before: %s' % OS.window_fullscreen)
OS.window_fullscreen = !OS.window_fullscreen
button_fullscreen.visible = state
button_not_fullscreen.visible = !state
print('state after: %s' % OS.window_fullscreen)
```

First line and last line print the same value

Fullscreen toggle works correctly.
it seems that there is some kind of 'delay' in updating the variable value.
Works ok on the engine. Problem only happens on the html5 exported version.

**Comment by Faless** [comment]
> it seems that there is some kind of 'delay' in updating the variable value.
> Works ok on the engine. Problem only happens on the html5 exported version.

That is kind of expected, requesting fullscreen is an asynchronous operation in JavaScript. so you are not in fullscreen until the new iteration.
