### ISSUE TITLE
Theme editor preview broken.

### ISSUE THREAD

**Issue by jjay** [godotengine/godot#4924]
**Operating system or device - Godot version:**
OSX 10.11.5, Godot built from [73918100b](https://github.com/godotengine/godot/commit/73918100b)

**Issue description** (what happened, and what was expected):
Theme editor preview broken.
![godot_theme_preview_bug](https://cloud.githubusercontent.com/assets/122736/15655553/c718b286-26a6-11e6-8711-3d8f678f4b30.png)

**Steps to reproduce:**
1. Create new project
2. Create new scene
3. Add Control node
4. Create new theme for control (in Control inspector)
5. Inspect the created theme

**Comment by reduz** [comment]
I can't seem to reproduce this, still though Godot's theme editor needs to be seriously improved..
