### ISSUE TITLE
PCK/Zip Export no longer include files in ignored folders

### ISSUE THREAD

**Issue by slasktotten** [godotengine/godot#49252]
**Godot version:**
3.3.2

**OS/device including version:**
 OS X 11.3

**Issue description:** 
After updating from 3.2.2 to 3.3.2 files in folders with a .gdignore file are no longer part of .pck/zip export.

**Steps to reproduce:**
Create a folder. Add .gdignore and a resource to. Export as pck/zip.

**Minimal reproduction project:**
[non_resource_exporter_test.zip](https://github.com/godotengine/godot/files/6583658/non_resource_exporter_test.zip)

**Comment by akien-mga** [comment]
That's expected, folders with a `.gdignore` file should be ignored and not exported. The previous behavior was a bug, which has been fixed in 3.3.

**Comment by slasktotten** [comment]
Suspected this was the case. Thanks!
