### ISSUE TITLE
The `Transform.LookingAt()` method doesn't exist in C#

### ISSUE THREAD

**Issue by AdrianCarmonaRoda** [godotengine/godot#49259]
**Godot version:**
Godot 3.3.1 Mono

**OS/device including version:**
Windows 10
CPU: AMD Ryzen 5 3600X
GPU: NVIDIA GTX 1080

**Issue description:**
The function looking_at() (or LookingAt()) from the class Transform is non existent on the C# API

**Comment by Calinou** [comment]
cc @aaronfranke

**Comment by AdrianCarmonaRoda** [comment]
After checking, it does exist in C# where it doesn't is in Transform2D
And in GDScript it don't exist either

**Comment by AdrianCarmonaRoda** [comment]
My mistake, I confused the looking at functionality, sorry for the inconveniences

**Comment by aaronfranke** [comment]
For future reference, you can find out what APIs the built-in C# structs have by just looking at the files in this folder: https://github.com/godotengine/godot/tree/master/modules/mono/glue/GodotSharp/GodotSharp/Core

In particular, [like 166 of Transform.cs](https://github.com/godotengine/godot/blob/master/modules/mono/glue/GodotSharp/GodotSharp/Core/Transform.cs#L166) has this method.

**Comment by AdrianCarmonaRoda** [comment]
Thank you!
