### ISSUE TITLE
Creating editor feature profiles doesn't work

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#49257]
**Godot version:**
v4.0.dev.custom_build.8b06d4275

**OS/device including version:**
Windows 10

**Issue description:**
Creating editor feature profiles doesn't work. It just puts this in the console whenever tried:
```
ERROR: Cannot create file 'feature_profiles/newprofile.profile'.
   at: (editor\editor_feature_profile.cpp:200)
ERROR: Cannot open directory 'feature_profiles'.
   at: (editor\editor_feature_profile.cpp:351)
```

https://user-images.githubusercontent.com/12120644/120512827-ae807980-c399-11eb-94bf-fe036bca180b.mp4

**Steps to reproduce:**

- Create new project
- Open `Manage Editor Features...`
- Press `Create Profile`

**Minimal reproduction project:**
new project

**Comment by Calinou** [comment]
How did you start Godot? There's an issue where an incorrect CWD can cause Godot to try to write files to an invalid directly.

**Comment by foxydevloper** [comment]
> How did you start Godot? There's an issue on Windows where an incorrect CWD (such as `C:\Windows\System32\`) can cause Godot to try to write files to an invalid directly.
> 
> Also, does this occur if you move the Godot executable to the `C:` drive and run it there?

I downloaded the windows-editor zip from github actions so I didn't have to compile

**Comment by pycbouh** [comment]
@Calinou While I've noticed the same issue while debugging, it still happens if you run the executable directly.

**Comment by timothyqiu** [comment]
I also experienced the same issue on macOS.

**Comment by Calinou** [comment]
I can confirm this on Linux too:

```
❯ godot-init /tmp/b
Godot Engine v4.0.dev.custom_build.ff648e250 - https://godotengine.org
Vulkan API 1.2.162
Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080
- Vulkan multiview supported:
  max views: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 32
  stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE, STAGE_RAYGEN_KHR, STAGE_ANY_HIT_KHR, STAGE_CLOSEST_HIT_KHR, STAGE_MISS_KHR, STAGE_INTERSECTION_KHR, STAGE_CALLABLE_KHR
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
  quad operations in all stages
 
ERROR: Error loading default feature profile: dddsds
   at: _notification (editor/editor_feature_profile.cpp:303)
ERROR: Cannot open directory 'feature_profiles'.
   at: _update_profile_list (editor/editor_feature_profile.cpp:336)
```

**Comment by pycbouh** [comment]
This was accidentally broken by https://github.com/godotengine/godot/pull/49050. There used to be `get_settings_dir` exposed and used across the editor to retrieve the root of the settings/configuration directory. It is used by feature profiles, as well as script templates for example. In #49050 during refactoring an internal variable `config_dir` was exposed via `get_settings_dir`, and `settings_dir` while kept was never set.

I'll talk with @reduz which one to keep and make a PR fixing this issue.
