### ISSUE TITLE
Subsequent requests in `HTTPRequest` don't resolve after #49026

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot#49261]
**Godot version:**

`master` @ https://github.com/godotengine/godot/commit/9990f28d8414e27843eb0626fbf7f0277e6c9130

**OS/device including version:**

Windows 10

**Issue description:**

#49026 breaks file downloading (e.g. export templates downloading in the editor). The download stops at an unassuming status `STATUS_DISCONNECTED`:

![image](https://user-images.githubusercontent.com/11782833/120540728-ad7b3680-c3f1-11eb-9217-6f5992767951.png)

If `use_threads` is disabled, the status changes to `STATUS_RESOLVING`, but it still stops at that and never downloads anything.

![image](https://user-images.githubusercontent.com/11782833/120540925-e74c3d00-c3f1-11eb-8646-6533b9e82b20.png)

Code that doesn't work:
```cpp
	download_templates->set_download_file(EditorPaths::get_singleton()->get_cache_dir().plus_file("tmp_templates.tpz"));
	download_templates->set_use_threads(true);

	Error err = download_templates->request(p_url);
```

But requests like this do work:
```cpp
	request_mirror->request("https://godotengine.org/mirrorlist/" + p_version + ".json");
```

**Steps to reproduce:**
Build `master` from https://github.com/godotengine/godot/commit/9990f28d8414e27843eb0626fbf7f0277e6c9130 with `version.py` set to a valid stable release, then try to download export templates from the editor. Mirror list is successfully fetched, but file download hangs as described above.

**Minimal reproduction project:**

Not applicable.

**Comment by akien-mga** [comment]
CC @sarchar @Faless

**Comment by sarchar** [comment]
Interesting! I'll have a look today

**Comment by sarchar** [comment]
I was able to reproduce this same bug in c5f237e, so I don't think it's related to the DNS request.

**Comment by sarchar** [comment]
I have a fix and will create a PR shortly.
