### ISSUE TITLE
Incorrect invalid operands when using enums

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#49278]
**Godot version:**
Godot master af3ebc96ed07810e001824743fbce1e01f565079

**OS/device including version:**
any

**Issue description:**
When using enums comparisons give a bogus invalid operands error

**Steps to reproduce:**
Use the following code:
```
extends Node

enum Test { ONE, TWO }
var test : Test = Test.ONE

func testing():
	if test == Test.TWO:
		# this is a test
		pass
```

We now get the error ` "Invalid operands "Test (enum)" and "TWO (enum value)" for "==" operator.` on the if statement

**Comment by joemicmc** [comment]
I'm seeing this issue in Godot 4.0 alpha 1.  To reproduce follow the steps in the original description. Removing the type from `var test` will allow comparison to work though...
