### ISSUE TITLE
Placing a colon (:) on the Project Name interferes with userdata

### ISSUE THREAD

**Issue by janmarcano** [godotengine/godot#4928]
Windows 10 - Godot 2.0.3 (Steam)

If you have a colon on your project name, you can't access user:// since Windows filesystem won't be able to make a project directory with a colon on it's name.

i.e.:
Project name: "Example: The Coloning"
User data folder on Windows would be: "%AppData%\Roaming\Godot\app_userdata\Example: The Coloning"
But Windows can't create a folder named "Example: The Coloning", so the user directory is never created.

**Comment by vnen** [comment]
I think this should be trivial to fix,

**Comment by KelinciFX** [comment]
Isn't that Windows OS doesn't allow us make a folder which has certain characters (as shown by the pict below) by default?

![windows folder naming](https://cloud.githubusercontent.com/assets/12244526/15741225/90a44c0c-28da-11e6-8d14-4fbf3a9ac93a.png)

**Comment by vnen** [comment]
> Isn't that Windows OS doesn't allow us make a folder which has certain characters

Yes, but because of that Godot shouldn't even try to make a file/folder with any of those characters. And this is true for any OS, not only Windows.

**Comment by janmarcano** [comment]
Precisely! A workaround should be made. Probably just ignore/skip the colon.
