### ISSUE TITLE
Various inconsistencies in shortcut naming

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#49299]
**Godot version:** 5d9cab3aeb3c62df6b7b44e6e68c0ebbb67f7a45

There are a variety of inconsistencies & confusing names for shortcuts. Some don't follow proper capitalization, some end with a single period, and some don't describe what they do very well. These are some that could be changed for clarity & consistency 
**current** -> **recommended**

**Next script** -> **Next Script** `script_editor/next_script`
**Previous script** -> **Previous Script** `script_editor/prev_script`
**Next tab** -> **Next Scene Tab** `editor/next_tab`
**Previous tab** -> **Previous Scene Tab** `editor/prev_tab`
**Open the next Editor** -> **Next Editor Tab** `editor/editor_next`
**Open the previous Editor** -> **Previous Editor Tab** `editor/editor_prev`

**Filter Files...** -> **Focus FileSystem Filter** `editor/filter_files`
More clear that it focuses on a specific dock.
It makes sense to remove the ellipsis since it does not open a new dialog, it just focuses on a different dock. The `Show in FileSystem` and `Open in Inspector` shortcuts also don't include ellipsis

**Open the search box.** -> **Focus Search/Filter Bar** `editor/open_search`
The keybind is also used for focusing on search/filter bar in menus.
Changing this would be an issue since the editor log uses the shortcut's name as tooltip

![godot windows tools 64_2021-06-03_20-40-49](https://user-images.githubusercontent.com/12120644/120729267-b5e47780-c4ac-11eb-8239-a092577a4779.png)

**Comment by skytower175** [comment]
Hi so where is this problem located?

**Comment by LightningAA** [comment]
> Hi so where is this problem located?

Try searching for the shortcut names in the codebase

**Comment by skytower175** [comment]
HI I am just wondering is the build broken. Because if it is I don't know how to make it work

**Comment by Calinou** [comment]
> HI I am just wondering is the build broken. Because if it is I don't know how to make it work

The `master` branch builds fine, but you need a graphics card with Vulkan support to run it.
