### ISSUE TITLE
Typing `0` in a certain spot of a script in my game creates a memory leak

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#49293]
**Godot version:**
v4.0.dev.calinou.3b3a55ca0

**OS/device including version:**
```
$ uname -a
Linux unfa-desktop 5.12.2-1-MANJARO #1 SMP PREEMPT Fri May 7 17:53:15 UTC 2021 x86_64 GNU/Linux

$ inxi
CPU: 8-Core AMD Ryzen 7 1700 (-MT MCP-) speed/min/max: 1958/1550/3000 MHz Kernel: 5.12.2-1-MANJARO x86_64 Up: 25m 
Mem: 6070.5/32103.4 MiB (18.9%) Storage: 3.87 TiB (52.3% used) Procs: 436 Shell: Bash inxi: 3.3.04

$ inxi -G
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] driver: amdgpu 
           v: kernel 
           Device-2: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo 
           Display: x11 server: X.Org 1.20.11 driver: loaded: amdgpu resolution: 1: 1920x1080 2: 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.40.0 5.12.2-1-MANJARO LLVM 11.1.0) v: 4.6 Mesa 21.0.3
```

**Issue description:**
Godot freezes and steadily allocates more and more memory after typing `0` before the first character in line 11 in `Chat.gd` script in my game.

The bug in action:
https://youtu.be/kII1XJX1LII

**Steps to reproduce:**
1. Load provided project
2. Go to `Chat.gd` file
3. Insert `0` before the first character in line 11
4. Watch Godot freeze and eat memory

**Reproduction project:**

https://github.com/unfa/liblast/tree/a54eb54293aa771a6b4bd642eee7312af7422e96

**Comment by lyuma** [comment]
I believe this to be the same issue as
godotengine/godot#50750

**Comment by lyuma** [comment]
Consolidating into #50865
