### ISSUE TITLE
Searching shortcuts by bound key ignores shortcuts in Common category

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#49294]
**Godot version:**
v4.0.dev.custom_build.f288a7948

**OS/device including version:**
Windows 10

**Issue description:**
When searching through shortcuts, searching for certain key bindings doesn't include results from common

![image](https://user-images.githubusercontent.com/12120644/120723174-3c925800-c49f-11eb-83fe-04bbd4bf73dd.png)

You would expect the result for `ui_select` to show up when searching "space" since it's bound to space

![image](https://user-images.githubusercontent.com/12120644/120723233-5b90ea00-c49f-11eb-9d0b-37117a3f2a5b.png)

**Steps to reproduce:**
Search shortcuts with a key bound to a common shortcut

**Minimal reproduction project:**
editor

**Comment by Calinou** [comment]
cc @EricEzaM
