### ISSUE TITLE
3d camera resets default clear color to gray and no longer allows it to be changed

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#4930]
see here

notice that my background is black but when camera is in the scene the background is gray

![rec1](https://cloud.githubusercontent.com/assets/6987027/15656978/dda3f19a-267a-11e6-872b-c81f65dd9840.gif)

is this normal or a bug?

EDIT:

further inspection reveals camera behaves normally if if worldevenvironment WITH environment is present

![rec1](https://cloud.githubusercontent.com/assets/6987027/15657261/4916f452-267d-11e6-8a34-0b5a2a48ea18.gif)

**Comment by reduz** [comment]
yeah, cameras override the clear color, this is more like a design problem and some people is using it as a feature. Can't be fixed until 3.0.

**Comment by trollworkout** [comment]
@reduz Reduz on OSX the clear colour cannot even be set from script (there is another issue i submitted for that). So I was forced to use a a scaling sprite with modulate on it. 

Do you wish to keep this bug open?  Is this something you wish to change?

**Comment by reduz** [comment]
Keep it open , we'll close when we get this fixed in 3.0.

**Comment by reduz** [comment]
got fixed in 3.0
