### ISSUE TITLE
Vulkan Error while parsing file

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#49315]
**Godot version:**
Godot night build

**OS/device including version:**
OS Win 10 64, AMD RX 480

**Issue description:**
Ive downloaded the latest night build and while opening my project - "Error while parsing file"
image: https://drive.google.com/file/d/1XNZqmSYaSuf_2GRxnxEqPmHiMWH87Koh/view?usp=sharing

**Comment by Xrayez** [comment]
If you're opening a project created in Godot 3.x versions, this will likely won't work (a converter has to be implemented to migrate 3.x projects to 4.x projects eventually, I guess).

**Comment by Akira1San** [comment]
No, but creating a new file and saving works.

**Comment by Calinou** [comment]
Closing per @Xrayez's comment. 3D mesh format 
conversion code has yet to be implemented.
