### ISSUE TITLE
Clicking 'Selection Only' in text replace popup deselects everything

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#49329]
**Godot version:** 3.3.2.stable.mono

**OS/device including version:** Windows 10

**Issue description:** if you are in the text editor and you press Ctrl+R to bring up the text replace window, select some text, then click the 'Selection Only' check box, it will deselect all of the text. I'd expect this to not deselect text as I usually select the text I want to replace parts of before opening the replace window, so it's very annoying to have to select it again.

**Steps to reproduce:**
 Open code editor in godot, press Ctrl+R to bring up the text replace window, select some text, then click the 'Selection Only' check box in the text replace window, it will deselect all of the text.

https://user-images.githubusercontent.com/7292421/120876583-8c485080-c57f-11eb-9e5c-a74d9264a45e.mov

**Comment by EricEzaM** [comment]
Cannot reproduce in 4.0, looks to be only in 3.X.

**Comment by Mautar55** [comment]
Unable to reproduce in the 3.3 branch to date.

**Comment by requizm** [comment]
Seems like 3.X has no such problem. This commit fixes problem: https://github.com/godotengine/godot/commit/79f48642a8f6fec63f5624083f5295e85e161e83

![deselect-test](https://user-images.githubusercontent.com/12533045/129559491-512a2e15-e7b0-424f-bc10-fa01945a98cc.gif)

**Comment by akien-mga** [comment]
Thanks! I'll cherry-pick it for `3.3` too then.
