### ISSUE TITLE
Default process material in Particles sometimes generates a lot of warnings

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49339]
**Godot version:**
7085c0d80110c4c3f90fcc12f609650144e08712

**OS/device including version:**
Win10/GTX1060/466.63 driver

**Issue description:**
Creating a GPU or CPU particles will spam the following errors to the output + the particles do not work.

![image](https://user-images.githubusercontent.com/3036176/120900971-8d8d8200-c640-11eb-8110-e668c629bc9c.png)

Prints:
```
ERROR: This compute pipeline requires (48) bytes of push constant data, supplied: (64)
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7084)
ERROR: The shader in this pipeline requires a push constant to be set before drawing, but it's not present.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7162)
```

**Steps to reproduce:**
Create a Scene and put CPU/GPU-Particles to it.

**Minimal reproduction project:**
Too easy to reproduce

**Comment by Chaosus** [comment]
I will try to bisect it in the next days if the reason does not appear.

**Comment by floppyhammer** [comment]
I can't reproduce this. I'm at 94c31ba3006b071a6fe03b29a86d0a415351a50f with Windows 10, GeForce MX250, 466.63 driver.

**Comment by Chaosus** [comment]
Yeah, @reduz said that happens in certain situations. Although it does not happens several commits ago (on my PC) so it's a recent regression.

**Comment by Chaosus** [comment]
Ah, the particles are working correctly, but the shader for process material sometimes generates these warnings when set up firstly.

**Comment by Chaosus** [comment]
I doesn't detecting this bug on a2d5f191d8d91f241a09233586da0f7e9deb8a76. Closed.
