### ISSUE TITLE
Godot Freezes in Windows 10 

### ISSUE THREAD

**Issue by remorse107** [godotengine/godot#49333]
![image](https://user-images.githubusercontent.com/7462993/120891238-1bc82080-c5cd-11eb-93d0-c425bfc53362.png)

Godot v3.3.2 freezes with no information displayed what the problem might be.  Doesn't happen all the time and is resolved when I reboot my computer.  

Previous versions did not do this.

OS:
Windows 10 Pro, Build 19042

System:
AMD FX8350
16GB 
nVidia 1660 Super

This could be a problem for me locally, but I saw a few other reports of freezing, one being on Linux.  So I'm reporting to see if others are having this issue.

**Comment by remorse107** [comment]
I downloaded the 3.3.2 stable version of the source and I found that the offending line (that is causing the freeze) is related to the gamepad.  I'm working on a two player game so I have two controllers hooked up to my PC.

As soon as I unplugged one of the controllers Godot executed properly.

![image](https://user-images.githubusercontent.com/7462993/120892807-9e54de00-c5d5-11eb-986e-81acb7b83d7e.png)

**Comment by remorse107** [comment]
I have a poorly working controller.  So I'll close this issue.

This appears to be more a problem of DirectInput8Create not returning if communicating with a controller in a bad state.  Nothing that Godot developers can resolve here.

**Comment by Calinou** [comment]
> This appears to be more a problem of DirectInput8Create not returning if communicating with a controller in a bad state. Nothing that Godot developers can resolve here.

Can't we handle this more gracefully on our end (e.g. by displaying an error message)?

**Comment by remorse107** [comment]
Freezes on the winapi call to directinput.

Not sure it's possible.
