### ISSUE TITLE
Assigning enum-typed function argument to a variable triggers error (GDScript 2)

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#49357]
**Godot version:**
master branch, commit 94c31ba3

**OS/device including version:**
Linux Mint 20.1

**Issue description:**
When trying to assign an enum value to a variable from a function argument typed to that enum, an incoherent error occurs: `Cannot assign a value of type MyEnum (enum) to a target of type MyEnum (enum)`
Removing the type from the argument does not trigger an error.

**Steps to reproduce:**
Run the following script:
``` GDScript
extends Node

enum MyEnum {ONE, TWO, THREE}

var test: MyEnum = MyEnum.ONE

func myfunc(myvar: MyEnum) -> void: # no error with func myfunc(myvar) -> void:
	test = myvar
```

**Minimal reproduction project:**
None. Using the above script is enough to reproduce.

**Comment by MarianoGnu** [comment]
I have a potential fix for this issue.
https://github.com/MarianoGnu/godot/commit/6e7696f6b497499ae1cbf16fd9ee696a56d74a8b
I am trying to fix more issues related to enums before doing a PR submission
