### ISSUE TITLE
Child nodes not being recognized and returning null

### ISSUE THREAD

**Issue by OldBrownSock** [godotengine/godot#49366]
[MarsX.zip](https://github.com/godotengine/godot/files/6604746/MarsX.zip)

I am trying to create a procedural 2d world thing. All was going well. Then, in Main.gd, I got an error saying:

E 0:00:00.426   get_node: Node not found: TileMap.
  <C++ Error>   Condition "!node" is true. Returned: __null
  <C++ Source>  scene/main/node.cpp:1381 @ get_node()
  <Stack Trace> Main.gd:9 @ _ready()

My issue is that "TileMap" is definitely a node that is a child of the "Main" node, so I don't understand why I am getting this error.

My theory is that something is going wrong with the "onready var grid = $TileMap" line that is causing the engine to be unable to assign child nodes as variables.

**Comment by qarmin** [comment]
The problem is that you use this scripts as singletons(just add `print(grid)` to `_ready` to see that this is printed twice).
You need to remove them from Autoload to fix errors.
Singletons are just a script, so they cannot have children and that is what this error means.
