### ISSUE TITLE
The selection rectangle is barely visible on some tiles

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#49371]
**Godot version:**

cb82442

**Issue description:**

I have a tileset with blue tiles and the selection rectangle for alternate tiles seems to be of similar color. The result is this:
![image](https://user-images.githubusercontent.com/2223172/120940950-3b239280-c720-11eb-9b75-0a41755753a2.png)
(seems to depend on screen color settings)

I think the rectangle should be thicker, or better, bicolored.

**Comment by groud** [comment]
Ah.
Well, the idea was that it would take as selection color the opposite of the one of the grid, but thinking about it it was kind of dumb (as if you choose a color quite different from your tiles' one, you don't want to have it as a seleciton color).

I am not really sure what to do about it though, maybe it should simply choose a similar color instead, or maybe make them both configurable.

**Comment by KoBeWi** [comment]
I'd just make the selection much more prominient. Here's example from RPG Maker:
![image](https://user-images.githubusercontent.com/2223172/120990250-a43af280-c780-11eb-984a-b6ca64d7e5cd.png)

**Comment by groud** [comment]
Yeah, I thought about that. But if I am not mistaking, it's hard in Godot to draw several rect inside of each other (to make the black/white/black pattern), the precision issues could lead to gaps between the lines.

Though maybe I could draw a 9-patch rect for that though, I'm not sure. It's something to try I guess.
