### ISSUE TITLE
Add OS.is_exported()

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4937]
When exporting a game, resources get converted to binary formats. So .tscn becomes .scn, .tres becomes .res etc.
It causes trouble in my game because I use file names in parameters, and in order to load them I need to append the right extension to them. 
A current workaround would be to use OS.is_debug_build() but it doesn't exactly fulfills the required feature.
If there is not already a function for this, could `OS.is_exported()` be added to know if a game is exported or is ran from the editor? Or make it so load("test.tscn") also works if only .scn is found?

**Comment by Calinou** [comment]
> .tres becomes .res etc.

I've just tested a simple project with `.tres` files (and with references to them in the code) and it works fine when exported. I think that only `.tscn` is converted to `.scn` on export?

**Comment by Zylann** [comment]
I only tested with .tscn and they get converted to .scn, so I assumed it was the same for all text-based formats. That's a bit inconsistent :p

**Comment by punto-** [comment]
Do these files fail to load on your exported game? That should be a bug,
files that change names during export get added to a remap database, the
file access layer takes care of that

**Comment by Zylann** [comment]
Oh. That's fine then :)
But there is another problem, when I get all files inside my levels folder, I filter them so I only get scenes. If I use ".tscn", I get no results in the exported game, forcing me to test both ".tscn" and ".scn". The remap doesn't works when using the Directory class.

**Comment by akien-mga** [comment]
Maybe the remappings should be exposed to the Directory API?

**Comment by vnen** [comment]
BTW, you can already access the remap's data directly: http://docs.godotengine.org/en/latest/classes/class_pathremap.html

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.

**Comment by luckyabsoluter** [comment]
`OS.get_executable_path()` is `Godot_v4.3-stable_win64.exe` if you run project in editor.

Exported Project: `my_game.exe`
