### ISSUE TITLE
Animation Transition node wont update until conected.

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#49375]
**Godot version:**
Godot 3.3

**OS/device including version:**
MX Linux

**Issue description:**
Updating the inputs for the Transition Node wont reflect any change until reconected

**Steps to reproduce:**
Create a Animation Tree
Add AnimationNodeBlendTree as the RootNode
Add Transition Node
Add inputs
You wont see any updates in the node until reconected to something

![AnimTree](https://user-images.githubusercontent.com/1168582/120944816-d448ae00-c70c-11eb-8d4f-6e56a676c0ee.gif)

**Minimal reproduction project:**
New project is fine

**Comment by unsignedFoo** [comment]
I think this can be fixed writing a signal, I am wrong?

**Comment by kodiwills** [comment]
Duplicate of https://github.com/godotengine/godot/issues/45437
I would like to implement the fix, or at least try to. I was working on the old issue. I proposed an idea in the chat that was basically.
add a new signal in animation_blend_tree.cpp that is emited by all property methods that update the graph visually. Then have the blend tree plugin connected to that signal and call _update_graph() when it is emited.

**Comment by kodiwills** [comment]
@unsignedFoo You would probably make a way better fix though. So if you think my solution is inadequate I would be fine with you doing it.

**Comment by kodiwills** [comment]
As for your comments, yes there is only 1 directionality from graph to properties if I understand correctly. When you update the inspector the input count does update because if you save and close the editor it will refresh the graph properly. The main disconnect is that when properties that edit the graph visually are not triggering the `_update_graph` method. As far as I can see. Although I am not quite sure why dragging the node doesnt update the input count even though it calls `_update_graph` but it does work when you undo a node drag. That might be a different bug entirely.

**Comment by unsignedFoo** [comment]
@kodiwills I managed in some way connecting a signal and emiting the signal but it works randomly. Not sure why. I would like to see your implementation.

**Comment by kodiwills** [comment]
@unsignedFoo I dont really know how to implement it properly but I fixed it in a very hacky method. Ill push my code to my remote. It works by connecting `update_graph` to the `tree_changed` signal. Every time `set_enabled_inputs` is called it emits `tree_changed` and it fixes the bug.

**Comment by kodiwills** [comment]
The actual method should probably have its own signal. Then in every property method that changes the graph just emit the signal. I am just really bad with adding signals in code right now since I am so new. I tried to add a signal myself and it broke lol.

**Comment by unsignedFoo** [comment]
This is more or less what I was thinking. Try open a PR and let's test it.
