### ISSUE TITLE
Navigation in 2D/3D viewport should "wrap around" the mouse

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4938]
Blender has an handy feature since a few versions (2.70 or so?) that makes the cursor "wrap around" when it reaches the edge of the viewport while panning (in both 2D and 3D views).

I guess this requires some OS-specific code.

**Comment by blurymind** [comment]
was this ever implemented in 2.1.4?

**Comment by Noshyaar** [comment]
Rotating in 3D using MMB already wraps mouse around.

Would be nice if interacting with spatial transform widget wraps the cursor around too.

**Comment by Calinou** [comment]
As this particular feature is now implemented, should I close this?

**Comment by Calinou** [comment]
Closing, as this was implemented a while ago.
