### ISSUE TITLE
VisibilityNotifier / Enabler (3D) deficiencies

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#49381]
**Godot version:**
3.3 (and presumably since 3.0)

**OS/device including version:**
All

**Issue description:**
While investigating `VisibilityEnabler` I discovered a number of potential problems (or perhaps mismatches with my expectations?). The `VisibilityNotifier` and `Enabler` system seems designed to switch on and off behaviour when objects or groups of objects, represented by the Notifier `AABB` (bound) move in and out of camera frustums. At the moment it seems designed to turn off animation, and put physics objects to sleep.

## Problems

- [x] Animation is only turned off when moving out of the frustum for animations driven purely by AnimationPlayer. This I have a PR to fix #49341.
- [ ] The `VisibilityNotifier` system currently works only with camera frustums, and not with shadow volumes from lights. This is problematic, because although an animated / physics object may itself be out of view, the shadow may still be in view, and stop moving suddenly in a disconcerting fashion.
- [ ] More than this, there is the potential that when entering view, due to a large change in animation time, an animation may jump to a highly different arrangement, leading to a glitch in the shadow as an object enters the view frustum. I'm not yet sure whether this glitch takes place, it depends on whether the animation is driven by absolute time, or purely by deltas. If it is just deltas, this may not be a problem.
- [ ] VisibilityNotifier takes no account of masks, either for cameras, or for lights.

**Steps to reproduce:**
Run with and without the PR #49341 with the test project below. Pressing left and right cursors to change the view direction can show you the shadow freezing as the object moves out of view (with the PR applied).

**Minimal reproduction project:**
[SkeletonCull2.zip](https://github.com/godotengine/godot/files/6606832/SkeletonCull2.zip)

#### Extra
This is mostly a mindfart of some approaches I'm considering, and to discuss with reduz. Primarily I want to get something that works fast for portals, but it would be nice if games that didn't use portals could also gain some of the benefits. I was torn whether to make this an Issue or Proposal, but as I have no firm proposal as yet, and this issue wasn't reported, I thought I'd put these together for now.

# Discussion
I'm not sure how many people are using the current `VisibilityNotifier` system but it appears the area could do with an overhaul. I'm mostly looking at this because I'm attempting to use the same functionality with the rooms & portals PR #46130, to turn on and off animation as objects move in and outside the gameplay area.

### User awareness
One concern I have is that users are likely unaware of the benefits of using `VisibilityEnabler` when using animations. In almost all cases, it would seem to make sense to use a `VisibilityEnabler` when using a `Skeleton`. I do suspect that users will expect that throttling animation is done automatically for them by the engine when objects are not in view, but this is not the case, unless they add a `VisibilityEnabler`. This has not been so visible with hardware skinning (where only the bones animation would be updated when not in view, but not the skin), but is much more of a concern with software skinning (where the skin is also unnecessarily updated).

### Separate node, or integral?
One obvious alternative would be to make the `VisibilityEnabler` part of a `MeshInstance` or `Skeleton`. However what happens if you want to drive multiple `MeshInstances` from one Enabler? Having the current manual system does seem more adaptable and efficient, if more cumbersome to use for the user. In either case, you could still have to define a manual AABB for the enabler, because animations by their nature tend to change their AABB over time, and you need to cull based on the position that 'will be', not the position that 'was', so an expanded bound is usually better.

### Inefficiencies
Sticking with the current system, it is clear that some work is being duplicated on the client side and the visual server side:
* Both sides are maintaining a list of current cameras, and frustum culling objects to the cameras

If we decide we need to take lights / shadows into account then this duplicated work increases even more, as both sides will also have to maintain lists of lights and do shadow volume culling.

This distinction occurs because of the separation, and the design that these can happen on separate threads. The animation / physics culling happens before the rendering even starts. If we wait for the rendering to start and the render frustum culling, the information we have is too late for the current frame, so there will be a frame delay in switching on and off notifiers.

### Deferred animation
Another possibility, at least for the animation, is to defer the animation processing until the rendering stage. We only update the heavy animation processing (bones, skins) on the first occurrence of an object during rendering. This could be doable, and would avoid the frame delay. This would lose any multithread benefits however (if any currently exist in 3.x) as the animation would have to be processed in the render thread. This couldn't be used for physics without a frame delay because physics needs to be updated with all objects at once.

A possible advantage of doing the off / on stage during rendering is that a lot of the processing as to which cameras / lights are active is done once, and not in the visual server AND the client.

Another possibility is a hybrid approach, where camera frustums are processed in the client, and a frame delayed version is processed for the lights on the server, then uses callbacks (which are implemented in rooms & portals) to inform the client notifiers. Although it sounds complex it is doable in a similar way to how I current process the rooms & portals.

### Light problems
Another problem with lights is, that although you typically might have 1 or 2 camera frustums to process, you may have a level with 200 lights, and you don't want to end up in a situation where you are frustum checking VisibilityEnablers against 200 lights every frame.

In addition, although an object may be in view of a light, the shadow may still not be cast into the camera frustum, thus the notifier doesn't need to be activated. This is why doing notifier / light culling in the visual server may be a better idea - the visual server already has to do code to reject lights that do not affect the view frustum. So this again favours the hybrid approach. 

### Frame delay
Perhaps the frame delay isn't so problematic, I'll have to test whether the glitches is a real or hypothetical problem. It is analogous to the problems with GPU occlusion culling, but in this case we can always draw *something* during the frame delay, it just won't be as up to date as it could be.

And the duplication may not be so bad, as the AABB proxies will only be frustum culled once, whether we do it client or server side. It is more the house keeping code that is in danger of duplication maybe (calculating frustums / light frustums etc).

**Comment by Calinou** [comment]
Note that VisibilityNotifier and VisibilityEnabler were refactored for 4.0 in https://github.com/godotengine/godot/pull/49666, fixing many of the issues described here. However, these rely on backwards-incompatible changes, so they can't be cherry-picked to `3.x`.

**Comment by lawnjelly** [comment]
Should be ok to close this as some of the major parts were resolved, and should be searchable for further work on the notifier.
