### ISSUE TITLE
Warning: Your clang-format binary is the wrong version 12.0.0

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#49380]
**Godot version:**
master 34fc33d192

**OS/device including version:**
Ubuntu 21.04

**Issue description:**
Similar to #48608, but I'm now getting the same message on Ubuntu 21.04, which includes clang-format 12.0.0:
```
Warning: Your clang-format binary is the wrong version (12.0.0, expected 11.x.x).
         Consider upgrading or downgrading clang-format as formatting may not be applied correctly.
Files in this commit comply with the clang-format rules.
```
I understand the need to control third-party code versions, but, since 12 doesn't seem to break anything, I don't think we need to suggest downgrading the version of clang-format.

**Steps to reproduce:**
On Ubuntu 21.04 copy the misc/hooks folder into your .git/hooks folder. Make a change, try to commit the change.

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
Yes we could relax the check and allow both clang-format 11.x and 12.x. 10.x would change formatting, and we don't know how 13.x will behave yet.
