### ISSUE TITLE
VisualServer.set_default_clear_color  doesn't do anything

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#4939]
i put it anywhere doesn't seem to do anything

possibly an OSX only issue

**Comment by reduz** [comment]
no longer an issue in 3.0

**Comment by icnikerazah** [comment]
i have the same problem. should I open a new issue?
On MacOs Sierra
version [99960d929](https://github.com/godotengine/godot/commits/99960d929)

**Comment by brainsick** [comment]
There's no sample and I'm not an expert.  I might be off base.  Does any of this help?

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ cat issues/4939-1.gd
extends SceneTree

func _initialize(): # MainLoop
	var viewport = get_root()
	
	var environment = Environment.new()
	environment.background_mode = Environment.BG_COLOR
	environment.background_color = Color(0, 0, 1, 1)
	
	viewport.world.environment = environment
	
	var camera = Camera.new()
	
	var mesh_instance = MeshInstance.new()
	mesh_instance.mesh = CubeMesh.new()
	mesh_instance.transform.origin.z = -5
	
	camera.add_child(mesh_instance)
	
	viewport.add_child(camera)

# main test body
func _iteration(delta): # MainLoop
	quit()
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ time ~/Downloads/Godot3.0Beta2/Godot_v3.0-beta2_x11.64 -s issues/4939-1.gd 
No touch devices found
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 Fury Series (AMD FIJI / DRM 3.18.0 / 4.13.0-21-generic, LLVM 5.0.0)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

real	0m1.135s
user	0m0.155s
sys	0m0.045s
```

![4939-1](https://user-images.githubusercontent.com/1111573/34641935-cabdd086-f2d0-11e7-849f-8d1ecd50acfd.png)

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ cat issues/4939-2.gd 
extends SceneTree

func _initialize(): # MainLoop
	var viewport = get_root()
	
	var environment = Environment.new()
	environment.background_mode = Environment.BG_COLOR_SKY
	environment.background_sky = ProceduralSky.new()
	environment.background_color = Color(1, 0, 0, 1)
	
	viewport.world.environment = environment
	
	var camera = Camera.new()
	
	var mesh_instance = MeshInstance.new()
	mesh_instance.mesh = CubeMesh.new()
	mesh_instance.transform.origin.z = -5
	
	camera.add_child(mesh_instance)
	
	viewport.add_child(camera)

# main test body
func _iteration(delta): # MainLoop
	quit()
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ time ~/Downloads/Godot3.0Beta2/Godot_v3.0-beta2_x11.64 -s issues/4939-2.gd 
No touch devices found
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 Fury Series (AMD FIJI / DRM 3.18.0 / 4.13.0-21-generic, LLVM 5.0.0)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

real	0m1.126s
user	0m0.305s
sys	0m0.039s
```

![4939-2](https://user-images.githubusercontent.com/1111573/34641941-ebd32c30-f2d0-11e7-804d-72f51cde7dbf.png)

If you're trying to do something like this, then I agree that it isn't working how I assume it would.  But I'm making a lot of assumptions here.

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ cat issues/4939-3.gd
extends SceneTree

func _init(): # Object
	VisualServer.set_default_clear_color(Color(0, 1, 0, 1)) # this

func _initialize(): # MainLoop
	var viewport = get_root()
	
	var environment = Environment.new()
	environment.background_mode = Environment.BG_CLEAR_COLOR
	
	viewport.world.environment = environment
	
	var camera = Camera.new()
	
	var mesh_instance = MeshInstance.new()
	mesh_instance.mesh = CubeMesh.new()
	mesh_instance.transform.origin.z = -5
	
	camera.add_child(mesh_instance)
	
	viewport.add_child(camera)

# main test body
func _iteration(delta): # MainLoop
	quit()
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ time ~/Downloads/Godot3.0Beta2/Godot_v3.0-beta2_x11.64 -s issues/4939-3.gd 
No touch devices found
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 Fury Series (AMD FIJI / DRM 3.18.0 / 4.13.0-21-generic, LLVM 5.0.0)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

real	0m1.130s
user	0m0.159s
sys	0m0.033s
```

![4939-3](https://user-images.githubusercontent.com/1111573/34641945-fb275bd4-f2d0-11e7-9168-6904d374841a.png)

**Comment by icnikerazah** [comment]
@brainsick Can you upload scripts as attachable to nodes?(ready to use .gd files)

**Comment by brainsick** [comment]
No can do.  GitHub doesn't allow .gd attachments.  

Best I can do:

[4939-1.gd.txt](https://github.com/godotengine/godot/files/1609084/4939-1.gd.txt)
[4939-2.gd.txt](https://github.com/godotengine/godot/files/1609085/4939-2.gd.txt)
[4939-3.gd.txt](https://github.com/godotengine/godot/files/1609086/4939-3.gd.txt)

**Comment by icnikerazah** [comment]
no your scripts are good. i will test later and i will do feedback.

**Comment by brainsick** [comment]
Since you're offering to test, I'm assuming that one of these, probably 4939-3 is similar to your issue and you would expect that example to work as well.  If so, here is an updated test that builds in a little buffer to ensure everything's initialized.  Just for good measure, I threw the `set_default_clear_color()` in there at various points in the initialization cycle.

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ cat issues/4939-3.gd
extends SceneTree

func _init(): # Object
	VisualServer.set_default_clear_color(Color(0, 1, 0, 1)) # this

func _initialize(): # MainLoop
	var viewport = get_root()
	
	VisualServer.set_default_clear_color(Color(0, 1, 0, 1)) # this
	
	var environment = Environment.new()
	environment.background_mode = Environment.BG_CLEAR_COLOR
	
	viewport.world.environment = environment
	
	var camera = Camera.new()
	
	var mesh_instance = MeshInstance.new()
	mesh_instance.mesh = CubeMesh.new()
	mesh_instance.transform.origin.z = -5
	
	camera.add_child(mesh_instance)
	
	viewport.add_child(camera)

# it takes 6 _iterations to have usable viewport texture data, add buffer
const DELAY_CYCLES = 6 * 2

var delay = DELAY_CYCLES

# main test body
func _iteration(delta): # MainLoop
	VisualServer.set_default_clear_color(Color(0, 1, 0, 1)) # this
	
	if delay > 0:
		delay -= 1
		
		return false # return true in MainLoop exits, keep going?
	
	quit()
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ time ~/Downloads/Godot3.0Beta2/Godot_v3.0-beta2_x11.64 -s issues/4939-3.gd 
No touch devices found
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 Fury Series (AMD FIJI / DRM 3.18.0 / 4.13.0-21-generic, LLVM 5.0.0)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

real	0m1.129s
user	0m0.174s
sys	0m0.030s
```

In the past, I've had the best success working with VisualServer in _init() or _initialize() as it was in my original example.

**Comment by icnikerazah** [comment]
does this script only work on the command line? I do not know how to use this script. i am on macos with app bundle i don't have godot command line.

**Comment by brainsick** [comment]
This script is designed to work from the command line, yes.  I don't know the syntax for OSX with an AppBundle, sorry.

**Comment by icnikerazah** [comment]
your script does not have any difference from regular api. this bug still exist for me.

**Comment by brainsick** [comment]
The script is not a fix.  It merely attempts to demonstrate the issue in the absence of any other examples.  If the script is accurate, it serves as a test for a developer who might try and address this reported bug.

**Comment by icnikerazah** [comment]
oh  i  understand. sorry

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by icnikerazah** [comment]
I think this problem is critical. this problem can make people crazy.

**Comment by akien-mga** [comment]
If it hasn't worked since 2016 and nobody went crazy so far, I think it can wait for 3.1 / 3.0.x.

**Comment by icnikerazah** [comment]
“I’d rather lose money than trust.”
Robert Bosch

**Comment by akien-mga** [comment]
Good that we're losing neither of those two over a 2 year old unfixed issue among 2000 fixed ones.

**Comment by icnikerazah** [comment]
ya bi siktirgit mına kodumun malı.

**Comment by akien-mga** [comment]
You know Google Translate knows Turkish, right? https://translate.google.com/#tr/en/ya%20bi%20siktirgit%20m%C4%B1na%20kodumun%20mal%C4%B1.

Anyway, go rant and insult somewhere else.

**Comment by icnikerazah** [comment]
hayatını bir sike yaramayan oyun motoru yapmaya mı adadın mına kodumun evladı. bunu da yapıştır çevir bakalım çevirebilecek mi.

**Comment by aaschmitz** [comment]
I tested with latest version compiled (Godot 3.1.dev from 01/30/2018) and this issue is present. 

For a simple test, use the "2d platformer" from godot demos, delete the node "parallax_bg" from main scene and run it: the background is grey (the default Godot editor color).

Add the code below in the player.gd:

```
func _ready():
    VisualServer.set_default_clear_color("000000")
```
Now the background should be black (in Godot 2.1.x this is true) but in latest Godot 3.1.x (or Godot 3.0.0) the background remains gray.

**Comment by trollworkout** [comment]
i tried this on windows and it appears it doesn't work

`VisualServer.set_default_clear_color("000000");`

Seems like environment clear setting overrides it? I cannot tell.

**Comment by aaschmitz** [comment]
As a workaround, add the code below in the player.gd (using the example "2d platformer" quoted above):

```
func _ready():
    # This not work in Godot 3, background remains gray
    #VisualServer.set_default_clear_color("000000")
    
    # Workaround solution for Godot 3, background changed to black
    ProjectSettings.set_setting("rendering/environment/default_clear_color", "000000")
```

**Comment by akien-mga** [comment]
Thanks, the fact that setting the project setting manually is a good hint to fix `VisualServer.set_default_clear_color`.

I'd suggest comparing what happens in both cases to find out why the latter doesn't work when the former does.

**Comment by eon-s** [comment]
Why do changes on project settings affect a running game? (This is not how it used to work)
PS clear color is resetting the visual server?

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
is this still an issue?

**Comment by girng** [comment]
@CarlGustavAlbertDwarfsteinYung  unfortunatly yea :P, tested on 3.0.2

**Comment by Alexander-Alekseev** [comment]
`set_default_clear_color` does nothing since 22d83bc9f655d5ae7a1b49709c4c1b663725daf5 (2016-10-03):
https://github.com/godotengine/godot/blob/22d83bc9f655d5ae7a1b49709c4c1b663725daf5/servers/visual/visual_server_raster.cpp#L1272-L1274

Current master:
https://github.com/godotengine/godot/blob/59710880cd21d79ae1329f04eb35ea48e646acb3/servers/visual/visual_server_raster.cpp#L160-L161

**Comment by girng** [comment]
really? Since 2016 omg lol

**Comment by Web-eWorks** [comment]
The way I see it, the solution is to make `VisualServerViewport::clear_color` public (or add a method to set it) and implement `set_default_clear_color` like so:
```
void VisualServerRaster::set_default_clear_color(const Color &p_color) {
    VSG::viewport->set_clear_color(p_color);
}
```
@reduz would this stomp all over the render system?
