### ISSUE TITLE
importing pngs loses indexing

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#494]
When importing a png file that uses indexing, or saving it as a resource, the resulting resource file loses the indexing data and the resulting file size is significantly larger.  An alternate solution is to use Godot's compression, WebP, but this produces an inferior image for certain kinds of art - namely cell shading that uses large regions of single colors.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment]
No answer, assuming that it's no longer reproducible. Please comment if you still experience this bug.
