### ISSUE TITLE
Particles2D not appearing in screen-reading shader when >1 shader in view

### ISSUE THREAD

**Issue by mangecoeur** [godotengine/godot#49400]
**Godot version:**
**OS/device including version:**
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon Pro 560 OpenGL Engine
OpenGL ES Batching: ON
MacbookPro 15inch 2017
macOS 11.3.1

**Issue description:**
I have an effect where there is a Particle2D system with an overlay (image sprite) that uses a screen reading shader to create some visual effects with the particles.

When I put two (or more) of these in a scene, only the one highest up in the scene tree is shown properly when both are in view. The next ones don't seem to be able to read the screen texture with the particles on. As you can see in the screenshot, the particle sprites appear again once they are outside the screen reading shader sprite rect.

![Screenshot 2021-06-07 at 21 09 43](https://user-images.githubusercontent.com/743508/121076806-1e966180-c7d7-11eb-8b96-b0198e8d45da.png)

Scrolling the camera so that only one of the sprites with the shader are in view causes the problem to disappear.

**Steps to reproduce:**
I attached a project to reproduce the issue. I cut down the shader and it seems it is only related to the screen reading part.

**Minimal reproduction project:**
[ParticleShaderDebug.zip](https://github.com/godotengine/godot/files/6611491/ParticleShaderDebug.zip)

**Comment by clayjohn** [comment]
Looks like you probably need to use a BackBufferCopy as explained in the [screen reading shaders doc](https://docs.godotengine.org/en/stable/tutorials/shading/screen-reading_shaders.html)

**Comment by mangecoeur** [comment]
@clayjohn aha reading that part in detail it makes more sense - i had skipped over it because it looked at first glance like it was only important when you want semi-transparent things to overlap. In fact, you need it as soon as you start building scenes out of other scenes where those scenes contain screen reading shaders, since as soon as you compose them together the first one in the hierarchy will trigger the buffer grab and the subsequent nodes won't get the data you expect. What as befuddling me was how everything worked in my component scenes but broke when I put them together. Aren't shaders great ;) 

Could be an idea to make clearer the importance of BackBufferCopy in the context of composing a scene hierarchy in the docs, since Godot encourages you to build sub-scenes and fit them together this might help other people too...

**Comment by clayjohn** [comment]
I agree. That is very helpful feedback. 

Additionally, users don't often think of objects using SCREEN_TEXTURE as transparent objects, so it isn't immediately clear that BackBufferCopy is needed. 


A note at the beginning of that section would be very helpful.
