### ISSUE TITLE
.apk can't be loaded on device when using custom build for Android 

### ISSUE THREAD

**Issue by TWolfdev** [godotengine/godot#49408]
**Godot version:**
3.3.2 (latest stable), occurring since at least 3.3(.0)

**OS/device including version:**
Tested on Windows and Apple Silicon macOS; more than one smartphone

**Issue description:**
"Could not install to device." Error.
Android custom build produces an apk but the apk can't be started on device. Same for one-click deploy.

**Steps to reproduce:**
1) Empty project with main scene set. 
2) Follow "Exporting for Android" and "Custom builds for Android" tutorials. 
3) One click deploy OR export apk and load on device. 

I double and triple checked that I set it up correctly on 2 different OSs, also doesn't work when I go down the route of making an actual plugin in Android Studio and trying to integrate it (gdap + aar). Maybe I missed something major, but at this point I'm far beyond trying to debug this any further.

**Comment by Calinou** [comment]
@TWolfdev Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by fmazan** [comment]
What output do you get when you run 'adb install exported.apk'? One reason might be that an application with the same package name already exists on your device and is signed with a different key.

**Comment by TWolfdev** [comment]
> What output do you get when you run 'adb install exported.apk'? One reason might be that an application with the same package name already exists on your device and is signed with a different key.

Yes, you're right. I literally spent weeks debugging this issue. Thank you very much, it would probably be a good idea to add this to the documentation.
