### ISSUE TITLE
Scrreen space reflections does not seem to actually take roughness into account

### ISSUE THREAD

**Issue by WattanaGaming** [godotengine/godot#49402]
**Godot version:**

3.3.2

**OS/device including version:**

NVIDIA GeForce GTX 1660, (dont know how to check driver on windows), GLES3 backend, graphics-related(minor issue)

**Issue description:**
With SS reflections enabled, Godot does not seem to actually take roughness into account because toggling the option in SS reflections does not seem to change anything. Reflections are clear even though the material have 0 metalness and 1 roughness.

Roughness on:
![image](https://user-images.githubusercontent.com/25323231/121076111-38986a00-c800-11eb-9875-f44ef1223ca1.png)

Roughness off:
![image](https://user-images.githubusercontent.com/25323231/121076134-40f0a500-c800-11eb-8d02-3c1fdce0544f.png)

Increased max steps for better visibility:
![image](https://user-images.githubusercontent.com/25323231/121077324-b1e48c80-c801-11eb-9e53-eeca63115426.png)
![image](https://user-images.githubusercontent.com/25323231/121076241-5fef3700-c800-11eb-88ec-8bfd1be6ecd4.png)

**Steps to reproduce:**
1. Enable SS reflections in the world environment you are using.
2. Create a flat plane to act as the mirrer.
2.1 Create a material for the plane and make the albedo dark. This makes it easier to see the reflections
3. Put something above it to be reflected.
4. You can see very defined reflections despite the material having roughness of 1

**Minimal reproduction project:**

I am unable to upload the .zip file of the project for some reason(see screenshot below) so I uploaded it to Google drive. Alternatively, this issue can be reproduced even on a fresh new project. https://drive.google.com/file/d/1WQf1LtvKwxayaSobqT5LEGSMJxOp7NRG/view?usp=sharing
![image](https://user-images.githubusercontent.com/25323231/121077159-7c3fa380-c801-11eb-97b7-12b425d8b9b7.png)

**Comment by Calinou** [comment]
I'm not sure if rough reflections were ever supported in the `3.x` branch. They are supported in the `master` branch's Vulkan renderer (nonwithstanding [this bug](https://github.com/godotengine/godot/issues/44539)).

**Comment by WattanaGaming** [comment]
> I'm not sure if true rough reflections were ever supported in the `3.x` branch. Instead, enabling roughness will just make SSR fade faster depending on the material's roughness.

Why is that though?

By the way, I googled about rough reflections and found another issue that seem to be the same as this one(#25112) but it's for a beta of 3.1 and at least a year old. Do I close this one or keep it open?

**Comment by Calinou** [comment]
> Why is that though?

The renderer in Godot 3.x is more limited than the one in the `master` branch. It's based on OpenGL ES 3.0 (which itself is more limited than Vulkan).
