### ISSUE TITLE
Theme items manager doesn't tell what to do

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#49407]
**Godot version:**

4.0 d92e462

**Issue description:**

So I just opened theme items manager in 4.0 and it took me a few seconds to get what I should do next. Now imagine a users opens it for a first time. They get completely lost.
![image](https://user-images.githubusercontent.com/2223172/121098269-c6bb2300-c7f5-11eb-9066-447b2f9cba2e.png)
Upon opening manager you are presented with an empty window with some unclickable buttons, a mysterious "Add Type" box and a second tab which is not immediately apparent that you should use it.

Maybe if the item list is empty, we could add a label like this:
![image](https://user-images.githubusercontent.com/2223172/121098449-29142380-c7f6-11eb-9519-b1d5a09ca461.png)
Just to give someone chance to figure this out on their own.

**Comment by pycbouh** [comment]
Yes, good idea. Though after the new theme editor is merged the flow shouldn't start with this window as it does now. So maybe it won't be as big of a problem. But that's a good improvement idea anyway.
