### ISSUE TITLE
Adding several dozens of software skinning mesh causes unexpected large amount of _physics_process call

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#49416]
**Godot version:**

3.4.beta f80b15bebc

**OS/device including version:**

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-18-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 570 Series

**Issue description:**

Adding several dozens of software skinning mesh causes unexpected large amount of `_physics_process` call in the same frame.
so, it causes massive frame drop.
it seems fine until adding 60~70 meshes.
but after that `_physics_progess` is called multiple by 2, 3, 4...
| Number of instance | _physics_proccess called | multiplied |
|--------------------|--------------------------|------------|
| 50                 | 50                       | 1          |
| 100                | 200                      | 2          |
| 200                | 600                      | 3          |
| 250                | 1000                     | 4          |

it happens with both Bullet and Godot physics.
it works fine with hardware skinning.

**Steps to reproduce:**

https://user-images.githubusercontent.com/8281454/121154823-3bd43a00-c882-11eb-86e5-f7ac65bd4151.mp4

Download the attached project and run it.

in detail, `Force software skinning` needs to be set `On` at Project settings.

**Minimal reproduction project:**

[software_skinning.zip](https://github.com/godotengine/godot/files/6614932/software_skinning.zip)

**Comment by volzhs** [comment]
cc @pouleyKetchoupp @lawnjelly

**Comment by lawnjelly** [comment]
This is expected I think.

As your frame rate decreases, you will get more physics tick run per frame, as the physics are run at a fixed tick rate. If you change your physics tick rate to 120 for example, on a 60hz monitor your initial _physics_process with be 20 for 10 meshes instead of 10.

**Comment by volzhs** [comment]
@lawnjelly Thanks for the detail explanation.
I can see the same happening with hardware skinning when Idle time went over 18ms by adding 800~900 instances.
I need to figure out a way not to increase idle time then. :smile: :+1:
