### ISSUE TITLE
Mesh imported with Static Lightmaps is missing polygons & vertices

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#49414]
**Godot version:**
4.0.dev d92e462

not present on 3.x

**OS/device including version:**
Windows 10 2004

**Issue description:**
Some meshes are getting decimated in an unusual way when lightmap generation is requested. You can see here that the bevels are missing in the right mesh (imported with Static Lightmap) but not in the left mesh (Static)
![picture showing left mesh has a bevel while right mesh has a gap](https://user-images.githubusercontent.com/39946030/121125091-d1b48a00-c7da-11eb-9e11-ed8c4551aa06.png)
Saving the meshes as .tres will show that the lightmap version has fewer vertices and indices:
![picture showing a smaller vertex and index count in the "with lightmap" mesh](https://user-images.githubusercontent.com/39946030/121125383-556e7680-c7db-11eb-8fb1-c5cf923e26f8.png)

To rule out a problem with LODs or Shadow Meshes, I have disabled those in import settings. The problem still persists, so it must be caused by lightmaps.

Here is the .glb file I'm importing: [BrickTest.zip](https://github.com/godotengine/godot/files/6613507/BrickTest.zip)

**Steps to reproduce:**
In the attached project, just open Node3D.tscn. The lightmapped version of the example mesh will be missing polygons.
In a new project:
1. Open BrickTest.glb in a project
2. Check that it looks as expected
3. Change "Light Baking" to "Static Lightmap" in the import settings.
4. Reimport.
5. The mesh will be missing polygons. If Create Shadow Meshes is on, the missing polygons will be filled in with black (shadow mesh).

**Minimal reproduction project:**
Godot 4.x: [LightmapLosesPolygons.zip](https://github.com/godotengine/godot/files/6613509/LightmapLosesPolygons.zip)
Control: same project for Godot 3.x - bug does not happen: [LightmapLosesPolygons3.zip](https://github.com/godotengine/godot/files/6613510/LightmapLosesPolygons3.zip)

**Comment by fire** [comment]
I created https://github.com/fire/godot/tree/lightmap-gaps but waiting for jfons to investigate too.
