### ISSUE TITLE
Setting Physics FPS above 1000 causes everything to slow down

### ISSUE THREAD

**Issue by SmartySmart702** [godotengine/godot#49426]
### Godot version

3.3.2 Stable

### System information

Win 10

### Issue description

Changing Physics FPS to something really high like 1000+ changes the speed of the physics or the gravity.
Objects are falling slower and the weight of objects if different.
But this also affects stuff like AnimationPlayers and Timers.

### Steps to reproduce

Create a simple project where Rigid Bodies are falling.
I only changed the default gravity (*5) in the Project Settings and the Physics FPS.

Oh and make sure that the Physics FPS is really changed. Sometimes it does not take the change but you can see it based 
on the quality of the sim. If objects are moving inside each other the physics is no that high.
One safe way to make sure the Physics FPS is changed is to restart the editor.

### Minimal reproduction project

[Test_Physics_FPS.zip](https://github.com/godotengine/godot/files/6617932/Test_Physics_FPS.zip)

**Comment by Calinou** [comment]
Physics Fps should not be set to very high values (> 200) because no CPU will be able to keep up.
