### ISSUE TITLE
Sprites, shapes, etc aren't where they are supposed to

### ISSUE THREAD

**Issue by JeipiDeveloper** [godotengine/godot#49427]
### Godot version

Every version since 3.2

### System information

Windows 7, GLES3

### Issue description

![vamonessa](https://user-images.githubusercontent.com/39769986/121217486-45e14300-c858-11eb-9bbe-afd721694bc6.PNG)
The image isn't where it was supposed to be

### Steps to reproduce

Create any visible node

**Comment by Calinou** [comment]
@JPedrex Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
