### ISSUE TITLE
Reusing script loaded textures for control and spatial makes the control darker

### ISSUE THREAD

**Issue by gkazan** [godotengine/godot#49434]
### Godot version

3.3.1.stable.mono

### System information

Manjaro, GLES3

### Issue description

Loading an image resource with code like
`var res = load("res://tnt.png")`

and applying that texture to a sprite and control with
`$Sprite3D.texture = res
$NinePatchRect.texture = res`

makes the texture render darker on the control compared to how it should look.

With both the sprite and control on screen
![screenshot_06 08 14:06:31](https://user-images.githubusercontent.com/19178322/121236553-17696500-c864-11eb-948a-b8c2c1871778.png)

With only the control
![screenshot_06 08 14:06:20](https://user-images.githubusercontent.com/19178322/121236591-2223fa00-c864-11eb-94ba-b2fbcfb56d3e.png)

When switching to GLES2 instead of GLES3 the issue was not present.
The texture was imported with the preset 2D pixel.

### Steps to reproduce

Below is the script used in the minimal reproduction project. I first encountered this issue with code written in C#.
To reproduce, load a texture and apply it to both a sprite 3d and control node (such as nine patch rect)

`extends Spatial

func _ready():
	var res = load("res://tnt.png")
	$Sprite3D.texture = res
	$NinePatchRect.texture = res
`

### Minimal reproduction project

[GodotBug.zip](https://github.com/godotengine/godot/files/6618755/GodotBug.zip)

**Comment by Calinou** [comment]
This is because of an engine limitation related to textures being sRGB-converted on import. This is resolved in the `master` branch thanks to Vulkan bindless textures, but this can't be backported to the `3.x` branch since bindless textures are not available in GLES3 and GLES2.


As a workaround, duplicate the texture resource (e.g. have two files with different names on disk).

**Comment by gkazan** [comment]
Apologies for missing the duplicate. Thank you for the info and workaround.
