### ISSUE TITLE
C#8 Runtime classes not found

### ISSUE THREAD

**Issue by pietrodito** [godotengine/godot#49439]
### Godot version

3.3.2 mono x64

### System information

Ubuntu 21.04, GLSE3

### Issue description

I am trying to use the class System.Range defined in C# 8. When I try to do that I have build errors. Suprisingly, the same kind of code works wth mono 6.12 out of Godot.

### Steps to reproduce

Create a `Main.tscn` with only one `Node2D`. Attach a `main.cs` script with that code:

```
using Godot;
using System;

public class Main : Node2D
{
   public static void _Ready()
   {
       System.Range range;
   }
}
```

The build error claims: `The type or namespace 'Range' does not exist in the namespace 'System' (are you missing assembly references`

But what I cannot understand is that out of Godot with the same version of mono I can build and run the following code:
```
// hello.cs

using System;

public class HelloWorld
{
        public static void Main(string[] args)
        {
                    System.Range range = 1..4;
                    Console.Write(range);
        }

}
```
Which works like a charm...

### Minimal reproduction project

[CSharpv8.zip](https://github.com/godotengine/godot/files/6618916/CSharpv8.zip)

**Comment by 31** [comment]
Your csproj looks like this:

```xml
<Project Sdk="Godot.NET.Sdk/3.3.0">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
</Project>
```

The problem is that `net472` doesn't have `System.Range`. (At least, that's what the compile error tells me.)

In your Mono-only experiment, what was the `TargetFramework` in the csproj?

Changing to `<TargetFramework>netstandard2.1</TargetFramework>` in the Godot csproj lets `System.Range` work, for me.

**Comment by pietrodito** [comment]
You are my hero. I was trying to use `.net5.0` but of course it did not work. I was not aware of `netstandard2.1`

**Comment by kleonc** [comment]
> Changing to `<TargetFramework>netstandard2.1</TargetFramework>` in the Godot csproj

For the reference, question to @neikeq: is it fine/safe to do such change or does it have any consequences?

**Comment by 31** [comment]
`netstandard2.0` and `netstandard2.1` can cause problems with some NuGet packages, and it's labeled as a high-priority bug in the Godot tracker: https://github.com/godotengine/godot/issues/42271.
