### ISSUE TITLE
Tabs Control Node: Hidden Tabs are selectable/dragable

### ISSUE THREAD

**Issue by Blue-Byrd** [godotengine/godot#49440]
### Godot version

3.3.stable.official

### System information

Windows 10

### Issue description

You can interact with hidden tab, which leads to unexpected behaviour.
It should not be allowed to interact with hidden tabs.

### Steps to reproduce

1. Add tabs to a Tabs Node until there is not enough space for all tabs
2. Click the offset button until at least one tab on the right side is hidden
3. Click between the last visible tab and the offset buttons

![GIF 08 06 2021 22-18-24](https://user-images.githubusercontent.com/85585292/121253167-14dd2e80-c8a9-11eb-8aa8-455bdfabefe3.gif)

**Comment by Mautar55** [comment]
Can´t reproduce in 3.3, any extra clues?

**Comment by Blue-Byrd** [comment]
Here is an example project for reproduction:
[Tabs.zip](https://github.com/godotengine/godot/files/6786256/Tabs.zip)

If you click in the space between the last visible Tab and the left arrow button, then the hidden tab underneath is clicked (see output).
You can also drag the tab from there.
