### ISSUE TITLE
`TileMap::set_cell` does not perform transformation in non-square modes

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49452]
### Godot version

4.0 dev (090e4c4abdd406a7ed7fc33d0a4670bba69a4c0a)

### System information

Windows 10

### Issue description

A similar code in 3.2 brings a different result in 4.0:

<details>
<summary>Godot 3.2</summary>

```
func create_selection(from : Vector2, to : Vector2):
	  var begin_x = int(min(from.x, to.x))
	  var end_x = int(max(from.x, to.x))
	  
	  var begin_y = int(min(from.y, to.y))
	  var end_y = int(max(from.y, to.y))
	  
	  for x in range(begin_x, end_x+1, 1):
	  	for y in range(begin_y, end_y+1, 1):
	  		tilemap.set_cell(x, y, 0)
```
Result:
![tilemap_test3 2](https://user-images.githubusercontent.com/3036176/121303457-c610b280-c903-11eb-82a6-ca1f20738b01.gif)

</details>

<details>
<summary>Godot 4.0</summary>

```
func create_selection(from : Vector2i, to : Vector2i):
	  var begin_x = mini(from.x, to.x)
	  var end_x = maxi(from.x, to.x)
	  
	  var begin_y = mini(from.y, to.y)
	  var end_y = maxi(from.y, to.y)
	  
	  for x in range(begin_x, end_x+1):
	  	for y in range(begin_y, end_y+1):
	  		tilemap.set_cell(Vector2i(x, y), 0, Vector2i(0, 0), 0)
```
Result:
![tilemap_test4 0](https://user-images.githubusercontent.com/3036176/121304322-dd9c6b00-c904-11eb-9aa9-547a2cc806a5.gif)

</details>

### Steps to reproduce

Simply run provided projects and compare.

### Minimal reproduction project

[TileMap3.2.zip](https://github.com/godotengine/godot/files/6621545/TileMap3.2.zip)
[TileMap4.0.zip](https://github.com/godotengine/godot/files/6621550/TileMap4.0.zip)

**Comment by Chaosus** [comment]
Ah, seems I need to activate *Diamond Down* TileLayout. Sorry, false alarm.

**Comment by groud** [comment]
Yep, the TileLayout property modifies how tiles are indexed in the TileMap. So well, this behavior is intended :)
