### ISSUE TITLE
drag/drop meshes into viewport 

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#4945]
The new drag/drop features are brilliant! Would be great if you could also drag/drop a .msh file from the filesystem into the 3d viewport or the scene tree(where it would automatically create a new meshinstance node). Would make populating a 3d world much quicker then having to manually make new mesh instances each time.

**Comment by reduz** [comment]
This could be done for meshes, scenes, etc. But what would the logic be for the "depth" of where this is placed? If dragged over another mesh I can imagine that the collision point can be taken into account, but what if this is done over nothing?

**Comment by zendorf** [comment]
Good question! I would tend to do this in a top down orthographic view to quickly populate a scene. Was envisaging dragging from the browser to the top down viewport and having the mesh be placed where the cursor is in xz space and 0 on the y axis. Not sure how this could work with a non-orthographic view though?

 I like your idea of the collision point being taken into account...similar to how primitives are added in 3dsmax. Another idea is to a use a null or other pointer object to be used for the new co-ordinates similar to how the 3d cursor is used in Blender. This 3d pointer object could be defined and moved around as needed.

Even if the new co-ordinates for each new instance were just to default to the origin(0,0,0) then it would still be a useful addition. Drag from the browser to the viewport origin and then move from there. This is still quicker than creating a mesh instance node manually each time for every new object.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Just to be sure, this still needs to be implemented in 3.0+?

**Comment by fracteed** [comment]
@akien-mga this issue can now be closed due to d3cb8d1

**Comment by djrm** [comment]
@fracteed you can close it.

**Comment by fracteed** [comment]
@djrm ...I am not sure how to do this?

**Comment by HummusSamurai** [comment]
I think it's next to the Comment button? :b

**Comment by volzhs** [comment]
close it now.

**Comment by fracteed** [comment]
@HummusSamurai ...hehe, now I see it...doh :)
