### ISSUE TITLE
Directory name appears as / in recent directory list of EditorFileDialog

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#49453]
### Godot version

3.3.2.stable 3.x(f3d931410) master(090e4c4abd)

### System information

macOS 11.4

### Issue description

When setting the editor font, I manually typed the directory path `/path/to/font/dir/` in the Open File dialog (ending with a slash). The directory appears as `/` in the recent directory list the next time I open the dialog.

### Steps to reproduce

When picking the main editor font:
1. Make sure you are not in the target directory
2. Manually type the directory path, end it with a slash, and hit enter. The dialog will bring you to the directory as usual
3. Pick a font, click OK
4. Open the dialog again, and check the recent directory list

**Comment by pfertyk** [comment]
I'd like to submit a fix. I just implemented a similar logic that is used when processing favorites: removing the trailing slash before extracting the name of the folder.
