### ISSUE TITLE
Godot Mono failed to launch on Manjaro Linux

### ISSUE THREAD

**Issue by SysError99** [godotengine/godot#49461]
### Godot version

3.3.2

### System information

Manjaro Linux 5.10.36-2-MANJARO (Prime-Run)

### Issue description

Godot failed to launch on Manjaro Linux

# Terminal Log:
Godot Engine v3.3.2.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce 920M/PCIe/SSE2
OpenGL ES Batching: ON
 
Mono: Log file is: '/home/nate/.local/share/godot/mono/mono_logs/2021-06-09_21.16.34_60430.log'
ERROR: _load_api_assemblies: Failed to load one of the prebuilt API assemblies.
   At: modules/mono/mono_gd/gd_mono.cpp:930.

=================================================================
        Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0xef115b - ./Godot_v3.3.2-stable_mono_x11.64 : 
        0xef14e9 - ./Godot_v3.3.2-stable_mono_x11.64 : 
        0xee41af - ./Godot_v3.3.2-stable_mono_x11.64 : 
        0xefe200 - ./Godot_v3.3.2-stable_mono_x11.64 : 
        0x7fc0e2475960 - /usr/lib/libpthread.so.0 : 
        0x39b7739 - ./Godot_v3.3.2-stable_mono_x11.64 : _ZN6GDMono20_load_api_assembliesEv
        0x39b793f - ./Godot_v3.3.2-stable_mono_x11.64 : _ZN6GDMono26initialize_load_assembliesEv
        0x36a7236 - ./Godot_v3.3.2-stable_mono_x11.64 : _ZN14CSharpLanguage4initEv
        0x14eea0f - ./Godot_v3.3.2-stable_mono_x11.64 : _ZN12ScriptServer14init_languagesEv
        0x3b819c1 - ./Godot_v3.3.2-stable_mono_x11.64 : _ZN4Main6setup2Em
        0x3b8650b - ./Godot_v3.3.2-stable_mono_x11.64 : _ZN4Main5setupEPKciPPcb
        0xe19909 - ./Godot_v3.3.2-stable_mono_x11.64 : main
        0x7fc0e2165b25 - /usr/lib/libc.so.6 : __libc_start_main
        0xe19c3e - ./Godot_v3.3.2-stable_mono_x11.64 : 

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x140465881462336x from 0x140466399944384x
Entering thread summarizer pause from 0x140466399944384x
Finished thread summarizer pause from 0x140466399944384x.
Failed to create breadcrumb file (null)/crash_hash_0x0

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

=================================================================
        Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x39b7739):0x39b7729  a3 ca 0c 01 48 8d 3d 03 f9 0c 01 e8 97 a1 ba fd  ....H.=.........
0x39b7739  0f 0b 0f 1f 44 00 00 45 31 c9 4c 8d 05 16 d7 0c  ....D..E1.L.....
0x39b7749  01 48 8d 0d 4f d9 0c 01 ba a6 03 00 00 48 8d 35  .H..O........H.5
0x39b7759  73 ca 0c 01 48 8d 3d d3 f8 0c 01 e8 67 a1 ba fd  s...H.=.....g...

=================================================================
        Managed Stacktrace:
=================================================================
=================================================================
/usr/bin/prime-run: line 2: 60430 Aborted                 (core dumped)

# 2021-06-09_21.16.34_60430.log: 
Config attempting to parse: '/etc/mono/config'. (in domain Mono, info)
Config attempting to parse: '/home/nate/.mono/config'. (in domain Mono, info)
Image addref mscorlib[0xbf8c190] (asmctx DEFAULT) -> /usr/lib/mono/4.5/mscorlib.dll[0xbf8ad20]: 2 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (/usr/lib/mono/4.5/mscorlib.dll) (in domain Mono, info)
AOT: module /usr/lib/mono/4.5/mscorlib.dll.so is unusable: compiled against runtime version '6.12.0 (makepkg/a22ed3f094e Tue Dec 22 06:01:50 PM -03 2020)' while this runtime has version '6.12.0 ((no/c621c35)'. (in domain Mono, info)
Assembly mscorlib[0xbf8c190] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)

### Steps to reproduce

1. Launch Godot as normal.
2. Godot appears working but then unexpectedly closed.
3. When launching on termial, it showst messages as above.

**Comment by akien-mga** [comment]
Did you move the executable out of the folder which contains the `GodotSharp` directory?

**Comment by SysError99** [comment]
@akien-mga I found the problem, it seems like my extracting software does not include some of the files out of the bundle. So there will be some of files missing on the `OodotSharp` directory, thus causing the issue. So make sure the `GodotSharp` has been extracted properly will fix this issue. 

Closing this issue now.
