### ISSUE TITLE
dtls_verify = false no longer works with VPS. mbeDTLS error  -0x6800

### ISSUE THREAD

**Issue by RichardBetson** [godotengine/godot#49489]
### Godot version

v3.3 Stable

### System information

Linux Mint 20.1, GLES2

### Issue description

Hi, 
my VPS host upgraded their back-end and my current implementation (for testing) of Enet+RPC+DTLS  fails to work on my host's VPS. I am using the method seen [here](https://godotengine.org/article/enet-dtls-encryption).  It all works great locally even when using the Godot Linux server.  But when my application is running on the VPS server the DTLS server seems not to allow a connection anymore with no errors in the putty console at first, but eventually I get a `mbeDTLS error  -0x6800`.  I can't find a search match to that error so not sure what it means.

I have been using `dtls_verify = false` to basically get DTLS working (with host VPS) to test with which seem to work great with WireShark showing DTLS packets. I suspect that maybe, this is no longer allowed and may be denied as a result of the VPS host's upgrade; but I am not sure. 

Disabling DTLS gets my Godot application working again.

Everything was working great then the VPS host upgraded and poof, DTLS no longer would work. I'm hoping others can replicate this.

### Steps to reproduce

Test a DTLS ready Godot application with `dtls_verify = false` locally and on a hosted VPS.

**Comment by Chaosus** [comment]
cc @Faless

**Comment by Calinou** [comment]
It's very strange to see this happen, because Godot uses its own copy of mbedTLS and SSL certificates are bundled with the editor and export templates.

**Comment by RichardBetson** [comment]
FYI: I rebuilt the OS ( VPS ) just to make sure that was not an issue. The certificate and key are good and work locally. I will give this another try tonight as I am seeing some some unscheduled maintenance  and degraded service warnings from the host currently (was none earlier).. so.. odd this pops up right after scheduled maintenance (I said upgrade). On going.

**Comment by RichardBetson** [comment]
OK.. I tried it again and no joy. Same issue as above. I have included a screen shot my putty session. Here my game server is running and when the client tries to login as described above with DTLS enabled I get the ' mbedtls error: returned -0x6800, error. The application console output is 'off'.  Scratching my head here cause this is literally a case of left it working, crashed to get Zzzz'z and then no working when I returned and restarted game server
![hosting24-3](https://user-images.githubusercontent.com/656713/121618639-bf318f00-ca2c-11eb-9281-0193e1bd217d.jpg)
.

**Comment by RichardBetson** [comment]
This what I get, if I  have the game server application running with DTLS enabled and disabled ( use_dtls = false ) in the client.

![hosting24-4](https://user-images.githubusercontent.com/656713/121619735-a924ce00-ca2e-11eb-9427-d01c18320efa.jpg)

**Comment by RichardBetson** [comment]
Hi,
I had my host look into this and they sent a screenshot of three errors that might makes sense to others here. I guess a handshaking issue? They also offered this link to help explain the issue. Looking into it now , but I thought I would pass it on.

![image](https://user-images.githubusercontent.com/656713/121636136-0f204e00-ca4d-11eb-8f7f-71bac4c74803.jpg)

**Comment by Faless** [comment]
> `mbeDTLS error -0x6800`. I can't find a search match to that error so not sure what it means.

https://tls.mbed.org/api/ssl_8h.html#a2fdb240812860402a1a946eae8264148

> Everything was working great then the VPS host upgraded and poof, DTLS no longer would work. I'm hoping others can replicate this.

I don't see how this can be a Godot issue honestly and with no minimal reproduction project to test there isn't much we can do to help.

**Comment by RichardBetson** [comment]
I can put something together to test this. A small  test project (adapt a demo). 

Just knowing what the error is is a good start (thanks). Let me contact the host and mention that I am timing out and see if it rings a bell. 

I've gone over my own code and see no issues and this all runs locally (even on Linux server). My assessment so far is that there is an issue with the host whether that is by back-end misconfiguration or a  patch/upgrade issue. If it's the later other should be effected.

give me a couple days to put something together. ;)

**Comment by RichardBetson** [comment]
Hi,
I reinstalled the OS on my VPS (Ubuntu 18.04 64bit) and ran my game server and had a little different result in putty.
`ERROR: _do_handshake: TLS handshake error: -26624
AT: modules/mbedtls/pack_peer_mbe_dtls.cpp:101.
mbedtls error: returned -0x6800`

Just including it in case it meaningful.  I guess you can close this out till I can figure it out. Thanks for your time on this.

![hosting24-6](https://user-images.githubusercontent.com/656713/121759177-147fa600-caea-11eb-8fcf-cb3f1be73689.jpg)

**Comment by RichardBetson** [comment]
So on my freshly installed image of Ubuntu 18.04 it appears openssl is work. for example:
command line: `openssl s_client -connect www.google:443 -tls1_3`

![hosting24-7](https://user-images.githubusercontent.com/656713/121787775-c3c18900-cb8d-11eb-9859-2edf660fdc5a.jpg).

Again my application works locally with DTLS functioning fine.  Openssl looks to work on the VPS server.  Yet my server application will not handshake when running on the VPS server.  Remove DTLS from my application and my server (running on VPS) and game client work with no issues.

Just at a loss here as to what would cause this.

**Comment by RichardBetson** [comment]
About the only thing left I can think to try is changing my applications port and see if that resolves things. Aside from that it's try another host or hope to stumble across the issue. 

@Faless - Unless you have any idea on what to do or how to diagnose this or have your opinion as to the issue involved I guess you (or me, them) can close this out. I'm currently lifting an MMO off-the-ground (first alpha) and it will be a week or two before I have time address this issue. Fully. I will though as I need the encryption.

**Comment by RichardBetson** [comment]
Outcome: This issue was most likely the result of a third party attack on the server. Monitoring revealed possible port attacks causing delays and handshaking issues. For example one out of twenty time you could get Godot to DTLS handshake. It has now ended and everything is working fine.

If you have a similar issue as above check to see if your server (VPS) is under attack as that may be causing handshaking issues with DTLS.
