### ISSUE TITLE
Visual Script - Godot 4 - Callable Variable Issue

### ISSUE THREAD

**Issue by Anaxan** [godotengine/godot#49492]
### Godot version

v4.0.dev.calinou [090e4c4ab]

### System information

Ubuntu 20.10/Atermiter dual Xeon motherboard, gtx 970 nvidia package 460

### Issue description

I'm attempting to learn about the new callable system. I was expecting to see input boxes in the variable edit box but don't see them. The field (not sure if that is the right word ) within the set variable node opens empty as well.  

To be honest I really hope the problem is on my end and that it is a simple lack of knowledge and understanding. If that is the case all that's needed is to add an example to the docs.  
![call_var_issues](https://user-images.githubusercontent.com/81984273/121564259-40ffc900-c9e9-11eb-93c1-c287f3431968.gif)

### Steps to reproduce

Add a variable, set it to callable, notice there are no boxes in which to input values.

**Comment by Anaxan** [comment]
A small update for anyone who wants to explore this. There is a constructor that will let you get info into the variable.

**Comment by KoBeWi** [comment]
Godot 4 issues on VisualScript are no longer relevant, closing.
