### ISSUE TITLE
Editor scrolls to the right when caret moves to the end of line after deleting another line

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#49507]
### Godot version

3.3

### System information

W10

### Issue description

When deleting empty line, the caret jumps to the end of next line and editor scrolls all to the right:
![DrzEOO9fd9](https://user-images.githubusercontent.com/2223172/121677166-d10b4480-cab5-11eb-873d-008cdf5b9c2a.gif)

### Steps to reproduce

1. Paste this code
```
func collision_avoidance() -> Vector2:
	var avoidance_force: Vector2
	var left = physics.raycast(left_collision_start.global_position, left_collision_end.global_position)
	if not left:
		left = get_world_2d().direct_space_state.intersect_ray(left_collision_start.global_position, left_collision_end.global_position, [self], Const.ENEMY_COLLISION_LAYER, false, true)
		
		if left.collider is BaseBuilding:
			print("kill")
```
2. Click at the blank line in the middle
3. Delete the line (e.g. by pressing Ctrl+X)

**Comment by jmb462** [comment]
![ctrlX](https://user-images.githubusercontent.com/3649998/135705174-4e6d742f-f1d4-4ed4-a2ab-0d981142c9ac.gif)

I can reproduce it even on 4.0 using CTRL+X (only)
