### ISSUE TITLE
Adding "Redraw this node" button to scene panel or scene toolbox

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot#4951]
**Operating system or device - Godot version:**
Using : Godot_v2.0.3_stable_x11.64 on linuxmint 17.3

**Issue description** (what happened, and what was expected):
After changing position or size of a child node in a container like VBoxContainer, HBoxContainer it needs to switch to another scene tab or play the edited scene to see the results of automatic arranging of child nodes. 

A "Redraw this node" button in scene panel or scene toolbox will be usefull when building complex menu panels.

**Comment by aaronfranke** [comment]
> After changing position or size of a child node in a container

It will no longer be possible to do this in Godot 3.1 (because that's not how Containers are intended to be used). https://github.com/godotengine/godot/pull/23059 will close this issue when merged.

**Comment by aaronfranke** [comment]
> After changing position or size of a child node in a container

It will no longer be possible to do this in Godot 3.1 (because that's not how Containers are intended to be used). https://github.com/godotengine/godot/pull/23059 will close this issue when merged.

**Comment by aaronfranke** [comment]
> After changing position or size of a child node in a container

It will no longer be possible to do this in Godot 3.1 (because that's not how Containers are intended to be used). https://github.com/godotengine/godot/pull/23059 will close this issue when merged.

**Comment by akien-mga** [comment]
Indeed, this is solved in the *master* branch as container children can no longer be moved/resized.

**Comment by akien-mga** [comment]
Indeed, this is solved in the *master* branch as container children can no longer be moved/resized.
