### ISSUE TITLE
Indenting is different on OSX and Windows

### ISSUE THREAD

**Issue by Tekuzo** [godotengine/godot#49536]
### Godot version

3.3.2 Stable

### System information

Big Sur 11.2.3 MacBook Air (M1, 2020)

### Issue description

I would like to preface this by saying that this is not a huge bug and does not need to be treated as a priority, this is just something that I personally find annoying and frustrating.

When I write my code, I like to comment by indenting at the end of the line and explaining what the line does.

On my Windows desktop, the indented lines line up just fine. When I open the GD file in another text editor on windows or OSX, the indented lines are still lined up. When I open the gd file on my Macbook Air, the indented lines are no longer lined up. 

When I correct the intending on OSX it then becomes broken on windows.

Here is a screenshot of the script file in the Godot Editor on my Mac
<img width="1552" alt="Screen Shot 2021-06-12 at 8 46 56 AM" src="https://user-images.githubusercontent.com/6944363/121776465-0453df00-cb5b-11eb-9200-cecb11104667.png">

Here is the same script file opened in Sublime Text on my Mac
<img width="1552" alt="Screen Shot 2021-06-12 at 8 47 15 AM" src="https://user-images.githubusercontent.com/6944363/121776483-1e8dbd00-cb5b-11eb-9c25-0d5ab4ec0d2d.png">

Here is the script file opened in the Godot Editor on Windows
![windows](https://user-images.githubusercontent.com/6944363/121776542-775d5580-cb5b-11eb-9141-3678b3d1da85.png)

In my Editor on both Windows and OSX I have left the tab options at the default (see attached screenshot)
<img width="892" alt="Screen Shot 2021-06-12 at 8 55 39 AM" src="https://user-images.githubusercontent.com/6944363/121776646-0bc7b800-cb5c-11eb-8189-fd6570195645.png">

I have not tested how the indenting is formatted on Linux. If there is documentation on how to fix this that I have missed I am sorry. I have googled around for 2 days and have not found anything that seems to resolve this issue.

Thank You

### Steps to reproduce

This isn't an issue with game performance or the engine (to my knowledge), this seems to just be an issue in the editor.

Steps to reproduce would be to comment at the end of a line, and open the project on another platform.

### Minimal reproduction project

I have created a project with the script file in question.
[TestProject.zip](https://github.com/godotengine/godot/files/6642203/TestProject.zip)

**Comment by bruvzg** [comment]
It's probably caused by the difference in default font hinting mode on macOS and Windows. Try setting `Editor Settings`→`Interface`→`Editor`→`Font Hinting` to the same value on both OS.

**Comment by Tekuzo** [comment]
Wow, that totally fixed it. My Laptop was on none and my windows pc was on light
<img width="1552" alt="Screen Shot 2021-06-12 at 9 30 48 AM" src="https://user-images.githubusercontent.com/6944363/121777577-e4271e80-cb60-11eb-9ba6-187049eee0c4.png">

**Comment by Calinou** [comment]
@bruvzg Is there a way to solve this font metric discrepancy in `3.x` when hinting is disabled?
