### ISSUE TITLE
AnimatedSprite node bugs out when a 2 frame animation is played backwards

### ISSUE THREAD

**Issue by Tralexium** [godotengine/godot#49537]
### Godot version

v3.3.2 stable

### System information

Windows 10, GTX1070, 461.92 driver ver, GLES3

### Issue description

When a 2 frame animation is played normally it works correctly, however when you set the backwards parameter in the play function to true the animation plays at full speed causing the animation to spaz out.

### Steps to reproduce

Add a spritesheet that consists of 2 frames into an animation node and play it backwards.

**Comment by Calinou** [comment]
@Tralexium Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Tralexium** [comment]
I've made a new barebones project to test the issue. Well I've got good news, this doesn't appear to be an ongoing issue but rather a project specific bug on my end.

Sorry for the trouble ^^
