### ISSUE TITLE
Pixel Size property of Sprite3D is displayed as integer into the Inspector

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4953]
**Operating system or device - Godot version:**
Official 2.0.3stable win64

**Issue description** (what happened, and what was expected):

The Pixel Size property of Sprite3D accept float values, but the Inspector display it as integer.

If I want to verify the actual value of this property, I'm forced to click on it.

It could be more practical if this value was displayed as float into the inspector.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
I can confirm this bug as of fbef1ff. It's really weird.

**Comment by henkz1** [comment]
Probably the same bug as https://github.com/godotengine/godot/issues/4513
And I still think it's all properties with low hint range:
PropertyInfo( Variant::REAL, "pixel_size",PROPERTY_HINT_RANGE,"0.0001,128,0.0001")
