### ISSUE TITLE
Cannot reload a project after adding a class name to a GDScript file

### ISSUE THREAD

**Issue by malhotraprateek** [godotengine/godot#49535]
*Bugsquad edit:* Regression from #49499

### Godot version

v4.0.dev.custom_build [fe7559f75]

### System information

Windows 10, Nvidia GTX 1080 Ti

### Issue description

![image](https://user-images.githubusercontent.com/10957697/121773582-726bc680-cb9a-11eb-8680-7eaa46392091.png)

The editor fails to even show the project in the project manager after specifying a class name to a script in the previous run.

The issue might to be due to the string name prefix being changed to '&' from '@' in commit id: 6710ad1.
I can replicate the issue on commit id: 6710ad1 but not the previous commit (a795a36ef).

If I remove the '_global_script_classes' and '_global_script_class_icons' properties from project.godot, the project can be loaded, but then it cannot be run with F5 as the runtime throws the same 'Unexpected character' error as in the image above.
This is because the engine updated the project file before running the game.

### Steps to reproduce

1. Load the minimal project attached
2. Open problem_script.gd and uncomment 'class_name PROBLEM_CLASS_NAME'
3. Save and close the project
4. Try to start the godot editor again and observe the error in the console window

### Minimal reproduction project

[ClassNameIssue.zip](https://github.com/godotengine/godot/files/6642042/ClassNameIssue.zip)

**Comment by Calinou** [comment]
This was confirmed by @aaronfranke.
