### ISSUE TITLE
ERR_CANT_OPEN on a CSV file

### ISSUE THREAD

**Issue by romanra1** [godotengine/godot#49560]
### Godot version

3.3.2.stable.mono

### System information

Debian 10

### Issue description

Opening the translation CSV file in the editor fails with the following error message:
> Failed loading resource: res://Translations/Strings.csv. Make sure resources have been imported by opening the project in the editor at least once.
> editor/editornode.cpp:947 - Condition "!res.isvalid()" is true. Returned: ERRCANTOPEN

Interestingly enough, Godot is able to read the file and even creates the corresponding .translation files (which DO contain translations).
The CSV was created with LibreOffice Calc and has UTF-8 encoding.

The file for reference:
```
key,en,ru
MainMenu_NewGame,New Game,Новая игра
MainMenu_Continue,Continue,Продолжить
MainMenu_Options,Options,Настройки
MainMenu_Quit,Quit,Выход
```

### Steps to reproduce

1. Create a new project
2. Drag and drop a CSV file into the project's resources
3. Double click it to open

### Minimal reproduction project

[testpr.zip](https://github.com/godotengine/godot/files/6643450/testpr.zip)

**Comment by romanra1** [comment]
I guess this happens after a loader either has not been found, or it failed to load the resource?

From core/io/resource_loader.cpp:
```c++
RES ResourceLoader::_load(const String &p_path, const String &p_original_path, const String &p_type_hint, bool p_no_cache, Error *r_error) {

	bool found = false;

	// Try all loaders and pick the first match for the type hint
	for (int i = 0; i < loader_count; i++) {

		if (!loader[i]->recognize_path(p_path, p_type_hint)) {
			continue;
		}
		found = true;
		RES res = loader[i]->load(p_path, p_original_path != String() ? p_original_path : p_path, r_error);
		if (res.is_null()) {
			continue;
		}

		return res;
	}

	ERR_FAIL_COND_V_MSG(found, RES(),
			vformat("Failed loading resource: %s. Make sure resources have been imported by opening the project in the editor at least once.", p_path));

#ifdef TOOLS_ENABLED
	FileAccessRef file_check = FileAccess::create(FileAccess::ACCESS_RESOURCES);
	ERR_FAIL_COND_V_MSG(!file_check->file_exists(p_path), RES(), "Resource file not found: " + p_path + ".");
#endif

	ERR_FAIL_V_MSG(RES(), "No loader found for resource: " + p_path + ".");
}
```

**Comment by akien-mga** [comment]
If you import a resource, only the imported files will be exported, not the source file. When using a CSV file as translation (TranslationCSV) importer, the `.translation` files are the ones used by the engine to add translations to the `TranslationServer`.

If you want to parse CSV files manually, you should configured them not to be imported ("Keep (No Import)" in the Import dock), so they will be exported and you can parse them manually as files. But then they're not used in the translation system.

What's your use case for manual loading of already imported CSV translations?

**Comment by romanra1** [comment]
@akien-mga 
The problem is not the export but the fact that I am unable to edit the CSV directly in the Godot's text editor. Is it not possible?

**Comment by romanra1** [comment]
When running the game in the editor I get

> E 0:00:00.282   _load: Failed loading resource: res://Translations/Strings.csv. Make sure resources have been imported by opening the project in the editor at least once.
>  <C++ Error>   Condition "found" is true. Returned: RES()
>  <C++ Source>  core/io/resource_loader.cpp:282 @ _load()

**Comment by romanra1** [comment]
I managed to fix it. 
For some reason Project Settings > General > Locale > Translations was set to res://Translations/Strings.csv instead of being an array of .translation files.
