### ISSUE TITLE
Gridmap does not support scenes with multiple models

### ISSUE THREAD

**Issue by Dente222** [godotengine/godot#49578]
### Godot version

3.3.2

### System information

Windows 10, GLES3

### Issue description

Grid maps don't like scenes that use more than one Mesh inside them and remove every secondary mesh from it.
This means that If you have a model that is separated into multiple parts then only the first part of the model will be visible, other parts "Including anything that is parented to these parts" will be removed.

Here is an example of that:
This is the photo of my model. Note that Hammer and Pedestal are 2 separate models:
https://cdn.discordapp.com/attachments/604227989550530561/853737639634141224/unknown.png

Here is the photo of that scene tree. "Pedestal with Hammer is the name for pedestal itself and Hammer Decoy is a hammer on its own"
https://cdn.discordapp.com/attachments/604227989550530561/853737742109507595/unknown.png

And here is the outcome where Hammer has magically disappear...
https://cdn.discordapp.com/attachments/604227989550530561/853737570168471622/unknown.png

I know that grid maps don't support much but this should be supported on its own, currently to bypass that you have to combine every mesh into one.

### Steps to reproduce

1. Make 2 models in one scene  "2 separate cubes should work"
2. Import it to Godot
3. Save it as a scene and add it to Meshlibrary "Make sure that Both cubes are not one but two different models in one scene"
4. Load grid map and place cubes

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
