### ISSUE TITLE
Dividing by certain numbers in node inspector rounds to nearest integer . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot#49579]
### Godot version

Godot 3.3

### System information

Windows 10

### Issue description

I was looking to go from seconds, to frames, using the wait node box, but the math doesn't work, in the inspector . . Here are some examples, first one's work, but when one divides by something, where result is close to 1, it removes all decimals, but it doesn't happen, for many other numbers . . .

![2021-06-14 0224](https://user-images.githubusercontent.com/83387915/121826482-257e1200-ccb8-11eb-9575-f2d27f203d7d.gif)

For instance, dividing 3 / 2, gives result 1, instead of 1.5, see above . . However, 3.2 / 2 gives result 1.5 . . So . .

3.2 / 2 = 1.6

3 / 2 = 1 ( not 1.5 )

2.8 / 2 = 1.4

Anyway, not sure why it happens, opened a new project and, tried to divide some numbers . . Problem is, many times it just writes 1, instead of the decimals number, like it's working in integers, or so on . . .

I wanted to make some 'frame' wait times, but if I do this . .

1/60 = 0 ( not 0.0167 )
2/60 = 0 ( not 0.0333 )
3/60 = 0 ( not 0.050 )

Anyway, not sure what happens, or why it works, for other numbers :(( <3

### Steps to reproduce

Open a new project, and write the above math, it should make numbers either 0, or 1, instead of correct decimals calculations, in the above cases . . It's like for numbers near 1, or 0, it rounds to nearest integer, for SOME calculations . . Not sure if this is intended or, what's wrong . .

Not even sure if it is a bug, or engine makers want this, makes it some-what annoying to try and type Wait numbers, that match frame time . . :OO Thx . . .

**Comment by charlesmlamb** [comment]
Here's more examples . .

![2021-06-14 0239](https://user-images.githubusercontent.com/83387915/121826753-cc16e280-ccb9-11eb-9349-3a3d9bea9213.gif)

Not sure why it happens, seems ' strange ' or, a bug ?? . . . .

**Comment by Calinou** [comment]
This is intended. Dividing two integers will return another integer.

To get a floating-point value, use `12/7.0` or `12.0/7`. You can shorten it to `12./7` or `12/7.` since non-significant zeros don't have to be specified.
