### ISSUE TITLE
Useless error on installing incompatible android build via debug

### ISSUE THREAD

**Issue by ModProg** [godotengine/godot#49588]
### Godot version

3.3.2.stable

### System information

Android

### Issue description

Trying to run a project with the same name e.g. `org.godotengine.example` via debug on a device where a different incompatible version is already installed, the cryptic error message: `Could not install on device.` is issued.

The real problem can be shown by running `adb install`:
adb: failed to install build/example.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package org.godotengine.example signatures do not match previously installed version; ignoring!]

I would expect Godot to either tell me to uninstall the incompatible version, or ask if it should do that (the command would be `adb uninstall org.godot.example`.

### Steps to reproduce

1. Install a build on an Android device (either manually or via debug)
2. Regenerate the `debug.keystore` you need to delete it to make `keytool` work
3. Try to run the Project again (by clicking the Android symbol in the editor in the top right)
4. You should get the error `Could not install on device.`
5. Verify that the error was the signature by exporting the project for android and installing via `adb install $FILENAME.apk`

**Comment by Calinou** [comment]
Note that I added a note about this on the documentation recently: https://github.com/godotengine/godot-docs/pull/4971

**Comment by madmiraal** [comment]
You can remove the previous install by enabling the `Clear Previous Install` option under `One Click Deploy`:
![OneclickDeploy1](https://user-images.githubusercontent.com/9253928/122641977-48695580-d100-11eb-8e87-4d58dffc53dc.png)

**Comment by ModProg** [comment]
> You can remove the previous install by enabling the `Clear Previous Install` option under `One Click Deploy`:

Yes, therefore having a more descriptive error is my biggest consern.

**Comment by heroassem** [comment]
![Screenshot 2024-06-16 172020](https://github.com/godotengine/godot/assets/165303929/97ebe17d-ecda-40db-b0e4-25893740d20a)

### My System
windows 10
64bit 
### My engine 
godot 4.2.2
### My Error
` editor/export/editor_export_platform.h:182 - Run: Could not install to device: adb: failed to install C:/Users/Admin/AppData/Local/Godot/tmpexport.1718550563.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.example.project signatures do not match newer version; ignoring!]
  Performing Streamed `Install``

**Comment by zaddok** [comment]
Is there a workaround for when this occurs in 4.2.2? I have tried changing settings, clearing the android folder, restarting everything, and more.

**Comment by zaddok** [comment]
The tick box "Clear Previous Install" doesnt appear to exist on 4.2.2 Why was it removed? How do we solve this now? My test android device _does not_ have the app installed at all. So something strange is going on and the error message is not helpful.
