### ISSUE TITLE
Closing current scene with hotkey triggers "save scene" method

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#49580]
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

Is this a bug or feature? closing opened scene with close button closes without save popup, closing scene with hotkey **CTRL+SHIFT+W**  opens saving popup and closes scene.

### Steps to reproduce

1. close scene with close button (**X icon on tab** )
2. reopen closed scene
3. close scene with **CTRL+SHIFT+W**

**Comment by KoBeWi** [comment]
Duplicate of #30140
