### ISSUE TITLE
Collision detection at startup issue

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#4959]
I am really hesitant to report this, but I ran out of options.

The issue is that at running the project, when Godot logo with splash screen appears, the nodes `_fixed_process()` function starts. All fine and dandy, but the problem is at the same time collisions doesn't work if there is one at startup! I used manual collision checking for RayCast2D or even Area2D, they fail to report collisions or overlapped areas when there is already one at startup. The collision objects ends up half way through the ground.

I suspected that physics server is not yet loaded and running when the nodes are already moving. What I did and seems to fix it:
```
onready var testTime = 0

func _read():
	set_fixed_process(true)

func _fixed_process(delta):
	testTime += delta
	if (testTime < 1):
		return

 ... rest of processing, collision checking .. etc!..
```

Is this the proper way of fixing it? Why `_ready()` is called when in fact it is not ready?

**Comment by reduz** [comment]
physics generally runs one frame behind to logic, and collisions are
processed all at once. This way a lot of cpu time is saved and both of them
can run simultaneously when multi thread configuration is selecte. It also
helps that you have enough time to move objects by code before any
collision is reported and detected.
It' s kind of a catch22, but it's generally preferred to adapt to this way
of thinking to later have less performance problems

**Comment by RebelliousX** [comment]
Thanks @reduz for the explanation :+1: Good to know that.
