### ISSUE TITLE
Visual Script – Godot 4 – AutoConstruct int to string not working

### ISSUE THREAD

**Issue by Anaxan** [godotengine/godot#49599]
### Godot version

v4.0.dev.calinou [6d98f84ab]

### System information

Ubuntu 20.10/Atermiter dual Xeon motherboard, gtx 970 nvidia package 460

### Issue description

When hooking a non string type to a set text label the autoconstructor does not appear. See attached GIFs for current vs expected behavior.
![int_yo_string4 0](https://user-images.githubusercontent.com/81984273/121899623-96dab680-ccf2-11eb-888c-27b7a4ae22b6.gif)
![int_to_string3 3 3](https://user-images.githubusercontent.com/81984273/121899644-9c380100-ccf2-11eb-9d8d-f4adbaf730d6.gif)

### Steps to reproduce

Drag a connection from a variable output to the connection on a set text label and notice the auto constructor does not appear.

### Minimal reproduction project

Will create if requested.

**Comment by KoBeWi** [comment]
VisualScript is removed in 4.0, closing.
