### ISSUE TITLE
Can't copy path to node from inherited scene

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#49596]
### Godot version

3.3.2

### System information

Linux, NVidia GTX 1080, GLES3

### Issue description

Using `ctrl+c`/`Copy Path` on an inherited node says "Can't operate on nodes the current node inherits from".
It seems like you should be allowed to perform non-mutating operations in inherited nodes.
For example, an attached script might want to reference node paths to inherited nodes.

### Steps to reproduce

1. Create a scene with at least one child node
2. Create an inherited scene from the scene in step 1
3. Click on one of the grayed-out nodes in the inherited scene
4. Press ctrl+c

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/6648209/example.zip)

**Comment by timothyqiu** [comment]
FYI: Copy Path now defaults to CTRL-SHIFT-C. CTRL-C is the actual Copy™.

**Comment by rcorre** [comment]
:facepalm: ah, you're right. Copy Path still works, and I was trying to just Copy, which makes sense to disable.
