### ISSUE TITLE
Line does not disappear when distraction-free mode is enabled

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#49608]
### Godot version

3.3.2 stable oficial

### System information

win10 64

### Issue description

a line in the middle of the editor remains even if the minimap was deactivated and do not disturb (no distraction) mode is activated
![gif gif](https://user-images.githubusercontent.com/19652075/121949600-f075cc00-cd58-11eb-9f80-ab2a91cfb172.gif)

### Steps to reproduce

disable the code editor minimap
activate do not disturb mode

**Comment by Calinou** [comment]
This is intended. The line represents the guideline that you should not exceed to keep your scripts readable.

You can remove this line length guideline by unchecking **Show Line Length Guideline**:


![image](https://user-images.githubusercontent.com/180032/121951109-c91ffe80-cd5a-11eb-8226-1429c4b45bf3.png)
