### ISSUE TITLE
Error while compiling for windows universal: 'OSWinrt': cannot instantiate abstract class

### ISSUE THREAD

**Issue by MB3hel** [godotengine/godot#4962]
I am running Windows 8.1 64-bit with 32-bit Python 2.7.11 and 32-bit pywin32 build 220 and scons 2.5.0 with Godot source cloned from the branch 'master'.

When running (using a Visual Studio 2015 x64 Native Tools Command Prompt):

<pre>scons platform=winrt</pre>

from the source directory it will run for a few seconds then give this error: 

<pre>platform\winrt\app.cpp(71): error C2259: 'OSWinrt': cannot instantiate abstract class
platform\winrt\app.cpp(71): note: due to following members:
platform\winrt\app.cpp(71): note: 'Size2 OS::get_window_size(void) const': is abstract
C:\godot\core\os/os.h(167): note: see declaration of 'OS::get_window_size'
platform\winrt\app.cpp(114): warning C4291: 'void *operator new(size_t,const char *)': no matching operator delete found; memory will not be freed if initialization throws an exception
c:\godot\core\os/memory.h(207): note: see declaration of 'operator new'
scons: *** [platform\winrt\app.winrt.tools.x64.obj] Error 2
scons: building terminated because of errors.</pre>

**Comment by slapin** [comment]
IIRC WinRT port is not complete and considered not supported yet,
so you will have to investigate the problem and provide fix.
@reduz correct me if I'm wrong.

**Comment by akien-mga** [comment]
It's indeed a work-in-progress and hasn't received much attention lately, so I'm not surprised it doesn't build. That doesn't mean that the OP should find a fix by themselves, any interested contributor can investigate and try to find a fix. It's likely easy to reproduce the bug.

**Comment by vnen** [comment]
@punto- probably knows better about this.

**Comment by MB3hel** [comment]
The same thing happens with Visual Studio 2013 on Windows 8.1 and with Visual Studio 2013 and Visual Studio 2015 on Windows 10.

**Comment by MB3hel** [comment]
I was trying to build version 1.0 (from git branch) and am now getting an error linking 'libEGL.lib'. Does anyone know why that is or how to fix it?

**Comment by vnen** [comment]
WinRT is totally broken, even if you manage to build it won't work (even in 1.0 I'd guess, though I haven't tested). `libEGL.lib`, `libGLESv2.lib` and `libANGLE.lib` are all from the ANGLE project. You can build it from the [MS repo](https://github.com/Microsoft/angle) (which have solutions ready) or from the [upstream from Google](https://chromium.googlesource.com/angle/angle) (which needs the depot_tools).

I'm currently working on this platform to make it work fully and already made quite a progress, but there are still stuff missing. Hopefully it'll be on master soon and ready for 2.2.

**Comment by akien-mga** [comment]
Likely fixed by #6363.
