### ISSUE TITLE
Broken single node selection

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#49627]
### Godot version

4.0.dev (e312df0)

### System information

Win 10 / 1080 Ti

### Issue description

Selection of single node is broken after [this commit.](https://github.com/godotengine/godot/pull/49482)

<details>
  <summary>Video:</summary>

https://user-images.githubusercontent.com/2698825/122100617-09938100-ce1c-11eb-84f2-b8a92739a9e8.mp4

</details>

### Steps to reproduce

Create/open a scene and select a node.

### Minimal reproduction project

[Test2.zip](https://github.com/godotengine/godot/files/6657667/Test2.zip)

**Comment by akien-mga** [comment]
CC @unsignedFoo

**Comment by unsignedFoo** [comment]
Sorry I can't see it properly on the mobile phone. Once I have a moment I'll rollback.

**Comment by akien-mga** [comment]
I reverted the fix in `master` for now as the Inspector was unusable. But we can work on another attempt at solving #49451 in `master`.
