### ISSUE TITLE
`Find in files` does not search in built-in scripts unless `tscn` is added to the list of file extensions to search through

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#49629]
### Godot version

3.3 stable

### System information

Linux

### Issue description

`Find in files` don't give search results for built-in scripts.

### Steps to reproduce

1. Create a scene
2. Create a built-in script for example `func _ready(): print('hello')`
3. Open `Find in files` dialog (`Script` - `Search` - `Find in files` / `Ctrl+Shift+F`)
4. Type `hello`, press `Find`
As you can see, there are `0 matches in 0 files`

**Comment by Calinou** [comment]
This is expected, since Godot would have to search within `.tscn` files (or worse, binary `.scn`) files to do this.

You can add `.tscn` to the list of file extensions to search inside in the Project Settings.

**Comment by me2beats** [comment]
Oh I missed this setting.

This works, but it doesn't looks convenient IMO.
I would prefer these files to be opened in the ScriptEditor as built-in scripts rather than text scene files.
It could be a separate proposal.

This issue could be closed I think, thanks
