### ISSUE TITLE
Vulkan: Decal sorting changes unexpectedly depending on camera rotation

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#49639]
### Godot version

4.0.dev (6d98f84ab)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

The new Decal node exhibits sorting issues when the camera moves or rotates. This can be seen both in the editor and in running projects:

https://user-images.githubusercontent.com/180032/122155594-9283da00-ce67-11eb-98b9-5697145dfd9b.mp4

I'm not sure *how* we should prevent this. We may not be able to rely on scene tree order because decals may be created with a lower-level API that does not use nodes. Maybe we could have a Render Priority property in the Decal node, so that users can force specific decals to render on top of others.

### Steps to reproduce

- Add 2 Decal nodes partially overlapping each other, with a different appearance (e.g. different **Modulate** property).
- Rotate the camera. Moving the camera alone does not seem to cause sorting issues, but rotating the camera will.

### Minimal reproduction project

[test_decal_sorting.zip](https://github.com/godotengine/godot/files/6660165/test_decal_sorting.zip)

**Comment by clayjohn** [comment]
I've noticed this issue as well. It looks like we may need to add some additional sorting to decals, however, any additional sort operation is likely to be quite expensive when you have many decals in a scene. 

Does the issue remain if you move each decal slightly up or down on the global Y-axis?

**Comment by Calinou** [comment]
> Does the issue remain if you move each decal slightly up or down on the global Y-axis?

Changing each decal's height will affect sorting, but using a slightly different each for each decal doesn't fix the variable sorting issues depending on camera rotation.

**Comment by Flavelius** [comment]
If they were sorted based on the projector's center/origin/position in the projection direction, it would make it an intuitive adjustment for users (optionally with an additional exposed bias parameter).

**Comment by Calinou** [comment]
@mieldepoche Please open a new issue with a minimal reproduction project attached.
