### ISSUE TITLE
Godot 4 Vulkan: latest night build broke SDFGI

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#49631]
### Godot version

v4.0.dev.calinou [4e582f9a7]

### System information

Win 10 64, AMD RX 480

### Issue description

When testing the latest night build, it looks like SDFGI broke and some spam errors show up.

### Steps to reproduce

Open project and enable sdfgi

**Comment by fire** [comment]
Is this still valid?

**Comment by Xartorx** [comment]
> Is this still valid?

Yes, it's still valid.

<details>
  <summary>Video (also shows bug with VoxelGI):</summary>

https://user-images.githubusercontent.com/2698825/122483625-b1a37880-cfdb-11eb-9dbc-e244fe1809bf.mp4

</details>

<details>
  <summary>Console output:</summary>


```
ERROR: Texture (binding: 17, index 0) is not a valid texture.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:4988)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:6966)
ERROR: Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7162)
```


</details>

**Comment by Calinou** [comment]
I bisected this to 7513b73902f3ed7ac45aa9aefc2f6f333ae731ff.

```
7513b73902f3ed7ac45aa9aefc2f6f333ae731ff is the first bad commit
commit 7513b73902f3ed7ac45aa9aefc2f6f333ae731ff
Author: reduz <reduzio@gmail.com>
Date:   Sat Jun 12 20:37:56 2021 -0300

    Fix VoxelGI (works again).
    
    It was broken due to #46046, this makes it work again.
```

**Comment by mauriciomarinho2** [comment]
Same error happens on my machine, version v4.0.dev.custom_build [60dcc4f39]
Pop!_OS 20.10, Nvidia driver 460.73.01, RTX 2070

```
  Texture (binding: 17, index 0) is not a valid texture.
  drivers/vulkan/rendering_device_vulkan.cpp:6966 - Condition "!uniform_set" is true.
  Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
```

**Comment by Ace-Dragon** [comment]
Strangely, I can get the SDFGI to work if I bake a Voxel GI probe and then remove it (if the checkbox in the sky settings was already ticked).

Nvidia Studio Driver May version, GTX 1060 6GB.

**Comment by AndreaCatania** [comment]
I've the same issue, with the following error, my GPU is Nvidia GTX 970
```
  Texture (binding: 17, index 0) is not a valid texture.
  drivers/vulkan/rendering_device_vulkan.cpp:6966 - Condition "!uniform_set" is true.
  Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
```

**Comment by clayjohn** [comment]
The issue is likely in this chunk of code (thanks to @Calinou for bisecting and finding the commit):
https://github.com/godotengine/godot/blob/7513b73902f3ed7ac45aa9aefc2f6f333ae731ff/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L3733-L3743

With the previous logic, ``setup_voxel_gi_instances()`` was called whenever SDFGI was used and ``rb->sdfgi->update_light()`` was called after ``setup_voxel_gi_instances()``, beyond that, the logic didn't change in that PR. 

So either sdfgi is erroneously relying on some state set in ``setup_voxel_gi_instances()`` or ``rb->sdfgi->update_light()`` needs to be called after  ``setup_voxel_gi_instances()``

**Comment by mauriciomarinho2** [comment]
Not sure if it might help now, but I managed to go back a few commits to where the error started happening: 7513b73902f3ed7ac45aa9aefc2f6f333ae731ff
