### ISSUE TITLE
Placeholder doesn't work on .tscn scenes.

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4963]
**Godot version:**
Built from source [7913e7](https://github.com/godotengine/godot/commit/7913e792acd656469b29fb90be1dbb7c06a855ba)

**Issue description**:
The placeholder option doesn't work on a instance of a .tscn scene. But an instance of this same scene saved as .scn works as a placeholder.

**Comment by akien-mga** [comment]
Actually, superseded by #7345.
