### ISSUE TITLE
editor_description isn't saved

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#49648]
### Godot version

d36b220

### System information

W10

### Issue description

When you set `editor_description` and reload scene, it will be cleared. Upon further inspection, seems like it's not saved in tscn file at all.

### Steps to reproduce

1. Add node
2. Set its `editor_description` property
3. Save and reload scene

**Comment by akien-mga** [comment]
For the reference, I had an old build lying around at 8b06d4275 (June 2) and the regression was already present there.
