### ISSUE TITLE
Issues parsing ProjectSettings with keys in Chinese

### ISSUE THREAD

**Issue by zuiaiyangyang3** [godotengine/godot#49646]
### Godot version

3.3.2

### System information

win10 64

### Issue description

I wrote it in the red circle.
Chinese.
The following error occurred during Android debugging
![QQ图片20210616134858](https://user-images.githubusercontent.com/61361272/122164612-a3edd600-cea9-11eb-94b6-d2d13a6291e7.png)

![QQ图片20210616134549](https://user-images.githubusercontent.com/61361272/122164512-7e60cc80-cea9-11eb-8cb7-0513739c703d.png)

### Steps to reproduce

Automatically load gd

![Clipboard - 2021年6月15日晚上11点57分](https://user-images.githubusercontent.com/61361272/122166146-c54fc180-ceab-11eb-8695-7e75b54ea148.png)

**Comment by zuiaiyangyang3** [comment]
![bug](https://user-images.githubusercontent.com/61361272/122166232-e57f8080-ceab-11eb-8882-08d33df8f31d.png)

**Comment by bruvzg** [comment]
Is it Android specific or happening on all exports / when running from editor?

>    "no space left"

This is UTF-8 parsing error. Might be overlong encoding (Is Android using some non-standard UTF-8 variant, like CESU-8?), or it's trying to parse non UTF-8 string as UTF-8 somewhere.

It's hard to tell what's exactly going wrong without a reproduction project.

**Comment by timothyqiu** [comment]
Is your project created using the unofficial Chinese Power-up build (中文加强版)?

The official build does not support using arbitrary Unicode as identifier yet, see https://github.com/godotengine/godot-proposals/issues/916

**Comment by zuiaiyangyang3** [comment]
> 您的项目是使用非官方的中国电源生成（新版）创建的吗？
> 
> 官方版本不支持使用任意的 Unicode 作为标识符， 见[戈多工程 / 戈多特建议 #916](https://github.com/godotengine/godot-proposals/issues/916)

Yes, third-party Godot.
Only the red circle does not support Chinese.

Other places are fine.

The red circle is.
Chinese characters. The Android simulator will flicker and report an error.
Just change it to English.

**Comment by timothyqiu** [comment]
Then this is indeed due to using characters outside the `0-9a-zA-Z` range as name of AutoLoad, which the official build does not allow. (so I don't think it's kind of an issue.)

In case anyone wants to test, here is an MRP: [ChinesePowerUp.zip](https://github.com/godotengine/godot/files/6660929/ChinesePowerUp.zip). Export this project to any platform, not limited Android, and run the binary, and you'll get the same error log.

**Comment by zuiaiyangyang3** [comment]
> 因此，这确实是由于使用范围外的字符作为自动加载的名称，这是官方构建不允许的。（所以我不认为这是典型的问题。`0-9a-zA-Z`
> 
> 如果有人想测试，这里有一个MP：[中国电力.zip。](https://github.com/godotengine/godot/files/6660929/ChinesePowerUp.zip)将此项目导出到任何平台，而不是限制 Android，并运行二进制文件，您将获得相同的错误日志。

Indeed.
I made the same mistake on the exe platform.
I use the enhanced Chinese version.
It seems that.
I'll wait for the boss to see if I can support it.
