### ISSUE TITLE
[Error] Websocket Client - Invalid URL

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot#49652]
### Godot version

v4.0.dev.calinou [c2ba45fcc]

### System information

Windows 10

### Issue description

I want to connect to a WebsocketServer with the `WebsocketClient.connect_to_url("ws://127.0.0.1:4444")` but I get this error:
![Websocket-url-error](https://user-images.githubusercontent.com/71942164/122211764-612afe80-cea7-11eb-8cda-3d8fb8f8ab93.PNG)

I am able to connect to my Websocketserver with Godot 3.3 and this url.

### Steps to reproduce

Try to run `connect_to_url("ws://127.0.0.1:4444")` with a Websocket Client.

### Minimal reproduction project

[Websocket Client.zip](https://github.com/godotengine/godot/files/6662628/Websocket.Client.zip)

**Comment by akien-mga** [comment]
Would probably be fixed by #49505.

**Comment by Gamemap** [comment]
@akien-mga I tried the Windows build and it worked.
Thank you.

**Comment by akien-mga** [comment]
Let's keep it open, it should be closed when the PR is merged.
