### ISSUE TITLE
Several errors in german translation

### ISSUE THREAD

**Issue by ajacobsen** [godotengine/godot#4965]
**Godot version:**
commit 1ae9ff19194af9a365b3a76e50ee8d3aa01205b8

The commit da25b76aa1c1950df34d540e808919f2f3740b9d added a lot of good translations but also has also some errors as listed below:

```
 #: tools/editor/code_editor.cpp
 msgid "Match Case"
-msgstr ""
+msgstr "Übereinstimmung"
```
Should be translated as `"Groß-/Kleinschreibung berücksichtigen"`

```
#: tools/editor/code_editor.cpp tools/editor/script_editor_debugger.cpp
 msgid "Line:"
-msgstr ""
+msgstr "Zeile"
````
The punctuation is missing, should be `"Zeile:"`

```
#: tools/editor/project_export.cpp
 msgid "Error exporting project!"
-msgstr ""
+msgstr "Fehler beim exportieren des Projekts!"
```
Should be translated as: `"Fehler beim Exportieren des Projekts!"`

 ```
#: tools/editor/project_settings.cpp
 msgid "Press a Key.."
-msgstr ""
+msgstr "Drück eine Taste"
```
Should be translated as `"Drücke eine Taste.."`

**Comment by akien-mga** [comment]
Please make a pull request, it would be much easier to manage.

**Comment by ajacobsen** [comment]
#4968

**Comment by akien-mga** [comment]
Merged.
