### ISSUE TITLE
Visual Script - Godot 4 - Odd Constructors.

### ISSUE THREAD

**Issue by Anaxan** [godotengine/godot#49671]
### Godot version

v4.0.dev.calinou [4e582f9a7]

### System information

Ubuntu 20.10/Atermiter dual Xeon motherboard, gtx 970 nvidia package 460

### Issue description

Several visual script constructors serve no purpose as their outputs match their inputs. My expectation would be ,for example, a Vector 2 output from  float or integer x and y inputs.
![Constructor_problems](https://user-images.githubusercontent.com/81984273/122314994-29dc4200-cee7-11eb-82db-3b1f9059ab92.gif)

### Steps to reproduce

Open the constructor section and notice many of the descriptions will say something like Construct BoolBool. I picked out many of them and added them in a column within the reproduction project.

### Minimal reproduction project

[odd_constructors.zip](https://github.com/godotengine/godot/files/6666665/odd_constructors.zip)

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
