### ISSUE TITLE
Crash on project startup at cmd->post()

### ISSUE THREAD

**Issue by RicardRC** [godotengine/godot#49684]
### Godot version

4.0 master branch (2b0bf20) but has been like this for at least three days.
At (8c2beee) the issue was not present.

### System information

Windows 10

### Issue description

When opening my project, it crashes on "cmd-post()" with the following callstack:
![image](https://user-images.githubusercontent.com/35220750/122400974-7a51af00-cf7c-11eb-981f-42ba319d81b0.png)

And the following console output:
```
Godot Engine v4.0.dev.custom_build.2b0bf20dc - https://godotengine.org
Vulkan API 1.2.162
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_get_json: Failed to open JSON file C:\WINDOWS\System32\amd-vulkan64.json
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2019601913824
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2019601913824
     at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:154)
Using Vulkan Device #0: NVIDIA - GeForce GTX 1070
- Vulkan multiview supported:
  max view count: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 32
  stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE, STAGE_RAYGEN_KHR, STAGE_ANY_HIT_KHR, STAGE_CLOSEST_HIT_KHR, STAGE_MISS_KHR, STAGE_INTERSECTION_KHR, STAGE_CALLABLE_KHR
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
  quad operations in all stages

ERROR: Compiler bug: unresolved assign.
   at: GDScriptByteCodeGenerator::write_assign_with_conversion (modules\gdscript\gdscript_byte_codegen.cpp:816)

```

The last error that was listed has the following callstack, not sure if related:
![image](https://user-images.githubusercontent.com/35220750/122400847-61e19480-cf7c-11eb-8ee8-da51de6f793d.png)
At that function, the p_target is of mode "local variable" and type null, and the p_source is of mode "temporary" and type null.

### Steps to reproduce

Try to open my current project.
Does not happen on new projects.

### Minimal reproduction project

Not yet.

**Comment by RicardRC** [comment]
Some locals I think could help:
![image](https://user-images.githubusercontent.com/35220750/122519077-5640ad00-d012-11eb-8006-a80fef26af22.png)
Seems like the problem is with the "unsigned int vector deleting destructor".

**Comment by RicardRC** [comment]
Looks like the problem exists only when I preload a packed scene that has a subviewport. Changed the script from preload to load and now this does not happen.

**Comment by akien-mga** [comment]
Can you still reproduce this in 4.0.3 and 4.1-beta3 or later?

If so, could you provide a reproduction project?

**Comment by YuriSizov** [comment]
I'm going to close this as there isn't any new information or corroborating reports. If you still can reproduce the issue with Godot 4.2 or the current `master`, please let us know and we can reopen it.
