### ISSUE TITLE
Root viewport is being incorrectly sized when HTML5 build runs in mobile phone browser

### ISSUE THREAD

**Issue by Quindigo** [godotengine/godot#49692]
### Godot version

3.3.2-stable (official)

### System information

browser on Android 9 mobile phone, GLES2

### Issue description

When the HTML5 build of the project is opened in a mobile phone browser, the root viewport receives a small size (1/3 of the actual width and 1/3 of the actual height of the client area) and the rendered image is upscaled to fit the browser client area.
If the same project is exported to HTML5 using a previous version of Godot (3.2.3) and opened in a mobile phone browser, the root viewport receives the expected size.

So far, the problem was reproduced with FireFox, Chrome and Brave browsers on Android 9, and Brave browser on iOS.
When opening the project in a desktop PC browser, it works as expected.

This is a mobile phone screenshot of the problem in fullscreen:
![ViewportInfo_Godot3 3 2](https://user-images.githubusercontent.com/31621615/122430038-a1eb4c00-cf69-11eb-921f-6534707c1466.png)

This is a mobile phone screenshot of the expected result in fullscreen:
![ViewportInfo_Godot3 2 3](https://user-images.githubusercontent.com/31621615/122430034-a152b580-cf69-11eb-82f4-0b5f74db11cd.png)

### Steps to reproduce

Open this Godot 3.3.2 build of the minimal reproduction project in a mobile phone browser to see the problem:
http://www.quindigo.eti.br/Godot/ViewportInfo3.3.2/index.html

Open this Godot 3.2.3 build of the minimal reproduction project in the same mobile phone browser to see the expected result:
http://www.quindigo.eti.br/Godot/ViewportInfo3.2.3/index.html

### Minimal reproduction project

[viewport_info.zip](https://github.com/godotengine/godot/files/6671532/viewport_info.zip)

**Comment by Calinou** [comment]
This is expected since the HTML5 export is now DPI-aware since Godot 3.3. Is **Allow Hidpi** enabled in the Project Settings? If not, enable it and try exporting again.

**Comment by Quindigo** [comment]
Thanks for pointing this **Allow Hidpi** option and for the explanation, Mr. Calinou!
The problem is solved and it was not a bug.
Closing this issue right away.
