### ISSUE TITLE
Websocket Network Limits in ProjectSettings missing

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot#49704]
### Godot version

v4.0.dev.calinou [8ffb631cd]

### System information

Windows 10

### Issue description

The `network/limits/websocket_client/` and `network/limits/websocket_server/` settings in the ProjectSettings are missing in the 4.0 dev Version.
In Godot 3.3 they are there:
![Websocket Client settings](https://user-images.githubusercontent.com/71942164/122531186-8e022180-d01f-11eb-99e7-c8ce38064c59.PNG)
Godot 4.0 dev:
![Websocket Client settings2](https://user-images.githubusercontent.com/71942164/122538082-7f6b3880-d026-11eb-82b3-ce784436e71a.PNG)

### Steps to reproduce

- Go to the ProjectSettings in Godot 4.0 dev.

**Comment by akien-mga** [comment]
Did you toggle Advanced settings?

**Comment by Gamemap** [comment]
Yes.

**Comment by akien-mga** [comment]
They were removed intentionally by @Faless in #37099.

**Comment by Gamemap** [comment]
Is it possible to change the Websocket values?

**Comment by Faless** [comment]
Yes, the [set_buffers](https://docs.godotengine.org/en/stable/classes/class_websocketmultiplayerpeer.html#class-websocketmultiplayerpeer-method-set-buffers) method in both `WebSocketClient` and `WebSocketServer`.
Although the documentation about the method should be updated.

**Comment by Gamemap** [comment]
Thank you!

**Comment by Gamemap** [comment]
@Faless  Am I right that `set_buffers` must be set once in the `_ready()` function? (before `connect_to_url()`)

**Comment by mhilbrunner** [comment]
Closing as this was an intentional change as per the discussion above.
