### ISSUE TITLE
Vulkan: Automatic LOD is broken

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#49706]
### Godot version

v4.0.dev.custom_build [085e1d3c0]

### System information

Win 10 / 1080 Ti

### Issue description

Imported models breaking down and glitching when moving camera away or sideways.

<details>
  <summary>Video:</summary>

https://user-images.githubusercontent.com/2698825/122557104-0202f080-d045-11eb-809e-0fd79c810a07.mp4

</details>

### Steps to reproduce

Open Main.tscn and move camera around.

### Minimal reproduction project

[Google Drive link, because project is too big for GitHub](https://drive.google.com/file/d/16nu3JkRs6_EN6-G-YrmaMBvs3ICWvv1Z/view?usp=sharing)

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
I think shadow meshes being disabled resolved this but its not ideal.

**Comment by Xartorx** [comment]
> I think shadow meshes being disabled resolved this but its not ideal.

Yeah, it resolves black clipping, but LOD is still too aggressive, model degrades too fast:

https://user-images.githubusercontent.com/2698825/122561750-e569b700-d04a-11eb-8f4b-7b8c4ac55f67.mp4

**Comment by fire** [comment]
I think the lod breaks when the mesh is 100x scale not able to check we could change the load bias baise on root scale.

**Comment by Xartorx** [comment]
Another test model with opposite effect - no LOD whatsoever (or at least i don't see changes):

https://user-images.githubusercontent.com/2698825/122604449-a3f2ff00-d07e-11eb-9900-72861498ab4d.mp4

**Comment by fire** [comment]
![Screenshot from 2021-06-18 12-16-04](https://user-images.githubusercontent.com/32321/122607172-06bcaa00-d02f-11eb-86a4-c30eacde3eb6.png)

The 0.001 scale is what breaks the lod.

**Comment by fire** [comment]
@Xartorx Can you try this build?

https://docs.godotengine.org/en/stable/community/contributing/testing_pull_requests.html

**Comment by Xartorx** [comment]
@fire a lot better, no black clipping on complex models, but still on ball for whatever reason.
Still, when zooming out models don't change to simpler ones (or maybe they do, but i can't see that? Too bad Information panel doesn't work properly rn).

https://user-images.githubusercontent.com/2698825/122611671-64321480-d08a-11eb-97f9-b71d49e7dd9c.mp4

**Comment by fire** [comment]
@Xartorx Can you try #49717

**Comment by Xartorx** [comment]
@fire tried out, now ball doesn't have any black clipping issues. Thanks 👍 
However, LOD on complex models (guns in my case) doesn't change, while on a ball it does. But it's hard to tell without working Information panel.

**Comment by fire** [comment]
My personal opinion is that the weapons can't be optimized while the sphere can be optimized.

I prefer numbers though to this intuition.

**Comment by Xartorx** [comment]
> My personal opinion is that the weapons can't be optimized while the sphere can be optimized.

I think weapons, as any other meshes, could be optimized, to a certain degree. 

> Also there are floatpoint point precision errors with 0.001 scale. Try the project I sent for a properly scaled mesh.

Tried it, now it works as other gun model.

> I disabled the shadow mesh. Need to retest.

Did a retest - no issues.

https://user-images.githubusercontent.com/2698825/122620576-f989d480-d09b-11eb-8a8e-b0249b4a463b.mp4
