### ISSUE TITLE
Godot 4 Occlusion culling broken

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#49709]
### Godot version

v4.0.dev.calinou [8ffb631cd]

### System information

Win 10 64, AMD RX 480

### Issue description

the new night build breaks the Occlusion culling feature
works v4.0.dev.calinou [6d98f84ab]
this build v4.0.dev.calinou [4e582f9a7] breaks

### Steps to reproduce

Ive imported the monkey from blender and used it as a test occluder, but as youll see the latest build, it dont work.

**Comment by akien-mga** [comment]
> works v4.0.dev.calinou [6d98f84]
this build v4.0.dev.calinou [4e582f9] breaks

Notable PR merged in between: #48847. @JFonS

**Comment by JFonS** [comment]
Looks like I inverted the IGNORE_OCCLUSION_CULLING logic in my last PR, it should be an easy fix.
