### ISSUE TITLE
InputEventMouseMotion.Relative is tied to window size

### ISSUE THREAD

**Issue by swift502** [godotengine/godot#49734]
### Godot version

v3.3.2.stable.mono.official

### System information

Windows 10, GLES3, GTX 1060 3GB 27.21.14.6647

### Issue description

I noticed that running my game in windowed mode at 1920x1080 results in noticeably higher mouse sensitivity than running it at 2560x1440.

Turns out the Third Person Shooter Demo suffers from the same issue. I performed roughly the same mouse movements with two different window sizes.

**Left:** 320x240 window, produces ~360° of camera rotation
**Right:** 2560x1440 window, produces ~60° of camera rotation

https://user-images.githubusercontent.com/24359130/122634668-c6693480-d0df-11eb-83e1-37b8cbd8d673.mp4

- Is this intended behavior?
- Is it not a problem to essentially have mouse sensitivity tied to screen resolution?

Thanks.

### Apparent solution

In case it helps, I noticed that multiplying the relative value by the smaller window dimension results in what I percieve as the "correct" behavior, where sensitivity remains constant across different window sizes and aspect ratios.

```cs
RotateCamera(@event.Relative); // works poorly

RotateCamera(@event.Relative * Mathf.Min(OS.WindowSize.x, OS.WindowSize.y)); // works much better
```

### Steps to reproduce

1. Use InputEventMouseMotion.Relative to orbit your camera around.
2. Run the game in windowed mode
3. Test mouse sensitivity with different window sizes
4. Test exaggerated aspect ratios, like and extremely wide or tall window, as the incorrect mouse sensitivty becomes even more apparent at those sizes

### Minimal reproduction project

Third Person Shooter Demo

**Comment by Calinou** [comment]
This depends on the configured stretch mode. Compare the default `disabled` mode with the `2d` stretch mode.

**Comment by swift502** [comment]
> this depends on the configured stretch mode

You seem to be right.

- `disabled` seems to work correctly.
- `2d` behaves incorrectly (as seen in the "comparison" video I posted).
- `viewport` seems to behave roughly the same way as `2d`, also incorrectly.

**Comment by flouterrr** [comment]
I'm still not 100% sure since I haven't looked at the engine code, but I suspected that InputEventMouseMotion.relative is actually tied to the size of the viewport / project width & height.

So after some testing I found that multiplying the InputEventMouseMotion.relative vector by a ratio of the window size by the viewport size to fix the problem, atleast when the stretch mode is set to 'viewport'.

Example:
`var mouse_movement = event.relative * (OS.window_size / get_viewport().size)`

**Comment by Braboware** [comment]
I recorded some data in 4.1.1 that may be useful.
[Project used for testing](https://github.com/godotengine/godot/files/12354213/Mouse.Sensitivity.and.Resolution.Test.Scene.zip)
used https://github.com/KovaaK/SensitivityMatcher for windows
and https://github.com/grindzohr/SensMatch for linux
3.0 sens x 0.022 yaw


OS | Viewport Width | Viewport Height | Size Mode | Stretch Mode |   | rotation_degrees.y, 1 Rotation | rotation_degrees.y, 22 Rotations | Notes
-- | -- | -- | -- | -- | -- | -- | -- | --
Windows 11 | 2560 (native) | 1440 (native) | Windowed | disabled |   | -0.0299999062 | 0.0000409813365 | On target
Windows 11 | 2560 (native) | 1440 (native) | Windowed | canvas_item |   | -4.809093475 | -106.6027145 |  
Windows 11 | 2560 (native) | 1440 (native) | Windowed | viewport |   | -4.875981808 | -106.6026764 |  
Windows 11 | 2560 (native) | 1440 (native) | Fullscreen | disabled |   | 0.03600022942 | 0.00001451422577 | On target
Windows 11 | 2560 (native) | 1440 (native) | Fullscreen | canvas_item |   | -0.593421638 | -12.39433098 |  
Windows 11 | 2560 (native) | 1440 (native) | Fullscreen | viewport |   | -0.5273184776 | -12.39431095 |  
Windows 11 | 2560 (native) | 1440 (native) | Exclusive Fullscreen | disabled |   | 0.03600022942 | 0.0000589106312 | On target
Windows 11 | 2560 (native) | 1440 (native) | Exclusive Fullscreen | canvas_item |   | -0.0299999062 | 0.00002646711255 | On target
Windows 11 | 2560 (native) | 1440 (native) | Exclusive Fullscreen | viewport |   | 0.03600022942 | 0.00006061821477 | On target
Windows 11 | 640 | 480 | Windowed | disabled |   | 0.03600022942 | 0.0000409813365 | On target
Windows 11 | 640 | 480 | Windowed | canvas_item |   | -0.0299999062 | 0.00005549551497 | On target
Windows 11 | 640 | 480 | Windowed | viewport |   | 0.03600022942 | 0.00002646712164 | On target
Windows 11 | 640 | 480 | Fullscreen | disabled |   | -0.0299999062 | 0.00005549550406 | On target
Windows 11 | 640 | 480 | Fullscreen | canvas_item |   | -120.1757736 | -124.1312561 |  
Windows 11 | 640 | 480 | Fullscreen | viewport |   | -120.1978073 | -124.1312714 |  
Windows 11 | 640 | 480 | Exclusive Fullscreen | disabled |   | 0.03600022942 | 0.00001451422577 | On target
Windows 11 | 640 | 480 | Exclusive Fullscreen | canvas_item |   | -120.0100021 | -120.0000763 |  
Windows 11 | 640 | 480 | Exclusive Fullscreen | viewport |   | -120.0100021 | -120.0000992 |  
  |   |   |   |   |   |   |   |  
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Windowed | disabled |   | -0.0299999062 | -0.6599736214 | On target
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Windowed | canvas_item |   | -22.75618935 | -140.6360779 |  
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Windowed | viewport |   | -22.75619316 | -140.6360016 |  
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Fullscreen | disabled |   | -0.02998282574 | -0.6598005891 | On target
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Fullscreen | canvas_item |   | -0.02998624183 | 0.6597261429 | On target
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Fullscreen | viewport |   | -0.02999136411 | -0.659752965 | On target
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Exclusive Fullscreen | disabled |   | -0.0299999062 | -0.6599736214 | On target
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Exclusive Fullscreen | canvas_item |   | -0.0299999062 | -0.659974277 | On target
Kubuntu 23.04 | 2560 (native) | 1440 (native) | Exclusive Fullscreen | viewport |   | -0.0299999062 | -0.6599736214 | On target
Kubuntu 23.04 | 640 | 480 | Windowed | disabled |   | -0.0299999062 | -0.6599736214 | On target
Kubuntu 23.04 | 640 | 480 | Windowed | canvas_item |   | -0.0299999062 | -0.6599736214 | On target
Kubuntu 23.04 | 640 | 480 | Windowed | viewport |   | -0.0299999062 | -0.6599736214 | On target
Kubuntu 23.04 | 640 | 480 | Fullscreen | disabled |   | -0.0299999062 | 0.6599736214 | On target
Kubuntu 23.04 | 640 | 480 | Fullscreen | canvas_item |   | -120.0100021 | -120.2200623 |  
Kubuntu 23.04 | 640 | 480 | Fullscreen | viewport |   | -120.0319977 | -120.2200623 |  
Kubuntu 23.04 | 640 | 480 | Exclusive Fullscreen | disabled |   | 0.0299999062 | -0.6599713564 | On target
Kubuntu 23.04 | 640 | 480 | Exclusive Fullscreen | canvas_item |   | -120.0100021 | -120.2200623 |  
Kubuntu 23.04 | 640 | 480 | Exclusive Fullscreen | viewport |   | -120.0100021 | -120.2200623 |
