### ISSUE TITLE
Window.has_focus() returns false when run.

### ISSUE THREAD

**Issue by sairam4123** [godotengine/godot#49739]
### Godot version

v4.0.dev (8ffb631cd)

### System information

Windows 10, Nvidia GeForce GTX 1050, 27.21.14.5771

### Issue description

`get_viewport().has_focus()` returns false till I manually change the focus to other window and then focus on the window.

`get_viewport().has_focus()` should return true if the window is focused

Here's the video showcasing the issue:

https://user-images.githubusercontent.com/61322406/122639475-b66d4700-d117-11eb-93b1-331e38c18893.mp4

### Steps to reproduce

1. Run the game.
2. Focus on other window.
3. Focus on the same window.

### Minimal reproduction project

[HasFocusBugTest.zip](https://github.com/godotengine/godot/files/6680500/HasFocusBugTest.zip)

**Comment by sairam4123** [comment]
Can still be reproduced in [`729461b2a`](https://github.com/godotengine/godot/commit/729461b2a).

**Comment by INdIEDeV016** [comment]
Uh yes, looks like it's happening with me as well

![image](https://user-images.githubusercontent.com/80198819/132897512-f2a9504e-4659-4112-a6f9-1e5b58bf76f6.png)

**Comment by sairam4123** [comment]
Can still confirm in 4.0.alpha.1.

**Comment by YuriSizov** [comment]
Appears to be fixed as of 4.1 beta 3 (but probably way before).
