### ISSUE TITLE
Can't Launch on Windows 7

### ISSUE THREAD

**Issue by ScotFlux** [godotengine/godot#4973]
**Operating system or device - Godot version:**

Windows 7 x64 - Godot 2.1 alpha phase at commit df139f5 or newer

**Issue description** (what happened, and what was expected):
Godot Engine can't Launch on Windows 7.

![w7 - godot issue](https://cloud.githubusercontent.com/assets/10663548/15707368/30be8b7e-281a-11e6-8be7-a2b1f51395e0.png)

**Steps to reproduce:**
1) Compile Godot for Windows, from Source (commit df139f5 or newer) using MSVC12 (VS2013) or MSVC14 (VS2015). I didn't test it using Mingw nor Cross Compiling from Linux OS.
2) Launch Godot on Windows 7.
3) Can't Launch.

**Link to minimal example project** (optional but very welcome):
- None

**Comment by reduz** [comment]
I have no idea how to fix this, the functions to get DPI are windows8+ it seems, so any help is appreciated.

**Comment by zaps166** [comment]
Hmm, you should dynamically resolve symbols using `GetModuleHandleA` and `GetProcAddress` for `GetDpiForMonitor` (example: https://github.com/zaps166/QMPlay2/blob/45aa629da4eb223b78e964fb11a2c81562ec1d88/src/modules/DirectX/DirectDraw.cpp#L57; https://github.com/zaps166/QMPlay2/blob/45aa629da4eb223b78e964fb11a2c81562ec1d88/src/modules/DirectX/DirectDraw.hpp#L14).
I can do a PR later, but I can't test.

**Comment by reduz** [comment]
yeah, ended up using LoadLibrary for this, thanks!
