### ISSUE TITLE
Operation/Assignment operators (+=/-=/*=) fail when used directly on type members

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#49748]
### Godot version

0a6a71973e50e31fef7b91658ab713ae5db5033f

### System information

Windows 10

### Issue description

GDScript will fail when attempting to use the operation/assignment operators (+=/-=/*=) on object members. So far, tested with Vector2, Vector3, Vector2i, Vector3i, and Quaternion. They do however work directly on floats and integers, just not class members.

![godot windows tools 64_ZNeeRKUBvU](https://user-images.githubusercontent.com/12756047/122651210-3f43ad00-d12f-11eb-8121-59d34b0d8fb4.png)

### Steps to reproduce

Simply create a GDScript function with the following code
```
var vec2: Vector2 = Vector2()
vec2.x += 1.0
```

### Minimal reproduction project

[testgd4.zip](https://github.com/godotengine/godot/files/6681115/testgd4.zip)

**Comment by Blackiris** [comment]
Noticed the same issue, bisecting indicates it starts happening since 2c81e5fa0ec17e8d17cc3c7df68417f9a49c73bc or b5f1e88b2ed7be4c0ecc9edf3f5d9f6287b7c513

**Comment by SaracenOne** [comment]
Thanks for bisecting this. It'll help a lot with tracking down the regression
