### ISSUE TITLE
New 3D import: Scene Importer doesn't generate static mesh when re-importing

### ISSUE THREAD

**Issue by Seubmarine** [godotengine/godot#49752]
### Godot version

v4.0.dev.custom_build [60dcc4f39]

### System information

Windows 10

### Issue description

Using the recent scene importer made by reduz, using "Mesh + Static Collider" on a mesh doesn't generate a staticbody as a child, it doesn't do anything or failed to do so, it doesn't look like a regression but something that never worked to begin with.

"Rigid body + Mesh" reset the scale of the root, the created RigidBody didn't get the transform correctly.

Tried on the latest branch 60dcc4f39c0e6289dba691225c002cd6e77be6ba and the one when the importer was first merged(97a3a6622).

I looked at the code source I think the issue is in "editor/import/ressource_importer_scene.cpp" line 624, the way it add a child or set the variable "base", mess up the process of creation of the StaticBody3D.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/48085383/122662972-61711580-d197-11eb-9833-edbc496efb3c.png)
go in blend_fille, and double click on test_exported_file.gltf, the importer should open, click on the mesh and in generate/physics select "Mesh + Static Collider" and click on re-import.

### Minimal reproduction project

[IslandDemo.zip](https://github.com/godotengine/godot/files/6681767/IslandDemo.zip)

**Comment by fire** [comment]
Fixed by by https://github.com/godotengine/godot/pull/50797?
