### ISSUE TITLE
Tree control relationship lines do not render properly when TreeItem custom background color is set

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#49755]
### Godot version

v4.0.dev.custom_build [9b0800cbf]

### System information

Win 10

### Issue description

See below, I was messing with the custom BG color of the tree in EditorSettings shortcuts. The dark blue and the red are set as custom BG colors.

![image](https://user-images.githubusercontent.com/41730826/122666488-dd4b7c00-d1f0-11eb-94e5-41a5aa0fd62d.png)

cc @pycbouh 

### Steps to reproduce

Have relationship lines turned on and use custom BG color on a tree item.

### Minimal reproduction project

None at the moment, might add later.

**Comment by pycbouh** [comment]
Can you make a theme with a copy of your Tree styles?

**Comment by EricEzaM** [comment]
I am just using `set_custom_bg_color`, default editor theme

**Comment by pycbouh** [comment]
Hmm, then I don't think this is related to the background color, as I didn't change render order. What may be a problem is that your tree has some non-selectable items around/as a parent of selectable items, which somehow breaks the lines. Does it?

**Comment by EricEzaM** [comment]
Nope, don't think so. Let me see if I can do an mrp

**Comment by EricEzaM** [comment]
[TreeCustomBG_MRP.zip](https://github.com/godotengine/godot/files/6682239/TreeCustomBG_MRP.zip)

Here you go

**Comment by pycbouh** [comment]
Just for the record, this issue exists in 3.3.2 as well, so it wasn't because of my recent changes.

[No custom background](https://user-images.githubusercontent.com/11782833/122768825-a5097380-d2ac-11eb-97bb-c27d17ae91ac.png)
[With custom background](https://user-images.githubusercontent.com/11782833/122768832-a63aa080-d2ac-11eb-9c53-80ae7954a5fe.png)

**Comment by EricEzaM** [comment]
Huh, ok, good to know.
