### ISSUE TITLE
Crash when extending a custom script from an embedded script

### ISSUE THREAD

**Issue by Eternahl** [godotengine/godot#49750]
### Godot version

4.0.dev (0a6a71973e)

### System information

Windows 10, Vulkan, Nvidia GTX 1080 TI (466.77)

### Issue description

Extending a custom script from an embedded script cause a crash

Here is the error log that i get when i run the scene:
```
ERROR: Condition "err" is true. Returning: err
   at: GDScript::load_source_code (modules\gdscript\gdscript.cpp:991)
```

Afterward, the same error happen if you try to open the scene in the editor, resulting by the crash of the editor

### Steps to reproduce

1. Create a _GDScript_
```
# parent.gd
extends Node
```

2. Create a scene and attach an embedded _GDScript_ inheriting from `parent.gd`.
```
# embedded in scene
extends "res://parent.gd"
```

3. Run the scene

### Minimal reproduction project

[issue-heriting-integrated-script.zip](https://github.com/godotengine/godot/files/6681122/issue-heriting-integrated-script.zip)

**Comment by lyuma** [comment]
Confirmed broken on latest master (85186bc)

However, instead of a crash, it seems to freeze when loading the scene (or assigning as main scene and running)
