### ISSUE TITLE
Regression: 48000 Hz .ogg file plays back in 44100 Hz in Godot 3.3.*

### ISSUE THREAD

**Issue by Benedani** [godotengine/godot#49759]
### Godot version

3.3 vs 3.2.3

### System information

Arch Linux x86_64, PulseAudio, 48000 Hz speakers/headset

### Issue description

48000 Hz .ogg files play back correctly on Godot version 3.2.3 and presumably previous versions.
On 3.3 and above, they are less clean, as if they were playing back at 44100 Hz.

This doesn't affect .wav files, but I'm not going to inflate the game's size just to not have worse audio on the newer version.

Interestingly, the project's Mix Rate setting doesn't affect results - a project configured at 44100 Hz plays back the file correctly on 3.2.3, and setting it to 48000 Hz doesn't fix it on 3.3+.

### Steps to reproduce

1. Open the example project in Godot 3.2.3.
2. Play the audio files back in the editor. They should sound the same.
3. Reopen it, this time using Godot 3.3.*.
4. Play the audio files back again. The ogg file should sound a tad muffled, while the wav file sounds the same as before.

This affects `AudioStreamPlayer`s too, obviously.

### Minimal reproduction project

[Literally just a project with the 2 audio files](https://github.com/godotengine/godot/files/6682493/eszo.zip)

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/49131.
