### ISSUE TITLE
RayCast still Detects Disabled CollisionShapes

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#49778]
### Godot version

4.0.dev

### System information

Linux Mint 20

### Issue description

Raycast's can detect a hit on a Physics Object CollsionShape even when the shapes is disabled.

### Steps to reproduce

Run the test project. Use the mouse to enter/exit the on-screen object. Toggle the CollisionShapes "disabled" property value.

### Minimal reproduction project

[Test_Project.zip](https://github.com/godotengine/godot/files/6683186/Test_Project.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.3.2?

**Comment by vonflyhighace2** [comment]
> Can you reproduce this on 3.3.2? Also, can you reproduce this in 2D?

After further testing. this seems to only affect 3D based raycasting. Can't seem to replicate it in 2D or with official 3.x build

**Comment by Houkime** [comment]
Cannot seem to replicate it in v4.0.dev.custom_build.a0d800e96
The provided script reports for an enabled shape but does not report for a disabled one.

**Comment by vonflyhighace2** [comment]
Yes, it seem to have been fixed with #49844 @Calinou @Xrayez.

**Comment by vonflyhighace2** [comment]
With that I'm going to close the issue now.
