### ISSUE TITLE
is_type_compatible: Parser bug

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#49779]
### Godot version

4.0.dev

### System information

Linux Mint 20

### Issue description

A Parser Bug in a for loop. This might also be a reference to issue #44375 and #48988

### Steps to reproduce

run the attached test project.

### Minimal reproduction project
[Test_Project_Parser_Bug.zip](https://github.com/godotengine/godot/files/6688230/Test_Project_Parser_Bug.zip)

**Comment by Chaosus** [comment]
Please fix the link to the attached zip file.

**Comment by vonflyhighace2** [comment]
not sure what happened there. I guess the upload was stuck? it should be fixed now

**Comment by vonflyhighace2** [comment]
can't reproduce in current master, so closing it.
