### ISSUE TITLE
Properties are locked after execution.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#49787]
### Godot version

3.3.2 stable oficial mono

### System information

w10 64

### Issue description

When you select a node you can edit its exported variables and properties.
Then run the scene.
Now the exported variables and node properties are locked.
To solve this, select another node and select the same node again.

In the gif you can see, for example, the "tick" option "gravity distance scale" was not blocked, but the others were.

![GIF](https://user-images.githubusercontent.com/19652075/122729750-ca30be80-d279-11eb-9cfe-1d819f880cbe.gif)

### Steps to reproduce

Select a node
execute scene
close the execution window
try change the node variables

**Comment by timothyqiu** [comment]
I saw this when I was tweaking `NavigationMesh`.

1. Create a `Navigation` node, and then a `NavigationMeshInstance` node as its child.
2. Create a new `NavigationMesh` for the node's `Navmesh` property in the Inspector.
3. Click the property value and expand the "Geometry" section, so you see two dropdowns.
4. Click "Bake Navmesh" on the toolbar.
5. Now at least one of the two dropdowns won't drop.

**Comment by Calinou** [comment]
Can you reproduce this in earlier Godot versions such as 3.2.3? You can download them [here](https://downloads.tuxfamily.org/godotengine/).

**Comment by timothyqiu** [comment]
I can reproduce this since 3.2.

**Comment by Torguen** [comment]
This does not happen in v3.5.beta1.official [b9b23d222]

**Comment by Torguen** [comment]
This does happen in v3.5.2.rc2.official [1a2bf3eb4]
