### ISSUE TITLE
Normalmap is too sharp with panorama sky.

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot#49788]
### Godot version

3.3 stable

### System information

Windows 10, GLES 3, Nvidia 1050 

### Issue description

Too clear normalmap at right angles (90 degrees) of illumination in the sky panorama mode of the world environment with HDRI texture. With default envinronment looks fine.
![godot2](https://user-images.githubusercontent.com/48552343/122734355-ac1d8b00-d286-11eb-9227-34609d658c40.png)
https://youtu.be/5hmJmKwBjlY

And another strange issue with the normalmap attached (another club on the scene), the reflections completely replace the albedo and it doesn't look natural. Everything looks correct in Blender and Substance painter. It seems to me that these problems are related, so I put them together in one issue. Although I'm not sure if these are errors, it still looks incorrect.

![SP](https://user-images.githubusercontent.com/48552343/122728451-d409f000-d280-11eb-9bd3-38de74a4f4d6.png)
![blender](https://user-images.githubusercontent.com/48552343/122728471-d8cea400-d280-11eb-8320-1f04815f592e.png)
![godot](https://user-images.githubusercontent.com/48552343/122732249-c35b7900-d284-11eb-8fc4-56e80df6b7e0.png)

### Steps to reproduce

in minimal reproduction project.

### Minimal reproduction project

[normalmap issue.zip](https://github.com/godotengine/godot/files/6685090/normalmap.issue.zip)

**Comment by Calinou** [comment]
Try decreasing the normal map intensity in Godot.

**Comment by Lexpartizan** [comment]
But then, where the angles are indirect normals will be almost invisible, since their intensity will be extremely low. And this problem is only in panorama sky mode.

**Comment by Calinou** [comment]
The material is configured to use a roughness of 0, which is very low. Consider increasing this value to 0.25 or so, or setting it to 1 and exporting a roughness map from Blender.

**Comment by Calinou** [comment]
I'm fairly sure this is happening because the normal map uses coordinates that are too strong.

**Comment by Lexpartizan** [comment]
Thanks. I change normalmap, this not problem.
What do you think about the fact that the normal map is too sharp at right angles of illumination with panorama sky? This is the main problem.

**Comment by Calinou** [comment]
> What do you think about the fact that the normal map is too sharp at right angles of illumination with panorama sky? This is the main problem.

The panorama sky you're using has much more variance in color compared to a basic ProceduralSky. I think the different normal map appearance is expected.

**Comment by Lexpartizan** [comment]
Thanks.

**Comment by Calinou** [comment]
@clayjohn Is there anything we need to document here?

**Comment by Calinou** [comment]
This was likely made less noticeable thanks to https://github.com/godotengine/godot/pull/51417, closing.

**Comment by clayjohn** [comment]
#51416 indeed makes a difference

Before:
![Screenshot (207)](https://user-images.githubusercontent.com/16521339/129500944-f0c104b4-eb04-4624-b930-82f3ebd1128c.png)

After:
![Screenshot (208)](https://user-images.githubusercontent.com/16521339/129500946-77364a3c-fc7c-4cb8-9368-b4ae71ec5908.png)

**Comment by Lexpartizan** [comment]
Thanks!
