### ISSUE TITLE
Holding Control key + Left click return wrong ButtonIndex 

### ISSUE THREAD

**Issue by AbanoubNassem** [godotengine/godot#49790]
### Godot version

v3.3.2.stable.mono.official

### System information

Mac BugSir + OpenGL ES 3.0 Renderer: NVIDIA GeForce GT 650M OpenGL Engine

### Issue description

Holding `control` key + `left` click , the `InputEventMouseButton.ButtonIndex` is `2` it should be `1` since it's left click 

### Steps to reproduce

```
public override void _UnhandledInput(InputEvent e)
{
bool isMouseInput = e is InputEventMouseButton;
if (isMouseInput)
{
var mouseInput = e as InputEventMouseButton;
//hold control key + left click , it should be 1 but it gives 2
GD.Print(mouseInput.ButtonIndex);
}
}

```

**Comment by timothyqiu** [comment]
Control-Click on this page in your browser, and you'll get the context menu.

Control-click is the [equivalent](https://support.apple.com/guide/mac-help/right-click-mh35853/mac) of Right click on macOS.

**Comment by AbanoubNassem** [comment]
> Control-click on this page in your browser, and you'll get the context menu.
> 
> Control-click is the [equivalent](https://support.apple.com/guide/mac-help/right-click-mh35853/mac) of Right-click on macOS.

I have tested it on windows as well, does windows have similar behavior?!

**Comment by Calinou** [comment]
> I have tested it on windows as well, does windows have similar behavior?!

No, this is macOS-only behavior that was added to accomodate for some mice having only one button.

**Comment by AbanoubNassem** [comment]
My bad since I was running the Engine through Virtual Machine it was still registered as Right click, tested on a Windows PC , it works fine.
