### ISSUE TITLE
rendering quality is bad when html5 export

### ISSUE THREAD

**Issue by uuuuuup** [godotengine/godot#49794]
### Godot version

3.3 stable

### System information

UBUNTU, GLES3

### Issue description

When I set canvasResizePolicy: 0, rendering quality is bad.
Default canvas rect size is too small (300x150) and it is not updated.
So I changed as below. Is it correct change?

```
diff --git a/platform/javascript/js/libs/library_godot_display.js b/platform/javascript/js/libs/library_godot_display.js
index affae90370..23f8977125 100644
--- a/platform/javascript/js/libs/library_godot_display.js
+++ b/platform/javascript/js/libs/library_godot_display.js
@@ -584,6 +584,9 @@ const GodotDisplayScreen = {
                        let width = wwidth;
                        let height = wheight;
                        if (noResize) {
+                               const canvasRect = canvas.getBoundingClientRect();
+                               canvas.width = canvasRect.width;
+                               canvas.height = canvasRect.height;
                                // Don't resize canvas, just update GL if needed.
                                if (canvas.width !== width || canvas.height !== height) {
                                        GodotDisplayScreen.desired_size = [canvas.width, canvas.height];

```

### Steps to reproduce

1. set canvasResizePolicy to 0
2. run in browser

**Comment by Calinou** [comment]
Since Godot 3.3, the HTML5 export follows the same hiDPI policy as Windows and macOS. Enable **Allow Hidpi** in the Project Settings to make rendering more crisp on hiDPI displays, at the cost of greater GPU usage.

**Comment by uuuuuup** [comment]
I mean... even though canvas size is changed, renderer size? is not updated. it remains 300 x 150. It is just scaled. 
When canvasResizePolicy is 1 or 2, there is no problem.

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
`canvasResizePolicy: 0` means no resizing. I.e. Godot will not touch the canvas.
You have to set the canvas size yourself via JavaScript. It that's not what you want, use a different canvas resize policy.

**Comment by uuuuuup** [comment]
Hi @Faless 

My web page contains header, footer, and other elements. Canvas is one of them.
Of course, I manually set the canvas size with 100% in JavaScript.

In case canvasResizePolicy is 0,
  Canvas size is 100% size. It is not problem.
  BUT, rendering resolution is always 300 x 150, so it shows blurred image.

In case canvasResizePolicy: 1,
  Canvas size is the same as window size set in project setting.
  So, I cannot use it.

In case canvasResizePolicy: 2,
  Canvas size is the same as browser window size.
  Canvas is drawn on the header and footer.
  So, I cannot use it.

Do you think my usage is wrong? Then, how to use it?

> `canvasResizePolicy: 0` means no resizing. I.e. Godot will not touch the canvas.
> You have to set the canvas size yourself via JavaScript. It that's not what you want, use a different canvas resize policy.

**Comment by Calinou** [comment]
> BUT, rendering resolution is always 300 x 150, so it shows blurred image.

What stretch mode are you using in the Project Settings? If you're using the `viewport` stretch mode, this is expected.

**Comment by uuuuuup** [comment]
I used default mode. "disabled"

**Comment by uuuuuup** [comment]
I have a question. In the code that I attached.
                                // Don't resize canvas, just update GL if needed.
                                if (canvas.width !== width || canvas.height !== height) {
                                        GodotDisplayScreen.desired_size = [canvas.width, canvas.height];

I think it should be called at least once. But it never called.
I printed log and the result is as below.
canvas.width == 300, width == 300,  canvas.height == 150, height == 150.

**Comment by Calinou** [comment]
Sounds like a floating-point precision issue. @Faless Should we use an epsilon value for the comparison?

**Comment by Faless** [comment]
> Of course, I manually set the canvas size with 100% in JavaScript.

You are probably confusing canvas size and css size. You can't use percentages in canvas size.
I can't really help much without knowing the HTML used.

> Sounds like a floating-point precision issue.

Canvas `height` and `width` [are integers](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/height)

**Comment by uuuuuup** [comment]
Oh, I see. Now, I understand what you mean and the concept.
For responsive web, I usually use css size with percentage, not width and height property.
I thought that canvas css size : render size = 1 : 1 would be better.
Anyway, thanks.

**Comment by Faless** [comment]
>  I thought that canvas css size : render size = 1 : 1 would be better.

Not for canvas, they work a bit different then other elements.

And what you want is [`size / css_size = devicePixelRatio`](https://www.html5rocks.com/en/tutorials/canvas/hidpi/).

**Comment by uuuuuup** [comment]
Thanks for the information. :)

> And what you want is [`size / css_size = devicePixelRatio`](https://www.html5rocks.com/en/tutorials/canvas/hidpi/).
