### ISSUE TITLE
Variable selection by double click is separated by underscores in code editor

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#49796]
### Godot version

v4.0.dev.custom_build [9da7f0690]

### System information

Windows 10, Vulkan, GeForce GTX 1080Ti (456.71)

### Issue description

Variable selection by double click is separated by underscores in code editor. I don't know if this is intended but it's super counterintuitive. In addition, selection by double click is not possible for variables with only one letter.
![variable_selection](https://user-images.githubusercontent.com/28705694/122763410-e3188e80-d2d0-11eb-936d-e8d48a904b34.gif)

### Steps to reproduce

Select a variable with underscores by double click in code editor.

### Minimal reproduction project

No need.

**Comment by Zireael07** [comment]
Search the issues first - you would have seen yesterday's issue #49769 which itself is a dupe of https://github.com/godotengine/godot/issues/46380

**Comment by floppyhammer** [comment]
@Zireael07 I tried but had no luck.
