### ISSUE TITLE
CSGCylinder3D has incorrect normals compared to the CylinderMesh primitive

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#49800]
*See also https://github.com/godotengine/godot/issues/19143.*

### Godot version

4.0.dev (6d98f84ab), 3.3.2

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

CSGCylinder3D has incorrect normals compared to the CylinderMesh primitive.

CSGTorus3D also has unexpected normals compared to a torus exported from Blender (due to a sharp line in the middle), but it's not as bad.

*Top: CSG nodes (torus, box, sphere, cylinder) or meshes (Suzannes, sharp cylinder).
Bottom: MeshInstances with primitive meshes (box, sphere, smooth cyulinder) or OBJs exported from Blender (torus, Suzannes, sharp cylinder).*

![image](https://user-images.githubusercontent.com/180032/122776786-b43bf180-d2ab-11eb-85a9-41deda5e22e6.png)

This also occurs on 3.3.2. CSGCylinder on top, MeshInstance with CylinderMesh at the bottom:

![image](https://user-images.githubusercontent.com/180032/122777777-a76bcd80-d2ac-11eb-8682-d6df64ed5bbb.png)

### Steps to reproduce

- Create a CSGCylinder node and set the number of sides to 64 to match a CylinderMesh.
- Create a MeshInstance node, add a CylinderMesh to it.
- Place the MeshInstance above/below the CSGCylinder and compare the lighting on both.

### Minimal reproduction project

- `master`: [test_csg_normals.zip](https://github.com/godotengine/godot/files/6687192/test_csg_normals.zip)
- `3.x`: [test_csg_normals_3.x.zip](https://github.com/godotengine/godot/files/6687266/test_csg_normals_3.x.zip)

**Comment by devvoid** [comment]
CSGSphere has the same issue.

Taking a guess, this might be the CSG models not having merging vertices that share the same coordinates - you get similar errors in Blender if you use the spin modifier to make a circular object, but disable "Auto Merge". I've included an exported model in my test project to show what I mean.

From top to bottom: CSGSphere, MeshInstance sphere, UV sphere from Blender (made with the spin modifier, Auto Merge disabled).

![Screenshot from 2021-07-13 23-41-58](https://user-images.githubusercontent.com/33298798/125562385-2b60778b-c81d-40f7-9d43-2226adc2185a.png)

[CSGSphereNormals.zip](https://github.com/godotengine/godot/files/6813525/CSGSphereNormals.zip)

**Comment by unfa** [comment]
I have the same issue. Here's how the shading looks after subtracting a CSG cylinder from a block:

![Clipboard - December 15, 2021 11_06 PM](https://user-images.githubusercontent.com/491704/146377782-68c36418-78c4-40a4-a9f3-30475264d764.png)

**Comment by unfa** [comment]
I suspect this is what's going on:
The CSG cylinder's curved shell's normals point away from the whole object's origin, rather than from the center of a ring of vertices they belong to (top or bottom).

Here's an illustration of what I suspect is going on:

![Screenshot_20211216_141626](https://user-images.githubusercontent.com/491704/146379599-c854751a-8a73-4fee-9547-6a737e5cb56a.png)

Of course the normals are split on edges with the flat top and bottom faces, but I'm omitting these as they appear to be correct.

I have no idea how the code looks like, but maybe this is enough to help fix it?

**Comment by Calinou** [comment]
I looked briefly at fixing this, but it appears the CSG shape's normals are automatically generated with no way to manually override them: https://github.com/godotengine/godot/blob/73ece5ba1962eb3c19ac529b8cb4ac18aefd5cac/modules/csg/csg_shape.cpp#L384-L397
