### ISSUE TITLE
Boot splash on Windows and Android are not scaled equally

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#49816]
### Godot version

3.3.2 stable

### System information

Win 64

### Issue description

![image](https://user-images.githubusercontent.com/47016402/122835772-47e3e100-d2f1-11eb-93e8-b9dbd854a84a.png)

A) If "Fullsize" is enabled, the boot splash graphic will correctly resize on Windows, but on Android the boot spash graphic will show up miniaturized, like an icon.

B) If "Fullsize" is disabled, the boot splash graphic will not be resized on Windows (therefore if the graphic is bigger than the project resolution the graphics will be cut off), but on Android the boot splash graphic will show up correctly (possibly due to the much higher native screen resolution on the phone. At any rate, it won't show up miniaturized)

Expected behavior would be if "Fullsize" is enabled (A), for the splash graphic to on android not to be miniaturized but look like it does in (B).

### Steps to reproduce

1: Create a project with a project resolution of something like 360 width 780 height, stretch mode: 2D
2: Add this test graphic as boot splash graphic:

![icon_boot_splash](https://user-images.githubusercontent.com/47016402/122837537-8af38380-d2f4-11eb-85bc-afef981b8860.png)

3: Run project in Windows and Android phone with and without "Fullsize" setting enabled.

**Comment by Calinou** [comment]
hiDPI scaling for splash screen is only implemented on Android and iOS (which use native OS drawing code). On other platforms, it must be done manually by the engine.

**Comment by m4gr3d** [comment]
@Calinou @golddotasksquestions The option (quick) option would be to move the boot splash scaling option to the export configs since we don't expect similar behavior between PC/mobile platforms.
Let me know what you think.

**Comment by boruok** [comment]
@golddotasksquestions did you found any workaround since then? I got same issue on Godot 3.5 beta 3

**Comment by golddotasksquestions** [comment]
@boruok Unfortunately, no, I have not.

**Comment by m4gr3d** [comment]
Resolved in Godot 4.3 via https://github.com/godotengine/godot/pull/92965.
