### ISSUE TITLE
Bug in nightly build installer/error . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot#49821]
### Godot version

4.0 dev

### System information

Windows 10 . .

### Issue description

I get an error message in the installer, is it a problem . .

<img width="661" alt="Skærmbillede (1898)" src="https://user-images.githubusercontent.com/83387915/122858308-5c889f00-d31a-11eb-8332-acd621330015.png">

Also, might be dumb question, do you want people to report bugs in Godot 4 dev, or wait until alpha . . . Am a total beginner, and not sure what it means, to code an engine <3 . . . Does it make sense to report bugs now, or would you rather, that people wait, thx . . <3

### Steps to reproduce

Uhh, it's from the installer, not sure if it matter, ie. it'll cause problems . . Maybe it's bec. the ' Path ' is write-only, not sure . . . .

### Minimal reproduction project

Well, not sure others have this issue, it's from the installer, might cause ' crash </3 . . .

**Comment by Calinou** [comment]
The setup is a third-party program, it is not part of an official build. I recommend using the ZIP archive instead.
