### ISSUE TITLE
The modulation argument of CanvasItem.draw_mesh does not work.

### ISSUE THREAD

**Issue by groud** [godotengine/godot#49824]
### Godot version

4.0dev (0638ca00373a7fb9e0c114ccc43eae7a17f6f61d)

### System information

Arch Linux

### Issue description

When drawing a mesh inside a CanvasItem the modulation argument is not taken into account.

### Steps to reproduce

Create a Node2D with this script:
```gdscript
extends Node2D

var texture := load("res://icon.png")
var mesh := ArrayMesh.new()
var a = []

func _init():
	a.resize(Mesh.ARRAY_MAX)
	a[Mesh.ARRAY_VERTEX] = PackedVector2Array([Vector2(0, 0), Vector2(100, 0), Vector2(0, 100)])
	a[Mesh.ARRAY_TEX_UV] = PackedVector2Array([Vector2(0, 0), Vector2(1, 0), Vector2(0, 1)])
	a[Mesh.ARRAY_COLOR] = PackedColorArray([Color(1,1,1), Color(1,1,1), Color(1,1,1)])
	a[Mesh.ARRAY_INDEX] = PackedInt32Array([0, 1, 2])
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, a, [], {}, Mesh.ARRAY_FLAG_USE_2D_VERTICES)
	
func _draw():
	# Draw without texture
	draw_mesh(mesh, null, Transform2D(), Color(1, 0, 0, 1))
	
	# Draw sith texture
	var xform := Transform2D()
	xform.origin = Vector2(0, 100)
	draw_mesh(mesh, texture, xform, Color(1, 0, 0, 1))
```
This results in this:
![2021-06-22-102032_1047x618_scrot](https://user-images.githubusercontent.com/6093119/122889912-84402d00-d343-11eb-98bf-66a5115fb0be.png)
Both of those should be tinted red as the modulation argument suggests.

### Minimal reproduction project

[Mesh2DNoModulation.zip](https://github.com/godotengine/godot/files/6692531/Mesh2DNoModulation.zip)

**Comment by insomniacUNDERSCORElemon** [comment]
Was already reported at issue #49781.  As I mention in the comments, it is broken for polygon2d and line2d nodes as well, textured+textureless+vertex colors (vertex colors getting the most benefit for an *individual* node due to a more due to a complex setup that cannot be changed as easily as colors or textures).

They also say:

> Reduz suggested that it might be intended, because the way it works has changed. In that case, it's a documentation issue about how it can be achieved now.

Although yes hopefully this can be fixed.

**Comment by groud** [comment]
Ah, so the issue has several consequences then, good to know.

**Comment by insomniacUNDERSCORElemon** [comment]
Is there a difference between the 2 issues you posted? Does the pull request you made fix the other situations, or is it a minor fix and that's why you assigned reduz on this issue?

**Comment by groud** [comment]
> Is there a difference between the 2 issues you posted? Does the pull request you made fix the other situations, or is it a minor fix and that's why you assigned reduz on this issue?

You mean https://github.com/godotengine/godot/issues/49825 ? It is an unrelated issue. I just reused the mesh drawing code as steps to reproduce as both issues happen using draw_mesh.
