### ISSUE TITLE
[Workflow] Copying properties between nodes is a cumbersome process

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#49830]
### Godot version

v4.0.dev.custom_build [085e1d3c0]

### System information

manjaro linux Gnome

### Issue description

For example if you have a lot of nodes, and need to make them same position you have to copy each axis's value manually:

![image](https://user-images.githubusercontent.com/58845030/122926287-12b1b000-d33e-11eb-9a44-ecdaebf1710f.png)
For transform:
* Copy X from Node A
* Paste X in Node B
* Copy Y from Node A
* Paste Y in Node B
* Copy Z from Node A
* Paste Z in Node B

and so on for another properties.

**The Solutions**

* Add a "COPY ALL PARAMS"
* Add a "PASTE ALL PARAMS" (where the values matches they'll pasted)
* Add a "COPY" foreach parameter (you may need to copy only position i.e)
* Add a "PASTE" foreach parameter

Obs: This should be possible for every existing Propertie in the engine, some has this option already like materials.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by nonunknown** [comment]
One of the proposals are more than a year old, the other almost. But there's no 4.0 milestone for that :(

**Comment by Calinou** [comment]
> But there's no 4.0 milestone for that :(

Milestones are only added for features that are very likely to be added to a given release. All other features depend on contributors' goodwill to implement them :slightly_smiling_face:

**Comment by nonunknown** [comment]
oh ok then!
