### ISSUE TITLE
Tileset scaling: big tiles make it unusable

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4983]
The preview of the tileset in the tilemap editor was recently improved by @Hinsbart and @bojidar-bg, to make it possible to zoom in and out, which is great.

If you test [this level of Jetpaca](https://github.com/KOBUGE-Games/jetpaca/blob/master/stages/world_1/forest_fun.tscn) though, you will see that it can become very unwieldy if there is a tile that is disproportioned compared to the others:

![spectacle g10877](https://cloud.githubusercontent.com/assets/4701338/15736141/ebec144c-289d-11e6-9e04-b032a7846024.png)

I think the tileset preview should use its width as a limiting factor for each tile's scaling. When iterating over all tiles to set their dimensions corresponding to the current zoom factor, if the calculated dimensions are wider than the panel width, we should set the preview of this tile to a custom zoom factor corresponding to the panel width. Other smaller tiles should still be able to be scaled up and down independently of this limiting tile (if possible, even allowing to keep this big tile on a single column even when the smaller tiles start being stacked on several columns at low zoom factors).

**Comment by Hinsbart** [comment]
Mhh, the tileset palette uses an `ItemList` internally, which is a general purpose class used all over the place. So modifying it to get the tileset right can result in bugs elsewhere as seen in #4907.
Maybe ItemList should have something like a "Tileset Mode/Flag", so we don't have to worry about breaking things.

**Comment by reduz** [comment]
seems ItemList broke recently though, have to give it a check. I was thinking of adding a "zoom" option to it though

**Comment by reduz** [comment]
nevermind, seems zooms was already added, i will just limit the icon size here
