### ISSUE TITLE
Package x11 was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by abueide** [godotengine/godot#49842]
### Godot version

4.0.dev (277db14b647d3184b341a359020c0acc4549afaf)

### System information

NixOS Gnome 40 X11, RTX 3080

### Issue description

default-chrootenv:andrew@nixos:~/programming/projects/game/godot$ scons p=linuxbsd -j8 tools=yes module_mono_enabled=yes mono_glue=no
scons: Reading SConscript files ...
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Invalid target platform "linuxbsd".
The following platforms were detected:

Please run SCons again and select a valid platform: platform=<string>
default-chrootenv:andrew@nixos:~/programming/projects/game/godot$ exit
exit

### Steps to reproduce

install prerequisite packages for building on NixOS:
```
scons
msbuild
dotnetPackages.Nuget
pkg-config
```

perform build:
`scons platform=linuxbsd`

### Minimal reproduction project

Not needed

**Comment by akien-mga** [comment]
You need to install the X11 development libraries. See https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html

**Comment by Calinou** [comment]
It would be nice if we could tell people to install dependencies explicitly, but I don't see a way to append or override the SCons pkg-config error messages.

**Comment by akien-mga** [comment]
I think it's fairly explicit already:

> Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found

This requires some knowledge of pkg-config / compiling C++ software against system package on a given distro, but making this more accessible is difficult. That's the role of the https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html documentation (which could benefit from a one-liner for NixOS I suppose).

**Comment by abueide** [comment]
@akien-mga @Calinou 
yeah sorry I didn't remember installing everything when I was on other distros presumably because it came with the distro. I should have definitely looked at the docs first.

On the other hand I'm still running into some issues building with nix on macos. Do you guys know how I could point scons/pkg-config to the macos header files?

Currently I have a list of paths that contain the frameworks & headers that scons needs (they're in a nonstandard location because of how nix stores packages in /nix/store/somepackagehash), but I don't know how to make it pick them up so I keep getting these errors:

```
In file included from platform/osx/power_osx.cpp:56:
platform/osx/power_osx.h:38:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from platform/osx/os_osx.mm:31:
In file included from platform/osx/os_osx.h:38:
./drivers/coreaudio/audio_driver_coreaudio.h:38:10: fatal error: 'AudioUnit/AudioUnit.h' file not found
#include <AudioUnit/AudioUnit.h>
```

Here are the paths to the frameworks I somehow need to include in the build:
```
/nix/store/s3xd4rqawdc14g5nhmlxzijxl8dd6fdg-apple-framework-AppKit 
/nix/store/781yy6vfk84fjxa71ddn7nlcsklh7wvs-apple-framework-AudioUnit 
/nix/store/yn6ahk09b7xb9r45cl3jvgww7i4sn1mc-apple-framework-CoreFoundation /nix/store/559qk5ycrc6zcxzwxfjv84gjyb94383k-apple-framework-CoreAudio 
/nix/store/k4wdvbk54rzz1wc08wanvmbvkv8zb8a1-apple-framework-IOKit
```

Here is an example path to one of the missing header files: 
`platform/osx/power_osx.h:38:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found`
`/nix/store/yn6ahk09b7xb9r45cl3jvgww7i4sn1mc-apple-framework-CoreFoundation/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h`

**Comment by akien-mga** [comment]
I'm not familiar with Nix as a package manager but you probably need to make its store paths part of system include paths, or pass them manually to the compiler. I would suggest asking in Nix / macOS communities to know what's the proper way to expose Nix-installed frameworks to applications that need them for compilation.

**Comment by abueide** [comment]
ah so there's no easy way to just add the paths to pkg-config or scons somehow so it can pick up the header files? I have tried asking in the nixos community, but haven't had any luck so far.

**Comment by bruvzg** [comment]
macOS build expect full macOS SDK. On macOS it's auto-detected by running `xcrun --sdk macosx --show-sdk-path` command, on cross builds it should be specified in the `OSXCROSS_ROOT` environment variable (it's passed as `-isysroot` to the compiler). No `pkg-config` or any other similar tools are used.

**Comment by akien-mga** [comment]
You can try to pass to `CCFLAGS` in the environment:
```
scons p=osx ... CCFLAGS="-I/nix/store/s3xd4rqawdc14g5nhmlxzijxl8dd6fdg-apple-framework-AppKit -I..."
```

But I don't have high hopes as it seems e.g. `CoreFoundation.h` is not packaged as `CoreFoundation/CoreFoundation.h` as expected by Godot code and system headers, so unless macOS clang can do some magic remapping of framework paths, it might be tricky.

**Comment by bruvzg** [comment]
> CoreFoundation.h is not packaged as CoreFoundation/CoreFoundation.h

```
├── CoreFoundation.tbd -> Versions/Current/CoreFoundation.tbd
├── Headers -> Versions/Current/Headers
├── Modules -> Versions/Current/Modules
└── Versions
    ├── A
    │   ├── CoreFoundation.tbd
    │   ├── Headers
    │   │   ├── CFArray.h
    │   │   ├── ...
    │   │   └── CoreFoundation.h
    │   └── Modules
    │       └── module.modulemap
    └── Current -> A
```

It's packaged in the same way macOS SDK do.
Framework search path can be set with `-F/path/to/framework`, which probably should be added to both CCFLAGS and LINKFLAGS.
