### ISSUE TITLE
Round object gets stuck in collider's edges

### ISSUE THREAD

**Issue by zerornull** [godotengine/godot#4984]
Round object gets stuck in collider's edges.

Here's a video example:
https://www.youtube.com/watch?v=J9QF2MKqJ4o

Example project that reproduces the bug:
https://www.dropbox.com/s/4olxg0848qkgo1p/CollisionBug.zip?dl=0

With CollisionPolygons:
https://www.dropbox.com/s/fvrdfucq4vg9ci8/CollisionBug%28Polygons%29.zip?dl=0

Godot 2.0.3 stable

**Comment by akien-mga** [comment]
Could you provide an example project that reproduces the bug? With only this video, it's not possible to define whether it's a bug in your own project or an engine bug.

**Comment by zerornull** [comment]
Here's an example project:
https://www.dropbox.com/s/4olxg0848qkgo1p/CollisionBug.zip?dl=0

**Comment by kubecz3k** [comment]
@zerornull would be the best to attach example as an attachment to the issue (dropbox links after some time might stop working).

**Comment by zerornull** [comment]
@kubecz3k The link wouldn't work only if file would be deleted.

**Comment by zerornull** [comment]
@kubecz3k Attached.

**Comment by zerornull** [comment]
@akien-mga Same happens with collision polygons:
https://www.dropbox.com/s/fvrdfucq4vg9ci8/CollisionBug%28Polygons%29.zip?dl=0

**Comment by zerornull** [comment]
Another physics bug: https://www.youtube.com/watch?v=o4RWyBUmi1o
Using set_pos to move platform.

**Comment by reduz** [comment]
seems like a bug indeed

**Comment by reduz** [comment]
I will rewrite the collision code for 3.0, so for now putting this on hold
