### ISSUE TITLE
Vulkan: StandardMaterial3D specular modes are off by one

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#49841]
### Godot version

4.0.dev (6d98f84ab)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

StandardMaterial3D specular modes are off by one compared to what you configure in the inspector.

From left to right, I configured the spheres to use **Toon**, **Phong**, **Blinn** and **SchlickGGX**.

However, from left to right, they *appear* to be **Disabled**, **Toon**, **Phong**, (**Blinn** or **SchlickGGX**). There's likely an off-by-one error in the shader since [parts of it were removed for performance reasons](https://github.com/godotengine/godot/pull/45023).

![image](https://user-images.githubusercontent.com/180032/123000146-7922e680-d3af-11eb-82cb-3229a45db98b.png)

### Steps to reproduce

Create StandardMaterial3D, set the albedo to black and tweak the specular mode.

### Minimal reproduction project

`tests/3d/test_standard_material_3d_opaque.tscn` from https://github.com/Calinou/godot-rendering-tests

**Comment by clayjohn** [comment]
This was fixed at some point! I can't reproduce in RC3
