### ISSUE TITLE
Adding new functions to visual script when zoomed out places them ' badly ' . . 

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot#49840]
### Godot version

Godot 3.3 . .

### System information

Windows 10

### Issue description

Had this problem many times before, when zoomed out, dragging a new function, or variable, it is placed wrong . . .

![2021-06-22 2238](https://user-images.githubusercontent.com/83387915/122996002-9e612600-d3aa-11eb-8a8c-3b16de194e92.gif)

Now, visual script is looking mint, really cool . . These are some of last small bugs, only happens when zoomed out, it's a minor bug, but it does get annoying, esp. now Godot 4 appears to look better when zoomed out ( I have a custom font, but it's small, and still very readable, zoomed out ) . . It's like, are there any bugs left in visual script ?? Super - happy with the feature, atm, thx . . . :OO . . .

### Steps to reproduce

Uhhh, make a new visual script, make a variable, or new function . . Move it in, normal zoom, it just works, the more one zooms out, worse it gets . .

It's not really a bug, it's just bit annoying, and weird . . Anyway, Godot 4 Visual script is just amazing, nothing much left to complain about, except small bugs, like this, thx . . . .

### Minimal reproduction project

Uhh, just like above . . .

**Comment by Xrayez** [comment]
It looks to me that zooming/transform is not taken into account when placing new nodes.

**Comment by charlesmlamb** [comment]
Yea, sometimes it's quite far, it's like the script has a center, and it pulls nodes toward it, not sure . .

Well, that's the last bug I know, from user experience . .

Down to nit-picking, after Godot 4, I have no more proposals, just the 'dang' wait <3 . .
