### ISSUE TITLE
"UnicodeDecodeError" when compiling Godot 3.3.2 with SCons 4.0.1

### ISSUE THREAD

**Issue by Infi-power** [godotengine/godot#49850]
### Godot version

3.3.2 (7610409) (installed source code as .zip file)

### System information

Windows 10 Pro 64 bits

### Issue description

_(This is my first time to compile this engine, so if I did any mistakes while trying compiling, then don't hesitate to tell me what I did wrong!)_

--------
I was trying to add custom module to Godot engine and compiling it. I installed Python 3.9, tdm-gcc 10.3.0-2 and SCons 4.0.1. After that, I downloaded Godot 3.3.2 branch into a folder and moved that folder to my main (C:\) drive.

When I tried to compile without extra modules, I got this error:
![image](https://user-images.githubusercontent.com/75531788/123063144-d5205600-d415-11eb-806c-f6395d60d649.png)

I removed this line from SConstruct file:
`EnsureSConsVersion(0, 98, 1)`

But still, it didn't worked, and also got same error at a different line:
![image](https://user-images.githubusercontent.com/75531788/123063910-7d361f00-d416-11eb-9f3d-8c29f401853d.png)

I checked SCons and Python versions, and here is the result:
![image](https://user-images.githubusercontent.com/75531788/123064477-f9c8fd80-d416-11eb-8709-722936d65393.png)

### Steps to reproduce

- Install Python 3.9, tdm-gcc 10.3.0-2 and SCons 4.0.1.
- Download Godot Engine 3.3.2 source code.
- Try compiling engine with `platform=windows` argument or list available platforms using `platform=list`.

### Minimal reproduction project

Not available.

**Comment by akien-mga** [comment]
The error makes it sound like there's an encoding problem on your `SConstruct`. How did you retrieve the source code? Can you check what encoding is used in the file you have locally? It must be UTF-8 to work properly.

**Comment by bruvzg** [comment]
Since it's the first call of `Environment()` in the SCons file, it's probably failing to parse some of the environment variables with non UTF-8 characters.

Run `set` command to list variables and check if there's any with non-Latin text (it's probably something in the path).

**Comment by Infi-power** [comment]
> The error makes it sound like there's an encoding problem on your `SConstruct`. How did you retrieve the source code? Can you check what encoding is used in the file you have locally? It must be UTF-8 to work properly.

I retrieved source code from there as .zip file:

![image](https://user-images.githubusercontent.com/75531788/123090467-d57a1a80-d430-11eb-8cc9-abfaa31c7671.png)

And, I also checked that `SConstruct` file is encoded in UTF-8:
![image](https://user-images.githubusercontent.com/75531788/123090624-0a866d00-d431-11eb-8155-f64ae634f1d5.png)

**Comment by Infi-power** [comment]
> Since it's the first call of `Environment()` in the SCons file, it's probably failing to parse some of the environment variables with non UTF-8 characters.
> 
> Run `set` command to list variables and check if there's any with non-Latin text (it's probably something in the path).

I ran `set` command, and I checked every single file path and I can't find any non-Latin character.

---
I have another computer, I will try to compile engine from that computer.

**Comment by Calinou** [comment]
Can you reproduce this from a WSL (WSL1 or WSL2) installation?

**Comment by Infi-power** [comment]
Now it works successfully when using `platform=list` argument!

![image](https://user-images.githubusercontent.com/75531788/123127735-39153f80-d453-11eb-9bd2-596e28a359b9.png)

Now I need to compile it for windows.

**Comment by Infi-power** [comment]
I started compiling process, I will edit this post when engine compiled successfully.

**Comment by Infi-power** [comment]
Finally, I compiled the engine, Thanks for your help!

**Comment by antsuke42** [comment]
This seems relevant: https://github.com/SCons/scons/issues/4011
