### ISSUE TITLE
Gyroscope/Accelerometer of Switch Pro Controller and PS5 Dual Sence is not supported

### ISSUE THREAD

**Issue by NicholasShatokhin** [godotengine/godot#49852]
### Godot version

3.3.stable

### System information

Windows 10, Ubuntu 20.10

### Issue description

On the modern consoles like Nintendo Switch and PS4/PS5 you can aim in shooting games using gamepad MEMS sensors.
But Godot doesn't allow to do it.

### Steps to reproduce

1. Go to Input tab of project properties
2. Add new input command
3. Assign gamepad input for it
4. Check that there are no gyroscope and accelerometer axises in the input options.

**Comment by Xrayez** [comment]
Since Godot never supported these kind of features, it looks like a feature request to me, for which there's an existing proposal: godotengine/godot-proposals#2829.
