### ISSUE TITLE
Translation snap with local coordinates activated behaves incorrect

### ISSUE THREAD

**Issue by guzzard** [godotengine/godot#4985]
**Operating system or device - Godot version:**
Tested in Arch Linux with Godot version 2.0.3 stable and git master

**Issue description** (what happened, and what was expected):
Translation snap with local coordinates activated behaves incorrect.
![2016-06-02_09-12-15](https://cloud.githubusercontent.com/assets/9007314/15736848/d6d8369e-28a2-11e6-8b46-cece4ceea92b.gif)

**Steps to reproduce:**
- Rotate an object to an arbitrary rotation
- Activate translation snap, for example 5
- Activate local coordinates
- Move the object

**Comment by reduz** [comment]
Is this really a bug? I seriously have no idea how translation snap should work with local coordinates..
Where's the origin?

**Comment by guzzard** [comment]
@reduz have a look at Blender, Maya, Unity, UE4 or AtomicGameEngine. Translation snap with local coordinates is working fine in all of those applications. Since source code is available in several cases it should be possible to get some clue how to implement it in Godot.

**Comment by reduz** [comment]
i guess I'll just create a custom origin using only the matrix basis, can't think of a better way to implement it

**Comment by bojidar-bg** [comment]
Well, if it is in local coordinates, then snap should probably be local to the object's position, no?
