### ISSUE TITLE
HTTP server for HTML5 does not serve the project if there are url parameters

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#49868]
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

I would like to have URL parameters fed into the html5 export of the game, like this:

`http://localhost:8060/tmp_js_export.html?test=true`

but when there is a url parameter, the debug server 404s

### Steps to reproduce

1. Launch godot project in the web
2. Add url parameter (like `?test=true`) to the url
3. The project will not be served

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
Can you expand on why you need the url parameter?

**Comment by Calinou** [comment]
> Can you expand on why you need the url parameter?

It's useful to test `OS.get_cmdline_args()` locally. I will probably need this for [GDScript Online](https://github.com/Calinou/gdscript-online/) at some point :slightly_smiling_face:

**Comment by Faless** [comment]
> It's useful to test `OS.get_cmdline_args()` in HTML5 locally. I will probably need this for [GDScript Online](https://github.com/Calinou/gdscript-online) at some point slightly_smiling_face

I don't get it, `OS.get_cmdline_args()` are not derived from the query string....

**Comment by creikey** [comment]
> Can you expand on why you need the url parameter?

Small amounts of sharable user-created game data without the need for a server, like a `?data=fa2fwie` parameter which is just base64 encoded json text

**Comment by Faless** [comment]
> Small amounts of sharable user-created game data without the need for a server, like a `?data=fa2fwie` parameter which is just base64 encoded json text

In that case you should not use the query parameter, but the `#` fragment.
