### ISSUE TITLE
Initializing a `const vec2[]` in a shader's global scope gives error `Expected initialization of constant`

### ISSUE THREAD

**Issue by ErnestoBorio** [godotengine/godot#49867]
### Godot version

3.2.3.stable

### System information

MacOS 10.15.7 build 19H1217, AMD Radeon Pro 5300M, GLES3 

### Issue description

When I try to declare a global const array in a shader whose elements are vec2 or vec3, I get the error `Expected initialization of constant`.  
It does work inside of a function, though. But not globally.  

The [Docs](https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/shading_language.html#constants) don't say anything about _global_ `const vec2[]` or other types not being supported.

### Steps to reproduce

Create a shader with the following content:  

    shader_type canvas_item; 
    const vec2 a[] = {
        vec2(-1, 0),
        vec2(1, 0)
    };

### Minimal reproduction project

No need of a project, just using that code in a shader will do.

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by Chaosus** [comment]
Yeah, https://github.com/godotengine/godot/pull/32751 should be ported to 3.2.

**Comment by akien-mga** [comment]
Fixed by #50889.
