### ISSUE TITLE
Recent master fails to build on FreeBSD. 

### ISSUE THREAD

**Issue by nonfatmatt** [godotengine/godot#49865]
### Godot version

4.0.dev (3cb153f)

### System information

FreeBSD Stable 13.0 / GCC 11 / LLVM 9 

### Issue description

After working out bugs with 3rd party libs, build fails on:

> platform/linuxbsd/os_linuxbsd.cpp:402:21: error: use of undeclared identifier 'basename'
        String file_name = basename(p_path.utf8().get_data());

### Steps to reproduce

Checkout master, verify dependencies, run build with "-j14 builtin-libvpx=False pulseaudio=False platform=linuxbsd"

**Comment by Calinou** [comment]
I can confirm this on FreeBSD 13 on Cirrus CI.

**Comment by akien-mga** [comment]
Duplicate of #48938 (fixed).
