### ISSUE TITLE
Built-in scripts don't autosave when executing project

### ISSUE THREAD

**Issue by UltimaN3rd** [godotengine/godot#4987]
**Operating system or device - Godot version:** Ubuntu 16.04 LTS 64-bit, Godot 2.0.3

**Issue description** (what happened, and what was expected): When using built-in scripts they won't be autosaved by running the project. I have to hit ctrl+s to save the script before executing or changes won't be reflected. External scripts are saved automatically so this is unintuitive and was initially quite confusing.

**Steps to reproduce:** Make a built-in script on some node, add some code, save and run. Stop running the game, change the script and hit the play button or F6. The script changes won't be reflected unless you manually save the built-in script with ctrl+s.

Obviously this is a minor issue but it was a bit of a tripping hazard until I figured it out.

**Comment by vnen** [comment]
This seems related to #438.
