### ISSUE TITLE
A BUG in binary encoding storage conversion

### ISSUE THREAD

**Issue by qjyqjyqjyqjy** [godotengine/godot#49883]
### Godot version

3.3.stable+

### System information

Windows10

### Issue description

project_settings.cpp  ：A BUG in binary encoding storage conversion

### Steps to reproduce

        //file：project_settings.cpp    function name：_save_settings_binary
        if (p_custom_features != String()) {
        file->store_32(count + 1);
        //store how many properties are saved, add one for custom featuers, which must always go first
        String key = CoreStringNames::get_singleton()->_custom_features;
        file->store_32(key.utf8().length()); //Fixed BUG location
        file->store_string(key);
        int len;
        err = encode_variant(p_custom_features, NULL, len, false);
        if (err != OK) {
            memdelete(file);
            ERR_FAIL_V(err);
     }

**Comment by Calinou** [comment]
@qjyqjyqjyqjy Can you describe the incorrect behavior and what this code fixes?

**Comment by timothyqiu** [comment]
This has already been fixed by #49649.
