### ISSUE TITLE
HTML5 - Key inputs do not fire until the user clicks into the webpage

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#49896]
### Godot version

3.3.2.stable

### System information

Ubuntu 20.10, Firefox (Nightly) 90.0a1, Chrome 91.0.4472.114

### Issue description

As the title says, key input events aren't fired unless you explicitly click on the webpage.

This is not a security issue, since other sites with raw HTML text fields such as [Google](https://www.google.com/) or [DuckDuckGo](https://duckduckgo.com/) do not have this issue.

https://user-images.githubusercontent.com/14253836/123323912-cca24b00-d4fb-11eb-80c7-48e1524a0fa7.mp4

### Steps to reproduce

1) Make a `_input` function and print its output.
    ```py
    func _input(event):
        print(event)
    ```

### Minimal reproduction project

[Test4_1.zip](https://github.com/godotengine/godot/files/6711866/Test4_1.zip)

**Comment by Calinou** [comment]
Does this also apply to `Input.is_key_pressed()` in an `_input()` function?

**Comment by nathanfranke** [comment]
Great question, and _input also doesn't work, so this isn't just an issue with the control nodes

**Comment by Faless** [comment]
Godot does not automatically focus the canvas on load, unlike the website you showed which automatically focus the input field on load.

I'm not sure we should automatically focus the canvas (as it might not be desired in some cases, i.e. when integrating into an existing web page).

**Comment by Calinou** [comment]
> I'm not sure we should automatically focus the canvas (as it might not be desired in some cases, i.e. when integrating into an existing web page).

Could this be exposed as an export option that's enabled by default? Most people will use the default HTML after all.

**Comment by nathanfranke** [comment]
Maybe the grab focus function should focus the canvas too? Would that be too cumbersome to implement from a technical standpoint? Or maybe just add that logic to `OS::move_window_to_foreground()`?

**Comment by Faless** [comment]
> Maybe the grab focus function should focus the canvas too?

What grab focus function?

> Or maybe just add that logic to `OS::move_window_to_foreground()`?

Yeah, that's easy, we already have the function to focus the canvas (`godot_js_display_canvas_focus`).
It would not actually move the window to foreground though.

In general, adding:

```
document.getElementById("canvas").focus()
```
to HTML head include will just work.

**Comment by Faless** [comment]
> Could this be exposed as an export preset option that's enabled by default? Most people will use the default HTML after all.

Yes, I mean, it's already a mess, but I guess another option is not too bad

**Comment by nathanfranke** [comment]
I mean `Control::grab_focus`
