### ISSUE TITLE
Basis.get_rotation_quat() throws error saying I should use get_rotation_quat()

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot#49892]
### Godot version

v3.3.2.stable.official

### System information

Windows 10, GLES3

### Issue description

I'm procedurally animating a 3D rig through code, for which I use `skeleton.get_bone_pose(index).basis.get_rotation_quat()` all over the place. However, this line throws the following error:
`E 0:00:03.352   get_quat: Basis must be normalized in order to be casted to a Quaternion. Use get_rotation_quat() or call orthonormalized() instead.
  <C++ Error>   Condition "!is_rotation()" is true. Returned: Quat()
  <C++ Source>  core/math/basis.cpp:791 @ get_quat()
  <Stack Trace> :91 @ update_rotation()
                :111 @ update_child_rotations()
                :106 @ update_rotation()
                :111 @ update_child_rotations()
                smooth_rig.gd:55 @ _physics_process()
`
Changing my line to `skeleton.get_bone_pose(index).basis.orthonormalized().get_rotation_quat()` doesn't fix the error, and I'm clearly already using get_rotation_quat() as advised by the error.

### Steps to reproduce

Import a 3D rig and add a script containing the line `var rotation_quat = $Skeleton.get_bone_pose(0).basis.get_rotation_quat()`.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@robertzzz Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by robbertzzz** [comment]
@Calinou I'm working on a closed project, so I can't share the rig unfortunately. Would've attached one otherwise.

**Comment by lawnjelly** [comment]
This expression is returning false with the basis:
```
bool Basis::is_rotation() const {
	return Math::is_equal_approx(determinant(), 1, (real_t)UNIT_EPSILON) && is_orthogonal();
}
```
If you examine the basis, you can work out what is going wrong. If you are not sure, post the contents of one of the basis that are failing and someone can take a look.

**Comment by robbertzzz** [comment]
@lawnjelly get_rotation_quat() shouldn't throw any errors according to the error I'm getting (it explicitly mentions I should use that), but it does. That's what this bug report is about.

**Comment by lawnjelly** [comment]
As I say, post the basis then we can take a look.

It is probably something that can't be normalized, like 0, 0, 0 on an axis. i.e. the basis is probably invalid. You can't do anything to such a basis to make it valid.

**Comment by robbertzzz** [comment]
I'm not trying to get an error on my end fixed, I added this bug report because the thrown error makes no sense. It's a bug in the engine's error handling

**Comment by dzil123** [comment]
I have also encountered this error, with the basis `((-1, 0, 1), (0, -1, 0), (0, 0, 0))`.

I think that if `is_rotation()` is false when `get_rotation_quat()` is called, there should be an error message printing the basis and explaining why this basis is an invalid rotation.

The current error message is confusing and unhelpful because the suggested solution does not make sense.

**Comment by Calinou** [comment]
> I have also encountered this error, with the basis `((-1, 0, 1), (0, -1, 0), (0, 0, 0))`.

I can confirm this on 3.3.3 with the following script:

```gdscript
extends Node

func _ready():
	var basis = Basis(Vector3(-1, 0, 1), Vector3(0, -1, 0), Vector3(0, 0, 0))
	print(basis)
	print(basis.get_rotation_quat())
	print(basis.orthonormalized().get_rotation_quat())
```
