### ISSUE TITLE
100% of a thread CPU usage while downloading export templates

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#49899]
### Godot version

3.3.2 Stable (from website)

### System information

Archlinux, Intel based Laptop

### Issue description

When downloading export templates Godot consumes 100% CPU
![100CPU](https://user-images.githubusercontent.com/13490050/123337355-302f8580-d59b-11eb-9a01-84ca9aa5fa77.jpg)

I would not expect waiting for a file to download to take much processing power.

### Steps to reproduce

Go to the export template manager, and start downloading the export templates.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/48902 might help with this once it's cherry-picked to the `3.x` branch.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/35868.
