### ISSUE TITLE
`Label.clip_text` doesn't clip vertically

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#49893]
See also https://github.com/godotengine/godot/issues/16863#issuecomment-405693704
### Godot version

3.3.2

### System information

Windows 10

### Issue description

The [docs](https://docs.godotengine.org/en/stable/classes/class_label.html#class-label-property-clip-text) say that `clip_text` let's you scale the control freely, but this is not true, it will only clip the text horizontally. Either a change in the implementation or in the documentation should be made.

### Steps to reproduce

- Create a label
- Type something in it
- Enable `clip_text`
- Try and scale it vertically so that it clips the text

**Comment by insomniacUNDERSCORElemon** [comment]
If you mean you can't reduce the vertical rect size to cause clipping, I can confirm.

Also see my comment at https://github.com/godotengine/godot/issues/43543 or for an example of a rotated label not clipping correctly:

![clip_text_rotated](https://user-images.githubusercontent.com/4397725/123344925-e60abd80-d522-11eb-9f26-e0684e4df7f5.png)
