### ISSUE TITLE
Max Size on 2D items

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#499]
I've just been trying to create some 2d ui, and I'd like to have a max_size.
I'm sure other people can see the usefulness in this?

**Comment by akien-mga** [comment]
Could you be more specific? I don't understand what you mean. Do you mean there should be a maximum size for UI controls when resizing the UI?

**Comment by mitchcurtis** [comment]
> Do you mean there should be a maximum size for UI controls when resizing the UI?

Yes:

- https://doc.qt.io/qt-5/qml-qtquick-layouts-layout.html#maximumWidth-attached-prop
- https://doc.qt.io/qt-5/qlayoutitem.html#maximumSize
- https://doc.qt.io/qt-5/qboxlayout.html#maximumSize
- https://doc.qt.io/qt-5/qwidget.html#maximumSize-prop
