### ISSUE TITLE
Shrink By option does not work if atlas ON

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4990]
**Operating system or device - Godot version:**
Windows 10, 2.1 alpha with 182ee80

**Issue description** (what happened, and what was expected):
Shrink By option does not work if altas ON.

**Steps to reproduce:**
1. make an image group at Project Export Settings > Image Groups
2. chage Compress Mode to Compress Disk
3. change shrink by option value to 4
4. export project and run
5. can see blurry image
6. make Atlas ON
7. export project and run
8. can not see blurry image (not shrink)

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
it seems to work for me, can you try erasing your export cache (just delete everything in ~/.godot/tmp ) and re export directly with shrink by 4? I want to know of this is a cache issue

**Comment by volzhs** [comment]
@reduz yes. it works after clear cache in ~/.godot/tmp

**Comment by reduz** [comment]
oh thanks for the info, it seems it _is_ a cache issue then, will take a
look

**Comment by reduz** [comment]
This is somewhere either in editor_import_export.cpp (most likely) or editor_texture_import_plugin.cpp

The generated atlases are cached sp they don't have to be re-generated every time, and they are cached together with a configuration file of the parameters use to cache the atlas. In theory, if the parameters are different (in this case shrink x2) , the atlas cache should no longer valid.

This piece of code (image conversion mostly) is pretty hacky, all the EditorImportExport options will need a serious clean-up at some point. For now fixing the bug would be enough

**Comment by reduz** [comment]
to add more detail, the specific bug is that the atlas is not being regenerated (the cache version is used) despite the parameters changed

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.

**Comment by volzhs** [comment]
generating altas at exporting is removed in 3.x so...
I expect rewritten one will be added at some point and this issue might not happen again.
