### ISSUE TITLE
GDNative API casting

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [godotengine/godot#49903]
### Godot version

latest

### System information

Does not matter

### Issue description

Currently, on the engine side of the GDNative API casting is done using C style (using round brackets) in the way like this:
```
void GDAPI godot_string_new(godot_string *r_dest) {
	String *dest = (String *)r_dest;
	memnew_placement(dest, String);
}
```
Maybe it would make sense to replace those casts with C++ casts?

### Steps to reproduce

There are no steps

**Comment by pycbouh** [comment]
Hi, `latest` is not a version, so please specify if you are using a stable version, and which one is it, or if you are using master, and at which commit.
