### ISSUE TITLE
Vulkan: CanvasItemMaterial light_mode light only doesn't work

### ISSUE THREAD

**Issue by dweremeichik** [godotengine/godot#49909]
### Godot version

4.0.dev (fdccc0b21)

### System information

Windows 10, Vulkan, GTX 1070

### Issue description

Setting light mode to light only on CannvasItemMaterial no longer works. When a light touches a sprite with this set, the sprite remains invisible.

### Steps to reproduce

1. Create a 2D scene with a Light2d (point or directional) and a Sprite2d.
2. Set the material on the Sprite2d to CanvasItemMaterial.
3. Set the CanvasItemMaterial light mode to `Light Only`

### Minimal reproduction project

[Light Only Test.zip](https://github.com/godotengine/godot/files/6717543/Light.Only.Test.zip)

**Comment by qwe3121** [comment]
I can confirm this behavior at Godot 6 beta 16

**Comment by clayjohn** [comment]
Duplicate of https://github.com/godotengine/godot/issues/44559
