### ISSUE TITLE
"Case" keyword is not treated as reserved in GDScript

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#4991]
The docs says that [`case` is a keyword](http://docs.godotengine.org/en/latest/reference/gdscript.html#keywords) "reserved for future implementation". The GDScript's tokenizer don't recognize it, so it can be used as an identifier.

So either the documentation should be changed or the `case` keyword should be reserved to avoid people using `case` as variable/function name.

**Comment by neikeq** [comment]
IMO it wouldn't harm to make it a reserved word, even if not used.
