### ISSUE TITLE
GDScript yield invalidated

### ISSUE THREAD

**Issue by Klaider** [godotengine/godot#49918]
### Godot version

b2dddc3c82e166cdca715e7f66eebf21be79f134

### System information

Windows 10

### Issue description

The GDScript parser expects an identifier before `yield` (the same column where `yield` begins).

### Steps to reproduce

Download editor artifact from GitHub action: https://github.com/godotengine/godot/actions/runs/972501327 and test a `yield` statement in the main scene, like this:

```
func _ready():
    yield(get_tree().get_root(), "ready")
```

**Comment by Calinou** [comment]
`yield()` was replaced by `await` in the `master` branch. The keyword is still reserved for future use, but `yield()` is no longer functional in `master`.
