### ISSUE TITLE
BBCode RichTextLabel not working as expected

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#49914]
### Godot version

 v3.3.stable.official

### System information

Windows 10

### Issue description

I writing a markdown to BBCode converter and stuck on implementation because of tags not work as expected.
I take a look in the source code and the tags e.g. `ul` should work but it not works.

https://github.com/godotengine/godot/blob/3.3/scene/gui/rich_text_label.cpp
```
} else if (tag == "ul") {

			push_list(LIST_DOTS);
			pos = brk_end + 1;
			tag_stack.push_front(tag);
		} else if (tag == "ol") {

			push_list(LIST_NUMBERS);
			pos = brk_end + 1;
			tag_stack.push_front(tag);
```

I uses this example bbcode to test the tags
```

[u]test tag u [/u]

[s]test tag s [/s]

[p]test tag p [/p]

[color=red] test tag color[/color]

[bgcolor=red] test tag bgcolor[/bgcolor]

[fgcolor=green] test tag fgcolor[/fgcolor]

[outline_color=green] test tag outline_color[/outline_color]

[indent]test tag indent [/indent]

[ul]test tag ul[/ul]
[ol type=1]test tag ol=1[/ol]
[ol type=a]test tag ol=a[/ol]
````
The rendered text is:
![image](https://user-images.githubusercontent.com/347037/123471696-77972f80-d5f6-11eb-88c7-04bf5b6ee400.png)

I see also differenzes in 3.3 and 4.0 rich_text_label.cpp implementation.
e.g. i miss support of 'bgcolor' in 3.3

For me looks like the RichTextlabe BBCode support is right in a beta state and not production ready.

Best Regards
Mike

### Steps to reproduce

- put the bbcode on a RichTextLabel
```

[u]test tag u [/u]

[s]test tag s [/s]

[p]test tag p [/p]

[color=red] test tag color[/color]

[bgcolor=red] test tag bgcolor[/bgcolor]

[fgcolor=green] test tag fgcolor[/fgcolor]

[outline_color=green] test tag outline_color[/outline_color]

[indent]test tag indent [/indent]

[ul]test tag ul[/ul]
[ol type=1]test tag ol=1[/ol]
[ol type=a]test tag ol=a[/ol]
````

Table support is also very bad 
```
[table=2]
[cell]food[/cell]
[cell]gold[/cell]
[cell]500[/cell]
[cell]5000[/cell]
[/table]
```
![image](https://user-images.githubusercontent.com/347037/123474085-bda1c280-d5f9-11eb-9cb9-b83137532fdf.png)
And why Godot uses his own bbcode tags and not the official tags?

**Comment by bruvzg** [comment]
Lists and table cell borders/backgrounds are implemented only in the `master` branch.

**Comment by Calinou** [comment]
> Lists, bg/fgcolor and table cell borders/backgrounds are implemented only in the `master` branch.

I guess we can print a warning message if unimplemented tags are used on `3.x`.

**Comment by MikeSchulze** [comment]
But i see list is implemented in 3.3

If there a way to just merge the 4.0 version back to 3.3

Godot 4.0 is far away you should merge down such enhancments / feature complete back in Godot 3.3.
It is always a pain to strugle un such half gared implementations.

The Goal should be bring Godot in a good shape, i have the feeling the most manpower gooes to Godot 4.0 and Godot 3.x is a bit neglected.

**Comment by bruvzg** [comment]
> But i see list is implemented in 3.3

The only implemented thing is `push_list` function (and reading tags to call it), rendering of the `ItemList` is not.

> Godot 4.0 is far away you should merge down such enhancments / feature complete back in Godot 3.3.
It is always a pain to strugle un such half gared implementations.

It's non-trivial task, 4.0 RichTextLabel implementation depends on #41100 which introduce breaking core changes.

**Comment by MikeSchulze** [comment]
@bruvzg thanks for your answer.

I now it is hard to focus to bing Godot 4.0 in a stable position ;)
But it is hard to see Godot 3.x is only mainternace releases e.g. bug fixes. 
Godot 4.0 is far away and i not expect that will production ready this year.

Let see ;)
regards
Mike

**Comment by Calinou** [comment]
Closing, as there is nothing actionable within this issue. Efforts to backport new RichTextLabel features in a backwards-compatible way to 3.x are welcome, but this won't be tackled by core contributors.
