### ISSUE TITLE
RegEx: sub not working on multilines by default

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#49927]
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

I working on a markdown parser to convert to bbcode and use regex pattern to replace md code by bbcode.
I test my pattern by popular online regex parsers and it works as expected but run into issues on Godot.

Using '$' pattern and regex.sub() with multiline = true is not working correct.

### Steps to reproduce

```
static func regex(pattern :String) -> RegEx:
	var regex := RegEx.new()
	var err = regex.compile(pattern)
	if err != OK:
		push_error("error '%s' on pattern '%s'" % [err, pattern])
		return null
	return regex

func test_regex() -> void:
	var regex := regex("^### (.*)$")
	
	prints("1", regex.sub("### testheader", "<h3>$1</h3>", true))
	prints("-------------------------------------------------------")
	prints("2", regex.sub("### testheader\n", "<h3>$1</h3>", true))
	prints("-------------------------------------------------------")
	prints("3", regex.sub("\n### testheader\n", "<h3>$1</h3>", true))
	prints("-------------------------------------------------------")
	prints("4", regex.sub("### testheader\n### testheader\n", "<h3>$1</h3>", true))
```
the output is:
```
 
1 <h3>testheader</h3>
-------------------------------------------------------
2 <h3>testheader</h3>

-------------------------------------------------------
3 
### testheader

-------------------------------------------------------
4 ### testheader
### testheader
```

- workaround is to split up the input into lines and parse each line selarate, but i guess it will have more problems when using a pattern that goes over multiple lines

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-docs/issues/4943.

**Comment by MikeSchulze** [comment]
@Calinou i tryed to use the suggested pattern

After some trys i get it running, thanks.
`(?m)^### (.*)$`

It would be nice to extend the compile function by optional flags e.g.

<html>
<body>


<h1> RegEx flags to control the parsing</h1>

Flag | value | Description
-- | -- | --
IGNORECASE | 1 | ignore case.
MULTILINE | 2 | make begin/end {^, $} consider each line.
DOTALL | 4 | make . match newline too.
UNICODE | 8 | make {\w, \W, \b, \B} follow Unicode rules.
LOCALE | 16 | make {\w, \W, \b, \B} follow locale.
VERBOSE | 32 | allow comment in regex.


</body>
</html>        

### function signature 
- flags are optional do not break the API
```
        Error compile(pattern: String, flags := 0)
```
### short example
```
	var regex := RegEx.new()
	var err = regex.compile(<pattern>, RegEx.MULTILINE)

````

**Comment by Calinou** [comment]
Closing, as this is a documentation issue: https://github.com/godotengine/godot-docs/issues/4943

Feature proposals should be made on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.
