### ISSUE TITLE
Real Camera not working in game when enabled in the editor

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot#49920]
### Godot version

v3.4.beta.custom_build [5fd13776a]

### System information

Windows 10

### Issue description

If you have a webcam running in the editor, it will not load in the game. (not present or green fallback texture).
(see conversation about CameraServer on Windows https://github.com/godotengine/godot/pull/49763).

This bug occurs on Windows ~~and probably also on Mac (see [this ](https://apple.stackexchange.com/questions/3386/how-do-i-use-multiple-webcams-at-once-on-mac-os-x)post)~~.

A possible solution idea from @benjarmstrong is that the editor could disable all active camera feeds when the game is launched from it, and then re-enable them once the game is no longer running.

### Steps to reproduce

1. Add a `Camera Texture` .
2. Start the Camera in the Editor.
3. Run the game.

(I tested it with a Github action result from https://github.com/godotengine/godot/pull/49763 on Windows 10. )

**Comment by bruvzg** [comment]
>  and probably also on Mac (see this post).

On macOS it's working fine, camera access is not exclusive.

**Comment by Gamemap** [comment]
I have updated it.
Thank you.

**Comment by Calinou** [comment]
This should be left on https://github.com/godotengine/godot/pull/49763 since the feature in question hasn't been merged yet. Otherwise, it's confusing for other people as this issue is discussing a feature that is not in Godot yet.

**Comment by benjarmstrong** [comment]
> > and probably also on Mac (see this post).
>
> On macOS it's working fine, camera access is not exclusive.

Thanks for correcting this, I'll correct my comment.
