### ISSUE TITLE
LineEdit Control not showing last characters or showing overflow for some align values

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot#4992]
**Operating system or device - Godot version:**
Using : Godot_v2.0.3_stable_x11.64 on linuxmint 17.3

**Issue description** (what happened, and what was expected):
LineEdit node when aligned with _node.set_align(HALIGN_RIGHT)_ is eating up the last characters of text. When aligned left, box size do not change, but missing characters become visible. 

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment]
related to #3643

**Comment by hubbyist** [comment]
To clarify I am stuck to this problem in production code so it is more than a usability issue.

**Comment by neikeq** [comment]
@hubbyist could you confirm if this is the same as #3643?

**Comment by hubbyist** [comment]
I have the same issue as #3643 with editor boxes as well. But also situation is as in the picture for the production code which is not said in #3643.

![linedit_alignment](https://cloud.githubusercontent.com/assets/5895328/15771686/20003c40-2975-11e6-9df8-86f3d3046b3b.png)

**Comment by akien-mga** [comment]
Thanks. Let's keep this issue which is a bit more detailed and close the other one then. Both bugs would have the same fix.

**Comment by hubbyist** [comment]
Note : #4840 which I reported early may be related with this issue.

**Comment by reduz** [comment]
the align code was contributed, not sure if this fixes, do you remember who contributed it?
