### ISSUE TITLE
Attempting to edit `ShaderMaterial` leads to editor freezing

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49937]
### Godot version

~92f75046378a63b46946e8acbd7c224f027ebfa5~ bde6f5eed1cec3639e5c81d1e5ee34ecf3fe7486

### System information

Windows 10

### Issue description

Attempting to edit a shader cause editor freeze with the following spam to console:

![image](https://user-images.githubusercontent.com/3036176/123534338-2fc2f600-d725-11eb-8f25-c4401fe844d7.png)

The error is:
```
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::prepare_buffers (drivers\vulkan\vulkan_context.cpp:1728)
```

call stack:

```
 	godot.windows.opt.tools.64.exe!VulkanContext::prepare_buffers() Line 1729	C++
 	godot.windows.opt.tools.64.exe!RenderingDeviceVulkan::prepare_screen_for_drawing() Line 8137	C++
 	godot.windows.opt.tools.64.exe!RendererViewport::draw_viewports() Line 623	C++
 	godot.windows.opt.tools.64.exe!RenderingServerDefault::_draw(bool p_swap_buffers, double frame_step) Line 115	
 	godot.windows.opt.tools.64.exe!Main::iteration() Line 2539	C++
 	godot.windows.opt.tools.64.exe!OS_Windows::run() Line 622	C++
 	godot.windows.opt.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 163	C++
 	godot.windows.opt.tools.64.exe!_main() Line 187	C++
>	godot.windows.opt.tools.64.exe!main(int argc, char * * argv) Line 199	C++
```

### Steps to reproduce

Create a simple scene with a mesh, assign `ShaderMaterial` to material override property and try open it.

### Minimal reproduction project

[ShaderTest.zip](https://github.com/godotengine/godot/files/6721099/ShaderTest.zip)

**Comment by SaracenOne** [comment]
This seems to happen with any material type, not just ShaderMaterial. It can also happen if you simply create the material from the inspector window without having to assign it a MeshInstance.

**Comment by Chaosus** [comment]
> This seems to happen with any material type, not just ShaderMaterial. 

Yeah, however, all other types of material are just shells for shader material and compile to it internally.

**Comment by Chaosus** [comment]
I've bisected it. Its a regression from bde6f5eed1cec3639e5c81d1e5ee34ecf3fe7486

**Comment by akien-mga** [comment]
Please confirm that the freeze is indeed fixed with #49973 if you can.

**Comment by SaracenOne** [comment]
@akien-mga Just tested this and it doesn't appear to be crashing anymore, yeah!

**Comment by Chaosus** [comment]
Indeed, it's fixed.
