### ISSUE TITLE
Strange behavior of the engine...

### ISSUE THREAD

**Issue by VarionDrakon** [godotengine/godot#49930]
### Godot version

3.3.2 Stable

### System information

Windows 10 20H2, GLES2

### Issue description

Good day to all. I played around with the code a bit and noticed an interesting feature, namely, this code fragment detects an node from another scene, but does not interact with it. But if you specify the path to the object directly on the general scene, then everything is fine. 
What do you think could be wrong?

Code:
```
var LoadSceneSpike_object = Godot.ResourceLoader.Load<PackedScene>("res://Core/Scenes/Spike.tscn");

var SpikeScene_object_loaded = LoadSceneSpike_object.Instance();

var CollisionSpike_Damage = SpikeScene_object_loaded.GetNode<KinematicBody2D>("Spike_body");


if (collision.Collider == CollisionSpike_Damage)
{
  hp = hp - 50;
}
```

### Steps to reproduce

I think that the bug (Or what it is) I described it in detail above...

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
