### ISSUE TITLE
Vulkan: LightmapGI's Directional property only works correctly when lights' bake mode is Dynamic, not Static

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#49936]
### Godot version

4.0.dev (659178e85)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

Vulkan: LightmapGI's Directional property only works correctly when lights' bake mode is **Dynamic**, not **Static**. When Directional is enabled and a light has its bake mode set to **Static**, it will generate lighting as if only indirect lighting was requested. This makes the scene much darker than it should be, since real-time lighting is disabled on baked objects when the bake mode is set to **Static**.

Having directional lighting in LightmapGI would be useful when the light's bake mode is set to Static, since this is how you can get the best possible performance while preserving normal map appearance. Otherwise, normal maps become useless for static lights if the lightmap doesn't store directional information.

See also https://github.com/godotengine/godot/issues/49935.

### LightmapGI Directional disabled, DirectionalLight bake mode set to Static (correct)

![LightmapGI Directional disabled, DirectionalLight bake mode set to Static](https://user-images.githubusercontent.com/180032/123529060-65e48380-d6ed-11eb-8d77-ddec9bbaa458.png)

### LightmapGI Directional enabled, DirectionalLight bake mode set to Static (broken)

![LightmapGI Directional enabled, DirectionalLight bake mode set to Static](https://user-images.githubusercontent.com/180032/123529058-641ac000-d6ed-11eb-9155-6fcf63940df9.png)

### Steps to reproduce

- Make sure you have meshes with UV2 and bake mode set to **Static**.
- Add a DirectionalLight3D node and set its bake mode to **Static**.
- Add a LightmapGI node and enable **Directional** on it.

### Minimal reproduction project

[test_lightmap_normalmap_1.zip](https://github.com/godotengine/godot/files/6720851/test_lightmap_normalmap_1.zip)

**Comment by Calinou** [comment]
This was confirmed by Saracen on the Godot contributors chat.

**Comment by williamd67** [comment]
The option `Direction` does not exist in Godot 3.4. The implementation of Godot 4.0 connects `Direction` to spherical harmonics, which seems to be in a alpha state.

My questions are: should the option `Direction` exist? In case, the answer is yes, what should the option `Direction` do? 

In case `Direction` is a valid option, my interpretation would be that directional lights would only be taken into account when `Direction` is enabled. Correct?

**Comment by Calinou** [comment]
> The option Direction does not exist in Godot 3.4. The implementation of Godot 4.0 connects Direction to spherical harmonics, which seems to be in an alpha state.

My questions are: should the option Direction exist? In case, the answer is yes, what should the option Direction do?

In case Direction is a valid option, my interpretation would be that directional lights would only be taken into account when Direction is enabled. Correct?

The **Direction** property toggles support for spherical harmonics. This is expected behavior, as you usually want to disable spherical harmonics when targeting low-end mobile hardware (or to save space for mobile/web games in general).

**Comment by williamd67** [comment]
Thanks @Calinou, clear now. I will investigate the `Spherical harmonics' implementation.

**Comment by techiepriyansh** [comment]
I investigated this issue a bit and found that the culprit might be the disparity between the scaling factors of `1.0 / 3.0` [here](https://github.com/godotengine/godot/blob/master/modules/lightmapper_rd/lm_compute.glsl#L369) and `8.0` [here](https://github.com/godotengine/godot/blob/master/modules/lightmapper_rd/lm_compute.glsl#L476).

Actually, the lightmap does store the direct lighting information when the lights' bake mode is set to static. It's just that the scaling factor for indirect lighting is much larger than that for direct lighting; it appears as if only indirect lighting was requested.

Bumping up the scaling factor of `1.0 / 3.0` improves the lighting (with LightmapGI Directional enabled and DirectionalLight bake mode set to Static):

* Original, without any bumping
    ![original_without_any_bumping](https://user-images.githubusercontent.com/26199781/167306376-771962a0-9189-4dd0-a03a-a708a332dd6f.png)


* `1.0 / 3.0` bumped up to `6.0 / 3.0`
    ![1_bumped_up_contribution_of_direct_light](https://user-images.githubusercontent.com/26199781/167305875-3a6c8951-cf0e-42b3-be25-797d8f597136.png)


* `1.0 / 3.0` bumped up to `9.0 / 3.0`
    ![bumped_up_contribution_of_direct_light](https://user-images.githubusercontent.com/26199781/167305525-c235917a-ca90-4b12-9439-2fa791f07861.png)


* `1.0 / 3.0` bumped up to `15.0 / 3.0`
    ![3_bumped_up_contribution_of_direct_light](https://user-images.githubusercontent.com/26199781/167305473-d0651dde-f3f2-4fb7-85e7-a0fb415268f7.png)

* `1.0 / 3.0` bumped up to `18.0 / 3.0`
    ![bumped_up_contribution_of_direct_light2](https://user-images.githubusercontent.com/26199781/167305445-2d0cbfed-386e-443d-8e4b-a58e56171679.png)

On the other hand, scaling down the factor of `8.0` makes the scene even darker:
* `8.0` scaled down to `1.0` (and `1.0 / 3.0` kept the same)
    ![scaled_down_contribution_of_indirect_light](https://user-images.githubusercontent.com/26199781/167305911-19c4605c-1737-4df2-9566-20d8bf6df919.png)


With these observations, I suspect that the scaling factor of `1.0 / 3.0` might be wrong and we just need to replace it with the correct one.

**Comment by DarioSamo** [comment]
Will attempt to reproduce and investigate.
