### ISSUE TITLE
Debugger showing Null when hovering over variable name in script editor

### ISSUE THREAD

**Issue by Blackiris** [godotengine/godot#49939]
### Godot version

4.0.dev (92f75046378a63b46946e8acbd7c224f027ebfa5)

### System information

Archlinux

### Issue description

When launching a project and adding a debug breakpoint, hovering over variable names in the script editor should show me their current value, but it shows 'Null' instead.
![image](https://user-images.githubusercontent.com/440909/123539965-b33c1180-d73c-11eb-86dc-248fbbd9e238.png)
However, the values do exist as we can see in the inspector in the bottom:
![image](https://user-images.githubusercontent.com/440909/123540025-16c63f00-d73d-11eb-8039-a44792228b0e.png)

### Analysis
In EditorDebuggerRemoteObject, all variables name and values are stored in a map: `Map<StringName, Variant> prop_values;`
However, the key in the case are `Locals/avar`, `Locals/bvar`... and not simply `avar` or `bvar`.

When hovering over the script editor, it tries to get avar value, instead of Locals/avar value as you can see here:
https://github.com/godotengine/godot/blob/92f75046378a63b46946e8acbd7c224f027ebfa5/editor/debugger/editor_debugger_inspector.cpp#L48-L55

### Steps to reproduce

Open the reproduction project, open test.gd.
Add a breakpoint at line 9, and launch the project.

_(Note: there is another bug but not related to this one, if you put it at line 10 instead, values in the inspector disappear)_

Hover your mouse over `avar`, `bvar` or `cvar`, and wait a few seconds to display the popup that should contains the value.

### Minimal reproduction project

[DebuggerNullValue.zip](https://github.com/godotengine/godot/files/6721353/DebuggerNullValue.zip)

**Comment by Blackiris** [comment]
A possible solution is to create a new _get() that only loop all keys, and find a key that ends with "/" + p_name.
However, if a var name exists as a Locals, Members and Globals, which one should it display, when knowing only the var name?

**Comment by ivalylo** [comment]
Wow, thanks for digging up that. I was able to patch it up, until there is official fix for that.

```
bool EditorDebuggerRemoteObject::_get(const StringName &p_name, Variant &r_ret) const {
	auto element = prop_values.find(p_name);
	if (!element) {
		if (((String)p_name).find_char('/') != -1) {
			return false;
		}
		StringName local_name = "Locals/" + p_name;
		element = prop_values.find(local_name);
		if (!element) {
			StringName member_name = "Members/" + p_name;
			element = prop_values.find(member_name);
			if (!element) {
				return false;
			}
		}
	}

	r_ret = element->get();
	return true;
}
```

**Comment by ivalylo** [comment]
There is another issue if you have something like this: "object.position". The method will receive only "position", while ideally, it should get also the object, and resolve "position" as property of "object".

**Comment by Blackiris** [comment]
With only the varname, it is technically impossible to guess which one from the locals, members or globals we need to read the value from. At the same time, it is a very bad practice to have some variables with the same name.

However for the moment, your idea of finding values from Locals first is enough in most cases.

**Comment by jmb462** [comment]
If we choose to find from Locals to Globals, pointing the mouse on a Member variable will show the local one (if exist).
Seems to be difficult to know the scope by pointing with mouse.

![image](https://user-images.githubusercontent.com/3649998/129927379-f4744d21-01e6-4282-a6c3-e921a6f1c80e.png)
