### ISSUE TITLE
Can't extend script from a parent folder using a relative path

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#49938]
### Godot version

master 92f75046378a63b46946e8acbd7c224f027ebfa5

### System information

Ubuntu 20.04 64-bit

### Issue description

In the current master branch, in GDScript, you can't extend a script in a parent folder by referencing a relative path (`../`). However, this is possible in Godot 3.x.

### Steps to reproduce

res://parent.gd: `extends Node`

res://test/test.gd: `extends "../parent.gd"` (this is broken in the current master)

See minimal reproduction project.

### Minimal reproduction project

[ExtendsRelative.zip](https://github.com/godotengine/godot/files/6721132/ExtendsRelative.zip)

**Comment by lyuma** [comment]
Getting the same issue.
```
Scripted.gd:0 - Parse Error: Could not resolve super class path "./Relative.gd".
  modules\gdscript\gdscript.cpp:840 - Method/function failed. Returning: ERR_PARSE_ERROR
res: script valid 0
res: script valid 1
```
Here's my test project since I already made one:
[ExtendsRelative.zip](https://github.com/godotengine/godot/files/6741851/ExtendsRelative.zip)

**Comment by Blackiris** [comment]
The error is triggered here:
https://github.com/godotengine/godot/blob/d5b8abdb67e0dad745ea4037e5eb52745c96bae7/modules/gdscript/gdscript_cache.cpp#L123-L146

FileAccess::exists(p_path) return false because p_path = "../parent.gd"
I have tried to change it with:
```
	String path = p_path;
	if (path.is_rel_path()) {
		path = p_owner.get_base_dir().plus_file(p_path);
	}
```

The error disappered in the editor, but when launching the project there is a Parse Error issue...

**Comment by Blackiris** [comment]
Putting this code in the analyzer layer seems to do the trick.

**Comment by CsloudX** [comment]
？？？I meet this bug in Godot4 Alpha14？？？
