### ISSUE TITLE
Vulkan: Enabling any MSAA level hangs the editor indefinitely

### ISSUE THREAD

**Issue by missembyr** [godotengine/godot#49933]
### Godot version

4.0.dev

### System information

Windows 10, Vulkan, GTX1080 (460.89)

### Issue description

![unknown](https://user-images.githubusercontent.com/20043270/123527854-d7ff9d00-d6da-11eb-8422-ce0698e66383.png)

As the title states, enabling MSAA at any quality level hangs the editor indefinitely.

### Steps to reproduce

N/A

**Comment by SaracenOne** [comment]
Yes, I can also confirm experiencing this too on Windows 10, GTX 1080 (471.11)

**Comment by SaracenOne** [comment]
@Calinou @missembyr Tested this again today after pulling this PR #49973 and appears to be resolved, so it may be okay to close this now.

**Comment by clayjohn** [comment]
Closed by #49973
