### ISSUE TITLE
Incorrect operator property for visual script nodes.

### ISSUE THREAD

**Issue by MisoMosiSpy** [godotengine/godot#49943]
### Godot version

4.0 Dev (92f75046378a63b46946e8acbd7c224f027ebfa5)

### System information

Windows 10, OpenGL ES 3.0 Renderer: AMD Radeon(TM) Vega 10 Graphics

### Issue description

Name of the operator property in the inspector does not match with the type of Visual Script node. This is happening for bitwise and logical operator nodes. 

The issue is not observed in 3.3.x stable builds. I believe this is side effect of new implementation of variant operators added in https://github.com/godotengine/godot/pull/43323.

Please check the screenshot animation below for exact issue. 
![VisualScriptOperatorMismatch](https://user-images.githubusercontent.com/52410428/123543797-e6e35f80-d76d-11eb-86dc-ad132a88c2b3.gif)

I have made required changes to fix this issue, will submit the PR as well for review.

### Steps to reproduce

1. Add visual script to any node
2. Inside visual script editor add a node "Bitwise Shift Left".
3. Observe that operator property in inspector shows "concatenate"
4. Add another node "Logical AND", observe the operator property in the inspector shows "Bit Negate"

### Minimal reproduction project

I will submit if can't be re-produced with steps given.

**Comment by akien-mga** [comment]
Note: related PR merged recently #49831 (fixes a similar issue but for captions).
