### ISSUE TITLE
creating new Animation from AnimationTreePlayer

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4996]
**Operating system or device - Godot version:**
Windows 10, 2.1 alpha

**Issue description** (what happened, and what was expected):
Nothing can be done if creating new Animation from AnimationTreePlayer

**Steps to reproduce:**
1. add AnimationTreePlayer
2. add Animation Node in AnimationTreePlayer editor.
3. load > New Animation in Animation node
4. click drop down and Edit
5. AnimationTreePlayer is closed and nothing comes up
6. can see Animation editor if click Animation button on bottom panel
7. All buttons are disabled

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
while this is a bug, creating and linking animations directly from AnimationTreePlayer will eventually be removed and you will always need to reference an AnimationPlayer that contains the animations..
as such this will end up being solved in 3.0

**Comment by reduz** [comment]
sorry, kicking it again

**Comment by reduz** [comment]
Closed, as treepayer is deprecated
