### ISSUE TITLE
Baked Lightmap no Dynamic Object Shadows

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#49963]
### Godot version

3.3.2 Stable

### System information

Windows 10, GLES 2&3, Nvidia Quadro K2000 461.92

### Issue description

Baked Lights are supposed to allow for Dynamic Objects to cast shadows, as shown in https://docs.godotengine.org/en/stable/tutorials/3d/baked_lightmaps.html at the bottom of the page

Note: Haven't Tested the current 4.0, might be there too

### Steps to reproduce

1. Create A scene with a Static and Dynamic Objects, make sure they are configured properly and create a Lightmap
2. Bake Lightmap
3. Observe how Dynamic Objects don't cast shadows on Static Objects

### Minimal reproduction project

[Lightmap.zip](https://github.com/godotengine/godot/files/6726107/Lightmap.zip)

**Comment by Calinou** [comment]
The DirectionalLight's bake mode is set to **All**, which prevents dynamic objects from casting shadows on static objects by design. Set the bake mode to **Indirect** instead, which has a greater performance cost but allows dynamic objects to cast shadows.

**Comment by Zireael07** [comment]
@Calinou: Is this documented properly in godot-docs?

**Comment by Calinou** [comment]
> @Calinou: Is this documented properly in godot-docs?

No, the baked lightmap documentation needs to be redone from scratch (or almost) following the introduction of the new CPU lightmapper in Godot 3.3.
