### ISSUE TITLE
Error tab index out of size when opening project

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#4997]
**Operating system or device - Godot version:**
Windows 10, 2.1 alpha with 182ee80

**Issue description** (what happened, and what was expected):
When open project output console display this error:
[http://postimg.org/image/e624va5nv/](http://postimg.org/image/e624va5nv/)
```
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tab_container.cpp:478.
```

**Steps to reproduce:**
Open project and see output console.

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
Which error are you refering to? I can see 4 in the image.

**Comment by mefihl** [comment]
First with tab.

**Comment by neikeq** [comment]
I edited you message adding the error text after the image url. Did you start getting this error today? It may be a regression from #4926

**Comment by volzhs** [comment]
I saw that error message for a long time.

**Comment by Paulb23** [comment]
This error is printed as a result of the changes in `tab_container.cpp` in this [commit](https://github.com/godotengine/godot/commit/9b1f8230ec435d9289b53afa8da02367daf8b5af#diff-a8e38f356469d0ba40da2c344c47a50dR414)
