### ISSUE TITLE
Newly created dialog windows may not always be focused

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#49978]
### Godot version

4.0.dev (659178e85)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

Newly created dialog windows may not always be focused. They will appear with an unfocused style, preventing keyboard input from going to them:

![Unfocused window title](https://user-images.githubusercontent.com/180032/123714161-14b3cb80-d876-11eb-84d9-72933e970048.png)

Sometimes, they will be focused correctly when created, which results in the following appearance:

![Focused window title](https://user-images.githubusercontent.com/180032/123714190-24331480-d876-11eb-9741-431bd94015a3.png)

See also https://github.com/godotengine/godot/issues/49977 for a video version of this.

I'm assuming this is Linux-specific, but feel free to test this on other operating systems.

### Steps to reproduce

- Open the Project Settings or Editor Settings, then look at the window title styling/color. It *should* always be focused, but it's not. This occurs in a random and unpredictable pattern (about 50% of the time for me).
- This has been reported to occur with the Create New Node dialog as well.

### Minimal reproduction project

N/A

**Comment by Jimmio92** [comment]
This seems to also be causing #53894 and my accidental duplicate #57294. Window manager does seem to affect this; XFCE definitely has the problem, where KDE may not show it.

**Comment by KoBeWi** [comment]
Is this still reproducible in alpha 7?

**Comment by akien-mga** [comment]
No answer, assuming fixed in the meantime.
