### ISSUE TITLE
Error with default value for exported variable

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#49998]
### Godot version

3.3.2 official stable

### System information

w10 64

### Issue description

The exported variable should show its default value "FACIL = 4", then it should show the value 4 when you print the text in "_Ready" but show 0.
However, on another occasion it showed me the correct value, then I added a scene to do a test and for some reason it started to show the value 0 again.
The displayed value should be 4.

![Captura](https://user-images.githubusercontent.com/19652075/123802064-284d4980-d8eb-11eb-8a1c-6b163c9d06c7.PNG)

![Captura3](https://user-images.githubusercontent.com/19652075/123802075-2be0d080-d8eb-11eb-9e31-3ab66760ebb2.PNG)

### Steps to reproduce

Run the project

### Minimal reproduction project

[testEnum.zip](https://github.com/godotengine/godot/files/6733565/testEnum.zip)

**Comment by Torguen** [comment]
So how do you explain that on some occasions it was shown correctly with the value 4?

**Comment by akien-mga** [comment]
You set it to a different value, then set back to "Facil", and it was properly set.

**Comment by Torguen** [comment]
Ok, now I understand.
