### ISSUE TITLE
Exported constant Dictionary only supports integer values

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#49991]
### Godot version

3.3.2 official stable

### System information

w10 64

### Issue description

Exporting a constant with different values does not show all the values in the editor.
I'm afraid it only shows int value, why can't it show float values?

This
![Captura](https://user-images.githubusercontent.com/19652075/123769302-74879200-d8c9-11eb-8694-99293b0931df.PNG)
Show this
![Captura3](https://user-images.githubusercontent.com/19652075/123769314-77828280-d8c9-11eb-93fe-9652f5e124ba.PNG)

### Steps to reproduce

Add the code in the image and observe

**Comment by akien-mga** [comment]
I can confirm the issue in `3.x`, and indeed only integer values are supported. I'm not even sure why exporting Dictionaries is supported though, it's probably a side effect of supporting enum exports (which are internally Dictionaries with only integer values).

So I'm not sure the way you want to use it is meant to be supported, but it should probably raise an error if not supported.

**Comment by akien-mga** [comment]
This is solved in 4.0 as the new GDScript's export syntax no longer supports an arbitrary `export(constant)`. So you have to use something which is an actual type (e.g. an enum).
