### ISSUE TITLE
Script analyzer throws errors on functions called on properties exposed with multiple types

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#49992]
### Godot version

eb318d3e04ac6d3bb01b0f2a8311d06ba55c3a2b

### System information

Windows 10, Vulkan, Nvidia GTX 1080 (471.11)

### Issue description

The function in GDScriptAnalyzer, get_function_signature, will throw the error
```Native class %s used in script doesn't exist or isn't exposed```
when attempting to call functions on properties declared with multiple valid types (the ones with multiple types declared seperated by commas). Examples of these are:

- the process_material in GPUParticles2D and GPUParticles3D
- material overrides in MeshInstance3D,
- material_override in GeometryInstance3D
- adjustment_color_correction in Environment
- surfaces in ArrayMesh
- material in PrimitiveMesh
- sky_material in Sky.

### Steps to reproduce

Use a script to call a function on any of the properties described in the issue description.

### Minimal reproduction project

[multi_type_property_access.zip](https://github.com/godotengine/godot/files/6732110/multi_type_property_access.zip)

**Comment by Calinou** [comment]
@SaracenOne Can you still reproduce this on the latest `master` branch?

**Comment by SaracenOne** [comment]
@Calinou I tested it and I think this is resolved now yes, so I'll close this
