### ISSUE TITLE
Tabs Borders Work Differently

### ISSUE THREAD

**Issue by O-XiXu** [godotengine/godot#50011]
### Godot version

3.2.3.stable.custom_build

### System information

Kali

### Issue description

when i click on tabs spaces (docks or whatever) it show a light border around the tab space, that it should
(with - space - i mean options like file names in file system tab and even empty space)
and when i move the cursor to somewhere else the border go away, this is fine
but some other tabs act different in here, like both scripts panel tabs

i don't know if this is a bug or not but i think if all of tabs work same it's better 

### Steps to reproduce

First dock in Scripts panel: with clicking on
- empty space: it shows a border that do not go away with moving cursor except with clicking on a script name that should not
- script name: it doesn't show a border except with double clicking on it or clicking on empty space after first click

**Comment by Calinou** [comment]
Can you record a video to demonstrate this? Also, make sure to upgrade to Godot 3.3.2 and test this on the latest version first. We don't support Godot 3.2.x anymore.

**Comment by O-XiXu** [comment]
Now i use v3.3.2.stable.official, borders work normal,
probably this thing never was a bug, and not about tabs
actually it's about a difference between work spaces,
in 2D and 3D with moving the cursor to that point it shows a border
in two other work spaces there's no border showing,
not matter what i try to explain, everything is fine, and long live the king! :)

**Comment by Calinou** [comment]
Closing per @O-XiXu's comment.
