### ISSUE TITLE
3 crashes in around an hour. Not very sure about anything else, details below.

### ISSUE THREAD

**Issue by FishyBusinessYT** [godotengine/godot#50013]
### Godot version

v3.3.2-stable_win64

### System information

Windows 10, 12 Intel i7-9750 cores, NVIDIA GeForceRTX 2060, 16gb RAM

### Issue description

I really do not know. But before the first crash, when searching for nodes to add to a scene, every letter I type got me an error in the console. Something about a string got returned. I was also having trouble dragging a player.tscn file (I think). (I literally downloaded the program yesterday and am still learning the usage and names for things.) So when I dragged it, literally nothing would happen. Then I tried doing something else, and it just closed.
The second time was similar, except nothing out of the ordinary was happening and then it closed again. The weird thing about this is it had saved everything until the crash, but I had not saved in a long time.

The last crash, I was in the tile map editor, doing I can't remember what, and it just hung. I tried waiting, but 5 minutes later it was still frozen, so I ended the process.

### Steps to reproduce

I have absolutely no idea what I did or how to break it three times. in the Issue Description I give as much information as I can remember. Previously mentioned, I have zero experience with the engine.

### Minimal reproduction project

The test project that crashed is this one:
[Tutorial.zip](https://github.com/godotengine/godot/files/6737113/Tutorial.zip)
Aaand the tutorial video:
https://www.youtube.com/watch?v=Mc13Z2gboEk

**Comment by Torguen** [comment]
Something strange, I read the bugs almost daily and I don't remember anyone that this is happening to him.
I guess it only happens to you with Godot.
If it only happens with Godot then I have no idea but if it happens with other programs then there could be a problem at the hardware level.

**Comment by FishyBusinessYT** [comment]
Nope, it’s only Godot afaik

**Comment by Valeryn4** [comment]
Your project with errors ...
```
SCRIPT ERROR: GDScript::reload: Parse Error: Unique global class "Actor" already exists at path: res://src/Actors/Actor.gd
          At: res://Actors.gd:2
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583
SCRIPT ERROR: GDScript::reload: Parse Error: Unique global class "Actor" already exists at path: res://src/Actors/Actor.gd
          At: res://Actors.gd:2
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:583
```

`res://Actor.gd` and `res://src/Actors/Actor.gd` dublicated, uses equal class_name
remove `res://Actor.gd`

The tileset embedded in the tilemap has 80x80 tiles, and the grid is 16x16

But I did not find any other errors, there are no crashes.

default_env.tres generate procedural sky, may be you devices low perfomance?
![image](https://user-images.githubusercontent.com/12483173/124228345-6e0a4c00-db4f-11eb-9492-a983aba5322b.png)

**Comment by Calinou** [comment]
@FishyBusinessYT Can you (or anyone else) still reproduce this bug in [Godot 3.5](https://godotengine.org/article/godot-3-5-cant-stop-wont-stop) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by FishyBusinessYT** [comment]
Hey, sorry for the late reply. To this day, I have no idea what happened. My best guess is that it had something to do with all my little screw-ups (as described by Valeryn4. I came back to the engine a few months ago and nothing of the like has happened since. I can't reproduce the bug either.

Should you see it fit, feel free to close the issue!
