### ISSUE TITLE
Error `Condition "int32_t(p_level) != level" is true.` when running command `godot4 --version`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50031]
### Godot version

4.0.dev.custom_build. bb409efa1

### System information

Ubuntu 21.04

### Issue description

`godot4 --version`
```
4.0.dev.custom_build.bb409efa1
ERROR: Condition "int32_t(p_level) != level" is true.
   at: deinitialize_extensions (core/extension/native_extension_manager.cpp:101)
```

### Steps to reproduce

Above

**Comment by Calinou** [comment]
This is likely a regression from https://github.com/godotengine/godot/pull/49744. cc @reduz

**Comment by MisoMosiSpy** [comment]
Registration for extensions happens @ https://github.com/godotengine/godot/blob/master/main/main.cpp#L1212 only if error path is not taken, however, unregister is called in error path.
In other words we are calling deinitialize_extensions() before calling initialize_extensions().

move the call to register_core_extensions() inside register_core_types() 
or
check if level is -1 and skip rest of deinitialize_extensions() as it was not initialized in first place. 

let me know if you want me to raise the PR.

**Comment by Calinou** [comment]
I can confirm this on `master` 9d1626b4d.

**Comment by poiati** [comment]
I have a fix here https://github.com/godotengine/godot/pull/58196. The solution is based on @MisoMosiSpy observations.

**Comment by akien-mga** [comment]
Reopening as #58196 broke extensions and was reverted.
