### ISSUE TITLE
Auto-complete prompt closes if a modifier button is pressed when using custom navigation keys

### ISSUE THREAD

**Issue by djpeach** [godotengine/godot#50064]
### Godot version

3.3

### System information

MacOS BigSur 11.4

### Issue description

The autocomplete prompt in the editor closes if I press a modifier button. This is an issue for me because I bound `Cmd+H,J,K,L` to their vim equivalents (left, down, up, right). In every other editor I use, I can type to start autocomplete, then use `Cmd+..` to navigate the autocomplete dialog that pops up. I can't do this in godot bc of (I think) [this line](https://github.com/godotengine/godot/blob/9da7f0690046746b2f1430717898abd6377d003a/scene/gui/code_edit.cpp#L376). I am not sure why the `allow_unicode_handling` boolean matters when determining of code completion should cancel, but it will definitely be false since the boolean is

```
/* Allow unicode handling if:              */
	/* No Modifiers are pressed (except shift) */
	bool allow_unicode_handling = !(k->is_command_pressed() || k->is_ctrl_pressed() || k->is_alt_pressed() || k->is_meta_pressed());
```

This will most certainly be false, bc the meta key is pressed when I used `Cmd`. I have compiled locally and removed the line linked above and all works well, so I am not sure what it is for. I am hoping @Paulb23 who wrote this code will know if this is something that can be addressed, or if I am way off base here. Thanks!

### Steps to reproduce

Open any project (pref on Mac), start typing to get auto-complete, and then hit and hold the `Cmd` button. The auto-complete fails.

**Comment by timothyqiu** [comment]
FYI: `allow_unicode_handling` was actually introduced by #43663.

**Comment by EricEzaM** [comment]
You are experiencing the bug on the 3.3 version, but are looking at code for 4.0 (current master). I cannot reproduce the issue on current master - triggering autocomplete and then pressing control does not close the autocomplete.

**Comment by djpeach** [comment]
Yep, seems sticking with 4.0 will solve this issue.
