### ISSUE TITLE
No way to export uv textures with blender Better Collada Exporter

### ISSUE THREAD

**Issue by Triangle345** [godotengine/godot#5008]
**Operating system or device - Godot version:**
Windows 10

**Issue description** (what happened, and what was expected):
No uv textures are exported from blender or imported into godot.

**Steps to reproduce:**
Created simple cube with UV texture - blender render.
File->Export->Better Collada
Select all options, but there is no option for uv texture export.
Import scene in godot.

**Comment by reduz** [comment]
it should always import UV as far as i know

**Comment by Triangle345** [comment]
let me give an example .blend file that does not export with better collada.

**Comment by Triangle345** [comment]
nevermind, I was applying the texture incorrectly in blender. UV Texture export works great!

**Comment by stubbsy345** [comment]
Hey sorry but what did you find you were doing incorrectly in blender, I am having the same problem?

**Comment by Triangle345** [comment]
oh man it was last year. I dont recall. I think in the end i just use
texture painting instead of pure uvmapping

**Comment by Jackain** [comment]
If you don't see the material of your mesh when you export it with Better Collada, try changing texture and material names **in Blender** because if it's end with ".001" or something weird that does not work.

Worked for me.
