### ISSUE TITLE
Change in Camera2D.current behavior in 3.3.2

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#50091]
### Godot version

3.3.2.stable.official

### System information

Windows 10, GLES 3, GTX 2060

### Issue description

In Godot 3.2.3 and previous versions, if you had more than one camera in a scene with "current" activated, the last one in tree order would become the current camera. 

For example here lvl_camera shoud become current when the scene loads. 
![image](https://user-images.githubusercontent.com/526829/124312819-54183b80-db46-11eb-9608-860fd9b17bde.png)

In Godot 3.3.2 it seems it's no longer the case. The first camera in tree order seems to be the one that becomes current. There is something even more weird. In the same example if I move the Player node below the lvl_camera node like this:
![image](https://user-images.githubusercontent.com/526829/124313084-c25cfe00-db46-11eb-8841-a1bd16987aa6.png)
When the scene loads lvl_camera will be current but as soon as the player moves, the camera inside the player will become current. 

Another thing I noticed is that if I check the remote tree both cameras have current set to true. It also seems to happen only when the camera is part of an instanced scene.
Maybe something wrong here? https://github.com/godotengine/godot/blame/ee115d7b2d5385a80710c0f0a16009640193ff93/scene/2d/camera_2d.cpp#L417

### Steps to reproduce

1. Open Node2D.tscn in the provided project
2. run the scene
Expected: Only one camera should have current set to true. lvl_camera should be active
Actual: Both cameras have current set to true. player/camera is active

Alternative test:

1. Open Node2D.tscn in the provided project
2. Swap the tree order of player and lvl_camera so that player comes last:
![image](https://user-images.githubusercontent.com/526829/124315822-f4705f00-db4a-11eb-9fd0-c69850a5bc61.png)
3. Run the scene
4. Move the player using arrow keys
Expected: Only one camera should have current set to true. player/camera should be active
Actual: Both cameras have current set to true. lvl_camera is active until you move the player, then player/camera becomes active. Both still show current ☑ in the remote tree

### Minimal reproduction project

[CameraBug.zip](https://github.com/godotengine/godot/files/6756401/CameraBug.zip)

**Comment by Calinou** [comment]
Can you test the [3.2.4 betas/RCs](https://downloads.tuxfamily.org/godotengine/3.2.4/) and [3.3 RCs](https://downloads.tuxfamily.org/godotengine/3.3/)? This will greatly speed up troubleshooting :slightly_smiling_face:

**Comment by noidexe** [comment]
> 
> 
> Can you test the [3.2.4 betas/RCs](https://downloads.tuxfamily.org/godotengine/3.2.4/) and [3.3 RCs](https://downloads.tuxfamily.org/godotengine/3.3/) to know when the regression started? This will greatly speed up troubleshooting 🙂
It was introduced in 3.2.4 rc 4
I don't have time today to build from source and test but I think it must be something in either of this two commit by @lawnjelly :
https://github.com/godotengine/godot/commit/8763d891feee9055dd26be95ac48b8848dde8b93
https://github.com/godotengine/godot/commit/136f94fa24bc12ce86ffa354542625947bc6d1e7

**Comment by lawnjelly** [comment]
Most likely to be the process logic PR, I can take a look tomorrow.

**Comment by akien-mga** [comment]
Diff between 3.2.4 RC 3 and RC 4: https://github.com/godotengine/godot/compare/4f891b706027dc800f6949bec413f448defdd20d...dc99f04d51d6556e5ba4d9cfcce8117d168ac6f1

Yes 8763d89 seems like a likely candidate, though I don't immediate see how it would impact `current`.

**Comment by lawnjelly** [comment]
Am looking at this now. It is possible that the changes exposed a previous bug (or not dealt with properly) situation. What doesn't seem to be considered at all is this situation where you have a camera that is `current` that is added to a scene where another camera is already `current`, allowing two cameras to have their bool set.

This means that whenever either camera receives a transform notification, it tries to `_update_scroll` and change the viewport position (which is ultimately how the camera works).

The proper thing to do is have some logic to deal with the situation where a current camera is added to the scene tree and there is another camera current already. What should happen? Should the newly loaded camera take priority? Or should the old one stay current and the new one by set to not current?

This looks fairly easy to fix but we need to decide on a standard. The current behaviour (and that before 3.2.4 rc4) may have been undefined, and just produced accidental results as seen.

**Comment by akien-mga** [comment]
Fixed by #50112.
