### ISSUE TITLE
File path drag-n-drop uses double quotes even when auto-completion is set to use single quotes

### ISSUE THREAD

**Issue by sacrificerXY** [godotengine/godot#50093]
### Godot version

v3.3.2.stable.official

### System information

Windows 10

### Issue description

Godot has an auto-completion setting on whether to use single or double quotes. Drag-n-dropping files from the FileSystem panel into the Script Editor uses double quotes even when this setting is set to single quotes.

### Steps to reproduce

1. Set Editor Settings > General > Text Editor > Completion > Use Single Quotes to true.
2. Open up a gdscript in the Script Editor.
2. Try to drag-and-drop a file from the FileSystem panel into the script.
3. The file's path is pasted, but it is enclosed in double quotes.

**Comment by Calinou** [comment]
cc @KoBeWi
