### ISSUE TITLE
Global Font setting in Editor Settings broken.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#5010]
Linux 64-bit, but I got a confirmation from OSX as well. Godot compiled 5 hours ago from head
![godot_bug](https://cloud.githubusercontent.com/assets/11817561/15765096/0a1aadd2-2931-11e6-9c5a-0fadaf6b6181.png)
.

In Editor Settings, in the Global, the Font settings can't be set. The folder icon is gone and using the path does not work. Probably because having a custom font now, that one should not be present in the settings at all.

**Comment by trollworkout** [comment]
I have also tried this and it does not work equally broken on my side.

**Comment by reduz** [comment]
this is not exactly a bug.. it's an old setting that remains there that has dissapeared...
I'm going to do changes to Godot, so settings that are gone are deleted after you open and close the editor
