### ISSUE TITLE
Problem importing project from few weeks old version of Godot.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#5011]
**Operating system or device - Godot version:**
Xubuntu Linux 14.04 64-bit, Godot compiled from github few hours ago.

**Issue description** (what happened, and what was expected):
I was importing a project.
Project was created around version 2.0 stable release - but my Godot was always compiled from Github.
Lately my project was edited in newer version of Godot from 2-3 weeks ago, 2.1 alpha, DynamicFonts were implemented already. Few days ago I changed all my fonts into DynamicFont. It was working great. 

Now, when I import, the project imports fine for the first time, but fonts are not visible.
The paths to the fonts(in UI) are gone and size reset to 16. Colour of the fonts is changed to black, even if the font colour square shows (is checked) the proper colour I set for the font in previous version of Godot.

After selecting the font again and changing colour, the font shows again. - it's size looks wrong, but can be changed.

However, when I save the project in such state (with some of the fonts recreated and some not), or without recreating the fonts at all, but just opening the project and saving, it will not open again. It shows in the project manager, it starts to load, but after a while quits, leaving no error messages.
The last line I see in the terminal is:

> bind toptions
> LOCAL PATH: res://main_scene.scn from res://main_scene.scn

I will try to reimport from backup and recreate all fonts, to see if that helps, so I will report back with the results.

**REPORTING BACK:**
Unfortunately repairing all the fonts and saving the project did not change anything.
The project does not open.

### TEST PROJECT
[check.zip](https://github.com/godotengine/godot/files/297461/check.zip)

To recreate the bug one needs to:

1.     scan projects directory form project manager
2.     open the project from project manager
3.     when project opens, save it right after it opens - do not correcting invisible fonts, or correct only one of the two labels.
4.     quite project to project manager or quit Godot completely
5.     repeat the process to open the project again - it fails to load.

**Comment by volzhs** [comment]
I had similar issue.
script path is broken with some ``scn`` files those worked on few weeks ago.
So, I need to reassign gd file with all dependency broken ``scn`` files.

**Comment by freemanfromgodotengine** [comment]
@volzhs reasign gd file? How to do that?

**Comment by volzhs** [comment]
@freemanfromgodotengine with dependency editor for each scenes, one by one.

**Comment by akien-mga** [comment]
It's likely due to the various changes that were made to DynamicFont. I'm not sure if there's something to fix or if it should just be considered as a transient bug for people that were using the dev version (i.e. if importing a 2.0.x in the current HEAD works fine, then we can probably consider this bug "fixed" - we'll just have to give the workaround to the users of the old DynamicFont).

**Comment by freemanfromgodotengine** [comment]
Workaround for people using dev version would be much appreciated.

I attach the simple test project, with 2 TTF fonts to the original post ^^.
To recreate the bug one needs to:

1. scan projects directory form project manager
2. open the project from project manager
3. when project opens, save it right after it opens - do not correcting invisible fonts, or correct only one of the two labels.
4. quite project to project manager or quit Godot completely
5. repeat the process to open the project again - it fails to load.

With this test project, correcting the font's (there are 2 labels in the project) setting @ point 3 prevents the bug to occur. 
Correcting font only in one of the labels and not correcting the other one results in project not opening as well.
In my original, much bigger and more complicated project, unfortunately correcting the fonts seams not work, but I can not take into account, that could omit the correction of the font somewhere in my project by mistake, what resulted in the bug occurring again.

**Comment by akien-mga** [comment]
So it looks like you have the workaround already, you need to reassign the fonts after opening the project :) Not sure how to fix an already broken project though.

**Comment by freemanfromgodotengine** [comment]
@akien-mga  I am not sure. I have to go again through all the fonts in my project again. Maybe I missed something the last time, reassigning the fonts. It was a long day and I did it at the very end. I really hope I did miss something and it will work after all.

**Comment by freemanfromgodotengine** [comment]
I can confirm that unchecking all DynamicFonts after first load of the project into newer version of Godot, then saving the project (without set fonts at all) makes the bug go away. The project loads again without problems after that.

**Comment by reduz** [comment]
anyone else suffers from this? should we close it?

**Comment by akien-mga** [comment]
I think we can close it yes, it's a transient issue for dev users that should not affect new users (only those that tested DynamicFont after it was implemented but before FreeType support).
