### ISSUE TITLE
Add Node Subtypes Summary Cheat Sheets

### ISSUE THREAD

**Issue by samuelgrigolato** [godotengine/godot#5012]
As a newbie at Gamedev and Godot, I think a Cheat Sheet summarizing Node Subtypes (one for 2D and another for 3D) would be helpful. Some minutes ago I was considering to implement a Tile Map as I did once from scratch using SDL, but suddenly I stumbled upon the Tile Map node subtype in the pallete (lucky me, otherwise I probably would miss an opportunity to save me time and learn a cool Godot feature). Maybe I could help write it someday.

**Comment by djrm** [comment]
The godot nodes hierarchy is shown in the node palette, it also has a search bar, if you type 'Tile', TileMap is revealed, also you can check the help palette, which also has a search bar.

**Comment by vnen** [comment]
Issues about documentation should be made at https://github.com/godotengine/godot-docs.

Not wanting to sound rude, but cheat sheets are usually for users already familiarized with the tool to remember stuff. To add every feature in a cheat sheet would make it very long or too dense (so you could easily miss it anyway). You should first look in the docs if the engine provide the functionality you want. If you had a look at 2D tutorials you could see the one about tile maps.

**Comment by samuelgrigolato** [comment]
@djrm @vnen first of all, thanks for your replies!

@djrm I couldn't find the "help palette", could you help me locate it?

@vnen Maybe I didn't choose the term well, I'm not exactly thinking about a Cheat Sheet with all information (attributes, methods, events etc) regarding all node types (that would be difficult to maintain, for sure), I'm talking about a brief summary (single paragraph) of each class, where one could easily ctrl+f for "tile" and find all types whose title and/or short description matches the term. In my opinion, this is slightly different from the currently available search functionality. One option would be to enhance the currently available editor's search function, in a way that it filters not only by title but also by a short description as well. By the way, should I close this ticket and create a new one at godot-docs?

**Comment by djrm** [comment]
The thing you are looking for is already integrated in godot, and its the help palette, i dont blame you for not finding it since now it is kinda hidden, it used to be a section along with 2D, 3D, and Script, now you have to go to the script section there you will see a Search Help button.

**Comment by samuelgrigolato** [comment]
Well, you are right. I've found it now, and even better, the search field in Godot's official documentation does that as well, even searching inside pages content. Thanks for your input!
