### ISSUE TITLE
Vulkan: Depth prepass does not respect cull mode

### ISSUE THREAD

**Issue by GiantBlargg** [godotengine/godot#50124]
### Godot version

4.0.dev (c1320aa)

### System information

Arch Linux, Vulkan, AMD RX 5500 XT (mesa 21.1.3)

### Issue description

The depth pre pass always seems to render with backface culling, instead of the culling mode set by the shader. This is visually obvious with frontface culling, but it probably has performance impacts for disabled culling as well.
![Screenshot_20210703_061352](https://user-images.githubusercontent.com/1700581/124354039-3b9c3580-dbc7-11eb-86ce-6850fb24a9e3.png)
Expected (3.3.2):
![Screenshot_20210703_220630](https://user-images.githubusercontent.com/1700581/124372860-eace2080-dc4a-11eb-8a68-893d42e54625.png)

### Steps to reproduce

Create an opaque material with Cull Mode set to "Front"

### Minimal reproduction project

[Culling.zip](https://github.com/godotengine/godot/files/6758392/Culling.zip)

**Comment by Calinou** [comment]
Can you reproduce this in 3.3.2?

**Comment by GiantBlargg** [comment]
@Calinou No. This issue is not present 3.3.2

**Comment by GiantBlargg** [comment]
The cause seems to be that the shadow material is used for depth pre-pass. In many cases the shadow material is set to the default material which is backface culled.

https://github.com/godotengine/godot/blob/5c3055e0fe363e08e8cdd3f922313ec9dacfaf43/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L2467-L2471
https://github.com/godotengine/godot/blob/5c3055e0fe363e08e8cdd3f922313ec9dacfaf43/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L342-L345
