### ISSUE TITLE
Editor log cuts the bottom line

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#50121]
### Godot version

c1320aa

### System information

W10

### Issue description

![image](https://user-images.githubusercontent.com/2223172/124352958-db77b480-dc03-11eb-8f22-2c48ecf1351a.png)

### Steps to reproduce

1.
```
func _process(delta):
	print("hello world or something")
```

**Comment by Calinou** [comment]
cc @EricEzaM

**Comment by EricEzaM** [comment]
Looked into it, can't figure it out :(
