### ISSUE TITLE
Image.blend_rect extracts an incorrect source texture when dst has negative values

### ISSUE THREAD

**Issue by DarkMarmot** [godotengine/godot#50126]
### Godot version

3.3.2 stable

### System information

Windows 10, GLES3

### Issue description

The `Image.blend_rect ( Image src, Rect2 src_rect, Vector2 dst )` method behaves incorrectly if the `dst` has negative values.

If the `dst` would cause the copied data to extend off the right or bottom of the destination image, the source data is clipped appropriately.

If the `dst` is negative, one would expect that the source data would be clipped as well. Rather, the source data is clamped against the left or top edge of the `src` image, potentially pulling a completely unexpected texture rect.

I wrote a workaround in GDScript, but this could definitely be better fixed in the C++. 

This was raised before in a closed issue: https://github.com/godotengine/godot/issues/19578

Thanks!

### Steps to reproduce

I wrote a small script that pulls sections from a source texture covered in numbers and displays them.

The attached project shows examples of how the data is mutated by pulling sections from this labeled texture. Note that the texture of the number 8 within it is replaced by other numbers from the source texture when the `dst` is negative.

Just run the attached project to see how the texture clamping works. Adjust the export vars to manually experiment with different outputs if desired.

### Minimal reproduction project

[blend_rect.zip](https://github.com/godotengine/godot/files/6758508/blend_rect.zip)

**Comment by DarkMarmot** [comment]
```
void Image::blend_rect(const Ref<Image> &p_src, const Rect2 &p_src_rect, const Point2 &p_dest) {
	ERR_FAIL_COND_MSG(p_src.is_null(), "It's not a reference to a valid Image object.");
	int dsize = data.size();
	int srcdsize = p_src->data.size();
	ERR_FAIL_COND(dsize == 0);
	ERR_FAIL_COND(srcdsize == 0);
	ERR_FAIL_COND(format != p_src->format);

	Rect2i clipped_src_rect = Rect2i(0, 0, p_src->width, p_src->height).intersection(p_src_rect);

	if (p_dest.x < 0) {
		clipped_src_rect.position.x = ABS(p_dest.x);
	}
	if (p_dest.y < 0) {
		clipped_src_rect.position.y = ABS(p_dest.y);
	}
```

I'm not set up to build from source and am not very fluent in C++ -- but I believe the bottom section of the code here should be:

```
if (p_dest.x < 0) {
		clipped_src_rect.position.x = ABS(p_dest.x) + p_src_rect.position.x;
	}
	if (p_dest.y < 0) {
		clipped_src_rect.position.y = ABS(p_dest.y) + p_src_rect.position.y;
	}
```

Without, the src_rect is clamped to the left or upper side of the texture, even if pulling from the middle.

**Comment by gu-fan** [comment]
well, this still exists in 3.4.4, any workaround?
