### ISSUE TITLE
Vulkan: GPUParticles2D gradient doesn't work

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#50131]
### Godot version

e849dc1

### System information

W10

### Issue description

When you set a gradient in GPUParticles2D color ramp, they ignore the gradient and become blue:
![Znv7BYZEYL](https://user-images.githubusercontent.com/2223172/124359791-c3fdf300-dc26-11eb-89e8-2d39fd97e1a4.gif)

Interestingly, everything is fine when you convert the material to shader.

### Steps to reproduce

1. Create GPUParticles2D
2. Add process material
3. Assign gradient to color ramp

EDIT:
3D has the same problem.

EDIT2:
Reloading scene seems to fix it. But every change to gradient needs reload.

**Comment by floppyhammer** [comment]
In v4.0.alpha.custom_build [9d1626b4d], changing gradient takes effect as long as the gradient is not newly set to the color ramp.

![color_ramp](https://user-images.githubusercontent.com/28705694/152671029-fee8d05a-e496-4c0e-a335-a9abc859a9f7.gif)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/57471, which has more information about the issue at hand.
