### ISSUE TITLE
Joystick vibration

### ISSUE THREAD

**Issue by ramoas86** [godotengine/godot#5013]
I wish to use Joystick vibration with Godot.

**Comment by vnen** [comment]
Ping @Hinsbart ;)

**Comment by neikeq** [comment]
Related to #4833

**Comment by akien-mga** [comment]
Done for Linux/X11 by @nounoursheureux, it still needs to be implemented for other desktop platforms (and maybe mobile platforms too if relevant).

Issue #5043 had some interesting discussions about what the API should be like if it should be shared between desktop joystick vibration and mobile device vibration, I'll let @Hinsbart, @punto- and @nounoursheureux see how things should evolve from here.

**Comment by nounoursheureux** [comment]
I think having a separate `Vibration` class would be better for the reasons that I mentionned here: https://github.com/godotengine/godot/pull/5043#issuecomment-223806266 . But I don't feel familiar enough with the codebase to add a whole new class and do all the bindings myself, I would certainly break some stuff in the process.

**Comment by vnen** [comment]
It'd be interesting to generalize vibration for phones and joysticks. Also consider the possibility of making it a Node, as @punto- suggested in https://github.com/godotengine/godot/pull/5043#issuecomment-226112859.

**Comment by punto-** [comment]
I agree with generalizing phones and joysticks, the idea of the "default
device" and the mapping between a joystick and a device id for vibration
was good. Making it a Node I don't think is that necessary on second
thought, because it's trivial enough that it can be done with a few lines
of gdscript, it's just a couple of setters that pass the call to the OS
api. Maybe on the platformer demo we could add vibration to the enemy
explosions, or the bullet shoot animations?

**Comment by Hinsbart** [comment]
Mhh, maybe on mobile platforms the first joystick should register as device id 1? So the phone vibration can always be on 0 and they don't interfere, idk..
About making it a Node, IMO it's a nice idea. That way users can emulate (via AnimationPlayer) some of the advanced features that most of the desktop gamepad APIs provide, ie vibration envelopes (attack, sustain, release). Sure that can also be done in scripts, but using Animations would certainly be easier for a lot of people.

**Comment by bojidar-bg** [comment]
Given that device ids are now handled by InputDefault, I think the device id part is a nonissue.

(Sneaky bump)

**Comment by akien-mga** [comment]
This has been fixed years ago.

Phone vibration support is tracked in #4833.
