### ISSUE TITLE
Vulkan: SSR still broken

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#50151]
___

***Note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.dev.custom_build [5c3055e0f]

### System information

Win 10 / 1080 Ti (466.47)

### Issue description

SSR still broken, even after #50144 was merged.
Clearing shader cache also didn't fixed it.

https://user-images.githubusercontent.com/2698825/124380982-c44eca80-dcc8-11eb-9413-5803774c5d21.mp4

<details>
  <summary>Error:</summary>
  
  ```
  ERROR: Attempted to use an unused shader variant (shader is null),
   at: (.\servers/rendering/renderer_rd/pipeline_cache_rd.h:72)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6805)
ERROR: No render pipeline was set before attempting to draw.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6822)
  ```
  
</details>

### Steps to reproduce

1. Open the MRP
2. Enable SS Reflections in WorldEnvironment

### Minimal reproduction project

[Test2.zip](https://github.com/godotengine/godot/files/6759699/Test2.zip)

**Comment by atirut-w** [comment]
This made me realize how complex graphical pipelines actually are, especially 3D ones

**Comment by unfa** [comment]
I don't see this error any more, maybe thsi should be closed?
@Xartorx, can you still reproduce this?

**Comment by Xartorx** [comment]
@unfa yes i can
![image](https://user-images.githubusercontent.com/2698825/134091416-09914168-7dd0-4907-9b59-3ab403c0b28b.png)

**Comment by Talon1024** [comment]
Is this a bug that only affects NVidia GPU users?

**Comment by sboron** [comment]
Same bug by me.. :-(

`  This render pipeline requires (0) bytes of push constant data, supplied: (16)
  No render pipeline was set before attempting to draw.
  Attempted to use an unused shader variant (shader is null),
  This render pipeline requires (0) bytes of push constant data, supplied: (16)
  No render pipeline was set before attempting to draw.
`

**Comment by cardcraft** [comment]
wanted to add this godot 4.0.alpha on an rtx 3060
![Screenshot from 2022-02-04 21-30-54](https://user-images.githubusercontent.com/61369184/152628818-74ac46b7-b0d8-4694-b3b2-f168d2c556cb.png)
0

**Comment by Calinou** [comment]
> wanted to add this godot 4.0.alpha on an rtx 3060 ![Screenshot from 2022-02-04 21-30-54](https://user-images.githubusercontent.com/61369184/152628818-74ac46b7-b0d8-4694-b3b2-f168d2c556cb.png) 0

It appears to be working on your screenshot (with no error messages in the console). Those streaking artifacts are unrelated, and I'm not sure if they can be resolved without making SSR much more expensive. Temporal antialiasing will make it possible to improve SSR quality without making it more expensive.

**Comment by cardcraft** [comment]
well is there a way to fix it?

**Comment by Calinou** [comment]
> well is there a way to fix it?

Not that I know of, although increasing the material roughness will make it less noticeable.

**Comment by unfa** [comment]
Hmm. Maybe having a more expansive but accurate algorithm as an option would be nice at some point?
Or would it just be temporal AA  fixing it up by then?

**Comment by Calinou** [comment]
> Hmm. Maybe having a more expansive but accurate algorithm as an option would be nice at some point? Or would it just be temporal AA fixing it up by then?

I've opened a proposal to suggest increasing the default depth tolerance value: https://github.com/godotengine/godot-proposals/issues/3919

Regardless, we are still bound by screen-space reflections' limitations.

**Comment by BastiaanOlij** [comment]
I'm looking at some of the issues in #66756

**Comment by elvisish** [comment]
What is the current state of Screen-Space Reflections in beta 9? I turned them on in WorldEnviroment and set my materials to have high metallic and low roughness, but it doesn't appear to work at all? I'm pretty sure I've set it up properly (same as 3.x) and it's not breaking or displaying incorrectly (no streaks or black materials), it just doesn't seem to be doing any reflections.

**Comment by clayjohn** [comment]
> What is the current state of Screen-Space Reflections in beta 9? I turned them on in WorldEnviroment and set my materials to have high metallic and low roughness, but it doesn't appear to work at all? I'm pretty sure I've set it up properly (same as 3.x) and it's not breaking or displaying incorrectly (no streaks or black materials), it just doesn't seem to be doing any reflections.

@elvisish It should be mostly working. Testing locally on master it appears to be working just fine

**Comment by elvisish** [comment]
It still doesn't work on beta 8: https://github.com/godotengine/godot/issues/70507

**Comment by clayjohn** [comment]
@elvisish Beta 10 is the most recent beta.
