### ISSUE TITLE
function (Color8 ()) does not return the color

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#5015]
I was not able to achieve this (Color8 ()) function worked fine, but all the other simple functions (Color ()) return color is normal ...

**Comment by volzhs** [comment]
This is my test code.

```
var color = Color8(1,1,1,1)
print(typeof(color) == TYPE_COLOR)  >> says "True"
```

**Comment by vnen** [comment]
@OlexiyKravchuk Care to explain the specifics? Sample code and/or sample project?

**Comment by OlexiyKravchuk** [comment]
https://www.dropbox.com/s/159vplqkhdu7eaw/BUG_color8.zip?dl=0
you should enter only 8-bit values from 0 to 255

**Comment by volzhs** [comment]
``1`` is not in between 0 and 255?

**Comment by OlexiyKravchuk** [comment]
he sees it as a simple 1.0, and this is the problem ... if you leave above the 1.0 framework, everything will always be white ...

**Comment by vnen** [comment]
I see now, `Color8` is behaving the same as `Color`, accepting values only between `0` and `1`.

**Comment by Hinsbart** [comment]
The problem is [here](https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_functions.cpp#L1013).
It just passes the arguments of `Color8()` to `Color()`. 
Should be something like `(real_t)255 / *p_args[x]`
