### ISSUE TITLE
Script Editor Crashes when working with big GDScript files.

### ISSUE THREAD

**Issue by sairam4123** [godotengine/godot#50160]
### Godot version

9b8095ad0

### System information

Windows 10, Nvidia GeForce GTX 1050, 27.21.14.5771

### Issue description

Script Editor crashes whenever I try to edit a big files like around 500 lines of code.
This issue seems to appear in the newer version, so I think some PR broke this, it didn't happen before, last worked version was, `9ace46a7d`.

I'll upload the project, it contains the game, I don't know if anyother thing causes the crash, but everytime I edit my RealTimeCamera.gd which is a big file with duplicated code, it seems to crash.

### Steps to reproduce

1. Create a new project
2. Write 500 lines.
3. Now close and re-open the project.
4. Finally, make somesort of change and it will crash. (It crashes for me tho).

**Comment by sairam4123** [comment]
Currently, I'm unable to upload the project sorry. I'll keep trying.

**Comment by Calinou** [comment]
Try to get a backtrace from a debug build. You can do so by running Godot from a terminal or using a debugger such as Visual Studio's debugger.

**Comment by sairam4123** [comment]
I mean it hangs for ever, and I've to close it manually from the Task Manager and re-open it.

**Comment by sairam4123** [comment]
Found the culprit, it was the autosuggestion.

**Comment by barbaros83** [comment]
happens to me when i type something and i get autocompletion on it, and immediately afterwards if i delete that line, the editor freezes

**Comment by KoBeWi** [comment]
Can someone still reproduce this? I can edit scripts much longer than 500 without any problems.

**Comment by KoBeWi** [comment]
Forgot to check here again (and edits don't notify). Thanks for confirming.
