### ISSUE TITLE
GodotPhysics does not have an intermediate axis theorem

### ISSUE THREAD

**Issue by krwolcott** [godotengine/godot#50173]
### Godot version

4.0 dev build

### System information

Windows 10, Radeon RX580

### Issue description

A sometimes important behavior of rotating bodies is what's called the [Intermediate Axis Theorem](https://en.wikipedia.org/wiki/Tennis_racket_theorem) (also Tennis Racket Theorem, or Dzhanibekov Effect).  This effect causes rotation around the axis with the median moment of inertia to be less stable than the max or min moments.  (see also [this video](https://www.youtube.com/watch?v=1VPfZ_XzisU))

The original Godot Physics engine also lacked this feature, but the Bullet physics engine does simulate this effect quite nicely.

If the new Godot physics engine is going to leave out this effect, could we please leave Bullet in place as an alternative?

### Steps to reproduce

(In Godot 4.0)  Create a project with a RigidBody3d
Give the body a CollisionShape3d with a BoxShape
Assign the three axes of the BoxShape three significantly different lengths.
Give the body a mesh, ideally patterned in some way, to show the rotational behavior
Rotate the body around the intermediate axis (the median axial length of the collision shape)
-- the test
Apply an off-axis torque to the spinning body (apply torque to either the long or short axis)
-- the result
With Bullet, the body will become unstable in a very specific way, seeming to flip so the intermediate axis aligns almost exactly opposite what it was before.  With rotation along other axes, the perturbation settles down quickly.  This complies with observed phenomena.
With Godot Engine (4.0) the perturbation is damped almost completely in all cases.  

### Minimal reproduction project

[PhysicsTesting.zip](https://github.com/godotengine/godot/files/6761802/PhysicsTesting.zip)

**Comment by Calinou** [comment]
cc @pouleyKetchoupp

**Comment by krwolcott** [comment]
@Calinou, wow, awesome news!  Thanks!  Glad to see Bullet will be making it into 4.0!

**Comment by Calinou** [comment]
> @Calinou, wow, awesome news! Thanks! Glad to see Bullet will be making it into 4.0!

We aren't certain whether that pull request will be merged yet, so we're not making any promises about it.

**Comment by pouleyKetchoupp** [comment]
Closing the issue as this feature will be supported only in alternative physics engines.
