### ISSUE TITLE
Editor help needs a better easier-to-read layout

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5017]
Currently the editor help is hard to read. You can't tell in a glance what is a method's signature and what is its description.

![godot windows opt tools 64_2016-06-03_12-56-35](https://cloud.githubusercontent.com/assets/5599796/15784936/28b811f8-298b-11e6-9304-507eb1a74f4c.png)
- The font is also too big, especially when contrasted with the monospaced font used in the code examples.
- The font for method signature should be a bit bigger.
- The space between paragraphs is too big, while the space between methods could be bigger.
- The methods' names don't stand out. So it's hard to tell to which method this description is about. A color would go miles in this way, so if method names were e.g. yellow, it'd be much more visible (check the bottom of the previous image, which shows a link to a function in yellow).
- Sometimes the text gets too close of the right border. There should be a right margin and also a greater left margin. ![godot windows opt tools 64_2016-06-03_13-02-56](https://cloud.githubusercontent.com/assets/5599796/15785333/2557c9a2-298d-11e6-9b09-23e93642c597.png)
- New lines in `classes.xml` should not make paragraphs. It's usually hard to edit long lines, so double new lines should make paragraphs instead. Otherwise we get something like this: ![godot windows opt tools 64_2016-06-03_12-48-11](https://cloud.githubusercontent.com/assets/5599796/15785389/542f700e-298d-11e6-9437-2be883b4819c.png)

**Comment by reduz** [comment]
what is the logic used in the online doc? we should do the same as there..

**Comment by vnen** [comment]
RTD also use single newlines as paragraph markers (though this is matter of tweaking our doc build tool).

The main point here is readability and easy spot of functions. RTD shows function names in bold and also with a bullet in the beginning of the line. This might work in the editor too.

**Comment by reduz** [comment]
it seems I can never get this right, so if anyone wants to help, it's welcome

**Comment by reduz** [comment]
this code is in editor_help.cpp - EditorHelp::_, if anyone wants to give it a check be welcome:

https://github.com/godotengine/godot/blob/master/tools/editor/editor_help.cpp#L1260

**Comment by vnen** [comment]
I'm making some progress on this, but will have to look a bit more than the linked function. For now it seems to properly break paragraphs and format better the codeblocks.

**Comment by akien-mga** [comment]
Several of those points have been addressed since 2016. I propose to close this issue and a new one could be reopened with proposals matching the current design of the in-editor help. (Feel free to reopen if you prefer to keep using this one.)
