### ISSUE TITLE
High DPI scale error

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#50178]
### Godot version

3.3 Stable

### System information

MacOS 11.4

### Issue description

When I switch from an external non HDPI screen to my internal HDPI screen (one at the time), the editor scaling is not updated: 

(when I return to my HDPI screen:)
<img width="1133" alt="Screenshot 2021-07-05 at 10 15 57" src="https://user-images.githubusercontent.com/6397893/124474225-963cb980-dda0-11eb-88ec-feafe4d4abe0.png">

note: the scaling works when I use both screen at the same time

### Steps to reproduce

1. I close my laptop to only use my external (non HDPI) monitor
2. I turn off my monitor
3. I reopen my laptop

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by SlitheringMule** [comment]
The solution might possibly be to check whether the monitor is _Hidpi_ when the window is loaded / brought up, then re-scale exactly as is done when the window is moved from one screen to the other.

**Comment by timothyqiu** [comment]
Kind of similar to #41849 :)
