### ISSUE TITLE
Command line debugger enters infinite loop on Ctrl+D (end of transmission) character

### ISSUE THREAD

**Issue by lihop** [godotengine/godot#50170]
### Godot version

3.3.2-stable

### System information

NixOS 21.11

### Issue description

Typing Ctrl+D at CLI debugger prompt results in an infinite loop which also starts filling the log file at `.local/share/godot/app_userdata/<project>/logs/godot.log` with a string of the following format (script path being project dependent):
```
Debugger Break, Reason: 'Breakpoint'
*Frame 0 - res://drag_drop_script.gd:4 in function 'get_drag_data'
Enter "help" for assistance.
debug> 
```
![godot-inf-loop](https://user-images.githubusercontent.com/3696783/124399759-c5730c80-dd47-11eb-8ae3-e706aab7d0f0.gif)

**Expected behavior:**
I would expect Ctrl+D to exit the debugger which, on Linux atleast, is consistent with other REPLs/shells such as bash, python, node, and gdb.
At the very least, I would not expect the command line debugger to go into an infinite loop.

### Steps to reproduce

1. Open any Godot project with a runnable main scene.
2. Start godot cli in debug mode `godot -d`.
3. Type `Ctrl+C` to drop to debugger prompt.
4. Type `Ctrl+D`.

**Comment by lihop** [comment]
I did some digging and here is what I found:
#### Affected platforms ####
I cannot reproduce this issue on Windows.

On Windows, using the python repl for reference, I wasn't able to reproduce this issue in powershell or git-bash. The windows equivalent of Ctrl+D is Ctrl+Z (to exit python you can use Ctrl+Z + return). This had no effect on the command line debugger. In git-bash Ctrl+C and Ctrl+Z don't appear to work at all, either when using the command line debugger or python.

#### Causes ####
The debugger repl runs a `while(true)` loop that starts by calling `OS::get_stdin_string()` to get input from stdin:
https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/core/script_debugger_local.cpp#L53-L57

`OS::get_stdin_string()` in turn calls `fgets()`:
https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/drivers/unix/os_unix.cpp#L149-L159

In the case of Ctrl+C, `fgets()` returns NULL and sets the error indicator for stdin to 1 (Interrupted system call).
In the case of Ctrl+D, `fgets()` returns NULL and sets the end-of-File indicator for stdin.
In both cases `OS::get_stdin_string()` returns empty string.

However, after encountering EOF, any subsequent calls to `fgets()` will _immediately_ return NULL (without waiting for or reading any more user input), thus the command line debugger enters an infinite loop, repeating the `line == ""` case:
https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/core/script_debugger_local.cpp#L61-L65

#### Possible solutions ####
This patch to 3.3.2-stable (tested on linux) will cause the debugger to exit on Ctrl+D (on *nix platforms). It also changes the behavior of the debugger to exit on Ctrl+C (on *nix and presumably windows platforms) which would resolve https://github.com/godotengine/godot/issues/19775 if this is the desired behavior:
```patch
diff --git a/core/script_debugger_local.cpp b/core/script_debugger_local.cpp
index 3cc14daf4c..7ccec46033 100644
--- a/core/script_debugger_local.cpp
+++ b/core/script_debugger_local.cpp
@@ -53,7 +53,14 @@ void ScriptDebuggerLocal::debug(ScriptLanguage *p_script, bool p_can_continue, b
 	while (true) {
 
 		OS::get_singleton()->print("debug> ");
-		String line = OS::get_singleton()->get_stdin_string().strip_edges();
+		String line = OS::get_singleton()->get_stdin_string();
+
+		if (line == "") {
+			print_line("");
+			line = "quit";
+		} else {
+			line = line.strip_edges();
+		}
 
 		// Cache options
 		String variable_prefix = options["variable_prefix"];
```

**Comment by Xrayez** [comment]
I stumbled upon this as well in the past. I run tests using GitHub Actions in https://github.com/goostengine/goost/blob/2cf40249f90d198bf722002bf883f78fd93bbc72/.github/workflows/linux_builds.yml#L265-L267, and sometimes in case of script error the job keeps hanging for hours until the job finally stops. This also may produce huge logs files there, but looks like GitHub handles these kind of cases and cancels the job eventually.

**Comment by rcorre** [comment]
> This patch to 3.3.2-stable (tested on linux) will cause the debugger to exit on Ctrl+D (on *nix platforms). It also changes the behavior of the debugger to exit on Ctrl+C (on *nix and presumably windows platforms) which would resolve https://github.com/godotengine/godot/issues/19775 if this is the desired behavior:

IMHO `ctrl+c` currently behaves correctly (though this is debated at https://github.com/godotengine/godot/issues/19775). However, the current behavior of `ctrl+d` is pretty clearly wrong.
Would there be any objection to a patch just fixing `ctrl+d` to exit the debugger instead of loop infinitely, but leaving `ctrl+c` as-is?
