### ISSUE TITLE
Particles2D pausing physics and rendering when it is over (or equal to maybe) 100px away from the sides of the window when Local Coords are disabled. Minimal Reproduction Project included.

### ISSUE THREAD

**Issue by SlitheringMule** [godotengine/godot#50176]
### Godot version

3.3.2.stable.official

### System information

Windows 10, Intel HD Graphics

### Issue description

This is how I saw the bug:

When the source of Particles2D moves more than off screen by more than 100px in that direction (by my testing) the particles pause, then resume when you are less than 100px away from the edge of the window.

I used a RigidBody2D and KinematicBody2D to test this, and this happens even when `can_sleep` is disabled on the RigidBody2D.

I tested it in both fullscreen and normal mode, and the same problem happens with the same 100px margin.

### Steps to reproduce

Run the program and guide the character off the screen. When all the particles randomly disappear, check the coordinates. In my testing it is over (or equal to maybe) 100px away from the border of the game window.

Try running straight to one edge, and when the particles disappear, move parallel to the edge you ran into, then go back into the window. It will be obious that the particles pause as they reappear where they were when they disappeared.

This happens regardless of _Local Coords_' toggle status.

### Minimal reproduction project

[Particles2D Pausing Bug.zip](https://github.com/godotengine/godot/files/6763876/Particles2D.Pausing.Bug.zip)

**Comment by SlitheringMule** [comment]
Might be related to #34713

**Comment by Calinou** [comment]
With Particles2D, you are expected to set the visibility AABB manually. You can use the **Particles > Generate Visibility Rect** option at the top of the 2D editor while the Particles2D node is selected. This option is also available in 3D.

With CPUParticles2D, this is not required as the visibility rect is computed automatically.

**Comment by SlitheringMule** [comment]
> 
> 
> With Particles2D, you are expected to set the visibility AABB manually. You can use the **Particles > Generate Visibility Rect** option at the top of the 2D editor while the Particles2D node is selected. This option is also available in 3D.
> 
> That said, in your particular case, generating the visibility rect will not be enough since **Local Coords** is disabled. I recommend generating a visibility rect, _then_ increasing its size by adjusting **Drawing > Visibility Rect** manually. You will have to do some trial and error until it looks good in action.
> 
> With CPUParticles2D, this is not required as the visibility rect is computed automatically.

When not outside the screen's border, everything works fine with the default VisibilityRect. I thought that the VisibleRect drew particles _around_ the Particles2D emission point, so there would be no reason for it so pause when it goes outside of the zone. You can see this zone I am referring to as the blue box around the Particles2D in the editor.

However, the Visibility Rect documentation refers to the screen size too, so I think one of the two do not work.

Depending on how the Visibility Rect was actually used I could give some suggestions.

**Comment by SlitheringMule** [comment]
In my testing setting the Visibility Rect to values which prevent far away particles (from the source of the particles) from rendering do not work.

This bug also pauses the particles instead of not rendering them.

**Comment by SlitheringMule** [comment]
I've found another possible Particles2D (and CPUParticles2D) bug: #50217

**Comment by SlitheringMule** [comment]
As this bug can also be seen to happen with long enough trails when _Local Coords_ are turned on, I believe the square around the Particles2D (I know this to be controlled by the _Visibilty Rect_ as it reacts when I change the _Visibilty Rect_ values) to be extremely misleading and be removed from the Editor.

Also, I believe the _Visibilty Rect_ values should be set as offsets from the sides of the screen in the normal Vector2 direction (like how Camera2D limits are set), and the same for the other 3 corners. A margin of 100px around the edges of the screen would therefore be: (Left: -100, Top: -100, Right: 100, Bottom: 100).

Most of this likely happens with the 3D equivalent of the nodes, but I haven't tested them yet.

**Comment by Calinou** [comment]
> As this bug can also be seen to happen with long enough trails when Local Coords are turned on, I believe the square around the Particles2D (I know this to be controlled by the Visibilty Rect as it reacts when I change the Visibilty Rect values) to be extremely misleading and be removed from the Editor.

If trails get outside of the visibility rectangle, then the particles will get culled too early when they leave the viewport.

**Comment by SlitheringMule** [comment]
See the _Visibility Rect_ and the square
![image](https://user-images.githubusercontent.com/84676658/124671958-2caad100-deae-11eb-8d57-747a9ef2205f.png)

Now see the _Visibility Rect_ again and the smaller square (there is still the other, thicker square because I didn't change the _Visibility Rect_ for all the _Particles2D_s
![image](https://user-images.githubusercontent.com/84676658/124672113-6976c800-deae-11eb-9dbe-ca51d7afa635.png)

**Comment by SlitheringMule** [comment]
I think by having the **actual** _Visibility Rect_ defined like how the Camera2D limits are, it defines the _Visibility Rect_ in proportion a region instead of a region in relation to the screen, and offers the same current flexibility and illustrates the region in the editor in a way which is correct and makes sense.

**Comment by benjarmstrong** [comment]
After playing with the reproduction I'm pretty sure this is intended behavior. 

The purpose of the visibility rect is only to inform the engine when the particle system should be drawn. If the visibility rect is within the camera, the particle system will be updated and drawn every frame. Otherwise the particle system is hidden and it doesn't process. 

Individual particles are not taken into consideration when the engine decides if the particle system is visible or not. Only the visibility rect is used for performance reasons.

To avoid this behaviour you can:
- Increase the size of the visibility rect
- Use CPUParticles2D instead of Particles2D. As Calinou mentioned this automatically handle the visibility rect for you, with the trade off being that it will run on the CPU instead of the GPU (slower processing+rendering)
- If you are using local coordinates, you can click on the Particle2D node, click on the 'Particles' menu that appears in the 2D viewport toolbar and click 'Generate Visibility Rect'. This works regardless of whether local coordinates are enabled, but generally works better with local coordinates enabled.

On a somewhat related note: does anyone know if the 'preprocess' property is meant to take effect when a particle system's visibility changes due to culling, or is that only when the node is instantiated?

**Comment by SlitheringMule** [comment]
> 
> 
> After playing with the reproduction I'm pretty sure this is intended behavior.
> 
> The purpose of the visibility rect is only to inform the engine when the particle system should be drawn. If the visibility rect is within the camera, the particle system will be updated and drawn every frame. Otherwise the particle system is hidden and it doesn't process.
> 
> Individual particles are not taken into consideration when the engine decides if the particle system is visible or not. Only the visibility rect is used for performance reasons.
> 
> To avoid this behaviour you can:
> 
>     * Increase the size of the visibility rect
> 
>     * Use CPUParticles2D instead of Particles2D. As Calinou mentioned this automatically handle the visibility rect for you, with the trade off being that it will run on the CPU instead of the GPU (slower processing+rendering)
> 
>     * If you are using local coordinates, you can click on the Particle2D node, click on the 'Particles' menu that appears in the 2D viewport toolbar and click 'Generate Visibility Rect'. This works regardless of whether local coordinates are enabled, but generally works better with local coordinates enabled.
> 
> 
> On a somewhat related note: does anyone know if the 'preprocess' property is meant to take effect when a particle system's visibility changes due to culling, or is that only when the node is instantiated?

So if the Particles2D node is in the _Visibility Rect_, which does not move, it is rendered?

Then how come moving more than 100 to the right from the original position of the node still renders the particles?

**Comment by SlitheringMule** [comment]
From my observations, the _Visibility Rect_ is used as follows:

The region:
`x + windowwidth+ w`
`y + windowheight + h`
or can be written as:
`Rect2(x, y, windowwidth + w, window_height + h)`

However, this is not what is displayed in the editor by the blue rectangle.

**Comment by benjarmstrong** [comment]
> So if the Particles2D node is in the Visibility Rect, which does not move, it is rendered?
> Then how come moving more than 100 to the right from the original position of the node still renders the particles?

The visibility rect moves with the node.

When you specify the rect (-100,-100,200,200) those coordinates are relative to the node's position.

**Comment by SlitheringMule** [comment]
> 
> 
> > So if the Particles2D node is in the Visibility Rect, which does not move, it is rendered?
> > Then how come moving more than 100 to the right from the original position of the node still renders the particles?
> 
> The visibility rect moves with the node.
> 
> When you specify the rect (-100,-100,200,200) those coordinates are relative to the node's position.

Then what's the point of having a _Visibility Rect_ if the _Particles2D_ node doesn't move away from its parent?

Also why do the particles pause after exiting this region:
`x + windowwidth+ w`
by
`y + windowheight + h`

**Comment by benjarmstrong** [comment]
> Then what's the point of having a _Visibility Rect_ if the _Particles2D_ node doesn't move away from its parent?

If the camera moves away from the Particles2D node the engine uses the visibility rect to detect when it no longer has to be drawn and processed

> Also why do the particles pause after exiting this region

When the visibility rect is outside of the camera the particles stop processing entirely. They will only start processing again once the visibility rect overlaps within the camera

**Comment by SlitheringMule** [comment]
> 
> 
> > Then what's the point of having a _Visibility Rect_ if the _Particles2D_ node doesn't move away from its parent?
> 
> If the camera moves away from the Particles2D node the engine uses the visibility rect to detect when it no longer has to be drawn and processed
> 
> > Also why do the particles pause after exiting this region
> 
> When the visibility rect is outside of the camera the particles stop processing entirely. They will only start processing again once the visibility rect overlaps within the camera

So if the *Visibility Rect* is on the screen then the particles are processed? Is that right?

**Comment by benjarmstrong** [comment]
Yeah that's correct

**Comment by SlitheringMule** [comment]
> 
> 
> Yeah that's correct

Ah I understand now! I couldn't understand that from the blue box in the editor 😄.
Is there a way to make the particles always process?

**Comment by Calinou** [comment]
> Is there a way to make the particles always process?

Set their visibility rect to a very large value.

**Comment by SlitheringMule** [comment]
> 
> 
> > Is there a way to make the particles always process?
> 
> Set their visibility rect to a very large value (something like `Rect2(-10000, -10000, 20000, 20000)`). Nonetheless, doing so is inefficient, especially when you have multiple particle nodes active.

Do CPUParticles have an infinite Visibility Rect?

My particles are coming off a rotating and moving object, so it's quite neccesary that they don't pause :-)

**Comment by Calinou** [comment]
> Do CPUParticles have an infinite Visibility Rect?

CPUParticles have their visibility rect automatically computed. In my experience, it works pretty well with fast-moving particles with local coords disabled. If it doesn't compute correctly, it's a bug :slightly_smiling_face:

**Comment by SlitheringMule** [comment]
As it seem this 'bug' was intended, I'll close this issue! 😄
