### ISSUE TITLE
It's almost impossible to deselect text in editor help

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5018]
If you select a text in editor help, the selection doesn't go away if you click somewhere else (as it is expected).

You might be able to deselect by dragging in an empty area between methods, but that's not easy.

**Comment by Hinsbart** [comment]
This always annoyed me a lot.. As the type of guy who tends to randomly select text when he's thinking :p

**Comment by volzhs** [comment]
![reset_select](https://cloud.githubusercontent.com/assets/8281454/15787252/2cf0f840-29fc-11e6-8eaa-8eadf8c7811a.gif)

This is what I did for test.

- Not deselect with moving scrollbar
- Not deselect with wheel scroll
- Deselect when click some where

@vnen @Hinsbart does it seem good?

**Comment by Hinsbart** [comment]
Indeed, looks just right :)

**Comment by vnen** [comment]
@volzhs cool :)
