### ISSUE TITLE
Hotkey to delete bezier handle points

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#502]
_Bugsquad edit:_
- Alt + right click already works to delete normal points in 3D paths
- The hotkey could be extended to also delete bezier handle points in 3D paths, and both normal and bezier handle points in 2D paths

---

I wouldn't call this a bug. Maybe it is more inconsitancy and a small addition.
At the moment you can create new points for your curve by ctrl+click.
With shift you can add bezier handles for each point.

At the moment it is not possible to delete existing handle points or normal points for 2d Pathes . 
In 3D deleting normal points at least works with alt+rightclick.

To make it more consistent it would be great to add the alt+rightclick combination for 2d pathes for normal points and bezier handle points.
And for 3d pathes for bezier handle points.

**Comment by akien-mga** [comment]
See also #2745 for a general-purpose feature request about hotkey listing and redefinition.

**Comment by akien-mga** [comment]
This can now be implemented properly as we have hotkey definition settings.

**Comment by voithos** [comment]
I tried looking into this with the current master, and it seems like godot has changed a bit (at least on x11):
- <kbd>Alt</kbd>+right-click no longer does anything - instead, nodes can now be deleted via single right-click (no modifiers). This works in both 2d as well as 3d paths.
- Holding down <kbd>Ctrl</kbd> adds new points and holding down <kbd>Shift</kbd> adds new Bezier handles.

So, it seems like the only thing missing is being able to delete Bezier handles (ideally via right-click, I suppose). And, this appears to be currently impossible in both 2d and 3d paths.

On a related note, from my (very limited) exploration, the hotkey definition system seems to only work with keyboard-only shortcuts, right? So it wouldn't really work here as-is.
