### ISSUE TITLE
find() only returns single index in array with duplicates.

### ISSUE THREAD

**Issue by independentCog** [godotengine/godot#5020]
**Operating system or device - Godot version:**
Ubuntu 16.04 Godot v2 stable

**Issue description** (what happened, and what was expected):
test_arr["test0","test1","test2","test2"]
using find on this array with return only index 2 instead while ignoring 3 three even though it also has the same value. Is there a way to have it return multiple indexes that share the same value?

Not sure if was intentional or not just mainly curious about the behavior.

**Steps to reproduce:**
```
var test_arr = ["test0","test1","test2","test2"]
for i in range(test_arr.size()):
	print("1st loop")
	print(test_arr[i])
	for j in range(test_arr.size()):
		print("2nd loop")
		print(test_arr[j])
		print(test_arr.find("test2"))
```

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment]
Is this common behavior on other languages with this logic?
It just try to find first index of ``"test2"`` in ``test_arr`` with 4x4 times.

maybe it will help to have a second parameter to set start index.

**Comment by independentCog** [comment]
Or if the array has duplicate values it could return the indexes in the form of a separate array to reference those elements as needed. 
I also thought it would be neat to have an array function that checks for duplicates and returns a bool if any are found, possibly another that removes them.

**Comment by volzhs** [comment]
@independentCog that would break compatibility.

**Comment by independentCog** [comment]
you mean by it being returned as an array instead of an int? If the element is unique just return it as a single element array.
As far as I know:
```
var test_arr = [2]
var test = test_arr[0] + 2
print(test)
```
prints out 4. It could still be used for manipulation with other ints.
I have much yet to learn in the ways of mojo and the force, so please correct me as needed.

**Comment by volzhs** [comment]
I mean ``find()`` method.
This is what I did for my game.

```gdscript
if arr.find(element) >= 0:
    # do something
```

If it returns array instead of int, I need to add ``.size()`` and comparison operator everywhere.
And it's not typical compared to other languages.

**Comment by volzhs** [comment]
If you really want it, it's better to make another method for it. like ``find_all``

**Comment by bojidar-bg** [comment]
I think it would be nice if we had `find(value, from)` as well.

**Comment by volzhs** [comment]
@bojidar-bg there will be somebody to ask find element from the last...

**Comment by akien-mga** [comment]
Yeah a `find(value, from=0)` would be nice, it's what we have for `String` already.

> there will be somebody to ask find element from the last...

`find(value, -1)` :p
More seriously, `String` has `find_last(value)` for that, we could use the same maybe.

**Comment by independentCog** [comment]
This whole thing came up when I was going about ways to catch duplicates in an array of strings. I tried to get it to skip past when two of the same element were comparing with continue.. but yeah lol it was a thought. Now as I understand it, its behavior is similar to .index in python. I have a way to find duplicates but I feel that it could be sleeker. Python has about 30 ways to do this some of which are one liners from what I've seen. While somewhat on topic in gdscript whats the way to do that with the lowest overhead on very small 5 element array?

**Comment by volzhs** [comment]
The engine is made for general purpose, and should provides minimal, promising and making same result function.
The engine is not AlphaGo.

**Comment by independentCog** [comment]
Than again AlphaGo did get awarded an honorary 9-dan ;P

**Comment by volzhs** [comment]
My last comment.

>I also thought it would be neat to have an array function that checks for duplicates and returns a bool if any are found, possibly another that removes them.

What do you feel your engine decide some function returns random type instead of a certain type,
like a certain function could returns bool, int, float, string, array, object.
That certain function returns different type of value when array size is 5 or 5000 or 500000000000.
How can you make to be satisfied your user who use your engine if you are making one in this case?

It's my mistake if you can predict what AlphaGo returns.

**Comment by J08nY** [comment]
How about having `rfind(value)` for reverse search, and `count(value)` to return the amount of times an element is in an Array? I can see those methods getting used. I think something like `find_all(value)` is easily implemented by users. I don't think it's worth adding it since the difference in speed in GDScript vs native should not be so big for such a simple operation(O(n)).

**Comment by volzhs** [comment]
@J08nY That would be good. :)

**Comment by independentCog** [comment]
@volzhs agreed. As I've said I have much to learn and just satisfying my curiosity. Thanks for helping with that. :)

**Comment by volzhs** [comment]
@independentCog I'm glad to hear that. I just tried to help as much as I can.

**Comment by reduz** [comment]
you already have find(what,from=0)

**Comment by vnen** [comment]
String has find(what,from=0), Array has only find(what).

**Comment by reduz** [comment]
oh.. you meant this for array, this is fine by me if you want to add it to
Array, should keep being compatible
