### ISSUE TITLE
[GodotPhysics] CharacterBody3D gets warped unexpectedly when interacting with certain concave colliders

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#50218]
### Godot version

6c2c643aa72d696bee55d3449783c8c78fe634f6

### System information

Windows 10, Vulkan, Nvidia GTX 1080 (471.11)

### Issue description

CharacterController3D nodes experience erratic and unexpected behaviour when colliding with certain concave colliders in the world. This can manifest in the form jitter, but in some cases, also being warped unexpectedly. I've included a sample project which demonstrates the warping a fairly reproducible manner.

### Steps to reproduce

Open the sample project and use WSAD keys to move the capsule character controller into the podium. Touching it will cause unexpected warping and may even trap the character controller in the ground if approached from the side.

### Minimal reproduction project

[collision_bugs.zip](https://github.com/godotengine/godot/files/6772308/collision_bugs.zip)

**Comment by SaracenOne** [comment]
Update on this issue indicates that toggle the backface collision flag on the concave geometry seems to address the warping, heavily implying the bug is related to handling of collision normals.

**Comment by Calinou** [comment]
Note that the MRP will display "test_scene.tscn is invalid or corrupt" when importing the project for the first time, but opening the scene manually works.
