### ISSUE TITLE
move_and_slide takes 0 arguments 

### ISSUE THREAD

**Issue by Galileo-dev** [godotengine/godot#50235]
### Godot version

4.0.dev

### System information

Windows 10,  Vulkan

### Issue description

move_and_slide takes 0 arguments

`Parser Error: Too many arguments for "move_and_slide()" call. Expected at most 0 but received 2.`

### Steps to reproduce

1. Create a CharacterBody3D.
2. Attach a script that extends CharacterBody3D
3. add 
```
func _physics_process(delta):
    move_and_slide(Vector.UP, 2)

```

**Comment by Calinou** [comment]
This is expected with the [physics nodes reorganization](https://github.com/godotengine/godot/pull/48908). Read that pull request's description for more information.

**Comment by pouleyKetchoupp** [comment]
For info, the documentation has been updated with this change. Arguments in `move_and_slide` have all become properties instead:
https://github.com/godotengine/godot/blob/master/doc/classes/CharacterBody3D.xml
