### ISSUE TITLE
Vulkan: ORMMaterial3D has a redundant Ambient Occlusion section

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#50231]
### Godot version

4.0.dev (7bd7b8f5e)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

ORMMaterial3D has a redundant Ambient Occlusion section. The Orm section already provides an ORM texture that should provide an ambient occlusion map.

The ambient occlusion **Light Affect** property could still be kept to allow tweaking this value, but I noticed that [the Metallic **Specular** property is also no longer available in ORMMaterial3D](https://github.com/godotengine/godot/issues/50232). I don't know if this is a bug or intended.

Enabling this Ambient Occlusion breaks the material rendering.

#### Disabled (correct)

![2021-07-07_00 09 58](https://user-images.githubusercontent.com/180032/124672915-2d486500-deb8-11eb-8f44-0345cbe0cb82.png)

#### Enabled (broken)

![2021-07-07_00 10 10](https://user-images.githubusercontent.com/180032/124672921-2f122880-deb8-11eb-8acf-402de1941a0f.png)

### Steps to reproduce

- Create an ORMMaterial3D resource in the inspector dock.

### Minimal reproduction project

[test_orm.zip](https://github.com/godotengine/godot/files/6773042/test_orm.zip)

**Comment by clayjohn** [comment]
The "Ambient Occlusion" section enables ambient occlusion, it isn't just for reading from the texture. Unlike roughness and metallic, you can choose whether to use ambient occlusion, so it makes sense to have a section still.
