### ISSUE TITLE
Setting a GradientTexture's width to 999999999 crashes the editor.

### ISSUE THREAD

**Issue by SlitheringMule** [godotengine/godot#50249]
### Godot version

3.3.2.stable.official

### System information

Windows 10, Intel HD Graphics

### Issue description

Setting a _GradientTexture_'s _width_ to _999999999_ crashes the editor.

### Steps to reproduce

This is the setup I had:

A _Sprite_ with a _GradientTexture_ as its _Texture_, and its _width_ set to _999999999_.

**Comment by Calinou** [comment]
The property hint should limit its length to 16384, since most GPUs don't support textures larger than 16384 pixels in either dimension.

This can also be enforced in the setter in case you're setting its width via a script.

**Comment by SlitheringMule** [comment]
![image](https://user-images.githubusercontent.com/84676658/124790230-e6ec1800-df42-11eb-8b11-5dcc5bc20769.png)
The property is enforced but not prevented in the editor, @Calinou's suggested fix should work!
