### ISSUE TITLE
Inheriting two classes indirectly and instancing results in silent crash of the engine

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#5024]
**Operating system or device - Godot version:**
Godot latest build - LInux 64

**Issue description** (what happened, and what was expected):

Instancing a class in gdscript that inherits two classes results in a silent crash of the engine

**Steps to reproduce:**

try to execute this in a gdscript file:

```
class A:
	func _init():
		pass

class B extends A:
	func _init():
		pass

class C extends B:
	func _init():
		pass

func _ready():
     var c = C.new()
```

**Comment by m4nu3lf** [comment]
I think the problem is just an inner class inheriting, as it appears also without inheriting from one class

**Comment by reduz** [comment]
I can't reproduce.. no crash.

**Comment by reduz** [comment]
tried again, still can't reproduce. Please reopen if you manage to do a minimal project where you manage to crash it

**Comment by m4nu3lf** [comment]
There must be something else, in conjunction to the hierarchy, that is causing this in my project. I can't reproduce it otuside my project either
