### ISSUE TITLE
Text Editor's block_caret options when enabled has wrong offset

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50245]
### Godot version

v4.0.dev.custom_build [cb4e42155]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

When the user enables block_caret option, it has wrong offset:

![image](https://user-images.githubusercontent.com/58845030/124763719-aa9cc580-df0a-11eb-91c0-0afb87f067e0.png)

over non-empty lines is fine:
![image](https://user-images.githubusercontent.com/58845030/124763817-c011ef80-df0a-11eb-8bb3-f0642a691039.png)

over empty lines it has wrong offset:
![image](https://user-images.githubusercontent.com/58845030/124763873-ce600b80-df0a-11eb-9a62-adaf6106a5cf.png)

### Steps to reproduce

* Click Editor
* Editor Settings
* Text Editor
* Cursor
* block_caret
* Enable it!

### Minimal reproduction project

N/a

**Comment by VedatGunel** [comment]
Seems to be a regression from #41100. Insert mode has the same problem.

From what I understand, `shaped_text_get_descent` and `shaped_text_get_ascent` returns 0 for empty text, which causes the wrong positioning.
https://github.com/godotengine/godot/blob/60add98a4cff0d27c6aa2f52042555eccb86ed70/scene/gui/text_edit.cpp#L1419-L1426

cc @bruvzg
