### ISSUE TITLE
[Workflow] Allow AnimationTree to have an array of AnimPlayer

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50246]
### Godot version

v4.0.dev.custom_build [cb4e42155]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

The current AnimationTree doesnt fill the use case, where the user has for example, two separate animations that needs to play toguether at same time, this isnt current possible with AnimationTree which accepts only one ANimationPlayer.

This could be solved by having all animations in one-file but its against project-organization, and gets very cumbersome when dealing with more and more new animations

![image](https://user-images.githubusercontent.com/58845030/124764576-7d044c00-df0b-11eb-8f47-9dfb928dce0b.png)

The solution would be having the AnimPlayer of AnimationTree as an array which accepts 1-N Animation Trees!

### Steps to reproduce

N/a

### Minimal reproduction project

N/a

**Comment by Chaosus** [comment]
This sounds like a proposal and should be created at: https://github.com/godotengine/godot-proposals
