### ISSUE TITLE
godot became slow suddenly from opening to loading games. Game is having just 1 fps.

### ISSUE THREAD

**Issue by aanishacharyaa** [godotengine/godot#50241]
### Godot version

3.3.2. stable official

### System information

arch linux 64bit 

### Issue description

suddenly godot became slow. I can see the clear difference. When it is slow it loads project slowly and loads like the image attached 

![ss](https://user-images.githubusercontent.com/60659030/124706770-6fec5a80-df15-11eb-8122-fbc1f9f80a6d.png)

When It loads like this and take 3-5 sec time I know it's going to be slow. It comes randomly and goes randomly, But this time I'm stuck with it. Game only produce 1-5 fps.

### Steps to reproduce

I really don't know what is causing it. some say on Internet that having external keyboard or mouse can cause it. I tried removing them but no sucess

**Comment by SirQuartz** [comment]
We'd really need a minimal reproduction project and more information on your hardware specs to understand what's going on here because this is almost definitely specific to the project you're loading. Especially if it normally isn't slow when you use it.

If you load an empty/new project is the engine slow?

**Comment by aanishacharyaa** [comment]
no it is happening to all projects @SirQuartz

**Comment by SirQuartz** [comment]
> no it is happening to all projects @SirQuartz

That is odd, not really sure what could be causing that.

**Comment by Zireael07** [comment]
Most likely duplicate of https://github.com/godotengine/godot/issues/43351

@aanishacharyaa: Post your hardware specs and check for any odd USB peripherals.

**Comment by aanishacharyaa** [comment]
@Zireael07  @SirQuartz @Calinou  gtx 970m with intel i7 .. I have same USB peripherals attached as before when it was running normally.Even then to cross check I tried removing all usb and restarted os but the result is same. 

here is cpu usage when godot is not open

![normal](https://user-images.githubusercontent.com/60659030/124723827-0fffaf00-df29-11eb-90fd-74ccd6231006.png)

when godot is loaded and editor is open

![just editor](https://user-images.githubusercontent.com/60659030/124723974-2c9be700-df29-11eb-9fd2-141f94f558dc.png)

and when I play the project 

![running game](https://user-images.githubusercontent.com/60659030/124724007-3887a900-df29-11eb-8d79-fa1d3c793d8a.png)

seems no gpu acceleration at all

**Comment by aanishacharyaa** [comment]
@Zireael07 @SirQuartz @Calinou gtx 970m with intel i7 .. I have same USB peripherals attached as before when it was running normally.Even then to cross check I tried removing all usb and restarted os but the result is same.

here is cpu usage when godot is not open

![normal2](https://user-images.githubusercontent.com/60659030/124727611-805bff80-df2c-11eb-9318-769a2bef087a.png)

when godot is loaded and editor is open

![just editor](https://user-images.githubusercontent.com/60659030/124727711-94076600-df2c-11eb-89e5-c50370827f8e.png)

and when I play the project

![running game](https://user-images.githubusercontent.com/60659030/124727736-9a95dd80-df2c-11eb-9c11-79a06bcf7854.png)

seems no gpu acceleration at all

**Comment by qarmin** [comment]
Are you using Nouveau or proprietary drivers?

**Comment by aanishacharyaa** [comment]
@qarmin  I'm using nvidia proprietary driver 465.31

**Comment by Calinou** [comment]
> Most likely duplicate of https://github.com/godotengine/godot/issues/43351

That issue is about the `master` branch, whereas this issue was reported on 3.3.2.

**Comment by Zireael07** [comment]
Whoops, meant to link https://github.com/godotengine/godot/issues/20566 and didn't double check.

**Comment by Calinou** [comment]
> Whoops, meant to link #20566 and didn't double check.

That issue is Windows-only as far as I know. I don't see a reason as to why it would affect other platforms.

**Comment by aanishacharyaa** [comment]
okay so after trying lot of things...Nothing worked out. At last reinstalling the NVIDIA driver did solve the problem. Before simple restart was the trick. But still one feel hopeless when it happens and this thing only affects Godot so I guess there is something to be fixed in Godot itself.

**Comment by Calinou** [comment]
> But still one feel hopeless when it happens and this thing only affects Godot so I guess there is something to be fixed in Godot itself.

Without precise reproduction steps, it's impossible for us to do anything, so I'll have to close this. It's good to hear you managed to solve the issue nonetheless :slightly_smiling_face:

**Comment by aanishacharyaa** [comment]
here I am again with same issue.

**Comment by aanishacharyaa** [comment]
@Calinou here I am again with same issue.

**Comment by Calinou** [comment]
> @Calinou here I am again with same issue.

What is your GPU temperature while running Godot? If it's too hign, thermal throttling will kick in.

Also, I recommend using the command line `nvidia-smi` tool to check the GPU clocks while Godot is running. Do you still get slowness when forcing high performance mode in the PowerMizer section of `nvidia-settings`?

**Comment by aanishacharyaa** [comment]
Actually , I reinstalled drivers again to fix it quickly. I'll check it when it happens next.

**Comment by aanishacharyaa** [comment]
here it's again. I think to use Godot I need to reinstall drivers every boot. 

Here I am attaching NVIDIA GPU states when I run the game

![greenwithenvy](https://user-images.githubusercontent.com/60659030/125025715-cafe8880-e0a0-11eb-8203-d960378d47f0.png)

GPU load is avg 10 to 11 percent till the game over screen. On game over screen it's 2-3 percent and when only editor is open it's 2 percent. So it seems it dose use GPU but very limited.CPU instead bumps to max

**Comment by Zireael07** [comment]
If you need to reinstall drivers every boot for Godot to work acceptably, there is something wrong with your computer's settings or the drivers themselves.

**Comment by aanishacharyaa** [comment]
@Zireael07 then why it only affects Godot and not any other programs ?

**Comment by Zireael07** [comment]
Other programs may not use OpenGL at all (most office software) or, in case of games, they might not use OpenGL at all but Vulkan or DirectX, or use a different version of OpenGL... plus there are so many ways to implement things in OpenGL, that some drivers like some things more but some less. For instance, in a completely different OpenGL project, the author discovered that Intel cards don't like repeated swap commands, so, counterintuitively, caching glyphs did not help...

**Comment by aanishacharyaa** [comment]
@Calinou you can close the issue. I can confirm that it is a NVIDIA driver issue in arch Linux.

for anyone experiencing same issue can look into this

https://bbs.archlinux.org/viewtopic.php?id=258360
https://bugs.archlinux.org/task/70287

**Comment by aanishacharyaa** [comment]
I can confirm that it is a NVIDIA driver issue in arch Linux.

for anyone experiencing same issue can look into this

https://bbs.archlinux.org/viewtopic.php?id=258360
https://bugs.archlinux.org/task/70287
