### ISSUE TITLE
EditorPropertyText misbehavior for LineEdit with `text` longer than `max_length`

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#50243]
### Godot version

4.0.dev (7428c0762)

### System information

Linux, Mageia 9 x86_64

### Issue description

When editing a `LineEdit`'s `text` property in the Inspector with a non-zero `max_length` property, a weird wrap around of the caret happens when hitting the max length. The caret jumps to the first column each time you attempt to input a new char that exceeds the max length.

This also triggers the unexpected behavior that new keypresses will insert characters at the start of the string and it's the end of the pre-existing string which gets truncated.

![Peek 2021-07-07 13-30](https://user-images.githubusercontent.com/4701338/124752040-a206b800-df27-11eb-9139-0d8c07981621.gif)

Expected behavior would be that the caret would stay at its current position (and the excess char would still not be inserted, as it can't fit).

See https://github.com/godotengine/godot/pull/50200#issuecomment-874684045 for details, the problem seems to be due to #44971 which prevents updates when the text doesn't change. And since the Inspector refreshes and not update is sent, the caret position might be reset?

We'd need to find a different fix for #42488 if we want to keep sending updates for actions that don't modify the text.

CC @pouleyKetchoupp 

### Steps to reproduce

- Add `LineEdit`, set `max_length` to something like 10
- Type enough text in the `text` property to reach max length (e.g. "Hello world")
- See the caret go back to 0 when you exceed the max length

### Minimal reproduction project

[LineEdit-max_length-caret.zip](https://github.com/godotengine/godot/files/6776762/LineEdit-max_length-caret.zip)

**Comment by pouleyKetchoupp** [comment]
Good news:
#44971 is not needed anymore to fix #42488 on master since #45879 is changing the inspector to poll updated properties, so it can be safely reverted now if needed.

Bad news:
From what I've tested, reverting this fix doesn't fully solve the `max_length` issue. The caret is still being reset to the beginning when `max_length` is reached.
