### ISSUE TITLE
Ctrl+A sometimes opens the Create New Node window while a text editor is focused

### ISSUE THREAD

**Issue by craigostrin** [godotengine/godot#50271]
### Godot version

3.3.2.stable.official

### System information

Windows 10

### Issue description

When a text editor is focused (e.g., the script editor, a string-based property in the Inspector) and I press Ctrl+A, Godot highlights all text in the editor (good) and sometimes opens the Create New Node window (bad).

### Steps to reproduce

The bug doesn't happen every time you press Ctrl+A in a text editor, only in certain situations.

The easiest way to reproduce the bug is to use the Ctrl+A shortcut in the 2D or 3D view to open the Create New Node window, close the window, then go to any text editor and press Ctrl+A.

**Comment by volzhs** [comment]
related issue #38922 #36205
it seems fixed on master #42109 but look not backport to 3.x
@akien-mga should know better its state

**Comment by akien-mga** [comment]
Indeed this is fixed in `master` but the fix can't be backported. So either this can be left unfixed, or the shortcuts should be changed to avoid conflicting (likely changing the *Create New Node* shortcut).

**Comment by EricEzaM** [comment]
Please direct further discussion to #52861
