### ISSUE TITLE
LSP doesn't implement the mandatory method `textDocument/didClose`

### ISSUE THREAD

**Issue by dcampos** [godotengine/godot#50272]
### Godot version

3.3.2.stable

### System information

Linux Mint

### Issue description

I believe there is an issue regarding the LSP implementation in Godot. The LSP documentation states the following:

> Client support for `textDocument/didOpen`, `textDocument/didChange` and `textDocument/didClose` notifications is mandatory in the protocol and clients can not opt out supporting them.

Currently, there are only implementations for `didOpen` and `didChange`, but an implementation for the `didClose` method is missing. This causes errors with clients that expect it to be implemented, which is the case with Neovim's built-in LSP client.

As it can be seen in  neovim/neovim#12633, Godot responds with an error in such occasions:

```
error = {
    code = -32601,
    message = "Method not found: didClose"
}
```

### Steps to reproduce

1. Install latest Neovim stable.
2. Install nvim-lspconfig
3. Enable GDScript LSP with nvim-lspconfig
4. Open a project in Godot
5. Open Neovim and edit a GDScript file from the same project
6. Run `:edit` to reload the file

**Comment by akien-mga** [comment]
CC @Razoric480
