### ISSUE TITLE
Completion options popup has incorrect width

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#50275]
### Godot version

bfc14a6359f6a466999af37f20c71269e9952328

### System information

Windows 10

### Issue description

Size looking incorrect and some options are overlapping the width limit.

![image](https://user-images.githubusercontent.com/3036176/124893516-7812cb80-dfe3-11eb-91d0-29f85a8d94fc.png)
![image](https://user-images.githubusercontent.com/3036176/124894473-5c5bf500-dfe4-11eb-87fa-a0ef60be6d64.png)

It seems like a regression from one of the @bruvzg commits...

### Steps to reproduce

Call a completion option in GDScript or shader editors.

### Minimal reproduction project

Too easy to reproduce.

**Comment by floppyhammer** [comment]
I'm also at v4.0.dev.custom_build [bfc14a635] but I'm unable to reproduce it.
![image](https://user-images.githubusercontent.com/28705694/124912981-2c7f1280-e021-11eb-983c-efe23559d6c6.png)
![image](https://user-images.githubusercontent.com/28705694/124912885-0f4a4400-e021-11eb-823f-90c2baa20072.png)

**Comment by Calinou** [comment]
@floppyhammer Chaosus is using a low editor scale and high code editor font size, while you are using a high editor scale and low code editor font size (look at the szie of the indent icons).
