### ISSUE TITLE
KinematicBody2D `move_and_collide()` fails to report collision in the case of very small safety margin

### ISSUE THREAD

**Issue by tomsaram** [godotengine/godot#50287]
### Godot version

3.3.2.stable

### System information

Windows 10

### Issue description

The `move_to_collide()` returns a null value, even though the moving object clearly interacts with the static object. This is triggered when two conditions are met:
1. The moving object has a small safety margin.
2. The moving object starts overlapping with the static object, with a small depth.

### Steps to reproduce

Open the reproduction project and run the scene. The moving object attempts to move downwards but is blocked by the static object. 

The expected behavior is for the moving object to report a collision on the first `_physics_process()`, but instead, it does not report collision until the second `_physics_process()`, even though judging by the change of position, the object is clearly blocked from the start.

Changing the safety margin to a bigger value or starting from a larger depth (e.g. `y = 256.05` instead of `256.02`) makes this phenomenon disappear.

### Minimal reproduction project

[collision_bug_example.zip](https://github.com/godotengine/godot/files/6786535/collision_bug_example.zip)

**Comment by Calinou** [comment]
Can you reproduce this after increasing **Physics Fps** in the project settings to a higher value (like 120 or 180)?

**Comment by tomsaram** [comment]
> Can you reproduce this after increasing **Physics Fps** in the project settings to a higher value (like 120 or 180)?

I increased it to 200 and the bug can still be replicated.

**Comment by pouleyKetchoupp** [comment]
Fixed in 4.0, probably in https://github.com/godotengine/godot/pull/52953.
