### ISSUE TITLE
Typing only `print` in the script editor spams the console with "found bug?"

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5028]
**Operating system or device - Godot version:**
Godot 2.0.3 and master, Mageia 6 x86_64.

**Issue description** (what happened, and what was expected):
When starting to type `print` or `print(` in the text editor, the code parser properly notifies the user that the the syntax is wrong.
But the console gets spammed with messages that suggest that the parser is failing to understand the situation:
```
found bug?
No completion
found bug?
found bug?
hint: void print( |var what|, var ... )
found bug?
```

**Steps to reproduce:**
Start typing `print` in any GDScript file in the editor.

**Comment by nunodonato** [comment]
not sure what you mean by "spam", I get that "found bug" only once.
looking at the relevant code, it seems that print could possibily be removed, gdscript is just complaining that the expression is not yet valid...

**Comment by akien-mga** [comment]
"spam" was a bit strong yeah, I just mean that it will write it for `print`, then for `print(`, etc., so you easily end up with a lot of "found bug" messages if you don't type fast enough.
