### ISSUE TITLE
GDScript 2.0: Error when you use +=/-= on a Vector2's component

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#50283]
### Godot version

4.0 Dev

### System information

MacOS 11.4

### Issue description

Error **at runtime** when you subtract or add a value to a Vector2's component:

### Steps to reproduce

```python
var foo : Vector2 = Vector2.ZERO
foo.y += 100 # error at runtime
```

**Comment by Calinou** [comment]
> 4.0 Dev

Please specify the commit hash of the build you're using.

**Comment by ykasehf** [comment]
Can reproduce with 56d712686. The error in question seems to be `Invalid operands 'Nil' and 'int' in operator '+'.` Curiously, this only appears when the `: Vector2` is used, and removing that part removes the error.

**Comment by nonunknown** [comment]
I can confirm this bug also, occurst whith me using Vector3 too! 

version: v4.0.dev.custom_build [cb4e42155]

**Comment by Shatur** [comment]
Can confirm too, here is the minimal reproduction project that missing in the description:

[Test.zip](https://github.com/godotengine/godot/files/6874669/Test.zip)
