### ISSUE TITLE
[AnimationPlayer] custom_blend param doesnt work if animations are made with/without CURVES

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50280]
### Godot version

v4.0.dev.custom_build [cb4e42155]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

calling `animation_player.play("A",custom_blend_time)` for example,if animation B is playing and was animated without CURVES, and animation A was made with CURVES, then the custom_blend_time doesnt work and it plays the wanted animation without blending.

### Steps to reproduce

* Create AnimationPlayer
* Animate some node
* Make animation 1 without curve
* Make animation 2 with curve
* create script
* call animation 1 with a blender param
* the blending will not work

### Minimal reproduction project

https://easyupload.io/0cehia

Press Arrow UP or DOWN to change animations!

**Comment by akien-mga** [comment]
Is this still reproducible in 4.1 beta 3 or later?

The MRP is no longer available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
