### ISSUE TITLE
Tile y-sort origin is not center

### ISSUE THREAD

**Issue by rosshadden** [godotengine/godot#50288]
### Godot version

4.0.dev (79d6c2ceb9)

### System information

Arch Linux

### Issue description

The tile origin used for y-sort is not the center of tiles in Godot 4. It is currently the top of tiles just like it was in Godot 3, but according to @groud it was intended and expected to be the center in `master`.

I was having [a conversation in Discord](https://discord.com/channels/212250894228652034/279004126795268106/862383973311971328) about this and ultimately ended up recording a video to capture the problem in the form of a video:  https://www.youtube.com/watch?v=MgmuR-ZC8PA
This video's intent was more about asking how we can change the value, but supposedly what I actually uncovered was that the intended default of using the center of tiles was not being respected.

If the default for tile-origin was indeed the center, this would make a much better user experience and I would imagine most people would rarely or never even need to override the tile-origin. As it stands though, with a default of the top of tiles, it would need to be overridden for just about every non-ground/path tile (trees, buildings, signs, chests, etc.).
For this reason I never understood why the default was `TOP_LEFT` in Godot 3 (bearing in mind the "_LEFT" part is irrelevant anyway for y-sort), and was very happy to hear that the default was changed in Godot 4, even if it's not currently working as intended.

### Steps to reproduce

The video linked above shows my minimal example in video form, but it can be distilled even further:

- make TileMap
- enable y-sort on it and its parent
- observe that it is essentially impossible to get the y-sort to kick in (change render order)

This is because the y-sort tile-origin is not the center by default, it is the top of the tiles.

### Minimal reproduction project

[godot-3-tile-origin.zip](https://github.com/godotengine/godot/files/6786640/godot-3-tile-origin.zip)
[godot-4-tile-origin.zip](https://github.com/godotengine/godot/files/6786641/godot-4-tile-origin.zip)

**Comment by groud** [comment]
Ok I tested and likely figured out the problem (I tested on my branch which is a little bi t different). Two things:
- The polygon origin should likely be at the bottom of the polygon, to make it work like a character I suppose. On my side I thus moved the polygon to have it on top of the KinematicBody2D node's position.
- You need to activate Y-sorting on the TileSet resource, in the rendering section. This is needed right now on master but since I am implementing Tilemap layers, I'll most likely remove it from the TileSet resource.

Let me know if it helps.

**Comment by rosshadden** [comment]
Oh okay, this did work. Thanks!
I'm going to close the issue, but feel free to open it back up again if you want.
