### ISSUE TITLE
Internal Script Error! - opcode #6

### ISSUE THREAD

**Issue by zachtyll** [godotengine/godot#50281]
### Godot version

c3.2.1.stable.official

### System information

Windows 10

### Issue description

Godot spontaneously ends debugging and my debugger hands me the error:

`E 0:00:12.549   call: Condition ' indexname < 0 || indexname >= _global_names_count ' is true. Breaking..:
  <C++ Source>  modules/gdscript/gdscript_function.cpp:662 @ call()
  <Stack Trace> Matrix.gd:374 @ ()
                Matrix.gd:661 @ _get_messages_completed()
`

### Steps to reproduce

It seems to happen as I am yielding for a signal that is emitted after an HTTP-GET request. It happens very sporadically so finding steps to reproduce it is very tough.

### Minimal reproduction project

My repo is at [godot-matrix](https://github.com/zachtyll/godot-matrix). A Matrix-protocol account is required to log in. Sadly I have not yet implemented that functionality yet. A developer will have to make their own to log in.

**Comment by Calinou** [comment]
> c3.2.1.stable.official

This Godot version is no longer supported. Please upgrade to 3.3.2.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
