### ISSUE TITLE
intersect_ray finds disabled CollisionShape in GodotPhysics

### ISSUE THREAD

**Issue by QazPolma** [godotengine/godot#50298]
### Godot version

3.3.2.stable.official

### System information

Linux Mint 20.1, GLES2, Intel HD 620

### Issue description

intersect_ray finds disabled CollisionShape in GodotPhysics, but not in Bullet physics.

### Steps to reproduce

1. Add KinematicBody with CollisionShape
2. Disable CollisionShape from editor and/or script
3. Use intersect_ray

### Minimal reproduction project

[TestSandBox.zip](https://github.com/godotengine/godot/files/6787640/TestSandBox.zip)

**Comment by Calinou** [comment]
This was already fixed in https://github.com/godotengine/godot/pull/49845, which will be in 3.3.3 once it's released.
