### ISSUE TITLE
Exposing more physics constants to project settings

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5029]
Follow-up on #505.

@marynate had proposed to expose physics parameters like https://github.com/godotengine/godot/blob/5be9ff7/scene/resources/world_2d.cpp#L381 and https://github.com/godotengine/godot/blob/a75f896/servers/physics/space_sw.cpp#L728 to the project settings for fine-tuning by the users.

I could PR @marynate's changes again but I see other constants that might be worth exposing, and overall I have too little experience with the physics engine to say if those changes would be sensible.

So, feedback appreciated :)

**Comment by reduz** [comment]
I think the exposed parameters are fine, Also exposing them for 3D and 2D the same should be done
