### ISSUE TITLE
TreeItem remove_child doesn't immediately update the UI

### ISSUE THREAD

**Issue by grabthefish** [godotengine/godot#50318]
### Godot version

v3.3.2.stable.official

### System information

Windows 10

### Issue description

When removing an item from a Tree node using TreeItem.remove_child, the UI doesn't get updated immediately.  
It will only update the UI when moving the mouse from outside the game window to the inside, or if you click an item in the Tree.

### Steps to reproduce

https://user-images.githubusercontent.com/12375347/125121966-04f97a00-e0f5-11eb-8856-e506212a697f.mp4

### Minimal reproduction project

[TreeRemoveChild.zip](https://github.com/godotengine/godot/files/6793307/TreeRemoveChild.zip)

**Comment by VedatGunel** [comment]
This is fixed by #50135.
