### ISSUE TITLE
Checkerboard background is no longer rendered in 3D material editor preview

### ISSUE THREAD

**Issue by AnilBK** [godotengine/godot#50315]
### Godot version

v4.0.dev.custom_build.d4e5fe6c4

### System information

Windows 10, Nvidia, Vulkan

### Issue description

Bug discovered while working for, and the relevant code behind it
https://github.com/godotengine/godot/pull/49466#discussion_r652768662

The material editor has a checkerboard pattern in the background,but that doesn't seem to be rendered at all.
![checkerboard_unrendered](https://user-images.githubusercontent.com/17506575/125094177-c19e0c00-e0f2-11eb-81e7-498786011ae0.png)

3.x for reference.
![3x-reference](https://user-images.githubusercontent.com/17506575/125095865-535a4900-e0f4-11eb-856f-d38ac93ee51d.png)

One Side effect might be:
There are two toggle icons for switching between Cube and Sphere preview.When the Sphere preview icon is clicked,the icon for cube toggle seems to disappear,not sure,but maybe because of the checkerboard pattern being not rendered.

![two_toggles](https://user-images.githubusercontent.com/17506575/125094489-0629a780-e0f3-11eb-8e32-57b55f7712c8.png)

For someone who is debugging this,one of this cases where the checkerboard pattern is rendered is, For ImageTexture3D.
So,I don't think its problem with draw_rect.

![working](https://user-images.githubusercontent.com/17506575/125094787-438e3500-e0f3-11eb-9429-58bc8c5c96ea.png)

### Steps to reproduce

->New MeshInstance3D
->   New Standard/Shader Material3D

The bug is about the material editor's preview view port.

### Minimal reproduction project

Not Required.

**Comment by KoBeWi** [comment]
Fixed.
