### ISSUE TITLE
GDScript 2.0: Singletons silently don't get registered as global variable if script failed to compile or has a circular dependency

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#50321]
### Godot version

4.0 (a5b2988a0)

### System information

Windows 10
Version	20H2
19042.928

### Issue description

When you create and add an autoload and enable "global variable", you cannot access it. The Singleton is created, but the variable not set.

```gdscript
#Test.gd
extends Node

var xyz := "A test"
```

```gdscript
#Node2D.gd
extends Node2D

func _ready():
	print(Test.xyz) # yields error and Test is null
```

### Steps to reproduce

1. Run project

### Minimal reproduction project

[Singletons unregistered.zip](https://github.com/godotengine/godot/files/6793369/Singletons.unregistered.zip)
[jordi's MRP](https://drive.google.com/file/d/1ND4N3f1RE-ftER1Ha5LEBIGyR-TURKVm/view?usp=sharing)

**Comment by Norrox** [comment]
I can confirm on 14cc1df1d8921600758bb40d27dde1200f109414

**Comment by MisoMosiSpy** [comment]
Tried this on commit a5b2988a0105deb37c14eb62ed8638eb15789ec3

There is typo in the shared project, variable is named **xyz** in test.gd and **yxz** in Node2D.gd

Test.gd
```
extends Node


var xyz := "A test"
```

Node2D.gd

```
extends Node2D


func _ready():
	print(Test.**yxz**)
```

Am I missing anything?

**Comment by HaSa1002** [comment]
Ok, the typo is my bad. Although the circular issue mentioned in #49049 is likely the other issue I encountered. I will upload an additional MRP, once I made one.

**Comment by summertimejordi** [comment]
I've created another minimal reproducible project. I don't think this error only occurs if a script failed to compile.
It occurs when there's a circular dependency between the singleton and the script that's trying to access it.

For example, I have a simple script that's added as an autoload:
![image](https://user-images.githubusercontent.com/12436824/125316236-8d4a6b80-e2fd-11eb-941b-371c22161442.png)

That script references another class named Player:
![image](https://user-images.githubusercontent.com/12436824/125316306-9e937800-e2fd-11eb-8bb8-f1c90b6cc7fe.png)

When the game is run, the Player tries to set a variable on GameManager but can't find GameManager.
![image](https://user-images.githubusercontent.com/12436824/125316488-c682db80-e2fd-11eb-833b-fec5fd063398.png)


Minimal Reproducible Project:
[Google Drive](https://drive.google.com/file/d/1ND4N3f1RE-ftER1Ha5LEBIGyR-TURKVm/view?usp=sharing)

**Comment by HaSa1002** [comment]
Thank you very much. I linked your MRP in the OP. I won't create another MRP then. Two are enough :)

**Comment by vnen** [comment]
There seems to be two different issues here. The original issue is probably the same as #50471 (which has a pending PR to fix already). Can't really confirm since the original project does not reproduce the bug (as pointed out earlier by MisoMosiSpy).

The other issue that was pointed out by @summertimejordi is not related to circular references, it is really that the parser gets confused since the `GameManager` class has the same name as the `GameManager` autoload. This should probably be forbidden explicitly, since there isn't any reason to name both the same. Removing the `class_name` line from `GameManager.gd` solves this.
