### ISSUE TITLE
`PackedByteArray` can't be assigned with a bool

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#50326]
### Godot version

4.0.dev (a5b2988)

### System information

Windows 10

### Issue description

You can't assign a bool to a PackedByteArray and the inspector shows them as integers.
![grafik](https://user-images.githubusercontent.com/14185889/125142513-3899cb80-e118-11eb-970c-3712468dd860.png)
``

### Steps to reproduce

1. Run MRP

### Minimal reproduction project

[PackedByteArray is int.zip](https://github.com/godotengine/godot/files/6794196/PackedByteArray.is.int.zip)

**Comment by Calinou** [comment]
Does that work in Godot 3.x?

**Comment by HaSa1002** [comment]
It was a PoolByteArray earlier. And yes there were issues with that #48999

**Comment by HaSa1002** [comment]
But you made me realise that I mixed bytes and bits when it came to the usage of this array. I should have implemented a BitArray for easy use 🤦

**Comment by Calinou** [comment]
There's a BitMap class you can use to store 2D bitmaps too :slightly_smiling_face:

**Comment by HaSa1002** [comment]
Well, I have to sync input states. I already have enums, to define which position is which value. I could have shifted my way through, but I don't know how readable the player code would remain ^^

**Comment by Mickeon** [comment]
No errors here anymore. I would safely close this @Calinou .
![image](https://github.com/godotengine/godot/assets/66727710/5453ffa0-258d-4830-a3b3-1f2a54f6992d)
(`false` is implicitly converted to `0`)
