### ISSUE TITLE
Instance of Path2D has erratic behaviour

### ISSUE THREAD

**Issue by dpensi** [godotengine/godot#50334]
### Godot version

Godot Engine 3.3.2.stable.fedora

### System information

Fedora 33, Gles3, Lenovo Thinkpad

### Issue description

Calling `.instance()` on a PackedScene of type Path2D, then calling `get_child` to retrieve the `PathFollow2D` object has incorrect behaviour in working with the offset property

- the offset is not summed with modulo(<path length>): adding values to the offset does not apply the modulo operation, that is: if the path length is 100, the current offset is 80, adding 30 to the offset will result in an offset of value 110 **instead** of the expected value 10
- the position does not change: changing the offset does not result in a change of the `position` property

A workaround is to add the Path2D as a child to the scene with the editor (point and click operation) avoiding calling `.instance()` and avoiding the subsequent call `add_child`

### Steps to reproduce

clone this repo: https://github.com/dpensi/path-bug/, open the project with the godot editor, press `play(F5)` and observe the output panel in the bottom of the screen where the output of [this operation](https://github.com/dpensi/path-bug/blob/main/KinematicBody2D.gd#L18) can be read. Notice how:

- the offset will be greater than 1030.57 that is the path length
- the position will not change

### Minimal reproduction project

https://github.com/dpensi/path-bug/

**Comment by kleonc** [comment]
It happens because the instance of your `Pack2D` scene is never added to the scene tree (same for `PathFollow2D` you're referring to), as you can read in the error message:

```
E 0:00:00.550   add_child: Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.
  <C++ Error>   Condition "data.blocked > 0" is true.
  <C++ Source>  scene/main/node.cpp:1163 @ add_child()
  <Stack Trace> KinematicBody2D.gd:13 @ _ready()
```

Deferring adding as a child (as suggested in the error message) will make it work as expected. Instead of:
```
func _ready():
	path_instance = MeNotWorks.instance()
	get_parent().add_child(path_instance)
```
do:
```
func _ready():
	path_instance = MeNotWorks.instance()
	get_parent().call_deferred("add_child", path_instance)
```
