### ISSUE TITLE
Vulkan: StandardMaterial3D alpha scissor does not cast shadows

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot#50344]
### Godot version

Calinou Nightly build 5710adda7

### System information

Macbook Pro 2019 16"

### Issue description

I've been trying to get basic alpha textures to cast shadows from a SurfaceTool geometry to no avail. They receive them no problems, and when i turn alpha off, the object then shadows, but not with Alpha on.

![image](https://user-images.githubusercontent.com/27105009/125164321-faaead00-e1d4-11eb-8392-c92bc4fe1f01.png)

### Steps to reproduce

Create a flat geo with SurfaceTool, or with ArrayMesh ()
Give it a material and texture with an alpha

[18_StandardMaterialShadowBug_GDv4.0.zip](https://github.com/godotengine/godot/files/6796125/18_StandardMaterialShadowBug_GDv4.0.zip)

**Comment by Calinou** [comment]
Try enabling opaque prepass on the material. See also https://github.com/godotengine/godot/issues/17567.

**Comment by Akira1San** [comment]
I have a similar issue when importing a mesh with an alpha texture in Godot 4. When enabling depth pre-pass i see the shadow, but its loosing alpha on the texture. I guess its an AMD Radeon issue.

**Comment by MrJoshBowman** [comment]
Turns out that it's any Mesh with alpha textures!
I've uploaded the minimum reproduction in the original post.

<img width="920" alt="Image" src="https://user-images.githubusercontent.com/27105009/125179326-0cbe3900-e231-11eb-98e0-4443e1bce18d.png">

Yep, could be a Mac thing. I get this error whenever i try to edit the transparency.
![image](https://user-images.githubusercontent.com/27105009/125179346-42632200-e231-11eb-8f6f-0007831ab8e8.png)

**Comment by MrJoshBowman** [comment]
Nope. Not just a Mac/Radeon thing, I've just tested the same project on my Surface Pro and it's not giving me any shadows on StandardMaterial3D with alphas on their either.

**Comment by ninao-xyz** [comment]
I've got the same issues in (Godot_v4.0-dev.20210916_win64) downloaded from tuxfamilly 
Windows 10
AMD Ryzen 9 3900X
NVIDIA GeForce RTX 3060
![Captura de Ecrã (77)](https://user-images.githubusercontent.com/10292929/134188990-9c4056be-047c-4892-9208-6ff708606ea2.png)

**Comment by JFonS** [comment]
I opened #55084 with some fixes.

It would be nice if you guys could confirm whether it fixes all your issues or there are things still unresolved.
