### ISSUE TITLE
Internal script error! - opcode #33554445 (report please).

### ISSUE THREAD

**Issue by norlowski** [godotengine/godot#50357]
### Godot version

3.3 compiled with Gramps steam library

### System information

Windows 10

### Issue description

I am reporting this because that's what it said to do. I wasn't doing anything weird, and it went away the next time I ran the scene. Should we still report these opcodes?

### Steps to reproduce

Just reporting an opcode - this is not reliably reproduced

**Comment by norlowski** [comment]
You can just close this out if you dont want opcodes reported

**Comment by KoBeWi** [comment]
Without reproduction steps or minimal project the report isn't very useful in itself. Comment if you find a way to reproduce it consistently.
