### ISSUE TITLE
[3.x] Sound playback is delayed in Chromium until running project is clicked.

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#50366]
### Godot version

3.4.beta.custom_build.9ec4c1bce

### System information

HTML5 Export - WebGL 1.0

### Issue description

Sound playback is delayed in Chromium until running project is clicked.

Chromium Version 91.0.4472.114 (Official Build) Arch Linux (64-bit)

This issue does not happen in Firefox.

### Steps to reproduce

1. Run attached project under Chromium
2. Sounds will not play until the running project is clicked.

Note that canvas is focused on start (which was introduced in commit 69645b0e44547afcb629923889de3c57ec119519)

### Minimal reproduction project

[template.zip](https://github.com/godotengine/godot/files/6796740/template.zip)

**Comment by Faless** [comment]
This is a feature in Chrome, nothing we can do about: https://developer.chrome.com/blog/autoplay/ .
And is also documented [in the official Godot docs](https://docs.godotengine.org/en/3.3/getting_started/workflow/export/exporting_for_web.html#audio)
