### ISSUE TITLE
Viewport node CanvasTransform "resets" when it leaves and reenters the scene tree

### ISSUE THREAD

**Issue by BerkUnver** [godotengine/godot#50379]
### Godot version

3.3.2 Stable Mono

### System information

Windows 10 Home, GLES3, Intel Core i7-6567U, Intel Iris Graphics 550, 16GB RAM

### Issue description

I am using C# with VSCode, but I do not believe this is related.
To pause my game, I remove the current room scene from the scene tree and store a reference to it. That scene has custom viewports. Whenever I reattach that to the tree, the viewport's canvas transform's origin vector appear to be "reset". This means that they render as if the viewport's CanvasTransform.origin vector is (0, 0). The thing is, it isn't actually reset. If I set the viewport's CanvasTransform to itself in the _EnterTree method, it is fixed.

### Steps to reproduce

Make a texturerect and connect its texture to a child viewport

While the game is running:
Change the CanvasTransform vector of the viewport
Detatch the texturerect from the node tree
Reattach it to the node tree

In my example project, the stack of boxes is off-center. I change the CanvasTransform of its viewport to be centered. But once I remove the viewport and add it back, the stack of boxes is uncentered again. Check the "workaround" export property of the viewport to fix it using the workaround I described in the issue description.

### Minimal reproduction project

[ViewportBug.zip](https://github.com/godotengine/godot/files/6797657/ViewportBug.zip)

**Comment by Kuech** [comment]
I can confirm that I have the same bug in Godot version 3.3.2 in a Linux system. I have reproduce the bug with gdscript
