### ISSUE TITLE
is_size_override_stretch_enabled and is_size_override_enabled are the same

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#5037]
In the `Viewport` class, `is_size_override_enabled` and `is_size_override_stretch_enabled` both return the same value:
````c++
bool Viewport::is_size_override_enabled() const {

	return size_override;
}

// Other methods omitted for clarity

bool Viewport::is_size_override_stretch_enabled() const {

	return size_override;
}
````

**Comment by reduz** [comment]
wow, i have no idea how you found this, but goot catch

**Comment by bojidar-bg** [comment]
@reduz it was an easy find, given that I was documenting the Viewport class, and I wondered what do they do exactly ^^
