### ISSUE TITLE
JavaScriptObject fails to keep object reference

### ISSUE THREAD

**Issue by triptych** [godotengine/godot#50380]
### Godot version

v4.0.dev.calinou [374ffbe2d]

### System information

Windows 10, Vulkan

### Issue description

Basic testing of the JavaScriptObject functionality.
Tried to run a basic script but it fails immediately and the resulting app hangs.

<img width="514" alt="godot_nEvsIIGltf" src="https://user-images.githubusercontent.com/8691/125210932-93860c80-e257-11eb-87df-acb87293a693.png">

### Steps to reproduce

Open the project below in the version listed above. Then just hit run - observe the debugger.

### Minimal reproduction project

[JavaScript object 001.zip](https://github.com/godotengine/godot/files/6797728/JavaScript.object.001.zip)

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
What browser are you testing on?

**Comment by triptych** [comment]
It's not possible to test in a browser because the export files are not there. I'm just hitting the "run" In the upper right hand side of the IDE.
<img width="98" alt="godot_GRH5FUNRRG" src="https://user-images.githubusercontent.com/8691/125211624-8fa8b900-e25c-11eb-982b-b436d484934f.png">

"Play the project"

**Comment by Faless** [comment]
The JavaScript Interface is only available in html5 exports as mentioned in
the blog post

**Comment by triptych** [comment]
Can you tell me how I can get the HTML exports templates for a nightly build to test?

**Comment by Faless** [comment]
We don't have official nightly builds (godotengine/godot-proposals#1458), you can build the `3.x` branch yourself (both editor and [javascript export template](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_web.html)), or wait for the first official `3.4` alpha to be published.

**Comment by akien-mga** [comment]
For the reference @triptych seems to be using the `master` branch (4.0.dev). The JavaScript templates don't support rendering in `master` at this time (no WebGL renderer), so it's not recommended to use them.

**Comment by triptych** [comment]
I'll check again once things are close to release. Thanks for the updates everyone.
