### ISSUE TITLE
Batching doesn't work/isn't supported for CanvasItem draw commands.

### ISSUE THREAD

**Issue by osimmac** [godotengine/godot#50387]
### Godot version

3.3.2 stable

### System information

Linux 5.10 manjaro / 1070 with nvidia driver, using gles3

### Issue description

It is suggested in the docs on both the "drawing in 2d" and "batching" pages that this should work:

https://docs.godotengine.org/en/stable/tutorials/2d/custom_drawing_in_2d.html#but
- _"Drawing a large number of simple objects. Custom drawing avoids the overhead of using nodes which makes it less memory intensive and potentially faster."_
https://docs.godotengine.org/en/stable/tutorials/optimization/batching.html#how-it-works
- _"Consecutive commands within an item can be joined to form a batch."_
- you can break batching by: _"Change of primitive type (say, going from rectangles to lines)."_

with this info, it seems like batching is supported for 2d drawing so long as its the same type of draw command, and maybe same color. however this doesn't seem to be the case.

I have a project that will reproduce the issue for me, it just spawns 1000 identical circles in place, and in the monitors tab you can see that its not batching the draw calls. (theres 1000 calls when there should be less)

I know batching works on my system as I have a separate project that uses tilemaps and batching works great for it. 

this is the code used in the _draw function:
```
func _draw():
	var col = Color.red
	var pos = Vector2.ZERO
	var rad = 100.0
	for i in 1000:
		draw_circle(pos,rad,col)
```

and this is the output of a diagnostic:
```
canvas_begin FRAME 526
items
	joined_item 1 refs, 
			batch D 0-1000 c c c c c c c c c c c c c c c c 
canvas_end
```
^^^
it is lacking ```MULIT```

this is also an issue in gdnative if it matters, im sure it would work there if it worked in gdscript though.

### Steps to reproduce

1. Open and run project in editor, see red balls in center (there is 1000 of them)
2. view draw count in monitors for 2D
3. observe it is 1000 and not less.

### Minimal reproduction project

[drawcommandbatching.zip](https://github.com/godotengine/godot/files/6798360/drawcommandbatching.zip)

**Comment by lawnjelly** [comment]
Not all primitives can currently be batched, circles are one of those that can't (yet). This is probably something we could add in the docs.

Originally, only rects were batched then I added primitives based on whether it was possible, and the popularity of the primitive.

Currently:
* Rects
* Ninepatches (not all types)
* Lines (lines in the rasterizer, some 'lines' are drawn as polys)
* Polys (except anti-aliased)
* Software skinned polys

There are also a lot of special cases determining whether a particular situation / primitive can be batched, so it is difficult to be exhaustive / keep up to date.

It is possible that a later date myself or another contributor will be able to get circles batching by converting them to polys (Godot 4 does a lot more of this kind of thing, rendering higher order primitives by converting to polys etc).

**Comment by Calinou** [comment]
> It is possible that a later date myself or another contributor will be able to get circles batching by converting them to polys (Godot 4 does a lot more of this kind of thing, rendering higher order primitives by converting to polys etc).

https://github.com/godotengine/godot/pull/43828 could be worth remaking for `3.x` to get working antialiasing for lines everywhere, including GLES2 and mobile/web platforms.

**Comment by osimmac** [comment]
> The method shown in the doc drawing the arc or circle with a single `draw_polygon` may do the trick.

this at least will batch the draw calls, thank you for that info. i'm able to manually draw octogons instead of circles and it runs much faster.

**Comment by lawnjelly** [comment]
Fixed in the sense we have added some notes on this to the docs, and we may be able to batch some more primitives at some point. I don't think there anything more immediately actionable on the issue.
