### ISSUE TITLE
Missing parameter name in api.json

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#50390]
### Godot version

4.0.dev 7594150f6539681660045c41eb2023c7607cd639

### System information

Any

### Issue description

Normally this is a mistake in the bindings but I can't find it.

In the generated `api.json` :
```
{
	"name": "_has_point",
	"return_type": "bool",
	"is_editor": false,
	"is_noscript": false,
	"is_const": true,
	"is_reverse": false,
	"is_virtual": true,
	"has_varargs": false,
	"is_from_script": false,
	"arguments": [
		{
			"name": "",
			"type": "Vector2",
			"has_default_value": false,
			"default_value": ""
		}
	]
},
```

The parameter for `_has_point` is missing its name.

### Steps to reproduce

Run:
`godot --gdnative-generate-json-api  api.json`

and check the output:)

**Comment by bruvzg** [comment]
All augment names seem to be correct (there are no empty names in `json` anymore), so this should be already fixed.
