### ISSUE TITLE
SOLVED[Windows10+Godot3.3.2]-Can't Export To Android-'apksigner' returned with error #1 ?

### ISSUE THREAD

**Issue by FallenAngelSoftware** [godotengine/godot#50395]
### Godot version

3.3.2 Stable standard version 64Bit Windows

### System information

Windows 10 Pro 64Bit fully updated

### Issue description

Hi,

Using Godot 3.3.2 64Bit on Windows 10 Pro 64Bit, we can't export to Android?
When we try to export to Android we get error: 'apksigner' returned with error # 1 ?

A temporary work-around is to use older Godot version 3.2.3.
Hope this can be fixed soon, thanks!

Jesse

### Steps to reproduce

Try to export to Android using Godot 3.3.2 64Bit on Windows 10 - does not seem to work currently.

**Comment by Calinou** [comment]
You need to update your Android export settings as the **Adb** and **Jarsigner** editor settings are no longer used. Instead, you need to set **Android Sdk Path**. See https://github.com/godotengine/godot/issues/22099.

**Comment by FallenAngelSoftware** [comment]
Hi,

I did that already and it still does not build for Android?

Jesse

![Godot-3_3_2-AndroidSDK-01](https://user-images.githubusercontent.com/35844132/125288803-8b2be100-e2ec-11eb-8762-de01b938cd2c.png)

**Comment by akien-mga** [comment]
Make sure that you have `build-tools` 30.0.3 installed in the Android SDK. Review https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html for current requirements.

**Comment by FallenAngelSoftware** [comment]
I did all that already - followed the complete building for Android instructions - still does not work.

**Comment by FallenAngelSoftware** [comment]
Ok, sorry I double checked the build-tools and it was not the correct version required.
It works now!
Thanks!

Jesse
