### ISSUE TITLE
Moving RemoteTransform2D discards SVG image resize in Sprite2D node.

### ISSUE THREAD

**Issue by RevolNoom** [godotengine/godot#50399]
### Godot version

v3.3.2.stable.official

### System information

Ubuntu 20.04.2 LTS - Graphic Card AMD Hainan / Mesa Intel UHD Graphics 620 (WHL GT2), OpenGL ES 3.0

### Issue description

Point a RemoteTransform2D to a Sprite2D with SVG image texture (resized) will bring the SVG back to original size.
Resize the Sprite2D with SVG texture, and then moving the RemoteTransform2D will bring the SVG back to original size.

https://user-images.githubusercontent.com/52204256/125313851-d92dfc80-e35f-11eb-8a5a-d585e239ff41.mp4

This problem is specific to SVG texture. I don't know about other picture formats, but PNG texture is not affected.

https://user-images.githubusercontent.com/52204256/125313826-d16e5800-e35f-11eb-8b07-43219a79b024.mp4

### Steps to reproduce

Create a Sprite, assign it an SVG texture.
Create a RemoteTransform2D.

1. Resize the Sprite, assign the Sprite to the RemoteTransform2D.
2. Assign the Sprite to the RemoteTransform2D, resize the Sprite, move the RemoteTransform2D.

**Comment by timothyqiu** [comment]
Scale is part of transform. I think it's expected behavior to reset the scale of remote transformed node when `update/scale` is enabled (i.e. match the scale of sprite to the scale of `RemoteTransform2D`).

I can't reproduce the PNG-scale-not-change scenario. The sprite does not even move when the `RemoteTransform2D` moves which seems incorrect.

**Comment by RevolNoom** [comment]
@timothyqiu My bad. I didn't read the full documentation and assumed it's a bug. Yes, there's a Scale tick box in the Update section. I thought that the RemoteTransform only move the remote node, and thus I have to resize the original node myself.
