### ISSUE TITLE
Need help completing editor customizable shortcuts!

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#5040]
Editor shortcuts can now be customized, and there are a new few tools for this, specially the ShortCut resource.

Most of editor_node.cpp has been converted, but the rest of the editor remains. Here's the global functions that can be used:

`ED_SHORTCUT(const String& p_path,const String& p_name,uint32_t p_keycode=0);`

This defines a new shortcut, which must contain a section/identifier path, a translatable name and a keyboard shortcut. Returns a shortcut object which can be added to a button or to a menu. An example of this from editor_node.cpp:

```
`p->add_shortcut(ED_SHORTCUT("editor/save_scene_as",TTR("Save Scene As.."),KEY_MASK_SHIFT+KEY_MASK_CMD+KEY_S),FILE_SAVE_AS_SCENE);
```

`

Many times, the menus, buttons, etc. are created on the fly, so call this function again on a constructor or at some place where initialization occurs, this way it can always appear in editor settings dialog. Just call it and ignore the return, as it will be cached for next time you call it.
`
ED_SHORTCUT("editor/save_scene_as",TTR("Save Scene As.."),KEY_MASK_SHIFT+KEY_MASK_CMD+KEY_S)
`
Optionally and for simplicity you can simply get the shortcut, but it must have defined as above!

```
Ref<ShortCut> ED_GET_SHORTCUT(const String& p_path);

usded like:

somebutton->set_shortcut( ED_GET_SHORTCUT("editor/save_scene_as") );
```

In many places, checking for a shortcut is done manually from an unhandled input callback. Generally this is done with a switch(), so it will have to be changed to a sequence of ifs(). In such cases simply define the shortcut as in the code (two samples above ^), then check manually against an InputEvent: 

```
if ( ED_IS_SHORTCUT("editor/save_scene_as") ) {
...
}
```

I think this is all! Good luck :)

**Comment by reduz** [comment]
Oh also, It's perfectly fine to define shortcuts that by default are unused or unasigned, just do not use the third parameter of ED_SHORCUT or leave it as zero.

**Comment by reduz** [comment]
Ah also, this is for editor stuff only, scene/ nodes like TextEditor or LineEdit, Tree etc. will default to the harcoded keybindings for now.

**Comment by bojidar-bg** [comment]
@reduz Note that switch statements might be converted to something like:
````c++
//...
switch(true) {
  case ED_IS_SHORTCUT("editor/save_scene_as"): {
    do_stuff();
  } break;
  case ED_IS_SHORTCUT("editor/save_script_as"): {
    do_more_stuff
  } break;
 // More checks
}
//...
````

Which of the two ways is more preferable?

**Comment by neikeq** [comment]
@bojidar-bg That's not possible because `case` expects a constant expressions.

**Comment by bojidar-bg** [comment]
@neikeq Ah right... seems like I forget some stuff from time to time ^^. JavaScript allows it though.

**Comment by reduz** [comment]
Oh one extra thing, in many places where buttons are used, the shortcut is harcoded via text in the tooltip like
button->set_tooltip("Does this and that (F5)");

If you set a shortcut to the button, the tooltip does not need to be harcoded, Button will add it to the tooltip automatically.

**Comment by reduz** [comment]
@bojidar-bg just made me realize this is wrong:

`ED_IS_SHORTCUT("editor/save_scene_as")
`
It actually is:

`ED_IS_SHORTCUT("editor/save_scene_as",input_event)
`

**Comment by bojidar-bg** [comment]
Ok, final question, what should be done for lines like this?
````c++
if (p_input.is_pressed() && (p_input.is_action("ui_up") || p_input.is_action("ui_page_up"))) {
````

**Comment by bojidar-bg** [comment]
Ok, I'll take `animation_editor` and `plugins/a*` for now. Any objections?

**Comment by akien-mga** [comment]
Go for it :)

**Comment by reduz** [comment]
For Basic stuff in case where any other key would not make sense just leave
it as is

**Comment by neikeq** [comment]
@reduz there is a problem with `ui_`* actions. They are not longer existent for the editor after 64fd75d, so the lines in @bojidar-bg's example will give errors. See #5050

**Comment by reduz** [comment]
Uh maybe i screwed something up

**Comment by neikeq** [comment]
What's the path naming convention?

**Comment by vnen** [comment]
@neikeq @reduz wasn't this fixed by #5053?

**Comment by neikeq** [comment]
@vnen Yes, that bug is already fixed :)

**Comment by vnen** [comment]
I got confused by the dates :laughing:

**Comment by bojidar-bg** [comment]
I'm really sorry, but I won't be able to do any of the files it reserved -- please take them yourselves. (I'll be semi-available for a week and a half, so, I won't really have the time with assetlib as well)

**Comment by reduz** [comment]
hey guys, any progress on this?

**Comment by neikeq** [comment]
Guys, now (as of 90b3f70) you can specify where to place the shortcut text in a button tooltip. Just add `$sc` identifier to the tooltip and it will be replaced with the shortcut text. Otherwise it will be added at the end of the tooltip like normal. e.g:

``` C++
select_button->set_shortcut(ED_SHORTCUT("canvas_item_editor/tool_select",TTR("Select Mode (Q)"),KEY_Q));
select_button->set_tooltip(TTR("Select Mode $sc")+"\n... some other text ...");
```

Results in:

```
Select Mode (Q)
... some other text ...
```

**Comment by djrm** [comment]
Working on TileMapEditor

**Comment by akien-mga** [comment]
@Paulb23 did script and shader text editors.

**Comment by akien-mga** [comment]
What's the status on this effort? Are there still editor components that need to be ported to the new system?

**Comment by djrm** [comment]
Grid map editor is missing

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by reduz** [comment]
Thanks everyone for the help! as far as I know, this is mostly done.. and this issue at least is no longer relevant. If something is missing, it will be better if we report as a separate issue.
