### ISSUE TITLE
move_and_slide expect only 0 arguments

### ISSUE THREAD

**Issue by AdrianCarmonaRoda** [godotengine/godot#50400]
### Godot version

4.0.dev.calinou [d1f25bb5f]

### System information

Windows 10, Vulkan, GTX 1080

### Issue description

When I try to make the CharacterBody2D move with:
`get_parent().move_and_slide(Velocity);`
(Velocity us a Vector2)
The game crash with this error:
`Invalid call to function 'move_and_slide' in base 'characterBody2D ()'. Expected 0 arguments`

### Steps to reproduce

1. Add a CharacterBody2D to the Scene tree (and the collider)
2. Add a GDScript to that node
3. In the '_physics_process' function add move_and_slide(Vector); with the Vector being a Vector2D with some value
4. Try to run the game

### Minimal reproduction project

[Test42D.zip](https://github.com/godotengine/godot/files/6802768/Test42D.zip)

**Comment by pycbouh** [comment]
That is correct, these methods no longer take parameters, see https://github.com/godotengine/godot/pull/48908.

**Comment by AdrianCarmonaRoda** [comment]
Right! Sorry for the inconvenience
