### ISSUE TITLE
compile error for android & windows template

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#5041]
**Operating system or device - Godot version:**
Windows 10, MSVC 14

**Issue description** (what happened, and what was expected):
There is compile error ``error c2066 cast to function type is illegal`` on line 74, 81, 88, 96 in ``scene/gui/input_action.cpp``.

**Steps to reproduce:**
```
scons.bat -j 4 platform=windows target=release_debug tools=no
```

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Maybe @reduz forgot some `#ifdef TOOLS_ENABLED` again.

Failing Travis build for Android: https://travis-ci.org/godotengine/godot/jobs/135336363

**Comment by volzhs** [comment]
I can compile with current head (64fd75d91a65d6fe05cf6c3578f53f85b4c92c27)
