### ISSUE TITLE
Improve ConfigFile example

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#50424]
### Godot version

3.x / master

### System information

W10

### Issue description

This was raised on the chat. Seems like there is some confusion on how to use ConfigFile. There is an example in the docs, but it doesn't really show *real* usage:
```GDScript
var config = ConfigFile.new()
var err = config.load("user://settings.cfg")
if err == OK: # If not, something went wrong with the file loading
    # Look for the display/width pair, and default to 1024 if missing
    var screen_width = config.get_value("display", "width", 1024)
    # Store a variable if and only if it hasn't been defined yet
    if not config.has_section_key("audio", "mute"):
        config.set_value("audio", "mute", false)
    # Save the changes by overwriting the previous file
    config.save("user://settings.cfg")
```

Most often you just open the file, put some values and then save it. Checks or gets for values in file *you are writing to* are rather rare. So IMO the example should just show how to save some data. (or there could be another example)

### Steps to reproduce

1. F1
2. ConfigFile
3. Enter
4. 👀

**Comment by maincomputer** [comment]
On the ConfigFile document page there is also a code block above the main example that shows the example section heading storing different variant values i.e. (int, string, Vector3). 

```gdscript

[section]
some_key=42
string_example="Hello World!"
a_vector=Vector3( 1, 0, 2 )

```

The example doesn't even reference that layout to change any of those types. So it couldn't hurt if the new example was more consistent.
