### ISSUE TITLE
Opening a Godot 3 project in Godot 4 gives errors spam

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#50421]
### Godot version

v4.0.dev.calinou [fc00a8390]

### System information

Win 10 64, AMD RX 480

### Issue description

Since one of the latest commits allow to open a Godot 3 project. I tested a project and got a spam of error.
console message:
Attempted to use an unused shader variant (shader is null),
  drivers/vulkan/rendering_device_vulkan.cpp:6633 - Condition "!pipeline" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  Attempted to use an unused shader variant (shader is null),

### Steps to reproduce

just copy the assets into a new created G4 project, uncheck etc2 cos is slow and open main scene.

### Minimal reproduction project

Ive tested this project: https://koros.itch.io/scifi-level

**Comment by Akira1San** [comment]
Found the issue, the SS Reflections was enabled.

**Comment by Calinou** [comment]
> Found the issue, the SS Reflections was enabled.

For future reference, this is being tracked in https://github.com/godotengine/godot/issues/50151.
