### ISSUE TITLE
Frame time very high and unstable using NavigationAgent

### ISSUE THREAD

**Issue by gg312** [godotengine/godot#50448]
### Godot version

v4.0.dev.custom_build [d5b8abdb6]

### System information

Windows 10, gtx 1650,  i7 9750H

### Issue description

I'm trying to implement pathfinding with the new NavigationAgent, but when I run the code the system performance drops very low, i get a lot of fps spikes; the worst spikes are on the physics process. 

### Steps to reproduce

See project below.

### Minimal reproduction project
[bug.zip](https://github.com/godotengine/godot/files/6816137/bug.zip)

**Comment by akien-mga** [comment]
How did you solve the issue?

**Comment by gg312** [comment]
In fact, I realized that we are using a custom 4 version, not the 3.x. The other thing is I didn't test the issue on the official 4. I'm compiling it right now and I'll test as soon as possible. If the issue persists, i'll reopen the issue.

**Comment by gg312** [comment]
Tested on 4, same issue. See the updated description.

**Comment by Calinou** [comment]
cc @AndreaCatania

**Comment by AndreaCatania** [comment]
Just tested and the framerate is fine. However, on my side the character wasn't able to move, and the function `print($NavigationAgent3D.is_target_reachable())` was returning false. This is a bug on godot side, since the project is using the navigation correctly. So far I didn't go deeper.

**Comment by gg312** [comment]
Very strange. On my side ```gdscript print($NavigationAgent3D.is_target_reachable())``` returns true, and it moves correctly.
