### ISSUE TITLE
Editor fonts in the script editor's script list are less crisp since 3.3 when using editor scale below 100%

### ISSUE THREAD

**Issue by felix7700** [godotengine/godot#50447]
### Godot version

3.3

### System information

Ubuntu 20.04 LTS and Mint 20.04

### Issue description

Since version 2.3 I have the problem that if I select under settings / interface / editor / display_scale: Custom and select a value <1.0 under interface / editor / custom_display_scale, the font in the font tree becomes blurred.

### Steps to reproduce

Since version 2.3 I have the problem that if I select under settings / interface / editor / display_scale: Custom and select a value <1.0 under interface / editor / custom_display_scale, the font in the font tree becomes blurred.

**Comment by JestemStefan** [comment]
I can't reproduce on `Windows` and `3.3.2`.

Screenshot:
![obraz](https://user-images.githubusercontent.com/37214990/125605039-630b68a8-df60-45b9-ba23-3d747b3146a9.png)


Maybe try disabling Font AA?

**Comment by Calinou** [comment]
This is done by design since 3.3 on small displays (such as 1366×768). The Auto editor scale will pick 75% editor scale to make the editor less cramped.

**Comment by felix7700** [comment]
For a year now I've been working on a project for my employer that mainly runs on Linux clients and that accesses the Linux terminal for certain functions. This means that I also need Linux for development. However, I got a Windows laptop (Dell Latitude 5490, display resolution 1920x1080) from my employer (or rather, from the IT department) on which I have few rights and no bash. Therefore I am always forced to work in VirtualBox. This has worked perfectly so far, until I wanted to update GoDot from v2.2.2 to a higher version. In versions higher than v2.2.2, the fonts in the script trees are so blurred that working permanently (sometimes more than 5 hours a day) with the newer versions is out of the question for me. See pictures. Unfortunately, various settings such as font antialiasing and font hinting to normal and a different font for the interface editor font have not achieved much improvement. 
blurred_godot_v3 3 2
![blurred_godot_v3 3 2](https://user-images.githubusercontent.com/51541572/125735510-7c535e9f-100a-46c6-96af-23d9d9054d6b.png)

blurred_godot_v3 3 2_settings
![blurred_godot_v3 3 2_settings_editorfont_fontHinting_normal_mainFont_arial](https://user-images.githubusercontent.com/51541572/125735513-6d5f397d-745d-4ef5-969a-076e1dff340b.png)

crisp_godot_v2 2 2
![crisp_godot_v2 2 2](https://user-images.githubusercontent.com/51541572/125735514-5d52e534-88ef-4f81-97f5-d308c165f1b1.png)

**Comment by felix7700** [comment]
The problem only seems to occur when working under VirtualBox and then changing the scaling for the editor. On a PC where Linux is installed directly or you work directly under Windows, the scaling works and everything looks sharp.

**Comment by Calinou** [comment]
@felix7700 Only certain parts of the editor are being blurred on your 3.3.2 screenshots, which hints at an issue with GUI elements being rendered at subpixel coordinates.

PS: It's 3.3.2 and 3.2.2, there is no Godot 2.2.2.

**Comment by Calinou** [comment]
@felix7700 Can you (or anyone else) still reproduce this bug in [Godot 3.5](https://godotengine.org/article/godot-3-5-cant-stop-wont-stop) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
