### ISSUE TITLE
MOUSE_MODE_CAPTURED does not hide the cursor

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#5051]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 2.1 alpha custom build.

**Issue description** (what happened, and what was expected):
When using `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)` the cursor is not hidden.

MOUSE_MODE_CAPTURED should hide the mouse, or alternatively a new mouse mode MOUSE_MODE_CAPTURED_HIDDEN could be used for both capturing and hiding the mouse.

I believe the problem might have started with this commit b5e0729 (but I can't test if that's true)

**Link to minimal example project** (optional but very welcome):
The demo "Window Management" has a button to capture the mouse.

**Comment by reduz** [comment]
This is clearly a bug in captured mode, needs to be fixed..

**Comment by J08nY** [comment]
I don't have a windows machine to test this. Could you try pulling from: https://github.com/J08nY/godot/commit/c3bd324864c254f2cebc3a00037597ce6fce4197 or a patch here https://github.com/J08nY/godot/commit/c3bd324864c254f2cebc3a00037597ce6fce4197.patch 
Will do a PR if this works.

**Comment by CowThing** [comment]
I'm sorry I couldn't test this earlier. But I just tried it now, and it doesn't seem to be fixed, the mouse cursor is still visible with MOUSE_MODE_CAPTURED.

**Comment by stillinthe90s** [comment]
Don't know if I'm missing something, so apologies if I am, but it seems that the MOUSE_MODE_CAPTURED is still not hiding the cursor in stable v2.1 & v2.1.2 (windows). I suppose this issue was considered fixed since it was closed quite some time ago,
Could someone please clarify?

**Comment by bojidar-bg** [comment]
Reopening as not fixed.

**Comment by Akira1San** [comment]
This is terrible. Every fps controller gives unplayable results. Even the fps tut in the doc. Except( https://github.com/Maujoe/godot-camera-control )

**Comment by CowThing** [comment]
Tried this again in 3.0.1 stable, on Windows 10 64bit, using the Window Management demo.

It seems like all of the modes work correctly. MOUSE_MODE_CAPTURED does hide the mouse cursor now. However there is a slightly different problem now, if you switch between **captured** and **hidden**, then to **visible**, the cursor will not be visible until it leaves the window, meaning in full screen it can't become visible again. There is no issue when switching between **visible** and **captured**, or **visible** and **hidden**. It's only when switching between **hidden** and **captured**, then to **visible**.

**Comment by Akira1San** [comment]
I also noticed, that the MOUSE_MODE_CAPTURED locks the keyboard. You have to move the mouse, then you can press a key and so on.

**Comment by akien-mga** [comment]
Can someone check the status in the current master branch?

CC @guilhermefelipecgs @capnm @avencherus

**Comment by guilhermefelipecgs** [comment]
It's working fine, including issues reported in the comments. Tested in win10 with e522baf.

**Comment by akien-mga** [comment]
Thanks!
