### ISSUE TITLE
Animation player's call method track doesn't update with script changes in an external editor

### ISSUE THREAD

**Issue by pablinos** [godotengine/godot#50510]
### Godot version

3.3, 3.x

### System information

macOS 11.4

### Issue description

With an `AnimationPlayer` node that has a 'Call Method' track. If the script for the node associated with the track is edited in an external editor, then the available methods to call doesn't update.

### Steps to reproduce

- Change the settings to launch an external editor for editing scripts
- Create scene and attach a script to the root node
- Add an `AnimationPlayer` node, a new animation, and a 'Call Method' track associated with the root node
- Add a method to the script file in the external editor
- Add a key frame to the 'Call Method' track 
- Notice that the new method is not availble to call
- Save and quit to the project list
- Reopen the project and now the method is available to call on the key frame

### Minimal reproduction project

[CallMethodTest.zip](https://github.com/godotengine/godot/files/6827993/CallMethodTest.zip)

This is a framework project for the above steps, but you would need to add a new method etc, as outlined in the steps above.

**Comment by pablinos** [comment]
I wondered if we could use the LSP `didSave` method to fix this, like in #48616 and #48615. Not that I want to give you more work to do @Razoric480 😄 I'd be happy to help, but I'm not sure my C++ and Godot knowledge is up to scratch.

**Comment by Razoric480** [comment]
I updated the PRs with a change that seems to fix this issue.
