### ISSUE TITLE
Vulkan: The "Display Unshaded" debug draw mode doesn't work as expected

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50522]
### Godot version

v4.0.stern-flowers.283.custom_build [4e4bcbc98]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

When the user wants to "Display Unshaded" he expect a completely `unlit` scene, with everything perfecly visible (no shadows, effects,  and so on) but seems that this option doesnt ignore the current vigent `World Environment` only the directional light!

as you can see:
* Top is "Display Unshaded"
* Bottom is "Display NORMAL"

![image](https://user-images.githubusercontent.com/58845030/125996969-11a9d91c-8d3f-4010-ad81-f173abb97e65.png)

### Steps to reproduce

* Create a 3d Scene
* Use 2 view panels
* Set "Display Ushaded" on top
* Set "Display Normal" on bottom

### Minimal reproduction project

N/a

**Comment by Calinou** [comment]
I would expect the unshaded draw mode to work as it does it in `3.x`. I think it keeps the background sky visible there.

**Comment by nonunknown** [comment]
even if it mantains the sky, worldenvironment node should be ignored!

**Comment by Calinou** [comment]
@nonunknown If you can still reproduce this on 4.0.stable or later, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by nonunknown** [comment]
@Calinou Seems its fixed in 4.0stable!

**Comment by Calinou** [comment]
Alright, closing then.
