### ISSUE TITLE
Addition assignment operator causes the assigned variable to change in gdscript

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#50523]
### Godot version

4.0.dev (60add98a4cff0d27c6aa2f52042555eccb86ed70)

### System information

Windows 10

### Issue description

Using `+=` operator between a property and a local variable can cause the local variable to take the value of the property.

It doesn't occur in 3.x versions.

### Steps to reproduce

In this example script:

```
extends Node2D

func _process(delta):
	var motion = Vector2(10.0, 0.0)
	position += motion
	print(motion)
```

The local variable `motion` ends up with its value being equal to `position` after the assignment, as observed in the printed value which increases every frame.

### Minimal reproduction project

[assignment-bug-gdscript.zip](https://github.com/godotengine/godot/files/6832875/assignment-bug-gdscript.zip)

**Comment by barbaros83** [comment]
/= *= += -= all crash when adding a value to a property as well, im getting the invalid operands error, says that its nil
