### ISSUE TITLE
audiostreamplayer2d doesnt play (SOLVED)

### ISSUE THREAD

**Issue by 2blackbar** [godotengine/godot#50525]
### Godot version

3.3.2

### System information

windows t 64bit

### Issue description

I have projectile/bullet scene, its area2D with sprite node and audiostreamplayer2d, sample in it loaded, works when testing play in editor

### Steps to reproduce

Once i preload  projectile scene in playable character(kinematic2d), the sound is not played, scene works and all, animation plays , everything fine, but sound from audiostreamplayer2d is not playing.
I call it like this in projectile ready:

func _ready():
	$fireb.play()

Also this sound plays fine when i test projectile scene alone, with only bullet onscreen flying on top.
Once its preloaded to be used by player, then sound doesnt play.

**Comment by Calinou** [comment]
AudioStreamPlayer2D is a *positional* audio node, so you will only hear the sound if the node is close enough to the camera. Try replacing it with an AudioStreamPlayer node instead.

**Comment by 2blackbar** [comment]
That worked, it can be closed, i didnt know that it just wont play at all
