### ISSUE TITLE
This autoload is shutting down android build, but works perfectly fine on windows export and in godot debug

### ISSUE THREAD

**Issue by 2blackbar** [godotengine/godot#50524]
### Godot version

3.3.2 stable

### System information

win 7 64 bit , android 8

### Issue description

autoload works fine on windows pc , but when testing apk oin android, its shutting down immediately
ITs just autoload with sound library.

I have no clue why godot even allows this, more tolerant on windows and less on android?
Took me about 5 hours to find the cause of the shutdown.

### Steps to reproduce

just set autoload for scene type "Node" which has like 4 audiostreamplayer2d nodes , one of them is called "fireb.

call it in here in projectile thats preloaded

func _ready():
	Sfx.get_node("fireb").play()

Test it on windows pc - works totally fine, export project to android, install apk, try it and enjoy shutdown

**Comment by Calinou** [comment]
@2blackbar Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
