### ISSUE TITLE
rotating 3d skeletone`s bone causes non-relative rotation of model (ESCN import)

### ISSUE THREAD

**Issue by ViktorcArmius** [godotengine/godot#50538]
### Godot version

3.3.2.stable.official

### System information

Windows 10, GLES3

### Issue description

i have a model with bones imported from blender to *.ESCN (and saved as tscn)

i have tried to rotate any random bones using transforms

    skel = get_node("Armature") #Skeleton node
    id = skel.find_bone("jaw")  #random bone
    t = skel.get_bone_pose(id)  #getting local transform
    t = t.rotated(Vector3(1.0, 0.0, 0.0), 30 ) #rotating around OX axis
    skel.set_bone_pose(id, t)   #setting local transforn

and it seems like mesh points are rotating relative to the model origin and not relative to the parent bone
![image](https://user-images.githubusercontent.com/45998866/126021219-ae7332ee-8783-4e6f-b05e-4ce37155eda5.png)

also, i have a simple model that rotates correctly 
![image](https://user-images.githubusercontent.com/45998866/126021257-b6645154-b9fe-4778-9593-ccd300a98561.png)

due to working simple model i think the problem is in the model but can't find the cause

### Steps to reproduce

i have both models exported as "Godot Engine (*.escn)" from blender 2.93.1
![image](https://user-images.githubusercontent.com/45998866/126021345-316eb1ed-006b-4f3e-ac4a-3550745b9898.png)

in godot engine i re-saved both scenes as *.tscn

then i applied simple code to rotate bones relative to OX axis
```
  var skel = get_node("Armature") #Skeleton node
  var id = skel.find_bone("jaw")  #random bone
  
  func _ready():
  	pass
  
  func _process(delta):
	var t = skel.get_bone_pose(id)
	t = t.rotated(Vector3(1.0, 0.0, 0.0), 1 * delta)
	skel.set_bone_pose(id, t)
```

### Minimal reproduction project

[bones_test.zip](https://github.com/godotengine/godot/files/6833960/bones_test.zip)

**Comment by fire** [comment]
I wonder if the gltf2 export from Blender is ok.

https://github.com/godotengine/godot-blender-exporter Can also try making an issue here.

**Comment by ViktorcArmius** [comment]
bones works correctly with model exported as gltf 2.0

**Comment by fire** [comment]
Are you satisfied with this result?

**Comment by ViktorcArmius** [comment]
yes, that`s enough for me
