### ISSUE TITLE
Add Item Type dialog of theme editor focuses OK button by default

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#50545]
### Godot version

4.0.dev (de83ee57e)

### System information

macOS 11.4

### Issue description

After the "Add Item Type" dialog of the new Theme editor is popped up:

* Expected: the type name line edit gains focus so the user can start filtering classes immediately
* Actual: it's the OK button that's focused, and I have to click the name line edit manually in order to start filtering

This does not happen in 3.x.

### Steps to reproduce

1. Create a `Theme` resource
2. Click the plus icon button to bring up the "Add Item Type" dialog
    * ... and the OK button is focused

**Comment by pycbouh** [comment]
Is that something MacOS specific? Because that's exactly the behavior I've coded and it worked on Windows:

```
void ThemeTypeDialog::_dialog_about_to_show() {
	add_type_filter->set_text("");
	add_type_filter->grab_focus();

	_update_add_type_options();
}
```

**Comment by timothyqiu** [comment]
I'm not sure and it works OK on 3.x.

The "Create New Node" dialog in the Scene panel correctly focuses the search box after popup though.

**Comment by pycbouh** [comment]
Okay, it's not working for me either in `master`, so not MacOS specific, will investigate.
