### ISSUE TITLE
Unhelpful Internal Error with Opcode #13

### ISSUE THREAD

**Issue by Null-14** [godotengine/godot#50541]
### Godot version

3.3.2 Stable Mono

### System information

Windows 10, AMD Ryzen 5 3800X EVGA NVIDIA 1060 SSC Super 6GB, Rendering on GLES3

### Issue description

This is my first time reporting an issue to a project, so If I have done this incorrectly, be sure to let me know. Pls no bully.

My game project has recently broken for no apparent cause. I have been unable to debug what is causing this, as the only messages are entirely unhelpful to me.

The Output is as follows:

--- Debugging process started ---
 scene/gui/text_edit.cpp:6082 - Index p_line = -1 is out of bounds (text.size() = 24).
 scene/gui/text_edit.cpp:5722 - Index p_line = -1 is out of bounds (text.size() = 24).
 scene/gui/text_edit.cpp:6082 - Index p_line = -1 is out of bounds (text.size() = 24).
 scene/gui/text_edit.cpp:6082 - Index p_line = -1 is out of bounds (text.size() = 24).

With the following error:

E 0:00:00.801   call: Condition ' !nc ' is true. Breaking..:
  <C++ Source>  modules/gdscript/gdscript_function.cpp:805 @ call()
  <Stack Trace> SettingsMenu.tscn::1:0 @ _init()

The game did not crash, but is totally broken.

<img width="513" alt="Renderer is broken" src="https://user-images.githubusercontent.com/60370288/126023192-290a46af-df37-42a3-a539-a12069caaa1e.PNG">

At the moment, I have absolutely no idea what caused this, however, if I can get in touch with someone that wants the project to fix it, I can possibly do so.

The problem first appeared when attempting to load a packed scene which contained an interface with a canvas layer as the root node then add this as a child to another interface. After building this change, the engine has this error everytime I attempt to build the game, even having reverted changes. I will likely reinstall the engine to see if I can cause it again, but do not have time to do so tonight.

I will look into if I can create a project which specifically reproduces this or not. Sometime tomorrow, when, if ever, this will be completed, however, is uncertain.

### Steps to reproduce

Will determine soon™. The little output there is and the point this began to occur suggests some sort of a rendering issue with scaling some text. I don't know what text specifically this could be, but will look into it tomorrow. I have several interfaces that could be causing this, and will have to test each one separately, as well as the possibility of it having been caused by adding a canvas layer node in GDscript.

### Minimal reproduction project

This will be added soon. Expect it sometime after 1:00 PM Mountain Time 07/17/2021. May never be added if I cannot find a way to reproduce this outside of my particular project.

**Comment by Null-14** [comment]
If I have written anything odd, I am currently half asleep and so apologize in advance. I will reassess this tomorrow, however, the message I got in the editor said "please report", so I have.

**Comment by Calinou** [comment]
@Null-14 Do you have any type hints in a script that have the same name as an engine singleton? See https://github.com/godotengine/godot/issues/52893.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
