### ISSUE TITLE
Saved scene files have redundant `structured_text_bidi_override_options = []` properties

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#50544]
### Godot version

4.0.dev (8747f2565)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

See also https://github.com/godotengine/godot/issues/50543.

Saving a scene as a `.tscn` file results in redundant `structured_text_bidi_override_options = []` for the Label, LineEdit, RichTextLabel, LinkButton and TextEdit nodes.

The C++ member matching that property is initialized to an empty array everywhere it is defined. Its value is not overridden in the constructor, and it doesn't have any values pushed to it by default:

![image](https://user-images.githubusercontent.com/180032/126024772-03c8bce9-a1e2-4c6c-989a-57cc2c3a3bdf.png)

***Note:** Tree's `st_args` is for the Cell subclass, which isn't a node.*

### Steps to reproduce

- Create a scene with a Label node.
- Save the scene as a `.tscn` file

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Seems fixed.
