### ISSUE TITLE
Bug in Transform::xform(Plane) with non-uniform scaling

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#50548]
### Godot version

3.4 beta 1, 4.x

### System information

All

### Issue description

I noticed while debugging the physics that when transforming planes, the normals appeared to be incorrect. Transforming vertices then rebuilding planes resulted in different planes to transforming the planes directly with `Transform::xform`.

It turns out there is quite a nasty bug. The plane transform currently works by taking a point on the plane (point), and creating another offset by the normal (point_dir). It then transforms both points, then back calculates the new plane.

```
_FORCE_INLINE_ Plane Transform::xform(const Plane &p_plane) const {
	Vector3 point = p_plane.normal * p_plane.d;
	Vector3 point_dir = point + p_plane.normal;
	point = xform(point);
	point_dir = xform(point_dir);

	Vector3 normal = point_dir - point;
	normal.normalize();
	real_t d = normal.dot(point);

	return Plane(normal, d);
}
```

The problem with this is illustrated with an example.
Consider in 2d a plane facing 1, 1.

If we transform by stretching on the x axis by two..., i.e. scale 2, 1.

In the diagram, two ends of such a line we might go from
### diagram 1
0, 1 - 1, 0 to
### diagram 2
0, 1 - 2, 0.
However, the point_dir gets stretched _further_ in the x direction, so it points more to the right (red normal), whereas with the decreased slope we want to point it more to the left (the blue normal).

![plane_xform_bug](https://user-images.githubusercontent.com/21999379/126034329-1b334cb5-961e-404e-9ffb-931c16ba8037.png)

This can be fixed by e.g. transforming the normal independently, with e.g. inverse transpose matrix.

The interesting thing is this bug will presumably have affected everything using this routine with non-uniform scaling, and there may be counter bugs to deal with this error.

A similar bug may also occur in `xform_inv`.

### Steps to reproduce

Create a Plane with normal (1, 1, 0). Transform by scaling 2, 1, 1. See that the new normal is incorrect.

## Simplistic Fix
```
_FORCE_INLINE_ Plane Transform::xform(const Plane &p_plane) const {
	Vector3 point = p_plane.normal * p_plane.d;
	point = xform(point);
	Basis b = basis;	
	b.invert();
	b.transpose();
	Vector3 normal = b.xform(p_plane.normal);
	normal.normalize();
	real_t d = normal.dot(point);
	return Plane(normal, d);
}
```
I'll be doing a PR for this later but want to do some considerations of efficiency and look at any knock on bugs - the fix has to be done with some care, because other code may have been depending on the bugged condition.

**Comment by pouleyKetchoupp** [comment]
Fixed in 4.0 (https://github.com/godotengine/godot/pull/51355) and 3.4 (https://github.com/godotengine/godot/pull/50637).
