### ISSUE TITLE
PopupMenu: add_submenu() documentation does not tell that submenu should already exist

### ISSUE THREAD

**Issue by Houkime** [godotengine/godot#50555]
### Godot version

3.3.2 stable AND v4.0.dev.custom_build [a0d800e96]

### System information

Arch Linux (kernel 5.12.15-arch1-1, X11)

### Issue description

PopupMenu's `add_submenu_item()` description reads:
```
Adds an item that will act as a submenu of the parent PopupMenu node when clicked. The submenu argument is the name of the child PopupMenu node that will be shown when the item is clicked.

An id can optionally be provided. If no id is provided, one will be created from the index.
```

First times i read this, i thought that this method will actually create the PopupMenu subnode, and the name here is so that i can access the child node like this (wow, github actually has a dedicated gdscript highlighting):

```gdscript
extends MenuButton

func _ready():
	get_popup().add_submenu_item("submenu label","submenu")
	get_popup().get_node("submenu").add_item("submenu item")
```

On 4.0 this throws a misleading (and buggy) error of previously freed instance (https://github.com/godotengine/godot/issues/48891), which makes things even worse, since now i think that my submenu WAS created but some incredibly evil bugforce insta-erased it.

It took me a trip to the godot sources to find an example of how godot editor itself does this (`editor_node.cpp`).

```cpp
vcs_actions_menu = VersionControlEditorPlugin::get_singleton()->get_version_control_actions_panel();
vcs_actions_menu->set_name("Version Control");
vcs_actions_menu->connect("index_pressed", callable_mp(this, &EditorNode::_version_control_menu_option));
p->add_separator();
p->add_child(vcs_actions_menu);
p->add_submenu_item(TTR("Version Control"), "Version Control");
vcs_actions_menu->add_item(TTR("Set Up Version Control"), RUN_VCS_SETTINGS);
vcs_actions_menu->add_item(TTR("Shut Down Version Control"), RUN_VCS_SHUT_DOWN);
```

So, the right way to do this is :
```gdscript
extends MenuButton

func _ready():
	var submenu = PopupMenu.new()
	submenu.set_name("submenu")
	submenu.add_item("submenu item")
	get_popup().add_child(submenu)
	get_popup().add_submenu_item("submenu label","submenu")
```
The documentation (or, ideally, function's name) should reflect the fact that it is the reader's job to get a correctly named submenu there. Example code like above (but above is written from the MenuButton point of view) would also be nice.

### Steps to reproduce

* Try to forget all you know as a Godot dev.
* Look at the documentation of add_submenu_item().

**Comment by Houkime** [comment]
on the improvement side of things, comparing my expectations and how it actually works, it is hard not to notice that something like this would be a much easier way:

```gdscript
submenu = add_submenu_item("submenu label")
submenu.add_item("submenu item")
```

Maybe this is how it should actually work?

**Comment by EricEzaM** [comment]
Yeah having to reference by the nodes name feels pretty yuck.

**Comment by kalshen2018** [comment]
Easily misunderstood and difficult to use.it took me two hours to test.

**Comment by jsjtxietian** [comment]
When deal with another bug, I found the doc is easily misunderstood for me too.
