### ISSUE TITLE
Regression in the GDNative API generator: Creates invalid JSON for `AESContext::update()`

### ISSUE THREAD

**Issue by ChronicallySerious** [godotengine/godot#50554]
### Godot version

3.4.beta1

### System information

Windows 10

### Issue description

```shell
.\godot.windows.tools.64.exe --gdnative-generate-json-api api.json
```
The above command generates a file `api.json` which can then be used in GDNative plugins that are currently working on a custom Godot build or unreleased Godot versions (like 3.x). 

However, this command is currently generating an artefact which later on causes `godot-cpp` to fail to compile and be used in a plugin.

This is specifically the case with the JSON created for the `AESContext::start()` function as shown below.
```json
{
	"name": "start",
	"return_type": "enum.Error",
	"is_editor": false,
	"is_noscript": false,
	"is_const": false,
	"is_reverse": false,
	"is_virtual": false,
	"has_varargs": false,
	"is_from_script": false,
	"arguments": [
		{
			"name": "mode",
			"type": "int",
			"has_default_value": false,
			"default_value": ""
		},
		{
			"name": "key",
			"type": "PoolByteArray",
			"has_default_value": false,
			"default_value": ""
		},
		{
			"name": "iv",
			"type": "PoolByteArray",
			"has_default_value": true,
			"default_value": "[PoolByteArray]" // <- Notice the square brackets
		}
	]
},
```
This then gets converted into the code below by the godot-cpp API generator, which is not actually valid C++.
```cpp
Error start(const int64_t mode, const PoolByteArray key, const PoolByteArray iv = [PoolByteArray]);
```

EDIT: A workaround is to manually remove the `"default_value"` key and change "has_default_value" to `false`. This should at least let godot-cpp compile without errors.

### Steps to reproduce

1. Generate api.json
```shell
.\godot.windows.tools.64.exe --gdnative-generate-json-api api.json
```
2. Open api.json, search for `[PoolByteArray]`
3. You should find it in `AESContext > start`

### Minimal reproduction project

N/A

**Comment by Faless** [comment]
I don't know much about the JSON API generator.
The code in `AESContext` is valid:

```
        Error start(Mode p_mode, PoolByteArray p_key, PoolByteArray p_iv = PoolByteArray());
```

We could change it to be `Vector<uint8_t>()` (although they're not really the same in `3.x`).

**Comment by Faless** [comment]
Turns out it's an error in the `godot-cpp` binding generator: See godotengine/godot-cpp#590

**Comment by ChronicallySerious** [comment]
@Faless Correct me if I am wrong, if the problem was solely in godot-cpp, shouldn't we have not seen `[PoolByteArray]` in api.json in the first place?

The api.json has the square bracket symbols right after getting generated from the Godot binary and AFAIK it doesn't look like it belongs there.

**Comment by Faless** [comment]
> @Faless Correct me if I am wrong, if the problem was solely in godot-cpp, shouldn't we have not seen `[PoolByteArray]` in api.json in the first place?

The default argument is written by the parser as a `Variant.operator String()`. In fact, it generates `[]` also for other things, like string array, int array, ecc. The reason why it writes the name is that `Variant.operator String()` is not implemented for PoolByteArray. We could also implement that, but still wouldn't fix the issue in the godot-cpp bindings.

In fact, in some places you also get `[Object:null]` as default arguments in the generated json api.
