### ISSUE TITLE
icons not representative of data

### ISSUE THREAD

**Issue by DavidCambre** [godotengine/godot#50557]
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

In VisualScript the icons are out of oreder.
Vector2 Icon now is Plane, Transform now shows RID etc.
![image](https://user-images.githubusercontent.com/20573784/126038837-61bc5267-8d2b-4b6a-98e9-dbb55aec563b.png)

### Steps to reproduce

open attached VisualScript press rmb

**Comment by fire** [comment]
There's a place in C++ where we have to sync icons. There's a message to sync, but i think it was forgotten.

**Comment by DavidCambre** [comment]
Do you mean #49462 ?
