### ISSUE TITLE
Imported GLTF Materials Do Not Respect Default Cull Mode

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#50552]
### Godot version

3.3.2 Stable

### System information

Windows 10 v20H2, Intel i7 6700, Nvidia GTX1080, 16GB RAM

### Issue description

When importing a GLTF model Godot sets the Cull Mode to "disabled" for all imported materials. This is not the default behavior, since when hitting the "reset" button the Cull Mode is set to "Back". Using backface culling by default is more efficient in an import workflow since most times you will want to be culling the backfaces to save performance.

It does not seem that you can change this setting in the Import dialogue and must reset it to default manually for every material.

### Steps to reproduce

1. Import the attached cube object. It has a simple material applied called "cube material".
2. Create new Inherited Scene.
3. Select cube mesh. Under Surface 1 > Parameters, Cull Mode will be set to Disabled.

[Cube.zip](https://github.com/godotengine/godot/files/6834644/Cube.zip)

**Comment by Calinou** [comment]
cc @fire 

See also https://github.com/godotengine/godot/issues/42294.

**Comment by timothyqiu** [comment]
If I understand it correctly, culling is a property that's determined by the GLTF/GLB.

You'll also get a material with culling disabled if you import your cube in Blender. The culling will be set to back if you export the cube with back face culling checked in its material and then import it in Godot.

**Comment by fire** [comment]
Godot is respecting the cube's material settings.

```

  "materials": [
    {
      "doubleSided": true,
      "name": "Cube Material",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.8000000715255737,
          0.14552806317806244,
          0.060454949736595154,
          1
        ],
        "metallicFactor": 0,
        "roughnessFactor": 0.5240641832351685
      }
    }
  ],
```

`doubleSided": true`

Please ask Blender to change their defaults.

**Comment by WickedInsignia** [comment]
@fire You're right! I assumed that backface culling was determined engine-side and not by the file. Turns out that can be defined in the Blender Materials tab and I can confirm it comes through properly in Godot.
![Blender backface culling](https://user-images.githubusercontent.com/70243134/126051950-9272b0f1-022d-4020-b1ab-65c79166f0a0.JPG)

**Comment by Calinou** [comment]
We should document this somewhere. Any ideas which page we should add a note on?

**Comment by WickedInsignia** [comment]
@Calinou Sounds great! If I can suggest, it could either be a disclaimer in the Parameters > Cull Mode section of [THIS PAGE](https://docs.godotengine.org/en/stable/tutorials/3d/spatial_material.html), or it could be a mention as part of the Scene Import workflow on [THIS ONE](https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_scenes.html).

I feel that the former would be more likely to be seen (It was harder for me to find the 3D asset import page), but up to you of course and open to suggestion.
