### ISSUE TITLE
Assigning anything to diffuse light makes the albedo unused

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#50564]
### Godot version

v4.0.dev.custom_build [60add98a4]

### System information

Linux Arch, Radeon RX 590

### Issue description

When assigning anything to diffuse light or specular_light, ALBEDO isn't used anymore.

Might

Mesh in godot4
![Screenshot_2021-07-17_22-57-05](https://user-images.githubusercontent.com/7917475/126049231-6e9f7e07-68e1-43b6-b1c0-2054d1275b5b.png)
Mesh in Godot3
![Screenshot_2021-07-17_22-56-52](https://user-images.githubusercontent.com/7917475/126049233-f442a1d9-683d-4bfc-b033-fa679aca1478.png)

### Steps to reproduce

Assign this shader, and comment the DIFFUSE_LIGHT line:

```glsl
shader_type spatial;

uniform float power_diffuse = 2.0;
uniform float glossiness = 1.0;

void fragment(){
	ROUGHNESS = 0.3;
	ALBEDO = vec3(1.0, 0.0, 0.0);
}

void light(){
	float dot_val = dot(LIGHT, normalize(NORMAL));
	dot_val =  clamp(dot_val, 0.0, 1.0);
	dot_val = pow(dot_val, power_diffuse);
	DIFFUSE_LIGHT += dot_val * ATTENUATION * ALBEDO;
}
```

### Minimal reproduction project

see above

**Comment by nevarek** [comment]
Cannot reproduce on [3990152f6b](https://github.com/godotengine/godot/commit/3990152f6b7fcbac39ed68f0cc0fd36131bc9e2f) (current master), can you verify that this is still an issue?

**Comment by Calinou** [comment]
I can't reproduce this on 212989d46 (Linux, NVIDIA 510.60.42).

[test_shader_light.zip](https://github.com/godotengine/godot/files/8606376/test_shader_light.zip)

### `DIFFUSE_LIGHT` unused

![2022-05-03_00 18 28](https://user-images.githubusercontent.com/180032/166336243-540f94b7-8bfd-41b5-9e49-34d1aff6376b.png)

### `DIFFUSE_LIGHT` used

![2022-05-03_00 18 33](https://user-images.githubusercontent.com/180032/166336245-f7c20d7f-cfaa-4670-afe4-a311c9f62b56.png)
