### ISSUE TITLE
Tooltips are clickable

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#50571]
### Godot version

6263f58

### System information

W10

### Issue description

You can hover mouse on the tooltips and click them:
![qAJqbrbNuz](https://user-images.githubusercontent.com/2223172/126050679-e7461b05-0074-42f0-8507-5b1492ade6c2.gif)
Notice how the main window gets unfocused as I click the tooltip. It will also block my clicks.

### Steps to reproduce

1. Hover over something so a tooltip appears
2. Move your cursor over the tooltip
3. Click

**Comment by EricEzaM** [comment]
Should be fixed by #48186
