### ISSUE TITLE
Illegible texts in audio bus editor when using a light theme

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#50583]
### Godot version

3.3.2, 3.x(9636deac55), 4.0.dev (b76dfde329)

### System information

macOS 11.4

### Issue description

When using light themes, name of the Master audio bus is hard to read. I think it's even using the same color as the background when in focus:

![name](https://user-images.githubusercontent.com/372476/126069850-95c39f11-9e7e-4243-8898-e0014a296968.png)

In 3.x, no matter which theme you use, the volume preview tooltip shown when dragging the volume handle is also using a similar color as the background:

![tooltip](https://user-images.githubusercontent.com/372476/126069912-3dd235ac-4795-4f44-93e3-40d60bdee415.png)

### Steps to reproduce

For the master bus name, change editor theme to Light.

Drag the volume handle in audio bus editor to see the tooltip, note that it's different from the hover tooltip.

**Comment by Calinou** [comment]
> In 3.x, no matter which theme you use, the volume preview tooltip shown when dragging the volume handle is also using a similar color as the background:

This should have been fixed by https://github.com/godotengine/godot/pull/49130, which was cherry-picked to `3.x`.

**Comment by timothyqiu** [comment]
@Calinou The 3.x screenshots are from 9636deac55 which is the current latest `3.x`.

The Dark theme screenshot is what you get after opening a default editor. Restarting the editor after switching the Light theme does not help, the text color still looks the same as in the screenshot.
