### ISSUE TITLE
Add Item Type dialog of theme editor does not clear text on reopen

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#50584]
### Godot version

3.x (9636deac55)

### System information

macOS 11.4

### Issue description

Type some text in "Add Item Type" dialog and close the dialog (close / cancel / ok / enter). Reopen the dialog, the text will still be there.

Opposite to the last time, this only happens on `3.x`, and the text is cleared properly on `master`.

### Steps to reproduce

1. Open the theme editor
2. Click the "+" button to open the "Add Item Type" dialog
3. Type some text and hit enter, the dialog closes
4. Click the "+" button again, the text remains there

**Comment by pycbouh** [comment]
Fixed by https://github.com/godotengine/godot/pull/50586.
