### ISSUE TITLE
Vulkan validation error on gather SSAO

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#50580]
### Godot version

4.0.dev b76dfde329592ecfd6f6b952082ae21859039e67

### System information

Windows 10 Vulkan

### Issue description

Running current version gives error spam when using Vulkan Validation Layers:
```
ERROR: VALIDATION - Message Id Number: -564812795 | Message Id Name: VUID-VkDescriptorImageInfo-imageLayout-00344
	Validation Error: [ VUID-VkDescriptorImageInfo-imageLayout-00344 ] Object 0: handle = 0x1ce18496c08, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xde55a405 | vkCmdDispatch(): Cannot use VkImage 0x3bc75b0000005eba[SSAO Depth] (layer=0 mip=0) with specific layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL that doesn't match the previous known layout VK_IMAGE_LAYOUT_GENERAL. The Vulkan spec states: imageLayout must match the actual VkImageLayout of each subresource accessible from imageView at the time this descriptor is accessed as defined by the image layout matching rules (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-VkDescriptorImageInfo-imageLayout-00344)
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_COMMAND_BUFFER, Handle 1984682355720
	Command Buffer Labels - 2
		Label[0] - Gather Samples{ 1, 1, 1, 1 }
		Label[1] - SSAO{ 1, 1, 1, 1 }
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157)
```
Error is triggered by the call to `RD::get_singleton()->compute_list_dispatch_threads(p_compute_list, size.x, size.y, 1);` in ` EffectsRD::gather_ssao`

### Steps to reproduce

Got this testing the material tester project

### Minimal reproduction project

https://github.com/BastiaanOlij/godot-demo-projects/tree/material_testers_4.0/3d/material_testers

**Comment by clayjohn** [comment]
I think we need a barrier that transitions the resource usage. This is probably caused by the PR adding subpasses.

**Comment by BastiaanOlij** [comment]
> 
> 
> I think we need a barrier that transitions the resource usage. This is probably caused by the PR adding subpasses.

This is using the clustered renderer though, might be worth doing a bisect to make sure

**Comment by clayjohn** [comment]
There was changes to the resource transition code at the same time! I'll take a closer look.

**Comment by BastiaanOlij** [comment]
This was resolved ages ago.
