### ISSUE TITLE
Can't explicitly specify `void` return type on `_init()`

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#50589]
### Godot version

v4.0.dev.calinou.de83ee57e

### System information

Windows 10 x64

### Issue description

When using typed GDScript, you can specify return types for functions via `func func_name() -> return_type:`. This is disallowed for `_init()`, which mostly makes sense as init can never return anything. But you also can't manually say that init returns nothing via `func _init() -> void:` -- it still gives you "Error at (line number): Constructor cannot have an explicit return type."

It's not a big bug, but it bugs me that I can't have a (void) return type on init though all of my other functions have return types, many of which are void.

### Steps to reproduce

func _init() -> void:

**Comment by KoBeWi** [comment]
IMO it's ok to disallow it, but then "Add Type Hints" option shouldn't put the `void` return for constructor.
