### ISSUE TITLE
Script List sometimes displays class reference name incorrectly.

### ISSUE THREAD

**Issue by NeoNeqs** [godotengine/godot#50596]
### Godot version

4.0.dev (b76dfde32)

### System information

Windows 10, Vulkan, GTX 1050 mobile 471.11

### Issue description

When you click "Search Help" button in Script Editor and select any children of EditorPlugin and then open the same script from FileSystem the class reference on the left changes from full path to file name with a double quote at the end.

E.g.:
`"addons/addon_name/main.gd"` changes to `main.gd"`   <--- notice the double quote

![image](https://user-images.githubusercontent.com/76450252/126082956-30effff8-4d49-4c39-bdad-de5c61362e73.png) 
![image](https://user-images.githubusercontent.com/76450252/126082976-60b341b6-5ad5-40bc-b8dc-645c285109f6.png)

### Steps to reproduce

* Go to Project -> Project Settings -> Plugins -> Create
* Give the plugin name, subfolder and main script (e.g. main.gd)
* Click "Search Help" and open main.gd (It will be a children of EditorPlugin Node)
* Notice that full path of the class refence is shown on the left
* Open main.gd script from FileSystem
* Now the class reference name is `main.gd"`

### Minimal reproduction project

[ScriptDisplayBug.zip](https://github.com/godotengine/godot/files/6836990/ScriptDisplayBug.zip)

**Comment by NeqsTech** [comment]
Also the Label showing currently selected item displays path with striped slashes (image 1)

**Comment by Calinou** [comment]
@NeqsTech Can you reproduce this in 3.3.2?

**Comment by NeqsTech** [comment]
@Calinou I don't think this can be reproduced in 3.3.2. When I click "Search Help" there are no children under "Editor Plugin" node. 

I guess documentation generation for user-defined scripts wasn't cherry-picked for 3.3.2-stable or at all.

**Comment by Calinou** [comment]
> I guess documentation generation for user-defined scripts wasn't cherry-picked for 3.3.2-stable or at all.

Indeed, this was added by https://github.com/godotengine/godot/pull/41095 which relies on GDScript 2.0.

**Comment by KoBeWi** [comment]
Doesn't happen in 4.3
![image](https://github.com/godotengine/godot/assets/2223172/675a68ea-b2a3-4683-8a3c-dc87a11559ed)
