### ISSUE TITLE
Overridden Functions Not Called if Invoked from a Typed Variable

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#50591]
### Godot version

v4.0.dev.calinou.de83ee57e

### System information

Windows 10 x64

### Issue description

Let's say you want to override a built-in function like `queue_free()`. That's easy and straightforward and normally when you call `object.queue_free()` the overridden implementation takes precedent.

But if `object` is a typed variable reference and it's typed to something higher up in the hierarchy than your overridden implementation (or so I speculate), then the custom implementation is not called.

### Steps to reproduce

Have some object override `queue_free()`. Make a variable reference to it that is typed (`var typed_reference : Node = $Path`). Call `typed_reference.queue_free()` and notice that the custom code you wrote was ignored.

Meanwhile if you reference was `var untyped_reference = $Path` then calling `untyped_reference.queue_free()` would have the expected behavior.

### Minimal reproduction project

[QueueFree.zip](https://github.com/godotengine/godot/files/6836862/QueueFree.zip)

There are two instances of the same class which has an overridden `queue_free()`. I instantiate them both in the same manner and treat them almost identically except one reference is held in a typed variable and the other is held in an untyped variable.

When I call `queue_free()` on both of them, the custom `queue_free()` implementation is only called on the untyped variable reference.

Object-oriented inheritance should not be broken just based on the type assigned to a variable. (This bug took a real long time to isolate.)

**Comment by quantumcode-martin** [comment]
Also, let's say I have a script with this `queue_free` override:
```
func queue_free():
	print("emit")
	super.queue_free()
```

Inside this script, if I call `queue_free()` nothing will be printed, which is wrong to me (?). I need to call `self.queue_free()` to have the expected result.
I'm not sure it's linked so tell me if I need to open a new issue for this.

**Comment by dalexeev** [comment]
Overriding non-virtual native methods is not supported. See #72608.
