### ISSUE TITLE
GDScript 2.0: Parent `_init()` function not called if child class doesn't define it

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#50590]
### Godot version

v4.0.dev.calinou.de83ee57e

### System information

Windows 10 x64

### Issue description

Recent GDScript changes no longer automatically call parent functions on methods like `_init()`, `_ready()`, `_process(delta)`, etc if a child class has a definition for them that does not manually call `super.whatever()`. I'm fully in support of this.

But if you have a parent class which has `_init()` defined and then you have a child class which does not have `_init()` defined, `_init()` will not be called. This is different than how all other such functions behave.

### Steps to reproduce

Create some class which has an `_init()` defined. Then create a script which extends it and has no definition for `_init`.

Instantiate the child class and notice that `_init()` does not get called, even though there's nothing overriding it.

### Minimal reproduction project

[Init.zip](https://github.com/godotengine/godot/files/6836851/Init.zip)

I have two classes, Parent and Child, which both have `_init()` and `_ready()` defined. As is if you run the project you'll get the Child class' output for both functions; it overrides them after all.

Comment out the Child's definition of `_ready()` and run it and you'll get the Parent's version of it. This also makes sense -- that is now the only definition of `_ready()` in the hierarchy.

But comment out the Child's definition of `_init()` and the Parent's definition will not get called. Despite being the only definition available. This is surprising and inconsistent with every other similar function's implementation.

**Comment by SaracenOne** [comment]
Should be resolved by this PR https://github.com/godotengine/godot/pull/51456

**Comment by SaracenOne** [comment]
The PR referenced has been merged so would recommend this issue can now be closed

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot/pull/51456

**Comment by vnen** [comment]
I guess someone forgot to click the close button. Closing now as fixed.
