### ISSUE TITLE
Duplicate Button inside get_drag_data() gives out of context warning about focus

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#50594]
### Godot version

3.3.2.stable.official

### System information

Ubuntu

### Issue description

Duplicating a `Button` inside the `get_drag_data()` method, gives this warning:
`W 0:00:01.621   set_enabled_focus_mode: BaseButton's Enabled Focus Mode property has been deprecated due to redundancy and will be removed in Godot 4.0. Please use Control.set_focus_mode instead.`
Whatever the cause of the warning is, it's out of context in this particular case.

This is a rather common operation because when dragging a button you may want to duplicate it to then use it as a drag-preview with `set_drag_preview()`,

### Steps to reproduce

Download the reproducible demo and try to drag the button.
This will immediately trigger the warning.

### Minimal reproduction project

[ButtonFocusUselessWarningDemo.zip](https://github.com/godotengine/godot/files/6836903/ButtonFocusUselessWarningDemo.zip)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/48199.
