### ISSUE TITLE
the angle given by diffrent functions dont match up

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot#50616]
### Godot version

3.3.2

### System information

Solus Linux

### Issue description

When i make 1 node2d look at another node2d, when the angle should indicate that the x axis of its transform to the global position of the second node2d should be 0, diffrent functions found in gdscript give diffrent results.
the dot function in the vector2 class should give 1.0 when there is 0 degree diffrence, but only does so when the x axis of the transform points slighty lower then the second node2d global positon.
the same goes for the angle_to function found in vector2 class, it only show close to 0.0 when its slighty lower then the second node2d global position.
but the node2d's get_angle_to function seems to give the correct result.

### Steps to reproduce

run the project and move the slider to check the angles between the 2 node2D's
diffrent functions give diffrent results

### Minimal reproduction project

[AngleTest.zip](https://github.com/godotengine/godot/files/6842958/AngleTest.zip)

**Comment by kleonc** [comment]
@barbaros83 I don't see any bug in here, the only problem seems to be your logic/code. First two lines in here don't make much sense (you're using local basis vector of one object and global position of another object):
```
func _process(_delta: float) -> void:
	vectorAngleToLabel.text = str(player.transform.x.angle_to(target.global_position))
	vectorDotLabel.text = str(player.transform.x.dot(target.global_position.normalized()))
	node2DGetAngleToLabel.text = str(player.get_angle_to(target.global_position))
```
Fixing the logic/math by changing it to:
```
func _process(_delta: float) -> void:
	var player_to_target_global_direction_vector = player.global_position.direction_to(target.global_position)
	vectorAngleToLabel.text = str(player.global_transform.x.angle_to(player_to_target_global_direction_vector))
	vectorDotLabel.text = str(player.global_transform.x.dot(player_to_target_global_direction_vector))
	node2DGetAngleToLabel.text = str(player.get_angle_to(target.global_position))
```
makes it produce expected, correct results.

**Comment by barbaros83** [comment]
@kleonc thnx for the clarification
