### ISSUE TITLE
Curve editor handles too small on Hi-DPI displays

### ISSUE THREAD

**Issue by Atlinx** [godotengine/godot#50617]
### Godot version

v3.3.stable.mono.official

### System information

Windows 10

### Issue description

The curve editor handles are too small on Hi-DPI displays (see image below).

The Hi-DPI curve editor is shown on the top.
The normal DPI curve editor is shown on the bottom.

![handle_comparison](https://user-images.githubusercontent.com/25368491/126211930-8d251ed2-d3d0-4741-8506-3c04792b857d.png)

### Steps to reproduce

Open Godot editor on a Hi-DPI display and try to edit a curve resource.

### Minimal reproduction project

[Curve Handle Scaling Bug.zip](https://github.com/godotengine/godot/files/6843242/Curve.Handle.Scaling.Bug.zip)

**Comment by Calinou** [comment]
If anyone wants to try their hand at fixing this, look at [`editor/plugins/curve_editor_plugin.cpp`](https://github.com/godotengine/godot/blob/master/editor/plugins/curve_editor_plugin.cpp), find where the selection rectangles are drawn *and* where the intersection tests are done (the visual representation should match the points' "hitbox"), and multiply those values by `EDSCALE` like this:

```cpp
// A size of 5 becomes:
Math::round(5 * EDSCALE);
```

To test the editor at different scales, open **Editor > Editor Settings** and set **Interface > Editor > Display Scale** to a larger value like 150% or 200%.

**Comment by Atlinx** [comment]
I've always wanted to contribute so I'll give it a shot.

**Comment by Atlinx** [comment]
Hey Calinou I have a question about this:

> * Multiply the rectangle sizes in both drawing and input by `EDSCALE` like this
> 
> ```c++
> // A size of 5 becomes:
> Math::round(5 * EDSCALE);
> ```

Do I need to round every time I multiply by the editor scale? Some of the code in `curve_editor_plugin.cpp` has no rounding at all when multiplying by the editor scale.

**Comment by Calinou** [comment]
> Do I need to round every time I multiply by the editor scale? Some of the code in curve_editor_plugin.cpp has no rounding at all when multiplying by the editor scale.

It's best to round to make non-integer scale factors behave better, but it's not strictly required. When you don't round, the number will be truncated, which means `1.5` will become `1.0` instead of `2.0`. In general, I find rounding up looks better than rounding down when dealing with hiDPI scaling.

**Comment by akien-mga** [comment]
Fixed by #50627.
