### ISSUE TITLE
Godot 4.0 Scons error, Python 3.6 f-Strings are not supported

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [godotengine/godot#50629]
### Godot version

4.0 dev

### System information

rpi4(8 gb ram) running reaspberry pi os

### Issue description

Im trying to compile godot 4.0 (what there is of it right now) to check it out and see some of the new features (yes, i know it is in development and very unstable right now, im just wanting to take a look at it and i am not planning on really using it for anything), iI have been able to compile godot 3.x without errors using this command: ```scons platform=x11 target=release_debug tools=yes -j4 module_webm_enabled=no LINKFLAGS="-latomic"```
When i try running that command to compile what there is of godot 4.0 right now i get this error: 
![image](https://user-images.githubusercontent.com/75915540/126253569-d1f54822-e882-4269-8c90-2ed624de327f.png)
Is this an problem with the command that im running or is it actually a bug that needs to be fixed?

### Steps to reproduce

Runn this command ```scons platform=x11 target=release_debug tools=yes -j4 module_webm_enabled=no LINKFLAGS="-latomic"``` to try and compile godot 4.0 on a rpi4 running raspberry pi os

**Comment by akien-mga** [comment]
What Python version do you have?

**Comment by The-Sapphire-Starship** [comment]
@akien-mga here is the answer to your question even though it looks like you figured out the problem:
![image](https://user-images.githubusercontent.com/75915540/126317203-0de2718a-b566-401f-a553-ff0b890dd003.png)

**Comment by akien-mga** [comment]
Well f-Strings should be supported as of Python 3.6, so it should work for you too.
Maybe your SCons uses Python 2, in which case you won't be able to compile Godot even after the fix I made. You'll need to use SCons with Python 3.

**Comment by The-Sapphire-Starship** [comment]
o right, maby that is the issue, how can i tell it to use python 3 instead?

**Comment by The-Sapphire-Starship** [comment]
Yea thats what its doing 
![image](https://user-images.githubusercontent.com/75915540/126317789-feb11f82-62c9-48f7-aee5-59e95b75f188.png)

**Comment by akien-mga** [comment]
You should be able to force it with `python3 /usr/bin/scons` (or wherever your scons is installed). Or you can edit the shebang of `/usr/bin/scons` to use `python3` instead of `python`.

**Comment by The-Sapphire-Starship** [comment]
Thanks you for the help, that seems to have corrected that problem, i seem to have run into some other problems though that seem to be unrelated to this, if i cant figure out how to fix them i may make another github issue (I know i have been asking a lot of questions about compiling godot, thank you all for your help and willingness to answer all my question and help me with the problems im having)

**Comment by The-Sapphire-Starship** [comment]
@akien-mga I wasnt sure if this was worth its own issue or not, if it is just let me know andd i will create a separate issue for this.

It appears that ```main/default_controller_mappings.h'``` is not able to be found:
![image](https://user-images.githubusercontent.com/75915540/126321333-725ede23-a37b-48dc-9fee-55fe4978cc68.png)

**Comment by akien-mga** [comment]
That's a file from the `3.x` branch. You can't compile the `3.x` branch and the `master` branch from the same Git clone (or you should clean up artifacts with `git clean -fxd`).

**Comment by The-Sapphire-Starship** [comment]
Okay, that makes sense, its continued on compiling now, thank you again for all your help, im leaning a lot about compiling through doing all this, im even learning some about github, i didnt know that using ```git checkout ...``` did not set everything to the way it should be, i didnt even know about the ```git clean -fxd``` command

**Comment by The-Sapphire-Starship** [comment]
Im running into another issue at the end of compiling
```pi@raspberrypi:~/godot/bin/source $ python3 /usr/bin/scons platform=x11 target=release_debug tools=yes -j4 module_webm_enabled=no LINKFLAGS="-latomic" use_llvm=yes
scons: Reading SConscript files ...
Platform "x11" has been renamed to "linuxbsd" in Godot 4.0. Building for platform "linuxbsd".
Enabling ALSA
Enabling PulseAudio
Enabling D-Bus
Enabling udev support
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.

scons: warning: parallel builds are unsupported by this version of Python;
	ignoring -j or num_jobs option.

File "/usr/bin/scons", line 201, in <module>
scons: Building targets ...
[ 96%] Linking Static Library ==> core/libcore.linuxbsd.opt.tools.32.llvm.a
[100%] progress_finish(["progress_finish"], [])
[100%] Ranlib Library         ==> core/libcore.linuxbsd.opt.tools.32.llvm.a
[100%] Linking Program        ==> bin/godot.linuxbsd.opt.tools.32.llvm
/usr/bin/ld: modules/libmodule_theora.linuxbsd.opt.tools.32.llvm.a(video_stream_theora.linuxbsd.opt.tools.32.llvm.o): in function `VideoStreamPlaybackTheora::clear()':
/home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:124: undefined reference to `vorbis_block_clear'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:125: undefined reference to `vorbis_dsp_clear'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:127: undefined reference to `vorbis_comment_clear'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:128: undefined reference to `vorbis_info_clear'
/usr/bin/ld: modules/libmodule_theora.linuxbsd.opt.tools.32.llvm.a(video_stream_theora.linuxbsd.opt.tools.32.llvm.o): in function `VideoStreamPlaybackTheora::set_file(String const&)':
/home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:189: undefined reference to `vorbis_info_init'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:190: undefined reference to `vorbis_comment_init'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:230: undefined reference to `vorbis_synthesis_headerin'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:233: undefined reference to `vorbis_info_clear'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:234: undefined reference to `vorbis_comment_clear'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:236: undefined reference to `vorbis_info_init'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:237: undefined reference to `vorbis_comment_init'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:278: undefined reference to `vorbis_synthesis_headerin'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:350: undefined reference to `vorbis_synthesis_init'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:351: undefined reference to `vorbis_block_init'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:355: undefined reference to `vorbis_info_clear'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:356: undefined reference to `vorbis_comment_clear'
/usr/bin/ld: modules/libmodule_theora.linuxbsd.opt.tools.32.llvm.a(video_stream_theora.linuxbsd.opt.tools.32.llvm.o): in function `VideoStreamPlaybackTheora::update(float)':
/home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:440: undefined reference to `vorbis_synthesis_read'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:411: undefined reference to `vorbis_synthesis_pcmout'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:447: undefined reference to `vorbis_synthesis'
/usr/bin/ld: /home/pi/godot/bin/source/modules/theora/video_stream_theora.cpp:448: undefined reference to `vorbis_synthesis_blockin'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.linuxbsd.opt.tools.32.llvm] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:05:00.257]
```

**Comment by Calinou** [comment]
@The-Sapphire-Starship Pass `module_theora_enabled=no `module_webm_enabled=no` to the SCons command line when compiling.

**Comment by The-Sapphire-Starship** [comment]
Thank you all for all your help with all my compiling problems (both now and in the past)
This command compiled godot 4 successful: ```python3 /usr/bin/scons platform=x11 target=release_debug tools=yes -j4 module_webm_enabled=no LINKFLAGS="-latomic" use_llvm=yes```
![image](https://user-images.githubusercontent.com/75915540/126410407-707d0b6d-8d35-433d-b8b3-255a854b7d0e.png)
It did take a bit to load (the first time at least, it might load a bit faster when ever i load it again) but it did load!
The UI is looking really nice so far, and i havent even gotten past the project screen yet, looking forward to seeing everything else that has been done so far!
