### ISSUE TITLE
Per-pixel transparency missing in Godot 4.0/master

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#50626]
### Godot version

4.0.dev ( 6173271)

### System information

None

### Issue description

It seems per-pixel transparency was temporarily removed with the renderer rework/move to Vulkan.

Parts of it remain, like the Viewport setting, and commented out code with `reenable later`.

Couldn't find a issue for tracking this :)

### Steps to reproduce

None

### Minimal reproduction project

None

**Comment by Calinou** [comment]
Transparent viewports are also not supported yet in the Vulkan renderer – this needs to be fixed first.
