### ISSUE TITLE
SkeletonIK root -> tip parenting error

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#50634]
### Godot version

3.3.2.stable.mono.official

### System information

Windows 10

### Issue description

With a mixamo rig i want to ise IK to position right and left hand. Right hand work as aspected, i set as root node the right Arm and as tip Right hand, all work as aspected. For left arm is not working, if you set left arm as root and left hand as tip you will get the following error: 
`E 0:00:01.504   build_chain: Condition "p_task->root_bone >= ee->tip_bone" is true. Returned: false
  <Sorgente C++>scene/animation/skeleton_ik.cpp:79 @ build_chain()`
![immagine](https://user-images.githubusercontent.com/16955149/126282693-58ff56d0-a85c-411d-a3cc-073b8a9eccaa.png)
![immagine](https://user-images.githubusercontent.com/16955149/126282761-1a542e24-9e5a-4ae3-b1ab-a1c983b18a15.png)

### Steps to reproduce

In a mixamo rig with 3 fingers create an IK node, user Left Arm as root bone and Left Hand as tip node.
For right arm all work as aspected.

**Comment by aaronfranke** [comment]
Does this occur in Godot 4.x, such as Godot 4.3 stable?

Please attach a minimal reproduction project, or else the problem cannot be tested and the issue will be closed.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
