### ISSUE TITLE
Change CodeText Size on the fly.

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#5063]
Changing the script size on the fly would be cool for creating tutorials. People are complaining they cannot follow the code very well because it is to small.
Could be a cool addition to change the font size with for example ctrl+mousewheel. That way you can quickly adjust the code font size without the need to restart the editor.

**Comment by neikeq** [comment]
I did it in a local branch and it was working fine, but discussing it with @reduz he said it could give problems with DynamicFont. I think he mentioned something like the right way to do it would be modifying the DynamicFontData.

**Comment by Paulb23** [comment]
Duplicate of #4183

**Comment by akien-mga** [comment]
Fixed by #5259.
