### ISSUE TITLE
AnimationTree function call track loop

### ISSUE THREAD

**Issue by robbeman** [godotengine/godot#50636]
### Godot version

3.3.2

### System information

macOS Catalina (10.15.7)

### Issue description

When calling a function from an AnimationPlayer activated by an AnimationTree a loop is triggered in some cases.

- When a frame takes too long to process.
- When the call method keyframe is at the very end of the track.

### Steps to reproduce

1. Create AnimationPlayer instance
    - add function call track
    - add function call keyframe (at the end time of the track)
2. Create AnimationTree instance
    - link animation player to tree
    - create AnimationNodeBlendTree as root
    - add animation node and connect it to output
3. `print_debug` in the called function and behold!

When adding the call method somewhere in the middle of the animation a breakpoint can also trigger this loop. In some exports with slower performance this can also occur when a frame takes too long to process.

### Minimal reproduction project

[GodotAnimationPlayerFunctionCallLoop.zip](https://github.com/godotengine/godot/files/6846709/GodotAnimationPlayerFunctionCallLoop.zip)

**Comment by lygamac** [comment]
Same problem when using state machines. But It seems that this bug only triggers when the `switch mode` is set to `Immediate` (with long xfade time). But it didn't triggred when set to `AtEnd`.
