### ISSUE TITLE
Failed silently when using slash in item type/name of Theme

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#50645]
### Godot version

3.3.2, 3.x(028bf846a8), master(1117c2c9f2)

### System information

macOS 11.4

### Issue description

There are no argument validation in `Theme` APIs.

One may use slashes in type/name for organization reasons (the Inspector will add corresponding sections). But there will be unexpected results after save & load:

```gdscript
extends SceneTree

const SAVE_PATH = "user://test_theme.tres"


func _init():
	var theme = Theme.new()

	theme.set_constant("foo", "Widget", 42)
	theme.set_constant("foo", "Widget/bar", 42)
	theme.set_constant("foo", "Widget/constants", 42)
	theme.set_constant("foo/bar", "Widget", 42)

	print("=== In memory ===")
        # This is for 4.0, will need to dump get_property_list for 3.x
	for node_type in theme.get_type_list():
		for name in theme.get_constant_list(node_type):
			printt(node_type, name, theme.get_constant(name, node_type))

	ResourceSaver.save(SAVE_PATH, theme)
	theme = ResourceLoader.load(SAVE_PATH)

	print("=== After save & load ===")
        # This is for 4.0, will need to dump get_property_list for 3.x
	for node_type in theme.get_type_list():
		for name in theme.get_constant_list(node_type):
			printt(node_type, name, theme.get_constant(name, node_type))

	quit()
```

executing the script will not emit errors, and will print something like:

```
=== In memory ===
Widget/constants    foo     42
Widget/bar          foo     42
Widget              foo     42
Widget              foo/bar 42
=== After save & load ===
Widget  foo         42
Widget  constants   0
```

Some entries are missing, and some are parsed into wrong values. So this is definitely a bug.

Either the way of parsing `Theme` resource should be changed, or slashes should be invalid for item type/name. If we don't allow slashes, I suggest reconsidering whether an empty item type/name should be allowed.

### Steps to reproduce

Run the snippet above with `/path/to/godot --no-window --script /path/to/snippet.gd`.

**Comment by pycbouh** [comment]
Qualified type and property names should probably be limited to alphanumeric values and an underscore, with no spaces and always starting with a letter.

An empty name for the theme type should be fine, as it doesn't introduce issues with serialization and can be used for some global theme definitions (though there is a downside that its impossible to fetch its items via `Control`'s `get_theme_*` methods due to how empty values are treated there, so you need a reference to the theme itself).

**Comment by timothyqiu** [comment]
I just found that there are editor icons named `2D.svg` and `3D.svg`, they will be added to the editor theme on `EditorIcons` by the name `2D` and `3D`. So the item name may start with a number?

**Comment by pycbouh** [comment]
Numbers are usually avoided at the start of identifiers to prevent collisions with various numeric notations. But I guess we can be lax here as we use strings anyway.

But it's not just slashes, so I would still go for a whitelist approach instead of a blacklist.

**Comment by KoBeWi** [comment]
Still valid in f0407ad
I experimented a bit and seems like only slashes are problematic. Other symbols are fine.

We should likely resolve this before beta, as forbidding slashes in names technically breaks compatibility.
