### ISSUE TITLE
want to use resources wav avi bmp

### ISSUE THREAD

**Issue by eaglecat** [godotengine/godot#5064]
my game uses external resources that may contain wav, avi, bmp files.

so I wish godot can use resources *.wav *.avi *.bmp on running.

**Comment by SuperUserNameMan** [comment]
@eaglecat  :

for BMP files, maybe you could write your own loader in Gdscript and create the Image() or ImageTexture() you need ?

same thing with WAV files from which you could create Sample() ressources ?

**Comment by eaglecat** [comment]
@reduz I can load .wav to SampleLibrary in editor, but not easy to do that on running.
@SuperUserNameMan I'm trying to do that , but It's hard for me now..

I'm working on music game. there are huge amount of external resources that may contain .bmp .wav.
preconverting them all won't solve the problem because new resources can be added after the project is published.

**Comment by akien-mga** [comment]
As mentioned above, .wav works already and there is no intention to try to support .avi (whatever .avi means, we would have to support hundreds of video codecs to support the avi container). As for .bmp, nobody should use this format in the 21st century :)
