### ISSUE TITLE
Adding items to Tree node not working

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50652]
### Godot version

v4.0.dev.custom_build [bb037de95]

### System information

Windows 10

### Issue description

For some reason trees aren't working at all for me. I copied the example code from https://docs.godotengine.org/en/stable/classes/class_tree.html
```gdscript
extends Control
func _ready():
    var tree = Tree.new()
    tree.set_column_titles_visible(true)
    tree.set_column_title(0, "Test")

    var root = tree.create_item()
    tree.set_hide_root(true)
    var child1 = tree.create_item(root)
    var _child2 = tree.create_item(root)
    var subchild1 = tree.create_item(child1)
    subchild1.set_text(0, "Subchild1")

    add_child(tree)
```
However, for some reason the created tree items don't appear, only the column titles appear.
![image](https://user-images.githubusercontent.com/12120644/126373183-23cf30a7-c654-4647-9bdd-51a05a5755dd.png)

Also: I tested this in 3.3.2 stable, and **nothing** appears, not even the column title, which is even more confusing

### Steps to reproduce

- Write a script that creates a tree
- Call create_item() on the tree
- None of the created items will appear

### Minimal reproduction project

[TreeTesting.zip](https://github.com/godotengine/godot/files/6850373/TreeTesting.zip)

**Comment by pycbouh** [comment]
Your tree has no size.

**Comment by foxydevloper** [comment]
> Your tree has no size.

Right, thanks, I blame the docs, probably should have a clarification in there

**Comment by pycbouh** [comment]
Not sure what can be clarified by the docs. All Controls have to have a size. Some assume some minimal size based on whatever property makes sense to them, but for a Tree it is harder to assume.

**Comment by foxydevloper** [comment]
> Not sure what can be clarified by the docs. All Controls have to have a size. Some assume some minimal size based on whatever property makes sense to them, but for a Tree it is harder to assume.

Yeah I edited that out of my comment, I had a bit of a stupid moment and forgot how controls work lol
