### ISSUE TITLE
Project exported on an M1 Mac ran on a Intel Mac is corrupted.

### ISSUE THREAD

**Issue by SirBuildsALot** [godotengine/godot#50666]
### Godot version

3.3.2

### System information

MacOS, M1 Mac, GLSE3 and MacOS, 2.7 GHz Dual-Core Intel Core i5, MacBook Pro Early 2015, GLES3

### Issue description

When a Godot project is export on a M1 or Intel Mac, if it’s ran on the opposite architecture, it’s display a message saying “”ProjectName” is damaged and can’t be opened”.

<img width="372" alt="Screen Shot 2021-07-20 at 3 40 44 PM" src="https://user-images.githubusercontent.com/43504019/126392673-dc1ce28a-a38a-4064-85b4-11c8bea4c42c.png">

### Steps to reproduce

Export a Godot project on any Mac, then run that project on x86 if it’s exported on a M1 Mac and M1 if it’s from a Intel Mac.

**Comment by akien-mga** [comment]
That's expected of any Mac application if you did not sign and notarize it.

If it's downloaded from the Internet, macOS will put it in quarantine and report it as damaged. See upcoming documentation about this (but it's not Godot-specific, it's the same for all macOS applications): https://github.com/bruvzg/godot-docs/blob/mac_export_and_run/tutorials/export/running_on_mac.rst

**Comment by SirBuildsALot** [comment]
The documentation says if it’s exported from Linux or Windows, but the project is exported from MacOS. Does that make a difference or is that just a mistake in the documentation?

**Comment by akien-mga** [comment]
> The documentation says if it’s exported from Linux or Windows, but the project is exported from MacOS. Does that make a difference or is that just a mistake in the documentation?

CC @bruvzg

**Comment by bruvzg** [comment]
> The documentation says if it’s exported from Linux or Windows, but the project is exported from MacOS. Does that make a difference or is that just a mistake in the documentation?

It does not meter from what OS it is exported, as long as it's not signed, macOS is going to report it as damaged.
- On Windows and Linux you can't sign macOS app.
- On macOS you can and have no reasons not to (to use ad-hoc signature select "codesign/enabled" checkbox in the export options, the only requirement is installed Xcode).

**Comment by SirBuildsALot** [comment]
Well that’s odd? I have the latest version of Xcode installed, but I can’t seem to get it to run on a Mac on the opposite architecture. Like I can get the app to run on another M1 Mac, or if I export on Intel I can get it to ran on another Intel Mac, I just can’t get the apps to run between any of them.

**Comment by SirBuildsALot** [comment]
Never mind, after some more testing I found out some Xcode files got misplaced, so everything is working great on the Godot side of thing.
