### ISSUE TITLE
Creating inherited script & opening it causes editor to freeze

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50681]
### Godot version

v4.0.dev.custom_build [e248d2629]

### System information

Window 10

### Issue description

Creating a script that inherits from another script and then opening it will cause the editor to freeze. This happens when attaching a script, and when creating it in the filesystem dock and opening it.

Reloading the project will cause the inherited scripts to not cause the editor to freeze anymore, it only happens when opening inherited scripts that were newly created.

### Steps to reproduce

- Create a script to inherit from
- Press "Create Script" in filesystem dock
- Change what the new script will inherit from to another script
- Create the script
- Now open the script in the filesystem dock
- The editor will freeze

OR:

- Create a script to inherit from
- Create a blank scene with a Node
- Press attach script on the node
- Change what the new script will inherit from to another script
- Create the script
- The editor will freeze

**Comment by Blackiris** [comment]
Indeed, the infinite loop happens here:

https://github.com/godotengine/godot/blob/9d9161c71956201875334b6a2a9ca37a7d5d3970/modules/gdscript/gdscript.cpp#L1773-L1780

`I` is always getting himself...
