### ISSUE TITLE
Signal connection dialog markup broken

### ISSUE THREAD

**Issue by jjay** [godotengine/godot#5068]
**Operating system or device - Godot version:**
Macbook Pro with retina, OSX 10.11.5, Godot 955ed0a 

**Issue description** (what happened, and what was expected):
Labels not aligned with UI elements.
<img width="960" alt="2016-06-06 16 29 47" src="https://cloud.githubusercontent.com/assets/122736/15823590/0a22ea26-2c04-11e6-8074-3630bab4f8df.png">
**Steps to reproduce**
- Create new scene. 
- Create new node
- Select signal in the signals dock
- Press "Connect"

**Comment by reduz** [comment]
oh I see, this is an old dialog that didnt't use containers, so it has
problems scaling with retina

**Comment by TheHX** [comment]
This wasn't fixed in e88e0607f8f9eac59d155c23490094159fde865b?

**Comment by akien-mga** [comment]
It likely was. Don't hesitate to ask us to reopen if it's not the case.

**Comment by vnen** [comment]
The issue number was mistyped in the commit :laughing:
