### ISSUE TITLE
Starting a thread from GDScript always require non-null data to be passed

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#50692]
### Godot version

3.x build 51f8247871c84736a3c3f56375deb432a4cb305a

### System information

OS: Arch Linux, CPU: Ryzen 5, GUP: RX 480

### Issue description

When calling Thread.start() with null data the thread doesn't start and this error is reported:

```
ERROR: Could not call function 'thread_run' to start thread 5559469359093562243: Too Few Arguments.
   at: _start_func (core/bind/core_bind.cpp:2604)
```

It used to be possible to not specify the user data parameter and have that default to `null`.
Forcing the user to pass in some non-null data seems unnecessary.

### Steps to reproduce

- Create a scene with a single node and a script for the node.
- Create a thread in the "_ready" method and start it by calling a function on the same script and specifying no data:
```
var my_thread: Thread = Thread.new()

func thread_run(_data) -> void:
  pass
  
func _ready():
  my_thread.start(self, "thread_run")
```

**Comment by akien-mga** [comment]
Likely a regression from #38078, CC @Faymoon @RandomShaper.

**Comment by akien-mga** [comment]
I'm not sure that's a bug though, this might just be the consequence of the bugfix.

If there's a parameter without a default value, it must be passed.

**Comment by m4nu3lf** [comment]
There is `null` default value defined in the start method as userdata, I would expect that to be used if no data is specified.

```
start(instance: Object, method: String, userdata: Variant = null, priority: Priority = 1)
```

I understand it can work that way too, but it is a bit surprising to me.

Also no `null`s are allowed unless the target function specifies a default null value too.
