### ISSUE TITLE
AnimatedSprite3D doesn't recognize its frames

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#5069]
**OS, GPU, Version** 
Linux 4.5.2 x86_64 01:00.0 
VGA compatible controller: NVIDIA Corporation GK106 [GeForce GTX 645 OEM] (rev a1)
"Nouveau" driver
Godot 955ed0a95f61e14e6c941540b11905a16fb40d00

**Issue description** 
The AnimatedSprite3D doesn't recognize its frames.
No frame is displayed in editor and when running it in editor.
Git bisect hints that it might also be the case for AnimatedSprite(2D) but I haven't tested it yet.

**Steps to reproduce:**
Start the editor
Create a new AnimatedSprite3D
Load frames into the AnimatedSprite3D
-> Nothing is displayed in editor, current frame can't be changed.

**Git bisect**

bed3efb17ede58a2bfc177b47cb3a49091aea30a is the first bad commit
commit bed3efb17ede58a2bfc177b47cb3a49091aea30a
Author: Juan Linietsky <reduzio@gmail.com>
Date:   Sat May 14 23:48:23 2016 -0300

    New reworked AnimatedSprite!
    
    -New SpriteFrames editor, with support for drag&drop, multiple animation
    sets, animation speed and loop.
    -New AnimatedSprite, with support for all the new features!
    AnimatedSprite3D has not been updated yet.
    -Added support for drag&drop to other editors, such as resourcepreload,
    sample library,  etc.

:040000 040000 b8d114f68dc950ce5be1aad466045cf340d864bb 25fbee4d647fdc6b7815b993321da88d1da19e33 M	core
:040000 040000 66f4fb20db05558f21096625d351686d6abc8a51 77c244cadb797700560b1cfc0bb7c335c462a295 M	scene
:040000 040000 a32769a8f4611647b70d49d7b58f01aa36b9f388 e8a86a905bd279acddaea51be7989872b232f418 M	tools

**Comment by akien-mga** [comment]
Thanks for looking into this, this issue will be a good reminder that AnimatedSprite3D still needs to be reworked to match the new system.

**Comment by reduz** [comment]
ah yes, working on this, didn't want to port the code from AnimatedSprite
until users were fine with the implementation. I think it's probably just
good enough, so AnimatedSprite3D will be fixed soon

**Comment by trollworkout** [comment]
This commit it completely crashing my Godot build on OSX.

**Comment by reduz** [comment]
seems to work for me, please make an example project that fails

**Comment by jmf** [comment]
It works again in the latest git. There has been a push concerning AnimatedSprite, that was probably the fix.
