### ISSUE TITLE
Collada Importing Problem

### ISSUE THREAD

**Issue by mamarilmanson** [godotengine/godot#507]
![1](https://cloud.githubusercontent.com/assets/3820189/3253293/73f10198-f1d4-11e3-9ba5-d9fdcee2b867.jpg)
Here's another issue... 
![3](https://cloud.githubusercontent.com/assets/3820189/3253296/7400a1f2-f1d4-11e3-8544-ff4b06d6aee8.jpg)
![4](https://cloud.githubusercontent.com/assets/3820189/3253297/74015070-f1d4-11e3-98d8-40dd7cae0927.jpg)
![5](https://cloud.githubusercontent.com/assets/3820189/3253295/73ffafea-f1d4-11e3-9ea8-56cfb366194e.jpg)

**Comment by mamarilmanson** [comment]
hi... the issue with different directories is not yet fixed... thanks... :)

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment]
Ping.

**Comment by set-killer** [comment]
@akien-mga this issue is closed with [this commit](https://github.com/godotengine/collada-exporter/commit/90d2752287ebe0719c96ce86abfe13b20d0d0bc1).

**Comment by akien-mga** [comment]
Great, thanks.
