### ISSUE TITLE
[help] .pck file not found

### ISSUE THREAD

**Issue by chibbi** [godotengine/godot#50708]
### Godot version

3.4.beta

### System information

POP_OS, GLES 2/3, GTX 960 (nvidia-driver-470), ryzen 1600

### Issue description

ERROR: Pack version unsupported: 1.
   at: try_open_pack (core/io/file_access_pack.cpp:176)
ERROR: Pack version unsupported: 1.
   at: try_open_pack (core/io/file_access_pack.cpp:176)
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension)
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7f8271ef5950] (??:0)
[2] ./VoxelDemo.x86_64() [0x71b3b7] (/home/chibbi/Downloads/godot/main/main.cpp:1083)
[3] ./VoxelDemo.x86_64() [0x6e25e1] (/home/chibbi/Downloads/godot/platform/linuxbsd/godot_linuxbsd.cpp:52)
[4] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2) [0x7f8271edccb2] (??:0)
[5] ./VoxelDemo.x86_64() [0x6e9b6e] (??:?)
-- END OF BACKTRACE --
Aborted (core dumped)

### Steps to reproduce

I dunno
I guess:
1. use [godot 3.4.beta version from voxel_plugin](https://github.com/Zylann/godot_voxel/actions/runs/1046347343)
2. use this as a project: https://github.com/Zylann/voxelgame (commit: 0690648ff180f710dd8abff54f4c9a9c5b2e1789)
3. use official godot 3.4.beta (commit: 286e9b853315343c8ddc121098e412af812b3495) to create your export templates (for linux)

**Comment by akien-mga** [comment]
> ./VoxelDemo.x86_64() [0x6e25e1] (/home/chibbi/Downloads/godot/platform/linuxbsd/godot_linuxbsd.cpp:52)

That's Godot 4 (master branch), not 3.4.

**Comment by chibbi** [comment]
what, but i looked into the "about Godot" inside the program, and there is: "Godot Engine v3.4.beta.custom_build [526447b86]".

**Comment by akien-mga** [comment]
You probably have two different binaries, but this `VoxelDemo.x86_64` one (i.e. your export template) was built from the `master` branch (`linuxbsd` is the name in `master`, in `3.x` it's still `x11`).

**Comment by chibbi** [comment]
Where do i find the 3.4.beta source? (so i can build the right export templates) xd

**Comment by chibbi** [comment]
ah found it thx

**Comment by Calinou** [comment]
> ERROR: Pack version unsupported: 1.
at: try_open_pack (core/io/file_access_pack.cpp:176)

This should probably display a visible alert with `OS::alert()` when it's the main pack.
