### ISSUE TITLE
Editor's select node popup doesn't work correctly

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#50719]
### Godot version

4.0.dev 88bf6e1c6d3e711976304bb16ac51719e8e82f72

### System information

MacOS 11.4, Windows 10

### Issue description

The operation to change the parent or add an animation track brings up a popup to select Node, but After selecting, it doesn't work correctly.

https://user-images.githubusercontent.com/61938263/126573423-06b15c1a-a72b-4957-bc76-3f42defe17c1.mov

### Steps to reproduce

Try to operate "Change Parent Node" or "Add Animation Track".

**Comment by Calinou** [comment]
@TokageItLab Can you reproduce this in 3.3.2 or the latest `3.x` branch?

**Comment by TokageItLab** [comment]
@Calinou No, it's only 4.0, it was fine before, but it was broken in some recent commit.

**Comment by TokageItLab** [comment]
@Calinou Oh, I'm sorry. I checked it properly and it's fine in 3.3.2, but broken in the latest 3.x. I used to be able to double click to decide on an item, but now not.

**Comment by Calinou** [comment]
> Oh, I'm sorry. I checked it properly and it's fine in 3.3.2, but broken in the latest 3.x just like in 4.0. And by the way, it used to be able to double click to decide on an item, but now not.

This may be a regression from https://github.com/godotengine/godot/pull/49310. Can you [bisect the regression](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html) to make sure?

**Comment by TokageItLab** [comment]
@Calinou Okay, I'll do that, should I do it in the 4.0 branch?

**Comment by TokageItLab** [comment]
@Calinou I finished search regression with bisect. The regression is caused by 7d20d78847b24586b3f25beb23b41d015a25fb0a.
