### ISSUE TITLE
Moving elements in the editor's tree with drag-and-drop is broken

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#50720]
### Godot version

4.0.dev (88bf6e1c6d3e711976304bb16ac51719e8e82f72)

### System information

MacOS 11.4

### Issue description

Dragging and dropping an element in the Editor tree does not move it correctly. The problem occurs both in Explorer and in the scene tree.

### Steps to reproduce

Try to move elements in the tree by dragging and dropping them.

**Comment by SirQuartz** [comment]
You're going to need to explain this a little better or provide a minimum reproduction project because I'm using 4.0 dev right now and not noticing any problems with moving elements within the scene tree.

**Comment by TokageItLab** [comment]
@SirQuartz For example, in this video, I expect the operation to put the CollisionShape into a child of the StaticBody, but it does not.

https://user-images.githubusercontent.com/61938263/126572887-fb5fedfe-7b76-407c-9adc-20317acb5642.mov

[tree.zip](https://github.com/godotengine/godot/files/6859262/tree.zip)

**Comment by SirQuartz** [comment]
That's very odd behavior on your end for some reason, because I just tested this exactly and didn't run into any problems, it behaved exactly as expected.


https://user-images.githubusercontent.com/62965063/126573409-6ec74d58-8fbf-41e5-b6e7-4c2ac9534c51.mp4

**Comment by TokageItLab** [comment]
It may have been broken in a commit somewhere, and it was certainly working correctly before.

**Comment by SirQuartz** [comment]
v4.0.dev (286e9b853)

I just compiled the engine within the last hour, try compiling again to a newer version, and see if that helps for some reason. Don't know why it would, but you never know.

**Comment by TokageItLab** [comment]
I tried the latest commit (a4c863791e407014ebdc58b980dd14eacbf8c550), but it was still broken. Also, trying to change the language to English did not improve the problem.

**Comment by SirQuartz** [comment]
I was just about to suggest that this might be a macOS specific problem, as I'm currently running Window 10 Home. Either way, it's definitely very strange.

**Comment by Calinou** [comment]
@TokageItLab Can you reproduce this if **Single Window Mode** is enabled in the Editor Settings?

**Comment by akien-mga** [comment]
Might be a HiDPI issue? Maybe the offsets for drag and drop are visually correct but internally wrong so it ends up on the wrong target.

**Comment by TokageItLab** [comment]
When I change the DisplayScale, these cannot be moved and no longer work.
It seems likely that there is some kind of problem around HiDpi mode.

**Comment by Calinou** [comment]
It seems the editor's display scale is not applied to *some* non-main windows such as popups (and in running project, it won't apply to any subwindows if you use a stretch mode other than `disabled`).

**Comment by foxydevloper** [comment]
I'm on Windows 10, I run into this issue often as well. When opening a project it has like a 50% chance of happening, I can't seem to figure out how exactly to reproduce it other than opening projects over and over until it happens. It fixes when I resize my window though.

When it occurs, it prevents me from dragging nodes around in the scene tree:

https://user-images.githubusercontent.com/12120644/126705261-f8564535-8428-4d2c-86ab-3a7010a0aacd.mp4

It also prevents me from dragging files into properties in the inspector, and prevents me from dragging images into the viewport to turn them into sprites.

https://user-images.githubusercontent.com/12120644/126705256-c73ba60c-ffaa-4fb4-8bcd-70a93ff29c29.mp4

Making my window smaller and then maximizing it again fixes the issue completely though, but it happens again after opening up another project 50% of the time.

**Comment by danger-dan** [comment]
Can confirm I have also just run into this issue with Windows 10 Desktop display scale of 175%. Also very likely related - when editing names/numbers (text input) a second text edit appears offset from the original input location. I can create a separate issue with screenshots - if desired - after work.

**Comment by KoBeWi** [comment]
Might be the same issue as #38312

**Comment by KoBeWi** [comment]
Is this still reproducible in alpha 8?

**Comment by TokageItLab** [comment]
Fixed!
