### ISSUE TITLE
Display visible alert and abort early when loading a PCK with mismatched version (DisplayServer regression)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#50727]
### Godot version

4.0.dev (8747f2565)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

Currently, this happens when running a `3.x` PCK using the `master` branch (quoting from https://github.com/godotengine/godot/issues/50708):

```
ERROR: Pack version unsupported: 1.
   at: try_open_pack (core/io/file_access_pack.cpp:176)
ERROR: Pack version unsupported: 1.
   at: try_open_pack (core/io/file_access_pack.cpp:176)
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension)
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7f8271ef5950] (??:0)
[2] ./VoxelDemo.x86_64() [0x71b3b7] (/home/chibbi/Downloads/godot/main/main.cpp:1083)
[3] ./VoxelDemo.x86_64() [0x6e25e1] (/home/chibbi/Downloads/godot/platform/linuxbsd/godot_linuxbsd.cpp:52)
[4] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2) [0x7f8271edccb2] (??:0)
[5] ./VoxelDemo.x86_64() [0x6e9b6e] (??:?)
-- END OF BACKTRACE --
Aborted (core dumped)
```

We should this kind of crash and display an user-visible dialog using `OS::alert()`, so that the user is informed even if they run the project without going through a terminal.

The alert message should display in particular that the PCK version doesn't match the engine version (either newer or older).

### Steps to reproduce

Export a project using 3.3.2 and try to run it with a `master` editor or export template using the `--main-pack /path/to/file.pck` command line argument.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
> The alert message should display in particular that the PCK version doesn't match the engine version (either newer or older).

That's exactly what Godot is trying to do, the crash is caused by `DisplayServer::get_singleton()->alert(error_msg);` call, since `DisplayServer` is not initialized at this moment.

**Comment by bruvzg** [comment]
Might be worth moving `alert` back to the `OS`, on Linux it's using an external app (`zenity`, `xmessage`, etc.) and on macOS / Windows it's not interacting with the rest of `DisplayServer` in any meaningful way and do not require anything to be initialized.
