### ISSUE TITLE
"Project is missing"  is printed twice for every missing project

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#50739]
### Godot version

3.3.2

### System information

Windows 10

### Issue description

If I have a missing project, it gets reported twice like so:
```
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 4400
OpenGL ES Batching: ON

Project is missing: [...]/ProjectFolder/project.godot
Scanning projects at: [...]
Found 28 projects.
Project is missing: [...]/ProjectFolder/project.godot
```

I haven't thoroughly investigated, but line that prints the error message is [here](https://github.com/godotengine/godot/blob/master/editor/project_manager.cpp#L1203).
### Steps to reproduce

1. Toggle system console on
2. Move/delete an empty project that's registered in the project manager
3. Open project manager

**Comment by LightningAA** [comment]
Could not reproduce on `master` (bf153b82c73755bf898df9de33ac2116ebe914b9)

**Comment by akien-mga** [comment]
I don't think that's a bug, what happens is:
- You open the project manager, it parses the config and reports that one project is missing.
- Then you used "Scan", which makes it find new project, save a new config, and reload it
- When reloading the config, it reports the missing project again

IMO that's not an issue and not worth working around.
