### ISSUE TITLE
Keep screen on not implemented on desktop platforms (to inhibit screensaver)

### ISSUE THREAD

**Issue by ramoas86** [godotengine/godot#5073]
**Operating system or device - Godot version:**
Ubuntu 14.04 and probably other Linux system.

**Issue description** (what happened, and what was expected):
Screensaver appears when using joystick during gameplay. I want avoid this.

**Comment by reduz** [comment]
maybe we should implement this during game (not editor) execution

http://stackoverflow.com/questions/31498114/how-to-programatically-prevent-linux-computer-from-sleeping-or-turning-on-screen

**Comment by Hinsbart** [comment]
Good idea. 
On this occation, we should also make `"display/keep_screen_on"` available on desktop platforms I guess.

**Comment by vnen** [comment]
I noticed there's a [`OS.set_keep_screen_on(bool)`](http://docs.godotengine.org/en/latest/classes/class_os.html#class-os-set-keep-screen-on) that seems to only work on mobile. Maybe the same function can be used for desktops?

**Comment by Hinsbart** [comment]
I tried to implement this and noticed that on windows, the screensaver never appears when the godot editor is open. Can somebody confirm this? Should it be regarded as a bug?

**Comment by bitbionic** [comment]
Just to put a little life back into this, just in case it's buried in the priority stack - this is still an issue (and an old one it seems). While the workaround for the user is simple (turn off screensaver / sleep options) it should be addressed IMO.

**Comment by Calinou** [comment]
**Bugsquad note:** This issue is still relevant as of commit https://github.com/godotengine/godot/commit/d87307d850186d27d2c27c5916ec8c4744c14979; `OS.set_keep_screen_on(bool)` is only implemented on Android, iOS and UWP.

**Comment by KoBeWi** [comment]
As of ffbea8a, the method is still not implemented for desktop.

However, XBox gamepad will prevent screensaver on Windows 10 even without game running, so maybe someone could test with other systems/gamepads (not to mention the bug could be fixed in another way).

Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

**Comment by tragiccommons** [comment]
I am using 3.2.2.stable.official on Linux Mint 20 and I am having this issue.
I am using a USB gamepad. The game and gamepad are functioning well, but the screen saver still turns on despite constant input from the gamepad.

**Comment by Calinou** [comment]
See how SDL 2 disables the screen saver on Linux: https://github.com/SDL-mirror/SDL/blob/dd496badc90f9b83ba1787abde26ef49d240108c/src/video/x11/SDL_x11events.c#L1479-L1512

Interesting to note is that SDL also disables the screensaver by default: https://github.com/SDL-mirror/SDL/blob/dd496badc90f9b83ba1787abde26ef49d240108c/src/video/SDL_video.c#L546-L554

**Comment by akien-mga** [comment]
> This will be fixed by #35536 if it's merged.

That PR fixes it for Linux, but AFAICT "Keep Screen On" is still not implemented for Windows (empty stubs) and macOS (no stubs) either.
