### ISSUE TITLE
Godot 4.0 "Unable to initialize Video driver" on macOS (problem with MoltenVK packaging)

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot#50730]
### Godot version

Calinou Nightly build 5710adda7

### System information

Macbook Pro 2019 16", AMD Radeon Pro 5500M, Big Sur 11.4

### Issue description

I'm testing the exporting of the pre-alpha nightly builds and after downloading the export templates and just letting them run with standard options on MacOS, all i get from the exported app when it starts is this.

![image](https://user-images.githubusercontent.com/27105009/126623913-34c0fe34-4000-45e4-9c27-1c878e71a4da.png)

My system info is telling me that I have the ability to use Metal, but I don't know what Godot is expecting:
![image](https://user-images.githubusercontent.com/27105009/126624271-fa4fceb9-763a-4ce4-ab9f-ff6b8951be15.png)

![image](https://user-images.githubusercontent.com/27105009/126624185-f9fa2e7a-6c7a-4d05-b895-6b0fe0689484.png)

Also tested creating a Windows Desktop exporter and the exported app didn't even start on my surface pro 🤷🏼‍♂️

### Steps to reproduce

download export templates from calinou nightly build site.
load them.
export.

**Comment by akien-mga** [comment]
Does the `.app` include the MoltenVK `dylib`?

**Comment by bruvzg** [comment]
Most likely, `MoltenVK` library is missing from the export template. For testing purpose, you can install Vulkan SDK - https://vulkan.lunarg.com/sdk/home#mac. Or copy `libMoltenVK.dylib` from the SDK to the `osx_template.app/Contents/Frameworks/` folder in the export template zip.

**Comment by MrJoshBowman** [comment]
@bruvzg Oh right, I'll give that a go, thanks!

**Comment by Calinou** [comment]
I didn't bundle MoltenVK in my macOS export templates, so it's not going to work out of the box on macOS yet.

> Also tested creating a Windows Desktop exporter and the exported app didn't even start on my surface pro

What Surface Pro model is it?

**Comment by MrJoshBowman** [comment]
Sorry chaps, it worked this time when i put it in the Frameworks folder, I tried previously but it didn't work, but then i installed the latest VulkanSDK so maybe that had something to do with it... but the exported app now works

**Comment by bruvzg** [comment]
> Nope! Turns out it only works if i have the libMoltenVK.dylib as @bruvzg said AND Disable Library Validation turned on...

`Disable Library Validation` is necessary when library has a different signature (like on from SDK, which is signed by LunarG).

**Comment by akien-mga** [comment]
Apparently I also have a packaging issue for MoltenVK in my first try at making 4.0 dev builds with the official buildsystem: https://twitter.com/fmestevez/status/1420309751368400896

And indeed I seem not to have included MoltenVK yet:
https://github.com/godotengine/godot-build-scripts/blob/62195f98080920b006afe7afd41ef2c454f7eaea/build-release.sh#L214-L237

**Comment by akien-mga** [comment]
As of the latest push on https://github.com/godotengine/godot-build-scripts/pull/38 I should now be linking MoltenVK statically properly for official builds (both editor and template). I'll upload a fixed build for testing soon.

@Calinou will need to do something similar (note also the iOS steps to copy the `MoltenVK.xcframework`) to fix nightly builds.

**Comment by akien-mga** [comment]
I have an updated build here where the macOS editor and export templates should all be linked statically against MoltenVK, so it should work without having to install the Vulkan SDK. Can anyone confirm?

https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20210727/

**Comment by Lykdraft** [comment]
I just dl'd and tested this and this does indeed work on OSX 10.14.6

I also should note that this is the first build in a long time that is starting (and running) successfully on OSX. Hugos nightlies still won't work (black screen...). They didn't since months actually. But this one does.

**Comment by akien-mga** [comment]
@Calinou You should do something similar to https://github.com/godotengine/godot-build-scripts/pull/38 for your builds then:

- Install the Vulkan SDK, or a copy of just the `MoltenVK` folder.
- Build Godot macOS with `use_static_mvk=yes VULKAN_SDK_PATH=path/to/vulkansdk`. `VULKAN_SDK_PATH` should point to the parent folder of the `MoltenVK` folder.
- For iOS templates, copy `MoltenVK.xcframework` in the template:

```
cp -r $VULKAN_SDK_PATH/MoltenVK/MoltenVK.xcframework ios_xcode/
rm -rf ios_xcode/MoltenVK.xcframework/{macos,tvos}*
```

**Comment by Calinou** [comment]
> @Calinou You should do something similar to [godotengine/godot-build-scripts#38](https://github.com/godotengine/godot-build-scripts/pull/38) for your builds then:

I already did this [here](https://github.com/Calinou/godot-builds-ci/commit/bdb933f7091bbc1c80ad6673507c17294f44efca), but it doesn't seem to be working.

**Comment by bruvzg** [comment]
> I already did this here

Vulkan SDK dmg contains an installer with the compressed contents, you can't just mount it and set the path.

**Comment by bruvzg** [comment]
Instead run:
```
sudo /Volumes/vulkansdk-macos-1.2.182.0/InstallVulkan.app/Contents/MacOS/InstallVulkan --root ~/VulkanSDK/1.2.182.0 --accept-licenses --default-answer --confirm-command install
```
and set `$VULKAN_SDK_PATH` to `~/VulkanSDK/1.2.182.0`

**Comment by bruvzg** [comment]
Or extract it manually, if you do not want to use `sudo`:
```
brew install p7zip
7z x /Volumes/vulkansdk-macos-1.2.182.0/InstallVulkan.app/Contents/Resources/installer.dat -o~/VulkanSDK/1.2.182.0
```

**Comment by Calinou** [comment]
This should be fixed for macOS editor, macOS templates and iOS templates since I pushed https://github.com/Calinou/godot-builds-ci/commit/75dc1555500bca34fc6eae1ffb05054829addff1.

**Comment by bruvzg** [comment]
@Calinou It's gonna need another small change to the build command after #51516 is merged: `use_static_mvk=yes` to `use_volk=no`.

**Comment by Calinou** [comment]
> @Calinou It's gonna need another small change to the build command after #51516 is merged: `use_static_mvk=yes` to `use_volk=no`.

Done: https://github.com/Calinou/godot-builds-ci/commit/3945993dba623864ded315689762598ea0a8f3bd
