### ISSUE TITLE
Error `Vulkan: Did not create swapchain successfully` when running project

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50740]
### Godot version

4.0.dev.custom_build. 286e9b853

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When I run project, then in one scene(exactly always in same place), Godot freeze and starts to print a lot of this messages
```
ERROR: Vulkan: Did not create swapchain successfully.
   at: prepare_buffers (drivers/vulkan/vulkan_context.cpp:1780)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:1856)
```

### Steps to reproduce

1. Download Minimal project
2. Run it from terminal(Due to e.g. Autoload bugs, opening from editor doesn't work for now)
3. Go to Benchmark menu
4. Click Start benchmark
5. Wait for 4 map in which environment will be added

![jfile](https://user-images.githubusercontent.com/41945903/126680254-0a9fb7e5-5922-434e-ae11-0766508da4cd.gif)

### Minimal reproduction project

https://github.com/qarmin/Pole-Mrowkowe/archive/refs/heads/4.0.zip

**Comment by sairam4123** [comment]
Can confirm in v4.0.dev.20210811.official.7188cb601. It doesn't let me start the editor.

**Comment by Calinou** [comment]
> Can confirm in v4.0.dev.20210811.official.7188cb601. It doesn't let me start the editor.

Which operating system and graphics card model are you using? Are you using a system with hybrid graphics (NVIDIA Optimus)?

**Comment by sairam4123** [comment]
Windows 10, NVIDIA GeForce GTX 1050, what do you mean by hybrid graphics?

**Comment by Calinou** [comment]
> Well, I have a Intel HD Graphics and NVIDIA GeForce GTX 1050 has my dedicated GPU. So that might be the problem?

This could be due to https://github.com/godotengine/godot/issues/45725.

**Comment by qarmin** [comment]
Looks that this is fixed in master
