### ISSUE TITLE
3.x Setting nodepaths in the inspector is broken

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#50744]
### Godot version
3.4 dev 883bb2f

This is something very recent, probably committed today (22nd July 2021)

### System information
Linux Mint 20

### Issue description
Trying to set a nodepath via the inspector does nothing, the function is not called in the class.

### Steps to reproduce
Try to set a nodepath via the inspector, for any node that has a nodepath property.
Interpolated camera will do, but it also occurs for RoomManager.

### Minimal reproduction project
N/A

Possibly due to #50561?
EDIT: Yes can confirm if I checkout the commit before #50561 it works again.

**Comment by akien-mga** [comment]
Fixed by #50763.
