### ISSUE TITLE
Compiling module in 4.0 dev gives error "fatal error: 'core/reference.h' file not found"

### ISSUE THREAD

**Issue by jimbeauphloyd** [godotengine/godot#50741]
### Godot version

4.0 dev

### System information

Mac OSX 11.1

### Issue description

Compiling godot from source with a custom module gives error "fatal error: 'core/reference.h' file not found". Documentation for this release states that you can reference core/reference.h, but this file is not found in the source. Documentation link: https://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html?highlight=custom%20modules

### Steps to reproduce

Create a module based on documentation at https://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html?highlight=custom%20modules. Compile source with module.

### Minimal reproduction project

No project, just compile the source

**Comment by bruvzg** [comment]
> fatal error: 'core/reference.h' file not found

It's renamed to `core/object/ref_counted.h`.

**Comment by pycbouh** [comment]
Note that the documentation in `latest` is not supposed to be used, it may not necessarily be up to date, as the 4.0 release is not yet finalized, let alone released.

We can keep this issue open as a reminder to update the docs.

**Comment by jimbeauphloyd** [comment]
Perfect, thanks for the tip!

**Comment by YuriSizov** [comment]
This was closed by https://github.com/godotengine/godot-docs/pull/5205.
