### ISSUE TITLE
Difficulties when translating 3D view name

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#50742]
### Godot version

3.3.2, 3.4.beta1, 3.x(883bb2f4f6), 4.0(5de991d57c)

### System information

macOS 11.4

### Issue description

Name is shown on the top left corner of each 3D viewport, like "Top Orthognal". But i18n and l10n are done separately on each word and then joined with a space.

This is OK in English, but in languages like Chinese, the space is not needed. There is no way to get rid of the space because it's hardcoded.

Wording & order may also be different depending on the context in other languages. "Top Orthognal" may not always be "Top" + "Orthognal". For example, Top - 顶部,  Orthognal - 正交, but Top Orthognal should be 正交顶视图 in Chinese, which swaps the order and changes the words when used together.

Currently, "thanks" to the space, "顶部 正交" makes sense if you think it's displaying two separate fields. But it's not ideal since Top Orthognal is always 正交顶视图 in other 3D softwares (e.g. Blender).

### Steps to reproduce

Open the 3D editor in Chinese.

**Comment by akien-mga** [comment]
Yes that logic should be refactored to have the full names be translated, not be combined from sub-strings:
https://github.com/godotengine/godot/blob/c2c82de49de93d58f8be1255ca787e2aa8c7f129/editor/plugins/node_3d_editor_plugin.cpp#L759-L773

It wouldn't work at all for RTL languages, and the `" [auto]"` part can't be localized currently and hardcoding the space wouldn't be good either for RTL.
