### ISSUE TITLE
To attract attention to the problem

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#5075]
Please note the #4139. A lot of inconvenience due to the fact that files with the same names in different directories are considered among those balk

**Comment by akien-mga** [comment]
Don't do that.

**Comment by ret80** [comment]
I have to do this because the problem weighs too long and not someone she is not interested.

**Comment by ret80** [comment]
and if I just write in the old theme that the chances are small halter attention.

**Comment by vnen** [comment]
That's not how it works. If you comment in the old issue everybody who's watching this repo will be notified. Creating a new issue only annoy us with an unneeded extra notification.

**Comment by ret80** [comment]
I know how it works. But sometimes it is achieved that the result should be all ruffle. :)

**Comment by akien-mga** [comment]
As @vnen said, commenting in the other thread is enough to "bump" it. Creating another pointless issue just generates annoyance, and less interest in your other issue, because nobody wants to fix bugs for annoying users.
