### ISSUE TITLE
`is_on_floor()` is jittering when going up the steep slope as wall from floor

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#50756]
### Godot version

4.0.dev

### System information

MacOS 11.4, Windows 10

### Issue description

When moving a `CharacterBody` from a floor to an angled wall with `move_and_slide()`, `is_on_floor()` jitters because the `CharacterBody` floats in the air for a second.

https://user-images.githubusercontent.com/61938263/126719743-341db9c4-1423-40a7-a6b8-7f61de227d91.mov

The floating by `move_and_slide()` may be ignoring snap.

In 3.x, this could be prevented to some extent by using `move_and_collide()` and the user's own slide using the gotten `linear_velocity` (but not completely).

~In 4.0, `move_and_collide()` is not implemented. Also, `CharacterBody` in 4.0 does not have a function like `move_test()` to predict the next move. Perhaps some kind of prediction function is needed to solve this problem.~

To solve this problem, we need to predict how `test_move()` will behave with the collider it finds, so `test_move()` should return information other than `bool`.

### Steps to reproduce

Moving a `CharacterBody` from a floor to an angled wall with `move_on_slide()`

### Minimal reproduction project

Same #50732.

**Comment by pouleyKetchoupp** [comment]
For info, in 4.0 `move_and_collide()` and `test_move()` have been moved to `PhysicsBody3D` to make them available to more physics classes, so you can still use them with `CharacterBody3D`.

**Comment by TokageItLab** [comment]
Probably what is really wanted in this problem is to determine whether the object returned by `test_move()` is a Wall, Floor, or Ceil, but the current `test_move()` returns only a bool, so it may need to be improved.

**Comment by pouleyKetchoupp** [comment]
That sounds like a good idea, I don't think it would be to difficult to add it, possibly as new functions in `KinematicCollision3D` to keep the API simple.

(Not to say this issue shouldn't be fixed by making `is_on_floor()` consistent when hitting corners)

**Comment by TokageItLab** [comment]
Yes, I want consistency in behavior too. So, I think the appropriate tag for this issue is enhancement, not regression or bug.

**Comment by pouleyKetchoupp** [comment]
@TokageItLab I think it can still be considered a bug, since `move_and_slide` is supposed to be used to consistently detect the floor. So it should work ok out of the box in a case like this, and this should be the priority.

On the other hand, adding support for floor and wall detection in `move_and_collide` does seem like it can be useful to work around specific issues, or just to make a custom character controller. So that can be seen as an enhancement that is separated from the current issue. Feel free to open a proposal if you're interested, otherwise I've added it to my list to do later.

**Comment by TokageItLab** [comment]
Perhaps in solving this problem, we may encounter the problem of not going over a low step and we may need a method to determine whether the slope is caused by the terrain or by the Player's collision.

https://user-images.githubusercontent.com/61938263/126867363-1106491e-0c68-4024-94c8-9938cbe9de8e.mov
