### ISSUE TITLE
Changing nodes' group through Groups Editor doesn't trigger update, and causes error

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50758]
### Godot version

v4.0.dev.custom_build [515670351]

### System information

Windows 10

### Issue description

When using the Groups Editor that's opened from the "Manage Groups" button, adding or removing nodes from groups causes the node to properly change group, but it doesn't cause an update to trigger in the Groups Editor.  It also causes an error to appear in the console. You need to click on the group again in the "Groups" column for it to update.

Error: `core\object\undo_redo.cpp:310 - Error calling method from signal '_group_selected': 'GroupDialog::_group_selected': Method not found.`

https://user-images.githubusercontent.com/12120644/126722944-c97f64cd-d9f7-49af-8d71-4951b9d33c45.mp4

This bug does not occur in 3.3.2.stable, or the latest 3.x (v3.4.beta.custom_build [b856841b9])

### Steps to reproduce

- Have a node that's added to a group
- Open up the "Manage Groups" dialog
- Remove the node from the group
- It won't immediately update until you click on the group again, and it'll show an error in the console

### Minimal reproduction project

any project with nodes with groups

**Comment by Calinou** [comment]
This may be due to the inspector no longer using `change_notify()` and relying on polling instead.

**Comment by KoBeWi** [comment]
Fixed.
