### ISSUE TITLE
Reparent button in the right click menu for nodes in scene tree does not work

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50754]
### Godot version

v4.0.dev.calinou [a4c863791]

### System information

Windows 10

### Issue description

The "Reparent" button in the right click menu for nodes inside of the scene tree does not work, there's no errors that show up in the console. However, the "Reparent to New Node" button does work.

https://user-images.githubusercontent.com/12120644/126707607-2307664d-cb79-4596-9f01-b77b7ed6da0d.mp4

### Steps to reproduce

- In the scene tree, use the "Reparent" button in the right-click menu for a node
- Reparent to another node in the scene
- It won't work

### Minimal reproduction project

any project with nodes

**Comment by TokageItLab** [comment]
The same issue occurs in `AnimationTrackEditor` #50719.

**Comment by akien-mga** [comment]
If it's a recent regression, might be related to #50559? See also #50744 due to 3.x cherrypick.

**Comment by foxydevloper** [comment]
> If it's a recent regression, might be related to #50559? See also #50744 due to 3.x cherrypick.

It seems to the node selection popup itself that's broken, see https://github.com/godotengine/godot/issues/50719
![image](https://user-images.githubusercontent.com/12120644/126709990-c784b61b-8bec-4a1d-a0d4-536c98ed26f9.png)
