### ISSUE TITLE
Tilemap not showing tiles when tileset are added by code

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#5076]
**Operating system or device - Godot version:**
Windows 7 64bit
release version 2.0.2 or 2.1 alpha custom build

**Issue description** (what happened, and what was expected):
var ts = TileSet.new()
tilemap.set_tileset(ts)
only show tiles in Tilemap when he has a dummy tileset added by hand

**Steps to reproduce:**
1. create a scene (*.TSCN or *.SCN)
2. add a tilemap node
3. create tileset by gdscript and add it with set_tileset() to tilemap node

```
func _ready():
    var ts = TileSet.new()
    for i in range(10):
        ts.create_tile(i)
        ts.tile_set_texture(i,newTexture(imageSize))
        ts.tile_set_name(i,str(i))
    get_node("TileMap").set_tileset(ts)
    for i in range(10):
        for j in range(10):
            get_node("TileMap").set_cell(5+i,5+j,j,false,false,false)
    get_node("TileMap").set_cell_size(imageSize)
```
1. play scene
2. nothing is displayed
3. stop scene
4. click on tilemap node
5. chose Tile Set --> New TileSet
6. play scene
7. everything works
   ![bug_with_set_tileset](https://cloud.githubusercontent.com/assets/10463138/15839880/6ca4c2f4-2c46-11e6-8b32-5831ee958fec.gif)

**Comment by vnen** [comment]
It doesn't work like this, the code is not executed in the editor. It might work if you use the `tool` keyword, but then I'm not sure how this will get the tilemap in runtime.

If you want to generate a TileSet via code and make the TileMap in editor the best way I can see is to use [ResourceSaver](http://docs.godotengine.org/en/latest/classes/class_resourcesaver.html) to save the TileSet to disk and load it in the editor.

**Comment by puppetmaster-** [comment]
I don't want to see the generated tiles in the editor (only as a bonus). 
I like to see the placed tiles while running the scene. But they don't show.
```
for i in range(10):
        for j in range(10):
            get_node("TileMap").set_cell(5+i,5+j,j,false,false,false)
```

**Comment by vnen** [comment]
Oh, I see now. Indeed, the TileMap only show stuff if you add the dummy TileSet in editor.

**Comment by neikeq** [comment]
Call this method after changing the TileSet:
``` GDScript
get_node("TileMap")._update_dirty_quadrants()
```

**Comment by vnen** [comment]
@neikeq had no idea this existed, it is not documented anywhere. Any reason to not call it automatically after setting a TileSet?

**Comment by neikeq** [comment]
@vnen No idea. The reason it doesn't appear in the documentation is that it ignores methods that start with `"_"` but are not virtual.

**Comment by reduz** [comment]
there should be no need to do this, _update_dirty_quadrands is called later with a deferred call on any changes that may happen. If you have an example of this not working, please make an example project and I will test it

**Comment by neikeq** [comment]
Example project:
[GenTilemap.zip](https://github.com/godotengine/godot/files/310555/GenTilemap.zip)

**Comment by eon-s** [comment]
I was using @puppetmaster- 's plugin for some big tileset and noticed this:
If you touch the shape controller dot (not the scale ones), the shape exports correctly.

In the tscn, rectangle shapes ignored by export have `_update_shape_index = -1`
Ignored polygons have `shape_range = Vector2( -1, -1 )`

That is the only difference that I was able to notice (and I'm not sure if means something).

**Comment by Hoten** [comment]
I came across the same issue. Calling._update_dirty_quadrants() fixed it for me too.

**Comment by neikeq** [comment]
After a bit of debugging I think I found the problem. After the following change my [example project](https://github.com/godotengine/godot/issues/5076#issuecomment-225400164) works as expected:

``` diff
@@ -269,9 +269,12 @@ void TileMap::_update_dirty_quadrants() {
 	if (!pending_update)
 		return;
 	if (!is_inside_tree())
-		return;
+		return; // not sure if also needed here
 	if (!tile_set.is_valid())
+	{
+		pending_update = false;
 		return;
+	}
 
 	VisualServer *vs = VisualServer::get_singleton();
 	Physics2DServer *ps = Physics2DServer::get_singleton();
```

I am not sure though so I will let someone with more experience with TileMap take care of this.

**Comment by bojidar-bg** [comment]
@neikeq Just PR it I guess.
Also, I think both returns are necessary, since node's properties are set before `_ready` or `_enter_tree`, and it is possible for something weird to occur if adding the node through a thread...
(Looks good to me).
