### ISSUE TITLE
Signals only connect to root

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#50778]
### Godot version

4.0.dev 8cddd3b

### System information

Windows 10

### Issue description

When connecting signals true the editor.
they always connect to the root script not the selected script.

### Steps to reproduce

Try connecting somewhere else

### Minimal reproduction project

[mrp signal not connecting.zip](https://github.com/godotengine/godot/files/6869472/mrp.signal.not.connecting.zip)

**Comment by KoBeWi** [comment]
Looks fixed in dcf2a62
