### ISSUE TITLE
Boot Splash Use Filter option has no effect

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50784]
### Godot version

v4.0.dev.custom_build [d17201afc]

### System information

Windows 10

### Issue description

The "Use Filter" project setting (`application/boot_splash/use_filter`) does nothing when enabled, the boot splash always renders with filter off. The option works fine in v3.4.beta.custom_build [322252e], so this is a regression.

### Steps to reproduce

- In the Boot Splash section of project settings:
- - Set a boot splash image
- - Enable "Use Filter" (on by default)
- Run the project
- The boot splash will not use filter

### Minimal reproduction project

[testing_boot_splash_use_filter_v4.0.zip](https://github.com/godotengine/godot/files/6870325/testing_boot_splash_use_filter_v4.0.zip)

**Comment by Calinou** [comment]
For the record, the splash screen was reimplemented in `master` by https://github.com/godotengine/godot/pull/50137. Filter options now need to be set on a per-texture use thanks to Vulkan bindless textures.

**Comment by foxydevloper** [comment]
Can confirm this still happens as of v4.0.alpha.calinou [c80540f9a]
