### ISSUE TITLE
View recently edited objects history always blank

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50783]
### Godot version

v4.0.dev.custom_build [d17201afc]

### System information

Windows 10

### Issue description

The "History of recently edited objects" button always shows no results. However, the "Go to previously edited object" and "Go to next edited object" buttons do work. This is a regression from v3.x

![image](https://user-images.githubusercontent.com/12120644/126819417-f2b06a55-0fd4-47df-8e45-1f1ebd896053.png)

It works fine in v3.4.beta.custom_build [322252e89]:
![godot windows opt tools 64_2021-07-23_13-24-51](https://user-images.githubusercontent.com/12120644/126819638-7b867971-744e-4410-bbb5-7bcb85e2da1c.png)

### Steps to reproduce

- Have a scene with multiple nodes inside of it
- Select a few of those nodes
- Click "History of recently edited objects"
- It will always be blank

### Minimal reproduction project

Scene with multiple nodes

**Comment by requizm** [comment]
I can't reproduce on v4.0.dev.custom_build https://github.com/godotengine/godot/commit/3e214a88380dab46a77d48863b7a6f1bc37e2885

Any reproducers?

**Comment by KoBeWi** [comment]
Seems fixed.
