### ISSUE TITLE
 Tab character not properly displayed in the Output panel

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5079]
**Operating system or device - Godot version:**
Mageia 6 x86_64. Current master branch (0729c85), the bug is not reproducible in 2.0.3-stable.

**Issue description** (what happened, and what was expected):
Tab charaters are not displayed in the Output panel when printed, though they still work just fine in the system terminal. E.g. ``printt("instanced scene ", scene, scene.get_filename())`` gives:

![screenshot_20160607](https://cloud.githubusercontent.com/assets/4701338/15847415/f17bbc82-2c85-11e6-8866-dc6004cec322.png)

**Steps to reproduce:**
```
printt("This should start with a line with `<?>` character.")
```

**Comment by akien-mga** [comment]
It could be that the tab character (`U+0009`, `	`) is not supported in the new editor font.

**Comment by bojidar-bg** [comment]
Note that before the font change it was displayed as a simple space. (not that it was better..)

**Comment by akien-mga** [comment]
No it was displayed as a tab character (much wider than a space).

**Comment by reduz** [comment]
this is weird, RTL considers tab a special character, for some reason it's lost here..
