### ISSUE TITLE
Camera2D's reset_smoothing() does not work as described

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot#50807]
### Godot version

3.3.stable, 4.0.dev

### System information

Windows 10

### Issue description

With Camera2D's smoothing enabled and limit smoothing enabled, after setting the limits and camera position, `reset_smoothing()`'s description implies that it should snap to the smoothed intended position immediately.

Printing `get_camera_position()`'s output before and after calling `reset_smoothing()` does say that its position has changed, but on screen the camera just keeps travelling to its intended position without actually snapping into place. Same behavior as if `reset_smoothing()` had not been called at all.

Calling `force_update_scroll()` right before calling `reset_smoothing()` does, however, snap the camera position into place. Looking at the source code, `reset_smoothing()` is:

```cpp
void Camera2D::reset_smoothing() {
	smoothed_camera_pos = camera_pos;
	_update_scroll();
}
```

So feels to me like `_update_scroll()` should be happening first, then `smoothed_camera_pos` should be set.

### Steps to reproduce

1. Put a Camera2D
1. Turn on smoothing_enabled and Limit smoothing
1. Make it move from its position to a new position
1. Call reset_smoothing() and watch it still animate

**Comment by lawnjelly** [comment]
This could be a regression as we made a few changes to the camera processing. If you can make a min reproduction project I can test this out.

**Comment by Razoric480** [comment]
[CameraLimitTest.zip](https://github.com/godotengine/godot/files/6872641/CameraLimitTest.zip)

**Comment by lawnjelly** [comment]
Can confirm this seems to operate the same in 3.2.3 as in 3.4 dev, so it's not a recent regression. I'm not absolutely sure yet whether it is meant to behave like this as I'm not familiar with that bit of code, but I'll try and work it out.

**Comment by lawnjelly** [comment]
Yeah it also occurs like that in 3.1.2 so this behaviour has existed for a long time. It does look like it might be a bug because it is retrieving the camera position from the visual server in `_update_scroll`. I'll probably have to leave looking at this until after the 3.4 beta (anyone else is free to look, I don't think this is that difficult a bug just I'm short of time).
