### ISSUE TITLE
Can't click buttons when the window is scaled using the `viewport` stretch mode (DisplayServer regression)

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#50802]
### Godot version

v4.0.dev.calinou [b918c4c3c]

### System information

Windows10 

### Issue description

Project Settings/Window like this:
![111](https://user-images.githubusercontent.com/35988767/126866918-81d87746-fa96-486b-92e1-13860125de95.PNG)
then button can't click.
![333](https://user-images.githubusercontent.com/35988767/126866980-cb3339b2-096d-466e-8685-11a797845e54.gif)

### Steps to reproduce

/

### Minimal reproduction project

[PanelTest.zip](https://github.com/godotengine/godot/files/6872323/PanelTest.zip)

**Comment by Calinou** [comment]
Can you reproduce this with the `canvas_items` stretch mode (formerly `2d`)?

**Comment by CsloudX** [comment]
@Calinou I was tested with the canvas_items, It's right.
