### ISSUE TITLE
Input.is_action_just_pressed doesn't work.

### ISSUE THREAD

**Issue by cabbi3** [godotengine/godot#50808]
### Godot version

3.3.2 mono

### System information

Windows 10, Acer Swift 3

### Issue description

I made a platformer character controller, but I can reproduce this error outside of its code as well. When I use Input.is_action_just_pressed(), it takes multiple button presses for it to respond.

### Steps to reproduce

Use Input.is_action_just_pressed.

### Minimal reproduction project

Just load up a project and use input.is_action_just_pressed.

**Comment by foxydevloper** [comment]
I can't reproduce on v3.3.2.stable
Does it work for you on this testing project?
[Testing is_action_just_pressed.zip](https://github.com/godotengine/godot/files/6872783/Testing.is_action_just_pressed.zip)

**Comment by pycbouh** [comment]
You need to provide an actual MRP, @ch3rrypicked, otherwise we cannot help you.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
