### ISSUE TITLE
Creating new json file is caching old file object data

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#50810]
### Godot version

3.3 stable

### System information

Linux mint

### Issue description

I have some JSON data (I will list it below). I save it as follows:

The code is in an autoload, I don't know if this is relevant or not:

```
	var new_save=File.new()
	new_save.open("res://gavesave1.save",File.WRITE)

	var jdata=to_json(save)
	var err=new_save.store_string(jdata)
	new_save.close()
```
On the first save, the file is saved ok with the correct data.

I added a brand new entry to the dictionary, modified some values, restarted my game (not the editor) and on running the above code again, the new entry nor the data changes made it into the file, it contained the old code. At a breakpoint I can see that 'jdata' holds the new data to be written, not the old, so the string/json is fine.

If I delete the save file and run the code again (without restarting Godot) it recreates the file but still the old save file was saved.

I then changed the file name and saved it and it wrote the new data correctly.

I then restarted Godot and on the first write, it saved the new data fine.

I then ran it a second time in same Godot session, having modified the data, and it wrote the old data from the first save.

So, the only conclusion (unless there's something wrong with my code), is that something is caching the file in the autoload.

This means that a binary release will almost likely do the same thing.

From the below I added a new value "XXXX" and modified some data on subsequent runs
```
var save ={
		"bunny_hiscore" 	: 1,
		"bunny_unlocked"	: false,
		"current_weapon" 	: 1,
		"easy_mode"			: false,
		"graphics_type"		: 1,
		"has_continue"		: false,
		"heat_shader" 		: true,
		"help_energy_seen" 	: false,
		"help_oxygen_seen" 	: false,
		"help_pod_seen" 	: false,
		"help_smart_seen" 	: false,
		"mouse_mode"		: 1,
		"next_life" 		: 10000,
		"player_spawn_point": "Spawn1",
		"score" 			: 1,
		"smart_bombs" 		: 3,
		"speccy_extra"		: true,
		"training_complete" : true,
		"weapon_level" 		: [0,    0,    0,    0,    0  ],
		"windowed_mode"		: 1,
		"volume_music"		: 100,
		"volume_sound"		: 100
	}
```

### Steps to reproduce

1. create an autoload with save option
2. save the data
3. stop the code
4. modify the dictionary to write
5. delete the file from the file system
6. run again
7. the old file data is written

You can restarted Godot and repeat the above. The first save will be fine, subsequent ones will fail.

### Minimal reproduction project

I can create one if requested. But in the meantime I would like to know if there is a workable solution.

**Comment by chucklepie** [comment]
Unless this is as designed (I wouldn't have thought so?), I've noticed the order of JSON is not preserved and on saving, the dictionary is sorted by key. I dunno if this is a potential fault area for my above given the Godot library does not provide a sorting option either.

**Comment by pycbouh** [comment]
> I can create one if requested.

Please do, because your explanation is not exactly trivial to reproduce and we can never exclude user error too. So in the interest of saving time an MRP is indeed required.

**Comment by chucklepie** [comment]
Ok, will try. While you're there, could you answer why using to_json() sorts the dictionary? But the default JSON print method is unsorted?

**Comment by Calinou** [comment]
> But the default JSON print method is the opposite and outputs unsorted?

Dictionaries are ordered when stored, but printing is not guaranteed to follow this order. This is documented in the Dictionary class reference already.

**Comment by Calinou** [comment]
> Ok, will try.

Bump :slightly_smiling_face:

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
