### ISSUE TITLE
Crash on GLES3, might be related to Linux/Intel freezes.

### ISSUE THREAD

**Issue by delphonso** [godotengine/godot#50829]
[test.zip](https://github.com/godotengine/godot/files/6878133/test.zip)
Empty project but with GLES2 selected for anyone who runs into a similar issue - though Calinou points out a command-line solution.
### Godot version

3.2.3(stable), 3.3(stable)

### System information
Intel Corporation GeminiLake [UHD Graphics 600] (rev 03), driver: i915

Ubuntu 21.04

### Issue description

A friend and I worked on a game for a gamejam the past two weeks. When playing other submissions to the jam, occasionally I would get a total freeze (flickering between two frames usually on the Godot logo) that required a hard reset. 

After the jam, every new project or template I used would crash - same type of freeze. Happened 95% of the time, not every time, though. I can open the project selection window, but freezes before getting to the editor.

Similar to the issues people were having with Intel and Godot4 - I tried --single-window and running from terminal - no change.

I went back to the project my friend and I made, which happened to be in GLES2. I switched it to GLES3 and instantly got the crash again.

Since everything defaults to GLES3, new projects and templates all crash before you can change them to GLES2.

### Steps to reproduce

If you're getting the Ubuntu freeze issue, try downloading a GLES2 project and opening that.

**Comment by Calinou** [comment]
> Since everything defaults to GLES3, new projects and templates all crash before you can change them to GLES2.

As a workaround, start the editor or project with the `--video-driver GLES2` [command line argument](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html).

**Comment by delphonso** [comment]
Thanks for the info, the command line option is pretty convenient.

This issue happened with both 3D and 2D, the jam game being 2D and only freezing when switching to GLES3. 

I should mention I tried a full reinstall - and cleared configs, caches, and share, too. No impact.

**Comment by lawnjelly** [comment]
From your description it sounds most likely (although not definite) to be a graphics driver issue, as that is the main difference when running GLES2 / GLES3. For anything possibly graphics related it's a good idea to include info on your GPU in the issue. If it occurs in 3.2.3 as well, that's before GLES3 batching, so that suggests something fundamental your GPU is not able to deal with.

Another thing to try would be if you can force software OpenGL rendering on your system, I think there is a way to do it using llvmpipe. If that runs ok (but slow) it would also suggest a driver / GPU issue.

**Comment by delphonso** [comment]
There is a known issue with Ubuntu freezing and flashing on Intel boards - it is apparently a driver issue, but has slightly different symptoms. This issue only occurs with Godot GLES3 for me right now, I'll keep testing and see if I can find any other program which will freeze it up, confirming the driver, Ubuntu issue rather than anything specific to Godot.

**Comment by delphonso** [comment]
Running Godot 3.2.3 on Manjaro on a Raspberry Pi 4 has a very similar effect, except Manjaro manages to throw up an error window pointing out either outdated drivers or too old of a GPU. Godot runs fine with GLES2, so appears to be the same issue. 

I am confident that this is merely an issue with Ubuntu Budgie 21.04 (and presumably older) being unable to put up the error window and freezing/flickering instead.
