### ISSUE TITLE
Cannot instantiate File class to read CSV file

### ISSUE THREAD

**Issue by Blackiris** [godotengine/godot#50831]
### Godot version

4.0.dev (fb821b83986dcfd610b7330f4128e169e8368c45)

### System information

Linux

### Issue description

When trying to open a CSV file using this code:
```gdscript

extends Node

# Called when the node enters the scene tree for the first time.
func _ready():
	var file = File.new()
	file.open("res://file.csv", file.READ)
```

I get the following errors:
```
ERROR: Cannot get class 'File'.
   at: instantiate (core/object/class_db.cpp:529)
ERROR: Class type: 'File' is not instantiable.
   at: _new (modules/gdscript/gdscript.cpp:76)
```

The CSV file is set at Do not import.
The issue started from a commit 2 or 3 days ago, but it is hard to bisect it since many scene file formats had some changes which make them incompatible with older versions of Godot.

### Steps to reproduce

Open the reproduction project and launch it

### Minimal reproduction project

[FileInstantiate.zip](https://github.com/godotengine/godot/files/6873538/FileInstantiate.zip)

**Comment by qarmin** [comment]
This is regression between b918c4c3c and fb821b8

**Comment by Blackiris** [comment]
> This is regression between [b918c4c](https://github.com/godotengine/godot/commit/b918c4c3ce84af1f8af2d06ef31784f48a15551a) and [fb821b8](https://github.com/godotengine/godot/commit/fb821b83986dcfd610b7330f4128e169e8368c45)
> 
> I thinky that this commit could do this - #50511

Hey! Nice catch! Just tried to revert this commit and it works. It is now much easier to debug. Thanks!

**Comment by akien-mga** [comment]
CC @aaronfranke 

Haven't checked in depth yet but from the changes in #50511 to ClassDB, this part might have changed behavior:
![Screenshot_20210725_120345](https://user-images.githubusercontent.com/4701338/126895355-bd8cce25-29f6-49ec-8cff-ed39d818b1da.png)

I think now we're always making a copy while before we were copying only when doing a validation.
But that doesn't necessarily relate to this bug.

**Comment by akien-mga** [comment]
> I think now we're always making a copy while before we were copying only when doing a validation.
But that doesn't necessarily relate to this bug.

Tested, that doesn't impact this bug indeed. I'll add a fix for this anyway in #50809.

**Comment by Blackiris** [comment]
Found it, it is here:
https://github.com/godotengine/godot/blob/2a8a59eac0f1bbec83d4d04cac9f428487a0d738/modules/gdscript/gdscript.cpp#L1646-L1658

More exactly this line:
`Ref<GDScriptNativeClass> nc = memnew(GDScriptNativeClass(n)); `

You can see than the n value is erased here
`n = s.substr(1, s.length());`

Before it was, 
`Ref<GDScriptNativeClass> nc = memnew(GDScriptNativeClass(E->get()));`
Which was the original value in the loop variable

**Comment by Blackiris** [comment]
Too bad, avoiding n to be erased is not enough... Got a new error 
```
SCRIPT ERROR: Compile Error: Identifier not found: File
          at: GDScript::reload (res://new_script.gd:5)
ERROR: Method/function failed. Returning: ERR_COMPILATION_FAILED
   at: reload (modules/gdscript/gdscript.cpp:858)
```

**Comment by Blackiris** [comment]
Ah found it, forgot to also change line:
`_add_global(n, nc);`
