### ISSUE TITLE
Always true expression `radius > 0.98 || radius < 1.02`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50846]
### Godot version

4.0 5d9cab3aeb3c62df6b7b44e6e68c0ebbb67f7a45

### Issue description

https://github.com/godotengine/godot/blob/5d9cab3aeb3c62df6b7b44e6e68c0ebbb67f7a45/servers/rendering/renderer_rd/cluster_builder_rd.h#L238

**Comment by Calinou** [comment]
It should use `&&` instead of `||`.
