### ISSUE TITLE
Self assignment `info.binding = info.binding`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50844]
### Godot version

4.0 ff0b5f8fa1be4ccd5b8de1d9d49f8a4b71439f63

### Issue description

https://github.com/godotengine/godot/blob/ff0b5f8fa1be4ccd5b8de1d9d49f8a4b71439f63/drivers/vulkan/rendering_device_vulkan.cpp#L4553

**Comment by akien-mga** [comment]
I think you misread, it's assigning the `binding` member of `const SpvReflectDescriptorBinding &binding = *bindings[j];` to a `UniformInfo info;`.

That's a translation between two incompatible structs with a compatible member, not a self-assignment.

**Comment by qarmin** [comment]
I copied wrong line, now it is fixed

**Comment by akien-mga** [comment]
Seems like #50847 fixes it.
