### ISSUE TITLE
Reduntant assignement of `arr[i + max]`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50848]
### Godot version

4.0 ff0b5f8fa1be4ccd5b8de1d9d49f8a4b71439f63

### Issue description

https://github.com/godotengine/godot/blob/ff0b5f8fa1be4ccd5b8de1d9d49f8a4b71439f63/core/debugger/remote_debugger.cpp#L409-L413

**Comment by YuriSizov** [comment]
This was fixed by https://github.com/godotengine/godot/pull/59911.
