### ISSUE TITLE
Redundant assignement of `name` inside `configure_joypad` function

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50850]
### Godot version

4.0 50a0a401a10dda9718169d690b4b941100eb4a2c

### Issue description

https://github.com/godotengine/godot/blob/50a0a401a10dda9718169d690b4b941100eb4a2c/platform/osx/joypad_osx.cpp#L287-L290

**Comment by akien-mga** [comment]
That seems to date back to 8c886b9d7a2.
