### ISSUE TITLE
Redundant assignement of `ssao.gather_push_constant.radius`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50851]
### Godot version

4.0 2a8a59eac0f1bbec83d4d04cac9f428487a0d738

### Issue description

https://github.com/godotengine/godot/blob/2a8a59eac0f1bbec83d4d04cac9f428487a0d738/servers/rendering/renderer_rd/effects_rd.cpp#L1220-L1224

**Comment by clayjohn** [comment]
Whoops! It's an easy fix, just need to rearrange the assignments.
