### ISSUE TITLE
Redundant assignement of `using_separate_specular`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50853]
### Godot version

4.0 1ba87f0c82ca62deaba71767ed08270a45fac2e9

### Issue description

https://github.com/godotengine/godot/blob/1ba87f0c82ca62deaba71767ed08270a45fac2e9/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L1285-L1287

**Comment by akien-mga** [comment]
One of those is meant to be `false`, it's setting a flag for using in `render_buffer->ensure_specular()`. But I don't know which.

**Comment by clayjohn** [comment]
Fixed at some point. That code is long gone
