### ISSUE TITLE
Redundant assignment of `blur_pipeline`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#50852]
### Godot version

4.0 2a8a59e

### Issue description

https://github.com/godotengine/godot/blob/2a8a59eac0f1bbec83d4d04cac9f428487a0d738/servers/rendering/renderer_rd/effects_rd.cpp#L1353-L1355

**Comment by akien-mga** [comment]
This can simply be made an `else`.

**Comment by Vitika9** [comment]
@akien-mga I am very new to contributing,do you mean someone needs to put line 1355 in an else statement?

**Comment by Calinou** [comment]
> @akien-mga I am very new to contributing,do you mean someone needs to put line 1355 in an else statement?

Yes, only that line should be within the `else` statement.

**Comment by Vitika9** [comment]
@akien-mga thanks,I will do that :)

**Comment by Vitika9** [comment]
@Calinou thanks :)
