### ISSUE TITLE
Threads on HTML5 don't work because of policy change

### ISSUE THREAD

**Issue by CenTdemeern1** [godotengine/godot#50868]
### Godot version

3.3.2.stable

### System information

Windows 10, not relevant (happens on Linux and Android and Mac and stuff too)

### Issue description

![image_554](https://user-images.githubusercontent.com/24682280/126912821-c121b094-ff2f-418f-ac6e-095d141213bb.png)
![image_555](https://user-images.githubusercontent.com/24682280/126912822-0494b326-5083-4bb7-b49a-4fa20830bfa0.png)
Due to policy changes regarding SharedArrayBuffer, HTML5 exports with threading don't work. (they don't get past the spinner, they don't start)

### Steps to reproduce

Export a game with HTML5, with threads enabled
![image](https://user-images.githubusercontent.com/24682280/126912849-eecd43b0-1bb9-477f-95a7-24cca16d6ed1.png)

### Minimal reproduction project

[HTML5bug.zip](https://github.com/godotengine/godot/files/6874537/HTML5bug.zip)

**Comment by Calinou** [comment]
This is something you need to fix by making the web server send the correct headers. (Unfortunately, if you're using itch.io or GitHub Pages, there is nothing you can do about this.)
