### ISSUE TITLE
Opening certain scene freezes editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#50865]
### Godot version

e2ebc7d

### System information

W10

### Issue description

I have a scene that freezes editor when I try to open it. Also happens when I try to open a scene that instances this scene or copy it to another project and try opening it there.

It opens fine in 3.x

### Steps to reproduce

Open this scene:
[Clamir2.zip](https://github.com/godotengine/godot/files/6874342/Clamir2.zip)

**Comment by KoBeWi** [comment]
The freeze is caused by GDScript parser. The scene has a built-in script and it seems to hang on `yield` while being loaded.

I reduced the script as much as I could, here's almost minimal version:
```GDScript
extends Node2D

func on_process(delta: float):
	match state:
		DASH:
			if vulnerable:
				get_parent().add_child(explosion)
#				yield(get_tree().create_timer(1), "timeout")
```
Uncomment the last line to freeze editor

**Comment by KoBeWi** [comment]
Just found another case, this time without using yield:
[ReproductionProject.zip](https://github.com/godotengine/godot/files/6913432/ReproductionProject.zip)
It's just a scene with built-in script extending a class. You can't open it.

**Comment by JestemStefan** [comment]
When I run @KoBeWi minimal version I got freeze and Godot editor ate all my 16 GB of RAM.


Also I get this error when I removed more code from MRP. Seems off so I'm sharing.
![obraz](https://user-images.githubusercontent.com/37214990/129097989-32e823a4-e8a6-42af-8a3f-1fa836d34a81.png)

Also isn't `yield` removed in favor of `await`? Maybe there is some leftover code

**Comment by Calinou** [comment]
> Also isn't yield removed in favor of await? Maybe there is some leftover code

See https://github.com/godotengine/godot/pull/49445.

**Comment by KoBeWi** [comment]
GDScript parser hangs on this loop:
https://github.com/godotengine/godot/blob/78c8b7ffec388506bc0df32d7c86e3ef45604f6f/modules/gdscript/gdscript_parser.cpp#L1718-L1743
There is a branch that makes it not advance anymore. It can be fixed by putting `advance()` after `push_error()` here:
https://github.com/godotengine/godot/blob/78c8b7ffec388506bc0df32d7c86e3ef45604f6f/modules/gdscript/gdscript_parser.cpp#L1932-L1934
but it produces error that doesn't make sense, so it's probably not a correct fix.

**Comment by lyuma** [comment]
Reproduction case by @Scony (confirmed on master fb176d5f6e6dc2b43c630a041a8ab7d737173ec4 )

```gd
var y
func foo(x):
	match x:
		1 + 1:
			pass
		[1,2,[1,{1:2,2:var z,..,}]]:
			pass
		1 if true else 2:
			pass
		1 or 2 and 1:
			pass
		1 < 2:
			pass
		1 | 1:
			pass
		1 >> 1:
			pass
		1, 2 or 3, 4:
			pass
		_:
			pass
```

**Comment by lyuma** [comment]
Reproduction case by @lyuma [[ repro project ]](https://github.com/godotengine/godot/files/6864775/gdscript_match_bug.zip)
```gd
@tool
extends Node

func _requesting_user_content(p_user_content_type: int, p_database_id: String, p_callback: Callable) -> void:
	match p_user_content_type:
		SomeGlobalClassName.EnumValue:
			if p_database_id != "":
				var result = yield(
					AutoloadedManager.do_something_async(p_database_id),
					"completed"
				)
```

**Comment by lyuma** [comment]
Closing #49293 as duplicate.
Reproduction case by @unfa :
> 
> Issue description:
> Godot freezes and steadily allocates more and more memory after typing 0 before the first character in line 11 in Chat.gd script in my game.
> 
> The bug in action:
> https://youtu.be/kII1XJX1LII
> 
> Steps to reproduce:
> 
> Load provided project
> Go to Chat.gd file
> Insert 0 before the first character in line 11
> Watch Godot freeze and eat memory
> Reproduction project:
> 
> https://github.com/unfa/liblast/tree/a54eb54293aa771a6b4bd642eee7312af7422e96
> 

Specific GDScript code for Chat.gd is here: line 11 is a match expression:
https://github.com/unfa/liblast/blob/a54eb54293aa771a6b4bd642eee7312af7422e96/Game/Assets/HUD/Chat.gd

**Comment by KoBeWi** [comment]
Fixed by #52081

**Comment by mojoyup** [comment]
This isn't closed yet. This happens on 3.5.1 from Steam Godot. Using an array to update firebase. The function is not running yet. error: Parse Error: value expected WIHLE CHANGING THE ARRAY

![Capture](https://user-images.githubusercontent.com/29804613/194714964-d512bf06-d1a2-4c77-a83c-bd64e5219153.PNG)

**Comment by mojoyup** [comment]
UPDATE: This error just happened as well trying to fix it on my own: 
![image_2022-10-08_122120423](https://user-images.githubusercontent.com/29804613/194717375-402114a7-0654-4de2-a0e9-1aa9222dbfb6.png)
