### ISSUE TITLE
Update embedded GLEW files

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5087]
We have a couple GLEW files in our `drivers/gl_context`:
- [glew.c](https://github.com/godotengine/godot/blob/master/drivers/gl_context/glew.c)
- [glew.h](https://github.com/godotengine/godot/blob/master/drivers/gl_context/glew.h)
- [glxew.h](https://github.com/godotengine/godot/blob/master/drivers/gl_context/glxew.h)
- [wglew.h](https://github.com/godotengine/godot/blob/master/drivers/gl_context/wglew.h)

I don't know yet how old those files are, but at least pre-open sourcing (Feb 2014), so they could use an update. We did some patches here and there to handle build issues on some platforms, so hopefully upstream development would have made them non necessary after we upgrade.

**Comment by akien-mga** [comment]
If we're to trust the headers, we apparently have a version from 2008.. The current upstream version has an additional copyright mention for the new maintainer since 2008:
```
** Copyright (C) 2008-2015, Nigel Stewart
```

**Comment by vnen** [comment]
I tried to do this, but is much harder than just replacing the files. I'm not sure if there were some other customizations to those files.

**Comment by akien-mga** [comment]
Alright, I checked all old GLEW versions between 1.5.0 and 1.7.0 and find out that we currently use GLEW 1.5.6 (from 2010-09-09, [tarball here](https://sourceforge.net/projects/glew/files/glew/1.5.6/glew-1.5.6.tgz/download)).

Here's the diff for `glew.c`: http://hastebin.com/iduwawuqam
So those are likely our own changes. The Haiku stuff looks like a hack and should likely be fixed by undefining the directive somewhere else. The rest was likely done by @reduz or @punto- at some time.

**Comment by akien-mga** [comment]
Here's a diff for all four files, comparing our versions (before) to the pristine GLEW 1.5.6 files (after): 
[godot-vs-glew-1.5.6.diff.txt](https://github.com/godotengine/godot/files/303056/godot-vs-glew-1.5.6.diff.txt)

All in all it's not too bad, but if/when we update our GLEW version, we should try to get rid of such customisations whenever possible.

**Comment by akien-mga** [comment]
I tried to dump the 1.13.0 source files on top of our own, and just readded the fixed includes and defines for ``GLEW_STATIC``, and it built out of the box on X11 (and seems to run fine).

I still need however to find out what was the reason for this change:
```
 #if defined(_WIN32)
-#  define glewInternalGetProcAddress(name) wglGetProcAddress((LPCSTR)name)
+#  define glewGetProcAddress(name) wglGetProcAddress((LPCSTR)name)
 #else
 #  if defined(__APPLE__)
-#    define glewInternalGetProcAddress(name) NSGLGetProcAddress(name)
+#    define glewGetProcAddress(name) NSGLGetProcAddress(name)
 #  else
 #    if defined(__sgi) || defined(__sun)
-#      define glewInternalGetProcAddress(name) dlGetProcAddress(name)
+#      define glewGetProcAddress(name) dlGetProcAddress(name)
 #    else /* __linux */
-#      define glewInternalGetProcAddress(name) (*glXGetProcAddressARB)(name)
+#      define glewGetProcAddress(name) (*glXGetProcAddressARB)(name)
 #    endif
 #  endif
 #endif
 
-
-#include <stdio.h>
-#include <stdlib.h>
-#include <string.h>
-
-typedef void (*glewFuncAddr)();
-
-glewFuncAddr glewGetProcAddress(const GLubyte *  procname) {
-
-	glewFuncAddr addr = (glewFuncAddr)glewInternalGetProcAddress(procname);
-	if (!addr) {
-		char *addrARB = malloc(strlen((const char*)procname)+4);
-		strcpy(addrARB,(const char*)procname);
-		strcat(addrARB,"ARB");
-		addr = (glewFuncAddr)glewInternalGetProcAddress((const GLubyte*)addrARB);
-		free(addrARB);
-	}
-	if (!addr) {
-		char *addrEXT = malloc(strlen((const char*)procname)+4);
-		strcpy(addrEXT,(const char*)procname);
-		strcat(addrEXT,"EXT");
-		addr = (glewFuncAddr)glewInternalGetProcAddress((const GLubyte*)addrEXT);
-		free(addrEXT);
-	}
-	return addr;
-}
```

**Comment by J08nY** [comment]
@akien-mga try to build for windows, I did the same and it failed for me.

**Comment by reduz** [comment]
Ah.. that was added as a compatibility measure because older macs had
really bad opengl support. It may no longer be necessary I think
