### ISSUE TITLE
VisualScriptCustomNode working memory is not working

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#50879]
### Godot version

3.3.2

### System information

Windows 10

### Issue description

VisualScriptCustomNode
func _step(inputs, outputs, start_mode, working_mem):
working_mem is always `[]`

https://github.com/godotengine/godot/blob/438be4422f25ccc93aa47cd8ed9a01ff318949c7/modules/visual_script/visual_script_nodes.cpp#L2943

Between step and _step the working memory is swapped between `Variant *p_working_mem` and `Array work_mem`.
Now the `int work_mem_size` is never changed. So no size, no iteration, no memory.

When setting `work_mem_size = work_mem.size();` The project always fails on any line containing `p_working_mem[x]`.

If I can get some help converting from `Variant` to `Array` and back again? Then I think I can fix it.

### Steps to reproduce

Create a new custom node that has 2 sequence outputs and in _step append and print working memory

### Minimal reproduction project

Use Prototyping CustomNodeScript
[Autoload.zip](https://github.com/godotengine/godot/files/6877024/Autoload.zip)

Project
[VisualScriptCustomNodes.zip](https://github.com/godotengine/godot/files/6878020/VisualScriptCustomNodes.zip)

**Comment by Chaosus** [comment]
If you attach an actual test project rather than a naked GDScript file that would be helpful.

**Comment by Gallilus** [comment]
@Chaosus, Your right,

The project stops at line 110 the second time the _step is running

**Comment by Gallilus** [comment]
Have been testing some more.
Oo `p_working_mem->get_type()` also crashes. What's that about?

**Comment by Gallilus** [comment]
You need to use `func _get_working_memory_size():` and never assign / overwrite the `working_mem` when implementing CustomNode
