### ISSUE TITLE
Illegible function prototype hint on 3.x

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#50890]
### Godot version

3.x (8ecb5d2047)

### System information

macOS 11.4

### Issue description

`3.x` recently inverted the color scheme of tooltips. Function prototype hint of script editor now looks like this:

![dark](https://user-images.githubusercontent.com/372476/126996273-d4ba3821-d89a-4726-8c86-4d9c5397eb42.png)
![light](https://user-images.githubusercontent.com/372476/126996285-e0cfb3ca-97f9-48cb-96cd-95bce3a7b969.png)

It's hard to tell the tooltip from actual code. The return type in the screenshot looks like `astint`.

The tooltip on `master` has a larger padding, so not a problem on it.

### Steps to reproduce

Open the script editor and try.

**Comment by pycbouh** [comment]
Related to https://github.com/godotengine/godot/pull/50646.

**Comment by akien-mga** [comment]
CC @SirQuartz

**Comment by akien-mga** [comment]
I'm about to build 3.4 beta 2 so I'll revert #50646 for now, we can then re-do it while making sure that this issue doesn't happen.

**Comment by akien-mga** [comment]
Fixed by 2ae4748.

**Comment by SirQuartz** [comment]
Yeah, I think adding a shadow color would probably improve legibility a lot in the script editor.
