### ISSUE TITLE
Issue with world_to_map and scaling tilesets

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#50906]
### Godot version

3.3 stable

### System information

Windows 10, RTX 3070 (laptop), Ryzen 7

### Issue description

Hi,

I have a tileset which is 512x512, which I am downscaling using a scale property of (0.5, 0.5) to 256x256.

Within this tileset script, if I use world_to_map(to_local(Vector2(260, 0))), the returned value is 0,0. 
The returned value is the same up to (770, 0), after which it gives me the accurate return value (3,0).

However, if I go beyond 256 for y, that is Vector2(256, 256), will give me (1,1). Conversely, Vector2(256, 255) will give me (0,0)

What is going on here? Seems like a bug? 

Your help is appreciated. Thanks!

### Steps to reproduce

Have a 512x512 tileset, scale it to 0.5, 0.5

Attach a script to your tileset, and run the following code: 
	self.path_start_position = world_to_map(to_local(Vector2(512, 255)))
	self.path_end_position = world_to_map(to_local(Vector2(512, 256)))

The return values should be (2,0) for the first one, but I get back (0, 0)

**Comment by Calinou** [comment]
@LakshayaG73 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by LakshayaG73** [comment]
Funnily enough, I created a test project and couldn't reproduce it. 

Then I tested again and seems like there was a rogue setter changing the value. Closing this, sorry for confusion.
