### ISSUE TITLE
Screen-space reflections have a visible line between the reflected object and the reflection, unless Fade In is exactly 0

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#50916]
### Godot version

3.3.2.stable (does not apply to 4.0.dev due to different algorithm)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

Screen-space reflections have a visible line between the reflected object and the reflection, unless Fade In is exactly 0.

I originally reported this [here](https://github.com/godotengine/godot/pull/28502#issuecomment-500243508), and I just found a workaround by setting **Fade In** to *exactly* 0.0.

### No visible line

***Fade In** is set to 0.0 by right-clicking the curve and choosing the Zero preset.*

![2021-07-26_23 29 46](https://user-images.githubusercontent.com/180032/127066053-3ed35c9c-b8b4-4648-af63-ef73bc95dd00.png)

### Visible line (default behavior, also seen with the default Fade In = 0.15)

***Fade In** is set to a very low positive value, displayed as 0.0 in the inspector (but not actually 0.0).*

![2021-07-26_23 29 54](https://user-images.githubusercontent.com/180032/127066056-109165df-135c-4a40-aafa-9d2a263c6f65.png)

### Steps to reproduce

- Create a scene with a non-rough, metallic plane to reflect other objects that are touching the plane.
- Enable screen-space reflections in a WorldEnvironment node's Environment resource.
- Look at intersections between objects and the reflective plane.

### Minimal reproduction project

[test_ssr_resolution_3.x.zip](https://github.com/godotengine/godot/files/6881423/test_ssr_resolution_3.x.zip)

**Comment by clayjohn** [comment]
This is what "fade in" does. It fades the effect in where the collision is very close to the reflecting surface. 

IMO this is a documentation issue. To have sharp reflections in corners like this "fade in" should be set to 0

**Comment by Calinou** [comment]
> This is what "fade in" does. It fades the effect in where the collision is very close to the reflecting surface.

I still think there might be a rounding error somewhere, as it results in a disgracious-looking curve that may look better if it wasn't there. The subtle fade-in is nice to have, but you can't have it without having that sharp line at the intersection.
