### ISSUE TITLE
The linked library 'iOSTest.a' is missing one or more architectures required by this target: armv7.

### ISSUE THREAD

**Issue by gumaciel** [godotengine/godot#50921]
### Godot version

3.3.2 stable

### System information

Mac OS, GLES 3, Catalina 10.15.7

### Issue description

When exporting for iOS, building for armv7 doesn't work anymore on 3.3.2 stable version.

Obs: The PrintScreen have more errors but just ignore it.
![Captura de Tela 2021-07-26 às 23 02 54](https://user-images.githubusercontent.com/20030153/127083621-dec99edc-2a9f-45be-9dcb-017cd9fff4b6.png)

### Steps to reproduce

1. Create a simple project
2. Export for iOS
3. Try to build

### Minimal reproduction project

[iOSTest.zip](https://github.com/godotengine/godot/files/6882166/iOSTest.zip)

**Comment by akien-mga** [comment]
That's expected, what iOS armv7 device is still compatible with the Apple Store? We don't distribute armv7 binaries anymore.

CC @godotengine/ios

**Comment by akien-mga** [comment]
I guess the only 32-bit devices which might still be relevant might be some of the iPads running iOS < 11. I don't know if they can still access the Apple Store though. https://david-smith.org/iosversionstats/

Either way, if you wish to target armv7 device, you need to compile the export template manually from the Godot source code using https://docs.godotengine.org/en/stable/development/compiling/compiling_for_ios.html (with `arch=arm`). We no longer provide these binaries as Apple ended support for 32-bit iOS devices more than 4 years ago.
