### ISSUE TITLE
[Godot4] shader param not effect

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#50936]
### Godot version

v4.0.dev.calinou [e6a544c16]

### System information

Window10

### Issue description

shader param not effect

### Steps to reproduce

run reproduction project
![333](https://user-images.githubusercontent.com/35988767/127145169-7a04610d-3e26-4cfc-b5a6-cc7eb6cc2517.gif)

### Minimal reproduction project

[ShaderParamTest.zip](https://github.com/godotengine/godot/files/6884947/ShaderParamTest.zip)

**Comment by Chaosus** [comment]
Seems like all shader uniforms are broken due to recent rendering changes. cc @reduz (I'm not very familiar with rendering Vulkan API)

**Comment by darrylryan** [comment]
Same problem here I think... I've got a shader that samples a heightmap and its just showing flat now.

**Comment by Ace-Dragon** [comment]
Just to toss my hat in the ring, can also confirm using Nvidia Studio drivers for Windows 10. It is not possible to make shaders with custom uniforms with the latest builds.

**Comment by Calinou** [comment]
@darrylryan @Ace-Dragon Could you try to [bisect the regression](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html) to see when the issue started happening?

**Comment by darrylryan** [comment]
So far I've narrowed it to:

cf3f404d312146cf46ae27fd8d220852eac27eb9 bad
c25fa02c1c242df0f256dd58af650f8c8806c066 good

**Comment by Chaosus** [comment]
> cf3f404

I think it's not correct - if you revert this commit in the current branch it is still incorrectly setup uniform.

**Comment by darrylryan** [comment]
96d7bc62af25b85b8b9cc091eeea1e7a784ba624 seems to be the one that breaks it for me... the previous commit my heightmap image is sampled correctly by the shader, with this one in the terrain is just flat.
