### ISSUE TITLE
Vulkan: LightmapGI Bounce Indirect Energy property not implemented (unlike BakedLightmap in `3.x`)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#50938]
### Godot version

4.0.dev (7bd7b8f5e)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

This issue is a reminder to implement https://github.com/godotengine/godot/pull/50827 in the `master` branch's GPU lightmapper.

If you are reading this and want to give it a try, feel free to open a pull request to reimplement it :slightly_smiling_face:
Just leave a comment to let other people know, or to ask questions about the implementation.

Remember that this property should affect indirect lighting energy (bounced light) only. It should **not** affect direct light (when the light's bake mode is set to **All**) and emissive materials' lighting.

### Steps to reproduce

- Create a LightmapGI node in the `master` branch.
- Select the node and look for a Bounce Indirect Energy property.

### Minimal reproduction project

N/A

**Comment by BlueCube3310** [comment]
Fixed by #82068, I think this should be closed to avoid cluttering the tracker.
