### ISSUE TITLE
Godot 4 - error opening a tscn file

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#50934]
### Godot version

v4.0.dev.calinou [e6a544c16]

### System information

Win 10 64, AMD RX 480

### Issue description

When i try to open scene file after the auto reimport of file i get an alert message: scene file appears to be corrupt invalid.

>   Failed loading resource: res://sci-fi-hangar-door.lmbake. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:170 - res://sci-fi-hangar-door.tscn:114 - Parse Error: [ext_resource] referenced non-loaded resource at: res://sci-fi-hangar-door.lmbake
  scene/resources/resource_format_text.cpp:269 - res://sci-fi-hangar-door.tscn:114 - Parse Error: [ext_resource] referenced non-loaded resource at: res://sci-fi-hangar-door.lmbake
  servers/rendering/renderer_rd/renderer_storage_rd.cpp:1547 - Condition "!material" is true.
  Failed loading resource: res://sci-fi-hangar-door.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:539 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
``

### Steps to reproduce

Just double click on the tscn file.

**Comment by Calinou** [comment]
@Akira1San Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Akira1San** [comment]
link: https://drive.google.com/file/d/1UZ2j1MQGTcBk0t-HIGxL1WPnynms4GrB/view?usp=sharing

**Comment by Blackiris** [comment]
On the latest 4.0 version (9d9161c71956201875334b6a2a9ca37a7d5d3970), just delete the hidden folder .godot to force ressource reloading. For me it just works after that. This was due to a recent binary loading change (more info here #51042).

**Comment by Akira1San** [comment]
Thx, it works now.

**Comment by SimoneStarace** [comment]
> On the latest 4.0 version ([9d9161c](https://github.com/godotengine/godot/commit/9d9161c71956201875334b6a2a9ca37a7d5d3970)), just delete the hidden folder .godot to force resource reloading. For me it just works after that. This was due to a recent binary loading change (more info here #51042).

I tried to do the same with my project, which I have linked on this issue https://github.com/godotengine/godot/issues/77007#issuecomment-1722426620, but it didn't solved my problem.

I'm using Godot stable version 4.1.1

**Comment by SnowriterMYX** [comment]
I also encountered the same problem

**Comment by SimoneStarace** [comment]
> I also encountered the same problem

In my case, I have solved the problem by doing this https://github.com/godotengine/godot/issues/77007#issuecomment-1722438624
