### ISSUE TITLE
Unreliable signal emission or callback with C# in 3.4 beta 2

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#50947]
### Godot version

3.4 beta 2 mono

### System information

w10 64

### Issue description

I don't know how I can explain this, it just breaks the game when the character collides with the enemy.
Line 218 is never printed.
If I don't "Connect" line 398 then the collision doesn't happen, obviously, so I guess there is some bug with the collision, this worked perfectly in 3.3.2 stable mono.
![Captura](https://user-images.githubusercontent.com/19652075/127196288-39121315-33b0-4c7c-a9b0-5aaf0108ffee.PNG)

### Steps to reproduce

...

**Comment by Torguen** [comment]
If I comment this line the error does not happen, however, the print "from setter of life" is never printed on the screen ... I do not understand it.
![Captura](https://user-images.githubusercontent.com/19652075/127198011-2379d9ee-5e99-484f-899b-86ecf72132b7.PNG)

**Comment by Calinou** [comment]
@Torguen Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Torguen** [comment]
I can't find the exact point, just when I comment on some seemingly unrelated lines, the error doesn't happen ... I can't specify but the error is there.

**Comment by Torguen** [comment]
Where I have gone the furthest seems to be something related to "await ToSignal(...)"

**Comment by Torguen** [comment]
3.3.3 RC 1 and this problem is still unsolved and not even tested?
I think I will not be able to use 3.3.3 stable with this problem.

**Comment by Torguen** [comment]
Hi, this seems to work correctly in 3.4 beta 5 mono.
Have you changed any code that has to do with this matter?

**Comment by Torguen** [comment]
For some reason this works fine in 3.4 beta 5 mono
