### ISSUE TITLE
Shader code: using global varying in function is broken

### ISSUE THREAD

**Issue by sash-rc** [godotengine/godot#50953]
### Godot version

3.4-beta2

### System information

Linux Ubuntu 20.04

### Issue description

```shader
shader_type spatial;

varying vec3 outer_vec;

void test() {
  vec3 local_vec = outer_vec; // error(6)
}
```
Shaders are no more happy when global `varying` is referenced anywhere in functions.
Godot throws error "error(L)". L - is a line number.

3.3 stable works.

### Steps to reproduce

Just any shader as described above. Both in editor and runtime.

**Comment by akien-mga** [comment]
Fixed by #50963.
