### ISSUE TITLE
AudioStreamPlayer2D doesn't play any audio when played

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50958]
### Godot version

v4.0.dev.custom_build [78f0d2d1d]

### System information

Windows 10

### Issue description

`AudioStreamPlayer2D` doesn't play any sound at all when played through `autoplay` or `play()`.
`AudioStreamPlayer3D` and `AudioStreamPlayer` work fine.
I tested `AudioStreamPlayer2D` in `v3.4.beta2.official` and it worked fine.

### Steps to reproduce

- Make an `AudioStreamPlayer2D` in a 2D scene
- Play it with `autoplay` or `play()`
- Won't make any sound

### Minimal reproduction project

[AudioStreamPlayer2D not working.zip](https://github.com/godotengine/godot/files/6889270/AudioStreamPlayer2D.not.working.zip)

**Comment by Calinou** [comment]
Confirmed by @ellenhp on Rocket.Chat.

**Comment by ellenhp** [comment]
Looks like this was a regression caused in 38d164c74b24f10215312f304ec1b04175989376

**Comment by ellenhp** [comment]
There's a workaround for this bug in #51296, so at least for simple 2d scenes you should be able to hear audio again. But this isn't fixed. Whenever it does finally get fixed, we'll be able to remove a TODO in `AudioStreamPlayer2D::_update_panning()` about this bug.

**Comment by git2013vb** [comment]
I have similar issue in v3.4.beta4.mono.official [6a058cbf3]  - Debian 11
When  use  `AudioStreamPlayer` my code work.
If I change the type in either `AudioStreamPlayer2D` or `AudioStreamPlayer3D` it not make any sound.

**Comment by ellenhp** [comment]
That seems more likely to be an issue with the way spatial audio is calculated than this specific bug. Just to confirm, have you added a Camera2D/Camera3D to your scene? If so, is it marked as `current` in the inspector and nearby to your audio source?

**Comment by git2013vb** [comment]
I have a Camera2D.. In the future I have to add another. What the catch?

**Comment by ellenhp** [comment]
Interesting. Could you create a [minimal reproduction project in 3.4 that reproduces the issue, and then create a new issue](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs) so I can look into this more? If you have a camera very close to the player that is set to current then you should hear audio as long as the source is nearby to the camera. This might be a new bug.

This issue (#50958) is specific to 4.0 though, so I'd prefer to discuss in a new bug. Feel free to ping me `@ellenhp` in the bug so I see it.

**Comment by foxydevloper** [comment]
Appears to be fixed as of v4.0.alpha.calinou [c80540f9a]

**Comment by KoBeWi** [comment]
It's not fixed, it's worked around:
https://github.com/godotengine/godot/blob/8c729f0f34a92b92a1a8204e1d56b6ad05cfd27b/scene/2d/audio_stream_player_2d.cpp#L160
I assume it's the same issue as #76634
