### ISSUE TITLE
ERROR: Attempted to free invalid ID - on Project Manager opening

### ISSUE THREAD

**Issue by MHillier98** [godotengine/godot#50969]
### Godot version

v4.0.dev.official

### System information

Windows 10, Vulkan, Ryzen 7 3700X, NVIDIA RTX 3080

### Issue description

Launched the dev preview @akien-mga tweeted out, and got the following error when launching the project manager.
```
ERROR: Attempted to free invalid ID: 2100239007746
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8313)

```

### Steps to reproduce

Download and run the dev build linked from this tweet: https://twitter.com/Akien/status/1420309040584929286

**Comment by bruvzg** [comment]
Seems like it's calling `free` from the wrong RID owner.

```diff
diff --git a/servers/rendering/renderer_rd/renderer_compositor_rd.cpp b/servers/rendering/renderer_rd/renderer_compositor_rd.cpp
index a7ee0dd141..02d548bf13 100644
--- a/servers/rendering/renderer_rd/renderer_compositor_rd.cpp
+++ b/servers/rendering/renderer_rd/renderer_compositor_rd.cpp
@@ -222,7 +222,7 @@ void RendererCompositorRD::set_boot_image(const Ref<Image> &p_image, const Color
 
 	RD::get_singleton()->swap_buffers();
 
-	RD::get_singleton()->free(texture);
+	storage->free(texture);
 }
 
 RendererCompositorRD *RendererCompositorRD::singleton = nullptr;
```
 Not sure if it's a correct fix.

**Comment by Calinou** [comment]
I can confirm this on b5b633ff5 (Linux).

**Comment by qarmin** [comment]
The patch from above fixed message and memory leak

**Comment by akien-mga** [comment]
The texture is allocated with `RID texture = storage->texture_allocate();` so I think the patch is correct.

**Comment by caniko** [comment]
I am also getting this error. I am on build d42652344 on v4.0.
```
E 0:00:04:0816   _free_internal: Attempted to free invalid ID: 2100239007746
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:8313 @ _free_internal()
```
