### ISSUE TITLE
Font Import Plug-in Discrepancy.

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#5097]
When a large path to a font file is present the options box is crammed into an unusable section on the window making it unusable. If this bug is present here it might also be present in other parts of the editor. 

Visual of the Problem:
![](https://s-media-cache-ak0.pinimg.com/originals/5a/57/b3/5a57b33da22a53efdb870928b0297d57.png)

**Comment by vnen** [comment]
Since #5082 was reverted by #5098, then this is valid again.
