### ISSUE TITLE
PathFollow with RotationMode = Oriented is wrong at unit_offset = 1.0

### ISSUE THREAD

**Issue by MikeFrom** [godotengine/godot#50973]
### Godot version

3.3.2.stable

### System information

Windows 10

### Issue description

 This seams to work, from unit_offset 0.0 to 0.999, the z-axis of the PathFollow is aligned to the Path correctly. But at unit_offset 1.0 suddenly the x-axis is aligned to the path. This seams like a bug.

### Steps to reproduce

Play the Project: At unit_offset = 1 the rotation is wrong.

![PathFollow_Bug_Example](https://user-images.githubusercontent.com/50963378/127332048-a93614f3-0c60-4d9f-809a-7dad1295e797.gif)

### Minimal reproduction project

Here a simple Godot 3.3.2.stable project, which shows the bug: 

[Godot_3_3_2_stable_PathFollow_Bug_Example.zip](https://github.com/godotengine/godot/files/6893776/Godot_3_3_2_stable_PathFollow_Bug_Example.zip)

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/issues/48864 says this only happens when the rotation mode is set to XYZ, not Oriented.

**Comment by MikeFrom** [comment]
Another note: When you switch rotation_mode to Y, XY, or XYZ, the rotation works for the first pass. But when you repeat the PathFollow movement, the rotation is always added, and is also buggy. You can try this with my project and switching e.g. to XYZ.

PathFollow is so essential and important, that I hope you fix first PathFollow, before you add some fancy Godot 4.0 features. Thank you.

**Comment by Calinou** [comment]
> PathFollow is so essential and important, that I hope you fix first PathFollow, before you add some fancy Godot 4.0 features. Thank you.

Bugs in existing nodes are fixed by contributors on a best-effort basis. There are [many other bugs in PathFollow](https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+pathfollow+label%3Abug) right now, and few contributors to help on this.

**Comment by MikeFrom** [comment]
I would like to help, but I am not the C++, and Bezier expert. Can I donate/vote for a working PathFollower?

I have done some tests with the Rotation modes of PathFollow. They seam so buggy (for years?), that noone can use them successfully.

I think I have to write my own rotation/tangent code for curves, started here:
https://godotengine.org/qa/111365/curve3d-how-to-get-the-direction-at-a-given-point

**Comment by Calinou** [comment]
> Can I donate/vote for a working PathFollower?

Due to how Godot's development works, there is no way to donate or vote to specific features to be fixed.

**Comment by MikeFrom** [comment]
Thanks
