### ISSUE TITLE
Godot 4 errors in exported debug file and  gpu driver crash in editor after some time

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#50978]
### Godot version

v4.0.dev.calinou [78f0d2d1d]

### System information

Win 10 64, AMD RX 480

### Issue description

While Testing "Godot 4.0 AAA Graphics? "The Junk Shop" after exporting the project to an debug exe some spam errors show up(some of them are known). I did disable the enviro effects and lowered some other to increase the fps.

godot log:

> ERROR: Attempted to free invalid ID: 2100239007746
>    at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8313) - Attempted to free invalid ID: 2100239007746
> CORE API HASH: 13245607664466767104
> EDITOR API HASH: 358842281
> Loaded builtin certs
> Using present mode: VK_PRESENT_MODE_FIFO_KHR
> ERROR: Attempted to use an unused shader variant (shader is null),
>    at: get_render_pipeline (./servers/rendering/renderer_rd/pipeline_cache_rd.h:75) - Condition "shader.is_null()" is true. Returning: RID()
> ERROR: Condition "!pipeline" is true.
>    at: draw_list_bind_render_pipeline (drivers/vulkan/rendering_device_vulkan.cpp:7078) - Condition "!pipeline" is true.
> ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
>    at: draw_list_draw (drivers/vulkan/rendering_device_vulkan.cpp:7285) - Condition "dl->validation.pipeline_vertex_format != dl->validation.vertex_format" is true.
> Project FPS: 1 (1000.0 mspf)
> ERROR: Condition "!rb" is true. Returning: false
>    at: render_buffers_has_volumetric_fog (servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:2211) - Condition "!rb" is true. Returning: false
> ERROR: Attempted to use an unused shader variant (shader is null),
>    at: get_render_pipeline (./servers/rendering/renderer_rd/pipeline_cache_rd.h:75) - Condition "shader.is_null()" is true. Returning: RID()
> ERROR: Condition "!pipeline" is true.
>    at: draw_list_bind_render_pipeline (drivers/vulkan/rendering_device_vulkan.cpp:7078) - Condition "!pipeline" is true.
> ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
>    at: draw_list_draw (drivers/vulkan/rendering_device_vulkan.cpp:7285) - Condition "dl->validation.pipeline_vertex_format != dl->validation.vertex_format" is true.
> Project FPS: 1 (1000.0 mspf)
> ERROR: Condition "!rb" is true. Returning: false
>    at: render_buffers_has_volumetric_fog (servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:2211) - Condition "!rb" is true. Returning: false
> ERROR: Condition "!pipeline" is true.
>    at: draw_list_bind_render_pipeline (drivers/vulkan/rendering_device_vulkan.cpp:7078) - Condition "!pipeline" is true.
> ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
>    at: draw_list_draw (drivers/vulkan/rendering_device_vulkan.cpp:7285) - Condition "dl->validation.pipeline_vertex_format != dl->validation.vertex_format" is true.
> ERROR: Attempted to use an unused shader variant (shader is null),
>    at: get_render_pipeline (./servers/rendering/renderer_rd/pipeline_cache_rd.h:75) - Condition "shader.is_null()" is true. Returning: RID()
> ERROR: Condition "!pipeline" is true.
>    at: draw_list_bind_render_pipeline (drivers/vulkan/rendering_device_vulkan.cpp:7078) - Condition "!pipeline" is true.
> ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
>    at: draw_list_draw (drivers/vulkan/rendering_device_vulkan.cpp:7285) - Condition "dl->validation.pipeline_vertex_format != dl->validation.vertex_format" is true.
> ERROR: Condition "!material" is true.
>    at: material_update_dependency (servers/rendering/renderer_rd/renderer_storage_rd.cpp:1682) - Condition "!material" is true.
> ERROR: Attempted to free invalid ID: 0
>    at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8313) - Attempted to free invalid ID: 0
> ERROR: Attempted to free invalid ID: 0
> ERROR: 1 RID allocations of type 'N17RendererStorageRD7TextureE' were leaked at exit.
> WARNING: 1 RID of type "UniformBuffer" was leaked.
>    at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8836) - 1 RID of type "UniformBuffer" was leaked.
> WARNING: 1 RID of type "VertexArray" was leaked.
>    at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8836) - 1 RID of type "VertexArray" was leaked.
> WARNING: 6 RIDs of type "Texture" were leaked.
>    at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9055) - 6 RIDs of type "Texture" were leaked.
> ERROR: Condition "p_ptr == nullptr" is true.
>    at: free_static (core/os/memory.cpp:148) - Condition "p_ptr == nullptr" is true.
> ERROR: Condition "p_ptr == nullptr" is true.
>    at: free_static (core/os/memory.cpp:148) - Condition "p_ptr == nullptr" is true.
> StringName: 19 unclaimed string names at exit.

Also by testing the project once by playing or just in the editor my AMD gpu driver crash.
one more log from the previously night build:

> ERROR: Condition "!rb" is true. Returning: false
>    at: render_buffers_has_volumetric_fog (servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:2094) - Condition "!rb" is true. Returning: false
> ERROR: Condition "!rb" is true. Returning: false
>    at: render_buffers_has_volumetric_fog (servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:2094) - Condition "!rb" is true. Returning: false
> ERROR: Condition "!rb" is true. Returning: false
>    at: render_buffers_has_volumetric_fog (servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:2094) - Condition "!rb" is true. Returning: false
> Project FPS: 22 (45.4 mspf)
> Project FPS: 24 (41.6 mspf)
> Project FPS: 42 (23.8 mspf)
> Project FPS: 49 (20.4 mspf)
> ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
>    at: swap_buffers (drivers/vulkan/vulkan_context.cpp:1856) - Condition "err" is true. Returning: ERR_CANT_CREATE
> ERROR: vmaMapMemory failed with error -5.
>    at: _buffer_update (drivers/vulkan/rendering_device_vulkan.cpp:1602) - Condition "vkerr" is true. Returning: ERR_CANT_CREATE
> ERROR: vmaMapMemory failed with error -5.
>    at: _buffer_update (drivers/vulkan/rendering_device_vulkan.cpp:1602) - Condition "vkerr" is true. Returning: ERR_CANT_CREATE
> ERROR: vmaMapMemory failed with error -5.
>    at: _buffer_update (drivers/vulkan/rendering_device_vulkan.cpp:1602) - Condition "vkerr" is true. Returning: ERR_CANT_CREATE
> ERROR: vmaMapMemory failed with error -5.
>    at: _buffer_update (drivers/vulkan/rendering_device_vulkan.cpp:1602) - Condition "vkerr" is true. Returning: ERR_CANT_CREATE
> ERROR: vmaMapMemory failed with error -5.
>    at: _buffer_update (drivers/vulkan/rendering_device_vulkan.cpp:1602) - Condition "vkerr" is true. Returning: ERR_CANT_CREATE
> ERROR: vmaMapMemory failed with error -5.

### Steps to reproduce

...

### Minimal reproduction project

https://github.com/everythingandnothingdev/godot-blender-2.81-splash

**Comment by clayjohn** [comment]
Do you still get these errors? I believe most have been fixed by now

**Comment by Akira1San** [comment]
I forgot about the old issue. I think its fixed, while i did delete the gi node before the rc1, cos when i select it, it spams, but after that no spam errors.

**Comment by akien-mga** [comment]
Thanks, closing as fixed.
