### ISSUE TITLE
Vulkan: Errors related to gaussian blur when using `textureLod(SCREEN_TEXTURE, ...)` in a shader

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#50976]
### Godot version

v4.0.dev.calinou [e6a544c16]

### System information

windows 10

### Issue description

shader in editor use SCREEN_TEXTURE no any effect and, once run the scene, it will report error
`Can't use the compute version of the gaussian blur with the mobile renderer.` 

![444](https://user-images.githubusercontent.com/35988767/127343232-5cf3199e-4c6c-4c54-ac1d-1d4402f28118.gif)
In 3.3.2, it right:
![捕获](https://user-images.githubusercontent.com/35988767/127343382-96e2bc18-dbad-45d1-9f9d-c7a55fa73a52.PNG)

### Steps to reproduce

please run the reproduction project

### Minimal reproduction project

[ScreenTexTest.zip](https://github.com/godotengine/godot/files/6893997/ScreenTexTest.zip)

**Comment by Calinou** [comment]
> As far I've understood this happens only on `canvas_item` shaders, yesterday I tried `spatial` and this doesnt happens!

It seems gaussian mipmap generation isn't correctly reimplemented in `master` yet: https://github.com/godotengine/godot-proposals/issues/3231

**Comment by unfa** [comment]
I have the same issue using Screen texture in a 2D Canvas Visual Shader.

**Comment by nonunknown** [comment]
@Calinou not sure it its only 2d related, because In my use case, I'm using canvas_item to modify the 3d environment!

**Comment by Calinou** [comment]
> @Calinou not sure it its only 2d related, because In my use case, I'm using canvas_item to modify the 3d environment!

It is still related to 2D rendering, as the errors only occur in `canvas_item` shaders, not `spatial` shaders.

**Comment by jimbeauphloyd** [comment]
> > As far I've understood this happens only on `canvas_item` shaders, yesterday I tried `spatial` and this doesnt happens!
> 
> It seems gaussian mipmap generation isn't correctly reimplemented in `master` yet: [godotengine/godot-proposals#3231](https://github.com/godotengine/godot-proposals/issues/3231)

If I do just a texture lookup on a regular texture (not the screen texture), I don't get errors, but I do get a blurry screen. I guess the blurriness is related to this issue since it has to do with gaussian mipmap generation? Should I open a separate ticket for the blurriness since it isn't getting errors, it just isn't pixel perfect?
Shader code:

```
shader_type canvas_item;

uniform sampler2D tilemap_texture : hint_albedo;

void fragment() {
	COLOR = texture(tilemap_texture, UV);
}
```
Image Example: https://imgur.com/a/FNj1JOe

**Comment by Calinou** [comment]
> If I do just a texture lookup on a regular texture (not the screen texture), I don't get errors, but I do get a blurry screen. I guess the blurriness is related to this issue since it has to do with gaussian mipmap generation? Should I open a separate ticket for the blurriness since it isn't getting errors, it just isn't pixel perfect?

Indeed, please open a separate issue for this (then I'll close https://github.com/godotengine/godot-proposals/issues/3231).

**Comment by jimbeauphloyd** [comment]
> > If I do just a texture lookup on a regular texture (not the screen texture), I don't get errors, but I do get a blurry screen. I guess the blurriness is related to this issue since it has to do with gaussian mipmap generation? Should I open a separate ticket for the blurriness since it isn't getting errors, it just isn't pixel perfect?
> 
> Indeed, please open a separate issue for this (then I'll close [godotengine/godot-proposals#3231](https://github.com/godotengine/godot-proposals/issues/3231)).

Thanks, submitted issue: #55755

**Comment by saki7** [comment]
https://github.com/godotengine/godot/blob/91b97dac03996c4b8791633ea6fa8fdc47852cb6/servers/rendering/renderer_rd/effects_rd.cpp#L448-L449

In case of non-raster effect implementation, the error condition must be `prefer_raster_effects`, not `!prefer_raster_effects`.

Similar codes:

https://github.com/godotengine/godot/blob/91b97dac03996c4b8791633ea6fa8fdc47852cb6/servers/rendering/renderer_rd/effects_rd.cpp#L483-L484

https://github.com/godotengine/godot/blob/91b97dac03996c4b8791633ea6fa8fdc47852cb6/servers/rendering/renderer_rd/effects_rd.cpp#L519-L520

I guess there's nothing wrong with the graphic implementation itself, it should be an error output mistake. The error message is being shown on the inverted condition, so if we could flip the flag, then we could get rid of those false-positives. 

For reference, I think it is a copy-and-paste error which was introduced in this commit: https://github.com/godotengine/godot/commit/1f695828351dd51a86ab1499176a1edbab273cc8#diff-cff00d5ca58d233af4e4590bfa182d3f6a10b10e9f9aaecbd6e8907efc259fba

@BastiaanOlij As the commit author, could you confirm that this is the valid solution?

**Comment by unfa** [comment]
I am having the same problem when using Visual Shader:
![image](https://user-images.githubusercontent.com/491704/149252214-981b6c6b-1195-477f-a60c-7df3e0784f9f.png)

Minimal reproduction project:
[Test Project.zip](https://github.com/godotengine/godot/files/7859245/Test.Project.zip)

Changing the texture type from Screen will stop the error flood.

```
Can't use the compute version of the gaussian blur with the mobile renderer.
```

The project is using the Clustered renderer, and also I am not using gaussian blur anywhere.

**Comment by wizcas** [comment]
Hey guys 👋 I still encounter this error in build `v4.0.beta2.mono.official [f8745f2f7]`. Is the merged PR not included in the latest release, or shall I request for reopening this issue?

**Comment by akien-mga** [comment]
This was fixed in January, it would be better to open a new issue if a new bug with the same symptoms reappeared. The cause and fix are likely different.
