### ISSUE TITLE
Near DOF regression from single-pass approach in 3.4beta2

### ISSUE THREAD

**Issue by drcd1** [godotengine/godot#50987]
### Godot version

3.4 beta 2

### System information

Windows 10, GLES3

### Issue description

There is a downgrade in Near DOF rendering in 3.4 beta 2, compared to 3.3.2. 
When blurred, the foreground no longer bleeds to the mid/background.

I think the problem is that, since near DOF works as a scatter operation, you can't just ignore pixels that are in focus, because the foreground should "bleed" to the background, so even pixel that are in focus may receive samples from nearby points in the foreground.

You can see the downgrade in the attached minimal reproduction project, as well as in these comparison screenshots.

Left is 3.3.2, right is 3.4 beta 2

![compare1](https://user-images.githubusercontent.com/22733172/127388452-780afe59-4060-45f1-bb19-c22c2ef08338.png)

![compare2](https://user-images.githubusercontent.com/22733172/127388474-045b800d-b878-48c2-bb13-30c9f5fe0e16.png)

Notice how the small cubes or the leaves are no longer properly blurred over the foreground.

This is most likely caused by https://github.com/godotengine/godot/pull/50723, since "in-focus" pixels are no longer blurred.

### Steps to reproduce

Turn on Near DOF, and notice how the foreground doesn't bleed into the mid/background.

### Minimal reproduction project

[MinimalDOF.zip](https://github.com/godotengine/godot/files/6896160/MinimalDOF.zip)

**Comment by BastiaanOlij** [comment]
Ai, yeah I missed that, you learn something every day... I'll see if I can still make the combined solution work.. 
Thanks for testing this!

**Comment by akien-mga** [comment]
Fixed by #51281.
