### ISSUE TITLE
The following project settings does not specify the version of godot through which it was created.

### ISSUE THREAD

**Issue by kuchishima** [godotengine/godot#50980]
### Godot version

3.2.3.stable

### System information

Windows 10, 8gb ram, GTX 1050 Ti, I5 Intel Core

### Issue description

When a project is created in Godot, some other time. The project will become unnamed project and a warning message will pop out when the project is open saying **"The following project settings does not specify the version of Godot through which it was created." "If you proceed it, it will be converted to Godot's  current configuration file format."** Upon proceeding despite the warning, the scenes in the project would not be open.

### Steps to reproduce

[Knight.zip](https://github.com/godotengine/godot/files/6895247/Knight.zip)

### Minimal reproduction project

[Knight.zip](https://github.com/godotengine/godot/files/6895230/Knight.zip)

**Comment by Calinou** [comment]
> 3.2.3.stable

Godot 3.2.x is no longer supported. Please upgrade to Godot 3.3.2 or later.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
