### ISSUE TITLE
Confusing Portal gizmo Z size

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#50996]
### Godot version

3.4.beta2, 3.x (5d4352f)

### System information

macOS 11.4

### Issue description

The Portal node has a gizmo of a red box.

![portal](https://user-images.githubusercontent.com/372476/127438917-92b120bb-90b8-481f-83d0-7447f8556b0f.png)

X and Y size of the node matters when determine the portal size.

How the gizmo reacts to Z size (scale) changes is confusing.

* Updating the Z scale resizes the gizmo, but once another node is selected, the Z of the gizmo resets while Z scale value remain unchanged.
* Neither does the gizmo reacts to the Portal Margin property of Portal.

### Steps to reproduce

1. Create a Portal
2. Change its Z scale to 1.5, the gizmo resizes accordingly.
3. Select another node, the gizmo size resets.
4. Select the Portal again, you can see that the Z scale is still 1.5.
5. Change the Z scale to 1, the gizmo shrinks to a smaller Z size than the original.
6. Select another node, the gizmo size resets.
7. Adjust the Portal Margin, the gizmo does not change.

**Comment by lawnjelly** [comment]
I'll take a look.

For the `portal_margin` it is slightly confusing in that by default it inherits the `portal_margin` from the RoomManager, the local version is only used if `use_default_margin` is disabled. I don't know if there is a way to gray the slider out in this situation.

**Comment by akien-mga** [comment]
Fixed by #51029.
