### ISSUE TITLE
script editor caret blinking causing updates in 2D editor

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#5100]
**Operating system or device - Godot version:**
Ubuntu Linux 16.04 64b, godot d61b91c

**Issue description** (what happened, and what was expected):
When "Caret Blink" is activated for the script editor, it'll cause a redraw even if 2D/3D editor are focused.
This is a ridiculously minimal thing, admittedly, but it's kind of strange it'd produce a redraw when the script editor is completely out of sight.

**Steps to reproduce:**
Enable caret blink, go to some empty/static scene in 2D mode, it'll cause updates as if script editor was focused

**Comment by akien-mga** [comment]
CC @Paulb23.

**Comment by hetdegon** [comment]
It's strange, seems that this is recently happening again. I was getting continuous redraws in 2D editor and disabling caret blink stopped them. Could a regression have happened?
