### ISSUE TITLE
3.4.beta2.mono iOS export upload to App Store Connect fails with errors

### ISSUE THREAD

**Issue by selfsame** [godotengine/godot#51045]
### Godot version

3.4.beta2.mono.official

### System information

OSX 11.3.1

### Issue description

Xcode 12.5.1

Archiving and uploading an iOS export to App Store Connect fails with the following errors:

![image](https://user-images.githubusercontent.com/2467644/127589238-274d7f42-29dc-43fd-a3c9-14f011078018.png)

This process worked fine in 3.3.2, my guess is the export template needs to be rebuilt with the latest Xcode?

### Steps to reproduce

1. Export an iOS mono project
2. Archive project in XCode
3. Distribute archive
4. Upload to testflight (App Store Connect)

**Comment by Difference** [comment]
I have the same problem in 3.4 Beta3

**Comment by Difference** [comment]
Just tested the new beta and
v3.4.beta4.mono.official [6a058cbf3] still has this problem.

**Comment by selfsame** [comment]
still present in 3.4 beta6 mono

**Comment by neikeq** [comment]
I think a workaround for now would be to manually change these static libraries in your target frameworks list in Xcode from `Embed & Sign` to `Do Not Embed`.

**Comment by akien-mga** [comment]
Fixed by #53932.
