### ISSUE TITLE
[v3.4.beta2] Player don’t rotate along/with 3D rotating platform

### ISSUE THREAD

**Issue by Leocesar3D** [godotengine/godot#51047]
### Godot version

v3.4.beta2

### System information

Windows 10, GLES3, Geforce 1070

### Issue description

KinematicBody First Person player don’t rotate along/with the 3D platform. It worked fine in Godot v3.3.

### Steps to reproduce

Open the provided 3.4 project, run it in Godot 3.4, the player should rotate with the platform, but it doesn’t and eventually fall.
It works fine on the provided Godot 3.3 project (running on Godot 3.3), with a slight noticeable sliding.

### Minimal reproduction project

[https://drive.google.com/file/d/1UcG5onMGb56CMPEbE3u4GakjYEdV3BEf/view?usp=sharing](https://drive.google.com/file/d/1UcG5onMGb56CMPEbE3u4GakjYEdV3BEf/view?usp=sharing)

**Comment by akien-mga** [comment]
Confirmed in bab9c02f472044415845ce284c55c961402c9c7c.
