### ISSUE TITLE
CSGShape gizmo still active after deselected

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51059]
### Godot version

3.3.2, 3.x(7075bb6129)

### System information

macOS 11.4

### Issue description

After deselecting a CSG node (by CTRL-clicking the node or by clicking empty area in the scene), the CSGShape gizmo is still active (you can still see the blue overlay). Some nodes like `CSGPolygon` will hide its handles, while some nodes like `CSGBox`'s handles are still available.

The gizmo correctly disappears on `master`.

### Steps to reproduce

1. Add a CSGBox in your scene
2. Select that node
3. Deselect the node by clicking in empty space in the scene

**Comment by Calinou** [comment]
This is an issue with all editor gizmos in general.

**Comment by akien-mga** [comment]
Fixed by #67947.

**Comment by CSLRDoesntGameDev** [comment]
seems to be present again in 4.5 but not sure if that's due to my outdated build
<img width="429" height="422" alt="Image" src="https://github.com/user-attachments/assets/90e0484b-469e-4178-9166-9e21e54f6f38" />
