### ISSUE TITLE
Add 'fat' compilation option for iOS templates

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5106]
Just like was done by @marcelofg55 in #4732.

**Comment by vnen** [comment]
This should be as trivial.

**Comment by reduz** [comment]
@punto- ?

**Comment by marcelofg55** [comment]
I made this patch: https://gist.github.com/marcelofg55/9261d562b609747fc296fec0c95cd01d
I didn't test it though, if anyone can give it a try let me know if it works.

**Comment by punto-** [comment]
the iOS template already is fat, it includes both architectures, is that
what you mean?

**Comment by vnen** [comment]
@punto- recently @marcelofg55 added a `bits=fat` option for OSX. The same option should be added to iOS.

BTW, @marcelofg55 I was going to try this but for some reason I can't compile for iOS on Linux anymore. There's a missing lib or something.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by mhilbrunner** [comment]
Closing this, should be done via Xcode when building the app. Besides that, I don't see where we'd need to do something, and supporting 32 bit systems on iOS is a bit questionable in 2018 as well.
