### ISSUE TITLE
Official Microsoft Xbox Series X/S improperly mapped on Windows

### ISSUE THREAD

**Issue by SeleDreams** [godotengine/godot#51065]
### Godot version

3.4 beta 2

### System information

Windows 11 22000.100

### Issue description

I am developing a game highly based around controller.
On Windows the controller is working but getting improperly mapped axis wise which is why i had to manually map it using a tool that auto generates mapping (although i'm not sure if the analog triggers got properly mapped yet by this string because the tool didn't seem to detect them so it will need to be checked)
`Input.add_joy_mapping("03000000000000000000000000000000,Xbox Series X Controller,platform:Windows,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4",true)`

The Xbox controllers being the most popular controllers on the market, I feel like having good support for them out of the box would be important

this is my configuration
![image](https://user-images.githubusercontent.com/16335601/127657774-9f6c0ff1-f23c-4f29-ad9a-796066169ece.png)

### Steps to reproduce

Create a project on Godot 3.4 and below
Assign controller input to it and use an Xbox Series X/S controller
Controller input doesn't work as intended

**Comment by Calinou** [comment]
> this is my configuration, to make sure it wasn't the fingerprint reader interfering i've set everything to "all devices" rather than device 0 but it still doesn't work

For the record, this is tracked in https://github.com/godotengine/godot/issues/47656.

**Comment by SeleDreams** [comment]
After checking the android part was fixed after re-pairing the controller to the phone which was weird, however the bad config out of the box could be fixed before the release of 3.4 i think by updating the sdl mapping

**Comment by akien-mga** [comment]
The mapping should be contributed to https://github.com/gabomdq/SDL_GameControllerDB if it's missing (that's where we source ours).

**Comment by SeleDreams** [comment]
i might do it once i'll be sure about my mapping, i'm not sure mine includes the analog triggers so i'll have to check

**Comment by Calinou** [comment]
There are many Xbox Series controllers in the current database: https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

(Ctrl+F for "Xbox Series")

**Comment by SeleDreams** [comment]
> There are many Xbox Series controllers in the current database already: https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt
> 
> (Ctrl + F for `Xbox Series`)

are they already imported in godot ? because if yes the blue controller might either be a new variant either the firmware got updated and changed stuff

**Comment by Calinou** [comment]
> are they already imported in godot ? because if yes the firmware got updated and changed stuff

You can check here: https://github.com/godotengine/godot/blob/3.x/main/gamecontrollerdb.txt

**Comment by SeleDreams** [comment]
the number seems to be the same
![image](https://user-images.githubusercontent.com/16335601/127661589-b4d1d266-8717-435e-ac1b-6a91f01721c5.png)
what i find interesting is that even the sdl2 mapping tool isn't able to detect the triggers when i press them and stays stuck at the step when we need to press it

**Comment by SeleDreams** [comment]
what i find interesting is the way it gets identified
"03000000000000000000000000000000"
i doubt it's normal that it litterally has only one actual number in its ID the rest being 0s

**Comment by akien-mga** [comment]
Yeah that's not a valid mapping, the mapping tool seems not to support it either. First time I see that.

**Comment by SeleDreams** [comment]
Ok so I found out the issue
the controller works in USB mode, HOWEVER in Bluetooth mode the mapping is messed up

**Comment by Calinou** [comment]
> edit: ok, so updating and re-pairing the controller seems to have fixed it as well

By "updating the controller", do you mean updating the controller's firmware using some kind of tool?

**Comment by SeleDreams** [comment]
> > edit: ok, so updating and re-pairing the controller seems to have fixed it as well
> 
> By "updating the controller", do you mean updating the controller's firmware using some kind of tool?

Yes, I used the Xbox accessories app that's on the microsoft store to update the controller's firmware
this can also be done through the xbox one and series s|x
