### ISSUE TITLE
Changing editor theme is extremely slow

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#51075]
### Godot version

4.0.dev (bdcc8741e4826ce27850bbffa5880c57451e3be5)

### System information

Windows 10

### Issue description

When applying a theme from editor settings, the editor freezes during a very long time before applying the theme (40 seconds on my configuration, in release_debug).

### Steps to reproduce

1. Open any project
2. Open `Editor > Editor Settings`
3. Go to `Interface > Theme`
4. Select a different theme in the `Preset` setting
5. Press close
6. Observe the editor freeze for a long time

### Minimal reproduction project

n/a

**Comment by Calinou** [comment]
I can confirm this on `master` b5b633ff5. It takes about 10-15 seconds on a `release_debug` build for me, which is significantly slower than in `3.x` (< 5 seconds).

**Comment by pouleyKetchoupp** [comment]
@Calinou There can be several problems, but from what I've seen the very long slowdown is due to the code editor being entirely updated each time a setting is modified, which is called many times when you switch the theme. I'm preparing a PR for this, it's not too difficult to improve.
