### ISSUE TITLE
Rotate_y property bug, 3d particles

### ISSUE THREAD

**Issue by AgeX005** [godotengine/godot#51085]
### Godot version

v3.4 beta2 official

### System information

Windows 8.1, GLES3, Nvidia GeForce GT 520 (391.35)

### Issue description

when the "rotate_Y" flag is set the particles ignore the emission shape and motion, instead they just stay in the center.

demonstration and comparison . On the left, Godot 3.3.2 official and on the right, Godot 3.4 beta 2 official.

https://user-images.githubusercontent.com/76788560/127715212-b501d495-7a0b-4151-8fb8-48410ac08f7c.mp4

### Steps to reproduce

- create a new scene.
- add a ¨particles 3d¨ node.
- set the emission shape to "box".
- in the process material set the flag "rotate_Y".
- set angular velocity to 1 

### Minimal reproduction project

[particles_bug.zip](https://github.com/godotengine/godot/files/6910123/particles_bug.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/51043.

**Comment by akien-mga** [comment]
Fixed by #51690.
