### ISSUE TITLE
Search letter-wise instead of word-wise

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#5109]
This is a usability improvement.

It is better to show search results that contain the typed "letters" instead of correctly spelled words. The working is similar to sublime text autocomplete where you don't have to type a method/property in the correct word.

For eg: 
In Godot Create Node Popup window, we can start typing "kin" to get Nodes that starts with letters "kin". It includes both KinematicBody and KinematicBody2D including their parents.
But I want to select the KinematicBody2D in the list. According to my proposal, if we type "kin2" the resulting nodes will be that contains the letters "k","i","n" and "2". So I can quickly select the node without moving my hand from keyboard to mouse.

**Comment by bojidar-bg** [comment]
In Atom, this is usually referred to as "fuzzy" search.

**Comment by vnen** [comment]
This is "officially" called "Longest Common Subsequence", which is indeed a good improvement not only for this but also for code completion. This is not so trivial though, so one should look for standard algorithms when implementing this to get better performance.

**Comment by vinod8990** [comment]
Yeah, this will certainly be very useful in code completion.

**Comment by reduz** [comment]
Oh yeah I noted down to research on this but didn't have time

**Comment by reduz** [comment]
Would be fantastic if anyone can work on it

**Comment by vnen** [comment]
It seems is not that hard (at least for dialog searches) 😆 Will try to send a PR soon, I just want to add this to every search field.

![screenshot from 2016-06-12 00-51-45](https://cloud.githubusercontent.com/assets/5599796/15988899/e02a57e4-3037-11e6-815f-c06f6b8a6056.png)

**Comment by vinod8990** [comment]
Great.
