### ISSUE TITLE
Last tree column exceeds control boundary when set to not expand

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51109]
### Godot version

4.0.dev (20d46c5)

### System information

macOS 11.4

### Issue description

`Tree`'s last column will exceed the control's boundary if set to not expand.

In editor:

![profiler](https://user-images.githubusercontent.com/372476/127743898-12263091-c949-47dc-80ef-98b80a0737c6.png)
![autoload](https://user-images.githubusercontent.com/372476/127743899-78bb663b-e9c0-453b-923c-1764b7bf3b0b.png)

In the MRP `set_column_expand(2, false)`:

![custom](https://user-images.githubusercontent.com/372476/127743901-cf022c57-456f-4e80-b033-12a47bd9b5c1.png)

This is only reproducible on `master`.

### Steps to reproduce

Open the profiler panel or run the MRP.

### Minimal reproduction project

[Tree.zip](https://github.com/godotengine/godot/files/6911357/Tree.zip)

**Comment by Calinou** [comment]
This is likely a duplicate of https://github.com/godotengine/godot/issues/50657.

**Comment by timothyqiu** [comment]
Looks related, but I'm not sure if they are the same.

It looks okay when the built-in ones are shown. The number of columns and column expand are not changed during the tree update.

**Comment by timothyqiu** [comment]
After adding a title to that button column, I think this is indeed a duplicate of #50657 😂
