### ISSUE TITLE
Deleting a Script via OS file manager or "FileSystem" panel leaves references in code even if not visibly referenced in project

### ISSUE THREAD

**Issue by spookdogg** [godotengine/godot#5110]
**Operating system or device - Godot version:**
Windows-2.0.3

**Issue description** (what happened, and what was expected):
Whenever a script is deleted from a project (not attached to a node or referenced in another script) via your OS's file manager or the delete function in the "FileSystem" panel, there are still references in the code (as whenever the project is opened up, error messages referencing the absence of the files appear) even if it was never visibly referenced in the project itself

**Steps to reproduce:**
Create a new project
Create a script and save it to the project folder
Delete script via either method
Close and reopen project
Observe the command line for errors

**Comment by bojidar-bg** [comment]
Note that this occurs because the script editor doesn't clear the reference to them.
