### ISSUE TITLE
Spaces following a Chinese character are not rendered

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51101]
### Godot version

4.0.dev (20d46c5b9e)

### System information

macOS 11.4

### Issue description

Spaces following a Chinese character are not rendered. I'm not sure if other languages also have similar problems.

There are spaces on both sides of "Android", but the left one seems missing:
![project](https://user-images.githubusercontent.com/372476/127740871-ad93f046-6dbe-48f0-966d-03b46bc4d071.png)

I typed "你好 Thank you 小笼包", but the space before "Thank" is missing:
![input](https://user-images.githubusercontent.com/372476/127740999-5cbdb3dd-304f-49f9-a59d-c2aeaada2f0f.png)

There are eight spaces between "这中间有" and "八个空格":
![multiple](https://user-images.githubusercontent.com/372476/127741094-4c7371e3-10e8-4002-a662-d09b3d25b6fd.png)

### Steps to reproduce

Type random characters in editor text boxes, or just switch to zh_CN locale and see the project menu.

**Comment by Calinou** [comment]
Does this occur in 3.3.2 or `3.x`?

**Comment by bruvzg** [comment]
Probably CJK font include zero width space glyph which is used instead of one from base font.

**Comment by timothyqiu** [comment]
> Does this occur in 3.3.2 or `3.x`?

It's only on `master`.
