### ISSUE TITLE
Determining platform from a script (improvement 2.0.x)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#5112]
It took a split of the script depending on whether it is running on any platform. As a result, it is found only "OS.get_name ()". Who also returns a string. Sometimes it is useful. But in most cases it would be necessary to function "OS.get_platform ()" that returns the number. And in the engine would be constant platforms. For example:
```
const PLATFORM_UNKNOWN = 0
const PLATFORM_ANDROID = 1
const PLATFORM_IOS = 2
const PLATFORM_OSX = 4
```
That they were flags. In this case, you can conveniently share the script depending on the target platform. For example:
```
if OS.get_platform () & (OS.PLATFORM_ANDROID | OS.PLATFORM_IOS):
```
Of course this functionality can be made to function through the statics but I would like that it was implemented in the engine.

**Comment by reduz** [comment]
Nowhere in godot a platform is harcoded, as a result you can add them and
remove them from platforms/ and they will magically work or not.
As that makes me proud and I want to keep it this way, please use the
string in OS.get_name()

**Comment by ret80** [comment]
Yes, I agree that my proposal has an advantage as well as disadvantage as constants. But the chance that someone other than you to add a platform not great. Or it will be added to the cooperation with you. And you may well be able to make one more constant. If all would do themselves and the constant will be able to add themselves. This is not a problem because the platform is rarely added. Think about it.

**Comment by punto-** [comment]
The cleanest way to solve this is with some configuration flag for whatever
you need. For example you can have this in engine.cfg

[game]
ui="res://ui/hud.scn"

[game.iOS]
ui="res://ui/hud_mobile.scn"

[game.Android]
ui="res://ui/hud_mobile.scn"

Then in your code you use load(Globals.get("game/ui")) to get the scene
with your UI, so you avoid having big branches of code that deal with
different platforms.

**Comment by ret80** [comment]
@punto- Just past the cashier! I discussed the small branch in the script depending on the platform. Do you offer support multiple scenes depending on the platform. Bad practice. I would have been to do so only in the most extreme case, if on the other does not like or what would I have different content on different platforms.

**Comment by punto-** [comment]
Ok but your branch would depend on a configuration value instead of a
platform. That way you can also test your code on PC by overriding the
config value. So in that case you would test for a flag
"game/use_mobile_platform" or something.

**Comment by ret80** [comment]
@punto- It makes no sense. Same as: ```OS.get_name()```. Although the latter is even better.

**Comment by reduz** [comment]
closing, as this won't be implemented
