### ISSUE TITLE
Document that SDFGI only works on meshes with their GI mode set to Baked

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot#51133]
### Godot version

4.0.dev (007b877cb)

### System information

Windows 10, Vulkan Clustered, RTX 3060 Ti / GTX 1650 ti

### Issue description

On my pc and laptop sdfgi still don't work on master builds. I tried clearing shader_cashe but it doesn't help.
In SDFGI Cascades rendering mode, just a black screen appears.
Probes are always black if ReadSkyLight = False, or just the colors of the sky.

![Screenshot_1](https://user-images.githubusercontent.com/54563399/127761128-fab4d920-9a4d-41dc-bc78-f72aff0c0eb1.png)
![Screenshot_2](https://user-images.githubusercontent.com/54563399/127761134-912991d9-a43b-4f57-b049-656ed93b855e.png)
![Screenshot_3](https://user-images.githubusercontent.com/54563399/127761137-da28aa1a-909b-4d36-8856-39529555a826.png)
![Screenshot_4](https://user-images.githubusercontent.com/54563399/127761140-6cd7953f-d4cb-429f-94f7-f1419d65e4db.png)
![Screenshot_5](https://user-images.githubusercontent.com/54563399/127761145-c68f35cc-ca6b-4a7c-81ec-70d1984faa5a.png)
![Screenshot_6](https://user-images.githubusercontent.com/54563399/127761148-9b2f49ee-9615-44ab-a413-d91a2eb4337c.png)
![Screenshot_7](https://user-images.githubusercontent.com/54563399/127761151-117a6b9c-d9be-485b-a8a6-ddbd5a67b711.png)

### Steps to reproduce

open sample project and enable sdfgi.

### Minimal reproduction project

https://github.com/Calinou/godot-sponza-4

**Comment by clayjohn** [comment]
Is your model set to GI mode "baked"?

**Comment by anunknowperson** [comment]
No.
![Screenshot_12](https://user-images.githubusercontent.com/54563399/127761513-86cc9c8f-6687-4cea-bd44-8a7f719fa934.png)
The same thing happens in empty projects with a couple of simple CSG models.

**Comment by mrjustaguy** [comment]
No wonder it isn't working. all models must be set to baked if they are to be creating GI. Dynamic objects only Get GI, but they don't contribute to it.

**Comment by Calinou** [comment]
Is there a difference between the **Disabled** and **Dynamic** bake modes when using SDFGI?

**Comment by mrjustaguy** [comment]
In theory I think so. Currently, I'm not sure if Dynamic objects get GI contributions from SDFGI, but Disabled shouldn't get any afaik.

**Comment by clayjohn** [comment]
Flagging for documentation. This issue has been posted multiple times because it isn't clear to users that the GI Mode needs to be set to "Baked".

**Comment by Calinou** [comment]
This is now [documented in the class reference](https://github.com/godotengine/godot/blob/09e12ba9b46934c32ffc9e178b5c6f0348de809f/doc/classes/Environment.xml#L193-L197), and [the default GI mode is now Static](https://github.com/godotengine/godot/pull/60935) (formerly Baked). Closing.

The [revamp of the global illumination documentation](https://github.com/Calinou/godot-docs/tree/revamp-gi-docs) I'm working on will also mention this on the SDFGI page.
