### ISSUE TITLE
GDScript 2.0: Lines incorrectly marked as safe

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#51142]
### Godot version

80143c9

### System information

W10

### Issue description

Apparently, all these lines are "safe":
```
extends Node2D

var text:
	set(t):
		$Label.text = t
	get:
		return $Label.text
```
The editor shouldn't know the type of $Label, because `get_node()` returns Node (and it doesn't matter if the node exists).

### Steps to reproduce

1. Paste above code.
2. See all lines being safe.

**Comment by vonagam** [comment]
This is no longer the case and can be closed, right?

**Comment by KoBeWi** [comment]
No, the last line is still considered safe for some reason.
![image](https://user-images.githubusercontent.com/2223172/214433198-8d9673b5-4884-42ca-a6ba-588689fed5ec.png)

**Comment by vonagam** [comment]
Strange, for me both are unsafe.

**Comment by KoBeWi** [comment]
Here's some minimal reproduction script
[Safe.gd.txt](https://github.com/godotengine/godot/files/10494715/Safe.gd.txt)
Tested in v4.0.beta.custom_build [a3a42159e]
