### ISSUE TITLE
Double click to create signal connection

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5116]
With the new dock with signal connections, would be interesting if a double click in a signal opened the connect window.

**Comment by reduz** [comment]
yeah and it would be nice that double clicking an existing connection would
tkae you to the code.. anyone wants to contribute this? :)

**Comment by alabd14313** [comment]
OK!

**Comment by neikeq** [comment]
I can do it, but I'm not sure if @alabd14313's "OK!" means he will do it :D

**Comment by Hinsbart** [comment]
@neikeq I actually tried it a few days ago.
I simply added a `tree->connect("item_activated", this, "_connect_pressed");` to the `ConnectionsDock` constructor. 

That worked for connects but crashed on disconnects. I didn't investigate further but maybe you can figure it out :)

**Comment by reduz** [comment]
I would just select the item and and open the connection dialog

**Comment by neikeq** [comment]
Wouldn't it be better for existing connections to open the connection editor dialog allowing to edit the connection? If going to the target method if desired, maybe it would be done with a context menu.

**Comment by akien-mga** [comment]
Or the other way around: double click goes to code, context menu allows to: edit connection; remove connection.

**Comment by reduz** [comment]
somebody make a PR :P

**Comment by neikeq** [comment]
I guess this can be closed. I proposed editing connections, but that was not really part of this issue.
