### ISSUE TITLE
CPUParticles: setting `direction.y` zeroes `direction.x` unless `direction.z` is non-zero

### ISSUE THREAD

**Issue by cptchuckles** [godotengine/godot#51162]
### Godot version

3.3.2-stable

### System information

Artix Linux 5.12.12 :: i7-9750H 16GB GeForce 1650 Max-Q :: GLES 3

### Issue description

Changing a CPUParticle's `direction.y` to anything other than zero will cause it to emit *only* along the Y-axis, even if `direction.x` is non-zero, *except* both `direction.x` and `direction.z` are non-zero.

Here is a video (link):
[![Watch the video](https://img.youtube.com/vi/l-ed1G2AnRk/hqdefault.jpg)](https://www.youtube.com/watch?v=l-ed1G2AnRk)

### Steps to reproduce

Create a CPUParticle, give it a basic mesh
Set the Direction X to something
Then change Direction Y
Observe that the particle emits exclusively on the Y-axis.
Then change Direction Z
Observe that the Direction X value is once again respected

### Minimal reproduction project

Here is the test scene from the video

`main.tscn`
```cfg
[gd_scene load_steps=2 format=2]

[sub_resource type="CubeMesh" id=1]
size = Vector3( 0.2, 0.2, 0.2 )

[node name="main" type="Spatial"]

[node name="CPUParticles" type="CPUParticles" parent="."]
mesh = SubResource( 1 )
direction = Vector3( 11.706, 0, 0 )
spread = 0.0
initial_velocity = 3.35
```

**Comment by akien-mga** [comment]
Fixed by #51565.
