### ISSUE TITLE
AnimationPlayer loses references when moved in the tree

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#51167]
### Godot version

3.3.2 stable mono

### System information

w10 64

### Issue description

I created an animation player, then I assigned an animation to it, then I moved the animationPlayer to another place in the tree, now the animation player no longer plays the animation.
I suppose that the animationPlayer memorized the place of the node involved in the animation, later, when moving the animationplayer from place in the tree, that reference remains but it does not work, the animation does not play.
![Captura](https://user-images.githubusercontent.com/19652075/127821123-737b6451-43e3-41fb-9bd1-4d2953dbe926.PNG)

### Steps to reproduce

Create a small tree of nodes.
create an animationplayer somewhere in the tree.
assign an animation that refers to one of the nodes
change the animationplayer place in the tree

**Comment by Zireael07** [comment]
Had the same problem when I moved the anim player.

**Comment by Xrayez** [comment]
It looks like a regression to me, I've never experienced this issue before until now.

**Comment by Torguen** [comment]
This is still open but seems to be fixed.
