### ISSUE TITLE
HTTPRequest freezes when hostname resolution stalls due to broken connectivity.

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#51181]
### Godot version

3.4 beta 2

### System information

Mac OSX

### Issue description

When making an HTTP request in the new beta, sometimes the app can pause.

This only happens when the WiFi has a connection, but the WiFi is not connected to the internet.

This bug is not present in 3.2.2 stable, it could be related to the new [HTTPRequest Gzip compression](https://github.com/godotengine/godot/pull/48651)?

### Steps to reproduce

1. Clone [this repository](https://github.com/tavurth/godot-internet-bug)

2. Disconnect your WiFi from the internet (pull the cable)

3. Run the project

4. Your app should freeze

In Godot 3.3.2 stable, the app does not freeze and instead shows a message in the console, as well as a connection warning.

### Minimal reproduction project

https://github.com/tavurth/godot-internet-bug

**Comment by akien-mga** [comment]
There's been a number of stable releases since 3.2.2, could you test them?

**Comment by timothyqiu** [comment]
After testing, the project freezes in both 3.4.beta2 and 3.3.2.stable for about 30 seconds before printing the result in the console which I think is the default connection timeout.

**Comment by Faless** [comment]
> In Godot 3.2.2 stable, the app does not freeze and instead shows a message in the console, as well as a connection warning.

Can you post the warning you get in `3.2.2`?

**Comment by timothyqiu** [comment]
Just tested in `3.2.2`. It also takes about 30 seconds to print the connection error, no other warnings. But the game itself is still responsive during that period, unlike 3.3.2 & 3.4.

**Comment by tavurth** [comment]
> Can you post the warning you get in `3.2.2`?

Sorry for me it was `3.3.2` I updated the main post.
In `3.3.2` I also don't see any freeze, just this message in the console.

<img width="499" alt="Screenshot 2021-08-02 at 17 33 03" src="https://user-images.githubusercontent.com/100964/127878197-c515b44c-adfd-4f20-a4d9-b458f273f42f.png">

**Comment by Faless** [comment]
@tavurth so, what is the difference you are seeing between two versions?

**Comment by tavurth** [comment]
@Faless in `3.4 beta 2` the app becomes unresponsive, no buttons can be clicked etc.

In `3.3.2` the app remains responsive and buttons can be clicked.

**Comment by Faless** [comment]
I can confirm the issue, but I don't think this is a regression. See #51199 for the full details

**Comment by tavurth** [comment]
Thank you @Faless!
