### ISSUE TITLE
Config should be able to create .tscn like config files

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#5118]
Would be nice if .tscn like ini could be generated and used for the game.

```
[tscn name="name" type="type1" parent="parentname"]
key = 20
```

`set_tscn("name", "type1", "parentname")`
`set_tscn_value("name", "type1", "key", 20)`

`get_tscn_types() ` = return a list of all types
`get_tscn("type1")` = return a list of all tscn objects of that type
`get_tscn_keys("name", "type1") `= returns a list of all keys for that name and type
`get_tscn_values("name,"type1")` = returns a list of all valeus for that name and type

`set_tscn("name","type1", "newname", "newtype", "newparent")`

**Comment by trollworkout** [comment]
I know people may be confused by this but tscn essentially is an alternative to  json or yaml. Since Godot uses it why not make it a proper system for storing tree like data.

**Comment by djrm** [comment]
Maybe you could write a TOML parser instead

**Comment by vnen** [comment]
This example API is confusing to me, I'm not sure what the methods do by looking at the signature. Also, it should be grabbed by `id` since `.tscn` can have more than one object of the same type.

It's easier and more practical to use [`ConfigFile`'s functions](http://docs.godotengine.org/en/latest/classes/class_configfile.html).

**Comment by neikeq** [comment]
I don't see the point. `.tscn` (and other scene formats) is designed to be created from a scene tree and the other way around, not manually (unless you are brave enough to edit it manually).

**Comment by bojidar-bg** [comment]
There is PackedSceneState or similar already that might do most of it... (except the writing AFAIK)

**Comment by trollworkout** [comment]
I just thought since Godot uses this special ini type config it should also be able to generate one for the game.  For this tool that I am using a tscn like config file would be much more useful over regular Config or JSON.

**Comment by reduz** [comment]
no intention of adding this as built-in, use ConfigFile
