### ISSUE TITLE
Executing `optimize_indices_for_cache` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#51184]
### Godot version

4.0.dev.custom_build. f2efa6f4f

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
	var temp_variable = SurfaceTool.new()
	temp_variable.begin(-18)
	temp_variable.add_index(11)
	temp_variable.optimize_indices_for_cache()
```

Godot crashes with assertion
```
godot4: thirdparty/meshoptimizer/vcacheoptimizer.cpp:173: void meshopt_optimizeVertexCacheTable(unsigned int*, const unsigned int*, size_t, size_t, const meshopt::VertexScoreTable*): Assertion `index_count % 3 == 0' failed.


```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

**Comment by Sslaxx** [comment]
Is this a bug with Godot, or the mesh optimiser library?
