### ISSUE TITLE
Horrible color banding after using image as a texture. 

### ISSUE THREAD

**Issue by abrasivetroop** [godotengine/godot#51197]
### Godot version

3.3.2

### System information

Windows 10, GLES 3, GTX 1050Ti

### Issue description

This gradient color palette(it is a .png image) gets horrible color banding after I use it as a texture on a 3D mesh. Before that gradient looks smooth but after I use it as a texture it just gets this gross color banding even when I delete it and put in the scene again. It also has this color banding on the 3D mesh as well.

![Screenshot (20)](https://user-images.githubusercontent.com/47716519/127924096-bf1f8993-c8aa-4f8d-a265-a16b88525f01.png)
![Screenshot (21)](https://user-images.githubusercontent.com/47716519/127924103-4ba213bf-d48f-4ca6-956e-e3c46973a2de.png)
![Screenshot (22)](https://user-images.githubusercontent.com/47716519/127924414-d3783924-a8d6-44f5-b23f-09af4338d9f0.png)

### Steps to reproduce

Just use a basic gradient texture in .PNG format and first put it on scene without applying it as a texture and then apply it as a texture on a 3D mesh.

### Minimal reproduction project

[Banding.zip](https://github.com/godotengine/godot/files/6919658/Banding.zip)

**Comment by Calinou** [comment]
This is caused by VRAM compression, which is automatically enabled by textures used in 3D. You can disable it by selecting the texture in the FileSystem dock, going to the Import dock, setting the compression mode to **Lossless** then clicking **Reimport**.
