### ISSUE TITLE
Add rulers and guide liens to the 2D editor

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#5121]
**Operating system or device - Godot version:**: Windows, Linux, MacOS

**Issue description** (what happened, and what was expected):

Hello,

I think a few things will improve the 2D Editor if would be added:
1) Rulers
- Horizontal and Vertical (something similar with the image from this link: http://s32.postimg.org/ax9fga511/rulers.png)
- Configurable (customize the 10 and 50 lines: different colors, different numbers)

2) Guide lines
    - Drag them from the Rules as in GIMP
    - Possibility to hide/show them
    - Rotate them by a specific angle
    - More "hard core" customization: Possibility to edit them as Bezier curves
    - Change colors
    - Combine them in groups and change colors by a group

**Steps to reproduce:** N/A

**Link to minimal example project** (optional but very welcome): N/A

**Comment by reduz** [comment]
not super prioritary, i would prefer auto snap, but if anyone wants to give it a try feel free to add it

**Comment by groud** [comment]
I think most of this have been implemented now, thus I close the issue. 
The other proposal looks overkill to me, but might be discussed in another one if ever really needed.
