### ISSUE TITLE
Transparent Mesh renders out of order when above water shader.

### ISSUE THREAD

**Issue by LittleDuck702** [godotengine/godot#51227]
### Godot version

3.4 beta 2

### System information

MacOS 11, M1, GLES3

### Issue description

When a mesh material has any transparency in it and it’s on top of some shaders, in some angles it renders in the wrong order.

![IMG_9766](https://user-images.githubusercontent.com/87885710/128113896-2bdc830e-7d27-4ba8-8ba2-df50e3a61883.jpeg)

![IMG_9767](https://user-images.githubusercontent.com/87885710/128113913-4113e141-0929-4636-8bce-2b640f5b75c6.jpeg)

https://user-images.githubusercontent.com/87885710/128117154-0e54349e-8e24-4c2e-b461-ad185aa24625.mov

I’ve only tried water shaders so far, like this one.
https://godotshaders.com/shader/stylized-water-shader/

### Steps to reproduce

I haven’t been able to figure out the reason for the problem, but I’ve been able to reproduce it when the linked water shader and a mesh with a material set with some transparency on top of it.

https://godotshaders.com/shader/stylized-water-shader/

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/6928251/BugReport.zip)

**Comment by Calinou** [comment]
You can change **Render Priority** on the transparent mesh's material to work around this. This works best in situations where you know that the object will always be above/below a specific translucent object.

**Comment by LittleDuck702** [comment]
Wow, that worked beautifully, Thanks.
