### ISSUE TITLE
GridMap with a NavigationMeshInstance will crash the game.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#5122]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 2.1 alpha

**Issue description** (what happened, and what was expected):
Having a GridMap with a NavigationMeshInstance will crash the game when run. There is no error in the debugger.

**Steps to reproduce:**
Create a mesh library, with one mesh having a NavigationMeshInstance. Then create a simple GridMap using that mesh library.

**Link to minimal example project** (optional but very welcome):
https://github.com/CowThing/godot-gridmap-crash

**Comment by avril-gh** [comment]
**i cant reproduce it**.
project example given in previous post **runs ok** for me, **no crashes**.

![gridmaptest](https://cloud.githubusercontent.com/assets/3224132/15951762/6e30308c-2ebb-11e6-8b7f-be2f3532c6e8.jpg)


I also currently heavily use gridmap populated with many meshes with navigation and it works ok.

Godot 2.1 alpha, Windows 7

@CowThing maybe something with your graphic drivers ?

**Comment by CowThing** [comment]
I tried running it again. It appears that sometimes it crashes, but sometimes it doesn't.
However if I delete the NavigationMesh from the mesh library the project has never crashed. So I'm certain it happens only when the NavigationMesh is present.

**Comment by avril-gh** [comment]
Godot 2.1 alpha
Windows 7

I done fiew tests and thats what i found.
* GridMap with NavigationMeshes might create crashes in game, in editor or in both.
* Godot does not capture these crashes (no error is shown by godot) just windows 0xC0000005
* While in editor, rotating tile (KEY S) can make editor crash.
* while in game, game will crash perhaps at moment when tile should be shown
* **adding WorldEnvironment to scene with default environment created - prevents from these crashes**.

**Comment by zaps166** [comment]
Hm, on the screenshot looks like `this` has strange address, maybe the method `navmesh_create()` is called from uninitialized pointer, so accessing to member `last_id` crashes the application? I guess that `GridMap` class doesn't initialize the `navigation` pointer in constructor, so it sometimes has random number different than `NULL`, so sometimes it crashes :)

**Comment by zaps166** [comment]
Please try #5139 (not tested by me).
