### ISSUE TITLE
iOS plugins initialize too late

### ISSUE THREAD

**Issue by Vosonos** [godotengine/godot#51230]
### Godot version

3.3.2.stable.official

### System information

iOS 14.6

### Issue description

The issue I'm facing is that the iOS Camera Plugin does not work; no cameras are found. I know it may sound like this bug report belongs over in the iOS plugins repository, but I looked through the plugin and engine code bases to get an idea of what was happening. As far as I can tell, the camera plugin should work EXCEPT for the fact that it is initialized AFTER the CameraServer singleton is created.

The iOS camera plugin works (or would work, heh) by setting the camera class for CameraServer to use. The camera classes for OS X and Windows work exactly the same way:
	godot -> modules -> camera -> register_types.cpp
	Line 45: `CameraServer::make_default<CameraOSX>();`
	godot-ios-plugins -> plugins -> camera -> camera_module.cpp
	Line 36: `CameraServer::make_default<CameraIOS>();`

The problem is that make_default must be set before the CameraServer is created. Setting it later will not change the camera class being used. Unfortunately, the iPhone platform code runs the plugin initialization AFTER the singletons have been created. Essentially the GodotViewRenderer setupView method executes in the following order Main::setup2, godot_ios_plugins_initialize, and Main::start. Main::setup2 is where the singletons are created, so the plugins should be initialized before this call.

I'm more than happy to do what I can to help get this fixed! I'd really like to use the iPhone camera functionality in my app :)

### Steps to reproduce

Create an xcode project for iOS and include the iOS camera plugin. Note that NO print statements from the plugin show up when debugging! If the CameraIOS class specified by the plugin was loaded, the text "Requesting Camera permissions" should print.

**Comment by naithar** [comment]
`godot_ios_plugins_initialize` method should not be called before `Main::setup2`. 
I've tried it when testing ARKit plugin and it resulted in crashes - singletons that are required for plugin registration to work are initialized in `Main::setup2` method.

If `godot_ios_plugins_initialize` should be moved then it should be at the same place where
```
register_platform_apis();
register_module_types();
```
are called inside `Main::setup2`.


@akien-mga I think `register_platform_apis` is generated by scons. Is it possible to use it to perform a call to `godot_ios_plugins_initialize` method?

**Comment by akien-mga** [comment]
You can probably add a `platform/iphone/api/api.{cpp,h}` like done for Android and JavaScript and it will be called automatically in `register_platform_apis`.

**Comment by naithar** [comment]
@Vosonos can you test if this changes fixes your issue: https://github.com/naithar/godot/commit/8b471d2998c80112370fb144b62080cd233cc246? You might be required to rebuild the plugins for them to work correctly.

**Comment by Vosonos** [comment]
@naithar thank you! Yes, the iOS camera plugin works with this build :)
