### ISSUE TITLE
Tilemap normal map - Bizarre Light2D behaviour

### ISSUE THREAD

**Issue by Thaniel94** [godotengine/godot#51248]
### Godot version

3.3.2

### System information

Windows 10, Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz (quad core) driver version: 10.0.19041.546,  NVIDEA GeForce GTX 1060 6GB driver version:  27.21.14.5671, 16 GB ram, (GLES2, and GLES3), 

### Issue description

As you can see, when I apply my normal map to my tileset (all tiles selected using atlas), the behaviour of Light 2D changes unprovoked, going from a simple modulation in the light area to a sort of birds eye view of a cone light. 
I am unsure why this is, as I'm not really versed in this sort of thing but I guess it could be a driver issue, as I have not tried updating it, but it almost looks intentional.

the normal map used is that of the entire tilemap, as instructed. It has a bit of alpha on all its pixels.

### Steps to reproduce

Normal map import settings: 

stream: 0
size limit: 0
detect3d: on

mode: lossless
normal map: enable

Filter: off
Mipmaps: off
anisotropic: off
srgb: detect

fix alpha border: off
premult alpha: on
hdr as srgb: off

svg:
scale 1

EDIT: just a sidenote, this only affects the tilemap with the normal map, all other objects in the scene behave normally with the light2D

Light 2D (default settings, will attach image used) appears to be affected regardless of whether shadows are enabled or not.
![light](https://user-images.githubusercontent.com/85733513/128233912-d7bfe862-3ef6-4215-ae83-1934e9fab994.png)

tilemap size: 128x90 (no spacing, ATLAS_TILE type)
![tilemap5](https://user-images.githubusercontent.com/85733513/128233028-269df93b-84c0-443c-bb53-5dcf3863823d.png)
![tilemap5_n](https://user-images.githubusercontent.com/85733513/128233059-2923dd6b-affd-41d9-ab11-36004ee0abfd.png)
![2021-08-04 18-21-03](https://user-images.githubusercontent.com/85733513/128233293-59662ee0-8c44-4248-a6d2-36ac040b8458.gif)

### Minimal reproduction project

[Tilemap normal map - BizarreLight2D behaviour.zip](https://github.com/godotengine/godot/files/6933569/Tilemap.normal.map.-.BizarreLight2D.behaviour.zip)

**Comment by Calinou** [comment]
Can you reproduce this after disabling batching in the Project Settings? Also, can you reproduce this after switching to the GLES2 renderer?

**Comment by Thaniel94** [comment]
Yes, the options use batching and use batching in editor have both been switched off in the batching tab of rendering, along with changing GLES3 to GLES2 in quality. I restarted the engine to make sure changes were seen. It did not seem to affect things

**Comment by Thaniel94** [comment]
I'm not sure what use this is, but I have been experimenting with the outcomes of inputting different files, and I think that files with either higher value or saturation affect the outcome of the light direction.

normal map input of a higher value (and/or lower saturation) appear to cause the light to shine in the opposite direction.

![2021-08-04 23-22-04](https://user-images.githubusercontent.com/85733513/128263921-6b90419e-b4cf-4f9d-8ce6-4ffccd764dbc.gif)

specifically this file causes the shift in direction:
![tilemap5_n_2](https://user-images.githubusercontent.com/85733513/128264292-dea4e20a-3e33-4c74-a627-ad184abebc73.png)

**Comment by Calinou** [comment]
@Thaniel94 Did you manage to resolve this issue by unchecking **Invert** in the normal map's import options? If so, this issue should be closed :slightly_smiling_face:

**Comment by Thaniel94** [comment]
@Calinou Unfortunately, no, it was just an observation about the behaviour of the bug. :(:(:(

**Comment by Thaniel94** [comment]
Okay, I have found the issue, and it's me not knowing how to read. 

There's a height slider for the Light 2D. Since it was on 0, I think it was 'inside' or at least very close to the normal map, causing a nasty lighting artefact. 

Increasing the height above zero fixes this from what I can see, though there is still a bias towards the bottom right of the viewport for normals with an **alpha channel** as the height slider is moved up and down. 

![2021-08-05 01-31-18](https://user-images.githubusercontent.com/85733513/128272773-d384313d-55ca-41e1-97af-044b38acde27.gif)

In any case, according to 
https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_images.html#normal-map 
normal maps should only need the red and green channels so this should not matter anyway, thus i'm closing the issue with this comment. Nevertheless, thanks for the suggestions @Calinou.
