### ISSUE TITLE
GLTF import = missing material

### ISSUE THREAD

**Issue by Henrydice** [godotengine/godot#51244]
### Godot version

3.3.2 stable

### System information

Windows 10

### Issue description

When importing GLB including several meshes, materials, textures (w/ alpha), and camera, only one material is displayed in Godot by default, the rest is not taken into account. When I try to import the same GLTF on https://gltf-viewer.donmccurdy.com/ all the materials are displayed properly. Screenshots attached.

![image](https://user-images.githubusercontent.com/67262422/128211294-991898c6-1564-4fdd-863c-2c61d201084d.png)

![image](https://user-images.githubusercontent.com/67262422/128211099-7967223d-2f83-4a0c-ac28-e97fb9db0b09.png)

### Steps to reproduce

I model and texture in Blender and export using glTF 2.0 exporter with these settings :

![image](https://user-images.githubusercontent.com/67262422/128211815-0536639c-d224-43a3-ae45-08b86caf6e87.png)

In Godot, I simply double-click the GLB file to open it.

**Comment by Calinou** [comment]
@Henrydice Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by fire** [comment]
It would be helpful to have a test project to debug.

**Comment by Henrydice** [comment]
After cleaning the import files and redoing the whole process of export from Blender/import to Godot it finally works and takes into account all the materials. I therefore close the issue, sorry for the inconvenience and thanks for the quick feedbacks.
