### ISSUE TITLE
Severe performance regression in GLES3/GLES2 renderer related to octahedral compression

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#51256]
### Godot version

3.x (63047093c9728974a7890f31096a36ced58ea60e)

### System information

MacOS Big Sur 11.4 (AMD Radeon Pro 5500M 4GB)

### Issue description

I have bisected, the bug was introduced by #46800

https://user-images.githubusercontent.com/748770/128261484-4e229393-7796-45d2-a013-71649e184f8b.mov

Without that PR I am getting solid FPS figures.

### Steps to reproduce

1. Run MacOS with Godot 3.X branch
2. Open ferris wheel mesh 
3. Move camera (huge fps drop down to 3-4 FPS)
4. Revert PR #46800
5. Repeat steps

### Minimal reproduction project
[FerrisWheel.zip](https://github.com/godotengine/godot/files/6934681/FerrisWheel.zip)

**Comment by akien-mga** [comment]
CC @The-O-King

**Comment by RevoluPowered** [comment]
I spent like 2 days looking into the cause and trying to find a solution, so am here to debug the issues too and can provide access to the macbook if you need it. 

Some more info:
- using clang may make this reproducible on other platforms.

ASAN/UBSAN errors which might be a related symptom:
1. ![image](https://user-images.githubusercontent.com/748770/128263585-1bebba8b-d5ed-40ab-92ee-8da52cb2fd62.png)
2. GL Draw Elements execution time with this PR seriously spikes (Shader compilation happening, or is OpenGL dropping to CPU rendering? unknown)
<img width="1042" alt="Screenshot 2021-08-03 at 15 09 13" src="https://user-images.githubusercontent.com/748770/128263734-b2bf03c9-9c89-49cd-b157-1ba521df09f1.png">
<img width="1067" alt="Screenshot 2021-08-03 at 15 09 27" src="https://user-images.githubusercontent.com/748770/128263801-742c7af9-b1fe-427d-a21c-fb1c751d57bf.png">
3. OpenGL profiling commands
[profileone.txt](https://github.com/godotengine/godot/files/6934739/profileone.txt)

**Comment by The-O-King** [comment]
Should be fixed fully with https://github.com/godotengine/godot/pull/51376

**Comment by clayjohn** [comment]
Closed by #51376
