### ISSUE TITLE
Visible Collision Shapes option has no effect when portals are active

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51264]
### Godot version

v3.4.beta.custom_build.63047093c

### System information

macOS 11.5.1

### Issue description

Debug > Visible Collision Shapes does not work after calling `rooms_convert()` on `RoomManager`.

### Steps to reproduce

Turn "Visible Collision Shapes" on in debug menu, and run your project with portals active.

**Comment by akien-mga** [comment]
Fixed by #51277.
