### ISSUE TITLE
Saved resources are displayed only when restarting edtior

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#5126]
**Operating system or device - Godot version:**
Linux, Fedora 23 64 bit, godot master branch

**Issue description** (what happened, and what was expected):
It is expected that saving a resource like an fnt or tilemap res file, will be immediately visible in the resource load dialog (the file manager window), but the resources arent visible (not event hitting the refresh button), you have to restart the editor in order to see the resources

**Steps to reproduce:**
Just save a resource like an fnt, try to load the newly created resource

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
how are you saving the resoucre as .fnt? are you saving to an existing directory, new directory? more detal would be appreciated

**Comment by djrm** [comment]
closing as unable to reproduce the issue
