### ISSUE TITLE
Suggest LIBGL_ALWAYS_SOFTWARE=1 when not meeting requirement OpenGL 3.3 / OpenGL ES 3.0

### ISSUE THREAD

**Issue by ffaf1** [godotengine/godot#51260]
### Godot version

3.0.6.stable.custom_build

### System information

Debian buster

### Issue description

When you try to run a game on older machines you get

    ERROR: initialize: Your system's graphic drivers seem not to support OpenGL 3.3 / OpenGL ES 3.0, sorry :(
    Try a drivers update, buy a new GPU or try software rendering on Linux; Godot will now crash with a segmentation fault.

My proposal: change «software rendering on Linux» to «software rendering on Linux (e.g. LIBGL_ALWAYS_SOFTWARE=1)». This should point most Linux users to the right direction. 

### Steps to reproduce

Run a Godot game on older hardware

**Comment by clayjohn** [comment]
Have you tried any more recent versions of Godot? The 3.0 release only supported OpenGL 3.3/ GL ES 3.0. But the newer releases all support OpenGL 2.1 / GL ES 2.1. 

You should try again with the latest version of Godot (3.3.2 at the time of writing) and see if it works for you. https://godotengine.org/download

Enabling software rendering isn't really an option as for most computers it will be way too slow to be usable (that will be especially true on older hardware)

**Comment by ffaf1** [comment]
I am using Godot 3.3.2

    ***@***.***:~/media/vcs/godot$ ./Godot_v3.3.2-stable_x11.64 --version
    3.3.2.stable.official
    ***@***.***:~/media/vcs/godot$ ./Godot_v3.3.2-stable_x11.64 ~/ColorSwarm/
    Godot Engine v3.3.2.stable.official - https://godotengine.org
    X Error of failed request:  GLXBadFBConfig
      Major opcode of failed request:  152 (GLX)
      Minor opcode of failed request:  34 ()
      Serial number of failed request:  28
      Current serial number in output stream:  25
    X Error of failed request:  GLXBadFBConfig
      Major opcode of failed request:  152 (GLX)
      Minor opcode of failed request:  34 ()
      Serial number of failed request:  28
      Current serial number in output stream:  25
    ERROR: initialize: Condition "ctxErrorOccurred || !p->glx_context" is true. Returned: ERR_UNCONFIGURED
       At: platform/x11/context_gl_x11.cpp:190.
    ERROR: is_viable: Error initializing GLAD
       At: drivers/gles3/rasterizer_gles3.cpp:141.

Il 04 agosto 2021 alle 18:21 Clay John ha scritto:

**Comment by akien-mga** [comment]
What is your GPU and drivers?

Most likely it's a low end IGP which claims OpenGL 3.3 support but doesn't handle it properly. You should use GLES2 only on such a GPU (but since the drivers claim OpenGL 3.3 support, we can't detect it and fallback automatically for you).

**Comment by ffaf1** [comment]
Does this anwswer your question?

        ***@***.***:~/download$ glxinfo | grep render
    direct rendering: Yes
        GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer,
        GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_OML_swap_method,
    Extended renderer info (GLX_MESA_query_renderer):
    OpenGL renderer string: Mesa DRI Mobile Intel® GM45 Express Chipset
        GL_NV_conditional_render, GL_NV_depth_clamp, GL_NV_fog_distance,
        GL_OES_element_index_uint, GL_OES_fbo_render_mipmap,

Il 05 agosto 2021 alle 02:40 Rémi Verschelde ha scritto:

**Comment by akien-mga** [comment]
Not yet, but `glxinfo | grep -i opengl` should.

**Comment by ffaf1** [comment]
```
***@***.***:~$ glxinfo | grep -i opengl
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Mobile Intel® GM45 Express Chipset
OpenGL version string: 2.1 Mesa 18.3.6
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

Il 05 agosto 2021 alle 02:55 Rémi Verschelde ha scritto:

**Comment by akien-mga** [comment]
Then yes you're out of luck. Intel GM45 is a very weak chipset and its OpenGL 2.1 support in Mesa was so bad that they limited it to OpenGL 1.4 in a later Mesa release (19.x IIRC). So if you upgrade to a newer Debian version you won't be able to run any Godot version.

As clayjohn pointed out, software rendering might work to let you start Godot, but it likely won't be usable to do actual game development or run any game. Software rendering is mostly useful for testing pipelines.

**Comment by ffaf1** [comment]
Sofware rendering worked for me to run and play without problem [this simple game](https://leagueh.xyz/m/librejam/26.html), hence why I suggested the change.

I will leave to the devs judging if my proposed change makes sense for the wider userbase-that-owns-old-hardware.

Il 05 agosto 2021 alle 03:47 Rémi Verschelde ha scritto:

**Comment by clayjohn** [comment]
@ffaf1 I see that I misunderstood you. My apologies. Seeing Calinou's PR and re-reading your post made me realize that I was wrong. I thought you were suggesting that Godot automatically run in software mode for all devices that don't support GLES2. Communicating how to turn on software rendering in the error message is very helpful. 

Thanks for the suggestion!
