### ISSUE TITLE
updating Godot , game stop working on android "could not to install "

### ISSUE THREAD

**Issue by AbdulkarimAhmad** [godotengine/godot#51269]
### Godot version

3.3.2

### System information

Windows 10

### Issue description

Hi there 
I used Godot 3.2.2 to build a game and now i want to use plugin work on Godot 3.3
so I download Godot 3.3.2 and i open it remove the previse template and download new one , remove the previse android build and download the new one and i try to run the game on my device and its not work it give me only "could not to install"
the game were work fine in Godot 3.2.2 . also i try to run it on bluestacks it run but as a blank screen .
its work fine to run it on windows .
i make new project and run on my android device and its work fine , 

i saw someone on the community said that it maybe a naming issue . i didn't change anything on my game file from Godot 3.2.2 its all the same file but i tried on new project naming new scenes ,file and node with include (space , - ) and it work .
so i don't think its a naming issue how could i find what wrong or what happen .

**Comment by floppyhammer** [comment]
This happened to me once, and it was a naming issue in my case. I used non-ASCII name for some resource file. You might want to double check you're not doing this.

**Comment by AbdulkarimAhmad** [comment]
i checked my res files and i only use [0-9][a-z] and space and - in naming  . is the space and - could causes the issue ?

**Comment by floppyhammer** [comment]
@AbdulkarimAhmad No, they wouldn't.

**Comment by AbdulkarimAhmad** [comment]
i found the problem after debugging with "adb logcat" i found that there is a problem with admob plugin so when i remove it its work . for some reason its work fine with Godot 3.2.2 but with Godot 3.3 its not work for me .

**Comment by floppyhammer** [comment]
@AbdulkarimAhmad You have to upgrade it to the latest release to make it work with 3.3.

**Comment by AbdulkarimAhmad** [comment]
yea thank you
