### ISSUE TITLE
The FileDialog Cancel Button does not have a signal

### ISSUE THREAD

**Issue by Arrow-x** [godotengine/godot#51275]
### Godot version

3.3.2 Stable

### System information

Windows 10 GLES 2 Intel HD Graphics 3000

### Issue description

The Filedialog Cancel button (not the X on the top bar) have no signal 
The model_closed and popup_hide Signals are not emitted when it is clicked
and connecting the pressed signal in get_close_button(), will connect the x button not the button that says cancel

![Capture2](https://user-images.githubusercontent.com/3308421/128345255-d5d02f85-d3fb-4871-9720-c83ffd062003.PNG)

### Steps to reproduce

it a lack of feature in the FileDialog Node

**Comment by KoBeWi** [comment]
You can use `get_cancel()` to get the button and then use it to connect.

**Comment by Arrow-x** [comment]
that it does
