### ISSUE TITLE
Input.is_action_just_pressed() sometimes misses events triggered with Input.parse_input_event()

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#51278]
### Godot version

3.3 custom build 51f8247871c84736a3c3f56375deb432a4cb305a

### System information

OS: Arch Linux, CPU: Ryzen 5, GUP: RX 480

### Issue description

When running tests I simulate input events with Input.parse_input_event() but I get pseudo-random failures because Input.is_action_just_pressed() sometimes returns false for an action that was clearly just "pressed" with  Input.parse_input_event().

Both parse_input_event() and is_action_just_pressed are called in _physics_process() either directly or indirectly.

I can reproduce the issue in a minimal project.

### Steps to reproduce

Create a node with this script:

```
extends Node


extends Node


func _physics_process(delta: float) -> void:
	var event = InputEventAction.new()
	event.action = "ui_accept"
	event.pressed = true
	if Engine.get_physics_frames() % 2:
		print("Parsing Event: ", Engine.get_physics_frames())
		Input.parse_input_event(event)

```

and a child node with this one:

```
extends Node


func _physics_process(delta):
	if Engine.get_physics_frames() % 2:
		print("Consuming Event: ", Engine.get_physics_frames())
		assert(Input.is_action_just_pressed("ui_accept"))

```

Full Output:

```
Parsing Event: 1
Consuming Event: 1
Parsing Event: 3
Consuming Event: 3

```
And nothing else because the assertion fails.

### Minimal reproduction project

[parse_input_bug.zip](https://github.com/godotengine/godot/files/6939010/parse_input_bug.zip)

**Comment by kleonc** [comment]
You're never unpressing the action hence it's pressed all the time after your first `parse_input_event` call.
Changed your scripts a little so the action will be pressed on frames: `0, 3, 6, (...)` and unpressed on frames: `2, 5, 8, (...)`:
```
# parent
extends Node

func _physics_process(delta: float) -> void:
	if Engine.get_physics_frames() % 3 == 1:
		return
	var event = InputEventAction.new()
	event.action = "ui_accept"
	event.pressed = Engine.get_physics_frames() % 3 == 0
	print("[%d] %s" % [ Engine.get_physics_frames(), event.as_text() ])
	Input.parse_input_event(event)
```
```
# child
extends Node

func _physics_process(delta):
	print("[%d] pressed=%s just_pressed=%s" % [ Engine.get_physics_frames(), Input.is_action_pressed("ui_accept"), Input.is_action_just_pressed("ui_accept") ])
	if Engine.get_physics_frames() % 3 == 0:
		assert(Input.is_action_just_pressed("ui_accept"))
```
and here's the output:
```  
[0] InputEventAction : action=ui_accept, pressed=(true
[0] pressed=True just_pressed=True
[1] pressed=True just_pressed=False
[2] InputEventAction : action=ui_accept, pressed=(false
[2] pressed=False just_pressed=False
[3] InputEventAction : action=ui_accept, pressed=(true
[3] pressed=True just_pressed=True
[4] pressed=True just_pressed=False
[5] InputEventAction : action=ui_accept, pressed=(false
[5] pressed=False just_pressed=False
[6] InputEventAction : action=ui_accept, pressed=(true
[6] pressed=True just_pressed=True
[7] pressed=True just_pressed=False
[8] InputEventAction : action=ui_accept, pressed=(false
[8] pressed=False just_pressed=False
[9] InputEventAction : action=ui_accept, pressed=(true
[9] pressed=True just_pressed=True
(...)
```

So everything seems to work as expected (besides the result of `InputEventAction.as_string()`, there should be no bracket after `pressed=`).

**Comment by m4nu3lf** [comment]
> You're never unpressing the action hence it's pressed all the time after your first `parse_input_event` call.
> Changed your scripts a little so the action will be pressed on frames: `0, 3, 6, (...)` and unpressed on frames: `2, 5, 8, (...)`:
> 
> ```
> # parent
> extends Node
> 
> func _physics_process(delta: float) -> void:
> 	if Engine.get_physics_frames() % 3 == 1:
> 		return
> 	var event = InputEventAction.new()
> 	event.action = "ui_accept"
> 	event.pressed = Engine.get_physics_frames() % 3 == 0
> 	print("[%d] %s" % [ Engine.get_physics_frames(), event.as_text() ])
> 	Input.parse_input_event(event)
> ```
> 
> ```
> # child
> extends Node
> 
> func _physics_process(delta):
> 	print("[%d] pressed=%s just_pressed=%s" % [ Engine.get_physics_frames(), Input.is_action_pressed("ui_accept"), Input.is_action_just_pressed("ui_accept") ])
> 	if Engine.get_physics_frames() % 3 == 0:
> 		assert(Input.is_action_just_pressed("ui_accept"))
> ```
> 
> and here's the output:
> 
> ```
> [0] InputEventAction : action=ui_accept, pressed=(true
> [0] pressed=True just_pressed=True
> [1] pressed=True just_pressed=False
> [2] InputEventAction : action=ui_accept, pressed=(false
> [2] pressed=False just_pressed=False
> [3] InputEventAction : action=ui_accept, pressed=(true
> [3] pressed=True just_pressed=True
> [4] pressed=True just_pressed=False
> [5] InputEventAction : action=ui_accept, pressed=(false
> [5] pressed=False just_pressed=False
> [6] InputEventAction : action=ui_accept, pressed=(true
> [6] pressed=True just_pressed=True
> [7] pressed=True just_pressed=False
> [8] InputEventAction : action=ui_accept, pressed=(false
> [8] pressed=False just_pressed=False
> [9] InputEventAction : action=ui_accept, pressed=(true
> [9] pressed=True just_pressed=True
> (...)
> ```
> 
> So everything seems to work as expected (besides the result of `InputEventAction.as_string()`, there should be no bracket after `pressed=`).

Thanks, It works. I didn't know that Godot was keeping the state of the current button when triggering it with parse_event_input(). Great it works. We can close the issue.
