### ISSUE TITLE
Using HeightMapShape with NavigationMeshInstance

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#51289]
### Godot version

3.3.2.stable

### System information

Manjaro Linux

### Issue description

I am trying to generate a NavMesh using static collisionshape bodies. It works with cube, sphere, cylinder, etc. but not HeightMapShape. I have checked that the shape is valid and it works with a RigidBody. Does NavigationMeshInstance not support working with HeightMapShape collisions? Or maybe there's some setting that needs to be set differently? Not sure where to go from here .

### Steps to reproduce

Create a HeightMapShape with points, large enough for a NavMesh to work.
Set NavigationMeshInstance to work with collision shapes.
Generate the NavMesh. (it's empty)

**Comment by Calinou** [comment]
@andersmmg Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by andersmmg** [comment]
[NavMesh HeightMap.zip](https://github.com/godotengine/godot/files/6941023/NavMesh.HeightMap.zip)
Here's the minimal project. Forgot to upload it!

**Comment by smix8** [comment]
HeightMapShape / HeightMapShape3D is not part of the `NavigationMeshGenerator::_parse_geometry()` function so it is simply ignored in the baking process.

@Scony 
Recently you reworked all the mesh_array functions for the different shape types in that part. Any chance we can add the heightmapshape?

**Comment by Scony** [comment]
@smix8 I can do it, sure.

**Comment by Scony** [comment]
Okay, I've taken a look at the `HeightMapShape`/`Shape` API and it looks like there is no simple shape-to-triangle-mesh converter available. @akien-mga @BastiaanOlij @groud do you know any way to convert a shape to triangle mesh easily?

**Comment by BastiaanOlij** [comment]
@Scony the heightmap data is just an array with heights spaced out over a 1.0x1.0 grid. So from memory your vertices can be calculated with code like:
```
float *height = &height_buffer[0];
for(int y = 0; y < height; y++) {
  for(int x = 0; x < width; x++) {
    Vector3 v = Vector3(float(x - width/2), *height, float(y - height/2));
    height++;
    
    // do something with the new vertex and create some faces..
  }
}
```

**Comment by Scony** [comment]
> @Scony the heightmap data is just an array with heights spaced out over a 1.0x1.0 grid. So from memory your vertices can be calculated with code like:
> 
> ```
> float *height = &height_buffer[0];
> for(int y = 0; y < height; y++) {
>   for(int x = 0; x < width; x++) {
>     Vector3 v = Vector3(float(x - width/2), *height, float(y - height/2));
>     height++;
>     
>     // do something with the new vertex and create some faces..
>   }
> }
> ```

Yeah, I know, I just wanted to avoid code duplication if such an implementation was already available somewhere in the code. But if you're suggesting doing it by hand then I can safely assume it's not there and I can implement it :)

**Comment by Scony** [comment]
I'll implement it no earlier than July.
