### ISSUE TITLE
Convert VisualScript between builds

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#51291]
### Godot version

master

### System information

Windows 10

### Issue description

Issue: When copying .vs files between builds they tend to be 'corrupted' this closes the editor.

Workaround: 
1 Open the project in the original build.
2 Open .vs
3 RMB the file in the Scripts Panel to `Save As ...` .tres (now you are able to open the file as a text file)
4 Copy and paste .tres in the new project.
5 repeat step 1-3 in the new project to save as a .vs

### Steps to reproduce

Create and edit a project then a .vs in one build.
Then try to open it in a other build.

I have had this issue multiple times now  and wanted to share the workaround I found.
Don't know if you can call it a bug if it is not happening between releaser builds.

### Minimal reproduction project

I do not get the original build in here it is `windows-editor PR51147 e59232c.zip` so I will attach the .tres for example
[Uploading mvp_basic_functions (5).zip…]()
[Control.zip .tres](https://github.com/godotengine/godot/files/6940612/Control.zip)

**Comment by fire** [comment]
Any ideas how to fix?

**Comment by Gallilus** [comment]
Nope, Sorry

**Comment by KoBeWi** [comment]
VisualScript is removed in 4.0, so the issue is no longer relevant.
