### ISSUE TITLE
get_tree().get_rpc_sender_id() returning wrong id

### ISSUE THREAD

**Issue by nerdnils** [godotengine/godot#51304]
### Godot version

3.3.2

### System information

Archlinux

### Issue description

Set up a network game. Call a network function. I called a function on the server from the client. Within that function, call another function.

Client:
rpc_id(1,"network_function")

Server:
remotesync func network_function():
     dostuff()

remotesync func dostuff():
     print (get_tree().get_rpc_sender_id())

This will return the id of the client. When in fact the function which was called is "dostuff" and this was called by the server itself. So get_tree().get_rpc_sender_id() should return 0 for local call instead.

### Steps to reproduce

See issue description

**Comment by dicarne** [comment]
`dostuff()` is just a local function call, not a rpc call. rpc call is not automatic.

**Comment by nerdnils** [comment]
> 
> 
> `dostuff()` is just a local function call, not a rpc call. rpc call is not automatic.

Yes, it is and according to the documentation at https://docs.godotengine.org/de/stable/classes/class_multiplayerapi.html#class-multiplayerapi-method-get-rpc-sender-id it should return 0 in this case which it does not.

**Comment by Faless** [comment]
> This will return the id of the client. When in fact the function which was called is "dostuff" and this was called by the server itself. So get_tree().get_rpc_sender_id() should return 0 for local call instead.

Well, `get_tree().get_rpc_sender_id()` returns the ID of the client because the function is indeed being called during a client RPC.
Specifically, `dostuff` is called by `network_function`, which was executed by the client. I.e. you are still inside `network_function` while executing `dostuff`.

To put it simply, the ID won't change until the RPC has returned.
