### ISSUE TITLE
Triple click doesn't take mouse position into account

### ISSUE THREAD

**Issue by codecat** [godotengine/godot#51312]
### Godot version

3.3.3.rc1

### System information

Windows 10

### Issue description

When double clicking to select a word, the mouse position is taken into account correctly, but when doing a third click elsewhere, the line is suddenly selected. The following gif demonstrates the problem:

![tripleclick](https://user-images.githubusercontent.com/136534/128507342-1eed3120-725f-4c1e-a2a7-fef9821b9ec7.gif)

### Steps to reproduce

1. Double click a word.
2. Quickly, single-click another word.
3. The entire line is now selected.

**Comment by Calinou** [comment]
For the record, this is how double-clicking/triple-clicking behaves in Visual Studio Code:

https://user-images.githubusercontent.com/180032/128518297-d9c32766-4eee-4513-b52a-123614fd571e.mp4

**Comment by codecat** [comment]
The code for this is here:

https://github.com/godotengine/godot/blob/50d5569ad49752803b980eca85590f5362b12409/scene/gui/text_edit.cpp#L2249-L2259

The solution would probably be to change `cursor.line == prev_line` so that it checks the last double click position instead of only the line number. I can do a pull request for this if that sounds okay.

**Comment by Calinou** [comment]
> I can do a pull request for this if that sounds okay.

Feel free to open a pull request for this :slightly_smiling_face:
