### ISSUE TITLE
Batching doesn't work with Line2Ds if antialiased

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot#51317]
### Godot version

3.3.2 stable

### System information

Linux Mint 20.1 Cinnamon, GLES3, Radeon Rx 570x, Mesa 21.1.6

### Issue description

Batching works fine with Line2Ds, but if `border/antialiased` is enabled in the Inspector, batching fails.
It is not a critical issue for my project, just a fyi notice, think you might want to know. :-)

### Steps to reproduce

Put some Line2Ds in your project, enable `borders/antialiased` and check the batching status by enabling `rendering/batching/debug/diagnose_frame` in the Project Settings.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/43332.

**Comment by TrickMe** [comment]
Does #43332 mean I can close this issue?
You assigned lawnjelly, so I leave it, but feel free to close, I'm not online regularly.

**Comment by lawnjelly** [comment]
See https://docs.godotengine.org/en/stable/tutorials/optimization/batching.html#batched-primitives.

> Batching is not guaranteed either, especially with primitives using an antialiased border.

This is kind of being a victim of our own success :grin: , at first only rects were batched and we gradually added so more such that people ended up expecting all primitives to be batched, but this is not the case, some are not easy to do.

We could possibly add it to the tooltip too, but there are so many special cases it is hard to know where to draw the line in providing too much info...

**Comment by lawnjelly** [comment]
Fixed by #51803.
