### ISSUE TITLE
PhysicsBody raypicking does not adhere to MOUSE_MODE_CAPTURED

### ISSUE THREAD

**Issue by xelivous** [godotengine/godot#5134]
**Operating system or device - Godot version:**
Win7 x64 - [2.1alpha / 00bfdc834bc028e7c15e939662a72353250d00f3]

**Issue description** (what happened, and what was expected):
If you set up any physicsbody to be raypickable, the picking will work correctly if the mouse_mode is set to `visible`. If you set the mouse_mode to `mouse_mode_captured`, it'll send the raypick as if the mouse *wasn't* captured.

**Steps to reproduce:**
1. Create any physicsbody, and make sure "raypick" is enabled
2. Create a script, and connect the physicbody's `input` signal so you know when you're picking it
3. Create a camera and point it so that the rigidbody is on the screen
4. Toggle between captured/visible verifying that the picking is wrong

**Link to minimal example project** (optional but very welcome):
[RayPickTest.zip](https://github.com/godotengine/godot/files/308269/RayPickTest.zip)

[Example Video](https://www.youtube.com/watch?v=idN3OfNjwlY)

**Comment by reduz** [comment]
I guess raypicking should simply be disabled if the mouse is disabled..?

**Comment by reduz** [comment]
i mean, captured

**Comment by xelivous** [comment]
tbh I would prefer to have it lock the ray to the center of the screen, since generally when the mouse is "captured" that's where the mouse is supposed to be. I *could* simply have a ray extending from the camera and use that, but then I would also have to re-implement when the ray stops colliding (for "mouse_exit" on CollisionObject) and then manually emit the signal for input. It's essentially just a lot of code duplication; unless there's some better way to do what i'm trying to do.

I was originally trying to use it to allow world interaction from a first person perspective. In the meanwhile I've basically worked around by having mouse capture disabled by default, and only allowing the player to rotate themselves by holding right-click (which captures the mouse); i'm not fond of [this particular solution](https://www.youtube.com/watch?v=WwceGOHhVAA) tho.

**Comment by reduz** [comment]
for now I have disabled it, I guess for an FPS, you can do picking yourself using the cast_ray API

**Comment by scraprats** [comment]
Yeah, I think this shouldn't be allowed. I know this makes sense in theory but in practice, on X11 the cursor isn't really confined to the center of the screen (shifts outside the center, then rubber bands) and on Wayland Godot doesn't center it on launch (you have to refocus the window) so I expect lots of other quirks like that. And that's just on one platform.

Probably best to write in the docs a warning not to use this feature for FPS camera and just do a regular raycast.
