### ISSUE TITLE
Unhandled Exception on opening of any project and build for 3.4 Beta 3 Mono

### ISSUE THREAD

**Issue by Keppl** [godotengine/godot#51344]
### Godot version

3.4-beta3-mono

### System information

Windows 10

### Issue description

Opening any project with Godot 3.4 beta 3 produces following on console/terminal:

> Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at GodotTools.Build.MSBuildPanel._Notification (System.Int32 what) [0x00022] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
  at (wrapper managed-to-native) Godot.EditorNativeCalls.godot_icall_2_387(intptr,intptr,intptr,string)
  at Godot.EditorPlugin.AddControlToBottomPanel (Godot.Control control, System.String title) [0x00012] in <d86e52e4ad7b488bbaa0527a6715c72d>:0
  at GodotTools.GodotSharpEditor.EnablePlugin () [0x00066] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
ERROR: System.NullReferenceException: Object reference not set to an instance of an object
   at: debug_send_unhandled_exception_error (modules/mono/mono_gd/gd_mono_utils.cpp:369)

> Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at GodotTools.Build.MSBuildPanel._Notification (System.Int32 what) [0x00022] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
ERROR: System.NullReferenceException: Object reference not set to an instance of an object
   at: debug_send_unhandled_exception_error (modules/mono/mono_gd/gd_mono_utils.cpp:369)

Building solution generates another one:
> Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at GodotTools.Build.MSBuildPanel.BuildSolution () [0x0003a] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
  at GodotTools.Build.MSBuildPanel.BuildMenuOptionPressed (GodotTools.Build.MSBuildPanel+BuildMenuOptions id) [0x00014] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
ERROR: System.NullReferenceException: Object reference not set to an instance of an object
   at: debug_send_unhandled_exception_error (modules/mono/mono_gd/gd_mono_utils.cpp:369)

Happens for me on two different Windows machines.
Doesn't seems to have any negative effect, at least not on second machine. On first Godot crashed/closed once during build but I haven't tested if that was a persistent issue or a one off.

Not sure if this is related, but Editor Settings -> Mono -> Builds -> Build tool is showing a number for me.

![Annotation 2021-08-06 223440](https://user-images.githubusercontent.com/8963514/128585264-1039b299-65cb-435d-9e7b-8399d5102211.png)

Similar to https://github.com/godotengine/godot/issues/50486#issuecomment-880774291

Neither of those (exception or number in build tools instead of name/drop down) happens for me in 3.4 beta 2.

### Steps to reproduce

Open any project in Godot v3.4 beta 3, on windows 10

**Comment by OtherCannon** [comment]
I am having a similar issue, I created a new project in Godot 3.4 beta 3 Mono and upon creating a C# script Godot crashed. I checked the project folder and Godot had successfully created the .sln, .csproj, and C# script, but in the editor the script was not attached to the node. I tried reattaching it but Godot crashed. Something of note: The "Solution" option is no longer available in project settings.

**Comment by akien-mga** [comment]
That's fixed by https://github.com/godotengine/godot/pull/51325. Bad timing sadly, I wasn't aware of the bug and upcoming fix when building beta 3.

**Comment by akien-mga** [comment]
Here's a hotfixed 3.4 beta 3 mono build which resolves this issue: https://downloads.tuxfamily.org/godotengine/3.4/beta3/mono/

You might not need to redownload the export templates if you have them already, only editor code was changed.
