### ISSUE TITLE
C# linting in godot not working

### ISSUE THREAD

**Issue by DanesZalor** [godotengine/godot#51359]
### Godot version

3.3.2

### System information

Linux

### Issue description

Omnisharp intellisence not working with godot mono.

Code linting for GD-Script works with visual studio but C# does not. 
When I open a normal cs project, there is intellisence for the dotnet framework but when I open a godot project in vscode, there is no linting at all.

### Steps to reproduce

I'm using the official Microsoft branded vscode release https://aur.archlinux.org/packages/visual-studio-code-bin/
and downloaded the following plugins:
- ms-dotnettools.csharp (C# intellisence)
- neikeq.godot-csharp-vscode (Mono-Debug)
- geequlim.godot-tools (godot-tools)
- neikeq.godot-csharp-vscode (C# tools for godot)

i followed a tutorial: https://www.youtube.com/watch?v=Do0YZocTu80 (just installing those plugins and setting the external editor to vs code)

### Minimal reproduction project

any basic project with a .cs file will work
[HelloWorld.zip](https://github.com/godotengine/godot/files/6948960/HelloWorld.zip)

**Comment by Calinou** [comment]
Can you reproduce this with another editor/IDE? If not, then the issue is with one of the Visual Studio Code add-ons (and should therefore be moved there).

**Comment by DanesZalor** [comment]
> Can you reproduce this with another editor/IDE? If not, then the issue is with one of the Visual Studio Code add-ons (and should therefore be moved there).

i tried other versions of vscode such as vscodium https://aur.archlinux.org/packages/vscodium/ and it also didn't work,
but i also tried the open source release of vs code from microsoft and the linting worked. my bad

**Comment by Moon422** [comment]
> but i also tried the open source release of vs code from microsoft and the linting worked. my bad

Open source release of vs code from the microsoft? Did you mean the one that you get from microsoft's website or is it some other build? I am facing this issue as the recent version of C# extension does not work with mono. So, if you please share what steps you took, that would be really helpful. Thank You.

**Comment by DanesZalor** [comment]
I got it from here https://github.com/VSCodium/vscodium. The linting works now, I just didn't know how to use vscode and omnisharp at the time haha.  I forgot to select csproj
