### ISSUE TITLE
Incorrect font size in titles and subtitles of text documentation when batching is enabled in the editor

### ISSUE THREAD

**Issue by Shockblast** [godotengine/godot#51350]
### Godot version

3.3.2 stable

### System information

Windows 10 21H1, Nvidia RTX 2060 471.11, GLES3

### Issue description

The titles and subtitles of the documentation looks dark or completely transparent, happens very rarely and completely random.
![image](https://user-images.githubusercontent.com/5357217/128591066-03edbacc-7bd4-422b-a0da-f54408bb9184.png)
![image](https://user-images.githubusercontent.com/5357217/128590968-d2bcdd0a-077d-4e55-bb3e-ea0c7e68e467.png)

### Steps to reproduce

I'm not sure, but I changed the font size in main and code to 10 in the editor, I'm sorry I wish I could provide more information.

**Comment by Calinou** [comment]
Can you reproduce this after disabling batching for the editor in the Project Settings?

**Comment by Shockblast** [comment]
> @Shockblast Can you reproduce this after disabling batching for the editor in the Project Settings?

no, it works normally there.
Another detail that I forgot to mention, when I restart the editor it returns to normal.
In the last times that I have used the editor, it has not happened again.
![image](https://user-images.githubusercontent.com/5357217/128614718-bd4ac435-cf55-4bb3-8e1e-2906b265122c.png)

**Comment by Calinou** [comment]
cc @lawnjelly

**Comment by lawnjelly** [comment]
I'll see if I can reproduce it. It might be tough to investigate without a reproduction situation.

**Comment by Shockblast** [comment]
> Unfortunately I've not been able to reproduce it on my side. These things are tough to investigate without a reproduction situation.
> 
> When I change the font size of `main` and `code` in the editor settings, it says "The editor must be restarted for the changes to take effect". With these warnings you can avoid restarting but sometimes it can leave things in an unstable state. Given that restarting seems to fix it, could this be related? It might be worth getting input here from anyone that knows anything about how the fonts get recreated in Godot just to exclude that side. Maybe this restart is just for the spacing and wouldn't be involved.
> 
> Also, does this occur when batching is active but GLES2 is selected instead of GLES3?
> 
> It looks like there is either a problem with the font texture or the alpha states somehow when rendering. But if it is the latter, I can't see immediately how creating a different font size (texture) could be affecting it, and it is notable that no one else has reported a similar problem, and that it only seems to be occurring for you in some situations.
> 
> My best guesses are:
> 
> * GL state bug in the batching, which might be e.g. GLES3 specific
> * Possibly texture compression related or mipmaps
> * Something in the font recreation which needs a restart
> * Uninitialized memory somewhere
> * Driver bug
> 
> But really not much to go on so far.
> 
> You could also try http://apitrace.github.io/ or similar graphics debugger to record the frames.
> This can be useful both to find out whether the behaviour is repeatable for the same run (if not it is more suggestive of a driver bug), and also to send API traces to us so we can try running them on different hardware.

Thank you, i will try apitrace.
Notice the problem has not happened again after I restarted the editor on that occasion, independent of batching enable or disable, also i was trying to recreate the steps for the bug with no success playing with the options.

So, will the issue be closed? Since apparently it is difficult to recreate and it happens very very rarely (at least for me) that it is not worth fixing?

Sorry my english (aka GoogleTranslate).

**Comment by lawnjelly** [comment]
If you can't reproduce it either, it is possible that is down to a state your machine was in that particular time (could it have been doing an automatic video driver update? sometimes we have had issues where a video driver downloaded an update which required a reboot, and behaved incorrectly until this).

I guess we can close but we can always reopen if you are able to reproduce the issue again. :+1:

It is useful to have such issues searchable because sometimes someone else has the same problem, but a year later, and it makes it easier to make sense of.
