### ISSUE TITLE
Setting a TextEdits 'text' property while it contains a sizable string freezes the executable.

### ISSUE THREAD

**Issue by ShadyChibinko** [godotengine/godot#51369]
### Godot version

3.3.2.stable

### System information

Windows 10

### Issue description

If you set a TextEdits 'text' equal to a sizable string and then attempt setting it to something else, the executable will freeze. 'Sizable' being roughly 79 000 words and 393 000 characters. It will always freeze if setting is done through code, and only rarely through mouse and keyboard operations. Below are my test cases:

### Does Freeze
- TextEdit.text = ''
- TextEdit.text += 'A'
- Highlighting and deleting a decent portion of the text.

### Does NOT Freeze
- Copy & Paste. (Highlighted the entire text block and pasted it at the end of the TextEdit.)
- Adding & deleting single characters through keyboard.

I tried similar tests with the other text based GUI nodes (i.e. Label, RichTextLabel and LineEdit) and all of them worked without issue. I've included the aforementioned large text file in the repro project.

### Steps to reproduce

- Open the repro project.
- Run the main scene.
- Press the 'Set Text' button. 

'text' will be set to an empty string and the executable should freeze.

### Minimal reproduction project

[TextEditCrashTest.zip](https://github.com/godotengine/godot/files/6949375/TextEditCrashTest.zip)

**Comment by Paulb23** [comment]
Should be fixed by #55739
