### ISSUE TITLE
Enabling the Visible property on an exclusive AcceptDialog causes the editor to no longer receive mouse events (DisplayServer regression)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#51362]
### Godot version

3177da1d053a6132668e12a8d8af82366f5c4ac9

### System information

Windows 10

### Issue description

The editor will freeze forever(without error spamming) if the user touches a `Visible` property of the `ConfirmationDialog` in the inspector:

![image](https://user-images.githubusercontent.com/3036176/128600547-044c4fea-1b16-4560-b518-0fdf1842ee2f.png)

### Steps to reproduce

Create a `ConfirmationDialog` and touch this property. 

### Minimal reproduction project

Too trivial to reproduce.

**Comment by Thane5** [comment]
Probably related:
When creating a new `Window` node, the "visible" flag will be enabled by default. You can toggle it without the editor freezing, but it shows heavy artifacts when it appears.
![Godot Engine - BugTest (_) 12 08 2021 17_01_54](https://user-images.githubusercontent.com/13683581/129220701-4fa710c5-e743-4194-ae05-73501889acb8.png)
(Tested in v4.0.dev.calinou [7188cb601], Forward Clustered vulkan renderer)
