### ISSUE TITLE
Assigning a texture to a MeshInstance3D results in no visible texture and error spam until the scene is saved and reloaded

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#51361]
### Godot version

v4.0.dev.calinou [4cb406e02]

### System information

Win 10 64, AMD RX 480

### Issue description

Pressing the re-import of normal map gives console spam.

> drivers/vulkan/rendering_device_vulkan.cpp:7153 - Condition "!uniform_set" is true.
>   Uniforms supplied for set (3):
>   Set: 3 Binding: 0 Type: UniformBuffer Length: 128
>   Set: 3 Binding: 1 Type: Texture Length: 1
>   Set: 3 Binding: 2 Type: Texture Length: 1
>   Set: 3 Binding: 3 Type: Texture Length: 1
>   are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
>   Set: 0 Binding: 1 Type: Sampler Length: 12
>   Set: 0 Binding: 2 Type: Sampler Length: 1
>   Set: 0 Binding: 3 Type: Sampler Length: 1
>   Set: 0 Binding: 4 Type: Sampler Length: 1
>   Set: 0 Binding: 5 Type: StorageBuffer Length: 0
>   Set: 0 Binding: 6 Type: StorageBuffer Length: 0
>   Set: 0 Binding: 7 Type: StorageBuffer Length: 0
>   Set: 0 Binding: 8 Type: UniformBuffer Length: 4224
>   Set: 0 Binding: 9 Type: StorageBuffer Length: 0
>   Set: 0 Binding: 10 Type: StorageBuffer Length: 0
>   Set: 0 Binding: 11 Type: Texture Length: 1
>   Set: 0 Binding: 12 Type: Texture Length: 1
>   Set: 0 Binding: 13 Type: StorageBuffer Length: 0
>   Set: 0 Binding: 14 Type: StorageBuffer Length: 0
>   Set: 0 Binding: 15 Type: UniformBuffer Length: 368
>   Set: 1 Binding: 0 Type: UniformBuffer Length: 2656
>   Set: 1 Binding: 1 Type: StorageBuffer Length: 0
>   Set: 1 Binding: 2 Type: Texture Length: 1
>   Set: 1 Binding: 3 Type: Texture Length: 1
>   Set: 1 Binding: 4 Type: Texture Length: 1
>   Set: 1 Binding: 5 Type: Texture Length: 1
>   Set: 1 Binding: 6 Type: Texture Length: 8
>   Set: 1 Binding: 7 Type: Texture Length: 8
>   Set: 1 Binding: 8 Type: StorageBuffer Length: 0
>   Set: 1 Binding: 9 Type: Texture Length: 1
>   Set: 1 Binding: 10 Type: Texture Length: 1
>   Set: 1 Binding: 11 Type: Texture Length: 1
>   Set: 1 Binding: 12 Type: Texture Length: 1
>   Set: 1 Binding: 13 Type: Texture Length: 1
>   Set: 1 Binding: 14 Type: Texture Length: 1
>   Set: 1 Binding: 15 Type: Texture Length: 1
>   Set: 1 Binding: 16 Type: Texture Length: 1
>   Set: 1 Binding: 17 Type: UniformBuffer Length: 896
>   Set: 1 Binding: 18 Type: Texture Length: 1
>   Set: 2 Binding: 0 Type: StorageBuffer Length: 0
>   Set: 3 Binding: 0 Type: UniformBuffer Length: 128
>   Set: 3 Binding: 1 Type: Texture Length: 1
>   Set: 3 Binding: 2 Type: Texture Length: 1
>   Set: 3 Binding: 3 Type: Texture Length: 1
>   Set: 3 Binding: 4 Type: Texture Length: 1
>   drivers/vulkan/rendering_device_vulkan.cpp:7153 - Condition "!uniform_set" is true.
>   Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
>   drivers/vulkan/rendering_device_vulkan.cpp:7153 - Condition "!uniform_set" is true.
>   Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
>   drivers/vulkan/rendering_device_vulkan.cpp:7153 - Condition "!uniform_set" is true.
>  

### Steps to reproduce

create a scene
add meshinstance -> make box
add a standard material -> check normal map.
go to the normal map import settings and check settings and reimport.
add the normal texture to the shader. and re-import.

Video: https://drive.google.com/file/d/1rgJrInhxweaKPx_D4kH6f37HMFQnoWwT/view?usp=sharing

**Comment by Calinou** [comment]
This was already reported in https://github.com/godotengine/godot/issues/48886 (it's from the same cause). However, the issue doesn't appear to be fixed yet, so I'll leave it open. I can still reproduce it here on `master` 85186bc0c.

This can be worked around by reloading the current scene after saving it (**Scene > Reload Saved Scene**).
