### ISSUE TITLE
Find next/prev doesn't move far when word selected

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#5136]
**Operating system or device - Godot version:**
Windows 10, compiled with 00bfdc8

**Issue description** (what happened, and what was expected):
Find next/prev doesn't move far when word selected

**Steps to reproduce:**
![find](https://cloud.githubusercontent.com/assets/8281454/15955168/360030cc-2f1a-11e6-99b1-081ad86f2c71.gif)

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
@neikeq ping ;)
