### ISSUE TITLE
VehicleWheel `steering` = 1 gives a 57.3 angle of turn.

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#51365]
### Godot version

4.0.dev.calinou(4cb406e02)(CI build of master branch)

### System information

(Deemed irrelevant)

### Issue description

This NEED to be changed to degrees instead of arbitrary values. Please either change it to degrees unit or have a way for developers to set the maximum steering angle.

Workaround(should make wheels rotate by 90 degrees):
```gdscript
## Amount of steering from 0.0 to 1.0. The maximum steering angle is defined by `max_steering_angle`
var steer := 1
var max_steering_angle := 90

func _process(delta):
	var steering_angle = steer * max_steering_angle
	# Steering 1 = 57.3 degree angle, GODOT PLEASE FIX!
	steering = steering_angle / 57.3
```

### Steps to reproduce

1. Get a VehicleWheel(parented to a VehicleBody?).
2. Set steering to 1
3. The wheel rotates by 57.3 degree

**Comment by akien-mga** [comment]
Like all angles changed through code, this expects a value in *radians*. It's not an arbitrary angle, the ratio between radians and degrees is `180/PI` i.e. ca. 57.3 °/rad.

**Comment by atirut-w** [comment]
> this expects a value in _radians_

Aeughhh there are so many places in the docs with unspecified units

**Comment by akien-mga** [comment]
Which ones specifically? Most angles should have "(in radians)" in their documentation, but some might have slipped like this one. It's easy to fix if we know which.

**Comment by atirut-w** [comment]
There are quite a few in the docs for Vehicle Body & Wheels. Engine force, brake, etc.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-docs/issues/5158, as the documentation issue is being tracked there.
