### ISSUE TITLE
Sprite3Ds disappear when PVS is enabled

### ISSUE THREAD

**Issue by 20kdc** [godotengine/godot#51386]
### Godot version

3.4.beta2

### System information

Ubuntu 20.04.2 LTS GLES2 Mesa 21.1.3 AMD Radeon(TM) Vega 3 Graphics (RAVEN2, DRM 3.38.0, 5.8.0-59-generic, LLVM 12.0.0)

### Issue description

Sprite3Ds disappear when PVS is enabled. A sample project has been given that demonstrates this - when culling is enabled, the sprites disappear.

### Steps to reproduce

To use the reproduction project, start it, then hit "Convert Rooms" (Enable PVS).
To look around, click the screen - this will trigger mouse-lock until you click it again. WASD moves around a small area.
Note that every few seconds, the camera will teleport between two rooms with different usages of sprites. All sprites are in portal mode Static and are included in bounds.

For as-of-yet unknown reasons, attempting to use the preview camera with culling enabled in the editor crashes Godot.

### Minimal reproduction project

[godot-bugreport-sprite3d-culling.zip](https://github.com/godotengine/godot/files/6950589/godot-bugreport-sprite3d-culling.zip)

**Comment by lawnjelly** [comment]
Ah yes, the sprites not working is for the simple reason I forgot Sprite3D existed. :grinning: I'll add it lol.
Not sure what the crash is about I'll try that right now.

**Comment by lawnjelly** [comment]
I worked out the crash, that was a simple mistake in the PVS reading so is fixed. I'll have a look at the Sprite3Ds now, for now if you set them to `portal_mode` ROAMING they seem to work (but they won't be as efficient as they should be, so I want to fix this).

**Comment by akien-mga** [comment]
Fixed by #51388 and #51396.
