### ISSUE TITLE
MY game is not responding!

### ISSUE THREAD

**Issue by CyberBlueCodes** [godotengine/godot#51398]
### Godot version

3.3.2

### System information

Windows 10, GLES2, intel hd graphics 3000, 64 bit

### Issue description

so i was making a top down rpg but when i ru my game , it doesnt respond

### Steps to reproduce

https://github.com/CyberBlueCodes/QFC

run scenes/world.tscn

**Comment by Calinou** [comment]
@CyberBlueCodes Can you reproduce this with any of the official [demo projects](https://github.com/godotengine/godot-demo-projects)?

**Comment by CyberBlueCodes** [comment]
Don't guess that I can do it with an demo project, but it does have a loop but it won't run infinitely, it is something that spawns skeleton within the parameters, the loop runs till the value will be under the parameters, and when I export it for Android it works fine but the skeletons don't spawn but if it runs by the editor it stops responding

**Comment by lawnjelly** [comment]
It appears like this is an infinite loop:

```
	while not valid_position:
		skeleton.position.x = spawn_area.position.x + rng.randf_range(0, spawn_area.size.x)
		skeleton.position.y = spawn_area.position.y + rng.randf_range(0, spawn_area.size.y)
		valid_position = test_position(skeleton.position)
```

**Comment by CyberBlueCodes** [comment]
Yes so sorry it was a silly mistake, I got the tilesets name wrong. sorry
