### ISSUE TITLE
Cannot blend the output of two animation state machines outputting the same animation using filter tracks

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#51408]
### Godot version

e010e05b3dd842ba86a68dee60e0d7be6f9aae50

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

This is a somewhat specific instance, but I encountered it actually became a pretty significant blocker for me. If you have a blend tree with multiple state machines outputting the same animation, but using a filter track to one apply that animation to specific bones, one of the animations will not play. This will however work if you're only blending multiple animations directly, it only fails when using state machines. Thought it may have been related to this issue since I investigated it and determined that it seems like it may be related to state machines somehow ending up with the same playback object (https://github.com/godotengine/godot/issues/45635), but I checked in my specific example and they do appear to have different playback objects.
Here's a screenshot to demonstrate the type of setup I'm talking about 
![godot windows tools 64_9bZrT9fBsy](https://user-images.githubusercontent.com/12756047/128644480-cfae5119-708f-4b37-a9cf-95c9c7208c56.png)

### Steps to reproduce

Import a model with multiple animations, add to a scene, create an animation tree with a blendtree as the root. Create two state machines containing the same animations and make sure they are outputting the same animation, connect the output of those nodes to a blend2 node using a filter mode to ensure it only affects a specific set of bones. When you do this, only one of the animations will play. This will only fail if they output the same animation, if one of the state machines is outputting a different animation, it should work without issue.

If you use examine the MRP, the expected behaviour is that both cubes should be oscilating up and down, but due to this bug, they are not.

### Minimal reproduction project

[animation_tree_parallel_state_machine_animation.zip](https://github.com/godotengine/godot/files/6951429/animation_tree_parallel_state_machine_animation.zip)

**Comment by SaracenOne** [comment]
Should also clarify that this problem appears to exist in the 3.x branch too, so I don't believe it is a recent regression.

**Comment by SaracenOne** [comment]
Also fails with additive nodes using a setup like this
![godot windows tools 64_LaW5qyFqkK](https://user-images.githubusercontent.com/12756047/128645684-0cb3fb29-2274-4853-9796-d4fd7f27ae64.png)

**Comment by SaracenOne** [comment]
Latest debugging is indicating that the problem might still be down to duplicate animation states. Still investigating
![devenv_iBA23qSR8v](https://user-images.githubusercontent.com/12756047/128721262-91f17e5e-1678-4b2f-ad73-0f0961d8cf98.png)

**Comment by SaracenOne** [comment]
Actually, it may not specifically be the whole state, but rather, track blends.

**Comment by SaracenOne** [comment]
Further info:
Basically, the way I have this set up is I have two state machines, but they're loaded externally. This means that both state machines share the same instance. Basically though, what is happening is the blend tree with the filters is responsible in the two inputs for setting up which tracks in the animation should be defined by the blend2 node's filter tracks. In a List called 'blends', it writes it directly to the animation node during processing. The problem arises is that since state machine B shares the same instance as state machine A, when it comes to writing the inverse blends for the second input, since both state machines are instances, if both state machines are outputting the same animation, the blend tracks from the first input are overwritten by the second, explaining why they can't run in parallel.
```float *blendw = p_node->blends.ptrw();```
It is a bug, but I guess quite an obscure one. Any suggestions on what might be the best way to go about fixing it?

**Comment by SaracenOne** [comment]
https://github.com/godotengine/godot/issues/51408
Fix here, but *might* introduce a performance penalty since it introduces new per-frame memory allocations. Requesting review.

**Comment by TokageItLab** [comment]
@SaracenOne Can you test #75759 whether it fix this issue or not?

**Comment by TokageItLab** [comment]
Tested, this bug was not fixed by https://github.com/godotengine/godot/pull/75759 and I have confirmed that the bug still exists.
