### ISSUE TITLE
I and @lyuma 's stance is that runtime support is achievable and wanted.

### ISSUE THREAD

**Issue by chachi85** [godotengine/godot#51406]
I and @lyuma 's stance is that runtime support is achievable and wanted.

The Godot Engine maintainers consensus from a few months ago is that runtime asset import is not desired and runtime templates should use the internal formats.

Since Godot Engine is consensus driven, we took the consensus to not have runtime asset loaders. @reduz and @BastiaanOlij were the last to have the runtime asset debate in my recollection. Maybe they can give an update on the runtime loader debate.

_Originally posted by @fire in https://github.com/godotengine/godot/issues/51383#issuecomment-894847181_

**Comment by pycbouh** [comment]
I'm not sure why you've decided to repost it like this, but the PR is a better place to discuss it. And if not, then the contributors chat.
