### ISSUE TITLE
Godot 3.4 theme editor has ' crash ' issue, atm . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot#51414]
### Godot version

Godot 3.4 beta 3 . .

### System information

Windows 10

### Issue description

The new theme editor, is sort-of MORE difficult to use, than in 3.3 . .

It's sort-of too difficult, to explain, made a video ( 10 minutes ), where one can see, that it just crashes, and is well even worse, ATM . . Then the Godot 3.3 theme editor . . Skip to end of video, 8:40 - 50 seconds, to see it crashing, when one tries to use, the new theme, one has made . . :OO . . . .

>> https://www.youtube.com/watch?v=UpFAPnz9Hbg

The video is a ten minute attempt, to make it work, goes over basically why it's really difficult, and in the end, after saving a theme, at about 8:50, it just crashes the program . . . So, the video sort-of shows the issues, and why it's a bit frustrating, to try and use it, or so . . . .

I'm trying my best, to make good use of Visual script and, being able to make a theme, so it becomes rock - solid, ' reliable ' and, fun . . is a big wish for me . . . The video explains, why it's now even MORE difficult, and well obscure, to make a custom theme, in Godot 3.4 beta 3 . . .

I like any update, to Godot and, I really appreciate someone is working on this, so any-way, thanks . . . <3

### Steps to reproduce

See video, basic problem is it crashes all the time, and now effectively doesn't work, compared to 3.3 that, was just sort-of buggy, hope you can fix it, for Godot 4, in some way or, so . . :OO

### Minimal reproduction project

Try and make a new theme, save it, and load it, as custom theme . . . For me, it crashes, no error message, can't find the documentation, and it went from difficult, to almost impossible . . There's no instant preview, in actual editor and, it crashes, so one can't use it, in any way . . That said, it's nice there's some work on it, bec. for me, it's important for creating a ' STABLE ', happy UX, so well, thx . . . .

**Comment by charlesmlamb** [comment]
The positive is, the theme editor is more advanced, and it's like a massive step, in the right direction . . .

The problem is, in the video, it's just confusing, how to use those features, to a new user, like it's gotten 3 x more complex and, no help, how to make it work . . .

After clicking every button, I'm not sure what 50 % of them do and, the one's that actually work, doesn't matter, bec. after saving it, then loading it, the them then sort-of crashes the program, and doesn't even work, compared to 3.3, at least on my computer, not sure if that's the problem, HP laptop, AMD 5800H, nVidia 3070 RTX, got it some weeks ago, as a present, so . . .

There's a lot, of positive, many improvements, imo . . But, it now has crash issues, and the complexity, is difficult, at least, thx . . . <3

**Comment by charlesmlamb** [comment]
So, 9 / 10 or, 10 / 10, for making the theme editor, more well - rounded, thx . . .

But, for some reason it crashes the program, when trying to use the theme, maybe I'm using it wrong, not sure <3

Well, it got better but, has a few bugs . . .

**Comment by timothyqiu** [comment]
Sounds like #51003 still happens in beta3.

**Comment by 7leodev** [comment]
It's present in linux when the editor is launched.

**Comment by pycbouh** [comment]
Should be resolved by https://github.com/godotengine/godot/pull/51646 and https://github.com/godotengine/godot/pull/51648
