### ISSUE TITLE
instanced rigid body is unaffected by physics after being changed to rigid from kinematic via script

### ISSUE THREAD

**Issue by Lexi-kelly** [godotengine/godot#51423]
### Godot version

3.3.2

### System information

Windows 10

### Issue description

loading a scene as an instance with a rigid body set to kinematic mode, then changing the rigid body to rigid mode via a script, causes it to change the mode correctly, but the rigid body does not fall.

expected:
it becomes affected by physics and falls

### Steps to reproduce

create a 3d scene with a spacial node, with a rigid body and mesh instance as children, save the rigid body as kinematic mode.
then instance the scene in the scene tree using a script, have it set the position up by 10, then change the mode to rigid using the same script, the instance does not fall.

**Comment by Calinou** [comment]
@Lexi-kelly Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
@Lexi-kelly Did you manage to find a solution to this issue? If so, please document it here to help other people who may be wondering about how to resolve this :slightly_smiling_face:
