### ISSUE TITLE
[Editor Bug] Particles Emission Shape switch bug

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#51428]
### Godot version

3.4 beta2, 3.4 beta3

### System information

MacOS 10.14.6 intel GPU GLES3

### Issue description

when switching Emission Shape from Sphere to Ring / Ring to Sphere or Point to Directed Points / Directed Points to Point , Editor won't update the particles shape

https://user-images.githubusercontent.com/64188282/128686527-6ddcac58-14c7-471e-9831-f422af956bd0.mov

### Steps to reproduce

create a Particles Node and setup it
change Emission Shape default Point to Directed Points, then change back to Point
or change Emission Shape to Sphere, then change to Ring and change back to Sphere

**Comment by akien-mga** [comment]
CC @QbieShay

**Comment by QbieShay** [comment]
On it, thanks for the report!
