### ISSUE TITLE
Control viewport doesn't get cropped when inside scroll container

### ISSUE THREAD

**Issue by TheoXD** [godotengine/godot#5142]
What happens is that when a control node with viewport is inside a scroll container - it never gets cropped. Test scene: http://blenderstars.com/uploads/tmp/viewport_bug.zip

**Comment by reduz** [comment]
this is seriosuly difficult to do with GLES2, planning to fix properly in GLES3 and then hack it back i GLES2

**Comment by reduz** [comment]
This was solved in 3.0, such a relief..
