### ISSUE TITLE
When Emission Shape is setting to Directed Points, Particles Emission won't work properly

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#51425]
### Godot version

3.4 beta2, 3.4 beta3

### System information

MacOS 10.14.6 intel GPU GLES3

### Issue description

https://user-images.githubusercontent.com/64188282/128682725-63e04a60-4ac5-48dc-816c-2032cef0fd19.mov

![Screen Shot 2021-08-09 at 4 13 24 PM](https://user-images.githubusercontent.com/64188282/128682795-9daa622a-1e71-41fb-b5a1-3a6864b9139e.png)

![Screen Shot 2021-08-09 at 4 13 36 PM](https://user-images.githubusercontent.com/64188282/128682804-aae0d385-6382-40b4-bb38-9a789b5a815a.png)

### Steps to reproduce

see the minimal reproduction project

### Minimal reproduction project

[particles.zip](https://github.com/godotengine/godot/files/6953168/particles.zip)

**Comment by Calinou** [comment]
This is likely the same cause as https://github.com/godotengine/godot/issues/51424.

**Comment by akien-mga** [comment]
Indeed, that's the same error as #51424.
