### ISSUE TITLE
Sync Spanish translations from weblate

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#5143]
The Spanish translation files in this repo are not up to date with the ones in weblate. 

Some users are testing the latest builds and using them to translate the documentation but they've found some texts are wrong or out of place. This doesn't happen if I build using the latest files from weblate.

**Comment by vnen** [comment]
The translation is not synced with this repository automatically (for the sake of our Git history). And Weblate is very new for us, we still have to find a good way to keep it in sync. We'll certainly sync the translations before the 2.1 alpha build (which is coming soon).

People making custom builds should download the translation `.po` file and add to the `tools/translations` folder of Godot source before building.

**Comment by noidexe** [comment]
This can be closed since the latest commits to master are integrating weblate translations regularly.

**Comment by akien-mga** [comment]
Indeed.
