### ISSUE TITLE
Feature: Option for TextureFrame to keep aspect ratio when expanding

### ISSUE THREAD

**Issue by TheoXD** [godotengine/godot#5144]
TextureFrame can be stretched (expanded), but it is not always desired. Would be great if it could have another stretch mode that would also preserve it's original aspect ratio. 

A new node with equal functionality can also be an option, for example if HBoxContainer has cells that are 2x3 in size, if that node is inside it gets shrinked down to 2x2 and centered. (more like it's children become shrinked)

Something in this direction (just a quick implementation out of CenterContainer)
![fixed_container](https://cloud.githubusercontent.com/assets/6633998/15974735/53776096-2f4a-11e6-8adc-241ee53a1f02.gif)

**Comment by reduz** [comment]
this already exist in 2.1, check the stretch_mode property

**Comment by TheoXD** [comment]
@reduz, I hope you're not talking about project settings, viewport stretching is out of the picture for me since I'm using viewports, and 2d stretching is awful. If you mean stretch_mode in textureframe, I tried italready, I haven't managed to scale stars the same way as in the picture without using scripts. Watch closely how they scale accordingly. It's making use of all the space available by hboxcontainer, without changing aspect ratio.

**Comment by reduz** [comment]
sorry, I completely misunderstood what you wanted to do, adding this asap

**Comment by reduz** [comment]
ok should be done now

**Comment by TheoXD** [comment]
Thanks, Flash xD I made a different node for this purpose earlier, but seems like an overkill, too many nodes already.
