### ISSUE TITLE
Vulkan warning after installing vulkan-sdk probably due outdated Vulkan Loader

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#51444]
### Godot version

4.0.dev.custom_build. f2efa6f4f

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

After installing the latest `vulkan-sdk`, I got this new warnings 
```
ARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loaderAddLayerProperties: /usr/share/vulkan/explicit_layer.d/VkLayer_device_simulation.json invalid layer manifest file version 1.2.0.  May cause errors.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 182720000
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:154)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loaderAddLayerProperties: /usr/share/vulkan/explicit_layer.d/VkLayer_khronos_synchronization2.json invalid layer manifest file version 1.2.0.  May cause errors.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 182720000
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:154)
```

looks that this warnings should be fixed after updating Vulkan Loader
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2729
https://github.com/KhronosGroup/Vulkan-Loader/pull/567

### Steps to reproduce

Run Godot with validation layers installed

**Comment by bruvzg** [comment]
Vulkan loader used by Godot is outdated (and new versions of the loader do not support static linking).

Maybe we should remove the built-in loader entirely and link to the system one (or directly link MoltenVK in case of macOS). The only issue, for Windows and macOS we'll need to install Vulkan SDK in the CI and release build  containers.

**Comment by akien-mga** [comment]
Saw this earlier today: https://mobile.twitter.com/SaschaWillems2/status/1424603199915401219

I haven't looked into it but the Renderdoc dev also advocates for using volk, we should have a look IMO.
