### ISSUE TITLE
3.4.beta3 mono object reference error

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#51450]
### Godot version

3.4.beta3 mono

### System information

Debian 10

### Issue description

I have this weird error in any projects. 

```
Godot Engine v3.4.beta3.mono.official (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
 modules/mono/mono_gd/gd_mono_utils.cpp:369 - System.NullReferenceException: Object reference not set to an instance of an object
 modules/mono/mono_gd/gd_mono_utils.cpp:369 - System.NullReferenceException: Object reference not set to an instance of an object
--- GDScript language server sstarted
```
In same projects I don't have this error if I use 3.4.beta2 mono
Also in the beta3 the "Build" menu in the top-right side is missing - related to this error I guess.
At same time is missing the autocompletion  during  GetNode<> in visual studio code. For example when I start to write the follow code: `GetNode<Label>(` in beta3 the autocompletion doesn't work.

### Steps to reproduce

I just open a projects where I was working with beta2

### Minimal reproduction project

NA

**Comment by akien-mga** [comment]
When did you download the 3.4.beta3.mono version? The first build I uploaded had a critical bug, and I fixed it up the next day (2021-08-07 @ 13:00 UTC). If you downloaded before this, redownloading it should give you the fixed version.

**Comment by git2013vb** [comment]
You right. :) 
I downloaded it again and it work fine so far.
Thanks
