### ISSUE TITLE
Refocusing a mouse-captured window by clicking the title bar moves the window

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51468]
### Godot version

master (f3ddc14d3)

### System information

macOS 11.5.1

### Issue description

#51405 moves the captured mouse cursor to the center when window gain focus. But when I switch back to the game by clicking the window's title bar, the window moves.

I think this is because `windowDidBecomeKey` is called when the mouse is down. When moving the captured mouse to the center of the window, it's interpreted as dragging the window downward.

### Steps to reproduce

1. Run a project that captures the mouse
2. Tab out the running game
3. Click the game on its title bar

**Comment by akien-mga** [comment]
@RPicster This was a macOS issue and was fixed 2.5 years ago. So even if you experience similar symptoms on another OS, it doesn't mean it's the same bug (bug == cause, not symptom). Could you open a new bug report with details on your reproduction case?

**Comment by Suwit2** [comment]
🪟 แก้ปัญหา Godot 4.x + Windows: ตรวจจับการลาก Title Bar แบบ 100% ด้วย GDWatcher
บทนำ

ใน Godot 4.x (และทุกเวอร์ชัน) การตรวจจับว่าผู้ใช้ ลาก Title Bar ของหน้าต่างเกมแล้วปล่อย เป็นเรื่องที่ทำได้ยากมาก เพราะ Windows เป็นคนจัดการ Title Bar ทั้งหมด และ Godot ไม่มี Signal หรือ Event ให้รับรู้จังหวะนี้โดยตรง

    _input() ใช้ไม่ได้ เพราะ Title Bar อยู่นอก Viewport

    _process() + เช็คตำแหน่ง ใช้ได้ แต่ไม่แม่นยำ (40/100)

    ไม่มี position_changed Signal ใน Window Class

    ไม่มี Event สำหรับ WM_ENTERSIZEMOVE / WM_EXITSIZEMOVE

ทางออก: GDWatcher (โปรแกรมเฝ้าจอ)

เราใช้แนวทาง Windows Hook ผ่าน SetWinEventHook เพื่อดักจับ Event EVENT_SYSTEM_MOVESIZESTART และ EVENT_SYSTEM_MOVESIZEEND ซึ่ง Windows ส่งออกมาเมื่อหน้าต่างใดๆ เริ่มหรือหยุดการเคลื่อนย้าย
ข้อดี

    ✅ ตรวจจับได้ 100%

    ✅ ไม่มี Delay

    ✅ ใช้ได้ทั้ง Editor และ Export

    ✅ ใช้ Process ID เพื่อเชื่อมโยงกับเกม

🧩 โค้ดฝั่ง GDWatcher (C# .NET 8)
csharp

using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Threading;

class Program
{
    [DllImport("user32.dll")]
    static extern IntPtr SetWinEventHook(uint eventMin, uint eventMax, IntPtr hmod, WinEventDelegate lpfn, uint idProcess, uint idThread, uint dwFlags);

    [DllImport("user32.dll")]
    static extern bool UnhookWinEvent(IntPtr hWinEventHook);

    [DllImport("user32.dll")]
    static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint lpdwProcessId);

    delegate void WinEventDelegate(IntPtr hWinEventHook, uint eventType, IntPtr hwnd, int idObject, int idChild, uint dwEventThread, uint dwmsEventTime);

    const uint EVENT_SYSTEM_MOVESIZESTART = 0x000A;
    const uint EVENT_SYSTEM_MOVESIZEEND = 0x000B;
    const uint WINEVENT_OUTOFCONTEXT = 0x0000;
    const uint WINEVENT_SKIPOWNPROCESS = 0x0002;

    static IntPtr _hook = IntPtr.Zero;
    static bool _isDragging = false;
    static int _targetPid = -1;
    static Process _targetProcess = null;

    static void Main(string[] args)
    {
        if (args.Length > 0 && args[0] == "-pid" && args.Length > 1)
        {
            if (!int.TryParse(args[1], out _targetPid))
            {
                Console.WriteLine("❌ PID ไม่ถูกต้อง");
                return;
            }
        }
        else
        {
            Console.WriteLine("❌ ต้องระบุ -pid <Process ID>");
            return;
        }

        try
        {
            _targetProcess = Process.GetProcessById(_targetPid);
            Console.WriteLine($"👀 GDWatcher เริ่มทำงาน... PID: {_targetPid} ({_targetProcess.ProcessName})");
        }
        catch (ArgumentException)
        {
            Console.WriteLine($"⚠️ ไม่พบ Process ID: {_targetPid}");
            Console.WriteLine("ปิดตัวใน 3... 2... 1...");
            Environment.Exit(0);
        }

        WinEventDelegate callback = new WinEventDelegate(WinEventProc);
        GCHandle callbackHandle = GCHandle.Alloc(callback);

        _hook = SetWinEventHook(
            EVENT_SYSTEM_MOVESIZESTART,
            EVENT_SYSTEM_MOVESIZEEND,
            IntPtr.Zero,
            callback,
            0,
            0,
            WINEVENT_OUTOFCONTEXT | WINEVENT_SKIPOWNPROCESS
        );

        if (_hook == IntPtr.Zero)
        {
            Console.WriteLine("❌ ติดตั้ง Hook ไม่สำเร็จ!");
            return;
        }

        Console.WriteLine("✅ กำลังรอ Event...\n");

        while (true)
        {
            if (!IsGameStillRunning())
            {
                Console.WriteLine("👋 เกมปิดไปแล้ว GDWatcher ขอลา!");
                break;
            }

            if (GetMessage(out var msg, IntPtr.Zero, 0, 0) == 0) break;
            TranslateMessage(ref msg);
            DispatchMessage(ref msg);
        }

        UnhookWinEvent(_hook);
        callbackHandle.Free();
    }

    static bool IsGameStillRunning()
    {
        try { return _targetProcess != null && !_targetProcess.HasExited; }
        catch { return false; }
    }

    static void WinEventProc(IntPtr hWinEventHook, uint eventType, IntPtr hwnd, int idObject, int idChild, uint dwEventThread, uint dwmsEventTime)
    {
        GetWindowThreadProcessId(hwnd, out uint pid);
        if ((int)pid != _targetPid) return;

        if (eventType == EVENT_SYSTEM_MOVESIZESTART)
        {
            _isDragging = true;
            Console.WriteLine($"🔄 เริ่มลาก");
        }
        else if (eventType == EVENT_SYSTEM_MOVESIZEEND && _isDragging)
        {
            _isDragging = false;
            Console.WriteLine("✅ DRAG_END");
            Console.WriteLine("DRAG_END");
        }
    }

    [DllImport("user32.dll")]
    private static extern int GetMessage(out MSG lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax);

    [DllImport("user32.dll")]
    private static extern bool TranslateMessage(ref MSG lpMsg);

    [DllImport("user32.dll")]
    private static extern IntPtr DispatchMessage(ref MSG lpMsg);

    [StructLayout(LayoutKind.Sequential)]
    private struct MSG { public IntPtr hwnd; public uint message; public IntPtr wParam; public IntPtr lParam; public uint time; public POINT pt; }

    [StructLayout(LayoutKind.Sequential)]
    private struct POINT { public int x; public int y; }
}

🧩 โค้ดฝั่ง Godot (C#)
csharp

using Godot;
using System;
using System.Diagnostics;

public partial class WatcherManager : Node
{
    private Process _watcherProcess;

    public override void _Ready()
    {
        StartWatcher();
    }

    private void StartWatcher()
    {
        int gamePid = Process.GetCurrentProcess().Id;
        string watcherPath = ProjectSettings.GlobalizePath("res://Watcher/GDWatcher.exe");

        if (!System.IO.File.Exists(watcherPath))
        {
            GD.PrintErr("❌ ไม่พบ GDWatcher.exe");
            return;
        }

        _watcherProcess = new Process();
        _watcherProcess.StartInfo = new ProcessStartInfo
        {
            FileName = watcherPath,
            Arguments = $"-pid {gamePid}",
            UseShellExecute = false,
            RedirectStandardOutput = true,
            CreateNoWindow = true,
        };

        _watcherProcess.OutputDataReceived += (sender, e) =>
        {
            if (e.Data == "DRAG_END")
            {
                CallDeferred(nameof(OnWindowDropped));
            }
        };

        _watcherProcess.Start();
        _watcherProcess.BeginOutputReadLine();
    }

    private void OnWindowDropped()
    {
        int newScreen = DisplayServer.WindowGetCurrentScreen();
        GD.Print($"📌 หน้าต่างถูกย้ายไปจอ {newScreen}");
        // อัปเดต GameData หรือ UI
    }

    public override void _ExitTree()
    {
        if (_watcherProcess != null && !_watcherProcess.HasExited)
        {
            _watcherProcess.Kill();
            _watcherProcess.Dispose();
        }
    }
}

📌 สรุปขั้นตอน

    Build GDWatcher.exe เป็น Single-file

    วางไว้ในโฟลเดอร์ Watcher/ ในโปรเจกต์ Godot

    สร้าง WatcherManager เชื่อมต่อกับ GDWatcher

    ลาก Title Bar → รับ DRAG_END → อัปเดต UI

🔗 เครดิต

    แนวคิด: จากปัญหาที่เจอใน Godot 4.x

    วิธีแก้: Windows Hook + Process ID

    โค้ด: DeepSeek 4.0 Flash (เป็นผู้ช่วย Gen โค้ด)

    ทดสอบ: บน Godot 4.7 + Windows 11

ถ้าใครเจอปัญหาเดียวกัน เอาไปใช้ได้เลยครับ! 😄
หมายเหตุเพิ่มเติม

    ต้อง Build GDWatcher.exe แบบ Self-contained (Single-file)

    ใช้ -pid แทนชื่อ Process เพื่อความแม่นยำ

    Watcher จะปิดตัวเองเมื่อเกมหายไป

    ถ้าใช้ Editor กด Stop → Watcher อาจค้าง (ไม่ต้องสน เพราะตอน Export ไม่มีปุ่ม Stop)

จบบทความ! 🚀
ใครเอาไปใช้แล้วได้ผล บอกให้รู้ด้วยนะครับ! 😄
