### ISSUE TITLE
Sprite3D modulate broken

### ISSUE THREAD

**Issue by tylerwilbanks** [godotengine/godot#51460]
### Godot version

3.3.2(stable)

### System information

windows 10, gles3,
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL ES Batching: ON

### Issue description

I used to be able to make an enemy flash white by using a tween and setting the modulate to something like Color(10, 10, 10). Now it seems that sprites can no longer become brighter than Color(1, 1, 1).

As far as I'm aware there are no import settings that can fix this behavior. u/goldotaskquestions on reddit had this to say about it:  https://www.reddit.com/r/godot/comments/p0tvgo/v332_sprite_3d_modulate_broken/h89s0r9?utm_source=share&utm_medium=web2x&context=3

### Steps to reproduce

Create a Sprite3D node (you can just use icon.png as a texture), set the modulate mode to raw, then move the sliders to values greater than 1 and see the sprite not be affected at all. You can get colors other than white, but they do not seem to go above the 1 brightness threshold.

https://user-images.githubusercontent.com/85759611/128804038-7d12ec80-e9e3-425b-b4b4-e0675f857997.mp4

### Minimal reproduction project

[sprite3d modulate broken.zip](https://github.com/godotengine/godot/files/6958728/sprite3d.modulate.broken.zip)

**Comment by clayjohn** [comment]
I just submitted a PR to fix this. You can expect a fix in the upcoming 3.3.3 and 3.4.0 releases :)

**Comment by akien-mga** [comment]
Fixed by #51462.
