### ISSUE TITLE
Importing textures in extremely slow and does not display proper progress

### ISSUE THREAD

**Issue by victorbstan** [godotengine/godot#51475]
### Godot version

3.3.3.rc1

### System information

Windows 10 

### Issue description

Why is importing textures into Godot so slow? It's slower than in any other engine, UE4/Unity, I'm just trying to imports this texture pack https://godotengine.org/asset-library/asset/781 it's maxing out all my 12 cores and taking a long time at that. Not to mention, simply moving the textures to another folder within the editor goes through the whole re-import process again, doubling the time. Shouldn't moving files around not have anything to do with importing? I'm using 3.3.3.rc1 but this has also been an issue in 3.2

### Steps to reproduce

1. download asset https://godotengine.org/asset-library/asset/781 and import from AssetLib tab in Godot. Wait... a very long time while 100% of CPU is used and progress bar is stuck at the very first texture (no progress display update). I would expect importing progress to be properly shown, and that it should be much faster especially if it consumes all CPU resources on a high-end PC.

2. After importin is finished. Make a new folder in editor and move the textures asset to the new folder within the FileSystem panel, the import process begins anew and takes just as long as the original import process. I would expect that it should not be going through the import process again after already having imported the files, simply to move them around.

### Minimal reproduction project

I have not included a minimal project as any new project would do, and the steps described for reproducing.

**Comment by Calinou** [comment]
If you only target desktop platforms, consider disabling ETC2 compression in the Project Settings.

**Comment by LightningAA** [comment]
Possibly also related to https://github.com/godotengine/godot-proposals/issues/280

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/280.
