### ISSUE TITLE
GDScript 2.0: Unclear error message when referencing non-existant node

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#51506]
### Godot version

current master (https://github.com/godotengine/godot/commit/688228030850005f84d7b51a527bc779d76b905e)

### System information

Windows 10, should be irrelevant

### Issue description

Placing the below in a script on the root node of an otherwise empty, just freshly created main scene leads to a lot of error spam due do the HTTPRequest node not existing:
```
func _ready():
	$HTTPRequest.request_completed.connect(self._on_request_completed)
```

That this errors is of course expected.
However, I'd expect the error to be somewhere along the lines of `Referenced node HTTPRequest does not exist`, and also to only get this error once.

Instead, this is spammed in the console dozens of times:
`ERROR: Native class GDScriptNativeClass used in script doesn't exist or isn't exposed.`
(`at modules\gdscript\gdscript_analyzer.cpp:3293`)

**Notably, this error is emitted on the CLI, but I don't get _any_ error whatsoever inside the editor.**

### Steps to reproduce

See above.

**Comment by Chaosus** [comment]
A similar error emits when the `material_override` property has been referenced inside a script attached to (for example) `MeshInstance`.

**Comment by Maran23** [comment]
Same error happens for me as well while using a global singleton (or I may miss something):

![image](https://user-images.githubusercontent.com/66004280/146663059-50c9bdb1-c9ef-49d4-a91c-8e600ef7a393.png)
![image](https://user-images.githubusercontent.com/66004280/146663063-cbfe9ca6-a595-44be-aaec-41077fd15165.png)
![image](https://user-images.githubusercontent.com/66004280/146663064-64ffc378-b248-4393-8478-6c17ee39ffb9.png)

Game is not starting with the following message:
`Native class res://Game.gd.FOOD used in script doesn't exist or isn't exposed.`

**Comment by ShawkMusic** [comment]
I'm getting this error too. How am I supposed to solve this?

**Comment by gustavi** [comment]
Restarting the Editor may be?

**Comment by vnen** [comment]
I cannot reproduce this, it was probably fixed since the report.
