### ISSUE TITLE
str2var error message not clear

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#5150]
**Operating system or device - Godot version:**
Ubuntu 16.04

**Issue description** (what happened, and what was expected):
ERROR
Invalid type in built-in function 'str2var'. Cannot convert argument 1 from String to String.

**Steps to reproduce:**
var test = 100
print(str2var('test'))

**Comment by vnen** [comment]
`str2var()` is not supposed to be used that way. But I'll keep the bug as the error message is not clear.

`str2var()` along with `var2str()` is a way to convert simple values between strings and variants (to show values or parse from input).
