### ISSUE TITLE
Starting Godot sometimes brings up the macOS Dock

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51504]
### Godot version

3.4.beta.custom_build.03c41fa34, v4.0.dev.custom_build [a902f7606]

### System information

macOS 11.5.1

### Issue description

Sometimes when starting the editor or a game, the macOS Dock is automatically shown (normally hidden at the bottom of the screen).

My mouse cursor is not moved during this process. And I have to move the mouse cursor to the Dock and then move away to hide it.

Not sure what the exact criteria are, but it happens from time to time since a few weeks ago.

### Steps to reproduce

Start the editor or run a game from the editor on macOS.

**Comment by timothyqiu** [comment]
Ah, I mean the macOS Dock.

**Comment by akien-mga** [comment]
CC @godotengine/macos

**Comment by timothyqiu** [comment]
It's standalone. Thanks for the explanation.

I recently switched from using stable to 3.x in order to utilize the portal occlusion, I think that's why it started to happen since "a few weeks ago" :)
