### ISSUE TITLE
Default sprite name changing in AnimatedSprite

### ISSUE THREAD

**Issue by Momfus** [godotengine/godot#5152]
**Operating system or device - Godot version:** Linux Mint 17.3 - Godot 2.1

**Issue description**:

When you have a sprite associated with a node and you change the name "default ", then you can't see the sprite on screen.

If this should not be changed ( because  one of the sprites must be named default ), you'd better don't let the user the possibily of change the name of the sprite.

![image](https://cloud.githubusercontent.com/assets/19497492/15982078/a09b1574-2f55-11e6-8f60-bf469d35b686.png)

**Comment by vnen** [comment]
As I said on IRC, you can change the name of the animation, but then you also have to manually change the selected animation on the AnimatedSprite.

I don't know if it's possible to change the selected animation automatically (as a single SpriteFrames resource can be used in many AnimatedSprite nodes).

(I'm not sure how to tag this)

**Comment by reduz** [comment]
maybe we should detect this special case somehow and rename it in the node too, but if the spriteframes is used somewhere else, it won't be detected

**Comment by reduz** [comment]
made it more user friendly
