### ISSUE TITLE
3.4.beta2: Crash in ResourceImporterTexture:_save_stex

### ISSUE THREAD

**Issue by ChainedLupine** [godotengine/godot#51535]
### Godot version

3.4.beta 2 (and 3 and presumably 1)

### System information

Windows 10, Godot compiled under x86_64-w64-mingw32-gcc 10-posix 20210110

### Issue description

There appears to be an issue with the new webp encoding which was introduced in 3.4 beta.  It is the new default lossless encoder now and is interacting with my project causing crashes.

I am receiving crashes when importing certain -- but not all -- PNGs.  I finally narrowed it down to one PNG that will introduce the crash, which I have included as the only image (aside from the default icon.png) in my example project.

I'm not able to get a good stack trace as it ends up as a SIGSEGV and smashes it, but I was able to step through _save_stex up to the point where the webp packer is called.

```
284                                     if (use_webp) {
285                                             data = Image::webp_lossless_packer(image);  // <-- crash
```

Info:

```
Thread 1 hit Breakpoint 4, ResourceImporterTexture::_save_stex (this=0x60bf1000, p_image=..., p_to_path=..., p_compress_mode=0, p_lossy_quality=0.699999988,     
    p_vram_compression=Image::COMPRESS_S3TC, p_mipmaps=false, p_texture_flags=4, p_streamable=false, p_detect_3d=true, p_detect_srgb=true, p_force_rgbe=false,   
    p_detect_normal=true, p_force_normal=false, p_force_po2_for_compressed=false) at editor/import/resource_importer_texture.cpp:285                             
285                                             data = Image::webp_lossless_packer(image);                                                                       
(gdb) info locals                                                                                                                                                
data = {alloc = 0x0}                                                                                                                                             
data_len = 0                                                                                                                                                     
r = {<PoolVector<unsigned char>::Access> = {_vptr.Access = 0x2b08b0c0, alloc = 0x3c, mem = 0x2b08ab16 ""}, <No data fields>}                                     
i = 0                                                                                                                                                            
lossless_force_png = false                                                                                                                                       
use_webp = true                                                                                                                                                  
image = {reference = 0x48fdeed0}                                                                                                                                 
mmc = 1                                                                                                                                                          
f = 0x48fddd30                                                                                                                                                   
__FUNCTION__ = "_save_stex"                                                                                                                                      
resize_to_po2 = false                                                                                                                                            
format = 119537664                                                                                                                                               
```

### Steps to reproduce

* Import example project in 3.4 beta, and it gives an immediate crash.

Alternative:

* Import example project into 3.3.2 stable.  Works OK.
* Load project into 3.4 beta, and it works.  It's only the import which causes the crash.

### Minimal reproduction project

[godot_3.4_beta3_png_stex_save_crash.zip](https://github.com/godotengine/godot/files/6972062/godot_3.4_beta3_png_stex_save_crash.zip)

**Comment by akien-mga** [comment]
CC @mortarroad

**Comment by akien-mga** [comment]
I don't seem to reproduce the crash with the MRP either, on Linux using the official 3.4 beta 3 binaries. I tried the Windows version in Wine and no crash either.

> Windows 10, Godot compiled under x86_64-w64-mingw32-gcc 10-posix 20210110

Is that a custom build? Can you try official binaries from https://downloads.tuxfamily.org/godotengine/3.4/beta3/ ?

**Comment by ChainedLupine** [comment]
@akien-mga  Originally, when I encountered the crash in large game project with the custom build, I went back and tried the binaries from the website.  The crash still occurred but it wasn't as predictable as the case I distilled for the example project with the custom build.  I admit I did not try the original binary on the example project but yes I also see that it does not crash.

While I do use a custom build of Godot with the Goost plugin and Zylann's Voxel engine, I reverted everything back to just a stock 3.4 beta 3 checkout and re-built.  I can still reproduce the crash with the example file.

I'm including my mingw32-gcc debug-enabled binary here: [link to my site since binary is too big for github issues](http://www.chainedlupine.com/temp/godotototo/godot.windows.tools.64.exe.zip)

I do my builds from a container based on debian stretch-slim with `mingw-w64` and `python3` installed (plus related Godot deps).  My Scons config was just: `scons -j4 platform=windows bits=64 tools=yes target=debug`

I am going to checkout 3.4 beta 3 onto my local machine and compile via MSVC19 and see if it crashes there, too.

**Comment by ChainedLupine** [comment]
Does not reproduce on debug build from MSVC19.  🤒  I am going to create a WSL2 instance on my Windows machine with a complete fresh install of Debian Stretch and setup Mingw64 and all, and test that build to see if this a Mingw64 issue.

**Comment by ChainedLupine** [comment]
Okay after lots of different build configs and setups I found out the cause.  I've posted a PR for master here: https://github.com/godotengine/godot/pull/51644

The gist of it is that if you have a` custom.py` configuration and disable webp, then ResourceImportTexture::_save_stex will always crash on a new project as it defaults to relying upon `modules/webp/image_loader_webp.cpp`
