### ISSUE TITLE
Behaviour of zooming in 2D editor is not correct

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#51542]
### Godot version

v4.0.dev.custom_build [37230dbb1]

### System information

Windows 11, Vulkan

### Issue description

Can't scroll the zooming value back when it's too small/big. The value goes the opposite way exponentially. Have to click on the minus and plus icons to bring it back.

![zoom_in](https://user-images.githubusercontent.com/28705694/129132593-63b6a923-8cfa-4925-9bc2-957206dbbbe7.gif)

![zoom_out](https://user-images.githubusercontent.com/28705694/129132597-577f97b0-1cda-48d4-b283-3707eb074152.gif)

### Steps to reproduce

Zoom in/out in the 2D editor to some extent, then you can't zoom back.

### Minimal reproduction project

No need.

**Comment by danielkariv** [comment]
I tried to reproduce this issue on the newest build from hugo website (f32c04f3), but it seems to got fix by having a limit for zooming in and out (0.4% to 6400%).

**Comment by Ayush-singla27** [comment]
Has this bug been fixed? cause i am unable to reproduce it. In 2D node there is a limit of 0.8% (minimum) to 12800% (maximum)

**Comment by akien-mga** [comment]
This was fixed by https://github.com/godotengine/godot/pull/51962.
