### ISSUE TITLE
Regression when KinematicBody is on wall

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51545]
### Godot version

3.x (dd30944)

### System information

macOS 11.5.1

### Issue description

I have a KinematicBody that moves towards a wall. i.e. gravity and the movement towards the wall are added to form the argument of `move_and_slide`.

![vec](https://user-images.githubusercontent.com/372476/129144870-11bcb34f-5eb1-4d0a-84c2-441172f21d0b.png)

When the KinematicBody reaches the wall:

* Before: `is_on_floor()` stays true, which is expected.
* Since #51458 was merged: `is_on_floor()` becomes false.

### Steps to reproduce

Run the MRP and watch the labels change.

### Minimal reproduction project

[OnFloor.zip](https://github.com/godotengine/godot/files/6973195/OnFloor.zip)

**Comment by akien-mga** [comment]
CC @pouleyKetchoupp @fabriceci

**Comment by fabriceci** [comment]
@timothyqiu Thanks for the clean and clear project/description. It's fixed, if you need a workaround until the next beta, you can simply use `move_and_slide_with_snap` instead of `move_and_slide`.

**Comment by akien-mga** [comment]
Fixed by #51556.
