### ISSUE TITLE
HTTPClient SSL does not work

### ISSUE THREAD

**Issue by Catprog** [godotengine/godot#5154]
**Operating system or device - Godot version:**
Windows V2.03.stable

**Issue description** (what happened, and what was expected):
HTTPClient will crash if SSL is used

**Steps to reproduce:**
var http = HTTPClient.new()
http.connect("google.com,16325,true,true) 
while( http.get_status()==HTTPClient.STATUS_CONNECTING or http.get_status()==HTTPClient.STATUS_RESOLVING):
		http.poll()

**Link to minimal example project** (optional but very welcome):

** Solution I used to fix it ***
Version: Windows V2.1.alpha
Uncomment line 319 of SConstruct (I think it needs more work then this which is why I am not pushing it in a git push.) and then compile

**Comment by akien-mga** [comment]
Do you mean uncomment the line ``#		env.Append(CPPPATH=['#drivers/builtin_openssl2'])``?

**Comment by Catprog** [comment]
Yes that is the line.

**Comment by akien-mga** [comment]
That's weird as openssl is builtin by default on Windows.
@punto- @vnen Seems like it could be another issue related to splitting the drivers into their own environment.

**Comment by vnen** [comment]
Now that I looked at this better, seems the same as #2157 and I thought this was fixed already, Isn't the asset lib is using SSL?

**Comment by vnen** [comment]
I tested this and it's not an issue with the drivers environment in SCons. This does not crash for me, but it hangs forever in `CONNECTING` status. If I use the proper HTTPS port (443) then it fails with the same console error that comes from the Asset Library: `Some I/O error occurred. The OpenSSL error queue may contain more information on the error.`

**Comment by reduz** [comment]
We just added SNI support, maybe this fixes the issue?

**Comment by Catprog** [comment]
I can confirm that compiling with the latest code has fixed the issue.

**Comment by reduz** [comment]
hooray \o/
