### ISSUE TITLE
OS.get_system_time_secs() result is not in seconds

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5155]
Tested on Windows 10 with Godot 2.0.3

If I try to print the result of `OS.get_system_time_secs()` every frame, I get this result:
```
Time = -1182457248
Time = -1182287248
Time = -1182117248
Time = -1181947248
Time = -1181777248
Time = -1181617248
Time = -1181447248
Time = -1181297248
Time = -1181127248
Time = -1180957248
Time = -1180787248
...
```
Which is not in seconds, because it increases by thousands per frame.

The method is also undocumented, so maybe the function has the wrong name, or is obsolete?

Edit: I see there was a closed issue about this: https://github.com/godotengine/godot/issues/3143
However, this function is supposed to have been removed?

**Comment by vnen** [comment]
I'm not sure what `OS.get_system_time_secs()` is supposed to do. In Linux it has the same output as `OS.get_unix_time()`.
