### ISSUE TITLE
Incorrect rendering of PanoramaSky texture

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#51563]
### Godot version

v4.0.dev.custom_build [7188cb601]

### System information

Windows 11, Vulkan

### Issue description

3.4
![image](https://user-images.githubusercontent.com/28705694/129189604-d16ab045-929c-4183-a8b5-b2c5f2c5e79a.png)

4.0
![image](https://user-images.githubusercontent.com/28705694/129189652-7f04e3ce-d772-4747-bd9c-68b18d1dc0de.png)

### Steps to reproduce

Just use ParonomaSky.

### Minimal reproduction project

[ParonomaSky Test.zip](https://github.com/godotengine/godot/files/6979334/ParonomaSky.Test.zip)

**Comment by clayjohn** [comment]
Are you seeing those banding artifacts in the viewport, or is that a result of your screen capture method?

**Comment by Calinou** [comment]
Can you reproduce this if you select the panorama texture in the FileSystem dock, go to the Import dock, set the compression mode to **Lossless** then click **Reimport**

**Comment by floppyhammer** [comment]
@clayjohn It's exactly how it looks on my screen.
@Calinou With Lossless, it looks slightly better but is still worse than how it looks in 3.4.

![image](https://user-images.githubusercontent.com/28705694/129289078-85894f0d-b2b9-49b2-8fb6-af09a27d92bc.png)

I've attached a minimal project so you guys could test it out.
