### ISSUE TITLE
Hyperlinks in editor documentation tooltips (EditorHelpBit) are too dark to read

### ISSUE THREAD

**Issue by Whimfoome** [godotengine/godot#51561]
### Godot version

v4.0.dev.20210811.official [7188cb601]

### System information

Windows 10, AMD R9 280X, Vulkan

### Issue description

When hovering over something over the editor, most of the time there is a hint.
Some hints have links on them, that can be clicked.
Well, in Godot 4, these links are too dark to read, I don't know if it is a graphical issue or theme issue and/or if I can change the color manually.

Here's how they look in Godot 3.4 vs Godot 4:
![godot3.4](https://user-images.githubusercontent.com/42871796/129186889-9b2690ba-950b-432b-b680-cc186636298b.png)
![godot4.0](https://user-images.githubusercontent.com/42871796/129186893-b7a051e8-ebf9-47df-8968-536e193e84ff.png)

While I'm at it, also when hovering over a link the mouse cursor doesn't change until you click somewhere in the hint box.

### Steps to reproduce

1. Open the a project with Godot 4 editor
2. Hover over an item, that has a hint with link (like project settings or resources such as `Sky`)
3. Done, it's too dark to read, at least for me

**Comment by akien-mga** [comment]
CC @godotengine/usability

**Comment by EricEzaM** [comment]
This bug has been in godot 4 since I started working on Godot almost 1.5 years old. It's basically a feature at this point 😂
