### ISSUE TITLE
GUI: Discussion

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#5157]
Game GUI is very different from that offered Godot. Your built-in GUI comfortable doing editor but it does not play. And that would make even a simple game to do their own controls that is tiring. It may be worth considering the creation of a small number of standard control for the casual games. Examples of successful implementation of such control can be viewed in the Unity3D or CocosCreator.

**Comment by Zylann** [comment]
It is true that most of the GUI nodes in Godot are oriented for tools / "classic interfaces". There are simple nodes, such as Patch9Frame or TextureButton, but I still ended up implementing Control scripts myself in my game because its menus are simple, animated and have different requirements than those provided by the basic GUI nodes (such as relying on color animation instead of texture change on mouse over, or having a disabled state).

However, I think the complex GUI nodes can still be of use, if you make a strategy game for example. I've witnessed game projects being struck by technical debt because they started with "simple game GUIs", their game grew up, GUI became a mess and they couldn't go back because they had no time to implement a new framework.

**Comment by reduz** [comment]
There are simple GUI controls you can use like Label, TextureFrame,
Patch9Frame, TextureButton, TextureProgress, etc. which cover the same kind
of things that you mention from Cocos or Unity. As the post above also
mentions, it's super easy to implement your own controls in Godot.

Now that asset library is almost done, anyone can contribute custom
controls.

**Comment by ret80** [comment]
In Unity I for example the very texture speak as her drawn (how it will stretch with increasing size), and then point out the texture button. Godot and I need to draw the required size button (which is almost no longer who do not).
Ai. What is not in the mood to explain anything today. You are not driving the obvious.

**Comment by vnen** [comment]
There's a communication issue going on here. It's hard to understand this machine-translated text. Maybe you have some pictures of Unity3D or CocosCreator to illustrate what you mean?

**Comment by trollworkout** [comment]
@ret80  provide animated GIF

**Comment by ret80** [comment]
I tried to create a button. Unfortunately I could not have found in the editor to take a basic button and hang it on a script that would implement my functional. Of course I can write a script that will be inherited from the base button but I can not put it in the editor. All have to do it through a script. And it is not convenient. How can I solve this?

**Comment by ret80** [comment]
Explain what GUI Godot differs from competitors is very difficult (especially with my English). Perhaps the surest way is to take a look at you, and competitors. Try to do what is the standard menu. I think it will not be a waste of time. It is always possible to take something useful from the others.

**Comment by ret80** [comment]
To make a button that, when pressed, changes its size (decreased by 10 percent). However, text is not reduced. How to make that text would also decreased?
PS
Creation of a custom GUI not such a simple task.

**Comment by ret80** [comment]
There is an opportunity to do so "user signal" were available for "connect" in the editor and not only in the script?

**Comment by Zylann** [comment]
In Godot, GUI primarily works by connecting signals to functions. Signals are similar to Qt or C# events. For example, select your Button node, click "Edit connections", and from there you can tell the button to call a method on the node of your choice (including the button itself), which will perform whatever you want to do.

This can be done by scripting too by calling `button.connect("pressed", node_receiving_the_signal, "the_method_you_want_executed")`.

These are basic concepts explained in the documentation.

But, initially your question was about "game oriented GUI", can you provide an example of what you are trying to achieve? (GIF? YouTube video?)

**Comment by ret80** [comment]
@Zylann,  thanks, Cap

**Comment by Calinou** [comment]
This doesn't look like an issue with the editor to me, but rather like a question on how to create simple game GUIs. I'm closing this, since questions should be directed to one of the [various community platforms](https://godotengine.org/community).
