### ISSUE TITLE
Mono glue generation error: Type mismatch for `GPUParticles2D.trail_length_secs` setter and getter

### ISSUE THREAD

**Issue by mdc634** [godotengine/godot#51570]
### Godot version

4.0 Dev

### System information

Fedora 34

### Issue description

![Screenshot_2021-08-12_07-09-15](https://user-images.githubusercontent.com/75803472/129205721-465e69f0-4258-4924-8e9a-3b11da43edaf.png)
![Screenshot_2021-08-12_08-33-04](https://user-images.githubusercontent.com/75803472/129205815-deb16727-3c19-4e30-8943-bf60cf60cd1d.png)
Included screenshots to help with debugging if possible.
Error on this line of code (everything is installed accordingly):
`<godot_binary> --generate-mono-glue modules/mono/glue`

### Steps to reproduce

`<godot_binary> --generate-mono-glue modules/mono/glue`

**Comment by akien-mga** [comment]
@aaronfranke There's a `double`/`real_t` type mismatch in that class. Other properties seem to still be `double`, I'll let you see if they should all be made `real_t` or `double`.

**Comment by mdc634** [comment]
Ok. Keep me posted...thought it would be worth sharing with others for no reason to start the documentation process.
