### ISSUE TITLE
Support shadows with DynamicFonts

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5159]
Currently, DynamicFonts can't cast any shadows, not even sharp ones. It would be nice if they could be set to cast a sharp shadow at least, with customizable X/Y offset and color.

Something like this (from another engine): ![shot0001](https://cloud.githubusercontent.com/assets/180032/15986801/83915e9e-3012-11e6-9e42-50f22093db80.jpg)

**Comment by reduz** [comment]
I think Label has the option for that

**Comment by volzhs** [comment]
![image](https://cloud.githubusercontent.com/assets/8281454/15986998/4e0fab08-3054-11e6-9616-40acb6fa4be5.png)

**Comment by Calinou** [comment]
> I think Label has the option for that

I can confirm, it also has outline options. Closing.
