### ISSUE TITLE
Complex Text Layouts: Label's Percent Visible property does not follow RTL text orientation

### ISSUE THREAD

**Issue by yzn-h** [godotengine/godot#51614]
### Godot version

4.0.dev

### System information

Linux Manjaro, i7-8550U, Vulkan

### Issue description

in arabic Percent Visible should delete from left to right:

### Steps to reproduce

![vokoscreenNG-2021-08-13_11-14-43](https://user-images.githubusercontent.com/63852512/129327769-d17b0a00-839b-4ede-b550-cbf397c4233a.gif)

**Comment by Chaosus** [comment]
Fixed by https://github.com/godotengine/godot/pull/52860
