### ISSUE TITLE
404: https://github.com/godotengine/godot/issues/CONTRIBUTING.md

### ISSUE THREAD

**Issue by graydwarf** [godotengine/godot#51623]
### Godot version

3.2.3.stable

### System information

Windows 10

### Issue description

FYI: https://github.com/godotengine/godot/issues/CONTRIBUTING.md is offline. About to file a bug and read the doc and found it missing.

### Steps to reproduce

Navigate to https://github.com/godotengine/godot/issues/CONTRIBUTING.md

**Comment by akien-mga** [comment]
Where did you find this link?

**Comment by graydwarf** [comment]
Oh, on the bug reporting page. Got there from a google search for godot bugs.
https://github.com/godotengine/godot/issues/new?assignees=&labels=&template=bug_report.yml

**Comment by graydwarf** [comment]
Here's the actual link on the page which is different from what you posted: https://github.com/godotengine/godot/issues/CONTRIBUTING.md#reporting-bugs
