### ISSUE TITLE
Godot 4.0: "Repeat" option missing for importing textures

### ISSUE THREAD

**Issue by Xyotic** [godotengine/godot#51621]
### Godot version

4.0-dev (20210811)

### System information

Windows 10, Vulkan, RTX2080

### Issue description

Using the test build [Godot_v4.0-dev.20210811_win64](https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20210811/)

When importing an image as a Texture2D the import option "Repeat" seems to be missing in 4.0
See screenshot.
Left -> Godot 3.3.2
Right -> Godot 4.0
![grafik](https://user-images.githubusercontent.com/8405059/129351532-72135169-ab53-47b8-8a52-2a33dbba1667.png)

### Steps to reproduce

Choose an image.
Open the import window.
Search for "Repeat" options.

**Comment by KoBeWi** [comment]
It's now a property of CanvasItem
![image](https://user-images.githubusercontent.com/2223172/129354632-8932a3a0-4db9-4de8-b44c-e6bba93074eb.png)

**Comment by Xyotic** [comment]
You need this option outside of Canvas items. What about shaders and uvs that go beyond the range of 0-1?

I don't think it is a good idea to put this option on a node...

This change would would break custom shaders

**Comment by alikandir** [comment]
> You need this option outside of Canvas items. What about shaders and uvs that go beyond the range of 0-1?
> 
> I don't think it is a good idea to put this option on a node...
> 
> This change would would break custom shaders
> 
> And what about 3D Games? They need this option too

Have you found a work around?

**Comment by KoBeWi** [comment]
For shaders there is a hint for that, e.g. `uniform sampler2D tex : filter_linear;`.
