### ISSUE TITLE
Infinitely loop showing 'nonexistent InputMap action'

### ISSUE THREAD

**Issue by sprhawk** [godotengine/godot#51631]
### Godot version

4.0dev (3a48474c49fa, d8a8d32f2ef617944c)

### System information

Debian 11 Linux, Vulkan, nVidia 3060 Laptop

### Issue description

Infinitely showing error message:
```
ERROR: Request for nonexistent InputMap action 'move_forward'.
   at: is_action_pressed (core/input/input.cpp:246)
```

### Steps to reproduce

call:
```
if Input.is_action_pressed("move_forward"):
```

in one gdscript file.

### Minimal reproduction project

https://github.com/sprhawk/godot_crash_demo/tree/errors/Children

**Comment by Calinou** [comment]
Your project does not have an input action called `move_forward`: https://godotengine.org/article/dev-snapshot-godot-3-4-beta-3

You need to create this action
 using **Project > Project Settings > Input Map**.

**Comment by sprhawk** [comment]
> Your project does not have an input action called `move_forward`, so this error message is expected: https://godotengine.org/article/dev-snapshot-godot-3-4-beta-3
> 
> You need to create this action using **Project > Project Settings > Input Map**.

Yes I know I don't have this action map. But my point is, when this action is missed, the startup of the engine editor will go into infinitely loop, and the Editor hang up.

I think this should be a bug that hang up the Editor

**Comment by madmiraal** [comment]
@sprhawk I cannot reproduce this issue. The `ERROR: Request for nonexistent InputMap action` errors are not generated in the editor when starting the editor, and the editor does not hang. Other errors are reported when trying to open the MRP, but they are unrelated to this issue.

The `ERROR: Request for nonexistent InputMap action` errors are only generated when running a project which repeatedly calls `Input.is_action_pressed("move_forward")` in the `func _physics_process(_delta)` method without an action called `move_forward` as in the MRP. Yes, it endlessly creates Debugger Errors, but this is to be expected as long as the flawed project is running and the `Input.is_action_pressed("move_forward")` keeps getting called. But again, the editor does not hang. The project can be stopped and the errors stop being generated.

**Comment by akien-mga** [comment]
I cannot reproduce the hang either, but I suspect that if it happens, it's not directly linked to this input error, but to the fact that any error spam would stress the communication with the terminal so much that things would end up in a broken state.
But here the error spam shouldn't happen in the editor at all (unless the script has `tool` but that's not the case here).
