### ISSUE TITLE
[4.0] Creating a Node from "Recent" list in "Create New Node" dialogue creates Node2D instead of Node

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#51632]
### Godot version

v4.0.dev.custom_build [3a48474c4]

### System information

Windows 10, 1080 Ti

### Issue description

Creating a Node from "Recent" list with "Create New Node" dialogue returns Node2D instead of Node: 

https://user-images.githubusercontent.com/2698825/129388525-8d8a6e90-0b89-40e1-b7e8-af38644d05b1.mp4

### Steps to reproduce

1. Open "Create New Node" dialogue (Ctrl + A)
2. Select "Node" in Recent list

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@Xartorx Can you reproduce this in 3.3.2 or [3.4 beta3](https://godotengine.org/article/dev-snapshot-godot-3-4-beta-3)?

**Comment by Xartorx** [comment]
@Calinou nope, only on ```master``` branch.

**Comment by hinlopen** [comment]
Working on a fix for this along with something else, this issue had a more interesting reason behind it than I imagined at first.
