### ISSUE TITLE
OS.open_midi_inputs() crashing

### ISSUE THREAD

**Issue by IsotoxalDev** [godotengine/godot#51659]
### Godot version

3.x development verison, commit: 632844e46412133edc163957626c9849004a2554

### System information

Fedora Silverblue, GLES3, audio driver pipewire

### Issue description

Godot crashes when OS.open_midi_inputs() is called.

This is not the segfault that is mentioned in issue #46183

Godot only crashes when a MIDI device is connected.

The output of stdout is
```
Running: /var/home/abhinav/Source/godot/bin/godot.x11.tools.64 --path /var/home/abhinav/Dev/MIDIBUG --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 9478 --position 448,240
Godot Engine v3.4.beta.custom_build.632844e46 - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL ES Batching: ON
 
ALSA lib rawmidi_hw.c:100:(snd_rawmidi_hw_params) SNDRV_RAWMIDI_IOCTL_PARAMS failed: Invalid argument
godot.x11.tools.64: rawmidi.c:256: snd_rawmidi_open_conf: Assertion `err >= 0' failed.
```

### Steps to reproduce

1. Call OS.open_midi_inputs() in the ready function of any node.
2. Run the project with a MIDI device connected

### Minimal reproduction project

[MIDIBUG.zip](https://github.com/godotengine/godot/files/6986109/MIDIBUG.zip)

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/46183 and https://github.com/godotengine/godot/issues/51169.

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by IsotoxalDev** [comment]
No. It works fine :) can i close the issue?
