### ISSUE TITLE
Showing Black screen after click 'play' button

### ISSUE THREAD

**Issue by sprhawk** [godotengine/godot#51665]
### Godot version

v4.0.dev.custom_build [b9b6102b9]

### System information

Debian 11 Linux, Vulkan, nVidia 3060 Laptop

### Issue description

I setup a very simple Scene: A Cube Mesh and a Camera.

When I Click play, it ( The Engine / Game ) shows Black Screen.

I tried in 3.3(custom build under godot  source code repo) with similar setup ( different nodes' names ), it will show correct rendered view.

### Steps to reproduce

Open  Project
Click Play

### Minimal reproduction project

https://github.com/sprhawk/godot-demo-blackscreen

**Comment by timothyqiu** [comment]
You have to setup the sun and environment manually in 4.0.

What you're seeing in the editor are using the preview sun and preview environment, which can be toggled on the toolbar.

See <https://godotengine.org/article/editor-improvements-godot-40>

**Comment by sprhawk** [comment]
@timothyqiu I see, thanks. Should I close this issue or leave it opened? I see you added this to milestone.

**Comment by timothyqiu** [comment]
Oh, sorry, I think the milestone is a mistake 😅
