### ISSUE TITLE
Ubsan errors in `visual_server.cpp`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#51663]
### Godot version

v3.4.beta.custom_build. 632844e46

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

Running editor shows this errors
```
servers/visual_server.cpp:336:33: runtime error: division by zero
servers/visual_server.cpp:498:17: runtime error: -nan is outside the range of representable values of type 'signed char'
servers/visual_server.cpp:499:17: runtime error: -nan is outside the range of representable values of type 'signed char'
servers/visual_server.cpp:556:17: runtime error: -nan is outside the range of representable values of type 'signed char'
```

Looks that this is regression from - https://github.com/godotengine/godot/pull/46800
CC @The-O-King

### Steps to reproduce

Above

**Comment by lawnjelly** [comment]
Also see here #51268.
