### ISSUE TITLE
'Code not correct' on activation email

### ISSUE THREAD

**Issue by Pikl** [godotengine/godot#5167]
So first of, I apologise for opening an issue on the repo that has nothing to do with the repo - it's just my issue prevents me from using the Godot Answers site.

**Operating system or device - Godot version:**
N/A

**Issue description** (what happened, and what was expected):
So I was just about to get involved on the Godot Answers site and answer a question, so naturally I signed up - using the "Link your GitHub account" option.
When clicking on the link in the activation email for the Godot Answers site, I'm greeted with "Code not correct - please click below to send a new link"
I've tried multiple activations and 2 different emails at different domains but it always ends up the same.

I've tried searching around on the Answers site and here on GitHub for this issue but couldn't find anything. 

**Steps to reproduce:**
Create new account on GodotEngine.org using "Link GitHub account".
Click on link in activation email.

**Link to minimal example project** (optional but very welcome):
N/A

Thanks for the hard work guys - I've only spent a few hours learning Godot but I like what I see so far (mostly)!

I'm more than happy to provide anything you guys may need.

**Comment by vnen** [comment]
Check #4170 and #3888. It might be related with the Q&A domain, so try without `www`.

**Comment by Pikl** [comment]
Hmm, I just went to try a new activation link without the www, but turns out I was already using the non-www links: http://godotengine.org/qa/confirm?c=zuvb1ua5&u=Jess was one of the ones I tried last night that didn't work.

But, a newly generated link just worked, so the problem seems to have gone away - whatever it was.

**Comment by maxwellc055** [comment]
In case anyone encounters this problem in the future and stumbles upon this post. I faced the same problem. After repeated trial and error, I found that simply giving godot a few minutes before clicking the email verification link works perfectly. Patience is key
