### ISSUE TITLE
CSG nodes are not exported correctly with scenes as GLTF (3.4b3)

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#51677]
### Godot version

3.4 beta3

### System information

Windows 10

### Issue description

CSG nodes are not exported correctly when exporting a scene as GLTF, these are read as empty axes by Blender and as simple Spatial nodes by Godot.
CSG nodes seem to be correctly exported on master (4-dev), except for materials.

The original scene tree
![original tree](https://user-images.githubusercontent.com/10215987/129457247-9eee5178-a167-4a56-873b-63c93dc21686.png)

Scene view
![original scene](https://user-images.githubusercontent.com/10215987/129457223-eb454f2f-c7da-4e67-b2d3-a8b29a8c5c9d.png)

Exported tree (inherited)
![Exported tree](https://user-images.githubusercontent.com/10215987/129457259-49fdd423-372d-479c-803b-9ad347c41a51.png)

Scene view of the exported scene in Blender (windows vewer can't open it).
![Opened with blender](https://user-images.githubusercontent.com/10215987/129457324-d1d1f834-3907-4665-aa29-afdf43af33ed.png)

### Steps to reproduce

Create CSG nodes in any configuration and amount, then export the scene with the GLTF exporter.

### Minimal reproduction project

Simple scene, includes an exported model.
[csgexportbug.zip](https://github.com/godotengine/godot/files/6987038/csgexportbug.zip)

**Comment by fire** [comment]
Verified still broken on https://github.com/godotengine/godot/commit/f28199f403df45b1e1276f39afe2d415170adcf5

![image](https://user-images.githubusercontent.com/32321/137580066-9e50f409-966a-4fb3-bb42-a5d33667aafd.png)

**Comment by DrRevert** [comment]
Hey, found a culprit in modules/gltf/gltf_document.cpp the define macro MODULE_CSG_ENABLED is not defined (grid maps seems to also be broken the same way).
As a workaround: Adding define MODULE_CSG_ENABLED to gltf_document.h fixed the issue, but that's not a proper way to do it.

**Comment by akien-mga** [comment]
Fixed by #54911.

**Comment by eon-s** [comment]
Looks like it exports the mesh correctly now, CSG object's materials are missing (material slots/surfaces are correct, though) but need to test it on 4 again to see if it does the same there .

**Comment by Corruptinator** [comment]
Just a heads up, I've just downloaded the latest Stable: v3.4.stable.official [206ba70f4], but unfortunately the export for _gltf/glb_ for CSG objects just comes up as Plain Axes:

![image](https://user-images.githubusercontent.com/5027750/142135130-8526edbb-915e-408e-8b30-d078316eaf6c.png)

**Comment by akien-mga** [comment]
@Corruptinator This was fixed 5 days ago, which is *later* than the release of Godot 3.4-stable, so that's normal.

See milestones and comments on https://github.com/godotengine/godot/pull/54911, the fix is in 3.5 and 3.4.1.

**Comment by Corruptinator** [comment]
Got it, thanks @akien-mga!
