### ISSUE TITLE
GPU particles broken and spitting out errors continuously

### ISSUE THREAD

**Issue by RicardRC** [godotengine/godot#51686]
### Godot version

4.0.dev (57e16812a1a4b89058de29e81247351afdd09087)

### System information

Windows 10, Nvidia 1070

### Issue description

Gpu particles emit a constant stream of errors when active and visible by the camera:
```
  This compute pipeline requires (32) bytes of push constant data, supplied: (40)
  The shader in this pipeline requires a push constant to be set before drawing, but it's not present.
```

### Steps to reproduce

Create a GPU particles node.

### Minimal reproduction project

[GPUParticlesBug.zip](https://github.com/godotengine/godot/files/6987685/GPUParticlesBug.zip)

**Comment by darrylryan** [comment]
Can confirm, same issue here...

**Comment by Chaosus** [comment]
I've bisected it to 84f720966c74d5b37f70e21867e9e3e6a1e44c36 (https://github.com/godotengine/godot/pull/51294)

**Comment by akien-mga** [comment]
That PR might need a re-review as it uses `double`s in rendering code which can be problematic for performance if it's stuff that needs to be passed to the GPU.

**Comment by aaronfranke** [comment]
Code that uses time should generally be double, but I'm not sure how this code interacts with the GPU. It's also possible that using float in the rendering/* files but double in the nodes will give us most of the benefits anyway.
