### ISSUE TITLE
Broken display using previously imported glb from godot 3.3.2 in godot 3.4 beta

### ISSUE THREAD

**Issue by cesarizu** [godotengine/godot#51683]
### Godot version

3.4.beta (f285b88d)

### System information

Linux (openSUSE tumbleweed) nvidia (proprietary module) GLES3

### Issue description

When using a glb mesh in 3.3 and then trying to open the same project in 3.4, the mesh is broken. Doing a bisect the commit that introduced this problem is f0de7ec2b6. Deleting the imported file from the `.import` folder and letting 3.4 reimport the mesh fixes the issue.

3.3:
![Screenshot from 2021-08-14 22-15-02](https://user-images.githubusercontent.com/658725/129465922-02ca5bdb-362c-487b-8eb1-bf7c56537802.png)

3.4:
![Screenshot from 2021-08-14 22-15-31](https://user-images.githubusercontent.com/658725/129465929-19fad311-eaea-4e24-bfff-638f22e197e9.png)

### Steps to reproduce

Import a glb file in a 3.3 project. Open the project with 3.4. The mesh will be broken.

### Minimal reproduction project

[regression-test.zip](https://github.com/godotengine/godot/files/6987454/regression-test.zip)

**Comment by akien-mga** [comment]
CC @The-O-King

**Comment by akien-mga** [comment]
It seems fixed in 3.4 RC 2.
