### ISSUE TITLE
Editor is broken after setting HiDPI mode

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5168]
Windows 10, Godot 2.1 alpha as of 11/06/2016.

I tried to set the editor in HiDPI, restarted it, then the project selector took a while to open, with these errors looping in the console:
```
ERROR: _png_error_function: PNG file corrupted by ASCII conversion
   At: drivers\png\image_loader_png.cpp:60
libpng error: PNG file corrupted by ASCII conversion
ERROR: ImageLoaderPNG::_load_image: PNG Corrupted
   At: drivers\png\image_loader_png.cpp:94
ERROR: _load_mem_png: Condition ' err ' is true. returned: Image()
   At: drivers\png\image_loader_png.cpp:297
ERROR: RasterizerGLES2::texture_set_data: Condition ' p_image.empty() ' is true.
   At: drivers\gles2\rasterizer_gles2.cpp:962
```
Then if I try to open a project, the same errors continue to appear and the editor eventually crashes with this last error:
```
VBoxContainer: 272,201
bind toptions
..http://godotengine.org/asset-library/api
1 url: http://godotengine.org/asset-library/api/configure
no SSL
2 url: godotengine.org/asset-library/api/configure
request string: /asset-library/api/configure
3 url: godotengine.org
4 url: godotengine.org
Requesting:
        URL: godotengine.org
        String: /asset-library/api/configure
        Port: 80
        SSL: 0
        Validate SSL: 1
ERROR: RasterizerGLES2::texture_get_data: Condition ' texture->data_size==0 ' is true. returned: Image()
   At: drivers\gles2\rasterizer_gles2.cpp:1122
```

Because of this I can't set the option back to LoDPI.
Although my screen is not big enough for this to be enabled, there might be a bug.

**Comment by reduz** [comment]
for now edit ~/.godot/editor_settings.tres and remove the line with the
hidpi
will try to see how to reproduce, though so far i can't seem to

**Comment by volzhs** [comment]
it happens to me when start editor on Windows 10 with ``global/hidpi_mode = 2`` setting.

**Comment by reduz** [comment]
I can't reproduce this, but it seems some images (not sure which ones) in theme and editor icons use indexing mode (pallete), which is causing some errors... those should be converted to rgba

**Comment by reduz** [comment]
Not sure if this was really fixed, as I could never reproduce the original issue, even on windows. I have the feeling that what I fixed was the culprit though. Please reopen if you can reproduce.

**Comment by archetypitect** [comment]
I get the same error and crash, even with the 2.1 RC.  Only fixed by changing editor_settings.tres, but that means it just defaults to lowdpi.  (My screen is 1440p)
