### ISSUE TITLE
Portals: Roaming object culled unexpectedly

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51688]
### Godot version

3.x (f285b88dae)

### System information

macOS 11.5.1

### Issue description

I have a MeshInstance with portal mode set to Roaming. The MeshInstance is sometimes culled unexpectedly.

![capture](https://user-images.githubusercontent.com/372476/129472173-2ed3f19a-62b2-4507-83c4-3f8c2c03d59d.gif)

CC @lawnjelly 

### Steps to reproduce

Run the MRP and watch.

### Minimal reproduction project

[Roaming.zip](https://github.com/godotengine/godot/files/6987768/Roaming.zip)

**Comment by lawnjelly** [comment]
Ah, this is due to looking at the room through more than one portal. My logic is slightly wrong there, I'll fix it. I had to work through same problem on my old module so I'm familiar with it! :+1: :grin:

**Comment by lawnjelly** [comment]
Incidentally your room arrangement reminds me of something I have seen a few people do, which is to create two opposing portals in _both_ adjacent rooms. This is good for bug testing in your case (as it does seem to work correctly), but I want to see if it is possible to flag a warning when the user does this.

As portals are two way by default only one is needed between two rooms. If there are two it will visit the same room twice and do extra processing. The result should be the same, but it's doing twice the culling calculations needlessly. So I'm figuring a warning would be good, and possibly auto-disabling one of the portals to prevent this double processing if it is possible.

**Comment by akien-mga** [comment]
Fixed by #51689.
