### ISSUE TITLE
Lookup symbol does not work on built-in functions

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#51687]
### Godot version

57e16812a1a4b89058de29e81247351afdd09087

### System information

Should not matter

### Issue description

Lookup symbol does not work on built-in functions like `clamp`, `print` etc.

### Steps to reproduce

Create a script, add a built-in function call, and left-click on it with CTRL.

### Minimal reproduction project

Too easy to reproduce.

**Comment by LightningAA** [comment]
Is this why https://github.com/godotengine/godot/issues/48113 was not reproducible on master (https://github.com/godotengine/godot/pull/48119#issuecomment-825733912)? Or is this more recent?
