### ISSUE TITLE
Same icon for Minimap & Node arranger in GraphEdit/VisualScript/VisualShader editor

### ISSUE THREAD

**Issue by theoway** [godotengine/godot#51680]
### Godot version

4.0 dev latest

### System information

Any system

### Issue description

![Screenshot (302)](https://user-images.githubusercontent.com/41969735/129459258-7bb779a3-c725-49b1-af32-23faeafa8c15.png)
![Screenshot (301)](https://user-images.githubusercontent.com/41969735/129459259-e9c2523c-75f4-4158-a23c-1f3c258161bc.png)

We need different icon for node auto-arranger button. Currently, it is using the `.svg` & `.png` file of Minimap icon

### Steps to reproduce

- Open VisualScript/VisualShader editor

**OR**

- Add a `GraphEdit` node.

**Comment by theoway** [comment]
If anyone is willing to contribute to the icon, it would be appreciated. You can send me the respective icon files and I'll change it, or I can guide you through the process of updating it in the engine.

**Comment by LucyLavend** [comment]
Would something like this work? I still have to learn how to compile the engine so I haven't been able to test how it looks in engine.

![NodeArranger](https://user-images.githubusercontent.com/47501982/129461130-fed096b0-c491-477f-93a2-af67af5e9e67.png)

**Comment by Calinou** [comment]
> Would something like this work? I still have to learn how to compile the engine so I haven't been able to test how it looks in engine.
> 
> ![NodeArranger](https://user-images.githubusercontent.com/47501982/129461130-fed096b0-c491-477f-93a2-af67af5e9e67.png)

This icon looks good, just make sure it snaps well to a 16×16 pixel grid.

Compiling instructions are here: https://docs.godotengine.org/en/latest/development/compiling/index.html

**Comment by theoway** [comment]
> Would something like this work? I still have to learn how to compile the engine so I haven't been able to test how it looks in engine.
> 
> ![NodeArranger](https://user-images.githubusercontent.com/47501982/129461130-fed096b0-c491-477f-93a2-af67af5e9e67.png)

@LucyLavend This looks awesome. Can I use this file for setting up the icon or there is something else to be added to the file? (*_After making it 16×16 pixel_)

**Comment by LucyLavend** [comment]
Here's a zip with the .svg file and the 16x16 .png. Let me know if I need to tweak anything.

[NodeArrangerIcon.zip](https://github.com/godotengine/godot/files/6987690/NodeArrangerIcon.zip)

**Comment by theoway** [comment]
@LucyLavend Thank you so much! I'll try it in the engine, and let you know if anything else needs to be done.
