### ISSUE TITLE
Calling .get_mouse_pos() on a render target viewport works, but spams the error log on every call

### ISSUE THREAD

**Issue by olsonjeffery** [godotengine/godot#5169]
**Operating system or device - Godot version:**
OSX El Capitan, both in the 2.0.3 stable 64bit client and the 2.1.alpha nightly 64bit from 10 jun from fixnum.org

**Issue description** (what happened, and what was expected):
Calling `get_viewport().get_mouse_pos()` on a node that is within a world inside a `Viewport` works correctly, but logs an error every time.

When ran from the 2.1-alpha client build from fixnum.org (also on local source builds on the tip of master), the error is:

![screen shot 2016-06-11 at 8 30 15 pm](https://cloud.githubusercontent.com/assets/10408/15988368/5ea76fc8-3013-11e6-93bf-52542cca207f.png)

When run from the 2.0.3 stable 64bit OSX client, the error is logged, but it is empty (because debug symbols are stripped?)

**Steps to reproduce:**

1. Set up a project with a scene that is within a child `Viewport` that is configured as a Render Target.
2. Have a node within the scene that is collecting input via `get_viewport().get_mouse_pos()` from within `_process()` or whatever
3. Watch the errors pile up

**Coda**

I'm doing the above thing (getting mouse_pos from a viewport that is a rendertarget) because my "game world" has custom lighting and I have GUI elements overlaying the game world. And you _don't_ want those lit the same as the game world, for obvious reasons.

So I'm using a render target. I _also_ have mouse-picking of map tiles in the game world. Before I switched to using a render target, this was straightforward and I could use proper event handling on my player node via `_input()`.

After switching to using a render target, I discovered that `_input()` events aren't being triggered on that node anymore.

So in experimenting I tried seeing if a child viewport would properly track mouse coords (and it does!), but it spews errors because of what looks like an assert in the C++ src.

Any insight on this would be appreciated, especially if it involves suppressing the error or a suitable workaround.

Thanks!

**Comment by olsonjeffery** [comment]
a related question: would you accept a PR stripping out this check? I haven't evaluated the src to fully understand the context for the assert (ie are there valid circumstances for this non-fatal error to be logged like this?)

**Comment by trollworkout** [comment]
This happens to me too. Latest build El Capitan. But to be honest Viewport is somewhat broken at the moment in the editor. If you try to add nodes in the editor they never scale up or down as you zoom in for example. Devs accept PR requests if you can fix would be helpful. You should discuss it with them either a dev will reply here or you can go on godotengine-devel channel on freenode irc.
