### ISSUE TITLE
Startup errors: `Condition "version_owner.get_rid_count() > 0" is true.`

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#51696]
### Godot version

e537a1f10ec32e9e2daecb171128c3f63f0bcc97

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/3036176/129485495-d3668fb0-24ee-4b9d-b74a-e6f741c52f72.png)

### Steps to reproduce

Simply run a project manager

### Minimal reproduction project

No need

**Comment by qarmin** [comment]
![Screenshot from 2021-08-15 20-10-00](https://user-images.githubusercontent.com/41945903/129488242-76320942-2399-4b8d-9f34-0c8f6fb29aa1.png)

**Comment by BastiaanOlij** [comment]
The set_variant_enabled calls need to be above the version_create() call. I thought I already moved those but must have been either one of the other shaders, or in one of my many outstanding PRs :)

**Comment by BastiaanOlij** [comment]
Ah I did miss this one, will fix it
