### ISSUE TITLE
Can't compile using float=64

### ISSUE THREAD

**Issue by RicardRC** [godotengine/godot#51692]
### Godot version

4.0.dev (57e16812a1a4b89058de29e81247351afdd09087)

### System information

Windows 10, Nvidia 1070

### Issue description

Can't compile using option float=64

![imagen](https://user-images.githubusercontent.com/35220750/129477981-4d1013cb-52ff-463e-bc12-13355392e7e0.png)

### Steps to reproduce

Compile using float=64

**Comment by akien-mga** [comment]
That's expected for now as the work isn't finished.  But this issue can serve as a reminder/status report.

**Comment by RicardRC** [comment]
Oh! I didn't know it was not supported, sorry!
I think I've solved the compilation problem though, just making vector2, 2i, 3 and 3i more "correct", as they are missing definitions that the templates require. I'll make the PR once I test it a little.
