### ISSUE TITLE
"Could not determine inheritance" error when inheriting from an inner class

### ISSUE THREAD

**Issue by jrimclean** [godotengine/godot#5170]
**Operating system or device - Godot version:**

X11 (master), X11 (2.0.3-stable), and X11 (2.0-stable) have been tested.

**Issue description** (what happened, and what was expected):

When inheriting from an inner class (according to the documentation at http://docs.godotengine.org/en/latest/reference/gdscript.html) the following error occurs:

`SCRIPT ERROR: GDScript::reload: Compile Error: Could not determine inheritance`

followed by:

`ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED`

**Minimal example:**

**test1.gd**
```
class Test1:
	func hello():
		print("hello")
```

**test2.gd**
```
extends "test1.gd".Test1
```

**main.gd**
```
extends MainLoop

func _init():
        print("begin")
        var test2 = load("test2.gd")
        print("end")
```

Running the script using the following command: `godot -s main.gd` causes the error. I have also tested this in the editor with the same results.

**Comment by reduz** [comment]
you may need to specify full path in extends, alternatively just make an example project and I will give it a check

**Comment by jrimclean** [comment]
Here's a minimal example project: https://github.com/jrimclean/godot-innerclass-test

It demonstrates loading a class with regular inheritance and then loading a class that extends an inner class.

**Comment by jrimclean** [comment]
I tested eska's fix and it solves the problem.

**Comment by reduz** [comment]
this was fixed recently, closing
