### ISSUE TITLE
Built-in variables are not highlighted enough in the shader editor

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#51727]
### Godot version

v3.4.beta.custom_build [93ff6e790]

### System information

Linux Arch, Radeon RX 590

### Issue description

Syntax highlight in shader editor does not highlight UV
![Screenshot_2021-08-16_11-29-51](https://user-images.githubusercontent.com/7917475/129542444-59aed58d-c052-4d62-ab2e-0e2091f66e87.png)

### Steps to reproduce

Paste this shader in the shader editor, and note that `UV` is not highlighted.

```
shader_type spatial;

uniform sampler2D mask_texture;
uniform sampler2D emission_texture;

void fragment(){
	vec4 color = texture(emission_texture, UV);
	
}
```

**Comment by Chaosus** [comment]
There were changes: https://github.com/godotengine/godot/pull/33548 by @Calinou. I think it's actually highlighted but maybe not much to see a difference.

**Comment by Calinou** [comment]
There is a highlight, it just happens to be more subtle now.

We could look into adding a new color dedicated (likely the same as GDScript annotations)?
