### ISSUE TITLE
Rightclick not working on Android is not BUTTON_RIGHT

### ISSUE THREAD

**Issue by ModProg** [godotengine/godot#51737]
### Godot version

3.3.2.stable

### System information

Android

### Issue description

While left and middle click correctly map to `BUTTON_LEFT` and `BUTTON_MIDDLE` rightclick does not, it is 0 instead.

### Steps to reproduce

Attach this to a control and run on Android (I have a child name Label2 to display the value):
```gd
func _input(event: InputEvent) -> void:
	
	if event is InputEventMouseButton:
		$Label2.text = "PRESSED: " if event.pressed else "RELEASED: "
		match event.button_index:
			BUTTON_LEFT:
				$Label2.text += "left";
			BUTTON_RIGHT:
				$Label2.text += "right";
			BUTTON_MIDDLE:
				$Label2.text += "middle";
```

**Comment by Calinou** [comment]
cc @thebestnom

**Comment by akien-mga** [comment]
Note that the Android input handling changed significantly in `3.x`, so it might be worth testing if this is reproducible in 3.4-beta3 or later: https://downloads.tuxfamily.org/godotengine/3.4/beta3/

I haven't tested and I'm not familiar with that code, but from a quick glance at the code I noticed something fishy:
https://github.com/godotengine/godot/blob/f66ff33b25e1a1298d119b6a198f2562789e5f0c/platform/android/os_android.cpp#L683-L685

`AMOTION_EVENT_BUTTON_SECONDARY` is handled twice.

**Comment by ModProg** [comment]
@akien-mga I tried your recomendation and it fixed the issue:
#51744

**Comment by thebestnom** [comment]
What rom are you, the fix is mostly wrong 😅
Most default android roms doesn't support right click correctly,I tested on lineageos as a baseline because it doesn't meddle with the mouse click

**Comment by akien-mga** [comment]
I don't know if the fix is sufficient for all ROMs but it does seem to fix a typo, no? What's the use case for matching `AMOTION_EVENT_BUTTON_SECONDARY` to `BUTTON_MASK_XBUTTON2`?

**Comment by ModProg** [comment]
> What rom are you? the fix is mostly wrong sweat_smile

Samsung Android 11, but this should be the default behaviour, did you check with a native android application?

[`BUTTON_SECONDARY`](https://developer.android.com/reference/android/view/MotionEvent#BUTTON_SECONDARY) was added in android 4.0

**Comment by thebestnom** [comment]
Actually not, samsung did this completely wrong when I tested on my dad galaxy s10, I have a huge complain on it in the PR 😅

**Comment by thebestnom** [comment]
https://github.com/godotengine/godot/pull/37158#issuecomment-620063431

**Comment by thebestnom** [comment]
Oh... My bad, I didn't read the bug correctly, I think you are correct, but my comment in the PR will make this really hard to test on most devices 😅
