### ISSUE TITLE
[4.0] "Custom Effects" dropdown menu of RichTextLabel doesn't work

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#51735]
### Godot version

v4.0.dev.custom_build [203cc6dd3]

### System information

Windows 10, 1080 Ti

### Issue description

Clicking on "Custom Effects" array item doesn't show (or show very briefly) dropdown menu for RichTextEffect.
Possibly this bug affects other dropdown menus for arrays, but didn't tested it yet.

https://user-images.githubusercontent.com/2698825/129582108-6b2857ea-469e-4e9f-afad-96d42e0de3f4.mp4

### Steps to reproduce

1. Add RichTextLabel
2. Change "Custom Effects" size to 1 (or more)
3. Click on ```[empty]``` dropdown menu

### Minimal reproduction project

N/A

**Comment by requizm** [comment]
I couldn't find the function that works when I hit dropdown. I messed around with:
-ArrayPropertyEdit
-EditorPropertyArrayObject
-EditorPropertyArray

**Comment by williamd67** [comment]
I think that this issue relates to #49817 which refers to #45879. The method `get_effects` of `RichTextLabel` returns a copy of the custom effects array (see below). This means that the editor determines that this value changes continuously, which can also be seen be the 'undo' symbol that is shown immediately and when clicked does not seem to do anything (see screenshot).

```
Vector<Variant> RichTextLabel::get_effects() {
	Vector<Variant> r;
	... 
	return r;
}
```
![Screenshot from 2021-08-22 16-21-45](https://user-images.githubusercontent.com/10560119/130358611-7f3b0c57-1b8b-40e7-8abc-85d58efdcb20.png)

I will investigate further if the member can be returned in stead of a copy and what the impact of that would be.
