### ISSUE TITLE
Sprite3D broken when SplitStream enabled

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#51756]
### Godot version

4032d26dd5

### System information

MacOS Big Sur 11.4 (AMD Radeon Pro 5500M 4GB)

### Issue description

Making a sprite 3D with split stream enabled results in broken vertex data

<img width="1224" alt="Screenshot 2021-08-16 at 22 13 15" src="https://user-images.githubusercontent.com/748770/129630870-12365530-6e0f-4421-8640-fda5e18667d2.png">

With the option disabled

<img width="487" alt="Screenshot 2021-08-16 at 22 19 58" src="https://user-images.githubusercontent.com/748770/129630907-218d5d0c-50a0-4fa6-8957-d3c3ba9b52bf.png">

### Steps to reproduce

1. Make sprite 3d with split stream enabled
2. you should get the same result as me

**Comment by RevoluPowered** [comment]
CC: @the-o-king

**Comment by clayjohn** [comment]
Looks like:
https://github.com/godotengine/godot/blob/4032d26dd50dd10147d140ef5e201ee68c580e2f/servers/visual_server.cpp#L1268
and 
https://github.com/godotengine/godot/blob/4032d26dd50dd10147d140ef5e201ee68c580e2f/servers/visual_server.cpp#L856

will need to copy the logic from:
https://github.com/godotengine/godot/blob/4032d26dd50dd10147d140ef5e201ee68c580e2f/servers/visual_server.cpp#L989

**Comment by The-O-King** [comment]
This may be fixed once I fix https://github.com/godotengine/godot/issues/51652 I think these might be somewhat related as I found that similarly to be the issue there

**Comment by pouleyKetchoupp** [comment]
@The-O-King Is this issue fixed by #51769?

**Comment by clayjohn** [comment]
Yep!
