### ISSUE TITLE
NanoSVG undefined behaviour on init

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#51763]
### Godot version

master

### System information

MacOS Big Sur 11.4 (AMD Radeon Pro 5500M 4GB)

### Issue description
```
thirdparty/nanosvg/nanosvg.h:2190:49: runtime error: division by zero
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior thirdparty/nanosvg/nanosvg.h:2190:49 in 
```
### Steps to reproduce

build with ubsan=yes
run engine
error will show

**Comment by fire** [comment]
See also https://github.com/godotengine/godot/pull/49645
