### ISSUE TITLE
Imported animations not working correctly

### ISSUE THREAD

**Issue by MmAaXx500** [godotengine/godot#51785]
### Godot version

4.0.dev (84b11fb) Calinou's build and custom build

### System information

Windows 10 21H1

### Issue description

I have tried importing glTF and escn which are exported from Blender 2.93, but the animations ended up as a total mess when imported. Key frames are scattered all over the timeline, weird deformations, nothing happens, or the mesh has been hidden by playing the animation. Sometimes the animations are correct. All of these by reimporting the exactly same file over and over again.

#49974 is probably related, but there escn is working properly and is version 3.3.2.

### Steps to reproduce

1. Select one of the `cube*` models.
2. RMB -> "New Inherited Scene"
3. Select the animation player
4. Look at the timeline (sometimes it's weird)
5. Play the animation

### Minimal reproduction project

There are two `.blend`, one with 15 fps animation, one with 30 fps.
All exports made with Blender's default settings except the "selected only" checkbox.

[anims.zip](https://github.com/godotengine/godot/files/6998390/anims.zip)

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
Did you try disabling optimization of animation?

**Comment by MmAaXx500** [comment]
I just tried. Same results.

**Comment by MmAaXx500** [comment]
#51991 fixed this too. Should we close this?
