### ISSUE TITLE
Inconsistent button layout on dialogs

### ISSUE THREAD

**Issue by MmAaXx500** [godotengine/godot#51799]
### Godot version

4.0.dev (84b11fb)

### System information

Windows 10 and Linux (Tumbleweed, KDE)

### Issue description

Save - Don't save, Remove - Cancel, Open - Cancel buttons are swapped between platforms. Today I tried to reproduce an issue on Linux and at every dialog I successfully achieved the exact opposite of what I wanted.

I don't know it's more a bug report or a feature request, but I suggest keeping a consistent button layout on the dialogs, between platforms.

#### Save Chages dialog
![Save chages linux](https://user-images.githubusercontent.com/36025825/129732865-bc6a2d22-d050-4ab7-b975-ffe0bd337c07.png)
![Save chages windows](https://user-images.githubusercontent.com/36025825/129732945-30f1c77d-bdde-4af6-8690-3a1526fc4d6e.png)

#### Delete dialog
![delete linux](https://user-images.githubusercontent.com/36025825/129733019-6700492a-ff19-4a97-938b-8bd30f8a312e.png)
![delete windows](https://user-images.githubusercontent.com/36025825/129733027-01062834-434b-47c5-9a9a-36fddabcbe3d.png)

### Steps to reproduce

Delete something, open something, or delete something.

**Comment by bruvzg** [comment]
It's intended behavior, controlled by `DisplayServer::get_swap_cancel_ok()`, to mimic default button order in the system dialogs of different platforms.

**Comment by MmAaXx500** [comment]
Ahh! Sorry, I didn't find it.
