### ISSUE TITLE
File.open never opens files if they don't exist on Windows

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#51797]
### Godot version

3.3.3-rc2, 3.4.beta3

### System information

Windows 10

### Issue description

I was attempting to write a simple on-drive cache to prevent a bunch of images from being downloaded every time someone logs into my Discord clone game, and I couldn't get the file to ever open for writing. I have this very simple script:

https://gist.github.com/WolfgangSenff/461f00f9a325a8b709d3d2cd5a54d88f

This does not work - it will not ever save the file out. It always responds with this:
![image](https://user-images.githubusercontent.com/148612/129749851-a2e176a4-7793-4ae9-90a3-7f68f034e78e.png)

Tested on both the 3.3.3 current rc and 3.4 current beta, no luck. It doesn't appear to be the same issue as was fixed by M. Hilbrunner earlier, as I believe that fix was in the 3.3.3.rc2 release, or I could be mistaken. If this is believed to be fixed by that commit, I for one wouldn't understand how or why it would (nothing else is trying to access the file), or I can wait for the next version to pick it up and test again.

### Steps to reproduce

Open a basic project, add the script listed to a root Node2D and run it.

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/7001027/TestProject.zip)

**Comment by timothyqiu** [comment]
I think you might need to check the return value of `File.open()`, it may be returning `ERR_FILE_NOT_FOUND` as a result of missing directory `user://cache_temp`. You can try creating it first with `Directory`'s `make_dir()` method.

**Comment by WolfgangSenff** [comment]
Hm. File.open with WRITE passed in said it would create it, but if the directory isn't there, that's an interesting point. I will give that a shot, brb.

**Comment by WolfgangSenff** [comment]
@timothyqiu - you were right! Thanks! So obvious, but I did not see it at all.
