### ISSUE TITLE
AtlasTexture preview out of bounds

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#51802]
### Godot version

3.4.beta2,3.4.beta3

### System information

Windows 10, GLES2/GLES3, Nvidia GeForce GTX 750 Ti

### Issue description

The AtlasTexture will go out of its preview space in the Inspector Panel

![image](https://user-images.githubusercontent.com/1212509/129777697-c2072f76-60f4-4a21-88dd-1fb1a022e323.png)

![image](https://user-images.githubusercontent.com/1212509/129778000-5f41d5a1-df7c-490e-856e-cb1dc2800934.png)

### Steps to reproduce

- Create a new AtlasTexture
- Load some Texture on the Atlas property
- Give it width and height in Region
- Give it some margin x or y so it goes out of bounds

**Comment by pycbouh** [comment]
Do note that this is not exclusive to the atlas texture. For example, given that you start with a stylebox on the first screenshot, even `StyleBoxFlat` can be made to exceed the bounds if you set its margins to expand. I'm not sure what the proper solution would be here.

Though as far as the atlas texture goes, we should probably clip the content at least.

**Comment by kleonc** [comment]
Fixed by #93828 / #93857 (the preview is drawn using `TextureRect`).

---

> Do note that this is not exclusive to the atlas texture. For example, given that you start with a stylebox on the first screenshot, even `StyleBoxFlat` can be made to exceed the bounds if you set its margins to expand. I'm not sure what the proper solution would be here.

@YuriSizov Not sure what exact issue you mean here / how it's meant to be reproduced. If you can still reproduce it then please open a new separate issue for that.

**Comment by YuriSizov** [comment]
> Not sure what exact issue you mean here / how it's meant to be reproduced. If you can still reproduce it then please open a new separate issue for that.

Well, that's a 3-year old comment, and the issue originally reported for Godot 3. There used to be a problem that all styleboxes would be allowed to escape the preview area. But I guess some change in Godot 4 addressed that. Feel free to wait for more reports!
