### ISSUE TITLE
Cannot use SCons on Windows

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5181]
I updated my Git repo an hour ago, and now SCons cannot build Godot.
I use this command in the x64 native tools for Visual Studio 2015, as usual:
```
D:\...\godot>scons -platform=windows
Warning:  the -p option is not yet implemented
usage: scons [OPTION] [TARGET] ...

SCons Error: option -l: invalid floating-point value: 'atform=windows'
```
Did I missed something or the build system changed?

**Comment by djrm** [comment]
is platform not -platform

**Comment by Zylann** [comment]
Yes. Silly me. Thank you!
