### ISSUE TITLE
Quick Open Script top result is incorrect

### ISSUE THREAD

**Issue by hinlopen** [godotengine/godot#51811]
### Godot version

819aa47feeefe76bf1cb2e179765bf35ee5d3dda

### System information

Windows 10 (doesn't matter)

### Issue description

See image below. Compared to the other results, Control.gd should be selected but it isn't.
![image](https://user-images.githubusercontent.com/25907608/129802677-398e3f27-e639-405a-aa11-b94ad9d168d2.png)

### Steps to reproduce

- Create files seen in image.
- Type `c`

**Comment by akien-mga** [comment]
The neverending story... I feel like this code is tweaked every other month and we still haven't reached a point where it's reliable.

**Comment by KoBeWi** [comment]
Well, good news is that this doesn't affect scenes.

Bad news is that we have search matching implemented numerous times all over the codebase (recently added command palette has its own implementation too btw) and it might be high-time to unify it. The Quick Open for scenes should be used as reference, because it has the best results right now.

**Comment by hinlopen** [comment]
> Bad news is that we have search matching implemented numerous times all over the codebase (recently added command palette has its own implementation too btw) and it might be high-time to unify it.

I have looked into doing this but the search results can be very different in different parts, and it's hard to rank all results universally, while taking advantage of the particularities of each kind of search result. In most cases I think it will be difficult to do search without providing a custom filter and sorting function.

**Comment by akien-mga** [comment]
At least for Quick Open Script and Scene it should not be difficult to unify. The only difference is the supported extensions. (I thought they even used the same control?)

**Comment by hinlopen** [comment]
Yes, all three Quick Open dialogs are already unified in the same control.
