### ISSUE TITLE
Can't Assign Texture to TextureRect from custom function.

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#51825]
### Godot version

3.3.3rc2

### System information

Windows 10

### Issue description

I am using C# for this example.

I am unable to assign a texture to a TextureRect from a custom function, but can from a signal function. 

### Steps to reproduce

I have a demo reproduction project in which there is a button.  Upon pushing the button, an instance of a TextureButton with a TextureRect scene is created.  In the creation I assign the code is called: 
`txrBorder.Texture = (Texture)GD.Load("res://Sprites/tokenBorder.png");`
The border is not assigned to the instance.  However, in the "button_down" signal of the TextureButton, I put the same code: `txrBorder.Texture = (Texture)GD.Load("res://Sprites/tokenBorder.png");` and this time if I click on the newly formed instance the image is successfully added.

### Minimal reproduction project

[Txr Rect.zip](https://github.com/godotengine/godot/files/7004275/Txr.Rect.zip)

**Comment by kleonc** [comment]
Everything works fine, no bug in here.

You're calling `s.SetPic()` before `s` is added to the scene tree so at the moment of that call `s`'s `_Ready` method hasn't been called yet and its `txrBorder` member refers to the `TextureRect` you're initializing it with: `TextureRect txrBorder = new TextureRect();`, not to the `TextureRect` you're assigning to it in `_Ready` with: `txrBorder = GetNode<TextureRect>("txrBorder");`. BTW you have a memory leak in here, you're never freeing that `TextureRect` you're initializing it with. But the question is why are you doing it all (the ` = new TextureRect()` part), you seem to not use/need such new `TextureRect` in the first place.

**Comment by ondesic** [comment]
@kleonc ,
If it is not a bug, that is great.  To answer your question, remove the `= new TextureRect()`  and run the program.  Push the button and see what happens.  The app should crash with this error 
`E 0:02:29.680   void Tokens.SetPic(): System.NullReferenceException: Object reference not set to an instance of an object.
  <C++ Error>   Unhandled exception
  <C++ Source>  C:\Users\mmtbb\Documents\Godot\TxrRect\Scripts\Tokens.cs:21 @ void Tokens.SetPic()()
  <Stack Trace> Tokens.cs:21 @ void Tokens.SetPic()()
                Node2D.cs:24 @ void Node2D.AddToken()()
                Node2D.cs:16 @ void Node2D._on_Button_pressed()()
`

**Comment by kleonc** [comment]
As I've already explained you're calling `SetPic` before `_Ready` is called so at that point `txrBorder` is `null` and thus `txrBorder.Texture` throws a `NullReferenceException`. To fix this ensure `txrBorder` is not `null` before accessing its property. But don't do this by assigning a new `TextureRect` because you don't really use/need it so there's no point in setting its `Texture` property in the first place.

**Comment by ondesic** [comment]
Thanks.  A refresher on the order that functions are called when creating a node helped.
