### ISSUE TITLE
NetworkedMultiplayerENet::close_connection complains if there is no connection

### ISSUE THREAD

**Issue by rhofour** [godotengine/godot#51823]
### Godot version

3.3.1-stable

### System information

Fedora 34 Linux (x86_64)

### Issue description

Not sure if this is a documentation bug or an engine bug, but the behavior of NetworkedMultiplayerENet::close_connection doesn't match with what's documented.

The documentation says:

> Closes the connection. **Ignored if no connection is currently established.** If this is a server it tries to notify all clients before forcibly disconnecting them. If this is a client it simply closes the connection to the server.

However, when I call close connection when there is no connection I see a c++ error printed in the console:
> ERROR: close_connection: The multiplayer instance isn't currently active.
>    At: modules/enet/networked_multiplayer_enet.cpp:458.

### Steps to reproduce

Call NetworkedMultiplayerENet::close_connection before establishing a connection.

**Comment by Calinou** [comment]
This is likely a documentation issue, and can be fixed by modifying the description in the [class reference XML](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html).
