### ISSUE TITLE
body_test_motion causes crash when used with a Rigidbody and Bullet

### ISSUE THREAD

**Issue by mrezai** [godotengine/godot#51847]
### Godot version

3.4-beta3

### System information

OS: ubuntu 18.04

### Issue description

body_test_motion exposed in this PR: https://github.com/godotengine/godot/pull/50103
It works correctly with Godot physics for both KinematicBody and RigidBody, it doesn't crash and result properties like collision_safe_fraction will be updated after calling body_test_motion:
![Screenshot from 2021-08-18 21-58-28](https://user-images.githubusercontent.com/5120436/129945733-1685eb23-5ede-4c61-92a0-d3050a27ba1f.png)

but when calling body_test_motion with Bullet and KinematicBody, the result properties are zero and calling it with RigidBody will cause a crash
![Screenshot from 2021-08-18 21-57-48](https://user-images.githubusercontent.com/5120436/129946664-62c1d5e4-1c76-4e04-875b-f6a48903c414.png)

### Steps to reproduce

Run the attached project

### Minimal reproduction project

[Test-body_test_motion.zip](https://github.com/godotengine/godot/files/7009156/Test-body_test_motion.zip)

**Comment by mrezai** [comment]
@Calinou I think this issue should be added to 3.4 milestone too. I found it on 3.4-beta3

**Comment by akien-mga** [comment]
@mrezai There can only be one milestone on GitHub. The bug is likely valid in both `master` and `3.x` and we usually use the most recent affected branch as milestone in this case.

**Comment by mrezai** [comment]
> @mrezai There can only be one milestone on GitHub. The bug is likely valid in both `master` and `3.x` and we usually use the most recent affected branch as milestone in this case. But the bug will be fixed in both branches.
> 
> Also, nice to see you on Godot's GitHub again after all these years ;)

:+1: 
Thanks, nice is what you and other contributors done in these years. I'm still waiting for Godot :)
