### ISSUE TITLE
Project manager font can't be changed.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#5184]
**Operating system or device - Godot version:**
Xubuntu Linux 14.04 64-bit, freshly compiled Godot from Github.

**Issue description** (what happened, and what was expected):
Project manager font does not change according to font settings from Editor Settings/Global/Custom Font. I would expect it to change after setting 'global' font.

My global font is set and looks like this:
![godot_project_manager_font_bug2](https://cloud.githubusercontent.com/assets/11817561/15995336/04ffbb08-311a-11e6-8b1b-e68ce2422853.png)

In the same time font in Project Manager looks like this:
![godot_project_manager_font_bug](https://cloud.githubusercontent.com/assets/11817561/15995341/1a06d66c-311a-11e6-8683-1d5276ea5cac.png)

**Comment by volzhs** [comment]
and also, should the custom font allow ttf or otf too?
