### ISSUE TITLE
Godot simply not opening projects and freezing my entire computer.

### ISSUE THREAD

**Issue by TrevorBlythe** [godotengine/godot#51869]
### Godot version

3.3 stable

### System information

Ubuntu 20.04 | proccessor: Intel® Pentium(R) Silver N5030 CPU @ 1.10GHz × 4  | graphics: Mesa Intel® UHD Graphics 605 (GLK 3)|   HP LAPTOP BTW

### Issue description

When i start it works just fine, as you can see in the screen shot. Then i try to import a project or make a new project and my computer litterly freezes on the loading screen... This is a new computer and Ive tried waiting like 30 minutes and nothing happens. Is something not supported, i know it cant be this slow right??

IMPORTANT INFO?:
i installed a new WiFi driver before, i don't know if that will help.

I tried on earlier versions and its doesn't work
64 bits Ubuntu. 

![Snapchat-1216963610](https://user-images.githubusercontent.com/77030926/129988724-cf4520cc-8403-4d67-94e3-557be56732fb.jpg)
I LATTERLY HAVE TO RESTART MY COMPUTER WHEN IT FREEZES, ive also tried with and without sudo and re downloaded it and tried nothing seem to work.

### Steps to reproduce

download latest godot release. 

### Minimal reproduction project

Have an identical computer, download Godot, try and run it.

**Comment by akien-mga** [comment]
I don't know what causes the issue, but you should *not* run Godot as root. There's no reason to do it, and it puts you at risk if you download any thirdparty project that would get unrestricted access to your filesystem.

**Comment by TrevorBlythe** [comment]
EDIT: I found a way to workaround and its using opengl 2 setting.... Still cant open my old projects though

**Comment by Calinou** [comment]
> EDIT: I found a way to workaround and its using opengl 2 setting.... Still cant open my old projects though

You can force any project to be opened with GLES2 by passing the `--video-driver GLES2` command line argument to the editor. See [Command line tutorial](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html) for more information.

**Comment by TrevorBlythe** [comment]
looking back at this.. sorry lmao
