### ISSUE TITLE
Result of `CharacterBody`'s gravity calculation on steep slope in air is undesirable

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#51874]
### Godot version

4.0.dev

### System information

MacOS 11.4, Windows 10

### Issue description

At first I thought it was a problem on the GDScript side. However, probably the current implementation does not allow to coexist the behavior of "preventing `CharacterBody` slide-up wall in air" and "resetting gravity".

When `is_on_floor() == true`, `linear_velocity.y` is set to `0` after `move_and_silde()`, even if it is added gravity infinitely. The same is true for `is_on_floor() == true && is_on_wall() == true` and `linear_velocity.xz`. 

In the sample project, I intentionally keep the previous frame's `velocity.y` on steep slopes in air, because if we don't keep it, `CharacterBody` will slide-up the steep slope in air. In addition, GDScript has no way to determine if `CharacterBody` is stuck in the air between walls, so as a result, `CharacterBody` will continue to be added gravity. If the `CharacterBody` is stuck between walls and the `linear_velocity.y` is `0`, there is a possibility to get out of the stack by horizontal moving.

On a steep slope in air, someone may need a slower sliding-down behavior but I think anyone doesn't want the behavior of sliding-up, so may need to fix the calculation of gravity on steep slope in air.

### Steps to reproduce

https://user-images.githubusercontent.com/61938263/130021803-66ef777d-9d1b-487a-b620-7a4f1e7f07ed.mov

If comment out lines 178~180 of `Player.gd` in the sample project

https://user-images.githubusercontent.com/61938263/130032204-836874db-828d-46c1-bfea-857326c6df77.mov

### Minimal reproduction project

Same #50732.

**Comment by TokageItLab** [comment]
Note:
It could possibly be that solving the jittering slope problem will also solve "sliding up wall" problem, so please prioritize the solving jittering slope problem.

**Comment by pouleyKetchoupp** [comment]
Thanks for these use cases! They will be useful to test when porting #51027 to 3D. I'm pretty sure the new options will help with these scenarios.

**Comment by pouleyKetchoupp** [comment]
Could you please open an separate issue for the character stuck in between the cylinders (first video) with some details about the expected behavior? It's going to be a different problem to solve.

**Comment by TokageItLab** [comment]
> In the sample project, I intentionally keep the previous frame's velocity.y on steep slopes in air, because if we don't keep it, CharacterBody will slide-up the steep slope in air. In addition, GDScript has no way to determine if CharacterBody is stuck in the air between walls, so as a result, CharacterBody will continue to be added gravity. If the CharacterBody is stuck between walls and the linear_velocity.y is 0, there is a possibility to get out of the stack by horizontal moving.

@pouleyKetchoupp As you can lead, the cause of the first problem is mainly on the GDScript side. And, here are some reasons why this is inevitable.

> the current implementation does not allow to coexist the behavior of "preventing CharacterBody slide-up wall in air" and "resetting gravity".

**Comment by pouleyKetchoupp** [comment]
@TokageItLab Ah I see, thanks for the details. So if I understand correctly, the expected behavior is to be able to move horizontally when stuck in the cylinders, without moving vertically on the wall.

#51904 will fix the issue with the wall itself, but the player will be still stuck in the cylinders, so we'll have to handle this case with a separate fix.
