### ISSUE TITLE
Camera2D's "current" property reset after switching scene

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#51872]
### Godot version

v4.0.dev.custom_build [84b11fbaa]

### System information

Windows 11, Vulkan Clustered

### Issue description

Camera2D forgets its `current` state after switching scene.

![camera-2d](https://user-images.githubusercontent.com/28705694/130013265-4b06f523-b502-474d-b264-ccd1807123b3.gif)

### Steps to reproduce

Add a Camera2D node, set `current` as true, switch to another scene, switch back and check.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/7011948/Test.zip)

**Comment by Calinou** [comment]
Does this occur with Camera (in 3D)?

**Comment by floppyhammer** [comment]
@Calinou Nope.

**Comment by Calinou** [comment]
I forgot to ask, can you reproduce this in `3.x`?

**Comment by floppyhammer** [comment]
@Calinou No, only in 4.0.
