### ISSUE TITLE
for mychar in mystring : (iterating through each characters of a string)

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5188]
**Operating system or device - Godot version:**
Official 2.0.3stable win64

**Issue description** (what happened, and what was expected):
That would be cool if it was possible to iterate through each characters of a string using this simple syntax :

````
var mystring = "Hell of words";
for c in mystring :
    print( c )
````

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment]
same issue on FB group.

https://www.facebook.com/groups/godotengine/permalink/787646541371942/

**Comment by akien-mga** [comment]
This is a feature in many languages, including Python 2 and 3, so it would definitely be worth having in GDScript too.

**Comment by djrm** [comment]
in python iterating over unicode string will be per byte so a unicode character will return 2 characters in the iterator, should this function do the same, or should it do the expected thing (that is if string = 'á' the iterator returns 'á')?.

**Comment by vnen** [comment]
@djrm it should return the correct character, otherwise you'd have to parse the unicode in every string iteration you make. It's unneeded complexity for game scripting.

**Comment by OvermindDL1** [comment]
As long as there is some fall-back way to operate per byte (string.as_bytearray() or so?).

**Comment by vnen** [comment]
There are already `String.to_utf8()` and `String.to_ascii()` if you need a `RawArray`.
