### ISSUE TITLE
GODOT: screen orientation is not updating when auto-rotate icon in the upper tab of the phone is re-locked

### ISSUE THREAD

**Issue by jcgamedevph** [godotengine/godot#51880]
### Godot version

3.3.2 stable standard

### System information

GLES3

### Issue description

I tried to make a code that can access the screen orientation of the game screen to rotate automatically even without the user try to click the auto-rotate icon of their android phone...   my code works until it stop working if I re-locked the auto-rotate icon from the upper tab of my phone while the test game run... I think the problem is not to my code anymore but to the engine.  By the way I am using GDscript...  can someone fix this or tell me what is wrong ,, is it my code or the engine itself... please help. And by the way also, it goes back working if I switch off my phone and then switch it on while the game still running... 

### Steps to reproduce

```gdscript
extends Node2D

var orientation_ctr = 0
var ystring
var ACCELEROMETER


func _process(delta):
	ACCELEROMETER = Input.get_accelerometer()
	
	ystring = ACCELEROMETER.y

		

	if ystring >= 8:
		
		if orientation_ctr == 0:
			OS.screen_orientation = OS.SCREEN_ORIENTATION_LANDSCAPE
			orientation_ctr += 1
		elif orientation_ctr == 1:
			OS.screen_orientation = OS.SCREEN_ORIENTATION_REVERSE_LANDSCAPE
			orientation_ctr = 0


		
	$"Label 1".text = "Y axis: %d" % ystring

# this code works smoothly even the auto-rotate icon of the phone is locked i can still auto-rotate my game screen  until it stop working if i re-locked the auto-rotate icon from the upper tab of my phone while the test game keeps on running and so the auto-rotate of my game stop also...
```

### Minimal reproduction project

Here is my sample project:

[test screen orientation.zip](https://github.com/godotengine/godot/files/7013295/test.screen.orientation.zip)

**Comment by jcgamedevph** [comment]
i wish there is an auto-rotate detection if locked or unlocked in godot to solve the issue above

like this one.....

if (android.provider.Settings.System.getInt(getContentResolver(), Settings.System.ACCELEROMETER_ROTATION, 0) == 1){
        Toast.makeText(getApplicationContext(), "Auto Rotate is ON", Toast.LENGTH_SHORT).show();

    }
    else{
        Toast.makeText(getApplicationContext(), "Auto Rotate is OFF", Toast.LENGTH_SHORT).show();
    }

**Comment by madmiraal** [comment]
This is not a bug. If the `Project Settings -> General -> Display -> Window -> Handheld -> Orientation` is set to `sensor_landscape`, the screen rotates as expected, and rotations can be locked and unlocked by the user.

Godot's `sensor_landscape` maps to Androids [`userLandscape`](https://developer.android.com/guide/topics/manifest/activity-element#screen) setting, which automatically rotates the screen between `landscape` and `reverse_landscape` based on the device's orientation and allows the user to control whether or not and when these rotations happen.

It sounds like you want Android's [`sensorLandscape`](https://developer.android.com/guide/topics/manifest/activity-element#screen) setting, which will rotate the screen between `landscape` and `reverse_landscape` based on the device orientation regardless of whether or not the user wants it to. This would require additional `Orientation` options to be created, which would require a proposal: https://github.com/godotengine/godot-proposals

**Comment by jcgamedevph** [comment]
Thanks for clarification, <3
