### ISSUE TITLE
Black inconsistent blobs on environment reflections due to horizon specular occlusion

### ISSUE THREAD

**Issue by 20kdc** [godotengine/godot#51897]
### Godot version

3.4.beta4

### System information

Linux 64-bit, Ubuntu 20.04.1, AMDGPU RAVEN2, GLES2 & GLES3

### Issue description

Not really sure what to say further.
![image](https://user-images.githubusercontent.com/22304167/130138078-22ec9898-9869-44ff-8693-220f567d4a68.png)

My personal speculation is that this is caused by https://github.com/godotengine/godot/commit/1065f8dc863bbc2dac985213c5e95b5d2b238ed3 - EDIT: seems to be consistent with findings, see later comments.

Initially found by @DeerTears on an upgrade to 3.4.beta4 - they were busy so I'm writing the report.
Speculation, screenshots, etc. is my own.

### Steps to reproduce

(To use test project)
Just run it, although flying around in the editor helps if you want specific angles.
(to create new project demonstrating issue)
1. Create a new project.
2. Create a sphere.
3. For the most obvious effect, metallic of 1, roughness of 0.
4. Fly around in editor, see effect.

### Minimal reproduction project

[horiz.zip](https://github.com/godotengine/godot/files/7017514/horiz.zip)

**Comment by Calinou** [comment]
I can confirm this on the Material Testers demo in 3.4 beta 4 as well.

**Comment by 20kdc** [comment]
Bug is likely because in both GLES2 and GLES3 `ref_vec` gets modified after reflection for use by the cubemap sampling, which is the divergence in the maths between the master version and the 3.x version.

Specifically it's transformed by, among other things, radiance_inverse_xform, which also explains why the effect moves with sky rotation.

**Comment by 20kdc** [comment]
Ok, so, having tried that, and looked at the 4.0 PR again, I'm wrong about ref\_vec, but having actually moving the horizon check back I can at least definitely confirm it was that commit causing the blobs.
I'm also reasonably sure that the Z inversion on GLES2 is meant for the cubemap and therefore will mess with things anyway, so the horizon check there still needs re-ordering.

**Comment by clayjohn** [comment]
@20kdc That is the right fix! Good catch. It still results in better specular highlights than in 3.3

_3.3_
![Screenshot (213)](https://user-images.githubusercontent.com/16521339/130179635-c8ea314d-fe94-4ad5-bcbc-1471c14808e8.png)

_3.4 with 20kdc's fix_
![111](https://user-images.githubusercontent.com/16521339/130179636-b179bb3e-51d4-4f43-b44b-9debb4371d14.png)

**Comment by 20kdc** [comment]
Uuuuh, which iteration of the fix? 1f079ed , or the one where the check is moved back (which has disappeared but I can recreate)?

**Comment by clayjohn** [comment]
1f079ed but without the comments referencing this Github Issue

**Comment by 20kdc** [comment]
So apparently that was actually the one I was talking about, so it never disappeared anyway.
I'm confused, but whatever. I'll run a test and will PR once I confirm on a test project.
