### ISSUE TITLE
Godot 4 Slow saving and too big file after saved

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#51891]
### Godot version

v4.0.dev.calinou [31dfdcb69]

### System information

Win 10 64, AMD RX 480

### Issue description

Saving the scene take too long and after the file is saved, its too big( tscn file )
The scene contains some mesh instances and other nodes, but the saved file is like 180mb.

Edit: I found that the file become slow and big after i press the make local on the imported instance node.

### Steps to reproduce

Just press save.

### Minimal reproduction project

https://drive.google.com/file/d/1Zjh4QQmu8QLKfl_2gL00G5xWpXcaXlge/view?usp=sharing

**Comment by Calinou** [comment]
> Edit: I found that the file become slow and big after i press the make local on the imported instance node.

This is expected, because binary data will be saved to a `.tscn` file as Base64. This is slow and makes it significantly larger.

If you need to save local resources, save it to an external binary `.res` resource file (*not* `.tres`), or save a binary scene (`.scn` instead of `.tscn`).
