### ISSUE TITLE
Seemingly Active Input Fields Need Extra Click

### ISSUE THREAD

**Issue by ngreve** [godotengine/godot#51893]
### Godot version

v4.0.dev.custom_build [93dac1c7d]

### System information

Linux (Window Manager: i3)

### Issue description

When the Godot editor opens a popup (e.g. when wanting to create a new node), the popup window will be the now active window.
If the window has a text input box, this input box is most likely pre-selected, so it should be possible to start typing and entering whatever you want, in this input box. Unfortunately, even though the input box seems selected and you should be able to start typing right away, you actually need to do the extra click to manually select the input box. Only after that extra click, you can start typing.

This extra click should not be necessary.

The video below, explains it best.

### Steps to reproduce

https://user-images.githubusercontent.com/18660100/130119954-7e2c4418-49e2-43e0-bb2d-68078001ea71.mp4

**Comment by Calinou** [comment]
This is because the window is not focused automatically.
