### ISSUE TITLE
Vulkan: When a (CSG)Mesh doesn't have a surface/material, the viewport turns black or material turns invisible

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#51898]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 #51881

### System information

macOS 11.5 

### Issue description

In the following project: https://github.com/TokageItLab/3d-platform-test-for-godot4 , materials are not showing correctly:

![before](https://user-images.githubusercontent.com/6397893/130149230-bc1e5edc-f3a8-4b20-b926-b17efa802741.gif)

_Note: the bug can happen in just some angle (not sure why, seems to be related to how many object without material), you need to rotate the camera be sure of the situation:_

![after](https://user-images.githubusercontent.com/6397893/130150170-cee7216f-d8d1-4231-aa7d-697527cd0995.gif)

**I discover this issue is related to meshs. If a mesh doesn't have a material/surface, this issue happens:** (the default material is the issue?)

I have a feedback from a windows 10 user that not see this bug, it's why I think it can be Mac related.

https://user-images.githubusercontent.com/6397893/130149898-96d41e29-cdea-40dd-8e8b-ecf6e3094ec4.mp4

Here what is shown in the console, not sure if useful:

```

res: script valid 0
res: script valid 0
res: script valid 0
res: script valid 0
res: material_override valid 0
res: material valid 1
path res://Materials/WorldGrid.tres
res: script valid 0
res: script valid 0
res: script valid 0
res: script valid 1
path res://MovingObjects/PlayAnimation.gd
res: script valid 0
res: physics_material_override valid 0
res: script valid 0
res: material_override valid 0
res: material valid 0
res: script valid 0
res: shape valid 1
path res://MovingObjects/RollingPlane/RollingPlane.tscn::3
res: script valid 0
res: script valid 0
ERROR: Condition "!material" is true.
   at: material_set_shader (servers/rendering/renderer_rd/renderer_storage_rd.cpp:1547)
```

### Steps to reproduce

I made a simplified version of the project.

1. Open the project, and rotate the camera in the editor to see if there is an issue.
2. If yes, open the `RollingPlane` scene and add a material to the `CSGBox3D` node, 
3. Return to the main scene, the bug is gone.

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/7017947/minimal.zip)

**Comment by Calinou** [comment]
Can you reproduce this after changing the renderer from **Vulkan Clustered** to **Vulkan Mobile** in the Project Settings, then restarting the editor? (**Rendering > Vulkan > Rendering > Back End**)

**Comment by fabriceci** [comment]
@Calinou Yes, the bug is the same, seems like there is a place somewhere, where if no material is set, that causes the error.

Do you use Linux? I wondering if this is mac only.

**Comment by Calinou** [comment]
> Do you use Linux? I wondering if this is mac only.

Yes – I don't have access to macOS hardware.

**Comment by paddy-exe** [comment]
Alright I just ran the above example in the latest ci build from you Calinou. I have an M1 Macbook Air. I got the following error messages: https://imgur.com/a/8fphr91
Seems like the error comes from line 1547 from servers/rendering/renderer_rd/renderer_storage_rd.cpp

**Comment by fabriceci** [comment]
@Calinou  good news :) fixed in Godot 4 Alpha 11 (FYI the bug is present in the alpha 10).

**Comment by fabriceci** [comment]
For the record it works fine on alpha 11 and 12, but compiled from the master to the same commit as alpha 12, the problem returns.

![texture-bug](https://user-images.githubusercontent.com/6397893/179750278-cb933a49-031f-4ecc-9389-7d9ac574b396.jpg)

According to @bruvzg in the chat, this may be due to the difference in version of MoltenVK between the official build and the master.

**Comment by bruvzg** [comment]
> According to @bruvzg in the chat, this may be due to the difference in version of MoltenVK between the official build and the master.

Also, make sure you have deleted shader cache before switching version: `./godot/shader_cache` in the project folder and `~/Library/Application Support/Godot/shader_cache`. It might be incompatibility of compiled shader code, not a bug in MoltenVK.

**Comment by fabriceci** [comment]
> Also, make sure you have deleted shader cache before switching version: `.godot/shader_cache` in the project folder and `~/Library/Application Support/Godot/shader_cache`. It might be incompatibility of compiled shader code, not a bug in MoltenVK.

I've tried, it doesn't change anything.
