### ISSUE TITLE
bool Dictionary.has(var value) is misleadingly documented

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5190]
**Operating system or device - Godot version:**
official 2.0.3stable

**Issue description** (what happened, and what was expected):

This is minor but, the current Dictionary doc says ``bool has(var value)`` is slightly misleading.

I think it should be ``bool has(var key)``.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Fixed by #5192.
