### ISSUE TITLE
Performance issue in GodotPhysics

### ISSUE THREAD

**Issue by mrezai** [godotengine/godot#51909]
### Godot version

3.4-beta4

### System information

OS: ubuntu 18.04

### Issue description

There is a performance issue in GodotPhysics that seems doesn't exist in v3.3.2-stable. Bullet is OK in both versions.

Godot v3.3.2-stable:

https://user-images.githubusercontent.com/5120436/130202793-30236392-5f72-4b3e-8e55-d08129d7de41.mp4

Godot v3.4-beta4:

https://user-images.githubusercontent.com/5120436/130203150-b64ebdd4-054a-4256-a338-609364c62b35.mp4

Bullet:

https://user-images.githubusercontent.com/5120436/130203774-4a44fa0e-8c6e-4053-b067-8f655aa2eb1b.mp4

### Steps to reproduce

Run the attached project.
If textures doesn't show, select QodotMap node, select "addons/qodot/example_scenes/1-interactivity/1-brush-entities/1-brush-entities.map" in Map File property and press "Full Build" button.

![Screenshot from 2021-08-20 13-02-49](https://user-images.githubusercontent.com/5120436/130205108-35735398-5edf-43bb-aaec-e9f93160b9f5.png)

### Minimal reproduction project

[GodotPhysicsIssue.zip](https://github.com/godotengine/godot/files/7020265/GodotPhysicsIssue.zip)

**Comment by mrjustaguy** [comment]
Does this happen in 3.3.3 Stable?

**Comment by qarmin** [comment]
![Zrzut ekranu z 2021-08-20 11-24-31](https://user-images.githubusercontent.com/41945903/130212062-30f7cf8e-5ec2-450c-9db9-ad4906d2f8c1.png)
