### ISSUE TITLE
Godot 2D Tilemap Performance while zooming out

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#5191]
**Operating system or device - Godot version:**
Windows 7 64 bits
Godot 2.1 Alpha

**Issue description** (what happened, and what was expected):
While zooming out camera, FPS start dropping. Don't know if I doing something wrong or it's engine related.
Tileset is made of 64x64 tiles (independant png) to avoid artefact with unique big png. If I hide floor tilemap, then i have no FPS drop.

**Steps to reproduce:**
Combine 2D Tilemap and camera, populate tilemap (large), then zoom out

**Link to minimal example project** (optional but very welcome):
https://www.youtube.com/watch?v=ThYeRtSqeBU

**Comment by set-killer** [comment]
Did you try to increase the quadrant size? 
This option is combining a bunch of tiles (16 default) into single image. It should speed up the rendering.

**Comment by TotCac** [comment]
I have actually set it to maximum ie 128, and no change :/

**Comment by reduz** [comment]
if tiles become tiny, performance will definitely decrease. This is not a bug, it's just a lot of draw calls.
if performance and extreme zooming out is required, try using a shader that does this

**Comment by TotCac** [comment]
@reduz can you provide a link, tutorial or something plz because i am a newbee with shaders and can't get what you mean by shader@tilemap
