### ISSUE TITLE
GLES3 (as opposed to GLES2) reflection probes at odd angle and don't seem to reflect objects

### ISSUE THREAD

**Issue by 20kdc** [godotengine/godot#51924]
### Godot version

3.3.2.stable, 3.4.beta4

### System information

Linux, Ubuntu 20.04.1, AMDGPU RAVEN2, GLES3

### Issue description

More poking reflection probes to see what breaks...

Well, they're broken.

### Steps to reproduce

Project below shows both behaviours.
Switching to GLES2 will show the reflection probe working as expected.
![image](https://user-images.githubusercontent.com/22304167/130256406-8ca1da49-c50a-44ed-9d58-7477fbf7854c.png)
Switching to GLES3 will show the reflection on it's side and not reflecting expected objects.
(Cubemap resolution was downsampled due to a severe increase in GPU load on GLES3. The problem persists at higher resolutions.)
![image](https://user-images.githubusercontent.com/22304167/130256308-3b1592d2-908b-41ce-a2ee-40344eb52c23.png)

Setting the reflection probe update mode to "Once" results in even more broken output.
![image](https://user-images.githubusercontent.com/22304167/130256711-2ffb8557-05fa-4e15-8158-f2bb3d26a6bc.png)

### Minimal reproduction project

[lab.zip](https://github.com/godotengine/godot/files/7022527/lab.zip)

**Comment by clayjohn** [comment]
Do you get the same behaviour in 3.3.2 or 3.3.3?

**Comment by 20kdc** [comment]
Yes.
![image](https://user-images.githubusercontent.com/22304167/130258873-70d8deee-3641-4d07-a736-210be8f73f65.png)

**Comment by clayjohn** [comment]
I ran it in the web editor and the results look good in both GLES3 and GLES2. 
![Screenshot (20)](https://user-images.githubusercontent.com/16521339/130260426-56ce8b11-0fe2-45cf-af95-8aa743fb7fcb.png)

This may be a hardware dependent issue, so we will need testing from a few users to see if we can triangulate the problem.

**Comment by 20kdc** [comment]
Bug not in 3.1-stable
![image](https://user-images.githubusercontent.com/22304167/130262379-18a874bb-b577-463e-b900-134e86efbd6e.png)
But is in 3.2-stable
![image](https://user-images.githubusercontent.com/22304167/130262604-ebc0c110-0ded-4c8f-b29a-d07ab32db29d.png)

**Comment by 20kdc** [comment]
Ok, got something more precise:
Bug not in 3.2-beta1
![image](https://user-images.githubusercontent.com/22304167/130263347-37ba475a-74f0-4378-ad51-2dc016623c86.png)
But is in 3.2-beta2
![image](https://user-images.githubusercontent.com/22304167/130263382-e99bbe23-440e-4f20-bc14-e233931cc64a.png)

**Comment by clayjohn** [comment]
I have a feeling it is https://github.com/godotengine/godot/commit/cd40154890ba9791b219d66beaf187a7d8dcdba5 but no changes to reflection probes were made in that commit, so it may take a little digging

**Comment by 20kdc** [comment]
Updated reproduction project, should show more information for screenshots
[lab.zip](https://github.com/godotengine/godot/files/7022920/lab.zip)

**Comment by clayjohn** [comment]
Okay, I have a theory, I think that the sky code is accidentally leaving some state set in the cubemap filtering shader. When using texture array at the end these three condiitons are set to "False":
https://github.com/godotengine/godot/blob/16642e28380cf5513fad6ea8591f809e42820382/drivers/gles3/rasterizer_storage_gles3.cpp#L1931-L1933

buuut, when using a regular texture only 2 of the three conditions are set to false:
https://github.com/godotengine/godot/blob/16642e28380cf5513fad6ea8591f809e42820382/drivers/gles3/rasterizer_storage_gles3.cpp#L2067-L2068
So the conditional ``CubemapFilterShaderGLES3::USE_SOURCE_DUAL_PARABOLOID`` is left at true

the reflection probe code never touches the conditional so it is left as true
https://github.com/godotengine/godot/blob/16642e28380cf5513fad6ea8591f809e42820382/drivers/gles3/rasterizer_scene_gles3.cpp#L714-L747
The reflection probe code always uses a cubemap source so ``CubemapFilterShaderGLES3::USE_SOURCE_DUAL_PARABOLOID`` should always be false. 

The solution is to set ``CubemapFilterShaderGLES3::USE_SOURCE_DUAL_PARABOLOID`` to false here:
https://github.com/godotengine/godot/blob/16642e28380cf5513fad6ea8591f809e42820382/drivers/gles3/rasterizer_storage_gles3.cpp#L2067-L2068

**Comment by 20kdc** [comment]
This bug is fixed as of (at the latest) 76693aa but is likely fixed well before then, closing.
