### ISSUE TITLE
Room Manager have strange named enums `RoomManager.RoomManager::PVS_MODE_DISABLED`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#51926]
### Godot version

3.4 beta 2

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

RoomManager have 3 strange enums
```
RoomManager.RoomManager::PVS_MODE_DISABLED
RoomManager.RoomManager::PVS_MODE_FULL
RoomManager.RoomManager::PVS_MODE_PARTIAL
```
Cannot use them, because Godot shows GDScript error

Others enums looks in this way
```
SceneState.GEN_EDIT_STATE_DISABLED
SceneState.GEN_EDIT_STATE_INSTANCE
SceneState.GEN_EDIT_STATE_MAIN
SceneTree.GROUP_CALL_DEFAULT
SceneTree.GROUP_CALL_REALTIME
SceneTree.GROUP_CALL_REVERSE
SceneTree.GROUP_CALL_UNIQUE
```

### Steps to reproduce

Above

**Comment by lawnjelly** [comment]
Ah it's probably how I've bound them doesn't work with the macro:
```
	BIND_ENUM_CONSTANT(RoomManager::PVS_MODE_DISABLED);
	BIND_ENUM_CONSTANT(RoomManager::PVS_MODE_PARTIAL);
	BIND_ENUM_CONSTANT(RoomManager::PVS_MODE_FULL);
```
And looking at the other places BIND_ENUM_CONSTANT is used, the class scope isn't used so maybe this is causing problems. Will try this out tomorrow. :+1:
