### ISSUE TITLE
Loading different animation resource from same skeleton, different file causes corrupt animation (GLTF)

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#51931]
### Godot version

 v3.3.3.stable.official

### System information

Windows 10 GTX 1060 6gb Intel 4690k

### Issue description

Potentially linked issues include #50212, but perhaps less so #51785.
#50212 Doesn't focus on loading the resource.

You can have two of the same skeletons, no difference in settings; however, when you attempt to move animations between these skeletons, the animation is corrupted.

ex. Skeleton A has animation B and Skeleton C has animation D.
A and C are the same skeleton, no difference in anything, except for the fact they are two different exports.

You can't copy animation D to skeleton A. The animation ends up being corrupted/off. Same goes for animation B to Skeleton D.

It doesn't matter if you copy paste the animations, save the animations as a resource then load them into different skeletons, or turn off optimize animations in the GLTF import.

Here is short vid: https://youtu.be/Y6JX2CK95d8

### Steps to reproduce

Export two armatures/skeletons from blender. Same skeleton, don't change anything, just give both of these skeletons different animations.

Load these armatures into godot, and create a scene for each GLTF import.

Copy the animation from one skeleton onto the other one, and the animation will not be correct, despite there being no difference in the skeletons.

### Minimal reproduction project

There are two models. INSPECTAHDECK and METHODMAN. For this example, copy the animation "Armature002|mixamocom|Layer0 Retarget" from INSPECTAHDECK to METHODMAN, either by copy paste or saving and loading a resource. The animation will come out corrupted. In scene METHODMAN, this has already been done as an example. The result animation is labeled "CorruptAnimationExample", however for debugging purposes you may want to follow the above instructions.

Regardless of models and animations, this issue plagues all models and anims. Different animations using the same skeleton won't work correctly unless they are exported in the same file

Ignore the blockBroken animation, that one works on both because it was exported alongside both skeletons, so it has no impact on the bug/investigation
[AnimationTransferBug.zip](https://github.com/godotengine/godot/files/7024134/AnimationTransferBug.zip)

**Comment by fire** [comment]
My analysis of similar problems was done in https://github.com/godotengine/godot-proposals/issues/2961 and https://github.com/godotengine/godot/pull/51057.

Godot does not have generalized retargeting support and glTF2 if you are not strict about starting from the rest pose has an issue with reset.

**Comment by stryker313** [comment]
I'll give you as much data as I can, and create more debug projects if you need them, as I have run into this problem quite frequently across many different scenarios.
I use rokoko retargeting tool to put animations on my skeleton
What's weird is that I verify that the supposed "rest_pose" (in blender, there is the "pose_position" and "rest_position") are the same, or at least appear to be before the files are exported. Once again, nothing modified, nothing change, just different animations with the same rest pose. So, at least from my perspective, something is either happening during the GLTF export from blender or during the GLTF import by godot that is causing some type of shift, because if the animations can work when exported WITH the skeleton, but not work when exported WITHOUT the skeleton, something has to be occurring during the transition from blender to gltf or gltf to godot.

A workaround for some people can be https://github.com/smix8/GodotAnimationRetargeting, however this doesn't work 100% and minor repair work is needed after using it.

**Comment by fire** [comment]
Here's my copy of the retargeter from rokoko, may the Blender addon help. https://github.com/V-Sekai/blender-skeletal-motion-animate

**Comment by fire** [comment]
Also please investigate the "fortune" and "temperance algorithms from Blender". The fortune and temperance algorithms happen on Blender import.

**Comment by stryker313** [comment]
Im confused by the blender addon. How is that one different from the one you can get from https://github.com/Rokoko/rokoko-studio-live-blender ?

**Comment by fire** [comment]
@stryker313 I want to streamline using the Blender plugin and making it more usable.

**Comment by stryker313** [comment]
Currently looking into fortune and temperance on GLTF import, but something to note: This error happens on the SAME skeleton, SAME save file, making me believe that import error is less likely.

For example, if you import a gltf, save the file.Then resuse this file. ie. retargeting anims to this skeleton, exporting, then not saving the skeleton so that the save file can be used a clean slate for other animations.  I don't know that fortune and temperance would be contributing to this error if it is the same skeleton with the same rest pose (unless rokoko would be changing the rest pose, which it would seem is unlikely) Even though you are importing a different skeleton for retargeting animations, the target skeleton is still not changing, nor would the rest pose.

Are there any settings that you think could make a difference in the GLTF export? (That's a more likely scenario I'd think. Between that and godot)

**Comment by TokageItLab** [comment]
Currently, if you want to set an optional T-pose as the initial pose for the model you are importing into the Godot, **you need to have the T-pose animation at the top of animation track on the Blender**.

@fire How about adding the initial rest pose selector to the import settings?
