### ISSUE TITLE
Array.sort() should return a reference to the array

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5193]
**Operating system or device - Godot version:**
official 2.0.3stable

**Issue description** (what happened, and what was expected):

This is a detail again but, currently `Array.sort()` returns void.

In certain cases, it could be handy if it was returning the array itself.

For instance it would be possible to write something like this :

```
#displaying dictionary content by alphabetical order :

for key in mydictionary.keys().sort() : #{
     print( key + " = " + mydictionary[key] );
#}
```

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Currently `sort()` does not make a copy, it sorts the calling array itself. So this could (or not) have some unwanted side-effects.

**Comment by slapin** [comment]
Actually this behavior of sort is really confusing, it would be much better if it returned a sorted copy
or at least allow that via parameters. Anyway it is another bug matter.

**Comment by SuperUserNameMan** [comment]
allowing a copy by parameter is okay.
but returning a copy by default, it would make certain use-case slower and more memory hunger.

but yeah, `Array Array.sort( my_array, bool_copy = false )` would be cool

**Comment by nhydock** [comment]
Could the Array.sort() just always return the reference to the array that's sorted, regardless of if it's a copy or not, so then you can chain operations?

**Comment by SuperUserNameMan** [comment]
sure

**Comment by Toizi** [comment]
I have created a PR for this where sort, sort_custom and invert now return a reference to the array
#11919

**Comment by Hinsbart** [comment]
#11919 has been merged, so the original problem is solved.
Feel free to open a new issue about optionally returning a copy.

**Comment by FormerlyWD** [comment]
It still returns void. Please fix this.

**Comment by AThousandShips** [comment]
Changing this now would break compatibility so can't be done, instead a new method would have to be added, see:
* https://github.com/godotengine/godot-proposals/issues/2633

For this change specifically see:
* https://github.com/godotengine/godot-proposals/issues/5771
