### ISSUE TITLE
Animation glitch when minimizing editor by Show desktop on Windows 11 (caused by low processor mode)

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#51946]
### Godot version

v3.4.beta3.official [8db0bd442] and v4.0.dev.custom_build [0a001afec]

### System information

Windows 11, Vulkan Clustered

### Issue description

![show_desktop](https://user-images.githubusercontent.com/28705694/130317670-109a81bb-a4dd-42d9-80f3-231a5f58f1e5.gif)

### Steps to reproduce

Minimize the editor by clicking on Show desktop on Windows 11.

### Minimal reproduction project

No need.

**Comment by Torguen** [comment]
windows 11 is not even officially available as stable ... I don't think it is necessary to correct anything at the moment.

**Comment by floppyhammer** [comment]
Alright then.

**Comment by pycbouh** [comment]
On the contrary, early tech previews are mostly targeted at devs so that they can check if their apps are working properly. This is worth reporting.

**Comment by Torguen** [comment]
I would not pay attention to it, maybe it is something that will change in windows later and then we will have to modify Godot again.

**Comment by pycbouh** [comment]
That's not a hard thing to do, and can boil down to reverting a single PR. It doesn't mean issues shouldn't be reported, or that we shouldn't prepare for new releases beforehand. There is no harm in logging it and if someone wants to investigate it, it's okay as well.

**Comment by floppyhammer** [comment]
@Torguen I kind of doubt it's Windows' problem as I haven't met such an issue with other apps.

**Comment by Calinou** [comment]
- Can you reproduce this if you enable **Update Continuously** in the Editor Settings?
- Can you reproduce this if you comment out [this line](https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L5787) then recompile the editor?

**Comment by floppyhammer** [comment]
@Calinou The first solution works while the second doesn't.

**Comment by KoBeWi** [comment]
Is this still reproducible on newest master?

**Comment by floppyhammer** [comment]
@KoBeWi No.
