### ISSUE TITLE
1 pixel wide lines remain thin when `CanvasItem` is scaled

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#51978]
### Godot version

4.0 dev

### System information

Kubuntu 21.04

### Issue description

When the `CanvasItem` is scaled, the 1 pixel wide lines remain thin (although other transformations apply). Thick lines are scaled correctly.

Probably a bug in the `RenderingServer::canvas_item_add_line` function, `RendererCanvasCull::canvas_item_add_line` or deeper.

See [the comment](https://github.com/godotengine/godot/pull/41239#issuecomment-903227192).

![](https://user-images.githubusercontent.com/47700418/130351343-05850ccd-1841-4c84-80cb-f55ade5d42c1.png)

Also related: #41023.

### Steps to reproduce

See the MRP.

### Minimal reproduction project

[1px_line_bug.zip](https://github.com/godotengine/godot/files/7027084/1px_line_bug.zip)

**Comment by Calinou** [comment]
This is done by design: https://github.com/godotengine/godot-proposals/issues/1363
