### ISSUE TITLE
content of LineEdit and TextEdit partially disappear from sight when the window is reduced and restored 

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5197]
**Operating system or device - Godot version:**
Official 2.0.3win64, windows 8.1

**Issue description** (what happened, and what was expected):

Today, I've decided to be a magician.
I have written 3 sentences into a LineEdit and two TextEdit nodes.
I'm going to slice each one of them in two parts using the caret.
Then I'll make the first part of each sentences disappear from sight all at once just by reducing and restoring the window.

Better than an explanation, here is a video record of my show :

![textedit_lineedit_windows_resize](https://cloud.githubusercontent.com/assets/9801802/16021297/2a11247a-31b2-11e6-9348-9bef37a56a2e.gif)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by Paulb23** [comment]
Could this be related to #4444

**Comment by SuperUserNameMan** [comment]
@Paulb23 : i'm not sure it is related, because in this case, the text is not deleted from the text boxes.
It is like "scrolled".
When you press the "Beginning" key (I don't know how it is called on international keyboards, this is the key between "insert" and "page up", and above the "End" key) ... so when you press the "begin" key, the text is fully visible again.

On the #4444 which seems to have  #4656 as duplicate, the scripts were lost for ever.

**Comment by vnen** [comment]
I don't think it is related. This seems to be about the cursor position and focus.

As a note: the "beginning" key is called <kbd>Home</kbd>.

**Comment by Paulb23** [comment]
@SuperUserNameMan Ahh that makes sense  it looked liked you were undoing instead of pressing the "Home" key.

**Comment by reduz** [comment]
it may be related that when window is minimized it is super shrunk, it
should simply ignore doing anything if the window is minimized

**Comment by SuperUserNameMan** [comment]
and btw, this also happens with the script editor itself. 
You put the caret in the middle of a long line, then reduce the editor then bring it back, and the script is scrolled to the left without showing any horizontal scrollbar. Then only the [home] key will put it back to normal.

**Comment by vnen** [comment]
Hmm, I can reproduce this with the script editor, but it doesn't happen all the time. It seems to be problem when *restoring* the window, not when *minimizing* it, because the peek shows fine but it changes when I click.

**Comment by reduz** [comment]
thanks to @vnen recent fix, this should no longer happen (screen is no longer resized to 0,0)
