### ISSUE TITLE
Randomly white lines in Visual Script go black.

### ISSUE THREAD

**Issue by fire** [godotengine/godot#51988]
### Godot version

4.0.dev fb176d5f6e6dc2b43c630a041a8ab7d737173ec4

### System information

popos 20.04 Linux

### Issue description

![image](https://user-images.githubusercontent.com/32321/130365192-6900920f-b557-4bc9-8a4e-50a6d0bc73de.png)

Randomly the white lines go black.

### Steps to reproduce

Open visual script.

### Minimal reproduction project

[auto_arrange.zip](https://github.com/godotengine/godot/files/7027863/auto_arrange.zip)

**Comment by fire** [comment]
Do you think it's related your changes? https://github.com/godotengine/godot/pull/51952 @Jummit Not dug into the issue yet.

**Comment by Jummit** [comment]
> Do you think it's related your changes? #51952 @Jummit Not dug into the issue yet.

Seeing that the color change when zooming in and out, I think my patch is causing the problem.
