### ISSUE TITLE
Array not iterating index 1 [3.3.3 issue]

### ISSUE THREAD

**Issue by Mkneeshaw** [godotengine/godot#51994]
### Godot version

 v3.3.3.stable.official.b973f997f

### System information

Windows OpenGL ES 3.0 Renderer: GeForce GTX 1080/PCIe/SSE2

### Issue description

I am looping a small array for Vector2, max is 7.
the loop always skips the second Vector2.
This worked in 3.3.2 and broke on upgrade to 3.3.3.
Occupied_cells is a dictionary for a string key pairs to an array of Vector2s

Below is the GDScript for the 
![unknown](https://user-images.githubusercontent.com/16686828/130368636-5032228d-c660-46fa-8ffa-bc4bbbf7003c.png)

Below is the Output
(13,15) is completely skipped?
![unknown1](https://user-images.githubusercontent.com/16686828/130368687-b17bf75f-6afd-4fe4-b0fa-228f5171b085.png)

### Steps to reproduce

Open attached file and run. Error is reproduceable on minimal example attached

### Minimal reproduction project

[array_test.zip](https://github.com/godotengine/godot/files/7028092/array_test.zip)

**Comment by Calinou** [comment]
If you can compile the engine from source, you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to speed up troubleshooting.

**Comment by qarmin** [comment]
This code is invalid

Deleting objects from collection when iterating over them is undefined behavior in C++ and others languages.
To fix this, variable needs to be cloned before
```
	var temp_cells = cells[0].duplicate(true)
	for cell in temp_cells:
```

When running this project, output properly shows (13,15) point
```
cells[0]:[(12, 15), (13, 15), (12, 14), (11, 14), (11, 15), (12, 16)]
cell:(12, 15)
erasing (12, 15)Ally: TrueStorm: False
cell:(13, 15)
adding(13, 15)
cell:(12, 14)
adding(12, 14)
cell:(11, 14)
adding(11, 14)
cell:(11, 15)
adding(11, 15)
cell:(12, 16)
adding(12, 16)
```

**Comment by Mkneeshaw** [comment]
Thank you! Sorry still learning
