### ISSUE TITLE
[4.0] GDScript syntax autocomplete is broken

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#51996]
### Godot version

v4.0.dev.custom_build [e63f7dcf0]

### System information

Win 10 / 1080 Ti

### Issue description

#51970 broke both syntax highlight and code autocomplete
2a5c64f and earlier commits are fine

https://user-images.githubusercontent.com/2698825/130371134-04739554-0d20-4a93-ac62-3c130db6c5a7.mp4

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by sairam4123** [comment]
Can confirm in [`b4cea1077`](https://github.com/godotengine/godot/commit/b4cea107712b12ca6874fca189eef89cd37b30d7).

**Comment by Xartorx** [comment]
Halfway there! 👍 Highlighting is fixed, but autocomplete is still broken: 

https://user-images.githubusercontent.com/2698825/130487393-fb4a9ea7-e586-4937-b164-76d31e475d2b.mp4

**Comment by KoBeWi** [comment]
Wasn't it like that before? I recall the autocompletion being very unreliable on master.

**Comment by gamergamesz** [comment]
it still does not work for me in the recent pre-alpha 2, win10

**Comment by KoBeWi** [comment]
I noticed that you need to press Ctrl + Space, otherwise autocompletion doesn't appear.

**Comment by gamergamesz** [comment]
nope not for me, actually I don't see the list appearing at all

> I noticed that you need to press Ctrl + Space, otherwise autocompletion doesn't appear.
