### ISSUE TITLE
3D Animations doesn't play

### ISSUE THREAD

**Issue by requizm** [godotengine/godot#51990]
### Godot version

4.0 dev 2daef0400

### System information

Windows 10

### Issue description

The error happens on this line:
`quaternion.cpp:107 The start quaternion must be normalized.`

### Steps to reproduce

1. Import some 3d model with animation
1. Add to the scene
1. Open Animation Player in model node
1. Click "play selected animation from start" or "play selected animation from current pos"

### Minimal reproduction project

No need

**Comment by requizm** [comment]
May related to #51785

**Comment by nonunknown** [comment]
still reproduceable in: v4.0.dev.20210916.official [104a619]


Uploading 2021-09-18 08-41-12.mp4…
