### ISSUE TITLE
Can't set 'import as' flag for multiple .csv files to 'KeepFile (no import)'.

### ISSUE THREAD

**Issue by JoanPotatoes2021** [godotengine/godot#52037]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GLES3

### Issue description

When selecting 1 csv file it appears as expected:
![1](https://user-images.githubusercontent.com/88800565/130501293-f18993a8-4acf-45b3-8de5-b31738e9ec0d.png)
But when selecting more than 1 csv file the option keep file (no import) dissapears:
![2](https://user-images.githubusercontent.com/88800565/130501385-13b14219-9226-4063-9ee4-dfdee56f02d7.png)
In theory it's possible to re-import each .csv file separated, however being in a big project, re-opening the project with a lot of .csv files isn't a option.

### Steps to reproduce

Place two .csv files in a project, select the two files in the editor, go to import tab, the option doesn't show up to reimport them as keep file;

**Comment by Calinou** [comment]
As a workaround, you can *replace* the content of all `.csv.import` files with the following:

```
[remap]

importer="keep"
```
