### ISSUE TITLE
[GDScript 2.0] [regression] Godot hangs while parsing complex `match` expression

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#52032]
### Godot version

master #fb176d5f6e6dc2b43c630a041a8ab7d737173ec4

### System information

manjaro linux

### Issue description

following script:
```
var y
func foo(x):
	match x:
		1 + 1:
			pass
		[1,2,[1,{1:2,2:var z,..,}]]:
			pass
		1 if true else 2:
			pass
		1 or 2 and 1:
			pass
		1 < 2:
			pass
		1 | 1:
			pass
		1 >> 1:
			pass
		1, 2 or 3, 4:
			pass
		_:
			pass
```

causes Godot hanging, while it was working fine in Godot `3.x`

### Steps to reproduce

compile

**Comment by KoBeWi** [comment]
Sounds related to #50865
