### ISSUE TITLE
GDScript 2.0: Cannot parse `match` with `typeof()` (Expression in match pattern must be a constant)

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#52033]
### Godot version

master #fb176d5f6e6dc2b43c630a041a8ab7d737173ec4

### System information

manjaro linux

### Issue description

following script:
```
func baz(x):
	match typeof(x):
		TYPE_REAL:
			print("float")
		TYPE_STRING:
			print("text")
		TYPE_ARRAY:
			print("array")
```
yields:
```
SCRIPT ERROR: Parse Error: Identifier "TYPE_REAL" not declared in the current scope.
          at: GDScript::reload (res://tests/potential-godot-bugs/match-w-types.gd:3)
SCRIPT ERROR: Parse Error: Expression in match pattern must be a constant.
          at: GDScript::reload (res://tests/potential-godot-bugs/match-w-types.gd:3)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:840)
```
while it was working in Godot `3.x`

### Steps to reproduce

compile

**Comment by qarmin** [comment]
Enums were renamed - https://github.com/qarmin/godot/blob/5e1d6e2679dafa69b6df25839365901bedc04aea/editor/converter.cpp#L49, so that is why this script doesn't work

**Comment by qarmin** [comment]
Looks that

**Comment by anvilfolk** [comment]
I just tested this and it's working. Not sure why it was reopened a while back. Recommend closing it :) @Calinou since you were the last one to do some edits here.
