### ISSUE TITLE
[master] `ArrayMesh.surface_remove()` method missing.

### ISSUE THREAD

**Issue by JestemStefan** [godotengine/godot#52054]
### Godot version

v4.0.dev.20210820.official [75697c0df]

### System information

Windows 10

### Issue description

`ArrayMesh.surface_remove(idx)` method went missing in master.

I'm working on procedurally generated planets based on Sebastian Lague tutorial. Everything works fine in 3.3 version, but it's pretty slow so I decided to switch to 4.0, because `map()` method and faster GDscript will help improve performance, BUT

There is no `ArrayMesh.surface_remove(idx)` method anymore in master so new surfaces are stack on top of each other and I can't find a way to remove them.

Is it a mistake or this method was moved somewhere else?

![image](https://user-images.githubusercontent.com/37214990/130588948-bee1a6e8-73a1-43de-a33a-18f4a379b3a0.png)

3.3
https://github.com/godotengine/godot/blob/9d0e0fe783f05b7ea504f0d233afc7441a74c535/scene/resources/mesh.cpp

master
https://github.com/godotengine/godot/blob/e95fa21b455a5e2c512fe6e054f86df1f01e5bd3/scene/resources/mesh.cpp

### Steps to reproduce

```
var arr_mesh: ArrayMesh = ArrayMesh.new()
arr_mesh.surface_remove(0)  <--- method doesn't exist
```

**Comment by Calinou** [comment]
> because map() method and faster GDscript will help improve performance

If your program is an order of magnitude too slow, faster GDScript will most likely not close this gap. You will have to look into using threads, C#, GDNative or a C++ module instead.

**Comment by JestemStefan** [comment]
> 
> 
> > because `map()` method and faster GDscript will help improve performance
> 
> If your program is an order of magnitude too slow, faster GDScript in 4.0 will most likely not close this gap. There's only so much that can be done in an interpreted language 🙂
> 
> You will have to look into using [threads](https://docs.godotengine.org/en/stable/tutorials/threads/using_multiple_threads.html), C#, [GDNative](https://docs.godotengine.org/en/latest/tutorials/scripting/gdnative/gdnative_cpp_example.html) or a [statically compiled C++ module](https://docs.godotengine.org/en/stable/development/cpp/custom_modules_in_cpp.html) instead.

Thank you for reply 😄 I considered using GDNative if master version was still too slow and I will definitely look into it. 

Still the issue is that this one method is missing and I couldn't find any replacement for it in mesh.cpp.

This is more of a question if this is intended or a mistake

**Comment by JestemStefan** [comment]
Found it. It got removed in https://github.com/godotengine/godot/commit/449df8f688080c02bfbbfafc45421875b77deb1b#diff-e84616c8a1b4f2029ec6cc009fb3ed17f43d699e1f9125d8023c5ce9b65e66a8
