### ISSUE TITLE
Visible Collision Shapes (Debug) for Raycast node stucks on red color after first hit

### ISSUE THREAD

**Issue by starcin** [godotengine/godot#52051]
### Godot version

3.4.beta4.official [6a058cbf3]

### System information

Windows 10, GLES3

### Issue description

In 3.4.beta4.official [6a058cbf3], if "Visible Collision Shapes" setting is enabled, a raycast object is rendered as a blueish narrow pyramid.

In 3.3.2 stable, the same object is rendered as a orange line:

![v3 4 beta4_before_hit](https://user-images.githubusercontent.com/62737425/130571051-1cdfb65f-7d80-4a98-bba5-f106ab43ab29.png)
![v3 3 2 stable_before_hit](https://user-images.githubusercontent.com/62737425/130571087-73014422-e051-44d6-a258-4a474808b218.png)

During the raycast detects a hit, they both render the shape red:

![v3 4 beta4_during_hit](https://user-images.githubusercontent.com/62737425/130571152-dc0059e0-f92c-461c-bfb8-af6af0c65afc.png)
![v3 3 2 stable_during_hit](https://user-images.githubusercontent.com/62737425/130571165-2a051199-2b2e-4265-b514-4108f20ed05f.png)

But after the collision (when there is no hit anymore), the v3.4 one stays red:
![v3 4 beta4_after_hit](https://user-images.githubusercontent.com/62737425/130571344-77af93fc-927b-4a40-9528-0c59a62329a0.png)
![v3 3 2 stable_after_hit](https://user-images.githubusercontent.com/62737425/130571359-99c82795-c52c-4125-9ead-16b52e67fd7d.png)

### Steps to reproduce

You just need to collide a raycast with something.

This is the whole moving object in my scene:
![resim](https://user-images.githubusercontent.com/62737425/130571485-5cd4646a-082c-430c-aaa4-0797698c800b.png)

The script only contains simple impulse force funcitons to be able to move it with arrow keys.

And this is the whole scene:
![resim](https://user-images.githubusercontent.com/62737425/130571697-b73332cc-9694-40e1-aab4-073edd99fb26.png)

### Minimal reproduction project

Here is the project. 
[SampleRaycastBug.zip](https://github.com/godotengine/godot/files/7037093/SampleRaycastBug.zip)

Sorry I couldn't delete a plug-in. Even it is not enabled, Godot file system doesn't let me delete it and if I delete it in Windows File Explorer, I can't open the project because Godot crushes during opening the project.

**Comment by Calinou** [comment]
This is likely a regression from https://github.com/godotengine/godot/pull/49726.

@fabriceci Do you know what could be causing this?

**Comment by pouleyKetchoupp** [comment]
Closed by #52056 on 3.x (issue already fixed on master).
