### ISSUE TITLE
Node not found: BoneAttachment

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#5205]
**Operating system or device - Godot version:**
Ubuntu 16.04, Godot 2.0.3

**Issue description** (what happened, and what was expected):
Error: Node not found: BoneAttachment

**Steps to reproduce:**
Add BoneAttachment. Start game.

**Link to minimal example project** (optional but very welcome):
![2016-06-14 13-24-48](https://cloud.githubusercontent.com/assets/11325733/16033245/8d1419f2-323d-11e6-870a-8b09805e875a.png)
[Bone attach.zip](https://github.com/godotengine/godot/files/313280/Bone.attach.zip)

**Comment by J08nY** [comment]
Hmm, did a bit of checking, it probably happens because the child `BoneAttachment` is not in tree when the properties are being applied to the skeleton. Dunno what to do about it yet.

**Comment by bojidar-bg** [comment]
@J08nY Probably wait for `NOTIFICATION_READY`, or have the BoneAttachment register itself at runtime?
