### ISSUE TITLE
Script list is broken

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#52069]
### Godot version

ca7f53d

### System information

W10

### Issue description

![image](https://user-images.githubusercontent.com/2223172/130656899-1624f05f-db52-40c5-95e9-8d2fa7f3d502.png)
Seems like visual script and gdscript lists are merged into one.

### Steps to reproduce

1. Open script editor

EDIT:
I tried on a different machine and it doesn't seem to happen. I reproduced it once after creating VisualScript, but after restart it's gone again. Seems to be random, idk. The first PC I tried had 4k screen, the second is Full HD. Maybe it's related.

**Comment by Gallilus** [comment]
This is fixed?

**Comment by akien-mga** [comment]
Is this still reproducible?

**Comment by KoBeWi** [comment]
I don't see it anymore, but it was random. I'll reopen if it happens again.
