### ISSUE TITLE
C# file doesn't work after being edited

### ISSUE THREAD

**Issue by nguyenphuminh** [godotengine/godot#52062]
### Godot version

3.3.3 stable, mono

### System information

Windows 10

### Issue description

Me and my friend are creating a game together, he uses C#, I use GDScript (we both use the same Godot (v3.3.3 stable mono)), and somehow every time I tried editing the C# file, it didn't change anything, but GDScript still work fine. However, both languages work fine with my friend's.

 (and I've properly saved them.)

### Steps to reproduce

I don't really know how to reproduce this bug, seems like it only break on my computer :/ But every time I make changes to any C# files, it would just stay the same.

### Minimal reproduction project

For many reasons with my team, I can't post the code here, but I can provide any infos/examples if needed!

If the code is seriously needed, I'll share it

**Comment by Flyboy1010** [comment]
Have click build in the editor after saving the file?
![a](https://user-images.githubusercontent.com/59151174/130612092-ae5c1f89-9af9-4687-98c1-64a62c8976c4.png)

**Comment by nguyenphuminh** [comment]
The build button disappeared in my editor.

**Comment by Flyboy1010** [comment]
Try building a c# solution first

![image](https://user-images.githubusercontent.com/59151174/130646733-bfd1a7b3-0461-4859-9d99-e607f358988c.png)

![image](https://user-images.githubusercontent.com/59151174/130646837-f0b50360-4c20-480d-b36a-d124e636add4.png)

**Comment by nguyenphuminh** [comment]
I don't have that MSBuild as well.

**Comment by Flyboy1010** [comment]
are you using the mono version of godot ?

**Comment by nguyenphuminh** [comment]
yup, I’m using mono

**Comment by Flyboy1010** [comment]
and you have installed MSBuild (from Visual Studio Build Tools or the Mono SDK) ? if yes then i have no idea, maybe try to download the editor again

**Comment by nguyenphuminh** [comment]
Thanks, after re-installing some .NET SDK and VS Build Tools, as well as changing the build system, the problem is fixed.
