### ISSUE TITLE
Adding multi dimension support to HTTPClient.query_string_from_dict()

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot#5206]
**Operating system or device - Godot version:**
Using : Godot_v2.0.3_stable_x11.64 on linuxmint 17.2

**Issue description** (what happened, and what was expected):
I have a query parameters array like

```
var query = {
    'firm': 1
    , 'type': 2
    , 'duedate' : {
    'start':01-01-1970
    , 'end':14-06-2016
    }
}
```

I expect it to be encoded like

```
?duedate[end]=14-06-2016&duedate[start]=01-01-1970&firm=1&type=2
```

But output is like below

```
?duedate=%28end%3A02-06-2016%29%2C%20%28start%3A01-01-1970%29&firm=1&type=2
```

It seem as if dictionaries are treated as one dimesional structures by HTTPClient so multi dimensional encoding support is needed.

**Comment by vnen** [comment]
BTW, while this brackets notation is adopted by many systems, there's no standard way to send arrays/dictionaries via querystring. Currently you can use `var2str()` to make the dictionary text-friendly (it'll be in a JSON-like format).

**Comment by hubbyist** [comment]
@vnen I see. 

May be a single value url encoding function supplied to aid coding of recursive functions to handle this edge case. eg: value_to_query_string(String string)

**Comment by hubbyist** [comment]
Closing as there is no official standard on the subject.
