### ISSUE TITLE
Impossible to save not-yet-saved scene after renaming folder 

### ISSUE THREAD

**Issue by mrkdji** [godotengine/godot#52078]
### Godot version

3.3.3.stable 3.3.2stable

### System information

Windows 10

### Issue description

**Issue**
It's impossible to save a newly created scene if one renames the containing folder.

**Expected behaviour**
A) Show a filesystem popup to choose a different save location for the scene;
B) Save the scene inside the root folder;

### Steps to reproduce

1. Create a folder in Godot Editor's filesystem tab;
2. Create a scene inside that folder ( do not save the scene );
3. Rename the folder;
4. Try to save the scene;

**Comment by e8newallm** [comment]
Reproducing this bug gives the error:

`ERROR: Cannot save file 'res://test foldert/test scene.tscn'.
   at: save (scene/resources/resource_format_text.cpp:1600)
ERROR: Transient parent has another exclusive child.
   at: set_visible (scene/main/window.cpp:408)
`

and a popup saying "Error while saving."

This occurs with both "Save Scene" and "Save All Scenes" however "Save Scene As..." opens up at the root directory when the folder is not found.

Going to pick this up and see if I can replicate the "Save Scene As..." handling to the other two.
