### ISSUE TITLE
OS X retina hdpi fullscreen glitches

### ISSUE THREAD

**Issue by ComancheAk** [godotengine/godot#5209]
**Operating system or device - Godot version:**
OS X 10.11 El Captain - v2.1.alpha.custom_build

**Issue description** (what happened, and what was expected):
With allow_hdpi settings project in fullscreen mode causes glitches.
 [Screenshot](http://cs630225.vk.me/v630225154/359df/jSzcFC_Jqg0.jpg)
[Window Mode](http://cs630225.vk.me/v630225154/359e9/wQDnPIprJh0.jpg)

**Steps to reproduce:**
Simply set allow_hdpi and fullscreen enabled with portrait resolution. (640x1136)

**Comment by akien-mga** [comment]
Can someone reproduce this issue on OSX, and/or on another OS?

**Comment by reduz** [comment]
Testing in OSX with retina and I can't reproduce it. Maybe it was fixed by something else?

**Comment by reduz** [comment]
I'm even using the same OSX version..

**Comment by akien-mga** [comment]
Moving to the next milestone as we haven't had any user confirming this issue so far, so it should not be blocking for 2.1.

**Comment by bojidar-bg** [comment]
Any status here? It seems like we need more testers for this one :smiley:

**Comment by akien-mga** [comment]
Assuming fixed as there have been many improvements to macOS hidpi support, and no new confirmation of this specific bug either.
