### ISSUE TITLE
Can't make TextEdit scrollbars invisible by setting the internal ScrollBar nodes' visibility to `false`

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#52091]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GTS450

### Issue description

Tried to toggle visibility flag of both scrollbars within TextEdit-node. Scrollbars are visible with toggled flags.
```gdscript
extends TextEdit


func _ready():
	for child in get_children():
		if child is ScrollBar:
			child.visible = false

```
Also you can try toggle in **_process(delta)** callback, but, you can notice scrollbar **blinking while dragging caret by mouse**. Assuming that scrollbars flags are toggled to true by engine dynamically.

### Steps to reproduce

1. run attachment

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/7044407/New.Game.Project.zip)

**Comment by KoBeWi** [comment]
This is kind of expected. The scrollbars are internal and you are not supposed to access them (even if you technically can). For proper hiding of scrollbars we'd need to expose a way to do so, which means it's a missing feature.

**Comment by boruok** [comment]
@KoBeWi yeah, i thought about it, should that somehow documented?

**Comment by KoBeWi** [comment]
The workaround I mentioned is rather hacky and we shouldn't include such hacks in the documentation. Judging from low activity, this is not a very common issue, so it should be fine to close it.
