### ISSUE TITLE
Cube map importer

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#521]
We need cube maps importer :)

PS
Note for users.
If you want to add cube map, current Cube Map Resource is broken, just move your 6 textures to project and add text file with .cube extension, place in it names of your textures separated with Return (Enter). See 3D platformer demo for more.

**Comment by akien-mga** [comment]
Is this still relevant or what it solved by the fixing of #908?

**Comment by akien-mga** [comment]
No answer, assuming this is no longer reproducible or we'd hear about it. Please comment if you still experience this bug.

**Comment by ericvoid** [comment]
Hi, I'm facing this issue on 2.1.2 stable, Win 10.

OP's workaround works as a charm. Just to complement his instructions, after you have all the images and the `.cube` file in place, open to the Environment properties, click on Cubemap property (on arrow pointing down) then click on *Load* and select your `.cube` file.

**Comment by n-pigeon** [comment]
I think there is still no cube map mporter I think. Sorry for delay, I've missed the message :B

**Comment by n-pigeon** [comment]
@akien-mga 
I think there is still no cube map mporter I think. Sorry for delay, I've missed the message :B

**Comment by ericvoid** [comment]
It seems that the bug is related to the file types and/or their contents. I have a starscape texture that works just fine with with CubeMap Resource UI (same image for all sides), and a skybox created on Blender (one image for each side) that only works with the `.cube` format. Do you want these files?

**Comment by n-pigeon** [comment]
@ericvoid 
This bug is more about tool that would import images and prepare cubemap for you.
It is very old, and had little priority. Cubemaps workflow should be revised for 3.0 that aims to be 3D ready.
