### ISSUE TITLE
Self-reflection is visible in metallic materials with VoxelGI due to bias being too low

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#52114]
### Godot version

v4.0.dev.calinou [b4cea1077]

### System information

Mx Linux (Debian Based)

### Issue description

When baking VoxelGI  in a metalic sphere there is self reflect

![image](https://user-images.githubusercontent.com/1168582/130884549-317faecf-84a9-40a2-a1b9-1db14677307a.png)

### Steps to reproduce

Use the main.tscn in the Minimal reproduction project

### Minimal reproduction project

[Voxel.zip](https://github.com/godotengine/godot/files/7050807/Voxel.zip)

**Comment by Calinou** [comment]
If avoiding self-reflections entirely is your priority, I've found that using a Bias of 0 and Normal Bias of 1.75 works decently:

https://github.com/godotengine/godot/issues/52115#issuecomment-979504238

It will result in flatter-looking indirect lighting in some areas, but it's not something that can be prevented without the use of expensive anisotropy.
