### ISSUE TITLE
Game crashes when changing audio output (to bluetooth speakers)

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#5211]
**Operating system or device - Godot version:**
Android 6.0.1, 6.0.0, 5.1.1, 5.0.2 - Godot 2.0.3

**Issue description**:
Godot crashes when I'm starting the app with my phone speakers as audio output, and then connect the phone to Bluetooth speakers while playing.

**Steps to reproduce:**
Run a Godot game and connect to bluetooth speakers.

**Comment by akien-mga** [comment]
Related to #1684.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone (though for the stable branch would be very welcome).

**Comment by bojidar-bg** [comment]
Most likely fixed in 2.1.3 as mentioned by @timoschwarzer on #7272. Might reopen if still present.
