### ISSUE TITLE
Add ODBC support

### ISSUE THREAD

**Issue by silverkorn** [godotengine/godot#5213]
Greetings,

In many context, specially those with a lot of information to store such as user information, progress, logins & scoreboards, databases are fundamental to those applications/games.

Unfortunately, there's no support for larger scaled databases in Godot and the current format is extremely limited.

This is why I suggest the implementation of ODBC with, as suggestion, [nanodbc](http://lexicalunit.github.io/nanodbc/). 
It is MIT licensed, light and cross-platform.

Why do I suggested ODBC over any other specific method/protocol? 
Simply because it's supported by most of database softwares (e.g.: Microsoft SQL, MySQL, PostgreSQL, SQLite, etc.) with a generic syntax and it's platform independent.

Let me know your thoughts about it.
Thanks! :smile:

**Comment by vnen** [comment]
I think this is better as a separate module.

**Comment by silverkorn** [comment]
I can understand this point of view.

The request was more to have a ready to run server/client with a scalable data management service without the need to change the queries. (SQLite for local or light management and scalable to MySQL for larger data manipulation)

I'll let other people give their opinion about this. 
I'm just afraid that by doing it as a separate module, it won't be done at all, which seems to happen too frequently... :confused:

**Comment by Zylann** [comment]
The only reason why we are likely to want all things in core is because Godot currently lacks easy plug-and-play of native functionality. If module development evolves further than recompiling the whole engine binary (which is seriously considered here https://github.com/godotengine/godot/issues/3936#issuecomment-224849590), that could be no problem at all. I prefer a clean core than a bloated core :)

**Comment by silverkorn** [comment]
Understandable!
Should I migrate this issue to the [godotengine/godot-modules](https://github.com/godotengine/godot-modules) repository?
Maybe we should also put your module list in this place?

**Comment by TheoXD** [comment]
I'm all for it, having database support out of the box wouldn't hurt, if it's lightweight, cross-platform and can connect to all databases. I see godot-modules being there only for stuff that can't ship alongside godot because of license restrictions or if they do not work properly (in case of theora)

**Comment by silverkorn** [comment]
@TheoXD, that's indeed why I suggested it directly into Godot, just like other libraries such as `Node regex` and others tiny "drivers".

**Comment by SuperUserNameMan** [comment]
if it's really lightweight, I wouldn't mind it to be integrated into the core.
else, it could become a module that i might need.

**Comment by vnen** [comment]
This can be added as a module even if it's in Godot's core (such as GDScript, GridMap an IK).

**Comment by SuperUserNameMan** [comment]
Oh, i think that I used a wrong word. What I mean by "module" is more like "optional plugin".

Personally, I'd rather not to have to compile godot to add or remove modules.
I'd prefer an out of the box slim godot with optional .dll or .so.

**Comment by silverkorn** [comment]
Although some would prefer it in an all-in-one executable (like I personally do).

Still, I had migrated this issue to the [godotengine/godot-modules](https://github.com/godotengine/godot-modules) repository. 
(https://github.com/godotengine/godot-modules/issues/4)

Thanks for the interest!

**Comment by jhall39** [comment]
I'm sorry to ask on an old closed issue but the godot-modules repository seems to be gone these days. What ever happened with this feature request over there?

**Comment by Calinou** [comment]
> I'm sorry to ask on an old closed issue but the godot-modules repository seems to be gone these days. What ever happened with this feature request over there?

Feature proposals are now tracked on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.

**Comment by Angemell** [comment]
Greetings to anyone comming here:

We've reopened this discussion in the following thread: https://github.com/godotengine/godot-proposals/discussions/4609
