### ISSUE TITLE
Enable zoom with mousewheel in the visual shader editor

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#5214]
When dealing with anything beyond a basic shader graph, it becomes very important to zoom in and out regularly, as things tend to get quite big.

Being able to do it with the mousewheel is way faster than having to click those zoom buttons on the left corner.

I found that relevant code for this was already done but commented out with a note "hard to get it right". I enabled it back and tried it out and found out its working as expected.

Would it be ok to get this back or is there any problem I've not been able to see?

**Comment by ZX-WT** [comment]
zooming with mouse wheel and panning with middle mouse button makes more sense.

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/29091 supported in this pr.

**Comment by Chaosus** [comment]
Closed to prefer: https://github.com/godotengine/godot/issues/41538 (for GraphEdit instead only VisualShader)
