### ISSUE TITLE
gdscript print() ignores '\n'

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#52148]
### Godot version

v4.0.dev.custom_build [c5f62fad9]

### System information

Windows 11, Vulkan Clustered

### Issue description

```gdscript
print('1')
print('\n')
print('2')
print(' ')
print('3')
```
Output:
```
1
2
 
3
```

### Steps to reproduce

Just use `print('\n')` in gdscript.

**Comment by floppyhammer** [comment]
Yes it does, but '\r' alone would do the job.
```gdscript
print('1')
print('\r')
print('2')
print('\r\n')
print('3')
```
```
1

2

3
```

**Comment by Ev1lbl0w** [comment]
I just tested on 3.x and it shows the correct behavior:
```gdscript
1


2
 
3
```
So this is likely a regression

**Comment by Calinou** [comment]
Are you looking at the command prompt or editor Output panel? These likely treat line breaks differently.

If this only happens in the editor Output panel, this may be a regression from the Output panel improvements PR that added message merging.

**Comment by Ev1lbl0w** [comment]
I've only looked through the Output panel, forgot about the terminal output, but I'll take a look as well :+1:

**Comment by Ev1lbl0w** [comment]
@Calinou the terminal output is correct, it's indeed from the output logging panel changes.

It's a dead simple fix, but I'll ping the author to make sure it's not too naive :slightly_smiling_face:
