### ISSUE TITLE
Crash when opening scene with a tool script and incorrect node type

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#52155]
### Godot version

00268e37a0e40630ce76b5144cb272c4cc73a672

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

If you open a scene with a node (seems to be the root node, haven't tested it on child nodes yet) assigned a tool script inheriting from an invalid node type, the function _update_script_class_properties will get called but fail to assign values to script_variables, bottom, and insert, resulting in a NULL pointer error at the end of the function.

I'm not sure if there may be a deeper problem at play here, but I've already posted a quick fix for this here ().

### Steps to reproduce

Load the sample project file and open bug.tscn

### Minimal reproduction project

[missing_script_variables.zip](https://github.com/godotengine/godot/files/7067250/missing_script_variables.zip)

**Comment by SaracenOne** [comment]
Since the PR for this has been merged now, I guess I can close this

**Comment by akien-mga** [comment]
> Since the PR for this has been merged now, I guess I can close this

FYI, if you use closing keywords in the PR/commit description, this would happen automatically when merged: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
