### ISSUE TITLE
Wrong behavior of Action Editor with AZERTY keyboard

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#52169]
### Godot version

v4.0.dev.custom_build [8e3e9d121]

### System information

Windows 10, Physical AZERTY Keyboard

### Issue description

Something is really weird with key definition in Project Settings > Action Editor.

### Preamble

As far as I understand, there are two ways to define a key for an action : 
- default : if I press Q key, I want the action to be triggered by a Q key on all keyboard layouts.
- physical keycode : if I press Q key, I want the action to  triggered by a key at this position on all keyboard layouts (maybe it won't be an Q on other layouts but it will be the key at this position)

On my keyboard, either with default or physical keycode, it should always be my Q key that should trigger the action (because on my keyboard my Q key as a value of 'Q' and the position of physical key "Q" in my layout)

### Bug description

Let's set an action named "left". Often used key for left action is Q on an AZERTY keyboard (corresponding to the position of A on QWERTY).

I don't check "Use Physical Keycode" (so on all layouts, it should be triggered by the Q key wherever it is)
![image](https://user-images.githubusercontent.com/3649998/131187747-1ee0ec11-acb5-4ac6-9913-e895deca2a93.png)
I press Q key the letter A is shown in the windows (so it shows the QWERTY equivalent value).
Showing the QWERTY equivalent here is misleading. We don't care of that here. We always want an Q key even on QWERTY.

Then I start the project and another problem comes :
The key that I have to press to trigger the action is... A ! (not Q)
I have to press a key that I didn't press when assigning key to action.

Maybe, rather than showing misleading QWERTY keys, it should print : 
"value of Q" (by default) or "position of Q" (if «use physical» is checked) 
and in game action should never be triggered by a key that we never pressed (on the same keyboard of course).

### Steps to reproduce

On an AZERTY keyboard, setup an action and assign the key Q without checking "use physical keycode".
You will have to press A during game.

### Minimal reproduction project

[inputs.zip](https://github.com/godotengine/godot/files/7069476/inputs.zip)

In this project, Q key on AZERTY keyboard as been pressed for assigning it to "left" action.

You can see that it's the A key of AZERTY keyboard that trigger the action at runtime.

**Comment by Calinou** [comment]
I can confirm this on https://github.com/godotengine/godot/commit/dcf2d09231c03c444cf5374b4d250f327f1333e4 on Linux (Fedora 34, fr-oss keyboard layout).
