### ISSUE TITLE
Floats in GD Extension aren't working properly.

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#52178]
### Godot version

4.0.dev d04aa9a114811e27c672e9874c262e91299216f0

### System information

Any

### Issue description

Calling back into Godot from a GD Extension plugin doesn't work when float parameters are used. Doubles work fine.

### Steps to reproduce

Create a GD extension plugin that uses an object within Godot that either has float parameters or returns a float. It will either send or return an incorrect value.

For instance, in my XR plugin I have the following code:
```
XRServer *xr_server = XRServer::get_singleton();
float world_scale = xr_server->get_world_scale();
```

This should set `world_scale` to `1.0` but it gets the value `0.0`

> Note that I've since changed this function to return a double.

**Comment by akien-mga** [comment]
I believe this was fixed a long time ago.
