### ISSUE TITLE
`GraphNode` can connect one of its right side sequence ports to its own left side sequence port

### ISSUE THREAD

**Issue by MagdielM** [godotengine/godot#52196]
### Godot version

v3.3.3 stable (Mono build)

### System information

Windows 10

### Issue description

`GraphNode`s with sequence ports on both sides can connect any of their right side sequence ports to their left side sequence port, effectively allowing them to call themselves infinitely.
![image](https://user-images.githubusercontent.com/56076033/131226971-f56756ee-9bf8-4bcf-90b1-6344162851ea.png)

Naturally this immediately overflows the stack as soon as a scene with a node with this script attached is run.
![image](https://user-images.githubusercontent.com/56076033/131226856-f498e7dd-8101-41cc-aff0-458bd04ef51f.png)

I am unsure that this is intended behavior, but I'm choosing to report it as a bug rather than a proposal to change it because I can't think of any situation where this wouldn't simply cause problems.

### Steps to reproduce

In an empty project:

1. Create a `VisualScript` resource.
2. Attempt to connect the right side sequence port of a `GraphNode` with pins on both sides to its own left side sequence port.

From the reproduction project:

1. Note how the Type Cast `GraphNode`'s "yes" and "no" sequence ports connect to its own "Is Object?" sequence port.

### Minimal reproduction project

[GraphEditNodeConnectingToItselfTest.zip](https://github.com/godotengine/godot/files/7071213/GraphEditNodeConnectingToItselfTest.zip)

**Comment by kleonc** [comment]
Already fixed in #50413/#51208.

**Comment by KoBeWi** [comment]
Closing as per above comment.
