### ISSUE TITLE
RichTextLabel's characters visibility properties are broken

### ISSUE THREAD

**Issue by LATRio** [godotengine/godot#52209]
### Godot version

v4.0.dev.custom_build [4d08a737f]

### System information

Windows 10, 64 bit

### Issue description

"visible_character" doesn't do anything.
"percent_visible" scroll doens't work as expected. Only work as expected when reaches value 1. At 0 might show some characters.

### Steps to reproduce

Input long enough text.
Change values of properties "visible_character" and "percent_visible".

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/49189.
