### ISSUE TITLE
Text boxes in inspector revert to previous value when text is pasted Ctrl+V

### ISSUE THREAD

**Issue by LATRio** [godotengine/godot#52208]
### Godot version

v4.0.dev.custom_build [4d08a737f]

### System information

Windows 10, 64 bit

### Issue description

All text inputs in inspector immediately changes to "null" (or whatever previous text was) if you paste text into them (length doesn't matter).  Tested with nodes: Label, RichTextLabel, Button, Node.
Text input in ColorPickerButton seems to work just fine.
Only reproducable in master.

### Steps to reproduce

Copy any text and paste it into any text input in inspector. "editor_description", for example.
Ctrl+Z seems to return correct value before it was replaced with previous value.

**Comment by jmb462** [comment]
I've identified the cause.

It's a regression from 0205fffbf3ebf03cf974802f07368a5d18326893 (Copy/Paste property paths/values in inspector.)

When pressing CTRL+V in inspector textedit, the event is managed 2 times : 

- first by TextEdit in ``TextEdit::gui_input(const Ref<InputEvent> &p_gui_input)``
It pastes the text in the textedit (that what's we want here)

- then, by EditorProperty::unhandled_key_input(const Ref<InputEvent> &p_event)``
It paste the editor property. Null if no editor property was copy before.

When TextEdit deal with the event, it use accept_event() to set it as handled.
So I don't understand why the event continues to propagate to unhandled_key_input in EditorProperty.
