### ISSUE TITLE
Godot 4 editor not started with gpu (intel hd 2000) that not supports vulcan api

### ISSUE THREAD

**Issue by XDRiVE888** [godotengine/godot#52216]
### Godot version

4.0 dev (75697c0df)

### System information

Windows 10, Intel HD Graphics 2000 (9.17.10,4459)

### Issue description

Godot 4.0 editor not started with graphics card Intel HD Graphics 2000 because this card not supports
![godot4_screenshot1](https://user-images.githubusercontent.com/33435887/131251559-3ca8f9f4-4989-44c9-980b-19ea9dc2c7b3.png)
![godot4_screenshot2](https://user-images.githubusercontent.com/33435887/131251565-248e4d98-ad3e-4a12-91d7-04225d72fc30.png)
 vulcan api.

### Steps to reproduce

Try open godot 4.0 editor with gpu like intel hd 2000 that not supports vulcan api.

**Comment by pycbouh** [comment]
Indeed, Godot 4 currently only works on Vulkan-compatible hardware. OpenGL 3 support will come at a later date.

You can read more about our plans in the article [here](https://godotengine.org/article/about-godot4-vulkan-gles3-and-gles2).
