### ISSUE TITLE
StreamPlayer finished() signal triggers on play()

### ISSUE THREAD

**Issue by UltimaN3rd** [godotengine/godot#5222]
**Operating system or device - Godot version:** Ubuntu 16.04 64-bit. Godot 2.0.3 stable

**Issue description** (what happened, and what was expected): Using a StreamPlayer to play a .ogg file. Linked the finished() trigger to a script function but the finished() trigger is sent when the stream is started as well as when it's finished.

**Steps to reproduce:** Add StreamPlayer to project, link finished() signal to function, print something in that function and see that it triggers as soon as the StreamPlayer plays as well as whenever it finishes.

**Comment by akien-mga** [comment]
Interestingly, this issue was noted a few days ago by @TheoXD too. The signal was added in 9ed3d6d00 and occurs each time `stop()` is called, i.e. also via `set_stream()` and `play()`.

**Comment by akien-mga** [comment]
The signal was added to fix #2249.

**Comment by J08nY** [comment]
How about only emitting `"finished"` in `stop()` when the `StreamPlayer.is_playing()` when stop is called? Will that fix the issue sufficiently?

**Comment by akien-mga** [comment]
That sounds like a good solution to me.
