### ISSUE TITLE
android plugin doesn't work in godot (Version>=3.3)

### ISSUE THREAD

**Issue by 2439905184** [godotengine/godot#52249]
### Godot version

3.3.3stable 

### System information

windows10 opengl es 2.0

### Issue description

may be this commit break the code.
#47047
[a merge](https://github.com/godotengine/godot/pull/47047)
My codes is here:[gitee](https://gitee.com/h128/godot-android-plugin-template/tree/3.3/)
![godot3 3 bug android plugin](https://user-images.githubusercontent.com/29478722/131335412-bb2292a2-038c-48eb-90ae-33d4ff627c5c.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/29478722/131335551-18bc6975-6123-4e5d-9dd7-aab7d9f6eebd.png)
![image](https://user-images.githubusercontent.com/29478722/131335573-6b6f8a0d-16f7-460e-a6b7-934f6c27d126.png)
![image](https://user-images.githubusercontent.com/29478722/131335594-a07f5b22-7f45-42a7-a83a-7b48374214b1.png)
![image](https://user-images.githubusercontent.com/29478722/131335623-f42c1fb0-543e-43a3-a0e2-f3d5f66dc627.png)

**Comment by timothyqiu** [comment]
Not sure what's the cause of your issue. But I tried the plugin from your repository, and it works fine for me. Clicking the button in the demo project successfully shows a native Toast.

**Comment by 2439905184** [comment]
use openjdk instead of oracle jdk may solve the promblem

**Comment by neoncube2** [comment]
@2439905184 I'm running into a similar issue, but installing OpenJDK didn't seem to fix the issue for me. Any other ideas on what I should check? 🙂

**Comment by 2439905184** [comment]
> @2439905184 I'm running into a similar issue, but installing OpenJDK didn't seem to fix the issue for me. Any other ideas on what I should check? 🙂

I dont't know other problems.
I confirm my AndroidManifest.xml is correct.
But when use oracle jdk1.8 caused the problem,when I change it to openjdk 1.8 this problem solved.
Maybe you should check androidManifest.xml

**Comment by 2439905184** [comment]
Now I always use openjdk.
Because we can dowload this version freely.
And if you want to download oracle jdk, you must login to oracle account now.And accept some more 商业 lincenses.

**Comment by neoncube2** [comment]
Thanks! 🙂

I found a project that's similar to mine, so I guess I should try to compile it and see if it works 🙂  (https://github.com/Lamelynx/GodotGetImagePlugin-Android)
