### ISSUE TITLE
MSDF renders fonts with overlapping shapes incorrectly (not valid per OpenType standard)

### ISSUE THREAD

**Issue by DrCanvas** [godotengine/godot#52247]
### Godot version

v4.0.dev.calinou [d04aa9a11]

### System information

Windows 10

### Issue description

Visual artifacts appear on some characters when using MSDF option.
Font used: https://fonts.google.com/specimen/Inter
![Screenshot 132316](https://user-images.githubusercontent.com/65372494/131328292-33956759-42dd-440c-a9ab-d08bf081d35d.jpg)

### Steps to reproduce

Open the reproduction project below.

### Minimal reproduction project

[msdf_test.zip](https://github.com/godotengine/godot/files/7076257/msdf_test.zip)

**Comment by bruvzg** [comment]
For the reference, quoting my comment for the MSDF implementation:

> It's most likely an issue with the specific font. msdfgen is not good with handling self intersecting shapes when it's built without Skia (Skia is huge, and probably won't be integrated into Godot unless it's used for much more stuff than just MSDF generation), see Chlumsky/msdfgen#110.

AFAIK, curves that insect with themselves are not allowed by the OpenType standard, so this is an invalid font, I'm not sure whether we should fix it at all.

For example, FontForge gives multiple warnings when you try to validate this font.

<img width="582" alt="Screenshot 2021-08-31 at 13 13 30" src="https://user-images.githubusercontent.com/7645683/131485143-c06d4f8d-502a-428d-a22b-ac9fc1f280fe.png">
<img width="406" alt="Screenshot 2021-08-31 at 13 12 54" src="https://user-images.githubusercontent.com/7645683/131485181-d17454df-b320-4dc5-bb52-62c4c1a0638c.png">

**Comment by Calinou** [comment]
This is a known issue with the Inter font, although it appears there are no plans to fix it: https://github.com/rsms/inter/issues/343

**Comment by akien-mga** [comment]
I guess there's nothing we can/should do. Not sure where to document this if it's specific to this font, maybe this issue (once closed) will be sufficient as documentation?
