### ISSUE TITLE
Unable to build latest with Mono for X11

### ISSUE THREAD

**Issue by olestourko** [godotengine/godot#52268]
### Godot version

efc87481e45c66b3a18dfe1db82c3289fe2a370d

### System information

Ubuntu 20.04

### Issue description

I'm attempting to compile the latest version following the [documentation here](https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html) and getting stuck with the compilation error below.

I can compile successfully by checking out 3.3.3 stable plus the extra commit I'm interested in with `git cherry-pick`: https://github.com/godotengine/godot/commit/6db17a523e3747c489747d52de62790d9148d25d

Apologies in advance if there's an obvious reason for this, as I'm not familiar with C++ or its build tools. I believe I've satisfied all the dependencies listed [here](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html) and am at a dead end with this. My compiler is GCC 9.3.0.

```
scons: Reading SConscript files ...
Platform "x11" has been renamed to "linuxbsd" in Godot 4.0. Building for platform "linuxbsd".
Enabling ALSA
Enabling PulseAudio
D-Bus development libraries not found, disabling dependent features
Enabling udev support
Note: Building a debug binary (which will run slowly). Use `target=release_debug` to build an optimized release binary.

scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=0 to SConscript calls.
Missing SConscript 'modules/gdnative/xr/SCsub'
File "/home/censored/Documents/projects/godot/modules/gdnative/SCsub", line 20, in <module>
Mono root directory not found. Using pkg-config instead
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 40%] Compiling ==> modules/mono/editor/code_completion.cpp
modules/mono/editor/code_completion.cpp: In function 'PackedStringArray gdmono::get_code_completion(gdmono::CompletionKind, const String&)':
modules/mono/editor/code_completion.cpp:126:73: error: 'begin' was not declared in this scope; did you mean 'std::begin'?
  126 |     for (const KeyValue<StringName, ProjectSettings::AutoloadInfo> &E : autoloads) {
      |                                                                         ^~~~~~~~~
      |                                                                         std::begin
In file included from /usr/include/c++/9/string:54,
                 from /usr/include/c++/9/stdexcept:39,
                 from /usr/include/c++/9/array:39,
                 from /usr/include/c++/9/tuple:39,
                 from /usr/include/c++/9/mutex:38,
                 from ./core/os/mutex.h:39,
                 from ./core/string/string_name.h:34,
                 from ./core/string/node_path.h:34,
                 from ./core/variant/variant.h:46,
                 from modules/mono/editor/code_completion.h:35,
                 from modules/mono/editor/code_completion.cpp:31:
/usr/include/c++/9/bits/range_access.h:105:37: note: 'std::begin' declared here
  105 |   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
      |                                     ^~~~~
modules/mono/editor/code_completion.cpp:126:73: error: 'end' was not declared in this scope; did you mean 'std::end'?
  126 |     for (const KeyValue<StringName, ProjectSettings::AutoloadInfo> &E : autoloads) {
      |                                                                         ^~~~~~~~~
      |                                                                         std::end
In file included from /usr/include/c++/9/string:54,
                 from /usr/include/c++/9/stdexcept:39,
                 from /usr/include/c++/9/array:39,
                 from /usr/include/c++/9/tuple:39,
                 from /usr/include/c++/9/mutex:38,
                 from ./core/os/mutex.h:39,
                 from ./core/string/string_name.h:34,
                 from ./core/string/node_path.h:34,
                 from ./core/variant/variant.h:46,
                 from modules/mono/editor/code_completion.h:35,
                 from modules/mono/editor/code_completion.cpp:31:
/usr/include/c++/9/bits/range_access.h:107:37: note: 'std::end' declared here
  107 |   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
      |                                     ^~~
scons: *** [modules/mono/editor/code_completion.linuxbsd.tools.64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:03.641]
```

Possibly something about https://github.com/godotengine/godot/pull/52122?

### Steps to reproduce

Attempt to compile latest on Ubuntu 20.04.

**Comment by Calinou** [comment]
Reading the build log (especially the note about `x11` being renamed to `linuxbsd`, it looks like you're trying to build the `master` branch. Mono support is currently broken in the `master` branch.

**Comment by olestourko** [comment]
I am building from `master` instead of `3.3`, so makes sense. Thanks!

**Comment by raulsntos** [comment]
While it's true mono support in `master` is currently kinda broken, it was compiling fine for me a few days ago. I've looked into it and it seems it may have been broken because of PR #52122.

That PR changes the `autoloads` variable from `Map<StringName, ProjectSettings::AutoloadInfo>` to `OrderedHashMap<StringName, ProjectSettings::AutoloadInfo>` but since `OrderedHashMap` doesn't implement Range Iterators those for loops can't compile now.

**Comment by olestourko** [comment]
> While it's true mono support in `master` is currently kinda broken, it was compiling fine for me a few days ago. I've looked into it and it seems it may have been broken because of PR #52122.
> 
> That PR changes the `autoloads` variable from `Map<StringName, ProjectSettings::AutoloadInfo>` to `OrderedHashMap<StringName, ProjectSettings::AutoloadInfo>` but since `OrderedHashMap` doesn't implement Range Iterators those for loops can't compile now.

Yeah I was curious about that, I looked through the history of `code_completion.cpp` initially and noticed that recent change. Its strange that the automated build [succeeded](https://github.com/godotengine/godot/actions/runs/1173045423) though.

**Comment by raulsntos** [comment]
The CI only builds the editor (`tools=yes module_mono_enabled=no`) and the mono template (tools=no `module_mono_enabled=yes`), but the code that fails is only compiled when `tools=yes` and `module_mono_enabled=yes` because it's part of the mono module integration with the editor. So the automated build never compiled that class.

**Comment by raulsntos** [comment]
@olestourko you should be able to build now, let us know if you run into more issues

**Comment by olestourko** [comment]
> @olestourko you should be able to build now, let us know if you run into more issues

Awesome, thank you!
