### ISSUE TITLE
SCons 4.2.0 reports warning message: "Calling missing SConscript without error is deprecated"

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#52281]
### Godot version

4.0.dev (7ab78c4ca)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.57.02)

### Issue description

```
scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=False to SConscript calls.
```

### Steps to reproduce

Run `scons` in the Godot root directory with SCons 4.2.0 or later.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Missing SConscript is probably `modules/gdnative/xr/SCsub` which was removed in #52003, but still listed in the `modules/gdnative/SCsub`.

**Comment by Xrayez** [comment]
The `must_exist=False` is useful for optional user modules (lets say we have a `game` module which users could copy-paste directly into Godot source, and Godot would call `SConstript("game/SCSub", must_exist=False)`. But Godot does not use nor support this kind of approach so all calls to non-existing `SCSub` should likely be removed.
