### ISSUE TITLE
Godot can't find node that exists in scene tree

### ISSUE THREAD

**Issue by CosmicSpore** [godotengine/godot#52305]
### Godot version

3.3stable

### System information

Windows 10

### Issue description

I'm unsure exactly how to explain this...
I have one 'onready var' getting reference to a very basic label node, among many others, that one day suddenly decided to give an error message that it could no longer find the node, even though it was clearly in the scene tree and had been for a long time. I checked all spelling in case I accidentally edited it, rewrote the path several times just to be sure, and even dragged the node into the script. Nothing worked. It continued to tell me that it couldn't find the node.
Eventually I renamed the node and retyped the path to match, saved it, and like magic it works again...

Well today as I was helping others in the official Discord, someone else was having the exact same problem. And just like before, I told them how I renamed the node to get it to work again, and this fixed the issue for them as well. 
Seeing that the problem was identical to the one I had just a few days before I thought I should probably see if there was a ticket up for it and I couldn't find one, so I figured I should open one up even though I'm not sure how to reproduce this. This is at the very least a very frustrating problem to deal with as it seems to defy logic.

Also to note: when committing my project to git the same day, I had this issue: https://github.com/godotengine/godot/issues/48216 on some of my files (animations namely, but I didn't check everything). No idea if it is related but I thought it was worth mentioning as I'd never experienced either of these problems before that day.

### Steps to reproduce

Sadly I have no idea... Add a label, try to reference it in a script with 'onready var'... But this seems to be somewhat random / very rare as it obviously doesn't occur every time or even very often.

### Minimal reproduction project

Sorry, I wish I could but I've already resolved the issue and don't know how to reproduce it. :(
I'll try to get a copy of my project if it happens to come up again.

**Comment by pycbouh** [comment]
Without the steps or an MRP we can’t do anything about this report. Please open it with more detail when you have something we can investigate.
