### ISSUE TITLE
Premultiplied alpha to be supported on font import (old: smoothed text on the button)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#5231]
**Operating system or device - Godot version:**
Godot_v2.0.3_stable_win32

**Issue description** (what happened, and what was expected):

Text on the Button smoothed. As should be clear from a Label.
I made his Button and there is also smoothed text.

![godot_v2 2016-06-15 19-29-48-85](https://cloud.githubusercontent.com/assets/233268/16088589/80ca69d2-3330-11e6-946b-2a3e2dcfaaeb.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
it is not really smoothed, this is how alpha blending works. Godot supports
premultiplied alpha if you really want to avoid this situation, but as far
as I know font import does not support it.

How about we rename this issue or create a new one requesting premultiplied
alpha to be supported on font import? I promise to add it/fix it asap

**Comment by ret80** [comment]
Good. And can be renamed. Could you do it?

**Comment by ret80** [comment]
@reduz  - you can fix it?

**Comment by reduz** [comment]
just remember to set the label to use PMAlpha blend mode too

**Comment by ret80** [comment]
all I wanted it to 2.0.x version :(

**Comment by ret80** [comment]
but thanks anyway
