### ISSUE TITLE
Comment causes contents of folded methods to not hide (CodeEdit regression)

### ISSUE THREAD

**Issue by PrecisionRender** [godotengine/godot#52326]
### Godot version

v4.0.dev.calinou.036b7a098

### System information

Windows 10, Vulkan, Nvidia GeForce RTX 2060 Max-Q

### Issue description

When adding a comment in a method, any lines of code after the comment are not hidden when the method is folded. For instance, if you write a line of code, then write a comment on the next line to describe what the code does, then write some more code below the comment, and code below the comment will not be hidden when the method is folded. Images below:

![image](https://user-images.githubusercontent.com/89754713/131743796-d7d2c257-af80-4dec-892c-c909df4779e1.png)
![image](https://user-images.githubusercontent.com/89754713/131743886-54c30fb7-dd1e-447d-9659-227114751893.png)

### Steps to reproduce

1. Make a new script in Godot 4.0
2. In the `_ready()` function (or any other function), write a line of code
3. Below that code, make a comment
4. Below the comment, write another line of code
5. Fold the `_ready()` function

**Note:** I've tried this on arrays. It doesn't seem to be an issue with them.

### Minimal reproduction project

[Method Folding Issue.zip](https://github.com/godotengine/godot/files/7094375/Method.Folding.Issue.zip)

**Comment by Calinou** [comment]
cc @Paulb23

**Comment by jmb462** [comment]
The bug seems more complex.
Here, the same code doesn't fold the same way if there a function after or not

![bug](https://user-images.githubusercontent.com/3649998/132061557-6c13cc37-a5d7-4f8f-8dac-61772bf8f8ec.gif)
