### ISSUE TITLE
Shading language parser issue with retrieving vectors from matrices

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#5232]
Godot 2.0.3-stable

Looking at documentation on http://docs.godotengine.org/en/latest/reference/shading_language.html at the bottom of the page there is a "Obtaining world-space normal and position in material fragment program". The code does not work, seems like multiple vector extractions and swizzling is not supported properly. Also `mat3(INV_CAMERA_MATRIX)` does not work (invalid constructor argument).

`INV_CAMERA_MATRIX.w.xyz` does not work, while `(INV_CAMERA_MATRIX.w).xyz` is parsed properly.

Original code:

```
vec3 world_normal = NORMAL * mat3(INV_CAMERA_MATRIX);
vec3 world_pos = (VERTEX - INV_CAMERA_MATRIX.w.xyz) * mat3(INV_CAMERA_MATRIX);
```

Working code:

```
vec3 world_normal = NORMAL * mat3((INV_CAMERA_MATRIX.x).xyz, (INV_CAMERA_MATRIX.y).xyz, (INV_CAMERA_MATRIX.z).xyz);
vec3 world_pos = (VERTEX.xyz - (INV_CAMERA_MATRIX.w).xyz) * mat3((INV_CAMERA_MATRIX.x).xyz, (INV_CAMERA_MATRIX.y).xyz, (INV_CAMERA_MATRIX.z).xyz);
```

Also... after adding a `EMISSION = world_pos;` the result is still in screen-space... So I guess there's a parser and a documentation error here.

_EDIT:_
I did this in the fragment shader for a material, which is marked as "out" in the documentation... weird.

**Comment by Chaosus** [comment]
@akien-mga I guess this issue is obsolete, there is no such an example in shading_language.html anymore, and matrixes can now been builded from matrix of another dimension.

**Comment by vnen** [comment]
@Chaosus Thanks, closing as obsolete then.
