### ISSUE TITLE
Symbol lookup opens an editor documentation at wrong position

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#52335]
### Godot version

ebac430445ade41301e65508366217827cfc3574

### System information

Windows 10

### Issue description

![doc_bug](https://user-images.githubusercontent.com/3036176/131787640-c0e06de3-3b60-43fb-aa14-285d1ec447c6.gif)

### Steps to reproduce

^^

### Minimal reproduction project

Too easy to reproduce

**Comment by Calinou** [comment]
This is likely the same cause as https://github.com/godotengine/godot/issues/52124.
