### ISSUE TITLE
External editor exec flags can't be set

### ISSUE THREAD

**Issue by Pangeo-Alex** [godotengine/godot#52336]
### Godot version

4.0 dev (7ab78c)

### System information

Windows 10 (64-bit)

### Issue description

Trying to set text_editor/external/exec_flags by pasting in the UI displays a null in the input box, then disappears with the following error message in the output debug section:
  
```editor\editor_settings.cpp:191 - EditorSettings::_get - Property not found: text_editor/external/exec_flags```

![2021-09-02 08-37-34](https://user-images.githubusercontent.com/80619348/131803517-1d35c4b9-e3a8-4f0a-9e4d-348e04d90c32.gif)

### Steps to reproduce

1. Load up Godot 4.0 dev
2. Open Editor menu in top nav bar > go to Text Editor section > click External
3. Try an input anything via pasting ({project} --goto {file}:{line}:{col} is the desired input)
4. Errors

**Comment by Ev1lbl0w** [comment]
Introduced by https://github.com/godotengine/godot/pull/39404

The text is pasted firstly without issue, but when this code runs, it tried to paste the content of `property_clipboard`, which can be `null` by default.

This is happening on any `EditorPropertyText` actually:
![Peek 2021-09-03 11-07](https://user-images.githubusercontent.com/6501975/131988767-e6e4de3a-cefd-4526-8c34-3f1c5a2e00a7.gif)

I tried looking at the involved code but I can't find the issue; the event should be accepted, yet it's still being picked up later by a `_unhandled_key_input`:
https://github.com/godotengine/godot/blob/d20031ccaec4c9ff50bc718cb8d79eefba0d7f11/scene/gui/line_edit.cpp#L388-L392

cc @rcorre
