### ISSUE TITLE
When using setget on an exported Color variable in a tool script, the variable will always revert to it's default value when changed in the editor

### ISSUE THREAD

**Issue by lonevox** [godotengine/godot#52340]
### Godot version

3.4 beta 4 mono

### System information

Windows 10

### Issue description

When using setget on an exported Color variable in a tool script, the variable will always revert to it's default value when changed in the editor.

https://user-images.githubusercontent.com/38600896/131845583-03c79fe7-b0a3-4f37-ad05-022bb4442866.mp4

### Steps to reproduce

```gdscript
tool
extends Node


export(String) var text setget _set_text
func _set_text(new: String):
	text = new

export(Color, RGB) var color setget _set_color
func _set_color(new: String):
	color = new
```

This is all the code needed to show this bug. Color will now be unable to be changed to anything else in the editor, compared to a string which is perfectly fine.

### Minimal reproduction project

[SetgetToolColorBug.zip](https://github.com/godotengine/godot/files/7098962/SetgetToolColorBug.zip)

**Comment by kleonc** [comment]
Same for:
- `3.3.3.stable`,
- `3.3.stable`,
- `3.2.3.stable`,
- `3.2.stable`,
- `3.1.stable`.

**Comment by lonevox** [comment]
There's actually more to this problem. I accidentally have the _set_color parameter typed as string as you can see, which obviously fails to set it. But when I have the _set_text parameter typed as a Color (or anything else) it doesn't break and still let's me change the string in the editor. Maybe to remedy any typing problems here there should be some sort of editor feedback from this? It could be changed so that for setget you can only use the exported type or a type that extends from the exported type, otherwise the editor will show an error. I see no reason setget methods should receive anything other than their variable type or their derived classes.

**Comment by kleonc** [comment]
> There's actually more to this problem. I accidentally have the _set_color parameter typed as string as you can see, which obviously fails to set it. 

I need new eyes.

> But when I have the _set_text parameter typed as a Color (or anything else) it doesn't break and still let's me change the string in the editor. Maybe to remedy any typing problems here there should be some sort of editor feedback from this? It could be changed so that for setget you can only use the exported type or a type that extends from the exported type, otherwise the editor will show an error. I see no reason setget methods should receive anything other than their variable type or their derived classes.

In fact your variable isn't statically typed, AFAIK type isn't inferred from the export hint. Making that variable statically typed results in the error (whether it's exported or not doesn't really matter):
![6tIR7lwV4o](https://user-images.githubusercontent.com/9283098/131932643-20ebbc79-5691-4daa-853e-fed5f423ead8.png)
![Godot_v3 3 3-stable_win64_IxBOvMuUy8](https://user-images.githubusercontent.com/9283098/131932525-d78eb865-a0ae-41ce-a002-e02eb225eff4.png)
![nHtUt0519E](https://user-images.githubusercontent.com/9283098/131932646-b2cfff2a-4b74-43f1-acd6-8a79d55df48c.png)
![Dc9bwyof1D](https://user-images.githubusercontent.com/9283098/131932647-afffea45-bcf9-4cd5-ac3f-a151294c486a.png)

**Comment by lonevox** [comment]
You're right, I've just misunderstood export hints. I'll close this issue.
