### ISSUE TITLE
[platform/x11/crash_handler_x11.x11.opt.debug.aarch64.o]       execinfo.h not found

### ISSUE THREAD

**Issue by pranshuthegamer** [godotengine/godot#52355]
### Godot version

3.3

### System information

Android 10 with termux

### Issue description

While running scons, i get this error:
![Screenshot_2021-09-03-02-04-46-865_com termux](https://user-images.githubusercontent.com/61378895/131912767-fc5b8a2c-1a85-47d1-a484-f8f49e834a67.jpg)

### Steps to reproduce

Install termux from f-droid (play store version outdated)
Install python 3.5+
install scons with pip

NOTE: do this on android

run scons with `scons platform=server tools=no target=release_debug CCFLAGS="-mtune=cortex-a72 -mcpu=cortex-a72 -mfloat-abi=hard -mlittle-endian -munaligned-access -mfpu=neon-fp-armv8" -j4 module_webm_enabled=no arch=aarch64`

**Comment by Calinou** [comment]
Pass the `execinfo=no` SCons option when compiling (this disables the crash handler). See https://github.com/godotengine/godot/issues/20035.

**Comment by pranshuthegamer** [comment]
Passing that argument didnt work

**Comment by Calinou** [comment]
> Passing that argument didnt work

Can you join the [Godot Contributors Chat](https://chat.godotengine.org/) to discuss it there? GitHub issues aren't the best place to discuss this.

**Comment by akien-mga** [comment]
Building the `server` platform on Android is not supported.

**Comment by Calinou** [comment]
> Building the `server` platform on Android is not supported.

I think what OP is doing is building a `server` Linux binary on Android using a Linux environment (Termux).

**Comment by pranshuthegamer** [comment]
Yes ^^
