### ISSUE TITLE
Moving the mouse cursor on the script editor causes constant redrawing (unlike in `3.x`)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#52360]
### Godot version

4.0.dev (bb0122c93)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.57.02)

### Issue description

Moving the mouse cursor on the script editor causes constant redrawing (unlike in `3.x`). This results in increased CPU/GPU usage when using the script editor, which impacts power consumption and battery life negatively.

Look at the mouse cursor moving and the update spinner in the top-right corner:

https://user-images.githubusercontent.com/180032/131927412-138d6126-15f4-4745-a2a7-e1b8dfd65880.mp4

This does not occur in 3.4 beta4 (on the script editor itself at least – unnecessary redrawing still occurs when hovering the 2D editor tabs and PopupMenu items):

https://user-images.githubusercontent.com/180032/131927586-7093ee80-1b29-4123-b6b9-579ca7e62099.mp4

### Steps to reproduce

- Enable **Show Update Spinner** in the Editor Settings.
- Create a script.
- Move the mouse slowly. Notice how the spinner in the top-right corner will spin continuously when doing so, even if you don't click. In `3.x`, the spinner will only move slowly (twice a second) because of the caret blinking.

### Minimal reproduction project

N/A

**Comment by e8newallm** [comment]
This seems to be getting caused by a constant call to set_symbol_lookup_word_as_valid when the mouse is moving.

Going to pick this up and see if I can work out what the cause is.
