### ISSUE TITLE
Autoload Editor Plugin "main_screen_changed" signal not work

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#52373]
### Godot version

3.3 stable

### System information

windows 10

### Issue description

Singleton editor plugin in tool mode cannot emit signal "main_screen_changed" when change main screen in editor, while the other signal works well.

### Steps to reproduce

Add a editor plugin node, add it to autoload and set to tool mode. Connect the "main_screen_changed" signal when enter tree, then print something. Nothing happened

### Minimal reproduction project

[EditorSingletonChangeScene.zip](https://github.com/godotengine/godot/files/7104530/EditorSingletonChangeScene.zip)

**Comment by pycbouh** [comment]
> Add a editor plugin node, add it to autoload

I have to ask, why. This is not how you use editor plugins, they are a special class that is loaded with the project, and serve no purpose when you autoload them.

**Comment by KoBeWi** [comment]
This is wrong usage of plugins. A plugin needs to be registered properly (using the Plugins tab in the Project Settings), otherwise it's just some Node.
