### ISSUE TITLE
Variant class-reference

### ISSUE THREAD

**Issue by J08nY** [godotengine/godot#5237]
**Operating system or device - Godot version:**
Linux 4.5.0-kali1-amd64
`git master` 367aabf03080da8e4e72c9db56b0b2097c86d6b4

**Issue description** (what happened, and what was expected):
Class reference has many references to `Variant`(as a return type or argument), yet after clicking on this type in script editor reference, it opens an empty tab. This should be fixed, replaced by a page explaining what a Variant is.
![screenshot from 2016-06-15 22-19-41](https://cloud.githubusercontent.com/assets/1296726/16096199/346ab3c2-3348-11e6-9036-0cb8db4d6363.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by Ace-Dragon** [comment]
While we're at it, the built-in docs could use a sort of glossary that explains what a lot of the more unique argument types are (variant, parameters, what, ect...). Either that or change the argument type in the docs. to something more descriptive as to what is expected.

Then there's the fact that some classes still remain without any sort of documentation (like the one for the proximity node).

**Comment by vnen** [comment]
@Ace-Dragon:

> While we're at it, the built-in docs could use a sort of glossary that explains what a lot of the more unique argument types are (variant, parameters, what, ect...).

I think you meant "argument names"? Except for Variant, those are not "types" they are the "names" which follow the type. Usually the arguments to pass is explained in the function description (unless it's obvious). And, as always, some specific examples would help.

About the empty class documentation, it's just a matter of someone writing them.

**Comment by J08nY** [comment]
This issue is however more than just a missing class reference, it is about exposing the notion of what a Variant is to doctool/bindings, and the broader issue of letting a Variant return another Variant from a method as would be needed by(Array.pop_* #3763).

**Comment by vnen** [comment]
@J08nY yes, maybe it wasn't clear but I was talking about the other comment citing other empty classes (which we are aware: #3488). This Variant issue is another thing.

**Comment by reduz** [comment]
I made the docs generate Variant, you can document that it's a wildcard type and not meant to be used directly.

**Comment by vnen** [comment]
BTW `EditorExportPlatform` (used in `Editor{Import,Export}Plugin`) suffers the same problem, but I'm not sure if it should be solved the same way.
