### ISSUE TITLE
Godot 4.0: Tween node missing

### ISSUE THREAD

**Issue by jimbeauphloyd** [godotengine/godot#52382]
### Godot version

4.0 dev

### System information

Mac OS X

### Issue description

Tween node not found when adding a new node

### Steps to reproduce

Right click on node, click Add Child Node, search for Tween

![Screen Shot 2021-09-03 at 10 21 14 AM](https://user-images.githubusercontent.com/9885380/132029316-fd043d1f-949f-4ddb-92ee-30aad8c3fb6c.png)

**Comment by pycbouh** [comment]
Tweens are no longer a node. Refer to https://github.com/godotengine/godot/pull/41794
