### ISSUE TITLE
GDScript 2.0: get_object() on a Callable variable inside a class does not return a boolean equality correctly

### ISSUE THREAD

**Issue by jimbeauphloyd** [godotengine/godot#52380]
### Godot version

4.0 dev

### System information

Any System

### Issue description

When using a Callable variable inside a class, the get_object() returns the correct Node reference, but does not pass an equality test.

### Steps to reproduce

CallableContainer script:

```
extends Node
class_name CallableContainer

var callable: Callable
```

Test script:

```
extends Node

func _ready():
    var container = CallableContainer.new()
    container.callable = Callable(self, "test_method")
    print(container.callable.get_object(), " == ", self, " : ", (container.callable.get_object() == self))

func test_method():
    pass
```

Returns:
Test:[Node:29192356820] == Test:[Node:29192356820] : false

Expected:
Test:[Node:29192356820] == Test:[Node:29192356820] : true

You can see that the node references are identical, but the boolean equality returns false.

### Minimal reproduction project

[ObjectTest.zip](https://github.com/godotengine/godot/files/7106814/ObjectTest.zip)

**Comment by SheilaWarren** [comment]
One workaround (but not a fix) is to use get_instance_id() on each object.

```
container.callable.get_object().get_instance_id() == self.get_instance_id()
```

**Comment by vnen** [comment]
Can't reproduce in current master, might have been fixed along the way.
