### ISSUE TITLE
Add to node - ( OptionButton ) function to ( get_popup_menu() )

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#5238]
[improvement] add to node - ( OptionButton ) function to ( get_popup_menu() )
so you can get his pop-up menu

**Comment by AlexHolly** [comment]
This one?https://github.com/godotengine/godot/blob/b8087987723e5299635044b4dedcecb69426c43b/scene/gui/option_button.cpp#L249

**Comment by vnen** [comment]
As @AlexHolly said, there's such a function now. Closing as fixed.
