### ISSUE TITLE
Build Error (VS 2008)

### ISSUE THREAD

**Issue by TheCosmicGoat** [godotengine/godot#524]
I've been getting the following trivial build error after the last 2 source pulls using Visual Studio 2008 (9.0) express on MS Windows 7.0:

tools\editor\plugins\baked_light_baker.cpp(313) : error c2666: 'pow' : 6 overloads have similar conversions

Fortunately, its easily fixed by changing the second parameter of the 'pow' function on that line to an int - but I thought i'd better let someone know.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch? The PR linked above has not been merged yet.

**Comment by vnen** [comment]
Should we still support VS2008? There are 4 new major versions of Visual Studio—all of which have a free versions—and 2 pending PR's that'll fix the build for all of them (#2699 and #2748).

**Comment by akien-mga** [comment]
Has this issue has not seem much activity since 2014, I'll assume that people don't really need Godot to build in VS 2008, or it has been fixed already, so closing.
