### ISSUE TITLE
Converting a SpatialMaterial to ShaderMaterial resets "Local To Scene" flag

### ISSUE THREAD

**Issue by YellowAfterlife** [godotengine/godot#52402]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10 21H1

### Issue description

This makes for a slightly confusing experience given that if material uses a texture source that requires "local to scene" flag (e.g. ViewportTexture), the material will render fine in editor and appear black in-game

### Steps to reproduce

- Create a SpatialMaterial
- Tick the "Local To Scene" checkbox
- Pick "Convert to ShaderMaterial"
- Check if "Local To Scene" checkbox is still ticked

GIF:
![convert](https://user-images.githubusercontent.com/731492/132107023-fb8aa9f3-cdc0-4427-91f0-bcf0d70253ee.gif)

**Comment by Calinou** [comment]
This is likely because the conversion code creates a new resource, but doesn't carry over properties such as the resource name and Local To Scene.

**Comment by KoBeWi** [comment]
Most likely this affects all material types.
