### ISSUE TITLE
Vulkan: Rendering error with SpotLight and SDFGI

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#52411]
### Godot version

4.0.dev (0bdbce672c3c7b1894a6ac76cb2202966b05e735)

### System information

Windows 10, 1080 Ti

### Issue description

This happens when sdfgi is enabled.
if you add a spotlight directly as a child of the scene everything works ok.
when you add a scene with a spotlight this error strats popping up.
if we save this and restart the engine everything works ok, but if you open the spotlight scene and change anything the errors starts to show up again.

### Steps to reproduce

Make a 3d scene enable sdfgi, Make another 3d scene, add an spotlight.
Put that spotlight scene in to the first scene and you get this error.
![Skärmbild 2021-09-05 100656](https://user-images.githubusercontent.com/13393087/132120164-e229f39d-54ef-461e-b65a-0aadd5e972d8.png)

### Minimal reproduction project

[Godot4Spotlight.zip](https://github.com/godotengine/godot/files/7111214/Godot4Spotlight.zip)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/57840, which contains more information about the issue at hand.
