### ISSUE TITLE
Joypad Input Mapping does not recognize different between Positive and Negative

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#52419]
### Godot version

3.4.beta4

### System information

Windows 10, using Xbox One controller

### Issue description

In Godot, I add a Joypad Axis Left Stick **LEFT** action event, but the input system does not differentiate between positive and negative, so my action gets fired regardless.

### Steps to reproduce

1. Open new godot project
2. Plug in joypad and make sure Godot recognizes it
3. Add new action, with a Joypad Axis event set to your Joypad and an axis with a direction (positive or negative).
4. Hook up the action in the input events to print "hello world" for example.

Expected: "hello world" only prints when the right axis direction is pressed
Actual: "hello world" prints regardless of the direction

### Minimal reproduction project

It can be done with any godot project with a couple steps.

**Comment by jmb462** [comment]
I can't reproduce this issue neither in master branch nor the 3.x branch.
I'm using a 8bitdo gamepad with analog stick and Windows 10.

**Comment by Lucrecious** [comment]
I will post a minimal project soon, just been busy.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
