### ISSUE TITLE
[GDScript 2.0] Script cannot extend Reference

### ISSUE THREAD

**Issue by Kubulambula** [godotengine/godot#52424]
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

Any script cannot extend Reference
`Error at (0,0): Could not find base class "Reference".`

### Steps to reproduce

1. Create new script
2. Make it extend Reference

### Minimal reproduction project

[script_extend_issue.zip](https://github.com/godotengine/godot/files/7112185/script_extend_issue.zip)

**Comment by KoBeWi** [comment]
It was renamed to RefCounted.

**Comment by Kubulambula** [comment]
Must have slipped my mind. Thank you
