### ISSUE TITLE
C# export with Exp property hints don't show up properly in the inspector

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot#52428]
### Godot version

3.3.3.stable.mono

### System information

Windows 10

### Issue description

When using the property hint `ExpRange` A slider isn't used for the exported variable in the inspector. However it does with the GDScript equivalent. There's a similar issue with `ExpEasing` which has a curve editor, I think it's called that, but with the C# equivalent there isn't one. The C# code builds without errors so I assume it's correct, I've also had the C# discord channel look at this and they couldn't figure out what's going on.

### Steps to reproduce

use the `ExpRange` or `ExpEasing` property hints in a project.

### Minimal reproduction project

[C#Test.zip](https://github.com/godotengine/godot/files/7112854/C.Test.zip)

**Comment by kleonc** [comment]
> When using the property hint `ExpRange` A slider isn't used for the exported variable in the inspector. However it does with the GDScript equivalent. There's a similar issue with `ExpEasing` which has a curve editor, I think it's called that, but with the C# equivalent there isn't one.

In GDScript you're exporting floats, in C# you're exporting ints. So these are not equivalent. Changing int to float in C# will make them work the same.

**Comment by skyace65** [comment]
Thank you. I've made a PR to fix the 3.4 branch docs, and I'll look into the master branch. Closing this issue.
