### ISSUE TITLE
Can't copy errors from the error box

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#52421]
### Godot version

c6f6c05

### System information

W10

### Issue description

Example error:
```
func _ready():
	var sprite = Sprite2D.new()
	sprite.material = CanvasItemMaterial.new()
```
![image](https://user-images.githubusercontent.com/2223172/132136363-975b5f4f-2abc-410c-bafc-c36fceb10ef4.png)

### Steps to reproduce

1. Make script error
2. Click this button at the bottom: 
![image](https://user-images.githubusercontent.com/2223172/132136373-c65193a7-dad3-45f6-b176-ce3d383d0761.png)
3. Try to copy contents

**Comment by Ev1lbl0w** [comment]
Regression from #42595

The code inside `RichTextLabel::_get_line_text` is always returning an empty string despite the selection existing.

cc @bruvzg
