### ISSUE TITLE
`PropertyHint`s listed in `VisualScriptEditorVariableEdit` are out of sync

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#52434]
### Godot version

e5c6c773e99e3f9aae4ac8a804f392416c871285

### System information

N/A

### Issue description

Note sure what exactly is it used for, didn't dig into it. Noticed it because that's the only place where "ExpRange" still occurs:

https://github.com/godotengine/godot/blob/e5c6c773e99e3f9aae4ac8a804f392416c871285/modules/visual_script/visual_script_editor.cpp#L324-L325

https://github.com/godotengine/godot/blob/e5c6c773e99e3f9aae4ac8a804f392416c871285/doc/classes/%40GlobalScope.xml#L2239-L2356

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Xrayez** [comment]
I submitted a PR for this in the past: #43211.

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
