### ISSUE TITLE
Popover menus and tooltips rendering in the wrong position - MacOS with a secondary display (DisplayServer regression)

### ISSUE THREAD

**Issue by pablinos** [godotengine/godot#52432]
### Godot version

4.0.dev

### System information

macOS 11.5.2, Vulkan, Radeon Pro 560X 4 GB

### Issue description

When using a secondary display, if I right click on a item in the node inspector, the pop up menu appears in the wrong place.

<img width="2067" alt="image" src="https://user-images.githubusercontent.com/96462/132190770-0cd967b4-cf93-4eda-8142-1f8d536813b1.png">

The position changes if I resize the window, but is never in the correct place. Interestingly, this isn't an issue for other windows.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/96462/132191191-bf70c9fb-ed8c-4796-8d33-7296bba8471a.png">

Additionally tooltips appear in the wrong place, and a click is needed to dismiss them.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/96462/132191507-231cc4a7-9ae6-4d5e-ae93-11536a0e9261.png">

This could be a separate issue.

### Steps to reproduce

Using a build of the latest master, and a mac plugged into an external display (I'm using a LG Ultrafine, and I've seen some other issues with high definition displays, so it could be related), create a scene and right click on one of the signals in the Node panel.

Hover over one of the signals, to see the issue with the tooltips

**Comment by pablinos** [comment]
Note: This issue does not exist in 3.x

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/45740, except that issue is on Windows and likely needs a different fix.

**Comment by pablinos** [comment]
I've just got around to testing 4.0.alpha3, and this doesn't appear to be an issue anymore. I don't know if it was also fixed by #54645 or not.
