### ISSUE TITLE
Silence compiler warnings from external dependencies

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5244]
We should have SCons silence the compiler warnings related to external dependencies (openssl, theora, etc.).

Those warnings are not relevant for us as we won't touch the upstream source to fix them, they should be handled directly upstream. They also tend to make our Travis logs huge and sometimes I get stalled builds because of this verbosity.

**Comment by vnen** [comment]
I believe this is a matter of enabling warning suppression flags to the `env_drivers` environment in `drivers/SCsub`. This will remove warnings from `drivers/register_driver_types.cpp` too, but I guess it's manageable.

**Comment by akien-mga** [comment]
This still needs to be done btw. To avoid code duplication in all modules, there could be a `methods.py` method to disable warnings on a given env.

**Comment by Anutrix** [comment]
Any updates? Is this fixed?

**Comment by akien-mga** [comment]
Yes, fixed by #22506.
