### ISSUE TITLE
Normalmap on a generated Mesh does not work

### ISSUE THREAD

**Issue by Hannyson** [godotengine/godot#52444]
### Godot version

3.3.3

### System information

Archlinux GLES3 Nvidia Geforce GTX 1650 Super

### Issue description

On a generated mesh, a shader can't use normalmap

### Steps to reproduce

Generate a mesh through code, assign a shader to it

### Minimal reproduction project
https://ufile.io/chduihco

**Comment by robbertzzz** [comment]
Can confirm that this is happening for me on Godot 3.5.1 stable, Windows 10. The material I'm using works fine on default meshes, but it doesn't work on a generated mesh. I'm generating my mesh using ArrayMesh, vertex normals and UVs are set and work as intended. As soon as a normal map is assigned the mesh will just turn dark as if it's completely in shadows.
I've attached a minimal repro that I've confirmed has this issue in 3.5.1 stable.

[generated_mesh_normal_map.zip](https://github.com/godotengine/godot/files/9686079/generated_mesh_normal_map.zip)

**Comment by clayjohn** [comment]
> Can confirm that this is happening for me on Godot 3.5.1 stable, Windows 10. The material I'm using works fine on default meshes, but it doesn't work on a generated mesh. I'm generating my mesh using ArrayMesh, vertex normals and UVs are set and work as intended. As soon as a normal map is assigned the mesh will just turn dark as if it's completely in shadows. I've attached a minimal repro that I've confirmed has this issue in 3.5.1 stable.
> 
> [generated_mesh_normal_map.zip](https://github.com/godotengine/godot/files/9686079/generated_mesh_normal_map.zip)

Do you also generate per-vertex normals and tangents? You need normals and tangents for normal mapping to work correctly.

**Comment by robbertzzz** [comment]
> > Can confirm that this is happening for me on Godot 3.5.1 stable, Windows 10. The material I'm using works fine on default meshes, but it doesn't work on a generated mesh. I'm generating my mesh using ArrayMesh, vertex normals and UVs are set and work as intended. As soon as a normal map is assigned the mesh will just turn dark as if it's completely in shadows. I've attached a minimal repro that I've confirmed has this issue in 3.5.1 stable.
> > [generated_mesh_normal_map.zip](https://github.com/godotengine/godot/files/9686079/generated_mesh_normal_map.zip)
> 
> Do you also generate per-vertex normals and tangents? You need normals and tangents for normal mapping to work correctly.

Ah looks like missing tangents caused the issue. I'm surprised these are needed from my code, couldn't those just be generated when missing? From what I can recall I don't think they're needed in Unity when generating a mesh from arrays.

**Comment by robbertzzz** [comment]
Answering my own question here, ArrayMesh.regen_normalmaps() seems to do the job. We might need some better documentation there.

**Comment by clayjohn** [comment]
> Answering my own question here, ArrayMesh.regen_normalmaps() seems to do the job. We might need some better documentation there.

Absolutely, this is the sort of thing that should be mentioned multiple places so its a quick find.

**Comment by robbertzzz** [comment]
I think it should also be mentioned here: https://docs.godotengine.org/en/3.5/tutorials/3d/procedural_geometry/arraymesh.html
And I think [ArrayMesh.regen_normalmaps()](https://docs.godotengine.org/en/3.5/classes/class_arraymesh.html#class-arraymesh-method-regen-normalmaps) needs a better description. It doesn't regenerate normal maps (no textures are generated), it (re)generates any mesh data that's necessary to support normal maps.

**Comment by Calinou** [comment]
The method should be renamed to something else in 4.0, such as `regenerate_tangents`.

**Comment by Hannyson** [comment]
Don't have this problem this ages ago

**Comment by akien-mga** [comment]
You mean it's fixed in 4.0? Or you don't experience it anymore in 3.5.x?

**Comment by Hannyson** [comment]
I mean it's fixed in 4.0, I don't use 3.x anymore
