### ISSUE TITLE
Windows exclusive unicode bug

### ISSUE THREAD

**Issue by maksloboda** [godotengine/godot#52447]
### Godot version

3.3.3.stable, 3.3.2.stable

### System information

Windows or Ubuntu + wine

### Issue description

Windows build incorrectly works with some unicode symbols (tested on mac, windows and linux).

For example:
Having text with egyptian symbols wont work excusively on windows
Ubuntu:
![Screenshot from 2021-09-06 21-02-50](https://user-images.githubusercontent.com/26490401/132252020-d81e085a-583a-4eac-a6c9-7891c3b822f6.png)
unicode encoding as reported by the engine
![Screenshot from 2021-09-06 21-15-26](https://user-images.githubusercontent.com/26490401/132252050-ee273d48-a983-4c53-bf94-ed95d33ee6e5.png)
Windows:
![Screenshot from 2021-09-06 21-05-34](https://user-images.githubusercontent.com/26490401/132252062-9ce925b5-3724-4805-914a-08f7487a240c.png)
unicode encoding as reported by the engine
![Screenshot from 2021-09-06 21-15-15](https://user-images.githubusercontent.com/26490401/132252076-2d98f9f7-be27-498a-a59e-80fac5af3180.png)

 

### Steps to reproduce

1) Have an egyptian symbol in a string
1) Show string by priting bytes or using a label with a suffcient font
1) Verify that Windows and Linux show different strings

### Minimal reproduction project

[reproduction.zip](https://github.com/godotengine/godot/files/7117450/reproduction.zip)

**Comment by bruvzg** [comment]
Godot 3.x uses `wchar_t` for strings, on Windows it's 16-bit on other systems 32-bit, and Godot do not support UTF-16 surrogate pairs to handle characters outside of `0-ffff` with 16-bit char.

Godot 4.x use 32-bit `char32_t~ type on all platforms.

Changing char type in 3.x is breaking change and probably won't happen.

**Comment by aaronfranke** [comment]
As per @bruvzg's comment, this is fixed in master (what will be Godot 4.0), but can't be fixed in 3.x without breaking compatibility. If you need support for such characters we recommend upgrading to Godot 4.0 when it comes out. Closing.
