### ISSUE TITLE
Offset property for controls

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#5245]
**Operating system or device - Godot version:**
**Issue description** (what happened, and what was expected):
I think it would be very helpful to have ability to set Control origin point to the center, just like it's in Sprite2D node. Currently it's quite hard to make scale/rotation animations for controls, since they always will be rotated/scaled around the upper left corner. 
**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by SaracenOne** [comment]
I actually have support for this in my fork, so I could make a PR for it. Would probably like to polish it up first, but would definetly like to get it integrated since I'm using it for a lot of fancy new UI scaling features.

**Comment by reduz** [comment]
I think it's best to always assume, for GUI code, that the origin is in the
top left
that said, could try adding custom origin positioning for controls that you
can set using "v" like in Sprite or other nodes

**Comment by reduz** [comment]
I mean, there is rotation and scale now, offset could work. Saracen, does
your code include offset also?

**Comment by SaracenOne** [comment]
Yeah, my implementation does make that assumption about UI positioning and treats it the same. It only adds the offset to affect the scaling and rotation point, purely asethetic from a code position, but nessecary to accomplish a lot of things you would want to do with scaling and rotation.

**Comment by SaracenOne** [comment]
This was actually something I had in my first implementation, but was missing from the one which was actually added into the mainline, but it's something I forgot to mention. I still think it's very important to have to make this feature truly useful.

**Comment by reduz** [comment]
oh okay, if you want to make a PR adding this, also try to make sure to get
the "v" shortcut (or pivot set mode) to work to change pivot

**Comment by SaracenOne** [comment]
Sure, I'll try to get that polished up and get a PR for it soon. I may also like to release some scripts alongside it I've written which really show off how it can be used to make really nice scalable UIs which can also adapt effectively to multiple screen resolution and aspect ratios with ease.

**Comment by MarianoGnu** [comment]
Saracen what happens when the controls are inside of a Container? i supose offset is ignored along with Scale and Rotation.

**Comment by Zireael07** [comment]
Has there been any progress? I need to rotate a texture frame around it's center, and it rotates around one of the corners instead...

**Comment by reduz** [comment]
This should be added IMO as an offset property, together with scale and
rotate, changing origin to the center is not friendly with using it as a
GUI.

**Comment by reduz** [comment]
This was just added, closing.

**Comment by kubecz3k** [comment]
@reduz just tested, works beautifully! <3
