### ISSUE TITLE
Godot Web Editor does not respond to keyboard or mouse input

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#52468]
### Godot version

3.4.beta4

### System information

Windows 10, Google Chrome Browser

### Issue description

In this update, I cannot interact with anything in the editor whatsoever. The tab buttons at the top still work, and the engine is still running as evident to the fact that if you press the quit button beside the editor tab, the editor will still display a confirmation dialog.

### Steps to reproduce

Open or create any project and try to interact with the opened project GUI.

**Comment by Calinou** [comment]
Can you reproduce this in Firefox and Edge? Can you reproduce this in 3.4beta3 and older?

**Comment by SIsilicon** [comment]
I tried 3.4.beta3; it doesn't seem to have that issue.
I have Edge installed. I can test it there.

**Comment by snougo** [comment]
same issue in firefox on MacOS

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
I bisected the issue to https://github.com/godotengine/godot/pull/42220 .
Still trying to figure out a fix.
