### ISSUE TITLE
`.anim` file extension - not consistent with other `Resource` files?

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#52460]
### Godot version

3.0+

### System information

N/A

### Issue description

`Resource`s use the extension `.res`/`.tres`, except in the case of animations, where the extension is `.anim`. This seems to be inconsistent with the rest of `Resources`.

### Steps to reproduce

N/A

**Comment by Calinou** [comment]
There are still many binary formats with custom extensions such as `.material`. I'm not sure if we should remove them in favor of `.res` for 4.0, but this is better discussed in a proposal.

**Comment by akien-mga** [comment]
Yes this is more material for a proposal that should review the extensions used in all resource types (search `RES_BASE_EXTENSION`).
