### ISSUE TITLE
[TRACKER] External libraries and their versions

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5248]
This issue is meant to keep track of all external libraries that we embed in our source tree with their version, and for comparison's sake the current upstream version and/or latest upstream version of the same stable branch.

As upstream projects continue updating their libraries regularly, we'll keep this tracker around and use different issues (linked here) to handle specific updates.

---
## Core

| Library | Path | Local version | Upstream version | Update needed |
| --- | --- | --- | --- | --- |
| [aes256](http://www.literatecode.com/aes256) | core/io/aes256.* | 2011 | 2011 | No |
| [base64](http://episec.com/people/edelkind/c.html) | core/io/base64.* | ? | ? | Check |
| [fastlz](https://code.google.com/archive/p/fastlz) | core/io/fastlz.* | svn | svn | No |
| [hq2x](https://github.com/brunexgeek/hqx) | core/hq2x.cpp | git (2016, modified) | git (2016) | No |
| [md5]() | core/io/md5.* | ? | ? | Check |
| [minizip](http://www.winimage.com/zLibDll/minizip.html) | core/io/{crypt.h,ioapi.\*,unzip.\*,zip.\*} | 1.1 (2010) | ? (contrib in zlib) | Yes |
| [sha256](https://github.com/ilvn/SHA256) | core/io/sha256.* | 2015 | 2015 | No |
| [smaz](https://github.com/antirez/smaz) | core/compressed_translation.cpp | git (2012) | git (2012) | No |
| [triangulator](https://github.com/ivanfratric/polypartition/blob/master/src/polypartition.cpp) (polypartition) | core/math/triangulator.* | ? | git (2015) | Check |

## Drivers

| Library | Path | Local version | Upstream version | Update needed |
| --- | --- | --- | --- | --- |
| Box2D Polygon/Triangle? | drivers/convex_decomp | ? (2007) | ? | Check |

## Modules

| Library | Path | Local version | Upstream version | Update needed |
| --- | --- | --- | --- | --- |
| [cURL](https://curl.haxx.se/) (only snippets) | modules/openssl/{curl_hostcheck.*, stream_peer_openssl.cpp} | ? (2013) | 7.50.3 (2016) | Check |
| [ENet](http://enet.bespin.org) | modules/enet | git master (mid August 2016) | 1.3.13 | No |
## Platform

**Android**

Android Open Source Project / Google:
- `java/aidl/com/android/vending/billing` (duplicate), `java/com/android/vending/billing` (2012)
- `java/com/android/vending/licensing`
- `java/com/google/android/vending/expansion/downloader`
- `java/org/godotengine/godot/input/InputManager*`
- `android_native_app_glue.*`
- `cpu-features.*`

libjingle / Google:
- `ifaddrs_android.*`

**BlackBerry 10**
- `bbutil.*`

**UWP**
- `include/`
- `app.*`

## Scene
- `scene/resources/mikktspace.*` (2011)
- `scene/resources/stb_truetype.h` v1.11 (2015)

## Servers

**Physics**

Bullet:
- `servers/physics/gjk_epa.cpp` (snippet)

Chipmunk:
- `servers/physics/joints_sw.cpp` (snippet)
- `servers/physics/joints_2d_sw.cpp` (snippet)

## Thirdparty

| Library | Path | Local version | Upstream version | Update needed |
| --- | --- | --- | --- | --- |
| [FreeType](https://www.freetype.org/) | thirdparty/freetype | 2.6.5 | 2.7.2 (2016) | Yes |
| [GLEW](http://glew.sourceforge.net/) | thirdparty/glew | 1.13.0 | 2.0 (2016) | Yes (2.1 only) |
| [jpgd](https://github.com/richgel999/jpeg-compressor) (jpeg-compressor) | thirdparty/jpeg-compressor | 1.04 | 1.04 (2012) | No |
| [libmpcdec](https://www.musepack.net/index.php?pg=src) | thirdparty/libmpcdec | SVN snapshot between 1.2.6 and SV8 | 1.2.6 (deprec.), SV8 (r475) | Check |
| [libogg](http://www.xiph.org/downloads/) | thirdparty/libogg | 1.3.2 | 1.3.2 (2014) | No |
| [libpng](http://www.libpng.org/pub/png/libpng.html) | thirdparty/libpng | 1.6.28 | 1.6.28 (2016) | No |
| [libsquish](https://code.google.com/archive/p/libsquish) | thirdparty/squish | ? | 1.11 (2011, some more recent SVN commits) | Check |
| [libtheora](http://www.xiph.org/downloads/) | thirdparty/libtheora | 1.1.1 | 1.1.1 (2010) | No |
| [libvorbis](http://www.xiph.org/downloads/) | thirdparty/libvorbis | 1.3.5 | 1.3.5 (2015) | No |
| [libwebp](https://chromium.googlesource.com/webm/libwebp) | thirdparty/libwebp | 0.5.2 | 0.5.2 (2016) | No |
| [OpenSSL](https://www.openssl.org/) | thirdparty/openssl | 1.0.2h | 1.0.2j and 1.1.0c (2016) | Yes |
| [opus](http://www.opus-codec.org/) | thirdparty/opus | 1.1.3 | 1.1.3 (2016) | No |
| [opusfile](http://www.opus-codec.org/) | thirdparty/opus | 0.8 | 0.8 (2016) | No |
| [pvrtccompressor](https://bitbucket.org/jthlim/pvrtccompressor) | thirdparty/pvrtccompressor | hg tip | hg tip (2015) | No |
| [rg_etc1](https://github.com/richgel999/rg-etc1) | thirdparty/rg-etc1 | 1.04 | 1.04 (2013) | No |
| [RtAudio](https://www.music.mcgill.ca/~gary/rtaudio/) | thirdparty/rtaudio | 4.1.2 | 4.1.2 (2016) | No |
| [zlib](http://zlib.net/) | thirdparty/zlib | 1.2.10 | 1.2.10 (2016) | No |

## Tools
- `tools/certs/ca-certificates.crt`

**Comment by volzhs** [comment]
java sources under ``java/com/google/android/vending/expansion/downloader`` are updated with #4729.
it's referenced latest commit from https://github.com/danikula/Google-Play-Expansion-File

**Comment by volzhs** [comment]
OpenSSL 1.1.0 release. https://www.openssl.org/source/

**Comment by vnen** [comment]
[SHA256](https://github.com/godotengine/godot/blob/master/core/io/sha256.h) is missing on the list. It comes from here: http://www.literatecode.com/aes256. Also, OpenSSL has such function, is it needed to rely on a separate library?

**Comment by akien-mga** [comment]
> SHA256 is missing on the list. It comes from here: http://www.literatecode.com/aes256.

Actually I can't find its source there, only the AES256 library from the same author that we're also using. @bojidar-bg?

> Also, OpenSSL has such function, is it needed to rely on a separate library?

That's what I asked when it was first introduced, but my call was not heeded :)

**Comment by bojidar-bg** [comment]
@akien-mga Given what I starred, it should be https://github.com/ilvn/SHA256

**Comment by akien-mga** [comment]
Thanks, edited the OP accordingly.

**Comment by vnen** [comment]
I actually had problems with this SHA256 implementation, it was changing bits in memory that it shouldn't. Should I open an issue about this? I don't really know how to reproduce since I was doing it from C++.

**Comment by volzhs** [comment]
Freetype 2.7 has been released :)

**Comment by akien-mga** [comment]
Everything is now properly tracked in the `thirdparty` folder and its README.md, so closing.
