### ISSUE TITLE
A problem of Sprite3d disappearing

### ISSUE THREAD

**Issue by jdusart** [godotengine/godot#52487]
### Godot version

3.3.3.stable

### System information

Ubuntu, Mesa Intel® Xe Graphics (TGL GT2), GLES3

### Issue description

I have a small scene with just a character (a KinematicBody with a Sprite3d and a Camera attached) and a plane (a MeshInstance) that acts as floor. When I move my character away, it will disappear if both the transparent option of the Sprite3d and the alpha channel of the material of the plane are active.

### Steps to reproduce

I have upload a minimal project with the problematic setting. You can move the character with the up key.
On my computer:
- if the sprite is transparent and the alpha channel of the material of the plane has an input then after a bit of movement the character disappears
- if the sprite is not transparent or the alpha channel of the material of the plane has no input then the character does not disappear

### Minimal reproduction project

[MinBug.zip](https://github.com/godotengine/godot/files/7127406/MinBug.zip)

**Comment by Calinou** [comment]
This is a known limitation of alpha transparency sorting. Sorting has been improved in 3.4 beta 4, but we can't guarantee that it will work in all situations (as in other game engines).
