### ISSUE TITLE
VS14.0 compilation error C2466: cannot allocate an array of constant size 0

### ISSUE THREAD

**Issue by ranmaru90** [godotengine/godot#5249]
**Operating system or device - Godot version:**
Windows 10 Pro - Godot's source from GitHub, commit f0d9245ecf981dada4595da0e525cc95a0caf785

**Issue description** (what happened, and what was expected):
When trying to compile using the Visual Studio command prompt:

scons platform=windows target=release_debug tools=yes

failed with error messages:

d:\devworkfolder\godot\git_repos_godot\godot\scene\resources\default_theme\font_lodpi.inc(199): error C2466: cannot allocate an array of constant size 0
d:\devworkfolder\godot\git_repos_godot\godot\scene\resources\default_theme\font_lodpi.inc(200): error C2466: cannot allocate an array of constant size 0
d:\devworkfolder\godot\git_repos_godot\godot\scene\resources\default_theme\font_hidpi.inc(199): error C2466: cannot allocate an array of constant size 0
d:\devworkfolder\godot\git_repos_godot\godot\scene\resources\default_theme\font_hidpi.inc(200): error C2466: cannot allocate an array of constant size 0
scons: *** [scene\resources\default_theme\default_theme.windows.opt.tools.32.obj] Error 2
scons: building terminated because of errors.

**Steps to reproduce:**
1. Checkout commit f0d9245ecf981dada4595da0e525cc95a0caf785
2. vcvarsall.bat && scons platform=windows target=release_debug tools=yes

**Comment by Alex-doc** [comment]
same here.

**Comment by ranmaru90** [comment]
Thank you.
