### ISSUE TITLE
Skybox rotation support

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#525]
Mostly useful in Y axis to change direction of the sun, but probably someone in future will find use case for other axis as well. :)

**Comment by bojidar-bg** [comment]
Tagging for 3.0, for the new renderer :)

**Comment by avril-gh** [comment]
duplicate of _3D WorldEnvironment-CubeMap rotation_ #5619

> but probably someone in future will find use case for other axis as well.

allready found some in the past :)
- i thought about moving sky full of stars at night,
- moving slowly sky with clouds at day. (so it look more real, not static)
- also theres more awesome ideas than just sky
example of rotated skybox in both axis as magic FX in Final Fantasy VII https://www.youtube.com/watch?v=sv9aI5RkoeQ

it could be definitely useful feature

**Comment by reduz** [comment]
Problem of this feature is the cost of having to add an extra transform in the fragment program for the reflections. The only possibility of adding this is by not making it real-time (as in, radiance needs to be regenerated if angle changes).

In any case, postponing to 3.1

**Comment by n-pigeon** [comment]
This was feature request for old renderer, it could be a bit outdated. If it's too big cost for new renderer maybe it is better to not do this.

Current workflows in games is to make procedural shader with sun that handles sun position. Clouds are just huge spheres with could texture that rotates, or has it's own procedural shader.

**Comment by n-pigeon** [comment]
This was feature request for old renderer, it could be a bit outdated. If it's too big cost for new renderer maybe it is better to not do this.

Current workflows in games is to make procedural shader with sun that handles sun position. Clouds are just huge spheres with could texture that rotates, or has it's own procedural shader.
