### ISSUE TITLE
Weird bug with InputEvent.is_action_pressed()

### ISSUE THREAD

**Issue by fmenozzi** [godotengine/godot#52506]
### Godot version

3.3.3.stable

### System information

Ubuntu 18.04

### Issue description

Under some circumstances involving multiple keys being pressed at once, `InputEvent.is_action_pressed()` can incorrectly return `false` for one of them even though the key bound to that input action is being pressed. In my testing, I can reproduce this with sequences involving three keys, but only for some key combinations.

### Steps to reproduce

Open the reproduction project and run the main scene. Notice the two white labels "Z" and "X". Press Z (corresponding to custom action "action_z") and you'll see its label turn green on press and back to white on release. Similarly for X (corresponding to custom action "action_x").

If you just press and release Z and/or X, you should get correct behavior. The problem arises when a third key is pressed in between. For example, hold W and then hold Z: notice that Z turns green as expected. Now hold X (without letting go of either of the first two keys): notice that X does NOT turn green: `InputEvent.is_action_pressed()` is incorrectly returning false in this case.

What's weird is that this only happens with SOME keys. For example, replacing W above with D does not reproduce the issue. In my brief testing, Q, W, A, S, 1, 2, ~, Tab, and CapsLock are all problematic third keys, but most other keys seem to be fine.

### Minimal reproduction project

[input-bug-minimum-reproduction-project.zip](https://github.com/godotengine/godot/files/7132625/input-bug-minimum-reproduction-project.zip)

**Comment by ellenhp** [comment]
You could be running into a key rollover issue with your keyboard. Can you reproduce the issue here? http://gadzikowski.com/nkeyrollover.html

**Comment by fmenozzi** [comment]
Ok wow. I can reproduce this there. I guess it must be an issue with my keyboard then (probably physical for such a weird pattern though). Thanks for the link!

**Comment by ellenhp** [comment]
That's totally normal! My macbook keyboard displays the same behavior. It has to do with a cost-saving measure they use to manufacture keyboards. Keyboards are rarely built with a digital input pin devoted to each key, so they use a bunch of diodes to build a circuit that allows them to scan `N` keys with `<N` digital inputs. Needless to say, this results in some compromises.

https://deskthority.net/wiki/Rollover,_blocking_and_ghosting
