### ISSUE TITLE
Paths with "//" instead of "/" works in editor but not in export

### ISSUE THREAD

**Issue by gdesecrate** [godotengine/godot#52507]
### Godot version

3.3.3.stable

### System information

Manjaro 21.1.1 Pahvo, GLES2, Radeon RX 5500 XT (NAVI14, DRM 3.40.0, 5.10.60-1-MANJARO, LLVM 12.0.1)

### Issue description

If you use "//" in file name instead of "/" while in editor and run - all works fine.
If you export project - it would won't work anymore.

Accidentally hit this issue because I was constructing file path with string operations.

### Steps to reproduce

1) Use "//" instead of "/" in address on file, like "res://folder//folder//folder//icon.png"
2) use this address to load() something
3) It would work while running from editor
4) It won't work after export

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/7132792/New.Game.Project.zip)

**Comment by aleksfadini** [comment]
Is there any workaround that comes to mind?

I ran into this issue in a singleton where I preload all the assets in a fold with a loop similar to this:

`
[...]
		elif file.ends_with(".mp3"):
			var loop=preload("res://"+file)
			if file.begins_with("Drums"):
				drum_loops.append(loop)
[...]

`

How do I avoid using the double slash and getting the same result?
Nothing gets loaded in the exported file on android or osx. I'm a bit desperate

**Comment by Calinou** [comment]
> Is there any workaround that comes to mind?

`.replace("//", "/")` should do the trick :slightly_smiling_face:

**Comment by aleksfadini** [comment]
Didn't seem to do the trick reliably.

`file.replace("//", "/")` seem to crash the app on mac OS export, and resources just won't load on android.
It used to work before, and my mobile app is in production. Panic!
Any other idea?
