### ISSUE TITLE
EditorPlugin panel not compatible with tilemap editor panel

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#52514]
### Godot version

3.3stable

### System information

window10 pro

### Issue description

![image](https://user-images.githubusercontent.com/9168814/132708030-c247f7fa-62f7-4803-9735-89cf97c0bcc2.png)
When use add_control_to_container(CONTAINER_CANVAS_EDITOR_SIDE_LEFT, EditorPanel), add a custom editor panel to canvas editor, the tilemap editor panel not show on the right way, whether set it on left or right. Seems the panel is NOT on left or right to the canvas editor viewport, but below it.

### Steps to reproduce

Add a custom panel to the canvas editor by editor plugin, then edit a tilemap, you will see tile selector not show on the right place

### Minimal reproduction project

[PluginPanelBug.zip](https://github.com/godotengine/godot/files/7137553/PluginPanelBug.zip)

**Comment by kleonc** [comment]
Same in `3.4.beta3`, same for `GridMap`. It possibly happens for any node having such side panel, would be good to list all such nodes.
